### ISSUE TITLE
工程化支持

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#10]
1. 初始化
2. 默认和自定义构建配置
3. 调试
4. 构建

**Comment by sorrycc** [comment]
@afc163 请 review 下 https://github.com/ant-design/antd 。

**Comment by afc163** [comment]
:+1: 

改名成 `antd-cli` 吧，目前这个库就叫 `antd`。

**Comment by yiminghe** [comment]
为啥要单独写代码，现在代码重复太严重了  spmm chair-react, ant-bin,

ant-bin 完全可以依赖 spm-client ，加个支持 node_modules 读取就行了

**Comment by sorrycc** [comment]
@yiminghe 实现不一样的，差很多。

**Comment by sorrycc** [comment]
@yiminghe 偏右的要求是这个库的实现会尽量简单，只在 webpack 上做最简单的封装，很薄的一层，目前除了 entry 没其他配置。

**Comment by sorrycc** [comment]
@afc163 改名 antd-bin 后，命令行依赖是 `antd` ?

**Comment by afc163** [comment]
可以啊，我的想法是直接 require 到 ant-design 下好了。

**Comment by sorrycc** [comment]
和 @afc163 讨论了下，改名叫 `antd-bin`，然后不提供 `antd` 命令 (因为容易和 antd 的库混淆)，而是直接提供 `antd-init`, `antd-server` 和 `antd-build` 三个命令。
