### ISSUE TITLE
Ant Design Runtime Theme Update

### ISSUE THREAD

**Issue by mzohaibqc** [ant-design/ant-design#10007]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It allows one to update color specific theme in browser

There are guidelines to override Ant Design theme here https://ant.design/docs/react/customize-theme but these solutions need to be done at build time 
and one can't change at runtime, in browser. There are multiple issues open or closed which want such functionality. In some web projects, we need different color scheme/theme, different logo for different customers. We can change logo url for each customer but creating a separate build with specific theme (colors) and deploying is not ideal. So why not just save color variables and their values and apply them at runtime while page is loading. 
 

### What does the proposed API look like?
Demo: https://mzohaibqc.github.io/antd-live-theme/
Guide: https://ant.design/docs/react/customize-theme

I've setup a guide and a github source repository for demo here https://github.com/mzohaibqc/antd-live-theme.
There is a file `generate-color.js` which reads ant design less files, our own custom styless (less files), `variables.less` and `theme.less` to generate a `color.less` which actually contains only color related css rules to override theme of website or app. Similar technique is being used at Ant Design website but only for one color i.e `@primary-color`.

So point of this issue is to add this guide https://medium.com/@mzohaib.qc/ant-design-live-theme-588233ea2bbc  in `Customize Theme` page https://ant.design/docs/react/customize-theme so that other people who want such functionality can benefit from this.

Thanks in advance :)

**Comment by mzohaibqc** [comment]
@yesmeck I've created a new package https://github.com/mzohaibqc/react-app-rewire-antd-theme which can be installed using npm 
```
npm install react-app-rewire-antd-theme
```
and can be used like this in `config-overrides.js` file
```js
const path = require('path');
const { updateConfig } = require('react-app-rewire-antd-theme');

const options = {
  varFile: path.join(__dirname, './src/styles/variables.less'),
  stylesDir: path.join(__dirname, './src/styles'),
  antDir: path.join(__dirname, './node_modules/antd'),
  // colorFilePath: path.join(__dirname, './public/color.less'),
  themeVariables: ['@primary-color', '@secondry-color', '@text-color-secondary']
}
module.exports = function override(config, env) {
  config = updateConfig(config, env, options)
  return config;
};```

Now there is no need to add extra npm scripts to watch less files and regenerate `color.less` file

**Comment by yesmeck** [comment]
@mzohaibqc Great job, is it possible to write a webpack plugin to make it more generic?

**Comment by mzohaibqc** [comment]
@yesmeck I am not expert at webpack but I'll look into that. Nothing is impossible. If we can imagine, we can achieve.

**Comment by mzohaibqc** [comment]
@yesmeck  I've created a webpack plugin called `antd-theme-webpack-plugin`

npm: https://www.npmjs.com/package/antd-theme-webpack-plugin 
Github: https://github.com/mzohaibqc/antd-theme-webpack-plugin
to generate color.less and inject in `index.html` file. Now there is no need to add `color.less` and `less.js` in `index.html` manually. Plugin will add both reference automatically. We need to setup antd (e.g. less-loader etc) and then add this plugin in plugins array.
```const AntDesignThemePlugin = require('antd-theme-webpack-plugin');
 
const options = {
  stylesDir: path.join(__dirname, './src/styles'),
  antDir: path.join(__dirname, './node_modules/antd'),
  varFile: path.join(__dirname, './src/styles/variables.less'),
  mainLessFile: path.join(__dirname, '../../src/styles/index.less'),
  themeVariables: ['@primary-color'],
  indexFileName: 'index.html'
}
 
const themePlugin = new AntDesignThemePlugin(options);
// in config object
plugins: [
    themePlugin
  ]```

With app generated by `create-react-app`, we can add this plugin in `config-overrides.js` file 

```const themePlugin = new AntDesignThemePlugin(options);
module.exports = function override(config, env) {
  config = rewireLess.withLoaderOptions({
    modifyVars: getLessVars(options.varFile)
  })(config, env);
  config = injectBabelPlugin(['import', { libraryName: 'antd', style: true }], config);
  config.plugins.push(themePlugin);
  return config;
};```

I'll add example projects in github repository so it would be easier for others to follow, however it is very simple ...

I hope you will like it :)

**Comment by mzohaibqc** [comment]
@yesmeck I've added example in gitgub repo, how to use this `antd-theme-webpack-plugin` here https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/master/examples

Is it good enough now to be added in Ant Design Docs? What else is required to make it part of docs? Or you think that it's not something people will use.. Let me know about your thoughts .
Looking forward to your reply :)

**Comment by mzohaibqc** [comment]
@afc163 What do you think about this? Kindly have a look at this

Demo: https://antd-live-theme.firebaseapp.com/
Guide: https://medium.com/@mzohaib.qc/ant-design-dynamic-runtime-theme-1f9a1a030ba0

**Comment by yesmeck** [comment]
@mzohaibqc Great, need to find some time to migrate the theme picker of https://ant.design to your webpack plugin, or can you open a PR? PR of docs are welcome as well.

**Comment by mzohaibqc** [comment]
@yesmeck I did not get this `migrate the theme picker of https://ant.design to your webpack plugin`. What do you mean by theme picker and it's migration to webpack plugin? I would love to to create a PR. Kindly let me know what needs do :)

**Comment by yesmeck** [comment]
@mzohaibqc I mean using the  `antd-theme-webpack-plugin` to replace the https://github.com/ant-design/ant-design/blob/master/scripts/generateColorLess.js

**Comment by mzohaibqc** [comment]
@chenshuai2144 that is a suggestion which requires changes on ant-design side and will support only few themes. This #10007 approach is different and it is on end-user side.

**Comment by chenshuai2144** [comment]
He can already meet the simple use.
I think ok

**Comment by rezamorav** [comment]
I have a Project using Sass and Ant Design and I am using antd-scss-theme-plugin plugin to override ant design default variables.
Any suggestion how can I implement dynamic theme update?

**Comment by mzohaibqc** [comment]
@rezamorav I was in same situation when I was asked that we need dynamic theming and I was using sass alongside Ant Design. I could not find a solution so I created one with initial seed from Ant Design repo, how they were updating `@primary-color`.  If you can migrate you sass styles to less then you can use https://github.com/mzohaibqc/antd-theme-webpack-plugin to update theme dynamically and if you don't have luxury to take this decision the you can use https://github.com/mzohaibqc/css-runtime-theme post build. It will not be that good as `antd-webpack-plugin` but you can create a `color.less file containing color specific css rules and colors will be repalced with respective color variables e.g. `@primary-color`. 
```
const options = {
    source: path.join(__dirname, './src/index.css'), // File or css string,
    variables: { 
        '@primary-color': '#343312'
    },
    stylesDir: path.join(__dirname, './src'), // if your styles are in multiple files, specifiy the directory
    output: path.join(__dirname, './dist/color.less'), // output file path, filename should have .less extension and folder should be there,
    withoutGrey: false, // set to true to remove rules that only have grey colors
    withoutMonochrome: false, // set to true to remove rules that only have grey, black, or white colors
};

generateTheme(options).then(less => {
  console.log('Theme generated successfully');
})
.catch(error => {
  console.log('Error', error);
});
```

In order to handle different shades of `@primary-color` or any other color, you first need to calculate color for that shade and then add mapping here. e.g.  By default Ant design `@primary-color` is `@blue-6` which is equal to `#1890ff`. If you want to replace `@blue-5` as well, you first need to calculate that color and then add mapping. e.g that turns out to be `#1780fe` then you can apply builtin less methods like `soften`, `darken`, `spin` to achieve that color. this color is `spin(#1890ff, 4) = #1780fe` . You can calculate this from here https://www.ofcodeandcolor.com/cuttle/. This is not that simple but possible
```
const options = {
    source: path.join(__dirname, './src/index.css'), // File or css string,
    variables: { 
        '@primary-color': '#1890ff',
       'spin(@primary-color, 4)': '#1780fe'
    },
    stylesDir: path.join(__dirname, './src'), // if your styles are in multiple files, specifiy the directory
    output: path.join(__dirname, './dist/color.less'), // output file path, filename should have .less extension and folder should be there,
    withoutGrey: false, // set to true to remove rules that only have grey colors
    withoutMonochrome: false, // set to true to remove rules that only have grey, black, or white colors
};
```

**Comment by prakashmallow** [comment]
antd 4 custom theme is configured with antd.less after all .less style files are more times appended on DOM. How to fix this issue in nextjs with module federations.
