### ISSUE TITLE
Setting refs in Form children not compatible with React.createRef()

### ISSUE THREAD

**Issue by fibbers** [ant-design/ant-design#10006]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Linux, Chrome 65

### Reproduction link
[https://codepen.io/fibbers/pen/XEGojx](https://codepen.io/fibbers/pen/XEGojx)

### Steps to reproduce
When using React 16.3's [`React.createRef`](https://reactjs.org/docs/refs-and-the-dom.html#creating-refs) and passing this to an `Input` _inside a `Form`_, the `ref` is parsed as either a `String` or a `function`.
However, `React.createRef` creates an object. This causes an error (see the browser-console in the Codepen).

### What is expected?
No error, just using the passed `ref`

### What is actually happening?
The error isn't thrown when using an `Input` outside of a `Form`, see https://codepen.io/fibbers/pen/KoEGoO.

---
It seems the error is caused by rc-form's [`createBaseForm`](https://github.com/react-component/form/blob/183d2b40e025cac1d61cf42fe3e18af7227f7248/src/createBaseForm.js#L334), however I wasn't able to reproduce it with just rc-form.

**Comment by emersonlaurentino** [comment]
Hey @fibbers are you still having this problem? I could not reproduce it.

**Comment by afc163** [comment]
After upgrade react and antd to latest version in codepen, error is gone: https://codepen.io/afc163-1472555193/pen/yLNKgQR
