### ISSUE TITLE
Menu horizontal doesn't have caret-down animated icon. Menu inline does.

### ISSUE THREAD

**Issue by johnunclesam** [ant-design/ant-design#10005]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Latest everything

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/)

### Steps to reproduce
`<Menu mode="horizontal">`

### What is expected?

It should be the caret-down animated icon also in `horizontal Menu`.

### What is actually happening?

It is not present in `horizontal Menu`.

**Horizontal / inline**:
![image](https://user-images.githubusercontent.com/21275217/38619954-a4cef50e-3d9d-11e8-9448-80f66f91c276.png)

**Comment by johnunclesam** [comment]
@ant-design-bot this is not a Component: Icon tag. But Menu instead. Thanks.

**Comment by afc163** [comment]
It is by designed.

**Comment by johnunclesam** [comment]
@afc163 yes. I know. I was wondering why? And if we could make it... Because it makes sense.
