### ISSUE TITLE
Form: Validation Rules of type integer, number etc. do not work (TypeScript) 

### ISSUE THREAD

**Issue by k3flo** [ant-design/ant-design#10003]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
react 16.2.0, antd 3.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7ypr904701)

### Steps to reproduce
Change the value 50 to another number. For Example: 51

### What is expected?
There shouldn't be a validation error, because 51 is number and it is between 0 and 100.

### What is actually happening?
Produces 'testNumber is not a number' for any number provided in input field.

**Comment by k3flo** [comment]
https://codesandbox.io/s/5nk16768p

**Comment by yesmeck** [comment]
The type of Input value is a string, you need to convert it to a number using `getValueFromEvent`.

**Comment by k3flo** [comment]
For those who are interested i've implemented a working example:
https://codesandbox.io/s/7wyorykwp0

**Comment by HuYuee** [comment]
@k3flo this is a address to fix it .[address](https://github.com/ant-design/ant-design/issues/731)

**Comment by tagnja** [comment]
You can use regular expressions to validate integers, numbers etc. 

For example: 

```
{
  pattern: '^([-]?[1-9][0-9]*|0)$',
  message: "请输入整数"
}
```
