### ISSUE TITLE
TokenSeparators doesn't work in "multiple" mode in Select

### ISSUE THREAD

**Issue by apieceofbart** [ant-design/ant-design#10001]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Ubuntu, Chrome 65

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ko859ppy0r)

### Steps to reproduce
I forked the "Automatic tokenization"  example from docs: https://ant.design/components/select/
Documentation says it should work for "tags" and "multiple" mode. I changed mode to "multiple" - it doesn't work

### What is expected?
I expect the same behaviour as in docs for "tags" mode: when I copy multiple values separated by token they should appear in text field

### What is actually happening?
Nothing - the values are not copied and copied text dissappears

**Comment by yesmeck** [comment]
When you using `multiple`, the value you input should exist in the options list. Try input `a10,`

**Comment by apieceofbart** [comment]
@yesmeck what if I want to fetch data from somewhere? `onChange` handler is not fired
I guess I need to tokenize by myself?

**Comment by softboy99** [comment]
Hi,
does it support "Automatic tokenization" in multiple mode? i'm confused? i wish it can be used in both "multiple" and "token".

![Image](https://github.com/user-attachments/assets/8d4f1858-0302-414a-b85d-1f83310b7e71)


![Image](https://github.com/user-attachments/assets/4a0a472d-5bae-4f5a-b27f-02dd2974cc37)
