### ISSUE TITLE
ToolTip position anomaly

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#10010]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Win 10； Chrome 65.0.3325.181； The official website；https://ant.design/components/tooltip-cn/

### Reproduction link
[https://ant.design/components/tooltip-cn/](https://ant.design/components/tooltip-cn/)

### Steps to reproduce
First hover Tooltip is normal，after  position anomaly

### What is expected?
Tooltip Normal position

### What is actually happening?
ToolTip position anomaly

**Comment by chillyistkult** [comment]
I can confirm the issue. But its only happening in production.
