### ISSUE TITLE
Tag: prefixCls not passed to Icon

### ISSUE THREAD

**Issue by dalwlad** [ant-design/ant-design#10017]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Window 7 x64, Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zl5k64v8yp)

### Steps to reproduce
1. Import `Tag` component on demand
```javascript
import Tag from 'antd/lib/tag'
```
2. Do **NOT** import ~~'antd/dist/antd.css';~~
3. Pass a custom `prefixCls` to the `Tag` component
```javascript
<Tag closable prefixCls="custom-tag" />
```
4. Open a browser dev console and inspect the html for the tag. The tag will have the `class="custom-tag"`, but the `<i>` element for the icon will still have `class="anticon anticon-cross"`

### What is expected?
`prefixCls` should be passed to `Icon` component so that if one chooses not to use ant design styles and provide their own, they can use the custom `prefixCls` to style the icon as well, without the need of using `antd` default `prefixCls`

### What is actually happening?
`prefixCls` is not passed to `Icon` component

**Comment by dalwlad** [comment]
I think the component label is wrong: this is an issue of the `Tag` component, not of `Icon` component

**Comment by yesmeck** [comment]
#10855
