### ISSUE TITLE
Select 组件 multiple 模式怎么屏蔽 backspace 会删除已选中选项的功能

### ISSUE THREAD

**Issue by elowes** [ant-design/ant-design#10016]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为如果输入了错的字符，删除的时候，如果多按了一下 backspace，就会删除掉已经选中的选项

### What does the proposed API look like?
可以扩展 Select 上的 onInputKeyDown 方法
``` jsx
<Select 
    onInputKeyDown={e => {
        if (e.keyCode === 8 && e.target.value.length === 0) {
            e.stopPropagation()
        }
    }}
/>
```

**Comment by mattwalter91** [comment]
@elowes - Did you ever find a solution for this?

**Comment by zombieJ** [comment]
Maybe we can add delay when user just cleanup the input to avoid miss delete selectedValue.

**Comment by elowes** [comment]
> @elowes - Did you ever find a solution for this?
Sorry, I give it up :)

**Comment by afc163** [comment]
Duplicate of #15392

**Comment by boolak** [comment]
I can not avoid remove tag through extend onInputKeyDonw when pressing backspace.
