### ISSUE TITLE
ToolTips组件第二次展示时发生偏移

### ISSUE THREAD

**Issue by MangGoDio** [ant-design/ant-design#10015]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Steps to reproduce
第二次点击ToolTips

### What is expected?
ToolTips正常显示

### What is actually happening?
网站上所有用到的工具提示组件的地方，第一次打开即加入DOM树时显示的位置是正常的，然后关闭，第二次打开的弹窗位置则会发生向左或左上方一定距离的偏移
且开发环境并没有此问题，一旦打包压缩代码至正式环境就发生这种神秘的错误
想不出什么具体的原因，请问开发人员有碰过此类情况吗，以及工具提示的定位机制

**Comment by afc163** [comment]
Duplicate of #10008

**Comment by chillyistkult** [comment]
I can confirm the issue and it is not solved by #10008
