### ISSUE TITLE
DatePicker 组件如果选择了显示时间 showTime， 是否在最终显示上把时间也显示出来？

### ISSUE THREAD

**Issue by xinganng** [ant-design/ant-design#1001]
这个是范例， 尽管选择了时间，但结果显示时只有日期：

function onChange(value) {
  console.log('选择了时间：', value);
}

ReactDOM.render(
<DatePicker showTime format="yyyy-MM-dd HH:mm:ss" onChange={onChange} style={{ width: 160 }} />
, mountNode);

**Comment by benjycui** [comment]
http://ant.design/components/date-picker/#picker-demo-time
