### ISSUE TITLE
Tooltip is undefined on first load

### ISSUE THREAD

**Issue by mquandalle** [ant-design/ant-design#10027]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Linux, Chrome & Firefox

### Reproduction link
[https://gist.github.com/mquandalle/3e832e304ffeef0834954303119ee6da](https://gist.github.com/mquandalle/3e832e304ffeef0834954303119ee6da)

### Steps to reproduce
```js
import Tooltip from "antd/lib/tooltip";
console.log(Tooltip);
```

### What is expected?
We expect Tooltip to be a React Component immediately after importing it

### What is actually happening?
Tooltip is undefined

**Comment by dengfuping** [comment]
@mquandalle `import Tooltip from "antd/lib/tooltip";` => `import { Tooltip } from 'antd';`

**Comment by mquandalle** [comment]
The problem with this issue is that it is non-deterministic. Sometimes `Tooltip` is loaded immediately and sometimes it is undefined for a few milliseconds. I don't have that issue with other `antd` components. Also using `import { Tooltip } from 'antd';` doesn't solve the problem.

**Comment by mquandalle** [comment]
This is this bug: https://github.com/react-component/tooltip/issues/120

**Comment by yesmeck** [comment]
@mquandalle Could create a reproduction repo?
