### ISSUE TITLE
表格功能比较弱

### ISSUE THREAD

**Issue by hexian** [ant-design/ant-design#10020]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望增加如下3个功能:
1. 表格列中可以插入图标(对应可以绑定事件)
2.表格包含一个固定的搜索列
3.表格字段过多无法展示更多信息时，希望可以有一个隐藏部分来辅助展示更多的信息。
因为无法上传图片，您可以访问如下地址查看： http://www.zdysoft.com/1.png

### What does the proposed API look like?
这个我还达不到设计api的级别，哈哈哈。

**Comment by yesmeck** [comment]
> 表格列中可以插入图标(对应可以绑定事件)

`column[render]`

> 表格包含一个固定的搜索列

参考 https://preview.pro.ant.design/#/list/table-list

> 表格字段过多无法展示更多信息时，希望可以有一个隐藏部分来辅助展示更多的信息。

可以用固定列。

欢迎提出更加具体的建议。
