### ISSUE TITLE
select多选选中超过输入框长度，下拉列表遮住了选中项

### ISSUE THREAD

**Issue by NsNe** [ant-design/ant-design#10024]
Version
3.4.1

Environment
chrome65.0.3325.181

Reproduction link
https://ant.design/components/select-cn/#components-select-demo-tags

Steps to reproduce
选中多个，超过一行

What is expected?
不遮住，下拉列表相应下移

What is actually happening?
选中多个，超过一行，下拉列表遮住选中的项

**Comment by afc163** [comment]
Duplicate of #9905
