### ISSUE TITLE
Table add renderRow prop

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design#10025]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
编辑功能可以通过 renderRow 返回一个 Form 来实现。
现在的编辑写起来很累人，而且不支持 From 组件。 

### What does the proposed API look like?
 `renderRow=( record, index , row) => ReactNode`

**Comment by yesmeck** [comment]
举个详细点的例子对比下，用 `renderRow` 哪里方便？

**Comment by chenshuai2144** [comment]
```
<Table
  renderRow={(record, index, row) => {
    if (record.id !== this.state.editId) {
      return;
    }
    return (
      <From>
        <tr>
          {row.children.map(item => {
            return (
              <td>
                <FromItem />
              </td>
            );
          })}
        </tr>
      </From>
    );
  }}
/>;

```

**Comment by yesmeck** [comment]
这个 API 不好设计，用自定义 `components` 实现的例子：https://codesandbox.io/s/9l922ox7xo

**Comment by chenshuai2144** [comment]
我加个 demo 到官方示例上面吧。

**Comment by yesmeck** [comment]
可以把原来那个重写下

**Comment by 2678041235** [comment]
但是这个需要加一个操作列编辑按钮，在我们的产品业务中要求出现操作列，希望之间点击行的时候整行可以变成可编辑状态，点击当前行之外的可以触发保存。现在的困难是无法监听到当前行之外的其他区域的点击事件，比如表格之外的区域。大神们有什么好的建议么？
