### ISSUE TITLE
RangePicker: allow using RangeCalendar separately

### ISSUE THREAD

**Issue by kirzyka** [ant-design/ant-design#10034]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We need to use RangeCalendar without RangePicker. For example we have ag-grid and we want to useRangePicker in our date filters to select date range.
Currently there are no possibility to show RangeCalendar directly, without RangePicker.

### What does the proposed API look like?
Access to RangeCalendar directly or have an option to hide RangePicker

**Comment by afc163** [comment]
You can try http://github.com/react-component/calendar

**Comment by akob** [comment]
Guys, you already use it, we do not want to have two instances of the same library and track changes bot in ant design and react-component. We just want to have one nice library but with opportunities to use all existing features of related libraties
