### ISSUE TITLE
如何与后端服务关联起来呢？

### ISSUE THREAD

**Issue by think2011** [ant-design/ant-design#1003]
纯前端我已经跑起来，使用了示例中的`antd-init`初始化项目。

目前前端是由`npm run dev`启动起来的，后端又是由自己的服务启动的，还没有任何关联，两者如何关联起来开发呢？

请问有相关的示例吗？

**Comment by azhenge** [comment]
当然是通过请求服务端请求啦,  请求json/xml/text 都可以

**Comment by think2011** [comment]
我现在用koa, koa再配合`webpack-dev-middleware`，这样能实现只启动一个服务。

不过react hot reload还没搞定，一直报错 `hmre The following modules couldn't be hot updated:..`

**Comment by wenshiqi0** [comment]
不清楚你说的关联时什么意思，如果是后台接口就是json这种，还有就是后台来渲染前端，koa有相关的渲染方案，就要看你是否要模版和使用什么模版了，另外antd的issue应该不是问这一类问题的，可以去cnode或者stackoverflow问这类问题
