### ISSUE TITLE
Affix固钉组件，在手机端ios系统uc浏览器下有问题，建议用position: sticky属性解决

### ISSUE THREAD

**Issue by moonlu** [ant-design/ant-design#10035]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
手机端ios系统uc浏览器

### Reproduction link
[https://ant.design/components/affix-cn/](https://ant.design/components/affix-cn/)

### Steps to reproduce
略

### What is expected?
略

### What is actually happening?
略

**Comment by afc163** [comment]
不建议在手机端使用 antd。
