### ISSUE TITLE
Upload - Dragger: Pass prefixCls to UploadList - Upload

### ISSUE THREAD

**Issue by dalwlad** [ant-design/ant-design#10042]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Window 7 x64, Google Chrome Version 65.0.3325.181 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oj8xr145vy)

### Steps to reproduce
1. Import `Upload` component on demand
```javascript
import Upload from 'antd/lib/upload';

const {Dragger} = Upload;
```
2. Do **NOT** import ant design styles ~~'antd/dist/antd.css'~~
3. Pass a custom `prefixCls` to `Dragger` component
```javascript
import Upload from 'antd/lib/upload';

const {Dragger} = Upload;

const uploadProps = {
  name : 'file',
  multiple : true,
  action : '//jsonplaceholder.typicode.com/posts/',
  prefixCls : 'my-class',
  onChange(info) {
    const status = info.file.status;

    if (status !== 'uploading') {
      console.log(info.file, info.fileList);
    }
    if (status === 'done') {
      console.log('done');
    } else if (status === 'error') {
      console.error('Error');
    }
  }
};

React.render((
  <Dragger {...uploadProps}>
    <p className="my-class-drag-icon">
      <Icon type="inbox" />
    </p>
    <p className="my-class-text">Click or drag file to this area to upload</p>
    <p className="my-class-hint">
      Support for a single or bulk upload. Strictly prohibit from uploading company data or other band files
    </p> 
  </Dragger>
), document.getElementById('app'));
```

Running the code, inspecting the HTML will show that for the upload list, `ant-upload` class attribute is not overriden by the `prefixCls` prop.

### What is expected?
`prefixCls` should pe passed to `UploadList` component when used with `Dragger` upload component.

### What is actually happening?
`prefixCls` provided on `Dragger` component is not passed to `UploadList` component

**Comment by dalwlad** [comment]
The `Component` label is wrong - it should be `Component: Upload`

**Comment by yesmeck** [comment]
#10855
