### ISSUE TITLE
Ability to disable `Pager` on `Pagination`

### ISSUE THREAD

**Issue by MrSaints** [ant-design/ant-design#10044]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

The pagination component is heavily oriented towards "Offset-style Pagination" (see https://dev-blog.apollodata.com/understanding-pagination-rest-graphql-and-relay-b10f835549e7 for an overview of different types of pagination). There is nothing wrong with that. However, there are cases where the end-user experience necessitates a "Cursor-style Pagination", i.e. infinite loading of a stream of real-time data, and in such a case, page numbering (or the `Pager`) does not really work because we do not know the "cursor" for every page.

### What does the proposed API look like?

I believe this requires a change on https://github.com/react-component/pagination as well. I propose a new prop like `showPager` (taking inspiration from how the other props are named). To preserve compatibility with existing uses of `Pagination`, I also propose the default value be set to `true`. I understand that it is not *too difficult* to mimic a simple next / previous pagination via buttons, but having this option is more convenient for end-users (i.e. the developers).

Having a closer look at the API, I believe disabling the `Pager` alone might not be sufficient to achieve cursor-style pagination as it still has some knowledge of a "page number" in other parts.

**Comment by dengfuping** [comment]
@MrSaints If you don't want to display `pagination` in `Table`, just set `pagination={false}`.

**Comment by MrSaints** [comment]
@dengfuping I do want to display it, just not without the pager.

**Comment by dengfuping** [comment]
@MrSaints I don't understand what the `pager` means. Could you give a sample image to show it?

**Comment by dengfuping** [comment]
@MrSaints If so, there is no need to display `Next page` and `Previous page` that means not to display pagination. I couldn't figure out what the application scenarios are still.

**Comment by MrSaints** [comment]
> @MrSaints If so, there is no need to display Next page and Previous page that means not to display pagination. I couldn't figure out what the application scenarios are still.

@dengfuping What's your reasoning behind that?

 As my original post stated, it is not _too difficult_ to micmic a simple next / previous pagination via buttons, but it is perhaps even simpler to just have an option to disable the pager or to build support for cursor pagination.

You can find application scenarios almost everywhere where _pagination is done right_ (not using the conventional offset / limit). Reddit for example:

<img width="257" alt="screen shot 2018-04-16 at 08 28 01" src="https://user-images.githubusercontent.com/68859/38798571-df0e4d72-4159-11e8-9157-60db8e4801c4.png">

**Comment by dengfuping** [comment]
@MrSaints If the pager is not displayed, we couldn't know which page we are browsing. In the sample of `Reddit`, there are order numbers to show which page we are browsing implicit.

**Comment by MrSaints** [comment]
> @MrSaints If the pager is not displayed, we couldn't know which page we are browsing.

In the case of cursor pagination, why do you want to know which page you are browsing? That said, it can still be done without having an interactive pager (see https://react-table.js.org/#/story/simple-table for example, you can disable the "jump to page").

The number in the case of Reddit is not necessarily the "order" number, it is more like the "rank". Try changing the `count`, and refreshing, it will be "different" after a while. I think we need to be careful not to conflate pagination with numbers we see on list items.

**Comment by DeadcatDev** [comment]
+1 for this @MrSaints i need it too. When You have small table with like 1-4 pages i really don't need pagers and don't want it at all. 

PS. Moreover i need option for count 'results' not pages like  from "page 1/3" => "posts 1-10/27" so i will ask for it too but better will be just to add item renderer as it is done for 'next/page/prev' items in pagination API.

**Comment by annjawn** [comment]
The quick and dirty solution is to simply hide the stuff between the `<` and `>` arrows

```css
.ant-pagination-item,
.ant-pagination-jump-next,
.ant-pagination-jump-prev {
    display: none;
}
```

**Comment by liho98** [comment]
In order to preserved the prev and next button, im using this trick thanks @annjawn 
```
.ant-pagination-item {
    display: none!important;
}
```

I think cursor pagination should be supported because cursor pagination is more popular than offset-based paging. In most cases, you may not even know which page to browse, so classification is important. In order to improve performance, cursor pagination should be adapted. Unless you have powerful servers to help you perform offset-based pagination, such as Google search engine.

我觉得应该支持光标分页，因为光标分页比基于偏移的分页技术更加流行，在大多数的情况下，您甚至可能不知道要浏览哪个页面，所以分类很重要，为了提高性能，我们应该适应基于光标分页技术。 除非您有强大的服务器来帮助您执行基于偏移量的分页，例如Google搜索引擎。

**Comment by mathieu-anderson** [comment]
Excellent point raised by @MrSaints, was very puzzled to see the hoops one needs to jump through to implement the kind of pagination presented in the original issue. I hope this issue will not say inactive, as the CSS workaround is less than ideal.

**Comment by siwalikm** [comment]
@dengfuping I had a similar use-case to solve and came across this, any reason why this wasn't picked up over the past years?

Can i work on a fix and raise a PR for this? (thinking of a boolean pagination-prop which would not render the pager)

**Comment by IgorSobol** [comment]
Why not just give the decision on which pagination to choose on the side of your users? Now with the pagination cursor, I have to use hacks to solve the problem. And it could have been done by default. Why was it not accepted in the latest updates? This is an obvious problem.

**Comment by IlyaKrapivnoy** [comment]
how can I disabled pagination at that moment when the user clicks on it and till I got a response from the server?

**Comment by nmoinvaz** [comment]
Here is a custom component I made that uses cursor pagination for anybody who needs one now.
https://gist.github.com/nmoinvaz/b54e48969ccad25b047bc9fffcb38def
