### ISSUE TITLE
0.12.1中RangePicker未显示时间,0.11.3正常

### ISSUE THREAD

**Issue by dqaria** [ant-design/ant-design#1005]
0.12.1:
![image](https://cloud.githubusercontent.com/assets/1285675/13031801/f8e71532-d313-11e5-822e-31cda12dc2a5.png)
0.11.3:
![image](https://cloud.githubusercontent.com/assets/1285675/13031804/04dd7b6a-d314-11e5-8a67-2324bdccf554.png)

**Comment by ZXiner** [comment]
0.12.1DataPicker 中时间也未显示
