### ISSUE TITLE
Using DatePicker with Form FormItem

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [ant-design/ant-design#10058]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
mac os

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
wrap DatePicker inside FormItem

### What is expected?
        <FormItem {...formItemLayout} label="Publish Date">
          {getFieldDecorator('publishDate', {
            initialValue: '',
            rules: [
              {
                required: false,
                message: 'Please input publishDate',
                whitespace: true,
              },
            ],
          })(<DatePicker onChange={onChange} />)}
        </FormItem>

supposed to work seamlessly

### What is actually happening?
        <FormItem {...formItemLayout} label="Publish Date">
          {getFieldDecorator('publishDate', {
            initialValue: '',
            rules: [
              {
                required: false,
                message: 'Please input publishDate',
                whitespace: true,
              },
            ],
          })(<DatePicker onChange={onChange} />)}
        </FormItem>

doesn't work.  I get async validator saying 'publishDate is not a string'. 

so I'm using it this way as a temporary solution.
        <FormItem {...formItemLayout} label="Publish Date">
          {getFieldDecorator('publishDate', {
            initialValue: getCurrentDate(),
            rules: [
              {
                required: false,
                message: 'Please input publishDate',
                whitespace: true,
              },
            ],
          })}
          <DatePicker onChange={onChange} />
        </FormItem>

any help ? thanks in advance!

**Comment by afc163** [comment]
The type of DatePicker[value] in moment object, not string. So basicly your temporary solution is correct and recommended solution.
