### ISSUE TITLE
Move offcial site to netlify.com

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#10067]
To avoid China GFW.

---

现在 ant.design 把网站部署在 gh-pages 上，使用阿里云新加坡机房做了加速代理。但是由于中国互联网原因，ip 经常被墙。考虑部署到 netlify.com 等提供的静态站点服务（如果不会被墙的话）。

**Comment by yesmeck** [comment]
问题是被墙的是 gh-pages 还是新加坡服务器

**Comment by afc163** [comment]
是新加坡服务器

**Comment by afc163** [comment]
done

看一段时间效果。
