### ISSUE TITLE
v0.12 使用 Form 提供的校验功能代替 Validation如何考虑的

### ISSUE THREAD

**Issue by singba** [ant-design/ant-design#1007]
感觉比以前用起来更复杂，一些应该是组件内部完成的，是我理解错了吗
createForm、form={this.props.form}、getFieldProps

**Comment by afc163** [comment]
你比较过就知道原来的写法更麻烦：http://011x.ant.design/components/validation

**Comment by azhenge** [comment]
我想把每个表单域和validator作为一组, 放单独的jsx文件里, 动态组装表单, 现在可以支持了吗

**Comment by benjycui** [comment]
@azhenge 把 `this.props.form` 传过去就行，可以参考下这个 [例子](http://react-component.github.io/form/examples/overview.html).

**Comment by singba** [comment]
@afc163  我目前只用了校验提示，没有用表单校验例子的那种方式，

**Comment by benjycui** [comment]
@singba 如果只是需要校验，何不直接使用 [async-validator](https://github.com/yiminghe/async-validator)?

**Comment by singba** [comment]
@benjycui  谢谢，我不知道，学习了
