### ISSUE TITLE
upload组件上传文件时，后端无法获取文件内容

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#10078]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如下是核心代码：
<Upload
          action={UPLOAD}
          listType="picture-card"
          fileList={fileList}
          multiple={true}
          onPreview={this.handlePreview}
          onChange={this.handleChange}
          beforeUpload={this.checkType}
          headers={{
            'X-Requested-With': null,
            'Content-Type': 'multipart/form-data'
          }}
          data={{
            token:
              "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVUaW1lIjoxNTIzNDA5NDIxLCJ1c2VySWQiOiIzNGQwN2JhODU0ZDM1NWZmOWIyZDFkNWE3MGVmMDljOSJ9.LgP3Z_pQ8I5JNUkBGNBdrq2V2OkLftqqWu3hUTU67v8"
          }}
        >
          {fileList.length >= max ? null : uploadButton}
        </Upload>

如下是报文：
------WebKitFormBoundaryWqory19CoefOyhRu
Content-Disposition: form-data; name="token"

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjcmVhdGVUaW1lIjoxNTIzNDA5NDIxLCJ1c2VySWQiOiIzNGQwN2JhODU0ZDM1NWZmOWIyZDFkNWE3MGVmMDljOSJ9.LgP3Z_pQ8I5JNUkBGNBdrq2V2OkLftqqWu3hUTU67v8
------WebKitFormBoundaryWqory19CoefOyhRu
Content-Disposition: form-data; name="file"; filename="Lighthouse.jpg"
Content-Type: image/jpeg

------WebKitFormBoundaryWqory19CoefOyhRu--
文件内容为什么为空呢？

### What does the proposed API look like?
如何获取文件内容

**Comment by bobbychan** [comment]
请问楼主解决了吗？我上传的时候文件内容也是空的

**Comment by gametheworld** [comment]
兄弟我也是上传后，后端request.file中没有文件，但是请求头中看到当前上传文件的大小，躁动啊。。。。用符文编辑器调相同的接口能获取到看到文件

**Comment by Tommy-White** [comment]
There is one case needs be care for is that if you passing a string to name property of the Upload Component, the backend parameter name must also be consistent with it.
like below:
```
//The shortcut of the front end usage 
<Upload name="thumbnail"
   action={`${hostPort}/xxx/upload`}
   accept="image/*"
/>
```

```
// The shortcut of backend will like this :
@RequestMapping("/xxx/upload")
    public string upload(MutipartFile thumbnail....
```
* Notice that 'name' can be omit and the default value is ‘file’.
