### ISSUE TITLE
Do not exclude 'rowKey' from props of row component of table 

### ISSUE THREAD

**Issue by kirrosh** [ant-design/ant-design#10076]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to create table with 2 different types of rows: 'tr' with one color for odd rows and another color for even rows.

### What does the proposed API look like?
Just do not omit 'rowKey' in createBodyRow.tsx (57) 
const rowProps = omit(this.props, ['prefixCls', 'rowKey', 'store']);

**Comment by yesmeck** [comment]
You can pass `rowKey` to `tr` with `onRow` prop.

```javascript
<Table onRow={(record) => ({ rowKey: record.id })} />
```
