### ISSUE TITLE
请问 Modal 中的 表单初始化的时候如何激活某个文本框？

### ISSUE THREAD

**Issue by someok** [ant-design/ant-design#1008]
Modal 中的 Form componentDidMount 只调用了一次，于是多次显示 Modal 的时候无法做激活操作了。

不知是否有办法处理？

**Comment by benjycui** [comment]
Modal 只有在第一次显示时才会触发 `componentDidMount` 及相关的 lifecycle，后面的显隐是用 CSS 控制的。

对于多次显示 Modal，考虑到 Modal 的 `visible` 其实是父组件传进来的，所以可以在父组件修改 Modal 的 `visible` 的同时，调用文本框的 `focus`。

**Comment by someok** [comment]
目前已解决，在 modal 中得使用 setTimeout 来调用相应的 focus 后才有效果。

```
    focusTitleInput() {
        let titleInput = ReactDOM.findDOMNode(this.refs.titleInput.refs.input);
        setTimeout(() => titleInput.focus());
    }

    componentDidMount() {
        this.focusTitleInput();
    }

    componentDidUpdate(prevProps, prevState) {
        this.focusTitleInput();
    }
```

**Comment by deepfunc** [comment]
@someok 你的方法确实有效果，为啥要setTimeout呢？
