### ISSUE TITLE
Error happened in ScrollNumber.d.ts when buiding, using typescript

### ISSUE THREAD

**Issue by zizizheng** [ant-design/ant-design#10083]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
chrome

### Reproduction link
[https://ant.design/components/badge-cn/](https://ant.design/components/badge-cn/)

### Steps to reproduce
install antd package and build it using typscript loader

### What is expected?
no error

### What is actually happening?
The following error happened when building project.
It caused by adding the third props `never` in React.Component, is that a special meaning ? 

ERROR in [at-loader] ..\..\web\node_modules\antd\lib\badge\ScrollNumber.d.ts:48:43
    TS2707: Generic type 'Component<P, S>' requires between 0 and 2 type arguments.

---
typescript@2.8.1

**Comment by yesmeck** [comment]
@zizizheng Try upgrade `@types/react` to the latest version.
