### ISSUE TITLE
同时使用tree的showIcon和loadData功能时，没有loading的icon

### ISSUE THREAD

**Issue by wangyun122** [ant-design/ant-design#10082]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
macos chrome

### Reproduction link
[https://codepen.io/wangyun122/pen/rdXyxW](https://codepen.io/wangyun122/pen/rdXyxW)

### Steps to reproduce
同时使用tree的showIcon和loadData功能时，没有loading的icon

### What is expected?
当Tree异步加载子节点的时候可以出现loading的icon

### What is actually happening?
没有loading的icon

**Comment by zombieJ** [comment]
现在antd复用了icon作为loading图标，这里需要将loading css 从 icon 迁移到switcher上以避免载入时突然的缩进。

**Comment by lizhongzhen11** [comment]
我可以评论吗
