### ISSUE TITLE
setFieldsValue can not update field self's value

### ISSUE THREAD

**Issue by daskyrk** [ant-design/ant-design#10087]
it's same with this [issue](https://github.com/ant-design/ant-design/issues/4862), but it seem to be not resolved.

### Version
3.4.1

### Environment
mac: 10.13.4   chrome : 65.0.3325.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8y4rv52k2j)

### Steps to reproduce
write something in the input

### What is expected?
input value should be transformed to upper case

### What is actually happening?
not transformed

---
setFieldsValue can update other filed value, why not it self ?
what's the meaning of `getValueFromEvent`?

**Comment by afc163** [comment]
You shoud use `getValueFromEvent` or `normalize`.

https://ant.design/components/form-cn/#getFieldDecorator(id,-options)-%E5%8F%82%E6%95%B0

**Comment by daskyrk** [comment]
@afc163 demo里尝试了getValueFromEvent，可并没有看出如何正确的使用。。

**Comment by afc163** [comment]
https://codesandbox.io/s/v072o40rz0

**Comment by daskyrk** [comment]
@afc163 there is nothing changed between your and my demo, have you forgot to save your change?

**Comment by afc163** [comment]
My bad: https://codesandbox.io/s/03o0kjv2xv

**Comment by Even-Lau** [comment]
Both of your demos can not run properly. @afc163 @daskyrk

**Comment by afc163** [comment]
https://codesandbox.io/s/empty-voice-9g7w6
