### ISSUE TITLE
How to set the width of meny

### ISSUE THREAD

**Issue by leogeng** [ant-design/ant-design#10088]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Mac os "  "react": "^16.3.1",     "react-dom": "^16.3.1",     "react-scripts": "1.1.4"

### Reproduction link
[https://github.com/leogeng/reactLearn.git](https://github.com/leogeng/reactLearn.git)

### Steps to reproduce
set style={{ width: "500px" }} in the menu

### What is expected?
The width of menu is changed, The log dive and menu and the button are in the same line(Header)

### What is actually happening?
The width of menu is not changed, The log dive and menu and the button are not  in the same line(Header).

**Comment by Selectors-api2** [comment]
@ant-design-bot https://swifty-jsonmacho.github.io/Az32p1ci9MAOsbqfGXttbhX0hCQERjBfaXI-WYP9doJTPkfb6uioSV0PbnfXklkqg4XpDsIXrs-R_Yc6lRc/
