### ISSUE TITLE
Notification render component or Alert duration

### ISSUE THREAD

**Issue by NugzarGaguliya** [ant-design/ant-design#10091]
- [ + ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
By design I need something middle between Notification and Alert.

I need
1)notification logic that:
a)close after 4.5 seconds.
b)init from any place 

2)Alert properties such as: 
a)coloring error, warning
b)render in a specific place

Is it possible to do that with Notification or I need to build myself logic with Alert?

### What does the proposed API look like?
I think it will be good to config parent property in Notification, that will says where it should render.

**Comment by afc163** [comment]
I think you can use message: https://ant.design/components/message/
