### ISSUE TITLE
Carousel React组件自动播放BUG

### ISSUE THREAD

**Issue by li2go** [ant-design/ant-design#1009]
**问题描述**

自动轮播到一定时间后发生错误，不再轮播／
**发生环境**

- antd 版本：
- 操作系统及版本：
- 浏览器及版本：chrome
- 在线演示地址：http://ant.design/components/carousel/

**重现步骤**

1. ...
2. ...

**线上重现演示**

**Comment by benjycui** [comment]
只能说这是 [react-slick](https://github.com/akiran/react-slick) 的问题，毕竟 antd 里面只是 [简单的包装一层](https://github.com/ant-design/ant-design/blob/master/components/carousel/index.jsx)。

建议去 react-slick 的 issue 报告。

**Comment by jljsj33** [comment]
#https://github.com/ant-design/ant-design/issues/529

**Comment by jljsj33** [comment]
哈哈，自已写个吧。。。。如何？？？

**Comment by jljsj33** [comment]
react-slick  好像更新了？？？？？

**Comment by benjycui** [comment]
更新了 https://github.com/ant-design/ant-design/commit/7b608fe1e748c1a661aedb9da3e7e8026d5d6f48

不过好像还有其它的 bug。。。

**Comment by jljsj33** [comment]
好像切出去回来就不自动播放了。。。。。。。

**Comment by benjycui** [comment]
等下个版本吧：https://github.com/akiran/react-slick/issues/169
