### ISSUE TITLE
Form validation not working as expected

### ISSUE THREAD

**Issue by ycczkl** [ant-design/ant-design#10094]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Mac OS 10.10.5,  chrome 65.0.335

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l46wopn3q7)

### Steps to reproduce
Two input field. One of them is required(no matter the order). For example: i have input1 and input2, user is required to edit one of them.
1. click submit, error msg will showed in both input filed
![image](https://user-images.githubusercontent.com/6109663/38828138-ec2fb378-4169-11e8-900e-29e00d7e670c.png)
2. put something in input1, the asterix will behave correctly but the error msg for input2 is still there.
![image](https://user-images.githubusercontent.com/6109663/38828145-f6a2d6e6-4169-11e8-8258-cc82c0ec15a7.png)

https://codesandbox.io/s/l46wopn3q7

### What is expected?
both asterix and error msg for input2 should be hided

### What is actually happening?
error msg for input2 is still showing

**Comment by afc163** [comment]
I think it is a intented behavior.

**Comment by ycczkl** [comment]
@afc163 The behavior of the asterix and the error message is not consistent. 
As you can see in the last screen shot, the asterix was hided but the error msg was not

**Comment by ycczkl** [comment]
@afc163 any updates on this?

**Comment by ycczkl** [comment]
@afc163 you can take a look of my code. 
There are two inputs in my example and user is required to put something in one of the input(only one is required, shouldn't show any error msg if one of the input has been filled).

Reproduce:
1. If user didn't input any of the field, two error message will show up. (correct behavior)
2. If user put 'hello' in first field. The error message for the first input was hided(correct behavior), the asterixs for both inputs were hided(correct behavior). But the error msg for second input is not hided(wrong behavior).

**Comment by afc163** [comment]
https://codesandbox.io/s/749r2v4o8j
