### ISSUE TITLE
Select Component arrow takes up space even when disabled

### ISSUE THREAD

**Issue by ize8** [ant-design/ant-design#10092]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Chrome, react 16.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k5llmvo4mo)

### Steps to reproduce
when using Select Component, set prop showArrow={false}

### What is expected?
select field only to show the actual value

### What is actually happening?
field showing value PLUS an empty space for the arrow ... it would be nice not to have this extra space, as it adds to the field's width

**Comment by ad1992** [comment]
@afc163 can I take this up ?

**Comment by afc163** [comment]
@ad1992 sure

**Comment by ad1992** [comment]
@afc163 if i get it right, the issue has to be [react-component]( https://github.com/react-component/select) first right ?

**Comment by yutingzhao1991** [comment]
@ad1992 yes, this issue should be fixed in https://github.com/react-component/select .

**Comment by ad1992** [comment]
@yutingzhao1991 please look into  https://github.com/react-component/select/pull/292 and let me know if its fine
