### ISSUE TITLE
Table Component support for sorting done in the backend.

### ISSUE THREAD

**Issue by jamespacileo** [ant-design/ant-design#10093]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When database entries are high in number (e.g. 100k entries) it is preferable to handle sorting in the backend rather than the component.

Example:
- User toggles sorting on "age"
- Redux action is triggered and a new call is made to the server (sorting key and order is supplied to the API call)
- The entries are updated with the API response
- Table is rendered with new entries

### What does the proposed API look like?
N/A

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-ajax

**Comment by utkuturunc** [comment]
there is no way to pass the current sort state to the table. in this example table keeps track of the state.

what if initial load has some initial sorting? or sorting request fails from the backend?

**Comment by beevekmgr** [comment]
Any way to know the current sort state to get data from backend rather than sorting in frontend?

**Comment by Olegato** [comment]
any update?

**Comment by bombillazo** [comment]
There is a property called `defaultSortOrder` in the ColumnType prop for each column, wouldn't that work?
