### ISSUE TITLE
Tree的onSelect事件selectedKeys有值，e.selectedNodes是空数组

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design#10099]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
win10,chrome 62,react 16

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
	onSelect = (selectedKeys, e) => {
		if (e.selectedNodes && e.selectedNodes.length > 0) {
			let node = e.selectedNodes[0].props.dataRef;
			this.props.dispatch({
				type: 'MonitorTree/saveSelectNode',
				payload: node,
			});
		}
	};

### What is expected?
selectedNodes有值

### What is actually happening?
selectedNodes是空数组

**Comment by zombieJ** [comment]
提供一下demo，
Template: https://codesandbox.io/s/5x7v1v1opp
