### ISSUE TITLE
DatePicker throw error when form item validateTrigger is onBlur

### ISSUE THREAD

**Issue by hAtvis** [ant-design/ant-design#10097]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
os mac 10.13.3 chrome Version 65.0.3325.181 (Official Build) (64-bit) react 16.2.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o553q3zw26)

### Steps to reproduce
* use DatePicker in Form
* set validateTrigger to onBlur
* select date
* select again
* error throw

### What is expected?
date can be select correct and validate is normal

### What is actually happening?
onBlur can't check selected date, and trigger error when select again

**Comment by g8up** [comment]
I came accross the same issue on `antd@3.2.3`.

**Comment by Cziken** [comment]
Thanks guys for helping solving the problem!

**Comment by zombieJ** [comment]
Hi, since user always can't typing directly in the input of DatePicker. The `onBlur` is not necessary. Pls use `onChange` instead.
