### ISSUE TITLE
Problem with clone project on Linux/CentOS-6.5

### ISSUE THREAD

**Issue by gapsaras** [ant-design/ant-design#10106]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Linux web40 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux  CentOS-6.5

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
first try to clone this project with http way:

git clone https://github.com/ant-design/ant-design.git, failed

then try ssh way: 

git clone git@github.com:ant-design/ant-design.git, failed again

### What is expected?
clone this project to my own machine

### What is actually happening?
but failed in both way

with `http` show error: 
> Initialized empty Git repository in /home/haojie/ant-design/.git/

error:  while accessing https://github.com/ant-design/ant-design.git/info/refs

fatal: HTTP request failed

with `SSH` show error:
> Initialized empty Git repository in /home/haojie/ant-design/.git/

Permission denied (publickey).

fatal: The remote end hung up unexpectedly

**Comment by afc163** [comment]
It is not a antd problem.
