### ISSUE TITLE
upload component not work when img url has some params, example: show from aliyun oss

### ISSUE THREAD

**Issue by didmehh** [ant-design/ant-design#10102]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.1

### Environment
chrome 65.0

### Reproduction link
- first 
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jv6poyjjxv)

- [second codebox reproduce](https://codesandbox.io/s/pw9v76ky27)

### Steps to reproduce
[i got example from here](https://ant.design/components/upload-cn/), then add some params to `url`. not work.

### What is expected?
show image

### What is actually happening?
not show

**Comment by didmehh** [comment]
i had provide another example for this issue.
then, i had resolve this issue by FileReader.
ps: i think the first link was clearly re-display for this issue. so, why need to reproduce again?
thanks.

**Comment by afc163** [comment]
Did you mean the image url `"https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png?time=20180417"` will not display image correctly?

**Comment by didmehh** [comment]
yep

**Comment by didmehh** [comment]
hi guys, my antd version still at 3.3.1.
i had resolve it by parse remote img to base64.
[for example:](https://github.com/xiaohesong/ums/blob/master/src/until/Base64RemoteImg.js)
```javascript
function base64Url(url, callback) {
  let xhr = new XMLHttpRequest();
  xhr.onload = function() {
    let reader = new FileReader();
    reader.onloadend = function() {
      callback(reader.result);
    }
    reader.readAsDataURL(xhr.response);
  };
  xhr.open('GET', url);
  xhr.responseType = 'blob';
  xhr.send();
}

const url = 'http://img15.3lian.com/2015/f1/38/d/41.jpg'
base64Url(url, (result) => {
    console.log("result base64 url was", result)
})
```
