### ISSUE TITLE
Add new api for select

### ISSUE THREAD

**Issue by bnerDY** [ant-design/ant-design#10107]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
remove selected value in <Select />

remove all selected value in <Select />

### What does the proposed API look like?
removeSelected = () =>{}

removeAllSelected = () =>{}

**Comment by afc163** [comment]
Use `value` to control it. Please learn React before using antd.

**Comment by bnerDY** [comment]
@afc163 Is is possible to use value in multi selection mode ?
![screen shot 2018-04-17 at 1 29 09 pm](https://user-images.githubusercontent.com/5085327/38850292-5ba20862-4243-11e8-8fb1-14de976909f0.png)
I didn't find value props in the select instance

**Comment by afc163** [comment]
> Is is possible to use value in multi selection mode ?

Yep, you can use `value` in any Select mode.
