### ISSUE TITLE
Input 组件不支持autocomplete="off"

### ISSUE THREAD

**Issue by ypxu87** [ant-design/ant-design#10104]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
让Input组件不记录用户的输入内容，这是原生元素的基本属性，但是咱antd的组件Input设置这个属性却是无效的。

### What does the proposed API look like?
Input 组件支持autocomplete="off"

**Comment by zombieJ** [comment]
`autoComplete`
ref: https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes

**Comment by zhangchengzheng91** [comment]
It doesn't work.
react v 16.8.1
antd v 3.10.8
code:
 <Input  autoComplete="off" />

**Comment by zombieJ** [comment]
Hi @zhangchengzheng91 , could you help to provide an online reproduce?

**Comment by zhangchengzheng91** [comment]
> Hi @zhangchengzheng91 , could you help to provide an online reproduce?

you can visit https://stage03-www.novadax.com/.
click 'sign in'
then click 'forget password'
now, you can see that the email code is autoCompleting.
but the input has autoComplete attrs.

**Comment by afc163** [comment]
I don't see any autoComplete prop at Input.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/507615/53409128-27463d80-39fb-11e9-929d-5bdb9ba7248f.png">

could you help to provide an online reproduce via forking http://u.ant.design/codesandbox-repro ?

**Comment by zhangchengzheng91** [comment]
[>]I don't see any autoComplete prop at Input.
> 
> <img alt="image" width="1101" src="https://user-images.githubusercontent.com/507615/53409128-27463d80-39fb-11e9-929d-5bdb9ba7248f.png">
> 
> could you help to provide an online reproduce via forking http://u.ant.design/codesandbox-repro ?
This is a wrong place...
![Alt text](https://cdn.qiujun.me/image/2019/02/26/0971e10eb9b14c9e9fbb773db9e1547c.jpg)

**Comment by zombieJ** [comment]
It's chrome default behavior not antd bug. You should set
 `autocomplete="new-password"` to prevent chrome auto fill: https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

**Comment by zhangchengzheng91** [comment]
> It's chrome default behavior not antd bug. You should set
> `autocomplete="new-password"` to prevent chrome auto fill: https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

It doesn't work, I have tried this method.
I will try another methods.
Thank you.

**Comment by Zhaojing0987** [comment]
@zhangchengzheng91 Do you find a solution?

**Comment by holynewbie** [comment]
> @zhangchengzheng91 Do you find a solution?

just set <Input autoComplete="new-password" />

**Comment by efstathiosntonas** [comment]
@holynewbie it won't work in my case.

```
 <Form.Item
                                            label="E-mail"
                                        >
                                            {getFieldDecorator('email', {
                                                rules: [{
                                                    type: 'email', message: 'The input is not valid E-mail!',
                                                }, {
                                                    required: true, message: 'Please input your E-mail!',
                                                }],
                                            })(
                                                <Input type="email" autoComplete="new-password"/>
                                            )}
                                        </Form.Item>

```

**Comment by josejuniordev** [comment]
In fact you do not always need to enter **'new-password'**, just enter **'new-something'**, **something** that has meant the name of the field you are working on.

**Comment by dimasusername** [comment]
Most browsers will ignore. `new-password` is unofficial and works for now, but even that doesn't prevent completely.

Check this article on mozilla.org for more info: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion

**Comment by syuzichachyan** [comment]
I tried autoComplete={false}, autoComplete="off",autoComplete="new-password" in antd Input as prop. But there is no result. Chrome continue to fill saved passwords.

**Comment by FahRamatis** [comment]
autoComplete="new-password" works for me.

**Comment by Mekala-palaniyappan** [comment]
@afc163 
I tried autoComplete={false}, autoComplete={'off'}, autoComplete={'new-password'}, autoComplete={'something'},
but not working,
i am using react latest version=**16.8.1**
antd version=**4.4.2**
Can anyone help me?
