### ISSUE TITLE
input doesn't work with FieldDecorator in IE9

### ISSUE THREAD

**Issue by jojoLockLock** [ant-design/ant-design#10109]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.0

### Environment
Windows 10 / IE 9

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
git clone 3.2.0 --depth=1 https://github.com/ant-design/ant-design.git

npm install 

npm run start 

visit http://127.0.0.1:8001/components/form/

The input can not input anything in IE9  

### What is expected?
Input component can work with form 

### What is actually happening?
Input component can not input any text

**Comment by lhr0909** [comment]
Just checked on v3.4.1, same issue

**Comment by LinusCenterstrom** [comment]
Same problem here, also on 3.4.1

**Comment by bianlizuozishu** [comment]
The trouble is to provide a good version, the production will go online very anxious.

**Comment by carvinlo** [comment]
Just checked on v3.5.2, same issue

**Comment by sharkwarn** [comment]
I found that the e.target.value returned by onChange was undefined , This link can help [http://react-china.org/t/antd-form-input-ie9/21590](http://react-china.org/t/antd-form-input-ie9/21590)

**Comment by lzp3021** [comment]
Same problem here,
"antd": "^3.4.5",
"react": "^16.3.2",
"react-dom": "^16.3.2",

**Comment by benjycui** [comment]
@afc163 just remove `fixControlledValue`, everything works fine: https://github.com/ant-design/ant-design/commit/31ee4bea303c5d1ec3ad0567f76ef356f60f551d

**Comment by afc163** [comment]
@benjycui It is not the reason, the actual `value` is still `undefined` even after remove `fixControlledValue`.

**Comment by afc163** [comment]
Fixed in `16.4.1`: https://github.com/facebook/react/issues/12506#issuecomment-397011550
