### ISSUE TITLE
In the form, without the header of the subform, there will be blank lines.

### ISSUE THREAD

**Issue by leejay1992** [ant-design/ant-design#10118]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Mac Chrome

### Reproduction link
[https://github.com/ant-design/ant-design/issues/10079#issuecomment-381907032](https://github.com/ant-design/ant-design/issues/10079#issuecomment-381907032)

### Steps to reproduce
In the form, without the header of the subform, there will not be blank lines.

### What is expected?
In the form, without the header of the subform, there will not be blank lines.

### What is actually happening?
In the form, without the header of the subform, there will be blank lines.
display result:
<img width="197" alt="ant-bug" src="https://user-images.githubusercontent.com/15710933/38859758-4f64b770-4261-11e8-9e4e-4653f903319a.png">
columns:
<img width="406" alt="coding" src="https://user-images.githubusercontent.com/15710933/38859782-569b738a-4261-11e8-8c22-36a47c6a817a.png">

**Comment by leejay1992** [comment]
I have forked the codebase and completed a simple demo demo.  https://codesandbox.io/s/my3rx9knjy

**Comment by yesmeck** [comment]
You can use `Table[title]` https://codesandbox.io/s/nwvop06mom

**Comment by leejay1992** [comment]
well done, thx bro;
