### ISSUE TITLE
TreeSelect下拉菜单位于选择框上面，收起菜单位置错位

### ISSUE THREAD

**Issue by xaasu** [ant-design/ant-design#10117]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.0

### Environment
"react": "^16.2.0"

### Reproduction link
[https://codepen.io/xaasu/pen/xjKOmO?editors=1010](https://codepen.io/xaasu/pen/xjKOmO?editors=1010)

### Steps to reproduce
set a long size treeData and make the drop menu on the top of the Select

### What is expected?
when close the drop menu , the drop menu could  near the Select on top or bottom

### What is actually happening?
the drop menu is far away from the Select

---
I'm sorry I can't  reappear the problem in my link, I have picture to describe the problem ,  how can I fix it under the premise I don't change the version of antd
![tim 20180417175542](https://user-images.githubusercontent.com/24312839/38863556-994ce1ce-426a-11e8-8115-adba41c6c21c.png)
![tim 20180417175532](https://user-images.githubusercontent.com/24312839/38863565-a1aecf9e-426a-11e8-9969-daa3daac11a8.png)

**Comment by afc163** [comment]
Try reinstall your node_modules.
