### ISSUE TITLE
Rangepicker选择开始日期和选择结束日期后的清空按钮无法使用

### ISSUE THREAD

**Issue by taikongfeizhu** [ant-design/ant-design#1012]
Rangepicker选择开始日期和选择结束日期后的清空按钮点击无效果，也无法清空选择后的日期

**Comment by benjycui** [comment]
官网正常 http://ant.design/components/date-picker/#picker-demo-range

建议先阅读 [CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md)。

**Comment by taikongfeizhu** [comment]
问题已经解决，是由于生产环境中的index.css没有更新到最新版本，重新编译index.less后修复

**Comment by benjycui** [comment]
问题解决后，建议自行关闭 issue
