### ISSUE TITLE
Select component didn't shows scroll bar

### ISSUE THREAD

**Issue by sahar922** [ant-design/ant-design#10127]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Mac os, Chrom 65

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8lllp65zzl)

### Steps to reproduce
When using Select component, at the bottom of the screen (or somewhere near to the end of the screen) - there is no scroll option so I cant reach all of the options.

### What is expected?
Either a flag for forcing adding a scroll bar, or automatically detect that the component is close to the end of the screen and shows the scrollbar

.

### What is actually happening?
I can reach only 1-2 of my options (5). the rest of the options are inaccessible
![screen shot 2018-04-17 at 5 12 49 pm](https://user-images.githubusercontent.com/12861093/38875265-a8686ffa-4262-11e8-82f7-86f1c2d5c3a2.png)

**Comment by afc163** [comment]
Your codesandbox is working.

<img width="537" alt="image" src="https://user-images.githubusercontent.com/507615/38882862-ea350214-429d-11e8-8493-848d12fbecf5.png">
