### ISSUE TITLE
Create Option if Value not present in Dropdown

### ISSUE THREAD

**Issue by joshuagautham** [ant-design/ant-design#10124]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the value is not present in the select, it should automatically make an API request and create a value. This is for a single value drop down

### What does the proposed API look like?
Similar to select2 , semantic select

**Comment by yesmeck** [comment]
Duplicate of #7988
