### ISSUE TITLE
upload 的 customRequest函数不能是`async`函数

### ISSUE THREAD

**Issue by jiyarong** [ant-design/ant-design#10122]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
macos最新版本  65.0.3325.181 (正式版本) （64 位）

### Reproduction link
[https://ant.design/components/upload-cn/#header](https://ant.design/components/upload-cn/#header)

### Steps to reproduce
```
	<Dragger showUploadList={false} name='file' multiple={false} customRequest={this.uploadAvatar}>
		<AvatarCommon user={user} />
		<p>点击此处或将图片拖到此处更新头像</p>
	</Dragger>

	uploadAvatar = async (e) => {
		let url = await updateAliyunOss(e.file)
		let result = await userMobx.updateInfo({avatar_url: url})
		if (result === true) {
			message.success('更换成功')
		} else {
			message.error('更换失败')
		}
	}
```

换成promise的写法是好的，这样写之后点击其他任何链接会出现以下错误
```
AjaxUploader.js:178 Uncaught TypeError: reqs[uid].abort is not a function
    at AjaxUploader.js:178
    at Array.forEach (<anonymous>)
    at AjaxUploader.abort (AjaxUploader.js:176)
    at AjaxUploader.componentWillUnmount (AjaxUploader.js:69)
    at callComponentWillUnmountWithTimer (react-dom.development.js:8732)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at safelyCallComponentWillUnmount (react-dom.development.js:8739)
    at commitUnmount (react-dom.development.js:8865)
    at commitNestedUnmounts (react-dom.development.js:8901)
    at unmountHostComponents (react-dom.development.js:9184)
    at commitDeletion (react-dom.development.js:9234)
    at commitAllHostEffects (react-dom.development.js:9926)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at commitRoot (react-dom.development.js:10015)
    at performWorkOnRoot (react-dom.development.js:11017)
    at performWork (react-dom.development.js:10967)
    at batchedUpdates (react-dom.development.js:11086)
    at batchedUpdates (react-dom.development.js:2330)
    at dispatchEvent (react-dom.development.js:3421)
(anonymous) @ AjaxUploader.js:178



```

### What is expected?
希望可以支持async

### What is actually happening?
暂时不支持

**Comment by EvKylin** [comment]
I have met this problem either, I solve this problem by using a balanced method.
```
  // Custom Upload
  handleCustomRequest = ({ file }) => {
    this.setState({ importUploading: true });
    this.handleImportNumber(file).then(res => {
      this.setState({ importUploading: false });
      if (res.success) {
        const data = res.data.list;
        if (!data.length) message.error('no data~');
        this.props.onChange(data);
      }
    });
  };
  // Start file upload
  handleStartFileUpload = async file => {
    const res = await request('/api/excel/insertNum', {method: 'POST', body: file })
    return res;
  };
```

**Comment by R-on** [comment]
> I have met this problem either, I solve this problem by using a balanced method.
> 
> ```
>   // Custom Upload
>   handleCustomRequest = ({ file }) => {
>     this.setState({ importUploading: true });
>     this.handleStartFileUpload (file).then(res => {
>       this.setState({ importUploading: false });
>       if (res.success) {
>         const data = res.data.list;
>         if (!data.length) message.error('no data~');
>         this.props.onChange(data);
>       }
>     });
>   };
>   // Start file upload
>   handleStartFileUpload = async file => {
>     const res = await request('/api/excel/insertNum', {method: 'POST', body: file })
>     return res;
>   };
> ```

Hello. What is a balanced method?

**Comment by pybuche** [comment]
Hi, any news on this? Thx!

**Comment by PJCHENder** [comment]
Is there any new idea about this issue?

**Comment by 13725102796** [comment]
很难想象，这个bug是在覆盖默认上传的函数中return true 引起的！
`<Upload
                name="avatar"
                listType="picture-card"
                className="avatar-uploader"
                showUploadList={false}
            
                beforeUpload={beforeUpload}
                customRequest={this.saveImage}
                /* onChange={this.handleChange} */
              >
                {imageUrl ? <div className="ant-upload"><img src={imageUrl} alt="avatar"   /></div> : uploadButton}
</Upload>`

customRequest 里面接受的覆盖默认事件 this.saveImage
`saveImage = (val)=>{
    console.log(val)
    var reader = new FileReader();
    reader.readAsDataURL(val.file)
    const that = this
    reader.onload=function(){
      that.setState({
        imageUrl: this.result
      })
    }
    // return true  如果加了这一行，再去隐藏弹窗就会出现以上错误！
  }`

**Comment by Matheswaaran** [comment]
Also, the following is shown in the production build as well for ant upload.

`react-dom.production.min.js:194 TypeError: t[e].abort is not a function
    at AjaxUploader.js:188
    at Array.forEach (<anonymous>)
    at t.value (AjaxUploader.js:186)
    at t.value (AjaxUploader.js:82)
    at nr (react-dom.production.min.js:198)
    at or (react-dom.production.min.js:203)
    at Ir (react-dom.production.min.js:244)
    at Dr (react-dom.production.min.js:238)
    at Mr (react-dom.production.min.js:237)
    at Tr (react-dom.production.min.js:234)`

**Comment by legend1250** [comment]
I'm facing this issue as well
![image](https://user-images.githubusercontent.com/15612361/54220203-758f2c80-4523-11e9-8bb7-1ca1b9ef185e.png)

**Comment by legend1250** [comment]
After take a look deeper in `rc-upload`, I figure it out the `reqs[uid]` is a Promise and it will throw error if trying to invoke `.abort()` function. 
Simply fixed by overriding `abort()` function
![image](https://user-images.githubusercontent.com/15612361/54251926-88cde680-457b-11e9-9417-77b14ee42a74.png)

**Comment by dotexe0** [comment]
FYI -- there are examples [here](https://github.com/react-component/upload/blob/master/examples), including a [customRequest](https://github.com/react-component/upload/blob/master/examples/customRequest.js) example which shows how to go about doing the `abort` ovveride @legend1250 provided.

**Comment by lbordowitz** [comment]
The underlying code for the `AjaxUploader` is [here](https://github.com/react-component/upload/blob/master/src/AjaxUploader.jsx). If a request is still in progress, [it will be `abort()`ed](https://github.com/react-component/upload/blob/master/src/AjaxUploader.jsx#L184-L187). You *must* indicate explicitly that the request is no longer in progress by calling `onSuccess` or `onError`, which will [delete the `req[uid]` from the object](https://github.com/react-component/upload/blob/master/src/AjaxUploader.jsx#L158-L165).

You can also see that the [`req[uid]` is set to whatever the `request` returns](https://github.com/react-component/upload/blob/master/src/AjaxUploader.jsx#L148) which, unfortunately, is a Promise, not an object with an `abort()` function.

**Comment by afc163** [comment]
`customRequest` can be async function after 4.0: #26427
