### ISSUE TITLE
tabs的键盘上下左右按键功能可配置

### ISSUE THREAD

**Issue by gazxm** [ant-design/ant-design#10121]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当我需要使用上下左右的键盘事件在当前的TabPane里面进行操作的时候，会切换tab，并且无法取消切换。

### What does the proposed API look like?
<Tabs disableKeyDown={true}></Tabs>

**Comment by abc879475908** [comment]
同楼主...官方有解决的api么

**Comment by BigBigWen** [comment]
同求解决方案

**Comment by zhenxianluo** [comment]
通过重新renderTabBar可以解决这个问题, 用新的按键事件onKeyDown替换原有的onKeyDown
`<Tabs renderTabBar={(props, DefaultTabBar) => <DefaultTabBar {...props} onKeyDown={e => e}/>}></Tabs>`

**Comment by zombieJ** [comment]
Tabs 的 title 在 focus 时可以通过键盘操作，tab 键到下方的 TabPane 就不会响应方向键了。

**Comment by NOLDOR-orc** [comment]
> 通过重新renderTabBar可以解决这个问题, 用新的按键事件onKeyDown替换原有的onKeyDown
> `<Tabs renderTabBar={(props, DefaultTabBar) => <DefaultTabBar {...props} onKeyDown={e => e}/>}></Tabs>`

感谢，解决了

**Comment by Kelly8082** [comment]
请问ant-design-vue的这种情况要怎么解决 ？
<Tabs renderTabBar={(props, DefaultTabBar) => <DefaultTabBar {...props} onKeyDown={e => e}/>}></Tabs>
楼上这种方式好像不行
