### ISSUE TITLE
Wrong property passed to div in List

### ISSUE THREAD

**Issue by slonoed** [ant-design/ant-design#10123]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Any os, any browser

### Reproduction link
[https://codepen.io/slonoed/pen/PeYpRL?editors=0010](https://codepen.io/slonoed/pen/PeYpRL?editors=0010)

### Steps to reproduce
Use List component with empty array in dataSource and set "locale" property to object with field "emptyText" to override text for empty list.

### What is expected?
List shows custom empty text, no errors in console.

### What is actually happening?
An error (warning) in console, because List passes locale to internal div
Warning: Unknown prop `locale` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

---
"locale" is valid property for List
https://github.com/ant-design/ant-design/blob/3.4.1/components/list/index.tsx#L52

it stored in "rest" variable
https://github.com/ant-design/ant-design/blob/3.4.1/components/list/index.tsx#L132

than passed to div
https://github.com/ant-design/ant-design/blob/3.4.1/components/list/index.tsx#L204

**Comment by yesmeck** [comment]
Tagging as `good first issue`
