### ISSUE TITLE
ant-design的 tree 的数据超过2万个节点浏览器会卡死，这个要怎么优化？

### ISSUE THREAD

**Issue by muchengit** [ant-design/ant-design#10131]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ant-design的 tree 的数据超过2万个节点浏览器会卡死，这个要怎么优化？

### What does the proposed API look like?
可以加载5万，或者10万条数据不卡死

**Comment by afc163** [comment]
Duplicate of #3789
