### ISSUE TITLE
是否可以给table 增加一下 column 可以 互相换。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#10137]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如我选中某一个列头，然后拖动可以和其他列调换位置。

### What does the proposed API look like?
columnDragable=true

**Comment by yesmeck** [comment]
建议参考 https://ant.design/components/table/#components-table-demo-drag-sorting 自己实现。
