### ISSUE TITLE
react@16.13.2下面 Tree选中checkbox无法回显

### ISSUE THREAD

**Issue by wm3445** [ant-design/ant-design#10132]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
react@16.13.2

### Reproduction link
[https://codepen.io/wm3445/pen/xjxKrJ](https://codepen.io/wm3445/pen/xjxKrJ)

### Steps to reproduce
https://codepen.io/wm3445/pen/xjxKrJ

### What is expected?
选中checkbox回显

### What is actually happening?
checkbox无法回显

---
如果oncheck中不setState就可以正常回显

**Comment by wm3445** [comment]
一开始我以为是umi的问题所以在umi下面提过此问题
https://github.com/umijs/umi/issues/345

**Comment by zombieJ** [comment]
fixed in `rc-tree` 1.8.3
