### ISSUE TITLE
Scroll bug with submenu inside fixed header

### ISSUE THREAD

**Issue by abdurahmanus** [ant-design/ant-design#10145]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
windows 10, Chrome 65.0.3325.181

### Reproduction link
[https://codepen.io/abdurahmanus/pen/gzOGwJ?editors=0010](https://codepen.io/abdurahmanus/pen/gzOGwJ?editors=0010)

### Steps to reproduce
1) resize window to size when vertical scrollbar appears
2) click on submenu and scroll screen with mouse wheel 

### What is expected?
Opened submenu should stay in same position (in my opinion)

### What is actually happening?
Opened submenu starts scrolling and moves away from menu

**Comment by afc163** [comment]
`getPopupContainer={node => node.parentNode}`

https://codepen.io/afc163/pen/YLPzKm?editors=0010

https://github.com/react-component/menu

**Comment by abdurahmanus** [comment]
I can't find getPopupContainer declaration in prop types.

**Comment by afc163** [comment]
You can create a PR to improve that.
