### ISSUE TITLE
搜狗浏览器下Icon会被截断一点

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#10146]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
win10 ，搜狗8.0.5.27662

### Reproduction link
[https://ant.design/components/icon-cn/](https://ant.design/components/icon-cn/)

### Steps to reproduce
官网Icon演示页

### What is expected?
图标显示完整

### What is actually happening?
图标顶部截断
![_20180418221920](https://user-images.githubusercontent.com/22299421/38937781-8ed7ae1c-4356-11e8-818f-873ac5aff999.png)

**Comment by afc163** [comment]
3.9.0 之后 svg 不再有这个问题。
