### ISSUE TITLE
layout sider 组件属性，collapsedWidth='40px'后, 样式不正确，伸缩不能正常使用

### ISSUE THREAD

**Issue by aibaiejoy** [ant-design/ant-design#10140]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
chrome，react，web

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oqkp18o3xy)

### Steps to reproduce
https://codesandbox.io/s/oqkp18o3xy

### What is expected?
伸缩可以正常使用

### What is actually happening?
伸缩不能正常使用

**Comment by aibaiejoy** [comment]
`<Sider
	collapsedWidth='40px'
	width={this.state.collapsed ? '40px' : '200px'}
	collapsible
	collapsed={this.state.collapsed}
	onCollapse={this.onCollapse}
>
	<div className="logo" />
	<Menu
		style={{ width: this.state.collapsed ? 40 : 200 }}
	>
	</Menu>
</Sider>
`

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/2078354bc5ef0071e255d4809bb759c73ad63229

You can use this as workaround until next patch.

```diff
collapsedWidth="40px"
collapsedWidth={40}
```
