### ISSUE TITLE
Select component doesn't filter choices correctly in multiple mode

### ISSUE THREAD

**Issue by Arm1** [ant-design/ant-design#10157]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Windows 10 / Chrome 64

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/48xp5xmqm4)

### Steps to reproduce
Click on the select component, then start entering letters.

### What is expected?
It should only display choices that contains the letters I entered in the input component.

I also want to keep a key-value and a label to display. 

### What is actually happening?
It filters on key/value, but not on the label displayed.

---
Key or Value defined on the options doesn't seem to help resolving this issue. I was confused and tried different ways (with labelInValue for instance) in order to workaround...

Thanks to the team for your work !

**Comment by yesmeck** [comment]
<img width="938" alt="screen shot 2018-04-19 at 17 12 57" src="https://user-images.githubusercontent.com/465125/38982630-ed03bf32-43f4-11e8-81ab-6ddd690538ba.png">

**Comment by Arm1** [comment]
Sorry
