### ISSUE TITLE
Privacy error

### ISSUE THREAD

**Issue by firepunch** [ant-design/ant-design#10154]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
webpage

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
The page is not accessible. It is expected to be a certificate error.

### What is expected?
This is because the certificate is different from the domain.

### What is actually happening?
This is because the certificate is different from the domain.

### Screen Shot
![](https://goo.gl/4k1GoS "ss")

**Comment by afc163** [comment]
It should be ok now.
