### ISSUE TITLE
表单中field的 id 是否可以提供个prop用来设置前缀？

### ISSUE THREAD

**Issue by someok** [ant-design/ant-design#1015]
我用 form 封装了个表单组件，在页面上几个地方都使用了，导致的一个结果就是出现了重复的 id：

> input id="abc"

于是 label 的 htmlFor 也就不起作用了。

我查看了下源码也没发现哪儿可以设置这个的。

**Comment by benjycui** [comment]
`options.id`，see：http://ant.design/components/form/#this-props-form-getfieldprops-id-options

**Comment by someok** [comment]
我目前用的就是这个设置。

例如某个字段名为 title，在 createForm  的时候初始化数据：

```
export default createForm({
    mapPropsToFields(props) {

        const initData = props.initData;
        return {
            
            title: {
                value: initData.get('title', '')
            }
        };
    }
})(TitleForm);
```

在验证提交的时候 ` this.props.form.validateFields((errors, values) ` values 中的时候 values 继续保持 `{title:'XXX'}` 这样的格式。

但是在生成 input 的时候其 id 可以分配个前缀，这样即使一个页面有多个同样的表单，也不会导致 id 冲突。

**Comment by benjycui** [comment]
前缀可以自己加的吧：

```jsx
<TitleForm prefixId="sth" />

// 然后自己在内部拼接
<Input {...getFieldProps(`${props.prefixId}-input`, {})} />
```

**Comment by benjycui** [comment]
然后在 `handleSubmit` 里把 `{'prefixId-title': 'XXX'}` 转为 `{title: 'XXX'}`。

**Comment by someok** [comment]
这样太丑陋了吧

Benjy Cui <notifications@github.com>于2016年2月16日周二 10:01写道：

**Comment by afc163** [comment]
可自行封装。
