### ISSUE TITLE
上传组件在显示带参数的图片地址时不正常，

### ISSUE THREAD

**Issue by jinxin479** [ant-design/ant-design#10152]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
mac chorme64

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4w8lrkrny4)

### Steps to reproduce
Upload的uploadlist.js源代码并没有变化

### What is expected?
可以正常显示带参数的图片url

### What is actually happening?
显示不了

---
最新release 3.4.1.更新日志说是解决了这个问题，但是并没有

**Comment by afc163** [comment]
Fixed in #10102

**Comment by jinxin479** [comment]
但是为什么我安装的antd还是有这个问题呢？虽然版本是3.4.1

**Comment by afc163** [comment]
master 还没发布。

**Comment by jinxin479** [comment]
哦。好的，谢谢
