### ISSUE TITLE
TextArea height doesn't recalculate after resize broswer when 'autosize' configured

### ISSUE THREAD

**Issue by changhui3067** [ant-design/ant-design#10151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
windows 10, chrome

### Reproduction link
[https://codepen.io/freyjachang/pen/zjxvOa?editors=0010](https://codepen.io/freyjachang/pen/zjxvOa?editors=0010)

### Steps to reproduce
narrow the broswer for different screenwidth 

### What is expected?
there should be a scrollbar if the value string is more than current height can display, or resize the TextArea if its width changed.

### What is actually happening?
the TextArea narrow down as well, but its height does not recalculate, no scrollbar shows either, which result in some text may seems disappear.

**Comment by Arkellys** [comment]
Hello @afc163, any news about this bug ?

**Comment by zombieJ** [comment]
Add scroll first.
Will add resize observer later.
