### ISSUE TITLE
Dynamic table head grouping

### ISSUE THREAD

**Issue by ShaneZhengHarcourts** [ant-design/ant-design#10168]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
From time to time, we have tables that the users would like to dynamically set the grouping. At the moment, the grouping is static.

### What does the proposed API look like?
.

**Comment by yesmeck** [comment]
You can define columns as a state.
