### ISSUE TITLE
<fieldset> 设置 disabled 属性后对于其中的 Select 不起作用

### ISSUE THREAD

**Issue by someok** [ant-design/ant-design#1017]
如题，这是否是个bug？

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/399 https://github.com/ant-design/ant-design/issues/743

建议阅读 [CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md#3-read-the-faq-and-search-the-issues-list-of-ant-design)。
