### ISSUE TITLE
showSearch input of TreeSelect unfocus after each character entered

### ISSUE THREAD

**Issue by iqdev-ca** [ant-design/ant-design#10179]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
IE11

### Reproduction link
[https://ant.design/components/tree-select/](https://ant.design/components/tree-select/)

### Steps to reproduce
1.Open link in IE11 || 2.Click on "Please select" first drop-down || 3. Start typing in the searchbox inside drop-down

### What is expected?
Ability to type and enter entire word

### What is actually happening?
Input field unfocused after each character entered. 

---
Thank you for a great product! We love using it :) Please give ideas for fixing this.

**Comment by yesmeck** [comment]
Bug introuced in https://github.com/react-component/tree-select/pull/108 

@zombieJ

**Comment by dani-media** [comment]
Hey any update on this bug?

**Comment by zombieJ** [comment]
Since current `TreeSelect` & `Select` will do realign when content update which will trigger IE 10/11 input lost focus bug.

Will follow up.

ref: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15558714/

**Comment by taoeer** [comment]
This bug reappear when the treenode was generate async! 

![bug](https://user-images.githubusercontent.com/9425478/40460955-b52f72c4-5f3b-11e8-82e9-5a2776d3d0bb.gif)

**Comment by taoeer** [comment]
It's a issue for minority browser

**Comment by afc163** [comment]
Is this resolved now?

**Comment by zombieJ** [comment]
close since #14594 fixed.
