### ISSUE TITLE
 固钉的offsetBottom根本没任何作用

### ISSUE THREAD

**Issue by shadiniao** [ant-design/ant-design#10171]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
chrome 65.0.3325.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x390j1rq0z)

### Steps to reproduce
设置offsetBottom为40

### What is expected?
现在屏幕下方40的位置,滚动也能固定

### What is actually happening?
无任何效果

**Comment by afc163** [comment]
https://codesandbox.io/s/9yj746mrlw

It is working, you seems not to fully understand `offsetBottom`.
