### ISSUE TITLE
we cannot change the title's css of submenu 

### ISSUE THREAD

**Issue by SanPy** [ant-design/ant-design#10175]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
it can change the css we need!

### What does the proposed API look like?
Provide a param to change title'css on props of  Submenu  component

**Comment by dengfuping** [comment]
@SanPy 
```
:global {
  .ant-menu-item: {
    // your style here
  }
```
If you don't want to influence all the `Menu` style, you could wrapper it with a custom `className`.
```
.customCalssName {
  :global {
    .ant-menu-item: {
      // your style here
    }
}
```

Then

```
<Menu className={styles.customClassName} />
```

**Comment by SanPy** [comment]
I see, thank you!
