### ISSUE TITLE
table组件设置scroll后,然后设置某一列为fixed,当fixed的内容很多时,显示效果非常难看,而如果不设置fixed,列头就会出现滚动条

### ISSUE THREAD

**Issue by shadiniao** [ant-design/ant-design#10173]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
chrome 版本 65.0.3325.181（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j48xk1qz39)

### Steps to reproduce
table组件设置scroll后,然后设置某一列为fixed,当fixed的内容很多时

### What is expected?
能使行高度一致

### What is actually happening?
行高度不一致,固定列比非固定列高度要高

**Comment by afc163** [comment]
你的例子里写死了三列的宽度，而表格本身宽度是不定的。请至少留一列弹性宽度。
