### ISSUE TITLE
antd 3.4.1的Select的labelInValue不生效

### ISSUE THREAD

**Issue by lucklove** [ant-design/ant-design#10170]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
chrome

### Reproduction link
[http://riddle.alibaba-inc.com/riddles/29b026e1](http://riddle.alibaba-inc.com/riddles/29b026e1)

### Steps to reproduce
```js
        <Select labelInValue value={{key: 'jack', label: 'jacks'}} style={{ width: 120 }}>
            <Select.Option key="jack">Jack (100)</Select.Option>
            <Select.Option key="lucy">Lucy (101)</Select.Option>
        </Select>
```

### What is expected?
期望选中显示的结果为jacks

### What is actually happening?
实际选中显示的结果为Jack (100)

**Comment by yutingzhao1991** [comment]
预期行为，会优先使用匹配到的 Option 中的内容。你需要的应该是 `optionLabelProp` ，参考 http://riddle.alibaba-inc.com/riddles/454f0275。
