### ISSUE TITLE
Table Component (scroll.x dynamic)

### ISSUE THREAD

**Issue by aaesis** [ant-design/ant-design#10189]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My problem is to set the scroll.x to be dynamic. The current implementation is to have a dynamic column and rows, but the scroll.x in need to be set manually. And I cannot get the width of the table when setting it to default. Please.

### What does the proposed API look like?
```
const columns = [
  { title: "Full Name", dataIndex: "name", key: "name", width: 200 },
  { title: "Age", dataIndex: "age", key: "age", }, // dynamic
  { title: "Column 1", dataIndex: "address", key: "1", }, // dynamic
  { title: "Column 2", dataIndex: "address", key: "2", },// dynamic
  { title: "Column 3", dataIndex: "address", key: "3", },// dynamic
  { title: "Column 4", dataIndex: "address", key: "4", },// dynamic
  { title: "Column 5", dataIndex: "address", key: "5", },// dynamic
  { title: "Column 6", dataIndex: "address", key: "6", },// dynamic
  { title: "Column 7", dataIndex: "address", key: "7", },// dynamic
  { title: "Status", dataIndex: "status", key: "8", fixed: "right", width: 150 }, // dynamic
  { title: "Sub-Status", dataIndex: "substatus", key: "9", fixed: "right", width: 150 }// dynamic
];
```

**Comment by yesmeck** [comment]
You can set `scroll.x` to `true`. And refer to the document:

> if you want to set it to true, you need to add style .ant-table td { white-space: nowrap; }.

**Comment by afc163** [comment]
Maybe we can add a value named `fit-content` which we can add `white-space: nowrap;` defaultly.

```
scroll={{ x: 'fit-content' }}
```

**Comment by afaqahmedkhan** [comment]
I tried `scroll={{ x: 'max-content' }}` and it works for the same issue

**Comment by vmc08** [comment]
> I tried `scroll={{ x: 'max-content' }}` and it works for the same issue

This works for me. Thanks for this

**Comment by andribiz** [comment]
> I tried `scroll={{ x: 'max-content' }}` and it works for the same issue

This should be in official documentation. It will save a lot of time and headache

**Comment by fengyun2** [comment]
ie11下，无论实际宽度多少都是会出现滚动条

**Comment by niz94** [comment]
max-content rocks!

**Comment by niz94** [comment]
> I tried `scroll={{ x: 'max-content' }}` and it works for the same issue

you rock!

**Comment by rahulxyz** [comment]
I tired `scroll={{ x: 'max-content' }}`. Worked perfectly. Thanks.

**Comment by liadmagen** [comment]
Maybe it only happens to me, but it seems that `scroll={{ x: 'max-content' }}` creates another issue with the filtering.

I added a text-filtering, and when filtering by a non-existing text, the table disappears. 
Has anyone encountered this issue or have a solution for this?

**Comment by csulit** [comment]
> I tried `scroll={{ x: 'max-content' }}` and it works for the same issue

Where did you find this?

**Comment by huyywm** [comment]
help me! when i set `scroll={{ x: 'max-content' }}` if table have data, it work so good but if table empty, the table auto expand width of page forever

**Comment by danxczm** [comment]
So, basically don't set exact width to your column... so in the end when you set scroll for 'y' there will be no 'x' scroll - scroll={{ y: 760 }}
