### ISSUE TITLE
Please provide Ant Design without dependencies on components using the Facebook BSD   Patents license

### ISSUE THREAD

**Issue by ABBVelocityDev** [ant-design/ant-design#10180]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will allow us to use Ant Design for our project.

We have been working to use Ant Design for the UI of a new commercial application.  Ant Design is MIT licensed.  However, we've discovered that "npm install antd", adds dependencies that are licensed using the Facebook BSD   Patents license.  Specifically: "rc-editor-mention" and "rc-editor-core" reference "draft-js" 0.10.5 and immutable 3.7.6, which are licensed as Facebook BSD   Patents license.

Please let me know if there is a workaround, or if/when an update may be released that does not add these dependencies.  As it is now, we are likely to be prohibited from using Ant Design in our project.

### What does the proposed API look like?
N/A.

**Comment by yesmeck** [comment]
You can use `babel-plugin-import`, then the `draft-js` won't been bundled to your project if you don't use `Mention` component, the `Mention` component heavily relies on `draft-js`, if do want use `Mention` component, you can find other mention alternatives like https://github.com/signavio/react-mentions
