### ISSUE TITLE
Form表单验证

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#1019]
**问题**：直接看图吧。
![qq 20160216101814](https://cloud.githubusercontent.com/assets/433259/13065375/bcc2416a-d496-11e5-970a-02b46bd7cb15.png)

> 初始化的时候设置了正确的数据类型可以通过验证，只有有修改，值就变了。

**另外**：怎么统一设置提示信息中文。现在的提示信息貌似是写死的，需要逐一配置`message`

@benjycui

**Comment by benjycui** [comment]
下次提问不要直接 @ 某个特定的人可好 。。说不定社区的其他人本来想帮你的，看到也不懒得回复了。。

**Comment by bang88** [comment]
antd的问题，应该没人。

**Comment by benjycui** [comment]
1. [input[type=number]](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=input%20type%20number) 或者直接用 正则校验。
1. `message` 只能逐一配置，如果有可重用的 `message`，用变量重用即可。

另外麻烦阅读下 [CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md) 和 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)。

坦白说，这个也不是 antd 专有的问题。

**Comment by bang88** [comment]
嗯 好，关键是现在用的`rules:[{type:'number'}]`来验证，这种也有问题的话，那这个验证规则在这里有什么用。

**Comment by benjycui** [comment]
校验是直接使用 https://github.com/yiminghe/async-validator
