### ISSUE TITLE
3.4.2 "sideEffects: false" option causes site to render improperly

### ISSUE THREAD

**Issue by plhosk** [ant-design/ant-design#10190]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.2

### Environment
webpack 4.6.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
With 3.4.2 I notice antd components CSS doesn't load on my production site. If I edit node_modules/antd/package.json and remove the line "sideEffects: false" it goes back to normal.

My build makes use of babel-plugin-import, MiniCssExtractPlugin, less-loader to build the css

The development site with hot-reloading works fine, but when i build the production site it looks like no antd css loads at all

excerpt from webpack.prod.js
```
{
        test: /\.(css|less)$/,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          {
            loader: 'less-loader',
            options: {
              modifyVars: antdTheme,
              javascriptEnabled: true,
            },
          },
        ],
      },
```

with 3.4.1 a "yarn build" will produce a vendors.js and vendors.css, but with 3.4.2 the vendors.css does not get generated at all

### What is expected?
The production build worked in 3.4.1 and also works if i remove "sideEffects: false" from node_modules/antd/package.json

### What is actually happening?
unknown

---

**Comment by afc163** [comment]
@Aladdin-ADD

**Comment by yesmeck** [comment]
@yutingzhao1991 Need to release a patch

**Comment by Aladdin-ADD** [comment]
@plhosk @yubozhao @yeliex , I just created a PR (#10197 ) to fix it.

**Comment by yutingzhao1991** [comment]
Thanks, I will release a patch soon.

**Comment by tim-soft** [comment]
I see, so if you are using babel-import-plugin you'll need to use this config `{ libraryName: 'antd', "libraryDirectory": "es", style: true }`. The default option of `lib` doesn't work after this change.
