### ISSUE TITLE
Popover is too far away

### ISSUE THREAD

**Issue by ruoru** [ant-design/ant-design#10205]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
os: mac 10.13,browser: chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
I used a combination of table and Popover components. When I move the mouse to the value of one of the columns in the table, the popover is displayed on the right side, but the display position is too far away.

```
columns: [
        {
          title: '序号',
          dataIndex: 'number'
        },
        {
          title: '标题',
          dataIndex: 'title'
        },
        {
          title: '责任者',
          dataIndex: 'creator'
        },
        {
          title: '朝代',
          dataIndex: 'dynasty'
        },
        {
          title: '年号',
          dataIndex: 'reignTitle'
        },
        {
          title: '馆藏机构数量',
          dataIndex: 'heldBy',
          render: text => <Popover
            content={
              <div>
                {
                  (text.split(',') || []).map(item => <p>{item}</p>)
                }
              </div>
            }
            getPopupContainer={() => this.resultDOM}
            title="馆藏机构列表"
            trigger="hover"
            placement="left"
          >
            <span style={{color: '#1890ff'}}>{(text.split(',') || []).length}</span>
          </Popover>,
        }
      ],


```

### What is expected?
close and nearly

### What is actually happening?
i dont konw

**Comment by yesmeck** [comment]
Your codesandbox has no reproduction.

**Comment by ruoru** [comment]
我不想按照你们那个来，写一个 issue 我要半个小时，综合一句话就是 Popover 在 table 组件中渲染有问题。自己去试试。
