### ISSUE TITLE
为什么git clone的项目有200MB

### ISSUE THREAD

**Issue by chenyiqi** [ant-design/ant-design#10207]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
mac

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
git clone https://github.com/ant-design/ant-design.git

### What is expected?
解释下原因，为什么这个项目的.git文件有238M

### What is actually happening?
.git 238M

**Comment by yesmeck** [comment]
Plz don't ask questions here.

**Comment by afc163** [comment]
`git clone https://github.com/ant-design/ant-design.git --depth=1`
