### ISSUE TITLE
Table filters do not persit on rerender

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#10209]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
Chromium/65.0.3325.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2o11lwl3j0)

### Steps to reproduce
When a table with filters gets rerendered due to props changing any selected filters will be cleared. This can be quite frustrating for the user (try setting a filter in the [linked demo](https://codesandbox.io/s/2o11lwl3j0)).

### What is expected?
Filters remain selected after the component is rerendered.

### What is actually happening?
All filters are cleared.

**Comment by yesmeck** [comment]
Because of filters are applied after `ok` is clicked, if the component is rerendered before `ok` is clicked, filters will be cleared. What is the scenario do you want to rerender the component before `ok` is clicked?

**Comment by megawac** [comment]
I have a dynamic table that receives live data over a websocket. The table can rerender relatively frequently (0.5-1hz) with the new data. It is a frustrating user experience to filter some data only to have your selections reset due to a cell update.

**Comment by yesmeck** [comment]
Fixed in #10332
