### ISSUE TITLE
oadExtraneous: sill resolveWithNewModule string-convert@0.2.1 checking installable status

### ISSUE THREAD

**Issue by dano306** [ant-design/ant-design#10206]
npm install antd babel-plugin-import --save

卡在以下提示，全半天都不动：
loadExtraneous: sill resolveWithNewModule string-convert@0.2.1 checking installable status

**Comment by NICK-DUAN** [comment]
所以你解决了吗？我这也是这情况。

**Comment by donz007** [comment]
搞定了吗

**Comment by oyuyu** [comment]
求教怎么搞得，我也这问题

**Comment by ztplz** [comment]
翻墙
