### ISSUE TITLE
带边框的table使用了fixed 导致 显示有问题

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#10204]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
antd3.2.3 chrome 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8y4w0llzyj)

### Steps to reproduce
带边框带边框的table使用了fixed 导致 显示有问题 。具体打开连接 看 “单据状态” 那一列。

### What is expected?
期望结果应该不会有样式有问题

### What is actually happening?
样式有问题。

**Comment by yesmeck** [comment]
跟边框没关系，你需要留一个 column 不设置 width，来让宽度自适应。

**Comment by xgj1988** [comment]
@yesmeck  兄弟能否 加 个联系方式，我这边还是不行，，我本地 有问题。不知道为什么在codebox 就没问题，，问题是 中间是单据编号和 单据状态 中间 没有 边框。
