### ISSUE TITLE
form demo element id not unique 

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design#10218]
https://ant.design/components/form-cn

<img width="1071" alt="2018-04-24 12 27 19" src="https://user-images.githubusercontent.com/7971415/39166178-f441801c-47ba-11e8-9ea2-78c896e166dc.png">

```bash
[DOM] Found 2 elements with non-unique id #error: (More info: https://goo.gl/9p2vKq) <input type=​"text" placeholder=​"unavailable choice" id=​"error" class=​"ant-input">​…​</input>​#shadow-root (user-agent)</input>​ <input type=​"text" placeholder=​"unavailable choice" id=​"error" class=​"ant-input">​…​</input>​
/components/form-cn/#header:1 [DOM] Found 2 elements with non-unique id #nickname: (More info: https://goo.gl/9p2vKq) <input type=​"text" value id=​"nickname" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​ <input type=​"text" placeholder=​"Please input your nickname" value id=​"nickname" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​
/components/form-cn/#header:1 [DOM] Found 3 elements with non-unique id #password: (More info: https://goo.gl/9p2vKq) <input type=​"password" placeholder=​"Password" value id=​"password" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​ <input type=​"password" placeholder=​"Password" value id=​"password" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​ <input type=​"password" value id=​"password" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​
/components/form-cn/#header:1 [DOM] Found 2 elements with non-unique id #userName: (More info: https://goo.gl/9p2vKq) <input type=​"text" placeholder=​"Username" value id=​"userName" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​ <input type=​"text" placeholder=​"Username" value id=​"userName" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​
/components/form-cn/#header:1 [DOM] Found 2 elements with non-unique id #username: (More info: https://goo.gl/9p2vKq) <input type=​"text" value=​"benjycui" id=​"username" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​ <input type=​"text" placeholder=​"Please input your name" value id=​"username" data-__meta=​"[object Object]​" data-__field=​"[object Object]​" class=​"ant-input">​…​</input>​
/components/form-cn/#header:1 [DOM] Found 2 elements with non-unique id #warning: (More info: https://goo.gl/9p2vKq) 
```

**Comment by danedavid** [comment]
well, assigning different `id`s like `userName1` will look bad in the docs, won't it ?

**Comment by America-first-melon** [comment]
没人解决这个吗？

**Comment by afc163** [comment]
现阶段很难解决，除非给 form 加 id。

**Comment by America-first-melon** [comment]
找到了其他的解决方法，这个情况不是很常见。谢谢

**Comment by zombieJ** [comment]
> @afc163 :
> 现阶段很难解决，除非给 form 加 id。

这样如何？
```jsx
<Form id="abc">
...
</Form>
```

转换成：
```html
<form id="abc">
  <input id="abc_name" />
</form>
```

**Comment by qq645381995** [comment]
想法是好的，但是这是庞大的工作量

**Comment by afc163** [comment]
> 顺带把一个组件可以用多个 form 给支持了。

@qq645381995 https://github.com/react-component/form/pull/190 社区已经加上这个支持了，antd 也快了。

**Comment by afc163** [comment]
@zombieJ 对，差不多这样。

**Comment by afc163** [comment]
Form 最好有个默认 id，尽可能避免覆盖全局变量：#12937。

**Comment by ddzy** [comment]
> 没人解决这个吗？

+1

**Comment by vylan** [comment]
在处理动画时也遇到了这个问题，期待给每个Formitem一个全局唯一的id

**Comment by zhutiancheng2** [comment]
默默的问一下，现在这个问题解决了么=-=

**Comment by afc163** [comment]
@zhutiancheng2 给 Form 加个 name 就行了。

**Comment by spipatpunlop** [comment]
@afc163 I got just one form and I tried to add name. Warning still appeared. Thank you.

**Comment by afc163** [comment]
@spipatpunlop Please provider codesandbox to reproduce.

**Comment by lishaoh** [comment]
@afc163 我也是遇到了这种情况，给form加了name还是出现warning

"antd": "^3.25.2",

**Comment by bihongbin3027** [comment]
升级版本试试 我刚加了name 确实解决了这个问题

**Comment by bellbellu** [comment]
4.2.0版本，也是遇到了这个问题，Form上加name也出现问题
![image](https://user-images.githubusercontent.com/48513440/94505556-ebf69b00-023d-11eb-916e-563385a93b86.png)

**Comment by Haley-Zhu** [comment]
> 4.2.0版本，也是遇到了这个问题，Form上加name也出现问题
> ![image](https://user-images.githubusercontent.com/48513440/94505556-ebf69b00-023d-11eb-916e-563385a93b86.png)

You need to make sure each form have unique name. 
Like '<Form name='msgForm1 />', '<Form name='msgForm2 />'

**Comment by YazRae** [comment]
if you are using the same form multiple times in the same component for different reason this could happen, a condition must be considered every time the form component renders, like below:
`export default function Form({ updateForm = false }) {
  return (
    <>
      <Form.Item
        label="Name"
        name={updateForm ? "nameUpdate" : "name"}
        rules={[
          {
            required: true,
            message: "Please input your Name!",
          },
        ]}
      >
        <Input autoComplete="off" />
      </Form.Item>
    </>
  );
}`
