### ISSUE TITLE
Table sorter passed sort direction

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#10213]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a column which can have cells with null data. The null data should always be sorted to the bottom regardless of sort order (ascend descend). I would like to know the sort order in my table column's `sorter`. This will allow me to know for `null` cells to return `-1` when sorting in ascending order and `1` when sorting in descending order.

### What does the proposed API look like?
The column `sorter` will be passed an additional string argument which can be either `"ascend"` or `"descend"`

```
const columns = [{
  title: 'Name',
  dataIndex: 'name',
  sorter: (a, b, sortOrder) => {
    if (a.name != null && b.name != null) {
      a.name.localeCompare(b.name);
    }
    if (a.name) {
      return sortOrder === 'ascend' ? 1 : -1;
    }
    if (b.name) {
      return sortOrder === 'ascend' ? -1 : 1;
    }
    return 0;
  },
}]
```

**Comment by yesmeck** [comment]
Sounds reasonable, tagging as `good first issue`.

**Comment by kumarashwin** [comment]
I'd like to tackle this one. I've actually already managed to resolve it in a rough way and just need time to read through the Contributing document and write the appropriate tests.
