### ISSUE TITLE
Divider renders incorrectly with setting orientation and dashed at the same time

### ISSUE THREAD

**Issue by zheeeng** [ant-design/ant-design#10216]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
React 16.3

### Reproduction link
[https://codepen.io/zheeeng/pen/mLVZxv](https://codepen.io/zheeeng/pen/mLVZxv)

### Steps to reproduce
Check the reproduction

### What is expected?
Text is positioned by orientation and only dashed line are rendered.

### What is actually happening?
Dashed line and solid line are both rendered.

**Comment by afc163** [comment]
Sorry to duplicate your job, didn't notice that~ 😅
