### ISSUE TITLE
ScrollNumber.d.ts is Error Generic type 'Component<P, S>' requires between 0 and 2 type arguments.

### ISSUE THREAD

**Issue by yaempioy** [ant-design/ant-design#10211]
I had used for React with TypeScript 
"@types/react": "16.0.36"
"typescript": "2.8.3"

Failed to compile. -> ../node_modules/antd/lib/badge/ScrollNumber.d.ts
(48,43): Generic type 'Component<P, S>' requires between 0 and 2 type arguments.

**Comment by gburt** [comment]
See the fix in https://github.com/ant-design/ant-design/issues/10108#issuecomment-381875179
