### ISSUE TITLE
upload 上传文件 是否有增加限制文件类型 或文档大小的功能

### ISSUE THREAD

**Issue by robin536180** [ant-design/ant-design#10214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1、上传文件时 较大的文件很慢
2、什么文件 都可以上传 不安全，只是提示限制类型，还不够
3、展示类型 可以加个表格类型的，因为表格展示的形式 更直接，更全面，大小啊 进度啊 都可以一目了然

### What does the proposed API look like?
limit: [
{fileType: ['doc', 'excel', 'pdf'], message: '上传的文件不符合类型，请重新选择。' }
{fileSize: 200 * 1024 * 1024, message: '单个文件大小不超过200MB。' }
]

**Comment by yesmeck** [comment]
请参考 https://ant.design/components/upload-cn/#components-upload-demo-avatar
