### ISSUE TITLE
表格是否可以添加 点击某一行，这行数据为显示状态，添加背景色等

### ISSUE THREAD

**Issue by robin536180** [ant-design/ant-design#10224]
@jhsu @He-zhiyong @pmq20  [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1、有的时候不需要 复选框 或单选框来 操作数据
2、点击某行，可以再其他区域 通过获取某行的数据 做其他的功能，

### What does the proposed API look like?
onRow={record => this.onRowClick(record)} 背景显示高亮 这行获取焦点

**Comment by yesmeck** [comment]
You can achieve this feature by combine `onRow={() => ({ onClick() {} })}` and `rowClassName`.

**Comment by wp88** [comment]
> You can achieve this feature by combine `onRow={() => ({ onClick() {} })}` and `rowClassName`.

How to combine `onRow={() => ({ onClick() {} })}` and `rowClassName`?
