### ISSUE TITLE
为什么自定义表单控件不能是函数式组件

### ISSUE THREAD

**Issue by jasonxia23** [ant-design/ant-design#10228]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
浏览器

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-customized-form-controls](https://ant.design/components/form-cn/#components-form-demo-customized-form-controls)

### Steps to reproduce
无需重现

### What is expected?
一些场景下，自定义表单组件并不需要维护内部状态，这种情况下限制不能使用函数式组件

### What is actually happening?
限制不能使用函数式组件

**Comment by dengfuping** [comment]
@jasonxia23 Because the value of `Form Item` is designed to be editable and submitted. If you just want to display its value, there is no need to use `Form`.

**Comment by yesmeck** [comment]
目前 Form 的实现依赖控件的 ref，而函数式组件没有 ref，所以目前只能支持非函数式的组件。

Then current implement of Form rely on the ref of form controls, but the functional component doesn't have ref.
