### ISSUE TITLE
Card里边的Tabs的size希望可以是配置项

### ISSUE THREAD

**Issue by chaegumi** [ant-design/ant-design#10223]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我想要size="small"的，现在写死是large

### What does the proposed API look like?
tabSize="small" ?

**Comment by afc163** [comment]
Could you send us a PR?

**Comment by isoloist** [comment]
can i set tab title size=small now ?

**Comment by mytototo** [comment]
I have the same issue. How is it possible to change the tabs size in a card ?

**Comment by chaegumi** [comment]
@isoloist @mytototo 😅They asked me to send a PR, I tried https://ant.design/docs/react/contributing-cn, but i do not finish this work.U can use <Tabs type="card"> instead.
