### ISSUE TITLE
setFieldsValue not work in Checkbox onChange event

### ISSUE THREAD

**Issue by ltaoo** [ant-design/ant-design#10238]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
Mac  Chrome 版本 66.0.3359.117（正式版本）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6vp86p69jw)

### Steps to reproduce
选择 Checkbox 任意项如「商品酷」

### What is expected?
「品牌返利中心」（value 值为 5）的 Checkbox 被选中。

### What is actually happening?
「品牌返利中心」（value 值为 5）的 Checkbox 未被选中。

---
该需求预期实现`CheckboxGroup`中选择任意一项，能够控制另一个`Checkbox`。
开始的时候想可能`onChange`内`setFieldsValue`会又触发`onChange`而导致无限调用`onChange`，但加了只在某些条件下才`setFieldsValue`，还是无效。

而为了做对比，新增了`Button`组件，`onClick`和`onChange`的逻辑完全一致，`onClick`是有效的，并且`setFieldsValue`并不会触发`onChange`，所以开始的顾虑是不存在的。

这更加让我感到困惑为什么`onChange`内`setFieldsValue`不起作用。

**Comment by yutingzhao1991** [comment]
因为你 `setFieldsValue` 的操作会被组件 onChange 之后自己的操作给覆盖掉。

参考 https://codesandbox.io/s/n77367q7wm 这个，加上 setTimeout 可以解决这个问题。

**Comment by afc163** [comment]
别这样做，请仔细阅读 https://ant.design/components/form-cn/#this.props.form.getFieldDecorator(id,-options)

如果需要对 value 做修剪，应该用 `normalize`。

**Comment by ltaoo** [comment]
好的，谢谢 @afc163 。

**Comment by ltaoo** [comment]
我除了要选中 Checkbox 外，其实还要将一个 Switch 设置为 true。

![image](https://user-images.githubusercontent.com/15319872/39243733-1ef462b4-48c1-11e8-88e2-e05377d50dbc.png)

这种情况就只能用`setFieldsValue`。
但是使用`normalize`时，`setFieldsValue`还是无效，将`normalize`改为`getValueFromEvent`就可以了。

```js
const { getFieldValue, setFieldsValue } = this.props.form;
    const prev = getFieldValue("packages") || [];
    const brand = getFieldValue("brand");
    const next = _next || [];
    // 如果选中第六个，就将第五个和 Swtich 变为选中状态
    if (next.includes(6) && !prev.includes(6)) {
      setFieldsValue({
        brand: true
      });
      return next.includes(5) ? next : [...next, 5];
    }
```

由于`getValueFromEvent`没有给`prev`参数，所以使用`getFieldValue`替代。

不过还是很好奇为什么`setFieldsValue`不起作用，是像  @yutingzhao1991  提到的吗？而且 `setTimeout`这种做法合不合适呢，就使用上来说这个似乎更简单一点，虽然有点 hack 的感觉。

总之，非常感谢两位。

**Comment by afc163** [comment]
setFieldsValue 用于组件间的关联操作，getFieldValue 和 normalize 是自带的双向绑定的数据流中的一个步骤。
