### ISSUE TITLE
关于iconfont本地化和覆盖less变量的问题

### ISSUE THREAD

**Issue by wxxcarl** [ant-design/ant-design#10236]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
webpack3.8.1

### Reproduction link
[https://ant.design/docs/react/customize-theme](https://ant.design/docs/react/customize-theme)

### Steps to reproduce
使用定制主题的第二种方式，
  //style.less 

   - @import "~antd/dist/antd.less";
   - @import "./reset.less";

//reset.less

- @icon-url: "/font/iconfont";
- @body-background: #f8f8f8;
- ……

### What is expected?
1. 只加载本地iconfont
2. body的背景颜色替换为f8f8f8

### What is actually happening?
1. 加载了本地iconfont，但是同时请求了alicdn上的font
2. body颜色仍然是#fff,新定义的#f8f8f8被重新覆盖了

**Comment by afc163** [comment]
如果使用了第二种方式，不要开启 babel-plugin-import 的 style 属性。
