### ISSUE TITLE
建议TimePicker的分秒设置step参数

### ISSUE THREAD

**Issue by Xiu-Lan** [ant-design/ant-design#1023]
因为有时候进行时间选择的时候，前提可能是以5分钟为步数，但是现在的分秒是以1为步数。虽然有hideDisabledOptions和disabledMinutes的设置，可以实现以5分钟为步数，但是，若是disabledMinutes有其他限制条件，可能处理上就有些不大理想。
建议TimePicker的分秒可以设置step参数，使得TimePicker组件更加灵活

**Comment by benjycui** [comment]
> 但是，若是disabledMinutes有其他限制条件，可能处理上就有些不大理想。

可以给个例子？

**Comment by Xiu-Lan** [comment]
比如说小于10分钟的时间不可以选择，又要求以5为步数显示，若是hideDisabledOptions设置为true，则,0,5两个选择也会显示不了，得另外提示小于10分钟的时间不可以选择。如果有了step参数，那么hideDisabledOptions就可以很明确给用户根据需要判断要不要显示0,5两个选择

**Comment by Xiu-Lan** [comment]
使用DatePicker组件时，选择日期为2016-02-17，然后根据操作需要清除日期，将value设为“”时，DatePicker就显示无值；而使用TimePicker组件时，选择时间为18:37:00，然后根据操作需要清除时间，将value设置为""时，TimePicker显示的还是18:37:00。这个情况好像有点问题？value为“”时，TimePicker应该显示无值吧

**Comment by benjycui** [comment]
> 比如说小于10分钟的时间不可以选择，又要求以5为步数显示，若是hideDisabledOptions设置为true，则,0,5两个选择也会显示不了，得另外提示小于10分钟的时间不可以选择。

这交互设计的。。无法选择的直接隐藏就可以了，为什么还要加提示，用户没有这么笨吧。。

**Comment by benjycui** [comment]
> 而使用TimePicker组件时，选择时间为18:37:00，然后根据操作需要清除时间，将value设置为""时，TimePicker显示的还是18:37:00。这个情况好像有点问题？

这个 fork 下 http://codepen.io/anon/pen/pgdXYp?editors=001 提供必现的 demo，THX

**Comment by Xiu-Lan** [comment]
而使用TimePicker组件时，选择时间为18:37:00，然后根据操作需要清除时间，将value设置为""时，TimePicker显示的还是18:37:00。这个情况好像有点问题？

这个问题我发现0.12.x版本已经修复了
