### ISSUE TITLE
Input.Group组件box-shadow效果被遮盖

### ISSUE THREAD

**Issue by SeanGol** [ant-design/ant-design#10230]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
任意环境（官网demo即可重现）

### Reproduction link
[https://ant.design/components/input-cn/#components-input-demo-group](https://ant.design/components/input-cn/#components-input-demo-group)

### Steps to reproduce
（官网demo即可重现）
使用Input.Group组件，并设置compact属性为true，
Input.Group组件内部嵌套两个以上任意Input、select组件均可

当在填写group中的某一输入框时，box-shadow属性效果被遮盖

### What is expected?
每个内部嵌套的组件处于:focus状态时，right侧的box-shadow属性效果不被遮盖
![image](https://user-images.githubusercontent.com/8014327/39181533-89d1d632-47ec-11e8-9b16-5a16d22a505b.png)
![image](https://user-images.githubusercontent.com/8014327/39181548-96bdf9a2-47ec-11e8-86f1-e8e72891cb58.png)

### What is actually happening?
每个内部嵌套的组件处于:focus状态时，right侧的box-shadow属性效果被下一组件遮盖
![image](https://user-images.githubusercontent.com/8014327/39181589-b99462ea-47ec-11e8-8d31-fcc7d4630255.png)
![image](https://user-images.githubusercontent.com/8014327/39181622-d52d066a-47ec-11e8-8001-3eec53e61e14.png)

---
建议修复方案：
ant-design/components/input/style/mixin.less（270行）
去除z-index: auto属性

并在每个被嵌套的组件添加
&:focus {
  z-index: 1;
  border-right-width: 1px;
}

**Comment by wmzhong** [comment]
I will handle this issue.
