### ISSUE TITLE
Ability to override table className

### ISSUE THREAD

**Issue by mateeyow** [ant-design/ant-design#10237]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will enable us to override some class or styles in the html table. One example I can conjure is adding `table-layout: fixed` to the table style.

This is related to Issue #7917 but doesn't seem to work anymore.

### What does the proposed API look like?
<Table className='extra-class' style={{ tableLayout: 'fixed' }} />

This can be done by editing the code on https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L932 to this:

```js
const classString = classNames({
      [`${prefixCls}-${this.props.size}`]: true,
      [`${prefixCls}-bordered`]: this.props.bordered,
      [`${prefixCls}-empty`]: !data.length,
      [`${prefixCls}-without-column-header`]: !showHeader,
      className
    });
```

Or removing `style` to this line https://github.com/ant-design/ant-design/blob/52c8f34a734356f6e3076df87c2cf48fde20d25e/components/table/Table.tsx#L928

**Comment by afc163** [comment]
The className is binded to table wrapper already: https://github.com/ant-design/ant-design/blob/52c8f34a734356f6e3076df87c2cf48fde20d25e/components/table/Table.tsx#L996
