### ISSUE TITLE
RangePicker在form里面  getFieldDecorator 不能通过state 设置 initialValue

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#10232]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
antd3.4.3 chrome 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ko974kp9ko)

### Steps to reproduce
先选择日期（不要是今天），然后点击按钮无效  >但是先点击按钮就可以设置

### What is expected?
因为我设置了state 的值，按道理应该修改我的RangePicker的值。但是并没有。

### What is actually happening?
RangePicker的值并没有修改

**Comment by dengfuping** [comment]
@xgj1988 You should use `value` prop in `RangePicker` not `initialValue` in `getFieldDecorator`, because `initialValue`  is immutable.

**Comment by xgj1988** [comment]
@dengfuping  but   i can  modify  the  initialValue by button click  when   i not change the value  by  RangePicker . so  i think the initialvalue is not immutable
