### ISSUE TITLE
upload组件在picture或者picture-card类型时的兼容性问题

### ISSUE THREAD

**Issue by EthanWan** [ant-design/ant-design#10245]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在使用upload组件上传pdf文件的时候遇到了一个问题就是，在某些浏览器中（比如chrome）不支持在img标签中打开pdf的base64数据流，在点击预览的时候我可以自己使用react-pdf-js插件去解决这个问题，但是在组件内部的预览用的仍然是img标签。因此，我希望：1. 在upload组件内部将不同的文件MIME类型的兼容性完善一下，2. 或者能够自定义这种图片展示形式

### What does the proposed API look like?
``` javascrpt
// 如
<Upload
   pictureList={<div><img src='' /><span>...</span></div>}
>
</Upload>
```

**Comment by EthanWan** [comment]
@yutingzhao1991 
This is a browser compatibility issue.  some browser do not support thumbUrl which MIME type is 'applcation/pdf'

**Comment by afc163** [comment]
I think @yutingzhao1991 's solution is good enough.
