### ISSUE TITLE
Select组件分页加载bug

### ISSUE THREAD

**Issue by chenyihao2621023** [ant-design/ant-design#10248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
win10 、 Chrome 版本 65.0.3325.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w70x26oymk)

### Steps to reproduce
快速滚动触发 onPopupScroll 事件。判断加载到底部，加载数据后，滚动条位置偏移(会回到顶部，或者向上偏移一段距离)

### What is expected?
加载数据后，像触发原生onScroll事件一样， 滚动条保持加载数据前的位置

### What is actually happening?
加载数据后，滚动条位置偏移(会回到顶部，或者向上偏移一段距离)

**Comment by yesmeck** [comment]
这是正常的行为吧，高度变了，滚动条肯定会变化。
