### ISSUE TITLE
建议- Form - 表单校验这块感觉API比较晦涩

### ISSUE THREAD

**Issue by swindme** [ant-design/ant-design#1024]
#### 问题描述
比如这个demo： http://ant.design/components/form/#demo-validate-other

```javascript
<FormItem
          label="邮箱："
          labelCol={{ span: 7 }}
          wrapperCol={{ span: 12 }}
          hasFeedback>
          <Input type="email" placeholder="onBlur 与 onChange 相结合"
            {...getFieldProps('email', {
              validate: [{
                rules: [
                  { required: true },
                ],
                trigger: 'onBlur',
              }, {
                rules: [
                  { type: 'email', message: '请输入正确的邮箱地址' },
                ],
                trigger: ['onBlur', 'onChange'],
              }]
            })}/>
        </FormItem>
```
存在问题是
- 干扰组件的分类和层级关系   
这个demo里面，首先是校验代码远远大于组件本身，尤其多个表单项使用时候，整体表单会很庞杂，弱化了react组件使用本身应该体现组件的分类和层级关系, 从美观和使用上都不太顺手。   

- 配置项太重，喧宾夺主  
react配置项一般都比较轻，使用是，组件读取属性，进行处理，而这个demo是，首先注入了表单name，然后函数返回一个对象，再把对象属性值展开，放到props，而且都是外部完成的，感觉有点违背react的设计，react好像大多是组件本身具备行为，而不是通过外部函数辅助行为。而表单其实最重要的是字段，也不容易看清有哪些字段，校验有点喧宾夺主。

- 这个createForm也看起来奇怪, 感觉不太符合react的设计，觉得react设计思路上，组件封装了行为，暴露到外面的函数一般是比较少的，一般使用都是找组件使用，而不是找函数使用。

```javascript
const createForm = Form.create;
... 
Demo = createForm()(Demo); // 函数执行返回函数再执行，感觉也不透明
```
#### 期望方案
  - 简单的校验配置   
以前很多类似校验，也是元素上配置校验声明，但都会很简单,类似这样，整体表单会看起来清晰很多,至少一眼能看清表单本身有哪些字段
```
<input type="text" name="user" verify={users,required,minlen(3)]}>
```
- 校验可以考虑高阶组件，在不影响表单结构的情况下，用校验组件包装表单项处理

**Comment by TinyJiang** [comment]
+1

**Comment by Yuliang-Lee** [comment]
Form这块确实比较难懂啊..应该优化一下的

**Comment by afc163** [comment]
API 有一定程度参考了：http://erikras.github.io/redux-form/

**Comment by swindme** [comment]
redux-form 的 demo，react这部分结构就比较清晰，基本看上去还是简洁的表单。 校验和表单分离是有好处的，一般表单项可能最关心是字段name，其次才是辅助的校验

http://erikras.github.io/redux-form/#/examples/asynchronous-blur-validation?_k=zdaqvx
对比

```
<input type="text" placeholder="Username" {...username}/>
```

```
<Input type="email" placeholder="onBlur 与 onChange 相结合"
            {...getFieldProps('email', {
              validate: [{
                rules: [
                  { required: true },
                ],
                trigger: 'onBlur',
              }, {
                rules: [
                  { type: 'email', message: '请输入正确的邮箱地址' },
                ],
                trigger: ['onBlur', 'onChange'],
              }]
            })}/>
```

**Comment by someok** [comment]
这个相对看着清楚很多。

对于表单这块我觉得应该将焦点集中在这几块：

   - 表单初始化
   - 验证

至于布局之类的应该让用户结合 layout 自己处理，这个我觉得参照 bootstrap 的搞法就行了。

**Comment by benjycui** [comment]
@swindme 其实你提的 redux-form 和楼顶的例子，只不过是把 `username` `users` `required` 等的定义放到了别处：

```xml
<input type="text" placeholder="Username" {...username}/>
```

```xml
<input type="text" name="user" verify={users,required,minlen(3)]}>
```

antd 中也可以用变量把 `getFieldProps` 的返回值存起来再用

```jsx
const emailProps = getFieldProps('email', {
  validate: [{
    rules: [
      { required: true },
    ],
    trigger: 'onBlur',
  }, {
    rules: [
      { type: 'email', message: '请输入正确的邮箱地址' },
    ],
    trigger: ['onBlur', 'onChange'],
  }]
});

// JSX 部份就简单了
<Input {...emailProps} type="email" placeholder="onBlur 与 onChange 相结合"/>
```

然后 `Form.create` 就是使用了高阶组件啊。。不过是包装整个表单，而非单个表单域。这样的好处是把数据收集功能也一并做了，如果只是包装单个表单域的话，数据收集就要额外的代码了，[之前的版本](http://011x.ant.design/components/form/#demo-horizontal-form) 就是这样。

**Comment by swindme** [comment]
@benjycui 这个写法ok的，所以应该被表单校验demo误导了， 
demo一般是开发者参照和推荐的使用方式，这个demo可以改改觉得就ok了。

**Comment by benjycui** [comment]
改了个 demo，see: https://github.com/ant-design/ant-design/commit/a0c01b54e8a96e65a355bdef159a714484e919f0#diff-ca1ccf9189fb967e45a54d6a72b7ba51R130

不过对有多个表单域，大概就 7、8 个以上时，`emailProps` 的定义与其使用的位置距离就会比较远，个人觉得反而不好阅读。

**Comment by swindme** [comment]
> emailProps 的定义与其使用的位置距离就会比较远，个人觉得反而不好阅读。

是的，但是庞杂的校验配置，感觉更影响阅读。觉得校验只是辅助，表单项本身清晰感觉更重要, 因为没有校验，表单也能用。
- 表单项本身清晰
- 表单项校验内容清晰（这块 verify="users,required"  这种是直观的）

比如这样呢：
```
<input type="text" name="user" {...validate(username,required)}>
```

**Comment by astwyg** [comment]
我觉得作为一个业务系统的前端组件库, 根本不需要做表单验证啊..

前端进行的表单验证到了后端还得再跑一遍, 你这边封装的再好, 后端都要重新实现一遍, 维护难度太大, 真用起来的时候, 肯定是结合自己的后端或者API gateway框架, 封装一层类似于Django的From来用.

**Comment by someok** [comment]
前端后端都需要的，不可能只在后端做验证

WANG. YG <notifications@github.com>于2016年2月19日周五 15:32写道：

**Comment by astwyg** [comment]
@someok  我的意思是前端表单验证是由后端代码生成的, 总不能前端写一套表单验证, 后端再写一套吧.. 那样维护难度太大.

**Comment by benjycui** [comment]
@swindme 真心觉得这只是一个编程技巧的问题

```jsx
<input type="text" name="user" {...validate(username,required)}>

<input {...getFieldProps('user', {rules: [ username, required ]})} type="text" />
```

**Comment by swindme** [comment]
@benjycui  上面这种确实可以。
还有个办法是 这种看起来比较像原生，在react props方面会透明很多，会不会好些
```
<Input type="text" name="user" validate={[username,required]}>
```

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/issues/610

**Comment by afc163** [comment]
```jsx
<Input {...emailProps} type="email" placeholder="onBlur 与 onChange 相结合"/>
```

例子可以都写成这种，比较好看。

**Comment by afc163** [comment]
上面这种写法还有一个好处是，用户可以通过 `console.log(emailProps);` 来理清附加了哪些属性。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/commit/ce11c258b3fa021144fc39c8f1018b65676d9567

**Comment by dongli** [comment]
验证的规则写法也没有一个完整的描述。

**Comment by benjycui** [comment]
@dongli 

![image](https://cloud.githubusercontent.com/assets/3580607/21087901/fcb7fcc8-c064-11e6-8f49-96f354ca15a2.png)

同时维护多份相似的文档太累。

**Comment by hangyangws** [comment]
看了 ： [这个代码demo](https://github.com/ant-design/ant-design/commit/a0c01b54e8a96e65a355bdef159a714484e919f0#diff-ca1ccf9189fb967e45a54d6a72b7ba51R130)  
大家觉得 *庞杂的校验配置，感觉更影响阅读* ,  那么为什么不把抽离一个配置项文件，  
把：

```javascript
const passProps = getFieldProps('pass', {
  rules: [
    { required: true, whitespace: true, message: '请填写密码' },
    { validator: this.checkPass },
  ]
});

// ...
```

这样的配置项目放在单独文件里面，使用的时候 import 不就好了。  
这样维护也好，使用也简洁了。
