### ISSUE TITLE
DatePicker 组件如果只修改年份或月份不会触发 onChange 事件，value 没有变化

### ISSUE THREAD

**Issue by AceLeeWinnie** [ant-design/ant-design#10242]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.12.7

### Environment
随便一个版本

### Reproduction link
[https://ant.design/components/date-picker-cn/#header](https://ant.design/components/date-picker-cn/#header)

### Steps to reproduce
1. 先选择一个年月日
2. 再重新选择一个年份或月份
3. 点击确定

### What is expected?
只选择年份或月份时，也会触发 onChange 事件，使 value 值正确显现

### What is actually happening?
只选择年份或月份时，不会触发 onChange 事件，value 值还是原来的

---
所有版本都有这个问题

**Comment by havywu** [comment]
@AceLeeWinnie The same problem，have you solved it？

**Comment by afc163** [comment]
It is by designed.

**Comment by LeoLiangJin** [comment]
You can do this in this way!  <DatePicker mode='year' onPanelChange={(v) => yourCode(v)}/>.
