### ISSUE TITLE
动态验证表单(validateFieldsAndScroll)问题

### ISSUE THREAD

**Issue by wangzhongquan** [ant-design/ant-design#10244]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
Chrome

### Reproduction link
[https://codepen.io/wangzhongquan/pen/jxrWyM?editors=0011](https://codepen.io/wangzhongquan/pen/jxrWyM?editors=0011)

### Steps to reproduce
点击new 按扭，弹出表单，直接点右下角save，表单提示有两项必填，勾选第一项flag，现在必填项变成4个，直接点save，不会触发后两项必填的验证，但我再次勾选flag再取消，即可验证4项必填

### What is expected?
无论是首次打开弹出框，还是多次点击flag，当点击save时都能够触发正确的校验

### What is actually happening?
需要多次切换FLAG状态，validateFieldsAndScroll方法才能够正确验证

**Comment by afc163** [comment]
Your codepen cannot be open correctly.
