### ISSUE TITLE
Tooltip in Button can't appear

### ISSUE THREAD

**Issue by BlackGanglion** [ant-design/ant-design#10241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

### Reproduction link
[https://codepen.io/BlackGanglion/pen/bMeEVN?editors=0010](https://codepen.io/BlackGanglion/pen/bMeEVN?editors=0010)

### Steps to reproduce
When mouse up the <Icon /> which is in the <Button />，the Tooltip can't appear

### What is expected?
Tooltip appear

### What is actually happening?
Tooltip can't appear

**Comment by dengfuping** [comment]
@BlackGanglion `Button` should be wrapped by `Tooltip` like
```
<Tooltip title="This is title">
  <Button>Button</Button>
</Tooltip>
```
