### ISSUE TITLE
How to add / custom theme in Menu component

### ISSUE THREAD

**Issue by jamesriady** [ant-design/ant-design#10247]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.2

### Environment
Version 66.0.3359.117 (Google Chrome)

### Steps to reproduce
I have a problem with Menu component.. It's only has two kinds of theme, dark & light.. How If I want to add more theme color? like blue, red, green.. I want to modify the component color..

### What is expected?
I want to change / modify / add theme color that can be used in `Menu` component

Can I really modify the component background color?

### What is actually happening?
I have tried using style to change the background color.. but it seem does not work, I set the background color style in Menu but it does not change the Menu.Item or Menu.SubMenu color

---

**Comment by afc163** [comment]
https://ant.design/docs/react/customize-theme

**Comment by SuichiM** [comment]
dunno if still relevant but as @afc163 says, if you customize the theme and override the 
```
@menu-dark-bg: @layout-header-background;
```
to
```
@menu-dark-bg:  @primary-color;
```
you will get you dark theme with your @primary-color as @background-color of your menu
