### ISSUE TITLE
[Input.TextArea] suffix and prefix support

### ISSUE THREAD

**Issue by fantua** [ant-design/ant-design#10249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature will be very useful to add a helper (question/information icon) to `Input.TextArea` component.

### What does the proposed API look like?
Same as in `Input` component.

**Comment by afc163** [comment]
Try Input.Group

**Comment by fantua** [comment]
Hi, @afc163 

I need something like this, but with TextArea (multiline):
```js
<Input
    placeholder="Enter value"
    suffix={
        <Tooltip title="Some help information">
            <Icon type="question-circle-o" />
        </Tooltip>
    }
/>
``` 
![screen](https://image.prntscr.com/image/O1JfGYYGTN2FPjDeVU7MWw.png)

With `Input.Group` looks like I can do only something like that:
```js
<Input.Group>
    <Col xs={10}>
        <Input.TextArea rows={3}/>
    </Col>
    <Col xs={1}>
        <Icon type="question-circle-o" />
    </Col>
</Input.Group>
```
![screen](https://image.prntscr.com/image/cd_AhWJ2TMS94je4NOQYgw.png)

But it's look a little bit weird, or I'm missing something?

**Comment by afc163** [comment]
suffix and prefix only for single-line Input by designed, you have to customise the style by youself. 😈

**Comment by joenot443** [comment]
I would also appreciate this. Is there any reason why you're opposed to implementing it?

**Comment by Chuque** [comment]
@joenot443 I believe they will not implement it because the component will not look good. Try to draw how it would look like to see if it doesn't look weird.
