### ISSUE TITLE
Bower for antd or cdn for .less

### ISSUE THREAD

**Issue by NugzarGaguliya** [ant-design/ant-design#10251]
- [+] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to include .less files in my html, so then dynamically change variables.

### What does the proposed API look like?
One solution is install antd in specific folder. That can do bower, but I can't find antd on bower.
Second solution is using cdn, but less files doesn't seems to be there.

**Comment by afc163** [comment]
https://unpkg.com/antd@3.4.3/dist/
