### ISSUE TITLE
When ant design has own rich text editor? 

### ISSUE THREAD

**Issue by julin69** [ant-design/ant-design#10255]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We need a rich text editor to solve html edit problem,but other plugins is not suit for ant-design,and has a lot of problems

### What does the proposed API look like?
I need a rich text editor with less config,and can edit freely

**Comment by yesmeck** [comment]
Duplicate of #1083

**Comment by TRamainoane** [comment]
nn

**Comment by MyIvory** [comment]
### 

> [`_****_`](url)
