### ISSUE TITLE
Select.Option 中放入Input 后，Input无法编辑

### ISSUE THREAD

**Issue by QianWenW** [ant-design/ant-design#10252]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能够重复添加选项，不是tags的功能

### What does the proposed API look like?
使input可编辑

**Comment by afc163** [comment]
不知所云，建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)。
