### ISSUE TITLE
Tree 树形控件 异步数据加载，onLoadData 方法被调用两次

### ISSUE THREAD

**Issue by ada87** [ant-design/ant-design#10253]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
lasted

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
I copy the code and rewrite funtion "onLoadData" with  http.fetch (return a Promise) 。 like this:
```javascript
   onLoadData = (treeNode) => {
        console.log(treeNode);
        if (_.isArray(treeNode.props.children) && treeNode.props.children.length > 0) {
            return new Promise((resolve) => resolve());
        }
        return Ajax.FETCH(`/api/tree/${treeNode.props.eventKey}`).then(resp => {
            treeNode.props.dataRef.children = resp.data;
            this.setState({
                treeData: [...this.state.treeData],
            });
        });
    }
```

But in every time I expand a node. the onLoadData  was be call twice and the Ajax Request send twice.

### What is expected?
Ajax request only send single time.

### What is actually happening?
Ajax request send twice.

**Comment by zombieJ** [comment]
Pls clean up `node_modules` and reinstall. `rc-tree` - `1.8.3` already fix this.

ref: https://github.com/react-component/tree/commit/e64a679b6665787e49d419fea76f667ea743f86b

**Comment by sofafan** [comment]
我在最新的版本当中遇到同样的问题，onLoadData同样被调用了两遍。请问什么情况下，还会导致onLoadData被调用两遍

**Comment by FrameJ** [comment]
antd@4.17.0, rc-tree@5.3.0 
这个问题又出现了

**Comment by BrightXW** [comment]
tree组件中，我也遇到类似的问题，在loadData中请求接口，用fetch方法，会发出两条请求
![image](https://user-images.githubusercontent.com/20368898/145571309-871cb217-f738-418d-a9a9-4d8b43cf7a5b.png)
![image](https://user-images.githubusercontent.com/20368898/145571349-16b4a1a4-f994-4c18-89eb-4c018f1567f7.png)

**Comment by liby2006** [comment]
antd@4.19.1  rc-tree@5.4.4 也有问题，loadData 调了两次
