### ISSUE TITLE
希望Table的Column可以设置垂直向上、向下对齐的方式

### ISSUE THREAD

**Issue by fengyuxx** [ant-design/ant-design#10261]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望Table的Column可以设置垂直向上、向下对齐的方式。
现在只能垂直居中，但在很多情况下，这样的样式并不好看，希望能提供向上、向下对齐的方式

### What does the proposed API look like?
vertical-align="top"
vertical-align="center"
vertical-align="bottom"

**Comment by yesmeck** [comment]
我们目前没有这样的设计，建议自己通过覆盖样式实现。

**Comment by mengxingshike2012** [comment]
是什么原因，现在还不支持吗
