### ISSUE TITLE
Inline DatePicker

### ISSUE THREAD

**Issue by RaedsLab** [ant-design/ant-design#10267]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to display an inline DatePicker for users to pick a date.

### What does the proposed API look like?
Just add "inline" attribute ?

**Comment by yesmeck** [comment]
How does it look like?

**Comment by RaedsLab** [comment]
@yesmeck exactly the same as the current one, just displayed inline without the user having to click it open (and its fixed to a div without a hover) but exactly the same as now.

**Comment by yesmeck** [comment]
I think [Calendar](https://ant.design/components/calendar/#components-calendar-demo-card) is what you are looking for.

**Comment by RaedsLab** [comment]
Thanks, exactly !
