### ISSUE TITLE
新版面包屑移除对react-route Link的依赖之后非hash场景如何解决？

### ISSUE THREAD

**Issue by TinyJiang** [ant-design/ant-design#1026]
https://github.com/ant-design/ant-design/blob/master/components/breadcrumb/index.jsx#L74

新版的面包屑移除了对Link的依赖，直接使用a标签加hash的形式，如何应对非hash的场景

如地址是ip:port/users/1
hash的方式只能生成ip:port/#/users/1

**Comment by luckydrq** [comment]
:+1:

**Comment by TinyJiang** [comment]
awesome!
