### ISSUE TITLE
在使用TreeSelect时，单击Tag的删除按钮时，不希望弹出Option.

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#10274]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
win10、Chrome

### Reproduction link
[https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable](https://ant.design/components/tree-select-cn/#components-tree-select-demo-checkable)

### Steps to reproduce
当`TreeSelect`组件设置`treeCheckable=true`时。
选择多个`option`，然后单击`tag`上的`x`删除选择内容。

### What is expected?
不要弹出下拉框。

### What is actually happening?
弹出option的下拉框。

**Comment by zombieJ** [comment]
Thanks for feedback.

`TreeSelect` follow the behavior of `Select`.
It may adjust the logic both of them.

**Comment by zombieJ** [comment]
Fix `rc-tree-select` on `1.12.12`
