### ISSUE TITLE
When i use the nested table and use scorll attribute in nested table, table show error!

### ISSUE THREAD

**Issue by mintsweet** [ant-design/ant-design#10276]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
win10, chrome65

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wn0o6rl7y5)

### Steps to reproduce
 - create table
 - create nested table
 - setting nested table scroll attr

### What is expected?
nested table has scroll not external table.

### What is actually happening?
external table will be opened by nested table.

---
I want remove nested table's first td, but when i set the first td none, other td can't full up the current tr.

**Comment by yesmeck** [comment]
https://codesandbox.io/s/434v7pjkj4

**Comment by yesmeck** [comment]
> I want remove nested table's first td

You can not do that.

**Comment by mintsweet** [comment]
ok，thanks
