### ISSUE TITLE
setFieldsValue can't set upload fileList

### ISSUE THREAD

**Issue by EGBAR** [ant-design/ant-design#10277]
用Form 包装的 Upload：
                {getFieldDecorator('dragger', {
                //initialValue:this.state.fileList,
                valuePropName: 'fileList',
                getValueFromEvent: this.normFile,
                rules:[{required: true, message: '请选择文件！' }]
                })(
                <Upload.Dragger name="files"  action="/tmp" beforeUpload={this.handleBinaryUpload} disabled={this.state.current>1}>
                    <p className="ant-upload-drag-icon">
                    <Icon type="inbox" />
                    </p>
                </Upload.Dragger>
                )}

在 Upload 的 beforeupload 里面 form.setFieldsValue 可以set 其余的input 但是 fileList 不生效。

1 已经将 valuePropName 指向 'fileList',
2 initalValue 是可以正常设置。
3 beforeUpload 的返回值是false

**Comment by SilentFlute** [comment]
@EGBAR 你好， 我也遇到了需要form包裹upload的情形，也是验证有问题，请问你最后解决了这个问题了吗？

**Comment by SilentFlute** [comment]
后来找到了，在被getFieldDecorator HOC的那个上传组件中调props里的onChange事件，上传成功了调onChange(fileList[0].response)，将上传之后图片的url传出去，移除图片就调onChange('')

**Comment by afc163** [comment]
@SilentFlute `valuePropName: 'fileList'`
