### ISSUE TITLE
Website changelog is not updated

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#10273]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
firefox

### Reproduction link
[https://ant.design/changelog](https://ant.design/changelog)

### Steps to reproduce
Just open the website

### What is expected?
See new version 3.4.3

### What is actually happening?
The changelog displays 3.4.2 as the latest version

**Comment by afc163** [comment]
done
