### ISSUE TITLE
How does nprogress bar works in antd website

### ISSUE THREAD

**Issue by fameoflight** [ant-design/ant-design#10271]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am just trying to understand how does nprogress works in antd website I didn't see any method calling start

**Comment by dengfuping** [comment]
@fameoflight 
https://github.com/ant-design/ant-design/blob/d9053a252691c015941f009bf51896e236655f26/site/theme/static/template.html#L68-L70

https://github.com/ant-design/ant-design/blob/master/site/theme/static/nprogress.less

**Comment by fameoflight** [comment]
@dengfuping yes I see that but where does it call NProgress.start() ?
