### ISSUE TITLE
how to use this.props.form.setFieldsValue when fieldName is a Spliced string

### ISSUE THREAD

**Issue by sandm1227** [ant-design/ant-design#10278]
code： 
![default](https://user-images.githubusercontent.com/25194203/39347774-f3d56ac6-4a26-11e8-86db-c0ec3923087c.png)

**Comment by dengfuping** [comment]
@sandm1227 \`tableId${index}\`

**Comment by sandm1227** [comment]
![qq 20180427144153](https://user-images.githubusercontent.com/25194203/39348382-71f9aab4-4a29-11e8-8684-cf1d55712187.png)
