### ISSUE TITLE
antd合并表格 隔行变色问题

### ISSUE THREAD

**Issue by Nicolelll** [ant-design/ant-design#10285]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 需求：表格中内容太多 因此相同的内容就会合并成一条 
问题是：用户容易看串 因此我们想要隔一行换一种颜色

### What does the proposed API look like?
 rowClassName={
                    (record, index, indent) => {
                      if(record.children && index % 2 == 0){
                        return 'light'
                      } 
                    }
                  }

伪代码如上 但是这个问题就是只会限制indent ==0且是偶数行的列变色 并不会让indent == 1 的部分变色

问题如下图

![image](https://user-images.githubusercontent.com/29426229/39352155-7069d680-4a36-11e8-91b6-c3db768a3a35.png)

**Comment by Nicolelll** [comment]
模拟代码在这里 https://codepen.io/anon/pen/BxQzQm?editors=0111

**Comment by afc163** [comment]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/507615/39353491-7106f88a-4a3a-11e8-8e11-f6528f3184fb.png">

这种情况没有好的解决方案，最好避免对合并垂直单元格的表格使用隔行换色。
