### ISSUE TITLE
The upload image dont show

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#10287]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.0

### Environment
chrome 

### Reproduction link
[https://codepen.io/anon/pen/LmbZxG?editors=0010](https://codepen.io/anon/pen/LmbZxG?editors=0010)

### Steps to reproduce
。。。

### What is expected?
show upload image 

### What is actually happening?
dont show

**Comment by SynChron1zed** [comment]
![Uploading image.png…]()

**Comment by SynChron1zed** [comment]
![image](https://user-images.githubusercontent.com/18717051/39353936-b0c4f304-4a3b-11e8-8d8f-a8a0fca77364.png)

**Comment by SynChron1zed** [comment]
its default image

**Comment by afc163** [comment]
Try 3.4.3

**Comment by tizzyapunkt** [comment]
I had the same issue, an update to 3.5.1 fixed that for me!
