### ISSUE TITLE
antd-2.13.15 is not tagged and missing from npm

### ISSUE THREAD

**Issue by ojab** [ant-design/ant-design#10292]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.13

### Environment
linux

### Reproduction link
[https://www.npmjs.com/package/antd](https://www.npmjs.com/package/antd)

### Steps to reproduce
yarn install antd@2

### What is expected?
antd-2.13.15 is installed

### What is actually happening?
antd-2.13.13 is installed

**Comment by yesmeck** [comment]
Bump `2.13.15` is a mistake, I've released `2.13.14`, thanks for reporting.
