### ISSUE TITLE
希望dataSource能支持mobx类型的数据

### ISSUE THREAD

**Issue by yuminjustin** [ant-design/ant-design#10295]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
开发中用mobx替换redux，经过mobx监控后的数据不是原生的数据类型，现在必须使用toJS来转换，不知道转换之后的数据是不是失去了状态管理的特性。

### What does the proposed API look like?
例如Table控件中dataSource也能支持mobx的数据ObservableArray，目前只接受原生的array

**Comment by afc163** [comment]
antd is UI component which should'nt and won't nest any special data instructure.
