### ISSUE TITLE
能不能处理好版本兼容问题？？？

### ISSUE THREAD

**Issue by china-liji** [ant-design/ant-design#10293]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
antd 3.4.1 与 antd 3.4.3

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
Upload 的 onChange 事件！！！
本来 3.4.1 之前返回的是 { file, fileList }，其中 file 是 window.File 实例，可用于  file instanceOf File，
3.4.1 居然 file 改成了 object， 还给一个 originFileObj ？？？
这样算了，我改了一次兼容问题
结果 3.4.3 fileList 里面的也改成了 object ， 但 3.4.1 却没有一起改！！！
有问题能统一处理吗？？ 只改一部分？分2个版本？？？

### What is expected?
看我描述

### What is actually happening?
看我描述

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/10059

这里搞错了，我改一下。

**Comment by afc163** [comment]
@china-liji 你使用了 beforeUpload 并 return 了 false 是么？

**Comment by afc163** [comment]
我今天会发个 patch

**Comment by china-liji** [comment]
是，使用了  beforeUpload 并 return 了 false

**Comment by superlbr** [comment]
文档没更新？file的name位置变了
before:

```
{
  file: { name: 'xxx'},
  fileList: [ /* ... */ ],
  event: { /* ... */ },
}
```
now:

```
{
  file: { originFileObj: {name: 'xxx'}},
  ....
}
```

**Comment by superlbr** [comment]
果然妹子头像好使。。。https://github.com/ant-design/ant-design/issues/10319
