### ISSUE TITLE
TreeNode does not allow style prop to be passed

### ISSUE THREAD

**Issue by itsdeezy** [ant-design/ant-design#10291]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
mac sierra 10.13.3 // Chrome 66 // react 16.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lxzm282j49)

### Steps to reproduce
Add a style object to TreeNode ie.
```
<TreeNode style={{ color: "red" }} value={1} title="One" />
```

### What is expected?
Expect style to be passed through

### What is actually happening?
No style

---
I brought this up as a bug as Select options passes the style object nicely. This could be a feature request for `rc-tree-select`. It would be nice to style both components in a consistent way, right now I'm injecting styles with a theme provider, and have to resort to using direct css injection to the tree node class (which is bad).

**Comment by wjkang** [comment]
use className

**Comment by zombieJ** [comment]
This will be support in `3.7.0`.
But set style prop will append the style to the `<li>` element which may not what you want, I think you'd better use `className` or just set title prop as:
```jsx
title={<span style={{...}}>I'm the title</span>}
```
