### ISSUE TITLE
 无法与 reactcss 结合起来

### ISSUE THREAD

**Issue by yozman** [ant-design/ant-design#103]
想接合 [reactcss](http://reactcss.com/) 来使用，
但是 `antd server` 之后，
访问 `http://localhost:8000/` 样式不生效

```javascript
import ReactCSS from 'reactcss';

class Button extends ReactCSS.Component {
	classes() {
		return {
			'default': {
				btn: {
					color: 'red'
				}
			}
		}
	}
	render() {
		return <div is="btn">hello world</div>;
	}
}

React.render(<Button />, document.body);
```

**Comment by afc163** [comment]
应该是需要 react-map-styles 这个 loader 。@sorrycc

**Comment by yozman** [comment]
@afc163 怎么弄？

**Comment by sorrycc** [comment]
- @afc163 react-map-styles 要不要内置? 
- @yozman 在项目目录下写一个 webpack.config.js，把 react-map-styles 加上，antd 命令会先读这个的

**Comment by afc163** [comment]
这些 loader 内置不完的，能用 config 自定义就好。

**Comment by sorrycc** [comment]
https://github.com/ant-design/antd-bin/tree/master/examples/customize-with-reactcss
参考这个例子，用 antd-bin@0.2

**Comment by yozman** [comment]
@sorrycc 赞
