### ISSUE TITLE
In this condition, the validateFields function will ignore the InputNumber's value which was entered by clicking its up and down button

### ISSUE THREAD

**Issue by meiyouqing** [ant-design/ant-design#10303]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
macOs10.13.4, chrome65.0.3325.181（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y0rmm39l81)

### Steps to reproduce
The validateFields function will ignore the InputNumber's value which was entered by clicking its up and down button, when InputNumber as a parameter of getFieldDecorator()() is not a single node but a nested one

### What is expected?
the value entered by clicking will be validated correctly

### What is actually happening?
the value entered by clicking has been ignored

**Comment by meiyouqing** [comment]
any body help?

**Comment by afc163** [comment]
It is hard to find a perfect solution now, see https://github.com/ant-design/ant-design/issues/10417
