### ISSUE TITLE
Router issue

### ISSUE THREAD

**Issue by jamalabo1** [ant-design/ant-design#10304]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
ReactJS, Google Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qvw1pnm4xq)

### What is expected?
Page To load.

### What is actually happening?
if i click on the link on browser page load successfully but if i reload the page it returns "Not Found", 

---
its maybe server error (dora), i searched on web but there is not results. it worked on codesandbox.io but not working on my browser.

**Comment by afc163** [comment]
It is not relevant to antd.
