### ISSUE TITLE
tree组件能自动设置选中状态，清除选中状态

### ISSUE THREAD

**Issue by QCCS** [ant-design/ant-design#10300]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
Node8.0.0，Chrome浏览器版本 66.0.3359.139

### Reproduction link
[https://github.com/QCCS/antd-tree](https://github.com/QCCS/antd-tree)

### Steps to reproduce
克隆仓库-->安装依赖-->npm start-->得到结果

### What is expected?
1.当js设置树节点被选中时，树节点就为选中状态；
2.当js设置树节点不被选中时，树节点就为不选中状态；

### What is actually happening?
当js设置树节点选中与不选中，树节点没有响应；

---
我这边有一个页面，左边是树形部门树 普通部门列表(不是树形)，右边是节点被选择的列表；
我点击左边部门树节点，或者普通部门列表中的部门，需要在右边展示已经选择的部门；
当我点击右边已经选择的部门的删除按钮，右边的部门树被选中的节点也需要清除选中状态；

**Comment by afc163** [comment]
```diff
const { selectedKeys } = this.state;
selectedKeys.push('xxxx');
this.setState({
-  selectedKeys,
+  selectedKeys: [...selectedKeys],
});
```
