### ISSUE TITLE
在Form表单用FormItem的onChange方法调用form.getFieldsValue()，或取的值是上次选择的值

### ISSUE THREAD

**Issue by nilmeme** [ant-design/ant-design#10307]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
macos10.13.4,chrom65.0.3325.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l40vz4xnj7)

### Steps to reproduce
在重现链接中已经详细说明重现过程

### What is expected?
本次Select选择的结果

### What is actually happening?
上次次Select选择的结果

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6277

对 Form 的理解应该有误，一般来说你不应该用到 onChange。
