### ISSUE TITLE
New Component Skeleton

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#10308]
- https://github.com/buildo/react-placeholder
- https://github.com/danilowoz/react-content-loader
- https://github.com/trainline/react-skeletor
- https://ant.design/components/card/#components-card-demo-loading
- https://github.com/dvtng/react-loading-skeleton

**Comment by Rohanhacker** [comment]
@afc163 can I work on this ??

**Comment by afc163** [comment]
Sure you can, thx for help! @Rohanhacker

**Comment by zombieJ** [comment]
Since `3.7` has too many changes, let's put in `3.8.0`.

**Comment by zombieJ** [comment]
API design: Let's consider more use case on the fly. Pls feel free to leave comments.

# Sample on Avatar (pick one of them)
1. By `type` prop.
```jsx
<Skeleton type="avatar" size="small" loading>
  <Avatar size="small" src={...} />
</Skeleton>
```

2. By sub component:
```jsx
<Skeleton.Avatar size="small" loading>
  <Avatar size="small" src={...} />
</Skeleton.Avatar>
```

3. By sub component auto detect:
```jsx
<Skeleton loading>
  <Avatar size="small" src={...} />
</Skeleton>
```

# Default Type
basic:
* avatar - size
* title
* paragraph - rows

combination:
* img - width, height
* article(title + paragraph) - rows

# Combination (Maybe useless)
`placeholder` prop. (Maybe use other words):
```jsx
const placeholder = (
  <div style={{ display: 'flex', ... }}>
    <Skeleton.Avatar size="large" />
    <Skeleton.Paragraph rows={3} />
  </div>
);
<Skeleton placeholder={placeholder}>
  {/* Children Content */}
</Skeleton>
```

**Comment by zombieJ** [comment]
Too complex for user, need simplify this.

**Comment by zombieJ** [comment]
![1530873315778-e131012c-59c1-40db-b8d3-54d4414d5047](https://user-images.githubusercontent.com/5378891/42444156-f50bd970-83a1-11e8-8cbb-fc215ca3bb71.jpeg)

Maybe we can simplify like this:
```jsx
// Provide title + paragraph
<Skeleton loading>
  {/* children content */}
</Skeleton>
```

```jsx
// Provide avatar + title
<Skeleton loading avatar paragraph={false}>
  {/* children content */}
</Skeleton>
```

```jsx
// Provide avatar (config) + paragraph(config)
<Skeleton loading avatar={{ shape: 'square' }} title={false} paragraph={{ rows: 2 }}>
  {/* children content */}
</Skeleton>
```

The structure is fixed. User can only config part of them

**Comment by zombieJ** [comment]
Skeleton should support inline style. This can help if style file is loaded async. (But if other component like menu is in the UI, maybe not help on this)
