### ISSUE TITLE
Rely less on function calls to render components

### ISSUE THREAD

**Issue by georgiosd** [ant-design/ant-design#10318]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
More readable code, more familiar/similar to standard React APIs

### What does the proposed API look like?
Hey guys,

First of all fantastic work in Ant Design!

I wanted to ask whether you have any plans to convert dependencies on function calls to render components to more react-style components.

e.g.
```
<Form.Item label="Name">
            {getFieldDecorator('name', {
                rules: [ { required: true } ]
            })(<Input/>)}
        </Form.Item>
```
to:
```
<Form.Item label="Name" name="name" rules={rules} component={Input} />
```

**Comment by yuriloliveira** [comment]
Hi guys, well done with antdesign. I've been using it for a month, and I am really liking it so far.

But, I have to say that getFieldDecorator could, indeed, be more react-like, as Georgio pointed out.

Any thoughts regarding this matter.

**Comment by zombieJ** [comment]
`FormItem` is a simple wrapper to wrap children with [some style](https://github.com/ant-design/ant-design/blob/master/components/form/FormItem.tsx#L329). User can use field without this wrapper. So the `getFieldDecorator` should keep. But I agree to make the `getFieldDecorator` prop supported in `FormItem` to make user less coding.

**Comment by afc163** [comment]
https://github.com/nanxiaobei/ant-plus

**Comment by afc163** [comment]
```jsx
<Form.Item label="Name" name="name" rules={rules} />
  <Input />
<Form.Item>
```

**Comment by afc163** [comment]
Check out antd v4 new Form component: https://github.com/ant-design/ant-design/issues/21656
