### ISSUE TITLE
table的scroll.x是否可以通过scrollLeft进行控制？

### ISSUE THREAD

**Issue by linlinNB** [ant-design/ant-design#10310]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需要通过其他组件通知滑动滚动条显示不同的位置，比如document.ElementByClassName().scrollLeft = .....这种控制方式

### What does the proposed API look like?
，比如document.ElementByClassName().scrollLeft = .....这种控制方式

**Comment by afc163** [comment]
目前没办法，建议直接使用 dom 操作。
