### ISSUE TITLE
上传文件组件无法显示文件名 // Upload Component couldn't display file name

### ISSUE THREAD

**Issue by JixunMoe** [ant-design/ant-design#10319]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
Chrome 66.0.3359.117 (Fedora x64), Firefox 59.0.2 (Fedora x64), Chrome 66.0.3359.139 (Win 10 x64)

### Reproduction link
[http://ant.design/components/upload](http://ant.design/components/upload)

### Steps to reproduce
1. 左侧，第二个例子。
2. 选择一个文件上传。

.

1. Left section, second example from top.
2. Select any file.

### What is expected?
能显示文件名。

File name shown as expected.

### What is actually happening?
无法显示文件名（文件属性未能正确拷贝，在 `/antd/es/upload/utils` 的 `fileToObject` 函数）。

Blank file name (file properties was not copied in `/antd/es/upload/utils`, method `fileToObject`).

---
在 `onChange` 回调设定断点进行调试，可以发现以下特性：

```
const { file } = info;

> JSON.stringify(file)
< "{"uid":"rc-upload-1525188854561-2","percent":0,"originFileObj":{"uid":"rc-upload-1525188854561-2"},"status":"uploading"}"

> Object.keys(file.originFileObj)
< ["uid"]

> Object.keys(file.originFileObj.__proto__)
< (4) ["name", "lastModified", "lastModifiedDate", "webkitRelativePath"]
```

### 临时解决方案（Monkey-patch workaround）

在引导文件加入或引用下述代码 // Add or reference the following code in app entry：

```js
const uploadUtils = require('antd/es/upload/utils');
uploadUtils.fileToObject = function (file) {
  const fileDuplicated = {};
  if (file && file.__proto__) {
    Object.keys(file.__proto__).forEach(key => {
      fileDuplicated[key] = file[key];
    });
  }
  return {
    // file: uid
    ...file,
    // fileDuplicated: other `File` props.
    ...fileDuplicated,

    percent: 0,
    originFileObj: file,
  };
};
```

---

题外话：前两天还是正常的，今天突然显示不了了，应该是浏览器更新了。

**Comment by JixunMoe** [comment]
感觉把 issue 连接到 react-component/upload 会比较好一些…

**Comment by yociduo** [comment]
![image](https://user-images.githubusercontent.com/8317101/39504174-61de969a-4dfc-11e8-9fc1-3154459d1390.png)
应该是这个change引起的，可不可以回退回去？
