### ISSUE TITLE
Message instance update

### ISSUE THREAD

**Issue by ShiiRochi** [ant-design/ant-design#10320]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When making async calls we may want to show to the user using message.loading that there is a loading proccess and after async call is completed be able to update it to successful state, however at this time we need to close one and make another call message.success('message');

### What does the proposed API look like?
let loadingMessage = message.loading('content', 0);
loadingMessage.update({
    type:'success',
    content:'TEXT',
});
// OR
loadingMessage.success('Content');

**Comment by jzhangs** [comment]
I believe we can resolve this issue using solution to https://github.com/ant-design/ant-design/issues/9198 , by set `maxCount` to 1 and `duration` to 0.

Not merged to master yet, but @ShiiRochi you may try `feature-3.5` branch.

**Comment by ShiiRochi** [comment]
maxCount only limits number of shown messages simultaneously and duration to 0 stops them from being closed automatically, however...I think, that even with'em users will see two boxes replacing each other, the main idea of my issue on the other side is to make all transitions inside current message box.
Let's take code from the first post.
`loadingMessage.success('Your post has been created!', 1.5);`
From my point of view, this code could mean that current message box should be transformed to success state and since the moment when colors and new styles took place it should be visible only 1.5 seconds.

**Comment by afc163** [comment]
The return value of `message.xxx` is hide function now. So if we want to keep the compatibility, maybe we can implement this way:

```js
const loadingMessage = message.loading('content', 0); // 

loadingMessage(); // still hide it, for compatibility
loadingMessage.hide(); // new hide way
loadingMessage.update('new content'); // new hide way
```

**Comment by yesmeck** [comment]
Related https://github.com/ant-design/ant-design/issues/8021

**Comment by ShiiRochi** [comment]
Everything is OK. In update method (where 'new content' is placed), from my point of view, object with properties should be passed, because it's not very clear to what state loadingMessage will be updated. For example:
`
const updateObject = {
    type:'success' // any of ['success', 'error', etc.],
    duration: 2
};
loadingMessage.update(updateObject); // changes message to success state and makes it to be visible for two seconds
`

**Comment by ZhijianZhang** [comment]
目前3.5.3 设置 maxCount = 3，duration = 0 还是不能限制 message 的个数

**Comment by afc163** [comment]
I need this feature too personally.

**Comment by sirrodgepodge** [comment]
thoughts on using an API that matches the `notification` component for consistency?

https://github.com/ant-design/ant-design/blob/master/components/notification/index.en-US.md

see `open` here, 
if there is not a notification open with the provided `key` it opens a new notification,
if there is a notification open with the provided `key` it updates said notification. 
```js
notification.open({
  key: 'thingThisIsTrackedWith',
  ....
})
```

**Comment by JHanLu** [comment]
Was this issue resolved?
