### ISSUE TITLE
问一下list一行显示五列有办法处理吗，现在只能设置为24整除的数字。

### ISSUE THREAD

**Issue by chendonghai1982** [ant-design/ant-design#10322]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为我要设置各个设备的屏幕大小，通过动态来计算一行显示多少列。我每一个item宽度是固定大小的。

### What does the proposed API look like?
希望有一个这样的参数来设置

**Comment by afc163** [comment]
暂时不行，建议自行实现。

**Comment by chendonghai1982** [comment]
还有其他控件可以代替吗

**Comment by afc163** [comment]
https://ant.design/docs/react/recommendation-cn

**Comment by chendonghai1982** [comment]
谢谢
