### ISSUE TITLE
Square radio  box

### ISSUE THREAD

**Issue by rockwong** [ant-design/ant-design#10327]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
mac chrome

### Reproduction link
[https://ant.design/components/radio/](https://ant.design/components/radio/)

### Steps to reproduce
If set less variable "@border-radius-base" to 0 ,

### What is expected?
Radio checked box keep round 

### What is actually happening?
Radio checked is Square

---
Maybe `ant-radio-inner:after  border-radius`  should use 50%?

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/commit/52c8f34a734356f6e3076df87c2cf48fde20d25e
