### ISSUE TITLE
Uploaded the CSV and Excel file which is changed from txt file  in win7, the files'type is not identified on method 'onChange'.

### ISSUE THREAD

**Issue by Alice2222** [ant-design/ant-design#10323]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
win7/chrome/react 15.6.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1z3n16406l)

### Steps to reproduce
all the steps should happen in win7 : created a new txt file -> changed file extension to 'csv' or 'xls' or 'xlsx' ->   uploaded the file 

### What is expected?
we can see the file type which is same as the result in mac on method 'onChange' in info.file.type .

### What is actually happening?
''

**Comment by yociduo** [comment]
It seems the same issue of #10319

**Comment by afc163** [comment]
fixed in #10319

**Comment by Alice2222** [comment]
不是文件名，是文件类型是空的

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1718
