### ISSUE TITLE
The arg type of onChange in Upload Component

### ISSUE THREAD

**Issue by Mr-Yy** [ant-design/ant-design#10328]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zqp9zj43op)

### Steps to reproduce
- Click upload and select a file
- See log

### What is expected?
file: { name: 'xxx' }

### What is actually happening?
file: { originFileObj: { name: 'xxx' } }

---
I see this issue is create with [#10059](https://github.com/ant-design/ant-design/pull/10059), and seem to solved with [#10296](https://github.com/ant-design/ant-design/pull/10296)  
But when i use the version of 3.4.4, the name of file still in originFileObj not in file. It makes break change for my code, so what type and keys of file will be?  
I hope to have a definite result, and i will change for it. Thanks.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/10319
