### ISSUE TITLE
Dropdown component ignore its className prop

### ISSUE THREAD

**Issue by yenshih** [ant-design/ant-design#10325]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
macOS Sierra 10.12.6, Chrome 65

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1vwrvjvmpj)

### Steps to reproduce
Open your console and find that trigger container with `ant-dropdown-trigger` class. It may have another class `my-custom-dropdown`.

### What is expected?
`className` `my-custom-dropdown` should pass into trigger container `span` as a prop, intuitively.

### What is actually happening?
`className` lost in trigger container somehow.

---
### Related Code

`className` passed through [Dropdown](https://github.com/ant-design/ant-design/blob/master/components/dropdown/dropdown.tsx#L71), [RcDropdown](https://github.com/react-component/dropdown/blob/master/src/Dropdown.jsx#L139) and finally lost in [RcTrigger](https://github.com/react-component/trigger/blob/master/src/index.js#L555).

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/72ormv6l76

**Comment by yenshih** [comment]
@afc163 Indeed, we have a component `Groups`. It works like:
```jsx
<Groups className="container" childClassName="item">
    <Link>item1</Link>
    <Button>item2</Button>
    <Dropdown>{item3}</Dropdown>
</Groups>
```
The `Groups` will pass `item` as `className` for each child.
I just wanna to pass `className` into the container of `Dropdown`, rather than the trigger element.
However, `Dropdown` ignore `className`.
IMO, this is not an intuitive behavior. It will confuse developers.
Shall we fix this problem?

**Comment by afc163** [comment]
You can create a PR to rc-trigger for this.

**Comment by yenshih** [comment]
@afc163 Sure, I'd be grad to do so. Thanks for your patient.
