### ISSUE TITLE
Popover / Popconfirm placement 应该支持 "auto"

### ISSUE THREAD

**Issue by debbbbie** [ant-design/ant-design#10338]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如图，当 trigger 在浏览器上端时，Popconfirm 会出现看不见的情况，placement 应该自动显示到 bottom

我在公司项目中已经实现 "auto"， 建议 ant-design 默认支持这个 feature ，我提交 commit吧？ ~~ @afc163 

![image](https://user-images.githubusercontent.com/233115/39558108-a69a43b6-4ebe-11e8-9d31-8681b9471113.png)

### What does the proposed API look like?
`popover/popconfirm`  attribute `placement` should support `auto`

**Comment by yesmeck** [comment]
antd 里所有弹出框的逻辑是只有在页面在弹出方向上无法滚动时才会往另外一个方向弹出，目的是为了避免 #5130 的情况。

**Comment by bianlizuozishu** [comment]
@yesmeck 能不能加个属性来控制这个问题,我们有需求就是如果滚动条挡住也要换方向,考虑一下?

**Comment by whusnoopy** [comment]
@yesmeck 同意楼上 @bianlizuozishu 的意见

按 antd 的设计逻辑，只在页面无法滚动时才换方向，这个没问题。但是是否也可以给业务一个选择，到底是页面无法滚动时才换方向，或是超出视口就换方向，或是强行永远不换方向

对于 #5130 的情况，可以通过设定换方向的时机选项来避免的

**Comment by AdonLee** [comment]
> antd 里所有弹出框的逻辑是只有在页面在弹出方向上无法滚动时才会往另外一个方向弹出，目的是为了避免 #5130 的情况。

#5150 问题是动态内容造成，如果内容是静态的， 并不会出现这个问题。因为一个特殊case，干掉一项功能，这不科学。

**Comment by frei-x** [comment]
提议重开这个问题
