### ISSUE TITLE
Expecting an anchor-style icon button without border and background

### ISSUE THREAD

**Issue by enzeberg** [ant-design/ant-design#10334]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I always use `<a><Icon type="plus" /></a>` to get the icon button I want. But today my ESLint told me that the button element instead of anchor element should be used. So I had to change that code into `<Button icon="plus" style={{ border: 'none', backgroundColor: 'rgba(0, 0, 0, 0)', }} />`. However, I find it inconvenient because I need many icon buttons like this, and the `<i>` that represents the icon is not vertically centered in the `<button>`. So the effect of `<a><Icon type="plus" /></a>` is better.

### What does the proposed API look like?
`<Button icon="plus" anchorStyle />`

**Comment by afc163** [comment]
No plan cause our design guideline don't support it.
