### ISSUE TITLE
rangepicker 的mode为year时，选中年份，面板没有高亮选中

### ISSUE THREAD

**Issue by havywu** [ant-design/ant-design#10330]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
win7 、 Chrome 版本 63.0.3239.108（正式版本） （32 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oj2zqrl70q)

### Steps to reproduce
点击右下角的年按钮，选择某个年份

### What is expected?
选择某个年份的时候，选中的年份高亮，如选择月份面板交互

### What is actually happening?
选择某个年份的时候，选中的年份不高亮

---
单独选择年份的时候，结束年份可以大于开始年份

**Comment by mianhuaqishi** [comment]
楼主，这个问题解决没有？

**Comment by aforme** [comment]
v3.9.2仍然有问题，mode="year"  弹出面板选择年后没有高亮 并且在onPanelChange事件里面不知道选择的哪一个时间，values[0]的值一直是左边面板，values[1]是右边面板，不能实现选择两个左边面板的时间

**Comment by afc163** [comment]
Duplicate of #15659
