### ISSUE TITLE
Form: Validation Rules of type regexp do not work (TypeScript)

### ISSUE THREAD

**Issue by k3flo** [ant-design/ant-design#10335]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
react 16.2.0, antd 3.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oj9kkzv196)

### Steps to reproduce
Type any character in the input box

### What is expected?
The validation should fail, because the regex only allows numbers

### What is actually happening?
The validation succeeeds although the regex should fail

**Comment by afc163** [comment]
```diff
          {getFieldDecorator("testNumber", {
            rules: [
              {
                required: true,
-               type: "regexp",
                pattern: new RegExp("^[0-9]*$"),
                message: "Wrong format!"
              }
            ]
          })(<Input />)}
```

https://codesandbox.io/s/w09xl68pnw
