### ISSUE TITLE
Add ability to styling mention items in <Mention />

### ISSUE THREAD

**Issue by m1n0s** [ant-design/ant-design#10348]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi!
We are implementing functionality with mentions in multiline mode. 
Ours end user problems is that from big piece of text it's hard to see where mentions were used.

It would be great to be able wrap mention items into some React.Element. If it's hard to do - at least would be good to have ability pass some custom className to `span`s with mention items. Currently it's impossible to write such CSS selector because simple text and mention items has totally same markup.

Thank you for responses.

### What does the proposed API look like?
`<Mention renderItem={item => <div>{item}</div>} />`

or

`<Mention itemClassName="mention-item" />`

Tiny inline styling example via Chrome DevTools
![image](https://user-images.githubusercontent.com/12004923/39583899-d144083c-4ef9-11e8-9d19-010ae8a24834.png)

If it's a valuable feature and you agree about it need to be implemented - I can try it by myself.

**Comment by marinona** [comment]
Styling mentions would be a great improvement!

**Comment by Kvintus** [comment]
One way to achieve this:

```tsx
export interface TextContainingMentionsRendererProps {
  className?: string;
  content: string;
}

export const TextContainingMentionsRenderer = (
  props: TextContainingMentionsRendererProps
) => {
  const { className = "", content = "" } = props;
  return (
    <>
      {content.split(" ").map((part, index) => {
        if (part[0] === "@" || part[0] === "#") {
          return (
            <Link href="/">
              <a>{part} </a>
            </Link>
          );
        }
        return part + " ";
      })}
    </>
  );
};
```

This is useful not only for styling but if you need to actually reference something and navigate user to that specific thing referenced.

**Comment by halotest** [comment]
This needs to be reopened. Mentions is a handy feature but without custom rendered function it's barely useful, please give us an option to provide custom renderer either for selected value or for entire text via "value" so we can split strings like in the above example by @Kvintus

**Comment by FrenchMajesty** [comment]
Commenting here to add support to the issue.

**Comment by bruno-teruel** [comment]
I also think this feature would be greatly useful.

**Comment by iashris** [comment]
Kindly consider prioritising this!
