### ISSUE TITLE
Upload component file list does not show file name

### ISSUE THREAD

**Issue by duan602728596** [ant-design/ant-design#10341]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
antd:3.4.4

### Reproduction link
[https://github.com/duan602728596/webpackconfig/tree/bug](https://github.com/duan602728596/webpackconfig/tree/bug)

### Steps to reproduce
Upload does not show file name after file upload.

![https://raw.githubusercontent.com/duan602728596/webpackconfig/bug/bug.jpg](https://raw.githubusercontent.com/duan602728596/webpackconfig/bug/bug.jpg)

File list after successful upload of new version:
```json
[{
	"uid": "rc-upload-1525307921745-2",
	"response": {},
	"percent": 100,
	"originFileObj": {
		"uid": "rc-upload-1525307921745-2"
	},
	"status": "done"
}]
```

File list after successful upload of old version:
```json
[{
	"uid": "rc-upload-1524711272158-4",
	"size": 380870,
	"lastModifiedDate": "2018-01-30T09:26:48.254Z",
	"response": {},
	"name": "file.docx",
	"lastModified": 1517304408254,
	"type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	"percent": 100,
	"originFileObj": {
		"uid": "rc-upload-1524711272158-4"
	},
	"status": "done"
}]
```

### What is expected?
File list shows file name.

### What is actually happening?
File list does not show file name.

**Comment by afc163** [comment]
Fixed in #10319, 3.4.5
