### ISSUE TITLE
menu嵌套超过两层时选中最里层的item后对应最外层的title没亮起

### ISSUE THREAD

**Issue by suiyi8760** [ant-design/ant-design#10345]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.5

### Environment
macOS10.13.4,chrome66,react@16.3.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6l75v4x03)

### Steps to reproduce
无

### What is expected?
比如选中提供的demo中的option5或option6后，navigation three应该也高亮

### What is actually happening?
只有navigation three中的submenu高亮了

---
需求需要，可以方便菜单关上后用户也可以找到当前选中的菜单项

**Comment by suiyi8760** [comment]
不好意思，issue类型忘了选择为功能需求

**Comment by chinajuanbob** [comment]
+1

**Comment by zachguo** [comment]
duplicate of #8666

**Comment by afc163** [comment]
Duplicate of #8666
