### ISSUE TITLE
Upload组件上传问题

### ISSUE THREAD

**Issue by Yuliang-Lee** [ant-design/ant-design#1035]
Upload组件的action属性文档上写的是必填，选择完文件自动就把文件上传到服务器。
现在我的需求是要选择完文件，最后和其他表单项组成FormData后通过ajax发送到服务端，能做到吗？

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/830

建议阅读 [CONTRIBUTING.md](https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md#3-read-the-faq-and-search-the-issues-list-of-ant-design)
