### ISSUE TITLE
CheckboxGroup: style属性无效

### ISSUE THREAD

**Issue by jdz321** [ant-design/ant-design#10358]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.14

### Environment
chrome macos

### Reproduction link
[https://codepen.io/jdz321/pen/gzxLRv](https://codepen.io/jdz321/pen/gzxLRv)

### Steps to reproduce
用style属性给CheckboxGroup设置样式

### What is expected?
style属性指定的样式生效

### What is actually happening?
style属性指定的样式未生效

---
2.x版本的问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/52414976424e739a6a526920c7c9d4bb90f0b2f9

2.x will not accept new features.
