### ISSUE TITLE
TreeSelect 使用 disableCheckbox 时，选择错误

### ISSUE THREAD

**Issue by sabakugaara** [ant-design/ant-design#10360]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.5

### Environment
mac chrome

### Reproduction link
[https://codepen.io/jsen/pen/erEgpd](https://codepen.io/jsen/pen/erEgpd)

### Steps to reproduce
1. 展开树列表

2. 选择 c-child2-1

3. 再通过点击 c-child2-1，移除该节点。此时 c-child1-1 会被自动选择

### What is expected?
c-child1-1 不会被自动选择

### What is actually happening?
c-child1-1 会被自动选择

**Comment by zombieJ** [comment]
Thanks for feedback. TreeSelect is in refectory, will fix this issue.

ref: https://github.com/zombieJ/tree-select/tree/refactor

**Comment by sabakugaara** [comment]
感谢，如果想本地先修复这个问题的话，有什么建议吗？

**Comment by zombieJ** [comment]
这是因为 TreeSelect 会 cache 状态，和旧版本的Tree联动更新有错误。如果很着急的话，需要自己用Tree包一个简单版的出来。

**Comment by sabakugaara** [comment]
Tree 组件可能也有这个问题（之前不是最新的版的 ant 上试过），不确定最新版是否有该问题。
请问 refactor 版本预计什么时候会发布啊？

**Comment by zombieJ** [comment]
`Tree` 已经修复了，`TreeSelect` 还没有更新依赖。最早在 `3.6` 可以重构好。

**Comment by zombieJ** [comment]
fixed in `3.7.0`
