### ISSUE TITLE
Request Tag API for Select Tag

### ISSUE THREAD

**Issue by arvinxx** [ant-design/ant-design#10364]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As image below 
![](http://ox55f9bg6.bkt.clouddn.com/2018-05-04-084441.jpg)
If user want to add , edit or delete tags, only select tags cann't meet this demand.
So I request Select tag should extend Tag's api.
Thanks a lot.

### What does the proposed API look like?
same with Tag component

**Comment by afc163** [comment]
Try https://pro.ant.design/components/TagSelect

**Comment by arvinxx** [comment]
TagSelect doesn't have delete UI like Normal Tags Component.
![default](https://user-images.githubusercontent.com/28616219/39632453-b79a3d22-4fe7-11e8-97be-2a91e0c1e2d4.png)
I request  closable 、 onClose and afterClose API  for SelectTag Component.

**Comment by afc163** [comment]
Is Selectable Tag should be closed?

**Comment by arvinxx** [comment]
Yes if user want to interact with Tags.
This is the eample.
![](http://ox55f9bg6.bkt.clouddn.com/2018-05-09-1.gif)
