### ISSUE TITLE
AutoComplete displays key instead optionLabelProp when value same as key

### ISSUE THREAD

**Issue by SG5** [ant-design/ant-design#10367]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
docker node:8.9-alpine

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7w2r393nmx)

### Steps to reproduce
Write '1' in autocomplete and select 'Number: 1'

### What is expected?
Autocomplete displays 'Number: 1'

### What is actually happening?
Autocomplete displays '1'

**Comment by wmzhong** [comment]
Just a confirm, is this issue accpted to fix?

**Comment by afc163** [comment]
Fixed in rc-select@8.8.3
