### ISSUE TITLE
打包速度太慢

### ISSUE THREAD

**Issue by readyou** [ant-design/ant-design#1036]
安装antd后发现lib目录中没有打包并压缩的文件xxx.min.js，无法做webpack配置的优化，webpack打包的时候特别慢。不知道能不能像react一样提供一个打包并压缩的文件呢？

**Comment by afc163** [comment]
Try https://github.com/ant-design/babel-plugin-antd

**Comment by jzlxiaohei** [comment]
即使使用了`babel-plugin-antd`，打包速度还是不令人满意。而且对于大部分后台，全部组件都直接引进一般没有什么问题。

我看到 执行`webpack.antd.config.js`是可以打包的，但是还是希望官方提供打包好的版本

**Comment by jzlxiaohei** [comment]
算是给大家多一种选择

**Comment by afc163** [comment]
可以自行打包，建一个 webpack 项目，只有一个文件，并打包构建输出。

```js
import antd from 'antd';
export default antd;
```

**Comment by kyo4311** [comment]
对于大部分后台，全部组件都直接引进一般没有什么问题！顶起，我也觉得是这样子的。

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/build-antd-standalone

**Comment by someok** [comment]
这个应该是各有所需吧，像我，还巴不得能提供个带源码的版本

偏右 <notifications@github.com>于2016年4月3日周日 16:15写道：

**Comment by afc163** [comment]
对，这是一种备选方案，因为有很多人提到这点。我们还是推荐直接 npm 。
