### ISSUE TITLE
<Mention /> trigger 'onChange' on form init

### ISSUE THREAD

**Issue by m1n0s** [ant-design/ant-design#10369]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
Windows 10, Chrome 66.0.3359.139

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n5x573987l)

### Steps to reproduce
1. Create form
2. Add Mention component to Form.Item
3. Add validation rules 
```
            {
                required: true,
                transform: Mention.toString,
                message: "required"
              }
```

### What is expected?
On form init onChange will not be triggered and field will not be considered as `touched`.

### What is actually happening?
onChange triggered and field became `touched: true` -> it triggers validation rules and it turns out that on page init - field became red from very beginning

**Comment by afc163** [comment]
Fixed in latest version now.
