### ISSUE TITLE
rc-select存在bug, Select组件有label属性时表现异常

### ISSUE THREAD

**Issue by astwyg** [ant-design/ant-design#1037]
当给Select组件传入label属性时, 会覆盖默认选项的文字显示, 不影响html以选择状态. 见下图:

![image](https://cloud.githubusercontent.com/assets/8462079/13168782/13086f96-d71b-11e5-9b4a-4f9519551ec3.png)

=======bug描述结束, 下面是讨论=========
这些rc-xxx好像是ES6或者7babel之后的ES5代码, 看起来很费劲, 不知道有没有源码能下载到?

另外, 关于为啥要给Select传入babel属性, 主要是因为重新封装Form组件, 某些场合下, 我希望把一些组件的children自动包装一层FormItem, 主要代码如下:
```jsx
		if(this.props.children.length){ 
			for(let child of this.props.children){
				let childElement = React.cloneElement(child,
					{onChange: this.setValue.bind(null, child.props["onChange"],
						child.props["name"]),
					label:undefined});  //注意! 这里的label将被渲染为defaultText
				formEntity.push(
					<FormItem
							key= {"dummy-"+ keycnt++}
			        label={child.props["label"]}
			        labelCol={{ span: 10 }}
			        wrapperCol={{ span: 14 }}>
			        {childElement}
			    </FormItem>
				);
			}
		}
```

React存在限制, 不能直接删除props, 基本clone一个元素, 也只能覆盖props而无法删除, 我用null, undefined覆盖了label, 都不好使.

衷心感谢对于此话题的任何建议.

**Comment by afc163** [comment]
Need Demo: http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by astwyg** [comment]
@afc163 
BUG demo here: http://codepen.io/anon/pen/gPJxKV?editors=1010

**Comment by afc163** [comment]
不要加 label 。Try：

```jsx
delete child.props.label;
let childElement = React.cloneElement(child, ... );
```

**Comment by astwyg** [comment]
Element的props delete 不了, React好像是把丫的set方法重写了. delete报错.
btw, 谁知道rc-XXXXX 那些项目的源码哪里能找到? 看转义后的ES5太痛苦

**Comment by afc163** [comment]
http://github.com/react-component/

**Comment by astwyg** [comment]
Great!  tyvm.

**Comment by afc163** [comment]
```jsx
let childProps = child.props;
delete childProps.label;
let childElement = React.createElement(child.type, childProps);
```

**Comment by astwyg** [comment]
Great! tyvm, again.
