### ISSUE TITLE
Table expanded row props

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#10379]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
more flexibility for expandable rows

### What does the proposed API look like?
table have expandedRowProps - Function(record, index):Object - where more features can be supported. Example use cases:
- Some rows are expandable and some are not,  `expandedRowProps(record).expandable  // false`
- Expanded row fetches record details on open, so closing and reopening triggers fetching the data,  `expandedRowProps(record).destroyOnClose // true` 
- Instead of passing multiple props for the expanded rows  to the table (expandedRowKeys, expandedRowRender, expandRowByClick) now the can be grouped in one function
```expandedRowProps: (record) => ({
  key: 1,
  expanded: true,
  expandByClick: false
})```

P.S. I love your work, and I rely on it heavily on all my project. I do realize how much effort you did put, and still are putting into it. Thank you very much for  this magnificent framework


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by AhmedSayed77** [comment]
More control over the expand behaviour, that can be record dependant. Every row can have it's own unique behaviour

**Comment by yesmeck** [comment]
For `expandable` see https://github.com/ant-design/ant-design/issues/7817

For `destroyOnClose`, have you encountered some scenarios need to unmount expanded row?

**Comment by AhmedSayed77** [comment]
the row only displays the record's name, the expanded row fetch the rest of the record details from the server in the onMount hook. so when the user wants to unexpand the row and re-expands it to re-fetch the data. passing isOpen (or any boolean that indicates the state of the expanded row) to the expandedRowRender can also do the trick

**Comment by AhmedSayed77** [comment]
and thanks for the link, it solved my problem, although I suggest you consider my proposed api, as calling the getRenderProps on the table render will not cause any performance issues (as it doesn't render anything) and call the render function returned from it when the user clicks the expand button

**Comment by yesmeck** [comment]
You can trigger remount by giving a random key to your expanded component:

```javascript
<Table expandedRowRender={() => <MyComponent key={Date.now()} />} />
```

**Comment by AhmedSayed77** [comment]
here's a reproduction
https://codesandbox.io/s/pk2njj996j
expanding any row will result in an infinite loop

**Comment by yesmeck** [comment]
@AhmedSayed77 I've realized that's not a good idea, I'll add `expanded` as the fourth parameter to `expandRowRender`, so that you can: 

```javascript
<Table expandedRowRender={(record, index, indent, expaned) => expaned ? <MyComponent /> : null)} />
```

**Comment by AhmedSayed77** [comment]
Thank you very much

**Comment by alextaymx** [comment]
the individual record prop in ExpandedRowRender does not update when table data is changed?
