### ISSUE TITLE
Add ErrorBoundary Component

### ISSUE THREAD

**Issue by zhenghangjie** [ant-design/ant-design#10376]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
dispose component error base React 16 

### What does the proposed API look like?
<ErrorHandler>
    <MyComponent />
</ErrorHandler>
or
HOC

**Comment by zhenghangjie** [comment]
if it's useful , I can create PR to solve

**Comment by yesmeck** [comment]
https://github.com/bvaughn/react-error-boundary
