### ISSUE TITLE
建议 Input的value和Select的value表现一致

### ISSUE THREAD

**Issue by LeuisKen** [ant-design/ant-design#1038]
Input的value在props写定则不可更改
Select的value在props写定也可以更改

在使用时该觉Input这种设定用起来很不舒服 希望能统一一下

或者希望官方能够给出这样设计的理由和使用场景

**Comment by afc163** [comment]
http://codepen.io/anon/pen/obRGJj?editors=001

Select 设置了 value 应该是不可修改的吧。

**Comment by benjycui** [comment]
都不看 FAQ 的么 

https://github.com/ant-design/ant-design/wiki/FAQ#i-set-the-value-of-inputselectetc-and-then-it-cannot-be-changed-by-users-operation

**Comment by LeuisKen** [comment]
我在用的时候遇到的问题defaultValue没办法解决 稍后我想办法还原在codepen上

**Comment by LeuisKen** [comment]
http://codepen.io/LeuisKen/pen/RrmxRe?editors=0010

发现在绑定了state的时候 其实value是可以输入的 因为之前问的时候知道了value会锁定就没考虑 结果表明两者的表现确实是一致的

不过还有一点小建议 哈哈 写在CodePen里面了 就是希望Input和Select的disabled样式能保持一致

**Comment by afc163** [comment]
你指的样式差异是哪方面不同？

**Comment by afc163** [comment]
感谢反馈，先关了。
