### ISSUE TITLE
When the width of the label is set, can the Delete Icon be aligned to the right?

### ISSUE THREAD

**Issue by Y-MY** [ant-design/ant-design#10387]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the user name is rendered, the length of the label is inconsistent. When the width of the label is set, the delete icon is not aligned to the right.

### What does the proposed API look like?
Deleting icons can be right-aligned

**Comment by afc163** [comment]
I can't understand what are u talking about, if you are reporting a bug, please use bug-report template in http://new-issue.ant.design/
