### ISSUE TITLE
Consider these performance optimization and component context pollution problems.

### ISSUE THREAD

**Issue by zheeeng** [ant-design/ant-design#10386]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In our code base, we are stilling using the obsolete PureRenderMixin and manually optimize the render performance by shallow compare nextProps, nextState in `shouldComponentUpdate` lifecycle. At present, the peer React dependency is 16.0.0 , I think **we can safely use  `React.PureComponet` to replace the old school optimization**.

There are some things to be noted, the `context` updating will be blocked by `PureComponent`. In AntD, there are some real use cases that coupled components share context, e.g. CheckboxGoup and Checkbox, List and ListItem, and others. I have to say that we overused and misused the unsafe old React context API in designing components.

Given that `context` brings effects to its all children, I suggest **1. collect related contexts into an unique context namespace**. 
According to the official document `https://reactjs.org/docs/legacy-context.html#updating-context`, updating context is also not recommended, I suggest **2.subscribe the context's changing in HOC**.

### Some Explains

Below is the illustration of suggestion 1:

In Sider.tsx, collects all sider contexts
```ts
  static childContextTypes = {
    siderCollapsed: PropTypes.bool,
    collapsedWidth: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
  };

  getChildContext() {i
    return {
      siderCollapsed: this.state.collapsed,
      collapsedWidth: this.props.collapsedWidth,
    };
  }
```

into a namespace `antSider`:
```ts
  static childContextTypes = {
    antSider: PropTypes. shape({
      siderCollapsed: PropTypes.bool,
      collapsedWidth: PropTypes.oneOfType([PropTypes.number, PropTypes.string]),
    }),
  };

  getChildContext() {
    return {
      antSider: {
        siderCollapsed: this.state.collapsed,
        collapsedWidth: this.props.collapsedWidth,
      },
    };
  }
```

Suggestion 2 stresses that we should never expect our component to be reactive to `context` mutations which the mutation propagation is easy to be cut off by performance optimizations. Dan Abramov gave us a good illustration: https://github.com/facebook/react/issues/2517#issue-48659373

I found that [mini-store](https://www.npmjs.com/package/mini-store) handles this problem in some way. It provides us the subscribing feature. But Its potential problem is injecting `store` prop into a component is easy to break the component's fractal character, it is pointed out in suggestion 1. For instance:
TableRow and Table, MenuItem and Menu, are both coupled by `<mini-store.Connect />`, if we compose them incorrectly may cause some unexpected issues, namely, Table inject a store data into context 'miniStore', its children MenuItem can access the Table's context by Connect HOC. And if there is some other custom Components receive context named 'miniStore', it also happens error.

Inspired by the new [React Context API](https://reactjs.org/docs/context.html#reactcreatecontext), we can revise the mini-store to solve the Dependency Injection Naming Conflict problem.

### What does the proposed API look like?
```js
import { createContext } from 'mini-store'

//  store name is optional, it uses unique store name by default 
const {  Provider: MenuProvider, Connect: MenuConnect } = createContext('antMenuStore')

// ...same with the old mini-store usage.
```
`Provider` declares a child context named 'antMenuStore' (not a generic name 'miniStore'), `Connect` injects a prop 'antMenuStore' into its wrapped component.

### Overall

1. Ant Design Component extends React.PureComponent.

2. Don't use context directly and collect related context into context namespace by revising mini-store to produce Provider and Connect pair

3. Replace the context use cases with the new `mini-store`.

### Q&A:

Q: **Why not use React.createContext directly**?

A: At present, the peer React dependency version is 16.0.0 , React.createContext is added in React 16.3.0.

Q: **Why not use react-call-return**?

A: it is unstable and unsafe, moreover it is an experimental package.

Q: **How about a backward compatibility of mini-store**?

A: The directly exported Provider and Connect keep unchanging, the new createContext introduce a pair of Provider and Connect HOCs.

**Comment by yesmeck** [comment]
We should migrate to  the new context API #9870
