### ISSUE TITLE
站点头部版本号的地方显示错位

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#10383]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
显示的问题

### What does the proposed API look like?
显示好看

![1](https://user-images.githubusercontent.com/18542211/39669242-c75b1416-5118-11e8-8bef-13af2bee4dc7.png)

**Comment by afc163** [comment]
broken by https://github.com/ant-design/ant-design/issues/10092
