### ISSUE TITLE
checkbox style: .ant-checkbox-input should not have a z-index

### ISSUE THREAD

**Issue by Nouzbe** [ant-design/ant-design#10385]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
Windows 10.0.16299, Chrome 66.0.3359.139, React 16.3.2

### Reproduction link
[http://jsfiddle.net/3cwzj0ea/144/](http://jsfiddle.net/3cwzj0ea/144/)

### Steps to reproduce
As shown in the jsfiddle, use `antd.Checkbox` and have a absolutely positioned div rendered on top of it

### What is expected?
The checkbox should not appear on top of the overlay.

### What is actually happening?
The checkbox does appear on top of the overlay.

---
This can easily be fixed on the project side, but it implies having z-index >= 2 on every overlay, which is dirty.

The problem is caused by [components/checkbox/style/mixin.less#L72](https://github.com/ant-design/ant-design/blob/master/components/checkbox/style/mixin.less#L72).

This issue might be related to [ant-design/issues/9840](https://github.com/ant-design/ant-design/issues/9840).

**Comment by afc163** [comment]
Turns out `z-index` in Checkbox is useful, removing it caused #10452 and #10480 so I just reverted the change.
