### ISSUE TITLE
Checkbox 设置checked属性有Warning

### ISSUE THREAD

**Issue by ZerdFei** [ant-design/ant-design#10394]
<Form>表单下Checkbox设置checked时，chrome控制台弹出警告：
Warning: Failed prop type: Invalid prop `checked` supplied to `Checkbox`.
不过可以正常使用，想请问下为什么会弹出这个警告却可以正常使用

**Comment by afc163** [comment]
目测已经修复了，如果还有问题请提供重现后我会 reopen。http://u.ant.design/codesandbox-repro
