### ISSUE TITLE
表格固定列显示不正常

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#10392]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
chrome 65

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rr2313p3wn)

### Steps to reproduce
- 打开上面的重现链接的预览页面 https://rr2313p3wn.codesandbox.io/
- 浏览器分辨率调整到`x`大于1600，**拖动**y滚动条到最下面
- 会看到表格下方固定列部分有遮挡和行错位

### What is expected?
表格固定列和下方表格行对齐

### What is actually happening?
表格固定列和下方表格行错位，有部分遮挡

**Comment by yunxifd** [comment]
@yesmeck 

![snipaste_2018-05-07_15-23-36](https://user-images.githubusercontent.com/29558970/39689939-ff18ba00-520a-11e8-86fc-555ab2bd65ff.png)

通过鼠标滚轮滚动的时候是正常的，通过拖动Y滚动条的时候就会出现上面情况

**Comment by yesmeck** [comment]
@Nokecy Could you take a look?

**Comment by Tuerping** [comment]
行错位是如何解决的？

**Comment by qingqinxl1** [comment]
I met this problem, too. After fixed some column, Row misplaced.

**Comment by yesmeck** [comment]
Try reinstall node_modules.

**Comment by 623059008** [comment]
Have you solved this problem?
rc-table: 6.7.0
But I still got this problem. 
When I render the table firstly, it has wrong row height. But change the page, it will be right.
I guess there are some problems in the orders of rendering the table.

**Comment by 623059008** [comment]
I think I got this problem because there are images in my table, and the row height can not be calculated correctly before fixed table rendering. So when I change page and go back, the height is right.
