### ISSUE TITLE
Pagination 分页 组件出现乱码

### ISSUE THREAD

**Issue by luqin** [ant-design/ant-design#104]
![image](https://cloud.githubusercontent.com/assets/2267688/9029582/a4d04ed0-39c8-11e5-9bad-b5174e4ed2c8.png)

**Comment by luqin** [comment]
官网的例子，http://ant.design/components/pagination/
环境：
* Chrome

**Comment by afc163** [comment]
操作系统是？

**Comment by luqin** [comment]
windows 7

**Comment by afc163** [comment]
windows7 下的 chrome 无法重现。楼主看看这个例子里也是乱码吗？http://jsfiddle.net/a0rvk6v2/

**Comment by luqin** [comment]
刚又看了下，竟然没问题。不知道什么情况。
