### ISSUE TITLE
select为多选时，支持选完一个自动折叠起来选项吗？

### ISSUE THREAD

**Issue by nai6514531** [ant-design/ant-design#10407]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
select为多选时，支持选完一个自动折叠起来选项吗？

### What does the proposed API look like?
可以有一个属性控制选项的自动折叠

**Comment by yesmeck** [comment]
收不起来是 bug，已修复，重新安装下  node_modules.

**Comment by nai6514531** [comment]
@yesmeck 我没有用受控的组件，需求是多选的时候像单选一样，一旦选完就自动收起来~

**Comment by yesmeck** [comment]
看错了，sorry。

**Comment by yesmeck** [comment]
嗯，有 `open` 属性，但不受控， 欢迎 PR。

**Comment by afc163** [comment]
trace #10482
