### ISSUE TITLE
Uncomfortable clicked style in Collapse component

### ISSUE THREAD

**Issue by xinkule** [ant-design/ant-design#10403]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
windows 10/ osx 11, chrome 66.0.3359.139

### Reproduction link
[https://ant.design/components/collapse-cn/](https://ant.design/components/collapse-cn/)

### Steps to reproduce
You can view your official website, and click one of the panel. 

### What is expected?
The panel doesn't have a highlighted style like an input focused event when I click it.

### What is actually happening?
The panel does have this focused effect when I click.

---
I don't know if it's a feature or a bug, because as I remembered, there used to not having this kind of ugly effect.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/5e99a939307324f1bb97ea11184d44fc91821d45
