### ISSUE TITLE
DatePicker need a default value for the panel.

### ISSUE THREAD

**Issue by rainke** [ant-design/ant-design#10402]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the panel open and datepicker has no value,  the panel's date is today default, but I need a special value;

### What does the proposed API look like?
a props such as defaultPanelValue to solve it;
<Datepicker defaultPanelValue={moment('1970-01-01')} />

**Comment by rainke** [comment]
I see a props defaultPickerValue in source code, but the docs doesn't refer to it;

**Comment by rainke** [comment]
我觉得应该更新下文档

**Comment by Joe312341** [comment]
Same, had to find this prop in the source code, it does not seem to be documented.
It was the only way for me the selected value (e.g. the Day) without setting the value.

**Comment by zombieJ** [comment]
@afc163 , is `defaultPickerValue` a stable prop? Or we could add in doc.

**Comment by afc163** [comment]
@zombieJ 👌
