### ISSUE TITLE
Input Addons within a Form are misaligned

### ISSUE THREAD

**Issue by wesokuhara** [ant-design/ant-design#10404]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
macOS Sierra 10.12.6, Chrome Version 66.0.3359.139 (Official Build) (64-bit), React 16.3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l9nn50nxxm)

### Steps to reproduce
Please visit the code at: https://codesandbox.io/s/l9nn50nxxm

Must create a Form component and then include an Input component with an addonBefore/addonAfter component.

### What is expected?
It is expected that the Input addons are aligned properly in the same row as the Input field and sized correctly.

### What is actually happening?
The Input addonBefore and addonAfter flow above and below the input field respectively.  They are also sized incorrectly and not coherent with the input element itself.

---
I believe this is an error caused by the recent fix to Input.Group in 3.5.0: https://github.com/ant-design/ant-design/issues/10281

**Comment by afc163** [comment]
Fxied in #10371
