### ISSUE TITLE
table中使用cascader的loadData方法不生效

### ISSUE THREAD

**Issue by yangxy6** [ant-design/ant-design#10409]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
win7，chrome66.0

### Reproduction link
[https://codepen.io/shirley_0107/pen/odoKyQ](https://codepen.io/shirley_0107/pen/odoKyQ)

### Steps to reproduce
在table的Column中引入Cascader，使用异步加载loadData未生效，方法加载不到

### What is expected?
正确异步加载数据

### What is actually happening?
loadData方法未执行

**Comment by yesmeck** [comment]
子节点没数据才会去 `loadData`。

**Comment by yangxy6** [comment]
子节点没有数据loadData依旧不执行，codepen不方便实现异步调数据 @yesmeck

**Comment by yesmeck** [comment]
https://codepen.io/yesmeck/pen/eryzPp

**Comment by yangxy6** [comment]
谢谢，发现被自己坑了 @yesmeck

**Comment by ybning** [comment]
```
isLeaf=false
```
会触发loadData
@yangxy6
