### ISSUE TITLE
form表单inline布局下启用验证样式问题

### ISSUE THREAD

**Issue by Yuliang-Lee** [ant-design/ant-design#1040]
label没法对齐.如下图

![qq 20160219185844](https://cloud.githubusercontent.com/assets/6936358/13173849/d298514a-d73a-11e5-8d61-43f158b5b2cb.png)

**Comment by afc163** [comment]
Need Demo

**Comment by Yuliang-Lee** [comment]
@afc163 Demo: http://codepen.io/Yuliang-Lee/pen/eJayMR?editors=0010

**Comment by afc163** [comment]
试试都加上 `labelCol` 和 `wrapperCol`。

**Comment by Yuliang-Lee** [comment]
加上OK了.但是FormItem的宽度是不能自适应的吗?另外,里面的InputNumber输入数字也还是一直提示不能为空,第二个Select选完了之后点击空白的地方选项就会消失提示不能为空.还是刚才那个Demo

**Comment by afc163** [comment]
上面也针对最开始的问题进行了修复。

另外，校验问题可以参看下这里的使用方式：http://ant.design/components/form/#demo-validate-other 例子里是好的。
