### ISSUE TITLE
Recommend to add the can toggle visible/invisible password input component

### ISSUE THREAD

**Issue by SeanGol** [ant-design/ant-design#10411]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在输入密码时，用户可能多次错误输入某一字符，但由于密码输入框的不可见性，不能及时发现，一个可切换可见/不可见的密码输入框就能很好解决这个问题。
该组件除了在登陆时可以使用外，在后台管理平台需要配置密码项中，也能够很好应用，比如SaaS管理平台配置MySQL密码。

### What does the proposed API look like?
API字段可以在现有Input组件上，添加一个"visible" （type：Boolean，default：false），组件内部可对其控制切换
对应可见不见两种状态，点击右侧图标，切换visible，如下图：
![image](https://user-images.githubusercontent.com/8014327/39737616-c09e6adc-52b8-11e8-97ee-0aa90dc42a3f.png)
![image](https://user-images.githubusercontent.com/8014327/39737623-cd16abbc-52b8-11e8-9239-4d0ea9b9eed1.png)

**Comment by yesmeck** [comment]
自己动态修改 `Input[type]` 即可。
