### ISSUE TITLE
Design pattern about message component

### ISSUE THREAD

**Issue by zhenghangjie** [ant-design/ant-design#10421]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. why should onClose use callback not promisify like message[level](content, [duration]).then()
2. duration has 'function' type but not reflected in docs

### What does the proposed API look like?
update docs or change design pattern

**Comment by afc163** [comment]
1. PR is welcome~
2. I think `message.success(content, [duration], onClose)` can indicate that.

**Comment by zhenghangjie** [comment]
upward compatible or another method ? @afc163

**Comment by afc163** [comment]
`message.success(content, [duration], onClose).then()` would be fine.

**Comment by zhujinxuan** [comment]
@afc163 I am trying to submit a PR about it.  But there is a small question.

We had 
```
const hide = message.success(....);
hide() 
```
To close the message.  Suppose we have 
```
const hidePromise = message.success(..., onClose);
hidePromise(hide => hide() );
```
The hide shall be evaluated before `onClose`

Suppose we have 
```
const hidePromise = message.success(..., onClose);
hidePromise(()=> onClose2() );
```
Shall we still have onClose2 evaluated before `onClose`?

**Comment by zhujinxuan** [comment]
I made a PR for this feature https://github.com/ant-design/ant-design/pull/10470

**Comment by viztor** [comment]
close?
