### ISSUE TITLE
datePicker的mode为'year'时，选中年份，下拉框不会消失

### ISSUE THREAD

**Issue by LJJCherry** [ant-design/ant-design#10425]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
chrome

### Reproduction link
[https://codepen.io/anon/pen/gzowME?editors=0010](https://codepen.io/anon/pen/gzowME?editors=0010)

### Steps to reproduce
https://codepen.io/anon/pen/gzowME?editors=0010

### What is expected?
选择年份后下拉框关闭

### What is actually happening?
选择年份后下拉框未关闭

**Comment by zhujinxuan** [comment]
Translation for title:
When the DatePick has mode equals 'year', the drop-down box fails to hide after the year is selected.

**Comment by funfish** [comment]
mode 是用来做日期选择器头部 受控面板 切换用的。datePicker 下，点击年份会触发onPanelChange事件，这个时候mode理应变为 month，也就是切换为 month 选择面板，但是 mode 固定了，所以表现就是下拉框不会变化

**Comment by funfish** [comment]
面板切换是触发onPanelChange事件，设计中就是要选了年份后，mode切换为month，继续选月份的，所以下拉框不会消失，但是这里mode一直为year，所以什么都没有变化

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4524

**Comment by LJJCherry** [comment]
@那就是还不支持单纯的年份选择框是吗？@afc163

**Comment by LJJCherry** [comment]
我其实只是希望通过mode为year实现一个单纯的年份选择框。。。 @funfish

**Comment by LJJCherry** [comment]
Because when I set mode to 'year', onChange don't work ,but I can get the Changed year from 'onPanelChange', In my project,I just want a year picker @zhujinxuan

**Comment by qinyuhua** [comment]
我也遇到了这个问题，请问楼主解决了吗？

**Comment by panjiefeng** [comment]
the source code of rc-calendar only support year panel which isn't a 'Picker'. There is a solution that I repackage a component by using the API of the DatePicker. hope this helps!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16984
