### ISSUE TITLE
table/select/checkbox  数据多 选中响应慢

### ISSUE THREAD

**Issue by Tuerping** [ant-design/ant-design#10431]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
react 16.2.0；  antd 3.4.3

### Reproduction link
[https://github.com/Tuerping/testTableCheckbox](https://github.com/Tuerping/testTableCheckbox)

### Steps to reproduce
在tableList  页面中 当pageSize 为10 时 点击checkbox 反应速度正常； 当pageSize为200时，点击checkbox反应速度变慢

### What is expected?
checkbox点击反应速度和 pageSize数据量 与 columns数量 无关

### What is actually happening?
当pageSize或者columns 增多，checkbox点击反应速度会变慢

**Comment by QzAmoy** [comment]
这个问题我也遇到了，数据量大的时候，不止勾选响应慢，甚至会影响其他组件的响应速度。不知道你是否有找到解决方法？

**Comment by Tuerping** [comment]
没有找到办法，没人回答我的问题；你有解决出来吗？

**Comment by QzAmoy** [comment]
没有啊，试过删除动画，没什么效果。我看你发了听多次这个问题，都被关掉了。

**Comment by Tuerping** [comment]
自己写checkbox进去吧，自己写事件

**Comment by afc163** [comment]
> Issues labeled by Need Reproduce will be closed if no activities in 7 days.

@yesmeck seems not working

**Comment by fgiarritiello** [comment]
Can we please reopen this? Here is a link to reproduce the problem

https://codepen.io/anon/pen/QYdWaE?&editable=true&editors=001

When the table has many rows rendered the UI becomes really laggy and the page is just slow and unusable.

**Comment by galbash** [comment]
I am experiencing the same problem :( I think the reason is that all of the cells are re-rendered even though only the selection changed. Is there any way around this? I tried returning a custom ReactNode from the `render` function of the `columns` property that overrides `shouldComponentUpdate`, but I think since the function is called each time the table is rendered, I end up getting different components each time and they are rendered anyway.
thoughts?

**Comment by fgiarritiello** [comment]
yeah, I would expect that when a row is selected or expended only that row should be re-rendered. Instead the whole table is re-rendered and it gets pretty much unusable when you have a big set of data. This is becoming a show stopper for my company.

**Comment by UnicornXU** [comment]
最后这个问题解决了么?我也遇到了这个问题

**Comment by ztplz** [comment]
感觉我可以挑战一下

**Comment by lttien1** [comment]
@ant-design-bot 

How about this issue?

**Comment by songyule** [comment]
我用了分页，每页十条，datasource.length = 10000 的时候点分页就很卡

**Comment by Jonarzz** [comment]
This is a very important issue for my company as well.

**Comment by tsahnar** [comment]
Also encountering this issue. Has anybody managed to have good performance with multiple selection and a lot of rows?

**Comment by DeadManPoe** [comment]
Experiencing the same issue for my company too.

**Comment by mqliutie** [comment]
我解决的办法是将`Checkbox`拆分成**独立组件**, 有自己的`state`

 `Checkbox` `onchange`的时候调用父组件的`onChange`

父组件的`onChange`不做`setState`, 而是更新 `this.checkedList`

当 `indeterminate` 不等于更新后的 `indeterminate` 的时候` forceUpdate` 因为这个时候父组件要更新自己的全选状态,其他时候让`Checkbox`组件自己玩`

 `Checkbox`组件在`componentWillReceiveProps`判断组件自身状态是否需要更新

这样只有在全选和非全选切换的时候才出现一下卡顿

下面是我的Checkbox 组件

```
class MyCheckbox extends Component {

    constructor(props) {
        super(props);
        const { checkedList = [], id } = props;
        this.state = {
            checked: checkedList.indexOf(id) !== -1
        };
    }

    componentWillReceiveProps(nextProps, nextContext) {
        if (this.props.isSelectAll !== nextProps.isSelectAll) {
            // 全选之间的切换, 如果目标结果是全选, 全部设置checked
            if (nextProps.isSelectAll) {
                return this.setState({
                    checked: true
                });
            }
        }
        if (this.props.isSelectAll === true) {
            // 如果现在是全选状态, 目标操作是取消全选 并且已经明确(indeterminate === false)是全部取消(取消单行也是取消全选,但不是全部取消) 
            if (nextProps.isSelectAll === false && nextProps.indeterminate === false) 
                return this.setState({
                    checked: false
                });
            }
        }
    }

    render() {

        return (
            <Checkbox
                disabled={this.props.disabled}
                onChange={() => {
                    this.setState(state => ({ checked: !state.checked }));
                    this.props.onChange();
                }}
                checked={this.state.checked}
            />
        );
    }
}
```

**Comment by Boober44b** [comment]
any working solutions yet?

**Comment by WrathZA** [comment]
I'm also facing this issue.

**Comment by sebas-deedee** [comment]
Any update on this issue?

**Comment by ksh033** [comment]
@afc163 这问题有没有的解决办法.4.0版本好像也没解决这问题的计划

**Comment by chrisbchrist** [comment]
I know you guys work hard, but this is a **really** big problem for enterprise applications that can have tens of thousands of rows, essentially rendering the library useless for managing data.  Has anyone found a workaround for this that doesn't involve forking AntD and rewriting the component from scratch? We've been using AntD and invested a lot of time in developing our own CRUD wrapper for this table, but it looks like we're going to have to start over with something else.

**Comment by 13luck** [comment]
@chrisbchrist, use `ag-grid` for real big dataset.

**Comment by prashanth726** [comment]
Any update!>

**Comment by WJB3** [comment]
数据量很大，每当选择每一行时，时间间隔时间较长

**Comment by WJB3** [comment]
数据量很大，每当选择每一行时，时间间隔时间较长，希望有人能给个官方解决方案

**Comment by prashanth726** [comment]
@Tuerping are you able to solve this?

**Comment by mfaradzh** [comment]
@mqliutie
> My solution was to `Checkbox`split it into **separate components** , with my own`state`
> 
> `Checkbox` `onchange`When calling the parent component`onChange`
> 
> The parent component `onChange`does not do `setState`, but updates`this.checkedList`
> 
> When `indeterminate`the update is not equal to the `indeterminate`time ` forceUpdate`because this time the father of the components to update its full-selected state, at other times so that `Checkbox`the components they play `
> 
> `Checkbox`The component is `componentWillReceiveProps`determining whether the component's own status needs to be updated
> 
> This will only cause a lag when switching between full and non-selection
> 
> Below is my Checkbox component
> 
> ```
> export default class MyCheckBox extends Component {
>     static displayName = 'MyCheckBox';
> 
>     constructor(props) {
>         super(props);
>         this.state = {
>             checked: false
>         };
>     }
> 
>     static getDerivedStateFromProps(props, state) {
>         if (props.isSelectAll) {
>             return {
>                 checked: true
>             };
>         }
>         if (!props.isSelectAll && !props.indeterminate) {
>             return {
>                 checked: false
>             };
>         }
>         return null;
>     }
> 
>     render() {
>         return (
>             <Checkbox
>                 checked={this.state.checked}
>                 onChange={() => {
>                     this.setState(state => ({
>                         checked: !state.checked
>                     }));
>                     this.props.onChange();
>                 }}
>                 disabled={this.props.disabled}
>             />
>         );
>     }
> }
> ```

Could you please provide an example of how you attached it? 
Thank you

**Comment by see365** [comment]
200条就卡了 性能好差啊

**Comment by mqliutie** [comment]
> @mqliutie
> 
> > My solution was to `Checkbox`split it into **separate components** , with my own`state`
> > `Checkbox` `onchange`When calling the parent component`onChange`
> > The parent component `onChange`does not do `setState`, but updates`this.checkedList`
> > When `indeterminate`the update is not equal to the `indeterminate`time ` forceUpdate`because this time the father of the components to update its full-selected state, at other times so that `Checkbox`the components they play `
> > `Checkbox`The component is `componentWillReceiveProps`determining whether the component's own status needs to be updated
> > This will only cause a lag when switching between full and non-selection
> > Below is my Checkbox component
> > ```
> > export default class MyCheckBox extends Component {
> >     static displayName = 'MyCheckBox';
> > 
> >     constructor(props) {
> >         super(props);
> >         this.state = {
> >             checked: false
> >         };
> >     }
> > 
> >     static getDerivedStateFromProps(props, state) {
> >         if (props.isSelectAll) {
> >             return {
> >                 checked: true
> >             };
> >         }
> >         if (!props.isSelectAll && !props.indeterminate) {
> >             return {
> >                 checked: false
> >             };
> >         }
> >         return null;
> >     }
> > 
> >     render() {
> >         return (
> >             <Checkbox
> >                 checked={this.state.checked}
> >                 onChange={() => {
> >                     this.setState(state => ({
> >                         checked: !state.checked
> >                     }));
> >                     this.props.onChange();
> >                 }}
> >                 disabled={this.props.disabled}
> >             />
> >         );
> >     }
> > }
> > ```
> 
> Could you please provide an example of how you attached it?
> Thank you

For convenience, I imported the `lodash` library

```
import React, { Component } from 'react';
import { Table, Checkbox, Button, Modal } from 'antd';
import _ from 'lodash';


export default class Parent extends Component {
    static displayName = 'Parent';

    constructor(props) {
        super(props);
        this.checkedList = [];
        this.state = {
            data: [{
                id: 1,
                name: 'Lucky'
            }, {
                id: 2,
                name: 'Lily'
            }, {
                id: 3,
                name: 'Jim'
            }],
            columns: [{
                title: () => <Checkbox onChange={e => {
                    if (e.target.checked) {
                        this.selectedAll = true;
                        this.indeterminate = false;
                        this.checkedList = this.state.data;
                        return this.forceUpdate();
                    }
                    this.selectedAll = false;
                    this.indeterminate = false;
                    this.checkedList = [];
                    this.forceUpdate();

                }} checked={this.selectedAll} indeterminate={this.indeterminate}/>,
                key: 'checkbox',
                render: (row) => {
                    return <ChildCheckbox name={row.name} isSelectAll={this.selectedAll} indeterminate={this.indeterminate} onChange={() => {
                        // init values ;
                        this.selectedAll = false;
                        this.indeterminate = true;
                        const originLength = this.checkedList.length;
                        // remove will change checkedList
                        const removedRow = _.remove(this.checkedList, r => r.id === row.id);
                        if (_.isEmpty(removedRow)) {
                            // if removedRow is empty that means the row is not in checkedList
                            // if removedRow is not empty the row was removed from checkedList
                            this.checkedList.push(row);
                        }

                        // now all row is checked so should forceUpdate
                        if (this.checkedList.length === this.state.data.length) {
                            this.selectedAll = true;
                            this.indeterminate = false;
                            // should update selectedAll status
                            this.forceUpdate();
                        }

                        // now all row is not checked so should forceUpdate
                        if (this.checkedList.length === 0) {
                            this.selectedAll = false;
                            // I know that row all is checked or all is not checked.
                            this.indeterminate = false;
                            this.forceUpdate();
                        }

                        // from none to one or from all checkedRows to checkedRows.length - 1, status should be changed
                        if (originLength === 0 || originLength === this.state.data.length) {
                            this.indeterminate = true;
                            this.forceUpdate();
                        }

                    }}/>;
                }
            }, {
                title: 'name',
                dataIndex: 'name',
            }]
        };
    }

    render() {
        return (
            <React.Fragment>
                <Button
                    style={{ marginBottom: 16 }}
                    onClick={() => Modal.info({ title: `Your checkedList value is ${JSON.stringify(this.checkedList, null, 4)}` })}
                >
                    get checkedList</Button>
                <Table bordered columns={this.state.columns} rowKey='id' dataSource={this.state.data}/>
            </React.Fragment>
        );
    }

}

class ChildCheckbox extends React.PureComponent {
    static displayName = 'ChildCheckbox';

    state = {
        checked: false
    };

    static defaultProps = {
        isSelectAll: false,
        indeterminate: false
    };

    static getDerivedStateFromProps(props, state) {
        if (props.isSelectAll) {
            return {
                checked: true
            };
        }
        if (!props.isSelectAll && !props.indeterminate) {
            return {
                checked: false
            };
        }
        return null;
    }

    render() {
        console.log(`name : ${this.props.name} Checkbox render`);
        return (
            <Checkbox
                checked={this.state.checked}
                onChange={() => {
                    this.setState(state => ({
                        checked: !state.checked
                    }));
                    this.props.onChange();
                }}
                disabled={this.props.disabled}
            />
        );
    }
}
```

You can open the chrome dev tool, the console will be logged when toggle select all status

**Comment by huangfei7528** [comment]
这个问题这么久了 请问有解决方案了么

**Comment by jsonshao** [comment]
这么大的问题，官方也不出来给个方案，主要是性能太差了，200条就卡成那样了

**Comment by yoyo837** [comment]
3.x工作安排性能的优先不高，4.0已经在着手解决，你也可以考虑提交相关PR帮助推进。

**Comment by jsonshao** [comment]
好的，希望这个性能问题尽快完善，因为如果基于现有业务更换组件，代价太大，也不利于后期维护




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Amumu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月18日(星期三) 上午10:33
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"742410510"<742410510@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] table/select/checkbox  数据多 选中响应慢 (#10431)




3.x工作安排性能的优先不高，4.0已经在着手解决，你也可以考虑提交相关PR帮助推进。

**Comment by hsluoyz** [comment]
We are also using it in our project. Can we fix it maybe a little sooner?

**Comment by prashanth726** [comment]
Please check https://next.ant.design/ . V4.0 ant design fixed the issue hopefully.

**Comment by hsluoyz** [comment]
@prashanth726 did v4.0 fix this issue?

**Comment by prashanth726** [comment]
@hsluoyz I haven't tested in production. But in 4.0 they support virtual list - https://next.ant.design/components/table/#components-table-demo-virtual-list

And I tried the same on codesandbox environment with filter, sort & checkbox - it worked perfectly.

**Comment by NICK-DUAN** [comment]
Select也会有这个问题

**Comment by furkanilhan** [comment]
> @hsluoyz I haven't tested in production. But in 4.0 they support virtual list - https://next.ant.design/components/table/#components-table-demo-virtual-list
> 
> And I tried the same on codesandbox environment with filter, sort & checkbox - it worked perfectly.

How did you implement the row selection in virtual list? Can you exlain?

**Comment by afc163** [comment]
Perfermance issue had been resolved in favor of our visual list solution in v4: https://github.com/ant-design/ant-design/issues/21656

**Comment by chillyistkult** [comment]
@afc163 There is no "visual list" mentioned on the issue you linked. I don't see the performance issue solved in latest 4.0.2 for a normal table with a couple thousand rows.

**Comment by DeadManPoe** [comment]
@chillyistkult  I think @afc163 meant to say "virtual list". Anyways, I don't think the virtual list solution solves the problem completely: I believe the problem is that the table does a whole re-render every time a checkbox is checked.

**Comment by lorenzocestaro** [comment]
@DeadManPoe  If the table is virtualized properly the component should render again only the rows currently in view.

**Comment by DeadManPoe** [comment]
@lorenzocestaro Sure, still all the rows that are currently visible will be re-rendered. The problem is that only the selected row should be re-rendered rather than all the others, regardless of the use of virtualization

**Comment by lorenzocestaro** [comment]
Sure I completely get your point and agree. What I meant to say is you can mitigate for now by controlling how many rows are visible and manage performance. Of course it would be much better if only the affected row was rerendered.

**Comment by running-snail-sfs** [comment]
不知道这个虚拟表格能不能也优化到3.x，因为很多的项目考虑到兼容性和业务升级的一系列问题，不准备升级4,0，这就很尴尬

**Comment by MinJieLiu** [comment]
table 目前本身是没有结合虚拟滚动的，官方文档的虚拟滚动例子局限很大，样式得自己写

**Comment by StallionV** [comment]
We are facing the same problem this like row selection, hover, onRow function are all triggering a whole table render instead of only rendering the row in action.
This degrades the performance dramatically specially when you have 100's or 1000's of records.

Yes you can use [virtual grid ](https://ant.design/components/table/#components-table-demo-virtual-list)looks like now, but that would probably mean rewriting the table because it is not a small change, the example in docs shows this as a much bigger change and a completely different way to write your tables.

It does not take away from the fact that not all rows should be re-rendered when only one changes

**Comment by StallionV** [comment]
Opened #23763 since this issue was closed.
This really should be amongst the top priority of this library, otherwise a very useful component like table dies a slow death due to underlying performance issues.

**Comment by WangYang-Rex** [comment]
ant-table的性能太差，@4.0中的虚拟滚动技术确实可以，但是局限性太大，比如如何实现虚拟滚动+固定列的功能；以及虚拟滚动时如何实现列的选中，好像都不支持，望解答

**Comment by MinJieLiu** [comment]
虚拟滚动 => 列选中/树形我实现了，但就是列的边框条与 顶部表头无法完全对齐，目前只能隐藏列边框

**Comment by WangYang-Rex** [comment]
@MinJieLiu 有实现固定列吗？

**Comment by MinJieLiu** [comment]
没有

**Comment by lxsunbin** [comment]
3.x版本有没有解决方案呢？升级到4.0成本太高了。。

**Comment by littlebox692** [comment]
> @hsluoyz I haven't tested in production. But in 4.0 they support virtual list - https://next.ant.design/components/table/#components-table-demo-virtual-list
> 
> And I tried the same on codesandbox environment with filter, sort & checkbox - it worked perfectly.

cannot connect to next.ant.design, server's down?

**Comment by afc163** [comment]
@littlebox692 https://ant.design/components/table/#components-table-demo-virtual-list

**Comment by laosandegudai** [comment]
选中行很慢，20条也慢，有解决方案吗？版本是目前最新cli生成。  "antd": "^4.4.0",

**Comment by dwb1994** [comment]
Checkbox 虚拟滚动我实现了

**Comment by zhouccccc** [comment]
`"antd": "^4.14.1"`
表格数据是167条，虽然上下滚动不卡，但是横向滚动有明显卡顿，CheckBox也卡顿明显.
希望官方及时解决下这个问题

**Comment by Bravo123** [comment]
table通过rowSelection自带的checkbox会导致选中响应慢，可以自己实现一个checkbox，在选择上面可以减少卡顿。

**Comment by wangym0203** [comment]
我换成了原生 <input type='checkbox'/> 就不卡了。 之前的场景是 大概有5000多个checkbox。用antd的Checkbox组件会变得非常卡。感觉应该是动画引起的原因，因为我并没有数据绑定，再点击选中后，并没有触发render

**Comment by Dabeer-Raza** [comment]
> 我换成了原生 < input type='checkbox' /> 就不卡了。 之前的场景是 大概有5000多个checkbox。用antd的Checkbox组件会变得非常卡。感觉应该是动画引起的原因，因为我并没有数据绑定，再点击选中后，并没有触发render

Life Saver

**Comment by amodes** [comment]
I am adding to every column in the table

```js
shouldCellUpdate: (record, prevRecord) => !_.isEqual(record, prevRecord);
```

This way just the checked cell gets updated

**Comment by liuxi0811** [comment]
现在有解决方案了吗

**Comment by AsuraKev** [comment]
its 2023 Aug, issue still present. Time to give up on this library

**Comment by AsuraKev** [comment]
I think opting out of the built in checkbox basically made the performance so much better. but question is you lose all the callback method that Antd provides? Does anyone have any sample implmentation of rolling your own checkbox? 

![image](https://github.com/ant-design/ant-design/assets/52765572/406f84be-6970-4228-abc7-b9da6f50e516)

**Comment by EquinoxFlowerJG** [comment]
2023年9月了，这个问题就真的没有什么合理的解决方案吗？？？

**Comment by yoyo837** [comment]
> 2023年9月了，这个问题就真的没有什么合理的解决方案吗？？？

除table外不是已经支持虚拟列表了吗? table的也已经合并待发布了.

**Comment by AsuraKev** [comment]
I dont know if this will fix this issue

https://github.com/ant-design/ant-design/pull/44349

**Comment by EquinoxFlowerJG** [comment]
> > 2023年9月了，这个问题就真的没有什么合理的解决方案吗？？？
> 
> 除table外不是已经支持虚拟列表了吗? table的也已经合并待发布了.

需要的就是Table组件的虚拟列表支持，不是自己使用虚拟列表去重写的那种。

**Comment by yoyo837** [comment]
> I dont know if this will fix this issue
> 
> #44349

Yes. The last component supported by the virtual list in the TODO list: `table`

**Comment by EquinoxFlowerJG** [comment]
> > I dont know if this will fix this issue
> > #44349
> 
> Yes. The last component supported by the virtual list in the TODO list: `table`

什么时候发布？支持版本4吗？

**Comment by AsuraKev** [comment]
@yoyo837 right, I dont know if row selection is still going to lag even in large virtual list ~~~

**Comment by yoyo837** [comment]
> > > I dont know if this will fix this issue
> > > #44349
> > 
> > 
> > Yes. The last component supported by the virtual list in the TODO list: `table`
> 
> 什么时候发布？支持版本4吗？

应该快了, 目前只在5.x中, 预计5.9.0.

**Comment by yoyo837** [comment]
> @yoyo837 right, I dont know if row selection is still going to lag even in large virtual list ~~~

I personally haven't done much testing on it, it comes from other members, and `antd` is willing to keep improving it. :)

**Comment by heshubin** [comment]
> 感觉我可以挑战一下

请问，表格卡顿问题解决了吗

**Comment by Reeyc** [comment]
2024年了，3.x版本至今未解决，卡就算了，关键别影响别的组件啊，我在表格最外层套了个loading，明明loading值都变了，loading效果就是在表格动画之后才出现

**Comment by afc163** [comment]
3.x 版本？antd 已经发到 5.x 版本了。

**Comment by mundane799699** [comment]
2024年了，这个问题解决了吗？我目前用的是5.16.2，感觉还是有这个问题

**Comment by QiCodeCN** [comment]
![table加载后卡很久才可以正常选中或取消](https://github.com/ant-design/ant-design/assets/52949189/8e125886-4e9d-418c-91c5-4be8353ed139)
最近在用antdpro莫名奇妙也遇到此问题，上官方体验下下也也，总感觉有相互影响地方，不知道官方或其他大佬有人能办法吗？

**Comment by AsuraKev** [comment]
its Aug 2024, has this issue been resolved? :/ I am currently using Virtual table for now, but felt like the normal Table still has fundamental issue ...

**Comment by matisszemturis** [comment]
Still not resolved, very slow with large data-set.

**Comment by helmif** [comment]
any solution for this issue?

**Comment by Avhishek05** [comment]
this is still not fixed using 5.21.2 version

**Comment by Bulala-liu** [comment]
I updated antd from 5.15.1 to 5.22.2. Table renders very slowly when pageSize is bigger than 100, the checkbox is also getting worse

**Comment by kneczaj** [comment]
I have found the same issue, and I decided to switch directly to rc-table. The problem seem to be there too, so I thing this is rather rc-table problem.

**Comment by LiMuBai-ACE** [comment]
2025.6.5 留言 表示依旧未能解决此问题

**Comment by jmct123** [comment]
2025.6.13日了，直到现在antd@5.26.0，table超过两百个使用rowsSelection都卡得一批，哪怕自定义checkbox都卡，我试过element-ui，同样渲染一个超过两百条的数据，多选框全选很快。
