### ISSUE TITLE
Form error is showing in wrong position

### ISSUE THREAD

**Issue by lovekonakona** [ant-design/ant-design#10435]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
MacOS 10.13.4, Chrome 66.0.3359.139, React 3.5.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n32nv3jrml)

### Steps to reproduce
Use Row in Item.

### What is expected?
Error's position is correct.

### What is actually happening?
Error is floating by first tag.

---
Add clearfix for `.ant-form-item-children` but `inline` mode.

**Comment by lovekonakona** [comment]
![image](https://user-images.githubusercontent.com/790296/40037498-252ac004-5840-11e8-81f6-b5807392682d.png)
@wmzhong wm

**Comment by wmzhong** [comment]
@lovekonakona  Can't reproduce in your example.

![image](https://user-images.githubusercontent.com/5080442/40039396-dc2fc152-5848-11e8-9464-8a2603900c49.png)

**Comment by lovekonakona** [comment]
I cannot reproduce it too, I print the version of antd, it is 3.5.2, maybe antd was fixed it.
@wmzhong

**Comment by andrea-smartsailors** [comment]
Here's another related behaviour which is fixed by changing  .ant-form-item-children 's display: inline to display: block (antd 3.6.2)

![screenshot from 2018-07-05 09-51-33](https://user-images.githubusercontent.com/39905014/42309553-3076ef5c-8039-11e8-8ce6-4a1ebf7e7417.png)
