### ISSUE TITLE
message 组件 设置不自动关闭时，无法手动关闭

### ISSUE THREAD

**Issue by mengtw** [ant-design/ant-design#10432]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
谷歌

### Reproduction link
[https://codepen.io/anon/pen/dedbML?&editors=001](https://codepen.io/anon/pen/dedbML?&editors=001)

### Steps to reproduce
设置持续时间为0，无法手动关闭

### What is expected?
出现关闭小×，可以设置关闭回调函数

### What is actually happening?
没有出现关闭图标，点击无法关闭

**Comment by afc163** [comment]
https://ant.design/components/message/#components-message-demo-loading
