### ISSUE TITLE
Select组件bug

### ISSUE THREAD

**Issue by shenck215** [ant-design/ant-design#10436]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
win 10,chrome 65.0.3325.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9l91616q2r)

### Steps to reproduce
在onChange回调中调用this.setState需要选择两次才能关闭下拉框，在onSelect回调中调用this.setState选中后无法关闭下拉框

### What is expected?
选中后正常关闭下拉框

### What is actually happening?
在onChange回调中调用this.setState需要选择两次才能关闭下拉框，在onSelect回调中调用this.setState选中后无法关闭下拉框

---
在react16.2.0,react-dom16.2.0下,会出现如上结果。在react16.3.2,react-dom16.3.2下,正常。

**Comment by zombieJ** [comment]
fixed in `rc-select 8.0.7`. Pls re-install node_modules.

ref: https://github.com/ant-design/ant-design/issues/10400
