### ISSUE TITLE
table fixed right

### ISSUE THREAD

**Issue by geraldchen890806** [ant-design/ant-design#10444]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
chrome

### Reproduction link
[https://codepen.io/geraldchen89/pen/KRQNVW?&editors=001](https://codepen.io/geraldchen89/pen/KRQNVW?&editors=001)

### Steps to reproduce
set fixed right in previous columns

### What is expected?
column with fixed right show in right

### What is actually happening?
column with fixed right display twice

**Comment by yesmeck** [comment]
> column with fixed right display twice

It's by design.

**Comment by geraldchen890806** [comment]
@yesmeck 
i mean we can do 
```
_.filter(columns, (d) => d.fixed !== 'right').concat(_.filter(columns, (d) => d.fixed === 'right').);
```

**Comment by yesmeck** [comment]
没看懂你想说什么。

**Comment by yesmeck** [comment]
中间列 fixed 没有意义

**Comment by Kris-Lee-SH** [comment]
@geraldchen890806 How do u fix it?

**Comment by geraldchen890806** [comment]
@Kris-Lee-SH don't set 'fixed' in middle columns

**Comment by Kris-Lee-SH** [comment]
@geraldchen890806 Actually, set `fixed` in middle columns works.
The exact difference is keep at least one column without `width` configuration.
It seems like tables with `fixed` columns is combined by two, or three if there is both `left` and `right` fixed columns, tables. I call the table with all column as base table, and the table combined by all fixed columns fixed table. The table we see is one, or two, fixed table float on the base table. The scroll props will define the base table's scroll width and height. If the sum of  none-fixed columns width is smaller than `scroll.x`, the base table's columns which have fixed will appear. Well, actually these columns should be overlay by the fixed table's columns, which have the same props.

So, **keep one or more columns without `width` configuration** to ensure the base table will spread to suit the view's width, then the fixed table will correctly overlay these columns with fixed props.

**Comment by uriee** [comment]
Thanks Kris-Lee-SH,
Your comment helped me a lot.
It's worth mentioning that in order for this fix to work the column must be **between**  the float left column and the float right column.
I first inserted an empty column ({title : ''}) as the last column and it did not fix the problem , only when i inserted it before the last column it fixed all issues perfectly.
