### ISSUE TITLE
Form表单项校验位置高度出现抖动

### ISSUE THREAD

**Issue by sbyps** [ant-design/ant-design#10445]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
win7, chrome 61.0.3163.100

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-register](https://ant.design/components/form-cn/#components-form-demo-register)

### Steps to reproduce
https://ant.design/components/form-cn/#components-form-demo-register
1、在password项输入1后迅速删除表单项高度出现抖动，重复多次
2、试验多次后发现当校验处于临界状态时，高度会出现抖动

### What is expected?
表单项高度不发生改变

### What is actually happening?
表单项高度校验位置高度发生改变

**Comment by sbyps** [comment]
https://github.com/ant-design/ant-design/issues/7730 和这个问题有类似

**Comment by sbyps** [comment]
https://github.com/ant-design/ant-design/pull/9675 似乎这个修复不完整吧

**Comment by sbyps** [comment]
@jljsj33

**Comment by johnJine** [comment]
解决方法1:
.ant-form.ant-form-horizontal .ant-form-item{
margin-bottom: 0;
min-height: 56px;
}
