### ISSUE TITLE
Select的tags模式，输入框的值始终会展示在下拉菜单的第一项

### ISSUE THREAD

**Issue by vito24** [ant-design/ant-design#10449]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
Chrome 59

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2x092kjmzj)

### Steps to reproduce
输入1

### What is expected?
不展示下拉第一项

### What is actually happening?
远程获取数据，渲染Select的下拉菜单，每次下拉菜单的第一项都是搜索框的值，然而搜索框的值不在远程获取的数据中
![qq 20180509223716](https://user-images.githubusercontent.com/13133596/39820917-8e1911e4-53d9-11e8-8c0f-532a6eee4c6e.png)

**Comment by afc163** [comment]
It is a right behavior for `Select[mode="tags"]`

**Comment by vito24** [comment]
Sorry!
I should use `Select[mode="multiple"]`

**Comment by fatfan** [comment]
> 

> 

请问下，Select[mode="tags"] 时下拉菜单里面未匹配到children的Option能否自定义渲染？
如题主截图下拉菜单中的1进行自定义渲染

期望提供optionRender实现自定义Option，类似tagRender的API

```
const options = [{ value: 'gold' }, { value: 'lime' }, { value: 'green' }, { value: 'cyan' }];

function optionRender(props, dom) {
  const { label, value } = props;
  // 未匹配到options的选项进行自定义
  if(!options.find(x=> x.value === value)) {
    return <Select.Option>
        <span>{label}</span>
        <span>Something New!</span>
    </Select.Option>
  }
  return dom;
}

<Select
    mode="tags"
    optionRender={optionRender}
    defaultValue={['gold', 'cyan']}
    options={options}
/>
```
