### ISSUE TITLE
multiple Select can't handle children which is hidden when select option

### ISSUE THREAD

**Issue by Irislm** [ant-design/ant-design#10440]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
Chrome 66.0.3359.139

### Reproduction link
[https://github.com/Irislm/antd-demo](https://github.com/Irislm/antd-demo)

### Steps to reproduce
1、Select Component's mode is multiple
2、Select any option

### What is expected?
When select option, there is no error. Can select any option.

### What is actually happening?
Select Component is wrong

---
Select options data is asynchronous,  so Spin Component will be a better user experience when fetching data.

**Comment by zombieJ** [comment]
Add online sample: https://codesandbox.io/s/qk9pkq6w26
