### ISSUE TITLE
antd组件渲染优化

### ISSUE THREAD

**Issue by echowant** [ant-design/ant-design#10442]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前，antd组件在使用渲染检测工具whyDidYouUpdate检测时，会警告重复渲染。

希望antd组件能够**避免组件的不必要渲染或不必要的虚拟DOM比较**。比如，采用ImmutableJS shouldComponentUpdate判断是否进行Antd组件渲染。

该优化对于时间需求苛刻的项目很重要。

### What does the proposed API look like?
在相关antd组件中，增加如下判断 （仅做参考）
```
shouldComponentUpdate(nextProps) {
    const nextData = Immutable.fromJS({
      a: nextProps.a,
      b: nextProps.b,
      c: nextProps.c,
    });
    const thisData = Immutable.fromJS({
      a: this.props.a,
      b: this.props.b,
      c: this.props.c,
    });
    return !Immutable.is(nextData, thisData);
  }
```

**Comment by yesmeck** [comment]
组件不会依赖 ImmutableJS，欢迎提出更具体的优化建议，更欢迎直接给我们 PR。
