### ISSUE TITLE
BSOD 原因找到了，请到mark-twain合并下PR

### ISSUE THREAD

**Issue by guxingke201** [ant-design/ant-design#10441]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
win10，win7

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
1. 访问[虚拟机下载地址](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
1. 选择MSEdge on Win10 (x64) Stable (16.16299)和VirtualBox，下载并启动虚拟机
1. 下载master源码
1.  运行`npm install`
1. 运行`npm run start`cpu暴涨到99%
1. 控制台输出卡在`building modules (1734/1735 modules)`，如果是真机，部分win10,win7会出现蓝屏死机（BSOD）

### What is expected?
运行`npm run start` 能正常启动项目

### What is actually happening?
运行`npm run start`控制台输出卡在`building modules (1734/1735 modules)`，如果是真机，部分win10,win7会出现蓝屏死机（BSOD）

**Comment by guxingke201** [comment]
@yesmeck  找到原因了，请更新下mark-twain版本号。
https://github.com/benjycui/mark-twain/pull/21

**Comment by benjycui** [comment]
```bash
➜  mark-twain git:(master) npm publish
+ mark-twain@2.0.3
```
