### ISSUE TITLE
When i use select component and form component, use props initialValue can not normal work.

### ISSUE THREAD

**Issue by mintsweet** [ant-design/ant-design#10443]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
win10, chrome65

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ly6x7325kl)

### Steps to reproduce
  - create select component
  - incoming a data props
  - setting form's getFieldDecorator initialValue
  - show key not options's child

### What is expected?
Set the initialization value to the key of the option, I want show option's child not key

### What is actually happening?
show option's key or data's value

**Comment by yesmeck** [comment]
`key` is `string`, but you pass a `number` as `value`.
