### ISSUE TITLE
Table filter doesn't work on checkbox click

### ISSUE THREAD

**Issue by shivamgupta94** [ant-design/ant-design#10452]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
Windows 8, Chrome Version 66.0.3359.139 (Official Build) (64-bit)

### Reproduction link
[https://ant.design/components/table/#components-table-demo-head](https://ant.design/components/table/#components-table-demo-head)

### Steps to reproduce
See link of example on the ant design page (https://ant.design/components/table/#components-table-demo-head)
The filter works on clicking the text, but not by clicking the checkbox

### What is expected?
Works when checkbox is clicked

### What is actually happening?
Works only when the filter popup text is clicked

---
Probably something broke in the latest build. It worked fine about a month ago.

**Comment by afc163** [comment]
@picodoth Look up this problem, it will trigger twice Menu[onClick] when click Checkbox.

![1](https://user-images.githubusercontent.com/507615/39850131-5687e20a-5442-11e8-81e8-310edcb3f885.gif)

**Comment by shivamgupta94** [comment]
It works when you click on the menu text. But it doesn't work when the check box is clicked.
Just providing further context.

**Comment by picodoth** [comment]
working on this

**Comment by afc163** [comment]
Should be fixed in
