### ISSUE TITLE
建议 less custom 中的各个变量也增加个 ant 前缀

### ISSUE THREAD

**Issue by someok** [ant-design/ant-design#1045]
打算将 bootstrap 中部分 less 引入，不过发现不少 less 变量是重复的，导致样式变幻莫测。

所以建议 antd 的变量可否能够增加个前缀啊，这样也好减少冲突。

**Comment by afc163** [comment]
我们参考了很多 bootstrap 中的变量。

不建议两者进行混用啊。

**Comment by someok** [comment]
我觉得各自独立更好吧 ，这样引入一些 antd 没有的组件的时候就比较方便了，现在的方式还得手工做很多处理。

**Comment by afc163** [comment]
暂时不支持，感觉意义不大，抱歉~
