### ISSUE TITLE
Keyboard shortcuts in Select

### ISSUE THREAD

**Issue by antoinetissier** [ant-design/ant-design#10451]
I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
After clicking on a HTML <select> with options John, Jack, Alice and Bob, pressing "A" on the keyboard allows to jump to the first option whose caption starts this first letter (Alice in my example). Pressing "J" and "O" quickly allows to jump to John. This is a feature that is available in the dropdowns of most websites (for example choosing one's country when booking a flight). It would be nice to have in Ant "Select" too.

From a user experience point of view, having a shortcut always feels better, and not having it can be frustrating if this is a common habit.

### What does the proposed API look like?
From an API point of view, this could potentially not change anything if it was always activated.

Otherwise, there could be a dedicated flag passed a prop to activate/deactivate the feature.

**Comment by afc163** [comment]
https://ant.design/components/select/#components-select-demo-search

Try `showSearch`
