### ISSUE TITLE
Child data comes without click in Tree data table component

### ISSUE THREAD

**Issue by firepunch** [ant-design/ant-design#10459]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
Mac OS^10.13.3, react^16.2.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y07w2v615v)

### Reproduction Screen Shot
<img src="https://bit.ly/2I9zYp3" width="400" height="600">
<img src="https://bit.ly/2I2IauZ" width="400" height="600">
<img src="https://bit.ly/2Ix78Cj" width="400" height="600">
<img src="https://bit.ly/2I5zYdK" width="400" height="600">

### Steps to reproduce
1. Check the data according to the date.
2. Data comes out regardless of the tree.  
**Notice the extension icon. Child data appears without clicking.**

### What is expected?
<img src="https://bit.ly/2jNeHXm" width="400" height="900">

### What is actually happening?
Without clicks, child data should not be visible. Data of the same date shall be available.

**Comment by yesmeck** [comment]
Can not reproduce your issue on the link you post.

**Comment by firepunch** [comment]
@yesmeck  Can not implement as a link because it is a random phenomenon.

**Comment by yesmeck** [comment]
If we can not reproduce it, we can not fix it.

**Comment by firepunch** [comment]
I'm so sorry. I don't know the cause, so I can't reproduce it. I'll close this issue.
