### ISSUE TITLE
upload组件在Form中，并且listType="picture-card"时，上传过程中右上角删除按钮不出现

### ISSUE THREAD

**Issue by kunkkaliu** [ant-design/ant-design#10454]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
Mac，chrome  66.0.3359.139（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/611yj2vy63 )

### Steps to reproduce
重现链接里面将listType修改为picture-card

### What is expected?
上传过程中右上角有删除按钮

### What is actually happening?
上传过程中删除按钮不可见

**Comment by afc163** [comment]
> 重现链接里面将listType修改为picture-card

为什么不直接改好呢

**Comment by kunkkaliu** [comment]
https://codesandbox.io/s/m5xq759099
sorry 改好了
