### ISSUE TITLE
Transfer Bug On Edge - Not Found label visible when remove and than take back items 

### ISSUE THREAD

**Issue by vorlov** [ant-design/ant-design#10464]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
Microsoft Edge 41.16299.402.0, Win 10

### Reproduction link
[https://ant.design/components/transfer/](https://ant.design/components/transfer/)

### Steps to reproduce
advanced example on demos, type in "content4", move this item to the left, then click on the cross icon to remove "content4" from search, and observe

### What is expected?
4 items on the left without "not found" label

### What is actually happening?
4 items on the left with "not found" label

---
works fine on chrome

**Comment by afc163** [comment]
Edge are using webkit now, we won't fix bugs from old version of Edge now.
