### ISSUE TITLE
[Table] Provide 'currentPageData' on 'onChange'

### ISSUE THREAD

**Issue by mkaradeniz** [ant-design/ant-design#10462]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm trying to get the `currentPageData` out of the `<Table />` to save the filtered and sorted data in state / redux store.

For example: I'd like to export an excel sheet with exactly the data and order that is currently visible. 

Antd provides a great way to define sorters and filters and I'd like to not keep a seperate state of which items are visible and in what order (and filter them again outside of the component) if `<Table />` already does that internally. Currently the only way to get this, is to abuse the `title` or `footer` props to somehow save the current state somewhere else (e.g. `this.setState()` or by dispatching an redux action), because these are the only callbacks that provide the `currentPageData`.

My Idea would be to provide the `currentPageData` on the `onChange` function as well.

### What does the proposed API look like?
```js
<Table
    dataSource={data}
    onChange={(pagination, filters, sorter, currentPageData) => /* save currentPageData to store */}
>
  {...}
</Table>
```

This way we could take the `currentPageData` and put it inside the state or redux store.

**Comment by yesmeck** [comment]
#10298
