### ISSUE TITLE
is it possible to combine inline and horizontal inputs at form?

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1047]
i.e. i need 2 rows, first raw must be stretched as much as possible, but second row must hold more elements. I tried flex row, inline/horizontal but no success :(
```
https://www.dropbox.com/s/omc70f1kdm53un8/Screenshot%202016-02-21%2016.33.02.png?dl=0
```
as you see 'title' and 'category' is not align well. Category's input also must take as much space as possible. Same for title's input - it must take as much space as possible. 

Can you help me to make such simple form?

**Comment by benjycui** [comment]
Try: http://ant.design/components/layout/#demo-basic

Here is an example: http://codepen.io/anon/pen/wMLrYJ?editors=001

I know it's unfriendly for non-Chinese speaker...

**Comment by plandem** [comment]
thanks, looks like right way to dig. Google translate helps sometime, but not so often actually :)
