### ISSUE TITLE
the dropdown menu in component "Dropdown" -> Hidden when hover (or click) ....

### ISSUE THREAD

**Issue by namhoai** [ant-design/ant-design#10471]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
any

### Reproduction link
[https://ant.design/components/dropdown/](https://ant.design/components/dropdown/)

### Steps to reproduce
any

### What is expected?
I want you to fix this error before next week

### What is actually happening?
when you hover (or click ) a button in component "Dropdow"  
=> https://drive.google.com/file/d/1c_1lmnSeaeDRucGIJfy8CaF8MmnqWbSu/view

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8497#issuecomment-351702425

**Comment by namhoai** [comment]
Thanks
