### ISSUE TITLE
Table filter for multiple selection doesn't work

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#10476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
chrome,mac

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
官网的例子中，table的filter的多选例子比如adress就不work

### What is expected?
多选框可选择

### What is actually happening?
多选框不可选

**Comment by yesmeck** [comment]
Duplicate of #10452
