### ISSUE TITLE
Add hover shadow effect and click effect to list.

### ISSUE THREAD

**Issue by roser240** [ant-design/ant-design#10473]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Add a hover and select effect of the list to see if the current right table list shows that the information belongs to that subitem.

### What does the proposed API look like?
Add a list of items in the unity of the click and hovering effect and custom formats, such as 
```
onSelectClassName: default | [string: custom class name]
unSelectClassName:default | [strging: custom class name]
```

**Comment by roser240** [comment]
![default](https://user-images.githubusercontent.com/37793031/39910052-08a09a1e-5528-11e8-95d4-b657b721c488.png)

**Comment by nikogu** [comment]
i think we can add a 'hover' effect, the `clicked` effect is not necessary.

can u pull request for that ? @roser240

**Comment by roser240** [comment]
When the list gets smaller, the contents overflow and the style is out of order. How should I modify this style?
![default](https://user-images.githubusercontent.com/37793031/40466725-7f5cfcd4-5f59-11e8-8929-d2240be2e6f6.png)

**Comment by roser240** [comment]
I think it might be due to the elastic layout, but I won't change it.
I don't know how to submit pr before, can you take a look at the picture?
![default](https://user-images.githubusercontent.com/37793031/40466858-0a5a32c0-5f5a-11e8-9764-0ff13ca46406.png)

**Comment by roser240** [comment]
I have solved some of the style problems and can share them with you to solve the content overflow problem above.
![default](https://user-images.githubusercontent.com/37793031/40470803-2fc6881c-5f67-11e8-928d-43e50c1c3d7f.png)
