### ISSUE TITLE
TreeSelect超过8层后showCheckedStrategy失控

### ISSUE THREAD

**Issue by ice-zjchen** [ant-design/ant-design#10477]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
Max OS 10.13.4, Chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7yow17q3zj)

### Steps to reproduce
点击任意1-8的根节点

### What is expected?
符合showCheckedStrategy=SHOW_PARENT，显示根节点

### What is actually happening?
显示子节点（SHOW_CHILD）或全部（SHOW_ALL）

**Comment by zombieJ** [comment]
感谢反馈。tree select 组件正在重构，会一并修复～

**Comment by zombieJ** [comment]
Fixed in `3.7.0`
