### ISSUE TITLE
Carousel垂直滚动，内容显示不全

### ISSUE THREAD

**Issue by xaasu** [ant-design/ant-design#10489]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
win10 "react": "^16.2.0" 

### Reproduction link
[https://codepen.io/xaasu/pen/YLvJWY?editors=0110](https://codepen.io/xaasu/pen/YLvJWY?editors=0110)

### Steps to reproduce
`<Carousel autoplay vertical dots={false}>
            <div><a href='#'>1111</a></div>
            <div><a href='#'>1234657</a></div>
            <div><a href='#'>sdsaasd 2qasda</a></div>
            <div><a href='#'>112312123231</a></div>
            <div><a href='#'>d asd q2</a></div>
            <div><a href='#'>sad xc2qsczxcz</a></div>
            <div><a href='#'>asdas</a></div>
            <div><a href='#'>其味无穷</a></div>
            <div><a href='#'>asdas</a></div>
            <div><a href='#'>潇洒暗示法</a></div>
            <div><a href='#'>我去问问</a></div>
          </Carousel>`

### What is expected?
按顺序滚动。并且一次显示一行

### What is actually happening?
按顺序滚动，但滚到第四行左右开始，上一轮内容未完全消失，下一行显示不全，如下图所示

![tim 20180514110411](https://user-images.githubusercontent.com/24312839/39976484-965fce02-5766-11e8-90c6-203561dafead.png)
![tim 20180514110402](https://user-images.githubusercontent.com/24312839/39976486-96bbbe88-5766-11e8-9807-eb55bcac9bf3.png)

**Comment by afc163** [comment]
感觉是滥用了 Carousel，这种走马灯效果建议自行实现或者直接使用 https://github.com/akiran/react-slick
