### ISSUE TITLE
import 'antd/dist/antd.less'报错，样式无法加载

### ISSUE THREAD

**Issue by wangjianjun0730** [ant-design/ant-design#10485]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
电脑系统版本：macOS High Sierra 10.13.4/浏览器版本：Google Chrome  66.0.3359.139（正式版本）/node v10.1.0 npm:6.0.1

### Reproduction link
[https://github.com/wangjianjun0730/test](https://github.com/wangjianjun0730/test)

### Steps to reproduce
1.使用的脚手架是react-cavalier-cli
2.创建步骤：
2.1:下载脚手架：npm i react-cavalier-cli -g
2.2:创建项目：react-cavalier init <项目名称>
2.3:安装蚂蚁金服组件库：npm install antd babel-plugin-import --save
2.4:项目目录(<项目名称>/src/container/App/index.js)首页导入:
```
import 'antd/dist/antd.less'
import {Table} from 'antd'
.........

render() {

    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo"/>
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <Table dataSource={dataSource} columns={columns}/>
      </div>
    );
  }


```
报下列错误：
```
Failed to compile.

./node_modules/antd/dist/antd.less
Module build failed: 

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in /Users/wangjianjune/test/node_modules/antd/lib/style/color/bezierEasing.less (line 110, column 0)


```

### What is expected?
表格样式能正常加载

### What is actually happening?
不写import 'antd/dist/antd.less'这行代码，数据能展示，但表格线条及样式加载不出来。加了这行代码则js报错，无法正常启动。

---
我是不是少操作了什么？react-cavalier-cli这个脚手架是创建的工程基于`create-react-app` `webpack3.x` `React16.x`搭建而成。所有的打包构建都遵循`webpack3.x`的轻量化原则，支持多端(native，web)输出，并自带serviceWorker（PWA）做纯web端的简单离线处理。可使用`yarn`安装，搭配`Jest`进行单元测试。另外,less和less-loader都用过npm install less less-loader更新到最新。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7927#issuecomment-369099450
