### ISSUE TITLE
Carousel 走马灯组件自动切换长时间停留在当前页面会变成空白的，需要重新刷新页面后才能出来。

### ISSUE THREAD

**Issue by hutxs** [ant-design/ant-design#1048]
**问题描述**

如题

**发生环境**

- antd 版本：0.12.1
- 操作系统及版本：
- 浏览器及版本：
- 在线演示地址：

**重现步骤**

1. ...
2. ...

**线上重现演示**

http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by benjycui** [comment]
Try: 0.12.3

And see: https://github.com/ant-design/ant-design/issues/1009
