### ISSUE TITLE
Expose and document defaultOpen Select prop

### ISSUE THREAD

**Issue by ncknuna** [ant-design/ant-design#10482]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In our product we have a set of filters which, while the user is not interacting with them, act like Tags with a summary of the filter values chosen. When you click them, they open a contextual popup which contains some type of data entry based on the type of filter (e.g. an InputNumber, two InputNumber representing a range, a Select, etc). For the filters which contain a Select, we would like that Select to default to being open.

### What does the proposed API look like?
Right now, we have code that runs at `componentDidMount` to find the rendered Select and call `.click()` on it. 

I just discovered that the underlying rc-select implementation has a way to default a Select to `open` via the `defaultOpen` defaultProp (https://github.com/react-component/select/blob/e2ab65b37b7571e40d7cae71b6d058843b1defe7/src/Select.jsx#L56), however that prop doesn't seem to be part of the `SelectPropTypes` (https://github.com/react-component/select/blob/e2ab65b37b7571e40d7cae71b6d058843b1defe7/src/PropTypes.js#L43) or the public documentation of the Select component (https://ant.design/components/select/), even though it does seem to work when I pass it to my component. 

I would like that prop to be documented (so I know it's stable; I don't want to rely on undocumented features) and added to the official `SelectProps` TypeScript interface (https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L36)

**Comment by 180and170** [comment]
This function does not perform very well in the floating box, and the positioning of the drop-down content is inaccurate
