### ISSUE TITLE
Gap between dropdown and sub-menu closes dropdown

### ISSUE THREAD

**Issue by svanderweyst-cpr** [ant-design/ant-design#10481]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.1

### Environment
mac, Chrome Version 66.0.3359.139

### Reproduction link
[https://ant.design/components/dropdown/#](https://ant.design/components/dropdown/#)

### Steps to reproduce
on the cascading menu example in dropdown,
1) open the cascading menu example
2) hover over sub-menu item
3) cursor towards the opened up sub-menu, but stop between the menu and sub menu

Result: dropdown closes

### What is expected?
that the dropdown menu should not close

### What is actually happening?
the dropdown closes

**Comment by mitchelldemler** [comment]
This happens in the vertical gap as well: 
![dropdowngap](https://user-images.githubusercontent.com/995053/49468039-b0b8fa00-f868-11e8-9b65-1f3ab7731107.gif)
