### ISSUE TITLE
use nuka-carousel instead of slick-carousel

### ISSUE THREAD

**Issue by alirezavalizade** [ant-design/ant-design#10495]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Always when i installing antd's dependencies i seeing that it's installing jquery as a dependency, i got that it's related to slick-carousel so i recommend to use another carousel such as nuka-carousel. I can work on this feature. what's you suggestion?

**Comment by yesmeck** [comment]
Thanks for your suggestion, looks like nuka-carouse not fully compatible with slick-carousel, we may consider your suggestion in next major version.
