### ISSUE TITLE
Table标签在设置了横向滚动后，如果此时没有数据，“暂无数据”提示信息展示在了滚动条的下方。

### ISSUE THREAD

**Issue by clown-helang** [ant-design/ant-design#10490]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table标签在设置了横向滚动后，如果此时没有数据，“暂无数据”提示信息展示在了滚动条的下方。展示效果不太合理。
![image](https://user-images.githubusercontent.com/20653395/39977016-9ce094ac-5769-11e8-8cb0-fd6943e6490f.png)
希望要的效果为，没有数据时，“暂无数据”提示展示在滚动条的上方。

### What does the proposed API look like?
没有数据时，“暂无数据”提示展示在滚动条的上方。
![image](https://user-images.githubusercontent.com/20653395/39977046-cecc0082-5769-11e8-9029-6a286bdba326.png)

**Comment by afc163** [comment]
尝试解决过，很难找到完美的解决方案。

**Comment by clown-helang** [comment]
个人比较浅层的理解
![image](https://user-images.githubusercontent.com/20653395/39977302-9e953350-576b-11e8-8538-156a447c15f0.png)
把提示的 div 放到 ant-table-body 的里面可以展示在上方（不清楚会造成什么深层的影响）

**Comment by clown-helang** [comment]
暂时是在外面的：
![image](https://user-images.githubusercontent.com/20653395/39977361-13ec1344-576c-11e8-8c08-ccd5bf8b9578.png)

**Comment by tianzhich** [comment]
这个问题是不是解决了

**Comment by afc163** [comment]
https://codesandbox.io/s/wizardly-galileo-yf56j

v4 中已经完美解决了。
