### ISSUE TITLE
Select component with search field can't be opened with the keyboard after being opened once

### ISSUE THREAD

**Issue by roryokane** [ant-design/ant-design#10505]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Firefox 60 on Ubuntu Linux 18.04

### Reproduction link
[https://ant.design/components/select/#components-select-demo-search](https://ant.design/components/select/#components-select-demo-search)

### Steps to reproduce
1. Click on the example “Select with search field” to open the menu
2. Use the up and down arrows and the <kbd>Enter</kbd>/<kbd>Return</kbd> key to select a value, e.g. "Lucy"
3. Press <kbd>Enter</kbd>/<kbd>Return</kbd>.

### What is expected?
The [`Select`](https://ant.design/components/select/) should activate by expanding its list of menu items, as it does if you focus the component with the <kbd>Tab</kbd> key and press <kbd>Enter</kbd>.

### What is actually happening?
Nothing happens. The `Select` stays closed, still showing its existing value.

---
After triggering this bug, you have to blur and and refocus the `Select` before you are able to open it again. If you use only the keyboard, you can do this with <kbd>Tab</kbd>, <kbd>Shift</kbd>+<kbd>Tab</kbd>, <kbd>Enter</kbd>.

This sounds similar to https://github.com/ant-design/ant-design/issues/10179 and may be caused by the same underlying issue.

**Comment by mikecanann** [comment]
zhujinxuan, any progress on this?

**Comment by Veveue** [comment]
<kbd>Tab</kbd> 切换到组件  按 <kbd>↑</kbd> <kbd>↓</kbd> 键

**Comment by ajhernandez95** [comment]
Any progress here?

**Comment by zhujinxuan** [comment]
Sorry, I did not had time to do it.

**Comment by afc163** [comment]
Try new Select component in antd v4: https://ant.design/components/select/
