### ISSUE TITLE
Circle shape button borders are not drawn perfectly/sharp

### ISSUE THREAD

**Issue by cemremengu** [ant-design/ant-design#10500]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Windows 10, Chrome Version 66.0.3359.170 (Official Build) (64-bit)

### Reproduction link
[https://ant.design/components/button/](https://ant.design/components/button/)

### Steps to reproduce
Just add:
<Button shape="circle" icon="search" />

### What is expected?
A perfectly sharp circle button border.

### What is actually happening?
If you look carefully you will see that the circle button borders are not sharp (not sure if this is the right term to call). The screen size does not matter but if I zoom in, though, it looks perfect. This only happens for straight circle buttons. For dashed or square buttons there is no problem

Strangely (to me) this does not happen on my friends OS X Mac Book. Everything looks perfect there without zooming or doing anything else.

Attached is a screen shot of what I see: 
![circle](https://user-images.githubusercontent.com/1297759/39994756-dd9d3b6c-5782-11e8-93d2-5508a4157bcd.png)

**Comment by afc163** [comment]
I don't think there is anything we can do about it because it is total brower render issue, welcome to send us PR if you find any solution.
