### ISSUE TITLE
Suggestion: Divider component should have light/dark theme

### ISSUE THREAD

**Issue by jakelauer** [ant-design/ant-design#10504]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.0

### Environment
All

### Reproduction link
[http://not-relevant-to-this.report](http://not-relevant-to-this.report)

### Steps to reproduce
N/A

### What is expected?
Because Divider is really useful in menus, which have a dark theme, it would be great if Divider also had a light/dark theme. Even better would be if the Divider theme would automatically match the surrounding Menu theme.

### What is actually happening?
No theme

**Comment by chenshuai2144** [comment]
You can package it yourself, we don't recommend it.
Divider  should be used for content.
But the designer gave me a color

```
<Divider style={{
       margin:0,
       background:"rgba(255,255,255,.05)"
 }}/>
```

![image](https://user-images.githubusercontent.com/8186664/41278840-799088a8-6e5d-11e8-92ff-57231f6a266d.png)
