### ISSUE TITLE
Select component should support typing to search even when `showSearch` is false

### ISSUE THREAD

**Issue by roryokane** [ant-design/ant-design#10508]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- Parity with features of the [browser-native `<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) (drop-down menu). I have seen this feature in at least Firefox, Chrome, and Safari’s implementations.
- Quick selection of an option within a [Select](https://ant.design/components/select/) when you already know the option's name. For example, choosing a U.S. state from a Select with the keyboard is much faster than having to scroll through a long Select with the mouse.
- Being able to search in a Select that doesn't have the `showSearch` option. It is not desirable to always enable the `showSearch` option because that prevents closing the options list by clicking again on the control, and it makes it harder to read the currently-selected option while the options list is shown.

### What does the proposed API look like?
This would not add a new code API, but rather would change the default behavior of the Select component. For example, the Select in the [“basic usage” example](https://ant.design/components/select/#components-select-demo-basic) would have different behavior.

I am proposing **the same behavior that browsers have** when typing characters while a `<select>` is expanded. The details below are just a description of that behavior.

In the [“basic usage” `Select` example](https://ant.design/components/select/#components-select-demo-basic), if you click to expand the menu you can see “Jack”, “Lucy”, “Disabled” and “yiminghe” as options, with “Lucy” selected. If you press the J key nothing happens. The feature I am talking about would change your selection to “Jack” when you pressed J, as if you had pressed the Up arrow key in this example.

If there were also a “John” option below “Jack”, typing J would select the first match, “Jack”. If you typed “jo” quickly, “John” would be selected. If you slowly typed J then O, it would select whatever option is after the letter O, “yiminghe” in this case.

**Comment by dengfuping** [comment]
@roryokane I don't think `Select` should be totally as same as the `browser-native select`. The operation logic what you proposed is complicated and counter-intuitive. Think about the options like `First Value`, `Second Value` and `Third Value` in the [browser-native select](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select). When you input `value` string, you cannot get all three matched options at the same time.

**Comment by roryokane** [comment]
@dengfuping I still think that this behavior would be an improvement.

> When you input `value` string, you cannot get all three matched options at the same time.

If the user wanted this feature, they would have added the `showSearch` prop to the `Select`. I am only proposing changing the _default_ behavior of `Select`, when `showSearch` is not enabled. With this default behavior, you already cannot search for options and show multiple matches, so my suggestion does not make it worse.

> The operation logic what you proposed is complicated and counter-intuitive.

Perhaps it seems like that when all the details are written out, but it does not feel complicated when I use it. What's more, all major browsers and operating systems already act this way with drop-down menus, so many users should be used to it already.

The current behavior when typing in a `Select` with `showSearch` disabled is that nothing happens. The title of this issue is still relevant: “Select component should support typing to search even when `showSearch` is false”. So no matter which search method is best – the one built into browsers or a different one – adding _any_ functionality would be an improvement over the current behavior.

**Comment by pbrink231** [comment]
I agree with this.

I have a simple select list of 40 users.  In a normal select I could type P and it would bring me to the first P value highlighted.

In the current setup nothing happens so I have to go through the list.  I dont want a full search box, just a quick letter or two and it takes you to that item.   If nothing typed after a delay its the same as an empty search again.  This as said is very normal of any drop down box on most platforms.  Just go to the first item that matches.  As more letters are typed quickly it picks the next best.  If nothing then it stays where it is.  I can pick from there.

**Comment by afc163** [comment]
Maybe https://ant.design/components/auto-complete/ is what you need for.

**Comment by thisissami** [comment]
@afc163 `autocomplete` is not a solution. `autocomplete` forces you to type, instead of giving you a choice.

the suggestion here is to make `Select` work like literally every single `select` on every single website in the world. It completely breaks the keyboard UX to be tabbing through a form and typing in answers, and then to hit `P` to jump to the `p` section of the select... and then be forced to click on the dropdown and handle this by mouse. 

I don't think this issue should have been closed. It would be one thing if this was a novel or unique suggestion - but all that @roryokane is asking is to have the behaviour work identically to how `select`s work everywhere.

**Comment by thisissami** [comment]
@dengfuping that's not how a native select works. what happens is that as soon as you press `v`, it will jump to the first option that starts with a `v`. In your example, of `First Value`, `Second Value`, and `Third Value` - nothing will happen, because none of them start with a `v`. You must type `F`, `S`, or `T` for anything to happen.

**Comment by lucis** [comment]
+1 here.

@afc163 could you reconsider opening this issue?

**Comment by asgoel** [comment]
+1 here. Maybe a more common example would be if I am entering an address and want to input my state. It's pretty common to start typing the first letter of the state and have it scroll to the state (i.e if I start typing "C" it would go to California without filtering results). @afc163 thoughts @thisissami thoughts?

**Comment by mohandast52** [comment]
![select_gif](https://user-images.githubusercontent.com/22061815/106120213-1b7dcb80-617c-11eb-8c3b-2d47fcfa732a.gif)

I'm able to select different values while typing 1st character "without opening select". Users are used to this native feature.

**Comment by mloop1** [comment]
has this been implemented now?
