### ISSUE TITLE
服务端渲染按需引入 antd 报错

### ISSUE THREAD

**Issue by declanlc** [ant-design/ant-design#10503]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Node

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new](https://github.com/ant-design/ant-design/issues/new)

### Steps to reproduce
node   express 搭建的服务器环境，  [ 'import', { libraryName: 'antd', libraryDirectory: 'lib', style: true } ] 配置后，启动服务器，打开网页报错：
\node_modules\antd\lib\style\index.less:1
(function (exports, require, module, __filename, __dirname) { @import "./themes/default";

### What is expected?
正常显示 Button 样式

### What is actually happening?
\node_modules\antd\lib\style\index.less:1
(function (exports, require, module, __filename, __dirname) { @import "./themes/default";

**Comment by lzr900515** [comment]
require('babel-register');
require.extensions['.less'] = () => {};  // very important for ssr to avoid this error
require('./server');

@declanlc

**Comment by albafica2015** [comment]
@lzr900515 你好，你说说清楚点吗？antd怎么配置服务端渲染？

**Comment by lzr900515** [comment]
若果.babelrc配置 ["import", { "libraryName": "antd", "style": true }] 使用less文件，导致ssr报错，在入口文件添加require.extensions['.less'] = () => {};试下。 ["import", { "libraryName": "antd", "style": 'css' }]或者直接使用css

**Comment by uedkx** [comment]
@lzr900515 这个问题你解决了吗？

**Comment by declanlc** [comment]
已经解决

declanlc&163

uedkx <notifications@github.com>编写：

**Comment by sukechris** [comment]
@declanlc 请问这个问题你是如何解决的

**Comment by zhaoyuanfeng** [comment]
> 若果.babelrc配置 ["import", { "libraryName": "antd", "style": true }] 使用less文件，导致ssr报错，在入口文件添加require.extensions['.less'] = () => {};试下。 ["import", { "libraryName": "antd", "style": 'css' }]或者直接使用css
> @albafica2015

非常感谢，折腾了好久，虽然不明白原理，能解决就好

**Comment by Shurlormes** [comment]
> > 若果.babelrc配置 ["import", { "libraryName": "antd", "style": true }] 使用less文件，导致ssr报错，在入口文件添加require.extensions['.less'] = () => {};试下。 ["import", { "libraryName": "antd", "style": 'css' }]或者直接使用css
> > @albafica2015
> 
> 非常感谢，折腾了好久，虽然不明白原理，能解决就好

能请教下怎么弄的吗？我还是报错
```
(function (exports, require, module, __filename, __dirname) { import '../../style/index.less'; // style dependencies
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected string
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
```

**Comment by daweilv** [comment]
贴一下我的解决方案

```
// babel.config.js  只在 client 侧构建的时候启用 import 插件。
!server && [
    'import',
    {
        libraryName: 'antd',
        style: true,
    },
],
```

```
// webpack.config.server.js  server 侧构建忽略css等其他静态资源
{
    test: /\.(less|css)$/,
    loader: 'ignore-loader'
},
{
    test: /\.(woff|woff2|eot|otf|webp|ttf)$/i,
    loader: 'ignore-loader',
},
{
    test: /\.(png|jpg|jpeg|gif|mp3|svg)$/i,
    loader: 'ignore-loader',
},
```

完整例子在 [react-isomorphic-boilerplate](https://github.com/daweilv/react-isomorphic-boilerplate)

**Comment by astonishqft** [comment]
> > > 若果.babelrc配置 ["import", { "libraryName": "antd", "style": true }] 使用less文件，导致ssr报错，在入口文件添加require.extensions['.less'] = () => {};试下。 ["import", { "libraryName": "antd", "style": 'css' }]或者直接使用css
> > > @albafica2015
> > 
> > 
> > 非常感谢，折腾了好久，虽然不明白原理，能解决就好
> 
> @zhaoyuanfeng 能请教下怎么弄的吗？我还是报错
> 
> ```
> (function (exports, require, module, __filename, __dirname) { import '../../style/index.less'; // style dependencies
>                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
> 
> SyntaxError: Unexpected string
>     at new Script (vm.js:79:7)
>     at createScript (vm.js:251:10)
>     at Object.runInThisContext (vm.js:303:10)
>     at Module._compile (internal/modules/cjs/loader.js:657:28)
> ```
> 
> .babel文件:
> 
> ```
> {
> 	"presets": ["@babel/preset-env", "@babel/preset-react"],
> 	"plugins": [
> 		"@babel/plugin-proposal-object-rest-spread",
> 		"@babel/plugin-transform-runtime",
> 		[
> 			"import",
> 			{
> 				"libraryName": "antd",
> 				"libraryDirectory": "es",
> 				"style": true
> 			}
> 		]
> 	]
> }
> ```
> 
> 入口文件
> 
> ```
> var fs = require('fs');
> var babelConfig = JSON.parse(fs.readFileSync('./.babelrc'));
> require('@babel/register')(babelConfig);
> require.extensions['.less'] = () => {};
> require('./express.js');
> ```

你的问题解决了吗？我也遇到同样的问题

**Comment by Jeff-Tian** [comment]
> 你的问题解决了吗？我也遇到同样的问题

如果是 babel 里配置了如下设置：

```
...
[
            "import",
            {
                "libraryName": "antd",
                "libraryDirectory": "es",
                "style": "css"
            },
            "antd"
        ],
        [
            "import",
            {
                "libraryName": "antd-mobile"
            },
            "antd-mobile"
        ]
...
```

去掉即能消除错误。但如果仅仅在某个条件下需要去掉，而另外的条件下需要保留，那么可以通过设置环境变量判断是否需要相关设置。比如

```
"plugins": [...].concat(process.env.NODE_ENV==='unittest' ? []: [[
            "import",
            {
                "libraryName": "antd",
                "libraryDirectory": "es",
                "style": "css"
            },
            "antd"
        ],
        [
            "import",
            {
                "libraryName": "antd-mobile"
            },
            "antd-mobile"
        ]])
```

注意，如果你的 `babel` 配置是放在 `.babelrc` 文件里，要些判断条件，就需要先将 `.babelrc` 重命名为 `babel.config.js`，然后

```
module.exports = {...原来的 .babelrc 内容...}
```

**Comment by zhangyuang** [comment]
https://github.com/ykfe/ssr/blob/dev/packages/plugin-react/src/config/server.ts#L62

不知道怎么配置的，参考这个配置。或者给该框架提issue
