### ISSUE TITLE
FilterDropDown and filterIcon no render when I wrap Table within customized columns props

### ISSUE THREAD

**Issue by Irislm** [ant-design/ant-design#10519]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Chrome 66.0.3359.139

### Reproduction link
[https://github.com/Irislm/antd-demo](https://github.com/Irislm/antd-demo)

### Steps to reproduce
1、Run app: npm start
2、No render filterIcon in Column '姓名'
3、Click Column '姓名' header cell, no render filterDropDown

### What is expected?
Render filterIcon and filterDropDown, or give a wrong message if something is wrong

### What is actually happening?
No render filterIcon and no render filterDropDown,  no wrong message.

---
I need a common Table Component with customized filterDropDown and user interaction.  So the others just need to use customized props which can build a search filterDropDown.

**Comment by yesmeck** [comment]
```diff
- filterDropDown: <SearchDropDown onSearch={col.onSearch} />,
+ filterDropdown: <SearchDropDown onSearch={col.onSearch} />,
```

**Comment by Irislm** [comment]
@yesmeck what's wrong with this?  Thanks !

**Comment by yesmeck** [comment]
`filterDropdown` 

`down`的 `d` 是小写。

**Comment by Irislm** [comment]
@yesmeck  oh... thanks !
