### ISSUE TITLE
Why is "private textAreaRef;"

### ISSUE THREAD

**Issue by tuduong2** [ant-design/ant-design#10527]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I found private textAreaRef; in antd/lib/input/TextArea.d.ts Line 24
So why is it private?

I need to get some information from textarea and set  value ti it such as
this.$textarea.textAreaRef
this.$textarea.textAreaRef.selectionStart
this.$textarea.textAreaRef.selectionEnd
obj.setRangeText(text);

 <TextArea placeholder={placeholder}
                    ref={ref => (this.$textarea = ref)}
                    className="app-postform-input"
                    onFocus={this.handleFocus}
                    onChange={this.handleChange}
                    value={content}
                    autosize />

### What does the proposed API look like?
 Public textAreaRef

**Comment by yesmeck** [comment]
`textAreaRef` is not a public API, It may change any time.

**Comment by yesmeck** [comment]
Try `ReactDOM.findDOMNode(this.$textarea).quertSelector('input')`.

**Comment by ManAnRuck** [comment]
why textAreaRef ref should not be public? It would be very helpful in some cases.
