### ISSUE TITLE
click search icon is invalid on Input.Search Component

### ISSUE THREAD

**Issue by NameIsEward** [ant-design/ant-design#10529]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
os: mac     browser: chrome@66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n7nrkvqv5m)

### Steps to reproduce
.

### What is expected?
onSearch can invoke by click search Icon

### What is actually happening?
click search icon is invalid on Input.Search Component

---
the document tell us the onSearch function of Input.Search's search Icon can click, but it can't actually;

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8445

**Comment by NameIsEward** [comment]
@afc163  i think most of people prefer to click search Icon rather than press Enter;   and click search icon is antd2's  default action
