### ISSUE TITLE
Pagination issue.

### ISSUE THREAD

**Issue by cyyyu** [ant-design/ant-design#10524]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
macos latest, chrome latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n985r2l9k0)

### Steps to reproduce
check out the link.

![image](https://user-images.githubusercontent.com/15100664/40096854-7ce0484e-5905-11e8-9473-628195394827.png)

### What is expected?
'current' in 'onShowSizeChange' should be the same value as 'current' prop.

### What is actually happening?
Once 'total' is 0, 'current' in 'onShowSizeChange' is 0, which is not correct.

**Comment by cyyyu** [comment]
I feel like the root cause supposes to be here: https://github.com/react-component/pagination/blob/0c034f12d8c188cae3e8f14e32aef85cd23e6dcc/src/Pagination.jsx#L189

**Comment by afc163** [comment]
PR is welcome~

**Comment by wmzhong** [comment]
@afc163 I have pull a PR to the **react-component/pagination** repository.

Here's the link for the PR.
https://github.com/react-component/pagination/pull/133

Please have a check, thanks.

**Comment by yesmeck** [comment]
`rc-pagination@1.16.4`
