### ISSUE TITLE
Upload: The easiest way to rename the uploading file.

### ISSUE THREAD

**Issue by imakou** [ant-design/ant-design#10521]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The current ```Upload``` component does not support rename the uploading file.
It seems that the component takes the API – ```name``` then grab ```filename``` and upload to the server.
Is there any way to rename ```filename``` then upload to server?

### What does the proposed API look like?
```<Upload reName={this.handleRename} />```

**Comment by yesmeck** [comment]
You can rename the access file and rename it in `data` callback.

**Comment by yesmeck** [comment]
<Upload data={(file) => file.name = 'foo'} />

**Comment by bgold0** [comment]
> <Upload data={(file) => file.name = 'foo'} />

It is a read only property you can't do this

**Comment by zhangzs000** [comment]
how to change name? If the names are the same, the file will be overwritten

**Comment by zhangzs000** [comment]
i think can change a attribute name, such as filename

**Comment by enkil2003** [comment]
Hi, So is there anyway of doing this?
given that ```<Upload data={(file) => file.name = 'foo'} />``` wont work because of read only property name?

**Comment by cbsanal** [comment]
Hi, you can achive this by using customRequest, for example (replace all the spaces with - in file name):
```
const uploadImage = async (options) => {
  // below file element is the file you uploaded
  const { onSuccess, onError, file, onProgress } = options;
  const fmData = new FormData();
  const config = {
  headers: { 'content-type': 'multipart/form-data'},
  onUploadProgress: (event) => {
      onProgress({ percent: (event.loaded / event.total) * 100 });
    },
  };
  // create copy file and change the name when it is appending to data
  let data = new FormData();
  data.append('file', file, file.name.replaceAll(' ', "-" )); // replace all the spaces in the file name with -
  let _file = data.get('file');
  fmData.append('image', _file);
  try {
    // then send the copy file to the server
    const res = await axios.post(`url`, fmData, config);
    onSuccess('Ok');
  } catch (err) {
    onError({ err });
  }
};

<Upload
    // action="url"
    customRequest={uploadImage}
    listType="picture-card"
    fileList={fileList}
    onPreview={this.handlePreview}
    onChange={this.handleChange}
    >
    {fileList.length >= 8 ? null : uploadButton}
</Upload>
```

**Comment by huccct** [comment]
I had the same problem, and this is how I solved it.
```
<Upload
  maxCount={1}
  action={...}
  beforeUpload={handleBeforeUpload}
  multiple={false}
  onChange={...}
>
  <Button icon={<UploadOutlined />}>Upload Image</Button>
</Upload>;
```
```
const handleBeforeUpload = (file: RcFile) => {
  // custom rename file name
  const newName = generateFileName(file.name)
  // replace origin File
  const newFile = new File([file], newName, { type: file.type })
  return newFile
}

const generateFileName = (originalName: string) => {
  const uuid = uuidv4()
  const extension = originalName.split('.').pop()
  return `${uuid}.${extension}`
}
```

**Comment by ronaldsalili1** [comment]
> I had the same problem, and this is how I solved it.
> 
> ```
> <Upload
>   maxCount={1}
>   action={...}
>   beforeUpload={handleBeforeUpload}
>   multiple={false}
>   onChange={...}
> >
>   <Button icon={<UploadOutlined />}>Upload Image</Button>
> </Upload>;
> ```
> 
> ```
> const handleBeforeUpload = (file: RcFile) => {
>   // custom rename file name
>   const newName = generateFileName(file.name)
>   // replace origin File
>   const newFile = new File([file], newName, { type: file.type })
>   return newFile
> }
> 
> const generateFileName = (originalName: string) => {
>   const uuid = uuidv4()
>   const extension = originalName.split('.').pop()
>   return `${uuid}.${extension}`
> }
> ```

You're a life saver. Thank you for this!

**Comment by choijiho0021** [comment]
> 나도 똑같은 문제가 있었는데, 다음과 같은 방법으로 문제를 해결했습니다.
> 
> ```
> <Upload
>   maxCount={1}
>   action={...}
>   beforeUpload={handleBeforeUpload}
>   multiple={false}
>   onChange={...}
> >
>   <Button icon={<UploadOutlined />}>Upload Image</Button>
> </Upload>;
> ```
> 
> ```
> const handleBeforeUpload = (file: RcFile) => {
>   // custom rename file name
>   const newName = generateFileName(file.name)
>   // replace origin File
>   const newFile = new File([file], newName, { type: file.type })
>   return newFile
> }
> 
> const generateFileName = (originalName: string) => {
>   const uuid = uuidv4()
>   const extension = originalName.split('.').pop()
>   return `${uuid}.${extension}`
> }
> ```

you save my day thank you
