### ISSUE TITLE
eslint-plugin-react和eslint-config-airbnb版本依赖的问题

### ISSUE THREAD

**Issue by zhaotai** [ant-design/ant-design#1052]
## What`s wrong

当我clone下ant-design工程并在命令行敲击 `npm install` 时，出现了以下错误：
```
npm ERR! peerinvalid The package eslint-plugin-react@3.16.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@6.0.1 wants eslint-plugin-react@^4.0.0
```
安装的`eslint-config-airbnb`要求的`eslint-plugin-react`依赖版本是4.0.0+，但实际上安装的却是3.16.1

## What should happened

`eslint-config-airbnb`是一个es style的插件，它在2016年2月21日更新了版本，由5.0+跳到了6.0+，这本来不应该影响该工程；

## What actually happened

但实际上影响了，显而易见。无法安装成功。

## Why this happened

package.json内容的devDependencies中存在以下两行：
```
"devDependencies": {
    "eslint-config-airbnb": "latest",
    "eslint-plugin-react": "^3.3.1"
}
```
可以看到，安装的最新`eslint-config-airbnb`版本为6.0.1，其依赖的`eslint-plugin-react`版本为4.0.0+，但devDependencies中的`eslint-plugin-react`版本大于等于3.3.1，小于4.0.0，因为出现了依赖问题。

## How to solve this problem

将`eslint-config-airbnb`的版本改成一个固定的大版本，如`^5.0.0`或者其他对`eslint-plugin-react`版本依赖满足要求的版本。
即 
```
"devDependencies": {
    "eslint-config-airbnb": "^5.0.0"
}
```
然后再次 `npm install`, bingo~!

## Then what`s my question

写latest绝对是错的，因为这样有版本依赖的问题。那么应该是5.0.0还是4.0.0或者应该是x.x.x。
ant-design团队在写的时候用的是什么版本呢？或者说正确的应该是哪个版本呢？

## Environment Information

- os： OS X EI Capitan Version 10.11.2
- node v4.3.0
- npm 2.14.12

**Comment by afc163** [comment]
```
$ git pull origin master
```

https://github.com/ant-design/ant-design/pull/1049/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R90
