### ISSUE TITLE
Normal Modal without cross in the title bar

### ISSUE THREAD

**Issue by leizhangcnnz** [ant-design/ant-design#10522]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Could we please provide a modal type that won't show the cross in the title bar when the modal already has OK or Cancel footer button?

The cross in the title bar is duplicate when it already has the button footer, and we also have to add more code for it.

### What does the proposed API look like?
New type modal could have an option that doesn't show the cross button.

**Comment by leizhangcnnz** [comment]
Just like customising footer, can we also customise the title bar please?

I know the info, warning and error modal don't have that cross but they also don't have the title bar. I need the title bar.

**Comment by dengfuping** [comment]
@leizhangcnnz You could set `closable={false}`.
