### ISSUE TITLE
TreeSelect 搜索 ： 搜索的是treenode的value 为什么不是搜treenode的title呢 ，个人觉得更有意义

### ISSUE THREAD

**Issue by zzwar2009** [ant-design/ant-design#10535]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望能支持treeselect 搜索treenode 的  title

### What does the proposed API look like?
 至少提供配置可选择搜value

**Comment by zzwar2009** [comment]
我理解用户用的时候是关注的title,也不可能有人记得住value是什么啊,会增加搜title这个需求吗 [](url)
![image](https://user-images.githubusercontent.com/2322990/40107603-47df0dd0-592b-11e8-84c4-9498150f0c37.png)
![image](https://user-images.githubusercontent.com/2322990/40107611-4c650224-592b-11e8-9f41-315c176faa71.png)
![image](https://user-images.githubusercontent.com/2322990/40107615-4ed1842e-592b-11e8-9e44-f796a1f7fcaa.png)

**Comment by yesmeck** [comment]
你可以使用 `filterTreeNode` 自定义搜索逻辑。

**Comment by chenxiaochun** [comment]
是可以自定义搜索逻辑。但个人觉得默认就应该搜索 title 啊，所以，设计成默认搜索 value 是基于什么考虑的呢？😳

**Comment by yesmeck** [comment]
`value` 是 `string` 方便搜索，`title` 的类型不可预期。
