### ISSUE TITLE
create-react-app config typescript but error “is not sorted alphabetically”

### ISSUE THREAD

**Issue by mazhiwen** [ant-design/ant-design#10533]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
mac chrome react

### Reproduction link
[https://github.com/mazhiwen/antd-demo-ts](https://github.com/mazhiwen/antd-demo-ts)

### Steps to reproduce
git链接是按照antd官网 http://ant.design/docs/react/use-in-typescript-cn 此页面生成的项目，
config-overrides.js：
tsLoader.options = {
      getCustomTransformers: () => ({
        before: [ tsImportPluginFactory({
          libraryName: 'antd',
          libraryDirectory: 'es', //this line get error
          style: 'css',
        }) ]
      })
    };

tslint 已经设置ordered-imports 为false。
start项目，报错：config-overrides.js
(22,11): The key 'libraryDirectory' is not sorted alphabetically

### What is expected?
正常start

### What is actually happening?
报错config-overrides.js
(22,11): The key 'libraryDirectory' is not sorted alphabetically

**Comment by yesmeck** [comment]
交换下 libraryName  和 libraryDirectory 的位置。

**Comment by mazhiwen** [comment]
@yesmeck  所以为什么要这么改，是tslint报错的吗？我改了tslint的object-literal-sort-keys值也没用

**Comment by yesmeck** [comment]
可以把 `onfig-overrides.js` 忽略掉。
