### ISSUE TITLE
Form.Item label在小于575px时，冒号消失，after就没有了，影响布局

### ISSUE THREAD

**Issue by xiaoyierle** [ant-design/ant-design#10547]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Form.Item label在小于575px时，冒号消失，after就没有了，影像效果，在手机端查看时会变形

### What does the proposed API look like?
let style = {
            labelCol: {span:8},
            wrapperCol: {span: 14}
        };
        let col_style={
            xs: 8,
            sm: 8,
            md: 12,
            lg: 12,
            xl: 12,
            xxl: 8
        }
在小屏下不影响样式

**Comment by afc163** [comment]
If you are reporting a but instead of featrue request, you should use bug-report template.
