### ISSUE TITLE
Backfill in autocomplete does not apply filter

### ISSUE THREAD

**Issue by Bosco28** [ant-design/ant-design#10543]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Chrome Version 66.0.3359.139

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://l7o3z2vo6l.codesandbox.io/)

### Steps to reproduce
1. create autocomplete with props backfill={true}, a filterOption and a datasource
2. run code and type something
3. use down button on keyboard to select an item
4. the input is backfilled

### What is expected?
the dropdown menu should be updated with filter being applied to the newly selected input

### What is actually happening?
the dropdown menu is showing all the items in datasource

**Comment by yesmeck** [comment]
I think this behavior is correct. There are two types of value in `AutoComplete`, `inputValue` which used to filter options, `value` which is the value of the `AutoComplete`. What we `backfill` is the `value`, so the filter function won't be applied.
