### ISSUE TITLE
input-number does not respect wrapperCol

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1054]
```
<Form.Item
 label = { formatMessage(messages.iconOrder) }
 labelCol={{ span: 12 }}
 wrapperCol={{ span: 12 }}
>
 <InputNumber defaultValue={0}/>
</Form.Item>
```

Not matter what wrapperCal is - input for number is still same width. At least looks like it has 'min-width'. Everything is ok with common inputs.

```
wrapperCol={{ span: 12 }}
```
https://www.dropbox.com/s/4mfxx3nzf2lbqlu/Screenshot%202016-02-22%2013.02.25.png?dl=0
```
wrapperCol={{ span: 8 }}
```
https://www.dropbox.com/s/951m9avtixgtbo7/Screenshot%202016-02-22%2013.03.00.png?dl=0
```
wrapperCol={{ span: 5 }}
```
https://www.dropbox.com/s/1derji2jnqt5ezm/Screenshot%202016-02-22%2013.03.23.png?dl=0

But! Supposed that input-number is control that will be used only for number, so it will not require a lot of space in most cases to enter number - e.g. 5,10,100,1000 - only 1-5 symbol. Even 100000 is only 6 symbol. I really would like to be able to use much smaller width of that input for small numbers.

**Comment by afc163** [comment]
The `InputNumber` component has initial width, you can try:

```jsx
<InputNumber style={{ width: '100%' }} />
```

**Comment by plandem** [comment]
i just wanted to inform you, that behaviour for normal input and input-number is different :) first one is respecting wrapperCol and last one is not.
