### ISSUE TITLE
react ant design Tabs.TabPane 如何隐藏

### ISSUE THREAD

**Issue by ariesjian** [ant-design/ant-design#10558]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们现在有这样一样系统，不同角色看到的不同的页签，或者是满足指定需求后隐藏标签页，目前好像没有隐藏功能

### What does the proposed API look like?
        <TabPane hiddenTabPhone={true}  
             tab={<span><Icon type="home"/>PM</span>} 
             key="three"
         >
                            //此处省略。。。
                            </TabPane>

类似于 hiddenTabPhone={true} 就可以隐藏这个标签页了

**Comment by afc163** [comment]
```
<Tabs>
  <Pane />
  <Pane />
  {this.state.hideTab && <Pane />}
</Tabs>
```
