### ISSUE TITLE
Menu defaultOpenKeys Not working on Re-render

### ISSUE THREAD

**Issue by mani541** [ant-design/ant-design#10556]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
React version

### Reproduction link
[https://mordorintelligence.com](https://mordorintelligence.com)

### Steps to reproduce
Default openKeys not working on re-rendering the Menu section.
Default Open keys are working fine on load with the sub menu keys.
After re-rendering the default openkeys are not working and not opening the Sub menu.

### What is expected?
After re-render also, the default sub menu should be opened.

### What is actually happening?
After re-render also, the default sub menu should be opened, which is not opening on re-render which should happen

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically

**Comment by jamesjianpeng** [comment]
我的 openKeys 也不生效
