### ISSUE TITLE
在modal（页面过长）里写AutoComplete，在滚动时会使AutoComplete的下拉框出现错位

### ISSUE THREAD

**Issue by Rocky1073** [ant-design/ant-design#10557]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.3

### Environment
chrome 65.0.3325.181

### Reproduction link
[https://github.com/Rocky1073/AutoComplete.git](https://github.com/Rocky1073/AutoComplete.git)

### Steps to reproduce
首先要页面过长，然后只要把AutoComplete组件包在Modal组件里就会出现这个问题

### What is expected?
鼠标滚动条上下滚动时AutoComplete组件的下拉框不要跟着动

### What is actually happening?
鼠标滚动条上下滚动时AutoComplete组件的下拉框会跟着动

---
<AutoComplete dataSource={dataSource}>
总之不包在<Modal>组件里就不存在问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#select-dropdown-datepicker-timepicker-popover-popconfirm-will-scroll-with-page

#3438

#3487

**Comment by Huanghuiying0624** [comment]
AutoComplete do not have getXxxxContainer props so the misplace problem cannot be fixed in TypeScript

**Comment by Huanghuiying0624** [comment]
@afc163

**Comment by afc163** [comment]
@Huanghuiying0624 PR welcome

**Comment by fuhaichao122** [comment]
> @afc163 #11690 please check it. thanks a lot

Hello, how can I solve this problem? no getXxxxContainer props

**Comment by Huanghuiying0624** [comment]
@fuhaichao122  
https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L34
