### ISSUE TITLE
move hardcoded messages to separate files

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1055]
It would be better if you will move all i18n related text into separate files, i.e. popconfirm has buttons that by default in chinese.

Of course i can set via okText, cancelText, but right now i have to do it each time. It would be better to use locale file, like for calendar/pagination and etc.

**Comment by benjycui** [comment]
How about this:

```jsx
const locale = {
  okText: 'Yes',
  calcelText: 'No',
};

<Popconfirm {...locale} title="Are you sure?">
  <a href="#">Delete</a>
</Popconfirm>
```

This is as convenient as `locale` property.

**Comment by benjycui** [comment]
Added in Cookbook, see: https://github.com/ant-design/ant-design/wiki/Cookbook#re-use-locale-config-for-popconfirm-modal-etc

**Comment by plandem** [comment]
yep, of course we can use it, but my point that if you are not using chinese language, than you don't have default locales and always must override it :(

I.e.: for chinese i would use only this:
```
Popconfirm title="Are you sure?">
  <a href="#">Delete</a>
</Popconfirm>
```
but for any other language everywhere i must use something like this:
```
import { popLocale } from '../locale';
...
Popconfirm {...popLocale} title="Are you sure?">
  <a href="#">Delete</a>
</Popconfirm>
```

See the difference? Behaviour is not same for other language.

**Comment by benjycui** [comment]
Yep, it's inconvenient for other language. Maybe feature? @afc163

**Comment by afc163** [comment]
搞一个统一的 local 目录好了。

**Comment by plandem** [comment]
how to use 'antd/locale/*' for it?

**Comment by afc163** [comment]
We plan to do it in `1.0.0`.

**Comment by afc163** [comment]
Components need locale:

- Calendar
- DatePicker
- TimePicker
- Pagination
- Table
- Popconfirm
- Modal

**Comment by plandem** [comment]
i can create RU locale. but probably better to wait for stable version of that idea :)

**Comment by afc163** [comment]
After finishing `LocalProvider` component, you can create a separate locale file for all components.

**Comment by plandem** [comment]
when LocaleProvider will be released? I want to migrate to new locale system :)

**Comment by afc163** [comment]
Maybe next week we can release a preview edition 1.x.

**Comment by afc163** [comment]
Since `antd@1.0.0-beta` has `LocaleProvider`, maybe @plandem can try on it and supply a Russian locale.

**Comment by plandem** [comment]
ok, i can try, but what about react 15? is it supported now? i saw issue in chinese about react 15, that's why i didn't tried beta of antd yet.

**Comment by afc163** [comment]
try `npm install antd@beta`.

https://github.com/ant-design/ant-design/blob/develop-1.0.0/components/locale-provider/index.md

**Comment by afc163** [comment]
react@15 is compatible now, we still have some warning consoles to fix.
