### ISSUE TITLE
Modal: prefixCls not passed to Button

### ISSUE THREAD

**Issue by skidrowe** [ant-design/ant-design#10565]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Windows 10 x64, Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/718x8q9kx)

### Steps to reproduce
1. import Modal component on demand
`import Modal from 'antd/lib/modal' `
1. do NOT `import 'antd/dist/antd.css'`
1. Pass a custom prefixCls to the Modal component

<Modal prefixCls="custom-modal" title='title' visible />

### What is expected?
prefixCls should be passed to Button component so that if one chooses not to use ant design styles and provide their own, they can use the custom prefixCls to style the button as well, without the need of using antd default prefixCls

### What is actually happening?
Modal: prefixCls not passed to Button

**Comment by viral810** [comment]
@skidrowe Make sure you do not have `href` tag to `Button`

**Comment by afc163** [comment]
- [ ] Modal
- [ ] Transfer

Could U help us to resolve these? @skidrowe

**Comment by yesmeck** [comment]
#10855
