### ISSUE TITLE
InputNumber border disappears when zoom level below 90%

### ISSUE THREAD

**Issue by timataran** [ant-design/ant-design#10562]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Ubuntu 16.04, Google Chrome  66.0.3359.170, Firefox Quantum 60.0

### Reproduction link
[Example at codesandbox](https://codesandbox.io/s/rym1mwr0k4)
[And it can be reproduced on library homepage](https://ant.design/components/input-number/)

### Steps to reproduce
1. Ensure that zoom level is set to 100%
2. Press repeatedly "Ctrl"   "-" to decrease zoom level and watch how InputNumber borders are changing

### What is expected?
Expected that InputNumber has border on every side on all zoom levels

### What is actually happening?
On zoom level below 90% component border not always fully shown.

**Comment by ferociousfox** [comment]
I can attest to this problem occurring. I am currently on a development team building a large app and we are using antd. I have used InputNumber in several places and this is always the case when I zoom out.
