### ISSUE TITLE
TreeSelect的TreeNode使用ReactNode作为title属性时，鼠标移到选择器上时title会显示为[object Object]

### ISSUE THREAD

**Issue by dislido** [ant-design/ant-design#10561]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
windows 10(x64), chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xjop5k8r5w)

### Steps to reproduce
使用ReactNode类型的值作为TreeSelect.TreeNode的title属性，选择后鼠标移动到TreeSelect上，显示的title会变成[object Object]

### What is expected?
显示的title能够使用该ReactNode的title属性

### What is actually happening?
即使设置了这个ReactNode的title属性，文字周围依然有一部分区域title显示为[object Object]
![image](https://user-images.githubusercontent.com/25094788/40167899-c80e891c-59f4-11e8-9f8b-49f3ac2b62be.png)

**Comment by zombieJ** [comment]
`Select` 组件中 `Option` 可以定义 `title` 属性，但是 `TreeSelect` 里 `title` 被占用了。
现在 `TreeSelect` 通过 `treeData` 和 `children` 创建树一个用的是 `label`，一个是 `title`。
感觉应该统一一下，统一用 `label` 然后把 `title` 放出来。这样行为就和 `Select` 组件一致了。

相关 issue：https://github.com/ant-design/ant-design/issues/9879

**Comment by afc163** [comment]
没必要改，简单的解决方案是 Tree 里面判断一下，类型不是 string 就不设置。

**Comment by zombieJ** [comment]
我觉得默认做 string 判断，但是用户如果需要也可以自己控制会更好些。

**Comment by zombieJ** [comment]
Fixed in `rc-tree-select 1.12.13`.
API 调整等 `rc-tree-select` 重构完后再说。

**Comment by zombieJ** [comment]
PS: Also fixed in `rc-select 8.0.9`

ref: https://github.com/react-component/select/commit/e5659350629dcdb9e5bcf857c333d1bf20e6470b
