### ISSUE TITLE
Transfer: prefixCls not passed to Button and Checkbox

### ISSUE THREAD

**Issue by skidrowe** [ant-design/ant-design#10567]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Windows 10 x64, Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/88wy7qwm2j)

### Steps to reproduce
1. import Transfer component on demand
`import Transfer from 'antd/lib/transfer' `
1. do NOT `import 'antd/dist/antd.css'`
1. Pass a custom prefixCls to the Transfer component

### What is expected?
prefixCls should be passed to Button and Checkbox components so that if one chooses not to use ant design styles and provide their own, they can use the custom prefixCls to style the button and checkbox as well, without the need of using antd default prefixCls

### What is actually happening?
Transfer: prefixCls not passed to Button or Checkbox

**Comment by afc163** [comment]
Merged to #10565
