### ISSUE TITLE
the head of table will misalignment after use scroll y

### ISSUE THREAD

**Issue by Ai01** [ant-design/ant-design#10572]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
latest chrome

### Reproduction link
[https://codepen.io/Ai01/pen/odQVLB](https://codepen.io/Ai01/pen/odQVLB)

### Steps to reproduce
you can find this bug in the example has been given

### What is expected?
the head of the table alignment with the body

### What is actually happening?
the head of table will misalignment after use scroll y
![image](https://user-images.githubusercontent.com/18245929/40228056-cb33fd7e-5ac2-11e8-98ac-ba9c3ef0c2e1.png)

**Comment by afc163** [comment]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/507615/40230858-b441c110-5acb-11e8-99dc-9a08eeddce96.png">

https://ant.design/components/table-cn/#components-table-demo-fixed-header
