### ISSUE TITLE
antd less module build failed with typings-for-css-modules-loader

### ISSUE THREAD

**Issue by zhaoyu69** [ant-design/ant-design#10571]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
win10

### Reproduction link
[https://github.com/zhaoyu69/react-cnode](https://github.com/zhaoyu69/react-cnode)

### Steps to reproduce
[https://user-images.githubusercontent.com/23548734/40184819-bf083cbc-5a23-11e8-9502-451ec80adef1.png](https://user-images.githubusercontent.com/23548734/40184819-bf083cbc-5a23-11e8-9502-451ec80adef1.png)

### What is expected?
fix this error

### What is actually happening?
no idea

---
thanks a lot

**Comment by Ehesp** [comment]
I think this is a known issue with less v3. Try installing a `less` version of `^2.*.*` like `"less": "^2.7.3"`.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7927#issuecomment-372513256

**Comment by zhaoyu69** [comment]
@Ehesp i try installing less@2.7.3, fixed this error, but have a new error.

![_20180518220429](https://user-images.githubusercontent.com/23548734/40239109-af95bb0a-5ae7-11e8-9e1a-6d5950169ec9.png)

**Comment by zhaoyu69** [comment]
@afc163 I tried it but not work. it may works for less-loader, but i use typings-for-css-modules-loader, i don't know how to set its options.
```
//webpack.config.js
{
                test: /\.less/,
                use: [
                    'style-loader',
                    'typings-for-css-modules-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]&namedExport&camelCase&less!less-loader'
                ]
            },
```

**Comment by zhaoyu69** [comment]
error demo: [https://github.com/zhaoyu69/react-cnode](https://github.com/zhaoyu69/react-cnode)
