### ISSUE TITLE
Automplete with delay option

### ISSUE THREAD

**Issue by ulima69** [ant-design/ant-design#10578]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Autocomplete searches for every letter typed, this cause many requests. With a delay option the request will be done after setted milliseconds delay.

### What does the proposed API look like?
delay={this.state.delay}

**Comment by afc163** [comment]
You can follow this example: https://ant.design/components/select/#components-select-demo-select-users
