### ISSUE TITLE
Select选择器

### ISSUE THREAD

**Issue by tangli1** [ant-design/ant-design#10573]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
下拉框宽度太小，文字过长会出现隐藏问题

### What does the proposed API look like?
期望下拉框组件支持横向滑动

**Comment by afc163** [comment]
建议根据文字加长下拉宽度，横向滚动的交互不可取。
