### ISSUE TITLE
Input masks

### ISSUE THREAD

**Issue by leticiacostadias** [ant-design/ant-design#10580]
I'm having some trouble with input masks with antd.

I almost wrapping antd input in a react input mask, but I'm not quite sure if this is a good idea.
Is there any suggested way to do that?

**Comment by fhaze** [comment]
I managed this way:

```
import {Input} from "antd";
import React from "react";
import InputMask from 'react-input-mask';
import PropTypes from 'prop-types';

const InputMasked = (props) => {
  const { mask, maskChar, formatChars, alwaysShowMask, inputRef } = props;

  return (
    <InputMask
      mask={mask}
      maskChar={maskChar}
      formatChars={formatChars}
      alwaysShowMask={alwaysShowMask}
      inputRef={inputRef}
      value={props.value}
      onChange={props.onChange}>
      { (inputProps) => <Input {...inputProps} disabled={props.disabled ? props.disabled : null} /> }
    </InputMask>
  );
};

InputMasked.propTypes = {
  mask: PropTypes.string,
  maskChar: PropTypes.string,
  formatChars: PropTypes.object,
  alwaysShowMask: PropTypes.bool,
  inputRef: PropTypes.func
};

export default InputMasked;
```

**Comment by marlosirapuan** [comment]
Thank you! Using react-hooks showed me a warning:

`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

so then I added `forwardRef`, like this, to fixed:

```
import { Input } from 'antd'
import React, { forwardRef } from 'react'
import ReactInputMask from 'react-input-mask'
import PropTypes from 'prop-types'

const InputMask = forwardRef((props, ref) => {
  return (
    <ReactInputMask {...props}>
      {(inputProps) => <Input {...inputProps} ref={ref} disabled={props.disabled ? props.disabled : null} />}
    </ReactInputMask>
  )
})

InputMask.propTypes = {
  mask: PropTypes.string,
  maskChar: PropTypes.string,
  formatChars: PropTypes.object,
  alwaysShowMask: PropTypes.bool,
  inputRef: PropTypes.func
}

export default InputMask
```

**Comment by antoniopresto** [comment]
https://www.npmjs.com/package/antd-mask-input

**Comment by iloveip** [comment]
Hi @marlosirapuan,

Could you please share a codesandbox demo with `antd` and `react-input-mask`? I tried your example, but for me it doesn't work (the mask is shown, but user input doesn't follow it and can be typed beyond the mask). Here is a [demo](https://codesandbox.io/s/react-input-mask-wantd-v2-dkp8o?fontsize=14).

**Comment by marlosirapuan** [comment]
> Hi @marlosirapuan,
> 
> Could you please share a codesandbox demo with `antd` and `react-input-mask`? I tried your example, but for me it doesn't work (the mask is shown, but user input doesn't follow it and can be typed beyond the mask). Here is a [demo](https://codesandbox.io/s/react-input-mask-wantd-v2-dkp8o?fontsize=14).

Sure. I used with drawerform: [https://codesandbox.io/s/example-drawer-form-input-mask-n64ko](https://codesandbox.io/s/example-drawer-form-input-mask-n64ko)

**Comment by iloveip** [comment]
@marlosirapuan Thank you very much!

**Comment by iloveip** [comment]
Hi @marlosirapuan,

I have a question. Is there anyway to make your example work without `getFieldDecorator` and `Form.create`?

**Comment by romelgomez** [comment]
@antoniopresto a feature request, that work also with:   

https://rn.mobile.ant.design/components/input-item/
