### ISSUE TITLE
Mention component value={this.state.value} failed

### ISSUE THREAD

**Issue by foxmuldercp** [ant-design/ant-design#10584]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
npm 6.0.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xr3v4pyljp)

### Steps to reproduce
When i try to create controlled component <Mention /> with value={this.state.existant_param} component generated a runtime error, and works if i drop value={..} from props

### What is expected?
properly generated dom element

### What is actually happening?
runtime error, described in codesandbox.
onChange and onSelect props don't work properly.
setting value={this.state.exstantprop} generated error
---
bundle.js: TypeError: contentState.getBlockMap is not a function
    at Function.createWithContent (bundle.js)
    at new Mention (bundle.js)
    at constructClassInstance (bundle.js)
    at beginWork ...
---

---
try to use controlled Mention component without <Form />. setting the ref properly such as described in component documentation can't affected too

**Comment by memoryza** [comment]
value and defaultValue must be convert to ContentState

 @foxmuldercp  use **toContentState** method  convert string to ContentState

```
import React, {Component} from 'react';
import ReactDOM from 'react-dom';
import moment from 'moment';
import { Mention, version } from 'antd';
import 'antd/dist/antd.css';
const { toString, toContentState } = Mention;


class ChatTab extends Component {
  constructor(props) {
    super(props)
    this.state = { message: toContentState('none'), selected: '', users: ['a','b'] }
  }

  updateMessage(data) {this.setState({message: data})}

  setSelected(data) { this.setState({ selected: data }) }
  render() {
   return( <div style={{ margin: 24 }}>
    <div>mesg: to: {this.state.to}</div>
    <Mention defaultValue={this.state.message}
       value={this.state.message}
      onSelect={() => this.onSelect}
      suggestions={this.state.users} onChange={(data) => this.updateMessage(data)} />
    </div>
   )}
}
// function showData(value) { console.log(value)}

ReactDOM.render(<ChatTab />,
  document.getElementById('root')
);
```

**Comment by afc163** [comment]
The type of value should be a EditState rather than string.

https://ant.design/components/mention
