### ISSUE TITLE
Card cover image sizing

### ISSUE THREAD

**Issue by acrtz** [ant-design/ant-design#10585]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Card images should be able to be evenly sized for a set of related cards. Here is a codesandbox that  shows the implementation with uneven and even sizing, https://codesandbox.io/s/km45ox3pp7. 

### What does the proposed API look like?
Potentially pass an argument to the cover prop of card, that specifies desired aspect ration, or just height and width of images.

**Comment by afc163** [comment]
https://codesandbox.io/s/oj5myp4rwy

**Comment by afc163** [comment]
You can customize your owner styles to make it right.
