### ISSUE TITLE
Expandable table does not include children when adding new rows

### ISSUE THREAD

**Issue by omaji7** [ant-design/ant-design#10588]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
ubuntu 16.04

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6x790o0mlk)

### Steps to reproduce
Implement expandable table, add new row with children, it will ignore the children

### What is expected?
When adding new row (parent   children), it should add it to the table.

### What is actually happening?
it ignores the children rows of newly added parent row

**Comment by yesmeck** [comment]
`defaultExpandAllRows` only works at the first render. If you want the newly added row expanded by default, plz use `exapndedRowKeys`.
