### ISSUE TITLE
Language of enter is not changing from chinese to english

### ISSUE THREAD

**Issue by Alfran007** [ant-design/ant-design#10593]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Feature will change the 'Enter' which is written in chinese to english .
I tried using import enUS from 'antd/lib/locale-provider/en_US';

### What does the proposed API look like?
https://mobile.ant.design/components/input-item/#components-input-item-demo-money

**Comment by afc163** [comment]
You should file issue in http://github.com/ant-design/ant-design-mobile/issues
