### ISSUE TITLE
tree能一个节点多个选择

### ISSUE THREAD

**Issue by wang5909912** [ant-design/ant-design#10597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tree单个节点多个多选框提供选择，不止是满足读写功能，也有可能权限管理里面功能细化或者读写功能分离

### What does the proposed API look like?
我希望是tree的树形结构，后面能配上check多选框的多选功能，类似于table组件，只是后面内容变成了多选框

**Comment by afc163** [comment]
自定义 TreeNode 的 title。
