### ISSUE TITLE
Under ie9, the calendar year is selected and then clicked open again, not scrolling to the correct location, but back to the top.

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#10594]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
windows7，ie9

### Reproduction link
[http://ant.design/components/calendar-cn/](http://ant.design/components/calendar-cn/)

### Steps to reproduce
At the beginning. Select Year 2027.Then,click again to select year,Year selection scroll to the top.

### What is expected?
Like chrome, scroll to the selected year.

### What is actually happening?
Year selection scroll to the top.

**Comment by afc163** [comment]
antd v4 had dropped IE9/10 support and v3 won't take time to check compatibility issues on old browers.
