### ISSUE TITLE
Why ant.design <Upload> component cancel upload request when setState?

### ISSUE THREAD

**Issue by qinyuanbin** [ant-design/ant-design#10590]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
chrome、ant

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wopv2xn1k5)

### Steps to reproduce
1. I have a form with upload component using ant.design
2. but every time I upload an image, the request aborted.
3. I figure out the `setState()` method call in the `onChange` handler caused the aborted.
4. I copied the code from ant.design example: https://ant.design/components/upload-cn/#components-upload-demo-avatar
5. I dont kown what's wrong here, I wasted too much time on this...
6. finally, here is my code: [![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wopv2xn1k5)

### What is expected?
how can I post a request that not abort

### What is actually happening?
request always abort, image upload failed

**Comment by afc163** [comment]
Seems to be a bug.

**Comment by qinyuanbin** [comment]
@afc163 这个是我的锅，issue可以关闭了，我发现是我用纯函数组件封装了form.item导致的，改成react class来封装之后，问题就不存在了
