### ISSUE TITLE
Cascader showSearch is not working on latest version

### ISSUE THREAD

**Issue by Aruna1990** [ant-design/ant-design#10599]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
Google Chrome 66.0.3359.181

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
1. Open https://ant.design/components/cascader-cn/
2. Find the demo for Search
3. Click on the Cascader component

### What is expected?
Can input my searching text and show the correct result list

### What is actually happening?
Input is not available, cannot input any letters

---
There is a problem after we installed latest node package。It was working fine in earlier version。

**Comment by afc163** [comment]
broken by https://github.com/ant-design/ant-design/commit/bc4143f8a3109e3b66bc068a7dfea89e1c0253c6

**Comment by afc163** [comment]
z-index 导致的点击 bug 好像没办法写用例。

**Comment by yesmeck** [comment]
Checkbox 最好改成不要依赖 z-index 吧
