### ISSUE TITLE
选择下拉框带Input输入

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design#10600]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在Antd的select好像没有这个功能。效果类似 http://jsfiddle.net/BobStein/ty640uva/。

### What does the proposed API look like?
```
<Select inputOption=true .... />
```

**Comment by afc163** [comment]
https://ant.design/components/select/#components-select-demo-search

**Comment by AttackOnMorty** [comment]
@afc163 Why this is closed?

**Comment by Ostaer** [comment]
> @afc163 Why this is closed?

+1
