### ISSUE TITLE
webpack react ts babel，import antd时 会提示antd找不到

### ISSUE THREAD

**Issue by Ouhuang** [ant-design/ant-design#10601]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
windows8.1,Google Chrome版本 65.0.3325.181（正式版本） （64 位）,react 16.3.2,webpack4.8

### Reproduction link
[https://github.com/Ouhuang/interest_web/blob/master/src/views/login/login.tsx](https://github.com/Ouhuang/interest_web/blob/master/src/views/login/login.tsx)

### Steps to reproduce
如重现github内 login.tsx中，引用antd  编辑器会提示找不到

### What is expected?
能找到antd

### What is actually happening?
找不到antd

**Comment by yesmeck** [comment]
Please refer to the document https://ant.design/docs/react/use-in-typescript-cn
