### ISSUE TITLE
The button can be still clicked when it is on loading state in a modal component of antd

### ISSUE THREAD

**Issue by SanPy** [ant-design/ant-design#10615]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
windows 10, ie 11

### Reproduction link
[http://ant.design/components/modal-cn/](http://ant.design/components/modal-cn/)

### Steps to reproduce
please try it on the second example of modal component of official antd。When i click the commit button, the buttong is loading, but i can still click on it. 

### What is expected?
when it is loading, i cannot click it.

### What is actually happening?
when it is loading, i can still click it.

---
在ie11浏览器中，modal组件中的提交按钮点击处于loading状态之后，仍然可以点击它。具体现象可以用ie11打开antd官网，点击modal组件中第二个例子的提交按钮，你就会发现尽管按钮处于loading状态，但是我们仍然可以点击他。

**Comment by afc163** [comment]
@SanPy 能帮忙看看最新的 antd 4.0 官网上还存在这个问题么？

**Comment by afc163** [comment]
Closing for no response
