### ISSUE TITLE
initialValue not changed on props changed

### ISSUE THREAD

**Issue by zzsoszz** [ant-design/ant-design#10612]
#- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
浏览器版本

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
```js
              
                    <div id="div1">
                        pkid:{this.props.pkid}
                    </div>
                    <FormItem
                        {...formItemLayout}
                        label="产品ID"
                        hasFeedback
                    >
                        {getFieldDecorator('pkid', {
                            initialValue:this.props.pkid,
                            rules: [
                                { required: true, message: '产品ID!' },
                            ],
                        })(
                            <Input placeholder="a-10" />
                        )}
                    </FormItem>

```

### What is expected?
initialValue will changed on this.props.pkid changed

### What is actually happening?
initialValue is fist seted value

![qq 20180522100953](https://user-images.githubusercontent.com/3824958/40338554-57a25638-5da8-11e8-9c54-a817ed6e65c9.png)
![qq 20180522101001](https://user-images.githubusercontent.com/3824958/40338555-57ee4eda-5da8-11e8-8490-02727eb11976.png)

**Comment by afc163** [comment]
That is why it is called **initial** value.

**Comment by zzsoszz** [comment]
handleSubmit= (values) =>  {
        if(this.props.onOk)
        {
            this.props.onOk(values);
            **this.props.form.resetFields();**
        }
    }


called this.props.form.resetFields() after form submit  resolved my problem

**Comment by braian125** [comment]
https://github.com/ant-design/ant-design/issues/22372#issuecomment-602102164

**Comment by asedreza** [comment]
it because initialValue will set in Form componentDidMount lifecycle,
when you update initialValue it won't set inputs value again
you can use these methods:
``` javascript
/** for reset all input values: */
this.props.form.resetFields();
/** for update inputs values: */
this.props.form.setFieldsValue(newFormFieldsValues);
```
