### ISSUE TITLE
穿梭框目前只有左右布局, 希望能支持上下布局呢?

### ISSUE THREAD

**Issue by xjdata** [ant-design/ant-design#10617]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前的左右布局  在实际业务界面中 占位太大, 但这不是最终要的, 更希望 有上下布局的穿梭框 以实现一个界面中的业务操作更流畅.

预期, 能将  业务对象的添加功能  画在界面左侧  将上下布局的穿梭框 画为右侧,   在日常的业务操作中, 左侧可以新增 穿梭框 数据源中的项目, 

比如  快递派送规划界面,  左侧录入单号,选择派送人员,  右侧 将已录入的 单号 进行选择.  使用穿梭框 来 显示 最新录入的50个单号,    及规划本次派送的目标单号.  

当然 将这个界面拆分成2个 功能是肯定可以实现的.   但拆分后操作起来 太繁琐了.

谢谢

### What does the proposed API look like?
如上

**Comment by afc163** [comment]
暂时不支持，建议通过自定义样式满足。

如果有优雅的改造方案，可以直接 PR ~
