### ISSUE TITLE
通过npm install antd的antd库import时DatePicker和TimePicker名称不对

### ISSUE THREAD

**Issue by freestyle21** [ant-design/ant-design#1061]
在 [github仓库](https://github.com/ant-design/ant-design) 和 [DatePicker文档](http://ant.design/components/date-picker/) 里面都是正确的，即：

      import { DatePicker, TimePicker } import antd;

都能正确使用。
但是，通过 `npm install antd` 下载的执行上面的import就会报错。

看了看原因是在 npm 仓库代码里面，/lib/index.js export的对象中，是 `Datepicker`, `Timepicker`。

**Comment by afc163** [comment]
你安装的 antd 版本是多少？

http://ant.design/docs/react/upgrade-notes#timepicker%E3%80%81datepicker-%E9%87%8D%E5%91%BD%E5%90%8D

**Comment by freestyle21** [comment]
哦，看到了。
版本0.10.5
