### ISSUE TITLE
Teaxtarea autosize bug

### ISSUE THREAD

**Issue by alexmelnyk** [ant-design/ant-design#10621]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
All

### Reproduction link
[http://ant.design/components/input/#components-input-demo-textarea](http://ant.design/components/input/#components-input-demo-textarea)

### Steps to reproduce
1) Set to Textarea autosize prop (for example autosize={{minRows: 3, maxRows: 8}})
2) Stretch Textarea to max height
3) Start type text as much as possible

### What is expected?
Textarea don't change it height

### What is actually happening?
Textarea's height is getting lower

---
This bug reproduces in examples too

**Comment by yutingzhao1991** [comment]
I think it's not a bug, it's a design problem, `autosize` means adjust height automatically. Maybe we should move minRows and maxRows out from autosize.

**Comment by afc163** [comment]
The Textarea with autosize prop shouldn't be stretchable.

**Comment by yutingzhao1991** [comment]
> The Textarea with autosize prop shouldn't be stretchable.

agree.

But I guess this is not @alexmelnyk want. @alexmelnyk what's your real want? set maxRows for stretch?

**Comment by alexmelnyk** [comment]
@yutingzhao1991 yes. As it is done in the example.

**Comment by yutingzhao1991** [comment]
I see. so it is two issue:

- The Textarea with autosize prop shouldn't be stretchable.
- add props `maxRows` and `minRows` to set range for stretchable. @alexmelnyk Is this your mean? why you need this? it's seems unimportant for textarea.

**Comment by zombieJ** [comment]
Hi @alexmelnyk,
No response for long time. Since user can set style by `min-height` & `max-height` for TextArea stretch.

Will reopen if additional info provided.
