### ISSUE TITLE
Popconfirm如何阻止弹出框关闭

### ISSUE THREAD

**Issue by xaasu** [ant-design/ant-design#10622]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
win10 chrome

### Reproduction link
[https://codepen.io/xaasu/pen/ELMLXy?editors=0010](https://codepen.io/xaasu/pen/ELMLXy?editors=0010)

### What is expected?
现Popconfirm中做了一些简单的校验，希望根据校验结果决定是否关闭弹框，使用e.preventDefault();弹框仍然会关闭

### What is actually happening?
e.preventDefault();可以阻止其关闭

**Comment by afc163** [comment]
Use `visible` and `onVisibleChange` to control it.

**Comment by BinaryHot** [comment]
有个问题 onConfirm 是先设置 visible 为 false 后执行，这里感觉应该做成根据执行的返回结果或者执行情况进行关闭
