### ISSUE TITLE
ValidateFields and validateFieldsAndScroll are not working when errors are adding dinamically through setFields

### ISSUE THREAD

**Issue by carlagromero** [ant-design/ant-design#10624]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
Chrome 66.0.3359.181, Windows 10

### Reproduction link
[https://codepen.io/carlagromero/pen/YLgjjG?editors=1010](https://codepen.io/carlagromero/pen/YLgjjG?editors=1010)

### Steps to reproduce
1. Enter any character into 'note' input
2. Click on submit button

### What is expected?
The form should not be submitted.

### What is actually happening?
The form is submitted. Validation is not working.

---
I tried implement these both methods to validate: validateFields and validateFieldsAndScroll

**Comment by yutingzhao1991** [comment]
Filed without rules will not be validated, ref: https://github.com/react-component/form/blob/master/src/createBaseForm.js#L442 . @yesmeck is it a bug?

And @carlagromero maybe you can custom a validate for your required https://codepen.io/yutingzhao1991/pen/GGNNVG?editors=1010

**Comment by yesmeck** [comment]
I don't think this is a bug. `validateFields` means validate by the rules, you'd have to provide validate rules.

**Comment by raindecastro** [comment]
Hi there, were any of you able to make a workaround for this? I'm also setting my errors dynamically since we're handling some other errors through the backend.
