### ISSUE TITLE
建议antd 官网支持service worker

### ISSUE THREAD

**Issue by EthanWan** [ant-design/ant-design#10625]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
由于网络原因，在公司查看组件文档时经常加载不出来。故建议antd 官网支持service worker。

### What does the proposed API look like?
none

**Comment by afc163** [comment]
http://github.com/ant-design/ant-design-pro
http://github.com/ant-design/ant-design-mobile

我们需要把这些公用配置都提到 antd-tools 里共享起来。
