### ISSUE TITLE
Popover的trigger方式为click,在弹出层中如果有Select,修改Select的选项会导致Popover隐藏

### ISSUE THREAD

**Issue by shadiniao** [ant-design/ant-design#10632]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
3.5.3, chrome 版本 66.0.3359.117（正式版本） （64 位）, react 16.3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk97o1xjxw)

### Steps to reproduce
1.在给到的链接demo中,点击test按钮,弹出Popover
2.弹出的popover中修改Select下拉框,修改为其他选项

### What is expected?
1.Select下拉框修改为其他选项
2.popover正常显示

### What is actually happening?
popover隐藏

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#select-dropdown-datepicker-timepicker-popover-popconfirm-will-disappear-when-i-click-another-popup-component-inside-it-how-to-resolve-it
