### ISSUE TITLE
Select collapses in Forms with "inline" layout

### ISSUE THREAD

**Issue by eduludi** [ant-design/ant-design#10637]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/93oxw93nny)

### Steps to reproduce
In a Form with inline layout, add a Select field.

### What is expected?
The select to have some minimum width, like in other inputs.

### What is actually happening?
The Select collapses horizontally, making the component almost useless . 

---
Would we great if Select's width can be inferred from the options width.

**Comment by afc163** [comment]
You should set `style={{ width: xxx }}` to Select which has no default width.
