### ISSUE TITLE
Popup is attached to the top of the page after expanding

### ISSUE THREAD

**Issue by apieceofbart** [ant-design/ant-design#10638]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
Chrome, Ubuntu

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8y25l48jzj)

### Steps to reproduce
1. Click on the input field
2. Expand the root element
3. Collapse the root element

### What is expected?
Tree is attached to the top of the page

### What is actually happening?
Tree should be below input as before

---
I have tried workarounds suggested in other tickets but they don't seem to work:
```
      getPopupContainer: () => document.getElementById("wrapper"),
      getPopupContainer: triggerNode => triggerNode.parentNode,
```
Important thing here is number of elements (height of the tree) - it works fine for smaller tree (e.g. 10 elements)

**Comment by afc163** [comment]
It is by designed, popup element will take as much as space if there is no enough space to display.

**Comment by apieceofbart** [comment]
Yeah, but shouldn't it get back to it's original position after collapsing? Seriously, you don't consider this bug?

**Comment by afc163** [comment]
> shouldn't it get back to it's original position after collapsing

That is a bug ❤️

**Comment by apieceofbart** [comment]
@afc163 Sorry, deleted by accident, I will create an example soon

**Comment by apieceofbart** [comment]
Here is the new one: https://codesandbox.io/s/008320vxz0

![image](https://user-images.githubusercontent.com/3791384/42829963-b9852a9c-89ea-11e8-9736-71bf1d06d82d.png)

**Comment by afc163** [comment]
@zombieJ

**Comment by zombieJ** [comment]
Publish for `rc-tree-select@2.0.7`: https://codesandbox.io/s/5w1yj8qzzx
