### ISSUE TITLE
 Icon in Dropdown Menu Items

### ISSUE THREAD

**Issue by eduludi** [ant-design/ant-design#10633]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k536m98w37)

### Steps to reproduce
In a Dropdown overlay, add an icon and a label (text) to the Menu.Item content.

### What is expected?
A margin between icon and label. There are other components where the proper margins are added to '.anticon', like in:

* `.ant-tabs-tab .anticon`
* `.ant-menu-item .anticon`
* `.ant-menu-submenu-title .anticon`

### What is actually happening?
There is no margin

**Comment by picodoth** [comment]
@eduludi you can either specify `.ant-tabs-tab .anticon` or wrap your label with a styled span. It's not very helpful for us to provide a fixed margin. What if someone else want a different margin?

**Comment by picodoth** [comment]
Closing

**Comment by afc163** [comment]
I think we can add a decent default margin for Icon in menu item as first child.

**Comment by eduludi** [comment]
@picodoth As you can see in the example, having no margin doesn't looks nice. Having a default margin will prevent this situation in the future, making the design framework more consistent. In the case someone wants a different margin, they can do what you say: _override the defaults_. 

Also, like I mentioned, that is something is being done in several other components that use icons: 

* `.ant-tabs-tab .anticon`
* `.ant-menu-item .anticon`
* `.ant-menu-submenu-title .anticon`

**Comment by eduludi** [comment]
Thanks @picodoth and @afc163! 👍
