### ISSUE TITLE
表单验证有bug, getFieldProps中设置initialValue将导致验证无效.

### ISSUE THREAD

**Issue by astwyg** [ant-design/ant-design#1063]
如题, 例子[点我](http://codepen.io/anon/pen/PZMPPW?editors=0010#0)

注意第82, 96, 117行, 只要在getFieldProps中设置了initialValue, 无论initialValue为null, undefined, 还是false, 表单验证一律直接通过了.

**Comment by benjycui** [comment]
再认真看下文档 http://ant.design/components/form/#this-props-form-getfieldprops-id-options
