### ISSUE TITLE
message能否带关闭的图标

### ISSUE THREAD

**Issue by jacktang** [ant-design/ant-design#10646]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
message一般设置的自动关闭的时间会长一点，不方便的是有时候想关闭也地方可以点击关闭。于是想换到notification，发现notification没有从topMiddle出来的... 所以有没有可能在message上加个关闭的图标？谢谢

### What does the proposed API look like?
```
let showCloseIcon = true;
message.error("This is error", 5, onClose, showCloseIcon);
```

**Comment by afc163** [comment]
You can try this way now: https://codesandbox.io/s/0pw0or248l

**Comment by jacktang** [comment]
@afc163 没看出来和原来的`message.info` 有什么不一样...

**Comment by afc163** [comment]
Sorry...

https://codesandbox.io/s/j4k4qp3z63

**Comment by asvencoop** [comment]
@afc163  非常感谢，看代码里 hide() 会直接执行  messageInstance.removeNotice(target)； 感谢!

**Comment by TTtuntuntutu** [comment]
but if i wanna click outside to hide Message

**Comment by afc163** [comment]
https://codesandbox.io/s/dank-shadow-gd8rt?file=/index.js
