### ISSUE TITLE
Add a prop on Table to allow user to hide expand icons for expandable rows

### ISSUE THREAD

**Issue by kafkahw** [ant-design/ant-design#10641]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When building tables with expandable rows, we choose to turn on prop 'expandRowByClick' on Table, which means user can now click anywhere in the row to expand/fold the row. Expand icons, in this case, look redundant and provide minimum help to users. Moreover, the column containing those icons takes up a big chunk of spaces in each row. We tried multiple hacky ways including css overriding to hide it, but that caused some unexpected side effects. Therefore, we thought it might be good to add a new feature to allow us to toggle the display of those expand icons.

### What does the proposed API look like?
We expect to see a new prop (e.g. "hideExpandIcon") added to Table component, so that when it exists the rendered table will hide the left-most column that contains expand icons. Here's a simple example:

```javascript
<Table
    hideExpandIcon
    expandRowByClick 
    expandedRowRender={() => {}}
    ...
/>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3055#issuecomment-248203824

**Comment by kafkahw** [comment]
Thanks for the reference! Would you mind giving a short description of the proposed solution in English? If my understanding is correct, we're suggested using 
```
expandIconAsCell={false} expandIconColumnIndex={-1}
```
Would these two props potentially change in the future? We couldn't find it in Ant-Design's official doc (https://ant.design/components/table/).
