### ISSUE TITLE
Redefine props in some components such as Button, Input and so on.

### ISSUE THREAD

**Issue by saplf** [ant-design/ant-design#10650]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
Webstorm

### Steps to reproduce
I used this library in WebStorm as it has powerful auto-complete functions. However, some inspections complained that I should offer props such as 'size', 'shape', 'type' and so on for the Button while the doc says these props are all optional.

![Produce](https://user-images.githubusercontent.com/8789121/40529538-f545883e-6027-11e8-9f7e-74977c193e90.png)

 I reviewed the code related in this repo and found that some components duplicate the declaration of component's props. Such as the Button component below: 

https://github.com/ant-design/ant-design/blob/b7cf33d1eb2fc7af66e4728e347af4c1824259e7/components/button/button.tsx#L41-L59

https://github.com/ant-design/ant-design/blob/b7cf33d1eb2fc7af66e4728e347af4c1824259e7/components/button/button.tsx#L69-L78

Maybe you choose these because of some reasons, but I think the latter can also remarked as optional.

### What is expected?
The right type declaration of these components.

### What is actually happening?
Some optional props of some components are marked as required.

**Comment by afc163** [comment]
There are TypeScript types and react prop-types which are different and we don't set any of props required. So I think it is Webstorm's problem.
