### ISSUE TITLE
Cacader设置expandTrigger="hover"后，容易误操作

### ISSUE THREAD

**Issue by luolonghao** [ant-design/ant-design#1065]
http://ant.design/components/cascader/#demo-hover

重现：设置10几条数据，先选择一级靠下的项，再选二级靠上的项，这时候很大概率划过其它一级项，导致二级项变成不是你要选择的数据。

解决方案：增加延迟。

**Comment by afc163** [comment]
:+1: 来个 PR？

> 不要把内网地址贴出来。

**Comment by luolonghao** [comment]
URL改了。。

**Comment by afc163** [comment]
Fixed in rc-cascader@0.9.1
