### ISSUE TITLE
treeSelect关于treeDefaultExpandAll的默认值有误

### ISSUE THREAD

**Issue by ahchuguang** [ant-design/ant-design#10669]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.5

### Environment
chrome66

### Reproduction link
[http://ant.design/components/tree-select-cn/](http://ant.design/components/tree-select-cn/)

### Steps to reproduce
The default value of treeDefaultExpandAll on API is false, but is actually true.

### What is expected?
The default value of treeDefaultExpandAll is false

### What is actually happening?
The default value of treeDefaultExpandAll is true

**Comment by yesmeck** [comment]
The default value is `false`.
