### ISSUE TITLE
Input Status change to error automatically

### ISSUE THREAD

**Issue by jamalabo1** [ant-design/ant-design#10665]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
ReactJS, Google Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
at first it worked but now its not working for unknown reason.

### What is expected?
Inputs does not turn red (error)

### What is actually happening?
Inputs turn to error status (red)

---
just first 6 inputs do that,
  
![antd](https://user-images.githubusercontent.com/25992049/40589279-30ed9512-61f3-11e8-8bba-215eac05eb02.gif)

**Comment by afc163** [comment]
Your codesanbox is not about what you are talking about.

**Comment by jamalabo1** [comment]
https://codesandbox.io/s/20k6r70wrj not the exact Code, but the invalid inputs.

**Comment by afc163** [comment]
I can't do anything if you don't provide any of steps to reproduce.

**Comment by jamalabo1** [comment]
@afc163 
Steps: 
Page load.
Wait 1~5s 
and the inputs change to error status without doing anything.

what more do you want to know?

**Comment by jamalabo1** [comment]
reopen

**Comment by picodoth** [comment]
@jamalabo1 not able to reproduce..
![test](https://user-images.githubusercontent.com/1731837/40984920-8a72149a-6915-11e8-8c25-c87e57a42f79.gif)

**Comment by picodoth** [comment]
Please reopen as needed

**Comment by jamalabo1** [comment]
@picodoth Actually yes. 

![antd2](https://user-images.githubusercontent.com/25992049/41005411-0204b926-6926-11e8-8fa3-fa3461684a9a.gif)

**Comment by picodoth** [comment]
@jamalabo1 can you reproduce on other browser? What is your browser version? Can you check console to see if there is anything unusual?

I really don't see this weird behavior. And seems like there is no one else reporting similar issue.

**Comment by jamalabo1** [comment]
Sounds like a browser fault, sorry for the inconvenience.
