### ISSUE TITLE
After create a tag in Select tag mode and do save action to update tags, a duplicate tag appeared

### ISSUE THREAD

**Issue by 374632897** [ant-design/ant-design#10661]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.56 Safari/537.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/31njjj9nn6)

### Steps to reproduce
* use `tag` mode of select
* set onChange callback to get created tag and save the new tag .
* created a tag

### What is expected?
after create a new tag and update the tag state, the previous item should disappear.

### What is actually happening?
there are two tags in the dropdown list with the save value, one is checked, another is not

---
I wanna a Select can do check and create jobs like GitHub Label.  I reviewed the docs of Select so many times but find no way to do this conveniently， so I hacked by using  onChange callback.  Maybe I got a wrong way. Thanks

**Comment by afc163** [comment]
https://codesandbox.io/s/v8qp75z457

Don't use index as key.

**Comment by 374632897** [comment]
@afc163 I have updated the demo above, and now the tags look like [{ name: 'tagName' }], and I use tag item as key of each option. The problem exsits,  and only when I use tagName as key,  the duplicated option with the same name will disappear.

```js
tags.push({ name: i.toString(36) + i });
// ....
{this.state.tags.map((item, index) => (
    <Option key={item}>{item.name}</Option>
))}
```
