### ISSUE TITLE
form can't set horizontal within a modal

### ISSUE THREAD

**Issue by draco111** [ant-design/ant-design#10664]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
browser

### Reproduction link
[https://segmentfault.com/q/1010000015046892](https://segmentfault.com/q/1010000015046892)

### Steps to reproduce
(1)declare a modal
(2)declare a form as a child for the modal

### What is expected?
can show the form item as horizontal

### What is actually happening?
by default the form item show vertical, if thought i set the layout of the form to horizontal, it still show the form item vertical

**Comment by draco111** [comment]
you can refer this link: https://codepen.io/whiteblueya/pen/NwVVLX?editors=0011

**Comment by afc163** [comment]
@draco111 Why don't you just modify the codepen to reproduce?

**Comment by afc163** [comment]
You have to specify `labelCol` and `wrapperCol` if you are using default horizontal layout like [all demos](https://ant.design/components/form/#components-form-demo-layout) did.

https://codepen.io/afc163/pen/KRORdv?editors=0010

**Comment by draco111** [comment]
sorry, here is the repo: https://codesandbox.io/s/py051kk8rx

**Comment by draco111** [comment]
still here? i just checked your code in codepen, the form display vertical, and i just fork the code, and set the layout to horizontal, and still show vertical, here is the updated code. https://codepen.io/anon/pen/Vxoxao?editors=0010

**Comment by draco111** [comment]
![image](https://user-images.githubusercontent.com/22537188/40582670-bf3f658c-61af-11e8-9dec-9b1b23b68f30.png)

**Comment by afc163** [comment]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/507615/40582684-51b7e858-61b0-11e8-82f4-8b60f761eddd.png">

**Comment by draco111** [comment]
ok, got it, you mean: event thought the layout was set to horizontal, the labelCol and wrapperCol still need to set the as you mention above, right? 
is this a bug since the api doc say as this:

**Comment by draco111** [comment]
![image](https://user-images.githubusercontent.com/22537188/40582973-cbdcdc82-61b6-11e8-94f4-8e9bf331576d.png)
