### ISSUE TITLE
Timepicker has no access to event, comes back as undefined

### ISSUE THREAD

**Issue by psingh24** [ant-design/ant-design#10662]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have multiple Timepicker components on the same page, being able to use the same handleChange method would be nice as I shhould be able to distinguish between the timepicker components via a name or other attribute that should be accessed via the event.target._____

### What does the proposed API look like?
Many react bootstrap components like Checkbox have access to event.

onChange(e) {
this.setState({
[e.target.name]: e.target.value
});

}
<CheckBox name="first" onChange=(this.onChange)></CheckBox>
<CheckBox name="second"  onChange=(this.onChange)></CheckBox>
<CheckBox name="third"  onChange=(this.onChange)></CheckBox>

Not sure how that would effect your API

**Comment by psingh24** [comment]
@picodoth

Thanks for the reply. I was able to solve my issue using Refs. 

Is there any other way to distinguish between multiple Timepicker components on the same page that’s already built into your API?

**Comment by picodoth** [comment]
the underline rc-timepicker takes id from props, but I think what you need is something for onChange handler. We'll have to use a wrapper.

**Comment by picodoth** [comment]
We can reopen this issue as needed, but closing it for now since the issue does not block anything right now
