### ISSUE TITLE
input-number: focused style could not be removed after clicking up/down button and then outside

### ISSUE THREAD

**Issue by wendzhue** [ant-design/ant-design#10663]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
macOS High Sierra 10.13.4, Firefox 60.0.1

### Reproduction link
[http://ant.design/components/input-number-cn/](http://ant.design/components/input-number-cn/)

### Steps to reproduce
It's on official website. Click up/down button of a input-number component without focusing the input, and then click outside, focused style would not be removed.

### What is expected?
Focused style should be removed.

### What is actually happening?
Focused style is not removed.

---
I fixed the problem in ng-zorro-antd, and I thought I should check it on your repo :D.

I think it is caused by the same reason as #10417.

**Comment by zhujinxuan** [comment]
@afc163 I think I find the reason about that:
`rc-input-number` does not call native focus (this.ref.focus) with input handler, then the click outside does not call the onBlur event. 

I will submit a PR on that next week on rc-input-number

**Comment by zhujinxuan** [comment]
Fixed in https://github.com/react-component/input-number/pull/106

**Comment by afc163** [comment]
also fix https://github.com/ant-design/ant-design/issues/9953
