### ISSUE TITLE
Input's box-shadow not display correct in Tabs

### ISSUE THREAD

**Issue by lovekonakona** [ant-design/ant-design#10675]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.5

### Environment
MacOS 10.13.4, Chrome 66.0.3359.139, React 3.5.5

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk407xvop6)

### Steps to reproduce
Put a Input into TabPane.

### What is expected?
box-shadow is display correct when Input is focusing.

### What is actually happening?
the left, right, bottom of box-shadow are not display, hidden by `.ant-tabs`
![image](https://user-images.githubusercontent.com/790296/40605769-fe518fc0-6295-11e8-8a2e-a08f1b3fc16e.png)

**Comment by picodoth** [comment]
<img width="513" alt="screen shot 2018-06-07 at 2 15 42 pm" src="https://user-images.githubusercontent.com/1731837/41081414-54a668fe-6a5d-11e8-8e27-48651922044b.png">

I don't think this should be considered as a bug, you should manage padding in side tabpane content.
