### ISSUE TITLE
Affix not work when set offsetTop or offsetBottom

### ISSUE THREAD

**Issue by chenhaizhou** [ant-design/ant-design#10674]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
all browsers

### Reproduction link
[https://ant.design/components/affix-cn/](https://ant.design/components/affix-cn/)

### Steps to reproduce
scroll page

### What is expected?
Affix is fixed

### What is actually happening?
no fixed

**Comment by afc163** [comment]
`offsetBottom` is not working now.
