### ISSUE TITLE
Webpack 4.10.0 results in error

### ISSUE THREAD

**Issue by plhosk** [ant-design/ant-design#10689]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
Webpack 4.10.0

### Steps to reproduce
when I run `yarn build` (to build the production bundle with webpack)

```
ERROR in chunk vendors [initial]
bundle.vendors.css
.\node_modules\antd\es\col\index.js
RuntimeTemplate.moduleId(): Module .\node_modules\antd\es\grid\col.js has no id. This should not happen.
```

### What is expected?
Weback should complete without error

### What is actually happening?
Webpack stops with error.
If I downgrade to webpack 4.9.2 the error no longer occurs

**Comment by afc163** [comment]
It seems more about webpack not antd.
