### ISSUE TITLE
Menu.Item cannot render correctly in React.Fragment

### ISSUE THREAD

**Issue by dreamerblue** [ant-design/ant-design#10688]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.3

### Environment
macOS 10.13.4, Chrome 66

### Reproduction link
[https://codepen.io/dreamerblue/pen/NzKmej](https://codepen.io/dreamerblue/pen/NzKmej)

### Steps to reproduce
Open codepen link

### What is expected?
Menu.Item renders correctly in React.Fragment (<>...</>).

### What is actually happening?
Menu.Item cannot render correctly in React.Fragment.

In HTML it's rendered as `<li class="undefined-item" role="menuitem">...</li>`.

**Comment by yesmeck** [comment]
It's a known issue, you can only pass `MenuItem` or `MenuGroup` as `Menu`'s children. See #4853

**Comment by IslaMurtazaev** [comment]
I had an issue with my `<AccessControl />` component which looked like this
```
const AccessControl = ({ children, permission }: Props) => {
  const user = useUserPermission()

  return user[permission]
    ? children
    : null
}
```
Passing `Menu.Item` would into it would break menu styles
```
      <AccessControl permission={Permissions.CAN_MANAGE}>
        <Menu.Item>
          <NavLink to='/billing' activeClassName='active-link'>Billing</NavLink>
        </Menu.Item>
      </AccessControl>
```
So I had to pass props into the child component and it worked!
```
const AccessControl = ({ children, permission, ...props }: Props) => {
  const user = useUserPermission()
  const childrenWithProps = Children.map(children, child => {
      return cloneElement(child, props)
  })

  return user[permission]
    ? <>{childrenWithProps}</>
    : null
}
```
