### ISSUE TITLE
Tree Component Error  when draggable defalut false

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#10686]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.5

### Environment
Win 10 17134； Chrome 65.0.3325.181（正式版本）； The official website；https://ant.design/components/tree-cn/

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
Drag  a Tree Component that can't be dragged

### What is expected?
Console no error

### What is actually happening?
Console error

**Comment by Zero0331** [comment]
英语表达能力实在有限，哈哈哈哈哈啊哈，官网第二个demo，checkBox的Tree，尝试拖拽的时候（也许需要把dom选中，有蓝色背景色的时候），在控制台会报错，不知道会不会影响到其他功能

**Comment by zombieJ** [comment]
@Zero0331 , 我这边重现不了。能说一下具体重现步骤吗？

**Comment by Zero0331** [comment]
@zombieJ  我重新看了下，应该不算是bug，index.js:1 Uncaught TypeError: Cannot read property 'props' of undefined，拖动Tree节点到其他组件时，只是控制台会报错
