### ISSUE TITLE
Does the component provide a callable upload method?

### ISSUE THREAD

**Issue by Linbubin** [ant-design/ant-design#10687]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I click on the screenshot (save the picture locally), directly trigger the Upload upload event, upload the picture to the specified address, instead of being selected and uploaded one by one.

### What does the proposed API look like?
dont know

**Comment by yesmeck** [comment]
No, you can not trigger upload event programmatically du the security strategy of browser.

**Comment by Linbubin** [comment]
@yesmeck 
ask a question: I  can bring screenshots and uploads together to avoid  the security strategy of browser？
because I see the man should click to upload method(Or I understand wrong, must click on upload, then select file, upload again, can not be replaced by any other way.)
