### ISSUE TITLE
Webpack Server Side Rendering - Supported or not?

### ISSUE THREAD

**Issue by joenot443** [ant-design/ant-design#10685]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.5

### Environment
Mac OS, Chrome Version 66.0.3359.181 (Official Build) (64-bit)

### Reproduction link
[https://github.com/ant-design/react-starter-kit](https://github.com/ant-design/react-starter-kit)

### Steps to reproduce
Create a webpack config which includes a client-side and server-side configuration.
Use the suggested implementation of `  ["import", { libraryName: "antd", style: true }],` inside the babel-loader client configuration. 

### What is expected?
Antd CSS is included in the HTML on the server side rendered payload

### What is actually happening?
Antd CSS is not included in the HTML. Once the client renders however, the styling appears and it works fine.

---
I'm working on a relatively large project which initially was started using the react-starter-kit repo. 

Should I expect SSR to work with antd, and have the CSS included in the payload?

**Comment by yesmeck** [comment]
`antd` do support SSR, your question seems more related to the configuration of webpack.

**Comment by joenot443** [comment]
Please see the attached repository. It's an @ant-design repository, what changes are required to make it work with SSR? 

Or perhaps, more generally, what loader chain is required to make SSR work for antd?

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/5171
