### ISSUE TITLE
Menu的selectedKeys经过react-css-modules处理后无法使用

### ISSUE THREAD

**Issue by LeuisKen** [ant-design/ant-design#1068]
参考 #573 

经过测试，其实不是无法使用，而是说，如果设置<MenuItem key="movie"></MenuItem>时，selectedKeys所实际接受的值变成了 “movie/.$movie”，请问官方打算如何处理次问题

**Comment by joesonw** [comment]
Tree也是这样, 解决方法也不绕啊. `${key}/.${key}`

**Comment by afc163** [comment]
有好的解决方案欢迎给 PR ，我们自己暂时没遇到这个问题，优先级就不高。

**Comment by warmhug** [comment]
`${key}/.${key}` 这样的key 是经过 `React.Children.map/toArray/xx`等方法处理后生成的（CSSModules 可能做为上层组件会使用这些方法把节点key改变掉）可以自己遍历节点时使用`Array.from()`等纯js方法来做、不会修改key。

**Comment by 951759534** [comment]
遇见同样的问题  defaultSelectKeys不生效

**Comment by 951759534** [comment]
in CssMoudle中

**Comment by 951759534** [comment]
I put the css file of Show component into the global css file 
who can tell me a better solution to solve the problem
I think In global Solution is not best solution In this project

**Comment by 951759534** [comment]
I add key in defaultSelected string that is ".$" to solve it ................... work normal
