### ISSUE TITLE
antd-design PC版上传ios纵向拍摄图片会90度翻转 （A problem in Pc version:  the photo made with iphone will turn 90 degree when I use Upload components）

### ISSUE THREAD

**Issue by HappySusan** [ant-design/ant-design#10696]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want the origin direction of the picture.

### What does the proposed API look like?
I want the origin direction of the picture.

**Comment by yesmeck** [comment]
upload 不会对图片进行处理，可以在服务端对图片进行处理。
