### ISSUE TITLE
Select组件multiple模式不显示placeholder

### ISSUE THREAD

**Issue by Yuliang-Lee** [ant-design/ant-design#1069]
Demo:http://codepen.io/Yuliang-Lee/pen/mVNLQz?editors=0010
问题:
1. 在multiple模式下的placeholder没生效
2. 在multiple和search结合的时候显示了'searchPlaceholder'

**Comment by afc163** [comment]
Reinstall antd.

**Comment by Yuliang-Lee** [comment]
ok.THX
