### ISSUE TITLE
Antd pro can't be established :)

### ISSUE THREAD

**Issue by wuranxu** [ant-design/ant-design#10691]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.5

### Environment
mac os

### Reproduction link
[https://pro.ant.design/index-cn](https://pro.ant.design/index-cn)

### Steps to reproduce
1. 打开浏览器
2. 输入网址https://pro.ant.design/index-cn

### What is expected?
能够正常显示Antd pro 首页

### What is actually happening?
无法加载网页

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9930

**Comment by wuranxu** [comment]
sorry~~下次会记得先搜一下issue
