### ISSUE TITLE
TabPane's content is placed on top of fixed header

### ISSUE THREAD

**Issue by whtsky** [ant-design/ant-design#10693]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.5

### Environment
Chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k2rzwmvw7)

### Steps to reproduce
Open page, scroll

### What is expected?
TabPane's content is covered by fixed header

### What is actually happening?
TabPane's content is placed on top of fixed header
<img width="578" alt="image" src="https://user-images.githubusercontent.com/876694/40643845-e6f25df0-6353-11e8-8cf2-f96593f11d5e.png">

**Comment by afc163** [comment]
https://codesandbox.io/s/p5l96rx26x

**Comment by whtsky** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/876694/40652755-befd7740-636b-11e8-8dae-b0f99e34b673.png">

still

**Comment by frantic1048** [comment]
![image](https://user-images.githubusercontent.com/3102803/40654514-1d38be5a-6371-11e8-8c57-32d8de47ee28.png)

Open page -> **scroll**

**Comment by afc163** [comment]
My bad, https://codesandbox.io/s/q8yj8k9kmw

**Comment by whtsky** [comment]
@afc163 thanks, adding z-index fixed.
