### ISSUE TITLE
Popover Bubble card, can not customize the setting of color properties

### ISSUE THREAD

**Issue by jishuke** [ant-design/ant-design#10708]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We can customize the colors that you need to set up the project

### What does the proposed API look like?
One more style setting property

**Comment by jishuke** [comment]
For example, black

**Comment by picodoth** [comment]
For a workaround, you can always use `${prefix}-popover-inner` class to add customized style

**Comment by yesmeck** [comment]
```
.my-popover .ant-popover-inner {
  color: black;
}

<Popover overlayClassName="my-popover" />
```
