### ISSUE TITLE
百度域下字体403 forbidden

### ISSUE THREAD

**Issue by hxlniada** [ant-design/ant-design#1070]
百度内部的项目，发现访问字体的时候403 forbidden，
请问有什么方法通过么？

**Comment by afc163** [comment]
字体是托管在 http://iconfont.cn/ 上的，公网可用。是否网络环境有限制？

**Comment by hxlniada** [comment]
不是，我就是把host配成xx.baidu.com。就不行了

**Comment by afc163** [comment]
看下网络请求是否有错误，控制台是否有字体文件跨域相关的报错。

**Comment by afc163** [comment]
![](https://os.alipayobjects.com/rmsportal/CSkPlzpEEGsApgF.png)

**Comment by insekkei** [comment]
已经下载到本地使用...

**Comment by afc163** [comment]
@hxlniada 可以先本地部署。http://ant.design/docs/resource/download

**Comment by afc163** [comment]
本地部署 iconfont 可参考这个例子：https://github.com/ant-design/antd-init/tree/7c1a33cadb98f2fd8688fe527dd7f98215b9bced/examples/local-iconfont

**Comment by afc163** [comment]
alicdn 对百度域做了访问限制，先按本地部署来解决。

**Comment by someok** [comment]
这个其实是因为字体图标的 url 采用的前缀是 //at.xxx

可以创建一个开发环境下的 less：

@import "~antd/style/index.less";

@import "custom.less";

@icon-url: "http://at.alicdn.com/t/font_1452596235_7047422";

**Comment by fengmk2** [comment]
尴尬。。。

**Comment by Flourad** [comment]
在http://ant.design/docs/resource/download下载web font放在项目目录下引用之后，怎么在代码里引用图标？按照原来的方式这样<Icon type="search"/>，图标无法显示？

**Comment by Dafrok** [comment]
alicdn除了百度域还对别的域做限制吗……最好有个black list 以免耽误不必要的时间排查此类问题

**Comment by afc163** [comment]
这个我们也不了解。。。

**Comment by evilemon** [comment]
![image](https://cloud.githubusercontent.com/assets/13042865/17736251/4c661a6e-64b9-11e6-8c04-85c7bf80fe89.png)
还真是对百度域拦截了

**Comment by yankun01** [comment]
我累个去。。。。

**Comment by a-jie** [comment]
使用StringReplacePlugin，就可以一步绕过吧

{ 
        test: /\.(css|less|js|jsx)$/,
        loader: StringReplacePlugin.replace({
          replacements: [
            {
              pattern: new RegExp('https://at.alicdn.com/t/','ig'),
              replacement: function (match, p1, offset, string) {
                 return '/assets/fonts/';
              }
          }
        ]})
      }
