### ISSUE TITLE
Ant Design Icons not work in IE 11

### ISSUE THREAD

**Issue by lidongbest5** [ant-design/ant-design#10700]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.5

### Environment
IE11 version:11.0.9600.17501

### Reproduction link
[https://ant.design/components/icon/](https://ant.design/components/icon/)

### Steps to reproduce
Open official document link in IE11, the icons did not display

### What is expected?
icons display well

### What is actually happening?
icons did not display

![image](https://user-images.githubusercontent.com/2869676/40697395-964e155c-63fc-11e8-93da-0c61103dac3f.png)

**Comment by afc163** [comment]
![](https://gw.alipayobjects.com/zos/rmsportal/VTKwfGVGYhOzCXJYeLzI.png)

It works, please check your network.
