### ISSUE TITLE
custom header in Transfer component or can showSelect in every transfer header

### ISSUE THREAD

**Issue by CeleKing** [ant-design/ant-design#10709]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
add api to make transfer title render other antd design component like Select, Icon, 
e.g select items in A or B group transfer to  C or D group...

### What does the proposed API look like?
showSelect = true

**Comment by afc163** [comment]
It is hard to understand your requirement

**Comment by CeleKing** [comment]
add api to make transfer title render other antd design component like Select, Icon,

**Comment by picodoth** [comment]
something looks like this:
`
      <Transfer
        dataSource={[
                key: '1',
                title: 'title', // => being able to change to Select or an Icon
                description: '1',
                chosen: true,
        ]}
        showSearch
        filterOption={this.filterOption}
        targetKeys={this.state.targetKeys}
        onChange={this.handleChange}
        render={item => item.title}
      />
`

**Comment by afc163** [comment]
```jsx
title: <div>whatever you want to put in</div>
```

**Comment by hungpurdie** [comment]
I don't know how to insert select is shown on each column (It's looks like property `search=true`).
but can you it as Table API.
It looks like this: 
```
const leftTableColumns = [
  {
    dataIndex: "address",
    title: "Address",
    filters: [
      {
        text: "London",
        value: "London",
      },
      {
        text: "New York",
        value: "New York",
      },
    ],
    onFilter: (value, record) => record.address.indexOf(value) === 0,
  },
];
```
