### ISSUE TITLE
表单中的选择器Select，mode为multiple，初始值为null时，会显示一个空的已选项

### ISSUE THREAD

**Issue by kylin** [ant-design/ant-design#10711]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
MacOS Chorm

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://82kynz39l2.codesandbox.io/)

### Steps to reproduce
设置表单多选模式的Select字段初始值为null

### What is expected?
初始值为null时，不显示空的已选项

### What is actually happening?
显示空的已选项

**Comment by kylin** [comment]
初始值为[]时，显示正常

**Comment by yesmeck** [comment]
预期行为，多选的值必须为数组
