### ISSUE TITLE
antd missing dependency on immutable library

### ISSUE THREAD

**Issue by uberolerass** [ant-design/ant-design#10710]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
N/A

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
1) Add `antd` to package.json
2) Do `npm/yarn install`

### What is expected?
No warning during package installation

### What is actually happening?
Warning is appearing during package install: `warning "antd > rc-editor-mention@1.1.6" has unmet peer dependency "immutable@^3.7.4".`

---
`antd` depends on `rc-editor-mention` which has a peer dependency on `immutable`. Thus `antd` should also depend (directly) on` immutable`.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8625#issuecomment-363531156

@megawac

**Comment by uberolerass** [comment]
@megawac I don't know the internals of `rc-editor-mention`. I assume the library has its dependencies in order. 

Normally peer dependencies are used if the containing library is a plugin or similar to the one it "peer depends" on. In this case `rc-editor-mention` should this be a plugin to `immutable`. If it uses `immutable` inside like calling it's functions it should be a standard dependency.

This might be an issue with `rc-editor-mention`. It sounds weird that it should be a plugin to `immutable`. Nevertheless, from the perspective of `antd` it should obey the dependency invariants of the packages it uses no matter if they are wrong or not.

**Comment by yesmeck** [comment]
https://github.com/react-component/editor-mention/issues/26

**Comment by ztplz** [comment]
Close it for It has already been fixed in https://github.com/react-component/editor-mention/pull/31.
