### ISSUE TITLE
Create a form.getFieldDecorator  wrapped component did't fire onChange event when the bound field's value first changed

### ISSUE THREAD

**Issue by BarryYan** [ant-design/ant-design#10714]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnw9p3jy33)

### Steps to reproduce
1. 在链接的例子中, 上传图片
2. 查看 console, 发现第一次传过来的值是图片的 路径, 没有触发getFieldDecorator 添加的 onChange  事件
3. 打断点, 发现 
![image](https://user-images.githubusercontent.com/8463435/40759869-83964c70-64c6-11e8-896e-8555fb699102.png)
![image](https://user-images.githubusercontent.com/8463435/40759883-93087746-64c6-11e8-96c4-261aecd141c8.png)
![image](https://user-images.githubusercontent.com/8463435/40759900-a9525576-64c6-11e8-9864-c05d3d3f31d4.png)
其实第三张图中 `idCardImg` 的 `value`  值是期望的正确结果, 但是因为 `onValuesChange` `undefiend`, 所以直接把第一张图中的 `value`  到最后赋给了 `idCardImg`, 导致报错.
如果没有在 `Upload`  组件属性 `fileList={fileList}`, 则不会报错, onChange  也会执行, 但是需要自己去维护一个 state;
第一次没触发 `onChange`, 并且返回的 `value`  是图片路径  
![image](https://user-images.githubusercontent.com/8463435/40760150-fc9c7ff8-64c7-11e8-9aa4-b29fa7f37c89.png)
第二次返回的值是正常的, 并且触发了 `onChange`
![image](https://user-images.githubusercontent.com/8463435/40760175-144b7e2e-64c8-11e8-93ce-3bc9194d754c.png),
想知道为什么第一次没有触发 `onChange`

4. 查看了 [`rc-form` 的源码](https://github.com/react-component/form/blob/master/src/createBaseForm.js#L89), 发现 `onValuesChange` 是创建 Form.create()  装饰器的一个 options

### What is expected?
正常触发 onChange ,  返回正确的值

### What is actually happening?
报错

---
提交表单的时候, 同时提交上传的图片

**Comment by afc163** [comment]
https://codesandbox.io/s/stupefied-sutherland-ydv3n

仔细看看官网例子：https://3x.ant.design/components/form-cn/#components-form-demo-validate-other
