### ISSUE TITLE
TimePicker should accept `24:00` value

### ISSUE THREAD

**Issue by newraina** [ant-design/ant-design#10719]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when format="HH:mm", the latest time you can choose is 23:59, one second less than the real latest time.

### What does the proposed API look like?
when format="HH:mm", I can select 24:00 as value.

**Comment by yesmeck** [comment]
https://github.com/react-component/time-picker/issues/95
