### ISSUE TITLE
incopatible type with typescript v2.9.1

### ISSUE THREAD

**Issue by saostad** [ant-design/ant-design#10729]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
bowser 3.5.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://jnw46698m3.codesandbox.io/)

### Steps to reproduce
npm start

### What is expected?
compile successfully

### What is actually happening?
Error: 
antd\lib\_util\type.d.ts
(8,63): error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to
type 'string'.
    Type 'number' is not assignable to type 'string'.

**Comment by webKity** [comment]
me too

**Comment by silverbolt** [comment]
you can use typescript@2.8.4 before fixed

**Comment by karol-majewski** [comment]
#10730 will fix the issue for Ant consumers.

To ensure full compliance within the project one additional thing has to be taken care of: trailing commas in rest parameters. TypeScript 2.9 doesn't allow them, but there are to be found in the repository. This will require a change in this upstream repository:

https://github.com/ant-design/antd-tools/blob/master/lib/tslint.json#L93-L99
