### ISSUE TITLE
For InputNumber, if some chars(like %，°) appended to the end of the value by formatter, the delete key on the keyboard will not work when the caret is at the end of the input

### ISSUE THREAD

**Issue by zengfenfei** [ant-design/ant-design#10722]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
all

### Reproduction link
[https://ant.design/components/input-number/](https://ant.design/components/input-number/)

### Steps to reproduce
1. Go to https://ant.design/components/input-number/.
2. Scroll to section [Examples - Formatter].
3. Place a caret at the end of the second input.
4. Press delete(or backspace) key on the keyboard.

### What is expected?
The last digit will be deleted

### What is actually happening?
Nothing is deleted

**Comment by picodoth** [comment]
@zengfenfei I can't reproduce according to your steps. Can you provide a gif or image?

**Comment by zengfenfei** [comment]
Place the caret to the position indicated by the screenshot, and press delete key:
![image](https://user-images.githubusercontent.com/773310/40878011-0046011e-66bd-11e8-9197-faa72683c136.png)
