### ISSUE TITLE
希望Progress可以增加修改颜色的API

### ISSUE THREAD

**Issue by JameJJ** [ant-design/ant-design#10725]
### What problem does this feature solve?
Progress目前定位表示的是进度多少，但是在一些场景中，比如有一系列分数段的显示，可以使用Progress表示不同等级的显示，在这样的场景中目前的三种状态是无法满足的。

### What does the proposed API look like?
```js
 <Progress type="circle" percent={75}  strokeColor="" trailColor="" />
```
### API

|    属性     | 说明     |             类型                |   默认值 |
| ------------ |---|------------------------------- |------------------------------- |
| strokeColor |  进度条颜色     | `string` |    #108ee9    |
| trailColor     |  圆环的底色    |   `string`      |        #f3f3f3       |

**Comment by yesmeck** [comment]
@JameJJ 来个 PR?

**Comment by JameJJ** [comment]
@yesmeck 😂我试试提一下

**Comment by JameJJ** [comment]
@yesmeck 如果增加修改颜色的API，感觉会和status的功能有重复的层面

**Comment by yesmeck** [comment]
`strokeColor` 的优先级高于 `status`

**Comment by calldream** [comment]
我看到progress.js文件的确的被更改了，但是参数并没有往下一曾继续传递，好像优先级不够，最后颜色方案并没有执行

**Comment by yesmeck** [comment]
@calldream 单独提个 issue
