### ISSUE TITLE
Upload 组件 预览 支持 video

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#10723]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
预览支持video

### What does the proposed API look like?
isVideo

**Comment by afc163** [comment]
Could you send us a PR for this feature?

**Comment by xgj1988** [comment]
@afc163  What's PR 。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pulls

**Comment by xgj1988** [comment]
It's hard for me .
