### ISSUE TITLE
弹出层中的新建表单初始值错误

### ISSUE THREAD

**Issue by weidapao** [ant-design/ant-design#10724]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
antd3.5.4 win7 chrome

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
1.点击按钮，弹出modal框
2.输入内容后，点击取消
3.再次点击按钮，modal框显示上一次输入的值。

### What is expected?
正确结果：显示定义好的初始值

### What is actually happening?
modal框显示上一次输入的值。

---
表单设置好初始值的情况下，这种操作会使显示的值不正确。

**Comment by yesmeck** [comment]
`<Model destroyOnHide />`
