### ISSUE TITLE
Pagination显示页数的一个问题

### ISSUE THREAD

**Issue by chendonghai1982** [ant-design/ant-design#10732]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在有一个问题，比如我总记录数有299026条，然后分页显示为1,2,3,4,5 ...  14952 现在有的员工不懂，直接点14952页，直接把服务器卡掉了，而不会去点那个三个点...,所以我希望能不能多显示几页数字比如:1,2,3,4,5,6,7,8,9,10由人工去控制 

### What does the proposed API look like?
希望能增加一个API自己控制显示多少页数字在上面，而不是默认5个在上面

**Comment by chendonghai1982** [comment]
晕，都看不懂英文啊

**Comment by afc163** [comment]
直接点14952页为啥会挂掉服务器。

**Comment by yutingzhao1991** [comment]
嗯，那可以加一个 `maxShowPage` 默认是 5。

但是这个还是无法解决你的最后一页的问题，那个需要你的接口做优化。理论上也可以加一个 `showFisrtAndLastQuickJumper`解决，但是加在组件上的理由似乎不够充分。

**Comment by afc163** [comment]
感觉 antd 不应该解决这样的问题，建议排查后端性能问题。

**Comment by codeArvin** [comment]
https://codesandbox.io/s/antd-pagination-7b536?file=/Pagination.js
加了个只展示连续页码的功能
