### ISSUE TITLE
mapPropsToFields not working in nested fields

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#10737]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
macOS, chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2o3043woyy)

### Steps to reproduce
decorator 'userName.a' input value is undefined

### What is expected?
decorator 'userName.a' input value should  'iam a'

### What is actually happening?
decorator 'userName.a' input value is undefined

**Comment by afc163** [comment]
https://codesandbox.io/s/32pv15x83m
