### ISSUE TITLE
Can we have a datepicker without input?

### ISSUE THREAD

**Issue by iamfoxuriel** [ant-design/ant-design#10731]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5zzx8wk9wp)

### Steps to reproduce
to imply: Popup a datepicker after I click a button.

### What is expected?
What I want to implement is:
Popup a datepicker after I click a button.

### What is actually happening?
1. I try Datepicker, it's binded with an input.
failed!(which I don't want a Input)

2. then I turn to use Calendar, but I got 'month/year'mode selection, which I don't want them to show up
![image](https://user-images.githubusercontent.com/1312897/40773603-fc3a944a-64f5-11e8-8415-479183f7033e.png)
failed!(which I don't want mode selection)
and the 'year' mode Calendar in  Popover is going to larger

is it any way I can utilize DatePicker/Calender to imply my requirement?

**Comment by yesmeck** [comment]
You can use rc-calendar directly http://react-component.github.io/calendar/examples/antd-calendar.html
