### ISSUE TITLE
modal弹框和tab切换框键盘操作可配置

### ISSUE THREAD

**Issue by taikongfeizhu** [ant-design/ant-design#1073]
目前modal弹框和tab切换时候按下esc键和左右键也是可以操作的，但是有的时候易造成误操作或者无需键盘操作需求，能否增加一个类似bootstrap的modal中的keybord=ture/false选项，可自定义是否启用键盘快捷操作。

**Comment by afc163** [comment]
暂不支持~ 感谢建议

不过如果很需要这个功能，可以去给 rc 组件 pr ~
