### ISSUE TITLE
Select组件下的Option组件增加控制是否显示的接口

### ISSUE THREAD

**Issue by Zhangsw02** [ant-design/ant-design#10733]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我知道一个Option不可用的时候可以设置它的disabled属性，但是产品说不可用Option要去掉。现在问题是，如果过滤掉这个不可用Option，Select的value为这个Option的值时，会只显示一个id， 因为没有了这个Option。所以我希望这个Option还在，只是视觉上小时，比如display:none.

### What does the proposed API look like?
<Option disappeared={condition}></Option>

**Comment by yesmeck** [comment]
> 现在问题是，如果过滤掉这个不可用Option，Select的value为这个Option的值时，会只显示一个id

Try `labelInValue`.
