### ISSUE TITLE
Modal Use drag and drop to zoom?

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#10735]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
the Modal of width and height is set fixed,but sometimes of big screen I want drag enlarge.

### What does the proposed API look like?
```javascript
<Modal
          title="Basic Modal"
          visible={this.state.visible}
          onOk={this.handleOk}
          onCancel={this.handleCancel}
         dragZoom
        >
          <p>Some contents...</p>
          <p>Some contents...</p>
          <p>Some contents...</p>
</Modal>
```

**Comment by afc163** [comment]
Won't support.
