### ISSUE TITLE
Select选择器 带搜索框功能不能保存自定义输入

### ISSUE THREAD

**Issue by 909288037** [ant-design/ant-design#10740]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
Chrome  65.0.3325.181

### Reproduction link
[http://ant.design/components/select-cn/#components-select-demo-search](http://ant.design/components/select-cn/#components-select-demo-search)

### Steps to reproduce
filterOption=true

### What is expected?
自定义输入能够保留不被清空

### What is actually happening?
自定义输入失去焦点时，被清空。

**Comment by afc163** [comment]
You should use https://ant.design/components/select-cn/#components-select-demo-combobox instead of search select.
