### ISSUE TITLE
Consider an issue that is not an answer as an answer. Does antd's staff have to be so sloppy?

### ISSUE THREAD

**Issue by relax-admin** [ant-design/ant-design#10744]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The so-called answer you gave, almost everyone's reply is opposed, and all the likes of the comments are unresolved.
The answer you gave is：https://github.com/ant-design/ant-design/issues/8668

### What does the proposed API look like?
please open issue：https://github.com/ant-design/ant-design/issues/10742

**Comment by afc163** [comment]
Don't spam.

I just reopen #8668 and you can discuss solutions and workaround in it.

The best way to resolve your problem is sending us PR with complete test cases or demo.

**Comment by relax-admin** [comment]
In fact, when you closed the post, it did not tell you that you had reopened another issue

**Comment by afc163** [comment]
That is my negligence

**Comment by relax-admin** [comment]
It's ok
