### ISSUE TITLE
需求是点击按钮使Modal组件弹出来，里面的Input组件自动获取焦点

### ISSUE THREAD

**Issue by relax-admin** [ant-design/ant-design#10742]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如填写表单元素，当Modal组件弹起时Input自动获取焦点，不用再手动点击获取焦点，这样可以节约时间。

### What does the proposed API look like?
就是Input组件的一个配置项，比如

**Comment by relax-admin** [comment]
这是之前讨论过很多的问题，不幸的是，"antd": "^3.2.2" 这个版本的却无法使用 <Input autoFocus />

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/8668

**Comment by relax-admin** [comment]
@yesmeck

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/8668#issuecomment-394071570
