### ISSUE TITLE
Unable to close the select menu, when checkbox is used inside select option

### ISSUE THREAD

**Issue by acamogh** [ant-design/ant-design#10757]
I'm Unable to close the select menu item when I try to use checkbox inside it  . The behavior is random does not happen always. 

[https://codesandbox.io/s/6w4wkol4kz](https://codesandbox.io/s/6w4wkol4kz) 

Ways to find out the issue.
1) click on checkbox
2) click on element name 
3) again click on checkbox
4) now try to click outside menu options, menu does not close.

**Comment by zombieJ** [comment]
Hi, pls use stopPropagation on checkbox since it will affect popup close check currently:  
https://codesandbox.io/s/43473r216x

ref: https://github.com/react-component/trigger/pull/86
