### ISSUE TITLE
upload 组件能否自定义loading的展示效果

### ISSUE THREAD

**Issue by minpuff** [ant-design/ant-design#10751]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
listType="picture-card"时，如果图片过大或网络比较慢时，这时候会展示出较长时间的loading效果，而这loading效果和整体的页面风格不太搭配，希望能够提供一个属性，可以让开发者自己设计

### What does the proposed API look like?
```javascript
<Upload
   action="//jsonplaceholder.typicode.com/posts/"
   listType="picture-card"
   fileList={fileList}
   onPreview={this.handlePreview}
   onChange={this.handleChange}
   loadingButton={string|ReactNode}
>
    {fileList.length >= 3 ? null : uploadButton}
</Upload>
```

**Comment by afc163** [comment]
Try `showUploadList={false}` then create your own upload files list.

**Comment by minpuff** [comment]
我指的是红框中的loading效果，确定能通过 showUploadList={false} 实现？![image](https://user-images.githubusercontent.com/22900082/40885414-54c49980-6758-11e8-9916-7eee90f666d2.png)

![image](https://user-images.githubusercontent.com/22900082/40885436-94c68e8a-6758-11e8-9e97-e8f7b001c480.png)
