### ISSUE TITLE
MonthPicker年份选择失效

### ISSUE THREAD

**Issue by kaiwen1811** [ant-design/ant-design#10758]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
mac  chrome 

### Reproduction link
[http://p9s53qmbl.bkt.clouddn.com/QQ20180604-104207-HD.mp4](http://p9s53qmbl.bkt.clouddn.com/QQ20180604-104207-HD.mp4)

### Steps to reproduce
<MonthPicker defaultValue={moment('2015/01','YYYY/MM')} format={'YYYY/MM'} />

### What is expected?
月份选择框可以选择年份

### What is actually happening?
现在可以选择月份，但是在选择年的时候，出来的是之前的

**Comment by jymlbei** [comment]
@ant-design-bot 该年份时间段选择，需要两次选择，年份才生效的问题出现于react和react-dom版本为^15.3.2中

**Comment by zhenghaiyang** [comment]
You can try 3.1.0 instead.
@kaiwen1811

**Comment by afc163** [comment]
Try react@16.x

**Comment by jymlbei** [comment]
react@16.x is no problem，but in React@15.3.2，antd@3.1.0 or antd@3.6.1 , the problem still exists

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/9334

**Comment by zombieJ** [comment]
过去的代码是从 `value` 改成了 `defaultValue`，唔...
ref: https://github.com/react-component/calendar/commit/a45f543a008f68f3392b055f6bb1ef0f39bc628c#diff-bf02fe778785099e5c2bea1895305609R76

**Comment by zhenghaiyang** [comment]
@kaiwen1811  
My project 
React.js  15.4.1
antd 3.1.0

antd version,You can try to change it  3.1.0 
l think is ok
