### ISSUE TITLE
button in column triggers expandRowByClick  

### ISSUE THREAD

**Issue by riwu** [ant-design/ant-design#10769]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4lv6x25x10)

### Steps to reproduce
Click on the "edit" button.

### What is expected?
The row should not be expanded.

### What is actually happening?
The row gets expanded.

---
The use case is to open a Modal when "edit" is clicked. I want to retain the ability to expand the row by clicking anywhere (except the "edit" button).

**Comment by afc163** [comment]
https://codesandbox.io/s/vy15por40
