### ISSUE TITLE
Column render no difference between `text` and `record` parameters

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#10768]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oj29qyj15z)

### Steps to reproduce
Open console. Output of `console.log(text, record)` is the same.

### What is expected?
`text` should be different from `record` otherwise it's redundant

### What is actually happening?
`text` and `record` are exactly the same.

**Comment by afc163** [comment]
Briefly,`text` === `record[dataIndex]`.
