### ISSUE TITLE
antd upload withCredentials not work

### ISSUE THREAD

**Issue by ywww** [ant-design/ant-design#10763]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.13

### Environment
win10 chrome

### Reproduction link
[http://192.168.25.21:8080/testPlugin](http://192.168.25.21:8080/testPlugin)

### Steps to reproduce
                <Upload
                    action="http://192.168.25.21:8887/upload"
                    multiple={false}
                    withCredentials={true}
                    showUploadList={true}
                    defaultFileList={defaultFileList}
                    onChange={this.onChange}>
                    <Button>
                        <Icon type="upload"/> Upload
                    </Button>
                </Upload>

### What is expected?
带cookie

Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cache-Control: no-cache
Connection: keep-alive
Cookie: OUTFOX_SEARCH_USER_ID_NCOO=1113520183.529224; ___rl__test__cookies=1527596869525; token=A68QrNRaYtcCyArJl7E17Bal29XvxYIrqQZIs%2FnyG9XuAYI2a3r8s%2FA9XGBaZ7fZk7wXDLv3Wl8VSbMBMxSY%2BIpgf1k2v%2Bvb2QGb%2FnT7NTAQxrICqokPtCnHhUvxduoVVlKNLCb3z25tLWWWQnuTJ1JjqL4sIwTxQ6kYaaQ%2FLDQ%3D; connect.sid=s%3AQhjqT8o4vTZiwcoSd0pDyQ1y1dXBPUin.HJyc5fks7HjMo7Xn3p1nqTdAfqjCC1t1MSmvBOOjTzw
Host: 192.168.25.21:9090
Pragma: no-cache
Referer: http://192.168.25.21:8080/app/11
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

### What is actually happening?
Accept: */*
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Access-Control-Request-Headers: x-requested-with
Access-Control-Request-Method: POST
Cache-Control: no-cache
Connection: keep-alive
Host: 192.168.25.21:8887
Origin: http://192.168.25.21:8080
Pragma: no-cache
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36

**Comment by ywww** [comment]
谢谢, 已经解决了, 是服务端设置的问题

        if (request.getMethod().equalsIgnoreCase("OPTIONS")) {
            response.setStatus(200);
            return true;
        }


参考 

https://github.com/ant-design/ant-design/issues/2373

**Comment by afc163** [comment]
Please close issue if you resolved the problem.
