### ISSUE TITLE
TreeSelect in  ie9,ie10,ie11 ，expand parent's menu，scrollTop=0

### ISSUE THREAD

**Issue by zhangjingge** [ant-design/ant-design#10765]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
win7、 ie9,ie10,ie11

### Reproduction link
[https://shimo.im/docs/7NqRHIrHDRYkKGFF/](https://shimo.im/docs/7NqRHIrHDRYkKGFF/)

### Steps to reproduce
https://shimo.im/docs/7NqRHIrHDRYkKGFF/

### What is expected?
TreeSelect.scrollTop = now

### What is actually happening?
TreeSelect.scrollTop = 0

**Comment by afc163** [comment]
建议有空阅读下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 和 [如何有效地报告 bug](https://www.chiark.greenend.org.uk/%7Esgtatham/bugs-cn.html)。
