### ISSUE TITLE
【建议】Radio 附属的Label上加cursor: pointer

### ISSUE THREAD

**Issue by JonneyYan** [ant-design/ant-design#1076]
这样和HTML默认的交互就一致了

- The version of antd( 0.12.4):

**Comment by afc163** [comment]
Html 默认的交互，label 不是 `cursor: pointer` 的哦。

http://www.w3school.com.cn/tiy/t.asp?f=html_label

**Comment by JonneyYan** [comment]
哦，抱歉，是我记错了，是`bootstrap`的默认样式。

**Comment by afc163** [comment]
Bootstrap 里也只有 Checkbox 和 Radio 的 label 是 `cursor: pointer`。

这里先改掉 Radio 的，Checkbox 的要在 #1029 里一起改。
