### ISSUE TITLE
DatePicker.RangePicker 快捷键不能用

### ISSUE THREAD

**Issue by shuaiboy** [ant-design/ant-design#10764]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.12.6

### Environment
浏览器：Chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k3lqm1v5n3)

### Steps to reproduce
使用DatePicker.RangePicker组件
输入框获取焦点，出现选择日期框， 鼠标移动到上一年图标按钮， 出现按钮说明和快捷键， 尝试使用快捷键， 失败。

### What is expected?
鼠标移动到上一年，下一年， 上个月， 下个月图标上， 出现的提示快捷键可以用

### What is actually happening?
鼠标移动到上一年，下一年， 上个月， 下个月图标上， 出现的提示快捷键不可以用

---
DatePicker 组件提示的快捷键是可以用的， 有用最新的版本测试也是有问题

**Comment by hqzh** [comment]
试了下你的代码,没遇到这个问题.

**Comment by zombieJ** [comment]
fixed in `rc-calendar` 9.6.2.
