### ISSUE TITLE
Select crashes after option list is updated

### ISSUE THREAD

**Issue by mocheng** [ant-design/ant-design#10774]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
react v16.2.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9z8x14l43w)

### Steps to reproduce
1. Click to check "Foo" checkbox. This should update Option list to be "Foo1" and "Foo2".
2. Select "Foo1" in select menu;
3. Unselect "Foo1" in select menu;
4. Uncheck "Foo" checkbox.
5. Check "Bar" Checkbox. This should update Option list to be "Bar1" and "Bar2"
6. Check Select input to show dropdown menu

### What is expected?
The dropdown menu is shown.

### What is actually happening?
It crashes with below error:
Invariant Violation
Unable to find node on an unmounted component.

---
This is reproduced against React v16.2.0, but not in v16.4.0.

**Comment by huijian3139** [comment]
I also met the same problem, but you succeed in reproduce it in sandbox, that's awesome!

**Comment by afc163** [comment]
Try reinstall node_modules

**Comment by mocheng** [comment]
This is not a issue about node_modules. It is an issue about antd behavior in React v16.2.0.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/commit/34969e31ed3ddcf4309bf3dc33b9f271cd2aef41

**Comment by afc163** [comment]
<img width="599" alt="image" src="https://user-images.githubusercontent.com/507615/41273701-15405faa-6e4d-11e8-902a-764b9c4f8467.png">
