### ISSUE TITLE
form验证 getFieldDecorator 里面的rules 里面的验证提示信息message如何自定义样式 ，我要扩展一下提示样式

### ISSUE THREAD

**Issue by jaunemmechine** [ant-design/ant-design#10775]
{...formItemLayout}
                    label={(
                      <span>
                        联系人邮箱&nbsp;
                      </span>
                    )}
                  >
                    {getFieldDecorator('mail', {
                      rules: [{ required: true, message: '请填写你的邮箱', whitespace: true},{
                        type: 'email', message: '邮箱地址不正确!',
                      }]
                    })(
                      <Input placeholder="填写邮箱" />
                    )}
          </FormItem> 
          
          
          message如何扩展成比如我想修改成tip 小三角 的提示方式怎么修改

**Comment by zjsyxrf** [comment]
message可以是ReactNode
