### ISSUE TITLE
Popover add  a new API

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#10777]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Whether to close the modal dialog when the mask (area outside the modal) is clicked!
if Won't support. how can i do just onClick will close?thank you.

### What does the proposed API look like?
```javascript
<Popover
            maskClosable={false}
            content={<BaiduMap
              style={{ width: 500, height: 500 }}
              center={postion}
              zoom={18}
            >
              <MarkerLayer data={[item]} />
            </BaiduMap>
            }
            title={<a onClick={hide}>关闭</a>}
            trigger='click'
            visible={visible}
            onVisibleChange={handleVisibleChange}
          >
            <a>{text}</a>
          </Popover>);
```
maskClosable={false} ,like Modal

**Comment by afc163** [comment]
It is a intented behavior.
