### ISSUE TITLE
Can value of TreeSelect.TreeNode support type `Number`

### ISSUE THREAD

**Issue by linzebin** [ant-design/ant-design#10776]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
macOS 10.13.4 & Chrome 67.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/84vxj2wk90)

### Steps to reproduce
link to https://codesandbox.io/s/84vxj2wk90, open console of browser

### What is expected?
warning clear

### What is actually happening?
Warning: Failed prop type: Invalid prop `value` of type `number` supplied to `TreeNode`, expected `string`.

---
Value of TreeNode always the same as id

**Comment by afc163** [comment]
The warning message is quite obvious.

```diff
- value={i}
+ value={i.toString()}
```
