### ISSUE TITLE
ant-design Table when delete a row with some data is '', Table width will be change 

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#10779]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
Win 10 17134； Chrome 65.0.3325.181（正式版本）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/507p0pwk5n)

### Steps to reproduce
When I add a row； 
const newData = {
      key: count,
      name: `Edward King ${count}`,
      age: "", /* this is '' ! important */
      address: "111111111"
 }; 
then I delete other row, the new row's width will be change

### What is expected?
Width not  change

### What is actually happening?
Table's width change

**Comment by afc163** [comment]
You have to fix width of column if you need keep layout whatever the content is.
