### ISSUE TITLE
Spin: auto custom indicator size 

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#10786]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
allows correct sizing spin indicator (large/normal/small) if Icon component used as indicator

### What does the proposed API look like?
it is just CSS definitions (translate to correct less):
.ant-spin .anticon.ant-spin-dot: {font-size: 20px}
.ant-spin.ant-spin-lg .anticon.ant-spin-dot: {font-size: 30px}
.ant-spin.ant-spin-sm .anticon.ant-spin-dot: {font-size: 14px}

**Comment by afc163** [comment]
PR is welcome~
