### ISSUE TITLE
一个页面同时展现两个Popover

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#10780]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
版本 66.0.3359.117（正式版本） （64 位）

### Reproduction link
[https://codepen.io/hqzh/pen/RJaVXm?&editors=001](https://codepen.io/hqzh/pen/RJaVXm?&editors=001)

### Steps to reproduce
一个页面同时展现两个Popover,共用一个state控制,点击content部分导致Popover隐藏了

### What is expected?
点击content部分Popover不隐藏,仅仅点击onClick={this.hide}回调隐藏.

### What is actually happening?
点击content部分导致Popover隐藏了

**Comment by afc163** [comment]
You should use two different state to control each Popover visible.
