### ISSUE TITLE
一个页面同时展现两个Popover(续)

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#10782]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
版本 66.0.3359.117（正式版本） （64 位）

### Reproduction link
[https://codepen.io/hqzh/pen/RJaVXm?editors=0010](https://codepen.io/hqzh/pen/RJaVXm?editors=0010)

### Steps to reproduce
https://github.com/ant-design/ant-design/issues/10780,你告诉我使用两个不同的state控制,上面重现链接我试了不行,

### What is expected?
我的业务需求是点击任何一个按钮,同时弹出两个Popover,所以走了同一个回调.但是我觉得点击content部分两个Popover不应该隐藏.

### What is actually happening?
点击content部分两个Popover隐藏.

**Comment by hqzh** [comment]
@afc163

**Comment by hqzh** [comment]
@afc163 就是这两个按钮,我点击任何一个按钮,两个按钮的气泡卡片都出来,但是点击两个气泡卡片的内容不要致使两个气泡卡片关闭,我这么说不知您明白没

**Comment by afc163** [comment]
这是你的实现需求，具体产品上为啥要点击一个按钮弹出两个卡片呢？

**Comment by hqzh** [comment]
@afc163 
![pp](https://user-images.githubusercontent.com/26128706/40963887-3848cd82-68dc-11e8-8795-17986bb9f113.png)
想知道两个点的差距......

**Comment by hqzh** [comment]
@afc163 然后我点击地图两个气泡卡片就消失了,不知道怎么样可以不消失

**Comment by afc163** [comment]
感觉这种需求应该展开同一个地图，然后画两个点，看着更直观一些。

**Comment by afc163** [comment]
现在有透传这个属性，你可以这样来实现：https://codepen.io/afc163/pen/MXyrPN?editors=0010

https://github.com/react-component/trigger/blob/c311a0ed3e0f91115442924cfebc815aff4a327d/src/index.js#L288

---

不过还是觉得这个交互很奇怪。
