### ISSUE TITLE
Spin: default custom indicator

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#10787]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
automatically sets default custom indicator to all spins (Except those implicitly got other one via props)

### What does the proposed API look like?
Static function of Spin: Span.setDefaultIndicator(reactElement)
usage:
Spin.setDefaultIndicator(&lt;Icon type='loading'/&gt;);

**Comment by codelegant** [comment]
It this can affect the table loading?
