### ISSUE TITLE
Ant design for Select showSearch Failure！

### ISSUE THREAD

**Issue by xiaohongwang** [ant-design/ant-design#10789]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.12.8

### Environment
win10/google

### Reproduction link
[http://xiaohongwangs@163.com](http://xiaohongwangs@163.com)

### Steps to reproduce

Ant design for Select showSearch Failure！
Can showSearch in the Select component query only the value in Option？

### What is expected?
The Select Option provides the search name function

### What is actually happening?
The Select Option can only search for value

---
联系邮箱:xiaohongwangs@163.com

**Comment by yesmeck** [comment]
`filterOption`
