### ISSUE TITLE
Tooltip of ButtonGroup of disabled buttons does not disappear

### ISSUE THREAD

**Issue by crudo** [ant-design/ant-design#10795]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
Mac OSX 10.13.5, Google Chrome Version 67.0.3396.62 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zk51zxr05l)

### Steps to reproduce
Hover the button group and move the mouse bellow the buttons.

### What is expected?
Tooltip will disappear.

### What is actually happening?
Tooltip is still visible.

---
Related to https://github.com/ant-design/ant-design/issues/9581 and https://github.com/ant-design/ant-design/issues/9296

**Comment by afc163** [comment]
It is a bug of chrome you can look up in https://github.com/react-component/tooltip/issues/18 and https://github.com/facebook/react/issues/4251

We handle the `<Tooltip><Button disabled /></Tooltip>` situation by https://github.com/ant-design/ant-design/pull/4865. However there are many edge cases like your issue. It is hard to find perfect solution now.

**Comment by afc163** [comment]
That will be a workaround but lost the disabled cursor style.

**Comment by crudo** [comment]
Hm, you are right. But the cursor is smaller issue for me then the visible tooltip.

**Comment by afc163** [comment]
closing for no better solution now, you can trace https://github.com/react-component/tooltip/issues/18 for further information.
