### ISSUE TITLE
请问一下能否在以后的**所有组件**里都可以自己定义className？

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design#1079]
Hi, 我发现有些组件可以定义自己的className，但有些不行（比如`Button.Group`），我用的antd版本是`0.11.1`.  
请问一下能否在以后的**所有组件**里都可以自己定义className？类似像下面这样，谢谢

```
<Button.Group className="foo">
</Button.Group>
```

**Comment by afc163** [comment]
http://codepen.io/anon/pen/qZWqQJ?editors=001

Button.Group 是支持 className 配置的。

**Comment by zhaozhiming** [comment]
哦不好意思，我看错了，但还有一个问题，是不是现在antd的所有组件都支持className这种自定义样式的方法？谢谢

**Comment by afc163** [comment]
理论上应该大部分都要支持，目前没有排查。遇到有问题的，欢迎提 PR 或 issue ~
