### ISSUE TITLE
[Form] Allow to use 'updateFields'

### ISSUE THREAD

**Issue by fantua** [ant-design/ant-design#10797]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Already exist PR with this feature and I would like to receive some review/feedback to this. I believe this feature will be very helpful not only for me.

### What does the proposed API look like?
https://github.com/react-component/form/pull/165

**Comment by afc163** [comment]
`rc-form` will not accept new feature now, we provide a new https://github.com/react-component/field-form for antd 4.0: https://github.com/ant-design/ant-design/issues/16911
