### ISSUE TITLE
upload中选择文件，弹出文件选择框之后，再将文件拖拽进行上传，会导致浏览器崩掉，antd官网也有这个问题

### ISSUE THREAD

**Issue by Diamondjcx** [ant-design/ant-design#10799]
![image](https://user-images.githubusercontent.com/27531549/41013593-5ef6e368-6979-11e8-8ece-796e27fc10fb.png)

**Comment by 546200350** [comment]
i have the same problem

**Comment by qingming418** [comment]
请问最后怎么解决的？

**Comment by 546200350** [comment]
@qingming418 请卸载搜狗输入法或者更新

**Comment by qingming418** [comment]
神奇了
