### ISSUE TITLE
如何从 0.12 升级到3.x

### ISSUE THREAD

**Issue by Aladdin-ADD** [ant-design/ant-design#10809]
由于历史原因，我们内部有一些系统现在仍然使用的0.12版本，需要升级到3.x，

+ 哪里能看到各个版本之间的 breaking changes，升级指南
+ 能否有一些自动化的工具帮助升级，e.g. https://github.com/vuejs/vue-migration-helper

**Comment by Aladdin-ADD** [comment]
could someone reopen this issue?  
(sorry for not following the issue template :(

**Comment by afc163** [comment]
一步步来，先从 0.12 到 1 再到 2 再到 3，具体看 changelog，2.x 和 3.x 都有提供 codemod 或者 migration-helper。

**Comment by panlina** [comment]
@afc163 3.x有codemod吗？没有找到，只有https://github.com/ant-design/antd-codemod，是2.x的。
