### ISSUE TITLE
table组件点击单行选中怎么实现？

### ISSUE THREAD

**Issue by gejialun8888** [ant-design/ant-design#10805]
` <Table
                    columns={columns}
                    dataSource={con1.list}
                    onRow={(record,index) => {
                      return {
                        onClick:()=>{this.onRowClick(record,index)} 
                      }
                    }}
                    bordered={true}
                  />`
这个是目前代码，怎么实现单击行选中样式呢，类似hover放到每一行样式的效果

**Comment by mlf75** [comment]
请问楼主后面解决了吗
