### ISSUE TITLE
MonthPicker 组件  bug

### ISSUE THREAD

**Issue by zhendong1993** [ant-design/ant-design#10806]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
chrome  66

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
MonthPicker 组件 year 的快捷切换，如上一次点击的 是 2018， 在点击 2016 时，显示的还是 2018， 但去点击 2015 时，才会再次显示 2016 。

### What is expected?
year 快捷切换 正确显示

### What is actually happening?
year 快捷切换 显示的是上一次选中的结果

---
const { DatePicker } = antd;
const { RangePicker, MonthPicker } = DatePicker;

ReactDOM.render(
  <div>
    <MonthPicker renderExtraFooter={() => 'extra footer'} placeholder="Select month" />
  </div>
, mountNode);

**Comment by zhenghaiyang** [comment]
You can try 3.1.0（antdVersion）instead.
@zhendong1993

**Comment by afc163** [comment]
Try react@16.x

**Comment by zhendong1993** [comment]
Thank you

**Comment by panjiefeng** [comment]
The example in the Codepen is OK, but it still likes that. I use react@16.6.0 and antd@3.10.3. And I switch the antd to 3.1.0, it still doesn't work.
