### ISSUE TITLE
Ant design for RadioButton   Click  uncheck

### ISSUE THREAD

**Issue by xiaohongwang** [ant-design/ant-design#10807]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.12.8

### Environment
win10 google

### Reproduction link
[http://xiaohongwans@163.com](http://xiaohongwans@163.com)

### Steps to reproduce
RadioButton checked is true and can be unchecked if you click again

### What is expected?
RadioButton checked is true and clicking again will uncheck it

### What is actually happening?
RadioButton checked is true and clicking again is still checked

**Comment by afc163** [comment]
You can't click to uncheck a radio either, so we are better to pass it.

**Comment by ohhyunjin** [comment]
I'm showing the table with one data and a radio button in a modal and in the first time the radio button is not selected and I select one, then I close the modal and open it again and the radio button is still selected. Is there a way to clear the radio button selection when the modal closes?
