### ISSUE TITLE
TreeSelect在 ie9,ie10,ie11中使用的时候点击父级菜单展开或者关闭时组件滚动条回到顶部

### ISSUE THREAD

**Issue by zhangjingge** [ant-design/ant-design#10803]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
win7、 ie9,ie10,ie11

### Reproduction link
[https://shimo.im/docs/7NqRHIrHDRYkKGFF/](https://shimo.im/docs/7NqRHIrHDRYkKGFF/)

### Steps to reproduce
首先组件数据足够多可以出现滚动条（也可以设置高，但是去掉依旧有这种情况），滚动组件让滚动条离开顶部，然后点击父级菜单展开或者关闭都会造成滚动条回到顶部

### What is expected?
展开或者关闭父级菜单滚动条在目前位置不动

### What is actually happening?
展开或者关闭父级菜单滚动条回到组件顶部

---
页面form表单，弹窗form表单均有出现相同问题，Chrome正常，ie9-ie11均有问题

**Comment by zombieJ** [comment]
@zhangjingge , 能给个 codeSandbox 的重现不？你给的链接我没权限。

**Comment by zhangjingge** [comment]
@zombieJ 上面gif图片链接的权限我重新设置了
codeSandbox链接https://codesandbox.io/s/v6v0zlz545，但是win10的ie11没有重现问题，win7电脑装ie11的时候切换浏览器版本的时候显示的是edge版本（实际查询版本为ie11），公司win7的电脑打不开codeSandbox，win10和win7电脑的ie10都打不开codeSandbox，我再找找问题吧，非常感谢

**Comment by zombieJ** [comment]
@zhangjingge，
修复这个问题会有些影响，这个issue我先开着。

**Comment by zhangjingge** [comment]
@zombieJ 嗯好的
关了是因为我没办法复现这个bug，我按照antd官网的 https://ant.design/docs/react/practical-projects-cn  构建的demo没办法复现，antd版本跟公司项目是一样的（公司3.3.3，antd官方是3.6.1，两个版本都试过，公司项目一直有这个bug，新建的demo都没有），公司项目删除过自己写的所有css，但是还是有这个问题，不知道是不是安装的其他工具也有影响，你看一下能复现不，要是不能复现，我把公司的脚手架整理一份demo放到GitHub上去

**Comment by zhangjingge** [comment]
@zombieJ 
测试帮忙复现了
复现时安装的ie版本和demo都在下面的链接里面
https://pan.baidu.com/s/1eCVLj-VNyiFurzSYGQjN9Q

**Comment by jeffycai** [comment]
同求解决方案，MENU也存在此问题。

**Comment by zombieJ** [comment]
@jeffycai，能给个 codesandbox 吗？麻烦你了

@picodoth，看起来需要一起解决一下。

**Comment by jeffycai** [comment]
@zombieJ 我给处理掉了。自己控制了滚动条。

**Comment by zhangjingge** [comment]
@jeffycai 是点击后给scrollTop赋值吗，我这边这么处理，TreeSelect自己点击的时候有的还是会滚动回去，把子级也做相同处理的话，会先滚动回去然后又回来，可以把你方法发一下吗

**Comment by zombieJ** [comment]
related discuss: https://github.com/utatti/perfect-scrollbar/issues/160

**Comment by zhangjingge** [comment]
@zombieJ 
var domAlign = require('dom-align');  这个方案我大概看了一下还没尝试，它需要事件，恢复位置。
事件click，恢复位置也有，但是滚动条回到顶部不是在点击的时候发生的，是之后。
所以我我觉这个方案可能不可行
perfect-scrollbar这个方案原理一样，就是点击的时候滚动条是在正确的位置，是之后的一些渲染或者其他因素导致了取消后滚动条回到顶部

**Comment by zombieJ** [comment]
@zhangjingge , 目前这个 dom-align 的 PR 可以解决位置不变时重置的问题。还有一个位置改变重置需要额外做一些事情。

**Comment by zhangjingge** [comment]
@zombieJ ，dom-align：   http://yiminghe.me/dom-align/examples/simple.html 
试过了，是这个问题，开发网ie浏览器可以复现，我看看怎么修，非常感谢

**Comment by zhangjingge** [comment]
@zombieJ 
var domAlign = require('dom-align');
domAlign(sourceNode, targetNode, {
  points: ['tl', 'tr'], 
  offset: [10, 20], 
  targetOffset: ['30%','40%'], 
});
通过外部设置没有实现TreeSelect滚动bug的修复，但是我们通过设置依赖包  node_modules/dom-align/lib/index中useCssTransform的属性为true可以解决bug，想问一下直接设置是否会产生其他影响，如果没有影响打算直接改这个依赖包的属性

**Comment by zombieJ** [comment]
@zhangjingge ,可以用 `dropdownPopupAlign` 属性覆盖这个默认的 align 行为。

**Comment by zhangjingge** [comment]
@zombieJ ，已验证可以实现，谢谢！！！

**Comment by zhangjingge** [comment]
@zombieJ ， ie10，ie11没有问题并且bug被修复，但是ie9点击选择框下拉面板没有弹出。

**Comment by zombieJ** [comment]
那还是弄成 IE post scroll 一下吧

**Comment by zhangjingge** [comment]
动态赋值不行，三角图标展开关闭这个bug可以搞定，但是选项框点击选中没问题，取消选项滚动条上滚，取消click事件时滚动条位置正确（测试过，此时alert出来的数值正确，并且滚动条位置没有变化），取消之后很短间隔滚动上去
示意图： https://shimo.im/docs/7NqRHIrHDRYkKGFF/

**Comment by afc163** [comment]
这个问题修复了么

**Comment by zombieJ** [comment]
> 这个问题修复了么

还不行，`rc-align` 把 size 近似的抖动解决掉了。还有 size 变化的抖动，这个需要在 rc-trigger 里多包一层。

**Comment by XiangyuShi** [comment]
在Chrome 79版本，antd 3.26.6版本，mac 10.14.6 版本环境下，出现了相同的问题
