### ISSUE TITLE
Table组件在Modal中时，某些条件下，会出现横向滚动时表头长度和body不一致的问题，也无法同步滚动

### ISSUE THREAD

**Issue by sam019** [ant-design/ant-design#10816]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
macOS 10.13.4 Chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4qjx0m95y0)

### Steps to reproduce
1. 将Table展示在Modal中
2. 将Table的 th 和 td 元素 设置为不折行 { word-break: keep-all; white-space: nowrap; }
3. 设置Table的scroll为 { x: true, y: 400 } (y设为其他值也可以，只有设置了y值才能复现bug)
4.  将 dataSource 中的数据字段设置为比较长的字符串，使Table出现横向滚动条

### What is expected?
渲染后的表头长度和表格体长度一致，且滚动表格体时，表头会随着滚动

### What is actually happening?
渲染后的表头长度和表格体长度不一致，且滚动表格体时，表头不会随着滚动

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-header

<img width="477" alt="image" src="https://user-images.githubusercontent.com/507615/41039309-9cf09cc0-69cb-11e8-8028-760b1cde1656.png">
