### ISSUE TITLE
Select component with showSearch property will trigger onSearch with empty string when selecting a filtered option

### ISSUE THREAD

**Issue by jasonxia23** [ant-design/ant-design#10817]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
Chrome 66

### Reproduction link
[https://codepen.io/jasonxia/pen/JZKmdK?editors=1010](https://codepen.io/jasonxia/pen/JZKmdK?editors=1010)

### Steps to reproduce
Open Chrome DevTool. Input `j` and select `Jack`

### What is expected?
After inputing `j` and selecting `Jack`, `change Jack` should be logged in console.

### What is actually happening?
`search ` in logged in the console

**Comment by zombieJ** [comment]
`onSearch` should trigger even if component clean. Or it will miss search value sync in developer side.
