### ISSUE TITLE
Safari 中部分排列 Demo 失效

### ISSUE THREAD

**Issue by lomocc** [ant-design/ant-design#1081]
## 部分排列无效
http://ant.design/components/layout/#demo-sort

**Comment by afc163** [comment]
我看了下没有发现问题。。。

可否提供更多的信息帮助排查。

**Comment by lomocc** [comment]
Failed to load resource: the server responded with a status of 404 (Not Found) https://as.alipayobjects.com/g/component/es5-shim.map
好像是因为这个文件404，然后就 我的 safari 版本 8.0.8 (10600.8.9)，chrome就能忽略这个404，唉，搞不懂。。。
<img width="495" alt="2016-02-25 10 58 28" src="https://cloud.githubusercontent.com/assets/2075138/13323230/69bfa0c8-dc13-11e5-8e17-88392c7e8142.png">

**Comment by afc163** [comment]
这个文件是 sourcemap，不影响实际功能的。

升级下 safari 吧，目前最新应该是9.0.1。8.0.0 的对 flex 的支持应该不全面。
