### ISSUE TITLE
modal能否加一个弹出多个窗口并能拖动功能啊，实在在企业开发中大需要这个功能了

### ISSUE THREAD

**Issue by chendonghai1982** [ant-design/ant-design#10810]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们现在在开发大企业系统，现在碰到好多功能模块需要弹出的窗口可以拖动，并且可以弹出多个对话框，因为有时要对照一下内容，比如我有几套房子，我就要弹出多个对话框并且能移动对照，还有人事，财务等，都要对照，就像这个组件一样功能：http://layer.layui.com/

### What does the proposed API look like?
希望能增加一个参数设置这样的功能

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3012#issuecomment-386537987

**Comment by Yannanna0920** [comment]
@chendonghai1982  求分享多个modal 实现拖拽！谢谢！

**Comment by wb-chenlong** [comment]
@Yannanna0920  这个是我实现的一个 demo，你可以参考下。希望对你有帮助。
https://codesandbox.io/s/pyyzk54rnm

**Comment by chendonghai1982** [comment]
收到，谢谢，你这个应该还有些问题吧，点过去应该弹在最上面

**Comment by wb-chenlong** [comment]
@chendonghai1982  还是原来的 demo 地址，已经更新了。大致思路就是将所有可拖拽浮层的 zindex 设置为 999，目标拖拽浮层的 zindex 设置为 1000。只能想到这么 low 的直接操作 dom。有好的思路也可以提供下。仅做参考哈。
