### ISSUE TITLE
Modal (rc-dialog, rc-trigger) could provide interface like "isUseCreatePortal" 

### ISSUE THREAD

**Issue by swchenforgetful** [ant-design/ant-design#10812]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
as we know, ``React 16`` add new api ``ReactDOM.createPortal`` , and the portal will propagation event to parent. for it's name ``protal`` , this behavior maybe make sense, but it also takes many trouble(https://github.com/facebook/react/issues/11387)

I think the component named "Modal" should not share event with the parent. I find ``rc-dialog`` use `` IS_REACT_16 = !!ReactDOM.createPortal;`` to make compatible with ``React 16-`` . I think ``Modal`` could  provide interface like ``isUseCreatePortal`` .

### What does the proposed API look like?
```
<Modal isUseCreatePortal={true|false} />
```

**Comment by yesmeck** [comment]
https://github.com/facebook/react/issues/11387#issuecomment-340019419

Just don't put modal inside buttons.

**Comment by swchenforgetful** [comment]
Yes, ``Modal`` can, but ``DatePicker`` , ``Tooltip`` can't put outside.

**Comment by yesmeck** [comment]
@sammaxwellxyz Do you have any real world example?

**Comment by yesmeck** [comment]
Unfortunately, React will remove `unstable_rendersubtreeintocontainer` in the feature, so adding `isUseCreatePortal` is not a good choice. As a workaround you wrap `DatePicker` with a `<span onClick={e => e.stopPropagation()}>`

**Comment by swchen** [comment]
It works. 
Maybe ``antd`` could buildin wrap it and provide a prop like ``isEventPropagation``
