### ISSUE TITLE
create-react-app + antd新的流程有没有问题？

### ISSUE THREAD

**Issue by yinhunfeixue** [ant-design/ant-design#10813]
查了一下代码，按官网的配置，最终是执行的react-scripts包中的start.js等

研究了下，似乎可以按如下步骤操作

基于create-react-app的antd项目
1、创建项目
create-react-app demo 
cd demo
2、展开配置
      npm run eject
3、安装依赖
      cnpm i  babel-plugin-import --save-dev
      cnpm i antd --save
      cnpm i

3、添加bable配置
根目录下创建.babelrc文件，内容为
{
  "presets": ["react-app"],
  "plugins": [
    **["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]**
  ]
}

4、（可选）添加eslint配置
根目录创建  .eslintrc 文件，内容为
{
  "extends": "react-app",
  "rules": {
       "no-console":"warn"
       //自行设置eslint规则
  }
}

**Comment by afc163** [comment]
https://ant.design/docs/react/use-with-create-react-app-cn
