### ISSUE TITLE
Modal能否加个确定按钮的disabled属性？

### ISSUE THREAD

**Issue by ZH4L** [ant-design/ant-design#10822]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`Modal`要实现确定按钮的禁用的话，当前只能通过自定义的`footer`来实现，这应该是个常用的需求，加入disabled后就可以不使用`footer`来控制了了

### What does the proposed API look like?
希望增加一个比如叫做`okDisabled`的属性，用于控制默认的确定按钮的禁用状态

**Comment by chenshuai2144** [comment]
可以通过 footer 自定义按钮

**Comment by ZH4L** [comment]
@chenshuai2144 我知道可以通过footer自定义按钮，但是如果单纯的想实现禁用确定按钮这个，每次都要通过footer来自定义，花费是不是略大

**Comment by afc163** [comment]
感觉需要一个 oKButtonProps

**Comment by yuyichen** [comment]
看到3.10的文档上有okButtonProps这个配置项,但是我项目用的3.2版本不起作用,这个是新增的么?

**Comment by zombieJ** [comment]
@yuyichen ，嗯，升级一下版本

**Comment by yuyichen** [comment]
> @yuyichen ，嗯，升级一下版本

建议文档上标注下多少版本以上可用

**Comment by zombieJ** [comment]
@yuyichen , https://ant.design/changelog-cn
