### ISSUE TITLE
使用Table组件的 filters 和 filterDropdown ，filterDropdown 不能触发 Table 的onChange 事件

### ISSUE THREAD

**Issue by top-soft** [ant-design/ant-design#10829]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
win10,chrome最新版

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l5pvkr2oq7)

### Steps to reproduce
首先选择姓名点击搜索不能触发Table的onChange事件，试了很多种方法，还是不得行

### What is expected?
像点击filters里面的那些过滤一样能自动调用onChange，我在onChange中去完成后台请求

### What is actually happening?
filterDropdown 不能触发 Table 的onChange 事件

**Comment by top-soft** [comment]
在输入框发生改变时 执行onTableSearchChange = (dataIndex, e) => {
        this.setState({filteredValue: [e.target.value]});
    };，这个时候input的值是获取到的，只差一步，就是触发onChange

**Comment by top-soft** [comment]
在没得到支援前，最终的实现方案，感觉不是很优雅。希望能有办法手动触发onChange事件
`
handleTableChange = (pagination, filters, sorter) => {
        this.setState({pagination, filters, sorter});
        this.loadData({
            pageSize: pagination.pageSize,
            current: pagination.current,
            sortField: sorter.field,
            sortOrder: sorter.order
        }, filters);
    };
    handleTableSearch = (dataIndex) => {
        const o = {};
        o[dataIndex + '_filterDropdownVisible'] = false;
        o[dataIndex + '_filtered'] = this.state[dataIndex + '_filteredValue'].length > 0;
        this.setState({...o});
        //TODO 手动触发Table的onChange事件  或者调用当前页
        const {pagination, filters, sorter} = this.state;
        filters[dataIndex] = this.state[dataIndex + '_filteredValue'];
        this.handleTableChange(pagination, filters, sorter)
    };
`

**Comment by yesmeck** [comment]
是的，这种方式其实因为是在 Table 组件外部做的 filter，所以 Table 其实是不知道发生了 filter 变化的。

**Comment by w118zn** [comment]
这个问题最后解决了吗，我这边第一次不会触发，再次点开搜索框触发一次就能触发table Onchange

**Comment by qinghua5453** [comment]
我因为类似 无法触发onChange的 bug，试了好多种方法了。哎
