### ISSUE TITLE
Tree组件重新加载已展开的节点，节点展开按钮消失

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#10821]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
Google Chrome 66.0.3359.139

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9oyjkyzyl4)

### Steps to reproduce
展开一个节点后， 点击重新加载按钮， 节点前面的展开按钮消失

### What is expected?
展开按钮还存在

### What is actually happening?
展开按钮消失

**Comment by zombieJ** [comment]
Tree 在展开后这个节点就会被标记为已载入的状态， `setState` 没有传子节点 Tree 就认为是用户故意删除了子节点：
```jsx
this.setState({
  expandedKeys: [],
  treeData: [
    { title: "Expand to load", key: "0" },
    { title: "Expand to load", key: "1" },
    { title: "Tree Node", key: "2", isLeaf: true }
  ]
});
```

感觉得再加个属性，让 loadedKeys 也变成可控的。

**Comment by ty-bt** [comment]
对的.  不然没办法刷新..

**Comment by ty-bt** [comment]
现在是用更换key的方式刷新的，但是太不友好了.

**Comment by zombieJ** [comment]
Will release in `3.7.0`

**Comment by refixldy** [comment]
有demo代码么？
