### ISSUE TITLE
getFieldDecorator has some bug

### ISSUE THREAD

**Issue by rainke** [ant-design/ant-design#10827]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
chrome 66.0.3359.181 react 16.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j2x13zvqz5)

### Steps to reproduce
for getFieldDecorator(name, options). 
1. set the name with 'users[0].password'
2. execute `getFieldValue('users')`, no error.
3. execute `setFieldsValue({users: [{password: '222'}]})`, no error;
4. set the name with 'users[0][password]';
5. execute `getFieldValue('users')` no error;
6. execute `setFieldsValue({users: [{password: '222'}]})`, error, the execute doesn't work;

I will get the error `You cannot set field before registering it`;

### What is expected?
the name can support both `a[0].b` and `a[0][b]`. because `lodash/set` support both

### What is actually happening?
For getFieldDecorator(name, options). if the name like 'users[0].password' or 'users[0][password]', `getFieldValue('users')` is correct, but  `setFieldsValue({users: [{password: '222'}]})` has different case. If the name is `users[0].password`, there is no error, but when the name is `users[0][password]`, I will get the error `You cannot set field before registering it`;

---
英语不好，如果看不懂请@我

**Comment by abdih** [comment]
I intend to work on this issue.

**Comment by afc163** [comment]
Please upgrade to antd v4 new Form.
