### ISSUE TITLE
Allow to add custom node before or after select items

### ISSUE THREAD

**Issue by ybning** [ant-design/ant-design#10831]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有这样一个场景：单位Select，在选项下可以放组件，如：按钮——“新增”。
如图：
![select](https://user-images.githubusercontent.com/3725612/41095454-0af8584e-6a84-11e8-8002-14f0b5ee9df4.png)

### What does the proposed API look like?
Select，在选项下区域，可以允许自定义组件，有考虑支持这样吗？

**Comment by rainke** [comment]
让产品改需求吧，比如把新增按钮放下拉框后边

**Comment by ybning** [comment]
@rainke 
”用户在Select下拉项中没有找到想要的项，直接在下拉项的视线内，点击新增，方便操作。新增放到外面，跳出了下拉项的视线，体验不好“——援引自xx产品

**Comment by chenshuai2144** [comment]
你可以组合一个

**Comment by afc163** [comment]
感觉可以提供类似 `dropdownRender(menu) => ReactNode` 的东西。

**Comment by chenshuai2144** [comment]
新增再谈一个表单？ 我感觉这个我们做不合适

**Comment by afc163** [comment]
用户做什么不管，提供的是前后插入自定义 node 的能力。

**Comment by ybning** [comment]
> 用户做什么不管，提供的是前后插入自定义 node 的能力。

@afc163  good！

**Comment by chenshuai2144** [comment]
这个是级联框吧

**Comment by ybning** [comment]
像类似这种Select衍生交互，还是希望Select有插入自定义node的能力。

**Comment by afc163** [comment]
It is not closed.

I am indented to solution of https://github.com/ant-design/ant-design/issues/10831#issuecomment-395677779

Welcome to help us and send us PR~

**Comment by m1n0s** [comment]
Hi @afc163!
Any chances it'll be available in closest week or two? I assume you haven't started developing this feature yet. So if I'll add PR for that what could be ETA of fix to be available? 

Are there any possible workarounds to add button before options?

Sorry for messy questions but I need this feature ASAP.

Thank you!

**Comment by zombieJ** [comment]
下拉新增感觉可以这么做？ https://codesandbox.io/s/v87kr0mlyy

**Comment by zombieJ** [comment]
@m1n0s , I guess you can combine [cascader](https://ant.design/components/cascader/) with the sample above to do as the workaround

**Comment by m1n0s** [comment]
@zombieJ thank you and I can even add custom styling because `Option` propagates `className` to `li` element. But the problem that `Select` decorated with `getFieldDecorator` which has own `onChange` and I don't know the way how to catch in earlier or stop propagation to decorated onChange unfortunately.

**Comment by m1n0s** [comment]
@zombieJ eventually your sandbox example helps me made the magic. Thank you!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/e1d3d2b3e1f6c3af17007f1009a6083dd416f09d

**Comment by jackton1** [comment]
This seems to be broken when the button is clicked the dropdown closes for cases where the select is placed inline with other inputs.

<img width="558" alt="Screen Shot 2019-04-15 at 3 30 38 PM" src="https://user-images.githubusercontent.com/17484350/56159782-83592700-5f93-11e9-8819-8f55558d5944.png">

**Comment by m1n0s** [comment]
@jackton1 please take a look to #13504

**Comment by gtaranti** [comment]
https://codesandbox.io/s/antdselectaddoption-7fov7

Still not perfect.

**Comment by n313893254** [comment]
It is too bad, we hope for just input and create. It should look like `react-select` do.
https://react-select.com/creatable

![image](https://user-images.githubusercontent.com/18737885/68471145-85991080-0258-11ea-8491-a355b0b32256.png)

**Comment by demirhancosku** [comment]
> https://codesandbox.io/s/antdselectaddoption-7fov7
> 
> Still not perfect.

I just forked your code-sandbox and refactored it for my use-case. It's worked enough to meet my needs :)

https://codesandbox.io/s/antd-select-add-option-cr6ii

**Comment by theo4u** [comment]
@demirhancosku used your fork updated(used hooks) it to work like [react-select creatable](https://react-select.com/creatable) 

### Codesandbox
 [![Edit modifiedAntd-select](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-silence-ky32o?fontsize=14&hidenavigation=1&theme=dark)


![creatable-select](https://user-images.githubusercontent.com/10440327/77476079-4545c380-6df0-11ea-9299-a0bc1982eb54.gif)
