### ISSUE TITLE
Popover doesn't work correctly with Tooltip

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#10832]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
chrome, windows 10, react 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qxyx911pv4)

### Steps to reproduce
  - create Button inside Tooltip inside Popover.
  - hover button
  - tooltip appears, button receives class ant-tooltip-open
  - click button
  - popover appears, BUT button doesn't receive class ant-popover-open

if you switch tooltip and popover hierarchy, then  ant-tooltip-open will be blocked.

FYI: Inner component Trigger doesn't pass className to the child.

### What is expected?
Expected that trigger component (e.g. button) receive classes from both (all) triggering component(popover and tooltip) over it.

### What is actually happening?
only nearest triggering component passes class to trigger

**Comment by urrri** [comment]
I updated code to https://codesandbox.io/s/qxyx911pv4
Somehow it didn't save all code.

**Comment by afc163** [comment]
Please try reinstall node_modules.

**Comment by urrri** [comment]
what do you mean? Have you fixed it?

**Comment by afc163** [comment]
<img width="564" alt="image" src="https://user-images.githubusercontent.com/507615/41150322-44bf3338-6b40-11e8-93de-b625d827720d.png">

**Comment by urrri** [comment]
Ooops, I missed it :+1: 
It works
