### ISSUE TITLE
Form validating is trigged on removed input element in the certain condition！

### ISSUE THREAD

**Issue by ufohjl** [ant-design/ant-design#10830]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
all

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nr3zzl0xzp)

### Steps to reproduce
1. Select yes
2. Select no
3. Click [Show Modal] button
4. Type something in NAME input
5. Click [OK] button

### What is expected?
No validating QUANTITY input because the react element is removed

### What is actually happening?
Validating QUANTITY input

---
Strangely, If I add 2 operations:
1. Select yes 
 > Click [Show Modal] button
 > Close modal
2. Select no
3. Click [Show Modal] button
4. Type something in NAME input
5. Click [OK] button

It works!!

**Comment by zombieJ** [comment]
Duplicate of #13689
