### ISSUE TITLE
Editor

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#1083]
theme and encapsulation about [draft-js](http://facebook.github.io/draft-js/)

https://www.facebook.com/notes/

https://react-rte.org/demo

https://github.com/react-component/editor-core  @RaoHai

**Comment by benjycui** [comment]
**Note**

antd need es6-shim after including draft-js, see: https://facebook.github.io/draft-js/docs/advanced-topics-issues-and-pitfalls.html#polyfills

**Comment by benjycui** [comment]
https://github.com/facebook/draft-js/blob/master/package.json#L32

**Comment by shepherdwind** [comment]
期待啊，这个看起来似乎没啥进展？是不是换一个皮肤就好了？

**Comment by clarkhan** [comment]
看了下，这个组件不包含在 1.0 #978 中，是不是暂时处于搁置状态，有大概的发布时间吗？

**Comment by benjycui** [comment]
还没开始做，做了的话，会有一个 In progress 的 PR 的。

**Comment by afc163** [comment]
https://github.com/sstur/react-rte

**Comment by afc163** [comment]
![](https://zos.alipayobjects.com/rmsportal/PoGEeRBqatmwxIx.png)

**Comment by uedkx** [comment]
期待

**Comment by Nokecy** [comment]
期待发布

**Comment by raisezhang** [comment]
再刨下之前的坑  -_- ||     啥时候发布~    

目前看好多都不是那么理想，要么不支持图片，要么是基于 jQuery 的，不是 rc 的， 多谢啦~

**Comment by TDiDa** [comment]
同求，找了一圈没找到合适的富文本编辑器，期待

**Comment by whx76** [comment]
期待发布，有时间点吗？

**Comment by afc163** [comment]
https://github.com/jpuri/react-draft-wysiwyg

**Comment by ochukai** [comment]
期待

**Comment by kcshan** [comment]
Hurry to release 啊

**Comment by kvetoslavnovak** [comment]
This one isreally superb!

**Comment by pigletfly** [comment]
please consider Markdown support

**Comment by raisezhang** [comment]
还没有搞定的也可以参考下  https://github.com/liuhong1happy/react-umeditor

**Comment by imshenyz** [comment]
期待发布，不知道这个项目有没有可参考性
https://github.com/draft-js-plugins/draft-js-plugins

**Comment by yuweilan** [comment]
期待发布富文本编辑器，找了好多其他的编辑器，使用效果不佳

**Comment by afc163** [comment]
https://github.com/leejaen/react-lz-editor

**Comment by TangMonk** [comment]
期待

**Comment by ryli** [comment]
暂时使用了 https://github.com/zenoamaro/react-quill

**Comment by kennylbj** [comment]
Any progress?   @afc163

**Comment by NicholasNC** [comment]
[wangeditor](http://www.wangeditor.com/)

也是一个不错的选择

**Comment by kimown** [comment]
draftjs仅做备份参考：

https://docs.slatejs.org/

https://github.com/crossfield/react-drafts

**Comment by acomito** [comment]
Would people recommend using this in the mean time?

https://github.com/leejaen/react-lz-editor

**Comment by pruhstal** [comment]
@acomito that feels super heavy and is pretty buggy with my limited use of it. I'd personally go with something like https://github.com/tinymce/tinymce as it's just way more battle tested than the majority of editors out there.

**Comment by nmgwddj** [comment]
http://margox.github.io/braft-editor/

**Comment by benjycui** [comment]
Actually, I don't recommend antd to support RTE.

There are too many edge cases, even a RTE framework(e.g. draft-js, slate.js) cannot work well in every use case. It's impossible to write an RTE which works fine in every use case.

What we can do is develop some draft-js plugins which is useful in most use cases. And then, developers use our plugins to build a RTE, and they may need to develop their own plugins for their special use cases.

**Comment by junliuxian** [comment]
Supporting the rich text editor is a great suggestion. Expect the ant team to develop it.

**Comment by huyanatown** [comment]
> > http://margox.github.io/braft-editor/
> 
> It looks good, but his UL and OL don't seem to be doing very well

有没有复杂的，比方说有模板可以选择的那种，类似秀米编辑器。

**Comment by wowlusitong** [comment]
自荐一个富文本编辑器 https://github.com/wowlusitong/re-editor

**Comment by aiddroid** [comment]
CKEditor 与 FroalaEditor 无法兼容 <a-form>, form.getFieldsValue() 取不到值
-------------------------------------------------------------------------------
CKEditor and FroalaEditor incapable with ant-design's  <a-form>, form.getFieldsValue() cannot get editor data

**Comment by Chendabaiiii** [comment]
超级超级期待antd出富文本组件，请问antd目前有没有这个计划？

**Comment by Chendabaiiii** [comment]
I am looking forward to antd's rich text component. Does antd currently have this plan?

**Comment by zombieJ** [comment]
Close since rick text edit is much heavy that may not good to apply on antd side.
