### ISSUE TITLE
checkbox: How to implement multi-layer nesting(怎么实现多层嵌套)

### ISSUE THREAD

**Issue by Mr-jiangzhiguo** [ant-design/ant-design#10839]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
权限分配

### What does the proposed API look like?
Want to implement the following structure
(想实现如下结构):
```
口 All
    口 menu1 
        口 menu1-1
        口 menu1-2
    口 menu2 
        口 menu2-1
        口 menu2-2
```

Requirement(要求):
1.(Click `All`, and all the subitems are selected)
     点击 All, 所有的子项都被选中
2.Click `menu1`, and its own subitems are selected (here are `menu1-1` and `menu1-2`)
   点击 menu1 , 属于它自己的子项都被选中(这里是menu1-1和menu1-2)
=========
How to use checkbox to achieve the above effect,
   使用checkbox怎么实现上面的效果,
If there is a better solution, please recommend it, thank you.
   若有更好地解决方法,请推荐,谢谢啦!

**Comment by afc163** [comment]
http://ant.design/components/tree/

**Comment by Mr-jiangzhiguo** [comment]
@afc163 thx
