### ISSUE TITLE
select labelInValue怎么优雅的追加其他属性值

### ISSUE THREAD

**Issue by DuduStyle** [ant-design/ant-design#10834]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
select 传值能够更加灵活；不仅仅只局限于['12233']或[{key:'222',label:'张三'}]这两种形式

### What does the proposed API look like?
labelInValue={key:${key},type:${type},label:${label}}

**Comment by DuduStyle** [comment]
另外这个确实找了很多，找不到合适的答案，[https://segmentfault.com/q/1010000009180993](url)
很久了也没人回答。。。

**Comment by afc163** [comment]
建议传给 Select 前自行处理一下数据。

**Comment by DuduStyle** [comment]
数据当然是处理了，我的问题是，如何在提交表单时，追加其他属性信息，难道要去原数据遍历找到对应的数据，然后再把值追加到提交的数据中嘛？ @afc163

**Comment by Alina92** [comment]
我也遇到这个问题，哪个大佬有解决方法
