### ISSUE TITLE
使用Table及Card组件的时候如何显示成圆距边框

### ISSUE THREAD

**Issue by liu-ziang** [ant-design/ant-design#10843]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
直接对组件设置成圆距边框，上部分显示不正常，下部分边框显示正常。

### What does the proposed API look like?
可以正常设置圆距边框

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
