### ISSUE TITLE
Badge status is not affected by the change theme

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design#10842]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The color change after the theme change caused some problems

### What does the proposed API look like?
none

![image](https://user-images.githubusercontent.com/8186664/41111444-917ede5e-6aae-11e8-9c93-513b2f13ae8a.png)

**Comment by afc163** [comment]
不能这么改，回滚了重新发 PR

**Comment by chenshuai2144** [comment]
需要你回滚一下 保护分支
