### ISSUE TITLE
AllowClear不生效

### ISSUE THREAD

**Issue by 174255317** [ant-design/ant-design#1084]
rc-tree-select的allowClear不生效
版本1.1.5，antd版本0.12.4

**Comment by afc163** [comment]
请学会正确的提问题。

https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md

http://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html

**Comment by 174255317** [comment]
学不会亲，BUG请修复下
