### ISSUE TITLE
ios11 needs to double-click to trigger the upload function

### ISSUE THREAD

**Issue by mrcaobin** [ant-design/ant-design#10854]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.0

### Environment
windows，chrome，iphone safri

### Reproduction link
[Https://ant.design/components/upload-cn/](Https://ant.design/components/upload-cn/)

### Steps to reproduce
upload 控件在iphone手机上，ios11中，需要点击2次才能触发；ios10则完全触发不了。安卓正常

### What is expected?
点击一次即可触发上传文件选择框。
网站是PC和手机端共同适配的，所以选择用antd，没用antd-mobile

### What is actually happening?
ios11中，需要点击2次才能触发；ios10则完全触发不了

**Comment by zhanchengkun** [comment]
我遇到同样的问题，效果上选择antd更合适，而不能选择antd移动。
机器人正常，IOS需要双击，怎么解决？
antd上传跟OSS中的上传类似可直接用customRequest操作定义
若用antd移动需要对应的让后台再调整接口，不合适。
所以寻求antd在ios下单机上传的解决方案

**Comment by yejing2017** [comment]
我也遇到了这个问题，发现是手机版 用了 fastClick 导致的

**Comment by nannongrousong** [comment]
参考：https://segmentfault.com/a/1190000009246194

那就有解决方案了，在你实际点击的那个元素上添加class[needsclick]
注意，一定是【你页面中实际点击的那个元素】。
但在不同场景下，picture-card或picture或text下，页面中显示的元素也不一样，有 .antd-upload-text 也也有普通  <span>，所以你实际点击的元素每次都不一样，那怎么办？
碰到这种问题不要太温柔了，粗暴一点，componentDidMount中给Upload所有子元素（递归）添加class[needclick]
over！

**Comment by itxcc** [comment]
有可能是因为在项目中引用了FastClick这个解决移动端延迟300毫秒的优化
打开**node_modules/fastclick/lib/fastclick.js**
修改如下：
`FastClick.prototype.focus = function (targetElement) {
  let length;
  if (targetElement.setSelectionRange && targetElement.type.indexOf('date') !== 0 && targetElement.type !== 'time' && targetElement.type !== 'month') {
    length = targetElement.value.length;
    targetElement.focus();
    targetElement.setSelectionRange(length, length);
  } else {
    targetElement.focus();
  }
};`

**Comment by Haixiang6123** [comment]
果然是 fastclick 的锅，找到原因了！
