### ISSUE TITLE
Title of treeNode can't be react-dnd dragSource component

### ISSUE THREAD

**Issue by liuchaofeng1230** [ant-design/ant-design#10859]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.1

### Environment
OSX10.13.3 chrome66

### Reproduction link
[https://github.com/liuchaofeng1230/antd-tree-react-dnd-demo](https://github.com/liuchaofeng1230/antd-tree-react-dnd-demo)

### Steps to reproduce
Step1: Drag tree node from left to right.

Step2: If the text in right block changed to "can drop", it means react-dnd works.

### What is expected?
I can drag component from tree node, and drop to dragTarget of react-dnd

### What is actually happening?
antd 3.1.3 is ok, but after I upgrade version to 3.6.1, my feature is broken

**Comment by zombieJ** [comment]
有人发了pr，还没有更新：
https://github.com/react-component/tree/pull/166

**Comment by DonChengCheng** [comment]
现在我也遇到这个问题，现在有没有解决？还有其它的解决方案吗？

**Comment by afc163** [comment]
Closed by https://github.com/react-component/tree/pull/166
