### ISSUE TITLE
单独使用radio时，label怎么添加（不是作为formitem）

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#1085]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/pgdXYp?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
`<Radio>xxx</Radio>`

**Comment by Aggie123** [comment]
不是，可能我描述的不够清除，是给一个radioGroup加一个标签，怎么加

**Comment by afc163** [comment]
```jsx
<div>
  <label>标签：</label>
  <RadioGroup onChange={this.onChange} value={this.state.value}>
    <Radio key="a" value={1}>A</Radio>
    <Radio key="b" value={2}>B</Radio>
    <Radio key="c" value={3}>C</Radio>
    <Radio key="d" value={null}>D</Radio>
  </RadioGroup>
</div>
```

**Comment by Aggie123** [comment]
哦 直接这样 多谢 ！
