### ISSUE TITLE
table组件，当datasource是对象套对象时，怎么展现子对象的数据

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#1086]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/pgdXYp?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
默认 issue 模板里的信息，如果你不需要，不要这样直接提交上来。

**Comment by afc163** [comment]
http://ant.design/components/table/#demo-expand-children

**Comment by Aggie123** [comment]
datasource:
{
name: 'A',
age:'10',
records:[{year:2014,english:80,math:90},{year:2015,english:85,math:80}]
}
table 如下：
name age year     enlish math 
A        10   2014      80       90
                  2015      85      80

**Comment by Aggie123** [comment]
例子当中没找到想要的，举个例子，比如上面是已有的数据和想要的table,怎么实现呢？

**Comment by Aggie123** [comment]
我现在能想到的是table里面套table，但title不在一行，不是完全想要的效果，有比较好的解决方法吗

**Comment by afc163** [comment]
```
const columns = [{
  title: 'xxx',
  render() {
    return <Table />;
  }
}];
```

**Comment by Aggie123** [comment]
你这也是table套table啊 这样会有2行title 希望只有1行子对象的title跟父对象一行展示 这样怎么实现呢？

**Comment by afc163** [comment]
试试 http://ant.design/components/table/#demo-expand-children 配合这个参数 `https://github.com/react-component/table/blob/e4e7eaa299087f66416d0d2283e27b0530a20592/src/Table.jsx#L51`

**Comment by Aggie123** [comment]
好的 我试试 谢谢这么及时的回复
