### ISSUE TITLE
How can I get an instance of TreeNode?

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#10868]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
Windows 10 1803, Electron

### Reproduction link
[https://ant.design/components/tree/](https://ant.design/components/tree/)

### Steps to reproduce
<TreeNode key={key} title={data} ref={(node) => this.addToNodeList(node)} />

### What is expected?
No error when compile

### What is actually happening?
throw error 
TS2339: Property 'ref' does not exist on type 'IntrinsicAttributes & AntTreeNodeProps & { children?: ReactNode; }'.

---
react 16.2.0
react-dom 16.2.0
typescript 2.9.1

**Comment by yesmeck** [comment]
@Voronar Could you take a look?
