### ISSUE TITLE
Modal's animation conflicts with transform in style props

### ISSUE THREAD

**Issue by dc3671** [ant-design/ant-design#10862]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
MacOS 10.13.4, Chrome 66.0.3359.139 (Official Build) (64-bit) 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/58rvop6jx)

### Steps to reproduce
点击按钮，会弹出对话框

### What is expected?
对话框直接定位在屏幕中央，因为在style里设置了如下：
```jsx
style={{
  position: 'absolute',
  top: '50%',
  left: '50%',
  transform: 'translate(-50%, -50%)'
}}
```

### What is actually happening?
对话框会先只是左上角根据top和left定位到屏幕中央，在差不多1s之后才transform成整体中央，猜想是modal的animation导致的bug，如果能关闭animation也许就不会有延迟了

**Comment by afc163** [comment]
That is why we provide https://ant.design/components/modal/#components-modal-demo-position

**Comment by dc3671** [comment]
Thanks, I missed that.
Although I think it's not that elegant for users.
