### ISSUE TITLE
Press `Enter` key on AutoComplete submits the form

### ISSUE THREAD

**Issue by piuccio** [ant-design/ant-design#10861]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
Any browser

### Reproduction link
[https://ant.design/components/form/#components-form-demo-register](https://ant.design/components/form/#components-form-demo-register)

### Steps to reproduce
In the demo page there's a form with autocomplete (Website)

1. Type anything in the autocomplete
2. The dropdown opens
3. Use keyboard up / down to highlight an option
4. Press ENTER on the option

### What is expected?
I expect the option to be selected but the form should not be submitted

### What is actually happening?
The form is submitted, you can see that the form is submitted because all fields are now in red

---
Is there a way to prevent submit when the select dropdown is open?

**Comment by afc163** [comment]
https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/
http://david-chen-blog.logdown.com/posts/177766-how-forms-submit-when-pressing-enter

**Comment by piuccio** [comment]
Yes, enter on the field should submit, but not on the option.

To better understand please have a look at [this simple form](https://jsfiddle.net/ag2913un/). The AutoComplete is the same as a Select (they share a lot of their code).

In the form above
1. focus on the text field
2. press tab to focus on the select
3. press down to go to option two
4. press enter to select option two

At this point, after **one** key press, the form is not submitted, but the option two is selected. If you want to submit the form you have to press enter **again**.

The AutoComplete behaves differently because on the **first** enter press submits the form

**Comment by afc163** [comment]
Try reinstall node_modules
