### ISSUE TITLE
Select: "not found" state cannot be detected from e2e tests (DOM html)

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#10863]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- Exact detecting "not found" state from e2e (selenium like) tests. 
- Additional possibility of styling empty list

### What does the proposed API look like?
Add class like "ant-select-not-found" to main and drop-down parts of the Select

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/0bfd5ee14dd4de73239b3d7a642d9ae3084fa626/components/select/__tests__/index.test.js#L17-L26

**Comment by afc163** [comment]
If that doesn't works for you, you can send PR to http://github.com/react-component/select directly.

**Comment by urrri** [comment]
Identifying by text is wrong practice. It can be e.g. translated or replaced by other content via API of the Select component. In theory I can even have one real item with title 'Not Found', though it sounds strange.
