### ISSUE TITLE
RangePicker format default value loss

### ISSUE THREAD

**Issue by junliuxian** [ant-design/ant-design#10860]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.0

### Environment
win64、Chrome/62.0.3202.75

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m404mnnylx)

### Steps to reproduce
```
<p>Undesirable results：</p>
<RangePicker showTime style={{ marginBottom: 24 }} />
<p>Ideal result：</p>
<RangePicker showTime format="YYYY-MM-DD HH:mm:ss" />
```

### What is expected?
`format` in `RangePicker` API has a default value, I want to omit it

### What is actually happening?
When using `showTime`, I must set the `format`

**Comment by zombieJ** [comment]
Since currently `showTime` & `format` process is in different package (format depends on user locale prop), this will makes code coupling.

Will not upgrade this recently
