### ISSUE TITLE
Expose event object in onSelect callback of Select Component

### ISSUE THREAD

**Issue by Aashishkmr** [ant-design/ant-design#10873]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
To create dynamic states and objects based on Selects name. I magine i have five Select dropdowns on page used as custom filters for a table. I would like to access there name like event.target.name and create my filters object like filters["event.target.name"]=event.target.value.

### What does the proposed API look like?
onSelect=this.handleChange(value,event)

**Comment by yesmeck** [comment]
`onSelect` has the second parameter `option`, plz refer to the document https://ant.design/components/select-cn/#Select-props
