### ISSUE TITLE
提一个关于使用pagination然后特定需求产生的bug

### ISSUE THREAD

**Issue by allces** [ant-design/ant-design#1087]
![image](https://cloud.githubusercontent.com/assets/7076712/13351467/c545ab64-dcc1-11e5-822f-c1f800725ebc.png)

一个table绑定两个pagination，当改变其中一个size的时候，当前修改这个的currentSize正确，但是另外一个不变，有什么解决方案吗

![image](https://cloud.githubusercontent.com/assets/7076712/13351538/3df4a8ee-dcc2-11e5-9c31-75d4b9dcdd8b.png)

两个pageSize是从state里面读取的同一个变量

**Comment by allces** [comment]
我希望两个都变，能实现吗。谢谢各位

**Comment by afc163** [comment]
Need Demo: http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by allces** [comment]
例子加上去了

**Comment by afc163** [comment]
确实是一个问题，我稍晚修复下。

**Comment by ibigbug** [comment]
我看一下
