### ISSUE TITLE
Mention, remove prefix after text replacenment

### ISSUE THREAD

**Issue by HFR1994** [ant-design/ant-design#10875]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Ok so in the Mention element if I insert @Hello the text will be translated to @Goodbye for example. I can't seem to find a way to remove the "@" from the ending text. I tried currently save the text to a state variable which currently replaces the "@" to "" and update the property "value" with the new text but it crashes even if I add something like:            
               
             value={toContentState(descripcion)}

Is their a work around to this?

### What does the proposed API look like?
So you could add a property which could be something like "appendPrefix"

**Comment by zombieJ** [comment]
Could you provide a code sandbox? or some step example?

**Comment by HFR1994** [comment]
Sure.

Let's say in the mention componente I write:

> Hello how are you @user

Which that system transaltes it into:

> Hello how are you @Hector Flores

Insead of this being the final product could it just show:

> Hello how are you Hector Flores

**Comment by zombieJ** [comment]
Use `onChange` to get the content and set by `value` can do this : )
