### ISSUE TITLE
Can't npm start ？ the error is about 'bisheng.config'

### ISSUE THREAD

**Issue by zaoansijia** [ant-design/ant-design#10870]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
win7 , npm: 3.10.10 ,node: 6.11.2

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
1. git clone 'https://github.com/ant-design/ant-design.git'
2. npm install
3. npm start
4. I also restall the node_modules  , then  npm install and npm start, however, it's also error.

### What is expected?
start success 

### What is actually happening?
start error. and the error report is as follows：

 antd@3.6.2 start D:\anan\ant-design
> rimraf _site && mkdir _site && node ./scripts/generateColorLess.js && cross-en                                          v NODE_ENV=development bisheng start -c ./site/bisheng.config.js

Theme generated successfully. OutputFile: D:\anan\ant-design\_site\color.less
D:\anan\ant-design\site\bisheng.config.js:135
    );
    ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getBishengConfig (D:\anan\ant-design\node_modules\bisheng\lib\utils\get-b                                          isheng-config.js:55:54)
    at Object.start (D:\anan\ant-design\node_modules\bisheng\lib\index.js:73:23)
    at Object.<anonymous> (D:\anan\ant-design\node_modules\bisheng\bin\bisheng-s                                          tart:10:9)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\yangliu15\\dev\\nodejs\\node.exe" "C:\\Users\\yangliu1                                          5\\dev\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! antd@3.6.2 start: `rimraf _site && mkdir _site && node ./scripts/genera                                          teColorLess.js && cross-env NODE_ENV=development bisheng start -c ./site/bisheng                                          .config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@3.6.2 start script 'rimraf _site && mkdir _site && n                                          ode ./scripts/generateColorLess.js && cross-env NODE_ENV=development bisheng sta                                          rt -c ./site/bisheng.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rimraf _site && mkdir _site && node ./scripts/generateColorLess.js                                           && cross-env NODE_ENV=development bisheng start -c ./site/bisheng.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\anan\ant-design\npm-debug.log

---
I have search other issues which like this issue, I found  two issues are very similar to my issue。but one is use yarn install，so he restall the node_modules and use npm install is ok. the other just closed issue beacasue  it does not conform to issue requirements.

**Comment by yesmeck** [comment]
node 8
