### ISSUE TITLE
Select组件怎么跑测试

### ISSUE THREAD

**Issue by jsers** [ant-design/ant-design#1088]
我想通过 Selenium WebDriver 来编写集成测试，但是发现Select组件渲染后的DOM结构很难通过脚本完成 点开下拉和选中选项的操作。

**Comment by afc163** [comment]
我们没有相关的经验，欢迎自行探索。

**Comment by pulord** [comment]
@jsers select的问题解决了吗？我也遇到同样的问题，求解决方案

**Comment by yesmeck** [comment]
需要自己去找到合适的 DOM 模拟点击。比如要找 `.ant-select` 来点击打开 Select，然后再找到合适的选项再模拟点击，可以把这两个步骤封装下。

**Comment by jsers** [comment]
@pulord 没有解决
后来考虑下成本和收益放弃做这件事了

**Comment by pulord** [comment]
@yesmeck 谢谢这个方法确实不错，谢谢

**Comment by haydonduan** [comment]
@pulord @yesmeck 什么方法？我现在是用的Cascader组件，用触发事件为hover的时候，测试代码里写hover() 就不行；触发事件为click的时候，测试代码写click()就好使，#5128

**Comment by yesmeck** [comment]
hover 的事件是 mouseenter，不知道 selenium 里怎么处理的，自己研究下吧。

**Comment by haydonduan** [comment]
@yesmeck selenium 里面可以执行js代码，所以我想在selenium里面直接调用js，所以在浏览器的console上调试的时候<pre>$(".xxxx").hover()</pre>或者<pre>$(".xxxx").mouseenter()</pre>等等事件都试了还是没用，你可自己在console上调试一下，感谢~

**Comment by haydonduan** [comment]
I was successful with this issue! And I used the code :<pre>element.fire_event('mouseover')</pre>, I hope it can help others

**Comment by VectorM** [comment]
@yesmeck Just as an idea, maybe we can add hidden `<select>` html tag, and synchronize it with ant-select/rc-select?

**Comment by GQMai** [comment]
我用Selenide是这样写的
```
       $(".ant-select-selection-search-input").click();
       $$(".ant-select-item-option-content").filterBy(text("XXXXX")).get(0).click();
```
