### ISSUE TITLE
How to hide 'expend' Icon when Table's 'expandedRowRender' is used? 

### ISSUE THREAD

**Issue by pumpkin123** [ant-design/ant-design#10889]
I encoutered a problem when I used Table Compoent.
I want to achieve the following effects.
![image](https://user-images.githubusercontent.com/18691796/41284500-0af18b04-6e6c-11e8-9ccf-d4ac5bec5bff.png)
Not all data need to expand,so how to hide the Icon with red square?
![image](https://user-images.githubusercontent.com/18691796/41284633-751f903e-6e6c-11e8-9794-eea8327f7b14.png)

Does the Antd has a function to do it?
Please help me... All github's BIG GOD!

**Comment by dasoncheng** [comment]
@pumpkin123 you can refer here [example](https://codesandbox.io/s/antd-reproduction-template-forked-z4z4o?file=/index.js)
