### ISSUE TITLE
Report Error Using DatePicker component

### ISSUE THREAD

**Issue by felix307253927** [ant-design/ant-design#10888]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
deepin15.5  node8.11.0 npm5.6.0 react16.4.0 chrome63

### Reproduction link
[https://github.com/felix307253927/react16-webpack4.git](https://github.com/felix307253927/react16-webpack4.git)

### Steps to reproduce
> npm start

> open the link http://localhost:8000 in the browser

> and click the link DatePicker

### What is expected?
normal page

### What is actually happening?
 Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check the render method of `Picker`.

**Comment by chenshuai2144** [comment]
脚手架配置的问题，默认是  _rcTrigger2['default'] 
你配置的需要 _rcTrigger2['default']['default'],
你可能需要配置一下你的脚手架
参考这个插件  https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by felix307253927** [comment]
@chenshuai2144 我使用按钮和输入框等组件都是正常的,当我使用Form.Item,DatePicker等组件时就会报错,
我试了下babel-plugin-add-module-exports还是会报同样的错误

**Comment by felix307253927** [comment]
![image](https://user-images.githubusercontent.com/9459249/41326574-1c8b6f5c-6ef2-11e8-89dd-b4df8296ae9e.png)
![image](https://user-images.githubusercontent.com/9459249/41326614-56e1de84-6ef2-11e8-8a7b-16b4e68eac19.png)

而且我把antd组件打印出来看起来似乎是正常的,

**Comment by chenshuai2144** [comment]
第二层就有问题了，roadhog 来一波吧
