### ISSUE TITLE
Select Editor in column

### ISSUE THREAD

**Issue by nskiro** [ant-design/ant-design#10884]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We can use select editor in specify column

### What does the proposed API look like?
const columns = [
    {
        title: 'Group Name',
        dataIndex: 'group_name',
        editorRenderer: () => {
return <Select>....
}
}

**Comment by yesmeck** [comment]
Please refer to https://ant.design/components/table-cn/#components-table-demo-edit-row for editable table.
