### ISSUE TITLE
Modal内部固定高度内部无法滚动

### ISSUE THREAD

**Issue by daqi** [ant-design/ant-design#10885]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
chrome

### Reproduction link
[http://codepen.io/anon/pen/qmEwQr?editors=0010](http://codepen.io/anon/pen/qmEwQr?editors=0010)

### Steps to reproduce
打开连接

### What is expected?
可以滚动

### What is actually happening?
不可以

---
http://codepen.io/anon/pen/qmEwQr?editors=0010

**Comment by daqi** [comment]
https://github.com/ant-design/ant-design/issues/5777

**Comment by afc163** [comment]
Your codepen is not working.

**Comment by daqi** [comment]
@afc163 It's your

**Comment by daqi** [comment]
可能是chrome的问题，在笔记本上可以滚动，把窗口拖到外接屏幕上就滚动不了了，完全不知道是什么问题
