### ISSUE TITLE
Upload Componment support single or multiple select? [上传组件展示的项添加选项扩展]

### ISSUE THREAD

**Issue by YouNoCanNoBB** [ant-design/ant-design#10886]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i wander to single choise or miltiple choise what i had upload, just like http://www.wailian.work/images/2018/06/12/4864332e2a413b2d.png
[对文件展示添加选择扩展]

### What does the proposed API look like?
null

**Comment by YouNoCanNoBB** [comment]
上传的图片展示类型为“picture-card”时，可不可以给对应图片添加选项框？

**Comment by afc163** [comment]
Try `showUploadList={false}` then create your own upload files list.
