### ISSUE TITLE
Column headers misaligned when scroll.x = true and td has white-space: nowrap

### ISSUE THREAD

**Issue by dan-dr** [ant-design/ant-design#10893]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l3258y5w97)

### Steps to reproduce
1. Set `<Table scroll={{ x: true, y: 1000 }} />`
2. Add the css `.ant-table td { white-space: nowrap; }`
3. Optional - add css `.ant-table th { white-space: nowrap; }`
4. Resize the window so that horizontal scrollbar appears
5. Try to scroll

### What is expected?
Header columns should be aligned with the body columns

### What is actually happening?
Header columns are misaligned and different size, they scroll differently as well

**Comment by yesmeck** [comment]
It's a known issue, setting `white-space` to `nowrap` break the width constraint of the table cells. I'd recommend you set a proper number value for `x`.
