### ISSUE TITLE
select组件多选模式下，可否加个参数，超过N条显示  N这种标签，其他隐藏

### ISSUE THREAD

**Issue by yshysh123** [ant-design/ant-design#10899]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当用treeSelect或者Select组件时，选择内容过多时，会自动导致select换行，样式非常难把握

### What does the proposed API look like?
maxShow:N(number)  selet上最多展示的内容数量，超过该数量的选择内容用  N 标识

**Comment by yesmeck** [comment]
`maxTagCount`

**Comment by yshysh123** [comment]
TreeSelect有这个属性吗？

**Comment by yesmeck** [comment]
#9117

**Comment by lchunxiu** [comment]
it does not work in TreeSelect @yesmeck
