### ISSUE TITLE
Add feature that auto spicify width of column Table 

### ISSUE THREAD

**Issue by twisger** [ant-design/ant-design#10901]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I was tired to spicify each column's width when I use some features like Fix Header or Fix Columns, So I write a function to auto spicify column width by title length.

根据我的使用体验，一旦用到了固定表头功能，表格基本上100%会出现对齐问题，每次都手动指定列的的宽度很麻烦， 所以我写了一个根据title字符串的长度自动给列加宽度的函数。

另一个需要讨论的问题是，设定了宽度之后表格内容太长会导致表格行换行，体验不是很好。对于没有使用固定表头的表格，可以通过css修改td标签的white-space属性来实现自适应，但使用了固定表头的会出现对齐问题。
是否有一种方法能让表格根据内容自适应并且不会出现换行问题。现在使用的解决方法是将计算列宽时放大一定倍率，然后用Ellipsis组件做截断。但最理想的解决方案还是表格根据内容自适应，但Header的对齐问题似乎不好解决。

### What does the proposed API look like?
autoAddColumnWidth：是否自动添加列宽      
columnWidthRatio: 自动添加列宽时的计算倍率（如果根据内容自适应能实现就不需要这个了）

**Comment by yesmeck** [comment]
如果没有比较理想的解决方案，暂时不考虑加到组件里。有好的方案欢迎分享出来。
