### ISSUE TITLE
Hiding Table columns based on breakpoints

### ISSUE THREAD

**Issue by eduludi** [ant-design/ant-design#10904]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Even when the Table component shows an horizontal scroll on small screens, it can be frustrating on tables with many columns. In some cases, just hiding columns that are not important, can help to improve the user experience.

### What does the proposed API look like?
The columns can have properties to show or hide them in specific endpoints.

```jsx
const columns = [{
  title: 'Name',
  dataIndex: 'name',
  key: 'name',
}, {
  title: 'Age',
  dataIndex: 'age',
  key: 'age',
  hideOn: ['xs', 'sm'], // <-- Hide this column on small resolutions
}, {
  title: 'Address',
  dataIndex: 'address',
  key: 'address',
  visibleOn: ['lg', 'xl'],  // <-- Hide this column on larger resolutions (the "mobile first" approach)
}];

const dataSource = [...]

<Table dataSource={dataSource} columns={columns} />
```

**Comment by yesmeck** [comment]
You can use https://github.com/ReactTraining/react-media to achieve this feature.

**Comment by twisger** [comment]
I think you should achieve it by yourself, just need to filter columns by clientWidth,which will be more flexible.

**Comment by eduludi** [comment]
How can [`react-media`](https://github.com/ReactTraining/react-media) be used with [antd's `Table` API](https://ant.design/components/table/#API)?

I tried several variants, and it doesn't seems to work:

[![Edit Antd's Tables and Media Queries](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7zovykxoz1)

**Comment by yesmeck** [comment]
https://codesandbox.io/s/r384nmn4n

**Comment by eduludi** [comment]
Thanks for your quick answer @yesmeck! 

Still I think this will be a nice feature to use, also to keep consistency with other components that have built-in breakpoint support, like `Layout`, `Layout.Sider` and `Grid`.

**Comment by eduludi** [comment]
I created an alternative solution, based on @yesmeck's one: https://codesandbox.io/s/nn1y6q1rv4
