### ISSUE TITLE
table filter indexof bug

### ISSUE THREAD

**Issue by allengzh** [ant-design/ant-design#10900]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
chrome

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
table组件，筛选项，如果只允许选择唯一一个，如果筛选项里的值有1,2,12然后选择12会把1、2、12都选上

### What is expected?
只选上12

### What is actually happening?
1、2、12都选上了

---
查看源码，发现是filterdropdown源码里indexof的问题，目测本来是为了适配多选的数组的，但现在导致单选的时候字符串匹配出错了；建议修复或者在antd文档里指出筛选项字符串不能有包含关系（不建议）

**Comment by yesmeck** [comment]
用 `onFilter` 自己实现筛选逻辑。

**Comment by allengzh** [comment]
可能我描述的你还没理解，我不是筛选的时候没把筛选项匹配出来；而是筛选项匹配对了，但是在筛选菜单重新打开数据回显到下拉菜单的时候，你们用了indexOf匹配，出现了这个问题

**Comment by allengzh** [comment]
造成这块异常的原因是我未按照文档上filteredValue应该是个数组的形式存储造成，而是设置成了字符串，然后菜单渲染的时候indexOf查找就按照字符串查找，导致渲染出错，抱歉哈~已解决~
![image](https://user-images.githubusercontent.com/4568460/41387720-075b17b2-6fbb-11e8-9ee9-30c52a1210f5.png)
