### ISSUE TITLE
Should the InputNumber have a fixed width?

### ISSUE THREAD

**Issue by rwinzhang** [ant-design/ant-design#10906]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ant-design/ant-design/blob/713a0bcdc50353f4ede0eeae80d070046169db64/components/input-number/style/index.less#L15

The `InputNumber` and `Input` will have the same style, a stretched width

### What does the proposed API look like?
Change the `InputNumber` width to 100%

**Comment by yesmeck** [comment]
It's a breaking change, we'd have to keep it at present. You set it to `100%` by yourself.
