### ISSUE TITLE
Carousel 在chrome下flex布局时宽度错误

### ISSUE THREAD

**Issue by abingdz** [ant-design/ant-design#10902]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
chrome:67.0.3396.87（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m9l2y8o7y)

### Steps to reproduce
<div style={{ display: 'flex'}}>
  <Carousel autoplay>
    <div><h3>1</h3></div>
    <div><h3>2</h3></div>
    <div><h3>3</h3></div>
    <div><h3>4</h3></div>
  </Carousel>
  </div>

### What is expected?
在固定位置展示

### What is actually happening?
移出了位置

**Comment by afc163** [comment]
https://codesandbox.io/s/6jpo2975yw

It is a css problem than antd's.

```diff
.ant-carousel {
  flex: 1;
+ max-width: 100%;
}
```

**Comment by fwh1990** [comment]
> https://codesandbox.io/s/6jpo2975yw
> 
> It is a css problem than antd's.
> 
> ```diff
> .ant-carousel {
>   flex: 1;
> + max-width: 100%;
> }
> ```

@afc163  根据您提供的sandbox，我fork了一个新的 https://codesandbox.io/s/lucid-nobel-pnvce ，当flex有多层时，走马灯依旧是无限宽度，而真实业务中flex肯定是会嵌套的

**Comment by jacintoface** [comment]
这个问题有解决方案了吗

**Comment by jacintoface** [comment]
https://github.com/akiran/react-slick/issues/1887

**Comment by fwh1990** [comment]
@afc163 抱歉，还是走马灯的问题， https://codesandbox.io/s/misty-browser-nmt31

在走马灯里input输入框文字选中后，再点击文字，选中状态不会消失，光标也插入不了。这个行为在走马灯外面是不会的，sandbox里可以直接演示

**Comment by tom-chanafanghua** [comment]
同样遇到该问题 被迫使用浮动
