### ISSUE TITLE
手动编译style中的less报错

### ISSUE THREAD

**Issue by lockelee1015** [ant-design/ant-design#1090]
10:23:13 AM LESS CSS Compiler Error
            tooltip.less: Parse Error: Unrecognised input (line 25, column 22) near
            // Base class
            .@{tooltip-prefix-cls} {
            position: absolute;

用的是idea的less compile编译的，然后编译到calendar也会报错。用webpack的loader也会报unrecognised input

**Comment by afc163** [comment]
编译入口 `style/index.less`，不要编译单独的文件。
