### ISSUE TITLE
Avatar text not centered inside of Popover when using "visible" prop

### ISSUE THREAD

**Issue by jurajzoric** [ant-design/ant-design#10917]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
Windows 10, Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1yvjrvmr73)

### Steps to reproduce
See sandbox link to minimal reproduction. Try to hover over the button multiple times. Only the first time text inside of an Avatar will be centered correctly.
Problem is with using visible={this.state.popoverVisible}. If you remove that code, it will work properly. 

### What is expected?
Avatar contents should be centered no matter how many times user opens a Popover

### What is actually happening?
Avatar contents are centered only first time Popover opens, after that they are misplaced to the right.

---
To fix it in my project I added this code: 
 span.ant-avatar-string {
      position: static !important;
    }

**Comment by yesmeck** [comment]
Avatar needs to get the width of text to decide whether to scale it. Unfortunately, it happens before the animation finished, so it gets the wrong width. Can not figure out an appropriate fix for this situation now. As a workaround, you can trigger the scale computation manually by calling `forceUpdate` after `setState`.

```javascript
handleVisibleChange = popoverVisible => {
  this.setState({ popoverVisible: popoverVisible }, () => this.forceUpdate());
};
```
