### ISSUE TITLE
upload bug

### ISSUE THREAD

**Issue by rongzhx123** [ant-design/ant-design#10911]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
无

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
设置upload的accept 为‘text/plain’

### What is expected?
只能上传纯文本（eg. .txt）

### What is actually happening?
可以上传js文件

**Comment by afc163** [comment]
I don't think it is a bug.
