### ISSUE TITLE
Is this a BUG of the Row Component ?

### ISSUE THREAD

**Issue by qxchen6** [ant-design/ant-design#10915]
### Version
3.6.2

### Environment
reactJS,Antd.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0o10ozrx7v)

### Steps to reproduce
For some reason , I make a Layout without using AntD's Layout Component . 
It's made up of simple HTMLs .
It has two parts : left and right . The left part should be set a certainly width and the right part should be responsive .
But when I finished the Layout , the Row component went wrong ... the first Row Component had a full-height ... 

**[Look this at codesandbox](https://codesandbox.io/s/0o10ozrx7v)**

### What is expected?
Row Component's height should not be full-height .

### What is actually happening?
The first Row Component's height is full-height .

Picture Desc

![image](https://user-images.githubusercontent.com/25380801/41411388-3f833864-700f-11e8-9d0c-bae0651fb61a.png)

**Comment by afc163** [comment]
Nope, it is a css issue.

https://codesandbox.io/s/nw7k6q4yjp
