### ISSUE TITLE
select 的search模式下动态请求数据渲染option,  会出现不能实时更新下拉选项内容，要失焦以后再聚焦或者清空输入框内容才显示上次搜索的结果

### ISSUE THREAD

**Issue by lvxue-shirly** [ant-design/ant-design#10918]
![image](https://user-images.githubusercontent.com/16660437/41416099-b693c092-701c-11e8-9ca3-0433807d2e04.png)
![image](https://user-images.githubusercontent.com/16660437/41416129-c656b516-701c-11e8-850b-d24af61a488a.png)

**Comment by Xiongqi-XQ** [comment]
Select 加上  filterOption={false}

**Comment by mixj93** [comment]
遇到了同样的问题，感谢~

**Comment by lovemegowin** [comment]
同样的问题 +1

**Comment by DaphneChang** [comment]
遇到了同样的问题+1
用@lovemegowin 的方法成功了，万分感谢！

**Comment by cxyuns** [comment]
设置了filterOption={false}，但是option还是会保留一条上次的搜索的，是什么问题？
