### ISSUE TITLE
Message data-* and aria-* props

### ISSUE THREAD

**Issue by matthewlein** [ant-design/ant-design#10919]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like the ability to add data-* and aria-* attributes to the rendered Message html.

### What does the proposed API look like?
For Message, that would require another parameter to the message methods:
`message.success(content, [duration], onClose, props)`

Which then ultimately gets passed through to RcNotification, which will be updated too.

**Comment by matthewlein** [comment]
I'm willing to do all the work for this, I just want to know that this is an acceptable approach before I start.

**Comment by matthewlein** [comment]
I have just over a week more available to do this this, any feedback?

**Comment by afc163** [comment]
Try this as workaround.

```jsx
message.success(<div data-xxx="xxx">xxxx</div>, [duration], onClose)
```

**Comment by matthewlein** [comment]
True. I didn't think of that at the moment. Maybe not ideal for aria attributes, but fine for now.
