### ISSUE TITLE
React warned unique key when set unique key and repeated value to AutoComplete.Option component.

### ISSUE THREAD

**Issue by CeleKing** [ant-design/ant-design#10912]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
MacOS10.13.5 (17F77) Chrome

### Reproduction link
[https://codepen.io/CeleKing/pen/gKxLbq?&editors=001](https://codepen.io/CeleKing/pen/gKxLbq?&editors=001)

### Steps to reproduce
when click AutoComplete input 

### What is expected?
set unique key and repeated value to Option could be normal use

### What is actually happening?
warn unique key

**Comment by afc163** [comment]
value should be unique.

**Comment by Evan-Leee** [comment]
May I ask why the value should be unique?  and why the key at the option will be replaced by value? @afc163

**Comment by chenshuai2144** [comment]
@Evan-Leee https://reactjs.org/docs/lists-and-keys.html
