### ISSUE TITLE
The TreeSelect should add a onClose or onHide event?

### ISSUE THREAD

**Issue by chenxiaochun** [ant-design/ant-design#10913]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I choose multiple choices and after close the treeSelect, it will trigger a search event.

### What does the proposed API look like?
onClose or onHide

**Comment by zombieJ** [comment]
Here is an internal api for this:
```jsx
onDropdownVisibleChange={(visible) => {
  console.log('->', visible);
  return true; // Return false will prevent visible change
}}
```

**Comment by chenxiaochun** [comment]
Thank you very much. But why i not found this api in the doc? Although I have been very careful to look for it.😂
