### ISSUE TITLE
optimize Table rendering performance

### ISSUE THREAD

**Issue by qhxin** [ant-design/ant-design#10926]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
in my component, i use antd/Table. it will rerender every row every time i set props, that's expensive, so i want a prop like the `components: { body: { row } }` in rc-table  to set TableRow component as a PureComponent

### What does the proposed API look like?
give us a prop like `components` in rc-table

**Comment by afc163** [comment]
You should create issue in http://github.com/react-component/table
