### ISSUE TITLE
TreeSelect dropdownMatchSelectWidth属性无效，弹出框宽度无法控制

### ISSUE THREAD

**Issue by liuhong1happy** [ant-design/ant-design#10927]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
浏览器版本

### Reproduction link
[https://ant.design/components/tree-select-cn/#API](https://ant.design/components/tree-select-cn/#API)

### Steps to reproduce
<TreeSelect dropdownMatchSelectWidth={false} dropdownStyle={{ width: '300px', minWidth: '300px' }} style={{ width: '100%' }}></TreeSelect>

### What is expected?
输入框宽度100%，但是弹出框不需要100%，仅需要300px

### What is actually happening?
输入框宽度100%，但是弹出框与输入框等宽

---
输入框同宽之后，关闭弹出框的区域变小，很难关闭弹出框。

**Comment by yutingzhao1991** [comment]
reproduce link: https://codesandbox.io/s/nkqwpxnpjl .

It only exist when dropdown with less then select width. because a minWidth style prop https://github.com/react-component/tree-select/blob/master/src/SelectTrigger.jsx#L314

@zombieJ Is it's by design or a bug?

**Comment by zombieJ** [comment]
@liuhong1happy @yutingzhao1991 ，历史原因。`dropdownMatchSelectWidth` 最初只有 true 才会影响弹出框宽度。后来变成 true / false 只会影响 width / minWidth。
我会在重构里加一个判断，如果有了 style 就用用户定义的。

**Comment by zombieJ** [comment]
@yutingzhao1991 ,
我会给调整一下 `dropdownMatchSelectWidth` 属性，默认 minWidth， true 为 width， false 就不设置。
