### ISSUE TITLE
Form 内容校验报错

### ISSUE THREAD

**Issue by LazyJoke** [ant-design/ant-design#10936]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
win10专业版、谷歌 67.0.3396.87（正式版本)、 React (V-16.4.0)

### Reproduction link
[https://www.colorfullife.club/login](https://www.colorfullife.club/login)

### Steps to reproduce
getFieldDecorator(USER_PSW, {
     rules: [{
           required: true,
            whitespace: true,
            message: '密码格式错误，请检查！',
            pattern: /^(?![A-Z] $)(?![a-z] $)(?!\d $)(?![\W_] $)\S{6,16}$/
       }]
   })(<Input  type='password' placeholder='密码' /> )

### What is expected?
输入密码时，控制台不应该报错

### What is actually happening?
输入密码时，控制台报错，影响输入

---
开发模式下控制台报错：Uncaught TypeError: Cannot read property 'push' of undefined

**Comment by yangxiaolin** [comment]
@LazyJoke  hello,  as your code
```js
getFieldDecorator(USER_PSW, {
     Rules: [{
           Required: true,
            Whitespace: true,
            Message: 'The password is in the wrong format, please check! ',
            Pattern: /^(?![A-Z] $)(?![a-z] $)(?!\d $)(?![\W_] $)\S{6,16}$/
       }]
   })( /* you should add some component in here, such as Input, Select, Checkbox and etc */ )
```
for detail, you can see [here](https://codesandbox.io/s/mqo8967949)

**Comment by yangxiaolin** [comment]
@afc163 you can close this issue
