### ISSUE TITLE
Are you planning to add onClick or onSelect feature to List Component?

### ISSUE THREAD

**Issue by leehen** [ant-design/ant-design#10932]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When click on a list item, it would be nice to have "selected" className, like it does in Menu component. Maybe create a parameter called "selectable" or "clickable"? Do you have any plan to implement this?

### What does the proposed API look like?
List clickable={true}
     List.Item onClick={'some functions'} /
/List

**Comment by chenshuai2144** [comment]
Why do you need？

**Comment by yesmeck** [comment]
`<List.Item onClick={() => console.log('click')}>{item}</List.Item>`

List.Item can accept any valid div props.

**Comment by lostpebble** [comment]
@yesmeck actually it doesn't want to allow me to add regular props with Typescript.

```
Error:(110, 46) TS2339: Property 'onClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Item> & Readonly<{ children?: ReactNode; }> & Readonly<ListItemProps> & Pick<InferProps<{ column: Requireable<string | number>; xs: Requireable<...>; ... 4 more ...; xxl: Requireable<...>; }>, "column" | ... 5 more ... | "xxl">'.
```

Also, is there no way to have hover effects or anything like that on list items? It seems like lists in Ant Design have not been designed to be used as clickable / selectable items in a list - which I think is one of the main uses of a list..

**Comment by undead85** [comment]
When click on a list item with a card, it would be nice to have "selected" className, like it does in Menu component!
