### ISSUE TITLE
Popover 控件在 react-d3-tree 的HTML节点上定位错误

### ISSUE THREAD

**Issue by aiportal** [ant-design/ant-design#10933]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
    "react": "16.3.2",     "react-d3-tree": "1.10.6",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/womv44wpl)

### Steps to reproduce
1、使用 react-d3-tree 的 nodeLabelComponent 创建 html 节点。
2、在节点上使用 Popover。
3、鼠标悬停时发现 Popover 定位错误。
4、屏幕左边 x 方向偏移较小，屏幕右边 x 方向偏移较大，y 方向偏移量类似，屏幕上方偏移小，屏幕下方偏移多。

### What is expected?
找到原因，找到修复办法。

### What is actually happening?
已确定是 antd 引用的 rc-tooltip 库 计算错误，更具体的原因尚未找到。

https://github.com/react-component/tooltip/issues/126

**Comment by chenshuai2144** [comment]
你的 demo 里面没有使用Popover

**Comment by yesmeck** [comment]
要引入 css https://codesandbox.io/s/o9n686kqoy

**Comment by aiportal** [comment]
没在 index.js 里引用 Popover，是在 tree-node.jsx 里引用的。

tree-node.jsx: 

`
import React from "react";
import { Popover } from "antd";

type Props = {
  nodeData: Object
};

export default class NodeLabel extends React.PureComponent {
  props: Props;

  render() {
    const { nodeData } = this.props;

    return (
      <Popover title={nodeData.name}>
        <div style={{ backgroundColor: "silver" }}>
          <h2>{nodeData.name}</h2>
        </div>
      </Popover>
    );
  }
}
`
