### ISSUE TITLE
Menu with dark theme does not underline item during hover

### ISSUE THREAD

**Issue by brianbwong** [ant-design/ant-design#10941]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The light theme menu has the nice feature that when hovering over a menu item, a blue border-bottom appears. However there is no such feedback in the dark theme. 

### What does the proposed API look like?
The menu with dark theme either automatically has a border-bottom when hovered over, or there is a boolean option for this underline.

**Comment by afc163** [comment]
It is by designed, so we won't support this.
