### ISSUE TITLE
Table组件不支持对多个字段进行排序

### ISSUE THREAD

**Issue by ralphya0** [ant-design/ant-design#10946]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在很多场景下需要对表格的多个字段进行排序，但目前antd不支持

### What does the proposed API look like?
在Table组件的Column允许保留多字段排序状态

**Comment by yutingzhao1991** [comment]
It looks complicated, have any example for the Interactive behavior?

**Comment by Gpia** [comment]
Only one column can effect in fact, how can you sort something while column 'A' is asc and column 'B' is dec ?

**Comment by yesmeck** [comment]
#5057

**Comment by ralphya0** [comment]
@yutingzhao1991  @Gpia @yesmeck  
Thanks for your replies. We have build a data analysis system, which allows users querying data in any possible ways to meet their requirements, e.g,  grouping data by col_1 and col_2, then sorting them by col_3 and col_4. We process data(e.g, grouping and sorting) in backend(and also in database), so you don't have to worry about the heavy lifting works, if antd could maintain multiple sorting states will be great! 
In general, antd maintains all sorting states, and the data are taken cared by server-end.

**Comment by yoyo837** [comment]
我也有类似的需求：
1. `sorter: function(a, b) { ... }`：我认为多个字段同时排序的实现应该是按优先级，先使用优先的字段排序，在优先字段的顺序下局部使用另一个字段排序; 
2. `true`，服务器排序，服务器实现可能也是参照上面的逻辑；

My English is very poor and I can't provide an accurate English translation of the above.

**Comment by yoyo837** [comment]
3. 如果antd不考虑支持，请开放给我们自己实现的入口，不直接限制为只能使用单字段排序亦可；

**Comment by yoyo837** [comment]
This is what I want: https://github.com/ant-design/ant-design/issues/5057#issuecomment-346167538

**Comment by YaoKaiLun** [comment]
Any solutions there?

**Comment by afc163** [comment]
antd v4 Table had supported multiple sorters. https://github.com/ant-design/ant-design/issues/21656
