### ISSUE TITLE
Documentation error in component "Tree"

### ISSUE THREAD

**Issue by KidyovrS** [ant-design/ant-design#10949]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
Any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q9q8n5m499)

### Steps to reproduce
Use the example codes of "SearchTree" of "Tree" component in `antd` documentation https://ant.design/components/tree-cn/

### What is expected?
Values of `item.title` are displayed on UI.

### What is actually happening?
Values of `item.key` are displayed on UI.

---
This is just an error in documentation, not an error of `antd` library itself.

**Comment by yesmeck** [comment]
It's intended to use `key` in the demo.

https://codesandbox.io/s/82n79k11mj

**Comment by KidyovrS** [comment]
Is that really the case? It's very confusing since all other examples use `title` and I seriously don't think showing `key` on UI make any sense. If it's truly "by design", you could keep this issue closed.

**Comment by yesmeck** [comment]
I've changed `key` to `title`, I guess the original reason to use `key` is the `key` and `title` have the same value.
