### ISSUE TITLE
Table在选择每列中的文字时也出发了onRow

### ISSUE THREAD

**Issue by Liqiankun** [ant-design/ant-design#10942]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以选择每列的文字了

### What does the proposed API look like?
```
<Table 
 canCopyOnColumns
/>
```

![onrowclick](https://user-images.githubusercontent.com/11532418/41571631-a35d2fd0-73a6-11e8-98a6-010797cfdf8b.gif)

**Comment by afc163** [comment]
There is no `canCopyOnColumns` prop for Table.

**Comment by afc163** [comment]
It is hard to implement this feature for table, please send PR to us if you have perfect solution. I am gonna close this now.

**Comment by Liqiankun** [comment]
Well!

**Comment by afc163** [comment]
Try

```jsx
render(text) {
  return <span onClick={e => e.stopPropagation()}>{text}</span>;
}
```

```jsx
render(text) {
  return <span onMouseDown={e => e.stopPropagation()}>{text}</span>;
}
```

**Comment by Liqiankun** [comment]
Ok
