### ISSUE TITLE
在Modal对话框，关闭得时候出现这样的效果，虽然很炫酷但不是我想要的

### ISSUE THREAD

**Issue by xyy7260** [ant-design/ant-design#10958]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
mac开发、谷歌和火狐、"react": "^16.0.0"、 "antd": "^3.6.2"

### Reproduction link
[https://github.com/xyy7260/notes-/blob/master/9786B6D8A70BFC299A5FA8A73D87FFF2.gif](https://github.com/xyy7260/notes-/blob/master/9786B6D8A70BFC299A5FA8A73D87FFF2.gif)

### Steps to reproduce
在结束对话框，出现了旋转效果，并不是我想要的

### What is actually happening?
我想要的是antd 官方的modal那样结束效果

---
自己也降低过antd的版本，并没有压缩使用的是JS编写

**Comment by xyy7260** [comment]
代码就是 demo上复制下来就会变成这个样子的

**Comment by yesmeck** [comment]
可能是跟其他样式的冲突，没重现的话没法帮你。

**Comment by afc163** [comment]
MacOS 的版本是？可能和 #9731 有关。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10948#issuecomment-398608390

**Comment by xyy7260** [comment]
刚刚把所有样式去掉，然后测试一下 还是出现问题，并且在safari 浏览器也是这样子。
怀疑是不是我下载一些东西造成的呢
"devDependencies": {
    "autoprefixer": "^7.1.5",
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-plugin-import": "^1.6.7",
    "babel-plugin-react-transform": "^3.0.0",
    "babel-plugin-transform-decorators-legacy": "^1.3.5",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-1": "^6.24.1",
    "bundle-loader": "^0.5.5",
    "clean-webpack-plugin": "^0.1.17",
    "css-loader": "^0.28.7",
    "cssnano": "^3.10.0",
    "eslint": "^4.9.0",
    "eslint-loader": "^1.9.0",
    "extract-text-webpack-plugin": "^3.0.1",
    "file-loader": "^1.1.5",
    "grunt": "^1.0.1",
    "grunt-cli": "^1.2.0",
    "grunt-contrib-compass": "^1.1.1",
    "html-webpack-plugin": "^2.30.1",
    "image-webpack-loader": "^3.4.2",
    "json-loader": "^0.5.7",
    "koa": "^1.2.2",
    "koa-router": "^5.4.0",
    "load-grunt-tasks": "^3.5.2",
    "node-sass": "^4.5.3",
    "open-browser-webpack-plugin": "0.0.5",
    "postcss-loader": "^2.0.8",
    "react-transform-hmr": "^1.0.4",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.19.0",
    "time-grunt": "^1.4.0",
    "url-loader": "^0.6.2",
    "webpack": "^3.8.1",
    "webpack-dev-server": "^2.9.2",
    "webpack-merge": "^4.1.0"
  },
  "dependencies": {
    "antd": "^3.6.2",
    "babel-polyfill": "^6.26.0",
    "isomorphic-fetch": "^2.2.1",
    "mobx": "^5.0.0",
    "mobx-react": "^5.2.3",
    "npm": "^5.8.0",
    "prop-types": "^15.6.1",
    "query-string": "^6.1.0",
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-router-dom": "^4.2.2",
    "swiper": "^2.7.0",
    "to": "^0.2.9",
    "update": "^0.7.4"
  }

**Comment by xyy7260** [comment]
@afc163 
刚刚把所有样式去掉，然后测试一下还是出现问题，并且在safari浏览器也是这样子。
怀疑是不是我下载一些东西造成的呢
“devDependencies”：{ 
“autoprefixer”：“^ 7.1.5”，
“babel -core“：”^ 6.26.0“，
”babel-loader“：”^ 7.1.2“，
”babel-plugin-import“：”^ 1.6.7“，
”babel-plugin-react-transform“：” ^ 3.0.0“，
”babel-plugin-transform-decorators-legacy“：”^ 1.3.5“，
”babel-preset-es2015“：”^ 6.24.1“，
”babel-preset-react“：”^“ 6.24.1“，
”babel-preset-stage-1“：”^ 6.24.1“，
”bundle-loader“：”^ 0.5.5“，
”clean-webpack-plugin“：”^ 0.1.17“ 
“css-loader“：”^ 0.28.7“， 
”cssnano“：”^ 3.10.0“，
”eslint“：”^ 4.9.0“，
”eslint-loader“：”^ 1.9.0“，
”extract- text-webpack-plugin“：”^ 3.0.1“，
“file-loader”：“^ 1.1.5”，
“grunt”：“^ 1.0.1”，
“grunt-cli”：“^ 1.2.0”，
“grunt-contrib-compass”：“^ 1.1.1 “，
”html-webpack-plugin“：”^ 2.30.1“，
”image-webpack-loader“：”^ 3.4.2“，
”json-loader“：”^ 0.5.7“，
”koa“：” ^ 1.2.2“，
”koa-router“：”^ 5.4.0“，
”load-grunt-tasks“：”^ 3.5.2“，
”node-sass“：”^ 4.5.3“，
”open- browser-webpack-plugin“：”0.0.5“，
”postcss-loader“：”^ 2.0.8“，
”react-transform-hmr“：”^ 1.0.4“，
”sass-loader“：“^ 6.0.6”， 
“style-loader”：“^ 0.19.0”，
“time-grunt”：“^ 1.4.0”，
“url-loader”：“^ 0.6.2”，
“webpack” ：“^ 3.8.1”，
“webpack-dev-server”：“^ 2.9.2”，
“webpack-merge”：“^ 4.1.0” 
}，
“依赖”：{ 
“antd”：“^ 3.6.2”，
“babel-polyfill”：“^ 6.26.0”，
“isomorphic-fetch”：“^ 2.2.1”，
“mobx”：“^ 5.0。 0“，
”mobx-react“：”^ 5.2.3“，
”npm“：”^ 5.8.0“，
”prop-types“：”^ 15.6.1“，
”query-string“：”^ 6.1。 0“，
”react“：”^ 16.0.0“，
”react-dom“：”^ 16.0.0“，
”react-router-dom“：”^ 4.2.2“，
”swiper“：”^ 2.7。 0“，
”to“：”^ 0.2.9“，
”update“：”^ 0.7.4“ 
}

**Comment by xyy7260** [comment]
我知道什么原因了，是在 webpack 配置中  "plugins": ["transform-decorators-legacy"],造成的
但是如果不配置那么mobx的装饰无法使用， 如果配置了那么就会出现问题
