### ISSUE TITLE
Dragger breaks when multiple files are selected and some are invalid

### ISSUE THREAD

**Issue by aseemgautam** [ant-design/ant-design#10953]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
OSX High Sierra, Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9owl6vyqno)

### Steps to reproduce
Dragger is configured to allow only jpeg files. `Multiple` attribute is set to true.
Click on the dragger and select one JPG file and any other file. One valid and one invalid file. 

### What is expected?
Begin upload for valid file and reject invalid file.

### What is actually happening?
An exception the thrown in the console - Warning: Each child in an array or iterator should have a unique "key" prop. This error is also throws sometimes - Encountered two children with the same key, `rc-upload-1529412272836-3`

---
Only occurs when valid and invalid files are selected. Works fine when all files are valid or invalid.

**Comment by aseemgautam** [comment]
Any update on this issue?

**Comment by zombieJ** [comment]
Hmmm, let me check...
