### ISSUE TITLE
AutoComplete自定义输入组件的样式问题

### ISSUE THREAD

**Issue by ybning** [ant-design/ant-design#10956]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
Win7 64位，Chrome 66.0.3359.117

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/724lnwykj0)

### Steps to reproduce
AutoComplete的placeholder内容 与 AutoComplete自定义输入组件Input的前缀prefix 重叠

![1](https://user-images.githubusercontent.com/3725612/41639332-e7a1bf0a-748f-11e8-8331-11d48b19089e.png)

```
      <AutoComplete
        dataSource={dataSource}
        style={{ width: 200 }}
        onSelect={onSelect}
        onSearch={this.handleSearch}
        placeholder="input here"
      >
        <Input prefix={<Icon type="plus" />} />
      </AutoComplete>
```

### What is expected?
不重叠

### What is actually happening?
重叠了

**Comment by ybning** [comment]
@afc163

**Comment by ybning** [comment]
@yesmeck

**Comment by Evan-Leee** [comment]
@ybning placeholder 加到input上就好了，autocomplete上就不用加placeholder了
