### ISSUE TITLE
ButtonGroup button border does not fade out correctly after hover

### ISSUE THREAD

**Issue by menberg** [ant-design/ant-design#10951]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
Chrome 67, macOS 10.12.6

### Reproduction link
[https://ant.design/components/button/](https://ant.design/components/button/)

### Steps to reproduce
https://codesandbox.io/s/912qpl35oy
Hover with mouse over buttons, watch border transition after unhovering.

### What is expected?
Blue coloured border highlight of hovered button should fade out nicely after moving away from the button.

### What is actually happening?
Right border side does not fade out nicely. Seems to be a z-index problem with the next button.

**Comment by ZWkang** [comment]
button group.
border use margin-left: -1px to cover the rest border size.
in focus , antd give the element a z-index: 2;
default the button is z-index: auto;
when the mouse not focus the button .the z-index change to auto
this problem work with this.

in bootstrap, bulma find same problem with using transition.
Suggest:
1. remove the border-color transition.
2. give button a small z-index. like 0 1

**Comment by afc163** [comment]
Button.Group is not recommended to use in antd 4.x, I will pass this issue.
