### ISSUE TITLE
Typescript：Cannot set className for TreeNode.

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#10950]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
Windows 10 1803

### Reproduction link
[https://ant.design/components/tree/](https://ant.design/components/tree/)

### Steps to reproduce
<TreeNode className="node_leaf" />

### What is expected?
No error when compile

### What is actually happening?
 TS2339: Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<AntTreeNodeProps, ComponentState, any>>

---
react 16.4
react-dom 16.4

**Comment by CareyToboo** [comment]
@zombieJ  <Tree > is already support the 'className' prop, but the sub component 'TreeNode' needs 'className' prop, too. eg. <Tree.TreeNode className="xxx" />
