### ISSUE TITLE
Set labelInvalue in select component, placeholder dispaly incorrect！

### ISSUE THREAD

**Issue by littleLane** [ant-design/ant-design#10961]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.1.4

### Environment
mac 10.13.5 , chrome 67.0.3396.87 , react 16.2.0

### Reproduction link
[https://codepen.io/littlelane/pen/eKVyRM?editors=0010](https://codepen.io/littlelane/pen/eKVyRM?editors=0010)

### Steps to reproduce
```javascript

		const mipayFormOptios = [
			{
				label: '医保中心',
				type: 'select',
				placeholder: '请选择医保中心',
				field: 'accountNo',
				initialValue: handleType === 'update' ? {key: thisRecord.accountNo, label: thisRecord.medicalCenterName } : {key: ''},
				options: { options: medicalList, label: 'medicalCenterName', value: 'medicalCenterNo' },
				labelInValue: true,
				rules: [{
					required: true, message: '请选择医保中心',
				}]
			}, {
				label: '医疗机构编号',
				type: 'input',
				placeholder: '请输入医疗机构编号',
				field: 'medicalJournalNo',
				initialValue: thisRecord.medicalJournalNo,
				maxLength: 40,
				rules: [{
					required: true, message: '请输入医疗机构编号',
				}, {
					pattern: CODE_REG, message: '请输入长度最大为40位的包含数字、字母和下划线的编码'
				}]
			}
		]
```

### What is expected?
expect when set labelInvalue in select component，the select accept type of value  not only {key: string | number, label: ReactNode}，but also {key: string | number | undefined, label: ReactNode} ! Because the select component only set undefined, the placeholder can display correct！

### What is actually happening?
the select accept value type only {key: string | number, label: ReactNode}, when select component init the placeholder can't display correct！

**Comment by yesmeck** [comment]
I think it's by design, we consider empty string is a valid value.

**Comment by littleLane** [comment]
I know ! But now the problem is when i set `labelInValue: true`, the `initialValue` only can set `{key: string | number, label: ReactNode}`。I want to show `placeholder`, but now it's impossible，because the `Select Component` only set `undefined`( which is {key: undefined, label: ReactNode}), the placeholder can display correct，but the property of key can't set `undefined`!

**Comment by yesmeck** [comment]
设置 `labelInValue` 后，`value` 还是可以为 `undefined` 的。

**Comment by rynjwssl** [comment]
I am encountering this issue as well. There won't always be a default value that is supposed to be selected on initial load, and there is a specific placeholder message we would like to show in it's place. 

I've seen on some other GitHub issues that by replacing the value with `undefined` the placeholder displays correctly. I can't seem to replicate that, and it doesn't seem like an appropriate solution long-term. Have there been any updates on this?

**Comment by lovemegowin** [comment]
这个bug没修复就这么关了。。。。

**Comment by Molly6943** [comment]
I got the same problem, dose anynoe have a solution?

**Comment by lovemegowin** [comment]
> I got the same problem, dose anynoe have a solution?

Just set value: undefiend @Molly6943

**Comment by ltbyce** [comment]
我觉得这个不是归为设计问题，这应当看做是一个bug

**Comment by gaoxuerong** [comment]
所以问题怎嘛解决？？？

**Comment by xingorg1** [comment]
so???
