### ISSUE TITLE
table的row不支持设置tooltip

### ISSUE THREAD

**Issue by yy923683900** [ant-design/ant-design#10963]
table的row不支持render，如果想让鼠标移到table的一行上面的时候出现tooltip提示，现在的table很难实现类似的需求，所以能否支持rowRender属性。

**Comment by BinaryBingo** [comment]
这个有解决办法么？

**Comment by snowshoes** [comment]
It did support in `render()` method of `ColumnProps`

**Comment by Zhang-haohua** [comment]
同问,,
