### ISSUE TITLE
The key value of the getCheckboxProps attribute of the table component is not placed in the selectedRowKeys

### ISSUE THREAD

**Issue by roser240** [ant-design/ant-design#10966]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
window7 (64)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pj9z0op760)

### Steps to reproduce
1.默认选中
2.点击行无法对这行进行操作

### What is expected?
添加默认属性，也可以通过点击行或者多选框进行操作

### What is actually happening?
点击多选框可以，但是点击行没有效果

**Comment by zombieJ** [comment]
Should set `selectedRowKeys` to default value instead of change Checkbox directly: https://codesandbox.io/s/m7z5mw8kqx

Will add warning for this.
