### ISSUE TITLE
表格组件支持下载功能

### ISSUE THREAD

**Issue by toxmc** [ant-design/ant-design#10967]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望可以下载渲染出来的表格，保存格式为csv或xls

### What does the proposed API look like?
无

**Comment by yesmeck** [comment]
https://stackoverflow.com/questions/14964035/how-to-export-javascript-array-info-to-csv-on-client-side
