### ISSUE TITLE
Button wrapped in <Upload /> can still triggers when it's disabled on IE edge.

### ISSUE THREAD

**Issue by Innermadness** [ant-design/ant-design#10962]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
win10 x64，Microsoft Edge 42.17134.1.0，react 16.2.0

### Reproduction link
[https://codepen.io/innermadness/pen/eKVMrg](https://codepen.io/innermadness/pen/eKVMrg)

### Steps to reproduce
```
<Upload
  accept=".jpg,.png,.pdf"
  action="/api/upload"
>
  <Button disabled type="primary" icon="upload">download</Button>
</Upload>
```
On IE edge，the disabled Button triggers when it's clicked on content('download') . 

### What is expected?
The disabled Button would not trigger on IE Edge.

### What is actually happening?
The disabled Button still triggers  on IE Edge (it's okay on latest chrome and firefox).

---
Upload组件中的Button在disabled的情况下仍然能点击按钮文字弹出选择文件（点击icon或者按钮空白处都不会），目前只在IE edge上有这个问题，最新版的chrome和firefox没复现。

**Comment by zombieJ** [comment]
Upload bind event on the parent dom `<span />` element.
For IE, click disabled button region is also mean click the `<span />` but other browser don't do this.

You can add `disabled` prop on the `<Upload />` to prevent this issue.

**Comment by Innermadness** [comment]
Oh..  my carelessness.  Thank you...
