### ISSUE TITLE
Unable to prevent default click on a Switch when inside a Collapse Panel header

### ISSUE THREAD

**Issue by delesseps** [ant-design/ant-design#10979]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
OSX, Chome

### Reproduction link
[https://codepen.io/delesseps/pen/BVrmwv?&editors=001](https://codepen.io/delesseps/pen/BVrmwv?&editors=001)

### Steps to reproduce
e.g. 
```jsx
<Collapse>
  <Collapse.Panel header={(<Switch />)} />
</Collapse>
```

Click Switch

### What is expected?
Switch toggles but Collapse Panel does not

### What is actually happening?
Both Switch and Collapse Panel are toggling

Is related to this [closed issue](https://github.com/ant-design/ant-design/issues/7181) but more realistic scenario.

**Comment by yutingzhao1991** [comment]
> Is related to this closed issue but more realistic scenario.

That issue give a solution for this.

https://codepen.io/yutingzhao1991/pen/vrjWRp?&editors=001
