### ISSUE TITLE
how to prevent submit event when Enter key is pressed in Input which is in an Form

### ISSUE THREAD

**Issue by redlapin** [ant-design/ant-design#10982]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在Form组件中，当在输入框中按下Enter键的时候，表单将会提交。如何阻止这一功能？

### What does the proposed API look like?
在Form 组件上开放一个属性值，用来设置是否能够阻止Input的回车产生的提交

**Comment by yesmeck** [comment]
https://stackoverflow.com/questions/45711927/how-to-avoid-submitting-in-the-form-of-react-bootstrap-validation-when-press-the

**Comment by redlapin** [comment]
谢谢你的回复，但是这个解决方案是在每个Input上面增加一个监听函数阻止这一行为的发生。如果一个表单包含了十多个Input,这无疑是一个重复性的复制粘贴。this is not cool I mean. 所以我希望antd可以在Form表单上面提供一个API, 用来设置是否能够阻止enter产生的提交。

**Comment by redlapin** [comment]
我看到你们已经把这个issue关了。其实提这个issue更多的是优化方向的。目的是组件使用起来更便捷。也希望你们能看到我的留言。

**Comment by 453495181** [comment]
楼主这个问题我也遇到了  非常的不方便，在输入框中的回车总是会触发我不想执行的按钮事件。还有从.6X 到 1.1X 版本的用法改动很大，导致了升级很麻烦

**Comment by codedart2018** [comment]
这都2022年了　还是存在这个问题

**Comment by yoyo837** [comment]
当表单中只有一个可见的表单项时回车会默认提交, 这是浏览器行为.

但我不确定上面说的是不是这个事儿.

**Comment by codedart2018** [comment]
[8928](8928)

**Comment by xrkffgg** [comment]
form html 原生标签的行为吧

**Comment by codedart2018** [comment]
[issue](https://github.com/ant-design/ant-design-pro/issues/8928)
我刚提交错了连接。我觉得应该在这边发个issue
