### ISSUE TITLE
用RangePicker时，设置了mode=['month','month']，disabledData属性不起作用

### ISSUE THREAD

**Issue by zhoulisuper** [ant-design/ant-design#10981]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
选择区间月份，并严格控制哪些月份可以选择

### What does the proposed API look like?
disabledDate={disabledDate}可以起作用

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/55286824-76ed9f80-53d3-11e9-8b81-0b2769f8cda9.png)

可以用的

```jsx
 disabledDate = (date) => {
    if (!date) {
      return false;
    }
    const currVal = date.valueOf();
    return currVal <= moment('2019-03-20').valueOf() 
      || currVal >= moment('2019-03-31').valueOf();
  }
```

**Comment by afc163** [comment]
Duplicate of #9008

**Comment by swwinone** [comment]
https://codesandbox.io/embed/lp7zx1854m?fontsize=14
