### ISSUE TITLE
RangePicker在移动端点击会调出来软键盘，遮挡了日期无法选择

### ISSUE THREAD

**Issue by beysong** [ant-design/ant-design#10998]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
大部分手机或者pad端浏览器

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
正常操作 选择时间

### What is expected?
弹出日期选择框，能正常选择日期

### What is actually happening?
调出了软键盘，遮挡了控件

**Comment by zombieJ** [comment]
移动端可以使用 Ant Design Mobile: https://mobile.ant.design/components/calendar-cn/
