### ISSUE TITLE
DatePicker Localization not working as expected

### ISSUE THREAD

**Issue by cheena14** [ant-design/ant-design#10995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
Windows10 , chrome Version 67.0.3396.87 , react -^16.2.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/my32wwx368)

### Steps to reproduce
Update the language of application 
update moment locale also -> ( eg: moment.locale("de-DE"))
Open the RangePicker 

### What is expected?
RangePicker/DatePicker should be completely localized

### What is actually happening?
 "Select Time " and "ok" text is not localized 
The format of selected date range is not according to selected locale

---
We are using react-intl library for localization .
I tried to wrap application as well as RangePicker component in <LocaleProvider/> also.

**Comment by yesmeck** [comment]
Plz refer to the document https://ant.design/components/locale-provider/#header

**Comment by cheena14** [comment]
I have already referred to the document https://ant.design/components/locale-provider/ and tried what all is mentioned in the doc

**Comment by cheena14** [comment]
When i try to use <LocaleProvider> in my actual  application , It is not making any change .
We are using "react-intl" library for localization  , not sure this is impacting LocaleProvider
