### ISSUE TITLE
整体风格设计

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#10994]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
设计风格问题

### What does the proposed API look like?
和主题色一样，改变一个风格的api，整体风格都变了

如下示意图：
**dark**风格
![default](https://user-images.githubusercontent.com/18542211/41759511-79eeaa52-7621-11e8-8d26-b329845239c4.png)
**light**风格
![1](https://user-images.githubusercontent.com/18542211/41759512-7c7b3664-7621-11e8-9ac9-1c9146a132e5.png)

**Comment by yesmeck** [comment]
可以关注下 Ant Design Pro 2.0 里的实现。

**Comment by kaoding** [comment]
难道是皮球吗？
https://github.com/ant-design/ant-design-pro/issues/1715
 @yesmeck @afc163
