### ISSUE TITLE
Tag标签能不能定制closable=true时的图标Icon

### ISSUE THREAD

**Issue by koupeng** [ant-design/ant-design#11006]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如换成 号图标，完成类似添加的操作

### What does the proposed API look like?
Tag标签定制closable=true时的图标Icon

**Comment by afc163** [comment]
```jsx
<Tag>添加 <Icon type="plus" onClick={...} /></Tag>
```

**Comment by koupeng** [comment]
谢谢！！！
