### ISSUE TITLE
Input: allow for numbers to also be sent to prop type size

### ISSUE THREAD

**Issue by susielu** [ant-design/ant-design#11007]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In the HTML spec, an input can be given a number for it's `size` attribute, this allows you to dynamically size the input based on character length. I would like to use this attribute, but currently when I provide a number I see the error in the console: Invalid prop `size` of value `10` supplied to `Input`, expected one of ["small","default","large"].

I feel that this should be supported since your input `size` prop is overriding a core attribute of input elements.

### What does the proposed API look like?
On this line for type checking also allow for type of number for the size prop: https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L19

**Comment by chenshuai2144** [comment]
maxlength is a better choice in HTML5.
