### ISSUE TITLE
less 样式, 大部份组件应写为mixin. 

### ISSUE THREAD

**Issue by LinBoLen** [ant-design/ant-design#11001]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
组件样式重写不得不, 重新定义一遍样式来覆写. 但是基本样式元素结构基本一致.
因此需要提供, 组件mixin. 通过 传入影响样式来生效. 而不是把影响样式写死.

### What does the proposed API look like?
```css
@mixin .menu-selected {
  &-selected,
  &-hover {
    @content
  }
}
```

**Comment by afc163** [comment]
代码优化建议直接提交 PR 吧，贡献起来 😃
