### ISSUE TITLE
Component Autocomplete

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1100]
将 select combobox 封装为一个新组件，更直观和简洁的配置。

http://ant.design/components/select/#demo-combobox
http://ant.design/components/select/#demo-search-box

**Comment by afc163** [comment]
http://www.material-ui.com/#/components/auto-complete

**Comment by RaoHai** [comment]
讨论下这个实现？ https://github.com/RaoHai/ant-design/commit/c0df58a323a99d636ba4ba7fd3248229cb5c4ddd

**Comment by afc163** [comment]
赞效率~

**Comment by benjycui** [comment]
ping~

**Comment by RaoHai** [comment]
@benjycui 你是在催更么……

**Comment by benjycui** [comment]
迫不及待的想看下续集。。。
