### ISSUE TITLE
setFieldsValue can't set the value of RangePicker

### ISSUE THREAD

**Issue by bayun2** [ant-design/ant-design#11005]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jjv0ko4wq9)

### Steps to reproduce
监听RangePicker的onChange事件，在change的time区间不满足一定条件时，比如相隔不小于6个月，则希望能用setFieldsValue重置当前已经选好的时间

### What is expected?
能用setFieldsValue重置当前已经选好的时间

### What is actually happening?
使用setFieldsValue以后，仍然是用户输入的时间

**Comment by afc163** [comment]
Your codesandbox link is not working.

**Comment by yesmeck** [comment]
See https://github.com/ant-design/ant-design/issues/4862

你传给 `RangePicker` 的 `onChange` 调用在 `rc-form` 内部的 `onChange` 之前，所以你的 `onChange` 会被内部的 `onChange` 覆盖。如果你要现在用户的输入可以用 `getValueFromEvent`。

**Comment by bayun2** [comment]
十分感谢回答的我的问题，但是在查看getValueFromEvent的api说明时，发现normalize这个场景，更符合我对场景描述的预期，仍然十分感谢
