### ISSUE TITLE
Specify the time zone in DatePicker

### ISSUE THREAD

**Issue by pierre-b** [ant-design/ant-design#11012]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Actually, DatePicker returns a Moment() object with the browser time zone.
Global SaaS reporting softwares have users who may work on different time zones, and the DatePicker should return a date in a specific time zone.

### What does the proposed API look like?
A "timezone" property to the DatePicker (i.e: Asia/Singapore , Europe/Paris etc...) will be great. Thanks.

**Comment by afc163** [comment]
https://momentjs.com/docs/#/manipulating/utc-offset/
https://momentjs.com/timezone/

**Comment by afc163** [comment]
https://github.com/moment/moment/issues/3433

**Comment by pierre-b** [comment]
I would just like to avoid doind this at every DatePicker onChange:
`const tzDate = Moment.tz(value.format('YYYY-MM-DD HH:mm:ss), "Asia/Singapore")`
You are the judge, thanks for your fast answer anyway!

**Comment by adred** [comment]
Hopefully you guys can fix this. I too need this feature!

**Comment by pybuche** [comment]
Same here !

**Comment by rahuls360** [comment]
Although we can modify timezone's offset onChange, since we are showing the current date (7 September in the screenshot), it becomes important to be able to set a prop on DatePicker
![image](https://user-images.githubusercontent.com/10925984/92377038-24182b80-f121-11ea-8ed3-358ef1a7dbe8.png)

**Comment by nguyenbathanh** [comment]
Pass value to DatePicker a date string (not a `Date` or `moment` object) and it should work.

```
const date = moment(yourDate).utc().format('LL');
```

**Comment by empz** [comment]
> Pass value to DatePicker a date string (not a `Date` or `moment` object) and it should work. For example with UTC:
> 
> ```
> const date = moment(yourDate).utc().format('LL');
> ```

The components only accepts `moment` objects in `value` prop. Passing a string results in a TypeError.

**Comment by succerror** [comment]
+1 on this.
A timezone prop like `tz="Europe/Paris"`.
Probably it should take effect if [moment-timezone](https://github.com/moment/moment-timezone) add-on is installed.

**Comment by succerror** [comment]
There are suggestions to do the conversion on the way in(`value`) and on the way out(`onChange`),but that won't control the way the the date and time is shown in the picker(it will still show in the local timezone).
It's a messy hack that would create confusion for the user.

What we want is that the the DatePicker should show the date and time as if the user is located on that specified timezone.

**Comment by mikeyshing88** [comment]
If you're using `moment` then you can simply use `moment.tz.setDefault(timeZone)` - which should set the `DatePicker` to the respected timezone.

That being said, I'm looking to replace `moment` with `date-fns` (https://ant.design/docs/react/replace-moment) but there is no obvious way to convert the timezone when using `date-fns` instead.

Perhaps it would be better if we had the ability to change the `today/now` date and time.

**Comment by mcshaman** [comment]
Setting the default timezone dosn't provide a solution for where you want to set a timezone for a specific picker

**Comment by jer-sen** [comment]
Same need than @mcshaman, we should be able to choose a timezone for the DatePicker (different than the default one).

**Comment by jer-sen** [comment]
This code is a workaround (could be added to documentation or implemented in antd):

```
import * as React from 'react';
import moment from 'moment-timezone';
import generatePicker, { PickerProps } from 'antd/es/date-picker/generatePicker';
// eslint-disable-next-line node/no-extraneous-import
import { noteOnce } from 'rc-util/lib/warning';
// eslint-disable-next-line node/no-extraneous-import
import { GenerateConfig } from 'rc-picker/lib/generate/index';


const generateConfig = (timezone: string): GenerateConfig<moment.Moment> => ({
	// Get
	getNow: () => moment.tz(timezone),
	getFixedDate: (string) => moment.tz(string, 'YYYY-MM-DD', timezone),
	getEndDate: (date) => {
		const clone = date.clone();
		return clone.endOf('month');
	},
	getWeekDay: (date) => {
		const clone = date.clone().locale('en_US');
		return clone.weekday() + clone.localeData().firstDayOfWeek();
	},
	getYear: (date) => date.year(),
	getMonth: (date) => date.month(),
	getDate: (date) => date.date(),
	getHour: (date) => date.hour(),
	getMinute: (date) => date.minute(),
	getSecond: (date) => date.second(),

	// Set
	addYear: (date, diff) => {
		const clone = date.clone();
		return clone.add(diff, 'year');
	},
	addMonth: (date, diff) => {
		const clone = date.clone();
		return clone.add(diff, 'month');
	},
	addDate: (date, diff) => {
		const clone = date.clone();
		return clone.add(diff, 'day');
	},
	setYear: (date, year) => {
		const clone = date.clone();
		return clone.year(year);
	},
	setMonth: (date, month) => {
		const clone = date.clone();
		return clone.month(month);
	},
	setDate: (date, num) => {
		const clone = date.clone();
		return clone.date(num);
	},
	setHour: (date, hour) => {
		const clone = date.clone();
		return clone.hour(hour);
	},
	setMinute: (date, minute) => {
		const clone = date.clone();
		return clone.minute(minute);
	},
	setSecond: (date, second) => {
		const clone = date.clone();
		return clone.second(second);
	},

	// Compare
	isAfter: (date1, date2) => date1.isAfter(date2),
	isValidate: (date) => date.isValid(),

	locale: {
		getWeekFirstDay: (locale) => {
			const date = moment.tz(timezone).locale(locale);
			return date.localeData().firstDayOfWeek();
		},
		getWeekFirstDate: (locale, date) => {
			const clone = date.clone();
			const result = clone.locale(locale);
			return result.weekday(0);
		},
		getWeek: (locale, date) => {
			const clone = date.clone();
			const result = clone.locale(locale);
			return result.week();
		},
		getShortWeekDays: (locale) => {
			const date = moment.tz(timezone).locale(locale);
			return date.localeData().weekdaysMin();
		},
		getShortMonths: (locale) => {
			const date = moment.tz(timezone).locale(locale);
			return date.localeData().monthsShort();
		},
		format: (locale, date, format) => {
			const clone = date.clone();
			const result = clone.locale(locale);
			return result.format(format);
		},
		parse: (locale, text, formats) => {
			const fallbackFormatList: string[] = [];

			for (let format of formats) {
				let formatText = text;

				if (format.includes('wo') || format.includes('Wo')) {
					format = format.replace(/wo/ug, 'w').replace(/Wo/ug, 'W');
					const matchFormat = format.match(/[-YyMmDdHhSsWwGg]+/ug);
					const matchText = formatText.match(/[-\d]+/ug);

					if (matchFormat && matchText) {
						format = matchFormat.join('');
						formatText = matchText.join('');
					}
					else {
						fallbackFormatList.push(format.replace(/o/ug, ''));
					}
				}

				const date = moment.tz(formatText, format, locale, true, timezone);
				if (date.isValid()) {
					return date;
				}
			}

			// Fallback to fuzzy matching, this should always not reach match or need fire a issue
			for (const fallbackFormat of fallbackFormatList) {
				const date = moment.tz(text, fallbackFormat, locale, false, timezone);

				/* istanbul ignore next */
				if (date.isValid()) {
					noteOnce(
						false,
						'Not match any format strictly and fallback to fuzzy match. Please help to fire a issue about this.'
					);
					return date;
				}
			}

			return null;
		},
	},
});

export type LocalDatePickerProps =
	PickerProps<moment.Moment>
	& {
		timezone: string,
	}
	& (
		{
			startOfDay?: false,
			startOfNextDay?: false,
		}
		| {
			startOfDay: true,
			startOfNextDay?: boolean,
			showTime: false,
		}
	)
;

const LocalDatePicker: React.FC<LocalDatePickerProps> = ({ timezone, startOfDay, startOfNextDay, value, onChange, ...otherProps }) => {
	const handleOnChange = React.useMemo<typeof onChange>(() => {
		if (startOfDay !== true) return onChange;

		if (onChange === undefined) return undefined;
		return (newValue) => {
			if (newValue === null) onChange(null, "");
			else {
				const res = newValue.clone().tz(timezone);
				if (startOfNextDay === true) res.add(1, 'day');
				onChange(res.startOf('day'), "");
			}
		};
	}, [onChange, startOfDay, startOfNextDay, timezone]);

	let valueToUse = value?.clone().tz(timezone);
	if (startOfDay === true && moment.isMoment(valueToUse)) {
		const startOfTheDay = valueToUse.clone().startOf('day');
		if (!startOfTheDay.isSame(valueToUse)) {
			valueToUse = startOfTheDay;
			// eslint-disable-next-line no-console
			console.warn("Date is not a start of day so it will be changed to the start of the day");
			if (handleOnChange !== undefined) handleOnChange(valueToUse, '');
		}
		
		if (startOfNextDay === true) valueToUse = valueToUse.clone().add(-1, 'day');
	}

	const InnerLocalStartOfDayPicker = React.useMemo(() =>
		generatePicker<moment.Moment>(generateConfig(timezone))
	, [timezone]);

	return <InnerLocalStartOfDayPicker value={valueToUse} onChange={handleOnChange} {...otherProps} />;
};

export default LocalDatePicker;
```

**Comment by Mathijs003** [comment]
any solution to this problem? we need to set a specific timezone per datepicker so we can't use a default

**Comment by wi-ski** [comment]
Very frustating please fix thanks

**Comment by liao02x** [comment]
+1 on this

**Comment by CruelSilence** [comment]
+1.
We can't change default timezone(

**Comment by mienaikoe** [comment]
@mcshaman made the key point. If you need to specify a timezone (for a conference or travel event, for example), we can't set a single timezone for all of moment.

**Comment by zhengk1994** [comment]
+1 on this.
It's not graceful to specify a timezone every time for each values from DatePicker (and the same with RangePicker).

**Comment by adkr** [comment]
+1
Why it's closed?

**Comment by matinfo** [comment]
Please provide for DatePicker (RangePicker, TimePicker) possibility to give prop timezone. The internal use of the date need to use UTC (GMT), because like in Europe with whiter, the timezone shift during the year for example and need specially for RangeDatePicker!

**Comment by matinfo** [comment]
After spending lot time to understand why `dayjs.tz.setDefault `not worked like for `moment.tz.setDefault`, I understand that when with _dayjs_ you set default time zone this affect `dayjs.tz()` but not `dayjs()`. Result if your app not used same time zone of your browser not work with _dayjs_, but only with _momentjs_.

But if you need to display two or more DatePicker/DateTimePicker on the same page with different time zone will be better to be able to provide prop timezone! 

Result for my need I switched all my project back to _momentjs_ :sleepy:

**Comment by Austint30** [comment]
I need this. I need to use the Date/Time picker to choose a date and time for a specific timezone of which changes depending on the timezone of the data being looked at. Using the browser's timezone or a global default timezone isn't going to cut it.

**Comment by s-comp** [comment]
I wrote a function in which I manually collect the date in UTC

const getUTCtime = (typeDay, date) => {
    let utcDate = new Date(date)

    let yyyy = utcDate.getFullYear()
    let mm = ("0" + (utcDate.getMonth() + 1)).slice(-2)
    let dd = ("0" + utcDate.getDate()).slice(-2)
    let fullUTCDate

    if (typeDay === 'startDay') {
      fullUTCDate = yyyy + '-' + mm + '-' + dd + 'T00:00:00Z'
    }
    if (typeDay === 'endDay') {
      fullUTCDate = yyyy + '-' + mm + '-' + dd + 'T23:59:59Z'
    }
    return moment(fullUTCDate).valueOf()
  }

**Comment by mschultz4** [comment]
In our case, we just want to display the DatePicker date in UTC. Using dayjs and a custom format worked.

`format={ date => date.utc().format()}`

**Comment by HarnonA** [comment]
i had a similar problem, it's solved playing with timezone.
- Current date: 24/06/2022
- Displayed date: 25/06/2022

Fixed for me:
`defaultValue={addMinutes(new Date(), new Date().getTimezoneOffset())}`

**Comment by 0529bill** [comment]
`format={date => date.utc().format("MMM DD, YYYY HH:mm:ss")}` this worked for me!

**Comment by peter2gossell** [comment]
Part of the problem is momentjs itself.  If you have a timezone in your timestamp that moment accepts, you can use `moment.parseZone(timestamp)` and then the pickers will use the correct timezone.  Really I think this should be the default behavior in moment, honestly.

**Comment by hakan-controlplane** [comment]
Can we reopen this please? There is no resolution currently.

If we manually set the timezone when feeding to value prop or getting from the onChange prop, it brakes the keyboard input, if we try to solve by using a format function, then the UI selector shows still in local, but the value become utc.

**Comment by aminsaedi** [comment]
+1

**Comment by wraeth-eth** [comment]
++1

**Comment by aminsaedi** [comment]
I crated two custom components. Maybe it can help

https://gist.github.com/aminsaedi/6e034a41b75b8f7d7e21e618d91319b8

**Comment by francois-spectre** [comment]
+1

**Comment by devdevdenis** [comment]
+1

**Comment by GutoVeronezi** [comment]
+1

**Comment by DiogenesRychlewski** [comment]
+1

**Comment by gregor-mueller** [comment]
We also need this. Just to be clear, we are using dayjs, not moment.

**Comment by JackLiR8** [comment]
For anyone who use antd v4.x just like I do, you should add both `moment` and `moment-timezone` as your project dependency. And you need to import the `moment` function from `moment-timezone`. When you witch to another timeZone, just call moment.tz.setDefault(timeZone).

Note that you can't get time by `new Date()`, cause it still use the timeZone of your computer system.

```js
// import 
import moment from 'moment-timezone'

// init or change timeZone
moment.tz.setDefault(timeZone)

// ❌
const now = new Date()
const now = moment(new Date())

// ✅
const now = moment()
```

**Comment by Kogl1n** [comment]
> `format={date => date.utc().format("MMM DD, YYYY HH:mm:ss")}` this worked for me!

Thank you. If you write "MMM DD, YYYY HH:mm" the "seconds"- selection column doesn't disappear, though.

**Comment by limion** [comment]
You can create a utc aware `dayjs` instance from the current one and use it like this:

```
import utc from "dayjs/plugin/utc";
import dayjs from "dayjs";
dayjs.extend(utc);

...
<DatePicker
      onChange={(date) => {
             const utcAwareDateJs = dayjs(date).utc(true);
             // timestamp
             setDate(Math.round(utcAwareDateJs.valueOf() / 1000));
       }}
/>
...
```

**Comment by eugenlinde** [comment]
I found a simple solution in my project, where client timezone should always stay the same. Perhaps this helps someone...
Basically since the date should be always stored in utc format and client timezone is fixed, we could use simple offset.

` <Form.Item
        label={translate("start")}
        name={["start"]}
        getValueProps={(value) => ({
          value: value ? dayjs.utc(value).utcOffset(120) : undefined,
        })}
   >
        <DatePicker />
   </Form.Item>`
