### ISSUE TITLE
Input.Search supports onPressEnter and onClick(onSearch) optional

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#11015]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
Input.Search supports onPressEnter and onClick(onSearch) optional.

### What problem does this feature solve?
Different events trigger different tasks

### What does the proposed API look like?
onPressEnter?: React.KeyboardEventHandler<HTMLInputElement>
onSearch?: React.KeyboardEventHandler<HTMLInputElement>

**Comment by pkl93** [comment]
I have same request for onPressEnter.

**Comment by afc163** [comment]
I don't realy understand your need.

**Comment by yoyo837** [comment]
艾玛，谷歌翻译坑我...

我是想区要分回车事件和右边search按钮事件...

**Comment by afc163** [comment]
给 onSearch 增加了 event 参数：`onSearch(value, event)`
