### ISSUE TITLE
antd中有elementUI中的show-overflow-tooltip 类似的吗?

### ISSUE THREAD

**Issue by renjimin** [ant-design/ant-design#11010]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当表格某个td中文字描述过多,现在会将表格撑开,或者换行.整个页面看起来很不美观

### What does the proposed API look like?
有elementUI中的show-overflow-tooltip 这种的没

**Comment by afc163** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

**Comment by fengyun2** [comment]
> https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

`elementUI中的show-overflow-tooltip`，不仅仅超出内容出现省略号，还根据内容的宽度出现tooltip效果；具体效果如下图：

![image](https://user-images.githubusercontent.com/8147202/67135424-01043500-f24c-11e9-926f-b25b40a903ed.png)
