### ISSUE TITLE
The react/jsx-space-before-closing rule is deprecated. Please use the react/jsx-tag-spacing rule with the "beforeSelfClosing" option instead.

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#11020]
![1](https://user-images.githubusercontent.com/26128706/41828011-447166f8-7865-11e8-9f61-5f64a41c2900.png)
![2](https://user-images.githubusercontent.com/26128706/41828014-4b0d9b30-7865-11e8-96ed-6e9711c2d391.png)
![3](https://user-images.githubusercontent.com/26128706/41828016-4e7f66f4-7865-11e8-8779-6c543ca9c203.png)

- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
"react": "^16.4.1"

### Reproduction link
[https://github.com/hqzh/sutpc](https://github.com/hqzh/sutpc)

### Steps to reproduce
表单校验使用了老版本废弃的API,导致页面报警告,是否考虑修正下

### What is expected?
表单校验使用了老版本废弃的API,导致页面报警告,是否考虑修正下

### What is actually happening?
表单校验使用了老版本废弃的API,导致页面报警告,是否考虑修正下

**Comment by yesmeck** [comment]
这个不是 antd 的警告。是 eslint 的。
