### ISSUE TITLE
希望 expandedRowRender 和 rowSelection 可以同时显示

### ISSUE THREAD

**Issue by bindai** [ant-design/ant-design#1102]
在table.jsx 里面 只要把  expandIconColumnIndex设置为0， 就可以保证 expandedRowRender 和 rowSelection 同时显示， 并且没有对其他造成影响，如果有问题，纠正我哈！

let table = (
      <div>
        <Table {...this.props}
          data={data}
          columns={columns}
          className={classString}
         ** expandIconColumnIndex={0}**
          expandIconAsCell={expandIconAsCell} />
          {emptyText}
      </div>
    );

**Comment by afc163** [comment]
感谢反馈~
