### ISSUE TITLE
保存css文件时报错： Cannot find module 'moment' 

### ISSUE THREAD

**Issue by some-code** [ant-design/ant-design#11021]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
win10 chrome64

### Reproduction link
[https://github.com/some-code/antd-error-showcase](https://github.com/some-code/antd-error-showcase)

### Steps to reproduce
1，安装项目
2，保存css文件
3，出错

### What is expected?
正常。

### What is actually happening?
.../react-admin/node_modules/antd/lib/calendar/Header.d.ts
(2,25): Cannot find module 'moment'.

---
1，保存任何css文件或者less文件都会报错，转而保存js文件后报错消失，功能正常
2，已经手动安装 ` "moment": "^2.22.2"`, 并且手写了d.ts文件：
````
import * as moment from 'moment';
export as namespace moment;
export = moment;
````
3，开关 `babel-plugin-import` 问题均存在

**Comment by zombieJ** [comment]
```bash
rm types/moment.d.ts
yarn
yarn start
```

PS: This is not an antd issue : )

**Comment by some-code** [comment]
````
rm types/moment.d.ts
rm -rf node_modules/
yarn
yarn start
````
 It is still do the same; 
How to fix this problem?

**Comment by aminmahrami** [comment]
I have the same issue.

**Comment by hayk94** [comment]
Anyone was able to make this work?

**Comment by huangbinjie** [comment]
3.9.2 has the same issue.

**Comment by whirish** [comment]
Also encountering this, no `types/moment.d.ts`. `moment` is installed and in my `node_modules` folder.

**Comment by aminmahrami** [comment]
I do my styling inline so i removed the `watch-css` and it's fine. 
Note: this is not a proper solution. just a workaround.
