### ISSUE TITLE
Number Input cursor position issue 

### ISSUE THREAD

**Issue by chenhaizhou** [ant-design/ant-design#11022]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
all browsers

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4mv9jxn18)

### Steps to reproduce
input '12345' in have price Number Input；

### What is expected?
12,345

### What is actually happening?
12,354

---
I noticed same with this issue https://github.com/ant-design/ant-design/issues/9826, but for now, the issue still have on lasted version.

**Comment by afc163** [comment]
Try reinstall node_modules.

**Comment by chenhaizhou** [comment]
for  now, latest version is 3.6.4, I visit ant.design website, test NumberInput, still have this issue, So, Can reinstall actually repair?

**Comment by afc163** [comment]
The website is not updated yet, you can try in your local enviorment.

**Comment by chenhaizhou** [comment]
but for now, antd latest version is 3.6.4, I can not install new version. can you tell me how to reinstall on my locale?

**Comment by afc163** [comment]
It is npm's semver version magic: https://github.com/ant-design/ant-design/blob/f80961b94625aa138835f5ce128eb9888cca68f8/package.json#L64

**Comment by chenhaizhou** [comment]
yes, so I need change to '4.0.9' and then reinstall?

**Comment by afc163** [comment]
Nope, just reinstall.

**Comment by chenhaizhou** [comment]
Sorry man, I remove node_modules folder in my project, and reinstall, but still has this issue.

**Comment by afc163** [comment]
Remove your yarn.lock or package-lock.json and retry again.

**Comment by chenhaizhou** [comment]
I tried, remove package-lock.json with node-modules folder, but not work, still display 12,354. are you make sure fixed it?

**Comment by afc163** [comment]
@chenhaizhou Try `cat node_modules/rc-input-number/package.json` and check the version.

**Comment by chenhaizhou** [comment]
still 4.0.8

**Comment by afc163** [comment]
Just make sure it is 4.0.10.

**Comment by chenhaizhou** [comment]
I already update version to 4.0.10, but `InputNumber` still display `12,354` .

**Comment by afc163** [comment]
Could you provide a reproducible demo by github repo?

**Comment by chenhaizhou** [comment]
if use `defaultValue` props setting value, it work well.  but if use `value` props setting value, still have this issue.
