### ISSUE TITLE
Select: When mode="combobox" and content is much enough, there is a bug of style

### ISSUE THREAD

**Issue by quanshubli** [ant-design/ant-design#11035]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
Chrome 版本 67.0.3396.87（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7341wj5zvj)

### Steps to reproduce
Just input much enough content.

### What is expected?
The content is inside the box.

### What is actually happening?
There is another content outside and overlaying the box.

---
I think the root of this bug is the element span whose classname is "ant-select-search__field__mirror". When the content is much enough, the style "left=-9999px" is not enough. So maybe let it hide of opacity=0 directly.

**Comment by quanshubli** [comment]
Sorry, there is a little problem in my additional remark.
Following is the correction one:
I think the root of this bug is the element span whose classname is "ant-select-search__field__mirror". When the content is much enough, the style "left=-9999px" is not enough. So maybe let it hide of opacity=0 directly.

**Comment by zombieJ** [comment]
wow! thanks for feedback. Let me check
