### ISSUE TITLE
error style in Table small size

### ISSUE THREAD

**Issue by PeterRao** [ant-design/ant-design#11033]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
Mac OSX 10.13.5 Chrome 67

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y2kn3pjqv1)

### Steps to reproduce
Not show thead last tr border right in Table small size, [example](https://codesandbox.io/s/y2kn3pjqv1)

### What is expected?
show thead last tr border right in Table small size

### What is actually happening?
show thead last tr border right in Table small size
![image](https://user-images.githubusercontent.com/1611647/41838355-c9b7e026-7892-11e8-8979-180f27663c1a.png)

---
https://github.com/ant-design/ant-design/pull/9325/commits/7d3ff69e12cb7cfda2b42c304bdb99054c06a89f cause the problem.

**Comment by yesmeck** [comment]
😢 Too many edge cases.

**Comment by PeterRao** [comment]
Not reproduction in middle size. could you fix the bug? @yesmeck

**Comment by afc163** [comment]
This problem seems gone in latest antd version with chrome 70.
