### ISSUE TITLE
About ClassName

### ISSUE THREAD

**Issue by xqk1** [ant-design/ant-design#11032]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
chrome , 67.0.3396.87

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4zvyq08wz7)

### Steps to reproduce
only add the same className in the antd modules
```

<DatePicker className="ant-calendar-picker" />

``` 
and get the DOM node like 
```

<span class="ant-calendar-picker ant-calendar-picker"></span>

```

### What is expected?
don't add the same className

### What is actually happening?
antd add the same className in the DOM node

**Comment by afc163** [comment]
I don't think this is a bug, it won't be hurt or benefited from this className.

**Comment by xqk1** [comment]
@afc163 If i really do something by using this className , it must be hurt . For example , i define a key frame animation for this className . Really no hurt ? In fact , nobody use by this method . But it's a bug .

**Comment by afc163** [comment]
> define a key frame animation for this className

What is your expected render result? I think the below render dom would be still not working when you define custom styles.

```jsx
<span class="ant-calendar-picker"></span>
```

**Comment by xqk1** [comment]
@afc163 https://codesandbox.io/s/4zvyq08wz7 
If i need control this key frame animation by control this className , but i can't  if it has two same className .

**Comment by afc163** [comment]
```jsx
<DatePicker className="ant-calendar-picker" />

=>

<span class="ant-calendar-picker"></span>
```

```jsx
<DatePicker className="" />

=>

<span class=""></span>
```

Is this your expected result?
