### ISSUE TITLE
`<Input type="textarea" /> `组件不能设置className

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design#1103]
Hi, `<Input type="textarea" /> `这个组件好像不能设置className？示例：  http://codepen.io/zhaozhiming/pen/dMbNqY
  
请帮忙确认一下，谢谢

**Comment by afc163** [comment]
确实不能。而且 Input 组件默认不应该是 `display: block;`。

**Comment by zhaozhiming** [comment]
:+1:
