### ISSUE TITLE
Cascader动态加载，表单赋值的问题

### ISSUE THREAD

**Issue by ybning** [ant-design/ant-design#11037]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有这样一个场景：
Cascader的数据是动态加载的，现在做表单赋值，但实际动态加载出来的数据没有loadData出来，赋值不上。
请问有什么好的解决方案吗？

https://codesandbox.io/s/x38pooxmo4

### What does the proposed API look like?
动态加载的数据能赋值

**Comment by zombieJ** [comment]
选择的数据如果未加载，可以在选择的时候触发一个加载，等加载完毕再赋值。

**Comment by ybning** [comment]
@zombieJ 
但实际场景是：表单赋值是不需要进行选择操作的。表单赋值在componentDidMount后拿到数据就执行完成了。
