### ISSUE TITLE
input-number: focused style could not be removed after clicking up/down button and then outside

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#11034]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

See
#8592, #9953, #10663 and react-component/input-number#106
### Version
3.6.4

### Environment
Windows 10 FCU latest 64bit, Chrome 67.0.3396.99 64bit

### Reproduction link
[http://cloud.vipwindows.com/basic/scanpay?sales-id=101224](http://cloud.vipwindows.com/basic/scanpay?sales-id=101224)

### Steps to reproduce
1.clicking up/down button 
2.then outside
3.focused style could not be removed

### What is expected?
focused style can be removed

### What is actually happening?
focused style could not be removed

---
Only in production, dev is work fine.

> **for reproducible demo**
U: 15088885555
p: 123456

**Comment by hardensky** [comment]
同样遇到了 打包后有问题，dev是ok的

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/input-number/commit/ca03ff7e0c944216fc1a1c72c281bb0dc20af292, try reinstall node_modules.
