### ISSUE TITLE
The Popover component doesn't work when I use the trigger way "focus" in Firefox and safari

### ISSUE THREAD

**Issue by HIceFire** [ant-design/ant-design#11039]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
MacOS  10.12.3  Firefox Quantum 60.0.1

### Reproduction link
[https://codepen.io/hicefire/pen/bKxegR?editors=001](https://codepen.io/hicefire/pen/bKxegR?editors=001)

### Steps to reproduce
1. open the link to minimal redo or "https://ant.design/components/popover/#components-popover-demo-triggerType" in Firefox browser
2. click the trigger element

### What is expected?
The popover content will be showed

### What is actually happening?
Nothing happened

---
you can reproduce the bug by open the documentation of Popover Component 
(https://ant.design/components/popover/#components-popover-demo-triggerType)

**Comment by afc163** [comment]
It is a browser compatibility problem, firefox won't focus button after click it, so there is nothing we should do about it, thx for reporting it still.
