### ISSUE TITLE
upload beforeupload return false 之后继续上传会很卡除非删掉错误的选项才恢复正常

### ISSUE THREAD

**Issue by huyawei** [ant-design/ant-design#11043]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
最新版  windows环境

### Reproduction link
[https://codepen.io/LynnHg/pen/YYZdRV](https://codepen.io/LynnHg/pen/YYZdRV)

### Steps to reproduce
上传错误格式的文件  beforeupload return false 之后 upload组件会很卡

### What is expected?
不卡

### What is actually happening?
卡

**Comment by dengfuping** [comment]
@huyawei I cannot reproduce the problem as you said. Could you give a gif to show that?

**Comment by huyawei** [comment]
![222](https://user-images.githubusercontent.com/23353032/41903389-5609e526-7968-11e8-8544-7c3f5aeba630.gif)
@dengfuping 
上传错误的文件，beforeupload return false, 点击+ 选择下一张图片，这个时候 文件弹框会卡住一直等到第二张图片 显示file图标之后，才会弹出
之后继续上传图片就比较卡，删掉第二张图片，之后上传就没问题
