### ISSUE TITLE
DatePicker onChange 需要得到 format 后的值

### ISSUE THREAD

**Issue by zinkey** [ant-design/ant-design#1104]
现在的 DatePick onChange 只能得到 Date 类型的值，要是想得到 format 后的值还需要自己再用第三款库进行 format，这样就没有办法保证跟组件 format 一样的值。

是否可以：

1. onChange 添加 format 后的 String

2. 提供 Date 到 String 的 format 方法

**Comment by afc163** [comment]
返回原生 Date 对象的初衷是想要去掉 https://github.com/yiminghe/gregorian-calendar/ 的影响，让大家可以选用 moment 这样的库二次处理，也方便后续可能的底层重构。

现在看来确实有些麻烦，1.0 之后改为和 http://ant.design/components/calendar/#api 一样的方式，统一返回 [GregorianCalendar)](https://github.com/yiminghe/GregorianCalendar) 对象好了。

> 返回 string 会很不方便，因为无法直接比较和操作。

**Comment by zinkey** [comment]
好像不用修改也可以，现在是这样做的：

```javascript
{
	onChange: function(date){
		var GregorianCalendarFormat = require('gregorian-calendar-format');
		var GregorianCalendar = require('gregorian-calendar');
		var gregorianCalendar = new GregorianCalendar(this.props.locale || require('gregorian-calendar/lib/locale/zh_CN'));
		var df = new GregorianCalendarFormat(this.props.format || 'yyyy-MM-dd');
		gregorianCalendar.setTime(date);
		var dateString = df.format(gregorianCalendar);
		console.log(dateString)
	}
}
```

**Comment by afc163** [comment]
目前也可以直接用 Date 原生方法来得到 String 。

`date.toLocaleDateString()`

**Comment by liuchaofeng1230** [comment]
我用的timepicker，也有这样的需求，希望得到输入框中的字符串

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/0.11.3/components/time-picker/demo/basic.md

**Comment by zinkey** [comment]
date.toLocaleDateString() 肯定不行啊，这个跟输入框的字符串不一致。

**Comment by liekkas** [comment]
+1

**Comment by afc163** [comment]
先补充第二个参数如何？

```js
onChange(date, text) {
}
```

**Comment by zinkey** [comment]
嗯

**Comment by hotoo** [comment]
原生的 input[type=date] 的日期类型输入框是不允许修改 format 的。

- 可视化的部分，默认使用本地格式（浏览器或系统设置）
- 提交的值都是 ISO 8601 标准格式。
