### ISSUE TITLE
当嵌套表格 rowSelection 中 type 属性设置为 radio 时，怎么设置单选那一列的列名称

### ISSUE THREAD

**Issue by littleLane** [ant-design/ant-design#11041]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.1.4

### Environment
mac、 chrome、 antd v3.1.4

### Reproduction link
[https://codepen.io/littlelane/pen/qKMNGb?editors=0010](https://codepen.io/littlelane/pen/qKMNGb?editors=0010)

### Steps to reproduce
```JavaScript
expandedRowRender: () => {
      return (
        <Table 
          columns={[].concat(columns)} 
          dataSource={[].concat(data)}
          rowSelection={{
            type: 'radio',
          }}
        />
      )
    },
```

### What is expected?
有相关配置设置该列名称

### What is actually happening?
目前好像没有相关配置参数

**Comment by chinaxiaoyy** [comment]
大神们, 并不是每行都渲染checkbox怎么实现啊?
![wechatimg5](https://user-images.githubusercontent.com/20460743/41910549-985d6682-797c-11e8-9da6-643bd5e31c3a.jpeg)

**Comment by littleLane** [comment]
@chinaxiaoyy 你要实现什么需求，我这里有另外一种实现就是对相应行的 checkbox 做 disabled 处理

**Comment by chinaxiaoyy** [comment]
@littleLane 需求就是显示checkbox, 但是不是每个row都显示

**Comment by littleLane** [comment]
@chinaxiaoyy 就目前看 antd 没有办法实现你这个功能

**Comment by chinaxiaoyy** [comment]
@littleLane 好吧  那我手写吧, 多谢

**Comment by peterzhai** [comment]
请问一下，嵌套table不能使用rowSelection 显示出checkBox?

**Comment by littleLane** [comment]
@peterzhai 有在线的例子吗
