### ISSUE TITLE
Table组件的rowSelection.onSelectAll的第二个selectedRows参数，应该始终返回数据

### ISSUE THREAD

**Issue by luolonghao** [ant-design/ant-design#1105]
现状：selected为false时，selectedRows为空数组。

期望：selected为false时，selectedRows为取消选中的数据列表。

**Comment by afc163** [comment]
这个参数是 `selectedRows`，并非 `deselectedRows`，取消全选时为 `[]` 是合理的。

我可以补充 onSelectAll 的第三个参数为 `deselectedRows`。

> PS：建议直接使用 `onChange` 而不是 `onSelect` 和 `onSelectAll`。

**Comment by yiminghe** [comment]
onSelect/onSelectAll deprecated 了吧

**Comment by luolonghao** [comment]
那onChange希望添加selectedRows参数

````js
onChange(selectedRowKeys, selectedRows)
````

**Comment by afc163** [comment]
- 补充了 onSelectAll 的第三个参数 `deselectedRows`。
- 补充 onChange 的第二个参数 `selectedRows`。

onChange 在 ajax 模式下确实有局限性。

**Comment by afc163** [comment]
`onSelectAll` 的第三个参数改为 `changeRows`，`deselectedRows` 不够用。

**Comment by jialeicui** [comment]
@afc163 
请问`onChange`里添加的第二个参数`selectedRows`用于什么情景?
有点儿疑惑的就是: `selectedRowKeys`是整个表的, `selectedRows `是当前页的.
>const data = this.getCurrentPageData();
      const selectedRows = data.filter(row => selectedRowKeys.indexOf(row.key) >= 0);
      this.props.rowSelection.onChange(selectedRowKeys, selectedRows);

我想获得所有选中的row时不能用第二个参数, 是否只能用`selectedRowKeys `从我的dataSource中遍历获取?
 谢谢!

**Comment by afc163** [comment]
> 我想获得所有选中的row时不能用第二个参数, 是否只能用selectedRowKeys从我的dataSource中遍历获取?

推荐这么做，selectedRows 是为了兼容旧版本就没去掉。
