### ISSUE TITLE
Layout breaks when right Layout.Sider used with Layout.Footer

### ISSUE THREAD

**Issue by eryi** [ant-design/ant-design#11054]
- [ X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
Chrome 67.0.3396.87, React latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2x335kkzqy)

### Steps to reproduce
Click on the codesandbox link.

### What is expected?
Footer should be at the bottom of the page

### What is actually happening?
Footer is at the right side of right Sider.

**Comment by spideeee** [comment]
Every Layout component (Sider, Content, Header...) has to be inside Layout.

Example:
```
<Layout>
   <Sider></Sider>
</Layout>
<Layout>
   <Footer>Footer</Footer>
</Layout>
```

Checkout this updated example you shared : https://codesandbox.io/s/jl08vznq25
