### ISSUE TITLE
Collapse Component doesn't destroy the component once it is destroyed

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#11056]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ryo7r474lo)

### Steps to reproduce
Please run the Link by clicking on it

### What is expected?
It should destroy the inner components

### What is actually happening?
It is not destroyed

**Comment by afc163** [comment]
https://github.com/react-component/Collapse#collapse

destroyInactivePanel

**Comment by aditya-padhi-kbl** [comment]
@afc163 I believe this is not part of the antd..
