### ISSUE TITLE
穿梭框选中之后再搜索头部会显示类似5/3项的问题

### ISSUE THREAD

**Issue by sunrise555** [ant-design/ant-design#11066]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
头部统计选中项的数量，在有搜索的情况下和没有搜索的情况下应该使用不同的统计显示，否则会出现类似5/3项的显示；具体穿梭框的操作如下：先选中某些项，不勾选，然后再搜索，接着再选中一些项，就会出现类似5/3项的问题

### What does the proposed API look like?
搜索结果下的统计显示和不搜索结果的显示不同

**Comment by yangxiaolin** [comment]
@afc  on [antd offical site](https://ant.design/components/transfer-cn/) can reproduce this question,
![2018-06-29 1 57 15](https://user-images.githubusercontent.com/13888873/42075670-994e48ca-7ba4-11e8-872a-e1368a48cce3.png)

reproduce step as follow:
 - select something items

![2018-06-29 1 57 03](https://user-images.githubusercontent.com/13888873/42075722-deb1de0e-7ba4-11e8-887f-e14f0ac44c5f.png)

 - type some word on search-bar and you can see 9 / 2 项
![2018-06-29 1 57 15](https://user-images.githubusercontent.com/13888873/42075725-e33b6972-7ba4-11e8-9a63-7be1b5ec595e.png)

@sunrise555  i think it's correctly, becase before you type word in seach-bar, you has been select some items

**Comment by yangxiaolin** [comment]
@afc  on [antd offical site](https://ant.design/components/transfer-cn/) can reproduce this question,
![2018-06-29 1 57 15](https://user-images.githubusercontent.com/13888873/42075670-994e48ca-7ba4-11e8-872a-e1368a48cce3.png)

reproduce step as follow:
 - select something items

![2018-06-29 1 57 03](https://user-images.githubusercontent.com/13888873/42075722-deb1de0e-7ba4-11e8-887f-e14f0ac44c5f.png)

 - type some word on search-bar and you can see 9 / 2 项
![2018-06-29 1 57 15](https://user-images.githubusercontent.com/13888873/42075725-e33b6972-7ba4-11e8-9a63-7be1b5ec595e.png)

@sunrise555  i think it's correctly, becase before you type word in seach-bar, you has been select some items

**Comment by afc163** [comment]
It seems to be a bug.
