### ISSUE TITLE
Strange appear transition while using dev server

### ISSUE THREAD

**Issue by geakstr** [ant-design/ant-design#11062]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
browser, antd 3.6.4, ts 2.9.1, custom webpack (4.12.0) config, webpack-dev-server 3.1.4, ts-import-plugin 1.5.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r20p7jq6n)

### Steps to reproduce
When I run project with webpack dev server there is a strange appear animation for components. I attached screencast which shows the problem. 

P.S. When I build project to static files (html   css) all ok

### What is expected?
No appear animation for components

### What is actually happening?
Appear animation for components

---
![kapture 2018-06-27 at 11 34 28](https://user-images.githubusercontent.com/1496368/41960112-eacdb0f6-79ff-11e8-93c7-c318d0744cee.gif)

**Comment by afc163** [comment]
It is normal, because style-loader will load styles asynchronously.

**Comment by geakstr** [comment]
Ok, for development I just created second `index.development.html` file and manually added `<link rel="stylesheet" href="vendor/antd/antd.css" />` into head. Maybe will helpful for someone
