### ISSUE TITLE
TreeSelect

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1106]
is it possible to open branch with selected values only?

i.e. i don't want to use 'treeDefaultExpandAll', because in case wide tree it can be quite slow, but i would like to open/show selected value only.

At least for single value setting.

**Comment by warmhug** [comment]
We will consider.

**Comment by plandem** [comment]
Thanks. It would be a nice feature.

**Comment by warmhug** [comment]
Already support it. use `rc-tree-select@1.2.2`

**Comment by plandem** [comment]
bugged!

here is path:
```
https://www.dropbox.com/s/rsgvf7b7kro72n4/Screenshot%202016-03-03%2014.17.45.png?dl=0
```

here is how it looks (bugged):
```
https://www.dropbox.com/s/7j3e9n2s0sv76ul/Screenshot%202016-03-03%2014.18.01.png?dl=0
```

here is how it MUST look (correct):
```
https://www.dropbox.com/s/xjsz1w5c404mhrb/Screenshot%202016-03-03%2014.19.08.png?dl=0
```

So if there are few levels of tree, then it expand it wrong

**Comment by plandem** [comment]
It can't be quite hard to resolve full path for selected nodes to open. Because you don't use flat list - only roots with children, so this task turns into 'walking tree' task with quite high complexity.

It would stick to additional property for TreeNode. In that case it's up to developer what branches to open. In my case i have 2 version of tree anyway - flat list  indexed by ID and tree for your component. So in my case i can set 'open' branches without any complexity using indexed flat list.

**Comment by warmhug** [comment]
I can't exactly understand what you say. You can modify and run demo with [CodePen](http://codepen.io/anon/pen/pgdXYp?editors=001), thus it will be more clear.

**Comment by plandem** [comment]
I can't reproduce with fake tree :(
http://codepen.io/anon/pen/aNvZVL?editors=001

will try to dig more, because in my case with real tree - it expands wrong :(

**Comment by plandem** [comment]
btw, there is no styles for treeLines :(

**Comment by plandem** [comment]
sorry man, my tree structure was corrupted.
