### ISSUE TITLE
Input.Search 支持 "search on type"

### ISSUE THREAD

**Issue by xpol** [ant-design/ant-design#11065]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在无法在文本变化的时候获得 Input.Search 的内容。这样就没法实现即时搜索（search on type）。
当然最好的方式还是 `Input.Search` 直接有回调函数比如`onSearchChange`.

### What does the proposed API look like?
```jsx
<Input.Search onSearchChange={value => console.log(value) } />
```

**Comment by zombieJ** [comment]
```jsx
<Search
      onSearch={value => console.log(value)}
      onChange={(event) => { console.log(event.target.value); }}
/>
```
