### ISSUE TITLE
Upload 组件  在componentDidMount 更新数据后不会重新渲染

### ISSUE THREAD

**Issue by 2233322** [ant-design/ant-design#11068]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
Chrome  67.0

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
Upload 组件设置了defaultFileList 已经上传的列表， componentDidMount 后返回更新后的this.props.defaultFileList ,不过Upload组件图片还是之前的图片没有更新

### What is expected?
显示componentDidMount更新后的图片

**Comment by yutingzhao1991** [comment]
这个是预期行为，defaultFileList 只有组件初始化的时候有效，后面如果需要再更新的话那请使用受控组件，用 fileList 来控制显示的内容。

**Comment by afc163** [comment]
https://reactjs.org/docs/forms.html#controlled-components
