### ISSUE TITLE
Table组件给列设置宽度不起作用，会按照内容自动伸缩

### ISSUE THREAD

**Issue by Aralhi** [ant-design/ant-design#11072]
### Version
3.6.4

### Environment
mac、Chrome67

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qm4zokv14)

### Steps to reproduce
1. 对Columns的每一列都(或者其中任意几列)设置宽度100px

### What is expected?
期望按照像素设置了的列的列宽是所设置的值，而不是Table组件自己分配的宽度

### What is actually happening?
Table会根据宽度弹性设置列的宽度

---
另外发现，如果设置了scoll.x = 所有列的宽度之和，那么可以达到目的。但显然这是很不合理的
请问一下这是一个bug吗？怎么能达到对某些列设置了像素宽度的列的宽度就是所设置的宽度

**Comment by afc163** [comment]
You can try `scroll={{ x: true }}`

https://codesandbox.io/s/40y1oo5kkx

**Comment by afc163** [comment]
@yesmeck https://github.com/ant-design/ant-design/commit/04ee8526abe08377edc7d6b404742b914aa0e8c5 回滚的原因是什么？https://codesandbox.io/s/40y1oo5kkx 会挂。

**Comment by Aralhi** [comment]
@afc163 scroll={{ x: true }} does not works. But scroll.x = The sum of all column widths works, but poor scalability.

**Comment by afc163** [comment]
Right, we are disscussing about #9704 and 04ee852

**Comment by yesmeck** [comment]
回滚是因为 #9822

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/2203#issuecomment-229009279

**Comment by Aralhi** [comment]
scroll.x = The sum of all column widths works without ‘rowSelection’. If set rowSelection, it does not work.

**Comment by Aralhi** [comment]
by the way, is there a way to set the width of selection column? maybe scroll.x = The sum of all column widths works with ‘rowSelection'

**Comment by yesmeck** [comment]
`rowSelection.columnWidth`

**Comment by yoyo837** [comment]
If `scroll:{x:true}`, the column `width` setting is not work.

**Comment by kobsucTam** [comment]
antd 3.10.2, win7 chrome 71.0.3578.98 遇到同样的问题，Firefox IE10不会，设置了width不会根据内容scale

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by yangfan0095** [comment]
4.6版本还是有问题， 建议自己写一个简单的表格代替组件吧

**Comment by zjsix** [comment]
还没解决。。

**Comment by EugeneYilia** [comment]
还是不行啊  在添加data后 column设置的width无效 还是会动态伸缩

**Comment by yoyo837** [comment]
主题贴有点老了，开新issue吧

**Comment by yaocoding007** [comment]
可以试一下 scroll={{ x: 'max-content' }}

**Comment by liuqituo** [comment]
5.x 的表格也是有一样的问题

**Comment by XiaoPiHong** [comment]
5.14.2也有一样的问题，我总结了一下一共两个问题，column设置的width不生效，就算给了ellipsis，原因就是td没有一个固定的width或者max-width，浏览器不知何时候

**Comment by XiaoPiHong** [comment]
v5.14.2也有一样的问题，我总结了一下一共两个问题，
1、column设置的width不生效（超长的英文内容才会出现这个问题，存在中文的内容不会出现）；
2、给了ellipsis后，没有截断文本和超出省略；
第一种情况是因为td的样式没有设置对英文超出换行的属性，只有overflow-wrap: break-word;而这个属性得基于td有max-width属性的情况，所以设置width后无效，这时候你得给td设置word-break: break-word;或者word-break: break-all;属性来使其换行

第二种情况ellipsis后无法截断内容antd给其td加了overflow: hidden;white-space: nowrap;text-overflow: ellipsis;word-break: keep-all;这些属性，但是这些属性还是基于max-width的，所以还是无效，这时候加一个max-width就可以超出省略了
