### ISSUE TITLE
It would be better if the tree has editable ability, such as add,edit and delete.

### ISSUE THREAD

**Issue by duzliang** [ant-design/ant-design#11070]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
With the editable ability, we can mange the tree structure data more flexible and easy. Mostly, we can mange the tree data in one place. For example, when the cursor hover a node, show add, edit and delete button or icon, then we can add a node for the current node or edit the current node or delete it directly.

It's like one of the jQuery plugin, [zTree](http://www.treejs.cn/v3/main.php#_zTreeInfo)

### What does the proposed API look like?
For example, add these properties to the node:
1. addable
2. editable
3. deletable

In some cases, a node may has only editable and deletable, but a parent node may has all these properties.

**Comment by zombieJ** [comment]
You can customize the `title` prop to support the feature.

```jsx
state = {
  treeData: [
    { title: 'p1' },
    { title: 'p2' },
  ],
};

renderTreeNode = list => list.map({ title }) => (
  <TreeNode title={(
    <div>
      {title}
      <Button onClick={[you add logic for state update]}>Add</Button>
    </div>
  )}
  />
));
```
