### ISSUE TITLE
AutoComplete, Select 的 Option 不应使用 value 作为 key, value 不一定唯一

### ISSUE THREAD

**Issue by angular-moon** [ant-design/ant-design#11074]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
win7 64bit, chrome 版本 67.0.3396.99（正式版本)（32 位)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5ol3wq0ol)

### Steps to reproduce
https://codesandbox.io/s/5ol3wq0ol

### What is expected?
使用 text   value 作为 Option 内组件的 key, 或其他方案

### What is actually happening?
react error:  Encountered two children with the same key

**Comment by zombieJ** [comment]
https://codesandbox.io/s/jpq7m783oy

`value={text}` => `value={value}`

**Comment by angular-moon** [comment]
I mean, I want use value={text}, eg: pick org, submit org name to Server for search

**Comment by zombieJ** [comment]
If both value & label is the same, why do you need display twice?
