### ISSUE TITLE
NumberInput设置为受控组件时，带有千位分隔符的组件依旧会有光标位置不正确的问题

### ISSUE THREAD

**Issue by chenhaizhou** [ant-design/ant-design#11071]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
all browsers

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l7jv40019)

### Steps to reproduce
输入12345

### What is expected?
12,345

### What is actually happening?
12,354

---
非受控组件已修复该问题

**Comment by chenhaizhou** [comment]
这么多天了，代码还没合啊？

**Comment by zombieJ** [comment]
Fixed in `rc-input-number@4.0.11` release. Close issue.
