### ISSUE TITLE
ant design的网站service worker没有更新资源

### ISSUE THREAD

**Issue by hardfist** [ant-design/ant-design#11080]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
chrome  67.0.3396.99

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)
### Steps to reproduce
打开 https://ant.design/index-cn 显示如下
<img width="583" alt="2018-06-28 3 07 33" src="https://user-images.githubusercontent.com/8898718/42021707-e3d019ee-7aed-11e8-8161-dc5dfc7d5b4c.png">

资源预览结果如下
<img width="547" alt="2018-06-28 3 03 31" src="https://user-images.githubusercontent.com/8898718/42021737-fcb1acac-7aed-11e8-8647-6610a880fb49.png">

而点击图片地址，实际图片内容如下
<img width="422" alt="2018-06-28 3 06 12" src="https://user-images.githubusercontent.com/8898718/42021751-06163830-7aee-11e8-9c7d-8129f5d6f5c9.png">
查看service worker的缓存如下
<img width="1183" alt="2018-06-28 3 37 42" src="https://user-images.githubusercontent.com/8898718/42021780-16d0b8f8-7aee-11e8-92f6-3271ce2c5f30.png">

分析应该是某次antd错误上线带上了错误的资源，后来虽然覆盖了资源，但是错误的资源被service worker缓存了，且更新资源后service worker里的资源并未更新，导致用户这里的图片显示一直有问题，且无法通过强制刷新解决。
### What is expected?
更新为正确的资源

### What is actually happening?
没更新为正确的资源

**Comment by yesmeck** [comment]
感谢反馈，已修复，如果还有问题的话可以清一下浏览器缓存。
