### ISSUE TITLE
Modal Component has ESC event，why no Enter event

### ISSUE THREAD

**Issue by yangxiaolin** [ant-design/ant-design#11088]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
OS: MacOS 10.13.4 (17E202).  Browser: Chrome 67.0.3396.99. Antd: 3.6.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kmw5rmk6wv)

### Steps to reproduce
- when Modal is open,  press ESC button， Modal is close
- when Modal is open,  press Enter button, Modal still open

### What is expected?
press Enter button, Modal close

### What is actually happening?
when Modal is show,  press Enter button, Modal still open

**Comment by yesmeck** [comment]
You can press Enter to close modal by focus the ok or cancel button. This is by design.

**Comment by yangxiaolin** [comment]
you said when Modal is open, i should listening Enter press event?

**Comment by yesmeck** [comment]
Focus ok or cancel button, then press <kbd>Enter</kbd>.
