### ISSUE TITLE
disabled parent node cannot spread for TreeSelect

### ISSUE THREAD

**Issue by younth** [ant-design/ant-design#11083]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree 和 TreeSelect 组件的父节点在 disabled 状态下无法展开，影响体验

### What does the proposed API look like?
支持展开即可

**Comment by yutingzhao1991** [comment]
https://codesandbox.io/s/53m7ll8p2k you can click the arrow to expand.

**Comment by younth** [comment]
@yutingzhao1991 arrow is too small , disabled the parent,  the chilren can also expand will be a better experience

**Comment by yutingzhao1991** [comment]
> tree-select 在重构，之后应该可以用 selectable: false 和 onClick 组合出来这个效果。

duplicate https://github.com/ant-design/ant-design/issues/11013
