### ISSUE TITLE
validateFields回调函数的参数errors和values的说明缺失

### ISSUE THREAD

**Issue by pei-han** [ant-design/ant-design#11084]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
便于使用者更好的使用api

### What does the proposed API look like?
起码有的api有详尽的说明，这是最基本的吧

**Comment by afc163** [comment]
Could you help us and try sending us a PR for this?

**Comment by yangxiaolin** [comment]
@pei-han  [here](https://codesandbox.io/s/4xm083k6v0) is a sample example，i will pull request for this issue.

**Comment by yangxiaolin** [comment]
@afc163 hello, i update the document, could you merge it?

**Comment by pei-han** [comment]
@yangxiaolin  我看了一下你的codepen上的栗子，挺好。
只有validateFields函数的回调函数的两个参数中values的说明，缺少了errors的说明

**Comment by pei-han** [comment]
@afc163  thanks so much.
