### ISSUE TITLE
上传Upload的属性fileList中的uid为0时，删除图片时会把后面的全删除。建议文档上写明uid不能为0

### ISSUE THREAD

**Issue by guoguole** [ant-design/ant-design#11089]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
https://ant.design/components/upload-cn/

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
https://ant.design/components/upload-cn/

### What is expected?
建议文档上写明上传Upload的属性fileList中的uid不能为0

### What is actually happening?
hh

**Comment by afc163** [comment]
应该是个 bug。

**Comment by afc163** [comment]
4d5d3c1 修复了相似的问题，但是和楼主的描述不完全一样。
