### ISSUE TITLE
form.item 点击的问题

### ISSUE THREAD

**Issue by walker-jiang** [ant-design/ant-design#11096]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
google

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
给form.item的子组件加点击事件，发现在子组件之外，form.Item之内的区域点击也会触发子组件的点击事件，急急急！

### What is expected?
只有在子组件的区域内点击才触发点击事件

### What is actually happening?
子组件之外，form.item之内的区域点击也触发该函数

**Comment by yangxiaolin** [comment]
@walker-jiang hello, [here](https://codesandbox.io/s/8z73pyy99j) is a example, i can't reproduce your problem. can you try?

**Comment by biology-w** [comment]
设置 htmlFor=""
