### ISSUE TITLE
getFieldDecorator  CheckboxGroup 设置 initialValue无效

### ISSUE THREAD

**Issue by zhaoyanbei** [ant-design/ant-design#11099]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
code:
{getFieldDecorator('targetInstancesIDs', {
              initialValue: ['247','250'],
              rules: [{
                required: true,
                message: '请选择目标实例!',
              }],
              // valuePropName: 'checked',
            })(
              <CheckboxGroup options={instancesOptions} disabled={isEdit}/>
            )}

### What does the proposed API look like?
initialValue值设置生效

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

**Comment by cookcc** [comment]
分两种情况，一种是checkgroup含有组件件checkbox，一种是直接用checkGroup，要使得提问中设置的initivalue生效，均需要在checkboxgroup把发生value带上，像这样<CheckboxGroup value={initivalue}>
