### ISSUE TITLE
Input.Group中使用Form.Item希望有和普通Input一样的合并样式

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#11109]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在组合框中 可以使用内置Form.Item的校验提示https://codesandbox.io/s/ww5vp281yl

### What does the proposed API look like?
Input.Group中使用Form.Item希望有和普通Input一样的合并样式

**Comment by zombieJ** [comment]
可以用自定义组件包一下： https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by ty-bt** [comment]
@zombieJ 我是想两个输入框都作为单独的属性使用getFieldDecorator绑定， 要是使用自定义组件， 两个属性就只能绑定到一个属性上了..

**Comment by zombieJ** [comment]
两种方式吧，放一个 FormItem 下： https://codesandbox.io/s/lppvny9n5l
另一个就自己写 css

**Comment by ty-bt** [comment]
@zombieJ 放在一个FormItem下 组合框中第二个组件的 校验效果就显示不出来了...  应该就只能自己写css了.
