### ISSUE TITLE
getFieldDecorator CheckboxGroup 设置 initialValue没有作用，checkbox没有勾选上

### ISSUE THREAD

**Issue by zhaoyanbei** [ant-design/ant-design#11102]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
window、chrome、react

### Reproduction link
[https://ant.design/components/checkbox/](https://ant.design/components/checkbox/)

### Steps to reproduce
{getFieldDecorator('targetInstancesIDs', {
              initialValue: ['247','250'],
              rules: [{
                required: true,
                message: '请选择目标实例!',
              }],
              // valuePropName: 'checked',
            })(
              <CheckboxGroup options={instancesOptions} disabled={isEdit}/>
            )}

### What is expected?
initialValue设置生效

### What is actually happening?
initialValue没有生效，checkbox没有勾选上

**Comment by yangxiaolin** [comment]
@zhaoyanbei hello, [here](https://codesandbox.io/s/3xoj9kqjw6) is a example,  it's ok

**Comment by yangxiaolin** [comment]
@afc163 you can close this issue

**Comment by indiejoseph** [comment]
有同樣的情況, checkbox 沒有勾

```jsx
<Form.Item>
  {
    getFieldDecorator('equity', {
      initialValue: true,
      valuePropName: 'checked',
    })(
      <label className="Filter-section-title">
        <Checkbox>
          Equity Projects
        </Checkbox>
      </label>,
    )
  }
</Form.Item>
```

**Comment by yangxiaolin** [comment]
@indiejoseph  [here](https://codesandbox.io/s/7jjq1zwz3q), this example use your code, it's ok too. can show you whole code ?

**Comment by yejing2017** [comment]
+1

**Comment by cookcc** [comment]
好多类似这样的问题没有得到解决就关闭了，哎。。。

**Comment by cookcc** [comment]
分两种情况，一种是checkgroup含有组件件checkbox，一种是直接用checkGroup，要使得提问中设置的initivalue生效，均需要在checkboxgroup把发生value带上，像这样<CheckboxGroup value={initivalue}>
