### ISSUE TITLE
DatePicker locale abnormal

### ISSUE THREAD

**Issue by programmer-yang** [ant-design/ant-design#11108]
### version 3.6.4

```javascript
import { LocaleProvider } from 'antd';
import zhCN from 'antd/lib/locale-provider/zh_CN';

<LocaleProvider locale={zhCN}>
  // ...
  <RangePicker />
  // ...
</LocaleProvider>
```
![image](https://user-images.githubusercontent.com/8612167/42080157-442128f8-7bb4-11e8-8c9b-e615a9c6afbc.png)

### expect
![image](https://user-images.githubusercontent.com/8612167/42080220-86c6e01c-7bb4-11e8-99f7-1704e174187c.png)

**Comment by zxj963577494** [comment]
@programmer-yang 我也有这个问题，怎么解决的？

**Comment by programmer-yang** [comment]
@zxj963577494 
```
import 'moment/locale/zh-cn';
```

**Comment by xiaoyierle** [comment]
@programmer-yang 
import 'moment/locale/zh-cn';
这个写上以后，需要给DatePicker设置什么东西吗？

**Comment by zxj963577494** [comment]
@xiaoyierle  @programmer-yang  我是在webpack中将`new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)`注释掉
