### ISSUE TITLE
Form  对Array的绑定无法正常显示值

### ISSUE THREAD

**Issue by hyyan112** [ant-design/ant-design#11100]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
暂无

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0vvrrnxyn)

### Steps to reproduce

    
    import { Form, Input } from 'antd';

    import React, { PureComponent } from 'react';
    import PageHeaderLayout from '../layouts/PageHeaderLayout';

    @Form.create({
    mapPropsToFields(props) {
        const fields = {};
        fields['somearray'] = Form.createFormField({
        value: [{ id: 1111, name: 2222 }, { id: 3333, name: 4444 }],
        });
        fields['foobar'] = Form.createFormField({
        value: 'im fine,this is ok',
        });
        return {...fields}
    },
    })
    export default class TestCase extends PureComponent {

    render() {
        const { form } = this.props;
        const { getFieldDecorator } = form;
        const data = form.getFieldValue('somearray');

        return (
        <PageHeaderLayout>
            {
            data.map((_, index) => {
                return (
                <div>
                    {
                    getFieldDecorator(`foobar`, {
                    })(
                        <Input/>,
                    )
                    }
                    {
                    getFieldDecorator(`somearray[${index}].id`, {
                    })(
                        <Input/>,
                    )
                    }
                    {
                    getFieldDecorator(`somearray[${index}].name`, {
                    })(
                        <Input/>,
                    )
                    }
                </div>
                );
            })
            }
        </PageHeaderLayout>
        );
    }
    }

### What is expected?
input栏显示1111,2222,3333,4444

### What is actually happening?
input栏的值是undefined

**Comment by yesmeck** [comment]
要这样去定义 https://codesandbox.io/s/72q0xpq6px
