### ISSUE TITLE
Example code unavailable in docs

### ISSUE THREAD

**Issue by brianbwong** [ant-design/ant-design#11113]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
Mac OS X, all browsers

### Reproduction link
[https://ant.design/components/popconfirm/](https://ant.design/components/popconfirm/)

### Steps to reproduce
Go to a doc page for any React component, eg https://ant.design/components/popconfirm/. Try to click on the button which shows the example code.

### What is expected?
Example code shows up

### What is actually happening?
No example code

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/42121669-cf4e4d00-7c65-11e8-9ae4-3ff2274300e6.gif)

It works.

**Comment by brianbwong** [comment]
Ah, interesting. I used to always click on the icon to the right of "Examples", which would open all the code on the page. That's what stopped working.
