### ISSUE TITLE
Tree 组件 onCheck触发后获取的halfCheckedKeys错误，实在无法用英文描述这个bug

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#11110]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
Win10 家庭中文版 17134； Chrome 版本 66.0.3359.181

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pyz5k53q40)

### Steps to reproduce
分别勾选2个跟节点下的子节点（0-0-0-0-1，0-0-0-1-1），console里会打出halfCheckedKeys有4个半选节点，然后console里的halfCheckedKeys只存在一个半选节点了，实际会有3个半选节点

### What is expected?
期待halfCheckedKeys里会存在与页面渲染一样数量的半选节点

### What is actually happening?
只会存在与剩余子节点相连的半选父节点

---
这块描述好复杂，是antd的规范就是这样 吗，我需要获取所有的半选节点做处理，感觉这是一个很普遍的需求

**Comment by zombieJ** [comment]
第一次勾选 0-0-0-0-1：
<img width="799" alt="2018-06-30 12 13 23" src="https://user-images.githubusercontent.com/5378891/42121310-2eedfbae-7c5f-11e8-8fc4-1ad8f8588e48.png">

第二次勾选 0-0-0-1-1：
<img width="788" alt="2018-06-30 12 13 42" src="https://user-images.githubusercontent.com/5378891/42121312-47b764ea-7c5f-11e8-988c-5d60088a4e69.png">

看起来没问题啊，你是说哪个不符合预期的？

**Comment by zombieJ** [comment]
@Gong-Elory ， 重现了，谢谢
