### ISSUE TITLE
Checkbox validation not happening if user check and then uncheck the checkbox again.

### ISSUE THREAD

**Issue by AntonBramsen** [ant-design/ant-design#11112]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
MacOS 10.13.4, Chrome 67.0.3396.87 (Official Build) (64-bit), React 16.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7yqyrq91wx)

### Steps to reproduce
Check the checkbox and uncheck it again, then click on the form submit button.

### What is expected?
There should be a validation error, as the required checkbox is not checked when trying to submit the form.

### What is actually happening?
No validation error is shown and the form will successfully submit.

---
The validation works correctly if you try to submit the form before having interacted with the checkbox at all.

**Comment by afc163** [comment]
https://codesandbox.io/s/52zwyrq34x
