### ISSUE TITLE
Popconfirm support set custom icon?

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#11124]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Popconfirm can set custom icon!

### What does the proposed API look like?
```jsx
<Popconfirm icon={<Icon type="question-circle-o" style={{ color: 'red' }} />} />
```

![popconfirm](https://user-images.githubusercontent.com/1730277/42154236-cccb5b82-7e17-11e8-9f80-af5edef4ec36.png)

**Comment by yesmeck** [comment]
PR's welcome.

**Comment by nuintun** [comment]
@yesmeck PR to 3.7.0 or master?

**Comment by yesmeck** [comment]
3.7.0

**Comment by nuintun** [comment]
@yesmeck OK, I will send a PR later.

**Comment by nuintun** [comment]
@yesmeck #11127

**Comment by nuintun** [comment]
@yesmeck Not accept this feature request #11191 ?

**Comment by yesmeck** [comment]
是因为 3.7 分支被删了，PR 自动关闭了。

**Comment by afc163** [comment]
Added in #11191
