### ISSUE TITLE
webstorm 提醒 attribute 没有

### ISSUE THREAD

**Issue by wangcongyi** [ant-design/ant-design#11123]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 webstorm：2018.1.5 & antd：3.6.2 中  
例如使用了 Button 组件  <Button></Button> 没有设置任何的 attribute 
webstorm 就会提醒 Element Button doesn't have required attribute .........
因为在 button.d.ts 中 
static propTypes: {
        type: any;
        shape: any;
        size: any;
         ....
    };

### What does the proposed API look like?
我希望 websotrom 不提醒 

static propTypes: {
        type?: any;
        shape?: any;
        size?: any;
      ......
    };

**Comment by chenshuai2144** [comment]
show code？

**Comment by wangcongyi** [comment]
这不是 代码错误 而是 编辑器有提醒

![a](https://user-images.githubusercontent.com/13843979/42152820-e7094a6c-7e13-11e8-8374-f8ea0bf25679.jpg)

**Comment by chenshuai2144** [comment]
改掉这个鸡毛设置吧，很烦人的

**Comment by wangcongyi** [comment]
@chenshuai2144 
但是 想灵活一点啊
  有些 attr 是必须的  有些可有可无

**Comment by chenshuai2144** [comment]
antd 官方并没有任何必须项.
看这里 https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L5812

**Comment by wangcongyi** [comment]
那以后 antd 有没有可能做下 ‘适配’工作呢？
而且 我觉得 会让 antd 更加灵活一下啊
  ： -->>  ?:

**Comment by chenshuai2144** [comment]
你配置一下编辑器 岂不是更美滋滋

**Comment by wangcongyi** [comment]
编辑器是根据代码来提醒的
这种编辑器的提醒 我觉得是 OK 的啊 
不过 修改 antd 的 propTypes 工作量是挺大的，
但是 会更加灵活 更加友善嘛

**Comment by SergeyVolynkin** [comment]
Yep, same with me.
Will be glad to know how to fix it in WebStorm
![image](https://user-images.githubusercontent.com/34238697/48677392-6dcb0700-eb85-11e8-8d44-f21781749841.png)

WebStorm warns on commit every time :)

**Comment by fwh1990** [comment]
You may get some solution here:

https://youtrack.jetbrains.com/issue/WEB-35183
