### ISSUE TITLE
Embedded DatePicker instead of floating in a layer

### ISSUE THREAD

**Issue by miksansegundo** [ant-design/ant-design#11128]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Always keep visible the calendar inline/embed in the content and not floating.

### What does the proposed API look like?
Maybe just a prop called "embed" or something. For instance in http://react-day-picker.js.org/ is the default behaviour and then they have component to show it on an input: http://react-day-picker.js.org/docs/input

**Comment by afc163** [comment]
http://ant.design/components/calendar

**Comment by zomars** [comment]
@afc183 Both `Calendar` and `DatePicker` solves very different issues. With Calendar we don't have a month switcher and Calendar doesn't respects `disabledDate` when you use the month switcher. I suggest we re-open this issue.

DatePicker | Calendar
--- | ---
<img width="282" alt="image" src="https://user-images.githubusercontent.com/3504472/62650798-dc6b1300-b914-11e9-9d4c-21006506deca.png"> | <img width="295" alt="image" src="https://user-images.githubusercontent.com/3504472/62650960-310e8e00-b915-11e9-8140-6c7b65495ec2.png">

**Comment by zomars** [comment]
In Calendar if you have `disabledDates` prop and use the month selector it will still call the `onChange` callback. With DatePicker this doesn't happens:

<img width="302" alt="image" src="https://user-images.githubusercontent.com/3504472/62651178-a712f500-b915-11e9-94c4-e13545591629.png">

**Comment by edmundsj** [comment]
I would also like this feature - would prefer to have a floating calendar as opposed to a pop-up one. It makes design much easier.
