### ISSUE TITLE
UI display incorrectly when Table no data in Firefox 61.0

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#11135]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
Firefox 61.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/926jnjqjo)

### Steps to reproduce
Tabe set dateSource empty

### What is expected?
UI display correctly

### What is actually happening?
UI display incorrectly

![_20180703154912](https://user-images.githubusercontent.com/1730277/42206102-c36aa694-7ed8-11e8-93b9-ba4ddf4e57fc.png)

**Comment by afc163** [comment]
Try reinstall node_modules.

**Comment by nuintun** [comment]
@afc163 这么修改有问题，设置表头固定的时候如果内容没出滚动条列会对不齐

![_20180703183529](https://user-images.githubusercontent.com/1730277/42215154-2f4ddb76-7ef0-11e8-80d6-28a64086f6b3.png)

又发现 Firefox 一个奇葩的问题， 负 margin 不生效

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3rwr9wymw1)

![_20180703184047](https://user-images.githubusercontent.com/1730277/42215330-a61efc30-7ef0-11e8-8c0b-a6f0da2b3546.png)

**Comment by afc163** [comment]
`table-layout: fixed` 会有其他副作用，我再看看。

**Comment by nuintun** [comment]
@afc163 `table-layout: fixed` 设置完是有些副作用，不过还可以接受，比如下面的例子：

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q9zwxnqmr4)

在设置表头 `fixed` 的情况下，如果过折叠内容过多， ie, edge 就会出现对不齐的情况，chrome 正常，火狐未测，现在表格坑的地方是一不小心就会出现对不齐的情况 😯

**Comment by nuintun** [comment]
@afc163 火狐表头下面有空隙问题不用负 `margin` 就行了 (参考 `tabalinas/jsgrid` 和下图)

![_20180704094041](https://user-images.githubusercontent.com/1730277/42252311-94539bea-7f6e-11e8-8fe5-5557631dba3f.png)

这样可以不用获取滚动条宽度计算负 `margin` 了，也杜绝了用户自定义滚动条存某些情况下滚动条宽度计算错误的问题。

第二个问题两种办法：
 - 没数据的时候设置 `ant-table-body: overflow: auto` 。
 - 把 `ant-table-placeholder` 移到 `ant-table-body` 中。

**Comment by lijianxin1202** [comment]
请问下样式为什么要应用important呢，更新后直接导致对它的自定制样式失效了
