### ISSUE TITLE
The component of InputNumber isn't lose focus and it can input any letter!

### ISSUE THREAD

**Issue by zhuzhuyule** [ant-design/ant-design#11143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
v3.6.5

### Environment
Safari

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nrlv85ojkj)

### Steps to reproduce
1. enter 1234 into the first InputNumber;
2. enter 1234 into another InputNumber;
3. repeat step 2.

### What is expected?
any InputNumber component value is 1234.

### What is actually happening?
just the first InputNumber component(first get focus) can input numbers.

**Comment by zombieJ** [comment]
Fixed.
Pls reinstall `rc-input-number@4.0.12`: https://codesandbox.io/s/qlo7k1x4p9

**Comment by zhuzhuyule** [comment]
@zombieJ 
but,  it can enter any letter, is it right ?

**Comment by zombieJ** [comment]
@zhuzhuyule , what's the reproduction steps?
![kapture 2018-07-04 at 14 06 36](https://user-images.githubusercontent.com/5378891/42259579-9f063c80-7f93-11e8-9d87-f66e6930b6b8.gif)
