### ISSUE TITLE
Alert组件状态值的字体颜色按照@text-color 取值导致的问题

### ISSUE THREAD

**Issue by bluesh** [ant-design/ant-design#11146]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
antd2.13.14

### Reproduction link
[https://github.com/bluesh/antd-darktheme/tree/master/examples/customize-antd-theme](https://github.com/bluesh/antd-darktheme/tree/master/examples/customize-antd-theme)

### Steps to reproduce
主题颜色配置
{
    '@layout-body-background': '#404040',
    '@body-background': '#404041',
    '@layout-sider-background': '#313131',
    '@component-background': '#313132',
    '@input-bg': '#313133',
    '@btn-default-bg': '#262626',
    '@border-color-base': '#1e1e1e',
    '@border-color-split': '#262627',
    '@heading-color': 'fade(#fff, 85%)',
    '@text-color ': 'fade(#fff, 80%)',
    '@primary-1': 'fade(#000, 15%)',
    '@text-color-secondary ': 'fade(#fff, 65%)',
  }
即：https://github.com/bluesh/antd-darktheme/blob/master/examples/customize-antd-theme/theme.js 

### What is expected?
反转主题色之后，Alert的字体颜色color应该是保持之前的黑灰色（毕竟状态背景色没有变

### What is actually happening?
反转主题色之后，Alert的字体颜色color变成@text-color的白色，导致在状态背景色下看不见文字了

**Comment by yesmeck** [comment]
`@alert-text-color`
