### ISSUE TITLE
 form 组件设置initialValue 后 validator失效

### ISSUE THREAD

**Issue by houdingding** [ant-design/ant-design#11156]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
MAC10.13.4  chrome 67.0.3396.99 

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
     
    handleInspectModNmaeTest = (rule, app_name, callback) => {
        console.log(rule)
        if (app_name) {
            const pattern = new RegExp("^[a-zA-Z][a-zA-Z0-9-.] $")
            if (!pattern.test(app_name)) {
                callback('模块名字不合法，示例:abcad-abc')
            } else {
                this.props.modularservice.modular_name_check(
                    app_name, this.props.app_type, callback)
            }
        } else {
            callback()
        }
    }
 <FormItem
                    key='1'
                    label="模块名"
                >
                    {getFieldDecorator('app_name', {initialValue: "1"},{
                        rules: [{
                            required: true, message: '请输入模块名!', whitespace: true,
                        }, {
                            validator: this.handleInspectModNmaeTest.bind(this),
                        }],
                        validateTrigger: 'onChange'
                    })(
                        <Input placeholder="请输入模块名" autoComplete='off'/>
                    )}
                    {console.log("a")}
                </FormItem>

### What is expected?
在设置初始化值时，在更改后input值后能够进行校验

### What is actually happening?
无校验

**Comment by houdingding** [comment]
你好链接入下
https://codesandbox.io/s/00rp9xnl6n

**Comment by houdingding** [comment]
你好@ant-design-bot 
链接如下
https://codesandbox.io/s/00rp9xnl6n

**Comment by Gong-Elory** [comment]
getFieldDecorator(id, options) 
it doesn't have the third params
```javascript
{
              initialValue: 1,
              rules: [
                {
                  required: true,
                  message: "必填项"
                },
                this.handleInspectModNmaeTest.bind(this)
              ]
              // validateTrigger: "onChange"
            }
```

**Comment by houdingding** [comment]
来信已收到，测试无异常，非常感谢

**Comment by afc163** [comment]
解决问题请自行关闭 issue。
