### ISSUE TITLE
通过 import 'antd/lib/index.css' 引入样式不能使用

### ISSUE THREAD

**Issue by WenXuanYuan** [ant-design/ant-design#1115]
我通过import 'antd/lib/index.css' 在入口处引入了ant的官方样式，但是我写<Icon type='inbox'/>后却没有看到图标，审查元素后发现html标签转化正常，css也通过extract-text-webpack-plugin打包正常，请问这个是怎么回事呢？貌似转化后的i没有找到anticon和anticon-inbox这两个样式

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#providing-a-demo-while-reporting-a-bug

**Comment by afc163** [comment]
看看是否 https://github.com/ant-design/ant-design/issues/1070 类似的问题。

**Comment by WenXuanYuan** [comment]
@afc163 解决掉了，谢谢帮助

**Comment by afc163** [comment]
是什么问题可以分享一下么

**Comment by WenXuanYuan** [comment]
@abc163

我从npm上安装后发现lib下面的css是这个样子
@font-face {
  font-family: 'anticon';
  src: url('//at.alicdn.com/t/font_1452596235_7047422.eot');
  /* IE9*/
  src: url('//at.alicdn.com/t/font_1452596235_7047422.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */ url('//at.alicdn.com/t/font_1452596235_7047422.woff') format('woff'), /* chrome、firefox */ url('//at.alicdn.com/t/font_1452596235_7047422.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/ url('//at.alicdn.com/t/font_1452596235_7047422.svg#iconfont') format('svg');
  /* iOS 4.1- */
}
.anticon {
  display: inline-block;
  font-style: normal;
  vertical-align: baseline;
  text-align: center;
  text-transform: none;
  text-rendering: auto;
  line-height: 1;
}
.anticon:before {
  display: block;
  font-family: "anticon" !important;
}
然后我将字体库下载到了本地并且修改了路径，然后字体可以正常加载，但是不明白原来为什么不行
我是在本地的localhost环境中写的

**Comment by afc163** [comment]
网络有问题？试试：http://at.alicdn.com/t/font_1452596235_7047422.eot 能否访问

**Comment by WenXuanYuan** [comment]
哦哦，这个样子的呀。这个可以正常访问
