### ISSUE TITLE
cannot customize 'trigger' of Layout Sider when collapsedWidth={0}

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#11153]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
Chrome 67.0.3396.87

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3wkypjz8w)

### Steps to reproduce
set collapsedWidth={0}
set trigger={<Icon type="menu-fold" />}

### What is expected?
the trigger icon should change

### What is actually happening?
it doesn't change.

**Comment by Rehubbard** [comment]
I believe this is still an issue. If you pass your own component into the `trigger` prop, nothing changes. The default trigger and icon is still displayed no matter what. Any plans to fix this?

**Comment by ztplz** [comment]
@Rehubbard  Could you provide a online demo for this problem ? The sandbox address provided by the author of the issue does not exist.

**Comment by Rehubbard** [comment]
Sure, here's a simplified example: https://codesandbox.io/s/7258jq6yoq

If you inspect the elements in the side bar, you can still see the default trigger in there. Where it should be my custom component I passed in. Let me know if I can provide anything else. Thanks!

**Comment by ztplz** [comment]
Thanks, if it is a bug, we will fix it ASAP.

**Comment by Rehubbard** [comment]
Also, if you place the `<Sider>` on the right side, the default trigger doesn't behave correctly. Could be a separate issue, but just wanted to point it out

**Comment by YasmineHamdy** [comment]
i have the same issue 
is this issue solved?

**Comment by ztplz** [comment]
@YasmineHamdy  When the `collapsedWidth` is 0, it has a default `trigger`.

**Comment by Oleg4370** [comment]
The same issue, when collapsedWidth={0} and some custom triger
trigger={<button>Trigger</button>}

**Comment by mtsalenc** [comment]
News on this? I need to use a custom event on click but I can't pass in my own component.

**Comment by mtsalenc** [comment]
News on this? I still can't pass in my own component.

**Comment by WG75** [comment]
> @YasmineHamdy When the `collapsedWidth` is 0, it has a default `trigger`.

but there should be a way to override this default trigger with a custom component!!

I went through the source code and I think I can fix it. Should I submit a pull request if I do fix it?

**Comment by lipemat** [comment]
Issue is still present although I was able to create somewhat of a workaround by using the same css classes generated by the default trigger. 

Using simple function component and a hook to manage state it does the job for now.

```js
const SidebarCollapsed = () => {
	const [ collapsed, setCollapsed ] = useState( true );
	return (
		<Sider
			collapsible
			collapsed={collapsed}
			collapsedWidth={0}
			trigger={null}>
			<span className={'ant-layout-sider-zero-width-trigger ant-layout-sider-zero-width-trigger-left'}>
				<Icon type={'bars'} onClick={() => setCollapsed( ! collapsed )}/>
			</span>
			<SIDBAR_CONTENT_COMPONENT_GOES_HERE />
		</Sider>
	)
}
```
Upon writing this I noticed this issue is "Closed" and may be worth creating a new issue to get this resolved properly...

**Comment by qhh001** [comment]
@chj-damon

**Comment by qhh001** [comment]
@ant-design-bot

**Comment by lafllamme** [comment]
> The same issue, when collapsedWidth={0} and some custom trigger `trigger={<button>Trigger</button>}`

Document NOWHERE lmao. big thx

**Comment by EverStarck** [comment]
> > The same issue, when collapsedWidth={0} and some custom trigger `trigger={<button>Trigger</button>}`
> 
> Document NOWHERE lmao. big thx

It's documented here: https://ant.design/components/layout#components-layout-demo-custom-trigger
