### ISSUE TITLE
small table can't  hide border by using bordered

### ISSUE THREAD

**Issue by Angelki** [ant-design/ant-design#11161]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
all

### Reproduction link
[![Edit 81kyo24m22](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/81kyo24m22)

### Steps to reproduce
        <Table
            bordered={false}
            size="small"

### What is expected?
hide all borders

### What is actually happening?
cannot hide the boder outside

**Comment by afc163** [comment]
It is by designed.

**Comment by snirp** [comment]
That may be a sign of bad design, if you offer an explicit `bordered` parameter and it has no effect. Any change to reconsider this counter-intuitive behavior?

**Comment by jakubknejzlik** [comment]
The `bordered` seems to work, but only for the inner border. Is there any reason for `size="small"` to have border turned on?
Specifically these lines: https://github.com/ant-design/ant-design/blob/master/components/table/style/size.less#L40-L41

**Comment by keithort** [comment]
If it is by design, the design should change. It is inconsistent and counter-intuitive.

**Comment by LSanOI** [comment]
Also would like to have the possibility of removing outer table borders on small table

**Comment by kiishkishan** [comment]
This is a major defect on Ant Design. I am facing bigger problems because of this problem. you have to fix it

**Comment by taiwanhua** [comment]
you can do like below:

.ant-table-tbody > tr > td {
    border-bottom: 0px solid #f0f0f0;
}
