### ISSUE TITLE
虽然能自定义主题，自定义组件感觉比较薄弱

### ISSUE THREAD

**Issue by RenChunhui** [ant-design/ant-design#11162]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At present, the function of ant design is quite powerful, but it feels that the custom component is not very smooth. If the model header wants to be a custom color, can it be modified globally by changing a variable, there are some internal layouts of the component, like Modal's OK cancels no layout interface, and there is no display of this block, you can set the footer, then Add, if you can have an interface, it is better. This aspect of ionic is doing a good job.

### What does the proposed API look like?
``` less
@ant-modal-header-background: blank;
```

**Comment by zhujinxuan** [comment]
Try rc-components?

**Comment by afc163** [comment]
You can send PR for `@modal-header-bg` less variable.
