### ISSUE TITLE
Being able to hide Calendar filters and only render specific days to be able to fit more content

### ISSUE THREAD

**Issue by JoaoCnh** [ant-design/ant-design#11171]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This refers to the Calendar component.

I would like to hide the filters or at least customize what they do.

The second thing is only rendering specific days like only rendering 2 weeks, so I can fit more content into each day cell.

### What does the proposed API look like?
To not render filters you could provide a prop function like renderFilters and the user could return null if no filters were to be used.

**Comment by zombieJ** [comment]
1. You can use css to hide the filter.
2. You can use `dateFullCellRender` by render your date cell (return `null` to display nothing)

https://codesandbox.io/s/n06r8jwp1p
