### ISSUE TITLE
https://mobile.ant.design/页面打不开

### ISSUE THREAD

**Issue by zhuhaixia** [ant-design/ant-design#11178]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
谷歌浏览器

### Reproduction link
[https://mobile.ant.design/](https://mobile.ant.design/)

### Steps to reproduce
1.进入https://ant.design/docs/react/introduce-cn
2.点击Ant Design Mobile后显示连接被重置，页面打不开

### What is expected?
Ant Design Mobile页面能打开

### What is actually happening?
Ant Design Mobile页面能打开

**Comment by wuyandefeixue** [comment]
@ant-design-bot 
https://pro.ant.design/
https://preview.pro.ant.design/
Do these addresses have corresponding mirrors？
