### ISSUE TITLE
Combobox does not mimick non combobox behavior

### ISSUE THREAD

**Issue by Geczy** [ant-design/ant-design#11177]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
Win 10, Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lrnw3kv8m)

### Steps to reproduce
1. In first select field, type "A" and press TAB
2. In 2nd select field, type "A" and press TAB

### What is expected?
Expected to select Jack in step 2 just like it did in step 1

### What is actually happening?
Saves your "a" input as the select value

**Comment by zombieJ** [comment]
'combo' mode accept the input value as value, user can type any string not match in option list. It's correct behavior.
