### ISSUE TITLE
webpack构建，按需加载样式不生效

### ISSUE THREAD

**Issue by YanYuanFE** [ant-design/ant-design#11181]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
ubuntu16.04,Chrome 67.0.3396.99（正式版本） （64 位）

### Reproduction link
[https://github.com/YanYuanFE/react-start-app/tree/dev](https://github.com/YanYuanFE/react-start-app/tree/dev)

### Steps to reproduce
配置webpack4的antd按需加载，样式不能正确打包

### What is expected?
正确打包antd样式

### What is actually happening?
页面antd样式显示不正确，antd样式未打包

---
使用了css module，对antd和自己代码的样式在webpack中进行了分别处理

**Comment by Gong-Elory** [comment]
`{
  "presets":["@babel/react", "@babel/env"],
  "plugins": [
//    "dva-hmr",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    [
      "import", {
        "libraryName": "antd",
        "style": "true"
      }
    ]
  ]
}`

remove double quote of  this value of 'style'

**Comment by YanYuanFE** [comment]
感谢，已解决
