### ISSUE TITLE
Combobox Select With Form will auto display panel when options changed 

### ISSUE THREAD

**Issue by walker27** [ant-design/ant-design#11187]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.14

### Environment
Chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0o58x4nyxp)

### Steps to reproduce
1. click Button "Change to empty options"
2. focus on select input
3. click Button "Change to full options" then wait 2 seconds

### What is expected?
panel will not auto dispaly

### What is actually happening?
panel will auto dispaly

**Comment by jochenshi** [comment]
Have you solved this problem?

**Comment by walker27** [comment]
@jochenshi not yet

**Comment by afc163** [comment]
antd@3.8.2 seems to have fixed this problem: https://codesandbox.io/s/615nmjjx2n

2.x was not maintained any more.
