### ISSUE TITLE
RadioGroup features request...

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1119]
1) There is no default way to align it vertically
2) There is no way for custom render, i.e. i need to show some additional input when radio selected. I see it like this: a) vertically align radio group with additional inputs at right side that shows only when radio is checked. For this case i need custom render, but looks like it can't be done, because radio wrapped with 'label'

I need something like this:
```
<RadioGroup>
 <Row>
  <Col span="3">
   <Radio>choice 1</Radio>
  </Col>
  <Col span="5">
   <Input>
  </Col>
 </Row>
</RadioGroup>
```

or 
```
<RadioGroup>
 <Radio>
  <Label>choice 1</Label>
  <Input>
 </Radio>
</RadioGroup>
```

Right now i have to implement all logic that RadioGroup already has, but use differ component to get it :(

**Comment by plandem** [comment]
as final result i would like to have something like:
https://www.dropbox.com/s/tuxk5qbmlawouci/Screenshot%202016-03-03%2019.42.18.png?dl=0

Right now there is no RadioGroup, but bunch of Radio with same 'onChange' handler and workarounds for 'checked'

**Comment by afc163** [comment]
I will publish a fixed version later.

**Comment by afc163** [comment]
http://ant.design/components/radio/#demo-radiogroup-more

**Comment by plandem** [comment]
thanks, man!

**Comment by g8up** [comment]
I layout RadioGroup like this below, but It apears not in the same group. Am I wrong ?
```jsx
<Row>
  <RadioGroup name="myRadio">
    <Col span="12">
    <Radio>item 1</Radio>
    </Col>
    <Col span="12">
    <Radio>item 2</Radio>
    </Col>
    <Col span="12">
    <Radio>item 3</Radio>
    </Col>
    <Col span="12">
    <Radio>item 4</Radio>
    </Col>
  </RadioGroup>
</Row>
```
