### ISSUE TITLE
Formatter on normal input

### ISSUE THREAD

**Issue by marklaihk01** [ant-design/ant-design#11198]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm working on a form and want to trim down spaces
ie: "abc      " to "abc"
and if the input is all space, it shouldn't pass the field check at all (i'm using FieldDecorator)
I saw the Input.number has the ability to set formatter, perhaps Input can also do that?? 

### What does the proposed API look like?
just copy the logic from Input.number to input

**Comment by Gong-Elory** [comment]
firstly:
you can use options.rules to validate that all space case 
secondly:
you can use options.normalize to normalize the raw value
[getFieldDecorator](https://ant.design/components/form-cn/#getFieldDecorator(id,-options)-%E5%8F%82%E6%95%B0)

**Comment by marklaihk01** [comment]
@Gong-Elory First, thanks a lot for helping
I tried options.normalize but it triggers every time I type
then I'm not able to type in space, my expectation is do it at onBlur
any solution??

**Comment by marklaihk01** [comment]
@chenshuai2144 @Gong-Elory just play around with rules.transform
but it doesn't behave like async-validator said, it should mutate the value on submit, but it doesn't do anything, any idea??

**Comment by chenshuai2144** [comment]
try getValueFromEvent？

**Comment by marklaihk01** [comment]
@chenshuai2144 same as options.normalize, it fires every time user input
if I return value.trim(), the user won't be able to type in space at all

**Comment by darylszehk01** [comment]
got the same issue these days.

**Comment by joelgetaction** [comment]
Hey @Gong-Elory any update?  `normalize` just doesn't work properly because it first with every keystroke, so although it does properly normalize `" Hello "` (which properly normalizes to `"Hello"`) it will not even allow me to type in `"Hello World"` because the space between Hello and World gets removed and there's no way to add it.

So normalize needs to be run only before validation ...  I would consider the current behavior to be not very useful for trim like operations.

Any chance we could get a change in this behavior?

Thanks!

**Comment by shreyansRS** [comment]
hey guys just see this code 
` <Form.Item style={{ width: "100%" }} label={<span className="h3">Description</span>} colon={false}>
                                        {getFieldDecorator('description', {
                                            rules: [
                                                { transform: (value) => value.trim() },
                                                { required: true, message: 'Description is required!' },
                                                { max: 4000, message: 'Description should be less than 4000 characters!' }
                                            ]
                                        })(<Input.TextArea autosize={{ minRows: 3, maxRows: 5 }} placeholder="Describe the issue" />)}
                                    </Form.Item>`

**Comment by dimasusername** [comment]
Use `https://nosir.github.io/cleave.js/`, and set the class to `ant-input`.

**Comment by nikmargit** [comment]
One solution is to create a method that will trim input value on blur and set it as a new field value:
```javascript
 const trimInput = ({ target }) => {
     const { id, value } = target;
     this.props.setFieldsValue({ [id]: value.trim() });
 }
```
and then use it in the form input like this:
```javascript
{getFieldDecorator(`fieldName`)(<Input onBlur={trimText} />)}
```

**Comment by denishjariwala** [comment]
You can try following code
rules: [{ whitespace: true}]

**Comment by pabloandreychacon** [comment]
> You can try following code
> rules: [{ whitespace: true}]

That one solved my problem

**Comment by anaggithub** [comment]
>  { max: 4000, message: 'Description should be less than 4000 characters!' }

Hi there!!
Is there a way to add a max length to the ant design form items, instead of doing the max:400 validation?

**Comment by hsgadi** [comment]
> You can try following code
> rules: [{ whitespace: true}]

That one solved my problem too

**Comment by MalvinJay** [comment]
> You can try following code
> rules: [{ whitespace: true}]

This is only for 'string' type. For 'email' type, it won't work

**Comment by chathurabuddi** [comment]
> > You can try following code
> > rules: [{ whitespace: true}]
> 
> This is only for 'string' type. For 'email' type, it won't work

For emails, you can use `rules: [{ type: email}]`

**Comment by Jsmond2016** [comment]
Try to use `onChange` to trim value

```jsx
<Input onChange={() => form.setFieldsValue({keyword: (form.getFieldValue('keyword') || '').trim() })} />
```
