### ISSUE TITLE
RangePicker: Unable to use 24-hour clock

### ISSUE THREAD

**Issue by stoneox** [ant-design/ant-design#11199]
**Version**

3.6.5

**Environment**

Chrome 66

**Reproduction link**

[Edit on CodeSandbox](https://codesandbox.io/s/lx3l3kjk3m)

**Steps to reproduce**

1.click RangePicker component
2.select time 21:00:00

**What is expected?**

RangePicker show 21:00:00

**What is actually happening?**

show 9:00:00，Unable to use 24-hour clock

**Comment by dengfuping** [comment]
@stoneox `hh` means 12-hour system and `HH` means 24-hour system.
```diff
import React from "react";
import ReactDOM from "react-dom";
import { DatePicker } from "antd";

import "./styles.css";
import "antd/dist/antd.css";

const RangePicker = DatePicker.RangePicker;

function App() {
  return (
    <div className="App">
      <RangePicker
-       showTime={{ format: "hh:mm:ss" }}
-       format="YYYY-MM-DD hh:mm:ss"
+       showTime={{ format: "HH:mm:ss" }}
+       format="YYYY-MM-DD HH:mm:ss"
      />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```
