### ISSUE TITLE
Keyboard friendly Table component

### ISSUE THREAD

**Issue by cnagadya** [ant-design/ant-design#11194]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
MacOs

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w03yv2qw6l)

### Steps to reproduce
Use the tab key to move between table cells and expand the nested rows

### What is expected?
Users to be able to navigate through the table using their keyboard keys

### What is actually happening?
Cant expand the nested elements but can navigate through the links in the action column

---
We are considering using antd for a new project and having keyboard support would be great.

**Comment by afc163** [comment]
trace #4102

**Comment by beostefan** [comment]
If this issue could be solved, it could really help my project. Is it somehow on the roadmap?

**Comment by beostefan** [comment]
@afc163 As you closed this issue, could you give a short feedback on the status of tab navigation within editable tables, please? Thank you.
