### ISSUE TITLE
Modal.confirm在点击确认后，我应该如何阻止它关闭窗口

### ISSUE THREAD

**Issue by kingmoumoumou** [ant-design/ant-design#11209]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Modal.confirm在点击确认后 , 如果有一些重要提示,我不希望当前窗口自动关闭. 

### What does the proposed API look like?
Modal.confirm 如果赋值,  希望能通过.destroy();进行关闭, 或者如果设置了visible 属性,也能通过visible来控制显示与关闭!

**Comment by kingmoumoumou** [comment]
1

**Comment by zhangchao828** [comment]
可以返回一个promise来解决
![1531186715](https://user-images.githubusercontent.com/15683846/42484350-311be634-8425-11e8-9cfa-dff74550099d.jpg)

**Comment by kingmoumoumou** [comment]
我用modal自己封装了一个组件实现了,  你这个有一个问题, loading会一直存在

**Comment by afc163** [comment]
参数 resolve 漏了
