### ISSUE TITLE
getFieldDecorator嵌套id的使用

### ISSUE THREAD

**Issue by Puuuudding** [ant-design/ant-design#11205]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
macOS 10.13, Chrome 69.0.3485.0

### Reproduction link
[https://codepen.io/puuuudding/pen/wxwgmJ?editors=0011](https://codepen.io/puuuudding/pen/wxwgmJ?editors=0011)

### Steps to reproduce
使用code pen提供的例子

### What is expected?
控制台不报错

### What is actually happening?
getFieldValue拿回来的对象属性错误

---
根据form的[例子](ant-design/components/form/demo/dynamic-form-item.md)我在实现动态form item的时候发现有这么个问题。

当我用`getFieldDecorator`初始化一个object，当我在使用后发现用`getFieldValue`拿回来的对象会有个空key的property，值是这个object的初始化的值。而且如果用`object[key]`的方法使用嵌套的话会导致key错误。

这样就会导致控制台一直报错，而且因为这个空key的属性存在没法把这个object当数组对待。

请问是我嵌套id的使用方法有问题么？完全按照例子的写法是无法使用的。

**Comment by afc163** [comment]
```
"Warning: One field name cannot be part of another, e.g. `a` and `a.b`."
```

现在不支持两个表单项的 key 互相内嵌。

**Comment by Puuuudding** [comment]
可是我并没有两个表单项的key互相内嵌，即使完全按照官网的样例来写，也会出这样的问题

**Comment by afc163** [comment]
<img width="664" alt="image" src="https://user-images.githubusercontent.com/507615/42682925-77691cf6-86be-11e8-8bb5-a46a0ff5ef62.png">

不能这样内嵌调用 getFieldDecorator 的。

**Comment by Puuuudding** [comment]
在[官方的文档](https://github.com/ant-design/ant-design/blob/master/components/form/demo/dynamic-form-item.md)中是用`[]`的方式调用
![image](https://user-images.githubusercontent.com/8097548/42752594-fad90808-8920-11e8-8fa2-fd832e94ca0a.png)
在我的例子里两种方式都有
![image](https://user-images.githubusercontent.com/8097548/42752605-08b32d32-8921-11e8-9cc8-bcfae7f4f309.png)
可以看到两种方式都会导致这个问题，而且用`[]`的时候还会有key字符串截取错误
![image](https://user-images.githubusercontent.com/8097548/42752657-2ba6f044-8921-11e8-9d57-dc2a0fb360df.png)

**Comment by afc163** [comment]
1. 用了 `getFieldDecorator('a.b')` 就不能用 `getFieldDecorator('a')`。
2. 支持 `name[0]`  `name[1]`  `name.a` 但是不支持 `name[b]`：https://lodash.com/docs/#get

**Comment by Puuuudding** [comment]
1. 我更新了下codepen，你可以打开看一下，即使一开始不做`getFieldDecorator('a')`的操作，仍然出错
1. 而且单独注释掉L20或者L21，还是保留两个，都会发生没有key的object情况
1. 我做了下测试，lodash完全支持这样的写法
![image](https://user-images.githubusercontent.com/8097548/42796605-b043360e-89bd-11e8-925e-72a72274f6ed.png)

**Comment by hosembafer** [comment]
Guys, what about nested objects of arrays in forms? I have asked this questing in another related issue, but have no answer. If antd does not support it yet, so please, let me know. I have a project with antd and now I have the problem.

**Comment by Puuuudding** [comment]
@hosembafer my problem is focusing on dynamically add/remove form items. You shall open a new issue about nested objects of array

**Comment by Puuuudding** [comment]
@afc163 你好，有什么进展么？

**Comment by tcatche** [comment]
I also had the problem, and i found when i stop to call  `getFieldValue(data)` in @Puuuudding 's example in line 18, the warn was disappeared and the field value was correct.

**Comment by Puuuudding** [comment]
@tcatche Great, `getFieldsValue` seems to be a workaround for this issue.

Also the error object problem seems to be triggered at line 17 when I first initial the data object with an empty `getFieldDecorator` if I uncomment that line while using `getFieldsValue` trick.

**Comment by lhwu** [comment]
@tcatche do you know how to setFieldsVale?
```
const fname = 'data.detail';
const fieldValue =getFieldValueFix(this.props.form, fname) ;
// console is not [{}]
setFieldsValue({ [fname]: [{}] }, console.log(getFieldValueFix(this.props.form, fname)); 
```

**Comment by helloli** [comment]
遇到同样的问题，有进展了吗

**Comment by zombieJ** [comment]
`getFieldValue` 对应的是 `getFieldDecorator`，这里的 field 是 `data.a` 和 `data[b]` 而不是 `data`。
Form 内部会对遗失的 field 进行初始化，运行了 `getFieldValue('data')` 相当于初始化了 data 作为 field，才会出现这个警告。

如果需要取到上一层的 `data` 直接通过 `getFieldsValue().data` 拿：https://codesandbox.io/s/pyqr6nqzmm

**Comment by lcoder** [comment]
@zombieJ 谢谢，你的回答解决我的问题，棒
