### ISSUE TITLE
Locale(ko_KR): missing property

### ISSUE THREAD

**Issue by HsuanXyz** [ant-design/ant-design#11201]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
*

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/locale-provider/ko_KR.tsx#L16](https://github.com/ant-design/ant-design/blob/master/components/locale-provider/ko_KR.tsx#L16)

### Steps to reproduce
*

#### zh_CN

```diff
  Table: {
    filterTitle: '筛选',
    filterConfirm: '确定',
    filterReset: '重置',
    emptyText: '暂无数据',
+   selectAll: '全选当页',
+   selectInvert: '反选当页',
  }
```

### ko_KR

```diff
  Table: {
    filterTitle: '필터 메뉴',
    filterConfirm: '확인',
    filterReset: '초기화',
    emptyText: '데이터 없음',
-   selectAll: ...,
-   selectInvert: ...,
  }
```

---

ref: https://github.com/NG-ZORRO/ng-zorro-antd/issues/1797

**Comment by afc163** [comment]
You can send us a PR~
