### ISSUE TITLE
npm run dev错误

### ISSUE THREAD

**Issue by chishichao** [ant-design/ant-design#1120]
C:\ant>npm run dev

> antd-demo@1.0.0 dev C:\ant
> dora -p 8001 --plugins atool-build,proxy,hmr

▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! antd-demo@1.0.0 dev: `dora -p 8001 --plugins atool-build,proxy,hmr`
npm ERR! Exit status 3221225501
npm ERR!
npm ERR! Failed at the antd-demo@1.0.0 dev script 'dora -p 8001 --plugins atool-
build,proxy,hmr'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd-demo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     dora -p 8001 --plugins atool-build,proxy,hmr
npm ERR! You can get their info via:
npm ERR!     npm owner ls antd-demo
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\ant\npm-debug.log

log的错误信息如下：
14 verbose stack Error: antd-demo@1.0.0 dev: `dora -p 8001 --plugins atool-build,proxy,hmr`
14 verbose stack Exit status 3221225501
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

**Comment by yiminghe** [comment]
不支持 windows
