### ISSUE TITLE
animate active run after end 

### ISSUE THREAD

**Issue by wangtao0101** [ant-design/ant-design#11216]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
chrome 67

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
It is hard to reproduce, i have not found a right way.

### What is expected?
The menu work right after init.

### What is actually happening?
Sometimes the menu can't shrink and expand when click the arrow.

The bug is in the file in [css-animation](https://github.com/yiminghe/css-animation/blob/master/src/index.js#L104)
```
if (active) {
    setTimeout(active, 0);
}
```
The timer should be clear in node.rcEndListener when the animation is finished before run active()

**Comment by afc163** [comment]
We don't know how to resolve it if you can reproduce it.

**Comment by wangtao0101** [comment]
@yiminghe @afc163 I have location the bug very clearly. You just think whether the case will appear or not.
The bug is in the file in [css-animation](https://github.com/yiminghe/css-animation/blob/master/src/index.js#L104)
```
if (active) {
    setTimeout(active, 0); // this timer maybe run after node.rcEndListener
}
```
Extremely, the timer run after node.rcEndListener, so the active fucntion will run after end fucntion  in  [openAnimation](https://github.com/ant-design/ant-design/blob/master/components/_util/openAnimation.tsx#L23)
```
active() {
  if (requestAnimationFrameId) {
    raf.cancel(requestAnimationFrameId);
  }
  requestAnimationFrameId = raf(() => {
    node.style.height = `${show ? height : 0}px`;
    node.style.opacity = show ? '1' : '0';
  });
},
end() {
  if (requestAnimationFrameId) {
    cancelRequestAnimationFrame(requestAnimationFrameId);
  }
  node.style.height = '';
  node.style.opacity = '';
  done();
},
```
Above active function will leave a style height on dom. Sometimes, it cause bug。
The height original should be clear in function end, but it not.

**Comment by afc163** [comment]
https://github.com/yiminghe/css-animation/commit/d9218e8e4870d404668ba0460f3fff032168597b

It is for firefox compatibility, I need to check if removing it will affect firefox now.
