### ISSUE TITLE
在Modal中使用百度地图，报错Error: A cross-origin error was thrown

### ISSUE THREAD

**Issue by songming43** [ant-design/ant-design#11210]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
chrome

### Reproduction link
[http://2x.ant.design/components/modal-cn/](http://2x.ant.design/components/modal-cn/)

### Steps to reproduce
1. 在入口文件index.html中引入百度地图
  <script type="text/javascript"  src="http://api.map.baidu.com/api?v=2.0&ak=eBGR7XzaPhB5UbYARl3E7ksdkMdgrCw7"></script>
2. 调用百度地图    
 componentDidMount = () => {
        // var BMap = window.BMap//取出window中的BMap对象
        var map = new BMap.Map("mapContainer"); // 创建Map实例
        map.centerAndZoom(new BMap.Point(116.404, 39.915), 11); // 初始化地图,设置中心点坐标和地图级别
        map.addControl(new BMap.MapTypeControl()); //添加地图类型控件
        map.setCurrentCity("北京"); // 设置地图显示的城市 此项是必须设置的
        map.enableScrollWheelZoom(true); //开启鼠标滚轮缩放
    }
3. 绑定id
 <Modal>
    <div id="mapContainer" style={{ width: 100, height: 100 }} ></div>
</Modal>   

### What is expected?
在Modal中使用百度地图组件

### What is actually happening?
在Modal中使用地图，报错：‘Error: A cross-origin error was thrown. React doesn't have access to the actual error object in development.

---
去过去掉Modal  直接写 <div id="mapContainer" style={{ width: 100, height: 100 }} ></div>  则没有问题

**Comment by biuge** [comment]
我也遇到了同样的问题  请问找到原因了吗

**Comment by blockmood** [comment]
我也遇到了，目前还没解决

**Comment by gaohan1994** [comment]
<Modal {...props} getContainer={false}>
      your map
</Modal>

**Comment by xian88888888** [comment]
> 我也遇到了，目前还没解决
用一个定时器包住就行了

**Comment by xian88888888** [comment]
> 我也遇到了同样的问题 请问找到原因了吗

用一个定时器包住就行了
