### ISSUE TITLE
Table Scrolling in Firefox doesn't work well

### ISSUE THREAD

**Issue by bhargaviswami12** [ant-design/ant-design#11214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
Firefox 61.0 on Mac, npm: '4.2.0', react @ 15.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pkjy70z0m7)

### Steps to reproduce
When the table is scrolled horizontally and vertically, the scrolling is not even. There is a weird behaviour. This happens in Firefox but not in chrome.

### What is expected?
The scrolling should be even and equal.

### What is actually happening?
The scrolling of table in both horizontal and vertical is not even. I have some rows and columns that are fixed. So when I try to scroll, the fixed rows scrolling is falling a few pixels behind the other rows scrolling. (You will understand when you see the sample code. If still you dont, then the additional link I have provided in the comments sections will definitely help)
In the case of the horizontal scrolling (Column scrolling), the columns seem to have some kind of a moving effect which is not how it is supposed to be .

---
The same issue has been raised in github for blueprint - https://github.com/palantir/blueprint/issues/1712 
My project created columns and rows on an adhoc basis . The column and the row count changes time to time. The scrolling works fine in Chrome , but breaks in firefox.

**Comment by afc163** [comment]
https://codesandbox.io/s/p7r714nrv0

width is too small for cell content.
