### ISSUE TITLE
Disable feature for card tabs

### ISSUE THREAD

**Issue by hemanthvrm** [ant-design/ant-design#11212]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tabs feature has disabled option whereas card tabs don't have any.

##### Right now tablist accepting only Array<{key: string, tab: ReactNode}> 

```
const tabListNoTitle = [{
  key: 'article',
  tab: 'article',
 disabled : true
}, {
  key: 'app',
  tab: 'app',
disabled : false
}, {
  key: 'project',
  tab: 'project',
 disabled : false
}]
```

**Comment by vadymhimself** [comment]
@hemanthvrm i believe there has to be an option to add a tooltip or other user message to display the reason for disabling the tab. Can you kindly advise how to accomplish this?

**Comment by hemanthvrm** [comment]
@vadymhimself 

firstly i requested for tab disabling feature, 
Just now verified that card is taking tabs component as prop, so in new version it is solved.


If you want tooltip on why the tab is disabled then you have to write your logic since it is not a generic usecase which will be helpful for everyone.

Solution:
Label prop accepts react node , so you can include your tooltip component here.
