### ISSUE TITLE
Tooltip overflow

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#11217]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
WIN10 - Chome67 - React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r5yq6nx4yn)

### Steps to reproduce
Hover element with tooltip

### What is expected?
Show right

### What is actually happening?
Tooltip overflow

![_20180710113149](https://user-images.githubusercontent.com/1730277/42487737-e37d62d0-8434-11e8-8e43-1b009cc4fcef.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/xr2l87z41q
