### ISSUE TITLE
Table Pagination: add alignment options ('left' | 'center' | 'right')

### ISSUE THREAD

**Issue by trofivan** [ant-design/ant-design#11213]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allows to choose horizontal alignment for the pagination blocks in the table.

### What does the proposed API look like?
```
<Table pagination={{ alignment: 'left' | 'center' | 'right' }} />
```
or it:
```
<Table pagination={{ alignmentTop: 'left' | 'center' | 'right', alignmentBottom: 'left' | 'center' | 'right'  }} />
```
or modify prop `position`:
```
<Table pagination={{ position: 'top left' | 'top center' | 'top right' | 'bottom left' | 'bottom center' | 'bottom right' | 'both left' | 'both center' | 'both right' }} />
```
or add Less variables for modify css.

**Comment by afc163** [comment]
PR 没关哦~

**Comment by yarbrough56** [comment]
Is this feature provided already or will it be provided in future?
I think bottom-center is a common use case for me. For now, the only way I can do it is to hack antd css style. 
Is there any api or other ways to solve this?

**Comment by mikeaustin** [comment]
> Is this feature provided already or will it be provided in future?
> I think bottom-center is a common use case for me. For now, the only way I can do it is to hack antd css style.
> Is there any api or other ways to solve this?

I thought this would be a basic feature? The way I was going to do it is provide a separate <Pagination /> component and disable the table pagination.
