### ISSUE TITLE
Layout.Sider doesn't support responsive layout with react >= 16.

### ISSUE THREAD

**Issue by elrasco** [ant-design/ant-design#11211]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.5

### Environment
chrome, linux, react 16.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ooj6q9okjq)

### Steps to reproduce
Shrink the layout

### What is expected?
The whole sider should collapse.

### What is actually happening?
Only the menu collapse.

---
It works with react 15.6.2

**Comment by yesmeck** [comment]
It's a bug, you can pass `collapsedWidth` as a number before we release the fix.
