### ISSUE TITLE
dropdown组件在chrome全屏模式下，失效

### ISSUE THREAD

**Issue by The-End-Hero** [ant-design/ant-design#11233]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
macos10.13.4 chrome67 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kkxykmojx3)

### Steps to reproduce
1.dropdown组件
2.全屏
3.功能失效

猜测原因为chrome在全屏下，自动给body第一个元素添加:-webkit-full-screen-ancestor:not(iframe) {
    z-index: auto !important;
    position: static !important;
    opacity: 1 !important;
    transform: none !important;
    filter: none !important;
    perspective: none !important;
    transform-style: flat !important;
    will-change: auto !important;
    -webkit-mask: none !important;
    transition: none !important;
}
dropdown等一系列组件挂在在body下导致。

### What is expected?
期望结果与浏览器非全屏模式下行为一致

### What is actually happening?
实际结果是在全屏模式下  行为失效

---
业务场景为web业务系统的全屏 功能演示

**Comment by yesmeck** [comment]
It's a known issue, see https://github.com/ant-design/ant-design/issues/7815
