### ISSUE TITLE
table组件没有了参考示例

### ISSUE THREAD

**Issue by alexlili** [ant-design/ant-design#11231]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
正式环境，3.6.6

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
昨天还能看到table组件示例，今天只有一个了

### What is expected?
还原

### What is actually happening?
还不知道

**Comment by dengfuping** [comment]
@alexlili Fixed.
