### ISSUE TITLE
Using message inside Component render method throws warning

### ISSUE THREAD

**Issue by amit-shopback** [ant-design/ant-design#11238]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
macOS high sierra (10.13.4)

### Reproduction link
[https://codepen.io/amit-shopback/pen/EpaVJe](https://codepen.io/amit-shopback/pen/EpaVJe)

### Steps to reproduce
Just start the application and open the console and you should see the react warning.

### What is expected?
No warning.

### What is actually happening?
Open the console and you should see the following warning :-
"Warning: _renderNewRootComponent(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate. Check the render method of Test."

**Comment by yesmeck** [comment]
`message` is not supposed to be called in `render`, you should not call function hash side effects in `render`.

**Comment by mhrvatin** [comment]
@yesmeck Would you mind explaining how `message` is supposed to be used? I'm quite new to react and I can't really figure out exactly how to use it.
