### ISSUE TITLE
npm run build css Compile error

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#11239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
chrome 

### Reproduction link
[http://www.dasuandata.com/point_b/#/point](http://www.dasuandata.com/point_b/#/point)

### Steps to reproduce
npm run build ，if css  have border:1px solid #1890ff8c  ，so packaging css code is border:8c solid #1890ff8c 

### What is expected?
border:1px solid #1890ff8c 

### What is actually happening?
border:8c solid #1890ff8c

**Comment by SynChron1zed** [comment]
![image](https://user-images.githubusercontent.com/18717051/42557838-24c3712e-8522-11e8-8a98-6f33b0b78859.png)

**Comment by SynChron1zed** [comment]
update border:1px solid #1890ff 

so

![image](https://user-images.githubusercontent.com/18717051/42557920-53b5f1f0-8522-11e8-9fd3-2037c2542432.png)

**Comment by afc163** [comment]
I don't think this problem is related to antd or you can prove it by providing a reproducible repository. Then I will reopen it.
