### ISSUE TITLE
Demos in table components doc page  is not shown

### ISSUE THREAD

**Issue by cjmling** [ant-design/ant-design#11230]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
Windows 10, Chrome 67.0

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
Visit this page  https://ant.design/components/table/ 

### What is expected?
Should see many other demo

### What is actually happening?
Only 1 demo (Editable Cells) is shown

---
I am sure there were many other demo before but I only see 1 today

**Comment by OwenMaschal** [comment]
Also having this issue

**Comment by ybning** [comment]
https://ant.design/components/table-cn/
![11](https://user-images.githubusercontent.com/3725612/42546430-f77d82fe-84ef-11e8-9fc1-6df00495c7be.png)
me too！

**Comment by dengfuping** [comment]
Fixed ~.
