### ISSUE TITLE
求教怎么更具一组父子结构的json数组去动态的生成menu?

### ISSUE THREAD

**Issue by pangbi** [ant-design/ant-design#1124]
数组试例var data = [{key: 'sub1', value: '导航一', children: [{key: '2', value: '选项一'}, {key: '3', value: '选项二'}]},
        {key: 'sub2', value: '导航二', children: [{key: '3', value: '选项一'}, {key: '4', value: '选项二'}]}
    ]

**Comment by benjycui** [comment]
嵌套循环或者递归，see：https://github.com/ant-design/ant-design/pull/1093/files#diff-355099ef45245d70c2e978bdebeae706R38

另外麻烦看下：http://doc.zengrong.net/smart-questions/cn.html

**Comment by wangking873** [comment]
function renderMenu(item) {
    if (item.items && item.items.length > 0) {
        return (<SubMenu key={item.key} title={item.title}>
            {
                item.items.map(renderMenu)
            }
        </SubMenu>
        )
    }
    else {
        return (<Menu.Item key={item.key}>{item.title}</Menu.Item>)
    }
}
