### ISSUE TITLE
CSS styles don't import correctly with server side rendering

### ISSUE THREAD

**Issue by hakankaraduman** [ant-design/ant-design#11244]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
Windows 10, Chrome Latest, Node 8.11.2, npm 6.0.0

### Reproduction link
[https://github.com/hakankaraduman/antdServerSideBug](https://github.com/hakankaraduman/antdServerSideBug)

### Steps to reproduce
Clone the git repo, checkout to ssr branch. execute script 'yarn ssr', open the localhost and see that other css works okay but the antd button is not okay.

### What is expected?
To work as expected just as when loaded from javascript

### What is actually happening?
Styles don't apply when server side renders

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5171
