### ISSUE TITLE
onCheck's  second param of  'node' get a wrong result

### ISSUE THREAD

**Issue by fenghuizhang** [ant-design/ant-design#11257]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
chrome 60, linux

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2jvlzlyovn)

### Steps to reproduce
https://codesandbox.io/s/2jvlzlyovn
line 15,  node's checed is wrong

### What is expected?
function(checkedKeys, e:{checked: bool, checkedNodes, node, event})
the second param <node>'s key <checked> should be the right result but it give me a opposite result
for node.props.checked

### What is actually happening?
the second param <node>'s  key  <checked>   give me a opposite result

---
function(checkedKeys, e:{checked: bool, checkedNodes, node, event})

**Comment by zombieJ** [comment]
onCheck second params of node returns the node instance and its props is also the current status.
It's not a bug.

**Comment by fenghuizhang** [comment]
@zombieJ  Do you mean "node.props.checked" is the last state?

**Comment by zombieJ** [comment]
Again, params of node is the node *'instance'* which is not a *'snapshot'*. It's for the current props. Consider follow code, what's the last checked state it will be?
```jsx
state = {
  checkedKeys: [],
};
onCheck = (checkedKeys) => {
  // do nothing
}

render () {
  return (
    <Tree checkedKeys={this.state.checkedKeys} onCheck={this.onCheck}>
      ...
    </Tree>
  );
}
```

If you want to know the checked status of it tend to be. Check the params of `checked` instead.
