### ISSUE TITLE
On Firefox, Dropdown overlay Menu does not work when Dropdown is wrapped inside its triggering Button

### ISSUE THREAD

**Issue by msedatgungor** [ant-design/ant-design#11251]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.0

### Environment
Firefox 61 on macOS (High Sierra)

### Reproduction link
[https://codepen.io/msedatgungor/pen/xJbWOP](https://codepen.io/msedatgungor/pen/xJbWOP)

### Steps to reproduce
1. Open Dropdown by clicking the button.
1. Try hovering or click any of the MenuItems of the opened Menu.

### What is expected?
MenuItem to be hovered or clicked.

### What is actually happening?
Menu is displayed but does not trigger any hover nor click events. Also, if the opened Dropdown Menu covers any UI item (e.g another button), it will hover or click that button.

---
I wanted the Dropdown to stay fixed at its position when I scrolled the page. That's why I wrapped Dropdown inside of the Button; that way it didn't scroll as I scroll the page. It works as expected on Chrome 67 though.

**Comment by afc163** [comment]
You can't insert dom node to a button node.

https://stackoverflow.com/questions/15885444/why-cant-a-button-element-contain-a-div

**Comment by msedatgungor** [comment]
But it works as expected on Chrome or Safari. If that is against a rule, then how Google or Safari can handle this situation properly?
