### ISSUE TITLE
pagination's options need to be splitted

### ISSUE THREAD

**Issue by ruoqianfengshao** [ant-design/ant-design#11253]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
it allows custom options's position through css, such as selection and quick jumper will be at Head and tail

### What does the proposed API look like?
no api requested just use more `li` elements to present options than one `ant-pagination-options`

**Comment by chenshuai2144** [comment]
Using css is not the recommended method because the dom structure may change

**Comment by afc163** [comment]
No plan now.
