### ISSUE TITLE
Tree 组件应该支持 TreeNode 封装在其他组件中

### ISSUE THREAD

**Issue by hh54188** [ant-design/ant-design#11254]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前不支持动态的，递归的创建叶子节点，遇到了如 https://github.com/ant-design/ant-design/issues/4688 这个issue下同样的问题

### What does the proposed API look like?
```
const Leaf = ({ id }) => <Tree.TreeNode title={doing something dynamic here} />
```

**Comment by yesmeck** [comment]
已知问题，暂时没有好的解法，见 #4853

**Comment by hoalongntc** [comment]
I have found a solution for this: extend `TreeNode` with custom render logic then you're good to go.

```tsx
class TreeNode extends Tree.TreeNode {
  constructor(props) {
    super(props);
    const originalRender = this.render;

    this.render = () => {
      return (
        <Row type='flex'>
          <Col style={{ flex: 1 }}> {originalRender.call(this)}</Col>
          <Col>
            <Button icon='delete' type='danger' size='small' />
          </Col>
        </Row>
      );
    };
  }
}
```

**Comment by lbottoni** [comment]
@hoalongntc how to import Tree and TreeNode, if i try to extend for override onDragEnter and onDrop method i iva always this error

TS2507: Type 'ComponentType<AntTreeNodeProps>' is not a constructor function type.
