### ISSUE TITLE
Timeline.Item with Tooltip on dot Icon

### ISSUE THREAD

**Issue by theCmaker** [ant-design/ant-design#11250]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
Windows 10, Chrome 67 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p56w9n1jqq)

### Steps to reproduce
Hover the timeline step icon.

### What is expected?
A tooltip should appear.

### What is actually happening?
The tooltip is only triggered when you hover the left border of the icon's box. It is difficult to catch it.

---
This may be due to specific margin/padding rules set on the timeline dots.

**Comment by afc163** [comment]
working on it
