### ISSUE TITLE
字体页面中错别字

### ISSUE THREAD

**Issue by Seki13** [ant-design/ant-design#11255]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
无

### Reproduction link
[https://antv.alipay.com/zh-cn/vis/design/font.html](https://antv.alipay.com/zh-cn/vis/design/font.html)

### Steps to reproduce
无

### What is expected?
字体>字体颜色部分 黑色部分title是否应为“深色背景下”

### What is actually happening?
浅色背景下

**Comment by chenshuai2144** [comment]
有兴趣搞个 pr 吗？

**Comment by yesmeck** [comment]
可以直接给 https://github.com/antvis/site PR。
