### ISSUE TITLE
MapPropsToFields do not perform consistently in 2.x and 3.x, and 3.x appears to overwrite rather than merge using the return results of mapPropsToFields

### ISSUE THREAD

**Issue by Amorites** [ant-design/ant-design#11266]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
react16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qv38zz213w)

### Steps to reproduce
input something in field2

### What is expected?
Like antd2   react15: https://codesandbox.io/s/pk6w206qjm

We can modify field2 

### What is actually happening?
Field2 is not modified

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9816
