### ISSUE TITLE
幽灵按钮背景色应该透明.

### ISSUE THREAD

**Issue by TossShinHwa** [ant-design/ant-design#1126]
ant-design 中的 ghost button 示例:

![image](https://cloud.githubusercontent.com/assets/3007674/13520071/2c9a1c0e-e218-11e5-98a5-10b7ba08b9d9.png)

标准定义的 ghost button 示例:

![image](https://cloud.githubusercontent.com/assets/3007674/13520123/97b8dcb4-e218-11e5-930f-3035c31aa752.png)

**Comment by afc163** [comment]
Nice catch!

正在协调设计师更新。
