### ISSUE TITLE
Tabs 中存在多个 input  时，使用 tab 键能切换焦点但 TabPane 却无法显示

### ISSUE THREAD

**Issue by HsuanXyz** [ant-design/ant-design#11261]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
Google Chrome 67.0.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7w8xn1o81x)

### Steps to reproduce
1. 点击 Tab1 Tab2 Tab3
2. 回到 Tab1 或 Tab2
3. 使 input 聚焦，按下 tab 键切换焦点

### What is expected?
在切换焦点时同时切换 TabPane，或者阻止 tab 键。 

### What is actually happening?
input 被切换焦点，TabPane 却无法显示

---
ref: https://github.com/NG-ZORRO/ng-zorro-antd/issues/1821

**Comment by zombieJ** [comment]
fixed in `rc-tabs@9.3.1`. Thanks for feed back.

**Comment by afc163** [comment]
https://github.com/react-component/tabs/commit/1194be5232ce79d0e66af102519e033bcadccc9f introduced #11621 and I just change another way above to resolve it.
