### ISSUE TITLE
Incorrect usage of export default in antd/lib/[xxx]/index.d.ts (except radio and time-picker)

### ISSUE THREAD

**Issue by buhichan** [ant-design/ant-design#11263]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
typescript 2.9, node 10

### Reproduction link
[https://github.com/buhichan/tmp](https://github.com/buhichan/tmp)

### Steps to reproduce
```
//tsx
import Component from "antd/lib/xxxxxxx" 
React.createElement(Component, ...)
//React complains about passing undefined as component type
```

### What is expected?
As in https://github.com/Microsoft/TypeScript/issues/13017 explained, 

when use 
```
import Affix from "antd/lib/affix; 
React.createElement(Affix, ...
```

 in typescript, if the target is es5, the emitted code is always

```
var Affix = require("antd/lib/affix")
React.createElement(Affix.default, ...
```

Now "antd/lib/affix/index.d.ts" says export default Affix, so the right way to use it is 
```
import Affix from "antd/lib/affix"
```
therefore require("antd/lib/affix") should have the shape {"default":Affix}

### What is actually happening?
But "antd/lib/affix/index.js" 's exports are actually
```
export['default'] = Affix
module.exports = exports['default']
```
So "require("antd/lib/affix").default" is undefined. 
This is not the shape described in "antd/lib/affix/index.d.ts".

Only 'radio' and 'time-picker' are correctly typed and do not have the above issue, because in their index.js, the exports are like

```
_radio2['default'] = Radio
...
export['default'] = _radio2['default'] 
//no stupid module.exports =exports['default']
//can someone explain why is this different?
```

If this issue is not a real issue but a wanted behavior, maybe it will be better to keep consistensy across "antd/lib/xxx/index.d.ts"s, 对不对?

---
Use allowSyntheticDefaultImports does not help.

**Comment by buhichan** [comment]
Using `antd/es/xxx` can cause a totally different set of problems.


For example, do I really have to depend on babel to transpile `antd/es`'s es6 js codes when i already have tsc? (tsc does not do js transpile even if --allowJS option is on)


It's much more convenient to use only es5 codes from node_modules, do you guys have any plan to fix "antd/lib/xxx/index.d.ts"?

**Comment by chenshuai2144** [comment]
Welcome pr.
We do not recommend this use

**Comment by buhichan** [comment]
你的意思是不推荐在ts里import xxx from "antd/lib/xxx"? 那推荐用法是什么, es下面是es6代码啊, tsc不支持js转译的, 遇到js它直接看都不看一眼就emit了. 你干脆说不推荐tsc推荐babel好了.
还是说推荐直接 import {xxx,yyy} from "antd", 然后用插件来做tree-shaking?

**Comment by chenshuai2144** [comment]
import { Table} from 'antd'

**Comment by buhichan** [comment]
以后的版本有计划改正这个.d.ts 或者 export default吗 大佬

**Comment by buhichan** [comment]
Should'n't close this.
It's related to https://github.com/babel/babel/issues/2212
It's actually because antd-tools depends on babel-plugin-add-module-exports@0.2,
Should turn on addDefaultProperty option of babel-plugin-add-module-exports@0.3,
I can try to make it work

**Comment by buhichan** [comment]
I'll close this since it's not an issue in this repo itself.
