### ISSUE TITLE
Select doesn't display active option after search

### ISSUE THREAD

**Issue by fantua** [ant-design/ant-design#11268]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4r9mmn4937)

### Steps to reproduce
1. Open Select
2. Type "50"
3. Select option with label "50"
4. Open Select
5. Option with label "50" isn't active
6. Lose focus
7. Open Select
8. Option is active

### What is expected?
1. Open Select
2. Type "50"
3. Select option with label "50"
4. Open Select
5. Option with label "50" is active

### What is actually happening?
Select doesn't display active option after search

**Comment by zombieJ** [comment]
Could you provide a gif for this since I can't reproduce

**Comment by fantua** [comment]
@zombieJ, sure:

![jul-20-2018 18-22-37](https://user-images.githubusercontent.com/7703761/43010762-fc0c7cd8-8c49-11e8-80cf-0e5405705ee3.gif)

**Comment by zombieJ** [comment]
Got it. You mean the scroll bar should scroll to the checked value. Let me check. Thanks
