### ISSUE TITLE
Change order of arrow buttons in Transfer element - 1st: to right 2nd: to left

### ISSUE THREAD

**Issue by weidenhaus** [ant-design/ant-design#11269]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In all other frameworks and UIs I ever saw (Apple, SAP,  etc.) the button to move the element from left to right is first, then the button to move a element from right to left below

### What does the proposed API look like?
n/a

**Comment by afc163** [comment]
> In all other frameworks and UIs I ever saw (Apple, SAP, etc.)

Could you provide url of this demos?

**Comment by weidenhaus** [comment]
Sure, here you go, thank you for considering.

[Microsoft Office](https://support.office.com/en-us/article/create-a-query-form-or-report-in-access-2016-04eb597f-cb77-47be-83ed-1b8325b34cde)
[SAP](http://www.whypad.com/posts/sap-cost-centers-master-data/156/)
[Salesforce](https://help.salesforce.com/articleView?id=customviews.htm&type=5)
[Microsoft](http://www.dbxtra.com/documentation/topic/report-designer/report/report_wizard.htm)
[Oracle](https://docs.oracle.com/cd/E48434_01/fusionapps.1118/e49548/F1071036AN2856A.htm)
[Drupal](https://www.drupal.org/taxonomy/term/35954)
[Open Office](https://wiki.openoffice.org/wiki/Documentation/OOo3_User_Guides/Getting_Started/Creating_database_tables)
[Maprecord](https://www.maprecord.com/CM_help/CM_fieldselection.html)

**Comment by y-takey** [comment]
+1
