### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by zpforcoding** [ant-design/ant-design#11260]
你好，我本地下载了fonts，可以使用，因为公司所用是内网，但是还是会去请求alicdn，浏览器一直请求不了的话会请求两次，用户等待时间过长，请问有什么解决方法吗？本地开发用的scss，用ant design 做的主题。求指教

**Comment by picodoth** [comment]
@zpforcoding 请参看 https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont#local-hosted-iconfont
