### ISSUE TITLE
Select: Render selected options differently?

### ISSUE THREAD

**Issue by Tsury** [ant-design/ant-design#11272]
I render all of my options as [IMG][TEXT] and would like to render the selected values without the [TEXT] part to make it more compact, I want to show only the image.

How can I go about achieving that?

**Comment by afc163** [comment]
check: `optionLabelProp`

**Comment by tangticco** [comment]
@afc163 how to render the style of selected options differently? Say a group of selected options will be rendered like a red tag and others will be like a green tag?
