### ISSUE TITLE
form table 结合使用例子

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#1127]
场景： 上面一个搜索表单，下面一个 table ， 联动

单独放到 http://antd.alipay.net/docs/pattern/table/example

需要结合 react-router / form/ table

```
<SearchConditionForm />
<SearchTable />
```

注意：将搜索条件放到 url 维护

```
#/list?x=search1&y=search2
```

放到  https://github.com/ant-design/antd-init/tree/master/examples

**Comment by afc163** [comment]
例子略复杂，放到 https://github.com/ant-design/antd-init/tree/master/examples 这里来好了。antd 文档里给个链接。

**Comment by yiminghe** [comment]
还是新建以前的 examples 库吧，发到 gh-pages 吧，需要能直接看到 demo

**Comment by jsers** [comment]
examples 的地址确定了吗？

**Comment by afc163** [comment]
https://github.com/ant-design/examples 占位先。

**Comment by afc163** [comment]
会做在业务模式库中。
