### ISSUE TITLE
Affix组件放到Layout组件中后不生效

### ISSUE THREAD

**Issue by lvze1992** [ant-design/ant-design#11276]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
chrome 67.0.3396.99

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ly290zwrzl)

### Steps to reproduce
请打开重现链接   无法在layout的组件内使用affix

### What is expected?
在layout的组件内使用affix

### What is actually happening?
无法在layout的组件内使用affix

**Comment by afc163** [comment]
```diff
-       <Affix offsetTop={100} target={() => document.getElementById("xxx")}>
+       <Affix offsetTop={100}>
          <Button type="primary">无效</Button>
        </Affix>
```

`target` should be a scrollable area.
