### ISSUE TITLE
table组件没有预留滚动条宽度

### ISSUE THREAD

**Issue by wakeupSu** [ant-design/ant-design#11289]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
Google Chrome 67.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xl26pjrvvo)

### Steps to reproduce
mac在设置滚动条始终显示，或者使用window系统

### What is expected?
在table设定的宽度后，始终显示滚动条时，table的宽度为设定的宽度加上滚动条的宽度

### What is actually happening?
在table设定的宽度后，始终显示滚动条时，table的宽度为设定宽度，滚动条的宽度占用了table设定的宽度

**Comment by yesmeck** [comment]
#4637
