### ISSUE TITLE
为什么ant团队没有做一些 panel , list, thumb 等这样的组件呢

### ISSUE THREAD

**Issue by Yunlong2cn** [ant-design/ant-design#1128]
请问小伙伴们，是没有计划呢，还是考虑了没来得及做呢？如果无计划的话，我们就可以大胆的自己定制了，如果是还没来得及做的话，有没有具体的方向呢？

主要考虑的是自己是否有必要去做一些这样的组件，一旦ant团队发布了这类组件，我们一定会转移到这边来的，就意味着我们自己定义的组件不再适用

**Comment by afc163** [comment]
panel、thumb 可能和 Card 组件类似。

可以关注下我们的计划。https://github.com/ant-design/ant-design/issues/978

list 组件的样式形态较多，目前难以沉淀高复用的组件，可按照业务线需求自行定制实现。
