### ISSUE TITLE
rc-form outdated?

### ISSUE THREAD

**Issue by viztor** [ant-design/ant-design#11283]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
in the current build, the rc-form is at @2.1, which is released half a year ago. the latest version seems to be @2.2

### What does the proposed API look like?
there is no proposed api

**Comment by viztor** [comment]
at the same time, in the official document of rc-form antd form referenced to ——"更多示例参考 rc-form。"
the api of this.props.form include getFieldProps. while it wasn't documented in antd form.d.js.

**Comment by afc163** [comment]
Nope, check https://david-dm.org/ant-design/ant-design
