### ISSUE TITLE
You should not use <Link> outside a <Router> after update to 3.7.0

### ISSUE THREAD

**Issue by saostad** [ant-design/ant-design#11294]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
Browser

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
update from 3.6.6 to 3.7.0

### What is expected?
work without error

### What is actually happening?
Error: You should not use <Link> outside a <Router>
and Crash the app

---
I am using create-react-app-typescript and this is my packages versions: 

"react": "^16.4.1",
"react-dom": "^16.4.1",
"react-router-dom": "^4.3.1"
"antd": "^3.7.0",
"typescript": "^2.9.2"

**Comment by yesmeck** [comment]
Duplicate of #1192

**Comment by afc163** [comment]
#1192 ?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11292

**Comment by picodoth** [comment]
Trying to come up a fix as soon as possible.

**Comment by picodoth** [comment]
A fix will be made soon in https://github.com/react-component/menu/pull/175

**Comment by JonDum** [comment]
Man, I thought I was going nuts with this one!! Spent a while reproducing in CodeSandbox... Turns out it doesn't do it with a normal `<Menu>`, only `<Menu mode='horizontal'>` for me!

Repro: 

[![Edit rrmz144j9m](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rrmz144j9m)

**Comment by picodoth** [comment]
should be fixed via 5098c55a4e9a2f454db2d9c843dd954c96b5d2eb
