### ISSUE TITLE
Table: split merged cells

### ISSUE THREAD

**Issue by XinyuYang** [ant-design/ant-design#11290]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to have both sorter and merged cells at the same time. This won't work without some ways of un-merging or splitting. For example if there are 1-2-3-4 merged, 5-6 merged and 7, when the user sorts at another column and changes the original order into 1 2 5 6 3 4 7. Instead of having the visualization of 1-2, 5-6, 3-4, 7 the big merged cell that once belonged to 1-2-3-4 goes with 1, and takes in 1-2-5-6 and makes them seem like a new large merge block, which they should not be.

### What does the proposed API look like?
I'm not sure how exactly to do it without modifying the original way of merging cells. But it would be helpful to have cells of the same contents merged.

**Comment by yesmeck** [comment]
I don't quite understand you, could you demonstrate your issue on codesandbox.io?

**Comment by XinyuYang** [comment]
https://codesandbox.io/s/k2oqlw5z9o
It's like this, so if you clicked in and sorted by address, the format goes wrong.

**Comment by yesmeck** [comment]
Your link is not working.

**Comment by XinyuYang** [comment]
Sorry I just updated it, is it working now?

**Comment by yesmeck** [comment]
This is a usage issue, you need to sort the addresses by the name column.

**Comment by XinyuYang** [comment]
what if I want it to be sorted at addresses as well?

**Comment by yesmeck** [comment]
`address` 的 sorter 方法需要把 `name` 也考虑进去。
