### ISSUE TITLE
Link out of Router context error when placed inside Menu.Item 

### ISSUE THREAD

**Issue by apikiakos** [ant-design/ant-design#11292]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
React 16.4.1, OS X 10.13.4, Chrome 67.0.3396.99

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kk6vwwy653)

### Steps to reproduce
If placed inside Menu.Item, Link component from react-router-dom is considered out of Router context

### What is expected?
To be able to have links inside of menu item

### What is actually happening?
Before 3.7.0, Link was fine inside of Menu.Item

---
Sorry if my new issue is not state of the art, I am new to contributing

**Comment by KnoveZ** [comment]
import { BrowserRouter as Router } from "react-router-dom";

然后在Link 标签外包个Router  即可

**Comment by yesmeck** [comment]
https://github.com/react-component/menu/pull/172

**Comment by picodoth** [comment]
should be fixed via 5098c55a4e9a2f454db2d9c843dd954c96b5d2eb
