### ISSUE TITLE
Tree, TreeSelect

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1129]
rc-tree-select has 'treeLine' feature, but for antd this feature is not using. Is it possible to include this feature at antd too?

**Comment by warmhug** [comment]
It is present in antd, just not in document.
Try to set it.

**Comment by plandem** [comment]
nothing visually changed. Looks like i need extra styles for it. Can you add these styles into antd?

**Comment by warmhug** [comment]
It has no line style in antd. You need add your own style.

**Comment by plandem** [comment]
maybe instruction what exactly styles i must add?

**Comment by warmhug** [comment]
It may have a little difficulty. Reference here:
https://github.com/react-component/tree-select/blob/master/assets/tree.less
http://react-component.github.io/tree-select/examples/basic.html
![image](https://cloud.githubusercontent.com/assets/2011119/13591441/933fa34e-e523-11e5-8d0d-fafce8f07043.png)

**Comment by plandem** [comment]
i hoped for no debugging :)))
