### ISSUE TITLE
Can the select component add a suffix?

### ISSUE THREAD

**Issue by lucasleelz** [ant-design/ant-design#11305]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When some data is large, you can click to pop up a modal component.

### What does the proposed API look like?
The select component has a new suffix that can be clicked to display modal.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6866
