### ISSUE TITLE
Dropdown will shift a pixel when open

### ISSUE THREAD

**Issue by linkbay** [ant-design/ant-design#11306]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.4

### Environment
Chrome Version 67.0.3396.99 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/621m4wlw1k)

### Steps to reproduce
Create two dropdown with button in same row, one on the left, another on the right, make left width is not round up, for example '200.411px', you open the right dropdown, it will shift a pixel to left or right when show up.

### What is expected?
The small shift should not be occur.

### What is actually happening?
We found that when get the position value for the dropdown, chrome seems to round up during render, and make the dropdown shift.
We are able to solve this by modify \node_modules\dom-align\es\getRegion.js, round up the left offset.

---
Can you let us to have an option or just round up the offset on dom-align? so the dropdown shift will not occur.

**Comment by zombieJ** [comment]
Can't reproduce in my screen. Could you provide a gif ?

**Comment by linkbay** [comment]
![pixelshift](https://user-images.githubusercontent.com/40389606/43117416-4437e69e-8f3f-11e8-9cfb-ffbc8877b612.gif)

**Comment by linkbay** [comment]
Thanks for your reply that's the GIF

**Comment by zombieJ** [comment]
Thanks for your gif. I can see it now : )
But it seems affected by the browser UI render. I guess we may do nothing about it.

**Comment by ywtsang** [comment]
As mentioned by @linkbay at the description "We are able to solve this by modify \node_modules\dom-align\es\getRegion.js, round up the left offset.", can ant-design round up the left offset to avoid this browser UI render?

**Comment by zombieJ** [comment]
Hi @ywtsang ,
it's great to create PR to [dom-align](https://github.com/yiminghe/dom-align) I guess  : )
