### ISSUE TITLE
Receiving support? 

### ISSUE THREAD

**Issue by Francolpm** [ant-design/ant-design#1130]
Hi there! This isn't a issue but I didn't know where to ask!
Are you accepting donations or supports? Because ant-design it's a great open source project and may you get some extra support for it.
I don't trying to spam you, but I want to invite you to beerpay.io, a simple platform to monetize open source projects, like ant-design. 
I know that the open source is free, but it's okay if someone want to contribute in other way.

Thanks for this work man!

**Comment by afc163** [comment]
I will consider it if beerpay support [alipay.com](https://www.alipay.com/).
