### ISSUE TITLE
Can the new diectoryTree be unselected as the normal tree ?

### ISSUE THREAD

**Issue by fankxxd** [ant-design/ant-design#11302]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now the treeNode of the directoryTree  can not be cancelled once one is selected, only can select other one to change its status, it is unreasonable.

### What does the proposed API look like?
I hope it can be used like normal tree with select acitons.

**Comment by zombieJ** [comment]
You can control the selectedKeys for the purpose : https://codesandbox.io/s/w6n016kr5k
