### ISSUE TITLE
Infinite Animation of Menu

### ISSUE THREAD

**Issue by noscripter** [ant-design/ant-design#11308]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ovk75j40r9)

### Steps to reproduce
https://ovk75j40r9.codesandbox.io/

Change `param` to `undefined` would not trigger the problem.

### What is expected?
Collapse finish on click without any more animation.

### What is actually happening?
Infinite animation on click the menu to collapse the submenu.

---
The link provides enough information already.

**Comment by noscripter** [comment]
Update: this is related to `react-css-module`

**Comment by noscripter** [comment]
any progress? @yutingzhao1991 @afc163

**Comment by picodoth** [comment]
this is a truly weird issue, personally not familiar with how animation works yet. might take some time..

**Comment by jljsj33** [comment]
重复 render 的问题...

**Comment by jljsj33** [comment]
transitionEnd 在重复时，是不是重复添加？

**Comment by jljsj33** [comment]
或改成 PureComponent

**Comment by picodoth** [comment]
@jljsj33 为啥加了 cssModules decorator 会导致重复 render ？

**Comment by afc163** [comment]
It is more like a react-css-modules bug.

**Comment by noscripter** [comment]
Any progress with this issue?

**Comment by jljsj33** [comment]
> It is more like a react-css-modules bug.

Please use `PureComponent`.

```
@CSSModules(param)
class App extends PureComponent {
}
```

**Comment by zombieJ** [comment]
Looks like `react-css-modules` will [recv copy](https://github.com/gajus/react-css-modules/blob/master/src/linkClass.js#L23) sub component cause re-render makes `rc-animate` repeat check last [leave event](https://github.com/react-component/animate/blob/master/src/Animate.js#L161) and trigger leave animate.

It's not easy to fix this since it's a mixed issue.

For the quick fix, use PureComponent like @jljsj33  said.

**Comment by noscripter** [comment]
Thanks for your reply, I'd like to keep this issue as a reminder of this caveat in case anybody else run into it.

But for now, I'll close it.
