### ISSUE TITLE
Prop destroyOnClose prevents the closing animation of drawer

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design#11307]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
MacOS: Darwin kenny.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May 8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
Chrome: Version 67.0.3396.99 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/kennylbj-the-bashful/pen/PBNVYY?editors=0010](https://codepen.io/kennylbj-the-bashful/pen/PBNVYY?editors=0010)

### Steps to reproduce
1. Add destroyOnClose prop to Drawer
2. Close the Drawer

### What is expected?
Showing closing animation 

### What is actually happening?
Drawer close immediately without closing animation.

**Comment by jljsj33** [comment]
destroyOnClose 是 antd 里 @chenshuai2144 加的。。。

**Comment by yesmeck** [comment]
可能得在 rc-drawer 里实现才能有动画。

**Comment by jljsj33** [comment]
可能是 react 15.x 的问题。。我看看

**Comment by jljsj33** [comment]
这个真是 antd 里的问题。。。
https://github.com/ant-design/ant-design/blob/master/components/drawer/index.tsx#L111

return null 了，，，
我搞下？？ @chenshuai2144 ?

**Comment by chenshuai2144** [comment]
这个行为的错误在哪里？

**Comment by jljsj33** [comment]
关闭时直接删了，，没有把抽屉收回再删，，他的意思。。。

**Comment by amitpatil321** [comment]
I am facing the same issue, while closing drawer it closes immediately but in the above demo its working fine, Not sure what's wrong. I even tried using the same code as above. The only difference in the above code and my code is that my visibility flags are getting set from parent component using react context.

I tried adding/removing destroyOnClose flag but it doesn't make any difference

`<Drawer
                    className    = "channel-info"
                    title        = {<strong>About #{room.name}</strong> }
                    placement    = "right"
                    width        = "250"
                    closable     = {true}
                    maskClosable = {true}
                    visible      = {context.state.channelInfoVisible}
                    onClose      = {context.hideDrawer}
                    destroyOnClose
                >`

**Comment by amitpatil321** [comment]
Okay I found the cause, it was because I was loading drawer component conditionally like below 

` { showDrawer && <DrawerComponent }`

Maybe because of that all the events were not getting bind to it. Instead, I am now lazy loading this component and it's working fine now. 

BTW: Same happens with modal components close animation as well. Due to that only I was able to find the problem.

**Comment by laxarcuteria** [comment]
> I am now lazy loading this component and it's working fine now.

How are you doing this?  React.lazy?

**Comment by hitanshiMehta-Dev** [comment]
@amitpatil321 hey problem is still there, it would be helpful if you share the code.

**Comment by GeorgeFlorian** [comment]
I am also having issues with the closing animation.

When using conditional rendering for the drawer the closing animation does not work.

**Comment by emre-ozgun** [comment]
We're also facing this issue. Initially we've conditionally rendered all the modals in our app. We've removed conditional renders and close animations are now visible. However, all the effect handlers (useEffect) are being triggered since they're no longer conditionally rendered. Any workarounds ?

**Comment by morteza-gho** [comment]
Hi, we have the same issue in modals, when we conditionally rendered modals

**Comment by chathurabuddi** [comment]
> Hi, we have the same issue in modals, when we conditionally rendered modals

use the `destroyOnClose` prop in the Modal. then, extract the modal's content (child) into a new component and render that one conditionally.
