### ISSUE TITLE
Data entry components such as Input, DatePicker don't work as expected while combining with Drawer.

### ISSUE THREAD

**Issue by kennylbj** [ant-design/ant-design#11303]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
MacOS: Darwin kenny.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64  
Chrome: Version 67.0.3396.99 (Official Build) (64-bit)

### Reproduction link
[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce
Just look at the **edit item in drawer** example in official site 
Select and  DatePicker can not select values.
```js
<Drawer
   title='Create'
   visible={drawerVisible}
>
<Form layout="vertical">
    <Row gutter={16}>
          <Col span={12}>
            <Form.Item label="type">
              {getFieldDecorator('type', {
                rules: [{ required: true, message: 'Please select type' }],
              })(
                <Select placeholder="Please select type">
                  <Option value="xiao">Xiaoxiao Fu</Option>
                  <Option value="mao">Maomao Zhou</Option>
                </Select>
              )}
       </Form.Item>
     </Col>
  </Row>
</Drawer>
```

### What is expected?
The Select and DatePicker components are selectable

### What is actually happening?
Data entry components don't work as expected

**Comment by afc163** [comment]
same issue as #11304
