### ISSUE TITLE
使用Transfer组件时报错：invariant.js:42 Uncaught Error: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

### ISSUE THREAD

**Issue by luoluoluoluoluoluo** [ant-design/ant-design#11318]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
antd:3.6.6

### Environment
react 15.6.2

### Reproduction link
[http://code.linke.alipay.com/app_release/qualityprod/blob/app_monitor_refactor/antd/src/js/pages/oneData/pages/AppOSDataKeyEditor.jsx](http://code.linke.alipay.com/app_release/qualityprod/blob/app_monitor_refactor/antd/src/js/pages/oneData/pages/AppOSDataKeyEditor.jsx)

### Steps to reproduce
 <Transfer
                                dataSource={this.state.apps}
                                showSearch
                                listStyle={{
                                    width: 220,
                                    height: 300,
                                }}
                                operations={['to right', 'to left']}
                                targetKeys={this.state.targetKeys}
                                onChange={this.handleTranserChange}
                                render={item => {debugger;return item.key}}
                                footer={this.renderTranserFooter}
                            />

### What is expected?
解决该报错

### What is actually happening?
只有在引用Transfer组件时报该错误，其他情况下良好，应该不是重复引用React的问题，也没有涉及到refs

**Comment by luoluoluoluoluoluo** [comment]
riddle下是没有问题的 
https://riddle.alibaba-inc.com/riddles/c5ee7b27
是我的版本问题吗？
react 15.6.2 
antd 3.6.6

**Comment by chenshuai2144** [comment]
react 的版本原因吗？你试试升级一下 react 的版本

**Comment by cookHu** [comment]
我这边也出现类似的错误啦

错误内容： 
Element ref was specified as a string (input) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information

```javascript
"antd": "^3.10.0"
"react": "^16.2.0",
```
该组件在 ```codePen``` 中运行是正常
之前怀疑是版本不兼容原因 但是尝试升级版本未解决该问题
待反馈原因

**Comment by eidonjoe** [comment]
@cookHu 你好 问下这个问题解决了吗 能否提供下解决方案
