### ISSUE TITLE
Menu组件render出现异常

### ISSUE THREAD

**Issue by JbSun** [ant-design/ant-design#11313]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
mac chrome67.0.3396.99 dva1.0

### Reproduction link
[https://abird.alibaba-inc.com/](https://abird.alibaba-inc.com/)

### Steps to reproduce
加载Menu组件报错
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DOMWrap`.
其他组件无问题，使用antd的Menu报此错误

### What is expected?
可以正常使用

### What is actually happening?
页面崩溃

---
今天下午开始出现问题，是否是antd发布包出现异常

**Comment by yesmeck** [comment]
暂时回滚了相关的代码，重新安装下 node_modules 即可。
