### ISSUE TITLE
AutoComplete Value设置成非String报错。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#11317]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
windows10 chrome react 16.2.20

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2omyz9mw2n)

### Steps to reproduce
1：按照antd 官网对AutoComplete的定义value值的类型定义如下：string|string[]|{ key: string, label: string|ReactNode }|Array<{ key: string, label: string|ReactNode }>。
2：我设置的value是： value={{ key: "1", label: "121212" }} ,应该是复合标准的，但是报错。

### What is expected?
其实我想实现一个类似于<Select>组件的mode="multiple"模式，但是因为Select组件，没得自动补全的。以及不能自定义input，所以选择AntoComplete,但是我又想把Tag标签放在AutoCompete的value里面（像Selectd多选模式一样）。所以现在这样报错。

### What is actually happening?
希望能实现<Select>mode="multiple"样式。

**Comment by zombieJ** [comment]
你可以动态修改 <Select /> 的 `children` 达到你要的效果。
（PS：你的重现挂了）

**Comment by xgj1988** [comment]
@zombieJ  可以给一个伪代码吗？3Q

**Comment by zombieJ** [comment]
```jsx
renderList = () => {
  const { value } = this.state;
  // 你的逻辑产生一个 list
  return list.map((val) => (
    <Option key={val} value={val}>{val}</Option>
  ));
};
```

```jsx
<Select onSearch={(value) => { this.setState({ value }) }}>
  {this.renderList()}
</Select>
```

**Comment by xgj1988** [comment]
@zombieJ  大哥，你这个是select组件 ，我说的是autocomplete的value 哦。如下代码：
<AutoComplete
        value={{ key: "1", label: "121212" }}
        dataSource={options}
        style={{ width: 200 }}
        placeholder="input here"
      />

**Comment by zombieJ** [comment]
AutoComplete 是封装的 Select，你的需求 AutoComplete 没有，但是 Select 改改可以做到。

**Comment by xgj1988** [comment]
@zombieJ 大神。  我如何 修改AutoComplete里面的Select呢？

**Comment by zombieJ** [comment]
你不用修改 AutoComplete，直接用 Select 。写法参照我上面的例子哈

**Comment by afc163** [comment]
你需要的是 Select[mode="tags"] https://ant.design/components/select-cn/#components-select-demo-tags

**Comment by xgj1988** [comment]
@afc163  开始我就想用这个，但是用这个又有一个问题，因为我的Input是需要自定义的，但是AutoComplete有一个Input属性可以自己操作，，select 并没有，因为我要加前缀和后缀，好像select又不行了。

**Comment by xgj1988** [comment]
@zombieJ  大神，，我其实开始就想用Select的，但是我已经回复 @afc163  了。我们需求是又可以在Input前面和后面添加前缀和后缀，所以才选择了AutoComplete。

**Comment by zombieJ** [comment]
前后缀指的是什么？具体点的例子？

**Comment by xgj1988** [comment]
@zombieJ  类似于 https://codesandbox.io/s/j3w609q4vw  这种

**Comment by xgj1988** [comment]
@zombieJ  因为AutoComplete 的children可以自己覆盖input ，比如我的代码如下：
` <AutoComplete
            value={keyword}
            dataSource={!readOnly ? options : null}
            {...newAutoCompleteProps}
            onChange={this.handleCompleteChange}
          >
            <Input
              ref={input => {
                if (input) {
                  this.input = input.input;
                  if (this.input) {
                    if (paddingLeft) {
                      this.input.style.paddingLeft = paddingLeft;
                    }
                    if (paddingRight) {
                      this.input.style.paddingRight = paddingRight;
                    }
                  }
                }
              }}
              placeholder={`请选择${name}`}
              prefix={inputPrefix}
              suffix={inputSuffix}
              className={inputClassName}
              readOnly={isAutoCompleteInputReadonly}
            />
          </AutoComplete>`

**Comment by xgj1988** [comment]
@zombieJ  

 <AutoComplete
            value={keyword}
            dataSource={!readOnly ? options : null}
            {...newAutoCompleteProps}
            onChange={this.handleCompleteChange}
          >
            <Input
              ref={input => {
                if (input) {
                  this.input = input.input;
                  if (this.input) {
                    if (paddingLeft) {
                      this.input.style.paddingLeft = paddingLeft;
                    }
                    if (paddingRight) {
                      this.input.style.paddingRight = paddingRight;
                    }
                  }
                }
              }}
              placeholder={`请选择${name}`}
              prefix={inputPrefix}
              suffix={inputSuffix}
              className={inputClassName}
              readOnly={isAutoCompleteInputReadonly}
            />
          </AutoComplete>

**Comment by zombieJ** [comment]
可以自己写一下 css 样式。不过如果是这种前后缀，感觉你要用 multiple 的需求挺怪异的

**Comment by xgj1988** [comment]
@zombieJ  怎么写样式嘛。其实这个需求比较常见，，你做过ERP系统就晓得了。

**Comment by xiaotaohong66** [comment]
最后解决了吗？方案是啥～我也遇到了这个需求

**Comment by xiaotaohong66** [comment]
可以用select 的mode="tags" 解决

**Comment by xgj1988** [comment]
@xiaotaohong66 shi e
