### ISSUE TITLE
Menu horizontal Mode causes error

### ISSUE THREAD

**Issue by antibytes** [ant-design/ant-design#11310]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
dva   umi 1.3.15

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
create Menu, add <Menu.Item/> inside. And add Link from 'react-router-dom' or 'umi/link' inside the item. When click causes error.

### What is expected?
no error

### What is actually happening?
<Link> should not at the outside of <Router> error

**Comment by antibytes** [comment]
Only horizontal mode cause error.

**Comment by picodoth** [comment]
https://github.com/ant-design/ant-design/issues/11300

original issue has been fixed via https://github.com/react-component/menu/pull/175.

more style regression fixed will come in https://github.com/react-component/menu/pull/176 soon.

**Comment by yesmeck** [comment]
We've revert related commits, try reinstall node_modules.
