### ISSUE TITLE
InputNumber

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1131]
How to use floating number?

i tried to use step 1.0, but it just ignores. If i set step 1.1, then it works, but in that case i can't set 1.2354 - it will be rounded to 1.2

what i want:
1) use floating number, like 1.234567
2) use step 1

**Comment by afc163** [comment]
Set step to `step={0.1}` or `step={0.000001}`.

**Comment by plandem** [comment]
but if i want to use step like 1, but for floats?

**Comment by afc163** [comment]
Try `step="1.000000"`

**Comment by plandem** [comment]
have you tried? cause for me it does not work as supposed.
http://codepen.io/anon/pen/oxjWbb?editors=001

**Comment by afc163** [comment]
http://codepen.io/anon/pen/BKoRzm?editors=001

Use string.

**Comment by plandem** [comment]
worked, but please fix documentation :) step must be type of number in documentation :) or another demo for floating number at least.

**Comment by plandem** [comment]
hmmm...it worked at codepen, but not if i use rc-input-number from antd:
https://www.dropbox.com/s/zijhl0w1g9mlmfe/Screenshot%202016-03-04%2018.32.58.png?dl=0
