### ISSUE TITLE
请问Dropdown组件下的菜单项为什么不会一起render出来？

### ISSUE THREAD

**Issue by zhaozhiming** [ant-design/ant-design#1132]
Hi, 
我在`Dropdown`的菜单里面有个自定义组件，我原来以为Dropdown render的时候会把下面的子组件一起render了，但现在看起来好像不会，需要我点击下拉菜单后，菜单里面的组件才会render出来。  

请问有没有办法让Dropdown菜单里的组件随Dropdown一起render出来？谢谢  

示例代码：http://codepen.io/zhaozhiming/pen/dMbNqY?editors=0010

**Comment by chaomaogithub** [comment]
奇怪的需求，需要访问dom节点？话说你这个antd.js文件是怎么打包出来的啊

**Comment by zhaozhiming** [comment]
不访问dom节点，我只是想让drowdown组件render的时候把下面的子组件一起render

**Comment by benjycui** [comment]
> 我只是想让drowdown组件render的时候把下面的子组件一起render

总得给个理由。

**Comment by zhaozhiming** [comment]
@benjycui 我的自定义组件里面一些业务逻辑，会判断如果用户没有添加东西会弹出一个Modal让用户添加，原来这个组件没有放到dropdown里面是可以正常工作的，但是现在放到dropdown里面就不行了。  
  
照理说render父级组件时会把下级的组件一起render才对，为什么Dropdown不会（需要出现下拉菜单才会）？是做了一些什么修改吗？

**Comment by chaomaogithub** [comment]
我猜这么做是为了性能优化吧，没有展开的节点，就不要加载；话说你那个antd.js怎么打包的啊，我都问第二遍了

**Comment by benjycui** [comment]
> 判断如果用户没有添加东西会弹出一个Modal让用户添加

你这个判断该不会是判断 Dropdown 弹层有多少个子节点吧。。。

**Comment by zhaozhiming** [comment]
@chaomaogithub 我也不知道，我是fork别人的一个codepen，你可以问问他@afc163 

@benjycui 不是，是我们系统的一个业务逻辑

**Comment by benjycui** [comment]
@zhaozhiming 。。。。

你们如何判断：

> 判断如果用户没有添加东西会弹出一个Modal让用户添加

这跟 Dropdown 有什么关系。

不描述清楚怎么解释。。

**Comment by zhaozhiming** [comment]
@benjycui 我觉得我弹出Model的逻辑跟我的问题没有什么关系。
我的问题是：  
1. Dropdown组件为什么在render时不会把子组件一起render出来？
2. 有没有办法可以让Dropdown组件在render时把子组件一起render出来？
  
我在chrome工具栏里面看到，这2个div在开始的时候是没有的，等到我点击`点击触发`链接后才出现。  
![image](https://cloud.githubusercontent.com/assets/1436694/13569802/06d49e42-e4a5-11e5-92d3-8cd620127e9e.png)

**Comment by zhaozhiming** [comment]
我用React-bootstrap试了下，好像就不会有这个问题：  
http://codepen.io/zhaozhiming/pen/mPVwPX?editors=0010

**Comment by afc163** [comment]
同 @benjycui 。不理解 `判断是否要弹出一个Modal` 为什么需要先 render 不显示的 dropdown 菜单。

**Comment by afc163** [comment]
dropdown 的逻辑继承自 https://github.com/react-component/trigger/blob/5666dfb3e5ab03b65c213774afba838c6001454c/src/Popup.jsx#L70-L82

rc-trigger 目前认为组件隐藏时不需要显示 dom ，需要有足够的理由做改动。

**Comment by zhaozhiming** [comment]
@afc163 因为我的Modal是放在dropdown的menu里面的，如果render dropdown时不render里面的menu的话，menu里面的Modal也就不会出来了。  
  
可能这个需求是比较特殊一些，我是想看看有没有配置（比如在dropdown设置个类似`visible`的属性）可以达到我的目的，如果没有的话就算了，我看看能否通过其他组件来满足我的需求。谢谢各位了。

**Comment by benjycui** [comment]
> 因为我的Modal是放在dropdown的menu里面的，如果render dropdown时不render里面的menu的话，menu里面的Modal也就不会出来了。

Modal 不需要放在 Menu 里面。。用户是否有添加东西，数据层判断就行了。

**Comment by zhaozhiming** [comment]
嗯，Modal不放在menu里面就可以了，谢谢。
