### ISSUE TITLE
Stateless function components cannot be given refs. Attempts to access this ref will fail

### ISSUE THREAD

**Issue by lucasleelz** [ant-design/ant-design#11324]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
react 16.2.0

### Reproduction link
Similar Issues 
[https://github.com/ant-design/ant-design/issues/8029](https://github.com/ant-design/ant-design/issues/8029)
https://codesandbox.io/s/lll8862jom

### Steps to reproduce
Input.Group caused warning of "Stateless function components cannot be given refs"

### What is expected?
None

### What is actually happening?
Input.Group caused warning of "Stateless function components cannot be given refs"

**Comment by lucasleelz** [comment]
@yesmeck 
https://codesandbox.io/s/lll8862jom

**Comment by yesmeck** [comment]
Input should be passed to `getFieldDecorator` without wrappers.

**Comment by yesmeck** [comment]
https://codesandbox.io/s/58nq7wv54

**Comment by lucasleelz** [comment]
@yesmeck Thanks, but, if I use Group as a component?
Because Select does not support suffixes.
https://github.com/ant-design/ant-design/issues/11305
https://github.com/ant-design/ant-design/issues/6866

https://codesandbox.io/s/kxoprk1yo

**Comment by damiangreen** [comment]
was this fixed ?

**Comment by ztplz** [comment]
@damiangreen Sorry, this has not been fixed yet.

**Comment by taichiyi** [comment]
yesmeck is right.

[https://github.com/react-component/form/blob/master/examples/react-native/App.js](https://github.com/react-component/form/blob/master/examples/react-native/App.js)

**Comment by evolify** [comment]
I got the same with Input.Search

**Comment by john-hu** [comment]
I got the same warning with my owned function component which is a wrapper of `Select` from antd with some default values filled.

**Comment by john-hu** [comment]
@taichiyi  Your example uses a `PureComponent` instead of `Functional Component`. That's the reason you don't get the warnings.

**Comment by aalpgiray** [comment]
> Input should be passed to `getFieldDecorator` without wrappers.

there should be a workaround to validate custom input components

**Comment by yoyo837** [comment]
@aalpgiray You are right and I got same here.
