### ISSUE TITLE
steps使用点状步骤图，无法自定义图标？因为我要title在下面这个样式。

### ISSUE THREAD

**Issue by Williamlook** [ant-design/ant-design#11320]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不合理

### What does the proposed API look like?
自定义的图标在任何情况下都能显示。

**Comment by afc163** [comment]
You can send us a PR~
