### ISSUE TITLE
Drawer display error when viewport change size

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#11326]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
WIN10 - Chome67 - React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/643q3kpj43)

### Steps to reproduce
Open and close in small size viewport, then change viewport to big size.

### What is expected?
Drawer display ok

### What is actually happening?
Percent display error

![drawer](https://user-images.githubusercontent.com/1730277/42858582-e405bb46-8a81-11e8-958a-dba61449d0b9.gif)

**Comment by chenshuai2144** [comment]
@jljsj33  look

**Comment by jljsj33** [comment]
说中文

**Comment by jljsj33** [comment]
没监听 resize 的问题。。。

**Comment by jljsj33** [comment]
@afc163 点表情挺快哦，，呀的。。一堆中国人讲着中式英文，，，为什么不能让老外用谷歌翻译。。。

**Comment by afc163** [comment]
不要监听 resize，用纯样式解决。

**Comment by jljsj33** [comment]
我知道，，antd 的好像不需要转换成 px,,我看看能否用 %。。。

**Comment by chenshuai2144** [comment]
fix in https://github.com/ant-design/ant-design/pull/11356
