### ISSUE TITLE
使用table组件 fix scroll属性的时候，如果scroll设置宽度>表格所有列之和，这里似乎会出现重复的2列

### ISSUE THREAD

**Issue by cathy0048** [ant-design/ant-design#11328]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
mac 10.12.4  chrome 67.0.3396.99  

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/8c7b443a](https://riddle.alibaba-inc.com/riddles/8c7b443a)

### Steps to reproduce
见重现链接
![image](https://user-images.githubusercontent.com/1029866/42863232-f28240aa-8a94-11e8-85d8-1a3361e2389b.png)

### What is expected?
移动横向滚动条，不会出现重现列

### What is actually happening?
移动横向滚动条，最后一列fix住的，出现了重现列

**Comment by ovictorain** [comment]
Maybe the sum of your columns' width is smaller than scroll.x .BTW,  it seems that your link is invalid.

**Comment by a494836960** [comment]
scroll.x 的宽度可以写成动态的，就不会有着问题了

**Comment by afc163** [comment]
- 你需要自行控制列宽度的和与 scroll.x 匹配。
- 如果列宽度之和是个固定值，那么两者最好相等。
- 如果列宽度之和小于 scroll.x，那么最好留一列或几列不设宽度，用于弹性适应剩余宽度。

**Comment by boborua** [comment]
> * 你需要自行控制列宽度的和与 scroll.x 匹配。
> * 如果列宽度之和是个固定值，那么两者最好相等。
> * 如果列宽度之和小于 scroll.x，那么最好留一列或几列不设宽度，用于弹性适应剩余宽度。

还有一种情况：
当页面宽度变大，页面宽度大于了所有列宽之和，并且存在fixed的列，也会出现上述问题。

**Comment by wengzs** [comment]
> > * 你需要自行控制列宽度的和与 scroll.x 匹配。
> > * 如果列宽度之和是个固定值，那么两者最好相等。
> > * 如果列宽度之和小于 scroll.x，那么最好留一列或几列不设宽度，用于弹性适应剩余宽度。
> 
> 还有一种情况：
> 当页面宽度变大，页面宽度大于了所有列宽之和，并且存在fixed的列，也会出现上述问题。

如果配置了动态的scorll.x，仍然出现重复列(这时候出现重复的列应该是fixed的那列)，那么在columns中再添加一个空配置项即可解决重复列问题（ columns.push({}); ，注意这个空项的位置。
![image](https://user-images.githubusercontent.com/14542348/56021639-860e0f00-5d3c-11e9-88ab-13c1ea200201.png)

**Comment by ZhaoTim** [comment]
这个问题到底该怎么修复。？？？疯了快。

**Comment by yoyo837** [comment]
请试一下最新版本，如有问题请打开一个洗的issue。

**Comment by ZhaoTim** [comment]
如果能升级到最新版本也不会来这问了，公司ant design库不是随便升级的。
目前已经尝试：
所有columns都设置width属性，且scrollX用动态方法计算
`{{x: columns.reduce((pre, cur) => pre + cur.width,0)}}`
还是不行，还有重复列。
还尝试了columns.push({} as any)也不行。
我只是想知道在不升级的情况 How To Fix  the bug.........

**Comment by a494836960** [comment]
@ZhaoTim 重复列应该是你 fixed 的宽度 不等于 列宽，导致不能完全覆盖住底下的那一层列？

**Comment by ZhaoTim** [comment]
> @ZhaoTim 重复列应该是你 fixed 的宽度 不等于 列宽，导致不能完全覆盖住底下的那一层列？

有点没看懂你的意思，我把所有的columns都加了width：100，我竟然发现，因为我一共给四列加了fixed:left的属性，然后屏幕很宽的情况下， 不只一列重复了，另一个fixed的列也重复出现了，。。。

**Comment by yoyo837** [comment]
如果你使用了一个特定功能有bug的版本，如果不更新版本or代码 如何解决bug呢？很困难的。

**Comment by a494836960** [comment]
有可能是这样：假如你table 总宽度 1000， 而你一共有5个列 每列设置width = 100 这种情况下实际上每列的宽度应该是 200 ，这时 你fixed 的4个列总宽度是400，所以会漏。
你应该根据实际的屏幕大小来设置width 和 scroll.x

**Comment by a494836960** [comment]
{{x: columns.reduce((pre, cur) => pre + cur.width,0)}}
这个只是当屏幕小于 x 的时候有用， 如果大于x 就没有意义了，所以 curWidth 需要根据容器实际宽度去加减

**Comment by ZhaoTim** [comment]
> {{x: columns.reduce((pre, cur) => pre + cur.width,0)}}
> 这个只是当屏幕小于 x 的时候有用， 如果大于x 就没有意义了，所以 curWidth 需要根据容器实际宽度去加减

我理解的scrollX的意义是当我的Table的宽度小于这个值的时候，会产生滚动条。
但是当Table的宽度大于scrollX的时候，antdesign会自适应地 给 每一列增加宽度。
大概是这样，但是现在的效果就是当Table宽度大于scrollX的时候，也就是大屏的时候，会莫名多了很多重复列（因为我有好几个列都是fixed的）
所以我觉得不应该来根据实际的屏幕大小来设置scrollX吧？？？？
anyway，我准备放弃做前端了，害怕自己猝死，，，。

**Comment by ZhaoTim** [comment]
> 试试 `scroll={{ x: 'max-content' }}` @ZhaoTim

还是不行，最终研究了一下，利用媒体查询来做，因为用的是`styled-components`,所以把计算之后的scrollX传给了`styled-component`生成的组件-> TableStyled,在TableStyled里面：
```javascript
export const TableStyled = styled(Table)`
  @media (max-width: ${(props: any) => props.scroll.x + 240 + 'px'} ) {
    .ant-table-fixed-left: {
     display: none;
    }
}
`;
```
因为发现了，fixed的列其实是手动生成然后覆盖到了表格上面，真正的列依旧存在，只不过在下面看不到。。。。。。我这个问题应该就是手动生成的列宽度something wrong。。。导致没有大屏（超过scrollX）就会有问题。

但是其实还是有问题，因为我们的Table经过封装，thead头部的内容有一个Popover是根据手动生成的固定列定位的，我现在把他隐藏了，Popover跑到了页面左上角。。。。

然而我已经放弃了。。。。

**Comment by a494836960** [comment]
```
// 如果总宽度大于 容器宽才会 fixed  newCountWidth是所有列的总宽度
resetWidth(newColumns, newCountWidth, scroll) { //重置宽度
        let container = document.getElementsByClassName('container')[0];
        let width = container && container.clientWidth;

        scroll.x = newCountWidth;
        if (newCountWidth > width && newColumns[0] && Util.isEmpty(this.props.expandedRowRender)) {
            newColumns[0].fixed = 'left';
            newColumns[newColumns.length-1].fixed = newColumns[newColumns.length-1].title === '操作' ? 'right' : undefined;
        } else if (newColumns[0]) {
            newColumns[0].fixed = undefined;
        }
        return newColumns;
    }
```

这是我以前写的一直没什么问题，可以参考一下

**Comment by SpinachMiss** [comment]
我也遇到这样的问题，如果我的表单列是动态加载的呢？ width 是百分比。

**Comment by kkkkkkxser** [comment]
> ```
> // 如果总宽度大于 容器宽才会 fixed  newCountWidth是所有列的总宽度
> resetWidth(newColumns, newCountWidth, scroll) { //重置宽度
>         let container = document.getElementsByClassName('container')[0];
>         let width = container && container.clientWidth;
> 
>         scroll.x = newCountWidth;
>         if (newCountWidth > width && newColumns[0] && Util.isEmpty(this.props.expandedRowRender)) {
>             newColumns[0].fixed = 'left';
>             newColumns[newColumns.length-1].fixed = newColumns[newColumns.length-1].title === '操作' ? 'right' : undefined;
>         } else if (newColumns[0]) {
>             newColumns[0].fixed = undefined;
>         }
>         return newColumns;
>     }
> ```
> 
> 这是我以前写的一直没什么问题，可以参考一下

大佬 牛逼啊 确实是这样可以解决 如果总宽度都小于容器 好像确实没有fixed的必要。
