### ISSUE TITLE
[table] Bad performance on filter and multi-selection

### ISSUE THREAD

**Issue by mgenware** [ant-design/ant-design#11331]
I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
macOS 10.13, chrome latest

### Reproduction link
https://codesandbox.io/s/ryvyo1x4wp

### Steps to reproduce
* Open the console panel of codesandbox
* Click on the face icon on the `Name` column and search sth, e.g. `j`
* When search completes, according to the console log, filter method got called **36** times while i only have **4** entries (**this is issue 1**)
* Select/unselect some rows
* According to the console log, filter method will be called **4** times every time the selection changes. (**this is issue 2**)

### What is expected?
For issues 1: filter method should be called only 4 times.
For issues 2: selection changes should not trigger the filter method.

### What is actually happening?
For issue 1: filter method is called a lot more than expected.
For issue 2: filter method is called when selection changes.

**Comment by mgenware** [comment]
Added an online reproducible demo at https://codesandbox.io/s/ryvyo1x4wp

**Comment by FreeClimb** [comment]
You need to provide a way to call the onFilter function only once, 
when you click on Ok - to Apply a filter, 
since Filtered data for the table can be created in a reducer or loaded from the server api (usually it is).
