### ISSUE TITLE
<select> component, when it's value propertie is not [] , placeholder can not be shown.

### ISSUE THREAD

**Issue by cathy0048** [ant-design/ant-design#11330]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
mac 10.12.4  chrome 67.0.3396.99  

### Reproduction link
[http://riddle.alibaba-inc.com/riddles/96fb3a07](http://riddle.alibaba-inc.com/riddles/96fb3a07)

### Steps to reproduce
when I change the value of state from [] to  '', the placeholder disappear

### What is expected?
when the value property in Select Component is '',the placeholder(输入sellerID精确查询) also can shown
![image](https://user-images.githubusercontent.com/1029866/42863778-cf6d4838-8a96-11e8-951f-648371242cc0.png)

### What is actually happening?
the placeholder disappear

**Comment by afc163** [comment]
It is expected behavior, `''` and `null` is considered as meaningful value, you should set it to `undefined` for showing placeholder.
