### ISSUE TITLE
table组件可以导出excel吗？

### ISSUE THREAD

**Issue by ranzhu123** [ant-design/ant-design#1133]
现在用到table组件，需要导出excel，可以实现吗？

**Comment by afc163** [comment]
呃。。。建议自行探索。

**Comment by tindytian** [comment]
简单粗暴的解决方案就是把table的html片段post到后台或者根据datasource拼接成<table>，在后台直接输出到excel文件

**Comment by ranzhu123** [comment]
准备用后台生成了

**Comment by ABoooClay** [comment]
chrome 导出excel时 innerHTML报错。。
