### ISSUE TITLE
table with fixed render wrong row when multiple line

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#11337]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
macOS, Chrome

### Reproduction link
[https://codepen.io/AshoneA/pen/BPzMVK?editors=0010](https://codepen.io/AshoneA/pen/BPzMVK?editors=0010)

### Steps to reproduce
when row data has children,  children data has multiple line display,  row is not render correct

### What is expected?
should render correct

### What is actually happening?
render wrong row

**Comment by yesmeck** [comment]
Fixed on upstream, try reinstall node_modules.
