### ISSUE TITLE
在Drawer中select下拉项不显示的bug，你们页面上的抽屉，打开Sandbox也是不显示下拉菜单的~

### ISSUE THREAD

**Issue by YingZzz** [ant-design/ant-design#11335]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
3.7.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y2p1w3vxwz)

### Steps to reproduce
<Drawer
            title="Create Campaign Name"
            width={520}
            visible={visible}
            closable={false}
            onClose={this.onClose}
          >
            {/* 新建Campaign Name */}
             <Form>
                <FormItem
                    label="Shop"
                    {...formItemLayout}
                    hasfeedback
                >
                    <Select placeholder="Please select an owner">
                      <Option value="xiao">Xiaoxiao Fu</Option>
                      <Option value="mao">Maomao Zhou</Option>
                    </Select>
                </FormItem>    
             </Form>   
            
          
          </Drawer>

### What is expected?
在Drawer中select下拉项显示

### What is actually happening?
在Drawer中select下拉项显示

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/11304, thx for reporting~

**Comment by YingZzz** [comment]
@afc163  #11304 是解决办法么？第一次用这个，不怎么会看。

**Comment by bnerDY** [comment]
@afc163 What is the next release ? 3.8.1? Thanks
