### ISSUE TITLE
react InputNumber OnChange事件只有value，没法用stopPropagation

### ISSUE THREAD

**Issue by mar105** [ant-design/ant-design#11332]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为我现在输入值时需要计算，当我输入快了，由于是异步的，值有问题。想用阻止冒泡的方式来处理。

### What does the proposed API look like?
输入时，以最后一次算的为主。

**Comment by zombieJ** [comment]
没懂，你说一个场景？

**Comment by mar105** [comment]
我InputNumber 输入值时要作计算，客户需要边输入边计算，计算要调用到后台，用到fetch，如果输入快了，例如我输入50000，他是从5，50，500，5000，50000，每输入一次去计算一次结果，最终返回不是50000算出来的值，由于是异步，有可能是5000最后返回，有可能是500的最后返回值，如果我输入慢一点，就是以50000来算出来。没有阻止冒泡，想要以最后一次来计算，前面的计算要全部终止。

**Comment by zombieJ** [comment]
使用 [debounce](https://lodash.com/docs/4.17.10#debounce)

**Comment by selinp** [comment]
当我在Collapse组件头部使用了InputNumber组件时，InputNumber的点击事件不能被阻止，会冒泡到Collapse组件头部点击事件上，给InputNumber加上onClick={e => e.stopPropagation()} 只能阻止input的事件冒泡，并不能阻止右侧加减按钮的冒泡

**Comment by p-nuliew** [comment]
> 

解决了吗

**Comment by kangyana** [comment]
的确不太友好，应该把 e 作为第二个参数。

**Comment by WiseWood** [comment]
同问
