### ISSUE TITLE
Ability to arrange fileList items from an Upload component

### ISSUE THREAD

**Issue by zomars** [ant-design/ant-design#11343]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It solves the need to have a specific arrangement of a set of uploaded files, for example in a gallery of images where the order matters.

### What does the proposed API look like?
Taking inspiration from [this PR](https://github.com/ant-design/ant-design/pull/11002), we could add a drag event handler to modify the current fileList state and return the new value. Or maybe something like [ListSort](https://github.com/ant-design/ant-motion/blob/master/src/edit/template/components/ListSort.jsx).  If you need me to be more specific please let me know.

Thanks for you hard work!

**Comment by afc163** [comment]
Duplicate of #8387
