### ISSUE TITLE
Checkbox不能对vlue和label绑定相应字段吗？

### ISSUE THREAD

**Issue by codepandy** [ant-design/ant-design#11341]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以灵活绑定数据源，而不需要把数据源转换成有value和label的字段才能用。

### What does the proposed API look like?
```
<CheckboxGroup labelFeild="id" labelField="name" options={LayerData} onChange={self.onChangeLayer} />
```

**Comment by afc163** [comment]
建议自行转换数据格式。
