### ISSUE TITLE
React-16.4.0 not supported

### ISSUE THREAD

**Issue by LeSGoel** [ant-design/ant-design#11355]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
react-boiler-plate

### Reproduction link
[https://github.com/LeSGoel/react-16.4.0-in_antd](https://github.com/LeSGoel/react-16.4.0-in_antd)

### Steps to reproduce
just clone from the repo and run npm install or yarn add, run npm start ,on the local host click on open button and you get that antd modal not working

### What is expected?
antd modal should pe appear as a popup as shown in the website

### What is actually happening?
modal not popup , it comes below the webpage , it should be appear in the center

**Comment by yesmeck** [comment]
Plz provide a minimal reprodution on codesanbox.io, thanks!

**Comment by LeSGoel** [comment]
here is the link
https://codesandbox.io/s/ql4l9l8lzj
<img width="480" alt="screen shot 2018-07-19 at 1 35 16 pm" src="https://user-images.githubusercontent.com/41039987/42929793-bd94bee4-8b58-11e8-8ef4-ce31de940b5b.png">
<img width="488" alt="screen shot 2018-07-19 at 1 35 27 pm" src="https://user-images.githubusercontent.com/41039987/42929794-bdda4612-8b58-11e8-9118-50d6b1916eb7.png">

**Comment by yesmeck** [comment]
You forgot import css, plz refer to the document how to use antd.

**Comment by yesmeck** [comment]
Working sample https://codesandbox.io/s/wqjxxvj3o8
