### ISSUE TITLE
Select Component:  can not show the arrow when the mode is multiple

### ISSUE THREAD

**Issue by detectiveHLH** [ant-design/ant-design#11350]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In some situation, we may need show the arrow on the right side of the component even the mode is multiple.
Because for the normal user, when you give a select component to him, his first reaction may be to find the arrow in this select box.If there is not an arrow, he may feel kind of werid.

### What does the proposed API look like?
```javascript
import { Select } from 'antd';

class SelectSizesDemo extends React.Component {
  state = {
    size: 'default',
  };

  handleSizeChange = (e) => {
    this.setState({ size: e.target.value });
  }

  render() {
    const { size } = this.state;
    return (
      <div>
        <br />
        <Select
          mode="multiple"
          showArrow="true"
          size={size}
          placeholder="Please select"
          defaultValue={['a10', 'c12']}
          onChange={handleChange}
          style={{ width: '100%' }}
        >
          {children}
        </Select>
      </div>
    );
  }
}

ReactDOM.render(<SelectSizesDemo />, mountNode);
.code-box-demo .ant-select {
  margin: 0 8px 10px 0;
}

#components-select-demo-search-box .code-box-demo .ant-select {
  margin: 0;
}
```

**Comment by afc163** [comment]
It is by designed, multiple select don't display the arrow.

**Comment by wangcongyi** [comment]
@afc163  但是有时候需要啊，  有箭头表示用户可以选择而不是输入....
希望提供这个属性

**Comment by ankurpatel18** [comment]
I think that is fine as per design, but what if we want to show  arrow as proposed by @detectiveHLH.
Can you provide information how to do that? even I require in one of my project.

**Comment by detectiveHLH** [comment]
> I think that is fine as per design, but what if we want to show arrow as proposed by @detectiveHLH.
> Can you provide information how to do that? even I require in one of my project.

I don't think they'll change that.It is by designed.That what they said.I try to change the source code, but because the time.I didn't finished.

**Comment by vijaythakre** [comment]
I need single selection of User, in this Select component. Is that possible?
I tried removing the "mode" configuration but in that case it do not allows me to perform search .
