### ISSUE TITLE
Inconsistent width in form items 

### ISSUE THREAD

**Issue by ayox** [ant-design/ant-design#11358]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
Everywhere

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w0q242lz7)

### Steps to reproduce
You can check the sandbox link. 
When creating Form Items it comes without a consistent width. I prefer If we can have default option to make them all in the same width. 

### What is expected?
Have same width for all Form Items

### What is actually happening?
Different width depending on Form Item type.

**Comment by afc163** [comment]
It will cause breaking change so you have to set styles by youself.
