### ISSUE TITLE
Select 组件不能被包装起来

### ISSUE THREAD

**Issue by yuuk** [ant-design/ant-design#11352]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
mac os、Chrome64

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o2jx4r9pz)

### Steps to reproduce
访问地址：https://codesandbox.io/s/o2jx4r9pz

### What is expected?
不报错，功能正常。

### What is actually happening?
报错，功能不正常。

**Comment by zombieJ** [comment]
Select 内部对 key 有依赖，所以不支持 HOC。建议调整 Option 的子元素来达到你要的效果。

**Comment by jianfenkezhan** [comment]
Yes,  I also have the same problem, hope to fix it.

**Comment by yuuk** [comment]
@zombieJ 我是想增加一些扩展属性，有什么好办法吗。

**Comment by zombieJ** [comment]
@yuuk 能举个例子吗？

**Comment by yuuk** [comment]
貌似是OPTION的问题，option组件不支持hoc。先关了，希望能解决这个问题~~~
