### ISSUE TITLE
Failed to close "closable" Drawer when no mask

### ISSUE THREAD

**Issue by gulian** [ant-design/ant-design#11369]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
Chrome 67.0.3396.99
macOS 10.13.5 (17F77)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3lp8801nm)

### Steps to reproduce
On the codesandbox: 
- click on "show drawer" button 
- the drawer shows up 
- click on the cross on top right

### What is expected?
The drawer should be closed

### What is actually happening?
It's showing an error 

---
if the "mask" parameter is set to "true", the drawer is closable with the top right cross

**Comment by chenshuai2144** [comment]
fixed in https://github.com/ant-design/ant-design/pull/11356
