### ISSUE TITLE
Drawer ,当使用destroyOnClose={true}后，关闭抽屉的话，会直接抖动消失。

### ISSUE THREAD

**Issue by YingZzz** [ant-design/ant-design#11360]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
3.7.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4qxjjr156w)

### Steps to reproduce
destroyOnClose={true}

### What is expected?
解决直接抖动关闭

### What is actually happening?
解决直接抖动关闭

**Comment by jljsj33** [comment]
没看到闪动，，请把你的浏览器版本号也贴上来。。。

![kapture 2018-07-30 at 11 41 57](https://user-images.githubusercontent.com/6802825/43376506-bda6b57a-93ed-11e8-89ca-baa642556ba2.gif)
