### ISSUE TITLE
Allow adding className/style in Popover

### ISSUE THREAD

**Issue by Rohanhacker** [ant-design/ant-design#11364]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There is no way to pass className or style in popover. It would be difficult for someone to style popover if they are using css-in-js. 

### What does the proposed API look like?
className="classnames"
styles={styleObject}

**Comment by afc163** [comment]
Try `overlayClassName` and `overlayStyle`

**Comment by Rohanhacker** [comment]
@afc163 But this way it can't be styled by styled-components or emotion.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5570#issuecomment-332551645

**Comment by toiyeuhuong90** [comment]
> Try `overlayClassName` and `overlayStyle`

Thank so much

**Comment by MassoudSharifi** [comment]
overlayClassName and overlayStyle not working for me

**Comment by cbojaca** [comment]
Hi, I need to remove the padding inside the popover basically on this class ant-popover-inner-content, Thanks in advanced!

**Comment by audriuiv** [comment]
> overlayClassName and overlayStyle not working for me

It's working with !important tag.

**Comment by tiagomnferreira-mzt** [comment]
Using styled-components, I was having problems with the padding on the inner-content because I wanted to change the bg color according to the theme so I used withTheme to wrap my component, received my theme in the comp props and passed the bg color to overlayInnerStyle.
To sum it up:

```
const Comp = (props) =>(
    <Propover overlayInnerStyle={{ backgroundColor: props.theme.bgColor }}>...</Popover>
)

export default withTheme(Comp);

```

It doesnt solve the padding problem but since that was my issue with it, hope it helps someone out there!

**Comment by spencer741** [comment]
bump. Need to be able to remove padding.

**Comment by snrs-art** [comment]
this (handling `overlayInnerStyle`) has been fixed in https://ant.design/changelog#4.9.2
#27682

**Comment by douglasmamuty** [comment]
@spencer741 I have the same problem here, i passed the day trying to remove this padding. I want to custom the content, but the `overlayInnerStyle` ins't enough

`.ant-popover-inner-content {
    padding: 12px 16px;
    color: #494949;
}
`
Anyone has out of box idea?

**Comment by spencer741** [comment]
Bump. This needs to be fixed.

**Comment by spencer741** [comment]
Looks like this has been fixed. I had opened new issue to get attention a while back. 

https://github.com/ant-design/ant-design/issues/32275#issuecomment-1018493080

**Comment by Truongcot99** [comment]
> Cố gắng `overlayClassName`và `overlayStyle`

THANK YOU

**Comment by vijayczr** [comment]
set content style margin -12px , that should solve it

**Comment by bhosalekunalsanjay** [comment]
I used something like this in Angular and it got hidden in the background, Any better solution??????
nz-range-picker
                    [nzFormat]="dateTimeFormat" nzInline [(ngModel)]="dateSearchValues[header.key]"
                    style="height: 0px;
                            width: 0px;
                            top: -15px;
                            left: -29px;">

**Comment by gilluminate** [comment]
Anyone looking for a solution here for removing padding can use
```
overlayInnerStyle={{ "--ant-popover-inner-content-padding": 0 }}
```
