### ISSUE TITLE
TreeSelect组件focus样式问题

### ISSUE THREAD

**Issue by Instanced** [ant-design/ant-design#11368]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
Google Chrome

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
点击第一个Demo

### What is expected?
outline: none

### What is actually happening?
null

**Comment by chenshuai2144** [comment]
只有第一个 demo 有问题

**Comment by Instanced** [comment]
@chenshuai2144 不不，第三个也是有问题的。

**Comment by Instanced** [comment]
@chenshuai2144 还有就是 `TreeNode` 的 `value` props 类型为什么只限制为`string`类型呢？如果是数字ID就会报错了，能不能改成 `number|string` ？
