### ISSUE TITLE
customRequest使用了async await语法时AjaxUploader的abort方法无法正常执行

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#11363]
rc-upload -> file:AjaxUploader -> method:abort -> code:reqs[uid].abort();
如果reqs[uid]是promise就跪了~~~~~

**Comment by qiaoyixuan** [comment]
http://new-issue.ant.design/难用的一b。。。。

**Comment by AllanJian** [comment]
> [http://new-issue.ant.design/难用的一b。。。。](http://new-issue.ant.design/%E9%9A%BE%E7%94%A8%E7%9A%84%E4%B8%80b%E3%80%82%E3%80%82%E3%80%82%E3%80%82)

最后怎么解决的?

**Comment by AllanJian** [comment]
> [http://new-issue.ant.design/难用的一b。。。。](http://new-issue.ant.design/%E9%9A%BE%E7%94%A8%E7%9A%84%E4%B8%80b%E3%80%82%E3%80%82%E3%80%82%E3%80%82)

那个async方法return 一个 { abort: () => {} }可以解决这个问题 但是比较trick
