### ISSUE TITLE
Drawer组件内无法使用选择器，日历等组件

### ISSUE THREAD

**Issue by Instanced** [ant-design/ant-design#11367]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
Google Chrome 67.0.3396.99

### Reproduction link
[https://beta.preview.pro.ant.design/dashboard/analysis](https://beta.preview.pro.ant.design/dashboard/analysis)

### Steps to reproduce
（发现pro的示例也有此问题）点击右侧的个性化选项里面的 栅格模式，下拉无法显示option

### What is expected?
无

### What is actually happening?
无

---
使用了UMI

**Comment by chenshuai2144** [comment]
Waiting for the new version
https://github.com/ant-design/ant-design/issues/11304
