### ISSUE TITLE
Add an option to let us wrap Provider for funcitons like Modal.info and so on

### ISSUE THREAD

**Issue by Jack-Works** [ant-design/ant-design#11375]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will fix https://github.com/ant-design/ant-design/issues/6321

### What does the proposed API look like?
```jsx
Antd.setWrapper((children) =>
        <ReduxProvider store={stroe}>
              <IntlProvider>{children}</IntlProvider>
        </ReduxProvider>)
```

And apply this function here
https://github.com/ant-design/ant-design/blob/7fa05996957ef0eded21d810d71364d294ea947d/components/modal/confirm.tsx#L83
Let it become 
```js
ReactDOM.render(contextProvider(<Dialog ... />, div)
```

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/20949/
