### ISSUE TITLE
add getContainer props to Modal.confirm to allow React-Portal in confirmation modal

### ISSUE THREAD

**Issue by gjulivan** [ant-design/ant-design#11377]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Ability to support React-Portal in Modal.confirm (already supported by modal, but not Modal.confirm), thus, modal can be rendered using React 16's portal

### What does the proposed API look like?
```
const ConfirmDialog = (props) => {
  const { onCancel, onOk, close, zIndex, afterClose, visible, keyboard, getContainer } = props;

  return (
    <Dialog
...
      getContainer={getContainer}
...
    >
```

**Comment by yesmeck** [comment]
It's not possible to use React.Portal with current implementation of Modal.confirm.

**Comment by afc163** [comment]
https://codesandbox.io/s/84mm87lqk9

We should make this works.
