### ISSUE TITLE
Class for the created child inside body when using antd popover

### ISSUE THREAD

**Issue by Shelyo** [ant-design/ant-design#11387]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Antdpopover currently can only be styled in a very limited way using ugly workarounds due to how and where  the popover is created (wrapped inside two divs, which are attached as direct child of body)
It would be nice to have a class for the outermost div.
In our specific case, the popover is not displayed correctly while scrolling, since the popover is embedded inside a fixed container and the wrapper has position absolute.

### What does the proposed API look like?
```
<div class="new class name goes here" someinlinestyle>
   <div>
         <div class="ant-popover ant-popover-placement-bottomRight" inlinestyle>
           ...
        </div>
    </div>
</div>
```

**Comment by afc163** [comment]
Try `overlayClassName` and `overlayStyle`.

**Comment by Shelyo** [comment]
@afc163 
This does not resolve the issue as it adds just style/class to the div with the class `ant-popover` which I can already style and address.  Like I wrote above, I want to have a class on the outermost wrapper div, since it creates problems (due to where and how the popover is inserted).

I would like if you reopen the issue and don't close it directly after your answer again, so that I can tell you if your advice actually worked.

**Comment by afc163** [comment]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/507615/43008781-7f0e386e-8c6e-11e8-9c6d-3aa4bb4661e7.png">

**Comment by afc163** [comment]
>  Like I wrote above, I want to have a class on the outermost wrapper div, since it creates problems (due to where and how the popover is inserted).

```jsx
<Popover getPopupContainer={node => node.parentNode}>
  <div className="the-outermost-wrapper-classname-contain-both-trigger-and-popover">Trigger</div>
</Popover>
```

```css
.the-outermost-wrapper-classname-contain-both-trigger-and-popover {
  /* styling your popover and trigger */
}
```

**Comment by Shelyo** [comment]
Thanks!
This did the job (and my bad for the link).
For future reference I think it would be better if you add an explanation instead of writing it inside the CSS class though :)

For anyone having the same issue: `getPopupContainer={node => node.parentNode}` basically adds the popover inside the container where you have the Popover component of antd instead of into the body (which is the default).

**Comment by Mohamed-Ghanem** [comment]
@afc163
Hi, the proposed solution did not solve the problem as in some cases we need to render the popover normally in document.body.
Can we have a className="ant-popover-container" or add a key to the api containerClassName so we can access the outermost div of the popover?
