### ISSUE TITLE
Discrepancies between selectedRowKeys and selectedRows

### ISSUE THREAD

**Issue by mgenware** [ant-design/ant-design#11384]
I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
macOS 10.13, chrome latest

### Reproduction link
Added an online reproducible demo at https://codesandbox.io/s/ryvyo1x4wp

### Steps to reproduce
**Please strictly follow these steps to reproduce the issue, thanks for your patience 😃**
* Open the console panel of codesandbox
* Click on the face icon of `Name` column and search `joe`
* Select the entry named `Joe Black`
* Click the face icon of `Name` column and search `jim`
* **(1)** Select the entry named `Jim Green` 
* **(2)** Unselect the entry named `Jim Green`

### What is expected?
`selectedRowKeys` and `selectedRows` should not have any discrepancies

### What is actually happening?
**(1)** when selecting `Jim Green`, console shows:
```
selectedRowKeys: 2,3
selectedRows: {key: "3", name: "Jim Green", age: 32, address: "Sidney No. 1 Lake Park"}
```

**(2)** when deselecting  `Jim Green`, console shows:
```
selectedRowKeys: 2 selectedRows:  []
```

**Comment by mgenware** [comment]
Sure, i've added an online reproducible demo at https://codesandbox.io/s/ryvyo1x4wp

**Comment by afc163** [comment]
Duplicate of #9751

**Comment by Even-Lau** [comment]
> Sure, i've added an online reproducible demo at https://codesandbox.io/s/ryvyo1x4wp

Sorry, there are some bugs in your demo.
