### ISSUE TITLE
DatePicker only disable input but allow select

### ISSUE THREAD

**Issue by BaconZhang** [ant-design/ant-design#11383]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes I do not want users to input something in the DatePicker, I just want them to select a certain date which is listed in the calendar. However, I can not found a props to realize my thought. Could you please add a props which can disable the input of this component but allow users to select date in the calendar at same time. Your timely reply would be much appreciated.

### What does the proposed API look like?
Probably could add a props named inputDisabled or someone like that.

**Comment by afc163** [comment]
https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date

**Comment by BaconZhang** [comment]
I don't want disabledDate or disabledTime, I just want not to change the date through typing a date in the input. Only select a date in calendar can change the value.

**Comment by afc163** [comment]
It is not supported now and probably won't, sorry.
