### ISSUE TITLE
Table加了useFixedHeader之后，排版样式错乱

### ISSUE THREAD

**Issue by liekkas** [ant-design/ant-design#1139]
Table 加上 useFixedHeader 字段，其他代码未动情况下

## 期望是这样子的
![Uploading Snip20160306_1.png…]()

## 实际上数据发生了错乱
![Uploading Snip20160306_2.png…]()

## 版本信息
- antd 0.12.8

**Comment by liekkas** [comment]
奇怪图片上传不上来，
期望是这样：

**Comment by liekkas** [comment]
图片老上传不上来，只能用外链了
[期望是这样的：](http://7xkjpz.com1.z0.glb.clouddn.com/Snip20160306_1.png)
[实际排班错乱了：](http://7xkjpz.com1.z0.glb.clouddn.com/Snip20160306_2.png)

**Comment by afc163** [comment]
http://ant.design/components/table/#demo-fixed-header

固定列的 `width`。
