### ISSUE TITLE
when I use customRequest of Upload, the onChange will not be called.

### ISSUE THREAD

**Issue by zheiyi** [ant-design/ant-design#11397]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
so I can use axios to upload file, and display the progress bar at the same time.

### What does the proposed API look like?
the "onChange" should be called at the same time.

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
