### ISSUE TITLE
Layout Section in Document Website is broken 

### ISSUE THREAD

**Issue by saostad** [ant-design/ant-design#11392]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
Browser

### Reproduction link
[https://ant.design/components/layout/](https://ant.design/components/layout/)

### Steps to reproduce
https://ant.design/components/layout/

### What is expected?
some example broken

### What is actually happening?
some examples are broken

---
https://ant.design/components/layout/

**Comment by mohamed-seada-1994** [comment]
I think there must be tests cover the maping of iframe names.

**Comment by afc163** [comment]
@benjycui Maybe it is bug of bisheng@0.29.0

**Comment by afc163** [comment]
- [ ] iframe demos in production are broken now.
- [ ] Another issue in development: https://github.com/ant-design/ant-design/commit/ee6ef28ec61d23bb4cff3dc3c01d9264a9cb5d25#commitcomment-29730601
