### ISSUE TITLE
Useless scrolling visible in the header and table.

### ISSUE THREAD

**Issue by rafaelodassi** [ant-design/ant-design#11390]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Useless scrolling visible in the header and table.
![capturar](https://user-images.githubusercontent.com/11441937/43014868-0ca8b492-8c24-11e8-84d6-c84c69778611.PNG)

### What does the proposed API look like?
Remove useless scroll.

**Comment by mohamed-seada-1994** [comment]
This is because of scroll.y From rc-table
http://react-component.github.io/table/examples/scrollY.html

**Comment by afc163** [comment]
See comments in https://github.com/react-component/table/pull/219

**Comment by YgamiLight** [comment]
请问当我屏幕的宽度足够大的时候，如何才能消除多余的X-轴滚动条呢？

**Comment by YgamiLight** [comment]
事实上只要我添加了scroll的x属性，无论我在columns里面如何设置width, X轴滚动条始终会出现。

**Comment by YgamiLight** [comment]
Set the CSS 'overflow-x:auto!important;' of the ant-table-body class solved my useless x-scrollbar problem.

**Comment by weiq** [comment]
觉得之前 overflow-x:auto比较合理，改为scroll解决了什么问题么

**Comment by 1010543618** [comment]
@weiq 

我也遇到这个问题了，然后找了一圈发现在 https://github.com/react-component/table/pull/208 这个提交里候改的
