### ISSUE TITLE
Dark menu under the header display not suitable

### ISSUE THREAD

**Issue by hongxuWei** [ant-design/ant-design#11399]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
every platform

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9167jlr17y)

### Steps to reproduce
create a dark menu as official layout demo

### What is expected?
display not right

### What is actually happening?
header and the menu should bottom align

---
I've create a PR please check it

**Comment by hongxuWei** [comment]
[link to PR](https://github.com/ant-design/ant-design/pull/11400)

**Comment by zombieJ** [comment]
Thanks for contribution. PR merged.
