### ISSUE TITLE
InputNumber arrows overlap fixed columns of table

### ISSUE THREAD

**Issue by jezikk** [ant-design/ant-design#11408]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
OS Windows 10, Google Chrome 67

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2jx4wjoynn)

### Steps to reproduce
The InputNumber component should be placed in the table with fixed columns. If the InputNumber is placed behind any fixed column, its arrow buttons overlap the content of fixed columns.

### What is expected?
The arrow buttons of InputNumber components do not overlap the content of fixed columns in the table.

### What is actually happening?
The arrow buttons of InputNumber components overlap the content of fixed columns in the table.
![overlap](https://user-images.githubusercontent.com/7671531/43049253-cdafa0f2-8df4-11e8-91a0-133175575965.png)

**Comment by afc163** [comment]
caused by https://github.com/ant-design/ant-design/issues/6289
