### ISSUE TITLE
3.7.1 DatePicker 指定了value之后，无法选择月份

### ISSUE THREAD

**Issue by soguagirl** [ant-design/ant-design#11405]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
macOS   "react": "^16.3.2"   "webpack": "^4.8.3"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ymwvrww58x)

### Steps to reproduce
如题

### What is expected?
修复此bug

### What is actually happening?
修复此bug

**Comment by afc163** [comment]
1. 你的 codesandbox 代码和问题无关。
2. 这不是 bug，请自行研习 React 受控组件概念：https://reactjs.org/docs/forms.html#controlled-components
