### ISSUE TITLE
Cannot change year or month in DatePicker when its wrapped in `form.getFieldDecorator`

### ISSUE THREAD

**Issue by djyde** [ant-design/ant-design#11416]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
all

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yw1w997nrx)

### Steps to reproduce
Click the DatePicker, try to click the arrow. 

### What is expected?
Should change month or year

### What is actually happening?
Nothing happend.

**Comment by ryanji94** [comment]
same as you. and when i downgrade antd form 3.7.x to 3.5.x, then remove nodemodule folder, it still have this problems. but when i downgrade and backup preview package-lock.json, ti works

**Comment by djyde** [comment]
3.7.0 works well

**Comment by ryanji94** [comment]
@djyde i have do these
when i change antd version to 3.7.0 or 3.7.1 or 3.5.x, then execute
$ rm-rf node_modules
$ rm package-lock.json
$ npm i
when I choose a date, choose again and click the year or month arrow, it still dosen't work.
but if i backup preview package-lock.json it works well

**Comment by luhw** [comment]
一样的情况，改用3.7.0可以

**Comment by changjunhao** [comment]
I have the same problem
