### ISSUE TITLE
list的infinite-virtualized-load demo在ie10下都不能工作

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#11413]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
win7 & ie10

### Reproduction link
[https://ant.design/components/list-cn/#header](https://ant.design/components/list-cn/#header)

### Steps to reproduce
1. 点击进入list组件
1. 下拉滚动到滚动加载无限长列表的demo

### What is expected?
正常显示列表

### What is actually happening?
顶部是空白，只有底部几行有显示

![image](https://user-images.githubusercontent.com/22299421/43064778-7f508afe-8e92-11e8-98fb-27ade967097e.png)

**Comment by nikogu** [comment]
@mraiguo 是不是第一次加载会出现，然后拖拽放大下浏览器窗口，它又好了。

**Comment by mraiguo** [comment]
@nikogu 不知道是不是loadmore例子里的dispatch在ie的兼容问题导致的（我觉得不是，我也修改了这块的兼容写法）。而且我也试过了拖拽放大浏览器窗口，它并没有变正常。
环境： vmware虚拟机， win7 32位系统 ie10 
![image](https://user-images.githubusercontent.com/22299421/43381793-64ae6380-9408-11e8-9b13-5ff028a06e1c.png)

**Comment by afc163** [comment]
react-virtualized 的问题，我们做不了啥。
