### ISSUE TITLE
AutoComplete 没有下拉匹配项的情况下回车会选中输入过程中的匹配项

### ISSUE THREAD

**Issue by minesaner** [ant-design/ant-design#11412]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
mac chrome 最新版

### Reproduction link
[https://ant.design/components/auto-complete-cn/](https://ant.design/components/auto-complete-cn/)

### Steps to reproduce
【不区分大小写】的代码演示中输入"downdddddd"，然后回车

### What is expected?
输入框中仍然显示"downdddddd"

### What is actually happening?
输入框选中了"Downing Street"

**Comment by cfk199244** [comment]
设置defaultActiveFirstOption=false就可以了.  不过有个问题就是回车后下拉框还在，没收缩起来，还没找到办法

**Comment by minesaner** [comment]
收缩后回车一样有问题，defaultActiveFirstOption=false 可以先作为解决方案

**Comment by ChiuMungZitAlexander** [comment]
Same problem. Fixed temporarily as @cfk199244 said.

**Comment by cfk199244** [comment]
@ChiuMungZitAlexander @minesaner 不好意思，刚看到. 后来用了偏方处理回车后下拉框还在的问题
export function autoCompleteEnter(control){
  if(control){
        control.select.rcSelect.inputRef.ele.input.onkeydown = (e) => { 
            if(e.keyCode == 13){
              control.select.rcSelect.onInputKeyDown(e);
              control.select.rcSelect.setOpenState(false,true);
              return;
            }
        }
    }
}


先defaultActiveFirstOption=false ,  然后ref={autoCompleteEnter}
