### ISSUE TITLE
Tooltip not working properly when used close to a disabled button

### ISSUE THREAD

**Issue by mauriciosoares** [ant-design/ant-design#11418]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
MacOS High Sierra, Chrome 67.0.3396.87

### Reproduction link
[https://codepen.io/anon/pen/ajJPxo?editors=001](https://codepen.io/anon/pen/ajJPxo?editors=001)

### Steps to reproduce
Hover the disabled button first, and then directly hover the button on the left.

### What is expected?
The Tooltip should appear

### What is actually happening?
The tooltip is not appearing

---
This only happened when the first button is disabled. If it was not disabled then everything works normally.

I only tested the tooltip with buttons, but this is possibly happening with other components as well.

This issue is similar to [this one](https://github.com/ant-design/ant-design/issues/10795), but not exactly the same thing

**Comment by chenshuai2144** [comment]
Chrome off all the events of the disbale button, wrapped in the outer div, can solve the problem

**Comment by afc163** [comment]
https://getbootstrap.com/docs/4.1/components/tooltips/#disabled-elements
