### ISSUE TITLE
form.getFieldValue method will create a new field in fieldMeta

### ISSUE THREAD

**Issue by lulut** [ant-design/ant-design#11414]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
Mac, Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/50x3l7y59n)

### Steps to reproduce
1. click "Add field" button
2. new row will be created with no issue
3. click "Error Button" button, no impacts to the function since the "list" variable has been initialized as an Array correctly.
4. reload the page
5. this time click "Error Button" first.
6. a new field "list" will be added to fieldMeta
7. click "Add field" button
8. error occurred because  list is an 'object' instead of 'Array'

### What is expected?
form.getFieldValue will not create a new field in form

### What is actually happening?
form.getFieldValue method will create a new field in fieldMeta. This causes an issue when set an array value to the field later.

**Comment by lulut** [comment]
Is there anyone looking at this issue?

**Comment by lulut** [comment]
I have done the pull request at [pull request](https://github.com/react-component/form/pull/183) to fix this bug.   But no one look at that either.

**Comment by afc163** [comment]
It seems to be fixed in latest version of antd now.
