### ISSUE TITLE
is it possible to use differ height of Form.Item when there is no error?

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1141]
How it looks now when there is no any error:
https://www.dropbox.com/s/fs8ybnjfdgcoo18/Screenshot%202016-03-06%2021.28.21.png?dl=0

It's one item. Looks like Form.Item always 'reserve' height for possible validation errors. Is possible ignore it? I want 'increased height' only in case of any errors.

**Comment by benjycui** [comment]
If `Form.Item` doesn't reserve height for errors, those elements after error message will "drop" suddenly when error shows. IMO, this will make users uncomfortable.

Maybe we should consult our designer @Chinglik
