### ISSUE TITLE
You cannot set field before registering it

### ISSUE THREAD

**Issue by BurnhamZhang** [ant-design/ant-design#11410]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
MAC  , chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l2ow9zjm5m)

### Steps to reproduce
open the demo

1.click first button 
2.click second button
3.click submit , field b miss
4.click first button , console show error: You cannot set field before registering it

### What is expected?
got field b

### What is actually happening?
since i have set field b , and i setFieldsValue b after set field ,but still got error

**Comment by zombieJ** [comment]
You remove the field since click second button
```jsx
const content =
  getFieldValue("a") === "1" ? (
    <FormItem {...formItemLayoutWithOutLabel}>
      {getFieldDecorator("b")(<Input />)}
    </FormItem>
  ) : null;
```

Which cause the warning of `You cannot set field before registering it`.

And also, when you remove the field from the view, Form will also clean the value of it.

If you want to keep the value, you can use css to hide the field.

**Comment by BurnhamZhang** [comment]
```javascript
 getFieldDecorator("a");
 getFieldDecorator("b");
```
but i had registered them before , and it works in value a, how doesn't it  work in value b?

@zombieJ

**Comment by zombieJ** [comment]
These code not in `return` which will not do the render process.
