### ISSUE TITLE
Collapsible sider is broken when collapsedWidth is specified

### ISSUE THREAD

**Issue by jezikk** [ant-design/ant-design#11422]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
OS Windows 10, Google Chrome 67

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j71x8ny4j9)

### Steps to reproduce
The target is to create the collapsible sider which is possible to show/hide by external buttons (not by in-built trigger). If collapsedWidth props is explicitly specified, the style of Collapsible trigger is broken.

### What is expected?
Collapsible trigger is aligned with Sider.

### What is actually happening?
Collapsible trigger has smaller width than Sider.
![image](https://user-images.githubusercontent.com/7671531/43089414-d15df1da-8ea4-11e8-85e6-4540cd826688.png)

**Comment by jezikk** [comment]
If I set collapsedWidth = 80, GUI defect is not shown. Perhaps It would be enough to change the defaultProps of collapsedWidth from 64 to 80. 64 is default value specified in docs.

**Comment by afc163** [comment]
You have to override the less variable https://github.com/ant-design/ant-design/blob/86398d910a2a535a58c0d410255955059a6c529c/components/style/themes/default.less#L319 now by following https://ant.design/docs/react/customize-theme

**Comment by abbychau** [comment]
instead of using a less variable, this should be passed by props to menu. (sider did the same)

**Comment by pak11273** [comment]
For react apps I had to use the collapsedWidth and change the less variable in craco.config.js
