### ISSUE TITLE
Validation green check mark

### ISSUE THREAD

**Issue by mikayel1982** [ant-design/ant-design#11428]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have select box with validation. The green check mark that shows the data entered is valid is in the left side of the check box. I want either move it to the right side or remove it at all if I am not be able to move it the right side. Thank you

### What does the proposed API look like?
 <Form.Item
                    {...formItemLayout}
                    label=" " colon={false}
                    {...db.getAntDValidationConfig('jobScheduleWeekly')} // goes to validation API.
                >  
                    
                    <Check.Box>

                            ..........................................
                            ..........................................
                            ..........................................

                    </Check.Box>
                
                </Form.Item>

**Comment by afc163** [comment]
Sorry, can not understand what you said.

**Comment by mikayel1982** [comment]
Then forward it to somebody who at least can read the code that I attached.
