### ISSUE TITLE
[Typescript] provider some inner type definition

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#11437]
### What problem does this feature solve?
As mentioned in https://github.com/ant-design/ant-design/issues/6023, To give the form an exact type is impossible.

### What does the proposed API look like?
I hope to provide a namespace called antd, can use some type definitions directly, such as antd.FormComponentProps, just like React.ReactNode.

**Comment by yesmeck** [comment]
`import FormComponentProps from 'antd/es/form'`;
