### ISSUE TITLE
3.7.1 RangePicker指定value后月份与年份都无法更改

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design#11439]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
chrome 67 react 16.4.1

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-time-related-controls](https://ant.design/components/form-cn/#components-form-demo-time-related-controls)

### Steps to reproduce
官网的例子都不好使了，点一下RangePicker就知道了，老版本的好使

### What is expected?
设定value后能选择月份与年份

### What is actually happening?
设定value后月份与年份点不动

**Comment by wumiangithub** [comment]
3.24.0发现同样的问题，只有部分电脑会这样。
