### ISSUE TITLE
Upload.Dragger makes Chrome crash while dragging files from pop-up window

### ISSUE THREAD

**Issue by estemomento** [ant-design/ant-design#11435]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
Chrome 67.0.3396.99 @ Windows 10 x64 15063.1088

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://6w6mq16n5r.codesandbox.io/)

### Steps to reproduce
1. Click in the Dragger
2. Select multiple files in the pop-up window
3. Drag the files on the Dragger

### What is expected?
Messages saying that upload succeeded.

### What is actually happening?
Messages saying that upload succeeded.
AND CHROME CRASHES!

**Comment by dengfuping** [comment]
@estemomento It seems that everything is ok. Could you give a gif to show the problem?
