### ISSUE TITLE
3.7.1 当RangePicker中的value 与组件state绑定时，会引起切换月份按钮失效

### ISSUE THREAD

**Issue by while-it** [ant-design/ant-design#11440]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
antd 3.7.1  react 16.2

### Reproduction link
[https://github.com/while-it/antd-3.7.1-issue](https://github.com/while-it/antd-3.7.1-issue)

### Steps to reproduce

将value绑定给rangepick就会触发这个bug

### What is expected?
应该正常能够选择月份切换月份功能

### What is actually happening?
不能选择月份切换月份

---
3.4.1 版本是正确的 3.7.1 出现的问题

**Comment by while-it** [comment]
设置了vlue之后 onchange时间不会触发

**Comment by wulanhada** [comment]
DatePicker也存在同样的问题，无法选择 年份 和月份
