### ISSUE TITLE
InputNumber如何通过触发事件获得焦点

### ISSUE THREAD

**Issue by xiao-hai** [ant-design/ant-design#1145]
我的使用场景是：点击添加按钮，新增一个InputNumber，并且总是最新的一个InputNumber获得焦点。
请问有办法让InputNumber获得焦点吗？

**Comment by benjycui** [comment]
建议先好好学习 React 的文档 https://facebook.github.io/react/docs/more-about-refs.html

**Comment by yiminghe** [comment]
autoFocus prop
