### ISSUE TITLE
It's always lags when I use "showSeach" or "mode=combobox" 

### ISSUE THREAD

**Issue by cfk199244** [ant-design/ant-design#11456]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
win7、IE/Chrome

### Reproduction link
[https://codepen.io/anon/pen/XBgZPr?editors=0010](https://codepen.io/anon/pen/XBgZPr?editors=0010)

### Steps to reproduce
1、set  mode='combobox' to SELECT  (or showSeach=true)
2、set datasouce about 360 data.
3、(Important) Each row of data has a "1111111111"

### What is expected?
More fluent in input.
I don't think there's a lot of data.

### What is actually happening?
It's lags when I press the word (1111....). 

---
I think the reason of this matter is as follows:
when I input the word.  ANTD filter more data and setState to re-render the component.

**Comment by afc163** [comment]
Duplicate of #11843
