### ISSUE TITLE
Select tags 类型，如何不让输入空格产生标签

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#11459]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.2

### Environment
win7、Chrome 67.0.3396.99（正式版本）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2x092kjmzj)

### Steps to reproduce
输入框输入空格，离开输入框，产生空格标签

### What is expected?
禁止输入空格，或者输入框标签可控

### What is actually happening?
空格也产生了标签

**Comment by yesmeck** [comment]
自己在 `handleChange` 里过滤下。

**Comment by EagleWolf** [comment]
不在表单里面还好，vlaue管用，在表单里面this.props.form.setFieldsValue({})不管用

**Comment by yesmeck** [comment]
那更简单了，`getValueFromEvent`。

**Comment by EagleWolf** [comment]
https://codesandbox.io/s/009k83k5vv,数据过滤掉了但是setFieldsValue就是不管用

**Comment by EagleWolf** [comment]
@yesmeck 简单的方法求怎么解决啊。
@ant-design-bot 这属不属于setFieldsValue的bug

**Comment by wen81643956** [comment]
@EagleWolf 我也遇到这个问题了，刚好看到你发的issus

**Comment by EagleWolf** [comment]
@wen81643956  果然管用，谢谢，https://codesandbox.io/s/009k83k5vv已更新，留给遇到一样问题的人吧
