### ISSUE TITLE
Tree text vertical-align not middle

### ISSUE THREAD

**Issue by vthinkxie** [ant-design/ant-design#11458]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.2

### Environment
mac & chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3y9390m15)
![19_25_54__07_25_2018](https://user-images.githubusercontent.com/1506722/43198523-8c67b2f2-9041-11e8-8197-26b4a36ab2e4.jpg)

### Steps to reproduce
open codesandbox

### What is expected?
tree text vertical-align middle

### What is actually happening?
tree text vertical-align not middle

**Comment by ilanus** [comment]
which version of chrome do you use? seems fine on 
> 67.0.3396.99 (Official Build)
<img width="333" alt="screen shot 2018-07-26 at 17 21 33" src="https://user-images.githubusercontent.com/9677898/43271691-7c5db372-90f8-11e8-97a6-7db9d74140fe.png">

**Comment by zombieJ** [comment]
Hi @vthinkxie , which chrome version do you use?
<img width="232" alt="2018-07-30 10 02 33" src="https://user-images.githubusercontent.com/5378891/43373978-ca55ee98-93df-11e8-9683-17b08a5c3767.png">

**Comment by vthinkxie** [comment]
版本 67.0.3396.99（正式版本） （64 位）

**Comment by vthinkxie** [comment]
版本 68.0.3440.75（正式版本） （64 位）has same problem.
