### ISSUE TITLE
You can't switch between mounths in the range picker when its parent component rerenders

### ISSUE THREAD

**Issue by NawfelBgh** [ant-design/ant-design#11454]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.4

### Environment
Windows 10, Firefox 61 (chrome and Edge too), React 16.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zrzjnn4kxx)

### Steps to reproduce
- Click the range picker to open it.
- Try to switch between months

### What is expected?
You can switch between months

### What is actually happening?
You can't switch between months

---
If we delete setState in the click handler, the range picker functions correctly.

**Comment by yesmeck** [comment]
Fixed in 3.7.2
