### ISSUE TITLE
地化3.7.1的时候报错:utils.js:17 Uncaught TypeError: Cannot use 'in' operator to search for 'transition' in null

### ISSUE THREAD

**Issue by mage1028** [ant-design/ant-design#11450]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.1

### Environment
react16.4.1 charome67.0.3396.99

### Reproduction link
[https://github.com/mage1028/antd_proolem](https://github.com/mage1028/antd_proolem)

### Steps to reproduce

在html文件中引入js
~~~
<script src="https://cdn.bootcss.com/babel-standalone/6.26.0/babel.min.js"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/react/16.4.1/umd/react.production.min.js"</script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/16.4.1/umd/react-dom.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>  
<script src="https://cdnjs.cloudflare.com/ajax/libs/antd/3.7.1/antd.js"></script>
<link rel="stylesheet" type="text/css"href="https://cdnjs.cloudflare.com/ajax/libs/antd/3.7.1/antd.css">
~~~
浏览器报错：utils.js:17 Uncaught TypeError: Cannot use 'in' operator to search for 'transition' in null
~~~
return key in (document.body && document.body.style);
~~~

在使用3.6.6的时候，即引入js
~~~
<script src="https://cdnjs.cloudflare.com/ajax/libs/antd/3.6.6/antd.js"></script>
~~~
并没有这个报错，antd可以正常加载

### What is expected?
use antd3.7.1 successfully

### What is actually happening?
报错

---
3.6.6的引入很正常。。

**Comment by zombieJ** [comment]
没有重现，操作步骤是什么？
