### ISSUE TITLE
TimePicker moves numbers when scroll bar appears

### ISSUE THREAD

**Issue by rmcp1g15** [ant-design/ant-design#11460]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.2

### Environment
React

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnw46698m3)

### Steps to reproduce
Click on box then select 'select time', hover either column and when the scrollbar appears the text jumps

### What is expected?
Not jumping text. for the scrollbar to appear but not to move the text

### What is actually happening?
the text is being moved when scrollbar appears

**Comment by afc163** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/507615/43243867-2ec14dda-90db-11e8-8063-e995642d938d.png">

**Comment by rmcp1g15** [comment]
Here is the link https://codesandbox.io/s/433k96y014 Thank you
