### ISSUE TITLE
请问 2.x 版本文档是否有国内镜像地址？

### ISSUE THREAD

**Issue by Witee** [ant-design/ant-design#11465]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
国内访问 http://2x.ant.design/ 慢的问题

### What does the proposed API look like?
希望 http://ant-design.gitee.io/ 域名下能有2.x的文档

**Comment by yesmeck** [comment]
http://ant-design-2x.gitee.io/index-cn

**Comment by Witee** [comment]
我知道什么问题了，打开 http://ant-design.gitee.io/index-cn 之后点击右上角，选择2.x版本，然后就会跳转到 http://2x.ant.design/index-cn ，并不能一直在 ant-design.gitee.io 域名上。

**Comment by FengLee1113** [comment]
不知道3.x的是否有国内镜像站点呢，使用3x.ant.design访问很慢，使用http://ant-design-3x.gitee.io/index-cn 是访问不到的，现在文档都是4x的，但是没升级的还要看3x的文档。

**Comment by WebEngineerLi** [comment]
同问 antd 3.x 是否有国内镜像地址

**Comment by xrkffgg** [comment]
ant-design 国内镜像地址：https://github.com/ant-design/ant-design/issues/25661
