### ISSUE TITLE
Ant design docs on Icon causes 100% CPU usage - https://ant.design/components/icon/

### ISSUE THREAD

**Issue by eryi** [ant-design/ant-design#11463]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.2

### Environment
Chrome 67

### Reproduction link
[https://ant.design/components/icon/](https://ant.design/components/icon/)

### Steps to reproduce
Open https://ant.design/components/icon/ in Chrome

Open Chrome task manager (menu > More Tools > Task Manager or Shift   Esc)

### What is expected?
https://ant.design/components/icon/ should not cause 100% CPU usage

### What is actually happening?
https://ant.design/components/icon/ causes 100% CPU usage

---
I couldn't find the repo for https://ant.design/ website. Apologize if this is not the correct place to post issues with the website.

**Comment by ilanus** [comment]
@eryi the ant-design landing page is right here 😄 just clone this repo and run it. I could reproduce this issue as-well. I think that what causes it Is the following component: `ant-design/site/theme/template/IconSet/index.jsx`

```javascript
render() {
  const { className, catigory } = this.props;
  const listClassName = classNames({
    'anticons-list': true,
    clearfix: true,
    [className]: !!className,
  });
  return (
    <ul className={listClassName}>
     {this.icons[catigory].map(type => (
        <CopyableIcon key={type} type={type} isNew={this.newIcons.indexOf(type) >= 0} />
      ))}
    </ul>
  );
}
```

It seems that the cpu usage is due to:

```javascript
{this.icons[catigory].map(type => (
  <CopyableIcon key={type} type={type} isNew={this.newIcons.indexOf(type) >= 0} />
))}
```
disabling this `.map` function makes puts the cpu back to normal.

**Comment by eryi** [comment]
@ilanus the deploy preview at https://deploy-preview-11488--ant-design.netlify.com/components/icon/ is still taking 100% CPU for me. I don't think your PR fixed it.

I looked into the problem and discovered that
1. Removing the 'loading' icon **totally fixes** the CPU issue on the icon page
2. However, using the 'loading' icon by itself only uses around 25% CPU https://codepen.io/anon/pen/PBOayN?editors=001

Does this qualify as a bug for the loading icon?
