### ISSUE TITLE
Set Checkbox using form setFields

### ISSUE THREAD

**Issue by mrdannael** [ant-design/ant-design#11468]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.2

### Environment
Ubuntu, Chrome

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
Set checkbox value using form setFields method.

### What is expected?
Setting initial checkbox value.

### What is actually happening?
Checkbox is not set properly.

---
How should i use setFields to set Checkbox value as 'checked'?

**Comment by eozbay** [comment]
Have you any solution?

**Comment by mrdannael** [comment]
@eozbay 
I'm setting the initial value in **getFieldDecorator** for specific field.

```
<Form.Item>
     {form.getFieldDecorator('require_location', {
         valuePropName: 'checked',
         initialValue: this.props.require_location,
     })(
         <Checkbox>Require GPS location</Checkbox>
     )}
</Form.Item>
````
