### ISSUE TITLE
Tree.I hope to custom node style.

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#11466]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ui
![image](https://user-images.githubusercontent.com/8358236/43245949-b9d81f00-90e2-11e8-9a14-bcbf9a8ec046.png)

### What does the proposed API look like?
no

**Comment by afc163** [comment]
Sorry, cannot understand what are you talking about with so less information.
