### ISSUE TITLE
TreeSelect 数据展示BUG

### ISSUE THREAD

**Issue by lomocc** [ant-design/ant-design#1147]
我这里有一个疑似Bug，希望帮忙看下是否有问题，（主要是天津市只有一个子项，却错误展示了别的省份数据）
const option = `[{"label":"北京市110000","value":"110000","children":[{"label":"北京市110100","value":"110100"}]},{"label":"天津市120000","value":"120000","children":[{"label":"天津市120100","value":"120100"}]},{"label":"河北省130000","value":"130000","children":[{"label":"石家庄市130100","value":"130100"},{"label":"唐山市130200","value":"130200"},{"label":"秦皇岛市130300","value":"130300"},{"label":"邯郸市130400","value":"130400"},{"label":"邢台市130500","value":"130500"},{"label":"保定市130600","value":"130600"},{"label":"张家口市130700","value":"130700"},{"label":"承德市130800","value":"130800"},{"label":"沧州市130900","value":"130900"},{"label":"廊坊市131000","value":"131000"},{"label":"衡水市131100","value":"131100"}]},{"label":"山西省140000","value":"140000","children":[{"label":"太原市140100","value":"140100"},{"label":"大同市140200","value":"140200"},{"label":"阳泉市140300","value":"140300"},{"label":"长治市140400","value":"140400"},{"label":"晋城市140500","value":"140500"},{"label":"朔州市140600","value":"140600"},{"label":"晋中市140700","value":"140700"},{"label":"运城市140800","value":"140800"},{"label":"忻州市140900","value":"140900"},{"label":"临汾市141000","value":"141000"},{"label":"吕梁市141100","value":"141100"}]},{"label":"内蒙古自治区150000","value":"150000","children":[{"label":"呼和浩特市150100","value":"150100"},{"label":"包头市150200","value":"150200"},{"label":"乌海市150300","value":"150300"},{"label":"赤峰市150400","value":"150400"},{"label":"通辽市150500","value":"150500"},{"label":"鄂尔多斯市150600","value":"150600"},{"label":"呼伦贝尔市150700","value":"150700"},{"label":"巴彦淖尔市150800","value":"150800"},{"label":"乌兰察布市150900","value":"150900"},{"label":"兴安盟152200","value":"152200"},{"label":"锡林郭勒盟152500","value":"152500"},{"label":"阿拉善盟152900","value":"152900"}]},{"label":"辽宁省210000","value":"210000","children":[{"label":"沈阳市210100","value":"210100"},{"label":"大连市210200","value":"210200"},{"label":"鞍山市210300","value":"210300"},{"label":"抚顺市210400","value":"210400"},{"label":"本溪市210500","value":"210500"},{"label":"丹东市210600","value":"210600"},{"label":"锦州市210700","value":"210700"},{"label":"营口市210800","value":"210800"},{"label":"阜新市210900","value":"210900"},{"label":"辽阳市211000","value":"211000"},{"label":"盘锦市211100","value":"211100"},{"label":"铁岭市211200","value":"211200"},{"label":"朝阳市211300","value":"211300"},{"label":"葫芦岛市211400","value":"211400"}]},{"label":"吉林省220000","value":"220000","children":[{"label":"长春市220100","value":"220100"},{"label":"吉林市220200","value":"220200"},{"label":"四平市220300","value":"220300"},{"label":"辽源市220400","value":"220400"},{"label":"通化市220500","value":"220500"},{"label":"白山市220600","value":"220600"},{"label":"松原市220700","value":"220700"},{"label":"白城市220800","value":"220800"},{"label":"延边朝鲜族自治州222400","value":"222400"}]},{"label":"黑龙江省230000","value":"230000","children":[{"label":"哈尔滨市230100","value":"230100"},{"label":"齐齐哈尔市230200","value":"230200"},{"label":"鸡西市230300","value":"230300"},{"label":"鹤岗市230400","value":"230400"},{"label":"双鸭山市230500","value":"230500"},{"label":"大庆市230600","value":"230600"},{"label":"伊春市230700","value":"230700"},{"label":"佳木斯市230800","value":"230800"},{"label":"七台河市230900","value":"230900"},{"label":"牡丹江市231000","value":"231000"},{"label":"黑河市231100","value":"231100"},{"label":"绥化市231200","value":"231200"},{"label":"大兴安岭地区232700","value":"232700"}]},{"label":"上海市310000","value":"310000","children":[{"label":"上海市310100","value":"310100"}]},{"label":"江苏省320000","value":"320000","children":[{"label":"南京市320100","value":"320100"},{"label":"无锡市320200","value":"320200"},{"label":"徐州市320300","value":"320300"},{"label":"常州市320400","value":"320400"},{"label":"苏州市320500","value":"320500"},{"label":"南通市320600","value":"320600"},{"label":"连云港市320700","value":"320700"},{"label":"淮安市320800","value":"320800"},{"label":"盐城市320900","value":"320900"},{"label":"扬州市321000","value":"321000"},{"label":"镇江市321100","value":"321100"},{"label":"泰州市321200","value":"321200"},{"label":"宿迁市321300","value":"321300"}]},{"label":"浙江省330000","value":"330000","children":[{"label":"杭州市330100","value":"330100"},{"label":"宁波市330200","value":"330200"},{"label":"温州市330300","value":"330300"},{"label":"嘉兴市330400","value":"330400"},{"label":"湖州市330500","value":"330500"},{"label":"绍兴市330600","value":"330600"},{"label":"金华市330700","value":"330700"},{"label":"衢州市330800","value":"330800"},{"label":"舟山市330900","value":"330900"},{"label":"台州市331000","value":"331000"},{"label":"丽水市331100","value":"331100"}]},{"label":"安徽省340000","value":"340000","children":[{"label":"合肥市340100","value":"340100"},{"label":"芜湖市340200","value":"340200"},{"label":"蚌埠市340300","value":"340300"},{"label":"淮南市340400","value":"340400"},{"label":"马鞍山市340500","value":"340500"},{"label":"淮北市340600","value":"340600"},{"label":"铜陵市340700","value":"340700"},{"label":"安庆市340800","value":"340800"},{"label":"黄山市341000","value":"341000"},{"label":"滁州市341100","value":"341100"},{"label":"阜阳市341200","value":"341200"},{"label":"宿州市341300","value":"341300"},{"label":"六安市341500","value":"341500"},{"label":"亳州市341600","value":"341600"},{"label":"池州市341700","value":"341700"},{"label":"宣城市341800","value":"341800"}]},{"label":"福建省350000","value":"350000","children":[{"label":"福州市350100","value":"350100"},{"label":"厦门市350200","value":"350200"},{"label":"莆田市350300","value":"350300"},{"label":"三明市350400","value":"350400"},{"label":"泉州市350500","value":"350500"},{"label":"漳州市350600","value":"350600"},{"label":"南平市350700","value":"350700"},{"label":"龙岩市350800","value":"350800"},{"label":"宁德市350900","value":"350900"}]},{"label":"江西省360000","value":"360000","children":[{"label":"南昌市360100","value":"360100"},{"label":"景德镇市360200","value":"360200"},{"label":"萍乡市360300","value":"360300"},{"label":"九江市360400","value":"360400"},{"label":"新余市360500","value":"360500"},{"label":"鹰潭市360600","value":"360600"},{"label":"赣州市360700","value":"360700"},{"label":"吉安市360800","value":"360800"},{"label":"宜春市360900","value":"360900"},{"label":"抚州市361000","value":"361000"},{"label":"上饶市361100","value":"361100"}]},{"label":"山东省370000","value":"370000","children":[{"label":"济南市370100","value":"370100"},{"label":"青岛市370200","value":"370200"},{"label":"淄博市370300","value":"370300"},{"label":"枣庄市370400","value":"370400"},{"label":"东营市370500","value":"370500"},{"label":"烟台市370600","value":"370600"},{"label":"潍坊市370700","value":"370700"},{"label":"济宁市370800","value":"370800"},{"label":"泰安市370900","value":"370900"},{"label":"威海市371000","value":"371000"},{"label":"日照市371100","value":"371100"},{"label":"莱芜市371200","value":"371200"},{"label":"临沂市371300","value":"371300"},{"label":"德州市371400","value":"371400"},{"label":"聊城市371500","value":"371500"},{"label":"滨州市371600","value":"371600"},{"label":"菏泽市371700","value":"371700"}]},{"label":"河南省410000","value":"410000","children":[{"label":"郑州市410100","value":"410100"},{"label":"开封市410200","value":"410200"},{"label":"洛阳市410300","value":"410300"},{"label":"平顶山市410400","value":"410400"},{"label":"安阳市410500","value":"410500"},{"label":"鹤壁市410600","value":"410600"},{"label":"新乡市410700","value":"410700"},{"label":"焦作市410800","value":"410800"},{"label":"濮阳市410900","value":"410900"},{"label":"许昌市411000","value":"411000"},{"label":"漯河市411100","value":"411100"},{"label":"三门峡市411200","value":"411200"},{"label":"南阳市411300","value":"411300"},{"label":"商丘市411400","value":"411400"},{"label":"信阳市411500","value":"411500"},{"label":"周口市411600","value":"411600"},{"label":"驻马店市411700","value":"411700"},{"label":"省直辖县级行政区划419000","value":"419000"}]},{"label":"湖北省420000","value":"420000","children":[{"label":"武汉市420100","value":"420100"},{"label":"黄石市420200","value":"420200"},{"label":"十堰市420300","value":"420300"},{"label":"宜昌市420500","value":"420500"},{"label":"襄阳市420600","value":"420600"},{"label":"鄂州市420700","value":"420700"},{"label":"荆门市420800","value":"420800"},{"label":"孝感市420900","value":"420900"},{"label":"荆州市421000","value":"421000"},{"label":"黄冈市421100","value":"421100"},{"label":"咸宁市421200","value":"421200"},{"label":"随州市421300","value":"421300"},{"label":"恩施土家族苗族自治州422800","value":"422800"},{"label":"省直辖县级行政区划429000","value":"429000"}]},{"label":"湖南省430000","value":"430000","children":[{"label":"长沙市430100","value":"430100"},{"label":"株洲市430200","value":"430200"},{"label":"湘潭市430300","value":"430300"},{"label":"衡阳市430400","value":"430400"},{"label":"邵阳市430500","value":"430500"},{"label":"岳阳市430600","value":"430600"},{"label":"常德市430700","value":"430700"},{"label":"张家界市430800","value":"430800"},{"label":"益阳市430900","value":"430900"},{"label":"郴州市431000","value":"431000"},{"label":"永州市431100","value":"431100"},{"label":"怀化市431200","value":"431200"},{"label":"娄底市431300","value":"431300"},{"label":"湘西土家族苗族自治州433100","value":"433100"}]},{"label":"广东省440000","value":"440000","children":[{"label":"深圳市440300","value":"440300"},{"label":"珠海市440400","value":"440400"},{"label":"汕头市440500","value":"440500"},{"label":"佛山市440600","value":"440600"},{"label":"江门市440700","value":"440700"},{"label":"湛江市440800","value":"440800"},{"label":"茂名市440900","value":"440900"},{"label":"肇庆市441200","value":"441200"},{"label":"惠州市441300","value":"441300"},{"label":"梅州市441400","value":"441400"},{"label":"汕尾市441500","value":"441500"},{"label":"河源市441600","value":"441600"},{"label":"阳江市441700","value":"441700"},{"label":"清远市441800","value":"441800"},{"label":"东莞市441900","value":"441900"},{"label":"中山市442000","value":"442000"},{"label":"潮州市445100","value":"445100"},{"label":"揭阳市445200","value":"445200"},{"label":"云浮市445300","value":"445300"},{"label":"广州市440100","value":"440100"},{"label":"韶关市440200","value":"440200"}]},{"label":"广西壮族自治区450000","value":"450000","children":[{"label":"南宁市450100","value":"450100"},{"label":"柳州市450200","value":"450200"},{"label":"桂林市450300","value":"450300"},{"label":"梧州市450400","value":"450400"},{"label":"北海市450500","value":"450500"},{"label":"防城港市450600","value":"450600"},{"label":"钦州市450700","value":"450700"},{"label":"贵港市450800","value":"450800"},{"label":"玉林市450900","value":"450900"},{"label":"百色市451000","value":"451000"},{"label":"贺州市451100","value":"451100"},{"label":"河池市451200","value":"451200"},{"label":"来宾市451300","value":"451300"},{"label":"崇左市451400","value":"451400"}]},{"label":"海南省460000","value":"460000","children":[{"label":"海口市460100","value":"460100"},{"label":"三亚市460200","value":"460200"},{"label":"三沙市460300","value":"460300"},{"label":"省直辖县级行政区划469000","value":"469000"}]},{"label":"重庆市500000","value":"500000","children":[{"label":"重庆市500100","value":"500100"}]},{"label":"四川省510000","value":"510000","children":[{"label":"成都市510100","value":"510100"},{"label":"自贡市510300","value":"510300"},{"label":"攀枝花市510400","value":"510400"},{"label":"泸州市510500","value":"510500"},{"label":"德阳市510600","value":"510600"},{"label":"绵阳市510700","value":"510700"},{"label":"广元市510800","value":"510800"},{"label":"遂宁市510900","value":"510900"},{"label":"内江市511000","value":"511000"},{"label":"乐山市511100","value":"511100"},{"label":"南充市511300","value":"511300"},{"label":"眉山市511400","value":"511400"},{"label":"宜宾市511500","value":"511500"},{"label":"广安市511600","value":"511600"},{"label":"达州市511700","value":"511700"},{"label":"雅安市511800","value":"511800"},{"label":"巴中市511900","value":"511900"},{"label":"资阳市512000","value":"512000"},{"label":"阿坝藏族羌族自治州513200","value":"513200"},{"label":"甘孜藏族自治州513300","value":"513300"},{"label":"凉山彝族自治州513400","value":"513400"}]},{"label":"贵州省520000","value":"520000","children":[{"label":"贵阳市520100","value":"520100"},{"label":"六盘水市520200","value":"520200"},{"label":"遵义市520300","value":"520300"},{"label":"安顺市520400","value":"520400"},{"label":"毕节市520500","value":"520500"},{"label":"铜仁市520600","value":"520600"},{"label":"黔西南布依族苗族自治州522300","value":"522300"},{"label":"黔东南苗族侗族自治州522600","value":"522600"},{"label":"黔南布依族苗族自治州522700","value":"522700"}]},{"label":"云南省530000","value":"530000","children":[{"label":"昆明市530100","value":"530100"},{"label":"曲靖市530300","value":"530300"},{"label":"玉溪市530400","value":"530400"},{"label":"保山市530500","value":"530500"},{"label":"昭通市530600","value":"530600"},{"label":"丽江市530700","value":"530700"},{"label":"普洱市530800","value":"530800"},{"label":"临沧市530900","value":"530900"},{"label":"楚雄彝族自治州532300","value":"532300"},{"label":"红河哈尼族彝族自治州532500","value":"532500"},{"label":"文山壮族苗族自治州532600","value":"532600"},{"label":"西双版纳傣族自治州532800","value":"532800"},{"label":"大理白族自治州532900","value":"532900"},{"label":"德宏傣族景颇族自治州533100","value":"533100"},{"label":"怒江傈僳族自治州533300","value":"533300"},{"label":"迪庆藏族自治州533400","value":"533400"}]},{"label":"西藏自治区540000","value":"540000","children":[{"label":"拉萨市540100","value":"540100"},{"label":"昌都地区542100","value":"542100"},{"label":"山南地区542200","value":"542200"},{"label":"日喀则地区542300","value":"542300"},{"label":"那曲地区542400","value":"542400"},{"label":"阿里地区542500","value":"542500"},{"label":"林芝地区542600","value":"542600"}]},{"label":"陕西省610000","value":"610000","children":[{"label":"西安市610100","value":"610100"},{"label":"铜川市610200","value":"610200"},{"label":"宝鸡市610300","value":"610300"},{"label":"咸阳市610400","value":"610400"},{"label":"渭南市610500","value":"610500"},{"label":"延安市610600","value":"610600"},{"label":"汉中市610700","value":"610700"},{"label":"榆林市610800","value":"610800"},{"label":"安康市610900","value":"610900"},{"label":"商洛市611000","value":"611000"}]},{"label":"甘肃省620000","value":"620000","children":[{"label":"兰州市620100","value":"620100"},{"label":"嘉峪关市620200","value":"620200"},{"label":"金昌市620300","value":"620300"},{"label":"白银市620400","value":"620400"},{"label":"天水市620500","value":"620500"},{"label":"武威市620600","value":"620600"},{"label":"张掖市620700","value":"620700"},{"label":"平凉市620800","value":"620800"},{"label":"酒泉市620900","value":"620900"},{"label":"庆阳市621000","value":"621000"},{"label":"定西市621100","value":"621100"},{"label":"陇南市621200","value":"621200"},{"label":"临夏回族自治州622900","value":"622900"},{"label":"甘南藏族自治州623000","value":"623000"}]},{"label":"青海省630000","value":"630000","children":[{"label":"西宁市630100","value":"630100"},{"label":"海东市630200","value":"630200"},{"label":"海北藏族自治州632200","value":"632200"},{"label":"黄南藏族自治州632300","value":"632300"},{"label":"海南藏族自治州632500","value":"632500"},{"label":"果洛藏族自治州632600","value":"632600"},{"label":"玉树藏族自治州632700","value":"632700"},{"label":"海西蒙古族藏族自治州632800","value":"632800"}]},{"label":"宁夏回族自治区640000","value":"640000","children":[{"label":"银川市640100","value":"640100"},{"label":"石嘴山市640200","value":"640200"},{"label":"吴忠市640300","value":"640300"},{"label":"固原市640400","value":"640400"},{"label":"中卫市640500","value":"640500"}]},{"label":"新疆维吾尔自治区650000","value":"650000","children":[{"label":"乌鲁木齐市650100","value":"650100"},{"label":"克拉玛依市650200","value":"650200"},{"label":"吐鲁番地区652100","value":"652100"},{"label":"哈密地区652200","value":"652200"},{"label":"昌吉回族自治州652300","value":"652300"},{"label":"博尔塔拉蒙古自治州652700","value":"652700"},{"label":"巴音郭楞蒙古自治州652800","value":"652800"},{"label":"阿克苏地区652900","value":"652900"},{"label":"克孜勒苏柯尔克孜自治州653000","value":"653000"},{"label":"喀什地区653100","value":"653100"},{"label":"和田地区653200","value":"653200"},{"label":"伊犁哈萨克自治州654000","value":"654000"},{"label":"塔城地区654200","value":"654200"},{"label":"阿勒泰地区654300","value":"654300"},{"label":"自治区直辖县级行政区划659000","value":"659000"}]}]`
`<TreeSelect treeData={option}/>`
![qq 20160308105103](https://cloud.githubusercontent.com/assets/2075138/13590567/ce28bc5a-e51b-11e5-8469-47334860fab8.png)

**Comment by warmhug** [comment]
rc-tree-select 版本号是多少？请升级到最新版

**Comment by lomocc** [comment]
升级到 1.2.4 解决 ，谢谢！
