### ISSUE TITLE
input 能不能加一个自动获取焦点的方法或者属性，自己写方也没有解决这个问题

### ISSUE THREAD

**Issue by MarisWang** [ant-design/ant-design#11470]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能为用户提供更好的体验，同时有利于减少开发的工作 

### What does the proposed API look like?
有一个属性，例如 原本的 autoFocus = "autoFocus",或者autoFocus = true/flase  (default false)

**Comment by ilanus** [comment]
对不起，如果我的中文不好, 我正在使用翻译工具 .. 我不认为这个api是必要的 你应该使用 一个参考 请看演示: https://codesandbox.io/s/jjj686qwrw

**Comment by yesmeck** [comment]
支持 `autoFocus` 的。

**Comment by MarisWang** [comment]
![image](https://user-images.githubusercontent.com/39178648/43296154-317ed082-917c-11e8-944c-c2fdd07c9c3e.png)


this is what im facing now,i tried your code,but coming with this error

**Comment by ilanus** [comment]
@MarisWang could you share with me the full page code or invite me to repo so I can take a look?

**Comment by builtbyproxy** [comment]
This is because on mount the property current of a ref is undefined.

Test your ref is ok by placing it in a render. And as a hunch remove the current property and change line 40 to be:

this.textInput.focus();

**Comment by MarisWang** [comment]
@ilanus @builtbyproxy Thank you so much for your help, i have fixed this problem by    componentDidMount() {
    setTimeout(() => {
      this.input.focus();
    });
  };
its works now

**Comment by builtbyproxy** [comment]
@MarisWang Perfect!

I fixed it as well but couldnt for the life of me refind this issue: 
```
setTimeout(() => {
    this.input.focus();
}, 300);
```
