### ISSUE TITLE
FilterTreeNode filtered nodes are not bolded

### ISSUE THREAD

**Issue by lsunflower** [ant-design/ant-design#11479]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.4

### Environment
windows10 64bit  /  Google Chrome 68.0.3440.75

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x7rrn6kynw)

### Steps to reproduce
Enter "张三", the filter will be bolded, enter "zs", the filter will not load the display

### What is expected?
Filtered results are shown in bold

### What is actually happening?
Filtered results are not shown in bold

---
Make search support pinyin

**Comment by zombieJ** [comment]
use `treeNodeFilterProp` to highlight the match props.
