### ISSUE TITLE
DirectoryTree 不能用

### ISSUE THREAD

**Issue by wangkegui** [ant-design/ant-design#11486]
一用DirectoryTree，就报错
![image](https://user-images.githubusercontent.com/29109109/43314960-2071bcaa-91c7-11e8-9f80-d836d717bf31.png)
这是什么问题

**Comment by CandyBeauty** [comment]
我也遇到这个问题，求解决

**Comment by wangkegui** [comment]
这个只是antd的版本问题，那个是最新的api，老板没有，所以只需要更新antd到最新就行了

**Comment by gershonv** [comment]
同遇到这个问题。
