### ISSUE TITLE
select框数据量大的时候很卡

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#1148]
如题

**Comment by dyf2015** [comment]
能否增加一个定义最大条数的功能？

**Comment by benjycui** [comment]
> 能否增加一个定义最大条数的功能？

如果你是想限制最多显示多少条，自行裁剪数据就好。

**Comment by dyf2015** [comment]
意思是检索后显示前n条

发自我的 iPhone

**Comment by yiminghe** [comment]
var options=[1,2,3].map(()=><Option>)

<Select>{options}
