### ISSUE TITLE
DatePicker设置showTime为true，format="YYYY-MM-DD HH:mm"，打开日期面板，面板已默认高亮今天的日期，直接按确定按钮，当前日期的value没有显示在输入框上

### ISSUE THREAD

**Issue by nowkizzz** [ant-design/ant-design#11481]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在showTime为true,需要显示时分的情况下，点击面板有一个当天日期高亮，一般意味着默认当天已选中，期望直接点击确定按钮，就选择了该日期时间。

### What does the proposed API look like?
isSelectedToday 表示是否默认选中今天的按钮，并且点击确定就能将今天的数据输入到输入框上

**Comment by afc163** [comment]
Remain current interaction is better now.
