### ISSUE TITLE
Form.Item , extra 和 校验信息 同时 存在， 样式会乱

### ISSUE THREAD

**Issue by sqfbeijing** [ant-design/ant-design#11483]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.2

### Environment
mac chrome 最新版本， react 最新版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wznz9yvn6l)

### Steps to reproduce
https://codesandbox.io/s/wznz9yvn6l  点击check按钮 , extra 信息  和校验信息 重合了

### What is expected?
extra 信息  和校验信息  不重合， 上下布局来显示

### What is actually happening?
extra 信息  和校验信息 重合了

---
https://user-images.githubusercontent.com/12571054/43311844-26c166c2-91be-11e8-8fd7-de2ade1a61cf.png

**Comment by yesmeck** [comment]
Introduced by https://github.com/ant-design/ant-design/commit/8736b0a17e5fc990577cf6e69f75b9f698f7fb9f

**Comment by zombieJ** [comment]
Seems fixed in latest version. Close issue.
