### ISSUE TITLE
使用了3.7.0的级联选择器API ---fieldNames 3.6.6版本antd级联选择器不显示

### ISSUE THREAD

**Issue by qianxuemin** [ant-design/ant-design#11497]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.6

### Environment
mac 10.12.6   Google Chrome 版本 67.0.3396.99

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
使用3.6.6版本的antd级联选择器时，使用了API ---fieldNames 城市选择器不显示

### What is expected?
3.6.6版本兼容3.7.0版本的级联选择器

### What is actually happening?
使用3.6.6版本的antd级联选择器时，使用了新的API ---fieldNames 城市选择器不显示

**Comment by afc163** [comment]
See the changelog of 3.7.0: https://ant.design/changelog-cn#3.7.0
