### ISSUE TITLE
Cascader设置popupPlacement="bottomRight"时浮层方向不对

### ISSUE THREAD

**Issue by luolonghao** [ant-design/ant-design#1150]
当前：向左弹出子浮层，导致超出window，页面出现滚动条。

期望：向右弹出子浮层。

**Comment by afc163** [comment]
这个异常麻烦，向右弹出浮层，所有的东西都要调转方向。包括子菜单弹出方向，动画方向，箭头方向，文字排序方向。建议在设计层面尝试做一下妥协。

**Comment by luolonghao** [comment]
其实主要问题还不是方向，而是超出页面之后没办法滚动后查看，Windows系统下点击滚动条，浮层会自动关闭，影响功能的使用，Mac下用触摸板滚动所以没这个问题。这个能不能修复一下？

**Comment by afc163** [comment]
点击滚动条会触发 document click 事件？

**Comment by afc163** [comment]
http://stackoverflow.com/a/34805113

**Comment by afc163** [comment]
cascader 做了改动，现在简单的在选择后重新定位，整个浮层会向右弹。体验会怪一点，但可以解决超出文档窗口的问题。

**Comment by yiminghe** [comment]
这个后面细节最好完善下，right 时从右到左扩展菜单

**Comment by afc163** [comment]
涉及组件：

- [ ] Menu
- [ ] Cascader
- [ ] Dropdown

**Comment by afc163** [comment]
按 https://github.com/ant-design/ant-design/issues/1150#issuecomment-193733305 解决。
