### ISSUE TITLE
Add loading and onClick to file in upload fileList

### ISSUE THREAD

**Issue by pbrink231** [ant-design/ant-design#11503]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When grabbing a list from third party source would be nice to show the list as loading with a spinner.  set like all the other components with a prop on Upload of loading with default false.

Another addition I have here is an onClick on the file.  Currently in the UploadList it will only use a url string.  My problem is I want to get a temporary link to the file and then forward the person to that link since I do not have the link when I show the files (third party with authentication)

### What does the proposed API look like?
        <Upload {...options} loading={true}>
          <Button type="primary">
            <Icon type="upload" /> Click to Upload or Drop Files Here
          </Button>
        </Upload>

above will have the button displayed and usable.  Below the button will show the spinner if loading is true.

**Comment by afc163** [comment]
This could be resolved by https://github.com/ant-design/ant-design/pull/11002
