### ISSUE TITLE
Dynamic form additions and deletions, data with new, UI is not new

### ISSUE THREAD

**Issue by ivanberry** [ant-design/ant-design#11502]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
os version macOS HS 10.13.5 Beta, browser version Chrome 67.0.3396.99 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1v9166yzx7)

### Steps to reproduce
0. 新增两条或者三条记录
1. 分别为每一条记录增加数据（下拉选取)
2. 删除任意非最后一条数据

### What is expected?
数据和UI同步更新

### What is actually happening?
未同步更新

---
代码中通过两个数组来分别表示UI的展示和真是数据展示原因是无奈之举，本应该是操作相同的数组来更新数据，并触发render，但因antd会提示警告，不能存在表单域名有包含关系：a / a.b

**Comment by ldwonday** [comment]
https://codesandbox.io/s/lpqqo9ykmz
This is the right way to use the list field. But I think it is a bug of the form component!

**Comment by afc163** [comment]
@ivankravets Any conclusion could share?

**Comment by ivanberry** [comment]
@afc163 Just as @ldwonday comments, use a unique id to render the UI, but not use the map index especially in nest fields. May be you can implement the dynamic CURD example.

**Comment by WuJiY** [comment]
是有这个问题，所以用新的数组来作为表现层，但是问题来了。需要拖拉排序的时候一般是根据索引来的。所有感觉两难全。不知道有没有好的解决方案
