### ISSUE TITLE
RangePicker: 当我仅仅给结束时间设置初始值，点击选择的时候会报错:Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by Hills-V** [ant-design/ant-design#11509]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
antd 最新版本

### Reproduction link
[https://codepen.io/anon/pen/JBMPOa?editors=0010](https://codepen.io/anon/pen/JBMPOa?editors=0010)

### Steps to reproduce
<Form.Item label={fieldLabels.dateRange}>
       {getFieldDecorator('dateRange', {
              rules: [{ required: true, message: '请选择生效日期' }],
              initialValue: [undefined, moment()],
        })(
              <RangePicker placeholder={['开始日期', '结束日期']} style={{ width: '100%' }} />
        )}
</Form.Item>

### What is expected?
当我仅仅给结束时间设置初始值能够正常使用

### What is actually happening?
当我仅仅给结束时间设置初始值不能正常使用，会报错

**Comment by Hills-V** [comment]
who can help me ???

**Comment by chenshuai2144** [comment]
It is best to give a starting value.
What are you trying to achieve?

**Comment by Hills-V** [comment]
这是一个编辑页面，只有结束时间的情况是存在的，也是合理的

**Comment by afc163** [comment]
It was fixed now.
