### ISSUE TITLE
select onchange事件

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#1151]
select控件，用了getFieldProps之后，onchange不work了，是怎么回事，请问怎么解？

**Comment by Aggie123** [comment]
大概知道怎么回事了，getFieldProps默认是由onchange触发的，2个冲突了，把事件绑定在其它事件上应该就OK了

**Comment by Aggie123** [comment]
不好意思 刚看见 希望还有用
因为getFieldProps默认是由onchange事件触发的，所以2种方法:
1.将你的方法换个事件触发比如onselect
2.将antd的getFieldProps换个时间触发(具体字段介绍文档里有写，如果没找到可以告诉我发给你)

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/blob/develop-1.0.0/components/form/index.md#thispropsformgetfieldpropsid-options

**Comment by leica0** [comment]
非常感谢 后来仔细看了文档 已经解决了

<Select
  {...getFieldProps('currentCriteria',{'trigger':'onSelect'})}
  placeholder='Choose Criteria' onChange={this.selectCriteria}>
