### ISSUE TITLE
antd pro can not support multiple tabs

### ISSUE THREAD

**Issue by RivanLuo** [ant-design/ant-design#11512]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
we need to open multiple independent tab and different tabs are also edited at the same time

### What does the proposed API look like?
no idea

**Comment by yesmeck** [comment]
Please file issue to https://github.com/ant-design/ant-design-pro
