### ISSUE TITLE
checkbox Button Style

### ISSUE THREAD

**Issue by stevejiachen** [ant-design/ant-design#11524]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
similar to Radio Button style, the Checkbox also nice to have a button style for particular UI requirment

### What does the proposed API look like?
```jsx
import { Checkbox } from 'antd';
const CheckboxButton = Checkbox.Button;
const CheckboxGroup = Checkbox.Group;

function onChange(checkedValues) {
  console.log('checked = ', checkedValues);
}

ReactDOM.render(
  <div>
    <CheckboxGroup onChange={onChange} defaultValue={['Apple']}>
        <CheckboxButton value="Apple">Apple</CheckboxButton>
        <CheckboxButton value="Pear">Pear</CheckboxButton>
        <CheckboxButton value="Orange">Orange</CheckboxButton>
    </CheckboxGroup>
  </div>
, mountNode);
```

**Comment by afc163** [comment]
Sorry, our design system don't include this.

**Comment by stevejiachen** [comment]
@afc163 Hi, Thanks for the reply, Antd Radio component does support Button Style, so why the Checkbox doesn't? I've made a pull request for Checkbox, if you have time please have a look. Cheers

**Comment by afc163** [comment]
It is by designed, there is no checkbox button style in our design system.

**Comment by stevejiachen** [comment]
@afc163 ok, i see, thanks anyway
