### ISSUE TITLE
Space between Chinese charater in Popconfirm buttons

### ISSUE THREAD

**Issue by JHanLu** [ant-design/ant-design#11520]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
windows10, Chrome 62

### Reproduction link
[https://codepen.io/JHanLu/pen/mjpYGZ?editors=0010](https://codepen.io/JHanLu/pen/mjpYGZ?editors=0010)

### Steps to reproduce
```
  <Popconfirm title="Are you sure delete this task?" onConfirm={confirm} onCancel={cancel} okText="确定" cancelText="取消">
```

### What is expected?
okText shoule be "确认", cancelText shoule be "取消", exactly as same as what we put in 

### What is actually happening?
okText is "确 认", cancelText is"取 消", there is an extral space in charater

**Comment by yesmeck** [comment]
It's by design, see #5977

**Comment by JHanLu** [comment]
@yesmeck So the solution here is to add an invisible icon?

**Comment by JHanLu** [comment]
找到一个解决办法
`
<Popconfirm placement="bottom" okText=" 确认 " cancelText=" 取消 ">
`
```css
.ant-btn-two-chinese-chars {
     &:first-letter {
       letter-spacing: 0;
     }
}
```
