### ISSUE TITLE
TreeSelect, 当父节点下存在个别禁用的子节点，如果把这个父节点选中，能否判断为halfChecked?

### ISSUE THREAD

**Issue by antstudio-git** [ant-design/ant-design#11523]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
Chrome Latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://81zvx22v2.codesandbox.io/)

### Steps to reproduce
1. 江苏省节点下存在一个禁用的节点
2. 勾选江苏省，其他城市被勾选。禁用的没有勾选

### What is expected?
江苏省是halfChecked, 全国也是halfChecked。即禁用的子节点，不要排除到判断是否全部被选中的条件外

### What is actually happening?
全国和江苏省都被选中了。

**Comment by zombieJ** [comment]
被禁用的选项不参与任何勾选传导。此外，halfChecked 的值在非 checkStrictly 下是自动计算出来的，不能设置。

**Comment by zhangzhuang15** [comment]
所以，只能用 Tree 自己实现一个TreeSelect才能解决这个问题了吗 @zombieJ
