### ISSUE TITLE
Table组件：当指定scroll={{y:240}} 时，列数据渲染单元格的宽度出现问题

### ISSUE THREAD

**Issue by gzhou1976** [ant-design/ant-design#11527]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
Win10, 所有浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l4mz70m37q)

### Steps to reproduce
Table组件：当指定scroll={{y:240}} 时，表格的列单元格显示会错位
当指定Column的width后，就不会有问题

### What is expected?
列单元格不错位

### What is actually happening?
列单元格显示错位

**Comment by yesmeck** [comment]
> 当指定Column的width后，就不会有问题

目前的设计是需要指定宽度。
