### ISSUE TITLE
Progress进度条组件，在type=circle时，设置strokeColor不生效

### ISSUE THREAD

**Issue by myworking2012** [ant-design/ant-design#11539]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
win10， Chrome浏览器67版本

### Reproduction link
[https://ant.design/components/progress-cn/](https://ant.design/components/progress-cn/)

### Steps to reproduce
const warningColor = '#f5222d', commonColor = '#1890ff', successColor = '#52c41a';

let strokeColorVal  = commonColor ; 

if(currentSpace > AlarmPercent) strokeColorVal  = warningColor ; 

< Progress type="circle" percent={programPercent}  strokeColor={strokeColorVal} / >

### What is expected?
Progress进度条组件，在type=circle时，设置strokeColor可以生效

### What is actually happening?
Progress进度条组件，在type=circle时，设置strokeColor不生效;
通过查看源码发现，目前只有在type=line时，设置会生效。这个是不是可以优化一下。

**Comment by hon2a** [comment]
This is still relevant in version 3.10.0.

Real reproduction link, since my issue with full info was closed as duplicate: https://codepen.io/hon2a/pen/gBWOOX?&editors=001

**Comment by miminal** [comment]
I have the same issue. I need to customise the colour of a dashboard type progress bar but the source code only allows strokeColour to take effect for line progress bars. This should only be a very small modification in the source code:

- progress.tsx:141 strokeColor={(statusColorMap as any)[progressStatus]}
+ progress.tsx:141 strokeColor={strokeColor}

**Comment by hon2a** [comment]
Not as simple as that, if the current behavior should be retained unless `strokeColor` is specified, but still quite simple :)

**Comment by zombieJ** [comment]
Fixed in PR: https://github.com/ant-design/ant-design/pull/12587
