### ISSUE TITLE
怎么获取选中的checkbox的value ？

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#1153]

**Comment by afc163** [comment]
http://ant.design/components/checkbox/#demo-basic

https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question

**Comment by Aggie123** [comment]
？rude
好吧 我这样理解是，不像antd其它的表单控件，antd没有封装自己Checkbox的value获取方式,沿用原生方法，对吧

**Comment by afc163** [comment]
也可以这么理解，是直接传递上来的。

**Comment by Aggie123** [comment]
thx!
