### ISSUE TITLE
Tooltip stealing classes

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#11545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
macOS Mojave Public Beta, Chrome 67.0.3396.99 (Official Build) (64-bit)

### Steps to reproduce
I have a table with each row containing a button with tooltip:

```javascript
<Tooltip title={tooltipTitle}>
  <Button
    className="button-link table-deletion-button"
    onClick={handleClickMethod}
    disabled // This only happens when the disabled prop is set to true
  >
    <MyIcon name="escape_1" />
  </Button>
</Tooltip>
```

This is what I get in the HTML –– the `<span>` gets the button classes, instead of the button having them

![screen shot 2018-07-31 at 2 44 52 pm](https://user-images.githubusercontent.com/16444141/43460304-8a7ef124-94d0-11e8-9467-1df01ee6d3eb.png)

### What is expected?
Tooltip should not get its children classes

### What is actually happening?
Tooltip gets its children classes

**Comment by afc163** [comment]
It is for resolve tooltip or popover don't work on disabled elements issue.

You can find more information at https://github.com/ant-design/ant-design/pull/4865 https://github.com/react-component/tooltip/issues/18 https://github.com/mui-org/material-ui/issues/11601
