### ISSUE TITLE
Add a param to disable keyboard when using tabs

### ISSUE THREAD

**Issue by BaconZhang** [ant-design/ant-design#11549]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes I don't want users to change tab by using keyboard, but I can't find how to disable it now. Could you please add a switch to do this.

### What does the proposed API look like?
Maybe you could add a param for this component to do this

**Comment by afc163** [comment]
> Sometimes I don't want users to change tab by using keyboard

Why?

**Comment by BaconZhang** [comment]
For example, when I have Modals for different tabs, if I open a Modal at current tab, I should not allow user to change tab before closing this Modal. However, user could do this by using keyboard . So that means you can not change tab when Modal is open however you can do it by using keyboard at same time. In my opinion, this is not a good interactive mode, so I want to disable keyboard to solve this problem.

**Comment by jackple** [comment]
I also have similar problem, what can I do to reslove it?

**Comment by zombieJ** [comment]
https://codesandbox.io/s/o51jr9vp3q
