### ISSUE TITLE
关于Table组件中每行按钮的问题

### ISSUE THREAD

**Issue by jinjiaxing** [ant-design/ant-design#1154]
Table组件中，我每一条数据中都存在一个操作列，该列中 存在两个按钮，比如添加和删除 button

那么我点击这两个button的时候，如何能够得到该行的索引号和数据呢？

我看到Table中的onRowClick事件，是能得到数据的，但是这样我无法得到，我点击的是添加还是删除按钮了

关于这个问题如何解决

**Comment by afc163** [comment]
`onClick={this.onClick.bind(this, record, index)}`
