### ISSUE TITLE
how to make CheckboxGroup to use differ title/value?

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1155]
case:
1) use checkboxgroup
2) each checkbox has name
3) each checkbox  can have title:

Right now we can use only plain array, so it's not possible to get differ title.
i would like to get something like this:
```
{
'option1': formatMessage(messages.option1),
'option2': formatMessage(messages.option2),
'option3': formatMessage(messages.option3)
}
```
looks like right now we can use only:
```
['option1', 'option2', 'option3]
```

Am i right?

**Comment by benjycui** [comment]
Yep, `Checkbox.Group` doesn't support `title`, but `Checkbox` support. I think it is a defect.

**Comment by afc163** [comment]
Use `Checkbox` directly.

**Comment by plandem** [comment]
i can use Checkbox directly, but what the purpose of CheckboxGroup in that case? How it can be useful, if there is no way to set titles different from values?!

**Comment by afc163** [comment]
Maybe `<Checkbox.Group options={[{ value: 'xx', label: 'xx' }]} />` is necessary.

**Comment by plandem** [comment]
for me any way to use differ title/value for each checkbox is ok :) otherwise i just can't understand how CheckboxGroup can be useful :(

**Comment by afc163** [comment]
It is not, actually. :sweat_smile:

**Comment by Aggie123** [comment]
Would be great if Checkbox can support such kind of options, looking forward to this happening:
<Checkbox.Group options={[{ value: 'xx', label: 'xx' }]} />

Now, we can only use Checkbox with origin js to makes this work, below is how I does FYI:
`//bind checked array to one state of the component,like checkedArray as below
//then update the array state accordingly using origin js
onChange(e) {
  let checkedArray = this.state.checkedArray,
    index = checkedArray.indexOf(e.target.value);
  if (e.target.checked) {
    if (index = -1) {
      checkedArray.push(e.target.value);
    }
  } else {
    if (index > -1) {
      checkedArray.splice(index, 1);
    }
  }

  let newState = {};
  newState['checkedArray'] = checkedArray;
  this.setState(newState);
}`
