### ISSUE TITLE
Table组件scroll在x,y都设置的情况下,列头和内容没有对齐

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#11558]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
Google Chrome 66.0.3359.139

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ovmy3375xy)

### Steps to reproduce
比如给Table设置 scroll={{ x: 1600, y: 200 }}

### What is expected?
列头和内容对齐

### What is actually happening?
列头和内容不对齐

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header

<img width="715" alt="image" src="https://user-images.githubusercontent.com/507615/43517143-45fef9b4-95ba-11e8-83fa-4ce87cbe312d.png">

**Comment by McPatto** [comment]
If I copy this example, but don't put a certain width, the Columns does not align propertly.

ex: https://codesandbox.io/s/xz91mz8k7o

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/11822#issuecomment-435380556

Even if the width is set for each column, there is still this problem.

**Comment by yinlv** [comment]
我也遇到了这样的问题！
我认为是不是可以在表格内容创建和更新时，重新定义表头列的宽度？
also got this problem too!
i think this may have to resize table header column width,
after table body mounted or updated？

**Comment by chenmrU** [comment]
同样遇到这个问题，有没有解决方案啊

**Comment by ty-bt** [comment]
@chenmrU 没啥好办法, 我现在是 留一列不设width, 其他列都设置width

**Comment by VEMTK** [comment]
坑

**Comment by yinlv** [comment]
目前我临时解决了一下，在原有的 Table 组件包了一层，利用 headerCell 的渲染，强制设置了 th 元素的 min-width 和 max-width，现在测试起来表现良好。

**Comment by yoyo837** [comment]
@ty-bt 
> 没啥好办法, 我现在是 留一列不设width, 其他列都设置width

那你scroll设置x了吗

**Comment by yinlv** [comment]
> @ty-bt
> 
> > 没啥好办法, 我现在是 留一列不设width, 其他列都设置width
> 
> 那你scroll设置x了吗

我这里基于 antd 的 Table 封装了一个 CustomTable ， 额外提供了表头拖拽排序，隐藏显示，宽度设置，自动持久化设置到 redux(通过redux-persist持久化到localstorage)。同时还解决了自适应宽度支持滚动条，自适应高度支持滚动条。

目前工作太忙还没时间整理分享，实在着急的小伙伴可以找我先要代码看看。

**Comment by yoyo837** [comment]
能在y存在的时候响应式总宽并对齐列吗

**Comment by yinlv** [comment]
> 能在y存在的时候响应式总宽并对齐列吗

什么叫 Y 存在 ？？？

**Comment by yoyo837** [comment]
@yinlv scroll.y设置了值

**Comment by yinlv** [comment]
https://github.com/ant-design/ant-design/issues/11558#issuecomment-439838678
我已经把代码传到 github 上啦，有兴趣的大佬可以帮我修改下，我实在太忙了...

**Comment by yinlv** [comment]
目前代码功能上是没有问题的，主要是我用到的 redux-persist ， connect 高阶函数 combiner， 还有用了自己封装的 modal.dialog (可以用 modal.confirm 代替)。各位要用目前还需要自己改一下代码才行。

**Comment by yankeeguyu** [comment]
> @yinlv 你上传的代码太片段了，跑起来看不到效果。ClassNameX 这是什么？

有人解决了这个东西吗？

**Comment by yinlv** [comment]
@yankeeguyu ClassNameX 和 npm 里的 ClassNames 差不多，主要问题是你需要改改 css ，然后给 table 做一层高阶组件，通过 hook 把 column 里的 width 传到 render 的参数里去。这个问题我已经解决很久了。

**Comment by yinlv** [comment]
然后设置 column 的 render 里第一层的 span 或者 div 的 style = { maxWidth: width, minWidth: width } 这样就可以工整的对齐啦。
