### ISSUE TITLE
使用DatePicker组件后，界面上出现的年是中文，月是英文

### ISSUE THREAD

**Issue by sandm1227** [ant-design/ant-design#11556]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
antd@3.7.2

### Reproduction link
[http://ant-design.gitee.io/components/date-picker-cn/](http://ant-design.gitee.io/components/date-picker-cn/)

### Steps to reproduce
<DatePicker style={{ width: '200px' }} />
![default](https://user-images.githubusercontent.com/25194203/43507799-a36ef73a-95a0-11e8-893a-70278ec2515f.png)

### What is expected?
默认情况，年月全是中文

### What is actually happening?
年是中文，月是英文

**Comment by afc163** [comment]
https://ant.design/components/locale-provider/

**Comment by sandm1227** [comment]
没有变化
代码：
![default](https://user-images.githubusercontent.com/25194203/43509109-44dcaff6-95a4-11e8-8bd8-980458ab9c1c.png)
![default](https://user-images.githubusercontent.com/25194203/43509133-57c48eea-95a4-11e8-9383-e825712f8b57.png)

结果：![default](https://user-images.githubusercontent.com/25194203/43509082-362150fc-95a4-11e8-97a1-725823a4b55d.png)

**Comment by sandm1227** [comment]
我把moment也更新到最新版本就可以了，多谢啦！！

**Comment by dqm926** [comment]
你好，我也碰到了这个问题了，我的版本是3.10.1，用了antd/lib/date-picker/locale/zh_CN，但是没效果，moment也更新到了最新版本，问题还是存在，希望得到你的帮助！谢谢！

**Comment by dqm926** [comment]
你好，我也碰到了这个问题了，我的版本是3.10.1，用了antd/lib/date-picker/locale/zh_CN，但是没效果，moment也更新到了最新版本，问题还是存在，希望得到你的帮助！谢谢！
