### ISSUE TITLE
antd样式加载和自定义webpack配置冲突了

### ISSUE THREAD

**Issue by wklc2014** [ant-design/ant-design#11554]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
node: v8.11.2；npm: v6.2.0

### Reproduction link
[https://github.com/wklc2014/spa-for-all/tree/master/learn-react](https://github.com/wklc2014/spa-for-all/tree/master/learn-react)

### Steps to reproduce
yarn start

### What is expected?
配置既支持自定义webpack配置，又支持antd的样式

### What is actually happening?
实际antd的样式类名被改掉了

---
自定义了webpack配置文件，增加了 less文件的处理，配置如下：
Customized the webpack configuration file, added the processing of the less file, configured as follows:
````
{
	test: /\.(less|css)$/,
	use: [
	  'style-loader',
	  {
		loader: 'css-loader',
		options: {
		  camelCase: true,
		  modules: true,
		  importLoaders: 2,
		  localIdentName: '[name]--[local]--[hash:base64]'
		}
	  },
	  {
		loader: 'postcss-loader',
		options: {
		  config: {
			path: path.resolve(__dirname, 'postcss.config.js')
		  }
		}
	  },
	  {
		loader: "less-loader",
		options: {
		  javascriptEnabled: true
		}
	  }
	]
},
````
配置中，我用 postcss处理浏览器兼容性，用了css-loader处理css，并开启了 modules 功能，定义了 localIdentName，由此导致了给 antd 的样式文件中的类名也改掉了。
In the configuration, I used postcss to handle browser compatibility, css-loader to handle css, and enabled the modules function, which defined localIdentName , which caused the class name in the antd style file to be changed.
**请问有什么办法分开对待吗？**

目前我的处理是：给自己的less配置处理，增加include属性，仅对 src中项目本身源码做自定义处理，
At present, my processing is: to configure the processing of my less, add the include attribute, and only customize the source code of the project itself in src.
`include: path.resolve(__dirname, 'src'),`
单独给antd一套处理：
Give antd a separate treatment:
````
// 单独给 antd 样式处理
{
	test: /\.(less|css)$/,
	include: path.resolve(__dirname, 'node_modules'),
	use: [
	  'style-loader',
	  'css-loader',
	  {
		loader: "less-loader",
		options: {
		  javascriptEnabled: true
		}
	  }
	]
},
````

**Comment by yesmeck** [comment]
可以搜索下过往的 issue
