### ISSUE TITLE
Check parent node or a child node in TreeSelect's search result won't work WHEN there is already a child node been checked

### ISSUE THREAD

**Issue by gtopia** [ant-design/ant-design#11559]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
Windows 7，Chrome 68

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
1. Go to web page `https://ant.design/components/tree-select-cn/`, find the checkable multiple select demo
2. Check "Child Node3"
3. Search "0-1"
4. Check  "Child Node4" (Check "Node2" or "Child Node5" can also reproduce this issue)
![image](https://user-images.githubusercontent.com/8113851/43518302-3783f0de-95be-11e8-88d9-7c00441d3db2.png)

### What is expected?
1. "Node2" in half-checked status. 
2. "Child Node4" be checked.

### What is actually happening?
1. "Node2" is not in half-checked status. 
2. "Child Node4" cannot be checked. There is a console error reported as blow.
![image](https://user-images.githubusercontent.com/8113851/43518249-10b09462-95be-11e8-8d44-134c2006b19d.png)

**Comment by zombieJ** [comment]
Fixed `rc-tree-select@2.0.12`: https://codesandbox.io/s/8x9qjj06l0
