### ISSUE TITLE
If the Table is custom components, Setting the fiexd property for the column will appear bug

### ISSUE THREAD

**Issue by yucccc** [ant-design/ant-design#11560]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k25nlqkzxr)

### Steps to reproduce
见链接

### What is expected?
x

### What is actually happening?
If the Table is custom components, Setting the fiexd property for the column will appear bug.
给表格自定义了components 同时给components设置fixed 则会导致页面布局出错

**Comment by afc163** [comment]
Yes, it is not supported now and I don't think we are able to support it cause we depend on a very complicated body wrapper in fixed-columns Table.
