### ISSUE TITLE
table组件，期望每一列宽度支持拖拉

### ISSUE THREAD

**Issue by enjoy-wind** [ant-design/ant-design#11564]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
浏览器版本

### Reproduction link
[http://ant-design.gitee.io/components/table-cn/](http://ant-design.gitee.io/components/table-cn/)

### Steps to reproduce
无

### What is expected?
提供功能

### What is actually happening?
暂无

**Comment by afc163** [comment]
http://react-component.github.io/table/examples/column-resize.html
