### ISSUE TITLE
export FilterDropdown 组件吧

### ISSUE THREAD

**Issue by cathy-zhao** [ant-design/ant-design#11579]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table 控件目录下有一个 FilterDropdown 组件，有一定的通用性

### What does the proposed API look like?
export { FilterDropdown } from 'antd'

**Comment by afc163** [comment]
You can try to custom Dropdown.
