### ISSUE TITLE
Carousel 在使用 beforeChange 时点击 dot 不能跳转

### ISSUE THREAD

**Issue by colmugx** [ant-design/ant-design#11570]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Steps to reproduce
beforeChange = (_, next) => this.setState({ currentIndex: next })

### What is expected?
图片可以正常跳转

### What is actually happening?
值更新了，图片无法跳转

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/issues/1216

**Comment by cardiv** [comment]
Seems like _react-slick_ is not maintained anymore. No responses to issues and no merged pull requests since Juli. Maybe fork and maintain it separately? The community seems active with issues and pull requests to help maintain.

**Comment by zombieJ** [comment]
Looks like when parent render will cause react-slick re-render which makes slide witch stop: https://codesandbox.io/s/01lprp1n0l

**Comment by yoyo837** [comment]
react-slick release version 0.23.2
