### ISSUE TITLE
Select组件能否单独reset

### ISSUE THREAD

**Issue by Yuliang-Lee** [ant-design/ant-design#1157]
除了包含在Form中调用resetFields来重置,能否单独重置?因为现在需要使用到select的onChange来触发一些行为，如果包含在form中会使onChange失效

**Comment by benjycui** [comment]
`Select` 的 `value` 是受控的。

**Comment by yiminghe** [comment]
resetFields(fields: string[])

**Comment by Yuliang-Lee** [comment]
@yiminghe 这个方法我看文档知道了,但是这个需要使用form的getFieldProps绑定到Select上,这样select的onChange就没法触发了,我需要用到onChang。benjycui说的value是一种方法，我只是想问问Select有没有类似reset()的方法提供出来。
