### ISSUE TITLE
Ability to use Cascader in HeaderSearch instead of AutoComplete

### ISSUE THREAD

**Issue by salarzobir** [ant-design/ant-design#11577]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use Cascader instead of AutoComplete in HeaderSearch, but cannt change it easily.

My scenario is:

1. When user selects item from Cascader popup i will submit Cascader value to my search api.
2. If user start typing not numeric in Cascader i will use showSearch prop and search in items.
3. If user start typing numbers i will not show popup and i will submit the text value written in Cascader's input element to api.
Can you help me for this please?

### What does the proposed API look like?
```javascript
<Cascader
          key='Cascader'
          className={inputClass}
          value={value}
          onChange={this.onChange}
          options={this.props.dataSource}
          showSearch={this.filter()}
          notFoundContent=''
        >
          <Input
            placeholder={placeholder}
            ref={node => {
              this.input = node;
            }}
            onKeyDown={this.onKeyDown}
            onBlur={this.leaveSearchMode}
          />
</Cascader>
```

**Comment by afc163** [comment]
I suggest using AutoComplete in your scenario if it does not fit, I am afraid you have to write your owner component.
