### ISSUE TITLE
被 Form.create 包裹后的组件，在父组件中无法通过 this.refs 调用

### ISSUE THREAD

**Issue by tinyhill** [ant-design/ant-design#1158]
rt

**Comment by benjycui** [comment]
首先你想用 `ref` 作甚

**Comment by benjycui** [comment]
建议先看下 http://doc.zengrong.net/smart-questions/cn.html

**Comment by yiminghe** [comment]
form.getFieldInstance

**Comment by djllhs** [comment]
这个坑我也遇到过几次，一直没找到方法。最后就是子组件用回调函数把this传回父组件，然后在父组件中获取子组件的this，调用其自定义方法
