### ISSUE TITLE
Drawer 使用了 css 属性“pointer-events ”，但是这个属性在IE10 上并不支持,IE 10 not support pointer-events

### ISSUE THREAD

**Issue by bdDandelion** [ant-design/ant-design#11583]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
win7 IE10

### Reproduction link
[https://ant.design/components/drawer-cn/#header](https://ant.design/components/drawer-cn/#header)

### Steps to reproduce
在IE10上面打开，antd 官网 Drawer页；
打开、关闭一个Drawer ，页面内容会被div.ant-drawer-mask 挡住，无法操作页面

### What is expected?
在IE10/9 关闭Drawer后可以操作页面

### What is actually happening?
在IE10/9 关闭Drawer后不可以操作页面

**Comment by jljsj33** [comment]
😓

**Comment by jljsj33** [comment]
这玩意要在 jq 里用。。。我改了一下, 用 display 了....@afc163

**Comment by afc163** [comment]
需要把 antd 里的样式同步改掉。

**Comment by afc163** [comment]
@bdDandelion Why closing it?
