### ISSUE TITLE
upload组件如何实现只上传一个文件，如果再次选择文件覆盖之前选择的

### ISSUE THREAD

**Issue by LJJCherry** [ant-design/ant-design#11580]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
限定只上传一个文件

### What does the proposed API look like?
有一个限定文件上传个数的属性

**Comment by afc163** [comment]
https://ant.design/components/upload-cn/#components-upload-demo-fileList

**Comment by jamesltesim02** [comment]
?? 然后呢? 这个例子上说明了?
