### ISSUE TITLE
After set RangePicker's mode to ['month', 'month'], choose the second panel can't close the panel

### ISSUE THREAD

**Issue by ghostflow** [ant-design/ant-design#11586]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
mac os / chrome / react 16.4.1

### Reproduction link
[http://ant-design.gitee.io/components/date-picker-cn/](http://ant-design.gitee.io/components/date-picker-cn/)

### Steps to reproduce
1. set RangePicker's mode to ['month', 'month']
2. choose startMonth
3. choose endMonth

### What is expected?
the rangepicker should fade out 

### What is actually happening?
it's still there.
when I click the blank space,it disappeared.

---
in the situation, only onPanelChange triggered.onChange, onCalendarChange does not triggered

**Comment by ghostflow** [comment]
you can confirm it at the official docs.
the Controlled Panels demo

**Comment by jrschumacher** [comment]
@afc163

**Comment by jrschumacher** [comment]
@tcatche is this something which I need to fix in my code or is it related to ant/rc-datepicker?

**Comment by tcatche** [comment]
> @tcatche is this something which I need to fix in my code or is it related to ant/rc-datepicker?
The problem seems that a bug that onChange event can't triggered when use `mode="year"` or `mode="month"`

**Comment by afc163** [comment]
It is not a bug, `<DatePicker mode="year" />` don't equal to `<YearPicker />`, you guys can trace https://github.com/ant-design/ant-design/issues/4524 for further move.

**Comment by Aladingding** [comment]
<LocaleProvider locale={zhCN}>
 {
 getFieldDecorator(field)( 
   <DatePicker
     placeholder={ placeholder || '请选择年份' }
     locale={ zhCN }
    // value={ this.state.time }
    open={ this.state.yearStartShow } 
    mode='year'
    format='YYYY' 
    // onChange={ this.handleChange } 
    onOpenChange={ this.handleOpenChange }  
    onPanelChange={ this.handlePanelChange } /> 
 } 
</LocaleProvider>

do like this ,you will fix this bug, combine use onOpenChange and onPanelChange （maybe you need onFocus）

tks, 一江西流 [关于antd 日期组件只选择年份，设置mode=year无法获取value的解决办法](url)

四个方法并用一定能完美实现你的需求，哈哈哈，官方说，你既然都单选了，为什么不用下拉框，说的好有道理，我竟无言以对
@afc163

**Comment by afc163** [comment]
@Aladingding https://github.com/ant-design/ant-design/pull/16984
