### ISSUE TITLE
Storybook doesn't understand import on demand

### ISSUE THREAD

**Issue by devautor** [ant-design/ant-design#11603]
I have followed [instructions](https://ant.design/docs/react/use-with-create-react-app) here to get antd working fine with **CRA**. But while using it from **storybook**, I was getting an **error** as: `Build fails against a mixin with message Inline JavaScript is not enabled. Is it set in your options?` I had **fixed** that following suggestions on an issue I raised [here](https://github.com/storybooks/storybook/issues/3949). 

Now, **storybook** understands **antd** **but not importing components on demand**. Is babel has to be configured separately for storybook? 

1. On using 
```import { Button } from "antd";```
I get this:
![image](https://user-images.githubusercontent.com/26021293/43663118-e5a04f0a-9785-11e8-81ab-507c837897d4.png)

2. On using
```
import Button from "antd/lib/button";
import "antd/lib/button/style";
```
I get:
![image](https://user-images.githubusercontent.com/26021293/43663154-01e62414-9786-11e8-9f63-72309be8cc24.png)

### Dependency: "antd": "^3.7.3"

I have been stuck (again) with this for quite long hours googling things, any help is appreciated. Thanks!

**Comment by tomasfrancisco** [comment]
@devautor Have you found any solution on this?
I think I have exactly the same problem as you.

**Comment by cheickmec** [comment]
@tomasfrancisco and @devautor , I just provided the solution to this [here](https://stackoverflow.com/a/53490766/7566465)

**Comment by finaxar-arthur** [comment]
I still get this issue on Storybook 5
