### ISSUE TITLE
antd的Modal组件的确认和取消按钮可以不显示吗？

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#1160]
antd的Modal组件的确认和取消按钮可以不显示吗？比如，我想用子组件表单的确认，取消按钮

**Comment by afc163** [comment]
footer

**Comment by Aggie123** [comment]
great!

**Comment by luats** [comment]
@afc163 能只要取消按钮，隐藏掉确认按钮吗？

**Comment by weijiqiang1024** [comment]
footer允许的值有些？能动态的设置footer显示和隐藏吗？

**Comment by weijiqiang1024** [comment]
footer允许的值有些？能动态的设置footer显示和隐藏吗？@afc163

**Comment by weijiqiang1024** [comment]
已解决 
 footer={this.state.unitTitle === 'unitDetail' ?null: [
                            <Button key="back" size="large" onClick={this.handleUnitCancel}>取消</Button>,
                            <Button key="submit" type="primary" size="large" loading={this.state.loading} onClick={this.addUnitSubmit}>确定</Button>
                        ]}

**Comment by weijiqiang1024** [comment]
已解决  footer={this.state.unitTitle === 'unitDetail' ?null: [<Button key="back" size="large" onClick={this.handleUnitCancel}>取消</Button>,<Button key="submit" type="primary" size="large" loading={this.state.loading} onClick={this.addUnitSubmit}>确定</Button> ]}

**Comment by weijiqiang1024** [comment]
已解决  https://design.alipay.com/develop/web/components/modal/
