### ISSUE TITLE
Mention 初始化 马上触发onChange事件

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design#11619]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lwvm5rx87)

### Steps to reproduce
初始化

### What is expected?
Mention 初始化 不触发onChange事件

### What is actually happening?
Mention 初始化 马上触发onChange事件

**Comment by BruinK** [comment]
去掉事件函数的圆括号，如果你需要传递参数的话，就用剪头函数把事件函数包一下。
