### ISSUE TITLE
Confirm dialog flipped footer buttons

### ISSUE THREAD

**Issue by kingbreddo** [ant-design/ant-design#11622]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
People doesn't always read the text in the confirmation dialog. So they automatically click on the button that's highlighted (The primary colored one).

So it would be nice to have the option to flip those button of position and color. So that the user automatically clicks on the cancel button.
The user will then read the text in the confirmation. And will think of he/she will proceed with the risk behind it.

### What does the proposed API look like?
I think a good way to solve this is to add a 'flipButtons' property in the ModalFuncProps. And when this is true the buttons will flip from position.

In the confirm.tsx you can check if the flipButtons is true and place the cancel button after the ok button. And add the primary color to it.

**Comment by yutingzhao1991** [comment]
How about to use `okButtonProps` and `cancelButtonProps` for your require?

**Comment by kingbreddo** [comment]
If you using the normal modals it would be a way to change the color of the buttons. But with the ```*ButtonProps``` it's not possible to change/flip the position of the button.

And for the confirm, warning, success dialogs you cannot use the ```*ButtonProps```.
Those dialogs depend on a different component then the normal Modal.
(https://github.com/ant-design/ant-design/blob/master/components/modal/confirm.tsx) 

So ```*ButtonProps``` is not a option to fix this issue. maybe you know a trick with it to accomplish the task. 
But I don't see one at the moment

**Comment by afc163** [comment]
We can make `okButtonProps` and `cancelButtonProps` works with `Modal.xxxx` too, @kingbreddo could you help us to make it happen by sending a PR?

**Comment by kingbreddo** [comment]
@afc163 That is good. I will try to implement the functionality. And where should I describe the functionality that the the buttons are mapped  [Ok] [Cancel]   instead of   [Cancel] [Ok]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/12425
