### ISSUE TITLE
TextArea does not support size property like the other form elements

### ISSUE THREAD

**Issue by Gyokur0** [ant-design/ant-design#11624]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
react: 16.4.2, antd: 3.8.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ywz1nv4v8j)

### Steps to reproduce
Add TextArea element to component, add size prop and set it to a valid value like 'large'

### What is expected?
The font size should larger or smaller depending on the prop value, and should match other form elements

### What is actually happening?
The size stays the same

---
I guess that the Input.Search element also misses the size property (Just by looking at the typedefinitions)

**Comment by afc163** [comment]
Yep, it is by designed.

**Comment by afc163** [comment]
```
<TextArea rows={2} />
```

Try use `rows` to make it higher than one-line Input at least.

**Comment by Gyokur0** [comment]
The main problem with "large" is the font-size
(not the number of rows). 

I can work around this issue myself with css, but I'm still convinced that all inputs should work the same way and support the size (small | default | large) property.

Can you give me a technical explanation why this is not implemented?

**Comment by afc163** [comment]
IMO, TextArea should not be used as one line just like Input, it should be always two lines high at least.

**Comment by Gyokur0** [comment]
Ok, I understand you point of view. 
I'm my project the fields are {minRows:1, maxRows:8}, 
From a usability point minRows:2 would be easier to discover the textbox,
but the font sizes would still not match:

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7y5xr2yrzq)

**Comment by nodkrot** [comment]
+1 api to inputs should be consistent. TextArea should support `size="large"`. This issue is not about multiline or autoresize capabilities. It is about the font-size.

**Comment by SilencerWeb** [comment]
+1

**Comment by indiejoseph** [comment]
+1

**Comment by daniel-simon** [comment]
+1. Running into the inconsistent font size problem right now. I'm not sure why this issue is closed.

**Comment by robinvdv12** [comment]
+1 also running into this issue. IMO the font-size of all Inputs should work the same way.

**Comment by ysbakker** [comment]
Issue still exists. Manually adding `ant-input-lg` is the hotfix for now but that's not ideal.
