### ISSUE TITLE
Upload组件，从文件列表删除时能否触发onChange

### ISSUE THREAD

**Issue by azurefang** [ant-design/ant-design#11623]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
同时使用Form和Upload, 需要对Upload里的文件列表进行自定义校验，添加文件的时候一切正常， 但是删除的时候由于不会触发onChange, validator默认不会执行，导致此时应该校验通过的场景报错的文字不会消失。尝试把onRemove加到validateTrigger, 但是event里面没有剩下的文件列表。或者有其他的实现方式吗，我没有想到。

### What does the proposed API look like?
Upload组件，从文件列表删除时能否触发onChange
或者 onRemove的event中能有剩余的fileList

**Comment by azurefang** [comment]
看了下源码，改下onRemove就行了。

**Comment by afc163** [comment]
@azurefang 来个 PR？

**Comment by afc163** [comment]
> Upload组件，从文件列表删除时能否触发onChange

实测会触发。

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/507615/43834858-55865fb6-9b42-11e8-951d-1ca8a4f0daeb.png">
