### ISSUE TITLE
drawer 建议增加 keyboard - esc 关闭

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#11628]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
和modal一样，esc关闭

### What does the proposed API look like?
keyboard={true}

**Comment by frewillems** [comment]
This should be implemented in the components. Esc should trigger an onClose callback if this is set. Also valid for the drawer component for example.

**Comment by afc163** [comment]
@jljsj33

**Comment by jljsj33** [comment]
这个 @chenshuai2144 不是有整过吗？？PR 还发在那。。

**Comment by afc163** [comment]
@jljsj33 帮忙搞完吧

**Comment by chenshuai2144** [comment]
merge 一下就就好了，主要是 prettier 风格问题 后来我们已经全部转向 prettier

**Comment by jljsj33** [comment]
@chenshuai2144 我信你个鬼。。。

**Comment by jljsj33** [comment]
drawer: ~1.9.0

**Comment by afc163** [comment]
@jljsj33 发个 MR 到 feature 分支上。
