### ISSUE TITLE
TypeError: Cannot read property 'ownerDocument' of undefined

### ISSUE THREAD

**Issue by songyanbo** [ant-design/ant-design#11620]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
mac

### Reproduction link
[http://ant-design.gitee.io/components/tabs-cn/](http://ant-design.gitee.io/components/tabs-cn/)

### Steps to reproduce
npm run build

### What is expected?
success

### What is actually happening?
error

**Comment by pheadra** [comment]
me too

**Comment by afc163** [comment]
Duplicate of #11612
