### ISSUE TITLE
Table column is not aligned with fixed header in Firefox

### ISSUE THREAD

**Issue by fayhy** [ant-design/ant-design#11635]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
Windows, Firefox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3ol50nrk3)

### Steps to reproduce
1. output `Open in New Window`  
1. click `query` button  
1. scroll to right  
1. reload current page (F5)  
1. click `query` button  

### What is expected?
header and cell align  
![image](https://user-images.githubusercontent.com/35906690/43756572-e43737cc-9a47-11e8-9ed7-b53a9d18badd.png)

### What is actually happening?
header is displayed as same as before reload   
cell is displayed as same as Initially   
![image](https://user-images.githubusercontent.com/35906690/43756417-253d228c-9a47-11e8-9d86-dca48edd6ae3.png)

---
IE and Chrome is fine

**Comment by fayhy** [comment]
@yesmeck @afc163 帮忙看看问题吧。。。

**Comment by afc163** [comment]
着急的话，可以排查一下给我们 PR~ 现在 open issues 很多确实精力不够
