### ISSUE TITLE
Table use scroll prop cause strange style.

### ISSUE THREAD

**Issue by LinFeng1997** [ant-design/ant-design#11638]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
Mac、Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/71z0p0m876)

### Steps to reproduce
Add Table scroll prop `{{ y: 100 }}`

### What is expected?
abnormal table style 

### What is actually happening?
The Table seems to have been suppressed by some mysterious power.

---
v3.8.0

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-header

<img width="467" alt="image" src="https://user-images.githubusercontent.com/507615/43758352-6bb3a6c6-9a4e-11e8-9e04-1c8c781b772f.png">
