### ISSUE TITLE
'fileList' cannot be assigned on redux while using Upload component

### ISSUE THREAD

**Issue by Renderz** [ant-design/ant-design#11639]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.0

### Environment
system :macOS 10.13.6; browser :chrome 68.0.3440.84; 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y0k68mr3vx)

### Steps to reproduce
1. when click 'upload', the 'fileList' suppose to be assigned to redux(dva-core with dva-immer) 
2. the error will be showed on this step: 'Cannot assign to read only property 'percent' of object '#<Object>'

### What is expected?
The onChange callback supposed to be invoked 3 times as same as 'fileList' be assigned to redux 3 times. 

### What is actually happening?
While which successfully assigned at first time and then throw an error 'Cannot assign to read only property 'percent' of object '#<Object>',
when i remove using dva-immer, everything goes fine

**Comment by afc163** [comment]
You should file issue in dva-immer.
