### ISSUE TITLE
InputNumber 中加入getFieldProps时，无法输入小数

### ISSUE THREAD

**Issue by huanhuan129129** [ant-design/ant-design#1163]
**InputNumber 中加入getFieldProps时，无法输入小数，只有加入step后，才可以**

代码如下：
<InputNumber  style={{width: 200}} min={0} max={max} {...getFieldProps(name, {
          initialValue: value,
          rules: [{
            required: true,
            type: 'number',
            message: '请输入正确的名称',
          }],
        })}/>

**Comment by afc163** [comment]
需要设置 step ，才可以输入小数。

不加 `getFieldProps` 时也不应该能输入。

**Comment by huanhuan129129** [comment]
官网中的例子中，没有getFieldProps是可以输入小数的。。主要在使用form封装的时候，在componentWillReceiveProps时，对小数进行处理时，是使用step获取的小数点后的位数的。
