### ISSUE TITLE
ant form validateFields指定一组值校验时，历史的error不会清除

### ISSUE THREAD

**Issue by nai6514531** [ant-design/ant-design#11632]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
osx chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n91lw4x4np)

### Steps to reproduce
点击下一步。会随机校验输入框，但是却不清除上一步的错误状态。

### What is expected?
点击下一步。会随机校验输入框，期望清除上一步的错误状态。

### What is actually happening?
点击下一步。会随机校验输入框，但是却不清除上一步的错误状态。

**Comment by chenshuai2144** [comment]
demo is true

**Comment by nai6514531** [comment]
@chenshuai2144 这是bug嘛还是我的写法有问题

**Comment by nai6514531** [comment]
@chenshuai2144 还是说这是组件的正确行为，但是我觉得应当是每次我传入前把历史的error清除掉再进行校验吧。

**Comment by chenshuai2144** [comment]
你改掉错误不就消失了。

**Comment by nai6514531** [comment]
@afc163 有时间帮看下这个demo

**Comment by chenshuai2144** [comment]
https://github.com/react-component/form
可以给这个里面 pr 一下, resetFieldsError
