### ISSUE TITLE
 Maximum update depth exceeded or infinite cycle

### ISSUE THREAD

**Issue by VesperDev** [ant-design/ant-design#11642]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.2

### Environment
MacOS

### Reproduction link
[https://easypay-a5c8c.firebaseapp.com/restaurante | https://bitbucket.org/amarecoding/easypay-web](https://easypay-a5c8c.firebaseapp.com/restaurante | https://bitbucket.org/amarecoding/easypay-web)

### Steps to reproduce
in the restaurant view click on the edit button, open the console to see more information

### What is expected?
that the this.props.form.setFieldsValue function works only once

### What is actually happening?
 const { name, direction, telephone } = this.props.objRest
 
this.props.form.setFieldsValue({ name, direction, telephone })
when executing this is cycled and I have the error of Maximum update depth exceeded

setTimeout(() => {
     this.props.form.setFieldsValue({ name, direction, telephone })
 }, 100)

an infinite cycle is generated

---
https://easypay-a5c8c.firebaseapp.com/restaurante   email:vesper.dev@hotmail.com password: demodemo22
https://bitbucket.org/amarecoding/easypay-web          /src/containers/Restaurante/

**Comment by afc163** [comment]
RTFM

<img width="927" alt="image" src="https://user-images.githubusercontent.com/507615/43760218-076f0f92-9a54-11e8-915a-6d90cb181029.png">

**Comment by VesperDev** [comment]
then where can I put the setFieldsValue when I call it from another component.

the only thing I have to do is pass data to a form, nothing else

**Comment by GTVanitha** [comment]
> then where can I put the setFieldsValue when I call it from another component.
> 
> the only thing I have to do is pass data to a form, nothing else

Check the prevProps and do the setFieldsValue
[Sanbox Link](https://codesandbox.io/s/antd-reproduction-template-olged?fontsize=14&hidenavigation=1&theme=dark)

**Comment by GTVanitha** [comment]
> Hello @VesperDev. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.

Sandbox link(https://codesandbox.io/s/antd-reproduction-template-olged?fontsize=14&hidenavigation=1&theme=dark)
