### ISSUE TITLE
Icon usage should be unify

### ISSUE THREAD

**Issue by ruoqianfengshao** [ant-design/ant-design#11645]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Antd provides custom theme scheme，but icon usage in antd present disunity，some with unicode，otherwise with classname，it's totally confused and increase the difficulty of customize theme.

### What does the proposed API look like?
All usage of icon with classname.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/11322
