### ISSUE TITLE
Missing pop-up assembly

### ISSUE THREAD

**Issue by chenzezhang** [ant-design/ant-design#11657]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Comparative public

### What does the proposed API look like?
{
    displayIcon: Boolean, // isShow icon
    icon: String,   //icon
    title: String,   // title
    titletype: true,
    subtitle: '',  // subtitle
    content: '',
    button: ['知道了', {callBack: Func, className: String, content: String}] ,
    callback: function
}

**Comment by afc163** [comment]
Cannot understand it.
