### ISSUE TITLE
改进了一下table组件可伸缩列例子可传入百分比宽度，但是出现内容宽度比table-wrapper宽度短的问题

### ISSUE THREAD

**Issue by suiyi8760** [ant-design/ant-design#11669]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
macOS10.13.6,chrome66,react@16.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qkm8yx22kq)

### Steps to reproduce
在列数多于5列时出现该问题，

### What is expected?
table内容能填满table

### What is actually happening?
内容宽度会比table-wrapper少5到10px不等，造成table右上角出现缺口(table的border-top较长)

**Comment by zombieJ** [comment]
你计算的值带小数点了，被游览器省略了。取整就好了： https://codesandbox.io/s/72wxxxn8xq

**Comment by suiyi8760** [comment]
@zombieJ Appreciate. 把小数这个坑忽略了
