### ISSUE TITLE
Form 没有提交按钮的时候，键盘Enter无法触发onSubmit

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#11663]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
chrome61

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9okpzy186y)

### Steps to reproduce
```
const showSubmit = false;
const showMore = true;
```

修改这两个值，任何一个输入框获得焦点的时候，按键盘Enter
***只有一个输入框的时候，不需要button，也能键盘enter触发***
多个表单项的是，必须要button，才能键盘enter触发

```
onSubmit = e => {
    e.preventDefault();

    message.info("提交表单");
```

### What is expected?
在Modal中显示的表单，都是没有提交按钮的，按enter键能提交表单

### What is actually happening?
必须要有一个button htmlType="submit"

**Comment by zlab** [comment]
官方例子
弹出层中的新建表单，无法按键盘enter提交

https://ant.design/components/form-cn/#components-form-demo-form-in-modal

**Comment by zlab** [comment]
放一个隐藏的button就能enter提交表单了，这算问题吗

```
 <Form onSubmit={this.onSubmit}>
            <Button htmlType="submit" style={{ display: 'none' }}/>
```

**Comment by afc163** [comment]
It is not a bug, read more at https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/ and https://stackoverflow.com/questions/477691/submitting-a-form-by-pressing-enter-without-a-submit-button

**Comment by zlab** [comment]
谢谢
