### ISSUE TITLE
Add "Append"  button and "Remove" button for TreeNode or Menu.

### ISSUE THREAD

**Issue by fengshengde** [ant-design/ant-design#11668]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Add "Append"  button and "Remove" button for TreeNode or Menu.  I can edit the TreeNode 
like this  http://element-cn.eleme.io/#/zh-CN/component/tree#tree-shu-xing-kong-jian

### What does the proposed API look like?
```javascript
<TreeNode title="parent 0" key="0-0">
	<TreeNode title="leaf 0-0" key="0-0-0" isLeaf  editText="edit" deleteText="delete"  editAction="{this.edit()}  deleteAction="{this.delete()}"/>
	<TreeNode title="leaf 0-1" key="0-0-1" isLeaf />
	<Add title = "Append" onClick="{this.add()}"/>
</TreeNode>
```

**Comment by afc163** [comment]
`title` could be a ReactNode.

**Comment by damaohub** [comment]
> `title` could be a ReactNode.
Can it get the information(key etc) of the selected target?

**Comment by daiyang123456** [comment]
setTimeout 0;

**Comment by keithlimmontajes** [comment]
same issue anyone get this ?

**Comment by keithlimmontajes** [comment]
could not get the selected target info.
