### ISSUE TITLE
Pagination组件defaultCurrent值更新，除非是点击分页的页数，不然通过其他方式修改defaultCurrent，页数不会改变

### ISSUE THREAD

**Issue by SakuraJing** [ant-design/ant-design#11676]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
Google Chrome	67.0.3396.87 (正式版本) （64 位）

### Steps to reproduce
自己对该组件进行了二次封装，父组件传值给Pagination，跟踪到传给Pagination的defaultCurrent值已经有所改变，但是页面渲染出来的页数未改变
<Pagination
        showQuickJumper
        onChange={onChange}
        onShowSizeChange={onShowSizeChange}
        defaultCurrent={defaultCurrent}
        total={total}
      />

### What is expected?
Pagination的defaultCurrent值不论是通过点击页数还是其他方式修改，页面都可以更新到最新的数据

### What is actually happening?
现在的展示是：除了通过点击页数或者reload页面，其他更新defaultCurrent值的情况，页数都保持不变

**Comment by afc163** [comment]
建议自行研习 React 受控组件概念：http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by SakuraJing** [comment]
经过自己测试是自己属性使用的问题，将defaultCurrent属性变为current属性，页数改变组件会跟着刷新的
