### ISSUE TITLE
1.11版本Upload组件不兼容IE8,IE9

### ISSUE THREAD

**Issue by camillalo** [ant-design/ant-design#11678]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
window7,IE8,9,好像是react 0.14 

### Reproduction link
[http://codepen.io/paranoidjk/pen/LWpaKe](http://codepen.io/paranoidjk/pen/LWpaKe)

### Steps to reproduce
网站为了兼容IE8，对相关插件进行了降级，antd为1.11。
经测试，发现IE8,IE9下，错误：
返回的file，fileList对象下的type为undefined，以及其他属性也都hiundefined，只有length，和一个图片本地地址属性有值。
通过一一排查，发现在Upload组件的_this.onStart(file)，这个方法中，file的值就有问题（在IE8,IE9下）。
但没找到onStart怎么调用的（求解惑？？）
猜测：图片上传后，组件解析图片没有成功！！

### What is expected?
file下，type有值，name正常

### What is actually happening?
undefined

**Comment by afc163** [comment]
1.x 版本是两年前的了，已经不维护了。
