### ISSUE TITLE
antd/table rowSelection 设置 defaultChecked 无效

### ISSUE THREAD

**Issue by noyobo** [ant-design/ant-design#1167]
## What you did

取消任意一条目 checkbox 勾选后, 点击添加按钮, 更改 table 的 dataSource 后, 强制渲染

(如果没有点击 checkbox, 直接点击添加,是正确的)

## What you would like to happen

新添加的 dataSource 内容, defaultChecked 默认是 true, 应该默认勾选

## What actually happened

但是添加后默认没有勾选

## Online demo

http://codepen.io/noyobo/pen/GZZabW

## Environment Information

-  antd@0.12.8
- OSX 10.11.3
- chrome  48.0.2564.116 (64-bit)

**Comment by afc163** [comment]
Try this way: http://codepen.io/anon/pen/VaaoxE

**Comment by imsobear** [comment]
@afc163 能不能解释下原因呢？是这么设计的，还是说是个 bug.

按照正常的思路 push 一个 checked 的数据应该就是可以的，看你的做法是自己再改变了 `selectedRowKeys`，然后传给 table, 这个我感觉是一种奇技淫巧，普通的开发者并不知道。

**Comment by afc163** [comment]
selectedRowKeys 是 react 通用的做法。不要使用目前的 defaultChecked，有问题，文档里我也去掉了。

**Comment by miaojiuchen** [comment]
看了半天源码，在handleSelect(record, rowIndex, e) 这个里面把selectionDirty设置为true之后就会完全忽略检查这个属性，暂时还没看懂后面的代码。
