### ISSUE TITLE
support forwardRef

### ISSUE THREAD

**Issue by huangbinjie** [ant-design/ant-design#11670]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hello everyone. I used to write react stateless function component within our new react project. However the `Input` doesn't seem support forwardRef right now, have any plans to support it?

### What does the proposed API look like?
input = React.createRef()
<Input ref={this.input}>

**Comment by yesmeck** [comment]
Introduce `forwardRef` in `Input` would be a breaking change and the old versions of React doesn't support this new API.
