### ISSUE TITLE
 抽屉组件Drawer不兼容ie 10 和 ie 9  

### ISSUE THREAD

**Issue by waynesuns** [ant-design/ant-design#11672]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
win7 ie9或ie10

### Reproduction link
[https://ant.design/components/drawer/](https://ant.design/components/drawer/)

### Steps to reproduce
1.打开抽屉 ----正常
2.关闭抽屉----正常
3.再次打开-----无法打开

### What is expected?
兼容ie10 和ie 9

### What is actually happening?
不兼容ie 10 和ie 9

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/issues/11583

**Comment by waynesuns** [comment]
你好
该问题在当前版本的demo里依然存在，但却被close了
