### ISSUE TITLE
报错：Uncaught TypeError: Cannot read property 'webpackHotUpdateantd' of undefined

### ISSUE THREAD

**Issue by chemdemo** [ant-design/ant-design#1168]
引用[打包好的库](http://ant.design/dist/antd.js)报错了：

![image](https://cloud.githubusercontent.com/assets/1014734/13668239/81fba586-e6f6-11e5-90db-16612ce181dd.png)

**Comment by afc163** [comment]
不推荐这么使用。

**Comment by chemdemo** [comment]
直接引用npm上的模块 用webpack编译实在是太慢了
