### ISSUE TITLE
RangePicker width is out of the col.

### ISSUE THREAD

**Issue by believeZJP** [ant-design/ant-design#11683]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
mac,chrome

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
form里有row,col，每个col里一个formItem，最后一个formItem是rangePicker

### What is expected?
rangepicker不超出col宽度

### What is actually happening?
rangePicker超出了宽度

<img width="1294" alt="machi 2018-08-09 14-17-33" src="https://user-images.githubusercontent.com/15198091/43882892-ebeebfa6-9be3-11e8-97ef-8ebccf95fdbd.png">

**Comment by chenshuai2144** [comment]
You can set a style props

**Comment by believeZJP** [comment]
<img width="542" alt="1" src="https://user-images.githubusercontent.com/15198091/43898674-27bf9c84-9c12-11e8-88bc-4acfab7f4e6a.png">
That's not working! And It's a bad solution, not responsive.

**Comment by chenshuai2144** [comment]
```
<RangePicker style={{
     width:200
}}/>
```
like this

**Comment by afc163** [comment]
```
<RangePicker style={{ width: '100%' }} />
```
