### ISSUE TITLE
TreeSelect 能不能只搜索父级

### ISSUE THREAD

**Issue by zhengyanwen** [ant-design/ant-design#11686]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TreeSelect能不能只搜索父级，不搜索子级，因为子级都是异步获取的，现在一搜索所有父级都会触发异步获取子级，导致页面卡死

### What does the proposed API look like?
searchParents: true

**Comment by zombieJ** [comment]
挺合理的，目前可以先用 loadedKeys 来控制子节点加载情况（有点 tricky）。我看看怎么调整比较适合。

**Comment by cjchnwscqwsbsy** [comment]
@zhengyanwen 我很想知道你是如何做到可以搜索子元素的，因为我的只能搜索父元素

**Comment by ZoeBai** [comment]
V3.8.2时搜索父级会触发异步获取子级，导致页面卡死；
V3.9.1时搜索正常返回父级，但是展开父节点不能触发onLoadData，获取不到子类

**Comment by zombieJ** [comment]
@ZoeBai 能给个重现不？https://codesandbox.io/

**Comment by ZoeBai** [comment]
https://codesandbox.io/s/4r1lkv7wl9
引用的3.9.3也是一样，搜索时正常返回父级，但是展开父节点不能触发onLoadData
重现步骤：任意输入字符后展开SearchNode Expand to load @zombieJ

**Comment by zombieJ** [comment]
@ZoeBai 你这个没错，key 相同代表是同一个节点， load 一次后就不会再 load 了。如果不是同一个 key 就设置不同的 key 就行了：https://codesandbox.io/s/mj81orv9o8

**Comment by ZoeBai** [comment]
嗯嗯，感谢回复，我下午也发现是key重复的问题，但是本来一级节点的children是undefined，触发onSearch会把children全设成Array[0]，并将每个一级节点触发两遍onLoadData，这是为什么呢？
@zombieJ

**Comment by zombieJ** [comment]
能写个简化版的重现吗？我来定位一下

**Comment by ZoeBai** [comment]
https://codesandbox.io/s/4xprkljp89 @zombieJ 
我删了些代码加上了注释，附图（重现步骤，不展开之前的一级节点，直接搜索）
![image](https://user-images.githubusercontent.com/11712143/46143150-b3f1a180-c28b-11e8-970c-ba68334bc954.png)

**Comment by zombieJ** [comment]
看起来是有点问题，我看看

**Comment by zombieJ** [comment]
TreeSelect support `treeExpandedKeys` now.

**Comment by panhuajian** [comment]
这个问题还是不知道用什么好的方法解决，不知道官方有什么好的推荐，就是当搜索之后所有的节点都默认展开，再次点击展开节点不会重新请求数据了，获取不到子节点数据了，感觉这个影响很严重。
