### ISSUE TITLE
Antd3.7.2中Tree的expandedKeys属性设置，展开节点时，loadData方法错乱（3.6.*是可以的）？

### ISSUE THREAD

**Issue by lygcngh** [ant-design/ant-design#11689]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
windows7;chrome 64;react: ^16.2.0

### Reproduction link
[https://github.com/lygcngh/ReportAntdIssue.git](https://github.com/lygcngh/ReportAntdIssue.git)

### Steps to reproduce
具体看发布在Segmentfault上的文章：https://segmentfault.com/q/1010000015946888?_ea=4144328；
运行（先cnpm i）重现代码，看console下loadData被调用多少次；会发现loadData调用异常;

### What is expected?
https://segmentfault.com/q/1010000015946888?_ea=4144328；此处有详细说明和图解

### What is actually happening?
https://segmentfault.com/q/1010000015946888?_ea=4144328；此处有详细说明和图解

---
我的webpack配置是^3.0.0,即大版本不变，cnpm i后会自动更新下小版本。
一开始一直不知道为什么会这样，因为Tree组件我之前使用过这个属性都没问题。发现是升级后就对比新版本和原先版本，发现这个是bug

**Comment by zombieJ** [comment]
TreeNode loaded 逻辑调整过以支持受控。非受控状态下，可以通过 `treeNode.props.loaded` 属性查看是否已经加载。在受控状态下，可以通过 `loadedKeys` 来控制节点加载状况。

相关属性：https://ant.design/components/tree-cn/#Tree-props
相关讨论: https://github.com/ant-design/ant-design/issues/10821

**Comment by lygcngh** [comment]
你说的这个受控呢确实是一方面，但是我提出的问题中有一个也是无法用loadedKeys这个属性解释的。我expendedKey设置了3个展开节点（加载展开节点的时候会调用loadData方法），但控制台却显示loadData方法调用了6次喔（也就说每个展开节点各自调用loadData两次）。这个和loadedKeys这个受控节点没关系了吧？我在Https://segmentfault.com/q/1010000015946888?_ea=4144328;有截图的，希望能采纳。

**Comment by zombieJ** [comment]
嗯，expandedKeys 下的确有点问题。

**Comment by lygcngh** [comment]
哈哈，今天试了一下。expandedKeys 设置多个展开节点loadData重复加载的问题已经解决。
我再次测试了一下Tree的loadedKeys和expandedKeys ，发现一个小问题还是存在~~。
当我不设置loadedKeys受控节点时，设置expandedKeys 展开一个本身带children:[...]的节点时，并未触发loadData。
代码如下：
1.第一个节点自带children:[...]：
`treeData: [
            {
                title: 'Expand to load00', key: '0',
                children: [
                    { title: '00-0', key: '00-0' },
                    { title: '00-1', key: '00-1' },
                    { title: '00-2', key: '00-2' },
                ]
            },
            { title: 'Expand to load01', key: '1' },
            { title: 'Expand to load02', key: '2' },
            { title: 'Expand to load03', key: '3' },
            { title: 'Tree Node04', key: '4', isLeaf: true },
            { title: 'Tree Node05', key: '5', isLeaf: true },
        ],`
2.Tree不设置loadedKeys受控节点，设置 expandedKeys={['0']}展开这个包含chlidren的节点
` <Tree
                loadData={this.onLoadData}
                expandedKeys={['0']}
            >
                {this.renderTreeNodes(this.state.treeData)}
            </Tree>`
这个节点展开时，并未触发loadData。也就是说非受控情况下，“ console.log('loadData异步加载。。。。', treeNode);”这句未打印，那么“if(treeNode.props.loaded)”这个判断就没法执行。
按理是loadData()执行，function内部通过“if(treeNode.props.loaded)”来判断。
` loadData = (treeNode) => {
        console.log('loadData异步加载。。。。', treeNode);
        if(treeNode.props.loaded){
           ......
        }else{
          ......  
        }
    }`
我觉得这也还是个问题,望采纳。

**Comment by zombieJ** [comment]
@lygcngh ，loadData 行为有很多相关讨论，带有 children 不触发 loadData 是权衡后的结果。这也是为什么提供了 loadedKeys 用于解决带有 children 时还需要 loadData 的需求。

**Comment by lygcngh** [comment]
谢谢回答，因为我的项目使用了很多antd的树组件，我对组件的属性效果的变化是比较敏感的和关注的。这意味着小版本升级也要做代码改动，工作量还是挺多的。
