### ISSUE TITLE
[Form] wrappedComponentRef returns undefined in production build

### ISSUE THREAD

**Issue by froston** [ant-design/ant-design#11694]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
Chrome 67, Windows 10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z72mkl8o4)

### Steps to reproduce
Cannot reproduce it in dev enviroment.
It only happens in production build!!
Using create-react-app with react-app-rewired.

### What is expected?
Beign able to access all the `Form` functions thru `wrappedComponentRef`.

### What is actually happening?
`TypeError: Cannot read property 'props' of undefined.` when calling `this.wrappedForm.props.form.validateFields()`
The value of `wrappedComponentRef` is always `undefined` so I can't access the props.

---
Note it only happens in production build. In dev everythings works perfectly.
Any thoughts what could be the problem? Thanks a lot!

**Comment by yesmeck** [comment]
I've tried downloading your codesandbox and built it, have no luck to reproduce the error.

**Comment by marswong** [comment]
still sucks by this...

here is my code:

```js
const CohortForm = Form.create({
  mapPropsToFields(props) {
    return {
      username: Form.createFormField({
        value: '',
      }),
    };
  },
})((props) => {
  const { getFieldDecorator } = props.form;

  return (
    <Form>
      <FormItem
        label="username"
      >
        {getFieldDecorator('username', {
          rules: [{ required: true }],
        })(
          <Input />,
        )}
      </FormItem>
    </Form>
  );
});

class Demo extends React.Component {
  constructor(props) {
    super(props);
    this.customForm = React.createRef();
  }

  onChange = () => {
    if (!this.customForm.props.form.validateFields()) {
     // submit form
   }
  }

  render() {
    <React.Fragment>
      <Modal
         visible={true}
         onOk={this.onChange}
      >
         <CustomForm wrappedComponentRef={(inst) => { this.customForm = inst; }} />
       </Modal>
    </React.Fragment>
  }
}
```

**Comment by dgreene1** [comment]
I'm having this issue as well. Please reopen.

**Comment by mikemusni** [comment]
@froston, add initial value on to your field.
Change 

> {form.getFieldDecorator("test")(<Input />)}

 to 

> {form.getFieldDecorator("test",{initialValue: ''})(<Input />)}

**Comment by donglinkai** [comment]
The bug still exist

**Comment by zilurrane** [comment]
I am also facing this error.
During development mode it works fine but not in production build.

**Comment by zilurrane** [comment]
I changed my component from stateless functional to class component and it starts working now.
But still question remains in my mind that why it didn't work correctly with functional component and that too only in production mode.

**Comment by Timikcool** [comment]
@yesmeck needs to be reopen cuz it's still not working for functional components and/or useRef hook
