### ISSUE TITLE
RadioGroup use prop 'defaultValue' is useless when the data is loaded asynchronously

### ISSUE THREAD

**Issue by zwStar** [ant-design/ant-design#11693]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
none

### Reproduction link
[https://ant.design/components/radio-cn/](https://ant.design/components/radio-cn/)

###  English:
when use a component RadioGroup with a props defaultValue like:

    <RadioGroup name="radiogroup" defaultValue={data[0].id}>
      {
        data.map((item)=>(
             <Radio value={item.id} key={item.id}>{item.value}</Radio>
         ))
     }
    </RadioGroup>

If the data data is loaded asynchronously, defaultValue will not work. I looked at the source code, because with the change of data, the RadioGroup component will trigger the componentWillReceiveProps hook, and the source code is written like this:

    componentWillReceiveProps(nextProps: RadioGroupProps) {
        if ('value' in nextProps) {
            this.setState({
                value: nextProps.value,
            });
        } else {
            const checkedValue = getCheckedValue(nextProps.children);
            if (checkedValue) {
                this.setState({
                value: checkedValue.value,
                });
            }
        }
    }

At this time, the defaultValue is not processed at all, so it does not work. I think this code can be added.

    ...
    if (checkedValue) {
      this.setState({
         value: checkedValue.value,
      });
    }else{  // Add code
      if('defaultValue' in nextProps){
          this.setState({
              value: nextProps.defaultValue,
           });
       }
    }

      

### 中文：
当使用RadioGroup组件并使用prop 'defaultValue'的时候   
   

     <RadioGroup name="radiogroup" defaultValue={data[0].id}>
      {
        data.map((item)=>(
             <Radio value={item.id} key={item.id}>{item.value}</Radio>
         ))
     }
    </RadioGroup>

如果数据data是异步加载时，defaultValue将不起作用，我看了一下源码，因为随着data的变化，RadioGroup这个组件会触发componentWillReceiveProps这个钩子，而源码里面是这样子写的如下：

    componentWillReceiveProps(nextProps: RadioGroupProps) {
        if ('value' in nextProps) {
            this.setState({
                value: nextProps.value,
            });
        } else {
            const checkedValue = getCheckedValue(nextProps.children);
            if (checkedValue) {
                this.setState({
                value: checkedValue.value,
                });
            }
        }
    }

这个时候完全没有处理defaultValue，所以导致不起作用，我觉得可以加上这段代码

    ...
    if (checkedValue) {
      this.setState({
         value: checkedValue.value,
      });
    }else{  // 这里是新增代码
      if('defaultValue' in nextProps){
          this.setState({
              value: nextProps.defaultValue,
           });
       }
    }

      

### What is expected?
fix this problem

### What is actually happening?
none

---

**Comment by afc163** [comment]
建议自行研习 React 受控组件概念：http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by MillionChen** [comment]
<RadioGroup name="radiogroup" value={data[0].id}>
  {
    data.map((item)=>(
         <Radio value={item.id} key={item.id}>{item.value}</Radio>
     ))
 }
</RadioGroup>

 同事发现 设置 value就ok了，不知道原因是啥？求官方解析

**Comment by Janaka-Steph** [comment]
Any news on this? I don't read Chinese sorry.
