### ISSUE TITLE
antd3.8.0 upload组件interface.d.ts,RcFile接口报错

### ISSUE THREAD

**Issue by baggiomygod** [ant-design/ant-design#11699]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
macos

### Reproduction link
[https://github.com/ant-design/ant-design/tree/master/components/upload](https://github.com/ant-design/ant-design/tree/master/components/upload)

### Steps to reproduce
引入antd import {} from antd

### What is expected?
正常运行

### What is actually happening?
[ts]
接口“RcFile”错误扩展接口“File”。
  属性“lastModifiedDate”的类型不兼容。
    不能将类型“Date | undefined”分配给类型“Date”。
      不能将类型“undefined”分配给类型“Date”。

---
源码interface.d.ts
```
export interface RcFile extends File {
    uid: string;
    lastModifiedDate?: Date; // 原码是：lastModifiedDate?: Date;可选 File接口里原码是：lastModifiedDate: Date 必须
}
```
以上代码改成： lastModifiedDate: Date后正常
```
export interface RcFile extends File {
    uid: string;
    lastModifiedDate: Date;
}
```

**Comment by windwang** [comment]
+1

**Comment by andycall** [comment]
#11709
