### ISSUE TITLE
alert组件的closable属性为什么要用a标签设置, 能在这个属性上添加跳转路径吗

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#1169]

**Comment by afc163** [comment]
Try `closeText=<span onClick={this.goToLocationFunc}>xxx</span>`.

**Comment by XUGAOBO** [comment]
如果在打开新页面的时候, window.location.href有时候会被拦截的

**Comment by XUGAOBO** [comment]
我一般使用link包裹着控件,但是alert里面的关闭按钮是<a>就会报错误

**Comment by XUGAOBO** [comment]
问题已经解决,谢谢

**Comment by afc163** [comment]
可以分享一下解决方案，其他人遇到类似问题也能受惠。

**Comment by XUGAOBO** [comment]
var link = document.createElement('a');
    link.target = "_target";
    link.href = 'url'
    document.body.appendChild(link);
    link.click();
