### ISSUE TITLE
Icon component doesn't accept refs

### ISSUE THREAD

**Issue by dbismut** [ant-design/ant-design#11696]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2vm6yky19p)

### Steps to reproduce
Add a ref prop to an Icon component.

### What is expected?
The ref should be passed to the Icon component.

### What is actually happening?
Console shows this error: stateless function components cannot be given refs.

**Comment by afc163** [comment]
React don't support that, check https://hackernoon.com/react-stateless-functional-components-nine-wins-you-might-have-overlooked-997b0d933dbc

**Comment by dbismut** [comment]
Hey @afc163c, sorry for insisting but would’t be a way to add a innerRef prop to functional components as explained here?

https://github.com/reactstrap/reactstrap/issues/1054#issuecomment-396703752

Many thanks.
