### ISSUE TITLE
怎么增加 icon 

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design#1170]
![image](https://cloud.githubusercontent.com/assets/2011119/13668876/97dc73d6-e6fa-11e5-8e77-116c70fa9247.png)
http://fortawesome.github.io/Font-Awesome/icon/thumb-tack/
需要这个图标

**Comment by afc163** [comment]
已给设计师提需求。

**Comment by guolin** [comment]
http://iconfont.cn/search?q=pin&page=3 

可以这里搞，略微复杂一点儿。
或者直接引用fontawesome
