### ISSUE TITLE
Table Tree bug?

### ISSUE THREAD

**Issue by TheNorthWindRises** [ant-design/ant-design#11700]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
MAC OS Chrmoe

### Reproduction link
[https://codepen.io/TheWindRises/pen/QBzOga?editors=0010](https://codepen.io/TheWindRises/pen/QBzOga?editors=0010)

### Steps to reproduce
English: Click the change button

中文：点击change按钮

### What is expected?
English: Only one column should be displayed in the table component ('Line 2.1 should be a child of 'Line 1') and line 2.1 should be hidden

中文：table组件中应该只显示一列（'第2.1行'应该作为'第1行'的子元素）且'第2.1行'应该隐藏

### What is actually happening?
English: But the reality is that the 'line 2.1' element is rendered into the DOM and is not hidden.

中文：但实际情况是'第2.1行'元素被渲染到DOM中且没有被隐藏。

---
English: I tested if I changed the `key` of 'line 2.1', which is what I expected.

中文：我测试了如果改变'第2.1行'的`key`，能是我期望的状态

**Comment by yesmeck** [comment]
Fixed in upstream, try reinstall node_modules.

**Comment by spllot** [comment]
@yesmeck I got the same problem, as I reinstall node_modules, this problem is solved, but get another one:

when move record A to the children of record B, The A will not be showed when expand B, only showed when expand B->Hide B->expand B.

**Comment by TheNorthWindRises** [comment]
@yesmeck 
中文：感觉应该不是node_modules的问题，我在本地环境和codepen上都出现这个问题。
English: I feel that it should not be a problem with node_modules. I have this problem in both the local environment and the codepen.

**Comment by yesmeck** [comment]
@spllot remove yarn.lock or package-lock.json if exists.
