### ISSUE TITLE
Content blindly passes all props to the DOM element

### ISSUE THREAD

**Issue by dbismut** [ant-design/ant-design#11707]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
Chrome v69

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/57v8k7y74)

### Steps to reproduce
Create a styled Layout.Content component  and add a custom prop to it in a render function use that component.

### What is expected?
No warnings.

### What is actually happening?
Console shows the following warning:

> Warning: React does not recognize the `myProp` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `iscollapsed` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### Observations
I believe Content is blindly passing all props to the dom element wrapping its content.
**EDIT: I realize this is actually the case for other components such as Slider**.

**Comment by afc163** [comment]
> I believe Content is blindly passing all props to the dom element wrapping its content.

It is by designed, you should search solution in styled-components community.

**Comment by dbismut** [comment]
Thanks @afc163. For reference, from https://github.com/styled-components/styled-components/issues/439 I can see that prefixing a prop with $ doesn't generate an error, so I guess I'll use this as a fix.
