### ISSUE TITLE
Breadcrumb组件中和router联动时，路径写死以井号开头，导致ssr无法使用

### ISSUE THREAD

**Issue by binzeehale** [ant-design/ant-design#1171]
在 Breadcrumb 组件中， line 111 有如下代码
```
            link = _react2.default.createElement(
              'a',
              { href: '#/' + paths.join('/') },
              name
            );
```
如果我使用 ssr 的话，路径是不需要 # 的，能否增加一个prop 来控制下，开关这个 #号

**Comment by benjycui** [comment]
1.0.0 将会支持自定义 link，see: https://github.com/ant-design/ant-design/pull/1030

**Comment by binzeehale** [comment]
大概多久会发布呢？

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/978
