### ISSUE TITLE
[Timeline] Feature - Default color of the circle's

### ISSUE THREAD

**Issue by DouglasOGarrido** [ant-design/ant-design#11714]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Standardize the API according to the default template.

### What does the proposed API look like?
 Instead of using "blue, red or green" to default value, use "primary or default, error, success and warning". Equals to [Notifications colors](https://ant.design/components/notification/#components-notification-demo-with-icon).

E.g.:
```
// old way
<Timeline>
  <Timeline.Item color="green">Create a services site 2015-09-01</Timeline.Item>
</Timeline>

// new way
<Timeline>
  <Timeline.Item color="success">Create a services site 2015-09-01</Timeline.Item>
</Timeline>
```

**Comment by afc163** [comment]
I think we may stick to the old way cause Timeline is more like Tag.
