### ISSUE TITLE
Missing less file in lib/icon/style

### ISSUE THREAD

**Issue by RyanWarner** [ant-design/ant-design#11713]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This would allow less default theme overrides to work when using the icon styles

### What does the proposed API look like?
Add index.less to the icon component, just like all the other components

**Comment by afc163** [comment]
https://unpkg.com/antd@3.8.0/lib/icon/style/index.js

> This would allow less default theme overrides to work when using the icon styles

I don't see why there should be less file to allow theme overrided.
