### ISSUE TITLE
Drawer组件增加自定义header

### ISSUE THREAD

**Issue by zjsxfly** [ant-design/ant-design#11717]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
header除了关闭功能，想增加分享、删除等自定义功能

### What does the proposed API look like?
header属性：HTMLElement | ReactNode

**Comment by afc163** [comment]
title could be a React node.
