### ISSUE TITLE
Update props of existing modal dialogs created by Modal.method()

### ISSUE THREAD

**Issue by xuxinhang** [ant-design/ant-design#11721]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Updating the existing dialogs could be useful. For example:

===== Uploading =====

  Your files have been upload by XX%.

================= 

OR

===== Info =====

Your operation will be execuated in 4 seconds.

(this number keeps changing)

=============

Maybe I just want a simple method to implement such efforts, instead of writing so much `Modal` tags , especially to be implemented for many times. After all, many extra tags can not be a good idea.

Thank you.

### What does the proposed API look like?
```javascript
let myDialog = Modal.info(config);
myDialog.update(theNewConfig);
```

**Comment by chenshuai2144** [comment]
@yesmeck This demand feels very reasonable.

**Comment by afc163** [comment]
`Modal.method()` is for convenience, you should use Modal if you need more lifecycle method.

**Comment by xuxinhang** [comment]
@afc163  Sorry, I can't catch you. Why do you think this issue is about "lifecycle metond"? It is just about a way to reuse modals that have been created before, and no more tags in my JSX, as I wrote in the first comment.

**Comment by afc163** [comment]
@xuxinhang You can trace the solution of https://github.com/ant-design/ant-design/issues/11377 then we can make usage like https://codesandbox.io/s/84mm87lqk9 working which is not yet.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/11884

`instance.update({ ... })` will be supported at 3.9.0: https://github.com/ant-design/ant-design/blob/c038d6f3c97045d1abd1e1206e3e1d717bdf39a5/components/modal/demo/manual.md

**Comment by xuxinhang** [comment]
@afc163   Thanks for your work which makes its using more convenient and elegant !
