### ISSUE TITLE
highlight currentRow by click row

### ISSUE THREAD

**Issue by felix9ia** [ant-design/ant-design#11728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
higglight currentRow by click row

### What does the proposed API look like?
currentRowkey =XXXXXX

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues?q=is%3Aissue+click+highlight+is%3Aclosed
