### ISSUE TITLE
如何选择性打包antd?

### ISSUE THREAD

**Issue by liaobin312716** [ant-design/ant-design#1172]
现在fis不支持npm包， 我只能先打包antd，再使用。但是整体打包体积有点大，我想把基础UI和一些常用的原子组件打包的antd.core 里面，再将其他不常用的组件比如 日历 等 打包的扩展包里面，应该怎么做，没找到打包相关的文档？望解答一下，谢谢。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#i-just-want-to-use-menubuttonetc-but-it-seems-that-i-have-to-import-the-whole-antd-and-its-style

可用以上插件按需加载。

**Comment by afc163** [comment]
也可以自行构建模块，只引入自己需要的模块。

**Comment by liaobin312716** [comment]
好的，已使用第二种方法，自行构建模块。非常感谢。
