### ISSUE TITLE
Layout.Sider  Too few themes - Layout.Sider 主题太少了。

### ISSUE THREAD

**Issue by MinHongwei** [ant-design/ant-design#11720]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Left menu layout - 左菜单布局

### What does the proposed API look like?
More theme colors or custom theme colors can be used with background images - 更多的主题颜色或自定义主题颜色，可以使用背景图片

**Comment by afc163** [comment]
暂无计划。
