### ISSUE TITLE
Tooltip Title overflow breaks instead of wraps

### ISSUE THREAD

**Issue by barmargalit** [ant-design/ant-design#11722]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
Windows 10, Chrome 68.0.3440.106, React 16.2 (Though not really environment version related)

### Reproduction link
[https://codepen.io/barmargalit/pen/pZGMjO](https://codepen.io/barmargalit/pen/pZGMjO)

### Steps to reproduce
Use tooltip and set title to a text longer than the set width of the tooltip.

### What is expected?
Text in the title should wrap.

### What is actually happening?
Text in the title simply breaks and cuts words in the middle.

---
Used Tooltip for the first time with a long title (instructions for input), and noticed the text breaking.
Possible solution:
I saw in your change log than for version 3.7.2, tooltip overflow was fixed with: word-break: break-all; (as seen in issue https://github.com/ant-design/ant-design/pull/11402).
Consider using: word-wrap: break-word; instead.
more examples and info:
https://www.w3schools.com/cssref/css3_pr_word-break.asp
https://www.w3schools.com/cssref/css3_pr_word-wrap.asp
Thanks!

**Comment by afc163** [comment]
Thx for hint! @barmargalit
