### ISSUE TITLE
Menu导航菜单，如果子菜单是弹出的形式，级联菜单之间有间隙，当鼠标滑上去的时候菜单会消失

### ISSUE THREAD

**Issue by fuyufeng1025** [ant-design/ant-design#11725]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
window7  google

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
Menu导航菜单，如果子菜单是弹出的形式，级联菜单之间有间隙，当鼠标滑上去的时候菜单会消失

### What is expected?
去掉菜单之间的间隙

### What is actually happening?
菜单之间有间隙

**Comment by picodoth** [comment]
@fuyufeng1025 来个gif?

**Comment by oNexiaoyao** [comment]
这个menu与submenu之间的间距如何去掉呀，submenu是相对dom定位计算出来的，不是相对父菜单的呀。。

**Comment by LiuXiao617111** [comment]
同求，该这么解决呢
