### ISSUE TITLE
DatePicker 在mode={'year'} 情况下，点击年份，面板不消失

### ISSUE THREAD

**Issue by Jonny-Zou** [ant-design/ant-design#11735]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.2

### Environment
window10, chrome 63

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qx9wop9j76)

### Steps to reproduce
[![Edit antd reproduction template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qx9wop9j76)

### What is expected?
点击年份能选择

### What is actually happening?
点击年份面板不消失，也无数据回调

**Comment by afc163** [comment]
We don't support YearPicker yet, trace #4524

**Comment by guxingke201** [comment]
@afc163 文档改下呗，如果不想支持Year
![image](https://user-images.githubusercontent.com/8326941/48995972-319b3600-f185-11e8-9f9f-7849e86afbc5.png)

**Comment by zombieJ** [comment]
@guxingke201 ，
是没有直接的 YearPicker，不是 DatePicker 没有 Year 面板。参考一下[受控面板](https://ant.design/components/date-picker-cn/#components-date-picker-demo-mode)。

**Comment by afc163** [comment]
`<DatePicker mode="month"` don't equal to `<MonthPicker />`.

**Comment by guxingke201** [comment]
好的，明白了，感谢回复。
也就是说[这个pr](https://github.com/react-component/calendar/pull/427)是不会合并的？

**Comment by afc163** [comment]
应该会的，这两个都不是同一件事。

**Comment by Aladingding** [comment]
<LocaleProvider locale={zhCN}>
                        {
                            getFieldDecorator(field)(
                                <DatePicker
                                    locale={ zhCN }
                                    // value={ this.state.time }
                                    open={ this.state.isOpen}
                                    mode='year'
                                    format='YYYY'
                                    // onChange={ this.handleChange }
                                    onOpenChange={ this.handleOpenChange }
                                    onPanelChange={ this.handlePanelChange }
                                />
                            )
                        }   
</LocaleProvider> 

do like this ,you will fix this bug, use onOpenChange onPanelChange （maybe you need onFocus）

tks, 一江西流   [ https://www.cnblogs.com/zyl-Tara/p/10197177.html](关于antd 日期组件只选择年份，设置mode=year无法获取value的解决办法)

四个方法并用一定能完美实现你的需求

**Comment by tyawei** [comment]
这么大的一个bug，antd都不修复一下

**Comment by afc163** [comment]
@tyawei https://github.com/ant-design/ant-design/pull/16984
