### ISSUE TITLE
Rate组件focus时出现outline

### ISSUE THREAD

**Issue by Instanced** [ant-design/ant-design#11736]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
Chrome

### Reproduction link
[https://ant.design/components/rate-cn/](https://ant.design/components/rate-cn/)

### Steps to reproduce
https://ant.design/components/rate-cn 随便找个例子

### What is expected?
outline: none;

### What is actually happening?
未处理outline样式

**Comment by afc163** [comment]
挺好的，这是为了更好的可访问性支持。

**Comment by afc163** [comment]
挺好的，这是为了更好的可访问性支持。

**Comment by afc163** [comment]
可以优化一下点击时的效果。
