### ISSUE TITLE
Be able to select a table row without having to turn the column as a selectable column.

### ISSUE THREAD

**Issue by iacapuca** [ant-design/ant-design#11737]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This resolves issues when you only want to select a single row, not allowing multi selection and when you need to perform extra UI steps after selecting a row, for example, opening a modal.

### What does the proposed API look like?
It could be a simple boolean like allowMultipleSelection inside rowSelection.

**Comment by afc163** [comment]
```jsx
onRow={{ onClick: ... }}
```

**Comment by crazyx13th** [comment]
thx, **onRow={{ onClick: ... }}** AND **rowClassName** does the job for me
