### ISSUE TITLE
Form 默认不要使用 form

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#1173]
form 有时会导致页面提交刷新，对于 react 单页面不需要

http://stackoverflow.com/questions/895171/prevent-users-from-submitting-form-by-hitting-enter

http://stackoverflow.com/questions/1370021/why-does-forms-with-single-input-field-submit-upon-pressing-enter-key-in-input

@benjycui @afc163

**Comment by benjycui** [comment]
0.12.9
