### ISSUE TITLE
建议控制展开的行使用行的key来记录是否展开

### ISSUE THREAD

**Issue by houdingding** [ant-design/ant-design#11731]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果行处于展开状态，当删除这行时候，组建更新后，展开页会到新的data序号上，这样会造成用户错觉

### What does the proposed API look like?
建议控制展开的行使用行的key来记录是否展开

**Comment by yesmeck** [comment]
目前确实是这样的。

**Comment by houdingding** [comment]
我的锅！我自己用key是index！打扰了
