### ISSUE TITLE
关于Tooltip组件要显示的英文单词过长,单词中间就会发生"断开"的现象

### ISSUE THREAD

**Issue by XanderXueMingJi** [ant-design/ant-design#11739]
你好,Tooltip组件如果要显示的英文单词过长,单词中间就会发生"断开"的现象,我看了里面的代码,应该是由于 word-break: break-all;造成的,不知道这么去除这段代码,请问需要怎么解决
![weititop](https://user-images.githubusercontent.com/20898793/44078122-594a72dc-9fd8-11e8-8f46-c3b3a49056bc.png)

**Comment by afc163** [comment]
有太多人报长连续字符文本不截断的问题了，所以干脆默认加上了 `word-break: break-all;`。现在还蛮犹豫的。

**Comment by XanderXueMingJi** [comment]
可不可以加个属性来控制?

**Comment by afc163** [comment]
```jsx
<Tooltip title={<div style={{ wordBreak: 'keep-all' }}>1111 12221 34234 324324 123123 12323</div>}>
```

你可以暂时这么解决。

**Comment by XanderXueMingJi** [comment]
好的,谢谢

**Comment by afc163** [comment]
可以加一个 `wordBreak` 属性方便大家修改，主要是默认值不好取。

**Comment by afc163** [comment]
先保持默认 `wordBreak` 好了，@XanderXueMingJi 要不要来帮忙来个 PR？

**Comment by XanderXueMingJi** [comment]
谢谢,不过还是算了
