### ISSUE TITLE
Unable to disable mousePosition prop in Modal

### ISSUE THREAD

**Issue by cybercompa** [ant-design/ant-design#11747]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
Latest Chrome, MacOS, React.

### Reproduction link
[https://codepen.io/anon/pen/mjYJJw?editors=001](https://codepen.io/anon/pen/mjYJJw?editors=001)

### Steps to reproduce
If you pass mousePosition prop to a modal component you can see that it is not applied. In the case of a null value assigned to mousePosition, the animation should not appear.

### What is expected?
mousePosition is respected as is laid out in the react-component/dialog documentation. As a user you should be able to set it to null if you do not wish for mousePosition to be used. The animation should be optional, but currently is forced for every modal opening based on the users mouse position coordinates.

### What is actually happening?
Since specification order is important when using the spread operator, the later mousePosition prop overrides the previous one if passed in as a prop (see ...restProps) to the modal.

https://github.com/ant-design/ant-design/blob/master/components/modal/Modal.tsx

```
  render() {
    const { footer, visible, wrapClassName, centered, prefixCls, ...restProps } = this.props;

    const defaultFooter = (
      <LocaleReceiver
        componentName="Modal"
        defaultLocale={getConfirmLocale()}
      >
        {this.renderFooter}
      </LocaleReceiver>
    );

    return (
      <Dialog
        {...restProps}
        prefixCls={prefixCls}
        wrapClassName={classNames({ [`${prefixCls}-centered`]: !!centered }, wrapClassName)}
        footer={footer === undefined ? defaultFooter : footer}
        visible={visible}
        mousePosition={mousePosition}
        onClose={this.handleCancel}
      />
    );
  }
```

**Comment by cybercompa** [comment]
I believe [https://github.com/react-component/dialog] will also need to be updated to enforce this behavior.

**Comment by afc163** [comment]
You can sending us a fixing PR but undocument it cause we don't hope someone to custom it.
