### ISSUE TITLE
Tabs behavior error when tab pane contain auto focus element

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#11748]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
WIN10 - Chome68 - React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qmlx3mxp4)

### Steps to reproduce
Refresh page and change tab card to 5 or 6

### What is expected?
Behavior right

### What is actually happening?
Behavior error

**Comment by nuintun** [comment]
@afc163

**Comment by zombieJ** [comment]
I'm not sure what you mean. Could you add more describe on this?

**Comment by nuintun** [comment]
@zombieJ 
![tabs](https://user-images.githubusercontent.com/1730277/45272395-83fe7c00-b4df-11e8-8844-d612afa3c4b9.gif)

切 5，6 选项卡的时候因为 5，6 中有 `autofocus` 元素，对上面的动画造成了影响！
