### ISSUE TITLE
在多个项目中，如何基于ant-design 封装自己的组件

### ISSUE THREAD

**Issue by mrandpz** [ant-design/ant-design#11744]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求：想改变一处的UI组件，就可以在其他项目中执行更新就可以更新组件。    因为有多个项目应用到当前UI框架，然后我们基于当前UI框架又封装了一层UI组件。 现在两三个项目可以复制黏贴，等项目多了就会很麻烦

### What does the proposed API look like?
无

**Comment by chenshuai2144** [comment]
也什么不自己封装一个组件库呢
