### ISSUE TITLE
啥时候可以对tab加上左右手势滑动的支持呀

### ISSUE THREAD

**Issue by Alex1512** [ant-design/ant-design#1174]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/pgdXYp?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
不支持移动端应用。

**Comment by Alex1512** [comment]
antdesign会考虑以后做一个移动版本的吗？

**Comment by afc163** [comment]
其实正在行动中，你可以看看 https://github.com/react-component/ 下，已经有很多 `rn-` 和 `m-` 开头的组件了。
