### ISSUE TITLE
Table组件设置scroll.x = true时使用固定列在chrome浏览器下显示出现遮挡

### ISSUE THREAD

**Issue by poklau123** [ant-design/ant-design#11742]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
操作系统：windows10，浏览器版本： Google Chrome 62.0.3202.94（正式版本） （32 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k0x6r8orwv)

### Steps to reproduce
Table组件设置
```javascript
scroll.x = true
```
增加css属性
```css 
.ant-table td { white-space: nowrap; }
``` 
并在columns里面添加固定列（fixed: "left"）

### What is expected?
在chrome浏览器中，Table横向scrollbar拉到最左侧时首个非固定列不被遮挡

### What is actually happening?
在chrome浏览器中会出现遮挡，但是Microsoft Edge浏览器中未出现遮挡。

**Comment by afc163** [comment]
Add `scroll={{ x: '200%' }}` to resolve it, that is weird...

@yesmeck

**Comment by yesmeck** [comment]
因为设置了 nowrap 所以即使 age 设置了宽度，但是还是会被其他列挤扁。。。

**Comment by poklau123** [comment]
目前使用```scroll={{x: 'max-content'}}```解决了这个问题，这样设置的话<th>的中文文本也不会换行，除了在Edge下不兼容还是会换行外，可以说很完美了。

**Comment by fayhy** [comment]
https://github.com/ant-design/ant-design/issues/9283

**Comment by afc163** [comment]
@yesmeck 要不要当 scroll.x=true 时，设置宽度为 `max-content`

**Comment by unrealsmart** [comment]
![image](https://user-images.githubusercontent.com/11688458/44316990-5fbffa00-a461-11e8-8279-518666ee081a.png)
![image](https://user-images.githubusercontent.com/11688458/44317003-7a926e80-a461-11e8-8bb6-fee7d024a81d.png)

hover似乎有些问题？
Hover seems to have some problems?

**Comment by yoyo837** [comment]
`max-content` 兼容性有限，慎重使用哦

**Comment by zjafei** [comment]
mark一下 我觉的 {x: 'max-content'} 很好

**Comment by ensignwy** [comment]
@poklau123 如果我想将td文字超出部分隐藏并显示省略号，设置了这么一段样式
`
.ant-table-thead > tr > th, .ant-table-tbody > tr > td {
  padding: 12px 12px;
  text-align: center;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
`
跟你的情况一样，列被遮挡，设置了scroll={{x: 'max-content'}}还是不管用

**Comment by afc163** [comment]
trace #17127
