### ISSUE TITLE
upload/UploadList.tsx判断url是否是图片链接不通用

### ISSUE THREAD

**Issue by zhuozp** [ant-design/ant-design#11755]
发生问题的环境是：
antd 版本: 3.6.4
操作系统及其版本: mac
浏览器及其版本: chrome 68

您做了什么？
upload组件展示服务器返回的默认图片。

您期待的结果是：
根据图片url正确展示缩略图

实际上的结果是：
无法展示缩略图，原因是UploadList.tsx中isImageUrl方法判断url不通用。如图片链接：https://www.xxx.com/file/14/74e7998d-deb7-4b8a-bf1c-b3da0ae4a2cb.do?
以前老版本2.x版本是可以正确显示的，但3.6.4版本不行。

可重现的在线演示
无

**Comment by yesmeck** [comment]
Hello @zhuozp, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](http://new-issue.ant.design?repo=ant-design) to create an issue, thank you!

**Comment by yesmeck** [comment]
感觉这个功能确实没实现好，是不是可以加个 `image` 属性给 Upload。

```javascript
<Upload image />
// or
<Upload image={(file) => isImage(file)} />
```

**Comment by afc163** [comment]
可以看下这个 PR：https://github.com/ant-design/ant-design/pull/11684/files

**Comment by zhuozp** [comment]
就是这个pr觉得通用性不够。比如有些图片是加了相关权限的，需要服务器做逻辑判断的，这个时候的请求链接地址可能不是.png、.jpg作为extension。比如jave后台，以.do这种extension作为请求。

**Comment by zhuozp** [comment]
不好意思，看到了PR里面加了type类型判断了。我更新下antd版本。
