### ISSUE TITLE
Model is unexpect with react@16  in some way

### ISSUE THREAD

**Issue by xinggangling** [ant-design/ant-design#11759]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
chrome and so on

### Reproduction link
[https://codepen.io/anon/pen/pZXzJO https://codepen.io/anon/pen/djBbpM](https://codepen.io/anon/pen/pZXzJO https://codepen.io/anon/pen/djBbpM)

### Steps to reproduce

rollback = (fversionId) => {
     this.setState({
           visible: true, handleType: 'rollback', versionId: fversionId 
      }, () => { 
           console.log(document.getElementById('password'))
           // react@16  null 
           // react@15  <p id="test">...</p>
      }) 
}

### What is expected?
i want to the callback of setState works expected as react@15 

### What is actually happening?
result will show in codepen with diff url

---
react@15  -> https://codepen.io/anon/pen/pZXzJO
react@16  -> https://codepen.io/anon/pen/djBbpM

**Comment by yesmeck** [comment]
This is the difference between React 15 and React 16, not bug of Modal.

**Comment by xinggangling** [comment]
but i think react is the dependence of antd, antd should work as before.otherwise, who use we have to getElementById untill listen dom created; setState works as expected when antd Modal has not been used;
there is a example without antd Modal:
https://codepen.io/gaearon/pen/dac8528178e2c8774a870438f57b56b9/
so it seems to be ...
how Antd library works with React 16. I think Antd could update and just like we update our code for antd update v2 -> v3

**Comment by yesmeck** [comment]
https://codesandbox.io/s/wk04r016q8

建议调整下代码
