### ISSUE TITLE
自定义组件

### ISSUE THREAD

**Issue by careyke** [ant-design/ant-design#11750]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现有组件库提供的组件无法满足我们的需求，就比如我们想要一个地图的组件，期望是你们可以提供一个组件，组件内部怎么显示由用户提供的第三方的js、css来决定

### What does the proposed API look like?
希望提供一个api能够让我传递给你我自定义的js\css，然后当组件挂载完自动帮我js加载进来

**Comment by afc163** [comment]
Won't support.
