### ISSUE TITLE
关于Form动态生成的讨论

### ISSUE THREAD

**Issue by astwyg** [ant-design/ant-design#1175]
我希望在页面中动态生成表单, 比如这个样子:

```
<Query>
    <Input name="input1" placeholder="请输入搜索名称" label="搜索名称：" />
    {this.state.otherFormItem}
</Query>
```

显然在Query中无法使用`Query = createForm()(Query);`去初始化props.form.

我是[这么做的](https://github.com/ctyun/Mimiron2/blob/master/components/business/query.jsx), 在Query这个组件中手动接管了所有children的value, 但是感觉并不高明, 不知道各位有什么建议?

**Comment by afc163** [comment]
和这个问题 https://github.com/ant-design/ant-design/issues/1384 好像类似？

**Comment by astwyg** [comment]
@afc163  类似, 我也是因为动态生成的表单没法读写值, 只能做个组件手动接管value和onchange, 但是感觉很不好.

**Comment by benjycui** [comment]
参考下这个例子 http://react-component.github.io/form/examples/input-array.html

如果不行的话，麻烦提供一个可重现的 demo http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by benjycui** [comment]
`otherFormItem` 不要存在 `state` 内。

**Comment by astwyg** [comment]
在不在`state`中是一样的, `Query = createForm()(Query);`只能接管当时的`otherFormItem`, 而无法处理之后添加的

**Comment by benjycui** [comment]
> 如果不行的话，麻烦提供一个可重现的 demo http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by afc163** [comment]
动态表单可参考：http://ant.design/#/components/form?scrollTo=components-form-demo-dynamic-form-item

不要把 formitem 放在 state 里：https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html#what-shouldnt-go-in-state
