### ISSUE TITLE
Type definitions for antd

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#1176]
Anybody who use the VS Code Editor or `typescript` can found a typing here
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8500

<img width="1280" alt="screen shot 2016-03-11 at 17 15 19" src="https://cloud.githubusercontent.com/assets/433259/13698105/f1590f02-e7ac-11e5-8d95-4593ec77d379.png">

**Comment by afc163** [comment]
:+1:

**Comment by afc163** [comment]
这种社区贡献真是让人欣慰呀~

**Comment by tindytian** [comment]
nice job 
不过好像[https://github.com/DefinitelyTyped/tsd/issues/269](https://github.com/DefinitelyTyped/tsd/issues/269)
先用着，等1.0之后整一个antd snippets
