### ISSUE TITLE
pagination type simple size not auto

### ISSUE THREAD

**Issue by mikexfreeze** [ant-design/ant-design#11763]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
all

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
<>

### What is expected?
no number been hidden

### What is actually happening?
long not auto justify

**Comment by picodoth** [comment]
Sry, it's very hard to understand what's the issue here.

**Comment by afc163** [comment]
暂时不会做自动宽度，当时留三位数长度就是为了适应大多数场景，如果超过三位数了建议用样式调宽。
