### ISSUE TITLE
map button onClick 不生效

### ISSUE THREAD

**Issue by ccbang** [ant-design/ant-design#11765]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
codesandbox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qznwkvz66j)

### Steps to reproduce
打开console

### What is expected?
正常点击后触发onClick

### What is actually happening?
初始化则触发onClick

**Comment by afc163** [comment]
```diff
- onClick={this.handleSet(x)}
+ onClick={() => this.handleSet(x)}
```

Please learn JavaScript first.
