### ISSUE TITLE
Menu set selectedKeys.Hope to auto expand parent SubMenu

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#11764]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If the `selectedKeys` value is set, the parent menu is not expanded and is meaningless to the user.

### What does the proposed API look like?
autoExpandParent={true}

**Comment by afc163** [comment]
Please learn react controlled component: https://reactjs.org/docs/forms.html#controlled-components
