### ISSUE TITLE
 Custom trigger selector for the Collapse

### ISSUE THREAD

**Issue by cnagadya** [ant-design/ant-design#11770]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
By default, the Collapse can be toggled by clicking anywhere on the header. Would like to have a drop list in the Panel header that filters the data displayed in the particular panel's content area. 
As such, I would not want the panel to collapse when the user clicks on the droplist or anywhere else on the header except the icon

### What does the proposed API look like?
<Collapse>
<Panel triggerSelector=icon header="string|ReactNode">
</Panel>
</Collapse>

**Comment by apieceofbart** [comment]
@cnagadya 
You could make the Collapse controllable, like so:
https://codesandbox.io/s/kx091w9185

It's kind of hack, a change in the Collapse would be better.

**Comment by cnagadya** [comment]
Thanks for the suggestion @apieceofbart. However it does not fully solve my issue. Was able an input that I wanted, but the panel is collapsed when I click on the input too. Would like to have the collapse/expand only triggered by the icon

**Comment by saidziani** [comment]
> @cnagadya just hide the original arrow and create one yourself:
> https://codesandbox.io/s/kx091w9185

Please, the **codesandbox** attached is no more accessible, can you solve that?

**Comment by apieceofbart** [comment]
@saidziani ooops, I think I removed that by accident. Let me try to do it again

**Comment by apieceofbart** [comment]
@saidziani This should give you some idea: https://codesandbox.io/s/antd-custom-collapse-do-not-delete-c70qu
You can abstract it even more of course
