### ISSUE TITLE
DirectoryTree 报错

### ISSUE THREAD

**Issue by zichen-cici** [ant-design/ant-design#11772]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
win 10 ，react 16

### Steps to reproduce
组件运行报错

### What is expected?
组件能够正常显示

### What is actually happening?
组件报错，页面直接空白

![image](https://user-images.githubusercontent.com/13568082/44251112-c529a600-a229-11e8-83df-84e72ac345a1.png)

**Comment by zombieJ** [comment]
Closed for antd `3.8.2`
