### ISSUE TITLE
The mask of the modal box component is rendered abnormally.

### ISSUE THREAD

**Issue by chengsluo** [ant-design/ant-design#11777]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
win10 chrome   68.0.3440.106  

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
Slide the screen, move the "open" button closer to the top of the page, and quickly double-click the button. The title or part of the text in the modal box will be rendered abnormally as the theme color.
滑动屏幕，将"open"按钮移动至接近页面顶端，快速双击按钮，模态框内的标题或者部分文字会被异常地渲染成主题色。

### What is expected?
Quickly double-click, the contents of the modal box will not be rendered abnormally into the theme color.
快速双击，模态框内的内容不会被异常地渲染成主题色。

### What is actually happening?
Quickly double-click, and some of the contents of the modal box will be abnormally rendered into the theme color.
快速双击，模态框内的内容会有部分被异常地渲染成主题色。

---
The official documentation will reproduce this bug.
官方文档就可以重现这个Bug了。
https://ant.design/components/modal-cn/

**Comment by afc163** [comment]
因为双击的时候会选中动画路过的弹层里的文字，真的是非常细节的问题，感谢反馈。

**Comment by chengsluo** [comment]
@afc163 
The exception when opening is fixed, but when you double-click the "open" button to close the modal box, there will still be the same exception. Although it is very short, it is possible to re-render the exception when it is opened again. So I suggest you do something similar to the closed animation.
打开时的异常已经修复了，但是快速双击”open"按钮所在位置，进行关闭模态框操作的时候，还是会有同样的异常。虽然很短暂，但是有可能会在再一次打开的时候重新又渲染异常。所以我建议你对关闭的动画效果做类似的处理。
