### ISSUE TITLE
Dynamic form set with initial state

### ISSUE THREAD

**Issue by sayjota** [ant-design/ant-design#11789]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
windows 10, chrome 68

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r5j6x1vjjq)

### Steps to reproduce
Begin with official Dynamic Field Set example.

Attempt to implement initial state by adding getFieldDecorator in the constructor (for fields 'keys' and 'values').

In the render method, try to index into values as in the official example.  By calling getFieldValue('values[1]' ... etc

### What is expected?
See the values passed to the constructor as the beginning fields.

### What is actually happening?
Constructor values are not shown, instead the beginning fields are populated with defaultValue.

Also, you receive console error in the render: 

Warning: One field name cannot be part of another, e.g. `a` and `a.b`.

This is because in constructor the field "values" was decorated, and in render fields "values[1]" etc are decorated.

---
What is the proper method for implementing initial fields in the dynamic form set example?

**Comment by sayjota** [comment]
I hacked a solution together.

Instead of storing values in an array, I stored the values in individual fields.

So, whereas the demo has "values[key]", i use "values-key".  If that makes sense.

**Comment by afc163** [comment]
> Attempt to implement initial state by adding getFieldDecorator in the constructor

Don't do that, always use `getFieldDecorator` to wrap a real form field.
