### ISSUE TITLE
Tabs - editable tab names

### ISSUE THREAD

**Issue by raptoria** [ant-design/ant-design#11780]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
there's no easy way for the user to change a tab's name

### What does the proposed API look like?
give the user the ability to directly change the tab name by clicking on the tab and typing

**Comment by afc163** [comment]
No sure we are supposed to provide such feature when you can easily use `ReactNode` in Tabs title like `<Tabs.Pane tab={<EditableInputByYourOwn />} />`

**Comment by vaasu070** [comment]
For some reasons, when i use input node for tab prop as `<Tabs.Pane tab={<input/>} />,` it is now allowiing me to enter white spaces

**Comment by Shubhrakanti** [comment]
@vaasu070 were you able to resolve the issue of spaces?

**Comment by vaasu070** [comment]
Yeah @Shubhrakanti. stop event propagatio on keydown

```
<TabPane
      tab={<Input onKeyDown={e => e.stopPropagation()} onChange={(e) => console.log(e.target.value)} />}
      key="1"
    >
```

[#32843](https://github.com/ant-design/ant-design/issues/32843)

**Comment by Shubhrakanti** [comment]
Thanks!
