### ISSUE TITLE
[BUG] upload will cause chrome crash but firefox will not

### ISSUE THREAD

**Issue by sniperyan** [ant-design/ant-design#11787]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
windows, chrome版本 68.0.3440.106（正式版本） （64 位）

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
click upload button in demo will cause the chrome crash

### What is expected?
not crash

### What is actually happening?
crash

**Comment by afc163** [comment]
It works on my machine.

**Comment by sniperyan** [comment]
you should use the latest version of chorme on windows platform

**Comment by sniperyan** [comment]
Google Chrome 已是最新版本
版本 68.0.3440.106（正式版本） （64 位）

**Comment by sniperyan** [comment]
Maybe it is the bug of chrome,others windows computer has the same issue

**Comment by afc163** [comment]
我找了台 windows 机器试了最新的版本 68.0.3440.106，还是没重现。你试试隐身模式是否也会崩溃？

**Comment by sniperyan** [comment]
隐身模式也会崩溃，我试了下，这个版本的chrome file open 都会造成崩溃，我应该把这个Bug提给chrome

**Comment by canoelu** [comment]
我也遇到了这个问题

**Comment by afc163** [comment]
https://blog.csdn.net/u013401853/article/details/81806174

**Comment by afc163** [comment]
实锤了，搜狗输入法的问题，各位切换下或者干脆卸载了就好。

**Comment by TristanDongMaster** [comment]
how to resolve it?hurry!!!online waiting

**Comment by 546200350** [comment]
确实是搜狗输入法的问题。。。。

**Comment by drinkingcode** [comment]
@afc163 it works for me

**Comment by yingyingyingmm** [comment]
Chrome68版本更新后出现的一个问题，Chrome在最新版本中修复了，搜狗输入法也在9.1以后版本修复了。更新任意软件即可。
