### ISSUE TITLE
Value passed to table classname is not getting picked up

### ISSUE THREAD

**Issue by cnagadya** [ant-design/ant-design#11781]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
MacOs, Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rljv4yqwm)

### Steps to reproduce
Add class name to table

### What is expected?
The class name should be attached to the table

### What is actually happening?
Class name remains empty
![screen shot 2018-08-17 at 18 54 52](https://user-images.githubusercontent.com/26176338/44276063-18621f80-a24f-11e8-863b-56165f6cd728.png)

**Comment by afc163** [comment]
<img width="505" alt="image" src="https://user-images.githubusercontent.com/507615/44278181-cd143500-a27f-11e8-8300-1f430cece600.png">

`className` should allways be on the wrapper node of component so that people can override styles of any children inside.

**Comment by cnagadya** [comment]
For nested tables, there are styles that I need to apply to the parent table only. How do I go about that @afc163

**Comment by afc163** [comment]
```css
.sample-table table {
  // ...
}
```

**Comment by cnagadya** [comment]
That would impact all tables including the nested ones. Tried this .sample-table > table {} but got the same result. If I could add the class straight to the table, then I would be able to use table.sample-table{}
