### ISSUE TITLE
Empty table cell for nested table

### ISSUE THREAD

**Issue by cnagadya** [ant-design/ant-design#11788]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
MacOs, Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w03yv2qw6l)

### Steps to reproduce
Create a nested table as shown in the documentation

### What is expected?
Flexibility to have the nested table fill out the entire parent row

### What is actually happening?
An empty table cell (td) is added before the  nested table

<img width="1245" alt="screen shot 2018-08-19 at 14 56 24" src="https://user-images.githubusercontent.com/26176338/44308575-d5c05480-a3c0-11e8-894a-02eab8373b06.png">

**Comment by afc163** [comment]
It is for indent padding.

**Comment by cnagadya** [comment]
I'm using antd for a project and according to the designs, they would rather not have the indentation there. Is there no way to make this optional?

**Comment by sandeshsapkota** [comment]
Hi @cnagadya , How did you fixed this issue ? I am on the same situation.

**Comment by cnagadya** [comment]
Unfortunately was never able to resolve it
