### ISSUE TITLE
和 redux 一起用的时候 tag 组件 close 问题

### ISSUE THREAD

**Issue by eqielb** [ant-design/ant-design#1178]
问题:
使用 redux时点关闭，会导致关闭掉两个 tag

猜测原因：
点关闭的时候，1.先触发关闭动画，2.redux 触发 state 更新=>触发重新渲染=> tag 减少一个。此时前面的关闭动画还未结束。动画根据 component key 来识别动画元素，redux 到的重新渲染后，第二 tag 的 component key 被改变成和原来的第一个一样，动画结束时导致被关闭。

目前解决了：
手动在 shouldComponentUpdate 中把 redux 删除 tag 的更新 return 掉。

不过又遇到增加 tag 的时候也会有问题：
删除一个 tag 后马上增加一个 tag，重新渲染的时候，会多删掉另外一个 tag。。

原因：
没看出原因。

讨论：
删除的时候可以把 redux 引起的 render return 掉，让组件自己控制删除，增加 tag 的话没办法啊，不能手动去拿 ref 来 append new tag 吧。

不过感觉这样有点蛋疼，有没有高级点的方式?
比如，加一个关闭动画的参数😂（虽然可以解决这个问题，但是动画没了。。不是想要的结果。）

是不是我哪边的姿势有问题才遇到这样的问题

**Comment by afc163** [comment]
key 要稳定，不建议按 index 来设置。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/937#issuecomment-175087615
