### ISSUE TITLE
Checkbox indeterminate style broken

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#11797]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
WIN10 - Chome68 - React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x3r79z0o3p)

### Steps to reproduce
Checkbox set indeterminate

### What is expected?
Style ok

### What is actually happening?
Style broken

![_20180820181451](https://user-images.githubusercontent.com/1730277/44334737-f95ccb00-a4a4-11e8-9cb5-de4c937557b3.png)

**Comment by afc163** [comment]
It is by designed.

**Comment by afc163** [comment]
Fixed, 半个像素的 translate 在 windows 的 chrome 下面会有模糊问题。

https://stackoverflow.com/questions/32034574/font-looks-blurry-after-translate-in-chrome/38875162
