### ISSUE TITLE
Interest in changing from React.createClass to extending React.Component?

### ISSUE THREAD

**Issue by waywardmonkeys** [ant-design/ant-design#1179]
In the current repository, there are 113 instances where ``React.createClass`` is called and 17 where ``React.Component`` is extended.  Is there interest in changing over to extending ``React.Component`` if someone does the boring work?

**Comment by afc163** [comment]
That will be a good improvement, pull request welcomes~

**Comment by waywardmonkeys** [comment]
Will do!

**Comment by benjycui** [comment]
It's a good chance to unified antd's code convention, see: https://github.com/ant-design/ant-design/issues/1244

**Comment by afc163** [comment]
Already done! Thank U @waywardmonkeys

**Comment by waywardmonkeys** [comment]
Not actually complete yet ... have to deal with event handler binding and then convert the remaining usages of `React.createClass`. :)

**Comment by benjycui** [comment]
Done: https://github.com/ant-design/ant-design/commit/0ebf6c2eccc0961f5a84e4dd327f6bbbb4653a96

Demos will keep using `React.createClass`:
1. We do not recommend our user to use ES7 now.
1. `React.createClass` will bind `this` automatically.
