### ISSUE TITLE
Table组件的行内编辑AddRow和EditRow，应该如何实现？

### ISSUE THREAD

**Issue by longshaoye** [ant-design/ant-design#1180]
# 关于Table组件：
**应用背景**：在后台ERP类系统开发中，常会有主-从表的单据录入方式，
**问题描述**：我想问下在Table组件中如何实现新增一行AddRow，并在行中完成编辑和修改(EditRow)的功能呢？

# 关于InputNumber组件
**应用背景**：处理金额等含小数位的数字
**问题描述**：InputNumber组件能否设置小数点位数？

**Comment by afc163** [comment]
1. 建议系统学习下 React 。
2. https://github.com/ant-design/ant-design/issues/1131

**Comment by Liyuk** [comment]
这里扩展楼主的第一个问题：
如果在table组件中，每一行中都有input框，怎样去对这些input框进行数据获取呢？

我现在采用的方法是form和table混合的模式，即用一组data撑开table，另一组数据填充form，操作时进行下数据转换；虽然能够实现功能，但是复杂度提升了。

想问下有没有更合理的解决方案。

**Comment by Liyuk** [comment]
另外一种实现方法是，在`column`数组的`object`的`render`里，对`return`的` <input> `绑`onChange`去触发父组件的`setState`，通过修改数据源来实现页面数据修改显示，通过组件受控来实现
