### ISSUE TITLE
Table可编辑单元格，使用DatePicker后，save无法获取值

### ISSUE THREAD

**Issue by litcto** [ant-design/ant-design#11803]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
win10 chrome68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zr05k2rm6l)

### Steps to reproduce
1. 选择日期，日期带入日期框
2. 鼠标在页面空白处点击，日期无法save到页面，validateFields获取的values是undefined

### What is expected?
validateFields可以获取到日期

### What is actually happening?
validateFields获取不到日期

**Comment by yesmeck** [comment]
https://codesandbox.io/s/l9p0yp1xom

DatePicker 的值要转换成字符串。

**Comment by litcto** [comment]
使用日期，确实还存在几个问题：

**Comment by litcto** [comment]
使用日期，确实还存在几个问题：

**Comment by litcto** [comment]
感谢指点！
目前在编辑单元格中使用日期，还是存在几个小问题：
1、 选择完日期后，继续点击日期框，不能再选择，会触发失去焦点事件，理论上再点击日期输入框，应该继续选择；
2、 如果日期有`initialValue`的话，那么`onBlur`就不能再弹出日期框了，只有`initialValue`为空，才能弹出日期框，用`onChange`可以，但是`onChange`取不到值；
3、在`validateFields`格式化成String，能解决带不回值的问题，只能针对指定的`column`格式化，目前也只能是写死了；
以上就是使用过程中发现的一些瑕疵，先这样弄起来，后续再想想看能否优化，也写出来供大家参考，大神们若有好的方式，也麻烦不吝赐教~
