### ISSUE TITLE
Selector in bottom-fixed Containers miss the options

### ISSUE THREAD

**Issue by qxchen6** [ant-design/ant-design#11811]
### Version
3.8.2

### Environment
chrome mac/windows

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wo3jxx9l3l)

### Steps to reproduce
Has been written in [codesandbox](https://codesandbox.io/s/wo3jxx9l3l) .

### What is expected?
Options do not scroll with screen and could be seen when the screen is not scrolled . OR , provide a option to set drop direction (now it is auto.If i could set it always spread up but not drop down ,the problem will be solved .)

### What is actually happening?
Has been written in [codesandbox](https://codesandbox.io/s/wo3jxx9l3l) .

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#select-dropdown-datepicker-timepicker-popover-popconfirm-will-scroll-with-page

 #3487 #3438
