### ISSUE TITLE
Menu的下拉菜单选项会被DatePicker遮盖

### ISSUE THREAD

**Issue by Yunfans** [ant-design/ant-design#1182]
http://ant.design/components/menu/ 这个示例中也有同样的问题

**Comment by afc163** [comment]
确实有问题。

**Comment by Yunfans** [comment]
我刚刚看了一下，我用的版本里已经被修复过了... 但是还是有问题

**Comment by afc163** [comment]
是上面那个提交导致的。

**Comment by afc163** [comment]
http://stackoverflow.com/questions/5472802/css-z-index-lost-after-webkit-transform-translate3d
