### ISSUE TITLE
使用表格组件的时候出错了。

### ISSUE THREAD

**Issue by zelonggit** [ant-design/ant-design#1183]
Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `TableRow`。

**Comment by afc163** [comment]
http://ant.design/components/table/ 没有这个提示。

最好给出 demo 。

**Comment by zelonggit** [comment]
fetch('http://c.51bby.cn/bbuapi/groupMealManager/sight/list.json?type=1001')
            .then(response => response.json())
            .then(json => {
                console.log(json.data.dataList.r);

                this.setState({
                    data: json.data.dataList.r,
                    loading: false
                });
                console.log(this.state);
            })

data为table的dataSource

**Comment by zelonggit** [comment]
是用github的fetch库，是不是这个有问题。promise之间的错误貌似

**Comment by zelonggit** [comment]
找到了问题了，好像是数据有错导致的。

**Comment by zelonggit** [comment]
数据里面有一些空的字段为{}，然后渲染的时候，React直接去读取数据，但是为空- -什么的原因吧。具体还是高手来指教，我还是新手。
