### ISSUE TITLE
能否为 notification 新增 onClick 接口

### ISSUE THREAD

**Issue by focus0802** [ant-design/ant-design#11832]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些场合下，我们需要通过点击 notification(通知)内容来表示已阅读通知或跳转相关链接。

### What does the proposed API look like?
目前只能通过 btn 添加一个按钮来实现，不过这样的话可点击面积太小，不是很方便使用，样式上也不是很美观。能否为notification添加一个onClick，点击响应区域为整个notification的区域。

```
notification.open({
    message: '通知标题',
    description: '通知内容',
    onClick: ()=>{
        // 关闭当前通知并设为已读或跳转到通知相关的链接
    }
})
```

**Comment by focus0802** [comment]
有没有这个考虑啊

**Comment by zombieJ** [comment]
哦哦~你可以试试这个：https://ant.design/components/notification-cn/#components-notification-demo-with-btn

**Comment by focus0802** [comment]
你可以仔细看一下我的描述😄，btn可点击面积比较小，我提这个需求是因为之前用element的时候notification是有这个的

**Comment by afc163** [comment]
可以有，类似原生的通知。

**Comment by flydeB** [comment]
const args = {
            message: '消息通知',
            description: this.state.msg,
            duration: 3,
            key,
            onClick:()=>{
                console.log(2345)
            }
          };
          notification.open(args);
}

There is no response？why？
