### ISSUE TITLE
The <Carousel> cannot autoplay correctly when toggle the autoplay prop by setState() method

### ISSUE THREAD

**Issue by Kerlli** [ant-design/ant-design#11830]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
System: macOS 10.13.6 Browser: Chrome 68

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kxw05zm5nv)

### Steps to reproduce
In the demo provided, toggle the switch and watch the behavior(autoplay) of Carousel then you'll get this issue.

### What is expected?
The Carousel Component should autoplay(stop) when 'autoplay' is set from 'false(true)' to 'true(false)'.

### What is actually happening?
The autoplay behavior of Carousel Component not working as expect.

**Comment by Kerlli** [comment]
It seems like a bug of react-slick, after resizing the browser window, it works again... Anyway, thanks.

**Comment by lidianhao123** [comment]
I think it's not react-slick bug.
I see all code https://github.com/ant-design/ant-design/blob/master/components/carousel/index.tsx
It have not handle when props.autoplay is change.
Do you see the Reproduction link detail?
