### ISSUE TITLE
antd select 下拉非常慢

### ISSUE THREAD

**Issue by ajwang** [ant-design/ant-design#11843]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
线上

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/f025e169](https://riddle.alibaba-inc.com/riddles/f025e169)

### Steps to reproduce
https://riddle.alibaba-inc.com/riddles/f025e169

### What is expected?
点击下拉快速显示

### What is actually happening?
好几秒

**Comment by afc163** [comment]
https://codesandbox.io/s/012367ry80

一个非常奇怪的 bug，只有长词在 chrome 下会有性能问题。

**Comment by afc163** [comment]
目测是 chrome 的一个渲染性能 bug。

**Comment by zombieJ** [comment]
chrome mark as [wontFix](https://bugs.chromium.org/p/chromium/issues/detail?id=876965&can=2&q=getboundingclientrect&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)
