### ISSUE TITLE
Pagination的bug

### ISSUE THREAD

**Issue by LinHengrui** [ant-design/ant-design#11842]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
谷歌浏览器

### Reproduction link
[https://github.com/ant-design/ant-design/tree/master/components/pagination](https://github.com/ant-design/ant-design/tree/master/components/pagination)

### Steps to reproduce
使用Pagination组件

### What is expected?
如网站示例一样显示10条 / 页
pageSizeOptions生效

### What is actually happening?
默认显示为10 / Page
使用pageSizeOptions，传入数组作为值，不生效

**Comment by afc163** [comment]
It works: https://codesandbox.io/s/54zz8wyxxx Note that size options select will responsively hide if screen width is too small.

<img width="712" alt="image" src="https://user-images.githubusercontent.com/507615/44471797-41bfe880-a65f-11e8-8358-c1e16d5df336.png">
