### ISSUE TITLE
Fixed column is hengning after opening of the expanded row.

### ISSUE THREAD

**Issue by podeig** [ant-design/ant-design#11841]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
Chrome and Firefox, React 16.4.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zwz60vno0l)

### Steps to reproduce
Create a table with extended rows. Make a column in the table fixed like "fixed: 'right'". Run and click on "plus" to open extended row. Fixed column will hang and not be moved together with extended row.

### What is expected?
Expectation: fixed columns of the parent table must follow extended rows and be on the same place related to the parent rows of the main table.

### What is actually happening?
Fixed column will hang and not be moved together with extended row.

**Comment by yesmeck** [comment]
Fixed columns are not supposed to use with `expandedRowRender` at present.
