### ISSUE TITLE
Table组件一行内多个按钮操作问题

### ISSUE THREAD

**Issue by ringrid** [ant-design/ant-design#1184]
我在行内添加了多个铵钮进行一些便捷操作，比如编辑、删除、开启关闭等，但是我通过Table的onRowclick绑定事件后，无论怎么样都无法取到行内是哪个按钮的操作。
Table：
onRowClick={(record, index, event) => this.handleRowClick(record, index, event)}

handleRowClick(record, index, event) {
    console.log(event.target)
  }

我通过event.target可以看到相应的信息，但是我尝试通过id或name获取，均无法取到数据。
请问应该如何处理多个按钮情形？谢谢

**Comment by benjycui** [comment]
可以直接监听按钮的事件，为什么要用 `onRowClick`?

**Comment by ringrid** [comment]
行内按钮无法直接监听，我尝试在Button上 写onClick={()=>this.handleEdit()}

然后写相应的事件，但根本监听不到，总是提示Uncaught TypeError: Cannot read property 'handleEdit' of undefined

**Comment by ringrid** [comment]
@benjycui 这个我生成按钮的代码
const columns = [
  .......
  {
    title: '操作',
    dataIndex: 'operation',
    key: 'operation',
    render(text, record) {
      return (
        <span>
          <Button id="edit" size="small" onClick={()=>this.handleEdit()}>编辑</Button>
          <span className="ant-divider"></span>
          <Button id="delete" size="small">删除</Button>
        </span>
      );
    }
  },
];

这里直接render的，我的事件写到放Table的Component中，就存在上面说的这样的问题

**Comment by benjycui** [comment]
可以监听，建议认真研究 JavaScript 中的 `this`。

See: http://bonsaiden.github.io/JavaScript-Garden/zh/#function.this

**Comment by ringrid** [comment]
@benjycui  我看了你发的资料，还是没找到对我目前有用的地方。this的作用域的概念我是知道的，我用的是ES6写法，我不知道你说的可以监听是什么概念？如果可以的话还希望能提供更进一步的帮助，谢谢！

**Comment by benjycui** [comment]
```jsx
const columns = [
  .......
  {
    title: '操作',
    dataIndex: 'operation',
    key: 'operation',

    // render 的 `this` 指向什么？
    render(text, record) {
      return (
        <span>
          <Button id="edit" size="small" onClick={()=>this.handleEdit()}>编辑</Button>
          <span className="ant-divider"></span>
          <Button id="delete" size="small">删除</Button>
        </span>
      );
    }
  },
];
```

**Comment by ringrid** [comment]
@benjycui 解决了，谢谢

**Comment by linayanse** [comment]
@benjycui 建议把官网上的示例加上绑定事件。

**Comment by zhoulijie** [comment]
@ringrid 怎么解决的？分享一下

**Comment by ringrid** [comment]
@zhoulijie this的作用域是全局，关键是function的位置。。。

**Comment by Ben07** [comment]
通过箭头函数，this的问题就解决了。
`{title: '操作',key: 'operation',render(text, record) {}`
改为
`{title: '操作',key: 'operation',render:(text, record)=> {}`

**Comment by YDJSZY** [comment]
@Ben07 我的行定义是写在另一个文件import进来的。操作列的render的this是undefined。不知道怎么去绑定这个this到我想要的地方

**Comment by Ben07** [comment]
@YDJSZY 你这种情况的话，可以去看下Function的bind,apply或者call的使用，先拿到你想要的this，然后通过前面的这些，把this给予列的render。或者单纯的把this通过一个参数或者变量传给你那个render

**Comment by YDJSZY** [comment]
这是我现在折中的做法：
var action = function () {
    var self = this;
    return action = function (actionName,args) {
        if(!this[actionName]){
            console.error("The function "+actionName+" is not exits");
            return;
        }
        this[actionName](args)
    }.bind(self)
}
var model = {
    fields:[
        {
            title: 'ID',
            dataIndex: 'id',
            key: 'id',
            sorter:true,/*服务端排序*/
            render: text => <a href="#">{text}</a>,
        },
       {
            title: '操作',
            key: 'action',
            fixed: 'right',
            width: 100,
            render: (text, record, context) => {
                return <span>
                          <a href="#" onClick={action.bind(undefined,"edit",record)}>编辑</a>
                          <span className="ant-divider"/>
                        </span>
            },
        }
]
}
在另一个文件import上面的代码。并执行action.apply(this);绑定this到我想要的地方。只是觉得这样挺麻烦的。不知道为什么它没有自动在render里绑定this，比如到当前table组件里。

**Comment by travonf** [comment]
Mark
