### ISSUE TITLE
环境不同 一个是1x 一个是3x 怎么兼容这个图标呢

### ISSUE THREAD

**Issue by Vsion** [ant-design/ant-design#11855]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
环境不同 一个是1x 一个是3x 怎么兼容这个图标呢

### Reproduction link
[https://ant.design/components/icon-cn/](https://ant.design/components/icon-cn/)

### Steps to reproduce
`<Icon type="arrow-salt" /> <Icon type="arrows-alt" />`
同一套代码 环境不同 一个是1x 一个是3x 怎么兼容这个图标呢

### What is expected?
同一套代码 不同环境 可以兼容 这个图标 

### What is actually happening?
只能兼容一个环境

**Comment by yesmeck** [comment]
1.x 和 3.x 就是不兼容的

**Comment by Vsion** [comment]
新老项目 引入同一个组件, 只能自己做兼容了
