### ISSUE TITLE
Border between tree rows

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#11852]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Our UI design calls for a border between all row items. With the `Tree` component it is non trivial to add a border to the bottom of each element of a tree item. It would be easier to implement a border if there were a div which contained the `spans` which ant places the content in. Then the user could just apply styles to the tree node container.

Here is a rough example of what our desired borders look like (ignore the colors and alignment as they require more tweaking :): https://codepen.io/megawac-the-scripter/pen/PdqWwP?editors=0110 

### What does the proposed API look like?
Have the tree node contents separated in a div which is separated from the child `ul` of any decedent tree

**Comment by zombieJ** [comment]
We have the plan to use virtual list in Tree. It will make TreeNode only contains self content.
Currently, the better way is still modify with css as your sample code.

ref branch: https://github.com/react-component/tree/tree/perf
