### ISSUE TITLE
Optional Indentation for nested tables

### ISSUE THREAD

**Issue by cnagadya** [ant-design/ant-design#11850]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

I previously raised [issue #11788
](https://github.com/ant-design/ant-design/issues/11788#issuecomment-414736470) regarding the empty cell added to nested table. Was however told this is to create the indentation and was wondering whether this could be made optional 

### What problem does this feature solve?
Make indentation of nested tables optional

### What does the proposed API look like?
On the nested table: 
<Table
     indent={false}..../>

**Comment by afc163** [comment]
You can try add styles to nested table like `marginLeft: '10px'` or `marginLeft: '-10px'`.
