### ISSUE TITLE
Seperate Pagination while using built in pagination & allow top component put into table

### ISSUE THREAD

**Issue by pbrink231** [ant-design/ant-design#11853]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to move the pagination around so using a seperate pagination would be helpful but I dont know how to hook it up so I can easily use the filters and everything else already built into the table.  Is there an easy way to do this.  Thinking an easy way would be to add an explicit visible:false so you can still change the pages manually but wont see the built in pagination.  All updates would be seen in filters update so can update seperate pagination as needed.

Also main reason for this is because moving pagination to the top makes a large blank space on the left I would like to put a title or buttons.  Secondary/Seperate request would be to have this space usable by passing a component into the table that will be placed top of the table and left of the pagination if it is in the top.  This would also work for the bottom with the same thing floating left if pagination.

### What does the proposed API look like?
```
<Table
pagination={visible: false, current: this.state.current}
topComponent=MyTopComponent
bottomComponent=<MyBottomComponent />
/>
```

**Comment by afc163** [comment]
```jsx
<MyTopComponent />
<Table pagination={false} />
<MyBottomComponent />
```

**Comment by ChambreNoire** [comment]
Doesn't this imply managing one or more external <Pagination> components just for the sake of positionning, which if one needs sorting, filtering etc means rewriting a ton of functionality offered by the <Table> component?
