### ISSUE TITLE
Upload.Dragger doesn't catch file drop on whole area

### ISSUE THREAD

**Issue by jakubknejzlik** [ant-design/ant-design#11869]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
macos 10.13.6 (17G65), chrome Version 68.0.3440.106 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/932nxpzmny)

### Steps to reproduce
It's observable on any Upload.Dragger component (each dragger has padding defined for upload wrapper (16px)). The minimal reproduction link shows the extreme version of it by updating the padding to 50px.

### What is expected?
Upload.Dragger should handle file drop on whole area.

### What is actually happening?
Padding on class .ant-upload.ant-upload-drag ("16px 0") is causing the 16px from bottom/top are not handled as file drop (by default browser usually just displays the file). 

---
This gap could be:
1) removed by setting padding to zero
2) move the padding to .ant-upload-drag-container which can be observed here: https://codesandbox.io/s/5x9wkk9ljk

**Comment by meharfatimakhan** [comment]
What if I still want to trigger drop functionality here?
