### ISSUE TITLE
Table使用scroll参数之后，点开额外的行样式会乱

### ISSUE THREAD

**Issue by houdingding** [ant-design/ant-design#11860]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
MAC10.13.4  chrome 67.0.3396.99 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ymxqp678lz)

### Steps to reproduce
无

### What is expected?
样式需要怎么设置么

### What is actually happening?
样式错乱

**Comment by yesmeck** [comment]
expandedRowRender 不能跟 fixed 混用。
