### ISSUE TITLE
Table 内容较多时或者编辑时不够友好

### ISSUE THREAD

**Issue by w3286879** [ant-design/ant-design#11861]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在做编辑表格时，表格的列需要下拉框来选择，这个时候下拉框就会把内容撑大，造成列头和下面的下拉框不一致。

### What does the proposed API look like?
能支持多个不同分辨率，同时集成进编辑表格。

**Comment by afc163** [comment]
建议自行业务探索实现。
