### ISSUE TITLE
Badge animation bug while setting 0 to 1 and 1 to 0

### ISSUE THREAD

**Issue by lhz516** [ant-design/ant-design#11870]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
Latest Chrome and Firefox on Win 10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6yvloq809z)

### Steps to reproduce
Click minus button to set number from 1 to 0; click plus button to set number from 0 to 1

### What is expected?
Badge animations happen always at the same position

### What is actually happening?
Badge animations were at wrong places. After the animation, the badge jumps to correct position.

### Additional comments:
This example is actually from [antd documentation](https://ant.design/components/badge/#). However, it works on the documentation.

**Comment by afc163** [comment]
Fixed in 22162fe04ba8fc8d32a1e31d66e83a01b5ca87c8
