### ISSUE TITLE
公共盒子阴影样式  @shadow-1-up 应该为 -2px

### ISSUE THREAD

**Issue by BobiY** [ant-design/ant-design#11873]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
无

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less ](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less )

### Steps to reproduce
无

### What is expected?
@shadow-1-up            : 0 -2px 8px @shadow-color;

### What is actually happening?
@shadow-1-up            : 0 -2px 8px @shadow-color;

**Comment by afc163** [comment]
PR is welcome~

**Comment by dancerphil** [comment]
Just make describe correct

### What is expected?

@shadow-1-up : 0 -2px 8px @shadow-color; (after fix)

### What is actually happening?

@shadow-1-up : 0 2px 8px @shadow-color; (before fix)
