### ISSUE TITLE
升级后，TreeSelect开启showSearch，检索出的叶子节点被折叠

### ISSUE THREAD

**Issue by younth** [ant-design/ant-design#11881]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
antd 3.8.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0vmlq3pkm0)

### Steps to reproduce
1. 打开链接
2. 搜索关键词 美
3. 所有节点为包含 美 的被检索出来，但是被折叠起来了

### What is expected?
检索出的叶子节点直接展示出来。

### What is actually happening?
升级到最新版的antd，检索出的叶子节点被隐藏

---
antd 3.4.1是正常的，可切换到3.4.1看正常的效果

**Comment by younth** [comment]
3.8.1也没有问题，是3.8.2修复treeNode问题造成的吗

**Comment by zombieJ** [comment]
能否上截图，我这边看是好的：
![kapture 2018-08-25 at 21 31 40](https://user-images.githubusercontent.com/5378891/44618740-56de8680-a8ae-11e8-84df-17ebafbed696.gif)
