### ISSUE TITLE
Some features are not displayed properly in the codepen

### ISSUE THREAD

**Issue by relax-admin** [ant-design/ant-design#11886]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0-beta.0

### Environment
chrome

### Reproduction link
[https://codepen.io/xiaoxinmiao/pen/WgrLZX?&editors=001](https://codepen.io/xiaoxinmiao/pen/WgrLZX?&editors=001)

### Steps to reproduce
normal display:https://codepen.io/xiaoxinmiao/pen/XPXoWB
not normal displaying:https://codepen.io/xiaoxinmiao/pen/WgrLZX?&editors=001

### What is expected?
normal display

### What is actually happening?
not normal displaying

![1](https://user-images.githubusercontent.com/18659289/44625947-5f829b80-a946-11e8-9b52-c5d15a98333d.png)

**Comment by afc163** [comment]
Thx for reporting.
