### ISSUE TITLE
Assign id Attribute to tab pane element for automation purposes.

### ISSUE THREAD

**Issue by salman1995** [ant-design/ant-design#11899]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0-beta.0

### Environment
React-redux Application

### Reproduction link
[https://ant.design/components/tabs/](https://ant.design/components/tabs/)

### Steps to reproduce
Assign id to tab pane element.
See generated markup.

### What is expected?
When I assign id attribute to TabPane element, it should be reflected in markup generated.

### What is actually happening?
I can't see assigned id in generated markup of tab pane.

**Comment by kfrajtak** [comment]
Hi,
I am afraid TypeScript definitions were not updated. It is reporting an error when `id` is provided (NPM version 3.23.4).
Thanks,
Karel
