### ISSUE TITLE
Modal 是否能增加onEnter事件

### ISSUE THREAD

**Issue by houdingding** [ant-design/ant-design#11907]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
方便用户在输入表单完成后，enter键触发提交事件

### What does the proposed API look like?
onEnter={function}

**Comment by yesmeck** [comment]
这种情况应该用 <kbd>Tab</kbd>  focus 到提交按钮后再按 <kdb>Enter</kdb>，不然容易误操作。
