### ISSUE TITLE
The placeholder does not display correctly when the value of the select form item is cleared

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#11905]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
chrome 68, mac 10.14

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vvyonjp2ql)

### Steps to reproduce
Initialize the value of the selected form item and then clear it using the form

### What is expected?
show the placeholder

### What is actually happening?
no placeholder

**Comment by yoyo837** [comment]
使用`form.setFieldsValue` 设置`Select`值为空时，其`placeholder`没有正确显示，`mode="multiple"`时设置为`[]`却可以.

**Comment by afc163** [comment]
```diff
    this.props.form.setFieldsValue({
-     note: null,
+     note: undefined,
    });
```

https://github.com/ant-design/ant-design/issues/11330#issuecomment-405826778
