### ISSUE TITLE
drop down box does not automatically adjust the position when the height of the text box changes 

### ISSUE THREAD

**Issue by xuzhengquan** [ant-design/ant-design#11900]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.14

### Environment
Mac OS, Chrome(latest)

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
select multiple selection

### What is expected?
drop down box automatically adjust the position

### What is actually happening?
The height of the text box changes, and the position of the selection box does not adjust automatically, affecting the display of options in the text box.

**Comment by afc163** [comment]
Please upgrade to 3.x, 2.x is not maintained any more.
