### ISSUE TITLE
upload 显示成功，但后台提示失败

### ISSUE THREAD

**Issue by believeZJP** [ant-design/ant-design#11904]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
mac chrome

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
拷贝上传组件代码到项目
<img width="868" alt="props" src="https://user-images.githubusercontent.com/15198091/44657314-00e51c80-aa2f-11e8-820c-359fa7ab01e3.png">
<img width="757" alt="upload" src="https://user-images.githubusercontent.com/15198091/44657370-2b36da00-aa2f-11e8-9704-9ac1c26daea8.png">
<img width="578" alt="error" src="https://user-images.githubusercontent.com/15198091/44657381-3d187d00-aa2f-11e8-81e0-e19c89dc88b8.png">

### What is expected?
上传成功

### What is actually happening?
上传返回错误

**Comment by afc163** [comment]
建议排查后端问题。
