### ISSUE TITLE
Option of AutoComplete Select should not use value as a key, as value may not be unique and React requires keys to be unique

### ISSUE THREAD

**Issue by mjenczmyk** [ant-design/ant-design#11909]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
Chromium 68.0.3440.75, Firefox ESR 52.9.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7yxp0vjv90)

### Steps to reproduce
Use `Select` component and pass `key` and `value` properties to its `Select.Option`s. Make sure that there are two same `value` values. Notice warning about duplicate keys in the browser's console.

### What is expected?
`key` property in `Select.Option` component is used as component key.

### What is actually happening?
`value` property is being used as component key instead.

---
One can notice the bug while looking at [https://github.com/ant-design/ant-design/blob/3.8.4/components/select/index.tsx](https://github.com/ant-design/ant-design/blob/3.8.4/components/select/index.tsx), the `Select.Option` and `Select.OptGroup` components does not support `key` property as one could expect after reading [documentation](https://ant.design/components/select/#Option-props). 

```
export interface OptionProps {
  disabled?: boolean;
  value?: string | number;
  title?: string;
  children?: React.ReactNode;
}

export interface OptGroupProps {
  label?: React.ReactNode;
}
```

That issue was raised before in #11074.

**Comment by afc163** [comment]
https://codesandbox.io/s/61875yq9xr

**Comment by mjenczmyk** [comment]
Thanks, so I should use `AutoComplete` instead? Why shouldn't we support passing `key` to make sure that it's unique?

**Comment by afc163** [comment]
I don't know what component you should use but probably you need `Select[showSearch]`, you can checkout it. But still, value of AutoComplete should not be duplicated.

**Comment by damiangreen** [comment]
So was there a solution?

**Comment by syberen** [comment]
This still appears to be a problem. I can set a key prop on `<AutoComplete.Option>`, however as soon as I set a value prop this is used as the key.

I understand that value should not be duplicated, but in some cases this is not avoidable, for example when using a Belgian zip code API, where multiple towns can have the same zip code.

**Comment by tony-scio** [comment]
I'm hitting this same issue. Two `AutoComplete.Options` cannot have the same `value`, even though their `key`s are unique.

Did anyone come up with a workaround? I can't tell why this issue was closed.

**Comment by De-Santa** [comment]
@tony-scio don`t use `value` prop on `Option`, use only `key`, where `key`=`value`

**Comment by damiangreen** [comment]
I've worked around this issue like this:
`import { any } from 'ramda'

// https://github.com/ant-design/ant-design/issues/11909

export const autocompleteSelectHack = <T extends { id: string }>(
  keyName: keyof T,
) => (acc: T[], item: T): T[] => [
  ...acc,
  any(x => x[keyName] === item[keyName], acc)
    ? { ...item, keyName: `${item[keyName]} [${item.id}]` }
    : item,
]
`

then to consume:
`const makeOptions = (data: DataResponse, searchFilter: string) =>
  data.components.componentPageEntries
    .reduce(autocompleteSelectHack('name'), [])
    .sort((a, b) => alphabetically(a.name, b.name))
    .map(x => makeHighlightedOption(x, searchFilter, 'name'))
`

**Comment by thesocialdev** [comment]
> I don't know what component you should use but probably you need `Select[showSearch]`, you can checkout it. But still, value of AutoComplete should not be duplicated.

This misses the point of collecting a new data from the AutoComplete input.

**Comment by ops1ops** [comment]
> https://codesandbox.io/s/61875yq9xr

@afc163 your example does not work in the following situation:
```
const data = [
  { id: "1", title: "sun", subtitle: "1" },
  { id: "2", title: "sun", subtitle: "2" },
  { id: "3", title: "sun", subtitle: "3" }
];
...
<AutoComplete optionLabelProp="value">
  {data.map(({ id, title, subtitle }) => (
    <Option key={id} value={title}>
      <p>{title}</p>
      <p>{subtitle}</p>
    </Option>
  ))}
</AutoComplete>
```
so i consider it's a bug and easiest way to solve it - let pass your own key for option

**Comment by damiangreen** [comment]
@afc163  this case does require re-opening

**Comment by AnirudhaGohokar** [comment]
I have a hacky solution for this. will post modified codepen here for reference. Only thing is you wont be able to see selection highlights.

**Comment by N00nDay** [comment]
> > https://codesandbox.io/s/61875yq9xr
> 
> @afc163 your example does not work in the following situation:
> 
> ```
> const data = [
>   { id: "1", title: "sun", subtitle: "1" },
>   { id: "2", title: "sun", subtitle: "2" },
>   { id: "3", title: "sun", subtitle: "3" }
> ];
> ...
> <AutoComplete optionLabelProp="value">
>   {data.map(({ id, title, subtitle }) => (
>     <Option key={id} value={title}>
>       <p>{title}</p>
>       <p>{subtitle}</p>
>     </Option>
>   ))}
> </AutoComplete>
> ```
> 
> so i consider it's a bug and the easiest way to solve it is to let pass your own key for option
> 
> upd:
> You even have this bug in your own documentation page :)
> 
> ![image](https://user-images.githubusercontent.com/49243022/85026299-2b164a00-b181-11ea-851c-6e49263f385d.png)

Agreed! I am dealing with the same issue. I have to set the value property explicitly because I am showing a custom Option as follows:

`
const _materials = [
   { value: '3" Nails', type: "5lb Box", color: "N/A" },
   { value: '3" Nails', type: "", color: "N/A" },
   { value: "B & B", type: "", color: "" },
   { value: "Caulk", type: "Solar Seal", color: "" },
   { value: "Caulk", type: "", color: "" },
   { value: "Caulk", type: "Flintbond", color: "N/A" },
   ...
];

const options = _materials.map((m) => (
    <Option
      key={JSON.stringify(m)}
        value={m.value}
      type={m.type}
      color={m.color}
      style={{ borderBottom: "1px solid #f0f0f0" }}
    >
      <div>
        <b>{m.value}</b>
      </div>
      {m.type && (
        <div style={m.color ? { width: "50%", display: "inline-block" } : {}}>
          Type: {m.type}
        </div>
      )}
      {m.color && (
        <div style={m.type ? { width: "50%", display: "inline-block" } : {}}>
          Color: {m.color}
        </div>
      )}
    </Option>
  ));
`

In this scenario I have several options and some of them may have the same value but will not share the same type or color.

I have seen it suggested to others to use a `Select` instead but the issue is this list is not all inclusive nor is it possible to ever get an all inclusive list for this scenario so the user has to have the ability to select/type values that do not exist in the list itself.

**Comment by N00nDay** [comment]
My temporary hack to solve my use case is below:

```
const onSelect = (p, i) => {
    const material = form.getFieldValue("material");
    material[i].material = p.material;
    material[i].type = p.type;
    material[i].color = p.color;

    form.setFieldsValue({
      material,
    });
  };
```
I replaced the value prop with material prop and then onSelect I setFieldsValue to overide the JSON key that was set. The only downfall with this situation is that because the value does not match the key the option will not be highlighted in the dropdown. Other than no highlight it seems to work so far.

**Comment by bvnflatliner** [comment]
I found a workaround.
```
const options = [
    {'value' = 'sometest.com - somecategory1', 'realValue' = 'sometest.com', 'category' = 'somecategory1},
    {'value' = 'sometest.com - somecategory2', 'realValue' = 'sometest.com', 'category' = 'somecategory2'},
    {'value' = 'sometest.com - somecategory3', 'realValue' = 'sometest.com', 'category' = 'somecategory3'}
];

onDomainSelect = (value, option, form) => {
    form.change('domain', option.realValue);
    form.change('category', option.category);
}
```
form - is a final-form instance

**Comment by mleister97** [comment]
For me it works to just define the key

e.g.
```
{ value: 'mail@mail.com', label: 'mail@mail.com (Darwin Junior)', key: `customKey` }
```

**Comment by vishal-pixsoffice** [comment]
Thank you @mleister97, This is the actual solution for me 🙌
