### ISSUE TITLE
自定义组件作为formItem时，校验rules validator中，callback返回异常时，怎么标红指定表单元素，或者不标红框？

### ISSUE THREAD

**Issue by shaoxi2093** [ant-design/ant-design#11903]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义组件作为formItem时，校验rules validator中，callback返回异常时，怎么标红指定表单元素，或者不标红框？
目前自定义组件，例如Card包起来的一套，类似一个表单用户输入组合，因为这个组合表单可能存在多个，又存在于一个父表单之中。考虑到最终父表单取值的复杂性，因此采用了这种封装自定义组件作为FormItem的方式。
但是想利用rules.validator 来校验这个组件的value（Object）来做校验时，校验是正常的，但是标记却出了问题，校验错误时，自定义组件中的所有输入表单元素全部被加上了红色error边框。查找文档，未找到能针对指定元素的标红方案。

### What does the proposed API look like?
getFieldDecorator的options中，希望加入一个validateRefs，并搭配rules.validator使用，rules.validator的callback能加一个参数找到指定的表单元素。

**Comment by afc163** [comment]
> 但是想利用rules.validator 来校验这个组件的value（Object）来做校验时，校验是正常的，但是标记却出了问题，校验错误时，自定义组件中的所有输入表单元素全部被加上了红色error边框。

可以用 codesandbox 把这个重现出来，我们来看看有没有什么手段解决。

**Comment by shaoxi2093** [comment]
https://codesandbox.io/s/7y3wlnm531 写了个简化版的，问题能重现

**Comment by zombieJ** [comment]
自定义带多个 input 比较特殊，可以自己搞一下 css：https://codesandbox.io/s/q7xp9m53zw

**Comment by shaoxi2093** [comment]
@zombieJ emmm，这又起了一个问题，当你初始化都为空的情况下，输入其中一个输入框，也会导致校验这个自定义组件的所有input，不能完全适用，校验的时机不太对。validator好像并不能适用于这个场景，我的

**Comment by xiaofengqqcom123** [comment]
那有什么解决方案吗？我这边还是这样

**Comment by shaoxi2093** [comment]
> 那有什么解决方案吗？我这边还是这样

有替代方案，将form作属性传进组件，不过对大规模组件改造就比较麻烦

**Comment by chaserstrong** [comment]
> > 那有什么解决方案吗？我这边还是这样
> 
> 有替代方案，将form作属性传进组件，不过对大规模组件改造就比较麻烦

请问这个将form作为属性传入怎么理解呀？ 我这边也遇到了这个问题。

**Comment by wangyong93** [comment]
> @afc163 https://codesandbox.io/s/7y3wlnm531 写了个简化版的，问题能重现

你这个还是没解决问题呀，自定义的组件，校验还是全部标红了。

**Comment by zhumengyue** [comment]
这个现在有比较好的解决方案吗

**Comment by IvanLiang1025** [comment]
我也遇到这个问题

**Comment by xiaoliu-99** [comment]
请问有解决方案吗
