### ISSUE TITLE
InputNumber can input strange string，like '..abcd'

### ISSUE THREAD

**Issue by codetker** [ant-design/ant-design#11918]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This is a problem <input type="number" /> has.When type="number", user cannot input other words except numbers and special charactor like "  - e . "But while entering "--"、".."、"1.2.3." ,you will find it can enter any other charactor now.I suppose we can improve this situation by parsing this.target.value in function named onChange(or onPress)

### What does the proposed API look like?
InputNumber can only input number like '0.1','-0.1',but can not input strange string like '  abcd',through it turns out value '',but looks odd.

**Comment by afc163** [comment]
It is by designed, like `<input type="number" />`.
