### ISSUE TITLE
Antd and Next.js integration

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#11913]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
nodejs, chrome browser

### Reproduction link
[https://github.com/aditya-padhi-kbl/antdnextjspoc](https://github.com/aditya-padhi-kbl/antdnextjspoc)

### Steps to reproduce
1. clone the repo (https://github.com/aditya-padhi-kbl/antdnextjspoc)
2. cd into it.
3. yarn install
4. yarn start

then fo the the next.config.js file
in line number 6 change the value of cssModules from false to true (this enables on demand loading of css classes) or css module loading.
this works for my custom css files but doesn't work for antd.css files.
My intention is to reduce the initial page load time

### What is expected?
css module loading should work for antd.css files as well

### What is actually happening?
The antd.css files are not loading.

---
I am trying to integrate antd with nextjs for server side rendering, so it will be nice to have support for css module loading feature for antd on server side.

**Comment by yesmeck** [comment]
You should not enable css module for antd.css
