### ISSUE TITLE
antd3.8.4空格键异常触发事件bug 

### ISSUE THREAD

**Issue by junjie-lean** [ant-design/ant-design#11915]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
MacOSX 10.13.4/Chrome 68/React16.4.2

### Reproduction link
[https://github.com/ant-design](https://github.com/ant-design)

### Steps to reproduce
你好，我遇到个情况，在一个Button组件上绑定了一个click事件，我点击此按钮，正常触发了该事件。奇怪的是，我鼠标在点击了一次按钮后，不移出Button的显示范围，同时按下了空格键，就会立即再触发一次click事件。多次按下空格，就会触发多次click事件。事实上，并非只有Button组件会触发click事件，这个bug导致还会导致CheckBox触发onChange事件，Modal触发显示/隐藏的事件，请作者关注下此问题。

### What is expected?
移除异常的事件触发机制

### What is actually happening?
空格键异常触发了其他事件

**Comment by yesmeck** [comment]
这是预期的行为，因为点击按钮后焦点还在按钮上。

**Comment by junjie-lean** [comment]
是的，点击后焦点还在按钮上，可是正常预期是click触发事件，而不是keydown触发事件，不是吗？

**Comment by afc163** [comment]
空格会触发按钮点击，这是浏览器默认行为。
