### ISSUE TITLE
form的表单校验进了validator的方法了，但是却没有返回错误信息。

### ISSUE THREAD

**Issue by ranzhu123** [ant-design/ant-design#1191]
![image](https://cloud.githubusercontent.com/assets/12227617/13737765/bd4b3546-e9fa-11e5-9def-cd766621536d.png)
可以获取值，但是进了callback之后页面却没有反应是怎么回事呢？

<FormItem
              label="确认密码："
              {...formItemLayout}
              required
              hasFeedback>
              <Input type="password" {...rePasswdProps} placeholder="两次输入密码保持一致" autoComplete="off"
                     /*value={this.state.confirmPassword} onChange={this.setConfirmPassword}*/ onContextMenu={noop} onPaste={noop} onCopy={noop} onCut={noop}/>
            </FormItem>

**Comment by benjycui** [comment]
建议先阅读：http://doc.zengrong.net/smart-questions/cn.html

然后提供可重现的 demo：http://codepen.io/anon/pen/pgdXYp?editors=001
