### ISSUE TITLE
Select等支持filterOption属性的控件，在无输入内容时，希望可以触发filterOption的function

### ISSUE THREAD

**Issue by liyuanqiu** [ant-design/ant-design#11927]
- [*] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
filterOption这个属性可以自定义筛选方式，那么当用户无输入时，依然希望可以自定义筛选，我认为无输入也是一种输入。产生需求的场景是我在使用Select时，Option有非常多（数千个），这时我不希望用户在无输入的情况下，依然给他弹出所有的Option供其选择，这会非常卡，在这种场景下，如果filterOption也支持无输入时进行筛选，则可以满足这个需求。

### What does the proposed API look like?
```javascript
<Select
  filterOption={(inputValue, option) => {
    if (inputValue === '') {
      return false;
    }
    ...
  }}
>
  ...
</Select>
```

**Comment by yesmeck** [comment]
建议通过 `onSearch` 来控制 Option 的展示。参考 https://ant.design/components/select/#components-select-demo-select-users
