### ISSUE TITLE
There is no strict match between Select value and Option

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design#11922]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[https://codesandbox.io/s/1465m3pk7l](https://codesandbox.io/s/1465m3pk7l)

### What does the proposed API look like?
strictMatch

**Comment by afc163** [comment]
My suggestion is clean up your data before send to Select.

**Comment by code-matt** [comment]
It seems a little crazy that select displays values that are no longer in options after a re-render.  It should default back as if nothing is selected when this case happens

**Comment by zombieJ** [comment]
hi @code-matt, 
When user edit a form and option list is loaded by ajax call, if select remove the value when list is empty, it will case select become empty. Which makes user much more code on handling this.

**Comment by Zhangsw02** [comment]
I don't expect the value of Select to be removed when the value is not contained in option list. At least, the value should not be exposed to user, because the value is usally an ugly uuid.

**Comment by ayqy** [comment]
> hi @code-matt,
> When user edit a form and option list is loaded by ajax call, if select remove the value when list is empty, it will case select become empty. Which makes user much more code on handling this.

**If ...** means it's somehow a special case, but in more common cases (e.g. simple static forms), current behavior is definitely an obvious bug.

On the other hand, when we build dynamic forms with React, common recommended practice is something like this:

```
// with Redux
Server Response Data -> Selector -> Store -> Container Component -> View Component
// and without Redux
Server Response Data -> Selector -> State -> View Component
```

If

> option list is loaded by ajax call

**Selector layer should filter and ignore empty data if necessary**, don't you think so ? @afc163 @zombieJ @yesmeck 

FYI:

- [Selector](https://github.com/reduxjs/reselect)

**Comment by zombieJ** [comment]
hi @ayqy,
It's common usage on the edit exist form data & select option from different ajax call. Specially expansive list cost fetch. Select can even not fetch the data unless user operation on it.

If you want to keep Option sync, you can wrap a HOC to handle this.

**Comment by ayqy** [comment]
Copied. It means "We do not supports this basic usage, because there is an advanced case to cover." :see_no_evil:
