### ISSUE TITLE
我使用的是compass，每次都需要自动下载字体文件，如何本地加载好

### ISSUE THREAD

**Issue by jinjiaxing** [ant-design/ant-design#1193]
Request URL:http://at.alicdn.com/t/font_1452596235_7047422.woff

每次都要去请求这个

如何直接下载到本地使用，简单修改，而不是将你们的css文件一行一行修正

**Comment by jinjiaxing** [comment]
补充一下，没有使用webpack，使用的是gulp+browerify

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1070
