### ISSUE TITLE
Antd and Mobile First Application

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#11930]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
nodejs, chrome browser

### Reproduction link
[https://github.com/aditya-padhi-kbl/antdnextjspoc](https://github.com/aditya-padhi-kbl/antdnextjspoc)

### Steps to reproduce
Pull the application from the github repo and do yarn install
then yarn dev

### What is expected?
Application should work

### What is actually happening?
It is working.  I am planning to do a mobile first web app based on antd.  I am not sure if I am using the correct antd library or should I look for separate antd application

**Comment by yesmeck** [comment]
You should use https://github.com/ant-design/ant-design-mobile
