### ISSUE TITLE
Table里的dataSource有children属性时会出现expandedRowRender的加号图标

### ISSUE THREAD

**Issue by LDmin** [ant-design/ant-design#11937]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
Chrome版本 68.0.3440.106（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j4vq1x3jvw)

### Steps to reproduce
import React from "react";
import ReactDOM from "react-dom";
import { Table, Button } from "antd";
import "antd/dist/antd.css";

class App extends React.Component {

  render() {
    const dataSource = [{
      key: '1',
      name: '胡彦斌',
      age: 32,
      address: '西湖区湖底公园1号',
      children: 1,
    }, {
      key: '2',
      name: '胡彦祖',
      age: 42,
      address: '西湖区湖底公园1号',
    }];

    const columns = [{
      title: '姓名',
      dataIndex: 'name',
      key: 'name',
    }, {
      title: '年龄',
      dataIndex: 'age',
      key: 'age',
    }, {
      title: '住址',
      dataIndex: 'address',
      key: 'address',
    }];
    return (
      <Table dataSource={dataSource} columns={columns} />
    );
  }
}

ReactDOM.render(<App />, document.getElementById("root"));

### What is expected?
不出现加号图标

### What is actually happening?
出现加号图标

**Comment by afc163** [comment]
It is by designed, to allow async loading data when click plus icon.

**Comment by qianyuchang** [comment]
> It is by designed, to allow async loading data when click plus icon.

so is there any events or api  can i listen plus icon click？

**Comment by afc163** [comment]
Duplicate of #1365
