### ISSUE TITLE
希望form表单提交的时候能够获取到标准化的值（非normalize）

### ISSUE THREAD

**Issue by top-soft** [ant-design/ant-design#11935]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
form 表单提交通过了validateFields的验证，里面获取的values，就是准备往后台传递的结果，但是往往需要对这个些值进一步处理（当然你可以在后台完成），我更喜欢在前台完成，最近有个需求，频率 时间   每天/周/月/年    时间，如果是每天 时间应该是HH:mm:ss，每周应该是字符串一/二...，每月应该是 DD HH:mm:ss等等，显示日期的格式不同可以根据选择频率不同去改变时间的format，但是提交的时候里面的日期类型都是清一色的Moment，这就尴尬了，我还得处理一遍。

### What does the proposed API look like?
通过组件上添加一个函数（normalizeSubmit），这个函数在提交的时候调用，准确说在this.props.form.validateFields()执行完成后执行，添加的这个函数（normalizeSubmit）能获取到当前组件的value，并且能获取到this.props.form.validateFields()执行后的values，该函数（normalizeSubmit）返回最终生成的values，就是this.props.form.validateFields((err,values)=>{})中的values。
中文不好，不知道描述明白没有。

**Comment by qiqiboy** [comment]
You may need  [react-antd-formutil](https://github.com/qiqiboy/react-antd-formutil#datepicker)

**Comment by afc163** [comment]
建议自行在 validateFields 中处理数据后再提交到后台。

**Comment by hengkx** [comment]
现在是这样处理的
```js
this.props.form.validateFields(async (err, values) => {
      if (!err) {
        const record = {};
        Object.keys(values).forEach(key => {
          const field = find(model.modelForm, { fieldName: key });
          if (values[key]) {
            if (field.type === 'DATEPICKER') {
              record[key] = values[key].format('YYYY-MM-DD HH:mm:ss');
            } else if (field.type === 'UPLOAD' || field.type === 'IMAGE') {
              record[key] = values[key].map(item => item.response.url);
            } else {
              record[key] = values[key];
            }
          }
        });
      }
});
```

**Comment by papibabi** [comment]
同感，就只想要一个正常的值，别搞这么多花里胡哨的东西。

**Comment by onecompany** [comment]
我认为这是很重要的功能。
比如日期组件，前后台是字符串交互的。
金额组件，前后台是用分做单位的，但用户输入的是元。
级联选择只需要取最后一个值就可以了。。。
如果可以有地方可以做进和出转换，就可以把这些封装起来，否则就要每个地方做手动转换。

**Comment by onecompany** [comment]
我认为这是很重要的功能。
比如日期组件，前后台是字符串交互的。
金额组件，前后台是用分做单位的，但用户输入的是元。
级联选择只需要取最后一个值就可以了。。。
如果可以有地方可以做进和出转换，就可以把这些封装起来，否则就要每个地方做手动转换。

**Comment by dazhi007** [comment]
@hengkx  这个方法哪里来的呢，`**find(model.modelForm, { fieldName: key });**`,根据fieldName获取form表单对象.
