### ISSUE TITLE
时间轴提供横向时间轴的选择

### ISSUE THREAD

**Issue by capaten** [ant-design/ant-design#11949]
[-](url) [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
时间轴可以在各种工作流程中使用，例如入职流程，申请流程，审批流程等，可以使页面简洁美观。但目前时间轴仅有纵向时间轴，而没有横向时间轴，很大程度的限制了使用场景。（相似问题#2166，但并未解决，特再提一次）

### What does the proposed API look like?
可以通过设置某个参数控制横向或者纵向，例如:
`direction = 'horizontal' || 'vertical'`
使用方法可以如下:
```
<Timeline direction = 'horizontal'>
    <Timeline.Item>Create a services site 2015-09-01</Timeline.Item>
    <Timeline.Item>Solve initial network problems 2015-09-01</Timeline.Item>
    <Timeline.Item>Technical testing 2015-09-01</Timeline.Item>
    <Timeline.Item>Network problems being solved 2015-09-01</Timeline.Item>
  </Timeline>
```

**Comment by capaten** [comment]
![timeline](https://user-images.githubusercontent.com/35480932/44776704-4a5a7680-abab-11e8-82e5-e0ed377aad63.jpg)
效果类似这样

**Comment by afc163** [comment]
请使用 Steps。

**Comment by capaten** [comment]
哦哦，好的，抱歉，那请关闭此条需求吧

**Comment by afc163** [comment]
这个没办法，你举的例子语义上是步骤条，不是时间轴。样式上不支持只能爱莫能助了，建议按规范设计 UI。

**Comment by capaten** [comment]
@afc163 我理解错了，确实是步骤条，但我觉得将标签内容仅可以放在右侧或者下方是不是限制了使用需求？毕竟标签内容放在左侧或者上方或者上下方都有标签内容的需求也存在，可否考虑完善该Steps的功能呢？

**Comment by angelsunshuli** [comment]
遇到同样的问题，需要横向时间轴，而且文案部分在上，部分在下，期待完善

**Comment by cnlydia** [comment]
use the a-time-line in vue , the direction = "horizontal" is useless , sad

**Comment by liubei1** [comment]
时间轴和步骤还是有区别的，需要展示水平时间轴无法用步骤代替，步骤的间距都是一样的，没有时间跨度长短对比

**Comment by xrkffgg** [comment]
感觉和 Steps 差不多。

**Comment by wuzhenda** [comment]
` li {
    float: left;
}`
