### ISSUE TITLE
table 加了useFixedHeader并且设置了column 的width,为什么还是对不齐？

### ISSUE THREAD

**Issue by pangbi** [ant-design/ant-design#1194]
想使用固定表头，查阅ant-design的文档，设置useFixedHeader,同时也设置了column的witdh,可是发现table还是不能够对齐 ，求教这是什么原因，目测是设置useFixedHeader后产生滚条挤占了空间
clumn设置
`
const columns = [{
    title: '公司名称',
    dataIndex: 'companyName',
    width: 100
}, {
    title: '客户类型',
    dataIndex: 'customerType',
    width: 100
}, {
    title: '企业类型',
    dataIndex: 'businessType',
    width: 100
}, {
    title: '联系人',
    dataIndex: 'contact',
    width: 100
}, {
    title: '联系电话',
    dataIndex: 'tel',
    width: 100
}, {
    title: '联系操作',
    dataIndex: 'contactType',
    width: 100
}, {
    title: '已上传资质',
    dataIndex: 'zizhi',
    width: 100
}, {
    title: '审核未通过原因',
    dataIndex: 'remark',
    width: 100
}, {
    title: '服务',
    dataIndex: 'fuwu',
    width: 100
}, {
    title: '详细地址',
    dataIndex: 'address',
    width: 50
}, {
    title: 'VIP信息',
    dataIndex: 'vip',
    width: 100
},

];
`

设置数据源
`  
      const dataList = [];
        customerList.resultList.map((data) => {
            dataList.push({
                key: data.id,
                companyName: data.companyName,
                customerType: data.customerType,
                businessType: data.businessType,
                contact: data.contact,
                tel: data.tel,
                contactType: data.contactType,
                zizhi: `已上传${data.totalZizhi}份(审核通过${data.passedZizhi}份)`,
                remark: data.remark,
                fuwu: `开通时间:${data.addDate}`,
                address: data.address,
                vip: data.vip ? "是VIP" : "不是VIP",
            });
        });
`

使用table：
`                        <Table
                            rowSelection={rowSelection}
                            columns={columns}
                            dataSource={dataList}
                            pagination={pagination}
                            onChange={this.handleTableChange}
                            bordered
                            useFixedHeader
                            onRowClick={this.handleRowClick}/>`

运行结果：
[截图](http://182.254.149.236/wp-content/uploads/2016/03/ant_design.png)

**Comment by afc163** [comment]
呃，滚动条，有点难办。

**Comment by afc163** [comment]
加上样式：

```
.ant-table td {
  word-break: break-all;
}
```

**Comment by pangbi** [comment]
@afc163    设置
`.ant-table td {
  word-break: break-all;
}`
这个没有效果的，我目前是用了一个比较笨的方法，在antd的源码的index.css中加了一个样式
`
.ant-table-header{
  overflow-y: scroll;
}
`
使得body和head都产生滚条，来达到对齐的目的，
[效果图](http://182.254.149.236/wp-content/uploads/2016/03/ant.png)

另外，在table中可以设置bodyStyle控制body的样式
`
<Table
                            rowSelection={rowSelection}
                            columns={columns}
                            dataSource={dataList}
                            pagination={pagination}
                            onChange={this.handleTableChange}
                            onRowClick={this.handleRowClick}
                            useFixedHeader
                            bordered
                            bodyStyle={{overflow: 'auto',width:'100%', height: 500}}
                        />
`
为什么没有暴露一个一个headerStyle 来设置head样式的？

**Comment by afc163** [comment]
你也可以试试最后一列或最后几列不设宽度，保证表格布局的弹性，看看还会不会错位。

**Comment by pangbi** [comment]
最后几列不设宽度也不行 ，相差就是body里面滚动条的20px
