### ISSUE TITLE
Collapsed inline menu functionality breaks when menu is inside <Layout.Sider>

### ISSUE THREAD

**Issue by cnagadya** [ant-design/ant-design#11959]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0-beta.2

### Environment
MacOs, Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pjn82yqo97)

### Steps to reproduce
Add the menu inside the Layout Sider 

### What is expected?
When inlineCollapsed is set to true, only icons should be visible 

### What is actually happening?
The text too stays visible

**Comment by afc163** [comment]
It is by designed.
