### ISSUE TITLE
Modal 滚动的时候能否固定原来的页面

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#1195]
http://codepen.io/yesmeck/pen/reMZVN?editors=001

上面的例子，我有一个很长的 modal，能否在滚动 modal 的时候，把原来的页面固定住？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/190 https://github.com/react-component/dialog/issues/9

**Comment by yesmeck** [comment]
:cry:

**Comment by afc163** [comment]
求 PR ~ :smile:

**Comment by yesmeck** [comment]
https://github.com/react-component/dialog/pull/19 等 @yiminghe 的反馈

**Comment by yesmeck** [comment]
那边 merge 了，这边要做什么吗？

**Comment by afc163** [comment]
等那边发布先，这边要加样式吧。

**Comment by afc163** [comment]
@yesmeck rc-dialog@6.0 已经发布了，这边来个升级 pr 如何？

**Comment by afc163** [comment]
ref #978

**Comment by yesmeck** [comment]
@afc163 晚上哈 :smile:

**Comment by yesmeck** [comment]
Upload 也有[新版](https://github.com/react-component/upload/releases)，有打算升级吗

**Comment by afc163** [comment]
升升升，你搞不，分两个 PR ~

**Comment by yesmeck** [comment]
我先看看你们是怎么搞的

**Comment by afc163** [comment]
rc-dialog 也升下如何？

**Comment by yesmeck** [comment]
rc-dialog 我看了下，好像改动比较大，我需要找时间搞一下。
