### ISSUE TITLE
Modal.confirm method's param {centered: true} doesn't working!!

### ISSUE THREAD

**Issue by mengera88** [ant-design/ant-design#11969]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
macOs serria 10.12.6 ,chrome 68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/km64v0qqzo)

### Steps to reproduce
when I set:
 Modal.confirm({
      title: "测试",
      centered: true
    });

the modal doesn't align vertically

### What is expected?
the modal should align vertically

### What is actually happening?
the modal doesn't align vertically

**Comment by zlv-thisF** [comment]
+1
