### ISSUE TITLE
upload组建使用了beforeupload钩子后bug

### ISSUE THREAD

**Issue by hulkyuan** [ant-design/ant-design#11968]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.0

### Environment
mac,chrome,react

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
1.（使用官方demo）点击上传用户头像，并使用 beforeUpload 限制用户上传的图片格式和大小。
2.采用多文件上传，一个文件超过2m限制，一个不超过。
3.onchange事件的filelist最后会变成3个，实际用户只选择了2张图片

### What is expected?
正确的filelist

### What is actually happening?
filelist不正确

**Comment by hulkyuan** [comment]
以下是代码：
const { Upload, Icon, message } = antd;

function getBase64(img, callback) {
  const reader = new FileReader();
  reader.addEventListener('load', () => callback(reader.result));
  reader.readAsDataURL(img);
}

function beforeUpload(file) {
  const isLt2M = file.size / 1024 / 1024 < 2;
  if (!isLt2M) {
    message.error('Image must smaller than 2MB!');
  }
  return  isLt2M;
}

class Avatar extends React.Component {
  state = {
    loading: false,
  };

  handleChange = (info) => {
    if (info.file.status === 'uploading') {
      this.setState({ loading: true });
      return;
    }
    if (info.file.status === 'done') {
      // Get this url from response in real world.
      getBase64(info.file.originFileObj, imageUrl => this.setState({
        imageUrl,
        loading: false,
      }));
    }
  }

  render() {
    const uploadButton = (
      <div>
        <Icon type={this.state.loading ? 'loading' : 'plus'} />
        <div className="ant-upload-text">Upload</div>
      </div>
    );
    const imageUrl = this.state.imageUrl;
    return (
      <Upload
        name="avatar"
        className="avatar-uploader"
       multiple={true} action="//jsonplaceholder.typicode.com/posts/"
        beforeUpload={beforeUpload}
        onChange={this.handleChange}
      >
        {imageUrl ? <img src={imageUrl} alt="avatar" /> : uploadButton}
      </Upload>
    );
  }
}

ReactDOM.render(<Avatar />, mountNode);

**Comment by yang-chenhao** [comment]
同遇到这个问题！我们项目用的版本还要新一点，3.8.1，依然有这个问题。

**Comment by zombieJ** [comment]
设计如此: https://github.com/ant-design/ant-design/pull/9340#issuecomment-364841597
