### ISSUE TITLE
Incomplete propTypes typing causing error with styled-components

### ISSUE THREAD

**Issue by KagamiChan** [ant-design/ant-design#11967]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
macOS 10.13.6, chrome 70

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/526v0783rl)

Please see the `hello.tsx` file, there will be an error prompt

### Steps to reproduce
The following code won't pass compilation with latest `antd`, `styled-components`, `@types/react`, `@types/prop-types` and `typescript`
```
import { Button } from "antd";
import styled from "styled-components";

const StyledButton = styled(Button)`
`;
```

### What is expected?
The above code is compiled to js code

### What is actually happening?
The above code could not be compiled because with the latest react definition, component's or stateless component's `propTypes` should include all keys from `Props` generics, while in current antd definitions it is not the case.

The error message is:
```
Argument of type 'typeof Button' is not assignable to parameter of type 'ComponentType<ButtonProps>'.
  Type 'typeof Button' is not assignable to type 'StatelessComponent<ButtonProps>'.
    Types of property 'propTypes' are incompatible.
      Type '{ type: Requireable<string>; shape: Requireable<string>; size: Requireable<string>; htmlType: Requireable<string>; onClick: Requireable<(...args: any[]) => any>; loading: Requireable<boolean | object>; className: Requireable<...>; icon: Requireable<...>; block: Requireable<...>; }' is not assignable to type 'ValidationMap<AnchorButtonProps> | ValidationMap<NativeButtonProps> | undefined'.
        Type '{ type: Requireable<string>; shape: Requireable<string>; size: Requireable<string>; htmlType: Requireable<string>; onClick: Requireable<(...args: any[]) => any>; loading: Requireable<boolean | object>; className: Requireable<...>; icon: Requireable<...>; block: Requireable<...>; }' is not assignable to type 'ValidationMap<NativeButtonProps>'.
          Property 'prefixCls' is missing in type '{ type: Requireable<string>; shape: Requireable<string>; size: Requireable<string>; htmlType: Requireable<string>; onClick: Requireable<(...args: any[]) => any>; loading: Requireable<boolean | object>; className: Requireable<...>; icon: Requireable<...>; block: Requireable<...>; }'.
```

**Comment by KagamiChan** [comment]
It seems to me usage with styled-components is just an example here, if someone uses componentType<ButtonProps> in matching typeof Button in their own code, the problem will also arise

**Comment by KagamiChan** [comment]
@zombieJ It does not seem the fix b076b52 solves all the problems

I suggest use explicitly `PropTypes.ValidationMap<Props>` for propTypes to reveal the hidden mismatch, like this in `button.tsx`:

```
  static propTypes: PropTypes.ValidationMap<ButtonProps> = {
    type: PropTypes.string,
    shape: PropTypes.oneOf(['circle', 'circle-outline']),
    size: PropTypes.oneOf(['large', 'default', 'small']),
    htmlType: PropTypes.oneOf(['submit', 'button', 'reset']),
    onClick: PropTypes.func,
    loading: PropTypes.oneOfType([PropTypes.bool, PropTypes.object]),
    className: PropTypes.string,
    icon: PropTypes.string,
    block: PropTypes.bool,
  };
```

**Comment by zombieJ** [comment]
hi  @KagamiChan ,
Do you have interesting to submit a PR for this? 😄

**Comment by KagamiChan** [comment]
@zombieJ I'm afraid the related work would be large since nearly every component's `propTypes` should be checked

Let's keep this issue open first

**Comment by iRoachie** [comment]
Is there any workaround for this? Encountering this atm

**Comment by meel-io** [comment]
Hi @zombieJ 
I'm interested in submitting a PR for this. 
Should I try to submit a PR for each component I checked? or one with all of them?

**Comment by zombieJ** [comment]
Hi @meel-io , you can send PR as your convenience. These 2 choice are both OK : )

**Comment by deftomat** [comment]
I'm also encountering this. Waiting for you @meel-io 😉

**Comment by hieuhlc** [comment]
Hi, I'm also encoutering this problem with `Button` component. Any progress so far? Should we re-open the issue?
