### ISSUE TITLE
mapPropsToFields 中绑定但是不在表单中显示的field，  使用 validateFields 得不到值

### ISSUE THREAD

**Issue by lawrsp** [ant-design/ant-design#11972]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n3yokp2zn4)

### Steps to reproduce
用 mapPropsToFields 绑定一些 field，但是不用 getFieldDecorator 在表单中绑定，这样validateFields 的时候，返回的值，并不包含未 使用 getFieldDecorator 的field
比如绑定三个 fields：
```
Form.create({
  mapPropsToFields(props) {
    return {
      test0: Form.createFormField({ value: props.test0 }),
      test1: Form.createFormField({ value: props.test1 }),
      test2: Form.createFormField({ value: props.test2 })
    };
  }
})
```
其中 test2 作为隐藏值，不在表单中体现，
那么当调用：
```
this.props.form.validateFields((err, values) => {
       console.log(values)
})
```
只能得到 test0 和 test1

### What is expected?
得到 test0， test1， test2

### What is actually happening?
test0， test1

**Comment by afc163** [comment]
这是对的，必须要用 getFieldDecorator 绑定。form 不处理没有实际表单元素的状态。

**Comment by lawrsp** [comment]
这样不太方便啊，能不能再提供一个得到所有值的接口呢？

**Comment by afc163** [comment]
和表单元素无关的状态用 props 传就可以了，不需要用到 mapPropsToFields，这个函数名已经很明确了。

**Comment by lawrsp** [comment]
我的理解是，这块是是处理数据，更大可能指的是数据意义上的fields

而且Form里没有 fields 这个元素，有的是 Form.Item, fields == Form.Item ，这个理解起来不是那么明显

参考redux-form，它里边有 Field 这个元素，提交的时候，可以给出所有的values，包括没被Field使用的
