### ISSUE TITLE
The save function in demo named 'Table with editable rows'  doesn't work

### ISSUE THREAD

**Issue by JChord** [ant-design/ant-design#11973]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
chrome: 68.0.3440.106 react:15.6.0

### Reproduction link
[https://codepen.io/DosLin/pen/KxNepm](https://codepen.io/DosLin/pen/KxNepm)

### Steps to reproduce
add style 'fixed: 'right' to the operation column, edit cell and save, the row from form is {} without any values.

### What is expected?
the validateFields method return all row values.

### What is actually happening?
the validateFields method return {}.

**Comment by yesmeck** [comment]
The demo is just an example. If you want more complicated usage, you need to explore it yourself.
