### ISSUE TITLE
Cascader的options参数中children数组中出现value相同的多个项时，多次选取后列表错乱

### ISSUE THREAD

**Issue by IDontKnowDontCallMe** [ant-design/ant-design#11978]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
react: 16.4.2;  antd: 3.8.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3yy2p8xj5m)

### Steps to reproduce
在上面codesandbox中，多次反复点击zhejiang和jiangsu

### What is expected?
多次反复点击zhejiang和jiangsu，其子列表不会发生变化

### What is actually happening?
多次反复点击zhejiang和jiangsu，其子列表会发生变化

**Comment by zombieJ** [comment]
value 不能相同，item 是跟着 value 来的。你可以做成同 label 不同 value 的形式。
