### ISSUE TITLE
DataPicker无法设置value属性，报错

### ISSUE THREAD

**Issue by ringrid** [ant-design/ant-design#1198]
## What you did

我按照官网的例子设置了`<DataPicker value={this.state.startValue} />`，当我在点击该选项时，页面出现错误。
错误描述如下：Uncaught Error: calendar must be type of GregorianCalendar

## Environment Information

- antd版本：0.12.10
- OS: fedora 23
- Browser: Chrome版本 49.0.2623.87 (64-bit)

**Comment by benjycui** [comment]
提供下 demo? http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by afc163** [comment]
是否应是 `DatePicker` ？

**Comment by ringrid** [comment]
上午这边网络断了……
请见：http://codepen.io/anon/pen/NNbpWz?editors=0011
我测试过ES5用React.createClass写法，是不存在问题的，但是我改用ES6写法，当我设置了DatePicker的value属性后，选择日期框打开后无法通过点击日期关闭，和我本地的问题一样。去掉value属性就正常。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/qZqrGP?editors=0011

建议按文档里的来：http://ant.design/components/date-picker/#picker-demo-start-end
