### ISSUE TITLE
select被initialValue选中填充为value值而非text值

### ISSUE THREAD

**Issue by joriewong** [ant-design/ant-design#11984]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.11

### Environment
win10 chrome

### Reproduction link
https://codesandbox.io/s/2p6own87wn

### Steps to reproduce
服务端传递的roletype值仅为0或1

``` jsx
<FormItem>
{
  getFieldDecorator('roletype', {
    initialValue: roletype,
  })(
  <Select>
     <Option value="1">普通用户</Option>  
     <Option value="0">管理员</Option>                  
  </Select>
)}
</FormItem>
```

### What is expected?
表单编辑时select被initialValue选择填充为text值

### What is actually happening?
表单编辑时select被initialValue选中填充为value值

**Comment by joriewong** [comment]
@afc163 https://codesandbox.io/s/2p6own87wn 🙏

**Comment by yoyo837** [comment]
`value={1}`?

**Comment by afc163** [comment]
```
0 === '0'   // false
```

**Comment by joriewong** [comment]
@yoyo837 @afc163 thx 🙏
