### ISSUE TITLE
Popover doesn't dismiss

### ISSUE THREAD

**Issue by iphonic** [ant-design/ant-design#11993]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0-beta.6

### Environment
MacOSx, Browser - Chrome(68.0.3440.106), Firefox(61.0.2), Safari(11.1.2 )

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/43qw7ox8rw)

### Steps to reproduce
1. Click on Open Popover
2. Click on Open Modal

### What is expected?
 Popover should dismiss on its own when it is out of focus and Modal is open

### What is actually happening?
There are multiple scenarios

In Example 1 - https://codesandbox.io/s/43qw7ox8rw
  - Popover doesn't dismiss if clicked outside, it happens when a boolean is used to show and hide Popover

In Example 2 - https://codesandbox.io/s/1vrn77morq
  - Popover does dismiss if clicked outside, but it appears over the Modal and doesn't dismiss.

**Comment by afc163** [comment]
https://codesandbox.io/s/o94vvy2119

Please learn React controlled component concept before using antd. https://reactjs.org/docs/forms.html#controlled-components
