### ISSUE TITLE
Button icon prop

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1199]
```jsx
<Button>
  <Icon type="star" />START
</Button>

==>

<Button icon="star">START</Button>
```

**Comment by plandem** [comment]
I would like to have same for TabPane.

**Comment by hotoo** [comment]
I think `Button > Icon[type]` is good enough.

```jsx
<Button>
  <Icon type="star" />                Star
</Button>

<Button>
  Next                <Icon type="right" />
</Button>
```

**Comment by plandem** [comment]
i you are going to add 'icon' prop to Button, then probably it will be also a good idea to add it to other components - e.g. tabs. But i'm fine with current way - less to learn, lower learning curve => more users.

**Comment by afc163** [comment]
Just for `Button` because I like it. :alien:

**Comment by afc163** [comment]
You guys can still use nested Icon.

**Comment by plandem** [comment]
please add to Tabs, because right now i have to use callback to render titles with icons.

**Comment by afc163** [comment]
`<TabPane tab=<span><Icon type="xx" />tab 2</span> key="2">second</TabPane>`

Why callback?

**Comment by plandem** [comment]
because it's ugly and much more worse as was with Button.
Button was:
```
<Button><Icon type="xx"/>title</Button>
```
Button now:
```
<Button icon="xx">title</Button>
```

Tab now:
```
<TabPane tab=<span><Icon type="xx" />title</span>>
  second
</TabPane>
```

Tab can be:
```
<TabPane tab="title" icon=""xx">
  second
</TabPane>
```

As i said - your addition about icon would be better for tabs, than for buttons.

**Comment by afc163** [comment]
Ok, I consider it.
