### ISSUE TITLE
Card 中headStyle中设置fontSize不生效

### ISSUE THREAD

**Issue by hellenhellen** [ant-design/ant-design#11995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0-beta.6

### Environment
windows、chrome

### Reproduction link
[https://github.com/hellenhellen/antd-Card-issues-demo.git](https://github.com/hellenhellen/antd-Card-issues-demo.git)

### Steps to reproduce
在APP.js中使用Card并设置headStyle

### What is expected?
Card标题字体大小改变

### What is actually happening?
Card标题字体大小未改变

**Comment by weinengjian** [comment]
请问，后来是怎么修复了？

**Comment by renzhenqi** [comment]
2022年了还是有这个问题
