### ISSUE TITLE
create-react-context has changed to a non-Open Source license in 0.2.3

### ISSUE THREAD

**Issue by ckknight** [ant-design/ant-design#11994]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0-beta.6

### Environment
Irrelevant

### Reproduction link
[https://github.com/jamiebuilds/create-react-context/commit/392ef2b40a4a6239ff63131c03797b7607708040](https://github.com/jamiebuilds/create-react-context/commit/392ef2b40a4a6239ff63131c03797b7607708040)

### Steps to reproduce
See the license of `create-react-context`

### What is expected?
That ant-design only relies on Open Source dependencies

### What is actually happening?
Because `create-react-context` is a dependency at ^0.2.2, it will automatically install 0.2.3, which is not Open Source.

---
An easy solution to this is to pin the `create-react-context` version to `0.2.2` rather than `^0.2.2`

**Comment by zombieJ** [comment]
Thanks for notice. Not sure the affects since it add some abandon org in license. TMP lock the version in `package.json`.

**Comment by ckknight** [comment]
This is an issue again, as of https://github.com/ant-design/ant-design/commit/338217410eaef6bff41b46316119f1df66e1c1cf @afc163

**Comment by ckknight** [comment]
Note: if React 16.3 or greater were guaranteed, an easy solution would be to just use `React.createContext`
