### ISSUE TITLE
Popover incorrectly position its arrow in some cases

### ISSUE THREAD

**Issue by otakustay** [ant-design/ant-design#11997]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
Chrome 68, macOS 10.13.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/644xmp3jvr)

### Steps to reproduce
1. Open reproduction link
2. Click the button

### What is expected?
The arrow should be placed to the right of popover

### What is actually happening?
The arrow is now placed on the left side

---
This issue comes when `placement="right"` and there is no enough place on both the right and bottom side, by changing the `contentStyle.height` to a smaller value such as `200` this issue could be fixed because there is enough place on the bottom side

**Comment by afc163** [comment]
You should not using `placement="right"` if there is possibility that no enough space for popover which will auto switch it's position to fit, try `placement="leftBottom"` instead.

**Comment by otakustay** [comment]
There is not always a strategy to assign the right `placement` value, a real world case is a sidebar and columns of labels:

![image](https://user-images.githubusercontent.com/639549/44954450-fe723f00-aed4-11e8-844e-75fa99471059.png)

It is complex to known the column and row of a label, what we can say generally is "don't open popover on the left to cover the sidebar", this is not a rare case

I think popover should fallback to "auto" mode when `placement="right"` but there is insufficient room on the right

**Comment by afc163** [comment]
You can try using undocumented prop `align` to disable auto overflow switching function, though there will be other issue: https://codesandbox.io/s/j2jqv142r3
