### ISSUE TITLE
onFieldsChange is undefined and not being invoked

### ISSUE THREAD

**Issue by nishant-dani** [ant-design/ant-design#11998]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
react, chrome browser

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l50k35qwm7)

### Steps to reproduce
I am having a strange issue with antd when I use Form.Create( onFieldsChange, mapPropsToFields. The onFieldsChange never gets called. So I debugged to resolve it and ended up with a lot of questions about the javascript lexical scope and the this pointer. The layout of the code in antd is similar to the follows:

init()
  var onFieldsChange = options.onFieldsChange;

  return decorator(function {
      function1() {
        // onFieldsChange is valid and points to the function object
      },
      function2() {
         // onFieldsChange is valid and points to the same function
      },
      function3() {
         // onFieldsChange is invalid
      }
  });
}
The order in which the functions are called at runtime is

function1()
function3()
function2()
function1 and function2 are called with this pointer pointing to the wrapped form, while function3 is called with the this pointer pointing to the form. So there are differences in the this pointer. But my understanding of javascript and its lexical scope is that access to onFieldsChange is available to all the functions because they inherit the lexical scope and the lexical scope is independent of the execution scope which is the runtime stack and what this pointer is on the runtime stack.

Now because of onFieldsChange being invalid, it won't invoke the callback, and it leads to a cascading break in functionality.

Now as this is part of the antd documentation, I assume that it works for them, but it is somehow not working for me.

Any insights would be great. I am able to put console. logs to debug this freely, so I can examine the flow in as much detail as I need. Apparently, there is no way in javascript to examine at a point in the function what all variables are present in the current lexical scope. If there were I would have more helpful material.

Any tips on why this lexical scope is messed up?

### What is expected?
onFieldsChange will be called.  I am expect to see the console.log
EventFormProposer: onFieldsChange

### What is actually happening?
onFieldsChange inside setFields is invalid and it never gets called. The only console.log that is called is.
EventFormProposer: mapPropsToFields

---
I have debugged this through the chrome browser and it appears that the function setFields which is supposed to call onFieldsChange is unable to do so because onFieldsChange, mapPropsToFields are both undefined.

      setFields: function setFields(maybeNestedFields) {
        var _this4 = this;

        console.log(`setFields: onFieldsChange is ${onFieldsChange}:${this.onFieldsChange}, mapPropsToFields is ${mapPropsToFields} this is ${stringify(this)}`)

        var fields = this.fieldsStore.flattenRegisteredFields(maybeNestedFields);
        this.fieldsStore.setFields(fields);
        if (onFieldsChange) {
          var changedFields = Object.keys(fields).reduce(function (acc, name) {
            return __WEBPACK_IMPORTED_MODULE_10_lodash_set___default()(acc, name, _this4.fieldsStore.getField(name));
          }, {});
          onFieldsChange(this.props, changedFields, this.fieldsStore.getNestedAllFields());
        }
        this.forceUpdate();
      },

**Comment by zombieJ** [comment]
You use `Form.create` in `FormContainer.js` and pass the `form` prop to child component `FormProposer`:
```jsx
<FormProposer
  form={this.props.form}
  ...
/>
```

which replace the `form` prop of `FormProposer` makes your config option of `Form.create()` under `FormProposer` not work.

**Comment by nishant-dani** [comment]
Thanks @zombieJ , that fixed it.  I removed the Form.create from the outer container.
