### ISSUE TITLE
Tooltip not being triggered by Icon

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#12005]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
React 16.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ov752w1nw5)

### Steps to reproduce
```
<Tooltip title="Tooltip">
    <Icon type="close" />
</Tooltip>
```

### What is expected?
The `Tooltip` should be triggered.

### What is actually happening?
The `Tooltip` does not appear unless you wrap `Icon` in span or something

**Comment by josh231101** [comment]
Add &nbsp; to the end of the icon this adds a blank space but tooltip sort of detects that there is a text to hold on This will work ;)

**Comment by xinghul** [comment]
@josh231101 that's not a good fix though, do we know what's the underlying issue?
