### ISSUE TITLE
add method to get fieldsMeta on form instance

### ISSUE THREAD

**Issue by daskyrk** [ant-design/ant-design#12017]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when using data to restore form fields value, part of keys in data may not registered in form fields, if not remove these useless keys, antd will throw a  error: 'You cannot set field before registering it.'
we dont't want to watch the change of fields to update the keys of data every time, and now i use this way to remove useless keys:
```javascript
const { formRef, form, data } from this.props;
form.setFieldsValue(_.pick(data, Object.keys(formRef.fieldsStore.fieldsMeta))); // formRef is the instance of Form
```
but in this way we need to get the ref from From.create()(InnerComponent), and some time we need to get the fieldsMeta in InnerComponent before setFieldsValue.

### What does the proposed API look like?
**form.getFieldsMeta()**

```javascript
const { form, data } from this.props;
form.setFieldsValue(_.pick(data, form.getFieldsMeta())); // form is a prop from From
```

**Comment by yesmeck** [comment]
> when using data to restore form fields value, part of keys in data may not registered in form fields, if not remove these useless keys, antd will throw a error: 'You cannot set field before registering it.'

Could you demostrate your issue on https://codesandebox.io?

**Comment by daskyrk** [comment]
https://codesandbox.io/s/yw5xy85j2v @yesmeck

**Comment by yesmeck** [comment]
> codesandbox.io/s/yw5xy85j2v

Not working

**Comment by daskyrk** [comment]
some error info is logged in console @yesmeck

**Comment by yesmeck** [comment]
As warning said, `You cannot set field before registering it`, you wrote the code, you know which fields are registered, don't rely on undocumented API `fieldsStore`.

**Comment by daskyrk** [comment]
but i dont't want to pick the fields every time the form fields change or the data keys change. i know  fieldsStore is a undocumented API, that's why i want an official API to get fields meta info. @yesmeck

**Comment by yesmeck** [comment]
> you wrote the code, you know which fields are registered
