### ISSUE TITLE
Table: The border of grouping column disappears when size is small

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#12015]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
MacOS: 10.136        Chrome: 68.0.3440.106        react: 16.4.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vnvkyx7mw3)

### Steps to reproduce
Click the re-producible link and view the result.

### What is expected?
The border should display normally as same as that size is large and middle.

![image](https://user-images.githubusercontent.com/14918822/44968541-19978a00-af7b-11e8-9b28-d2c218fdcc94.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/14918822/44968379-2b2c6200-af7a-11e8-80b0-0f9bcc4b350d.png)

**Comment by AsatryanKaren** [comment]
Hey guys can you help me? The same issue is now happening on my app
