### ISSUE TITLE
Menu horizontal模式下自动收起功能对靠右的菜单不太友好

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#12025]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有一些顶部菜单是靠右的, 在新版本下右边会有一块空白(显示...图标的区域), 现在我是通过自己写的样式隐藏的

### What does the proposed API look like?
希望有属性可以隐藏这个
或者新增 horizontal-right 模式适应靠右的菜单

**Comment by picodoth** [comment]
menu@7.4.4 修复了右边空白的问题。重装 antd 应该就好了。

至于要不要把这个变成 optional 的行为，现在还没想清楚。如果修复了右边空白的问题，理论上默认开启应该没问题。
