### ISSUE TITLE
Table控件在传入的dataSource数据中有字段数据为{}时出错。

### ISSUE THREAD

**Issue by zelonggit** [ant-design/ant-design#1202]
例如：
dataSource={
a:1,
b:{},
c:'test'
}
会因为{}出错。
错误为：
request failed Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `TableRow`.(…)

**Comment by afc163** [comment]
dataSource 应为数组。

**Comment by zelonggit** [comment]
就是数组里面包含了几个Object，楼上的举例为Object里面的数据

**Comment by afc163** [comment]
经测试，确实如此，当对应 column 未指定 render 时出现。

想问一下，如果数据为 Object 对象 `{}`，建议渲染的结果是？

**Comment by zelonggit** [comment]
我认为就把{}当做一个空好了。里面也不会存什么数据。

**Comment by afc163** [comment]
Reinstall

**Comment by jacoobwang** [comment]
也碰到了，解决了吗

**Comment by SoftwareEngineerPalace** [comment]
我也碰到了，没解决
