### ISSUE TITLE
新版 Icon 造成一些组件出现 Icon 丢失和垂直对齐偏移

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#12026]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
WIN10 - Chome68 - React 16

### Reproduction link
[https://ant.design/components/popconfirm-cn/](https://ant.design/components/popconfirm-cn/)

### Steps to reproduce
使用新版 Icon

### What is expected?
正确显示

### What is actually happening?
显示错误

Popconfirm
![_20180903155559](https://user-images.githubusercontent.com/1730277/44974531-8f5b2000-af92-11e8-9130-4c6620b88c6e.png)

Table
![_20180903155715](https://user-images.githubusercontent.com/1730277/44974558-a13cc300-af92-11e8-930e-8dd558f670b9.png)

Modal.error
![_20180903155802](https://user-images.githubusercontent.com/1730277/44974568-a863d100-af92-11e8-957a-d2c40c8d74a2.png)

**Comment by songchengen** [comment]
也出现这个问题了！！！我也是醉了，检查好久才找到原因，以后心在以来包一定要固定版本号

**Comment by afc163** [comment]
抱歉，今天内会发版本修复。

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12016

**Comment by zlab** [comment]
新版的`close`图标不是正方形,是个长方形

**Comment by zlab** [comment]
所有图标整体比以前偏小, 看起来比以前模糊了
