### ISSUE TITLE
Carousel 需要实现左右按钮上下翻页 next方法怎么使用

### ISSUE THREAD

**Issue by tcly861204** [ant-design/ant-design#12024]
```
          <span className="swiper-wrapper-pre"></span>//上一页按钮
          <span className="swiper-wrapper-next"></span>  //下一页按钮
          <Carousel className="swiper-wrapper-slider" autoplay>  
            {banner.map((v, index)=>{
              return (
                <div className="swiper-item" key={index} onClick={()=>{
                  this.props.clickBanner(v.id)
                }}>
                  <img src={v.banner_img} alt="banner"/>
                </div>
              )
            })}
          </Carousel>
```
怎么实现左右按钮切换页面？

**Comment by wongzzh** [comment]
可以利用ref实现即可，举例如下
const carousel = useRef(null)
const next = ()=>{carousel.current.next()}
`return (
<>
<span className="swiper-wrapper-next" onClick={next}></span>
<Carousel ref={carousel}>
    <div>
      <h3>1</h3>
    </div>
    <div>
      <h3>2</h3>
    </div>
</Carousel>
</>
)`

**Comment by WLyKan** [comment]
> 可以利用ref实现即可，举例如下
> const carousel = useRef(null)
> const next = ()=>{carousel.current.next()}
> `return ( <> <span className="swiper-wrapper-next" onClick={next}></span> <Carousel ref={carousel}> <div> <h3>1</h3> </div> <div> <h3>2</h3> </div> </Carousel> </> )`

我看到ref打印出来，在current的`__proto`上是又prev和next的，但是还是报错`Cannot read property 'prev' of null`
