### ISSUE TITLE
表单数据存储于上层组件 - Ant Design Demo表单事件被触发2次

### ISSUE THREAD

**Issue by nsuedu** [ant-design/ant-design#12028]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
win10 ，最新版谷歌浏览器

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
修改表单内容，打开F12进行断点调试

### What is expected?
表单事件只会被触发一次

### What is actually happening?
表单事件被触发次两次

---
  onFieldsChange(props, changedFields) {
    props.onChange(changedFields);
  },

**Comment by nsuedu** [comment]
online reproduction:  https://codesandbox.io/s/k3oqy4zx7r @ant-design-bot @yesmeck

**Comment by yesmeck** [comment]
参考 https://github.com/ant-design/ant-design/issues/2934
