### ISSUE TITLE
Menu组件的兼容性问题

### ISSUE THREAD

**Issue by wangzhics** [ant-design/ant-design#12033]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
无

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new](https://github.com/ant-design/ant-design/issues/new)

### Steps to reproduce
  以下代码会在3.9.0报错，但是旧版本(3.8.4)不会        
<Menu mode="horizontal">{[]}</Menu>

### What is expected?
无

### What is actually happening?
无

---
提个issue真是难

**Comment by afc163** [comment]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/507615/44981030-077e1180-afa4-11e8-9b79-8a5f4624648f.png">

**Comment by wangzhics** [comment]
代码如下
<Menu
  mode="horizontal"
>
  {[]}
</Menu>

**Comment by wangzhics** [comment]
`
<Menu
  mode="horizontal"
>
  {[]}
</Menu>
`

**Comment by wangzhics** [comment]
提交不了示例代码。。。
![image](https://user-images.githubusercontent.com/6712999/44982482-a442ae00-afa8-11e8-83cf-50c050709b75.png)

**Comment by wangzhics** [comment]
The above error occurred in the <DOMWrap> component:
    in DOMWrap (created by SubPopupMenu)
    in SubPopupMenu (created by Connect(SubPopupMenu))
    in Connect(SubPopupMenu) (created by Menu)
    in Provider (created by Menu)
    in Menu (created by Menu)

Uncaught TypeError: Cannot read property 'style' of undefined
    at DOMWrap._this.setChildrenWidthAndResize (DOMWrap.js:107)
    at DOMWrap.componentDidMount (DOMWrap.js:162)

**Comment by wangzhics** [comment]
3.9.0: https://codesandbox.io/s/ly9qn5wonq
3.8.4: https://codesandbox.io/s/0348q7979l

**Comment by picodoth** [comment]
Fixed in Menu@7.4.4

**Comment by ty-bt** [comment]
@picodoth 更新后children为null或undefined还是会报错
还有一个类似的问题 https://codesandbox.io/s/pxyq76vzj
展开没有children的Menu.SubMenu也会报错
我这边的业务是: 点击展开的时候会去后台加载子菜单, 在还没加载完成的时候这个子菜单就是空的..
大佬 辛苦了.

**Comment by picodoth** [comment]
@ty-bt 感谢反馈！ fixed in https://github.com/react-component/menu/commit/a26b7d52799c0ec9c45bbbcf03fb703c6ce0fd06 and available in menu@7.4.5

请重装依赖再试一下！

**Comment by ty-bt** [comment]
@picodoth 已解决.
