### ISSUE TITLE
Wrong UP icon in InputNumber component after new release

### ISSUE THREAD

**Issue by amirhossein693** [ant-design/ant-design#12035]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
Ubuntu 18.04, Chrome 68

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lpy2o7vrj9)

**Comment by HeskeyBaozi** [comment]
Thanks, it will be fixed in 3.9.1
https://github.com/ant-design/ant-design/pull/12014

**Comment by NoanHu** [comment]
Why is this problem still there in 3.9.1? Up and down arrow icons are not displayed

**Comment by HeskeyBaozi** [comment]
@NoanHu create another issue and give a reproduction link, plz :)
