### ISSUE TITLE
Can Antd less module be import easier and clear without the global reset stylesheet effect? 

### ISSUE THREAD

**Issue by LaiHuanMin** [ant-design/ant-design#12037]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Recently, I'm using the antd(v3.8.4) tree component for a JS plugin, the compile tools is parcel.    
When I compiled(one css file, and one js file), after insert the resource into an old project which using old tools such as jquery, bootstrap, the total page UI is mixed and conflict.   
After checking the less file, I found the conflict question is causing by antd lib less file(node_modules/antd/lib/style/core/base.less). After I removed the default global less import, and import less file which the minimal need and without base.less, the conflict UI question has be fixed, but I found seems like tree component horizontal direction is always scrolling.   
After rechecking the base.less,  I found because losing the base.less which define pseudo class ::after and ::before attribute box-sizing like 'border-box'.      
Now question is fixing, but I wonder is there better way to exact a antd component into a separate component without global element css effect(such as input, ul, ol), and without any change and checking, what I just need to do is import this component and can easier insert it into another project which using different UI style.    

### What does the proposed API look like?
Easier Import Less, make CSS Module, Antd Style can be easier import.  Sorry, seems like this feature cannot support a code snippet

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4331
https://github.com/ant-design/ant-design/issues/9363
https://github.com/ant-design/ant-design/pull/11929

**Comment by LaiHuanMin** [comment]
@afc163 Thanks
