### ISSUE TITLE
Can't do npm i antd with custom registry

### ISSUE THREAD

**Issue by prilutskiy** [ant-design/ant-design#12039]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
macOS High Sierra, node v9.11.1, npm 6.4.1, JFrog Artifactory

### Steps to reproduce
```
$ npm i antd

npm ERR! code E404
npm ERR! 404 Not Found: @ant-design/icons-react@~1.0.0

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prilutskiy/.npm/_logs/2018-09-03T13_17_50_890Z-debug.log

```

### What is expected?
I expect package to be resolved automatically

### What is actually happening?
@ant-design/icons-react doesn't get resolved

---
Maybe package got published incorrectly.

**Comment by afc163** [comment]
It is not antd issue, it works on npm right well.

**Comment by SpartaSixZero** [comment]
Same issue for us. I made the following change in our package.json and that seemed to have fixed the error:
Replaced
"antd": "^3.7.2",

With
"antd": "3.8.4",

I looked into our node_modules folder and the current version that we had of antd was 3.7.3

**Comment by camille666** [comment]
i met the problem

**Comment by garkey** [comment]
I have the same issue with "latest":"3.16.2" on Linux Mint 19, npm 6.4.1. My work colleagues are able to install that version on their OSXes. I'd would be great to be able to use the latest version, instead of reverting to old version b/c of install issues.

**Comment by gadflying** [comment]
open with npm config edit and remove  JFrog Artifactory _auth and email fix the issue

**Comment by aamaclaren** [comment]
Jumping in to note that as of Nov 7, 2019 this issue still produces with v3.25.0.  I'm using on macOS Mojave. I can also say that v3.8.4 installs as expected
