### ISSUE TITLE
Popover弹出框问题

### ISSUE THREAD

**Issue by Always-OL** [ant-design/ant-design#12034]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
"antd": "^3.6.6",

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mzzx2q7qn9)

### Steps to reproduce
1、正常引入Popover组件
2、点击按钮时弹出Popover
3、每次点击按钮，Popover都是先错位显示（即弹出位置不正确），然后再跳回正确位置

### What is expected?
每次点击按钮，Popover直接在正确位置

### What is actually happening?
每次点击按钮，Popover都是先错位显示（即弹出位置不正确），然后再跳回正确位置

**Comment by zombieJ** [comment]
你的重现不全，预览是空的。

**Comment by syaivin** [comment]
![qq 20180906083310](https://user-images.githubusercontent.com/13479047/45128441-a11a0e80-b1b0-11e8-98f9-1b723c36c717.png)
![qq 20180906083348](https://user-images.githubusercontent.com/13479047/45128447-a8d9b300-b1b0-11e8-94a8-ce8fdb7ec819.png)
也出现这情况了，还没找到处理办法~

**Comment by xaasu** [comment]
使用roadhog1会有这种问题
roadhog2没有

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/47849868-21a26780-de0e-11e8-8c08-d3d7cdad89e1.png)


我的场景是如图，（红色）位置是初始状态会，它可以自己闪到正确位置，或点击下页面，或者resize一下，猜测是触发重新计算位置的因子相关。另外逻辑可能和`autoAdjustOverflow `有关，各位可以尝试`false`看能不能解决，有时间可以PR一下。

**Comment by DearGaz** [comment]
@xaasu 赞，我也碰到一样的问题，升级到roadhog 2.0之后确实没有这个问题了。我的antd版本是3.10.1

**Comment by tvrcgo** [comment]
遇到同样的问题，装的 antd@3.18.1，设置 autoAdjustOverflow = false 也没用。

不是特殊的渲染场景，就在页面上放一个 Popover，由 Button 触发。

```js
render () {
  return (
    <div>
      <Popover 
        placement="bottom" 
        title={'title'} 
        content={<div>contnet</div>} 
        trigger="click" 
      >
        <Button>Bottom</Button>
      </Popover>
    </div>
  )
}
```

**Comment by Arthurcherryli** [comment]
> 遇到同样的问题，装的 antd@3.18.1，设置 autoAdjustOverflow = false 也没用。
> 
> 不是特殊的渲染场景，就在页面上放一个 Popover，由 Button 触发。
> 
> ```js
> render () {
>   return (
>     <div>
>       <Popover 
>         placement="bottom" 
>         title={'title'} 
>         content={<div>contnet</div>} 
>         trigger="click" 
>       >
>         <Button>Bottom</Button>
>       </Popover>
>     </div>
>   )
> }
> ```
> 
> ![mut86-2kzob](https://user-images.githubusercontent.com/237062/57619764-5b240e80-75b9-11e9-9cc0-0733f0fb93d4.gif)
我也遇到这种问题了，想请问一下是怎么解决的呢？

**Comment by tvrcgo** [comment]
> > 遇到同样的问题，装的 antd@3.18.1，设置 autoAdjustOverflow = false 也没用。
> > 不是特殊的渲染场景，就在页面上放一个 Popover，由 Button 触发。
> > ```js
> > render () {
> >   return (
> >     <div>
> >       <Popover 
> >         placement="bottom" 
> >         title={'title'} 
> >         content={<div>contnet</div>} 
> >         trigger="click" 
> >       >
> >         <Button>Bottom</Button>
> >       </Popover>
> >     </div>
> >   )
> > }
> > ```
> > 
> > 
> > ![mut86-2kzob](https://user-images.githubusercontent.com/237062/57619764-5b240e80-75b9-11e9-9cc0-0733f0fb93d4.gif)
> > 我也遇到这种问题了，想请问一下是怎么解决的呢？

问题还存在

**Comment by wengcd** [comment]
仍有这个问题

**Comment by yoyo837** [comment]
我也一直有，个人准备去看一下的，一直没去看。

**Comment by yoyo837** [comment]
![Nov-15-2019 10-19-04](https://user-images.githubusercontent.com/6134547/68911925-8e766e80-0791-11ea-95c4-23c76d59a347.gif)

**Comment by yoyo837** [comment]
@tvrcgo 请教下你用的gif录制软件？

**Comment by wengcd** [comment]
@yoyo837 我刚刚解决了这个问题，原因是 Popover 内的图片高度设成了自动，保证Popover内容高宽固定就不会有问题

**Comment by yoyo837** [comment]
Popover 初始化时内容高度未知是吧？那应该是因为图片异步加载。

**Comment by yoyo837** [comment]
预先设置好内容的宽高就行，好像也没更好的办法，总不能让Popover 不间断获取宽高然后调整位置吧！

**Comment by ensignwy** [comment]
> @yoyo837 我刚刚解决了这个问题，原因是 Popover 内的图片高度设成了自动，保证Popover内容高宽固定就不会有问题

不是这个问题，你没看到楼上那个例子吗，那个popover里面直接写的是静态内容，还是不行

**Comment by CrazySean007** [comment]
+1，我在设置了popover的位置从 position: fixed 让它贴在左边，但是总是先从对应位置出来然后闪一下到左边。请问各位有解决的方案么? @yoyo837 @tvrcgo @wengcd @afc163

**Comment by pengpeng9413** [comment]
@afc163  人呢，这么多人有问题，到时回应一下啊，直接就关了，无语

**Comment by XavierShi** [comment]
+1， 同样问题

**Comment by A-GG** [comment]
所以这个问题还是没解决么？

**Comment by one-thing-one-world** [comment]
我也遇到了这个问题，，

**Comment by xukeke520** [comment]
+1

**Comment by Mone-Lee** [comment]
在Popover上加 `transitionName="" `试试？

我的情况是popover里的content可能是视频或图片，在content加载完后会闪动一下，加了`transitionName="" `后就没有闪动了。

**Comment by minzhang2** [comment]
onVisibleChange={(visible) => {
    if (visible) {
      setTimeout(() => {
        setVisible(true)
      }, 100)
    } else {
      setVisible(visible)
    }
  }}
