### ISSUE TITLE
是否继续支持3.9.0一下的icon的Tooltip展示

### ISSUE THREAD

**Issue by gclb** [ant-design/ant-design#12036]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在任意表单或者功能时，通常会在输入框后面或者某个头上添加一个图标，在通过Tooltip进行hoving进行展示

### What does the proposed API look like?
<Tooltip placement="right" title="版权登记系统">
    <Icon type="desktop"/>
</Tooltip>

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/issues/12005
https://github.com/ant-design/ant-design/issues/12032
https://github.com/ant-design/ant-design/commit/c4b6dafb64c9284a52face3f3aa5f04f3ba5420f
