### ISSUE TITLE
Collapse.Panel 如果header里放的Icon会根据收缩旋转

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#12041]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
chrome

### Reproduction link
[https://ant.design/components/collapse-cn/](https://ant.design/components/collapse-cn/)

### Steps to reproduce
Collapse.Panel 如果header里放的Icon会根据收缩旋转

### What is expected?
不旋转

### What is actually happening?
旋转

**Comment by zombieJ** [comment]
![kapture 2018-09-04 at 11 02 07](https://user-images.githubusercontent.com/5378891/45007796-0a274800-b032-11e8-916d-1e88df4b4b97.gif)

给个例子

**Comment by HeskeyBaozi** [comment]
重现不正确。`3.9.1` 应该已经修复
[![Edit 0xlwkj516n](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0xlwkj516n)

**Comment by Fled8617** [comment]
抱歉，之前版本是3.9.0
