### ISSUE TITLE
Button support custom icon

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#12047]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Button can set custom icon

### What does the proposed API look like?
```jsx
<Button type="primary" icon={<MyIcon type="game" />} />
```

**Comment by zombieJ** [comment]
直接写里面就行了，`icon` 是方便用户少一个 import： https://codesandbox.io/s/2vw20ryynn

**Comment by nuintun** [comment]
@zombieJ 考虑过写里面，不过设置 loading 的时候还要做些逻辑处理

https://codesandbox.io/s/m37nk663qj

**Comment by zombieJ** [comment]
嗯，需要稍微封装一下...

**Comment by nuintun** [comment]
@zombieJ 尬了，写里面 loading 的时候会造成视觉抖动，体验很差！

https://codesandbox.io/s/m37nk663qj

**Comment by zombieJ** [comment]
https://codesandbox.io/s/p38krpjv50

**Comment by afc163** [comment]
https://codesandbox.io/s/236rjw2j7p

这样就行了。

**Comment by nuintun** [comment]
@zombieJ @afc163 其实是想要实现自定义 Icon
所以 @zombieJ 的更符合，但是还是抖动~

https://codesandbox.io/s/v0jq048yol
