### ISSUE TITLE
modal里的table由于样式whitespace nowrap导致表格不能换行，有scroll时不能对其

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#12050]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://3qwyjyyw2q.codesandbox.io/)

### Steps to reproduce
https://3qwyjyyw2q.codesandbox.io/

### What is expected?
可以正常使用scroll

### What is actually happening?
有scroll内容过长不对其

**Comment by ycjcl868** [comment]
```diff
- <Modal centered bodyStyle={{ width: 800, height: 500 }} visible={true}>
+ <Modal centered style={{ width: 800, height: 500 }} visible={true}>
```

然后调下换行样式，
