### ISSUE TITLE
"transform" function in validation rules in Forms does not work. 

### ISSUE THREAD

**Issue by ucanlendit** [ant-design/ant-design#12056]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
browser

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ox7n107rqz)

### Steps to reproduce
1) go to codesandbox, 2) type in "CAPITALs ", 3) click login and see in the console that the value that has been submitted in NOT transformed, even though the function is called. 

### What is expected?
It's expected that the "transform" would apply to the submitted values, maybe the current behaviour is intended, but it is not expected from the end user perspective. 

### What is actually happening?
The values are NOT transformed by the "transform" function on the validator options. 

---
version 3.9.1

**Comment by zombieJ** [comment]
`transform` function under `rule` is used for transform value to the rule validator. Not for field value.
https://codesandbox.io/s/j445jwpmy9
