### ISSUE TITLE
The new version of the icon filled mode is ugly

### ISSUE THREAD

**Issue by Hughen** [ant-design/ant-design#12053]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Before 3.9, the size of the actual content area of the icon is larger than the current icon. The advantage of this is that under the small size icon application scene, such as 15x15, you can see at a glance what the icon wants to express, but from This was not the case at the beginning of 3.9, and it did not take into account the small size.
I said that I am very sad.

v3.9.1: https://codesandbox.io/s/8pl7vj0np2
v3.8.4: https://codesandbox.io/s/zqzo1prom3

### What does the proposed API look like?
Icon actual content area size is larger

**Comment by yesmeck** [comment]
@JuelChiang

**Comment by Hughen** [comment]
Has anyone followed up on this issue?
I think the 3.9 version of the icon changes, it is very unacceptable

**Comment by afc163** [comment]
We should enlarge 3.9 icons as 3.8's for compatibility.

**Comment by Hughen** [comment]
@afc163 
Do you mean to increase the icon and be forward compatible?

**Comment by HeskeyBaozi** [comment]
We can use the `viewBox` to solve this problem.
modify the `viewBox` from `0 0 1024 1024` to `64 64 896 896`.
`896 = (1024 * 875) / 1000`, where the `875/1000` is the current size ratio `path box / svg box`.
`64 = (1024 - 896) / 2`.

the result preview:
![image](https://user-images.githubusercontent.com/15819224/45137404-139fe400-b1db-11e8-9cc5-addaea6214f4.png)

**Comment by Hughen** [comment]
Modifying the viewBox will make the code very bloated, because in order to pass the viewBox property, either use a custom component or children, but no matter which method I choose, I need to import @ant-design/icons, which is not Is it equivalent to rebuilding a Icon component?

**Comment by HeskeyBaozi** [comment]
@Hughen This change only impact the offical icons in `@ant-design/icons`

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12114
