### ISSUE TITLE
文件上传配合表单验证行为异常

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#12052]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
chrome 68, mac 10.14

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n9wy36lymm)

### Steps to reproduce
文件上传表单验证：
1.如果没有上传过，则验证不通过，ok.
2.上传文件，上传失败，验证通过；
3.删除失败的文件，验证通过；

### What is expected?
上传失败和移除上传文件后应该识别为验证不通过

### What is actually happening?
上传失败和移除上传文件后识别为验证通过。结论上只要上传过验证就通过；

**Comment by zombieJ** [comment]
https://codesandbox.io/s/v697w4wr3l

**Comment by yoyo837** [comment]
Thanks for your reply.
