### ISSUE TITLE
Select多选样式

### ISSUE THREAD

**Issue by ZH4L** [ant-design/ant-design#12054]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
win10 Chrome67

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
更新到3.9.1后，多选下拉框样式有变化

### What is expected?
更新到3.9.1后，多选下拉框样式有变化，已选中的去掉了之前版本右侧的钩，单纯的靠加粗字体和加了个很浅的背景色区分，导致很不明显

### What is actually happening?
希望把已选中的钩改回去

**Comment by afc163** [comment]
Will be fixed in this weekend.

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12114

**Comment by kennylbj** [comment]
![image](https://user-images.githubusercontent.com/6435874/45260931-aaacac00-b426-11e8-89bd-a05172649b0e.png)
多选后面莫名其妙多了da √号 
The same issue?
