### ISSUE TITLE
Table的sorter指示器默认不呈现

### ISSUE THREAD

**Issue by liekkas** [ant-design/ant-design#1205]
Table的sorter指示器(上下三角形)默认不呈现，我看官网例子是呈现的。
但是我用同样的代码，鼠标要滑过去才出来上下三角形，会是什么原因呢？多谢

**Comment by afc163** [comment]
给个 codepen 例子看看？

**Comment by liekkas** [comment]
我的原因，我把表头的背景色设置的跟指示器一样了，难怪看不出来。还是感谢！
