### ISSUE TITLE
Can add option for removing EXIF orientation information when upload image

### ISSUE THREAD

**Issue by wangxia337** [ant-design/ant-design#12069]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
can ignore EXIF orientation  tag when upload image

### What does the proposed API look like?
ReactDOM.render(
  <Upload cleanOrientation={true}>
    <Button>
      <Icon type="upload" /> Click to Upload
    </Button>
  </Upload>
, mountNode);

**Comment by wangxia337** [comment]
Has a duplicate https://github.com/ant-design/ant-design/issues/7271, but it is closed.

**Comment by zombieJ** [comment]
Since this is rare requirement, we may not have plan on this. But PR is welcome.
For current antd, you can use `customRequest` to handle this: https://ant.design/components/upload-cn/#customRequest
