### ISSUE TITLE
使用TreeSelect for Ant Design V3.9.1，如何在两个子节点一样，隶属于不同组的情况下如何操作代码

### ISSUE THREAD

**Issue by 5679361** [ant-design/ant-design#12064]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用TreeSelect for Ant Design V3.9.1版本，我的数据格式是这样的{id: 1, pId: 0, value: 'a', title: '标签1'},
{id: 2, pId: 1, value: 'aa', title: '标签2'},
        {id: 3, pId: 1, value: 'ab', title: '标签3'},
        {id: 4, pId: 0, value: 'b', title: '标签4'},
        {id: 5, pId: 4, value: 'ba', title: '标签5'},
        {id: 6, pId: 4, value: 'bb', title: '标签6'},
        {id: 2, pId: 4, value: 'aa', title: '标签2'}  是这样的，如果id:2表示一个人，他分别隶属于两个不同的部门，那么我要如何处理代码呢？目前我选择了一个内容，会有2个子节点都高亮的情况，请帮帮忙，谢谢。

### What does the proposed API look like?
{id: 1, pId: 0, value: 'a', title: '标签1'},
{id: 2, pId: 1, value: 'aa', title: '标签2'},
        {id: 3, pId: 1, value: 'ab', title: '标签3'},
        {id: 4, pId: 0, value: 'b', title: '标签4'},
        {id: 5, pId: 4, value: 'ba', title: '标签5'},
        {id: 6, pId: 4, value: 'bb', title: '标签6'},
        {id: 2, pId: 4, value: 'aa', title: '标签2'}

**Comment by zombieJ** [comment]
title 相同 id & value 不同即可。

PS：issue 板块是处理 bug，使用问题一般不回答的。
