### ISSUE TITLE
table组件的pageSize变化时不能保留filters和sort信息

### ISSUE THREAD

**Issue by wormcc** [ant-design/ant-design#1206]
pageSize变化时会触发onShowSizeChange方法，但是在方法内并不能携带filters和sort的信息，能否让onShowSizeChange携带filters和sort的参数？

**Comment by benjycui** [comment]
这样不符合语义吧，Owner 收集 filter 和 sort 的参数，`onShowSizeChange` 可以用闭包访问。

**Comment by wormcc** [comment]
@benjycui 那是否可以考虑在pageSize变化的时候，也同样触发table的`onChange`方法呢？因为page变化的时候的确是触发了，这个在语义上应该没有什么问题吧？

**Comment by afc163** [comment]
确实应该。
