### ISSUE TITLE
how to align with the parent columns, while the subtable  is "showHeader={false} and the header isn't fixed"

### ISSUE THREAD

**Issue by LiangLuDeng** [ant-design/ant-design#12074]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
antd: 3.9.1

### Environment
react: latest

### Reproduction link
https://codesandbox.io/s/mqkkyl8orx
### Steps to reproduce
subTable's columns
```
 return <
  Table columns={columns} 
  dataSource={data} 
  pagination={false} 
  showHeader={false} 
/>;
```

### What is expected?
showHeader={false}
can align with the parent columns

#### show Header:(subtable)
![image](https://user-images.githubusercontent.com/38555827/45087455-70968e00-b138-11e8-9707-c7ef7400905c.png)
#### hide Header:(subtable)
![image](https://user-images.githubusercontent.com/38555827/45087644-38dc1600-b139-11e8-9f2a-875eebc80f1e.png)

**Comment by LiangLuDeng** [comment]
I provided the online reproduction in the issue above@zombieJ

**Comment by yesmeck** [comment]
I would recommend you using [tree data](https://ant.design/components/table-cn/#components-table-demo-expand-children)
