### ISSUE TITLE
antd中的Table组件没有集成pagination中的showtotal功能

### ISSUE THREAD

**Issue by Captain-G** [ant-design/ant-design#12076]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表格本身就带有pagination功能，但是pagination的一些功能都没有集成进去，table没有集成pagination导致ant design pro中的standardTable也没有这个功能，如果说表格需要pagination，我觉得应该把它做好，如果不需要，倒不如将table和pagination彻底分开，需要的时候自由组合

### What does the proposed API look like?
table组件尽可能完善的集成pagination，将各个属性放在table组件的pagination参数中

**Comment by zombieJ** [comment]
参考文档 pagination 配置：https://ant.design/components/table-cn/#pagination
https://codesandbox.io/s/7mo0rvl971

**Comment by Captain-G** [comment]
@zombieJ table怎么显示数据总条数？
