### ISSUE TITLE
基本的表单校验例子 校验行为不正确

### ISSUE THREAD

**Issue by chaofan** [ant-design/ant-design#1207]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

1. “密码” input 1
2. “确认密码” input 1，the two password fields are both ticked。
3. “密码” input more 1
4. press “确定”

## What you would like to happen

“确认密码” should have error on it.

## What actually happened

“确认密码” still ticked, no error on it.

May be validateFields does not call the user defined check functions like 'checkPass' and 'checkPass2'

## Online demo

http://ant.design/components/form/
基本的表单校验例子

## Environment Information

- The version of antd( 0.12.10):
- Your operating system and it's version(OSX 10.11.2):
- Your browser and it's version(Chrome 48.0.2564.109 (64-bit)):

**Comment by benjycui** [comment]
Sorry, I cannot re-produce it.

**Comment by chaofan** [comment]
1. “密码” input 1
------
![image](https://cloud.githubusercontent.com/assets/446385/13974564/c82b06a0-f0e7-11e5-9a2d-0e885d7a7e92.png)

2. “确认密码” input 1，the two password fields are both ticked。
------
![image](https://cloud.githubusercontent.com/assets/446385/13974574/df6f1aa4-f0e7-11e5-94f7-ee41e638ea7c.png)

3. “密码” input more 1
------
![image](https://cloud.githubusercontent.com/assets/446385/13974584/fd1929dc-f0e7-11e5-9aee-d1c41965ec46.png)

4. press “确定”
------
![image](https://cloud.githubusercontent.com/assets/446385/13974595/0946dc0e-f0e8-11e5-9c9a-505f8ee4be30.png)
