### ISSUE TITLE
Why is the magnifying glass icon of the Input.Search component in 3.9.1 inverted?

### ISSUE THREAD

**Issue by wangmeijian** [ant-design/ant-design#12079]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
Mac mini 10.13.6

### Reproduction link
[https://ant.design/components/input-cn/#components-input-demo-search-input](https://ant.design/components/input-cn/#components-input-demo-search-input)

### Steps to reproduce
不需要任何步骤，Search组件的icon为啥反过来了

### What is expected?
Search组件的icon和2.7.1时一样

### What is actually happening?
Search组件的icon和2.7.1镜像对称了

**Comment by wangmeijian** [comment]
before
![image](https://user-images.githubusercontent.com/9384140/45085248-d41dbd00-b132-11e8-88ed-1ae28487810d.png)

after
![image](https://user-images.githubusercontent.com/9384140/45085190-b05a7700-b132-11e8-899d-b6f0e7b3d322.png)

**Comment by yesmeck** [comment]
It's intended, we redesigned our icons.

**Comment by wangmeijian** [comment]
@yesmeck It looks strange...

**Comment by wangmeijian** [comment]
3.10.4 又改回来了，你们真会玩
![image](https://user-images.githubusercontent.com/9384140/48248107-fe407380-e430-11e8-887b-2d62419c6237.png)
