### ISSUE TITLE
monthpicker左右箭头点击无效

### ISSUE THREAD

**Issue by FranklinTesla** [ant-design/ant-design#12082]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
chrome68

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
参见你们官网demo

### What is expected?
点击左右箭头可切换年份

### What is actually happening?
点击不可切换

---
可搜我钉钉联系我，丁元

**Comment by afc163** [comment]
Fixed in rc-calendar@9.7.5, ry reinstall node_modules.
