### ISSUE TITLE
Extra buttons added to the Tabs don't work

### ISSUE THREAD

**Issue by yallie** [ant-design/ant-design#12087]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
68.0.3440.106 (Official Build) (64-bit) (cohort: Stable)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xro9x44jmo)

### Steps to reproduce
* Edit the "[Extra content](https://ant.design/components/tabs/#components-tabs-demo-extra)" tabs sample on CodeSandbox
* Add an onClick handler to the tabBarExtraContent's "Extra Action" button
* Click the button and watch nothing happens

### What is expected?
An onClick handler should be executed

### What is actually happening?
An onClick handler is ignored.

![image](https://user-images.githubusercontent.com/672878/45118810-3d68f480-b162-11e8-9c45-1bb4eca05007.png)
### Code:
```jsx
class Sample extends React.Component {
  operations =
    <Button onClick={this.handleClick} type="danger">
      Extra Action —  this button doesn't work
    </Button>;

  handleClick = () => alert("It works!");

  render() {
    return (
      <Tabs tabBarExtraContent={this.operations}>
        <TabPane tab="Tab 1" key="1">
          <Button onClick={this.handleClick} type="primary">
            Click me — this button works fine
          </Button>
        </TabPane>
        <TabPane tab="Tab 2" key="2">Content of tab 2</TabPane>
        <TabPane tab="Tab 3" key="3">Content of tab 3</TabPane>
      </Tabs>
    );
  }
}
```

**Comment by zombieJ** [comment]
You cant call a function before init it: https://codesandbox.io/s/ywwm1qrq7j

**Comment by yallie** [comment]
Oh, I see. Sorry, my bad!
Thanks for the explanation.
