### ISSUE TITLE
table在ie9，ie10下显示复选框的时候报错（无法获取未定义或 null 引用的属性“store”）

### ISSUE THREAD

**Issue by 007yaoyang** [ant-design/ant-design#12086]
table在ie9，ie10下显示复选框的时候报错,如果去掉显示复选框就会显示正常
![image](https://user-images.githubusercontent.com/926889/45112058-2da8da80-b179-11e8-8e7b-287261b96108.png)
![image](https://user-images.githubusercontent.com/926889/45112677-e3c0f400-b17a-11e8-9952-c6107ff22031.png)

**Comment by letmeknowhow** [comment]
遇到同样问题，版本3.5.4，使用网站代码即可浮现
https://ant.design/components/table-cn/#components-table-demo-row-selection-and-operation
