### ISSUE TITLE
Popconfirm - The icon is not aligned to horizon when placement= bottomLeft/bottom/bottomRight

### ISSUE THREAD

**Issue by xusiyuan841028** [ant-design/ant-design#12080]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
OSX/Chrome

### Reproduction link
[https://ant.design/components/popconfirm-cn/](https://ant.design/components/popconfirm-cn/)

### Steps to reproduce
```
<div style={{ marginLeft: 70, clear: 'both', whiteSpace: 'nowrap' }}>
      <Popconfirm placement="bottomLeft" title={text} onConfirm={confirm} okText="Yes" cancelText="No">
        <Button>BL</Button>
      </Popconfirm>
      <Popconfirm placement="bottom" title={text} onConfirm={confirm} okText="Yes" cancelText="No">
        <Button>Bottom</Button>
      </Popconfirm>
      <Popconfirm placement="bottomRight" title={text} onConfirm={confirm} okText="Yes" cancelText="No">
        <Button>BR</Button>
      </Popconfirm>
</div>
```

### What is expected?
The icon should be aligned to horizon with the title of Popconfirm. 

### What is actually happening?
But the icon has 10px gap.

---
Because the parent DIV of popconfirm has 10px `margin-top`, when the popconfirm is placed to the bottom, so the `top` of the icon element <i> should be assigned to `30px`

**Comment by xusiyuan841028** [comment]
![image](https://user-images.githubusercontent.com/1681459/45085035-493cc280-b132-11e8-91a7-71b2a9f5b891.png)

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12114
