### ISSUE TITLE
Table scroll support overflow auto and min-height

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#12088]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- `scroll={{y: number}} ` y只能是数字，不能使用css的`calc(100vh-120px)`
- `y`只能设置`table-body`的`max-height`，不够灵活，比如无法设置`height`, `min-height`

## height
表格固定高度，在数据少的时候，分页工具栏位置固定在底部，阿里云控制台以前就是这样的
> 看了这个 https://github.com/ant-design/ant-design/issues/2428 ，以前是实现了，后面改成了`max-height`

table一般有两种使用场景，增删改查的列表页和`Modal`弹框里的数据表格，

- 在列表页的时候，分页栏是固定还是跟随表格内容，各有所需，希望能都支持

- 在`Modal`里显示表格的时候，希望表格内容可以固定高度，有以下原因
  - 显示modal的时候，表格内容异步加载，modal高度会自动变化，设置modal高度不能完美解决这个问题
  - 表格数据的数量可以预估，数量不多，此时不需要分页，没有高度，就难看了，表格数据变化的时候，整个modal内容高度也在变化

## minHeight
功能需求类似`height `

## maxHeight
等同现在的`scroll={{y: number}} `

## bodyStyle
可以完全自定义`table body style`，如果不能增加属性`height`，增加`bodyStyle`也是可以的

**Comment by kunhour** [comment]
这个坚决同意，希望官方支持，自己硬改样式也可以做到

**Comment by lc-stevenzhang** [comment]
> 这个坚决同意，希望官方支持，自己硬改样式也可以做到

请教一下，我需要在一个页面上展示三个不同固定高度的table，怎么硬改样式呢？硬改一个我知道怎么改，就是直接修改 .ant-table的css样式。可这个样式是每一个table都通用的…… 而且ant table不接受className这个field。 = =

**Comment by yinlv** [comment]
`&.auto-scroll-y {
    height: 100%;
    .ant-spin-nested-loading,
    .ant-spin-container,
    .ant-table,
    .ant-table-scroll,
    .ant-table-body-inner,
    .ant-table-fixed-left,
    .ant-table-content {
      height: 100%;
    }
    .ant-table-content {
      position: relative;
    }
    .ant-table-body, .ant-table-body-inner {
      overflow-y: auto!important;
    }
    .ant-table-header {
      overflow-y: hidden!important;[如果列有轻微错位请注释掉这行(if table a little garbled, try disable this)]
    }
    .ant-table-body {
      height: calc(100% - 27px[表头高度(table head offset height)]);
    }
    .ant-table-body-outer {
      height: calc(100% - 27px[表头高度(table head offset height)]);
    }
    .ant-table-body-inner {
      overflow-x: `hidden;`
    }
  }`

这里临时给大家分享一个 max-height 的解决方法，请给你的 table 添加 className “auto-scroll-y”，props的scroll={{y: true}}。请不要忘记给你的列设置宽度，不然列错位会很严重o(>﹏<)o！！！

最终实现：给你的table父元素设置高度即可限制table的最大高度，实现overflow-y: auto类似的效果。
Effect: Give your table's parent element a height, it can makes table works as overflow-y: auto.

**Comment by damiss** [comment]
不知道你用的是哪个版本？我在给Table设置高度的时候 可以使用calc(100vh-120px)这种写法。

**Comment by yinlv** [comment]
> 不知道你用的是哪个版本？我在给Table设置高度的时候 可以使用calc(100vh-120px)这种写法。

我这里这么用之后，上下滚动表头会一起被滚走 ··· 这就很尴尬了 ···

**Comment by lc-stevenzhang** [comment]
> > 不知道你用的是哪个版本？我在给Table设置高度的时候 可以使用calc(100vh-120px)这种写法。
> 
> 我这里这么用之后，上下滚动表头会一起被滚走 ··· 这就很尴尬了 ···

我也是 = =， 兄台后来解决连表头也一起滚动这个问题了么？

**Comment by lucasleelz** [comment]
我觉得这个很重要，现在搞得很难受。y 写死一个高度，可能导致页面底部还要大量的空白，也可能导致小屏幕又显示不全。

**Comment by hardywu** [comment]
Same issue here

**Comment by afc163** [comment]
scroll.x optional values: 

- `**%`
- `**px`
- `max-content`
- `true`

**Comment by America-first-melon** [comment]
额 还没支持自定义y，，

**Comment by afc163** [comment]
`y` 现在可以写 `calc(100vh - 80px)` 这样哦。

**Comment by lcnsf18** [comment]
我现在也很苦恼，y设置的是最大高度，所以当表格的数据条数比较少的时候，分页器就上去了，不能固定在下面

**Comment by damiss** [comment]
> 我现在也很苦恼，y设置的是最大高度，所以当表格的数据条数比较少的时候，分页器就上去了，不能固定在下面

你可以当数据少的时候 手动push空的数据..

**Comment by lileilei** [comment]
@afc163  还有一种场景添加一条数据后，如何指定滚动条高度到最下面。。

**Comment by 417394980** [comment]
height可以在bodyStyle设置{height:500},不知道为什么官方文档把他隐藏了，试验过可以生效；
这样在数据少时表格高度也能固定；
在数据为空时建议不要设定高度，bodyStyle=｛data.lenght > 0 ? {height:500} : {}｝，
空时设置默认的暂无数据会挤到底部；
还有就是数据太少，表格高度过大时，最后一行数据的底线是没有的，很丑
这个要加上样式
.ant-table-tbody{
  border-bottom:1px solid #e8e8e8;
}

**Comment by 417394980** [comment]
> @afc163 还有一种场景添加一条数据后，如何指定滚动条高度到最下面。。希望能够实现。这个应用场景也挺多的吧

虽然没有暴露出方法，但其实etable滚动区域也是div加table实现的
        var $modal = $("#modal");//包裹etable的div,
        var $objTr = $(".ant-table-body", $modal);
//限制只找这个div下的etable，'.ant-table-body'是包裹普通table的div,就是Etable的除头部外的滚动区域
        var objTr = $objTr[0]; //转化为dom对象 
        $objTr.animate({scrollTop:objTr.scrollHeight},"slow");//jquery写法，执行滚动到底部动画

**Comment by james70s** [comment]
改动了一下，这个可以满足需求
https://codesandbox.io/s/pedantic-driscoll-8djlj?fontsize=14

**Comment by liuhaoliang** [comment]
使用table组件的scroll属性，当数据量少时候，也会出现纵向的滚动条。 我的意思是，为什么不设置成overflow-y: auto？这样就解决了我说的这个问题，否则不管数据多少，slidebar是一直在右侧的

**Comment by yoyo837** [comment]
@liuhaoliang 列头容易对不齐。一串的issue 你搜索一下。

**Comment by liuhaoliang** [comment]
可以参考elementui就不会出现这样的问题，可以参考一下https://elemefe.github.io/element-react/#/zh-CN/table

**Comment by galisandlerfed** [comment]
Thank you - the bodyStyle property with {overflow-x: auto} helped. Why isn't this documented in the API?

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/pull/21584

**Comment by afc163** [comment]
Merged this issue with #21066

**Comment by lishaoh** [comment]
> `y` 现在可以写 `calc(100vh - 80px)` 这样哦。

scroll={{ x: true, y: 'calc(100vh-30px)' }}

y设置的无效

"antd": "^3.25.2",

**Comment by Yukimotochern** [comment]
> > `y` 现在可以写 `calc(100vh - 80px)` 这样哦。
> 
> scroll={{ x: true, y: 'calc(100vh-30px)' }}
> 
> y设置的无效
> 
> "antd": "^3.25.2",

It should be ''scroll={{ x: true, y: 'calc(100vh - 30px)' }}''. You missed two space.

**Comment by philxavier** [comment]
大家好，我发现了这个问题，但是只会说英语，因此我将使用google翻译。我希望这一点清楚。我正在尝试让我的桌子占用其父div（高度100％）的完整性。我在这里看到的所有解决方案似乎都依赖于设置滚动：{y：'calc（100 vh-some pixel value）'。您如何找到将从“ 100vh”中减去的数字。我已经为此苦苦挣扎了一段时间。任何帮助将不胜感激。非常感谢你！！

**Comment by yoyo837** [comment]
> 大家好，我发现了这个问题，但是只会说英语，因此我将使用google翻译。我希望这一点清楚。我正在尝试让我的桌子占用其父div（高度100％）的完整性。我在这里看到的所有解决方案似乎都依赖于设置滚动：{y：'calc（100 vh-some pixel value）'。您如何找到将从“ 100vh”中减去的数字。我已经为此苦苦挣扎了一段时间。任何帮助将不胜感激。非常感谢你！！

See PR #22914

**Comment by yoyo837** [comment]
> 大家好，我发现了这个问题，但是只会说英语，因此我将使用google翻译。我希望这一点清楚。我正在尝试让我的桌子占用其父div（高度100％）的完整性。我在这里看到的所有解决方案似乎都依赖于设置滚动：{y：'calc（100 vh-some pixel value）'。您如何找到将从“ 100vh”中减去的数字。我已经为此苦苦挣扎了一段时间。任何帮助将不胜感激。非常感谢你！！

See PR #21584

**Comment by MarshallLu** [comment]
> 大家好，我发现了这个问题，但是只会说英语，因此我将使用google翻译。我希望这一点清楚。我正在尝试让我的桌子占用其父div（高度100％）的完整性。我在这里看到的所有解决方案似乎都依赖于设置滚动：{y：'calc（100 vh-some pixel value）'。您如何找到将从“ 100vh”中减去的数字。我已经为此苦苦挣扎了一段时间。任何帮助将不胜感激。非常感谢你！！

Hello! It should be ''scroll={{ x: true, y: 'calc(100vh - some pixel value)' }}''. You missed two spaces.

**Comment by sunpar** [comment]
My final solution for this was to use rc-resize-observer to dynamically calculate the size of my container, then use the scroll property on Ant Table component. See below for my code.

`<ResizeObserver
      onResize={({ height }) => {
        setTableHeight(height);
      }}
    >
      <Row className="h-full w-full flex flex-col">
        <AntTable
          components={components}
          columns={mappedColumns}
          dataSource={dataState.dataSource}
          size="small"
          rowKey={rowKey}
          bordered
          className={className}
          style={{ width: "100%", height: "100%" }}
          pagination={pagination}
          scroll={
            scroll ?? {
              y: tableHeight - 61,
            }
          }
        ></AntTable>
      </Row>
    </ResizeObserver>`

**Comment by DannyDevil0** [comment]
If someone is still looking for a solution, I found a temporary fix.

I used `react-container-dimensions` package in Parent Component


Parent Comp
 `<ContainerDimensions>{({ width, height }) => <Table height={height} />}</ContainerDimensions>`

Child Comp
 ```
 // t-head 35 + pageSelector 25 = 60
 // row = 30
 const paginationSize = (props.height - 60) / 30;

 <Table
        columns={columns}
        dataSource={data}
        size="small"
        pagination={{ pageSize: Math.floor(paginationSize) }}
     />
```

You could use same method for scroll too

**Comment by DannyDevil0** [comment]
> My final solution for this was to use rc-resize-observer to dynamically calculate the size of my container, then use the scroll property on Ant Table component. See below for my code.
> 
> `<ResizeObserver onResize={({ height }) => { setTableHeight(height); }} > <Row className="h-full w-full flex flex-col"> <AntTable components={components} columns={mappedColumns} dataSource={dataState.dataSource} size="small" rowKey={rowKey} bordered className={className} style={{ width: "100%", height: "100%" }} pagination={pagination} scroll={ scroll ?? { y: tableHeight - 61, } } ></AntTable> </Row> </ResizeObserver>`

Thanks for the idea

**Comment by ZhuAnQi123** [comment]
> calc(100vh - 80px)

百分比和calc() ,一个不生效一个报错。使用的是`"ant-design-vue": "^1.7.6",`

**Comment by RainManGO** [comment]
这个现在怎么解决的，自己计算页面比较复杂的确实不方便。

**Comment by EliezerWu** [comment]
在macos中，设置scroll.y会让表格出现滚动条，显得不太美观，还是建议提供单独设置max-height的地方

**Comment by jaycethanks** [comment]
我这里自己写的，还是有些些麻烦的， 
指定如下样式：
```css
<style lang="less" scoped>
/deep/.table-full-height.ant-table-wrapper {
  height: 100%;
  *:not(.ant-table-header, .ant-table-header *, .ant-table-body, .ant-table-body *) {
    height: 100%;
  }
  .ant-table-scroll {
    overflow: hidden;
  }
}
</style>
```
dom上需要这样去指定：
```html
        <a-table
          class="table-full-height"
          :pagination="false"
          rowKey="orderId"
          :columns="columns"
          :data-source="data"
          :scroll="{ y: 'calc(100% - 38px)' }"
          size="small"
        >
......
```

/**
  - 修改当table 指定为scroll-y时的样式
  - 修改table的高度自动撑满容器, 如果希望指定table高度撑满容器，需要加上这里自定义的类名 .table-full-height
  - 此外，table 上需要指定：
    :scroll="{ y: 'calc(100% - 38px)' }"
    size="small"
    注意： 这是calc计算时，减去像素值的参数
*/

算不上什么好的解决方法，期待官方有更直接的API 解决这类问题，
我自己的项目中需求是这样的：
![image](https://user-images.githubusercontent.com/44388103/162355766-233a96b7-8c32-4737-8562-1e2ee92a31c6.png)
我需要table 和 echart的高度都是自适应填满父级容器。
