### ISSUE TITLE
在http://ant.design/docs/resource/download下载web font放在项目目录下引用之后，怎么在代码里引用图标？按照原来的方式这样<Icon type="search"/>，图标无法显示？

### ISSUE THREAD

**Issue by Flourad** [ant-design/ant-design#1209]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/pgdXYp?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
你可以把这个例子跑起来看看：https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont

应该是可以的。

**Comment by Flourad** [comment]
@afc163 就是参照这个例子写的，但是我们是用的sass，引入方式有些差异，不能import整个iconfont文件夹，只是import了iconfont下的css文件，但是我手动把其它文件加入到了生成的css目录下~

**Comment by Flourad** [comment]
@afc163 谢谢您，问题已经解决，把iconfont文件里的.woff文件放在目录下，直接修改了antd style文件中font-face里定义的url，这样就不会从网络下载了，之前显示不出来是我把这块注释掉了~
`@font-face {
  font-family: 'anticon';
  src: url("iconfont.woff") format("woff")
}`

**Comment by afc163** [comment]
:+1:

**Comment by szalansun** [comment]
@Flourad 请问你具体是怎么解决的?
我用了style插件: plugins:  [["antd", { "style": 'css' }]]
而且项目也是用SASS,...
