### ISSUE TITLE
Customized Range picker: selecting same date issue

### ISSUE THREAD

**Issue by jacob-san** [ant-design/ant-design#12093]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ll962lj1z7)
This is the same code for Customized Range picker from the docs https://ant.design/components/date-picker/

### Steps to reproduce
1. Select a start date.
2. Select the same date as end date (Works fine).
3. Clear the two dates.
4. Do the same selecting end date first.
5. Same date in the start date picker will be disabled

### What is expected?
Same date in the start date picker should not be disabled after selecting the end date.

### What is actually happening?
Selecting Start date and End date as same is only possible when you select Start date first. If you select End date first, the same date on the start date picker appears disabled.

**Comment by zombieJ** [comment]
Hi, pls check my comment: https://github.com/ant-design/ant-design/pull/12104
