### ISSUE TITLE
当用户对table组件render出来的inputNumber获取焦点时，竟然触发了table组件的onRow click事件

### ISSUE THREAD

**Issue by dajohnny** [ant-design/ant-design#12097]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
请查看 package.json文件

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w8kl34p3k)

### Steps to reproduce
事先配置onRow click，当点击的时候row（非InputNumber）时正常，当用户点击table组件render出来的inputNumber获取焦点时，竟然触发了table组件的onRow click事件

### What is expected?
期望 当用户获取tabler中render出来的inputNumber时，不要向上冒泡，不要触发onRow的click事件！

### What is actually happening?
当下，当用户点击table中render出来的inputNumber框获取焦点时，自动触发onRow的click方法

---
table渲染的数据中，部分数据需要inputNumber动态修改，这时我使用render渲染；有个新的需求，需要点击每一item时需要触发弹窗等其他事件，这是当用户对table组件render出来的inputNumber获取焦点时，竟然触发了table组件的onRow click事件。

**Comment by zombieJ** [comment]
`stopPropagation` 了解下...

https://codesandbox.io/s/2128784lrj

**Comment by selinp** [comment]
> `stopPropagation` 了解下...
> 
> https://codesandbox.io/s/2128784lrj

当点击右侧的加减按钮时，控制台是会抛出错误的，按钮的冒泡并未被阻止
