### ISSUE TITLE
同时使用scroll和onRow时, 单元格的高度不一致

### ISSUE THREAD

**Issue by linnardo** [ant-design/ant-design#12096]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
macOS ,Chrome/68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ykrw7wxnn1)

### Steps to reproduce
同时使用scroll和onRow属性, 且column里面的组件高度不一致, 那么渲染出的表格, 同一行高度会出现不一致

### What is expected?
单元格高度一致

### What is actually happening?
高度不一致

**Comment by zombieJ** [comment]
Nice catch! fixing...
