### ISSUE TITLE
When Calendar,DatePicker and TimePicker can select multiple

### ISSUE THREAD

**Issue by BeatriceWang** [ant-design/ant-design#12103]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
select multiple

### What does the proposed API look like?
<Calendar multiple={true} />

**Comment by zombieJ** [comment]
https://ant.design/components/date-picker-cn/#components-date-picker-demo-presetted-ranges
