### ISSUE TITLE
在Form中使用TimePicker组件，且设置validator自定义校验，在点击TimePicker时代码报错

### ISSUE THREAD

**Issue by Yann-LiuZY** [ant-design/ant-design#12106]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
系统： MacOS 10.13.6    浏览器：Chorme 69.0.3497.81

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l99wpyxjv7)

### Steps to reproduce
点击TimePicker组件

### What is expected?
无异常，弹出时间面板

### What is actually happening?
组件代码报错

**Comment by zombieJ** [comment]
`TimePicker` 的 `onBlur` 是 input 组件原生事件，value 是 string 不是 moment 对象。如果需要在 onBlur 触发，可以使用 [normalize 属性](https://ant.design/components/form-cn/#getFieldDecorator(id,-options)-%E5%8F%82%E6%95%B0) 进行转换。
