### ISSUE TITLE
Menu的SubMenu zIndex异常

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#12105]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x39wvqoyzq)

### Steps to reproduce
元素ant-menu-submenu的zindex被定死为1

### What is expected?
!(元素ant-menu-submenu的zindex被定死为1)

### What is actually happening?
元素ant-menu-submenu的zindex被定死为1

**Comment by afc163** [comment]
你只描述了客观事实，没有描述问题在什么地方？

**Comment by Chastrlove** [comment]
@afc163 
![image](https://user-images.githubusercontent.com/17813559/45275560-08f19180-b4f0-11e8-8413-ab043422ab97.png)

![image](https://user-images.githubusercontent.com/17813559/45275534-f7a88500-b4ef-11e8-9eb1-8f7951a144f9.png)

如果style里每次都有默认的z-index，那ant-menu-submenu-popup 中的z-index存在的意义是什么呢，而且这会导致层级错乱，subPopMenu处于很低的层级，被别的dom遮住

**Comment by afc163** [comment]
这里确实没必要互相覆盖，@picodoth 来看下。

**Comment by JonDum** [comment]
Ran into this today. Looks like this is coming from `rc-menu`. Is there a workaround until this can get fixed? Or do we just have to add another additional style override with `!important`?

**Comment by picodoth** [comment]
Removed hard-coded zIndex in rc-menu@7.4.12 via 185a01f059246172a4d6f4820e927d0b8706c4a9
