### ISSUE TITLE
form 内的ref定义丢失

### ISSUE THREAD

**Issue by maolion** [ant-design/ant-design#1210]
![q](http://17qmjy.com/file/qTfzTF3S56e8f10e7c7d4)

嵌套在Form的FormItem里的 commponent 的 ref定义未在当前component对像的 refs对象里

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1056 https://github.com/ant-design/ant-design/issues/1210

**Comment by maolion** [comment]
谢谢
