### ISSUE TITLE
3.9.1版本的antd配合1.4.4的ant-design-pro，PageHeader下选项卡表头显示不全

### ISSUE THREAD

**Issue by xaasu** [ant-design/ant-design#12111]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
windows chrome 

### Reproduction link
[https://v1.pro.ant.design/components/PageHeader-cn/](https://v1.pro.ant.design/components/PageHeader-cn/)

### Steps to reproduce
"ant-design-pro": "~1.4.0",
"antd": "^3.9.0",

以下为antd-pro官网例子:
https://v1.pro.ant.design/components/PageHeader-cn/

```
const tabList = [{
  key: '1',
  tab: '页签一',
}, {
  key: '2',
  tab: '页签二',
}, {
  key: '3',
  tab: '页签三',
}];

    <PageHeader
      className="tabs"
      title={<div className="title">Title</div>}
      logo={<div className="logo">logo</div>}
      action={<div className="action">action</div>}
      content={<div className="content">content</div>}
      extraContent={<div className="extraContent">extraContent</div>}
      breadcrumbList={breadcrumbList}
      tabList={tabList}
      tabActiveKey="1"
    />
```

### What is expected?
选项卡正常显示
![tim 20180906172541](https://user-images.githubusercontent.com/24312839/45148496-f62e4280-b1f9-11e8-9cd3-0c8f3eb09a3b.png)

### What is actually happening?
选项卡头只显示一半
![tim 20180906173621](https://user-images.githubusercontent.com/24312839/45149095-66899380-b1fb-11e8-90b0-ea2e56c9d333.png)

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/blob/master/src/components/PageHeader/index.less#L24
```
 .tabs {
    margin: 0 0 0 -8px;

    :global {
      .ant-tabs-bar {
        border-bottom: @border-width-base @border-style-base @border-color-split;
      }
    }
  }
```
