### ISSUE TITLE
TreeSelect可勾选组件，使用时可以获取值，但是页面显示不出来title

### ISSUE THREAD

**Issue by dch1212** [ant-design/ant-design#12112]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
mac google  "react": "15.5.3"

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
按照可勾选部分的代码，本地复制一遍，都出不来title，但是value值能获取到

### What is expected?
可以展示title的值

### What is actually happening?
展示title的值那为空，都是三个横线

**Comment by WHX777** [comment]
请问您解决了这个问题吗

**Comment by Vera1128** [comment]
同问，我也遇到了

**Comment by ztplz** [comment]
有问题请建个重现的demo。

**Comment by dch1212** [comment]
看一下antd的版本，之前公司封装的是2.0的版本，我按照3.0的文档来写的，2.0的数据结构里是label，3.0里面是title
![image](https://user-images.githubusercontent.com/30695818/55227399-606c0a80-5252-11e9-98ec-79bba4cf3e14.png)
![image](https://user-images.githubusercontent.com/30695818/55227413-67931880-5252-11e9-95f2-0bb195dc2e00.png)

**Comment by Vera1128** [comment]
好棒，果然是版本的问题，周末愉快~~！！

**Comment by zhchy1996** [comment]
oh!you're right!it really work after i check my version!thanks!!!
