### ISSUE TITLE
Allow the supply of custom icon's to components that hard-code them

### ISSUE THREAD

**Issue by bryanberger** [ant-design/ant-design#12116]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A lot of Ant components, such as the `<Progress />`, hard code some logic regarding icon usage and assumes the usage of Ant's icon set and naming convention:
https://github.com/ant-design/ant-design/blob/master/components/progress/progress.tsx#L88-L94

and the `<Alert />` component assumes an icon in the Ant set (as a String) to be provided:
https://github.com/ant-design/ant-design/blob/master/components/alert/index.tsx#L121

At one point Ant used hard-coded unicode values that needed to be overriden by themers. With the use of SVGs those overrides are now useless.
eg:
```
.anticon-cross-circle:before {
  font-family: "MY-CUSTOM-ICON-SET";
  content: "MY-CUSTOM-ICON-UNICODE" !important;
}
```

While a default set of icons makes sense for most components, we must supply a way for user's of Ant to override and use custom icons (in-line with their design styles)

### What does the proposed API look like?
I'm suggesting to expose every icon as an override-able property in the effort to make Ant more attractive to custom theming.

examples:
```
<Alert
  message="Success Text"
  type="success"
  icon={<Icon component={MyCustomSvg} />} <--- overrides the default icon for the `success` type
/>

<Alert
  message="Success Text"
  type="success"
  icon={<Icon type="check" theme="outlined" />} <--- overrides the default icon for the `success` type
/>
```

Related to: https://github.com/ant-design/ant-design/issues/11802

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12247
