### ISSUE TITLE
Icon theme property does not exist in typescript

### ISSUE THREAD

**Issue by raptoria** [ant-design/ant-design#12119]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
Using Chrome on Windows

### Reproduction link
[http://na](http://na)

### Steps to reproduce
Add new Icon in React and use the theme prop
 <Icon type='frown' theme='outlined' />

### What is expected?
no error

### What is actually happening?
Property Theme does not exist on property IntrinsicAttributes & IconProps

**Comment by zombieJ** [comment]
`theme` prop dose provided, could u double confirm of this? https://unpkg.com/antd@3.9.1/lib/icon/index.d.ts
<img width="483" alt="2018-09-07 4 34 23" src="https://user-images.githubusercontent.com/5378891/45183692-66b77c80-b257-11e8-972c-a646eb3c2b92.png">
