### ISSUE TITLE
ant.design.pro的饼状图data对象中x:文案很多 的情况下会展示有问题，希望可以支持文本省略(React.ReactNode)

### ISSUE THREAD

**Issue by aozhen** [ant-design/ant-design#12110]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果支持React.ReactNode可以让饼状图更加灵活

### What does the proposed API look like?
原有的data?: Array<{
    x: string | string;
    y: number;
  }>;
变为
Array<{
    x: string | React.ReactNode;
    y: number;
  }>;

**Comment by yesmeck** [comment]
请提到 https://github.com/ant-design/ant-design-pro/issues
