### ISSUE TITLE
Form中如何设置Datepicker等时间组件的值，初始化的时候获取到值，通过setFields、setFieldsValue来设置时间组件的值？？？？

### ISSUE THREAD

**Issue by Johnny-young** [ant-design/ant-design#12118]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
通过setFields、setFieldsValue来设置datepicker等时间组件的值

### What does the proposed API look like?
能有demo

**Comment by zombieJ** [comment]
和其他组件一样弄就行了，记得值类型是 moment
