### ISSUE TITLE
升级到3.9.1版本没有wechat的icon

### ISSUE THREAD

**Issue by zhangqianliang** [ant-design/ant-design#12121]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
wechat的icon的缺失

### What does the proposed API look like?
wechat的icon

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12114
