### ISSUE TITLE
在3.7.0以下的版本Table设置filterIcon会报错

### ISSUE THREAD

**Issue by tuliprope** [ant-design/ant-design#12122]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.0

### Environment
google chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lr8mzqv13z)

### Steps to reproduce
Table设置filterIcon

### What is expected?
设置filterIcon正常工作

### What is actually happening?
报错

**Comment by zombieJ** [comment]
升级一下最新版本
