### ISSUE TITLE
3.9  how do I replace default icon svg. example datapicker's calendar icon.

### ISSUE THREAD

**Issue by kumaw** [ant-design/ant-design#12123]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
use private icon.

### What does the proposed API look like?
Icon should can replace default svg. in 3.8 i can replace iconfont file.

**Comment by afc163** [comment]
Duplicate of #12116

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12247
