### ISSUE TITLE
select选择器的下拉小箭头没有显示

### ISSUE THREAD

**Issue by kingsily** [ant-design/ant-design#12128]
antd 升级到3.9.1后select选择器的下拉小箭头显示了看了一下代码没有生成svg
如下图
![image](https://user-images.githubusercontent.com/12093660/45201405-ce95b380-b2a7-11e8-9699-bb43487b7d31.png)
![image](https://user-images.githubusercontent.com/12093660/45201427-dfdec000-b2a7-11e8-9aa7-65f49e41b73e.png)

请问这要怎么解决

**Comment by ShuBuShao** [comment]
找到问题了没 大佬

**Comment by Ale-cc** [comment]
.ant-select-combobox .ant-select-arrow{
      display: block;
    }
--
试试这个？

**Comment by Ale-cc** [comment]
showArrow={false}
这个设置为true 就可以了

**Comment by shandamengcheng** [comment]
![image](https://user-images.githubusercontent.com/39256380/132158575-c6c209c3-9b30-4c6a-9fd3-cfbba6c7a481.png)
如果设置showArrow={true}还没有显示，应该是他的颜色设置为空白了
