### ISSUE TITLE
Carousel's method goTo doesn't work when the length of previous Carousel is greater than the current

### ISSUE THREAD

**Issue by xyyit9** [ant-design/ant-design#12126]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
google chrome 68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6156jp2mow)

### Steps to reproduce
There are two arrays ,  carousel's content is one of the arrays, length of the first array is 4,  length of the second array is 3
1. Click the first button and go to 1st or 2nd or 3rd slide , just less than 4
2. Click the second button , carousel go to 1st slide , that works 
but ，when Click the first button, then slide to page 4 , click the second button,  carousel go to 3rd slide 

### What is expected?
when Click the first button, then slide to page 4 , click the second button,  carousel go to 1st slide  

### What is actually happening?
when Click the first button, then slide to page 4 , click the second button,  carousel go to 3rd slide

**Comment by zombieJ** [comment]
Since animation to 0 is still in progress and then `setState` cause reset, workaround is to set a timeout to wait for the animation finished:https://codesandbox.io/s/q9j85wxk9j

Or, you can create a issue to the [react-slick](https://github.com/akiran/react-slick) which Carousel is in using.
