### ISSUE TITLE
treeselect和select的allowClear图标不一致

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#12124]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
chrome69

### Reproduction link
[https://codepen.io/anon/pen/vzeMQL?editors=0010](https://codepen.io/anon/pen/vzeMQL?editors=0010)

### Steps to reproduce
各选择一项, 查看清除图标

### What is expected?
保持一致

### What is actually happening?
一个有圆圈,一个没有圆圈

![image](https://user-images.githubusercontent.com/2288630/45199216-1b27c180-b29d-11e8-9d2d-f6af67213c85.png)

![image](https://user-images.githubusercontent.com/2288630/45199219-21b63900-b29d-11e8-885a-af4d90b41012.png)

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12114
