### ISSUE TITLE
Customized filter panel in table in IE doesnt work correctly

### ISSUE THREAD

**Issue by GuentherK** [ant-design/ant-design#12135]
![antdesignsearch](https://user-images.githubusercontent.com/5037536/45212806-24616000-b296-11e8-93f3-8841385e04df.PNG)
![antdesignsearch](https://user-images.githubusercontent.com/5037536/45212828-393df380-b296-11e8-84bf-d2a48ef2efce.PNG)

- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
 Windows 10, IE 11

### Reproduction link
[https://ant.design/components/table/#components-table-demo-custom-filter-panel](https://ant.design/components/table/#components-table-demo-custom-filter-panel)

### Steps to reproduce
Open IE 11 go to https://ant.design/components/table/#components-table-demo-custom-filter-panel  and open the filter for searching. 

### What is expected?
That searching works.

### What is actually happening?
After inserting one character (for example "j") in the search input, it looses the focus. after writing further characters (for example "John") and clicking search the following error is shown "SyntaxError: Unexpected Quantifizierer" or it redirects to an empty page.

**Comment by GuentherK** [comment]
Sorry my bad, you can scratch the syntax error from the bug list. That's because the string method includes() was used (ES6). But the input field still looses focus in IE.

**Comment by chenshuai2144** [comment]
I can't reproduce your question, is there any other reason?
