### ISSUE TITLE
新人弱弱地问一下，这个代码是运行在服务端的还是客户端的？

### ISSUE THREAD

**Issue by yishou** [ant-design/ant-design#1213]
如果是运行在服务端，如何跟服务端语言如JSP PHP结合使用?还是只能用NodeJs?
如果是运行在客户端，要引用哪些Js才能运转这个代码?
import React from 'react';
import { DatePicker, message } from 'antd';

const App = React.createClass({
  getInitialState() {
    return {
      date: ''
    };
  },
  handleChange(value) {
    message.info('您选择的日期是: ' + value.toString());
    this.setState({
      date: value
    });
  },
  render() {
    return <div style={{width: 400, margin: '100px auto'}}>
      <DatePicker onChange={this.handleChange} />
      <div style={{marginTop: 20}}>当前日期：{this.state.date.toString()}</div>
    </div>;
  }
});

export default App;

**Comment by benjycui** [comment]
http://ant.design/docs/react/getting-started

http://doc.zengrong.net/smart-questions/cn.html
