### ISSUE TITLE
CheckBox无法作为Tree的全选组件

### ISSUE THREAD

**Issue by linnardo** [ant-design/ant-design#12134]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
macOS ,Chrome/68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yqppv6po0z)

### Steps to reproduce
点击全选,treeNode不会变为选中状态

### What is expected?
点击全选,treeNode随checkedKeys变量改变选中状态

### What is actually happening?
点击全选,treeNode不会变为选中状态

**Comment by afc163** [comment]
```diff
- this.setState({ checkedKeys });
+ this.setState({ checkedKeys: [...checkedKeys] });
```

**Comment by linnardo** [comment]
@afc163 This code is in effect, thanks
