### ISSUE TITLE
add debounce feature to AutoComplete

### ISSUE THREAD

**Issue by ihaichao** [ant-design/ant-design#12136]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
the dataSource of AutoComplete is mostly from server api, when we type in the input box, it will fire up some parallel requests without debounce which I think is not a good practice.

### What does the proposed API look like?
```javascript
<AutoComplete dataSource={dataSource} debounce={true} />
```

**Comment by afc163** [comment]
You can do it by your own in onChange.

**Comment by harunurhan** [comment]
For sure we can do it by our own but I strongly think that `debounce` is an important feature for a component like `AutoComplete` and should be provided.
@afc163

**Comment by ihaichao** [comment]
@harunurhan can't agree any more

**Comment by carlflor** [comment]
is there anywhere I can find a sample to adding debounce on AutoComplete component. Can't wrap my head around it 😅
