### ISSUE TITLE
Extra scrollbars in <Table /> with fixed rowSelection on Mac

### ISSUE THREAD

**Issue by AngusFu** [ant-design/ant-design#12139]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.1

### Environment
5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3529.3 Safari/537.36

### Reproduction link
[https://codepen.io/AngusFu/pen/yxPgXY](https://codepen.io/AngusFu/pen/yxPgXY)

### Steps to reproduce
0. **This issue is a duplication to [#6515](https://github.com/ant-design/ant-design/issues/6515), which was opened this issue on 19 Jun 2017. Since it was not resolved and closed yet, I decide to open another issue.**
1. Fork [official demo](https://ant.design/components/table-cn/#components-table-demo-fixed-columns) "components-table-demo-fixed-columns".
2. Add `rowSelection={{ selectedRowKeys: [], fixed: true }}` to `<Table />`, then run the code: SEE [https://codepen.io/AngusFu/pen/yxPgXY](https://codepen.io/AngusFu/pen/yxPgXY)
3. Scroll on the table body, we could easily noticed that there is a vertical scrollbar in the fixed left part, and a horizontal scrollbar in table header.

### What is expected?
No extra scrollbars on Mac.

### What is actually happening?
There is a vertical scrollbar in the fixed left part, and a horizontal scrollbar in table header ——

![](https://ws2.sinaimg.cn/large/006tNbRwly1fv1c273s19j31kw0czq38.jpg)

---
Online Demo: [https://codepen.io/AngusFu/pen/yxPgXY](https://codepen.io/AngusFu/pen/yxPgXY)
Seems this only occurs when using `<Checkbox />`.
Using `{ fixed: 'left', render: () => <Checkbox />, ... }`  in `props.columns` would get similar result.

**Comment by AngusFu** [comment]
#6515

**Comment by AngusFu** [comment]
The same issue with Firefox,  for [official demo](https://ant.design/components/table/#components-table-demo-fixed-columns-header).
Env: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:61.0) Gecko/20100101 Firefox/61.0"
![image](https://user-images.githubusercontent.com/8180186/45229293-0b899680-b2f8-11e8-800c-9b29b2a102e2.png)

**Comment by afc163** [comment]
We can discuss in #6515

**Comment by zombieJ** [comment]
Set header div opacity can hide the scroll bar as workaround, but not sure if it's the best way: https://codepen.io/zombieJ/pen/MqOZdX

@afc163 , how do you think about this?
