### ISSUE TITLE
It supports summing certain items in a table header grouping and displaying them in Alert

### ISSUE THREAD

**Issue by shunzizhan** [ant-design/ant-design#12133]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In practice, we need to sum certain items in a table header grouping and show the accumulated values on Alert

### What does the proposed API look like?
 const columns = [
      ……
      {
        title: '第一列',
        needTotal:true, //该列需要累加
        sumInfo:"第一列b c总和 ",//提示信息头，如果没有，则默认title
        unit:"元",//单位,没有为空
        key:"b c",
        children: [{
          title: 'a',
          dataIndex: 'num1',
          align:'center'
        },{
          title: 'b',
          dataIndex: 'num2',
          align:'center',
          needSum:true //是否需要累加
        },{
          title: 'c',
          dataIndex: 'num3',
          align:'center',
          needSum:true //是否需要累加
        }]
      },
      ……
    ]

In fact, I have finished the extension and I don't know if I can pull it in
https://blog.csdn.net/u011613356/article/details/82497531

**Comment by zombieJ** [comment]
It's too specific for the usage requirement. Pls use `name` of `columns` prop to customize your title.
