### ISSUE TITLE
cascader 两级联动时, 第三级是空白

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#12144]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrome69

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
修改数据为两级联动

### What is expected?
两级联动时,隐藏第三级空白

### What is actually happening?
数据结构固定只有两级 , 多出第三列空白列, 

![image](https://user-images.githubusercontent.com/2288630/45260401-85fe0780-b419-11e8-9040-f4c46c4e5ca4.png)

### 选择第二列之后,第三列闪一下,就没了
![form](https://user-images.githubusercontent.com/2288630/45260411-b9d92d00-b419-11e8-81dd-9747bcc06399.gif)

**Comment by zombieJ** [comment]
不要设置 children: https://codesandbox.io/s/l58v5k788m

**Comment by catherinejing** [comment]
> 不要设置 children: https://codesandbox.io/s/l58v5k788m

您好，数据类型为两级，但是在选择的时候，选完第二级之后，需要再点击一次才能关闭复层，请问下这个问题如何解决？
