### ISSUE TITLE
Documentation for Menu: type of children

### ISSUE THREAD

**Issue by waywardmonkeys** [ant-design/ant-design#1215]
Looking at the `develop-1.0.0` and `master` branches, the docs for `Menu.SubMenu` and `Menu.ItemGroup` props both mention a `children` property. This property claims to have the type `(MenuItem or SubMenu)[]` in one case and `MenuItem[]` in the other.

This is how it is defined in the `antd` typings for TypeScript as well.

But if we go back and look at the docs from the underlying `menu` component from `react-component` from https://github.com/react-component/menu, then we see that it documents only one of those props as including `children` and that it has the type `React.Element[]`.

I'm not sure that we should be documenting this property at all. It is something that is assumed to exist and is automatically populated rather than manually populated. And when it is, it is populated with `React.Element[]` and not instances of either `MenuItem` or `SubMenu`.

While the current definition in the `antd` typings works, there is a pending fix to the `react` typings which breaks the `antd` typing. I'm going to submit a fix, but ran across this set of discrepancies.

I think that:

* We should perhaps not document `children` on either set of props.
* But if we do, we should indicate that the type is `React.Element[]`.

**Comment by waywardmonkeys** [comment]
The issue with the typings is being resolved in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8592

**Comment by waywardmonkeys** [comment]
@bang88 - You might be interested in this.

**Comment by bang88** [comment]
Waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8561 lands

**Comment by afc163** [comment]
We don't expected any other `React.Element` as children in Menu. But it miss the `propTypes` validation, you can PR for that.
