### ISSUE TITLE
是否考虑添加一个生成纯的脚手架命令？

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design#12150]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
实际使用 Pro 时，Pro 提供的范例过多，基本上都需要全部删掉，然后实现自己的业务，删除的过程很麻烦，尤其是认证那一块，相互依赖。对于我来讲，只需要 Pro  + antd，其它的使用范例掌握了方法之后没有使用的需求。

是不是可以考虑实现一个纯的 Pro，不包含这些样例，或者每个文件夹下只包含一个样例，比如 model/index component/index 等等。

### What does the proposed API look like?
    pro new # 安装脚手架
    pro new -p # 安装纯脚手架

**Comment by yutingzhao1991** [comment]
这个正在设计中，未来会考虑和 `umi generate` 这个命令一起来实现这样的功能。可以让每个页面都变成一个可以被独立使用的物料。

有什么更具体的想法和建议可以提出来。

**Comment by zhangjie2012** [comment]
好像提错地方了···，需求是 ant design pro 的，不是 antd。
