### ISSUE TITLE
定制主题，部分组件未生效

### ISSUE THREAD

**Issue by jinjinwa** [ant-design/ant-design#12154]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrome

### Reproduction link
[https://ant.design/docs/react/customize-theme-cn](https://ant.design/docs/react/customize-theme-cn)

### Steps to reproduce
1:使用roadhog，在webpackrc.js定制主题
2:button组件未生效

### What is expected?
全局主题色被覆盖

### What is actually happening?
目前发现button组件颜色未被覆盖

**Comment by choquet33** [comment]
我也遇到这个问题，怎么解决

**Comment by zombieJ** [comment]
@choquet33 能给个重现吗？麻烦你啦~

**Comment by gooddaddy** [comment]
。。我也发现了这问题，怎么办啊

**Comment by gooddaddy** [comment]
我知道为什么了，研究了2个小时。。
原因是 我在 app.jsx 中引入了：
import 'antd/dist/antd.css'

然而我又使用了babel-plugin-import 插件按需加载样式
这两个有冲突

所以在使用按需加载样式的时候 必须删除掉 import 'antd/dist/antd.css'
