### ISSUE TITLE
Tree option "autoExpandParent" is not respected for the first render

### ISSUE THREAD

**Issue by supnate** [ant-design/ant-design#12151]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
macOS 10.12.6 Chrome 69.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mmr8069xqx)

### Steps to reproduce
Create a tree with "autoExpandParent={false}" and "expandedKeys={['child1', 'child2'}".

### What is expected?
The root node is not expanded.

### What is actually happening?
The root node is expanded

---
The bug only occurs on first render. It behaves correctly on subsequent  updates. If you click 'update' button on the sample page, the root node is collapsed which is correct.

**Comment by zombieJ** [comment]
Use `defaultExpandParent={false}` for the first render: https://codesandbox.io/s/j2p6q3yn9y
