### ISSUE TITLE
Slider滑动输入条,在输入框中输入一个-减号,就会造成一个类型错误!

### ISSUE THREAD

**Issue by helpceo** [ant-design/ant-design#12157]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
任何环境

### Reproduction link
https://ant.design/components/slider-cn

### Steps to reproduce
在滑块后面的输入框里输入减号(-)立马就报类型错误!

### What is expected?
解决这个bug,用户误操作整个页面会受到这个错误的影响

### What is actually happening?
TypeError: Cannot read property 'toFixed' of undefined

**Comment by helpceo** [comment]
toFixed()这个是保留几位小数的函数,如果输入其他的类型,应该没有这个方法了!

**Comment by zombieJ** [comment]
这个例子写的比较简单， `InputNumber` 里 `onChange` 如果输入字符串暂时不是合法数字触发会把当前输入 string 提供出来，需要转一下：https://codesandbox.io/s/3yv69796jq
