### ISSUE TITLE
3.8.4以后的版本，打包后main.js比以前大了500kb

### ISSUE THREAD

**Issue by javaLuo** [ant-design/ant-design#12155]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
webpack4,babel7,所有其他包均为最新版本（2018-9-10）

### Reproduction link
[https://github.com/javaLuo/react-luo](https://github.com/javaLuo/react-luo)

### Steps to reproduce
重现链接中的那个项目，yarn install（此时antd版本是3.9.2）, yarn build,查看build/dist/main.js的大小。
再把package.json中的antd改成3.8.2，重新install,build后查看build/dist/main.js的大小
前者比后者大了500kb...这是正常的吗 ?

### What is expected?
3.9.2,打包后main.js应该也只有300～400KB左右

### What is actually happening?
3.9.2打包后main.js有800多KB

**Comment by yesmeck** [comment]
见 #12011
