### ISSUE TITLE
Module not found: Can't resolve 'antd' 

### ISSUE THREAD

**Issue by StanislavBerezin** [ant-design/ant-design#12169]
I've created a project by using create-react-app and started getting some problems, at first i thoght i've done something wrong with the project, so decided to start from scratch and did everything according to your doccumentation. In my app.js file i have the following code
```
import React, { Component } from 'react';

import './App.css';
import { Menu, Icon } from 'antd';

const SubMenu = Menu.SubMenu;
const MenuItemGroup = Menu.ItemGroup;

class App extends Component {
  state = {
    current: 'mail',
  }

  handleClick = (e) => {
    console.log('click ', e);
    this.setState({
      current: e.key,
    });
  }

  render() {
    return (
      <div >
        <Menu
        onClick={this.handleClick}
        selectedKeys={[this.state.current]}
        mode="horizontal"
      >
        <Menu.Item key="mail">
          <Icon type="mail" />Navigation One
        </Menu.Item>
        <Menu.Item key="app" disabled>
          <Icon type="appstore" />Navigation Two
        </Menu.Item>
        <SubMenu title={<span className="submenu-title-wrapper"><Icon type="setting" />Navigation Three - Submenu</span>}>
          <MenuItemGroup title="Item 1">
            <Menu.Item key="setting:1">Option 1</Menu.Item>
            <Menu.Item key="setting:2">Option 2</Menu.Item>
          </MenuItemGroup>
          <MenuItemGroup title="Item 2">
            <Menu.Item key="setting:3">Option 3</Menu.Item>
            <Menu.Item key="setting:4">Option 4</Menu.Item>
          </MenuItemGroup>
        </SubMenu>
        <Menu.Item key="alipay">
          <a href="https://ant.design" target="_blank" rel="noopener noreferrer">Navigation Four - Link</a>
        </Menu.Item>
      </Menu>
      </div>
    );
  }
}

export default App;
```

and in App.css i have the following
```
@import '~antd/dist/antd.css';
```

However it gives me errors like 
```
1)
Uncaught Error: Cannot find module "-!../node_modules/css-loader/index.js?{"importLoaders":1}!../node_modules/postcss-

2)./src/App.js
Module not found: Can't resolve 'antd' in
```

Is there a decent documentation on how to get started with this package?

**Comment by tarun4all** [comment]
i am getting the same issue on vs code 
any help please

**Comment by danilocecilia** [comment]
same issue here

**Comment by tarun4all** [comment]
@danilo i have solved it you can add classname for it as per ant-d team but i found it was not also working ao i applied my custom javascript code like document.getElementByClassname('').setAttribute("style", border:red);

**Comment by hasan-shafiq-ivolve** [comment]
I also have same issue

**Comment by Hamza-Liaqat1** [comment]
I had same issue but i solved it, just add ~ before this line 'antd/dist/antd.css'; in your css file, so finally this will be `@import '~antd/dist/antd.css'; `

**Comment by Hamza-Liaqat1** [comment]
> I also have same issue

just add in your css file `@import '~antd/dist/antd.css';`

**Comment by zhaodengping** [comment]
step1:confirm your code is "@import '~antd/dist/antd.css';" 
step2:reInstall "npm i"  

My situation is step2，and successful

**Comment by pavinduLakshan** [comment]
This happened to me when I tried to install a package using NPM when I had previously used Yarn and there was a `yarn.lock` file. Removing the `package-lock.json` and installing packages using `yarn` fixed the issue for me.

**Comment by meghna750** [comment]
I had the same issue, got it solved by installing
`react-router-dom` by `npm install react-router-dom`

**Comment by DenisOuma** [comment]
Just install antd with this command
`npm i antd`

**Comment by cristoferrao** [comment]
Error: Cannot find module 'antd/lib/modal/confirm
 getting this error when upgraded to antd^5.0.0
I am using confirm like 
getting it everywhere m using it 
```
import confirm from "antd/lib/modal/confirm";
const app =()=>{

const funcCall=()=>{
       let a = confirm({
                      okCancel: true,
                      title: "Confirm Delete",
                      onOk: () => {
               
                      },
                    });
}
return <></>
}
```

**Comment by cristoferrao** [comment]
> Error: Cannot find module 'antd/lib/modal/confirm getting this error when upgraded to antd^5.0.0 I am using confirm like getting it everywhere m using it
> 
> ```
> import confirm from "antd/lib/modal/confirm";
> const app =()=>{
> 
> const funcCall=()=>{
>        let a = confirm({
>                       okCancel: true,
>                       title: "Confirm Delete",
>                       onOk: () => {
>                
>                       },
>                     });
> }
> return <></>
> }
> ```

solved 
using 
import {Modal} from 'antd';
const {Confirm}=Modal;

**Comment by MohamedFaroukAbdelazeem** [comment]
Add in App.js

`import 'antd/dist/reset.css';`

**Comment by shanky-bhilwar** [comment]
try downgrading the version it resolved my issue

npm install antd@4.6.4

**Comment by shanky-bhilwar** [comment]
`npm install antd@4.6.4`
