### ISSUE TITLE
Default project inited by  commond "antd-init" , can't run in IE8, help!

### ISSUE THREAD

**Issue by CheckZhang** [ant-design/ant-design#1217]
Default project inited by commond "antd-init" , can't run in IE8, help!

**Comment by afc163** [comment]
antd-init 的版本是？

**Comment by CheckZhang** [comment]
0.7.0

**Comment by CheckZhang** [comment]
antd-init 的版本: 0.7.0 (这个版本号是通过antd-init -v取到的)

**Comment by sorrycc** [comment]
有啥出错信息?

**Comment by CheckZhang** [comment]
文件: component，行: 33，列: 3955

**Comment by CheckZhang** [comment]
`if(l&&(f(e,r)||a(e,r))){var u=e.__proto__;e.__proto__=t;delete e[r];e[r]=n.value;e.__proto__=u}else{e[r]=n.value}}else{if(!l&&("get"in n||"set"in n)){throw new TypeError(T)}`

**Comment by CheckZhang** [comment]
如果我在index.html中把component.js删除，再在entry/index.jsx中补充
```
require('es5-shim');
require('es5-shim/es5-sham');
require('console-polyfill');
```
并且把import改成require；
就会报新的错误：文件: common.js，行: 104，列: 15：Object.defineProperty(fn, name, (function(name) {...

**Comment by sorrycc** [comment]
https://github.com/ant-tool/atool-build/issues/28

**Comment by sorrycc** [comment]
try antd-init@0.8.1 。

**Comment by extmail** [comment]
用 antd-init@0.8.1 进行antd-init && npm install 后，直接 npm run dev 用ie浏览也还是报错:

例外被抛出且未被接住  media.match.min.js, 行33 字符3942
对象不支持此属性或方法  index.js, 行1 字符1
