### ISSUE TITLE
https://ant.design经常打不开，看不了文档

### ISSUE THREAD

**Issue by myadomin** [ant-design/ant-design#12173]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://ant.design经常打不开，看不了文档

### What does the proposed API look like?
https://ant.design经常打不开，看不了文档

**Comment by JimmieMax** [comment]
> Ant Design 系列官网由于某些众所周知的原因无法访问，建议翻墙或访问国内镜像站点。
> 
> ## 官网
> * Ant Design: https://ant.design
> * Ant Design Pro: https://pro.ant.design
> * Ant Design Mobile: https://mobile.ant.design
> * Ant Motion: https://motion.ant.design
> 
> ## 国内镜像
> * Ant Design: http://ant-design.gitee.io
> * Ant Design Pro: http://ant-design-pro.gitee.io
> * Ant Design Mobile: http://antd-mobile.gitee.io
> * Ant Motion: http://ant-motion.gitee.io



> Ant Design 系列官网由于某些众所周知的原因无法访问，建议翻墙或访问国内镜像站点。
> 
> ## 官网
> * Ant Design: https://ant.design
> * Ant Design Pro: https://pro.ant.design
> * Ant Design Mobile: https://mobile.ant.design
> * Ant Motion: https://motion.ant.design
> 
> ## 国内镜像
> * Ant Design: http://ant-design.gitee.io
> * Ant Design Pro: http://ant-design-pro.gitee.io
> * Ant Design Mobile: http://antd-mobile.gitee.io
> * Ant Motion: http://ant-motion.gitee.io
但是切换3.x版本后又跳回原来的链接了
