### ISSUE TITLE
Icon 组件 svg path 报错

### ISSUE THREAD

**Issue by doveccl** [ant-design/ant-design#12170]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
macOS 10.13.6, Chrome 68.0.3440.106, React 16.5.0

### Reproduction link
[https://ant.design/components/icon-cn/#header](https://ant.design/components/icon-cn/#header)

### Steps to reproduce
打开上述 antd 官方文档 Icon 页面

即可看到控制台报错：Error: <path> attribute d: Expected moveto path command ('M' or 'm'), "undefined".

### What is expected?
没有报错

### What is actually happening?
有报错

**Comment by HeskeyBaozi** [comment]
新的 `login` 图标路径不正确。正在修复

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design-icons/commit/6814583c1dc2d751abb3a5389c32f206d07cfe54
已修复。由于 `login` 图标有 `<defs>` 元素作为 `children`，被当做 `path` 读取 `d` 属性失败，变成了 `undefined`。进行一次判断即可解决。

需要确保文档 `antd` 依赖的 `@ant-design/icons` 是 `1.1.8` 版本以上。重新构建一次文档即可
