### ISSUE TITLE
Update sketch file with most recent icons/assets

### ISSUE THREAD

**Issue by AhmadBadrUX** [ant-design/ant-design#12175]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I use the ant sketch file extensively when designing, the icons in particular. The most recent update included icon changes that I don't have access to. Please update the sketch file asap as the current download link is only for 3.0, not 3.9.2. 

### What does the proposed API look like?
n/a

**Comment by afc163** [comment]
We are working on it, it will be released in next several months.
