### ISSUE TITLE
message方法支持在指定元素附近弹出

### ISSUE THREAD

**Issue by leeseean** [ant-design/ant-design#12178]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
添加订单的时候，如果成功则弹出提交成功，这个可以弹出在中央。如果后端接口返回错误，这个错误就在按钮下方提示下就可以了，不需要弹到中央，但message现在不支持弹在指定元素旁边

### What does the proposed API look like?
message.config({
  top: 100,
  duration: 2,
  maxCount: 3,
  attachElement: xxx//这个是附着的元素旁边，未指定则按照默认的弹出位置
});

**Comment by zombieJ** [comment]
用 Popconfirm： https://ant.design/components/popconfirm-cn/#components-popconfirm-demo-dynamic-trigger

**Comment by zombieJ** [comment]
@leeseean https://codesandbox.io/s/n3w8427880

**Comment by leeseean** [comment]
> @leeseean https://codesandbox.io/s/n3w8427880

你这个还是用组件标签的形式触发的，我要的是用api触发啊。不可能我点击那个按钮，你把按钮那个组件替换成Popconfirm组件吧？

**Comment by leeseean** [comment]
> @leeseean https://codesandbox.io/s/n3w8427880

这个demo也是在点击的按钮旁边弹出来的，我从页面顶部弹出的，不是从按钮旁边弹出来的

**Comment by leeseean** [comment]
@zombieJ 
可以看看这个demo http://aui.github.io/artDialog/test/align.html
这个demo调用dialog({
	align: 'bottom right',
	content: 'hello world'
}).show()就会按制定的位置弹出，message也可以做到就好了。而Popconfirm是写死的组件，不是通过api触发的，没有什么用

**Comment by zombieJ** [comment]
你的需求不用 API 也够了：https://codesandbox.io/s/57n4lo8vp

**Comment by afc163** [comment]
尽量遵循 Ant Design 设计规范，我们的 message 是统一在上方弹出的。

**Comment by leeseean** [comment]
> 尽量遵循 Ant Design 设计规范，我们的 message 是统一在上方弹出的。

我觉得可以根据自己的喜好配置，从上边，底部，左边右边，指定div旁边都可以

**Comment by afc163** [comment]
这是取舍的哲学问题了。

**Comment by leeseean** [comment]
> 这是取舍的哲学问题了。

就一个方向，有些需求真的满足不了

**Comment by haydonduan** [comment]
所以有方法吗
