### ISSUE TITLE
Table props not extending HTML Attributes

### ISSUE THREAD

**Issue by venkatb78** [ant-design/ant-design#12177]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
production

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r4jz29j734)

### Steps to reproduce
Trying to make table component keyboard accessibile

### What is expected?
When Using tab key i should be able to select a table row as a whole

### What is actually happening?
when using tab key, i can only select an individual column and not the whole row

---
We just started using antd , the table component specifically. The problem is i want to make the table rows keyboard accessible. I looked at the tableprops and seems like it does not accept any HTMLAttribute for table rows.

I searched the documentation, github issues and also on stackoverflow and did not come across an answer

Apologize if i am missing anything. Thanks for this great library by the way.

**Comment by venkatb78** [comment]
Just to add, what i am wanting is that when i use tab key, a whole row is selected. When i use tab key, i am only able to select a column as of now as seen in the code example below

https://codesandbox.io/s/r4jz29j734

**Comment by zombieJ** [comment]
https://codesandbox.io/s/0qwp7wr50n
