### ISSUE TITLE
Upload component must provide a property to disable click to open choose file dialog

### ISSUE THREAD

**Issue by herbertpimentel** [ant-design/ant-design#12174]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In some cases we want use upload component to wrap some elements allowing to drag files direct to those elements to perform an upload. But, when using upload with Upload.Dragger it has an onClick event that is not possible to disable this behaviour messing with the ability of those wrapped elements handle they own click events.

For users will be awesome have a nice and clean UI without too much elements on the screen but still have this feature to drag files to upload.
In the follow image my UI has a list of boxes, each box allow to upload files that will be "linked" with this box. The red line delimites each box. To show the problem, this box has a popup menu that show more options when clicked. 

A similiar UI feature is here on github issue edit input, that allows me to drag the file to attach the the issue.

![upload_wrapper](https://user-images.githubusercontent.com/1668448/45315666-57f8f000-b50b-11e8-9a14-4911816ba9ca.jpeg)

### What does the proposed API look like?
may add property to the component openChooseDialogOnClick: false

**Comment by hengkx** [comment]
https://github.com/react-component/upload/pull/125

**Comment by herbertpimentel** [comment]
@hengkx thanks to drive your attention to this... I belive that with this implementatation we may also need two extra events to this component.

now, as this component does not give any glue about an element can receive drag. We could add events `onDragEnter` and  `onDragLeave`. those events will allow visually change this container to indicate it allow drop files into this.

**Comment by hengkx** [comment]
@herbertpimentel mouse over default class `${prefixCls}-drag-hover`
see [https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx#L272](https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx#L272)
