### ISSUE TITLE
treeselect组件上线后未正常工作。

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#12183]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
win10，eact16.5.0，antd 3.8.0

### Reproduction link
[https://git.coding.net/ready-/tree-select-demo.git](https://git.coding.net/ready-/tree-select-demo.git)

### Steps to reproduce
npm start

```
系统详细信息
Google Chrome	68.0.3440.106 (正式版本) （64 位） (cohort: Stable)
修订版本	1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}
操作系统	Windows
JavaScript	V8 6.8.275.26
Flash	30.0.0.154 

### What is expected?
开发运行正常，打包后失败

### What is actually happening?
开发运行正常，打包后正常


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment]
Don't spam.
