### ISSUE TITLE
【bug】treeselect组件经打包后出现"Uncaught TypeError: Cannot read property 'i' of undefined"

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#12182]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
win10，eact16.5.0，antd 3.8.0

### Reproduction link
[https://git.coding.net/ready-/tree-select-demo.git](https://git.coding.net/ready-/tree-select-demo.git)

### Steps to reproduce
npm start

```
系统详细信息
Google Chrome	68.0.3440.106 (正式版本) （64 位） (cohort: Stable)
修订版本	1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}
操作系统	Windows
JavaScript	V8 6.8.275.26
Flash	30.0.0.154 

### What is expected?
开发运行正常，打包后失败

### What is actually happening?
开发运行正常，打包后正常


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by zombieJ** [comment]
我这边打包可以的，你是什么错误？
<img width="714" alt="2018-09-11 6 46 04" src="https://user-images.githubusercontent.com/5378891/45355470-13e11a80-b5f3-11e8-972b-1420906568b8.png">

**Comment by steady-join** [comment]
打包之后，请访问index.html文件，然后点击下拉框，就会报错。

**Comment by steady-join** [comment]
start和build都正常均不报错，但是访问index文件并点击下拉选择，就会出现"Uncaught TypeError: Cannot read property 'i' of undefined"。

**Comment by steady-join** [comment]
另外，通过我自己配置的webpack，当我回滚至上一个版本（3.1.0）的时候，正常使用。
并且我尝试使用create-react-app创建demo，这样使用，开发和上线均是可以的。
请问是你们在3.8.0与3.1.0版本，有什么配置是需要重新设置或者添加的？

**Comment by steady-join** [comment]
下面是我部署的一个静态服务，打包之后的index.html文件，请访问，并请尽快修复，谢谢。
http://ready-.coding.me/tree-select-demo/tree-select-demo/index.html

**Comment by zombieJ** [comment]
看起来像是 webpack 配置问题，试试 [umi](https://umijs.org/zh/) 打包有没有问题。

**Comment by steady-join** [comment]
可我并不清楚3.1.0和3.8.0的区别，同一套配置，为什么在不同版本会产生错误。另外...还没用过umi打包....

**Comment by afc163** [comment]
粗看上去 webpack 配置没啥错误。

**Comment by steady-join** [comment]
我已经减少了配置，只针对react，antd进行一定的配置，是我的配置有一定错误（疑惑：3.1.0版本是可行的）还是antd3.x.x版本后就针对自定义配置报错？目前解决的方案是...比如...create-react-app？

**Comment by zombieJ** [comment]
其他组件会报错吗，比如使用 Select ？

**Comment by steady-join** [comment]
Select组件没有发现，已提交。
http://ready-.coding.me/tree-select-demo/tree-select-demo/index.html

**Comment by afc163** [comment]
https://github.com/afc163/tree-select-demo/commit/d46db4e7e21d7a31545c5dee53f1b9421d54d7c2

用了 1.x 的 `uglifyjs-webpack-plugin` 之后就没问题了。原因没有细究，粗略判断是 webpack@3 自带的 uglifyjs 版本太老了压缩高级语法有问题。

https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

<img width="707" alt="image" src="https://user-images.githubusercontent.com/507615/45370743-6f270300-b61b-11e8-85ee-fba4cd64eaa4.png">
