### ISSUE TITLE
select 清除icon不一致

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#12181]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrome69

### Reproduction link
[https://codepen.io/zhanqi/pen/yxvxKV?&editors=001](https://codepen.io/zhanqi/pen/yxvxKV?&editors=001)

### Steps to reproduce
选中一个，查看清除icon

### What is expected?
和treeselect等保持一致

### What is actually happening?
很小，还是斜的

![image](https://user-images.githubusercontent.com/2288630/45335955-0bb5ba80-b5b4-11e8-8240-bb97bbf33c5e.png)

![image](https://user-images.githubusercontent.com/2288630/45335974-183a1300-b5b4-11e8-9e89-1e86b9799aea.png)

**Comment by afc163** [comment]
cascader 感觉也有问题。

**Comment by yutingzhao1991** [comment]
![image](https://user-images.githubusercontent.com/1061968/45336333-9945da00-b5b5-11e8-8241-00a56be48ff8.png)

另外选项中后面带的勾也是问题吗？之前有这个？

**Comment by afc163** [comment]
这个已经在 rc-select 里修复了。

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12196
