### ISSUE TITLE
滚动条粗细调节

### ISSUE THREAD

**Issue by OliverJason** [ant-design/ant-design#12187]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd中默认的滚动条太小了，而且不容易看清，建议加入全局样式修改快速入口

### What does the proposed API look like?
可定制的主题样式中加入滚动条样式修改

**Comment by afc163** [comment]
这是全局 css 样式，和 antd 无关，你可以自行修改。
