### ISSUE TITLE
3.9.2的Slider组件不会阻止mousedown事件冒泡

### ISSUE THREAD

**Issue by chuxiaonan** [ant-design/ant-design#12193]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
macOS10.12.6 chrome69 react16

### Reproduction link
[https://codepen.io/chuxiaonan/pen/jvZojx](https://codepen.io/chuxiaonan/pen/jvZojx)

### Steps to reproduce
- https://codepen.io/chuxiaonan/pen/jvZojx
- 打开控制台
- 拖动Slider组件
- 将antd的版本更换为3.9.2后再试

### What is expected?
期望3.9.2的Slider与3.8.4中的结果一致，即控制台没有输出'mouse down'

### What is actually happening?
在antd版本为3.9.2时，控制台输出了'mouse down'

---
业务场景：一个可拖拽的Modal中嵌入一个Slider组件，由于没有截获mousedown事件，导致整个Modal跟随一起被拖拽；如果在onChange中截获event并阻止冒泡，则会引起错误：当拖动到Slider边缘时，Slider的value会弹回到拖动的起始位置（比如在一个0-100的Slider上拖动，初始位置是5，向100方向拖动，如果拖出100，则会被弹回到5）

**Comment by zombieJ** [comment]
以前没有 mousedown 是 bug，stopPropagation 即可：https://codesandbox.io/s/n95yp45k10
