### ISSUE TITLE
Allow Calendar to display a range of months vertically

### ISSUE THREAD

**Issue by ditiem** [ant-design/ant-design#12195]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A very natural way to display a calendar in a "Sider view" is to display it continuously vertically.

Here is a good example:

https://i.stack.imgur.com/NjPRu.png

it was originally taken from https://bl.ocks.org/mbostock/4063318 where the calendars are continuous but shown horizontally.

### What does the proposed API look like?
I would propose something this:

```<Calendar vertical={true} fromDate={ moment } toDate={ moment } />```

**Comment by afc163** [comment]
Won't support.

**Comment by zmayor** [comment]
@ditiem Did you find any components like this? I need it, too.

**Comment by ditiem** [comment]
@zmayor No, sorry. I will have to do it by myself (I have something already
done). By the moment I am surviving just showing 1 month.
