### ISSUE TITLE
3.8.0更新到3.9.2之后引入Button，Tabs标签出错，Card和Icon没问题

### ISSUE THREAD

**Issue by mrandpz** [ant-design/ant-design#12191]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrom

### Steps to reproduce
3.8.0更新到3.9.2

### What is expected?
不报错

### What is actually happening?
报错 Unable to find node on an unmounted component.

**Comment by mrandpz** [comment]
删除包重新安装又出现
`
Failed to compile.

./src/index.js
Module build failed: Error: The 'decorators' plugin requires a 'decoratorsBeforeExport' option, whose value must be a boolean.
`

**Comment by chenshuai2144** [comment]
babel 的锅。建议你更新一下你的依赖，升级 babel 到正式版本

**Comment by zaaack** [comment]
table 标签也遇到了通用的问题

**Comment by infinnie** [comment]
>           table 标签也遇到了通用的问题

你想说的是 “同样” 的问题…

**Comment by mrandpz** [comment]
还原版本还不行了、、=。=

**Comment by zaaack** [comment]
antd 奇技淫巧太多了，感觉要废了，真后悔入这个坑... 😢

**Comment by mrandpz** [comment]
解决了。cnpm i roadhog@2.5.0-beta.1 --save-dev

**Comment by zaaack** [comment]
@zombieJ 我不是用 ant-design-pro, 坑更加隐晦一点，可能和 React 版本有关，原因没有找到，不过暂时也解决问题了。

**Comment by chenshuai2144** [comment]
@zaaack 检查你所有用到 babel 的库，统一升级一波，babel7 和 beta 有不兼容改动

**Comment by zaaack** [comment]
@chenshuai2144 我是用 ts 编译的，和脚手架没关系，遇到的问题还是 animate 包报的 `Unable to find node on an unmounted component` 错误，原因是因为我用的框架是把 React 当 vdom 用的，也就是说每次事件或者 render 都会触发 ReactDOM.render() 调用，这种方法在实现 elm 架构时比 setState 稍微快一点点。之前都没有遇到过兼容性问题，可能这次 antd 某个包的声明周期函数和这种写法冲突了，所以踩了坑。

**Comment by chenshuai2144** [comment]
> 原因是因为我用的框架是把 React 当 vdom 用的，也就是说每次事件或者 render 都会触发 ReactDOM.render() 调用

你这样是花样作死，生命周期什么的全干掉了

**Comment by zaaack** [comment]
@chenshuai2144 并没有，React 所有的功能依然都是支持的，因为 React 本质就是个 vdom 库。。
