### ISSUE TITLE
Drawer have a props is handler, but docs can't find it

### ISSUE THREAD

**Issue by 104gogo** [ant-design/ant-design#12192]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
none

### Reproduction link
[https://github.com/ant-design/ant-design-pro/blob/master/src/components/SettingDrawer/index.js#L139](https://github.com/ant-design/ant-design-pro/blob/master/src/components/SettingDrawer/index.js#L139)

### Steps to reproduce
none

### What is expected?
Drawer's doc have the describe of handler

### What is actually happening?
docs can't find the describe of handler

**Comment by afc163** [comment]
It is by designed, Drawer in Ant Design is like Modal, should contain any trigger element inside it.

**Comment by 104gogo** [comment]
it's very useful, I propose you should give a demo for us in Drawer's doc

**Comment by boshka252** [comment]
please, can you declare this props for typescript
