### ISSUE TITLE
Table.Sort clickable area is too small.

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#12200]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Inconvenient to use.
![image](https://user-images.githubusercontent.com/8358236/45398494-f190e080-b676-11e8-8ca6-a8cf15738585.png)

### What does the proposed API look like?
Not

**Comment by zombieJ** [comment]
similar with https://github.com/ant-design/ant-design/issues/12158
