### ISSUE TITLE
Icon组件使用createFromIconfontCN后Button组件使用icon属性，不能显示自定义图标

### ISSUE THREAD

**Issue by sbyps** [ant-design/ant-design#12206]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
win7, chrome 61.0.3163.100

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/94n7vo9xz4)

### Steps to reproduce
根据Icon组件示例https://ant.design/components/icon-cn/#components-icon-demo-custom

`
const IconFont = Icon.createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js',
});
`
`
<Button icon="icon-twitter" >11111</Button>
`

### What is expected?
Icon组件使用createFromIconfontCN后Button组件使用icon属性，能够使用自定义图标

### What is actually happening?
Icon组件使用createFromIconfontCN后Button组件使用icon属性，不能显示自定义图标

**Comment by yesmeck** [comment]
https://codesandbox.io/s/88n00z3m09

目前 `type` 只支持内置图标。

**Comment by zombieJ** [comment]
如果需要使用自定义图标可以 Button 内嵌你的 <IconFont />: https://codesandbox.io/s/n5j7pjyv30

**Comment by sbyps** [comment]
@zombieJ 感觉新图标没以前的好看了，太锐化了，不圆润，比如关闭图标，link图标

**Comment by zombieJ** [comment]
@sbyps 总需要有个适应时间哈~
