### ISSUE TITLE
provide an English version of the sketch design file

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#12214]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
English web
![image](https://user-images.githubusercontent.com/8358236/45420490-da74e180-b6bc-11e8-9a86-518286c4716e.png)

### What does the proposed API look like?
not

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9280#issuecomment-415355983
