### ISSUE TITLE
Upload 图片类型判断问题

### ISSUE THREAD

**Issue by NauxChen** [ant-design/ant-design#12218]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
浏览器版本

### Reproduction link
[https://github.com/ant-design/ant-design/blob/197d1392f500c6dc9c85715e261efbb65f65ad5e/components/upload/UploadList.tsx#L32](https://github.com/ant-design/ant-design/blob/197d1392f500c6dc9c85715e261efbb65f65ad5e/components/upload/UploadList.tsx#L32)

### Steps to reproduce
https://github.com/ant-design/ant-design/blob/197d1392f500c6dc9c85715e261efbb65f65ad5e/components/upload/UploadList.tsx#L16

```js
extname = (url: string) => {
  if (!url) {
    return '';
  }
  const temp = url.split('/');
  const filename = temp[temp.length - 1];
  const filenameWithoutSuffix = filename.split(/#|\?/)[0];
  return (/\.[^./\\]*$/.exec(filenameWithoutSuffix) || [''])[0];
};

extname('https://debug.oss.aliyuncs.com/speaking-test/cpzae/2295b61dcb8b15a2fb20f283dccabbeb.10ee953e407954122261edf0ff9ef905.png@90Q');
```

结果是.png@90Q

### What is expected?
支持阿里云老版本图像处理规则的计划

### What is actually happening?
目前没有支持

---
目前自己在 fileList的file 中加 type属性解决

**Comment by afc163** [comment]
PR is welcome~

**Comment by NauxChen** [comment]
emmm....阿里云的老版规则处理不应该放入 antd中....应该自行处理
关闭issue
