### ISSUE TITLE
需要在组件上捆绑id

### ISSUE THREAD

**Issue by erwzqsdsdsf** [ant-design/ant-design#12216]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我做软件测试，需要在组件上捆绑id，antd没有明确声明id的组件，如何设置id？

我设置了，发现没效果，不会渲染出 属性列表之外的属性。

### What does the proposed API look like?
现在的方案是临时用class代替

**Comment by afc163** [comment]
具体问题具体提，太含糊了。https://github.com/ant-design/ant-design/issues/11899
