### ISSUE TITLE
TreeNode appears to do some recursive work while leaf node is clicked

### ISSUE THREAD

**Issue by 879479119** [ant-design/ant-design#12217]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
mac chrome 68

### Reproduction link
[https://codepen.io/rocksama/pen/gdzrOJ](https://codepen.io/rocksama/pen/gdzrOJ)

### Steps to reproduce
  build a tree with some leaf node whose property 'isLeaf' is set to be false
  expand the leaf node which appears like a non-leaf one
  chrome lose control, CPU runs to 100% or higher

### What is expected?
I add the 'isLeaf' property to make the node act like a directory node in my project, but it seems not fit and harmful...

### What is actually happening?
recursive call of some function, chrome is dead.

---
点一下示例parent 1-2里面那个可以展开的node就会导致浏览器卡死

**Comment by 879479119** [comment]
It seems TreeSelect has the same problem but not fixed 🤔

**Comment by Yingkaixiang** [comment]
Has this problem been solved?
