### ISSUE TITLE
Autocomplete in CellEditable Table

### ISSUE THREAD

**Issue by ommyan** [ant-design/ant-design#12220]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i need the autocomplete in editable Cell table, when user click edit, editable cell mode active then autocomplete apear

### What does the proposed API look like?
i dont know

**Comment by afc163** [comment]
Thx for sharing, but I think that is your job.
