### ISSUE TITLE
select使用labelInValue如何在初始化和选择选项后，显示text部分内容

### ISSUE THREAD

**Issue by Youzi-wr** [ant-design/ant-design#12228]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[https://codesandbox.io/s/q89q0l3vy4](https://codesandbox.io/s/q89q0l3vy4)

问题1：希望初始化时候显示Jack而不是Jack (100)，在选择后显示Jack或Lucy而不是Jack (100)或Lucy（100）

问题2：dropdownStyle无效

### What does the proposed API look like?
使用 labelInValue 属性，当value是一个对象时，如何回显label的部分内容给

**Comment by zombieJ** [comment]
文档里有，仔细看看：https://codesandbox.io/s/n5rw20yxlm
