### ISSUE TITLE
Suggestion: Set the default value of Modal's maskClosable property to false

### ISSUE THREAD

**Issue by Silence-Rain** [ant-design/ant-design#12225]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Since the word "Modal" means a dialog monopolizes user's operations, which means all operations to the main window should be disabled before the modal dialog is normally closed.

However, the default value `true` of Modal's `maskClosable` property actually allows user to close the modal dialog abnormally ( by click on the mask ) , which seems to violate the original intention of modal dialog. 

What's more, the Modal components does provide a mask, which can be really misleading. Imagine a situation that we use a Modal component to get user's input. When looking at the modal dialog, user would easily have a thought like "this dialog provides a gray mask, so it's a modal dialog, I can't do anything before I finish all the content inside this dialog". But in actual cases, the click on the mask would cause the dialog to close, leading to loss of user's input. 

Maybe I haven't catch your design principles, but this feature does perplex our PMs ...

### What does the proposed API look like?
Set the default value of Modal's `maskClosable` property to `false`.

Or remove the mask, and change the name "Modal" into "Dialog" .

**Comment by zombieJ** [comment]
Thanks for feed back, I'm afraid that we will not change exists prop & default value. But you can wrap it with your own component:
```jsx
const MyModal = ({ maskClosable = false, ...props }) => (
  <Modal maskClosable={maskClosable} {...props} />
);
```
