### ISSUE TITLE
Table的size设为small时，表头分组后的thead单元格有问题，右侧边框不显示

### ISSUE THREAD

**Issue by wubostc** [ant-design/ant-design#12222]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
react 16.41  chrome 69

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
```
const { Table } = antd;

const columns = [{
  title: 'Name',
  dataIndex: 'name',
  key: 'name',
  width: 100,
  fixed: 'left',
  filters: [{
    text: 'Joe',
    value: 'Joe',
  }, {
    text: 'John',
    value: 'John',
  }],
  onFilter: (value, record) => record.name.indexOf(value) === 0,
}, {
  title: 'Other',
  children: [{
    title: 'Age',
    dataIndex: 'age',
    key: 'age',
    width: 200,
    sorter: (a, b) => a.age - b.age,
  }, {
    title: 'Address',
    children: [{
      title: 'Street',
      dataIndex: 'street',
      key: 'street',
      width: 200,
    }, {
      title: 'Block',
      children: [{
        title: 'Building',
        dataIndex: 'building',
        key: 'building',
        width: 100,
      }, {
        title: 'Door No.',
        dataIndex: 'number',
        key: 'number',
        width: 100,
      }],
    }],
  }],
}, {
  title: 'Company',
  children: [{
    title: 'Company Address',
    dataIndex: 'companyAddress',
    key: 'companyAddress',
  }, {
    title: 'Company Name',
    dataIndex: 'companyName',
    key: 'companyName',
  }],
}, {
  title: 'Gender',
  dataIndex: 'gender',
  key: 'gender',
  width: 80,
  fixed: 'right',
}];

const data = [];
for (let i = 0; i < 100; i  ) {
  data.push({
    key: i,
    name: 'John Brown',
    age: i   1,
    street: 'Lake Park',
    building: 'C',
    number: 2035,
    companyAddress: 'Lake Street 42',
    companyName: 'SoftLake Co',
    gender: 'M',
  });
}

ReactDOM.render(
  <Table
    columns={columns}
    dataSource={data}
    bordered
    size="small"
    scroll={{ x: '130%', y: 240 }}
  />,
  mountNode);
```

### What is expected?
Table的size设为small时，表头分组后的thead单元格可以正常显示

### What is actually happening?
Table的size设为small时，表头分组后的thead单元格有问题，右侧边框不显示

---
直接把代码粘贴运行就能看到bug

**Comment by zombieJ** [comment]
重现链接不对...

**Comment by wubostc** [comment]
> Hello @wubostc. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.


http://183.129.204.238:610/reportform/%E5%9C%A8%E7%BA%BF%E7%9B%91%E6%B5%8B

**Comment by wubostc** [comment]
https://codesandbox.io/s/7zy4x7qq2q

**Comment by wubostc** [comment]
> Hello @wubostc. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.

https://codesandbox.io/s/7zy4x7qq2q

**Comment by Angelki** [comment]
Multiple border in small border when grouped last line.   https://codesandbox.io/s/92w6293y9p
