### ISSUE TITLE
Select选择器添加allowClear，当选中项超过一行时删除图标不能居中显示

### ISSUE THREAD

**Issue by marga8080** [ant-design/ant-design#12226]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
win10、chrome68

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o5kx47y426)

### Steps to reproduce
![](http://thyrsi.com/t6/369/1536807450x1822611359.png)

### What is expected?
清除按钮垂直居中，最好能清晰一点

### What is actually happening?
选中项有多行时在顶部显示不能居中

**Comment by zombieJ** [comment]
感谢你的建议~
不过从用户体验角度出发，删除按钮应该在一个稳定的位置从而减少用户的记忆/识别成本。

当然，你可以修改一下 css 来实现这个需求：https://codesandbox.io/s/j4ww23zlnv
