### ISSUE TITLE
Unable to customize table-header-color

### ISSUE THREAD

**Issue by James2516** [ant-design/ant-design#12232]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Chrome

### Steps to reproduce
Table header color is not changed (remains black) when [`@table-header-color`](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L345) is overridden.
Overriding `@table-header-bg` works so the problem lies with `@table-header-color`.

### What is expected?
All table header colors should be changed.

### What is actually happening?
Table header colors remain black.

---
No reproducible demo is provided as theme customisation requires webpack changes (not possible on codesandbox).

**Comment by afc163** [comment]
It works pretty well in my machine. You can try to provide a reproducible demo as a github repo. I am closing it now and reopen it as soon as that reproducible demo is provided.
