### ISSUE TITLE
使用Form组件中的rules，控制台出现Cannot read property 'push' of undefined at createBaseForm.js:414

### ISSUE THREAD

**Issue by mayunyi** [ant-design/ant-design#12239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrome69

### Reproduction link
[https://github.com/mayunyi/react-webpack-blog](https://github.com/mayunyi/react-webpack-blog)

### Steps to reproduce
设置rules：
``` <Form onSubmit={this.handleLogin} className='formStyle'>
                <FormItem>
                    {getFieldDecorator('userName', {
                        rules: [{ type: 'array', required: true, message: 'Please select time!' }],
                    })(
                        <Input prefix={<Icon type="user" style={{fontSize: 13}}/>} placeholder="Username"/>
                    )}
                </FormItem>
                <FormItem>
                    {getFieldDecorator('password', {
                        rules: [{ type: 'array', required: true, message: 'Please select time!' }],
                    })(
                        <Input prefix={<Icon type="lock" style={{fontSize: 13}}/>} type="password"
                               placeholder="Password"/>
                    )}
                </FormItem>
                <FormItem>
                    <Button className={style.loginButton} type="primary" htmlType="submit">
                        登录
                    </Button>
                </FormItem>
            </Form>
```
这样我在输入框输入字符串然后清空输入框，控制台就报错

我去除rules后没有验证是不会报错的，不知道是什么情况

### What is expected?
想官网登录案例一样有提示

### What is actually happening?
我清空字符没有设置的提示文字校验

**Comment by zombieJ** [comment]
提供一个 [codesandbox](https://codesandbox.io/) 看看

**Comment by mayunyi** [comment]
codesandbox上测试是好的。https://github.com/mayunyi/react-webpack-blog拉取下拉登录和组成的都是有不能校验的

**Comment by zombieJ** [comment]
@mayunyi , 方便的话能否麻烦你提供一个最小重现？一整个代码放上来实在不方便看……

**Comment by shinygang** [comment]
@mayunyi 你问题怎么解决的，我这边也出现了。

**Comment by vince-fly** [comment]
遇到同样的问题，也没解决

**Comment by shinygang** [comment]
@vince-fly 我今天发现是lodash的插件引起的

**Comment by vince-fly** [comment]
@shinygang 兄弟，有解决方案吗？

**Comment by shinygang** [comment]
@vince-fly 先把插件去掉呗，先让能用。

**Comment by vince-fly** [comment]
移除lodash可以用了，我们项目，一兄弟加了lodash-webpack-plugin babel-plugin-lodash lodash，欲哭无泪啊

**Comment by BoomBooA** [comment]
> @shinygang 兄弟，有解决方案吗？

LodashModuleReplacementPlugin 配置参数
```
'paths': true
```

**Comment by shinygang** [comment]
@BoomBooA LodashModuleReplacementPlugin  我是没有再使用这个插件。

**Comment by kwzm** [comment]
@BoomBooA 厉害，加上确实好了，不过这是为什么呢？
