### ISSUE TITLE
Table组件rowSelection= {fixed: true, type: "radio"}时异步加载columns 左侧列会闪动

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#12233]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Google Chrome 68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kx69xoz0r7)

### Steps to reproduce
进入重现链接,等待数据出现

### What is expected?
左侧列不会闪动

### What is actually happening?
左侧列闪动

---
我的columns, dataSource都是异步加载的, 项目中实际情况是加载完数据后左侧列和右侧数据没有对齐(随机出现, 偶尔是对齐的), 随便选中一行后就对齐了,只有radio会这样, 但是demo暂时只能复现成这样

**Comment by zombieJ** [comment]
Nice catch! 我看一下~
