### ISSUE TITLE
RangePicker to be able to select hours only

### ISSUE THREAD

**Issue by hussaintamboli** [ant-design/ant-design#12231]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If I want my users to just select time in hours only, I am not able to do it right now.

### What does the proposed API look like?
<RangePicker
      showTime={{ format: 'HH:mm' }}
      format="YYYY-MM-DD HH:00"
      placeholder={['Start Time', 'End Time']}
      onChange={onChange}
      onOk={onOk}
    />

**Comment by zombieJ** [comment]
If only hour, why not use select to combine one? https://ant.design/components/input/#components-input-demo-group
