### ISSUE TITLE
table中的render有一个button，如何根据数据不同显示不同类型的button

### ISSUE THREAD

**Issue by NICK-DUAN** [ant-design/ant-design#12240]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
每行数据可以对应一个不同的可以自定义的render

### What does the proposed API look like?
render中的数据可以根据表格中的数据发生动态变化。

**Comment by NICK-DUAN** [comment]
#### 例如，根据record中的is_vaild字段的true和false，可以选择显示button的disabled选项是否生效

**Comment by zombieJ** [comment]
render 里可以拿到 record 信息的
