### ISSUE TITLE
缩起内嵌菜单，菜单内容有位移，有接口进行调整吗？

### ISSUE THREAD

**Issue by Mantak** [ant-design/ant-design#12249]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://ant.design/components/menu-cn/   内嵌菜单进行折叠的时候，内容有位移，如何进行调整位移呢？

### What does the proposed API look like?
collapsedOffset='123px'

**Comment by afc163** [comment]
无法理解，请详述。

**Comment by fangit01** [comment]
![menu problem](https://user-images.githubusercontent.com/33096165/45622172-70967680-bac6-11e8-91fa-97e0e07085f9.png)
3.9.2版本。可能是相关的问题。
虽然menu收起来了，但是sub-menu似乎还是占用着位置，导致下方会出现滚动条。
谢谢

**Comment by fangit01** [comment]
issue demo [https://codepen.io/anon/pen/EedPRz?editors=0010](https://codepen.io/anon/pen/EedPRz?editors=0010)

**Comment by zombieJ** [comment]
@picodoth Seems `visibility: hidden` still exceed the bound. Pls check:
<img width="306" alt="2018-09-17 9 57 16" src="https://user-images.githubusercontent.com/5378891/45627537-c407c500-bac4-11e8-97c2-490009061f75.png">
<img width="277" alt="2018-09-17 9 57 22" src="https://user-images.githubusercontent.com/5378891/45627539-c407c500-bac4-11e8-8f3e-df836a1df538.png">

**Comment by afc163** [comment]
I believe this problem has been fixed now.

cc @picodoth
