### ISSUE TITLE
Select with dropdownMatchSelectWidth

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#12248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
After the dropdownMatchSelectWidth property is set by the Select component, can the minWidth of the Option be the same as the width of the Select? Now the display is ugly. 
I prefer the performance before 3.8

### What does the proposed API look like?
dropdownMatchSelectWidth

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
