### ISSUE TITLE
DirectoryTree 控件，多次频繁的不停切换目录的展开收起状态时，控制台会不停报警告

### ISSUE THREAD

**Issue by mlf75** [ant-design/ant-design#12242]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Chrome 68.0.3440.106（正式版本）

### Reproduction link
[https://codepen.io/pen/?editors=0011](https://codepen.io/pen/?editors=0011)

### Steps to reproduce
不停的点击一个目录节点

### What is expected?
控制台不报警告

### What is actually happening?
控制台报警告

---
本地在 DirectoryTree 的 onClick 事件里添加 event.persist() 控制台就不会报警告了

**Comment by zombieJ** [comment]
看起来应该是你的代码里延迟使用了 event 才会，官方例子里我试了没有问题。如果方便的话，提供一下网上重现吧：https://codesandbox.io/s/4y6rl0127

**Comment by mlf75** [comment]
@zombieJ 官网例子也会报错 ，触控板一直不停的点击一个根节点

Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `metaKey` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

**Comment by zombieJ** [comment]
给个截图看看：
![kapture 2018-10-09 at 10 33 18](https://user-images.githubusercontent.com/5378891/46643465-d0a4a800-cbae-11e8-93e3-32f4d6bfc532.gif)

**Comment by guoguo0202** [comment]
4.5.3版本下，DirectoryTree设置selectable=false会引发此问题
