### ISSUE TITLE
请问，要使用ant中的组件，项目目录必须是antd-init出来的那样吗？

### ISSUE THREAD

**Issue by insekkei** [ant-design/ant-design#1224]
## What I did
$ npm install antd --save

页面上：

import { Select } from 'antd';
const Option = Select.Option;
..
handleChange(value) {
        console.log(`selected ${value}`);
    },
render: function () {
 return <Select showSearch
                    style={{ width: 200 }}
                    placeholder="请选择人员"
                    optionFilterProp="children"
                    notFoundContent="无法找到"
                    searchPlaceholder="输入关键词"
                    onChange={this.handleChange}>
                    <Option value="jack">杰克</Option>
                    <Option value="lucy">露西</Option>
                    <Option value="tom">汤姆</Option>
                  </Select>;
}
...
渲染出来的select看着是正常的，但一点击就报错：
app.js:21 Uncaught TypeError: p.default.unstable_renderSubtreeIntoContainer is not a function(anonymous function) @ app.js:21Trigger_componentDidUpdate @ app.js:21o.notifyAll @ app.js:29f.close @ app.js:33a.closeAll @ app.js:34a.perform @ app.js:34a.perform @ app.js:34v.perform @ app.js:34D @ app.js:34ReactUpdates_flushBatchedUpdates @ app.js:33a.closeAll @ app.js:34a.perform @ app.js:34d.batchedUpdates @ app.js:32o @ app.js:34v.dispatchEvent @ app.js:32
app.js:21 Uncaught TypeError: p.default.unstable_renderSubtreeIntoContainer is not a function(anonymous function) @ app.js:21Trigger_componentDidUpdate @ app.js:21o.notifyAll @ app.js:29f.close @ app.js:33a.closeAll @ app.js:34a.perform @ app.js:34a.perform @ app.js:34v.perform @ app.js:34D @ app.js:34ReactUpdates_flushBatchedUpdates @ app.js:33a.closeAll @ app.js:34a.perform @ app.js:34d.batchedUpdates @ app.js:32l @ app.js:34r @ app.js:33f.enqueueSetState @ app.js:33r.setState @ app.js:31u.default.createClass.setOpenState @ app.js:17u.default.createClass.onDropdownVisibleChange @ app.js:17c.default.createClass.setPopupVisible @ app.js:21(anonymous function) @ app.js:21

另外，换成任何一个有交互的组件，比如穿梭框什么的，都会报这个错。是不是缺什么依赖包？

或者，使用ant-ui必须采用antd-init出来的结构？

谢谢

**Comment by afc163** [comment]
不一定的，你也可以参考下面链接里提到的脚手架：

http://ant.design/docs/react/getting-started#%E8%87%AA%E8%A1%8C%E6%9E%84%E5%BB%BA

https://github.com/ant-design/ant-design/issues/129

**Comment by insekkei** [comment]
不用webpack可以吗？我使用的是flux＋gulp。。。

**Comment by afc163** [comment]
应该也是可以的，不过只能自行探索了。

**Comment by insekkei** [comment]
试了下其它组件，大部分静静地看着没问题，一动就bug。。。不能简单地安装引入直接使用吗。。。

总觉得还缺了啥。。。有肉没骨头的感觉。。。真的只要npm install antd之后引入css文件吗。。。

**Comment by afc163** [comment]
你提供的信息太少了，can't help
