### ISSUE TITLE
antd 如何连接 nextjs

### ISSUE THREAD

**Issue by VanquisherMe** [ant-design/ant-design#12255]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrome

### Reproduction link
[https://github.com/VanquisherMe/with-nextjs-antd-app/blob/master/next.config.js#L28](https://github.com/VanquisherMe/with-nextjs-antd-app/blob/master/next.config.js#L28)

### Steps to reproduce
https://github.com/VanquisherMe/with-nextjs-antd-app

【yarn 可以看到】

### What is expected?
我想在项目里用cssModules:true，但是 antd 不包括在其中

### What is actually happening?
antd 的class 直接被转换了

---
我需要一个例子 我尝试了很久
但没有成功
https://github.com/zeit/next.js/tree/canary/examples/with-ant-design-less
我看过这个但是这个不适合在项目中使用

**Comment by afc163** [comment]
Maybe you should discuss this in next issues.

**Comment by GoatherdNaN** [comment]
@VanquisherMe 也许你可以把@zeit/next-less，修改下源码，把antd的相关样式的cssModules关掉，暂时只能这么解决了，亲测可以完美使用。如果有更好的办法请告诉我

**Comment by sdli** [comment]
solution : https://www.yuque.com/steven-kkr5g/aza/ig3x9w

**Comment by xiaofengbai** [comment]
使用按需加载后,自己添加的css 属性transition 会覆盖原先的css由于引入有时间差,有时候ant 自带的css渲染完成后,模块的css才会加载完成,这个过程还会有一个 明显的transition过渡效果,怎么解决呢,怎么样才能让模块的css覆盖ant的

**Comment by xiaofengbai** [comment]
@VanquisherMe
