### ISSUE TITLE
Icons are doubled by .anticon-icon:before after migrating 3.8.0-3.9.2

### ISSUE THREAD

**Issue by arherzf8er** [ant-design/ant-design#12258]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Ubuntu 18.04 or Windows 10, React@latest, Chrome@latest, Mozilla@latest

### Reproduction link
[https://ant.design/components/icon/](https://ant.design/components/icon/)

### Steps to reproduce
1) fresh install React and Antd,
2) take *old* Antd 3.8.0 code with ~50 of <Icon type='' />,
3) see the screenshot below.

### What is expected?
Expected to see blank instead of icons and planned just to add type='outlined' everywhere.

### What is actually happening?
CSS property selector ':before' with content: 'unicode' was added to all those icons. It causes doubling of all icons.

---
Example:
```
.anticon-safety:before {
    content: "\E6EA";
}
```

**Comment by arherzf8er** [comment]
![1e72f807-b59d-4d7f-bbe3-3f187df32bf6](https://user-images.githubusercontent.com/29209372/45597171-65b5e600-b9e1-11e8-8098-7b8b34dc643a.png)

**Comment by arherzf8er** [comment]
Looks like all these redundant before-icons are added by `iconfont.less`. Don't know if I should delete it.

**Comment by afc163** [comment]
Don't import two copies of antd's styles.

**Comment by Hal-pan** [comment]
If our version is 3.3.0, but the three parties rely on the library version to be 3.9.2, Icons are doubled after build

**Comment by aclowwwn** [comment]
Same here on the 3.9.2. Any help, please?

**Comment by AvidSid** [comment]
Downgrade your ANTD using:

npm install antd@3.8.1

And then restart the server using "npm start"

Should work :)

**Comment by aca-390** [comment]
> is there a good solution for this?

See afc163's somewhat short response above. It seems to be caused by importing more than one instance of antd, either side of 3.9.0. The way icons get rendered was changed around then, so it seems that when you have multiple versions it renders icons multiple ways.

Check whether you're using it in a dependency or something else, and see whether the version used there is different to your primary one.

**Comment by lisandropat** [comment]
I'm using antd 3.9.3 and only importing css one time. Is there any other solution?

**Comment by jasonHzq** [comment]
We both use ng-zorro-mobile and antd in some page. The icon solution in ng-zorro-mobile and antd is different now, how can we solve the problem elegantly

**Comment by DamianoPapi** [comment]
you need to update the css file to the last version, this fix it
