### ISSUE TITLE
Responsive support of the component <Col /> ?

### ISSUE THREAD

**Issue by czn574775237** [ant-design/ant-design#1226]
```
<Row>
  <Col span="6"></Col>
  <Col span="18"></Col> 
</Row>
```
When I use the Col , I was confused to solve the problem of supporting mobile.Just like the .col-* of bootstrap, it can be very nice to mobile browser.

So I assume the code like that
```
<Row>
  <Col md-span="6" sm-span="12" xs-span="24"></Col>
  <Col md-span="18" sm-span="12" xs-span="0"></Col>
</Row>
```

Thanks.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/978

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/1082
