### ISSUE TITLE
The tree control should be checked with the highest priority of the checkedkeys rather than the default check of child nodes

### ISSUE THREAD

**Issue by GevilEsen** [ant-design/ant-design#12267]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The 'tree' control should check the child node with the highest priority of 'checkedkeys' instead of the parent. If strict mode is used, the user will not check the child nodes by default, which will bring a bad experience, if the operation is To modify the 'check' mode, the strict mode from 'false' to 'true', when the user operates, will lead to the full selection of the child nodes that are not fully selected, of course, the back-end only check the child nodes will be useless operating

### What does the proposed API look like?
The tree control should be checked with the highest priority of the checkedkeys rather than the default check of child nodes

**Comment by zombieJ** [comment]
Sorry for I can't get your point. What do you mean of highest priority?
