### ISSUE TITLE
Select with dropdownMatchSelectWidth

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#12260]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Chrome 69.0.3497.81

### Reproduction link
[https://codepen.io/gonenoob/pen/PdeXvV](https://codepen.io/gonenoob/pen/PdeXvV)

### Steps to reproduce
Setting the dropdownMatchSelectWidth property of Select

### What is expected?
The minimum width of Option should be equal to the width of Select.

### What is actually happening?
The width of Option is adaptive content.

**Comment by chenyang-biu** [comment]
@gonenoob The dropdownMatchSelectWidth with false, that means the options width not  need to match select width

**Comment by gonenoob** [comment]
@cheapsteak You are right.
But even better, the width of the option does not equal the width of the selection until there is too much content in the selection.That's the way it was before version 3.9.

**Comment by zombieJ** [comment]
@afc163 , `rc-select` adjust [width logic](https://github.com/react-component/select/pull/318/files#diff-82c08f1d4a03c73032ab7a87df872285R70) change the behavior.

**Comment by afc163** [comment]
My bad, don't note this will change behavior before.

**Comment by zombieJ** [comment]
@afc163 should revert?

**Comment by afc163** [comment]
Don't revert, it contains other optimize code, I will fix this later.

**Comment by afc163** [comment]
It should affect #12758 too.
