### ISSUE TITLE
SubMenu uses title prop to display menu title which also triggers html title tooltip

### ISSUE THREAD

**Issue by raptoria** [ant-design/ant-design#12277]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Using Chrome on Windows

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/dropdown/demo/sub-menu.md](https://github.com/ant-design/ant-design/blob/master/components/dropdown/demo/sub-menu.md)

### Steps to reproduce
Set the title attribute on sub menu. 
```
    <SubMenu title="sub menu">
      <Menu.Item>3rd menu item</Menu.Item>
      <Menu.Item>4th menu item</Menu.Item>
    </SubMenu>
```

### What is expected?
considering renaming the attribute which displays the SubMenu's name, so the html tooltip doesn't get triggered

### What is actually happening?
HTML tooltip is triggered when hovering over sub menu - this may not be a feature the user wants

---
this is viewable within the demo page (Cascading Menu example)
https://github.com/ant-design/ant-design/blob/master/components/dropdown/demo/sub-menu.md

**Comment by chenshuai2144** [comment]
I am very sorry, but for the time being we have no way to close this.
Do you have time to mention a pr?

**Comment by zombieJ** [comment]
Maybe deprecated the prop of `title` use `label` instead is better. Since MenuItem can also use `title` prop to show the html title tooltip.

**Comment by raptoria** [comment]
It seems the way to specify the title for rc-menu without seeing the HTML title attribute at the same time is to wrap the plain text in a span, so instead of
 <SubMenu title="sub menu">

do this: 

 <SubMenu title={<span>sub menu</span>}>

I think I can live with that.
