### ISSUE TITLE
Combine Ant Design and Ant Design Mobile

### ISSUE THREAD

**Issue by danielreichhart** [ant-design/ant-design#12274]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

There are components that are predestined for only one environment. For example, the [NavBar](https://mobile.ant.design/components/nav-bar/) from Ant Design Mobile is barley used on a desktop website. As well the other way round.

Nevertheless, I think it make sense to combine the packages Ant Design and Ant Design Mobile.

Because some components have a duplicate implementation in both packages, like the carousel component. So as a web developer I want to create a responsive website and not to have the same component for [desktop](https://ant.design/components/carousel/) and [mobile](https://mobile.ant.design/components/carousel/).

A more meaningful approach is to split by architecture. This step was recently completed by Ant Design Mobile. They now have two packages for [React](https://github.com/ant-design/ant-design-mobile/) and [React Native](https://github.com/ant-design/ant-design-mobile-rn/).

Also, the effort for the maintenance would be less. For the developer as well as for the use: The developers don’t have to keep two websites and repositories up to date. And for example, the user does not have to theme both packages.

Of course, the package size will be increase by this approach, but I think this should handle good code-splitting.

**Comment by zombieJ** [comment]
Thanks for suggestion. We currently don't have the plan for merge then together.
And of course, antd api is forward compatibility. If developer want to keep the package up to date, it can just use antd@3.x for the upgrade.
