### ISSUE TITLE
Tabs component has bug in "Vertical" mode

### ISSUE THREAD

**Issue by josefanostylus** [ant-design/ant-design#12276]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Windows,Chrome 65 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6j2yzvz8r3)

### Steps to reproduce
Import Antd Tabs React component and set it to vertical layout (tabPosition = 'left')

### What is expected?
Tabs bar indicator to position to the side of the tab item 

### What is actually happening?
The tabs bar indicator does not show at all

**Comment by afc163** [comment]
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/507615/45662005-90fc1a80-bb32-11e8-80e2-1055aec437cf.png">

It works pretty well.

**Comment by zombieJ** [comment]
@barrypeng6 , thanks for report. Checking...
