### ISSUE TITLE
Badge "className" and "style" are not applied to the same DOM element

### ISSUE THREAD

**Issue by pierre-b** [ant-design/ant-design#12278]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
macos, firefox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j41608kp4v)

### Steps to reproduce
Check https://codesandbox.io/s/j41608kp4v

### What is expected?
The className and style should be applied to the same element, or the Badge component should expose both the wrapper and count "style" props: "wrapperStyle"   "countStyle"

### What is actually happening?
The className is applied to the wrapper, while the style is applied to the count

**Comment by zombieJ** [comment]
hi @afc163 , do you remember why move `style` into sub element? https://github.com/ant-design/ant-design/commit/8a69058364459b418a92d50d2fed43017dcf8990#diff-3abc5b3cce87e54e1323a47b582f4328R32

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/8a69058364459b418a92d50d2fed43017dcf8990#diff-890f41764e116fcbdb9bea8dcca77340R16

That is why.

**Comment by zombieJ** [comment]
Why not named as `badgeStyle` or `innerStyle`? Since `style` & `className` bind into different element is little strange.
