### ISSUE TITLE
Rows height go out-of-sync on grouped tables head with fixed columns

### ISSUE THREAD

**Issue by AMTourky** [ant-design/ant-design#12273]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
macOS 10.13.6, chrome 69.0.3497.92, react-js 16.3.2

### Reproduction link
[https://codepen.io/anon/pen/bxmRpX](https://codepen.io/anon/pen/bxmRpX)

### Steps to reproduce
Resize the text area under 'company address' column

### What is expected?
all cells height is adjusted to match the new height

### What is actually happening?
cells in fixed column won't change it's height and you start seeing duplicate cells from the fixed columns (the actual columns behind the fixed columns)

---
on the side, why drawing the columns twice in case of fixed columns?

**Comment by khashish** [comment]
Same happens to me, and to add when the browser is resized the heights of the rows are recalculated correctly and the issue is no longer visible

**Comment by zombieJ** [comment]
Since `ResizeObserver` is still in [draft](https://wicg.github.io/ResizeObserver/). Polyfill directly in the table component is expansive.
But you can still use it by your own: https://codesandbox.io/s/v6ll237m9y

I guess we can implement it when finally comes in spec.
