### ISSUE TITLE
InputNumber 能否也支持设置 addonBefore 和 addonAfter？

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#1228]

**Comment by afc163** [comment]
可以考虑，不过最近人力有点紧张。

来个 PR 如何？

**Comment by yesmeck** [comment]
:sweat_smile: 暂时用`<Input type="number" />`代替了，周末找时间看看。

**Comment by afc163** [comment]
我也觉得 `<Input type="number" />` 挺好的，要不是要支持 IE ...

**Comment by zhfish** [comment]
可以考虑放出不支持IE的版本.. 实在没那条件要求所有人的浏览器, 用Webkit打包个APP出来用也比支持IE来的轻松

**Comment by KirySen** [comment]
希望能支持AddonAfter/AddonBefore

**Comment by jljsj33** [comment]
这个哪路大神整下，，这个需求还是有的。。。。

![image](https://user-images.githubusercontent.com/6802825/62035424-5c60f100-b222-11e9-995d-119369987142.png)

**Comment by jljsj33** [comment]
type="number" 丑的一 B。。。

**Comment by hengkx** [comment]
希望能支持AddonAfter/AddonBefore

**Comment by petitspois** [comment]
```js
<div class="ant-input-group-wrapper">
      <div class="ant-input-wrapper ant-input-group">
        <span class="ant-input-group-addon">前缀(CheckBox)</span>
        <InputNumber className="ant-input"  />
        <span class="ant-input-group-addon">后缀</span>
      </div>
</div>
```
支持CheckBox

**Comment by afc163** [comment]
Duplicate of #14284

**Comment by hengkx** [comment]
> ```js
> <div class="ant-input-group-wrapper">
>       <div class="ant-input-wrapper ant-input-group">
>         <span class="ant-input-group-addon">前缀(CheckBox)</span>
>         <InputNumber className="ant-input"  />
>         <span class="ant-input-group-addon">后缀</span>
>       </div>
> </div>
> ```
> 
> 支持CheckBox

尝试过 各种方式 只有上诉 代码 可以实现效果，Input.Group 并不好用 或者 找的方式 不对 @afc163  还是希望可以增加一下

**Comment by yykoypj** [comment]
> ```js
> <div class="ant-input-group-wrapper">
>       <div class="ant-input-wrapper ant-input-group">
>         <span class="ant-input-group-addon">前缀(CheckBox)</span>
>         <InputNumber className="ant-input"  />
>         <span class="ant-input-group-addon">后缀</span>
>       </div>
> </div>
> ```
> 
> 支持CheckBox

要放在Form里面怎么办..  把props往InputNumber里面传，结果显示不出来...

**Comment by zhangnan24** [comment]
> > ```js
> > <div class="ant-input-group-wrapper">
> >       <div class="ant-input-wrapper ant-input-group">
> >         <span class="ant-input-group-addon">前缀(CheckBox)</span>
> >         <InputNumber className="ant-input"  />
> >         <span class="ant-input-group-addon">后缀</span>
> >       </div>
> > </div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 支持CheckBox
> 
> 要放在Form里面怎么办.. 把props往InputNumber里面传，结果显示不出来...

改成这样即可：
```
const MyFormItem = (props: { value?: number; onChange?: (val: number) => void }) => {
  return (
    <div class="ant-input-group-wrapper">
      <div class="ant-input-wrapper ant-input-group">
        <span class="ant-input-group-addon">前缀(CheckBox)</span>
        <InputNumber className="ant-input" value={ props.value }  onChange={ val => props.onChange?.(val) }  />
        <span class="ant-input-group-addon">后缀</span>
      </div>
   </div>
  )
}
```

**Comment by zhangnan24** [comment]
有东西的啊
