### ISSUE TITLE
[suggest]  Drawer add conform loading

### ISSUE THREAD

**Issue by ruoru** [ant-design/ant-design#12288]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
none

### Reproduction link
[https://github.com/antd/antd](https://github.com/antd/antd)

### Steps to reproduce
none

### What is expected?
like modal conform loading api

### What is actually happening?
like modal conform loading api

**Comment by zombieJ** [comment]
Drawer is different with Modal. It's just a flash popup region, you can customize the content what you want: https://codesandbox.io/s/ym93k5701
