### ISSUE TITLE
Icon for Woman is unorthodox

### ISSUE THREAD

**Issue by tb2johm** [ant-design/ant-design#12296]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
all

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1zqy47qn7j)

### Steps to reproduce
Create Icon

### What is expected?
Usually a women icon looks something like this:  (with the plus sign straight down)
https://www.shutterstock.com/image-vector/women-sign-icon-1031740363

### What is actually happening?
Now it's kind of mixed with the sign for man. As far as I know this has no "official" meaning, but it might actually be interpreted as transsexual or transgender.
The priority of this issue is rather low I'd say. Just wanted to make you aware of it.

**Comment by tb2johm** [comment]
This might also be a cultural thing? at least for US and Europe what I wrote is true.

**Comment by yesmeck** [comment]
Talked to our designer, we will update the icon.
