### ISSUE TITLE
Upload组件服务器端渲染和客户端渲染存在差异性警告

### ISSUE THREAD

**Issue by shawon1220** [ant-design/ant-design#1229]
**问题描述**

Upload组件服务器端渲染和客户端渲染存在差异性警告。如下：

Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:

(client) tgcg.1.0.0.0"><span role="button" tabind
 (server) tgcg.1.0.0.0"><span style="position:rela

**发生环境**

- antd 版本：最新版本
- 操作系统及版本：win8
- 浏览器及版本：chrome
- 在线演示地址：http://ant.design/components/upload/

**Comment by afc163** [comment]
ref #215

**Comment by shepherdwind** [comment]
https://github.com/react-component/upload 服务端渲染，需要配置 forceAjax 的。

**Comment by shawon1220** [comment]
@shepherdwind ，确实可以了，谢谢。
