### ISSUE TITLE
table 如何在外部控制 select 选中问题

### ISSUE THREAD

**Issue by meixiaohei** [ant-design/ant-design#12291]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有这么一个需求  当我点击外部的一个按钮  或者  切换页面时  清空选中项不让他选中

### What does the proposed API look like?
table  中的多选可在外部控制   譬如  点击按钮  去控制多选选中项

**Comment by AChaoZJU** [comment]
I have the same issue.
