### ISSUE TITLE
官网的 模式-导航 里对侧边导航、顶部导航的“总结”似乎搞反了

### ISSUE THREAD

**Issue by spirohe** [ant-design/ant-design#1230]
> 侧边导航 ：一般适用在浏览性强、门户性质的网站，以及一些比较前台化的应用。顶部导航：适用在操作性强、中后台管理性质的应用。

这个确定没有写反么？各大新闻、门户、购物等前台化的应用几乎都是顶部导航为主，而各类单页面的后台应用（如云计算公司的控制台、外卖商家的后台）大多以侧边为主。

个人拙见。

**Comment by afc163** [comment]
确认确实反了，已更新，感谢您的细心 :100:
