### ISSUE TITLE
Upload listType is text, remove  file icon style error

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#12304]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrome latest

### Reproduction link
[https://ant.design/components/upload/](https://ant.design/components/upload/)

### Steps to reproduce
official website

### What is expected?
vertical center

### What is actually happening?
![image](https://user-images.githubusercontent.com/8358236/45727339-dfbeb880-bbf5-11e8-9336-dc58a8a39742.png)

**Comment by HeskeyBaozi** [comment]
https://github.com/ant-design/ant-design/pull/12330
