### ISSUE TITLE
table 响应式隐藏列

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#12301]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可选列可以在大屏幕显示，小屏幕隐藏。固定列滚动条不好看

### What does the proposed API look like?
设置列的className，基于bootstrap响应式设计
https://getbootstrap.com/docs/3.3/css/#responsive-utilities

![image](https://user-images.githubusercontent.com/2288630/45719735-197ec780-bbd4-11e8-84b7-2e24cbaadbd1.png)

**Comment by zombieJ** [comment]
感觉对于 table 不是必须的，是否可以考虑自己写一些 css 来解决？

**Comment by yesmeck** [comment]
建议自己实现。
