### ISSUE TITLE
Modal组件的afterClose在React 16后已经无效，希望移除或者更新文档

### ISSUE THREAD

**Issue by alexxyzeng** [ant-design/ant-design#12302]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我去看了rc-dialog的代码，其中关于afterClose部分已经做了修改，只局限于React 16之前的版本使用。希望Ant Design能够更新文档或者考虑移除这个api.

### What does the proposed API look like?
修改Ant Design中Modal组件中afterClose部分的文档或者移除该api，避免误用。

**Comment by afc163** [comment]
我们应该先尝试修复。

**Comment by zombieJ** [comment]
能给个重现吗？我这边看是好的：https://codesandbox.io/s/lxv03060yz

**Comment by alexxyzeng** [comment]
经检查是我们自己的代码有误，很抱歉打扰了。
