### ISSUE TITLE
add step title and step destiption at left in vertical

### ISSUE THREAD

**Issue by justLearner** [ant-design/ant-design#12303]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当我需要在垂直的步进条的左边添加一些内容的时候，发现没有接口。

### What does the proposed API look like?
希望 title 和 description 可以再垂直的step左右都能设置

**Comment by afc163** [comment]
暂不支持，可以试试 Timeline。

**Comment by justLearner** [comment]
![step](https://user-images.githubusercontent.com/22292102/45736355-3f7c8a00-bc1d-11e8-8b8c-dc114cdd74b7.jpg)

**Comment by justLearner** [comment]
类似这样的效果的，timeline也是实现不了的吧

**Comment by afc163** [comment]
对，都不支持，应该也不会支持。建议设计师按 Ant Design 规范进行设计。
