### ISSUE TITLE
A space character insert into the middle of two Chinese character of Button Component

### ISSUE THREAD

**Issue by XGHeaven** [ant-design/ant-design#12314]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lyy2yw3k1z)

### Steps to reproduce
If button text is two Chinese character, one space character inserted. This is not what I expected. How to disable this behavior?

### What is expected?
No space character inserted.

### What is actually happening?
A space character inserted.

**Comment by afc163** [comment]
It is by designed.
