### ISSUE TITLE
Textarea with maxLength

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#12318]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Chrome 69.0.3497.81

### Reproduction link
[https://codepen.io/gonenoob/pen/vzvEvY](https://codepen.io/gonenoob/pen/vzvEvY)

### Steps to reproduce
Copy the contents in the Table and paste them into TextArea. The maxLength attribute of TextArea does not play a correct role.I limit the maximum length to 28, but the content length can be up to 29.

### What is expected?
MaxLength of TextArea works correctly.

### What is actually happening?
The maxLength attribute of TextArea does not play a correct role.

**Comment by zombieJ** [comment]
Nice catch!

**Comment by zombieJ** [comment]
Looks like a chrome bug: https://jsfiddle.net/o4rjL7wu/4/

**Comment by zombieJ** [comment]
Test in some browser. Both chrome & safari has this issue.

**Comment by gonenoob** [comment]
ths for help

**Comment by natanielcz** [comment]
Doubt that this is still an issue. Tried to reproduce on:
- Firefox 62
- Chrome 69
- Brave 0.25

**Comment by ztplz** [comment]
@gonenoob @zombieJ @natanielcz 
[maxlenth](https://caniuse.com/#feat=maxlength)
![image](https://user-images.githubusercontent.com/17755202/48989909-4b2d8500-f167-11e8-931b-69f3a605eead.png)
If you type in English it will always work fine, but if it is a character in another language, it will not be counted in the limit number. 
If I want to limit Chinese character number. Set `lang` to `zh-cn`, it works fine.
![image](https://user-images.githubusercontent.com/17755202/48990864-3bb03b00-f16b-11e8-9529-7de7599753f3.png)
Then I found that I could no longer reproduce the bug, even if I changed it back to `en`!!!!!

**Comment by ztplz** [comment]
@zombieJ I also copied it to `textarea` at the beginning, but it works fine now.

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/48991819-abc0c000-f16f-11e8-9aff-3a1f650192ef.png)
chrome 70

**Comment by zombieJ** [comment]
@ztplz ,
Try double click the `copythis` text and then paste.

**Comment by ztplz** [comment]
@zombieJ  https://bugs.webkit.org/show_bug.cgi?id=182725

**Comment by zombieJ** [comment]
Close since it's not antd bug.
