### ISSUE TITLE
Problem using multiple Select with onBlur validation

### ISSUE THREAD

**Issue by blade254353074** [ant-design/ant-design#1231]
I write a multiple Select with Validation:

```javascript
...
const multiSelectProps = getFieldProps('groups', {
  validate: [{
    rules: [{
      required: true,
      message: '请选择员工所属用户组',
      type: 'array'
    }],
    trigger: 'onBlur'
  }]
})
...
<Select
  {...multiSelectProps}
  multiple
  placeholder="请选择所属用户组，可以输入文字搜索"
  notFoundContent="没有找到，请试试中文"
  optionFilterProp="children"
>
  {selectList}
</Select>
...
```

When I focus on Select and then blur off, the Select dropdown menu can't closed, and console report an error:

Animate.js:296 Uncaught Error: must set key for <rc-animate> children
![image](https://cloud.githubusercontent.com/assets/9346008/13897355/eb62e080-ede9-11e5-8eb6-e83b4030fa21.png)

## Environment Information

- The version of antd: ^0.12.10
- Your operating system and it's version: OS X 10.11.3
- Your browser and it's version: Chrome 49.0.2623.87 (64-bit)

**Comment by afc163** [comment]
selectList 的内容是？

最好有 codepen 。

**Comment by blade254353074** [comment]
```javascript
const selectList = config.groups.map((item, index) => {
  return <Option value={item.id} key={index}>{item.name}</Option>
})
```

**Comment by afc163** [comment]
Codepen: codepen.io/anon/pen/reyWGL?editors=001

原因是 https://github.com/react-component/select/blob/5.10.2/src/Select.jsx#L486 这里 value 为 `[""]`。

selectedValueNodes 里会生成一个 key 为 `""` 的，导致 rc-animate 报错。

@yiminghe

**Comment by yiminghe** [comment]
Select 不支持 onBlur 验证
