### ISSUE TITLE
anchor in tabs demo

### ISSUE THREAD

**Issue by Vosang** [ant-design/ant-design#12312]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Is there a anchor in tabs demo? thx

### What does the proposed API look like?
Is there a anchor in tabs demo? thx

**Comment by relaxxpls** [comment]
I was facing this issue recently, does a demo exist?
If not how to I use the Anchor component to highlight a particular tab?
