### ISSUE TITLE
Icon.createFromIconfontCN方法会强制添加https:

### ISSUE THREAD

**Issue by shaokr** [ant-design/ant-design#12316]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Steps to reproduce
import { Icon } from 'antd';
let scriptUrl = `./icon/iconfont.js`;
if (__DEV__) {
  scriptUrl = '//at.alicdn.com/t/font_810467_0vb7rjfqkwzk.js';
}
export default Icon.createFromIconfontCN({
  scriptUrl
});

### What is expected?
可根据传入的scriptUrl判断自适应http或者https,
这样就可使用下载到本地或者其他cnd中无https服务的 iconfont.cn 项目

### What is actually happening?
不管scriptUrl的值传什么都会添加https:

**Comment by jiechud** [comment]
I want to solve this problem
