### ISSUE TITLE
SubMenu style can't independent control

### ISSUE THREAD

**Issue by qingzi-king** [ant-design/ant-design#12319]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
mac10.12.6/ chrome 68.0.3440.106/ant-design 3.9.2

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
1、Menu在horizontal方式时，子菜单展开容易被其他的元素挡住，不能直接在style中设置zIndex控制（因为全局submenu渲染时的外面套了两层div）
2、当子菜单展开时超过页面宽度，不会自适应移动位置，而是强制撑宽页面

### What is expected?
水平布局menu展开子菜单，可直接改变submenu样式

### What is actually happening?
1、Menu在horizontal方式时，子菜单展开容易被其他的元素挡住，不能直接在style中设置zIndex控制（因为全局submenu渲染时的外面套了两层div）
2、当子菜单展开时超过页面宽度，不会自适应移动位置，而是强制撑宽页面

---
使用过程中v3.7.2 并不会出现上面问题

**Comment by picodoth** [comment]
@qingzi-king 给个gif?
