### ISSUE TITLE
antd DatePicker二次封装

### ISSUE THREAD

**Issue by llsldwy** [ant-design/ant-design#12328]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
您好，现在公司产品有个需要，需要在DatePicker 的基础上进行按照日周月的快捷切换（如下图、图片仅供参考），我查看了一下antd的DatePicker没有这个功能。所以我想咨询一下各位大神，1.是在先用antd的框架下进行二次封装（有没有可参考的例子） 2.基于rc-calendar 进行二次封装（因为我查看DatePicker的底层应该是调用rc-calendar     

### What does the proposed API look like?
我想咨询一下各位大神，1.是在先用antd的框架下进行二次封装（有没有可参考的例子） 2.基于rc-calendar 进行二次封装（因为我查看DatePicker的底层应该是调用rc-calendar
 
![image](https://user-images.githubusercontent.com/6800117/45794329-b327a100-bcc8-11e8-915b-c1bd5f5879ff.png)

**Comment by zhipengsong** [comment]
@llsldwy 请问二次封装的功能实现了吗？是否可以给个参考？
