### ISSUE TITLE
请求添加一些功能。

### ISSUE THREAD

**Issue by zhump** [ant-design/ant-design#1232]
1.希望可以添加拖动/排序组件。
2.表格之后能支持多级表头吗？
3.treeGrid的节点能否支持异步加载？
4.表格列宽能否支持拖拽调整吗？
5.能否在表格末尾增加汇总行？
6.表格列能否支持拖动？

ps:感觉我提的需求，好些都是与拖动有关。先让我yy下，能找到一个合适强大的表格实在太难了，之前用jqgrid，多表头时会有bug,而且现在也收费了，然后换了好几个表格，都有各种各样的问题，像slickgrid多久没更新了啊，像handsontable现在也有收费版了，功能最最强大的还属easyui的datagrid，我还单独把他从easyui里面拿出来的事都干过。最让我神伤不紧是他收费。更是他的性能，当超过20列时，卡的我嘴角流血。很多优秀的表格组件，20列真不算啥。看到这，肯定有人说我，bbdd的，你怎么不自己做一个表格呢，特么在一个根本不重视前端的公司，根本不给你造轮子的时间，天天赶着要功能，只要结果不看过程，各种特效和组件，全靠百度。哎。一不小心说远了。。还是自己能力不够，加油、、

**Comment by afc163** [comment]
同情你的吐槽，但是这样纯伸手党确实不鼓励。

欢迎给我们 PR ~

5. 现在有 footer 参数。

其他项，目前暂不支持或不在组件的职责范畴，感谢反馈。
