### ISSUE TITLE
upload点击上传文件后 ，怎么能在文件选择框弹出之前拦截

### ISSUE THREAD

**Issue by jYh1014** [ant-design/ant-design#12325]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
浏览器版本 chrome  65.0.3325.181

### Reproduction link
[https://codepen.io/anon/pen/gdZVwy?editors=0010](https://codepen.io/anon/pen/gdZVwy?editors=0010)

### Steps to reproduce
点击选择文件按钮

### What is expected?
能手动控制是否弹出文件选择框

### What is actually happening?
并不能阻止弹出文件选择框

**Comment by afc163** [comment]
If you are tring to request feature, please use feature-request template in http://new-issue.ant.design/ to create another issue.

**Comment by jYh1014** [comment]
https://codesandbox.io/s/m77z0rxrvy
