### ISSUE TITLE
Progress type line not showing

### ISSUE THREAD

**Issue by aclowwwn** [ant-design/ant-design#12322]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Linux Mint, Google Chrome 65.0.3325.181 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l7v9nj55q7)

### Steps to reproduce
Just tried to use the basic progree example from the docs.
https://ant.design/components/progress/

### What is expected?
A liniar progress.

### What is actually happening?
Only the percentage shows

**Comment by zombieJ** [comment]
https://codesandbox.io/s/7y418vv8px

**Comment by aclowwwn** [comment]
Hello @zombieJ , thank you for the quick answer. I might not see it right, but I think this is not an usage issue. The circular progress renders well (although it has an issue), the linear doesn't. Anyway, thank you for the awesome work you guys do.
