### ISSUE TITLE
Duplicate Icon

### ISSUE THREAD

**Issue by dasouch** [ant-design/ant-design#12326]
When creating a `<Icon type='picture' style={{ fontSize: 30 }}  theme='outlined' />` the icon is doubled

![screen shot 2018-09-19 at 9 23 55 pm](https://user-images.githubusercontent.com/1742818/45792283-bd0ebd00-bc52-11e8-9483-24319b574a77.png)

![screen shot 2018-09-19 at 9 27 40 pm](https://user-images.githubusercontent.com/1742818/45792308-dfa0d600-bc52-11e8-9e12-bfef08ee2a01.png)

**Comment by serranoarevalo** [comment]
@dasouch How did you fix this?
