### ISSUE TITLE
Seems Menu does not support usages with React context API

### ISSUE THREAD

**Issue by EnixCoda** [ant-design/ant-design#12331]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
macOS, Chrome. Both latest version.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z65p82m76x)

### Steps to reproduce
Check the repro link.

### What is expected?
No error when hover.
Render menu item normally.

### What is actually happening?
Error was thrown if hover the menu item.
Style broken.

**Comment by EnixCoda** [comment]
BTW, it will be better if the link to the minimal repro CodeSandbox in issue drafting page could open in a new tab instead of redirecting.

**Comment by jiechud** [comment]
@afc163  Is there any plan to fix this? I want to solve.

**Comment by afc163** [comment]
seems that it is same problem as https://github.com/ant-design/ant-design/issues/4853
