### ISSUE TITLE
Table columns 过长时候，title 错位

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#12333]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
chorme 版本 69.0.3497.92（正式版本） （64 位）

### Reproduction link
[https://codepen.io/bzonegogogo/pen/eLxBmM?editors=0011](https://codepen.io/bzonegogogo/pen/eLxBmM?editors=0011)

### Steps to reproduce
打开链接，向右滑动

### What is expected?
交易ID那一列正常出现

### What is actually happening?
被覆盖了

---
首列设置了 fixed

**Comment by zombieJ** [comment]
https://codepen.io/anon/pen/gdqXoe?editors=0010

Column 里如果全部设置 width 在固定宽度下它们会按照 width 的百分比分配。scroll x 的空间不足就缩小了。
