### ISSUE TITLE
<Option> 的 key 参数无效

### ISSUE THREAD

**Issue by jas0ncn** [ant-design/ant-design#12334]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
macOS 10.13.4, Chrome 69

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/qz7o9wkm04)

### Steps to reproduce
antd 会将 `<Option>` 的 `value` 当成 `key` 来传递给 React，但是[文档](https://ant.design/components/select-cn/#Option-props)中指明了可以自定义 `key` 的。根据重现链接中的使用方式，当 `value` 一致时，我传入自定义的 `key` 却没有任何效果，还是使用 `value` 当做了 `key`，这会导致选中的时候错误。

**请注意，这和已有的 https://github.com/ant-design/ant-design/issues/11909 这个 issue 并不完全一样，重现链接的代码中的 `value` 和 <Option> 展示的值是不同的**

### What is expected?
当有自定义 `key` 的时候，不应该使用 `value` 作为 `key`，这也是文档所展示的

### What is actually happening?
不管提供没提供 `key`，都会把 `value` 当做了 `key`

**Comment by jas0ncn** [comment]
我理解 antd 的逻辑是如果没有传 `value`，会将 `key` 当 `value`，但是如果都传的时候，`key` 却没有生效，这个问题感觉很奇怪。

**Comment by zombieJ** [comment]
ref: https://github.com/react-component/select/blob/master/src/Select.jsx#L1060

**Comment by afc163** [comment]
印象中原来的逻辑是：

1. 只有 key，就用 key。
2. 只有 value，就用 value。
3. 两者都有，用 value。

你可能希望 key 不一样，value 有重复，这种情况是不允许和不支持的，必须没有重复项。

**Comment by jas0ncn** [comment]
是的，逻辑是这样的，但是 `key` 的语义应该保证和 React 本身是一样的吧。。不应该保证 `value` 是唯一，`key` 才应该是唯一的呀

**Comment by jas0ncn** [comment]
或者说，取值应该取 `value`，但是判定唯一应该是 `key`，这样才是符合语义化的。

**Comment by afc163** [comment]
key 和 value 都需要唯一。

**Comment by jas0ncn** [comment]
那如果 `value` 和 `key` 都提供了，能否别将 `value` 别设置到 `key` 上呢？目前报错的是来自 React 的 `key` 重复了。https://github.com/react-component/select/blob/master/src/Select.jsx#L1060
由业务自己保证唯一呢？

**Comment by afc163** [comment]
看了下你的例子。

1. value 不应该重复，会导致 select 无法判断选中项。
2. Option 上的 key 是用于解决 map 后 Option 组件的 array 警告，和 MenuItem 的 key 警告本质上不是一回事。
3. 目前的警告确实来自于我们将 value 用作 MenuItem 的 key，由于 React 的实现机制，目前没有优雅的办法去传递 Option 的 key 给 MenuItem。但是 value 我们预期是唯一的，所以重复的 value 除了这个警告以外，也会带来 1 的问题，所以目前这个组件行为应该是符合预期的。

**Comment by jas0ncn** [comment]
嗯，是的，发现 `select` 无法判断选中项了，这种场景我还是特殊处理一下吧。辛苦了！感谢这么晚还在解答！

**Comment by yoyo837** [comment]
> 是的，逻辑是这样的，但是 `key` 的语义应该保证和 React 本身是一样的吧。。不应该保证 `value` 是唯一，`key` 才应该是唯一的呀

有一定道理，但是antd里onChange不好处理吧，倒不如自己特殊处理一下value使其不唯一来使用来的快。比如你的值`[1, 2, 2, 3]` 换成`['1-1', '1-2', '2-2', '3']`类似这种。
