### ISSUE TITLE
how to add  some tip message on table checkbox by rowSelection

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#12332]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

![bb](https://user-images.githubusercontent.com/29558970/45809347-88eed700-bcfa-11e8-87bf-23194e74c5f6.png)

I want give some tip message on table checkbox to tell people why this checkbox is disabled when mouse hover

### What does the proposed API look like?
```js
const rowSelection = {
    // set tip message,  like getCheckboxProps
    getTooltipProps:(record)=>{
         // tooltip props
    }
}
```

**Comment by zombieJ** [comment]
It's not a common requirement. You can customize the column by your own:https://codesandbox.io/s/1q2x7jx9nj
