### ISSUE TITLE
AutoComplete组件bug

### ISSUE THREAD

**Issue by winter-ice** [ant-design/ant-design#12337]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
无

### Reproduction link
[https://ant.design/components/auto-complete-cn/](https://ant.design/components/auto-complete-cn/)

### Steps to reproduce
查询模式 - 不确定类目

输入框输入字数很多的时候

### What is expected?
正常显示

### What is actually happening?
输入框输入字数过多会和后面的提示文字重叠

**Comment by zombieJ** [comment]
官方样例只是个示例，具体的 css 是可以自己写的：https://codesandbox.io/s/w680nlyj05
