### ISSUE TITLE
js执行报错Uncaught TypeError: n.load is not a function

### ISSUE THREAD

**Issue by dongjiang123** [ant-design/ant-design#12346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.0.0

### Environment
"react":16.0.0, "chrome":69.0.3497.100，"ant-design-pro": "^1.0.1",

### Reproduction link
[https://gw.alipayobjects.com/as/g/wb-zhz352862/The-ant-institutional-center/0.2.9/index.html#/](https://gw.alipayobjects.com/as/g/wb-zhz352862/The-ant-institutional-center/0.2.9/index.html#/)

### Steps to reproduce
直接打开链接，就会出现js错误：
TypeError: n.load is not a function

### What is expected?
页面正常渲染出来

### What is actually happening?
业务无法展现

---
蚂蚁机构门口开放场景，做机构入驻业务,
蜻蜓构建地址：
https://rmsportal.alipay.com/jobs#/29571

**Comment by afc163** [comment]
It is not antd issue.
