### ISSUE TITLE
Provides a way to modify the default values of component properties

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#12345]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There's no way to change the default values of component properties, so I have to rewrite them many times in my project. Can you provide a global method for modifying the default values of component properties?

### What does the proposed API look like?
Maybe a JS or JSON file

**Comment by afc163** [comment]
Nope, we won't support global config for default values of all components.
