### ISSUE TITLE
表单验证不行啊....

### ISSUE THREAD

**Issue by silverPanda** [ant-design/ant-design#1234]
我用了新的表单验证为什么感觉像是实现了一半啊？？？
![image](https://cloud.githubusercontent.com/assets/2177207/13902839/ccadb198-ee97-11e5-8b35-580ff8980237.png)
onBlur根本就不触法验证，提交只有console.log的效果，组件中的input根本不标红，和现实错误信息，
你们最新的代码是不是没上传到npm上啊？在线等，急

**Comment by afc163** [comment]
仔细检查下你漏了什么代码。

http://ant.design/components/form/#demo-validate-basic

npm 上的是最新的。

**Comment by silverPanda** [comment]
Input 的 defaultValue  也被清掉了。。。

**Comment by benjycui** [comment]
@silverPanda 建议再认真看下文档 http://ant.design/components/form/#this-props-form-getfieldprops-id-options

**Comment by afc163** [comment]
我猜是 createForm 漏掉了。

**Comment by silverPanda** [comment]
木有漏 createForm。我明天不用Es6 写试试

**Comment by silverPanda** [comment]
@benjycui 使用这个initialValue 这个参数就可以了， 但是为什么要把react官方推荐 Input 的defaultValue直接无视，感觉不太科学。。

**Comment by imsobear** [comment]
@silverPanda +1, 为什么不直接使用 defaultValue? antd 里有些特殊化处理非常奇怪，让人不得不去看 demo 里的代码是怎么写的，很头疼。

**Comment by afc163** [comment]
Form 使用了 React 业界推荐的 controlled components 的数据流写法，封装了 value 和 onChange。

http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by benjycui** [comment]
现在的方案是不可能用 `defaultValue` 的，除非像之前 `Validation` 那样。

**Comment by silverPanda** [comment]
@afc163 我知道我的代码和Demo最大的区别是啥了。。。我把提交的Button扔到另一个FormItem中就正常了，这个提交表单的Button一定要当在一个单独的 FormItem 中么？ 好诡异....
![image](https://cloud.githubusercontent.com/assets/2177207/13913326/a34c4ca8-ef80-11e5-9431-df9c1d86920a.png)

**Comment by afc163** [comment]
我试了下，不存在这个问题。放在 `FormItem` 外面也能触发。

**Comment by silverPanda** [comment]
![image](https://cloud.githubusercontent.com/assets/2177207/13938996/b0e5383a-f00b-11e5-8a22-f7bacea8be9b.png)
这样是真的不行。。。。另起一个FormItem就可以了

**Comment by silverPanda** [comment]
谢谢 @afc163 @benjycui  的关注

**Comment by benjycui** [comment]
@silverPanda https://github.com/ant-design/ant-design/issues/610#issuecomment-171918270

**Comment by benjycui** [comment]
更新了下文档 https://github.com/ant-design/ant-design/commit/3611c798c108659883ff00979307e0eaf7cc6f37

**Comment by silverPanda** [comment]
@benjycui 明白了，原来是这个原因，谢谢

**Comment by codering** [comment]
![image](https://cloud.githubusercontent.com/assets/2271825/13948929/bbf707f6-f05d-11e5-9ebd-0d2dd5ef6318.png)
![image](https://cloud.githubusercontent.com/assets/2271825/13948947/cfd9e400-f05d-11e5-9e6a-8582468a8821.png)

顺路问下, ``` const nameProps = getFieldProps('name'  ... ```  这个定义的时候，只能写"name", 我如果改成其他名称如 "realName" ， 它就校验不通过，但是页面呈现是通过的。
![image](https://cloud.githubusercontent.com/assets/2271825/13949114/7de6c9be-f05e-11e5-9ca9-ca04a760cc87.png)
