### ISSUE TITLE
v0.12.12，table的pageSize问题

### ISSUE THREAD

**Issue by wormcc** [ant-design/ant-design#1235]
v0.12.12中，`pageSize`改变已经会触发table的`onChange`事件，但是在`onChange`方法中通过`this.state.pageSize`获取到的`pageSize`仍然是改变前的，需要在`onChange`方法里手动`setState`？
## Environment Information

- The version of antd(0.12.12):
- Your operating system and it's version(OSX 10.11.0):
- Your browser and it's version( Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
给 codepen 。

> `在onChange方法中通过this.state.pageSize获取到的pageSize`

这句话不是很理解。
