### ISSUE TITLE
Component `DatePicker` showTime.defaultValue need to be 0 o'clock on the day when not to show time

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#12358]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Most time, I expect the date I choose to be 0 o'clock on the day, when i use `DatePicker` or `RangePicker` without showTime.
But now the default time is the current time. 
This is a counter-intuitive behavior.
This can easily lead to problems that are not easy to find, although I can handle this problem with `shotTime.defaultValue`.

### What does the proposed API look like?
i expect `DatePicker` showTime.defaultValue to be 0 o'clock on the day when i do not pick time

**Comment by xyy94813** [comment]
now, i find i can not use `shotTime.defaultValue` to resolve this problem.
when i use `shotTime.defaultValue`, the pick time button will show.

so i need transform all values returned by `DatePicker` or `RangePicker`.
it is too terrible

**Comment by zombieJ** [comment]
Just wrap it: https://codesandbox.io/s/04zq83nlnv

**Comment by xyy94813** [comment]
@zombieJ This is useless. 
If I execute the following steps：
1. click `today`
2. re-pick another day

now i wrapper by [this way](https://codesandbox.io/s/p783rwm3kx)

but i think this is best a default behavior.

**Comment by AENeuro** [comment]
I would agree, this is counterintuitive. The time should be set as the same when the user is not inputting a value. You are introducing uncertainty to the system (same input would produce different results).
Yes, it is easy to just wrap it. But consider the time that everyone encountering this problem will have to spend on figuring out that the time value is actually **different** (counterintuitive point), and then refactoring the code. Or if you are using it in a form and you'll actually have to transform it in a decorator.
