### ISSUE TITLE
const form = this.formRef.props.form;  undefined

### ISSUE THREAD

**Issue by gametheworld** [ant-design/ant-design#12352]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.2

### Environment
react

### Reproduction link
[https://codepen.io/anon/pen/jvJrzX?editors=0010](https://codepen.io/anon/pen/jvJrzX?editors=0010)

### Steps to reproduce
我在父组件中，打印当前的this为 undefined

### What is expected?
-

### What is actually happening?
-

**Comment by yesmeck** [comment]
没看到有 undefined

**Comment by ycjcl868** [comment]
this 不是 undefined.

![image](https://user-images.githubusercontent.com/13595509/45947941-a7214380-c028-11e8-8ed7-e16107fd6db8.png)
