### ISSUE TITLE
Collapse组件在 ie10 及以下报错：  无法获取未定义或 null 引用的属性“activeKey” 

### ISSUE THREAD

**Issue by pkl93** [ant-design/ant-design#12355]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
win7 ie10

### Reproduction link
[https://ant.design/components/collapse-cn/](https://ant.design/components/collapse-cn/)

### Steps to reproduce
用ie10 或 ie11的ie10文档模式 进入官网Collapse组件页面

### What is expected?
页面正常显示

### What is actually happening?
Collapse组件报错： 无法获取未定义或 null 引用的属性“activeKey”

---
官网首页在 ie10 及 以下也会报类似错误显示空白：  对象不支持“addScrollEvent”属性或方法

**Comment by zombieJ** [comment]
官方没有对旧版本 IE 做 polyfill，Collapse 报错能给个重现吗？

**Comment by pkl93** [comment]
后面我试了两种情况， 一个是用create-react-app创建的， 一个是用的umi， 发现只有umi的那个Collapse组件会报错（加了同样的polyfill）。   因为试过了一些其他的antd组件都没问题， 也没报es6语法的错误， 实在找不出是什么问题导致的。
在线的示例用 ie 打不开， 我只能放github上了。
https://github.com/pkl93/umi-antd-test 这个会报错 （umi）
https://github.com/pkl93/antd-test 这个不会 （create-react-app）
前端菜鸟， 能力不足请谅解。

**Comment by pkl93** [comment]
试过了umi@2.1.0-beta.1 ， 任然报同样的错误， 已下是项目实际的配置， 不知道配置有没有问题。

package.json(部分配置) :    -----------------------------------------
{
  "scripts": {
    "dev": "cross-env PORT=9090 ./node_modules/.bin/umi dev",
  },
  "devDependencies": {
    "umi": "2.1.0-beta.1"
  },
}

.umirc.js :     ----------------------------------------------------------

const path = require('path');
export default {
  history: 'hash',
  extraBabelPlugins: [
    ...(process.env.COVERAGE ? ['babel-plugin-istanbul'] : [])
  ],
  alias: {
    'components': path.resolve(__dirname, 'src/components'),
    'pages': path.resolve(__dirname, 'src/pages'),
    'assets': path.resolve(__dirname, 'src/assets'),
    'utils': path.resolve(__dirname, 'src/utils'),
    'config': path.resolve(__dirname, 'src/config'),
    'servers': path.resolve(__dirname, 'src/servers'),
  },
  targets: {
    ie: 10,
  },
  plugins: [
    ['umi-plugin-react', {
      dva: true,
      antd: true,
      routes: {
        exclude: [
          /models\//,
          /model\.(j|t)sx?$/,
          /servers\//,
          /service\.(j|t)sx?$/,
          /utils\//,
          /utils\.(j|t)sx?$/,
          /components\//,
          /others\//,
          /images\//,
        ],
      },
      polyfills: ['ie9','ie10','ie11'],
      locale: {
        default: 'zh-CN', // default zh-CN
        baseNavigator: false, // default true, when it is true, will use navigator.language overwrite default
        antd: true, // use antd, default is true
      },
      library: 'react',
      dynamicImport: {
        webpackChunkName: true,
        loadingComponent: './components/LoadingPage',
        level: 3,
      },
    }],
  ],
  extraBabelPlugins: [
    [
      "import",
      { "libraryName": "components", "libraryDirectory": "", 'camel2DashComponentName': false },
      'components',
    ],
  ],
  theme: "./theme.js",  //ant主题设置
};

一些补充：
试过去掉 polyfills: ['ie9','ie10','ie11'] 这行，  会报<DvaContainer />的错误。
试过在global.js 里手动加 polyfill
import '@babel/polyfill';
import 'raf/polyfill';
也没有用。
之前的项目用 dva 直接在index.js 里加上这两个 polyfill 就可以在ie9以上正常使用所用组件。

**Comment by afc163** [comment]
非 antd 问题，这里先关了，可以去 umi 相关社区讨论。
