### ISSUE TITLE
Tabs允许编辑时，关闭最后一个报错。

### ISSUE THREAD

**Issue by nannongrousong** [ant-design/ant-design#12365]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
win10/chrome 68

### Reproduction link
[https://ant-design.gitee.io/components/tabs-cn/](https://ant-design.gitee.io/components/tabs-cn/)

### Steps to reproduce
有两个个可编辑的tab页，关闭第一个正常，关闭第二个报错。

### What is expected?
可以正确关闭最后一个tab页面。

### What is actually happening?
关闭最后一个tab页报错。

**Comment by afc163** [comment]
It works on my machine.

**Comment by nannongrousong** [comment]
> It works on my machine.

It does not work well at VERSION 3.9.2.
It may have been fixed.
