### ISSUE TITLE
Problem using Drawer component with Layout

### ISSUE THREAD

**Issue by tiagowippel** [ant-design/ant-design#12363]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Latest Chrome or Firefox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1o3l318o1q)

### Steps to reproduce
Just click the open button

### What is expected?
Drawer should open

### What is actually happening?
Drawer is opening, but a vertical scrollbar is appearing too.

![image](https://user-images.githubusercontent.com/12776397/45905166-c8cec080-bdc5-11e8-8bb8-3e9af7ba9b30.png)

---
Apparently on codesandbox it works...

**Comment by jljsj33** [comment]
fix in https://github.com/react-component/drawer/pull/45/files#diff-69642f1c5a5fca3dddfc78c09d0ebb80R248

Please re install dependencies.
