### ISSUE TITLE
Dynamic form item lose value with mapPropsToFields

### ISSUE THREAD

**Issue by ilanus** [ant-design/ant-design#12368]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
Version 69.0.3497.92 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4x2w81jkp)

### Steps to reproduce
Select more then one item in the select, start typing in the dynamic inputs

### What is expected?
The value of the input should remain

### What is actually happening?
The value of the previous input is lost

---
The functionality works as expected without mapPropsToFields
![5slk31sdtx](https://user-images.githubusercontent.com/9677898/45916498-8231a280-be67-11e8-8157-85b80e843887.gif)

**Comment by zombieJ** [comment]
`onFieldsChange` only tell which field update. So you need merge the result if use it: https://codesandbox.io/s/8kk24mjpw9

**Comment by ilanus** [comment]
Thanks for clarification @zombieJ
