### ISSUE TITLE
Lazy image load in docs

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1236]
- https://github.com/loktar00/react-lazy-load
- http://ant.design/components/spin

**Comment by benjycui** [comment]
感觉这个意义不大。。还要手动给每张图片设置一个 `offsetTop`

**Comment by afc163** [comment]
不用的，offsetTop 不是必选。

**Comment by benjycui** [comment]
加了之后，在体验上感觉更慢了，先不加。
