### ISSUE TITLE
Layout.Sider侧边导航可收起时，显示错误

### ISSUE THREAD

**Issue by cpxGithub** [ant-design/ant-design#12366]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
window10，Chrome-66.0.3359.170，react16.4.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4qpl3k9vr7)

### Steps to reproduce
1.开启侧边栏可收起。
2.Menu设置onOpenChange={this.onOpenChange}，   openKeys={this.state.openKeys}。
3.选择二级目录。
4.点击侧边栏收起。

### What is expected?
侧边栏收起时，菜单栏不应该显示。
侧边栏收起状态下，使用鼠标滑过其他菜单栏，再次放开侧边栏时，已选中的二级菜单应该展开。

### What is actually happening?
侧边栏收起时，菜单栏显示。
侧边栏收起状态下，使用鼠标滑过其他菜单栏，再次放开侧边栏时，已选中的二级菜单没有展开。

**Comment by zombieJ** [comment]
Menu 做成可控后需要自己管理一下 openKeys 的状态，否则收缩的时候你这相当于锁定了它要展示：https://codesandbox.io/s/3q1q7l7xlm
