### ISSUE TITLE
Allow Calendar to display the Panel and its options

### ISSUE THREAD

**Issue by ditiem** [ant-design/ant-design#12373]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a calendar that on each day I want to put a different price. For instance, a calendar that shows the flight ticket price depending on the date you depart. So I have two problems here:
- I dont want the user to select "year", as it does not makes sense in this scenario
- I would like to make a view where there is no date selector but a calendar carousel or a table of calendars. In this case I would like to completely hide the panel as I am rendering the 12 months on the screen.

### What does the proposed API look like?
I have thought of two proposals:

<Calendar showHeader={ false } />
<Calendar showYearSelector={ false } />

OR

<Calendar showPanel={ [ 'month', 'year' ] } />

**Comment by zombieJ** [comment]
Its view is by design. But if you really don't like it may use css to hide the header.

**Comment by ditiem** [comment]
@zombieJ  Will you assure the CSS wont change in future releases? Otherwise your solution is not valid.

**Comment by zombieJ** [comment]
Dom structure of a component may be adjust, but the exist className is stable (like `ant-fullcalendar-header` in Calendar).
So, yes. You can use it to hide the element.
