### ISSUE TITLE
How about Weekly Ant-Design Things?

### ISSUE THREAD

**Issue by monkindey** [ant-design/ant-design#12379]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Inspired by https://twitter.com/PhilippSpiess/status/1043119121871896576 , [The first week about React](https://twitter.com/PhilippSpiess/status/1043186943624982529)

It will be awesome to ant-design subscribers.

### What does the proposed API look like?
No

**Comment by ilanus** [comment]
@monkindey `antd` does maintain a weekly change logs on their website https://ant.design/changelog

**Comment by ycjcl868** [comment]
Maybe, you can see as follows: 
- [Antd Course](https://www.yuque.com/ant-design/course)
- [changelog](https://ant.design/changelog)
