### ISSUE TITLE
上传 Upload

### ISSUE THREAD

**Issue by sunguoxing0628** [ant-design/ant-design#12375]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
场景：界面一行会出现很多功能按钮，其中包括“上传”。
问题：目前“上传”组件只能自己单独一行。

### What does the proposed API look like?
需求：增加可设置属性，标识功能按钮是单独一行或跟随内部组件
```
<Upload>
    <Button icon="import">上传</Button>
</Upload>
```

> **目前可达到效果：**

![image](https://user-images.githubusercontent.com/27573161/45926531-f5194700-bf55-11e8-8781-1b6d1f6211b4.png)

> **期望可实现效果：**

![image](https://user-images.githubusercontent.com/27573161/45926541-1c701400-bf56-11e8-9880-954427a06d2d.png)

**Comment by afc163** [comment]
https://codepen.io/anon/pen/mGgXGd?&editors=001
