### ISSUE TITLE
Callback for modal destroy

### ISSUE THREAD

**Issue by jaisonjjames** [ant-design/ant-design#12383]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like to get callback future after modal destroy. For example, I would like to pass some information to the user by using Modal.info(), if user doesn't wish to click an "OK" button after reading the message, I would like to destroy/close the modal info in a setTimeout and proceed with next function.

### What does the proposed API look like?
const payInfo = Modal.info({
    title: 'Request processing...',
    content: ('Dont refresh'),
    onOk: () => {
        document.getElementById("paymentForm").submit();
    }
});

setTimeout(() => payInfo.destroy(() => {document.getElementById("paymentForm").submit()}), 3000);

**Comment by zombieJ** [comment]
If you call the destroy function, you've already know the destroy will happen: https://codesandbox.io/s/m5wrmx407p

**Comment by jaisonjjames** [comment]
I think it's not a usage question because I have already tried the approach posted by @zombieJ, the issue for this approach is "onFinish" method will trigger twice if the user clicks on the ok button before timeout ends. the behavior is based on the user action. that's why I have requested a callback.
