### ISSUE TITLE
【2.x版本没问题，3.x出现以下描述问题】tooltip，包括popover和Popconfirm在触屏windows上，点击弹出的展开区域，会出现pop闪退的问题

### ISSUE THREAD

**Issue by jsdchenye** [ant-design/ant-design#12388]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
win10/chrome69 【触屏电脑】

### Reproduction link
[https://ant-design.gitee.io/components/popconfirm-cn/](https://ant-design.gitee.io/components/popconfirm-cn/)

### Steps to reproduce
在触屏windows上，antd中Popconfirm通过按钮被点开后，再次点击展开内容区域，不论是“确定”按钮还是展开空白区域，pop都会闪退。内部的“确认”按钮也点击不上，onConfirm无法被触发；

### What is expected?
希望点击Popconfirm展开的内容，pop仍然存在，不会闪退。点击其中的“取消”和“确认”按钮都能触发相应的onCancel 和onConfirm

### What is actually happening?
点击Popconfirm展开的内容，pop立即闪退，其中的“取消”和“确认”按钮的事件无法触发

---
触屏电脑，试了下antd中官网中的例子（tooltip,popover,Popconfirm事例），3.x版本存在同样的问题，2.x版本没有这样的问题。

**Comment by zombieJ** [comment]
应该也是 onTouch 的问题，看来得解决一下...
ref: https://github.com/ant-design/ant-design/issues/12382

**Comment by jsdchenye** [comment]
感谢🙏

**Comment by haue** [comment]
rc-trigger2.6.1的bug引起的
