### ISSUE TITLE
级联选择手机端有bug

### ISSUE THREAD

**Issue by YYL1999** [ant-design/ant-design#12382]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
Chrome最新版  react16.2.0

### Reproduction link
[https://ant.design/components/cascader-cn/](https://ant.design/components/cascader-cn/)

### Steps to reproduce
手机端失效

### What is expected?
手机端无bug

### What is actually happening?
手机端无法选择

**Comment by ycjcl868** [comment]
`Cascader` 组件在 mobile 下 touch 事件不生效。
不过移动端建议使用 [antd-mobile](http://mobile.ant.design)，antd 主要用在 pc。

**Comment by afc163** [comment]
为了提高效率和更加聚集，我们不会特别针对移动端进行优化。当然如果社区可以帮助我们提高在移动端的表现，可以直接给我们 PR 帮助修复，这里先关了。
