### ISSUE TITLE
table表单的滚动条自定义样式

### ISSUE THREAD

**Issue by leeseean** [ant-design/ant-design#12381]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
滚动条是浏览器自带的，有点丑，可否自定义滚动条样式？

### What does the proposed API look like?
增加一个prop，scrollBarStyle={{width:'',color:''}}

**Comment by zombieJ** [comment]
https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

**Comment by leeseean** [comment]
> https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

这个没有兼容ie浏览器，火狐浏览器

**Comment by afc163** [comment]
这是浏览器的特性，Ant Design 不会支持超出浏览器能力的功能。

**Comment by leeseean** [comment]
> 这是浏览器的特性，Ant Design 不会支持超出浏览器能力的功能。

不可以用div模拟下滚动条吗？

**Comment by zombieJ** [comment]
> 不可以用div模拟下滚动条吗？

这不是普遍需求，不会去特地开发。
