### ISSUE TITLE
expandedRowKeys设置值后，貌似只能通过事件更新state中的keys数组，再渲染，有没有办法在一开始设置onExpand中第二个参数expanded默认为true

### ISSUE THREAD

**Issue by zjscy666** [ant-design/ant-design#12394]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
全部

### Reproduction link
[https://github.com/ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)

### Steps to reproduce
随便写点 只设置写死的expandedRowKeys

### What is expected?
需要个属性  能在一开始设置expanded一开始展开后为true

### What is actually happening?
时间是展开后 onExpand中的expanded全为false,这样需要通过其他方式更新expandedRowKeys，无奈

---
不属于bug 只是希望多个功能

**Comment by zombieJ** [comment]
没看懂你的意思......

**Comment by zjscy666** [comment]
就是table组件中设置expandedRowKeys，会让table这个组件变成可控组件，这样就不会自己收缩了，需要手动设置expandedRowKeys！onExpand这个方法中有个参数expanded，能不能提供一个动态的办法，可以在一开始设置expandedRowKeys的时候，就让expanded参数的值动态变化

**Comment by yesmeck** [comment]
这样不行的，老老实实按受控组件这个思路来吧。

**Comment by zjscy666** [comment]
我幼小的心灵收到了成吨的伤害，宝宝心里苦，但是宝宝不说话
