### ISSUE TITLE
Checkbox 校验缺陷 

### ISSUE THREAD

**Issue by 1997Liusheng** [ant-design/ant-design#12398]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
win 10,   Google Chrome 版本 68.0.3440.106（正式版本） （64 位）

### Reproduction link
[https://codepen.io/anon/pen/qMvVWW?editors=0010](https://codepen.io/anon/pen/qMvVWW?editors=0010)

### Steps to reproduce
进入重现连接，点击提交表单按钮

### What is expected?
重现连接中可查看

### What is actually happening?
重现连接中可查看

---
1.保存勾选信息后，刷新页面。
2.只有当勾选时才能进行下一步操作。

**Comment by zombieJ** [comment]
`getFieldDecorator` 默认对 `value` 进行操作。如果需要对 Checkbox 操作，需要对 `valuePropName` 进行设定，就是你的第二种写法。
