### ISSUE TITLE
transfer组件item title在自定义render下不准确

### ISSUE THREAD

**Issue by shudery** [ant-design/ant-design#12399]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义render时，如果render函数返回的是字符串则item的title显示正常，但如果返回的是一个JSX，item的title属性会变为'[object Object]'。

### What does the proposed API look like?
组件提供一个属性，方便控制title的展示。
或者组件内部渲染item title时做一个判断，不是string的就不要展示了。

**Comment by zombieJ** [comment]
调整了一下逻辑，只有是 `string` 才显示 `title`，可以配合：
```jsx
render={item => (<span title="your logic">{item.title}</span>)}
```

来自定义 title

**Comment by shudery** [comment]
good job!
