### ISSUE TITLE
苹果手机safari浏览器MenuItem中a链接点击没反应

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#12393]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
苹果手机 safari浏览器

### Reproduction link
[https://codepen.io/anon/pen/rZEaPO?&editors=001](https://codepen.io/anon/pen/rZEaPO?&editors=001)

### Steps to reproduce
在苹果手机浏览器中展开菜单点击展开的菜单

### What is expected?
跳转到链接地址

### What is actually happening?
没有跳转

**Comment by zombieJ** [comment]
应该和 #12388 一个问题
