### ISSUE TITLE
InputNumber设置precision后希望有选项可以关闭自动补全小数位的功能

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#12405]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我设置了precision只是想限制小数位, 但不想用户输入的所有数字都必须达到这个位数, 自动补充小数位之后感觉看起来不太清晰

### What does the proposed API look like?
InputNumber设置precision后希望有选项可以关闭自动补全小数位

**Comment by zombieJ** [comment]
如果是这个使用场景，`precision` 不太适用。你可以这么处理：https://codesandbox.io/s/jj014l35wy

**Comment by ty-bt** [comment]
我本来是以为我自己这样处理后感觉precision就没啥存在的意义了, 既然本来就不是这个场景使用的那就是我想错了..  多谢大佬..
