### ISSUE TITLE
【Table固定列功能】可否实现固定任意列，而不从第一列开始固定？

### ISSUE THREAD

**Issue by Gwen106728** [ant-design/ant-design#12400]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1、需要固定的列不在表的前几列，并且表头不可更改顺序的时候，可以固定中间几列，缩小固定的长度，在屏幕较小的时候不影响用户使用。

### What does the proposed API look like?
如果实现没有需要，可以保持现在的API不变

**Comment by zombieJ** [comment]
不太明白，意思是几列被固定后，剩下的空间不足就支持 scroll？

**Comment by Gwen106728** [comment]
> 不太明白，意思是几列被固定后，剩下的空间不足就支持 scroll？

不好意思没有描述清楚
我的意思是：
 比如，我对表设置了{{ x: 1500, y: 300 }}，而table父层宽度只有600px，我固定第4，5列，前面的1-3列并不需要固定，如果一起固定，总共的固定区域就会很长，窗口会被占用较多。

**Comment by Gwen106728** [comment]
> 不太明白，意思是几列被固定后，剩下的空间不足就支持 scroll？

实现效果：如果可以从第4，5列开始固定，那么滚动到第4，5列的时候才开始固定

**Comment by yesmeck** [comment]
想想不出是个什么交互。

**Comment by Gwen106728** [comment]
> 想象不出是个什么交互。

不要啊~你们一定要想出来啊、、、、

就是滚动到第4，5列的时候 ，第4，5列开始固定，固定在开头，然后看4，5列后面的列，相当于第1，2，3列被隐藏了，然后往回滚的时候，4，5列再还原。。。其实就是给left加个值，好像原本浮动的table的left是0，改成1，2，3列的宽度和，不知道是不是这样实现啊。。囧。。

**Comment by zombieJ** [comment]
还是不太明白，你能说说是什么使用场景吗？

**Comment by Gwen106728** [comment]
> 还是不太明白，你能说说是什么使用场景吗？

我们的表的列很多很长（比如财务的表），但是表的父级宽度有限，这个时候X方向就需要滚动
操作最后几列内容需要去比对关键的第4,5列
但是，目前antd table如果去固定列，是必须从第一列写fixed：left，如果我从第2列开始写，那么结果就永远遮挡了第一列。
我刚刚试了一下给ant-table-fixed-left加了left不太行，因为是直接浮动在最上面固定的，可能要监听一下scroll，当滚动的长度大于 “开头没加fixed的列的长度和的时候“ 才显示。。。。。

**Comment by zombieJ** [comment]
如果是这样，为什么不直接把 4 5 列放到前面 fix 住呢？

**Comment by Gwen106728** [comment]
> 如果是这样，为什么不直接把 4 5 列放到前面 fix 住呢？

确实有些表可以挪动位置
但是有些表有业务逻辑性在里面，不可以换位置，哎

**Comment by zombieJ** [comment]
这个需求不太普遍，应该不会特意去开发。当然，如果你有意愿，可以给 rc-table 发 PR 哈~

**Comment by afc163** [comment]
这个交互太复杂了，楼主还是想想别的办法。
