### ISSUE TITLE
Transfer[onSearchChange]

### ISSUE THREAD

**Issue by fhqdgv** [ant-design/ant-design#12410]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
win7 chrome

### Reproduction link
[https://codepen.io/anon/pen/oPKzLg](https://codepen.io/anon/pen/oPKzLg)

### Steps to reproduce
input word onSearchChange fn will trigger，but click auto clear btn not

### What is expected?
点搜索框清除按钮时也触发

### What is actually happening?
并没有

---
  handleLeftFilter = (e: React.ChangeEvent<HTMLInputElement>) => this.handleFilter('left', e);
  handleRightFilter = (e: React.ChangeEvent<HTMLInputElement>) => this.handleFilter('right', e);

  handleClear = (direction: string) => {
    this.setState({
      [`${direction}Filter`]: '',
    });
  }

场景类似这个https://github.com/ant-design/ant-design/issues/4444
发起搜索事件为change不是enter

**Comment by zombieJ** [comment]
目前的 onSearchChange 不太好加这个。
像 Select 一样出个 onSearch(dir, str) 吧。

@yesmeck @afc163
