### ISSUE TITLE
Standalone Badge is vertically offset

### ISSUE THREAD

**Issue by eduludi** [ant-design/ant-design#12419]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://oxym7vjwpq.codesandbox.io)

### Steps to reproduce
Since `v3.9.3`, setting a **standalone** `Badge` (with `count` lower than 100) makes it go up, not aligned with the text like it was before this version. And setting `offset` doesn't help.

### What is expected?
Badge to be aligned to text

### What is actually happening?
Badge is offset vertically to the top

---
You can even see this bug in `Badge` documentation page, in the "Standalone" section

**Comment by zombieJ** [comment]
@afc163 , could you pls take a look why remove the `vertical-align`? https://github.com/ant-design/ant-design/commit/fd409df14d33cb5acc2bcc4eb5164c663435d8ec#diff-62068314142dce13c064785c1f44b644

**Comment by afc163** [comment]
```jsx
<Badge><span style={{ verticalAlign: 'top' }} /></ Badge>
<Badge><span style={{ verticalAlign: 'top' }} /></ Badge>
<Badge><span style={{ verticalAlign: 'top' }} /></ Badge>
```

For not changing vertical align of wrapped element.

I should put `vertical-align: middle` on badge not as a wrapper.
