### ISSUE TITLE
有关主题设计的建议

### ISSUE THREAD

**Issue by liekkas** [ant-design/ant-design#1241]
您好，为了制作一套黑色主题的皮肤，我把相关组件的less样式文件翻了个遍，里面很多基于浅色系的硬编码，比如下拉框的白色背景色，这使得单修改一个custom.less文件还远不够。也许是我还没找到更好的方式？

我想了解下ant-design会针对主题设计出一套更为优雅的机制来方便大家定制主题吗？

我用过echarts、material-ui组件，它们提供一个设置主题的api接口，只需要赋一个js对象就能定制一套皮肤，建议ant-degsin也可以提供一个类似的api接口。

若有违你们的设计理念，那可以再丰富下custom.less的变量，少些硬编码，尽量做到一个文件就能搞定主题。

感谢你们的努力。

**Comment by afc163** [comment]
Ant Design 的设计初衷就是预设一套强烈风格化的主题，减少各种样式上的定制，提高开发效率，现阶段主题更换上只推荐主色的定制。

目前我们的设计师也在梳理各种样式变量，后续会支持一定程度内更自由的主题定制。到时前端框架层面也会有相应的统一支持。

现阶段如果有变化较大的定制需求，可能需要一些样式覆盖，也欢迎给我们 PR ~
