### ISSUE TITLE
table th 不设置border的时候  chrome下面table出现横向滚动条

### ISSUE THREAD

**Issue by frank7755** [ant-design/ant-design#12411]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
win10 , chrome 69.0.3497.100

### Reproduction link
[https://codepen.io/frank7755/pen/aaeZoE](https://codepen.io/frank7755/pen/aaeZoE)

### Steps to reproduce
table th border设置为none的时候，出现横向滚动条。

### What is expected?
th border 为none 的时候，滚动条不会出现

### What is actually happening?
th border 为none 的时候，滚动条出现

**Comment by frank7755** [comment]
@yesmeck  我现在的需求是，需要scroll.x  ，现在其他浏览器是没问题的，就是谷歌浏览器下，会默认出现横向滚动条，以前antd里面， table上面  border-collapse: separate;  更新版本后为    border-collapse: collapse; 然后就出现了上述问题。

**Comment by yesmeck** [comment]
设置 `scroll.x` 就是表示需要横向滚动，为什么会不需要滚动条呢？

**Comment by frank7755** [comment]
scroll.x设置时，是希望在视窗宽度小于给定宽度的时候，出现滚动条，并不是一开始就出现，因为bodyStyle给的是overflowX:auto，并未得到overflow:auto的效果

**Comment by zombieJ** [comment]
https://codesandbox.io/s/ookj9k5vyz
