### ISSUE TITLE
DatePicker的mode选用了yaer之后不能点击了

### ISSUE THREAD

**Issue by babyxu51521** [ant-design/ant-design#12416]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以选择年了

### What does the proposed API look like?
能点击 最好在点击时候触发一个回调

**Comment by zombieJ** [comment]
请参考样例：https://ant.design/components/date-picker-cn/#components-date-picker-demo-mode
