### ISSUE TITLE
自定义表单控件存在多个自定义校验规则时，存在不触发的问题

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design#12418]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
win10, chrome69,react16

### Reproduction link
[https://codepen.io/rhuaer/pen/pOMRbN?editors=0010](https://codepen.io/rhuaer/pen/pOMRbN?editors=0010)

### Steps to reproduce
1. 默认直接点击submit，会看到第一条校验规则的提示
2. 在输入框中输入2，点击submit，没有触发第二条校验规则，而是校验通过

### What is expected?
1. 触发全部自定义规则

### What is actually happening?
1. 只触发了第一条校验规则

**Comment by zombieJ** [comment]
`InputNumber` 不支持 `onBlur` 校验：https://codepen.io/anon/pen/mGNRNV?editors=0010

**Comment by Rhuaer** [comment]
@zombieJ 请问官方是否有相关文档说明呢？我在`Form`组件这一节没有看到相关的备注

**Comment by zombieJ** [comment]
sorry，看错了。你的这个问题是你的写的 `PriceInput` 组件只处理了 `onChange` 没有处理 `onBlur` 事件。
