### ISSUE TITLE
Second time selection not work in TreeSelect

### ISSUE THREAD

**Issue by halukapaydin** [ant-design/ant-design#12424]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
Chrome(version 69) , Firefox(version 62), OS Ubuntu 18.04

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p5ro3v4v7q)

### Steps to reproduce
click TreeSelection component

### What is expected?
i want to change selection

### What is actually happening?
first time i change selection but second, third... time selection does not work.

**Comment by zombieJ** [comment]
这个已经修了，删除 node_modules 重装一下
