### ISSUE TITLE
Click Menu item will close DropDown

### ISSUE THREAD

**Issue by JHanLu** [ant-design/ant-design#12420]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
windows10, Chrome 62

### Reproduction link
[https://codepen.io/JHanLu/pen/YOmvGr?&editors=001](https://codepen.io/JHanLu/pen/YOmvGr?&editors=001)

### Steps to reproduce
I put a search input in Menu item in dropDown overlay, when I click the search input in menu, dropDown menu will be closed. When I do something like preventDefault in Menu, it show event.preventDefault is undefined.

### What is expected?
I want to click the Menu without closing dropDown.

### What is actually happening?
When I click the menu item, dropDown closed immediately.

**Comment by picodoth** [comment]
please refer this example: https://codepen.io/pen/?&editors=001

**Comment by JHanLu** [comment]
@picodoth Your example is empty.

**Comment by picodoth** [comment]
woops, my bad: https://codesandbox.io/s/k5v3yjzwrv

**Comment by JHanLu** [comment]
Thanks! Been struggled for a long time.

**Comment by JHanLu** [comment]
@picodoth Thank u so much! I could have tried it. 😅

**Comment by mahyalpr** [comment]
I have a problem. i set the input into dropdown , I used visible an onvisiblechange , it works, but i cant write anything in input !!!!!!!!!!!!!!!!!!!!!!

**Comment by arnav-dt** [comment]
> woops, my bad: https://codesandbox.io/s/k5v3yjzwrv

Update 2021: Fix antd imports to 

`import Dropdown from 'antd/lib/dropdown';
import Icon from 'antd/lib/icon';
import Menu from 'antd/lib/menu';`

**Comment by muslimr** [comment]
> woops, my bad: https://codesandbox.io/s/k5v3yjzwrv

this page doesn't work correctly man )

**Comment by saikrishnabanda5** [comment]
> 

THis is empty

**Comment by EvanSmith93** [comment]
It seems that this fix is no longer viable, as it involves the `overlay` prop which is deprecated. The docs have a [solution](https://ant.design/components/dropdown#dropdown-demo-overlay-open) for this, however it doesn't work for sub menu items. Does anyone know of a similar fix for sub menu dropdown items?
