### ISSUE TITLE
How to use Tooltip in CheckboxGroup

### ISSUE THREAD

**Issue by xiashei** [ant-design/ant-design#12427]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
windows10 \69.0.3497.100、react@16.5.2，react-app-rewired@1.6.2，react-dom@16.5.2，babel-plugin-import@1.9.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lp1z9xrrpm)

### Steps to reproduce
I can use ToolTip in Checkbox,but it can't work in Checkbox.group.Is this a bug? How can I use it if it isn't.

### What is expected?
I can use ToolTip in Checkbox,but it can't work in Checkbox.group.Is this a bug? How can I use it if it isn't.

### What is actually happening?
I can use ToolTip in Checkbox,but it can't work in Checkbox.group.Is this a bug? How can I use it if it isn't.

---

**Comment by ycjcl868** [comment]
https://codesandbox.io/s/x972o75k1p

**Comment by xiashei** [comment]
> https://codesandbox.io/s/x972o75k1p

非常感谢！

**Comment by vatsaldaveVD** [comment]
> https://codesandbox.io/s/x972o75k1p

Can you check this link it is not opening

**Comment by xiashei** [comment]
> > https://codesandbox.io/s/x972o75k1p
> 
> Can you check this link it is not opening

this question has been solved.It's my fault to forget to close it.

**Comment by xiashei** [comment]
> > https://codesandbox.io/s/x972o75k1p
> 
> Can you check this link it is not opening

because this question was solved.

**Comment by vatsaldaveVD** [comment]
> > > https://codesandbox.io/s/x972o75k1p
> > 
> > 
> > Can you check this link it is not opening
> 
> because this question was solved.

It is giving the Request failed with status code 404

**Comment by wphatpat** [comment]
how to use it, pls share code again.
