### ISSUE TITLE
Second time selection not work in TreeSelect

### ISSUE THREAD

**Issue by halukapaydin** [ant-design/ant-design#12423]
Second time selection not work in TreeSelect
Demo code not work ( https://codesandbox.io/s/p5ro3v4v7q )
i tried in Chrome(version 69) and Firefox(version 62). 
My os is Ubuntu 18.4

**Comment by zombieJ** [comment]
This has been fixed in `rc-tree-select@2.2.6`. Pls remove `node_modules` and reinstall: https://codesandbox.io/s/1zpx5k57p7
