### ISSUE TITLE
Pagination页数多了会换行，可不可以加一个参数控制显示的页码的个数

### ISSUE THREAD

**Issue by zhxsh** [ant-design/ant-design#12435]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
windows 10,chrome 67

### Reproduction link
[https://github.com/zhxsh/zhxsh.github.io](https://github.com/zhxsh/zhxsh.github.io)

### Steps to reproduce
Pagination 组件总长度限制在300px，当有30000多页时，页码会分成上下两行。（上面那个链接不是，内网的，没有传代码上GitHub）

### What is expected?
加一个参数控制显示的页码的个数

### What is actually happening?
页码会分成上下两行

**Comment by zombieJ** [comment]
设计上少于 5 个就不好看，建议使用[迷你](https://ant.design/components/pagination-cn/#components-pagination-demo-mini)或者[简洁](https://ant.design/components/pagination-cn/#components-pagination-demo-simple)模式。

**Comment by zhxsh** [comment]
搜嘎  谢谢回复
