### ISSUE TITLE
table-columns fixed and hover color wrong

### ISSUE THREAD

**Issue by Manjushaka** [ant-design/ant-design#12432]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
macOS Sierra 10.12.6, chrome 67.0.3396.99

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
In antd website, the example of components-table-demo-fixed-columns(link: https://ant.design/components/table-cn/#components-table-demo-fixed-columns), the cursor hovers on the fixed columns of the first line(or other lines),and then move the cursor to the non-fixed columns of the first line. 
Note: Keep parallel movement on the same line(from the fixed columns to the the non-fixed columns , or from the non-fixed columns to the fixed columns )!!!

### What is expected?
after movement, the entire row's background-color is hover color.

### What is actually happening?
after movement,only the non-fixed columns's background-color is hover color(when from the fixed columns to the the non-fixed columns), or only the fixed columns's background-color is hover color(when from the non-fixed columns to the fixed columns ).

**Comment by yesmeck** [comment]
Fixed in rc-table@6.3.7, try reinstall node_modules.
