### ISSUE TITLE
DatePicker的mode选用了yaer之后不能点击了

### ISSUE THREAD

**Issue by babyxu51521** [ant-design/ant-design#12434]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
浏览器版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://0q4nx79x00.codesandbox.io/)

### Steps to reproduce
 <DatePicker mode="year" onPanelChange={e => console.log(e)} />

### What is expected?
能有一个年的日期选择器

### What is actually happening?
暂时还没有

---
选择年的日期切换

**Comment by ycjcl868** [comment]
参考下 [受控面板](https://ant.design/components/date-picker-cn)
https://codesandbox.io/s/koryl868ko

**Comment by xiashei** [comment]
> 参考下 [受控面板](https://ant.design/components/date-picker-cn)
> https://codesandbox.io/s/koryl868ko

![image](https://user-images.githubusercontent.com/28834220/46138429-73d7f200-c27e-11e8-963f-26fd4a3811f8.png)
点击2015以后，上面年份变了，但是选择框（蓝色部分）依旧是2018年。

**Comment by Jian-Yin** [comment]
可以在onPanelChange上绑定事件，通过 ref 调用 handleChange，handleOpenChange 修改 value 和 显示状态
 <DatePicker mode='year' format='YYYY' ref={c => { this.yearPicker = c }} onPanelChange={this.yearPickerChange} /> 
yearPickerChange = (value, mode) => {
    this.yearPicker.picker.handleChange(value)
    this.yearPicker.picker.handleOpenChange(false)
  }
