### ISSUE TITLE
Code convention for antd

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#1244]
Thanks to @waywardmonkeys, antd's code style is more consistent now :-)

And I think we had better to write those code convention in a document, so others can refer to it (as a complement or ESLint). I had created a [wiki](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).

Maybe we could discuss code convention in this issue, and update the wiki when we draw a conclusion. 

cc @afc163 @yiminghe 
Maybe @hotoo is interested in this :-)

**Note:** antd's code style should be super set of [eslint-config-airbnb](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb).

**Comment by benjycui** [comment]
We can discuss questions like this:

I think `PropTypes.string` is better than `React.PropTypes.string`, for it's more concise.

```jsx
// Good
Button.propTypes = {
  type: PropTypes.string,
};

// Bad
Button.propTypes = {
  type: React.PropTypes.string,
};
```

**Comment by awaw00** [comment]
```javascript
// Good
Button.propTypes = {
  type: PropTypes.string,
}
```

```javascript
// Bad
Button.propTypes = {
  type: PropTypes.string,
};
```

自从写js后看到分号总觉得不自在。。。

**Comment by yiminghe** [comment]
based on eslint-config-airbnb@6.x
