### ISSUE TITLE
TreeSelect放在Form.Item中时无法直接选中点击项

### ISSUE THREAD

**Issue by wildtree001** [ant-design/ant-design#12444]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
win10，chrome，ant-design-pro2.0

### Reproduction link
[https://gist.github.com/peterbe/a3c9c716c4a99b97b4dac5f81915d5a0](https://gist.github.com/peterbe/a3c9c716c4a99b97b4dac5f81915d5a0)

### Steps to reproduce
<Form onSubmit={this.handleSubmit}>
        <Form.Item labelCol={{ span: 5 }} wrapperCol={{ span: 15 }} label="父分类">
            {this.props.form.getFieldDecorator('fatherId', {
              initialValue: 'parent 1',
            })(
                <TreeSelect
                style={{ width: 300 }}
                onChange={this.onChange}
              >
                <TreeNode value="parent 1" title="parent 1" key="0-1">
                  <TreeNode value="parent 1-0" title="parent 1-0" key="0-1-1">
                    <TreeNode value="leaf1" title="my leaf" key="random" />
                    <TreeNode value="leaf2" title="your leaf" key="random1" />
                  </TreeNode>
                  <TreeNode value="parent 1-1" title="parent 1-1" key="random2">
                    <TreeNode value="sss" title={<b style={{ color: '#08c' }}>sss</b>} key="random3" />
                  </TreeNode>
                </TreeNode>
              </TreeSelect>
            )}
          </Form.Item>
          </Form>

### What is expected?
点击任意一个节点直接选中

### What is actually happening?
无法直接切换选中项

---
表单里放一个TreeSelect，要切换选中项时必须先点击原项清除，然后才能选中其他项
使用this.props.form.setFieldsValue也无效

**Comment by zombieJ** [comment]
重现不对，给个在线的例子：https://u.ant.design/codesandbox-repro

**Comment by ty-bt** [comment]
@wildtree001 我也有这个问题, 重新下载依赖就好了..

**Comment by ggwakaka** [comment]
I met the same problem and find the answer. This has been fixed in rc-tree-select@2.2.6. Pls remove node_modules and reinstall.You can try it.
