### ISSUE TITLE
Canendar IE下选择月份时样式错误

### ISSUE THREAD

**Issue by jinyaqiao1102** [ant-design/ant-design#12449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
IE 11

### Reproduction link
[https://ant.design/components/calendar-cn/#header](https://ant.design/components/calendar-cn/#header)

### Steps to reproduce
先点击选择月份 然后选择一个其他的月份 再次点击选择月份

### What is expected?
下拉框中月份样式正确

### What is actually happening?
下拉框中月份样式变短导致显示中会显示...

**Comment by zombieJ** [comment]
能提供个截图吗？

**Comment by jinyaqiao1102** [comment]
![image](https://user-images.githubusercontent.com/12856504/46239551-69c40980-c3cc-11e8-8342-9cd6c8db282b.png)

**Comment by jinyaqiao1102** [comment]
![bug](https://user-images.githubusercontent.com/12856504/46239626-55344100-c3cd-11e8-9588-e6bf3167af27.gif)
@zombieJ
