### ISSUE TITLE
点击表头排序功能？更换版本？

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design#12447]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
antd 3.9.3

### Reproduction link
[https://deploy-preview-12353--ant-design.netlify.com/components/table-cn/](https://deploy-preview-12353--ant-design.netlify.com/components/table-cn/)

### Steps to reproduce
下载antd3.9.3或者3.9.2版本之后，并不能实现上述链接中实现的功能，在上面链接的示例中代码实现并没有发现什么变化：
{
  title: 'Age',
  dataIndex: 'age',
  defaultSortOrder: 'descend',
  sorter: (a, b) => a.age - b.age,
},
<Table columns={columns} dataSource={data} onChange={onChange} />,

我本地代码没有onChange方法，但是我觉得应该不是问题所在，我以为只要匹配版本不改变代码就可以实现这个功能，哪里我想的不对？

### What is expected?
升级版本后可以实现点击表头排序

### What is actually happening?
并不能排序

**Comment by zombieJ** [comment]
ref: https://github.com/ant-design/ant-design/pull/12264#issuecomment-425312292
