### ISSUE TITLE
Strange warning message about using `theme="filled"` prop on <Icon/>

### ISSUE THREAD

**Issue by peterbe** [ant-design/ant-design#12441]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
jest

### Reproduction link
[https://gist.github.com/peterbe/a3c9c716c4a99b97b4dac5f81915d5a0](https://gist.github.com/peterbe/a3c9c716c4a99b97b4dac5f81915d5a0)

### Steps to reproduce
I have something like https://gist.github.com/peterbe/a3c9c716c4a99b97b4dac5f81915d5a0 in my code. When rendered in a test run by jest I get this output:

```
 PASS  src/tests/workflows/recipes/components/HistoryItem.test.js
  ● Console

    console.error node_modules/antd/node_modules/warning/warning.js:36
      Warning: This icon already has a theme 'outlined'. The prop 'theme' filled will be ignored.
```

I this it's coming from here: https://github.com/ant-design/ant-design/blob/5a0448aa4dadbb5e8563d162a68c064bfd877eb2/components/icon/index.tsx#L121-L128

I don't know why it only happens in running tests. I supposed because of this https://github.com/BerkeleyTrue/warning/blob/e4806228c076429774878522cafdf9321b7ff71c/warning.js#L17

### What is expected?
No warning. If I don't use `theme="filled"` I get an outline icon which is not what I want. 

### What is actually happening?
The warning adding noise to my tests when running with jest.

**Comment by peterbe** [comment]
What it looks like
<img width="727" alt="screen shot 2018-09-27 at 4 44 13 pm" src="https://user-images.githubusercontent.com/26739/46173569-995ffe00-c274-11e8-9cd6-6197195aa378.png">

**Comment by peterbe** [comment]
For the record, if I do this:

```javascript
      // <Icon type={iconType} theme="filled" style={{ fontSize: '18px' }} />
      <Icon type={iconType} style={{ fontSize: '18px' }} />
```
The warning does not appear when running tests. 

Also, `process.env.NODE_ENV !== 'production'` is `true` in both running my create-react-app based app with the dev server *and* when running test. 

I don't know why I don't get the warning when running the app at `http://localhost:3000`.

**Comment by yesmeck** [comment]
Thanks for reporting, will be fixed in next release (this weekend).
