### ISSUE TITLE
datePicker 组件添加195像素的宽度

### ISSUE THREAD

**Issue by zyt-cloud** [ant-design/ant-design#12446]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
3.9.2

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/date-picker/createPicker.tsx](https://github.com/ant-design/ant-design/blob/master/components/date-picker/createPicker.tsx)

### Steps to reproduce
datePicker 配置showTime 自动加了195px的宽度 导致整个项目布局混乱

### What is expected?
不添加195px的宽度

### What is actually happening?
自动添加195px的宽度

**Comment by zombieJ** [comment]
因为 css 调整过字体间距，小于 195 会显示不全。
感觉可以搞成 minWidth = 195?

**Comment by zyt-cloud** [comment]
看源码好像props.style也可以覆盖

**Comment by zombieJ** [comment]
说的有道理，改成只有当 style 里没有 width 属性时才覆盖。这样用户可以通过：
```
style={{ width: null }}
```
来禁用自动调整

**Comment by huaibaomengxiang** [comment]
@zombieJ  如何取消min-width=195 这个设置？
