### ISSUE TITLE
IE报错或者空白

### ISSUE THREAD

**Issue by lusonghe0313** [ant-design/ant-design#12445]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
window10   IE11 

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
github  上的ant design脚手架下载下来之后运行，在IE11页面会报错 “ TypeError: 对象不支持'find'属性或方法 ”（错误有多个），使用这个脚手架做好本地项目，install @babel/polyfill及引用之后 ，在IE11页面打开空白

### What is expected?
显示正常 

### What is actually happening?
空白页或者报错

**Comment by zombieJ** [comment]
> antd-init 是一个用于演示 antd 如何使用的脚手架工具，实际业务项目建议使用 dva-cli 和 create-react-app 进行搭建。

可以参考：
- https://umijs.org/
- https://github.com/facebook/create-react-app

**Comment by lusonghe0313** [comment]
@zombieJ 我们用的是antd pro,也是空白

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design-pro/issues/2344
