### ISSUE TITLE
提供模块样式的版本

### ISSUE THREAD

**Issue by jeezlee** [ant-design/ant-design#12457]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们的系统是由多个子应用组合（前端微服务），所以各个应用可能会引入不同版本的antd组件库，这时候就会产生样式冲突和其他副作用。
所以希望antd能提供模块化的样式或者类似 Material-UI 的样式处理方式

### What does the proposed API look like?
-

**Comment by yesmeck** [comment]
CSS in JS 的方案之前有调研过，把目前的 less 代码全部重写掉工作量实现太大，暂时不会考虑，如果有好的实施方案，欢迎能提出来。

另外你的问题应该可以通过设置 `prefixCls` 来解决。在 less 覆盖变量 `@ant-prefix: antd2`，使用组件的时候指定相应的 `prefixCls`, `<Button prefixCls="antd2">`。这样 antd2 和  antd3 同时存在的时候应该不会冲突了。
