### ISSUE TITLE
Table hide extra row

### ISSUE THREAD

**Issue by jasonxia23** [ant-design/ant-design#12459]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table hide extra row when the dataSource count is bigger than pageSize, such as, with row collapsing.

### What does the proposed API look like?
Table show extra row even if dataSource count bigger than pageSize

**Comment by yesmeck** [comment]
用详细的描述下你的需求吧

**Comment by jasonxia23** [comment]
如果 dataSource 的数量大于 pageSize，dataSource 不会被完全展示，是否有什么方法可以避免 antd 的这一默认行为

**Comment by yesmeck** [comment]
dataSource 的数量大于 pageSize 就会分页，不想分页设置 `pagination={false}` 即可。

**Comment by jasonxia23** [comment]
如果我需要分页，并且不希望 Table 自动隐藏 dataSource 多出的数据

**Comment by jasonxia23** [comment]
@zombieJ 如果我没理解错，这个实例是针对只有一页数据时候的情况，我的情况是因为页面中会出现行合并，所以实际从后台拿到的 pageSize 和 Table 展示的 pageSize 不一样，比如我想展示10条数据（合并后），那么对于 Table 来说其实不止 10 条，但是如果我把 10 传给 Table 组件，最终只能展示前 10 条。

**Comment by zombieJ** [comment]
为什么需要把 10 传给 Table？Table 本身会自己根据数量分页啊。

**Comment by jasonxia23** [comment]
我的意思就是不希望 Table 自己分页，我认为就像 `hideOnSinglePage` 一样通过提供一个参数让我能够关闭 Table 自己处理分页的逻辑

**Comment by afc163** [comment]
`pagination={false}`
