### ISSUE TITLE
使用Form封装组件时Input无法正常输入

### ISSUE THREAD

**Issue by YanYuanFE** [ant-design/ant-design#12450]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
Ubuntu18、Chrome69、antd3.6.5、react16.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ww1vmpml9l)

### Steps to reproduce
在input中开始输入，输入的值无法正确显示。

### What is expected?
输入值正确显示

### What is actually happening?
输入的值无法正确显示

---
在Item组件中接收了传递的getFieldDecorator作为props，此时无法输入，当把getFieldDecorator改为form传递到Item组件，却可以正常输入。

**Comment by yesmeck** [comment]
`getFieldDecorator` 不是这么用的，参考下文档吧。

**Comment by zombieJ** [comment]
`getFieldDecorator` 用到了 this。不能直接这么用。
