### ISSUE TITLE
Cannot select an option in selection menu. Working on Desktop view not on mobile view

### ISSUE THREAD

**Issue by lanzosuarez** [ant-design/ant-design#12452]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
 "antd": "^3.9.3"  "react": "^16.5.2"  "react-dom": "^16.5.2",

### Reproduction link
[https://git.heroku.com/cloud9-automotive.git](https://git.heroku.com/cloud9-automotive.git)

### Steps to reproduce
You cant test the issue here. dont forget to view it on mobile

https://cloud9-automotive.herokuapp.com/webviews

### What is expected?
To be able to select an option in the selection menu

### What is actually happening?
Cannot select an option

**Comment by zombieJ** [comment]
Remove the `node_module` folder and reinstall.

PS: can't access your git repo.

**Comment by AndreiDuma** [comment]
Can we please reopen this? I confirm the problem described by @lanzosuarez.

**Comment by zombieJ** [comment]
Hi @AndreiDuma , create a new issue if necessary : )

**Comment by zombieJ** [comment]
Hi @AndreiDuma , create a new issue if necessary : )

**Comment by zombieJ** [comment]
Hi @AndreiDuma , create a new issue if necessary : )

**Comment by zombieJ** [comment]
Hi @AndreiDuma , create a new issue if necessary : )

**Comment by zombieJ** [comment]
Hi @AndreiDuma , create a new issue if necessary : )

**Comment by zombieJ** [comment]
Hi @AndreiDuma , create a new issue if necessary : )

**Comment by zombieJ** [comment]
Hi @AndreiDuma , create a new issue if necessary : )
