### ISSUE TITLE
Style missing when writing a library with antd. 

### ISSUE THREAD

**Issue by lzszone** [ant-design/ant-design#12456]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
ubuntu 18.04, chrome 69 , react 16 

### Reproduction link
[https://github.com/lzszone/reproduce_demo)

### Steps to reproduce
I want to write a library which uses `antd` as a `peerDependency`. 
For example, I use the Button and Slider in my library, 
and then I import the library into a project, this project has `antd` as a `dependency`,
I used `Button` component in both the project and library while `Slider` is not, I just use `Slider` in my library,
and the result comes with the Button works fine but the style of Slider is missing. I think `webpack` does not resolve my library

I know that this is not a bug or error, it's something about the `webpack` or the way I should import `antd`,
but I don't know how to deal with it. Help~...

### What is expected?
In the example above, both `Button` and `Slider` has the correct style.

### What is actually happening?
Only the `Button` has style, I guess the `webpack ` does not import the relative class of `Slider`.

---
[reproduce demo](https://github.com/lzszone/reproduce_demo)

**Comment by zombieJ** [comment]
We may not have much time on non-antd issue. For this issue, my suggestion is to let user import antd style inline or ask the question on stackoverflow:
```jsx
import 'antd/dist/antd.css';
```

**Comment by schester44** [comment]
@lzszone Ever find a fix for this?

We're writing a package that uses antd as a peer dependency and including it in an existing antd-based dashboard that uses babel-plugin-import for importing styles.

Everything works but the styles are missing because I assume babel-plugin-import isn't looking at packages in node_modules?

**Comment by lzszone** [comment]
@schester44 Yes, but I don't quite remember the detail... 
I remember it's the `babel-plugin-import` configuration or the RegExp inside the `externals` make my work done.

Take a look at [this config file](https://github.com/lzszone/antd-cropper/blob/master/webpack.config.js) if you need.

**Comment by glebdv** [comment]
Hey, make sure that your versions of antd don't clash in your library - check your yarn lock and make sure that the resolved version is the same as the declared dependency version
