### ISSUE TITLE
TreeSelect with multiple mode, after i search and select a node, tree will expand all nodes automatically, that makes this component very slow

### ISSUE THREAD

**Issue by kc2525** [ant-design/ant-design#12462]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
win7, chrome69.0

### Reproduction link
[https://ant-design.gitee.io/components/tree-select/](https://ant-design.gitee.io/components/tree-select/)

### Steps to reproduce
TreeSelect with multiple mode, after i search and select a node, tree will expand all nodes automatically

### What is expected?
tree won't expand all nodes automatically

### What is actually happening?
tree will expand all nodes automatically

**Comment by kc2525** [comment]
i just found when treeNodeFilterProp equal to 'title', this problem won't show. otherwise, tree will always expand all nodes automatically, just like the offical example

**Comment by zombieJ** [comment]
In coming 3.10.x, the expandedKey of TreeSelect can be controlled.

Branch: https://github.com/ant-design/ant-design/tree/feature
