### ISSUE TITLE
Components that implement "Make it direct" principle

### ISSUE THREAD

**Issue by adamborowski** [ant-design/ant-design#12461]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to follow 'Make it direct' principle which means you see and edit data in the same place. https://ant.design/docs/spec/direct
I can't find any component so I assume there is no one.

### What does the proposed API look like?
something like 

`<DirectEdit onChange=... value=... />`

**Comment by yesmeck** [comment]
It's easy to implement based on the exists components. 😄

**Comment by adamborowski** [comment]
I assumed all things covered by gudelines should have default implementation, due to styling compability
