### ISSUE TITLE
Pagination分页优化建议

### ISSUE THREAD

**Issue by jszjgqq** [ant-design/ant-design#12465]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
设置showQuickJumper为true之后，Input触发onChange为Enter回车才能触发。

### What does the proposed API look like?
希望Input输入框有其他触发onChange的事件，比如blur失焦触发。

**Comment by zombieJ** [comment]
Wrap it: https://codesandbox.io/s/kkq6wwxxyr
