### ISSUE TITLE
Upload Component has dependence on action that isnt used

### ISSUE THREAD

**Issue by developdeez** [ant-design/ant-design#12468]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
reactjs

### Reproduction link
[https://ant.design/components/upload/](https://ant.design/components/upload/)

### Steps to reproduce
Use any upload component. They all require action which even in the demo is stock text (//jsonplaceholder.typicode.com/posts/)
How can I stop the 404 error from showing or the red box around the photo?

### What is expected?
Easy upload using non REST api or Function

### What is actually happening?
Requires mock text to run but still gives CORS errors.

**Comment by zombieJ** [comment]
It's just a demo for upload. You should have your own file service. And if default send action not satisfy your requirement, you can use [customRequest](https://ant.design/components/upload/#customRequest).

**Comment by developdeez** [comment]
That defeats the purpose of using the styled component but yea. thanks :/

**Comment by zombieJ** [comment]
Thanks for reply,
Since Upload component focus on the design instead of backend upload type, provide the customRequest is enough for customize. And also, not every developer need use Upload component by AWS. It's not the good way to support all type of file service in antd.

**Comment by developdeez** [comment]
Eh not really useful info since the switch to the rc-upload didnt show anything. They may work too differently.

Is there some promise or string we can put there to prevent the error? The code about accesses a  site that gives cors errors. Also because this error the box shows red.

**Comment by zombieJ** [comment]
Could you provide a screen shot for it? Thx

**Comment by developdeez** [comment]
Here's the result of providing no action:
![image](https://user-images.githubusercontent.com/13059525/46253245-6dd34400-c42b-11e8-8934-06ad3e1b67d2.png)

result if using demo link:
![image](https://user-images.githubusercontent.com/13059525/46253260-a5da8700-c42b-11e8-9519-01b670441cf7.png)

Code with demo link:
![image](https://user-images.githubusercontent.com/13059525/46253263-b3900c80-c42b-11e8-8393-3bbacd81ec29.png)

**Comment by zombieJ** [comment]
As I said, jsonplacceholder is a a demo. You should change to your own file upload service.
