### ISSUE TITLE
IE 下 对象不支持“startsWith”属性或方法 

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [ant-design/ant-design#12470]
![image](https://user-images.githubusercontent.com/11493796/46244143-59804e80-c40d-11e8-876a-c9cb424553e8.png)

使用情况

![image](https://user-images.githubusercontent.com/11493796/46244153-7fa5ee80-c40d-11e8-93d6-ec6521a3d307.png)
![image](https://user-images.githubusercontent.com/11493796/46244179-aebc6000-c40d-11e8-8cf5-bf617edeb1f9.png)

antd @3.9.3 版本

**Comment by zombieJ** [comment]
用 balbel polyfill 一下
