### ISSUE TITLE
Select 多选模式下的功能请求

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ant-design/ant-design#12472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
多选模式下，当我们从输入框中取消某项时，只有 onChange 和 onDeselect 事件响应，但是有时我们需要获取选项的标签名（lable），不单单是value值，而多选模式下，想要获取选项的标签名就比较麻烦了，希望能在 onChange 的参数中，加入可以获取标签文本的参数。

### What does the proposed API look like?
onChange ( value, selectedOption )

**Comment by yesmeck** [comment]
目前 `onChange` 就是有第二个参数的。
