### ISSUE TITLE
Select 组件的 Option 的 key 和 value 只能设置同一个值 ？

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ant-design/ant-design#12474]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.6

### Environment
谷歌浏览器

### Reproduction link
[https://2x.ant.design/components/select-cn/](https://2x.ant.design/components/select-cn/)

### Steps to reproduce
Select 组件的 Option 的 key，一般设置为 一个对象的 id 值，同时可以忽略 value 不填值，但有时我想分别设置 key 和 value，而这样设置后浏览器就会提示错误，不知道这是不是bug？

### What is expected?
Option  的 key 和 value 可以分别设置，比如我可以把一个对象的 id 赋给 key ，然后把整个对象赋给 value，这样从 onChange 中 获取到的参数将非常方便自由。

### What is actually happening?
对 Option 设置了 value （value 的值就是想要设为某个JSON对象），再设置 key 就没用了，就会报组件的 key 重复的信息。（其实 key 是不重复的）

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12334
