### ISSUE TITLE
TreeSelect 组件两个问题

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ant-design/ant-design#12471]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
谷歌浏览器69.x

### Reproduction link
[https://ant-design.gitee.io/components/tree-select-cn/#header](https://ant-design.gitee.io/components/tree-select-cn/#header)

### Steps to reproduce
一、TreeSelect 基本用法那里只能选择一次，再选择就不行了。
二、基本用法示例，单选模式，为什么下拉中多出了个搜索框，而不能直接在输入框中输入要查找的项，感觉下拉中出现的搜索框是多余的，
但右侧的多选模式示例，反而可以直接在输入框中输入要查找的项，这让人很不解。

### What is expected?
单选模式的下拉中没有搜索框。

### What is actually happening?
基本示例那里不能再次选择项，单选模式的下拉中有搜索框。

---
如果第二个问题，算是个bug的话，那么多选模式也应该在下拉中出现个搜索框，并且不能直接在输入框中输入要查找的内容。

**Comment by zombieJ** [comment]
1. 已经修复了，gitee 没有更新：https://ant.design/components/tree-select-cn/#header
2. 设计如此，你的意见收到了，会权衡一下~
