### ISSUE TITLE
希望 InputNumber  能加入 onPressEnter 事件。

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ant-design/ant-design#12476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Input 组件有 onPressEnter 事件，而 InputNumber  没有，但是很多时候也习惯在输入数字时就按下回车键。

### What does the proposed API look like?
InputNumber  能有个 onPressEnter  事件。

**Comment by afc163** [comment]
You can use onKeyDown now.
