### ISSUE TITLE
Upload 为什么要规定服务端返回 JSON？

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#1248]
https://github.com/ant-design/ant-design/blob/develop-1.0.0/components%2Fupload%2Findex.jsx#L115-L124

我看  response JSON.parse 了后面也没用到呀，杯具的阿里云 OSS 返回的 response  是空的。

**Comment by afc163** [comment]
这是一个约定，无法返回标准的 JSON 格式，视为出错。这样组件可以帮助用户直接解析返回数据。不用每次都去 `JSON.parse` 了。

欢迎帮助我们改成更兼容的方案。

**Comment by yesmeck** [comment]
如果 response 的 Content-Type  是 application/json 再去 JSON.parse 怎么样？

**Comment by afc163** [comment]
response 有可能是个字符串，怎么会有 `Content-Type`，考虑 IE8/9 的情况。

**Comment by yesmeck** [comment]
我指的是 response header 里的 Content-Type

**Comment by afc163** [comment]
有可能是别的：https://github.com/react-component/upload#download-popup-problem

不过你可以在 ajax 模式下加这个判断。

**Comment by yesmeck** [comment]
其实如果能允许自己传入 onSuccess 也可以解决这个问题。

**Comment by yesmeck** [comment]
> 这样组件可以帮助用户直接解析返回数据。不用每次都去 JSON.parse 了。

现在的代码好像并没有做到这一点。

**Comment by afc163** [comment]
好像是的，我误解了。

**Comment by yesmeck** [comment]
> 无法返回标准的 JSON 格式，视为出错

所以这里只是要做这样一个约定是吗？

**Comment by afc163** [comment]
在 IE 下试了试，去掉格式限制好像对错误判断也没问题。

**Comment by yesmeck** [comment]
:+1:

**Comment by simi--** [comment]
因为 react 0.13.x，现在我使用的是 antd 0.9.5，找了半天，我没有找到在哪里有规定服务端返回的 JSON 格式啊。。

**Comment by benjycui** [comment]
`antd@0.9.5` 已经不支持了，建议升级或者自己看源码吧。。

**Comment by simi--** [comment]
@benjycui 我自己看源码吧，谢谢。
