### ISSUE TITLE
Linux building tabs component has a bug

### ISSUE THREAD

**Issue by wanliyunyan** [ant-design/ant-design#12487]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
linux windows chrome69

### What is expected?
希望位置在正下方，3.8.4版本没有问题，windows也没有问题，当3.9.3在linux上打包就有这个问题，这个问题我不出重现的连接。。。

### What is actually happening?
ant-tabs-ink-bar has a wrong location
![image](https://user-images.githubusercontent.com/10751248/46256127-24413280-c4d9-11e8-81d4-13f8a2c8668e.png)

**Comment by afc163** [comment]
需要你提供可以重现的例子（可以用 github repo 提供），否则无法排查。

**Comment by wanliyunyan** [comment]
@afc163 3.10.0 版好使了，不偏了。。。。
