### ISSUE TITLE
表单验证，在validating状态下，Input框无法显示验证的状态

### ISSUE THREAD

**Issue by stkevintan** [ant-design/ant-design#12484]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
antd 3.9.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7m9l1mrv0x)

### Steps to reproduce
demo: https://codesandbox.io/s/7m9l1mrv0x  
当在输入框输入字符时，1s的delay函数过程中输入框没有相应的validating的交互

### What is expected?
Input框显示如<https://ant.design/components/form-cn/#components-form-demo-validate-static>所示的validating状态

### What is actually happening?
没有validating状态

**Comment by yesmeck** [comment]
这个状态是需要你自己去加的。参考 `isFieldValidating`
