### ISSUE TITLE
table header text overlap icon

### ISSUE THREAD

**Issue by xiaoyu-tamu** [ant-design/ant-design#12495]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
macos

### Reproduction link
[https://user-images.githubusercontent.com/33362998/46311782-ddab1100-c588-11e8-80ac-a37deda6159a.png](https://user-images.githubusercontent.com/33362998/46311782-ddab1100-c588-11e8-80ac-a37deda6159a.png)

### Steps to reproduce
set table column align to right

### What is expected?
it should has correct padding right

### What is actually happening?
overlapping

---
only @ 3.10.0

**Comment by rhilliard1976** [comment]
Here is the link to the forked reproduction. If you have any more questions, please let me know. 

[![Edit antd reproduction template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rm973k093m)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/12552
