### ISSUE TITLE
根据数组动态生成Menu组件，defaultOpenKeys初次正常，数组源切换后失效

### ISSUE THREAD

**Issue by liekkas** [ant-design/ant-design#1249]
## What you did

使用数组自动生成菜单项，并且默认打开第一个菜单组，默认选中第一个菜单组的第一个子菜单
## What you would like to happen

默认正常打开，切换数组源后也能正常默认打开

## What actually happened

第一次加载界面表现正常，然后切换数组源后，默认打开(defaultOpenKeys)失效，

## Online demo
http://codepen.io/liekkas/pen/Wwomoj

## Environment Information

- The version of antd: 0.12.12
- Your operating system and it's version: OSX 10.11.3
- Your browser and it's version: Chrome49.0.2623.87(64-bit)

**Comment by afc163** [comment]
这是对的，defaultOpenKeys 只有组件初次渲染时生效，你可以使用受控属性 `openKeys`。

受控属性和非受控属性区别请研习：http://facebook.github.io/react/docs/forms.html#controlled-components
