### ISSUE TITLE
use svg instead of icon-font

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#1250]
https://github.com/blog/2112-delivering-octicons-with-svg

**Comment by afc163** [comment]
1. IE8
2. Can't set style like normal text.

**Comment by yiminghe** [comment]
1. react will not support ie8..
2. div + background

**Comment by benjycui** [comment]
IE8: 虽然 React@0.15.0+ 不支持 IE8，但 antd 可以同时兼容 0.14.0 和 0.15.0+ 。

**Comment by yiminghe** [comment]
1.0 以后不考虑 ie8 了，ie8 根本跑不起来稍微复杂的应用

**Comment by plandem** [comment]
also can be performance issue. svg slower than font

**Comment by kvetoslavnovak** [comment]
My experiences with icon-fonts are also better than with svg.

**Comment by afc163** [comment]
http://svgicons.sparkk.fr/

**Comment by afc163** [comment]
http://leungwensen.github.io/svg-icon/#ant
