### ISSUE TITLE
Additional button colours

### ISSUE THREAD

**Issue by fsimkovic** [ant-design/ant-design#12504]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Enables more button style defaults than currently implemented. Maybe support all bootstrap styles https://getbootstrap.com/docs/4.0/components/buttons/

### What does the proposed API look like?
```
<Button type="secondary">Secondary</Button>
<Button type="success">Success</Button>
<Button type="warning">Warning</Button>
<Button type="info">Info</Button>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4770#issuecomment-278217817

**Comment by Sanan4li** [comment]
More than 6 years and still no secondary button in ant d.
