### ISSUE TITLE
Grid not responsive

### ISSUE THREAD

**Issue by SyncroIT** [ant-design/ant-design#12507]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Actually I find the grid useless because if I fill all the 24 columns in a row, other columns won't wrap on a new line. Why should I use responsive props if the columns won't wrap? 

Example:
I want to display a Search Bar and a Button. On XS devices I want the Search Bar of 24 columns (1 line) and the Button on another line (other 24 columns), but on SM, LG, and XL devices I want these 2 components appear on same line (Search Bar of 12 columns and Button of 12 columns). On other frameworks like Bootstrap this would work fine, but with Ant design this doesn't work. In the first case (XS devices) Ant Design will try to wrap both columns in a single row instead of displaying them on 2 different lines.

### What does the proposed API look like?
Just like Bootstrap, make the columns wrap on a new line.

**Comment by ycjcl868** [comment]
you can see the [grid-responsive](https://ant.design/components/grid/#components-grid-demo-responsive) doc, and add `type="flex"` in `Row` Component. detail in [demo](https://codesandbox.io/s/61o75x034w)

**Comment by marharyta** [comment]
@ycjcl868 any way you can update documentation? It seems it is missing from the docs. Thank you!

**Comment by aanu1994** [comment]
@ycjcl868 thanks for showing us the `type="flex"` but what can we do if you then need to add some separation between the flexed columns. Right now in a Row I have 2 Cols, flex has helped them to stack ontop of each other but now the buttons inside the cols are touching. Is there a way to add a padding when they flex?

**Comment by aanu1994** [comment]
The workaround I have done for this is in a css file that adds more instructions to the `ant-col-xs-24` class.
```
.ant-col-xs-24 {
  padding-top: 4px;
}
```

**Comment by mgrama** [comment]
@aanu1994 скажите, а вы нашли решение данной проблемы?

**Comment by mgrama** [comment]
@aanu1994 have you find the solution? I still have a question how to set "offset" params for mobile view.
