### ISSUE TITLE
Use in Create React App 2.0

### ISSUE THREAD

**Issue by NotAmaan** [ant-design/ant-design#12500]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Since CRA 2.0 has officially released, Ant Design's solution of using react-app-rewired would not work anymore since it doesn't support CRA 2.0 (https://github.com/timarney/react-app-rewired/issues/162#issuecomment-417872507)

We've started trying out CRA 2.0 for our apps and would be using the longer import syntax for now i.e. `import Button from 'antd/lib/button'` but it would be great if there was a workaround to get the easier syntax back i.e. `import Button from 'antd'`

### What does the proposed API look like?
No proposals.

**Comment by bodaz** [comment]
since `create-react-app` and `ant-design` are two popular React projects in the ecosystem, this issue should have a higher priority than usual

**Comment by afc163** [comment]
I test the https://ant.design/docs/react/use-with-create-react-app step by step with create-react-app@2.0 and it works pretty well 😃. Updated the newest source code to https://github.com/ant-design/create-react-app-antd/commit/0399f45b52662325be3cff597bb57804b8f71193 and welcome to try it.

**Comment by gudh** [comment]
@afc163 

However in https://github.com/timarney/react-app-rewired home page, it says
> ⚠️ ⚠️This repo doesn't support CRA 2.0

I worry that it may break in the future

**Comment by afc163** [comment]
https://github.com/FormAPI/craco-antd seems pretty cool~
