### ISSUE TITLE
add support for srcset in the Avatar component.

### ISSUE THREAD

**Issue by deviantfero** [ant-design/ant-design#12516]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes you need to have a fallback URL for an avatar image, HTML5's srcset provides just that, it's a simple addition to the Avatar component that would be useful.

### What does the proposed API look like?
```
<Avatar src={fallbackSrc} srcset={actualSrc} {...otherProps}/>
```

**Comment by zombieJ** [comment]
PR merged in feature branch: https://github.com/ant-design/ant-design/pull/12525
