### ISSUE TITLE
the expandable rows are duplicating when left column is fixed

### ISSUE THREAD

**Issue by jadelmir** [ant-design/ant-design#12513]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.3

### Environment
macOS High Sierra V10.13.6 , browser chrome ,react 16.2

### Reproduction link
[https://codepen.io/Jayjay-em/pen/BqKYZX?editors=001](https://codepen.io/Jayjay-em/pen/BqKYZX?editors=001)

### Steps to reproduce
I have a table with a fixed left column, 
i added the expandable row the same from the website https://ant.design/components/table/  @Nested Table

### What is expected?
i expect to see a clear table independent from the left fixed header 

### What is actually happening?
I see a duplicate of the expandable rows, one in the left fixed header and one in the table too

**Comment by zombieJ** [comment]
Fixed columns needs mapping the column but `expandedRowRender` makes expanded content share the row. It's the fixed column limitation.
If want to merge fixed with expanded, you'd better use as tree: https://codesandbox.io/s/4xj9yo1j3x

**Comment by ayush17** [comment]
@zombieJ  Hey in your code as a tree structure the rest of the columns are not showing for an expanded row. How to show this?
