### ISSUE TITLE
需求：使用文件上传的时候，当beforeUpload返回false的时候，不需要展示上传的文件列表

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#12517]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
版本：3.9.0
使用场景：
通过beforeUpload验证文件的类型时，返回false的时候，也能将当前选择的文件名字展示出来。实际上我是不需要的

### What does the proposed API look like?
返回false，不展示文件名

**Comment by zombieJ** [comment]
Duplicate of #11968
