### ISSUE TITLE
DatePicker input readonly mode or onInpute interface

### ISSUE THREAD

**Issue by Kokksya** [ant-design/ant-design#12512]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like to forbid my users use Input in datepicker. Could you please provide some solution ?

### What does the proposed API look like?
props for component:   inputReadonly = {true|false}

**Comment by afc163** [comment]
Sorry, we may not provide this feature now.
