### ISSUE TITLE
this.form.props is undefined

### ISSUE THREAD

**Issue by pandoracat** [ant-design/ant-design#12526]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
react-16.5, Typescript 3.x

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9ywj6zl6xw)

### Steps to reproduce
copy cod and run npm run start

### What is expected?
For this code:
```Typescript
const { getFieldDecorator, getFieldsError, getFieldError, isFieldTouched } = this.props.form;
```
this.props.form is not undefined.

### What is actually happening?
For the above code, this.props.form is undfined.

**Comment by afc163** [comment]
https://codesandbox.io/s/8xrj2zk86l
