### ISSUE TITLE
Icon not spinning with "spin" attribute

### ISSUE THREAD

**Issue by tylik1** [ant-design/ant-design#12522]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Google Chrome latest version

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3197pjvxx1)

### Steps to reproduce
Import only icon styles:
import "antd/lib/icon/style/index.css";

### What is expected?
Icon should spin, without need to import all styles, not related to icon

### What is actually happening?
Icon is not spinning

**Comment by tylik1** [comment]
Also all other styles for icon are absent.  antd/lib/icon/index.less is empty

**Comment by afc163** [comment]
The styles of is here: https://github.com/ant-design/ant-design/blob/master/components/style/core/iconfont.less

check https://codesandbox.io/s/3197pjvxx1

**Comment by Druux** [comment]
@tylik1 Did you manage to fix this? Facing the same problem right now :/

**Comment by tylik1** [comment]
@Druux yes, i think i've manually imported the styles pointed above 
https://github.com/ant-design/ant-design/blob/master/components/style/core/iconfont.less

**Comment by jimmy-e** [comment]
You can import the necessary stylesheet like this:

via js:
`import "antd/lib/style/index.css";`

via less:
`@import "~antd/lib/style/index.less";`
