### ISSUE TITLE
Table组件的loading设置delay无效

### ISSUE THREAD

**Issue by 624220042** [ant-design/ant-design#12539]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
mac、chrome69，react16

### Reproduction link
[https://ant.design/docs/react/introduce](https://ant.design/docs/react/introduce)

### Steps to reproduce
<Table" size='middle' bordered
                columns={columns}
                dataSource={dataSource}
                rowKey={rowKey}
                loading={{
                    delay: 500,
                    spinning: loading
                }}
                style={style}
                onChange={onPageChange}
                pagination={pagination}
                scroll={{x: tableWidth}}
            />

### What is expected?
支持delay

### What is actually happening?
不支持delay

**Comment by zombieJ** [comment]
看起来没问题：https://2x38956z3j.codesandbox.io/

**Comment by 624220042** [comment]
delay
Specifies a delay for loading state. If spinning ends during delay, loading status won't appear.
现在的情况是，设置delay为5000、spinning为true，然后过1000后设置spinning为false，正常情况下不应该显示loading，但实际情况是5000后居然还是loading了

**Comment by nuintun** [comment]
@zombieJ 

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/40ljpnk2ww)
