### ISSUE TITLE
table的columns未设置sorter，依然可以点击表头触发onChange事件进行降序排序

### ISSUE THREAD

**Issue by Ma-Yi** [ant-design/ant-design#12532]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qvo46mvvv6)

### Steps to reproduce
点击重现链接的name列，下方会显示相关提示

### What is expected?
没有设置sorter的列，表头不应该可点击和触发onChange

### What is actually happening?
依然可以点击表头触发onChange事件进行降序排序

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/12515

**Comment by m26597** [comment]
@afc163 这个问题什么时候更新版本？周六项目组检验成果

**Comment by afc163** [comment]
https://ant.design/changelog-cn#%E5%8F%91%E5%B8%83%E5%91%A8%E6%9C%9F

**Comment by m26597** [comment]
这个算是紧急的bug嘛？
修订版本号：每周末会进行日常 bugfix 更新。（如果有紧急的 bugfix，则任何时候都可发布）

**Comment by afc163** [comment]
属于日常。

**Comment by m26597** [comment]
好吧
