### ISSUE TITLE
InputNumber对于输入框焦点处理的问题

### ISSUE THREAD

**Issue by iambluebird** [ant-design/ant-design#1253]
在ANTD组件中的InputNumber是从react-component组件库下的rc-input-number派生来的，而rc-input-number在处理focus的时候跟react官方文档里描述的不大一致，是直接在虚拟DOM里进行的focus操作，浏览器执行的时候会报错，找不到focus方法。

react-component/input-number/src/InputNumber.js
代码第70行和第215行，两句

this.refs.input.focus();

修改成

this.refs.input.getDOMNode().focus();

需要在真实的DOM控件下去设置焦点

**Comment by benjycui** [comment]
请使用 React@0.14.0+

**Comment by iambluebird** [comment]
thanx，看文档的时候图方便直接看的中文的官网，没注意两边版本不一致，中文这边还是在13.。。。
