### ISSUE TITLE
InputNumber设置了formatter和parser导致了placeholder属性失效

### ISSUE THREAD

**Issue by HuYuee** [ant-design/ant-design#12547]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
chrome浏览器版本69.0.3497.81

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4zkyoj1j97)

### Steps to reproduce
InputNumber控件在设置了formatter和parser属性之后placeholder参数失效

### What is expected?
希望placeholder参数能有效

### What is actually happening?
placeholder参数失效

**Comment by zombieJ** [comment]
https://codesandbox.io/s/p9p489790m
