### ISSUE TITLE
Badge & Tag components throw "Error: A DOM element reference is required" in Jest snapshot tests

### ISSUE THREAD

**Issue by annmedvid** [ant-design/ant-design#12545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
10.13.4, Version 69.0.3497.100 (Official Build) (64-bit), react@16.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3r5l5wzm0p)

### Steps to reproduce
run test

### What is expected?
New snapshot showed OR test passed

### What is actually happening?
Test fails with error - Error: A DOM element reference is required

**Comment by zombieJ** [comment]
Cause internal animation use css operation. Mock render not polyfill this. You can ref:
* https://github.com/ant-design/ant-design/tree/master/tests
* https://github.com/react-component/tree/tree/master/tests
