### ISSUE TITLE
create icon for airport (plane landing, taking off or just flying)

### ISSUE THREAD

**Issue by mlg87** [ant-design/ant-design#12543]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i feel a lot of users could benefit from this addition

### What does the proposed API look like?
`<Icon type="airplane" theme="outlined" />`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-icons/issues/26#issuecomment-435328587
