### ISSUE TITLE
更新记录总是有一些单词拼写错误

### ISSUE THREAD

**Issue by chinawzc** [ant-design/ant-design#12557]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
浏览器版本

### Reproduction link
[https://ant.design/changelog-cn](https://ant.design/changelog-cn)

### Steps to reproduce
decilamSeparator 、 modal 等等

### What is expected?
错误避免

### What is actually happening?
错误单词错误引导

**Comment by afc163** [comment]
`decilamSeparator` is fixed in 5458177 and PR is welcome~

<img width="537" alt="image" src="https://user-images.githubusercontent.com/507615/46662381-dff71600-cbed-11e8-9bc1-6142b9160fa7.png">

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/12559
