### ISSUE TITLE
when table in form，pagination show is error

### ISSUE THREAD

**Issue by fangaofeng** [ant-design/ant-design#12554]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
react， chrome版本 69.0.3497.81

### Reproduction link
[https://codepen.io/fangaofeng/pen/xygzLG](https://codepen.io/fangaofeng/pen/xygzLG)

### Steps to reproduce
browser  https://codepen.io/fangaofeng/pen/xygzLG
when table in form， pagination show with showSizeChanger and showQuickJumper

### What is expected?
QuickJumper show inline 

### What is actually happening?
QuickJumper show is vertical

**Comment by zombieJ** [comment]
Hi @fangaofeng , in which case you need put a table in a Form?

**Comment by fangaofeng** [comment]
Yes,i have a large form，some data selected  from table by user.

**Comment by fangaofeng** [comment]
thank you
