### ISSUE TITLE
table 组件 sort 样式

### ISSUE THREAD

**Issue by jiameng123** [ant-design/ant-design#12552]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
chrom 69.0.3497.100,   react 16.5.2 

### Reproduction link
[https://codepen.io/jiameng123/pen/yRgvaQ](https://codepen.io/jiameng123/pen/yRgvaQ)

### Steps to reproduce
设置table 属性size ='small' ，设置Columns 内属性 sorter，同时设置align ='right'

### What is expected?
文字不与排序图标重叠

### What is actually happening?
文字与排序图标重叠

**Comment by afc163** [comment]
...这种情况比较蛋疼。

**Comment by jiameng123** [comment]
@afc163 好像是设置small时td的paddding由16变成8px 这样

**Comment by afc163** [comment]
不是的，现在位置用 absolute 实现的。我要重新看看怎么搞比较好。

**Comment by sillyfeng** [comment]
貌似还不行是吧？ @xiaoyu-tamu  @afc163

**Comment by Jerry-FD** [comment]
![image](https://user-images.githubusercontent.com/19424989/46943017-3dcda700-d0a1-11e8-9f30-82b1599e08ad.png)
不只是size为small的时候
https://riddle.alibaba-inc.com/riddles/a323f3cc
