### ISSUE TITLE
Cascader 自定义字段名后，选项无法显示

### ISSUE THREAD

**Issue by linxiaojialin** [ant-design/ant-design#12558]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.1

### Environment
Windows10，Google Chrome 69.0.3497.100。{   "dependencies": {     "react-dom": "16.3.2",     "react": "16.3.2",     "antd": "3.4.1"   } }

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3q11mk3mo6)

### Steps to reproduce
点击Cascader组件

### What is expected?
正常显示级联选择选项

### What is actually happening?
没有显示选项；报错信息：Warning: Each child in an array or iterator should have a unique "key" prop.

---
因项目已上线，版本固定，不可随意升级。
请问这是什么原因导致的呢？在不升级版本的情况下可以解决吗？

**Comment by afc163** [comment]
3.4.1 不支持这个属性：https://ant.design/changelog-cn#3.5.0
