### ISSUE TITLE
关于form表单动态验证问题

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#12560]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
antd3.10.0 chrome 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wqkm0l503k)

### Steps to reproduce
先说明一下重现链接的问题，首先打开页面，有一个按钮，按钮会传递一个checkNick给一个Modal，但是我的Modal 又是根据 checkNick 的值来进行对age 和 nickname 两个输入框展示，然后两个输入框都要进行required true,，其实也就想要做的到是如果checkNick为true ，那么就只验证nickname，否者验证age，但是结果是age 不会渲染，但是也进行了验证。

重现步骤
1：点击按钮，弹出modal。
2：在nickname输入框，输入内容。
3：单击check按钮，这个时候会报please input age。但是age这个组件并没有。

我换衣是第一次加载的时候会渲染出age，然后数据写入到form里面去了。后面就算重新render之后，虽然没有age 但是并不会从form里面移除，那么我的问题是如果手动移除。

### What is expected?
希望给一个移除API，或者form 能自己检测包括的组件是否已经有删除或者增加。

### What is actually happening?
出现没有显示的组件也会被验证。

**Comment by zombieJ** [comment]
加了个 setTimeout 就正常了：https://codesandbox.io/s/r7447vnrw4

感觉是 form 初始化的时候代码逻辑有什么问题，得再调试一下。

**Comment by xgj1988** [comment]
@zombieJ  谢谢

**Comment by xgj1988** [comment]
@zombieJ  你好，，我的给的实例和我实际生产环境不一样，我其实不是点击按钮改变状态，我是在一个table 里面，点击了编辑某条记录。。所以你的这个做法还是不能解决我的问题。

**Comment by zombieJ** [comment]
原因是 age 在 Modal 没有创建出来的时候调用不到 saveRef 结果就只注册没有删除：https://github.com/react-component/form/blob/master/src/createBaseForm.js#L325

感觉不太好调整，还得看看

**Comment by xgj1988** [comment]
@zombieJ  大哥，，那么怎么搞呢，，这个问题。

**Comment by xgj1988** [comment]
@zombieJ  我在生产环境，偶尔还是 有这个问题。。。很奇怪。

**Comment by RaoHai** [comment]
这个是不兼容改动，为啥发了个 patch ？

真不一定所有 Field 都显示的。
比如表单某个字段，在某个角色的时候显示控件，其他角色的时候不展示，内部逻辑处理。
往常的写法，getFieldDecorator / setFieldsValue 啥的都一样写，只在 render 里做处理就行了。
这个改动之后，这个场景下，整个 Form 写法都变了。

**Comment by zombieJ** [comment]
@RaoHai ，以前的逻辑里。Field 从 render 到不 render 也是会清除的。

**Comment by TotooriaHyperion** [comment]
> @RaoHai ，以前的逻辑里。Field 从 render 到不 render 也是会清除的。

但是这里有个情况就是某些复杂表单希望手动控制渲染流程，某些认为无需渲染的节点会进行优化，这就会导致目前的流程错误地清空了依然存在于页面上的field。

**Comment by zombieJ** [comment]
@TotooriaHyperion , 
之前这种不删除的行为是一个 bug。会导致如果注册的 field 存在 require 但是页面没有渲染这个 Field 导致 Form 验证无法通过。
如果仍然想保留不渲染预置的效果，可以在 render 里调用一下 getFieldDecorator 注册一下。

**Comment by TotooriaHyperion** [comment]
> @TotooriaHyperion ,
> 之前这种不删除的行为是一个 bug。会导致如果注册的 field 存在 require 但是页面没有渲染这个 Field 导致 Form 验证无法通过。
> 如果仍然想保留不渲染预置的效果，可以在 render 里调用一下 getFieldDecorator 注册一下。

进行的优化恰恰是为了不调用render，所以没有地方可以进行这样的操作。
每一次对form的更新，要求所有field都进行一次render难道就是合理的吗？那些没有任何修改的field也要进行render吗？

**Comment by zombieJ** [comment]
这里总结一下吧，form 的逻辑是如果调用了 getFieldDecorator 就注册一个 field。当这个 field 元素从 dom 里删除就会把对应的 field 删除。
但是存在一个 bug，是如果这个 filed 没有在 dom 上 render 会导致下次不使用的时候也就不会触发删除。使得这个 field 无法被回收掉。对应到这个 issue 就是注册了一个 require 的 field 结果没有被回收导致 form 无法验证通过。 

对应 Form 而言，已经存在的 field 对应的方法会被 cache。不会应为 getFieldDecorator 被调用就反复创建新的绑定事件。因而没有必要对此进行优化。

此外，对于一个 form 而言。它的目的是进行表单绑定。如果一个组件并不会实际被渲染，那么也不应该放到 form 里。不应该把 form 当成一个 store 来使用。

**Comment by TotooriaHyperion** [comment]
@zombieJ 
是一个实际被渲染的组件，由于没有重复渲染，导致其field被清空。而非是一个没有被渲染的组件。

**Comment by afc163** [comment]
PR 和重现最好一起提上来，这样方便综合判断。另外最好补上用例，这个组件有点复杂了，不留底后面不敢动了。

**Comment by zombieJ** [comment]
好呀，万分欢迎哈 : )

**Comment by TotooriaHyperion** [comment]
issue https://github.com/react-component/form/issues/205
bug重现 https://github.com/TotooriaHyperion/rc-form-bug
bug修复 https://github.com/react-component/form/pull/206

**Comment by xgj1988** [comment]
@TotooriaHyperion 我这边这么改呢？？

**Comment by TotooriaHyperion** [comment]
@xgj1988 已经在204里修复了吧，按照你的描述不应该会有问题啊。。

**Comment by xgj1988** [comment]
@TotooriaHyperion  我微信加你了。。你同意一下嘛。。PrincessSniper 这个是你微信号撒。。还是有问题。

**Comment by TotooriaHyperion** [comment]
@xgj1988 emm我不是antd的维护者。。我是路人来着。。你问 @zombieJ 把= =

**Comment by xgj1988** [comment]
@zombieJ  就这个，https://codesandbox.io/s/wqkm0l503k 而且实际项目必这个复杂，，如果你能加我QQ,或者微信，或者钉钉可以远程看看。

**Comment by TotooriaHyperion** [comment]
@zombieJ 
https://codesandbox.io/s/1z7oqj741l

这个是他的例子的真正的情况。你在有age的时候check，nickname会error，在有nickname的时候check，age会error。

他每次渲染都执行了getFieldDecorator
而antd的form是在这个函数中添加field的，也就是说他的问题不是没有回收，而是每次都生成了全部。

也就是说 @xgj1988 的expect behavior其实是我之前PR里提到的，“实际被渲染出来的内容，才是应该被validate的内容”所一致的。

之前跟你讨论过了，不过我还是不太确定到底是我的看法对还是你的对。你参考一下他这个应用场景觉得呢？

**Comment by xgj1988** [comment]
@zombieJ  现在的问题就是，我有一个switch 按钮，在切换的时候会有不同的 formitem ，导致每次用户在点击编辑的时候，我都要让他先点击两下switch ，不然form提交就报错。所以我说能远程帮我看一下你就知道了。

**Comment by TotooriaHyperion** [comment]
@zombieJ 

目前的behavior：
initial：初始化所有field（包括没被渲染出来的）
change：回收没有渲染的field
outcome：第一次会validate age和nickname，但是切换一次就不会了，因为切换的时候把没render的那个回收掉了，再切换回来才能正常使用。

这就是 @xgj1988 遇到的问题了。

**Comment by xgj1988** [comment]
@TotooriaHyperion  就是你的这个意思

**Comment by zombieJ** [comment]
@xgj1988 @TotooriaHyperion，
能上个 gif 吗？https://codesandbox.io/s/1z7oqj741l 这个例子我 console 看是好的。

**Comment by zombieJ** [comment]
@ztplz ，别着急重构，rc-form 里面有些东西要去掉。

**Comment by xgj1988** [comment]
@zombieJ  什么时候可以解决嘛。

**Comment by zombieJ** [comment]
@xgj1988 ，你能给个 gif 吗？
