### ISSUE TITLE
NPM package for each component

### ISSUE THREAD

**Issue by aa6864** [ant-design/ant-design#12568]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm thinking of using some of the components in the ant design, for example, the date-picker but prefer to keep the size of my app small and therefore was wondering if it is possible to have a NPM package for each component so that users just get the component that they are interested in. Please let me know what you guys think? and thank you for the great work.

### What does the proposed API look like?
Maintaining a package for each component using package.json

**Comment by afc163** [comment]
http://github.com/react-component/
