### ISSUE TITLE
Do not support new way to add refs and use refs for Input and Select component

### ISSUE THREAD

**Issue by thinksource** [ant-design/ant-design#12565]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
react 16.5.2

### Reproduction link
[https://github.com/thinksource/newrest/blob/master/static/src/js/Manager.js](https://github.com/thinksource/newrest/blob/master/static/src/js/Manager.js)

### Steps to reproduce
According to document https://reactjs.org/docs/refs-and-the-dom.html#creating-refs
The new way to refs is:
this.myRef = React.createRef();
when it rend，should like:
```
rend(){
<Input  ref={this.myRef}/>
}
```
But when I want to get the value of Input or Select

I try to:
console.log(this.myRef.current.value);

### What is expected?
the value of Input or Select

### What is actually happening?
this.myRef.current is object like:
```
t {props: {…}, context: {…}, refs: {…}, updater: {…}, saveSelect: ƒ, …}
context: {}
props: {style: {…}, children: Array(2), prefixCls: "ant-select", showSearch: false, transitionName: "slide-up", …}
rcSelect: t {props: {…}, context: {…}, refs: {…}, updater: {…}, onInputChange: ƒ, …}
refs: {}
renderSelect: ƒ (n)
saveSelect: ƒ (n)
state: null
updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}
_reactInternalFiber: Na {tag: 2, key: null, type: ƒ, stateNode: t, return: Na, …}
__proto__: v
```
do not have value props

---
Does Antd component support the old way string ref and get the value?

**Comment by thinksource** [comment]
According to your document https://ant.design/components/select/

the select should have value props.
But After check the dict, I find your value is  : 
```
ref.rcSelect.state.value
```
I think you should change the document you provid.

**Comment by minran** [comment]
ant component is a object, ref need a document,but isn`t

**Comment by minran** [comment]
component need ReactDom.findDOMNode() get DOM

**Comment by Minhpd87** [comment]
for Input the value should be
`ref.current.state.value`

**Comment by btegenbosch** [comment]
I don't get why `ref.current.state.value` is a valid option as it will force you to rely on implementation details of the component.

**Comment by monolithed** [comment]
The same problem.... how to get `current.target` to call native events?

**Comment by yonatanmn** [comment]
Any solution valid for antd@4 ?

**Comment by medeiroshudson** [comment]
Need some solutions for v4

**Comment by findli** [comment]
it should be reopened. how get value throught react ref?

**Comment by DavidODonovan** [comment]
bump! Having the same issue: how to get the value of a select using a ref?!

**Comment by CodHeK** [comment]
use `InputRef.current.input`

**Comment by hex0cter** [comment]
👀

**Comment by manoj-nagarro** [comment]
> for Input the value should be
> `ref.current.state.value`

Not working as expected. This is returning previous value.
Ex- Enter ab but `ref.current.state.value` retuns a, Enter abc but `ref.current.state.value` returns ab.

@CodHeK reference worked like charm - InputRef.current.input.value

**Comment by itsalb3rt** [comment]
Any example ? About `InputRef.current.input.value`

**Comment by sudhir4ev** [comment]
> Any example ? About `InputRef.current.input.value`

from ant docs. 
https://github.com/ant-design/ant-design/blob/ea6a8012908bed3dafce3b549906bd0e272d12e2/components/input/Search.tsx#L73

but this does not play well with typescript. `InputRef` type is not exported from ant.

Tried and failed options.
```ts
const inputEl = useRef(null);
...
console.log(inputEl.current?.input?.value); // TS2339: Property 'input' does not exist on type 'never'.
```

```ts
import { InputRef } from 'antd'; // TS2305: Module '"antd"' has no exported member 'InputRef'.
...
const inputEl = useRef<InputRef>(null);
...
console.log(inputEl.current?.input?.value);
```

`"antd": "^4.18.3",`
