### ISSUE TITLE
antd编译报错问题

### ISSUE THREAD

**Issue by mei50923** [ant-design/ant-design#12561]
![image](https://user-images.githubusercontent.com/14801491/46666468-6402cb00-cbf9-11e8-9575-aa48fc895396.png)
![image](https://user-images.githubusercontent.com/14801491/46666556-8c8ac500-cbf9-11e8-9b9d-b84231a28ce7.png)
是不是应该改成 import TransitionEvents from 'css-animation/lib/Event';

**Comment by aiportal** [comment]
![111](https://user-images.githubusercontent.com/878799/54028454-04c4d900-41e0-11e9-8642-e1ed43452e5d.PNG)

**Comment by afc163** [comment]
https://unpkg.com/css-animation@1.5.0/es/

There it is.
