### ISSUE TITLE
Table column 未设置 sorter 的列单击会触发排序事件

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#12569]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
WIN10 - Chome69 - React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lrkkpx0x0q)

### Steps to reproduce
单击表头中的列

### What is expected?
未设置 sorter 不触发排序事件

### What is actually happening?
触发了排序事件

![table sorter](https://user-images.githubusercontent.com/1730277/46708658-563d5c00-cc72-11e8-92c8-162d865a885f.gif)

**Comment by afc163** [comment]
Fixed in #12515
