### ISSUE TITLE
Some Layout examples styles are broken

### ISSUE THREAD

**Issue by eduludi** [ant-design/ant-design#12563]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
any

### Reproduction link
[https://ant.design/components/layout/](https://ant.design/components/layout/)

### Steps to reproduce
Go to the layout docs.

### What is expected?
All examples should have Ant Design styles.

### What is actually happening?
The following examples are broken:

- [Sider]( https://ant.design/components/layout/#components-layout-demo-side)
- [Fixed Header](https://ant.design/components/layout/#components-layout-demo-fixed)
- [Fixed Sider](https://ant.design/components/layout/#components-layout-demo-fixed-sider)

**Comment by afc163** [comment]
Redeployed and fixed, thx for reporting!
