### ISSUE TITLE
Modifying array tracked by form does not update form dirty state

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#12566]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Firefox, Chrome

### Reproduction link
[https://codepen.io/megawac-the-scripter/pen/XxMKGR?editors=0010](https://codepen.io/megawac-the-scripter/pen/XxMKGR?editors=0010)

### Steps to reproduce
Track an array with a `getFieldDecorator` from form. Either create a new entry or remove an existing entry (removal is particularly important). The form does not get marked as dirty. If you were to modify any form input first the form gets marked as dirty appropriately.

### What is expected?
`form.isFieldsTouched()` should return `true` after an item is removed from  (or added to) the tracked array.

### What is actually happening?
`form.isFieldsTouched()` should returns `false` when the tracked array is modified.

**Comment by zombieJ** [comment]
`isFieldsTouched` should not return `true` since the remove operation is not managed by form. It's your code logic.
So if you want to have the mix state, you can add own 'modified' in component state and change it when `add` or `remove` is called.

**Comment by megawac** [comment]
That seems weird to me, what is the point of even going through the hassle of having form track your dynamic variables if its other hooks are not going to work. I'd expect whenever you do a `setFieldValue` that is not equal to the initial value the form would be smart enough to mark it as dirty. Otherwise tracking this variable via form provides no benefit.
