### ISSUE TITLE
带筛选的表格右对齐显示边距错误

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#12572]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Mac OS, Chrome Canary 71.0.3570.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5x57oy61rl)

### Steps to reproduce
为表格添加筛选按钮、排序按钮，并且表格内容右对齐（`alias: 'right'`）

### What is expected?
右边距能在有筛选按钮 / 排序按钮时正确设置。

### What is actually happening?
带筛选的表格右对齐显示边距错误

当表格带筛选按钮时，如果标题栏右对齐，则会和筛选按钮重叠，特别是鼠标移动到筛选按钮上时，文字直接被覆盖了。

同时带筛选和排序时更明显。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/12552
