### ISSUE TITLE
REQUEST: allow Slider to be draggable

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design#12585]
### What problem does this feature solve?
I'm using a Slider layered on a chart (over time) to select sections of the chart to be viewed in a deeper dive. This works pretty well. But it'd be great to, say, select a 8 hour range and be able to slide that range around (not the start/end markers) to see different time periods in 8 hour blocks.

### What does the proposed API look like?
example:

https://www.jqueryscript.net/demo/Draggable-Range-Selection-Plugin-JQDRangeSlider/

https://www.jqueryscript.net/form/Draggable-Range-Selection-Plugin-JQDRangeSlider.html

**Comment by afc163** [comment]
I think you should try Chart with built-in slider.

https://antv.alipay.com/zh-cn/g2/3.x/demo/candlestick/basic.html
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/area-rainfall.html
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/line-rain-and-flow.html
https://antv.alipay.com/zh-cn/g2/3.x/demo/other/area-large.html
