### ISSUE TITLE
IE 11 下 table 的 checkbox 样式不正确

### ISSUE THREAD

**Issue by stxwd46** [ant-design/ant-design#12597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
系统 windows10， 浏览器版本 IE11

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/93x1nrm21o)

### Steps to reproduce
点击 checkbox 勾选行

### What is expected?
点击 checkbox 勾选的时候，中间白色的勾出现

### What is actually happening?
点击 checkbox 勾选的时候，中间白色的勾没有出现，只出现了蓝色的选中背景

---
后来测试发现 win7 下同样会有这个问题

**Comment by 007yaoyang** [comment]
@yutingzhao1991 ie9-ie11的table中的checkbox只有底色，没有勾
