### ISSUE TITLE
时间选择框选择样式错误

### ISSUE THREAD

**Issue by jinyaqiao1102** [ant-design/ant-design#12598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
IE 11

### Reproduction link
[https://ant.design/components/time-picker-cn/#header](https://ant.design/components/time-picker-cn/#header)

### Steps to reproduce
点击时间选择框-

### What is expected?
时间选择框样式错误，导致选择时间样式不正确

### What is actually happening?
正确的样式

**Comment by zombieJ** [comment]
debug 了一下，看起来是 IE 11 的 bug。心累...

**Comment by jinyaqiao1102** [comment]
> @jinyaqiao1102 PR is always welcome~

ok 有时间我修复一下
