### ISSUE TITLE
请问antd的form提交要如何操作, 才能在表单提交时校验是否填写数据, 而不是在填写表单是就判断是否有填写

### ISSUE THREAD

**Issue by XanderXueMingJi** [ant-design/ant-design#12590]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有些用户不喜欢在填写表单时, 将一个input清空时看到错误提示(请输入内容), 而是喜欢在点击提交按钮时才根据错误提示来修改表单, 请问这个要如何来实际

### What does the proposed API look like?
我现在使用的antd版本是3.8.4, 就想问问如何实现效果, 麻烦你们了

**Comment by ycjcl868** [comment]
可以看看教程 [validateFields](https://www.yuque.com/ant-design/course/up1dn3#%E7%A1%AE%E5%AE%9A%E6%93%8D%E4%BD%9C)，有空也可以看看 [如何有效地报告 Bug](https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html)
