### ISSUE TITLE
labelCol and wrapperCol in form is not working.

### ISSUE THREAD

**Issue by gzhou1976** [ant-design/ant-design#12599]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.0

### Environment
Win10, 所有浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6lpk73oo1r)

### Steps to reproduce
import React from "react";
import ReactDOM from "react-dom";
import { Button, version, Row, Col, Input, Form } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const App = () => (
  <div className="App">
    <Form layout="inline">
      <Row>
        <Col span={12}>
          <Form.Item
            label="1234"
            labelCol={{ span: 6, offset: 0 }}
            wrapperCol={{ span: 18, offset: 0 }}
          >
            <Input size="small" style={{ width: "100%" }} />
          </Form.Item>
        </Col>
        <Col span={12}>
          <Form.Item
            label="123"
            labelCol={{ span: 6, offset: 0 }}
            wrapperCol={{ span: 18, offset: 0 }}
          >
            <Input size="small" style={{ width: "100%" }} />
          </Form.Item>
        </Col>
      </Row>
      <Row>
        <Col span={12}>
          <Form.Item
            label="123456"
            labelCol={{ span: 6, offset: 0 }}
            wrapperCol={{ span: 18, offset: 0 }}
          >
            <Input size="small" style={{ width: "100%" }} />
          </Form.Item>
        </Col>
        <Col span={12}>
          <Form.Item
            label="12345678"
            labelCol={{ span: 6, offset: 0 }}
            wrapperCol={{ span: 18, offset: 0 }}
          >
            <Input size="small" style={{ width: "100%" }} />
          </Form.Item>
        </Col>
      </Row>
    </Form>
  </div>
);

ReactDOM.render(<App />, document.getElementById("root"));

### What is expected?
The two lines of forms, labels, and input component are aligned vertically.
I found labelCol and wrapperCol in form is not working.

### What is actually happening?
Out of alignment vertically.

**Comment by afc163** [comment]
It is built-in responsive design.

**Comment by gzhou1976** [comment]
What is build-in responsive design? Could this issue can be fix?

**Comment by afc163** [comment]
It is not a bug, it is a feature by designed.

**Comment by gzhou1976** [comment]
What is the feature id? and When will this feature be implemented?

**Comment by gzhou1976** [comment]
Is there any workarounds?

**Comment by PunkSea** [comment]
set the form layout to horizontal or vertical
