### ISSUE TITLE
input 除去前后空格

### ISSUE THREAD

**Issue by davy-gan** [ant-design/ant-design#12593]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
很多时候 需要除去掉输入框前后的空格，要是每次都手动去除去非常烦的，尤其是在后台项目中，使用input的地方是非常多的 ，现在每次都不要去手动除去的

### What does the proposed API look like?
<Input autotrim placeholder="请输入host" style={{ width: '100%' }} />

**Comment by afc163** [comment]
建议自行封装，基础组件不合适做这个。
