### ISSUE TITLE
Table 有滚动条的时候能让滚动条自适应高度吗？

### ISSUE THREAD

**Issue by leeseean** [ant-design/ant-design#12596]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
滚动table为右边栏，想让滚动的高度自适应左边栏，但是现在的scroll属性都是只能设置一个写死的高度，能不能自适应？

### What does the proposed API look like?
scroll: {
    y: 'auto'
}

**Comment by yesmeck** [comment]
建议自己通过获取父容器的高度来动态设置吧。
