### ISSUE TITLE
AutoComplete with customize inputComponent (TextArea) doesn't render right when disabled

### ISSUE THREAD

**Issue by cani1see** [ant-design/ant-design#12594]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
all

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9lnr64mwl4)

### Steps to reproduce
nest a TextArea set disabled

### What is expected?
disabled area is all

### What is actually happening?
disabled area seems to be 1 line

**Comment by Selfron** [comment]
For me this bug still happens in 3.16.2.
Seems like it was only fixed until 3.11.0 got released.

Reproduction links:
- 3.10.0   (bugged) https://codesandbox.io/s/3n90525p1
- 3.10.1   (working ) https://codesandbox.io/s/004o8o6kk0
...
- 3.10.10 (working) https://codesandbox.io/s/rm78zyo9pq
- 3.11.0   (bugged) https://codesandbox.io/s/n75lk1rylj
...
- 3.16.2 (bugged) https://codesandbox.io/s/93w5kk22pp

**Comment by Kermit-Xuan** [comment]
3.x version don't maintain, please upgrade to 4.x.
