### ISSUE TITLE
select表单校验问题

### ISSUE THREAD

**Issue by no-repeat** [ant-design/ant-design#1260]
**问题描述**

    const categoryIdProps = getFieldProps('categoryId', {
          rules: [
            {required: true, message: '请选择类型'},
          ]
    });

    let categorieOptionsNode = [];
    categorieOptions.map(function(item){
        categorieOptionsNode.push(<Option value={item.categoryId}>{item.name}</Option>);
    });

     <FormItem
            {...formItemLayout}
            label="类型选择：">

          <Select {...categoryIdProps} placeholder="请选择类目" style={{width: 200}}>
            {categorieOptionsNode}
          </Select>
     </FormItem>

**发生环境**

- antd 版本：0.12.12
- 操作系统及版本：mac
- 浏览器及版本：chrome 49.0.2623.87 (64-bit)
- 在线演示地址：无

**重现步骤**

1. ...
2. ...

**线上重现演示**

**Comment by yiminghe** [comment]
categoryId  整数需设置 type:'number'

默认 type:'string'
