### ISSUE TITLE
Modal Form has no way to send values from hidden fields or variables

### ISSUE THREAD

**Issue by developdeez** [ant-design/ant-design#12607]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
reactjs

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
Either try to create a hidden input or empty form field to pass to calling page.

### What is expected?
The form within the modal should show without empty gaps for hidden inputs or allow me to set a field that can returned from the the form modal without having a displayed field.

### What is actually happening?
It shows gaps for hidden inputs and can't set fields for form return.

---
This is important for calculated values. My popup looks up addresses and returns latitude and longitude. The field is the address but what I want sent back to the calling page is the latitude and longitude.

**Comment by spideeee** [comment]
Why do you need hidden fields?
You can listen to the Forms `onSubmit`, and then you can trigger your HTTP POST request, sending whichever parameter you want.

**Comment by afc163** [comment]
@spideeee is right.

**Comment by developdeez** [comment]
@spideeee that sounds good on the page itself. I'm passing in my callback for onsubmit to the form. Since the form is in a popup. When it closes it seems to only return form fields. Are you saying that I can use the forms on submit to pass back state values from the form along with the field values? 
Or am I misunderstanding?

**Comment by spideeee** [comment]
There may be many ways to achieve this, one is below...
https://ant.design/components/form/#components-form-demo-form-in-modal
Looking at the above example, there are 2 components `CollectionsPage` and `CollectionCreateForm`.

`CollectionsPage` passes the `handleCreate` function as `onCreate` to `CollectionCreateForm`, which in turn gives it to `Modal' as `onOk`. So when `onOk' is triggered (assuming that here your fields are validated and the location is calculated). You can return your location details to the `onCreate` which is `handleCreate` of `CollectionsPage` and trigger your POST request from there.

If its still not clear, you can create a sample codepen with your use case and then we can find a solution.
