### ISSUE TITLE
select tags模式 单选功能

### ISSUE THREAD

**Issue by xiaopangalf** [ant-design/ant-design#12605]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
就是select有下拉选项，又可以输入文本变成一个选项，tags模式是多选模式，不支持单选，虽然可以限制数量为1个，但是操作方式（选中后自动关闭）于数据格式（有数组的[]在内容中）都是不一样的。

### What does the proposed API look like?
tag 支持单选于多选

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/7960

**Comment by song111** [comment]
这个功能很实用呀，为啥不提供呀

**Comment by afc163** [comment]
@song111 你可能需要的是 https://ant.design/components/auto-complete/

**Comment by anran758** [comment]
@afc163 主要是有需求是想要 input 内单选的结果是标签的表现形式
