### ISSUE TITLE
Table在固定一列的情况下，使用Form，如果不输入内容，报错的样式有问题

### ISSUE THREAD

**Issue by PWDream** [ant-design/ant-design#12602]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3r73yrq6k5)

### Steps to reproduce
1. 第一列第一行，编辑
2. 把这一行中的内容清楚
3. 样式就出现问题

### What is expected?
样式正常

### What is actually happening?
样式有问题

**Comment by afc163** [comment]
可编辑列目前和固定列不兼容。你可能要自己想办法。
