### ISSUE TITLE
input框在设置了maxLength属性之后再特定情况下，输入长度可以大于maxLength

### ISSUE THREAD

**Issue by withzhaoyu** [ant-design/ant-design#12604]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
react@v16.4.2

### Reproduction link
[https://codepen.io/withzhaoyu/pen/WapWmp](https://codepen.io/withzhaoyu/pen/WapWmp)

### Steps to reproduce
（场景是：form表单里有input和textarea，这两个同时存在）
1.在input框内输入字符使长度到最大值；
2、切换为中文输入，随意输入按回车确认；
3、按crtl z撤销，此时文字长度大于了maxLength
（P.S. react升级到16.5.x后，这个bug消失；）

### What is expected?
不会出现文字大于maxLength

### What is actually happening?
出现输入字符大于maxLength

**Comment by afc163** [comment]
> react升级到16.5.x后，这个bug消失

既然是这样，说明是 react bug，直接升级就好。

**Comment by withzhaoyu** [comment]
@afc163 ，不是很确定这个是不是react bug哦。不在antd的form里面用input 和textarea是没有问题的_(:з」∠)_

**Comment by innocces** [comment]
这个问题是存在的，如果是cv到textarea里的文本是不受maxLength的限制的
