### ISSUE TITLE
关于 table sorter 的一个疑问 

### ISSUE THREAD

**Issue by chenxiaochun** [ant-design/ant-design#12601]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Mac

### Reproduction link
无

### Steps to reproduce
在这个[示例](https://ant.design/components/table/#components-table-demo-ajax)中，我点击 Email 列的时候，不会触发`onChange`事件。

但是，为什么把它[新页面打开](https://codesandbox.io/s/zx10p491rm)之后，在它当中点击 Email 列的时候却触发了`onChange`事件呢？

### What is expected?
点击 Email 不会触发 onChange

### What is actually happening?
点击 Email 会触发 onChange

**Comment by afc163** [comment]
问题已经在 #12515 里修复。
