### ISSUE TITLE
Table Row hover missing color on filtered column

### ISSUE THREAD

**Issue by shivamgupta94** [ant-design/ant-design#12610]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Ant example on docs page

### Reproduction link
[https://ant.design/components/table/#components-table-demo-head](https://ant.design/components/table/#components-table-demo-head)

### Steps to reproduce
Bug on documentation page

### What is expected?
the row should be completely blue on hover

### What is actually happening?
the row is blue except the sorted column on hover

**Comment by afc163** [comment]
It is by designed.
