### ISSUE TITLE
ref is not a function in Form getFieldDecorator 

### ISSUE THREAD

**Issue by saostad** [ant-design/ant-design#12611]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
browser

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mjzk67141p)

### Steps to reproduce
it's not run

### What is expected?
run like normal ref functionality

### What is actually happening?
in form Item2 :
TypeError
ref is not a function

---
in getFieldDecorator  it's not forwarding ref to component so ref is always null.
technically ref API is not usable to access children components generated with getFieldDecorator

**Comment by spideeee** [comment]
You can send ref as a function and save the input which will be sent as a param.

`ref = {(input) => this.ref1 = input}`

In the `rc-form` component, its is written as if the ref is a function:

```
var ref = fieldMeta.ref;
if (ref) {
    if (typeof ref === 'string') {
        throw new Error('can not set ref string for ' + name);
    }
    ref(component);//  <<==
}
```
https://github.com/react-component/form/blob/master/src/createBaseForm.js#L338

**Comment by saostad** [comment]
Can you please show me how to do this with my [CodeSandBox](https://codesandbox.io/s/mjzk67141p) ?

**Comment by spideeee** [comment]
Check this...

`<Input ref={(input) => this.myRef1 = input} />`

You can use `this.myRef1` as your input element, where in `React.createRef()` case, you get the element in `this.myRef1.current`. But here no need of `current` key, use it directly.

**Comment by saostad** [comment]
now it makes sense. thanks.

**Comment by j3l11234** [comment]
I have submit the pr   https://github.com/react-component/form/pull/217 for using React.createRef()
hope it publish asap
