### ISSUE TITLE
SubMenu: Add support for other components

### ISSUE THREAD

**Issue by cardiv** [ant-design/ant-design#12614]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Enables the use of `Row` and `Col` to build mega menus.

Currently, if I try this and hover the submenu title to display submenu, React throws an error: `renderMenuItem is not a function`

Example here: https://codesandbox.io/s/v63oywrj35

### What does the proposed API look like?
```jsx
<Menu.SubMenu>
  <Row>
    <Col span={12}>
      <Menu.ItemGroup title="Item 1">
        <Menu.Item key="setting:1">Option 1</Menu.Item>
        <Menu.Item key="setting:2">Option 2</Menu.Item>
      </Menu.ItemGroup>
    </Col>
    <Col span={12}>
      <Menu.ItemGroup title="Item 2">
        <Menu.Item key="setting:3">Option 3</Menu.Item>
        <Menu.Item key="setting:4">Option 4</Menu.Item>
      </Menu.ItemGroup>
    </Col>
  </Row>
</Menu.SubMenu>
```

**Comment by yutingzhao1991** [comment]
Menu's children are required be Menu.ItemGroup or Menu.Item, just like use select with option.

If you want custom menu style, refer this doc: https://pro.ant.design/docs/style#Override-the-component-style

**Comment by cardiv** [comment]
Hm, I understand the issue with children of components. Tried something like that myself in the past and thought you could have a solution to this.

Just adding custom styles seems the easier solution to this. Thank you for the quick response!
