### ISSUE TITLE
3.10.0 版本的antd 使用 and pro 无法识别函数

### ISSUE THREAD

**Issue by ningzhenyi** [ant-design/ant-design#12617]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
antd 3.10.0 , antd pro 2.0.0

### Reproduction link
[https://preview.pro.ant.design/dashboard/analysis](https://preview.pro.ant.design/dashboard/analysis)

### Steps to reproduce
antd  结合  pro 使用
test = () => {
}
这样的函数 编译报错 not found

### What is expected?
正常运行

### What is actually happening?
编译错误 not found

**Comment by afc163** [comment]
pro 问题请提到 pro 的 issue。

另外，你这样提问信息太少，基本不可能帮助到你。
