### ISSUE TITLE
Table 中不配置sorter和sortOrder 为什么无缘无故添加了一个<div title="排序">？

### ISSUE THREAD

**Issue by top-soft** [ant-design/ant-design#12613]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
和环境无关

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
我以为是自己写的问题，结果在官方API上面看到table都是那样，https://ant.design/components/table-cn/
const tableConfig = {
            columns: columns,
            dataSource: this.state.dataSource,
            rowKey: record => record.id,
            bordered: true,
            loading: this.state.loading,
            title: () => {
                return <span>管理员列表</span>;
            },
            pagination: this.state.pagination,
            onChange: this.handleTableChange,
            locale: {
                filterTitle: '筛选',
                filterConfirm: '确定',
                filterReset: '重置',
                emptyText: '暂无数据',
            },
            size: 'middle',
            sorter:false
        };
渲染的样子：
        `<thead className="ant-table-thead">
        <tr>
            <th className="">
                <div title="排序">登录名</div>
            </th>
            <th className="">
                <div title="排序">昵称</div>
            </th>
            <th className="">
                <div title="排序">状态</div>
            </th>
            <th className="">
                <div title="排序">操作</div>
            </th>
        </tr>
        </thead>`
点击这样的表头还能触发table的onChange事件！！！

### What is expected?
不会新增这样一个div

### What is actually happening?
`<thead className="ant-table-thead">
        <tr>
            <th className="">
                <div title="排序">登录名</div>
            </th>
            <th className="">
                <div title="排序">昵称</div>
            </th>
            <th className="">
                <div title="排序">状态</div>
            </th>
            <th className="">
                <div title="排序">操作</div>
            </th>
        </tr>
        </thead>
`

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/f1d1d87de08eadaa00f3d4c3c302f16e77ea8020

**Comment by top-soft** [comment]
我也没有配置sortButton

**Comment by top-soft** [comment]
@afc163 我的列不排序，我的column配置了sorter:false也是没效果，还是自动的创建这么一个div?  并且点击column还会触发onChange，这体验太差了，不排序点下还去后台发送请求！！！而且整个列的样式也要变化！

**Comment by afc163** [comment]
@top-soft Calm down.

> 并且点击column还会触发onChange

That was fixed in https://github.com/ant-design/ant-design/issues/12515

**Comment by FaFamylove** [comment]
我现在也出现了这个问题 貌似没有被修复哎
