### ISSUE TITLE
组件联动，怎么通过数据来重置table的fliter

### ISSUE THREAD

**Issue by ql434** [ant-design/ant-design#1261]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/pgdXYp?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/971
