### ISSUE TITLE
Borders around table header cells are missing in bordered ordered table

### ISSUE THREAD

**Issue by mkarajohn** [ant-design/ant-design#12628]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
CentOS 7, Firefox 60.2, react@16.3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7z0j80yr4x)

### Steps to reproduce
Have a bordered sortable table 

### What is expected?
I expect borders around the sortable table header cells to display properly

### What is actually happening?
The borders around the sortable table header cells are not showing, creating a visual inconsistency with the rest of the bordered table.

---
Updated from 3.9.3 to 3.10.0 and later to 3.10.1. Probably related to https://github.com/ant-design/ant-design/pull/12264

**Comment by Ryanhui** [comment]
use cellspacing="0" may solve this problem.
[Firefox 1 pixel bug with border-collapse, workaround?](https://stackoverflow.com/questions/1035706/firefox-1-pixel-bug-with-border-collapse-workaround)

**Comment by Ryanhui** [comment]
> use cellspacing="0" may solve this problem.
> [Firefox 1 pixel bug with border-collapse, workaround?](https://stackoverflow.com/questions/1035706/firefox-1-pixel-bug-with-border-collapse-workaround)

Just for project maintainer

**Comment by afc163** [comment]
https://stackoverflow.com/questions/7517127/borders-not-shown-in-firefox-with-border-collapse-on-table-position-relative-o

**Comment by afc163** [comment]
`background-clip: padding-box` is a workaround.

https://stackoverflow.com/a/16337203
