### ISSUE TITLE
3.10.0 table的问题

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design#12621]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
win10 chrome 69 react 16.5

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
未开启排序的表头，鼠标放在表格头上会出现排序，点击会触发change事件

### What is expected?
和3.9.2一样

### What is actually happening?
未开启排序的表头，鼠标放在表格头上会出现排序，点击会触发change事件

![image](https://user-images.githubusercontent.com/11569655/46863074-02d13680-ce49-11e8-9aaa-f1855c165348.png)

**Comment by afc163** [comment]
Fixed in #12515
