### ISSUE TITLE
Modal.confirm should have transitionName prop

### ISSUE THREAD

**Issue by theabhimanyu** [ant-design/ant-design#12623]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
any

### Reproduction link
[https://2x.ant.design/components/modal/](https://2x.ant.design/components/modal/)

### Steps to reproduce
always

### What is expected?
there should be one prop which control transition effect in Modal.confirm.

### What is actually happening?
This is not possible to change transition for Modal.confirm

**Comment by afc163** [comment]
We won't add it, you can try to override style globally.
