### ISSUE TITLE
panel groups

### ISSUE THREAD

**Issue by P0oOOOo0YA** [ant-design/ant-design#12636]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm reviewing ant design and i have to say its the best react framework i have seen. One feature that might be handy specially in desktop applications (electron) is resizable panels. I mean something like [this](https://danfessler.github.io/react-panelgroup/). It would be great if ant design team add this feature to their roadmap

### What does the proposed API look like?
```html
<PanelGroup borderColor="grey">
  <Content>panel 1</Content>
  <Content>panel 2</Content>
  <Content>panel 3</Content>
</PanelGroup>
```

**Comment by afc163** [comment]
something like https://github.com/tomkp/react-split-pane?

**Comment by P0oOOOo0YA** [comment]
@afc163 yes exactly, thanks.

**Comment by huoshidehua** [comment]
也就是说 我还要另外在用个什么其他插件？
