### ISSUE TITLE
Input框输入内容时通过正则验证报错

### ISSUE THREAD

**Issue by cymmint** [ant-design/ant-design#12634]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Window7、Chrome 61.0.3163.91、react-16.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mzw067k8xj)

### Steps to reproduce
input标签通过正则验证非法输入时出现错误
浏览器控制台提示：util.js:161 Uncaught (in promise)
错误是从 /node_modules/async-validator/es/util.js 抛出

### What is expected?
修复此BUG

### What is actually happening?
Input框输入内容时通过正则验证报错

**Comment by ycjcl868** [comment]
用官方的 demo 试了下，只要把输入的值删空就报错了。

![image](https://user-images.githubusercontent.com/13595509/46912449-58702500-cfa8-11e8-941d-d80f7a529659.png)

**Comment by andrewcodes404** [comment]
Any chance the solution could be printed in English please as I think i am having this same issue?

**Comment by ycjcl868** [comment]
Duplicate #12649.
