### ISSUE TITLE
transfer数据源太多，页面卡死

### ISSUE THREAD

**Issue by rana4504** [ant-design/ant-design#12632]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
页面卡死

### What does the proposed API look like?
通过参数控制左侧数据的显示数量

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
