### ISSUE TITLE
分页控件 showQuickJumper、showSizeChanger在手机端显示不出来

### ISSUE THREAD

**Issue by mrcaobin** [ant-design/ant-design#12641]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
react 

### Reproduction link
[https://ant.design/components/pagination-cn/](https://ant.design/components/pagination-cn/)

### Steps to reproduce
https://ant.design/components/pagination-cn/

### What is expected?
希望在手机端可以显示出来页面跳转和页面条数

### What is actually happening?
不现实

**Comment by yesmeck** [comment]
特意这么设计的 https://github.com/ant-design/ant-design/issues/4349 

可以自己覆盖下样式 https://github.com/ant-design/ant-design/blob/master/components/pagination/style/index.less#L328-L341
