### ISSUE TITLE
问个表单验证的问题

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#1264]
## What you did

定义了一个邮箱验证
```js
const emailProps = getFieldProps('email',{
       validateFirst: true,
       validate: [{
        rules: [
          { required: true, message: '必须填写邮箱地址' },
          { validator: this.emailExists }
        ],
        trigger: 'onBlur',
      }, {
        rules: [
          { type: 'email', message: '请输入正确的邮箱地址' },
        ],
        trigger: ['onBlur','onChange'],
      }]
     });

  emailExists(rule, value, callback) {
    if (!value) {
      callback();
    } else {
        fetch(`${api.checkEmail}?email=${value}`)
        .then(response => response.json())
        .then(result => {
          if(result.data) {
            callback([new Error('抱歉，该邮箱地址已被占用。')])
          } else {
            callback()
          }
        })
    }
  }
```

## What you would like to happen

我只想要一个提示信息： 必填 or 格式错误 or 已存在

## What actually happened

当两个规则同时满足触发条件时，提示信息都出来了
![image](https://cloud.githubusercontent.com/assets/2271825/14011705/a6cd67c4-f1db-11e5-8f99-bee7e5704e5a.png)

## Online demo
no

## Environment Information
版本是 0.12.12

**Comment by yiminghe** [comment]
trigger 不要有交集

**Comment by afc163** [comment]
试试：https://github.com/ant-design/ant-design/issues/659#issuecomment-169574521

预设的 email 校验规则也包含了 required 的判断，现在只能替换掉。

**Comment by codering** [comment]
demo :  http://sandbox.runjs.cn/show/aa58mp8v#/?_k=8arq53

**Comment by yiminghe** [comment]
类似 http://codepen.io/anon/pen/pgdXYp?editors=001 的 demo

**Comment by codering** [comment]
@yiminghe 根据你给的地址，我修改内容测试了下，并没用问题。
看来应该是fis3编译的问题。  让你费心了，实在不好意思！
