### ISSUE TITLE
Modal opened with Button in Drawer not opening

### ISSUE THREAD

**Issue by AWR14** [ant-design/ant-design#12652]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Create react app react 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/24y6kxq46n)

### Steps to reproduce
When you click to open the modal nothing happens.

### What is expected?
The modal should open

### What is actually happening?
Nothing

**Comment by ilanus** [comment]
https://codesandbox.io/s/xv11v28q2z

**Comment by afc163** [comment]
https://codesandbox.io/s/7ylo0jjvj0

You can close it by youself.

**Comment by ilanus** [comment]
> https://codesandbox.io/s/7ylo0jjvj0
> 
> You can close it by youself.

I don't have rights 😢 @AWR14 please close 😄
