### ISSUE TITLE
Make DatePicker internal input mirror `size` of external input for consistency

### ISSUE THREAD

**Issue by barneycarroll** [ant-design/ant-design#12657]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Windows 10, Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7wvw66j95q)

### Steps to reproduce
Compare <DatePicker size="medium" /> with <DatePicker size="large" />

### What is expected?
All sizes of DatePicker should have an internal input that's consistent with the size properties of the external input. 

### What is actually happening?
Instead these are always medium, so the internal input is out of place with small & large variations.

**Comment by afc163** [comment]
It is by designed now, we may resolve it via redesigning our DatePicker popup UX in future, thx for reporting it any way.

**Comment by barneycarroll** [comment]
cc @JAForbes
