### ISSUE TITLE
layout组件类型声明丢失

### ISSUE THREAD

**Issue by jiameng123** [ant-design/ant-design#12655]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
chrom 69.0.3497.100,   react 16.5.2 

### Reproduction link
[https://ant.design/components/layout-cn/](https://ant.design/components/layout-cn/)

### Steps to reproduce
layout文件夹下Sider.d.ts文件Sider组件responsiveHandler函数mql参数MediaQueryListEvent类型定义丢失，ts报错找不到MediaQueryListEvent

### What is expected?
mql参数应有MediaQueryListEvent 类型定义

### What is actually happening?
ts:找不到MediaQueryListEvent

**Comment by dougefr** [comment]
I've upgraded a working application from antd 3.9.2 to 3.10.1 and I've got the same error.

`
ERROR in /home/dougefr/develop/raol/node_modules/antd/lib/layout/Sider.d.ts
ERROR in /home/dougefr/develop/raol/node_modules/antd/lib/layout/Sider.d.ts(58,30):
TS2304: Cannot find name 'MediaQueryListEvent'
`

**Comment by afc163** [comment]
What is your ts version?

**Comment by jiameng123** [comment]
> What is your ts version?

ts:2.9.2 和 3.1.1 都会报这个错误

**Comment by afc163** [comment]
你能提供一个可重现的 git repo 来帮助排查么？

**Comment by Jw-Eminent** [comment]
有解决方法吗？今天也遇到了这个问题

**Comment by zombieJ** [comment]
ref: https://github.com/ant-design/ant-design/commit/9cfaf1750d407bf6048ba167f084c0a97fa9f78c

**Comment by zombieJ** [comment]
升级一下 ts，`MediaQueryListEvent` 是在 [typescript@3.1.x](https://unpkg.com/typescript@3.1.1/lib/lib.dom.d.ts) 添加的。[typescript@3.0.x](https://unpkg.com/typescript@3.0.3/lib/lib.dom.d.ts) 及以前没有这个定义。

**Comment by yesmeck** [comment]
`MediaQueryListEvent` was introduced in typescript@3.1.3

**Comment by weiQing88** [comment]
antd ^3.10.1 版本，出现这个问题

**Comment by luohong123** [comment]
>  我也遇到了同样的问题，已解决。
- 问题描述：webpack编译时会报错，报错代码如下，
```javascript
ERROR in [at-loader] ./node_modules/antd/lib/layout/Sider.d.ts:59:30
    TS2304: Cannot find name 'MediaQueryListEvent'.
```
- 我的package安装包版本如下，
```json
{
"antd": "^3.12.4",
 "react": "^16.7.0",
 "react-dom": "^16.7.0",
"typescript": "^2.9.2"
}
```
## 解决方法
升级typescript到3.1.x
```javascript
$ npm i -D typescript@3.1.6
```
执行webpack命令，

编译成功

**Comment by algaeReed** [comment]
再记录一个可能导致此问题的原因：
错误的导入方式：// import { ProLayout } from '@ant-design/pro-components';
正确的导入方式：import ProLayout from '@ant-design/pro-layout';
