### ISSUE TITLE
Mention add show image,sticker

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#12659]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
chat input box 
![image](https://user-images.githubusercontent.com/8358236/46988084-8cbf1f00-d129-11e8-9449-23dfba1f5239.png)
![image](https://user-images.githubusercontent.com/8358236/46988095-99437780-d129-11e8-9041-ab442a699c67.png)

### What does the proposed API look like?
not

**Comment by hengkx** [comment]
现在`Mention`是只能显示文字，官方考虑支持图片和表情吗，类似钉钉的聊天输入窗口

**Comment by yesmeck** [comment]
参考 https://ant.design/components/mention-cn/#components-mention-demo-avatar
