### ISSUE TITLE
Icon里SandBox示例报错

### ISSUE THREAD

**Issue by Fiv5** [ant-design/ant-design#12662]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
SandBox

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jjmk7w7nqv)

### Steps to reproduce
1. 找到Icon示例当中的 自定义示例 ，点开sandbox代码示例；

### What is expected?
1. 完整的示例

### What is actually happening?
界面一直loadding，打开F12报错：sandbox-service-worker.js:1 Uncaught (in promise) Error: Both cache and network failed: "No result returned", "TypeError: Failed to fetch" at u (sandbox-service-worker.js:1)

**Comment by yesmeck** [comment]
这是 codesandbox 的错，不是 antd 的。
