### ISSUE TITLE
Tree组件的 defaultExpandAll 参数在动态数据情况下失效

### ISSUE THREAD

**Issue by ganxunzou** [ant-design/ant-design#12663]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Chrome  69.0.3497.100 ， macos 10.12.6 (16G29) 

### Reproduction link
[https://codepen.io/ganxunzou/pen/gBXyKX?editors=0010#0](https://codepen.io/ganxunzou/pen/gBXyKX?editors=0010#0)

### Steps to reproduce
1. 打开：https://codepen.io/ganxunzou/pen/gBXyKX?editors=0010#0
2. 点击 change tree data 按钮

### What is expected?
Tree的所有自动展开。

### What is actually happening?
Tree 没有被展开

---
静态数据没有问题。就是动态数据会有。动态数据的场景更加普遍

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by ganxunzou** [comment]
@afc163  FAQ里面没有这项说明呀？

**Comment by ganxunzou** [comment]
@afc163  懂你意思了

那如果连Tree空间一起重新渲染呢？例如：https://codepen.io/ganxunzou/pen/gBXyKX?editors=1010

为啥也是不行的呢？

因为React是Diff算法的缘故吗？

如果是这样，请问怎么解决呢，这个是很常用的一个功能。总不能遍历数据生成所有的`expandedKeys `

**Comment by zombieJ** [comment]
`defaultExpandAll` 只会在第一次有效，如果你不想自己控制 expandedKeys 的话就删除 Tree，setTimeout 后再加回来。否则 Tree 会被复用。
