### ISSUE TITLE
Autocomplete控件BUG

### ISSUE THREAD

**Issue by UDLD** [ant-design/ant-design#12661]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
chrome

### Reproduction link
[https://xn.xiami.com/#/feedback](https://xn.xiami.com/#/feedback)

### Steps to reproduce
当输入的内容使得自动引导的内容选项为一个，且内容和引导选择的option的value相等的时候，选项不可点击

### What is expected?
选项可点击选择

### What is actually happening?
选项点击后，内容没有变化

---
阿里的同事，可以联系我  花名：法上

**Comment by UDLD** [comment]
https://codesandbox.io/s/l28vmyjlq9

**Comment by UDLD** [comment]
@ant-design-bot  需要更详细的，可以直接钉钉我： 17342055867

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/47195081-e2dfcc80-d38c-11e8-91ea-31efe7984eca.gif)

目测没问题。
