### ISSUE TITLE
Tree 组件数据调整后，默认展开所有项

### ISSUE THREAD

**Issue by ganxunzou** [ant-design/ant-design#12669]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree 组件数据调整后，默认展开所有项

### What does the proposed API look like?
dataChangedDefaultExpandAll

https://github.com/ant-design/ant-design/issues/12663#event-1905644236

**Comment by afc163** [comment]
最好的方式是自行用 expandedKeys 去控制状态。expandAll 这样的受控属性会导致无法收起。

**Comment by zombieJ** [comment]
`dataChangedDefaultExpandAll` 太定制化了，而且这个属性会显著降低大数据下 Tree 的性能。还是建议自己封装成受控组件或者用 re-render 来实现。
