### ISSUE TITLE
Notification 通知提醒框 html 标签

### ISSUE THREAD

**Issue by hzad** [ant-design/ant-design#1266]
message 和 description 均不支持html标签？
如：`description: '<p>我不会自动关闭</p><p>我不会自动关闭</p>' 会直接把 <p> </p>都显示出来`

或者应该怎么样显示多行文本呢？

**Comment by benjycui** [comment]
```jsx
description: <p>我不会自动关闭</p><p>我不会自动关闭</p>
```
