### ISSUE TITLE
Select组件在设置showSearch参数后，无法在输入框中输入空格

### ISSUE THREAD

**Issue by HuYuee** [ant-design/ant-design#12671]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
chrome浏览器版本69.0.3497.81

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5kmkv4v6rl)

### Steps to reproduce
Select组件在设置showSearch参数后，无法再输入框中输入空格

### What is expected?
Select组件在设置showSearch参数后，能输入框中输入空格

### What is actually happening?
Select组件在设置showSearch参数后，无法再输入框中输入空格

**Comment by HuYuee** [comment]
@zombieJ

**Comment by zombieJ** [comment]
Fixed in [`rc-select@8.4.2`](https://codesandbox.io/s/1zlx970vxl)

**Comment by HuYuee** [comment]
想问下，发了新版这个没有在3.10.2里面更新，以后不会支持这个功能吗？还是说需要自己引入新的rc-select，自己实现这个功能

**Comment by afc163** [comment]
@HuYuee 重新更新 node_modules 之后。
