### ISSUE TITLE
请在Form 表单中将 input 的 type="password" 的value 隐藏 

### ISSUE THREAD

**Issue by ZhiGang-Fang** [ant-design/ant-design#12672]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在浏览器的自动填充功能，会自动填充，在检查元素时，能直接看到明文密码

### What does the proposed API look like?
希望能把渲染好的 的 element 元素为  input  type="password" 的value 隐藏

**Comment by zombieJ** [comment]
这个是游览器的行为，和 antd 没有关系。
另外，即便是 value 用 * 混淆掉。安装了 react dev tools 查看组件一样是可以看到 state 里的 value 的。

**Comment by ZhiGang-Fang** [comment]
觉得并不是浏览器的行为，在正常的情况下， input  type="password" 时浏览器控制台elements看不到 value 的属性，而在 antd  Form 表单中能直接看到input 的value 属性 `<input type="password" id="password" data-__meta="[object Object]" data-__field="[object Object]" class="ant-input" value="11111111" data-com.agilebits.onepassword.user-edited="yes">` 麻烦请验证 ，谢谢！ @zombieJ
