### ISSUE TITLE
table表格支持列筛选问题

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design#12673]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决可以动态显示列需求

### What does the proposed API look like?
相关配置就可以实现目标

**Comment by zombieJ** [comment]
请问能描述更详细一点吗？

**Comment by afc163** [comment]
动态配置 columns 即可。
