### ISSUE TITLE
Button with icon is misaligned vertically

### ISSUE THREAD

**Issue by adnan-i** [ant-design/ant-design#12681]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Mac OS High Sierra, Chrome 69, Firefox 62

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zko2wzkvmx)

### Steps to reproduce
As shown in codesandbox: Place two or more Button components next to each other. Specify icon property on one of the buttons.

### What is expected?
When arranging several circle buttons next to each other in-line, all buttons should have equal vertical alignment

### What is actually happening?
Buttons with icon are dropped several pixels below the line in Chrome and raised in Firefox

---
<img width="1101" alt="screen shot 2018-10-16 at 14 34 11" src="https://user-images.githubusercontent.com/1370983/47017021-71680a00-d151-11e8-85e3-b9d4ef0fb029.png">

**Comment by ilanus** [comment]
@afc163 can be solved with `display: block` on `i` and `svg` level? or situation is more complicated? 😄

**Comment by afc163** [comment]
https://codesandbox.io/s/5x73o2q7vl

It may not be the problem of icon buttons but the empty button, which is pretty weired usage.

**Comment by adnan-i** [comment]
@afc163 I was using empty circle buttons with custom background color while making a color picker. I wanted to utilise the hover effect of the antd Button, and in terms of semantics using the <button> element here makes sense.  My workaround is to add a "." character to the "empty" buttons and apply "text-indent: -9999px". And yes, I can confirm that the issue is within the empty buttons and not icon buttons.
