### ISSUE TITLE
The extra of `Card` will cover the title of `Card` When `Card` is not wide enough

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#12680]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kx6459k4r7)

### Steps to reproduce
1. A Card's instance has title and extra same time.
2. The width of A is getting shorter and shorter
3. The extra of `Card` will cover the title of `Card`

### What is expected?
The extra of `Card` will not cover the title of `Card` anytime

### What is actually happening?
The extra of `Card` will cover the title of `Card`

---
Title is very important in a Card, it will not be cover by extra whenever.

**Comment by Ryanhui** [comment]
If you need to achieve it, maybe you can use z-index manually.

**Comment by xyy94813** [comment]
The issue is still in there. Please see the test case. 
https://codesandbox.io/s/kx6459k4r7
@afc163
