### ISSUE TITLE
Option to make Slider thicker

### ISSUE THREAD

**Issue by 8shaks** [ant-design/ant-design#12685]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The slider component is a nice component that has a ton of features. However I feel it is too thin, I was wondering if you guys could put in a default LESS variable to allow developers to controls the size of the slider. For example instead of it being pencil thin, developers would be able to make it thick as a marker stroke.This would be very handy for developers since we would be able to customize the look of the slider more to our liking.

### What does the proposed API look like?
The default LESS variable could look like this:

```"@slider-size": "140px",```

**Comment by zombieJ** [comment]
Thanks for feedback. You can send a PR for what css prop you want to be in a variable. Here is the slider less file: https://github.com/ant-design/ant-design/blob/master/components/slider/style/index.less

**Comment by 8shaks** [comment]
Hey, I am not really sure how does works. What lines would I edit?

**Comment by zombieJ** [comment]
[.@{slider-prefix-cls}](https://github.com/ant-design/ant-design/blob/master/components/slider/style/index.less#L6) is the class name of slider. It contains track, handle, mark, etc. sub item. For the size usage, these sub item should be adjust.

**Comment by afc163** [comment]
Feel free to send us PR, closing it now.
