### ISSUE TITLE
table中设置宽度之后复选框列不能固定在左侧问题 

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design#12686]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
win7 chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://jzx80kjp8y.codesandbox.io/)

### Steps to reproduce
表格列设置宽度之后，复选框会右移,设置固定之后，则会出现两列复选框

### What is expected?
只有一列，复选框固定左侧

### What is actually happening?
会出现两列复选框

**Comment by yescookie** [comment]
固定列是需要配合 `scroll.x` 使用的，参考 https://ant.design/components/table-cn/#components-table-demo-fixed-columns

**Comment by m26597** [comment]
@afc163 已经解除

**Comment by yesmeck** [comment]
固定复选框也是属于固定列，你需要设置一个 `scroll.x`

**Comment by m26597** [comment]
你说的是把rowSelection的fixed:true 、 table的scroll={{ x: 1300 }}吗？这样仍然是两列复选框，你能描述的更清晰一些么

**Comment by yesmeck** [comment]
https://codesandbox.io/s/xj4z70w2ro

**Comment by m26597** [comment]
嗯， 我的应用场景是table中的列需要支持动态筛选和隐藏，而且第一列的宽度需要指定来保证不会换行，这时，当我筛选过后只剩下第一列的时候，就会出现列宽度不匹配和scroll.x不匹配，这时候应该怎么处理

**Comment by yesmeck** [comment]
只剩下一列的时候，那一列不要设置宽度，跟我上面的例子一样。

**Comment by m26597** [comment]
@yesmeck 搞定啦，  老铁，感谢你！

**Comment by m26597** [comment]
@yesmeck 还有，只要不设置宽度，复选框就不会右移，fixed属性也就没有用到

**Comment by m26597** [comment]
@yesmeck  还有个问题，我怎样才能获取或者清空transfer中搜索框的内容呀？ 

ant-design 中只能提出问题或者需求， ant-design-pro中提问也没人回复我， 没有答案。。。
