### ISSUE TITLE
ant mention initialized value

### ISSUE THREAD

**Issue by NoureldeanSaed** [ant-design/ant-design#12699]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Ubuntu 18.04 64bit, Chrome 69, React 16.4

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m7n7194pmx)

### Steps to reproduce
Just create some new contentState and give it to the mention component. It doesn't accept the value until it has been interacted with. In the codesandbox snippet, just click the mention, it only then will add the value that has been set to initial.

### What is expected?
That the mention component accepts the text whenever the value has changed or initialized.

### What is actually happening?
The components accepts only direct change, while it cannot be changed by passing some acceptable value from outside the component.

**Comment by NoureldeanSaed** [comment]
@zombieJ Solved?

**Comment by zombieJ** [comment]
Remove `node_modules` and reinstall: https://codesandbox.io/s/zkmzpl2l63
