### ISSUE TITLE
Allow font-variant to be customizable

### ISSUE THREAD

**Issue by neemski** [ant-design/ant-design#12690]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We are using Greycliff CF as the main font on our site. We have an `<InputNumber>` component, which by default uses `font-variant: tabular-nums`. Unfortunately this looks pretty awful with Greycliff, and we'd like to be able to configure this property to go back to `font-variant: normal`, for all `<InputNumber>` components, by overriding a LESS variable.

### What does the proposed API look like?
To `components/style/themes/default.less`, add the following variable:
```less
@font-variant-base      : tabular-nums;
```
and use this variable in `base.less`, and `reset.less`.

**Comment by neemski** [comment]
Created a PR here: https://github.com/ant-design/ant-design/pull/12691

**Comment by afc163** [comment]
Thx @neemski Merged #12691
