### ISSUE TITLE
Button: inner span can raise onclick on Edge

### ISSUE THREAD

**Issue by dazbo** [ant-design/ant-design#12698]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Windows 10 / Edge

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pk8z1j8qpx)

### Steps to reproduce
Create a button and attach an handler which make usage of the target.

### What is expected?
It is expected the target to be the `<button />`, but on Edge, the target can be the inner `<span />` holding the button text.

Click on 1st button, the console should display twice the same id: `notEdge`.
Click on 2nd button, the console should display twice the same id: `EdgeLike`

### What is actually happening?
On Edge, the target is the span but not the button, both button could return an empty ID from target object.
It introduces some disparity between how browsers behave regarding the event.

A quick debug session seems to point that the below CSS property/rule is _ignored_ by Edge, unless we specify the span to be display as `inline-block`
```css
.ant-btn > i, .ant-btn > span {
    pointer-events: none;
}
```
Not 100% sure this is the fix, but pretty sure this is a way to a resolution.

You can also see [CanIUse knwon issues](https://caniuse.com/#feat=pointer-events) about how IE and Edge can be buggy with that.
Note the bug is not reproducible with Internet Explorer 11.

---
A workaround is to read about the currentTarget, but on other browsers, the target is correct and the same as currentTarget.

**Comment by yesmeck** [comment]
> unless we specify the span to be display as inline-block

Could you send a PR?

**Comment by dazbo** [comment]
For sure, I could try to prepare it, but I will not be able to work on it before next week.
That fix was also not widely tested, not sure about other impact it could introduce.

**Comment by yesmeck** [comment]
Thanks! We'll release a path this weekend.
