### ISSUE TITLE
Ant Design of React 文档中命令错误

### ISSUE THREAD

**Issue by charliezzo** [ant-design/ant-design#12693]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Win10、Chrome69

### Reproduction link
[https://ant.design/docs/react/practical-projects-cn](https://ant.design/docs/react/practical-projects-cn)

### Steps to reproduce
打开 https://ant.design/docs/react/practical-projects-cn
在项目实战-->新建路由-->$ yarn global addd npx

### What is expected?
$ yarn global add npx

### What is actually happening?
$ yarn global addd npx

**Comment by afc163** [comment]
来晚了。

https://github.com/ant-design/ant-design/pull/12678

**Comment by charliezzo** [comment]
fix就行，晚不晚都没关系的。
