### ISSUE TITLE
I hope "font-family" can be a customizable variables

### ISSUE THREAD

**Issue by ebameng** [ant-design/ant-design#12697]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能否把font-family抽成变量，可通过修改主题的变量来配置

### What does the proposed API look like?
能否把font-family抽成变量，可通过修改主题的变量来配置

**Comment by yesmeck** [comment]
Yes, you can. https://github.com/ant-design/ant-design/blob/bf83845986031f8dc8a9d4b24cca49d58b30eda3/components/style/themes/default.less#L37
