### ISSUE TITLE
The MenuItem will collapse when the width is not enough. How to make it not fold

### ISSUE THREAD

**Issue by Angelki** [ant-design/ant-design#12702]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6413r0n31z)

### Steps to reproduce
1

### What is expected?
not fold

### What is actually happening?
fold

**Comment by afc163** [comment]
Don't use `inlineCollapsed` when `mode="horizontal"`.

**Comment by Angelki** [comment]
> Don't use `inlineCollapsed` when `mode="horizontal"`.

that's  not the point,OK?

![image](https://user-images.githubusercontent.com/14013570/47138384-d5263a80-d2eb-11e8-906f-12d8a678ad1e.png)
宽度过小时，菜单项会折叠 成"..."，如何让它不折叠。
