### ISSUE TITLE
希望和Tree相关控件支持 自定义TreeNode字段 比如 title  key  children

### ISSUE THREAD

**Issue by pbbisme** [ant-design/ant-design#12708]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了：不需要前端在对后端的数据进行 递归转换处理，增加了Tree的灵活性和可配置性
现在是后端返回tree数据，前端需要递归成Tree需要的数据格式

###### 现在Tree需要的的数据格式

```typescript

const treeData = [
	{
		title: 'Node1',
		value: '0-0',
		key: '0-0',
		children: [
			{
				title: 'Child Node1',
				value: '0-0-1',
				key: '0-0-1',
			},
			{
				title: 'Child Node2',
				value: '0-0-2',
				key: '0-0-2',
			},
		],
	},
	{
		title: 'Node2',
		value: '0-1',
		key: '0-1',
	},
];

```

###### 现在获取到的格式

```typescript
const treeData = [
	{
		name: 'Node1',
		value: '0-0',
		id: '0-0',
		childrens: [
			{ name: 'Child Node1', value: '0-0-1', id: '0-0-1' },
			{ name: 'Child Node2', value: '0-0-2', id: '0-0-2' },
		],
	},
	{ name: 'Node2', value: '0-1', id: '0-1' },
];
```

**期望**：像  https://angular2-tree.readme.io/docs/options  这样支持 Tree的可配置性 
这样就不需要前端在将后端返回的数据格式转换成Tree固定的格式

**Comment by zombieJ** [comment]
感觉写个 convert 也可以实现，并不是必须的。加个 `Discussion` tag，先收集一下社区反馈吧。

**Comment by pbbisme** [comment]
现在自己写convert   Tree数据量庞大的话，前端递归成本有点搞，中间件covert递归一次，树渲染又递归一次，有时候感觉页面有点卡顿

**Comment by zombieJ** [comment]
> @pbbisme ：现在自己写convert Tree数据量庞大...

感谢反馈，我先记下了。

**Comment by afc163** [comment]
转换数据结构几乎不耗时。

**Comment by pbbisme** [comment]
现在使用JSON.stringify 转换，但是还是希望官方支持下

**Comment by ybning** [comment]
+1

**Comment by ybning** [comment]
希望能像table一样有属性childrenColumnName支持

**Comment by pkaq** [comment]
这个真的可以有 antd现在组件化上虽然做的不错了 但比起当年的extjs的完成度上还是略显薄弱

**Comment by maimai123** [comment]
期待早日完善 这样就不用再去转换了

**Comment by pkaq** [comment]
> This a useless feature , ant-design should be a pure component library IMO. You'd better write a covert tool to transform data.

这么多人评论 支持 还强行无用论关闭issue这样对吗?

**Comment by Lihuans** [comment]
+1

**Comment by morelearn1990** [comment]
+1

**Comment by America-first-melon** [comment]
+1
