### ISSUE TITLE
Calendar 面板同时显示了英文和中文 (Panel diaplay both chinese and english.)

### ISSUE THREAD

**Issue by xiaoquanWu** [ant-design/ant-design#12706]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Ubuntu 18, Chrom  68.0.3440.106（正式版本） （64 位）, React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m5m6m8lj5p)

### Steps to reproduce
正常使用Calendar 组件。(  Use Calendar component with normal way.)

### What is expected?
日期面板中文显示. (All date  display with chinese.)

### What is actually happening?
日历面板同时显示了中文和英文. (Display both chinese and english. )

**Comment by Transee1** [comment]
我也遇到了类似的问题，请问怎么解决？
