### ISSUE TITLE
Table 组件设置可展开的情况，收起是希望销毁这个dom

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#12701]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果我要对Table设置奇偶行的背景色，默认收起，当展开一行再收起时，Table使用了display：none，影响了根据tr:odd设置的背景色

### What does the proposed API look like?
期望对展开收起类型的Table，做出相应优化

**Comment by yesmeck** [comment]
用 `rowClassName` 来做背景色 https://codesandbox.io/s/m75pjnzmyx
