### ISSUE TITLE
Information Modals do not expose icon like other components

### ISSUE THREAD

**Issue by bryanberger** [ant-design/ant-design#12717]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Chrome 69 latest

### Reproduction link
[https://ant.design/components/modal/](https://ant.design/components/modal/)

### Steps to reproduce
The Modal seemed to be left behind in the big update around adding icon customizability to components: #12247

Currently Modal.success Modal.error Modal.warning and Modal.info have hardcoded icon associations tied to the Ant Design Icon Library only

### What is expected?
Similar to what was done in #12247 by allowing us to pass in custom <Icon /> components into iconType

### What is actually happening?
iconType only supports Ant Design icons passed as a string.

**Comment by afc163** [comment]
Yes, it does not support custom components for now.
