### ISSUE TITLE
Menu group title padding is wrong

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#12715]
`3.10.1` is wrong: https://codesandbox.io/s/lrn1yyx12l

<img width="261" alt="image" src="https://user-images.githubusercontent.com/507615/47169103-3a524e00-d335-11e8-8749-5ce447a1d661.png">

`3.9.3` is correct: https://codesandbox.io/s/q31m2rr2lq

<img width="274" alt="image" src="https://user-images.githubusercontent.com/507615/47169112-4211f280-d335-11e8-80aa-3a938e41c128.png">

**Comment by picodoth** [comment]
It's coming from https://github.com/react-component/menu/pull/201  for addressing https://github.com/react-component/menu/issues/198

<img width="301" alt="screen shot 2018-10-19 at 10 28 45 am" src="https://user-images.githubusercontent.com/1731837/47194422-d1e18c00-d389-11e8-853a-9cc1117f3648.png">


I thought it's a valid point, and didn't notice it's causing the visual change. I tried to change the indentation logic, but it's becoming:

<img width="307" alt="screen shot 2018-10-19 at 10 30 46 am" src="https://user-images.githubusercontent.com/1731837/47194494-22f18000-d38a-11e8-9d22-ce78c87d5c01.png">


Shall we revert that change?
