### ISSUE TITLE
Table column sorter has conflict with click action

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#12711]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义表头组件存在点击区域的时候，会和 sorter 冲突

### What does the proposed API look like?
emm...

点击 checkbox 的时候，后面的排序也会被作用到 
[![Edit vq6yn869x3](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vq6yn869x3)

**Comment by afc163** [comment]
You need to use `e.stopPropagation()` to avoid click event bubble up.

https://codesandbox.io/s/017o9wzyn

**Comment by tolerance-go** [comment]
i use it in onChange callback pres...
