### ISSUE TITLE
Tabs component doesn't seem to respect activeKey

### ISSUE THREAD

**Issue by byzyk** [ant-design/ant-design#12714]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
macOS 10.13.6, Chrome 69, react: ^16.3.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lxlm00328l)

### Steps to reproduce
Try to click on `Second` tab. It will prevent tabs from changing since bounded to the component state via `activeKey`

### What is expected?
Tabs don't change, `onChange` callback **is not** firing

### What is actually happening?
Tabs don't change, `onChange` callback **is** firing

**Comment by dazbo** [comment]
The active key is never changed in your state. Your `handleChange` method should take as 1st parameter the selected key and update the state with it:
```js
  handleChange = (selectedkey) => {
      this.setState({activeKey:selectedkey}); // <- set key sent by the handler to the state
      console.log("change callback");
  };
```

Or without state management, you can also just use `defaultActiveKey` prop on `<Tabs />` declaration, so the tabs will use that value for 1st render, but then the clicked tab.

**Comment by ilanus** [comment]
https://codesandbox.io/s/xpzw064ymq

**Comment by byzyk** [comment]
Thank you guys, I understand that and this is done intentionally.

Maybe I'm not addressing the problem in a very nice way but the idea is I'm **not expecting** a tab to change, and it works fine. However, `onChange` callback is firing while it shouldn't. I see now that the title is misleading, I'll fix that.

Try to run my example, when you click on the Second tab see the console output.

**Comment by byzyk** [comment]
@afc163 I see, but could you explain why it's implemented in such way? `onChange` triggers while nothing actually changed, it doesn't really make sense to me but perhaps I'm missing something.

**Comment by afc163** [comment]
It is not antd's logic but react's.

Check the native input example: https://codesandbox.io/s/rjvkoz6mpp

**Comment by byzyk** [comment]
Thanks for the clarification, now I get it.

So how do you think we could address such a case? Perhaps extend Tabs component, add another callback method which will trigger only when the actual tab change takes place? Something like `onTabChange` etc.

What do you think? I'll be happy to take a look at it and submit a PR shortly.

**Comment by zombieJ** [comment]
Hi @byzyk , this is customize logic which should not included in antd. Just wrap it in your project is enough : )

**Comment by byzyk** [comment]
@zombieJ got it, thanks.

**Comment by yassineZemmouri** [comment]
i think that the component is re-rendering and tab 1 is the default selected try to store the tab's key using Redux:

const YourComponent = () => {
  const selectedTabKey = useSelector(selectSelectedTabKey);
  const dispatch = useDispatch();

  const handleTabChange = (key: string) => {
    dispatch(setSelectedTabKey(key));
  };

  return (
    <Tabs defaultActiveKey={selectedTabKey} items={items} onChange={handleTabChange} />
  );
};
