### ISSUE TITLE
when using Dropdown component, always report an error "Uncaught Error: React.Children.only expected to receive a single React element child.", even if the component has only one child

### ISSUE THREAD

**Issue by cuiqiusheng** [ant-design/ant-design#12710]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
macos12 & chrome 69.0.3497.100

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zvx9lx1ol)

### Steps to reproduce
import React from "react";
import ReactDOM from "react-dom";
import { Button, version, Dropdown } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const App = () => (
  <div className="App">
    <p>Current antd version: {version}</p>
    <p>Please fork this codesandbox to reproduce your issue.</p>
    <div>
      <Dropdown>
        <Button type="primary">Here is a button</Button>
      </Dropdown>
    </div>
  </div>
);

ReactDOM.render(<App />, document.getElementById("root"));

### What is expected?
no error

### What is actually happening?
Uncaught Error: React.Children.only expected to receive a single React element child.

**Comment by dazbo** [comment]
It looks like you are missing a `overlay` property to your dropdown definition.

I took the menu definition from documentation and just pass it to your sandbox sample, the error disappear: [sample with overlay defined](https://codesandbox.io/s/lojy49zw9)

Maybe you don't need the overlay, but why using a `<Dropdown />`? In that case you should just remove it from your template.

**Comment by cuiqiusheng** [comment]
@dazbo  I solved my problem.

**Comment by afc163** [comment]
@cuiqiusheng You can close issue now.

**Comment by cuiqiusheng** [comment]
@dazbo   I solved my problem.  Thanks a lot.
