### ISSUE TITLE
Can't control Upload Component 'filelist'

### ISSUE THREAD

**Issue by developdeez** [ant-design/ant-design#12722]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
reactjs

### Reproduction link
[https://ant.design/components/upload/](https://ant.design/components/upload/)

### Steps to reproduce
Try to set filelist to null using a clear button after uploading a file to the file list

### What is expected?
list disappears

### What is actually happening?
List doesnt show because empty list not allowed for filelist.

---
Attempt so far:

  <Upload
                      disabled={
                        this.props.form.getFieldValue("upload") ? true : false
                      }
                      name="file"
                      action="//jsonplaceholder.typicode.com/posts/"
                      onChange={this.handlePhotoChange}
                      file={this.props.form.upload}
                      data={file => this.handleUpload(file, signS3)}
                      fileList={["test,jpg"]}
                    >
                      <Button>
                        <Icon type="upload" /> Click to Upload
                      </Button>
                    </Upload>

**Comment by swordguard** [comment]
Can you share you complete code(or at least involved code), so we can help.
