### ISSUE TITLE
普通复选框使用indeterminate之后，勾选样式不全

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design#12724]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
win7 chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yjo67y554j)

### Steps to reproduce
参照重现链接

### What is expected?
样式正常

### What is actually happening?
样式残缺

**Comment by afc163** [comment]
Your codepen is not working.

**Comment by m26597** [comment]
https://yjo67y554j.codesandbox.io/
这个呢？

**Comment by afc163** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/507615/47195174-4a961780-d38d-11e8-9ed3-4e9352d5ddf6.png">

你自己能跑得起来么

**Comment by m26597** [comment]
![default](https://user-images.githubusercontent.com/39291213/47195229-8df08600-d38d-11e8-84c9-02965ce5d0e2.png)


能的呀，是我没保存嘛，跟我代码不一样呀

**Comment by afc163** [comment]
重新 fork 一份。

**Comment by afc163** [comment]
可以打开一个隐私窗口测试一下。

**Comment by m26597** [comment]
https://codesandbox.io/s/v07w87v693

**Comment by m26597** [comment]
可以嘛
