### ISSUE TITLE
table的size设置为middle或者small之后，复选框设置selections后，左侧复选框不能对齐

### ISSUE THREAD

**Issue by m26597** [ant-design/ant-design#12723]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
win7  chrome 66

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
设置size为middle或者small之后出现

### What is expected?
对齐

### What is actually happening?
不对齐

**Comment by m26597** [comment]
又是空的！

**Comment by m26597** [comment]
等我

**Comment by yesmeck** [comment]
还是空的

**Comment by m26597** [comment]
这也太难了。。。
https://codesandbox.io/s/23xqxx89j0

https://23xqxx89j0.codesandbox.io/

这次真的可以啦
