### ISSUE TITLE
TreeSelect shouuld filter by title not key and should suppourt filterOption like Transfer. 

### ISSUE THREAD

**Issue by mlyknown** [ant-design/ant-design#12726]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Make TreeSelect is suitable.

### What does the proposed API look like?
TreeSelect shouuld filter by title not key and should suppourt filterOption like Transfer.

**Comment by zombieJ** [comment]
TreeSelect do provide the `treeNodeFilterProp` prop. It's default use `value` as filter condition. You can set as `title` : )
