### ISSUE TITLE
Typescript compile error: node_modules/antd/lib/layout/Sider.d.ts:58:30 - error TS2304: Cannot find name 'MediaQueryListEvent'

### ISSUE THREAD

**Issue by Jeowulf** [ant-design/ant-design#12736]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
MacOS High Sierra 10.13.4, Chrome Version 70.0.3538.67 (Official Build) (64-bit)

### Reproduction link
[https://ant.design/docs/react/use-in-typescript](https://ant.design/docs/react/use-in-typescript)

### Steps to reproduce
The error listed in this title points directly to the file and line containing the error in the source code. If you want to see the error in a reproduction, follow the steps listed in the ant-design typescript demo at https://ant.design/docs/react/use-in-typescript, up until yarn add antd, at which point all you have to do is navigate to the line in the antd node module and see the MediaQueryListEvent is underlined in red and any attempt to see its definition will reveal it refers to nothing

### What is expected?
MediaQueryListEvent to have a type definition or interface reference

### What is actually happening?
MediaQueryListEvent does not refer to anything

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12655

<img width="610" alt="image" src="https://user-images.githubusercontent.com/507615/47251088-cb721380-d460-11e8-8216-f78614443cf1.png">

I believe you lied about it.

**Comment by OrenSchwartz** [comment]
this still happens.

**Comment by talkl** [comment]
> this still happens.

still happens in 2019

**Comment by ztplz** [comment]
@talkl  Make sure your `typescript` > 3.1.6.
