### ISSUE TITLE
Floating Button

### ISSUE THREAD

**Issue by obonyojimmy** [ant-design/ant-design#12738]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Floating buttons have and are an essential part of any UI development, while this can be achieved  easy with some css , i think it would be handy if we have some props on the button that would make it floating.

### What does the proposed API look like?
https://material-ui.com/components/floating-action-button/

**Comment by afc163** [comment]
We follow Ant Design specification which don't contain Float Buttons in it.

**Comment by viranmalaka** [comment]
![image](https://user-images.githubusercontent.com/17590939/77241019-f262e500-6c12-11ea-9d82-1b9b444393f2.png)
But the Document itself contains some floating buttons. can anyone give me some examples of this ?

**Comment by viranmalaka** [comment]
Hi all, 
I can see @afc163 added a label `New Component`. 
Will this be a new Component or an additional props to the existing `Button` Component?

**Comment by afc163** [comment]
I believe it is a good addition to antd design spec, but we don't have a extact plan to implement it.

**Comment by anktsrkr** [comment]
Any plan for this enhancement?

**Comment by oussamabouchareb** [comment]
I've always thought this was part of antd months ago and now when I need it I find out it's not, the fact that there's two always floating in the documentation is kind of misleading because you would think they would only use what is available in their library

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/37407

**Comment by Sgrprsd2204** [comment]
Is there a way to make this floating button's component's horizontally aligned ?
