### ISSUE TITLE
Table sorter gets stuck when render function is present on column

### ISSUE THREAD

**Issue by kevinfling** [ant-design/ant-design#12737]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
MacOS / Google Chrome Version 69.0.3497.100 (Official Build) (64-bit)

### Reproduction link
[https://codepen.io/anon/pen/YJvXrw](https://codepen.io/anon/pen/YJvXrw)

### Steps to reproduce
```
const columns = [{
  title: 'Name',
  dataIndex: 'name',
  sorter: true, // This sorter gets stuck
  key: 'name',
  render: name => (<strong>{name}</strong>)
}, {
  title: 'Age',
  dataIndex: 'age',
  sorter: true, // This sorter works correctly
  key: 'age',
}];
```

Edit: This only seems to happen to the sort state when columns are inside render, so I believe it's related to [#12571](https://github.com/ant-design/ant-design/issues/12571).

### What is expected?
Sort should toggle from ascend/descend/none.

### What is actually happening?
Sorter gets stuck on descending sort.

**Comment by ilanus** [comment]
https://codepen.io/anon/pen/NOzGmQ

**Comment by afc163** [comment]
Just move columns outside render: https://codepen.io/anon/pen/JmZRXp?editors=0010

**Comment by gijo-varghese** [comment]
@afc163 I'm facing the same issue. Moving it outside render function fixed the issue. But there are cases where props change and columns filers may change. Moving outside doesn't work in that situation

**Comment by adamdarr** [comment]
@gijo-varghese In that case, you can use controlled mode to manually set the `sortOrder`
