### ISSUE TITLE
feature request: comment component

### ISSUE THREAD

**Issue by ilanus** [ant-design/ant-design#12739]
### What problem does this feature solve?
comments enable discussions on page, blog post or other site content.

### What does the proposed API look like?
new comment component

### Picture for illustration purposes
<img width="467" alt="screenshot 2018-10-20 at 00 30 28" src="https://user-images.githubusercontent.com/9677898/47246656-63d7ac00-d3ff-11e8-8739-cd5b80fd4792.png">

**Comment by yesmeck** [comment]
Basicly, it's a list https://ant.design/components/list/#components-list-demo-basic

**Comment by ilanus** [comment]
@yesmeck I'm aware of list component 👍 but I was aiming for something more advanced and specific for comments example: https://semantic-ui.com/views/comment.html

**Comment by afc163** [comment]
We could consider it in future.

**Comment by ilanus** [comment]
@afc163 are there any sketch mock-ups for the comment at the moment? I could submit PR with start point then we can extend it

**Comment by ztplz** [comment]
Sounds good.

**Comment by ilanus** [comment]
Had a little bit of time to start working on that 😄will make PR soon
<img width="1426" alt="screenshot 2018-10-21 at 20 41 32" src="https://user-images.githubusercontent.com/9677898/47270839-d5d00280-d571-11e8-831f-c338204e8230.png">

**Comment by kalalumbeng** [comment]
gtyrwreyery
