### ISSUE TITLE
Spin 闪动问题

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#1273]
Spin 用于页面和区块的加载中状态，但如果加载速度比较快，Spin 一出现就立刻消失，看起来就是闪动了一下。

在 http://ant.design/components/spin/#demo-nested 中快速切换状态可以看到这个问题。

**Comment by afc163** [comment]
小而美的优化，可以有。加入 debounce

**Comment by RaoHai** [comment]
PR https://github.com/ant-design/ant-design/pull/1606 

这样改如何？
