### ISSUE TITLE
Icons in esm for webpack concatenation

### ISSUE THREAD

**Issue by hlehmann** [ant-design/ant-design#12732]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently I'm directly importing icons definitions from the `@ant-design/icons/lib/` files. But Webpack concatenation doesn't work because there are not available in a es module format. 

Because this is a lot of small modules, concatenation could have a big impact in the bundle size.

### What does the proposed API look like?
Generate an `es` directory with all files in es format.

**Comment by afc163** [comment]
trace #12011

**Comment by hlehmann** [comment]
What about generating esm files? Should I create an issue in https://github.com/ant-design/ant-design-icons?

#12011 is about targeting only needed definition files.
