### ISSUE TITLE
Allow Tooltip above slider to permanently be visible

### ISSUE THREAD

**Issue by 8shaks** [ant-design/ant-design#12743]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature would allow the slider tooltip to permanently be visible instead of only being visible when users are dragging on the slider handle. This would be useful since it would allow devs to customize their website more. It would also allow the user to always be able to see the value of the slider.

### What does the proposed API look like?
`<Slider
defaultToolTip={true}/>`

**Comment by zy410419243** [comment]
if you don't want to wait for upgrading,  you can change code in index.tsx which is in node_modules/antd/slider, around line 85 to 93, as below
``` javascript
var _this$props = _this.props,
   tooltipPrefixCls = _this$props.tooltipPrefixCls,
   tipFormatter = _this$props.tipFormatter,
   defaultToolTip = _this$props.defaultToolTip;

   var visibles = _this.state.visibles;

   var visible = tipFormatter && visibles[index] || dragging || defaultToolTip : false;

   return React.createElement(
```
then, you can try <Slider defaultToolTip /> as you suppose.

If this issue will be upgraded, I will take it.

**Comment by 8shaks** [comment]
So how long would it be until it is upgraded?

**Comment by 8shaks** [comment]
Also how I would make so if users pull my code from GitHub and do an npm install they get the customized Index.tsx that I made?

**Comment by 8shaks** [comment]
Thanks
