### ISSUE TITLE
RangePicker 可以选择相同的month

### ISSUE THREAD

**Issue by jinxin0112** [ant-design/ant-design#12753]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
RangePicker的mode为month的时候，例如： 当一个选择框选择了十月， 第二个选择框默认只能从十一月开始选择， 期望可以增加一个api使第二个选择框可以选择十月，使其能够查看单独一个月内的信息

### What does the proposed API look like?
```js
class ControlledRangePicker extends React.Component {
  state = {
    mode: ['month', 'month'],
    value: [],
  };

  handlePanelChange = (value, mode) => {
    this.setState({
      value,
      mode: [
        mode[0] === 'date' ? 'month' : mode[0],
        mode[1] === 'date' ? 'month' : mode[1],
      ],
    });
  }

  render() {
    const { value, mode } = this.state;
    return (
      <RangePicker
        placeholder={['Start month', 'End month']}
        format="YYYY-MM"
        value={value}
        mode={mode}
        onPanelChange={this.handlePanelChange}
       sameMonth={true} // 新增api
      />
    );
  }
}
```

**Comment by zombieJ** [comment]
Hi, `mode` of month picker is reuse of the range panel, if it can't satisfy your requirement, you can use the start & end: https://ant.design/components/date-picker-cn/#components-date-picker-demo-start-end
