### ISSUE TITLE
when i switch language from en to ch? Modal.confirm has some problem.

### ISSUE THREAD

**Issue by yanguoyu** [ant-design/ant-design#12768]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
mac osx 10.13 chrome  69.0.3497.100

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l5om13w35q)

### Steps to reproduce
when i switch language from en to ch, then i call Modal.confirm to show a modal, the modal's onOk text and onCancel text is wrong.

### What is expected?
the modal's onOk text and onCancel text is ch.

### What is actually happening?
the modal's onOk text and onCancel text is en.

**Comment by hengkx** [comment]
`LocaleProvider` remove `key`. [https://codesandbox.io/s/ymjpl4rr91](https://codesandbox.io/s/ymjpl4rr91).

**Comment by hengkx** [comment]
A new component is created when `key` changes. The previous component is destroyed and `componentWillUnmount` is called to cause the language change to be initialized. [https://github.com/ant-design/ant-design/blob/master/components/locale-provider/index.tsx#L76](https://github.com/ant-design/ant-design/blob/master/components/locale-provider/index.tsx#L76)

**Comment by yanguoyu** [comment]
thanks

**Comment by yanguoyu** [comment]
can you help me understand why unmount need reset the runtimeLocale?
can i do nothing in the componentWillUnmout?

**Comment by hengkx** [comment]
Is handled internally by the component.see [code](https://github.com/ant-design/ant-design/blob/master/components/locale-provider/index.tsx#L76)

**Comment by yanguoyu** [comment]
i mean why can't i remove the componentWillUnmount handler?

**Comment by hengkx** [comment]
> A new component is created when `key` changes. The previous component is destroyed and `componentWillUnmount` is called to cause the language change to be initialized. https://github.com/ant-design/ant-design/blob/master/components/locale-provider/index.tsx#L76

@yanguoyu remove `key` done.
