### ISSUE TITLE
antd 表单 getFieldDecorator 包裹自定义组件，校验规则可以生成，但是样式和提示不显示

### ISSUE THREAD

**Issue by zjscy666** [ant-design/ant-design#12762]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
全部

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
父组件MedicalListModal.jsx，这是一个modal
renderFormRow(modalData) {
        const { form: {getFieldDecorator}, handleAction } = this.props;
        let rowNum = modalData.length;
        let _arr = new Array(rowNum).fill(null);
        return (
            _arr.map((v, i) => {
                return (<FormItem
                    key={i}
                    {...this.formItemLayout}
                    label={modalData[i].label}
                >
                    {
                        modalData[i].type === 'autoComplete' && <EasyAutoComplete
                            data={modalData[i]}
                            getFieldDecorator={getFieldDecorator}
                            onSearchName={modalData[i].onSearch}
                            paramsField={modalData[i].id}
                            handleAction={handleAction}
                        />
                    }
                </FormItem>)
            })
        );
    };

export default Form.create()(MedicalListModal);

子组件 EasyAutoComplete.jsx
render() {
    const { dataSource } = this.state;
    const { data, getFieldDecorator, dataIndex } = this.props;
    let _id = data.id ? data.id : dataIndex;
    let initialValue = data[dataIndex] ? data[dataIndex]   '' : '';
    return (
      getFieldDecorator(_id, {
        rules: [{
          required: data.required, message: data.message,
        }],
        initialValue: initialValue,
      })(
        <AutoComplete
          dataSource={dataSource}
          onSelect={onSelect}
          onSearch={this.handleSearch}
          placeholder={data.placeholder}
        />
      )
    );
  }

export default EasyAutoComplete;

data.required是true,但是没有出现左边红色的*和相应的message提示

### What is expected?
期望出现提示和左边的红色*和相应的message提示

### What is actually happening?
data.required是true,但是没有出现左边红色的*和相应的message提示

---
重现链接随便写的，虽然校验可以，但是信息和样式不显示，用户无法及时获得相关信息

**Comment by zjscy666** [comment]
https://codesandbox.io/s/53qqmz5l3p
已经创建，但是貌似线上的有个问题，当你输入后删除到空，会报
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.
This error overlay is powered by `react-error-overlay` used in `create-react-app`.
我本地就不会，抛开这个，点击页面上console,可以看到async-validator: 
["micName is required"]
0: "micName is required"，
但是校验的样式提示啥的都没触发，麻烦作者大大看看

**Comment by misumi111** [comment]
同有这个问题。
FormItem包裹自定义组件将会丢失校验样式和提示。

**Comment by zombieJ** [comment]
FormItem 需要从子组件获取表单状态，需要紧跟着 `getFieldDecorator`: https://codesandbox.io/s/n5xrw3x44
