### ISSUE TITLE
microsoft edge下Table组件column对不齐

### ISSUE THREAD

**Issue by Chastrlove** [ant-design/ant-design#12767]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
win10 microsoft edge

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/18jk440vpl)

### Steps to reproduce
* 任意创建一个表格，使column定宽，如果column中的实际的数据长度大于设置的column长度，在edge浏览器下，thead与tbody无法对齐

### What is expected?
win10 microsoft edge下table能与chrome下一样换行对齐

### What is actually happening?
win10 microsoft edge下table未对齐，单元格长度远远大于设置的column长度

**Comment by afc163** [comment]
https://codesandbox.io/s/1rql450m77
