### ISSUE TITLE
[0.12.0]在android的微信浏览器中显示空白

### ISSUE THREAD

**Issue by bestv2** [ant-design/ant-design#1276]
在版本0.12.0中
通过android 微信浏览器访问显示空白，ios的微信浏览器没有该问题。
如果使用npm run build 打包js 访问，在android 微信浏览器中可以显示，但是css显示不正产，无法正常调用js。

**Comment by afc163** [comment]
此项目目前暂不支持移动端，后续可能会单独推出移动版本，欢迎关注。
