### ISSUE TITLE
webpack4 配置antd按需加载build和start都报错 Module parse failed: Unexpected character '@' (6:0) You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by wyj580231** [ant-design/ant-design#12777]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
win7 chrom70 react 16.5.2

### Reproduction link
[https://github.com/wyj580231/webpack4-react-redux.git](https://github.com/wyj580231/webpack4-react-redux.git)

### Steps to reproduce
使用antd未在webpack配置babel-plugin-import 按需加载时正常,配置后build和start均报错

### What is expected?
正常按需加载使用antd

### What is actually happening?
build和start报错

---
报错信息:

ERROR in ./node_modules/_antd@3.10.1@antd/es/style/index.css 6:0
Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
| /* stylelint-disable declaration-bang-space-before,no-duplicate-selectors,string-no-newline */
| /* stylelint-disable at-rule-no-unknown */
> @font-face {
|   font-family: "Chinese Quote";
|   src: local("PingFang SC"), local("SimSun");
 @ ./node_modules/_antd@3.10.1@antd/es/spin/style/css.js 1:0-31
 @ ./src/routes/Loading.js
 @ ./src/App.js
 @ ./src/index.js
 @ multi @babel/polyfill ./src/index.js

**Comment by wyj580231** [comment]
webpack.config.js配置信息:
 {
        test: /\.jsx?$/, 
        loader: "babel-loader",
        exclude: [
          path.resolve("./node_modules")
        ],
        query: {
          presets: ["@babel/react"],
          plugins: [
            "@babel/proposal-class-properties",
            "@babel/plugin-syntax-dynamic-import",
            [
              "import",
              { libraryName: "antd", libraryDirectory: "es", style: "css" }
            ]
          ]
        }
      },

**Comment by yesmeck** [comment]
不要把 less-loader 用在 antd 的 css 上，或者 `{ libraryName: "antd", libraryDirectory: "es", style: "less" }`

**Comment by drdevelop** [comment]
@yesmeck { libraryName: "antd", libraryDirectory: "es", style: "less" }按照这样配置antd的样式都无法引入进来
