### ISSUE TITLE
怎么才能知道Model中内容已经完全渲染完成了

### ISSUE THREAD

**Issue by qiaogr** [ant-design/ant-design#12782]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Model中的children在ReactDOM.render的回调之后才被渲染，我怎么才能知道Model中内容已经完全渲染完成了呢

### What does the proposed API look like?
我有一个需求，希望在ReactDOM.render的回调函数中获取Model中的children的内容，但是Model中的children在ReactDOM.render的回调之后才被渲染。
我希望在Model中能有一个类似onLoadSuccess之类的回调。

**Comment by yesmeck** [comment]
```javascript
class MyComponent extends React.Component {
   componentnDidMount() {
      // component rendered
   }
}

<Modal>
  <MyComponent />
</Modal>
```

**Comment by chenshuai2144** [comment]
class DEMO extends React.PrueComponent {
   componentnDidMount() {
      this.props.onInit();
   }
}

<Modal>
  <DEMO onInit={()=>console.log("run")}/>
</Modal>

**Comment by qiaogr** [comment]
多谢
