### ISSUE TITLE
Cannot use react-router v4 Link component inside notification

### ISSUE THREAD

**Issue by gibbsfromncis** [ant-design/ant-design#12781]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Mac OS

### Reproduction link
[https://codepen.io/anon/pen/ReYZwj?editors=0010](https://codepen.io/anon/pen/ReYZwj?editors=0010)

### Steps to reproduce
1. Put <Link> inside notification description
2. Try to show Notification
3. Get Error

### What is expected?
Expect it to work

### What is actually happening?
The link doesn't display real error like on local setup. The error I get on local setup is the following:
`Failed context type: The context `router` is marked as required in `Link`, but its value is `undefined`
`You should not use <Link> outside a <Router>`

I have tried to use `getContainer` to put notification inside `<Router>` but it doesn't help

**Comment by hengkx** [comment]
`Link` needs to be in `BrowserRouter`.
try `this.props.history.push('/')` Route jump.
```js
 notification.open({
      message: 'Notification Title',
      description: (
        <div>
          <Button onClick={() => { this.props.history.push('/'); }}>Test</Button>
        </div>
      )
});
```

**Comment by gibbsfromncis** [comment]
Thx it works
