### ISSUE TITLE
Cascader: search twice and text overlayed

### ISSUE THREAD

**Issue by wendzhue** [ant-design/ant-design#12787]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Chrome

### Reproduction link
[https://ant.design/components/cascader-cn/#components-cascader-demo-search](https://ant.design/components/cascader-cn/#components-cascader-demo-search)

### Steps to reproduce
Search and search again.

### What is expected?
No overlay.

### What is actually happening?
Overlay.

![image](https://user-images.githubusercontent.com/12122021/47339302-6d963380-d6cd-11e8-9c3f-953198c49d81.png)

**Comment by zombieJ** [comment]
Could you provide a snapshot for this?
![kapture 2018-10-28 at 10 49 59](https://user-images.githubusercontent.com/5378891/47611394-6c834e80-da9f-11e8-91a6-b1d2af9e9626.gif)

**Comment by wendzhue** [comment]
Does it has anything to do with my environment? Chrome: Version 70.0.3538.77, Windows 10.

Check this link: https://drive.google.com/file/d/1g_F1-tO2eNsyk3JmZ3SYDwon1L9S1UO4/view

The version is 3.10.3 and the problem is still there.

**Comment by afc163** [comment]
Please help us fix it cause we can't find envioronment to reproduce it.
