### ISSUE TITLE
getFieldDecorator包裹了自定义组件 在切换的时候值就没法保存了 这是自定义组件

### ISSUE THREAD

**Issue by zjscy666** [ant-design/ant-design#12791]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
全部

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
1.https://preview.pro.ant.design/list/table-list这个链接，在规则名称等input中填充值，点击下方展开，收起，值都可以保存，但是我用getFieldDecorator包裹自己的封装的组件，结果没法在点击展开收起的时候获得值
parent.jsx
getFieldDecorator(data[i].id)(
                        <EasyAutoComplete 
                        />
                    )

EasyAutoComplete .jsx
 render() {
    const { dataSource } = this.state;
    const { data, getFieldDecorator, dataIndex } = this.props;
    let _id = data.id ? data.id : dataIndex;
    let initialValue = data[dataIndex] ? data[dataIndex]   '' : '';
    return (
        <AutoComplete
          dataSource={dataSource}
    );
  }

export default EasyAutoComplete;
代码雷同

### What is expected?
点击展开收起可以保存相关的数据

### What is actually happening?
点击展开收起没有保存相关的数据

**Comment by afc163** [comment]
因为你的 TestInput 完全不接收 `value`。

https://codesandbox.io/s/98x5wxjw14

**Comment by zjscy666** [comment]
谢谢，但是有个问题，如果我调用TestInput这个组件的时候，有一大堆自己的属性，那么我在TestInput里面的<Input {...this.props}>可能会出现Input 不能识别相关的属性报错或者属性冗余，比如我调用<TestInput name={data[i].id} placeholder={data[i].placeholder} fnObj={this.fnObj} testProps = {this.testProps} />
这时候如果使用<Input {...this.props} />会有属性冗余，因为我完全不需要fnObj和testProps等属性，有啥办法吗？如果我用<Input {...this.restprops} />去除多余属性，那么也会有问题，我拿出来的属性不一定在那里用到，违反开发的原则，有啥好的办法解决吗

**Comment by afc163** [comment]
需要哪个属性传哪个，或者不需要哪个删哪个，自行决定吧。

**Comment by zjscy666** [comment]
value和onChange是必须的？只有有了这2个，才可以把value保存下来，其他的随便传是吗？
