### ISSUE TITLE
请问有办法把折叠面板搞成可以拖拽来调换顺序的么？

### ISSUE THREAD

**Issue by haanyip** [ant-design/ant-design#12790]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户添加折叠项 又想能自己改变折叠项的顺序

### What does the proposed API look like?
直接加一个属性支持 比如 isDraggable = {true | false}

**Comment by afc163** [comment]
暂不支持。
