### ISSUE TITLE
[Bug] InputNumber return an empty string '' when it was cleared

### ISSUE THREAD

**Issue by zhouhailong** [ant-design/ant-design#12795]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
any

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pwzl64jk1q)

### Steps to reproduce
When clear the InputNumber value.

### What is expected?
It should only return 'number' or 'undefined'

### What is actually happening?
It returned an empyt string ''.

---
When I use InputNumber's onChange callback, I wrote like:

~~~
receivInputNumberValue = (val = 0) => {
  console.log(val)
}
~~~

I expected that when clear the InputNumber, I will set the 'val' to be 0, but I receive an empty string ''. So the default value 0 is not applied.

**Comment by sqfbeijing** [comment]
The same with me

**Comment by zombieJ** [comment]
Hi @zhouhailong , `onChange` of InputNumber will return string when the value of input can not convert into number type. So if you don't want string value, you can check the value type: https://codesandbox.io/s/jlrx0yzzy9

**Comment by jjhbw** [comment]
I was caught out by this issue because the Typescript type definitions don't reflect this reality.

```typescript
onChange?: (value: number | undefined) => void;
```

Should instead be something like
```typescript
onChange?: (value: number | string | undefined) => void;
```

Right?

**Comment by mikewheaton** [comment]
Is there a new issue tracking this? Looks like the TypeScript definitions should be updated as @jjhbw pointed out, or the component should return `undefined` instead of `""` when the field is blank.

**Comment by Artyom-Ganev** [comment]
So, why it still returns empty string `""` instead of `undefined`?
