### ISSUE TITLE
InputNumber support addonBefore and addonAfter

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#12794]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Support addon in InputNumber like Input.

### What does the proposed API look like?
```jsx
<InputNumber addonBefore={<Select />} addonAfter={<Select />} />
```

![_20181023170456](https://user-images.githubusercontent.com/1730277/47349358-0f297f00-d6e6-11e8-8431-de82fbc106ff.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10846#issuecomment-395663125
https://github.com/ant-design/ant-design/issues/1228#issuecomment-199338244

**Comment by m430** [comment]
I have a solution to resolve this issue by custom a component `CusInputNumber`

```html
import React from "react";
import cx from 'classnames';
import { InputNumber } from "antd";
import "./index.less";

function CusInputNumber(props) {
  const handleKeyUp = (e) => {
    e.target.value = e.target.value.replace(/[^\d.]/g, "");
    e.target.value = e.target.value.replace(/\.{2,}/g, ".");
    e.target.value = e.target.value
      .replace(".", "$#$")
      .replace(/\./g, "")
      .replace("$#$", ".");
  };

  const cls = cx("ant-input-wrapper", "ant-input-group", {
    "addonAfterInput": props.addonAfter
  })

  return (
    <div className={cls}>
      <InputNumber onKeyUp={handleKeyUp} style={{ width: "100%" }} {...props} />
      {props.addonAfter && (
        <span className="ant-input-group-addon">{props.addonAfter}</span>
      )}
    </div>
  );
}
```

Less as：
```less
.ant-input-group {
  display: inline-table;
  &.addonAfterInput {
    .ant-input-number {
      border-top-right-radius: 0;
      border-bottom-right-radius: 0;
    }
  }
}
```

**Comment by nerdess** [comment]
Hm, as per documentation InputNumber should suppot addonAfter/addonBefore now: https://ant.design/components/input-number

However, this code

`<InputNumber value="sum" addonAfter="Euros" />`

Leads to a warning in the console: 

_React does not recognize the `addonAfter` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `addonafter` instead. If you accidentally passed it from a parent component, remove it from the DOM element._

?!

**Comment by Pacheco95** [comment]
@nerdess actually they even not appear in type declaration resulting in this error:
```
Property 'addonAfter' does not exist on type 'IntrinsicAttributes & InputNumberProps<ValueType> & { children?: ReactNode; } & { ref?: Ref<HTMLInputElement> | undefined; }
```

**Comment by nerdess** [comment]
@Pacheco95 I am not that familiar with Typescript, so you mean that addonAfter is not implemented so far? Strange that it appears in the docs then....

**Comment by Pacheco95** [comment]
Yes. It looks like not implemented. I disabled eslint to test and didn't work

**Comment by Pacheco95** [comment]
I found the "problem"... I was using an outdated version :eyes: :man_facepalming:
