### ISSUE TITLE
Function in RangePicker's presetted ranges not work

### ISSUE THREAD

**Issue by Evoque** [ant-design/ant-design#12806]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
Windows, Chrome

### Reproduction link
the origin issue is here[https://github.com/ant-design/ant-design/issues/8281](https://github.com/ant-design/ant-design/issues/8281), but the function in ranges is not work!!!

### Steps to reproduce
```
     <RangePicker
            ranges={_ => { 
                return {
                    '半小时': [moment().add(-0.5, 'hours'), moment()],
                    '1小时': [moment().add(-1, 'hours'), moment()],
                    '3小时': [moment().add(-3, 'hours'), moment()],
                    '12小时': [moment().add(-12, 'hours'), moment()],
                    '1天': [moment().add(-1, 'days'), moment()],
                    '3天': [moment().add(-3, 'days'), moment()],
                    '7天': [moment().add(-7, 'days'), moment()],
                }
            }}
            showTime
            format="YYYY/MM/DD HH:mm:ss"
            onChange={onChange}
     />
```

### What is expected?
get the latest value using the function in ranges prop

### What is actually happening?
function in ranges won't work.

**Comment by zombieJ** [comment]
Looks like the doc not correct. It should be: `{ [range: string]: moment[] } | { [range: string]: () => moment[] }`

https://codesandbox.io/s/6jxxyzrz1n

**Comment by Evoque** [comment]
Nice! Thanks.
