### ISSUE TITLE
getFieldDecorator内绑定的组件允许在校验时修改自身的值

### ISSUE THREAD

**Issue by OliverJason** [ant-design/ant-design#12809]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在输入值、或者选中值经过校验规则之后，允许在此动态修改值

### What does the proposed API look like?
当前或较早版本下，自定义表单校验函数内都是无法直接修改当前组件的值，但是可以修改其他field的值，希望能将这个问题解决一下

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
