### ISSUE TITLE
InputNumber在父页面组件update并re-render的时候，会失去自身之前的数字选中状态。

### ISSUE THREAD

**Issue by amourguo** [ant-design/ant-design#12808]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
macOS High Sierra (版本10.13.4), Google Chrome  69.0.3497.100（正式版本）（64 位）, react@15.4.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk659187k7)

### Steps to reproduce
1、在InputNumber框中选中全部或部分数字；
2、页面父组件因为每秒钟会接收DeepStream推送，所以每次推送都会致使update页面组件；
3、InputNumber在页面父组件update并re-render的时候，既便是InputNumber的值未发生变化，也会失去之前的数字的选中状态；
（但是如果把InputNumber换成普通Input组件的话，就一切正常；怀疑是InputNumber的默认Parser/Formatter导致的InputNumber认为的值发生了变化而重新Render自己）

```javascript
      <Form.Item
        label={t('APP_OPEN_PRICE')}
      >
        {getFieldDecorator('openPrice', {
          initialValue: 1,
          rules:  [{
            required: true,
            message: t('FORM_REQUIRED')
          }, {
            type: 'number',
            message: t('FORM_NUMBER_INCORRECT')
          }, {
            validator: this.checkPriceStep
          }]
        })(
          <InputNumber />
        )}
      </Form.Item>
```

### What is expected?
InputNumber像普通的Input组件一样的行为，即当值不发生变化的话，InputNumber不会随当前组件的更新而Re-render，随之也不会失去Selected的状态.（目前Input在选中框内文本后的行为是正常的）

### What is actually happening?
InputNumber在页面父组件update并re-render的时候，既便是InputNumber的值未发生变化，也会失去之前的数字的选中状态；

**Comment by zhangkuiworld** [comment]
所以现在的解决方案是？更新哪个版本？
