### ISSUE TITLE
自定义表单组件里getFieldProps如何传递？

### ISSUE THREAD

**Issue by miaojiuchen** [ant-design/ant-design#1280]
我有一个复合组件，类似于slider demo里那个带输入框的slider：
http://ant.design/components/slider/

```javascript
class LevelSwicher extends React.Component {
    constructor(props) {
        super(props);
        this.state = {
            value: 1
        }
    }
    onChange(value) {
        this.setState({
            value: value
        });
    }
    render() {
        const {marks,min,max,...fieldProps} = this.props;
        return (
            <div>
                <Row>
                    <Col span="16">
                        <Slider
                            {...fieldProps}
                            marks={marks}
                            min={min}
                            max={max}
                            value={this.state.value}
                            onChange={this.onChange.bind(this) }
                            />
                    </Col>
                    <Col span="8">
                        <InputNumber
                            style={{ marginLeft: '16px' }}
                            value={this.state.value}
                            onChange={this.onChange.bind(this) }
                            />
                    </Col>
                </Row>
            </div>
        );
    }
}
```

这个是FormItem
```javascript
<Form.Item
    {...formItemLayout}
    key="clevel"
    label="消费等级："
    required>
    <LevelSwicher
        {...getFieldProps('clevel')}
        marks={{ 1: "1", 2: "2", 3: "3", 4: "4", 5: "5" }}
        min={1}
        max={5}
    />
</Form.Item>
```

 我这样写，在this.props.form.getFieldsValue() 中始终得不到clevel字段的值，查看了相关的issues和文档，暂时没有找到相关资料，请问哪里写的有问题？

**Comment by benjycui** [comment]
http://ant.design/components/form/#this-props-form-getfieldprops-id-options

**Comment by miaojiuchen** [comment]
@benjycui 谢谢，但是我看过这段了。。。
我把它生成的props传递给了子组件的slider，问题就在，最后收集表单值的时候获取不到这个slider的值，请问具体应该如何传递这些属性给子组件里的表单项？

**Comment by benjycui** [comment]
你把 `onChange` 覆盖了

![image](https://cloud.githubusercontent.com/assets/3580607/14070534/7e3b3f50-f4da-11e5-8455-cc46c41ec2a1.png)

**Comment by miaojiuchen** [comment]
@benjycui 十分感谢，取消覆盖后的确能获取到表单项的值。
但是，如果我不覆盖这个事件，那要怎样实现 http://ant.design/components/slider/ 右边第一个demo里 slider跟InputNumber的联动呢？我期望表单能够提取这两个组件联动所代表的值。

**Comment by benjycui** [comment]
更新了下文档 https://github.com/ant-design/ant-design/commit/f4193866b8151f175705eff447521381b4ad9954

**Comment by miaojiuchen** [comment]
@benjycui 我试了一下，trigger传了slider自带的事件onAfterChange，可以实现我要的功能。

但最后一个疑问，文档里有**options.onXXX**，这里似乎可以自定义，如果我trigger="onGetFieldValue"，那options.onGetFieldValue这个应该传一个什么function呢？

如果只能传子组件自带事件的话，有点不理解这个的作用

**Comment by benjycui** [comment]
因为 `getFieldProps` 返回的对象占用了对应的事件，如果你在 `getFieldProps` 外使用了同名事件，就会有冲突。

**Comment by wufeng87** [comment]
看了下rc-xxx的源码，看到this.props.onChange就明白了，谢谢前辈。

**Comment by xieyihao** [comment]
我发现很多issues里都有用这个链接（http://ant.design/components/form/#this-props-form-getfieldprops-id-options ）来解释，可是这个链接失效了啊，this-props-form-getfieldprops-id-options的例子是怎样的？还能在哪儿找到？

**Comment by rayallen001** [comment]
在你这个例子中，正好Slide有onAfterChange，如果其他组件没有onAfterChange怎么办呢，比如DatePicker就只有onChange。自定义组件可以覆盖onChange事件，但在你的onChange回调中，需要手动调一下被覆盖的onChange方法。
例如：
`    handleChangeDatePicker(datePickerId, value) {
        // 由于覆盖了DatePicker通过getFieldProps()方法自动设置的onChange事件，需要手动调用一次onChange
        const { getFieldProps } = this.props.form
        getFieldProps(datePickerId).onChange(value)

        this.updateSelfValue()
    }

`<DatePicker {...getFieldProps('mydate', {initialValue: new Date())})}
                            onChange={this.handleChangeDatePicker.bind(this, 'mydate')}/>`
`
