### ISSUE TITLE
Form 表单 Item 错乱问题

### ISSUE THREAD

**Issue by chenxiaochun** [ant-design/ant-design#12803]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
操作系统：windows7，浏览器：Chrome 版本 70.0.3538.67（正式版本） （32 位）

### Reproduction link
在线链接demo：https://codesandbox.io/s/k5xy509k8v

### Steps to reproduce

如下界面所示，直接点击确定按钮会发生错乱。经过排查，发现这个`ant-col-12`元素在包含错误提示信息和不包含错误提示信息时，渲染的高度是不一样的。所以，如果把它们强制为相同的高度之后，就没有此问题了。比如：

```css
.ant-col-12 {
  height: 63px !important;
}
```
![image](https://user-images.githubusercontent.com/1744713/47408005-3dfc2f80-d790-11e8-9e8b-67bcd556d239.png)

### What is expected?
界面不会错乱

### What is actually happening?
界面会错乱

**Comment by chenxiaochun** [comment]
已更新在线 demo 链接

**Comment by afc163** [comment]
无法重现。

**Comment by afc163** [comment]
好，我来看看。

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/47415965-3d22c800-d7a7-11e8-918d-dcd8acbc1559.png)
windows 10,chrome latest 正常

**Comment by chenxiaochun** [comment]
抱歉，那应该是在 win7 上才会有。

**Comment by afc163** [comment]
<img width="393" alt="image" src="https://user-images.githubusercontent.com/507615/47692175-c024a200-dc2f-11e8-8c9b-e252f0913cd6.png">

**Comment by chenxiaochun** [comment]
好的，谢谢

**Comment by ztplz** [comment]
@afc163  @zombieJ  
https://github.com/ant-design/ant-design/blob/master/components/form/style/index.less#L131
`line-height` 在chrome、firefox、opera上表现都是不一样的，改`line-height`的时候，经常修好这个浏览器，但是另外的浏览器又不正常了。
像https://github.com/ant-design/ant-design/issues/13214 和 https://github.com/ant-design/ant-design/issues/12978
![image](https://user-images.githubusercontent.com/17755202/51086217-e7930180-177e-11e9-98aa-ffc2f7219093.png)
光stackovstackoverflow的line-height在不同浏览器上不一样的问题就有5w多个，看起来是个很坑的属性，浏览器处理它的方式都不一样，尤其是带有很高精度的浮点数的情况下。
但是现在现在css代码里很多line-height，有的还是用 x / y 这样容易造成高精度浮点数赋值给line-heght的，

**Comment by ztplz** [comment]
可以弄个组件库开发规范  慎用这些浮点数  line-height  防止后人踩坑

**Comment by zombieJ** [comment]
因为现在 FormItem 和 withError FormItem 占高的方式不太一样，FormItem 里用的 margin 来顶出一个空间来。如果要调整的话，我建议是和 withError 一样用个空 space 来代替 margin 让两边高度计算方式一致。

**Comment by zjafei** [comment]
试试看 我这里是没问题了
.ant-form-item-children{
    position: relative;
    display: inline-block;
    height: 33px;
}
