### ISSUE TITLE
InputNumber 组件设置精度 precision 之后实时更新导致数值四舍五入自增问题

### ISSUE THREAD

**Issue by 0326** [ant-design/ant-design#12813]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
问题 demo 参考：https://codesandbox.io/s/l22pwn9309
当组件限制了 precision=2 精度时，某些业务场景下需要监听 onChange 事件实时去设置组件的 value，如果用户输入2.225，这时候value 会四舍五入变为2.23，如果用户连续输入大于5的尾数，数值框就会不断变化，让人感觉会像是 bug 一样。

### What does the proposed API look like?
 这种情况下期望能对自动四舍五入做一个配置，开发者可以控制是否需要小数四舍五入。比如设置 InputNumber 的属性 autoRounding={false}就可以去掉这个功能。

**Comment by zombieJ** [comment]
InputNumber 内部使用 `toFixed` 做小数截取，如果不希望四舍五入。建议自己对数字做处理。

**Comment by CryChow** [comment]
我因为这个被qa记了bug，四舍五入没问题，但是四舍五入到9以后，小数位会进一，从而少一位，要是用户持续在输入框输入5以上的数字，小数位最终全部依次进一，最终小数全无，用户输入的就变成整数，这时候的交互就很难说不是bug。如果能一直保证小数位永远在precision设置的精度下，那就不会出现上述问题了。
