### ISSUE TITLE
BackTop问题

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#12811]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
antd3.10.1 chrome 64.0.3282.186（正式版本） （64 位）

### Reproduction link
[https://ant.design/components/back-top-cn/](https://ant.design/components/back-top-cn/)

### Steps to reproduce
BackTop 样式有问题 ，样式如下。。我也不知道怎么复现，不知道是怎么出来的。。我查看我们的代码没有改到这里的。。我用F12 查看backtop的样式。如下
.ant-back-top-icon {
    background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACQAAAAoCAYAAACWwljjAAAABGdBT…piZ2PyYO1EVykesGfZEESsCkweyR8MUW V8uJ1gkYipmpdP1pm2aJVPEGzAAAAAElFTkSuQmCC) 1% no-repeat;
}
这里的1% ，不知道是怎么出来的。。

### What is expected?
应该是100%

### What is actually happening?
应该是1%

**Comment by afc163** [comment]
没重现无法排查。

**Comment by lucklove** [comment]
The same

**Comment by LbhFront-end** [comment]
遇到同样的问题
