### ISSUE TITLE
editableTable component when column add flex attribute has a bug

### ISSUE THREAD

**Issue by WangJM001** [ant-design/ant-design#12829]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1y3wnk8zv4)

### Steps to reproduce
1、add flex:'right' to operation column 
2、click 'edit' in the column
3、input form values
4、click 'save' in the column

### What is expected?
1、click 'edit' in the column can show edit form 
2、click 'save' to save the form

### What is actually happening?
 click 'edit' in column and change input value ，but click 'save' can not save the form value, i can not get the new value from the edit form

**Comment by afc163** [comment]
This demo do not adapt for fixed column situation, you have to dig it by youself, and welcome PR for sure 😆~
