### ISSUE TITLE
progress的format无法使用html，比如<br />换行

### ISSUE THREAD

**Issue by kinghoo5201** [ant-design/ant-design#12821]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求基于antd中的progress，要求文字换行显示

### What does the proposed API look like?
当format返回的string中包含br标签的时候使用dangerouslySetInnerHTML来将html塞进去，包含其他html的时候不用，这样解决了安全问题

**Comment by afc163** [comment]
你这不已经找到解决方案了。

**Comment by kinghoo5201** [comment]
> 不想用 `dangerouslySetInnerHTML ` 就返回个 Node 如何？https://codesandbox.io/s/w00j0mm6rk

谢谢，学到了，原来返回值类型除了string，还有node的呀，不过api里format的返回值没有写详细，容易让使用者看不懂呢，是否加上返回值得类型。
