### ISSUE TITLE
typescript如何对getFieldDecorator自动注入到组件里的value和onChange进行声明？

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#12828]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

ant design官方文档里面有介绍到，经过 getFieldDecorator 包装的控件，表单控件会自动添加 value（或 valuePropName 指定的其他属性） onChange（或 trigger 指定的其他属性）。
我想请问如何在typescript里面对value和onChange声明？
现在必须把value和onChange标注为可选的，但是我认为ant design应该有定义类似的类型。

求指点如何解决如何在ts中的自定义组件里声明和获取getFieldDecorator自动注入到组件里的value和onChange属性

**Comment by sunOpar** [comment]
同问

**Comment by Peterlhx** [comment]
将value和onchange设为可选参数
`interface IProps {
    value?: any,
    onChange?: any
}`

**Comment by iShawnWang** [comment]
why just closed ?
