### ISSUE TITLE
Table组件与禁止高亮

### ISSUE THREAD

**Issue by XanderXueMingJi** [ant-design/ant-design#12824]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用Table展示行列数据, 当鼠标移到上面时, 背景会变成淡清色, 希望禁止高亮显示

### What does the proposed API look like?
无

**Comment by afc163** [comment]
建议自行样式覆盖。

**Comment by XanderXueMingJi** [comment]
最初我覆盖了, background-color: black; 包括hover, 其效果是鼠标移上时, 内容背景一黑, 接着有迅速变成淡清色

**Comment by qingming418** [comment]
覆盖哪个样式呢？
