### ISSUE TITLE
progress type=circle的时候设置strokeColor属性无法更改图形颜色

### ISSUE THREAD

**Issue by kinghoo5201** [ant-design/ant-design#12825]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
mac,chrome,react16

### Reproduction link
[https://github.com/ant-design/ant-design/tree/master/components/progress](https://github.com/ant-design/ant-design/tree/master/components/progress)

### Steps to reproduce
```jsx
<Progress
            ref={(node: any) => this.progress.push(node)}
            type={'circle'}
            gapPosition="bottom"
            gapDegree={90}
            percent={90}
            format={(percent: any) => {
              return <span>
                {percent}%
                <br />
                cccc
              </span>;
            }}
            strokeColor='#f00'
/>
```

### What is expected?
strokeColor无法更改色彩

### What is actually happening?
环形进度条能更改颜色

**Comment by afc163** [comment]
https://codesandbox.io/s/lxkkn7z3vm

It works.

**Comment by drj17** [comment]
Having the same issue, stroke color for circle is always rgb(16, 142, 233)

**Comment by hfutpath** [comment]
Having the same issue, stroke color for circle is always rgb(16, 142, 233)

Edit: my version is 3.7.3
