### ISSUE TITLE
date range picker responsive?

### ISSUE THREAD

**Issue by dayrlism10** [ant-design/ant-design#12831]
Hi there, 

wanna know does ant design date range picker could be responsive in mobile, or i have to overwrite the function?
![screenshot 2018-10-25 at 5 55 35 pm](https://user-images.githubusercontent.com/38413388/47492275-35ceed80-d87f-11e8-9a05-c056dec7fad9.png)

and one more is that, how i can overwrite css  component like date range picker?

**Comment by lakshaytalkstocomputer** [comment]
Nothing on this??? Dude its big problem!1

**Comment by yuenzp** [comment]
Any solutions?
