### ISSUE TITLE
Table组件如何自定义选中行的样式

### ISSUE THREAD

**Issue by langjt** [ant-design/ant-design#1283]
在Table组件中当选中某行时，如何自定义样式。现在行只有hover样式，我想实现click之后也添加样式，用来标记当前选中行。不想使用rowSelection的单选或多选，这样就可以节省一列的宽度了。

**Comment by afc163** [comment]
rowClick 配合 column.className.

**Comment by langjt** [comment]
大侠，你好
    首先，谢谢你的答复！
    不过，我还是有些不明白，就是设置当前选中行样式，传统的做法是：根据选择器找到TR的DOM，然后给DOM添加样式。
那么，使用react是否也是先找到当前的选择React组件，然后设置其className? 
onRowClick(record, index) 通过该方法，可以找到当前选中的React组件吗？
您的答复中说设置column.className，那是不是所有行都为选中样式了。我之前试了下rowClassName，发现改变它，也是所有行都改变样式了。
我是新手，还望大侠指点，非常感谢。






在 2016-03-28 11:13:28，"偏右" <notifications@github.com> 写道：


rowClick 配合 column.className.

**Comment by afc163** [comment]
写错了，是 rowClassName。

1. 通过 rowClick 实现选择行为，维护一个 `当前选中项` 的 key 列表。
2. 通过 rowClassName 来将 `当前选中项` 标上你需要的 selected 的样式。
