### ISSUE TITLE
【建议】tag组件样式交互问题

### ISSUE THREAD

**Issue by vueZZ** [ant-design/ant-design#12839]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的tag组件更接近button，拥有交互，而不是显示状态的标签

### What does the proposed API look like?
颜色更浅化，类似于element-ui的tag这种，作为状态标记提示

**Comment by afc163** [comment]
tag 视觉迭代过很多版本，暂时不会修改了，感谢反馈。
