### ISSUE TITLE
Unable to find node on an unmounted components always occurs

### ISSUE THREAD

**Issue by sakopqiu** [ant-design/ant-design#12843]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
macos chrome  70.0.3538.67, react 16.6.0 react-dom 16.6.0

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
We are using the `<Button/>` component not the `<Wave/>` component, but it seems the error occurs in Wave's componentDidmount method.
We switched from antd 3.8.4 to 3.9.3 to 3.10.2, but the problem still lurks

```
react-dom.development.js:55 Uncaught Error: Unable to find node on an unmounted component.
    at invariant (react-dom.development.js:55)
    at findCurrentFiberUsingSlowPath (react-dom.development.js:4161)
    at findCurrentHostFiber (react-dom.development.js:4269)
    at findHostInstanceWithWarning (react-dom.development.js:18296)
    at findDOMNode (react-dom.development.js:18774)
    at Wave.componentDidMount (wave.js:118)
    at commitLifeCycles (react-dom.development.js:14685)
    at commitAllLifeCycles (react-dom.development.js:15905)
    at HTMLUnknownElement.callCallback (react-dom.development.js:145)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:195)

```

### What is expected?
This error should never happen

### What is actually happening?
This error should never happen

**Comment by mitjade** [comment]
I get this also on 3.10.4

**Comment by schester44** [comment]
I'm getting this with 3.11.2, react 16.7.0-alpha.2, and react-router 4.3.1.

It usually occurs when selecting a menu item option that triggers a route change or similar.

**Comment by zlv-thisF** [comment]
same issue here;

what troubles me is:
i use react-router's nest Route --  Switch  nest Switch
and Menu from antd;

if i don not use React.Lazy ,all works perfectly, however if i add React.lazy, when click menuItem to navigate route , page collapse, show ' Unable to find node on an unmounted ',  but if i change **inner** Switch from React.Lazy to normal, no error any more..

is there any thing i missed , i dont even know its's a antd's bug or react-router's or react's

**Comment by ztplz** [comment]
Could you provide a sample online demo or github repository?

**Comment by zlv-thisF** [comment]
https://codesandbox.io/s/xorrkwry7w  @ztplz 

thx for help!

**Comment by ztplz** [comment]
@zlv-thisF  Can you tell me how to reproduce this bug?
![image](https://user-images.githubusercontent.com/17755202/50449748-2eea5700-0964-11e9-8c0e-a3140778abfb.png)

**Comment by schester44** [comment]
@ztplz He has his routes backwards in that example. Switch the routes in the App component to be 

````js
   <Switch>
              <Route path="/test" exact render={() => <div>123</div>} />
              <Route apth="/" component={Parent} />
            </Switch>
````

then click on one of the menu items.

**Comment by schester44** [comment]
It only occurs when the `Menu` component is nested inside of a `Suspense` component.

**Comment by ztplz** [comment]
@schester44 Thanks for your reminder. Here is the right way to use route with `Suspense`.
![image](https://user-images.githubusercontent.com/17755202/50452314-5ea15b00-0974-11e9-9311-479bd69ee2dc.png)
https://stackoverflow.com/questions/53300272/failed-prop-type-invalid-prop-component-of-type-object-supplied-to-route

**Comment by zlv-thisF** [comment]
Thx a lot! @schester44  @ztplz,  it does work! 

in my project, may nested a bit more complicated , nested deep inner Switch still throw error above, now i have changed React.suspense wrap all routes to something like:

const Loadable = Component => props => (
  <React.Suspense fallback={<div>Loading...</div>}>
    <Component {...props} />
  </React.Suspense>
);

 <Switch>
      <Route path="/xx/xx/xx" component={Loadable(MyComponent} />
 </Switch>

now all work as expected in my project;

its high time i read the source code of React.Suspense and React.lazy !!!!!!!
