### ISSUE TITLE
add a Tree prop that allow align leaf nodes horizontally

### ISSUE THREAD

**Issue by rikakomoe** [ant-design/ant-design#12848]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In a typical scene, using [tree view](https://ant.design/components/tree-cn/) in a privilege control, like this
![image.png](https://i.loli.net/2018/10/26/5bd30e1037e2e.png)
it would be nice if i could have an option to align the leaf nodes in a horizontal way

### What does the proposed API look like?
horizontal boolean

**Comment by zombieJ** [comment]
这个需求有些定制，也不符合 Tree 的场景。不推荐用 Tree 实现。
当然，你可以魔改 css：https://codesandbox.io/s/1w3zmm9l0q

**Comment by LazyChun** [comment]
> 这个需求有些定制，也不符合 Tree 的场景。不推荐用 Tree 实现。
> 当然，你可以魔改 css：https://codesandbox.io/s/1w3zmm9l0q

这个需求很常见啊，最后的子菜单横排显示，引用菜单太多会导致树列表太长，对客户不友好，所以横排显示最后一级的树，节约空间。以前这个还可以通过改css来实现，现在完全实现不了了。
