### ISSUE TITLE
Hiding error information when the Form value changes

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#12841]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
After setting up {validateTrigger:'onBlur'}, I want to hide the error message when the value of the form item changes.

### What does the proposed API look like?
hideErrorTrigger

**Comment by afc163** [comment]
There is `setFields` you can try out.
