### ISSUE TITLE
Selecting start and end month in RangePicker in month mode doesn't set the range

### ISSUE THREAD

**Issue by chrismcgarry** [ant-design/ant-design#12850]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
Electron 3.0.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3jqm05q65)

### Steps to reproduce
Create a RangePicker with mode set to ['month', 'month']

### What is expected?
Selecting a start and end month should set the range

### What is actually happening?
Nothing, selecting two months just leaves the range picker open

**Comment by zombieJ** [comment]
https://ant.design/components/date-picker-cn/#components-date-picker-demo-mode
