### ISSUE TITLE
react-hook support for form

### ISSUE THREAD

**Issue by xiaoxiangmoe** [ant-design/ant-design#12857]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

**Comment by yesmeck** [comment]
Yay, once the hooks API get stable.

**Comment by djyde** [comment]
Could the team provide a RFC for more detail? And we could discuss in this thread.

**Comment by afc163** [comment]
Merge into #10640

**Comment by andriijas** [comment]
Should release ant design 4.0  with all components that needs it using hooks.

**Comment by hlehmann** [comment]
Adding a public `useForm` should not be a breaking change. It just require to use React 16.7.

Later Ant Design 4.0 could change it's components to rely on react hooks.

**Comment by xiaoxiangmoe** [comment]
@yesmeck Any plan to release the hooks version form API before hooks API get stable? maybe something like  useForm_UNSAFE for testing

**Comment by JannesV** [comment]
Is there any update available for this?

**Comment by yanlee26** [comment]
waiting

**Comment by taozhi8833998** [comment]
keep waiting for this feature !!!

**Comment by remon-nashid** [comment]
This issue shouldn't be closed until hooks support is shipped.

**Comment by iwaduarte** [comment]
Feature very important!!!

**Comment by mushan0x0** [comment]
https://github.com/mushan0x0/rc-form-hooks You can use this library, which has been used in many real projects.

**Comment by pietervanwijk** [comment]
Would love this feature!

**Comment by dimacros** [comment]
Reopen this feature

**Comment by vladkampov** [comment]
Me would like to have it as well please :)

**Comment by Rhjulskov** [comment]
Please consider this! :D

**Comment by 3dw1np** [comment]
Waiting for this !

**Comment by jeggy** [comment]
This will be included in the 4.0 release. You can follow progress on that here: https://github.com/ant-design/ant-design/issues/16911
