### ISSUE TITLE
RangePicker 的allowClear为true时。用户点击清除。还保留着原来的值

### ISSUE THREAD

**Issue by mrandpz** [ant-design/ant-design#12853]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1：列表页的的RangePicker，选择时间，点击搜索，发起请求
2：用allowClear清除输入框的值，再次发起搜索，带的还是上一次搜索的时间。

### What does the proposed API look like?
应当重置当前RangePicker的值。

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

**Comment by wangzongming** [comment]
我也遇到了这个问题
