### ISSUE TITLE
Dropdown SubMenu flickers when using click trigger

### ISSUE THREAD

**Issue by travikk** [ant-design/ant-design#12858]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
macOS, React.JS 16.5

### Reproduction link
[https://gist.github.com/travikk/8419eec9f0a4a95356cce2e6982e9141](https://gist.github.com/travikk/8419eec9f0a4a95356cce2e6982e9141)

### Steps to reproduce
1. Click on "test" button
2. Hover over "sub menu"
3. Click on "3rd menu item"

### What is expected?
The dropdown to close without flickering in top left corner.

### What is actually happening?
The dropdown closes and the submenu flickers for a second in the top left corner.

---
When used with "hover" trigger works fine.

**Comment by yanguoyu** [comment]
@travikk https://codesandbox.io/s/w6jywj1w5l  this example not reproduce your problem.

**Comment by zombieJ** [comment]
hi @yanguoyu , could you provide a gif for this since I can't see the flicker.

**Comment by travikk** [comment]
@yanguoyu for some reason, I can't reproduce it on codesandbox that's why I didn't provide example link.

@zombieJ here is a url to a gif showing the issue:
https://giphy.com/gifs/fikm1KPjuwNLpajrmq

**Comment by zombieJ** [comment]
hi @travikk,
We can't help if no reproduce provide. Will reopen if get reproduce.

**Comment by travikk** [comment]
@zombieJ I did some digging around, and found out that the menu got broken for me when upgrading rc-menu from 7.0.5 to 7.1.0
I'm not sure why it can't by reproduced on codesandbox, but it always happens for me.

**Comment by zombieJ** [comment]
hi @travikk, if no reproduce provide, I can do nothing for this. But you can diff the `rc-menu` to check what updated.

**Comment by travikk** [comment]
@zombieJ i blew away yarn.lock and node_modules, installed everything from scratch and seems to be working ok now.
