### ISSUE TITLE
Input：同时添加onChange事件和{...getFieldProps('material_fee_in')}后，不能输入

### ISSUE THREAD

**Issue by duzliang** [ant-design/ant-design#1286]
`<Input 
            type="number" {...getFieldProps('material_fee_in')}
            onChange={this.calculateTotalFee.bind(this)}
             addonAfter="元"/>`

**Comment by afc163** [comment]
http://ant.design/components/form/#this-props-form-getfieldprops-id-options

**Comment by duzliang** [comment]
已解决，谢谢

**Comment by WHX777** [comment]
请问一下是怎么解决的呢，我也遇到了这个问题呢

**Comment by duzliang** [comment]
@WHX777 [请参考文档](https://ant.design/components/form-cn/#this.props.form.getFieldDecorator(id,-options))
