### ISSUE TITLE
[bug] tree 组件 经打包后出现先‘Cannot read property 'filter' of undefined’

### ISSUE THREAD

**Issue by Dseekers** [ant-design/ant-design#12861]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
win7  chrome   react 16.5.2

### Reproduction link
[https://new-issue.ant.design](https://new-issue.ant.design)

### Steps to reproduce
开发正常使用，打包之后tree组件报错。“Cannot read property 'filter' of undefined”

### What is expected?
打包正常使用

### What is actually happening?
error:“Cannot read property 'filter' of undefined”

---
Duplicate of #12182
但是采用以上的解决方案并没有解决掉改问题

**Comment by afc163** [comment]
https://github.com/afc163/tree-select-demo

这个例子你跑起来有问题么？

**Comment by Dseekers** [comment]
那个例子跑起来没有问题，项目使用create-react-app构建的，webpack版本为3.8.1，打包的是采用dll.js和webpack.prod.js分开打包
以下是dll.js中的配置
`const path = require('path')`
`const webpack = require('webpack')`
`const uglifyJsPlugin = require('uglifyjs-webpack-plugin')`
`module.exports = {`
`  entry: {`
`    vendor: [`
`        'react', `
`        'react-dom', `
`        'immutable', `
`        'redux', `
`        'react-redux', `
`        'react-router-dom',`
`        'antd',`
`        'moment',`
`        'axios',`
`    ],`
`  },`
`  output: {`
`    filename: '[name].dll.js',`
`    path: path.resolve(__dirname, '../public'),`
`    library: '[name]_library', `
`  },`
`  plugins: [`
.....
`    new uglifyJsPlugin({`
`      uglifyOptions: {`
`        output: {`
`          beautify: false,`
`          comments: false,`
`        },`
`        compress: {`
`          warnings: false,`
`          drop_console: true,`
`          collapse_vars: true,`
`          reduce_vars: true`
`        }`
`      }`
`    }),`
....
`  ],`
`}`
