### ISSUE TITLE
Popover first display of wrong position.

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#12868]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
chrome latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2prlx870o0)

### Steps to reproduce
https://codesandbox.io/s/2prlx870o0
![popover-bug](https://user-images.githubusercontent.com/8358236/47637574-27dade80-db97-11e8-95c2-1234e8f31e55.gif)

### What is expected?
normal

### What is actually happening?
first display of wrong position.

**Comment by ilanus** [comment]
Popover content need to Identify the intrinsic height of an image you are passing, It can be resolved by passing `height` attribute to `img` tag

https://codesandbox.io/s/l72m78yljz

**Comment by yanguoyu** [comment]
@ilanus you use padding to fixed.but if you remove the padding it's also not right

**Comment by yanguoyu** [comment]
https://codesandbox.io/s/5z41m4q97l

**Comment by ilanus** [comment]
> https://codesandbox.io/s/5z41m4q97l

@yanguoyu you are responsible for the Popover content, If you don't limit the width the content will use 100% of the window space which will cause overfloating ... additionally, you can specify the Popover `placement`: https://ant.design/components/popover/#components-popover-demo-placement.

https://codesandbox.io/s/lmjx747kz

**Comment by joenot443** [comment]
For the record, I'm seeing the same behaviour, though specifically on mobile. I specify the exact size of the Popover content, but I still find the first display is in the incorrect position and overflows off the screen. Closing and reopening the popover causes it to display correctly, however.

**Comment by ilanus** [comment]
> For the record, I'm seeing the same behaviour, though specifically on mobile. I specify the exact size of the Popover content, but I still find the first display is in the incorrect position and overflows off the screen. Closing and reopening the popover causes it to display correctly, however.

Like I mentioned earlier, passing the height of the `img` solves the issue https://codesandbox.io/s/9ym9yp2o3y and works fine on mobile.

<img width="272" alt="screenshot 2018-10-30 at 20 19 11" src="https://user-images.githubusercontent.com/9677898/47744313-52a16180-dc81-11e8-8bd2-4ea09df6aff7.png">

**Comment by dimitar-nikovski** [comment]
Setting an explicit `width` on the div container via `overlayStyle` fixed it for me.
