### ISSUE TITLE
省市联动数据源问题

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#12869]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codepen.io/pen/?&editors=001 原本数据源是
```javascript
const provinceData = ['Zhejiang', 'Jiangsu'];
const cityData = {
  Zhejiang: ['Hangzhou', 'Ningbo', 'Wenzhou'],
  Jiangsu: ['Nanjing', 'Suzhou', 'Zhenjiang'],
};
```
请问下这个例子支持数组里面的选项是对象吗?类似[{value:1,text:'Zhejiang'}],但是子选项好像不好定义了假如这样的话.

### What does the proposed API look like?
*

**Comment by zombieJ** [comment]
参考一下文档吧：https://ant.design/components/cascader-cn/#components-cascader-demo-basic
