### ISSUE TITLE
Providing array with value of an empty string breaks multiple/tags Select & TreeSelect components

### ISSUE THREAD

**Issue by rynjwssl** [ant-design/ant-design#12872]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
Mac OS 10.13.6 Chrome Version 70.0.3538.77

### Reproduction link
[https://codepen.io/rynjwssl/pen/KGYQPZ?editors=1111](https://codepen.io/rynjwssl/pen/KGYQPZ?editors=1111)

### Steps to reproduce
You can either provide a defaultValue prop of `['']` or set the value prop to `['']`.

### What is expected?
The field should display an empty Select component or (preferably) show the placeholder message.

### What is actually happening?
Page-breaking error: "The above error occurred in the <Animate> component:
    in Animate (created by Select)
    in div (created by Select)
    in div (created by Select)
    in div (created by Select)
    in Trigger (created by SelectTrigger)
    in SelectTrigger (created by Select)
    in Select (created by LocaleReceiver)
    in LocaleReceiver (created by Select)
    in Select

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries."

---
This was difficult to debug, because the error is from the rc-components package and provides no reference to where this is occurring in your app. The only way I was able to determine that this caused the error was by adding breakpoints in the rc-components library and looking at the props that were passed into their component.

**Comment by zombieJ** [comment]
Thanks for feedback. Fixed: https://codesandbox.io/s/3xkk1rwpm5
