### ISSUE TITLE
[bug] table组件  onChange事件触发时自定义事件时使用this.setState({})导致排序一直处于descend状态

### ISSUE THREAD

**Issue by Dseekers** [ant-design/ant-design#12870]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
win7  chrome   react 16.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ryj84o1p1o)

### Steps to reproduce
见重现链接

### What is expected?
可以随意改变排序order的值并可以使用setState

### What is actually happening?
在onChange事件触发的中使用setState导致order一直为descend

**Comment by afc163** [comment]
Your codesandbox don't contain any data.

**Comment by Dseekers** [comment]
请问你指的是没有什么数据？codesandbox 中没有代码还是table表格中没有数据？要是table表格没有数据的话，我已经添加了，而且这个问题和有没有数据没有关系吧，我只是想触发一下table的onChange事件。

**Comment by afc163** [comment]
https://codesandbox.io/s/m59p54k99y

将 columns 移出 render 就好了。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12737#issuecomment-431548253
