### ISSUE TITLE
I want an approach to communicate with the popover content component.

### ISSUE THREAD

**Issue by NevenLeung** [ant-design/ant-design#12874]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to put multiple functional control buttons to the popover to make the page look clean. So I want to pass some callback function from popover outside to the props of content. 

The current api of popover component is like this.

```
<Popover content={contentComponent}>Popover</Popover>
``` 

This only provides a way to display **what** in popover, but I can't access the data in content of popover, and also can not pass any data to the it.

Is any other way to fulfill my requirement in antd?

### What does the proposed API look like?
Just add an option named **contentProps**. The new api is like this:

```
const contentProps = {
  contentNeededData: data,
  contentNeededHandler: fn
}

...
render (
  <Popover content={contentComponent} contentProps={contentProps}>Popover</Popover>
)
```

**Comment by ilanus** [comment]
You don't need a separate prop `contentProps` to pass data to the content of popover, It accepts a `ReactNode` so you can pass any component and handle data with props. https://codesandbox.io/s/206wjlo11y

**Comment by NevenLeung** [comment]
@ilanus Great! Thanks for your answer.

**Comment by mave108** [comment]
we can't pass a class base component in popover content props.
this is may be bug.
