### ISSUE TITLE
What is the variable for changing background color of a selected item?

### ISSUE THREAD

**Issue by wangdicoder** [ant-design/ant-design#12876]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
Mac OS, Chrome v68.0.3440.106

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v8pm4n9770)

### Steps to reproduce
Double clicking the label and see the background color of the label.

### What is expected?
How can I change the **"::selection"** for all dom? I go through this page [https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less) and didn't find any variables that can be referred. Actually, the background color is modified according to the **@primary-color**, but the color is so dark. I prefer to customise it.

### What is actually happening?
There is a way to change selected background color for all dom.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/72a6febcc49a2efb10d9b35b1c950c3b198b321b/components/style/core/base.less#L489

**Comment by wangdicoder** [comment]
> [ant-design/components/style/core/base.less](https://github.com/ant-design/ant-design/blob/72a6febcc49a2efb10d9b35b1c950c3b198b321b/components/style/core/base.less#L489)
> 
> Line 489 in [72a6feb](/ant-design/ant-design/commit/72a6febcc49a2efb10d9b35b1c950c3b198b321b)
> 
>  background: @primary-color;

Cheers. But how can I set it programmatically in create-react-app? The guideline seems only for **default.less** file.

**Comment by afc163** [comment]
https://github.com/ant-design/create-react-app-antd/
