### ISSUE TITLE
Form performance issue

### ISSUE THREAD

**Issue by vavdav** [ant-design/ant-design#12873]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
Chrome, react

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yjz6r2z2l9)

### Steps to reproduce
try to write into inputs

### What is expected?
Fast response

### What is actually happening?
It takes some time to rerender input values and it is slow

**Comment by afc163** [comment]
You can use multilple Forms with multilple `Form.create` to split state flows.

https://github.com/ant-design/ant-design/issues/4502#issuecomment-270864174

**Comment by duhseekoh** [comment]
So completely re-structure your form because the implementation doesn't support conditional updates... ok.
