### ISSUE TITLE
Form onSubmit won't fire with more than one input as children

### ISSUE THREAD

**Issue by acomito** [ant-design/ant-design#12871]
Simple reproduction using official sandbox: https://codesandbox.io/s/n9w6rvwr1m

I'm thinking that I'm missing something simple, but I'm finding that my onSubmit won't fire. 

Was going to post on stackoverflow, but I tried a few different tweaks, and alas couldn't get it to work. So I thought I'd pop over here in case it was a actual bug. Hopefully this isn't a duplicate.

**Comment by qzmer1104** [comment]
什么鬼，老是自动关bug???，这个问题确实存在，onsubmit不生效

**Comment by zhouzhiqiangzzq** [comment]
@qzmer1104 
if you use  custom  rules in form ,  make sure every  callback method called in **every validator condition**。

please  turst me ,I use my tear  validated  it .

**Comment by zhouzhiqiangzzq** [comment]
@acomito 

i saw your code in codesandbox,  add htmltype  props for Button  will be ok 

 <Button type="primary" **htmlType='submit'**>Does not work</Button>

**Comment by eileenwg** [comment]
I can confirm that @zhouzhiqiangzzq 's  solution works. 
I have a have an Input, Autocomplete and checkbox component. I initially wrote <Button type="submit">. changed it to <Button htmlType="submit"> and my form submits when you press enter on any of my fields. 
Thank you for the solution !
