### ISSUE TITLE
Form: dynamic form does not update value properly

### ISSUE THREAD

**Issue by castamir** [ant-design/ant-design#12884]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
latest chrome, macos

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4v805y429)

### Steps to reproduce
Code based on official demo for dynamic form, I have just added 1 extra line to display current form value.

- add passager "A"
- add passager "B"
- delete passager "A"

### What is expected?
you should see 

```
{"keys":[1],"names":["B"]}
```

### What is actually happening?
you can see 

```
{"keys":[1],"names":["A","B"]}
```

---
if I rename "B" to "C", I got

```
{"keys":[1],"names":[null,"C"]}

```

**Comment by ilanus** [comment]
@castamir I noticed this some time ago. referenced a fix now 👍

**Comment by castamir** [comment]
@ilanus is there any other change associated with this issue? Cause just a change in docs did not help to solve this...

**Comment by ilanus** [comment]
@castamir the keys represent your dynamic data, you need to handle them somehow. If following example of doc do: `const nextKeys = keys.concat(keys.length);` and it will solve the `[null, null, null]` after deleting fields.
