### ISSUE TITLE
3.10.3版本 Table组件 排序有问题

### ISSUE THREAD

**Issue by specialCoder** [ant-design/ant-design#12880]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
chrome

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
默认是顺序排列
1.点击逆序，激活状态正常，排序正常
2.点击顺序，激活失效，排序正常
3.随意点击 顺序/逆序，出现顺序激活状态，顺序排序

### What is expected?
点击顺序，激活正常，排序正常

### What is actually happening?
点击顺序，激活失效，排序正常

**Comment by afc163** [comment]
It is a feature, not a bug.

More detail see https://github.com/ant-design/ant-design/pull/12264
