### ISSUE TITLE
<a> 标签里设备onClick 事件后，页面自动跳转，并且无法返回列表页

### ISSUE THREAD

**Issue by linyongfu2013** [ant-design/ant-design#12886]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
macos chrome react16

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
```
<List.Item key={item.id}>
                  <Card hoverable className={styles.card}
                        // actions={[<a>修改</a>, <a>停用</a>]}>
                        actions={[<a onClick={this.handleUpdateRecord(item)}>修改</a>, <a>停用</a>]}>
                    <Card.Meta
                      avatar={<img alt="" className={styles.cardAvatar} src={OSS_URL   item.icon}/>}
                      title={<a>{item.appName}</a>}
                      description={
                        <Ellipsis className={styles.item} lines={3}>
                          {item.description}
                        </Ellipsis>
                      }
                    />
                  </Card>
                </List.Item>
```

### What is expected?
<a> 标签能够通过手动点击触发事件

### What is actually happening?
不需要手动点击，页面加载时就自动触发了事件

**Comment by yutingzhao1991** [comment]
你需要在 onClick 中阻止掉默认的事件，中断 a 标签的默认行为。这个不是个 antd 的问题。
