### ISSUE TITLE
table使用scroll固定表头，表格宽度无法自适应

### ISSUE THREAD

**Issue by z784324922** [ant-design/ant-design#12883]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前table固定表头需要指定 column 的 width 属性，否则列头和内容可能不对齐。现在的问题是，table列的内容长短不一致。width固定后显示效果不太好。

### What does the proposed API look like?
能否在不指定width属性的情况下，达到列头和内容对其的效果。最终想得到的效果是，某些表格过长时适当扩宽。

**Comment by afc163** [comment]
Duplicate of #11822
