### ISSUE TITLE
when i import antd and react-slick together , dots display twice include dot and Horizontal line styles.

### ISSUE THREAD

**Issue by amActiveHello** [ant-design/ant-design#12895]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
chrom

### Reproduction link
[https://ant.design/components/carousel-cn/](https://ant.design/components/carousel-cn/)

### Steps to reproduce
![error img](https://img-blog.csdnimg.cn/20181031093244154.JPG?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L2h0dHAxODgxODg=,size_16,color_FFFFFF,t_70)
1、import:
```
import React from "react"
import Slider from "react-slick";
import { Card, Row, Col, Spin,Carousel,Avatar,Icon,List } from 'antd';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
```
2、antd 
```
   <div style={{ background: '#f0f2f5', padding: '0px', height:'100vh' }}>
              <Carousel autoplay >
                <div><h3>1</h3></div>
                <div><h3>2</h3></div>
                <div><h3>3</h3></div>
                <div><h3>4</h3></div>
              </Carousel>
            <div>
```
3、react slick
```
        const settings = {
          dots: false,
          infinite: true,
          slidesToShow: 3,
          slidesToScroll: 1,
          autoplay: true,
          speed: 2000,
          autoplaySpeed: 2000,
          cssEase: "linear"
        };
    <div>
        <h2>Right to Left</h2>
        <Slider {...settings}>
          <div>
            <h3>1</h3>
          </div>
          <div>
            <h3>2</h3>
          </div>
          <div>
            <h3>3</h3>
          </div>
          <div>
            <h3>4</h3>
          </div>
          <div>
            <h3>5</h3>
          </div>
          <div>
            <h3>6</h3>
          </div>
        </Slider>
      </div>
```

### What is expected?
in Carousel  display dot or Horizontal line ,not display two styles together.

### What is actually happening?
in Carousel  display dot and Horizontal line two styles together。

**Comment by amActiveHello** [comment]
the issue address is ： https://codesandbox.io/s/xp5r75vr8w

**Comment by amActiveHello** [comment]
antd's Carousel dosen't display , only react-slick's Slider dislpay ok.

**Comment by afc163** [comment]
You used wrong JavaScript syntax `(a, b)`.

https://codesandbox.io/s/zrylzl558m
