### ISSUE TITLE
when i import List set itemLayout="horizontal" and itemLayout="vertical" there dosen't have effect

### ISSUE THREAD

**Issue by amActiveHello** [ant-design/ant-design#12896]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
chrom

### Reproduction link
[https://codepen.io/amActiveHello/pen/dgBXpp](https://codepen.io/amActiveHello/pen/dgBXpp)

### Steps to reproduce
1、Default Size  use itemLayout="horizontal"
2、small size use itemLayout="vertical"

### What is expected?
in Default Size item  Horizontal arrangement ， in small size section item vertical arrangement 

### What is actually happening?
in both itemLayout="horizontal" and itemLayout="vertical" settings ,item  vertical arrangement

**Comment by afc163** [comment]
You need to add more content to see the difference bettween these two itemLayouts:

https://codepen.io/anon/pen/YJoaKq?editors=0010
