### ISSUE TITLE
table的排序只能降序，点击升序图标没响应

### ISSUE THREAD

**Issue by TsangTszKin** [ant-design/ant-design#12898]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
比较新的谷歌浏览器都不行

### Reproduction link
[http://www.内网暂无提供链接.com](http://www.内网暂无提供链接.com)

### Steps to reproduce
table的排序只能降序，点击升序图标没响应

### What is expected?
table的排序只能降序，点击升序图标出现降序效果

### What is actually happening?
点击升序图标没响应

**Comment by afc163** [comment]
It is a feature, not a bug.

More detail see #12264

**Comment by TsangTszKin** [comment]
i have no filters  in my code. i have saw the bug#12264, but i did not know how i should modify my code. i foubd this issues since i updated the antd 2 weeks ago.

**Comment by afc163** [comment]
1. 你可以用中文。
2. 如果你看过 #12264 后还是觉得有问题，请参照前面的回复提供一个可重现的在线链接。

**Comment by TsangTszKin** [comment]
> 1. 你可以用中文。
> 2. 如果你看过 #12264 后还是觉得有问题，请参照前面的回复提供一个可重现的在线链接。

多Q谢晒，搞卵掂左
