### ISSUE TITLE
ID with `dot`/`period` in getFieldDecorator()

### ISSUE THREAD

**Issue by chungwong** [ant-design/ant-design#12899]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
Chrome 63.0.3239.132 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zn20m7zr6l)

### Steps to reproduce
Given an ID `username[a_key]`, when `a_key=1.1` so that `getFieldDecorator("username[1.1]")`, the form will return 
`{
  userName: {
    1.1: "some value"
  }
}`

However, when `a_key` contains an alphabet, so that `getFieldDecorator("username[V1.1]")`, the form will return 
`{userName: {
    V1 :{
      1: "some value"
    }
  }
}`

### What is expected?
keys with dot should work consistently 

`{
  userName: {
    1.1: "some value"
    V1.1: 1: "some value
  }
}`

### What is actually happening?
keys with dot are treated more like lodash.get()

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/nkqy8w74y0

**Comment by sunwenli** [comment]
> Try this way: https://codesandbox.io/s/nkqy8w74y0

我遇到的问题是，getFieldDecorator 的 id 包含了逗号，再用  this.props.form.validateFieldsAndScroll((err,values)) 校验并取值时，values 里的值不对, 从逗号那里截取后处理成对象了。

期望值是:
 { "mic-a.b":"val"}

实际上：
{"mic-a":{"b":"val"}}

是不是不能通过 values 取值了，只能用 this.props.form.getFieldValue("mic-a.b") 取值呢？

**Comment by sunwenli** [comment]
> getFieldValue

@afc163
