### ISSUE TITLE
社区示例和脚手架收集 Demo and Scaffold from communication

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#129]
2017.05.13 更新，欢迎将您的脚手架提交到：http://scaffold.ant.design/

---

这里将长期收集社区提供的一些 antd 周边的开发资源和例子，帮助你探索其他人是怎么进行开发的，也欢迎主动回复到此处。

> 无关回复将会定期删除。

**Comment by ReadingSteiner** [comment]
跪求更新示例

**Comment by jorycn** [comment]
求更新~~

**Comment by yasenagat** [comment]
up，更新

**Comment by imcaffrey** [comment]
求更新的demo....

**Comment by kaiye** [comment]
+1，没 demo 的确很难上手

**Comment by AbyChan** [comment]
呵呵哒

**Comment by alwayrun** [comment]
:+1:

**Comment by wuzhao** [comment]
+1 有示例前期摸索可以省很多时间。

**Comment by yiminghe** [comment]
@benjycui

**Comment by imcaffrey** [comment]
:+1:

**Comment by diaoaa** [comment]
给的页面 404.........

**Comment by benjycui** [comment]
@diaoaa 还没开始做。。。

**Comment by lysnoter** [comment]
1.我使用的系统是windows7.
2.我在执行antd-init的时候报错,:
     ERR! fetch failed https://registry.npmjs.org/dora-plugin-proxy/-/dora-plugin-proxy-0.5.
     WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
3.如何使用cnpm.

**Comment by imcaffrey** [comment]
@lysnoter cnpm --> npm.taobao.org

**Comment by lysnoter** [comment]
@imcaffrey 非常感谢!可以了.

**Comment by lysnoter** [comment]
@imcaffrey 
C:\Users\lys\Desktop\test>antd-init
Write .\.editorconfig
Write .\.eslintrc
Write .\gitignore
Write .\index.html
Write .\package.json
Write .\README.md
Write .\webpack.config.js
Write .\lib.js
Write .\App.jsx
Write .\index.jsx
use npm: cnpm
npm WARN package.json antd-demo@1.0.0 No repository field.
npm WARN package.json antd-demo@1.0.0 No license field.
npm WARN peerDependencies The peer dependency webpack@^1.0.0 included from webpack-dev-middleware will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

> spawn-sync@1.0.13 postinstall C:\Users\lys\Desktop\test\node_modules\pre-commit\node_modules\cross-spawn\node_modules\spawn-sync
> node postinstall

> pre-commit@1.1.2 install C:\Users\lys\Desktop\test\node_modules\pre-commit
> node install.js

npm WARN optional dep failed, continuing fsevents@1.0.6
npm WARN optional dep failed, continuing fsevents@1.0.6
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lys\\AppData\\Roaming\\npm\\node_mod
ules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\lys\\.cnpmrc" "--disturl=ht
tps://npm.taobao.org/mirrors/node" "--cache=C:\\Users\\lys\\.cnpm" "--registry=https://registry.npm.
taobao.org" "--node-gyp=C:\\Users\\lys\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\nod
e-gyp\\bin\\node-gyp.js" "install"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.15
npm ERR! path C:\Users\lys\.cnpm\wrappy\1.0.1\package\package.json.1338073656
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\lys\.cnpm\wrappy\1.0.1\package\pack
age.json.1338073656' -> 'C:\Users\lys\.cnpm\wrappy\1.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\lys\.cnpm\wrappy\1.0.1\package\
package.json.1338073656' -> 'C:\Users\lys\.cnpm\wrappy\1.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\lys\\.cnpm\\wrappy\\1.0.1\\package\\package.json.1338073656',
npm ERR!   dest: 'C:\\Users\\lys\\.cnpm\\wrappy\\1.0.1\\package\\package.json',
npm ERR!   parent: 'once' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

**Comment by lysnoter** [comment]
我看了我电脑C:\\Users\\lys\\.cnpm\\wrappy\\1.0.1\\package\\package.json目录下的文件名称没有问题

**Comment by lysnoter** [comment]
问题解决了，可能是第一次安装的时候C:\\Users\\lys\\.cnpm\\wrappy\\1.0.1\\package\\package.json目录下的文件名是错误的，报错之后自动修正了，关闭命令行，重新执行一次antd-init就不报错了

**Comment by benjycui** [comment]
@lysnoter 以后提问请另外 issue，另外麻烦先看下这个 https://github.com/ant-design/ant-design/blob/master/CONTRIBUTING.md
这楼歪的。。。要删 commet 整理一下么。。。

**Comment by benjycui** [comment]
写了个简单的例子 https://github.com/benjycui/selector-specificity/tree/master

之所以不是 TODO，是因为刚好需要这么一个工具

**Comment by xiongjiabin** [comment]
这个问题，把那个版本改成低一个版本就可以了！

On Tue, Jan 26, 2016 at 5:28 PM, Benjy Cui <notifications@github.com> wrote:

> 写了个简单的例子 https://github.com/benjycui/selector-specificity/tree/master
>
> 之所以不是 TODO，是因为刚好需要这么一个工具
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/129#issuecomment-174922114>
> .
>



-- 
熊佳斌

**Comment by afc163** [comment]
这个脚手架是一个非常棒的示例：https://github.com/jovey-zheng/react-start-kit

**Comment by afc163** [comment]
还有这个：https://github.com/okoala/react-redux-antd

**Comment by afc163** [comment]
https://github.com/fireyy/react-antd-admin

**Comment by benjycui** [comment]
https://github.com/pizn/eevee

**Comment by afc163** [comment]
https://github.com/allces/webpack-dev-server-antd

**Comment by afc163** [comment]
https://github.com/pandazki/ant-design-redux-boilerplate

**Comment by yuzhouisme** [comment]
I hope that can help

**Comment by yuzhouisme** [comment]
I hope that can help developers who used antd. 

This project is designed to help those who use antd to develop a website(or web app). Maybe also need to use redux, router and so on.

https://github.com/yuzhouisme/react-antd-redux-router-starter

**Comment by afc163** [comment]
https://github.com/sorrycc/github-stars

**Comment by afc163** [comment]
https://github.com/yuzhouisme/react-antd-redux-router-starter

**Comment by afc163** [comment]
https://github.com/huhulab/react-frontend-boilerplate

**Comment by afc163** [comment]
http://demo-static.huhulab.com/react-frontend-boilerplate/#/demo/test_forms?_k=9267rv

**Comment by RichardLyp** [comment]
https://github.com/huhulab/react-frontend-boilerplate 跑不起来 @afc163

**Comment by benjycui** [comment]
@RichardLyp 那个 repo 并不是我们在维护，请直接去对应仓库开 issue。

（虽然我知道是什么原因，但我不喜欢你们把 antd 的 issue 当垃圾桶，有关无关都往这里扔 :-( 

（issue 应当放在对应的项目下面，并 @ 下你认为需要参与讨论的人即可

（到那个 repo 开个 issue 再 @ 下我，我会回复的

**Comment by RichardLyp** [comment]
我不用antd的脚手架，为什么项目引进antd之后，webpack打包出来有800多K大，没引antd时才200多，这样正常吗 @benjycui

**Comment by benjycui** [comment]
Please read [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ#i-just-want-to-use-menubuttonetc-but-it-seems-that-i-have-to-import-the-whole-antd-and-its-style), and [smart questions](http://doc.zengrong.net/smart-questions/cn.html).

**Comment by Liyuk** [comment]
呵呵哒

**Comment by afc163** [comment]
https://github.com/tetojs/teto.js

**Comment by afc163** [comment]
https://github.com/yukrain/koa-antd-admin

**Comment by benjycui** [comment]
国人的项目都不提供英文文档的么 😅

**Comment by afc163** [comment]
https://github.com/yedegesong/typescript-webpack-react-antd

**Comment by afc163** [comment]
https://github.com/bang88/typescript-react-redux-starter

**Comment by miss61008596** [comment]
In this file affix/index.js,
the code does not work well .

var elemSize = {
        width: _reactDom2["default"].findDOMNode(_this.refs.fixedNode).offsetWidth,
        height: _reactDom2["default"].findDOMNode(_this.refs.fixedNode).offsetHeight
      };

so , I use the affix  like this :

 <div>
        <div style={{position: 'fixed', top: 0, left: 0, width: this.state.windowWidth,zIndex: 10}}>
          <div
            style={{
            display:'flex',
            height:35,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor:'rgba(0, 0, 0, 0.5)'
        }}>
            <div style={{paddingLeft:10}}>
              <h1 style={{color:'#FFF',fontWeight:'bold'}}>BTW</h1>
            </div>
          </div>
        </div>

Thanks for ant-design project team :+1:

**Comment by afc163** [comment]
https://github.com/JasonBai007/reactSPA

**Comment by afc163** [comment]
- https://github.com/cupools/todoMVC-react
- https://github.com/Justin-lu/react-redux-best-practice
- https://github.com/chenliang2016/CLReactAntDesign
- https://github.com/LeuisKen/react-redux-intro
- https://github.com/dayiner-ued/antd-start-kit
- https://github.com/peterchenhdu/webbf

**Comment by Justin-lu** [comment]
https://github.com/Justin-lu/react-redux-antd

**Comment by superlbr** [comment]
有没有同构的方案

**Comment by afc163** [comment]
大家有什么好的脚手架和示例可以到这里去 PR：https://github.com/websemantics/awesome-ant-design

**Comment by afc163** [comment]
https://github.com/cas-x/cas-server

**Comment by afc163** [comment]
- https://github.com/visvadw/ant-design-playground
- https://github.com/websemantics/semantic-ant
- https://github.com/peterchenhdu/webbf

**Comment by websemantics** [comment]
Just updated https://github.com/websemantics/awesome-ant-design with all projects mentioned here, and few from searching Github,

I tried to test the ones I add first so I can describe them better, but it's a long list and I couldn't get a lot of them working, .. I've also added few more categories and a table of content,

Please feel free to add new Ant Design related projects directly with a PR, and I will be more than happy to merge, 

Will keep the listed up to date, ..

**Comment by justnull** [comment]
ant-design不支持IE吗？打包后以后的js，在IE9下直接打不开。调试态打开IE9，发现样式完全是乱的。 @afc163 你好，请问有解决的方法吗？

**Comment by afc163** [comment]
两个扩展组件：

- https://github.com/kagawagao/react-grid
- https://github.com/huhulab/antd-kit

**Comment by vtoo** [comment]
有没有更全一点案例呢？

**Comment by pookpal** [comment]
用webpack+react+ant-design+ES6+Echart做的项目模板，包含国际化等
[https://github.com/pookpal/star-initReact-example](https://github.com/pookpal/star-initReact-example)

**Comment by xianshannan** [comment]
[R2框架](https://github.com/dog-days/r2)(Redux React Framework)主要是基于React、Redux而构建的，其中还是用了`react-router`、`react-router-redux`、`react-redux`、`immutable.js`。同时使用webpack模块加载工具，采用ES62015语法。所有如果要使用本框架，这些知识多多少少都要会点的。同时也使用了[Ant Design React](http://ant.design/#/docs/react/introduce)组件,生成的页面使用的UI是Ant Design,目前只支持这种，后面页面生成也会支持多种UI组件。 R2框架旨在快速搭建页面，减少重复工作，减少重复代码，提高开发效率。
最主要的两种特点：
- 智能构建route和reducer
- 页面生成器

**Comment by wuhaih** [comment]
能提供demo 看看麽

**Comment by afc163** [comment]
@xianshannan 实现质量真高。:+1:

**Comment by xianshannan** [comment]
@wuhaih https://github.com/dog-days/r2
clone后运行就是demo了，可以看看文档

**Comment by afc163** [comment]
https://github.com/zuiidea/antd-admin

https://github.com/jiangxy/react-antd-admin

两个非常赞的后台 Demo。

**Comment by mgoann** [comment]
跪求一个页内编辑的demo

**Comment by ouzhou** [comment]
来一个 antd-dva-admin

**Comment by afc163** [comment]
Use antd with Java: https://github.com/ihaolin/diablo

**Comment by janjon** [comment]
有 和 redux 做的demo 吗。

**Comment by ouzhou** [comment]
@janjon  [dva](https://github.com/dvajs/dva)

**Comment by luckykun** [comment]
我来推荐一个，我自己写的react+router的项目脚手架。
https://github.com/luckykun/generator-reactpackage

**Comment by yangwq123** [comment]
@xianshannan 
https://console.topvdn.com
这个项目有放到github吗

**Comment by zmGitHub** [comment]
有没有注意到 如果把babel-plugin-import的配置下在 babel-loader的 query 中是不起作用的 但是在. babelrc是可以 但是 仍然会提示你的第三方包过大

**Comment by xianshannan** [comment]
@yangwq123 公司内部项目

**Comment by tianzx** [comment]
我的demo
https://github.com/tianzx/ui

**Comment by yedaodao** [comment]
webpack部署antd图标至本地

https://github.com/yedaodao/antd-local-icon

**Comment by lixiaoyang1992** [comment]
试着把redux reactrouter typescript整合了一下，下一步要把公司的项目也换成typescript开发
https://github.com/lixiaoyang1992/react-typescript-starter-kit

**Comment by afc163** [comment]
Koa2 + React + Redux + antd 同构直出探索：https://github.com/git-lt/isomorphism-koa2-react-antd

**Comment by websemantics** [comment]
Ant Design trending today, https://github.com/trending 
![ant-design](https://cloud.githubusercontent.com/assets/2190455/20715834/63d96fa0-b61e-11e6-8fe7-c3c8f0afa949.png)

**Comment by afc163** [comment]
如何在 [create-react-app](https://github.com/facebookincubator/create-react-app) 中使用 antd：https://github.com/ant-design/create-react-app-antd

**Comment by afc163** [comment]
如何在 [create-react-app](https://github.com/facebookincubator/create-react-app) 中使用 antd：

- 代码：https://github.com/ant-design/create-react-app-antd
- 文档：https://ant.design/docs/react/use-with-create-react-app-cn

**Comment by wufeng87** [comment]
请问有没有其他帖子专门放置开源案例(包括HOC扩展的组件)的？
类似这种开源app  https://github.com/andrewngu/sound-redux
这个帖子大多是脚手架。

**Comment by afc163** [comment]
https://github.com/guox191/antd-redux-scaffold

**Comment by afc163** [comment]
https://github.com/OwlAford/react-blade-desktop

**Comment by afc163** [comment]
https://github.com/lokewei/koa2-dva-antd

**Comment by afc163** [comment]
Some boilerplates using TypeScript and antd.

- https://github.com/zhifeng-mi/typescript-react-redux-router-antd-starter-kit
- https://github.com/huang6349/ts-dva
- https://github.com/xufei/antd-dva-ts-boilerplate

**Comment by tvrcgo** [comment]
Share one
https://github.com/tvrcgo/egg-react-mobx-ts-antd
egg, react, mobx-react, typescript and ant design.

**Comment by afc163** [comment]
https://github.com/rhiokim/react-boilerplate

**Comment by afc163** [comment]
https://github.com/mqyqingfeng/react-base

**Comment by benjycui** [comment]
https://github.com/bang88/fuse-box-antd-example

From: https://github.com/ant-design/ant-design/issues/5110#issuecomment-283095829

**Comment by danielbiloglav** [comment]
Here is a boilerplate using React, Redux, TypeScript, SSR, HMR, Webpack 2.

https://github.com/danielbiloglav/universal-react-redux-typescript-antd-starter-kit

**Comment by afc163** [comment]
https://github.com/mqyqingfeng/react-admin

**Comment by sunlightwdd** [comment]
也向大家推荐一个功能比较齐全且可实战的antd-dva-admin项目[https://github.com/pmg1989/dva-admin](https://github.com/pmg1989/dva-admin)

**Comment by afc163** [comment]
@sunlightwdd 感觉大量『借鉴』了 https://github.com/zuiidea/antd-admin ，是否不妥当。

**Comment by andyhu** [comment]
有没有和next.js结合的项目？

**Comment by shengbeiniao** [comment]
一个基于antd和dva的[统一中台框架](https://github.com/shengbeiniao/one-base)，实现了类似阿里云的2级导航

**Comment by myqianlan** [comment]
https://github.com/myqianlan/antd-admin-boilerplate

**Comment by eaTong** [comment]
[electron + Mobx + antd + sequelize](https://github.com/eaTong/electron-mobx-member),这个项目是最近自己在做的，由于是升级3年前刚入门的时候写的一个程序，所以在表结构上面设计会很不合理，不过尽量在保证前端代码的合理化。

**Comment by xianshannan** [comment]
[https://github.com/dog-days/antd-react-form-builder](https://github.com/dog-days/antd-react-form-builder)
[https://xianshannan.github.io/antd-react-form-builder/](https://xianshannan.github.io/antd-react-form-builder/)

**Comment by benjycui** [comment]
这个 issue 或者可以关了？

**Comment by benjycui** [comment]
@afc163

**Comment by afc163** [comment]
欢迎将您的脚手架提交到：http://scaffold.ant.design/
