### ISSUE TITLE
mobx-react和Form结合使用时mapPropsToFields不执行

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#12904]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
Mac OS

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/046l1mmrpn)

### Steps to reproduce
改变输入框中的数据，触发Form的onFieldsChange，修改store里面的值

### What is expected?
在store里面的值发生改变之后，mapPropsToFields会自动触发执行。

### What is actually happening?
mapPropsToFields没有执行

---
我参考官网上面https://ant.design/components/form-cn/#components-form-demo-global-state 这个例子，发现在onFieldsChange执行之后，mapPropsToFields会自动触发，但是用mobx-react的inject和observer包裹的Form组件，在onFieldsChange执行时，store里面的数据确实发生了改变，但是mapPropsToFields并不会触发执行。

**Comment by zombieJ** [comment]
不太熟悉 mobx，但是好像不用 Form 这个例子也不会触发更新？https://codesandbox.io/s/l5o7lm3vxm

**Comment by chj-damon** [comment]
@zombieJ https://codesandbox.io/s/k3oqy4zx7r 你看看官方这个例子，mapPropsToFields是会多次执行的。

**Comment by zombieJ** [comment]
@chj-damon , 是不是 mobx 用法不对？你看看我的例子，把你的代码里 Form 去掉也是不更新的。

**Comment by chj-damon** [comment]
@zombieJ 你所说的不更新是不是说componentWillReceiveProps这个生命周期函数没有执行？？

**Comment by zombieJ** [comment]
嗯，form 得到新的 props 会跑一遍 mapPropsToFields

**Comment by chj-damon** [comment]
我也是这么认为的，但是在用observer和inject之后，form的mapPropsToFields就出问题了。。。

**Comment by zombieJ** [comment]
还是再看看 mobx 和 mobx-react 的用法吧，这不是 Form 的问题。

**Comment by chj-damon** [comment]
@zombieJ 在父组件中获取数据，然后通过props传递给Form.create()(xxx)这个组件，就可以了。
