### ISSUE TITLE
Button component stays in "active" state after releasing mouse

### ISSUE THREAD

**Issue by ChemicalRocketeer** [ant-design/ant-design#12908]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
OSX Mojave, Chrome 69

### Reproduction link
[https://ant.design/components/button/](https://ant.design/components/button/)

### Steps to reproduce
1. Click on the button.
2. Release the mouse.
3. Move the mouse away.
4. The button will still appear "pressed"

### What is expected?
The button should appear released.

### What is actually happening?
The button appears pressed.

**Comment by afc163** [comment]
It is not a bug, it is a native behavior of chrome that button would stay focused after click it.

**Comment by ademkesim** [comment]
This issue has been closed without resolving the issue. Did you find a solution?
