### ISSUE TITLE
The validation rule in Form when using Tooptip wrapping Input

### ISSUE THREAD

**Issue by B1anker** [ant-design/ant-design#12900]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.2

### Environment
MacOs 10.14, Chrome 70.0.3538.77

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9yz03p14ko)

### Steps to reproduce
Texting in the two Input you will find the difference.
在两个输入框中输入字符串就会发现差异

### What is expected?
The first should be performed as same as the second and the tooltip is abled.
第一个应该和第二个表现想过一致并且Tooltip是可用的。

### What is actually happening?
The first was not triggered the validation rule but the second was triggered.
第一个没有触发验证规则，但是第二个触发了。

**Comment by afc163** [comment]
`getFieldDecorator` should wrap form filed component directly.
