### ISSUE TITLE
Table column click sort behavior

### ISSUE THREAD

**Issue by tiagowippel** [ant-design/ant-design#12905]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi, 

I think must be a way to change the behavior of the sorted column click. It should be possible that the sort do not go to and undefined state.

Ex: supposing a table unsorted with 2 columns that can be sorted, Name and Age. When a click on Age, it goes to ascend order. When I click again on Age it goes to descent order. When I click again it should go to ascend order, **and not to undefined state...**

### What does the proposed API look like?
Maybe a property that modify the sort click behavior.

Here is an example of Material-UI: https://codesandbox.io/s/l2x50p5m5m

**Comment by afc163** [comment]
We may gonna stick our way now, unless more important reason comes out.

**Comment by tiagowippel** [comment]
> I don't see any problem need to resolve, it is just different sort interaction.

Ok, I just think that maybe that could be implemented. (a way to modify this behavior)

When I'm more familiar with the code, maybe I'll propose a PR.

Thanks anyway.

**Comment by Nastya-Piu** [comment]
Is there any updates of this issue?

**Comment by itsmichaeldiego** [comment]
@afc163 I do see a problem here, I've an unordered list, and I want to sort my array by default using `defaultSortOrder`. I don't want the user to see the unordered list, but they do when they go through the undefined state.

**Comment by komal102990** [comment]
@afc163 I agree with @itsmichaeldiego . Most of the time we see this requirement to disable the undefined state and just sort in one of ['ascend', 'descend'] only.
I believe we should have some custom flag to strictly sort only, with this I believe both cases can be achieved the way it is and removal of undefined also.

**Comment by j-mars** [comment]
Hi all, pushing for this too. @afc163 please re-open this issue

**Comment by yoyo837** [comment]
This issue is outdated, feel free to open a new issue with something new!

**Comment by itsmichaeldiego** [comment]
Any news on this? :) Lets do it!!!

**Comment by jay-hyung** [comment]
@afc163 I agree with @itsmichaeldiego. I'm having to deal with a list of items that the only sensible way of sorting is through its order id. And none of my users expects that their second click is cancelling the sort. Example: Default sort is ascending, one click is changing it to descending, another click should change it back to ascending, however, in the current implementation, it seems like nothing changed. Can we do something about it?
