### ISSUE TITLE
table中设置的一个input框，为什么是只读的？

### ISSUE THREAD

**Issue by pangbi** [ant-design/ant-design#1291]
在table中设置了一个input输入框，鼠标失去焦点的时候更新该行的记录，为什么设置的inpu框是只读的，应该怎么去除只读属性

**Comment by awaw00** [comment]
<Input value={value} onChange={this.valueChangeHandler} />

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#i-set-the-value-of-inputselectetc-and-then-it-cannot-be-changed-by-users-operation
