### ISSUE TITLE
Table width inconsistent behavior between Chrome and Firefox

### ISSUE THREAD

**Issue by fgiarritiello** [ant-design/ant-design#12912]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
macOS Mojave, Firefox 63.0, React 16.6.0

### Reproduction link
[https://codepen.io/anon/pen/VEomag?editors=0110](https://codepen.io/anon/pen/VEomag?editors=0110)

### Steps to reproduce
1. Create a table and assign width in px to each column
2. Add scroll={{ x: true}}
3. Add white-space: nowrap; to td and th
4. Shrink the table by resizing the browser

### What is expected?
The column width should behave the same

### What is actually happening?
Chrome: the column width acts as percentage.
Firefox: the column width as min-width

**Comment by afc163** [comment]
It is browser compatibility issue, nothong we can do about it, sorry.
