### ISSUE TITLE
按模块定制主题问题

### ISSUE THREAD

**Issue by leeseean** [ant-design/ant-design#12921]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd官方提供了主题定制功能，在webpack配置下就可以，挺方便的。
但是现在有开发中遇到需求，SPA要求每个模块使用不同的风格，比如充值模块使用A风格，订单模块使用B风格，这能否在webpack上配置实现？

### What does the proposed API look like?
```jsx
options: {
  A: {
    modifyVars: {
      'primary-color': '#1DA57A',
      'link-color': '#1DA57A',
      'border-radius-base': '2px',
    }
  },
  B: {
    modifyVars: {
      'primary-color': '#1DA57A',
      'link-color': '#1DA57A',
      'border-radius-base': '2px',
    }
  }
  javascriptEnabled: true,
}
```
A模块使用key值'A'对应的配，B模块亦复如是。

**Comment by afc163** [comment]
看下 #5656

---

目前的实现不太可能做到楼主描述的问题，所以目前不会做改动。
