### ISSUE TITLE
怎么控制2个布局的上下间距呢

### ISSUE THREAD

**Issue by find456789** [ant-design/ant-design#12923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
mac

### Reproduction link
[https://ant.design/components/grid-cn/](https://ant.design/components/grid-cn/)

### Steps to reproduce
布局的时候，上下2个 Row 模块挨在一起的，看上去不美观 ，比如这个 https://codesandbox.io/s/2j0j6v1w0j

### What is expected?
希望有类似bootstrap.这样的，  控制间距的方法 https://getbootstrap.com/docs/4.1/utilities/spacing/

### What is actually happening?
实际布局中，控制上下距离很麻烦

**Comment by zombieJ** [comment]
你可以自己写样式解决哈~
