### ISSUE TITLE
when i control MonthPicker's value, the dropdown display is not right.

### ISSUE THREAD

**Issue by yanguoyu** [ant-design/ant-design#12929]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
mac osx 10.13 chrome 版本 69.0.3497.100（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l5yknkwmq)

### Steps to reproduce
1: click MonthPicker
2: choose Feb
3: click MothPicker

### What is expected?
1: the dropdown panel should choose Nov

### What is actually happening?
the dropdown panel should choose Feb

**Comment by yanguoyu** [comment]
https://codesandbox.io/s/l5yknkwmq

**Comment by yanguoyu** [comment]
https://codesandbox.io/s/l5yknkwmq
不好意思，上面放错链接了。

**Comment by afc163** [comment]
https://codesandbox.io/s/5mr8w7594l

Please learn https://reactjs.org/docs/forms.html#controlled-components

**Comment by yanguoyu** [comment]
我决定你可能理解错了，我的意思是如果我控制了不让他修改value，但是弹窗框里面选中的还是之前点击的值。
![image](https://user-images.githubusercontent.com/12881040/47904885-b5cd0700-dec0-11e8-8eda-8c822b98b1ca.png)

**Comment by zombieJ** [comment]
发现是 antd 的 createPicker 这一层逻辑的问题，找了半天，蛋疼。修一下去...

**Comment by yanguoyu** [comment]
thanks
