### ISSUE TITLE
<Pagination> 渲染异常, 出现中文汉字 "五"

### ISSUE THREAD

**Issue by 16slowly** [ant-design/ant-design#12925]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.7.3

### Environment
Goole Chrome 70.0.3538.77 (64 位正式版本)

### Reproduction link
[http://vivedu-web.oss-cn-beijing.aliyuncs.com/wechat/WX20181101-203526%402x.png](http://vivedu-web.oss-cn-beijing.aliyuncs.com/wechat/WX20181101-203526%402x.png)

### Steps to reproduce
根据 API 调用 <Pagination > 组件，传入的参数均符合规定

### What is expected?
所有页码为阿拉伯数字

### What is actually happening?
![Pagination 出现汉字"五"](http://vivedu-web.oss-cn-beijing.aliyuncs.com/wechat/WX20181101-203526%402x.png)

**Comment by 16slowly** [comment]
相关代码：https://codesandbox.io/s/7prznopv6

**Comment by afc163** [comment]
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/507615/47893005-ab494800-de95-11e8-80cc-106b3c088635.png">

There is no reproduction in your codesandbox.

**Comment by 16slowly** [comment]
公司部分同事的 Mac 上出现了的

**Comment by zombieJ** [comment]
@16slowly , 指的是用你的重现出现了还是项目代码里出现了？

**Comment by 16slowly** [comment]
已上线的项目在产品经理的 Mac 上出现的，开发机上没出现过，感到迷茫～～

**Comment by zombieJ** [comment]
@16slowly 你的开发环境给 PM Mac 上看是文字吗？

**Comment by hileix** [comment]
因为你的浏览器启用了翻译功能...😄

**Comment by hileix** [comment]
我也遇到过这样的问题，把翻译关掉就行了...😁
