### ISSUE TITLE
Is it possible the icon in <Popconfirm> invisible?

### ISSUE THREAD

**Issue by plainnany** [ant-design/ant-design#12927]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to set icon in popconfirm invisible, not custom icon, not default icon, just invisible

### What does the proposed API look like?
I try `<Popconfirm icon={null} />`，but it does't work

**Comment by zombieJ** [comment]
https://codesandbox.io/s/xr7n8j344
