### ISSUE TITLE
Test React Component useing JEST and Enzyme, report the error：ReferenceError: Layout is not defined

### ISSUE THREAD

**Issue by baizn** [ant-design/ant-design#12932]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.3.0

### Environment
node v8.11.4; chrome 68.0.3440.106（正式版本） （64 位）; React 16.5

### Reproduction link
[https://github.com/baizn/ComponentTest](https://github.com/baizn/ComponentTest)

### Steps to reproduce
Run Unit Test File

### What is expected?
Unit test is performed normally

### What is actually happening?
```
Test suite failed to run

    ReferenceError: Layout is not defined

      2 | import { NavLink } from 'react-router-dom'
      3 | import { Layout, Menu } from 'antd'
    > 4 | const { Header } = Layout
        |                    ^
      5 | import './header.scss'
      6 |
      7 | const PrimaryHeader = () => (
```

---
Test React Component ， which useing Antd Layout Component。

**Comment by zombieJ** [comment]
Pls make sure your project is installed `antd`. Or you can ref our test config: https://github.com/ant-design/ant-design/tree/master/tests

**Comment by goodbedford** [comment]
I had the same error with Collapse. I have `antd@4.0.0`. This only when running test, I can spin up storybook.js with no problem

` Test suite failed to run

    ReferenceError: Collapse is not defined

      5 |
    > 6 | export const { Panel } = Collapse;
        |                          ^
      7 |
      8 | type Props = {
      9 |     children: React.Node,

      at Object.<anonymous> (src/Collapse/Collapse.js:6:26)
      at Object.<anonymous> (src/Collapse/__tests__/Collapse.test.js:5:1)`

**Comment by igor-lemon** [comment]
Hi there! I stuck on the same problem, the solution next, need just mock `ant/lib` to `ant`
Just add:

Add to `setupFilesAfterEnv` new file, like mocks.js, it should looks like
```
  setupFilesAfterEnv: ['<rootDir>/tests/mocks.js'],
```

After in `mocks.js` add next:

```js
jest.mock('antd', () => ({
  ...jest.requireActual('antd/lib'),
}))
```

**Comment by igor-lemon** [comment]
@goodbedford I have a similar problem with `Layout`. It reproduces just with --coverage param. I found just 1 way hot to fix it. Just use `<Collapse.Panel >...</Collapse.Panel>` instead of `const { Panel } = Collapse` & `<Panel>...</Panel>`
