### ISSUE TITLE
Mention component in controlled mode loses focus when a suggestion is selected

### ISSUE THREAD

**Issue by vijayst** [ant-design/ant-design#12931]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
MacOS Mojave, Chrome 70

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pmo55yrjlx)

### Steps to reproduce
In the Mention component, type @, select a suggestion from the list.

### What is expected?
The mention component is still in focus. And the cursor is shifted to the appropriate position

### What is actually happening?
Mention component loses focus

---
It works correctly in Mention component - uncontrolled mode.

**Comment by ilanus** [comment]
Confirming issue with cursor shifting:
![gkapgysldy](https://user-images.githubusercontent.com/9677898/47945690-eaae7d80-df03-11e8-86a1-bd7e3612da79.gif)

**Comment by zombieJ** [comment]
`rc-edit-mention` keeps the cursor but `draft-js` ignore it by [documentSelection.needsRecovery](https://github.com/facebook/draft-js/blob/master/src/component/handlers/edit/editOnSelect.js#L57).
Checking...

**Comment by vijayst** [comment]
@zombieJ  If I try it now with the latest release, after selecting the item from the cursor, both onSelect and onChange is not firing. So nothing happens.

**Comment by zombieJ** [comment]
@vijayst , could you provide a online reproduce. I test the official sample. It works as normal: https://ant.design/components/mention-cn/#components-mention-demo-basic

**Comment by vijayst** [comment]
@zombieJ for me, the official sample does not work. Are you selecting with the mouse by clicking on the selection?

**Comment by zombieJ** [comment]
Checked. Thanks.

**Comment by vijayst** [comment]
Thanks @zombieJ. It works great.

**Comment by timmyz** [comment]
bothered by the same issue here. wish to be fixed.
