### ISSUE TITLE
Transfer高级模式在chrome下按钮边框bug

### ISSUE THREAD

**Issue by cloudychen** [ant-design/ant-design#1293]
**问题描述**

在chrome下，使用Transfer控件的高级用法。穿梭框的按钮在disabled状态时，左侧边框消失。当使用chrome的f12查看，在css中 `ransform: translate3d(0, 0, 0);` 将该属性取消，则左侧边框可以正常显示。

**发生环境**

- antd 版本：0.12.12
- 操作系统及版本：windows10
- 浏览器及版本：chrome 49.0.2623.87 m

**Comment by afc163** [comment]
没有发现 Transfer 有 `transform: translate3d(0, 0, 0);` 的样式，需要 codepen 演示。

**Comment by cloudychen** [comment]
嗯，并不是Transfer的`transform: translate3d(0, 0, 0);`样式，是Transfer的那个按钮。
而且我的显卡比较差，估计是不支持硬件加速的，所以才会出现渲染问题吧

**Comment by afc163** [comment]
去掉好了，反正没啥用。

**Comment by cloudychen** [comment]
啊，我以为你们加这个是用来硬件加速的呢。

**Comment by afc163** [comment]
sorry，不能去掉，会影响 loading 和动画效果。
