### ISSUE TITLE
表单项被存到了window全局变量中， 如果有同名的全局变量会被有此id的dom 节点覆盖掉， 出现window.casetype = <div class=​"ant-radio-group" id=​"casetype">​…​</div>​

### ISSUE THREAD

**Issue by taoxueweilong** [ant-design/ant-design#12937]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.4.0

### Environment
chrome

### Reproduction link
[https://new-issue.ant.design/?repo=ant-design](https://new-issue.ant.design/?repo=ant-design)

### Steps to reproduce
表单项
{getFieldDecorator('casetype', {
            initialValue: window.casetype ? window.casetype : ( casetype.length ? casetype[0].value : '') // initialValue == '1' && '1' || initialValue == '2'  && '2' || '0'
          })(
            <RadioGroup >
            {
              casetype.map(item => <Radio key={item.value} value={item.value}>{item.vname}</Radio>)
            }
            </RadioGroup>
          )}
          </FormItem>
打印window.casetype 出现对应的dom

### What is expected?
该节点不应该出现在全局变量中啊， 为什么呢

### What is actually happening?
出现了全局变量中

**Comment by yesmeck** [comment]
浏览器的默认行为。`id` 会变成全局变量。

**Comment by afc163** [comment]
similar issue: https://github.com/ant-design/ant-design/issues/10218

**Comment by walker-jiang** [comment]
还真是， 学习了， 谢谢
