### ISSUE TITLE
Typescript def missing for type and size in Button

### ISSUE THREAD

**Issue by raptoria** [ant-design/ant-design#12938]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

 

### Version

3.10.3

 

### Environment

Using Chrome on Windows

 

### Reproduction link

[http://NA](http://NA)

 

### Steps to reproduce

<Button

         size='small'

         type='primary' />

 

### What is expected?

type and size attributes work as per https://ant.design/components/button/

 

### What is actually happening?

[ts] Property 'type' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<RadioButton> & Pick<Readonly<{ children?: ReactNode; }> & Readonly<AbstractCheckboxProps<RadioChangeEvent>>, "children" | ... 12 more ... | "name"> & Partial<...> & Partial<...>'.

**Comment by raptoria** [comment]
is it really necessary to create online reproductions for missing Typescript definitions? Seems like overkill

**Comment by afc163** [comment]
@raptoria We ask for reproduction because it works well in our envioronment.
