### ISSUE TITLE
使用 getFieldDecorator 如何格式化得到的 value

### ISSUE THREAD

**Issue by ANDEMEN** [ant-design/ant-design#12940]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 使用 getFieldDecorator 后，数据同步被 Form 接管，所以无法在拿到值之前做格式化。比如 AutoComplete 选择 abc 后自动在前面加上 $，得到 $abc。现在能想到的做法是在 onSelect 事件中使用 setFieldsValue 去处理。但这会有一个问题，直接使用 setFieldsValue 时是没反应的，需要再选择一次才生效。尝试了再 callback 里再一次 setFieldsValue 和 setTImeout 使用 setFieldsValue 是可以的，但输入框会从 abc 一闪而过变成 $abc。原因应该是 getFieldDecorator 先处理了 abc 然后我的自定义处理在将其变成了 $abc。直接使用 setFieldsValue 不生效也应该是因为 getFieldDecorator 的结果覆盖了我的自定义处理。所以想请教一下有没有更合适的方法实现这个功能？例子

[![Edit z2op4qrk0p](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z2op4qrk0p)

### What does the proposed API look like?
```js
getFieldDecorator(key, { formatter: value => `$${value}` })
```

**Comment by ilanus** [comment]
Not sure what you are trying to achieve, you can use `options.normalize` in `getFieldDecorator` to normalize value demo: https://codesandbox.io/s/k9w0947jj7 alternatively use `options.getValueFromEvent` more info: https://ant.design/components/form/#getFieldDecorator(id,-options)-parameters
