### ISSUE TITLE
Some weird animation behaviour of Radio group and Switch occur in Popover

### ISSUE THREAD

**Issue by NevenLeung** [ant-design/ant-design#12942]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
"5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n04pm6vz7m)

### Steps to reproduce
Click the radio button quickly. 

After that, you can see the animation will show on every button you just clicked including the switch component. 

If you wait few seconds to click the button, you may still see only one button show the animation you clicked before.

The Gif for this issue:
![antd-animation](https://user-images.githubusercontent.com/18048923/47931236-2e57b600-df09-11e8-8442-4347b3524732.gif)

### What is expected?
Show the animation correctly .

### What is actually happening?
One click, every button show animation.

---
Using the radio group and switch together at the popover outside works fine.  

I have found if the handler of radio group contains the `this.setState()`, the animation problem will occur. 

Hope this clue will help you to fix it.

**Comment by zy410419243** [comment]
For easier to read, I [rewrite the demo of this.](https://codesandbox.io/s/4z3r7y99m7)

When render `PopoverContent` in App directly, it would show animation correctly, as below,
``` jsx
render() {
  return (
    <PopoverContent
      toggleScrollSync={this.onScrollSyncChange}
      toggleDisplayMode={this.onDisplayModeChange}
    />
  );
 }
```

So maybe there is something wrong with [trigger](https://github.com/react-component/trigger). To know more, I must learn how it works, and it may take for a long time. 

If anyone would like to take this issue, maybe check what wrong with [trigger](https://github.com/react-component/trigger) is a good direction.

**Comment by zombieJ** [comment]
Looks like re-render will makes Wave animation re-play. Still checking...
![kapture 2018-11-05 at 22 58 40](https://user-images.githubusercontent.com/5378891/48005421-63a11580-e14e-11e8-9807-32719035613a.gif)

**Comment by zombieJ** [comment]
Catch it! [`forcePopupAlign`](https://github.com/react-component/tooltip/blob/master/src/Content.js#L18) in `rc-tooltip` makes the browser reflow which reset the animation. Later for patching...

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/48179805-d9c69780-e35b-11e8-8a8f-09d4ddf17110.gif)

This problem still exists in popconfirm demo.

**Comment by zombieJ** [comment]
> This problem still exists in popconfirm demo.
Hmmm, popup will trigger re-align...

**Comment by zombieJ** [comment]
Find some way, let me test.
