### ISSUE TITLE
Mention @ 选择出来的数据不能删除某个字符 删除就删除全部

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#12959]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
聊天窗口@别人，

### What does the proposed API look like?
not

**Comment by zombieJ** [comment]
给个重现

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

**Comment by hengkx** [comment]
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)

![111](https://user-images.githubusercontent.com/8358236/47984729-7695f480-e112-11e8-9871-b9ce92aeab80.gif)

希望删除直接把`@afc163 ` 给删除

**Comment by hengkx** [comment]
@afc163 这个功能 能考虑 加上去吗？
