### ISSUE TITLE
点击button按钮，然后隐藏button，再显示button,会把上次激活状态显示一遍

### ISSUE THREAD

**Issue by lixuguang1988** [ant-design/ant-design#12967]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
window chrome antd 3.8.4 重新连接antd3.10.4

### Reproduction link
[https://codepen.io/anon/pen/NEqvJM?editors=0010](https://codepen.io/anon/pen/NEqvJM?editors=0010)

### Steps to reproduce
1.勾选记录，显示button
2.点击button
3.勾选记录

### What is expected?
再次勾选记录，显示button，不回放激活状态

### What is actually happening?
再次勾选记录，显示button，回放激活状态

---
1.给button隐藏一个延时，时间短激活状态走不完，可能要大于    
node.rcEndAnimTimeout = setTimeout(function () {
      node.rcEndAnimTimeout = null;
      if (node.rcEndListener) {
        node.rcEndListener();
      }
    }, time * 1000   200); 这个时间

**Comment by lixuguang88** [comment]
```js
//_util/wave.js 43行 加上node.style.display==="none" 
if (!node || !node.getAttribute || node.getAttribute('disabled') || node.style.display === "none" || node.className.indexOf('disabled') >= 0) {
      return;
 }
```
