### ISSUE TITLE
Form item onchange one key behind and can't check length of input value

### ISSUE THREAD

**Issue by adamjw3** [ant-design/ant-design#12964]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
Create react app latest, chrome, Mac Book pro

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1q6ykz64o7)

### Steps to reproduce
- enter a character in the input box, the initial return then of the change event is undefined, it should be what you just enetered
- if you uncomment the console below that is trying to log the length of the value, this errors

### What is expected?
- the change event to be up to date with whats entered
- length checking should be easy, it probably is and i'm missing something

### What is actually happening?
- the change event is one step behind, as if its doing setstate, is that right?
- the .length doesn't work but can't see in the documentation how to do this

**Comment by afc163** [comment]
You should use `onValuesChange` instead of binding `onChange` to fetch newest form values.

https://github.com/ant-design/ant-design-pro/pull/2280

https://github.com/ant-design/ant-design-pro/issues/2196

**Comment by adamjw3** [comment]
@afc163 thanks, i've updated my example code. what i want to do is is compare some input values and then do a calculation and then set the value of a field to that value.

```
props.form.setFieldsValue({
      "1-out": "00:10:10:01"
    });
```

form doesn't seem to be available on the props in "onValuesChange"

**Comment by AWR14** [comment]
@afc163 @chenshuai2144 shall i open another issue for this?
