### ISSUE TITLE
Antd should follow Semantic Versioning 'strictly'

### ISSUE THREAD

**Issue by darylsze** [ant-design/ant-design#12970]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For the changes in 3.7.0, it discards 'filedNames' which causes backward incompatibility, while having breaking changes should pumps one major version following Semantic Versioning standards. Also, in 3.9.0, it discards icon 'cross' without major version upgrade. 

### What does the proposed API look like?
...

**Comment by afc163** [comment]
https://github.com/react-component/cascader/blob/1997960bb37c461895baa88338f73fdf824529da/src/Cascader.jsx#L97-L99

We preserved the typo `filedNames` usage after 3.7.x and add warning message, so it won't break the Semantic Versioning.

**Comment by darylsze** [comment]
@afc163 ic. But the icon 'cross' from 3.6.5 is not exist anymore when i upgraded to 3.9.0

**Comment by darylsze** [comment]
@afc163 yes will do. 
Btw, could you provide more known breaking changes made between 3.6.6 and 3.9.0 ? i am investigating the affected area after upgrade, and not sure my mentioned above are the only 2 breaking changes.

**Comment by afc163** [comment]
We don't know any breaking changes more, we thought it is compatible 100% and maybe something missing now.

**Comment by afc163** [comment]
Just let me know if you find more, I will fix them.

**Comment by darylsze** [comment]
thanks!

**Comment by afc163** [comment]
`filedNames` had been broken in antd's code. :sad:

https://github.com/ant-design/ant-design/commit/0f7794946fa97d33f477130e0852db835387ac10#diff-3141ae7cf791cd0b5edcad2c51dd6dddR130

**Comment by afc163** [comment]
The above two problems has been fixed in master, we will release a patch in this weekend. @darylsze

**Comment by darylsze** [comment]
@afc163 i have left comments https://github.com/ant-design/ant-design/commit/e6d9a770291e9384622ee630a88337f188cc27dd#diff-284bc7ec180dee42b223a16bfa8819edR271 fyi

**Comment by NavidMitchell** [comment]
I have just upgraded from 4.21.6 to 4.23.0 and my tab's no longer function. According to the docs this seems intentional. https://ant.design/components/tabs/

This is not really following semantic versioning strictly..
