### ISSUE TITLE
`Button` with `href` prop and `Button` without one appears with a small difference (about 1px) 

### ISSUE THREAD

**Issue by serhiiminin** [ant-design/ant-design#12978]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Linux, MacOS, Chrome 70.0.3538.77 (Official Build) (64-bit)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ojkn186jyq)

### Steps to reproduce
Put `Button` component with `href` prop and `Button` component without `href` prop close to each other

### What is expected?
Buttons are on the same height (without any difference)

### What is actually happening?
There is about 1px of difference

---
on Ubuntu the Button with `href` prop is 1px lower than without it, but on the MacOS it's vise versa

**Comment by afc163** [comment]
<img width="311" alt="image" src="https://user-images.githubusercontent.com/507615/48064500-eb485c00-e202-11e8-9032-87c55a69227a.png">

**Comment by Michael-1** [comment]
Well, nowadays, it’s this 0.01px fix that is causing the misalignment.
