### ISSUE TITLE
Typescript 在使用 React.createElement 的时候出现类型不兼容

### ISSUE THREAD

**Issue by shynome** [ant-design/ant-design#12979]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
react 16, tsc 3.1

### Reproduction link
[https://github.com/shynome/antd-lost-type-when-use-createELement.git](https://github.com/shynome/antd-lost-type-when-use-createELement.git)

### Steps to reproduce
- 克隆仓库, 进入仓库
- 运行 `npm i`, 安装依赖
- 运行 `tsc -p ./jsconfig.json`

### What is expected?
运行 `tsc -p ./jsconfig.json` 不出现错误, 在使用 `jsx` 语法的时候 props 没有的话也不会出现错误

### What is actually happening?
出现了类型不兼容的错误
```
app.js:8:9 - error TS2345: Argument of type 'typeof Table' is not assignable to parameter of type 'string | ComponentClass<TableProps<{}>, any> | StatelessComponent<TableProps<{}>>'.
  Type 'typeof Table' is not assignable to type 'StatelessComponent<TableProps<{}>>'.
    Types of property 'propTypes' are incompatible.
      Type '{ dataSource: Requireable<any[]>; columns: Requireable<any[]>; prefixCls: Requireable<string>; us...' is not assignable to type 'ValidationMap<TableProps<{}>>'.
        Property 'pagination' is missing in type '{ dataSource: Requireable<any[]>; columns: Requireable<any[]>; prefixCls: Requireable<string>; us...'.

8       h(antd.Table)
```

**Comment by afc163** [comment]
What is your typescript version? which I can't find any

**Comment by shynome** [comment]
3.1 的版本
我自己写的也会出现这个问题, 看起来是 react 的类型文件有问题, 而不是 antd 出现的问题
