### ISSUE TITLE
ButtonGrou控件size属性设置small，icon图标不居中

### ISSUE THREAD

**Issue by chinacoolboyzz** [ant-design/ant-design#12972]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
windows10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/342jv8xx86)

### What is expected?
icon图标居中显示

### What is actually happening?
icon图标偏下

**Comment by afc163** [comment]
There area more vertical align problems: https://codesandbox.io/s/2p8k935jjp
