### ISSUE TITLE
if the Progress support three segments only?

### ISSUE THREAD

**Issue by weixianpin** [ant-design/ant-design#12984]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If I achieve four or more segments, how can I implement it with progress?
![image](https://user-images.githubusercontent.com/16029151/48054987-7caad480-e1e9-11e8-9016-ab7b2887ea80.png)

### What does the proposed API look like?
```javascrip
<Progress
        percent={60}
        successPercent={30}
        otherPercent={10}
 />
```

**Comment by afc163** [comment]
Won't support it now, I believe there segments is already a rare usage already.

**Comment by udayrajMT** [comment]
Any changes in this in the newer version? I could see only success segment in the docs - https://ant.design/components/progress/#components-progress-demo-segment
