### ISSUE TITLE
Access form so you can set field values in onValuesChange

### ISSUE THREAD

**Issue by adamjw3** [ant-design/ant-design#12989]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
Create react app latest, chrome, Mac Book pro

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1q6ykz64o7)

### Steps to reproduce
In onvaluechange the form is not passed as props

### What is expected?
to have access to the form so i can setvalues

### What is actually happening?
it errors

**Comment by adamjw3** [comment]
it looks like props is always empty on this line but should contain a reference to the form

`onValuesChange(props, values, allFieldsValues)`

**Comment by ilanus** [comment]
`onValuesChange(props)` are the props which are being passed to the `<Form />`: see example: https://codesandbox.io/s/p720qr2447 doing `setFieldsValue()` in `onValuesChange()` is invalid, you can use `onValuesChange()` to store the values in `localStorage` for example.

**Comment by adamjw3** [comment]
But thats hard coding the value. also i want to have it with dynamically adding inputs (not included in my example code) https://codesandbox.io/s/v3owr6n8x5

so from my example i have the values for in and out and want to then set the value for duration in the loop. would appreciate a little example of how to achieve this is possible

**Comment by adamjw3** [comment]
should i open a new issue?

**Comment by adamjw3** [comment]
Please have a look here https://codesandbox.io/s/v3owr6n8x5, i've updated it to use 

`document.getElementById` in a change event

it works but is this a good way

**Comment by ilanus** [comment]
- dynamic fields demo: https://ant.design/components/form/#components-form-demo-dynamic-form-item
- custom `fields` and `onChange` using mapPropsToFields demo: https://codesandbox.io/s/8kk24mjpw9
