### ISSUE TITLE
table columns title里同时使用Tooltip和sorter时Tooltip失效

### ISSUE THREAD

**Issue by lynxkor** [ant-design/ant-design#12998]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table columns title里同时使用Tooltip和sorter时Tooltip失效

### What does the proposed API look like?
table columns title里同时使用Tooltip和sorter时Tooltip失效

**Comment by SycamoreYC** [comment]
我也发现这个问题了，是不是sorter为true后 
排序的事件被加到<th>了，Tooptip接收不到事件啦？

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
