### ISSUE TITLE
Table里的rowSelection,比如在第一页选择的，切换到第二页后，在切换回来第一页选择清空了

### ISSUE THREAD

**Issue by ChrisFuck** [ant-design/ant-design#1299]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/pgdXYp?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
http://ant.design/changelog#0-12-0

**Comment by ChrisFuck** [comment]
const rowSelection = {
      selectedRowKeys,
      onChange: this.onSelectChange,
    };

API里的例子是这样，但是selectedRowKeys设置了没起作用，请问是什么问题？

**Comment by afc163** [comment]
看看 demo 的代码和你的代码有什么不同？

**Comment by afc163** [comment]
http://codepen.io/anon/pen/pgdXYp?editors=001

Need Demo.

**Comment by ChrisFuck** [comment]
onSelectChange(selectedRowKeys){
		console.log('selectedRowKeys changed: ', selectedRowKeys)
		RowSelectedStore.setRowSelected(selectedRowKeys)
		this.setState({ selectedRowKeys:selectedRowKeys })
	},

const rowSelection = {
			selectedRowKeys,
		 	onChange: this.onSelectChange}

一样的

**Comment by afc163** [comment]
And make sure your antd version above 0.12.0

**Comment by ChrisFuck** [comment]
thanks so much

**Comment by ChrisFuck** [comment]
<img width="1280" alt="screen shot 2016-03-30 at 2 42 15 pm" src="https://cloud.githubusercontent.com/assets/10722776/14133963/046969a6-f686-11e5-8287-bac34113c509.png">


你看到这个图片，是我在选择之后，提交，更新页面，然后disable已选择的item，但是那个打勾还留着，这是为什么呢？
