### ISSUE TITLE
tree控件添加expandedKeys无效

### ISSUE THREAD

**Issue by chinacoolboyzz** [ant-design/ant-design#12999]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
windows10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/342jv8xx86)

### Steps to reproduce
点击添加'0-0-0-0'  按钮

### What is expected?
'0-0'节点正常展开

### What is actually happening?
异常：点击添加'0-0-0-0'  按钮可以看到 '0-0'节点key添加到expandedKeys,但是'0-0'节点并没有展开

---
如说初始状态手动展开'0-1'节点后再点击添加'0-0-0-0'，此时可以正常展开'0-0'节点

**Comment by afc163** [comment]
```diff
-    this.setState({ treeData, expandedKeys });
+    this.setState({ treeData, expandedKeys: [...expandedKeys] });
```

这样就行了 。
