### ISSUE TITLE
Table组件的dataSource里，如果有children属性，row会变得expandable，这点在文档里没有体现

### ISSUE THREAD

**Issue by leftstick** [ant-design/ant-design#13002]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
macOS Mojave 10.14, Chrome 70.0.3538.77, React 16.6.0

### Reproduction link
[https://codepen.io/leftstick/pen/oQjmqY?editors=0010#](https://codepen.io/leftstick/pen/oQjmqY?editors=0010#)

### Steps to reproduce
1. 在设计dataSource时，数据里加入children属性
2. 表格添加了children属性的那一行，会变得expandable

### What is expected?
dataSource的数据结果和table的渲染结构无关

### What is actually happening?
dataSource的数据结构影响了渲染出的table样式

**Comment by afc163** [comment]
#1365

**Comment by smallfishr** [comment]
文档说【如果不需要或配置为其他字段可以用 childrenColumnName 进行配置】，配置其他字段可以用childrenColumnName来覆盖，如果不需要的话要怎么设置呢？

**Comment by afc163** [comment]
```
childrenColumnName="any_name_beside_children"
