### ISSUE TITLE
table 左上角斜线拆分有这样的功能吗？

### ISSUE THREAD

**Issue by top-soft** [ant-design/ant-design#13000]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
做一张交叉报表或者分组报表需要对左上角表头斜线拆分，里面添加描述，应该知道我要表达的意思吧，没看到table中的API

### What does the proposed API look like?
在 Table组件中添加这项配置

**Comment by afc163** [comment]
没有这个功能，目前也不会支持。
