### ISSUE TITLE
disabled 状态 Tooltip 长时间不消失

### ISSUE THREAD

**Issue by chinacoolboyzz** [ant-design/ant-design#13001]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
windows10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/342jv8xx86)

### What is expected?
Tooltip  正常消失

### What is actually happening?
Tooltip  长时间不消失

**Comment by afc163** [comment]
https://codesandbox.io/s/qkl3pxl9ww

**Comment by chinacoolboyzz** [comment]
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/342jv8xx86)
Tooltip 放 Popconfirm 里面，请点击此 button
button 的 disabled 状态无效还是会激活 Popconfirm
