### ISSUE TITLE
Upload.Dragger component not showing progress bar progressing on Edge

### ISSUE THREAD

**Issue by ehdwn1212** [ant-design/ant-design#13010]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
Windows 10 Enterprise, Edge 7

### Reproduction link
[https://ant.design/components/upload/#header](https://ant.design/components/upload/#header)

### Steps to reproduce
Go to minimal reproduction link and drag and drop any file.

### What is expected?
The color of progress bar filling as in other browsers

### What is actually happening?
Showing no color at all

**Comment by afc163** [comment]
@ehdwn1212 Could you help us fix this?

**Comment by ehdwn1212** [comment]
@afc163 It seems like this is a bug in Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/12224510/.
