### ISSUE TITLE
Menu组件报错：TypeError: Cannot read property 'isRootMenu' of undefined

### ISSUE THREAD

**Issue by lemondreamtobe** [ant-design/ant-design#13016]
我在Menu组件里遍历生成Submenu， SubMenu里遍历生成item，但是报错。是否不允许这样的用法呢
`<Menu
        mode="inline"
        openKeys={[openKeys]}
        onOpenChange={this.handleClick}
      >
        {
          navList.map((val, index) => {
            debugger;
            return <TreeChid key={val.id} downkey={val.id} title={val.title} list={val.nextLevelList} />;
          })
        }
      </Menu>`
`

class TreeChid extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
  }
  render() {
    const { downkey, title, list } = this.props;
    return (
      <SubMenu key={downkey} title={title}>
        {
          list.map((val, index) => {
            return <Menu.Item key={val.id}>val.title</Menu.Item>;
          })
        }
      </SubMenu>
    );
  }
}
`

**Comment by chloesun** [comment]
@lemondreamtobe 我跟你的情况一样，你找到原因了么？

**Comment by lemondreamtobe** [comment]
> @lemondreamtobe 我跟你的情况一样，你找到原因了么？

贴下代码吧。我通过改变渲染children的方式可以解决

**Comment by chloesun** [comment]
@lemondreamtobe 
```
render() {
    return (
      <Menu theme="light" defaultSelectedKeys={['1']} mode="inline">
        <Query query={FLOORS_QUERY}>
          {({ loading, error, data }) => {
            if (loading) return <h4> loading... </h4>;
            if (error) console.log(error);
            console.log(data);
            return (
              <React.Fragment>
                {data.getAllFloors.map((floor) => (
                  <SubMenu
                    key={floor.id}
                    title={
                      <span>
                        <Icon type="plus" />
                        <span>{floor.floorName}</span>
                      </span>
                    }
                  >
                    <React.Fragment>
                      {floor.rooms.map((room) => (
                        <Menu.Item key={room.id}>{room.roomNumber}</Menu.Item>
                      ))}
                    </React.Fragment>
                  </SubMenu>
                ))}
              </React.Fragment>
            );
          }}
        </Query>
      </Menu>
    );
  }
```
