### ISSUE TITLE
Dropdown `style` prop

### ISSUE THREAD

**Issue by ardok** [ant-design/ant-design#13012]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If you have a dropdown with a menu item that opens a modal, they both will "sit" on the same zIndex plane.
We also don't want to hide the dropdown on click. It should stay open while the modal is open.

At the same time, we don't want to override the CSS right away, affecting it globally.
If we were to override the CSS globally, now we wouldn't be able to have a dropdown inside a modal.

### What does the proposed API look like?
Just need to expose `style` prop to override dropdown root style.

**Comment by afc163** [comment]
`overlayStyle` `overlayClassName`

**Comment by ardok** [comment]
It works.
Just wondering, where is that `overlayStyle` from exactly?
https://ant.design/components/dropdown/

Can't find it there along in `Menu` as well.

**Comment by afc163** [comment]
I believe we missed it, could you help us adding this into documentation?

**Comment by ardok** [comment]
Yeah, I'll give it a shot. Thanks!
