### ISSUE TITLE
antd组件用commonjs模式引用方式加载，国际化不起作用？将模块引入方式改成“es2015”国际化就没问题

### ISSUE THREAD

**Issue by geowitGitHub** [ant-design/ant-design#13015]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使国际化在commonjs引用方式下起作用，控件中的英文变成中文，因为我的项目中只能使用commonjs的引用方式；

### What does the proposed API look like?
commonjs引用组件的模式下国际化起作用

**Comment by yesmeck** [comment]
可以给个弄重现的 repo 吗？

**Comment by geowitGitHub** [comment]
> 可以给个弄重现的 repo 吗？

https://codesandbox.io/s/3qm3w132p5

**Comment by afc163** [comment]
@geowitGitHub 你这只是个例子，不是"可重现"的例子。

**Comment by afc163** [comment]
```diff
- import zhCN from "antd/lib/locale-provider/zh_CN";
+ import * as zhCN from "antd/lib/locale-provider/zh_CN";
```

https://codesandbox.io/s/2wk78ynmy0

**Comment by geowitGitHub** [comment]
改成import * as zhCN from "antd/lib/locale-provider/zh_CN";后，我的编译器过不去，是不是声明文件有问题？
ERROR in [at-loader] ./web/boot.tsx:13:21
    TS2322: Type 'typeof import("E:/\u301004\u9879\u76EE\u4EE3\u7801\u3011/\u3010\u56FE\u667A\u5E73\u53F0\u3011/\u3010\u4E91\u5E73\u53F0\u3011/Geowit.Mvc/node_modules/antd/lib/locale-provider/zh_CN")' is not assignable to type 'Locale'.
  Property 'locale' is missing in type 'typeof import("E:/\u301004\u9879\u76EE\u4EE3\u7801\u3011/\u3010\u56FE\u667A\u5E73\u53F0\u3011/\u3010\u4E91\u5E73\u53F0\u3011/Geowit.Mvc/node_modules/antd/lib/locale-provider/zh_CN")'.

**Comment by afc163** [comment]
看下和 codesandbox 上的 ts 配置有什么区别。

**Comment by geowitGitHub** [comment]
我用codesandbox上的配置替换了还是报一样的错误

**Comment by afc163** [comment]
目测不是 antd 的问题，自行研究一下 ts 的配置吧。

https://unpkg.com/antd/lib/locale-provider/zh_CN

**Comment by geowitGitHub** [comment]
我这边这样改了一下，就可以了 ！谢谢！
![image](https://user-images.githubusercontent.com/29303127/48186559-4a2ce300-e373-11e8-9bae-0ba6c859771b.png)
