### ISSUE TITLE
form 使用getFieldDecorator，日期没法设置成空

### ISSUE THREAD

**Issue by chenxiaoli** [ant-design/ant-design#13011]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.6.3

### Environment
firefox

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
due_date: due_date ? Moment(date) : "",       
<FormItem
            label=""
          >
            {getFieldDecorator('date', {
              initialValue:date,
              rules: [{ required: false }],
            })(
              <DatePicker onChange={this.onDateChange} format={dateFormat} placeholder="应收日期" />
            )}
          </FormItem>

### What is expected?
DatePicker 希望是空的，显示placeholder

### What is actually happening?
报错，一定要一个 Moment，但是设置成Moment()是当前日期。求解决方案

---
在使用getFieldDecorator，DatePicker  控件时，希望能设置日期时空的。

**Comment by Veveue** [comment]
> 这么写
`
initialValue:date && moment(date)
`

**Comment by wangyong93** [comment]
> > 这么写
> > `initialValue:date && moment(date)`

谢谢，解决了我的疑问
