### ISSUE TITLE
可搜索的树，title和key必须保持一致才能在搜索的状态下展开，否则搜索后无法展开树，实际工程状态下，title无法保证唯一

### ISSUE THREAD

**Issue by z418577198** [ant-design/ant-design#13017]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
mac10.14  chrome  react 16.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://0xy96l0zzl.codesandbox.io/)

### Steps to reproduce
搜索01，树无法维持展开状态

### What is expected?
在搜索01时，autoExpandParent为true，树保持展开状态

### What is actually happening?
搜索01时，autoExpandParent为true，树不展开

**Comment by Veveue** [comment]
[example](https://codesandbox.io/s/v10798nj2l)

**Comment by zombieJ** [comment]
可以用 `filterTreeNode` 来自定义搜索规则。
