### ISSUE TITLE
Table filterDropdown in React Typescript environment [Why not Typescript examples]

### ISSUE THREAD

**Issue by lvybriage** [ant-design/ant-design#13020]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.1

### Environment
Typescript   React

### Reproduction link
[https://github.com/ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)

### Steps to reproduce
sorry

### What is expected?
比如这一行，{ setSelectedKeys, selectedKeys: number, confirm, clearFilters }) => ( 在js里应该是不会报错的，但是在typescript环境下，因为不允许any类型，所以会报错。既然antd是支持typescript的，为什么没有一些typescript的example呢？ 期待回复。

### What is actually happening?
filterDropdown: (
                { setSelectedKeys, selectedKeys: number, confirm, clearFilters }) => ( // 报错，因为环境不允许any类型
                <div className="custom-filter-dropdown">
                    <Input
                        // ref={(input) => {this.searchInput = input}}
                        ref={this.searchInput}
                        placeholder="Search name"
                        value={selectedKeys[0]}
                        onChange={e => setSelectedKeys(e.target.value ? [e.target.value] : [])}
                        onPressEnter={this.handleSearch(selectedKeys, confirm)}
                    />
                    <Button type="primary" onClick={this.handleSearch(selectedKeys, confirm)}>Search</Button>
                    <Button onClick={this.handleReset(clearFilters)}>Reset</Button>  // clearFilters 这究竟是什么类型呢
                </div>
            ),

**Comment by lvybriage** [comment]
ok

**Comment by lvybriage** [comment]
在线example： https://o45rjl3zz.codesandbox.io/ thanks~

**Comment by yesmeck** [comment]
回调方法的参数类型是需要自己写的，建议先自己学习下 TypeScript。

**Comment by lvybriage** [comment]
@yesmeck  您好，我提供了一个线上地址，等待您的回复。
