### ISSUE TITLE
Table filterDropdown state.selectedKeys does not update from props when it needs to ignore new filter value

### ISSUE THREAD

**Issue by xiety** [ant-design/ant-design#13028]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
react: 16.6.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l57j808qp9)

### Steps to reproduce
- Click filter icon on the "Name" column.
- Enter some text and press Enter. (Method handleChange will modify new filter values to { Name: "", Age: "25" })
- Click filter icon on the "Name" column again. The entered text will still be there. (But at the same time the filter icon is not highlighted)
- Additionaly check the "Age" column filter. It is changed to 25 without problems

### What is expected?
Filter text box for the "Name" column must be empty, when the props is empty and the filterDropdown is closed.

### What is actually happening?
filterDropdown component didn't update it's state, because props changed from empty array to an empty array. And there is a shallowequal in code added by #10332. And shallowequal for two empty arrays always returns true.

---
https://github.com/ant-design/ant-design/issues/10209
https://github.com/ant-design/ant-design/issues/10289

**Comment by zombieJ** [comment]
Hmmm...seems need to change the `shallowequal` logic in compare...
