### ISSUE TITLE
table 组件-可伸缩

### ISSUE THREAD

**Issue by liuzizibeisen** [ant-design/ant-design#13024]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
谷歌浏览器版本：70.0.3538.77

### Reproduction link
[https://ant-design.gitee.io/components/table-cn/#components-table-demo-resizable-column](https://ant-design.gitee.io/components/table-cn/#components-table-demo-resizable-column)

### Steps to reproduce
对其中一列，向左缩小宽度，缩小到最小宽度时继续往左拖动鼠标，部分字体变成白色

### What is [expected?](url)
字体颜色不改变，拖到最小没有变化

### What is actually happening?
字体颜色变成白色
![image](https://user-images.githubusercontent.com/41134910/48190278-456d2c80-e37d-11e8-8df1-571652a4f47f.png)

**Comment by zombieJ** [comment]
可以给标题设置`user-select: none;`：https://codesandbox.io/s/r0286p4v5q
