### ISSUE TITLE
Tabs组件没有activeKey没有匹配的时候,下划线没有消失,而且还是高亮的状态

### ISSUE THREAD

**Issue by zhalice2011** [ant-design/ant-design#13029]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rwlmk88xq)

### Steps to reproduce
https://codesandbox.io/s/rwlmk88xq

### What is expected?
期望没有activeKey没有匹配的时候,下划线也不需要高亮

### What is actually happening?
期望没有activeKey没有匹配的时候,下划线目前是高亮的

**Comment by ztplz** [comment]
@afc163  This is the current behavior in Material UI. 
link: [https://codesandbox.io/s/3v3o883025](https://codesandbox.io/s/3v3o883025)
