### ISSUE TITLE
tree uses excessive cpu resources on chrome

### ISSUE THREAD

**Issue by edencorbin** [ant-design/ant-design#13035]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
ubuntu, macos, chrome latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xv0l1k3k9q)

### Steps to reproduce
Create a draggable tree with 50 nodes and watch your system resources as you attempt to drag and drop (without releasing), resource monitor will show cpus working excessively. I am on a 4770k and have tested with lower end modern i5 as well. CPU usage also increases in firefox, but to a lesser extent and the performance on the UI is reasonable. 

### What is expected?
Reasonable UI performance and CPU usage with 50 nodes in a folder.

### What is actually happening?
UI is locking up or taking multiple seconds to become responsive when dragging folders.

---
Is this an antd issue or an underlying issue with dragging and html/etc.? I'm not entirely sure there are performance javascript libraries for drag and drop folder functionality. Note my codepen is the default, this wouldn't even work (drag and drop) on chrome for me so increasing to 50 folders seemed irrelevant.

**Comment by zombieJ** [comment]
Merge issue to #13041
