### ISSUE TITLE
TreeSelect maxTagPlaceholder attribute missing in Typescript definition

### ISSUE THREAD

**Issue by raptoria** [ant-design/ant-design#13031]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version

3.10.4

### Environment

Using Chrome on Windows

### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2x8pk6m8rn)

 

### Steps to reproduce

```
<TreeSelect maxTagPlaceholder="multiple"
```

### What is expected?

no error

### What is actually happening?

```
(51,21): Property 'maxTagPlaceholder' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TreeSelect> & Pick<Readonly<{ children?: ReactNode; }> & Readonly<TreeSelectProps>, "disabled" | "style" | "open" | "size" | ... 40 more ... | "autoClearSearchValue"> & Partial<...> & Partial<...>'.
```

---

I tried to use the sandbox to reproduce the issue, but the sandbox isn't throwing the error. However, if you look at the code, you can see that it does not exist:

 

https://github.com/ant-design/ant-design/blob/4d42f75a5903bfeaf874bdb962fa9d2a2ddd8576/components/tree-select/interface.tsx

 

My local version is still throwing the error (not sure why the sandbox is different)

**Comment by ilanus** [comment]
Thanks @raptoria
