### ISSUE TITLE
datasource列字段为key报错

### ISSUE THREAD

**Issue by z784324922** [ant-design/ant-design#13039]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
"react": "15.6.2","antd": "^3.9.2"

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/36fa3e26](https://riddle.alibaba-inc.com/riddles/36fa3e26)

### Steps to reproduce
datasource存在key字段

### What is expected?
希望这个key不用设置，如果存在key字段，能正常显示所有内容

### What is actually happening?
目前key，作为唯一标识，如果存在key字段，会引发冲突。控制台报warning，如果key字段的value相同，只会显示第一个。

**Comment by yesmeck** [comment]
没看到 warning。

**Comment by yesmeck** [comment]
奥，看到了, `key` 是关键字，你可以通过 `rowKey` 来指定用哪个字段作为 "key"。

**Comment by yesmeck** [comment]
https://codesandbox.io/s/4jqrjymnmx
