### ISSUE TITLE
Affix组件的target不是window的情况下，Affix组件脱离了target元素

### ISSUE THREAD

**Issue by flowersunshine** [ant-design/ant-design#13051]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
windows 10,，chrome 70.0.3538.77正式版

### Reproduction link
[https://ant.design/components/affix-cn/](https://ant.design/components/affix-cn/)

### Steps to reproduce
设置Affix组件target不是window，也就是antd演示的第三个，然后滚动target，当Affix出现fixed布局之后，再滚动window，Affix组件会脱离target元素，我看了一下源码，此时设置的定位是fixed，是不是将target设置为非static定位，然后Affix设置为absolute定位会比较好？

### What is expected?
Affix组件不会脱离target元素。

### What is actually happening?
Affix组件脱离了target元素的视口。

**Comment by afc163** [comment]
Duplicate of #12270
