### ISSUE TITLE
隐藏表格某些列后，最后一列后面跟了很多空白

### ISSUE THREAD

**Issue by iHadDream** [ant-design/ant-design#13050]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
mac10.14 chrome react15.6.2

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
对table的一些列，设置className display:'none'

### What is expected?
设置display none 不显示最后一列的多余的空白

### What is actually happening?
对table的一些列，设置className display:'none'，页面中在表格最后一列多展示了很多空白

**Comment by hyliuzhenhao** [comment]
个人觉得删除table某一项可以通过删除columns中的数组来控制
