### ISSUE TITLE
menu was wrong in collapse mode

### ISSUE THREAD

**Issue by LeeGeonho** [ant-design/ant-design#13055]
### Version
3.10.4

### Environment
mac mojave, react 16.5.1, antd pro 2.0.0

### Steps to reproduce
go to collapse mode > click side menu

### What is expected?
shows in pop-up style

### What is actually happening?
not show in pop-up style

---
Screen shot
https://user-images.githubusercontent.com/9799339/48258561-b1709300-e458-11e8-9956-6aa29d0cd4b1.png

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/85a758c7ec8611936f50092d0bae7b492d8caa1c

https://github.com/ant-design/ant-design-pro/issues/2783#issuecomment-436494262

**Comment by LeeGeonho** [comment]
@afc163 
It was fixed after resizing browser window on v3.10.7
but If you refresh your browser after adjusting the window width to about 950px, it still occurs
Thanks for help
