### ISSUE TITLE
TreeSelect prop which allows drop down to remain open until input’s focus is lost

### ISSUE THREAD

**Issue by raptoria** [ant-design/ant-design#13066]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

 

### What problem does this feature solve?

I have a use case where I’m using TreeSelect to make excel-like filters. The drop down should remain open while the user is checking/unchecking options. The update filters request does not get called until onDropDownVisibleChange (dropdown is closed). This way, a request does not get sent for every checked item - only when the user is done selecting options in the dropdown.

 

1. User wants to search for ItemA and ItemB ( treeCheckable is set to true)

2. User searches for itemA, dropdown opens and highlights the item. He/she checks it. The dropdown remains open (so far this is default TreeSelect behavior)

3. User goes to type in ItemB into the search box, but the dropdown closes which calls onDropDownVisibleChange which sends the filter request prematurely. Idea for enhancement: keep dropdown open until input loses focus, only then the user is ‘done’

 

### What does the proposed API look like?

<TreeSelect dropdownStayOpen={true}

**Comment by zombieJ** [comment]
You can use `open` to control this:
```jsx
<TreeSelect open={this.state.open} {...restProps} />
```
