### ISSUE TITLE
table can Specifies the cell display color and table head On the left

### ISSUE THREAD

**Issue by SynChron1zed** [ant-design/ant-design#13068]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table can Specifies the cell display color and table head On the left

### What does the proposed API look like?
color and head

**Comment by zombieJ** [comment]
You can use [`onHeaderCell`](https://ant.design/components/table-cn/#onRow-%E7%94%A8%E6%B3%95).
