### ISSUE TITLE
如果要用form的this.props.form.getFieldsValue()方法得到表单输入内容，必须新建一个文件专门装这个form吗

### ISSUE THREAD

**Issue by juemin90** [ant-design/ant-design#1306]
文档上写要获得表单里输入的内容，要用到this.props.form.getFieldsValue()方法，
而如果想在props里有form.getFieldsValue()方法，就要用到类似
```
BasicDemo = createForm()(BasicDemo);
```
这样的步骤。
这样说，是不是需要每用到一个Form就要新建一个文件来装这个Form？
因为一个文件里只能有一个Component。
感觉这样不是最佳实践。
请问有更好的方法吗？

**Comment by benjycui** [comment]
把一个 Form 提取成一个组件，还是挺好的么，不要用 HTML 的方式写 JSX。

**Comment by juemin90** [comment]
如果Form很多，不是要维护很多文件。提取是好，但是如果不是通用组件，只能增加维护成本吧。

**Comment by benjycui** [comment]
即使不是通用组件，按职责划分组件也是个好习惯。
