### ISSUE TITLE
getFieldDecorator re rendering the whole component 

### ISSUE THREAD

**Issue by monzoor** [ant-design/ant-design#13063]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.5

### Environment
macOS High Sierra 10.13.3, Version 70.0.3538.77 (Official Build) (64-bit), react 16.6.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r58926x56o)

### Steps to reproduce
Two way to check
Check 1:
1. Click on the checkbox 
2. Component console log will be shown every changes

Check 2:
Latest react has feature to check the performance https://reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html
If we check the profiler graph it shows all the components are re rendering. 

### What is expected?
Just the checkbox change not the whole component. 

### What is actually happening?
Re rendering whole component.

**Comment by snanilim** [comment]
I face this also.

**Comment by esarner** [comment]
Same here. I have a lot of form items with field decorators and changing one affects them all. It really slows down the page to a point where it's unusable.

**Comment by kino90** [comment]
I have the same issue. Does someone know a workaround or similar?

**Comment by aindong** [comment]
Same issue here, please enlighten us.

**Comment by afc163** [comment]
It is intented behavior.

**Comment by happier2** [comment]
We faced the same issue. It's a shame when form has lots of component.

**Comment by ztplz** [comment]
Actually this is a common problem about HOC form. We make it available to validate the form by injecting properties, but it also causes whole form re-render. I tried to make the form accurately refresh like `mobx-react`, but it may causes some break change. Because forms are used in a lot of old code, we need to be careful and limit our thoughts. We must first ensure compatibility, then performance. 
One solution is to provide new and better performance verification components, this won't cause break change. 
Another way is to optimize the performance of the form. We can't avoid render whole component, but we can minimize the number of re-render.
At the moment, if you are facing some performance problems about form, splitting into multiple forms is still the best way.

**Comment by miyunim** [comment]
Same here. Inserting texts in the Input box is very slow.

**Comment by Bramarth** [comment]
The problem can be easily solved. By reading the doc of antd, we can see that there are two interesting properties to avoid a global rendering.

When you wrap with `getFieldDecorator`, you can specify it like this : 

```javascript
{getFieldDecorator('lastName', {
  trigger: 'onBlur',
  valuePropName: 'defaultValue',
  initialValue: user.lastName,
  rules: [{ required: true, message: 'Please input the lastName !' }]
})(<Input name="lastName" onBlur={onChange} />)}
```

1. **Trigger** prop is used to target a value from children prop. In our case : onBlur.
2. **valuePropName** also targets one value from children prop. In our case **defaultValue** that has been override by **initialValue**.

You no longer have any global rendering affecting your performance.

**Comment by alexchen1875** [comment]
> The problem can be easily solved. By reading the doc of antd, we can see that there are two interesting properties to avoid an overall untimely rendering.
> 
> When you wrap your element with `getFieldDecorator`, you can specify it like this :
> 
> ```js
> {getFieldDecorator('lastName', {
>   trigger: 'onBlur',
>   valuePropName: 'defaultValue',
>   initialValue: user.lastName,
>   rules: [{ required: true, message: 'Please input the lastName !' }]
> })(<Input name="lastName" onBlur={onChange} />)}
> ```
> 
> 1. **Trigger** prop is used to target a method from children node. In our case : onBlur.
> 2. **valuePropName** also targets a prop from children node. In our case **defaultValue** that is override by **initialValue**.
> 
> You no longer have any global rendering affecting your performance.

YEAH!!       its a solution... maybe we should split alone component for each From

**Comment by vKongv** [comment]
> onBlur

@Scharpp 
I tried the solution but my Input doesn't render the data anymore when I type. Is it a new feature?

My antd version is `3.9.2`

**Comment by atharhashmi** [comment]
@vKongv Did you ever solve it? I am having the same issue...

**Comment by BRKsReginaldo** [comment]
@atharhashmi for you and anyone who gets to this issue on the future, i've managed to create a "solution",
as said before on this thread, this always re-render is the expected behavior, so i've created a PersistedInput component to avoid dispatching onChange method on every input

// PersistedInput.js

```js
const debouncedOnChange = debounce((e, onChange) => {
  onChange(e)
}, 500)

const persistedOnChange = onChange => e => {
  e.persist()
  debouncedOnChange(e, onChange)
}

const PersistedInput = ({renderInput, onChange, ...props}) => 
  renderInput({...props, onChange: persistedOnChange(onChange)})

export default PersistedInput
```

and then you can do this:

```js
getFieldDecorator('field', {
  valuePropName: 'defaultValue',
  initialValue: 'defaultValue'
})(
  <PersistedInput
    renderInput={props => <Input disabled={readOnly} {...props}/>}
  />
)
```

This will only update the form value when the input go iddle for 500ms, you can update that value as you wish

**Comment by atharhashmi** [comment]
Superb! I will give it a try and update you. Thanks a lot.

**Comment by yuribit** [comment]
I am also having this problem when the form has more than 140 form items. 
The two "solutions" proposed by @Scharpp and @BRKsReginaldo  are more of a workaround than a real solution.

I am going to replace Antd `getFieldDecorator` with [Formik FastField](https://jaredpalmer.com/formik/docs/api/fastfield).

**Comment by rmolinamir** [comment]
IMO, `trigger: 'onBlur',` is a bandaid fix (no offense of course). `getFieldDecorator` should provide debounce by itself, just integrate it with lodash. But even with debounce, after the timer of the debounce is over, the whole container will re-render.

**Comment by gauravchaware** [comment]
> The problem can be easily solved. By reading the doc of antd, we can see that there are two interesting properties to avoid an overall untimely rendering.
> 
> When you wrap your element with `getFieldDecorator`, you can specify it like this :
> 
> ```js
> {getFieldDecorator('lastName', {
>   trigger: 'onBlur',
>   valuePropName: 'defaultValue',
>   initialValue: user.lastName,
>   rules: [{ required: true, message: 'Please input the lastName !' }]
> })(<Input name="lastName" onBlur={onChange} />)}
> ```
> 
> 1. **Trigger** prop is used to target a method from children node. In our case : onBlur.
> 2. **valuePropName** also targets a prop from children node. In our case **defaultValue** that is override by **initialValue**.
> 
> You no longer have any global rendering affecting your performance.

Yes, inputs are working well after applying this but it puts me into a new problem.
this.props.form.setFiledsValue() not setting new value after using this solution. if input already contains some value this.props.form.setFiledsValue() not working.
a huge problem will be solved if some will solve this.
Thanks.

**Comment by oktorakevinarigi** [comment]
> @atharhashmi for you and anyone who gets to this issue on the future, i've managed to create a "solution",
> as said before on this thread, this always re-render is the expected behavior, so i've created a PersistedInput component to avoid dispatching onChange method on every input
> 
> // PersistedInput.js
> 
> ```js
> const debouncedOnChange = debounce((e, onChange) => {
>   onChange(e)
> }, 500)
> 
> const persistedOnChange = onChange => e => {
>   e.persist()
>   debouncedOnChange(e, onChange)
> }
> 
> const PersistedInput = ({renderInput, onChange, ...props}) => 
>   renderInput({...props, onChange: persistedOnChange(onChange)})
> 
> export default PersistedInput
> ```
> 
> and then you can do this:
> 
> ```js
> getFieldDecorator('field', {
>   valuePropName: 'defaultValue',
>   initialValue: 'defaultValue'
> })(
>   <PersistedInput
>     renderInput={props => <Input disabled={readOnly} {...props}/>}
>   />
> )
> ```
> 
> This will only update the form value when the input go iddle for 500ms, you can update that value as you wish

I tried this method successfully. but I get a warning "The function component cannot be given a reference. Attempts to access this reference will fail. Do you intend to use React.forwardRef ()?".

I've tried a number of things but I can't get rid of that warning. Is there a solution for this?

**Comment by annjawn** [comment]
This literally makes it impossible to use `getFieldDecorator` with large forms.

**Comment by 8bu** [comment]
Is there any new update for this issue? I got into the same situation and those workarounds above are not possible in my project

**Comment by avalanche1** [comment]
Same here. Why won't the devs fix this?? @afc163

**Comment by rmolinamir** [comment]
I've been subscribed to this issue for a while, it's a very critical thing because of the HUGE impact on performance.

I haven't looked at the source code but wouldn't be using `useMemo` on the input components/decorators and then subscribe to the value of their respective values to memoize prevent re-renders unless the value changes practically fix this issue?

**Comment by annjawn** [comment]
Meanwhile, i've created a custom Datepicker that is keyboard friendly and also takes care of the performance improvement. It uses `<Calendar/>`, `<Popover/>` and `<Input/>` components and gives a somewhat bearable datepicker that can be used in a form. It handles `Tab` and `Esc` keys for proper keyboard accessibility inside a form. You must use `trigger: "dateChange"` and `validateTrigger: "onChange"` in the `getFieldDecorator`. It also won't cause performance issue if used inside of a Large `<Form />` component since the `trigger` is `debounced` after a delay, you can change the delay to whatever suits you.

Here it is.

https://gist.github.com/annjawn/66ba488a41883adcecb9b46c8853b5a3

Usage:
```js
import Datepicker from 'components/DatePicker';

....
//date validation 
checkdate = (rule, value, callback) => {
    if (value) {
      callback();
      return;
    }
    callback('Date is required!');
  };

render(){
     .....
    <Form.Item>
     {getFieldDecorator('dateValue', {
                      validateTrigger: "onChange",
                      trigger: "dateChange",
                      valuePropName: "value",
                      rules: [{ validator: this.checkdate }]            
                    })(                      
                      <Datepicker
                        disabledDate={this.disabledDate}
                        format='MM-DD-YYYY'
                        placeholder='MM-DD-YYYY'   
                      />                      
          )}      
    </Form.Item>
    .....
}
```

**Comment by topazas** [comment]
This needs to be addressed and solved because this is critical for the real world applications, now antd performance is unusable for any bigger form.

**Comment by avalanche1** [comment]
This seems to be fixed in `4.0`. Yay!
Plus, no more `getFieldDecorator`

**Comment by 8bu** [comment]
> 
> 
> This seems to be fixed in `4.0`. Yay!
> Plus, no more `getFieldDecorator`

wait what

**Comment by avalanche1** [comment]
yep.
https://next.ant.design/components/form/v3
but maybe they'll provide an auto-patcher if you ask them

**Comment by 8bu** [comment]
> 
> 
> yep.
> https://next.ant.design/components/form/v3
> but maybe they'll provide an auto-patcher if you ask them

ty for your response. Seem like I have to refactor all current forms in my project, btw when will they update v4 for their Vue version, currently I'm using ant-design with Vue not React.. Did a search job but found no information about Vue update

**Comment by rkumar1904** [comment]
> The problem can be easily solved. By reading the doc of antd, we can see that there are two interesting properties to avoid an overall untimely rendering.
> 
> When you wrap your element with `getFieldDecorator`, you can specify it like this :
> 
> ```js
> {getFieldDecorator('lastName', {
>   trigger: 'onBlur',
>   valuePropName: 'defaultValue',
>   initialValue: user.lastName,
>   rules: [{ required: true, message: 'Please input the lastName !' }]
> })(<Input name="lastName" onBlur={onChange} />)}
> ```
> 
> 1. **Trigger** prop is used to target a method from children node. In our case : onBlur.
> 2. **valuePropName** also targets a prop from children node. In our case **defaultValue** that is override by **initialValue**.
> 
> You no longer have any global rendering affecting your performance.

This is Awesome trick to handle the multiple form element if you'r working with big **form**.
& ThankYou for the tips.   @Scharpp

**Comment by abellee** [comment]
@avalanche1  so we have to everything about validation self? just like we have to set the `onChange` event of the `Input` and then put the value somewhere and get it when submit??
