### ISSUE TITLE
Form表单不能出现错误提醒

### ISSUE THREAD

**Issue by fangkyi03** [ant-design/ant-design#13071]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
mac 10.14.1 chrome 70.0.3538.77

### Reproduction link
[https://codesandbox.io/s/v1y79ynz75](https://codesandbox.io/s/v1y79ynz75)

### Steps to reproduce
编辑框删除文字的时候 没有错误提醒

### What is expected?
希望编辑框删除数据的时候 如果检测到数据不符合要求进行错误提醒

### What is actually happening?
编辑框删除文字的时候 没有错误提醒

---
antd版本:3.10.1
```
export const createFromGroup = ({ modelName, data }) => {
  let newData = []
  Object.keys(data).map((e) => {
    newData = newData.concat(data[e].data)
  })
  return connect((state) => ({ ...state[modelName], modelName, data }))(Form.create({
    onValuesChange: (props, fields, allFields, add) => {
      props.dispatch({ type: `${modelName}/setValue`, payload: { dataSource: {...props.dataSource,...allFields} } })
      // props.dispatch({ type:`Form/sumbit`,payload:{name:modelName}})
    },
    mapPropsToFields: (props) => {
      let obj = {}
      if (!props.dataSource) return
      Object.keys(props.dataSource).map((e) => {
        const select = newData.find((el) => el.key == e) || { key: '' }
        switch (select.type) {
          case 'datePicker':
            obj[e] = Form.createFormField({
              value: moment(props.dataSource[e])
            })
            break;
          case 'uploadImg':
            if (props.dataSource[e]) {
              obj[e] = Form.createFormField({
                value: tranImage(props.dataSource[e])
              })
            }
            break;
          default:
            obj[e] = Form.createFormField({
              value: props.dataSource[e]
            })
        }
      })
      return obj
    }
  })(FormCardGroup))
}
```
因为业务需求的关系 antd默认的表单无法满足自身的业务需求 所以在antd上面又包裹了一层自己的框架 可以说效果非常显著 所有的表单写的都很愉快 但是最近发现有个问题就是 如果我这样包裹了以后 表单删除数据或者录入数据的时候 不能有效的进行错误提醒 必须要点击提交的时候 才可以有错误提醒的效果

一开始以为是rc-form出现了问题 所以去看了一下rc-form的源码并且做了调试 最后发现 rc-form并没有实现errors的渲染 这部分操作是antd自己实现的 所以又去看了一下antd的底层源码 找到了问题 但是却不知道因为什么原因引起的 所以希望官网能帮忙解决一下

出现问题的代码
![image](https://user-images.githubusercontent.com/30390014/48300216-57cd9e80-e514-11e8-8d40-ebbc36f5a27b.png)

![image](https://user-images.githubusercontent.com/30390014/48300221-61570680-e514-11e8-8785-cf93b7778a0b.png)

这张是正常的
![image](https://user-images.githubusercontent.com/30390014/48300225-6caa3200-e514-11e8-95a0-d405b5425ae6.png)

这张是不正常的
![image](https://user-images.githubusercontent.com/30390014/48300230-a1b68480-e514-11e8-9e36-e78249926959.png)

所以出现这个编辑框删除内容不进行提醒的原因在于这个data_field这边根本没有返回对应的errors这个数据 所以自然也就无法在页面上显示出对应的错误提醒 希望官方能解决一下

![image](https://user-images.githubusercontent.com/30390014/48300266-1984af00-e515-11e8-8b3e-6481868727de.png)

![image](https://user-images.githubusercontent.com/30390014/48300273-2ef9d900-e515-11e8-8806-c16b9927210d.png)

![image](https://user-images.githubusercontent.com/30390014/48300276-3620e700-e515-11e8-9c1e-1e34d5196458.png)

**Comment by hileix** [comment]
Reproduction link 进不去

**Comment by fangkyi03** [comment]
https://codesandbox.io/s/v1y79ynz75
问题出在这里
![image](https://user-images.githubusercontent.com/30390014/48350959-b08f6980-e6c3-11e8-8410-e38344c414b6.png)
当你在valueChange事件中再对model进行操作的时候 会同时触发
![image](https://user-images.githubusercontent.com/30390014/48350983-c735c080-e6c3-11e8-9591-3b25deccf53d.png)
从而导致页面又重新的刷新了一次 初始化了一次 所以导致那时候没有触发任何操作也自然不会有错误提醒了
这个dvajs是我对dva的一个封装 这个你们不用担心 你们可以直接用自己在valueChange时操作model来复现这个效果

**Comment by zombieJ** [comment]
参考一下官方例子：https://ant.design/components/form-cn/#components-form-demo-global-state

你的写法不对：https://codesandbox.io/s/2v5180jk6n

**Comment by fangkyi03** [comment]
> 参考一下官方例子：[https](https://ant.design/components/form-cn/#components-form-demo-global-state)：[//ant.design/components/form-cn/#components-form-demo-global-state](https://ant.design/components/form-cn/#components-form-demo-global-state)
> 
> 你的写法不对：[https](https://codesandbox.io/s/2v5180jk6n)：//codesandbox.io/s/2v5180jk6n[](https://codesandbox.io/s/2v5180jk6n)

我个人觉得并不是我写法不对 而是你们这个东西 如果要跟redux密切组合起来的话 我肯定希望有个地方能直接保存dataSource 因为这个东西就是到时候要提交给后台的数据 我不可能把当前form的结构提交给后台 所以我希望的是能直接通过这个来直接回显 我关注的只是数据流 而不是连错误也都需要我这边来处理 如果现在用你给的方式去做的话 的确 错误可以显示了 但这是因为自己传递了errors给他才实现的 那换个思路来说 如果我现在要外部去改变这个数据的时候 那么是否我也得自己传递对应的errors给他才能显示对应的错误提醒呢 这明显是不对的 你们这个form组件在显示的时候 应该跟当前组件上一次的errors状态进行一下合并 而不是需要我自己传递过去

**Comment by zombieJ** [comment]
form 将 field 相关数据全部交给用户，用户如何处理是自己的业务逻辑。如果只需要值而不希望对 field 做成受控的，只处理 onValuesChange 即可。

**Comment by fangkyi03** [comment]
主要问题是mapPropsToFields这个东西会在onValuesChange 刷新model的时候也会被触发了 导致我下次刷新的时候 我用的是model中的dataSource 这个里面是没有errors的 所以导致原本应该有errors状态的组件 又变成原来的样子了 只刷新数据 但是无法触发数据的效验 比如现在的我通过model刷新的时候也是一样 数据刷新了的确没错 但是无法再外部触发这个数据的效验 导致即使数据是错误的 也不会提醒

**Comment by fangkyi03** [comment]
抛离其他的任何一个不说 我现在就像从外部通过model去刷新对应的antd表单数据 这个时候 我要如何让其进行效验呢 因为现在的model刷新方式 仅仅只是刷新数据 但是无法进行错误的效验 这难道不算是个问题吗

**Comment by zombieJ** [comment]
> 主要问题是mapPropsToFields...

建议看一下[受控组件](https://reactjs.org/docs/forms.html#controlled-components)的概念，当你对 Field 进行控制时，其所有状态都由你的代码逻辑来控制，value 只是其中一项。如果需要控制 Filed 的值，那么它的所有状态都交由你来管理。组件提供了 error 信息，而你控制的时候不给予它 error，当然就不会有了。

> 抛离其他的任何一个不说 我现...

用 [`validateFields`](https://ant.design/components/form-cn/#validateFields/validateFieldsAndScroll) 来做表单校验哈~

--------------- 我是分割线 ---------------

如果你想要 store 保持洁净，可以用 HOC 包一下，让错误信息不透出来。不过我觉得从你的使用场景看，用 `initialValue`, `validateFields` 和 `onValuesChange` 就足够了。

**Comment by fangkyi03** [comment]
受控组件 也不代表每次刷新数据连errors都需要自己处理吧 没有要求受控组件一定要这样做吧 就不能你处理errors只将数据变成受控的吗

**Comment by fangkyi03** [comment]
换个角度思考一下 变成 我刷新的时候 触发一下新的onChange 然后生成一个新的errors 这样不就可以了 不管是model改变 还是组件自带的onChange你都理解等于是组件的onChange 然后去根据组件的值走一次对应的errors不就可以了吗 因为pc端用的是你们antd的 我自己的react-native端 我都是自己封装的form表单 我这边就是这样实现的 通过这种方式 我关注的 永远只是数据 其他部分 都由内部来进行实现

**Comment by yesmeck** [comment]
你需要用 `onFieldsChange` 把 `errors` 也存到 `redux` 里。

**Comment by zombieJ** [comment]
还是建议自己封装一下。就像我上面提到的，Field 受控就一起受控了，把受控改成混合受控反而造成不确定性。当用户决定通过受控方式控制 Field，一切行为应该交由用户来处理。

**Comment by fangkyi03** [comment]
> 你需要用 `onFieldsChange` 把 `errors` 也存到 `redux` 里。

单纯的组件onChange没问题 但是如果说你直接不经过组件触发由外部的model来触发的话 我这个errors从何而来呢

**Comment by fangkyi03** [comment]
希望这个问题能解决一下 我感觉如果让别人自己去实现errors这个的话 等于重新写了一个antd没区别

**Comment by afc163** [comment]
@fangkyi03 如果你需要更自由且白盒的表单，建议不要使用 Form.create 和 getDecorator 提供的双向绑定。我们支持直接使用 Form.Item 的各类属性绑定错误和提示信息，你可以自行校验和绑定各表单组件的 onChange。你可以看这个例子：https://ant.design/components/form-cn/#components-form-demo-validate-static

**Comment by fangkyi03** [comment]
> @fangkyi03 如果你需要更自由且白盒的表单，建议不要使用 Form.create 和 getFormDecorator 提供的双向绑定。我们支持直接使用 Form.Item 的各类属性绑定错误和提示信息，你可以自行校验和绑定各表单组件的 onChange。你可以看这个例子：https://ant.design/components/form-cn/#components-form-demo-validate-static
这样的话 工作量更大 因为 我等于需要把整个antd form部分全部重写

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/48751269-72dfa180-ecbe-11e8-9d73-fa0e2628550d.png)
![image](https://user-images.githubusercontent.com/30390014/48751283-88ed6200-ecbe-11e8-8562-80abde6b76a7.png)
我原本用onValueChange的时候 这边直接用defaultFileList是可以在初始化的时候赋值的
但是现在我 用了onFieldsChange以后 在defaultFileList这边赋值没用了 我下断跟了一下 发现是因为你们压根就不读取这个的数据 只在初始化的时候读取了一下 但是因为 我的这个value值是mapPropsToFields生成的 所以初始化的时候其实是没数据的 最后就导致这里一直读不到数据显示不出来

**Comment by chj-damon** [comment]
@afc163 @zombieJ 请问为什么onFieldsChange和onValuesChange里面都没有办法直接通过props.forms拿到form呢？

**Comment by wulei7528** [comment]
问题还是出在实现mapPropsToFields这个方法时，我们一般同步redux里面的表单数据只包括value值，导致表单字段的error对象丢失了，进而页面上所有的错误提示都会被清空，我也遇到类似的问题，很困惑：为什么我还要关心error，我仅仅只是想双向绑定表单的核心数据啊

**Comment by afc163** [comment]
error 也是核心数据，field 里包括 value 和 error 两个状态。

**Comment by ztplz** [comment]
@afc163  加个没历史包袱的新form吧，hook + ts

**Comment by fangkyi03** [comment]
其次表单还有一个问题 就是比如datePicker upload inputSelect等等都有很多问题
尤其是inputSelect这个完全就是一个智障的大坑
如果我同一行里面有多个控件在的话 直接包在同一个formItem里面的时候 就会导致这个error无法正确提醒
你必须要改成input的addonBefore去兼容 代码复杂度 直线上升
其次datePicker也是智障 自己都设定了format了 自己还不会转换 返回的结构还有moment的结构 导致自己又需要处理一次

**Comment by zhengcanbiao** [comment]
不知道是不是同个问题。我的使用场景是，我需要单独使用Form组件，但是按钮我是放在父层的组件上，在父层想判断error为true的时候按钮置灰。目前遇到一个问题，通过onValuesChange我可以拿到Form组件的表单数据，error数据通过onFieldsChange 回调进行数据处理传到父层，拿到这两个数据之后，，form组件不能正常的显示错误信息，需要把error信息也传回form组件才可以正常显示。矛盾点在，我不希望处理error数据又传回form组件，这个数据不是我想处理的，我只想读到它的值。或许可以考虑提供一个onError回调就好了？

**Comment by yoyo837** [comment]
看了对话，大部分还是使用问题，剩下的部分就是封装效果没有100%贴合使用者特定的需求。

**Comment by chj-damon** [comment]
mapPropsToFields要和onFieldsChange配合使用，而且我发现在validateFields的时候，要强制指定force: true，不然会有问题。具体的问题等我新建一个codesandbox重现一下。

**Comment by Bealiah** [comment]
> 不知道是不是同个问题。我的使用场景是，我需要单独使用Form组件，但是按钮我是放在父层的组件上，在父层想判断error为true的时候按钮置灰。目前遇到一个问题，通过onValuesChange我可以拿到Form组件的表单数据，error数据通过onFieldsChange 回调进行数据处理传到父层，拿到这两个数据之后，，form组件不能正常的显示错误信息，需要把error信息也传回form组件才可以正常显示。矛盾点在，我不希望处理error数据又传回form组件，这个数据不是我想处理的，我只想读到它的值。或许可以考虑提供一个onError回调就好了？
onFieldsChange 拿不到当前操作项的errors信息,始终为undefined,需要从validateFields后存储的errors拿

**Comment by Bealiah** [comment]
onFieldsChange 拿不到当前操作项的errors信息,始终为undefined,需要从validateFields后存储的errors拿

**Comment by AdmireWang** [comment]
我也遇到这个问题，form中的input的数据来自redux，input值变化后发出action更新redux，这时也出现了无法报验证失败的问题。因为form中的其他地方也要用到redux的这个数据，所以才这么弄。想了下可以把redux的数据另存一份，把这个另存的传给form，交由form管理，input变化的时候更新原来的数据，使用的时候也还是使用原来的数据。

**Comment by chj-damon** [comment]
try this way:
this.props.form.validateFields({ force: true }, (err: Error, values: any) => {})

**Comment by steadyzeus** [comment]
在model中 存储form的changedFields ，
在mapPropsToFields的时候对字段进行errors 赋值就行了
smsToken: {
        value: smsToken,
        errors: formErrors ? (formErrors.smsToken ? formErrors.smsToken.errors : "") : ""
      },
