### ISSUE TITLE
Some icons are not centered

### ISSUE THREAD

**Issue by Mrtenz** [ant-design/ant-design#13074]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.5

### Environment
Arch Linux, Google Chrome 70.0.3538.77 (64-bit), React v16.6.1, Webpack v4.25.1

### Reproduction link
[https://github.com/Mrtenz/antd-test](https://github.com/Mrtenz/antd-test)

### Steps to reproduce
Create a modal or pagination.

### What is expected?
The icons should be centered.

### What is actually happening?
The icons are only horizontally centered, not vertically.

---
The issue may apply to other components as well, but modals and tables (pagination) were the ones where I ran into this issue.

**Comment by ztplz** [comment]
@Mrtenz  You've forgotten `<!DOCTYPE html>`.  Browsers use different CSS by default depending on whether a doctype is declared. Code on `demo` and `Codesandsbox` automatically uses an HTML 5 doctype, unless your document starts with `<!DOCTYPE html>` you will be missing some of the styles you can see on `demo` and `Codesandsbox`. [This is where you made a mistake](https://github.com/Mrtenz/antd-test/blob/master/src/index.html#L1)

**Comment by Mrtenz** [comment]
@ztplz Wow, now I feel really stupid... I was looking for issues in the JS, didn't really think it was a problem with the `index.html`. Thanks a lot for figuring that out!

**Comment by anson-GH** [comment]
My project included <!DOCTYPE html> but it does not work for me. Please help

**Comment by bowdawn** [comment]
If we already have <!DOCTYPE html> in out index.html file is there any other solutions to fix this bug?

**Comment by brandonwisnicki** [comment]
> 
> 
> If we already have in out index.html file is there any other solutions to fix this bug?

Are you using TailwindCSS by any chance?
I was having the same issue until I figured out that TailwindCSS had "vertical-align: center;" in its output that seemed to mess with the button icons in Antd. To solve this, I added the following to my tailwind.css file (where I imported base, components, and utilities):


`
svg {
    vertical-align: baseline;
}
`

Make sure to add this AFTER your imports from TailwindCSS. This should override the output. :)

**Comment by charitha95** [comment]
> svg { vertical-align: baseline; }

Amazing. This solved my issue. I didn't know that it was overriding. Appreciate the sharing <3

**Comment by yogithesymbian** [comment]
i am not using tailwind and already use doctype html , still icon are not centered .

**Comment by yashspr** [comment]
In addition to @brandonwisnicki answer, I had to do this to get it to work.

```css
@tailwind base;

@layer base {
    svg { 
        display: inline;
        vertical-align: baseline; 
    }
}
```

**Comment by chj-damon** [comment]
@yashspr Thank you so much! you saved my day

**Comment by zabihullah-azadzoi** [comment]
> > If we already have in out index.html file is there any other solutions to fix this bug?
> 
> Are you using TailwindCSS by any chance? I was having the same issue until I figured out that TailwindCSS had "vertical-align: center;" in its output that seemed to mess with the button icons in Antd. To solve this, I added the following to my tailwind.css file (where I imported base, components, and utilities):
> 
> `svg { vertical-align: baseline; }`
> 
> Make sure to add this AFTER your imports from TailwindCSS. This should override the output. :)

I had the same issue but with bootstrap but this one line saved my day.
