### ISSUE TITLE
antd在ts中的使用

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#13078]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我查看了官网的文档，没发现antd有对ts进行过仔细的使用，比如表单的一些props，基类等等，都不知道，请问有文档吗？

### What does the proposed API look like?
文档链接...

**Comment by afc163** [comment]
https://ant.design/docs/react/use-in-typescript-cn

https://ant.design/components/form-cn/#%E5%9C%A8-TypeScript-%E4%B8%AD%E4%BD%BF%E7%94%A8
