### ISSUE TITLE
badge appear animation conditional

### ISSUE THREAD

**Issue by Enalmada** [ant-design/ant-design#13082]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Next.js page transitions each cause badge appear animation to fire with every page change.  This is extremely undesirable when badge is in a global layout like header.  This can be worked around using css to disable it completely ".ant-badge-zoom-appear {animation: none;}" but then we get no animation when it legitimately appears for the first time.

### What does the proposed API look like?
name: appearAnimation
description:Whether to trigger animation when badge appears 
type: boolean
default: true

**Comment by afc163** [comment]
> Next.js page transitions each cause badge appear animation to fire with every page change. 

Could you provide a reproduible demo?

**Comment by Enalmada** [comment]
Here is a a minimal reproducable demo:
   https://github.com/Enalmada/next-reason-boilerplate/tree/badgeFlicker 

(since this involves next.js and npm I tried getting codebox to work but had trouble so I made a branch)

**Comment by zombieJ** [comment]
Pls simplify you sample to make sure provided the mini reproduce, since the repo contains too many deps.

**Comment by Enalmada** [comment]
I spent many hours cutting down my full project into a small reproducible example just for this.

**Comment by zombieJ** [comment]
Check the code.
Your layout component is in page component. When user change the page, the hole page includes `MyLayout` is new mounted. So the `Badge` under `MyLayout` is all new mounted which get the appear animation. Pls check [next.js doc](https://nextjs.org/docs/#custom-app) for how to handle customize layout.

**Comment by zombieJ** [comment]
Maybe you can ref this for sub common layout: https://github.com/zeit/next.js/issues/596
