### ISSUE TITLE
AutoComplete object as defaultValue throws an error

### ISSUE THREAD

**Issue by delca85** [ant-design/ant-design#13081]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
Mac OS 10.14.1 Chrome Version 70.0.3538.77 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mzw057n388)

### Steps to reproduce
Sending an object as defaultValue to AutoComplete

### What is expected?
According to [AutoComplete](https://ant.design/components/auto-complete/#API) documentation, it should accept a defaultValue composed by key and label fields

### What is actually happening?
An _Invariant Violation_ error is thrown, telling that _Objects are not valid as a React child..._

**Comment by ztplz** [comment]
@afc163  `defaultValue` in `AutoComplete` only supports `string` and `string[]`. It seems that 
 the `Select` docs should also be updated.

**Comment by afc163** [comment]
When use `labelInValue`, it could support a object like `{ label: xx, value: xx }`.

**Comment by afc163** [comment]
https://codesandbox.io/s/6l96pv9pkw
