### ISSUE TITLE
Tabs 组件在 tabPosition 为 left 或 right 的时候，renderTabBar 会使样式失效

### ISSUE THREAD

**Issue by Madridspark** [ant-design/ant-design#13086]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
Windows 10

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n4po60lmqj)

### Steps to reproduce
1. 设置 Tabs 组件的 tabPosition 属性为 left
2. 为 Tabs 组件的 renderTabBar 返回 一个有 wapper 的 DefaultTabBar

### What is expected?
使 TabBar 重写后其原生的样式不变

### What is actually happening?
TabBar 重写后变成了水平排列

---
查看了 antd 样式后发现，antd 中对于 vertical 方向的 TabBar 的样式定义是这样的：

```
.ant-tabs-vertical.ant-tabs-left>.ant-tabs-bar {
    float: left;
    border-right: 1px solid #e8e8e8;
    margin-right: -1px;
    margin-bottom: 0;
}
```

这样，一旦 DefaultTabBar 的外面包裹了一层 div ，就会使该样式失效

**Comment by xiongchen2012** [comment]
不用div包，使用<React.Fragment>DefaultTabBar </React.Fragment>来包呢？

**Comment by Madridspark** [comment]
这样的话使用场景就受限了，Fragment 不能渲染为任何 DOM 元素，也就不能加样式了
