### ISSUE TITLE
Button 增加 danger type

### ISSUE THREAD

**Issue by mongris** [ant-design/ant-design#1308]
除了目前支持的 types 外，往往在 UI 上还需要区分出比较危险的按钮，比如 “删除”

<img width="104" alt="5e061768-669a-4059-8d3d-88bcc6f1ad61" src="https://cloud.githubusercontent.com/assets/259816/14167564/9adcf4c8-f778-11e5-88a9-c331df4e5037.png">

在我们的项目中，我复制了 antd styles，对 button 的样式做了这方面的扩展（增加了 danger, success 类型）。但是在最新的 antd 中，type prop 做了限定。虽然运行不会有什么问题，但还是会输出大量的 warning。

不知道对这个建议是否会采纳，如果需要的话，可以 PR。

**Comment by afc163** [comment]
type 目前是按照 Ant Design 的设计规范来配置的，应该不会支持 danger success 这些按钮。

我这里去掉 type 的限制提示，方便上层业务扩展。

**Comment by afc163** [comment]
已经提交设计师讨论。

**Comment by afc163** [comment]
@mongris 2.6 里已新增。

**Comment by mongris** [comment]
Thank you!
