### ISSUE TITLE
打包之后的体积，重复打包的疑问

### ISSUE THREAD

**Issue by wang777777** [ant-design/ant-design#13083]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
打包之后，webpack-bundle-analyzer可视化看到rc-select下面有一个rc-menu，另外也有一个单独的rc-menu，这两个都是一样的，打包了两份，已经使用了babel-plugin-import，有什么解决方法可以只打包一份

### What does the proposed API look like?
只打包一份

**Comment by afc163** [comment]
It seems to be a bug rather than a feature request, please use feature-request template in http://new-issue.ant.design/ to create another issue.
