### ISSUE TITLE
[Tabs component] refresh data will trigger an error when "tabPosition" value is the "left" or "right"

### ISSUE THREAD

**Issue by hileix** [ant-design/ant-design#13087]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
os version: macOS High Sierra, browser version: Chrome 70.0.3538.77（正式版本）（64 位）,react version: 16.6.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/30k9xy08y1)

#### error occurred
`TypeError`:
`Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

**Comment by ztplz** [comment]
This isn't a bug. You shouldn't set tabsData to empty.

**Comment by hileix** [comment]
@ztplz 
Refresh data will not trigger an error when "tabPosition" value is the "top" or "bottom".
Only "tabPosition" value is the "left" or "right" will results in an error.

**Comment by ztplz** [comment]
@hileix Because if they are set with different `positions`, they will trigger different functions.

**Comment by hileix** [comment]
@ztplz 
For the first time Tabs component rendering, tabsData is an empty array, and not trigger an error at that time.
And I think set tabsData to an empty array should not lead to errors. Besides, refresh data will not trigger an error when "tabPosition" value is the "top" or "bottom".

**Comment by zombieJ** [comment]
Seems fixed in `3.10.8`: https://codesandbox.io/s/j3vqp6w8rw
