### ISSUE TITLE
 Not to return a array for field after table changed, when the `filterMultiple` of  `Column` is set to `true`,

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#13090]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We need to aggregate the changes to the field in the Table and then stitch them into the query language required by the server.

most  time:
field value is array. =>  `${fieldKey}_in: [1,2,3]`
field value is  not array => `${fieldKey}_eq:  ${value}`

`eq` and `in` is a special 'operation'. There are many other special operators

`${fieldKey}__not_eq:  ${value}`

it is always  return an array, even filterMultiple is set to false.
so that i need to transform value array => array[0]

### What does the proposed API look like?
onChange(pagination, filters: {
field: `Array||value`,
}, sorter, extra: { currentDataSource: [] })

**Comment by yutingzhao1991** [comment]
In my opinion, return a array is more universal. Maybe it is expected in other projects.

**Comment by zombieJ** [comment]
This is not common usage which should not be handled by the Table component. You can wrap the Table component to handle `onChange` and `columns` by yourself.

**Comment by xyy94813** [comment]
@zombieJ 
It looks strange when the value of filter is a boolean type. `filter.enabled = [true]`.
And filter value is boolean is common.
