### ISSUE TITLE
当RangePicker中的value 与组件state绑定时，会引起切换月份按钮失效

### ISSUE THREAD

**Issue by xiaozhu123123123** [ant-design/ant-design#13093]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
3.10.7

### Reproduction link
[https://github.com/while-it/antd-3.7.1-issue](https://github.com/while-it/antd-3.7.1-issue)

### Steps to reproduce
将value绑定给rangepick就会触发这个bug

### What is expected?
应该正常能够选择月份切换月份功能

### What is actually happening?
不能选择月份切换月份

**Comment by hileix** [comment]
建议升级到 3.10.7（目前最新版本），在这个版本中是没有问题的。

**Comment by zombieJ** [comment]
删除一下 node_modules 重装一下，新版看起来没问题：https://codesandbox.io/s/z2kow2vvkx
