### ISSUE TITLE
🎄 Christmas easter egg 🎄

### ISSUE THREAD

**Issue by davidebianchi** [ant-design/ant-design#13098]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Christmas easter egg is a really fun joke, but in business app we should give the possibilities to switch off that. This feature could block users from using this awesome library

### What does the proposed API look like?
My proposal is a prop (also true by default) and when switched to false it block the easter egg.

**Comment by llhupp** [comment]
This _might_ be ok for such a widely used application if it was at least opt-in... I cannot use this library with this applied, and it is tricks that I had to scour source code to find it...

**Comment by caitecoll** [comment]
Are there any other Easter eggs like this within Ant? I want to be sure I'm overriding them in my application.

**Comment by schnerd** [comment]
I was really hoping to use Ant for an upcoming project but I really can't justify that decision when the library authors think it's okay to sneak in things like this for all their customers. I imagine some poor developers are going to have their Christmas day interrupted when they get an angry email from their managers asking to remove the snow from all the buttons.

**Comment by afc163** [comment]
The potential ConfigProvider API would be like below and default value `snowyButton` will be `false`. 

```jsx
<ConfigProvider snowyButton={true}>
  ...
</ConfigProvider>
```

**Comment by Jasper0819X** [comment]
Easter egg should be disabled by default in production mode.

**Comment by ybning** [comment]
怎么去掉
```
title="Ho Ho Ho!"
```
?
@zombieJ

**Comment by theMxb** [comment]
怎么去除

**Comment by georgehpj** [comment]
我们是做2B应用的，这种“彩蛋”让人有失控的感觉。翻了下过去的release里也没有提到过这个彩蛋，看起来是故意为之。但用户如果有意见，我们就被动了。加彩蛋可以，但最好控制权还是在开发者手里，默认关闭，由开发者决定是否开启。开发者给最终使用者的惊喜叫“彩蛋”，框架给开发者的惊喜就是惊吓了……

**Comment by onfuns** [comment]
So foolish！！！

**Comment by chaegumi** [comment]
💔

**Comment by hengkx** [comment]
吓我一跳，没有 任何 说明 突然 来这么一下

**Comment by weig** [comment]
This is ridiculous! We are running serious business using Ant.Design.

If Ant.Design is designed as "library", how and when to present an Easter egg should be controlled by the application developer, not the library.

Christmas is a happy day, but not for every business.

**Comment by TnWah** [comment]
吓死宝宝了！

**Comment by Airkro** [comment]
所谓“彩蛋”就是不会事先通知的。

我觉得雪花如果使用能够使用更高融合度的设计，也许更多人能一笑置之，毕竟没有什么不良影响。或许还能获得好评，毕竟skin这个概念是有的。可惜现在扁平的界面里那块3D雪。。。
但是改写 title 完全没必要，仿佛像是恶作剧了。

**Comment by 15920007247** [comment]
可以让开发者配置就好了， title 完全没必要

**Comment by zy410419243** [comment]
~没有女朋友，一觉醒来还要被喷，我已经隔着屏幕体会到那种弱小又无助的感觉了~

实际上发个新版本出来就好了...

**Comment by Lpbzzz** [comment]
希望每个前端都不要被产品经理diss...

**Comment by xinx1n** [comment]
这次在代码里掺屎，下次就不定搞什么了

**Comment by zoeblow** [comment]
本来今天高高兴兴的， 没想到还没到公司就被喷，整个群都炸了，说中病毒了。感觉要被杀了祭天。。

**Comment by TsangTszKin** [comment]
Please solve the problem as soon as possible。
anyway 控制权应该在我们开发者手里，应该是可配置！而不是完全覆盖！right？

**Comment by TsangTszKin** [comment]
> 本来今天高高兴兴的， 没想到还没到公司就被喷，整个群都炸了，说中病毒了。感觉要被杀了祭天。。

请做好防御措施

**Comment by zjhzxmx** [comment]
> 本来今天高高兴兴的， 没想到还没到公司就被喷，整个群都炸了，说中病毒了。感觉要被杀了祭天。。

God Bless you

**Comment by TnWah** [comment]
> 本来今天高高兴兴的， 没想到还没到公司就被喷，整个群都炸了，说中病毒了。感觉要被杀了祭天。。

稳住，老铁

**Comment by kabike** [comment]
WTF

**Comment by TsangTszKin** [comment]
> 这次在代码里掺屎，下次就不定搞什么了
666

**Comment by pureZjr** [comment]
心机Boy

**Comment by znanjie** [comment]
因为这个christmas彩蛋一大早就被测试提了过来...真的服了

**Comment by flyhuang** [comment]
哈哈, 惊喜大于惊讶..特地找了一圈..不过还是改成可配置的, 会比较好.

**Comment by redclown** [comment]
> 本来今天高高兴兴的， 没想到还没到公司就被喷，整个群都炸了，说中病毒了。感觉要被杀了祭天。。

surprised! good luck~

**Comment by githubwing** [comment]
Ho Ho Ho

**Comment by fengdi** [comment]
还好没点击按钮跳出个徐锦江

**Comment by jackple** [comment]
只能把锅甩给产品了

**Comment by ducbuianh** [comment]
I don't need `christmas` in my business apps. So unprofessional for a widely used library x(

**Comment by TsangTszKin** [comment]
Don't worry too much. The antd team will work it out.  否则，大家等着被祭天

**Comment by rmlzy** [comment]
为什么不先通知开发者??????

**Comment by AuthorJim** [comment]
你已经是个成熟的框架，不用别人教你不该做什么。。。

**Comment by stanye** [comment]
是时候杀一个开发者祭天了。
Time to kill a developer  to Celebrate Christmas.

**Comment by Grewer** [comment]
群里还说 这是冰雪节限定皮肤  然而这并不好, 希望有全局配置能够对其进行删改

**Comment by itellboy** [comment]
国内的开发现状暂时还接受不了这种类型的彩蛋，antd 还是准备公关吧

**Comment by redclown** [comment]
开源的项目，个人觉得应该多高一些这种彩蛋，如果有个彩蛋列表就更好了~

**Comment by Aaron-China** [comment]
Is it April Fool's Day today?

**Comment by RanQiwu** [comment]
哈哈！好玩。

**Comment by KenLiuHantao** [comment]
官方开玩笑吧，不通知就强行开始彩蛋了？我要重新评估是否需要把ANTD从项目中移除，因为它开始失控了！

**Comment by MokerT** [comment]
> 国内的开发现状暂时还接受不了这种类型的彩蛋，antd 还是准备公关吧
别说国内，国外也一样。。。

**Comment by WDJ-XUMA** [comment]
感觉互联网产品开发大战要开始了

**Comment by zemzheng** [comment]
看业务产品的包容程度吧。如果是比较成熟而严肃的业务不应该出现这种变化的。
In some profession place it should not be enabled this by default.

**Comment by ZhouYK** [comment]
这波操作太随意了，会产生对antd团队专业性的质疑

**Comment by hongwanzhang** [comment]
还有没有其它彩蛋了，我好都去都关了，太可怕了，会被骂的

**Comment by kabike** [comment]
怎么给项目差评啊？有人会么

**Comment by dcy0701** [comment]
不敢用了，下次愚人节把UI都可能给我搞崩了，shit

**Comment by bleedkaga** [comment]
> 怎么给项目差评啊？有人会么

弃用之！

**Comment by itellboy** [comment]
> 感觉互联网产品开发大战要开始了

里程碑啊，这次圣诞事件

**Comment by minteliuwm** [comment]
吃瓜群众默默的看着。。

**Comment by dovakinlink** [comment]
> 本来今天高高兴兴的， 没想到还没到公司就被喷，整个群都炸了，说中病毒了。感觉要被杀了祭天。。

保重

**Comment by toksea** [comment]
踩蛋

**Comment by XuChunxiao** [comment]
这个彩蛋不太适合我们公司的业务产品，太随意了，之前的文档里也从来没见到彩蛋说明

**Comment by SiriusQin** [comment]
大清早的，要被祭天了

**Comment by wangchun0020** [comment]
foolish!!!

**Comment by jiaoyanfei** [comment]
我们是单独部署给工厂的项目，工厂要求单独部署都是为了自己的数据安全考虑，这样搞人家就会有一种不安全感，而且难道要我们一家一家给解释？，覆盖代码后都重新给部署一遍吗 。。。

**Comment by sxi3265** [comment]
两个项目 一个项目老版本，一个项目新版本，以为开发人员造了个隐藏bug

**Comment by vickychu** [comment]
Just ridiculous! It's a terrible experience to have such an easter egg for poor developers!

**Comment by volash86** [comment]
对那些是背景是白色的页面，，这些button如同被咬了一口。

**Comment by didmehh** [comment]
自认为antd是国内为数不多的靠谱的开源库，这样就太让人大跌眼镜了。

**Comment by dovakinlink** [comment]
这次彩蛋让我扯着蛋了

**Comment by heshengbang** [comment]
you people don't know how to solve this problem, so this issue became a gitter ? come on guys, do a feature hot fix, solve it.

**Comment by smk0621** [comment]
欢迎大家使用 https://github.com/sheinsight/shineout，向大家承诺不会添加任何不通知用户的彩蛋

**Comment by SolidZORO** [comment]
hhhh，为此我向客户解释了一番。

**Comment by rmlzy** [comment]
@smk0621 链接后加个空格

**Comment by supernovayo** [comment]
一大波bug单已经在路上了，这波操作让我对Ant Design非常失望，他已经变得不再可靠了。

**Comment by SiriusQin** [comment]
完蛋啊，要被祭天了，好几个已经online的项目。

**Comment by jonjamz** [comment]
I have to update my app on Christmas Eve to remove this. I get the humor, but my platform goes through a design approval process with each client and this was not approved. Now I'm rolling out updates to a bunch of single tenant apps when I should be getting drunk with my family. Thanks!

**Comment by lanbomo** [comment]
太失望了，对Ant Design好感顿时降低一个数量级。

**Comment by lidianhao123** [comment]
国内开发，不太能接受

**Comment by bestRenekton** [comment]
感觉过了点啊，console里面玩玩就可以了嘛。。太突然了

**Comment by wucipo** [comment]
完全失控，彩蛋变踩蛋！请ANTD快速移除吧

**Comment by billyct** [comment]
这一波，老板觉得 ok，马上升职加薪了。

**Comment by redclown** [comment]
> 太失望了，对Ant Design好感顿时降低一个数量级。

个人对ant好感提升了~

**Comment by bleedkaga** [comment]
antd 要作死！

**Comment by itellboy** [comment]
antd 产品祭天吧

**Comment by uhr** [comment]
以后的框架可以这么介绍自己：“永远不会直接给用户加特效”。

**Comment by superlbr** [comment]
至少在更新日志里提一下

**Comment by huxiaonb** [comment]
哈哈哈  测试还没来得及发现

**Comment by yeyongyong** [comment]
太坑了， 被老板骂了

**Comment by exzhicall** [comment]
产品觉得不错，期待下一次的彩蛋，哈哈

**Comment by redclown** [comment]
> 产品觉得不错，期待下一次的彩蛋，哈哈

同期待下一波彩蛋

**Comment by xyxuyao** [comment]
这么多人使用的库，不能这么玩啊，还有没有其它的，请告知，需要去掉

**Comment by 133922249** [comment]
我家测试也没发现, 朋友的政F项目已被骂惨

**Comment by yeyongyong** [comment]
如何去掉啊

**Comment by awakenin** [comment]
要有一个配置才行的，不能这么玩

**Comment by Ericfish007** [comment]
新年彩蛋可以开始准备了！！！

**Comment by fwh1990** [comment]
建议放到console。因为这本来就是框架和开发者之间的互动。做前端的，console控制台是必须开的。实在要体现在组件上，那么我觉得应该在production模式下是禁用的。毕竟开发者90%的时间是在开发环境。

**Comment by dcy0701** [comment]
> 产品觉得不错，期待下一次的彩蛋，哈哈

下次愚人节把页面给你搞崩了开心吗？

**Comment by wangchun0020** [comment]
刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么

**Comment by QSQ1989** [comment]
小玩一下还是可以滴，哈哈~~

**Comment by plainnany** [comment]
这个要事先通知开发者的吧，或者由开发者来控制。

**Comment by yi-ge** [comment]
这么玩😂，真怕其它框架效仿。。。😂

**Comment by RanQiwu** [comment]
> 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么

在风口上被捅了一刀。

**Comment by wangkai123456** [comment]
> 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么

真的假的

**Comment by duanbowen** [comment]
> 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么

真的假的？

**Comment by barrypeng6** [comment]
列入黑名單

**Comment by yi-ge** [comment]
> 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么

当真？

**Comment by Kris-Lee-SH** [comment]
真心不敢用，这次是圣诞，下次可能就是春节，想象下 早上不是被鞭炮炸醒的，而是被 boss 夺命连环 call 醒的。。。。。。。

**Comment by demonoidaemon** [comment]
太傻了这彩蛋

**Comment by sxyandapp** [comment]
毛线的彩蛋，我还以为是公司svn服务器被人黑了，后来才发现仅仅是所有用了antd的项目才这样，THIS IS NOT FUNNY !!!!

**Comment by kabike** [comment]
> 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么

啊？

**Comment by Geocld** [comment]
通过植入垃圾代码实现这类愚蠢的彩蛋，这种设计就是一种bug。

**Comment by aited** [comment]
身为国人应抵制国外节日，自带这么高流量的企业应该更要带好头弘扬中国的传统文化，
我实在无法忍受一个鸟圣诞，有什么好宣传节日氛围的，还说什么彩蛋，我认为这个是臭蛋。
有些电视剧主角们配件也是人手一台苹果电脑，手机。我们国人什么时候才能雄起，什么时候才能不崇洋媚外啊，哀哉！！！

**Comment by william-yz** [comment]
我也以为系统被黑了

**Comment by chen86860** [comment]
> 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么

心疼

**Comment by yeyongyong** [comment]
![image](https://user-images.githubusercontent.com/14305099/50409169-7b7e4700-082b-11e9-8d1f-8dc62e161026.png)

**Comment by buf1024** [comment]
刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么
-------------------
今天也公司也爆出这个问题了，客户投诉量巨增，老板把前端开了，说是造成公司重大损失，一分钱也不赔。

**Comment by Aaron-China** [comment]
哎! 骂归骂，骂完了接着用，难道还能把架构重新写一遍？还是有更好的react-UI框架推荐？

**Comment by zy410419243** [comment]
> 身为国人应抵制国外节日，自带这么高流量的企业应该更要带好头弘扬中国的传统文化，
> 我实在无法忍受一个鸟圣诞，有什么好宣传节日氛围的，还说什么彩蛋，我认为这个是臭蛋。
> 有些电视剧主角们配件也是人手一台苹果电脑，手机。我们国人什么时候才能雄起，什么时候才能不崇洋媚外啊，哀哉！！！

老哥转进如风啊

**Comment by sxyandapp** [comment]
> > 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么
> 
> 心疼

好皮

**Comment by theMxb** [comment]
以为是病毒，想不到竟然是....

**Comment by ybning** [comment]
> 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么

Really？

**Comment by qq645381995** [comment]
以前公司数据库被sql注入过，每个表每个字段都插入一段 img 标签，然后网页能显示的地方都显示出来图片。

**Comment by Blackgan3** [comment]
赶紧取消掉吧，我们这边的业务没法这样搞啊，真要紧急发布？？？？？？？？？

**Comment by cesar-blog** [comment]
看到大家都在喷，我就放心了。另外杭州海创园招前端高级开发！

**Comment by dovakinlink** [comment]
老板问我按钮为什么被狗啃了

**Comment by Jeffy2012** [comment]
什么玩意呀

**Comment by jeffhtli** [comment]
如此**专业的开源项目**发生这么**不专业的事情**，痛心！

**Comment by phodal** [comment]
怕是下次就注入漏洞了。

**Comment by yeyongyong** [comment]
判断写死在代码内的。。。。

**Comment by fanyingmao** [comment]
> ## 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么
> 今天也公司也爆出这个问题了，客户投诉量巨增，老板把前端开了，说是造成公司重大损失，一分钱也不赔。

真的？裁员的好借口。

**Comment by itellboy** [comment]
这个事情开始发酵了

**Comment by crper** [comment]
> 哎! 骂归骂，骂完了接着用，难道还能把架构重新写一遍？还是有更好的react-UI框架推荐？

会流失潜在的开发用户, 估计下次大整改.部分人就会把antd 剔除在考虑的范围内...

还有一些业务不复杂的公司..说替换那替换起来也很快的

**Comment by xinyu198736** [comment]
客户会觉得你可以操控他们私有的项目，这是一个很可怕的事情，谁来担责

**Comment by zhichao8756** [comment]
> > 刚到公司，就让我收拾东西办理离职手续，好了，本来就在裁人，现在都不用找借口了。问下这个情况可以申请仲裁么
> 
> 啊？

应该不至于吧

**Comment by Ba5sx1a0sen1** [comment]
这是一个可以一天后自愈的bug（手动滑稽）

**Comment by yi-ge** [comment]
这太不严谨了。。

**Comment by zhiyan** [comment]
整个小红帽就够了，结果一大片跟啃的一样，背景还是白的，一点都不像彩蛋，像bug

**Comment by FaFamylove** [comment]
就我想知道title该怎么去掉咩

**Comment by crper** [comment]
> 这是一个可以一天后自愈的bug（手动滑稽）

看面向的用户群吧..若是有政F合作这些的..很容易给叼..因为出现了不可控因素..

**Comment by jiangqizheng** [comment]
出售花生瓜子。
Sell peanuts and melon seeds。

**Comment by duanbowen** [comment]
我想知道明天会好吗？

**Comment by Justinidlerz** [comment]
一大早头上莫名多了一个BUG。。。

**Comment by Dante-dan** [comment]
我觉得这个挺好啊。。。很有意思啊，不管是给谁，都有一种节日氛围的感觉

**Comment by superfur** [comment]
antd这波劝退堪比当年的脸书劝退

**Comment by theshying** [comment]
愚蠢的人类

**Comment by dzeze** [comment]
莫名其妙的被批了

**Comment by bleedkaga** [comment]
> 出售花生瓜子。
> Sell peanuts and melon seeds。

同售啤酒香烟

**Comment by zhichao8756** [comment]
> 整个小红帽就够了，结果一大片跟啃的一样，背景还是白的，一点都不像彩蛋，像bug

我也以为组件出bug了,来这儿一看,嚯,原来是个彩蛋.....

**Comment by Dante-dan** [comment]
就是有点丑！这个白雪花，还不如一个圣诞帽子

**Comment by FaFamylove** [comment]
> 我觉得这个挺好啊。。。很有意思啊，不管是给谁，都有一种节日氛围的感觉

政府部门不看这个

**Comment by sxyandapp** [comment]
> 我觉得这个挺好啊。。。很有意思啊，不管是给谁，都有一种节日氛围的感觉

关键那个效果不忍直视，像狗啃的

**Comment by yi-ge** [comment]
花生瓜子方便面，啤酒饮料矿泉水~

**Comment by littlelake** [comment]
没有一点点防备

**Comment by duanbowen** [comment]
zf 不过圣诞节

**Comment by Dante-dan** [comment]
> > 我觉得这个挺好啊。。。很有意思啊，不管是给谁，都有一种节日氛围的感觉
> 
> 关键那个效果不忍直视，像狗啃的

那倒是，挺丑的！

**Comment by Justinidlerz** [comment]
![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
还有。。你们的官网首页Christmas好像拼错了吧。。

**Comment by zhichao8756** [comment]
前排出售小板凳~

**Comment by WWR1234567** [comment]
这个代码也是写死的每年11月25，amazing

**Comment by onfuns** [comment]
lower than version 3.9.2 can solve the problem

**Comment by crper** [comment]
> ![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
> 还有。。你们的官网首页Christmas好像拼错了吧。。

为何你这么皮...

**Comment by wuzhipei** [comment]
https://www.zhihu.com/question/306858501

**Comment by duanbowen** [comment]
> > ![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
> > 还有。。你们的官网首页Christmas好像拼错了吧。。
> 
> 为何你这么皮...

~~~·

**Comment by itellboy** [comment]
> ![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
> 还有。。你们的官网首页Christmas好像拼错了吧。。

老哥，还是你稳啊

**Comment by ghrace** [comment]
> 这个代码也是写死的每年11月25，amazing

12月

**Comment by plainnany** [comment]
> ![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
> 还有。。你们的官网首页Christmas好像拼错了吧。。

哈哈还真是，这个眼神无敌了

**Comment by zhxsh** [comment]
觉得挺可爱的啊

**Comment by Dante-dan** [comment]
> ![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
> 还有。。你们的官网首页Christmas好像拼错了吧。。

你是魔鬼嘛

**Comment by weechang** [comment]
吃瓜，，，哈哈

**Comment by bao-han** [comment]
前排围观

**Comment by Airkro** [comment]
大家可以直接回滚到 3.9.2 之前。。。
另外没有建设型的聊天真的应该停止，让全球跟着看笑话没必要，还暴露自己的水准。

@afc163
`<ConfigProvider snowyButton={true}>` 我认为没必要实现，毕竟不到14个小时节日就过了。没必要占用代码量和流量。

**Comment by WWR1234567** [comment]
坐等好戏

**Comment by vipbo** [comment]
不敢想象4.1日会出现什么！

**Comment by WadeZhu** [comment]
春节会不会来串鞭炮

**Comment by MokerT** [comment]
> ![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
> 还有。。你们的官网首页Christmas好像拼错了吧。。

滑天下之大稽

**Comment by zibuyu69** [comment]
我还觉得挺可爱····竟然大多数人不喜欢 ·。·看来这种规模的库还是要首先考虑用户的下限，然后再锦上添花

**Comment by timothynode** [comment]
来瞧一瞧看一看了~~~欢迎各位有前端技术热情的同学加入我们。特别地，我们不会因为一个彩蛋就杀了程序员祭天。。。base 广州，上市公司。广招前端后台~~~有兴趣邮件一下简历谢谢~~~

**Comment by freedom520** [comment]
> 看到大家都在喷，我就放心了。另外杭州海创园招前端高级开发！

这波招聘厉害了

**Comment by vipbo** [comment]
不敢想象4.1日会出现什么！

**Comment by pangjunpeng** [comment]
> ![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
> 还有。。你们的官网首页Christmas好像拼错了吧。。

把我的九层妖塔拿出来，我要给秀儿蒸笼包子

**Comment by Alice-gxh** [comment]
Merry Christmas！
圣诞快乐(*^▽^*)
我来写个正确的吧！^_^

**Comment by Dante-dan** [comment]
> 来瞧一瞧看一看了~~~欢迎各位有前端技术热情的同学加入我们。特别地，我们不会因为一个彩蛋就杀了程序员祭天。。。base 广州，上市公司。广招前端后台~~~有兴趣邮件一下简历谢谢~~~

优秀啊

**Comment by narco001** [comment]
大版本4.x.x升级不会给我们一个很大很大的惊喜吧！！！！！？？？？？

**Comment by yuu2lee4** [comment]
这种彩蛋到底是要给客户带来"惊喜"，还是给开发者带来惊吓？

**Comment by KaierChou** [comment]
![img](https://i.ibb.co/RNJdBY5/001.gif)

**Comment by Dante-dan** [comment]
弄个投票，我投赞成票！

**Comment by annyHu** [comment]
坐等吃瓜

**Comment by jiafulu** [comment]
> ![image](https://user-images.githubusercontent.com/7475347/50409247-3dcdee00-082c-11e9-8ae0-95b0ada33bfd.png)
> 还有。。你们的官网首页Christmas好像拼错了吧。。

哈哈哈哈哈哈哈

**Comment by kalsolio** [comment]
真是没一点责任心 不考虑用户使用场景

**Comment by luliangce** [comment]
伊斯兰国家过圣诞节吗?打开一看十字军占领自己家网站了?前端被砍死有人负责吗?

**Comment by tao1991123** [comment]
侵犯我们无神论者的信仰自由

**Comment by stbui** [comment]
这代码怎么加上去的？

**Comment by lu-lu-wang** [comment]
这波操作很溜，还好我们线上版本没更新，尴尬😓

**Comment by RoJoHub** [comment]
What about the Spring Festival? Nothing in the Spring Festival?
Ant???
Only Christmas?

------

春节呢?春节没有嘛???
Ant???
只有圣诞?

**Comment by zy410419243** [comment]
issue 是用来提问题跟解决问题，而不是用来炒热点的，讨论到这份上只能锁了
