### ISSUE TITLE
Cascader filter freezing

### ISSUE THREAD

**Issue by gorilla-devs** [ant-design/ant-design#13097]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
browser version

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wo961470l5)

### Steps to reproduce
1. Open codesandbox
2. Open the cascader
3. Search for "World60"
4. Wait until the freeze ends

### What is expected?
The freeze should not happen, maybe use some debounce with a delay between the for cycles.
If the loading is too long, having a loading icon on the right would be awesome so the users knows it's doing something.

### What is actually happening?
The entire window just freezes and the user cannot click or interact with anything on the page until it's done filtering.

**Comment by zy410419243** [comment]
It works well on Window 10, Chrome 70.0.3538.102.

**Comment by gorilla-devs** [comment]
Aren't you experiencing any freeze while searching?  I have your same exact setup and it's almost unusable with that dataset. Notice that the cascader works fine, the problem is with the search

**Comment by zombieJ** [comment]
Seems too many filtered items in dropdown. Maybe we should add `limit` prop in `showSearch`:
```jsx
<Cascader
  options={this.data}
  showSearch={{ filter: this.filter, limit: 30 }}
/>
```

**Comment by afc163** [comment]
I think we can make limit 30~50 defaultly.
