### ISSUE TITLE
Event onSearch of Input.Search component never fire on React 16.6.1

### ISSUE THREAD

**Issue by ejoc** [ant-design/ant-design#13101]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
browser

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/woqzxkxymw)

### Steps to reproduce
<Input.Search onSearch={value => alert(value)} />

### What is expected?
onSearch event will be triggered

### What is actually happening?
onSearch event doens't work

**Comment by ztplz** [comment]
@ejoc  Can't reproduced it. 
![d7b83467-4277-4ba2-b9bc-0bffb15e131c](https://user-images.githubusercontent.com/17755202/48378954-79de4100-e70d-11e8-9dd4-b33011953937.png)
