### ISSUE TITLE
Table翻到第二页后，调用setState会导致Table自动刷新（回到第一页）

### ISSUE THREAD

**Issue by JiaHui-STU** [ant-design/ant-design#1311]
## What you did

首先将Table翻到第二页，然后点击Table里的一个"入库"按钮（每一行都有）
``<i title="入库" data-key={key} onClick={this.handleAdd} className="fa fa-truck" style={{color:"#2db7f5"}}></i>``

`this.handleAdd(){ this.setState({ isVisible:true }) } //用来控制一个弹窗的display:none or inline-block`

## What you would like to happen

弹窗出现，但page应保持在第二页

## What actually happened

弹窗出现了，但是page跳回了第一页

## Environment Information

- The version of antd(e.g. 0.12.12):
- WIN7
- Chrome 49.0.2623.87 

## Else

类似的问题还出现在修改每一行的input:number时

## DEMO
http://codepen.io/guangjun/pen/LNjvaa?editors=0100

**Comment by afc163** [comment]
codepen demo

**Comment by JiaHui-STU** [comment]
http://codepen.io/guangjun/pen/LNjvaa?editors=0100

**Comment by afc163** [comment]
http://codepen.io/anon/pen/BKdgjV?editors=0010

你把 this.pagination.current 写死了，这个是受控属性。可以用 defaultCurrent。

**Comment by afc163** [comment]
实际上，如果设置了 `pagination.current`，表格分页应该无法手动切换，必须配合 `pagination.onChange` 进行同步设置。详细可见：http://facebook.github.io/react/docs/forms.html#controlled-components

我这里修复了可以手动切换的问题，并且修正了 demo 中设置的 `pagination.current`。这个 demo 应该给楼主造成误解了，十分抱歉。
