### ISSUE TITLE
cascader placeholder text not localized

### ISSUE THREAD

**Issue by waywardmonkeys** [ant-design/ant-design#1312]
On the current ``develop-1.0.0`` branch, the ``placeholder`` text for ``components/cascader/index.jsx`` is not localized.

It defaults to Chinese text and every location that instantiates one must provide text in the desired language:

```javascript
export default class Cascader extends React.Component {
  static defaultProps = {
    prefixCls: 'ant-cascader',
    placeholder: '请选择',
```

**Comment by afc163** [comment]
Just remove the Chinese default value, make it simple.
