### ISSUE TITLE
自定义icon，无法修改color属性

### ISSUE THREAD

**Issue by tdida** [ant-design/ant-design#13137]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
Mac os 10.14.2 Beta、chrome 72

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/nl2nxjv80)

### Steps to reproduce
https://codesandbox.io/embed/nl2nxjv80

### What is expected?
自定义icon可以修改颜色

### What is actually happening?
自定义icon不可修改颜色

**Comment by afc163** [comment]
https://codesandbox.io/s/lr3375xj69

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/507615/48475771-78f5fe00-e838-11e8-98d5-02b68faf9583.png">

你的 iconfont 的 svg 已经自带了颜色，这种是无法覆盖的。

**Comment by tdida** [comment]
好的，在iconfont去色就可以

**Comment by afc163** [comment]
https://github.com/thx/iconfont-plus/issues/350#issuecomment-278269496

**Comment by k983551019** [comment]
> [thx / iconfont-plus＃350（评论）](https://github.com/thx/iconfont-plus/issues/350#issuecomment-278269496)

 <Icon component={DeleteSvg} style={{ color: '#0667ca' }} /> 取出了DeleteSvg的颜色， 再使用style并不能改变它的颜色

**Comment by JounQin** [comment]
@afc163 IconFont 自定义图标目前生成的 color 属性在 span 上，这个 svg 无法识别到，workaround 如 @k983551019 所说使用 style 是可以的

![image](https://user-images.githubusercontent.com/8336744/131329484-35721f00-e217-4c46-8320-992b51e20672.png)

**Comment by JounQin** [comment]
See https://github.com/ant-design/ant-design-icons/pull/498
