### ISSUE TITLE
Add category in Menu component

### ISSUE THREAD

**Issue by LeeGeonho** [ant-design/ant-design#13136]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Too much menu items are very confusing.
It would be easier if we could divide it into categories.

As shown in the screenshot below
![flatkit app ui kit preview - themeforest 2018-11-14 18-28-33](https://user-images.githubusercontent.com/9799339/48473165-4699d000-e83b-11e8-9fc5-3cec3465054b.png)

### What does the proposed API look like?
``` javascript
<Menu>
// add Category 1
<Menu.Category key="1"><span>Category 1</span></Menu.Category>
<Menu.Item key="1"><span>Menu 1</span></Menu.Item>
<Menu.Item key="2"><span>Menu 2</span></Menu.Item>
<Menu.Item key="3"><span>Menu 3</span></Menu.Item>

// add Category 2
<Menu.Category key="2"><span>Category 2</span></Menu.Category>
<Menu.Item key="1"><span>Menu 1</span></Menu.Item>
<Menu.Item key="2"><span>Menu 2</span></Menu.Item>
</Menu>
```

**Comment by zy410419243** [comment]
What about [this](https://codesandbox.io/s/llo4xyk847)
