### ISSUE TITLE
Tree组件checkStrictly为true时，选中子节点的时候如何获取父节点的key值

### ISSUE THREAD

**Issue by keduoli** [ant-design/ant-design#13139]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户体验

### What does the proposed API look like?
无

**Comment by 13417094465** [comment]
[https://blog.csdn.net/weixin_47183748/article/details/133173575?spm=1001.2014.3001.5502](https://github.com/ant-design/ant-design/issues/url)
