### ISSUE TITLE
Tabs Pane ink bar doesn't properly calculates width and position

### ISSUE THREAD

**Issue by arherzf8er** [ant-design/ant-design#13144]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.3

### Environment
Ubuntu 18.04 or Windows 10, React@latest, Chrome@latest, Mozilla@latest

### Reproduction link
[https://ant.design/components/tabs/](https://ant.design/components/tabs/)

### Steps to reproduce
Standard install of type `line` with 3 or more long tabs names

### What is expected?
Properly positioned underline bar of actual width

### What is actually happening?
Underline bar isn't positioned right under the tab names
![peek 2018-11-14 21-23](https://user-images.githubusercontent.com/29209372/48496906-dbf58e00-e854-11e8-9284-1c0b7cf46836.gif)

**Comment by arherzf8er** [comment]
Hi, @ilanus thanks for your quick reply! Turned out it's on my side and behaves as such globally on any of my pages. Any thoughts on where point should I start debugging from? Seems like it gets some wrong inputs for calculating transition values for `.ant-tabs-ink-bar-animated` CSS property. Thanks!

**Comment by ilanus** [comment]
@arherzf8er without reproduction of your issue I cannot help, please try to replicate it using a sandbox: https://u.ant.design/codesandbox-repro

**Comment by arherzf8er** [comment]
The issue has been solved by updating from 3.9.3 to 3.10.8.

**Comment by vectorx5** [comment]
This issue has returned in v5. Please check.

**Comment by mrlubos** [comment]
Hey @ilanus, here's a reproduction link with `v5.0.7` https://codesandbox.io/s/antd-reproduction-template-forked-zoj0go?file=/index.js

**Comment by mrlubos** [comment]
Opened a new issue for `5.0.7` in https://github.com/ant-design/ant-design/issues/39666
