### ISSUE TITLE
RadioGroup.RadioButton组件遍历出错

### ISSUE THREAD

**Issue by heyizhiyuan** [ant-design/ant-design#13149]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
Google Chrome，edge 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://9ylnoqn04r.codesandbox.io/)

### Steps to reproduce
将RadioButton。RadioButton 换成 Select .Option 组件 程序正常运行

### What is expected?
动态加载出RadioButton组件

### What is actually happening?
报错

**Comment by ztplz** [comment]
@heyizhiyuan  `RadioButton` => `Radio.Button`
![image](https://user-images.githubusercontent.com/17755202/48524135-0ded0b80-e8ba-11e8-9ba1-13ca58c95e5a.png)
