### ISSUE TITLE
Card 的 transition: all 会造成  queue-anim 等一些组件效果错误

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#13156]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
WIN10 - Chome70 - React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk37229okj)

### Steps to reproduce
使用 `queue-anim` 为 `Card` 添加队列动画。

### What is expected?
动画效果正常

### What is actually happening?
组件 `Card` 的 `transition: all` 对 `queue-anim` 造成了影响

---
参考： https://github.com/react-component/queue-anim/issues/66

**Comment by afc163** [comment]
这不是 antd 的问题。

**Comment by nuintun** [comment]
@afc163 不过 `transition: all` 波及面有点广，最好精确到用到的地方。

**Comment by jljsj33** [comment]
其实这真是 antd 的问题。。transition一直都是慎用。。。一直不提倡用 all，有些组件是我改过了。。。

**Comment by jljsj33** [comment]
all 不仅会影响当前dom 的动画。。。还会影响子级的动画效果。。。这 transition 的 bug 以前在 menu 里就出现过。。。
