### ISSUE TITLE
onChange function (props of the Form component) isn't fired

### ISSUE THREAD

**Issue by zelongc** [ant-design/ant-design#13152]
Thanks for the awesome work!

I came across this issue:
The onChange event couldn't get fired when I use a drop-down (I used Select component of AndDesign) field.
Not sure if this is a bug and intentional? 

Please see this demo if you have a chance: https://codepen.io/anon/pen/QJvdJd?editors=0010

I the demo, I was expecting the console print an event object when I select a value in the Select field while it doesn't print anything.

Thanks.
Z
---

**Comment by zelongc** [comment]
It's funny that I would make a duplicated issue if I use an issue helper to create a new issue, while it seems that the issue can't be re-opened by the robot if I update it.

Looks like we need a PR to give the ant-design-robot ability to re-validate the updated invalid issue...

**Comment by afc163** [comment]
@zeakhold You can create new issue with https://new-issue.ant.design/ regardless of closed one.
