### ISSUE TITLE
Custom minimize/restore and zoomout/maximize buttons next to close button of Modal

### ISSUE THREAD

**Issue by kamiyaki22** [ant-design/ant-design#13159]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using antd modal component and I would like to allow users to change size of the modal in the application. I want minimize/restore and zoom out/maximize buttons next to the close button. When user minimize or zoom out the modal, they can do stuff on the modal or browse the container behind (where they open the modal) at the same time. Also, when I add props "mask={false}", I want to allow scroll the container behind.

### What does the proposed API look like?
Add props minimizable, zoomable like closable, onMinimize, onZoom like onCancel. The icon should be changed for different state of minimize/restore and zoomout/maximize, therefore also need props for customizing the button icons. And allow scroll the container behind when "mask={false}", alternatively to have a new props to control it.

**Comment by afc163** [comment]
```jsx
<Modal title={<div>{whatever_you_need_to_render_in_header}</div>}>
```
