### ISSUE TITLE
[Select component]Support disableSelectedItem props

### ISSUE THREAD

**Issue by kagol** [ant-design/ant-design#13151]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When i select an item, i can't select it again, the onChange event can't trigger again
But this function is very useful, it can allow you to do some custom task

### What does the proposed API look like?
I hope support a bool props similar to 'disableSelectedItem', if its value is true(default), you can't triggger onChange when you select an selected item; but you can set it false, then you can trigger onChange event, and do some custom task

**Comment by afc163** [comment]
There is `disabled` prop for Option.

**Comment by yutingzhao1991** [comment]
For your require, you can set a different value after option were clicked, then the option will not been set to selected and will trigger onChange again when you click it.

**Comment by kagol** [comment]
But i want to maintain the selected state, then users can know what they had chosen @yutingzhao1991

**Comment by kagol** [comment]
I know `disabled` props,  but i don't want to disabled an Option, i just want to select an selected item again(trigger onChange event) @afc163

**Comment by afc163** [comment]
Why do you need that? What is your situation exactly?

**Comment by kagol** [comment]
There is a Select Component contain some Options, the front of all are normal Option, but the last one is a custom Option. 
when i click the last Option, it will pop a Modal except select this option, when i do something in the modal, i will close it, maybe i will pop the Modal twice, so i need click the last Option again.
But i can't click the last Option again just because it is selected, i must refresh the page or select another Option then select the last Option, the experience is very bad. @afc163

**Comment by kagol** [comment]
So i need a prop like `disableSelectedItem` to control the selected item whether it can be selected multiple times, its value is true default, just as the Select's current performance.
But i can set `disableSelectedItem=false`, then i can select an selected item(trigger the onChange event) multiple times. @afc163

**Comment by afc163** [comment]
You can trace https://github.com/ant-design/ant-design/issues/10831 for futhermore development, and use method in https://github.com/ant-design/ant-design/issues/10831#issuecomment-418106428 or https://github.com/ant-design/ant-design/issues/10831#issuecomment-418303902 as workaround.

**Comment by afc163** [comment]
Wow, somebody just proposed a PR right now: https://github.com/react-component/select/pull/348

**Comment by kagol** [comment]
Good, this function may meet my demand.
When can you support this `customize Option` function?
