### ISSUE TITLE
form表单中自动添加、删除表单项

### ISSUE THREAD

**Issue by zhoulisuper** [ant-design/ant-design#13168]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
window7

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
表单示例--动态添加、删除表单项
1、添加5个表单项
2、删除第2个表单项
3、再添加一个表单项、一次输入1、2、3、4、5、

### What is expected?
第5个输入框显示5

### What is actually happening?
第4个输入框和第5个输入框联动显示相同的内容

---
将add方法中的nextKeys变量定义为const nextKeys = [...Array(keys.length 1).keys()]

**Comment by zhoulisuper** [comment]
add方法中 nextKeys变量改为const maxKey  = keys&&keys.length?Math.max(...keys):0
    const nextKeys = keys.concat(maxKey+1)这样子才可以

**Comment by zombieJ** [comment]
感谢反馈，官网已调整示例。
