### ISSUE TITLE
Tree Select 当节点数达到300的时候，性能需要提升

### ISSUE THREAD

**Issue by huangyingjie** [ant-design/ant-design#1316]
RT。节点数量一多，页面卡顿非常明显，点击tree节点也非常卡，至少一秒钟才能完成选中。
另外，调用Tree Select的组件如果shouldComponentUpdate不手动限制下，很可能导致页面其它地方输入文字卡顿，也是因为它渲染慢。

**Comment by plandem** [comment]
yep....got same issue. about 5 sec to open :(

also perfomance issue with common rc-select  and alot of items :(

**Comment by plandem** [comment]
corrected - it's slow with 6000 items. Is there any way to speed up it?

**Comment by warmhug** [comment]
sorry. will release new version soon.

**Comment by warmhug** [comment]
@huangyingjie 300个节点应该是不会卡的，之前测试过5千左右数据量的，可以再帮忙进一步确认下问题，谢谢。另外注意一些基本优化点：不要让所有节点都默认展开；一个页面不要同时有过多的Tree Select组件一起存在。
组件本身也正在进一步优化速度，放在 antd-1.0-beta 里发出，目前beta版已可用。

**Comment by huangyingjie** [comment]
好的，300个确实是不严谨的估算，重新确认下，我这里是890个，没有默认展开，只有一个tree select。

**Comment by totoSalad** [comment]
情况：
项目中包含了500-600的treeNodes，没有默认展开，并且我们支持全选功能。
当check任何一个TreeNode，渲染时间大约两秒。

实践方式：
保存了数据在state tree中，每次更新state之后。TreeNode List都重新生成。

求改进方法？

**Comment by Z1hgq** [comment]
It still renders very slow with 10000 items, is there any solutions?
