### ISSUE TITLE
表格列使用fixed固定，扩展行高度不一致

### ISSUE THREAD

**Issue by linzelong95** [ant-design/ant-design#13165]
很抱歉我又来提问了，因为我实在不知如何解决这个问题。期待热心网友能告诉我一下如何使表格扩展出来的部分两边等高（如图），十分感谢！
![table](https://user-images.githubusercontent.com/40480550/47700328-0b9b7800-dc51-11e8-98fc-df9a1e266c31.png)

**Comment by dusheng0927** [comment]
楼主，您好！请问你这个问题“表格列使用fixed固定，扩展行高度不一致”怎么解决的呢？

**Comment by linzelong95** [comment]
@dusheng0927 
抱歉，这个问题我并没有得到解决。
