### ISSUE TITLE
DatePicker onCalendarChange does not work

### ISSUE THREAD

**Issue by akramer24** [ant-design/ant-design#13162]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
macOS High Sierra 10.13.6, Google Chrome Version 70.0.3538.77

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1449ynx33l)

### Steps to reproduce
pass callback as onCalendarChange prop, and the callback is never called when the calendar changes (i.e. changing the month or year)

### What is expected?
I would expect to click through the months and see my onCalendarChange callback to be called

### What is actually happening?
nothing

**Comment by spideeee** [comment]
The `rc-calendar` does not has any prop named `onCalendarChange`, so this should be removed from the documentation. 
You can use `onChange`, which triggers when the date is selected.

**Comment by akramer24** [comment]
@spideeee it would be great though if there were a way to know which dates were rendered at a given time. so if onCalendarChange could be added so that it takes a start and end date, that would be fantastic.

**Comment by spideeee** [comment]
@akramer24 , you can refer to the documentation, `onChange` gives the date selected on the `DatePicker`.

**Comment by akramer24** [comment]
@spideeee but what if someone wants the range of visible dates?

**Comment by spideeee** [comment]
DatePicker has only single date, if you need range of date, then use RangePicker.
