### ISSUE TITLE
最新版组件bug

### ISSUE THREAD

**Issue by llcgh** [ant-design/ant-design#13172]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
win10，chrome

### Reproduction link
[https://www.meiyoulianjie.com](https://www.meiyoulianjie.com)

### Steps to reproduce
import {message, notification} from 'antd';

export const LoginSuccess = () => {
   message.success('登陆成功');
};

我引入的是message 结果出来的是 notification。这只是其中之一。Input 有bug 无法获取输入的值。

一直认为 antd 比 elementui 强呢。今见不过如此。啰嗦了这么多，有人看吗？

### What is expected?
import {message, notification} from 'antd';

export const LoginSuccess = () => {
   message.success('登陆成功');
};

我引入的是message 结果出来的是 notification。这只是其中之一。Input 有bug 无法获取输入的值。

一直认为 antd 比 elementui 强呢。今见不过如此。啰嗦了这么多，有人看吗？

### What is actually happening?
import {message, notification} from 'antd';

export const LoginSuccess = () => {
   message.success('登陆成功');
};

我引入的是message 结果出来的是 notification。这只是其中之一。Input 有bug 无法获取输入的值。

一直认为 antd 比 elementui 强呢。今见不过如此。啰嗦了这么多，有人看吗？

**Comment by llcgh** [comment]
项目在开发中，没有链接。我的邮箱lilichang@189.cn

**Comment by Veveue** [comment]
https://codesandbox.io/s/m7o2rk55qj

**Comment by afc163** [comment]
Your codesandbox works without any errors and exceptions that you described above.

<img width="1440" alt="default" src="https://user-images.githubusercontent.com/507615/48657883-4ab03280-ea73-11e8-86d2-0205f885eaf6.png">

**Comment by afc163** [comment]
Closing it for no reproduible demo.
