### ISSUE TITLE
Cannot input in `getFieldDecorator()` items in a form displayed by `Modal.confirm()`?

### ISSUE THREAD

**Issue by boringwong** [ant-design/ant-design#13182]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
macOS 10.14.1, Chrome 70

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9oyyww1llr)

### Steps to reproduce
See the CodeSandbox link.

### What is expected?
Can input normally.

### What is actually happening?
Cannot input.

**Comment by chenshuai2144** [comment]
`Modal.confirm() `by `ReactDOM.render ` to render.
