### ISSUE TITLE
Manual upload on ie9

### ISSUE THREAD

**Issue by BG5FD** [ant-design/ant-design#13188]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I saw beforeUpload api in antd. But it says that it doesn't work on ie9. So how can I implement manual upload on ie9. Because I don't think file should upload immediately after you click the upload button at first time. In addition, will antd support multiple files on ie9?

### What does the proposed API look like?
I hope that beforeUpload function can work on ie9.

**Comment by afc163** [comment]
Maybe you should use `<input type="upload" />` instead antd Upload. It is hard to implement beforeUpload in IE9.
