### ISSUE TITLE
搞了一天没有跑通脚手架的人说几句

### ISSUE THREAD

**Issue by kyo4311** [ant-design/ant-design#1318]
windows 搞一个init脚手架好难，搞了一天没有搞起来，这足以说明我太菜太笨了。

ant-design是基于react的组件，
react和react-dom可以使用es6方式加载使用，也可以通过引入js来使用。

希望ant-design也能支持引入一个js文件和一个css文件来使用，虽然这样子引入使用，可以文件比较大，利用率什么的都没有考虑，但这样子能简单很多，也能在原先的项目中集成变的方便。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1036

**Comment by afc163** [comment]
搞了一个单独构建的例子：https://github.com/ant-design/antd-init/tree/master/examples/build-antd-standalone

**Comment by afc163** [comment]
@kyo4311

**Comment by kyo4311** [comment]
好的，fork一个。
