### ISSUE TITLE
The Upload warn "Unknown props `directory`, `webkitdirectory` on <input> tag"

### ISSUE THREAD

**Issue by onfuns** [ant-design/ant-design#13186]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
Mac Chrome 70.0.3538.102

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
<Upload>
    <Button>
      <Icon type="upload" /> Click to Upload
    </Button>
  </Upload>

### What is expected?
no warning

### What is actually happening?
warning

**Comment by afc163** [comment]
Please upgrade to react 16

**Comment by likelikeli** [comment]
不能用react 16,我这只能使用15啊

**Comment by quqiuhua-dawn** [comment]
How to solve this problem?
