### ISSUE TITLE
onSelect props on Tree

### ISSUE THREAD

**Issue by GaiaBing** [ant-design/ant-design#13190]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There are only two parameters for this method(selectedKeys and e) , but I need to get complete data of selectedNode and I need get this selectedNode's parent, Is there a way to achieve this?

### What does the proposed API look like?
function(selectedKeys, selectNode:{key: , title: , parentKey: , ...otherData}, e);
I hope to add a parameter.

**Comment by zombieJ** [comment]
`onSelect` do provide the node info. Pls check official doc: https://ant.design/components/tree-cn/#Tree-props
