### ISSUE TITLE
是否考虑给checkbox 顶层元素加个disable的类名

### ISSUE THREAD

**Issue by walker27** [ant-design/ant-design#13199]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
浏览器版本: Chrome 70

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zlpm4v4nkp)

### Steps to reproduce
我司的UI期望对Checkbox进行一些样式调整，包括Checkbox的整体点击区域，现在我在调整样式后发现，disable情况下顶层元素没有disable样式名，导致内部元素的间隙无法出现禁用的手势

### What is expected?
顶层元素增加disable的类名

### What is actually happening?
顶层元素<label className="ant-checkbox-wrapper" /> 没有disable类名

---
在顶层增加disable的类名有助于二次开发的样式调整

**Comment by yutingzhao1991** [comment]
确实，disable 的范围应该等同于点击的范围。给 https://github.com/react-component/select 这里来个 PR？

**Comment by walker27** [comment]
> 确实，disable 的范围应该等同于点击的范围。给 https://github.com/react-component/select 这里来个 PR？

👌

**Comment by walker27** [comment]
我提了antd的checkbox的[PR](https://github.com/ant-design/ant-design/pull/13211), 目前跟radio上的做法保持一致，还有一点，我发现radio上defaultChecked & disabled 的时候和 checked & disabled 的状态顶层的类名不一样（差了一个ant-radio-wrapper-checked）不知道这个有什么用意没有 @yutingzhao1991

**Comment by afc163** [comment]
@walker27 没啥用意，就是没加。
