### ISSUE TITLE
TimePicker style error, when format = 'HH:mm'

### ISSUE THREAD

**Issue by DarylsJoy** [ant-design/ant-design#13194]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Chrome 70

### Reproduction link
[https://ant.design/components/time-picker/](https://ant.design/components/time-picker/)

### Steps to reproduce
when set format = 'HH:mm' (hide second), item .ant-time-picker-panel-input overflow its wrapper

隐藏掉选择器一部分后，展示值的元素长度没有变化，仍是之前的长度，导致溢出其父级元素。

### What is expected?
not overflow

### What is actually happening?
overflow

**Comment by afc163** [comment]
reproduce link: https://ant.design/components/time-picker/#components-time-picker-demo-hide-column
