### ISSUE TITLE
Hide error information when the formitem focus

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#13202]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Validate input and render error info when onBlur event is fired.
Then trigger the onFocus event, I hope to automatically clear the error info. Too many formItem makes me do not want to reset the error with the setFields method.

### What does the proposed API look like?
hideFieldError

**Comment by zombieJ** [comment]
Close since it's not common requirement.

**Comment by MatheusPatrickZup** [comment]
Any updates on this or something similar?
