### ISSUE TITLE
antd doesn't strictly follows Semantic Versioning 2.0.0. actually

### ISSUE THREAD

**Issue by fenghuizhang** [ant-design/ant-design#13209]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
windows10, chrome 70, react 16.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qx45pkqz5w)

### Steps to reproduce
1.my project's package.json config  "antd": "^3.0.1",
2. node_modules actually installed "version": "3.8.4",

### What is expected?
ant-design should be installed atleast 3.9.x

### What is actually happening?
actually installed "version": "3.8.4",

---
i think it should be installed at least more than 3.9.x,
 actually i found another question is that version 3.9.x is not Backward compatible

**Comment by afc163** [comment]
Please reinstall node_modules after removing `yarn.lock` and `package-lock.json`.

We follow Semantic Versioning 2.0.0 if you find any compatible problems, feel free to create new issue and report them.
