### ISSUE TITLE
import svg with creat-react-app and put it into Icon props makes a type error

### ISSUE THREAD

**Issue by sholsyjy** [ant-design/ant-design#13205]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
MacOS, Chrome 70, node 11.1.0, typescript 3.1.6

### Reproduction link
[https://github.com/sholsyjy/antd-svg-type-error](https://github.com/sholsyjy/antd-svg-type-error)

### Steps to reproduce
1.import svg using creat-react-app 
![1542686010009](https://user-images.githubusercontent.com/17801252/48752356-c4d6f600-ecc3-11e8-8536-a7cb82f5cce9.jpg)
2.put this svg component as a prop into Icon
![1542685969853](https://user-images.githubusercontent.com/17801252/48752355-c4d6f600-ecc3-11e8-90fb-d21c5ef00a0b.jpg)
3.there is a type error

### What is expected?
however I import the svg with create-react-app or antd, the component is the same type

### What is actually happening?
the component is not the same type

**Comment by sholsyjy** [comment]
@chenshuai2144 
I just updated my reproduction link. I hope it helps solve the problem.

**Comment by chenshuai2144** [comment]
thank you.
you can try create new file 'logo.svg.d.ts' in your project.
or you can use  const ReactComponent = require("./logo.svg").
this is a typescript wrong.
It may be better to escape him.

**Comment by EnixCoda** [comment]
@chenshuai2144 Is there any reason that ant design declared `CustomIconComponentProps` interface instead of using `React.SVGProps<SVGSVGElement>`?
This doesn't make sense to me.
Thanks.

**Comment by EnixCoda** [comment]
@chenshuai2144 
Thank you for replying!

If it was meant for that purpose, I'd suggest:
```ts
interface CustomIconComponentProps extends React.SVGProps<SVGSVGElement> {
  // extra types
}
```

Then no unexpected overrides will happen. Or is there any other concerns I missed?

**Comment by danilofuchs** [comment]
This should be reopened. My suggestion is to extend the interface `React.FunctionComponent<CustomIconComponentProps>` to `React.FunctionComponent<CustomIconComponentProps | SVGProps<SVGSVGElement>>`, allowing for usage according to CRA documentation.
