### ISSUE TITLE
Affix Component show disorderly after page resize

### ISSUE THREAD

**Issue by Ykeng** [ant-design/ant-design#13204]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
windows7，chrome 64，node 10.13.0

### Reproduction link
[https://github.com/Ykeng/affix-test.git](https://github.com/Ykeng/affix-test.git)

### Steps to reproduce
1： scroll the page to make the content fixed
2：resize the page from bottom to top
3：scroll to the bottom of  the page

### What is expected?
the content in Affix doesn't overlap the table pagination 

### What is actually happening?
the content in Affix overlap the table pagination

**Comment by zombieJ** [comment]
Close since reproduce not exist.
