### ISSUE TITLE
References to 'this' at the top level of modules

### ISSUE THREAD

**Issue by MrStevenHill** [ant-design/ant-design#13217]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
Windows 10

### Reproduction link
[https://github.com/MrStevenHill/rollup-antd-library-typescript](https://github.com/MrStevenHill/rollup-antd-library-typescript)

### Steps to reproduce
I've uploaded an example to GitHub (see above).

### What is expected?
I'm trying to create a boilerplate for a library of reusable components in TypeScript, using Ant Design for UI elements and Rollup for bundling.

### What is actually happening?
Rollup is warning about invalid references to 'this' at the top level.

---
I am using Rollup because the intention is for the package to be used as a library. There seem to be few examples of this specific development stack, so hopefully this will be useful to others.

**Comment by ztplz** [comment]
I tried to make your demo work properly, but it looks like it lacks a lot of rollup environment settings. It prompts that many variables are not exported.

**Comment by ZenStevenHill** [comment]
Hi, thanks for looking at this. The errors point to invalid references to 'this' in the AntD source. I initially raised this with Rollup and was advised me to raise an issue here.

**Comment by FatFatFox** [comment]
I met the same problem. Hope some expert could solve this problem. It makes me exhusted .
now, I have to go back to Webpack.

**Comment by kcsmad** [comment]
Hey guys, I'm gonna take a look on this issue and see if I can help on anything

**Comment by kcsmad** [comment]
Well, I've already encountered this problem in day by day with rollup. I guess this is just a problem on how to build with rollup than a problem in the antd specific. As I see in your project, you use the native external from rollup, I changed for a plugin that handles this for you. Could you please see if this still happen after this?

Feel free to correct me if I'm wrong.

**Comment by afc163** [comment]
https://github.com/MrStevenHill/rollup-antd-library-typescript/pull/2

**Comment by MrStevenHill** [comment]
Thanks for your time on this Kevin, I've create a new branch and merged your pull request.

I think there is a problem with the config for rollup-plugin-peer-deps-external. On build, rollup is throwing an error:

`semantic error TS2307 Cannot find module 'antd'.`

**Comment by kcsmad** [comment]
Strange, since I built here and everything seems to work, could you please commit or give more information on how you're doing this. Because seems to have some divergences on your local and remote repos.

**Comment by MrStevenHill** [comment]
Hi, yes very strange. I cloned the new branch containing your changes, installed dependencies and then ran the build command. Haven't made any changes to commit.

**Comment by MrStevenHill** [comment]
https://github.com/MrStevenHill/rollup-antd-library-typescript/tree/fix-build

**Comment by kcsmad** [comment]
I guess you already done this, but could delete your node_modules and then install inside my branch?
Just to kill this possibility.

**Comment by MrStevenHill** [comment]
The branch was cloned into a new directory so we can rule that out.

**Comment by kcsmad** [comment]
I see, I'll check more later on today and see if I can get this error at home. (sorry for the late response)

**Comment by kcsmad** [comment]
#https://github.com/MrStevenHill/rollup-antd-library-typescript/pull/3

**Comment by kcsmad** [comment]
https://github.com/MrStevenHill/rollup-antd-library-typescript/pull/3

**Comment by kcsmad** [comment]
#https://github.com/MrStevenHill/rollup-antd-library-typescript/pull/3

**Comment by MrStevenHill** [comment]
Thanks for the pull request, I've merged your changes into the dev branch.

**Comment by kcsmad** [comment]
How do I get the funding? Since the issue was closed!

**Comment by MrStevenHill** [comment]
This issue is not closed, we are still working on a dev branch

**Comment by MrStevenHill** [comment]
Please re-open this issue until we have a verified solution

**Comment by MrStevenHill** [comment]
Sorry for the delay. I've reviewed the code on Dev and made a few changes but the build is working so happy for this issue to be considered closed. Thanks for the work @kcsmad

**Comment by kcsmad** [comment]
You're welcome mate. I'm happy that I could help.
