### ISSUE TITLE
Tabs set animated, TabPane set fixed width, second pane position moved

### ISSUE THREAD

**Issue by coldice945** [ant-design/ant-design#13218]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.7

### Environment
Windows, Chrome, react 16.3.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mmq4wwkxk9)

### Steps to reproduce
set  Tabs animated, TabPane content width set less than Tabs(like 90% width), or fixed width (set max-width)

### What is expected?
second pane content position is right.

### What is actually happening?
second pane content position is moved.

**Comment by afc163** [comment]
```diff
.card-container > .ant-tabs-card > .ant-tabs-content {
  height: 120px;
  margin-top: -16px;
- width: 90%;
}
```

https://codesandbox.io/s/826x3736m2
