### ISSUE TITLE
Why not provide a way to set `global prefixCls `

### ISSUE THREAD

**Issue by jeezlee** [ant-design/ant-design#13210]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
antd@3.10.8

### Steps to reproduce
No

### What is expected?
In my case, the project design as `Micro frontends`, which means may have two different versions of ant-design in my project. We desire a simple way to set `global prefixCls `, so that we can implement our `Customize Theme` friendly.

### What is actually happening?
RT

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10855#issuecomment-430562835
https://github.com/ant-design/ant-design/pull/12991

**Comment by anyexinglu** [comment]
so why not provide a way to set `global prefixCls `
