### ISSUE TITLE
TreeSelect搜索bug

### ISSUE THREAD

**Issue by qiaoyixuan** [ant-design/ant-design#13213]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
macOS High Sierra，Chrome latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/39owo1wm6)

### Steps to reproduce
搜索title关键字 比如:19

### What is expected?
像官网TreeSelect[多选demo]一样的效果

### What is actually happening?
搜索结果没有选中效果，同时console报key重复warning
关键字消失后搜索结果仍在最上面

---
treeData初步检查没有key重复问题

**Comment by qiaoyixuan** [comment]
@yutingzhao1991 麻烦关注一下这个case，不知道是bug还是用法问题，谢谢

**Comment by zombieJ** [comment]
你的 data 中有几个 node 没有 value，导致 filter 的时候，通过 value 映射回 node 时，几个空 value 对应到了同一个 node。使得 react render 的时候报了 key 相同的错误：https://codesandbox.io/s/25pykwym0

**Comment by zombieJ** [comment]
`rc-tree-select@2.4.1` 里加了一个 warning 来帮助用户排查。
