### ISSUE TITLE
Menu in sider does not render if sider is default collapsed with collapsed width 0 and the menu is connected

### ISSUE THREAD

**Issue by joshuaavalon** [ant-design/ant-design#13224]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Chrome 70.0.3538.102

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3q3yqwjn16)

### Steps to reproduce
See the example.

### What is expected?
Both `Test` and `Test2` is shown

### What is actually happening?
Only `Test` is shown.

---
If you remove either `defaultCollapsed` or `collapsedWidth={0}`, then `Test2` is shown, so I am pretty sure this is a bug.

**Comment by spideeee** [comment]
You can check how I implemented the same here: https://codesandbox.io/s/l27zo562mm and is working fine.

**Comment by joshuaavalon** [comment]
I have a work around which connects at the item level. It also works. I wonder why it does not even render with connected menu.

**Comment by olivermack** [comment]
I had the same issue right now and I did not see the difference in the fiddles directly. Anyway, I got it working by using the `Layout.Sider` as the connected component directly instead of just the Menu. Thus, I ended up with a connected sider which includes also the menu. No issues anymore.
