### ISSUE TITLE
卡片Card的API中参数hoverable的默认值错误，与案例自相矛盾。

### ISSUE THREAD

**Issue by chenjia001** [ant-design/ant-design#13225]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
自带codepen

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
案例更灵活的内容展示，其中hoverable为默认值，鼠标移过时可浮起；当把hoverable设置为false时，不可浮起。

### What is expected?
当把hoverable设置为false时，不可浮起。

### What is actually happening?
当把hoverable设置为false时，可浮起。

**Comment by afc163** [comment]
https://codepen.io/anon/pen/LXerxg?&editors=001

It works perfectly.
