### ISSUE TITLE
dockerbuild failed, yarn socket timeout

### ISSUE THREAD

**Issue by ergenekonyigit** [ant-design/ant-design#13221]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
docker linux node 10.13

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
docker build failed after upgrade antd to 3.10.8

### What is expected?
success docker build 

### What is actually happening?
```
[2/4] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarnpkg.com/antd/-/antd-3.10.8.tgz: ESOCKETTIMEDOUT".
```

**Comment by afc163** [comment]
I don't think it is antd's problem.
