### ISSUE TITLE
ant design tree component without add,delete,wrtie function

### ISSUE THREAD

**Issue by Wenxiaoxiao** [ant-design/ant-design#13229]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
it's help our front-end engineer build pages quickly.

### What does the proposed API look like?
       nodeAdd: ((s,d,n) => that.handleAdd(s,d,n)),
       nodeEdit: ((s,d,n) => that.handleEdit(s,d,n)),
       nodeDel: ((s,d,n) => that.handleDelete(s,d,n))

add these three function to the ant design tree component ,it would be more popular

**Comment by ztplz** [comment]
Why not edit data directly?

**Comment by Wenxiaoxiao** [comment]
> Why not edit data directly?

I want have icon-button after tree node ,so that i can click them,like that
[https://xiaoniezi.github.io/projects/elementUI_tree/#/slot](url)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5782
https://github.com/ant-design/ant-design/issues/8997
https://github.com/ant-design/ant-design/issues/11668
