### ISSUE TITLE
input 使用len 或者 max 限定长度

### ISSUE THREAD

**Issue by changbin666** [ant-design/ant-design#13235]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Input  限定 len 或者max min 长度之后还能输入。还得使用原生的 maxLength 限定长度。还不如elementui呢。真实高看你蚂蚁金服了。

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
Input  限定 len 或者max min 长度之后还能输入。还得使用原生的 maxLength 限定长度。还不如elementui呢。真实高看你蚂蚁金服了。

### What is expected?
Input  限定 len 或者max min 长度之后还能输入。还得使用原生的 maxLength 限定长度。还不如elementui呢。真实高看你蚂蚁金服了。

### What is actually happening?
Input  限定 len 或者max min 长度之后还能输入。还得使用原生的 maxLength 限定长度。还不如elementui呢。真实高看你蚂蚁金服了。

---
开发中的项目，没有链接。这个问题可以自己试试，十行代码都用不了。

**Comment by afc163** [comment]
Don't use props that antd or native input don't provide.
