### ISSUE TITLE
Incorrect rendering of wrapped Menu.Items

### ISSUE THREAD

**Issue by dkamyshov** [ant-design/ant-design#13237]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Chrome 70 (Ubuntu 18 x64), Chrome 68 (Windows 7 x64), IE 11 (Windows 7 x64) and probably all others

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/py6wl5rxym)

### Steps to reproduce
Wrap Menu.Item with another component and render it inside Menu.

### What is expected?
Menu items are rendered correctly

### What is actually happening?
Menu items are rendered incorrectly. Menu items' LI classes look like "undefined-item" instead of "ant-menu-*-item"

**Comment by afc163** [comment]
https://codesandbox.io/s/k906z9yo1r
