### ISSUE TITLE
Table存在固定列并开启展开功能，固定列的行高度异常

### ISSUE THREAD

**Issue by misumi111** [ant-design/ant-design#13232]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
win10，chrome 70

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/74nr89z4ox)

### Steps to reproduce
Table组件设置固定列，开启展开行功能。点击展开行，查看固定列的行高。

### What is expected?
固定列的行高能够和非固定列的行高保持一致。

### What is actually happening?
固定列的行高小于非固定列的行高。

---
重现链接提供了两种展开行内容。默认为一个P标签。实际业务中我们展开行内展示的是一个子表格。使用子表格的话，这个问题会更加明显。

**Comment by misumi111** [comment]
希望有一天能支持这个功能。感谢。

**Comment by Irislm** [comment]
遇到同样的问题，挺明显的
