### ISSUE TITLE
设置sider collapsewidth，收起后菜单超出menu

### ISSUE THREAD

**Issue by Lynn0108** [ant-design/ant-design#13236]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
os chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://njp774nlj.codesandbox.io/)

### Steps to reproduce
设置sider的collapseWidth
点击收起菜单

### What is expected?
正常收起

### What is actually happening?
菜单超出sider

**Comment by Lynn0108** [comment]
上面的链接可能打不开，试试这个？https://codesandbox.io/s/njp774nlj

**Comment by afc163** [comment]
You have to customize this variable as well: https://github.com/ant-design/ant-design/blob/b2f6655061ef1a8e574544b99c210cdfb3e8e6fb/components/style/themes/default.less#L323
