### ISSUE TITLE
Pagination 选择每页条数弹出方向

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#13241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前只能下拉往下弹出，分页工具栏一般在底部，会出现滚动条，必须再滚动一下屏幕，操作不友好

![form](https://user-images.githubusercontent.com/2288630/48883896-f20adc00-ee5c-11e8-8844-c7c4a501ac7f.gif)

### What does the proposed API look like?
自动适配，选择向上或向下弹出

**Comment by afc163** [comment]
It will, check this demo: https://4343o55vn7.codesandbox.io/

![1](https://user-images.githubusercontent.com/507615/48934619-c3b1fd00-ef3f-11e8-8bbe-25bffda051b8.gif)

**Comment by zlab** [comment]
@afc163 https://xlqm9wm4ww.codesandbox.io/

**Comment by zlab** [comment]
@afc163 问题还是存在，可以重新打开这个issue吗？
https://xlqm9wm4ww.codesandbox.io/

**Comment by Kermit-Xuan** [comment]
给的 codesandbox 已经正常了，先关闭了，有需要再打开。
