### ISSUE TITLE
Option in Select repot 'missing import', but I declared Option

### ISSUE THREAD

**Issue by fikyair** [ant-design/ant-design#13247]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.9

### Environment
linux deepin 15.5 、Chrom 版本 63.0.3239.132（正式版本）（64 位）、webstorm

### Reproduction link
[https://github.com/fikyair/Ant-Design-Beta/blob/master/pic/picInfo.png](https://github.com/fikyair/Ant-Design-Beta/blob/master/pic/picInfo.png)

### Steps to reproduce
https://github.com/fikyair/Ant-Design-Beta/blob/master/pic/picInfo.png

### What is expected?
When using Option = Select.Option, it will be referenced in webstorm

### What is actually happening?
Missing import statement

**Comment by fikyair** [comment]
This is the a online reproduction I provided, https://codesandbox.io/s/24m60j67yj, It has no bugs，
but when I use 'const Option=Select.Option;'  in webstorm, the 'Option' will not be referenced, but the program runs normally. This is my screenshot  (https://github.com/fikyair/Ant-Design-Beta/blob/master/pic/picInfo.png)
The latest version also has the same problem.

**Comment by ztplz** [comment]
@fikyair It is probably a bug  in `webstorm`. Are you using other ide to open normally?

**Comment by fikyair** [comment]
> @fikyair It is probably a bug in `webstorm`. Are you using other ide to open normally?

I am sure it is an bug in webstorm and in deepin , thank you.

**Comment by ztplz** [comment]
@afc163  右神快邀我`Collaborator` 。

**Comment by zombieJ** [comment]
@ztplz ,https://github.com/ant-design/ant-design/wiki/Collaborators welcome : )

**Comment by fikyair** [comment]
> @ztplz ,https://github.com/ant-design/ant-design/wiki/Collaborators welcome : )
Why are my contributions not showing up on my profile?

**Comment by zombieJ** [comment]
Here is the link for [WebStorm Bug Tracker](https://youtrack.jetbrains.com/issues/WEB).
