### ISSUE TITLE
Table column sorter icon has bad UX

### ISSUE THREAD

**Issue by cemremengu** [ant-design/ant-design#13249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Chrome Version 70.0.3538.102

### Reproduction link
[https://ant.design/components/table/#components-table-demo-head](https://ant.design/components/table/#components-table-demo-head)

### Steps to reproduce
Create table with sorter option

### What is expected?
I expect to be able to easily click on the `asc` and `desc` buttons.

### What is actually happening?
The icon is very small and being vertically aligned it makes things even harder. It is actually same size as the hand icon so it is very difficult to hit buttons especially the `asc` one.

**Comment by ztplz** [comment]
Hm... these icons looks really a bit small, how about place them horizontal？What's your opinion? @afc163

**Comment by afc163** [comment]
I believe @dazbo had made a great point, check the following issues for more information about why we did that and how people hated the original icon-clicking behavior.

#9911
#12158
#5873
#11246
#11543
#12200
#11543
#11541
#1524

**Comment by LilMinmax** [comment]
Sorry to comment on a closed item, but (@dazbo etc) is there any way to get rid of the "null" click? Once you click on a column, there is an expectation from every one of our users that clicking on the head will just toggle between ascend and descend. the "extra" click back to null state seems broken to many people we spoke to.

**Comment by dazbo** [comment]
Documentation doesn't mention that kind of customization, I guess it is not possible.
But that is a good enhancement, and could help users as you said!

**Comment by zy410419243** [comment]
> Sorry to comment on a closed item, but (@dazbo etc) is there any way to get rid of the "null" click? Once you click on a column, there is an expectation from every one of our users that clicking on the head will just toggle between ascend and descend. the "extra" click back to null state seems broken to many people we spoke to.

Just click the third time.
