### ISSUE TITLE
Select Placeholder shrinks when using Form inline layout

### ISSUE THREAD

**Issue by francisconeves97** [ant-design/ant-design#13240]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Mozilla Firefox

### Reproduction link
[https://codepen.io/anon/pen/bQLRpW?&editors=001](https://codepen.io/anon/pen/bQLRpW?&editors=001)

### Steps to reproduce
Create inline form with Select Input using placeholders

### What is expected?
The placeholder's should be the same size as the text and have a margin like it happens when an option is selected

### What is actually happening?
The select box is shrinked

**Comment by afc163** [comment]
https://codepen.io/anon/pen/QJmZBj?&editors=001

Select don't have default width.

**Comment by snirp** [comment]
Somehow that codepen link is stuck in an eternal reload loop for me. Is that just me?

**Comment by ztplz** [comment]
@snirp  Seems working for me. Try to open it again?
![image](https://user-images.githubusercontent.com/17755202/60428727-179a6800-9c2c-11e9-9481-06cf8e2ee419.png)
