### ISSUE TITLE
antd2-antd3  Warning: onRowClick is deprecated, please use onRow instead.

### ISSUE THREAD

**Issue by ywww** [ant-design/ant-design#13244]
onRowClick={(record, index) => isNullOrUndefined(this.props.onClickRow) ? null : this.props.onClickRow(record)}

当我把 onRowClick 换成 onRow 之后

直接导致react报错

Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls set

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by MrMuhammadRizwan** [comment]
**If you still getting this issue : Warning: onRowClick is deprecated, please use onRow instead.**
you can fixed this issue by trying this:
```
onRow={(record) => ({ onClick: () => { this.someClick(record.key) } })}
```
