### ISSUE TITLE
关于treeSelect组件的bug

### ISSUE THREAD

**Issue by Liswi** [ant-design/ant-design#13245]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
mac/windows/linux

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
1.treeNodeFilterProp属性置为 true, loadData开启懒加载数据
2. 在输入框中搜索某个节点的值(必须是能匹配到的）
3.回删搜索关键词

### What is expected?
期望搜索时展示过滤到的节点，回删显示原完整节点，节点闭合状态不变

### What is actually happening?
1.实际中，匹配到节点之后，组件会自动展开匹配到的节点，这会导致请求子节点加载数据（bug1 ？？）
2.回删关键词到空的时候，会显示原有的所有父节点，并且所有父节点都会去自动展开，导致所有节点一起发送加载数据请求，网页阻塞，奔溃

---
这个bug在我更新到 3.6.X 时出现，一直到 3.10.X还存在。3.4.2好像没有这个问题

**Comment by TristanDongMaster** [comment]
I also encounter the same bug: if  I try to delete all data of the search input, the tree select will auto  request the api of all the children node by recursion , so many many request, the browser crash !!!!!  the  how to resolve it????

**Comment by zombieJ** [comment]
@TristanDongMaster , could you help to provide an online reproduce?

**Comment by TristanDongMaster** [comment]
we just want to achieve the search feature, but I found the bug, so I give up the search requirement....at latest, I have to wait the bug to resolve....

**Comment by TristanDongMaster** [comment]
@zombieJ , @ant-design-bot

**Comment by exonuclease** [comment]
@zombieJ I read the source code of rc-tree-select and find that this problem is caused by expanding all nodes when tree is in filter mode.Please read my PR of rc-tree-selec for more details.
