### ISSUE TITLE
Table / expandedRowRender optional each row

### ISSUE THREAD

**Issue by crazyx13th** [ant-design/ant-design#13253]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
if I return `null` from the `expandedRowRender` function there is no expand functionality at this row.

### What does the proposed API look like?
`expandedRowRender={(record: any, expandedIndex: number, indent: number, expanded: boolean) => null} // no expand functionality`

`expandedRowRender={(record: any, expandedIndex: number, indent: number, expanded: boolean) => 'content'} // normal expand with content`

Thanks!

**Comment by crazyx13th** [comment]
current workaround:

- rowClassName
![grafik](https://user-images.githubusercontent.com/8912561/48933203-becd5900-eeff-11e8-8791-427b39f147bc.png)

- css/sass definition
![grafik](https://user-images.githubusercontent.com/8912561/48933258-f20fe800-eeff-11e8-9e06-d71cf54e5c35.png)

Thanks!

**Comment by crazyx13th** [comment]
closed? without comment?

**Comment by zomars** [comment]
This should be re-opened

**Comment by zombieJ** [comment]
Since performance consideration, we don't call `expandedRowRender` if expanded row not rendered. You can use `expandIcon` to control the expanded logic: https://codesandbox.io/s/8x2j898pp2

ref: #7817 #8157

**Comment by afc163** [comment]
related issue: #10819

**Comment by kodie** [comment]
> current workaround:
> 
> * rowClassName
>   ![grafik](https://user-images.githubusercontent.com/8912561/48933203-becd5900-eeff-11e8-8791-427b39f147bc.png)
> * css/sass definition
>   ![grafik](https://user-images.githubusercontent.com/8912561/48933258-f20fe800-eeff-11e8-9e06-d71cf54e5c35.png)
> 
> Thanks!

A slightly simplified version in text instead of a screenshot:

```js
<Table
  rowClassName={ (item) => (!item.records || !item.records.length) ? 'no-expand' : null }
  ... />
```

```scss
.ant-table-row.no-expand {
  & + .ant-table-expanded-row, .ant-table-row-expand-icon {
    display: none;
  }
}
```

**Comment by matvenko** [comment]
expandable={{
            expandedRowRender: (record) => <p></p>,
            rowExpandable: (record) => record.children ? record.children.length > 0 : false,
          }}
