### ISSUE TITLE
Button弹出Modal会报错

### ISSUE THREAD

**Issue by fonghehe** [ant-design/ant-design#13264]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Win7、google chrome、react 16.1.1

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
通过按钮打开Modal框

### What is expected?
事件的监听出了问题，希望能修复

### What is actually happening?
事件监听报错

---
wave.js:167 Uncaught TypeError: _Event2.default.removeStartEventListener is not a function
    at Wave.resetEffect (wave.js:167)
    at HTMLButtonElement.onClick (wave.js:97)

**Comment by coxom** [comment]
@fonghehe did you by any chance update the antd version? I ran into that issue. Cleaned the node_modules and package-lock.json and reinstalled and no more issues.
Probably you have an older version of css-animation: https://github.com/yiminghe/css-animation/pull/17

**Comment by jamieYou** [comment]
升级到最新版(v3.11.6)后也出现了这个问题

**Comment by fikyair** [comment]
> +1

删了node_modules 重新编译一下就好

**Comment by thbgh** [comment]
++1

**Comment by xiazhangli** [comment]
+1 貌似问题还在？

**Comment by Lumend** [comment]
Popconfirm 的按钮也会报这个错

**Comment by ikhsanuddin** [comment]
+1

**Comment by gigizhaoo** [comment]
> @fonghehe did you by any chance update the antd version? I ran into that issue. Cleaned the node_modules and package-lock.json and reinstalled and no more issues.
> Probably you have an older version of css-animation: [yiminghe/css-animation#17](https://github.com/yiminghe/css-animation/pull/17)

I have updated it to the latest version(1.5.0), but the problem still exists.

**Comment by guoxunbo** [comment]
+1

**Comment by guoxunbo** [comment]
@ant-design-bot
