### ISSUE TITLE
Filter of Table goes wrong in Firefox

### ISSUE THREAD

**Issue by JackLLLLL** [ant-design/ant-design#13268]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
Firefox: 63.0(64-bit) Mozilla Firefox for Ubuntu canonical - 1.0, OS: Ubuntu 16.04, 

### Reproduction link
[https://ant.design/components/table/#components-table-demo-custom-filter-panel](https://ant.design/components/table/#components-table-demo-custom-filter-panel)

### Steps to reproduce
Click the smile face, which functioning as filter, and input something, e.g. 'joe'. Then the error comes out. However, it works fine in Chrome.

### What is expected?
Find rows contain 'joe'

### What is actually happening?
SyntaxError: invalid regexp group in t in tr in n in t in Connect(t) in t in Connect(t) in tbody in table in t in Connect(t) in div in f in div in div in t in Connect(t) in t in t in t in div in t in div in t in t in div in t in o in t in section in section in t in div in t in div in t in article in DocumentTitle in SideEffect(DocumentTitle) in t in div in t in div in t in div in t in div in t in IntlProvider in StrictMode in t in RouterContext in Router

---
Acutally I'm not sure whether it's a bug of Antd or not, but, at least, it's a bug of ant.design

**Comment by ztplz** [comment]
#13187

**Comment by JackLLLLL** [comment]
Awesome!
