### ISSUE TITLE
Could you add an <Input.Password> Component.

### ISSUE THREAD

**Issue by ada87** [ant-design/ant-design#13267]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Could you add an <Input.Password> Component, not Input type="password".

It maybe like as Input.Search , has a Icon "eye" on right .  Click the icon can switch the input mode form common to password, or password to common.

Password Mode :  show text as ******, Common Mode : show orgin text.

### What does the proposed API look like?
```
 <Input.Password
      placeholder="input password"
    />
```

**Comment by zombieJ** [comment]
Update component design preview from our designer:
<img width="221" alt="2018-11-29 2 11 35" src="https://user-images.githubusercontent.com/5378891/49202788-c64da000-f3e0-11e8-951b-8aadbf25778c.png">

**Comment by zombieJ** [comment]
@ada87 , It's good to follow browser behavior instead of missing auto password memorize.

**Comment by ada87** [comment]
I know it, but sometimes, it not reasonable for a password filed tigger browser's autofill.

**Comment by zombieJ** [comment]
You mean this? https://github.com/justjavac/the-front-end-knowledge-you-may-not-know/issues/36

**Comment by ada87** [comment]
Yes, the chrome 's featrue "Automatically sign in" is too strong, password type (under form tag) will always trigger the fill behavior, the property `autocomplete`  can not effect.

**Comment by afc163** [comment]
```diff
- autocomplete
+ autoComplete
```

**Comment by afc163** [comment]
close via #13342
