### ISSUE TITLE
compile  error.  spin\style\index.less filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false)

### ISSUE THREAD

**Issue by panjiefeng** [ant-design/ant-design#13263]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.8

### Environment
win10 react 16.0.0

### Reproduction link
[https://codepen.io/panjunfen/pen/jQzvpJ?&editors=001](https://codepen.io/panjunfen/pen/jQzvpJ?&editors=001)

### Steps to reproduce
origin:            filter: ~"progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false)";
modified:       filter: "progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false)"; 
                  or filter: progid:DXImageTransform.Microsoft.Blur(PixelRadius=1, MakeShadow=false); 
                  or filter: ~"progid:DXImageTransform.Microsoft.Blur(PixelRadius=1, MakeShadow=false)"; these all are OK.

1. why the original code is written like that?
2. can modify the original code?

### What is expected?
compile is ok

### What is actually happening?
compile error

**Comment by JerryChin** [comment]
同样遇到这个问题。

```
ERROR in ./node_modules/_antd@3.10.8@antd/es/spin/style/index.css (./node_modules/_css-loader@1.0.1@css-loader!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--7-2!./node_modules/_antd@3.10.8@antd/es/spin/style/index.css)
Module build failed (from ./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js):


  /* autoprefixer: off */
  filter: progid\:DXImageTransform\.Microsoft\.Blur(PixelRadius\=1, MakeShadow\=false);
                                                             ^
Unrecognised input
      in D:\workspace\web\iot-web\node_modules\_antd@3.10.8@antd\es\spin\style\index.css (line 99, column 63)
 @ ./node_modules/_antd@3.10.8@antd/es/spin/style/index.css 2:14-153
 @ ./node_modules/_antd@3.10.8@antd/es/spin/style/css.js
 @ ./src/layouts/ConsoleHeader.js
 @ ./src/layouts/ConsoleLayout.js
 @ ./src/pages/Console/Dashboard.js
 @ ./src/index.js
 @ multi ./src/index.js
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/_html-webpack-plugin@3.2.0@html-webpack-plugin/lib/loader.js!./public/index.html] 1.82 KiB {0} [built]
    [./node_modules/_webpack@4.26.0@webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/_webpack@4.26.0@webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
```

antd - 3.10.8

**Comment by ztplz** [comment]
@panjiefeng @JerryChin Could you provide a git repository for us to reproduce this problem?

**Comment by JerryChin** [comment]
@ztplz I've created [a minimal project](https://github.com/JerryChin/spin-bug) to demonstrate this bug, check it out!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4915#issuecomment-281551158

**Comment by ztplz** [comment]
@JerryChin Any build script?
![image](https://user-images.githubusercontent.com/17755202/49128531-c0838c00-f306-11e8-864d-78475070aa61.png)

**Comment by JerryChin** [comment]
@afc163  这是逃避问题，而不是解决问题。

**Comment by afc163** [comment]
这个本质是 webpack 配置问题，也欢迎你给我们 PR 来完善文档。

**Comment by JerryChin** [comment]
也许我应该给 less-loader 开发者提个 issue.

**Comment by ztplz** [comment]
https://github.com/webpack-contrib/less-loader/issues/123

**Comment by ztplz** [comment]
@JerryChin 你的问题在于你匹配了css、less后缀的文件，但是你同时用css-loader和less-loader去处理这两种文件，
![image](https://user-images.githubusercontent.com/17755202/49133801-5ece1c80-f31c-11e8-9eb3-0cd77ba12d5a.png)

![image](https://user-images.githubusercontent.com/17755202/49133715-026afd00-f31c-11e8-922a-c4ea6a464545.png)
但是css-loader处理后，less-loader开始处理这个文件，按它定义的解析规则它解析出错了
所以改webpac.config让css-loader处理css文件，less-loader处理less文件可以解决这个问题。
这里的源代码[https://github.com/ant-design/ant-design/blob/master/components/spin/style/index.less#L90](https://github.com/ant-design/ant-design/blob/master/components/spin/style/index.less#L90)
转义符好像是多余的 
![image](https://user-images.githubusercontent.com/17755202/49134072-4f9b9e80-f31d-11e8-9925-a2ac9aa9c778.png)
把转义符去了
![image](https://user-images.githubusercontent.com/17755202/49134107-68a44f80-f31d-11e8-843b-405c7f1dad57.png)
生成的css代码也是ok的

**Comment by JerryChin** [comment]
@ztplz Thanks a lot. the solution provided by @afc163  is equally helpful!

**Comment by panjiefeng** [comment]
@ztplz 对呀，转移符是不需要的，就是说的这个问题。应该不要转移符，不要~，不要双引号，直接写也是可以的
