### ISSUE TITLE
Access the inner dom of components

### ISSUE THREAD

**Issue by robertying** [ant-design/ant-design#13277]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Please provide some way to access the inner DOM of a component.
For example, I need to get `selectionStart` prop of `textarea`. Using `ref` can only access antd's component `TextArea` which does not have prop `selectionStart`.

### What does the proposed API look like?
Maybe `innerRef`

```javascript
<TextArea innerRef={this.textareaRef} />

handleTextAreaInsert = () => {
  console.log(this.textareaRef.current.selectionStart); // access the inner `textarea`
};
```

**Comment by rghattas** [comment]
+1 for inputs as well.

**Comment by ilanus** [comment]
You can access `selectionStart ` like the following
[![Edit antd reproduction template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/74zzqqm8zj)

**Comment by robertying** [comment]
> You can access `selectionStart` like the following https://codesandbox.io/s/74zzqqm8zj

Thanks! It's quite convenient. I'll close the issue.

**Comment by PaulPCIO** [comment]
Yea so this does not work anymore, for anyone else looking for an alternative i updated [that example](https://codesandbox.io/s/antd-reproduction-template-9z721?file=/index.js)

if you have the event target you can use that else, you can access the dom using this method
```jsx
      const domTextArea = ReactDOM.findDOMNode(textarea.current);
      setSelectionStartDomNode(domTextArea.selectionStart);
```

**Comment by rbabayoff** [comment]
Hey there, [here](https://codesandbox.io/s/antd-textarea-dom-ref-i7wf5?file=/index.js) is a complete example that uses [callback refs](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) which unlike regular refs, will re-render the component whenever the ref to the text area dom node changes. My example is based on [this example](https://reactjs.org/docs/hooks-faq.html#how-can-i-measure-a-dom-node) from react's FAQ.

**Comment by PaulPCIO** [comment]
Just a warning with the with the `findDOMNode` => https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-find-dom-node.md

**Comment by netsrikc** [comment]
Are there good alternatives to `findDOMNode` to get the inner HTML ref given the above comments?

**Comment by naingoted** [comment]
you can try this 

```
const inputRef = useRef();
<TextArea ref={inputRef} />
inputRef.current?.resizableTextArea?.textArea.selectionStart
```
