### ISSUE TITLE
无法使用this.refs.xx获取到子组件上的方法

### ISSUE THREAD

**Issue by drawing-snail** [ant-design/ant-design#13284]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
win 10 64位

### Steps to reproduce
// 父组建
<Form>
  <Child ref='child' />
</Form>

// 子组件
getSelectValue = () => {
  console.log('get something');
}

<FormItem label='选择区：'>
  <Select>
    ...
 </Select>
</FormItem>

在父组建上我想通过this.refs.child 来调用子组件上的方法getSelectValue， 但是this.refs.child打印出来的列表中不存在子组件上的任何自定义方法

说明下，这种方式不能用wrappedComponentRef 如果在组建上写了wrappedComponentRef 代码会直接报错

### What is expected?
希望能获取到子组件上的自定义方法

### What is actually happening?
实际打印出来的不含子组件上的任何自定义方法

---
业务场景是表单中，用户可以通过新增的方式创建自定义输入框，我把新增的输入框做成了组建，通过props传值把form属性传给了子组件，这样子组件就能使用form提供的方法及属性， 在父组件Form中引用子组件， 我想通过this.refs的形式获取到子组件上的自定义方法，获取到子组件上的列表值

**Comment by Veveue** [comment]
https://github.com/dvajs/dva/issues/906
