### ISSUE TITLE
Documentation error for RangePicker

### ISSUE THREAD

**Issue by jeremypeters** [ant-design/ant-design#13289]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
Not relevant

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n0v765xm14)

### Steps to reproduce
Not a major issue. At https://ant.design/components/date-picker/ in the example for 'Presetted Ranges',  for 'This Month' the values are `[moment(), moment().endOf('month')]`. I think they should be `[moment().startOf('month'), moment().endOf('month')]`. 

### What is expected?
Not applicable

### What is actually happening?
Not applicable

**Comment by ztplz** [comment]
Hm...I also think that this month means the beginning of the month to the end of the month.

**Comment by fikyair** [comment]
However, I think that for the business scenario, we are more concerned about the day from the beginning of the month to the current day. Because from the current day to the end of the month, from this level, it is impossible to find the data. This is my opinion.

**Comment by jeremypeters** [comment]
In that case I think the label for the button should be "Month To Date".

A case where your suggestion may not be suitable is where a user may require forecast data for example.

I think the discussion is a little moot though as the button is in the documentation to demonstrate how to set a preset range.
