### ISSUE TITLE
有没有相关文档介绍在Webpack中使用本地字体文件包替换默认的 cdn 方式 ？

### ISSUE THREAD

**Issue by abbish** [ant-design/ant-design#1328]
有没有相关文档介绍在 Webpack 中使用本地字体文件包替换默认的 cdn 方式 ？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#i-cant-visit-icon-in-my-network-environment

**Comment by abbish** [comment]
多谢，已找到方案
https://shellmonger.com/2016/01/22/working-with-fonts-with-webpack/
