### ISSUE TITLE
Upload manually cann't trigger Upload's onChange / 手动上传无法触发 Upload 组件的 onChange 事件

### ISSUE THREAD

**Issue by MillionQW** [ant-design/ant-design#13294]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
Chrome laster

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/62kwj0jovr)

### Steps to reproduce
在 CodeSandbox 页面中上传图片，观察 控制台 有没有打印出信息。

### What is expected?
手动上传 点击“上传”按钮，上传成功后，触发 ```onChange```。

### What is actually happening?
Upload 组件的 ```onChange``` 事件并没有触发。

---
发现如果是使用自动上传的话，在图片上传完成后会触发 Upload 组件的 ```onChange```，但是如果是手动上传，```onChange```并不会在上传完成后触发。

**Comment by afc163** [comment]
You have to trigger onChange logic in `handleUpload` by yourself.

**Comment by MillionQW** [comment]
> You have to trigger onChange logic in `handleUpload` by yourself.

Yes, trigger onChange logic in ```handleUpload``` is work, 
but this way can't get ```onChange``` arguments. 
Originally, If the ```onChange``` trigger automatically, the ```onChange``` has a argument : ```{ file: {}, fileList: {}, event: {}}```. 
If I trigger it manually, the argument is ```undefined```.

**Comment by afc163** [comment]
It trigger onChange for the first time when selected the file.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/507615/49057926-b2693900-f23c-11e8-94c9-6578589a2eb0.png">

Then Upload will not trigger more onChange cause beforeUpload returns false that makes upload won't upload file.

**Comment by MillionQW** [comment]
> It triggers onChange for the first time when selected the file.
> 
> <img alt="image" width="474" src="https://user-images.githubusercontent.com/507615/49057926-b2693900-f23c-11e8-94c9-6578589a2eb0.png">
> 
> Then Upload will not trigger more onChange cause beforeUpload returns false that makes upload won't upload file.

Is it mean the ```file``` won't be add attribute ```response``` and ```status``` after upload finish ?

**Comment by MillionQW** [comment]
> Right, because the upload request is sent manaully.

OK！ Thanks for your  reply！

I still have a question, If I want to add attribute ```response``` and ```status```, Whether I should Convert ```File Object``` to plain Object, and replace the object in the fileList ?
look forward to your reply~

**Comment by afc163** [comment]
You can try out if you need it.

**Comment by ztplz** [comment]
@MillionQW  你别研究编译后的代码啊 那是给机器运行的 你有的看不懂正常 你直接fork看源代码就行了  ts还是很容易看的  虽然为了方便用了很多不必要的any

**Comment by MillionQW** [comment]
> @MillionQW 你别研究编译后的代码啊 那是给机器运行的 你有的看不懂正常 你直接fork看源代码就行了 ts还是很容易看的 虽然为了方便用了很多不必要的any

嗯是的，主要是为了方便调试和查找直接翻了 node_modules 里的代码[捂脸]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15561#issuecomment-475108235

**Comment by xgfd** [comment]
@MillionQW 没国内手机号没法在简书上回复……

连续两个括号那段是comma operator expression的用法。(expr1, expr2, ..., exprN)会执行所有的expressions，但是整体的值等于最后一个表达式的值。

(0, fn)(a)相当于fn(a)。如果函数是作为类的方法调用的，classA.fn，直接调用fn中的this会指向classA。(0, classA.fn)的话等同于直接调用fn，this会指向Window（浏览器环境）。

一个简单的例子：
function f() {return this;}
let a = {f};
a.f() === a; // true
(0, a.f)() === a; // false
f() === a; // false
f() === (0, a.f)(); // true

**Comment by MillionQW** [comment]
@xgfd 刚刚看到回复😂，多谢！
