### ISSUE TITLE
Table filterIcon is wrong in React16

### ISSUE THREAD

**Issue by LiHaiX** [ant-design/ant-design#13299]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.1.0

### Environment
chrome69     "react": "16.4.2"，"react-dom": "16.4.2"   

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yq56083z5v)

### Steps to reproduce
Please open the "https://codesandbox.io/s/yq56083z5v", the error is in console
FilterIcon can not use.  
When delete filterIcon , the page is normal.

### What is expected?
I want to use  filterIcon in my project

### What is actually happening?
But filterIcon  is wrong

**Comment by afc163** [comment]
https://ant.design/changelog-cn#3.7.0

**Comment by LiHaiX** [comment]
thank you
