### ISSUE TITLE
i need help with form and 'mapPropsToFields'

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1329]
there is no any example how to use. Can you add it to the docs?

**Comment by benjycui** [comment]
Will update demo later, and you can consult the documentation of rc-form now.

http://react-component.github.io/form/

http://react-component.github.io/form/examples/data-binding-form.html

**Comment by plandem** [comment]
Yep, i tried this one: http://react-component.github.io/form/examples/redux.html

but always getting 'undefined' as value, although if i'm using directly - everything is fine.

not working:
```
class DashboardSettings extends React.Component {
  render() {
    const { actions, config, intl: { formatMessage }, form } = this.props;
    const { isTopicsFetching } = this.state;
    const titleProps = form.getFieldProps('title', { rules: [ { required: true } ]});

    return (
      <Form horizontal>
        <Form.Item label={formatMessage(messages.titleLabel)} labelCol={{span: 3}} wrapperCol={{span: 21}} required>
          <Input type="text" placeholder={formatMessage(messages.titlePlaceholder)} onChange={e => actions.change({ title: e.target.value })} {...titleProps}/>
        </Form.Item>
</Form>
);
}
}

DashboardSettings.propTypes = {
  actions: PropTypes.objectOf(PropTypes.func).isRequired,
  dashboard: PropTypes.instanceOf(Map).isRequired,
  topics: PropTypes.instanceOf(Map).isRequired,
  config: PropTypes.shape({
    title: PropTypes.string,
    icon_id: PropTypes.any,
    topic_id: PropTypes.any,
    srt: PropTypes.any
  }).isRequired
};

const z = Form.create({ mapPropsToFields(props) { return {...props.config} }})(DashboardSettings);
export default connect(sharedSelectors.dashboard, storeActions.dashboard)(injectIntl(z));
```

working:
```
        <Form.Item label={formatMessage(messages.titleLabel)} labelCol={{span: 3}} wrapperCol={{span: 21}} required>
          <Input value={config.title} type="text" placeholder={formatMessage(messages.titlePlaceholder)} onChange={e => actions.change({ title: e.target.value })} {...titleProps}/>
        </Form.Item>
```

**Comment by plandem** [comment]
i mean everything is ok if i'm using like: 
```
<Input value={config.title} 
```

and not working if like this:
```
 const titleProps = form.getFieldProps('title', { rules: [ { required: true } ]});
...
 <Input {...titleProps}
```

**Comment by benjycui** [comment]
The return value of `mapPropsToFields` should be:

```jsx
{
  name: { value: 'Benjy' },
}
```

**Comment by plandem** [comment]
is it possible to add feature like this: if prop's value is not object, then convert it to **{ value }**

E.g.:
```
{
  name: 'Benjy',
}
```

will be transformed into object:
```
{
  name: { value: 'Benjy' },
}
```

**Comment by benjycui** [comment]
I had discussed with @yiminghe , and we thought that we had better not to change this API.

1. Developers will get the following data format from `onFieldsChange`, and this data can be set back to form through `mapPropsToFields`, see: http://react-component.github.io/form/examples/redux.html . 

  ```js
  {
    field: { value, errors...}
  }
  ```

  If we support this format:

  ```js
  {
    field: value,
  }
  ```

  Yep, it's easier to use, but when the fields change and `onFieldsChange` update the data which is stored in Redux(or Owner), developers will be puzzled.

2. It is `mapPropsToFields`, and a field includes not only value, but also errors and other status.

**Comment by plandem** [comment]
i see. ok, i did a own HOC for forms.
