### ISSUE TITLE
TreeSelect calls onSearch after onChange if the input has something in it

### ISSUE THREAD

**Issue by raptoria** [ant-design/ant-design#13293]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version

3.10.9

 

### Environment

Using Chrome on Windows

 

### Reproduction link

[https://codepen.io/Raptoria/pen/gQjGjz?&editors=001](https://codepen.io/Raptoria/pen/gQjGjz?&editors=001)

 

### Steps to reproduce

1. Type '1' into the input box

2. Check one of the child nodes  - both onChange and onSearch get called

 

### What is expected?

only onChange is called, since that was the last action, regardless of whether anything was typed into the input

 

### What is actually happening?

onChange and then onSearch gets called if something was typed into the input

 

---

This bug doesn't exist in V 3.10.8. I don't want onSearch to get called if the user checks something in the dropdown because I'm doing lazy-loading using the input such that it filters the values in the dropdown based on what the user types.

 

3.10.8 workflow --

1. user starts typing , which filters on a list and displays matching values

2. user checks something

3. dropdown stays open and the user can check more options (i'm using the open prop)

3. user clicks out and their selections are "saved"

 

With 3.10.9 -

1. user starts typing , which filters on a list and displays matching values

2. user checks something

3. the dropdown clears unexpectedly because onSearch gets called after onChange, so the user can no longer make more selections that were filtered based on what they typed in because the onSearch value is blank

**Comment by zombieJ** [comment]
Yes. This is new added feature.

We released `treeExpandedKeys` in recent version. User can control popup tree by set expandedKeys. But when filter input, it miss the event for user reset expandedKeys after item selected. So we adjust `onSearch` trigger logic (it is always triggered when filter changed).

If you want to ignore this, you can check the filter value:
```jsx
onSearch = (str) => {
  if (!str) return;

  // Your logic here
}
```
