### ISSUE TITLE
form的demo中存在bug，只输入每行第一个值，点击Search按钮会导致错位

### ISSUE THREAD

**Issue by yisufei** [ant-design/ant-design#13298]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
Win/Chrome70

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rlm2ly0pm4)

### Steps to reproduce
1、在Field 0中输入任意值
2、点击Search按钮

### What is expected?
没有错位，有正确的提示信息

### What is actually happening?
有错位

**Comment by yisufei** [comment]
分辨率为1920*1080时有此问题，分辨率为1680*1050时没有这个问题

**Comment by yisufei** [comment]
![image](https://user-images.githubusercontent.com/7361415/49066410-f881c500-f25b-11e8-8352-af9b68a0dfe7.png)
分辨率为1920x1080，缩放为100%时没有问题
![image](https://user-images.githubusercontent.com/7361415/49066444-17805700-f25c-11e8-9980-02d27a24d882.png)
分辨率为1920x1080，缩放为125%时有问题
![image](https://user-images.githubusercontent.com/7361415/49066480-3a127000-f25c-11e8-875a-efb814c7deb0.png)
具体表现为行高变成了63.2而不是63

**Comment by afc163** [comment]
目前无法完美解决这个问题，建议不要缩放。
