### ISSUE TITLE
CheckBoxGroup在form里面使用setFieldsValue无效

### ISSUE THREAD

**Issue by cheekey** [ant-design/ant-design#13306]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
Chrome/70.0.3538.110 Safari/537.36

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ym3oz2rk31)

### Steps to reproduce
有个单选功能, 又需要cancel的功能, 所以选用了checkbox, 动态设置数据。但是在form里面, 用setFieldsValue无效。

### What is expected?
CheckBoxGroup在form里面使用setFieldsValue有效

### What is actually happening?
CheckBoxGroup在form里面使用setFieldsValue无效

**Comment by hileix** [comment]
When you use the `Form component` to manage `form state`,it's best not set `form state` by yourself.In your case, you can try [this](https://codesandbox.io/s/72xo23zqr0).
