### ISSUE TITLE
Table 表格用scroll之后出现列错位

### ISSUE THREAD

**Issue by llsldwy** [ant-design/ant-design#13304]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
系统版本mac和win，浏览器，chrome和火狐，react  16.6.3版本，antd 3.10.8版本

### Reproduction link
[https://codepen.io/llsldwy/pen/PxBgzq?&editors=001](https://codepen.io/llsldwy/pen/PxBgzq?&editors=001)

### Steps to reproduce
antd里的table表格，增加scroll属性之后，列出现错位，如果去掉之后，变得正常

### What is expected?
增加scroll之后应该列跟header对齐

### What is actually happening?
增加scroll之后 列跟header不能对齐
![image](https://user-images.githubusercontent.com/6800117/49071991-2a9a2380-f26a-11e8-9ba7-b3d0f33b61ca.png)

**Comment by afc163** [comment]
<img width="666" alt="image" src="https://user-images.githubusercontent.com/507615/49072605-8a44fe80-f26b-11e8-8829-4d6a40b9f3dc.png">

**Comment by wangsijie** [comment]
所有列均指定width，并已经设定scroll.x为正确值，也会出现这个问题，在早期版本(3.1)中并没有这个问题

**Comment by afc163** [comment]
@wangsijie https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by Mr-jiangzhiguo** [comment]
> 所有列均指定width，并已经设定scroll.x为正确值，也会出现这个问题，在早期版本(3.1)中并没有这个问题

我也遇到了,升级最新本,3.13.5后就出现错位,甚至td里面是图片的都不显示,td没有被图片自动撑开,
原来的3.10.x就没问题
