### ISSUE TITLE
Table表格     可编辑行例子中出现bug

### ISSUE THREAD

**Issue by GreatPersonal** [ant-design/ant-design#13301]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
window/chrome/react16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0m05zqw7yv)

### Steps to reproduce
columns中operation中加入fixed属性,点击edit,修改input内容，点击save，数据提交为空

### What is expected?
点击save保存更新数据

### What is actually happening?
点击save提交数据为空

**Comment by afc163** [comment]
这个例子不支持 fixed columns。

**Comment by zombieJ** [comment]
Update demo on this #15475
