### ISSUE TITLE
 new-issue.ant.design Modal

### ISSUE THREAD

**Issue by suciy** [ant-design/ant-design#13305]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
Chrome70.0.3538.102

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
点击按钮触发模态框，关闭模态框后，点击回车键或者空格键，模态框会出现
When you show a modal，close it, and then, you clicked the keyboard: enter or backspace, the modal will show again.

### What is expected?
只有按钮或者触发点能够触发模态框的显示隐藏
Only when you clicked the button or the target, the modal will show or hide.

### What is actually happening?
点击回车键或者空格键，模态框会出现
 clicked the keyboard: enter or backspace, the modal will show again.

**Comment by afc163** [comment]
It is by designed, trigger button will stay focused state after Modal is closed.
