### ISSUE TITLE
官网样例个人信息按钮在某些情况下点击失效

### ISSUE THREAD

**Issue by maxlzc** [ant-design/ant-design#13313]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
chrome 手机浏览器 70.0.0.3538.75

### Reproduction link
[https://preview.pro.ant.design](https://preview.pro.ant.design)

### Steps to reproduce
点击个人信息那个头像(那个有个人中心，个人设置的下拉框)，再点击网页空白处且不引起网页重新绚烂情况下，个人信息弹出下拉列表消失，再次点击个人信息按钮，按钮颜色变深，下拉框不出现。【必现】

### What is expected?
希望点击按钮后如果网页不重新渲染按钮也能有效。

### What is actually happening?
按钮无效

**Comment by zombieJ** [comment]
Hi @maxlzc,
Please create issue to https://github.com/ant-design/ant-design-pro/issues instead. Thanks.

PS: I can't reproduce this, maybe snapshot is better for track.
