### ISSUE TITLE
Add the possibility to edit a tag in multiple select

### ISSUE THREAD

**Issue by florian-bd** [ant-design/ant-design#13310]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As a user, I have mistyped a value in the multiple select, and I want to be able to correct it.
Today I have to remove the tag and type a new tag with the correct value.
It would be nice to be able to edit the tag.

### What does the proposed API look like?
When clicking on a tag, set the cursor and allow editing directly.

**Comment by zombieJ** [comment]
Thanks for feedback.
Let tag editable makes too many interactive action in small place. We may not implement this feature officially.
