### ISSUE TITLE
 TypeError: Cannot read property 'offsetWidth' of null     at Avatar.render (index.js?a567:154)

### ISSUE THREAD

**Issue by cornwang** [ant-design/ant-design#13315]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.1

### Environment
win7 系统，谷歌浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j24664ny19)

### Steps to reproduce
1.页面渲染后，点删除，本地环境会白屏，并报错

### What is expected?
删除成功，页面不白屏

### What is actually happening?
 报 left: 'calc(50% - '   Math.round(childrenNode.offsetWidth / 2)   'px)'

---
·

**Comment by ztplz** [comment]
Could you provide a git repository for this problem? Online demo can't reproduce what you said.
