### ISSUE TITLE
Mention.toString convert "@abc" to "undefinedabc"

### ISSUE THREAD

**Issue by totoSalad** [ant-design/ant-design#13319]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n99xp51274)

### Steps to reproduce
input @, then use mouse select "benjycui"

### What is expected?
output "@benjycui"

### What is actually happening?
output "undefinedbenjycui"

---
Antd v3.10.7 also has this bug. This case appears with 20% possibility，please be patient to produce. Thanks~

**Comment by totoSalad** [comment]
![nov-28-2018 11-41-40](https://user-images.githubusercontent.com/8340876/49127543-a9429f80-f302-11e8-9da7-16550e8c94a8.gif)

**Comment by ztplz** [comment]
What's your OS?

**Comment by totoSalad** [comment]
mac high sierra 10.13.6

**Comment by zombieJ** [comment]
Reproduced, click the item quickly makes `undefined`.

**Comment by zombieJ** [comment]
OPS.
@ztplz , sorry for unnoticed you are handling this...

**Comment by ztplz** [comment]
@zombieJ Just an unconscious operation. In fact, I can’t reproduce this bug.
