### ISSUE TITLE
Fixed row high misalignment when displaying table data

### ISSUE THREAD

**Issue by zhl666** [ant-design/ant-design#13316]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
all

### Environment
win chrome firefox

### Reproduction link
[https://codepen.io/anon/pen/vQzvNb?editors=0010](https://codepen.io/anon/pen/vQzvNb?editors=0010)

### Steps to reproduce
When the tree structure data is displayed, when there is a fixed column, the contents of the fixed column are broken, and when the horizontal scroll bar appears, the line height is misaligned.

### What is expected?
The row height of the fixed column is consistent with the original row height

### What is actually happening?
The row height of the fixed column is inconsistent with the original row height

---
The above version cannot be selected，this bug  in the latest version

**Comment by afc163** [comment]
```

const columns = [{
  title: 'Name',
  dataIndex: 'name',
  key: 'name',
  fixed: true,
- width: 100
+ width: 200
}, {
```

https://codepen.io/anon/pen/yQxGRP

**Comment by zhl666** [comment]
This is to solve the problem by modifying the width of the name column to ensure that the content does not wrap, but the content of this column may be longer in the actual application, and cannot be guaranteed to be displayed in one line.
