### ISSUE TITLE
treeSelect autoClearSearchValue Bug

### ISSUE THREAD

**Issue by sysuzero** [ant-design/ant-design#13328]
如图:
![image](https://user-images.githubusercontent.com/21362533/49143017-0ce5c080-f335-11e8-8e19-685377419fbc.png)
设置autoClearSearchValue为false后,在搜索条件下勾选,父级没有变成勾选状态.
期待:父级变成有勾选
[![Edit vj765v77kl](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vj765v77kl)

**Comment by zombieJ** [comment]
Node2 本身还有其他 2 个子节点没有被勾选，filter 下看不到罢了：
<img width="315" alt="2018-11-28 5 50 41" src="https://user-images.githubusercontent.com/5378891/49143526-2f2c0e00-f336-11e8-8b1f-eed476ab43eb.png">

**Comment by sysuzero** [comment]
![image](https://user-images.githubusercontent.com/21362533/49143681-84681f80-f336-11e8-8081-c3ce7a16c723.png)
![image](https://user-images.githubusercontent.com/21362533/49143694-8af69700-f336-11e8-9fe0-408a7ca1c581.png)
勾选了一个,期待应该也是变成这个样子吧

**Comment by sysuzero** [comment]
> Node2 本身还有其他 2 个子节点没有被勾选，filter 下看不到罢了：
> <img alt="2018-11-28 5 50 41" width="315" src="https://user-images.githubusercontent.com/5378891/49143526-2f2c0e00-f336-11e8-8b1f-eed476ab43eb.png">

而且清除搜索条件后,重新输入搜索条件,这个父级也是

![](https://user-images.githubusercontent.com/21362533/49143694-8af69700-f336-11e8-9fe0-408a7ca1c581.png)
