### ISSUE TITLE
Antd 2.x doc has a spelling mistabke

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design#13324]
In Form api doc:

![default](https://user-images.githubusercontent.com/16114101/49140317-f9cff200-f32e-11e8-9f6b-5a7fd7f6a0f7.PNG)

getFieldsvalue => getFieldsValue

**Comment by zombieJ** [comment]
The prop name is typo and used in v2. We fixed in v3

**Comment by kwzm** [comment]
@zombieJ I see, 3Q!
