### ISSUE TITLE
穿梭框禁用时搜索框依然可用

### ISSUE THREAD

**Issue by cipchk** [ant-design/ant-design#13330]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
Chrome

### Reproduction link
[https://codepen.io/cipchk/pen/PxyPvL?editors=0010](https://codepen.io/cipchk/pen/PxyPvL?editors=0010)

是如此设计呢？还是BUG？

**Comment by zombieJ** [comment]
Nice catch!
