### ISSUE TITLE
Button renders anchor even if href is set `undefined`

### ISSUE THREAD

**Issue by harunurhan** [ant-design/ant-design#13337]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
All

### Reproduction link
[https://codepen.io/anon/pen/MzPOad](https://codepen.io/anon/pen/MzPOad)

### Steps to reproduce
- set button `href` prop undefined <Button href={undefined}>

### What is expected?
render a regular `<button>`

### What is actually happening?
renders `<a>`

---
So, I have a custom component that has button and sets all the button props directly because sometimes I want my component to render an `<a>` button, but sometimes `<button>`.  

Looks like `<Button href={props.href} onClick={props.onClick}...`. Since `in` operator used https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L210, it is always an `anchor` even if `href` is undefined.

I think this should be `!= null` or at least `!== undefined`.

**Comment by harunurhan** [comment]
I could do a PR, if you think this is a bug.

**Comment by ycjcl868** [comment]
This is [ant-design-mobile](https://github.com/ant-design/ant-design-mobile) bug, you can do the PR in antd-mobile.

**Comment by afc163** [comment]
https://codepen.io/anon/pen/MzPOad is a antd mobile demo.

**Comment by harunurhan** [comment]
@afc163 that is another bug in another repository, and is not the reason of this bug appearing here. I do not know why you closed #13357 and tag this issue "invalid" and later you committed almost identical changes to my PR (https://github.com/ant-design/ant-design/commit/35585a6d07166b57a3839ab0a10607f0cfa9c5be) to fix the bug.

From an open source project, I would expect a PR review, or more valid reason why it happened that way. This is not how you build a community around your project and encourage them to contribute.
