### ISSUE TITLE
Notification Component display issue with long messages| Notification 对于长句显示问题

### ISSUE THREAD

**Issue by yixiaol-m** [ant-design/ant-design#13339]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
chrome Version 70.0.3538.102

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z2ok9loy8m)

### Steps to reproduce
A long message is not properly wrapped around if the message does not have spaces. 当长句子中没有空格或者横杠的时候，Notification不会正确的换行。
Example message:
"This.is.the.content.of.the.notification.This.is.the.content.of.the.notification.This.is.the.content.of.the.notification. "
This type of messages are very common in our use case where the UI is proxying requests to backend Java services. Java error code with class names have long dot messages like above. 我们的应用需要界面向后端Java服务互动，在JAVA服务出错时，此类长句子非常常见。
Our current workaround is to break the message before passing to notification component, but that does not work well if people's browser are zoomed. 为了完整显示notification，目前我们在传message前按照字符数量加入空格，但是此番做法在用户的浏览器不是100%zoom的时候显示会有多余空格。

### What is expected?
Message should wrap around on characters such as . , [ { ( ` and so on | Notification中Message换行时应该参照更多的标点

### What is actually happening?
Message only wrap around on characters for white space or - Notification中Message换行目前只参照空格或者横杠

**Comment by afc163** [comment]
https://codesandbox.io/s/4x8p0pvnz0
