### ISSUE TITLE
Modal. Confirm content in the use of internationalization,The second time you open Modal, Modal bottom button text becomes the default language

### ISSUE THREAD

**Issue by Tgoing** [ant-design/ant-design#13344]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.9.2

### Environment
win10, chrome 版本 70.0.3538.110（正式版本） （64 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/42p68nmk0x)

### Steps to reproduce
Switch to Chinese, open modal and then close it, and then open it again

### What is expected?
Internationalization in content is consistent with modal buttons

### What is actually happening?
After the second time when I open modal, the bottom button text of modal becomes the default

---
Internationalized components need to be used in modal.confirm

**Comment by Veveue** [comment]
https://codesandbox.io/s/lyj10qwlxq 
@afc163 非BUG 还是他用法的问题

**Comment by Veveue** [comment]
看了下是`LocaleProvider`的问题， 是动态添加删除导致的
