### ISSUE TITLE
Form表单无法正常效验

### ISSUE THREAD

**Issue by fangkyi03** [ant-design/ant-design#13355]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
mac 10.14.1 chrome 70.0.3538.77

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p2pkyrqn4x)

### Steps to reproduce
如果你先点击按钮的时候 错误是可以正常体现的 但是如果先点击时间选择器 选择一个时间 然后点击按钮 错误不能正常体型 不止这个时间选择器有这个问题 upload select 等都有问题 唯独input没关系

### What is expected?
希望能根据当前选中项进行必填项提醒

### What is actually happening?
点击确认按钮以后 无法获取到对应组件的error数据 直接提示正常 导致数据录入出错

**Comment by fangkyi03** [comment]
createBaseForm.js
问题出在这个文件的这行代码里面
![image](https://user-images.githubusercontent.com/30390014/49237243-c5e0f380-f438-11e8-9cbc-a29e6aeffca9.png)
这里其实我明白写这句代码的意思 就是进行一下脏检查尽量减少不必要的刷新以及处理 也就是因为这边这行代码的关系 导致将原本有问题的组件脏检查给过滤掉了 导致当你调用validateFields的时候error直接变成null 然后我这边以为表单上面已经没有错误的表单了 直接就导致后台崩溃 因为其实我页面上有100个组件的数据 其实只传了我刚才改变的那一个值 这里去掉就可以了 麻烦还是改一下吧

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/49238064-9c28cc00-f43a-11e8-8a9c-77639b17ff7d.png)
其次这句代码的关系 其实会导致整个表单页面重复刷新多次 同时 对应的onFieldsChange也会被重复调用多次 这样的无疑会增加react自身diff的损耗

**Comment by wanliyunyan** [comment]
我是因为createform方法中添加onFieldsChange方法，upload组件上传的文件在validateFieldsAndScroll校验的时候拿不到value中的对应upload上传的文件， @fangkyi03 ，哥们，你是这原因吗，要是不写onFieldsChange，就可以在value中拿到 文件，但是要是不加onFieldsChange，怎么保存到redux中啊?

**Comment by fangkyi03** [comment]
有人能处理一下吗

**Comment by zombieJ** [comment]
@fangkyi03 ，逻辑比较复杂。还在想如何处理，如果着急的话，先用 onValuesChange 和 initialValue 顶一下。
