### ISSUE TITLE
Button、Popconfirm气泡确认框没有阻止默认冒泡

### ISSUE THREAD

**Issue by YoungHearts** [ant-design/ant-design#13351]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
测试过的环境：mac10.13.5、window10等系统上的谷歌70.0.3538.110

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1rkl2lz244)

### Steps to reproduce
Popconfirm包裹的Button，即使Button已经disabled，还是会触发Popconfirm的点击事件

### What is expected?
Popconfirm包裹的Button，不能冒泡触发Popconfirm事件

### What is actually happening?
Popconfirm包裹的Button，能冒泡触发Popconfirm事件

**Comment by afc163** [comment]
这是合理的，建议自行判断一下。也会有需求针对 disabled 的 button 展示 Tooltip 或者 Popconfirm 的。

**Comment by YoungHearts** [comment]
> 这是合理的，建议自行判断一下。也会有需求针对 disabled 的 button 展示 Tooltip 或者 Popconfirm 的。

为啥antd的3.4版本都是不可被冒泡点击的，这次更新3.10.8后就可以点击了哟~，我觉的按钮已经disabled确实不应该能点击呀

**Comment by CTheMyth** [comment]
> @YoungHearts 这种场景需求是存在的，举个例子：
> <img alt="2018-11-30 10 17 00" width="350" src="https://user-images.githubusercontent.com/5378891/49264424-2009a500-f489-11e8-91d6-625c96c4a0d7.png">
是否能在popconfirm上加上disabled属性呢，感觉这样需求就都能满足了

**Comment by zombieJ** [comment]
> > @zombieJ
> > 是否能在popconfirm上加上disabled属性呢，感觉这样需求就都能满足了

https://ant.design/components/popconfirm-cn/#components-popconfirm-demo-dynamic-trigger
