### ISSUE TITLE
Modal设置了destroyOnClose，下次打开，子元素依然没有被销毁~

### ISSUE THREAD

**Issue by MuJinYan** [ant-design/ant-design#13354]
<Modal
        title="添加模板页面"
        centered
        confirmLoading={props.confirmLoading}
        visible={props.visible}
        onOk={() => this.onSubmit()}
        onCancel={() => props.onCancel()}
        destroyOnClose
      >
        <Row className={styles.row}>
          <Col span={5}>页面名称</Col>
          <Col span={16} offset={2}>
            <Input
              value={name}
              placeholder="请输入活动页面的名称 例如：鲜花"
              onChange={e => this.setState({ name: R.trim(e.target.value) })}
            />
          </Col>
        </Row>
        <Row className={styles.row}>
          <Col span={5}>页面类型</Col>
          <Col span={16} offset={2}>
            <Select
              showSearch
              style={{ width: 200 }}
              placeholder="请选择组件类型"
              optionFilterProp="children"
              onChange={value => this.setState({ theme: value })}
            >
              <Select.Option value="home">首页</Select.Option>
              <Select.Option value="generalMerchandise">百货</Select.Option>
            </Select>
          </Col>
        </Row>
        {!R.isEmpty(errorInfo) && (
          <Alert
            message={errorInfo}
            type="error"
            closable
            afterClose={() => this.setState({ errorInfo: '' })}
          />
        )}
      </Modal>

设置了destroyOnClose，可以在打开，所有的状态值依然存在~

**Comment by 3110160** [comment]
确实是

**Comment by 3110160** [comment]
bug

**Comment by hedy0111** [comment]
> Hello @MuJinYan, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](http://new-issue.ant.design?repo=ant-design) to create an issue, thank you!
> 
> 你好 @MuJinYan，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](http://new-issue.ant.design?repo=ant-design) 来创建 issue 以方便我们定位错误。谢谢配合！



> ```
> <Modal
>         title="添加模板页面"
>         centered
>         confirmLoading={props.confirmLoading}
>         visible={props.visible}
>         onOk={() => this.onSubmit()}
>         onCancel={() => props.onCancel()}
>         destroyOnClose
>       >
>         <Row className={styles.row}>
>           <Col span={5}>页面名称</Col>
>           <Col span={16} offset={2}>
>             <Input
>               value={name}
>               placeholder="请输入活动页面的名称 例如：鲜花"
>               onChange={e => this.setState({ name: R.trim(e.target.value) })}
>             />
>           </Col>
>         </Row>
>         <Row className={styles.row}>
>           <Col span={5}>页面类型</Col>
>           <Col span={16} offset={2}>
>             <Select
>               showSearch
>               style={{ width: 200 }}
>               placeholder="请选择组件类型"
>               optionFilterProp="children"
>               onChange={value => this.setState({ theme: value })}
>             >
>               <Select.Option value="home">首页</Select.Option>
>               <Select.Option value="generalMerchandise">百货</Select.Option>
>             </Select>
>           </Col>
>         </Row>
>         {!R.isEmpty(errorInfo) && (
>           <Alert
>             message={errorInfo}
>             type="error"
>             closable
>             afterClose={() => this.setState({ errorInfo: '' })}
>           />
>         )}
>       </Modal>
> ```
> 
> 设置了destroyOnClose，重新打开，所有的状态值依然存在~
> antd: v3.10.1
> node: v8.12.0
> 系统: mac os 10.14

确实是个bug,有的地方还挺影响的
