### ISSUE TITLE
getFieldDecorator 里定义initialValue值，select的placeholder就不会显示

### ISSUE THREAD

**Issue by tianxiaobao** [ant-design/ant-design#13353]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
mac os系统,chrome浏览器,AntD 版本3.10.9

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://vn82x1jkm0.codesandbox.io/)

### Steps to reproduce
表单验证结合select的动态搜索功能，select的placeholder失效。
只要getFieldDecorator 里定义initialValue值，不论这个值存不存在，select的placeholder就不会显示

### What is expected?
当getFieldDecorator 里定义initialValue值为空时，select显示placeholder

### What is actually happening?
当getFieldDecorator 里定义initialValue值为空时，select不显示placeholder

**Comment by zombieJ** [comment]
Select 组件是支持设置不存在的值的，这是为了方便开发者做异步加载的时候节省额外的代码逻辑。所以当你设置 initialValue 的时候，这个“不存在的”值是被 Select 接收的。因而就不会展示 placeholder 啦~

PS：如果希望展示 placeholder，可以参考 @gonenoob 的回复哈。
