### ISSUE TITLE
Table Component 中使用 react-dnd 报错

### ISSUE THREAD

**Issue by 15531400827** [ant-design/ant-design#13367]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
window7专业版、chrome 69.0.3497.100、最新版antd

### Reproduction link
[https://codepen.io/pen/?&editors=001](https://codepen.io/pen/?&editors=001)

### Steps to reproduce
链接是官网中的例子，但是现在似乎报错，按例子中使用正常， 当改变columns中任何一项的fixed:'right'(既列固定)时出现报错

### What is expected?
添加columns固定不出现报错

### What is actually happening?
添加固定columns后出现报错

**Comment by afc163** [comment]
react-dnd 和 fixed 现在不能一起使用。

**Comment by 15531400827** [comment]
@afc163 那这个功能有没有计划支持呢

**Comment by afc163** [comment]
比较复杂，没有精力搞，欢迎社区贡献。
