### ISSUE TITLE
TreeSelect设置treeCheckStrictly: true时，搜索后选中节点会清除掉之前选中的不在搜索结果中的节点

### ISSUE THREAD

**Issue by lucklove** [ant-design/ant-design#13365]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
mac, Chrome

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/609c972b](https://riddle.alibaba-inc.com/riddles/609c972b)

### Steps to reproduce
1. 进入重现链接，选中Node 2
2. 搜索0-0，此时Node 2不在搜索结果中
3. 选中搜索结果中的Node 1

### What is expected?
Node 1和Node 2均被选中

### What is actually happening?
只选中了Node 1

**Comment by lucklove** [comment]
@zombieJ

**Comment by zombieJ** [comment]
Out of corp reproduce: https://codesandbox.io/s/81k0xo6572
