### ISSUE TITLE
在form表单里使用Select的labelInvalue属性时，如何设置palaceholder？

### ISSUE THREAD

**Issue by wangchong19940101** [ant-design/ant-design#13366]
![image](https://user-images.githubusercontent.com/30942709/49266499-6ebb3d00-f491-11e8-8662-5629dca0d9fd.png)
页面渲染成下面这样
![image](https://user-images.githubusercontent.com/30942709/49266535-87c3ee00-f491-11e8-8f14-5933f9fbbcde.png)
我应该如何操作呢？请大家指教。

**Comment by TonyaQi** [comment]
请问最后怎么解决的

**Comment by yyz841875845** [comment]
设置 为undefined,
