### ISSUE TITLE
Tabs: update state when component is unmounted 组件在unmounted的时候更新state

### ISSUE THREAD

**Issue by zheng-chuang** [ant-design/ant-design#13361]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
macOS, chrome  70.0.3538.110, node 10.8.0,  npm 6.2.0, yarn 1.9.4

### Reproduction link
[https://github.com/zheng-chuang/antd-tabs-issue](https://github.com/zheng-chuang/antd-tabs-issue)

### 安装
```shell
git clone https://github.com/zheng-chuang/antd-tabs-issue.git

cd antd-tabs-issue
# 安装依赖
yarn 
# or
npm i
# 启动
yarn start
# or
npm start 
```

打开控制台，在两个页面直接跳转就可以看到问题

![error](https://raw.githubusercontent.com/zheng-chuang/antd-tabs-issue/master/img/WX20181129-230928.png)

### What is expected?
do not update state when component is unmounted

### What is actually happening?
component update state when it is unmounted

**Comment by zombieJ** [comment]
Nice catch~

**Comment by zombieJ** [comment]
Fixed. Pls reinstall node_modules: https://codesandbox.io/s/5x25wm28v4

**Comment by zheng-chuang** [comment]
thx
