### ISSUE TITLE
DatePicker的suffixIcon自定义的选择框后缀图标 属性放在项目里不生效

### ISSUE THREAD

**Issue by kanxuehe** [ant-design/ant-design#13364]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
改变图标

### What does the proposed API look like?
可以改变图标

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

**Comment by tiyunchen** [comment]
一样

**Comment by tiyunchen** [comment]
官方代码就可以，放到我代码里就不行
