### ISSUE TITLE
ie11 报错内容：Multiple definitions of a property not allowed in strict mode

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design#13374]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
ie11浏览器，win10系统，ant-desidn-pro 2.0.0-beta.1版本

### Reproduction link
https://codesandbox.io/s/yj236z9qpv

### Steps to reproduce
谷歌火狐edge都可以正常显示，只有ie11打开白屏。

### What is expected?
期望正常显示

### What is actually happening?
白屏

**Comment by liyue118** [comment]
补充：公司有网络限制，我把官方文档提供解决ie兼容的几个https的js代码写到本地，会报语法错误以及rollbar undefined；

**Comment by liyue118** [comment]
> Please provide a GitHub repo cause codesandbox don't support IE11.

https://github.com/liyue118/ie11.git

**Comment by zombieJ** [comment]
hi @liyue118 ,
clone 下来编译报错了，说有几个 Module 不存在。能看看吗？~

**Comment by zombieJ** [comment]
@liyue118 编译通过了，首页是白屏。我需要看哪个 router 地址？

**Comment by afc163** [comment]
@liyue118 

请给出傻瓜式的 123 重现步骤。

**Comment by liyue118** [comment]
> @liyue118 编译通过了，首页是白屏。我需要看哪个 router 地址？

本地路径例如  localhost:8000/#/user

路由后面加user即可

**Comment by liyue118** [comment]
@zombieJ  dear,请问是什么原因呢？

**Comment by zombieJ** [comment]
IE 9 不支持 `const`，babel 转译一下：
<img width="265" alt="2018-12-06 11 14 47" src="https://user-images.githubusercontent.com/5378891/49559038-32cc2000-f948-11e8-8816-c7f3e665bcf2.png">

**Comment by liyue118** [comment]
> IE 9 不支持 `const`，babel 转译一下：
> <img alt="2018-12-06 11 14 47" width="265" src="https://user-images.githubusercontent.com/5378891/49559038-32cc2000-f948-11e8-8816-c7f3e665bcf2.png">

请问改哪个文件

**Comment by zombieJ** [comment]
> 请问改哪个文件

参考：[uglify 压缩报错问题及 es5-imcompatible-versions](https://github.com/sorrycc/blog/issues/68)

**Comment by liyue118** [comment]
> > 请问改哪个文件
> 
> 参考：[uglify 压缩报错问题及 es5-imcompatible-versions](https://github.com/sorrycc/blog/issues/68)

我装了umi,webpack添加了es5ImcompatibleVersions: true,build之后还是报原来的错。是需要改文件吗？

**Comment by zombieJ** [comment]
这个配置了吗？https://umijs.org/zh/config/#targets
