### ISSUE TITLE
InputNumber 有默认值，点右边的增减都不好用，输入值后那个增减按钮才好用

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design#1337]
InputNumber 有默认值，点右边的增减都不好用，输入值后那个增减按钮才好用。
这个组件不能用 rules: [
                                    {required: true, message: '请输入级数！'}
                                ] 这个规则？

栗子：
http://jsfiddle.net/wangdao/dnnqo1Ln/2/

**Comment by afc163** [comment]
http://jsfiddle.net/dnnqo1Ln/3/

1. use initialValue in Form. https://github.com/ant-design/ant-design/issues/1327
2. default rule type is `string`, change it to `number`.
