### ISSUE TITLE
DatePicker默认安装moment并依赖它，antd后面版本能否将moment更换为dayjs这种体积小的库？

### ISSUE THREAD

**Issue by Vibing** [ant-design/ant-design#13377]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

打包后查看bundle图表，moment实在太大，但是又不敢直接使用dayjs替换，毕竟可能出现隐藏bug。

希望能使用其他小体积库，比如dayjs

**Comment by sam-dingkang** [comment]
@Vibing 
**moment.js确实比较大，主要是它支持i8n，所以它的local文件比较大，如果你的如果项目不要求支持多种语言，可以在webpack.config.js配置这个插件去掉local,减少打包体积。
new webpack.ContextReplacementPlugin(
  /moment[\/\\]locale$/,
  /de|fr|hu/
);
另外还有一种方法就是将moment这种比较大的库单独抽出来用cdn引入，也可以减少bundle体积。替换dayjs可能性不大，对用户影响太大

**Comment by ycjcl868** [comment]
external 出来，然后 cdn 引入。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10437#issuecomment-433612522

**Comment by Vibing** [comment]
@sam-dingkang 谢谢 这样做是能减少一些体积，目前就使用这种方案

**Comment by xxyuk** [comment]
@Vibing @sam-dingkang  Replace Moment.js in Ant Design (Antd) with Day.js https://github.com/iamkun/dayjs/issues/529
