### ISSUE TITLE
是否可以不更新版本的情况下，引入新版本新添加的组件？

### ISSUE THREAD

**Issue by Irislm** [ant-design/ant-design#13375]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
项目开发使用版本3.5.*  不想因为升级版本影响项目的稳定性，同时又想使用ant-design新添加的组件skeleton，是否有什么方法可以做到？

### What does the proposed API look like?
可以提供类似react-lifecycles-compat这样的polyfill，可以在不更新react版本(<16.2)的情况下使用新的生命周期getDerivedStateFromProps，或者有更好的办法

**Comment by afc163** [comment]
Can't make it.

**Comment by Irislm** [comment]
Why?

**Comment by Irislm** [comment]
Could you tell me why?  Or I can import a single component like react-component do. If still can’t, I want to know if ant-design will support it or not in the future. Thanks!
