### ISSUE TITLE
How to set initialValue with nested fields?

### ISSUE THREAD

**Issue by nodkrot** [ant-design/ant-design#13385]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
react 16, mac, chrome latest

### Steps to reproduce
```js
// in render method
getFieldDecorator('items', {
     initialValue: [{ item: 1, text: 'foo' }, { item: 2, text: 'bar' }]
})

const items = getFieldValue('items')

const renderedItems = items.map((item, i) => {
   return <FormItem key={i}>
     {getFieldDecorator(`items[${i}].text`, {
        initialValue: get(item, 'text'),
        rules: [{ required: true, message: 'Something went wrong' }],
     })(<TextArea autosize={{ minRows: 2, maxRows: 4 }} placeholder={'Enter something'} />)}
   </FormItem>
})
```

```js
// in some method on the component that reorders the items
const items = getFieldValue('items').slice()

setFieldsValue({ items: reorder(items) })
```

### What is expected?
Expected to work like a basic field (needs to update the order and values of nested fields)

### What is actually happening?
Getting this: Warning: One field name cannot be part of another, e.g. `a` and `a.b`. Nothing happens after

---
Related:
This issue doesn't seem to explain https://github.com/ant-design/ant-design/issues/9231
May be similar https://github.com/react-component/form/pull/48#issuecomment-371405549

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8806
