### ISSUE TITLE
iconfont.js   

### ISSUE THREAD

**Issue by qihong1983** [ant-design/ant-design#13399]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
react antd

### Reproduction link
[http://antd.design](http://antd.design)

### Steps to reproduce
npm run build

### What is expected?
正常 始用

### What is actually happening?
 Line 1:      Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

**Comment by yesmeck** [comment]
It's absolutely not an issue of antd.
