### ISSUE TITLE
弹出卡片的动画方案更新

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1339]
目前的弹出卡片动画是按照卡片位置 `placement` 来指定的。目前有两个问题：

1. 只有四个方向的动画，缺少 `zoom-up-right` 这些角落的动画。
2. 如果发生 adjustOverflow，动画方向是错误的。

为解决以上问题，并且避免过多的代码配置，改造如下：

动画统一采用 `zoom`，并在定位发生（onPopupAlign）时，依据弹层的绝对位置和触发点的绝对位置，动态计算 `transform-origin` 来完成弹层动画。

涉及组件：

- [x] Tooltip
- [x] Popover
- [x] Popconfirm

---

ref: https://github.com/react-component/trigger/pull/8/

**Comment by jljsj33** [comment]
动画统一采用 `zoom-big`
