### ISSUE TITLE
组件动画改进

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#134]
需要修改动画的组件：

- [x] modal
- [x] dropdown
- [x] select
- [x] ~~datepicker ?~~
- [x] ~~collapse~~

需要补充动画的组件：

- [x] menu
- [x] tag
- [x] alert
- [x] upload
- [x] validation
- [x] slider 上面的气泡
- [x] tree 展开缩放需要动画

**Comment by jljsj33** [comment]
slider中心点有问题。。。下周看下rc的

**Comment by yiminghe** [comment]
+ tree

**Comment by afc163** [comment]
tree 升到 0.15.0 后，原来的演示都坏掉了。

**Comment by yiminghe** [comment]
重新 tnpm install tree 好的

**Comment by afc163** [comment]
tree 一上来默认收起时，有一个多余的动画。
