### ISSUE TITLE
Drawer set getContainer don't show

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#13407]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
chrome latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8lzxv7np5l)

### Steps to reproduce
```js
<div
          ref={this.container}
          style={{ width: 300, height: 300, background: "#f00" }}
        />
        <Drawer
          title="Basic Drawer"
          placement="right"
          closable={false}
          getContainer={this.container.current}
          onClose={this.onClose}
          visible={this.state.visible}
        >
          <p>Some contents...</p>
          <p>Some contents...</p>
          <p>Some contents...</p>
        </Drawer>
```

### What is expected?
don't show

### What is actually happening?
show

**Comment by jljsj33** [comment]
用 `getContainer={() => this.container.current}`,  this.container.current 的话刚 render 时是 null, didMount 后才是 htmlElement,

**Comment by hengkx** [comment]
@jljsj33 Thanks .当我点击按钮的时候state已经发生了变化 第二次 render 已经有值了，实际 第二次`render` 存在值的, 是没有 监听`getContainer`的变化吗？
![image](https://user-images.githubusercontent.com/8358236/49423587-f5925180-f7d2-11e8-8438-ee69e3f61feb.png)
[https://codesandbox.io/s/olxolmqwn5](https://codesandbox.io/s/olxolmqwn5)

**Comment by jljsj33** [comment]
没有监听，，如果你有兴趣，可以 PR...

**Comment by tiomno** [comment]
For those coming across this issue, bear in mind that you need the right CSS position for the container and the drawer.
- The container needs `position: relative`
- The Drawer needs `position: absolute`. And depending on layout `destroyOnClose={true}`

Please check https://codesandbox.io/s/sharp-euler-xdz96?file=/index.js:1008-1029

**Comment by XueMeijing** [comment]
> For those coming across this issue, bear in mind that you need the right CSS position for the container and the drawer.
> 
> * The container needs `position: relative`
> * The Drawer needs `position: absolute`. And depending on layout `destroyOnClose={true}`
> 
> Please check https://codesandbox.io/s/sharp-euler-xdz96?file=/index.js:1008-1029

it works correctly,  thanks
