### ISSUE TITLE
Avatar样式错误

### ISSUE THREAD

**Issue by vueZZ** [ant-design/ant-design#13408]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xp8l0mp62p)

### Steps to reproduce
<Avatar icon="user" size={20}/>

### What is expected?
永远垂直居中

### What is actually happening?
此时样式为“    line-height: 20px;font-size: 10px;”,但chrome下最小fontsize为12px,所以此处图标不居中。
建议使用flex的align-items取代line-height，保证绝对居中

**Comment by afc163** [comment]
flex 兼容不了 IE9/10
