### ISSUE TITLE
水平滚动条

### ISSUE THREAD

**Issue by AllanSmithX** [ant-design/ant-design#13404]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决水平方向放置很多张表的问题。
背景：
1、echarts tree节点过多、节点尺寸较大时，会存在重叠情况
2、由于echarts重叠问题，领导计划改用table模拟tree的操作，但目前ant table不支持单独设置单元格的背景色，故计划采用多张表水平布局，每张表仅显示一列（对应树结构中的每一层）
3、目前仅看到ant design中存在栅格布局，超过24自动换行，故希望搞个水平滚动条，达到目的。

### What does the proposed API look like?
<scrollbar style={...} > </scrollbar>

**Comment by yesmeck** [comment]
> ant table不支持单独设置单元格

可以用 `column[onCell]` 为单元格设置单独的属性。

**Comment by yesmeck** [comment]
另外水平滚动条你应该自己用 css 去解决。
