### ISSUE TITLE
为什么要删除defaultValue？ 这会使得react初学者难以认识到需要对受控组件和非受控组件进行学习

### ISSUE THREAD

**Issue by manglobe** [ant-design/ant-design#13401]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
chrome

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L198](https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L198)

### Steps to reproduce
同时使用`value`和`defaultValue`

### What is expected?
抛出`warning`

### What is actually happening?
不会抛出`warning`

---
此外,以前看到过的一个问题，现在不知道是否还在了。 诸多组件似乎都有在同步props.value到state.value ,而后在`componentWillReceiveProps`,`onChange`方法内进行差异判断，只是为了让组件变得既能受控又能非受控？（如果是我误会了请忽略这段：））

**Comment by yesmeck** [comment]
组件不能同时可控和非可控。建议详细阅读下 React 的官方文档。

**Comment by manglobe** [comment]
@yesmeck 是我的中文有问题吗？ 我问的是为什么要删除这个提醒

**Comment by manglobe** [comment]
@yesmeck 麻烦仔细阅读一下issue 谢谢了

**Comment by chenshuai2144** [comment]
这不是个教学项目

**Comment by manglobe** [comment]
@chenshuai2144 这不是教学项目的问题， 这个delete去掉了本该提示给使用者的信息。

**Comment by yesmeck** [comment]
是在这个 PR https://github.com/ant-design/ant-design/pull/1414/ 引入的，确实我也认为不应该删，应该让 React 警告。

**Comment by yesmeck** [comment]
后来好想又去掉过 https://github.com/ant-design/ant-design/commit/0e156385da7fac3ea693e1b1a9b7d03e3787b17d

可能要做下考古了。

**Comment by yesmeck** [comment]
@manglobe 可以 PR 来把这行去掉。

**Comment by chenshuai2144** [comment]
删掉 然后提醒也可以，我觉得没必要。
都受控了，defaultValue 本来就不应该存在

**Comment by manglobe** [comment]
antd现在是很多react新手的入门UI库， 他们没有受控和非受控的概念。如果没有warning可能很久之后才会注意到这块知识点。

**Comment by manglobe** [comment]
@yesmeck 不只是Input ，这块的工作量很大。 很多 Select之类的组件其实也是分为受控非受控的， 也应当加上提示

**Comment by yesmeck** [comment]
@manglobe 可以逐个 PR
