### ISSUE TITLE
npmjs.com versions get updated in place, breaking projects with package-lock.json

### ISSUE THREAD

**Issue by jwwsc** [ant-design/ant-design#13417]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
Any package.json with dependency on 3.8.0

### Reproduction link
[https://www.npmjs.com/package/antd/v/3.8.0](https://www.npmjs.com/package/antd/v/3.8.0)

### Steps to reproduce
Create a dependency on 3.8.0 with a package-lock.json, and after an 

### What is expected?
New versions should be created, and old versions should be left in-place as immutable so that folks can lock their dependencies as desired.

### What is actually happening?
Old versions are updated in place (for example, 3.8.0 is updated to a new package), breaking folks with package-lock.json files with a set hash for the version.

---
Creating and using a package-lock.json is a security best practice, and by modifying the package in-place, it becomes impossible to differentiate between a hack and a legitimate package update. Folks who want to depend on the latest minor version can use wildcards and such in their package.json.

**Comment by afc163** [comment]
It is not antd-related issue.

**Comment by tzenes** [comment]
@afc163 who is responsible for release/publication of this library to NPM?
