### ISSUE TITLE
Slider ToolTip showing above Modal

### ISSUE THREAD

**Issue by 8shaks** [ant-design/ant-design#13416]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
Windows 10.0.17134

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/52k7qj56kn)

### Steps to reproduce
Create a slider and set `tooltipVisible={true}`, give the slider a `marginTop:'100px'`
Create a Basic Modal

### What is expected?
The Slider tooltip should be hidden behind the modal

### What is actually happening?
The slider tooltip is appearing over the modal, causing it to be visible above the modal.

**Comment by spideeee** [comment]
@8shaks , you need to manage it via using `zIndex` props of both `Tooltip` and `Modal`, default `z-index` for `Tooltip` is 1060.

**Comment by gonenoob** [comment]
@8shaks, you can use the getPopupContainer API of the Tooltip component to solve this problem

**Comment by mraiguo** [comment]
I saw the popover use [rc-tooltip](https://github.com/react-component/tooltip), there is `overlayStyle` and `overlayClassName` props can control `zIndex` of popup overlay; why not add them to the document?

**Comment by mraiguo** [comment]
besides, when I set Modal component `zIndex`  too high，then Message component will showing above Modal，but there is not `overlayStyle` and `overlayClassName` props to control `zIndex`

**Comment by afc163** [comment]
We need a `tooltipProps` prop for Slider tooltip.
