### ISSUE TITLE
Tabs arrow button is shown unintentionally sometimes

### ISSUE THREAD

**Issue by henrych4** [ant-design/ant-design#13423]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
mac os 10.13.1
node v10.8.0
antd v3.11.0
rc-tabs v9.5.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9y66nk91o)

### Steps to reproduce
Refer to the codesandbox link.
Create a component with two tab panels and add following code to place tab bar at center position.
```
tabBarStyle={{ display: "flex", justifyContent: "center"}}
```
Switch between panels and observe the change.

### What is expected?
Tabs arrow buttons should be hidden.

### What is actually happening?
Tabs arrow buttons are displayed when switching between panels. And the arrow buttons do not function correctly as well.

---
This issue has been reported before but it still exists with latest version of  antd and rc-tabs.

https://github.com/ant-design/ant-design/issues/9767

https://github.com/ant-design/ant-design/issues/8861

According to the previous issues, the problem is related to calculation of container width. A temporarily solution is to set larger width in tabBarStyle

**Comment by afc163** [comment]
> tabBarStyle={{ display: "flex", justifyContent: "center"}}

Try don't do that it will break calculation of container width which is neccessary.

**Comment by afc163** [comment]
Emmm..., it works well in Firefox

**Comment by henrych4** [comment]
I just test with chrome, firefox and safari. It seems that problem occurs in chrome only.

**Comment by zombieJ** [comment]
`offsetWidth` with decimal on Chrome get different value with same float cause this. Add 1px in calculation to fix this.

**Comment by miteshtagadiya** [comment]
I have a similar issue, I used vertical tabs and wrote below custom sass which worked for me,
```
.ant-tabs-nav-container-scrolling 
      padding: 0px !important

  .ant-tabs-tab-arrow-show 
      display: none
```
this CSS hides the arrows and then removes the top padding of the arrow.
