### ISSUE TITLE
Upload 组件  当有 组件有入参 fileList 时 选择文件上传的时候 上传成功之后不回调 onChange

### ISSUE THREAD

**Issue by whyfind** [ant-design/ant-design#13422]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
谷歌浏览器。（ps：）

### Reproduction link
[https://codepen.io/anon/pen/RqOVoy?editors=0010](https://codepen.io/anon/pen/RqOVoy?editors=0010)

### Steps to reproduce
Upload 组件  当有 组件有入参 fileList 时 ，选择文件上传的时候 上传成功之后不回调 onChange

### What is expected?
当有 组件有入参 fileList 时
上传成功之后回调 onChange 

### What is actually happening?
当有 组件有入参 fileList 时
上传成功之后不回调 onChange

**Comment by whyfind** [comment]
是因为 

Version
3.11.0

ant-design/components/upload/Upload.tsx
第184 行 做了判断。

当父组件中给Upload组件传入参数 fileList 时，Upload组件的 onChange 事件 不在setState fileList

**Comment by yutingzhao1991** [comment]
You should use `defaultFileList`.

参考 https://www.yuque.com/ant-design/course/goozth

**Comment by whyfind** [comment]
But async set defaultFileList is failed when init defaultFileList empty Array ,！ The value can't change.What should I do about it?
