### ISSUE TITLE
Antd sets box-sizing: border-box to all elements in the DOM

### ISSUE THREAD

**Issue by Nouzbe** [ant-design/ant-design#13436]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
Windows 10.0.17134, Chrome 70.0.3538.110, React 16.6.3

### Reproduction link
[https://github.com/Nouzbe/antd-style-side-effect](https://github.com/Nouzbe/antd-style-side-effect)

### Steps to reproduce
- Add `antd` to an already existing project.
- Import `antd` 's CSS.

### What is expected?
The project's layout remains unchanged.

### What is actually happening?
The existing elements heights and widths change.

---
Probably related to https://github.com/ant-design/ant-design/issues/13169.

### Cause

The problem is linked to https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less and its:

```
*,
*::before,
*::after {
  box-sizing: border-box; // 1
}
```

### What I tried

I tried to add a build step to remove these lines from the css ressources and add instead:

```
*[class^="ant-"],
*[class^="ant-"]::before,
*[class^="ant-"]::after {
  box-sizing: border-box;
}
```

Unfortunately it does not work perfectly: Antd also renders elements that don't have a CSS className (and that are therefore not matchable generically by a selector like the previous one) but that still relie on that box-sizing value to be displayed correctly. And even if it worked, that's pretty advanced and we probably don't want Antd users to have to do this kind of things when they integrate the lib.

Projects could also explicitely define the box-sizing to be "initial" for all their own elements. That would work. But:

- It's a painful thing to do: you basically have to match all your elements. This pain is a potential reason to not choose Antd.
- It's simply not possible for elements that are out of the project's reach: for instance elements that are rendered by other third party libraries.

### Potential fix

I believe that fixing this implies removing this global rule and add `box-sizing: border-box` to each individual element that needs it. I admit that it would be a big change in terms of number of lines.

**Comment by afc163** [comment]
It will be a breaking change for existed projects which using this as default reset styles for their own elements. So we are better to pass this. 

similar to #9363

**Comment by Atw-Lee** [comment]
"version": "4.21.7"
The problem occurs again
