### ISSUE TITLE
Slider blur doesn't work and slider stays selected after mouseup event

### ISSUE THREAD

**Issue by Andriy-Kulak** [ant-design/ant-design#13439]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
Chrome Version 70.0.3538.77 / Firefox 63.0.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nz8nzvjjm)

### Steps to reproduce
Move the slider, then stop

### What is expected?
the slider handle to stop being selected/focused once it is released by the mouse. Also, `blur` event is triggered in the code but does not have any affect on the slider.

### What is actually happening?
The slider handle is still focused on after the handle is released by the mouse and has this blue highlighted effect around it that is unsightly. In order to get rid of it, I need to click outside of the slider. 

In addition, I tried to use the slider `blur` event and that seems to not work at all. The slider is still focused on mouseup. Please refer to code sandbox for reference.

Attached is an image for reference of the highlighted blue circle.
![screen shot 2018-12-04 at 12 13 40 pm](https://user-images.githubusercontent.com/12179976/49460437-51eb7600-f7bf-11e8-9e14-439baeea1177.png)

**Comment by shubham-dentsu** [comment]
@ztplz Is there is any fix for thi ?
