### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by llcgh** [ant-design/ant-design#13449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
左边是穿梭框左半部分，右边是一个table。点击穿梭框内容，添加到table中，删除table列内容，内容返回穿梭框。

### What does the proposed API look like?
没有思路

**Comment by ztplz** [comment]
Here is what your described. https://ant.design/components/transfer/
