### ISSUE TITLE
dropdownRender 如何使render区点击不是去焦点不退出

### ISSUE THREAD

**Issue by crazyJac** [ant-design/ant-design#13448]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
mac os 10.14 chrome 71 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://v34n8lv9n3.codesandbox.io/)

### Steps to reproduce
<Select
          defaultValue="lucy"
          style={{ width: 120 }}
          dropdownRender={menu => (
            <div>
              <Button>点击不想关闭</Button>
              {menu}
              <Divider style={{ margin: "4px 0" }} />
              <div style={{ padding: "8px", cursor: "pointer" }}>
                <Icon type="plus" /> Add item
              </div>
            </div>
          )}
        >
          <Option value="jack">Jack</Option>
          <Option value="lucy">Lucy</Option>
</Select>

### What is expected?
下拉面板不关闭

### What is actually happening?
点击关闭，失去焦点

**Comment by selinp** [comment]
我也想知道如何给‘添加项目’的div绑定一个事件

**Comment by zombieJ** [comment]
控制 open 状态：https://codesandbox.io/s/32y80yk915

**Comment by selinp** [comment]
> 控制开放状态：[https](https://codesandbox.io/s/32y80yk915)：[//codesandbox.io/s/32y80yk915](https://codesandbox.io/s/32y80yk915)

请问为什么将onMouseDown换成onClick后事件没有触发

**Comment by zombieJ** [comment]
@selinp 内部监听了 onMouseDown 和 onClick，onMouseDown 和 onMouseUp 后两个就都阻止了。

**Comment by babycannotsay** [comment]
> 控制 open 状态：https://codesandbox.io/s/32y80yk915

你好，你这个demo 在select 是multiple的情况下，点击`不想关闭`， 就真的不能关闭了，无论怎么操作

[https://codesandbox.io/s/zrlyxmy9rm](https://codesandbox.io/s/zrlyxmy9rm)

**Comment by zombieJ** [comment]
@babycannotsay ，你要了解一下受控的概念：https://codesandbox.io/s/5zvz6q6584

**Comment by babycannotsay** [comment]
> @babycannotsay ，你要了解一下受控的概念：https://codesandbox.io/s/5zvz6q6584
受控我还是知道的。你可以对照单选的代码，，在点击`不想关闭`后，鼠标移出去点击，dropdown会自动关闭。多选的情况下却不会。我的问题就是这个。

**Comment by babycannotsay** [comment]
实际需求会像这样子 [https://codesandbox.io/s/8n7568j30j](https://codesandbox.io/s/8n7568j30j)

**Comment by zombieJ** [comment]
@babycannotsay 应该是 bug，我看一下

**Comment by babycannotsay** [comment]
@zombieJ 改完，预计哪个版本要发，这里说一下，谢谢了。我这边在祖辈元素上加了个mousedown事件 暂时hack了，代码如下。

`if (this.state.open && !e.target.closest('.ant-select-dropdown')) {
      this.setState({
        open: false,
      });`

**Comment by zombieJ** [comment]
@babycannotsay ,看了下源代码。Select 在 multiple 下是监听的 onBlur 事件，Button 自带焦点导致 onBlur 被消耗了。但是这如果让 Select 自行处理掉，就显得有点管太多了。感觉得在文档里标注一下。

Fix Sample：https://codesandbox.io/s/rjvzml4lv4

**Comment by abdurahmanus** [comment]
I was trying to implement select in default mode (single item) with search and add button. When result is not found I want to click add button to show modal dialog or something to add a new item to select, but in this case onClick handler doesn't work
https://codesandbox.io/s/yvwy28v3p1

**Comment by abdurahmanus** [comment]
Actually hack with wrapping Select in div with preventDefault mouseDown event seems to work fine
https://github.com/ant-design/ant-design/issues/13504
https://codesandbox.io/s/oo6q47mnr9

**Comment by hon2a** [comment]
It's a good idea to make things in documentation code samples that look interactive actually do something. This bug can be trivially reproduced just by adding an `onClick` handler to the _Custom dropdown_ example in [`Select` documentation](https://ant.design/components/select/): https://codesandbox.io/s/6x4kl1vo4n.

**Comment by afc163** [comment]
Can we prevent `onMouseDown` to element in dropdownRender defaultly? @zombieJ

**Comment by zombieJ** [comment]
This should be enhanced by `rc-trigger` to track virtual active state. Currently may lack of time to handle this. But it will happen~

ref: https://github.com/react-component/select/pull/348#discussion_r234406076

**Comment by afc163** [comment]
Here is a workaround via preventing `onMouseDown`: https://codesandbox.io/s/8zv3r3jw60

```diff
  <Select
    defaultValue="lucy"
    style={{ width: 120 }}
    dropdownRender={menu => (
      <div>
        {menu}
        <Divider style={{ margin: '4px 0' }} />
        <div
          style={{ padding: '8px', cursor: 'pointer' }}
+         onMouseDown={e => e.preventDefault()}
          onClick={() => console.log('click')}
        >
          <Icon type="plus" /> Add item
        </div>
      </div>
    )}
  >
    <Option value="jack">Jack</Option>
    <Option value="lucy">Lucy</Option>
  </Select>
````

**Comment by afc163** [comment]
Select 的 dropdownRender中 加了单选框，点击单选按钮的文字下拉框就被关闭了 #15333

**Comment by zombieJ** [comment]
> Select 的 dropdownRender中 加了单选框，点击单选按钮的文字下拉框就被关闭了 #15333

https://codesandbox.io/s/ql5rql42qq

**Comment by weiyang123** [comment]
antd 2.X的版本 怎么保持select 下拉选项不关闭，自定义选项实现dropdownRender属性功能

**Comment by zombieJ** [comment]
@weiyang123 , `2.x` 版本已经过了维护期，建议升级到 `3.x` 哈~

**Comment by weiyang123** [comment]
> @weiyang123 , `2.x` 版本已经过了维护期，建议升级到 `3.x` 哈~

但是最新版本的升级不向下兼容啊  icon，样式不对

**Comment by linshuizhaoying** [comment]
同样 在 dropdownRender 里写了 table 控制了menu open 然后还加上了各种黑科技
但是发现 table里面如果有checkbox的时候 还是会出现几率闪退 会自动执行blur

**Comment by zzxiexin** [comment]
我发现在dropdownRender里面写入input控件，onchange事件会失效，要怎么解决

**Comment by ShaileshPrajapati-BTC** [comment]
i have same issue `I found that writing the input control in dropdownRender, the onchange event will be invalid, how to solve`

**Comment by MurWhite** [comment]
我发现 antd-vue 上也有同样的问题。事情这么久了，所以是不打算修复了吗

**Comment by gitbu** [comment]
> Here is a workaround via preventing `onMouseDown`: https://codesandbox.io/s/8zv3r3jw60
> 
> ```diff
>   <Select
>     defaultValue="lucy"
>     style={{ width: 120 }}
>     dropdownRender={menu => (
>       <div>
>         {menu}
>         <Divider style={{ margin: '4px 0' }} />
>         <div
>           style={{ padding: '8px', cursor: 'pointer' }}
> +         onMouseDown={e => e.preventDefault()}
>           onClick={() => console.log('click')}
>         >
>           <Icon type="plus" /> Add item
>         </div>
>       </div>
>     )}
>   >
>     <Option value="jack">Jack</Option>
>     <Option value="lucy">Lucy</Option>
>   </Select>
> ```'
点击事件生效了，但是弹框还是消失了，怎么能不消失了

**Comment by gitbu** [comment]
这个bug得修复啊

**Comment by lc-stevenzhang** [comment]
> 这个bug得修复啊，折腾了半天才搞好

请问怎么搞好的？

**Comment by lc-stevenzhang** [comment]
> 我发现在dropdownRender里面写入input控件，onchange事件会失效，要怎么解决

https://codesandbox.io/s/beautiful-firefly-l5swz?fontsize=14

**Comment by GuillaumeLachaud** [comment]
Any plans to make this "officially" supported? It looks kind of a hack. At least, it should be part of the official samples for Select custom dropdown

**Comment by afc163** [comment]
1. Select 多选和 tags 模式为了防止点击选项时光标没有保持在输入框内，给浮层增加了 `onMouseDown={e => e.preventDefault()}`，这句话导致了本问题。
2. 单选没有这个需求，可以判断去掉。
3. 即使是多选和 tags 模式，也可以将这段代码限制作用在每个 Option 上，而不是整个 Select 浮层。

**Comment by afc163** [comment]
- [ ] 这个例子要更新一下：https://ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu ，默认加入 onMouseDown 的处理。
- [ ] 上面例子的描述文档里可以加入相关说明。
- [ ] Select 文档加入 FAQ 说明这个问题。

**Comment by 1yzz** [comment]
如果dropdownRender里面有input，它的父上面有onMouseDown，是不是会没办法focus？

**Comment by afc163** [comment]
@1yzz https://github.com/ant-design/ant-design/issues/13448#issuecomment-512002600 @lc-stevenzhang 给的例子很好，就是代码需要比较复杂。

**Comment by 1yzz** [comment]
> > 我发现在dropdownRender里面写入input控件，onchange事件会失效，要怎么解决
> 
> https://codesandbox.io/s/beautiful-firefly-l5swz?fontsize=14

通过这个事件`onDropdownVisibleChange` 肯定是可以的。就是感觉它里面监听的事件有点看不懂，没办法隔断。

**Comment by zombieJ** [comment]
3.0 中需要通过受控来实现，4.0 中不需要额外的代码：http://next.ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu

**Comment by xuzhanhh** [comment]
> @1yzz [#13448 (comment)](https://github.com/ant-design/ant-design/issues/13448#issuecomment-512002600) @lc-stevenzhang 给的例子很好，就是代码需要比较复杂。

mode="multiple"下由于强制search会导致失焦后不会hide哦 https://codesandbox.io/s/custom-render-dropdown-c0ryg

**Comment by a88053443** [comment]
> > @1yzz [#13448 (comment)](https://github.com/ant-design/ant-design/issues/13448#issuecomment-512002600) @lc-stevenzhang 给的例子很好，就是代码需要比较复杂。
> 
> mode="multiple"下由于强制search会导致失焦后不会hide哦 https://codesandbox.io/s/custom-render-dropdown-c0ryg

有办法解决多选的问题吗

**Comment by a88053443** [comment]
> > @1yzz [#13448 (comment)](https://github.com/ant-design/ant-design/issues/13448#issuecomment-512002600) @lc-stevenzhang 给的例子很好，就是代码需要比较复杂。
> 
> mode="multiple"下由于强制search会导致失焦后不会hide哦 https://codesandbox.io/s/custom-render-dropdown-c0ryg

![image](https://user-images.githubusercontent.com/20753923/78213988-b408d800-74e6-11ea-822b-ce78be5fb54c.png)
目前结局办法，在保存或取消时重新获取一下焦点

**Comment by xzf123456** [comment]
> Can we prevent `onMouseDown` to element in dropdownRender defaultly? @zombieJ

已经添加onMouseDown事件，点击checkbox选框没问题，但是点击checkbox选框后面的文字还是会自动关闭

**Comment by m7he4rt** [comment]
How can add select with the search field in the component? 

> > > @1yzz [#13448 (comment)](https://github.com/ant-design/ant-design/issues/13448#issuecomment-512002600) @lc-stevenzhang 给的例子很好，就是代码需要比较复杂。
> > 
> > 
> > mode="multiple"下由于强制search会导致失焦后不会hide哦 https://codesandbox.io/s/custom-render-dropdown-c0ryg
> 
> ![image](https://user-images.githubusercontent.com/20753923/78213988-b408d800-74e6-11ea-822b-ce78be5fb54c.png)
> 目前解决办法，在保存或取消时重新获取一下焦点

**Comment by renruijun** [comment]
> 实际需求会像这样子 https://codesandbox.io/s/8n7568j30j

解决了我的问题，thanks very very very much

**Comment by kiliaosi** [comment]
ok  我需要在Select的下拉框里面加上如下的功能：输入框、checkbox等，dropdownRender的函数如下：
```js
 const drepdownRenders = menu => {
    return (
      <>
        <div onMouseDown={onMouseDown}>
          <Input placeholder="输入搜索名称" />
          <Checkbox>全选</Checkbox>
          <Divider />
        </div>
        {menu}
      </>
    )
  }
```
你们给出的方案，不支持

**Comment by lc-stevenzhang** [comment]
> ok 我需要在Select的下拉框里面加上如下的功能：输入框、checkbox等，dropdownRender的函数如下：
> 
> ```js
>  const drepdownRenders = menu => {
>     return (
>       <>
>         <div onMouseDown={onMouseDown}>
>           <Input placeholder="输入搜索名称" />
>           <Checkbox>全选</Checkbox>
>           <Divider />
>         </div>
>         {menu}
>       </>
>     )
>   }
> ```
> 
> 你们给出的方案，不支持

试试这个：
https://codesandbox.io/s/kuo-zhan-cai-dan-antd-4-18-7-forked-vuined?file=/index.js

**Comment by luanwanwan** [comment]
现在想关闭了就不行了，阻止事件去了都没用

**Comment by afc163** [comment]
4.x onMouseDown is not necessary anymore: https://github.com/ant-design/ant-design/pull/36665

**Comment by DevilZh** [comment]
太坑了， 这问题搞了我大半天

**Comment by candisecandise** [comment]
> @selinp 内部监听了 onMouseDown 和 onClick，onMouseDown 和 onMouseUp 后两个就都阻止了。

@zombieJ 这是什么意思呢，监听了onMouseDown 和 onClick，然后 xxx 后就阻止了？是不是打错了，应该是监听了 onMouseDown 和 onMouseUp 吧？

另外 @afc163 ，如果把下面这段代码的 div 换成 antd 的 checkbox 组件，onMouseDown={e => e.preventDefault()} 也起不了作用，这是为什么呢？是因为 checkbox 没有监听 onMouseDown 事件么？


```
  <Select
    defaultValue="lucy"
    style={{ width: 120 }}
    dropdownRender={menu => (
      <div>
        {menu}
        <Divider style={{ margin: '4px 0' }} />
        <div
          style={{ padding: '8px', cursor: 'pointer' }}
+         onMouseDown={e => e.preventDefault()}
          onClick={() => console.log('click')}
        >
          <Icon type="plus" /> Add item
        </div>
      </div>
    )}
  >
    <Option value="jack">Jack</Option>
    <Option value="lucy">Lucy</Option>
  </Select>
```
