### ISSUE TITLE
table组件无法隐藏某列，希望能增在这个功能。

### ISSUE THREAD

**Issue by lijx2018github** [ant-design/ant-design#13457]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by guanyufen123** [comment]
我也是隐藏列来的，结果找半天不到

**Comment by yoyo837** [comment]
自己先封装实现吧，我自己实现了同一处表格的拖拽列宽（这个有文档）和隐藏显示列（columns 用state维护）并记忆（后台接口保存、查询）

![image](https://user-images.githubusercontent.com/6134547/64753046-55810a00-d554-11e9-8e36-be780b978ce9.png)

**Comment by ShawDanon** [comment]
可以加高阶函数过滤column

**Comment by GitHub-Haisheng** [comment]
> 可以加高阶函数过滤column

大佬 厉害 用你提供的这个思路 很简单的就实现了需求。贴一点代码，给找这个功能的人参考。

`
   columns={columns.filter((element) => {
              //  查看状态 不显示操作
              if (element.key === 'operation' && pageType === pageTypeEnum.VIEW) {
                return false;
              }
              return true;
            })}
`

**Comment by LongYue9608** [comment]
> > 可以加高阶函数过滤column
> 
> 大佬 厉害 用你提供的这个思路 很简单的就实现了需求。贴一点代码，给找这个功能的人参考。
> 
> ```js
>    <Table
>             rowKey="id"
>             bordered
>             size="middle"
>             columns={columns.filter((element) => {
>               //  查看状态 不显示操作
>               if (element.key === 'operation' && pageType === pageTypeEnum.VIEW) {
>                 return false;
>               }
>               return true;
>             })}
>             loading={loading}
>             dataSource={dataSource}
>             pagination={false}
>             scroll={{ y: 500 }}
>           />
> ```

感谢
