### ISSUE TITLE
checkboxes used as children of Checkbox.Group are not checking while using with map

### ISSUE THREAD

**Issue by itsazzad** [ant-design/ant-design#13452]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
Windows 10, Latest Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y3v794o9qj)

### Steps to reproduce
https://codesandbox.io/s/y3v794o9qj
You can see that the checkboxes used as children of Checkbox.Group are not checked although their texts are being changed while using with map.

### What is expected?
On Check/Uncheck in the first group should also reflect in the second group

### What is actually happening?
In the second group the inside Checkbox is not updating.

**Comment by itsazzad** [comment]
![capture2](https://user-images.githubusercontent.com/54909/49500428-deb73200-f89a-11e8-8a11-d787c3910511.PNG)
![capture1](https://user-images.githubusercontent.com/54909/49500429-df4fc880-f89a-11e8-8aef-66b8d521aa80.PNG)

**Comment by dazbo** [comment]
Your second group is missing the `value` property.
[working demo](https://codesandbox.io/s/jl9o6owzl5): changes are done on line 69 & 70
