### ISSUE TITLE
Tree, TreeSelect feature request

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1345]
Is it possible to add an option that will make to show path up to root after filter?

Here is tree:
https://www.dropbox.com/s/7u3c5si7brpcy60/Screenshot%202016-04-06%2015.59.52.png?dl=0

and here is what i get after search:
https://www.dropbox.com/s/lfgcghjqfzh3koi/Screenshot%202016-04-06%2016.00.41.png?dl=0

As you can see, when there are some nodes with same name then searching is quite useless, because you can't understand what exactly to choose.

It would be cool, if it will be possible to show full path for each node (and of course, unite parts of tree for same roots)

**Comment by warmhug** [comment]
Ok. This may be a bug, I will fix it, thank you.

**Comment by warmhug** [comment]
try 1.0.0-beta. Or see http://react-component.github.io/tree-select/examples/basic.html
![image](https://cloud.githubusercontent.com/assets/2011119/14410254/81f4851a-ff5d-11e5-8432-8cc6f2ff6f64.png)

**Comment by plandem** [comment]
1.0.0-beta? Do you mean 1.5.2-beta.2?

**Comment by plandem** [comment]
https://www.dropbox.com/s/ggmfn4myf7b75ar/Screenshot%202016-04-11%2012.52.16.png?dl=0

as you can see - they have different keys, but same titles.

**Comment by warmhug** [comment]
try `rc-tree-select@1.5.5`

**Comment by plandem** [comment]
i tried: npm update, antd was updated, but rc-tree-select is still same.

**Comment by plandem** [comment]
ok, i tried and here is result (last branch is closed):
https://www.dropbox.com/s/specdyrcfg5ek1j/Screenshot%202016-04-13%2017.37.07.png?dl=0

it's better now, but i suppose it must be like this:
https://www.dropbox.com/s/9mlapakkm41fmb5/Screenshot%202016-04-13%2017.38.00.png?dl=0

**Comment by warmhug** [comment]
Just want to automatically expand the treeNode to be searched ?

**Comment by plandem** [comment]
well, case is:
1) type title to search
2) select required node

In current case i must to do next:
1) search
2) open 'parent' of required node
3) select required node

In most cases you want to 'select' a node that was found. Without any additional actions.

**Comment by plandem** [comment]
Well.....maybe it must be an option. Your case is quite useful too. Need time to get users feedback, right now i'm not sure.

**Comment by warmhug** [comment]
rc-tree-select@1.5.7-beta.1
