### ISSUE TITLE
antd组件如何支持服务端渲染

### ISSUE THREAD

**Issue by TristanDongMaster** [ant-design/ant-design#13458]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
mac

### Reproduction link
[https://github.com/ant-design/react-starter-kit](https://github.com/ant-design/react-starter-kit)

### Steps to reproduce
git clone这个项目，antd样式会闪烁，css样式是客户端下载的，没有in js

### What is expected?
css in js

### What is actually happening?
css是页面单独下载的

---
// Only use babel-plugin-import in client side
clientConfig.module.rules[0].options.plugins = [
  ...clientConfig.module.rules[0].options.plugins,
  ['import', { libraryName: 'antd',  style: 'css'}],
];

**Comment by TristanDongMaster** [comment]
配置如下：antd组件会闪烁，服务端渲染代码没有把antd css插入页面，而是客户端下载的css
          // antd 
          {
            test: /\.css$/,
            include: [/node_modules\/.*antd/],
            loader: 'style-loader',
          },


          // Convert CSS into JS module
          {
            issuer: { not: [reStyle] },
            exclude: [/node_modules\/.*antd/],
            use: 'isomorphic-style-loader',
          },

// Only use babel-plugin-import in client side
clientConfig.module.rules[0].options.plugins = [
  ...clientConfig.module.rules[0].options.plugins,
  ['import', { libraryName: 'antd',  style: 'css'}],
];

**Comment by TristanDongMaster** [comment]
是不是antd不支持服务端渲染？

**Comment by nmsbaka** [comment]
Hi All,
I'm trying to add Antd design - UI to react starter kit.
I imported success antd, but the style of antd is loaded after mounted component. I want to that load before.  So who has solution, please help me?
[Source](https://bitbucket.org/nmsbaka/react-starter-kit-antd)
![Gif](http://g.recordit.co/Faw2YAW7YU.gif)

**Comment by TristanDongMaster** [comment]
@nmsbaka, did you extract the antd css into a single css file instread of css in js.

**Comment by nmsbaka** [comment]
Here is my webpack.config.js
```
...
      {
        test: /\.less$/,
        include: [/[\\/]node_modules[\\/].*antd/],
        use: [
          ...(!isDebug ? MiniCssExtractPlugin.loader : ['style-loader']),

          {
            loader: 'css-loader',
            options: {
              sourceMap: isDebug,
              minimize: isDebug ? false : minimizeCssOptions,
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: './tools/postcss.config.js',
              },
            },
          },
          {
            loader: 'less-loader',
            options: {
              javascriptEnabled: true,
              modifyVars: antThemeVars,
            },
          },
        ],
      },
...
// Rules for Style Sheets
      {
        test: reStyle,
        exclude: [/[\\/]node_modules[\\/].*antd/],
...
  plugins: [
    new MiniCssExtractPlugin({
      filename: '[name].css',
      chunkFilename: '[name].css',
    }),
...
// Only use babel-plugin-import in client side
clientConfig.module.rules[0].options.plugins = [
  ...clientConfig.module.rules[0].options.plugins,
  [
    'import',
    {
      libraryName: 'antd',
      libraryDirectory: 'es',
      style: true,
    },
  ],
];
```

**Comment by TristanDongMaster** [comment]
@notifications，is it work？

**Comment by nmsbaka** [comment]
@TristanDongMaster  the style still being loaded after.

**Comment by TristanDongMaster** [comment]
@nmsbaka, please refer:https://github.com/webpack-contrib/mini-css-extract-plugin.   I guess it sopport, i failed to try;   Using preloaded or inlined CSS
The runtime code detects already added CSS via <link> or <style> tag. This can be useful when injecting CSS on server-side for Server-Side-Rendering. The href of the <link> tag has to match the URL that will be used for loading the CSS chunk. The data-href attribute can be used for <link> and <style> too. When inlining CSS data-href must be used.

**Comment by nmsbaka** [comment]
@TristanDongMaster  i have solution base on "isomorphic-style-loader". The style will be load before mounted component. Don't use babel-plugin-import. Instead, I add the library style directly to the insertCss function.
webpack.config.js
```
...
// Rules for Style Sheets
      {
        test: reStyle,
        rules: [
          // Convert CSS into JS module
          {
            issuer: { not: [reStyle] },
            use: 'isomorphic-style-loader',
          },

          // Process external/third-party styles
          {
            exclude: SRC_DIR,
            loader: 'css-loader',
            options: {
              sourceMap: isDebug,
              minimize: isDebug ? false : minimizeCssOptions,
            },
          },

          // Process internal/project styles (from src folder)
          {
            include: SRC_DIR,
            loader: 'css-loader',
            options: {
              // CSS Loader https://github.com/webpack/css-loader
              importLoaders: 1,
              sourceMap: isDebug,
              // CSS Modules https://github.com/css-modules/css-modules
              modules: true,
              localIdentName: isDebug
                ? '[name]-[local]-[hash:base64:5]'
                : '[hash:base64:5]',
              // CSS Nano http://cssnano.co/
              minimize: isDebug ? false : minimizeCssOptions,
            },
          },

          // Apply PostCSS plugins including autoprefixer
          {
            loader: 'postcss-loader',
            options: {
              config: {
                path: './tools/postcss.config.js',
              },
            },
          },
          {
            test: /\.less$/,
            loader: 'less-loader',
            options: {
              javascriptEnabled: true,
              modifyVars: antThemeVars,
            },
          },
        ],
      },
...
// Comment this scope
// clientConfig.module.rules[0].options.plugins = [
//   ...clientConfig.module.rules[0].options.plugins,
//   [
//     'import',
//     {
//       libraryName: 'antd',
//       libraryDirectory: 'es',
//       style: true,
//     },
//   ],
// ];
```
server.js
```
import antdStyle from 'antd/dist/antd.less';
...
    const insertCss = (...styles) => {
      // eslint-disable-next-line no-underscore-dangle
      css.add(antdStyle._getCss());
      // eslint-disable-next-line no-underscore-dangle
      styles.forEach(style => css.add(style._getCss()));
    };
```
client.js
```
import antdStyle from 'antd/dist/antd.less';
...
insertCss: (...styles) => {
    // eslint-disable-next-line no-underscore-dangle
    let removeCss = [antdStyle._insertCss()];
    // eslint-disable-next-line no-underscore-dangle
    removeCss = removeCss.concat(styles.map(x => x._insertCss()));
    return () => {
      removeCss.forEach(f => f());
    };
  },
```

**Comment by TristanDongMaster** [comment]
@nmsbaka, thk, it works, but just the html file is so big, 600kb, it will be slow slow slow.....

**Comment by TristanDongMaster** [comment]
@nmsbaka, you can try only insert the necessary css in the html.......

**Comment by nmsbaka** [comment]
@nmsbaka, I will research more...

**Comment by afc163** [comment]
Seems that it is not antd issue, we do support server side render.

**Comment by tim-soft** [comment]
Use mini-css-extract-plugin to extract out antd styles to their own files, then include those separately in your html

**Comment by TristanDongMaster** [comment]
@nmsbaka， mini-css-extract-plugin  is not work, i guess the config is not right, i found the css still insert by script. you can check by track the request steps in network

**Comment by TristanDongMaster** [comment]
@nmsbaka，it works if I hard coding in html (Html.js):you can try
<html className="no-js" lang="en">
        <head>
          <meta charSet="utf-8" />
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <title>{title}</title>
          <meta name="description" content={description} />
          <link rel="stylesheet" type="text/css" href="/antd.css" />

**Comment by nmsbaka** [comment]
@TristanDongMaster, mini-css-extract-plugin is work, but the style is loaded after mounted component.
[Refer](https://github.com/nmsbaka/react-starter-kit-antd/tree/nms)
![Antd-React](http://g.recordit.co/U6IlVfrh96.gif)

**Comment by TristanDongMaster** [comment]
<html className="no-js" lang="en">
        <head>
          <meta charSet="utf-8" />
          <meta httpEquiv="x-ua-compatible" content="ie=edge" />
          <title>{title}</title>
          <meta name="description" content={description} />
          <link rel="stylesheet" type="text/css" href="/antd.css" />

**Comment by TristanDongMaster** [comment]
mini-css-extract-plugin is work, but it is executed by client, the css file is inserted by js, we expect the css is inserted in server, so the style  is loaded after mounted component.

**Comment by nmsbaka** [comment]
@TristanDongMaster, I mean, the style is loaded after, that is the style is deployed after. Sorry!

**Comment by nmsbaka** [comment]
@TristanDongMaster , I want to the css is inserted before the component is inserted. This is the problem. Before, i insert css on server side, so the response data is so big.

**Comment by TristanDongMaster** [comment]
@nmsbaka, you can insert the <  link rel="stylesheet" type="text/css" href="/antd.css"  >  into the Html.js by maunal....the html file size will be small

**Comment by nmsbaka** [comment]
@TristanDongMaster, I think, I should combine isomorphic-style-loader and MiniCssExtractPlugin. Then babel-import-plugin might work fine. And the necessary style will be inserted

**Comment by zhangyuang** [comment]
Use https://github.com/zhangyuang/ssr, seamless Integration with antd
