### ISSUE TITLE
发现upload组件代码演示的一个错误

### ISSUE THREAD

**Issue by huangyanyang** [ant-design/ant-design#13455]
![image](https://user-images.githubusercontent.com/19208961/49513753-fc9d8a80-f8cc-11e8-904c-8a692f8a4d55.png)
![image](https://user-images.githubusercontent.com/19208961/49513823-2eaeec80-f8cd-11e8-8ba5-0d78e07a46cc.png)
![image](https://user-images.githubusercontent.com/19208961/49513922-7766a580-f8cd-11e8-9b49-53363a9acf24.png)

**Comment by afc163** [comment]
来个 PR

**Comment by huangyanyang** [comment]
代码演示那一块不是markdown写的，本来也想提pr的

**Comment by afc163** [comment]
<img width="371" alt="image" src="https://user-images.githubusercontent.com/507615/49515165-235dc000-f8d1-11e8-9604-a322a199e3d6.png">

**Comment by zy410419243** [comment]
了解一下 [这个](https://github.com/benjycui/bisheng)，这玩意可以解析 md 的
