### ISSUE TITLE
从3.8.4升级到目前3.11.0后日期组件的周1到周日，1月到12月为英文

### ISSUE THREAD

**Issue by YoungHearts** [ant-design/ant-design#13462]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
测试过的环境：mac10.13.5、window10等系统上的谷歌70.0.3538.110

### Reproduction link
[https://github.com/YoungHearts/antd-datePicker](https://github.com/YoungHearts/antd-datePicker)

### Steps to reproduce
升级后就是这样

### What is expected?
中文

### What is actually happening?
周1到周日，1月到12月为英文，其他正常。

---
周一到周日，一月到12月为英文，其他正常。国际化LocaleProvider已经加上了，反正之前是没问题的，更新后出现此问题

demo上传了
[https://github.com/YoungHearts/antd-datePicker](url)

**Comment by loveZMM** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Version
> 3.11.0
> 
> ### Environment
> 测试过的环境：mac10.13.5、window10等系统上的谷歌70.0.3538.110
> 
> ### Reproduction link
> http://null.com
> 
> ### Steps to reproduce
> 升级后就是这样
> 
> ### What is expected?
> 中文
> 
> ### What is actually happening?
> 周1到周日，1月到12月为英文，其他正常。
> 
> 周一到周日，一月到12月为英文，其他正常。国际化LocaleProvider已经加上了，反正之前是没问题的，更新后出现此问题

请问这个问题有解决吗？我也有碰到类似的问题，年是中文的，其他的都是英文的！有时是都是中文的，有时就如图片一样！
![image](https://user-images.githubusercontent.com/40625143/49622831-1098d780-fa06-11e8-8e10-2553998f7d39.png)

**Comment by YoungHearts** [comment]
> > * [x]   I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> > 
> > ### Version
> > 3.11.0
> > ### Environment
> > 测试过的环境：mac10.13.5、window10等系统上的谷歌70.0.3538.110
> > ### Reproduction link
> > http://null.com
> > ### Steps to reproduce
> > 升级后就是这样
> > ### What is expected?
> > 中文
> > ### What is actually happening?
> > 周1到周日，1月到12月为英文，其他正常。
> > 周一到周日，一月到12月为英文，其他正常。国际化LocaleProvider已经加上了，反正之前是没问题的，更新后出现此问题
> 
> 请问这个问题有解决吗？我也有碰到类似的问题，年是中文的，其他的都是英文的！有时是都是中文的，有时就如图片一样！
> ![image](https://user-images.githubusercontent.com/40625143/49622831-1098d780-fa06-11e8-8e10-2553998f7d39.png)

没有，作者需要传示例，我弄一个先

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11464#issuecomment-425308789

**Comment by YoungHearts** [comment]
> [#11464 (comment)](https://github.com/ant-design/ant-design/issues/11464#issuecomment-425308789)
已经加了，我稍后上传一个demo

**Comment by loveZMM** [comment]
> > [#11464 (comment)](https://github.com/ant-design/ant-design/issues/11464#issuecomment-425308789)
> > 已经加了的，我稍后上传一个demo

请问有找到是什么原因嘛？试了各种能想到的方法了！

**Comment by YoungHearts** [comment]
> [#11464 (comment)](https://github.com/ant-design/ant-design/issues/11464#issuecomment-425308789)

demo上传了
[https://github.com/YoungHearts/antd-datePicker](url)

**Comment by Delphier** [comment]
import 'moment/local/zh-cn' 可解决。

**Comment by YoungHearts** [comment]
> import 'moment/local/zh-cn' 可解决。
[https://github.com/YoungHearts/antd-datePicker/blob/master/src/routes/test/test.js](加了的，没有用)

**Comment by afc163** [comment]
<img width="886" alt="image" src="https://user-images.githubusercontent.com/507615/49641304-b8d08f80-fa4a-11e8-9655-77a3533a10ce.png">

Your demo works fine.

**Comment by afc163** [comment]
如果你的项目里还不行，可以试试 https://github.com/YoungHearts/antd-datePicker/pull/1

**Comment by YoungHearts** [comment]
> 如果你的项目里还不行，可以试试[YoungHearts / antd-日期选择器＃1](https://github.com/YoungHearts/antd-datePicker/pull/1)

谢谢，解决了，什么都不用改，升级后删除依赖包，重新拉取就好了，别的同学可以试试

**Comment by yanszhang** [comment]
还是不行， +local,  升级antd 升级moment 都试过了、

**Comment by afc163** [comment]
@yanszhang 升级 umi

**Comment by yanszhang** [comment]
> @yanszhang 升级 umi

并未使用umi

**Comment by afc163** [comment]
@yanszhang 提供一个可重现的 repo 吧。

**Comment by Feafortecsy** [comment]
> > 如果你的项目里还不行，可以试试[YoungHearts / antd-日期选择器＃1](https://github.com/YoungHearts/antd-datePicker/pull/1)
> 
> 谢谢，解决了，什么都不用改，升级后删除依赖包，重新拉取就好了，别的同学可以试试

请问升级的是哪个依赖，我升级antd/moment后都无效，moment相关的导入了也没有用。

**Comment by yoyo837** [comment]
@Feafortecsy 更新到新版本试试 #18732
