### ISSUE TITLE
DatePicker does not return value based on format

### ISSUE THREAD

**Issue by schwanncheung** [ant-design/ant-design#13469]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
OSX EI、Chrome、React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wnol5vxn1l)

### Steps to reproduce
Using component `<DatePicker  showTime format="YYYY-MM-DD HH:mm" />` to choice a datetime value with format `YYYY-MM-DD HH:mm` .

### What is expected?
Expect return result without seconds and milliseconds, for example 1544077500000

### What is actually happening?
Actually return result with seconds and milliseconds, for example 1544077514322

---
Especially the part of milliseconds is invisible for user, may cause some unpredictable problem.

**Comment by yangxiaolin** [comment]
onChange is typeof `function(date: moment, dateString: string)` , function has to parameters, the second parameter is you want(this parameter is same type you passed)

**Comment by afc163** [comment]
`format` is just for displaying value, `onChange(value)` and `value` is moment object that won't be formatted at all.

**Comment by schwanncheung** [comment]
> onChange's format is:
> 
> ```js
>    function(date: moment, dateString: string)
> ```
> 
> onChange has **two** parameters, the second parameter is you want(the second value is same type you passed "YYYY-MM-DD HH:mm").
> [here](https://codesandbox.io/s/qx54j9m14q) is the example

Thanks.
But usually DatePicker is using `getFieldDecorator` for two-way binding to forms, so `onChange` is automatic called.

**Comment by yangxiaolin** [comment]
> > onChange's format is:
> > ```js
> >    function(date: moment, dateString: string)
> > ```
> > 
> > 
> > onChange has **two** parameters, the second parameter is you want(the second value is same type you passed "YYYY-MM-DD HH:mm").
> > [here](https://codesandbox.io/s/qx54j9m14q) is the example
> 
> Thanks.
> But usually DatePicker is using `getFieldDecorator` for two-way binding to forms, so `onChange` is automatic called.

you are right,  maybe a feature.
