### ISSUE TITLE
Select组件的filterOption过滤OptGroup 的label问题

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#13464]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
react 、chrome

### Reproduction link
[https://codepen.io/junhui/pen/YRoOeP?&editable=true&editors=001](https://codepen.io/junhui/pen/YRoOeP?&editable=true&editors=001)

### Steps to reproduce
无法搜索到OptGroup 的中的“Manager”

### What is expected?
可以搜索到Manager

### What is actually happening?
无搜索结果

**Comment by junhui75165** [comment]
使用filterOption遍历的时候，发现OptGroup 的内容好像并没有进入，只有Option的项遍历到了

**Comment by zombieJ** [comment]
`label={<div>Manager</div>}` => `label="Manager"`: https://codesandbox.io/s/zxx7nqvok3

**Comment by junhui75165** [comment]
label需要设置为React.Element，设置一些style样式，这时候就无法使用了，或者有什么可以设置label样式的方法？

**Comment by zombieJ** [comment]
@junhui75165，用 `dropdownRender` 包个样式： https://codesandbox.io/s/x7oxp9l32w
