### ISSUE TITLE
单选表格，selectedRowKeys 设为空数组对 Radio 标签没影响

### ISSUE THREAD

**Issue by blade254353074** [ant-design/ant-design#1346]
![image](https://cloud.githubusercontent.com/assets/9346008/14317367/84586810-fc3a-11e5-9fd6-a35834c2689e.png)

上图是选中了一项的单选表格

将 `rowSelection` 中的 `selectedRowKeys` 属性设为 `[]` 后，如下图

![image](https://cloud.githubusercontent.com/assets/9346008/14317597/924d9f5c-fc3b-11e5-845a-8c7cae5b465a.png)

`Radio` 标签的 `checked` 属性依然为 `true`，如下图

![image](https://cloud.githubusercontent.com/assets/9346008/14317605/989740d4-fc3b-11e5-9e33-aecd895788d9.png)

如果是多选，经测试没有问题
就是单选有这个情况

**Comment by afc163** [comment]
感谢反馈~
