### ISSUE TITLE
create-react-app ant.design eject的情况下 自定义主题修改

### ISSUE THREAD

**Issue by binperson** [ant-design/ant-design#13468]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
谷歌最新浏览器

### Reproduction link
[http://git.hyun.in/xuxingguo/saas-app-mange](http://git.hyun.in/xuxingguo/saas-app-mange)

### Steps to reproduce
create-react-app ant.design eject的情况下 自定义主题修改

### What is expected?
create-react-app ant.design eject的情况下 自定义主题修改成功

### What is actually happening?
create-react-app ant.design eject的情况下 自定义主题修改 添加修改loader没达到预期效果

**Comment by afc163** [comment]
eject 之后的配置方式需要你自行探索。
