### ISSUE TITLE
icon重复渲染，查看控制台发现iconfont和svg图片都渲染出来了

### ISSUE THREAD

**Issue by 404cat** [ant-design/ant-design#13474]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
react版本16.2.0，浏览器版本 70.0.3538.110（正式版本） （64 位）。

### Reproduction link
[https://github.com/404cat/repeat-icon](https://github.com/404cat/repeat-icon)

### Steps to reproduce
几天前开启过一次项目没有问题，今天开启项目的时候发现所有的icon会重复，包括表格分页的和表单内的icon，打开控制台查看结果为把iconfont和svg图片都渲染出来了，之前的antd版本为3.1.4，发现问题后尝试升级到3.11.0版本；尝试过git版本回退，没有解决这个问题。
查看Chrome后发现是ant的这个before伪元素也是一个图标[图片]。
![image](https://user-images.githubusercontent.com/34706182/49574701-f6b2b280-f97b-11e8-8f69-d569629f7f46.png)
![image](https://user-images.githubusercontent.com/34706182/49574709-f9150c80-f97b-11e8-8ee2-f4a566958125.png)

### What is expected?
期望能够解决icon渲染重复的问题。

### What is actually happening?
实际的结果为icon渲染重复。

**Comment by afc163** [comment]
你的 css 是 antd 3.1.4 的，不能和 antd@3.11 混用，请保持 js 和 css 是同一个版本的。

**Comment by BenlovedLamphere** [comment]
> 你的 css 是 antd 3.1.4 的，不能和 antd@3.11 的 js 混用，请保持 js 和 css 是同一个版本的。

大神有没有简要的升级指引，或是升级CSS文件的方法，我折腾了一下午，没解决这个问题

**Comment by noscripter** [comment]
> > 你的 css 是 antd 3.1.4 的，不能和 antd@3.11 的 js 混用，请保持 js 和 css 是同一个版本的。
> 
> 大神有没有简要的升级指引，或是升级CSS文件的方法，我折腾了一下午，没解决这个问题

找一下 antd 的引用，把 CSS 引用和 JS 模块引用都改成相同版本就好了。

**Comment by BenlovedLamphere** [comment]
> > > 你的 css 是 antd 3.1.4 的，不能和 antd@3.11 的 js 混用，请保持 js 和 css 是同一个版本的。
> > 
> > 
> > 大神有没有简要的升级指引，或是升级CSS文件的方法，我折腾了一下午，没解决这个问题
> 
> 找一下 antd 的引用，把 CSS 引用和 JS 模块引用都改成相同版本就好了。

大神，我使用的是antd Pro ，是不是也要把antdPro 也升级一下～我现在pro用的是1.4.4

**Comment by BenlovedLamphere** [comment]
> 几天前开启过一次项目没有问题，今天开启项目的时候发现所有的icon会重复，包括表格分页的和表单内的icon，打开控制台查看结果为把iconfont和svg图片都渲染出来了，之前的antd版本为3.1.4，发现问题后尝试升级到3.11.0版本；尝试过git版本回退，没有解决这个问题。
> 查看Chrome后发现是ant的这个before伪元素也是一个图标[图片]。
> ![image](https://user-images.githubusercontent.com/34706182/49574701-f6b2b280-f97b-11e8-8f69-d569629f7f46.png)
> ![image](https://user-images.githubusercontent.com/34706182/49574709-f9150c80-f97b-11e8-8ee2-f4a566958125.png)
> 
大神你这个问题解决没～～我还在坑里没爬出来～～
