### ISSUE TITLE
[bug] Form组件中遍历生成的FormItem的input 警告Failed prop type: Invalid prop `id` supplied to `Input`.

### ISSUE THREAD

**Issue by wjryours** [ant-design/ant-design#13470]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.4

### Environment
win7  chrome   react 16.6.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p277pjvo7)

### Steps to reproduce
重现步骤详见重现链接

### What is expected?
没有warning

### What is actually happening?
Failed prop type: Invalid prop `id` supplied to `Input`.

---
 将 <Input /> 替换为<TextArea rows={4} />不会warning

**Comment by yangxiaolin** [comment]
**Failed prop type: Invalid prop `id` supplied to `Input`**  means you passed parameter is illegal。
in your example, the code
```javascript
{ 
      getFieldDecorator([ item.key ], {
         rules: [],
         initialValue: ProductInfo[item.key]
     })
    (
        // <TextArea rows={4} />
        <Input />
    )
}
```
but the offical site document shows that: 
```js
getFieldDecorator(id: string, options)
```
you should pass a **String** for the first parameter instead of Object(in your code is Array)
the update demo is [here](https://codesandbox.io/s/q7xojzr7ww)

**Comment by yangxiaolin** [comment]
@afc163  maybe you can close this issue

**Comment by wjryours** [comment]
@yangxiaolin ，thanks

**Comment by yangxiaolin** [comment]
@wjryours close this issue, thank you🤨

**Comment by wjryours** [comment]
> @wjryours yuo can close the issue, thank you🤨
There is still some doubt，why use TextArea has not waring?but use Input has waring?As you say,use TextArea Should also waring ,actually, it has waring

**Comment by yangxiaolin** [comment]
@wjryours superise🤯🤯🤯, it's time to call @afc163

**Comment by afc163** [comment]
I don't know either, just don't use it this way.
