### ISSUE TITLE
upload 上传文件格式改变

### ISSUE THREAD

**Issue by WandW** [ant-design/ant-design#13475]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
win10 1809  chrome 

### Reproduction link
[https://github.com/WandW/antd/blob/master/pictures](https://github.com/WandW/antd/blob/master/pictures)

### Steps to reproduce
在多文件上传的时候 添加onchange方法导致上传的内容格式从 binary 变为 [object Object]
When uploading multiple files, the onchange method causes the uploaded content format to change from binary to [object object].

### What is expected?
维持binary 
Maintain a binary
### What is actually happening?
变为  [object Object]
A [object object]

**Comment by afc163** [comment]
If you are try to upload in manual way, it is prettry much all code you can control and be responsible to it. I don't think it is a antd upload issue.

https://github.com/WandW/antd/blob/master/pictures#L26-L58
