### ISSUE TITLE
Modal组件不显示右上角关闭按钮

### ISSUE THREAD

**Issue by GGwujun** [ant-design/ant-design#13477]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
浏览器版本

### Reproduction link
[https://stackblitz.com/edit/react-xwhkhl](https://stackblitz.com/edit/react-xwhkhl)

### Steps to reproduce
下载最新版本antd，直接使用Modal，就默认不显示

### What is expected?
显示

### What is actually happening?
不显示

**Comment by afc163** [comment]
Your demo works fine.

**Comment by afc163** [comment]
<img width="551" alt="image" src="https://user-images.githubusercontent.com/507615/49576478-42675b00-f980-11e8-989a-40d9d3fe9abc.png">
