### ISSUE TITLE
The props 'loading' and 'dropdownRender' don't work in Select component in antd@3.9.x and antd@3.10.x ?

### ISSUE THREAD

**Issue by qxchen6** [ant-design/ant-design#13473]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i want it work in 3.9.x . but it doesn't and the document doesn't mention it . here is the example : https://codesandbox.io/s/2v9rq7yy80

### What does the proposed API look like?
work in 3.9.x

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

**Comment by afc163** [comment]
https://ant.design/changelog-cn#3.11.0

**Comment by pilipala6868** [comment]
In my case, it seems like the `loading` props doesn't work when I set `showArrow=false`. Just set `showArrow` to `true`.
