### ISSUE TITLE
upload组件无法使用这种.png~0x0.image这种格式的图片

### ISSUE THREAD

**Issue by minpuff** [ant-design/ant-design#13483]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
chrome 70 react 15

### Reproduction link
[https://codepen.io/minpuff/pen/wQVWmL?editors=0010](https://codepen.io/minpuff/pen/wQVWmL?editors=0010)

### Steps to reproduce
原有antd版本为3.1.6，直接升级为3.11.0

### What is expected?
即使antd版本升级，也能兼容之前的兼容的图片格式

### What is actually happening?
3.11.0无法兼容.png~0x0.image格式的图片

---
重现链接里头给的图片链接是一个无法访问的链接，但是此时upload组件应该是显示一张裂开的图，现在显示的效果不符合预期。
之所以用这种.png~0x0.image格式图片，是希望由自己来控制图片的大小。

**Comment by minpuff** [comment]
阅读了下源码，发现upload中的UploadList.tsx添加了一层是否是图片的校验，这块的校验规则能否优化下？
![image](https://user-images.githubusercontent.com/22900082/49625439-75f1c600-fa10-11e8-8dad-bc5ace313369.png)

**Comment by afc163** [comment]
@minpuff 来个 PR

**Comment by zy410419243** [comment]
不如加个参数比如 `regular` 去自定义筛选条件？

这方法里判断逻辑已经很麻烦了

**Comment by muzea** [comment]
把`isImageUrl`暴露成一个属性吗？
https://github.com/ant-design/ant-design/pull/13535

**Comment by minpuff** [comment]
尝试提了一个pr，详见[#13543](https://github.com/ant-design/ant-design/pull/13543/files)

**Comment by afc163** [comment]
Fixed by https://github.com/ant-design/ant-design/pull/15412
