### ISSUE TITLE
Allow to pass object to "value" prop of Select.Option

### ISSUE THREAD

**Issue by SergeyVolynkin** [ant-design/ant-design#13485]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Handling Select Options as Object, not as strings

### What does the proposed API look like?
*skill is `{ _id: "001f191e810c19729de860ea", title: "React" }`*

```
       let skillSuggestions = this.state.searchMatches.map((skill: any) => (
        <SelectOption value={skill} key={skill._id}>
          {skill.title}
        </SelectOption>
      ));
```

**Comment by afc163** [comment]
literal object would make equal judement very hard, for instance `{ a: 1 } !== { a: 1 }`.

https://github.com/ant-design/ant-design/issues/2857

**Comment by SergeyVolynkin** [comment]
@afc163 I would suggest using `_.isEqual(a, b)` in the case if we have object as value.

If I will come up with a PR will it be declined?

**Comment by SergeyVolynkin** [comment]
@afc163 Agree, it shouldn't work out of the box as magic.

How about writing the quick note in the documentation on how to handle object values as <Option/>'s in the <Select>'s?

**Comment by kaikun213** [comment]
How about giving the option to transform the output of the selection field?
I understand the issue with deep comparisons, but this could really help.

We use it inside a Form and it would be great  to do something like this with getFieldDecorators:

```
<Form.Item>
            {getFieldDecorator('dataIndex', {
              initialValue: object.id,
              transform: (objId) => objects.find(o => o.id === objId)
            })(
             <Select>
                {objects.map(o => (
                  <Select.Option key={o.id} value={o.id}>
                    {o.name}
                  </Select.Option>
                ))}
              </Select>,
            )}
</Form.Item>
```

**Comment by Austaras** [comment]
@afc163 you could provide `compareWith` props like `ng-zorro` though?
