### ISSUE TITLE
ie8 下运行太缓慢了， 几乎没法操作

### ISSUE THREAD

**Issue by bugbuka** [ant-design/ant-design#13493]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
 1.11.6

### Environment
ie8, windows xp

### Reproduction link
[https://1x.ant.design/](https://1x.ant.design/)

### Steps to reproduce
render()方法执行很慢

### What is expected?
ie8 下能正常操作

### What is actually happening?
ie8 下运行太缓慢了， 几乎没法操作。  
公司网站改版必须支持ie8, 我们使用了ant design 1.11.6， 已经花了很大的功夫解决各种兼容性问题，网页没有任何的 js 错误了， 页面也能打开。  
但是 render()方法执行很慢， 特别是表单， 修改任何一个控件，例如Input, onChange事件都会重新render 整个表单，这样造成几乎无法在 Input 控件输入内容。  

---
1, 对于表单控件， 更精细的控制是： 如果某Input改变， 只重新刷新有依赖关系的其他 field, 而不应该刷新整个 form  
2, 就单次的render() 来说， ie8 环境下运行太慢， 还有解决办法吗？

以下是在 package.json 中使用的 依赖包
`  
"dependencies": {  
    "accounting": "0.4.1",  
    "antd": "1.11.6",  
    "axios": "0.16.2",  
    "babel-polyfill": "6.9.0",  
    "babel-runtime": "6.9.0",  
    "bignumber.js": "4.0.2",  
    "bowser": "1.7.3",  
    "classnames": "2.2.5",  
    "codemirror": "5.27.4",  
    "console-polyfill": "0.3.0",  
    "enumify": "1.0.4",  
    "es5-shim": "4.5.8",  
    "es6-promise": "3.2.1",  
    "extend": "3.0.0",  
    "history": "2.1.1",  
    "hoist-non-react-statics": "1.0.5",  
    "immutable": "3.8.1",  
    "lodash": "3.10.1",  
    "matchmedia-polyfill": "0.3.0",  
    "moment": "2.18.1",  
    "object-hash": "1.2.0",  
    "qs": "6.5.1",  
    "rc-queue-anim": "1.6.5",  
    "rc-echarts": "0.3.1",  
    "react": "0.14.9",  
    "react-document-title": "2.0.3",  
    "react-dom": "0.14.9",  
    "react-html-parser": "2.0.2",  
    "react-router": "2.3.0",  
    "react-router-scroll": "^0.4.4",  
    "store": "2.0.12"  
  },  
  "devDependencies": {  
    "autoprefixer": "6.3.6",  
    "babel-core": "6.9.0",  
    "babel-eslint": "6.0.4",  
    "babel-loader": "6.2.4",  
    "babel-plugin-import": "1.2.1",  
    "babel-plugin-transform-decorators-legacy": "1.3.4",  
    "babel-plugin-transform-react-jsx-source": "6.22.0",  
    "babel-plugin-transform-runtime": "6.15.0",  
    "babel-plugin-transform-proto-to-assign": "7.0.0-beta.3",  
    "babel-preset-es2015": "6.9.0",  
    "babel-preset-es2015-ie": "6.7.0",  
    "babel-preset-react": "6.5.0",  
    "babel-preset-stage-1": "6.5.0",  
    "babel-register": "6.9.0",  
    "chai": "3.5.0",  
    "clean-webpack-plugin": "0.1.16",  
    "copy-webpack-plugin": "4.0.1",  
    "css-loader": "0.23.1",  
    "es3ify-loader": "0.2.0",  
    "eslint": "2.10.2",  
    "eslint-config-airbnb": "9.0.1",  
    "eslint-import-resolver-webpack": "0.8.3",  
    "eslint-plugin-import": "1.8.0",  
    "eslint-plugin-jsx-a11y": "1.2.0",  
    "eslint-plugin-react": "5.1.1",  
    "file-loader": "0.8.5",  
    "html-webpack-plugin": "2.29.0",  
    "json-loader": "0.5.4",  
    "less": "2.3.1",  
    "less-loader": "2.2.3",  
    "mocha": "2.4.5",  
    "node-sass": "4.5.3",  
    "pixrem": "3.0.0",  
    "pleeease-filters": "3.0.0",  
    "postcss": "5.0.21",  
    "postcss-calc": "5.2.1",  
    "postcss-color-function": "2.0.1",  
    "postcss-custom-media": "5.0.1",  
    "postcss-custom-properties": "5.0.1",  
    "postcss-custom-selectors": "3.0.0",  
    "postcss-import": "8.1.2",  
    "postcss-loader": "0.9.1",  
    "postcss-media-minmax": "2.1.2",  
    "postcss-nesting": "2.3.1",    
    "postcss-selector-matches": "2.0.1",      
    "postcss-selector-not": "2.0.0",  
    "pre-commit": "1.2.2",  
    "react-hot-loader": "3.0.0-beta.6",  
    "redbox-react": "1.4.3",   
    "sass-loader": "4.1.1",  
    "style-loader": "0.13.1",  
    "stylelint": "7.10.1",  
    "stylelint-config-standard": "16.0.0",  
    "url-loader": "0.5.7",  
    "webpack": "1.15.0",  
    "webpack-dev-server": "1.16.5"  
  }  
`

**Comment by afc163** [comment]
1.x 是两年前的版本，抱歉已经不维护了。

**Comment by travelk** [comment]
我ie11以下都不考虑了 你怎么还要兼容ie8 如果真的要兼容直接用jquery和bootstrap吧
