### ISSUE TITLE
[iOS Safari]表格内容滚动到边后不能传递滚动效果到上层可滚动容器，或者不流畅

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#13498]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
iPhone 6sp iOS 12.1.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xlw3o40z9p)

手机直接访问 https://xlw3o40z9p.codesandbox.io/

### Steps to reproduce
当表格处在一个限高可滚动容器中，且同时设置表格的x，y为具体值（表格用y限高），滚动表格内容到顶部或者底部后不能使容器继续滚动，或者不流畅

### What is expected?
多层滚动条流程滚动

### What is actually happening?
到边后滚不动或者不流畅

**Comment by afc163** [comment]
好像没什么办法，都是原生的滚动条。

**Comment by yoyo837** [comment]
去掉x，留y很ok哦

**Comment by afc163** [comment]
现在没有精力兼容移动端，欢迎帮忙排查然后给 PR。
