### ISSUE TITLE
希望Table能够定制 expandIcon

### ISSUE THREAD

**Issue by snadn** [ant-design/ant-design#1349]
我期望的效果如图，但目前无法通过配置Table组件实现。

![image](https://cloud.githubusercontent.com/assets/1269858/14339577/32abbdfa-fcb2-11e5-8e04-11911ddbd057.png)

**Comment by afc163** [comment]
建议自行渲染 cell ，用 expandedRowKeys 进行控制。

**Comment by snadn** [comment]
@afc163 文档上没有看到相关的参数，能说详细一点吗？谢谢！

**Comment by snadn** [comment]
@afc163 明白你的意思了，自己管理 expandedRowKeys 来处理。我试一下吧，谢谢！

**Comment by afc163** [comment]
expandedRowKeys 和 onExpandedRowsChange 来配合，可能需要探索一下。

https://github.com/react-component/table

http://react-component.github.io/table/examples/expandedRowRender.html
