### ISSUE TITLE
Sider 布局在Edge样式bug

### ISSUE THREAD

**Issue by llcgh** [ant-design/ant-design#13492]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
win10 、edge、

### Reproduction link
[https://ant.design/components/layout-cn/](https://ant.design/components/layout-cn/)

### Steps to reproduce
 <Sider width={240} style={{height: 'calc(100vh - 325px)', background: '#ccc', overflow: 'hidden'}} theme="light">
                  <div style={{width: 470, height: 'calc(100vh - 325px)'}}>
                     <div style={{overflowY: 'scroll', paddingRight: '100px', marginRight: '-100px'}}>
                        {<TransferComponet/>}
                     </div>
                  </div>
               </Sider>

--------------------------------------------------------------
此没有重现链接。请试一下这段代码。 slider 默认200高度，自定义样式无法加上去，里边的内容都被隐藏了。

### What is expected?
可以自定义style

### What is actually happening?
高度一直为200，

---
 win10 的市场覆盖率很高了，edge作为自带浏览器，使用者很高的。i请开发者多多关注edge兼容。注：e11下正常显示。

**Comment by afc163** [comment]
欢迎 PR，antd 会因你更美好。

**Comment by afc163** [comment]
https://www.oschina.net/news/102458/goodbye-edgehtml

感觉很快这些问题也不用解决了。
