### ISSUE TITLE
自定义input file使用Button组件无法触发

### ISSUE THREAD

**Issue by zhangyuliangzyl** [ant-design/ant-design#13506]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
```
<label>
    <input type="file"  style="display: none"/>
    <Button>选择文件</Button>
</label>
```
类似这样的组件，希望可以用Button来完成

### What does the proposed API look like?
```
<label>
    <input type="file"  style="display: none"/>
    <Button>选择文件</Button>
</label>
```
这样的代码能work就行，目测是因为Button底层用的是原生button元素渲染的，或者添加个什么属性让它用div渲染

**Comment by afc163** [comment]
https://codesandbox.io/s/yq1l5272zj
