### ISSUE TITLE
Unexpected sorter on table's titles, clicking it triggers the `onChange` callback

### ISSUE THREAD

**Issue by zmayor** [ant-design/ant-design#13507]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
windows, chrome 70

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2zkv16p8xn)

### Steps to reproduce
Click table's titles

### What is expected?
Click table's titles, nothing happen.

### What is actually happening?
I did't set any sorter config in columns, but table's title rendered with sorter. Then clicking table's title would trigger 'onChange'

**Comment by afc163** [comment]
Fixed in antd@3.10.1 via https://github.com/ant-design/ant-design/issues/12515
