### ISSUE TITLE
TreeSelect  position issue

### ISSUE THREAD

**Issue by HeWenKe** [ant-design/ant-design#13500]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
chrome

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
change  all  checked and  its children ,the select option lists  position is wrong.

### What is expected?
well

### What is actually happening?
bug

**Comment by HeWenKe** [comment]
![image](https://user-images.githubusercontent.com/12146992/49634631-4ce52b80-fa38-11e8-8f9a-b5125c78ea74.png)

This can be reproduced from official website of antd. See the sreenshot above that I submitted. whenever you make the choices more than the max-with of the search input and then cancel one to make the height of the input back to normal. The dropdown top will no more auto-calculated.

**Comment by afc163** [comment]
<img width="1409" alt="image" src="https://user-images.githubusercontent.com/507615/49640421-832aa700-fa48-11e8-803b-988b83b2c496.png">

**Comment by afc163** [comment]
works on my chrome: 70.0.3538.110

**Comment by shuozhang2016** [comment]
The reproduced order should be:
1. make choice on Child Node1
2. make choice on Child Node3
3. make choice on Child Node 4
4. remove choice of Child Node4
thats it!

@afc163

**Comment by afc163** [comment]
<img width="424" alt="image" src="https://user-images.githubusercontent.com/507615/49641006-f4b72500-fa49-11e8-9b40-cb27ececf9d7.png">

Reproduced~

It will be better if you can provide reproducible step in first place.

**Comment by HeWenKe** [comment]
thanks  @afc163

**Comment by zy410419243** [comment]
Catch it, [there](https://github.com/react-component/tree-select/blob/master/src/Select.jsx#L968) need a function to update state of `Popup`'s align.

I will push a PR later.

**Comment by zombieJ** [comment]
Fix from [PR](https://github.com/react-component/tree-select/pull/135) merged: https://codesandbox.io/s/4qr9wvz7m0
