### ISSUE TITLE
引用 @import '~antd/dist/antd.less'; 有语法错误

### ISSUE THREAD

**Issue by welot** [ant-design/ant-design#13512]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
create-react-app, react 16.3

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/tree/style/index.less](https://github.com/ant-design/ant-design/blob/master/components/tree/style/index.less)

### Steps to reproduce
在css 文件中，引用 @import '~antd/dist/antd.less';

### What is expected?
样式正确

### What is actually happening?
./node_modules/antd/lib/tree/style/index.less (./node_modules/css-loader??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/antd/lib/tree/style/index.less)
Syntax error: Unknown word (10:1)

   8 | @tree-showline-icon-color: @text-color-secondary;
   9 | 
> 10 | .antCheckboxFn(@checkbox-prefix-cls: ~"@{ant-prefix}-tree-checkbox");
     | ^
  11 | 
  12 | .@{tree-prefix-cls} {

**Comment by afc163** [comment]
你需要用 less-loader 才能引入 less。
