### ISSUE TITLE
在 windows 下面开发本项目

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#1352]
之前有` issue` 也提到 windows 下面开发的问题 ,主要是以下几个问题导致的,看需不需要支持?

- `package.json` 里面的环境变量 (可以使用`better-npm-run`解决)
- `rm` 命令(可以使用`rimraf`解决)
- `./scripts/build-website.js` 生成的文件路径反斜杠的问题 (可以替换成`/`解决) 

`\components\upload\index.md`  中的 `\u` 在 windows 执行的时候会报错,替换成 `/`也可以解决这个问题

**Comment by afc163** [comment]
欢迎 PR ~

我们这里基本没有调试环境。

**Comment by bang88** [comment]
👌

**Comment by iskyshop** [comment]
windows下开发建议使用固态硬盘，否则读取文件会导致webstorm死机

**Comment by jingweizheng** [comment]
@iskyshop ssd一样死机，将node_modules设置成excluded就可以了

**Comment by ksh033** [comment]
runCmd('which', ['tnpm'], (code) => {
是否能判断是否是window换成where.

**Comment by shenduxian1** [comment]
@jingweizheng excluded还是死机怎么破。。。

**Comment by jingweizheng** [comment]
@shenduxian1 两步：
1.gitignore添加node_modules（git相关程序有时候会建索引）
2.webstorm下创建node_modules空文件夹，设置exclude，然后npm install，这样webstorm就不会索引而卡死了

**Comment by afc163** [comment]
关了，有需求的话可以本地兼容改造并直接给我们 PR ~

**Comment by shenduxian1** [comment]
@David1119 妥了。。方案2可行。。囧

**Comment by shenduxian1** [comment]
@David1119 非常感谢
