### ISSUE TITLE
Allow customization of ant-table-placeholder in <Table/>

### ISSUE THREAD

**Issue by SergeyVolynkin** [ant-design/ant-design#13526]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allow setting any React component as a placeholder for an empty table

### What does the proposed API look like?
```
<Table 
    …
    placeholder={()=><div>some component<div/>}
    …
/>
```
**Simple use case:**
1. Set a colored `<div/>` of certain height as a placeholder

**Comment by afc163** [comment]
```jsx
<Table locale={{ notFoundContent: <Icon /> }} />
```

**Comment by Tommy-White** [comment]
@afc163, @yesmeck 
Is there any consideration for this custom layout when data is empty?
![12 -17-2018 22-44-13](https://user-images.githubusercontent.com/24240963/50094552-6bc09a80-024e-11e9-9821-a967365d6a2c.gif)
