### ISSUE TITLE
InputNumber在Form里，设置了 getFieldProps之后onChange回调不生效

### ISSUE THREAD

**Issue by juemin90** [ant-design/ant-design#1353]
不知道是有意为之还是bug？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1286
https://github.com/ant-design/ant-design/issues/1151
https://github.com/ant-design/ant-design/issues/1280
https://github.com/ant-design/ant-design/issues/1234

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1533
