### ISSUE TITLE
Badge is reacting weirdly!

### ISSUE THREAD

**Issue by jamalabo1** [ant-design/ant-design#13532]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
Windows 10, Google Chrome, Reactjs (SSR) version 16.6.3

### Reproduction link
[https://ant.design/components/badge](https://ant.design/components/badge)

### Steps to reproduce
if there is any onMouseEnter event, remove it because that what cause the issue!

### What is expected?
not to re-render the component (maybe)

### What is actually happening?
re-rendering the component / re-popup.

![aw](https://user-images.githubusercontent.com/25992049/49702908-fe39bc00-fc06-11e8-8170-582e3ad7394e.gif)

---
tested on Firefox also.

**Comment by jamalabo1** [comment]
here is an preview repo:
https://codesandbox.io/s/k26z91x385

Actually i have figured the issue!
when `globalNavSecondaryItems` and `globalNavPrimaryItems` are functions this happens but when they are arrays it does not, 

anyway i have addressed this, you may can fix it!

**Comment by ztplz** [comment]
I don't think this problem relate to `Antd`.  It flashes because it re-rendered. It's not a re-render caused by `Antd` but a problem with third-party libraries.
