### ISSUE TITLE
table title 不支持同级元素，只能单个  报错方法: getColumnTitle

### ISSUE THREAD

**Issue by lvwei900901** [ant-design/ant-design#13542]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.1

### Environment
All

### Reproduction link
[https://ant.design/components/table-cn/#header](https://ant.design/components/table-cn/#header)

### Steps to reproduce
table ->  column -> title:<div><span>1</span><span>2</span></div>

### What is expected?
table column的title属性支持同级元素

### What is actually happening?
table column的title属性不支持同级元素

**Comment by feibi** [comment]
getColumnTitle返回有问题，title为ReactNode时应该直接返回

**Comment by afc163** [comment]
https://codesandbox.io/s/n7kwz8z8y0

**Comment by afc163** [comment]
Fixed in 3.11.2
