### ISSUE TITLE
非常规FormItem内容的表单验证，如何进行。。。

### ISSUE THREAD

**Issue by blade254353074** [ant-design/ant-design#1354]
# 我在 Form 中添加了这么一段

```jsx
<FormItem {...formItemLayout} label="主产品：" hasFeedback>
  <InputGroup className="ant-group">
    <Input
      {...getFieldProps('main_id')}
      readOnly
      value={this.props.formData.main_id}
      onChange={this.props.fieldChange(this.props.formData, 'main_id')}
    />
    <div className="ant-input-group-wrap">
      <Button type="ghost" onClick={this.props.selectProduct(this.props.formData, 'main_id')}>选择产品</Button>
    </div>
  </InputGroup>
</FormItem>
```

## 希望可以加入到表单校验中

但实际上这个并没有，如下图

![image](https://cloud.githubusercontent.com/assets/9346008/14344380/cfa4e394-fcd9-11e5-9f3f-0be04a5a745f.png)

不知道这种情况可以解决么

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1286
https://github.com/ant-design/ant-design/issues/1151
https://github.com/ant-design/ant-design/issues/1280
https://github.com/ant-design/ant-design/issues/1234
https://github.com/ant-design/ant-design/issues/1353

**Comment by blade254353074** [comment]
@afc163 非常感谢。。。下次我应该先搜一下
