### ISSUE TITLE
Table table sorter only works in descent order, when clicking ascent arrow table does not sort。表格排序只有降序生效，点击升序箭头时无法排序

### ISSUE THREAD

**Issue by Codyooo** [ant-design/ant-design#13555]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.1

### Environment
os version: mac Mojave   
brower: chrome70.0  
react: 16.6.3 
react-dom:16.6.3

### Reproduction link
[https://codepen.io/codyooo/pen/zyxjvq](https://codepen.io/codyooo/pen/zyxjvq)

### Steps to reproduce
步骤请看codepen链接

### What is expected?
表格升序降序均可正常工作

### What is actually happening?
只有降序能正常排序，点击升序按钮无反应

**Comment by zy410419243** [comment]
试试点第三下

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/OrPZde

该补习 js 了。

```diff
- sorter: (a, b) => b.count < a.count
+ sorter: (a, b) => b.count - a.count
```

**Comment by Codyooo** [comment]
> https://codepen.io/afc163/pen/OrPZde
> 
> 该补习 js 了。
> 
> ```diff
> - sorter: (a, b) => b.count < a.count
> + sorter: (a, b) => b.count - a.count
> ```

感谢大佬！
