### ISSUE TITLE
Pagination 能否自定义分页

### ISSUE THREAD

**Issue by duzliang** [ant-design/ant-design#1355]
能否自定义分页，如只有`上一页`，`当前页`，`下一页`三个操作
有时可能并需要翻到具体某一页，只需要处理所有数据，所以这种操作更简洁

现在如果只显示一页内容的话，上一页和下一页按钮的点击状态无法控制，默认都是不可点击的

**Comment by afc163** [comment]
可以用样式隐藏其他元素。
