### ISSUE TITLE
Looking for the ability to create custom select options. If I could just pass a react node to the option that'd be great.

### ISSUE THREAD

**Issue by tjones0808** [ant-design/ant-design#13553]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a request for custom select options and dropdowns.

### What does the proposed API look like?
Simply let me pass react jsx to the option and render it instead of stripping it out.

**Comment by afc163** [comment]
`<Option><div>anything you need</div></Option>`

If this can not satisfy, you can also try `dropdownRender`.
