### ISSUE TITLE
刷新浏览器，布局消失了

### ISSUE THREAD

**Issue by Chocolate-Lee** [ant-design/ant-design#13556]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
最新版本

### Reproduction link
[https://www.yuque.com/ant-design/course/ipsba8](https://www.yuque.com/ant-design/course/ipsba8)

### Steps to reproduce
按教程书写的路由配置：https://www.yuque.com/ant-design/course/ipsba8

### What is expected?
刷新浏览器，布局可以正常显示

### What is actually happening?
刷新浏览器，布局消失了，只展示页面

**Comment by afc163** [comment]
课程问题建议直接反馈到语雀评论区。
