### ISSUE TITLE
popover 点击content的空白区域，会向上冒泡给外层父元素

### ISSUE THREAD

**Issue by chaserstrong** [ant-design/ant-design#13568]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
mac chrome70.0.3538.110

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kkk7l33o33)

### Steps to reproduce
```
import React from "react";
import ReactDOM from "react-dom";
import { Popover, Button, Icon } from "antd";
import "antd/dist/antd.css";

function App() {
  const content = (
    <div>
      <div style={{ width: 300, height: 300, backgroundColor: "red" }}>
        fdlsakfsa
      </div>
    </div>
  );
  const click = e => {
    console.log(e);
  };
  return (
    <div
      className='container'
      onClick={() => {
        alert('container');
      }}
    >
      <Popover
        content={content}
        onClick={e => {
          alert('popover-content');
          e.stopPropagation();
        }}
        title=""
        trigger="focus"
      >
        <Button type="primary">Hover me</Button>
      </Popover>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);

```

### What is expected?
点击红色底区域，不应该弹出 'container'。

### What is actually happening?
弹出了container，并且 e.stopPropagation()也无法禁止冒泡。
如果向上冒泡是必须的，那至少应该提供一个给用户禁止冒泡的接口。

**Comment by afc163** [comment]
https://codesandbox.io/s/50xmq23z5k

**Comment by chaserstrong** [comment]
> https://codesandbox.io/s/50xmq23z5k

打扰了。。

**Comment by tharyckgusmao** [comment]
@chaserstrong  You found any solution ? I have a same problem.

**Comment by drdevelop** [comment]
@afc163 如果我点击内容的padding区域依然无法阻止冒泡，因为这个padding是popover内部控制的，其实弹出的整张卡片点击的event是否应该透传出来给用户整张卡片去阻止冒泡，而不是分别点击标题和content依次去处理冒泡问题

**Comment by afishhhhh** [comment]
> @afc163 如果我点击内容的padding区域依然无法阻止冒泡，因为这个padding是popover内部控制的，其实弹出的整张卡片点击的event是否应该透传出来给用户整张卡片去阻止冒泡，而不是分别点击标题和content依次去处理冒泡问题

@afc163 我也是...

**Comment by bolosea** [comment]
> https://codesandbox.io/s/50xmq23z5k

我遇到的问题是使用Popconfirm的时候冒泡了，它内部用的是Overlay，没法像你那样子阻止冒泡了。。
