### ISSUE TITLE
[Table] default filter button can not click!

### ISSUE THREAD

**Issue by TseHang** [ant-design/ant-design#13563]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Chrome 70.03

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mojkll0plx)

### Steps to reproduce
1. Click filtered icon.
2. Select one option.
3. Click `OK` or `Reset`
4. But!! It can not be clicked

### What is expected?
It can be clicked.

### What is actually happening?
.ant-dropdown:before overwrape the UI.

![](https://i.imgur.com/j0DqHal.png)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/6ee4c1a2905b1a5f75415adf59b73f5ee567dc13
