### ISSUE TITLE
in Upload component, let "beforeUpload" method always return false, file list still show

### ISSUE THREAD

**Issue by cuiqiusheng** [ant-design/ant-design#13566]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
macos12 & chrome 70.0.3538.110

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://o4qy6o2j05.codesandbox.io/)

### Steps to reproduce
upload something in "Upload" component, the method "beforeUpload" always return false, but the file list still show

### What is expected?
when the method "beforeUpload" return false, file list do not show

### What is actually happening?
when the method "beforeUpload" return false, file list show

**Comment by afc163** [comment]
It is by designed.

https://github.com/ant-design/ant-design/pull/9340#issuecomment-364841597
