### ISSUE TITLE
DatePicker format time select column not work

### ISSUE THREAD

**Issue by houshiduo** [ant-design/ant-design#13578]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
MacOS: 10.14.1 Chrome: 70.0.3538.110

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3rjj63zpz5)

### Steps to reproduce
DatePicker set field format="YYYY-MM-DD HH:mm" and showTime
Click select time.

### What is expected?
While part of format is omitted, the corresponding column in panel will disappear, too.

### What is actually happening?
column is not omitted.

**Comment by zy410419243** [comment]
Check [this](https://codesandbox.io/s/4rq2lr21l4)

**Comment by houshiduo** [comment]
@zy410419243  "OK" button is not work? But it's a good idea.

**Comment by zy410419243** [comment]
Maybe there is something wrong with the code, you can try it yourself by apis.

**Comment by houshiduo** [comment]
@zy410419243 Yep, i think i've solved the problem, look [this](https://codesandbox.io/s/3rjj63zpz5), thx.
