### ISSUE TITLE
Focus behaviour in form items

### ISSUE THREAD

**Issue by queimadus** [ant-design/ant-design#1358]
Most form items, except `Input`, do not visually show when they are in focused state.

Is this a ant component problem or an underlying component (`rc-*`) problem?

**Comment by afc163** [comment]
Yep, should fix it in `1.0.0`, Pull request welcomes also.

**Comment by afc163** [comment]
Components that lost focused style:

- [ ] Select
- [ ] Radio
- [ ] RadioButton
- [ ] Checkbox

**Comment by afc163** [comment]
ref to #978

**Comment by benjycui** [comment]
Done, close now.
