### ISSUE TITLE
Datepicker 组件貌似只能通过一个 Input 触发，期望可以自定义触发组件

### ISSUE THREAD

**Issue by sarike** [ant-design/ant-design#13580]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
业务中经常遇到链接组件、按钮组件触发日历选择日期的场景。

### What does the proposed API look like?
```
<DatePicker
    open={this.state.open}
    showInput={false} getTarget={() => this.dateTrigger}
    onChange={value => this.setState({ value, open: false });}
/>
<a
    href="#"
    ref={node => { this.dateTrigger = node}}
    onClick={e => { e.preventDefault(); this.setState({ open: true }); }}
>选择时间</a>
```

- showInput：用来控制是否显示触发日期选择的输入框
- open：以受控的方式控制日历的展示
- getTarget：以获取触发组件，以便定位日历面板的位置

**Comment by afc163** [comment]
We suggest you using [rc-calendar](http://github.com/react-component/calendar) make your own DatePicker.

**Comment by afc163** [comment]
https://codesandbox.io/s/blazing-resonance-eegnq
