### ISSUE TITLE
Form.Item 有多个 child 时，表单验证该如何触发提示样式

### ISSUE THREAD

**Issue by blade254353074** [ant-design/ant-design#1359]
## 当写入如下 FormItem 代码时

```jsx
<FormItem {...formItemLayout} label="主产品图片：" required hasFeedback>
  <InputGroup>
    <Input
      {...getFieldProps('main_img', {
        rules: [{
          required: true,
          message: '请上传主产品图'
        }],
        initialValue: formData.main_img,
        trigger: 'onBlur',
        validateTrigger: 'onBlur'
      })}
      disabled
      value={formData.main_img}
      onChange={this.props.fieldChange(formData, 'main_img')}
    />
    <div className="ant-input-group-wrap">
      <Upload {...this.props.uploadProps}>
        <Button type="ghost"><Icon type="upload" />上传</Button>
      </Upload>
    </div>
  </InputGroup>
</FormItem>
```

此时，help required validateStatus 无法自动生成

在调用 `this.props.form.validateFields()` 后，控制台可以看到信息未填写的提示。

但页面上没有提示信息

这种情况下应如何做才能将提示信息正确展示

**Comment by benjycui** [comment]
http://ant.design/components/form/#demo-validate-basic

用户名那个

**Comment by taditang** [comment]
Input组件父级必须是FormItem才会自动显示提示信息,但这样的结构又会破坏InputGroup的样式, 必须自己写CSS修正.
`<FormItem {...formItemLayout} label="主产品图片：">
  <InputGroup>
     <FormItem required hasFeedback>
    <Input
      {...getFieldProps('main_img', {
        rules: [{
          required: true,
          message: '请上传主产品图'
        }],
        initialValue: formData.main_img,
        trigger: 'onBlur',
        validateTrigger: 'onBlur'
      })}
      disabled
      value={formData.main_img}
      onChange={this.props.fieldChange(formData, 'main_img')}
    />
     </FormItem>
    <div className="ant-input-group-wrap">
      <FormItem required hasFeedback>
      <Upload {...this.props.uploadProps}>
        <Button type="ghost"><Icon type="upload" />上传</Button>
      </Upload>
      </FormItem>
    </div>
  </InputGroup>
</FormItem>`
