### ISSUE TITLE
date picker

### ISSUE THREAD

**Issue by inthiyaz7876** [ant-design/ant-design#13607]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
React

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pk4n52670m)

### Steps to reproduce
Demo available in this link "https://codesandbox.io/s/pk4n52670m" . Can you take a look into it .The problem is when I select a date the value coming in alerts ,So before I click on (ok) button I got the value. But I need that value after click on ok button only.  

### What is expected?
I need the  selected value after click on (ok) button. 

### What is actually happening?
I am getting the value before I click on ok button.

---
I have a scenario by selecting the date doing API call . So If I change the date I am ding again API call, So instead of doing multiple API calls I want Only once when I click on ok button.

**Comment by zy410419243** [comment]
https://codesandbox.io/s/ko154jm105
