### ISSUE TITLE
antd table 树形结构支持异步加载。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#13600]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在要加载一个行政区域的树形table，但是因为行政区域的树太大了。。导致页面卡死，所以要用ajax。

### What does the proposed API look like?
现在要加载一个行政区域的树形table，但是因为行政区域的树太大了。。导致页面卡死，所以要用ajax。

**Comment by zy410419243** [comment]
https://ant.design/components/tree-cn/#components-tree-demo-dynamic

这个不能满足么

**Comment by afc163** [comment]
支持的，自行异步加载数据结构即可。

**Comment by zy410419243** [comment]
可能楼主想法是点了每行前的加号才去加载下一级数据的，似乎没有加号的点击事件？

**Comment by afc163** [comment]
onExpand

**Comment by YardWill** [comment]
只有onExpand而没有expandedRowRender属性是并不会展示加号，也就是说需要自己去实现整个循环渲染吗？是否可以像tree一样我只需要更新数据而不需要自己写组件？ @afc163

**Comment by YardWill** [comment]
解决了 给需要展开的项手写一个children: [], 等待onExpand事件触发再去动态添加数据， 如果该项不需要展开，直接不写children或者直接children: undefined.

**Comment by xicunyang** [comment]
> 解决了 给需要展开的项手写一个children: [], 等待onExpand事件触发再去动态添加数据， 如果该项不需要展开，直接不写children或者直接children: undefined.

请问有做loading吗？想在展开区域做局部loading，没有找到好的解决方式，有点发愁

**Comment by miaojinsing** [comment]
> > 解决了 给需要展开的项手写一个children: [], 等待onExpand事件触发再去动态添加数据， 如果该项不需要展开，直接不写children或者直接children: undefined.
> 
> 请问有做loading吗？想在展开区域做局部loading，没有找到好的解决方式，有点发愁

我翻遍了文档也没见到能想element 那样的api
