### ISSUE TITLE
Why doesn't return response when response status between 200 and 300?

### ISSUE THREAD

**Issue by soolaugust** [ant-design/ant-design#13606]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. when we provide more information in response body when response status is not between 200 and 300. but when we use antd, we found we cannot receive them. 
2. as deep checking, we found the issue is exist in request.js:

``` javascript
      if (status === 401) {
        // @HACK
        /* eslint-disable no-underscore-dangle */
        window.g_app._store.dispatch({
          type: 'login/logout',
        });
        return;
      }
      // environment should not be used
      if (status === 403) {
        router.push('/exception/403');
        return;
      }
      if (status <= 504 && status >= 500) {
        router.push('/exception/500');
        return;
      }
      if (status >= 404 && status < 422) {
        router.push('/exception/404');
      }
```

you can see that there's no response return, may I know why antd doesn't support in default?

### What does the proposed API look like?
when error status returns, it would provide response.

``` javascript
 if (status >= 404 && status < 422) {
        router.push('/exception/404');
      }
````

would change like this:

``` javascript

 if (status >= 404 && status < 422) {
        router.push('/exception/404');
        return e.response;
      }
```

**Comment by afc163** [comment]
It is not antd issue.
