### ISSUE TITLE
table的表头里面能不能加search框

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#1360]

**Comment by AllenZeng** [comment]
这个你其实可以自己实现搜索功能，向服务器请求符合要求的数据，重新改变table的data值即可，另外table有一个配置选项onFilter（本地模式下，确定筛选的运行函数），你可以试试

**Comment by afc163** [comment]
业务多变，组件暂不支持，后续可能会作为模式的演示代码来提供。

**Comment by XUGAOBO** [comment]
嗯,onFilter用过,很好使用,可以根据自己的规则筛选,但是如果要是能在onFilter下面加上一个搜索框来应对那些对整个字段数据的搜索我感觉挺好
