### ISSUE TITLE
Layout.Sider default collapsed width is inconsistent with the documentation

### ISSUE THREAD

**Issue by wjielim** [ant-design/ant-design#13603]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
react 16.6.3, Google Chrome Version 70.0.3538.110 (Official Build) (64-bit), Windows 10 64-bit

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kkm16z4y2o)

### Steps to reproduce
1. Open the reproduction link
2. Inspect the sider width
3. The sider width is shown as 80px, but in the documentation is stated 64px by default

### What is expected?
Layout.Sider width is 64px by default when collapsed

### What is actually happening?
Layout.Sider width is 80px by default when collapsed

**Comment by ztplz** [comment]
Just tested a few demos, it seems that the docs is wrong. @afc163  Is the default width 80?

**Comment by zy410419243** [comment]
[Default width is 80, docs is wrong.](https://github.com/ant-design/ant-design/blob/master/components/layout/Sider.tsx#L78)

**Comment by wjielim** [comment]
Thank you for the prompt response. Also, I think it's worth mentioning how I found this issue. 

I was using the ant design sketch file to draw a mock-up for a web project. It appears that the dimension in the sketch file is 64px, but later when I do coding I found out the appearance is different from my mock-up. 

The sketch design resource might need to update as well.
