### ISSUE TITLE
FunctionComponent support for customized-form-controls

### ISSUE THREAD

**Issue by xiaoxiangmoe** [ant-design/ant-design#13609]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ant-design/ant-design/blob/377062bc9b30a0d1cdc7be398577f6b97c7299af/components/form/demo/customized-form-controls.md#en-us

> It must be a class component.

I want to it could be function component with react-hooks.

### What does the proposed API look like?

I want to it could be function component with react-hooks.

**Comment by yangsisi0422** [comment]
Version
3.11.6

Environment
react 16.3.14

Steps to reproduce
Use Select in getFieldDecorator

What is expected?
No warning.

What is actually happening?
Warning: Function components cannot be given refs. Attempts to access this ref will fail.
![image](https://user-images.githubusercontent.com/13655750/50415439-ed6b8600-0855-11e9-90f4-b3867c8af3df.png)

**Comment by rankun203** [comment]
Functional components is getting more and more popular these days, Most of our components are functional, so is our input component.

Is there a way to safely fix this error? Any workaround would appreciated.
