### ISSUE TITLE
按钮点击后其激活背景色仍然显示

### ISSUE THREAD

**Issue by uni-zheng** [ant-design/ant-design#13608]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
mac chrome

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
打开 https://ant.design/components/button-cn/ 随便点击一个按钮 

### What is expected?
点击后按钮背景色恢复

### What is actually happening?
点击后按钮背景色仍处于激活状态颜色

**Comment by afc163** [comment]
It is chrome brower default behavior that we are not gonna to change it.
