### ISSUE TITLE
Make Wave wrapper optional

### ISSUE THREAD

**Issue by meinte** [ant-design/ant-design#13614]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Some components such as Button and Switch automatically get wrapped in the Wave component. This should be optional as to give developers the choice whether they want that effect or not.

### What does the proposed API look like?
For now a simple boolean prop for the affected components would suffice: renderWave [true/false]. Wave.js will then read out it's children props to decide whether or not to render the onClick effect. Alternatively the components themselves could simply choose to render with or without being wrapped by the Wave component.

```javascript
renderWave = () => {
//figure out child component prop has renderWave true
}
onClick = (node: HTMLElement, waveColor: string) => {
    if (!node || isHidden(node) || node.className.indexOf('-leave') >= 0 || !this.renderWave()) {
      return;
    }
    ...
}
```

OR
```javascript
{
....
const btn = 
         <button
          {...otherProps as NativeButtonProps}
          type={htmlType || 'button'}
          className={classes}
          onClick={this.handleClick}
          title={title}
          ref={this.saveButtonRef}
        >
          {iconNode}
          {kids}
        </button>

if(!this.props.renderWave){
return btn;
}
return (
      <Wave>
         {btn}
      </Wave>
    );
}
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/2c79d2a7c1a908fe9ba0b62e5202a3fd686f15b4/components/style/themes/default.less#L519

Set `@wave-animation-width` to 0.
