### ISSUE TITLE
How to get the page size changer options to be 10, 20 rather than 10/ page, 20/page etc in AntD pagination.

### ISSUE THREAD

**Issue by sreenath124** [ant-design/ant-design#13619]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Display the page size options.
Currently, the options appears like 10/ page, 20/page etc. I want it to be displayed as 10, 20 only.
### What does the proposed API look like?
`showPageSizeOptionsWithPageAppended = false` some thing like this.

**Comment by afc163** [comment]
You can try `<Pagination locale={{ items_per_page: '' }} />`

https://github.com/react-component/pagination/blob/72f5c4b000dc088a45a9bf257d4e7ef841b4ca51/src/locale/zh_CN.js#L3

**Comment by sreenath124** [comment]
Its not working. I am using antd Table component with pagination object. I have set 
`<Table
                columns={tipsTableHeader}
                dataSource={this.props.tipData}
                pagination={{
                    defaultPageSize: this.state.limit,
                    total: this.props.total,
                    pageSizeOptions: ["20", "25", "30"],
                    showSizeChanger: true,
                    locale: {items_per_page: ""}
                }}
                onChange={this.handlePageChange}
                locale={{items_per_page: ''}}
            />`
Its not working as expected. What am I doing wrong?

**Comment by sreenath124** [comment]
@afc163 Thanks It worked. I just had to update the version of antd. Thanks again.

**Comment by rashmimh** [comment]
@sreenath124  which version is required to make it work. I am using 3.0.2.

**Comment by Nextt1** [comment]
```
pagination={{
          pageSizeOptions: ['50', '100'],
          showSizeChanger: true,
          pageSize: 50,
}}
```

Above code worked for me.
