### ISSUE TITLE
slider onAfterChange triggered two times with blur() method in it

### ISSUE THREAD

**Issue by Ryanhui** [ant-design/ant-design#13628]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k5mlnxyy1o)

### Steps to reproduce
drag the slider

### What is expected?
onAfterChange only trigger one time

### What is actually happening?
onAfterChange trigger two times

---
I am not sure whether it's a bug, if not how can I just trigger onAfterChange one time with blur() method in it?

**Comment by Ryanhui** [comment]
any help?

**Comment by scottclayton** [comment]
I believe this is still an issue in Ant Design v3.11.6, and that this issue didn't exist back in v3.5.4.

**Comment by benheb** [comment]
I am seeing this too, any status?

**Comment by ztplz** [comment]
I strongly don't recommend triggering `blur` on `onAfterChange`. Because `onAfterChange` will be triggered when the `touchend` event fires, but it will also fire when the blur event is triggered.

**Comment by ztplz** [comment]
@benheb   You can do something like @Ryanhui  to avoid these behaviors.

**Comment by ztplz** [comment]
Related to https://github.com/ant-design/ant-design/issues/13439.

**Comment by benheb** [comment]
Thanks @Ryanhui I'll give that try. I was doing something similar with mixed results, including calling `blur()` and it not actually blurring! I'll try this though, appreciate it.

**Comment by benheb** [comment]
@ztplz ok, but I personally wouldn't close this? It's definitely a bug, and didn't exist in previous versions?

**Comment by ztplz** [comment]
It is related to this imperfect [bugfix](https://github.com/ant-design/ant-design/commit/15770c527d6d8c8627f192f79dbdf5cd3450d393) 25 days ago. But I agree that some of the logic in `rc-slider` needs to be fixed.

**Comment by halftonepixel** [comment]
If you don't have any logic relating to blur, you can try doing this: https://codesandbox.io/s/mqm46vr9y

**Comment by Ryanhui** [comment]
@halftonepixel actually, if you have some function in 'onAfterChange'  when you click a blank place after you dragged the slider, the function triggers again.  I think in most cases that what we don't want to see.
