### ISSUE TITLE
Select/De-select checkbox and radio buttons associated with the row on row click

### ISSUE THREAD

**Issue by amittkSharma** [ant-design/ant-design#13623]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Windows 10, Chrome, React 16.x.x, Antd 3.11.2

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
1. Create a table with checkbox and radio buttons to select the row.
2. When clicking the row the checkbox or radio buttons are not getting selected.

### What is expected?
The Row click must select/de-select the checkbox and radio buttons associated with the row.

### What is actually happening?
Row click is not able to select/de-select the checkbox and radio buttons associated with the row.

---
While using the AntD table component (https://2x.ant.design/components/table/#), I am facing an issue that onRowclick event I am not able to check the checkbox or radio button placed in that row in order to make the selection.

I tried rowSelection and OnRow fields associated with the table but unable to accomplish the desired behavior.

Can someone please provide some pointers?

Thanks 
Amit

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-row-selection

<img width="866" alt="default" src="https://user-images.githubusercontent.com/507615/49947113-65b77a80-ff2b-11e8-95b1-29be79fa5d76.png">

**Comment by amittkSharma** [comment]
:+1:

**Comment by Akhilraghav05** [comment]
For better understanding please
check the condition `const hasSelected = selectedRowKeys.length > 0;` based on it you can track unselectedcheckboxes
