### ISSUE TITLE
autocomplete的dataSource为空的话，Form的onSubmit不能生效？

### ISSUE THREAD

**Issue by l769829723** [ant-design/ant-design#13634]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
macOS Mojave Version 10.14, Chrome Version 70.0.3538.102 (Official Build) (64-bit), React 16.6.3

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l4r856m49m)

### Steps to reproduce
autocomplete框中输入：ldsjalgjla

### What is expected?
按下回车键，调用onSubmit

### What is actually happening?
按下回车键，没有调用onSubmit

**Comment by afc163** [comment]
<img width="892" alt="default" src="https://user-images.githubusercontent.com/507615/53692396-25e58e00-3dca-11e9-8d42-815704b36d39.png">

It works now.
