### ISSUE TITLE
ant-design for vue 服务器挂掉了，而且treeSelect组件的异步加载功能有bug

### ISSUE THREAD

**Issue by lilifan1598** [ant-design/ant-design#13643]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
chrome 69

### Reproduction link
[https://tangjinzhou.gitee.io/](https://tangjinzhou.gitee.io/)

### Steps to reproduce
参照文档没法实现且报错

### What is expected?
异步加载功能用

### What is actually happening?
异步加载功能没法用

**Comment by afc163** [comment]
提错地方了。

**Comment by weizai118** [comment]
异步加载有示例没有
