### ISSUE TITLE
Fixed Sider example - can't scroll to see all menu options

### ISSUE THREAD

**Issue by devautor** [ant-design/ant-design#13640]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Browsers: Chrome, Firefox Quantum, Codesandbox; Next.js 7.0.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/307rxxr9v6)

### Steps to reproduce
I am using `Next.js` and `antd` Layout components to get a dashboard style page, where a fixed sidebar would extend to full page.

**EDIT: Using `top: 0` in `Sider` style doesn't work with my fixed Header and fixed Sider design. Codesandbox updated to show this.**

From the docs, I tried a fork of "fixed sider" [code](https://codesandbox.io/s/wqlxkmw06w), and populated the `Sider` component with more `Submenu` options. My code reproducing the bug is [here on codesandbox](https://codesandbox.io/s/307rxxr9v6), and a screenshot to point at the exact behavior is [shared here](https://drive.google.com/file/d/1fEGxgbjB_T9RUCtyB82yj5ofjyrDhlLG/view).
We can see in the screenshot that `option20` in `subnav5` is not reachable by scrolling.

### What is expected?
User should be able to scroll through all the menu items in a `Sider`.

### What is actually happening?
Scrolling is janky, and doesn't show last few items in the `Menu`.

---
Reading a few posts on SO, I suspect that this has something to do with fixed `Header`, but my experience with CSS is too limited to take my guess for any value. Thanks!

**Comment by zy410419243** [comment]
I add `top: 0` and it works well.

**Comment by devautor** [comment]
@zy410419243 It indeed works in sandbox (should also work in my environment). Thank you so much, and sorry to myself.

On a related note, I am trying to achieve styling effect mentioned in this [issue](https://github.com/ant-design/ant-design/issues/13572) and have realised that simple css flex rule, i.e. `margin-right: auto` on `Logo` component in `Header` doesn't help.

I realise that I am totally missing the point of how antd styling works, and what are the constraints, if any? Please elaborate a bit, and I will save some stupid queries and time :)

**Comment by afc163** [comment]
<img width="876" alt="default" src="https://user-images.githubusercontent.com/507615/53692403-38f85e00-3dca-11e9-8ce0-a50d09c80e50.png">

**Comment by zombieJ** [comment]
Close since reproduce missing.
