### ISSUE TITLE
Is it possible to make Select open upwards manually?

### ISSUE THREAD

**Issue by Tsury** [ant-design/ant-design#13647]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have complex UI in which it is required to open Select upwards.

### What does the proposed API look like?
Add direction="up" in props.

**Comment by ilanus** [comment]
Hi @Tsury, there is no `direction` prop however, you can use `getPopupContainer` to specify the popup container and in that way manipulate the select to be opened from the top, example: https://codesandbox.io/s/4j168r7jw0

**Comment by Tsury** [comment]
I have a complex application (not a transitional website) which uses the CSS `zoom` property. When using custom `zoom` values, `Select` components which are close to the bottom of the page open downwards, and are therefore cropped. I suspect it's some bug with `getBoundingclientRect` and CSS `zoom` in `Chromium`.
