### ISSUE TITLE
`Select` support custom suffixIcon even in 'multiple mode'

### ISSUE THREAD

**Issue by TiaossuP** [ant-design/ant-design#13653]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use custom `suffixIcon` to display a Loading animation, but `suffixIcon` will be useless when Select is in 'multiple mode'

### What does the proposed API look like?
I want a prop to force display my `suffixIcon` even in 'multiple mode'

**Comment by janjacuye** [comment]
UP

**Comment by TiaossuP** [comment]
@yutingzhao1991 Hello, if u have any plan for this issue?

**Comment by zombieJ** [comment]
Close since current Select support `showArrow` with multiple mode: https://codesandbox.io/s/reverent-sound-od951

**Comment by InFuz** [comment]
> Close since current Select support `showArrow` with multiple mode: https://codesandbox.io/s/reverent-sound-od951

Then the `showArrow` should be like a boolean|**ReactNode**

**Comment by haunb97** [comment]
> Close since current Select support `showArrow` with multiple mode: https://codesandbox.io/s/reverent-sound-od951

use suffixIcon to show icon, not showArrow

**Comment by ngohoang1254** [comment]
In tag mode, suffixIcon not working and how I can customize that showArrow.

**Comment by stefango** [comment]
In multiple mode, suffixIcon works if you add showArrow.

**Comment by tndong799** [comment]
@stefango I want disable animation of suffix icon when dropdown open. can you help I?

**Comment by RrNn** [comment]
> In multiple mode, suffixIcon works if you add showArrow.
Thanks, works but seems hacky 😁

**Comment by RrNn** [comment]
> In multiple mode, suffixIcon works if you add showArrow.

Thanks, works but seems hacky 😁
