### ISSUE TITLE
表格树形数据展现时当children为空数组时的显示问题

### ISSUE THREAD

**Issue by hodgevk** [ant-design/ant-design#1365]
表格树形数据展现时当children为空数组时，在表格里是会显示展开按钮的，除非把datasource中的children字段删除。这个是否可以改进下，没有子节点时或子节点个数为0时不显示展开按钮呢？

**Comment by jaredleechn** [comment]
这个是 by design 的，为那些异步加载 children 的节点先提供默认的占位缩进

如果本身的意图是不会有 children，可以将这个字段设置为 false

**Comment by afc163** [comment]
可以有占位，但确实不需要`展开按钮`。

**Comment by afc163** [comment]
有一个场景，如果展开行为是异步加载的，即使 `children` 为 `[]` 也需要出现 `[+]` 按钮，否则就无法操作了。保持原来的逻辑才能满足这个需求：

1. children 为 `[]` 时有 `[+]`
2. children 不存在或是 `null`、`false` 时，不展示 `[+]`。

@hodgevk

**Comment by pizn** [comment]
👍

**Comment by jaredleechn** [comment]
👍

**Comment by sAnwarm** [comment]
遍历树形数据，删除其空children项就行了：https://blog.csdn.net/weixin_38990605/article/details/109046555
