### ISSUE TITLE
关于Form中getFieldDecorator的rules-type验证问题（Rules type Verification of getFieldDecorator in Form）

### ISSUE THREAD

**Issue by sunguoxing0628** [ant-design/ant-design#13661]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
macOS; Google Chrome,Safari

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/21k61z7zm0)

### Steps to reproduce
1、初始化浮点型数据`118.5699519`（任意数，这里作为例子）

1、Initialize a float data `118.5699519`(arbitrary number, here as an example)
```
    getFieldDecorator("LGTD", {
        rules: [{ type: 'float', message: "请输入经度！" }],
        initialValue: 118.5699519
    }
```
2、修改数据中任意数字（增加数字，删除数字，替换数字）

2、Modify the data (Increase,Delete or Replace)

### What is expected?
可验证数据类型`muber`，`float`
Verifiable data types `muber', `float'

### What is actually happening?
无法识别数据类型，并提示验证失败！

Unable to identify data type and prompt validation failure!

![image](https://user-images.githubusercontent.com/27573161/50074863-2f724780-0218-11e9-9836-55fb110e7dce.png)

**Comment by zombieJ** [comment]
Try <InputNumber />: https://codesandbox.io/s/w0wpzv89lw

**Comment by sunguoxing0628** [comment]
如果用`<Input />`目前是否有解决方案，使用`<InputNumber />`的这种解决方案验证是没有问题，但是带来了更加麻烦的问题：**`样式被无效或覆盖`**，同时`<InputNumber />`的调节按钮 **`无法隐藏`**

**Comment by afc163** [comment]
建议自定义 validate rule
