### ISSUE TITLE
Table rowSelection 属性 onChange 方法参数改进建议

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design#1366]
这个方法的参数改为(nextSelectedRows,preSelectedRows) 会更实用吧。目前 Function(selectedRowKeys, selectedRows) 这样的参数值好像和 onSelect，onSelectAll 有点雷同。

**Comment by afc163** [comment]
nextSelectedRows 和 selectedRowKeys 是一样的。

preSelectedRows 可以自行保存在父组件的 this.state.selectedRowKeys 里。

**Comment by wangdao** [comment]
好的谢谢
