### ISSUE TITLE
WeekPicker can't custom input value，I need range time Instead of which week

### ISSUE THREAD

**Issue by KaivOU** [ant-design/ant-design#13667]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
custom input value of WeekPicker

### What does the proposed API look like?
return range time like 07/18~07/25，instead of 2018-25周

**Comment by afc163** [comment]
Try RangePicker
