### ISSUE TITLE
Affix Menu flickering when scrolling

### ISSUE THREAD

**Issue by riwu** [ant-design/ant-design#13662]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
macOS High Sierra 10.13.5, Chrome Version 70.0.3538.77

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v3vm3n19nl)

### Steps to reproduce
Open https://v3vm3n19nl.codesandbox.io and scroll with mouse. 

### What is expected?
Menu bar should remain visible at all times while scrolling.

### What is actually happening?
The menu flickers when scrolling for the first time after the page loads:

![](https://i.imgur.com/7xopojX.gif)

**Comment by ztplz** [comment]
![untitled7](https://user-images.githubusercontent.com/17755202/50486226-ed28e180-0a33-11e9-94d7-7702d6d4f8db.gif)
Sorry, I can't reproduce this problem.

**Comment by ztplz** [comment]
Mac Os
![image](https://user-images.githubusercontent.com/17755202/50486255-1a758f80-0a34-11e9-86d0-a7cc1200ea47.png)

**Comment by riwu** [comment]
You need to open the page on a separate tab. Use this link: https://v3vm3n19nl.codesandbox.io

**Comment by ztplz** [comment]
@riwu I see, thanks for your reminder.
