### ISSUE TITLE
Mention 组件突然失效(输入文字后不会自动过滤)

### ISSUE THREAD

**Issue by daya0576** [ant-design/ant-design#13678]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Using @alipay/bigfish@2.7.2 and umi@2.2.8...

### Reproduction link

: 「已屏蔽」

### Steps to reproduce
1. 打开页面
2. 点击mention组件
3. 输入 @   输入一些文字

### What is expected?
Mention 的下拉列表随文字输入变化 

### What is actually happening?
无反应

---
### antd 版本 不太确认: 
```
takachiho3.7) ➜  minimal_reproduction git:(sprint_minimal_reproduction_S901947573_20181218) ✗ tnpx bigfish -v --verbose
🐟 Using @alipay/bigfish@2.7.2 and umi@2.2.8...
bigfish:
@alipay/bigfish@@alipay/bigfish@2.7.2
@alipay/umi-plugin-bigfish@2.7.2
umi@umiVersion

umi:
umi@2.2.8
darwin x64
node@v8.14.0
umi-build-dev@1.2.7
af-webpack@1.2.7
babel-preset-umi@1.2.1
umi-test@1.2.2
react@16.6.3 (/Users/henry/repo/minimal_reproduction/node_modules/_react@16.6.3@react)
react-dom@16.6.3 (/Users/henry/repo/minimal_reproduction/node_modules/_react-dom@16.6.3@react-dom)
react-router@4.3.1 (/Users/henry/repo/minimal_reproduction/node_modules/_react-router@4.3.1@react-router)
react-router-dom@4.3.1 (/Users/henry/repo/minimal_reproduction/node_modules/_react-router-dom@4.3.1@react-router-dom)
umi-plugin-react@1.2.3
@alipay/umi-plugin-antdcloud-nav@2.0.3
dva@2.5.0-beta.2 (/Users/henry/repo/minimal_reproduction/node_modules/_dva@2.5.0-beta.2@dva)
dva-loading@2.1.0-beta.2
dva-immer@0.2.4
path-to-regexp@1.7.0
```

**Comment by yutingzhao1991** [comment]
可以用 https://codesandbox.io/s/wk04r016q8 这个复现吗？

**Comment by afc163** [comment]
不要暴露公司内网地址，这样对公司和对你的工作都是很危险的。

**Comment by afc163** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/507615/50139180-dd92f580-02db-11e9-9ce7-51bd0a0cd81e.png">

**Comment by daya0576** [comment]
https://codesandbox.io/s/q7k5k2p60j 
就是最简单的 Mention, 之前输入文字的时候, 会自动过滤列表, 现在需要去自定义 `onSearchChange`, 手动过滤.

**Comment by afc163** [comment]
2.x 确实是可以的：https://codesandbox.io/s/vmwxrw2lq5 好奇怪

@zombieJ 有空看看来龙去脉。

**Comment by daya0576** [comment]
> 目前的逻辑看着没啥问题，suggestions 应该是可控的，但是 2.x 确实是可以的：https://codesandbox.io/s/vmwxrw2lq5 好奇怪
> 
> @zombieJ 有空看看来龙去脉。

**Comment by daya0576** [comment]
> > 目前的逻辑看着没啥问题，suggestions 应该是可控的，但是 2.x 确实是可以的：https://codesandbox.io/s/vmwxrw2lq5 好奇怪
> > @zombieJ 有空看看来龙去脉。

是的, 很奇怪, 上周开发的时候还是可以自动筛选的. 
这周就不一样了.

**Comment by zombieJ** [comment]
@daya0576 ,
查了一下，`suggestions` 从半受控变成[完全受控](https://github.com/ant-design/ant-design/commit/eca24018fab9437f23d97defdc8e8340d3cd5b5f)的了。
我发 PR 加个 `defaultSuggestions` 属性，之后用这个。
