### ISSUE TITLE
Ant design can not run smoothly on miniblink, especially CSS animation

### ISSUE THREAD

**Issue by whaodu** [ant-design/ant-design#13675]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
miniblink

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
Accessing 'https://ant.design/index-cn' with Miniblink Kerne.I found CSS animation running slowly.

### What is expected?
Process running CSS animation

### What is actually happening?
CSS animation running slowly.

**Comment by afc163** [comment]
We don't provide support at other browsers listed in https://github.com/ant-design/ant-design#-environment-support
