### ISSUE TITLE
如何通过点击编辑获取当前行的数据

### ISSUE THREAD

**Issue by jameslazy** [ant-design/ant-design#1367]
const columns = [
            {title:'ID',dataIndex:'roleId',key:'roleId',width:2},
            {title:'角色名称',dataIndex:'rName',key:'rName',width:2},
            {title:"创建时间",dataIndex:'rAddTime',key:'rAddTime',width:2},
            {title: '操作', key: 'operation',width:2,render:(text, record) {
                render(text, record) {
                    return (
                        <span>
                            <a href="#">编辑{record.name}</a>
                            <span className="ant-divider"></span>
                            <a href="#">删除</a>
                        </span>
                    );
                }
            }
        ]

**Comment by afc163** [comment]
`onClick={this.handleClick(record)}`

**Comment by jameslazy** [comment]
@afc163 这个是在render{render{}}中的，这样的话不就是拿到最里层中的点击事件么，那岂不是获取之后还要在bind（this，record）才能可以么

**Comment by afc163** [comment]
嗯，你处理好 this 就好，推荐用 arrow function,  `render: () => { ... }`。

**Comment by afc163** [comment]
另外，注意 markdown 格式：https://guides.github.com/features/mastering-markdown/

**Comment by jameslazy** [comment]
@afc163 OK
