### ISSUE TITLE
Add Checkbox.Group example with Form

### ISSUE THREAD

**Issue by ipassynk** [ant-design/ant-design#13672]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
all

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k99r9jp1xr)

### Steps to reproduce
There is no example in the demo folder. I created a small one for my purpose.

### What is expected?
Checkbox.Group example with Form

### What is actually happening?
A lot of google ;-)

**Comment by zy410419243** [comment]
Welcome to PR.

**Comment by ipassynk** [comment]
Created - https://github.com/ant-design/ant-design/pull/13680

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/13680
