### ISSUE TITLE
Table加了纵向滚动条后，表头和表格内容对不上

### ISSUE THREAD

**Issue by chenmrU** [ant-design/ant-design#13688]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
win7、Chrome、

### Reproduction link
[https://github.com/ant-design/ant-design/issues/2422](https://github.com/ant-design/ant-design/issues/2422)

### Steps to reproduce
1

### What is expected?
1

### What is actually happening?
1

---
1

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-columns

<img width="712" alt="image" src="https://user-images.githubusercontent.com/507615/50148413-69fce280-02f3-11e9-91b7-7b51fab46014.png">
