### ISSUE TITLE
动态更改From.Item校验规则失效

### ISSUE THREAD

**Issue by ying-bin** [ant-design/ant-design#13689]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
浏览器版本

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xrmj2rlrjz)

### Steps to reproduce
1、Demo1选择male，Demo2校验为必输，Demo3不必输
2、Demo2切换选择female时，逻辑应该是Demo3校验为必输，Demo2不必输，但目前是错误的提示。

### What is expected?
动态更新校验规则时，校验生效

### What is actually happening?
动态更新校验规则时，校验未生效

**Comment by dengfuping** [comment]
- 对 `required` 做动态切换校验不生效，应该是有问题的。可以暂时先对 `rules` 做动态切换校验，参考 https://codesandbox.io/s/yp40jomm0j.

**Comment by ying-bin** [comment]
非常感谢回复。
    那是否目前有计划去修复此问题，感觉这类问题使用的场景比较多！


Thanks & Best Regards!
------------------------------------------------------
蒋迎宾 Nemo
E-mail: yingbin.jiang@outlook.com<mailto:yingbin.jiang@outlook.com>
Mobile: (+86)18516519209
------------------------------------------------------

在2019年01月9日 11:49，诸岳<notifications@github.com><mailto:notifications@github.com> 写道：

  *   对 required 做动态切换校验不生效，应该是有问题的。可以暂时先对 rules 做动态切换校验，参考 https://codesandbox.io/s/yp40jomm0j.

**Comment by zombieJ** [comment]
> * 对 `required` 做动态切换校验不生效，应该是有问题的。可以暂时先对 `rules` 做动态切换校验，参考 https://codesandbox.io/s/yp40jomm0j.

看起来一样有 bug，rule 验证过后就被 cache 掉了。这个逻辑看起来要调整一下。

**Comment by hacke2** [comment]
https://codesandbox.io/s/855w8vxyj

我这边发现一个问题，在验证过后沿用了上一个校验的结果。步骤是：

1. 点击 update
2. 开启校验
3. 点击 update，此时不会做校验了

**Comment by zombieJ** [comment]
> https://codesandbox.io/s/855w8vxyj
> 
> 我这边发现一个问题，在验证过后沿用了上一个校验的结果。步骤是：
> 
> 1. 点击 update
> 2. 开启校验
> 3. 点击 update，此时不会做校验了

Validate 后 Form 会缓存结果，如果你直接动态改 rule 的话，加一个 force 来强制无视缓存就好了：https://codesandbox.io/s/oj9r74k329

**Comment by hellowuxin** [comment]
@zombieJ 现在 antd 4 还支持 force 参数吗，好像没有？我动态更改 rules 后，校验结果没有变化
