### ISSUE TITLE
Able to customize icon(arrow) of Collapse component

### ISSUE THREAD

**Issue by popmanhe** [ant-design/ant-design#13683]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now, the only icon of Collapse using is arrow.    

### What does the proposed API look like?
Would be great to be able to customize it. For instance, use plus/minus instead of arrow.  This should be a simple feature. Would like to see it in the next update. 
Thanks in advance.

**Comment by afc163** [comment]
trace #12212
