### ISSUE TITLE
Slider 使用tooltipVisible 不能显示tooltip

### ISSUE THREAD

**Issue by dicallc** [ant-design/ant-design#13682]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
谷歌浏览器

### Reproduction link
[https://github.com/ant-design](https://github.com/ant-design)

### Steps to reproduce
  <Slider defaultValue={30} tooltipVisible onChange={this.handleSliderChange} min={2} max={96} value={this.state.defalut_num} />

### What is expected?
应该会始终显示tooltip

### What is actually happening?
没有显示显示tooltip

**Comment by dicallc** [comment]
使用代码：
```
  <Slider defaultValue={30} tooltipVisible onChange={this.handleSliderChange} min={2} max={96} value={this.state.defalut_num} />
```

**Comment by afc163** [comment]
https://ant.design/changelog-cn#3.11.0

**Comment by Ryuurock** [comment]
> 使用代码：
> 
> ```
>   <Slider defaultValue={30} tooltipVisible onChange={this.handleSliderChange} min={2} max={96} value={this.state.defalut_num} />
> ```
遇到了同样的问题

**Comment by Ryuurock** [comment]
@afc163

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by Ryuurock** [comment]
sorry . 没有更新版本
