### ISSUE TITLE
把form组件当做Modal组件的内容，想通过点击Modal的按钮来获取form中的数据该如何实现

### ISSUE THREAD

**Issue by jameslazy** [ant-design/ant-design#1368]

**Comment by afc163** [comment]
http://ant.design/components/form/#demo-validate-customized

**Comment by afc163** [comment]
@benjycui 这个最好把和 Modal 配合使用的例子单独拆出来。

**Comment by jameslazy** [comment]
@afc163 现在是form中没有事件来获取表单值，点击Modal中的确定我要获取表单值。

**Comment by benjycui** [comment]
@jameslazy https://github.com/ant-design/ant-design/commit/10edd74f33ca0ea24ab993d9dee3108265f81f17
