### ISSUE TITLE
input 组件支持 allowClear 清除按钮

### ISSUE THREAD

**Issue by tdida** [ant-design/ant-design#13691]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
input 组件新增 allowClear 按钮，用于清除 input 内容

### What does the proposed API look like?
allowClear 同 select 组件

**Comment by ybning** [comment]
@tdida 
其实你可以简单封装下，给Input加个suffix，用value判断下就可以了
```
<Input 
    suffix={
        this.state.value?
        <Icon type="close-circle" onClick={this.emitEmpty.bind(this)} />
        :null
    }
/>
```

**Comment by peakandyuri** [comment]
要更精细化就给Input组件加上mouseenter和mouseleave事件来触发显示suffix或隐藏

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/13939
