### ISSUE TITLE
Badge offset属性不生效，总是出现在右上角

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#13694]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Windows10,Chrome 71.0.3578.98

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kxj82w22mv)

### Steps to reproduce
无论怎样设置`offset`属性徽标总会移动到右上角，并且刷新会有闪烁

### What is expected?
可以通过设置`offset`将徽标放置到右下角

### What is actually happening?
`offset`不生效

**Comment by afc163** [comment]
@Liu-Ya 重新提个 issue
