### ISSUE TITLE
在最新的版本里Table组件的filters过滤功能“确定”“重置”按钮点击没有效果，反而在失去焦点之后执行过滤 

### ISSUE THREAD

**Issue by gitlwz** [ant-design/ant-design#13693]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Chrome  70.0.3538.110（正式版本） （32 位）

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ymv2lmmwqx)

### Steps to reproduce
选择过滤->选择其中几项->确定 和 重置按钮 无效，当失去焦点反而过滤生效

### What is expected?
希望能够，同以前一样。点击 确定 和重置的时候能够过滤表格

### What is actually happening?
点击没有效果，样式不见了，并且在失去焦点之后反而过滤了表格

**Comment by gitlwz** [comment]
> ![图片](https://user-images.githubusercontent.com/26959652/50147027-189f2400-02f0-11e9-8e60-d9d303a5965d.png)
> 靓仔试试这个

感谢你的方案，刚刚我测试了下，加上这个样式确实解决了这个问题

**Comment by afc163** [comment]
Duplicate of #13563

**Comment by ioandy** [comment]
我也遇到这样的问题，请教是怎么解决的
