### ISSUE TITLE
Mention not working correctly on mobile (Android)

### ISSUE THREAD

**Issue by matteosaporiti** [ant-design/ant-design#13692]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Android 8, tested with Chrome and Brave browsers

### Reproduction link
[https://ant.design/components/mention/](https://ant.design/components/mention/)

### Steps to reproduce
Write @ to trigger the mention in one of the mention textbox of the antd mention component page

### What is expected?
A list of options is displayed

### What is actually happening?
The @ is removed and nothing happens

---
If I press @ multiple times I can manage to make it work but with a single press the character gets remove instantly.
No problem with desktop browsers or with desktop browsers emulating mobile. iOS's Safari also seem to work and I had to report of this bugs from iOS users (3 android users complained about mentions not working).

**Comment by afc163** [comment]
antd don't provide support for mobile browser now.

**Comment by ztplz** [comment]
`Antd` was originally designed for desktop. The mobile environment is different from the desktop and is often not compatible. On mobile devices you can choose `Antd Mobile`.
