### ISSUE TITLE
radio button component cursor is not completely pointer in firefox

### ISSUE THREAD

**Issue by em2046** [ant-design/ant-design#13699]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Windows10 1809 OS17763.194 - Firefox 64.0

### Reproduction link
[https://ant-design.gitee.io/components/radio-cn/#components-radio-demo-radiobutton](https://ant-design.gitee.io/components/radio-cn/#components-radio-demo-radiobutton)

### Steps to reproduce
![Image of Yaktocat](https://i.v2ex.co/456HuO0a.png)
move mouse on the .ant-radio-button-input
This problem only in Windows with Firefox.
macOS cannot repetition

### What is expected?
mouse pointer should be { cursor: point; }

### What is actually happening?
.ant-radio-button-input element control cursor in Firefox, style is { cursor: default; }

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50160517-86f5dd80-0314-11e9-8098-b1dab0b470d0.png)
Are you sure?

**Comment by em2046** [comment]
> 
> Are you sure?

Yes, but only in Windows.
![2018-12-19_124708](https://user-images.githubusercontent.com/10690832/50199521-52256d00-038c-11e9-9863-10ae5ba2c33b.png)

**Comment by ztplz** [comment]
Sorry, I didn't test it in Win. @zombieJ
