### ISSUE TITLE
Can't remove array field in form

### ISSUE THREAD

**Issue by miyunim** [ant-design/ant-design#13698]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
reactjs

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lp9zz6myo7)

### Steps to reproduce
1. Click Add Button
2. Click Remove Button

### What is expected?
Removed the selected field.

### What is actually happening?
When field is added use getFieldDecorator and setFieldsValue
but I don't know how to remove fields (elements)
`Remove button' is clicked, the selected field is live in render function (getFieldsValue()['names'] I checked it)

**Comment by afc163** [comment]
https://codesandbox.io/s/5jookknrp

Don't try use `setFieldValue` to replace `setState`, it is not same and should be used in each other situation.
