### ISSUE TITLE
Calendars日前是否可以设置背景色或背景图片

### ISSUE THREAD

**Issue by mushroomlb** [ant-design/ant-design#13704]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在展示日历时可以通过不同的颜色区分日期

### What does the proposed API look like?
{ backgroundImage: `url('${getImg('hava_data')}')

**Comment by afc163** [comment]
Try `dateCellRender` antd `dateFullCellRender`
