### ISSUE TITLE
[Tabs]When Tabs.TabPane is disabled, mouse did not change.

### ISSUE THREAD

**Issue by zy410419243** [ant-design/ant-design#13709]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Window 10, Chrome 71.0.3578.98

### Reproduction link
[https://ant.design/components/tabs-cn/#components-tabs-demo-disabled](https://ant.design/components/tabs-cn/#components-tabs-demo-disabled)

### Steps to reproduce
![avatar](https://i.loli.net/2018/12/19/5c19e065404e0.gif)

### What is expected?
Cursor change to `not-allowed`, not `default`.

### What is actually happening?
Mouse did not change.

---
Is this designed?

**Comment by zy410419243** [comment]
https://github.com/react-component/tabs/blob/master/assets/index/common.less#L125

When I change this to `not-allowed`, `disabled` works.

Is this designed?

**Comment by Yangzhedi** [comment]
@zy410419243 [here](https://github.com/ant-design/ant-design/blob/master/components/tabs/style/index.less#L113) antd 会将rc的样式覆盖掉

**Comment by zy410419243** [comment]
是我系统问题么，更新以后还是没效果..我这边看到的是 `not-allowed` 之上还有一层 `pointer-events: none`

**Comment by afc163** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/507615/50347765-c705cc00-0571-11e9-98d4-ee03e570135a.png">
