### ISSUE TITLE
upload组件, 上传 xls，xlsx，docx的时候，file.type返回为“”

### ISSUE THREAD

**Issue by liyang0612** [ant-design/ant-design#13718]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---
chrome 71.0.3578.98

上传 xls，xlsx，docx的时候，beforeUpload的 file.type返回为“”

![image](https://user-images.githubusercontent.com/19622871/50216979-4ce31500-03c2-11e9-9297-ccd92c0034f8.png)

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by GTliangming** [comment]
xlsx我是正常的 但是xls也会返回type为”“
