### ISSUE TITLE
Datepicker在设置了不合适的时间时，确定按钮是蓝色可点击状态且点击完没有反应

### ISSUE THREAD

**Issue by luckyoneday** [ant-design/ant-design#13714]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
v3.11.2

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
不可选择日期和时间模块，直接点击选择时间，时分秒面板展开时日期默认为当前，不论选择了什么时分秒，确定按钮都为可点击状态，但是点击完没有反应。

### What is expected?
将确定按钮置为不可点击状态（灰色）

### What is actually happening?
确定按钮都为可点击状态（蓝色），但是点击完没有反应。

**Comment by afc163** [comment]
小技巧，点击 demo 标题可以获得直达链接：https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date

**Comment by afc163** [comment]
如何重现，我试了一下没试出来，最好提供 GIF。
