### ISSUE TITLE
Form setFieldsValue  不支持嵌套对象

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design#1371]
input placeholder="所属部门"   {...getFieldProps('department.name')}/>

form.setFieldsValue({"name" : "ddddd, "department" : {"name ": "部门1"}})

好像现在的form不支持这样来设置值。

**Comment by benjycui** [comment]
原生表单也不支持吧。

**Comment by wangdao** [comment]
好像是，setFieldsValue  这个方法改改就可以了吧

**Comment by wangdao** [comment]
写了个转换工具，搞定。

**Comment by williamkhshea** [comment]
@wangdao 请问您是怎样解决的呢？可以分享一下吗？

@benjycui 请问在将来的版本有打算支援吗？

**Comment by benjycui** [comment]
> 请问在将来的版本有打算支援吗？

这个不好做，因为有些表单域的值可能就是一个对象。

**Comment by wangdao** [comment]
@williamkhshea  自己写了个工具转了下，没想到好的办法。https://github.com/wangdao/object-trans-util
