### ISSUE TITLE
增加 input 或 select 组件的校验状态

### ISSUE THREAD

**Issue by pdsuwwz** [ant-design/ant-design#13712]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
针对用户输入的值是否合法或者选择了某一项等来为控件增加校验状态，以提醒用户完成其余的操作。
校验状态包括 error、warning 和 success 等，每种状态应有不同的边框颜色和提示信息。

### What does the proposed API look like?
属性：validation='warning | error | success '

**Comment by afc163** [comment]
https://ant.design/components/form/#components-form-demo-validate-static
