### ISSUE TITLE
New Component Image

### ISSUE THREAD

**Issue by ycjcl868** [ant-design/ant-design#13719]
```jsx
<Image src={src} />
// click image to zoom in / zoom out / rotate
<Image zoom  src={src} />
// image clip
<Image clip={{ obj }} src={src} />
// banner image load image 1x before image 2x ready
<Image image1x={1x} image2x={2x}  src={src} onLoad={() => {}} />
// loading (1-100)
<Image loading={50} src={src} />
```

zoom in out Inspired by [react-zmage](https://github.com/Caldis/react-zmage):

![image](https://user-images.githubusercontent.com/13595509/50217885-0fcc5200-03c5-11e9-847a-4e40d9ec0733.png)

in addition,  Image can controll gif , like zhihu:

![image](https://user-images.githubusercontent.com/13595509/50217825-da276900-03c4-11e9-8b29-6a3a20f39bc9.png)

https://github.com/KyleAMathews/react-retina-image

**Comment by afc163** [comment]
https://www.npmjs.com/package/react-image
https://jossmac.github.io/react-images/

**Comment by zy410419243** [comment]
What about PicturesWall like [this](https://ant.design/components/upload-cn/#components-upload-demo-picture-card).

I don't think it's a good idea that `Upload` does too much thing that is not its matter.

**Comment by ycjcl868** [comment]
@zy410419243 Pictures Wall in Upload should be replace by `Image` component.

**Comment by ilanus** [comment]
@ycjcl868 I agree, very good idea

**Comment by ztplz** [comment]
Sounds good. Any plan about API?

**Comment by ztplz** [comment]
@afc163  我加个hook form？

**Comment by afc163** [comment]
@ztplz Seems not related to this issue.

**Comment by zy410419243** [comment]
Is there any progress?

**Comment by ycjcl868** [comment]
WIP in react-component/image

**Comment by afc163** [comment]
https://photoswipe.com

**Comment by dmdoit** [comment]
这个组件真的挺需要的

**Comment by ycjcl868** [comment]
@dmdoit 有哪些需求？收集下加进去

**Comment by afc163** [comment]
image checkbox

![image](https://user-images.githubusercontent.com/507615/57352149-076b8c80-7197-11e9-8297-529e292127a0.png)

#16442

**Comment by zlab** [comment]
有没有类似 jquery fancybox colorbox

![image](https://user-images.githubusercontent.com/2288630/60818308-01624e00-a1d0-11e9-8aaf-28d155802e88.png)

**Comment by and80506** [comment]
很早就开始关注和使用antd，去年开始我们基于antd现有组件及规范，针对内部toB业务维护了一套自己的设计规范和组件库，有相应的图片查看组件，可评估下是否满足社区需求，看下反哺社区是否有可能。￼
https://nsfi.github.io/ppfish-components/#/components/picturePreview
![image](https://user-images.githubusercontent.com/1769410/62179734-1d48b200-b380-11e9-99a5-25588696f71e.png)

**Comment by dmdoit** [comment]
> 很早就开始关注和使用antd，去年开始我们基于antd现有组件及规范，针对内部toB业务维护了一套自己的设计规范和组件库，有相应的图片查看组件，可评估下是否满足社区需求，看下反哺社区是否有可能。￼
> https://nsfi.github.io/ppfish-components/#/components/picturePreview
> ![image](https://user-images.githubusercontent.com/1769410/62179734-1d48b200-b380-11e9-99a5-25588696f71e.png)

写的很好

**Comment by afc163** [comment]
- https://next.chakra-ui.com/docs/components/image
- https://react.semantic-ui.com/elements/image/

**Comment by crazyair** [comment]
缺少鼠标滚动变大缩小、推动图片会自动回到中心位置，无法固定。

**Comment by zlab** [comment]
怎么没有上一张，下一张的功能
