### ISSUE TITLE
menu horizontal with only top level items contains unnecessary submenu li elements

### ISSUE THREAD

**Issue by Enalmada** [ant-design/ant-design#13723]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v1v7q135n7)

### Steps to reproduce
add menu with mode horizontal and only one top level element.  Inspect the first menu element and note that there are submenu elements being rendered with display:none; that provide no apparent value.

### What is expected?
horizontal menu with only top level elements creates no submenu elements

### What is actually happening?
horizontal menu with only top level elements renders hidden submenu elements.  There elements appear to be contributing to a test error when running unit testing.

---
 When running jest unit testing against ant design horizontal menu I get a `TypeError: Cannot read property 'split' of undefined` bug that seems to be related to this and I am hoping that optimizing the menu behavior eliminates the test issue.  Please see this rc-menu issue for more context:
https://github.com/react-component/menu/issues/232

**Comment by ztplz** [comment]
Sorry for the delay reply. It is used to display the rest of the `menuitem`.
For example:
![image](https://user-images.githubusercontent.com/17755202/50451956-2d279000-0972-11e9-8c4f-20fdc6eb47ab.png)
![image](https://user-images.githubusercontent.com/17755202/50451960-3b75ac00-0972-11e9-8854-88dc3aab67ac.png)

**Comment by Enalmada** [comment]
That makes sense!  Thank you for taking the time to explain that.  I will continue to work with rc-menu on the issue I am experiencing.

**Comment by afc163** [comment]
We can still remove those extra li when there is only one menu item there.

**Comment by Enalmada** [comment]
Well if there is any optimizations you think make sense in that area then sure!
