### ISSUE TITLE
type 'editable' missing in ColumnProps<T> [typescript]

### ISSUE THREAD

**Issue by B1anker** [ant-design/ant-design#13725]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
fix typings

### What does the proposed API look like?
export interface ColumnProps<T> {
   ...,
   editable?: boolean
}

**Comment by B1anker** [comment]
It was unnecessary

**Comment by jaisonjjames** [comment]
> It was unnecessary

@B1anker  B1anker May I know its come unnecessary or how do you fix?
