### ISSUE TITLE
upload  beforeUpload demo 写法有疑义

### ISSUE THREAD

**Issue by zyMacro** [ant-design/ant-design#13730]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
anywhere

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
 beforeUpload: (file) => {
        this.setState(state => ({
          fileList: [...state.fileList, file],
        }));
        return false;
      },

### What is expected?
this.setState({
   fileList: [...this.state.fileList, file]
})

### What is actually happening?
setState里面第一个入参用一个函数？fileList有定义吗，

---
没看明白文档的demo为什么那样写

**Comment by afc163** [comment]
https://reactjs.org/docs/react-component.html#setstate
