### ISSUE TITLE
DatePicker: doubleClick support

### ISSUE THREAD

**Issue by arifemrecelik** [ant-design/ant-design#13739]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Datepicker modal close when you click once which means when you select the date. But I want to close it when you double click.

### What does the proposed API look like?
It could be add some events onClick and onDoubleClick.

**Comment by afc163** [comment]
It is a strange behavior to doubleClick calendar panel but you can add this callback to http://github.com/react-component/calendar and we will allow this passed to rc-calendar at least.
