### ISSUE TITLE
LocaleProvider doesn't perform well on RangePicker

### ISSUE THREAD

**Issue by pimkle** [ant-design/ant-design#13749]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
2.13.11

### Environment
default

### Reproduction link
[https://2x.ant.design/components/locale-provider-cn/](https://2x.ant.design/components/locale-provider-cn/)

### Steps to reproduce
# Steps
* 1、open https://2x.ant.design/components/locale-provider-cn/
* 2、goto page's demo area
* 3、switch from English to '中文'
* 4、open RangePicker component
* 5、look into the picker month area
* 6、month's text is still English!

# Detail
I've reproduced this issue on my own project, there are 2 RangePicker on the page, the first RangePicker's month's text is Chinese, the second RangePicker is not.

### What is expected?
month's text is Chinese

### What is actually happening?
month's text is English

---
[官方文档](https://2x.ant.design/components/locale-provider-cn/)  
上面的 demo 显示， RangePicker 展开的日期选择框，月份那里也还是英文的。  
实际开发项目，第一个 RangePicker 展开的月份那里是中文的，第二个的会变成英文。

**Comment by afc163** [comment]
Try 3.x, 2.x is not maintained any more.
