### ISSUE TITLE
Overriding LESS styles with ejected create-react-app not working

### ISSUE THREAD

**Issue by dev-drprasad** [ant-design/ant-design#13746]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
Ubuntu 16.04 LTS, Node-10.14.2, Create React App- v2.1.1

### Reproduction link
[https://github.com/dev-drprasad/antd-override](https://github.com/dev-drprasad/antd-override)

### Steps to reproduce
I added required configuration to override styles in `webpack.config.dev.js`

babel-plugin
```
[
  'import',
  { libraryName: 'antd', libraryDirectory: 'es', style: true },
],
```
less-loader
```
{
      loader: require.resolve('less-loader'), // compiles Less to CSS
      options: {
        modifyVars: {
          'primary-color': '#1DA57A',
          '@border-color-base': '0',
        },
        javascriptEnabled: true,
      },
    },
```
I added required dependecies `less less-loader babel-plugin-import`

Steps:
 * Clone the attached repo.
 * run `yarn start`
 * visit `localhost:3000` you will see button without any styles

### What is expected?
Button in homepage should have styles (green background without any border)

### What is actually happening?
I am not sure why its breaking

**Comment by dev-drprasad** [comment]
I realized i need to add `/\.less$/`in `test` regex. Thanks

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50286844-abc88d00-049b-11e9-88ce-6450f58e8208.png)
![image](https://user-images.githubusercontent.com/17755202/50286865-b6832200-049b-11e9-89d6-82f3ff6e4b04.png)
![image](https://user-images.githubusercontent.com/17755202/50286889-c438a780-049b-11e9-9142-771a8c750438.png)
Add `antd/dist/antd.css` at the top of `src/App.css`.
