### ISSUE TITLE
AutoComplete have unfriendly hints in console.

### ISSUE THREAD

**Issue by dkvirus** [ant-design/ant-design#13741]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
MacOS10.13，Chrome 70.0，

### Reproduction link
[https://github.com/dkvirus/autocomplete](https://github.com/dkvirus/autocomplete)

### Steps to reproduce
- clone 我的示例代码到本地；
- npm install 安装依赖包；
- yarn start 启动项目；
- 进入浏览器 F12 打开控制台。

### What is expected?
控制台没有错误信息打印。

### What is actually happening?
控制台打印错误信息，花费我三个小时去定位问题，一直以为是我代码问题，直到整了个干净的工程单独运行 AutoComplete 组件才发现是组件问题。

---
just user AutoComplete Component.

**Comment by dkvirus** [comment]
![image](https://user-images.githubusercontent.com/29170168/50273283-31851200-0475-11e9-99b4-cf31ab68e4f6.png)

**Comment by zombieJ** [comment]
感谢反馈！辛苦了！依赖 `rc-select` 已修复。重装一下试试哈~

**Comment by dkvirus** [comment]
你好，我执行了 `$ npm install antd@latest`，启动项目依然有这个报错。不知你说的重装是什么意思，还是说要等下周发布新版本？？

**Comment by zombieJ** [comment]
@dkvirus 删除 node_modules 再 install 一遍，这个是 antd 依赖的 `rc-select` bug。更新 antd 不会更新 rc-select
