### ISSUE TITLE
Can Table Head Load DND to Drag Head

### ISSUE THREAD

**Issue by chenzhili** [ant-design/ant-design#13740]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
want to drag your head through Column and ColumnGroup plus a layer of dnd, but debugging feels like there's no rendering middle layer.

### What does the proposed API look like?
Can you tell me how to get the head components and do the second drag development?

**Comment by codercodingthecode** [comment]
@chenzhili 
check this out

https://codepen.io/raisezhang/pen/MoMoyz

seems to be a common request/problem/desired feature to have out of the box.
