### ISSUE TITLE
I get some errors when I used antd-Calendar Component

### ISSUE THREAD

**Issue by Wanchaochao** [ant-design/ant-design#13753]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
cli:umi(v2.1.2)    browers:chrome      react-native:7.11.1

### Reproduction link
[https://github.com/Wanchaochao/react-blog/blob/master/src/pages/layouts/index.js](https://github.com/Wanchaochao/react-blog/blob/master/src/pages/layouts/index.js)

### and the error in the page
```
import { Calendar } from 'antd'

...
<Calendar
   fullscreen={false}
/>
```
#### After I got the errors I did this:
```
import moment from 'moment'
import 'moment/locale/zh-cn'

render(){
   const startTime = moment.momentToFormat
   ...
   value={startTime}
   defaultValue={startTime}
}
```

### What is expected?
I dont`t want to see any error at chrome console.
I read the doc and I try to complete the attibute value and defautlValue,

### What is actually happening?
but in the end, I got :
Warning: Failed value type: The value `isRequired` is marked as required in `Select`, but its value is `undefined`.
Warning: Failed defaultValue type: The defaultValue `isRequired` is marked as required in `Select`, but its value is `undefined`.'

---
I don`t how can I clear these errors, could you help me?

**Comment by afc163** [comment]
Retry remove your `node_modules` `yarn.lock` `package-lock.json` and reinstall `node_modules`.

**Comment by Wanchaochao** [comment]
Thank you very much ~~
👏👏
