### ISSUE TITLE
Input输入框 增加一个 删除内容的按钮

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#13755]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在Input   处于disabled状态下  无法清除Input的内容，需要使用者自己封装删除按钮，但是个人封装的风格可能与antd的不统一

### What does the proposed API look like?
allowClear

**Comment by afc163** [comment]
Duplicate of #13691
