### ISSUE TITLE
使用Select组件，控制台报错

### ISSUE THREAD

**Issue by zhuLni** [ant-design/ant-design#13767]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
create-react-app

### Reproduction link
[https://new-issue.ant.design](https://new-issue.ant.design)

### Steps to reproduce
# `3.11.2版本有这个问题，使用3.10.3版本没问题。重现步骤，直接使用官网例子，脚手架用create-react-app`
链接随便写的。

### What is expected?
使用正确，控制台不要有警告，有强迫症，看着很难受。

### What is actually happening?
直接用Select例子，控制台有错

**Comment by zy410419243** [comment]
试着重新 install 一下

https://github.com/ant-design/ant-design/issues/13741#issuecomment-449039319
