### ISSUE TITLE
Use RangePicker width Form.create can't set value when mode is ['month','month']

### ISSUE THREAD

**Issue by lidianhao123** [ant-design/ant-design#13769]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
chrome latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6407k4w6nk)

### Steps to reproduce
select start month and end month then input value not change

### What is expected?
set start month and end month correct

### What is actually happening?
value no set

**Comment by afc163** [comment]
RangePicker is not support for RangeMonthPicker now. This usage is not for RangeMonthPicker too.
