### ISSUE TITLE
Slide 点击滑条 onchange方法 回调两次 第一次回调正确值，后面会自动 1 回调给我

### ISSUE THREAD

**Issue by dicallc** [ant-design/ant-design#13763]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
谷歌浏览器 

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
```
  <Slider tooltipVisible onChange={this.handleSliderChange} min={0} max={100} value={this.state.defalut_num} />
```

### What is expected?
应该只会回调一次啊

### What is actually happening?
每次点击滑条 会自动 1 多一次回调

**Comment by dicallc** [comment]
而且切换浏览器tab 也会回调onchange 方法 值也被+1

**Comment by dicallc** [comment]
找到原因了，因为用css去修改了slider的样式
```
      .ant-slider-handle{
            //height: 40px;
            //width: 40px;
            margin-top: 2px;
          }
```

一旦修改height  和width 就会发生上面我阐述的问题

能提供修改滑块的大小和颜色么

**Comment by afc163** [comment]
Try https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L477
