### ISSUE TITLE
Upload组件 headers 仅支持 IE 10 以上吗？

### ISSUE THREAD

**Issue by yifanyou** [ant-design/ant-design#1376]
请问还有别的方式支持修改headers吗，如果用chrome

**Comment by afc163** [comment]
IE10 和正常浏览器都是支持的。

**Comment by yifanyou** [comment]
我用的版本是"antd": "^0.12.4"，是因为版本问题吗？

我用IE11，headers传进去了，用Chrome （版本 49.0.2623.87 m）没效果

**Comment by afc163** [comment]
http://ant.design/components/upload/#demo-basic

你试试这个例子，我用 chrome 测试的结果，headers 是生效的。

![](https://os.alipayobjects.com/rmsportal/VYQuMtdmkeYIGVC.png)

**Comment by yifanyou** [comment]
我的是跨域请求...
![qq 20160411231527](https://cloud.githubusercontent.com/assets/8372481/14432131/593f2218-003b-11e6-863b-01e5c6d0c86f.jpg)
![qq 20160411231544](https://cloud.githubusercontent.com/assets/8372481/14432137/60d99dd2-003b-11e6-8711-9ac74b8bcc70.jpg)
