### ISSUE TITLE
upload删除问题

### ISSUE THREAD

**Issue by Hal-pan** [ant-design/ant-design#13770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
antd v3.10.8

### Environment
chrome:70, os: sierra 10.12.1 react:16.6.3,  antd: 3.10.8

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx#L162](https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx#L162)

### Steps to reproduce
点击删除，然后beforeRemove返回 false ， 当前文件已经是removed状态了 

### What is expected?
点击删除，然后在beforeRemove返回 false ， 当前文件状态不变， 当beforeRemove没有阻止remove操作的时候状态改为removed

### What is actually happening?
点击删除，然后在beforeRemove返回 false ， 当前文件已经是removed状态了 

---
没有删除但是状态改为removed ，对使用方根据状态过滤处理会有影响

**Comment by afc163** [comment]
我们没有提供 `beforeRemove` 这样的 API。

**Comment by Hal-pan** [comment]
提供出来的是`onRemove`API  内部代码`handleRemove`方法 在返回false的时候  file.status已经是`removed`  
这点是不是可以优化一下  false的时候不改变file.status

**Comment by afc163** [comment]
@Hal-pan 可以来个 PR
