### ISSUE TITLE
Menu希望能选中子菜单的时候母菜单也能高亮，另外，什么时候改造成redux呢- -

### ISSUE THREAD

**Issue by EdenLiang** [ant-design/ant-design#1378]
目前如果menu有子集，那当选子集的时候父级并没有active
目前只能用 react-router-redux来再做一层封装
如果可以的话，可以在父级在一个参数，判断是否在子集选中的时候，父级select
原demo-link:http://ant.design/components/menu/

**Comment by afc163** [comment]
onClick 里有一个 keyPath 可以用。https://github.com/react-component/menu/pull/22

http://ant.design/components/menu/#demo-sider-current

另外，antd 是 UI 层，不负责数据流向。
