### ISSUE TITLE
[Select] Display wrong when Checkbox inside Select.Option

### ISSUE THREAD

**Issue by zy410419243** [ant-design/ant-design#13780]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

When I check https://github.com/ant-design/ant-design/issues/10757, it reproduces a new bug.

### Version
3.11.2

### Environment
Window 10, Chrome 71.0.3578.98

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6w4wkol4kz)

### Steps to reproduce
![avatar](https://i.loli.net/2018/12/22/5c1dca9c5afed.gif)

- click text `a10`

### What is expected?
nothing

### What is actually happening?
nothing

**Comment by afc163** [comment]
https://codesandbox.io/s/xry1wzyyoo
