### ISSUE TITLE
New component - Responsive or MediaQuery

### ISSUE THREAD

**Issue by filipjnc** [ant-design/ant-design#13785]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There is currently no way to conditionally render components based on media query attributes. While the docs suggest good complement libraries for that (react-responsive or react-media), implementing them feels like an unnecessary outsourcing of functionality that is partially already there in antd:
- In antd the breakpoints are already defined. Using a 3rd party library would mean having two sources of breakpoints definition (unless there is an API for getting the breakpoints out of antd, which I haven't found so far).
- Antd supports partially this functionality within its Layout and Grid components (attributes "breakpoint" and "onBreakpoint"). Why not pulling this functionality into a separate component, extend it a bit and make it available for the public as well? 

### What does the proposed API look like?
I suggest a new component (e.g. Responsive, MediaQuery, Hidden/Display) which reuses what's there within the Layout and Grid components and which will be extended with the rendering implementation from 'react-media' (more efficient than 'react-responsive' since the 'react-media' neither shows nor renders the children if media query is not met).

**Comment by ztplz** [comment]
We need more feedback to decide if we need to add new components. Keep it open to collect more feedback.

**Comment by afc163** [comment]
https://material-ui.com/components/use-media-query/

`Grid.useResponsive` or `Grid.useBreakpoint`

**Comment by MihaiWill** [comment]
YES! This I was looking for in documentation and I was amazed there is not something similar. 
How you guys handle responsive header for example?
 I pass the breakpoints props from `Sider` -> `onBreakpoint` property to Header component, but it become very messy if I want to pass it to a component outside of layout for example.

**I think an API for getting the breakpoints will be HUGE help.**

**Comment by hc-codersatlas** [comment]
@MihaiWill isn't it currently done via css / less? Material UI only needs this due to the css in js solution really. If it's in css / less stick to it.

**Comment by afc163** [comment]
close in favor of https://github.com/ant-design/ant-design/pull/22226
