### ISSUE TITLE
The table columns type error

### ISSUE THREAD

**Issue by j3l11234** [ant-design/ant-design#13793]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.3

### Environment
"typescript": "^3.2.2"

### Reproduction link
[https://github.com/j3l11234/antd-bug-demo](https://github.com/j3l11234/antd-bug-demo)

### Steps to reproduce
clone the repo
run `yarn install`
run `yarn start`
you will see the error

### What is expected?
I will work

### What is actually happening?
show
```
(59,16): Type '({ key: string; title: string; dataIndex: string; render?: undefined; align?: undefined; } | { title: string; key: string; render: (text: string, record: Item) => string; dataIndex?: undefined; align?: undefined; } | { ...; })[]' is not assignable to type 'ColumnProps<Item>[]'.
  Type '{ key: string; title: string; dataIndex: string; render?: undefined; align?: undefined; } | { title: string; key: string; render: (text: string, record: Item) => string; dataIndex?: undefined; align?: undefined; } | { ...; }' is not assignable to type 'ColumnProps<Item>'.
    Type '{ key: string; title: string; dataIndex: string; render?: undefined; align?: undefined; }' is not assignable to type 'ColumnProps<Item>'.
      Types of property 'dataIndex' are incompatible.
        Type 'string' is not assignable to type '"id" | "attrA" | "attrB" | "attrC" | undefined'.
```

---
I think the commit https://github.com/ant-design/ant-design/commit/f8fbb33c7387ede0b190050be5d2551bd2429212 is the reason.
maybe  it is a bug of typescript
the bug demo code

``` javascript

interface A {
  a: string;
}

function abc<T>(arg: {dataIndex?: keyof T}) {
  console.log(arg);
}


//work
abc<A>({ dataIndex: 'a' });


// don't work
const arg = { dataIndex: 'a' };
abc<A>(arg);


```

**Comment by afc163** [comment]
@bondBo 

ref #13605

**Comment by ztplz** [comment]
你的例子不是个bug
![image](https://user-images.githubusercontent.com/17755202/50382044-347c3e80-06d1-11e9-8ae6-0efb95fb0f3b.png)
你已经把arg的类型确定好了 它的类型是 { dataIndex: string }, 跟你要求的类型不一样 
![image](https://user-images.githubusercontent.com/17755202/50382050-655c7380-06d1-11e9-94c0-42c2b899a586.png)
这样检查参数类型的时候 发现类型符合 所以ok
同样的道理  那个pr也一样 
dataIndex 是个可选的枚举类型  
![image](https://user-images.githubusercontent.com/17755202/50382069-d56af980-06d1-11e9-92a7-81525fd0826b.png)
但是你
![image](https://user-images.githubusercontent.com/17755202/50382075-e451ac00-06d1-11e9-80da-472f5bced02b.png)直接把类型定义好了  
![image](https://user-images.githubusercontent.com/17755202/50382078-f0d60480-06d1-11e9-85ea-a0f73a26f3d8.png)
你可以ka看到你定义的这个  dataIndex是string类型  
然后类型检查的时候 跟要求的dataIndex可选的枚举类型冲突了

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50382089-3a265400-06d2-11e9-97a7-092eafb5e674.png)
这个意思其实没错，因为dataIndex确实是keyof T
但是有的用户在ts里会直接const columns = {
 dataIndex: 'xxx"
}
这样就会有问题了

**Comment by j3l11234** [comment]
> ![image](https://user-images.githubusercontent.com/17755202/50382089-3a265400-06d2-11e9-97a7-092eafb5e674.png)
> 这个意思其实没错，因为dataIndex确实是keyof T
> 但是有的用户在ts里会直接const columns = {
> dataIndex: 'xxx"
> }
> 这样就会有问题了

是的，其实也可以说是typescript在类型推断的时候还不够灵活，比如说他会吧 `{ dataIndex: 'a' }`定义为`{ dataIndex: string }`而不是{ dataIndex: 'a' }。一个折中的方式是 `{ dataIndex: 'a' as 'a'}`

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50382187-9ab69080-06d4-11e9-8303-49eea2836df5.png)
从antd里引入这个类型
![image](https://user-images.githubusercontent.com/17755202/50382198-bc177c80-06d4-11e9-9bd3-c822c77d9d75.png)

**Comment by tomasfrancisco** [comment]
Hi guys, this issue was helpful for me! 
But shouldn't it be shown somewhere on the docs? 

I know the docs are not in typescript, but perhaps a warning for the inference would be helpful?

**Comment by ztplz** [comment]
@tomasfrancisco  Actually this is a typescript issue, but I think it would be helpful to add some docs for it.

**Comment by tomasfrancisco** [comment]
@ztplz I just found this part of the documentation: https://ant.design/components/table/#Using-in-TypeScript

It's descriptive and enough, I guess! I just needed to be more attentive.
