### ISSUE TITLE
DatePicker 日期选择 点击今天按钮 会出现时间多出一天

### ISSUE THREAD

**Issue by Kshao123** [ant-design/ant-design#13795]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.9

### Environment
Mac 10.13.3  谷歌  71.0.3578.98（正式版本）react 16.6.3

### Reproduction link
[https://codepen.io/kshao123/pen/pqPNLw](https://codepen.io/kshao123/pen/pqPNLw)

### Steps to reproduce
点击select date  选择今天按钮 会出现时间多出一天（onChange 中的 date: moment） 点击完之后 在选择其他日期皆会出现此情况

### What is expected?
当天时间

### What is actually happening?
第二天时间

**Comment by afc163** [comment]
这样描述看不懂的。

**Comment by Kshao123** [comment]
> 这样描述看不懂的。

复现链接里的 datepicker 中，点击 today 按钮后，打印出的时间是24号的时间 应该是23号的

**Comment by Kshao123** [comment]
> 这样描述看不懂的。

当点击 today 按钮后再选择其他日期时 也会出现同样的情况

**Comment by afc163** [comment]
<img width="832" alt="default" src="https://user-images.githubusercontent.com/507615/50383783-3d7f0700-06f5-11e9-92d6-68173cbc2af0.png">

**Comment by afc163** [comment]
感觉只是 chrome 的对 moment 内部对象的显示问题：

https://codepen.io/anon/pen/Ormpza

**Comment by Kshao123** [comment]
> 感觉只是 chrome 的对 moment 内部对象的显示问题：
> 
> https://codepen.io/anon/pen/Ormpza

好吧 谢谢你的解答！

**Comment by afc163** [comment]
https://stackoverflow.com/a/31104671/3040605
