### ISSUE TITLE
Sider组件会导致所有组件render方法执行两次

### ISSUE THREAD

**Issue by coder-linx** [ant-design/ant-design#13798]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.4

### Environment
antd@latest, react@latest, react-dom@latest

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7wj062m3l0)

### Steps to reproduce
追踪代码发现antd/lib/layout/Sider.js文件176行，代码 `this.context.siderHook.addSider(this.uniqueId);` 导致该问题
```javascript
        key: 'componentDidMount',
        value: function componentDidMount() {
            if (this.mql) {
                this.mql.addListener(this.responsiveHandler);
                this.responsiveHandler(this.mql);
            }
            if (this.context.siderHook) {
                this.context.siderHook.addSider(this.uniqueId);
            }
        }
```

### What is expected?
期望render只执行一次，由于刚接触react时间并不长，不太确定该问题是否会有性能问题，但是该问题会导致页面上所有组件render被调用两次。

### What is actually happening?
render被执行了两次，参考重现链接中的console.log信息。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8983
