### ISSUE TITLE
IE8/9 的兼容性审查

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#138]
问题记录在这里：
- [x] 315e61a33d5dd8f721e45a4722092f57baf5b24a react-slick 需要 profill
- [x]  #145 组件搜索框在 IE10/11 下会自动展开，在 IE8/9 下因为没有 placeholder 导致看不见搜索输入框
### IE9下
- [x] ~~Layout Flex 布局无效~~
- [x] Select 智能提示 Demo 输入框内容向上偏移
- [x] Tabs 中的左侧箭头按钮样式
- [x] Pagination 左侧箭头按钮以及省略号的样式
  ![aabc9dba2202c223fd17ba4972a17110](https://cloud.githubusercontent.com/assets/7301773/9301476/608a056a-4501-11e5-9aa7-456277b3a509.png)
- [x] Table 表头文字与内容文字不对齐 24aba9ea24b7f945fbabd5950c25e0a3eed2e7da
- [x] Notification Demo 里的关闭方法需要完善
- [x] Upload 上传按钮补白部分点击无效，两个拖拽上传点击无效
- [x] Popover Tooltip Popconfirm 的位置 Demo 里的顺序建议调整为左、上、下、右
### IE8下
- [x] Form 行内表单失效
- [x] InputNumber 右侧按钮箭头方向
- [x] Slider 拖动无效，Icon Demo 里的 icon 错位
- [x] Select 箭头方向
- [x] Collapse 箭头方向，嵌套 Demo 里内部面板收缩时，外部面板不能收缩
- [x] Carousel 完全失效
- [x] Pagination 左右按钮箭头偏移
- [x] Upload 上传按钮补白部分点击无效，两个拖拽上传点击无效，样式偏移
- [x] Dropdown 下拉框没有上边框
- [x] Table 表头文字与内容文字不对齐 24aba9ea24b7f945fbabd5950c25e0a3eed2e7da

**Comment by sorrycc** [comment]
看了下 react-slick，貌似本身就不支持 IE8 。。我看下怎么改下。

**Comment by zhujun24** [comment]
## 万恶的 IE 兼容问题求认领
Select 然则 @warmhug 
Upload 玄寂 @pigcan 
Slider 在飞 @simaQ 
Carousel 云谦 @sorrycc 
Collapse 翰文 @shepherdwind 
InputNumber 承玉 @yiminghe

**Comment by shepherdwind** [comment]
额上传在ie下应该不支持拖拽的，Collapse我研究下。IE8下我以为能用就行了的

**Comment by afc163** [comment]
没事，这里只是列出问题，我们对兼容性有结论就好，不用强求。

**Comment by sorrycc** [comment]
https://github.com/akiran/react-slick/pull/103

**Comment by afc163** [comment]
拖拽上传组件 IE 下不支持拖拽可以理解，点击应该要可以呀。

**Comment by simaQ** [comment]
是 再飞 不是 在飞，认领了

**Comment by afc163** [comment]
到底在不在飞？

**Comment by warmhug** [comment]
是 autoprefixer-loader 在 ie8下生成的`filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=2)...` 这些？有测试这个filter在ie8下能正常工作吗？ 这个用的地方很多、貌似影响很大。 @afc163 @yiminghe

**Comment by simaQ** [comment]
@warmhug  IE8 下是可以的，你可以看 iconfont，但是不能用在 `:before` `:after` 伪元素上

```css
.@{iconfont-css-prefix}-backward                      {.ie-rotate(2);}
.@{iconfont-css-prefix}-backward:before               {content:"\e630";.rotate(180deg);}
```

**Comment by warmhug** [comment]
对的 @simaQ 多谢

**Comment by zhujun24** [comment]
Select 的箭头在 IE8 下好了，IE9 下又有问题了 @warmhug 
![6d23a9cd-ddbc-42c6-b5ae-1e382ddf16d3](https://cloud.githubusercontent.com/assets/7301773/9374210/1a9d783a-4726-11e5-92eb-f381125df6bf.png)

**Comment by warmhug** [comment]
@zhujun24 边角溢出已修复；ie上箭头方向修复了、但箭头会变大、似乎不能两全、谁比较了解求帮助~

**Comment by yiminghe** [comment]
rotate 不要放在 before 上试试

**Comment by shepherdwind** [comment]
箭头那个巨麻烦，ie里面如果使用缩放，会非常丑的

![image](https://cloud.githubusercontent.com/assets/452899/9426863/f90ad306-498d-11e5-9b15-9d4c59d89a49.png)

另外位置也便宜了，因为正常的一个icon是21px那么大小，缩放实际上，空间还是在那里的。

感觉用旋转来实现icon，要兼容ie，实在痛苦啊。

**Comment by pimkle** [comment]
Collapse的箭头，在IE9下会换行

**Comment by pimkle** [comment]
Modal对话框 弹出的时候，右侧滚动条消失，留下一个很丑的白块：https://ant.design/components/modal-cn/

**Comment by pimkle** [comment]
progress loading circle在ie9上动画只显示第一帧，不会转动

**Comment by benjycui** [comment]
* [ ] Collapse的箭头，在IE9下会换行
* [ ] Modal对话框 弹出的时候，右侧滚动条消失，留下一个很丑的白块，而且布局会向左靠：https://ant.design/components/modal-cn/

以上两点确认是有问题。

> progress loading circle在ie9上动画只显示第一帧，不会转动

这个问题不知道是什么， Progress 没有 laoding 属性。

**Comment by benjycui** [comment]
@pimkle 可以帮忙看看怎么解决？

**Comment by pimkle** [comment]
@benjycui 

> progress loading circle在ie9上动画只显示第一帧，不会转动
> 这个问题不知道是什么， Progress 没有 loading 属性。

上面这个问题 你用IE9访问下下面这个url就知道了：

**Comment by benjycui** [comment]
@pimkle Progress 和 Spin 是两个组件。。要区分开啊。

antd 中的动画都是用 CSS3 做的，所以在老 IE 下面会有损失，这个也不计划适配。

**Comment by pimkle** [comment]
@benjycui 👌🏻

**Comment by benjycui** [comment]
@pimkle 另外两个问题，就麻烦你看看了，谢谢。

**Comment by afc163** [comment]
Collapse 箭头错位的问题在 af9dc73 里修复了。

> Modal对话框 弹出的时候，右侧滚动条消失，留下一个很丑的白块

白块是给滚动条占位的，不算 bug。

**Comment by magnnus** [comment]
@afc163 

> Modal对话框 弹出的时候，右侧滚动条消失，留下一个很丑的白块

这里问题是 占位的宽度太大了，我在ie9上看，body的padding-right是34px，造成向左错位的视觉效果...  直接访问站点的modal组件即可复现

**Comment by budiga** [comment]
使用antd的Upload上传图片，在IE9里如何实现图片预览啊？
有哪个属性能得到选择的本地图片的路径嘛？能知道路径的话是不是可以通过滤镜实现预览，通过new ActiveXObject("Scripting.FileSystemObject")来验证文件大小、类型？
@afc163 @shepherdwind @pigcan

**Comment by kwzm** [comment]
@afc163 您好，我看您把 flex 给划掉了，但是我在使用的过程中发现IE9的layout flex 还是不行

**Comment by yoyo837** [comment]
@kwzm IE9 不支持 flex https://caniuse.com/#search=Flexible
