### ISSUE TITLE
组件样式丢失

### ISSUE THREAD

**Issue by dkvirus** [ant-design/ant-design#13803]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.4

### Environment
MacOS10.13，Chrome 70.0，

### Reproduction link
[https://github.com/dkvirus/dav-antd-integration-demo](https://github.com/dkvirus/dav-antd-integration-demo)

### Steps to reproduce
- clone 项目到本地；
- npm install 安装依赖；
- npm run start 启动项目；
- 浏览器中输入 localhost:8000 打开首页。

### What is expected?
表格样式不会丢失。

### What is actually happening?
表格样式丢失。

---
[子工程](https://github.com/dkvirus/dva-antd-products-demo) 用到了 antd   dva 那套，页面包含一个表格 Table 和一个按钮 Button，在子工程中运行是正常的。将子工程打成一个 npm 包，在 [集成工程](https://github.com/dkvirus/dav-antd-integration-demo) 中安装子工程依赖，集成工程也是 dva   antd 那套，发现按钮组件是可以正常显示的，表格组件样式丢失。

**Comment by dkvirus** [comment]
子工程正常情况显示如下：

![image](https://user-images.githubusercontent.com/29170168/50391554-b330b480-0781-11e9-9b2f-02a69026396b.png)

集成工程异常页面显示如下：Table 样式完全不生效。

![image](https://user-images.githubusercontent.com/29170168/50391545-972d1300-0781-11e9-8ddb-2db7181efefc.png)

> 这一套玩法在 antd 3.1.0 版本都是 ok 的，子工程打成 npm 包进行引用，那时候页面显示也没问题，最近升级 antd 就遇到这个尴尬的问题了。

**Comment by dkvirus** [comment]
定位了下，应该不是 antd 的问题，是 roadhog 升级后的问题。

**Comment by yesmeck** [comment]
是 antd 的问题，我们也碰到了。

**Comment by yesmeck** [comment]
https://unpkg.com/antd@3.11.4/lib/table/style/css.js

https://unpkg.com/antd@3.10.0/lib/table/style/css.js

在 3.11.4 里 css 文件 import 到的是 less，roadhog 默认会给 less 启用 css modules，导致样式显示不出来。

**Comment by LY-LiYi** [comment]
from表单组件也是样式有问题的

**Comment by afc163** [comment]
要尽快发版本修复。

**Comment by zombieJ** [comment]
@dkvirus @LY-LiYi 已修复，重装一下 antd~

**Comment by dkvirus** [comment]
@zombieJ  兄弟，讲道理，我装了 3.11.5 Table 组件样式还是有问题，Button 样式正常显示。复现仓库还是上面那两个仓库。

**Comment by dkvirus** [comment]
试了一下，将 IndexPage.js 中的 Button 按钮删掉，果然连按钮样式也没了。thx @zombieJ 的耐心解答。🌹🌹🌹

```
export default {
    extraBabelIncludes: [
        'node_modules/dva-antd-products-demo'
    ],
    extraBabelPlugins: [
        [ 'import', { libraryName: 'antd', libraryDirectory: 'es', style: 'css' } ],
    ]
}
```

这是 roadhog 的 .webpackrc.js 配置文件。之前加上 `extraBabelIncludes` 属性是可以处理 node_modules 里面的子包，子包工程 dva-antd-products-demo 是有用到 Table 组件和 Button 组件的，是可以正常显示的。我去 roadhog 社区找了下，说是 2.4.1 版本之后废弃了 extraBabelIncludes 属性，导致现在页面无法正常显示。

**Comment by LY-LiYi** [comment]
看了下 input框是.ant-input-affix-wrapper .ant-input{min-height: 100%;} 给表单添加个盒子设置高度为0解决了

**Comment by chj-damon** [comment]
> 试了一下，将 IndexPage.js 中的 Button 按钮删掉，果然连按钮样式也没了。thx @zombieJ 的耐心解答。🌹🌹🌹
> 
> ```
> export default {
>     extraBabelIncludes: [
>         'node_modules/dva-antd-products-demo'
>     ],
>     extraBabelPlugins: [
>         [ 'import', { libraryName: 'antd', libraryDirectory: 'es', style: 'css' } ],
>     ]
> }
> ```
> 
> 这是 roadhog 的 .webpackrc.js 配置文件。之前加上 `extraBabelIncludes` 属性是可以处理 node_modules 里面的子包，子包工程 dva-antd-products-demo 是有用到 Table 组件和 Button 组件的，是可以正常显示的。我去 roadhog 社区找了下，说是 2.4.1 版本之后废弃了 extraBabelIncludes 属性，导致现在页面无法正常显示。
> 
> 我现在要做的是用用到子包中的组件和样式，这一点和用 antd 包是很相似的，不知道为啥 antd 就可以做到组件样式起作用。我想了想 `extraBabelIncludes` 貌似只对 node_modules 下面包的 js 代码进行转译，貌似不会处理样式。😴😴😴😴😴😴

请问最后是通过配置extraBabelIncludes解决的吗？我现在也遇到这个问题了。我是自己基于antd建了一个组件库，在umi项目里面用。组件库里面一个组件里面import其他组件，其他组件的样式就出不来。

**Comment by xiaocaimeng007** [comment]
我也遇到了，Table 放到我的插件里面再引入到项目中，样式就失效了，在原来项目中都是好的，最后解决了吗你们？

**Comment by xiaocaimeng007** [comment]
> > 试了一下，将 IndexPage.js 中的 Button 按钮删掉，果然连按钮样式也没了。thx @zombieJ 的耐心解答。🌹🌹🌹
> > ```
> > export default {
> >     extraBabelIncludes: [
> >         'node_modules/dva-antd-products-demo'
> >     ],
> >     extraBabelPlugins: [
> >         [ 'import', { libraryName: 'antd', libraryDirectory: 'es', style: 'css' } ],
> >     ]
> > }
> > ```
> > 
> > 
> > 这是 roadhog 的 .webpackrc.js 配置文件。之前加上 `extraBabelIncludes` 属性是可以处理 node_modules 里面的子包，子包工程 dva-antd-products-demo 是有用到 Table 组件和 Button 组件的，是可以正常显示的。我去 roadhog 社区找了下，说是 2.4.1 版本之后废弃了 extraBabelIncludes 属性，导致现在页面无法正常显示。
> > 我现在要做的是用用到子包中的组件和样式，这一点和用 antd 包是很相似的，不知道为啥 antd 就可以做到组件样式起作用。我想了想 `extraBabelIncludes` 貌似只对 node_modules 下面包的 js 代码进行转译，貌似不会处理样式。😴😴😴😴😴😴
> 
> 请问最后是通过配置extraBabelIncludes解决的吗？我现在也遇到这个问题了。我是自己基于antd建了一个组件库，在umi项目里面用。组件库里面一个组件里面import其他组件，其他组件的样式就出不来。
我也遇到了，你怎么解决的啊

**Comment by xiaocaimeng007** [comment]
在.babelrc里面改了这个"plugins": [
     [
      "import",
      {
        libraryName: "antd",
        libraryDirectory: "es",
        style: true
      }
    ]
  ]
