### ISSUE TITLE
Notification无法关闭对应Key值的弹出框,Notification.close(key)无效

### ISSUE THREAD

**Issue by prpr2012** [ant-design/ant-design#13810]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
谷歌浏览器

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
Notification.open(key),然后过几秒后close(key)

### What is expected?
关闭对应key值的Notification弹出框

### What is actually happening?
 没有关闭对应的Notification弹出框

**Comment by smwanyi** [comment]
今天我也遇到这个问题,已解决,
key必须是String类型,文档里面有标注,而我传的是Number类型的.就无法关闭.
还有,我的需求是做websocket,把redux里面的多条通知数据用这个提醒展示出来.
我发现直接for循环,多个提醒窗口会重叠在一起.而写个setInterval让每个弹窗有点点延迟就不会重叠在一起.有大佬有更好的解决方案吗?
