### ISSUE TITLE
为什么不经过开发者的允许就在按钮上加上圣诞节的彩蛋？

### ISSUE THREAD

**Issue by hh54188** [ant-design/ant-design#13819]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我留意到按钮组件的上方出现了一块雪花？这是圣诞节彩蛋吧？为什么不经过开发者的允许就擅自加上了？

### What does the proposed API look like?
如何下线？

**Comment by zy410419243** [comment]
https://github.com/ant-design/ant-design/issues/13098

**Comment by zlusers** [comment]
请问如何解决

**Comment by smk0621** [comment]
非常不专业的做法，值得商榷

**Comment by MokerT** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

那为什么还要开放出来呢。。。还会有元旦、春节彩蛋？？？

**Comment by wanghaooo** [comment]
为什么不弄个API，想关的可以关闭

**Comment by BillQiu** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

毫无开源的责任意识。

**Comment by ChenHao92** [comment]
老板已经扣我工资了，你们看着办吧

**Comment by Whiteyork** [comment]
关键是单词还拼错了，这就很尴尬了
![image](https://user-images.githubusercontent.com/23288061/50409427-8639db80-082d-11e9-86d2-7c288efd907b.png)

**Comment by titianqx** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

信任就是好处  那些star也是好处

**Comment by javaLuo** [comment]
这太愚蠢了。你们是不是换产品经理了...

**Comment by elaninhust** [comment]
想想近期的zz氛围...确实过分了哈哈哈

**Comment by SynChron1zed** [comment]
我们是发改委的项目啊 antd的大哥们   到现在水都没喝一口  要不是我小姨子在里面上班 我现在卷铺盖滚蛋了

**Comment by 133922249** [comment]
> 去掉 ho! 在顶层app容器中添加
> 
> ```
> componentDidUpdate() {
>    const now = new Date();
>    if (now.getMonth() === 11 && now.getDate() === 25) {
>      document.querySelectorAll('button').forEach(
>        btn => btn.setAttribute('title', '')
>      );
>    }
>  }
> ```

如果自己额外设置了title的button如何解决

**Comment by hyy1115** [comment]
版本不要更新，安装之前的版本

**Comment by lixiaolihua** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

牛逼！！！

**Comment by camiler** [comment]
> > 去掉 ho! 在顶层app容器中添加
> > ```
> > componentDidUpdate() {
> >    const now = new Date();
> >    if (now.getMonth() === 11 && now.getDate() === 25) {
> >      document.querySelectorAll('button').forEach(
> >        btn => btn.setAttribute('title', '')
> >      );
> >    }
> >  }
> > ```
> 
> 如果自己额外设置了title的button如何解决

再判断下title是否是ho!吧  🤦‍♀️

**Comment by youyeke** [comment]
> > 去掉 ho! 在顶层app容器中添加
> > ```
> > componentDidUpdate() {
> >    const now = new Date();
> >    if (now.getMonth() === 11 && now.getDate() === 25) {
> >      document.querySelectorAll('button').forEach(
> >        btn => btn.setAttribute('title', '')
> >      );
> >    }
> >  }
> > ```
> 
> 如果自己额外设置了title的button如何解决

多写一个 if 判断
```
if(btn.title === 'hohoho'){
  btn.setAttribute('title', '')
}
```

**Comment by 133922249** [comment]
```
    const now = new Date();
    const isChristmas = now.getMonth() === 11 && now.getDate() === 25;
    const classes = classNames(prefixCls, className, {
      [`${prefixCls}-${type}`]: type,
      [`${prefixCls}-${shape}`]: shape,
      [`${prefixCls}-${sizeCls}`]: sizeCls,
      [`${prefixCls}-icon-only`]: !children && icon,
      [`${prefixCls}-loading`]: loading,
      [`${prefixCls}-background-ghost`]: ghost,
      [`${prefixCls}-two-chinese-chars`]: hasTwoCNChar,
      [`${prefixCls}-block`]: block,
      christmas: isChristmas,
    });

    const iconType = loading ? 'loading' : icon;
    const iconNode = iconType ? <Icon type={iconType} /> : null;
    const kids = (children || children === 0)
      ? React.Children.map(children, child => insertSpace(child, this.isNeedInserted())) : null;

    const title= isChristmas ? 'Ho Ho Ho!' : rest.title;
```
这是源码, 我自己设置的title完全被覆盖了,拿到的title全是hohoho

**Comment by kigawas** [comment]
> 我们是发改委的项目啊 antd的大哥们 到现在水都没喝一口 要不是我小姨子在里面上班 我现在卷铺盖滚蛋了

https://www.zhihu.com/question/306858501/answer/559174756
老哥，是你么？

**Comment by FrendKao** [comment]
期待春节的彩蛋，期待中表情...

**Comment by hyy1115** [comment]
> 我们是发改委的项目啊 antd的大哥们 到现在水都没喝一口 要不是我小姨子在里面上班 我现在卷铺盖滚蛋了

你有小姨子，怕什么

**Comment by roojay520** [comment]
之前看到一些学校和机关发文，明令禁止过洋节。用这个给政府和学校做项目的，今天估计凉了一半。

**Comment by ctq123** [comment]
我觉得挺好的，干嘛要搞得那么严肃，这是一个意外的惊喜

**Comment by SynChron1zed** [comment]
@kigawas 是的 老哥 快不行了 感觉明天不用来了

**Comment by camiler** [comment]
> ```
>     const now = new Date();
>     const isChristmas = now.getMonth() === 11 && now.getDate() === 25;
>     const classes = classNames(prefixCls, className, {
>       [`${prefixCls}-${type}`]: type,
>       [`${prefixCls}-${shape}`]: shape,
>       [`${prefixCls}-${sizeCls}`]: sizeCls,
>       [`${prefixCls}-icon-only`]: !children && icon,
>       [`${prefixCls}-loading`]: loading,
>       [`${prefixCls}-background-ghost`]: ghost,
>       [`${prefixCls}-two-chinese-chars`]: hasTwoCNChar,
>       [`${prefixCls}-block`]: block,
>       christmas: isChristmas,
>     });
> 
>     const iconType = loading ? 'loading' : icon;
>     const iconNode = iconType ? <Icon type={iconType} /> : null;
>     const kids = (children || children === 0)
>       ? React.Children.map(children, child => insertSpace(child, this.isNeedInserted())) : null;
> 
>     const title= isChristmas ? 'Ho Ho Ho!' : rest.title;
> ```
> 这是源码, 我自己设置的title完全被覆盖了,拿到的title全是hohoho

ant这确实过分了，部分按钮你可以用<a> 或者其他标签替换

**Comment by Lijingwen1104** [comment]
要是程序员自己搞得估计要祭天了

**Comment by hyy1115** [comment]
> 之前看到一些学校和机关发文，明令禁止过洋节。用这个给政府和学校做项目的，今天估计凉了一半。

如果有使用webpack编译，就很好解决，写一个loader，在解析html的时候，把class里面的彩蛋字母给干掉。

**Comment by chenhebing** [comment]
> > 之前看到一些学校和机关发文，明令禁止过洋节。用这个给政府和学校做项目的，今天估计凉了一半。
> 
> 如果有使用webpack编译，就很好解决，写一个loader，在解析html的时候，把class里面的彩蛋字母给干掉。

赶紧写个webpack 插件

**Comment by youyeke** [comment]
> ```
>     const now = new Date();
>     const isChristmas = now.getMonth() === 11 && now.getDate() === 25;
>     const classes = classNames(prefixCls, className, {
>       [`${prefixCls}-${type}`]: type,
>       [`${prefixCls}-${shape}`]: shape,
>       [`${prefixCls}-${sizeCls}`]: sizeCls,
>       [`${prefixCls}-icon-only`]: !children && icon,
>       [`${prefixCls}-loading`]: loading,
>       [`${prefixCls}-background-ghost`]: ghost,
>       [`${prefixCls}-two-chinese-chars`]: hasTwoCNChar,
>       [`${prefixCls}-block`]: block,
>       christmas: isChristmas,
>     });
> 
>     const iconType = loading ? 'loading' : icon;
>     const iconNode = iconType ? <Icon type={iconType} /> : null;
>     const kids = (children || children === 0)
>       ? React.Children.map(children, child => insertSpace(child, this.isNeedInserted())) : null;
> 
>     const title= isChristmas ? 'Ho Ho Ho!' : rest.title;
> ```
> 这是源码, 我自己设置的title完全被覆盖了,拿到的title全是hohoho

这种情况要么回退版本；要么自己在本地把 antd 彩蛋部分的代码去掉，然后重新发一个版本；要么等明天。

**Comment by zcSkr** [comment]
好好玩阿，建议做春节鞭炮、端午粽子。哈哈哈

**Comment by yujianxia** [comment]
几家欢喜几家愁

**Comment by hyy1115** [comment]
> > ```
> >     const now = new Date();
> >     const isChristmas = now.getMonth() === 11 && now.getDate() === 25;
> >     const classes = classNames(prefixCls, className, {
> >       [`${prefixCls}-${type}`]: type,
> >       [`${prefixCls}-${shape}`]: shape,
> >       [`${prefixCls}-${sizeCls}`]: sizeCls,
> >       [`${prefixCls}-icon-only`]: !children && icon,
> >       [`${prefixCls}-loading`]: loading,
> >       [`${prefixCls}-background-ghost`]: ghost,
> >       [`${prefixCls}-two-chinese-chars`]: hasTwoCNChar,
> >       [`${prefixCls}-block`]: block,
> >       christmas: isChristmas,
> >     });
> > 
> >     const iconType = loading ? 'loading' : icon;
> >     const iconNode = iconType ? <Icon type={iconType} /> : null;
> >     const kids = (children || children === 0)
> >       ? React.Children.map(children, child => insertSpace(child, this.isNeedInserted())) : null;
> > 
> >     const title= isChristmas ? 'Ho Ho Ho!' : rest.title;
> > ```
> > 这是源码, 我自己设置的title完全被覆盖了,拿到的title全是hohoho
> 
> 这种情况要么回退版本；要么自己在本地把 antd 彩蛋部分的代码去掉，然后重新发一个版本；要么等明天。

不用ant-design的路过

**Comment by yujianxia** [comment]
> 好好玩阿，建议做春节鞭炮、端午粽子。哈哈哈

你怕是 要上头那几个兄弟被公司祭天哦

**Comment by tabris17** [comment]
建议因为这个傻逼彩蛋而被公司开除的码农去阿里要个说法

**Comment by zcSkr** [comment]
> 那几个兄弟被公司祭天哦

外企可能有点严肃，国企发现了改了不就完了嘛，我觉得祭天事件，只是恰巧找个借口而已

**Comment by milixie** [comment]
震惊！

**Comment by 2012shenghua** [comment]
老板喊我谈话了，半年奖金没了

**Comment by zcSkr** [comment]
> 老板喊我谈话了，半年奖金没了

什么原因阿？为什么要这么严肃

**Comment by marsprince** [comment]
政治正确真恶心

**Comment by zcSkr** [comment]
antd 刚刚 3.11.6版本发布了 ，移除圣诞节彩蛋，更新就完了

**Comment by jackie19** [comment]
已取消star

**Comment by tgxpuisb** [comment]
> > 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？
> 
> 并非是你自己的库 而是蚂蚁金服的库，你也并非代表你自己发言 而是代表整个蚂蚁的所有前端在发言~

那人不是我们蚂蚁金服的

**Comment by Senzz** [comment]
发现还是用的3.3.0版本，没影响

**Comment by lazy1523** [comment]
？？？是不是傻逼，一大早被政府用户投诉，怀疑我们留了系统后门。现在系统停掉了，为什么这么任性？！

**Comment by QCCS** [comment]
我也没有允许你使用，你就使用了？

**Comment by tabris17** [comment]
> ？？？是不是傻逼，一大早被政府用户投诉，怀疑我们留了系统后门。现在系统停掉了，为什么这么任性？！

国家三令五申不过洋节，你们顶风作案啊，哈哈哈

**Comment by JoeysWang** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？
你算个j8

**Comment by JoeysWang** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

你算个J8

**Comment by FlyKite** [comment]
> 我也没有允许你使用，你就使用了？

不把MIT License当回事？

**Comment by haipengz** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

这个发言欠妥。

这是个开源的库，也就是社区的库，并不是属于某个组织的，这个库只是蚂蚁金服有管理权限而已。
信任和star即使好处。
所有参与贡献新功能、修bug而提交的代码也是好处。

**Comment by netroby** [comment]
发明这个彩蛋的人，拖出来，犬决，炮决，车裂。

**Comment by huangyiminghappy** [comment]
why you so piiii?

**Comment by fanux** [comment]
工作量不饱满，还有时间写彩蛋

**Comment by saybabi** [comment]
下班吧 到点了！

**Comment by netroby** [comment]
不正之风不宜助长。春节是不是给我来个春联？福字贴？过分了。

**Comment by zcSkr** [comment]
不正之风不宜助长。端午节是不是给我来个粽子？划龙舟？过分了。

**Comment by fanux** [comment]
不正之风不宜助长。清明节是不是给我们来个冥币？放鞭炮？过分了。

**Comment by yozosann** [comment]
核心问题不在于这个彩蛋本身 而是在于开发者使用了这个库并且项目失控了

**Comment by ZZhaoTireless** [comment]
不正之风不宜助长。清明节是不是给我们来个冥币？放鞭炮？过分了。

**Comment by ZZhaoTireless** [comment]
不正之风不宜助长。中秋节是不是给我们来个月饼？赏月亮？过分了。

**Comment by hades0525** [comment]
禁止过洋节，你就搞了个这个  
如何看待 antd 圣诞节彩蛋事件？ - 陈启明的回答 - 知乎
https://www.zhihu.com/question/306858501/answer/559220307

**Comment by wzc0x0** [comment]
不正之风不宜助长。六四节是不是给我们来个坦克？开坦克？过分了。

**Comment by xixiaoyu** [comment]
核心问题不在于这个彩蛋本身 而是在于开发者使用了这个库并且项目失控了

**Comment by zhanghuidinah** [comment]
以后过节前可以来个投票 蓝绿发布一波 要记得提前通知...

**Comment by diguage** [comment]
到清明节是不是要来个坟头菜单？🤣

**Comment by ZhanPeng** [comment]
核心问题是开发企业或者开发者选用库的时候，没有做过跟踪和验证

**Comment by unixzii** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

祝你幸福

**Comment by hechen0** [comment]
前排板凳 瓜子火腿肠 收收腿来~

**Comment by RiuHDuo** [comment]
真爱生命远离蚂蚁金服， 感觉同是阿里系的东西蚂蚁金服推出的服务都特么恶心

**Comment by tonymiao2012** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

u suck bro

**Comment by Liqiankun** [comment]
有个彩蛋有啥问题吗？我感觉还可以没啥问题！

**Comment by wzxaini9** [comment]
你跟他说。。。这是冬至下的雪。结果堵车了。现在才出来。。。天太冷了。。还没化呢

**Comment by blusewang** [comment]
阿里必将死于自以为是的“小聪明”

**Comment by balthild** [comment]
虽说不经过事先提示就加入彩蛋在道义上是一种不负责任的行为，但是它**并非是不合理的**。

因为 MIT License 的文本里面是有这样一段话的：

```
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
```

**Comment by lylpixin2121** [comment]
> 我们是发改委的项目啊 antd的大哥们 到现在水都没喝一口 要不是我小姨子在里面上班 我现在卷铺盖滚蛋了

忍不住给老哥点个赞

**Comment by CoatiFly** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

煞笔

**Comment by FlyKite** [comment]
> 虽说不经过事先提示就加入彩蛋在道义上是一种不负责任的行为，但是它**并非是不合理的**。
> 
> 因为 MIT License 的文本里面是有这样一段话的：
> 
> ```
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
> NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
> LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
> OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
> WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
> ```
> 这段话也并非 MIT 协议独有，很多协议都包含。即使有小部分不包含，使用那些协议的库的作者中也有大部分会自己加上。
> 
> 因此，理论上用户在使用任何一个库之前，就应该做好自行为它的代码负责的准备。当然，作者并非可以为所欲为，否则他要承担自毁口碑的**后果**（但不是**责任**）。

很棒，感觉有挺多人并没有了解开源协议。。。

**Comment by panhainan** [comment]
> 工作量不饱满，还有时间写彩蛋

@你们领导，你还有时间吃瓜，赶紧写bug去

**Comment by BertieGo** [comment]
期待 4.1 的彩蛋

**Comment by blusewang** [comment]
> 我们是发改委的项目啊 antd的大哥们 到现在水都没喝一口 要不是我小姨子在里面上班 我现在卷铺盖滚蛋了

认清阿里，重新做人吧！阿里的这种“小聪明”是深入骨髓的。看看支付宝协议、支持那啥的校园贷...阿里的成功，让所有阿里人有了区别于所有IT人的优越感。感觉阿里人永远比非阿里人聪明那么一点点。

**Comment by JimmyVV** [comment]
唯有取消 给你的 star 表示一点点小小敬意。

**Comment by shixinglong007** [comment]
还好我们锁定了久版本，虚惊一场

**Comment by ctq123** [comment]
> > 我们是发改委的项目啊 antd的大哥们 到现在水都没喝一口 要不是我小姨子在里面上班 我现在卷铺盖滚蛋了
> 
> 认清阿里，重新做人吧！阿里的这种“小聪明”是深入骨髓的。看看支付宝协议、支持那啥的校园贷...阿里的成功，让所有阿里人有了区别于所有IT人的优越感。感觉阿里人永远比非阿里人聪明那么一点点。

没有必要黑，就事论事，拒绝人身攻击

**Comment by HuChundong** [comment]
事件影响深远，，感觉要说88了啊antd

**Comment by anykno** [comment]
> > 虽说不经过事先提示就加入彩蛋在道义上是一种不负责任的行为，但是它**并非是不合理的**。
> > 因为 MIT License 的文本里面是有这样一段话的：
> > ```
> > THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> > EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> > MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
> > NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
> > LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
> > OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
> > WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
> > ```
> > 这段话也并非 MIT 协议独有，很多协议都包含。即使有小部分不包含，使用那些协议的库的作者中也有大部分会自己加上。
> > 因此，理论上用户在使用任何一个库之前，就应该做好自行为它的代码负责的准备。当然，作者并非可以为所欲为，否则他要承担自毁口碑的**后果**（但不是**责任**）。
> 
> 很棒，感觉有挺多人并没有了解开源协议。。。

老踩不到点啊你们，责任，一个开源项目能付个什么责任，但是一个项目要健康发展，是需要建立起良好的社区环境的，公信力当然是不可或缺的，没人敢用的项目再nb有啥用，况且，还不说对蚂蚁金服的品牌公信力的负面影响。

**Comment by xyzdata** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

# 还要点 face 吗？这是开源库，好多人都因为你们的行为而背锅！

照你这种说法，所有的开源软件是不是都可以随意植入挖坑脚本呀？

https://github.com/ant-design/ant-design/issues/13098

**Comment by anykno** [comment]
> > > 虽说不经过事先提示就加入彩蛋在道义上是一种不负责任的行为，但是它**并非是不合理的**。
> > > 因为 MIT License 的文本里面是有这样一段话的：
> > > ```
> > > THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> > > EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> > > MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
> > > NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
> > > LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
> > > OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
> > > WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
> > > ```
> > > 这段话也并非 MIT 协议独有，很多协议都包含。即使有小部分不包含，使用那些协议的库的作者中也有大部分会自己加上。
> > > 因此，理论上用户在使用任何一个库之前，就应该做好自行为它的代码负责的准备。当然，作者并非可以为所欲为，否则他要承担自毁口碑的**后果**（但不是**责任**）。
> > 
> > 
> > 很棒，感觉有挺多人并没有了解开源协议。。。
> 
> 老踩不到点啊你们，责任，一个开源项目能付个什么责任，但是一个项目要健康发展，是需要建立起良好的社区环境的，公信力当然是不可或缺的，没人敢用的项目再nb有啥用，况且，还不说对蚂蚁金服的品牌公信力的负面影响。

更加深远的，这样的事件会导致企业使用和参与开源有更多的疑虑，对开源文化对伤害是非常深远对

**Comment by RiuHDuo** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

彩蛋是给用户，这个是ui库的用户是web开发者，你爱怎么给都可以，但是至今跳过开发者，给用户的用户就有点过分了。

**Comment by bighamx** [comment]
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**Comment by xumeng** [comment]
这个事情应该是开发人员擅自加的feature，没想到大家这么上纲上线。
阿里是时候正视自己，严肃地做一些事情了。

**Comment by passos** [comment]
开发人员出来背锅了，但是阿里的代码上线没有Code Review吗？“一意孤行”的代码能上线？如果是后门代码是不是也能上线？

那些说因为是开源库所以踩坑就活该的，你大概是没中过之前那个开源库的“rm -rf  / xxx”的bug，因为多了一个空格直接系统被删的，当然没法去追究赔偿责任，给项目一个差评并谴责也不行吗？

**Comment by Eusen** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？

你是antd作者？

**Comment by Eusen** [comment]
> 个人觉得这次“彩蛋”给我们上了一堂课，在我们上线正式项目的时候，应该正确地估量“开源项目”的潜在风险，除此之外，在使用一些第三方框架的同时也应该注意这类问题。开源项目并不会为你的错误而买单。
> 
> 出现“彩蛋事件”后，我在github issue，或者网络或多或少看到的是：
> 
> > 毫无开源的责任意识。
> 
> > ？？？是不是傻逼，为什么这么任性？！
> 
> 等等的言论，一但出现问题，就是这个库的错，而不是反思自己为什么会出现这种问题？我只想说的是开源库，并没有义务为你负起责任。
> 
> ### 最后，当使用一个开源库的时候，你就应该做好自行为它的代码负责的准备，而不是推卸责任。

没人不愿意负责，起码能提前告诉开发者，并给大家选择的权力吧。

**Comment by nier-shoot** [comment]
火了

**Comment by jianhaobinan** [comment]
> 个人觉得这次“彩蛋”给我们上了一堂课，在我们上线正式项目的时候，应该正确地估量“开源项目”的潜在风险，除此之外，在使用一些第三方框架的同时也应该注意这类问题。开源项目并不会为你的错误而买单。
> 
> 出现“彩蛋事件”后，我在github issue，或者网络或多或少看到的是：
> 
> > 毫无开源的责任意识。
> 
> > ？？？是不是傻逼，为什么这么任性？！
> 
> 等等的言论，一但出现问题，就是这个库的错，而不是反思自己为什么会出现这种问题？我只想说的是开源库，并没有义务为你负起责任。
> 
> ### 最后，当使用一个开源库的时候，你就应该做好自行为它的代码负责的准备，而不是推卸责任。

那你用每一个开源项目是不是要把源码全部读一遍确保没有问题？你用linux要读内核代码吗？这里没有谁推卸责任，该付的责任他们已经在做了。这里声讨是因为他们标榜企业应用场景却搞出这么不严肃的东西，再里面埋不合理的彩蛋，玩笑开过头了，说蚂蚁金服没责任感难道有问题？开源不代表就能肆意妄为，就跟公众人物要比普通人更要注意言行一样

**Comment by Sraw** [comment]
> 虽说不经过事先提示就加入彩蛋在道义上是一种不负责任的行为，但是它**并非是不合理的**。
> 
> 因为 MIT License 的文本里面是有这样一段话的：
> 
> ```
> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
> EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
> MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
> NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
> LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
> OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
> WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
> ```
> 这段话也并非 MIT 协议独有，很多协议都包含。即使有小部分不包含，使用那些协议的库的作者中也有大部分会自己加上。
> 
> 因此，理论上用户在使用任何一个库之前，就应该做好自行为它的代码负责的准备。当然，作者并非可以为所欲为，否则他要承担自毁口碑的**后果**（但不是**责任**）。

首先，这可以说是“符合开源协议”的，但并不是“合理”的。任何一个理性的人，在事发后回头去思考这件事情，都清楚这是“不合理”的。

其次，开源协议并非免死金牌，真的造成实际损失时，这份协议在法律上能贡献多少责任减免？这次是插入彩蛋，若是下次插入病毒，难道也可以靠这份协议置之事外？

最后，都实际一点吧。企业开源自家框架，从社区中是受益无穷的。真的好意思说什么“有的用就不错了”之类的话吗？600+的Contributors全是企业内部员工吗？上万的issues全部是内部人员提出来的？

**Comment by chai2010** [comment]
开源终于慢慢露出本质了：谁的地盘谁做主，本质上就是这样，

**Comment by byronzoz** [comment]
> > 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？
> 
> 你是antd作者？

不是。我只是站在一个使用者的角度上，表达我个人的观点。

**Comment by Eusen** [comment]
> > > 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？
> > 
> > 
> > 你是antd作者？
> 
> 不是。我只是站在一个使用者的角度上，表达我个人的观点。

你的观点非常不符合开源精神，如果开源作者是这样的人，那么这个开源项目必死。

**Comment by clearloop** [comment]
感觉彩蛋挺棒的，把吐槽的时间拿来改一改源码不就好了

**Comment by Dengjiansheng** [comment]
学好英文，这个也太扯淡了

**Comment by shiguang1120** [comment]
> > > 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？
> > 
> > 
> > 你是antd作者？
> 
> 不是。我只是站在一个使用者的角度上，表达我个人的观点。

啧啧，不知道是反黑还是真蠢
[https://github.com/shiguang1120/Android/blob/master/TIM%E6%88%AA%E5%9B%BE20181225170910.png](img_url)

**Comment by shiguang1120** [comment]
> > > 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？
> > 
> > 
> > 你是antd作者？
> 
> 不是。我只是站在一个使用者的角度上，表达我个人的观点。


啧啧，不知道是反黑还是真蠢
![image](http://wx3.sinaimg.cn/mw690/73e1e15fly1fyj40k167cj20zj0gg0tx.jpg)

**Comment by goodfeeling** [comment]
天下大事必作于细

**Comment by caengcjd** [comment]
认真看下《关于实施中华优秀传统文化传承发展工程的意见》

**Comment by caengcjd** [comment]
认真看下《关于实施中华优秀传统文化传承发展工程的意见》

**Comment by chai2010** [comment]
JS热更新的问题，还是WebAssembly安全：
https://github.com/chai2010/awesome-wasm-zh

**Comment by orca-zhang** [comment]
还好没有选用antd，现在用的vant也有看大部分实现。

“为什么不经过开发者的允许就擅自加上了？”
建议改为
“为什么擅自加上彩蛋而不通知开发者。”
为妥，前者稍刺耳。

**Comment by TsaiYee** [comment]
我有个疑问，企业使用不应该相应版本freeze，到本地么？ 难道每次都从远程读？这样被人加了后门都不知道啊。

**Comment by luoshaohua** [comment]
我们是发改委的项目啊 antd的大哥们 到现在水都没喝一口 要不是我小姨子在里面上班 我现在卷铺盖滚蛋了

回复: 不应该是卷鼠标垫走人吗？难道睡在公司！

**Comment by JasonHK** [comment]
大家好像忘記了npm的left-pad chaos 了…… 🌝

**Comment by izee** [comment]
> 我们是发改委的项目啊 antd的大哥们 到现在水都没喝一口 要不是我小姨子在里面上班 我现在卷铺盖滚蛋了

感觉你这么一说，你的小姨子可能会面临比你更大的问题

**Comment by vkedwardli** [comment]
外國企業看到也只會一笑置之，近年中国的政治正確把這彩蛋妖魔化了

又不見大家去抗議中共禁聖誕

**Comment by RiuHDuo** [comment]
> 外國企業看到也只會一笑置之，近年中国的政治正確把這彩蛋妖魔化了
> 
> 又不見大家去抗議中共禁聖誕
繁体字是来挑衅的吗

**Comment by hcconquer** [comment]
> 我们是发改委的项目啊 antd的大哥们 到现在水都没喝一口 要不是我小姨子在里面上班 我现在卷铺盖滚蛋了

老哥，你小姨子有主了么？我们私信聊聊？😁

**Comment by hang333** [comment]
> 借楼问下，有没有可以一键block用户的chrome扩展，刚好过滤一波，以后不会关注也不会使用他们的开源项目。

自己造啊

**Comment by xiaodongalex** [comment]
> 自己的库，自己做主，你没给我一分钱，我没拿你一分好处，你凭什么要求我？
> 
> just joke

你怎么知道我没给一分钱？

**Comment by LjyYano** [comment]
1

**Comment by hengyanqwe** [comment]
> 外國企業看到也只會一笑置之，近年中国的政治正確把這彩蛋妖魔化了
> 
> 又不見大家去抗議中共禁聖誕

假如美国州政府网站上在伊斯兰教的节日出了个赞美真主安拉的彩蛋，你还会这么说吗？俩不搭边的东西硬扯到一块，钱属实是到位了
