### ISSUE TITLE
关于使用table自带pagination的问题

### ISSUE THREAD

**Issue by zsj1029** [ant-design/ant-design#1382]
## 我使用table自带的分页，发现默认不包含total总记录数

请教一下，不使用独立的pagination的情况下，如何显示total数量呢？谢谢了

**Comment by afc163** [comment]
Table 有 pagination 参数的。

**Comment by zsj1029** [comment]
我我看到了参数，但是具体使用不知道怎么加showTotal这个方法在页面显示总记录数，试了好多种方法都不行，提示props的问题

**Comment by afc163** [comment]
最好给例子，无法重现。

**Comment by zsj1029** [comment]
warning.js:45 Warning: Failed propType: Invalid prop `showTotal` of type `number` supplied to `Pagination`, expected `function`. Check the render method of `AntPagination`.

`class ProductTable extends React.Component {

    constructor() {
        super();
        this.state = {
            data: [],
            pagination: {},
            loading: false,
        };

    }

    handleTableChange(pagination, filters, sorter) {
        const pager = this.state.pagination;
        pager.current = pagination.current;
        pager.showTotal = ((total)=>{
            return `共 ${total} 条`;
        });
        this.setState({
            pagination: pager,
        });
        this.fetch({
            size: pagination.pageSize,
            page: pagination.current,
            sortField: sorter.field,
            sortOrder: sorter.order,
            ...filters,
        });
    }

    fetch(params = {size:10}) {
        console.log('请求参数：', params);
        this.setState({ loading: true });
        reqwest({
            url: pageUrl,
            method: 'get',
            data: params,
            type: 'json',
            crossOrigin: true,
            success: (result) => {
                const pagination = this.state.pagination;
                pagination.total = parseInt(result.data.count);
                pagination.showTotal = parseInt(result.data.count);
                this.setState({
                    loading: false,
                    data: result.data.list,
                    pagination,
                });
            }
        });
    }

    componentDidMount() {
        this.fetch();
    }

    render() {
        return (
            <div>
                <Table rowSelection={rowSelection}
                       columns={columns}
                       dataSource={this.state.data}
                       pagination={this.state.pagination}
                       loading={this.state.loading}
                       onChange={this.handleTableChange.bind(this)}
                       rowKey={record => record.p_id}
                />

            </div>
        )
    }
}`

**Comment by zsj1029** [comment]
搞定了，es6 写起来各种不习惯

**Comment by sfpprxy** [comment]
@zsj1029 请问如何搞定的？

**Comment by yedf** [comment]
zsj1029贴出来的代码中 
pager.showTotal = total => `共 ${total} 条`;

**Comment by Simple2012hcz** [comment]
showQuickJumper=true,此时onChange发生变化，不会去改变输入框中的页码。

**Comment by dengsibao** [comment]
in model pagination default setting like this:
pagination: {
      current: 1,
      pageSize: 20,
      total: 0,
      showTotal: ((total)=>{return `共 ${total} 条`})
}
it will solve your problem

**Comment by dengsibao** [comment]
in model pagination default setting like this:
`pagination: {
    current: 1,
    pageSize: 20,
    total: 0,
    showTotal: ((total)=>{return 共 ${total} 条})
}`
it will solve your problem

**Comment by yehoan** [comment]
怎么通过回调自定义设置回到多少页 呢

**Comment by yehoan** [comment]
比如在第4页来个请求 然后自定义回到第一页

**Comment by yehoan** [comment]
showQuickJumper=true,此时onChange发生变化，不会去改变输入框中的页码。
