### ISSUE TITLE
Upload上传多个文件会请求多次

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#13820]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Upload当multiple设置为true时，也就是可以支持多选文件上传，比如选择10个文件一起上传，发现请求次数也是10次，而且如果我要弹窗提示是否上传成功的话，会弹10次弹窗，请问怎样可以只请求一次接口

### What does the proposed API look like?
Upload当multiple设置为true时，也就是可以支持多选文件上传，比如选择10个文件一起上传，发现请求次数也是10次，而且如果我要弹窗提示是否上传成功的话，会弹10次弹窗，请问怎样可以只请求一次接口

**Comment by bosscheng** [comment]
可以看看源码，就知道了。

**Comment by afc163** [comment]
Duplicate of #8579
