### ISSUE TITLE
Button 圣诞节自动加的怎么去掉

### ISSUE THREAD

**Issue by zlusers** [ant-design/ant-design#13824]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by plainnany** [comment]
把button的christmas类去掉就好了

**Comment by zlusers** [comment]
> 把button的christmas类去掉就好了
是要修改源码？ 有不需要修改源码的方法吗？

**Comment by plainnany** [comment]
![image](https://user-images.githubusercontent.com/27320655/50408933-9b147000-0829-11e9-8799-74ce5a49b112.png)
你可以给这个before设置个属性opacity:0，或者display: none

**Comment by plainnany** [comment]
[#13098](https://github.com/ant-design/ant-design/issues/13098)
