### ISSUE TITLE
😨 Table align broken when cell contains long number or long word after 3.11.3

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#13825]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

https://github.com/ant-design/ant-design/pull/13774#issuecomment-449723598
不用设置x即可重现

### Version
3.11.3 +

### Environment
macos 10.14.2 chrome 71

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mynlj2x12x)

### Steps to reproduce
打开重现链接即可见

### What is expected?
y设置后列头对齐

### What is actually happening?
对不齐

**Comment by lidianhao123** [comment]
你这个情况加上固定宽度就解决了
```js
const columns = [
  {
    title: "Name",
    dataIndex: "name",
    width: 200,
  },
  {
    title: "Address",
    dataIndex: "address",
    width:200,
  }
];
```

**Comment by afc163** [comment]
还是超长连续字段破坏表格布局的问题，之前加过 `word-break: break-word;` 去纠正此类布局，又会引起 https://github.com/ant-design/ant-design/issues/13624 的问题。

所以最好的解决方案可能还是不默认 break word，提供一个属性来针对某些列进行断行处理。

```
columns={[
  ...
  wordBreak: true,
]}
```

**Comment by yoyo837** [comment]
@lidianhao123 我的表格都有固定宽度，Reproduction link 里的不用写也能重现，就没写。

**Comment by afc163** [comment]
@yoyo837 你这个例子应该写了 width 就能修正了，这种情况确实要写的，好像不是我说的上面的情况。

**Comment by afc163** [comment]
https://codesandbox.io/s/3y60m0wvwp

**Comment by afc163** [comment]
给出写了 width 也对不齐的 demo 再 reopen 吧。

**Comment by afc163** [comment]
@yoyo837 Bingo! 就是 https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241 的问题。

**Comment by a305566804** [comment]
同样的问题，请问如何解决？

**Comment by vxzhong** [comment]
但是，现在这个改动是不是算breaking change，现在只能回退到3.10.10的版本，不然设置的width都不生效，而原来有大量的页面都是通过设置width来限制宽度的。

**Comment by yoyo837** [comment]
@vxzhong 只能先自己补
```css
  .ant-table-tbody > tr > td {
    word-wrap: break-word;
    word-break: break-all;
    hyphens: auto;
  }
```

然后正常升级`antd`, 解决方案合入后再删掉。

**Comment by koupeng** [comment]
这个问题还没有解决啊----

**Comment by afc163** [comment]
@koupeng https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by fiveLucky** [comment]
还有一种问题，表格创建时 表格单元格内的文本是个枚举值，比如就是 'status' ，此时单元格已经设定好宽度，并且单元格未折行，后面通过请求，渲染为中文 '整体输出状态'， 此时单元格折行了，导致这个单元格对应的行高度变高，但是这一行 对应的fixed 的单元格 高度没变，出现表格 错行 的情况，这个和浏览器没关系，ant版本是2.x。求解决啊

**Comment by xupengkun** [comment]
设置table属性  `table-layout:fixed;` 宽度即生效

**Comment by x7zhang** [comment]
> 设置table属性 `table-layout:fixed;` 宽度即生效

fancy, man, fancy!!

**Comment by zoffyzhang** [comment]
> 设置table属性 `table-layout:fixed;` 宽度即生效

ur the best

**Comment by yoyo837** [comment]
@zoffyzhang Only for fixed width, not responsive width.

**Comment by wulienen** [comment]
> 设置table属性 `table-layout:fixed;` 宽度即生效

虽然生效，但是固定列的话，文字超长的字段还是会撑开

**Comment by xupengkun** [comment]
@wulienen 包裹超长字段，`overflow : hidden` 后即可忽略超出部分

**Comment by wulienen** [comment]
> @wulienen 包裹超长字段，`overflow : hidden` 后即可忽略超出部分

这样列动态拉伸就不能实现省略号展开 。😂

**Comment by xupengkun** [comment]
> > @wulienen 包裹超长字段，`overflow : hidden` 后即可忽略超出部分
> 
> 这样列动态拉伸就不能实现省略号展开 。😂

使用该属性会舍弃掉组件本身的动态宽度，你需要给每一列设置宽度，否则就会平均分配，如果需要文字省略显示则`text-overflow: ellipsis;`

**Comment by pawoma** [comment]
.ant-table-tbody > tr > td {
  white-space: nowrap;
}
.ant-table-thead > tr > th{
  white-space: nowrap;
}

**Comment by ddcatgg** [comment]
遇到了同样的问题，结合 [xupengkun](https://github.com/ant-design/ant-design/issues/13825#issuecomment-487374735) 和 [yoyo837](https://github.com/ant-design/ant-design/issues/13825#issuecomment-452942830) 的方案后完美解决了，感谢大家的努力！

[问题原型](https://github.com/ant-design/ant-design/issues/13825#issuecomment-449897145)
解决后：https://codesandbox.io/s/sg5r2

**Comment by VEMTK** [comment]
@ddcatgg 
![$O A%{JC6TK68JP7JK@2%A2](https://user-images.githubusercontent.com/23647215/58774644-10fcde80-85f5-11e9-93ea-5e0059e5fd86.png)

**Comment by heavenlian** [comment]
没解决， 多层childern， 有复选框而且文本超长。这个情况。更加解决不了

**Comment by afc163** [comment]
@heavenlian 给可重现 demo 我来帮你改好。

**Comment by heavenlian** [comment]
@afc163 
解决了，写个循环嵌套，给每个table下面的 tr.ant-table-row-level-${i}，计算里面 展开icon偏离大小，再动态设置文本需要的宽度。……

**Comment by ZengTianShengZ** [comment]
I solved it perfectly with css

[codesandbox demo](https://codesandbox.io/s/throbbing-hooks-wqoi4)

```
.ant-table-thead tr {
  display: flex;
}
.ant-table-thead th {
  flex: 1;
}
.ant-table-row {
  display: flex;
}
.ant-table-row td {
  flex: 1;
  overflow: auto;
}
.ant-table-row td::-webkit-scrollbar {
  display: none;
}
.columns {
  display: flex;
  align-items: center;
  width: 30px;
}

```

**Comment by heavenlian** [comment]
@ZengTianShengZ   perfect .

**Comment by miaozilong** [comment]
如何自动显示和隐藏滚动条? 
横向和纵向都需要支持
https://codesandbox.io/s/currying-river-6n2r5

**Comment by sstokke** [comment]
@ZengTianShengZ Amazing work!

**Comment by StallionV** [comment]
This issue is still present and should really be addressed as part of the main table component, instead of applying CSS hacks. Thanks to all who have helped provide a fix, but the table should render column headers correctly by default

**Comment by StallionV** [comment]
> https://codesandbox.io/s/sg5r2

This solution provided by users above works perfectly. 
The only issue being you have to specify width for every column.
The way the table should really work is 
1. Column headers should always align with the body
2. Specifying width should not be a hack or mandatory.  
3. You can specific width in numbers of percentage. Based on that it would be a % of the total table width or fixed width specified in number. 
4. All other columns to auto adjust themselves based on content from the space remaining after the fixed or % width distribution.

Check http://w2ui.com/web/demos/#!grid/grid-23 as reference.
This is a pretty powerful grid alas for pure JS not react. But it does this all amazingly well.

**Comment by xianghongai** [comment]
```less
.table_nowrap {
  table th,
  table td {
    white-space: nowrap;
  }
}
```

```jsx
<div className="table_nowrap">
  <Table scroll={{ x: true }} ... />
</div>
```

**Comment by smartchong** [comment]
js code:
const columns = [
            {
                title: 'goodName',
                key: 'goodName',
                dataIndex: 'goodName',
                align: 'center',
                width: 150,
                fixed: 'left',
                render: (item) => (item || item == 0 ? (<span className=' textOverflow maxWidth118' title={item}>{item}</span>) : (<span className='show'>--</span>))
            }];
css code:
.textOverflow{
  white-space: nowrap!important;
  overflow: hidden!important;
  text-overflow: ellipsis!important;
}
.maxWidth118{
  max-width: 118px;
}
用了笨方法，render里套一个标签，给标签设置样式，过长显示省略号，加上title属性

**Comment by afc163** [comment]
Pull Request sent: #17284

**Comment by StallionV** [comment]
> .ant-table-thead tr {
>   display: flex;
> }
> .ant-table-thead th {
>   flex: 1;
> }
> .ant-table-row {
>   display: flex;
> }
> .ant-table-row td {
>   flex: 1;
>   overflow: auto;
> }
> .ant-table-row td::-webkit-scrollbar {
>   display: none;
> }
> .columns {
>   display: flex;
>   align-items: center;
>   width: 0;
> }

That works, but makes all columns with equal width. You would really want width of each column to be dynamic based on content.

**Comment by YuZaiShui** [comment]
how to set percent width in the Columns Settings, seem doesn't work.

**Comment by jane-xxx** [comment]
实现固定列，固定的列的宽度支持百分比后表格没办法看啦 什么情况啊，是不支持百分比嘛

**Comment by afc163** [comment]
@jane-xxx 支持的，如果有问题可以发一个 codesandbox 来我帮你调好。

**Comment by PresByter2015** [comment]
width: 150, width 设置number类型。string，没效果。

**Comment by praburocking** [comment]
HI, I migrated from antd 3 to 4, and I am experiencing issue in table, initially in and 3 the table width was the parent elements width, but now it seems it width is adjusting to the content in the table, I have gone through the doc, I can't find anything to solve my issue. I will attach the image of the table from both version for the reference.
<img width="1182" alt="Screen Shot 2020-04-07 at 3 37 28 PM" src="https://user-images.githubusercontent.com/25414943/78657558-9375bf00-78e6-11ea-9791-24d0c2948e01.png">
<img width="1662" alt="Screen Shot 2020-04-07 at 3 39 54 PM" src="https://user-images.githubusercontent.com/25414943/78657573-983a7300-78e6-11ea-997d-a9272c15d858.png">

**Comment by weapon008** [comment]
> HI, I migrated from antd 3 to 4, and I am experiencing issue in table, initially in and 3 the table width was the parent elements width, but now it seems it width is adjusting to the content in the table, I have gone through the doc, I can't find anything to solve my issue. I will attach the image of the table from both version for the reference.
> <img alt="Screen Shot 2020-04-07 at 3 37 28 PM" width="1182" src="https://user-images.githubusercontent.com/25414943/78657558-9375bf00-78e6-11ea-9791-24d0c2948e01.png">
> <img alt="Screen Shot 2020-04-07 at 3 39 54 PM" width="1662" src="https://user-images.githubusercontent.com/25414943/78657573-983a7300-78e6-11ea-997d-a9272c15d858.png">

maybe set <Table  tableLayout="fixed"/> will help

**Comment by muzishuiji** [comment]
超短的内容也会导致宽度的设置失效.~
![image](https://user-images.githubusercontent.com/18276045/84342966-81abe300-abd9-11ea-91fb-470f22ea031a.png)
![image](https://user-images.githubusercontent.com/18276045/84342993-91c3c280-abd9-11ea-9098-a5c099bba5c4.png)

请教下大佬上述情况怎么处理?

**Comment by muzishuiji** [comment]
> 给出写了 width 也对不齐的 demo 再 reopen 吧。

超短的内容也会导致宽度的设置失效.~


> **超长连续字段（长数字和长单词）** 破坏表格布局的问题（**即使你指定了列的宽度也会被挤开**），之前组件内默认加过 `word-break: break-word;` 去纠正此类布局，又会引起 #13624 的问题。（[截图](https://user-images.githubusercontent.com/507615/54250117-75bc1600-457d-11e9-8645-61088c44a1eb.png)）
> 
> 所以最好的解决方案可能还是不默认 break word，提供一个属性来针对某些列进行断行处理。
> 
> ```js-jsx
> columns={[
>   ...
>   textWrap: 'word-break',
> ]}
> ```
> 
> 还可以和 #5753 一起做，支持
> 
> ```js-jsx
> columns={[
>   ...
>   ellipsis: true,
> ]}
> ```
> 
> 注意，在 3.24.0 之前，你需要针对超长字段的列增加折断样式：
> 
> ```js-jsx
> columns={[
>   ...
>   render: (text, record) => (
>     <div style={{ wordWrap: 'break-word', wordBreak: 'break-word' }}>
>       {text}
>     </div>
>   ),
> ]}
> ```
> 
> 已经在 3.24.0 里解决了超长字段破坏列对齐的问题，并增加了省略功能，具体 API 见：#17284

https://github.com/ant-design/ant-design/issues/13825#issuecomment-642389197

**Comment by eparizzi** [comment]
I'm sorry but I'm having a similar issue after migrating from 3.x to 4.x.
My Table looks like this on 4.x:
![image](https://user-images.githubusercontent.com/412489/85548458-3ead2f00-b61f-11ea-9ece-b8eb64c43740.png)

While it looks fine in 3.x:
![image](https://user-images.githubusercontent.com/412489/85548592-63090b80-b61f-11ea-9844-f27d90c12bd1.png)

I'm still not being able to reproduce the issue in a simplified Codesandbox. But in the meantime, I'd appreciate any help in English.

Thank you!

**Comment by codingbycat** [comment]
> I'm sorry but I'm having a similar issue after migrating from 3.x to 4.x.
> My Table looks like this on 4.x:
> ![image](https://user-images.githubusercontent.com/412489/85548458-3ead2f00-b61f-11ea-9ece-b8eb64c43740.png)
> 
> While it looks fine in 3.x:
> ![image](https://user-images.githubusercontent.com/412489/85548592-63090b80-b61f-11ea-9844-f27d90c12bd1.png)
> 
> I'm still not being able to reproduce the issue in a simplified Codesandbox. But in the meantime, I'd appreciate any help in English.
> 
> Thank you!

Did you set column width?
If you have already set column width, please try this. This method works for me
```jsx
<Table
    // some props...
   scroll={{ x: '100%' }} // this x should set '100%', not 'true'
 />
```

**Comment by eparizzi** [comment]
This has been fixed in a recent update.

**Comment by GhostYDFQ** [comment]
横向拖动有垂直的白色间隙怎么解决

**Comment by Oscar19921030** [comment]
> 横向拖动有垂直的白色间隙怎么解决

留一些非固定列不要定宽，让它自适应

**Comment by SrivathsaRaoI** [comment]
In antd table ,when we give width at column css of table breaks, width of column in header is not same as width of column in  #body.
![Screenshot 2021-01-13 200828222](https://user-images.githubusercontent.com/23190460/104468134-1dbd2300-55dd-11eb-8e06-b16095fae385.png)



import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Table, Tag, Space } from "antd";

const columns = [
  {
    title: "Name",
    dataIndex: "name",
    width: 50,
    render: (text) => <a>{text}</a>
  },
  {
    title: "Age",
    dataIndex: "age",
    width: 95
  },
  {
    title: "Address",
    dataIndex: "address",
    width: 120
  },
  {
    title: "Address1234567",
    dataIndex: "address1234567",
    width: 145
  },
  {
    title: "Tags",
    key: "tags",
    dataIndex: "tags",
    width: 200,
    render: (tags) => (
      <>
        {tags.map((tag) => {
          let color = tag.length > 5 ? "geekblue" : "green";
          if (tag === "loser") {
            color = "volcano";
          }
          return (
            <Tag color={color} key={tag}>
              {tag.toUpperCase()}
            </Tag>
          );
        })}
      </>
    )
  },
  {
    title: "Action",
    width: 130,
    render: (text, record) => (
      <Space size="middle">
        <a>Invite {record.name}</a>
        <a>Delete</a>
      </Space>
    )
  }
];

const data = [
  {
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
    address1234567: "i am testing whether it is working properly",
    tags: ["nice", "developer"]
  },
  {
    name: "Jim Green",
    age: 42,
    address: "London No. 1 Lake Park",
    tags: ["loser"],
    address1234567: "i am testing whether it is working properly"
  },
  {
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
    tags: ["cool", "teacher"],
    address1234567: "i am testing whether it is working properly"
  }
];

ReactDOM.render(
  <Table bordered={true}  tableLayout="fixed"  size="large" scroll= {{ y: 400, scrollToFirstRowOnChange:true, x:"100%" }} 
  columns={columns} dataSource={data} />,
  document.getElementById("container")

- [);[](url)](https://codesandbox.io/s/basic-usage-antd4102-forked-vgyg6?file=/index.js:0-1902)

**Comment by SrivathsaRaoI** [comment]
@empz @afc163 afc163 please help me to resolve the above said issue.Please reply in English.

**Comment by SrivathsaRaoI** [comment]
![Screenshot 2021-01-13 1111111](https://user-images.githubusercontent.com/23190460/104477630-59f58100-55e7-11eb-8754-64c3d63a74fb.png)
![Screenshot 2021-01-13 222222222](https://user-images.githubusercontent.com/23190460/104477653-6083f880-55e7-11eb-9fc0-0e78250583a1.png)
@empz @afc163 ,I have given width of column as 75px,but as shown in the above screen shot we can se in header width will be 1px less than table body part of the column ,here column width will be 74px in header where as width of the column in table body will be 75 px in columnGroup.

**Comment by empz** [comment]
@SrivathsaRaoI please stop tagging me. This is not the place to ask questions. If you need to file a bug on the library, create a new issue.

**Comment by crush996** [comment]
> > 横向预先有垂直的白色间隙怎么解决
> 
> 留一些非固定列不要定宽，让它适应

还是没有解决

**Comment by yoyo837** [comment]
I will lock it, if still have a problem, please feel free to create a new issue.
