### ISSUE TITLE
Remove Festival themes

### ISSUE THREAD

**Issue by TsangTszKin** [ant-design/ant-design#13822]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.5

### Environment
any

### Reproduction link
[https://ant.design/components/button-cn/#header](https://ant.design/components/button-cn/#header)

### Steps to reproduce
Open  the link

### What is expected?
The same theme as usual

### What is actually happening?
Christmas theme

**Comment by zy410419243** [comment]
https://github.com/ant-design/ant-design/issues/13098
