### ISSUE TITLE
请问怎么关闭圣诞树彩蛋

### ISSUE THREAD

**Issue by 662** [ant-design/ant-design#13829]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.5

### Environment
chrome latest

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
使用<Button type="primary"></Button>

### What is expected?
一个漂亮的Button

### What is actually happening?
按钮样式被一坨白色的东西遮挡

---
求解决，还有 HoHoHo！ 这一句无情的嘲讽；我现在面临非常严重的后果；

**Comment by H246802** [comment]
css解决

**Comment by kiinlam** [comment]
惊喜？不！惊吓！老板已经说要扣奖金了！
用css样式覆盖，important规则，所以呢？要发布一个版本才能解决？老板说不给发，必须解决，之前都没有的，怎么现在就出来了？

**Comment by sirzxj** [comment]
强烈建议把春节加上

**Comment by ctq123** [comment]
哈哈哈

**Comment by H246802** [comment]
> 惊喜？不！惊吓！老板已经说要扣奖金了！
> 用css样式覆盖，important规则，所以呢？要发布一个版本才能解决？老板说不给发，必须解决，之前都没有的，怎么现在就出来了？

小伙子实在是太惨了，哈哈哈

**Comment by lightyen** [comment]
在 node_modules/antd/lib/button.js 中：

var isChristmas = now.getMonth() === 11 && now.getDate() === 25
**isChristmas = false**

**Comment by 662** [comment]
> [#13819 (comment)](https://github.com/ant-design/ant-design/issues/13819#issuecomment-449789527)
> 
> `title` 可以先暂时这样，`css` 也可以这样移除

感谢

**Comment by 662** [comment]
> 在 node_modules/antd/lib/button.js 中：
> 
> var isChristmas = now.getMonth() === 11 && now.getDate() === 25
> **isChristmas = false**

感谢

**Comment by lwyj123** [comment]
字节跳动全年招聘，了解一下，简历发邮箱liangyuyi@bytedance.com

**Comment by toksea** [comment]
对于 build 后的代码，可以在 css 底部增加

```
.ant-btn.ant-btn-primary.christmas:before {
  display: none!important;
}
```

在 js 中搜索 'Ho Ho Ho!' 删除三元运算符，保留 : 之后的内容

**Comment by 404div** [comment]
惨，哈哈哈哈哈。。。。特意去看了自己之前的，还好没问题。。。

**Comment by staneee** [comment]
> 惊喜？不！惊吓！老板已经说要扣奖金了！
> 用css样式覆盖，important规则，所以呢？要发布一个版本才能解决？老板说不给发，必须解决，之前都没有的，怎么现在就出来了？

index.html加个样式吧，哈哈哈哈哈哈哈哈

**Comment by CruxCv** [comment]
笑死我了

**Comment by zhangyaoFkr** [comment]
说明你需要固定版本, 并在升级之前充分预估你升级带来的影响
@662

**Comment by zcSkr** [comment]
好好玩阿，建议做春节鞭炮、端午粽子。哈哈哈

**Comment by Lixucheng** [comment]
火钳刘明

**Comment by ctq123** [comment]
强烈建议把春节彩蛋加上，不能厚此薄彼

**Comment by anykno** [comment]
> 强烈建议把春节彩蛋加上，不能厚此薄彼

欢迎pr

**Comment by staneee** [comment]
![image](https://user-images.githubusercontent.com/26987099/50410526-6fe34e00-0834-11e9-9709-70c3dcab086b.png)

离职的可去 [这里](https://ant.design/components/button/)

**Comment by zcSkr** [comment]
> 强烈建议把春节彩蛋加上，不能厚此薄彼

chrismas和christmas的区别？
第一个指的是圣诞（耶稣的生日）第二个是指圣诞节这个节日
代码里面写的是第一个，调侃。

春节怕是不敢调侃哦

**Comment by FR15** [comment]
> ![image](https://user-images.githubusercontent.com/26987099/50410526-6fe34e00-0834-11e9-9709-70c3dcab086b.png)
> 
> 离职的可去 [这里](https://ant.design/components/button/)

阴谋论

**Comment by zcSkr** [comment]
话题终结了，3.11.6在40分钟前发布了。

**Comment by qiutuleng** [comment]
KPI的产物也敢用？
