### ISSUE TITLE
关于彩蛋的一个小建议

### ISSUE THREAD

**Issue by charliezzo** [ant-design/ant-design#13835]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了彩蛋的不可控

### What does the proposed API look like?
应该新建一个彩蛋属性，自己去定义要换哪个彩蛋。默认不开启。这样可以避免彩蛋的尴尬问题，并且大家可以做一些中国节日的彩蛋，方便使用。

**Comment by chengnuo** [comment]
有趣

**Comment by yutingzhao1991** [comment]
https://github.com/ant-design/ant-design/issues/13098#issuecomment-449754024

**Comment by zhengyangkang** [comment]
虽然这小彩蛋对我们公司没什么影响，但是不明白我们三个系统，就一个系统有彩蛋，很懵逼啊，antd版本号也一样，还和什么有关？

**Comment by Julius-Git** [comment]
花里胡哨，偏后端管理的组件这么不严谨。银行机构等若使用你们的组件那还得了？

**Comment by charliezzo** [comment]
我感觉彩蛋很有必要，这是一个企业级框架，不是一个政府级框架，所以只要把这种不是必要的东西做成自定义的属性就好了。没必要那么死板。默认关闭，不用的人别用就好了。

**Comment by nabaonan** [comment]
可以全局设置一个开启彩蛋的功能，可配置

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/d648b822a6b2789a783c7ad685a122466f6c083c

**Comment by PMExtra** [comment]
@afc163 https://github.com/ant-design/ant-design/commit/f706e255
这个2017彩蛋是否也该回滚或者统一到选项中。

**Comment by charliezzo** [comment]
@afc163  I think Christmas egg is very interesting ，and i like it . Do you have a plan for Spring Festival egg.

**Comment by fwh1990** [comment]
> 虽然这小彩蛋对我们公司没什么影响，但是不明白我们三个系统，就一个系统有彩蛋，很懵逼啊，antd版本号也一样，还和什么有关？

你的项目有加 yarn.lock  或者 npm-lock.json 吗？

**Comment by iamapig120** [comment]
> 虽然这小彩蛋对我们公司没什么影响，但是不明白我们三个系统，就一个系统有彩蛋，很懵逼啊，antd版本号也一样，还和什么有关？

服务器时间？
