### ISSUE TITLE
cascader 组件支持 非弹出式

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design#1383]
像这个：http://react-component.github.io/cascade-select/examples/simple.html 
![image](https://cloud.githubusercontent.com/assets/2011119/14419927/9c39aee8-fffb-11e5-9392-6d825c043525.png)

来自业务需求，不需要弹出层、要直接显示级联选择框。另外需要在每一个能选择列前加个label解释，如 省: `<select ...>` 市: `<select ...>`

**Comment by afc163** [comment]
http://ant.design/components/select/#demo-coordinate

**Comment by warmhug** [comment]
select 那个demo，多列的联动处理做起来比较麻烦，业务上他们反馈、希望组件做。
