### ISSUE TITLE
button 按钮出现一朵云,还有 title="Ho Ho Ho!" 

### ISSUE THREAD

**Issue by biyaoyao** [ant-design/ant-design#13837]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.4

### Environment
所有浏览器

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
直接打开

### What is expected?
解决button 按钮出现一朵云,还有 title="Ho Ho Ho!" 

### What is actually happening?
解决button 按钮出现一朵云,还有 title="Ho Ho Ho!"

**Comment by yutingzhao1991** [comment]
https://github.com/ant-design/ant-design/issues/13098 

3.11.6 已经关闭该彩蛋。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/d648b822a6b2789a783c7ad685a122466f6c083c

**Comment by hanchn** [comment]
政府项目会直接被开掉吧，埋彩蛋没想过后果吗

**Comment by jayasme** [comment]
智障彩蛋，开发团队闲得蛋疼出来作妖

**Comment by jayasme** [comment]
基础框架做好自己的本职工作，少出来作妖，人家网站要做彩蛋人家自己不会做，要你出来显摆？

**Comment by hanchn** [comment]
![20181225110835915](https://user-images.githubusercontent.com/8650965/50410672-76be9080-0835-11e9-8473-4532bf316881.jpg)

**Comment by hanchn** [comment]
作大死  想害阿里吗 ？？？？

**Comment by theMonkeyMan** [comment]
平时回答问题就拽不拉机的，现在做了让用户反感的事情，做的第一件事竟然是关闭评论，而不是给出一个合理的解释，"早就做好了被骂的准备"， 大厂姿态啊，

**Comment by chareice** [comment]
春夏之交的那天也可以加点彩蛋的。

**Comment by shuiRong** [comment]
> 作大死 想害阿里吗 ？？？？

屁大点事儿，还“想害死阿里吗？”2333
