### ISSUE TITLE
<Cascader> with props.popupVisible can not trigger onChange Event in Windows 

### ISSUE THREAD

**Issue by Terryand** [ant-design/ant-design#13834]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.5

### Environment
windows7/windows10  Chrome67 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2p9k4z84yp)

### Steps to reproduce

      <span
        className={styles['multi-cascader']}
        onFocus={this.onFocus}
        onBlur={this.onBlur}
      >
        <Select
          value={selectValue}
          mode="tags"
          style={{ width: '100%', ...{ style } }}
          dropdownStyle={{ display: 'none' }}
          placeholder={placeholder || '请选择'}
          tokenSeparators={[',']}
          onDeselect={this.onDeselect}
        >
          {selectChildren}
        </Select>
        <Cascader
          changeOnSelect={changeOnSelect}
          expandTrigger="hover"
          className={styles['spe-cascader']}
          popupVisible={popupVisible}
          options={options}
          onChange={this.handleChange}
        />
      </span>

### What is expected?
I want to create a  multiple Cascader by group <Select> and <Cascader>.
When the group area is focused, the <Cascader> should show popup. Then click the Cascader Option, onChange Event will be happen and set new value for <Select>.
It is all OK in MacOS.
But in Windows, when I click <Cascader> Option, onChange Event can not be  triggered.

### What is actually happening?
In Windows, when I click Cascader Option, onChange Event can not be  triggered

---
This bug is only  reappeared in Windows

**Comment by afc163** [comment]
You codesandbox is too complicated, can you make it minimal?
