### ISSUE TITLE
有什么不发版本关闭圣诞彩蛋的方法，急急急急！！！

### ISSUE THREAD

**Issue by lixiaolihua** [ant-design/ant-design#13832]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
任何

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
有什么不发版本关闭圣诞彩蛋的方法，急急急急！！！

### What is expected?
有什么不发版本关闭圣诞彩蛋的方法，急急急急！！！

### What is actually happening?
有什么不发版本关闭圣诞彩蛋的方法，急急急急！！！

**Comment by wxygeek** [comment]
没有办法。

**Comment by baikeh** [comment]
等明天就好了 😀

**Comment by xiaohuoni** [comment]
.ant-btn.ant-btn-primary.christmas::before {
display: none!important;
}
o=h.title
![](https://user-images.githubusercontent.com/9709396/50410118-e3379080-0831-11e9-9c5f-214dbcdbe7da.png)

**Comment by jaunemmechine** [comment]
.ant-btn.ant-btn-primary.christmas:before {
  display: none!important;
}

**Comment by xiaohuoni** [comment]
已经回滚了，更新版本能修复

**Comment by wonderFF** [comment]
const isChristmas = now.getMonth() === 11 && now.getDate() === 25;

**Comment by shenguotao2015** [comment]
ant pro --- global.less 增加：
```css
.christmas.ant-btn-primary:before{
  background:none;
}
```

**Comment by yaoshanliang** [comment]
这个是用的cdn的样式才会？
