### ISSUE TITLE
Antd既然标榜自己是企业级后台开发，就不应该弄一些失控的彩蛋，你们这是在玩弄开发者对你们的信任

### ISSUE THREAD

**Issue by LaiHuanMin** [ant-design/ant-design#13830]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对不起可能接下来的话不太好听，我也受这次影响很深，毕竟那么信任Antd，也很感谢Antd做出那么好的组件，但是希望你们可以认真看看这次彩蛋是否恰当。    
码农们本来可以不被扣钱扣年终奖扣绩效，只是因为在圣诞节的清晨，他们辛辛苦苦做出来的工作成绩被Antd莫名其妙的彩蛋一下子摧毁了！     
马云可以很乐意接受这些彩蛋，但是其他公司里的老总尤其是事业单位的那些领导们，你觉得他们喜欢这个圣诞节吗？更何况现在一带一路倡议，外派到伊斯兰国家的做软件系统那么多，你知不知道现在不仅是有扣钱危机，还有去见真主的危机啊！！！！！       
如果标榜自己是企业级开发，那么就不要做一些个人项目随意的事情，能在暗地里(不在changelog说明)随意操控开发者的项目UI，你们可以算是前端史上第一家了！     
企业级开发是什么，可以看下Java，这门语言不管是从GUI还是语言层面设计，都不会搞一些令人过于幽默的设计，会很严肃专注于业务。开源出来需要有责任心，我真的觉得你们这是在玩弄开发者的信任。   
弄这样的彩蛋，为什么不重新设计一套圣诞主题(不管从背景色还是其他组件都富有圣诞风格，你只弄个Button加个title HOHOHO很难让人想到是圣诞节)呢？然后让大家可以配置立刻生效，有选择的余地，这样不好吗？

### What does the proposed API look like?
无

**Comment by sirzxj** [comment]
没有春节，差评❌

**Comment by kiinlam** [comment]
> 没有春节，差评❌

你打算在大年初一凌晨3点钟起来改代码吗？

**Comment by hold-baby** [comment]
这种彩蛋我认为还是出现在命令行或者console中比较合适

**Comment by milenstack** [comment]
已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

**Comment by wulunyi** [comment]
吓尿了，以后不敢用了

**Comment by qmsu** [comment]
圣诞彩蛋是什么👻？这样搞，以后谁还敢用

**Comment by reatang** [comment]
说明阿里对企业级的东西还是可以完全掌握的，甚至可以全网入侵

**Comment by wangkuo1993** [comment]
不知道发生了什么 过来看热闹的

**Comment by zhan2016** [comment]
代码里面有只无形之手

**Comment by Tangwei91** [comment]
牛逼啊哈哈哈哈

**Comment by lixiaolihua** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

同情

**Comment by Viin-zx** [comment]
> 说明阿里对企业级的东西还是可以完全掌握的，甚至可以全网入侵

没有，在很早的版本就在代码里面预留了。

**Comment by medmin** [comment]
阿里的人也不出来解释一下吗？这次事故，负责人不离职吗？

**Comment by wsdqr001** [comment]
这个“彩蛋”真的是让我无语。请问开发组有想过用户的感受吗？作为一个有影响力的企业级开源应用，真的可以随便玩吗？

**Comment by jin5354** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

同情兄弟

**Comment by iceberg211** [comment]
这个因人而异啊，我们有一个收集需求的项目叫许愿树，这次彩蛋用户和领导都很喜欢，我只是觉得阿里需要做一下提示，不然过分惊喜

**Comment by wonderFF** [comment]
没有 我看了一下 就是 new Date 是 圣诞节的时候 加一个 类名,  在 global 中把  christmas 的 类名 覆盖掉 可以干掉 彩蛋

**Comment by Yangzhedi** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

package.json记得写死版本，别向上兼容就行了

**Comment by Viin-zx** [comment]
> 没有 我看了一下 就是 new Date 是 圣诞节的时候 加一个 类名, 在 global 中把 christmas 的 类名 覆盖掉 可以干掉 彩蛋

button 的 title Ho Ho Ho 不好去掉。

**Comment by Yangzhedi** [comment]
> 阿里的人也不出来解释一下吗？这次事故，负责人不离职吗？

这是彩蛋，不是事故

**Comment by milenstack** [comment]
> > 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释
> 
> package.json记得写死版本，别向上兼容就行了

已经不关我事了，现在已经在家里打酱油了

**Comment by reatang** [comment]
> > 说明阿里对企业级的东西还是可以完全掌握的，甚至可以全网入侵
> 
> 没有，在很早的版本就在代码里面预留了。

那就是时间触发的吧。。。可怕，要是植入了什么代码，当场都不知道的。。。

**Comment by Jlanglang** [comment]
我也很奇怪,上班一看,发现多了朵云,我还以为是老大昨天提上去的,原来是antd自己改的

**Comment by merrier** [comment]
953075999@qq.com，公司招人，因为彩蛋离职的小伙伴欢迎联系

**Comment by maodouchen** [comment]
这波操作可以说是很傻比了

**Comment by Viin-zx** [comment]
> > > 说明阿里对企业级的东西还是可以完全掌握的，甚至可以全网入侵
> > 
> > 
> > 没有，在很早的版本就在代码里面预留了。
> 
> 那就是时间触发的吧。。。可怕，要是植入了什么代码，当场都不知道的。。。

嗯，时间触发，3.9.2以前可用。

**Comment by zoudongyang** [comment]
前来围观

**Comment by xianxuLi** [comment]
楼上找人的同志你是认真的吗？

**Comment by afc163** [comment]
Duplicate of #13098

**Comment by bowencool** [comment]
明明一行样式就能解决的，非要等死

**Comment by zsychy** [comment]
> [953075999@qq.com](mailto:953075999@qq.com)，公司招人，因为彩蛋离职的小伙伴欢迎联系

极度优秀~

**Comment by wonderFF** [comment]
> > 没有 我看了一下 就是 new Date 是 圣诞节的时候 加一个 类名, 在 global 中把 christmas 的 类名 覆盖掉 可以干掉 彩蛋
> 
> button 的 title Ho Ho Ho 不好去掉。

emmm 写一段脏的代码干掉吧

**Comment by Nick-QI** [comment]
不来个解释么?官方

**Comment by maodouchen** [comment]
竟然被close掉了  ？

**Comment by lyhapple** [comment]
原来阿里的里面也有一些猪队友

**Comment by Kevinl7** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

我靠， 这么悲催， 马政委要加强思想教育了/

**Comment by zoudongyang** [comment]
这怎么想的

**Comment by iceberg211** [comment]
Hello，大家好，我是一个在伊朗工作的中国前端，因为使用antd进行平台开发，在伊朗一个官方网站上显示出来圣诞节，目前已经被抓，请大家救救我。

**Comment by shengbeiniao** [comment]
圣诞夜惊魂

**Comment by LaiHuanMin** [comment]
@iceberg211 同志，祝你平安

**Comment by qiantaobao** [comment]
还好我没用antd开发

**Comment by code-artisan** [comment]
This is crazy.

**Comment by hgfvhy** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

同情兄嘚

**Comment by youyeke** [comment]
> 明明一行样式就能解决的，非要等死

不是什么时候都可以给你在已部署的产品里面加一行什么东西的

**Comment by LaiHuanMin** [comment]
@bowencool 不是等不等死的问题，事故已经产生，你改样式就当这事没发生了？可笑

**Comment by Kuro233333** [comment]
这波操作玩死自己

**Comment by zjz1993** [comment]
按这套路，清明节来个墓碑？

**Comment by AllenBird** [comment]
自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～

**Comment by luliangce** [comment]
千不该万不该,圣诞节是个宗教节日,如果是元旦,可能真的没这么严重

**Comment by vigrodong** [comment]
> 按这套路，清明节来个墓碑？

秀

**Comment by luliangce** [comment]
> 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～

这怎么验证?if month==11 and date==25的代码你怎么验证?

**Comment by shery** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

这个可以找 @蚂蚁金服体验技术部 申请赔偿吗？

**Comment by anykno** [comment]
> 没有春节，差评❌

建议提pr，要一起吗，每天都有新彩蛋

**Comment by lvao813** [comment]
有彩蛋也是个不错的想法，但为什么不给开发者一个提示，让开发者自己去选呢？

**Comment by elysianaries** [comment]
> > 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～
> 
> 这怎么验证?if month==11 and date==25的代码你怎么验证?

人家是大佬 代码一行一行看的，工作也仔细认真，一丝不苟

**Comment by Phinome** [comment]
> 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～

Change Log 里没写，你咋看出来的？

**Comment by wSLecHayfIeNdock** [comment]
![qq 20181225110140](https://user-images.githubusercontent.com/16831715/50410538-8b4e5900-0834-11e9-97b8-f9f3af08b016.jpg)

**Comment by webgzh907247189** [comment]
> 按这套路，清明节来个墓碑？

秀儿，是你吗？

**Comment by hgfvhy** [comment]
> 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～
大佬大佬

**Comment by reatang** [comment]
> > 没有春节，差评❌
> 
> 建议提pr，要一起吗，每天都有新彩蛋

很新颖，antd-eggs 版主题，包含大量彩蛋。

**Comment by MrJoker1994** [comment]
> 按这套路，清明节来个墓碑？
额…… 光棍节可不可以来个女朋友

**Comment by vigrodong** [comment]
> > 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～
> > 大佬大佬

他那是云程序员

**Comment by hgfvhy** [comment]
> 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～

大佬大佬    ， 您慢慢一行一行看

**Comment by youyeke** [comment]
> 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～

@AllenBird 你厉害，坚持看每个 commit 的源码了？

**Comment by wangjianhui2464** [comment]
> > 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释
> 
> package.json记得写死版本，别向上兼容就行了

去年就写了。谁知道呢。

**Comment by Jlanglang** [comment]
不给回应,关了就完事?

**Comment by wangjianhui2464** [comment]
![image](https://user-images.githubusercontent.com/6160798/50410575-e54f1e80-0834-11e9-8799-1851f58c6325.png)
在这里，用到的先改了吧。

**Comment by cheerful-li** [comment]
9月10号加的， 没有写到changelog里面

**Comment by wangjianhui2464** [comment]
> 9月10号加的， 没有写到changelog里面

去年圣诞节 commit 的代码。

**Comment by maodouchen** [comment]
> 9月10号加的， 没有写到changelog里面

所以叫彩蛋  哈哈哈哈

**Comment by fanyongfeng** [comment]
这篇帖下发内推广告可以么

**Comment by welldone-jason** [comment]
火前留名，某条内推，442081028@qq.com，欢迎各前端大佬（北京、深圳）

**Comment by lucasleelz** [comment]
咦没有锁定了啊，吃瓜群众继续看下去。

**Comment by zsychy** [comment]
是不是被关了

**Comment by reatang** [comment]
> ![image](https://user-images.githubusercontent.com/6160798/50410575-e54f1e80-0834-11e9-8799-1851f58c6325.png)
> 在这里，用到的先改了吧。

老司机解决问题的方式就是厉害👍

**Comment by leeight** [comment]
字节跳动全年招聘（北京/上海/深圳/厦门）均可，邮箱：leeight@bytedance.com

**Comment by zsychy** [comment]
> 按这套路，清明节来个墓碑？

极度优秀

**Comment by bWhirring** [comment]
> 明明一行样式就能解决的，非要等死

你根本没明白事情的本质啊

**Comment by Jiang-Xuan** [comment]
这种失控的事情的发生, 就是在失去开发者的信任.

**Comment by hlbj105** [comment]
![image](https://user-images.githubusercontent.com/16408650/50410760-ffd5c780-0835-11e9-9638-112aff31525d.png)

**Comment by wonderFF** [comment]
辛辛苦苦一整年, 年初3.25跑不了

**Comment by xiangxingze** [comment]
你们的数据是不是也被采集的差不多了呢？

**Comment by m1911star** [comment]
> 你们的数据是不是也被采集的差不多了呢？

不知道antd有没有，bizcharts写一段就得关track，哈哈哈

**Comment by weishijun14** [comment]
要理解“道德绑架”，我们首先需要理解对一个行为的道德评判。通常，我们可能认为一个行为只有“道德”和“不道德”两种可能。但实际上，道德评判比这个要复杂得多。一个行为可以是：1. 义务行为（obligation)：道德上必须要执行的行为。你不做你就不道德。如：遵守交通规则。2. 额外行为（supererogation）：道德上是好的，但是你不需要做的行为。做了更好，不做也没错。如：捐款。3. 允许行为（permissible action）：道德上可好可坏，也可以是无关道德的。你可以做。如：不吃香菜。4. 禁止行为（impermissible/forbidden action）：道德上不好，且不被允许的行为。你做了你就是不道德的。如：插队。这样进行区分后，“道德绑架”就很容易分辨了。我们通常所说的“道德绑架”就是把“额外行为“当成了“义务行为”。

作者：王昱洲
链接：https://www.zhihu.com/question/21831223/answer/398920183
来源：知乎
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。

**Comment by zjz1993** [comment]
![image](https://user-images.githubusercontent.com/17746534/50410826-6bb83000-0836-11e9-9720-d81ecafdca24.png)
这一波密集的操作。。。辛苦了

**Comment by AllenBird** [comment]
> > 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～
> 
> Change Log 里没写，你咋看出来的？

![image](https://user-images.githubusercontent.com/8787182/50410837-796db580-0836-11e9-8502-58125660bcd2.png)

![image](https://user-images.githubusercontent.com/8787182/50410842-84c0e100-0836-11e9-9bf9-96803eff8b75.png)

**Comment by redbattle** [comment]
> 没有春节，差评❌

春节还没到，不要急 [doge]

**Comment by pengyinghao** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

这波操作不错。 你肯定能找到更好的下家

**Comment by heyunjiang** [comment]
还好我没有用 primary type ，用了的都是 antd 2.x 版本的

**Comment by zhoutingchuan** [comment]
彩蛋应该有单独的触发方式才好吧，这种更像一个特性

**Comment by MittWillson** [comment]
面向客户的产品才叫彩蛋，面向开发者的已经变成BUG了

**Comment by ByteChen** [comment]
咩~~~~咩~~me~~Merry Christmas?

**Comment by abcsnowwolf** [comment]
活生生把feature变成了bug。。。

**Comment by AibiTi** [comment]
![image](https://user-images.githubusercontent.com/40224479/50411198-23e6d800-0839-11e9-9194-8f50b3750452.png)


搞出这事谁负责？

**Comment by AllenBird** [comment]
> > > 自己编译出来的版本不验证？开源项目更新不关注就直接用最新版本？没有理由埋怨谁～
> > 
> > 
> > 这怎么验证?if month==11 and date==25的代码你怎么验证?
> 
> 人家是大佬 代码一行一行看的，工作也仔细认真，一丝不苟

做为部门的全端架构，没出问题～

**Comment by Yangzhedi** [comment]
> ![image](https://user-images.githubusercontent.com/40224479/50411198-23e6d800-0839-11e9-9194-8f50b3750452.png)
> 
> 搞出这事谁负责？

一看就是自己打出来的 微信的自己对话框，  求你被抓

**Comment by AibiTi** [comment]
@Yangzhedi 已经被抓了，现在在吃牢饭中。。。

**Comment by victorliuboom** [comment]
吃瓜吃瓜

**Comment by lizhiyao** [comment]
作为一名软件研发工程师，当遇到问题时，最应该想到的难道不应该是 如何解决当下的问题 吗？

一个 去掉圣诞彩蛋的 MR 比这个 发泄情绪 的 issue 更有意义。

**Comment by AllenBird** [comment]
生态要好～不要让人心寒～

**Comment by OBKoro1** [comment]
除夕的时候，按钮上面可以加一些鞭炮，这样子比较喜庆。 让外国人也一起欢欢喜喜过大年

**Comment by OBKoro1** [comment]
> 作为一名软件研发工程师，当遇到问题时，最应该想到的难道不应该是 如何解决当下的问题 吗？
> 
> 一个 去掉圣诞彩蛋的 MR 比这个 发泄情绪 的 issue 更有意义。

问题解决是简单的，问题导致的恶劣影响及后果，应该由谁来承担？

**Comment by yuanqingH** [comment]
> 除夕的时候，按钮上面可以加一些鞭炮，这样子比较喜庆。 让外国人也一起欢欢喜喜过大年

会不会农历不太好判断 所以没加

**Comment by CJY0208** [comment]
> 作为一名软件研发工程师，当遇到问题时，最应该想到的难道不应该是 如何解决当下的问题 吗？
> 
> 一个 去掉圣诞彩蛋的 MR 比这个 发泄情绪 的 issue 更有意义。

损失已经发生，年终没了换谁都不好控制情绪，个人感觉楼主已经很克制了，提出的建议也很中肯

**Comment by coolicer** [comment]
有种自己开发，用什么开源

**Comment by youyeke** [comment]
> 有种自己开发，用什么开源

@coolicer 请问你对开源有什么误解吗？

**Comment by heartOfblack** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

今天一来到测试问我是不是改了代码。我说没有啊。看了一下刚开始觉得没什么，影响不大，但是后面发现title被改成了ho ho ho我就有点。。。都是可怜人

**Comment by AibiTi** [comment]
还原一下失踪的现场。

![68747470733a2f2f692e6962622e636f2f524e4a644259352f3030312e676966 1](https://user-images.githubusercontent.com/40224479/50411402-b20f8e00-083a-11e9-9579-0508d5ed79e0.gif)

**Comment by MittWillson** [comment]
谁都不希望自己写的代码在发生在预料之外，特别是作为企业级底子的项目，无论是彩蛋还是幽默，你出现在console里大家都可以理解，出现在产品里导致产品变成预期之外的东西就是很不负责的行为了，特别是内网开发的产品，客户还不得追着问你是不是在代码里下毒了（此处应该配图

**Comment by Dylan-TW** [comment]
最近才开始使用AntDesign，整体感觉有一些还是不够成熟，越使用，越感觉心累。还好我们的Mobile不受此次影响。。真是人生何处不是惊喜呢。

**Comment by wentatte** [comment]
> > 阿里的人也不出来解释一下吗？这次事故，负责人不离职吗？
> 
> 这是彩蛋，不是事故

对用户来说，这“彩蛋”就是失控，就是事故

**Comment by valaxy** [comment]
看热闹不嫌事大，阿里的人不妨出来说说对这此事的价值观

**Comment by Dylan-TW** [comment]
> 谁都不希望自己写的代码在发生在预料之外，特别是作为企业级底子的项目，无论是彩蛋还是幽默，你出现在console里大家都可以理解，出现在产品里导致产品变成预期之外的东西就是很不负责的行为了，特别是内网开发的产品，客户还不得追着问你是不是在代码里下毒了（此处应该配图

![image](https://user-images.githubusercontent.com/42960490/50411502-6b6e6380-083b-11e9-83a9-de419808376a.png)

**Comment by lvao813** [comment]
为什么会这样，ant的内部是不是有内奸来搞破坏的，还是说你们的版本控制并不严格，这种代码竟然能够合并到主分支里？

**Comment by xiangxingze** [comment]
> 有种自己开发，用什么开源

开源出来不就是给别人用的吗？

**Comment by lvao813** [comment]
> 有种自己开发，用什么开源

你这种是专门来煽风点火的吧？

**Comment by tabris17** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

太惨了，你准备去阿里总部讨说法么？我支援你一桶汽油

**Comment by lxchuan12** [comment]
Ant Design是优秀的框架之一。虽然很早前就埋下的彩蛋，但这次明显是失控的。直接面向的是用户，开发解决发版需要时间。
而且圣诞节不是全世界的节日，这种彩蛋是极其不妥的。

**Comment by Cheonsoon** [comment]
> 这个“彩蛋”真的是让我无语。请问开发组有想过用户的感受吗？作为一个有影响力的企业级开源应用，真的可以随便玩吗？

你们还真当用了企业级框架就享有企业级服务了？那redhat干啥的？既然有开源的centos了，那redhat岂不是可以去死了？屁话。。

**Comment by amorist** [comment]
> > 这个“彩蛋”真的是让我无语。请问开发组有想过用户的感受吗？作为一个有影响力的企业级开源应用，真的可以随便玩吗？
> 
> 你们还真当用了企业级框架就享有企业级服务了？那redhat干啥的？既然有开源的centos了，那redhat岂不是可以去死了？屁话。。

高级黑

**Comment by CruxCv** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

上香

**Comment by binjie09** [comment]
还好我们是fork了antd和所有rc-component然后自己开发维护的。。

**Comment by mohanyu** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

妙啊！！！

**Comment by yangzhenwang** [comment]
免费和开源给你们用 怎么还就是人家的错啦

**Comment by Qquanwei** [comment]
> 作为一名软件研发工程师，当遇到问题时，最应该想到的难道不应该是 如何解决当下的问题 吗？
> 
> 一个 去掉圣诞彩蛋的 MR 比这个 发泄情绪 的 issue 更有意义。

此时大家都在落井下石。贬低一个高高在上的东西能让这些人获得巨大的满足感。

不仅是antd，任何一个开源程序包都有这种风险，而antd只是犯了这个愚蠢的错误的第一个企业级框架。

**Comment by shiyafeng** [comment]
有种自己开发

**Comment by ablikim915** [comment]
春节的时候可以加下鞭炮我觉得ok

**Comment by mohanyu** [comment]
> 免费和开源给你们用 怎么还就是人家的错啦

免费的水给我喝，我感谢，但是不能在水里下毒啊

**Comment by youyeke** [comment]
> 免费和开源给你们用 怎么还就是人家的错啦

体量大了，很多时候就没办法任性了

**Comment by ChasLui** [comment]
> > 作为一名软件研发工程师，当遇到问题时，最应该想到的难道不应该是 如何解决当下的问题 吗？
> > 一个 去掉圣诞彩蛋的 MR 比这个 发泄情绪 的 issue 更有意义。
> 
> 此时大家都在落井下石。贬低一个高高在上的东西能让这些人获得巨大的满足感。
> 
> 不仅是antd，任何一个开源程序包都有这种风险，而antd只是犯了这个愚蠢的错误的第一个企业级框架。

这次事件不会不造成开源运动的重大挫伤

**Comment by bluedazzle** [comment]
字节跳动招人，zhangjianqi@bytedance.com，欢迎彩蛋离职的小伙伴加入

**Comment by zackshen** [comment]
论锁定版本的重要性

**Comment by tabris17** [comment]
> 字节跳动招人，[zhangjianqi@bytedance.com](mailto:zhangjianqi@bytedance.com)，欢迎彩蛋离职的小伙伴加入

难道是你？

**Comment by brant9527** [comment]
没见到真主就还好……

**Comment by AcerFeng** [comment]
> 已经被迫主动离职了，这锅背的很冤，怎么解释都没有用，公司是事业单位项目，国家刚发文禁止洋节，就搞出这出。老板也很着急的给事业单位的领导解释

这可能就是古人所说的“毁于一蛋”吧

**Comment by MillionChen** [comment]
早上到和客户解释到现在懵了。。。。

**Comment by Viin-zx** [comment]
> 明明一行样式就能解决的，非要等死

你一样样式给去掉title看看。

**Comment by ZZhaoTireless** [comment]
> 字节跳动全年招聘（北京/上海/深圳/厦门）均可，邮箱：[leeight@bytedance.com](mailto:leeight@bytedance.com)

你们看看字节跳动的员工都是什么心态在考虑以上这条招聘好了.

https://github.com/ant-design/ant-design/issues/13848#issuecomment-449798234

**Comment by dbFlower** [comment]
> > 字节跳动全年招聘（北京/上海/深圳/厦门）均可，邮箱：[leeight@bytedance.com](mailto:leeight@bytedance.com)
> 
> 你们看看字节跳动的员工都是什么心态在考虑以上这条招聘好了.
> 
> [#13848 (comment)](https://github.com/ant-design/ant-design/issues/13848#issuecomment-449798234)

啧啧啧

**Comment by xiaohuangmao** [comment]
> 
> 
> [953075999@qq.com](mailto:953075999@qq.com)，公司招人，因为彩蛋离职的小伙伴欢迎联系

这波广告我给满分

**Comment by piaca** [comment]
建议把有彩蛋版本的版本号定为 3.25

**Comment by skyIsland** [comment]
问题来了，春节该弄个什么彩蛋

**Comment by xiezhenye** [comment]
完全没想清楚自己做的是什么东西就玩彩蛋。这是极其不负责任的行为。楼上洗地的那几位，祝你们以后去面试的时候不会碰到被坑过的公司

**Comment by alexinea** [comment]
还好楼主公司不是给伊斯兰教国家开发系统，否则就看不到这个帖子了。

**Comment by flashing** [comment]
强势围观，虽然是各种惨案，不知道为什么觉得特别欢乐！btw:我也算是受害者，好在还是在开发阶段，就是莫名其妙了一下。

**Comment by GuoJie1990** [comment]
还以为是服务器被入侵了， 担惊受怕， 这个 Ho Ho Ho 太魔性了

**Comment by ColeHou** [comment]
> > 字节跳动全年招聘（北京/上海/深圳/厦门）均可，邮箱：[leeight@bytedance.com](mailto:leeight@bytedance.com)
> 
> 你们看看字节跳动的员工都是什么心态在考虑以上这条招聘好了.
> 
> [#13848 (comment)](https://github.com/ant-design/ant-design/issues/13848#issuecomment-449798234)
> 
> 防删留图:
> 
> ![tim 20181224233346](https://user-images.githubusercontent.com/15257767/50412361-970a3300-07d4-11e9-80a3-ef66c76c8bf9.png)]
> 
> ![tim 20181224233350](https://user-images.githubusercontent.com/15257767/50412363-9bcee700-07d4-11e9-847d-31f218620f54.png)

666 你anti我张总啊

**Comment by hjkl950217** [comment]
> > > 作为一名软件研发工程师，当遇到问题时，最应该想到的难道不应该是 如何解决当下的问题 吗？
> > > 一个 去掉圣诞彩蛋的 MR 比这个 发泄情绪 的 issue 更有意义。
> > 
> > 
> > 此时大家都在落井下石。贬低一个高高在上的东西能让这些人获得巨大的满足感。
> > 不仅是antd，任何一个开源程序包都有这种风险，而antd只是犯了这个愚蠢的错误的第一个企业级框架。
> 
> 这次事件会不会造成开源运动的重大挫伤

对此表示担心

**Comment by hennesseywu** [comment]
开发者没想清楚他的开源项目会被什么样的场景使用，比如：国企的内部你给我来个圣诞节的是什么鬼，所以内部的系统还是自己写框架比较靠谱

**Comment by wujian6510** [comment]
第一天：测试提了一个BUG，按钮被狗啃了一点，请修复
开发：好的我看看
第二天：
开发：修好了，再测试一把
测试：哇！好了，真牛逼

**Comment by summerzo** [comment]
[![Fc0iC9.md.jpg](https://s1.ax1x.com/2018/12/25/Fc0iC9.md.jpg)](https://imgchr.com/i/Fc0iC9)

**Comment by leochan2017** [comment]
前排围观

**Comment by jacobking** [comment]
因为彩蛋被迫主动离职==不经测试直接上线的开发者.还有帮他找工作的?哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by MittWillson** [comment]
> 因为彩蛋被迫主动离职的伙伴，发消息给我...我帮你们找个新工作的机会

测试？ 能用测试解决的BUG能叫彩蛋？

**Comment by orhankutlu** [comment]
Are you guys serious? We run a production website with and design. It can be fun but not for all of the business!

**Comment by HuiKin** [comment]
世界上有两种开源社区，中国的开源社区和其他开源社区

**Comment by mofengmo** [comment]
跟随济南大学宇哥哥来的，好评！

**Comment by jxintang** [comment]
398727101@qq.com 公司招人，因为彩蛋离职的小伙伴欢迎联系

**Comment by unsix** [comment]
随着节日而变化的UI,感觉蛮前沿的

**Comment by donizyo** [comment]
极端组织会不会因此发动圣战啊？就像2012年，武装分子袭击美国驻利比亚班加西领事馆一样？

**Comment by blindpirate** [comment]
强烈要求七一放党旗！！！！！！！！

**Comment by arslan2012** [comment]
北京比赛帮全年招聘 java, js 均可，邮箱：hr@bisaibang.cn

**Comment by MittWillson** [comment]
后面对于此问题而非彩蛋这个点做评论和看法的，麻烦转站到其他论坛讨论，issue 已经歪的不成样子了，还有蹭热度打广告的就跟上面有人帖的那个图一样，不是你在这个贴下发招聘信息就能证明你们公司不会有这个问题

**Comment by andypinet** [comment]
没有春节 不尊重国家节日

**Comment by liujunning** [comment]
> 因为彩蛋被迫主动离职的伙伴，发消息给我...我帮你们找个新工作的机会

什么机会？

**Comment by amorist** [comment]
埋个春节 也没这么多骂声

**Comment by YangRobin** [comment]
> > > > 说明阿里对企业级的东西还是可以完全掌握的，甚至可以全网入侵
> > > 
> > > 
> > > 没有，在很早的版本就在代码里面预留了。
> > 
> > 
> > 那就是时间触发的吧。。。可怕，要是植入了什么代码，当场都不知道的。。。
> 
> 嗯，时间触发，3.9.2以前可用。

``
