### ISSUE TITLE
严重谴责阿里巴巴集团此次不负责任的入侵行为

### ISSUE THREAD

**Issue by ect0** [ant-design/ant-design#13841]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
macOS

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
打开即可看见

### What is expected?
阿里巴巴集团道歉，相关负责人离职。

### What is actually happening?
下到基层小兵，上到司长，全部都要检讨

**Comment by chenshuai2144** [comment]
duplicate of https://github.com/ant-design/ant-design/issues/13823

**Comment by hanchn** [comment]
严重谴责，已经影响到几十个项目了

**Comment by Fireflyi** [comment]
基层小兵只是执行，应该找决策的人的责任，别胡乱甩锅给基层

**Comment by mazeyqian** [comment]
产品的锅？

**Comment by yangbean4** [comment]
发生了什么？🤔

**Comment by chenxinwahaha** [comment]
引用antd会请求网络资源  下载下来替换成本地资源  就不会有问题了  我们公司的项目没有受到影响

**Comment by yaoshanliang** [comment]
用的cdn上的样式？

**Comment by yaoshanliang** [comment]
npm之前下载下来的应该不会吧

**Comment by Xaber20110202** [comment]
> npm之前下载下来的应该不会吧

九月份埋下的彩蛋好像

**Comment by chenxinwahaha** [comment]
package.json加版本锁

**Comment by Naville** [comment]
哦，我不知道。我建议你们让阿里集团顺便完全退还你们用这个项目所支付的全部款项，也就是0.00元

**Comment by Naville** [comment]
或者，你知道的，自己维护一份类似的框架绝对不会出问题。

哦等一下，你做不到

**Comment by limaofeng** [comment]
> 哦，我不知道。我建议你们让阿里集团顺便完全退还你们用这个项目所支付的全部款项，也就是0.00元

有时候支付的不一定是金钱，注意力也是。只要有人关注这个项目，就有人从中获益了。

**Comment by helloJincheng** [comment]
开源项目，谴责无效

**Comment by ShineLuo142** [comment]
只有我觉得还挺好看的嘛？？？

**Comment by Yangzhedi** [comment]
3.11.6 是已经完成修复的版本了

**Comment by 417606028** [comment]
> > 哦，我不知道。我建议你们让阿里集团顺便完全退还你们用这个项目所支付的全部款项，也就是0.00元
> 
> 有时候支付的不一定是金钱，注意力也是。只要有人关注这个项目，就有人从中获益了。

那么你为这个项目付出了什么呢？

**Comment by JoeGe** [comment]
What is expected?
阿里巴巴集团道歉，相关负责人离职。

What is actually happening?
下到基层小兵，上到司长，全部都要检讨
-----------------------------------
请说一下你所受的实际影响。

**Comment by DerekGrant** [comment]
你不花一分钱用人家的东西，不自己检查，出了问题要人家负责，你没责任么？自己看不懂代码？！这个叫入侵么？有什么恶意？要避免这个问题就只能自己写？是你不会还是懒？
