### ISSUE TITLE
请在每年的6月4日显示彩蛋

### ISSUE THREAD

**Issue by 64646464** [ant-design/ant-design#13845]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
纪念64

### What does the proposed API look like?
按钮上显示坦克

**Comment by baqihg** [comment]
枪毙名单+1，明年正好30周年。

**Comment by mumu1993** [comment]
章口就莱

**Comment by fanyingmao** [comment]
这是来蹭热度吗？

**Comment by Yizuchao** [comment]
作死

**Comment by xd19831203** [comment]
要死了……

**Comment by luoyuanhang** [comment]
要死了……

**Comment by by-chimon** [comment]
年底枪毙

**Comment by couldhll** [comment]
舒克舒克舒克

**Comment by xmflswood** [comment]
贝塔
