### ISSUE TITLE
Plz add the Spring Festival egg...

### ISSUE THREAD

**Issue by Yangzhedi** [ant-design/ant-design#13843]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
支持这次的蚂蚁彩蛋，虽然反响不是特别的好。
洋节不过，但是春节还是要过的。
希望加上春节的彩蛋，在changelog中体现即可。

### What does the proposed API look like?
如果能可以在theme中配制就更好了，默认关闭，关注antd的人自然会开。

**Comment by NangeGao** [comment]
过年好！

**Comment by jack-Lo** [comment]
春节让整个主题变红色

**Comment by vitrum** [comment]
少年其实你是想着过年加班修复拿三倍工资吧？

**Comment by hanchn** [comment]
你觉得让上线产品自动改UI？？？合理吗？？？

**Comment by shengbox** [comment]
清明节是不是也加一个

**Comment by a838189349** [comment]
nooooooooooo

**Comment by fernandoxu** [comment]
大哥大嫂过年好

**Comment by Yangzhedi** [comment]
> 少年其实你是想着过年加班修复拿三倍工资吧？

我们不是政府网站，对彩蛋很欢迎

**Comment by sinri** [comment]
Ant could call a public api to get visitor location, and then fetch what festival should be accepted, then, ... emmm .... Make Egg Boom!

**Comment by Yangzhedi** [comment]
> 你觉得让上线产品自动改UI？？？合理吗？？？

判断时间触发彩蛋

**Comment by hanchn** [comment]
> > 少年其实你是想着过年加班修复拿三倍工资吧？
> 
> 我们不是政府网站，对彩蛋很欢迎

要是埋个挖矿脚本也欢迎？？？

**Comment by licao404** [comment]
> > 少年其实你是想着过年加班修复拿三倍工资吧？
> 
> 我们不是政府网站，对彩蛋很欢迎

坑了多少政府项目

**Comment by percyjie** [comment]
说到彩蛋就想到明年年初..

**Comment by AibiTi** [comment]
这是要新年大半夜起来改代码的节奏？

**Comment by ph4day** [comment]
希望春节的时候两侧漂出2副对联

**Comment by jiadi0801** [comment]
这种非预期的行为是要坑多少人

**Comment by Bigpawn** [comment]
主要是来的太突然，一脸的懵逼

**Comment by Yangzhedi** [comment]
> > > 少年其实你是想着过年加班修复拿三倍工资吧？
> > 
> > 
> > 我们不是政府网站，对彩蛋很欢迎
> 
> 要是埋个挖矿脚本也欢迎？？？

event-stream给您吓到了

**Comment by besidewind** [comment]
其实设置一个可以开关所有彩蛋的配置项就好了，这么突然改一下真的不太好

**Comment by cswanghan** [comment]
彩蛋的英文不是egg，是eastern egg.

![image](https://user-images.githubusercontent.com/699970/50411443-00249180-083b-11e9-8ee0-6fafe4026ec3.png)

**Comment by 1993yihuan** [comment]
一串中国红的鞭炮挂在按钮上方，比狗啃的好看得多

**Comment by KitYeungDev** [comment]
去你的彩蛋，已取关，再也不可能用阿里的开源了

**Comment by babyisun** [comment]
Today‘s egg is unprofessional! You need to apologize.Don't be too arrogant.

**Comment by wenshin** [comment]
因为缺人手，还没有升级到有彩蛋的版本，有意向的快来，wenshin2011@gmail.com 字节跳动北京内推 ：）

**Comment by lockyang** [comment]
这是一个开源库。

**Comment by pangjunpeng** [comment]
两开花就完事了

**Comment by DarknessChaser** [comment]
这个是个好主意，其实可以搞个全球节日庆祝功能，给开关控制一下就好了。

**Comment by hanchn** [comment]
> 这个是个好主意，其实可以搞个全球节日庆祝功能，给开关控制一下就好了。

你这是把UI当产品做了吧

**Comment by ky0nch3ng** [comment]
![](https://chinadigitaltimes.net/chinese/files/2017/11/DOvX0ugVwAAhVqd-1.jpg)

**Comment by yanjun0501** [comment]
@zy410419243  快来close  issue都快被自爆大军爆破了

**Comment by Xuralyon** [comment]
> ![](https://camo.githubusercontent.com/700a5911af177675dd1778341bad04e78856d96b/68747470733a2f2f6368696e616469676974616c74696d65732e6e65742f6368696e6573652f66696c65732f323031372f31312f444f765830756756774141685671642d312e6a7067)
> 
> 真正的彩蛋

闷声作大死
