### ISSUE TITLE
🎅 About the Christmas egg and workaround

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#13849]
About the christmas egg in antd, it is derived from my commit https://github.com/ant-design/ant-design/commit/00aebeb9756afecc884ad48486084836b9a2707a at Sep 10th. This implementation will make primary button snowy with native tooltip `Ho Ho Ho!` at the specificed day of Dec 25th. It is a complete stupid decision of my own and very sorry to everyone that get involved.

### How it 

Versions would be affected: `3.9.3`、`3.10.0 ~ 3.10.9`、`3.11.0 ~ 3.11.5`

We reverted the related commit and release patches: `3.9.4` `3.10.10` `3.11.6` you can upgrade to. If you are using semver version, reinstall `node_modules` would be ok.

### Are there other eggs in antd's code.

No.

### Are there same events would happen in future?

No, I promise. We are open source project, please supervise us like this time, like always.

**Comment by xiaoxiaoting** [comment]
> pity boy
> 
> "projest" is project , be relax

哈哈哈哈哈哈

**Comment by CupNoodleFork** [comment]
老哥你 christmas 还是拼错了。

**Comment by dengkunli** [comment]
chrismas -> christmas
decesion -> decision
of my owner -> of my own
projest -> project

and there're too many grammar errors as well...

**Comment by Riadloc** [comment]
> chrismas -> christmas
> decesion -> decision
> of my owner -> of my own
> projest -> project
> 
> and there're too many grammar errors as well...

Are you 秀儿?

**Comment by Ragzzy-R** [comment]
our UAT push yesterday got postponed because of this as our client is not a christmas-ish person and we dont want to piss him off. Antd is supposed to be an enterprise UI solution please prevent such things in future or atleast give a headsup. Although! we love u guys! and all the time you help us save. so cheers! and Merry Christmas 👍

**Comment by lloydsheng** [comment]
作者太紧张了，写了很多语法错误。大家还是手下留情，先把问题解决掉 😂

**Comment by gztchan** [comment]
Merry Christmas 🎅🏻Just upgrade the library and let it go, guys!

**Comment by zclaiqcc** [comment]
Surprise!

**Comment by zmofei** [comment]
A good library, just because of a Christmas egg, sympathy.

**Comment by gitchennan** [comment]
写这个代码的人真的很没有水准，靠这种方式博人眼球，不配作为程序员，简直是丢阿里的脸

**Comment by fireflyhoo** [comment]
Be in awe of Allah

**Comment by zhansingsong** [comment]
take an easy! big bro, not a big deal. 
BTW, Recommend a grammar and spell checker for you, a chrome plugin: [Grammarly for Chrome](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen/related?hl=en.)。

**Comment by Shawn-ye** [comment]
I think you could fix your typos first...

**Comment by devnkong** [comment]
No offense bro, but you really need to correct your typos. I think some extensions may be helpful, like Grammarly.

**Comment by ZJM6658** [comment]
在这个寒冷的冬天，感受到了一丝暖意，我先回家过年了

**Comment by c0ming** [comment]
大家愤怒的是一种被强奸的感觉

**Comment by SergeyVolynkin** [comment]
Yeah, imagine getting that on production in some serious Bank! >.<

**Comment by heeeeeng** [comment]
Hahahahahaha. 
Solve the problem, and Merry Christmas!

**Comment by FurshawFu** [comment]
> 在这个寒冷的冬天，感受到了一丝暖意，我先回家过年了
you such a PPXIA

**Comment by Xuralyon** [comment]
> 写这个代码的人真的很没有水准，靠这种方式博人眼球，不配作为程序员，简直是丢阿里的脸

麻烦别把娱乐圈式吐槽带到这里来

**Comment by silentred** [comment]
> chrismas -> christmas
> decesion -> decision
> of my owner -> of my own
> projest -> project
> 
> and there're too many grammar errors as well...

What a horrible catastrophe it is.

**Comment by zssjz** [comment]
事已至此，无论怎么表达愤怒都不能挽回损失；作为antd的使用者，我也对造成的后果感到惋惜，对过激的言论表示寒心；我还是希望antd能继续推出好的产品，也希望作者不要因为圣诞节事件有什么太多的负面影响；但还是希望今后能多方考虑后果，为广大开发者带来眼前一亮的作品。

**Comment by workventure-ashish** [comment]
I was so close to lose my job. Thanks and Marry Christmas.

**Comment by buyPcToJJboom** [comment]
Marry Christmas.

**Comment by hileix** [comment]
@zhansingsong Thank you recommend chrome plugin.

**Comment by comeriven** [comment]
Not bad, but need to be controlled by the developer!

**Comment by EbiEbiEvidence** [comment]
Thank you for your rapid solving!
I was pleased that my manager did not get angry and say F word to me in Slack.
Merry Christmas.

**Comment by ssrpanel** [comment]
i has been fired , thank you, may the god with u

**Comment by ssrpanel** [comment]
I has been fired , thank you, may Santa be with u

**Comment by winduser** [comment]
The wording of this apology still needs polishing. Anyway, since problem has been solved, let's move on. Merry Christmas!

**Comment by EbiEbiEvidence** [comment]
@ssrpanel hey, your www.ssrpanel.com page's SSL certificate is dead! How about renewal?

**Comment by ssrpanel** [comment]
@EbiEbiEvidence thx，the website just my demo site..

**Comment by cbangchen** [comment]
> take an easy! big bro, not a big deal.
> BTW, Recommend a grammar and spell checker for you, a chrome plugin: [Grammarly for Chrome](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen/related?hl=en.)。

take an easy 是啥意思，歇息一下？take it easy
big bro 是另起一句了，应该是 Big bro, ...
Recommend 句内，不应该大写首字母吧 
你用了这个插件没

**Comment by TsangTszKin** [comment]
good, be careful next time, take it easy.   Merry Christmas .

**Comment by joesonw** [comment]
> take an easy! big bro, not a big deal.
> BTW, Recommend a grammar and spell checker for you, a chrome plugin: [Grammarly for Chrome](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen/related?hl=en.)。

take an easy `->` take it easy
big bro `->` bro
not a big deal `->` it's not a big deal
Recommend `->` I recommend

这插件也不咋地嘛

**Comment by EbiEbiEvidence** [comment]
Hmm, I think that this page is not an English classroom...

**Comment by wellenzhong** [comment]
Foreign friends are much friendlier than our  Chinese guys.
anyway, thank you guys for your hard work!

**Comment by EbiEbiEvidence** [comment]
Hmm, I think that this page is not an English classroom...
How about focusing our eyes on codes and features?

**Comment by 252405649** [comment]
> 写这个代码的人真的很没有水准，靠这种方式博人眼球，不配作为程序员，简直是丢阿里的脸

可能你不是程序员，才可以说出这样的话。小错，改了就好

**Comment by kangkai124** [comment]
> 老哥你 christmas 还是拼错了。
你是魔鬼吗...

**Comment by Zheaoli** [comment]
认真的说，这次最坏的情况下，有使用者被劝退是最好的结果
最坏的结果是有使用者被检察院以渎职罪或者破坏信息系统罪提起刑事诉讼了

**Comment by zhansingsong** [comment]
> > take an easy! big bro, not a big deal.
> > BTW, Recommend a grammar and spell checker for you, a chrome plugin: [Grammarly for Chrome](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen/related?hl=en.)。
> 
> take an easy 是啥意思，歇息一下？take it easy
> big bro 是另起一句了，应该是 Big bro, ...
> Recommend 句内，不应该大写首字母吧
> 你用了这个插件没

哈哈，尴尬鸟。完整功能需要付费，穷屌丝一枚😆。不过插件整体体验还是不错的。

**Comment by M1seRy** [comment]
> chrismas -> christmas
> decesion -> decision
> of my owner -> of my own
> projest -> project
> 
> and there're too many grammar errors as well...

[Grammarly ](https://www.grammarly.com/) is a good tool for making sure everything you typed is right.

**Comment by GabrielCheung128** [comment]
Didn't upgrade to the corresponding version, so wasn't impacted by this.
But how could that be merged if it was only your decision? And how you responded to those who raised the issue first was quite ridiculous as well as offensive. 
You guys should take it serious on code review, or somebody somewhere in the world would lose his job, that's **NOT FUN** at all. 

Still, Merry Christmas.

**Comment by Lilysunstrider** [comment]
Es Yotube tod us: if yo rite anysing un yor coputer, yo ned `Gramarly`. Marry Chrismas!

**Comment by zhenghangjie** [comment]
reverence for this issue

**Comment by ipv4sec** [comment]
惊闻 antd 发生了 圣诞节彩蛋事件，赶紧去检查了一遍所有项目，还好版本都较低没有发生故障，去官网观摩了一下，button 上的云彩的确够惊艳，说到云彩，我就想起筋斗云和孙悟空，明年年初，中美合拍的西游记即将正式开机，我继续扮演美猴王孙悟空，我会用美猴王艺术形象努力创造一个正能量的形象，文体两开花，弘扬中华文化，希望大家多多关注。

**Comment by OuyangQianba** [comment]
后排吃瓜。

**Comment by ferried** [comment]
后排偷偷卖片儿...加微信xxxxx

**Comment by hunterhug** [comment]
I want to see that egg, can anyone tell me where .....

**Comment by Albuseven** [comment]
> 惊闻 antd 发生了 圣诞节彩蛋事件，赶紧去检查了一遍所有项目，还好版本都较低没有发生故障，去官网观摩了一下，button 上的云彩的确够惊艳，说到云彩，我就想起筋斗云和孙悟空，明年年初，中美合拍的西游记即将正式开机，我继续扮演美猴王孙悟空，我会用美猴王艺术形象努力创造一个正能量的形象，文体两开花，弘扬中华文化，希望大家多多关注。



> I want to see that egg, can anyone tell me where .....

https://mobile.ant.design/

**Comment by Albuseven** [comment]
> I want to see that egg, can anyone tell me where .....

https://mobile.ant.design/

**Comment by hunterhug** [comment]
> > I want to see that egg, can anyone tell me where .....
> 
> https://mobile.ant.design/

Ho HO HO~~~

**Comment by hualv-tao** [comment]
换地方围观？

**Comment by luyc** [comment]
This egg is so big and so round.

**Comment by feichangtutu** [comment]
> Are there same events happend in future?
是个病句啊……

**Comment by cbangchen** [comment]
Are you gays OK ????

**Comment by lzfgnu** [comment]
> 惊闻 antd 发生了 圣诞节彩蛋事件，赶紧去检查了一遍所有项目，还好版本都较低没有发生故障，去官网观摩了一下，button 上的云彩的确够惊艳，说到云彩，我就想起筋斗云和孙悟空，明年年初，中美合拍的西游记即将正式开机，我继续扮演美猴王孙悟空，我会用美猴王艺术形象努力创造一个正能量的形象，文体两开花，弘扬中华文化，希望大家多多关注。

谢罪吧，老哥

**Comment by cbangchen** [comment]
are You gUys ookkk ???

**Comment by ferried** [comment]
> 惊闻 antd 发生了 圣诞节彩蛋事件，赶紧去检查了一遍所有项目，还好版本都较低没有发生故障，去官网观摩了一下，button 上的云彩的确够惊艳，说到云彩，我就想起筋斗云和孙悟空，明年年初，中美合拍的西游记即将正式开机，我继续扮演美猴王孙悟空，我会用美猴王艺术形象努力创造一个正能量的形象，文体两开花，弘扬中华文化，希望大家多多关注。

向全国人民谢罪吧

**Comment by FurshawFu** [comment]
@afc163   麻烦关闭一下，这一下午垃圾邮件已经够多了。

**Comment by rootkiter** [comment]
Good job!
