### ISSUE TITLE
Button's Style changed suddenly  on Christmas Day

### ISSUE THREAD

**Issue by jeezliu** [ant-design/ant-design#13842]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.0

### Environment
3.11.0

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
<Button type="primary">Click</Button>

### What is expected?
no extra scene

### What is actually happening?
have a extra scene

---
不带这么玩的，用很多严肃正式的场合啊

**Comment by Yangzhedi** [comment]
https://github.com/ant-design/ant-design/issues/13098
