### ISSUE TITLE
3.11.6版本列表无数据默认提示变成了英文No data

### ISSUE THREAD

**Issue by xiaomoziyi** [ant-design/ant-design#13854]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
3.11.6

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://mz047rnxzx.codesandbox.io/)

### Steps to reproduce
 render() {
    const tableData = [];
    const columns = [
      {
        title: "test1"
      },
      {
        title: "test2"
      }
    ];
    return (
      <div className="App">
        <p>Current antd version: {version}</p>
        <p>Please fork this codesandbox to reproduce your issue.</p>
        <p>请 fork 这个链接来重现你碰到的问题。</p>
        <Button type="primary">Hello</Button>
        <p>这是个列表</p>
        <Table dataSource={tableData} columns={columns} />
      </div>
    );
  }

### What is expected?
期望列表出现暂无数据

### What is actually happening?
实际是No data

**Comment by afc163** [comment]
你需要加上 https://ant.design/components/locale-provider-cn/

**Comment by chaegumi** [comment]
@afc163 我升级了ant design3.11.6之后，原来ant design pro的组件的中文是正常的，现在都是英文，删除了umi缓存也不行，是什么原因
