### ISSUE TITLE
🎄Project wiki can be edited by any user

### ISSUE THREAD

**Issue by FeeiCN** [ant-design/ant-design#13853]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
latest

### Reproduction link
[https://github.com/ant-design/ant-design/wiki](https://github.com/ant-design/ant-design/wiki)

### Steps to reproduce
https://github.com/ant-design/ant-design/wiki

### What is expected?
Can't edited

### What is actually happening?
Edited

**Comment by afc163** [comment]
Fixed now.
