### ISSUE TITLE
建议：关于DatePicker的返回值统一问题。

### ISSUE THREAD

**Issue by outrace** [ant-design/ant-design#1385]
当表单上有一个DatePicker，用户点击选择了日期后。
this.props.form.validateFields((errors, values)
返回的values。其类型是Date类型

当使用this.props.form.setFieldsValue 设置DatePicker的value ：'2016-04-01'
（  format="yyyy-MM-dd"）。可以正常显示。
但是这时候直接调用
this.props.form.validateFields((errors, values)   返回的是string类型的‘2016-04-01’。
但是如果用户点击表单，更改这个DatePicker的值  返回的就又会是Date类型

建议：
无论是setFieldsValue的时候，设置的是Date类型还是String类型。

DatePicker统一返回一种类型（Date类型或者String类型，个人建议都返回符合format格式的String类型）。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1104

**Comment by outrace** [comment]
@afc163 
我主要是觉得有的时候返回的是String，有的时候返回的是Date。会需要额外出来比较麻烦。
只要返回的格式是统一的。是那种类型都OK。

**Comment by afc163** [comment]
DatePicker 的返回值是统一的。应该是 Form 修改了返回值？

**Comment by afc163** [comment]
DatePicker 的返回值是统一的。应该是 Form 修改了返回值？

**Comment by outrace** [comment]
情况1：
1 From中放一个空白的DatePicker
2 在componentDidMount通过this.props.form.setFieldsValue更新DatePicker的值。这时候设置的值为String类型
3 在Submit的时候，提取出来的DatePicker的值将是String类型

情况2
1 From中放一个空白的DatePicker
2 在componentDidMount通过this.props.form.setFieldsValue更新DatePicker的值。这时候设置的值为String类型
3 用户更改DatePicker的日期为另外一个日期
4 在Submit的时候，提取出来的DatePicker的值将是Date类型

**Comment by outrace** [comment]
或者DatePicker的Value，不再接受String类型，只接受Date类型。可能也是一种方案。

**Comment by outrace** [comment]
因为setFieldsValue的时候。如果DatePicker的value是Date类型。
即使用户不操作。获取出来的也是Date类型。这样逻辑是通的。

现在的情况是：设置value为String类型，用户不更改的话，得到String类型。更改的话，得到的就是Date类型。感觉很怪。

**Comment by outrace** [comment]
```javascript
import '../common/lib';
import React from 'react';
import ReactDOM from 'react-dom';
import { Button, Form, Input, DatePicker} from 'antd';
import { Radio } from 'antd';
const createForm = Form.create;
const FormItem = Form.Item;

const formItemLayout = {
  labelCol: { span: 4 },
  wrapperCol: { span: 6 }
};

let Demo = React.createClass({

  componentDidMount() {
    const {setFieldsValue} = this.props.form;
    setFieldsValue({
      'testDate':'2016-01-01'
    })
  },

  getInitialState() {
    return {
      frmItems :[]
    };
  },

  handleSubmit(e) {
    e.preventDefault();
    this.props.form.validateFields((errors, values) => {
      if (!!errors) {
        return;
      }
      console.log(values.testDate); //没修改则为String，有修改则为Date，希望能够统一
    });
  },

  render(){
    const { getFieldProps } = this.props.form;

    return (
        <Form horizontal form={this.props.form}>
          <FormItem
              {...formItemLayout}
              label="日期3："
              hasFeedback>
            <DatePicker {...getFieldProps('testDate')}  format="yyyy-MM-dd"/>
          </FormItem>
          <FormItem wrapperCol={{ span: 8, offset: 6 }}>
            <Button type="primary" onClick={this.handleSubmit}>确定</Button>
          </FormItem>
        </Form>
    )
  },

});

Demo = createForm()(Demo);

ReactDOM.render(<Demo/>, document.getElementById("con"));
```

**Comment by afc163** [comment]
看来要这样：

```js
onChange(Date date, String dateString) {

}
```

=>

```js
onChange(String dateString, Date date) {

}
```

不过这样就无法向下兼容，要考虑一下。

**Comment by afc163** [comment]
1. 建议限制 DatePicker 的校验 type：

```js
getFieldProps('birthday', {
  rules: [{
    type: 'date',
  }]
})
```

2. setFieldsValue 和 initialValue 时使用 Date 类型。

---

暂不修改 onChange 的参数，向下兼容的压力比较大，望谅解。

**Comment by zhump** [comment]
所以说 还是自己拿到 onChange的参数  自己去处理吗

**Comment by benjycui** [comment]
1.0.0 已经支持 `dateString` 了 https://github.com/ant-design/ant-design/search?utf8=%E2%9C%93&q=dateString

**Comment by zhump** [comment]
1.0.0  发布了吗 我install 下来的 是  0.12.15

**Comment by benjycui** [comment]
`npm i antd@beta`

**Comment by zhump** [comment]
thx lot
