### ISSUE TITLE
Ant Design 圣诞彩蛋不升级版本的修复方式

### ISSUE THREAD

**Issue by duanzheng** [ant-design/ant-design#13857]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
圣诞彩蛋导致的2个问题

### What does the proposed API look like?
如果你暂时不想升级Antd版本，把下面这段JavaScript代码粘贴到你的html文件中即可

```javascript
(function() {
    var now = new Date();
    var isChristmas = now.getMonth() === 11 && now.getDate() === 25;
    if (isChristmas) {
        var style = document.createElement('style');
        style.type = 'text/css';
        style.innerHTML= '.christmas.ant-btn-primary::before {display: none !important;}';
        document.getElementsByTagName('HEAD').item(0).appendChild(style);
        document.addEventListener('mouseover', function(e) {
            var targetDom = e.target;
            if (targetDom.tagName === 'BUTTON' && targetDom.title === 'Ho Ho Ho!') {
                targetDom.setAttribute('title', '');
            }
    	});
    }
})()
```

**Comment by Richard1ybb** [comment]
now.getMonth() === 11?

**Comment by dbFlower** [comment]
> now.getMonth() === 11?

别问，问就是js如此

**Comment by wl00887404** [comment]
@Richard1ybb 
the value from Date.getMonth() starts from 0

**Comment by fengjiahao** [comment]
>* 根据本地时间，返回一个指定的日期对象的月份，为基于0的值（0表示一年中的第一月）
>* The getMonth() method returns the month in the specified date according to local time, as a zero-based value (where zero indicates the first month of the year).

**Comment by reddwen** [comment]
no problem , old iron~

**Comment by ChinaHDJ** [comment]
> no problem , old iron~

老铁，没毛病

**Comment by Richard1ybb** [comment]
...why date not starts with 0

**Comment by ChinaHDJ** [comment]
> now.getMonth() === 11?

0是一月份。懂了吧？

**Comment by wzc570738205** [comment]
You can open the browser console (F12), enter 
···
new Date (). getMonth ()
···
 and it will output ···11···, yes. This is JS.

**Comment by liuyueji** [comment]
这样强制所有title清空，也不太友好吧

**Comment by flyfox11** [comment]
圣诞按钮一朵云，菜鸟落进了聊天群，满屏都是程序汉，谁敲bug谁丢魂

**Comment by fwh1990** [comment]
今天antd的star多了好几百，收获挺大的

**Comment by wellenzhong** [comment]
> no problem , old iron~

double click 666~

**Comment by Zheaoli** [comment]
认真的说，这次最坏的情况下，有使用者被劝退是最好的结果
最坏的结果是有使用者被检察院以渎职罪或者破坏信息系统罪提起刑事诉讼了

**Comment by wf123537200** [comment]
> 今天antd的star多了好几百，收获挺大的

我也发现了，难道是营销手段

**Comment by xiaohubei** [comment]
> now.getMonth() === 11?

are you sure you are web developer

**Comment by Char-Ten** [comment]
弱爆了。。。。我都是叫客户改一下系统时间，把系统时间往后调一天

**Comment by xiaohubei** [comment]
> 弱爆了。。。。我都是叫客户改一下系统时间，把系统时间往后调一天

you are the one who look like super star

**Comment by hunterhug** [comment]
> 弱爆了。。。。我都是叫客户改一下系统时间，把系统时间往后调一天

niubility such you

**Comment by lifamomo** [comment]
点赞

**Comment by gtk4php** [comment]
> 认真的说，这次最坏的情况下，有使用者被劝退是最好的结果
> 最坏的结果是有使用者被检察院以渎职罪或者破坏信息系统罪提起刑事诉讼了
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND 许可证上说了，不提供任何担保

**Comment by a83988029** [comment]
# antd的星星涨了一波

**Comment by gtk4php** [comment]
> 认真的说，这次最坏的情况下，有使用者被劝退是最好的结果
> 最坏的结果是有使用者被检察院以渎职罪或者破坏信息系统罪提起刑事诉讼了

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND

**Comment by espaja** [comment]
> > 弱爆了。。。。我都是叫客户改一下系统时间，把系统时间往后调一天
> 
> niubility such you

what a  niubility english ：）

**Comment by fkdswfwqfet** [comment]
真坑啊

**Comment by fkdswfwqfet** [comment]
> 真坑啊

被领导骂死 ，尴尬

**Comment by chao** [comment]
强势围观

**Comment by KeepFing** [comment]
吓得我把春节的特效代码给删了

**Comment by RobotJiang** [comment]
> 弱爆了。。。。我都是叫客户改一下系统时间，把系统时间往后调一天

不是应该往前调整一天吗？

**Comment by xmt1139057136** [comment]
![image](https://user-images.githubusercontent.com/23303979/50416303-d9765300-085a-11e9-8302-793cb0df31b8.png)
更多效果在这里！

**Comment by NeverMore93** [comment]
感觉挺好的

**Comment by XuWuDeAi** [comment]
> now.getMonth() === 11?

一月是0

**Comment by ljwaheng** [comment]
好的

**Comment by AppxLite** [comment]
心里一直有个疑问，这是不是阿里故意做的一次 SEO，知名度又提高了不少，我看star数量涨了不少。

**Comment by shaopeng1** [comment]
> 心里一直有个疑问，这是不是阿里故意做的一次 SEO，知名度又提高了不少，我看star数量涨了不少。

是涨了一大截

**Comment by MorisHarA** [comment]
> 弱爆了。。。。我都是叫客户改一下系统时间，把系统时间往后调一天

牛逼

**Comment by MorisHarA** [comment]
> 其实春节加这个彩蛋的话就比较 好了,举国欢庆,我也希望这个能出一个配置来配置

外国开发者看到也会很奇怪啊

**Comment by xmt1139057136** [comment]
> ![image](https://user-images.githubusercontent.com/23303979/50416303-d9765300-085a-11e9-8302-793cb0df31b8.png)
> 更多效果在这里！

阿里这次是在提醒大家，大家平时使用开源框架要注意。ant-design 只是一个彩蛋而已，那些后端使用的框架，不知道有多少雷在等着大家！

尤其是一些国外的开源框架。

这只是一次善意的提醒！

**Comment by zhegexiaohuozi** [comment]
挺好的彩蛋！赞一个！

**Comment by kuchajun** [comment]
> 挺好的彩蛋！赞一个！
彩蛋没有好坏 人心有

**Comment by NeverMore93** [comment]
> 心里一直有个疑问，这是不是阿里故意做的一次 SEO，知名度又提高了不少，我看star数量涨了不少。

已经是react前五的组件了

**Comment by NeverMore93** [comment]
> > ![image](https://user-images.githubusercontent.com/23303979/50416303-d9765300-085a-11e9-8302-793cb0df31b8.png)
> > 更多效果在这里！
> 
> 阿里这次是在提醒大家，大家平时使用开源框架要注意。ant-design 只是一个彩蛋而已，那些后端使用的框架，不知道有多少雷在等着大家！
> 
> 尤其是一些国外的开源框架。
> 
> 这只是一次善意的提醒！

大家和我一起把这个傻叉举报了

**Comment by shaopeng1** [comment]
> > > ![image](https://user-images.githubusercontent.com/23303979/50416303-d9765300-085a-11e9-8302-793cb0df31b8.png)
> > > 更多效果在这里！
> > 
> > 
> > 阿里这次是在提醒大家，大家平时使用开源框架要注意。ant-design 只是一个彩蛋而已，那些后端使用的框架，不知道有多少雷在等着大家！
> > 尤其是一些国外的开源框架。
> > 这只是一次善意的提醒！
> 
> 大家和我一起把这个傻叉举报了

确实烦，一个二维码那么大，还一遍一遍不压其烦的发

**Comment by plightfield** [comment]
欢迎加入无觅，绝对不会因为bug就拿程序员祭天，leader保证会兜底。
联系邮箱：zhujiao@wumii.com    联系人：Teddy

**Comment by shenanheng** [comment]
这里发招聘的人也是牛逼的很

**Comment by zhegexiaohuozi** [comment]
别特么发广告，贱不贱

**Comment by qipiaoyang** [comment]
> 欢迎加入无觅，绝对不会因为bug就拿程序员祭天，leader保证会兜底。
> 联系邮箱：[zhujiao@wumii.com](mailto:zhujiao@wumii.com) 联系人：Teddy

别拉低你们公司的名声，谢谢！

**Comment by Azimiao** [comment]
six six six

**Comment by linronglang** [comment]
个人觉的挺好玩的

**Comment by DongDavid** [comment]
还好我的下个月才上线， 烙铁6666666666666

**Comment by percyjie** [comment]
好险是自己公司用的管理系统 问题不大 哈哈

**Comment by z54749412** [comment]
> 弱爆了。。。。我都是叫客户改一下系统时间，把系统时间往后调一天

how you are so diao

**Comment by byszhao** [comment]
这个彩蛋666

**Comment by okool** [comment]
国内节日都阴历,代码很难写.来来来你们用两行代码写个春节彩蛋.

**Comment by kuchajun** [comment]
> 国内节日都阴历,代码很难写.来来来你们用两行代码写个春节彩蛋.

你还真是给我出了个难题

**Comment by wellenzhong** [comment]
> 国内节日都阴历,代码很难写.来来来你们用两行代码写个春节彩蛋.

https://www.npmjs.com/package/solarlunar

**Comment by chao** [comment]
> 国内节日都阴历,代码很难写.来来来你们用两行代码写个春节彩蛋.

直接放个数组，存它个100年日期进去就完了。这个框架还能用100年？

**Comment by niean** [comment]
> 圣诞按钮一朵云，菜鸟落进了聊天群，满屏都是程序汉，谁修bug谁丢魂

人才

**Comment by xmt1139057136** [comment]
圣诞按钮一朵云，菜鸟落进了聊天群，满屏都是程序汉，谁修bug谁丢魂

**Comment by xmt1139057136** [comment]
> > ![image](https://user-images.githubusercontent.com/23303979/50416303-d9765300-085a-11e9-8302-793cb0df31b8.png)
> > 更多效果在这里！
> 
> 阿里这次是在提醒大家，大家平时使用开源框架要注意。ant-design 只是一个彩蛋而已，那些后端使用的框架，不知道有多少雷在等着大家！
> 
> 尤其是一些国外的开源框架。
> 
> 这只是一次善意的提醒！

圣诞按钮一朵云，菜鸟落进了聊天群，满屏都是程序汉，谁修bug谁丢魂

**Comment by 8pig** [comment]
> > ![image](https://user-images.githubusercontent.com/23303979/50416303-d9765300-085a-11e9-8302-793cb0df31b8.png)
> > 更多效果在这里！
> 
> 阿里这次是在提醒大家，大家平时使用开源框架要注意。ant-design 只是一个彩蛋而已，那些后端使用的框架，不知道有多少雷在等着大家！
> 
> 尤其是一些国外的开源框架。
> 
> 这只是一次善意的提醒！

反向洗

**Comment by hengkx** [comment]
广告 有点 过份了啊

**Comment by jiangbo212** [comment]
可以考虑写个开源代码检查功能，扫描代码中所有可能指定条件的功能，如定时器，特定时间，特定操作系统，特定网络环境等。

**Comment by HandsomeOrDie** [comment]
那些嚷嚷着被开掉的，除非是特别严肃的项目或者特别较真的领导，其余要么是凑热闹胡说的，要么是早被领导盯上憋着怎么开你呢，这种情况留着也没年终奖，早跑路早高就~~

**Comment by oychao** [comment]
连句道歉都没有吗？当然你觉得你们没错那当我没说~
