### ISSUE TITLE
纯活该，还有脸怪别人

### ISSUE THREAD

**Issue by mopiaoyao** [ant-design/ant-design#13864]
纯活该，ZF最重视数据所有权，给ZF干活必须本地化，图省事装逼用网络开源，还有脸怪蚂蚁，再说了，蚂蚁收你钱了吗？说白了蚂蚁免费给你用那是蚂蚁心善，不给你用了你也没吊治，自己没有点承担风险的觉悟就敢用免费开源，出了事就怪别人咯？百度网盘里的黄色视频都被和谐了，你怎么不去百度门口静坐？

**Comment by Eusen** [comment]
脑残...
