### ISSUE TITLE
TypeScript: Change handler parameters optional

### ISSUE THREAD

**Issue by travikk** [ant-design/ant-design#13862]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
browser

### Reproduction link
[http://ant.design](http://ant.design)

### Steps to reproduce
Some versions ago, TS definitions made parameters of change handlers optional. Under what conditions would they be undefined?
Few examples:

PopconfirmProps.onVisibleChange has all params optional.
InputNumberProps.onChange - surely this should just be (value: number) => void instead of number | string | undefined?
DropDownProps.onVisibleChange has visible param optional

### What is expected?
For the change handler params not to be optional and make sense.

### What is actually happening?
I need to workaround in the downstream code to work around optional props which should never be optional.

**Comment by afc163** [comment]
`<Popconfirm onVisibleChange={() => {}} />`

It could be allowed to use in this way, I think all argments should be optional.

**Comment by travikk** [comment]
@afc163 się, but you can do that without making parameters optional. TS allows omitting non needed parameters.

**Comment by raybooysen** [comment]
Agreed with @travikk

**Comment by afc163** [comment]
Could you send PR as a hint for us?

**Comment by travikk** [comment]
@afc163 https://github.com/ant-design/ant-design/pull/13988 here you go

**Comment by zy410419243** [comment]
Close please if completed.
