### ISSUE TITLE
Generic type 'MouseEvent<T>' requires between 0 and 1 type arguments.

### ISSUE THREAD

**Issue by zhengweijia** [ant-design/ant-design#13861]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
chrome typescript

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
安装了最新版本3.11.6，ts 检查时报错

### What is expected?
ts 检查通过

### What is actually happening?
node_modules/antd/lib/alert/index.d.ts
(34,22): Generic type 'MouseEvent<T>' requires between 0 and 1 type arguments.

**Comment by chaegumi** [comment]
虽然不是很懂，但是刚才看到这个，顺手就升级了下。https://github.com/ant-design/ant-design/issues/13858

**Comment by lpcman** [comment]
same error in 3.10.10

**Comment by Xiao4** [comment]
see #13858

**Comment by xianmxcv** [comment]
昨天升级3.11.6也有这个错误

**Comment by zhengweijia** [comment]
> 昨天升级3.11.6也有这个错误

see #13858
