### ISSUE TITLE
react现在升级到15了。ant有跟进吗?

### ISSUE THREAD

**Issue by phpjoe** [ant-design/ant-design#1386]
现在react升级到15.0.1了，ant design有跟进吗？我升级了一下react，结果有报警告出来：
Warning: Failed propType: Invalid prop `selectedKeys[0]` of type `number` supplied to `Menu`, expected `string`.warning @ warning.js:45checkPropTypes @ ReactElementValidator.js:189validatePropTypes @ ReactElementValidator.js:208ReactElementValidator.createElement @ ReactElementValidator.js:242AntMenu_render @ index.js:97ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:679ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:699ReactCompositeComponent__renderValidatedComponent @ ReactPerf.js:66ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:284ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:624ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:470ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:624ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:470ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:624ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:470ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39mountComponentIntoNode @ ReactMount.js:103Mixin.perform @ Transaction.js:136batchedMountComponentIntoNode @ ReactMount.js:124Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:97ReactMount._renderNewRootComponent @ ReactMount.js:277ReactMount__renderNewRootComponent @ ReactPerf.js:66ReactMount._renderSubtreeIntoContainer @ ReactMount.js:354ReactMount.render @ ReactMount.js:374React_render @ ReactPerf.js:66(anonymous function) @ index.jsx:19__webpack_require__ @ bootstrap 2bcd640…:585fn @ bootstrap 2bcd640…:109(anonymous function) @ index.js:6__webpack_require__ @ bootstrap 2bcd640…:585webpackJsonpCallback @ bootstrap 2bcd640…:21(anonymous function) @ index.js:1
warning.js:45Warning: Failed propType: Invalid prop `selectedKeys[0]` of type `number` supplied to `SubPopupMenu`, expected `string`.warning @ warning.js:45checkPropTypes @ ReactElementValidator.js:189validatePropTypes @ ReactElementValidator.js:208ReactElementValidator.createElement @ ReactElementValidator.js:242renderChildren @ SubMenu.js:263SubMenu_render @ SubMenu.js:319ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ReactCompositeComponent.js:679ReactCompositeComponentMixin._renderValidatedComponent @ ReactCompositeComponent.js:699ReactCompositeComponent__renderValidatedComponent @ ReactPerf.js:66ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:284ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:624ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:470ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:624ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:470ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:624ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:470ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactMultiChild.Mixin.mountChildren @ ReactMultiChild.js:203ReactDOMComponent.Mixin._createInitialChildren @ ReactDOMComponent.js:624ReactDOMComponent.Mixin.mountComponent @ ReactDOMComponent.js:470ReactDOMComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39ReactCompositeComponentMixin.performInitialMount @ ReactCompositeComponent.js:290ReactCompositeComponentMixin.mountComponent @ ReactCompositeComponent.js:237ReactCompositeComponent_mountComponent @ ReactPerf.js:66ReactReconciler.mountComponent @ ReactReconciler.js:39mountComponentIntoNode @ ReactMount.js:103Mixin.perform @ Transaction.js:136batchedMountComponentIntoNode @ ReactMount.js:124Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:63batchedUpdates @ ReactUpdates.js:97ReactMount._renderNewRootComponent @ ReactMount.js:277ReactMount__renderNewRootComponent @ ReactPerf.js:66ReactMount._renderSubtreeIntoContainer @ ReactMount.js:354ReactMount.render @ ReactMount.js:374React_render @ ReactPerf.js:66(anonymous function) @ index.jsx:19__webpack_require__ @ bootstrap 2bcd640…:585fn @ bootstrap 2bcd640…:109(anonymous function) @ index.js:6__webpack_require__ @ bootstrap 2bcd640…:585webpackJsonpCallback @ bootstrap 2bcd640…:21(anonymous function) @ index.js:1
invariant.js:38Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details:

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1340

Don't submit duplicate issue.
