### ISSUE TITLE
为何这么严肃？多一点阳光，实名支持这位程序员，抵制网络暴力。 

### ISSUE THREAD

**Issue by iamzfj007** [ant-design/ant-design#13874]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
为何这么严肃？生活应该充满阳光与乐趣。  开源项目应该多一点阳光。  如果你做政府项目，那么是否应该保证代码本地化，可控制？ 谁允许你图省事用UI库的？问过zf了吗?  自己图省事用了别人的开源库给你偷懒，既然要要求一切可控，为什么还要用网络上不可控的开源项目，人家埋个彩蛋，现在还来怪别人为什么要给你用？  现在人家被开了，你们这些网络暴民舒服了。

### Reproduction link
[https://github.com/ant-design/ant-design/issues/13864](https://github.com/ant-design/ant-design/issues/13864)

### Steps to reproduce
1

### What is expected?
1

### What is actually happening?
1

---
1

**Comment by young40** [comment]
抵制网络暴力!

**Comment by Shangyunliang** [comment]
抵制网络暴力!

**Comment by flyfox11** [comment]
圣诞按钮一朵云，菜鸟落进了聊天群，满屏都是程序汉，谁修bug谁丢魂

**Comment by jiahuajiang60** [comment]
抵制网络暴力!实名支持

**Comment by nerososft** [comment]
挺有爱的彩蛋

**Comment by dyun8080** [comment]
抵制网络暴力!实名支持。再说本来就是搞技术的，有点童心和幽默不好吗？

**Comment by lywTYH** [comment]
哎 只是觉得这个不隐藏的话，是否就不是这个结果了。到现在也没想明白为什么要隐瞒

**Comment by stone821** [comment]
在奇葩国，正好碰上奇葩时间，正好遇到奇葩。。。

**Comment by chengluyu** [comment]
抵制网络暴力不等于支持这种加彩蛋的做法，二者不排斥。谢谢。

我们反对网络暴力，也不欢迎在开源项目中为所欲为。

**Comment by teacherMa** [comment]
公猪配种，您配吗？

**Comment by afc163** [comment]
Duplicate of #13848

**Comment by huanhulan** [comment]
呵呵，没有搞清楚权力和自由的人真是一抓一大把

**Comment by zhishanggao** [comment]
公猪配种，您配吗？

**Comment by nerososft** [comment]
> 公猪配种，您配吗？

您配

**Comment by diwayou** [comment]
抵制网络暴力，但是一个大量用户的开源软件做这种事情，我还真不知道当时他脑子怎么想的。。。

**Comment by circletop** [comment]
坚决拥护党和人民

**Comment by AibiTi** [comment]
@iamzfj007 你不就是上此在 deno 搞事情，那傻逼货。

**Comment by iamzfj007** [comment]
> @iamzfj007 你不就是上此在 deno 搞事情，那傻逼货。

我搞事情？？你有什么资格在这里喷粪？
楼上骂人的话，公猪配种，你配吗？

**Comment by kelvin17** [comment]
抵制网络暴力，正确看待这个问题。

**Comment by AibiTi** [comment]
哈哈，既然这么快就出狱了。

![image](https://user-images.githubusercontent.com/40224479/50428028-53a3e780-08ee-11e9-905e-330f996c6203.png)

**Comment by kigawas** [comment]
> 哈哈，既然这么快就出狱了。
> 
> ![image](https://user-images.githubusercontent.com/40224479/50428028-53a3e780-08ee-11e9-905e-330f996c6203.png)

再送他进去一次

**Comment by iamzfj007** [comment]
> > 哈哈，既然这么快就出狱了。
> > ![image](https://user-images.githubusercontent.com/40224479/50428028-53a3e780-08ee-11e9-905e-330f996c6203.png)
> 
> 再送他进去一次

来呀 要紧大家一起进
