### ISSUE TITLE
开源免费的，放个彩蛋又怎么了？政府要假正经，一群狗跟着狂吠，支持这位阿里程序员

### ISSUE THREAD

**Issue by hugetiny** [ant-design/ant-design#13871]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
任何

### Reproduction link
[https://github.com/ant-design/ant-design/issues/13870](https://github.com/ant-design/ant-design/issues/13870)

### Steps to reproduce
支持这位阿里程序员

### What is expected?
提升这位阿里程序员职位，代替负责审核他的领导

### What is actually happening?
看阿里怎么定

---
现在中国人的思维里面，党就是要假正经，你敢让党的显得不正经，就要弄死你。

首先ant-design是开源免费的，爱用不用。撇去一些法律免责条款不说，圣诞节彩蛋怎么了？涉黄涉毒了吗？违什么法了吗？

要假正经就要让企业逼一个没有做错任何事的普通程序员滚是吗？

从阿里角度来说，责任不应该让这位程序员承担，如果不让彩蛋上，审核环节完全可以做到，你不会在new Date()的时候检查这个Date要干嘛的吗？责任都要起早摸黑的底层的程序员负，然后像百度刘超那样的人作为领导不做好审核工作还继续买豪车，泡野模，爆炒黑木耳？

从宗教角度来说：听说此次事件影响到了伊朗的中国程序员。伊朗明文禁止基督教相关的，那么我们国内的项目：
谁给你权力禁止过洋节的？
《中华人民共和国宪法》
第三十六条　中华人民共和国公民有宗教信仰自由。
任何国家机关、社会团体和个人不得强制公民信仰宗教或者不信仰宗教，不得歧视信仰宗教的公民和不信仰宗教的公民。
国家保护正常的宗教活动。任何人不得利用宗教进行破坏社会秩序、损害公民身体健康、妨碍国家教育制度的活动。
宗教团体和宗教事务不受外国势力的支配。
说好的法治国家呢？

**Comment by kuchajun** [comment]
？？？？

**Comment by MagicalAna** [comment]
你又懂开源了

**Comment by nerososft** [comment]
支持!!! 爱用不用, 使用的时候不感谢, 出事的时候就知道问候开发者, 有本事自己写一个啊.

**Comment by chenyitian** [comment]
任何国家机关、社会团体和个人不得强制公民信仰宗教或者不信仰宗教

**Comment by Null-Ouwenjie** [comment]
事故就是事故，这也能上升到宗教来杠，服了。

**Comment by vissssa** [comment]
你的👄有点甜

**Comment by dyun8080** [comment]
支持!!! 爱用不用, 使用的时候不感谢, 出事的时候就知道问候开发者, 有本事自己写一个啊.

**Comment by xuanmos** [comment]
在做的各位都需要上班的嘛🌝🌝🌝

**Comment by nerososft** [comment]
> 任何国家机关、社会团体和个人不得强制公民信仰宗教或者不信仰宗教

你别用嘛, 有本事自己写一个嘛, 人家团队花费心思精力自己写的, 免费出来,爱用不用. 还有理了.

**Comment by Eusen** [comment]
强制别人用，跟囚禁有区别么，强迫别人做别人不喜欢做的事，你还觉得挺骄傲？

**Comment by chenyitian** [comment]
> > 任何国家机关、社会团体和个人不得强制公民信仰宗教或者不信仰宗教
> 
> 你别用嘛, 有本事自己写一个嘛, 人家团队花费心思精力自己写的, 免费出来,爱用不用. 还有理了.

我真没用过antd。只是这事错了就是错了，没得洗。

**Comment by ContainsK** [comment]
即使是开源代码，也不能为所欲为吧？

**Comment by insipidness** [comment]
说被开除的，这次没有被开除的都是NMSL，我就是暴躁老哥，没脑子，爱用不用。

**Comment by hugetiny** [comment]
科普一下：
为什么涉及宗教?圣诞节是基督教节日

这帖子貌似很多人点unlike，估计都是被领导逼着改掉这个彩蛋的人，多了很多的工作，压力大，又不敢喷那群那假正经的人，只敢喷ant-design，可以理解

**Comment by Eusen** [comment]
那些洗的，你们越洗越觉得你们恶心，真的

**Comment by nerososft** [comment]
> 强制别人用，跟囚禁有区别么，强迫别人做别人不喜欢做的事，你还觉得挺骄傲？

免费的东西, 谁强制你用了? antdesign 开发团队强制你用antd了么

**Comment by flyfox11** [comment]
圣诞按钮一朵云，菜鸟落进了聊天群，满屏都是程序汉，谁修bug谁丢魂

**Comment by ljh15191849190** [comment]
从爱国问题已经上升到宗教问题了

**Comment by ZeddG93** [comment]
洗涤NMSL

**Comment by HtHuanChen** [comment]
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. 

这东西都没人看的吗。（挠头）

**Comment by pdsuysk** [comment]
开源，的确是爱用不用，没责任。
但是，大家因为相信才用，作为一个企业在没通知用户的前提下擅自加入，项目无关的后门程序。无论是什么都让人有些担心或后怕吧。
今天加的是彩蛋，明天如果加炸弹呢？

**Comment by XiaoxuanDemo** [comment]
> 科普一下：
> 为什么涉及宗教?圣诞节是基督教节日
> 
> 这帖子貌似很多人点unlike，估计都是被领导逼着改掉这个彩蛋的人，多了很多的工作，压力大，又不敢喷那群那假正经的人，只敢喷ant-design，可以理解

我觉得也是别人开源出来给你提供思路，这些伸手党 拿来都不带研究的 出问题怪谁，别人又没强制你用

**Comment by hugetiny** [comment]
本人跟阿里没有任何关系，也从未在阿里就职，目前自己创业中

**Comment by afc163** [comment]
Duplicate of #13848

**Comment by shaopeng1** [comment]
完全同意，本来就是一群搞技术的，非要把技术问题上升到宗教，爱国上面是不应该的。

**Comment by ChinaHDJ** [comment]
老哥好厉害。问题都讨论到宗教信仰层面了。

**Comment by zhengjianqiao** [comment]
使用你的开源代码，是因为信任你。
如果在开发环境你给我这样的彩蛋，我很开心。
但是我不希望出现在线上环境。
希望antd不要辜负我们的信任。

**Comment by Eusen** [comment]
> > 强制别人用，跟囚禁有区别么，强迫别人做别人不喜欢做的事，你还觉得挺骄傲？
> 
> 免费的东西, 谁强制你用了? antdesign 开发团队强制你用antd了么

你脑子里是有屎吗？我说强制我用antd了？我是说强制用这个菜单！
而且这特么跟政府一点关系没有。如果这放到伊斯兰教的国家，可是会死人的兄弟。

**Comment by xhuihui** [comment]
围观

**Comment by jason19659** [comment]
> 开源，的确是爱用不用，没责任。
> 但是，大家因为相信才用，作为一个企业在没通知用户的前提下擅自加入，项目无关的后门程序。无论是什么都让人有些担心或后怕吧。
> 今天加的是彩蛋，明天如果加炸弹呢？

你这没看出来吗？就是不想让你用了啊。

**Comment by jdzchao** [comment]
我就是来看看有没有人要去见真主安拉的

**Comment by nerososft** [comment]
> 开源，的确是爱用不用，没责任。
> 但是，大家因为相信才用，作为一个企业在没通知用户的前提下擅自加入，项目无关的后门程序。无论是什么都让人有些担心或后怕吧。
> 今天加的是彩蛋，明天如果加炸弹呢？

会有炸弹嘛, 不要故意放大, 开发者觉得很有意思就加了, 他没必要对别人的项目负责把, 别人的项目跟他利益不相关吧

**Comment by hugetiny** [comment]
> 开源，的确是爱用不用，没责任。
> 但是，大家因为相信才用，作为一个企业在没通知用户的前提下擅自加入，项目无关的后门程序。无论是什么都让人有些担心或后怕吧。
> 今天加的是彩蛋，明天如果加炸弹呢？

那你可以不用

**Comment by KiritoLiuyhSky** [comment]
又开始舔了？既然是开源的，为什么说明文档里面没有提示，彩蛋是给用户的，不是给开发者炸弹

**Comment by nerososft** [comment]
> > > 强制别人用，跟囚禁有区别么，强迫别人做别人不喜欢做的事，你还觉得挺骄傲？
> > 
> > 
> > 免费的东西, 谁强制你用了? antdesign 开发团队强制你用antd了么
> 
> 你脑子里是有屎吗？我说强制我用antd了？我是说强制用这个彩蛋！
> 而且这特么跟政府一点关系没有。如果这放到伊斯兰教的国家，可是会死人的兄弟。
其实更多的是团队对于技术的一腔热爱才有了这个优秀的开源产品,
伊斯兰教,这个可能真的是作者没考虑到, 如果真的要考虑那么多, 那估计没有这么优秀的开源作品了.

**Comment by HtHuanChen** [comment]
> 使用你的开源代码，是因为信任你。
> 如果在开发环境你给我这样的彩蛋，我很开心。
> 但是我不希望出现在线上环境。
> 希望antd不要辜负我们的信任。

别把伸手说的那么好听呀亲，起码要看一遍源码吧。

**Comment by millionbug** [comment]
如果在开发环境的话，肯定还会截图发到v2ex上大家喜乐一番，觉得有趣。 问题是什么都不知道，突然线上多了个这个东西，很多都是正式线上项目，第一反应都是：这是什么鬼。 尺度拿捏好才是玩笑，拿捏不好就是神经病。

**Comment by nakating** [comment]
楼主的思路清晰啊！点个赞！

咱不才引申一下，您看理解的对不对：

我都给你免费杀毒了，偷你点东西怎么了？
快递我帮你签的，吃你几块怎么了？ 
是我把光纤拉到你家的，放点广告怎么了？

**Comment by gilbert-yuan** [comment]
别人的项目，人家想怎么改怎么改。不喜欢可以不用。

**Comment by nerososft** [comment]
> 楼主的思路清晰啊！点个赞！
> 
> 咱不才引申一下，您看理解的对不对：
> 
> 我都给你免费杀毒了，偷你点东西怎么了？
> 快递我帮你签的，吃你几块怎么了？
> 是我把光纤拉到你家的，放点广告怎么了？
其实更多的是团队对于技术的一腔热爱才有了这个优秀的开源产品,真的没有想那么多

**Comment by XiaoxuanDemo** [comment]
> > 使用你的开源代码，是因为信任你。
> > 如果在开发环境你给我这样的彩蛋，我很开心。
> > 但是我不希望出现在线上环境。
> > 希望antd不要辜负我们的信任。
> 
> 别把伸手说的那么好听呀亲，起码要看一遍源码吧。

完全同意，这些人 用的时候爽了 涨工资拿奖金的时候你怎么没想到作者？出问题了就要找作者背锅？

**Comment by hugetiny** [comment]
> 楼主的思路清晰啊！点个赞！
> 
> 咱不才引申一下，您看理解的对不对：
> 
> 我都给你免费杀毒了，偷你点东西怎么了？
> 快递我帮你签的，吃你几块怎么了？
> 是我把光纤拉到你家的，放点广告怎么了？

所以圣诞节彩蛋是偷你，吃你，还是放广告了？

**Comment by Eusen** [comment]
> > > > 强制别人用，跟囚禁有区别么，强迫别人做别人不喜欢做的事，你还觉得挺骄傲？
> > > 
> > > 
> > > 免费的东西, 谁强制你用了? antdesign 开发团队强制你用antd了么
> > 
> > 
> > 你脑子里是有屎吗？我说强制我用antd了？我是说强制用这个彩蛋！
> > 而且这特么跟政府一点关系没有。如果这放到伊斯兰教的国家，可是会死人的兄弟。
> > 其实更多的是团队对于技术的一腔热爱才有了这个优秀的开源产品,
> > 伊斯兰教,这个可能真的是作者没考虑到, 如果真的要考虑那么多, 那估计没有这么优秀的开源作品了.

照你这话，那Google，微软，linux，Apache 那些开源项目就不是一群人怀着一腔热爱写的？就没考虑过各个国家的人？？？

**Comment by nerososft** [comment]
> > > > > 强制别人用，跟囚禁有区别么，强迫别人做别人不喜欢做的事，你还觉得挺骄傲？
> > > > 
> > > > 
> > > > 免费的东西, 谁强制你用了? antdesign 开发团队强制你用antd了么
> > > 
> > > 
> > > 你脑子里是有屎吗？我说强制我用antd了？我是说强制用这个彩蛋！
> > > 而且这特么跟政府一点关系没有。如果这放到伊斯兰教的国家，可是会死人的兄弟。
> > > 其实更多的是团队对于技术的一腔热爱才有了这个优秀的开源产品,
> > > 伊斯兰教,这个可能真的是作者没考虑到, 如果真的要考虑那么多, 那估计没有这么优秀的开源作品了.
> 
> 照你这话，那Google，微软，linux，Apache 那些开源项目就不是一群人怀着一腔热爱写的？就没考虑过各个国家的人？？？

对

**Comment by Eusen** [comment]
@nerososft 我劝你闭嘴吧，真的，别恶心大家了。。。你真是越抹越黑。。。

**Comment by nerososft** [comment]
> > > > > 强制别人用，跟囚禁有区别么，强迫别人做别人不喜欢做的事，你还觉得挺骄傲？
> > > > 
> > > > 
> > > > 免费的东西, 谁强制你用了? antdesign 开发团队强制你用antd了么
> > > 
> > > 
> > > 你脑子里是有屎吗？我说强制我用antd了？我是说强制用这个彩蛋！
> > > 而且这特么跟政府一点关系没有。如果这放到伊斯兰教的国家，可是会死人的兄弟。
> > > 其实更多的是团队对于技术的一腔热爱才有了这个优秀的开源产品,
> > > 伊斯兰教,这个可能真的是作者没考虑到, 如果真的要考虑那么多, 那估计没有这么优秀的开源作品了.
> 
> 照你这话，那Google，微软，linux，Apache 那些开源项目就不是一群人怀着一腔热爱写的？就没考虑过各个国家的人？？？

伸手党是体验不到的

**Comment by Mr-xue** [comment]
> 本人跟阿里没有任何关系，也从未在阿里就职，目前自己创业中

假如你们公司开发了一款产品，服务于几百万用户，过万家企业，各行各业的企业都有。突然产品里面的所有按钮莫名其妙的被雪花遮住一块。 你好好想一下后果？ 如果你想不明白，你还是别创业了。    如果你想明白了，你回头再看看你发的。

**Comment by xhuihui** [comment]
跪舔的这么开心吗？

**Comment by nerososft** [comment]
> > 本人跟阿里没有任何关系，也从未在阿里就职，目前自己创业中
> 
> 假如你们公司开发了一款产品，服务于几百万用户，过万家企业，各行各业的企业都有。突然产品里面的所有按钮莫名其妙的被雪花遮住一块。 你好好想一下后果？ 如果你想不明白，你还是别创业了。 如果你想明白了，你回头再看看你发的。

那你自己写一个嘛

**Comment by Eusen** [comment]
> > > 本人跟阿里没有任何关系，也从未在阿里就职，目前自己创业中
> > 
> > 
> > 假如你们公司开发了一款产品，服务于几百万用户，过万家企业，各行各业的企业都有。突然产品里面的所有按钮莫名其妙的被雪花遮住一块。 你好好想一下后果？ 如果你想不明白，你还是别创业了。 如果你想明白了，你回头再看看你发的。
> 
> 那你自己写一个嘛

拜托，你以为写一个很难吗？

**Comment by aoeiuvb** [comment]
看来程序猿工作都很不饱和阿

**Comment by Eusen** [comment]
> > > 本人跟阿里没有任何关系，也从未在阿里就职，目前自己创业中
> > 
> > 
> > 假如你们公司开发了一款产品，服务于几百万用户，过万家企业，各行各业的企业都有。突然产品里面的所有按钮莫名其妙的被雪花遮住一块。 你好好想一下后果？ 如果你想不明白，你还是别创业了。 如果你想明白了，你回头再看看你发的。
> 
> 那你自己写一个嘛

像你这种人，请别用github，请你自己写一个。

**Comment by ixsword** [comment]
说加炸弹的确实有点放大，但是开源这东西，你们本身就太依赖，按理说，你们要自己审核开源代码，如果不是不公开的高速你彩蛋还叫彩蛋吗？

**Comment by demonstration** [comment]
> > > > 使用你的开源代码，是因为信任你。
> > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > 但是我不希望出现在线上环境。
> > > > 希望antd不要辜负我们的信任。
> > > 
> > > 
> > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > 
> > 
> > 老哥你把Linux源码看完了吗？
> 
> 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？

笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？

**Comment by ixsword** [comment]
> > > > > 使用你的开源代码，是因为信任你。
> > > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > > 但是我不希望出现在线上环境。
> > > > > 希望antd不要辜负我们的信任。
> > > > 
> > > > 
> > > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > > 
> > > 
> > > 老哥你把Linux源码看完了吗？
> > 
> > 
> > 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？
> 
> 笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？

如果BAT对Linux二次开发然后拿来挣钱。绝逼会查看linux的每次更新，哪怕只是改个printf都要检查是否影响重大！

**Comment by Eusen** [comment]
> > > > > > 使用你的开源代码，是因为信任你。
> > > > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > > > 但是我不希望出现在线上环境。
> > > > > > 希望antd不要辜负我们的信任。
> > > > > 
> > > > > 
> > > > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > > > 
> > > > 
> > > > 老哥你把Linux源码看完了吗？
> > > 
> > > 
> > > 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？
> > 
> > 
> > 笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？
> 
> 如果BAT对Linux二次开发然后拿来挣钱。绝逼会查看linux的每次更新，哪怕只是改个printf都要检查是否影响重大！

linux 多久更一次？前端框架多久更一次?

**Comment by hugetiny** [comment]
程序员逻辑思维应该都相对很强了，但是很多评论基本的逻辑都没有。怎么科普呢？简单的说还是：
开源免费，爱用不用

**Comment by Eusen** [comment]
@ixsword 你以为大家都是机器人？

**Comment by Eusen** [comment]
> 程序员逻辑思维应该都相对很强了，但是很多评论基本的逻辑都没有。怎么科普呢？简单的说还是：
> 开源免费，爱用不用

从来没有一个开源项目强制大家一起过一个节日，如果是这样，这个开源项目未免也牛逼了吧。你这不要脸的精神也让人很是佩服。

**Comment by demonstration** [comment]
> > > > > > 使用你的开源代码，是因为信任你。
> > > > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > > > 但是我不希望出现在线上环境。
> > > > > > 希望antd不要辜负我们的信任。
> > > > > 
> > > > > 
> > > > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > > > 
> > > > 
> > > > 老哥你把Linux源码看完了吗？
> > > 
> > > 
> > > 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？
> > 
> > 
> > 笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？
> 
> 如果BAT对Linux二次开发然后拿来挣钱。绝逼会查看linux的每次更新，哪怕只是改个printf都要检查是否影响重大！

典型的“你行你上啊，不行别BB”逻辑，我使用Linux也要像BAT一样把它源码都通读一遍？你工作开发中没用过开源项目？你用的每一个开源项目都通读人家源码了吗？而且，这次彩蛋在更新里说明了吗？作者完全是隐藏代码，逃避责任，错了就是错了，不要像个巨婴一样，说你两句还来脾气。。。

**Comment by ixsword** [comment]
> > > > > > > 使用你的开源代码，是因为信任你。
> > > > > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > > > > 但是我不希望出现在线上环境。
> > > > > > > 希望antd不要辜负我们的信任。
> > > > > > 
> > > > > > 
> > > > > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > > > > 
> > > > > 
> > > > > 老哥你把Linux源码看完了吗？
> > > > 
> > > > 
> > > > 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？
> > > 
> > > 
> > > 笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？
> > 
> > 
> > 如果BAT对Linux二次开发然后拿来挣钱。绝逼会查看linux的每次更新，哪怕只是改个printf都要检查是否影响重大！
> 
> 典型的“你行你上啊，不行别BB”逻辑，我使用Linux也要像BAT一样把它源码都通读一遍？你工作开发中没用过开源项目？你用的每一个开源项目都通读人家源码了吗？而且，这次彩蛋在更新里说明了吗？作者完全是隐藏代码，逃避责任，错了就是错了，不要像个巨婴一样，说你两句还来脾气。。。

没错，是没考虑周全，但是如果过年的时候我还想弄个菜单咋办。。。你还用不用ant-design？你还看不看提交？

**Comment by Mrcxt** [comment]
怎么举报 ~这条狗~ 啊不，是这条作者啊。

**Comment by ixsword** [comment]
> > > > > > > 使用你的开源代码，是因为信任你。
> > > > > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > > > > 但是我不希望出现在线上环境。
> > > > > > > 希望antd不要辜负我们的信任。
> > > > > > 
> > > > > > 
> > > > > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > > > > 
> > > > > 
> > > > > 老哥你把Linux源码看完了吗？
> > > > 
> > > > 
> > > > 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？
> > > 
> > > 
> > > 笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？
> > 
> > 
> > 如果BAT对Linux二次开发然后拿来挣钱。绝逼会查看linux的每次更新，哪怕只是改个printf都要检查是否影响重大！
> 
> 典型的“你行你上啊，不行别BB”逻辑，我使用Linux也要像BAT一样把它源码都通读一遍？你工作开发中没用过开源项目？你用的每一个开源项目都通读人家源码了吗？而且，这次彩蛋在更新里说明了吗？作者完全是隐藏代码，逃避责任，错了就是错了，不要像个巨婴一样，说你两句还来脾气。。。

过年我再弄个猪年大吉，按钮都有头猪，咋办，你是不是要疯了，是不是要放弃ant-design，哈哈

**Comment by Eusen** [comment]
> 怎么举报 这条狗 啊不，是这条作者啊。

我也想举报

**Comment by ProgramLife** [comment]
如果linux也放彩蛋，把你线上服务搞蹦了，你自己是不是去开发了一款操作系统？

**Comment by demonstration** [comment]
> > > > > > > > 使用你的开源代码，是因为信任你。
> > > > > > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > > > > > 但是我不希望出现在线上环境。
> > > > > > > > 希望antd不要辜负我们的信任。
> > > > > > > 
> > > > > > > 
> > > > > > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > > > > > 
> > > > > > 
> > > > > > 老哥你把Linux源码看完了吗？
> > > > > 
> > > > > 
> > > > > 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？
> > > > 
> > > > 
> > > > 笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？
> > > 
> > > 
> > > 如果BAT对Linux二次开发然后拿来挣钱。绝逼会查看linux的每次更新，哪怕只是改个printf都要检查是否影响重大！
> > 
> > 
> > 典型的“你行你上啊，不行别BB”逻辑，我使用Linux也要像BAT一样把它源码都通读一遍？你工作开发中没用过开源项目？你用的每一个开源项目都通读人家源码了吗？而且，这次彩蛋在更新里说明了吗？作者完全是隐藏代码，逃避责任，错了就是错了，不要像个巨婴一样，说你两句还来脾气。。。
> 
> 过年我再弄个猪年大吉，按钮都有头猪，咋办，你是不是要疯了，是不是要放弃ant-design，哈哈

首先，我为你不是ant-design的开发成员感到庆幸，因为如果蚂蚁金服的开发人员像您这么幼稚不成熟的话，他家早就倒闭了，根本没资格，也别说还继续开源什么前端框架；一个负责的团队和公司一定会对自己的行为作出合理的解释和道歉；阿里的公关团队一向不错，不过也该管管自家的git了。

**Comment by ixsword** [comment]
作者完全是隐藏代码，逃避责任，我想他不是想逃避责任，不然也不会道歉，提交的时候没说明提交内容是不对的，绝大部分人不会去看全部代码，而且也很少看提交内容，但是是不是也给自己上了一课，不是责问阿里员工为什么这样做，而是问问自己以后怎么预防

**Comment by CasparLi** [comment]
> > > > > > > > 使用你的开源代码，是因为信任你。
> > > > > > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > > > > > 但是我不希望出现在线上环境。
> > > > > > > > 希望antd不要辜负我们的信任。
> > > > > > > 
> > > > > > > 
> > > > > > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > > > > > 
> > > > > > 
> > > > > > 老哥你把Linux源码看完了吗？
> > > > > 
> > > > > 
> > > > > 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？
> > > > 
> > > > 
> > > > 笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？
> > > 
> > > 
> > > 如果BAT对Linux二次开发然后拿来挣钱。绝逼会查看linux的每次更新，哪怕只是改个printf都要检查是否影响重大！
> > 
> > 
> > 典型的“你行你上啊，不行别BB”逻辑，我使用Linux也要像BAT一样把它源码都通读一遍？你工作开发中没用过开源项目？你用的每一个开源项目都通读人家源码了吗？而且，这次彩蛋在更新里说明了吗？作者完全是隐藏代码，逃避责任，错了就是错了，不要像个巨婴一样，说你两句还来脾气。。。
> 
> 没错，是没考虑周全，但是如果过年的时候我还想弄个菜单咋办。。。你还用不用ant-design？你还看不看提交？

我觉得你可以弄个挖矿脚本

**Comment by qianlishun** [comment]
> > 怎么举报 这条狗 啊不，是这条作者啊。
> 
> 我也想举报

https://github.com/contact/report-abuse?report=hugetiny+%28user%29

Publish abusive and discriminatory remarks in the community

**Comment by demonstration** [comment]
> 作者完全是隐藏代码，逃避责任，我想他不是想逃避责任，不然也不会道歉，提交的时候没说明提交内容是不对的，绝大部分人不会去看全部代码，而且也很少看提交内容，但是是不是也给自己上了一课，不是责问阿里员工为什么这样做，而是问问自己以后怎么预防

说作者“隐藏代码，逃避责任”可能确实话重了些，作者初衷也是无心之过，没想到会产生很大的反响；网络上一堆水军瞎喷作者，那是水军的问题，但是作者作为大公司大团队开源组件的开发人员，就得有一定的肚量去接受这次教训，即便受气了，也得兜着受着，所谓成长就是这么个事。

**Comment by hugetiny** [comment]
说到底还是中国人的奴性：
一堆人因为开源框架的彩蛋工作增加了，或者有丢工作的危险了，所以不爽，
不爽也不能骂什么都不懂的领导，
也不能骂本来就没什么影响还谴责你留后门的政府事业单位客户，
来骂一骂ant-design泄愤不需要付出什么代价，就骂ant-design
这群人对于法不法治，合不合理没关系，只要不影响赚钱，骂骂出口气继续当狗也好。
我不选择当狗，所以现在自己出来创业了

**Comment by yatokami** [comment]
> > > > > > > > 使用你的开源代码，是因为信任你。
> > > > > > > > 如果在开发环境你给我这样的彩蛋，我很开心。
> > > > > > > > 但是我不希望出现在线上环境。
> > > > > > > > 希望antd不要辜负我们的信任。
> > > > > > > 
> > > > > > > 
> > > > > > > 别把伸手说的那么好听呀亲，起码要看一遍源码吧。
> > > > > > 
> > > > > > 
> > > > > > 老哥你把Linux源码看完了吗？
> > > > > 
> > > > > 
> > > > > 您用Linux二次开发挣钱吗，嗯？能严谨点吗？能对您的客户们负责点吗？
> > > > 
> > > > 
> > > > 笑话，BAT的服务器不用Linux？BAT不对Linux二次开发？BAT不挣钱？
> > > 
> > > 
> > > 如果BAT对Linux二次开发然后拿来挣钱。绝逼会查看linux的每次更新，哪怕只是改个printf都要检查是否影响重大！
> > 
> > 
> > 典型的“你行你上啊，不行别BB”逻辑，我使用Linux也要像BAT一样把它源码都通读一遍？你工作开发中没用过开源项目？你用的每一个开源项目都通读人家源码了吗？而且，这次彩蛋在更新里说明了吗？作者完全是隐藏代码，逃避责任，错了就是错了，不要像个巨婴一样，说你两句还来脾气。。。
> 
> 过年我再弄个猪年大吉，按钮都有头猪，咋办，你是不是要疯了，是不是要放弃ant-design，哈哈

所以说你这种就是学生吧无脑舔？开源不是代表自由，使用他是因为相信他，这次的问题很难改吗，其实出了问题大部分前端都可以通过修改源码修正，你放个猪头我直接修改源码不就没了吗，这次问题是暴露出了信任危机，上面说的放炸弹是过了但是真的可能因为一些严重的行为你没通过log展示你改动这不是影响使用者？还有前端代码更迭较快大家不可能每次都去源码不然要changelog干嘛。我们使用这个框架就是用户我们难道还不能对产品有质疑？而且受到这么多用户的投诉你还觉得这次事件没问题，别说过你们这些人没吐槽过免费使用的东西？对于企业级应用来说最主要的是一个信用问题。建议你还是好好多读几年书吧。

**Comment by Eusen** [comment]
> > > 说到底还是中国人的奴性：
> > > 一堆人因为开源框架的彩蛋工作增加了，或者有丢工作的危险了，所以不爽，
> > > 不爽也不能骂什么都不懂的领导，
> > > 也不能骂本来就没什么影响还谴责你留后门的政府事业单位客户，
> > > 来骂一骂ant-design泄愤不需要付出什么代价，就骂ant-design
> > > 这群人对于法不法治，合不合理没关系，只要不影响赚钱，骂骂出口气继续当狗也好。
> > > 我不选择当狗，所以现在自己出来创业了
> > 
> > 
> > 我们说antd是为了这个项目未来能健康发展，跟踏马的奴性有个屁关系？
> > 我们更看重这件事对这个antd的影响，而不是对那些项目的影响。
> > 所以拜托别把自己标榜地很清高，就您这情/智商还创业，希望您别赔太惨。
> 
> 来来来我们加个群接着慢慢聊。哈哈哈哈。322042395

不好意思，不屑与你们为伍。

**Comment by hugetiny** [comment]
有一点的确要更正，客户不仅仅是政府，还有事业单位和各种企业。我刚开始听到新闻都是政府事业单位的，这点不能以偏概全

**Comment by yatokami** [comment]
nb啊可以举报这个题主了

**Comment by hugetiny** [comment]
请尽情举报

**Comment by yatokami** [comment]
算了反正你这个很快就没了和你这种人计较浪费力气

**Comment by Cai-Wencong** [comment]
战🐺、五毛和小粉红还有30秒到达战场
