### ISSUE TITLE
upload组件获取不到文件信息

### ISSUE THREAD

**Issue by yayamommy** [ant-design/ant-design#1387]
action设为自己后台请求地址后，调试跟踪到这个方法后，方法的参数MultipartFile filedata，filedata为null，没获取到文件信息。后台怎么获取文件信息

**Comment by afc163** [comment]
Node 下的获取方式可以参考：

https://github.com/react-component/upload/blob/52683cd8a7e6c638364615203a03247233db5016/server-fn.js#L15

https://github.com/ant-design/ant-design/blob/8b98ce682d45f5e3acc0cea3b53a3827f65c262d/nico.js#L67

其他后端语言建议研究：https://github.com/blueimp/jQuery-File-Upload/wiki#server-side
