### ISSUE TITLE
Antd 3.11.6 Table has one more column and first column style disorder

### ISSUE THREAD

**Issue by loveyoubaby5120** [ant-design/ant-design#13879]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
windows: Chrome 版本 62.0.3202.94 （32 bit）; firefox 64.0（32 bit） 2017.02;

### Reproduction link
[https://github.com/ant-design](https://github.com/ant-design)

### Steps to reproduce
Table Fixed column

### What is expected?
Don't have ont more column and style to normal

### What is actually happening?
Table has one more column and first column style disorder in windows，It's normal on a MAC

![551545727967_ pic_hd](https://user-images.githubusercontent.com/11256291/50418562-029ce080-0867-11e9-8366-ab317dbede21.jpg)

**Comment by afc163** [comment]
合并到 #13825
