### ISSUE TITLE
表头分组后列于表头不会对齐

### ISSUE THREAD

**Issue by jianhuatu** [ant-design/ant-design#13876]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
官方示例

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-grouping-columns](https://ant.design/components/table-cn/#components-table-demo-grouping-columns)

### Steps to reproduce
官方样例

### What is expected?
表格分组后列与表头对齐。

### What is actually happening?
表头与列不对齐。

---
使用表格分组同时固定列，发现列与表头不对齐，这个问题在使用3.10.1的时候没发现，升级到3.11.6最新版后发现问题比较严重，查看官方示例后发现有同样的问题（列比较少，没对齐的部分比较小）。

**Comment by afc163** [comment]
Duplicate of #13825
