### ISSUE TITLE
textArea行高自适应有问题

### ISSUE THREAD

**Issue by wiyhvs** [ant-design/ant-design#13885]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.3

### Environment
window10  chrome浏览器

### Reproduction link
[https://ant-design.gitee.io/components/input-cn/](https://ant-design.gitee.io/components/input-cn/)

### Steps to reproduce
首先复制一端文本，每一行尽量长一点，然后直接拷贝到文本域里面，因为文本域的自动换行导致行数变多但是文本域的高度没有对应的增加，所以就会显示不完全

### What is expected?
期望能够正确显示

### What is actually happening?
实际显示不完全，下面的一部分看不见，尤其是在禁用情况下，都不能通过光标的位置来移动

**Comment by zombieJ** [comment]
能给个重现步骤吗？我看官网是好的。

**Comment by redheart47** [comment]
我就是看的官网，使用的firefox 64位最新的浏览器，然后查看其它使用该框架的项目也是同样的问题，该不会是我电脑系统导致的吧，我的widows 10 企业版，64位的

发送自 Windows 10 版邮件应用

发件人: zombieJ
发送时间: 2018年12月25日 20:56
收件人: ant-design/ant-design
抄送: Subscribed
主题: Re: [ant-design/ant-design] textArea行高自适应有问题 (#13885)

能给个重现步骤吗？我看官网是好的。

**Comment by zombieJ** [comment]
@wellenzhong 给个[重现](https://u.ant.design/codesandbox)吧，这样好定位问题。

**Comment by ztplz** [comment]
你点下加载不就好了吗。。。

**Comment by wellenzhong** [comment]
> 你点下加载不就好了吗。。。

不单单是这个问题。。。

**Comment by zombieJ** [comment]
是网络问题吗？可以给个 git 看一下吗？

**Comment by wellenzhong** [comment]
> 是网络问题吗？可以给个 git 看一下吗？

居然[重现不了](https://codesandbox.io/s/1qj7loynj4),版本也和我用的版本一致。
不过错误显示是这样子的：
![](http://div.wiki/images/bug.png)

**Comment by wellenzhong** [comment]
找到了，sorry,是被其他同事重设了样式。

**Comment by wellenzhong** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Version
> 3.10.3
> 
> ### Environment
> window10 chrome浏览器
> 
> ### Reproduction link
> https://ant-design.gitee.io/components/input-cn/
> 
> ### Steps to reproduce
> 首先复制一端文本，每一行尽量长一点，然后直接拷贝到文本域里面，因为文本域的自动换行导致行数变多但是文本域的高度没有对应的增加，所以就会显示不完全
> 
> ### What is expected?
> 期望能够正确显示
> 
> ### What is actually happening?
> 实际显示不完全，下面的一部分看不见，尤其是在禁用情况下，都不能通过光标的位置来移动

我觉得是你们重设了全局样式影响了。
文字超高时，textarea右边会出现滚动条的。
