### ISSUE TITLE
I tried to add React Fragment into Collapse component and it break the design

### ISSUE THREAD

**Issue by atherdon** [ant-design/ant-design#13884]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
Linux, Chrome

### Reproduction link
[https://codesandbox.io/s/m4r79ojy5p](https://codesandbox.io/s/m4r79ojy5p)

### Steps to reproduce
I tried to split up Collapse component into few components with loop. and use <Fragment> tag. After that - this element didn't look as before.

### What is expected?
With or without Fragment tag - Collapse should looks the same after render

### What is actually happening?
it's generate an html with "undefined" values at classes.

**Comment by atherdon** [comment]
@afc163 i'm still having issues with Fragment.
I updated a bit my sandbox(by adding more fragments as wrappers). Please, advice - is this is an error or I making it harder?

**Comment by atherdon** [comment]
maybe @ztplz as developer of this update can help...

**Comment by ztplz** [comment]
@atherdon  Current version does not seem to update the collapse.
![image](https://user-images.githubusercontent.com/17755202/50735611-07f61580-11ed-11e9-8b91-3c18f72e3afb.png)
![image](https://user-images.githubusercontent.com/17755202/50735614-0f1d2380-11ed-11e9-8b6e-f969793e620e.png)

**Comment by atherdon** [comment]
got it, i think you right. I just saw visual changes at the sandbox and
assume that your code was added to release too. btw, thank you for
clarification and your time - really appreciate it

>

**Comment by atherdon** [comment]
please notify me when it'll be published online, or maybe we should open this issue

**Comment by atherdon** [comment]
@ztplz  at my project I have not the same display result, but yeah - looks like it wasn't updated at the last releases...

**Comment by erguotou520** [comment]
Same issue here, the `Panel` content won't renderer in `Fragment`.

**Comment by ztplz** [comment]
Not a high priority, we still need to do a lot of things if we fully support `Fragment`.

**Comment by atherdon** [comment]
I propose at least to open this issue - so people can be aware about this
problem

>

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/collapse/commit/2e4748d00d51d3299906b0ca74111eb0cec0569b
