### ISSUE TITLE
[List Component] Pagination with Simple=true input not work

### ISSUE THREAD

**Issue by ChiQianBingYue** [ant-design/ant-design#13889]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8y119xknrj)

### Steps to reproduce
goto pagination and input any page

### What is expected?
pagination should change to what I input

### What is actually happening?
the default page not change at all

**Comment by drawing-snail** [comment]
I'm sorry, I only speak Chinese
我想知道为什么昨天彩蛋修复之后 Pagination组件全部默认为英文了，咋改回来

**Comment by ChiQianBingYue** [comment]
3.11.2 版本好像升级了rc-pagination，按我上面的方法应该螚回退到之前的版本。然后圣诞菜单用官方给出的非升级方法修复就好吧

**Comment by zombieJ** [comment]
@ChiQianBingYue ,
的确是 rc-pagination 的问题，我修一下。 thx

**Comment by MakarovAV** [comment]
Still an issue for now =(

**Comment by zombieJ** [comment]
> Still an issue for now =(

Remove `node_modules` and reinstall. If lock file exist, delete also.

**Comment by MakarovAV** [comment]
> > Still an issue for now =(
> 
> Remove `node_modules` and reinstall. If lock file exist, delete also.

Sorry, it was probably my misunderstanding.
I expected pagination to react on input blur, or on input change. Not on pressing enter only.
Is there any way provided by library, to achieve this behavior?

**Comment by zombieJ** [comment]
You can ref this: #14819
