### ISSUE TITLE
求教实现table，行按钮事件处理

### ISSUE THREAD

**Issue by zsj1029** [ant-design/ant-design#1388]
一个table多行数据，每行有个编辑按钮
点击编辑，我想弹出modal来修改行数据

不知道该怎么写了，对react理解不深，现在table数据能看到了
因为按钮是写在columns 的数组对象里的，写按钮的onClick事件

`const getOne = ((record)=>{
    console.log(record);
})
const columns = [{
    title: '操作',
    key: 'p_id',
    render(text, record) {
        return (
            <span>
                <a href="#" onClick={getOne(record)}>修改</a>
                <span className="ant-divider"></span>
                <a href="#">删除</a>
            </span>
        );
    }
}]`

结果第一次渲染的时候，table所有数据都被打印了，单独点击修改按钮无效

求教因该如何实现，我觉得我的思路有问题，还是按照常规数据加载去思考

请指导一下谢谢了

**Comment by zsj1029** [comment]
看到之前其他朋友相同的问题，我自行研究吧，谢谢了

**Comment by zsj1029** [comment]
还是不幸啊，😢
真心求教
还有问题 我想把getOne 方法写到 组件里面怎么办？ 我用的es6 自定义了一个ProductTable组件，里面用的ant的table ，还有columns对象数组，好像只能写在ProductTable组件外面

**Comment by codering** [comment]
onClick={getOne}

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1184
https://github.com/ant-design/ant-design/issues/1154

**Comment by RifeWang** [comment]
@zsj1029 我现在有相同的问题，请问你怎么解决的？

**Comment by weiyy2012** [comment]
我最近一直做table相关的东西，以下代码希望可以帮助您
    const columns = _.isEmpty(tableHeader) ? [] : [
      ...tableHeader,
      {
        title: '操作',
        key: 'operation',
        width: '100px',
        render: (text, record, index) => {
          return <div>  
            <Button type="primary" onClick={that.updateFunc.bind(this,{
              id: record.id,
            })}>
              修改
            </Button>　
            <Popconfirm title="确定要删除吗？" onConfirm={that.handleDeleteConfirm.bind(this, {
              data_id: record.id,
              table_id: store.table_id,
            })}>
              <Button>删除</Button>
            </Popconfirm>
          </div>  
        }
      } 
    ];

**Comment by chenyizhongx** [comment]
onClick内也可以使用箭头函数，提供另外的思路供参考，希望有帮助
```
const tableColumn = [{
  title: ' 操作',
  align: 'center',
  render: (text, records, index) => { 
     return (
        <Button type="ghost"
            className='button-row'
            onClick={() => this.showClazz(records, index)}
         >
            查看课程
         </Button>
      )
   }
}]
```
records可以直接拿到该行的数据
