### ISSUE TITLE
InputNumber组件undefined的问题

### ISSUE THREAD

**Issue by jszjgqq** [ant-design/ant-design#13896]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
Win10 X64、Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m70qvk29p9)

### Steps to reproduce
1.鼠标点到输入框，删除1，按回车
    此步骤出现的结果：可以看到有表单提交值，只是nums为空罢了
2.然后让输入框先失去焦点，再点击“提交”，或者直接点击“提交”。
    此步骤出现的结果：此时表单提交值就没了，同时注意值的类型也变成了undefined了。

### What is expected?
不管怎么操作，只要一开始输入框有值，哪怕删掉了值，也不能出现undefined，换句话说 想要重现步骤1中的结果，不想要2的结果。

### What is actually happening?
实际输入框默认有值，然后把值删掉，提交表单，字段相关值并不会提交，因为undefined类型并不会提交给接口，
这就意味着用户想修改值的时候，一直都无法修改（无法改成空值）；
虽说在表单提交的时候也能判断是否为undefined，但是这么做感觉很不爽，如果页面有很多InputNumber组件的话，代码全是if else判断了，虽说也能用遍历，写一个if else，但就是不爽，感觉也不科学啊。

---
Hope to solve it ASAP, THKS....

**Comment by afc163** [comment]
https://codesandbox.io/s/0mvk17n01n

看了下代码，应该是 codesandbox 的例子有误。如果用 `getFieldDecorator` 包裹了控件，则不再需要用 onChange 和 this.setState 进行绑定，`getFieldDecorator` 自己已经做了。

去掉了 `initialValue: this.state.value` 之后的表现是，上述两种交互，提交后都是 `nums: undefined`。为什么不是编辑过程中的 `''`，这是因为 InputNumber 被设计成输入状态时返回 string（这样可以输入任意字符，保证输入的自由度），blur 后统一规整成正确的 Number 类型，这样能保证 blur 后调用的 onChange 返回的是 `Number | undefined`。不知道这个解释说清楚了没，这个问题先关了，有其他疑问可以继续在此讨论。

**Comment by jszjgqq** [comment]
> https://codesandbox.io/s/0mvk17n01n
> 
> 看了下代码，应该是 codesandbox 的例子有误。如果用 `getFieldDecorator` 包裹了控件，则不再需要用 onChange 和 this.setState 进行绑定，`getFieldDecorator` 自己已经做了。
> 
> 去掉了 `initialValue: this.state.value` 之后的表现是，上述两种交互，提交后都是 `nums: undefined`。为什么不是编辑过程中的 `''`，这是因为 InputNumber 被设计成输入状态时返回 string（这样可以输入任意字符，保证输入的自由度），blur 后统一规整成正确的 Number 类型，这样能保证 blur 后调用的 onChange 返回的是 `Number | undefined`。不知道这个解释说清楚了没，这个问题先关了，有其他疑问可以继续在此讨论。

并没有什么变化，复现步骤里面1跟2的操作方式，展现的返回结果完全不一样，这就意味着用户没失焦前直接按下回车，跟失去焦点后点提交，后端服务器接收到的值完全是不一样的；

假设去掉`initialValue: this.state.value`后，表现的都是 `nums:undefined`也有问题，具体表现为用户无法修改为空值，如果进行判断是否为空再重新给对应字段赋值也挺麻烦的，比较理想的方式：如果一开始InpurtNumber中有内容，把内容删掉之后，如果判断为空，那么就是空，返回`undefined`需要开发者自行并不是太好。

**Comment by jszjgqq** [comment]
> > https://codesandbox.io/s/0mvk17n01n
> > 看了下代码，应该是 codesandbox 的例子有误。如果用 `getFieldDecorator` 包裹了控件，则不再需要用 onChange 和 this.setState 进行绑定，`getFieldDecorator` 自己已经做了。
> > 去掉了 `initialValue: this.state.value` 之后的表现是，上述两种交互，提交后都是 `nums: undefined`。为什么不是编辑过程中的 `''`，这是因为 InputNumber 被设计成输入状态时返回 string（这样可以输入任意字符，保证输入的自由度），blur 后统一规整成正确的 Number 类型，这样能保证 blur 后调用的 onChange 返回的是 `Number | undefined`。不知道这个解释说清楚了没，这个问题先关了，有其他疑问可以继续在此讨论。
> 
> 并没有什么变化，复现步骤里面1跟2的操作方式，展现的返回结果完全不一样，这就意味着用户没失焦前直接按下回车，跟失去焦点后点提交，后端服务器接收到的值完全是不一样的；
> 
> 假设去掉`initialValue: this.state.value`后，表现的都是 `nums:undefined`也有问题，具体表现为用户无法修改为空值，如果进行判断是否为空再重新给对应字段赋值也挺麻烦的，比较理想的方式：如果一开始InpurtNumber中有内容，把内容删掉之后，如果判断为空，那么就是空，返回`undefined`需要开发者自行并不是太好。
补一张GIF操作图。
![2](https://user-images.githubusercontent.com/2629994/50428057-c6ad5e00-08ee-11e9-97c3-142986aeda2e.gif)

**Comment by jszjgqq** [comment]
> https://codesandbox.io/s/0mvk17n01n
> 
> 看了下代码，应该是 codesandbox 的例子有误。如果用 `getFieldDecorator` 包裹了控件，则不再需要用 onChange 和 this.setState 进行绑定，`getFieldDecorator` 自己已经做了。
> 
> 去掉了 `initialValue: this.state.value` 之后的表现是，上述两种交互，提交后都是 `nums: undefined`。为什么不是编辑过程中的 `''`，这是因为 InputNumber 被设计成输入状态时返回 string（这样可以输入任意字符，保证输入的自由度），blur 后统一规整成正确的 Number 类型，这样能保证 blur 后调用的 onChange 返回的是 `Number | undefined`。不知道这个解释说清楚了没，这个问题先关了，有其他疑问可以继续在此讨论。

补一张  GIF图
![2](https://user-images.githubusercontent.com/2629994/50428075-02482800-08ef-11e9-8d82-17928ee6b3d0.gif)

**Comment by afc163** [comment]
InputNumber 目前的设计是，blur 后吐出数据时，一定保证是 Number 类型或者是 undefined。目前不能吐出 String 和 Number 的混合类型。

不过从你的信息判断，如果返回是 undefined 会导出给服务端的传字段直接丢失，我在想是不是改成 null 就可以了，这里需要你帮我确认一下。

**Comment by afc163** [comment]
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/507615/50429981-383fd900-08fc-11e9-8ec9-57f420ea75f7.png">

应该是 `{nums:undefined}` 的，看 console 里打出来的东西和 `'nums' in values` 的判断可见。

`{}` 的展现应该是 `JSON.stringify` 的结果，不影响你 js 做判断。

**Comment by jszjgqq** [comment]
> <img alt="image" width="1256" src="https://user-images.githubusercontent.com/507615/50429981-383fd900-08fc-11e9-8ec9-57f420ea75f7.png">
> 
> 应该是 `{nums:undefined}` 的，看 console 里打出来的东西和 `'nums' in values` 的判断可见。
> 
> `{}` 的展现应该是 `JSON.stringify` 的结果，不影响你 js 做判断。

的确如你所说，然后我又测试了下，把值强制指定为null，跟undefined，然后往接口提交，用调试工具可以看出来的结果是 undefined并不会往接口提交，但是null的就可以，这样的话也能满足需求了。

![3](https://user-images.githubusercontent.com/2629994/50430287-092a6700-08fe-11e9-84ff-12ea561e5b55.gif)

**Comment by afc163** [comment]
那我试着先改为 null 吧。💪

**Comment by afc163** [comment]
https://github.com/react-component/input-number/pull/134

看看有没有问题。

**Comment by jssoscar** [comment]
> https://codesandbox.io/s/0mvk17n01n
> 
> 看了下代码，应该是 codesandbox 的例子有误。如果用 `getFieldDecorator` 包裹了控件，则不再需要用 onChange 和 this.setState 进行绑定，`getFieldDecorator` 自己已经做了。
> 
> 去掉了 `initialValue: this.state.value` 之后的表现是，上述两种交互，提交后都是 `nums: undefined`。为什么不是编辑过程中的 `''`，这是因为 InputNumber 被设计成输入状态时返回 string（这样可以输入任意字符，保证输入的自由度），blur 后统一规整成正确的 Number 类型，这样能保证 blur 后调用的 onChange 返回的是 `Number | undefined`。不知道这个解释说清楚了没，这个问题先关了，有其他疑问可以继续在此讨论。

按照次说法，如果清空了 作为输入框 值应该是''  那Number('')返回值应该是0,而不是undefined

我们现在遇到了这种场景：
由于后端返回数据量很多，很多字段比如id这种 未必会都在form表单元素中  所以，需要读取页面上的值后，然后合并到后端返回的model中。而你返回undefined，就会导致拷贝的时候  原始值为1 页面清空 而通过API获取到了undefined， 合并后  还是原始值 相当于没有修改。

所以，这应该是一个bug而不是一个特性。

**Comment by afc163** [comment]
@jssoscar react-component/input-number#134 看下能解决你说的问题么

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/14960
