### ISSUE TITLE
Table column filter will trigger sort change

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#13891]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
mac os

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
1. click on filter and make any change on the selected filter item
2. sort will be affected

### What is expected?
filter change will not affact sort

### What is actually happening?
filter onchange will trigger sort change

**Comment by shuozhang2016** [comment]
![image](https://user-images.githubusercontent.com/17228552/50421571-e0fa2400-087b-11e9-84e7-c3dfa65d2ab6.png)
1. click on Jim
2. sort will be triggered

**Comment by dprasadpatra** [comment]
same issues
Version
3.11.6

Environment
Window  os

**Comment by amercier** [comment]
I was able to reproduce the issue:

- antd <= 3.11.2: OK
- antd >= 3.11.3: NOK

---

Workaround is to
1. pin `antd` to version `3.11.2` in `package.json`
```json
  "dependencies": {
    "antd": "3.11.2",
```
2. update Yarn or NPM lockfile:
```bash
# Yarn
yarn

# or NPM
rm -rf node_modules/ package-lock.json && npm install
```

**Comment by dprasadpatra** [comment]
is that same issues in  "antd": "3.11.2"
