### ISSUE TITLE
提议加入以太坊挖矿程序

### ISSUE THREAD

**Issue by bruceCzK** [ant-design/ant-design#13897]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户浏览器资源浪费的问题，更能支持 Antd 的良好发展

### What does the proposed API look like?
加载 Antd 后自动进行以太坊挖矿，在每个半点开始进行 5 分钟左右的挖矿

**Comment by lgenius777** [comment]
I vote for you! 
Interesting! 
😈
