### ISSUE TITLE
Menu组件的样式有点坑

### ISSUE THREAD

**Issue by ReadingSteiner** [ant-design/ant-design#139]
往里面放了a链接，才发现Menu.Item是用padding整出来的，结果a并没有充满整个Item,所以除非点击a链接上的文字，点文字周围的空白是无法进行跳转的。
如下图所示，绿色部分为padding：
<img width="153" alt="2015-08-17 5 07 16" src="https://cloud.githubusercontent.com/assets/6670037/9301642/906df6e6-4502-11e5-9071-308a36415b10.png">

**Comment by ReadingSteiner** [comment]
ant.design官网的那个menu好像也是自己写的？囧rz

**Comment by ReadingSteiner** [comment]
目前我是加了handleClick，然后用location.replace来模拟  (╯‵□′)╯︵┻━┻

**Comment by afc163** [comment]
感谢反馈。Fixed in http://ant.design/components/menu/#demo-horizontal

**Comment by mervynchung** [comment]
0.11版本，在vertical和inline模式下，以及horizontal模式submenu下的menu item仍然存在这个问题
