### ISSUE TITLE
Improve Search Select 

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1390]
把搜索框和单选选择框的位置进行合并，点开后搜索框盖在选择框位置上方，当前选项半透明。

交互参照：http://semantic-ui.com/modules/dropdown.html#search-selection

![](https://os.alipayobjects.com/rmsportal/OmXTrUSKPXwVMkE.png)

涉及范围：有搜索的单选框

**Comment by eternalsky** [comment]
好，就按这种交互来吧，如果搜索的值没有命中任意一个选项，在 blur 时选中当前选项中的第一个

**Comment by afc163** [comment]
> 如果搜索的值没有命中任意一个选项，在 blur 时保持原有选中项不变。

**Comment by eternalsky** [comment]
@afc163 这样和 semantic 的交互还是有点不太一样的，sementic 的单选如果搜索的值没有命中的情况下，默认是选择第一个的，就是说这里我们和他们的交互是不一样的？

**Comment by afc163** [comment]
不是啊。

你 focus 进上面的例子，输入 `xxx`，显示 `Not result found`，此时点击页面空白处 blur，选择框未选中任何选项。

**Comment by afc163** [comment]
感觉 semantic 这个交互有问题，应该只能点击或回车选择才应该发生选中，blur 不应该发生选中。

**Comment by superRaytin** [comment]
http://react-component.github.io/select/examples/single.html

**Comment by afc163** [comment]
升级版本和样式补充，再看看原来的东西有没有挂掉。

**Comment by superRaytin** [comment]
收到

**Comment by superRaytin** [comment]
另外，有一点不同，输入关键字如果搜索结果只有一项，此时 blur，rc-select 会选中这一项。如果要保持不变，rc-select 可能也需要改 @yiminghe

**Comment by yiminghe** [comment]
blur 要选中
