### ISSUE TITLE
改编不是乱编，彩蛋不是捣蛋，人妖不分，是非颠倒，有意思吗？

### ISSUE THREAD

**Issue by n0099** [ant-design/ant-design#13903]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我经常讲，公共协作项目浓缩起来就是开源文化，具体来说就是开放精神，本质上就是共产主义。
所以不管任何项目，刚才我讲的少到千多到上万，我可以随意问在座的每一位前端，没有用过 Ant Design 的请举手，没有一个人举手，什么是中华开源项目啊？！
但今天惊闻那 Ant Design 植入彩蛋，用户点进登录按钮就问：Ho Ho Ho！
前端框架怎么能随便改动组件dom呢，又怎么能乱加特技呢？
那 Ant Design 到底还能植入多少这样的彩蛋啊？一个企业级框架怎么能随便在正式版本上部署这样触发的彩蛋呢？
改编不是乱编，彩蛋不是跳蛋，人妖不分，是非颠倒，有意思吗？
开发团队还在issue上笑，像这样一个中华项目、世界知名框架，如果如此恶搞，那么这个团队的PM、主创人员是需要向全世界开发者谢罪的。
昨天我看issue里的吐槽，好多项目的客户，都看到了这彩蛋按钮，说：“您这项目有后门的吧？你不是外网隔离的吗？”
我用 Ant Design 从2018年用到8102年的今天，我太了解它了，一千个开发者心中，有一千个不同场景下的UI框架。但在中国，我希望一千个项目中，只有 Ant Design 它一个这样的捣蛋王。
而我们要推崇的是这样的一种精神，让全球的开发者，真正知道什么是中国的科技实力，我们不要一味跟着某一些国家、文化后面去追他们的那种风格、习俗，把前端按钮都弄得髭毛乍鬼的那样的，还叫什么圣诞彩蛋，这个不是我们民族的东西。
一个国家，没有自己优秀的文化，是可怕的；有了优秀文化，而不去弘扬，是可悲的；弘扬之后，又去践踏它，则是可耻的。
要恶搞，就去恶搞你爷爷奶奶去！

### What does the proposed API look like?
说到前端UI框架，明年年中，中美合作研发的Bootstrap 5.0即将正式公测，也将植入各国节日彩蛋特技，Twitter 会用中西方传统艺术形象努力创造一个普世的组件设计，文体两开花，弘扬中华文化，希望大家能多多关注。
https://www.zhihu.com/question/306858501/answer/559780630

**Comment by 8Bobo8Jun** [comment]
六學，六學（🌸🐔

**Comment by Dayinruoxi** [comment]
带六学

**Comment by rench** [comment]
六学

**Comment by yugai** [comment]
耍贫嘴都耍到这里了？转门去V2

**Comment by AibiTi** [comment]
又是培训机构的。

**Comment by yamcer** [comment]
6p

**Comment by chengenzhao** [comment]
有小朋友问我，开源会有后门吗？

**Comment by Ccixyj** [comment]
苦练js，笑对娱乐圈

**Comment by yikwing** [comment]
> 有小朋友问我，开源会有后门吗？

我回答:   当然没有啊,一个正常的人都不会做这种事.如果做了这种事,那么这个团队的PM、主创人员是需要向全世界开发者谢罪的。

**Comment by yidaliniuzuizheng** [comment]
六老师：你在github传播六学我同意了么
