### ISSUE TITLE
希望增加一个新的组件

### ISSUE THREAD

**Issue by lvzaina** [ant-design/ant-design#13901]
What problem does this feature solve?

解决阿里程序员对技术及开源毫无敬畏之心的bug

What does the proposed API look like?

希望贵司换一批技术人员

**Comment by shaopeng1** [comment]
站着说话不腰疼，换一批你去维护啊？你有那个能力吗？

**Comment by lvzaina** [comment]
楼上，我的水平不需要你去评价，你也没有能力去评价，我说的是antd这个团队，是出于信任被辜负后的情绪宣泄，倒是你气冲冲来回复的样子，和此次逻辑炸弹的创作者一样是一个臭傻逼，喜欢装最叼的，垃圾
