### ISSUE TITLE
Antd select not working inside a full screen dialog

### ISSUE THREAD

**Issue by nitinsh99** [ant-design/ant-design#13905]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
mac os 10.14.2, chrome 71.0 , reactjs v16.4.1

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1zvj51xmj)

### Steps to reproduce
open codesandbox link, Click on the select outside the dialog, it will work correctly. Open the dialog and then open select, it will not render option list.

### What is expected?
Select should work inside the model dialog

### What is actually happening?
Select option list doesn't get displayed when placed inside a model dialog even after giving an absolute position and very high zindex

---
I am using both materialui and antd as the ui component library in my react app. I have been using material ui's full screen dialog and tried to insert antd's select inside the dialog.

But looks like select list doesn't render correctly when placed inside material-ui's dialog component. I have tried to give antd select a very large zindex with absolute position but no luck.

Here's a the codesanbox link. You can the select work out the dialog but same select component doesn't render it's option list when placed inside the full screen dialog

https://codesandbox.io/s/1zvj51xmj

**Comment by afc163** [comment]
Try `getPopupContainer` or `dropdownStyle`.

https://codesandbox.io/s/jjky5wkwp3

**Comment by umer-abid** [comment]
for better idea have a look below,
just use z-index inside modal 2000 and for drawer use zIndex 20
![Screenshot 2022-02-22 114136](https://user-images.githubusercontent.com/47104149/155076684-08db6074-200a-43c6-96ea-1ebefe22cb81.png)

**Comment by Ammar1999y** [comment]
Try to add `popupClassName="pointer-events-auto"` to the Select component, it works for me.

**Comment by victor-paydestal** [comment]
> Try adding `popupClassName="pointer-events-auto"` to the Select component.
> 
> ## **Reason**
> In my case, I was using the [ShadCN dialog](https://ui.shadcn.com/docs/components/dialog), which applies `pointer-events: none;` to the body, while only the dialog itself has `pointer-events: auto;`. The Ant Design Select renders its popup outside the dialog. Because of this, the popup appears on the screen, but I can't interact with it. (If it doesn't appear, try increasing the `z-index`)

Thanks man. This was my exact use-case

**Comment by udaymamidisetti** [comment]
But popupClassName="pointer-events-auto" this showing as deprecated ??

**Comment by Evavic44** [comment]
> But popupClassName="pointer-events-auto" this showing as deprecated ??

Then use this:

```js
classNames={{popup: {root: "pointer-events-auto"}}}
```
