### ISSUE TITLE
i'm upgrade ant to V3, but I need V2 style, Is there any way?

### ISSUE THREAD

**Issue by three-ago-zhou** [ant-design/ant-design#13916]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
because , project use ant V2 already 1 year,  Styles are written according to ant2 style。now ant3 Cause style confusion to my project。for example: Select\Checkbox...

### What does the proposed API look like?
i expect use antV2 styles

**Comment by yesmeck** [comment]
No, you can't.
