### ISSUE TITLE
confirm custom icon theme

### ISSUE THREAD

**Issue by niuchunling** [ant-design/ant-design#13918]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
after 3.9.x, confirm icon theme only show 'outlined'

### What does the proposed API look like?
add  iocnTheme

**Comment by afc163** [comment]
Add `icon` to Modal.confirm and deperate `iconType`.

You can use this usage after the comming version `3.12.0`.

```
Modal.confirm({
  icon: <Icon type="xxx" theme="filled />,
})
```
