### ISSUE TITLE
Table sorting problem, multi-column sorting, I want my table only has the function of ascending order and sorting, there is no third click to restore the default, the default set to ascending order, click to descending order, click again is ascending order, rather than unsorting, how to set it

### ISSUE THREAD

**Issue by InitialSugar** [ant-design/ant-design#13910]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表格排序问题，多列排序，我想要我的表格只具备升序和排序的作用，没有第三次的点击还原默认， 默认设置为升序，点击为降序，再次点击就是升序，而不是取消排序，该怎么设置呢

Table sorting problem, multi-column sorting, I want my table only has the function of ascending order and sorting, there is no third click to restore the default, the default set to ascending order, click to descending order, click again is ascending order, rather than unsorting, how to set it
### What does the proposed API look like?
...

**Comment by afc163** [comment]
目前不支持这样的用法。可能 https://github.com/ant-design/ant-design/pull/13773 的提交可以帮助到你。
