### ISSUE TITLE
Button type 支持自定义类型

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#13915]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
除了默认 Button 类型外可以自定义 Button 类型，前面版本是支持的，新版控制台抛警告!

### What does the proposed API look like?
```jsx
<Button type="gray">Gray</Button>
```
![_20181226112227](https://user-images.githubusercontent.com/1730277/50430811-30366800-0901-11e9-90fa-628ba66e7faf.png)
![_20181226112239](https://user-images.githubusercontent.com/1730277/50430816-33c9ef00-0901-11e9-90cb-ddf7e7d5a46f.png)

**Comment by 604587986** [comment]
use htmlType
