### ISSUE TITLE
请问type=primary的button某些图标为什么是灰色的

### ISSUE THREAD

**Issue by raclen** [ant-design/ant-design#13924]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
最新版本

### Environment
chrome70

### Reproduction link
[https://codepen.io/ralcen/pen/pqwZNW](https://codepen.io/ralcen/pen/pqwZNW)

### Steps to reproduce
search和edit都是白色的，为什么plus和minus是灰色的

https://codepen.io/ralcen/pen/pqwZNW

### What is expected?
期望type=primary的button图标都是白色的，或者button可以传style修改颜色

### What is actually happening?
实际结果
search和edit都是白色的，plus和minus是灰色的

---
https://codepen.io/ralcen/pen/pqwZNW

**Comment by afc163** [comment]
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/507615/50439403-ec595800-092c-11e9-8569-1eebde1aaa86.png">

你的例子没有发现有啥问题。

**Comment by afc163** [comment]
`type="primary"` 就是蓝色的主按钮，目前没有提供灰色的按钮。

**Comment by raclen** [comment]
![_20181226170308](https://user-images.githubusercontent.com/7697758/50440247-3f80da00-0930-11e9-9182-50e69d371400.png)
按钮里面的图标我这边看到plus和minus是灰色的，search和edit都是白色的。3.11.6版本

**Comment by afc163** [comment]
你的例子是好的，如果有问题，希望提供重现，不然无从排查。

**Comment by afc163** [comment]
哦，你是说图标颜色是吧。

我这里看着是好的，你的操作系统版本是？

**Comment by zombieJ** [comment]
能给个截图看看吗？

**Comment by afc163** [comment]
感觉是操作系统和浏览器的渲染问题，试试 cmd + 0?

**Comment by raclen** [comment]
我是windows7，同事是windows10都是这样

**Comment by zombieJ** [comment]
windows 下对夹在两个像素间 svg 处理糊了，我针对的处理一下这两个图标去……
