### ISSUE TITLE
Component of Table, Fixed Columns can be repeated

### ISSUE THREAD

**Issue by FireBushtree** [ant-design/ant-design#13920]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.2

### Environment
win10, Chrome 71.0.3578.98

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2467qw24oj)

### Steps to reproduce
Although i set `width` for every columns, the fixed columns will be repeated.

### What is expected?
The fixed columns are not repeated

### What is actually happening?
The fixed columns are repeated

---
I set the fixed columns' width `100px` , set the unfixed columns width `150px` and set the scroll `{x: 1500}`, at common state, it works well, but user's some operation may remove some unfixed columns, after these actions' the fixed columns repeated and the columns' alignment also are wrong.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8079#issuecomment-343828418

https://codesandbox.io/s/o7xy3947vz
