### ISSUE TITLE
表单中有其他元素导致校验失效

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1392]
https://github.com/ant-design/ant-design/blob/develop-1.0.0/components/form/demo/validate-other.md

```jsx
        <FormItem
          {...formItemLayout}
          label="性别：">
          <RadioGroup {...radioProps}>
            <Radio value="male">男</Radio>
            <Radio value="female">女</Radio>
          </RadioGroup>
          <span><Icon type="info-circle-o" /> 暂不支持其它性别</span>
        </FormItem>
```

`develop-1.0.0` 分支。

**Comment by TheWaWaR** [comment]
因为是直接从 repo 的 demo/xxx.md 复制出来的代码，我也遇到了这个问题，使用的版本是 `antd@0.12.13`

**Comment by afc163** [comment]
在 develop-1.0.0 中已经进行了修复。

**Comment by TheWaWaR** [comment]
OK, 我改下依赖试试。

**Comment by afc163** [comment]
beta 版本有很多改动，如果项目对稳定性要求高，建议耐心等待发布。

**Comment by TheWaWaR** [comment]
话说，完全看不出来为什么这个例子叫做 `校验其他组件` , 不是只有修改密码那里有涉及到校验其它字段的使用吗？

哦，beta 没关系的，我现在是在为下一版做公共组件。

**Comment by afc163** [comment]
其他组件指的是 antd 自己的各种表单组件。
