### ISSUE TITLE
InputNumber设置precision={2}，但是输入1.00这样的值获取到的值是1，显示值是1.00

### ISSUE THREAD

**Issue by 1416246152** [ant-design/ant-design#13923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
设置precision={2}的InputNumber，但是输入1.00，显示应为1.00，返回值也应为1.00

### What does the proposed API look like?
设置precision的InputNumber，返回值就应该是精度样式的值。precision={2}，输入1.00，返回就应该是1.00

**Comment by afc163** [comment]
InputNumber 返回的是 Number 类型，js 中没办法指定为 `1.00` 的值。

<img width="193" alt="image" src="https://user-images.githubusercontent.com/507615/50439668-d7c98f80-092d-11e9-9cc4-a8d5879375ce.png">
