### ISSUE TITLE
Table column设置了filter和sorter，当点击filter的时候同时sorter也捕获到了点击事件

### ISSUE THREAD

**Issue by codelieche** [ant-design/ant-design#13933]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
macOS(10.14.2)  Chrome版本 71.0.3578.98

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-head](https://ant.design/components/table-cn/#components-table-demo-head)

### Steps to reproduce
1. 打开网页：https://ant.design/components/table-cn/#components-table-demo-head
2. 选择：右侧的自定义选择项，点击过滤，把排序也亮了。
3. 原因：点击filter把事件也传给了ordering

### What is expected?
修复：点filter的时候不同时点了order。就是点击过滤的时候不触发排序。

### What is actually happening?
点过滤功能的时候不单击排序功能，需要排序的时候自己点。

**Comment by afc163** [comment]
Duplicate of #13891
