### ISSUE TITLE
表格组件是否可以在初始化的时候渲染排序的状态

### ISSUE THREAD

**Issue by wxt2005** [ant-design/ant-design#1393]
首先，谢谢你们开源了这么优秀的组件库！
我现在做的项目，数据的排序是由后端进行的。通过参考官网的实例，可以做到在表格的 onChange 触发时请求后端来进行排序。
但是在第一次发请求获取表格数据进行渲染的时候，虽然后端传给了我初始的排序参数（哪个列排序，以及是正序还是逆序），但是我没有找到如何通过这些参数来修改界面上排序状态的方法（主要是那个箭头的显示）。
请问现在存在这个功能吗？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/971

Finish in branch `develop-1.0.0` now.
