### ISSUE TITLE
Cause z-index error when used Badge in fixed Table columns

### ISSUE THREAD

**Issue by kenve** [ant-design/ant-design#13930]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
macOS Mojave, Chrome 71, React 16

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6l3mxqkvxz)

### Steps to reproduce
Scroll the table

### What is expected?
Correct vertical order

### What is actually happening?
Incorrect vertical order
![image](https://user-images.githubusercontent.com/7636918/50436053-e2c8f380-091e-11e9-9599-f8addfc948d2.png)

**Comment by tungpin** [comment]
this problem is caused by Badge component's z-index value is higher than fixed columns. so add `z-index: 99` to class `ant-table-fixed-right` can solve any problem caused by z-index that like yours problem

**Comment by tungpin** [comment]
so I recommend @afc163 add a common class of `ant-table-fixed-right` and `ant-table-fixed-right`, then add `z-index: 99` to the common class, or render empty node of the column that is fixed and not render the fixed column
