### ISSUE TITLE
Header Menu getting collapsed on Chrome

### ISSUE THREAD

**Issue by sushilbansal** [ant-design/ant-design#13937]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
Windows 10, Firefox: 60.4.0esr, Chrome: 71.0.3578.98, React: 16.4.0

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0o7zjly9mv)

### Steps to reproduce
1) Add Layout
2) Add Header
3) Add a Menu child with horizontal={true}
4) Add some Menu.Item

### What is expected?
Menu should not collapse on Chrome

### What is actually happening?
on chrome Menus are getting collapsed while on Firefox it is fine

---
Check this URL: https://bakbak.netlify.com/ 
to see the issue in production in Chrome and Firefox

**Comment by itzsaga** [comment]
@sushilbansal I don't think `horizontal={true}` is correct. It should be `<Menu mode="horizontal" />`. Not sure if this will fix your issue.

**Comment by sushilbansal** [comment]
I tried that already <Menu mode="horizontal" />. Still the same issue.

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50622796-17eeca80-0f4b-11e9-9938-fc38c48f8c99.png)
Can you explain this issue to me? I guess I have a little confuse with it.

**Comment by sushilbansal** [comment]
Hi @ztplz thanks for the contacting me. Please check this URL in chrome: https://www.bakbakapp.com/

I could not replicate the issue in code sandbox. I can share my code which is running on the site.

**Comment by ztplz** [comment]
@sushilbansal 
![image](https://user-images.githubusercontent.com/17755202/50643946-6f705300-0faa-11e9-95db-3adad8a442f7.png)
What are the differences between them?

**Comment by sushilbansal** [comment]
On firefox i can see Login and Register buttons. While on Chrome the buttons gets collapsed even though there is a lot of space.

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50645288-24583f00-0fae-11e9-8759-429479de6b73.png)

Not collapsed on my chrome.

**Comment by sushilbansal** [comment]
hmm that's weird. Let me test on another machine/laptop and report my results.

**Comment by sushilbansal** [comment]
looks like this issue is only on my computer
