### ISSUE TITLE
Can you add the selected style effect to the onRightClick of the Tree?

### ISSUE THREAD

**Issue by wangzhidavid** [ant-design/ant-design#13936]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the user right-clicks, he knows which one he has selected.But now it's just CSS style of onMouseEnter!

### What does the proposed API look like?
rightClick(info) {
    this.setState({ selectedKeys: [info.node.props.eventKey], currentSelected: info.node.props });
    info.node.props.selected = true;  
    or info.node.onSelect()
    this.renderCm(info);
  }

**Comment by afc163** [comment]
It is hard to implement right now... Can you try it?

**Comment by wangzhidavid** [comment]
Thanks awesome. Thanks for the quick response!
Yes,I tried to execute the onSelect method inside the onRightClick method, but it didn't work;Property values for parameters in the onRightClick method cannot be set;I haven't tried right-clicking on this node and looking for it by class name to set the selection style, but I think this method is a bit of performance consuming. Since it can have the effect of onMouseEnter, it should be easy for you to set the selection effect of onMouseEnter. Can you add the selected effect of right-clicking！
Thank you in advance!

**Comment by afc163** [comment]
I mean...could you try to send PR to http://github.com/react-component/tree cause it seems not a emergency requirement for us.

**Comment by wangzhidavid** [comment]
Thanks a lot!
I will try it as you suggest!

**Comment by afc163** [comment]
Closing now, Feel free to send PR to rc-tree.
