### ISSUE TITLE
Dropdown should support dynamic popup content with overlay as a function/lambda

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#13944]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
issue 1) when there are lots of items that need right click menu, like a datagrid editor. create a menu element for every single grid cell during rendering is not necessary. Creating it when showing the menu would be much more efficient.

issue 2) sometimes menu can be affected by other states, some global, some local, it's a waste of  time if component has to re-renderer every time a state changes  (not react state), even when the popup is not shown.

### What does the proposed API look like?
rc-trigger already supports it, so rc-dropdown and antd dropdown just need to allow that type and skip the clone logic

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by rinick** [comment]
in rc trigger,  it's defined as 
```
popup: PropTypes.oneOfType([
      PropTypes.node,
      PropTypes.func,
    ])
```

so I assume in antd, it should be 

```
overlay: React.ReactNode | () => React.ReactNode;
```

**Comment by rinick** [comment]
@zombieJ @yesmeck , that commit in rc-dropdown only solves half of the problem.  the drop down component in antd still needs to be updated for this to work.

**Comment by zombieJ** [comment]
Yes. Here is the related PR on antd: https://github.com/ant-design/ant-design/pull/14003

**Comment by asyura** [comment]
not solve, popup content only can be menu, not any component.

**Comment by rinick** [comment]
> not solve, popup content only can be menu, not any component.

you can always wrap a component inside menuitem.

or if you really don't like the style and padding of a menu, just use rc-trigger directly
