### ISSUE TITLE
SideMenu in Layout.Sider not opening on click in collapsed mode in Ipad

### ISSUE THREAD

**Issue by asimnazir** [ant-design/ant-design#13943]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
Chrome

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://4090xmkjr7.codesandbox.io/)

### Steps to reproduce
-In chrome dev tools select Ipad from "toggle device toolbar"

-Expand side panel (Sider)

-Select "Team > Team 1"

-Collapse Side panel

-Click on "Team" icon

### What is expected?
-Submenu for "Team" should appear

### What is actually happening?
-Submenu for "Team" is not appearing

---
-In collapsed mode: If click on  anyother menu item and then click on "Team" icon then it appears correctly

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50456224-f790a000-098d-11e9-98e1-c3cd9f5cd200.png)
This is only a demo, can you provide the code?
