### ISSUE TITLE
Checkbox.Group return wrong value after adding surrounding div tag

### ISSUE THREAD

**Issue by Rlexsu** [ant-design/ant-design#13940]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
Window 10, Chrome 71.0.3578.98, react version 16.5.2

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8l1x7x8789)

### Steps to reproduce
Surround the Checkbox.Group with a div tag

### What is expected?
Getting ticked checkbox options

### What is actually happening?
Getting true as value instead

---
Removing the surrounding div tag and I am able to get ticked checkbox value correctly

**Comment by afc163** [comment]
You should surround form filed control by `getFieldDecorator` directly. It is the way `getFieldDecorator` designed to work.

https://codesandbox.io/s/r06o2j04xo

**Comment by Rlexsu** [comment]
Hmm if you don't mind can you explain what value is being picked up by `getFieldDecorator` when I surround it with div tag?

**Comment by afc163** [comment]
`<div value={xxx} onChange={(value) => onChange(value)}>`

getFieldDecorator will add `value` and `onChange` to bind component if it can works at it.

**Comment by Rlexsu** [comment]
Alright thanks for the explanation 👍
