### ISSUE TITLE
antd是不是有选项能设置显不显示警告

### ISSUE THREAD

**Issue by allces** [ant-design/ant-design#1394]
antd是不是有选项能设置显不显示警告，谢谢！

**Comment by afc163** [comment]
https://github.com/r3dm/warning/blob/master/warning.js#L19

**Comment by allces** [comment]
但是我现在antd是从页面script引入的，代码就是从官网那儿拿的。好像这样就不行了。还有官网的antd.js有没有单独的例子来构建这个js

**Comment by afc163** [comment]
不推荐在生产环境使用官方网站的 antd.js

https://github.com/ant-design/ant-design/issues/1338

**Comment by allces** [comment]
谢谢，问题解决了。
