### ISSUE TITLE
Collapse折叠面板的箭头是否能新增一种情况是让它靠右显示

### ISSUE THREAD

**Issue by mantianrefeng** [ant-design/ant-design#13953]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
chorme

### Reproduction link
[https://ant.design/components/collapse-cn/](https://ant.design/components/collapse-cn/)

### Steps to reproduce
在自己本地文件中使用：global去修改样式，用position:absolute;right:16px.箭头居然在行的中央显示了，并没有靠右显示（然而，如果直接在浏览器的控制台中修改，他却靠右显示） 

### What is expected?
Collapse折叠面板的箭头是让它靠右显示

### What is actually happening?
在自己本地中使用：global去修改样式，用position:absolute;right:16px.箭头居然在行的中央显示了，并没有靠右显示

**Comment by tungpin** [comment]
@mantianrefeng 我这里按你这个样式进行修改icon图标类，是可以达到预期效果的，另外你可以使用codesandbox重现你的问题

**Comment by zombieJ** [comment]
🌝left 需要 initial 掉：https://codesandbox.io/s/vpm8qwo37

**Comment by afc163** [comment]
@zombieJ 

可以放一个链接到 demo 描述里。

**Comment by zombieJ** [comment]
@afc163 我在组件页面底下的加个小 FAQ 吧，可以归拢归拢。

**Comment by mantianrefeng** [comment]
还有一种方式 （
![image](https://user-images.githubusercontent.com/25834502/50499330-db6f2a80-0a83-11e9-9820-9c2421293e97.png)
）
>>用上面这个把前面箭头隐藏掉，直接在他的header内容里面的之后加个<Icon type="right" />，形如：
![image](https://user-images.githubusercontent.com/25834502/50499442-ac0ced80-0a84-11e9-8a65-352d1471376d.png)
然后用position:absolute;right:16px;这样子  就行了。这样子onChange事件都不用加，会根据
![image](https://user-images.githubusercontent.com/25834502/50499404-58020900-0a84-11e9-92b9-a325a95e024d.png)
>>这样直接会根据expanded=true让展开的时候图标向下
