### ISSUE TITLE
Select combobox mode always shows the selected option's value instead of label when used together with Form and the provided this.props.form.getFieldProps method

### ISSUE THREAD

**Issue by HyczZhu** [ant-design/ant-design#1395]
## What you did

Use Select combobox mode together with Form (already wrapped by Form.create()) and the provided this.props.form.getFieldProps method, try to select one option with integer value and string label (e.g. <Option value="1">jack</Option>).

```js
class Test extends Component {
    render() {
        return (
            <Form horizontal>
                <FormItem
                    label="Select 选择器："
                    labelCol={{ span: 8 }}
                    wrapperCol={{ span: 16 }}
                    required>
                    <Select combobox
                            style={{ width: 200 }}
                            {...this.props.form.getFieldProps('name')}>
                        <Option value="1">jack</Option>
                        <Option value="2">lucy</Option>
                        <Option value="3" disabled>disabled</Option>
                        <Option value="yiminghe">yiminghe</Option>
                    </Select>
                </FormItem>
            </Form>
        );
    }
}

Test = Form.create({})(Test);
```

## What you would like to happen

The select shows the option **label** I selected (e.g. jack).

## What actually happened

Yet the select shows the **value** actually (e.g. 1). 

## Environment Information

- The version of antd: 0.12.13

**Comment by yiminghe** [comment]
Option 's value should be same with Option's children for combobox

**Comment by HyczZhu** [comment]
Yes that should solve the problem, and I've been already doing so.

Yet I don't think this is what it's designed for. While if I use other types of Select in this case, we could set different values for the 'value' prop and children, but I just couldn't do the same for combobox (and the combobox select works well if used alone without Form), I think this is obviously an issue.

**Comment by spademan** [comment]
我也是这个需求，希望能满足一下。。

**Comment by codercatmomi** [comment]
同问

**Comment by erdigokce** [comment]
> Option 's value should be same with Option's children for combobox

Why there is a requirement for the _value_ and the _label_ specifications separately, since they must be the same? I am on the same page with @HyczZhu . This behavior seems not satisfying _Selector_ component's expectations.
