### ISSUE TITLE
dateRender doesn't invoked by WeekPicker 

### ISSUE THREAD

**Issue by fay04** [ant-design/ant-design#13957]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
undefined

### Environment
浏览器版本

### Reproduction link
[https://codepen.io/zhangpengju/pen/PXKWJZ?editors=0010](https://codepen.io/zhangpengju/pen/PXKWJZ?editors=0010)

### Steps to reproduce
看日期和周的弹出框

### What is expected?
期望周上的日期也是红色的

### What is actually happening?
周的日历颜色没变

**Comment by rashmimh** [comment]
facing the same issue. Any breakthrough?
