### ISSUE TITLE
hover the gap between Menu & subMenu could cause subMenu flashing show/hide 

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#13955]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
mac os

### Reproduction link
[https://ant.design/components/menu/](https://ant.design/components/menu/)

### Steps to reproduce
repeated hovering among the gap between menus and subMenu

### What is expected?
subMenu should not hide or not flashing show/hide when hovering back to its Menu item

### What is actually happening?
immediately hide and show for subMenu

**Comment by shuozhang2016** [comment]
Add subMenuOpenDelay will solve this issue but by default, this will obviously happen

**Comment by hengkx** [comment]
I didn't understand the mistake.same as #23369,#23148?
