### ISSUE TITLE
DatePicker inside of Modal remains fixed and does not scroll with Modal

### ISSUE THREAD

**Issue by obianachebe** [ant-design/ant-design#13952]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
Antd 3.11.6; Chrome 71.0; Typescript; React 16.7.18

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2jx321wv2p)

### Steps to reproduce
Create a Modal, then add a div with a large height and a DatePicker as a child

### What is expected?
When the Modal is scrolled, the DatePicker should scroll with the content 

### What is actually happening?
The DatePicker remains fixed in the same position and has strange jumps in position when the picker is below the fold and dates are tapped

---
Issue #3031 says this has been fixed, but I still see the issue on both Chrome and Safari

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-disappear-when-I-click-another-popup-component-inside-it,-How-to-resolve-it?
