### ISSUE TITLE
antdesign的官网首页 锚点-代码演示-API页面错乱

### ISSUE THREAD

**Issue by ykl124** [ant-design/ant-design#13965]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
生产

### Reproduction link
[https://ant.design/components/anchor-cn/#API](https://ant.design/components/anchor-cn/#API)

### Steps to reproduce
antdesign的官网首页 锚点-代码演示-点击API ，可以看到页面错乱

### What is expected?
期望页面正常

### What is actually happening?
实际页面重叠，代码演示盖住了API了部分。
![image](https://user-images.githubusercontent.com/10691264/50472814-55a49e00-09f5-11e9-94d5-e77ba6a77be7.png)

**Comment by tungpin** [comment]
@ykl124 确实错位了，但是我看这个锚点定位机制是把锚点滚动到页面顶部。所以如果这个组件再宽点，就会遮盖更多的内容。不过也没没啥大问题吧(除非更改例子，不要全部放在一个组件里)

**Comment by ycjcl868** [comment]
这是 Anchor 的展示效果，不是 bug。参考 [2.x](https://2x.ant.design/components/anchor-cn/)

**Comment by zombieJ** [comment]
感觉可以把 “基本” 和 “静态位置” 两个例子合起来，然后加个 Swith，用户点开就浮动，反之就是静态的。打开链接第一眼的确像 BUG。
