### ISSUE TITLE
使用babel-plugin-import插件后，报错

### ISSUE THREAD

**Issue by coderyyx** [ant-design/ant-design#13960]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.2

### Environment
mac os, chrome 71.0.3578.98， babel-core: 6.26.3

### Reproduction link
[http://ant.design](http://ant.design)

### Steps to reproduce
不适用babel-plugin-import插件打包、运行正常；使用后打包正常，运行报错。例如：_form2.default.create is not a function

### What is expected?
正常按需加载~

### What is actually happening?
不正常按需加载~

**Comment by tungpin** [comment]
@coderyyx  请给出更具体的报错信息，`babel-import-plugin` 只是将你 写的 `import { Form } from 'antd'` 转换为 
```jsx
import Form from 'antd/lib/form';
import 'antd/lib/form/style/css';
```

**Comment by coderyyx** [comment]
![541545898484_ pic](https://user-images.githubusercontent.com/19465842/50472178-b5e61080-09f2-11e9-9a78-600a5e8b8d48.jpg)
![551545898495_ pic](https://user-images.githubusercontent.com/19465842/50472188-bc748800-09f2-11e9-9514-854a3cde8291.jpg)
![561545898516_ pic](https://user-images.githubusercontent.com/19465842/50472192-c0080f00-09f2-11e9-9db7-159413b5bb24.jpg)

**Comment by coderyyx** [comment]
是的，只是一些环境变量不一样，不会影响构建；编译的时候不报错，浏览器运行的时候报错~

**Comment by coderyyx** [comment]
我猜测是babel版本的问题，按需导出的时候解析出错，我尝试升级到babel 7

**Comment by coderyyx** [comment]
@tungpin 
 babel升级到7，antd升级到3.11.6 ，引用babel-plugin-import报了如下如错误
![571545904502_ pic_hd](https://user-images.githubusercontent.com/19465842/50475707-9229c700-0a00-11e9-806f-53bb0b6d898e.jpg)

**Comment by coderyyx** [comment]
@afc163

**Comment by coderyyx** [comment]
@tungpin @afc163 大佬们过来瞧瞧~~

**Comment by tungpin** [comment]
能不能给个可复现的demo

**Comment by afc163** [comment]
配置类问题你要给 git repo 才能排查的，不然无能为力。
