### ISSUE TITLE
组件里不要调用reset-component。

### ISSUE THREAD

**Issue by lubyxu** [ant-design/ant-design#13969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
背景原因：不同的媒体查询，呈现不同的字体。因为每个组件都调用reset-component，重置每个组件的font-family，不方便开发。然而less不支持mixin override。为什么组件样式的font不能通过继承呢？

### What does the proposed API look like?
组件的样式里，不要调reset-component

**Comment by afc163** [comment]
有没有具体的例子，不 reset-component 的话组件样式有大量重构，比较棘手。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/a8019bf0a02349a3a2bbd79cc86427b9e2426f49
