### ISSUE TITLE
Table组件中，在render中过滤datasource，拖拽失效

### ISSUE THREAD

**Issue by plainnany** [ant-design/ant-design#13963]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.11.6

### Environment
Chrome 70.0.3538.110

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/91q1rp1954)

### Steps to reproduce
Table组件，在render中过滤datasource，拖拽失效

### What is expected?
Table组件，在render中过滤datasource，拖拽可以正常使用

### What is actually happening?
拖拽失效

**Comment by zombieJ** [comment]
你展示过滤后的数据，那你在交换的时候也需要映射回原来的数据再进行交换：https://codesandbox.io/s/zq9jxqzqom

**Comment by plainnany** [comment]
明白了，多谢
