### ISSUE TITLE
Carousel 在卸载组件后，持续setState()，导致页面卡死

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#1397]
## What you did
在项目首页使用Carousel组件实现多个图片自动轮播功能。

## What actually happened

从首页跳转到其他页面时，控制台出现如下警告（多条），最终导致页面卡死：
`warning.js?0260:44 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the InnerSlider component.`
![qq 20160412190307](https://cloud.githubusercontent.com/assets/4525647/14458229/5a6d6a30-00e2-11e6-8f3d-816c9be6d453.png)

## Online demo
https://codepen.io/xiaoyi_1222/pen/KzoVNr

demo我打包了一份，在附件中。

## Environment Information

- The version of antd(0.12.13):
- Your operating system and it's version(windinws 10):
- Your browser and it's version(49.0.2623.110 m(64-bit)):

**Comment by kairi1227** [comment]
个人感觉是在unmount Carousel的时个，没有将定时器清除。
解决办法：在Carousel组件中添加一个componentWillUnmount()方法，该方法中将定时器清除就可以了。
其他Ant的回复。

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/blob/c5301b569a9eb2c0927ef1083d1d67ce5a8a023f/src/inner-slider.jsx#L52

不给重现 demo 让我们很难办。

**Comment by kairi1227** [comment]
@afc163  demo我单独发你邮箱（afc163@gmail.com）里。请你查收一下。

**Comment by afc163** [comment]
不要发邮箱。http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by kairi1227** [comment]
@afc163 我们项目的代码，不方便公开。相互体谅一下吧。

**Comment by afc163** [comment]
帮助我们整理出一个能重现的例子，我没有要求公开项目代码....

**Comment by kairi1227** [comment]
@afc163 整理了个demo。

**Comment by kairi1227** [comment]
[Demo.zip](https://github.com/ant-design/ant-design/files/216814/Demo.zip)

**Comment by afc163** [comment]
重现了，在上面的 issue 我给 react-slick 提了这个问题，等待  react-slick 修复。

> PS：我把你的 Demo 链接移除了。

**Comment by afc163** [comment]
等后续有时间去提个 pr 。

**Comment by jljsj33** [comment]
官网案例里的 autoplay 切换回来还是卡死。。。

**Comment by kairi1227** [comment]
@afc163 什么时候能修复呢？项目等着升级呢。。。。

**Comment by afc163** [comment]
react-slick 的问题，我们也没有办法，可以去上面的 PR 中帮助我们催促官方合并。

**Comment by jljsj33** [comment]
如果是 banner，可以试试，http://react-component.github.io/banner-anim/，，，，，我已经对那 react-slick 彻底无语了。。。

**Comment by kairi1227** [comment]
其实我们是不想再引入更多的第三方组件了，再等一个迭代。

**Comment by afc163** [comment]
react-slick 已发布 0.12.1 。

**Comment by yangmingfa** [comment]
这个问题还是存在，会一直报这个警告
