### ISSUE TITLE
Upload使用beforeUpload返回false依旧会依旧触发上传

### ISSUE THREAD

**Issue by fangkyi03** [ant-design/ant-design#13972]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.10

### Environment
mac 10.14.1 chrome 70.0.3538.77

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ll567154j7)

### Steps to reproduce
使用upload并且限定只能传图片格式 然后在上传过程中 上传一张不是图片格式的文件 beforeUpload返回false 但是依旧会出现在上传列表中 并且依旧会触发onChange 如果url等一些问题不对的时候 就会导致页面奔溃

### What is expected?
beforeUpload返回false 不出现在列表中

### What is actually happening?
使用upload并且限定只能传图片格式 然后在上传过程中 上传一张不是图片格式的文件 beforeUpload返回false 但是依旧会出现在上传列表中

---
https://github.com/fangkyi03/ant-design

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13566
https://github.com/ant-design/ant-design/pull/9340#issuecomment-364841597

**Comment by fangkyi03** [comment]
这会导致崩溃的增加 毕竟你会重新触发onChange

**Comment by afc163** [comment]
有没有可重现的例子：http://u.ant.design/codesandbox-repro

**Comment by fangkyi03** [comment]
可以用我提供的那个例子 然后上传一个不属于图片的文件 然后你就会发现页面直接奔溃了 原因主要在于直接返回false依旧调用了onChange然后重新走了一次提交的流程 但是这个明显是错误的 因为这样的操作 
原本我明明可以将不属于图片格式的文件都规避掉 永远不可能因为这个原因报错 但是现在我却永远无法规避 这个问题其实我自己已经改好了 提issue只是跟你们说一下 因为我看了一下最新版依旧如此

**Comment by afc163** [comment]
我迟点看看

**Comment by afc163** [comment]
点错 😄

**Comment by fangkyi03** [comment]
自我鼓励

**Comment by afc163** [comment]
不行，开了你这个我得再去关一个才睡得了

**Comment by fangkyi03** [comment]
antd其实还有很多不合理的地方的 如果你有兴趣听 我能说很多

**Comment by afc163** [comment]
我们鼓励直接 PR

**Comment by fangkyi03** [comment]
主要是form改动很大
比如formItem的设计 导致如果同一行有多个组件 比如一个编辑框带两个下拉或者带个选择框
这个时候如果全部都是强制的话 在一个formItem里面就会导致无法进正确的错误提醒
![image](https://user-images.githubusercontent.com/30390014/50486200-d3879a00-0a33-11e9-9faf-adfa0e741c90.png)
其实目前form的设计 就拿刚才那个upload为例的话 如果跟redux结合起来的话 onChange触发的时候 又会导致form触发 然后触发onFieldsChange
但是因为redux实现双向绑定的关系 一般都会在这里对redux进行数据刷新 然后呢 就会又导致外层的form绑定了这个从而导致页面刷新 然后重新出发onFieldsChange

整个更新流程至少要多走好几次才行 页面要刷新多次

**Comment by afc163** [comment]
这种情况一般是鼓励封装上层的表单组件。https://ant.design/components/form/#components-form-demo-customized-form-controls

**Comment by fangkyi03** [comment]
modal不支持Preact

**Comment by fangkyi03** [comment]
就是想省点心才用的antd 现在光这个form反而心累

**Comment by ztplz** [comment]
设计好改，兼容难做。要改早改了，但是要不break change。

**Comment by fangkyi03** [comment]
还有table的size这个属性 改成small以后 希望能直接限死高度 现在有些时候样式写错了 会导致直接撑大 然后small这个属性就白费了

**Comment by fangkyi03** [comment]
还有table colums中的align属性 就不能直接在table组件的props那一级加个属性直接控制一下里面所有item都直接设为居中吗 现在得每个colums都去设置一下 累
item.colums.align || this.props.align

**Comment by fangkyi03** [comment]
其次table中如果data中的数据结构
children:[]是一个空数组的话 你们依旧会显示一个+好图标在那边 我想说 里面子都没有 显示+号 让别人点击有意思吗？

**Comment by fangkyi03** [comment]
Cascader AutoComplete Dropdown问题一样 如果我在下拉的过程中 想实现一个多选这么办 还有如果我展示的数据量很多 如何分页呢

**Comment by afc163** [comment]
> 还有table的size这个属性 改成small以后 希望能直接限死高度 现在有些时候样式写错了 会导致直接撑大 然后small这个属性就白费了

这个不可行，写死高度有单元格有多行内容怎么办。

>  children:[]是一个空数组的话 你们依旧会显示一个+好图标在那边 我想说 里面子都没有 显示+号 让别人点击有意思吗？

这个是有意的设计，用于异步加载子表格或者展开部分的数据。详细可见：

https://github.com/ant-design/ant-design/issues/6675#issuecomment-312787463
https://github.com/ant-design/ant-design/issues/9689#issuecomment-373319092
https://github.com/ant-design/ant-design/issues/11937#issuecomment-417194180

> 面包屑就更加不想说了 就不能直接跟左侧menu共享一下数据吗 点击哪个就把层级直接显示出来 这样既能动态也能少写很多东西 如果要自定义的话 在判断传参的方式来啊 现在每次都要自己手写 累死 而且我们现在左侧菜单有事可以动态化配置的 每个人进去的菜单都不一样 菜单功能层级也是可以随意配置的情况下 我直接面包屑就是废的 因为我的父级永远都是会变的 我写死的面包屑没有任何用处

antd 中的组件要原子化，面包屑和 react-router 绑定的示例。在 Pro 中也有和 menuData 直接关联的面包屑：http://preview.pro.ant.design/ 你可以去看一看。

**Comment by afc163** [comment]
> Dropdown 这个下拉菜单 如果普通的还行
> 但是如果说你下拉菜单实际显示的东西是一个进度条的话就很坑了

Dropdown 只是个下拉菜单，如果要做自定义内容应该用 Popover 或者是更自定义的 rc-trigger。

**Comment by fangkyi03** [comment]
> > 还有table的size这个属性 改成small以后 希望能直接限死高度 现在有些时候样式写错了 会导致直接撑大 然后small这个属性就白费了
> 
> 这个不可行，写死高度有单元格有多行内容怎么办。
> 
> > children:[]是一个空数组的话 你们依旧会显示一个+好图标在那边 我想说 里面子都没有 显示+号 让别人点击有意思吗？
> 
> 这个是有意的设计，用于异步加载子表格或者展开部分的数据。详细可见：
> 
> [#6675 (comment)](https://github.com/ant-design/ant-design/issues/6675#issuecomment-312787463)
> [#9689 (comment)](https://github.com/ant-design/ant-design/issues/9689#issuecomment-373319092)
> [#11937 (comment)](https://github.com/ant-design/ant-design/issues/11937#issuecomment-417194180)
> 
> > 面包屑就更加不想说了 就不能直接跟左侧menu共享一下数据吗 点击哪个就把层级直接显示出来 这样既能动态也能少写很多东西 如果要自定义的话 在判断传参的方式来啊 现在每次都要自己手写 累死 而且我们现在左侧菜单有事可以动态化配置的 每个人进去的菜单都不一样 菜单功能层级也是可以随意配置的情况下 我直接面包屑就是废的 因为我的父级永远都是会变的 我写死的面包屑没有任何用处
> 
> antd 中的组件要原子化，面包屑和 react-router 绑定的示例。在 Pro 中也有和 menuData 直接关联的面包屑：http://preview.pro.ant.design/ 你可以去看一看。

那个跟react-router合在一起的我试了 其实没看你们那个之前我就已经自己写了一个跟react-router绑定的东西了 但是后来需求变了 左侧的menu是根据用户权限走的 每个用户都可以有不一样的功能 而每个功能又可以挂在各自的模块下面 所以光是从路由判断是完全没有用的 因为你这个名字是跟左侧菜单对应不起来的

**Comment by afc163** [comment]
> Cascader AutoComplete Dropdown问题一样 如果我在下拉的过程中 想实现一个多选这么办 还有如果我展示的数据量很多 如何分页呢

- Cascader 目前不支持多选：https://github.com/ant-design/ant-design/issues/5698
- AutoComplete 本质是 Input，不应该多选，多选你可以用 `<Select mode="multiple">`。
- Dropdown 就是单纯下拉菜单，要做多选需要自己封装上层的选择逻辑。建议用 Select 更快捷。

**Comment by fangkyi03** [comment]
其次children:[]这个问题 就因为你们这个有意为之 所以我在不改动table底层代码的前提下 我必须要在数据获取的时候把children直接delete 不然那个+就会显示出来 但是我们这边业务根本不是这个需求 因为我在不点击的情况下 我根本不知道里面有多少东西 这就很坑了 我每次都要去点击一次 简直要气死客户

**Comment by afc163** [comment]
> 那个跟react-router合在一起的我试了 其实没看你们那个之前我就已经自己写了一个跟react-router绑定的东西了 但是后来需求变了 左侧的menu是根据用户权限走的 每个用户都可以有不一样的功能 而每个功能又可以挂在各自的模块下面 所以光是从路由判断是完全没有用的 因为你这个名字是跟左侧菜单对应不起来的

业务逻辑和复杂交互组件自然需要你封装，这不太可能由基础组件全部完成。

**Comment by fangkyi03** [comment]
如果menu自己共享一个数据层 或者在redux将当前选中的进行一下备份 我能从外部获取到的话 所有问题不就解决了

**Comment by afc163** [comment]
> 其次children:[]这个问题 就因为你们这个有意为之 所以我在不改动table底层代码的前提下 我必须要在数据获取的时候把children直接delete 不然那个+就会显示出来 但是我们这边业务根本不是这个需求 因为我在不点击的情况下 我根本不知道里面有多少东西 这就很坑了 我每次都要去点击一次 简直要气死客户

文档里其实写了解决方案：https://ant.design/components/table-cn/#components-table-demo-expand-children

<img width="834" alt="default" src="https://user-images.githubusercontent.com/507615/50487383-21eb6780-0a39-11e9-98a3-fb6b57b2baad.png">

**Comment by afc163** [comment]
> 如果menu自己共享一个数据层 或者在redux将当前选中的进行一下备份 我能从外部获取到的话 所有问题不就解决了

基础组件不会帮你做这个事。

**Comment by fangkyi03** [comment]
children这个 我又不是永远都是没数据的 有些是有 有些是没有的 我直接转换一下name有什么用的 治标不治本

**Comment by fangkyi03** [comment]
因为这个是树形结构 不改底层代码的情况下 我就得递归delete chidlren这个去实现 实在太浪费性能

**Comment by afc163** [comment]
直接把 `childrenColumnName` 设为 `'unexisted_whatever_name'` 就解决了。

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/50487775-8529c980-0a3a-11e9-919c-dfdeee01ceb4.png)
你确定把zhe这个改了就解决了？那我原来有children节点的呢 这么办 不是都显示不了了
我还特意去稍微翻了一下源码

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/50487914-100ac400-0a3b-11e9-943e-0db746bcf26e.png)
假设我childrenColumnName定义成unexisted_whatever_name 这个时候压根找不到对应值 直接返回item 但是item里面依旧有children的 有这个不就依旧会显示+号嘛

**Comment by fangkyi03** [comment]
找了一圈 包括rc-table都找了 childrenColumnName这个实现不了我想要的效果 因为我的children不是一直没数据的 只是有些是空数组 我想让它直接把+号箭头去掉 有数据的话就显示+号
![image](https://user-images.githubusercontent.com/30390014/50488288-bd320c00-0a3c-11e9-98b1-a8b848d8587e.png)
找了一圈这个东西也只能是改变一下取数节点而已

**Comment by fangkyi03** [comment]
> 直接把 `childrenColumnName` 设为 `'unexisted_whatever_name'` 就解决了。

你又忽悠我了

**Comment by fangkyi03** [comment]
相当精彩的一次绝杀
一个table居然嵌套的这么深
![image](https://user-images.githubusercontent.com/30390014/50488973-223b3100-0a40-11e9-91fc-e50aba941b73.png)
![image](https://user-images.githubusercontent.com/30390014/50488988-33843d80-0a40-11e9-8801-a55e5e0eaa59.png)
![image](https://user-images.githubusercontent.com/30390014/50488998-3d0da580-0a40-11e9-88a2-1a343f2341fa.png)
优秀 实在是太优秀了 一个icon 居然上演了一个连环杀
一个简单的判断 从2级父里面去调用去获取数据

**Comment by afc163** [comment]
我测试了受控的例子是没问题的：https://codesandbox.io/s/7zmz5jzjnj

你提供的重现去掉 `beforeUpload` 也会上传报错：https://codesandbox.io/s/7zk73329k0 

原因是 Upload 的 onChange 内返回的格式和其他组件不同，需要用 getValueFromEvent 转换一下：https://codesandbox.io/s/w0zqrmxjpw

也可以参考官方演示里的写法：https://ant.design/components/form-cn/#components-form-demo-validate-other

**Comment by fangkyi03** [comment]
我知道这个beforeUpload有问题 就是要让他有问题 毕竟我这个受控组件我不想让他在走一次 因为我自己都有意识的想把这个拦截掉了 我又为何需要他在走一次onChange呢 我都不想让他出现在上传列表里面

**Comment by afc163** [comment]
@fangkyi03 https://github.com/ant-design/ant-design/issues/15561#issuecomment-475108235
