### ISSUE TITLE
When using the title and sorter of the table at the same time, the tooltip on the title will be invalid.

### ISSUE THREAD

**Issue by Alexander-txj** [ant-design/ant-design#13984]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/knwzww14v)

### Steps to reproduce
Mouse hover to the place with sorter

### What is expected?
Can display the same effect as the Tootip, not the default title of the browser

### What is actually happening?
Show browser default title

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.5.2 |
| System | win10 |
| Browser | chorme 70.0.3538.67 |

**Comment by Alexander-txj** [comment]
Reproduce the link: https://codesandbox.io/s/knwzww14v

**Comment by Gwen106728** [comment]
@Alexander-txj 
I have the same problem
You can try the following  method~
title: <Tooltip title="xxxxxx"><span style={{position:"absolute"}}>xxxx</span></Tooltip>

**Comment by Gwen106728** [comment]
‘<Tooltip title="xxxx"><span style={{position:"absolute"}}>理论成本</span></Tooltip>’

**Comment by Gwen106728** [comment]
<T o o l tip title="xxx"><span style={{position:"absolute"}}>理论成本</span></T o o l t i p>,

**Comment by Gwen106728** [comment]
<T o  o l t  i p title="x  xx x  x"><s p an  style={{position:"absolute"}}>理论成本</s p a  n></T o o l  t i p>,

**Comment by Gwen106728** [comment]
<  T o o l t i p  > < s p a n style={{position:"absolute"}}>理论成本</ s p a n></ T o o l t i p>,
