### ISSUE TITLE
Table 的 expandedRowRender是否支持如果没有可以展开的数据，展开的Icon置灰不可点

### ISSUE THREAD

**Issue by ming995** [ant-design/ant-design#13985]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有些场景需要显示可展开行的Icon，但是需要判断是否有可展开的数据从而设置icon是否可以点击

### What does the proposed API look like?
只是想询问一下，同时建议Issues模板添加一个询问功能

**Comment by afc163** [comment]
你可以自定义 `expandIcon`: https://ant.design/components/table-cn/#API
