### ISSUE TITLE
tree组件onRightClick事件触发添加快捷菜单

### ISSUE THREAD

**Issue by smallSquirrels** [ant-design/ant-design#1398]
鼠标右键点击触发onRightClick，能否实现右键的时候在tree组件上弹出快捷菜单，添加自己的菜单选项？

**Comment by afc163** [comment]
http://react-component.github.io/tree/examples/contextmenu.html

**Comment by smallSquirrels** [comment]
谢谢

**Comment by ohmyauthentic** [comment]
@afc163 你好，我用的popover，使用state控制visible，可以实现右键的时候更改state使得popover 显示，但是在空白处点击怎么隐藏popover
