### ISSUE TITLE
如何自定义datePicker渲染input值？以及如何清除选中日期？ 

### ISSUE THREAD

**Issue by moxuan120** [ant-design/ant-design#13981]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1:目前我们有个业务就是把当天日期显示成至今，这个自定义渲染组件可以支持。但是选择至今后渲染在input上还是日期，我想要的是，选择至今后input显示至今。
2:现在我们自定义了个页足，新增一个取消与确定按钮，确定按钮是点击后关闭弹框，渲染日期。取消是想做成关闭弹框，并且清除选中的日期，但是目前api没有看到相关清除的方法。这个如何实现。

### What does the proposed API look like?
1.希望有支持自定义渲染input选中日期的方法。2.希望有相关方法可以支持清除选中日期。

**Comment by afc163** [comment]
1. `dateRender`。
2. 使用 value 做成受控组件。

**Comment by moxuan120** [comment]
value要求是moment类型的，至今只是字符串。

**Comment by afc163** [comment]
自行封装一下即可 `value={moment('2017-11-11')}`

**Comment by moxuan120** [comment]
我是想要input上渲染出至今这个字符串，并不是是时间

**Comment by moxuan120** [comment]
我月历上渲染当天都是至今，当我选择至今，我希望input上显示也是至今，并不是当天的日期。

**Comment by afc163** [comment]
那可能不太好处理，目前应该还不支持：https://github.com/ant-design/ant-design/issues/4394

**Comment by afc163** [comment]
你可以自己做一个自定义 Input 来渲染要展示的格式，然后配合 open 和 onOpenChange 来控制 DatePicker 的展开。

**Comment by moxuan120** [comment]
嗯嗯 谢谢。还有个问题是，如何调用清除日期。目前弄了个页脚，加了个取消按钮，希望点击它可以关闭弹框，并且清除选中的日期。目前控件是有清除的按钮，但是我希望也可以手动控制。

**Comment by afc163** [comment]
`value={null}`

**Comment by moxuan120** [comment]
好呢  谢啦

**Comment by afc163** [comment]
https://codesandbox.io/s/kom1wyykjv

前面一个简单的示例大概是这样，更多细节可能还需要你自行探索了。

**Comment by LeiYao123** [comment]
现在有个 inputRender 属性，可以实现自定义 input，不过现在的文档好像还没更新😅
