### ISSUE TITLE
搜索输入框输入超过框长度的数据时，能够拉动到最后一个字符进行编辑

### ISSUE THREAD

**Issue by yuntaiemma** [ant-design/ant-design#13992]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
搜索输入内容超过输入框时的编辑

### What does the proposed API look like?
open it

**Comment by afc163** [comment]
你这是要表达什么呢？

**Comment by zombieJ** [comment]
![kapture 2018-12-29 at 0 00 17](https://user-images.githubusercontent.com/5378891/50520721-d7cbba00-0afc-11e9-9af3-16ad115e1478.gif)

**Comment by afc163** [comment]
有更多信息给出再 reopen 吧。。。😄
