### ISSUE TITLE
多层抽屉，方向不同展示bug

### ISSUE THREAD

**Issue by mikexfreeze** [ant-design/ant-design#13991]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
举例第一层抽屉为left，第二层抽屉为bottom

### What is expected?
如果第二层抽屉为bottom，第一层不应在 第二层展开时移动自身位置

### What is actually happening?
如果第二层抽屉为bottom，第一层在第二层展开时移动自身位置

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.2.0 |
| System | windows |
| Browser | chrome |

**Comment by jljsj33** [comment]
这种使用场景，你不要用多层嵌套，，平级就可以了。。

**Comment by mikexfreeze** [comment]
> 这种使用场景，你不要用多层嵌套，，平级就可以了。。

Draw 内部使用另一个自带 Draw的组件的场景

**Comment by jljsj33** [comment]
不要放 Drawer 内部。。平级使用，，第一个 Drawer 里控制第二个的开关就行了。。。

**Comment by jljsj33** [comment]
[![Edit nky2n933n0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nky2n933n0)

**Comment by mikexfreeze** [comment]
https://codesandbox.io/s/n54vnr919p

第二Drawer是一个整体组件的情况如何处理，你的思路我明白只是这样组件就要被拆解了，复用成了问题。

**Comment by jljsj33** [comment]
唉，，你不要放里面随便你咋整都可以了，不要一根筋的觉得我这个东西就是抽屉组件里的抽屉，抽屉只是个容器，可灵活的配置，，你不打开抽屉，是什么东西都没有的。

实现方法有很多种啊，，传个 func 去控制就行了。。。

[![Edit 8kpy167o52](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8kpy167o52)

**Comment by jljsj33** [comment]
二级抽屉是给同一方向出现多个时使用的。。。

**Comment by mikexfreeze** [comment]
> 唉，，你不要放里面随便你咋整都可以了，不要一根筋的觉得我这个东西就是抽屉组件里的抽屉，抽屉只是个容器，可灵活的配置，如果是你这种场景，你完全可以在外层先占个坑，你不打开抽屉，是什么东西都没有的。
> 
> 实现方法有很多种啊，，传个 func 去控制就行了。。。
> 
> [![Edit 8kpy167o52](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/8kpy167o52)

是个方案，只是我在10个地方用要占10个坑，还是很麻烦。
我在css层面直接禁了，操作要简单的多。
还是希望你们能考虑把这个作为bug来处理，或者留个是否开动画的配置。

当然你要说“二级抽屉是给同一方向出现多个时使用的。。。”我也没意见。但是多个使用场景总是好的，不是吗

**Comment by jljsj33** [comment]
ant d 的二经抽屉应用方式本来就这样的，如果你执意要这样做，，你可以直接用 rc-drawer，，rc-drawer 没有包二级抽屉。。。https://github.com/react-component/drawer

**Comment by KiritoXF** [comment]
我也遇到了这个问题，贴一下解决方案
给 Drawer 加条样式禁掉 transform
```
style={{ transform: 'none !important' }}
```

**Comment by luichooy** [comment]
> 唉，，你不要放里面随便你咋整都可以了，不要一根筋的觉得我这个东西就是抽屉组件里的抽屉，抽屉只是个容器，可灵活的配置，如果是你这种场景，你完全可以在外层先占个坑，你不打开抽屉，是什么东西都没有的。
> 
> 实现方法有很多种啊，，传个 func 去控制就行了。。。
> 
> [![Edit 8kpy167o52](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/8kpy167o52)

二级抽屉里面如果要查找一级抽屉的 dom 元素呢，比如 clickoutside 类似的需求，或者二级抽屉某个元素要以一级抽屉的容器进行定位或者挂载在一级容器下的某个 dom 里面（可能得场景比如二级抽屉中的 modal, message等需要限制在一级抽屉的范围内），这些情况下要如何做呢。二级抽屉从底部出现，一级抽屉向左向右偏移本身就是个 bug 吧

**Comment by luichooy** [comment]
> 我也遇到了这个问题，贴一下解决方案 给 Drawer 加条样式禁掉 transform
> 
> ```
> style={{ transform: 'none !important' }}
> ```

style样式是加载子元素上的啊
