### ISSUE TITLE
RadioGroup  如何添加一个onChange 事件

### ISSUE THREAD

**Issue by gitcyrabbit** [ant-design/ant-design#1399]
如何在form，表单里为RadioGroup 添加一个onChange 事件，

我发现像这样[例子](http://ant.design/components/radio/#demo-radiogroup)添加，在form里如果同时添加了验证是不行的

目的是点击RadioGroup 的一个选项时，隐藏页面部分元素，哪位知道如何实现

多谢

**Comment by wjx8382** [comment]
@gitcyrabbit 你是怎么解决的啊？
用trigger吗？
