### ISSUE TITLE
InputNumber组件数值达到10e15-1时，会自动变到10e15

### ISSUE THREAD

**Issue by Darsoon** [ant-design/ant-design#13995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l7n1yqr8p9)

### Steps to reproduce
1. InputNumber组件输入框输入 10e15 - 1 数值，即9999999999999999
2. 焦点移出输入框，数据将变化为 10e15，即 10000000000000000

### What is expected?
数据不变化

### What is actually happening?
数据自动 1

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | Mac |
| Browser | Chrome71 |

**Comment by afc163** [comment]
这是 js 的精度问题，目前 InputNumber 不会支持 BigNumber，实现上也会比较复杂，如果遇到这种场景，建议用 `<Input />` 自行处理。
