### ISSUE TITLE
safari 表格同时设置x和y滚动会出现两条滚动条

### ISSUE THREAD

**Issue by xianwei-lu** [ant-design/ant-design#13994]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
在safari打开网址，锁定到“表头分组”示例，左右滑动，会出现两个左右滚动的滚动条

### What is expected?
只在底部有一条

### What is actually happening?
在title和data下方各出现一条

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | Mac OS |
| Browser | 10.1.2 |

---
当将表头的overflow关闭后正常，即class = "ant-table-header"的overflow属性

**Comment by afc163** [comment]
滚动条是有用的，这样无论在表头还是 body 里滚动，都可以联动滚动。

**Comment by afc163** [comment]
其实代码是隐藏的，你可以试试其他浏览器，已知情况是 safari 无论用什么办法也隐藏不了。另外，外接显示屏也会显示出来。目前没有可行的解决办法。

**Comment by afc163** [comment]
暂时先关了，你有好的解决方案也可以尝试一下，然后给我们 PR 或者继续在此回复就好。

**Comment by xianwei-lu** [comment]
.ant-table-header::-webkit-scrollbar {
    display: none !important;
}
我尝试了这个，可以解决这个问题

**Comment by afc163** [comment]
这样可能会导致列头对齐问题。https://github.com/ant-design/ant-design/issues/4637#issuecomment-280829518

**Comment by xianwei-lu** [comment]
![default](https://user-images.githubusercontent.com/28993048/50509680-cdd89580-0ac1-11e9-8ba9-9ee8ef52e7a3.png)
尝试了chrome和safari都正常，列是否fixed的两种也尝试列，未发现对齐问题

**Comment by afc163** [comment]
你的场景不会有问题，是 windows 电脑或者开启了固定滚动条，而且是某些 width 配置的情况。

这个问题目前 chrome 不存在，这段能否只针对 safari 生效，这样感觉可以一试。

**Comment by xianwei-lu** [comment]
身边没有条件测试windows，如果此问题只在safari出现，可以针对性处理

**Comment by afc163** [comment]
试一下开启了固定滚动条的情况

**Comment by xianwei-lu** [comment]
![default](https://user-images.githubusercontent.com/28993048/50510848-3e81b100-0ac6-11e9-8189-853ba2dede3d.png)
只要加上
.ant-table-header::-webkit-scrollbar {
display: none !important;
}
我在本地各种固定都试了，safari和chrome都没问题，你可以在直接在本地就可以测试效果

**Comment by afc163** [comment]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/507615/50511522-f1530e80-0ac8-11e9-895a-f1676f23b753.png">

**Comment by xianwei-lu** [comment]
![default](https://user-images.githubusercontent.com/28993048/50512074-121c6380-0acb-11e9-870e-baf68159d0c6.png)
设为始终后，对于滚动条还是一条，但是出现了对齐问题

**Comment by afc163** [comment]
是的，这里反复改过好几年了，比较复杂，轻易不敢乱动。

**Comment by xianwei-lu** [comment]
刚才研究了下，有这么一种解决方案
首先获取第一行的getBoundingClientRect().top，与它上方元素的clientHeight之和对比
如果前者比后者大(可以设一个误差)，滚动条伪元素设为“display: none”
反之设为“opacity: 0”
我本地测试了两种浏览器，都可行(发现Table是后续渲染的，计算过程用setTimeout异步)

**Comment by xianwei-lu** [comment]
昨天我回去试了下windows(Edge和chrome)，没有出现对不齐的问题，今天在你们官网demo上试了一下，本地测试正常，我把改的地方发出来，你可以在本地改了试试

**Comment by xianwei-lu** [comment]
![1](https://user-images.githubusercontent.com/28993048/50532480-cc0be200-0b54-11e9-97cf-f6ea75d0c11d.png)
![2](https://user-images.githubusercontent.com/28993048/50532482-d1692c80-0b54-11e9-8a0a-84648b7e23b4.png)
![3](https://user-images.githubusercontent.com/28993048/50532484-d5954a00-0b54-11e9-823b-06bcd48ecc89.png)

**Comment by 1120340041** [comment]
@xianwei-lu 可以给具体demo吗哥们？

**Comment by shen-lan** [comment]
IE下也是多个滚动条 .....
![Snipaste_2019-06-11_17-10-38](https://user-images.githubusercontent.com/21122615/59259214-e998b800-8c6b-11e9-973c-107d97786953.png)

**Comment by afc163** [comment]
4.0 里已经修复，3.x 里不再跟踪了。
