### ISSUE TITLE
Circle progress about 100% and 0%

### ISSUE THREAD

**Issue by BG5FD** [ant-design/ant-design#13997]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w67nx14mjw)

### Steps to reproduce
https://codesandbox.io/s/w67nx14mjw

### What is expected?
The text, such as 0%, 100%, should be in the middle of the circle.

### What is actually happening?
The text is not in the middle of the circle.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | windows/linus |
| Browser | chrome |

---
When the percent is 100%, the component Progress shows a icon of true. But in some cases, 100% doesn't means success. So I use the format function to rewrite the text to show 100%. But in this way, the text of 100% won't be in the middle of the circle. I hope you guys can solve this bug so that I don't have to rewrite the css of Progress. In addition, I don't think the progress should change the text into a icon when the percent is 100%. It wounld be happy for the devs, who use antd, to see that happen.

**Comment by Sid7736** [comment]
Was this issue fixed, I want to change the normal progress bar showing a true icon when the progress is 100%
