### ISSUE TITLE
日期选择框 DatePicker，选择完日期后直接得到焦点，没有考虑是否传了open=true参数，导致点击页面任何地方都回滚到输入处

### ISSUE THREAD

**Issue by baozi002** [ant-design/ant-design#14002]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/date-picker-cn/#header](https://ant-design.gitee.io/components/date-picker-cn/#header)

### Steps to reproduce
例如这样用：
``` javascript
<MonthPicker open={true} />
```

[#12475](https://github.com/ant-design/ant-design/issues/12475),感觉这个bug修的比较仓促：[https://github.com/ant-design/ant-design/commit/d81364c7a9cf90511f71603e801f09a9f6f3a753#diff-34c1c9d6622f2b32f87f4de9a64f099b](https://github.com/ant-design/ant-design/commit/d81364c7a9cf90511f71603e801f09a9f6f3a753#diff-34c1c9d6622f2b32f87f4de9a64f099b)

### What is expected?
如果props中有open并且等于true时，不自动获取焦点

### What is actually happening?
不管open是什么值都直接获取焦点

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.4.2  |
| System | mac os |
| Browser | chrome |

**Comment by Yangzhedi** [comment]
`onChange`函数 没!open @afc163  ill try fix this, ok?

**Comment by afc163** [comment]
focus 逻辑要放到 componentDidMount 里才比较严谨。

**Comment by Yangzhedi** [comment]
好的~

**Comment by Yangzhedi** [comment]
根据props的open控制默认展开的话，是不是要放在didMount里  毕竟用户传的open 只控制第一次的展开，放在getDerivedStateFromProps  每次更新都会被用户传的open 重置掉

**Comment by afc163** [comment]
`open={this.state.open}` 有可能控制多次展开关闭行为。

**Comment by Yangzhedi** [comment]
是有道理，但是像这个issue， `<MonthPicker open={true} />`  那不就永远关不上了？ 所以open是以组件内部的state.open 为主还是用户传的props.open为主？

**Comment by ztplz** [comment]
有优先级的

**Comment by Yangzhedi** [comment]
现在是 根据用户的props 更新 内部state 吧。
