### ISSUE TITLE
notification不能加入其它组件

### ISSUE THREAD

**Issue by davelet** [ant-design/ant-design#14000]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
弹出的notification期望能加入超链接等组件

### What does the proposed API look like?
弹出的notification期望能加入超链接等组件

**Comment by afc163** [comment]
https://codesandbox.io/s/y35l2pyokx
