### ISSUE TITLE
CheckboxGroup的rule required 为true时，initialValue是空数组或者不选中选项，此时会提示必输。没有选中项不能提示必输

### ISSUE THREAD

**Issue by bluemind7788** [ant-design/ant-design#14004]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/38r63525jm)

### Steps to reproduce
1. 点击check按钮提示不能为空；此时不应该提示
2. 选中几项，再反选掉，点击check按钮；此时不应该提示

### What is expected?
不应该提示必输

### What is actually happening?
提示了必输

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | latest |
| System | macos mojave 10.14 (18A391) |
| Browser | 版本 71.0.3578.98（正式版本） （64 位） |

**Comment by afc163** [comment]
呃，不希望提示『不能为空』的话，就不要加 required 。
