### ISSUE TITLE
Failing to compile

### ISSUE THREAD

**Issue by itzsaga** [ant-design/ant-design#14006]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/itzsaga/antd-error](https://github.com/itzsaga/antd-error)

### Steps to reproduce
Try to use `antd` in a TypeScript environment with TypeScript @ 3.2.2

### What is expected?
It to compile and not throw a TS2707 Error.

### What is actually happening?
I'm getting the following error upon compilation:
```
Type error: Generic type 'MouseEvent<T>' requires between 0 and 1 type arguments.  TS2707

    32 | export default class Alert extends React.Component<AlertProps, AlertState> {
    33 |     state: AlertState;
  > 34 |     handleClose: (e: React.MouseEvent<HTMLAnchorElement, MouseEvent>) => void;
       |                      ^
    35 |     animationEnd: () => void;
    36 |     render(): JSX.Element | null;
    37 | }
```

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | ^16.7.0 |
| System | MacOS |
| Browser | Firefox 65.0b6 |

**Comment by afc163** [comment]
Please upgrade `@types/react` to latest version: 16.7.18
