### ISSUE TITLE
上下滚动的时候可否设置左边导航菜单不随页面滚动

### ISSUE THREAD

**Issue by wzlee** [ant-design/ant-design#14018]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
增强页面滚动体验

### What does the proposed API look like?
上下滚动的时候设置左边导航菜单不随页面滚动

**Comment by afc163** [comment]
已经是了。

**Comment by wzlee** [comment]
Pro版本怎么实现这种滚动效果呢？

**Comment by afc163** [comment]
1. Pro 的问题建议你去 Pro 开 issue。
2. Pro 有个`fixSiderbar` 配置你可以试试。https://pro.ant.design/docs/theme-cn
