### ISSUE TITLE
走马灯Carousel

### ISSUE THREAD

**Issue by besoshanjun** [ant-design/ant-design#14014]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
数据可视化大屏显示两个页面，需要让两个页面进行切换，每个页面封装在一个组件中（1,2），然后把两个组件引入到了另一个页面（3），放在<Carousel><Carousel/>中，结果两个组件（1,2）分别被挂载了两次，在第一个组件（1）中，componentDidMount被执行了两次，导致同样的ajax被发送了两次，并且渲染也是。

### What does the proposed API look like?
希望解决这个问题。

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

**Comment by wendzhue** [comment]
估计这个问题跟 carousel 的实现有关, 现在底层基于 slick, 使用复制 DOM 的方式实现首尾的平滑滚动.
