### ISSUE TITLE
DatePicker只选择年份，设置了mode=year，但是无法触发onChange

### ISSUE THREAD

**Issue by zhangyanling77** [ant-design/ant-design#14017]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by Aladingding** [comment]
`<LocaleProvider locale={zhCN}>
                        {
                            getFieldDecorator(field)(
                                <DatePicker
                                    style={ style }
                                    placeholder={ placeholder || '请选择年份' }
                                    locale={ zhCN }
                                    // value={ this.state.time }
                                    open={ this.state.yearStartShow }
                                    mode='year'
                                    format='YYYY'
                                    // onChange={ this.handleChange }
                                    onOpenChange={ this.handleOpenChange.bind(this,'yearStart') }
                                    onPanelChange={ this.handlePanelChange.bind(this,'yearStart') }
                                />
                            )
                        }   
</LocaleProvider> `

do like this ,you will fix this bug, use onOpenChange and onPanelChange （maybe you need onFocus）

tks, 一江西流   [关于antd 日期组件只选择年份，设置mode=year无法获取value的解决办法 ]( https://www.cnblogs.com/zyl-Tara/p/10197177.html)

四个方法并用一定能完美实现你的需求，哈哈哈，官方说，你既然都单选了，为什么不用下拉框，说的好有道理，我竟无言以对

**Comment by zongzi531** [comment]
感谢 @Aladingding 的文章，@zhangyanling77 你们可以尝试这样解决问题：

```javascript
class Demo extends Component {
  hankPicker = null
  hankYearChange = v => {
    // 更新 v
    // 强制关闭补丁
    this.hankPicker.picker.setState({ open: false });
  }
  render() {
    return (
      <DatePicker
        ref={ref => (this.hankPicker = ref)}
        onPanelChange={this.hankYearChange}
        mode="year"
        format="YYYY" />
    )
  }
}
```

**Comment by KaivOU** [comment]
@zachguo 你把@Aladingding 的文章那种方法简化了，同时也解决了他哪种方法的：点击二次弹出弹窗的bug，这句this.hankPicker.picker.setState({ open: false }); that's good thx
