### ISSUE TITLE
table组件rowSelection中type设为radio时，selectedRowKeys修改后不生效

### ISSUE THREAD

**Issue by Liyuk** [ant-design/ant-design#1402]
### 需求描述
因为radio图标太小，不好点击；所以希望在点击该行时，便选中radio；

---
### 遇到的问题
当设置rowSelection的type为checkbox时，selectedRowKeys对于列表中的checkbox是受控的；
但是type为radio时，selectedRowKeys对于radio是不受控的。

---
### 实现代码
```javascript
getInitialState() {
	return {
		selectedRowKeys: [],
	}
}

...

onChange(selectedRowKeys) {
	this.setState({
		selectedRowKeys: selectedRowKeys,
	});
}

...

render () {
	const rowSelection = {
		type: 'radio',
		selectedRowKeys: this.state.selectedRowKeys,
		onChange: this.onChange,
	};
	return (<div>
		<Table
			rowSelection={rowSelection}
			onRowClick={this.onRowClick}
			...
		/>
	</div>);
}
```
---
### 实现的差异
希望实现的是通过修改selectedRowKeys，从而控制radio的选中项。

希望有解决方案，谢谢。

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/1346

下个小版本发布后修复。
