### ISSUE TITLE
github可能是中国最后一块没有被封的言论自由之地

### ISSUE THREAD

**Issue by hugetiny** [ant-design/ant-design#14022]
github可能是中国最后一块没有被封的言论自由之地，
这里不会屏蔽习近平，不会屏蔽共产党，
这里不会只许讲党好话，不许讲党坏话
这里是来看issue的人，八成是被领导或者被官老爷威胁了饭碗。
可惜那么多人还是改不了奴性，对于什么都不懂又能威胁你饭碗的官僚屁也不敢放，怒气全部撒在ant-design上。
满嘴什么什么精神，什么什么责任，却对罪恶来源视而不见或者根本看不见，谁叫他们是官，不敢惹?

横向对比：国际友人在ant-design issue留言，任何一个，要求fix圣诞彩蛋的留言，有没有骂的，有没有什么强烈谴责之类的？你或许会说他们不会被威胁饭碗，而我可能丢了工作，这一部分人大多做的是政府项目,ant-design也从来没说自己是什么政府级別的框架，所以让你丢工作的不是ant-design而是官僚。

我想起金星讲的空姐两副嘴脸，试想一下bootstrap出什么彩蛋，会不会一大堆人去issue强烈谴责。
所以建议ant-design面向国际吧，国内苟活的人继续苟活，因为苟利国家生死以。

**Comment by callG** [comment]
逻辑混乱，应黑而黑

**Comment by callG** [comment]
# 逻辑混乱，因黑而黑

**Comment by hugetiny** [comment]
> # 逻辑混乱，因黑而黑

你们还是被共产党教育的太好了

**Comment by prenukes** [comment]
吃着我党给你提供的粮食， 住着我党给你提供的稳定环境。 b事还那么多？  有能耐你 出国呗？

**Comment by xd199153** [comment]
https://www.zhihu.com/question/362774393/answer/949526389
