### ISSUE TITLE
Menu.Divider 在chrome中无法显示的问题

### ISSUE THREAD

**Issue by eruca** [ant-design/ant-design#14026]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/5526344/50546539-eed8ec00-0c63-11e9-9880-4ecb4b7982cd.gif](https://user-images.githubusercontent.com/5526344/50546539-eed8ec00-0c63-11e9-9880-4ecb4b7982cd.gif)

### Steps to reproduce
https://user-images.githubusercontent.com/5526344/50546539-eed8ec00-0c63-11e9-9880-4ecb4b7982cd.gif

### What is expected?
在firefox中表现正常

### What is actually happening?
感觉是bug

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | Mac 10.14.2 |
| Browser | Chrome:版本 70.0.3538.110（正式版本） （64 位） |

**Comment by eruca** [comment]
```jsx
 <SubMenu title={<Avatar>{nickname}</Avatar>}>
      <Menu.Item key="avanter">
        <Icon type="user" />
        个人设置
      </Menu.Item>
      <Menu.Divider/>
      <Menu.Item key="logout">
        <Icon type="logout" />
        退出
      </Menu.Item>
    </SubMenu>
```

**Comment by eruca** [comment]
I copy the js and css code to the codesandbox, but it works well!
but it happened in my project now, so I change some css value to find the bug!
the Icon in the MenuBar in the top, I change the Menu lineHeight 64px to 65px, the bug fixed, the other value happen again, second option is change the Menu theme to dark, it will work well too!
I think maybe the SubMenu css have some problem?

**Comment by afc163** [comment]
I don't know if I can't reproduce the problem...🤣

**Comment by ztplz** [comment]
@eruca `github repo` please.
