### ISSUE TITLE
Select option renders outside the input element

### ISSUE THREAD

**Issue by amolswnz** [ant-design/ant-design#14029]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/91y55jk554)

### Steps to reproduce
Code sample

### What is expected?
The selected form item value should show the selected option inside its own container, not outside its input box.

### What is actually happening?
The options values are shown correctly while using <br> tag in the <Select.Option> tag
When we select any value the selected values first line is render in the input box while the next line is rendered below the select option field.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | ^16.6.3 |
| System | macOS Sierra |
| Browser | Chrome Version 71.0.3578.98 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Try `optionLabelProp`

https://codesandbox.io/s/77x38nw1x

**Comment by dwb1994** [comment]
> Try `optionLabelProp`
> 
> https://codesandbox.io/s/77x38nw1x

Property 'label' does not exist on type of <OptionProps> of antd...
