### ISSUE TITLE
help wanted , unable to load icons

### ISSUE THREAD

**Issue by saikatharryc** [ant-design/ant-design#14034]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/tim-soft/react-starter-kit-antd](https://github.com/tim-soft/react-starter-kit-antd)

### Steps to reproduce
build command `yarn build --realease  `

### What is expected?
expecting icons to be loaded.

### What is actually happening?
icons are not loading, neither svg is building

| Environment | Info |
|---|---|
| antd | 3.3.3 |
| React | 16.2 |
| System | OSX latest |
| Browser | Chrome latest |

---
so, i'm using a react with antd starter kit [https://github.com/tim-soft/react-starter-kit-antd].
I have already created few issues regarding its not able to build  and icon loading issue,
no reply so far,seems they discontinued.
neither i'm getting any clue for those issue from google search and stackoverflow.
so if the members of antd helps to resolve it will be a releief.

issue:
after the build finish, the icons are not loading. want to know how do i manage the webpack .  and how do i add icons to it. 
also if there is any cdn for icons, how should i use it.
Thanks.

**Comment by ycjcl868** [comment]
I couldn't run the starter kit, the error messages were

```bash
react-starter-kit-antd/node_modules/_@babel_core@7.2.2@@babel/core/lib/config/full.js:135
    throw e;
    ^

Error: [BABEL] /Users/jcl/code/github/antd/react-starter-kit-antd/tools/run.js:
As of v7.0.0-beta.55, we've removed Babel's Stage presets.
Please consider reading our blog post on this decision at
https://babeljs.io/blog/2018/07/27/removing-babels-stage-presets
```

Could you describe the steps to reproduce in detail？

**Comment by zombieJ** [comment]
@saikatharryc , what's next step after `yarn build --realease`? How to start app and which page should check?

**Comment by saikatharryc** [comment]
Hi, thanks for trying to help me out.
but after debugging for hours, it seems to be a cyclic dependency,
i fixed it somehow, without importing `antd` components like this:
`import {Icon, Dropdown} from 'antd'`
doing like this 
`import Icon from 'antd/lib/icon'`
solved my problem!
Thanks.
