### ISSUE TITLE
Input Component lose focus when addonAfter is added in run time

### ISSUE THREAD

**Issue by YasmineHamdy** [ant-design/ant-design#14033]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zxxo9w61m3)

### Steps to reproduce
start typing in the input

### What is expected?
the input keeps focus

### What is actually happening?
it will lose the focus after the first character

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.4.1 |
| System | ubuntu 18.04 |
| Browser | Chrome 70.0.3538.102 64 bit |

**Comment by ztplz** [comment]
You didn't use it in the right way, I have updated [your demo](https://codesandbox.io/s/2w0y2r02ky)

**Comment by zombieJ** [comment]
Since change Input with `addonAfter` will change the dom structure. The input element will render with a new one which makes focus lost. You should set focus if addon is dynamic update: https://codesandbox.io/s/8129y91269
