### ISSUE TITLE
表格列锁定滚动条展现问题以及不一致问题

### ISSUE THREAD

**Issue by spllot** [ant-design/ant-design#14038]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
不同的系统，展现不一致

### 1. MacBook Pro (Retina, 15-inch, Mid 2015) MacOS 10.14.2  chrome 71.0.3578.98 

[效果图](https://img.alicdn.com/tfs/TB1HQMbzwHqK1RjSZFEXXcGMXXa-1922-546.png)

### 2. MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) . Mac OS 10.13.4 .  chrome 71.0.3578.98

[效果图](https://img.alicdn.com/tfs/TB199L_zwHqK1RjSZJnXXbNLpXa-1698-556.png)

### What is expected?

1.滚动条不占表格行的空间

2.滚动条起始位置不应该在左侧的锁定列内

3.不同的系统，UI效果应该保持一致

### What is actually happening?
见重现步骤的效果图

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16 |
| System | MacBook Pro MacOS 10.14.2 |
| Browser | chrome 71.0.3578.98 |

**Comment by zombieJ** [comment]
这个是因为默认隐藏滚动条的设置，导致滚动条在元素内不占空间使得被更高一层的 fixed column 遮盖。目前没有什么好的处理办法……
