### ISSUE TITLE
DatePicker日期显示格式不统一

### ISSUE THREAD

**Issue by langjt** [ant-design/ant-design#1403]
## 问题描述
DatePicker日期显示格式不统一。具体见下图
![image](https://cloud.githubusercontent.com/assets/2832575/14483962/0943c4c2-017f-11e6-96f6-fa0fd164048f.png)
建议按照format的格式来，即上图显示： 03/30/2016 应该更合理些。
我看了源码，能否在https://github.com/ant-design/ant-design/blob/develop-1.0.0/components/date-picker/createPicker.jsx 的<TheCalendar ...>中增加formatter属性，即：
`<TheCalendar formatter={props.format} ...>`
我在本地添加上述代码后，可以实现格式统一，不知我的思路是否正确，效果图：
![image](https://cloud.githubusercontent.com/assets/2832575/14484128/6930c672-0180-11e6-87ec-1c36c3919bdf.png)

## 示例

(Ant官网. http://ant.design/components/date-picker/#picker-demo-formatter)

**Comment by afc163** [comment]
感谢反馈~
