### ISSUE TITLE
react-scripts 2.1.2 cannot find module webpack.config.dev

### ISSUE THREAD

**Issue by guanpengchn** [ant-design/ant-design#14047]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n5z4n2vpvm)

### Steps to reproduce
Config as [Use in create-react-app](https://ant.design/docs/react/use-with-create-react-app-cn)
1. Create react app with react-scripts@2.1.2 
```
create-react-app antd-demo
```
2. Add antd@3.11.6 
```
yarn add antd
```
3. Add react-app-rewired 
```
yarn add react-app-rewired
```
4. Add babel-plugin-import 
```
yarn add babel-plugin-import
```
5. Config config-overrides.js
6. Run project
```
yarn start
```
7. You will see an error 
```
Cannot find module: webpack.config.dev
```

### What is expected?
No error

### What is actually happening?
```
antd-demo git:(master) $ yarn start
yarn run v1.12.3
$ react-app-rewired start
internal/modules/cjs/loader.js:582
    throw err;
    ^

Error: Cannot find module '/Users/aaron/Code/test/antd-demo/node_modules/react-scripts/config/webpack.config.dev'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/aaron/Code/test/antd-demo/node_modules/react-app-rewired/scripts/start.js:9:23)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | MacOS |
| Browser | Chrome 71.0.3578.98 |

**Comment by guanpengchn** [comment]
react-scripts@2.1.1 has no problem. But react-scripts@2.1.2 has.

**Comment by apollo7733** [comment]
这个你去react-app-rewired的github上自己看，作者写的很明白，另外，react-app-rewired作者本人估计也不维护了。

**Comment by ycjcl868** [comment]
Because of the create-react-app PR [#5722](https://github.com/facebook/create-react-app/pull/5722).  related issue [[Bug]Error: Cannot find module](https://github.com/sharegate/craco/issues/61)

**Comment by tangdw** [comment]
用这个  https://github.com/rescripts/rescripts

**Comment by ycjcl868** [comment]
Duplicate of [#14094](https://github.com/ant-design/ant-design/issues/14047)

**Comment by akbarbobomurodov** [comment]
I  have a problem the same above problem

**Comment by akbarbobomurodov** [comment]
how to solve this problem

**Comment by acomito** [comment]
@akbarbobomurodov Did you solve this?
