### ISSUE TITLE
建议每次升级后发布一个发布后的JS文件和对应的CSS文件

### ISSUE THREAD

**Issue by iambluebird** [ant-design/ant-design#1404]
我在用ANTD的时候基本上不会去修改原有的组件，一般都是通过现有的ANTD组件组合新的组件使用，每次ANTD升级后都需要针对ANTD单独去编译一次，如果官方能够直接提供一个编译好的JS文件就方便了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1338

强烈建议提问前先搜索一下。

**Comment by iambluebird** [comment]
没有发现相关问题。。。
