### ISSUE TITLE
Rerendering all form input fields when just one input is changed

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#14054]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-register](https://ant.design/components/form/#components-form-demo-register)

### Steps to reproduce
Just change one input value with `Highlight updates` turned on in React dev tools to see, that every input is rerendered with each change.

### What is expected?
On input change, only this input should get rerendered (and probably any other components that use `getFieldValue` or `getFieldsValue` inside.
I've been using Ant Design for quite a while and the form works brilliantly, but recently I had to create a really complex form with plenty of dynamic fields and rerendering in this scenario makes the form really slow.

Hence my questions - is this my fault of not properly using the form? Is this maybe the way it has to be done so each field rerenders when another is changed? Or maybe there is a bug somewhere? I would like to receive some more information :) Thanks in advance!

### What is actually happening?
As described above

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | macOS |
| Browser | Any browser |

**Comment by ztplz** [comment]
This is a known performance issue. But because many forms are in use, we have been very cautious about optimization because it is easy to cause break change. If you are running into some performance issues, please split it into multiple forms.

**Comment by Ancinek** [comment]
@ztplz Thanks for the fast response :)
I can imagine the greatness of issues if you were to introduce any breaking change in this field.

I've already split the form into two to separate the most dynamic parts from those, that are just there all the time.

Do you guys already thought about some idea how to make it better so maybe I (and other devs viewing this thread in the future) can try it ourselves?

**Comment by ztplz** [comment]
It seems that there is not much way other than splitting. In fact, this is a common problem with HOC forms. About new form API: https://github.com/ant-design/ant-design/issues/10640

**Comment by Ancinek** [comment]
Thanks for that. An API like this would be a great addition :) Guess this can be closed for now.
