### ISSUE TITLE
Wrapp Select.Option with Tootltip

### ISSUE THREAD

**Issue by luisgurmendez** [ant-design/ant-design#14057]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Select with fixed width that have options that overflow the total space

### What does the proposed API look like?

`<Option tooltip={string | ReactNode} />`

**Comment by afc163** [comment]
https://codesandbox.io/s/73vkjrkjkq

**Comment by luisgurmendez** [comment]
@afc163 I've tried a lot of variations of https://codesandbox.io/s/xlyp6z9rzw (also as functional component) and cound't make it work, do you know why am I doing something wrong?

**Comment by afc163** [comment]
I found nothing wrong in https://codesandbox.io/s/xlyp6z9rzw

<img width="982" alt="image" src="https://user-images.githubusercontent.com/507615/50639500-aa6b8a00-0f9c-11e9-9d01-6c927ae21fa8.png">

**Comment by luisgurmendez** [comment]
You are checking https://codesandbox.io/s/73vkjrkjkq not https://codesandbox.io/s/xlyp6z9rzw

**Comment by afc163** [comment]
You can see the screenshot of my reply, it is https://codesandbox.io/s/73vkjrkjkq

**Comment by luisgurmendez** [comment]
Yes, but I want to know whats wrong in https://codesandbox.io/s/xlyp6z9rzw
