### ISSUE TITLE
Feature request - allowClear for Input.Search

### ISSUE THREAD

**Issue by varun-dev** [ant-design/ant-design#14055]
I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and found some indirect discussions to this feature. 
#7970, #5807

### What problem does this feature solve?
Currently there is no way to clear the search.

### What does the proposed API look like?
```
    <Input.Search
      allowClear
      placeholder="input search text"
      onSearch={value => console.log(value)}
      style={{ width: 200 }}
    />
```

Behaves just like this feature on `AutoComplete`

**Comment by ztplz** [comment]
Already have this feature, may be released in the next release. ref: https://github.com/ant-design/ant-design/pull/13939

**Comment by varun-dev** [comment]
thanks
