### ISSUE TITLE
Collapse的Icon替换修改

### ISSUE THREAD

**Issue by zy888802** [ant-design/ant-design#14058]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需要替换Collapse头部Icon的默认样式

### What does the proposed API look like?
可以提供一个修改Icon的Api

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/pull/12212

**Comment by zy888802** [comment]
![image](https://user-images.githubusercontent.com/16602562/50625389-d8cc7380-0f62-11e9-9b9f-e76cc27bd055.png)
我根据他的操作 替换成3.9.0并没有这个参数可以使用

**Comment by zy888802** [comment]
能否通过继承的方式搞定？我通过继承的方式Icon不会转动了
