### ISSUE TITLE
InputNumber: Uncontrolled Input

### ISSUE THREAD

**Issue by arifemrecelik** [ant-design/ant-design#14069]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
I'm using InputNumber. I'm giving value of component from state. But when I don't change state and press key still I can see the characters on the input component.

### What is expected?
It should be a controlled input component. And I should change value from my state.

### What is actually happening?
I can see values when I press key on input component when I don't change the state.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.4.2 |
| System | Windows 7 |
| Browser | Google Chrome |

**Comment by ztplz** [comment]
Could you provide a `online demo` or `mini git repo` for your problem ?

**Comment by arifemrecelik** [comment]
@ztplz https://codesandbox.io/s/oqjzlrwk5q

I added the demo link. In here I'm expecting don't see any changes in input component. Because I'm not changing state. But I can see the values when I key press. So I think one part of code overwrite my state.

**Comment by ztplz** [comment]
@arifemrecelik  Because you didn't set value to state. 
![image](https://user-images.githubusercontent.com/17755202/50687507-7e174280-105c-11e9-985b-a115b10af897.png)

**Comment by arifemrecelik** [comment]
@ztplz I think you misunderstood me. Even I'm not changing the state I can see the values on input component until I trigger blur function. But also it shouldn't show in Input component when I key press. Because I'm not changing state.

**Comment by ztplz** [comment]
Okay, I see. Thanks for your explanation.

**Comment by zombieJ** [comment]
Hi @arifemrecelik ,
It's by design. InputNumber support `formatter` which means value may not mapping with display value. When user inputing, the value in input may not correct convert to number (like `123.`). This makes controlled value may not covert back to current input string.
So we adjust sync stage to InputNumber when it's not active to make sure is not converted by accident.
