### ISSUE TITLE
cascader的国际化为什么只添加了default和zn-cn的

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#14070]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/commit/a2a016d8cfaa8cc2eff2a865024cf72771553f89](https://github.com/ant-design/ant-design/commit/a2a016d8cfaa8cc2eff2a865024cf72771553f89)

### Steps to reproduce
如上链接所示，cascader的国际化在global里，但是只添加了英文和简体中文的

### What is expected?
全部语言都添加

### What is actually happening?
只添加了英文和简体中文的
![image](https://user-images.githubusercontent.com/22299421/50636086-b6048400-0f8f-11e9-9888-241f847d9de9.png)

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | react16 |
| System | win10 |
| Browser | chrome71 |

---
另： 这样设计的话，我想在antd的基础上增加一个未找到数据`noData`的国际化，有点问题啊

**Comment by mraiguo** [comment]
@zombieJ  语言这个知道怎么处理了；我看了empty组件，可能我描述的有问题。我想要在cascader组件里面修改内部代码，使其做到节点无数据时后面显示一个提示。如下图：
![image](https://user-images.githubusercontent.com/22299421/50670784-c0169900-1008-11e9-9a8b-062184d27c36.png)
这种情况下，他的国际化emptyText应该放在哪个key下面；是`global`还是`cascader`?

**Comment by afc163** [comment]
PR is welcome~ closing now
