### ISSUE TITLE
Dynamic form doesn't allow you to use any other arbitrary key except for "key"

### ISSUE THREAD

**Issue by rewnad** [ant-design/ant-design#14075]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l4lx92z46z)

### Steps to reproduce
change all the field keys from "key" to any arbitrary key like "foo". 

### What is expected?
Pressing "   Add field" should dynamically create another field.

### What is actually happening?
It doesn't work and the console returns:

Warning: Cannot use `setFieldsValue` until you use `getFieldDecorator` or `getFieldProps` to register it. 

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 3.9.6 |
| System | MacOS 10.14.1 |
| Browser | Google Chrome 70.0.3538.110  |

---
This should in theory work. There should be nothing stopping dynamic forms for having a different field key other than "key"

**Comment by afc163** [comment]
You codesandbox works fine.

**Comment by rewnad** [comment]
@afc163 Whoops! [try this](https://codesandbox.io/s/5zk19zwzyx).
Notable points of interest: lines `16`, `31`, `67` and `68` where I've named the field key `foo`. It seems to only work if the field key is called `keys`.

**Comment by zombieJ** [comment]
@rewnad, you get field by named `foo` but set field value with name `keys`. You should change all the name from `keys` to `foo`: https://codesandbox.io/s/xyow5z02q
