### ISSUE TITLE
IE8 Velocity Bug

### ISSUE THREAD

**Issue by ansonchen** [ant-design/ant-design#1407]
IE8 调用了 const SubMenu = Menu.SubMenu;
就会报
**IE8 and below require jQuery to be loaded before Velocity**

代码如：
import '../common/lib';
import '../component/index.less';
import ReactDOM from 'react-dom';
import React from 'react';
import { Menu,  Icon } from 'antd';
const SubMenu = Menu.SubMenu;
...

**Comment by benjycui** [comment]
> IE8 and below require jQuery to be loaded before Velocity

It's not bug, please Google error message.
