### ISSUE TITLE
是否可以支持多列同时排序？现在Table组件的排序功能总是互斥的。

### ISSUE THREAD

**Issue by shenguotao2015** [ant-design/ant-design#14079]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
多个字段列同时排序的问题

### What does the proposed API look like?
在原有的排序基础上，支持返回多列排序的数据结构。

**Comment by afc163** [comment]
Duplicate of #10946
