### ISSUE TITLE
是否可以为Table组件的排序功也增加类似于筛选的(filterDropdown)参数，来自定义排序的UI界面和排序操作？

### ISSUE THREAD

**Issue by shenguotao2015** [ant-design/ant-design#14078]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我的Table中有个字段列包含了多种数据，这些数据都是以标签(Tags)的形式展示，每种数据也都有具体的数量，现在的需求希望为这个列增加一个排序功能，并可以支持自己去选择要排序的数据（例如点击这列的排序按钮，展开一个浮层，在里面勾选数据类型，然后传给后台接口）进行排序。

### What does the proposed API look like?
类似于 Filter 即可，正好已经存在了 sortOrder 参数，可以自定义排序按钮的状态。

**Comment by afc163** [comment]
建议用 filterDropdown 进行自定义，里面的内容和交互都是可以控制的。
