### ISSUE TITLE
Disabled `Select.Option` can be selected in `tags` mode by typing the value and then can't be deselected

### ISSUE THREAD

**Issue by hon2a** [ant-design/ant-design#14089]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/13kv4j8n5j)

### Steps to reproduce
1. Click into the input. Note that the "f15" option is disabled and can't be selected by clicking on it.
1. Start typing "f15" (e.g. type just "f"). Note that the disabled "f15" option is no longer shown in the drop-down.
1. Finish typing "f15" and press `{enter}`. Note that the "f15" option is now selected and can't be deselected (either by pressing `{delete}` or by clicking on it in the drop-down).

### What is expected?
- The `Select` drop-down should show disabled options matching the search expression, not hide them.
- When the search expression matches exactly an existing disabled option, only that option should be visible and it shouldn't be selectable.

### What is actually happening?
- Disabled options are hidden on search.
- Disabled options can be selected by typing their exact value and pressing `{enter}` and can't be deselected.

Note that all of this is in `mode="tags"`.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | MacOS Mojave (10.14.2) |
| Browser | Chrome 71.0.3578.98 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
Will add warning in tags mode if using option with disabled prop.

**Comment by Ammar11013** [comment]
Hi there all, i want to programitically deselect select tags, thanks.
