### ISSUE TITLE
Cannot find module react-scripts/config/webpack.config.dev, during antd theme customisation

### ISSUE THREAD

**Issue by kushalmahajan** [ant-design/ant-design#14085]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Ok. I've my create-react-app project as a typescript project via `--typescript` flag.

Now following this [guide][1] 

I started making modification for scripts. 

Here is what it looks like

```
"scripts": {
    "start": "react-app-rewired start && node scripts/start.js",
    "build": "react-app-rewired build  && node scripts/build.js",
    "test": "react-app-rewired test --env=jsdom && scripts/test.js"
},
```
and my config-overrides.js is below

```
const tsImportPluginFactory = require('ts-import-plugin')
const { getLoader } = require("react-app-rewired");
const rewireLess = require('react-app-rewire-less');

module.exports = function override(config, env) {
  const tsLoader = getLoader(
    config.module.rules,
    rule =>
      rule.loader &&
      typeof rule.loader === 'string' &&
      rule.loader.includes('ts-loader')
  );

  tsLoader.options = {
    getCustomTransformers: () => ({
      before: [ tsImportPluginFactory({
        libraryDirectory: 'es',
        libraryName: 'antd',
        style: 'true',
      }) ]
    })
  };
  config = rewireLess.withLoaderOptions({
    javascriptEnabled: true,
    modifyVars: { "@primary-color": "#1DA57A" },
  })(config, env);

  return config;
}
```
  [1]: https://ant.design/docs/react/use-in-typescript

### What is expected?
Yarn start gives an error as stated in issue title

### What is actually happening?
yarn start should run the project

---
So basically, I'm not sure if I'm writing the scripts correctly, it was just a guess work as no formal guide for create-react-app ts version is available for it. Please note I don't want to use `antd-ts-demo` repo as it threw me an error upfront on `yarn start` in `tsconfig.json` saying `config/.env should be in root of project`. I've filed this separately [here](https://github.com/imzengyang/antd-demo-ts/issues/1)

But I prefer not to use that I've almost done everything.  I was using `antd` fine via webpack.config .js before I hit the point to customisation need to override less variables and follow use in Typescript guide of yours in docs. 

Looking forward to tweak for help. Thanks!

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.2 alpha |
| System | MacOs High Sierra |
| Browser | Chrome 71.0.3578.98 |

**Comment by afc163** [comment]
You can trace https://github.com/ant-design/ant-design/issues/12878 and it is better to help us rewriting this documentation which maybe outdated now.
