### ISSUE TITLE
Drawer that does not limit interaction outside drawer

### ISSUE THREAD

**Issue by edencorbin** [ant-design/ant-design#14080]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the drawer is active it makes it impossible to interact with the page outside the drawer. In my application I would like the drawer to only catch interactions if its z-index is higher, IE not mask the rest of the page. I can make the mask not visible, but not disable its interaction override.

### What does the proposed API look like?
preventBackgroundInteraction = false (defaults to true)

**Comment by afc163** [comment]
`mask={false}`
