### ISSUE TITLE
时间选择控件交互有点不理解

### ISSUE THREAD

**Issue by freestyle21** [ant-design/ant-design#1408]
对当前的时间选择空间交互感到奇怪，周围同事和不少用户都是这个反馈。

我们觉得更能接受的交互是，`DatePicker` 点击某天后就直隐选中然后隐藏选择框。

当有 `showTime` 时，当前需要点击时间选择后，再点击其他地方使时间选择浮层隐藏，再点击确定按钮，更好的交互不应该是点击时间选择后直接隐藏选择框。

希望综合考虑下是否有道理~

**Comment by afc163** [comment]
目前的交互是这样的：

1. DatePicker 点击某天后选中并隐藏。
2. 当有 `showTime` 时，选完时间后，可以直接点击 `确定` 完成选中。

---

至于时间选择为何不会自动消失的原因是，`时分秒` 三者地位是平行的，视觉上也是平等的，选完谁直接关闭都不太合适。

而日期面板的视觉效果，`日` 是较为明显的最终选项。

**Comment by mongris** [comment]
可以为 `时分秒` 三者分别记录 `touched`，在三者（已启用的）均 `touched == true` 时，就自动关闭。这样可以满足绝大部分用户的体验。

**Comment by freestyle21** [comment]
同意 @mongris 。

期望的交互是：

1. 时分秒 至少三个都点击过一次后，点击任何一个都消失
2. `日`如果无 `showTime`则点击时间后选中时间并关闭; 如果有 `showTime`，判断是否选中过时间(同1)，是则关闭，否则不关闭。

**Comment by afc163** [comment]
这个不好的，用户很可能记不住点过哪个的，这样反而在操作过程中不确定点了哪个就关闭了，更容易让用户感到奇怪。

**Comment by mongris** [comment]
最多只有三项，而仅有`时`或`时分`的场景也是非常多，还不至于会导致“记不住”
我们（的开发和测试）在实际操作中，也习惯于按顺序点击，认为点击完之后即应关闭

**Comment by Chinglik** [comment]
目前这个时间组件的交互确实不太好，我们可以继续讨论下方法，不过个人不太支持这个『三项选完就关闭』的建议，因为用户行为具有很强的不可控性，不是人人都是按顺序点的，突然关闭会很让人错愕，什么时候关闭还是应该让用户自己决定呢~~

**Comment by freestyle21** [comment]
@Chinglik 我上面的意思不是『三项选完就关闭』，而是『三项至少每个都选择一次就关闭』。

其实这种方案也有问题，用户第二次去改变`时`、`分`、`秒`就需要三次，不好。

提这个issue的本意在于，我这里的用户和测试人员第一次选择时间后不知道怎么确定，点击其他地方关闭整个 `DatePicker`却发现白操作了，不知道去点击下面的`确定`按钮。

知道怎么确定后，又觉得麻烦，需要先把时间选择关闭，再去点击日历的确定按钮。所以我们可以想想办法让他更智能。

**Comment by afc163** [comment]
@Chinglik 的『三项选完就关闭』的意思和 @freestyle21 的『三项至少每个都选择一次就关闭』含义应该是一致的。这种交互用户无法很明显的确认点击那个之后会关闭。（除非在视觉上上标识哪个是本次点过的）

原来的交互确实不完美，但是目前貌似没有更好的替代方案。

**Comment by afc163** [comment]
我的建议，给 TimePicker 加上`确定`按钮，用于选择完关闭。

**Comment by afc163** [comment]
![](https://zos.alipayobjects.com/rmsportal/jGUTPqniaCgdOzt.png)

![](https://zos.alipayobjects.com/rmsportal/ilWhwevdtlLLlzs.png)

@freestyle21 @mongris
