### ISSUE TITLE
Modal.confirm 与 form.validateFields 组合使用导致输入框无法输入

### ISSUE THREAD

**Issue by sayll** [ant-design/ant-design#14084]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vnnm6k9445)

### Steps to reproduce
直接操作，点击test按钮重现

### What is expected?
输入框，可以输入数值

### What is actually happening?
输入框，可以无法输入

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.5.2 |
| System | mac |
| Browser | chrome |

**Comment by sayll** [comment]
找到解决方案了，但这部分算我个人理解问题么？如果是的话，可以关闭该 Issues 了。
目前解决方案是：为Modal.confirm 的 content 内容单独抽离，再为单独的它 调用 Form.create()就可以了。

**Comment by zombieJ** [comment]
你的解决方案是对的， confirm 是 antd 内部独立创建了一个上下文。所以外面的 form 穿不过去。
