### ISSUE TITLE
Table设置scroll后错位

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design#14096]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-grouping-columns](https://ant.design/components/table-cn/#components-table-demo-grouping-columns)

### Steps to reproduce
有15列数据，导致table直接被挤压出右边了，然后加上scroll，给每个column定了width，现在是依然会错位，无论如何调整scroll.x都是错位的，
还有如果不设置scroll.y的话，title和内容就居然对齐了，而且数据少的大致40条以下也是对齐的，过百条的话就开始错位变大 。
数据复杂的话，scroll.x也很难设置吧

### What is expected?
标题与内容对齐

### What is actually happening?
table错位

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.4.1 |
| System | win10 |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/3ca6a18546d0594b9d769e69483f36ac62e873b6#diff-1b12506dffbc344b0c87fd7cd4b8f1d9R12

**Comment by Veigar-C** [comment]
[https://codesandbox.io/s/ypnyz37vz9](url)

大概像这样，现网的数据测的话，偏离就更大了

**Comment by afc163** [comment]
https://codesandbox.io/s/k984px7y2r

另外可以看看：https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241
