### ISSUE TITLE
Values contained in existing values can't be added when using `fiterOption` in `tags` mode

### ISSUE THREAD

**Issue by hon2a** [ant-design/ant-design#14090]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/626jl9q2jk)

### Steps to reproduce
1. Type "f" into the input. Note that only the disabled "f15" option is shown (no impromptu "f" option) and pressing `{enter}` doesn't add the "f" tag.
1. Click outside the input. Note that the "f" tag has been added.
1. Now type "b" into the input. Note that only the enabled "b11" option is shown and pressing `{enter}` selects it instead of adding the "b" tag.

### What is expected?
The option to add the currently typed in search as a new value should always be shown unless the search exactly matches an existing option and it should be possible to add the value.

### What is actually happening?
The new value can't be added properly as long as it's a sub-string of an existing value. It can only be added by clicking outside the input.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | MacOS Mojave (10.14.2) |
| Browser | Chrome 71.0.3578.98 (Official Build) (64-bit) |

---
Note that all of this is happening only when (a trivial) `filterOption` is used. I've examined what passes through `filterOption` during the searches and found that it gets passed an additional option aside from those originally rendered into the `Select`. The option looks weird - it has the same `key` as the existing option then proffered in the drop-down - but it's distinguishable from the others. But even when I adjust the `filterOption` to distinguish and always show it, [nothing changes](https://codesandbox.io/s/xl786qnwoz). _(Note the 2 options logged into the console on search.)_

IMO the "add the current search as new value" pseudo-option shouldn't get passed to `filterOption` at all and should be shown same as if `filterOption` wasn't used.

**Comment by ztplz** [comment]
I just looked into it, it is actually the expected behavior.
![image](https://user-images.githubusercontent.com/17755202/53298973-eec62880-386f-11e9-9d97-eb076f27fae0.png)
`Enter` means select the value in options, not adding value to options.

**Comment by ztplz** [comment]
Close it for it's a false positive. Feel free to reopen it if you have any question.

**Comment by hon2a** [comment]
@ztplz Please note that this is happening on a `<Select mode="tags">`. The behavior is IMO clearly not desired, so I'll try to explain it better. When you enter the _"f"_ in `tags` mode, the first visible option in the drop-down is supposed to be just _"f"_. It's supposed to be enabled and pressing `{enter}` is supposed to select it, i.e. add the it to the selected values/tags. And without `filterOption` all of this is happening

The problem is that when I try to use `filterOption` together with `mode="tags"`, this special pseudo-option on top of the list that is facilitating the `tags` mode (it'd be just the plain `multiple` mode without it) is sometimes no longer shown, as described in the OP. This makes it impossible to have both the `tags` mode and custom filtering in the same `Select`.

I can't reopen an issue in your repo, please do so yourself. Please let me know if you need me to explain some detail better.

**Comment by ztplz** [comment]
I used to think that this is a bug. But after I discussed with @zombieJ , I clarified the use of two different modes of `multiple` and `tags`. 
`multiple` means you can choose from the existing options, some options can be banned.  
`tags` means you can type as you like, options should not be disabled.

**Comment by zombieJ** [comment]
In `tag` mode, user can type whatever they and should not use disabled option. I think we can add warning for this.

**Comment by hon2a** [comment]
@ztplz I'd say that "because that's how it is implemented" is really no reasoning at all. My expectation of the `tags` mode is for it to work the same way I've seen it work everywhere else in the past - allow setting multiple values by either selecting from a (possibly empty) list of available options or by adding new ones. And this works just as expected until I try to use `filterOption`.

@zombieJ I now regret ever bringing `disabled` into this. Though I do need it and I see no reason for making it impossible to use with `tags`, it's _not_ part of the issue described here (please read the OP). The main point here is that **`filterOption` doesn't work well with the `tags` mode**. See my notes on why that might be at the bottom of the OP.

**Comment by zombieJ** [comment]
Got what you mean.

@ztplz, seems it's a bug of `filterOption` with `tag` mode.
