### ISSUE TITLE
extract i18n resources to a new package

### ISSUE THREAD

**Issue by wendzhue** [ant-design/ant-design#14097]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now we have implementations on React, Vue and Angular. It would be inefficient to maintain i18n resources in different packages.

### What does the proposed API look like?
```ts
import { zh_CN, en_US } from '@ant-design/i18n';
```

**Comment by krokofant** [comment]
This is mentioned in Milestone II of NG-ZORRO (Angular) https://github.com/NG-ZORRO/ng-zorro-antd/issues/2474
