### ISSUE TITLE
 react-app-rewired breaks with react-scripts@2.1.2 in documentation

### ISSUE THREAD

**Issue by csanggithub** [ant-design/ant-design#14094]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-with-create-react-app-cn](https://ant.design/docs/react/use-with-create-react-app-cn)

### Steps to reproduce
node安装到最新版本，按照链接步骤无法实现按需加载，原因是react-app-rewired1.6.2和react-scripts2.1.2 不兼容，导致无法运行

### What is expected?
可以按照文档说明步骤执行

### What is actually happening?
报错  不兼容

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | "react": "^16.7.0" |
| System | windows10 |
| Browser | 谷歌最新版本 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14047

**Comment by afc163** [comment]
react-app-rewired breaks with react-scripts@2.1.2: https://github.com/timarney/react-app-rewired/issues/343

**Comment by alexchen1875** [comment]
需要更新这个文档么 https://ant.design/docs/react/use-with-create-react-app-cn

**Comment by afc163** [comment]
- https://github.com/arackaf/customize-cra
- https://github.com/sharegate/craco
- https://github.com/rescripts/rescripts

要选一个方案重写了。

**Comment by iamplex** [comment]
现在只能加载antd的所有css了

**Comment by alexchen1875** [comment]
@iamplex 你可以先回滚到 2.1.1

**Comment by apollo7733** [comment]
react-app-rewired@2.0.1 can support react-scripts 2.1.2

**Comment by hengkx** [comment]
> react-app-rewired@2.0.1 can support react-scripts 2.1.2

How use? I still not style

**Comment by afc163** [comment]
Here is workaround: https://github.com/timarney/react-app-rewired/issues/348#issuecomment-452199363

**Comment by luotingv1** [comment]
> Here is workaround: [timarney/react-app-rewired#348 (comment)](https://github.com/timarney/react-app-rewired/issues/348#issuecomment-452199363)

这样 确实能访问端口了 问题是 还是报错
./src/App.js
Module not found: Can't resolve 'antd' in 'F:\antd-demo\src'
import React, { Component } from 'react';
import { Button } from 'antd';
import './App.css';


const {
     override,
     fixBabelImports,
     addLessLoader
} = require("customize-cra");

config-overrides里面的配置
module.exports = override(
     fixBabelImports("import", {
          libraryName: "antd",
          libraryDirectory: "es",
          style: true // change importing css to less
     }),
       addLessLoader({
            ident: 'postcss'
       })
);
还有什么地方没配置么

**Comment by MR03web** [comment]
customize-cra的override似乎是覆盖了cra2的默认配置
想要在cra2的配置上处理得要修改webpack.config.js的不少地方

demo
https://github.com/MR03web/Demo-and-Starter/tree/master/typescript-less-antd
相关
https://github.com/facebook/create-react-app/pull/5934

**Comment by apollo7733** [comment]
customize-cra 就行，假如你有自己想定义的，加一个函数进去就行

// 产品打包时定制
function mycustmize(config)
{
	const production = process.env.NODE_ENV === "production"
	if(production) //是产品环境
	{
                    // ...
	}
	return config;
}

module.exports = override(
	fixBabelImports('import',{ libraryName: 'antd-mobile', libraryDirectory: 'es', style:true}), /*antd-mobile按需导入*/
	addLessLoader({javascriptEnabled:true}), /*加载less-loader*/
	mycustmize /*产品打包时定制*/
);

**Comment by afc163** [comment]
Close in favor of https://github.com/ant-design/ant-design/pull/14385
