### ISSUE TITLE
PR 模板问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#14104]
1. 中英文翻译对不齐（例如 optional 的说明）
2. 『中文版』出现在 PR 中比较奇怪。https://github.com/ant-design/ant-design/pull/14098
3. 缺少对 New Feature 需要一个维护者审核通过才能合并的说明，master 分支的 PR 提交说明，还有哪些应该提到 feature 分支哪些应该提到 master 的说明。
4. 『这是一个...』这里可以补充 `TypeScript 定义更新`，`重构`，`代码风格优化`。
5. 可以把 Changelog 单独提成一个大标题。
6. 一些格式问题：
<img width="449" alt="default" src="https://user-images.githubusercontent.com/507615/50722824-00ad0a00-1110-11e9-80d3-bbd42d2440bf.png">
7. 有一些多余空格。
8. changelog is provided or not needed.

**Comment by ztplz** [comment]
`中文版` 在模板里不符合习惯   国外的会中文的很少  用英文模板的不会切到中文模板来  但是会中文的  通常英文也会一点

**Comment by zombieJ** [comment]
我调整一下。
另外 Self check before merge 那个应该是你把空格删了，然后被 github cache comment 了……
