### ISSUE TITLE
Sortable table column header doesn't work with Tooltip properly

### ISSUE THREAD

**Issue by kafkahw** [ant-design/ant-design#14106]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk663j3w3w)

### Steps to reproduce
Please refer to the link to minimal reproduction and open it with Chrome v71

### What is expected?
When hovering over the header of sortable columns, the Tooltip's title should show up correctly.
1. The hover over message for column "name" should be "Name Description"
2. The hover over message for column "age" should be "Age Title"
3. The hover over message for column whose dataIndex is "address" should be "Home Address".

### What is actually happening?
None of the three columns in the minimal reproduction render correct title when hovering over their headers.
1. The hover over message for column "name" is "Name"
2. The hover over message for column "age" is not showing up anything.
3. The hover over message for column whose dataIndex is "address" is "Sort".

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | macOS 10.13.6 |
| Browser | Chrome v71.0.3578.98 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/13984

**Comment by kafkahw** [comment]
@afc163 I don't think this issue gets resolved completely. Now in v3.12.1 when hovering over the header, both Tooltip's title and column title will pop up.

Can you please re-open this issue?

Thanks!

**Comment by afc163** [comment]
Could you create a new issue with reproducible demo and more detail?

**Comment by kafkahw** [comment]
Created a new one #14168
