### ISSUE TITLE
首页requestAnimationFrame动画在144Hz刷新率下的优化问题

### ISSUE THREAD

**Issue by FengJing0** [ant-design/ant-design#14109]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
打开Ant Design（https://ant.design/index-cn）、Motion Design（https://motion.ant.design/）官网首页动画均出现了撕裂卡帧的现象

### What is expected?
动画正常显示

### What is actually happening?
在144Hz刷新率下，首页动画均出现了撕裂卡帧的现象，而在60Hz刷新率下均为正常。经过浏览器性能检测，是由于requestAnimationFrame执行时间过长导致卡帧

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | windows |
| Browser | Chrome 69.0 ,FireFox  64.0  |

---
IE11，Edge，在两种刷新率下均为正常

**Comment by afc163** [comment]
你能尝试帮我们优化一下么，或者指导下排查方向。

**Comment by jljsj33** [comment]
。。。。144hz。。能发下在144Hz下的fps是多少？

**Comment by ztplz** [comment]
https://www.vsynctester.com/edgeieisbroken.html

**Comment by FengJing0** [comment]
> 你能尝试帮我们优化一下么，或者指导下排查方向。

大佬们，我只是发现了问题，也不会优化。。应该也是和fps之类的有关

**Comment by FengJing0** [comment]
> 。。。。144hz。。能发下在144Hz下的fps是多少？

用谷歌浏览器开发者工具监视滚动页面的时候是80-120

**Comment by ztplz** [comment]
改下这个函数的频率就行了  IE11，Edge正常是因为这两个压根就不支持144hz

**Comment by zombieJ** [comment]
能给个 gif 看看吗？

**Comment by FengJing0** [comment]
好像上不了图就录了个屏放在[网盘](https://pan.baidu.com/s/1pfchdEIS4ZLIz8IzQYvnXA)里，是谷歌浏览器和Edge在144Hz下的对比

**Comment by FengJing0** [comment]
是 Chrome 开发者工具里面 Performance 的数据么

**Comment by FengJing0** [comment]
在两种刷新率下禁用缓存记录的数据，可以在开发者工具导入看看[https://pan.baidu.com/s/1bL823oBPpnZjN3eySkojUg](https://pan.baidu.com/s/1bL823oBPpnZjN3eySkojUg)

**Comment by jljsj33** [comment]
tween-one 的 tick 问题，，，但没有 144Hz 的显示器，，我也没办法。。。。

**Comment by afc163** [comment]
穷限制了我们修 bug 😂...

**Comment by zombieJ** [comment]
突然想起来会不会和这个有关系：https://github.com/facebook/react/blob/master/packages/scheduler/src/Scheduler.js#L638

**Comment by FengJing0** [comment]
所以这个是react的bug么😂。。

**Comment by zombieJ** [comment]
> 所以这个是react的bug么😂。。

不能全算，我们在 Ticker 的时候也需要限制一下 8 ms / frame 的逻辑。（不过修了，设备原因我们其实也测不出来……）

**Comment by enclairfarron** [comment]
用165hz的测试了一下**ant-motion** 把**rc-tween-one**里**ticker**的**perFrame**改成**1000 / 165** 卡顿消失了😂

**Comment by afc163** [comment]
@jljsj33 看下 @enclairfarron 的方案，应该是 rc-tween-one 的问题。

**Comment by jljsj33** [comment]
没显示器我没法确定，，应该是 zombieJ 说的那个。。把差值小于 8fps 的跳过。

**Comment by afc163** [comment]
上了新首页，老的问题不修了。
