### ISSUE TITLE
Popover 如何实现 文本框输入@弹出呢

### ISSUE THREAD

**Issue by shawon1220** [ant-design/ant-design#1410]
Popover 是否可以实现在文本框输入类似@后弹出pop呢？

目前通过设置visible属性实现，但是点击document不能自动关闭，或许思路不对...

**Comment by shawon1220** [comment]
临时使用表达式
{this.state.showPop?
      <Popover 
        trigger={['click']}
        defaultVisible={true}
     />:null
}

**Comment by benjycui** [comment]
监听 `document` 的 `onClick`，在适当的时机把 `visible` 设为 `false`.

**Comment by afc163** [comment]
可以试试 Select 或者 https://github.com/effektif/react-mentions

Popover 应该做不到这个效果。

**Comment by afc163** [comment]
是否可以给 Select 的 tags 模式加一个 `dropdownAlignWithCursor` 属性。@yiminghe

**Comment by yiminghe** [comment]
select 已经太复杂了，用个新的组件吧 (谁有空 pr 也行)

**Comment by afc163** [comment]
先开着，后面有空来做。

**Comment by benjycui** [comment]
一个单独的 Mention 组件意义不大吧，觉得这个功能应该集成进 Editor https://github.com/ant-design/ant-design/issues/1083 才对，毕竟需要 `@` 功能时，基本都是要输入大量文本的情况。

Editor 支持 `plain-text`(类似 `textarea`) `rich` 等几个模式就可以。

**Comment by afc163** [comment]
http://uxco.re/components/mention/

**Comment by afc163** [comment]
不是的，metion 不一定是富文本编辑器，类似微博输入框、微信输入框这种需求还是蛮常见的。

**Comment by benjycui** [comment]
> Editor 支持 plain-text(类似 textarea) rich 等几个模式就可以。

这样如何？

**Comment by afc163** [comment]
还是不如一个 Metion 来的简单，这两个组件要解决的问题是不一样的。Metion 只是一个辅助输入功能。

**Comment by yiminghe** [comment]
Editor/Mention 底层都是基于 draft

**Comment by pigletfly** [comment]
+1
