### ISSUE TITLE
Context should be available inside notifications.

### ISSUE THREAD

**Issue by DylanVann** [ant-design/ant-design#14101]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently notifications are rendered using ReactDOM.render instead of using something like Portals.

If someone wants to use context for something like theming, state management, or i18n, context is not available within notifications.

Here's a sandbox showing this: https://codesandbox.io/s/m6m5lwl48

### What does the proposed API look like?
There should be a way to control which React tree notifications render into, instead of using ReactDOM.render. We could use something like a `NotificationRoot` component. Export that and if a user renders it somewhere in their React tree then use that to render notifications instead of using ReactDOM.render.

**Comment by ztplz** [comment]
Maybe we should refactor the `rc-notification` in the future.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/21275
