### ISSUE TITLE
Form Item validateStatus '' Invalid prop 

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#14111]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?editors=0011](https://codepen.io/pen/?editors=0011)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/8358236/50721186-49f06000-10f6-11e9-855a-6b7fe63e4ae2.png)
lib folder
![image](https://user-images.githubusercontent.com/8358236/50721193-5e345d00-10f6-11e9-9d80-f4a5ee4bd441.png)

[https://github.com/ant-design/ant-design/blob/master/components/form/FormItem.tsx#L14](https://github.com/ant-design/ant-design/blob/master/components/form/FormItem.tsx#L14)

![image](https://user-images.githubusercontent.com/8358236/50721203-82903980-10f6-11e9-8f2c-929368933774.png)

### What is expected?
not warning

### What is actually happening?
warning

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | windows 10 or mac |
| Browser | chrome latest |

**Comment by afc163** [comment]
It is not released yet. 

https://github.com/ant-design/ant-design/commit/b2c7c53b4cabb87f00e3ef3caa2a1a94a5004987#diff-94b7635a3702d37a73e4971da7dda90b
