### ISSUE TITLE
use12Hours props set true only show PM, no AM

### ISSUE THREAD

**Issue by hckhanh** [ant-design/ant-design#14116]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v8j335pz3)

### Steps to reproduce
1. Import TimePicker
2. Set `format` prop to `h:mm:ss A`
3. Set `use12Hours` to `true`

### What is expected?
Show the list of time with PM and AM options

### What is actually happening?
Only PM is shown

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | v16.7.0 |
| System | Windows 10 |
| Browser | Chrome v71.x |

**Comment by afc163** [comment]
<img width="307" alt="default" src="https://user-images.githubusercontent.com/507615/50722844-47026900-1110-11e9-817c-46b9a57b37ee.png">

It is there, you can sroll up to find it.

**Comment by rahuls360** [comment]
Is there a way to show it by default like your image @afc163 ?
Many users don't know it is available on scroll

**Comment by wbobeirne** [comment]
@rahuls360 I found this issue by searching and just wanted to share a technique I used when I ran into this
```less
.ant-picker-datetime-panel .ant-picker-time-panel-column:last-child::after {
    display: none;
}
```
This removes the spacer that makes it tall enough to scroll.
