### ISSUE TITLE
表单中 RangePicker 输入框修改日期自动关闭

### ISSUE THREAD

**Issue by panmenglin** [ant-design/ant-design#14114]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
第7个例子 时间类控件

表单中的 RangePicker
先通过日历选择一个区间
再次点击打开，通过上面的输入框修改日期，RangePicker 会自动关闭

### What is expected?
和非表单中的 RangePicker 一样
通过输入框修改日期，日历跳转对应月份

### What is actually happening?
RangePicker 自动关闭了

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | maxos |
| Browser | chrome 71.0.3578.98 |

**Comment by Yangzhedi** [comment]
可以提供一个重现链接吗

**Comment by panmenglin** [comment]
> 可以提供一个重现链接吗

https://ant.design/components/form-cn/
官网文档 第7个例子

**Comment by zombieJ** [comment]
看起来直接的 RangePicker 也有这个问题：https://ant.design/components/date-picker-cn/#components-date-picker-demo-basic
