### ISSUE TITLE
Use button to trigger (show/hide) of collapse/accordion

### ISSUE THREAD

**Issue by Hawiie13** [ant-design/ant-design#14122]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Use button to (show/hide) collapse/accordion
and the trigger button and does not need header and can be place outside  `<Collapse></Collapse>`

### What does the proposed API look like?
`<Button onClick={()=>this.collapse.trigger('a')} icon="home"/>
<Button onClick={()=>this.collapse.trigger('b')} icon="home"/>
<Button onClick={()=>this.collapse.trigger('c')} icon="home"/>`

//.trigger(key)

`<Collapse accordion ref={c=>this.collapse =c}>
    <Panel key="a">
      <p>text</p>
    </Panel>
    <Panel key="b">
      <p>text</p>
    </Panel>
    <Panel key="c">
      <p>text</p>
    </Panel>
  </Collapse>`

idea https://getbootstrap.com/docs/4.1/components/collapse/`
Sorry i am using phone typing this feature request

**Comment by afc163** [comment]
Use `activeKey` and `onChange` to conroll the collapse.

https://reactjs.org/docs/forms.html#controlled-components

**Comment by koshelevvasya** [comment]
> How about hiding the header?
<a-collapse class="my-collapse">

.my-collapse .ant-collapse-header {
  display: none;
}
