### ISSUE TITLE
Badge组件服务器端渲染和客户端渲染存在差异性警告

### ISSUE THREAD

**Issue by langjt** [ant-design/ant-design#1413]
## 问题描述
Badge组件服务器端渲染和客户端渲染存在差异性警告。如下：
![image](https://cloud.githubusercontent.com/assets/2832575/14516025/b3f9ea10-0231-11e6-9743-a2b52d2417b4.png)

## 发生环境

- antd 版本：0.12.11:
- 操作系统及版本: OS X El Capitan 10.11.4 
- 浏览器及版本: chrome 49.0.2623.112 (64-bit)
- 在线演示地址：http://ant.design/components/badge/#demo-basic

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/1300
