### ISSUE TITLE
Empty image broken

### ISSUE THREAD

**Issue by ericshao** [ant-design/ant-design#14133]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://p9ql7z65qq.codesandbox.io/)

### Steps to reproduce
as above

### What is expected?
showing an empty image

### What is actually happening?
there is no empty image

| Environment | Info |
|---|---|
| antd | 3.12.0 |
| React | 16.7 |
| System | MacOS Mojave (10.14.2) |
| Browser | Chrome 71.0.3578.98 |

**Comment by sy-tang** [comment]
+1.
All empty table suddenly look like this:
![image](https://user-images.githubusercontent.com/1843681/50736707-aa1cfa00-11fb-11e9-9706-68afce820893.png)

3.11.0 is fine.

**Comment by yesmeck** [comment]
https://codesandbox.io/s/l7qolkxyr7

Fixed in 3.12.1, thanks for reporting.
