### ISSUE TITLE
Tab into DatePicker field should open DatePicker so dates can be entered without mouse

### ISSUE THREAD

**Issue by thj-dk** [ant-design/ant-design#14136]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using tab to focus a DatePicker field, the field is focused, but nothing happens and dates cannot be entered. One has to use the mouse to click the field. It would be really useful if the DatePicker could open on field focus (by tab) and focus the field where the date can be entered using the keyboard. Then users can enter dates without having to use the mouse.

### What does the proposed API look like?
Boolean prop `showOnFocus`

**Comment by afc163** [comment]
Thx @thj-dk , we should support tab and press enter to open DatePicker at least.

**Comment by zombieJ** [comment]
Currently DatePicker support `down` key to open. Add `enter` key to open & close additionally.

**Comment by thj-dk** [comment]
@afc163 probaly a good idea with a Enter-press. It's better than KeyDown in my opinion.
@zombieJ Thank you! Any chance we can get this for the RangePicker as well?

How often are the react-components updated in antd?

**Comment by zombieJ** [comment]
@thj-dk already updated. Try to remove node_modules and reinstall.

**Comment by thj-dk** [comment]
@zombieJ Thank you! Any chance of getting this to work on the range picker?

**Comment by thj-dk** [comment]
Alright @zombieJ - no worries; the most important one is DatePicker.

For consistent behaviour, I think it would make sense if the DatePickers text field was focused and its input highlighted, after pressing the Enter/Down key. Just like regular text fields when focused. What do you think?

**Comment by zombieJ** [comment]
I agree with you. But since lack of hand. Do you interest to send a PR for this?
