### ISSUE TITLE
Table什么时候可以实现Column拖拽

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#14138]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望Table什么时候可以实现Column拖拽

### What does the proposed API look like?
希望Table什么时候可以实现Column拖拽

**Comment by afc163** [comment]
Table 已经很复杂了，短时间应该不会支持，欢迎自行探索。

**Comment by Mathround** [comment]
> Table 已经很复杂了，目前还有很多细节问题。短时间应该不会支持，欢迎自行探索。

希望下个新版本支持一下这功能，那就完美了，谢谢

**Comment by githubSiYao** [comment]
我已经基于react-dnd实现了antd-table的列拖拽，如果需要可以联系我。

**Comment by afc163** [comment]
这里有个列宽度拖拽调整的例子也可以参考：http://react-component.github.io/table/examples/column-resize.html

**Comment by Mathround** [comment]
> 这里有个列宽度拖拽调整的例子也可以参考：http://react-component.github.io/table/examples/column-resize.html

亲，你这个例子是列宽拖拽调整，我想要的需求是列的顺序拖拽，比如我想把第1列拖到最后一列这样的需求，有这样的demo例子吗

**Comment by Mathround** [comment]
> 我已经基于react-dnd实现了antd-table的列拖拽，如果需要可以联系我。

你好，请问怎么联系你呢

**Comment by zombieJ** [comment]
@githubSiYao 欢迎提供在线例子，如果简单我们可以放到 doc  的 faq 里。

**Comment by Mathround** [comment]
> @githubSiYao 欢迎提供在线例子，如果简单我们可以放到 doc 的 faq 里。

目前在用的例子，基于antd的，不过有点问题
https://github.com/raisezhang/react-drag-listview
