### ISSUE TITLE
Calling setFieldsValue in a hidden modal results in error

### ISSUE THREAD

**Issue by fccoelho7** [ant-design/ant-design#14134]
![image](https://user-images.githubusercontent.com/4829072/50736530-d1e17300-11a5-11e9-87c6-76b7a213494a.png)

- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/fccoelho7/andux](https://github.com/fccoelho7/andux)

### Steps to reproduce
1. Clone the repository
2. Execute `yarn start`
3. Open the browser's console
4. In the browser, click on "Edit" button of the first-row element

### What is expected?
Open the edition modal with filled inputs and without any error.

### What is actually happening?
The first opening is coming without filled inputs and if you check the console, you'll see an error message: `Warning: You cannot set a form field before rendering a field associated with the value.`

| Environment | Info |
|---|---|
| antd | 3.12.0 |
| React | react 16.7 |
| System | Mac OSX |
| Browser | Chrome |

---
I think it's happening because when I call the `setFieldsValue()` the modal is not visible yet. But, I didn't find any other way to do it. Anyone know how can we set field values in the modal?

**Comment by zombieJ** [comment]
I can't reproduce this error...

**Comment by wuranxu** [comment]
Hello, have you solved this problem?
When I wanna setFieldsValue with a hidden Tab components, the problem happened too.
(I have made TabPane's attribute(forceRender) true, it doesn't works)
If you known about it,  please tell me ~ Thanks a lot !   ^_^

**Comment by JasonBoy** [comment]
The object you passed to `setFieldsValue()` has some fields which were not `getFieldDecorator`ed in the form, e.g:
```jsx
//in form
<Form.Item label="name">
                {getFieldDecorator('name', {
                  rules: [{ required: true, message: 'name!' }],
                })(<Input/>)}
              </Form.Item>
```
But later when you set the value:
```javascript
this.props.form.setFieldsValue({
  name: 'newName',
  lastName: 'last-name', //this is the one that trigger the warning, because it's not decoratored in Form
})
```

**Comment by wenlittleoil** [comment]
Maybe you should set the initial value of form by  `initialValue` in the `getFieldDecorator` function, but not `setFieldsValue` outsize the component.
