### ISSUE TITLE
集成 react-resizable 来实现可伸缩列的表格在火狐浏览器表头没有左右及下边框

### ISSUE THREAD

**Issue by Twiner94** [ant-design/ant-design#14143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting](https://ant.design/components/table-cn/#components-table-demo-drag-sorting)

### Steps to reproduce
可伸缩列表格添加样式 
.react-resizable {
  position: relative;
}

.react-resizable-handle {
  position: absolute;
  width: 10px;
  height: 100%;
  bottom: 0;
  right: -5px;
  cursor: col-resize;
}
表格在火狐浏览器表头没有左右及下边框,
 例子集成 react-resizable 来实现可伸缩列在火狐浏览器上一样有此问题

### What is expected?
集成 react-resizable 来实现可伸缩列的表格在火狐浏览器上与谷歌浏览器上一样有边框

### What is actually happening?
集成 react-resizable 来实现可伸缩列的表格在火狐浏览器上部分边框没有

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.6.3 |
| System | windows |
| Browser | FireFox 64.0 |

**Comment by Twiner94** [comment]
https://codesandbox.io/s/kxxq0795jo

**Comment by Twiner94** [comment]
https://codesandbox.io/s/kxxq0795jo      用火狐浏览器打开，表头没有边框

**Comment by afc163** [comment]
Try this way: https://github.com/ant-design/ant-design/commit/42e5b8b77eba07593fd5042c5c24bac740128a51

https://codesandbox.io/s/jljm8lo3vy

More detail see: https://github.com/ant-design/ant-design/issues/12628#issuecomment-429695092
