### ISSUE TITLE
Change UI of Table's filter dropdown buttons for priority

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#14149]
<img width="879" alt="image" src="https://user-images.githubusercontent.com/507615/50754271-26611d00-1290-11e9-9450-aebbae61bdc7.png">

We can redesign `Ok` to primary button style.

**Comment by zombieJ** [comment]
confirm 和 modal 都是在右边。感觉可以直接换掉位置。然后把重置做成深灰色：
<img width="258" alt="2019-01-07 4 12 45" src="https://user-images.githubusercontent.com/5378891/50756443-3a5c4d00-1297-11e9-9216-29ba8ad05108.png">
<img width="534" alt="2019-01-07 4 13 08" src="https://user-images.githubusercontent.com/5378891/50756444-3a5c4d00-1297-11e9-9919-4b11b0902e7b.png">

**Comment by afc163** [comment]
Resolved by #22072
