### ISSUE TITLE
popover 样式定义存在问题

### ISSUE THREAD

**Issue by BobCao** [ant-design/ant-design#14148]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/popover/style/index.less   line:58](https://github.com/ant-design/ant-design/blob/master/components/popover/style/index.less   line:58)

### Steps to reproduce
用less.js动态切换样式时控制台报错

### What is expected?
去掉 \9

### What is actually happening?
    box-shadow: ~'0 0 8px @{shadow-color} \9';

| Environment | Info |
|---|---|
| antd | 3.12.0 |
| React | 16.x |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/13935

**Comment by xwzpp** [comment]
我们这边同样遇到自定义主题的less文件报错，也是由于这个 \9 问题

**Comment by afc163** [comment]
@gyh9457

**Comment by gyh9457** [comment]
可以提供复现的demo吗

**Comment by gyh9457** [comment]
@xwzpp  我使用 https://github.com/ant-design/create-react-app-antd 这个例子做测试是正常的，不知道你是怎么做定制的？

![image](https://user-images.githubusercontent.com/13557235/50883069-e16cf000-1421-11e9-8d2e-9f6add0451d8.png)

![image](https://user-images.githubusercontent.com/13557235/50883134-209b4100-1422-11e9-9e47-5bf3852b78d5.png)

**Comment by mzohaibqc** [comment]
`\9` is causing error on theme compilation for `antd-theme-generator`. Kindly remove this if it is not intentional

https://github.com/mzohaibqc/antd-theme-generator/issues/15

**Comment by afc163** [comment]
trace in https://github.com/mzohaibqc/antd-theme-generator/issues/15
