### ISSUE TITLE
At rowSelection'property  fixed is true , use expandedRowRender, render to a Table , display error

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design#14152]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/ZVoxXZ?editors=0010](https://codepen.io/anon/pen/ZVoxXZ?editors=0010)

### Steps to reproduce
1. rowSelection.fixed = true
2.expandedRowRender = { Table }

### What is expected?
Normal display

### What is actually happening?
Display chaos

| Environment | Info |
|---|---|
| antd | 3.8.2 |
| React | 16.7.0 |
| System | macos 13.6 |
| Browser | chorme 71.0.3578.98 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9900#issuecomment-378191423
