### ISSUE TITLE
Icon support async load 

### ISSUE THREAD

**Issue by ShanaMaid** [ant-design/ant-design#14153]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For example, if a 100kb svg has been used in a production project, the user needs to load an additional 100kb svg content each time the project releases a new bundle.

If the svg is packaged in chunks, when the developer introduces a new svg (assuming 1 kb), the user needs to load an additional 100 kb of content for this 1 kb update.

If you use asynchronous loading and cache svg, the above problem does not occur.

 my tool that solves the above problem: [archer-svgs](https://github.com/ShanaMaid/archer-svgs)

online demo: [click me ](http://blog.shanamaid.top/archer-svgs)

### What does the proposed API look like?
refactot Icon components by using [archer-svgs](https://github.com/ShanaMaid/archer-svgs), api not change!

**Comment by ShanaMaid** [comment]
if antd need the feature, I can do it and pr

**Comment by ShanaMaid** [comment]
this is a bad idea?

**Comment by afc163** [comment]
trace #12888
