### ISSUE TITLE
AutoComplete包含有search图标的时候出现在表单中发生移位

### ISSUE THREAD

**Issue by changero** [ant-design/ant-design#14156]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/changero/pen/ZVoovO?editors=0010](https://codepen.io/changero/pen/ZVoovO?editors=0010)

### Steps to reproduce
在Form表单的Form.Item中，如果AutoComplete位于Input.Group下,并且使用了图标（通过Icon组件或者Input.Search）,会出现输入框相对label偏上的情况

### What is expected?
与其他表单项一样与旁边的label居中的位置

### What is actually happening?
输入框偏上

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7 |
| System | window10 |
| Browser | chrome 70 |

**Comment by afc163** [comment]
https://codepen.io/anon/pen/GLaogB?editors=0110
