### ISSUE TITLE
Radio button empty row is clickable

### ISSUE THREAD

**Issue by liadbe** [ant-design/ant-design#14164]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/radio/](https://ant.design/components/radio/)

### Steps to reproduce
Enter the link above -> In 'Vertical RadioGroup' example -> click on 'More...' -> hover your cursor above the input field of 'More...' that was opened -> you will notice that the blank space next to 'Option A', 'Option B' and 'Option C' are clickable

### What is expected?
The blank space next to 'Option A', 'Option B' and 'Option C' shouldn't be clickable

### What is actually happening?
The blank space next to 'Option A', 'Option B' and 'Option C' is clickable

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7.0 |
| System | Windows |
| Browser | Chrome |

---
In case of radio group options that does not have the same length of charachters. the clickable area is as the longest option's width.

**Comment by afc163** [comment]
I think it is reasonable cause every item in radio group is `display: block`.
