### ISSUE TITLE
yarn start  时 报错 Cannot set property 'options' of undefined

### ISSUE THREAD

**Issue by q921232954** [ant-design/ant-design#14163]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
yarn start  时 

### What is expected?
正常启动

### What is actually happening?
报错 Cannot set property 'options' of undefined

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | xx |
| System | mac10.16.1 |
| Browser | xx |

---
能否 更新下  官方操作手册，谢谢！

**Comment by afc163** [comment]
Duplicate of #14094
