### ISSUE TITLE
Icons: Missing Linux icon

### ISSUE THREAD

**Issue by tvarsis** [ant-design/ant-design#14166]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Ant contains logos for Apple, Windows, Android, Chrome and so on. But misses one for Linux. I think it makes sense to include that logo as well when using this lib to display different operating systems options.

### What does the proposed API look like?
Add a penguin/Linux logo to the icon lib.

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design-icons/issues/26#issuecomment-451978683

**Comment by ShiftcodeDream** [comment]
Linux icon is still missing, and WE NEED IT !
