### ISSUE TITLE
Modal使用属性forceRender时，componentDidMount生命周期无法获取Modal子元素

### ISSUE THREAD

**Issue by tanyioO** [ant-design/ant-design#14160]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9zz6o619r4)

### Steps to reproduce
打开链接查看控制台在index/ModalDemo DidMount内以及点击打开modal子元素button时的打印内容

### What is expected?
在index/modalDemo componentDidMount生命周期内可以获取Modal内部子元素

### What is actually happening?
index/ModalDemo在DidMount时打印为null，点击打印modal子元素

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7.0 |
| System | windows10 |
| Browser | chrome 71.0.3578.98 |

**Comment by zy410419243** [comment]
https://codesandbox.io/s/314pl7ynwq

**Comment by Yangzhedi** [comment]
https://github.com/ant-design/ant-design/blob/master/components/modal/Modal.tsx
我在interface里没找到forceRender这个属性，但是API表格里有这个属性的描述？？

在modal文件夹里全局搜索也没发现forceRender？这属性逻辑没放modal里？

**Comment by Yangzhedi** [comment]
@tanyioO 检查一下你的rc-dialog是不是7.3.0版本， forceRender是7.3.0 新增的功能，
