### ISSUE TITLE
TableProps sortDirections type should optional

### ISSUE THREAD

**Issue by dano-giftbit** [ant-design/ant-design#14170]
### Steps to reproduce
In the table interface file sortDirections is required and the typescript compiler complains if it's missing

### What is expected?
According to https://github.com/ant-design/ant-design/pull/13773/files  
sortDirections has a defaultProps value (Table.tsx line 99)

I would expect the sortDirections in `TableProps` to be `sortDirection?: SortOrder[];`

### What is actually happening?
`TableProps` sortDirections is defined as `sortDirections: SortOrder[];`

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | React 16, Typescript 3.2.2, Ant 3.12.1 |

---
I can update this and submit a PR, but unfamiliar with workflow

**Comment by snowgrus** [comment]
Typescript Table 组件的 sortDirections 怎么是必填的

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/14182
