### ISSUE TITLE
希望可以去掉按钮阴影

### ISSUE THREAD

**Issue by 7Charlotte** [ant-design/ant-design#14172]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我是交互设计师。在引入ant之前，我们系统已经有一套自己的UI规范了，在规范中按钮是没有1px的阴影的，按钮文字也没有1px的阴影，这样的设计更符合我们产品清新的风格。能否在ant的default.less文件中给出一个属性，可以把按钮阴影和按钮文字的阴影去掉，以便和我们原来的UI风格保持一致。

### What does the proposed API look like?
希望在主题文件default.less中增加属性来设置按钮阴影和按钮文字阴影。我是设计师，不太懂代码。

**Comment by 7Charlotte** [comment]
应该不是的。抱歉没有刚才没有截图。
我说的阴影是按钮的阴影 [https://ant.design/components/popover-cn/#components-popover-demo-basic](url)
如下图
<img width="495" alt="2019-01-08 10 29 25" src="https://user-images.githubusercontent.com/4272864/50806197-a0e17980-1330-11e9-9248-ba174f63342c.png">

不是` @box-shadow-base`，这个属性是控制浮层的阴影的。

**Comment by afc163** [comment]
在 default.less 中增加了两个变量以供覆盖。https://github.com/ant-design/ant-design/pull/14174

**Comment by 7Charlotte** [comment]
wow，你们太快了，非常感谢！！！！afc163
我刚刚问了我们的前端同事，是不是要等你们发新版了，这三个属性才会生效哇？

**Comment by afc163** [comment]
按惯例，这个改动本周末会发。https://ant.design/changelog-cn#%E5%8F%91%E5%B8%83%E5%91%A8%E6%9C%9F

**Comment by 7Charlotte** [comment]
好的哈，感谢！比心❤️
