### ISSUE TITLE
Property 'onClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Item>

### ISSUE THREAD

**Issue by Alohaliu** [ant-design/ant-design#14171]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/9933](https://github.com/ant-design/ant-design/issues/9933)

### Steps to reproduce
```  
          <List.Item className={itemCls} key={item.key || index} onClick={() => onClick(item)}>
                  <List.Item.Meta
                    className={styles.meta}
                    avatar={<span className={styles.iconElement}>{leftIcon}</span>}
                    title={
                      <div className={styles.title}>
                        {item.title}
                        <div className={styles.extra}>{item.extra}</div>
                      </div>
                    }
                    description={
                      <div>
                        <div className={styles.description} title={item.description}>
                          {item.description}
                        </div>
                        <div className={styles.datetime}>{item.datetime}</div>
                      </div>
                    }
                  />
                </List.Item>
```

### What is expected?
typescipt 语法校验通过

### What is actually happening?
不通过，报错如下：

[ts] Property 'onClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Item> & Readonly<{ children?: ReactNode; }> & Readonly<ListItemProps> & Pick<InferProps<{ column: Requireable<ReactText>; xs: Requireable<ReactText>; ... 4 more ...; xxl: Requireable<...>; }>, "xs" | ... 5 more ... | "column">'.

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.6.3 |
| System | macOs |
| Browser | chrome71.0.3578.98 |

---
https://github.com/ant-design/ant-design/issues/9933

感觉跟这个问题类似，List组建目前还没有支持原生的事件等DOMAttributes

**Comment by simmatrix** [comment]
Thanks @dengfuping! May this fix be applied to "DropDownProps" as well? We are facing a similar issue in the DropDown component too. Thank you.
