### ISSUE TITLE
Setting filterIcon as a custom React Component but onFilterDropdownVisibleChange not work

### ISSUE THREAD

**Issue by tsejx** [ant-design/ant-design#14176]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. Use a custom ReactNode as filterIcon
2. And the onFilterDropdownVisibleChange can be invoked when user click the filter

DEMO：https://codesandbox.io/s/7m10ykorw0
* First row is not work
* Second row Icon Component is work, but I prefer to package common component
* Third row is work, but need to add 'onClick' and 'classname="ant-table-filter-icon ant-dropdown-trigger"' in it

### What does the proposed API look like?
Function <onFilterDropdownVisibleChange> can be invoked when user click the filter

**Comment by ztplz** [comment]
Close it for it has been fixed via https://github.com/ant-design/ant-design/pull/14243.
