### ISSUE TITLE
Form.create()  Upload initialValue

### ISSUE THREAD

**Issue by jiafulu** [ant-design/ant-design#14179]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/880kx8y619)

### Steps to reproduce
Form 
Upload 
initialValue

### What is expected?
希望上传组件的默认值能生效啊
The default value is normally displayed

### What is actually happening?
上传组件的默认值没生效啊
The default values ​​are not displayed

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7.0 |
| System | window 10 |
| Browser | Google Chrome版本 71.0.3578.98（正式版本） （64 位） |

---
编辑按钮打开带表单的弹窗，upload组件的默认图片无法显示

The edit button opens the popup window with the form, and the default image of the upload component cannot be displayed.

**Comment by afc163** [comment]
```diff
- valuePropName: "file",
+ valuePropName: "fileList",
```

**Comment by jiafulu** [comment]
谢谢大佬，自己瞎倒腾一下午没搞定

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#components-form-demo-validate-other

其实这里有例子的

**Comment by xoptimal** [comment]
跟示例代码是一致的, 但是结果还是没有渲染出来 ...

**Comment by zyy8782** [comment]
Does your upload component wrap other labels?
    if there is!     Add properties to the upload tag in the current component
`<upload fileList={this.props.fileList} />`

**Comment by daweilun** [comment]
> 谢谢大佬，自己瞎倒腾一下午没搞定

解决了吗？valuePropName设置后需要传initialValue吗，还是有fileList控制？
