### ISSUE TITLE
TreeNode selectable has no effect

### ISSUE THREAD

**Issue by travikk** [ant-design/ant-design#14175]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r4z1v8011m)

### Steps to reproduce
1. Select any tree node

### What is expected?
1. onSelect handler to be not invoked
2. Node to be not selected (visually)

### What is actually happening?
1. onSelect handler is invoked with the selected node
2. node is visually marked as selected

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7 |
| System | MacOS |
| Browser | Chrome 71 |

**Comment by ztplz** [comment]
@travikk
![image](https://user-images.githubusercontent.com/17755202/50852180-ccf50d00-13b9-11e9-9c00-630b852649fc.png)
Some typos here.   `selectabl` => `selectable`

**Comment by afc163** [comment]
issue 里的错别字可以出个集锦了~ 😂
