### ISSUE TITLE
There is an extra blank headers at the top of drawer component

### ISSUE THREAD

**Issue by tingxinCY** [ant-design/ant-design#14178]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/drawer-cn/](https://ant-design.gitee.io/components/drawer-cn/)

### Steps to reproduce
升级到最新版即可

### What is expected?
希望能做到向后兼容，默认不显示，在用户设置了title属性时再显示

### What is actually happening?
在未设置title属性时，drawer顶部会显示一个多余的空白行

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.6.3 |
| System | mac 10.14.1  |
| Browser | chrome 71.0.3578.98 |

---
drawer的关闭按钮之前是和ant-drawer-body同级的节点，现在被放到了ant-drawer-header(最新版新增)中了，这会导致页面多出来一个空白头

**Comment by afc163** [comment]
https://codesandbox.io/s/0q2mnrxm8w

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50827836-892ee300-137a-11e9-814d-3f02a25be237.png)
![image](https://user-images.githubusercontent.com/17755202/50827864-aa8fcf00-137a-11e9-86ea-8fc79f80ea4e.png)
