### ISSUE TITLE
组件全局属性defaultProps

### ISSUE THREAD

**Issue by sun-3211** [ant-design/ant-design#14189]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我可以通过这个属性设置全局的 分页样式，不需要单独每一个都加上属性
Pagination.defaultProps.pageSizeOptions = ["10", "20", "30", "40"];
Pagination.defaultProps.showSizeChanger = true;
Pagination.defaultProps.showTotal = (total, range) => `${range[0]}到${range[1]}行 一共${total}行`;

### What does the proposed API look like?
我期望能恢复这个功能。

**Comment by afc163** [comment]
建议封装上层组件来完成此需求。

**Comment by sun-3211** [comment]
谢谢，我知道原因了，因为系统添加了ConfigProvider
删除了以下代码
static defaultProps = {
    prefixCls: 'ant-pagination',
    selectPrefixCls: 'ant-select',
};
所以defaultProps属性默认未声明
我使用以下方法可以修改全局属性，
Pagination.defaultProps = {
    pageSizeOptions: ["10", "20", "30", "40"],
    showSizeChanger: true,
    showTotal: (total, range) => `${range[0]}到${range[1]}行 一共${total}行`
};
