### ISSUE TITLE
提供表格移动上去绑定多行功能

### ISSUE THREAD

**Issue by yizhengfeng-jj** [ant-design/ant-design#14187]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

## 解决的问题
解决了鼠标移动上去，能显示整体的信息，客户要求需要这个整体显示信息，便于观看
## 描述
之前的Table 组件鼠标移动上去都是一个一个的显示底色，我想要的是鼠标移动上去能根据某一个指标比如name,把所有name一样的行全部选中

## 建议
因为这个是对于表格而言，为了简洁我觉得可以这样
``` javascript
class App extends React.Component {
   render{
    return (
    <Table columns={[]}, dataSource={} bindData={true}>
)
}
}
// bindData 就是是否根据某一指标绑定多行
```

**Comment by dengfuping** [comment]
@yizhengfeng-jj 不是很懂具体需求是什么，能否有截图或示例详细描述下？

**Comment by afc163** [comment]
https://ant.design/components/table/#onRow-usage

我们提供了行的 `onMouseEnter` 和 `onMouseLeave` 你可以用于自定义交互实现。

**Comment by yizhengfeng-jj** [comment]
我想要的效果是这样的
![image](https://user-images.githubusercontent.com/20452750/50874676-f89ae600-13ff-11e9-9159-3a1320178e5f.png)
鼠标移动上去就是显示三个整体的底色，onMouseEnter提供了我移动上去，这一行的信息，但是还是只能是一行，我想要的是移动上去ip相同的三行，作为一个整体，显示底色

**Comment by afc163** [comment]
配合设置 rowClassName 可以达到这个效果。

**Comment by yizhengfeng-jj** [comment]
好的 我试试 感谢您的回答 谢谢！
