### ISSUE TITLE
Change Icon 'theme' prop to 'mode' because it breaks styled-components

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#14199]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Icon's 'theme' prop overrides [styled-components theme](https://www.styled-components.com/docs/advanced#theming), changing the prop name will allow styled-components theme provider to pass its theme property. Currently the only work around is to style a span that wraps the icon. To prevent breaking the api, you could accept both props
[here's a code pen that shows the issue](https://codesandbox.io/s/o9qokj3om6)

### What does the proposed API look like?
change the prop to 'mode' - or anything but 'theme'.

**Comment by afc163** [comment]
We can't change it for compatibility, you could look up solutions in styled-components too.
