### ISSUE TITLE
Using TextArea with AutoComplete and pressing "enter + shift" is not working as expected

### ISSUE THREAD

**Issue by mis94** [ant-design/ant-design#14194]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lroxzoo179)

### Steps to reproduce
- focus on the text area
- try to hold shift button and press enter

### What is expected?
To produce a new line in the text area

### What is actually happening?
the effect of holding the shift button is ignored and no new line is produced

| Environment | Info |
|---|---|
| antd | 3.7.1 |
| React | 16.3.2 |
| System | Mac 10.14.1 |
| Browser | Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) |

---
I've seen the example provided in the documentation here: https://codesandbox.io/s/km9n1m3v17

but I also realized that it doesn't work unless you make the dataSource be part of the component state, so if I make it as ordinary array or make this array be extracted from props (like the case in my application project) the feature doesn't work.

**Comment by ztplz** [comment]
Actually you need to set the DataSource to an empty array after you have selected it. [demo](https://codesandbox.io/s/qlrkz894jj)

**Comment by mis94** [comment]
Actually the issue is still reproducible in the example you added try:
- type any word then press enter
- type a new word on the next line then press enter

actual: the component considers it as a selection
expected: produce a third line

**Comment by ztplz** [comment]
I tend this is not a bug, because it works in controlled components. See this [example](https://ant.design/components/auto-complete/#components-auto-complete-demo-custom). Or you have other case that you can't do with controlled components?
