### ISSUE TITLE
Table: Ability to hide checkbox column when rowSelection provided

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#14198]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In our application we want to have a table with selection checkboxes when the app is in edit mode and when the user not in edit mode to have the checkbox column hidden. We can mostly obtain this by passing a `rowSelection` when we are in edit mode and passing `null` when not in edit mode. However this breaks down because the previous selection will not be reset when setting the `rowSelection` to null (the `selectedRowKeys` of the table never gets updated). Example of this issue https://codesandbox.io/s/qx7m8lj1wj

### What does the proposed API look like?

I propose adding a `columnVisible` attribute to the `rowSelection` config which allows the user to maintain the selection state of the rowselection via `selectedRowKeys` but also maintain whether the user can update the row selection via the checkboxes 

```
<Table
  data={data}
  rowSelection={{selectedRowKeys, visible: isEditMode, onSelectRow}}
/>
```

**Comment by ztplz** [comment]
Why not cache the state of `selectedRowKeys` yourself?  I have updated [your demo](https://codesandbox.io/s/l7yzl4rz7m).

**Comment by megawac** [comment]
Your update doesn't resolve the issues I'm attempting to address, I want to be able to set which rows are selected when the check box column is hidden. In my example I was attempting to set `selectedRowKeys` to empty when `selectionEnabled` was unchecked, however this isn't possible because ant doesn't update it's internal `selectedRowKeys` on table state when you set `rowSelection=null`.

I don't understand what attempting to cache `selectedRowKeys` would accomplish.

**Comment by hardywu** [comment]
the source codes structure does not support this feature. Should be a new feature request.

**Comment by ztplz** [comment]
![untitled7](https://user-images.githubusercontent.com/17755202/53245384-84cf4700-36e8-11e9-8885-9630bea36c21.gif)
@megawac  It seems has been fixed. Let me know if it's what you want.

**Comment by megawac** [comment]
Yep, looks like it works thanks for pointing that out

**Comment by rrev4ge** [comment]
Working for me: 
`rowSelection={{
    renderCell: (value) => <></>,
    columnWidth: 0,
 }}`
