### ISSUE TITLE
去除jQuery依赖更换IO依赖库

### ISSUE THREAD

**Issue by Jmarry** [ant-design/ant-design#142]
当前对jQuery的依赖仅仅是ajax处理，建议更换一个更加轻量级的IO库，比如:

1. [superagent](https://github.com/visionmedia/superagent)
1. [reqwest](https://github.com/ded/reqwest)
1. [axios](https://github.com/mzabriskie/axios)

**Comment by yiminghe** [comment]
table 换掉吧，很简单的操作

**Comment by afc163** [comment]
上面 3 个只有 axios 支持 IE8，有没有更好的选择？

**Comment by afc163** [comment]
貌似 reqwest 支持，那换用它好了。
