### ISSUE TITLE
There is a slider bar when create a drawer

### ISSUE THREAD

**Issue by alvinzxf** [ant-design/ant-design#14202]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/alvinzxf/Resources/blob/master/img/drawer1.png](https://github.com/alvinzxf/Resources/blob/master/img/drawer1.png)

### Steps to reproduce
1 进入官网的抽屉部分[ant design](https://ant.design/components/drawer-cn/)
2 点击new account，弹出抽屉的同时有一个滑动条，见![img](https://github.com/alvinzxf/Resources/blob/master/img/drawer.png)
3 进入F12， 点击new account，弹出抽屉，滑动条更为明显，见![imgF12](https://github.com/alvinzxf/Resources/blob/master/img/drawer1.png)

### What is expected?
避免出现滑动条

### What is actually happening?
一直存在

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | react |
| System | win10 |
| Browser | chrome浏览器版本 71.0.3578.98（正式版本） （64 位） |

---
应用列表弹出详情的时候，屏幕中间都会出现滑动条，体验特别糟

**Comment by jljsj33** [comment]
为啥就这一个会有滚动条。。。明天我看下吧

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/blame/master/components/drawer/demo/form-in-drawer.md#L51

这个 `overflow: 'auto'` 有什么用，，，就这个 demo 有这玩意，，没有特殊用处就删掉或改成 `overflowY: 'auto'`。。。
