### ISSUE TITLE
DatePicker 时间选择器，删除时间后再选择，原本设置好的中文，会出现混着英文的情况

### ISSUE THREAD

**Issue by zmhweb** [ant-design/ant-design#14205]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
点击弹窗时间选择->删除当前选中时间->再次点击时间选择

### What is expected?
删除后时间选择的语言还是中文

### What is actually happening?
弹窗的时间选择混杂着英文

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.2 |
| System | chrome |
| Browser | 70.0.3538.77 |

**Comment by zmhweb** [comment]
https://codesandbox.io/s/wk04r016q8

**Comment by zmhweb** [comment]
> Hello @zmhweb. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @zmhweb, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

https://wk04r016q8.codesandbox.io/

**Comment by zmhweb** [comment]
> 我碰到过这个问题，Provider需要 locale 改成中文，还有就是引用的 moment 需要全局改一下配置，
> `moment.lcale('zh-cn')`

![image](https://user-images.githubusercontent.com/16442336/50874194-1cf5c300-13fe-11e9-884e-855c84f2e399.png)

**Comment by zmhweb** [comment]
> > 我碰到过这个问题，Provider需要 locale 改成中文，还有就是引用的 moment 需要全局改一下配置，
> > `moment.lcale('zh-cn')`
> 
> ![image](https://user-images.githubusercontent.com/16442336/50874194-1cf5c300-13fe-11e9-884e-855c84f2e399.png)

我这里之前就添加了配置。直接打开是正常的，删除了值后点击就不正常了
![image](https://user-images.githubusercontent.com/16442336/50874307-81b11d80-13fe-11e9-98bf-bd49ce30aa41.png)
![image](https://user-images.githubusercontent.com/16442336/50874326-94c3ed80-13fe-11e9-94c1-d624e75b127f.png)

**Comment by dengfuping** [comment]
@zmhweb 给的重现链接 https://codesandbox.io/s/pk26kv720j 无法复现该问题。

**Comment by afc163** [comment]
在线无法重现的话，你可能只能自行先排查了。

**Comment by dengfuping** [comment]
问题先关闭，如果在线重现了再打开。

**Comment by zmhweb** [comment]
> 我也遇到一模一样的问题？在本地，你那边解决了么？

卸载掉antd以及相关依赖，再试试

**Comment by KayneWang** [comment]
> 我也遇到一模一样的问题？在本地，你那边解决了么？

建议查看antd组件使用的moment库版本，目前是2.24.0，把本地开发环境moment保持与antd一致试一下。

**Comment by daxianyu** [comment]
主要是因为本地自己装了个moment，antd下面也有个moment，全局moment.locale('zh-CN')只是设置了自己装的，DatePicker组件用的是内层的，并没有被设置，调了半天，已晕厥。
