### ISSUE TITLE
Select等类似组件的空数据状态样式，个人觉得不好看

### ISSUE THREAD

**Issue by YoungHearts** [ant-design/ant-design#14204]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Select等类似组件的空数据状态样式，个人觉得不好看

### What does the proposed API look like?
建议Select等类似组件空数据状态样式要么修改一下，要么不要图

![image](https://user-images.githubusercontent.com/19346339/50872084-0b5dec80-13f9-11e9-8a6a-f3f34654045d.png)

**Comment by yutingzhao1991** [comment]
@zombieJ 反馈给设计师？

**Comment by afc163** [comment]
<img width="230" alt="image" src="https://user-images.githubusercontent.com/507615/50873885-d9e72000-13fc-11e9-97ea-33ca9b9af851.png">

https://ant.design/components/empty/#components-empty-demo-config-provider

It should be look like this.

**Comment by zombieJ** [comment]
看起来像是丢样式，能给个重现不？
<img width="224" alt="2019-01-09 12 16 27" src="https://user-images.githubusercontent.com/5378891/50876520-6fd47800-1408-11e9-9210-d08fb2c739e4.png">

**Comment by stonexer** [comment]
项目里样式不太对，看了下没有引入 `.ant-empty` 的样式。模拟了只引入 Select 组件时的样式。

https://codesandbox.io/s/n04nor080

**Comment by afc163** [comment]
@zombieJ 样式依赖漏了。https://github.com/ant-design/ant-design/blob/master/components/select/style/index.tsx#L4

@stonexer 感谢重现！！

**Comment by zombieJ** [comment]
> 我们的默认图片大小也可以再缩小一点~

popup 里的图片已经缩过一圈了，再小的话可能需要再出一个图了。

**Comment by effectivecui** [comment]
为啥我回滚到3.9.2版本，还是会出现这种问题？这个样式不是后面的版本新上的吗？之前3.9.2版本我没有见到这种情况啊？你们自己有AB开关？

**Comment by zombieJ** [comment]
> 为啥我回滚到3.9.2版本，还是会出现这种问题？这个样式不是后面的版本新上的吗？之前3.9.2版本我没有见到这种情况啊？你们自己有AB开关？

npm list 一下看看是不是引入多个 antd 版本了。这个 empty 是 3.12.x 新加的。

**Comment by effectivecui** [comment]
> > 为啥我回滚到3.9.2版本，还是会出现这种问题？这个样式不是后面的版本新上的吗？之前3.9.2版本我没有见到这种情况啊？你们自己有AB开关？
> 
> npm list 一下看看是不是引入多个 antd 版本了。这个 empty 是 3.12.x 新加的。

感谢！已解决。
另外提醒各位开发者：
指定版本：比如1.2.2，遵循“大版本.次要版本.小版本”的格式规定，安装时只安装指定版本。
波浪号（tilde）+指定版本：比如~1.2.2，表示安装1.2.x的最新版本（不低于1.2.2），但是不安装1.3.x，也就是说安装时不改变大版本号和次要版本号。
插入号（caret）+指定版本：比如ˆ1.2.2，表示安装1.x.x的最新版本（不低于1.2.2），但是不安装2.x.x，也就是说安装时不改变大版本号。需要注意的是，如果大版本号为0，则插入号的行为与波浪号相同，这是因为此时处于开发阶段，即使是次要版本号变动，也可能带来程序的不兼容。
latest：安装最新版本

**Comment by afc163** [comment]
semver.org/lang/zh-CN/

**Comment by YoungHearts** [comment]
> @zombieJ样式依赖漏了[.https：//github.com/ant-design/ant-design/blob/master/components/select/style/index.tsx#L4](https://github.com/ant-design/ant-design/blob/master/components/select/style/index.tsx#L4)
> 
> @stonexer感谢重现！

哦，确实是select没有引入相关样式

**Comment by effectivecui** [comment]
> https://semver.org/lang/zh-CN/
> 
> @effectivecui 别轻易扣帽子啊...😂 我们公信力已经见底了。

抱歉抱歉
