### ISSUE TITLE
safari浏览器，表单输入之后，required的message会闪一下

### ISSUE THREAD

**Issue by xlslucky** [ant-design/ant-design#14218]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)
[https://files.gitter.im/ant-design/ant-design/ZVOu/antd.gif](https://files.gitter.im/ant-design/ant-design/ZVOu/antd.gif)

### Steps to reproduce
required的message会闪一下

### What is actually happening?
safari浏览器，表单输入之后，required的message会闪一下

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.x |
| System | mac |
| Browser | safari |

**Comment by xlslucky** [comment]
https://files.gitter.im/ant-design/ant-design/ZVOu/antd.gif

**Comment by afc163** [comment]
@jljsj33 有空看看

**Comment by jljsj33** [comment]
这不算 bug 吧，，，这是中文输入法的问题吧。。。第一个字拼音时先是字母，再切成空了出来中文字。。。

**Comment by JackClown** [comment]
### workaround
```javascript
import React from "react";
import { Form, Input } from "antd";

//用这个组件去替代原本的Input组件
class TextInput extends React.Component {
  handleChange = e => {
    const value = e.currentTarget.value;

    if (value === "") {
      this.timing = setTimeout(() => {
        this.props.onChange("");
      });
    } else {
      let nextValue = value;

      if (this.timing) {
        nextValue = nextValue.replace(new RegExp(`^${this.props.value}`), "");
        clearTimeout(this.timing);
        this.timing = undefined;
      }

      this.props.onChange(nextValue);
    }
  };

  render() {
    return <Input {...this.props} onChange={this.handleChange} />;
  }
}
```
### Example
[codesandbox](https://codesandbox.io/s/r58j12p16p)

可能有其他未知的问题
