### ISSUE TITLE
Radio's selected css not working

### ISSUE THREAD

**Issue by arifemrecelik** [ant-design/ant-design#14216]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk6ow9vpy6)

### Steps to reproduce
When I use Radio and RadioGroup from 'antd' it works perfectly. But when I wrap two of them with component. I can see the state changed. But I can't see the selected css.

### What is expected?
I'm expecting to see visual selection when I select RadioButton.

### What is actually happening?
I can't see visual selection when I wrap them with a tag.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.4.2 |
| System | Windows 7 |
| Browser | Google Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/x71r9281ko

```diff
- PureComponent
- Component
```
