### ISSUE TITLE
Card组件加入loading后  影响内部元素逻辑，比如逻辑控制不展现的表单元素，加了loading后会被表单验证捕获

### ISSUE THREAD

**Issue by mangoZT** [ant-design/ant-design#14213]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/wk04r016q8](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
Card组件加入loading后 ，比如逻辑控制不展现的必填表单元素，加了loading后会被表单验证捕获

### What is expected?
加入loading后不影响card内部逻辑

### What is actually happening?
影响表单验证，不显示的表单元素被捕获异常

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16 |
| System | window |
| Browser | 谷歌 |

**Comment by afc163** [comment]
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/507615/50881642-41ad6300-141d-11e9-9092-f99994c59cbd.png">

重现链接里没有相关内容。

**Comment by mangoZT** [comment]
sorry ，地址弄错了
