### ISSUE TITLE
`Select` disabled option is auto selected in multiple search mode

### ISSUE THREAD

**Issue by stonexer** [ant-design/ant-design#14220]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/znm03xq73x)

### Steps to reproduce
1. type in "ant" in select
2. click somewhere to blur
3. disabled option "ant" is selected and unable to remove

### What is expected?
not select disabled option

### What is actually happening?
select disabled option

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | any |
| System | MacOS |
| Browser | Chrome |

**Comment by zy410419243** [comment]
Looks like https://github.com/ant-design/ant-design/issues/14089, maybe is the same problem.

**Comment by morenyang** [comment]
这个bug应该来源于 `rc-select` 在判断是否select 某个option的时候没有过滤掉被disabled的选项。

追溯到是在 `getValueByLabel` 函数中没有过滤`disable`，导致没有返回预期值。但是得看看如果直接过滤会不会产生什么impact

**Comment by morenyang** [comment]
Fix in https://github.com/react-component/select/pull/367

**Comment by afc163** [comment]
Fixed in rc-select@8.8.3
