### ISSUE TITLE
<Icon> 使用webpack 打包 ,type 类型指定失效

### ISSUE THREAD

**Issue by kongyes** [ant-design/ant-design#14225]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Icon type 类型

### What does the proposed API look like?
keyi

**Comment by kongyes** [comment]
打包之后 查看dom, 是<i>标签中包含一个固定的svg, 在使用creat-react-app 中查看 是一个选择器

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
