### ISSUE TITLE
<Select> and <AutoComplete> should pass all `dropdown*` props to <Dropdown>

### ISSUE THREAD

**Issue by Dorious** [ant-design/ant-design#14227]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For example I want to pass `placement` props:
<AutoComplete dropdownPlacement="bottomRight" />

### What does the proposed API look like?
All `dropdown[(. )]` should be rewritten to `$1` props on <Dropdown> component.

**Comment by afc163** [comment]
You can try `dropdownAlign`: https://github.com/react-component/select
