### ISSUE TITLE
TypeScript compatibility

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#1422]
To be more friendly to TypeScript developer, we should use another way to export components.

```jsx
Select.Option = Option;
Select.OptGroup = OptGroup;
export default Select;
```

to

```jsx
// For compatibility.
Select.Option = Option;
Select.OptGroup = OptGroup;

export { Option, OptGroup };
export default Select;
```

**Comment by benjycui** [comment]
Maybe you are interested in this. @waywardmonkeys

**Comment by waywardmonkeys** [comment]
I am! I have been on holiday for the last 2 weeks (sort of), but will be back around next week!

**Comment by benjycui** [comment]
Relative: https://github.com/ant-design/antd-init/issues/28

BTW, could you revise [antd.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/antd/antd.d.ts), and pull request to develop-1.0.0? Thanks! @waywardmonkeys @vvakame @bang88

**Comment by bang88** [comment]
Ping @waywardmonkeys we should following http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html or not .
IMO,we should consider the new TypeScript Definition Manager https://github.com/typings/typings and add `antd.d.ts` inline

**Comment by waywardmonkeys** [comment]
@bang88 I agree! I use ``typings`` myself rather than ``tsd``.

I think it would be great if the ``antd`` npm package could include the typings by default and then we can manage and update it along side the actual changes.

**Comment by popomore** [comment]
+1

**Comment by bang88** [comment]
+1 
 Include typings into `antd`,just need a place for `antd.d.ts` file.  @benjycui

**Comment by benjycui** [comment]
`mkdir type-definitions`, see: https://github.com/facebook/immutable-js/tree/master/type-definitions

You should update [publish scripts](https://github.com/ant-design/ant-design/blob/develop-1.0.0/package.json#L143) and README.md .

Thanks!
