### ISSUE TITLE
Internationalization of Ant Design website

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#1423]
Divide `index.md` into `index.zh-CN.md` and `index.en-US.md` and so on.

```bash
components/button
├── demo
│   └── basic.md
└── index.md
```

to

```bash
components/button
├── demo
│   └── basic.md
├── index.zh-CN.md
└── index.en-US.md
```

And `demo/*.md`:

```bash
---
order: 0
title: 
  en-US: Basic
  zh-CN: 基本用法
---

## zh-CN

罗里吧嗦。。。

## en-US

Blabla...

```jsx
ReactDOM.render(...);
```

**Comment by benjycui** [comment]
Should be compatible with current usage.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1471

**Comment by visvadw** [comment]
Hello everybody,

In `demo/*.md` files, as the order is english, then chinese, I would prefer the rest of the content to respect this order. Currently, as specified above, the content starts with zh-CN.
```---
order: 0
title: 
  en-US: Basic
  zh-CN: 基本用法
---```
You can update the previous comment so that the new content would follow this rule.

Thanks.

**Comment by benjycui** [comment]
It's not important. If we want to sort those text, we can write a script to do this.
