### ISSUE TITLE
table单元格内容为数字时会出现布局乱掉的情况。

### ISSUE THREAD

**Issue by yuanxuzhang** [ant-design/ant-design#14234]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yuanxuzhang/nocode/blob/master/img/ant_table190110.png](https://github.com/yuanxuzhang/nocode/blob/master/img/ant_table190110.png)

### Steps to reproduce
单元格内容为数字，且长度超过单元格设置长度即可重现

### What is expected?
能够如同文字那样换行

### What is actually happening?
单元格内为数字，不会换行，使布局乱掉了

| Environment | Info |
|---|---|
| antd | 3.9.3 |
| React | 16.5.2 |
| System | win7 |
| Browser | chrome 71 |

**Comment by dengfuping** [comment]
@yuanxuzhang 设置了宽度只会自动换行，只会对文本进行换行。但对于 `单个数组或英文单词` 来说，是没有 `换行` 说法的，只有 `断行` 的说法。所以你需要在文本元素上设置 `word-break: break-all`。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241
