### ISSUE TITLE
自定义筛选菜单（filterDropdown）点击自定义的UI界面时，会触发排序（sort）的问题。

### ISSUE THREAD

**Issue by shenguotao2015** [ant-design/ant-design#14238]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/gtshen/pen/KbxmQd?editors=1010](https://codepen.io/gtshen/pen/KbxmQd?editors=1010)

### Steps to reproduce
1. 在Table Columns 为某个字段列同时定义 sort 与 filterDropdown
2. 点击 filterDropdown 定义的UI(菜单)界面，会触发sort，并会切换排序的状态，类似于执行了排序操作。

### What is expected?
筛选不要干扰排序。

### What is actually happening?
筛选会干扰排序。

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.4.1 |
| System | Window 7 |
| Browser | Chrome  71.0.3578.80 |

**Comment by dengfuping** [comment]
ref: https://github.com/ant-design/ant-design/issues/14176

**Comment by zombieJ** [comment]
This commit add a mask of it which cover the input: https://github.com/ant-design/ant-design/commit/3bf7e2b
