### ISSUE TITLE
If loading data from server, the length of selectedRowKeys and selectedRows are different.

### ISSUE THREAD

**Issue by atomoo** [ant-design/ant-design#14235]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oj0qxp435)

### Steps to reproduce
1. listen the rowSelection change
2. select one row
3. change page
4. select another row, the length of selectedRowKeys and selectedRows are different

### What is expected?
hope that length of selectedRowKeys and selectedRows are same when change page

### What is actually happening?
length of selectedRowKeys and selectedRows are different

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.3.1 |
| System | macOS10.12.6 |
| Browser | chrome71.0.3578.98 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9751#issuecomment-410987043

Don't use selectedRows when loading data from server, cause the state isn't stored at frontend so it is not possible to keep selectedRowKeys same as selectedRows.
