### ISSUE TITLE
Tabs组件 在ie9下样式有问题

### ISSUE THREAD

**Issue by gyh9457** [ant-design/ant-design#14241]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
demo上切换tab

### What is expected?
标签切换时tabBar样式正常

### What is actually happening?
标签切换时tabBar无法随之切换

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7.0 |
| System | win7 |
| Browser | ie9 |

![image](https://user-images.githubusercontent.com/13557235/50948552-c9f33d00-14dd-11e9-85c7-226664a2b892.png)

**Comment by afc163** [comment]
Fixed by https://github.com/react-component/tabs/pull/159
