### ISSUE TITLE
Tree Component ：  What does the function parameter mean?

### ISSUE THREAD

**Issue by mengxxSELF** [ant-design/ant-design#14244]
What does the function parameter mean  at onDrap ?

for example  dropPosition and dropToGap .

onDrap 函数的几个参数代表什么含义呢 比如 dropPosition and dropToGap  这两个参数

**Comment by shiny** [comment]
文档写的不够详细，搜了整个 issue 区，查看源码最后得到结论如下。如果有人正好搜到，可参考：

- dropToGap 
代表连接到节点之间的缝隙中，相对 `node` 参数是上下关系，而不是子节点关系。
- dropPosition
antd 依赖了 rc-node，在 rc-node 里 dropPosition 是一个相对地址。如果拖到了目标节点的上面是 -1，下面则是 1。antd 里则是相对于目标节点的 index。如图所示，右侧的是 dropPosition，左侧是 节点的 index。
如果拖动时正好落在该节点上，dropPosition 就是该节点的 index。
![image](https://user-images.githubusercontent.com/117487/56514942-38c64480-6569-11e9-8e00-640378e674bd.png)

**Comment by hamza0867** [comment]
Hello, please can someone translate the response above to English ? Thank you so much

**Comment by shiny** [comment]
> Hello, please can someone translate the response above to English ? Thank you so much


- dropToGap
means connect to the gap  between nodes, it is the sibling of the node parameter, not child.
- dropPosition
Antd depends on rc-tree. dropPosition is an relative variable in rc-tree, when drag upon the target node, it is `-1`, or `1` under. In antd, dropPosition related to the target node's index. dropPosition on the right side and node's index on the left side as picture shown. if you drag on the node, dropPosition has the same value as the index of this node.


![](https://user-images.githubusercontent.com/117487/56514942-38c64480-6569-11e9-8e00-640378e674bd.png)

**Comment by hamza0867** [comment]
Thank you so much @shiny
