### ISSUE TITLE
Ant Design Mobile下的searchBar如何使弹出的键盘的return键文字设置为“搜索”

### ISSUE THREAD

**Issue by inkCrazy** [ant-design/ant-design#14249]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mobile.ant.design/components/search-bar-cn/](https://mobile.ant.design/components/search-bar-cn/)

### Steps to reproduce
.

### What is expected?
弹出的键盘的return键文字为“搜索”

### What is actually happening?
使弹出的键盘的return键文字为“换行”

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 0.57.4 |
| System | iOS11.2 |
| Browser | 版本 71.0.3578.98（正式版本） （64 位） |

**Comment by dengfuping** [comment]
相关问题请到 [antd-mobile](https://github.com/ant-design/ant-design-mobile/issues) 进行提问。
