### ISSUE TITLE
Select defaultOpen can not closed after click other empty places

### ISSUE THREAD

**Issue by lnwu** [ant-design/ant-design#14254]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/24ylz9521n)

### Steps to reproduce
click empty space

### What is expected?
click empty space can close select dropdown

### What is actually happening?
click empty space can not close select dropdown

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | latest react |
| System | latest mac os |
| Browser | latest chrome |

**Comment by zhaomengru2015** [comment]
set the value of  _defaultOpen_ the same as _autoFocus_ will solve the problem

**Comment by afc163** [comment]
We should auto focus search input when defaultOpen is true.

**Comment by lnwu** [comment]
@afc163 you mean the default behavior of the usage of defaultOpen?

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/commit/921d4c9e76f212bee8451ea8cb1ef6df637d3bdf
