### ISSUE TITLE
undefined.format('YYYY-MM-DD') should throw Error

### ISSUE THREAD

**Issue by sam-dingkang** [ant-design/ant-design#14255]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/bOxvpE?editors=0011](https://codepen.io/anon/pen/bOxvpE?editors=0011)

### Steps to reproduce
if the value of datePciker is 'undefined'，undefined.format('YYYY-MM-DD') not throw Error，It bothers me when i debug，it should throw Error!

### What is expected?
undefined.format('YYYY-MM-DD') should throw Error

### What is actually happening?
直接相当于 return，记得 antd 之前的版本会抛出错误

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | ^16.3 |
| System | all |
| Browser | all |

**Comment by sam-dingkang** [comment]
![image](https://user-images.githubusercontent.com/15643321/50958474-c1116400-14fb-11e9-9237-175de1bdb2a8.png)
补充一点，fileldsValue.date 是undefined，在format是不抛出错误直接return，真的很难debug

**Comment by sam-dingkang** [comment]
这个问题为什么没人回复？ @yutingzhao1991 @afc163 
复现例子也有，难道这不算bug?

**Comment by afc163** [comment]
https://github.com/react-component/form/pull/236

看上去是这个问题。

**Comment by afc163** [comment]
虽然看上去项目很大，但其实人手非常捉急，你也看到我们有几百个 issue 没解决，而且每天都有几十个新 issue。请容忍一些响应迟滞，非常感谢支持。

**Comment by afc163** [comment]
Fixed in rc-form@2.4.1, try reinstall node_modules.

**Comment by sam-dingkang** [comment]
非常感谢这么快响应，因为之前版本没有这个问题，所以有点不确定这个异常处理是不是你们故意这样设计的，我看到你们一直在回复其他的issue，所以等了两天，建议你们可以先回复一下，让我们知道原因，这样甚至可以提供PR
