### ISSUE TITLE
form-item中upload组件使用picture-card模式的时候，this.form.getFieldsValue获取到的upload值为C:\fakepath\***，而不是file对象的集合

### ISSUE THREAD

**Issue by changegt** [ant-design/ant-design#14252]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/changegt/pen/aPaEZe?editors=0001](https://codepen.io/changegt/pen/aPaEZe?editors=0001)

### Steps to reproduce
查看链接中的demo，提交表单的时候打印了数据

### What is expected?
{file, fileList}的集合

### What is actually happening?
C:\fakepath\***

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.6.3 |
| System | mac |
| Browser | chrome |

---
尝试过3.10.9和3.11.6antd版本，结果一样，应该和antd版本无关，搜索出的C:\fakepath 位于jsdom的NPM包中

**Comment by afc163** [comment]
You are using Upload in form in a total wrong way, check this：https://codepen.io/afc163/pen/ebLrbO?editors=1011

https://ant.design/components/form-cn/#components-form-demo-validate-other

**Comment by Ailton265** [comment]
I have the same problem, & I have searched for solution bu I didn't find anything. Can anyone help us pls?

**Comment by Monica-lee99** [comment]
我也遇到了，要怎么解决呢
