### ISSUE TITLE
Table filterdropdown filter buttons are not working perfectly 

### ISSUE THREAD

**Issue by jamhus** [ant-design/ant-design#14263]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/my84qy1068)

### Steps to reproduce
the question is not clear

### What is expected?
the expetced is that when i toggle between filters then it will work , for exemple i should be able to switch from read to updated directly with apply filter

### What is actually happening?
what happening is that when i switch filters then it does not work until i reset the filters , so if i want to change the filters then i need to reset the filters first

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | react 16.5.2 |
| System | ios |
| Browser | chrome |

**Comment by jamhus** [comment]
and also sending an empty list from my custom dropdown does not restore the filters, what am i missing?

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/50980368-7dd2e780-1533-11e9-9e33-251de362c07c.png)
You don't need `filterDropdown`. If you use `filterDropdown`, `antd` will handle the logic by yourself. Here is the `filterDropdown` example in docs. https://ant.design/components/table/#components-table-demo-custom-filter-panel

**Comment by jamhus** [comment]
> ![image](https://user-images.githubusercontent.com/17755202/50980368-7dd2e780-1533-11e9-9e33-251de362c07c.png)
> You don't need `filterDropdown`. If you use `filterDropdown`, `antd` will handle the logic by yourself. Here is the `filterDropdown` example in docs. https://ant.design/components/table/#components-table-demo-custom-filter-panel

so if i have to use my FilterDropdown then i have to rewrite the filtering logic by my self?

**Comment by ztplz** [comment]
Yes, if you want to customize, the filtering logic is written by yourself.

**Comment by afc163** [comment]
@ztplz is right. `filterDropdown` only provide overlay to put elements in.

**Comment by shiyingyan** [comment]
> @ztplz is right. `filterDropdown` only provide overlay to put elements in.

Hello  @afc163  .  According to normal logic ,  the table contents should not be filterd if the onFilter listener is empty .  
Now, It is totally confusing ！

**Comment by rajrachchh-0xblock** [comment]
it's all about antd version issue
