### ISSUE TITLE
UI display incorrectly when click at mask of multilayer Drawer

### ISSUE THREAD

**Issue by Bearfinn** [ant-design/ant-design#14267]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/Bearfinn/pen/OroEoY](https://codepen.io/Bearfinn/pen/OroEoY)

### Steps to reproduce
1. Create two drawers, one inside another with buttons to open the drawer
2. Set `mask={false}` props for inside drawer
3. Click at the mask area of the outside drawer
4. The visualization glitch will occur

### What is expected?
The inside drawer is hidden while the outside drawer remains (similar to when X is clicked)

### What is actually happening?
The outside drawer is moved to the left and is unclosable.
The inside drawer remains at the same position.

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7.0 |
| System | Windows 10 |
| Browser | Chrome 71.0.3578.98 |

---
I was working on information panel in which the inside drawer action needs information from the outside drawer (hence I set mask false in order to make it become clearer)

**Comment by afc163** [comment]
It is a intentional feature of nested drawers. You can put drawers in same level instead nest them.

```
<Drawer />
<Drawer />
```
