### ISSUE TITLE
checkbox will not change when using setFieldsValue

### ISSUE THREAD

**Issue by stkevintan** [ant-design/ant-design#14261]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9j7v570ljp)

### Steps to reproduce
按一下Toggle Checkbox， 按Submit， 可以看到checkbox是true，但是界面上的checkbox展示不会变

### What is expected?
checkbox随数据改变

### What is actually happening?
checkbox不会变

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.3 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
```jsx
          {getFieldDecorator('agreement', {
            valuePropName: 'checked',
          })(
            <Checkbox />
          )}
```

https://ant.design/components/form-cn/#components-form-demo-register
