### ISSUE TITLE
Failed to load on demand

### ISSUE THREAD

**Issue by MiDouShiTongTong** [ant-design/ant-design#14265]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/MiDouShiTongTong/Failed-to-load-on-demand](https://github.com/MiDouShiTongTong/Failed-to-load-on-demand)

### Steps to reproduce
- `npm run start`
- see console `injectBabelPlugin is not a function`

### What is expected?
Compiled successfully!

### What is actually happening?
injectBabelPlugin is not a function

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7.0 |
| System | windows10 x64 |
| Browser | chrome v71.0.3578.98 |

---
Estimated reason: React-app-rewired 2.0 does not export the injectBabelPlugin function.
Currently resolved: react-app-rewired version 2.0.1 => 1.6.2, react-scripts version 2.1.3 => 2.1.1.

**Comment by afc163** [comment]
Close in favor of https://github.com/ant-design/ant-design/pull/14385
