### ISSUE TITLE
<Upload> does not work as expect.

### ISSUE THREAD

**Issue by TheWaWaR** [ant-design/ant-design#1426]
## What you did
Put two `<Upload>` in one `<Form>` then submit the files.

## What you would like to happen
* I can get the URL/id (generate by server) of the file.
* I can get the file list by `form.getFieldsValue()` when I submit the form.

## What actually happened
* Two `<Upload>` will affect each other (**really strange**).
* When I setup `onChange` as `<Upload>`'s properties I can not get the file list.

## Online demo
* [Demo::含图片(文件)](http://demo-static.huhulab.com/react-frontend-boilerplate/#/demo/test_forms)
* [codepen.io](http://codepen.io/weet/pen/WwzQYd?editors=001)
* [Souce code](https://github.com/huhulab/react-frontend-boilerplate/blob/5a869a59d7ddf6785e1396a53971922fc9b20fb3/src/page/demo/RawForms.jsx#L482-L610)

*Upload server is required, so I wrote one.*

## Environment Information
- The version of antd: 1.0.0-bate.2@CentOS7
- Your operating system and it's version:OSX 10.11.0
- Your browser and it's version:Chrome 49.0.2623.112 (64-bit)

**Comment by benjycui** [comment]
粗略看了下你的代码，试下 https://github.com/react-component/form#optiongetvaluefromevent 应该就可以了。

**Comment by TheWaWaR** [comment]
为什么 `image1` 不可以 `image2` 是可以的

**Comment by benjycui** [comment]
fc-form 的 state 被重置了，我稍后再看看吧

**Comment by benjycui** [comment]
麻烦提供未压缩的代码，这样我打不了断点。。

**Comment by TheWaWaR** [comment]
Demo 下面的链接就是源码。

**Comment by benjycui** [comment]
> 这样我打不了断点。。

**Comment by TheWaWaR** [comment]
https://github.com/huhulab/react-frontend-boilerplate/blob/5a869a59d7ddf6785e1396a53971922fc9b20fb3/src/page/demo/RawForms.jsx#L482-L610

有源码不能打断点吗？

**Comment by TheWaWaR** [comment]
codepen.io: http://codepen.io/weet/pen/WwzQYd?editors=001

**Comment by benjycui** [comment]
使用方式问题，正确使用方式见：http://codepen.io/benjycui/pen/xVaBjd?editors=001

另外，不建议修改 `getFieldProps` 返回的对象，应将其视为一个黑盒，直接使用即可。

**Comment by TheWaWaR** [comment]
刚看了下文档，的确是我用法的问题。

我觉得你文件上传相关的接口的设计不太好，像 `normalize` 这样的函数不应该让用户来写。还有就是哪些参数应该放 `getFieldProps.options`  里面，哪些应该 `Object.assign` ，没有相应的例子，你不觉得用户会比较困惑吗？

**Comment by benjycui** [comment]
文档中是有的，API 是因为目前没有想到更好的方案，如果你有更好的想法，可以开个 issue 提 proposal。
