### ISSUE TITLE
form validation for type="array" does not work

### ISSUE THREAD

**Issue by neekey** [ant-design/ant-design#14275]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/narratiive-neekey/pen/ebPRmv](https://codepen.io/narratiive-neekey/pen/ebPRmv)

### Steps to reproduce
As in the code, I have already setup the validation rule:

```
rules: [{ required: true, message: 'The tags must be urls', type: 'array', defaultField: { type: 'url' } }],
```
so that the select value must be presented and also each item's value must be a valid URL.

- Step 1: leave the select empty, click "submit", the validation error shows up correctly
- Step 2: input any invalid url string, click "submit" the validation error does not show up and the form will be submitted successfully as an alert will popup
- Step 3: open the console, you can see the validation log is actually showing :

```
async-validator: ["tags.0 is not a valid url"]
```

### What is expected?
the validation should work and the error msg should be shown under the select

### What is actually happening?
the validation does not work

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16 |
| System | mac os |
| Browser | chrome 71 |

---
A same issue has been raised before https://github.com/ant-design/ant-design/issues/5007, but it was closed not because the problem was resolved, but the owner of the issue used custom validator instead.

**Comment by neekey** [comment]
The usage of the rule `array` and `defaultField` can be found here https://github.com/yiminghe/async-validator#defaultfield

**Comment by dengfuping** [comment]
@neekey Incorrect usage. Please refer to the [demo](https://codepen.io/dengfuping/pen/REegqw).

**Comment by neekey** [comment]
@dengfuping thanks! So guess we need to separate the `required | array | url` to different rules:

```js
{
    rules: [
        { required: true, message: 'xxxx' },
        { type: 'array', message: 'xxxx' },
        { defaultField: 'url', message: 'xxxx' },
    ]
}
```

**Comment by neekey** [comment]
@dengfuping sorry I double checked the demo you provided, it's actually not working correctly (the error message is misleading here, as in your demo, you changed the `type` to `email`):

![image](https://user-images.githubusercontent.com/499870/51012587-f8424c80-15b1-11e9-94dd-c0d054eaed1c.png)

![image](https://user-images.githubusercontent.com/499870/51012592-02fce180-15b2-11e9-8c9f-04e27db34ddd.png)

if change the value to an invalid email:

![image](https://user-images.githubusercontent.com/499870/51012621-32abe980-15b2-11e9-899f-d2492f3797c0.png)

and actually the validation log is the same: 

![image](https://user-images.githubusercontent.com/499870/51012638-46575000-15b2-11e9-9d39-81d3b4ff3e0b.png)

Obviously the third rule `{ defaultField: 'url', message: 'xxxx' }` worked as checking the whole list against string.

--------------------------

so get back to my original [demo](https://codepen.io/narratiive-neekey/pen/ebPRmv) (it's actually align with the example given in the [async-validator](https://github.com/yiminghe/async-validator#defaultfield)): 

```js
{
    rules: [{ required: true, message: 'The tags must be urls', type: 'array', defaultField: { type: 'url' } }],
}
```

the validation log actually work correctly, but the error does not show up in the form:

![image](https://user-images.githubusercontent.com/499870/51012739-cc739680-15b2-11e9-8834-75822ccf1a42.png)

I believe it is a bug, thanks.

**Comment by neekey** [comment]
@dengfuping have you double checked?

**Comment by dengfuping** [comment]
@neekey Yeah! It seems a bug. Thanks for your report.

**Comment by DavidSichau** [comment]
This is still a but in the last release of antd 3.13.6

**Comment by SHITianhao** [comment]
@zombieJ any plan for adding `defaultField ` in type definition?

**Comment by yuantongkang** [comment]
> 我发现如果数组里嵌套对象，也会出现错误在控制台提示，而界面没有提示的情况。 @zombieJ
> [![dBrlGV.png](https://camo.githubusercontent.com/f872715ccdc035c3f1f6b58ad47635d391d04f0c/68747470733a2f2f73312e617831782e636f6d2f323032302f30382f32342f6442726c47562e706e67)](https://imgchr.com/i/dBrlGV)

校验规则如下
![dBrfit.png](https://s1.ax1x.com/2020/08/24/dBrfit.png)

**Comment by hoavo1490** [comment]
Have you already fixed this? I still have the same issue now.
![image](https://user-images.githubusercontent.com/49126861/104418757-057fe080-55aa-11eb-9b34-7431a0d9d4b8.png)

**Comment by sokre90** [comment]
> Have you already fixed this? I still have the same issue now. ![image](https://user-images.githubusercontent.com/49126861/104418757-057fe080-55aa-11eb-9b34-7431a0d9d4b8.png)

Hi, did you find a solution to this problem?
