### ISSUE TITLE
Table.Column props defaultSortOrder does not work when columns definition is async created 

### ISSUE THREAD

**Issue by bathpp** [ant-design/ant-design#14270]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l4r3y610kq)

### Steps to reproduce
Put  ```defaultSortOrder``` in column definition, and set the definition in place other than the component initiation.
The reproduction repo has clear info to reproduce. 

### What is expected?
defaultSortOrder props should work as expected

### What is actually happening?
defaultSortOrder props will not work when the table columns definition is not created with the component first render.

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | React 16.7 |
| System | Windows 10 |
| Browser | Chrome 71.0.3578.98 |

---
I need to generate the table column definition based on data from server, I do this in life cycles like componentDidUpdate, all other things work except this defaultSortOrder props.

**Comment by afc163** [comment]
Try `sortOrder`, `defaultSortOrder` only works in first render. Please learn React controlled components first: https://reactjs.org/docs/forms.html#controlled-components

**Comment by cdosborn** [comment]
Respectfully this has nothing to do with controlled components. You could point someone in that direction, if the component never received the prop in the first place. I understand why it doesn't work, but it is because of the non-reactive nature of the implementation.

**Comment by barbinbrad** [comment]
Just to add to this, I can confirm that it doesn't work even on the first render.
