### ISSUE TITLE
modifyVars in less are not being over ridden in webpack configuration

### ISSUE THREAD

**Issue by rockyhuber** [ant-design/ant-design#14272]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/54139022/less-modifyvars-not-overriding-the-styles-in-webpack-when-using-antdesign](https://stackoverflow.com/questions/54139022/less-modifyvars-not-overriding-the-styles-in-webpack-when-using-antdesign)

### Steps to reproduce
Create react app, eject application, try to modifyVars in webpack. 

### What is expected?
That the default variables will be over ridden and new styles applied.

### What is actually happening?
The default antDesign css values remain, however I can see the modifyVars values in the elements styles are being over ridden by the default values.

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.6.3 |
| System | Mac OSX |
| Browser | Chrome 71.0.35... |

---
See https://stackoverflow.com/questions/54139022/less-modifyvars-not-overriding-the-styles-in-webpack-when-using-antdesign for more information. I have tried to make the less values !important, though am unable to do this through webpack. No reproduction link available as it is a webpack issue, thanks.

**Comment by afc163** [comment]
Could you provide a reproducible and minimal git repo?

**Comment by hantq** [comment]
@rockyhuber I saw you've been using `@primary-color`, `@link-color`, etc. It seems that you should use `primary-color`, `link-color` instead.

**Comment by tomasfrancisco** [comment]
I believe I'm having a similar problem but with CRA 2.0 and `customize-cra`.
I've followed the docs from [here](https://ant.design/docs/react/use-with-create-react-app)

I'm not able to override the theme through `modifyVars`. In my case, it doesn't even appear at any time on the browser as @rockyhuber describes.

Here's a repo that can reproduce the issue.
https://github.com/tomasfrancisco/cra-antd

**Comment by afc163** [comment]
```diff

const { override, fixBabelImports, addLessLoader } = require("customize-cra");

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
 -  style: "css",
 +  style: "less",
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { "primary-color": "#1DA57A" }
  })
);
```

@tomasfrancisco

css cannot be override by less variables.

**Comment by yuzhakovvv** [comment]
Didn't work for me. Default variables still override my custom variables with exact same name

**Comment by yuzhakovvv** [comment]
@rockyhuber did you figure this out?

**Comment by yuzhakovvv** [comment]
So I contacted @rockyhuber and we figured out the solution.

**Problem:**
The way Ant Design says to work with styles when you use Create React App:
https://ant.design/docs/react/use-with-create-react-app

> Add antd/dist/antd.css at the top of src/App.css.
```
@import '~antd/dist/antd.css';

.App {
  text-align: center;
}

...
```

**Solution:**
So when you want to override variables, **you have to remove import of** `~antd/dist/antd.css` as it overrides your `modifyVars` override  🤦‍♂

**Comment by tridungle** [comment]
> So I contacted @rockyhuber and we figured out the solution.
> 
> **Problem:**
> The way Ant Design says to work with styles when you use Create React App:
> https://ant.design/docs/react/use-with-create-react-app
> 
> > Add antd/dist/antd.css at the top of src/App.css.
> 
> ```
> @import '~antd/dist/antd.css';
> 
> .App {
>   text-align: center;
> }
> 
> ...
> ```
> 
> **Solution:**
> So when you want to override variables, **you have to remove import of** `~antd/dist/antd.css` as it overrides your `modifyVars` override man_facepalming

Thank alot! You saved my life

**Comment by kami-sprakashk** [comment]
Thanks [yuzhakovvv](https://github.com/yuzhakovvv).  Spent almost a day figuring it out. Your solution worked like a charm.
