### ISSUE TITLE
Table-固定头和列

### ISSUE THREAD

**Issue by Lpbzzz** [ant-design/ant-design#14274]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
适合同时展示有大量数据和数据列

### What does the proposed API look like?
表格里的列是可以通过表格底部的滚动条左右拖动。但是如果能在表格上，通过鼠标 按下-移动-抬起 来横向移动表格内容 会更好一些。

**Comment by afc163** [comment]
还是保持浏览器的原生操作比较合适，自创交互是很难被发现和使用的。
