### ISSUE TITLE
form表单的必填校验有点小问题

### ISSUE THREAD

**Issue by wiyhvs** [ant-design/ant-design#14281]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/form-cn/](https://ant-design.gitee.io/components/form-cn/)

### Steps to reproduce
设置输入框有默认值，并且是非必填的，且在五秒后自动变为必填，并且在这之前删除掉默认值，此时输入框出现了必填标志，但是提交没有必填校验

### What is expected?
能够成功检测且不能提交

### What is actually happening?
没有出现必填提示，且能正常提交

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | react ^15.3.2 |
| System | window 10 |
| Browser | chrome |

---
// 注：代码改至https://ant-design.gitee.io/components/form-cn/      表单联动 

const { Form, Select, Input, Button, } = antd;

const { Option } = Select;

class App extends React.Component {
  constructor(props){
        super(props);
        this.state = {
            a: false
        }
  }
  componentWillMount(){
        setTimeout(() => {
            this.setState( { a : true })
        }, 5000)
    }
  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        console.log('Received values of form: ', values);
      }
    });
  }

  handleSelectChange = (value) => {
    console.log(value);
    this.props.form.setFieldsValue({
      note: `Hi, ${value === 'male' ? 'man' : 'lady'}!`,
    });
  }

  render() {
    const { getFieldDecorator } = this.props.form;
    const { a } = this.state;
    return (
      <Form onSubmit={this.handleSubmit}>
        <Form.Item
          label="Note"
          labelCol={{ span: 5 }}
          wrapperCol={{ span: 12 }}
        >
          {getFieldDecorator('note', {
            rules: [{ required: a, message: 'Please input your note!' }],
             initialValue: "1234"
          })(
            <Input />
          )}
        </Form.Item>
        <Form.Item
          label="Gender"
          labelCol={{ span: 5 }}
          wrapperCol={{ span: 12 }}
        >
          {getFieldDecorator('gender', {
            rules: [{ required: true, message: 'Please select your gender!' }],
          })(
            <Select
              placeholder="Select a option and change input text above"
              onChange={this.handleSelectChange}
            >
              <Option value="male">male</Option>
              <Option value="female">female</Option>
            </Select>
          )}
        </Form.Item>
        <Form.Item
          wrapperCol={{ span: 12, offset: 5 }}
        >
          <Button type="primary" htmlType="submit">
            Submit
          </Button>
        </Form.Item>
      </Form>
    );
  }
}

const WrappedApp = Form.create({ name: 'coordinated' })(App);

ReactDOM.render(<WrappedApp />, mountNode);

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11820#issuecomment-414885683
