### ISSUE TITLE
Passing a two-dimensional array in antd Table component dataSource props is a warning，Warning: Failed prop type: Invalid prop `record` of type `array` supplied to `ExpandableRow`, expected `object`

### ISSUE THREAD

**Issue by lovewinders** [ant-design/ant-design#14289]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)

### Steps to reproduce
step1 import { Table } from 'antd';

step2: <Table columns={columns}  dataSource={[[1, 2, 3, ...]]} />

step3:  run

### What is expected?
no warning，Maybe another way. antd Table component dataSource props support a two-dimensional array

### What is actually happening?
Warning: Failed prop type: Invalid prop `record` of type `array` supplied to `ExpandableRow`, expected `object`

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | react |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
Just follow warning messge: `Warning: Failed prop type: Invalid prop record of type array supplied to ExpandableRow, expected object`

The item of dataSource should be object instead of Array.

**Comment by afc163** [comment]
https://github.com/react-component/table/commit/cecc6476373568d8ffe0708f62f8d9e87be8533c

**Comment by lovewinders** [comment]
all the same ： Warning: Failed prop type: Invalid prop `record` of type `array` supplied to `TableRow`, expected `object`

**Comment by lovewinders** [comment]
> Maybe you are right.

Warning: Failed prop type: Invalid prop record of type array supplied to TableRow, expected object

**Comment by lovewinders** [comment]
You modified Expandable Row. js, but missed a file called TableRow. js, so TableRow still reports type warnings.

**Comment by afc163** [comment]
I see, could you send PR to https://github.com/react-component/table/ to fix that problem?

**Comment by lovewinders** [comment]
ok， thank you！
