### ISSUE TITLE
Allow prefix/suffix and addonBefore/addonAfter on InputNumber just like Input component

### ISSUE THREAD

**Issue by asumaran** [ant-design/ant-design#14284]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I was working on a custom input that formats the entered data into monetary value.

Something like: `9876.12` => `9,876.12` and also wanted to add a `$` prefix into the input without being part of the input value.

I noticed we can do that with the `Input` component but in order to format the entered value to the format I wanted I realized it was not going to be as easy as `InputNumber` with `formatter` and `parser` props.

I ended up wrapping up an `InputNumber` into another component which accepts all the same props as `InputNumber` plus the `prefix` option and made it look exactly as `Input`.

The render method looks something like

```jsx
render() {
  const { prefix, ...inputNumberProps } = this.props;

  return (
    <span className="my-custom-component">
      <span className="prefix">{prefix}</span>
      <InputNumber {...inputNumberProps} />
    </span>
  );
}
```

I think it would be useful if `InputNumber` accepts a `prefix` prop for cases like this.

### What does the proposed API look like?
The use and result should be exactly as `Input`.

`<InputNumber prefix="$" />`

`<InputNumber prefix={<span>$</span>} />`

**Comment by afc163** [comment]
You can try `<Input type="number" prefix="$" />` instead of InputNumber.

**Comment by asumaran** [comment]
@afc163 yes, that was my first attempt. But I find it easier to format the entered value using `InputNumber` using `formatter` and `parser` props.

**Comment by asumaran** [comment]
@dengfuping I would like submit a PR implementing this feature can I?

**Comment by pavolgolias** [comment]
I would appreciate this option too. 
It would be perfect to use `InputNumber` in the same way as `Input`.
Besides `prefix` I would also suggest creating these features in `InputNumber`:
- `suffix`
- `addonBefore`
- `addonAfter`
- option to show/hide arrows for increment/decrement of value of `InputNumber`

I am especially interested in `addonBefore `and `addonAfter` options as it is a very nice feature of `Input` which I would like to use with `InputNumber` too.
Are there any plans to add them in future releases? 
@afc163 @dengfuping

**Comment by afc163** [comment]
#10846 (comment)
#1228 (comment)
https://github.com/ant-design/ant-design/issues/12794

**Comment by pavolgolias** [comment]
@afc163 I am not sure what is the result of this issue?
Issue #15214 and #12794 are just duplicates of this issue
Issue #10846 - there is a suggestion to use `Input.Group`, which is a good idea but this component is also not working 100% correctly - see #5790
Issue #1228 - using of `<Input type="number" />` is also not the best solution because it behaves like standard HTML5 input with its own validation and it returns `string` instead of `number` so it can cause inaccuracies against custom typescript types.

So, is there possibility/plan to extend `InputNumber` properties so we can use this component in the same way as standard `Input`? 
Thanks :)

**Comment by skiingyac** [comment]
use this in some component file, say whatever.js:
```js-jsx
import React from 'react';
import { InputNumber } from 'antd';

export class BetterInputNumber extends React.Component {
  render() {
    if (this.props.addonAfter) {
      return (
        <>
          <InputNumber style={{verticalAlign:'middle', borderBottomRightRadius:0, borderTopRightRadius:0}} {...this.props}/>
          <div className="ant-input-group-addon" style={{paddingTop:'2px', verticalAlign:'middle', display:'inline-table', lineHeight:'24px', height:'32px'}}>{this.props.addonAfter}</div>
        </>
      );
    } else {
      return (
          <InputNumber {...this.props}/>
      );
    }
  }
}
```

now you can do:
```js-jsx
import {BetterInputNumber} from 'whatever'
class Yourthing extends React.Component {
  render() {
    return (
      <BetterInputNumber addonAfter="mph"/>
    );
  }
}
```

**Comment by ops1ops** [comment]
@afc163 What about suffix and prefix support? I think `InputNumber` should inherit from basic Input and have the same logical needed props (Suffix, Prefix and so on). For example when you use InputNumber as currency input. And solutions like `InputGroup` and `<Input type="number" />` are not even solutions. They are **workarounds**. I would understand if this wrote common library user. But it seems like you don't even want to improve and make better your library.

**Comment by gregpardo** [comment]
I got around this for a form field by adding a custom validator for a regular input field.

```javascript 
const inputNumberValidator = (rule, value) => {
  let min = rule.min
  let max = rule.max
  const message = rule.message
  if (min != null) min = Number(min)
  if (max != null) max = Number(max)
  try {
    const object = Number(value)
    if (min != null && object < min) throw new Error(message)
    if (max != null && object > max) throw new Error(message)
    if (isNaN(object)) throw new Error(message)
    return Promise.resolve()
  } catch (err) {
    return Promise.reject(err)
  }
}
```

Then using the validator like this

```jsx
<Form.Item
  label="My Number"
  rules={[
    {
      min: 0.0,
      max: 10.0,
      message: "Amount must be between 0 and 10",
      validator: inputNumberValidator
    }
  ]}
>
  <Input prefix="$" suffix="USD" />
</Form.Item>
```

**Comment by JoeCMorgan** [comment]
Is there any update on this? It would be really useful to use both the formatted and the suffix...

**Comment by edencorbin** [comment]
Any update on this? Agreed this would be very useful on InputNumber.

**Comment by Yu-Rain** [comment]
我暂时先这样解决了, 还不清楚会有什么没有测试到的隐患问题
我的需求是各类表单组件都有可能有前后缀或者表单组件后面跟着一个按钮, 这种方法虽然麻烦些, 但是比较通用. 
> 暂时还未进行封装, 因为这些代码都是会经过程序自动生成, 无需人工手动编写

```js
<Form.Item
        label={"贷款余额"}
        labelCol={{xs: {span: 8}}} wrapperCol={{xs: {span: 16}}}
      >
        <div className="form-after-before-box">
          <span>{"人民币"}</span>
         // 必须要有这个 Form.Item, 否则无法用form对象的方法进行设置和取值
          <Form.Item
            initialValue={defaultValue(this.$exp[17](), "")}
            name="grzhye" // 注意name属性位置
            htmlFor="grzhye"
          >
            <InputNumber
              id={'grzhye'}
              precision={0}
              step={1}
            />
          </Form.Item>
          <span>{"元"}</span>
        </div>
      </Form.Item>
```

**Comment by stcalica** [comment]
any updates on this? still not working for me.

**Comment by cookcc** [comment]
贴了一大堆没啥有用的

**Comment by MattBevis** [comment]
SO reading through all of this has left me more confused? Has anyone done this or not?

**Comment by AdamGerthel** [comment]
@MattBevis Doesn't seem like it, no.

**Comment by alex-zwingli** [comment]
To the savvy engineer able to add this update, many thanks in advance!! It seems very intuitive that we should have this.

**Comment by wuhao5436** [comment]
```typescript
import React from 'react'
import { Input } from 'antd'
import type { InputProps } from 'antd'
import { inRange } from 'lodash'

type CustomNumberInputProps = InputProps & {
  precision?: number
}

export function CustomNumberInput(props: CustomNumberInputProps) {
  const { value, onChange, max=100.01, min=0, precision=0, ...otherProps} = props;
  if (!Number.isInteger(precision) || precision< 0) {
    throw new Error("precision is not right")
  }

  return <Input
    {...otherProps}
    value={value}
    onChange={(e) => {
      const inputVal = e.target.value;
      const inputNumber = inputVal.replace(/[^0-9\.]/g, '');
      if (Number(inputNumber)!== NaN && inRange(Number(inputVal), Number(min), Number(max))) {
        onChange(e);
      }
    }}
    onBlur={(e) => {
      const inputNumber = Number(e.target.value) || 0 ;
      /** formate */
      e.target.value = Number(inputNumber).toFixed(precision);
      onChange(e);
    }}
  />
}


```

**Comment by afc163** [comment]
Is anyone interest to send PR for this feature?

**Comment by Austaras** [comment]
I could have a try

**Comment by wwyx778** [comment]
but is not support `suffix` now...

**Comment by luckymore** [comment]
@wwyx778 already support in Antd@4.x

**Comment by wwyx778** [comment]
> @wwyx778 already support in [Antd@4.x](mailto:Antd@4.x)

@luckymore only support `prefix`, not support `suffix`.

**Comment by glow27** [comment]
please add `suffix`

**Comment by OriBenNun** [comment]
suffix still missing, please add support

**Comment by luckymore** [comment]
@wwyx778 How about this... 
https://github.com/luckymore/IfAntdV4/blob/master/IfAntdV4/InputNumber/demo/index.js

**Comment by IsmailKemmoune** [comment]
> @afc163 yes, that was my first attempt. But I find it easier to format the entered value using `InputNumber` and its `formatter` and `parser` props.

this is a good solution, but it hides the placeholder

**Comment by Linggos06** [comment]
Same for Input.Password.
It supports prefix but suffix is missing. 
Maybe you can fix this bug.

**Comment by dey-dey** [comment]
Yeah, a way to create this type of input would be awesome!

<img width="168" alt="Screenshot 2023-06-04 at 10 31 40 AM" src="https://github.com/ant-design/ant-design/assets/796926/a3f6c31b-fa81-417c-b2aa-57a66bb1ac62">

**Comment by Scxw010516** [comment]
Please，we need suffix of InputNumber

**Comment by afc163** [comment]
`suffix` has been added in https://github.com/ant-design/ant-design/pull/49674

**Comment by hugobarragon** [comment]
@afc163 input.password doesnt have suffix prop yet, will it be added?
