### ISSUE TITLE
props.prefixCls got removed from updated antd version, so there no way of checking component type

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#14287]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input/](https://ant.design/components/input/)

### Steps to reproduce
using console.log() to print <Input> component

### What is expected?
I should have 'ant-input' as props.prefixCls

### What is actually happening?
prefixCls got removed

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.3.1 |
| System | mac os |
| Browser | firefox |

**Comment by shuozhang2016** [comment]
antd 3.12.1
![image](https://user-images.githubusercontent.com/17228552/51027870-ef12a900-15cc-11e9-8c95-86b4a5ae259d.png)


antd 3.11.6
![image](https://user-images.githubusercontent.com/17228552/51028118-8ed03700-15cd-11e9-9ce4-e648475de410.png)


component.props.prefixCls is lost in 3.12.1

**Comment by shuozhang2016** [comment]
@yesmeck

**Comment by afc163** [comment]
不应该依赖这个，不推荐这么用，这不是我们对外暴露的 API。

**Comment by nuaajiangteng** [comment]
> 不应该依赖这个，不推荐这么用，这不是我们对外暴露的 API。

那有没有其他方法来判断是何种组件呢？

**Comment by zombieJ** [comment]
> 那有没有其他方法来判断是何种组件呢？

https://discuss.reactjs.org/t/how-to-determine-what-type-of-component-a-child-is/3951/2
