### ISSUE TITLE
select控件在IE中，鼠标拖动下拉框滚动条，下拉框会消失

### ISSUE THREAD

**Issue by zero2lin** [ant-design/ant-design#1428]
select在IE中，鼠标拖动下拉框滚动条，下拉框会消失
http://ant.design/components/select/ ，搜索框那个就能看到

**Comment by afc163** [comment]
确认了。

相关问题：https://github.com/ant-design/ant-design/issues/1150#issuecomment-193699019 https://github.com/react-component/trigger/issues/11

**Comment by wzuhyl** [comment]
rc-select新版本已经解决这个问题了，麻烦升级一下

**Comment by afc163** [comment]
@wzuhyl https://github.com/ant-design/ant-design/blob/develop-1.0.0/package.json#L57

**Comment by sundyxfan** [comment]
@wzuhyl  @afc163 其实相关问题＃1150说的不是select的问题,  是rc-trigger的问题，rc-trigger 设置的popup是自己定义的一个列表，然后单击列表的一项出现模态窗，然后单击模态窗，就会触发rc-trigger的document  mousedown事件

**Comment by wzuhyl** [comment]
哦。。好的，那麻烦先升级下npm上的包，把[点击placeholder下拉框消失的bug](https://github.com/react-component/select/pull/68)先解决下

**Comment by yiminghe** [comment]
rc-select@6.1.2

**Comment by tianlang89757** [comment]
There is still a problem with Internet explorer's Edge document mode.

**Comment by ajieying** [comment]
没看明白这个是怎么解决的
