### ISSUE TITLE
日期选择框中月份选择框在选择前一年之后出现的年份还是显示当前年份

### ISSUE THREAD

**Issue by xieww** [ant-design/ant-design#14288]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
在弹出的月份框直接点击年份，选择之前的任何某一年，之后出现的年份仍然是当前年份

### What is expected?
在弹出的月份框直接点击年份，选择之前的任何某一年，之后出现的年份应该是选中之后的年份

### What is actually happening?
在弹出的月份框直接点击年份，选择之前的任何某一年，之后出现的年份仍然是当前年份

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | react@16.6.0 |
| System | Mac OS X 10_13_6 |
| Browser | Chrome/71.0.3578.98 |

**Comment by Yangzhedi** [comment]
确实是个bug

**Comment by Yangzhedi** [comment]
官网上的basic demo 确实有这个问题，但是在本地没复现出来 
是不是新版本修复过了？

**Comment by Yangzhedi** [comment]
> > 官网上的basic demo 确实有这个问题，但是在本地没复现出来
> > 是不是新版本修复过了？
> 
> 我现在本地更新到antd@3.12.2，依然有这个问题，应该是没有修复的

再看看

**Comment by alex89lj** [comment]
我也碰到了这个问题  RangePicker里的日期面板切换月份后 会清除   但是月份面板切换后 月份还是之前选择月份 这很怪异   另外普通的DatePicker的日期面板切换月份后 没有清除日期 而且他的交互效果让人有点困惑
![image](https://user-images.githubusercontent.com/8944883/51224904-14b00180-1983-11e9-8eb1-3c48c347b637.png)

**Comment by zombieJ** [comment]
Duplicate of #14371
