### ISSUE TITLE
Using ShowAction to open dropdown on focus breaks click behavior

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#14296]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/9l52v0j0rr)

### Steps to reproduce

1: Make sure you're not already focused on the `Select` component
2: Click the expand arrow (make sure you click the the down arrow icon.  If it doesn't happen, de-select component and try again)

### What is expected?
The select would expand and show the options

### What is actually happening?
It briefly opens and then immediately closes again.  
| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.7.0 |
| System | OSX |
| Browser | Chrome 71 |

---
Example is setup with a common use case of wanting the select to open when tabbed into.  It uses the underlying rc-select `showAction` which is mentioned in #6873.  You can see this in action by focusing on the input and then hitting tab.

However, adding this prop causes issues with the select opening up properly when clicking on it.

**Comment by ChuckJonas** [comment]
Wierd... I'll create a repro gif Sundays afternoon and also do more testing to see if it's maybe browser/extension related

**Comment by ChuckJonas** [comment]
I can actually repro it on my phone even (Android Google chrome). As long as I'm not already focused on the select, it opens and then immediately closes (no matter where I click).

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51093643-aa5f5b80-17e0-11e9-9ef3-3ce667c17c5c.png)

Actually you don't need to set this property.  You set `focus` and `click`, which will cause two changes to be triggered when there is no focus. The internal logic:  when `Select` isn't focus, click arrow icon, `trigger focus event => setState({open: !this.state.open}) => open(false default), then trigger click event => setState({open: !this.state.open}) => close`.
So it closed immediately after opening，

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51093812-45a50080-17e2-11e9-90a9-1499642a195d.png)
Comment it or just set `click` will work fine. Although you can use `showAction`, it is not in the document, not a public property.

**Comment by ChuckJonas** [comment]
Here's a GIF of it happening in chrome for OSX... It also happens in my safari.

![opvdkg0shg](https://user-images.githubusercontent.com/5217568/51094903-f7eeb080-176d-11e9-98f5-48c8a0ea718b.gif)

@ztplz the whole point of doing this in the first place is to be able to open the drop down on focus!  #6873 was closed with `showAction={['focus']}` as an acceptable solution.   

This is a **must have** feature for working with a `Select` (so maybe #6873 should be reopened)

**Comment by ztplz** [comment]
Currently the problem is that `focus` works fine, and `click` also work fine. But it won't work together. 
We will resolve the conflict between `focus` and `click`.

**Comment by afc163** [comment]
It only happens when click the arrow icon.

**Comment by ztplz** [comment]
@afc163  Because the click trigger function is bound to the span that wraps the icon. 
![image](https://user-images.githubusercontent.com/17755202/51101332-2f646800-1815-11e9-8b57-46d1727eb9c1.png)
If you click inside the input box but outside the icon, it will only trigger `focus`. So it's work fine.
But if you click icon, it will trigger `focus` and `click`.
At first `focus` set `open` to true, then `click` set `open` to false.

**Comment by afc163** [comment]
We can add `pointer-events: none` to arrow.

**Comment by ztplz** [comment]
This is not a css problem, some logic that controls `open` needs to be fixed.

**Comment by ztplz** [comment]
https://github.com/react-component/select/blob/master/src/Select.tsx#L465
Should consider the case that both of `focus` and `click`.

**Comment by zombieJ** [comment]
Since `showAction` is internal prop from `rc-select`. We don't pop to the antd doc. If you use this prop, you should also add related css to handle this: https://codesandbox.io/s/3vqk45o9q6

**Comment by zsf3** [comment]
Any update on this one? How to get around this issue while having both actions `focus` and `click`?

**Comment by Flynamic** [comment]
When can we expect a fix of this issue?
