### ISSUE TITLE
form表单里的使用upload组件，点击label也能触发选择文件

### ISSUE THREAD

**Issue by kid0809** [ant-design/ant-design#14298]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
form表单里的使用upload组件，点击label也能触发选择文件

### What is expected?
点击label不触发选择文件

### What is actually happening?
form表单里的使用upload组件，点击label也能触发选择文件

| Environment | Info |
|---|---|
| antd | 3.11.2 |
| React | react |
| System | win10 |
| Browser | chrome |

---
<Upload {...props}>
  {fileList.length >= 1 ? null : uploadButton}
</Upload>
当fileList.length 大于等于1时，点击label还是可以触发上传

**Comment by afc163** [comment]
It is a feature, not a bug.

**Comment by kid0809** [comment]
> It is a feature, not a bug.

您好，当上传了一个文件时，我把upload按钮给null了。我不希望他上传第二个文件，但他还是可以通过点击label触发上传文件？这不算bug吗？

**Comment by afc163** [comment]
> 您好，当上传了一个文件时，我把upload按钮给null了。我不希望他上传第二个文件，但他还是可以通过点击label触发上传文件？

这个看上去就是 bug 了，给个重现观察一下吧。

**Comment by kid0809** [comment]
> > 您好，当上传了一个文件时，我把upload按钮给null了。我不希望他上传第二个文件，但他还是可以通过点击label触发上传文件？
> 
> 这个看上去就是 bug 了，给个重现观察一下吧：http://u.ant.design/codesandbox-repro

https://codesandbox.io/s/14xp2oz20l

这个demo没有接收上传文件的地址。。关键点在

`                                    <Upload {...props}>
                                        {fileList.length >= 1 ? null : uploadButton}
                                    </Upload>
`
当fileList大于等于1时，我都没显示上传控件了，但是点label还是可以上传

**Comment by Yangzhedi** [comment]
是不是要考虑给label加个属性 控制focus
