### ISSUE TITLE
how to set table columns width? the width property is invalid

### ISSUE THREAD

**Issue by KejieLiu** [ant-design/ant-design#14291]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/kejieliu/pen/MZPzVo?editors=0010](https://codepen.io/kejieliu/pen/MZPzVo?editors=0010)

### Steps to reproduce
the first column's width is 400,but it is not effective

### What is expected?
the first column's width is 400px

### What is actually happening?
the first column's width is not 400px

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.6.3 |
| System | mac |
| Browser | chrome70 |

**Comment by afc163** [comment]
Too many columns to squeeze table layout, try `scroll={{ x: 'max-content' }}`: https://codepen.io/anon/pen/KbGrbq?editors=0010

**Comment by Ryuurock** [comment]
> Too many columns to squeeze table layout, try `scroll={{ x: 'max-content' }}`: https://codepen.io/anon/pen/KbGrbq?editors=0010

Why is it not documented please ?

**Comment by ggomma** [comment]
> Too many columns to squeeze table layout, try `scroll={{ x: 'max-content' }}`: https://codepen.io/anon/pen/KbGrbq?editors=0010

only this solution has worked!
Thank you.
