### ISSUE TITLE
组件的示例代码有一些不完善的地方

### ISSUE THREAD

**Issue by ReadingSteiner** [ant-design/ant-design#143]
例如有的代码 input标签没有闭合 会直接报错， 有的直接使用的是class而不是className来放置类而导致没有样式。希望可以review一下组件示例代码里这些小错误，示例代码稳定的话会友好很多 :) thanks~

**Comment by afc163** [comment]
哪里有问题，可以帮忙指出就太感谢了~~

**Comment by ReadingSteiner** [comment]
例如Button的实例代码里，我看了一下，除了最后一个，其他都用的class

**Comment by zhujun24** [comment]
Button 的实例代码，用 class 的实例都是纯粹的应用了样式而已，最后一个加载中的实例才是基于 React 的组件，所以 Button 的实例代码应该是没有问题的，还有其他问题欢迎指正 :)
