### ISSUE TITLE
Table组件有什么好方法支持多行头？

### ISSUE THREAD

**Issue by GrayChoi** [ant-design/ant-design#1430]
我阅读了文档和一部分source似乎组件原生不支持多行头。我现在的做法是componentDidMount直接操作DOM添加多行头，我想知道有没有什么更好的方法可以添加多行头呢？

**Comment by afc163** [comment]
目前不支持，接下来应该会有改进计划，我们遇到了一样的问题。

**Comment by benjycui** [comment]
`column.title` 支持 JSX，现在只能这样折腾下。

**Comment by GrayChoi** [comment]
@afc163  了解了。
@benjycui  好办法！

**Comment by aNameHere** [comment]
可以给个例子吗 @benjycui
