### ISSUE TITLE
Form get messed up with multi required/optional item in Row/Col

### ISSUE THREAD

**Issue by Raika** [ant-design/ant-design#14304]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vnoxnjwy7l)

### Steps to reproduce
Add form item inside `<Row>/<Col>` with some optional item and some required item

### What is expected?
after submitting form when showing message form shows as its structure

### What is actually happening?
form get messed up

| Environment | Info |
|---|---|
| antd | 3.12.2 |
| React | latest |
| System | Windows 10 |
| Browser | Firefox |

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51080237-cd233e80-1712-11e9-98b6-9cfd13a6b3a6.png)
Comment `text-align`, otherwise it will inherit this attribute. I updated your [demo](https://codesandbox.io/s/vnoxnjwy7l).

**Comment by Raika** [comment]
I remove it. but the problem still exist

**Comment by ztplz** [comment]
Sorry, I forgot to save it. See [demo](https://codesandbox.io/s/6lprnn0r5z).

**Comment by afc163** [comment]
@Raika You can describe what is the exact `messed up form` by screenshot to make sure we don't misunderstand you.

**Comment by Raika** [comment]
![aaa](https://user-images.githubusercontent.com/2825670/51081645-fe4b4100-1709-11e9-9cc4-3661513b1e6d.png)

**Comment by zombieJ** [comment]
<img width="471" alt="2019-01-13 12 50 31" src="https://user-images.githubusercontent.com/5378891/51081741-d7086a00-1731-11e9-8036-9de1d2c1cbf0.png">

In firefox, field with error has hight of `64.3333px` and normal one is `64px` which makes line break.

**Comment by Raika** [comment]
could this fix by something like
```css
.ant-form-item-control.has-error {
    height: 59px;
}
```

**Comment by zombieJ** [comment]
Since some user has very long error message. Fix height may cause new style issue. But for your situation you can do this.

**Comment by Raika** [comment]
now that you mention it how about long messages? 😁

**Comment by Raika** [comment]
@ztplz 
I don't think so, I apply the fix in the previous comment in the CSS. remove it and test it again.
remove `line-height` from css and check it again

**Comment by ztplz** [comment]
https://stackoverflow.com/questions/7229568/input-height-differences-in-firefox-and-chrome
