### ISSUE TITLE
use autoprefixer 9.4.5 in postcss (webpack) get a error

### ISSUE THREAD

**Issue by SolidZORO** [ant-design/ant-design#14306]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/postcss/autoprefixer/releases/tag/9.4.5](https://github.com/postcss/autoprefixer/releases/tag/9.4.5)

### Steps to reproduce
in "autoprefixer": "9.4.5" has a error.

Replace `text-decoration-skip: ink` to `text-decoration-skip-ink: auto`, because spec had been changed

----
https://github.com/postcss/autoprefixer/releases/tag/9.4.5

- Fix text-decoration-skip-ink support.

```
WARNING in ./node_modules/antd/lib/style/index.less (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/less-loader/dist/cjs.js??ref--6-3!./node_modules/antd/lib/style/index.less)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(155:3) Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed
```

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.12.2 |
| React | ^16.7.0 |
| System | OSX 10.14.2 (18C54) |
| Browser | Chrome 71 |

---
-

**Comment by abenchi** [comment]
I finished by reverting back to `"antd": "3.12.1",` so as to avoid such warnings while waiting for a fix to be released

**Comment by ztplz** [comment]
Fixed now.

**Comment by ztplz** [comment]
https://github.com/postcss/autoprefixer/issues/1179

**Comment by zombieJ** [comment]
> how can i remove this error? already update in new latest version

We will release patch version every weekend.

**Comment by justinlazaro-ubidy** [comment]
@zombieJ thanks you so much.

**Comment by hoantran-it** [comment]
I'm waiting for it too. Thanks for your effort!

**Comment by summer789** [comment]
I also encountered this problem and looked forward to repairing

**Comment by hsz** [comment]
`v3.12.3` still emits this warning.

**Comment by ztplz** [comment]
@hsz  This fixed version has not been released yet.

**Comment by ztplz** [comment]
@hsz  This fixed version has not been released yet.

**Comment by hedrovich** [comment]
Now released! just upgrade antd
Thanx a lot.
