### ISSUE TITLE
Popover Module Build Failed with Error Unrecognised input

### ISSUE THREAD

**Issue by chanzone** [ant-design/ant-design#14300]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/d78c0f270732c177a2616f73749abb0250303906/components/popover/style/index.less#L58](https://github.com/ant-design/ant-design/blob/d78c0f270732c177a2616f73749abb0250303906/components/popover/style/index.less#L58)

### Steps to reproduce
* Get latest Ant 3.12.1 and make sure your project includes Popover module
* Build and get the error

### What is expected?
Build pass

### What is actually happening?
ERROR  Failed to compile with 1 errors                               4:43:36 PM

 error  in ./node_modules/antd/lib/popover/style/index.less

Module build failed:

  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  box-shadow: 0 0 8px rgba(0, 0, 0, 0.15) \9;
                                        ^
Unrecognised input

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.2.0 |
| System | MacOS |
| Browser | Chrome |

---
The affected file is Popover's index.less file and the problematic line of code is https://github.com/ant-design/ant-design/blob/d78c0f270732c177a2616f73749abb0250303906/components/popover/style/index.less#L58 , which was just updated 6 days ago. I am not expert in Less coding, but when I remove the `/9` become **box-shadow: ~'0 0 8px @{shadow-color}';**, I can compile success.

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51080305-deb91600-1713-11e9-91d7-05c09720f33e.png)
Just tested and successfully built. Could you provide a `git repo` ?

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51080322-79195980-1714-11e9-982d-90b0498b0283.png)

**Comment by ztplz** [comment]
You need to update your `webpackconfig.js`.
For example:
![image](https://user-images.githubusercontent.com/17755202/51157464-00083680-18bb-11e9-9a5e-a251b4fc2be3.png)
Don't handle css with less-loader. 
![image](https://user-images.githubusercontent.com/17755202/51157504-26c66d00-18bb-11e9-9569-0848e3b54d2e.png)
This is a hack for `IE 9`, we cannot change it, so you need to change the webpack configuration to solve this problem.

**Comment by ztplz** [comment]
Close it for it's a webpack config problem. If you still having question here,  please ping me. Feel free to reopen it.
