### ISSUE TITLE
Wrong TypeScript definition for EmptyProps in Empty Component

### ISSUE THREAD

**Issue by chunlea** [ant-design/ant-design#14308]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
No Reproduction

### Steps to reproduce
When trying to use `<Empty />` with `<Icon />` in TypeScript, got errors 
```
Type error: Type 'Element' is not assignable to type 'string'.  TS2322
```

But in Empty component's doc, the Typings of `image` and `description` are both `string | ReactNode`. So I believe the Typings of EmptyProps are wrong.

<img width="1196" alt="screenshot 2019-01-13 at 8 42 58 pm" src="https://user-images.githubusercontent.com/1522415/51085429-df819480-1773-11e9-860e-21a496f2e429.png">

### What is expected?
Correct the typings, and can use `<Icon />` in both Empty's `image` or `description`.

### What is actually happening?
Can't use it in TypeScript.

| Environment | Info |
|---|---|
| antd | 3.12.2 |
| React | 16.7.0 |
| System | macOS Mojave |
| Browser | Chrome |

**Comment by afc163** [comment]
`React.ReactNode` includes `string`.
