### ISSUE TITLE
<Input /> with prefix a Icon don't show the Icon

### ISSUE THREAD

**Issue by yaznayka** [ant-design/ant-design#14310]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/64xjx3o20r)

### Steps to reproduce
Add property "prefix" to <Input /> component with any <Icon /> component

### What is expected?
See the added Icon into the Input

### What is actually happening?
the Icon has opacity:0 and it isn't visible

| Environment | Info |
|---|---|
| antd | 3.12.2 |
| React | 16.7.0 |
| System | Linux mint |
| Browser | Chrome 68.0.3440.106 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/fe121723217681240005b8d660da08fee507d61c#commitcomment-31866569
