### ISSUE TITLE
ESLint 提示警告

### ISSUE THREAD

**Issue by ohohco** [ant-design/ant-design#1431]
```
render () {
   const {getFieldProps} = this.props.form
}
```
这里如果没做类型检查会提示警告，这些类型可有文档。

**Comment by afc163** [comment]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prop-types.md

**Comment by ohohco** [comment]
浏览器警告  
`warning.js:44Warning: Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props. More info: https://fb.me/react-controlled-components`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1340
