### ISSUE TITLE
Change text-decoration-skip: ink; to text-decoration-skip-ink: auto;

### ISSUE THREAD

**Issue by ecreeth** [ant-design/ant-design#14313]
**Note**: The **ink** value was moved to the text-decoration-skip-**ink** property.

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by thesimpledesigners** [comment]
This is already solved  46a7a04

**Comment by lcoder** [comment]
How to upgrade with antd2.x?

**Comment by lcoder** [comment]
I created a postcss script that can handle with 2.x。[postcss-delete-text-decoration-skip](https://github.com/lcoder/postcss-delete-text-decoration-skip)
