### ISSUE TITLE
3.6.0 到 3.7.0 时 rc-table 重构了什么？？

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#14319]
没问题的: antd: '~3.6.0' 
[![Edit yjr8343o7j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yjr8343o7j)

有问题的:  antd: '~3.7.0'
[![Edit 82424327ml](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/82424327ml)

动画消失了，感觉是全部的元素重新刷了一遍。。。是不是又是每切换一次内部的标签更换了?

lock: https://github.com/ant-design/ant-motion/issues/200

**Comment by afc163** [comment]
👍
