### ISSUE TITLE
table onRow属性报错

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#14315]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
当把onRowClick替换成onRow属性，浏览器控制台就报错

### What is expected?
项目中用onRowClick，控制台会友好提示我尽量使用onRow属性，我用了onRow属性后为啥还给我报错呢

### What is actually happening?
用onRow属性不会报错

| Environment | Info |
|---|---|
| antd | 3.10.0 |
| React | react |
| System | windows |
| Browser | 谷歌，IE |

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#onRow-%E7%94%A8%E6%B3%95

**Comment by Mathround** [comment]
> https://ant.design/components/table-cn/#onRow-%E7%94%A8%E6%B3%95

谢谢，我以为跟以前写法一样的，没细看文档
