### ISSUE TITLE
[BUG] transfer "No Data" overlap when the list in animation

### ISSUE THREAD

**Issue by HsuanXyz** [ant-design/ant-design#14317]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r7o25j1z7o)

### Steps to reproduce
Fast typing
<kbd>y</kbd> > <kbd>delete</kbd> > <kbd>y</kbd> > <kbd>delete</kbd> > <kbd>y</kbd> > <kbd>delete</kbd> ...

### What is expected?
No overlap

### What is actually happening?

Overlap

![t-bug](https://user-images.githubusercontent.com/22736418/51095306-cd910780-17ee-11e9-90cf-c9faa12da8da.gif)

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | latest |
| System | macOS Mojave 10.14.1 |
| Browser | Google Chrome (64bit) 71.0.3578.98 |

**Comment by yoyo837** [comment]
@zombieJ 请Select的同学给看看中文Select在清空选项后也会出英文的`No Data`，可能是默认值，暂时只在项目里必现，弄出Reproduction后再开issue... 
![image](https://user-images.githubusercontent.com/6134547/51813246-45cbf280-22f0-11e9-9b18-8d847c3720e2.png)
