### ISSUE TITLE
Antd CSS do not apply while doing CSS module loading using css-loaders 

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#14328]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/aditya-padhi-kbl/frontend/tree/issue](https://github.com/aditya-padhi-kbl/frontend/tree/issue)

### Steps to reproduce
Please pull the source code and do yarn install.
Then please do yarn dev

The source code to look for is App.tsx
In webpack.config.js
If I comment line no. 34 and uncomment line no 33 then antd styles are loaded.

I am not able to understand why antd css doesn't load when css-loaders module is set to true

### What is expected?
Antd css should load when the css-loader's module option is set to true.

### What is actually happening?
When css-loaders module is set to true the antd css is not loading

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.4.18 |
| System | MAC |
| Browser | Chrome |

**Comment by aditya-padhi-kbl** [comment]
Hi @ztplz ,

This ticket was closed by you.  Requesting you to please help me the reason behind this.  If this is fixed by you . Then please let me know the fix .  Kind Regards.

**Comment by ztplz** [comment]
@aditya-padhi-kbl  
Please edit your `webpackconfig.js`。
![image](https://user-images.githubusercontent.com/17755202/51157186-b9fea300-18b9-11e9-8efd-132dffc905ca.png)

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51157221-d995cb80-18b9-11e9-9157-2afeb5738eee.png)
![image](https://user-images.githubusercontent.com/17755202/51157282-24afde80-18ba-11e9-97d6-0b7f1d637980.png)
You will match the css and less files. In some cases
For example:
![image](https://user-images.githubusercontent.com/17755202/51157386-a869cb00-18ba-11e9-8c21-a81fb3d05bfc.png)
Less-loader will cause problems.

**Comment by aditya-padhi-kbl** [comment]
Hi @ztplz ,

I followed the same:
The link for the repo is:-
[https://github.com/aditya-padhi-kbl/frontend/blob/issue/webpack.config.js](url)

Still the classes are not getting applied.
As of now none of the classes are loading.

**Comment by aditya-padhi-kbl** [comment]
Hi @ztplz ,

I have set .babelrc as 
`{
    "plugins": [
        ["import", {
            "libraryName": "antd","style": "css"
            }
        ]
    ]
}`

**Comment by aditya-padhi-kbl** [comment]
Hi @ztplz ,

Setting this webpack prop fixed the issue:
`           {
                test: /\.less$/,
                use: [
                    { "loader": "style-loader"},
                    { "loader": "css-loader?modules"},
                    { "loader": "less-loader"}
                ]
            },

            {
                test: /\.css$/,
                use: [
                    {"loader": "style-loader"},
                    {"loader": "css-loader"}
                ]
            },`

**Comment by ztplz** [comment]
Sorry for the delay reply. I'd strongly recommend that you initialize a project with CRA. If you customize the configuration yourself, you should handle css with `css-loader`, just like what you did.

**Comment by aditya-padhi-kbl** [comment]
Sure @ztplz .

**Comment by suncunhu** [comment]
插眼
google 搜索 antd css modules 
写两个less loader, 一个启用css modules, 另一个不起用

**Comment by lcoder** [comment]
less css modules support without eject

config-overrides.js

```javascript
const { override, fixBabelImports, addLessLoader, addWebpackModuleRule } = require('customize-cra')
const getCSSModuleLocalIdent = require('react-dev-utils/getCSSModuleLocalIdent');
const MiniCssExtractPlugin = require('mini-css-extract-plugin')
const postcssNormalize = require('postcss-normalize')
const paths = require('react-scripts/config/paths')

module.exports = override(
    fixBabelImports('import', {
        libraryName: 'antd',
        libraryDirectory: 'es',
        style: true,
    }),
    (config) => {
        const webpackEnv = config.mode
        const isEnvDevelopment = webpackEnv === 'development'
        const isEnvProduction = webpackEnv === 'production'
        const shouldUseSourceMap = process.env.GENERATE_SOURCEMAP !== 'false';

        const getStyleLoaders = (cssOptions, preProcessor) => {
            const loaders = [
                isEnvDevelopment && require.resolve('style-loader'),
                isEnvProduction && {
                    loader: MiniCssExtractPlugin.loader,
                    // css is located in `static/css`, use '../../' to locate index.html folder
                    // in production `paths.publicUrlOrPath` can be a relative path
                    options: paths.publicUrlOrPath.startsWith('.')
                        ? { publicPath: '../../' }
                        : {},
                },
                {
                    loader: require.resolve('css-loader'),
                    options: cssOptions,
                },
                {
                    // Options for PostCSS as we reference these options twice
                    // Adds vendor prefixing based on your specified browser support in
                    // package.json
                    loader: require.resolve('postcss-loader'),
                    options: {
                        // Necessary for external CSS imports to work
                        // https://github.com/facebook/create-react-app/issues/2677
                        ident: 'postcss',
                        plugins: () => [
                            require('postcss-flexbugs-fixes'),
                            require('postcss-preset-env')({
                                autoprefixer: {
                                    flexbox: 'no-2009',
                                },
                                stage: 3,
                            }),
                            // Adds PostCSS Normalize as the reset css with default options,
                            // so that it honors browserslist config in package.json
                            // which in turn let's users customize the target behavior as per their needs.
                            postcssNormalize(),
                        ],
                        sourceMap: isEnvProduction && shouldUseSourceMap,
                    },
                },
            ].filter(Boolean);
            if (preProcessor) {
                const preProcessorOptions = {
                    sourceMap: true,
                }
                if ( preProcessor === 'less-loader' ) {
                    preProcessorOptions.javascriptEnabled = true
                }
                loaders.push(
                    {
                        loader: require.resolve('resolve-url-loader'),
                        options: {
                            sourceMap: isEnvProduction && shouldUseSourceMap,
                        },
                    },
                    {
                        loader: require.resolve(preProcessor),
                        options: preProcessorOptions,
                    }
                );
            }
            return loaders;
        };

        return addWebpackModuleRule({
            test: /\.module.less$/, use: getStyleLoaders(
                {
                    importLoaders: 3,
                    sourceMap: isEnvProduction && shouldUseSourceMap,
                    modules: {
                        getLocalIdent: getCSSModuleLocalIdent,
                    },
                },
                'less-loader'
            )
        })(config)
    },
    addLessLoader({
        javascriptEnabled: true,
        // modifyVars: { '@primary-color': '#1DA57A' },
    }),
);
```

**Comment by saghar86** [comment]
dear @lcoder, can you please describes the steps you do for using css modules with ant design in web pack4?
I did the same but it did not effect and my classes dont apply to ant componnets.
