### ISSUE TITLE
how can i remove the 2px gap between input and dropdown when I clear box-shadow of select

### ISSUE THREAD

**Issue by z418577198** [ant-design/ant-design#14321]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
1、@shadow-1-down : 0 0 0 @shadow-color;

### What is expected?
no 2px gap

### What is actually happening?
2px gap

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.3 |
| System | macOS |
| Browser | chrome |

![1](https://user-images.githubusercontent.com/25921131/51099326-0343e980-180b-11e9-9624-ae0e857433f3.png)

**Comment by afc163** [comment]
It is by designed, I afraid you have override the style by your own.

**Comment by drebits** [comment]
You can pass the property *dropdownAlign*.
```
dropdownAlign={{ offset:[0,0] }}
```

This is from the [rc-select](https://www.npmjs.com/package/rc-select) package directly.

[Source.](https://github.com/react-component/select/issues/64)

**Comment by urwork** [comment]
i add dropdownAlign in tree-select , no effect ?

**Comment by asumaran** [comment]
is `dropdownAlign` actually supported? With Typescript adding `dropdownAlign` to a `<Select>` gives me an error.

```
Type '{ children: Element[]; dropdownAlign: { offset: number[]; }; defaultValue: string; dropdownMatchSelectWidth: false; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Select<string>> & Pick<{ readonly value?: string | undefined; readonly defaultValue?: string | undefined; readonly mode?: string | undefined; ... 51 more ...; readonly children?: ReactNode; } & Pick<...>, "style" | ... 50 more ... | "children"> & Partial<...> & Partial<...'.
  Property 'dropdownAlign' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Select<string>> & Pick<{ readonly value?: string | undefined; readonly defaultValue?: string | undefined; readonly mode?: string | undefined; ... 51 more ...; readonly children?: ReactNode; } & Pick<...>, "style" | ... 50 more ... | "children"> & Partial<...> & Partial<...'.
```

**Comment by dspacejs** [comment]
Overriding the `background-color` property for the menu items works:

```css
.ant-select-dropdown-menu-item {
  background-color: #fff;
}
```

**Comment by sophocles99** [comment]
You could also do this:

**Comment by sophocles99** [comment]
Another way of doing it:

```
<Select
  styles={{
    menu: (defaultStyles) => ({
      ...defaultStyles,
      marginTop: "0",
    }),
  }}
  {/* ... */}
/>
```
