### ISSUE TITLE
table 为表头设置样式

### ISSUE THREAD

**Issue by aiphatech** [ant-design/ant-design#14325]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/jiawenwu/pen/MZZPRN?editors=0110](https://codepen.io/jiawenwu/pen/MZZPRN?editors=0110)

### Steps to reproduce
找不到办法为表头设置 className 或者样式

### What is expected?
table 为表头设置样式

### What is actually happening?
找不到办法为表头设置 className 或者样式

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.4.2 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
用 `onHeaderRow` or `onHeaderCell` 来添加额外属性。

**Comment by liuxuzxx** [comment]
直接上样式就行，或者title直接写一个组件，亲自试验，绝对可用。例子如下：
{
            title: <ColumnShow content={'关系对象类型'} />,
            dataIndex: 'branchObjectTypeStr',
            render: (text, record) => <ColumnShow content={text} />,
        }, {
            title: <ColumnShow content={'关系对象号码'} />,
            dataIndex: 'branchValue',
            render: (text, record) => <ColumnShow content={text} />,
        }, {
            title: <ColumnShow content={'关系对象名称'} />,
            dataIndex: 'branchName',
            render: (text, record) => <ColumnShow content={text} />,
        }



ColumnShow是我自己写的一个组件：
class ColumnShow extends React.Component{
    constructor(props){
        super(props);
    }

    render(){
        let {content,color} = this.props;
        if(typeof color==='undefined' || color===null||color===''){
            color = '#40a9ff';
        }
        return (
            <span style={{color:color}}>{content}</span>
        );
    }
}

**Comment by cloud-chow** [comment]
@liuxuzxx  我设置背景颜色只会覆盖文字，无法覆盖到整个表格框，单单改变文字样式没有问题，我需要的是背景颜色就不行了。

**Comment by hanyuei** [comment]
> @liuxuzxx 我设置背景颜色只会覆盖文字，无法覆盖到整个表格框，单单改变文字样式没有问题，我需要的是背景颜色就不行了。

这个最好是直接通过css来做，目前看来没有api能做。
比如修改背景颜色
```scss
.custom-table-style {
  .ant-table-thead {
    > tr {
      > th {
        background: white !important;
      }
    }
  }
}
```

```js
 <Table
        columns={columns}
        className={'custom-table-style'}
         ...
/>
```

**Comment by BRUCE-JIN002** [comment]
`{
     title: "序号",
      dataIndex: "serialNo",
      width: 70,
      minWidth: 70,
      fixed: "left",
      resizable: true,
      onHeaderCell: () => ({
        style: { background: "#68ad71" },
      }),
}`
