### ISSUE TITLE
未注册的字段，通过调用getFieldValue或getFiledsValue却被自动注册成了表单元素

### ISSUE THREAD

**Issue by jssoscar** [ant-design/ant-design#14326]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/form/issues/237](https://github.com/react-component/form/issues/237)

### Steps to reproduce
简单的测试代码：https://github.com/react-component/form/issues/237

### What is expected?
简单的测试代码：https://github.com/react-component/form/issues/237

### What is actually happening?
简单的测试代码：https://github.com/react-component/form/issues/237

| Environment | Info |
|---|---|
| antd | 3.8.2 |
| React | 16.4.1 |
| System | mac |
| Browser | chrome |

**Comment by jssoscar** [comment]
![image](https://user-images.githubusercontent.com/4252175/51156168-465a9700-18b5-11e9-9539-fdfda662187d.png)
如图代码，为了测试，在didMount中 特意直接调用了一次getFieldsValue方法
通过getFieldDecorator只注册了一个name的input表单元素，按道理来说，最后获取表单数据时候得到的对象，应该是{name: ''}
然而实际得到的结果是：
![image](https://user-images.githubusercontent.com/4252175/51156179-54a8b300-18b5-11e9-993a-726dad80e4f4.png)

未注册的字段，通过调用getFieldValue或getFiledsValue却被自动注册成了表单元素。

**Comment by zombieJ** [comment]
升级一下你的 antd 版本：https://codesandbox.io/s/mm6285077p
