### ISSUE TITLE
Can I update only a single component

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design#14322]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I use antd2.x, and I found TreeSelect in this version has too many bugs, so I want to update only TreeSelect to the latest version, others remain the same, how can I do that?

### What does the proposed API look like?
I can update only a single component

**Comment by afc163** [comment]
I afraid there is no way to upgrade only one component, you have to try upgrade whole package.

**Comment by kwzm** [comment]
@afc163 I see, thanks.
