### ISSUE TITLE
Anyway to disable tab's keyboard event?

### ISSUE THREAD

**Issue by JHanLu** [ant-design/ant-design#14327]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have my own keyboard event which is using the up and down arrow to change the active item in current tab but the default event keep changing the current active tab.

### What does the proposed API look like?
A configurable api for closing the default event.

**Comment by joelrojo** [comment]
I'm having a similar issue as well. The best solution I found so far was to stop keyDown event propagation on the input element. It works well for Select and Input elements like so:

```js
<Input onKeyDown={e => e.stopPropagation() } />

<Select onInputKeyDown={e => e.stopPropagation() } />
```

The only problem I've encounter is with the ant calendar component input since there isn't a prop for binding the components input events (as there is with Select).

Would be really great to have a prop on tabs to disable keyboard events.

Hope this helps!

**Comment by JHanLu** [comment]
@joelrojo My event is attached on window so this stopPropagation thing is not works for my case. Thanks anyway.

**Comment by joelrojo** [comment]
@JHanLu I ended up just wrapping my component with a `div` and attaching it to that div using refs:

```js
componentDidMount() {
  this._ref.addEventListener("keydown", (e) => e.stopPropagation())
}

componentWillUnmount() {
  this._ref.removeEventListener("keydown", (e) => e.stopPropagation())
}

render() {
  <div ref={elem => this._ref = elem}>
    <YourComponent />
  </div>
}
```

Not sure if that will do the trick for you, but worth a shot.

**Comment by JHanLu** [comment]
I just find out a solution.

```
document.addEventListener('keydown', someEvent, true); // set useCapture true

someEvent = (event) => {
   event.stopImmediatePropagation(); // turns out this can not only stop propagation but also stop event capture
}
```

**Comment by JHanLu** [comment]
ps: `event.stopPropagation()`works too as long as useCapture is set true

**Comment by youngzhaosignifyd** [comment]
The proper way is to use the `renderTabBar` prop. To disable keyboard, set `keyboard` prop to false in renderTabBar:

```
<Tabs
  renderTabBar={(props, TabBar) => (
    <TabBar {...props} keyboard={false} />
  )}
  ...
/>
```

Ant design's Tabs is just a wrapper for rc-tabs
https://github.com/react-component/tabs#libtabbar

**Comment by joelrojo** [comment]
@youngzhaosignifyd  awesome, thanks! Much better than littering all my inputs with eventlisteners and stopPropagation :)
