### ISSUE TITLE
I hope the Grid supports 5 columns. 希望Grid 栅格系统能支持5列排版。

### ISSUE THREAD

**Issue by niices** [ant-design/ant-design#14324]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I hope the Grid supports 5 columns.
我希望Grid 栅格系统能支持  5 列排版。

5 columns is a wide range of needs.
5 列排版是一个很广泛的需求。

### What does the proposed API look like?
This feature is easy to implement by support span's prop type to String.

这个功能只需要通过让span的prop支持String类型就能实现。

Actually，This feature is aready implemented.

事实上这个功能已经实现了。

Just need to remove the error thrown when the span passed in a  String prop.

仅仅需要去掉span传入String类型的参数时抛出的错误。

**Comment by niices** [comment]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/8327775/51103687-ace0a600-181e-11e9-8677-1001a80bbf35.png">
<img width="185" alt="image" src="https://user-images.githubusercontent.com/8327775/51103704-b5d17780-181e-11e9-9287-a2500e73a9ad.png">
<img width="617" alt="image" src="https://user-images.githubusercontent.com/8327775/51103716-bff37600-181e-11e9-9f10-56a66a12dabd.png">
<img width="111" alt="image" src="https://user-images.githubusercontent.com/8327775/51103735-cd106500-181e-11e9-81ca-85d991c7b6b6.png">

**Comment by wangyazhen** [comment]
我升级了版本（**antd@3.21.4**），为啥这里还有这个错误呢
顺便还有一个问题就是，我如何搜索这个 `issues` 对应的 `antd` 版本呢
