### ISSUE TITLE
升级版本后,报内存溢出异常,且无法启动项目

### ISSUE THREAD

**Issue by UnicornXU** [ant-design/ant-design#14335]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce

**这是完整的异常报告,求解决良方**

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00000316680D0361]
Security context: 0x02495141d9f1 <JSObject>
    1: byteLength(aka byteLength) [0000023A353E1081] [buffer.js:531] [bytecode=000001465155DDE9 offset=280](this=0x00be54b825b1 <undefined>,0x00ee50e0ad49 <Very long string[2213036]>,0x02495143f369 <String[5]: utf-8>)
    2: arguments adaptor frame: 3->2
    3: fromString(aka fromString) [0000023A353FC389] [buffer.js:335] [bytecode=0000014651575889 offset=...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6C2F3AB9A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler 4810
 2: 00007FF6C2EE0C86 uv_loop_fork 80486
 3: 00007FF6C2EE1BB0 uv_loop_fork 84368
 4: 00007FF6C335E99E v8::internal::FatalProcessOutOfMemory 798
 5: 00007FF6C335E8D7 v8::internal::FatalProcessOutOfMemory 599
 6: 00007FF6C3637B54 v8::internal::Heap::RootIsImmortalImmovable 14788
 7: 00007FF6C362D794 v8::internal::Heap::CollectGarbage 7556
 8: 00007FF6C362BE68 v8::internal::Heap::CollectGarbage 1112
 9: 00007FF6C362B2D5 v8::internal::Heap::CollectAllGarbage 901
10: 00007FF6C36358B4 v8::internal::Heap::RootIsImmortalImmovable 5924
11: 00007FF6C31F603B v8::internal::Factory::AllocateRawWithImmortalMap 59
12: 00007FF6C31F8ABD v8::internal::Factory::NewRawTwoByteString 77
13: 00007FF6C35E6793 v8::internal::Smi::SmiPrint 483
14: 00007FF6C31F3403 v8::internal::CompilationJob::operator= 1155
15: 00007FF6C337AB36 v8::String::Utf8Length 22
16: 00007FF6C2EFD16B node::Buffer::New 3947
17: 00007FF6C33443AE v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64> 59870
18: 00007FF6C3345910 v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64> 65344
19: 00007FF6C33448A9 v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64> 61145
20: 00007FF6C334478B v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64> 60859
21: 00000316680D0361

### What is expected?
 期望内存溢出问题得以解决

### What is actually happening?
 实际结果内存溢出,当换其他端口时,启动到10%便卡死

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.7.0 |
| System | windows10 |
| Browser | 谷歌浏览器71.0.3578.98（正式版本） （64 位） |

**Comment by UnicornXU** [comment]
@afc163 @zombieJ

**Comment by zy410419243** [comment]
有项目地址么，看描述很难脑补出场景

**Comment by UnicornXU** [comment]
> 有项目地址么，看描述很难脑补出场景

没有,这是本地坏境报的错,且公司对代码有加密,没法外发。

**Comment by UnicornXU** [comment]
> 有项目地址么，看描述很难脑补出场景

之前试过清除内存限制，短时间可以正常启动，后来就报了现在的错误

**Comment by UnicornXU** [comment]
@sorrycc  面对这样的问题手足无措,想请大佬有时间看看

**Comment by UnicornXU** [comment]
> node 版本是 10？webpack-dev-server 有个内存泄漏

node版本是 11.3.0

**Comment by ztplz** [comment]
你webpack从3升到4？

**Comment by UnicornXU** [comment]
> 不给重现帮不了……

不好意思,我不知该如何重现这个报错,如果TeamView远程,你看可以么

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51155163-8cadf700-18b1-11e9-9019-15c6066f2af8.png)
限制node的使用老对象堆内存

**Comment by UnicornXU** [comment]
如果可以,可远程查看问题。TeamView ID: 1 131 163 567 , 密码 : 1446262068

**Comment by zy410419243** [comment]
自己作业自己做...

在公开场合放 tv 地址真的合适么

**Comment by ztplz** [comment]
这不是antd的问题啊 webpac-dev-server 有内存泄漏 你自己启动项目的时候 把它使用的堆大小限制一下就好了

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51155419-663c8b80-18b2-11e9-8f17-fda73b7e6653.png)
 这样每次start启动项目的时候  它自己会限制堆大小的

**Comment by UnicornXU** [comment]
> 限制node的使用老对象堆内存


> 自己作业自己做，路人最多给个看什么参考书的建议...
> 
> 在公开场合放 tv 地址真的合适么

 知道了  不好意思

**Comment by UnicornXU** [comment]
> ![image](https://user-images.githubusercontent.com/17755202/51155419-663c8b80-18b2-11e9-8f17-fda73b7e6653.png)
> 这样每次start启动项目的时候 它自己会限制堆大小的

好的  我试试,万分感谢

**Comment by ztplz** [comment]
多了个node 
![image](https://user-images.githubusercontent.com/17755202/51155518-b87dac80-18b2-11e9-9fad-9017591bfe69.png)

**Comment by UnicornXU** [comment]
> 多了个node
> ![image](https://user-images.githubusercontent.com/17755202/51155518-b87dac80-18b2-11e9-9fad-9017591bfe69.png)

![qq 20190115105302](https://user-images.githubusercontent.com/33044979/51155824-d566af80-18b3-11e9-86a2-6651cbdf2021.png)
我的是这样,是直接替换加限制么

**Comment by ztplz** [comment]
不是啊。。。 我那个只是示范给你看  你这里好像加不了  你webpack版本多少 你是不是看了百度的某些坑人教程。。。

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51155984-83725980-18b4-11e9-9dc8-364c9bfa8fa6.png)
你这个版本是多少

**Comment by UnicornXU** [comment]
> 不是啊。。。 我那个只是示范给你看 你这里好像加不了 你webpack版本多少 你是不是看了百度的某些坑人教程。。。

我的webpack版本是3.5.6 ,项目是根据antd-pro,改进的

**Comment by UnicornXU** [comment]
> ![image](https://user-images.githubusercontent.com/17755202/51155984-83725980-18b4-11e9-9dc8-364c9bfa8fa6.png)
> 你这个版本是多少

![qq 20190115110753](https://user-images.githubusercontent.com/33044979/51156313-dd275380-18b5-11e9-9c1d-0c2ede51700a.png)

**Comment by afc163** [comment]
https://github.com/sorrycc/roadhog/issues/197#issuecomment-371422783

**Comment by UnicornXU** [comment]
> ![image](https://user-images.githubusercontent.com/17755202/51155984-83725980-18b4-11e9-9dc8-364c9bfa8fa6.png)
> 你这个版本是多少

感谢大佬,没嫌弃菜鸟的这些问题 ,谢谢

**Comment by afc163** [comment]
https://github.com/sorrycc/roadhog/issues/703#issuecomment-418011741

**Comment by afc163** [comment]
> PS: 非 antd 问题建议不要在这里提问。

**Comment by leonkong** [comment]
我遇到这个问题了，是编译时候umi build 报错，和题主报的错一样。我把node从10.15.1升级到10.24.0就没问题了。内存是够用的，是node10.15.1本身有内存管理问题
