### ISSUE TITLE
升级npm版本后,报内存溢出错误,无法启动项目

### ISSUE THREAD

**Issue by UnicornXU** [ant-design/ant-design#14334]
这是 报错完整内容,求解决良方
<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 00000316680D0361]
Security context: 0x02495141d9f1 <JSObject>
    1: byteLength(aka byteLength) [0000023A353E1081] [buffer.js:531] [bytecode=000001465155DDE9 offset=280](this=0x00be54b825b1 <undefined>,0x00ee50e0ad49 <Very long string[2213036]>,0x02495143f369 <String[5]: utf-8>)
    2: arguments adaptor frame: 3->2
    3: fromString(aka fromString) [0000023A353FC389] [buffer.js:335] [bytecode=0000014651575889 offset=...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6C2F3AB9A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4810
 2: 00007FF6C2EE0C86 uv_loop_fork+80486
 3: 00007FF6C2EE1BB0 uv_loop_fork+84368
 4: 00007FF6C335E99E v8::internal::FatalProcessOutOfMemory+798
 5: 00007FF6C335E8D7 v8::internal::FatalProcessOutOfMemory+599
 6: 00007FF6C3637B54 v8::internal::Heap::RootIsImmortalImmovable+14788
 7: 00007FF6C362D794 v8::internal::Heap::CollectGarbage+7556
 8: 00007FF6C362BE68 v8::internal::Heap::CollectGarbage+1112
 9: 00007FF6C362B2D5 v8::internal::Heap::CollectAllGarbage+901
10: 00007FF6C36358B4 v8::internal::Heap::RootIsImmortalImmovable+5924
11: 00007FF6C31F603B v8::internal::Factory::AllocateRawWithImmortalMap+59
12: 00007FF6C31F8ABD v8::internal::Factory::NewRawTwoByteString+77
13: 00007FF6C35E6793 v8::internal::Smi::SmiPrint+483
14: 00007FF6C31F3403 v8::internal::CompilationJob::operator=+1155
15: 00007FF6C337AB36 v8::String::Utf8Length+22
16: 00007FF6C2EFD16B node::Buffer::New+3947
17: 00007FF6C33443AE v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+59870
18: 00007FF6C3345910 v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+65344
19: 00007FF6C33448A9 v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+61145
20: 00007FF6C334478B v8::internal::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>::ZoneVector<v8::internal::compiler::MoveOperands * __ptr64>+60859
21: 00000316680D0361

**Comment by ammirator-administrator** [comment]
What thats crazy I have same issue
Why that bot just closes them
