### ISSUE TITLE
Dynamic defaultValue property for Input stoped working

### ISSUE THREAD

**Issue by shayshu11** [ant-design/ant-design#14330]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jr5lqj939)

### Steps to reproduce
Type anything in the first Input

### What is expected?
All three lower Inputs: 2xInput and Input.Search should show the value typed in the first Input

### What is actually happening?
Only the second one with value property shows the value

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.7 |
| System | macOS Mojave |
| Browser | Chrome 71 |

---
3.12.0 seems to be the turning-point, 3.11.6 worked for me.
defaultValue for Input.Search stopped working when updated from 3.9.2 to 3.12.1

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically.

**Comment by llh1187** [comment]
add 'key' property.
