### ISSUE TITLE
filterTreeNode not work

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design#14339]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/kwzm/pen/NeoMvx?editors=0010](https://codepen.io/kwzm/pen/NeoMvx?editors=0010)

### Steps to reproduce
I don't want to filter node when I search, I want to do that by myself with back end api. 
so I do as follow:
1. I set filterTreeNode to false
2. I search some words in input
3. But still pop the menu with text 'No Data' like this:

![default](https://user-images.githubusercontent.com/16114101/51159366-d56eab80-18c3-11e9-85dd-80feace73a47.PNG)

### What is expected?
When I set filterTreeNode  to false, I search any words in input the menu don't pop or pop the default menu rather than 'No Data'

### What is actually happening?
When I set filterTreeNode  to false, I search any words in input the menu pop render 'No Data'

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.x |
| System | win7 64bit |
| Browser | chrome71.0.3578.98 |

---
I want search by myself with back end api, rather than by TreeSelect itself, so I don't want any component self behaviors.
So I read the api dom, and found filterTreeNode, but it seems not work.

**Comment by AntiMoron** [comment]
2年了 这咋还没修？
