### ISSUE TITLE
能否为tabs控件添加右键功能

### ISSUE THREAD

**Issue by maifine** [ant-design/ant-design#14338]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
想做类似代码编辑器那种效果，右键显示“关闭当前”，“关闭全部”等功能

### What does the proposed API look like?
目前配合Dropdown控件没有效果

**Comment by xiaoyierle** [comment]
<Dropdown overlay={this.renderTabs(pane)} trigger={['contextMenu']}>
</Dropdown>

**Comment by zombieJ** [comment]
https://codesandbox.io/s/3rv1wmy515

**Comment by zmayor** [comment]
@zombieJ Clicking `MenuItem` of `Dropdown`  will lead to the change event of `Tabs`. How can I prevent it?

**Comment by zombieJ** [comment]
You can add `stopPropagation` on Menu
