### ISSUE TITLE
use Input in Cascader costume trigger ,the input value can not be deleted

### ISSUE THREAD

**Issue by walk-liuyan** [ant-design/ant-design#14342]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4jyklw99p)

### Steps to reproduce
```
 <Cascader size="large" options={options} onChange={this.onChange}>
      <Input size="large" />
 </Cascader>
```

### What is expected?
The value of the input box can be changed ，i hope the value can be deleted

### What is actually happening?
The value of the input box can be changed , and value can not be deleted

| Environment | Info |
|---|---|
| antd | 2.12.6 |
| React | 15.4.2 |
| System | mac os 10.13.4  |
| Browser | chrome 71.0.3578.98 |

---
i need  Cascader[showSearch]，so i  Use Cascader costume trigger to implement this feature。but i find the input value can not be deleted

**Comment by walk-liuyan** [comment]
![image](https://user-images.githubusercontent.com/24427505/51165654-ef1bed00-18db-11e9-8146-b47d8023d305.png)
the source code is setting the input value can not be deleted

i want to implement Cascader[showSearch]，Can you give me some ideas? THX！

**Comment by afc163** [comment]
https://codesandbox.io/s/934n8956zy

```jsx
        <Cascader size="large" options={options} onChange={this.onChange}>
          <Input size="large" onKeyDown={e => e.stopPropagation()} />
        </Cascader>
```
