### ISSUE TITLE
缺少富文本编辑器

### ISSUE THREAD

**Issue by huyanatown** [ant-design/ant-design#14343]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
类似Ueditor这样的富文本框编辑器的组件。想问下你们有在考虑开发吗？

### What does the proposed API look like?
现在市面上 就  mark text和 Ueditor 这两种类型的编辑器。能不能开发一款结合两者特性的富文本框编辑器组件，或者可以用tab切换的组件。

**Comment by zy410419243** [comment]
你可能需要跟进 [这个](https://github.com/ant-design/ant-design/issues/1083) ~~以及催更~~

**Comment by afc163** [comment]
Duplicate of #1083

**Comment by afc163** [comment]
暂无计划。
