### ISSUE TITLE
Antd Tree组件拖动到另一节点时，目标节点自动展开，未被expandedKeys props控制

### ISSUE THREAD

**Issue by lsunflower** [ant-design/ant-design#14359]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/komzovjw4v)

### Steps to reproduce
将节点拖动到一个有子节点的节点上，目标节点会自动展开

### What is expected?
希望由我来控制展开

### What is actually happening?
自动展开

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.4.2 |
| System | windows10 |
| Browser | Google Chrome 71.0.3578.98 |

---
正常情况下，拖动时，拖动位置放到节点下方成一条横线时，应该是排序，而官方是自动展开，并放入节点的子集

**Comment by lsunflower** [comment]
@yutingzhao1991 麻烦处理一下噢

**Comment by chengwb53** [comment]
怎么关闭拖动排序时，自动展开节点的功能？
