### ISSUE TITLE
MonthPicker: Impossible to select year

### ISSUE THREAD

**Issue by ilanus** [ant-design/ant-design#14355]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

![Reproduce](http://g.recordit.co/xDEh4teSig.gif)

### Steps to reproduce
try to select any year in MonthPicker

### What is expected?
year should change to selected one

### What is actually happening?
the year doesn't change

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.6 |
| System | macOS Mojave |
| Browser | 71.0.3578.98 (Official Build) (64-bit) |

**Comment by Yangzhedi** [comment]
same as [#14288](https://github.com/ant-design/ant-design/issues/14355)

**Comment by zombieJ** [comment]
Duplicate of #14371

**Comment by 2678041235** [comment]
> Duplicate of ·

> Duplicate of #14371

这个问题解决了么？为什么我更新了rc-calendar还是存在这个问题呢？

**Comment by zombieJ** [comment]
@2678041235 删除 node_modules 重装，如果有 lock 文件也需要删一下。

**Comment by 2678041235** [comment]
> @2678041235 删除 node_modules 重装，如果有 lock 文件也需要删一下。

试过了还是不行，我的react版本是15.4.1，antd是3.11.6。我看有些人说是antd需要降到3.1.0才可以，或者react升到16版本？

**Comment by zombieJ** [comment]
> > @2678041235 删除 node_modules 重装，如果有 lock 文件也需要删一下。
> 
> 试过了还是不行，我的react版本是15.4.1，antd是3.11.6。我看有些人说是antd需要降到3.1.0才可以，或者react升到16版本？

升级一下 antd 版本，这个依赖的 rc-calendar 升级到了 9.10.x，antd 里也对应升过了。

**Comment by junhui75165** [comment]
@zombieJ  今天遇到同样的问题，查了下rc-calendar版本是9.15，但同样出现这个问题了
![image](https://user-images.githubusercontent.com/3411959/59746807-3868d200-92aa-11e9-8532-bdec3d7502bd.png)

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E6%8C%87%E5%AE%9A%E4%BA%86-DatePicker/RangePicker-%E7%9A%84-mode-%E5%B1%9E%E6%80%A7%E5%90%8E%EF%BC%8C%E7%82%B9%E5%87%BB%E5%90%8E%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E5%B9%B4%E4%BB%BD/%E6%9C%88%E4%BB%BD%EF%BC%9F

**Comment by junhui75165** [comment]
@afc163 重现了下，目测大概率是react版本的问题，我使用的是15.3.0的react版本
[重现链接](https://codesandbox.io/s/fast-bush-ghbwf)
