### ISSUE TITLE
Antd Tree组件拖动到另一节点时，目标节点自动展开，未被expandedKeys props控制

### ISSUE THREAD

**Issue by lsunflower** [ant-design/ant-design#14350]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree组件拖动到节点时，节点自动展开，我不希望自动展开，而是通过我更新expandedKeys state来手动控制展开。

### What does the proposed API look like?
Tree组件拖动到节点时，节点不自动展开，而是通过我更新expandedKeys state来手动控制展开。

**Comment by lsunflower** [comment]
@ant-design-bot https://codesandbox.io/s/komzovjw4v

**Comment by zombieJ** [comment]
duplicate of #14359
