### ISSUE TITLE
Tree component is too restrictive

### ISSUE THREAD

**Issue by Remimstr** [ant-design/ant-design#14358]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like to present our data to the user in a tree and allow them to easily select and filter pieces of it. As much as I love the look of antd's tree component, I simply cannot do what I want with it.

More specifically, I want to add a customized checkbox that can cycle between different selection states, ex. "unchecked -> A -> B -> C -> unchecked" instead of just "unchecked -> checked -> unchecked". I would also like to add a clickable element after node on the tree (for my purposes, to apply a specific filter) but I cannot do that either.

### What does the proposed API look like?
I think you should add the option to include ReactNode(s) as a prefix and postfix for each TreeNode to support this functionality. The new api would be called like so:
    
    <TreeNode
      title="Parent 1"
      prefix={<MyCustomComponent />}
      postfix={<MyOtherCustomComponent />}
    >

I've illustrated how this would look here: https://ibb.co/5chh5hQ

The Icon in the diagram next to the "Parent 1" text would be clickable and in my specific use case would pop up a menu for selecting filters.

**Comment by twisger** [comment]
Title can be a react element.
```
<TreeNode
  title={
    <div>
      <MyCustomComponent />
      <div>Parent 1</div>
      <MyOtherCustomComponent />
    </div>
  }
/>

**Comment by Remimstr** [comment]
Thank you for replying to my issue so quickly!

I'm sorry I should have read the documentation more carefully, you're absolutely right.
Adding my component(s) to the title in addition to setting the selectable prop to false has made my use case possible :)

**Comment by twisger** [comment]
@gregoryforel 
It is just a example to show that title can be element.  If you want to add prefix and suffix in tree node, use `span` wrap them.
```jsx
<TreeNode
  title={
    <div>
      <span>prefix</span>
      <span>Parent 1</span>
      <span>suffix</span>
    </div>
  }
/>

**Comment by gregoryforel** [comment]
@twisger OK. So, that's what I thought, you can use TreeNode as a React component, but it only works correctly if it fits in one line. That's a pity!
