### ISSUE TITLE
Select shake top when scroll down to select item

### ISSUE THREAD

**Issue by ycjcl868** [ant-design/ant-design#14352]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

https://ant.design/components/select-cn/#components-select-demo-size

![kapture 2019-01-15 at 18 54 16](https://user-images.githubusercontent.com/13595509/51176121-1c29c900-18f7-11e9-9064-b02305607cae.gif)

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/51741535-35d6c780-20d2-11e9-97d3-664194e0082e.gif)

**Comment by afc163** [comment]
除此之外还有另一个 bug，鼠标移动到面板上时，滚动条会向上跳动4、5像素。

![1](https://user-images.githubusercontent.com/507615/51963040-232b0c80-249d-11e9-989b-0e4635678c45.gif)

**Comment by zombieJ** [comment]
> 除此之外还有另一个 bug，鼠标移动到面板上时，滚动条会向上跳动4、5像素。

看了一下，是特意的逻辑，鼠标悬浮的 Option 如果显示不全就显示全：
![kapture 2019-02-01 at 14 56 39](https://user-images.githubusercontent.com/5378891/52107565-d4fb4200-2631-11e9-8fe7-a1699f3901b5.gif)
