### ISSUE TITLE
在表格size为middle的情况下，表格分页组件显示有问题

### ISSUE THREAD

**Issue by dunmengjun** [ant-design/ant-design#1436]
**问题描述**
在表格size为middle的情况下，pagination属性存在且showSizeChanger子项为true，，分页组件的changeSize select部分显示在中轴线以下，导致分页组件整体不整齐

**发生环境**
ant-init ant-build webpack droa 就是按照教程来的
- antd 版本 ：0.12.x
- 操作系统及版本：windows 10  2016/4/16
- 浏览器及版本：所有浏览器下都存在这个问题  2016/4/16
- 在线演示地址：无

**重现步骤**

1. 设置表格size为middle
2. 为Table添加pagination属性,且showSizeChanger子项设置为true

**线上重现演示**

无

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/1396

**Comment by afc163** [comment]
在 https://github.com/ant-design/ant-design/commits/develop-1.0.0 分支上。

**Comment by afc163** [comment]
0.12 上可以用 `<Table pagination={{ size: 'small' }}>` 临时修复下。

**Comment by jasonperk** [comment]
其实像实现的效果是 表格是middle的情况下，分页也middle（目前应该是small，无法自定义）

**Comment by jasonperk** [comment]
![image](https://cloud.githubusercontent.com/assets/689617/14669285/c24c0240-071a-11e6-89e2-c28f37b0fce4.png)图1

![image](https://cloud.githubusercontent.com/assets/689617/14669343/f5d6177c-071a-11e6-9f97-98f9bf141600.png)图2


图1表格为middle，图2表格为lagre

想图1使用图2的分页样式

**Comment by afc163** [comment]
对，这是目前的设计规范。

如果要自行配合，可以单独使用 Pagination 组件。关掉 Table 自带的分页。
