### ISSUE TITLE
数字输入框默认写死宽度了

### ISSUE THREAD

**Issue by Huatingzi** [ant-design/ant-design#14370]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
检查原生看‘.ant-input-number’类

### What is expected?
width：100%

### What is actually happening?
width：90px

| Environment | Info |
|---|---|
| antd | 3.11.2 |
| React | 16.7.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
It is by designed in fisrt place, we may not change it for compatibility, you can set it by your own.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10906

**Comment by fishCrush** [comment]
> It is by designed in fisrt place, we may not change it for compatibility, you can set it by your own.
how to set its width by my own,  i have tried to use "width"，but it does not work.

**Comment by afc163** [comment]
```
<InputNumber style={{ width: '100%' }} />
```
