### ISSUE TITLE
Restrict creating issues in github only in English

### ISSUE THREAD

**Issue by dospolov** [ant-design/ant-design#14382]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hello Ant.design team,

your product is no more local JS library, now it's a worldwide ecosystem used by international companies.
If you want to be even more frequently used and get more open-source community contribution - you should provide transparent roadmap and list of known issues with current status.

### What does the proposed API look like?
Thus I suggest to restrict creating issues in github only in English.

**Comment by dospolov** [comment]
@lintao-lintao like it or not - english is the language of international communication and more importantly open-source community language.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4897

**Comment by dospolov** [comment]
@afc163 maybe you should create a poll? To identify what antd users really want?

**Comment by zombieJ** [comment]
hi @dospolov,
We recommends user to use English for other non-Chinese user to view issue. But not force to do so since some users can not speak English well.

**Comment by dospolov** [comment]
@zombieJ 
I'm russian native speaker, nevertheless, I do not create tasks in Russian

**Comment by ztplz** [comment]
Just say my opinions. 
`roadmap`  @afc163  Maybe we should provide the roadmap about `Antd` as others did. I think roadmap can let others know the direction and progress of the current project.
`restrict English`   We know English is an international language and always recommend using English to open an issue. But there are many Chinese native speaker can't speak English.

**Comment by afc163** [comment]
Sorry, if we do that, some of our users will yell at us.

**Comment by dospolov** [comment]
I'm using ant.design 5 years straight, from version 1.* and I love it. Currently, it is used on 12 of my projects: personal and client. 
Forced to admit the issue is not resolved and it becomes even worse. From my observation now the majority of tickets with vivid discussions are in Chinese. As a user, I feel myself abandoned and probably will have to switch to another UI kit in long-term perspective.
