### ISSUE TITLE
typescript 使用input组件报错 

### ISSUE THREAD

**Issue by songyanbo** [ant-design/ant-design#14394]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/14393](https://github.com/ant-design/ant-design/issues/14393)

### Steps to reproduce
typescript 中使用input组件报错，有可能是antd/lib/input/Input.d.ts 定义文件没有更新，请修正，谢谢。说明：我是使用的antd版本为"antd": "3.9.3"，其他版本应该发现也会有同样的问题。

### What is expected?
无

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 3.9.3 |
| React | 16.0.0 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
升级到最新的 antd 版本。
