### ISSUE TITLE
table表头列是否支持拖动

### ISSUE THREAD

**Issue by iskyshop** [ant-design/ant-design#1439]
table表头列没有看到支持拖动的属性，是不是目前不支持，这个功能是其他各类控件都具备的呢

**Comment by afc163** [comment]
暂时不支持。

**Comment by iskyshop** [comment]
这个是否有开发计划？

**Comment by benjycui** [comment]
目前无计划支持列拖动，对于过宽的表格，建议使用替代方案。

http://ant.design/components/table/#demo-paging-columns

http://ant.design/docs/pattern/table#某一项内容过长
