### ISSUE TITLE
Build failure (version 3.12.3): Generic type 'MouseEvent<T>' requires between 0 and 1 type arguments

### ISSUE THREAD

**Issue by vsamotskiy** [ant-design/ant-design#14401]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://prntscr.com/m8dfii](http://prntscr.com/m8dfii)

### Steps to reproduce
Install latest version of library. 
Use typescript in project
Build

### What is expected?
Build pass

### What is actually happening?
Build error http://prntscr.com/m8dfii

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.6.3 |
| System | Windows 10 PRO x64 |
| Browser | Any |

**Comment by yesmeck** [comment]
What's the version of @types/react are you using?

**Comment by vsamotskiy** [comment]
@types/react@16.7.17

**Comment by vsamotskiy** [comment]
Solved by update @types/react

**Comment by vsamotskiy** [comment]
Solved by update @types/react
