### ISSUE TITLE
RangePicker在IE 10中点击会报错

### ISSUE THREAD

**Issue by tonypig93** [ant-design/ant-design#14405]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
点击RangePicker

### What is expected?
不会报错

### What is actually happening?
控制台报错：对象不支持“getDerivedStateFromProps”属性或方法

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.6.3 |
| System | windows 10 |
| Browser | IE 10 |

---
没办法在IE 10中打开codesandbox

**Comment by afc163** [comment]
https://github.com/react-component/calendar/commit/ee24ca5b09d7fab95dc7173ff6973e2f209852ad

**Comment by tonypig93** [comment]
> 给个 github 地址重现看一下，我这边好的：
> ![kapture 2019-01-18 at 10 26 39](https://user-images.githubusercontent.com/5378891/51361646-9468d800-1b0b-11e9-92ba-446ec58a45f8.gif)

我用win10 的IE，开启IE10的文档模式，打开antd官网点击datepick就会报错
![2da9bea7-d3e1-43fa-96ac-3d04bc20fb2e](https://user-images.githubusercontent.com/27796932/51362395-620caa00-1b0e-11e9-8cae-fb9f0ca2664b.png)

**Comment by zombieJ** [comment]
> > 给个 github 地址重现看一下，我这边好的：
> > ![kapture 2019-01-18 at 10 26 39](https://user-images.githubusercontent.com/5378891/51361646-9468d800-1b0b-11e9-92ba-446ec58a45f8.gif)
> 
> 我用win10 的IE，开启IE10的文档模式，打开antd官网点击datepick就会报错
> ![2da9bea7-d3e1-43fa-96ac-3d04bc20fb2e](https://user-images.githubusercontent.com/27796932/51362395-620caa00-1b0e-11e9-8cae-fb9f0ca2664b.png)

官方文档没有对旧版 IE 做 polyfill，自己项目开发的时候开启 polyfill 就行了。如果用的是 umi，可以直接配置目标游览器版本：https://umijs.org/zh/config/#targets

**Comment by tonypig93** [comment]
> > 我用win10 的IE，开启IE10的文档模式，打开antd官网点击datepick就会报错
> 
> 官方文档没有对旧版 IE 做 polyfill，自己项目开发的时候开启 polyfill 就行了。如果用的是 umi，可以直接配置目标游览器版本：https://umijs.org/zh/config/#targets

我在项目已经引用了`babel-polyfill`，然后用IE 10的文档模式打开依然会报上面的错。不太清楚还需要开启什么polyfill。

**Comment by zombieJ** [comment]
这个有开过吗？https://babeljs.io/docs/en/babel-preset-env#targets

**Comment by tonypig93** [comment]
> 这个有开过吗？https://babeljs.io/docs/en/babel-preset-env#targets

开过了
```
"browserslist": [
    "defaults",
    "ie 9-11"
  ]
```

**Comment by Tulipxu** [comment]
我的在ie9下也是报这个错，开启了polyfill，还是不行，请问还需要配置什么东西吗？

**Comment by zombieJ** [comment]
我看看我能不能在 rc 里把 polyfill 做掉，晚些时候会发个 rc-calendar 的 patch。

**Comment by zombieJ** [comment]
@tonypig93 @Tulipxu ，发了 `rc-calendar@9.10.7`。把 node_modules 删了重装一下，试试看。

**Comment by tonypig93** [comment]
@zombieJ 重装`node_modules`后`rc-calendar`还是`9.10.5`，手动把`9.10.7`拷贝到`node_modules`后，控制台报错
![image](https://user-images.githubusercontent.com/27796932/51379550-a74ecd00-1b4a-11e9-896a-573ed9d98add.png)
![image](https://user-images.githubusercontent.com/27796932/51379560-ad44ae00-1b4a-11e9-8b55-66caa445d892.png)

**Comment by afc163** [comment]
删除 package-lock.json 或者 yarn.lock 后重装。

**Comment by tonypig93** [comment]
删了lock文件后重装了，版本对了但是还是会报上面的错误

**Comment by tonypig93** [comment]
@zombieJ @afc163 我用`create-react-app`重启开了一个项目来测试，只引用了`RangePicker`，然后在IE 10下点击就会报错，不好意思之前以为是`DatePicker`。

**Comment by afc163** [comment]
可以提供下重现仓库。

**Comment by tonypig93** [comment]
> 可以提供下重现仓库。

[https://github.com/tonypig93/antd-demo](https://github.com/tonypig93/antd-demo)

**Comment by zombieJ** [comment]
> @zombieJ @afc163 我用`create-react-app`重启开了一个项目来测试，只引用了`RangePicker`，然后在IE 10下点击就会报错，不好意思之前以为是`DatePicker`。

DatePicker 的确是有问题的，看来 RangePicker 也有。我发了 `rc-calendar@9.10.8` 你再试试。

**Comment by tonypig93** [comment]
> > @zombieJ @afc163 我用`create-react-app`重启开了一个项目来测试，只引用了`RangePicker`，然后在IE 10下点击就会报错，不好意思之前以为是`DatePicker`。
> 
> DatePicker 的确是有问题的，看来 RangePicker 也有。我发了 `rc-calendar@9.10.8` 你再试试。

可以了，谢谢
