### ISSUE TITLE
Grid inside List should support flex

### ISSUE THREAD

**Issue by chunlea** [ant-design/ant-design#14407]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jsfiddle.net/chunlea/zxsb1kpd/](https://jsfiddle.net/chunlea/zxsb1kpd/)

### Steps to reproduce
Created a `List` with `Card`, enable `grid`, and the layout is mass.

<img width="1191" alt="screenshot 2019-01-17 at 9 56 57 pm" src="https://user-images.githubusercontent.com/1522415/51323445-2ee10100-1aa3-11e9-9670-5fe185d2bede.png">

### What is expected?
Like `Row` Component, with `flex`, the layout should look like

<img width="1192" alt="screenshot 2019-01-17 at 10 00 20 pm" src="https://user-images.githubusercontent.com/1522415/51323517-6354bd00-1aa3-11e9-97ae-7b4856c75a01.png">

### What is actually happening?
I looked at the source code and found that https://github.com/ant-design/ant-design/blob/master/components/list/index.tsx#L232 we only pass `grid.gutter` to `Row` and use Context to pass other options to `List.Item` col

Maybe we should support all `RowProps` fields here https://github.com/ant-design/ant-design/blob/master/components/grid/row.tsx#L29-L35 in `grid` of `List` Component? 

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.7.0 |
| System | macOS |
| Browser | Chrome 71 |

**Comment by davidpanzarella** [comment]
Agreed, and just to add, `Card` itself should be `flex` as well, or at least have an option to be.

**Comment by atav32** [comment]
Would love to see this. Just have to consider that a lot of Chinese users are still using IE9, https://github.com/ant-design/ant-design/issues/11480

**Comment by leehen** [comment]
Agree, we are having the same issue here. Any idea how to temporary fix this?

**Comment by asader** [comment]
Here's simple workaround
`export const FlexList = ({ dataSource, renderItem, gutter}) => {
	return (
		<Row gutter={gutter} type='flex'>
			{ dataSource.map(entity => renderItem(entity)) }
		</Row>
	);
};`

**Comment by harunurhan** [comment]
@asader  this doesn't give your all features that come out of the box with `List`

**Comment by harunurhan** [comment]
As a workaround, you can wrap all items (`children`), with a `<div className="ant-row-flex"`

```jsx
      <List
        grid={...}
      >
        <div className="ant-row-flex">
          {items.map(...)}
        </div>
      </List>
```
