### ISSUE TITLE
table的title是Input输入框时，点击输入框会触发排序

### ISSUE THREAD

**Issue by jeessy2** [ant-design/ant-design#14411]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l9r1p7plqm)

### Steps to reproduce
table的title是Input输入框时，点击输入框会触发排序

### What is expected?
不排序

### What is actually happening?
排序

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.7.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
You need `stopPropagation`: https://codesandbox.io/s/l9r1p7plqm
