### ISSUE TITLE
List Component pagination default page turning behavior miss the mark

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#14417]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6zz49nrlvw)

### Steps to reproduce
列表组件分页的默认翻页行为不符合预期

1. Click the page turning button

---

1. 点击翻页按钮

### What is expected?
1. In uncontrolled state, the number of list display changes

---

1. 非受控状态下，列表显示数量跟随改变

### What is actually happening?
1. Have no reaction

---

1. 没反应

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.3 |
| System | macOS 10.14.2 (18C54) |
| Browser | chrome 71.0.3578.98 |

---
https://codesandbox.io/s/03vxpylqjn

参考 table 非受控下 pageSize 的内部逻辑

**Comment by afc163** [comment]
https://codesandbox.io/s/6zz49nrlvw and https://codesandbox.io/s/03vxpylqjn are both broken link.
