### ISSUE TITLE
Table 每次页面有 方法调用 this.setState 设置值， 都会重新render列， 导致异常的卡

### ISSUE THREAD

**Issue by hpze2000** [ant-design/ant-design#1441]
```
const columns = [ {
        title: '设置',
        dataIndex: 'labe',
        render: this.renderSelect
      }];

```

我表格中列中放了一些表单控件，这样 比如每次打开或关闭modal，会使用 this.setState({modalVisible: false}); 
这样就会, 全部列重新render， 如果行数多一点就会会异常的卡， 这是为啥， 我操作有什么问题嘛 ？

**Comment by hpze2000** [comment]
@afc163
demo  在这里 [http://codepen.io/johnsonz/pen/ZWoqWE](http://codepen.io/johnsonz/pen/ZWoqWE)

**Comment by afc163** [comment]
给的 demo 没有打印信息。

**Comment by afc163** [comment]
React 的状态机原理就是这样，每次 setState 子组件就会渲染。上层组件可以使用 shouldComponentUpdate 进行性能优化。可参考：https://github.com/ant-design/ant-design/pull/1449/files#diff-fec8ea1ab365a7797fe2a563b4ea1be2R64

**Comment by yesuanzao** [comment]
@afc163 老实讲我没看到这个例子哪里做了优化，因为任何操作都会导致整个Table重新渲染
