### ISSUE TITLE
Change the style of GitHub Star button at home page of this project

### ISSUE THREAD

**Issue by lxohi** [ant-design/ant-design#14418]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At the home page of this project, [here](https://ant.design/) is a GitHub Star button at the top screen.

This button looks pretty different from the other elements on this page and it does not looks like the same style as antd.

Would you please change another button that share the same style of Ant Design?

### What does the proposed API look like?
No API changes.

**Comment by lxohi** [comment]
![image](https://user-images.githubusercontent.com/16010388/51369600-259d7600-1b2f-11e9-8564-90a1a58dc14a.png)
Here is a screenshot of the button was mentioned above.

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51370425-07854500-1b32-11e9-9bdc-b8bf1d517cf5.png)
Do you mean this button ? It's design is what we want.

**Comment by lxohi** [comment]
@ztplz 
Nope, I mean this one:
![image](https://user-images.githubusercontent.com/16010388/51373955-79fb2280-1b3c-11e9-8499-63eba2e809c2.png)

**Comment by lxohi** [comment]
hmmm,
I posts this issue is because antd has such refined styles.

Even the github badges in README.md:
![image](https://user-images.githubusercontent.com/16010388/51374499-34d7f000-1b3e-11e9-88d4-bd864a7e0447.png)
They are all in a flat style (not like the normal ones in the other project have some depth in it. e.g. ![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg))

But the *Star* button looks have some depth to me.
I have asked myself why it looks not flat to me before posting this issue. But I do not came up with a clue...
