### ISSUE TITLE
Uploader onChange接收到file属性不是UploadFile // Uploader onChange received file attribute is not UploadFile

### ISSUE THREAD

**Issue by gavinxgu** [ant-design/ant-design#14420]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/3.12.3/components/upload/Upload.tsx](https://github.com/ant-design/ant-design/blob/3.12.3/components/upload/Upload.tsx)

### Steps to reproduce
当beforeUpload返回false的时候onChange实际传入的file是RcFile类型，而onChange方法interface实际要求传入的是UploadFile，所以在使用的时候类型推断错误
```javascript
beforeUpload = (file: RcFile, fileList: RcFile[]) => {
    if (!this.props.beforeUpload) {
      return true;
    }
    const result = this.props.beforeUpload(file, fileList);
    if (result === false) {
      this.onChange({
        file,
        fileList: uniqBy(
          this.state.fileList.concat(fileList.map(fileToObject)),
          (item: UploadFile) => item.uid,
        ),
      });
      return false;
    } else if (result && (result as PromiseLike<any>).then) {
      return result;
    }
    return true;
  };
```

### What is expected?
统一返回UploadFile类型，或者在UploadChangeParam interface改为
```javascript
export interface UploadChangeParam {
  file: UploadFile | RcFile;
  fileList: Array<UploadFile | RcFile>;
  ...
}
```
或者beforeUpload传入onChange的时候使用fileToObject转换

### What is actually happening?
实际对象和类型推断不一致

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.7.0 |
| System | Mac OS 10.14.2 |
| Browser | Chrome 71.0.33578.98 |

**Comment by ycjcl868** [comment]
In my opinion, file should change into FileObject when `beforeUpload` return false.

Is there a reason for using origin `File` object?  @afc163 

![image](https://user-images.githubusercontent.com/13595509/56857295-4d0da580-699e-11e9-9fdf-ddcf0c1d82b9.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10293
https://github.com/ant-design/ant-design/pull/10059/files

**Comment by ycjcl868** [comment]
@gavinxgu There's [some reason](https://github.com/ant-design/ant-design/issues/10293) to use `File` when `beforeUpload` return false. 

One solution, therefore, is to use `RcFile` or `UploadFile`(default) through generic types, like this.


![image](https://user-images.githubusercontent.com/13595509/56859529-e1880000-69be-11e9-907b-eacec60d3fad.png)


![image](https://user-images.githubusercontent.com/13595509/56859530-e64cb400-69be-11e9-9b39-1302d51c8f99.png)
