### ISSUE TITLE
DatePicker的功能需求

### ISSUE THREAD

**Issue by jszjgqq** [ant-design/ant-design#14425]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在遇到个需求，需要时间自定义选择多个，比如可以随机选择多天，但日期并不是连贯的，找了下API文档，没找到相关资料。

看了下API中的defaultPickerValue默认要moment类型，不支持Array中放多个moment。

### What does the proposed API look like?
希望能够支持多天可选的功能。

**Comment by afc163** [comment]
Duplicate of #4447

**Comment by jszjgqq** [comment]
https://codesandbox.io/s/92xkz86y0r

基于 DataPicker自己实现了下，代码没优化，只是个Demo，有需要的可参考。
