### ISSUE TITLE
官网 create-react-app 中使用 antd，提供的按需加载方案已经不适用于 react-app-rewired2.x

### ISSUE THREAD

**Issue by idujiawei** [ant-design/ant-design#14423]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
none

### What is expected?
提供兼容方案

### What is actually happening?
官网：create-react-app 中使用 antd，提供的按需加载方案已经不适用于 react-app-rewired2.x

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.7.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed by https://github.com/ant-design/ant-design/pull/14385 #14386 #14413
