### ISSUE TITLE
Tooltip isn't correct work in mobile phone.

### ISSUE THREAD

**Issue by arg0navt** [ant-design/ant-design#14424]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
When button with event onClick has wrapper Tooltip.

### What is expected?
Need for event hover doesn't stop event onClick .

### What is actually happening?
Event hover doesn't stop event onClick

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.5.1 |
| System | ios, android |
| Browser | chrome, safari |

---
When I touch button who has wrapper Tooltip and has event onClick event hover stopped event onClick. Need use double touch for button.

**Comment by afc163** [comment]
You may need or don't need fast click in mobile page, btw, we don't provide support under mobile device.

**Comment by arist0tl3** [comment]
In case anyone encounters this, if you have a way to check for your environment, you can easily do something like this. 

Note: I didn't have to make any modifications to click handling, fastclick, etc.

```
<Tooltip
  title="Info about this button"
  trigger={window.cordova ? 'click' : 'hover'}
>
  <Button>{'Some Text'}</Button>
</Tooltip>
```

**Comment by aminhdev** [comment]
I have the same problem
