### ISSUE TITLE
RcUpload instance in Upload component should not be 'private'.

### ISSUE THREAD

**Issue by dbFlower** [ant-design/ant-design#14439]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have read the source code of `Upload` component, but I can't find a way to add files manually such as paste event. Maybe `RcUpload` instance in `Upload` should not be a private property or export it .

### What does the proposed API look like?
[https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx#L55](https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx#L55)
```js
get uploadInstance() {
  return this.upload;
}
```

**Comment by ztplz** [comment]
Why don't you use `ref`?

**Comment by dbFlower** [comment]
![image](https://user-images.githubusercontent.com/9190813/51448948-bc9f4380-1d64-11e9-916c-1c9d6a34b145.png)

**Comment by dbFlower** [comment]
> Is it better to remove `private` rather than to add a function?

当初留`private`关键字就是为了防止外部更改的吧，我现在增加getter来拿会不会从语义上来说更符合当初的设定？
提这个Issue的时候只是要拿到 `RcUpload` 而已，但是提的PR里实际上是添加了 `uploader` 的 getter，拿的是 `RcUpload` 中真正起到上传作用的组件，即 `AjaxUploader`或者`FrameUploader` ([Here](https://github.com/react-component/upload/blob/master/src/Upload.jsx#L82))。

**Comment by ztplz** [comment]
也不是，ts即使private修饰后还是可以改的，private只是类型检查而已。我只是觉得加个getter还不如直接去除private，现在代码的风格不怎么统一，很多组件里ref都是public的。

**Comment by ztplz** [comment]
@afc163

**Comment by dbFlower** [comment]
Ok，只要拿的时候过了ts的类型检查就可以的，毕竟有的时候还有有直接添加文件的需求的。
