### ISSUE TITLE
Input.Search不居中了

### ISSUE THREAD

**Issue by MxdBupt** [ant-design/ant-design#14448]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://30.31.181.78:7001/#/locationQuery/lastLocationQuery ，](http://30.31.181.78:7001/#/locationQuery/lastLocationQuery ，)

### Steps to reproduce
点连接进去页面就是
对应代码：http://gitlab.alipay-inc.com/mobilelbs/iotgis/blob/sprint_iotgis_S902352483_20190109/src/page/LocationQuery/LastLocationQuery.js

### What is expected?
上个版本是居中的，代码没动，今天新拉迭代，默认是升级所有依赖的，然后就不居中了

### What is actually happening?
居中

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 用的bigfish最新版默认的React |
| System | MAC |
| Browser | google |

**Comment by ztplz** [comment]
别随意暴露服务器ip。。。把该关的端口都关了吧  github上很多脚本时刻在扫描的
