### ISSUE TITLE
Add type definitions for Steps.Step

### ISSUE THREAD

**Issue by danilofuchs** [ant-design/ant-design#14442]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, Steps.Step is defined as `static Step: any`, as present in antd/lib/steps/index.d.ts

The type definitions should be updated to conform with the [documentation](https://ant.design/components/steps/)

### What does the proposed API look like?
```
static Step: {
    description: string | React.ReactNode;
    icon: string | React.ReactNode;
    status: string;
    title: string | React.ReactNode;
};
```

**Comment by ycjcl868** [comment]
PR welcome.

**Comment by wx1322** [comment]
I will solve this problem
