### ISSUE TITLE
Enable strict option in tsconfig.json

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#14445]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
More strict types, fewer bugs.

### What does the proposed API look like?
No need.

**Comment by afc163** [comment]
+1

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/47998
