### ISSUE TITLE
Input 使用了getFieldProps后react fbjs报warning

### ISSUE THREAD

**Issue by biao166** [ant-design/ant-design#1444]
```
<FormItem
{...formItemLayout}
 label="简介：">
<Input type="textarea" {...getFieldProps('desc')} rows="3" />
</FormItem>
```

>  Warning: Textarea elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled textarea and remove one of these props. More info: https://fb.me/react-controlled-components

查看是input的defaultValue和value都自动设置了

**Comment by afc163** [comment]
#1340
