### ISSUE TITLE
WeekPicker 的 format 能否支持传一个函数

### ISSUE THREAD

**Issue by Ma63d** [ant-design/ant-design#14455]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
背景：目前 DatePicker、WeekPicker 等的 format props 都只支持传字符串。
比如传递'YYYY-MM-DD'、'YYYY-WW' 等 moment 格式化字符串。

对于 WeekPicker 的场景，默认展示为 '2018-37周'  这样的文案，但是用户难以明白这到底是哪一段日期。
如果想呈现为 "08/13 - 08/19(37周)" 则无法实现，因为 moment 格式化字符串不支持取到一周的起始和结尾。我们曾尝试直接透出具体日期与周数来弥补这一问题，但用户反而更懵逼了：
![image](https://user-images.githubusercontent.com/7710875/51465363-c182e800-1da2-11e9-8d45-3cbf4b4e4078.png)

如果 format 能支持传一个函数，那么则可以解决这个这个问题，antd 将 moment 对象给到函数，用户自己对 moment 对象进行处理，返回字符串给 WeekPicker 进行展示。

### What does the proposed API look like?
```
<WeekPicker format=(currentDate: moment) => '日期' />
```

**Comment by zombieJ** [comment]
format 需要 str -> moment 和 moment -> str 双向支持，对用户使用来说会比较困难，而且场景相对较少。建议是自己封装一层 HOC 来实现。
