### ISSUE TITLE
Search Icon within Input.Search Collapsed With Clear Icon

### ISSUE THREAD

**Issue by Puuuudding** [ant-design/ant-design#14456]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0q45vnok5l)

### Steps to reproduce
在Search中输入内容

### What is expected?
放大镜图标替换为x或者当鼠标移上去时放大镜变为x

### What is actually happening?
x和放大镜同时存在，并且x没有理想的css样式

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7.0 |
| System | macOS 10.14.2 |
| Browser | Chrome 71 |

**Comment by zombieJ** [comment]
放大镜按钮是可以点击的，如果遮盖住就点不了了。如果有样式需求，建议自己调整一下。
