### ISSUE TITLE
Input.Search with enterButton style

### ISSUE THREAD

**Issue by halukapaydin** [ant-design/ant-design#14452]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x7y15yk0ko)

### Steps to reproduce
input and button is not same line. button is 1 pixel up.
screenshot is https://pasteboard.co/HXrD9Wb.png

### What is expected?
input and button is same line

### What is actually happening?
input and button is not same line

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7.0 |
| System | Ubuntu 18.04.1 LTS |
| Browser | Google Chrome Version 70.0.3538.77 (Official Build) (64-bit) |

**Comment by ztplz** [comment]
Relate to https://github.com/ant-design/ant-design/issues/14450. It will be fixed ASAP.

**Comment by zombieJ** [comment]
merge with #14450
