### ISSUE TITLE
menu的hover事件添加

### ISSUE THREAD

**Issue by yayamommy** [ant-design/ant-design#1445]
需要在menu上面添加hover事件，如

``` java
整体
   KPI报表
      周报
```

这样的三级目录，每级目录上hover后都要添加一个事件。现在尝试在Menu、SubMenu、Menu.Item标签分别添加onMouseEnter事件，都不起作用。除非像这样

``` java
 <SubMenu key={id} title={<span onMouseEnter={this.handleMouseEnter}>{name}({dataNum})</span>} >


<Menu.Item key={id}><span onMouseEnter={this.handleMouseEnter}>{name}</span></Menu.Item>
```

才会生效，但是这样hover事件填充不了整行，只在span范围内起作用。

**Comment by superRaytin** [comment]
rc-menu 貌似没有把这个事件暴露给外部：https://github.com/react-component/menu/blob/master/src/SubMenu.jsx#L96 

所以我可能要先提个 PR 给 rc-menu 并发布新版本后，再整合进来

**Comment by superRaytin** [comment]
@yiminghe 帮忙看一下是否可行？

**Comment by yiminghe** [comment]
修改 SubMenu Menu.Item 试试，不要改 Menu

**Comment by pigletfly** [comment]
+1,我也遇到同样的问题，SubMenu没有`onMouseEnter`,底层的接口没有暴露。暂时实现是实现Menu的onOpen,在onOpen里判断SubMenu的key。

**Comment by superRaytin** [comment]
Wait for https://github.com/react-component/menu/pull/34

**Comment by superRaytin** [comment]
Fixed.

**Comment by superRaytin** [comment]
Fixed.
