### ISSUE TITLE
Input.Search style bug when set container textAlign to center

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design#14450]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/714j7zn300)

### Steps to reproduce
Just open https://codesandbox.io/s/714j7zn300

### What is expected?
Input display at center of page

### What is actually happening?
Input display display at left and style not right.

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | ^16.0.0 |
| System | mac |
| Browser | chrome |

---
Maybe related with https://github.com/ant-design/ant-design/commit/321117c5e82b50765555b4382e74c83932b994bb

**Comment by yutingzhao1991** [comment]
一个临时解决方案 https://codesandbox.io/s/nnkz4y06xl

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/14397

这个修改造成的。@zombieJ

---

另一个问题是造成 #14397 里[要修复的例子](https://codesandbox.io/s/714j7zn300) 变成了这样：

<img width="602" alt="image" src="https://user-images.githubusercontent.com/507615/51459530-da37d180-1d93-11e9-834a-0dd400b76b77.png">

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51459606-1f5c0380-1d94-11e9-8d87-5b895ccd8743.png)
变成table了

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51459643-326ed380-1d94-11e9-9912-e2198c33bf20.png)

**Comment by ztplz** [comment]
这个可能也是这个问题 https://github.com/ant-design/ant-design/issues/14448

**Comment by zombieJ** [comment]
> #14397
> 
> 这个修改造成的，不能修改现有组件的 display。@zombieJ

不改 display 就不能解决 #14396。漏了 suffix 的样式，补一下就好了。

**Comment by zombieJ** [comment]
类似 `addonBefore` 和 `addonAfter` 一样，包一层 span。之前 Input.Search 用的 padding 来顶出一段距离，如果不改成 table 就需要我们动态获取 Button 宽度来设置一番。

**Comment by yufengtan** [comment]
![image](https://user-images.githubusercontent.com/25997227/51654297-2c663600-1fd2-11e9-818a-2d75894156aa.png)
以前是这样的 更新后是
![image](https://user-images.githubusercontent.com/25997227/51654315-430c8d00-1fd2-11e9-805b-98f106cebc95.png)
这样的
组件后面空了一节  并且 按钮有细微错位
