### ISSUE TITLE
Table组件的空数据状态能不能自己定义

### ISSUE THREAD

**Issue by azz1123** [ant-design/ant-design#14459]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
目前每个Table会有一个默认的无数据状态，但是这个状态和需求不一样，能不能自己定义，建议给个入口，文字和图片可以自己定义

### What is expected?
Table无数据状态可以自己定义

### What is actually happening?
不能直接定义

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.0.0 |
| System | * |
| Browser | 谷歌 |

**Comment by afc163** [comment]
`locale.emptyText`

https://ant.design/components/table/#Table

**Comment by afc163** [comment]
Duplicate of #7690

**Comment by touring** [comment]
> `locale.emptyText`
> 
> https://ant.design/components/table/#Table

新版的新增的图标，如果配置了locale.emptyText， 默认的图文和文字都会被覆盖

**Comment by zhulihao965255** [comment]
https://ant.design/components/table/#Table

**Comment by zhulihao965255** [comment]
@afc163 Table能不能新增一个属性: noDataElement,可以让用户自己设置空数据下的显示元素，默认展示antd的Empty组件，这个我觉得还挺合理的https://ant.design/components/empty/

**Comment by maimai123** [comment]
> > `locale.emptyText`
> > https://ant.design/components/table/#Table
> 
> 新版的新增的图标，如果配置了locale.emptyText， 默认的图标和文字都会被覆盖 @afc163

可以传入node啊 不一定只能是文字

**Comment by 158008001** [comment]
> > > `locale.emptyText`
> > > https://ant.design/components/table/#Table
> > 
> > 
> > 新版的新增的图标，如果配置了locale.emptyText， 默认的图标和文字都会被覆盖 @afc163
> 
> 可以传入node啊 不一定只能是文字

请问该怎么做，才可以达到不换图标，只换文字的效果？

**Comment by sillyl** [comment]
请问该怎么做，才可以达到不换图标，只换文字的效果？

**Comment by keminu** [comment]
> 

同问

**Comment by sTeADone** [comment]
> > > > `locale.emptyText`
> > > > https://ant.design/components/table/#Table
> > > 
> > > 
> > > 新版的新增的图标，如果配置了locale.emptyText， 默认的图标和文字都会被覆盖 @afc163
> > 
> > 
> > 可以传入node啊 不一定只能是文字
> 
> 请问该怎么做，才可以达到不换图标，只换文字的效果？

`import { Empty } from 'antd'`
...
`locale={{
          emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="aaaaa" />
        }}`
