### ISSUE TITLE
热加载在二级目录下失效

### ISSUE THREAD

**Issue by Abel94** [ant-design/ant-design#1446]
当路径切换到：http://localhost:8989/setting/site 时，尝试去加载了 http://localhost:8989/setting/5db1c02eaf9451f51123.hot-update.json

正确的路径应该是http://localhost:8989/5db1c02eaf9451f51123.hot-update.json

**Comment by sorrycc** [comment]
通过设 publicPath 解决，参考：https://github.com/dora-js/dora-plugin-webpack-hmr/issues/1#issuecomment-208111866
