### ISSUE TITLE
The are something wrong in Edge

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#14466]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rl2j645w6p)

### Steps to reproduce
When a component that relies on Wave re-triggers the animation.

### What is expected?
Compatible with Edge

### What is actually happening?
Can not compatible the environment that does not support removeAttribute

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.6.0 |
| System | Win 10 |
| Browser | Edge 17.17134 |

---
https://github.com/ant-design/ant-design/blob/b87261673ababf294f0fbfba680cfd95f7390f72/components/_util/wave.tsx#L44-L45

Need to be compatible with `removeAttribute`

**Comment by zombieJ** [comment]
This bug already fixed in latest edge. Pls update edge instead.

**Comment by xyy94813** [comment]
You can't always ask web users to upgrade user agent. 
This is why JS is always forward compatible.
@zombieJ
