### ISSUE TITLE
Steps with dots not responsively changing to vertical

### ISSUE THREAD

**Issue by danilofuchs** [ant-design/ant-design#14463]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o7r01mm52y)

### Steps to reproduce
Resize the preview window horizontally. You will notice that when the view size is too small to show the full timeline, Steps automatically sets its own property `direction="vertical"`. This only occurs when `progressDot={false}`.

### What is expected?
The same behaviour should apply when `progressDot={true}` (responsively changing the direction of timeline)

### What is actually happening?
The timeline is cut when `progressDot={true}` and the view window is too small.

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7.0 |
| System | Windows 10 |
| Browser | Chrome 71.0.3578.98 |

**Comment by zombieJ** [comment]
dot style 's Step layout is vertical instead. So it not provide the responsive function on that.

**Comment by danilofuchs** [comment]
I didn't quite understand the reason to close the issue.
Have you tried to resize the view window to a small size?

**Comment by saostad** [comment]
I confirm problem still exist in v4.0.4, if I use it without progressDot, it is responsive and no need any extra CSS. I think it will be better if it has same behavior as without progressDot.
<Steps
      progressDot={true}
      current={current}
      onChange={onChange}
    >
      {sections.map(el => (
        <Step title={el} key={el} />
      ))}
    </Steps>
