### ISSUE TITLE
Change TimePicker[allowEmpty] to allowClear for consistency

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#14472]
https://ant.design/components/time-picker-cn/

**Comment by wx1322** [comment]
Change `allowEmpty?: boolean;` to `allowClear?: boolean;`, isn't it?

**Comment by zombieJ** [comment]
> Change `allowEmpty?: boolean;` to `allowClear?: boolean;`, isn't it?

We will still keep `allowEmpty` in code. But add warning of it and remove from doc.

**Comment by zombieJ** [comment]
Seems TimePicker clear style is also not same as DatePicker. Let sync this at the same time:
<img width="192" alt="2019-01-22 4 19 43" src="https://user-images.githubusercontent.com/5378891/51521456-9f9c6a80-1e61-11e9-93be-62cba1c4bb5c.png">
<img width="183" alt="2019-01-22 4 19 56" src="https://user-images.githubusercontent.com/5378891/51521461-a32ff180-1e61-11e9-85a8-740d46539762.png">
