### ISSUE TITLE
Paggination set range item 

### ISSUE THREAD

**Issue by bigfatpanda1994** [ant-design/ant-design#14474]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i cant set number page can visible, The range of pages displayed

### What does the proposed API look like?
set number page can view

**Comment by afc163** [comment]
Sorry, we won't support this kind of customization cause we are following ant design specification.
