### ISSUE TITLE
use antd design table, and I copy a value in table, and paste the value to the a FormItem component(like input component).It will apears strange space in this value in input sometimes

### ISSUE THREAD

**Issue by wenwen1995** [ant-design/ant-design#14475]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2x.ant.design/components/form-cn/, https://2x.ant.design/components/table-cn/#](https://2x.ant.design/components/form-cn/, https://2x.ant.design/components/table-cn/#)

### Steps to reproduce
1、copy the table value.
2、paste the value to the formItem.
3、if it doesn't appear,please try the first and second step more times.

### What is expected?
After i copy the value from Table, when I paste the  value to the FormItem input,please don't show the strange space in the input

### What is actually happening?
The FormItem input component will have strange space someTimes

| Environment | Info |
|---|---|
| antd | 2.12.8 |
| React | 15.2.1 |
| System | windows |
| Browser | chrome, 360浏览器均会出现 |

**Comment by wenwen1995** [comment]
![image](https://user-images.githubusercontent.com/12100065/51522608-babca980-1e64-11e9-80a4-64d4886b88f2.png)

like the top photo

**Comment by afc163** [comment]
Could you record a video or gif?

**Comment by wenwen1995** [comment]
Yes,here.But it apears sometimes but normally.
![demo](https://user-images.githubusercontent.com/12100065/51530783-b3060080-1e76-11e9-979a-2f4d36aee194.gif)

**Comment by fonghehe** [comment]
About this question，the word you copy has spaces in it，you can add trim function behind the value when  you submit form

**Comment by wenwen1995** [comment]
@fonghehe ，emmmm, even the word I copy which has no spaces in it, it will show some strange space when I paste.So I want to solve it by listening window copy event or paste event? And add a trim function？But I wanted to know whether  the antd-design website has better solution.

**Comment by zombieJ** [comment]
Since 2.x version is not maintained. We strongly recommand to use 3.x

And for latest version it's OK: https://codesandbox.io/s/w05mz683j7
![kapture 2019-01-23 at 11 53 26](https://user-images.githubusercontent.com/5378891/51582098-9533ac80-1f05-11e9-9157-b0e43b74fff9.gif)

**Comment by shenzhim** [comment]
There are still problems when double-clicking the text of table cell to select

**Comment by shenzhim** [comment]
> There are still problems when double-clicking the text of table cell to select

![bug](https://user-images.githubusercontent.com/12244144/102161644-88dbd400-3e3c-11eb-8a35-c01bae10336f.gif)

**Comment by Leo7991** [comment]
I've had the same problem, even though this bug still exists, even if it's table in the latest version.

**Comment by jmtimko5** [comment]
This bug is still in the latest version can confirm
