### ISSUE TITLE
Table的loading是true loading的spin能自己定义吗

### ISSUE THREAD

**Issue by azz1123** [ant-design/ant-design#14486]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自己可以定义loading

### What does the proposed API look like?
接收ReactNode

**Comment by afc163** [comment]
`loading={{ indicator: <div>loading...</div> }}`

https://codesandbox.io/s/l521958pmz
