### ISSUE TITLE
RadioGroup onChange事件执行了两次

### ISSUE THREAD

**Issue by hhyaner** [ant-design/ant-design#14485]
antd 版本 3.12.4

问题：
今日更新npm库时，更新了antd。原功能是RadioGroup变更时，去请求数据一次，今日发现，请求重复了。由RadioGroup的onChange事件执行了两次引起的。

代码如下

`
<RadioGroup
        onChange={(e) => {
          e.preventDefault();
          // 查询数据
          query({
            isMy: e.target.value
          });
        }}
      >
        <RadioButton value={false}>
          全部
        </RadioButton>
        <RadioButton value>
          我的
        </RadioButton>
      </RadioGroup>
`
---

**Comment by ztplz** [comment]
给个online demo，你在radioGroup和radio里都写了onChange了？

**Comment by hhyaner** [comment]
> 给个online demo，你在radioGroup和radio里都写了onChange了？

https://codesandbox.io/s/l21kjjl2yl

**Comment by ztplz** [comment]
刚看了下  原来的好像重复了
