### ISSUE TITLE
select组件能否支持icon选择？

### ISSUE THREAD

**Issue by tanxiuguang** [ant-design/ant-design#14480]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
给菜单设置图标，需要一个类似select的组件。点击下拉有平铺所列的图标，选择后类似select组件显示选择的图片，数据层能够获得icon的相关数据

### What does the proposed API look like?
```
<Select defaultValue="lucy" style={{ width: 120 }} onChange={handleChange}>
      <Option value="step-backward"><Icon type="step-backward" /></Option>
      
    </Select>
```

**Comment by afc163** [comment]
可以支持，像你这么写就可以了。
