### ISSUE TITLE
Radio button doesn't have "name" attribute

### ISSUE THREAD

**Issue by Dreebo** [ant-design/ant-design#14491]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Regarding to this issue https://github.com/ant-design/ant-design/issues/14374. You said that it is a browser compatibility issue, but I have investigated this issue, and saw one interesting case. Focusing by tab doesn't work if input with type "radio" doesn't have a unique "name" attribute. And as i can see,  you do not provide an opportunity to set this attribute for radio button.  

### What does the proposed API look like?
Is it possible to add name attribute for radio button?

**Comment by ztplz** [comment]
Is there a related docs or demo? let me have a look, thanks.

**Comment by zombieJ** [comment]
We can support `name` prop on RadioGroup. Since user can not use tab for radio switch but can use direction key for select radio.

**Comment by Dreebo** [comment]
Yes, you are right! But it will be really cool, if you can add opportunity to set the "name" attribute:)

**Comment by zombieJ** [comment]
checked the code and find that Radio & RadioGroup already support `name` prop. Close this issue: https://codesandbox.io/s/7yww7724y0

**Comment by Dreebo** [comment]
But in RadioGroup i can't set the `name` prop for Radio button(

**Comment by zombieJ** [comment]
RadioGroup manage the `name` of sub RadioButtons. You need only to set `name` on RadioGroup.

**Comment by Dreebo** [comment]
Yes, i see, but `name` is not unique prop if i set the `name` prop for RadioGroup

**Comment by zombieJ** [comment]
Why do you want to set different `name` of RadioButton under a RadioGroup?

**Comment by Dreebo** [comment]
For expected behavior focusing by tab button)
Because as i said early, if input with type `radio` doesn't have unique  `name` prop, by pressing tab button focus set only on first item.
I know that i can manage radio button by arrow, but i have a requirements that focus should set on all item one by one by pressing tab button.

**Comment by zombieJ** [comment]
In this way, I think you may use Button to mock the UI as the RadioButton.
Since tab works on group of radio in same name is the browser behavior for accessibility, support different `name` under same RadioGroup is not good to do it in antd.

**Comment by Dreebo** [comment]
Ok. Thank you!
