### ISSUE TITLE
Input.Search 搜索按钮与Input断开

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design#14498]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6j1llo680k)

### Steps to reproduce
Input.Search 搜索按钮与Input断开

### What is expected?
正常显示

### What is actually happening?
Input.Search 搜索按钮与Input断开

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.4.1 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
merge into #14450
