### ISSUE TITLE
How to set the global timezone?

### ISSUE THREAD

**Issue by QAQMiao** [ant-design/ant-design#14497]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Moment maybe get wrong timezone in some versions of chrome, so how can I set a global timezone ?

### What does the proposed API look like?
config in LocaleProvider

**Comment by QAQMiao** [comment]
For example, the "this moment"（此刻） in the DatePicker component, when encountering the problem of the moment, there is no way to deal with it. So how do you configure the timezone globally?

**Comment by zombieJ** [comment]
http://momentjs.com/timezone/docs/#/using-timezones/default-timezone/

**Comment by QAQMiao** [comment]
Is there any api of antd to change the global timezone?
