### ISSUE TITLE
How to set the global timezone? this is not repeat

### ISSUE THREAD

**Issue by QAQMiao** [ant-design/ant-design#14499]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Moment maybe get wrong timezone in some versions of chrome, so how can I set a global timezone ?
For example, **the "this moment"(此刻) function in the DatePicker component**, when encountering the problem of the moment, using the moment.tz in the project is invalid for this case, so how to configure the time zone of the ant globally?

### What does the proposed API look like?
give a global timezone config of antd

**Comment by ycjcl868** [comment]
It should config in [ConfigProvider[](https://ant.design/components/config-provider/), we can discussion whether add `timeZone`

**Comment by carmenchapa** [comment]
> Why `using the moment.tz in the project is invalid for this case`? It works fine by setting the timezone: https://codesandbox.io/s/oo2zllzq2y

This is not working anymore
