### ISSUE TITLE
Type error: Interface 'TreeSelectProps' incorrectly extends interface 'AbstractSelectProps'.

### ISSUE THREAD

**Issue by jdpigeon** [ant-design/ant-design#14493]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/007kpxjk70)

### Steps to reproduce
Add the newest version of yarn to a typescript project and import any of the components (Layout in my case)

### What is expected?
App should compile

### What is actually happening?
The following TypeScript error is throw:
```
Type error: Interface 'TreeSelectProps' incorrectly extends interface 'AbstractSelectProps'.
  Types of property 'getPopupContainer' are incompatible.
    Type '((triggerNode: Element) => HTMLElement) | undefined' is not assignable to type '((triggerNode?: Element | undefined) => HTMLElement) | undefined'.
      Type '(triggerNode: Element) => HTMLElement' is not assignable to type '(triggerNode?: Element | undefined) => HTMLElement'.
        Types of parameters 'triggerNode' and 'triggerNode' are incompatible.
          Type 'Element | undefined' is not assignable to type 'Element'.
            Type 'undefined' is not assignable to type 'Element'.  TS2430

    24 |     rootPId?: string;
    25 | }
  > 26 | export interface TreeSelectProps extends AbstractSelectProps {
       |                  ^
    27 |     autoFocus?: boolean;
    28 |     defaultValue?: string | number | Array<any>;
    29 |     dropdownStyle?: React.CSSProperties;
```

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7.0 |
| System | Ubuntu 18.10 |
| Browser | Chrome |

---
Downgrading to antd version 3.11 resolves the issue

**Comment by ztplz** [comment]
Yes, It's fixed by https://github.com/ant-design/ant-design/pull/14443. We release new version every weekend.

**Comment by ztplz** [comment]
Close it for it have been fixed.

**Comment by aaronjameslang** [comment]
Can confirm this version works: `"antd": "^3.9.3 <3.12.4 || ^3.12.5",`

**Comment by Zane0816** [comment]
In Typescript AbstractSelectProps getPopupContainer Should be allowed to return null
