### ISSUE TITLE
在Table中，列有过滤(排序或查找)功能情况下，能否紧贴标题右侧，不一定非要在列居右。

### ISSUE THREAD

**Issue by handsomeFive** [ant-design/ant-design#14495]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在列宽较小的时候，样式会有点不协调；前提在不使用边框下，在列宽较大时，icon居列右边与第二列的title距离较近且第二列列表无值会有视觉上问题，用户会看见一个icon位于title的左边，会认为这两为一列。

### What does the proposed API look like?
列表定义时增加一个属性控制该列中icon位置

**Comment by handsomeFive** [comment]
![image](https://user-images.githubusercontent.com/31915664/51578986-56e4c000-1efa-11e9-9ddb-143dc2220948.png)

**Comment by 723156735** [comment]
我也遇见这个问题了，现在是通过css样式将icon改为left定位

**Comment by afc163** [comment]
Duplicate of #15403
