### ISSUE TITLE
When tabbing and changing focus to a Select component (With the search option activated), typing does not search the field

### ISSUE THREAD

**Issue by NathanBP** [ant-design/ant-design#14503]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/GOxqow](https://codepen.io/anon/pen/GOxqow)

### Steps to reproduce
Click on the first field, then press tab and try to type something.

### What is expected?
When tabbing the focus should change to the Select and let you type so you can search between options.

### What is actually happening?
When tabbing you are not able to type.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.6.3 |
| System | Windows 10 x64 |
| Browser | Chrome  71.0 |

---
We came across this bug in a current project, we have found an existing issue which mentions the exact same bug but it has been closed without any fix or reason for why the issue was closed. Could this new issue continue to get this bug resolved, or the original issue re-opened until a fix is put in place.

Original issue: https://github.com/ant-design/ant-design/issues/8269

I get that this issue is a duplicate but the above issue was not resolved and no reason was given for it being closed.

Antd version is 3.12.4, couldn't get the picker to allow me to select a version.

**Comment by KobanDavis** [comment]
[Apparently](https://github.com/ant-design/ant-design/issues/6873#issuecomment-396968157), select uses rc-select under the hood, so adding 
```
showAction='focus'
```
In my case, however, this broke the click functionality. I'm not sure it did this because I was using a ref to focus the select by a keyboard event, but writing
```
showAction={['focus', 'click']}
```
did the trick for me.

**Comment by dhassouni** [comment]
I am running into the same issue. I am finding this is only a problem when the Select component's mode property is "default". It works as we would expect/want when the mode is "multiple".

**Comment by ashatat** [comment]
@KobanDavis  I love you man,
this should be added to the antd documentation

**Comment by mattoni** [comment]
When applying `showAction={['focus', 'click']}`, I noticed clicking the chevron icon forces the select to pop open then close immediately. Is this happening for others?

**Comment by afc163** [comment]
It works in antd@4.6.x: https://codepen.io/afc163-1472555193/pen/LYNLzWL
