### ISSUE TITLE
Switch 缺少onClick

### ISSUE THREAD

**Issue by c19** [ant-design/ant-design#14509]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需要onClick和onChange分离。以便阻止Switch默认行为。以便增加确认框。rc-switch提供onClick。

### What does the proposed API look like?
<Switch onClick={event => {return false}} />
或者
<Switch onClick={event => {event.preventDefault}} />
这样onChange不会被调用。UI也不会变化。

**Comment by afc163** [comment]
使用受控属性 checked，并在 onChange 中进行判断就行了。

**Comment by wzlee** [comment]
@afc163 你都没看懂别人的意思就关闭issue
