### ISSUE TITLE
可伸缩列Demo设置scroll，fixed等错乱

### ISSUE THREAD

**Issue by America-first-melon** [ant-design/ant-design#14505]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnx2jxmmv)

### Steps to reproduce
如图

### What is expected?
正常渲染

### What is actually happening?
界面错乱

| Environment | Info |
|---|---|
| antd | 3.6.3 |
| React | 16.4.2 |
| System | windows |
| Browser | Chrome |

**Comment by America-first-melon** [comment]
![image](https://user-images.githubusercontent.com/21686182/51588554-8c4fd480-1f1f-11e9-8fbb-ed05692754c0.png)

**Comment by zombieJ** [comment]
Duplicate of #13825

**Comment by America-first-melon** [comment]
> Duplicate of #13825

这不是一个问题吧。断词不断词问题依旧。

**Comment by zombieJ** [comment]
是相同的，原本的 Table 为了宽度适应问题设置了 `word-break: break-word;`。后来又引起了另一个问题，就取消了这个样式。具体看看这里的说明：https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by America-first-melon** [comment]
> 是相同的，原本的 Table 为了宽度适应问题设置了 `word-break: break-word;`。后来又引起了另一个问题，就取消了这个样式。具体看看这里的说明：[#13825 (comment)](https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241)

我再看一下是不是遗漏了什么   谢谢
