### ISSUE TITLE
Modal设置z-index后，使用Notification设置z-index还是会被盖住

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#14506]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/WPbXgv?&editable=true&editors=001](https://codepen.io/mraiguo/pen/WPbXgv?&editable=true&editors=001)

### Steps to reproduce
打开模态框，再点击模态框中的弹出notification按钮

### What is expected?
notification被模态框盖住了

### What is actually happening?
notification在模态框之上

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | react16 |
| System | win10 |
| Browser | chrome71 |

---
使用getContainer或许可以解决这个问题，但是直接通过设置notification的style控制它的z-index来达到这个效果才是最让人容易接受的做法吧。
![image](https://raw.githubusercontent.com/mraiguo/image-respository/master/bug/notification.gif)

**Comment by zombieJ** [comment]
notification 的 style 属性是在框里不是在弹层上，所以如果要提升 notification 的 z-index 需要设置 `.ant-notification` 的 css。

**Comment by dwb1994** [comment]
> notification 的 style 属性是在框里不是在弹层上，所以如果要提升 notification 的 z-index 需要设置 `.ant-notification` 的 css。

notification 组件的 className 设置在 .ant-notification 的子元素上，这样修改 z-index 很不方便，怎么处理呢

**Comment by sjyMystery** [comment]
我鞭尸一下，这个问题得不到解决。
