### ISSUE TITLE
Tabs 内嵌在 Collapse 中的当前项显示问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1451]
重现演示：http://codepen.io/anon/pen/oxyxvz?editors=001

点击第二个项折叠菜单展开时，tabs 高亮的项有问题，切换 Tab 后恢复。

**Comment by warmhug** [comment]
另外：业务中发现条目多的时候、render 比较慢，是否有性能问题？ 改了一下测不出来 http://codepen.io/anon/pen/YqvELg?editors=001

**Comment by yiminghe** [comment]
rc-collapse 1.6.0
