### ISSUE TITLE
Small table header shows page background at left and right edge

### ISSUE THREAD

**Issue by oestrogen** [ant-design/ant-design#14510]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk0owwpwmq)

### Steps to reproduce
* Set the page or container background to something other than white
* Look at the left and right edges of the header of a small table

### What is expected?
* The background colour is **not** shown through at the table header edges

### What is actually happening?
* The background colour **is** shown through at the table header edges

![chrome_hnl6mwyzld](https://user-images.githubusercontent.com/351057/51592062-f734e780-1eee-11e9-8c14-43e921f8586c.png)

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | latest |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
It is by designed.

**Comment by krokofant** [comment]
@afc163 So this is a design issue. It does not look good compared to the other table sizes and for a small table it takes up unnecessary space.

![image](https://user-images.githubusercontent.com/5908498/51593592-d373a080-1ef2-11e9-8201-9d2bbd126858.png)

**Comment by oestrogen** [comment]
@afc163 Should I create a feature request instead? Because I think this is bad design.
I think the margin should be removed, and optionally the border too.

![chrome_evvyhi3toi](https://user-images.githubusercontent.com/351057/51593927-952ab100-1ef3-11e9-8658-ac481856fb11.png)

**Comment by afc163** [comment]
I afraid our design only works on white background..

**Comment by krokofant** [comment]
So if a PR is provided to fix this issue it could be accepted? Since fixing this wont disturb anything if the background is already white.

**Comment by keithort** [comment]
This change is causing me problems. The correct fix would have been either to remove the [margin](https://github.com/ant-design/ant-design/blob/master/components/table/style/size.less#L55) or expose the table header background color for theme overrides.
