### ISSUE TITLE
Changing the count of a badge with border-color raises an error

### ISSUE THREAD

**Issue by bakku** [ant-design/ant-design#14516]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oxrl1zz349)

### Steps to reproduce
1. Have a Badge with a custom border-color
2. Change the count of the badge

### What is expected?
Badge count is changed

### What is actually happening?
"TypeError: Attempted to assign to readonly property." is thrown

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | React 16.7.0 |
| System | MacOS Mojave |
| Browser | Chrome 71.0.3578.98 |

**Comment by lehuunhan404** [comment]
i fixed . thank youuuuu . good job
