### ISSUE TITLE
getFieldsValue return type  is not correct in typescript

### ISSUE THREAD

**Issue by RunningCoderLee** [ant-design/ant-design#14512]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/20mw4lrk7y)

### Steps to reproduce
When I use destruction syntax from the return value of `getFieldsValue`，TS will show `Type 'Object' has no property 'name' and no string index signature.`

### What is expected?
return type is  any 

### What is actually happening?
Object

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.6.3 |
| System | mac OSX |
| Browser | chrome  71.0.3578.98  |

**Comment by anton62k** [comment]
I think getFieldsValue should be

 `getFieldsValue(fieldNames?: Array<string>): { [field: string]: any }` 

instead 

`getFieldsValue(fieldNames?: Array<string>): Object;`

After that, TS will allow to write like this:

`
const { name } = this.props.form.getFieldsValue() 
`

I will make this pull request if antd team approves it.

**Comment by ztplz** [comment]
![untitled7](https://user-images.githubusercontent.com/17755202/51726484-9f3ee200-20a2-11e9-9017-3b9309b3db41.gif)
If I did something wrong? There is nothing happen.

**Comment by RunningCoderLee** [comment]
@ztplz please open the `CustomForm.tsx`,  you will see the TS error prompt

**Comment by ztplz** [comment]
![untitled7](https://user-images.githubusercontent.com/17755202/51727598-b16f4f00-20a7-11e9-9c0e-497dd934a849.gif)

**Comment by RunningCoderLee** [comment]
![image](https://user-images.githubusercontent.com/13218863/51727765-74f02300-20a8-11e9-9186-fdcbf7362e9f.png)

**Comment by RunningCoderLee** [comment]
英语太渣，还是用汉语来描述，有能力的大佬欢迎帮忙翻译

对 TS 的配置不同可能导致有些环境会报错，但有些不会，个人认为这里是否可以像 @anton62k 所描述的那样将返回值改的更精确一些？

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51730793-bfc36800-20b3-11e9-99f6-7ea4ae4e52e7.png)
但是我这里没错  因为它是any

**Comment by RunningCoderLee** [comment]
在 TS 环境中，如果对 `Object` 类型进行解构，编译器会报错，但是 `any` 则不会， 以下这个是 TS 的示例

https://www.typescriptlang.org/play/index.html#src=const%20Foo%3A%20Object%20%3D%20%7B%20aa%3A%201%20%7D%0D%0A%0D%0Aconst%20%7B%20aa%20%7D%20%3D%20Foo%3B%0D%0A%0D%0Aconst%20Bar%3A%20any%20%3D%20%7B%20bb%3A%201%20%7D%0D%0A%0D%0Aconst%20%7B%20bb%20%7D%20%3D%20Bar%3B

**Comment by zombieJ** [comment]
嗯，可以改一下。
