### ISSUE TITLE
Input.Search   size='large'  按钮错位   输入框宽度没有100%

### ISSUE THREAD

**Issue by yufengtan** [ant-design/ant-design#14527]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
直接看现象

### What is expected?
之前输入框占位 100% 

### What is actually happening?
输入框占位没100%， 当size属性为large时 搜索按钮 错位了

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.6.3 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
merge into #14450

**Comment by zy410419243** [comment]
Duplicate of #
