### ISSUE TITLE
ant design 配置按需加载后，scss 模块化样式失效

### ISSUE THREAD

**Issue by lzy94** [ant-design/ant-design#14528]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://xxx.com](http://xxx.com)

### Steps to reproduce
1、react 脚手架 create-react-app并且已经 npm run eject 
2、开始做项目时没有用到ant design ，样式组件全部是手写自己实现。
3、使用scss 并开启 scss 模块化  webpack.config.js 配置   modules: true,
4、后来引入 ant design  并按照文档配置 按需加载
5、启动运行发现 自己的样式没有加载  引入样式 import Header from './Header.scss'   结果Header 为{}   。但是ant design 可以使用。 

### What is expected?
配置按需加载后，自己实现的样式也能使用

### What is actually happening?
自己的样式没有加载  引入样式 import Header from './Header.scss'   结果Header 为{}   。但是ant design 可以使用。 

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7.0 |
| System | window 64 |
| Browser | google 71.0.3578.98 |

**Comment by afc163** [comment]
这应该是你的 webpack 配置问题，不是 antd 的问题。

**Comment by lzy94** [comment]
> Hello @lzy94. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @lzy94, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

https://github.com/lzy94/react-text.git

**Comment by lzy94** [comment]
> 这应该是你的 webpack 配置问题，不是 antd 的问题。
webpack 我只加了个  modules: true,

**Comment by lzy94** [comment]
> 这应该是你的 webpack 配置问题，不是 antd 的问题。

webpack 我只加了个 modules: true, 开始可以 配置了ant 按需加载后 scss 模块化就没用

**Comment by afc163** [comment]
react-app-rewired 和 customize-cra 安装他们的文档，是在非 reject 的情况下使用的。如果你 reject 了，需要你自行探索配置方式了。
