### ISSUE TITLE
官方缩起内嵌菜单示例在改变openKeys后缩起菜单，子菜单会漂移。

### ISSUE THREAD

**Issue by jiangseventeen** [ant-design/ant-design#14536]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/jiangseventeen/pen/GzJwwY](https://codepen.io/jiangseventeen/pen/GzJwwY)

### Steps to reproduce
点击收缩菜单按钮

### What is expected?
子菜单跟随Menu位置

### What is actually happening?
子菜单停留原地。

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7.0 |
| System | windows、MacOS |
| Browser | chrome |

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/ZwbEYd?&editable=true&editors=001

没有问题。

你的例子里指定了受控属性 `openKeys`，那么菜单会完全遵照你指定的状态表现。

**Comment by jiangseventeen** [comment]
展开可见是对的，但sub1 不应该回到收缩的菜单旁边吗，现在的问题是sub1 还停留在原位置，必须手动hover菜单，或页面resize时，才会正确归位。

**Comment by afc163** [comment]
Merged issue to #15321

**Comment by afc163** [comment]
Duplicate of #15321

**Comment by ouzhou** [comment]
现在收起会闪烁一下
