### ISSUE TITLE
Input.Search loading

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design#14538]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
网络慢时，防止用户继续点击去请求

### What does the proposed API look like?
输入关键字进行模糊查询，然后进入loading状态不可点击

**Comment by afc163** [comment]
+1

**Comment by BowenZ** [comment]
为什么这个功能3.18.2还是没有...

**Comment by afc163** [comment]
@BowenZ 来个 PR ☺

**Comment by shaodahong** [comment]
Closed via #18771
