### ISSUE TITLE
Pagination的showQuickJumper属性虽然有视觉展示 但是输入页码没有任何反应

### ISSUE THREAD

**Issue by 1416246152** [ant-design/ant-design#14532]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这是个bug吗 ？

### What does the proposed API look like?
或者正确用法是什么

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
