### ISSUE TITLE
Table里面加上rowSelection可选项属性，在IE浏览器页面下卡爆了

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#14531]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd版本为3.12.3；
Table里面加上rowSelection可选项属性，在IE或者360浏览器下，页面下直接卡爆了，表格里面数据不是很多，也就是二三十条，但勾选表格里面的某行数据，得停顿半天才勾选上，感觉体验很不友好，用户多次反馈这问题，谷歌浏览器还算正常，就IE跟360浏览器跟其它一些不知名的浏览器有延迟卡顿现象。

### What does the proposed API look like?
希望在IE或者其它浏览器下，能正常勾选，不会卡顿几秒后才勾选成功

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

**Comment by Mathround** [comment]
> If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

这个应该不算bug吧

**Comment by afc163** [comment]
性能问题算 bug 的。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12408

看看这个先
