### ISSUE TITLE
table内容为空的表格高度变窄问题。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#14534]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1ov5yp2q64)

### Steps to reproduce
查看重现链接可以看到，我的data, key 为 4,5,6的三条记录 是没值的，所以显示的时候，key 为 1 ,2 ,3 的要高点，但是 4，5，6 的样式要窄点。

### What is expected?
不管table是否有内容，都应该显示同等高度。

### What is actually happening?
table 的data 只有key 的时候显示的 记录高度不一致。

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.6.3 |
| System | windows10 专业版 |
| Browser | chrome 71.0.3578.98  |

**Comment by zombieJ** [comment]
表格高度是自适应的，组件不应该帮用户做决定。如果有高度需求，可以自己定一下：https://codesandbox.io/s/7m85812031

**Comment by xgj1988** [comment]
@zombieJ  那我不是每个table 都要写上这句话吗？？我现在封装了一个basictable 。我在basictable里面怎么统一做这个呢？而且还要考虑不同size情况。有可以覆盖哪个样式的这种做法吗？

**Comment by zombieJ** [comment]
使用 `components` 属性可以自定义元素，HOC 包一下就行了：https://ant.design/components/table-cn/#Table

**Comment by xgj1988** [comment]
@zombieJ 文档里面也没有些components 具体怎么使用撒

**Comment by xgj1988** [comment]
额，，我这样写的
` const BodyRow = (props) => <tr style={{ height: '90px' }} aa="1233214" {...props} />;

    const components = {
      // header: {
      //   cell: this.ResizeableTitle
      // }
      body: {
        row: BodyRow
      }
    };`

f12 查看 ， 然而style这个属性并没有添加，aa这个属性都添加了到tr了

**Comment by zombieJ** [comment]
额，我意思是自定 cell，弄个 div 设置一下高度：https://codesandbox.io/s/1y7qz9xrzq

**Comment by xgj1988** [comment]
好的。谢谢。

**Comment by xgj1988** [comment]
@zombieJ 我这里有个诡异的情况，就是 td 里面的连接点了没反应，但是我在你给我的sandbox上面改又可以。，能帮我远程看看吗？

**Comment by zombieJ** [comment]
用 dev tools 审查元素看一下是什么东西挡住了。

**Comment by zombieJ** [comment]
cc @chenshuai2144

**Comment by chenshuai2144** [comment]
你修改了 css-modlue 的生成方式吗？
https://github.com/ant-design/ant-design-pro/blob/54678ba63ee1ce1540448414f342badfecec9b2d/config/config.js#L89

将这个里面的 ant-design-pro 修改为 antd-pro

**Comment by xgj1988** [comment]
@chenshuai2144  我的配置是这样：
`// https://umijs.org/config/
import os from 'os';
import pageRoutes from './router.config';
import webpackplugin from './plugin.config';
import defaultSettings from '../src/defaultSettings';

export default {
  // add for transfer to umi
  plugins: [
    [
      'umi-plugin-react',
      {
        antd: true,
        dva: {
          hmr: true
        },
        locale: {
          enable: true, // default false
          default: 'zh-CN', // default zh-CN
          baseNavigator: true // default true, when it is true, will use `navigator.language` overwrite default
        },
        dynamicImport: {
          loadingComponent: './components/PageLoading/index'
        },
        ...(!process.env.TEST && os.platform() === 'darwin'
          ? {
            dll: {
              include: ['dva', 'dva/router', 'dva/saga', 'dva/fetch'],
              exclude: ['@babel/runtime']
            },
            hardSource: true
          }
          : {})
      }
    ]
  ],
  targets: {
    ie: 11,
  },
  hash: true,
  extraBabelIncludes: [
    /pinyin/,
  ],
  proxy: {
    '/api': {
      target: 'http://localhost:8080/',
      pathRewrite: { '^/api': '' },
      changeOrigin: true
    }
  },
  define: {
    APP_TYPE: process.env.APP_TYPE || ''
  },
  // 路由配置
  routes: pageRoutes,
  // Theme for antd
  // https://ant.design/docs/react/customize-theme-cn
  theme: {
    'primary-color': defaultSettings.primaryColor
  },
  externals: {
    '@antv/data-set': 'DataSet'
  },
  ignoreMomentLocale: true,
  lessLoaderOptions: {
    javascriptEnabled: true
  },
  disableRedirectHoist: true,
  cssLoaderOptions: {
    modules: true,
    getLocalIdent: (context, localIdentName, localName) => {
      if (
        context.resourcePath.includes('node_modules') ||
        context.resourcePath.includes('ant.design.pro.less') ||
        context.resourcePath.includes('global.less')
      ) {
        return localName;
      }
      const match = context.resourcePath.match(/src(.*)/);
      if (match && match[1]) {
        const antdProPath = match[1].replace('.less', '');
        const arr = antdProPath
          .split('/')
          .map(a => a.replace(/([A-Z])/g, '-$1'))
          .map(a => a.toLowerCase());
        return `antd-pro${arr.join('-')}-${localName}`.replace(/--/g, '-');
      }
      return localName;
    }
  },
  manifest: {
    name: 'ant-design-pro',
    background_color: '#FFF',
    description:
      'An out-of-box UI solution for enterprise applications as a React boilerplate.',
    display: 'standalone',
    start_url: '/index.html',
    icons: [
      {
        src: '/favicon.png',
        sizes: '48x48',
        type: 'image/png'
      }
    ]
  },
  chainWebpack: webpackplugin,
  cssnano: {
    mergeRules: false
  }
};
`

**Comment by chenshuai2144** [comment]
chainWebpack: webpackplugin, 把这个删掉试试

**Comment by xgj1988** [comment]
@chenshuai2144  删了，报这个错。
Failed to update theme ParseError: Unrecognised input in http://localhost:8000/color.less on line 1, column 1: 1 <!DOCTYPE html><html lang="en"><head> 2

**Comment by xgj1988** [comment]
@chenshuai2144  重启一样报这个错，而且样式依然是antd-pro\components\-common\-table\-basic-table-cellEdit

**Comment by xgj1988** [comment]
@zombieJ  我把我的 BasicTable的东西写在sandbox上面了。地址：https://codesandbox.io/s/1y28n9x16q
单独写了一些BasicTable.js。步骤如下:
1：你点删除，没有弹出Popconfirm。
2：注释掉150行，也就是this.handleRowClick(record);这句话，你发现可以点了。其实我这句话的目的就是单击某行的时候，给指定行加背景色。

**Comment by xgj1988** [comment]
@chenshuai2144 我用的umi是2.2.1。

**Comment by xgj1988** [comment]
@zombieJ   https://codesandbox.io/s/1y28n9x16q 这个能否肯一下，

**Comment by xgj1988** [comment]
@zombieJ   大神，。帮忙看看撒 https://codesandbox.io/s/1y28n9x16q

**Comment by zombieJ** [comment]
不太懂你的意思，不过如果你希望弹窗的话禁止冒泡就行。否则点击弹窗又触发了 setSelectedKey 使得子组件重新渲染，popup 就消掉了：https://codesandbox.io/s/qxmmvm5nj6

**Comment by xgj1988** [comment]
@zombieJ  谢谢
