### ISSUE TITLE
AutoComplete prevents form submit on enter key

### ISSUE THREAD

**Issue by florian-bd** [ant-design/ant-design#14544]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5yv32pr7y4)

### Steps to reproduce
Create an autocomplete in a form with a submit button. Enter something in the autocomplete and try to submit the form with the enter key.

### What is expected?
Form to be submitted

### What is actually happening?
Form is not submitted

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.4.2 |
| System | windows |
| Browser | Chrome |

**Comment by ztplz** [comment]
![untitled7](https://user-images.githubusercontent.com/17755202/51683623-3ebd8f80-2025-11e9-9e78-d5aa759435b3.gif)
It seems work fine for me, if I did something wrong, please correct me.

**Comment by florian-bd** [comment]
Yes, don't click the button, try pressing enter on your keyboard :)

**Comment by florian-bd** [comment]
If it helps, I investigated a bit, and I can reproduce the behavior in the rc-select component that is used underneath.

**Comment by zombieJ** [comment]
AutoComplete is like a Select instead of Input. Prevent submit is by purpose. Pls check #10861 for more info.

**Comment by florian-bd** [comment]
From a user point of view, it is an input so it should behave like an input.
Note that if you select an option of the autocomplete with the keyboard then when you press enter the form is submitted as expected. 
When you manually type an input then the submit doesn't work. That is the bug I am highlighting here.

**Comment by zombieJ** [comment]
Make sense. I think we should re-consider this.

**Comment by florian-bd** [comment]
So quick! Awesome job, thank you @zombieJ

**Comment by tychenjiajun** [comment]
Still not working as expected. When user want to submit a value that doesn't have any exactly matched option, it requires two `enter` to submit. https://codesandbox.io/s/jibenshiyong-antd4163-forked-q2puw
