### ISSUE TITLE
Fixed Columns for Table allow users to see duplicate columns when scrolling horizontally

### ISSUE THREAD

**Issue by rynjwssl** [ant-design/ant-design#14545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/rynjwssl/pen/yZYVMK?editors=0010](https://codepen.io/rynjwssl/pen/yZYVMK?editors=0010)

### Steps to reproduce
If you scroll quickly horizontally, then you can see the contents of the fixed column that is in the scrollable table (below the fixed columns for z-index). This only happens on browsers that have elastic scrolling, so in Safari you will see this behavior as well as Chrome in Windows.

### What is expected?
It's a bit odd to display duplicate data on the table, so maybe if the user scrolls that far or that quickly it will only show blank space underneath the fixed columns? That would be a better experience than it is currently.

### What is actually happening?
The user can scroll beyond the edge of the table so the duplicate version of the fixed columns is visible underneath the actual fixed columns. Also, if you scroll far enough, hold your cursor in that position, and then move the cursor the table is actually stuck in that position. So the user can see the same column twice. I've included a screen recording and a screenshot below.

| Environment | Info |
|---|---|
| antd | 3.9.2 |
| React | 16.3.2 |
| System | MacOS 10.14.2 |
| Browser | 12.0.2 |

---
A screen recording of what this looks like on Safari on MacOS.
https://drive.google.com/file/d/16504N45jFsat7d_5C4vtTDm4WIW84LqL/view?usp=sharing

A screenshot of what this looks like on Chrome for Windows.
https://drive.google.com/file/d/17vuVs9YA8ypaAU_fgX8zkCXiaJG4ciCC/view?usp=sharing

**Comment by zombieJ** [comment]
nice catch!

**Comment by zenoven** [comment]
this fix caused the table style not right, see this screenshot
![image](https://user-images.githubusercontent.com/1305982/52986185-d4381d80-3431-11e9-80e2-f4fc48d9bfd1.png)

**Comment by zombieJ** [comment]
@zenoven could you help to provide an online reproduce?

**Comment by knightf** [comment]
this fix causes bug
https://codepen.io/knightf-the-decoder/pen/LqaJeP?editors=0010

**Comment by afc163** [comment]
@knightf https://codepen.io/afc163/pen/WPmgWJ?editors=0010

Don't fix all column width if table has flexible width to screen, leave one column **at least** to fit.
