### ISSUE TITLE
ant.design 网站速度很慢，看到ip 属于美国的

### ISSUE THREAD

**Issue by jason1004** [ant-design/ant-design#14546]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ant.design 网站速度很慢，看到ip 属于美国的 ，能不能加快中国访问速度

### What does the proposed API look like?
ant.design 网站速度很慢，看到ip 属于美国的 ，能不能加快中国访问速度

**Comment by haoxinjieFE** [comment]
+1, 感觉访问速度很慢, 国产 UI 为什么站点要放在美国 - -。

**Comment by zombieJ** [comment]
可以试试国内镜像哈：https://ant-design.gitee.io/

**Comment by qiuyanlong** [comment]
还是忘不了跪舔的日子。。不扔到美国怎么显示自己的高大上

**Comment by xrkffgg** [comment]
ant-design 国内镜像地址：https://github.com/ant-design/ant-design/issues/25661
