### ISSUE TITLE
3.12版本以后,组件(如Input, Select等)的属性prefixCls没有了

### ISSUE THREAD

**Issue by nuaajiangteng** [ant-design/ant-design#14549]
3.12版本以后,组件(如Input, Select等)的属性prefixCls没有了
![1](https://user-images.githubusercontent.com/29668874/51729227-be8f3c80-20ad-11e9-8902-016dbabc29a3.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14287#issuecomment-457471635
