### ISSUE TITLE
Component Transfer - left window don't refresh when reset the dataSource props

### ISSUE THREAD

**Issue by DarkDance** [ant-design/ant-design#14543]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8k50voo6x0)

### Steps to reproduce
1. click button "add one to left", and nothing appear
2. choose one item and click ">"
3. you can see a new item add to left

### What is expected?
after step 1,  can see the new item

### What is actually happening?
after step 2, the new item can see

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7.0 |
| System | win7 |
| Browser | Google Chrome 70.0.3538.110 |

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51726221-3d31ad00-20a1-11e9-92bd-9d65d340a537.png)
Please clone a new list.
