### ISSUE TITLE
Warning: Unknown props `directory`, `webkitdirectory` on <input> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

### ISSUE THREAD

**Issue by linzixi31** [ant-design/ant-design#14551]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
已打开页面就报警告，可以不要升级react解决它吗

### What is expected?
不升级react no wanning

### What is actually happening?
wanning

| Environment | Info |
|---|---|
| antd | 3.9.2 |
| React | 15.4.1 |
| System | windows |
| Browser | Google Chrome 65.0.3325.181 |

**Comment by zombieJ** [comment]
不升级做不到啊亲，这个是老版 React 报的 warning。如果不想升级，那你只能假装看不到它了……
