### ISSUE TITLE
Table组件，树形数据层级超过3层时，表格渲染特别卡

### ISSUE THREAD

**Issue by NexxLuo** [ant-design/ant-design#14554]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/474zpj1x7)

### Steps to reproduce
打开上述链接codesandbox，点击展开表格第4行，会明显发现存在较长时间的卡顿

### What is expected?
能够流畅展开子级

### What is actually happening?
展开极其卡顿

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | latest |
| System | windows 10 |
| Browser | Google 71.0.3578.98 |

---
就目前情况来看，一旦层级过多，会导致整个table的再次render变得极其慢。

**Comment by afc163** [comment]
本质上是 #3789 问题，但是这个可以 case by case 看一下。

**Comment by dazhi007** [comment]
确实有这个问题，我们用 table 树形加载一个省市区 可以进行三级展开， 就 非常的卡顿，不知道哪里要处理一下

**Comment by zoxiyo** [comment]
> 确实有这个问题，我们用 table 树形加载一个省市区 可以进行三级展开， 就 非常的卡顿，不知道哪里要处理一下

我们也遇到了这个问题。期待有解决

**Comment by afc163** [comment]
合并到 https://github.com/ant-design/ant-design/issues/32987
