### ISSUE TITLE
官网更新api

### ISSUE THREAD

**Issue by INTMIN** [ant-design/ant-design#14561]
antd官网更新组件为什么我本地也会受到影响，，第三次了，第一次是圣诞节彩蛋，第二次是row的api更新，现在table组件结构都改了我这边项目怎么维护啊，我项目安装的不是最新的antd只是3.3版本的
---

。

**Comment by zombieJ** [comment]
你看一下项目是不是加入了多份 antd，3.3.x 的 rc-table 是 6.1.x。不会自动升级的: https://unpkg.com/antd@3.3.0/package.json
```json
{
  "//": "...",
  "dependencies": {
    "//": "...",
    "rc-table": "~6.1.0"
  }
}
```

**Comment by afc163** [comment]
估计是不知道语义化版本的意义：https://www.jianshu.com/p/d306ed03de62

**Comment by INTMIN** [comment]
{
  "name": "ant-design-pro",
  "version": "1.3.0",
  "description": "An out-of-box UI solution for enterprise applications",
  "private": true,
  "scripts": {
    "precommit": "npm run lint-staged",
    "start": "cross-env ESLINT=none NO_PROXY=true roadhog server",
    "start:no-proxy": "cross-env NO_PROXY=true ESLINT=none roadhog dev",
    "build": "cross-env ESLINT=none roadhog build",
    "site": "roadhog-api-doc static && gh-pages -d dist",
    "analyze": "cross-env ANALYZE=true roadhog build",
    "lint:style": "stylelint \"src/**/*.less\" --syntax less",
    "lint": "eslint --ext .js src mock tests && npm run lint:style",
    "lint:fix": "eslint --fix --ext .js src mock tests && npm run lint:style",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js",
    "test": "roadhog test",
    "test:component": "roadhog test ./src/components",
    "test:all": "node ./tests/run-tests.js",
    "prettier": "prettier --write ./src/**/**/**/*"
  },
  "dependencies": {
    "@antv/data-set": "^0.8.0",
    "@babel/polyfill": "^7.0.0-beta.36",
    "antd": "^3.3.0",
    "babel-runtime": "^6.9.2",
    "bizcharts": "^3.1.3-beta.1",
    "bizcharts-plugin-slider": "^2.0.1",
    "classnames": "^2.2.5",
    "dva": "^2.1.0",
    "dva-loading": "^1.0.4",
    "enquire-js": "^0.2.1",
    "lodash": "^4.17.4",
    "lodash-decorators": "^4.4.1",
    "moment": "^2.19.1",
    "numeral": "^2.0.6",
    "omit.js": "^1.0.0",
    "path-to-regexp": "^2.1.0",
    "prop-types": "^15.5.10",
    "qs": "^6.5.0",
    "rc-drawer-menu": "^0.5.0",
    "react": "^16.2.0",
    "react-container-query": "^0.9.1",
    "react-document-title": "^2.0.3",
    "react-dom": "^16.2.0",
    "react-fittext": "^1.0.0",
    "rollbar": "^2.3.4",
    "url-polyfill": "^1.0.10"
  },
  "devDependencies": {
    "babel-eslint": "^8.1.2",
    "babel-plugin-dva-hmr": "^0.4.1",
    "babel-plugin-import": "^1.6.7",
    "babel-plugin-module-resolver": "^3.1.1",
    "cross-env": "^5.1.1",
    "cross-port-killer": "^1.0.1",
    "enzyme": "^3.1.0",
    "eslint": "^4.14.0",
    "eslint-config-airbnb": "^16.0.0",
    "eslint-plugin-babel": "^4.0.0",
    "eslint-plugin-compat": "^2.1.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-markdown": "^1.0.0-beta.6",
    "eslint-plugin-react": "^7.0.1",
    "eslint-config-prettier": "^2.9.0",
    "gh-pages": "^1.0.0",
    "husky": "^0.14.3",
    "lint-staged": "^6.0.0",
    "mockjs": "^1.0.1-beta3",
    "prettier": "1.11.1",
    "pro-download": "^1.0.1",
    "redbox-react": "^1.5.0",
    "regenerator-runtime": "^0.11.1",
    "roadhog": "^2.3.0",
    "roadhog-api-doc": "^1.0.0",
    "stylelint": "^8.4.0",
    "stylelint-config-prettier": "^3.0.4",
    "stylelint-config-standard": "^18.0.0"
  },
  "optionalDependencies": {
    "puppeteer": "^1.1.1"
  },
  "lint-staged": {
    "**/*.{js,jsx,less}": [
      "prettier --wirter",
      "git add"
    ],
    "**/*.{js,jsx}": "lint-staged:js",
    "**/*.less": "stylelint --syntax less"
  },
  "engines": {
    "node": ">=8.0.0"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ]
}
@zombieJ 这个是我的文件，但是里面没有引入这个东西

**Comment by afc163** [comment]
@INTMIN 阅读下这个吧 https://www.jianshu.com/p/d306ed03de62

https://semver.npmjs.com/

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/507615/52040577-d1ed4c80-2572-11e9-8597-f715f5390154.png">
