### ISSUE TITLE
bottom sheet

### ISSUE THREAD

**Issue by zachguo** [ant-design/ant-design#1456]
Are you interested in adding a `bottom sheet` component? See [an example here](https://material.angularjs.org/latest/demo/bottomSheet).

I guess it's not too hard to implement using `rc-dialog`. I'm happy to work on it, but I need some directions.

**Comment by warmhug** [comment]
see http://react-component.github.io/m-picker/examples/popup.html ant it's style https://github.com/react-component/m-picker/blob/master/assets/popup.less#L76

**Comment by afc163** [comment]
Will do it in antd-mobile, it is not open yet.
