### ISSUE TITLE
input组件allowClear属性设置报错

### ISSUE THREAD

**Issue by lx544690189** [ant-design/ant-design#14576]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
示例“带移除图标”，随便输入任意内容报错

### What is expected?
出现清除按钮

### What is actually happening?
页面demo报错

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | react |
| System | windows |
| Browser | chrome71.0.3578.98 |

**Comment by zombieJ** [comment]
试了一下是 '@sentry/browser' 的错误，去除 sentry 相关代码就好了。 @afc163

**Comment by ztplz** [comment]
有bug  要改成受控组件

**Comment by ztplz** [comment]
不是这个原因   它没法直接识别input  需要用函数包裹
