### ISSUE TITLE
Using Menu inside Dropdown renders with very large rows when not root element

### ISSUE THREAD

**Issue by aryzing** [ant-design/ant-design#14578]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x3ny60xl8p)

### Steps to reproduce
Have a root element other than Menu in the overlay component

### What is expected?
Items in menu should keep their spacing regardless of position of dom elements

### What is actually happening?
The vertical spacing is incorrectly set and the background hover effect is gone

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | react 16.5.2 |
| System | Ubuntu |
| Browser | Chrome 71 |

**Comment by zombieJ** [comment]
Dropdown provides the style of inner menu. If you want to use non-menu element, you should customize style also: https://codesandbox.io/s/8rqky8z32
