### ISSUE TITLE
Form.create 与 Modal 组合 在React 15.0.0 中存在一个警告问题

### ISSUE THREAD

**Issue by yxqme** [ant-design/ant-design#1457]
重现演示： http://codepen.io/yxqme/pen/xVzXPE/?editors=0010

调试工具显示载图：

![image](https://cloud.githubusercontent.com/assets/5998046/14661425/1e849eb8-06e0-11e6-8793-2b09e70399ab.png)

**Comment by afc163** [comment]
duplicate #1340
