### ISSUE TITLE
表格当数据只有一行的时候，行内select下拉列显示不完整

### ISSUE THREAD

**Issue by syaivin** [ant-design/ant-design#14571]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
表格，一行数据，行内使用select组件

### What is expected?
点击 select下拉时正常显示
![aaaaaa](https://user-images.githubusercontent.com/13479047/51783739-69b8f800-2179-11e9-8cf7-f2938e3ff93b.png)

### What is actually happening?
设置表格横向滚动条，表格行数据 没有select下拉组件数据过多时，只显示部分其它的被隐藏了
![111](https://user-images.githubusercontent.com/13479047/51783698-cb2c9700-2178-11e9-951f-3c552eb93952.png)
![wwwwww](https://user-images.githubusercontent.com/13479047/51783801-3b87e800-217a-11e9-9967-7df883dff40c.png)

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | ^16.7.0 |
| System | windows7旗舰版 |
| Browser | Google Chrome 版本 68.0.3440.84（正式版本） |

**Comment by zombieJ** [comment]
是不是设置了 getPopupContainer？正常用是不会被挡住的：https://codesandbox.io/s/7mwnr2p4vj

**Comment by syaivin** [comment]
@zombieJ  是的，如果不设置getPopupContainer个属性，拉动滚动条的时候下拉列定在那不跟随滚动条走；很奇怪，客户跟测试都有提这个问题，查官网只能加这个属性，可是加了这个属性又存在新的问题，如这个问题单这类的~

**Comment by zombieJ** [comment]
这其实就是一个选择问题，你希望是让弹窗放在什么元素内。默认是在 body 最后，设置 getPopupContainer 后就改为你设定的元素内。而由于放的 scroll Table 是 overflow auto 的样式使得弹窗不能超出容器。
你可以选择：
* 还是不设置 getPopupContainer 让它放外面
* 考虑去掉 Table 的 scroll 属性
* 或者监听 onScroll，通过 Select ref 的 `forcePopupAlign` 强制刷新弹窗位置（不推荐）

**Comment by syaivin** [comment]
@zombieJ 项目表格的列很多，如果去掉滚动，其它字段列就显示不了了
![qq 20190129121328](https://user-images.githubusercontent.com/13479047/51883854-c4439580-23bf-11e9-9c30-84b85710aba5.jpg)

**Comment by syaivin** [comment]
@zombieJ 项目表格的列很多，如果去掉滚动，其它字段列就显示不了了
![qq 20190129121533](https://user-images.githubusercontent.com/13479047/51883924-0e2c7b80-23c0-11e9-886e-5f3bc31f47b5.jpg)

**Comment by syaivin** [comment]
@zombieJ @afc163 好的，谢谢你们帮忙；预祝：春节愉快，合家欢乐~
