### ISSUE TITLE
Improve Api for expandIconAsCell prop in <Table/>

### ISSUE THREAD

**Issue by SergeyVolynkin** [ant-design/ant-design#14580]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Control render of the "Expand icon" in `<Table/>` "Row"

### What does the proposed API look like?
```
<Table
    expandIconAsCell={record => {
        const renderExpandIcon = /* some calc based on "record"*/
        return renderExpandIcon
    }
}
/>
```

**Comment by SergeyVolynkin** [comment]
Btw: `expandIconAsCell ` is not described in the docs

**Comment by SergeyVolynkin** [comment]
I know that `expandIcon` prop can be used to render a `null` in place of the icon.
But it still appears as an empty `<td/>` and takes place

**Comment by zombieJ** [comment]
You can combine them: https://codesandbox.io/s/j4z5zmom09

**Comment by zombieJ** [comment]
props contains the record info: https://codesandbox.io/s/qvp737m8jq
