### ISSUE TITLE
Option to hide Select All checkbox from the table head

### ISSUE THREAD

**Issue by nitinsh99** [ant-design/ant-design#14581]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to show the select checkboxes for each row but DO NOT want to show the select all checkbox. There should be a flag for that.

### What does the proposed API look like?
`rowSelection : {
hideSelectAllCheckbox : true
}
`

**Comment by littlefinger42** [comment]
Why has this been closed? The suggested parameter doesn't do what @nitinsh99 is asking.

Could this issue be reopened? @afc163

**Comment by hugobarragon** [comment]
> Try `hideDefaultSelections`

Hi @afc163 that prop does not work :/

**Comment by shobhitnpm** [comment]
Is There any option to hide Select All CheckBox in antd

**Comment by shobhitnpm** [comment]
hideDefaultSelections does not work.

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by Kermit-Xuan** [comment]
@afc163 我看了`hideDefaultSelections`这个属性没有用到，我想问下这个属性是用来隐藏默认的`Checkbox`么？因为我把这个`Checkbox`隐藏后，当存在自定义`selections`时，`title`那就剩了一个展开箭头
![image](https://user-images.githubusercontent.com/33770367/83244778-5fc26180-a1d2-11ea-9c99-5864b1efb7c3.png)

**Comment by afc163** [comment]
对比一下 3.x，4.x 可能是 bug。

**Comment by Kermit-Xuan** [comment]
3.x是这样的，默认后面的下拉框中会有两个选项，分别为全选和取消全选，指定`hideDefaultSelections`后默认就不会有这两个选项，4.0后如果需要在下拉框中指定全选或取消全选需要用户自己显式的通过`SELECTION_ALL`和`SELECTION_INVERT`在`selections`中定义，因此`hideDefaultSelections`就失效了，至于说的隐藏默认全选的`Checkbox`功能一直都没有。

**Comment by Kermit-Xuan** [comment]
可以考虑添加`hideSelectAll`选项

**Comment by afc163** [comment]
1. 可以添加一个 `rowSelection : { hideSelectAll: boolean } `，用于把顶部的 checkbox 和下拉箭头都干掉。
2. `hideDefaultSelections` v4 之后应该没用了，需要更新一下文档和 TS 定义。

**Comment by hasan-shafiq-ivolve** [comment]
is there any option to hide selectAll checkbox

**Comment by JuanDiegoTissini** [comment]
Is Easy , just need to edit the ant de
<img width="318" alt="2020-12-04 12_24_14-EditUsers vue - lcv2 - Visual Studio Code" src="https://user-images.githubusercontent.com/72483437/101194227-b306e800-362b-11eb-9ba9-fe22363a699a.png">
sign styles classes

**Comment by markus-roe** [comment]
`.ant-table-thead tr .ant-table-selection-column div {
  display: none;
}`
