### ISSUE TITLE
[Tooltip] Popover is displayed in the wrong direction when title is long text

### ISSUE THREAD

**Issue by orzyyyy** [ant-design/ant-design#14582]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2woymyk6z0)

### Steps to reproduce
Hover the two images and observe the Popover display direction.
![demo](https://user-images.githubusercontent.com/24520193/51796593-c972da00-2231-11e9-9928-415b1802a1cb.gif)

### What is expected?
Popover displays in correct direction

### What is actually happening?
As title

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7 |
| System | windows 10 |
| Browser | chrome 71.0.3578.98 |

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51797880-a18d7180-2245-11e9-9cf2-7faf09cfc23a.png)
Set position to `bottom`.

**Comment by ztplz** [comment]
`dom-align`的逻辑错了，我改改

**Comment by afc163** [comment]
4.0 still has this bug.

**Comment by afc163** [comment]
This issue don't exist in 4.6.2 now, closing.
