### ISSUE TITLE
Need key validation in table column

### ISSUE THREAD

**Issue by adamsaparudin** [ant-design/ant-design#14585]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rw1o5qn4mn)

### Steps to reproduce
When I try to put integer value in key column, it's still display the data and no error. But filter not working with integer key, they should be string

### What is expected?
Show warning or error

### What is actually happening?
No warning or error

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.4.2 |
| System | Mac OS 10.14 (Mojave) |
| Browser | Chrome |

**Comment by ycjcl868** [comment]
You can make the `Input` controlled component, then use `Form` to validate the input value

**Comment by zombieJ** [comment]
Could you help to update sample code since it works fine:
![kapture 2019-01-28 at 10 05 00](https://user-images.githubusercontent.com/5378891/51810675-4bbbd680-22e4-11e9-8b3b-3cefd95a6263.gif)

**Comment by zombieJ** [comment]
It's not related with `key`. It's caused by you render use `render: text => text`: https://codesandbox.io/s/20pjmn1lwr

If you don't want to filter rows instead of highlight, you should do the logic to filter on `this.state.data`.
