### ISSUE TITLE
Input组件作为登录输入框会暴露用户输入的信息

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#14592]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
Input组件作为登录页面的输入框，会暴露出value值，也就是用户输入的信息，如果用原生input框并不会出现这情况

### What is expected?
Input输入框组件不会暴露用户输入的value值

### What is actually happening?
Input输入框组件暴露用户输入的value值，用原生input框并不会出现这情况，如果用户信息都暴露出来了，那这样我加密跟后台约定密钥最后传给后台就没啥意义了

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

---
Input输入框组件不会暴露用户输入的value值

**Comment by ycjcl868** [comment]
因为组件是[受控](https://reactjs.org/docs/forms.html#controlled-components)的，不暴露 value，需要将组件变成不受控的。

![image](https://user-images.githubusercontent.com/13595509/51816791-330ee900-2303-11e9-8b11-ede645b4e66c.png)

**Comment by Mathround** [comment]
> 因为组件是[受控](https://reactjs.org/docs/forms.html#controlled-components)的，不需要暴露 value，将组件变成不受控的。
> 
> ![image](https://user-images.githubusercontent.com/13595509/51816791-330ee900-2303-11e9-8b11-ede645b4e66c.png)


> 因为组件是[受控](https://reactjs.org/docs/forms.html#controlled-components)的，不需要暴露 value，将组件变成不受控的。
> 
> ![image](https://user-images.githubusercontent.com/13595509/51816791-330ee900-2303-11e9-8b11-ede645b4e66c.png)

亲 可以把demo链接发一下吗？我按照你要求写，还是会有value值暴露出来

**Comment by afc163** [comment]
这应该是 react 底层机制问题：https://github.com/facebook/react/issues/11896

有望在未来被重写：https://github.com/facebook/react/issues/13525

**Comment by Mathround** [comment]
> 这应该是 react 底层机制问题：[facebook/react#11896](https://github.com/facebook/react/issues/11896)
> 
> 有望在未来被重写：[facebook/react#13525](https://github.com/facebook/react/issues/13525)

为啥我用原生的input就正常呢？

**Comment by ztplz** [comment]
你能说一下在什么情况下受控组件会有危险吗

**Comment by dyyliao123** [comment]
这个有解决吗

**Comment by ztplz** [comment]
@dyyliao123   https://github.com/facebook/react/milestone/40   `millstone` in react 17.
