### ISSUE TITLE
tree-select 位于页面底部时，输入框输入中文的第一个字母会直接上屏，无法输入中文

### ISSUE THREAD

**Issue by zhrln** [ant-design/ant-design#14594]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zhrln/full/exZoGN#注意：IE11无法预览](https://codepen.io/zhrln/full/exZoGN#注意：IE11无法预览)

### Steps to reproduce
1）IE11下打开，把控件置于页面底部
2）点击下拉框，点击下拉菜单里的输入框
3）切换到中文输入法，随便输入一个拼音字母
问题复现，IE下输入法里的字母直接上屏，无法输入中文

### What is expected?
输入法不受影响

### What is actually happening?
IE下输入法里的字母直接上屏，无法输入中文

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7.0 |
| System | Windows 10 |
| Browser | IE 11.0.10240.16384 |

**Comment by zombieJ** [comment]
没太明白，能给个 gif 看看不？

**Comment by zhrln** [comment]
复现步骤：
1）移除官网 DEMO 上多余的 DOM 元素，使组件位于页面最底部（非屏幕最底部，使下拉菜单位于组件上方）
2）切换为中文输入法
3）在筛选输入框中输入拼音，问题复现

问题：
1）输入第一个拼音字母直接上屏，导致拼音输入失败
2）后续输入拼音如果不在列表里则也直接上屏，拼音输入失败

Win 10，IE 11，微软拼音输入法

![bug](https://user-images.githubusercontent.com/3120649/52685981-bcbae980-2f86-11e9-8723-20100eb8c28e.gif)

**Comment by zombieJ** [comment]
需要在 rc-align 里判断一下游览器版本，如果是 IE 时。在 align 前记录一下 activeElement 是不是在需要 align 的 element 内，是的话 align 后恢复一下 focus。
（推测会有副作用……）

**Comment by zhrln** [comment]
@zombieJ 貌似还没有解决 IE 下无法输入汉字的问题？本地版本 ：3.13.6

**Comment by zombieJ** [comment]
IE 在元素重新对齐浮动时会失去焦点，这边只能强行把焦点设置回来。所以会有第一个拼音丢失输入法状态的情况。这个只能尽量保持 input 可以 focus 让用户输入，没有特别好的解决第一个字重新浮动的方法。

**Comment by zhrln** [comment]
> IE 在元素重新对齐浮动时会失去焦点，这边只能强行把焦点设置回来。所以会有第一个拼音丢失输入法状态的情况。这个只能尽量保持 input 可以 focus 让用户输入，没有特别好的解决第一个字重新浮动的方法。

好的，多谢答复
