### ISSUE TITLE
Updating src prop for Avatar not effective after image load error

### ISSUE THREAD

**Issue by AhmedAlSammany** [ant-design/ant-design#14605]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wqq60xw617)

### Steps to reproduce
1- Set src prop for Avatar to a url that fails to load (URL_A)
2- Set src prop to a proper image url (URL_B)

### What is expected?
Image of URL_B should be loaded in the Avatar component

### What is actually happening?
Avatar not showing image of URL_B

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | react: 16.7 |
| System | macOS 10.14.2 |
| Browser | chrome: 71.0.3578.98 |

---
The bug is that the Avatar component state 'isImgExist' is not reset to 'true' on the src prop update

**Comment by ycjcl868** [comment]
Thanks for your PR, maybe you can add some test cases.
