### ISSUE TITLE
动态增减表单项中codepen的demo和预期结果不符

### ISSUE THREAD

**Issue by EthanOrange** [ant-design/ant-design#14613]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zkzy2856rx)

### Steps to reproduce
点击 add field 然后完成必填项 提交表单，查看console，names第一位永远是一个empty

### What is expected?
和document一样 正常取值
[1, 2, 3]

### What is actually happening?
[ empty, 1, 2, 3]

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7 |
| System | mac 10.14.2 |
| Browser | 71.0.3578.98 |

**Comment by ycjcl868** [comment]
```diff
-    const nextKeys = keys.concat(++id);
+    const nextKeys = keys.concat(id++);
```

**Comment by EthanOrange** [comment]
@ycjcl868 thanks rep
