### ISSUE TITLE
Could not resolve host: new-issue.ant.design

### ISSUE THREAD

**Issue by atav32** [ant-design/ant-design#14611]
Trying to use http://new-issue.ant.design but can't connect to the site

<img width="771" alt="screen shot 2019-01-28 at 5 34 40 pm" src="https://user-images.githubusercontent.com/622185/51878080-47fb7480-2323-11e9-9fa0-84a68fcdae22.png">

```
atav@home:~/code> curl http://new-issue.ant.design
curl: (6) Could not resolve host: new-issue.ant.design
```

---

The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by atav32** [comment]
@afc163 it's kinda hard to create an issue correctly if the issue creator is down 😆

**Comment by atav32** [comment]
Double-checking my DNS settings, cause other services say the site is up

<img width="586" alt="screen shot 2019-01-28 at 5 43 05 pm" src="https://user-images.githubusercontent.com/622185/51878399-61e98700-2324-11e9-926c-3feaf39498a1.png">

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/51878858-22667d80-23ac-11e9-9275-6accbb4e1a5b.png)
![image](https://user-images.githubusercontent.com/17755202/51878883-49bd4a80-23ac-11e9-8852-bf07da33ba77.png)
It's work for me.
