### ISSUE TITLE
Request Icon Provider

### ISSUE THREAD

**Issue by kimochg** [ant-design/ant-design#14629]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Personally, it's too trivial to send prs for every icon customization. Especially, antd starts injecting a config-provider, how about a brand new **icon-provider** come into rescue. The philosophy is same with other providers, if none icon setting, default Ant-Icon should be used, if custom icon injected, thus custom icon should be used, another benefit is to support different ways to use icons (svg, custom icon component).

### What does the proposed API look like?
1. svg

```jsx
<IconProvider
  svgSpritePath="/assets/icons"
>
   <IconConsume
       category="utility"
       name="check"
   />
</IconProvider>
```

This should render a checkmark with svg icon

2. custom icons

```jsx
<IconProvider
  icons={
    select: { clear: <MyClearIcon /> }
  }
>
    <AntSelect />
</IconProvider>
```

This should render Antd Select with our custom clear icon

**Comment by afc163** [comment]
I think you should create HOC Select and other components to use for better customization.

**Comment by kimochg** [comment]
@afc163 The point of this issue is not such simple. The capacity of icon customization in antd’s compoenent is not satisfied. I’d like to use antd’s select for an example here. We have suffix icon now, but it’s not so easy for custom, because developers need handle whether it renders loading/arrow/custom icon. IconProvider aims to provide a better way to custom the icons for the specified purpose. Pass `icon: { loading: <Myspinner /> }` to select should be easier to just change the loading icon which is irrelavant to business logic. Btw, the inner implementation in most component doesn’t take custom all icons into consideration.(Most clear/remove icon has not been exposed an props to take care now)
