### ISSUE TITLE
simple Pagination 当前页码指定不生效

### ISSUE THREAD

**Issue by shpfli** [ant-design/ant-design#1462]
If you are going to report a bug, please answer the following questions, thank you!

## What you did

这是我写的组件的构造方法片段：
```
  constructor(props) {
    super(props);
   
    this.state = {
        pageIndex: 0,
        pageSize: PAGE_SIZE,
        totalCount: 0,
        records: []
    };
}
```

这是我写的组件的render方法片段：
```
<Pagination simple current={this.state.pageIndex} pageSize={this.state.pageSize}  total={this.state.totalCount} showQuickJumper="false"/>
```
```
componentDIdMount(){
 this.setState({
    current:10,
    totalCount:100
});
}
```

## What you would like to happen
页面初次渲染的时候，数据未加载，我随意指定了当前页码。我希望数据加载后，根据返回的数据确定当前页码。在未指定Pagination的simple属性之前，一切正常。

## What actually happened
但是，一旦在Pagination中加上simple属性，则无法通过this.setState改变当前页码，并且无论我是否显示的指定 showQuickJumper="false"，当前页码都是个输入框，可编辑。

例如上面的代码片段中，实际运行结果页码显示为：”0/10“，0是可编辑状态

## Environment Information
antd版本：
    "antd": "0.12.x",
    "atool-build": "0.6.x",
System：windows 7 64位
浏览器：chrome

**Comment by ibigbug** [comment]
收到

**Comment by benjycui** [comment]
```jsx
```

**Comment by afc163** [comment]
pageIndex current
@shpfli 确认下是否写对了。

**Comment by shpfli** [comment]
@benjycui @afc163 
这个是我在简化的代码用于粘贴的时候写错的。不关这个事。

很明显的区别就是，我去掉simple一切正常，加上simple，立马出现上面的问题。

**Comment by shpfli** [comment]
改成下面之后，问题依旧存在
```
componentDIdMount(){
 this.setState({
    pageIndex:10,
    totalCount:100
});
}
```

**Comment by ibigbug** [comment]
Did 单词拼错了。

http://codepen.io/ibigbug/pen/XdBJRP?editors=001#anon-login

**Comment by ibigbug** [comment]
先关闭了，有问题欢迎再提出。

**Comment by benjycui** [comment]
感觉可以写个拼写检查工具，文件修改时自动检查对应的 API 是否拼写正确 😅

**Comment by shpfli** [comment]
@ibigbug 谢谢您。

刚看了你的示例代码，确实是正常的。不过showQuickJumper="false"也没有生效，当前页码依然可编辑。showQuickJumper="false"showQuickJumper="false"

**Comment by shpfli** [comment]
@ibigbug 我在本地单独写的测试例子也是正常的了。但项目中的该问题仍然存在，拼写没有错。所以应该是项目环境的问题

我注意到有很多ant design默认的css样式被人修改了，所以我怀疑问题可能在此。
