### ISSUE TITLE
Select组件中dropdownRender方法有问题，在额外元素上加的onClick()事件不生效！！

### ISSUE THREAD

**Issue by GroupOfStar** [ant-design/ant-design#14639]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mq6q360kqyhttps://codesandbox.io/embed/mq6q360kqy?expanddevtools=1)

### 问题描述

Antd `<Select />` 组件中通过`dropdownRender`自定义下拉框内容后，在额外元素上加上的`onClick()`事件无效果，或者说不灵敏（点击`10`次可能会生效一次）。

### 问题出现的环境背景及自己尝试过哪些方法

**背景（需求场景）：**

有时候在使用下拉框组件选择的时候，如果没有想要的选择，可以在最下面友好的加上一个`添加`按钮去新建数据，如下图所示：

![_20190130142643](https://user-images.githubusercontent.com/28132535/51966028-5f169f80-24a6-11e9-9546-83a8534a17fe.png)

**尝试过的方法：**

1. 看到了API中的`dropdownRender`接收的方法有第二个参数props`(menuNode: ReactNode, props) => ReactNode`，尝试使用后发现一个奇葩的解决方法：必须要在元素里添加以下多余的代码`console.log()`才生效，如下
2. 考虑过把额外的元素写在一个函数组件里并传props；阻止时间冒泡；查看API中是否有之前属性可以控制等等，都不行。
3. **猜想**可能是点击时，除非点击某一`Option `选项，点击其他地方都是调用的隐藏下拉框的事件，也就是说下拉框的隐藏事件阻止了自己写的事件，那就怎么办呢？？。

```diff
// 使用第二个参数props
dropdownRender={(ReactNode, props) => (
 <div>
   {ReactNode}
+  {console.log('props: ', props)}
   <Divider style={{ margin: '4px 0' }} />
   ...
 </div>)
```

### 相关代码

```javascript
<Select 
    defaultValue="lucy"
    dropdownRender={(ReactNode, props) => (
      <div>
        {ReactNode}
        <Divider style={{ margin: '4px 0' }} />
        <div 
        style={{ padding: '8px', cursor: 'pointer' }}
        onClick={()=> {
          console.log('Add item onClick()...')
        }}
        >
          <Icon type="plus" /> Add item
        </div>
      </div>
    )}
  >
    <Option value="jack">Jack</Option>
    <Option value="lucy">Lucy</Option>
  </Select>
````

**也可以在线尝试我写的[Demo](https://codesandbox.io/embed/mq6q360kqy?expanddevtools=1)：**

[![Edit mq6q360kqy](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/mq6q360kqy?expanddevtools=1)

### What is expected?

`<Select />`组件中的`dropdownRender`方法里可以写`onClick()`事件。

### What is actually happening?

在额外元素上加上的`onClick()`事件无效果，或者说不灵敏（点击`10`次可能会生效一次）。

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | v16.6.3 |
| System | 最新 |
| Browser | Google Chrome 版本 70.0.3538.110（正式版本） （64 位） |

业务场景：有时候在使用下拉框组件选择的时候，如果没有想要的选择，可以在最下面友好的加上一个`添加`按钮去新建数据。

**Comment by yoyo837** [comment]
临时方案：内部容器添加一个
```
onMouseDown={e => {
    e.preventDefault();
}}
```

See #13504

**Comment by GroupOfStar** [comment]
@yoyo837  OK，暂时解决了我的问题，谢谢！
