### ISSUE TITLE
Dropdown下拉菜单 多级菜单显示子菜单时闪烁

### ISSUE THREAD

**Issue by zlh1234** [ant-design/ant-design#14638]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown-cn/#](https://ant.design/components/dropdown-cn/#)

### Steps to reproduce
划入多级菜单查看子菜单

### What is expected?
解决

### What is actually happening?
解决

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7.0 |
| System | win7 |
| Browser | 71.0.3578.80 |

---
Dropdown下拉菜单 多级菜单显示子菜单时闪烁

**Comment by MrBoolean** [comment]
划入多级菜单查看子菜单

**Comment by MrBoolean** [comment]
划入多级菜单查看子菜单?

**Comment by zombieJ** [comment]
debug 了一下，应该是 css-animation 填加 className 后 rc-align 重新定位后导致重绘了，在 enter 里额外加个 opacity 来强制设置为 0 应该就行了:
```
>>>>>>> Render: false
Trigger Render: ant-dropdown-menu-submenu-title false
Trigger Popup: false
Animate render:
Trigger Render: ant-dropdown-menu-item false
>>>>>>> Render: false
Trigger Render: ant-dropdown-menu-submenu-title false
Trigger Popup: false
Animate render:
>>>>>>> Render: true
Trigger Render: ant-dropdown-menu-submenu-title true
Trigger Popup: true
Animate render:
Trigger Render: ant-dropdown-menu-item false
Add: zoom-big-enter
Align: do align!
CSS_ANI Add: zoom-big-enter-active
CSS_ANI Remove: zoom-big-enter zoom-big-enter-active
```
