### ISSUE TITLE
Table Components: Edit data failed when using "Editable Rows" and "Fixed columns" mixed

### ISSUE THREAD

**Issue by Candieslove** [ant-design/ant-design#14634]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://9yvp6r1x1y.codesandbox.io/)

### Steps to reproduce
1. Click the "edit" button;
2. Modify any one data in the table;
3. Save the modification.

### What is expected?
Edit data successfully

### What is actually happening?
Edit data failed

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7.0 |
| System | windows 7 |
| Browser | chrome 62.0.3202.89 |

**Comment by afc163** [comment]
Editable row is not compatibility with fixed columns now, don't use it this way.

**Comment by alexhawkins** [comment]
@afc163 Will this feature be supported in the future? I have huge tables that use in-place editing where this feature would be extremely beneficial to the user. See attached 
<img width="2015" alt="Screen Shot 2019-03-13 at 3 53 39 PM" src="https://user-images.githubusercontent.com/5912301/54265674-6c946e80-45a8-11e9-83aa-aedd1e002878.png">

**Comment by afc163** [comment]
Could you help us to make it happen? Cause we are short of hands now.

**Comment by alexhawkins** [comment]
@afc163 I can try, I just have so much work going on right now with work. Where would you recommend I begin? What do you think the main issue is? I'm actually quite new to ANT Design, was previously using Material Design but Ant is vastly superior so I made the switch. Great job so far!! Keep up the excellent work!!

**Comment by zombieJ** [comment]
update demo on this #15475
