### ISSUE TITLE
body background 自定义颜色无效

### ISSUE THREAD

**Issue by beeant0512** [ant-design/ant-design#14635]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
自定义主题 `'body-background': '#f0f2f5'`,
结果 body的backgroud 还是 `#fff`,
查找源码 发现在common.less中 body的`background: #fff;`写死的

### What is expected?
body background可自定义

### What is actually happening?
body background可自定义

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7.0 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
antd 源码中好像没有 `common.less`。
