### ISSUE TITLE
Table 使用useFixedHeader后可以不设置列的宽度吗？因为表头以及列表的内容都是动态生成的呢

### ISSUE THREAD

**Issue by Sunzhuoyi** [ant-design/ant-design#1463]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

使用了表头固定属性

## What you would like to happen

希望可以不设置列的宽度，因为表头和内容都是动态生成的

## What actually happened

不设置宽度表头和内容就无法对齐，但是动态内容不好为每一列设置宽度

## Online demo

(e.g. http://codepen.io/anon/pen/dMdjeo?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
宽度也可以动态根据内容设置吧，目前没有优雅的方式，抱歉。
