### ISSUE TITLE
Affix is missing className prop (among others)

### ISSUE THREAD

**Issue by wbobeirne** [ant-design/ant-design#14649]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/affix/](https://ant.design/components/affix/)

### Steps to reproduce
* Import the Affix component in Typescript
* Render it with a className prop
* Confirm you get typescript error, despite Affix displaying the added class

### What is expected?
It shouldn't have a type error

### What is actually happening?
It shows a type error

| Environment | Info |
|---|---|
| antd | 3.9.3 |
| React | 16.5.2 |
| System | macOS |
| Browser | Chrome 71 |

---
Affix should either explicitly define commonly used div props such as className, or should extend the div component props since it's just doing an object spread.

**Comment by ycjcl868** [comment]
lack ts definition

![image](https://user-images.githubusercontent.com/13595509/52028457-11ec0980-254a-11e9-905d-8ade81c22de8.png)
