### ISSUE TITLE
[网站] Menu 弹出菜单 demo 部分被遮盖

### ISSUE THREAD

**Issue by superRaytin** [ant-design/ant-design#1464]
http://ant.design/components/menu/#demo-vertical

<img width="473" alt="qq20160420-1 2x" src="https://cloud.githubusercontent.com/assets/2723376/14675558/2acdc120-073c-11e6-9fbf-734293df1c84.png">

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/27e6460fde270495a18d5b097f187da6e72a078a

估计是这个导致的。

**Comment by superRaytin** [comment]
刚验证了下，确实是。

**Comment by YangZhouChaoFan** [comment]
我按照网站的例子，菜单有点问题。帮忙看看。**右哥**。
![image](https://cloud.githubusercontent.com/assets/13232941/14697765/a3e873c0-07b9-11e6-8a55-f3e2556959ac.png)
