### ISSUE TITLE
文本框通过浏览器AutoComplete选择或粘贴时失去焦点

### ISSUE THREAD

**Issue by cfk199244** [ant-design/ant-design#14657]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen我这边打不开，没法写](https://codepen我这边打不开，没法写)

### Steps to reproduce
项目去年使用3.73版本的antd.
其中大量使用了文本框的onBlur事件. 且粘贴内容或自动完成选中数据时，焦点都保留在文本框.

但是switch点击会报错, 搜索问题发现在3.84版本已修复，因此升级到3.84.

### What is expected?
粘贴内容或自动完成选中数据时，焦点都保留在文本框.

### What is actually happening?
升级后，在文本框中以上2个操作后，文本框都直接失去了焦点，且不触发onBlur事件，导致项目中大部分功能出问题.

| Environment | Info |
|---|---|
| antd | 3.8.4 |
| React | 16.2.0 |
| System | Win7 64 |
| Browser | Chrome |

**Comment by afc163** [comment]
You can try antd@3.13.0 first.

**Comment by cfk199244** [comment]
@afc163 不好意思耽误了你们时间，经过刚才一起讨论重新审查代码，发现是一位同事使用高阶组件封装了Input导致. 这个问题可以关闭，我们自己处理，谢谢

**Comment by afc163** [comment]
好，还有问题随时反馈。

**Comment by zombieJ** [comment]
如果是清除按钮，直接用 `allowClear` 属性： https://ant.design/components/input/#components-input-demo-allowClear

如果是其他图标的，在显示图标的时候需要用户自己调用一下 input.focus 因为纯粹的 Input 和 Input with suffix 的 dom 结构不一样，React 会重新创建 dom 节点。所以新的 input 自然就不会有 focus 了。
这个不便于在组件层去包，会有些 over design。对于这种需求如果多的话建议自己包一个 HOC 来设置一下 focus。

**Comment by afc163** [comment]
@zombieJ 有没有可能用 key 来保持 dom 节点。

**Comment by zombieJ** [comment]
> @zombieJ 有没有可能用 key 来保持 dom 节点。

key 只在同级 diff 有效，除非我们冗余的把 dom 结构也保持一次…………

**Comment by cfk199244** [comment]
好的，谢谢，新年快乐. 我会尝试下HOC的方式去做，暂时不想升级太高的版本，怕出问题.

**Comment by cfk199244** [comment]
emmm..... 我刚才改了下例子, 如果自己focus()的话, 中文输入法第一个字符就有问题了,  比如我输入"你好".
输入"n"的时候. 就没了, 在输入i, 输入法只剩下i的显示了

**Comment by zombieJ** [comment]
那用个空 suffix 吧：https://codesandbox.io/s/1oq805r6v3

**Comment by cfk199244** [comment]
@zombieJ  试了一下，可以，谢谢.
