### ISSUE TITLE
文本框通过浏览器AutoComplete选择或粘贴时失去焦点

### ISSUE THREAD

**Issue by cfk199244** [ant-design/ant-design#14655]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
项目去年使用3.73版本的antd.
其中大量使用了文本框的onBlur事件. 且粘贴内容或自动完成选中数据时，焦点都保留在文本框.

但是switch点击会报错, 搜索问题发现在3.84版本已修复，因此升级到3.84.
但是升级后，在文本框中以上2个操作后，文本框都直接失去了焦点，且不触发onBlur事件，导致项目中大部分功能出问题. 

### What does the proposed API look like?
我想知道这是什么原因导致的. 的确是版本更新后才这样，换回旧版本就正常.

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
