### ISSUE TITLE
DatePicker component using DEFAULT_FORMAT instead of LocaleProvider format

### ISSUE THREAD

**Issue by SamKirkland** [ant-design/ant-design#14656]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5wmw92v5rn)

### Steps to reproduce
Select a date, it will be formatted using the DEFAULT_FORMAT specified in wrapPicker.tsx instead of the locale based date format

### What is expected?
The date format should be based on the locale from <LocaleProvider>

### What is actually happening?
The DEFAULT_FORMAT is being used instead

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.5.2 |
| System | Windows 10 x64 |
| Browser | Chrome 71.0 |

---
I've fixed this issue, I will be submitting a PR after this bug has been submitted

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13196
https://github.com/react-component/calendar/pull/468#issuecomment-457502792

**Comment by SamKirkland** [comment]
I noticed both those issues, I've actually been following their progress.

However the commit to fix #13196 has a small bug.

#14340 added code in wrapPicker.tsx to select the format from the locale using this line
`locale[LOCALE_FORMAT_MAPPING[mergedPickerType]]`
when it should be
`locale.lang[LOCALE_FORMAT_MAPPING[mergedPickerType]]`

LOCALE_FORMAT_MAPPING keys are within the lang object not on the base object, I checked every locale format at none of them have these keys on the base object. If you look at the locale files within ant-design/components/date-picker/locale/ you will see rc-datepicker component locales are wrapped under lang which means these keys never exist in the base object.

I fixed the locale example.json file to be correct as well.

**Comment by SamKirkland** [comment]
> #13196
> [react-component/calendar#468 (comment)](https://github.com/react-component/calendar/pull/468#issuecomment-457502792)

I noticed both those issues, I've actually been following their progress.

However the commit to fix #13196 has a small bug.

#14340 added code in wrapPicker.tsx to select the format from the locale using this line
locale[LOCALE_FORMAT_MAPPING[mergedPickerType]]
when it should be
locale.lang[LOCALE_FORMAT_MAPPING[mergedPickerType]]

LOCALE_FORMAT_MAPPING keys are within the lang object not on the base object, I checked every locale format at none of them have these keys on the base object. If you look at the locale files within ant-design/components/date-picker/locale/ you will see rc-datepicker component locales are wrapped under lang which means these keys never exist in the base object.

I fixed the locale example.json file to be correct as well.

**Comment by zombieJ** [comment]
local.DatePicker.lang is not format usage but picker related string display. You should add format in DatePicker: https://codesandbox.io/s/vj3w0qz2p3

Here is the locale file format: https://github.com/ant-design/ant-design/blob/master/components/date-picker/locale/example.json

**Comment by SamKirkland** [comment]
> locale.DatePicker.lang is not format usage but picker related string display. You should add format in locale.DatePicker: https://codesandbox.io/s/vj3w0qz2p3
> 
> Here is the locale file format: https://github.com/ant-design/ant-design/blob/master/components/date-picker/locale/example.json

What's the use case for different formatted dates? Is that common in non en-us cultures?

Due to locale.DatePicker not being defined in any current locale file they're all falling back to the default.
I'm willing to make a PR to populate those keys on all the locale files if that's the approach we want. It would also be nice if we strongly typed locales to force all keys be defined in the future.

Thanks :D

**Comment by zombieJ** [comment]
In most case format is the same so it use default format. But something may different.
For example, in china. Both format of `2019年1月1日` or `2019-01-01` in Chinese are OK. And mostly use `2019-01-01` but some official env may use `2019年1月1日`. We can't tell which one may best fit for user business logic. So this `locale.DatePicker` only provides the ability to customize format which user want to customize in their business logic.

**Comment by SamKirkland** [comment]
> In most case format is the same so it use default format. But something may different.
> For example, in china. Both format of `2019年1月1日` or `2019-01-01` in Chinese are OK. And mostly use `2019-01-01` but some official env may use `2019年1月1日`. We can't tell which one may best fit for user business logic. So this `locale.DatePicker` only provides the ability to customize format which user want to customize in their business logic.

Thanks for the response!

ISO 8601 is great, however some counties have not yet adopted it unfortunately.
I would expect LocaleProvider to handle formatting, as it's an opt-in component designed to make locale support easier. I'd expect business logic to be okay because of the documentation mentions you must set the moment culture. Looking at [momentjs.com](https://momentjs.com/) setting locales to US/China/Azerbainjani I'd expect the format to follow "calendar time" .calendar()
[Here is a list of date format by country](https://en.wikipedia.org/wiki/Date_format_by_country)

Let me know how you want to proceed.

**Comment by zombieJ** [comment]
Got it. If some counties not use this default format, I think it does help to change it in matched locale file : )

**Comment by SamKirkland** [comment]
I'll put together a pull request.
Thanks!

**Comment by pierre-H** [comment]
any news ?

**Comment by SamKirkland** [comment]
Unfortunately I haven't put together a pull request.

I have it working in my project by using LocaleProvider and passing in a modified locale with dateFormat set.

Example:
```typescript
import antd_en_US from 'antd/lib/locale-provider/en_US';

const custom__antd_en_US = {
    ...antd_en_US,
    DatePicker: { // format datePicker date to whatever you want
        ...antd_en_US.DatePicker,
        dateFormat: "ll", // this is likely the one you want :)
        dateTimeFormat: "ll HH:mm",
        weekFormat: "wo YYYY",
        monthFormat: "MM YYYY"
    }
};

<LocaleProvider locale={custom__antd_en_US}>
    <>
        {myApp} // wrap your entire app in LocaleProvider
    </>
</LocaleProvider>
```

**Comment by david-soyez** [comment]
Why is this closed ? is it resolved ?
