### ISSUE TITLE
Custom SVG Icon, prop viewbox is overwritten with undefined

### ISSUE THREAD

**Issue by BroKun** [ant-design/ant-design#14658]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/93zqnk49pw)

### Steps to reproduce
see the codesandbox [example](https://codesandbox.io/s/93zqnk49pw)

same when using svgr [example](https://www.smooth-code.com/open-source/svgr/playground/)

### What is expected?
Don't pass the viewBox property, when the value is undefined

### What is actually happening?
viewBox is always overridden as undefined

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | * |
| System | * |
| Browser | * |

---
commit 47e23d4137efc8cd17468a0ac249f91178de9fa2 

components/icon/index.tsx

```js
-    if (!viewBox) {
-      delete innerSvgProps.viewBox;
-    }
```

**Comment by earlymeme** [comment]
when use create-react-app svg component
