### ISSUE TITLE
Table expand row is slow when used as accordion

### ISSUE THREAD

**Issue by fgiarritiello** [ant-design/ant-design#14665]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4zv6yornj)

### Steps to reproduce
1. Create a component with state to manage the expand and collapse of the row one at the time (accordion)
2. Add a large set of data
3. Click on expand
4. Check the console
Observe: the UI gets very laggy and the console prints a message such as [Violation] 'click' handler took 511ms

### What is expected?
The table should expand and collapse the row without lag

### What is actually happening?
the UI gets very laggy and the console prints a message such as [Violation] 'click' handler took 511ms

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7.0 |
| System | macOS Mojave 10.14 |
| Browser | Chrome 71.0.3578.98 |

**Comment by ztplz** [comment]
Optimizing the table is a future thing because of the priority. I am afraid that this thing can't be completed in the near future since we are short of hands.

**Comment by ChuckJonas** [comment]
I just upgraded a medium/large app from `3.7.3` -> `3.13.5` and did some very basic profiling.  

In general, I'm seeing about a 300% slow down.

My app is primarily a combination of tables, accordions and tabs

**Comment by umaxfun** [comment]
I would pay $100-$200 to everyone who fixes this bug, please contact me at ![umaxfun outlook com](https://user-images.githubusercontent.com/521752/53500493-7784d480-3abb-11e9-8e21-e3a37c1fa975.png) to opt-in 💵 💵 💵

**Comment by fgiarritiello** [comment]
Can anyone please give an update on this? Is it even in the backlog? The table component is pretty much unusable with more than 100 rows in it. I will have to ditch antd if this problem is not fixed soon.

**Comment by afc163** [comment]
It works much faster in antd 4.0: https://codesandbox.io/s/m4zv6yornj
