### ISSUE TITLE
Table sort bug !!!

### ISSUE THREAD

**Issue by thbgh** [ant-design/ant-design#14661]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vvox9w1vl5)

### Steps to reproduce
table sort /表格排序

### What is expected?
排序正常

### What is actually happening?
排序异常

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.5.2 |
| System | win10 |
| Browser | chrome 版本 71.0.3578.98（正式版本） （64 位） |

---
问题图示
![antd_tablesotrbug](https://user-images.githubusercontent.com/9399517/52035936-b8de9e80-2566-11e9-9be4-be8ee82de074.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/qlk075np14

You use sort and string compare in wrong way, please learn JavaScript first.

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
- https://stackoverflow.com/a/6712080/3040605
