### ISSUE TITLE
menu的目录下面如果有子目录的话，onSelect和onClick失效

### ISSUE THREAD

**Issue by yayamommy** [ant-design/ant-design#1466]
menu的onSelect和onClick事件貌似只针对叶子节点（没有子节点），对于有子节点的目录是没用的，这个问题现在解决了吗？
之前看到过类似的问题 [485](https://github.com/ant-design/ant-design/issues/485)

**Comment by afc163** [comment]
```
<SubMenu title={<span onClick={this.handleClick}></span>}>
</SubMenu>
```

可以先试试这样。

**Comment by RaoHai** [comment]
see PR https://github.com/react-component/menu/pull/37

**Comment by afc163** [comment]
在 1.0.0-beta 上可以用 onTitleClick 。

**Comment by afc163** [comment]
需要补充相关文档。

**Comment by afc163** [comment]
onTitleClick 目前是失效的。
