### ISSUE TITLE
Select选择器收起区域都会先去选中第一个选项， 然后再消失。

### ISSUE THREAD

**Issue by johnJine** [ant-design/ant-design#14662]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
1. 点击展开下拉框， 
2. 再点击收起下拉框

### What is expected?
lucy 是选中项

### What is actually happening?
弹出框收起的刹那 ， 变成jack选中了。

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | react  |
| System | win10 |
| Browser | chrome |

---
Select选择器收起区域都会先选中第一个选项， 然后再消失。

**Comment by afc163** [comment]
确实，chrome 下有这个问题。感觉和 https://github.com/ant-design/ant-design/issues/14352 是同一类问题。@zombieJ
