### ISSUE TITLE
Modal无法获取dom节点

### ISSUE THREAD

**Issue by qianduanMortal** [ant-design/ant-design#14671]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kxn5owp625)

### Steps to reproduce
modal对话框，设置属性forceRender为true.    
在componentDidMount中，通过document.getElementById('#dom');  不能获得dom节点。

### What is expected?
期望可以在componentDidMount环节，获取到modal中的某dom元素。

### What is actually happening?
获取不到dom，打印为null。

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | stable |
| System | windows |
| Browser | chrome.stable |

**Comment by qianduanMortal** [comment]
补充一点，最终的需求是在Modal中初始化一个jquery插件。类似于antv/G6的用法。 但是获取不到窗口中的dom元素。

**Comment by zombieJ** [comment]
https://codesandbox.io/s/xv68643y14
