### ISSUE TITLE
react-router的browserHistory不支持吗？

### ISSUE THREAD

**Issue by QzhouZ** [ant-design/ant-design#1467]
import React from 'react'
	import ReactDOM from 'react-dom';
	import { Router, Route, IndexRoute, Link, IndexLink, browserHistory } from 'react-router';
	import App from '../component/App';
	import Home from '../component/Home';
	import About from '../component/About';
	import Example from '../component/Example';

	ReactDOM.render((
		<Router history={browserHistory}>
		    <Route path="/" component={App}>
		        <IndexRoute component={Home} />
		        <Route path="example" component={Example} />
		    </Route>
		</Router>
	), document.getElementById('app'));

``npm run dev``模式下，页面有出来的，但页面刷新后就出错了
![](http://ww1.sinaimg.cn/large/6167eb83gw1f342hsnlsaj208r02w0sz.jpg)
刷新后
![](http://ww1.sinaimg.cn/large/6167eb83gw1f342ipss9vj208u02xjrl.jpg)

``npm run build``编译后，引入编译的文件，页面直接显示不出来了，去掉``history={browserHistory}``是可以正常使用的。

我之前用gulp是可以正常使用的
这是用gulp构建的，刷新后页面正常
![](http://ww1.sinaimg.cn/large/6167eb83gw1f342q4o6wzj209s03c3ys.jpg)

**Comment by benjycui** [comment]
`browserHistory` 是需要服务端支持的 https://github.com/dora-js/dora-plugin-browser-history

http://doc.zengrong.net/smart-questions/cn.html

**Comment by QzhouZ** [comment]
@benjycui 用了这个成功了，谢谢谢谢。
另外请教一下：有办法支持用nginx的服务器吗？
个人探索结果：
执行``npm run build``,编译后通过访问127.0.0.1/ant-demo/src，index.html的文件路径已经替换，
现在的结果是页面一片空白。
请问nginx需要额外的配置吗？

**Comment by QzhouZ** [comment]
已解决~
