### ISSUE TITLE
Select 多选状态下的值的问题

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ant-design/ant-design#14672]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/select-cn/#components-select-demo-multiple](https://ant-design.gitee.io/components/select-cn/#components-select-demo-multiple)

### Steps to reproduce
设置 Select 组件为多选时，给 Select 的 defaultValue 或 value 设置的值，理应为一个数组，但是如果值为一个空的字符串或 null 时，显示的效果为有一项被选择了，而且下拉中也没有对应的值选项，所以，这个情况下显示的效果是不是不符合常理？

### What is expected?
输入框中应没有任何选中的项

### What is actually happening?
输入框中有一个空白的选项被选中

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.x |
| System | win10 |
| Browser | 谷歌浏览器 |

**Comment by afc163** [comment]
`null` 和 `""` 我们认为是一个有意义的值，例如可能关联选项中的『未选择』『留空』等等。只有 `undefined` 才是真正的空。

**Comment by douzhuanxingyi** [comment]
@afc163 但是多选模式下,value为空字符串, <Option value="">其它</Option>,当选中了这一项后,下拉列表中这一项的表现为未选中的状态,字体没有变黑变粗,后面没有对号,且无法onDeselect取消
