### ISSUE TITLE
消息全局提示IE11“Promise”未定义

### ISSUE THREAD

**Issue by lzy94** [ant-design/ant-design#14679]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://xxx.com](http://xxx.com)

### Steps to reproduce
`//退出
    
    logOut =（）=> { 

        // console.log（'退出'）; 

        message.success（ '退出成功，正在跳转······'）; 

        // message.success（'退出成功，正在跳转······'，1，（）=> { 

            // this.props.history.push（{pathname：“/ login”}）; 

        // }）

    }
`
在IE11中使用消息全局提示会报“Promise”未定义，使用Modal就可以。我用IE11打开官方示例就可以...

### What is expected?
message ie11 正常使用

### What is actually happening?
IE11  message “Promise”未定义

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7 |
| System | window 64 |
| Browser | google 71.0.3578.98 |

**Comment by yesmeck** [comment]
https://ant.design/docs/react/getting-started-cn#%E5%85%BC%E5%AE%B9%E6%80%A7

需要自己酌情添加 polyfill.
