### ISSUE TITLE
notification - conflict of onClick and onClose

### ISSUE THREAD

**Issue by Vermouth1995** [ant-design/ant-design#14670]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vv3vm5lrpy)

### Steps to reproduce
1.create a notification
2.click the close button

### What is expected?
Do not trigger the onClick event when I click the close button.

### What is actually happening?
When I click the close button, both the onClose and onClick events are triggered.

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.6.3 |
| System | windows |
| Browser | Chrome |

**Comment by Renderz** [comment]
may use 'event.currentTarget' of 'onClick' event to identity which element you are about to click...

(waiting for another solution...)

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/52550491-4b0e5e80-2e13-11e9-84c9-5c613178022d.png)
@afc163  @zombieJ  但是rc里的example 这好像又是default behavior
