### ISSUE TITLE
InputNumber widget need a mode to only change on enter, not on type

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#14685]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when I change number from 48 to 60, it goes 48 -> 4 -> 0 -> 6 -> 60, and since other part of the UI is updated on every change event, these unnecessary changes are annoying

### What does the proposed API look like?
add new prop  changeOnEnter: boolean

when changeOnEnter == true:

1. typing in the input area won't trigger any onChange event, it will only change when user press enter
2. when widget lose focus with uncommitted changes, it automatically revert to the previous value

features below is nice to have but not critical

3.  when start typing, the up/down arrow in the right become check and cross icon, this UI difference makes it clear that you need to press enter or click the check button
4. mousedown on the check icon has same effect as press enter, (probably not click event, since the blur event would happen first and value will be reverted)
5. mousedown on the cross icon is basically same thing as focus out, so there is no need for event handler

**Comment by afc163** [comment]
You can try to create a HOC InputNumber by overriding onChange and onBlur.

**Comment by rinick** [comment]
@afc163 This is doable, but it would be tricky since I need to make the decision if the onChange is from typing or from up/down arrow button by listening to all click and keyboard event. since this behavior only apply to keyboard typing

it would be nice if the onChange event can have a second parameter telling me the source of the change
