### ISSUE TITLE
升级最新版本后，为什么Input高度以及Select里面的文字都变大了

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#14681]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
升级最新版本后，为什么Input高度以及Select里面的文字都变大了，就连日期选择器里面的日期数字都变大了

### What is expected?
输入框或者文字大小保持跟旧版本默认大小一样

### What is actually happening?
输入框或者文字大小保持跟旧版本默认大小一样

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by Mathround** [comment]
> Hello @Mathround. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @Mathround, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

> Hello @Mathround. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @Mathround, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

也不是什么大问题，我自己改下就行了，只是升级后，font-size从原来旧版本(2.7.1) 12px变成了14px

**Comment by afc163** [comment]
看下 3.0 的 changelog 啊，这不是 bug
