### ISSUE TITLE
Pagination添加隐藏首尾页的功能

### ISSUE THREAD

**Issue by tonypig93** [ant-design/ant-design#14683]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
由于一些性能问题，我们系统中超过一定数值的跳页会比较慢，例如从第1页直接到第100页，仅仅使用`showQuickJumper=false`是不能满足需求的，因此希望`Pagination`可以原生支持隐藏首尾页的功能。

### What does the proposed API look like?
`hideBoundary: boolean`

**Comment by yoyo837** [comment]
就是不查总数那种？

**Comment by tonypig93** [comment]
类似于百度这种，只能在10页内跳转
![image](https://user-images.githubusercontent.com/27796932/52768885-b3ef1400-3069-11e9-9749-5ee48c79a5ff.png)

**Comment by afc163** [comment]
Could you send a PR to http://github.com/react-component/pagination to make this happen?

**Comment by seki2020** [comment]
Has this enhancement been finished in http://github.com/react-component/pagination? 
I am interested in it. 
Lol.
@afc163

**Comment by zombieJ** [comment]
v5 中 `itemRender` 返回 `null` 不再会渲染节点，closed：

https://codesandbox.io/s/ji-ben-antd-5-8-4-forked-4jgctd?file=/demo.tsx
