### ISSUE TITLE
Table: empty space between columns when using fixed columns

### ISSUE THREAD

**Issue by rekbrjdf** [ant-design/ant-design#14689]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y00p7lnj0z)

### Steps to reproduce
1. Fix the first column.

### What is expected?
There is no empty space between the first column and the other columns.

### What is actually happening?
There is empty space between the first column and the other columns.

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.8.0-alpha.0 |
| System | Ubuntu 18.10 |
| Browser | Chrome 72.0.3626.81 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Please leave at least one column without width to fit container width.

https://codesandbox.io/s/jpv46wom5v

**Comment by rekbrjdf** [comment]
@afc163 I updated my original example: https://codesandbox.io/s/y00p7lnj0z. I actually want all my columns to have auto width. In that case the empty space between columns is present.
