### ISSUE TITLE
change colour of range picker on blank data

### ISSUE THREAD

**Issue by tarun4all** [ant-design/ant-design#14688]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hey
Just want to confirm that i tried with the style but nothing happens to the component i want to change the colour of range picker if its empty
please guide i am sending the code to you
<RangePicker style={{border:'rgb(224, 17, 17)'}} onChange={this.getDate} defaultValue={[moment(this.state.fromDate), moment(this.state.toDate)]}/>

tarun.b@notifyvisitors.com

### What does the proposed API look like?
it takes the date input from user and if shows the analytics but if blank then it should got red please mail me on tarun.b@notifyvisitors.com

**Comment by afc163** [comment]
You should override styles by `className`, the style don't go to input element for RangePicker.
