### ISSUE TITLE
inconsistent rounding for monetary values

### ISSUE THREAD

**Issue by slillo** [ant-design/ant-design#14690]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/bss-rounding-sample-antd](https://stackblitz.com/edit/bss-rounding-sample-antd)

### Steps to reproduce
Just read label on InputNumber field is the initial value, the value shown is the value rounded (precision 2)

### What is expected?
Consistent behaviour for different input value. For example for EUR value 3.555 should be rounded as 3.56€ and 4.555 should be rounded as 4.56€ (half up method)

### What is actually happening?
Some value are rounded using half up method other are rounded using half down method (see [this image](https://m.eet.com/contenteetimes/images/00-Max-Embedded/2015-06-June/max-0053-emb-ral-01.gif)).  3.555 is rounded as 3.56 and 4.555 is rounded as 4.55

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7.0 |
| System | linux mint 19.1 |
| Browser | chrome 71 |

---
Would be great if we have the possibility to set rounding behaviour like is done in [Dinero.js .toFormat](https://sarahdayan.github.io/dinero.js/module-Dinero.html#~toFormat)

**Comment by ztplz** [comment]
Actually the strange behavior of `toFixed`.
![image](https://user-images.githubusercontent.com/17755202/52160893-44d40000-26f8-11e9-9581-c12999a7b3d0.png)

**Comment by ztplz** [comment]
@afc163  I am not sure if we should handle this strange behavior?

**Comment by afc163** [comment]
Following the default behavior of JavaScript would be my preference no matter how strange it is.

**Comment by zy410419243** [comment]
What about add a custom prop to handle this by userself?

**Comment by ztplz** [comment]
@slillo Uniform handling of this behavior does not seem very good. It may be better to use `onChange` to handle it as you wish.

**Comment by longilineo** [comment]
I'd like to see a way to handle rounding behaviour from a prop too. A lot of time number fields are used to handle monetary values and a uniform handling just for half up/down rounding would be great. The default behvaiour can remain just like using .toFormat

**Comment by zombieJ** [comment]
Since this is js default behavior, we will not change it. But for this case, you can use `parser` prop to customize the logic for rounding.

**Comment by slillo** [comment]
I understand your point of view, but currently api has useless precision prop and miss useful feature to make it work correctly in a lot of very plausible use case. 
I'd prefer to use parser or onchange to do something specific for specific field
