### ISSUE TITLE
Bug: Popover stays visible while modal closes on esc

### ISSUE THREAD

**Issue by ranbena** [ant-design/ant-design#14699]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://mo9jx1nkpx.codesandbox.io/)

### Steps to reproduce
1. Create Popover with click trigger in Modal
2. Open Modal, click popover button
3. Press keyboard esc key

![gif](https://media.giphy.com/media/63H9hOCFiiW3a1gYZq/giphy.gif)

### What is expected?
Modal and popover close

### What is actually happening?
Modal closes but popover stays open

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16 |
| System | Mac OS |
| Browser | Chrome |

**Comment by ranbena** [comment]
@zombieJ I've added the ability to close Trigger with escape key in https://github.com/react-component/trigger/pull/113, so that eventually `<Popover keyboard .. />` would allow the first "escape" to close the popover, then a second "escape" to close the modal, similar to how it works with Select in Modal.

**Comment by zombieJ** [comment]
How about add `destroyOnClose` on Modal? https://codesandbox.io/s/j7wpp3o9v5

**Comment by zombieJ** [comment]
👌
