### ISSUE TITLE
增加多语言支持

### ISSUE THREAD

**Issue by magicshui** [ant-design/ant-design#147]
对于datepicker等组件，希望能够提供多语言的支持，或者可以提供标准来扩展语言包；

**Comment by Erwin11** [comment]
日历控件我觉得能显示双月日历的功能会更重要吧？我做旅游的，双月显示，和日期上显示库存价格特别重要。
多语言是只引入i18n.js么？

**Comment by qiaolb** [comment]
我看到rc-calendar本身是支持多语言，通过locale可以配置，datepicker是否也应该增加国际化的支持。谢谢！

**Comment by afc163** [comment]
close via #424
