### ISSUE TITLE
Tree select in Transfer component?

### ISSUE THREAD

**Issue by irfanabliz** [ant-design/ant-design#14705]
-  [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use Transfer component, but it has this one limitation, or maybe I just don't know how to make it work, I wish to render Tree inside of Transfer component, like my object looks [{id: 1, name: building1, users: [{id: 999, name: test}]}], I want to render building as one tree and users inside of that tree in transfer select.

### What does the proposed API look like?
<Transfer customRender={() => /* react component */} />,
or whatever the api might look like.

**Comment by irfanabliz** [comment]
sorry if I didn't make my self clear, I wanted to accomplished this using Transfer.

<img width="699" alt="screen shot 2019-02-03 at 12 08 04 pm" src="https://user-images.githubusercontent.com/17282448/52179775-67275580-27ac-11e9-9428-836825f5cc94.png">

instead of writing my own Transfer component

**Comment by ztplz** [comment]
`Transfer` does not support custom components yet. But for your situation, I think it would be better to use `TreeSelect`.

**Comment by zombieJ** [comment]
Left is Tree, and right is list?

**Comment by irfanabliz** [comment]
right is tree also

**Comment by fighting1992** [comment]
同遇到这种交互  请问这个问题有解决方案了么

**Comment by billfienberg** [comment]
+1

**Comment by mstao** [comment]
请问 #14932 这个提交可以提前用在自己的项目中吗，现在需要在穿梭框中实现表格

**Comment by zombieJ** [comment]
> 请问 #14932 这个提交可以提前用在自己的项目中吗，现在需要在穿梭框中实现表格

还没有做完，还需要等等。
