### ISSUE TITLE
Table组件rowSelection.onChange与onRowClick冲突

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#1470]
### 场景
1、创建一个带单选框的表格
![image](https://cloud.githubusercontent.com/assets/17123400/14699233/bb4e6984-07c8-11e6-821a-a655fdec92c6.png)
2、注册rowSelection.onChange事件，用于更新表格中选中项
3、注册onRowClick事件，用于当点击行时执行跳转
![image](https://cloud.githubusercontent.com/assets/17123400/14699260/004de37a-07c9-11e6-8aa3-f7df51a541d0.png)
### 问题
点击任意单选框，希望执行rowSelection.onChange注册事件，获取选中项；而真正执行的是onRowClick事件，导致页面跳转

是否可以通过其他方式实现上述功能？

**Comment by zjdgx** [comment]
这个应该添加stopPropagation阻止事件冒泡

```
e.stopPropagation();
e.nativeEvent.stopImmediatePropagation();
```

**Comment by jaredleechn** [comment]
> 点击任意单选框，希望执行rowSelection.onChange注册事件，获取选中项；而真正执行的是onRowClick事件，导致页面跳转

这样的话，就没有必要注册 onRowClick 事件了吧？

**Comment by zachguo** [comment]
@afc163 This was fixed by 14f857b7ace56a40a09409d7fbc74a147e1b125b for a while. But in 1.3.2 in `rowSelection.onChange` is triggering `onRowClick`.

**Comment by zachguo** [comment]
I trace it back a little. It's working until 1.1.0, so the regression is introduced by 1.2.0

**Comment by afc163** [comment]
Yes... the `rc-checkbox` would not receive `onClick` any more.

https://github.com/react-component/checkbox/pull/14/files
