### ISSUE TITLE
Tree parent checkbox behaviour weird when each parent have same child (same child key)

### ISSUE THREAD

**Issue by irfanabliz** [ant-design/ant-design#14729]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/50r35m061k)

### Steps to reproduce
[![Edit 50r35m061k](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/50r35m061k)

### What is expected?
Three tree node parents, all of them each have one same key tree node children, but if one is click, only one parent tree node checkbox is checked indetermined

### What is actually happening?
Shouldn't all of the parent tree node checkbox is checked (indetermined?) if each has the same child with the same key?

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | 16.7 |
| System | MacOS |
| Browser | Chrome |

**Comment by ztplz** [comment]
Yes, the key of all nodes in the tree cannot be repeated. It is used to identify each node.

**Comment by gfafei** [comment]
what if I want to render a departmant tree ,when a member can belong to multiple department ? Can I use id or something to replace key
