### ISSUE TITLE
Table Doesn't Show Data Except For First Page When Used With Ajax Calls

### ISSUE THREAD

**Issue by onderonur** [ant-design/ant-design#14734]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5kmzjq7z1p)

### Steps to reproduce
* Wait for fetching data.
* Table shows the first page with data in it.
* Go to another page.
* Table shows "No Data" even if it has more than one page.

### What is expected?
Table should display the related data on the correct page.

### What is actually happening?
It stores the fetched data on the first page even if you are on the 2nd or 3rd page for example.
Thus, it shows "No Data" warning.

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | react 16.7.0 |
| System | Windows 10 |
| Browser | Google Chrome 72.0.3626.81 |

**Comment by ztplz** [comment]
Thanks for your report.  It has been fixed by https://github.com/ant-design/ant-design/pull/14724. The next version will release at weekend.

**Comment by onderonur** [comment]
Thanks for the lightning quick reply.

**Comment by anujshah1996** [comment]
why this issue is closed, it has not been resolved yet. We took a lot of time in our project, figuring what was wrong!!

**Comment by ztplz** [comment]
@anujshah1996 It has been fixed via https://github.com/ant-design/ant-design/pull/14724, the next version will release at weekend.

**Comment by afc163** [comment]
Fixed in `3.13.2` via https://github.com/ant-design/ant-design/pull/14724

**Comment by onderonur** [comment]
> Fixed in `3.13.2` via #14724

Thanks!
