### ISSUE TITLE
Make pagination active item background colour parameterized

### ISSUE THREAD

**Issue by ameen-demidem** [ant-design/ant-design#14739]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In this commit https://github.com/ant-design/ant-design/commit/b84bf85526e447150f4b4e966018d1206698282e, the background colour of the active item has been removed and cannot be customized.

### What does the proposed API look like?
Restore the background colour to using a variable that we can override.

**Comment by ztplz** [comment]
@afc163  Is it necessary to add a new api to the `pagination` to control the background color ?
