### ISSUE TITLE
ant-design-icons

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1473]
like https://github.com/google/material-design-icons & http://fortawesome.github.io & http://glyphicons.com/

**Comment by afc163** [comment]
- Repo: https://github.com/ant-design/ant-design-icons
- Website: http://icon.ant.design
- Usage:

  ```js
  import Icon from 'ant-design-icons';
  ```

**Comment by afc163** [comment]
@ddcat1115 牵头搞一下这个，网站找设计师设计，`antd` 依赖 `ant-design-icons`.

**Comment by afc163** [comment]
https://github.com/jianliaoim/icon-fonts
http://leungwensen.github.io/svg-icon/#ant

**Comment by warmhug** [comment]
顺便支持下 rn ？像这里：https://github.com/oblador/react-native-vector-icons

**Comment by afc163** [comment]
暂时不考虑拆出。
