### ISSUE TITLE
Proposal - better perfomance of Table component while editing

### ISSUE THREAD

**Issue by sharpensteel** [ant-design/ant-design#14740]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[Tutorial for `Table`](https://ant.design/components/table/#components-table-demo-edit-cell) suggested to add event handler for **each editable cell**, not just **editing** one:

```
class EditableCell extends React.Component {
...
componentDidMount() {
    if (this.props.editable) {
      document.addEventListener('click', this.handleClickOutside, true);
    }
  }
...
}
```

So many event listeners can affect perfomance. Table have only one focused cell in the moment.

### What does the proposed API look like?
Whould it be better to limit adding listeners only to edited (and focused) cells?

**Comment by afc163** [comment]
PR welcomes~

**Comment by sharpensteel** [comment]
@yesmeck  wow, great!
