### ISSUE TITLE
Table组件第二页以后都加载不出数据（ps: 过年是否能不给惊喜或者暂停几天发版...）

### ISSUE THREAD

**Issue by flyfinec** [ant-design/ant-design#14741]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5kmzjq7z1p)

### Steps to reproduce
官方demo - Table组件，远程加载数据。点击第二页及以后的页都加载不出数据

### What is expected?
点击第二页翻页，正常加载数据

### What is actually happening?
点击第二页翻页（或以后页），数据为空

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | 16.5.2 |
| System | win 10 |
| Browser | chrome |

---
实测3.13.1有问题，3.13.0没问题，pagination的current设置>=2即使后端有数据，前端都不会显示

**Comment by afc163** [comment]
duplicated https://github.com/ant-design/ant-design/issues/14734#issuecomment-460755948

**Comment by afc163** [comment]
@zombieJ We should release a patch ASAP.

**Comment by afc163** [comment]
Fixed in `3.13.2` via https://github.com/ant-design/ant-design/pull/14724
