### ISSUE TITLE
Controlled Input.Search does not work with onSearch

### ISSUE THREAD

**Issue by crudo** [ant-design/ant-design#14748]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rwvwk7jpjq)

### Steps to reproduce
See reproduction link. 
Variant _A_ is working, due to _onChange_. 
Variant _B_ is not working because _onSearch_ is used.

Input.Search can not have _value_ set, because it requires _onChange_. But I do not want to be searched on every keypress, but only when the search button or Enter is pressed.

### What is expected?
Input.Search should have support for _onSearch_ AND _value_ props set.

### What is actually happening?
Value is not set.

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | React 16.8.1 |
| System | MacOS Mojave 10.14.2  |
| Browser | Google Chrome Version 71.0.3578.98 (Official Build) (64-bit) |

**Comment by ztplz** [comment]
You didn't turn it into a controlled component. I updated your [demo](https://codesandbox.io/s/oo4pw0mxp9).

**Comment by crudo** [comment]
Hi @ztplz, 

I wasn't asking any question. I still think it is a bug. You can not use _onSearch_ and _value_ WITHOUT _onChange_.

If it's design decision, it should be mentioned in documentation.

**Comment by afc163** [comment]
`value` and `onChange` should be used together. `onSearch` is triggered only when press enter and button as it is been documented.

You can treat `<Search value={xxx} onChange={yyy} onSearch={zzz} />` same as `<Input type="search" value={xxx} onChange={yyy} onKeyDown={e => { e.key === 'enter' && zzz() }} />`.

**Comment by ztplz** [comment]
@crudo Actually this is the design of the `react`. If you set the `value`, react will become a controlled component. The text in the input will be controlled by you, and you need to modify the value when the `onChange` event is fired in the `input`.

**Comment by crudo** [comment]
@ztplz Yeah, I know that, and in my eyes, it does seems to make sense that ant will use onChange on behalf of me internally when I signup for onSearch only. But never mind. I had a workaround. Thanks!

**Comment by hanzlahabib** [comment]
> @ztplz Yeah, I know that, and in my eyes, it does seems to make sense that ant will use onChange on behalf of me internally when I signup for onSearch only. But never mind. I had a workaround. Thanks!

Glad to hear you had workaround, post it if you still remember it 😆 , next time post your workarounds for future viewers
