### ISSUE TITLE
Comment Component Content

### ISSUE THREAD

**Issue by Coolranch** [ant-design/ant-design#14744]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When my users are entering text into the comment control and they add line breaks I am storing the text like:

test comments with line breaks\n\ncomments are the best!

However, when I pass that value in the content property of the comment control it does not respect the line breaks.  This would be a great enhancement to make this control even better.

### What does the proposed API look like?
No change to the API, just either render the text as html to respect the line breaks or provide a separate property for indicating html content.

**Comment by afc163** [comment]
You should try `dangerouslySetInnerHTML`: https://zhenyong.github.io/react/tips/dangerously-set-inner-html.html

There is another commit that may help you: https://github.com/ant-design/ant-design/commit/1737fe37387a26924f173a101c4ffa09ad780cfc
