### ISSUE TITLE
Pagination doesn't work in table on ajax requests

### ISSUE THREAD

**Issue by anuragsingh722** [ant-design/ant-design#14743]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5kmzjq7z1p)

### Steps to reproduce
Click on page 2,3...last page in pagination, the table shows no data message, inspite of the data being present.

### What is expected?
Data should be shown on all pages.

### What is actually happening?
Data isn't being shown from page 2. But when going to page 1 from page 2, shows data but behind a loader. Slight glitch.

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | 16.3.2 |
| System | OSX 10.14.2  |
| Browser | Chrome 71.0.3578.98 |

**Comment by ztplz** [comment]
Please upgrade to `3.13.2`. We just released a new version.

**Comment by afc163** [comment]
Duplicated #14734, fixed in `3.13.2` via https://github.com/ant-design/ant-design/pull/14724

**Comment by zachguo** [comment]
The fix only works for some of my tables, not all. Still trying to find out why this happens.

**Comment by ztplz** [comment]
@zachguo If you still have problems, please provide an online demo.
