### ISSUE TITLE
TimePicker能否支持双击选择

### ISSUE THREAD

**Issue by avwo** [ant-design/ant-design#1474]
RT

**Comment by afc163** [comment]
暂不支持。

**Comment by avwo** [comment]
时间控件弹出的浮层只有点击其它地方才能选择，这种方式会给用户带来困惑及操作不便，不支持是居于什么考虑的?

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/issues/1408

**Comment by afc163** [comment]
双击不是很容易学习的交互，欢迎到上面 issue 中进一步讨论。
