### ISSUE TITLE
TreeSelect not working as expected

### ISSUE THREAD

**Issue by kelvin-oliveira** [ant-design/ant-design#14758]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/koomxrzk15)

### Steps to reproduce
Copy the TreeSelect [basic example](https://ant.design/components/tree-select/) in a project bootstrapped with create-react-app.
Execute the project.
Try to see the Tree Structure.

### What is expected?
The Tree Structure being displayed and no errors on console.

### What is actually happening?
The Tree Structure isn't being displayed and the following error is appearing on console:
"Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.8.1 |
| System | Windows 10 |
| Browser | Google Chrome 71.0.3578.98 |

---
The same issue can be reproduced by using only the Tree Component.

**Comment by afc163** [comment]
```diff
- const { TreeNode } = TreeSelect.TreeNode;
+ const { TreeNode } = TreeSelect;
```

https://codesandbox.io/s/4205m03mqx
