### ISSUE TITLE
Add onDisabledClick handler

### ISSUE THREAD

**Issue by kachkaev** [ant-design/ant-design#14751]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When some UI elements are disabled, users may struggle to figure out why. Examples include a submit form button that cannot be pressed, a menu item that's greyed out etc. As a user, I still sometime press on these elements even though they are pale, but only rarely get any useful feedback. 

In the best case scenario, clicking a greyed-out `Submit` button in a form scrolls me to a field that I have made a mistake in and switches the cursor to the right input element. For a disabled menu item, a well-made UI would show me a notification message or give some hint about the current situation somehow else.

It'd be great if ant design had something like `onDisabledClick` prop in various components. In my opinion, this can significantly improve the UX in cases when it's critical to guide users towards the system goal. Because `onDisabledClick` will have an arbitrary logic, it can be accompanied with another a11y prop for screen reader users. I'm not sure about the name of that prop, but it can just contain a string message that would work as a hint.

### What does the proposed API look like?
```jsx
<Button disabled={trueOrFalse} onClick={executeAction} onDisabledClick={() => message.info('You cannot do this action at the moment because of XYZ');} />
```

```jsx
<Menu onClick={handleMenuItemClick} onDisabledClick={({ key }) => notification.open({ message: `You cannot use ${key} because ${reasons[key]}`});}>
  <Menu.Item key="action1">Action 1</Menu.Item>
  <Menu.Item key="action2" disabled={true}>Action 2</Menu.Item>
</Menu>
```

**Comment by zombieJ** [comment]
`onDisabledClick` is not a good api design. Component with `disabled` should not provides the ability to interactive.

**Comment by kachkaev** [comment]
Hi @zombieJ! How would you suggest helping users to accomplish UI tasks in the cases I described above? Could you please explain what you mean by ‘not a good api design’?

**Comment by ztplz** [comment]
Don't you think this is a very contradiction thing? For example, we don't want a button to be clicked, but it does provide a hint that shows why it is disabled. If there is this feature, and we set up `onDisableClick`, but the button is disabled, should it be clickable or not clickable? You can use components like `tooltip` to tell the user why the component is disabled when the button is disabled.

**Comment by ztplz** [comment]
If you want users to know why a component is disabled, I think using `tooltip` would be a better choice. When the user mouses over a disabled component, the `tooltip` will pop up a prompt, and the user can know why the component is disabled.

**Comment by kachkaev** [comment]
> If there is this feature, and we set up `onDisableClick`, but the button is disabled, should it be clickable or not clickable

The idea is that the button does not look visually clickable, but if a person _still_ clicks on it, some side effect comes into play. This can be a notification message or an animation (e.g. the form shakes horizontally and the focus moves to the field that is preventing the form from submitting, that field flashes). A tooltip or a static message can serve here too, but there is not enough space for having these at all times. The proposed `onDisabledClick` (or whatever the name) is about reacting on the user action the UI does not expect, rather than showing some 'static' status. Tooltips, BTW do not work for touch-only UIs.

The behaviour similar to `onDisabledClick` is very common in games. Imagine some random scene where there is a box with a bonus the player is interested to open. If a key for this box has not been found yet, the box will not open, but it's unlikely that it will stand completely still: the box might jump or flash a bit, some sound will play. This feedback on the disabled game element helps human brain to follow the right scenario, hinting them on what needs to be done for the box to open. The same positive cognitive effect can be achieved in critical parts of the web UIs if it is possible for the feedback to trigger even if an action is temporary unavailable. Hope this game analogy will help communicate what I mean.

**Comment by zombieJ** [comment]
We not recommend tip user after user operate with a disabled component since this is not user friendly. Please consider to show tooltip directly when user hover the disabled component: https://codesandbox.io/s/nr2z39625l

And also, Tooltip support touch when user using mobile device.

**Comment by kachkaev** [comment]
> We not recommend tip user after user operate with a disabled component since this is not user friendly

I totally agree that interacting with a disabled component is not desired, but it does not mean that users never do that. Even if we assume that a tooltip is a good enough replacement for a custom behaviour a disabled element can provide as feedback, how about tracking stats? If I'd like to know how many times my potential customers pressed a disabled pay button, what are my options?

**Comment by zombieJ** [comment]
We will not support this function since it's about business specific. But you can use HOC to wrap a button to provide a style to make it looks like a disabled button but clickable.

**Comment by kachkaev** [comment]
Thanks for the suggestion! I'll give it a try and report back if the result is successful.

**Comment by ztplz** [comment]
You can use `div` wrap the disabled button, see this [demo](https://codesandbox.io/s/y31rovopqj).
This will allow you to prompt the user and count user clicks.
