### ISSUE TITLE
Select.Option should support boolean in prop types

### ISSUE THREAD

**Issue by code-matt** [ant-design/ant-design#14752]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q390my2wm9)

### Steps to reproduce
Pass an Select.Option to a Select where the value is false

### What is expected?
Select's label might be one thing and the values are true or false. Currently this throws a PropType warning.

### What is actually happening?
The prop types for Select.Option only include string or number

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.6.0 |
| System | macOS Mojave |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Why not use Switch component if want to use boolean type?

**Comment by code-matt** [comment]
Out of my control, the design calls for a select. I agree but silly designers !

**Comment by ztplz** [comment]
@code-matt  You can use the boolean of the string instead of a real boolean value(i.e. "true", "false").

**Comment by zombieJ** [comment]
@code-matt , you can ref @ztplz 's answer.
Merge issue into #2857.

**Comment by manuelurenah** [comment]
I was able to make it happen with typescript const assertions
```ts
export const BooleanStatus = {
  Yes: true,
  No: false,
} as const;

export function BooleanStatusSelect(props: Props) {
  return (
    <Select placeholder="Select Status" {...props}>
      {Object.keys(BooleanStatus).map((key) => (
        <Select.Option key={key} value={BooleanStatus[key]}>
          {_startCase(key)}
        </Select.Option>
      ))}
    </Select>
  );
}

type Props = React.ComponentProps<typeof Select>;
```

**Comment by lucataglia** [comment]
Use the string instead of the boolean value is more a workaround that a solution. I'm having the same problem, is there a chance that in the future <Select /> will be able to handle plain boolean value ? In the rare use cases where it's needed, helps in keep the code cleaner instead of use strings.

Version:
"antd": "3.26.20"
