### ISSUE TITLE
Async Pagination does not work properly on Table

### ISSUE THREAD

**Issue by samuelcastro** [ant-design/ant-design#14754]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4q0k7vwpo4)

### Steps to reproduce
1 - Click in the 2nd or 3rd page.
2 - No data shows up.

### What is expected?
Table should be able to handle async data loading, when loading more chunk of data it should show up properly in the respective page number.

### What is actually happening?
It seems that when we load more datasource data, (when clicking in a 2nd or 3rd page) if the number of data is less than the page size, the datasource will be rendered in the first page, but if the user is in the 2nd/3rd page no data shows up.

| Environment | Info |
|---|---|
| antd | 3.10.0 |
| React | 16.7.6 |
| System | OSX |
| Browser | Version 71.0.3578.98 (Official Build) (64-bit) |

I can also reproduce this issue in the oficial table ajax documentation demo (https://ant.design/components/table/)

**Comment by zombieJ** [comment]
typo `curent` -> `current`: https://codesandbox.io/s/wwq831qkv7

**Comment by samuelcastro** [comment]
I don't think it's just a typo, I'm still having this problem even with `current` also the oficial table ajax doc it's happening the same thing:

<img width="1975" alt="screen shot 2019-02-07 at 11 38 48 pm" src="https://user-images.githubusercontent.com/5281701/52464947-b0bbcb80-2b31-11e9-9e78-6c1610170502.png">

**Comment by ztplz** [comment]
@samuelcastro 
![image](https://user-images.githubusercontent.com/17755202/52469259-f0cc8e00-2bc5-11e9-8435-fbc1a37d17e5.png)
Please check the `antd` version in your project,  make sure it is not version 3.11.

**Comment by ztplz** [comment]
I looked into your demo, after I correct the typo, it's work fine for me.
![image](https://user-images.githubusercontent.com/17755202/52469493-8e27c200-2bc6-11e9-814a-8c18d394859c.png)

**Comment by ztplz** [comment]
@afc163  
![image](https://user-images.githubusercontent.com/17755202/52469673-127a4500-2bc7-11e9-91bc-c11a239ac213.png)
`Antd` website has not been updated yet.

**Comment by zombieJ** [comment]
> `Antd` website has not been updated yet.

Thanks for tips. Updated

**Comment by samuelcastro** [comment]
Ok guys, it's working on `3.13.2`, thanks!
