### ISSUE TITLE
expose internal ref as protected instead of private

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#14753]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
many components keep a private ref to the internal rc component. The features of rc component are usually not 100% exposed. so having a high order component or extended class won't be able to access them either
It would be nice if they can be accessed from a class that directly extends the component.

### What does the proposed API look like?
**protected** buttonNode?: HTMLElement

**Comment by zombieJ** [comment]
Since we don't want internal ref expose to user, could you describe which component you need to access?

**Comment by afc163** [comment]
Don't use ref in 99.9% situation, please let me know what exact usage you need and let us handle by react way.

**Comment by rinick** [comment]
@afc163 I've run into couple of component that I need the ref.
One example is Input.TextArea ,  I want to commit the value on ctrl+Enter or lose focus, but not during regular typing, that flood my server with too many useless requests.
So my choice is to bind the `defaultValue` in props, not `value`.  But using defaultValue prevent it from update when use is not typing.
So when props.defaultValue changes, and component is not focused, I want to use the internal ref and manually update textArea's value

**Comment by rinick** [comment]
the above example might not be legit enough, since there are other way to work around it, just much more complicated to implement.

Here is another example, without internal ref 100% no way to do
 InputNumber, similar usecase as above, I made an HOC like you suggested, and when user press Escape, I want to revert to the original value, the only way to do that is get the internal ref and call
`inputNumberRef.setState({inputValue: myOriginalValue});`

**Comment by rinick** [comment]
Here is my understanding: input related react component with defaultValue prop usually provide some method or state so the HOC can use it as uncontrolled component and change the value.

**Comment by zombieJ** [comment]
HOC already can do this requirement. You can add value state in HOC and make the value of InputNumber control. No need to get internal `rc-input-number` component.
Call internal ref may cause strange behavior of component, should avoid that.

**Comment by tpakhoa1996** [comment]
On this same topic, I'm building a text box that has an arrow pointing to a Button component. In order to do that I need to access the dom node of the Button component to calculate where the arrow should point to. Is there an alternative way for me to do this? Currently, I'm using findDOMNode to do this but this is not a quite react-recommended way.
