### ISSUE TITLE
Select and dropdown sizing 

### ISSUE THREAD

**Issue by JohnPersano** [ant-design/ant-design#14763]
### What problem does this feature solve?
As it stands, I cannot modify the sizing of the select and dropdown items using any of the variables here: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less. When adjusting the base font size to anything above 16px, the Select component does not resize accordingly. This could be fixed by adding an overridable theme setting for select height.

For the dropdown items, they don't scale with the base font size either. This could be fixed by adding an overridable theme setting for dropdown menu item height.

### What does the proposed API look like?
Adding the following to the default Less styles:

@select-height-base: 32px;
@select-height-lg: 40px;
@select-height-sm: 24px;

@dropdown-item-height-base: 32px;
@dropdown-item-height-lg: 40px;
@dropdown-item-height-sm: 24px;

**Comment by JohnPersano** [comment]
After more experimenting, it looks like the select component can be resized with these two styles: 

"@input-height-base"
"@input-height-lg"

I can't find anything with the dropdown sizes. I should also add that if you use a large Select component (i.e. size={ 'large' }, the dropdown items stay the same size. Maybe the option to resize dropdown items is altogether missing?

**Comment by ztplz** [comment]
`Select` has three sizes, `small`, `default` and `large`. Are you not satisfied with the current style size, so you want to customize the size of the select?

**Comment by JohnPersano** [comment]
Hi @ztplz, no those options are perfect . It's the dropdown menu itself that I'm having trouble with. I've attached a screenshot below. This `Select` has been given 'large' as the size prop but I can't seem to figure out how to make the spacing in the dropdown match the `Select`. Each item in the dropdown is spaced close together relative to the dropdown itself. Ideally, I would like to style the dropdown so that each item is about the height of the `Select`.

![image823](https://user-images.githubusercontent.com/3487327/52532453-6f731980-2cf3-11e9-88d3-ff7e04d6c06c.png)

I've tried looking through the default styles for an override but can't seem to find anything relevant.

**Comment by ztplz** [comment]
Actually it is based on `line-height` in `ant-select-dropdown-menu-item`. i.e, set `line-height` to `32px`, it looks the same hight.
![image](https://user-images.githubusercontent.com/17755202/52533447-0c26cd00-2d6f-11e9-9d25-a60726eafc45.png)

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/52533478-4e500e80-2d6f-11e9-8ab4-b2ea49bea2cc.png)
It seems that you can use class for `Select.Option`.

**Comment by zombieJ** [comment]
Hi @JohnPersano, you can ref @ztplz 's suggestion for adjust.

And also we welcome for PR to improve less variable. Here is the related less code: https://github.com/ant-design/ant-design/blob/master/components/select/style/index.less#L492

**Comment by jamesreilly5** [comment]
I was able to fix this issue by overriding `@select-dropdown-vertical-padding`

**Comment by shehroz-sheri** [comment]
> `Select` has three sizes, `small`, `default` and `large`. Are you not satisfied with the current style size, so you want to customize the size of the select?

Yes please, I want much smaller size

**Comment by Argon2-ffiathan192** [comment]
I experienced the same difficulty and crafted a remedy



https://lnkr.fun/842cfcd
