### ISSUE TITLE
DatePicker.Range not working if start date is null

### ISSUE THREAD

**Issue by popmanhe** [ant-design/ant-design#14761]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://n5ry297550.codesandbox.io/)

### Steps to reproduce
      <p>WORKING if end date is null</p>
      <DatePicker.RangePicker value={[moment(), null]} />

      <p>NOT WORKING when start date is null. </p>
      <DatePicker.RangePicker value={[null, moment()]} />

### What is expected?
Should be able to pick dates

### What is actually happening?
exception throws, page goes blank

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.7 |
| System | windows |
| Browser | Chrome, firefox |

**Comment by ztplz** [comment]
It is the default behavior. If only start time is set, we can think of this date as starting time from now. But if you only set end time, so which time point should we start?

**Comment by popmanhe** [comment]
it means not start time. why date range has to have start time? for example, users would like to show 3 segments data: before 2000/01/01, 2000/01/01-2010/01/01and after 2010/01/01.this is a legit requirement and i just want to use one component.


On Feb 9, 2019 02:24, ztplz <notifications@github.com> wrote:

It is the default behavior. If only start time is set, we can think of this date as starting time from now. But if you only set end time, so which time point should we start?

**Comment by ztplz** [comment]
After I looked into your demo, I found that your usage was wrong. 
![image](https://user-images.githubusercontent.com/17755202/52529891-dca79e80-2d35-11e9-89f2-01eca2052dc0.png)
If you set `value`, this component becomes a controlled component. So you need to set the `onPanelChange` callback function yourself. But I guess you might want to set a date range.

**Comment by popmanhe** [comment]
The screenshot you took, that part is working and it has no problem. The issue is the next one, the start time is set to null. then there is an exception.

The doc is not what I want. My issue is pretty straightforward. The range picker can be used for not starting date. The start date of range picker should not be required,and definitely not raise a unhandled exception.

**Comment by zombieJ** [comment]
Hi @popmanhe,
RangerPicker not support part value range. You can send a PR to https://github.com/react-component/calendar if think it's necessary.
