### ISSUE TITLE
form组件 高级搜索例子 显示错误提示时在ie所有浏览器下布局错乱

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#14772]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-advanced-search](https://ant.design/components/form-cn/#components-form-demo-advanced-search)

### Steps to reproduce
在输入框输入一个值，然后按退格键删除

### What is expected?
布局正常
![image](https://user-images.githubusercontent.com/22299421/52544009-ee964980-2de8-11e9-90dd-a9d93bdc45b9.png)

### What is actually happening?
布局错误
![image](https://user-images.githubusercontent.com/22299421/52544002-e6d6a500-2de8-11e9-839a-dd93d246915d.png)

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | react16 |
| System | win10 |
| Browser | ie11 |

**Comment by ickeep** [comment]
![image](https://user-images.githubusercontent.com/9164133/52939463-36940e00-339f-11e9-82d3-cf3fcaf489f7.png)

错误信息换行 仍然会触发 bug

**Comment by zombieJ** [comment]
> ![image](https://user-images.githubusercontent.com/9164133/52939463-36940e00-339f-11e9-82d3-cf3fcaf489f7.png)
> 
> 错误信息换行 仍然会触发 bug

换行的就需要用户自己定义一下 FormItem 的高度了。

**Comment by zombieJ** [comment]
Since 3.13.5 revert this update. Reopen it.
