### ISSUE TITLE
antd换肤部分组件效果和默认色有冲突

### ISSUE THREAD

**Issue by v5zz** [ant-design/ant-design#14774]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
antd官网换肤

### What is expected?
颜色显示正确

### What is actually happening?
颜色显示有误

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.0.0 |
| System | 3 |
| Browser | 谷歌 |

![image](https://user-images.githubusercontent.com/47095302/52545357-d7a82500-2df1-11e9-9699-8152f7a1c321.png)
![image](https://user-images.githubusercontent.com/47095302/52545370-ee4e7c00-2df1-11e9-8070-ad1973d08d41.png)
![image](https://user-images.githubusercontent.com/47095302/52545379-045c3c80-2df2-11e9-923f-eea63b007f74.png)

**Comment by chenshuai2144** [comment]
在线换肤有一些 bug，有些样式并不会被重新计算，你可以试试使用 less-loader 的变量修改，如果使用的 umi，可以在 config.js 中配置 theme 属性

**Comment by afc163** [comment]
Same problem as #20079, merged in it.
