### ISSUE TITLE
Table固定列后，如果页面宽度较大Table不出现滚动条，则会有裂隙

### ISSUE THREAD

**Issue by 723156735** [ant-design/ant-design#14789]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
官方示例中，在 Table固定列 这一示例中，最右的action列和左边有一道裂隙，如果页面宽度缩小，Table可以横向滚动，裂隙就会消失

### What is expected?
页面宽度大，Table没有滚动时不出现裂隙

### What is actually happening?
出现了裂隙

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.6 |
| System | win10 |
| Browser | chrome71 |

---
在我的项目中，裂隙更严重
![](https://i.imgur.com/6WOLWSz.png)

**Comment by afc163** [comment]
```diff
- scroll={{ x: 1300 }}
+ scroll={{ x: true }}
+ scroll={{ x: '150%' }}
+ scroll={{ x: 'max-content' }}
```

这个例子写死了 1300px，用 true 或者百分比或者 `'max-content'` 就行了。

**Comment by t270173732** [comment]
只能通过属性设置x值去控制吗？

**Comment by t270173732** [comment]
好的,解决了，谢谢

**Comment by t270173732** [comment]
![image](https://user-images.githubusercontent.com/29575023/52770302-b2bfe600-306d-11e9-818e-445e029da406.png)
但是，如果我所有列宽度加起来没有页面宽就会出现两个固定列

**Comment by t270173732** [comment]
并且下面也会产生滚动条的样式

**Comment by afc163** [comment]
至少留一列不设宽度来自适应布局。

**Comment by SansaZhang** [comment]
> 至少留一列不设宽度来自适应布局。

屏幕很宽的时候这一列会变得特别宽。。。

**Comment by afc163** [comment]
> 屏幕很宽的时候这一列会变得特别宽。。。

多留几列，或者其他列宽度设置成百分比。
