### ISSUE TITLE
Popconfirm appear even button is disabled.

### ISSUE THREAD

**Issue by fwh1990** [ant-design/ant-design#14788]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.example.com](http://www.example.com)

### Steps to reproduce
\<Popconfirm title="I am showing...">
&nbsp;&nbsp;&nbsp;&nbsp;\<Button disabled=true>Show me\</Button>
\</Popconfirm>

### What is expected?
Don't show confirm modal.

### What is actually happening?
It happened with words 'I am showing...'

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 6.17.0 |
| System | macos 14 |
| Browser | chrome 70 |

**Comment by fwh1990** [comment]
Maybe the earlier antd has the same problem.

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/52611335-23c19b00-2ec0-11e9-80ef-3f7f321f4b34.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13351
https://github.com/ant-design/ant-design/issues/5000

**Comment by jake-hebert** [comment]
Looks like all of these related issues are closed as well - just curious what this resolution was?

Is this an improper implementation? I had the same expectation that clicking would not fire the popconfirm if the button was disabled and don't see any way to also disable the popconfirm.

**Comment by Niavart** [comment]
@jake-hebert 

If I understood issues linked and the doc, current workaround is using the "visible" tab of PopConfirm to stop it from displaying. 
But it require another state watch function and handling confirm + cancel functions

It wasn't really a solution to me so here's how I did it:
```
render() { 
let event; //
[...]
const Delete_confirm = () =>
        event === undefined ? (
          <Button
            disabled={event === undefined}
            onClick={this.deleteMe}
          >
            Delete
          </Button>
        ) : (
          <Popconfirm
            placement="topLeft"
            icon={<Icon type="question-circle-o" style={{ color: "red" }} />}
            title={"titleText"}
            onConfirm={this.deleteMe}
            okText="Delete"
            cancelText="Cancel">
            <Button
              disabled={event === undefined}
            >
               Delete
            </Button>
          </Popconfirm>
        );
[...]
 return (
   [...]
   <Delete_confirm key="delete" />
   [...]
)
```

**Comment by steviesama** [comment]
Yeah if you have `disabled={true}` it should work...however `Popconfirm` will not respect `disabled` if you have nested objects in it...I had a Badge around the icon I was using originally when it worked...and a div around the Badge because the Badge wouldn't `float: left`...so I had to move the div/badge to outside the `Popconfirm` so only the icon was on the inside for it to respect `disabled`.

**Comment by merthanmerter** [comment]
use `disabled ` of Popconfirm component not Button
