### ISSUE TITLE
Tabs 组件内容的异步加载

### ISSUE THREAD

**Issue by cuining** [ant-design/ant-design#1478]
> 看了官方的相关示例和源码，发现导航条和内容是放在一起返回的。但如果内容是需要异步加载的话，就要等到内容加载完毕才会切换到当前点击的选项卡。

想请教一下，能否实现**用户点击之后，先切换到当前点击的选项卡，再异步加载内容**的需求？

**Comment by yiminghe** [comment]
现在是异步的，请自己试下再体温
