### ISSUE TITLE
Prop addonAfter not working with Input.Search

### ISSUE THREAD

**Issue by arieldossantos** [ant-design/ant-design#14785]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wo67jmx31l)

### Steps to reproduce
• Create an Input.Search;
• Add 'addonAfter' prop;
• You'll see nothing happens

### What is expected?
It should work

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.7.0 |
| System | Windows |
| Browser | Chrome |

**Comment by ztplz** [comment]
It looks like a default behavior. Actually `Search` will default to this search icon as `addonAfter`.  @afc163  Is that so?
![image](https://user-images.githubusercontent.com/17755202/52609601-c7a74880-2eb8-11e9-878e-dfcbaecce7f0.png)
If you want to replace this search icon with a custom button, you can use `enterButton`.
![image](https://user-images.githubusercontent.com/17755202/52609695-18b73c80-2eb9-11e9-955c-030957720a9c.png)
