### ISSUE TITLE
antd table 列上加入footer 固定行，现在有什么解决方案？

### ISSUE THREAD

**Issue by mar105** [ant-design/ant-design#14795]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
#5710 有提议下面这个方案，我看是2017的，#14794 现在要达到这样的效果有解决方案不？你们这个关的太快了，又得重新提。最起码来个什么解决方案来处理这个问题再关嘛。我现在就是不知道怎么整。

const columns = [{
title: 'Name',
dataIndex: 'name',
}, {
title: 'Age1',
dataIndex: 'age',
footer: (data) => {
return

Summary: {data.reduce((sum, record) => sum record.age, 0)}

},
}, {
title: 'Address',
dataIndex: 'address',
}];

### What does the proposed API look like?
希望能够表格下方有固定footer行

**Comment by yesmeck** [comment]
https://github.com/ant-design/ant-design/issues/5710#issuecomment-443628076

不要重复提 issue，在原来的下面继续讨论即可。
