### ISSUE TITLE
table组件 footer想放汇总行，跟着表格走，现在只能放文字

### ISSUE THREAD

**Issue by mar105** [ant-design/ant-design#14790]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在有固定列，footer固定行

### What does the proposed API look like?
现在有固定列，footer固定行

**Comment by mar105** [comment]
现在表格中数字列要汇总，要悬浮固定在表格最下方，footer只能放文字。

**Comment by afc163** [comment]
Duplicate of #5710

**Comment by mar105** [comment]
看了5710的例子
footer: (data) => {
    return <div>Summary: {data.reduce((sum, record) => sum + record.age, 0)}</div>
  },
加了这句话 发现根本没有这属性，显示不出来。

**Comment by afc163** [comment]
#5710 being still open means this problem is not resolved offcially yet.
