### ISSUE TITLE
Pagination快速跳转到某一页，能不能加一个跳转按钮，或者失去焦点时触发也可以，现在enter键触发，用户未必知道

### ISSUE THREAD

**Issue by kangkang1995** [ant-design/ant-design#14798]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决人性化问题，程序员多做点，用户少思考一点，用户快速跳转到某一个分页，有时候并不知道Enter键可以触发

### What does the proposed API look like?
只需要把onBlur或者加个跳转按钮onClick   时把 Enter键触发的函数事件 绑定就好了

**Comment by zombieJ** [comment]
感觉可以弄成，enter / onBlur 确定， esc 取消。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14535#issuecomment-457115033
https://github.com/ant-design/ant-design/issues/7328#issuecomment-324880314

**Comment by sys1110** [comment]
onBlur跳转页面时，没有像enter那样清空输入框中的页码
