### ISSUE TITLE
 Modal.info({   title: 'some info',  content: <RangePicker style={{ width: 200 }} />,   });  Localization does not work.

### ISSUE THREAD

**Issue by Fendoe** [ant-design/ant-design#14804]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/48rr8z90pw)

### Steps to reproduce
Switch language to Chinese.
Click on "show info".
RangePicker component  localization does not work.

### What is expected?
Update localization.

### What is actually happening?
<RangePicker> localization does not work

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | react |
| System | windows 10 |
| Browser | chorme 72.0.3626.81 |

**Comment by zombieJ** [comment]
`Modal.xxx` don't have real context so that Locale not correct. Please wrap LocaleProvider in content also: https://codesandbox.io/s/nkmwq57r20
