### ISSUE TITLE
Will react-hooks drive Antd to upgrade to version 4.0?

### ISSUE THREAD

**Issue by ruoqianfengshao** [ant-design/ant-design#14808]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
for future

### What does the proposed API look like?
is there any plan?

**Comment by afc163** [comment]
No plan yet, antd is a UI library that can work with react hooks in 3.x already.
