### ISSUE TITLE
 Modal hides bottom line when the footer is set `null`.

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design#14816]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the footer is set `null`, bottom line is also visible

### What does the proposed API look like?
nothing

**Comment by mstao** [comment]
e.g:

![snipaste_2019-02-13_17-08-10](https://user-images.githubusercontent.com/23411433/52701232-b6dbfd00-2fb4-11e9-9bab-89f69afb4c33.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/247q0m69zn

It works well.

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
