### ISSUE TITLE
Drawer抽屉 的滚动区域能不能优化一下

### ISSUE THREAD

**Issue by johnJine** [ant-design/ant-design#14813]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce
1. 点击"  New account" 按钮
2. 浏览的窗口变小至到 Drawer抽屉出现纵向滚动条

### What is expected?
头部和尾部固定

### What is actually happening?
头部不固定， 滚动条被底部截掉

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | react |
| System | win10 |
| Browser | chrome |

---
将
style={{
    overflow: 'auto',
    height: 'calc(100% - 108px)',
    paddingBottom: '108px',
}}
替换成
bodyStyle={{
    overflow: 'auto',
    height: 'calc(100% - 108px)',
}}

**Comment by afc163** [comment]
可以的，这只是一个示例，你可以酌情修改成你需要的交互。鉴于目前的交互也是可选方案，就不修改 demo 了。
