### ISSUE TITLE
拖拽功能和固定列功能同时使用报错

### ISSUE THREAD

**Issue by yangxueyou** [ant-design/ant-design#14815]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
最开始table只有拖拽功能，然后业务需求要把首位固定，中间滚动的的形式，但是当我在colums里面加fixed:'left'之后就报错了（ypeError: Cannot read property 'getBoundingClientRect' of null
    at TableRow.setRowHeight (TableRow.js:181)
    at TableRow.saveRowRef (TableRow.js:225)
    at TableRow.componentDidMount (TableRow.js:142)）
现在只能保证一个功能的实现，无法同时实现。（不使用components属性或者colums[fixed]属性）

### What does the proposed API look like?
当我在colums里面使用fixed之后就是固定列

**Comment by afc163** [comment]
这两个功能目前无法共用，不要同时使用。
