### ISSUE TITLE
table 表头分组demo，滑动下方滚动条，性别会多处一列

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#14810]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-grouping-columns](https://ant.design/components/table-cn/#components-table-demo-grouping-columns)

### Steps to reproduce
滑动底部滚动条到最右边，发现性别那一列溢出

### What is expected?
性别那一列被固定住的性别列盖住

### What is actually happening?
因为ie9滚动条问题，导致溢出一个滚动条的距离
![image](https://user-images.githubusercontent.com/22299421/52693321-6313e880-2fa1-11e9-9d93-c7ad92b452b0.png)

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | react16 |
| System | win7 |
| Browser | ie9 |

**Comment by zombieJ** [comment]
Merge into #14545
