### ISSUE TITLE
[Documentation] Add version column to API Table

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#14818]
Indicate which version the API could be supported.

**Comment by DiamondYuan** [comment]
还有可以加一列 optional，可以自动从 interface 取。


version 我思考一下怎么实现。

**Comment by DiamondYuan** [comment]
version 指的是什么？我觉得代码里的文档应该是当前最新版本的文档，历史版本应该依靠 git 来实现

**Comment by DiamondYuan** [comment]
或者是增加新接口时候附带上当前的 version，这样用户就可以知道自己当前的版本能否使用。

**Comment by afc163** [comment]
是不是可以有另外一种方式，写一个脚本查询文档，反向写回到代码里？

**Comment by DiamondYuan** [comment]
命令行工具读代码，然后写文档会比较好，因为代码和文档的关系是一对多的。

**Comment by zy410419243** [comment]
写回到代码里这操作可能有问题，如果涉及到 `path` 的话，windows 可能就得靠边站了...

能看到例子的就是 `rc-tools` 了，它上面的 `Select` 放在 windows 下是跑不起来的

~~本来一直想提这个，但老是过几秒就忘了...~~
