### ISSUE TITLE
Upload组件上传最后一张图片时接口会报cancelled

### ISSUE THREAD

**Issue by linzhesheng** [ant-design/ant-design#14826]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#header](https://ant.design/components/upload-cn/#header)

### Steps to reproduce
``` 
<Upload
          action="//jsonplaceholder.typicode.com/posts/"
          listType="picture-card"
          fileList={fileList}
          onPreview={this.handlePreview}
          onChange={this.handleChange}
        >
          {fileList.length >= 3 ? null : uploadButton}
</Upload>
```

### What is expected?
最后一张图片能上传

### What is actually happening?
最后一张图片上传时接口会报cancelled

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | 16.5.0 |
| System | macOS High Sierra 10.13.4 |
| Browser | Google Chrome 72.0.3626.109 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/14779, will be released in this weekend.
