### ISSUE TITLE
ant-tabs-content设置的width会被覆盖成100%

### ISSUE THREAD

**Issue by yingxiaoqiang** [ant-design/ant-design#14827]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
把.ant-tabs设置为overflow-x: auto;.ant-tabs-contentTab宽度设置为width: auto;想实现左右滚动条，但是.ant-tabs-contentTab宽度会被覆盖为100%，导致超出部分永远滚动不出来

### What does the proposed API look like?
.ant-tabs-contentTab手动设置的宽度别被覆盖了

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
