### ISSUE TITLE
IE9上 bootstrap css 和 antd css同时引入导致样式失效问题

### ISSUE THREAD

**Issue by shlice** [ant-design/ant-design#1482]
我在项目里同时使用了 bootstrap和 antd。
如下引用 css
```
import 'bootstrap/dist/css/bootstrap.css';
import 'antd/lib/index.css';
import './my.less';
```
使用 webpack打包。在 chrome、safari、firefox 和 IE10以上浏览器均正常。
但是在IE9浏览器上，只要同时存在 bootstrap css 和 antd css就会出现 antd css 加载不全，且后续的 css 定义无法生效的问题。
调整bootstrap css 和 antd css的加载顺序，antd css 也加载不全，但加载的样式有所区别，后续样式定义同样不生效。

请帮忙确认下该问题，谢谢。

##### Environment Information
- "antd": "^0.12.13"
- "bootstrap": "^3.3.6"
- browser: IE9

**Comment by benjycui** [comment]
antd bs 之类的 UI 库只能用其中一个，同时使用会有冲突的，因为 CSS 都是全局，这种冲突无法解决。

**Comment by shlice** [comment]
能解释下为什么在 IE9会暴露出来呢，其他浏览器目前使用中未发现异常。

**Comment by benjycui** [comment]
不是浏览器专家，自行研究吧 😅

**Comment by afc163** [comment]
IE 会有 selector 数量限制和 css 文件大小限制。

http://stackoverflow.com/questions/9906794/internet-explorers-css-rules-limits

**Comment by justnull** [comment]
我找到了完美的解决方法。[https://www.npmjs.com/package/css-split-webpack-plugin  ](url)
