### ISSUE TITLE
Table Component can't keep the changed value when I trigger pagination change on edit row status. 在Table编辑状态下换页不能保留之前手动改变的值

### ISSUE THREAD

**Issue by AmyShieh** [ant-design/ant-design#14823]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-edit-row](https://ant.design/components/table-cn/#components-table-demo-edit-row)

### Steps to reproduce
1. edit any cell's values
2. page up without save
3. back to the first page

### 
1. 编辑了表单中的某一个值（原始值已经改变），
2. 不保存，点击下一页， 
3. 再返回之前的编辑页

### What is expected?
keep the changed value when I trigger the page's pagination change on the edit.

在编辑状态下触发换页时保留之前的编辑值

### What is actually happening?
When I edit any cell's values, and page up without save, Now I'm on the second page, then I back to the first page, the value I changed was reverted to the initial value.

当我编辑了表单中的某一个值（原始值已经改变），不保存，点击下一页， 再返回之前的编辑页， 我改变的值又被初始化成原始值了。

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.6.3 |
| System | Mac OS |
| Browser | Chrome |

---
Not only change the pagination, but also search table data or change table's data resource also makes this.

**Comment by ztplz** [comment]
以前是保留的  但是有issue要求不保留的去了 所以到底是需不需要保留  还是加个是否需要保留的api

**Comment by zombieJ** [comment]
感觉翻页就取消编辑框会好些？

**Comment by ztplz** [comment]
也行啊
