### ISSUE TITLE
getFieldDecorator不能是数组元素

### ISSUE THREAD

**Issue by 38606277** [ant-design/ant-design#14831]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
form表单是数组元素进行验证

### What does the proposed API look like?
<FormItem style={{ margin: 0 }}>
              {getFieldDecorator(this.state.data[index]['in_name'], {
                rules: [{
                  required: true,
                  message: `Please Input !`,
                }],
                initialValue: record.in_name,
              })(<Input onChange={e => this.handleFieldChange(e.target.value, 'in_name', index)}  />)}
            </FormItem>

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
