### ISSUE TITLE
Table component has only two columns left and right, and the left and right columns are fixed. There will be a blank in the middle of the table.

### ISSUE THREAD

**Issue by Carreylife** [ant-design/ant-design#14837]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ShawnZhang/pen/VgGWej?editors=0110](https://codepen.io/ShawnZhang/pen/VgGWej?editors=0110)

### Steps to reproduce
open this link and you will find it.

### What is expected?
table中间内容没有空白

### What is actually happening?
table中间内容样式出现空白

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | react (16.8.1) |
| System | macOS |
| Browser | chrome( 71.0.3578.98) |

**Comment by yesmeck** [comment]
Don't fix all columns, it's meaningless.
