### ISSUE TITLE
table中显示特定列的sum值

### ISSUE THREAD

**Issue by totothink** [ant-design/ant-design#1483]
我希望能够在table的底部显示其中某数值列的合计，不知道如何实现这个功能？

**Comment by benjycui** [comment]
`footer` http://ant.design/components/table/#table 

demo: http://react-component.github.io/table/examples/footer.html

**Comment by totothink** [comment]
谢谢,@benjycui

**Comment by motorguo** [comment]
@benjycui 请问如何在 `dataSource`  里，根据列的值，判断合并某些单无格，或者计算某些列的值。
第一列某几个字段相同，且连续的，将其合并或计算。

看 [table-demo-colspan-rowspan](https://ant.design/components/table/#components-table-demo-colspan-rowspan)
琢磨了半天

**Comment by benjycui** [comment]
那就再琢磨琢磨如何？

合并单元格不是用 `dataSource`，而是 `columns`
