### ISSUE TITLE
Upload组件上传照片数到达限制后，最后一个文件上传进程被中断.

### ISSUE THREAD

**Issue by VoliBearCat** [ant-design/ant-design#14838]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://deploy-preview-14733--ant-design.netlify.com/components/upload-cn/](https://deploy-preview-14733--ant-design.netlify.com/components/upload-cn/)

### Steps to reproduce
演示代码中的照片墙..上传图片到第三张

### What is expected?
最后一张图片能正常上传

### What is actually happening?
最后一张图片能无法正常上传

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.6.0 |
| System | macOS 10.14.2 |
| Browser | Chrom 72 |

![image](https://user-images.githubusercontent.com/11676384/52775839-8f9c3300-307b-11e9-8742-1b9d8768eb22.png)

**Comment by afc163** [comment]
Fixed in #14779, will be released in this weekend.
