### ISSUE TITLE
Upload.Dragger 无法上传所有拖进来的文件

### ISSUE THREAD

**Issue by evanzombie** [ant-design/ant-design#14845]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8nmo2l6v29)

### Steps to reproduce
拖了4000个文件进dragger，实际只有一部分上传

### What is expected?
上传所有拖进Dragger的文件

### What is actually happening?
拖了一个有4000个文件的目录到Dragger，实际只有1000多个文件上传。但是如果只用Upload，点击按钮选择目录上传的时候就没有这种问题。

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.6.1 |
| System | MacOS |
| Browser | Chrome Version 71.0.3578.98 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
有点蛋疼，最新标准的 File System API 已经暂停了：https://www.w3.org/TR/file-system-api/
现在用的还是 [2012 老的标准](https://www.w3.org/TR/2012/WD-file-system-api-20120417/#the-directoryreader-interface)，Chrome 还有做兼容支持。

而文件不全的原因是按照最后一版旧的规则，每次 `readEntries` 只保证提供成功读取的文件，所以需要不断调用直到全部读完为止。有点改造成本，不知道我要不要花精力来修一下？
@afc163

**Comment by afc163** [comment]
> 而文件不全的原因是按照最后一版旧的规则，每次 `readEntries` 只保证提供成功读取的文件，所以需要不断调用直到全部读完为止。

没看懂为啥文件不全。

**Comment by zombieJ** [comment]
> 没看懂为啥文件不全。

我们的 [traverseFileTree](https://github.com/react-component/upload/blob/master/src/traverseFileTree.js#L13) 里只调用了一次 `readEntries`，所以只能读取一部分文件出来。需要重复调用直到读不到文件为止。

**Comment by afc163** [comment]
那确实是我们的锅。

**Comment by zombieJ** [comment]
👌，那还是修一下。
