### ISSUE TITLE
timepicker clear icon style error when size small

### ISSUE THREAD

**Issue by vthinkxie** [ant-design/ant-design#14841]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zqxno11r6m)

### Steps to reproduce
hover the small timepicker

### What is expected?
clear icon style correct

### What is actually happening?
clear icon style error

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by chenlizan** [comment]
https://github.com/ant-design/ant-design/blob/master/components/time-picker/style/index.less
221行 right: @control-padding-horizontal-sm - 1px;
    right: 11px;
