### ISSUE TITLE
table加上rowSelection属性，勾选不起作用

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#14840]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
3.10.10版本下，table加上rowSelection属性，无法勾选，在3.12.3版本中是可以正常勾选的

onSelectChange = (selectedRowKeys, selectedRows) => {
    this.setState({ selectedRowKeys,selectedRows });
  }
const rowSelection = {
      selectedRowKeys,
      onChange: this.onSelectChange,
    };

<Table rowSelection={dataSource.length?rowSelection:null}  bordered pagination={false} columns={columns} dataSource={dataSource} />
        

### What is expected?
可以正常勾选

### What is actually happening?
无法勾选

| Environment | Info |
|---|---|
| antd | 3.10.10 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by afc163** [comment]
Please upgrade to latest version if it works.

**Comment by Mathround** [comment]
> Please upgrade to latest version if it works. If bug still happens at latest version, provide the codesandbox via http://u.ant.design/codesandbox-repro and I will reopen.

sorry, 是我粗心大意的错，不关版本的事

**Comment by EmmieF** [comment]
> > Please upgrade to latest version if it works. If bug still happens at latest version, provide the codesandbox via http://u.ant.design/codesandbox-repro and I will reopen.
> 
> sorry, 是我粗心大意的错，不关版本的事

今天遇到这个问题，同样的问题，最后怎么解决的？
