### ISSUE TITLE
TreeSelect It cannot delete the values entered in input

### ISSUE THREAD

**Issue by 137861368** [ant-design/ant-design#14848]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://012x.ant.design/components/tree-select/#select-demo-checkable](https://012x.ant.design/components/tree-select/#select-demo-checkable)

### Steps to reproduce
import { TreeSelect } from 'antd';
const SHOW_PARENT = TreeSelect.SHOW_PARENT;

const treeData = [{
  label: '节点一',
  value: '0-0',
  key: '0-0',
  children: [{
    label: '子节点一',
    value: '0-0-0',
    key: '0-0-0',
  }, {
    label: '子节点二',
    value: '0-0-1',
    key: '0-0-1',
  }],
}, {
  label: '节点二',
  value: '0-1',
  key: '0-1',
  children: [{
    label: '子节点三',
    value: '0-1-0',
    key: '0-1-0',
  }, {
    label: '子节点四',
    value: '0-1-1',
    key: '0-1-1',
  }],
}];

const Demo = React.createClass({
  getInitialState() {
    return {
      value: ['0-0-0'],
    };
  },
  onChange(value) {
    console.log('onChange ', value, arguments);
    this.setState({ value });
  },
  render() {
    const tProps = {
      treeData,
      value: this.state.value,
      onChange: this.onChange,
      multiple: true,
      treeCheckable: true,
      showCheckedStrategy: SHOW_PARENT,
      searchPlaceholder: '请选择',
      style: {
        width: 300,
      },
    };
    return <TreeSelect {...tProps} />;
  },
});

ReactDOM.render(<Demo />, mountNode);

### What is expected?
Delete input text without result when losing focus

### What is actually happening?
no

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | Cannot be deleted by method |
| System | window10 |
| Browser | Chrome 70.0.3538.110 |

**Comment by zombieJ** [comment]
Is antd@0.12.x or antd@3.13.2 ?

**Comment by 137861368** [comment]
> Is antd@0.12 or antd@3.13.2 ?

0.12

**Comment by 137861368** [comment]
> 你好@ 137861368。请提供此链接https://u.ant.design/codesandbox-repro或最小的GitHub存储库，以提供在线复制。标记为的问题`Need Reproduce`将在7天内没有活动时关闭。
> 
> 你好@ 137861368，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击[此处](https://u.ant.design/codesandbox-repro)创建一个代码盒或者提供一个最小化的GitHub仓库.7天内未跟进的问题会被自动关闭。

**Comment by 137861368** [comment]
> Hello @137861368. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @137861368, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

The third example of official website is an example.（多选和勾选框功能）
https://012x.ant.design/components/tree-select/#select-demo-checkable

**Comment by chenlizan** [comment]
![image](https://user-images.githubusercontent.com/10942164/52837000-ecedbe00-3127-11e9-9f82-6c14cf2240d6.png)

**Comment by chenlizan** [comment]
我在https://gitter.im/ant-design/ant-design群里回答了你的问题

**Comment by 137861368** [comment]
> 我在 https://gitter.im/ant-design/ant-design 群里回答了你的问题
> 
> ![image](https://camo.githubusercontent.com/088ef0eb7d23923a11cfd6ba5c3b9ec995555100/68747470733a2f2f66696c65732e6769747465722e696d2f616e742d64657369676e2f616e742d64657369676e2f724752502f696d6167652e706e67)

Thanks.
