### ISSUE TITLE
Progress component has a hard-coded color map

### ISSUE THREAD

**Issue by jurkowski** [ant-design/ant-design#14842]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zk0z7k4z3l)

### Steps to reproduce
Import `Progress` component from `antd` and render it with React.

### What is expected?
The colors for the `Progress` component should be defined from the theme color variables.

### What is actually happening?
The Progress component uses the Circle component (https://github.com/ant-design/ant-design/blob/master/components/progress/Circle.tsx). This has a hard-coded color map.

```
const statusColorMap: Record<string, string> = {
  normal: '#108ee9',
  exception: '#ff5500',
  success: '#87d068',
};
```

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.3.0 |
| System | MacOS |
| Browser | Firefox 65.0 |

**Comment by ztplz** [comment]
@afc163  Is it designed like this?

**Comment by afc163** [comment]
Yep, it is hard to read less variables to js.

**Comment by pybuche** [comment]
Hi ! I noticed it too.
Is anything planned to make it work like the other components?
Thx!
