### ISSUE TITLE
当滚动列的行高变化时，固定列的行高不会同步变化 fixed column height would not change when scroll column height change 固定列

### ISSUE THREAD

**Issue by rade1995** [ant-design/ant-design#14859]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8zn1xlv2p9)

### Steps to reproduce
在input内输入任意值
 enter some values 

### What is expected?
无论是固定列高度变化还是滚动列高度变化，固定列高度和滚动列高度一致 
fixed column height is the same as the scroll column height

### What is actually happening?
固定列或者滚动列有任一方高度在运行中变化时，另一方高度不会变化
 fixed column height is different from the scroll column height

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.8.1 |
| System | win10 |
| Browser | chrome, version: 72.0.3626.96 |

---
可编辑表格内期望更友好的用户体验，在用户输入时保持和form一致的错误提示方式，但在下方提示错误信息会导致行高变化，此时会出现固定部分和滚动部分错位。

**Comment by rade1995** [comment]
期望得到是否会升级此部分的答复,或者一点点的建议

**Comment by afc163** [comment]
Could you try to help us fix this issue by sending PR to http://github.com/react-component/table (maybe), we are out of hands for so many open issues now.

**Comment by afc163** [comment]
Actually, this problem could be a little tricky and I can't see good solution at first sight.

**Comment by rade1995** [comment]
we will try :)

**Comment by chenlizan** [comment]
这个问题要修复rc-table
https://github.com/react-component/table/blob/master/src/Table.js文件的239行syncFixedTableRowHeight函数
Table的左右固定列都是单独贴上去的table，你需要通过ant-table-fixed-left或ant-table-fixed-right找到固定列，并且获得行高，同步到ant-table-fixed

**Comment by chenlizan** [comment]
![image](https://user-images.githubusercontent.com/10942164/52892640-42c97100-31cf-11e9-8202-2877bf193f4c.png)

**Comment by rade1995** [comment]
!!感谢，这样会省去我很多时间

**Comment by rade1995** [comment]
由于之前就使用table的components属性将默认的tableRow覆盖，我们在自身的组件上实现了不是很好的方法。大体为render的每个td的内容都会被一个divA包裹，我们计算一行中每个td最高的divA高度作为tr的真实最大高度，在重写的tableRow组件中实现每一部分可以获取到其它部分的此行最大高度，在每一部分重新渲染后都会通知另外两个部分重新计算最大高度。

**Comment by chenlizan** [comment]
自身组件上实现为啥不好，怕影响性能吗。编辑表格不光要撑开到一样高度还有退出编辑态再缩回去的逻辑。

**Comment by rade1995** [comment]
> 自身组件上实现为啥不好，怕影响性能吗。编辑表格不光要撑开到一样高度还有退出编辑态再缩回去的逻辑。

自身组件上实现没什么问题，只是我们的获取高度和设置高度的方法不是很优，可能大部分人的需求是antd本身解决这个问题。不知你是否有时间向antd提交你已修改的rc-table这部分

**Comment by codercatmomi** [comment]
关注，拉了最新的 rc-table代码并没有修复这个问题

**Comment by ivanberry** [comment]
关注一下，是需要更新rc-table吗？我这边是拓展行展开后，固定列高度会未更新

**Comment by ivanberry** [comment]
@codercatmomi 你怎么拉取最新的rc-table的呀？

**Comment by codercatmomi** [comment]
> 最新的rc-table的呀？

我最重新install了一下 rc-table 的最新版

**Comment by chenxiaochun** [comment]
所以，目前为止还没有解决办法吗？😲

**Comment by chenxiaochun** [comment]
我目前只是暂时解决了一下，如果你的行高是固定的，可以先把它写死临时解决一下。

**Comment by codercatmomi** [comment]
> 我目前只是暂时解决了一下，如果你的行高是固定的，可以先把它写死临时解决一下。

我也是这么干的 ToT

**Comment by liuhuagui** [comment]
@zombieJ 不好意思， 这个问题依然处于解决中，是吗

**Comment by yoyo837** [comment]
@liuhuagui 很显然，属于遗留问题，暂未处理。

**Comment by liuhuagui** [comment]
> @liuhuagui 很显然，属于遗留问题，暂未处理。

@yoyo837 多谢

**Comment by zombieJ** [comment]
@liuhuagui , v3 中通过模拟固定列的方式来实现等高，但是会有触发时机的问题。v4 里解决了，但是 v3 为了兼容性和性能的权衡修不了。

ref：https://zhuanlan.zhihu.com/p/102037418

**Comment by liuhuagui** [comment]
@zombieJ @yoyo837 本来以为是文档没有看仔细，想寻求官方的配置方式来解决该问题。既然官方仍在处理中，在这里给出自己的解决方案，希望能够帮到其他同学。
https://blog.csdn.net/qq_32331073/article/details/103978188

**Comment by afc163** [comment]
升级到 4.x 即可完美解决。

**Comment by lofayo** [comment]
> 这个问题要修复rc-table
> [https://github.com/react-component/table/blob/master/src/Table.js文件的239行syncFixedTableRowHeight函数](https://github.com/react-component/table/blob/master/src/Table.js%E6%96%87%E4%BB%B6%E7%9A%84239%E8%A1%8CsyncFixedTableRowHeight%E5%87%BD%E6%95%B0)
> Table的左右固定列都是单独贴上去的table，你需要通过ant-table-fixed-left和ant-table-fixed-right找到固定列，ant-table-fixed找到中间部分，获取三部分的行高，取最大值同步到个表格

链接打开404了。这个版本，也没找到你对应需要修改的文件
        "react": "16.9.0",
        "antd": "3.26.14",

**Comment by liangzhicong** [comment]
鸡肋一点，当内容宽高发生变化时，触发一下window.resize 事件可以解决

**Comment by qiutian00** [comment]
> 鸡肋一点，当内容宽高发生变化时，触发一下window.resize 事件可以解决

resize事件，是需要做啥处理呢？

**Comment by hqm012** [comment]
> > 鸡肋一点，当内容宽高发生变化时，触发一下window.resize 事件可以解决
> 
> resize事件，是需要做啥处理呢？

@qiutian00  根据他的描述，我尝试了一下，是可行的
```js
useEffect(()=>{
        const myEvent = new Event('resize');
        window.dispatchEvent(myEvent)
    }, [fetchedData])
```
