### ISSUE TITLE
Card component nested table

### ISSUE THREAD

**Issue by fikyair** [ant-design/ant-design#14853]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r1oz5579zn)

### Steps to reproduce
- Open the codesandbox
- Review code
- Narrow your browser, for example，you can set pixel to 571*391

### What is expected?
The data in the table does not overflow the card component

### What is actually happening?
The data in the table overflows the outer card component

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.3.2 |
| System | osx |
| Browser | 15 |

---
Component nesting

**Comment by afc163** [comment]
Try https://codesandbox.io/s/4837z58q49
