### ISSUE TITLE
Localprovider does not include Chinese internationalization(zh_CN) in 2.13.9

### ISSUE THREAD

**Issue by fikyair** [ant-design/ant-design#14850]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2x.ant.design/components/locale-provider/](https://2x.ant.design/components/locale-provider/)

### Steps to reproduce
https://2x.ant.design/components/locale-provider/

### What is expected?
I hope to add the zh_CN dependency package to the Localprovider.

### What is actually happening?
I hope to add the zh_CN dependency package to the Localprovider.

| Environment | Info |
|---|---|
| antd | 2.13.9 |
| React | 15.6.1 |
| System | osx |
| Browser | 15 |

---
I hope to add the zh_CN dependency package to the Localprovider.

**Comment by ztplz** [comment]
Please try to use `Antd 3.x`.

**Comment by afc163** [comment]
antd@2.x is not maintained anymore.

**Comment by fikyair** [comment]
so..
