### ISSUE TITLE
Upload组件无法使用

### ISSUE THREAD

**Issue by schwanncheung** [ant-design/ant-design#14851]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wo0kz27r7w)

### Steps to reproduce
更新最新版 antd 后，上传组件无法正常使用，如demo 中，对第2张图片进行上传操作

### What is expected?
图片上传成功并且组件显示正常

### What is actually happening?
当上传第2张图片时，文件虽然在服务端被接受成功，但网络请求最终被 canceled，组件也无法正常显示进度，处于不可用状态。

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | latest |
| System | Mac OS |
| Browser | Chrome |

---
经测试，antd 3.13.0 版本正常，从3.13.1版本后出现异常，可能主要在于图片数量控制这里，当 `fileList.length >= 2` 时，上传不了第2张

**Comment by afc163** [comment]
Fixed in #14779, will be released in this weekend.
