### ISSUE TITLE
Skeleton doesn't animate in Menu

### ISSUE THREAD

**Issue by orzechdev** [ant-design/ant-design#14860]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/orzechdev/pen/qgJMOq](https://codepen.io/orzechdev/pen/qgJMOq)

### Steps to reproduce
Put Skeleton into Menu.

### What is expected?
Animation should work.

### What is actually happening?
Animation doesn't work.

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.8.2 |
| System | Ubuntu 18.04.2 |
| Browser | Opera 58.0.3135.65 |

**Comment by ztplz** [comment]
Why do you want to use `Skeleton` in the `Menu`? If you want to use it, please use it in the `Menu.item`.

**Comment by orzechdev** [comment]
Seems it solves the problem. Thank you.

**Comment by CarlosAmaral** [comment]
https://codepen.io/Perseus_/pen/oNvEaNp 
Not working under Sider either
