### ISSUE TITLE
Dropdown隐藏overlay

### ISSUE THREAD

**Issue by zxyah** [ant-design/ant-design#1486]
默认在overlay点击后会自动隐藏
发现官方也没有提供不隐藏的api，翻看源码，看到rc-dropdown是提供有这属性的
https://github.com/react-component/dropdown
配合visible和onVisibleChange一起使用可以实现，希望可以在api里体现出来，可能其他人还有同样的需求

**Comment by eaielo** [comment]
我这有个需求，为了方便交互，需要在Dropdown里增加一个InputNumber 数字输入框组件，
由于没法控制隐藏overlay，点击InputNumber的按钮后，overlay就被收起了，导致无法完成这一的交互。
只好弹个窗让用户选数字，繁琐了好多。

**Comment by zxyah** [comment]
这样实现的：
`
<Dropdown overlay={dropDownContent}
                                  onVisibleChange={(visible) => {this.setState({visible: visible});}}
                                  visible={this.state.visible}>
                        </Dropdown>
`

**Comment by zxyah** [comment]
我是这样实现的：
Dropdown overlay={dropDownContent} onVisibleChange={(visible) = {this.setState({visible: visible});}} visible={this.state.visible} /Dropdown 

你可以参考下


原始邮件
发件人:Wu Wenbinnotifications@github.com
收件人:ant-design/ant-designant-design@noreply.github.com
抄送:zxyahzxyah@126.com; Authorauthor@noreply.github.com
发送时间:2016年4月22日(周五) 17:14
主题:Re: [ant-design/ant-design] Dropdown隐藏overlay (#1486)


我这有个需求，为了方便交互，需要在Dropdown里增加一个InputNumber 数字输入框组件，
 由于没法控制隐藏overlay，点击InputNumber的按钮后，overlay就被收起了，导致无法完成这一的交互。
 只好弹个窗让用户选数字，繁琐了好多。

**Comment by afc163** [comment]
合理，参照 Popover 来个 PR 如何？

**Comment by zxyah** [comment]
好的
