### ISSUE TITLE
Table's rowSelection hideDefaultSelections is ignored

### ISSUE THREAD

**Issue by hedleygois** [ant-design/ant-design#14863]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/hedley/pen/YBJRaG](https://codepen.io/hedley/pen/YBJRaG)

### Steps to reproduce
It's simple. Just try to use the flag hideDefaultSelections. It was supposed to hide the checkboxes but it doesn't.

### What is expected?
Hide the selection's checkboxes.

### What is actually happening?
Nothing. 

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | react/16.6.3 |
| System | macOS 10.14.3 |
| Browser | Chrome 72 |

**Comment by zombieJ** [comment]
`hideDefaultSelections` is hide `select all` & `invert select`. Not hide checkbox. You can try this for understand:
```jsx
const rowSelection = {
  ...
  hideDefaultSelections: true, // false
  selections: true,
};
```

**Comment by yoyo837** [comment]
我感觉他是要：表格里数据有互斥的，不能全选。咋控制？

**Comment by zombieJ** [comment]
@yoyo837,  not your description. Just miss understand of `hideDefaultSelections`.

**Comment by Yoping** [comment]
So, how can we hide the checkbox ? @zombieJ

**Comment by zombieJ** [comment]
Currently not provide directly api for this. You can use css to hide it.

**Comment by Jetsly** [comment]
@zombieJ why are [doc](https://ant.design/components/table/#rowSelection) have it

**Comment by Jetsly** [comment]
@zombieJ why are [doc](https://ant.design/components/table/#rowSelection) have it

**Comment by yoyo837** [comment]
@Jetsly Just CSS override, no doc.
