### ISSUE TITLE
按照官方推荐按需加载启动后还是有警告信息

### ISSUE THREAD

**Issue by paulfrom** [ant-design/ant-design#14868]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-with-create-react-app-cn](https://ant.design/docs/react/use-with-create-react-app-cn)

### Steps to reproduce
#14867 完全按照官方配置进行

### What is expected?
无警告信息 ，有个相关的 issue #3156，但是没有说控制台警告信息，可能是换了插件的原因

### What is actually happening?
有警告信息

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.5.2 |
| System | macOS |
| Browser | Chrome 版本 72.0.3626.109（正式版本） （64 位） |

**Comment by afc163** [comment]
我又走了一遍没发现任何警告信息，你可以直接试试 clone 这个仓库 https://github.com/ant-design/create-react-app-antd/ ，如果还有问题请提供可重现的仓库。
