### ISSUE TITLE
getFieldDecorator validation returns prop type error

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#14865]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5295vjjzy4)

### Steps to reproduce
1. Create a custom form element
2. Wrap input field in getFieldDecorator 
3. Enter any values into the input field and see the output in the console.

### What is expected?
getFieldError should return one of ["success","warning","error","validating",""].

### What is actually happening?
getFieldError is returning the error message

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.7.0 |
| System | Windows 10 |
| Browser | Chrome 72 |

**Comment by yesmeck** [comment]
It's expected behavior. Please refer to the documentation https://ant.design/components/form/?locale=en-US#API
