### ISSUE TITLE
AutoComplete数据重叠

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design#14866]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/z3k237xyo4](https://codesandbox.io/s/z3k237xyo4)

### Steps to reproduce
例如快速输入 vpn111，会出现vpn11 和vpn111结果重叠的现象，如果输入慢则没问题。
确认了log，dataSource传入的数值是正确的
提一下，我是输入时从后台拿到数组再set入dataSource

### What is expected?
快速输入 vpn111时，出现正确结果

### What is actually happening?
快速输入 vpn111，会出现vpn11 和vpn111结果重叠的现象

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.4.1 |
| System | win10 |
| Browser | chrome |

**Comment by chenlizan** [comment]
XX建筑有个组件和这个一样，叫AutoSelect。
我们先前也有这个问题，就是数据异步请求慢了的问题。
因为你每次输入的时候要去后台查询数据再setState到dataSource。但如果很快数据你会很短时间发起多个请求。这个请求返回速度是不可以控制的，最终回填AutoComplete的时候照成了你说的现象。
我在组件逻辑里是这么解决的，如下图。我建议你直接用rc-trigger,rc-menu自己做一个类似组件。
yylib-react 里有完整代码
![image](https://user-images.githubusercontent.com/10942164/52895568-7ae4aa00-31f7-11e9-855b-e92a17f59320.png)
![image](https://user-images.githubusercontent.com/10942164/52895577-a2d40d80-31f7-11e9-9f7d-25d8aef05ca9.png)

**Comment by Veigar-C** [comment]
getTip = (keywords)=>{
    this.setState({
      tips: []
    },()=>{
      if(keywords!==''){
        const { dispatch } = this.props;
        dispatch({
          type: `globalSearch/getTips`,
          payload:{
            keyword: keywords,
          },
          callback:(res)=>{
            if(res.success){
              this.setState({
                tips: res.tips,
              })
            }
          }
        })
      }
    });
  };
我是有先将tips清空的，并且打印了tips也是正确的，
但还是发现了数据重叠的情况， 
@chenlizan

**Comment by chenlizan** [comment]
你先理解我发的第一张图149行和150行，clearTime和setTimeout的意图。
我这样写对付那种输入框快速输入。免得在很多时间内做不必要的后台异步请求。
第二张图针对那种后台服务超级慢的，500毫秒后又输入了字符，但先一个请求没有反回，需要丢弃第一个请求结果。
只能提供思路

**Comment by Yangzhedi** [comment]
@Veigar-C 要不你上传个动图？

**Comment by Veigar-C** [comment]
https://codesandbox.io/s/z3k237xyo4
输入ab, 输快点，然后少一位到a？

**Comment by afc163** [comment]
> @Veigar-C 要不你上传个动图？

**Comment by Veigar-C** [comment]
你看link嘛，你输入ab 是不是有两个vpn3的数据
然后你back个b， vpn3值有三个
@afc163

**Comment by afc163** [comment]
dataSource 里不要用相同的 item，组件会拿内容做 key，相同的 key 会导致 React 渲染异常。

**Comment by Veigar-C** [comment]
```
const tips = new Set(res.tips);
this.setState({
    tips: Array.from(tips),
})
```
意思是使用AutoComplete，还得处理重复数据后再传入?
@afc163

**Comment by afc163** [comment]
对的，重复数据对于 AutoComplete 没有意义。
