### ISSUE TITLE
Why calendar show full days in next week?

### ISSUE THREAD

**Issue by nghiepit** [ant-design/ant-design#14872]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar/](https://ant.design/components/calendar/)

### Steps to reproduce
![screen shot 2019-02-17 at 5 35 51 pm](https://user-images.githubusercontent.com/4768095/52911975-8dd1aa00-32dd-11e9-9957-0b6caa9539c8.png)

### What is expected?
Calendar component show days in the next week. 

### What is actually happening?
Calendar component don't' show days in the next week. 

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | react |
| System | macOS |
| Browser | Chrome |

**Comment by ztplz** [comment]
It is designed in such a way that the highlighted ones indicate the month you selected, and the gray ones indicate the other months.

**Comment by nghiepit** [comment]
But all days this week are in next month

**Comment by nghiepit** [comment]
But all days this week are in next month.

**Comment by ztplz** [comment]
I known, but for convenience, the number of lines is fixed at 6.

**Comment by zombieJ** [comment]
Hi @nghiepit , you can ref @ztplz 's reply.
We fix the row count to avoid height change when user change the date. And also make prev / next day of week as gray to identify.
