### ISSUE TITLE
Get blurred screen when added Tabs component

### ISSUE THREAD

**Issue by WoodenPC** [ant-design/ant-design#14876]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/25397745/52912210-15182100-32d0-11e9-8c4d-9ae1885b0fc8.png](https://user-images.githubusercontent.com/25397745/52912210-15182100-32d0-11e9-8c4d-9ae1885b0fc8.png) sorry i can paste only screen

### Steps to reproduce
In google chrome. Add basic form example from official antd site->add 2 tabs(it may 2 tabs with same content)-> check  render

### What is expected?
not getting blurred screen i guess :)

### What is actually happening?
getting blurred screen in chrome, in mozilla and edge all seems to be working fine

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.8 |
| System | linux mint 19 |
| Browser | 71.0.3578.98 |

---
tested on linux and windows

**Comment by ztplz** [comment]
Could you provide an online demo or `mini git repo`? It's so hard to figure out from just a picture.

**Comment by WoodenPC** [comment]
@ztplz take a look pls https://github.com/WoodenPC/antd-form-bug-test

**Comment by afc163** [comment]
Is it the Tabs component cause bluring?

**Comment by WoodenPC** [comment]
@afc163 no, i removed them and checked again, getting same results

**Comment by ztplz** [comment]
@WoodenPC It seems work fine in my mac. Have you tried only on `liunx`?
![image](https://user-images.githubusercontent.com/17755202/52954240-a2d53880-33c4-11e9-8f24-6d6a0ed2a26e.png)

**Comment by WoodenPC** [comment]
also tested on windows

**Comment by ztplz** [comment]
@zombieJ  Please test on `win`.

**Comment by zombieJ** [comment]
what's your screen resolution?

**Comment by WoodenPC** [comment]
1920x1080

**Comment by zombieJ** [comment]
Hmmm... Since we can't reproduce this. May ask more info about this.

Is this only happened on antd or only happened when form wrapped in a tab?

**Comment by WoodenPC** [comment]
It is happened only when antd form wrapped in antd tab(using google chrome), i tried  to use material ui tabs, and it looks nice(antd form wrapped in material ui tab)

**Comment by afc163** [comment]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/507615/52989092-d9e73080-343c-11e9-8a98-e8e4786fb833.png">

You give me wrong hints 😢

**Comment by WoodenPC** [comment]
@afc163 i mean, i removed styles, sorry for mis understood, also without tabs form renders without blur. I think tabs component cause bluring.
P.S. my english is bad :)

**Comment by zombieJ** [comment]
@WoodenPC, could you help to check if only use Input & Button component without Form. Is that still blur?

**Comment by WoodenPC** [comment]
@zombieJ  yes, i made a couple screen so you can see difference
in edge all looking good
![edge](https://user-images.githubusercontent.com/25397745/53012118-ecc12b80-3463-11e9-9671-1f9d41abb565.PNG)
in chrome its looking better than when i used form but still blurred
![chrome](https://user-images.githubusercontent.com/25397745/53012031-b388bb80-3463-11e9-8c08-29c0db307fa9.PNG)
please dont tell me that its my imagination :)

**Comment by ztplz** [comment]
It seems to be related to `dpi`. Can you adjust the `dpi` to try it?

**Comment by afc163** [comment]
Nothing we can do cause we cannot reproduce it, please feel free to dig in and send us PR.
