### ISSUE TITLE
Table自定义列功能在哪

### ISSUE THREAD

**Issue by zxyah** [ant-design/ant-design#1487]
看[官方文档](http://ant.design/docs/pattern/complex-table)有自定义列功能，可是没找到API
是这功能没实现吗
![image](https://cloud.githubusercontent.com/assets/3394312/14736347/228f0a5a-08a9-11e6-8bff-b717c0e57125.png)

**Comment by benjycui** [comment]
Pattern 下只是一些如果组合现有组件的建议，并不是现成的组件。

**Comment by longhuasishen** [comment]
有实现么，还有横向滚动条那个样例怎么组合

**Comment by zxyah** [comment]
自己写吧， 我自己写的

**Comment by longhuasishen** [comment]
求分享啊

**Comment by zxyah** [comment]
公司项目里，代码不方便拿出来
把columns放到state里，动态的修改columns就可以做到动态列啊
