### ISSUE TITLE
在登录页面打开Modal时登录密码被重置

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#14884]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/gonenoob/loginWithModal](https://github.com/gonenoob/loginWithModal)

### Steps to reproduce
在线地址https://www.dingxiang-inc.com/open-modal-reset-pwd/index.html#/
1输入账号密码点login让浏览器记录下账号密码 2 返回登录页修改密码点openModal 3 f12可以看到dom中密码已经被重置成浏览器记录下的密码

### What is expected?
打开Modal时，Input的密码仍然是用户输入的密码

### What is actually happening?
打开Modal时，Input的值被重置成浏览器记录的密码

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | ^16.4.2 |
| System | mac |
| Browser | chrome |

---
不太确定是antd组件的问题还是chrome本身的bug

**Comment by zombieJ** [comment]
看表现是挺奇怪的，应该不是 antd 的问题。
你能给个最小的在线重现不？https://u.ant.design/codesandbox

**Comment by afc163** [comment]
需要最小重现，你这里面太多无关代码了。

**Comment by zombieJ** [comment]
你这个跑不起来，我剥了一下：https://m46y5monmx.codesandbox.io/

**Comment by ztplz** [comment]
不是bug  firefox和chrome保存密码的behivor好像不同

**Comment by zombieJ** [comment]
@ztplz ，你看一下我剥下来的例子。弹出 Modal 会重置密码输入框，这个太诡异了。

**Comment by ztplz** [comment]
好像是chrome自动填充了

**Comment by zombieJ** [comment]
去掉了 antd，应该是 rc-dialog 引起的：https://codesandbox.io/s/xj055jn5ww

**Comment by ztplz** [comment]
autocomplete的问题

**Comment by zombieJ** [comment]
验证下来，Chrome 的输入组件在 body 被 append 新的输入组件后会重置掉并且触发 onChange 事件：
https://0o0r7qqmpl.codesandbox.io/

`rc-dialog` 中正好有一个关闭按钮导致被重置了。

推测是 Chrome 为了支持异步初始化输入框的自动填充做的逻辑，antd 这边做不了什么。

**Comment by BingXiong1995** [comment]
我也遇到了这个问题，<Input.Password />被自动填充了，即使设置了initialValue也没有用。

**Comment by zombieJ** [comment]
> 我也遇到了这个问题，<Input.Password />被自动填充了，即使设置了initialValue也没有用。

见上，这是 Chrome 的默认行为。不用 antd 加组件也会自动填。
