### ISSUE TITLE
Pagination 每页条数显示英文

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#14887]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/53n2nknzr4)

### Steps to reproduce
界面显示问题

### What is expected?
显示为 30条 / 页

### What is actually happening?
显示为 30 / page

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | React16.7.0 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

**Comment by LeeVirtue** [comment]
how to solve it?
