### ISSUE TITLE
can't use change the theme

### ISSUE THREAD

**Issue by sunshixiong789** [ant-design/ant-design#14892]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
const { override, fixBabelImports, addLessLoader } = require("customize-cra");

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
    style: true
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { "@primary-color": "#1DA57A" }
  })
);

### What is expected?
true

### What is actually happening?
yarn run v1.13.0
$ react-app-rewired start
Starting the development server...

Failed to compile.

./node_modules/antd/es/button/style/index.less (./node_modules/css-loader??ref--6-oneOf-7-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-7-3!./node_modules/antd/es/button/style/index.less)
Error: Cannot find module 'less'

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | 16.8.2 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
Did you forget add `less` and `less-loader` as instruction?

https://ant.design/docs/react/use-with-create-react-app-cn#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%BB%E9%A2%98

**Comment by sunshixiong789** [comment]
soory, I only see less-loader,not add less, think you

**Comment by iancdma** [comment]
I installed all the proper packages on mine (https://github.com/ant-design/ant-design/issues/15663) but it's not loading the style at all.

**Comment by fodurrr** [comment]
I have the same issue like @iancdma  (#15663) should not be closed, custom theme does not work with the latest create-react-app.

**Comment by manpenghui** [comment]
1.when  u  import the style   use the less  not css
```
@import '~antd/dist/antd.less';
```
