### ISSUE TITLE
datapicker 8小时时差问题

### ISSUE THREAD

**Issue by 406224330** [ant-design/ant-design#14890]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/10021](https://github.com/ant-design/ant-design/issues/10021)

### Steps to reproduce
这个问题有好几个人都已经提过了，八小时的问题，在form中，提交的json数据会少8小时，8小时不够扣回弄成昨天的日期，好像都没给出来明确的答案啊，真心求助，不会整。

### What is expected?
不需要知道原因，只需要答案，怎么解决这个8小时的问题。

### What is actually happening?
json数据里少了8小时

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | antd pro |
| System | WIN10 |
| Browser | GOOGLE |

**Comment by afc163** [comment]
[#6236 (comment)](https://github.com/ant-design/ant-design/issues/6236#issuecomment-308050178)
#13795

**Comment by chenlizan** [comment]
你们是不是拿到了datapicker数据是Date类型，然后提交的是后json.stringify()了。
如果这样恭喜了，json.stringify()原始问题

**Comment by afc163** [comment]
https://stackoverflow.com/a/31104671/

**Comment by 406224330** [comment]
![image](https://user-images.githubusercontent.com/21120585/52936691-e9f90480-3397-11e9-9ecc-9a80ff7e4768.png)
![image](https://user-images.githubusercontent.com/21120585/52936753-1dd42a00-3398-11e9-97f0-2a354c2f3534.png)
![image](https://user-images.githubusercontent.com/21120585/52936770-2dec0980-3398-11e9-8459-80e0cc6a89af.png)
用的antd pro，拿到了form数据直接提交了，我也不清楚日期内部是怎么处理，有没有什么方法能快速解决这个问题？

**Comment by chenlizan** [comment]
@afc163 我百分之80估计是JSON.stringify的问题。你跑下面的例子就知道了，早在antd1.10的库就发现了这个问题，以前返回值还是Date，JSON.stringify(Date)有时区的问题。
var moment = require('moment');
var dd = moment();
console.log(JSON.stringify(dd));
console.log(dd);

**Comment by wo-xiaoxiao** [comment]
解决了没呢
