### ISSUE TITLE
TreeSelect选择不能自动聚焦到选项

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#14897]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2pzjzjp39y)

### Steps to reproduce
选择一个下拉项，再次打开选项时，不能聚焦至所选的项，而是聚焦在第一项

### What is expected?
聚焦并滚动至选择的项

### What is actually happening?
TreeSelect选择一个选项后不能自动滚动到选择的项

| Environment | Info |
|---|---|
| antd | 3.11.2 |
| React | 15.6.1 |
| System | windows |
| Browser | chrome |

**Comment by junhui75165** [comment]
补充一下，搜索的时候不能搜索父节点内容，监听键盘上下回车按键也不支持 @yesmeck

**Comment by zombieJ** [comment]
@afc163 @yesmeck 
目前 TreeSelect 单选模式下的搜索框在弹出框里。如果我们自动帮用户定位到选中项，那搜索框就需要用户自己滚动上去填了。要不要让 TreeSelect 的单选模式搜索框也在上面？否则这个 issue 不太好处理。

ref: #9972

**Comment by zombieJ** [comment]
> 搜索框固定在浮层上面就好。

目前 `dropdownStyle` 是放在 popup 最外层的，搜索框设置 absolute 也是会跟着一起滚动。

**Comment by afc163** [comment]
把滚动区域改到里面。

**Comment by a958330481** [comment]
请问目前该问题解决了吗？用了getPopupContainer还是不行

**Comment by afc163** [comment]
看上面的提交应该已经在最新版内解决了，如果还有问题，欢迎开一个新的 issue。
