### ISSUE TITLE
FormItemLayout has no effect on the DatePicker

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design#14891]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mstao/pen/ErGEPR](https://codepen.io/mstao/pen/ErGEPR)

### Steps to reproduce
Click the reappear link， update the code
```
const formItemLayout = {
      labelCol: { span: 4 },
      wrapperCol: { span: 9 },
      colon: false,
    };
```
DatePicker length is no change.

### What is expected?
DatePicker length can be changed by setting formItemLayout.

### What is actually happening?
DatePicker length is no change.

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | 16.4.1 |
| System | Win10 |
| Browser | Google Chrome  71.0.3578.98 |

**Comment by afc163** [comment]
`<DatePicker style={{ width: '100%' />`

DatePicker has default width that you should override it.

**Comment by mstao** [comment]
Thanks
