### ISSUE TITLE
关于select选中值之后hover出现tip的问题

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design#14894]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前是利用select显示在导航位置

### What does the proposed API look like?
期望隐藏hover时会出现的白色tip框

**Comment by afc163** [comment]
Try set title to `' '`: https://codesandbox.io/s/y3q17k3q1

**Comment by liyue118** [comment]
> Try set title to `' '`: https://codesandbox.io/s/y3q17k3q1

thanks
