### ISSUE TITLE
No reaction in TreeNode for onRightClick

### ISSUE THREAD

**Issue by mholthausen** [ant-design/ant-design#14893]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xpjmry71qo)

### Steps to reproduce
Add the onRighClick property to a TreeNode and click with the right mouse button on it

### What is expected?
That a function is called, which does something when a TreeNode is clicked with the right mouse button.

### What is actually happening?
The console throws an error message: "Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `buttons` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information."

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | 16.8.2 |
| System | Linux Mint 19 |
| Browser | Chrome 72.0.3626.109 64-bit |

---
I need this function working to add a context menu to each TreeNode in order to open a context menu to it.

**Comment by ztplz** [comment]
It looks more like a problem with `codesandbox`. I copied your demo and ran it locally, no warnings have occurred.
![untitled7](https://user-images.githubusercontent.com/17755202/52938996-01d38700-339e-11e9-91ff-33487c8d5369.gif)

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/52939290-b9689900-339e-11e9-94d8-d35e1cbf31dd.png)

**Comment by zombieJ** [comment]
It's caused by when you console event in codesandbox, it will try to pass in the console window and get React error. Click to open in a new window will find it works as expect:
<img width="108" alt="2019-02-18 5 03 17" src="https://user-images.githubusercontent.com/5378891/52939495-4c093800-339f-11e9-8c1b-3ad944063c52.png">

**Comment by mholthausen** [comment]
Haven't tried it loaclly until yet. But then I will send this error to codesandbox.
