### ISSUE TITLE
Feature Request: Shareable visible status for <Modal> and <Tooltip>

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#14906]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
sandbox: https://codesandbox.io/s/4jwrxp7ml0

`Tooltip` can not response to parent element's `Modal`'s `visible` status.

```javascript
<Modal visible={false}> { /* change from true to false */}
  <Tooltip visible /> { /* ⬅️ always true */}
</Modal>
```

### What does the proposed API look like?
`visible` shareable between parent and children

**Comment by afc163** [comment]
https://codesandbox.io/s/940x1qo5v4

Try `getTooltipContainer={node => node.parentNode}` to render tooltip inside modal element.

**Comment by chiaweilee** [comment]
@afc163 Useful, why not include in docs?

https://github.com/react-component/tooltip/blob/master/README.md#props

**Comment by afc163** [comment]
<img width="960" alt="default" src="https://user-images.githubusercontent.com/507615/52961100-2565f400-33d5-11e9-9f1d-c26678b7bc72.png">
