### ISSUE TITLE
The className on the input does not take effect

### ISSUE THREAD

**Issue by Hughen** [ant-design/ant-design#14902]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
```jsx
<Input
  className="my-custom-class"
  addonAfter={(<span>hello addonAfter</span>)}
/>

// and real render:
<input
  {...otherProps}
  className={classNames(this.getInputClassName(prefixCls), {
    [className!]: className && !addonBefore && !addonAfter,
  })}
  onKeyDown={this.handleKeyDown}
  ref={this.saveInput}
/>
```

### What is expected?
Since the `Input` component has provided the `className`, you should not have other filters, and still without the developer's knowledge.
At the very least, you can't violate the design purpose of `className`. The style problems of `addonBefore` and `addonAfter` can be solved by other constraints.
```jsx
<input
  {...otherProps}
  className={classNames(this.getInputClassName(prefixCls), {
    [className!]: className,
  })}
  onKeyDown={this.handleKeyDown}
  ref={this.saveInput}
/>
```

### What is actually happening?
not exist `my-custom-class`

Also ask a question outside the question:
```typescript
{ [a!]: true }
```
what is the meaning of the exclamation mark in this, I found that there is no difference in exclamation mark...

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | react 16.7.0 |
| System | Ubuntu 18.04 |
| Browser | Chrome v71 |

**Comment by ztplz** [comment]
建议看下`classNames`这个库的用法，感叹号是断言。
如果你不在编译选项里设置strictNullCheck的话，它会默认所有的定义都是optional类型的。比如 `let a: string`, ts会认为这个a有可能是string，也有可能是undefined， 但是这时我确信这个值有，就用`!`。和 `as` 断言的区别是，`as` 是我认为这个变量是某一个类型，`!` 是我认为这个变量有值。

**Comment by Hughen** [comment]
@ztplz why did you turn off this issue?

**Comment by ztplz** [comment]
Feel free to reopen it if you have any question.

**Comment by Hughen** [comment]
The main question I raised has not been answered yet.

**Comment by ztplz** [comment]
所以你想问的的问题是？

**Comment by zombieJ** [comment]
`className` always work on Input.
* When only Input used, it works on input element: https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L275
* When affix used, it works on affix wrapper element: https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L235
* When `addonBefore/addonAfter` used, it works on group wrapper element: https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L205

Please notice that, className always works on the top of Input component element.
