### ISSUE TITLE
Can't select text in a text input when used in a draggable TreeNode

### ISSUE THREAD

**Issue by EmrysMyrddin** [ant-design/ant-design#14907]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4q2oylo8p7)

### Steps to reproduce
Try to select the text in the input by maintaining the mouse button pressed.

### What is expected?
Select the input text content

### What is actually happening?
It starts a drag of the TreeNode element

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | react@1.16.8 |
| System | macOS 10.14.3 |
| Browser | Chrome 72.0.3626.96 |

---
This is partially expected behavior.
But I haven't found any way to prevent dragging on my input. (see [here](https://codesandbox.io/s/n58wznw23l) for an example of what I tried)

**Comment by ztplz** [comment]
What confuse me is that since you don't want it to be able to drag, why do you want to set the `draggable`  to true?
![image](https://user-images.githubusercontent.com/17755202/52968297-ba71e880-33e7-11e9-9e20-0698e436ab9e.png)

**Comment by EmrysMyrddin** [comment]
I want the TreeNode to be draggable. In this minimal example, it's not obvious but in my real case, there isn't juste a single Input. There is other things the user can click on to begin a drag.

I juste want to prevent begin a drag when the mouse is on the input.

**Comment by ztplz** [comment]
Okay, I see. I updated your [demo](https://codesandbox.io/s/n3qm8kwjr0).

**Comment by EmrysMyrddin** [comment]
Yes, it's the workaround I'm using for now.

**Comment by EmrysMyrddin** [comment]
Hum, as I said, I'm doing this trick as a workaround... I think this is a bug since it's never the behavior you expect when using an Input.

Furthermore, this is buggy since there is a style difference between draggable and non draggable TreeNodes.

**Comment by ztplz** [comment]
I don't think this is a tricky way because it doesn't violate the way the component advocates it. Both `onFocus` and `onBlur` are the api exposed by the input component. What does the style difference you mean?

**Comment by EmrysMyrddin** [comment]
A draggable TreeNode has a border but a non draggable one hasn't. 
and since all CSS properties are transitioned, the border is animated and is fading in and out when losing focus.

For me, the problem is not that it's tricky or hard to do. the problem is that it's the user concern to handle this case. This should be handle in the library. Otherwise, every single developer trying to use this component will rewrite the same code (and perhaps miss some places where it should be donne...)

**Comment by ztplz** [comment]
I agree with some style optimizations, but there are not enough people to do these things at the moment.

**Comment by zy410419243** [comment]
It's better to reopen this, there is something wrong with style.

Issue died when closed, but problems won't.

**Comment by EmrysMyrddin** [comment]
I can understand this is not a hight priority issue 😄 I will try to open a PR if find a fix.

**Comment by zombieJ** [comment]
You can use onDragStart to decide whether drag needed: https://codesandbox.io/s/423j2qr6x4
