### ISSUE TITLE
DatePicker component,When the time format is HH:mm,the seconds and milliseconds are not automatically set to 0.

### ISSUE THREAD

**Issue by lihongbin100** [ant-design/ant-design#14901]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
Set time format is HH:mm,then to change value and to view timestamp.

### What is expected?
the seconds and milliseconds should be automatically set to 0.

### What is actually happening?
the seconds and milliseconds are not automatically set to 0.

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | react |
| System | mac |
| Browser | chrome 61 |

**Comment by afc163** [comment]
It is intent behavior, you can cut off extra second and provide a moment object as value of DatePicker if you need that.
