### ISSUE TITLE
Unable to set style on Input.Password

### ISSUE THREAD

**Issue by henrych4** [ant-design/ant-design#14900]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jvywm512zy)

### Steps to reproduce
Create a Input.Password component and try to set style on it.

### What is expected?
Style should be applied on input.
For example in https://codesandbox.io/s/jvywm512zy, text should start from right hand side.

### What is actually happening?
Style is not set on input tag but on upper span tag.
And style on input tag is set to null (https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L216).

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | 16.7.0 |
| System | macOs |
| Browser | chrome |

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L213
`style` is the style of the `span`, but it seems that giving `input` will be better.
@afc163  @zombieJ  Any suggestions?

**Comment by afc163** [comment]
```css
.ant-input input {
  text-align: inherit;
}
```

**Comment by mstfymrtc** [comment]
Any updates on this? I'am unable to style input.password or input.textarea whereas i can style original input component.

**Comment by sethstha** [comment]
This is how you can use it

```
<StyledPassword placeholder="input password" value={'password'} />

const StyledPassword = styled(Input.Password)`
  input {
    background-color: transparent;
    border-color: red;
    color: white;
    padding: 10px;
    height: auto;
    border-radius: 3px;
  }
`;
```

**Comment by romainchabrolin** [comment]
> This is how you can use it
> 
> ```
> <StyledPassword placeholder="input password" value={'password'} />
> 
> const StyledPassword = styled(Input.Password)`
>   input {
>     background-color: transparent;
>     border-color: red;
>     color: white;
>     padding: 10px;
>     height: auto;
>     border-radius: 3px;
>   }
> `;
> ```

Thanks !
