### ISSUE TITLE
3.13.4 .ant-form-explain-holder breaks all forms

### ISSUE THREAD

**Issue by bgold0** [ant-design/ant-design#14909]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

https://codesandbox.io/s/lrvj8w44xl

### Steps to reproduce
3.13.4
https://codesandbox.io/s/mzoyox81ny

3.13.2
https://codesandbox.io/s/k270rnyk9v

### What is expected?
All my forms should not be breaking. This is a breaking change.

### What is actually happening?
`.ant-form-explain-holder` is breaking all the forms adding unnecessary space.

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | 16.4.1 |
| System | Mac OSX |
| Browser | Chrome |

---
Why was this accepted and how do we disable the explain holder from breaking eveyone's forms?

**Comment by zombieJ** [comment]
Could you provide an online reproduce?

**Comment by fatefate0727** [comment]
出现了同样的情况
![1](https://user-images.githubusercontent.com/42198858/52997131-9dc2c880-345a-11e9-880e-5c5d7184a584.png)
![2](https://user-images.githubusercontent.com/42198858/52997139-a1564f80-345a-11e9-95c1-289bd6c62002.png)

**Comment by zombieJ** [comment]
@fatefate0727 ，方便给个重现吗？

**Comment by fatefate0727** [comment]
> @fatefate0727 ，方便给个重现吗？

https://github.com/fatefate0727/MessyProject

**Comment by zombieJ** [comment]
> > @fatefate0727 ，方便给个重现吗？
> 
> https://github.com/fatefate0727/MessyProject

你这东西太多了…………

**Comment by tangye1234** [comment]
@zombieJ 以前（3.13.3）是explain不存在的时候，explain holder是不占位的，现在（3.13.4）是，explain 存不存在，都占位，因此老的项目一旦升级，form-item之间的距离就变大了。
![image](https://user-images.githubusercontent.com/447084/53008481-737e0480-3474-11e9-8f3a-4471b7f992ce.png)

**Comment by zombieJ** [comment]
> @zombieJ 以前（3.13.3）是explain不存在的时候，explain holder是不占位的，现在（3.13.4）是，explain 存不存在，都占位，因此老的项目一旦升级，form-item之间的距离就变大了。
> ![image](https://user-images.githubusercontent.com/447084/53008481-737e0480-3474-11e9-8f3a-4471b7f992ce.png)

能给个重现吗？explain-holder 占的高度是以前 margin-bottom 的值，应该高度不变的。

**Comment by tangye1234** [comment]
@zombieJ 因为自己的项目都很大，但是，如果explain-holder使用的是以前margin-bottom的值，就有一些问题：
* 以前那些复写了form-item的margin-bottom，项目都得升级，为了适应新的explain-holder逻辑
* button不需要explain-holder，大部分人都会改写其外面的form-item的margin-bottom，遇到兼容问题

期望：
form-item 的 margin-bottom 和实际使用时的期望一致。

**Comment by zombieJ** [comment]
> @zombieJ 因为自己的项目都很大。直接讲问题吧，如果explain-holder使用的是以前margin-bottom的值，就有一些问题：
> 
> * 以前那些复写了form-item的margin-bottom，项目都得升级，为了适应新的explain-holder逻辑
> * button不需要explain-holder，大部分人都会改写其外面的form-item的margin-bottom，遇到兼容问题
> 
> 期望：
> form-item 的 margin-bottom 和实际使用时的期望一致。

你是通过 css class 来设置的 marginBottom 是吗？

**Comment by bgold0** [comment]
@zombieJ What if we have 100 of `Form.Item` without any `marginBottom`. So switching from 3.13.3 to 3.13.4 added extra space EVERYWHERE

**Comment by zombieJ** [comment]
临时先 .ant-form-explain-holder 设置 `display: none;`。之后给 ConfigProvider 加个 hideFormExplainHolder 属性让用户可以全局配置掉。

这个 .ant-form-explain-holder 是为了 fix 不同游览器下 FormItem 在有提示时高度不一致的问题。


You can set `.ant-form-explain-holder`  as `display: none;` temporary. Will add `hideFormExplainHolder` in ConfigProvider later to enable user remove the placeholder.

This `.ant-form-explain-holder` is to fix FormItems with message may not align height in some browser.

**Comment by bgold0** [comment]
> You can set `.ant-form-explain-holder` as `display: none;` temporary. Will add `hideFormExplainHolder` in ConfigProvider later to enable user remove the placeholder.

@zombieJ This would not be a good solution. 

[In 3.13.2](https://codesandbox.io/s/mq2zj6px) - notice that the `.ant-form-explain-holder` is hidden unless it is needed.

While [in 3.13.4](https://codesandbox.io/s/o56yq4yxo5) - it is always there.

I don't want to `display:none`. I have form validation in some area's but not in all so I can't just hide it globally.

**Comment by zombieJ** [comment]
Hmmm. Let's revert this first.

cc @afc163
