### ISSUE TITLE
Table header cells aren't aligned with the body cells when scrolling on both axes 

### ISSUE THREAD

**Issue by gion** [ant-design/ant-design#14904]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jvn38xv1lw)

### Steps to reproduce
Render a [<Table />](https://ant.design/components/table/#components-table-demo-fixed-columns) with border and specified width for all the columns and be sure to add the both `x` and `y` values to the `scroll` prop.
Something like:
```
<Table
  {...otherProps}
  bordered
  scroll={{ x: 1500, y: 300 }}
/>
```

### What is expected?
That you will see a table that's scrollable on both axis with the header cells aligned to the body cells. 

### What is actually happening?
The header cells aren't aligned with the body cells.

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | 16.8.2 |
| System | macOS Mojave 10.14.2 |
| Browser | Opera 58.0.3135.65 |

---
If I remove the `y` prop from the `scroll`, then everything is perfectly aligned.

Here are some screencasts that can help to better understand this issue:
 * http://g.recordit.co/8SvjxTw6Kg.gif
 * http://g.recordit.co/LcL1VTvw7a.gif
 * http://g.recordit.co/pfISWgZVbI.gif
 * http://g.recordit.co/em7lo5idDu.gif

**Comment by afc163** [comment]
https://codesandbox.io/s/5wq2my1jyl

The `Age` column has a small width(`40px`) which is not enough for `Age` table header, set it to `60px` or above to fit.

**Comment by omarragi** [comment]
Does version 4 fix the problem ? it seems it does
v4
https://codesandbox.io/s/fixed-header-ant-design-demo-7uc9e?file=/index.js
v3
https://codesandbox.io/s/cocky-fermat-mrth2?file=/index.js

**Comment by Gfast2** [comment]
![Screenshot from 2020-09-09 16-36-32](https://user-images.githubusercontent.com/2803903/92612962-b1db4e80-f2ba-11ea-9371-b389aa0b2362.png)
Hi everyone, 
may be there is only a occasional issue. I experienced the same issue, even the V4 example mensioned by @omarragi works out not as expected...

**Comment by dasani08** [comment]
I upgraded to v4.x and have same issues.

<img width="898" alt="Screen Shot 2020-09-18 at 09 40 55" src="https://user-images.githubusercontent.com/10113538/93604556-84b22e80-f993-11ea-8fa1-0a65fa1fca84.png">
