### ISSUE TITLE
DatePicker 星期和月份展示为英文

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#14917]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q346868l04)

### Steps to reproduce
设置LocaleProvider为zh-cn后，DatePicker 星期和月份展示为英文

### What is expected?
DatePicker 星期和月份展示为中文

### What is actually happening?
DatePicker 星期和月份展示为英文

| Environment | Info |
|---|---|
| antd | 3.13.3 |
| React | React16.7.0 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

**Comment by zombieJ** [comment]
不太明白，这不就是中文吗？
<img width="292" alt="2019-02-19 2 16 10" src="https://user-images.githubusercontent.com/5378891/52993955-ed03fb80-3450-11e9-9921-3ca004c6d3c6.png">

**Comment by zhang504988670** [comment]
在本地开发时，正常展示为中文，当点击下面的今天后，变成英文。
![image](https://user-images.githubusercontent.com/18161513/52994077-55eb7380-3451-11e9-88e0-7cb63afe734d.png)
点击清除按钮后，又重新变回英文。
正常选择日期没问题。

**Comment by afc163** [comment]
你要想办法给重现，否则互相猜来猜去效率很低。

**Comment by liaokaime** [comment]
> 在本地开发时，正常展示为中文，当点击下面的今天后，变成英文。
> ![image](https://user-images.githubusercontent.com/18161513/52994077-55eb7380-3451-11e9-88e0-7cb63afe734d.png)
> 点击清除按钮后，又重新变回中文。
> 正常选择日期没问题。

我也遇到了这个问题
