### ISSUE TITLE
svg sprite icon as tree switcherIcon flashes

### ISSUE THREAD

**Issue by kimochg** [ant-design/ant-design#14913]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yjk0n0k21x)

### Steps to reproduce
1. open the reproduction codesandbox
2. click the tree node of the upper demo, acts correctly
3. click the tree node of the bottom demo, the `switcherIcon` flashes

### What is expected?
switcherIcon don't flash

### What is actually happening?
using svg-sprite icon causes the icon flash issue

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | 16.8 |
| System | Mac |
| Browser | Chrome |

![2019-02-19 at 11 41](https://user-images.githubusercontent.com/16147702/52988798-9b04ab00-343b-11e9-9f30-4b297de70e2d.gif)

**Comment by zombieJ** [comment]
It's caused by web request the svg icon resource when display the svg by xlinkHref. It's not a antd bug:
![kapture 2019-02-19 at 11 55 18](https://user-images.githubusercontent.com/5378891/52989210-5b3ec300-343d-11e9-87d5-131ad71e84b2.gif)

**Comment by kimochg** [comment]
@zombieJ 
FYI, after digging a little deeper, I think it is highly related to these two lines of code:

- https://github.com/react-component/tree/blob/master/src/TreeNode.jsx#L314
- https://github.com/react-component/tree/blob/master/src/TreeNode.jsx#L323

**Comment by zombieJ** [comment]
It's caused by TreeNode removed when collapse and re-create after  expand. React.createElement not affect this.

**Comment by kimochg** [comment]
@zombieJ If you checked the GIF I uploaded closely, you can see that selecting the TreeNode also making the icon flashing. So IMO it comes from the state changed in parent react component, which makes the `swithcerIcon` re-rendered, because of the `React.createElement`. Is it make sense to you?

**Comment by zombieJ** [comment]
You are correct. It should not use `React.createElement` here.
