### ISSUE TITLE
当Drawer从上方或下方打开时能否控制宽度？

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#14914]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
文档中的`width`没有说明宽度只在`placement`为`left`或`right`时生效，但我在代码里找到
```js
if (placement === 'left' || placement === 'right') {
  offsetStyle.width = width;
} else {
  offsetStyle.height = height;
}
```
我现在的使用场景是当热线接通时从上方弹出一个控制台，效果类似下图：

![image](https://user-images.githubusercontent.com/23520283/52990255-47e22680-3442-11e9-8c04-53878d609f0f.png)

使用`style`也无法控制，所以想问这里该怎么实现？还是说我这个本身不应该这样设计？

### What does the proposed API look like?
```jsx
<Drawer visible mask={false} width={360} height={64} placement="top" />
```

**Comment by afc163** [comment]
从上方和下方打开时 Drawer 应始终和浏览器窗口等宽，此时不存在宽度这个属性。

**Comment by jaryway** [comment]
我有一个使用场景是，一级drawer从右侧向左滑出，点击一级drawer上的button，从底部向上滑出二级drawer，并且二级drawer的宽度不超过一级的drawer的宽度，一级drawer不要偏移！

**Comment by savelifeme** [comment]
@Liu-Ya   你解决了吗？我也有这样的需求
