### ISSUE TITLE
any plan to design TreeTable component for loading data async

### ISSUE THREAD

**Issue by agoni1212** [ant-design/ant-design#14919]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 loading data async

### What does the proposed API look like?
 loading data async

**Comment by afc163** [comment]
Duplicate of #14918

**Comment by afc163** [comment]
You can listen to `onExpand` and load dateSource from remote asynchronously.
