### ISSUE TITLE
InputGroup unexpected margin

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#14929]
https://ant.design/components/input-cn/#components-input-demo-group

<img width="463" alt="image" src="https://user-images.githubusercontent.com/507615/53001495-b5ec1500-3465-11e9-8cfc-a636ff64a9eb.png">

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/53025322-b0112680-349b-11e9-9ddd-ff7ab79ee862.png)
被这个污染了
https://github.com/ant-design/ant-design/blob/master/site/theme/template/Content/ComponentDoc.jsx#L114
