### ISSUE TITLE
TypeError: "parameter 1 is not of type "Element"." on Firefox.

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#14921]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://testbdweb.educoder.net/ec_courses/148/ec_course_support_setting](https://testbdweb.educoder.net/ec_courses/148/ec_course_support_setting)

### Steps to reproduce
I am using this code in a dynamic form. And I got the error on firefox when the form init. The code works fine on Chrome. Any ideas? Thanks.

```
{getFieldDecorator(`target_contents[${k}]`, {
                    // validateTrigger: ['onChange', 'onBlur'],
                    rules: [{
                        required: true,
                    //     whitespace: true,
                        message: "请填入目标内容",
                    }],
                })(
                <TextArea autosize placeholder="" style={{  width: '100%', marginRight: 8 }} />
            )}
```

```
/**
     * Starts observing provided element.
     *
     * @param {Element} target - Element to be observed.
     * @returns {void}
     */
    ResizeObserverSPI.prototype.observe = function (target) {
       if (!arguments.length) {
            throw new TypeError('1 argument required, but only 0 present.');
        }
        // Do nothing if current environment doesn't have the Element interface.
        if (typeof Element === 'undefined' || !(Element instanceof Object)) {
            return;
        }
        if (!(target instanceof getWindowOf(target).Element)) {
            throw new TypeError('parameter 1 is not of type "Element".');
        }
```

### What is expected?
no error.

### What is actually happening?
got error:
TypeError: "parameter 1 is not of type "Element"."

    observe ResizeObserver.es.js:778 e ResizeObserver.es.js:916 value TextArea.js:148 value TextArea.js:122 br react-dom.production.min.js:229 gr react-dom.production.min.js:220 vr react-dom.production.min.js:219 pr react-dom.production.min.js:216 ir react-dom.production.min.js:214

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.3.0-alpha.2 |
| System | windows10 |
| Browser | firefox 65.0.1 |

---
website id and password : kosasa04   kosasa33!
open the website and click edit button.

**Comment by afc163** [comment]
Any steps to reproduce it? The page works with no errors.

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/507615/52999890-f21d7680-3461-11e9-9c5e-239c1aae61e0.png">

**Comment by wufeng87** [comment]
please click the green edit icon button on the right of the page.

**Comment by afc163** [comment]
Great! I see the errors.

<img width="630" alt="image" src="https://user-images.githubusercontent.com/507615/53000522-90f6a280-3463-11e9-9de5-aaa476ea2169.png">

**Comment by wufeng87** [comment]
It works on my mac in dev environment..

**Comment by afc163** [comment]
https://github.com/souporserious/react-measure/issues/76#issuecomment-358448544
https://github.com/deepsweet/hocs/issues/15

something related from google.

**Comment by wufeng87** [comment]
It works now. But I don't know why. I changed nothing relate to it.

**Comment by afc163** [comment]
Eh....It may be a deploy issue.

Anyway, I will reopen if it comes out again.

**Comment by wufeng87** [comment]
可能是node版本的问题吗？我这边用mac node8的环境build后没问题。
mac node10或win10 node10的环境build后有这个问题。谢谢。

**Comment by zombieJ** [comment]
> 可能是node版本的问题吗？我这边用mac node8的环境build后没问题。
> mac node10或win10 node10的环境build后有这个问题。谢谢。

应该不会，感觉更像是 node_modules 的依赖出了问题。这边 CI 也是 node 10。

**Comment by wufeng87** [comment]
尝试升级antd的版本是否能解决这个问题呢？谢谢

**Comment by zombieJ** [comment]
可以试试把 antd & react 这些都升级上来。

**Comment by wufeng87** [comment]
能重新打开这个issue吗？最近在本地开发时也遇到了这个问题。感觉是Menu组件影响了这个判断。

去掉整个Menu，页面就能正常打开了：
![image](https://user-images.githubusercontent.com/1686808/61029202-136d0800-a3ed-11e9-9c2b-e764d86fb3d1.png)

留下Menu，就会报这个错：
![image](https://user-images.githubusercontent.com/1686808/61029209-18ca5280-a3ed-11e9-845f-d294fb1f90db.png)

**Comment by wufeng87** [comment]
antd从3.6升级到3.11后才会出现这个问题

**Comment by afc163** [comment]
@wufeng87 升级到最新版 antd 试试

**Comment by wufeng87** [comment]
好的

**Comment by wufeng87** [comment]
升级到antd3.20.1还是有同样的问题：
![image](https://user-images.githubusercontent.com/1686808/61030112-3dbfc500-a3ef-11e9-8519-32733d07532b.png)
![image](https://user-images.githubusercontent.com/1686808/61030341-c179b180-a3ef-11e9-9589-43c7837ec09b.png)

**Comment by afc163** [comment]
看看能不能搞一个重现到 github 上来。

**Comment by wufeng87** [comment]
嗯 我试试

**Comment by wufeng87** [comment]
不好意思，是我们自己的问题。
应该基本确定问题了，是有全局加载的js覆盖掉了Window.Element，会导致这个判断通不过：
`if (!(target instanceof getWindowOf(target).Element)) {`

**Comment by 465162390** [comment]
> 不好意思，是我们自己的问题。
> 应该基本确定问题了，是有全局加载的js覆盖掉了Window.Element，会导致这个判断通不过：
> `if (!(target instanceof getWindowOf(target).Element)) {`

你好，想问一下这个问题最后你怎么解决的，我现在也遇到了这个问题，也是跟你一样

**Comment by wufeng87** [comment]
@465162390 是某个js的代码把全局的Element改了，会导致if判断有误。具体不记得哪个js了，好像是和编辑器有关的js。
