### ISSUE TITLE
固定表头并且使用可伸缩列，对不齐问题

### ISSUE THREAD

**Issue by AlwaysBeOk** [ant-design/ant-design#14924]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk9z240n0j)

### Steps to reproduce
使用固定表头并且使用可伸缩列

### What is expected?
使用固定表头并且使用可伸缩列，拖动之后，表头与表体列对齐。

### What is actually happening?
使用固定表头并且使用可伸缩列，拖动之后，表头与表体列对不齐。

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | 16.2.0 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
Try

```
        scroll={{ x: 'max-content', y: 500 }}
```

https://codesandbox.io/s/lrl1102219

**Comment by AlwaysBeOk** [comment]
![image](https://user-images.githubusercontent.com/23167192/52999050-c5685f80-345f-11e9-9d38-f9a6c9ff9402.png)

Column 7777777777777    drag left is not align

**Comment by rmlzy** [comment]
> Try
> 
> ```
>         scroll={{ x: 'max-content', y: 500 }}
> ```
> https://codesandbox.io/s/lrl1102219


请问这里值为 `max-content` 是什么意思?

**Comment by afc163** [comment]
@rmlzy https://www.zhangxinxu.com/wordpress/2016/05/css3-width-max-contnet-min-content-fit-content/

**Comment by rmlzy** [comment]
@afc163 好的, 感谢~

**Comment by AlwaysBeOk** [comment]
![image](https://user-images.githubusercontent.com/23167192/54189079-09450680-44ec-11e9-92ce-f1a9f26a93eb.png)
order与动态列宽同时存在时，拖拽宽度会点击到排序，请问这个如何解决。
