### ISSUE TITLE
1.0beta版本的 babel 编译对 IE9 IE10支持的问题

### ISSUE THREAD

**Issue by shlice** [ant-design/ant-design#1492]
#### 现象
我将antd升级为1.0beta 版本（develop 分支）之后，IE9、IE10上很多组件无法使用，如 Table，DatePicker。控制台报错：
```
SCRIPT5007: 无法获取属性"columns"的值：对象为 null 或未定义。
```
#### 原因
经过我对代码的分析，发现 develop 分支使用了 es6语法写构造函数，在构造函数中直接或间接的通过 this.props访问 props。这种方式在 IE9和10上是不支持的。
Table 构造函数的代码片段：
```
 this.state = {
      // 减少状态
      selectedRowKeys: props.selectedRowKeys || [],
      filters: this.getFiltersFromColumns(),
      selectionDirty: false,
      ...this.getSortStateFromColumns(),
      pagination: this.hasPagination() ?
        {
          ...defaultPagination,
          ...pagination,
          current: pagination.defaultCurrent || pagination.current || 1,
        } : {},
    };
  }
```
其中`this.getFiltersFromColumns`中访问了 this.props。

究其原因，是 Babel6编译对 IE9、IE10的支持问题。
参见：<https://phabricator.babeljs.io/T6954>
<https://phabricator.babeljs.io/T3041>

#### 建议的解决方案
使用`babel-preset-es2015-ie`插件替代`babel-preset-es2015`
babel loader的 presets中 es2015 换成 es2015-ie。
这个方法目前测试可行。请参考。

我们目前的项目在使用antd@beta，希望下个 beta版本发布能够支持 IE9和10。谢谢：）

#### Environment Information

- and: "^1.0.0-beta.3"
- browser: IE9

**Comment by afc163** [comment]
貌似和这个类似：https://github.com/ant-tool/atool-build/pull/145

@sorrycc 看看 antd 里需要改什么？

**Comment by superRaytin** [comment]
之前踩过这个坑，Babel 6 编译继承的问题
http://leonshi.com/2016/03/16/babel6-es6-inherit-issue-in-ie10/

**Comment by sorrycc** [comment]
`babel-preset-es2015-ie` 不是 babel 官方维护的，担心升级和稳定性的问题得不到保障。事实上现在的 `babel-preset-es2015-ie` 和 `babel-preset-es2015` 的依赖库版本上已经存在很多差异。

我试下 @superRaytin 提供的插件的方式。https://github.com/ant-tool/atool-build/issues/126

**Comment by sorrycc** [comment]
在 atool-build@0.7.1 里修复了，详见：https://github.com/ant-tool/atool-build/issues/126#issuecomment-215307162

**Comment by shlice** [comment]
@sorrycc 1.0.0-beta.5版本开始antd/style/下面的 less 都是空的了。还有修复后是在哪个版本开始可用？

**Comment by sorrycc** [comment]
0.7.1

**Comment by shlice** [comment]
不是 atool-build，我是用npm安装的antd@beta

**Comment by afc163** [comment]
antd 用的是 atool-build 做的编译。

**Comment by afc163** [comment]
1.0.0-beta.6

**Comment by afc163** [comment]
less 文件有变动。https://github.com/ant-design/ant-design#usage-example

**Comment by shlice** [comment]
以前我是这样引入
@import "~antd/style/themes/default/index.less";
@import "antdcustom.less";
@import "~antd/style/core/index.less";
在antdcustom.less里面定义颜色，字体。实现自定义主题。那现在岂不不行了？

**Comment by afc163** [comment]
稍等，我再微调下。

**Comment by afc163** [comment]
`1.0.0-beta.7`, try this:

```css
@import "~antd/lib/style/themes/default.less";
@import "antdcustom.less";
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";
```

**Comment by shlice** [comment]
thanks
