### ISSUE TITLE
固定表头并且使用可伸缩列，对不齐问题

### ISSUE THREAD

**Issue by AlwaysBeOk** [ant-design/ant-design#14925]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk9z240n0j)

### Steps to reproduce
往左拖动 “Column 7777777777777” 这一列

### What is expected?
tbody 中列宽与表头一致对齐

### What is actually happening?
没有对齐

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | 16.2.0 |
| System | mac os |
| Browser | chrome |

图片参考链接：https://github.com/ant-design/ant-design/issues/14924

**Comment by afc163** [comment]
The long word `777777777777` breaks column width, try wrap it forcely:

https://codesandbox.io/s/6yz3089kvw
