### ISSUE TITLE
customize component initialValue  problem

### ISSUE THREAD

**Issue by githubyong** [ant-design/ant-design#14923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o1q9140woq)

### Steps to reproduce
click button "change"

### What is expected?
item1 value change by order

### What is actually happening?
item1's value not change

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | ^16.7.0 |
| System | windows7 |
| Browser | Chrome 71.0.3578.98 |

---
The difference between two item is that item1 use direct value,and item2 use json.  
We usually use direct value for common form item,so why customize form item can't use direct value?

**Comment by zombieJ** [comment]
It's caused by your customize code logic. If you want to read from `value`, just use it and not need read from `value.choice`: https://codesandbox.io/s/o4prvno4zq
