### ISSUE TITLE
When I use showSearch of Cascader, I can't type the right Chinese characters at the search box 

### ISSUE THREAD

**Issue by unamelcs** [ant-design/ant-design#14931]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/unamelcs/pen/NooLpw?&editable=true&editors=001](https://codepen.io/unamelcs/pen/NooLpw?&editable=true&editors=001)

### Steps to reproduce
Typing a 'fuwuqi' at the search box.

### What is expected?
I'd like to get a Chinese words like '服务器'

### What is actually happening?
we got a sentence like 'fuwuqi服务器'

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | reac |
| System | window 10 |
| Browser | chrome |

**Comment by Yangzhedi** [comment]
@unamelcs  you can try [this](https://codesandbox.io/s/20yq4zv9lj)
i think it is a bug caused by `fieldNames`

**Comment by unamelcs** [comment]
> @unamelcs you can try [this](https://codesandbox.io/s/20yq4zv9lj)
> i think it is a bug caused by `fieldNames`

Thank you for your answer . It works well without 'fieldNames ' as you said . In fact , It's better to use 'fieldNames ' in my job . Looking forward to getting the news that this bug is fixed.

**Comment by Yangzhedi** [comment]
> Thank you for your answer . It works well without 'fieldNames ' as you said . In fact , It's better to use 'fieldNames ' in my job . Looking forward to getting the news that this bug is fixed.

[https://codesandbox.io/s/010ov9qk6p](https://codesandbox.io/s/010ov9qk6p) 
this can work, can you find the difference between this one and your codepen link?

**Comment by afc163** [comment]
It is a react@16.8.2 bug that chinese chars cannot input in controlled mode: https://github.com/facebook/react/issues/14861

**Comment by unamelcs** [comment]
> It is a react@16.8.2 bug that chinese chars cannot input in controlled mode: [facebook/react#14861](https://github.com/facebook/react/issues/14861), and it only appears in CDN version of react.
> 
> https://codepen.io/afc163/pen/bzZjLd

Got it ! Thank you !

**Comment by afc163** [comment]
Close now cause nothing we can do.

**Comment by unamelcs** [comment]
> > Thank you for your answer . It works well without 'fieldNames ' as you said . In fact , It's better to use 'fieldNames ' in my job . Looking forward to getting the news that this bug is fixed.
> 
> https://codesandbox.io/s/010ov9qk6p
> this can work, can you find the difference between this one and your codepen link?

It seems there are no differences between the two code.  What's the main reason cause my result ?

**Comment by afc163** [comment]
codesandbox don't use the CDN version of react, codepen does.

**Comment by unamelcs** [comment]
> codesandbox don't use the CDN version of react, codepen does.

Got it ! thank you so much !
