### ISSUE TITLE
Select Component to get load more or func when user add item

### ISSUE THREAD

**Issue by zanisis** [ant-design/ant-design#14939]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
let say i have 100 data. but, in my API give me data 50 in first page 1 but i want go to next page i need load more or button to go to next page. because i need when user scroll for select not to height.

### What does the proposed API look like?
example = https://codepen.io/elmahdim/pen/sGkvH but i want need in select.

**Comment by afc163** [comment]
Try `onPopupScroll`.
