### ISSUE TITLE
引入组件，样式有点问题？

### ISSUE THREAD

**Issue by zhump** [ant-design/ant-design#1493]
使用方式如Github上的步骤
```js
import 'antd/lib/index.css';
const React = require('react');
const ReactDOM = require('react-dom');
import { DatePicker } from 'antd';
ReactDOM.render(<DatePicker />, document.querySelector('#wrapper'));
```
效果图如下：
![www](https://cloud.githubusercontent.com/assets/7962067/14762698/d57a6bea-09b3-11e6-8793-dd38bc269ec1.png)

这个字体变大了，跟官网的demo不一样

我又使用了官网的方式，搭建了一下环境，确实正常的字体大小
```js
$ npm install antd-init -g

npm run dev

```
效果图如下：
![af6ed7dc-d8d4-41a0-93ce-f86d24388505](https://cloud.githubusercontent.com/assets/7962067/14762761/a4c040a4-09b5-11e6-910c-e6c9f0c7dbbc.png)

是我哪里使用的方式不正确吗？

**Comment by afc163** [comment]
请确认全局样式（默认字体大小等）是否正确。

**Comment by zhump** [comment]
不好意思 确实是我的问题 ，，我少加了<!DOCTYPE HTML>
