### ISSUE TITLE
[RFC]  add comments in typescript interface.

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design#14940]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这样写代码的时候就不需要看 antd 的文档，只需要看代码。

### What does the proposed API look like?
点击 d.ts 文件就可以看到字段大致的用法。
可以用 英语 中文 来描述。

如果可以的话我可以提交 pr 慢慢改。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/53032332-a098da00-34a9-11e9-9998-a2fa7d65ebad.png)


![image](https://user-images.githubusercontent.com/9692408/53032357-ab536f00-34a9-11e9-8449-b414851bfe8b.png)

**Comment by DiamondYuan** [comment]
https://github.com/ant-design/ant-design/issues/3767


16年有人提到过。

**Comment by yesmeck** [comment]
注释如果能跟文档自动同步就好了，不然要维护两份。

**Comment by DiamondYuan** [comment]
> 注释如果能跟文档自动同步就好了，不然要维护两份。

应该是文档能和注释同步就好了。
脑中的第一个想法是文档里面 import 组件，然后编译文档的时候自动读取注释。

**Comment by DiamondYuan** [comment]
继续看了一下，似乎网站是通过 bisheng 生成的，组件来自于组件的markdown。
可能需要 bisheng 支持特殊语法，把读取 interface 的注释。

**Comment by DiamondYuan** [comment]
```
interface Demo {
  /**
   * name
   *
   * @language en_US
   *
   * @default "123"
   */
  /**
   * 姓名
   *
   * @language zh_CN
   *
   * @default "123"
   */
  name: string;
}
```







```javascript
const ts = require("typescript");
const fs = require("fs");
const path = require("path");

const filePath = path.resolve(__dirname, "./index.ts");

let sourceFile = ts.createSourceFile(
  "fileName",
  fs.readFileSync(filePath).toString(),
  ts.ScriptTarget.Latest,
  /*setParentNodes */ false
);

const member = sourceFile.statements[0].members[0];

console.log("字段 member");

member.jsDoc.forEach(element => {
  console.log(`${element.comment}`);
  console.log(
    element.tags.map(o => ({
      key: o.tagName.escapedText,
      value: o.comment
    }))
  );
});
```


result 
```
字段 member
name
[ { key: 'language', value: 'en_US' },
  { key: 'default', value: '"123"' } ]
姓名
[ { key: 'language', value: 'zh_CN' },
  { key: 'default', value: '"123"' } ]
```

**Comment by DiamondYuan** [comment]
@benjycui 可以考虑 bisheng 支持这个功能吗？解析 typescript 的文件，读取注释，然后渲染 markdown。

**Comment by ztplz** [comment]
接口要整理一下再搞  有点乱

**Comment by DiamondYuan** [comment]
插件写完了 https://github.com/yuquewebclipper/bisheng-plugin-typescript-interface
测试覆盖率 96%


```typescript
/** post/fixtures.tsx **/
type AnchorContainer = HTMLElement | Window;

interface ITestInterface {
  /**
   * @default `false`
   */
  /**
   * @language en-US
   * @description disabled state of button
   */
  /**
   * @language zh-CN
   * @description 按钮失效状态
   */
  disabled?: boolean;
  /**
   * @default `button`
   */
  /**
   * @language en-US
   * @description set the original html `type` of `button`, see: [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type)
   */
  /**
   * @language zh-CN
   * @description 设置 `button` 原生的 `type` 值，可选值请参考 [HTML 标准](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#attr-type)
   */
  htmlType?: string;

  /**
   * @default `false`
   */
  /**
   * @language en-US
   * @description set the loading status of button
   */
  /**
   * @language zh-CN
   * @description 设置按钮载入状态
   */
  loading?: boolean | { delay: number };
  /**
   * @language en-US
   * @description date
   */
  /**
   * @language zh-CN
   * @description 日期
   */
  value?: "one" | "two" | { delay: number };

  getContainer?: () => AnchorContainer;

  /**
   * Indexable Types @see http://www.typescriptlang.org/docs/handbook/interfaces.html
   */
  [propName: string]: any;

  /**
   * Function Types @see http://www.typescriptlang.org/docs/handbook/interfaces.html
   */
  (source: string, subString: string): boolean;

  1: () => void;
}
```

```typescriptInterface
{
    "filePath":"posts/fixtures.tsx",
    "interfaceName":"ITestInterface",
    "language":"zh-CN"
}
```

**Comment by afc163** [comment]
加一列 version 如何。#14818

**Comment by afc163** [comment]
原来的手写 API table 有一个优势，就是网站 down 掉也可以在 GitHub 阅读：https://github.com/ant-design/ant-design/blob/master/components/avatar/index.zh-CN.md#api 让我们试试改造后能保持这个优势。

**Comment by DiamondYuan** [comment]
> 原来的手写 API table 有一个优势，就是网站 down 掉也可以在 GitHub 阅读：https://github.com/ant-design/ant-design/blob/master/components/avatar/index.zh-CN.md#api 让我们试试改造后能保持这个优势。

可以在 GitHub 阅读源码的注释。

version 是什么意思？自动标注为当前代码的版本吗？

**Comment by afc163** [comment]
> 可以在 GitHub 阅读源码的注释。

可读性会比较差。

> version 是什么意思？自动标注为当前代码的版本吗？

指的是在 API 表格里加一列列出一些新 API 支持的版本，因为有些用户用了某个固定 3.x 的老版本，有时候会使用到不可用的 API。

**Comment by DiamondYuan** [comment]
version 问题好解决。只需要加一行配置就可以了。
```
interface ITestInterface {
  /**
   * @version 3.x.x
   */
  disabled?: boolean;
}
```


```typescriptInterface
{
    "filePath":"components/locale-provider/index.tsx",
    "interfaceName":"LocaleProviderProps",
    "language":"en-US",
    "columnNames":[
        {
            "label":"属性",
            "key":"name"
        },
        {
            "label":"说明",
            "key":"description"
        },
        {
            "label":"类型",
            "key":"types"
        },
        {
            "label":"默认值",
            "key":"default"
        },
       {
            "label":"需求版本",
            "key":"version"
        }
    ]
}
```



文档问题有些麻烦，写在注释上的话编辑器有代码提示，直接去看 GitHub 上 readme 的需求很少。
而且用户可以自己运行一下文档。

**Comment by DiamondYuan** [comment]
可以用 since 来代表需求的 version

中文和英文文案需要考虑一下。

**Comment by DiamondYuan** [comment]
我想了一下，如果要在GitHub阅读markdown表格，应该再写一个人cli工具，类似于bisheng，读取markdown的meta信息，然后把原有markdon的内容覆盖。缺点是改完代码后需要手动运行脚本生成文档。

**Comment by DiamondYuan** [comment]
有一些细节需要讨论一下。

1. @ 后面的字符应该是什么格式。我的想法是 `/[a-zA-Z]+/`
虽然纯小写也可以满足需求，但是 element 文档里面用到了 acceptedValues

2. 最低版本应该是叫什么。 我觉得 since 不错。
http://usejsdoc.org/tags-since.html jsdoc 也是这样的。

3. 在文档上是否要显示 optional，即这个字段是否是必填。

4 since 的中文翻译叫什么好。

**Comment by ztplz** [comment]
先把接口搞好啊  暴露的接口都放一个文件夹里 然后再弄jsdoc

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/53423599-9da76780-3a1c-11e9-8dfc-9d4a9f6be2b2.png)
比如zhe'ge这个button 里面建一个type或者interface文件用来放类型
