### ISSUE TITLE
Input loses focus

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#14945]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/13rwy809zj)

### Steps to reproduce
When you type a letter in the input box, you automatically lose focus.

### What is expected?
Don't lose focus

### What is actually happening?
 lose focus

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/507615/53064187-e6818c80-3501-11e9-9d9e-562c3c3bd71f.png">

**Comment by gonenoob** [comment]
sorry, try again

**Comment by afc163** [comment]
see https://github.com/ant-design/ant-design/pull/14948/files#diff-26cb6da96d10397e18e7dbd6c5d8f7a1R96

**Comment by gonenoob** [comment]
ths..

**Comment by afc163** [comment]
#14033

https://github.com/ant-design/ant-design/issues/14657#issuecomment-459765778
