### ISSUE TITLE
Dropdown 下拉菜单，菜单选项上添加Popconfirm，点击Popconfirm上的取消操作，Dropdown下拉框不自动隐藏

### ISSUE THREAD

**Issue by yyj66** [ant-design/ant-design#14947]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/917vjyomwp)

### Steps to reproduce
1. 点击‘更多操作’，显示下拉框选项
2. 点击‘作废’选项，弹出Popconfirm确认框
3. 点击Popconfirm的‘取消’按钮，Dropdown下拉框不自动隐藏

### What is expected?
点击Popconfirm的‘取消’按钮，Dropdown下拉框自动隐藏

### What is actually happening?
点击Popconfirm的‘取消’按钮，Dropdown下拉框没有自动隐藏，需要手动控制Dropdown组件的visible

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.8.2 |
| System | win10  |
| Browser | Google Chrome 72.0.3626.96 |

---
- 测试发现，是rc-dropdown 依赖的rc-trigger库的版本引起的问题。
- rc-dropdown 依赖 rc-trigger 的2.5.4以及之前的版本，  
  点击Popconfirm的‘取消’按钮，Dropdown下拉框会自动隐藏  
- rc-dropdown 依赖rc-trigger 的2.6.0及以上的版本，  
  点击Popconfirm的‘取消’按钮，Dropdown下拉框`不会`自动隐藏，需要手动控制Dropdown组件的visible

**Comment by zombieJ** [comment]
这是预期行为，`trigger` 为 `click` 时展示、隐藏都需要通过点击来执行。以前点击 Popconfirm 会影响上层的 Trigger 其实是一个 BUG……

**Comment by yyj66** [comment]
以下示例中：
https://codesandbox.io/s/34n8prn52p

1. 点击‘测试’选项，弹出Modal
2. 点击modal 上的任意位置，Dropdown 的下拉框隐藏

为什么这两种情况，Dropdown 下拉框的行为不一致

**Comment by zombieJ** [comment]
rc-trigger 只管内部子元素点击。Modal.info 并不是子元素，而是 antd 内部帮忙创建了一个新的元素在外面。

**Comment by fayhy** [comment]
当没有使用 getPopupContainer 的时候，Popconfirm DOM上渲染出来也不是下拉菜单的子元素   
FAQ里准针对这个问题，不认为是bug，并给出了解决方案    
现在的调整，改变了原有的行为模式，是否合适？

[FAQ：当我点击 Select Dropdown DatePicker TimePicker Popover Popconfirm 内的另一个 popup 组件时它会消失，如何解决？](https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E7%82%B9%E5%87%BB-Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E5%86%85%E7%9A%84%E5%8F%A6%E4%B8%80%E4%B8%AA-popup-%E7%BB%84%E4%BB%B6%E6%97%B6%E5%AE%83%E4%BC%9A%E6%B6%88%E5%A4%B1%EF%BC%8C%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F)

**Comment by zombieJ** [comment]
嗯，这个 FAQ 应该去掉了。
ref: https://github.com/react-component/trigger/pull/98
