### ISSUE TITLE
Collapse 折叠面板在Safari下动画异常

### ISSUE THREAD

**Issue by jasonal** [ant-design/ant-design#1494]
**问题描述**

Collapse 折叠面板在Safari下动画异常

**发生环境**

- antd 版本：最新版本，官网组件演示界面
- 操作系统及版本：osx10.11.4
- 浏览器及版本：safari 9.1
- 在线演示地址：
官网

**重现步骤**

直接点击

**线上重现演示**

无

**Comment by afc163** [comment]
一开始没有使用 rc-collapse 的样式的原因是在 firefox 下有问题。（这个问题现在在 https://github.com/react-component/collapse/pull/33 里修复）

**Comment by afc163** [comment]
楼主可先样式覆盖下。
