### ISSUE TITLE
Input.Search组件的addonBefore和addonAfter样式有问题

### ISSUE THREAD

**Issue by liuyanjie** [ant-design/ant-design#14959]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/liuyanjie/pen/gqEVQg](https://codepen.io/liuyanjie/pen/gqEVQg)

### Steps to reproduce
样式问题，无需步骤

### What is expected?
样式正常

![image](https://user-images.githubusercontent.com/5998826/53084458-d8506200-353b-11e9-80f7-e8bf0d56b2d6.png)

### What is actually happening?
样式不正常

![image](https://user-images.githubusercontent.com/5998826/53084415-c1aa0b00-353b-11e9-8d87-e086ff786f90.png)
![image](https://user-images.githubusercontent.com/5998826/53084502-ef8f4f80-353b-11e9-956b-4c3128687b7d.png)

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.8.2 |
| System | MacOS |
| Browser | Google Chrome Version 72.0.3626.109 (Official Build) (64-bit) |

**Comment by liuyanjie** [comment]
![image](https://user-images.githubusercontent.com/5998826/53141892-d682af00-35cc-11e9-890a-f211072a0540.png)

补充：Safari 12.0.3 浏览器样式同样有问题

**Comment by codelegant** [comment]
@afc163 当有 enterButton 属性时，addonBefore 的样式仍然不正确。

**Comment by hikari1024** [comment]
最新版本（4.8.4）中仍然存在此问题。
https://codesandbox.io/s/hopeful-mountain-wjz7r
