### ISSUE TITLE
Tree Component: the node spacing is getting bigger if the node has a number of child 

### ISSUE THREAD

**Issue by agoni1212** [ant-design/ant-design#14958]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/agoni1212/pen/rPbBMX](https://codepen.io/agoni1212/pen/rPbBMX)

### Steps to reproduce
link to https://codepen.io/agoni1212/pen/rPbBMX

### What is expected?
normal spacing between tree node

### What is actually happening?
growing spacing

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16 |
| System | windows  |
| Browser | chrome |

**Comment by Yangzhedi** [comment]
![image](https://user-images.githubusercontent.com/11626454/53096512-4b68d100-355a-11e9-8dca-225b1786335b.png)
set the `padding-bottom` to 0?
@afc163

**Comment by Yangzhedi** [comment]
![image](https://user-images.githubusercontent.com/11626454/53096683-ab5f7780-355a-11e9-80d4-619cf9e6f079.png)

![image](https://user-images.githubusercontent.com/11626454/53096902-2a54b000-355b-11e9-96f5-6cbf1091c3ed.png)

like this
