### ISSUE TITLE
TreeSelect 下拉框闪现

### ISSUE THREAD

**Issue by jinxin0112** [ant-design/ant-design#14951]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
1.点击TreeSelect弹出下拉框

2.在下拉搜索框中输入'sss'进行过滤搜索

3.点击过滤后的树结构选项进行选中

4.会闪现过滤之前的完整树结构然后再关闭下拉框

### What is expected?
在选中选项后，下拉框直接关闭，而非先闪现完整树结构再关闭

### What is actually happening?
在选中选项后会闪现一个完整的（过滤之前的）树结构下拉框，然后再关闭

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | 16.7 |
| System | os |
| Browser | chrome 71.0.3578.98 |

---
导致原因可能是在tree-select 中，清空下拉框的searchValue与关闭下拉框的两个动作是同步执行。

https://github.com/react-component/tree-select/blob/master/src/Select.jsx#L647

**Comment by afc163** [comment]
Your codepen is empty.

**Comment by jinxin0112** [comment]
@afc163  https://codepen.io/jinxin0112/pen/GzeeKY?&editable=true&editors=001
