### ISSUE TITLE
TreeSelect 在设置treeExpandedKeys后搜索中不会展开搜索结果

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#14956]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mpnjypp8p)

### Steps to reproduce
搜索子科目时不能自动展开，但不设置treeExpandedKeys时可以

### What is expected?
设置treeExpandedKeys时，搜索时仍可展开搜索结果的子科目

### What is actually happening?
搜索时，未设置的展开项不会自动展开

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 15.6.1 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
TreeSelect 的 treeExpandedKeys 受控时，filter 状态下的 expandedKeys 也是一并受控的：https://codesandbox.io/s/m44om3z1qj
