### ISSUE TITLE
input标签同时绑定 defaultValue和onChange事件，报错 'defaultPrevented' of undefined 

### ISSUE THREAD

**Issue by zhechang520** [ant-design/ant-design#1495]
比方我需要实现一条数据的编辑功能,最好的实现方式是怎样?

类似
`<Input ref="xxx" placeholder="xxx" initialValue={this.state.xxx} onChange={this.onChangexxx} />`

同时，如果绑定了value和onChange,则出现不能编辑的问题~~
没有绑定 `{...getFieldProps('xxx')}` ~

**Comment by benjycui** [comment]
`initialValue` 是 `getFieldProps` `option` 的值，组件应该直接用 `defaultValue`，另外再认真看下 Form 的文档如何？http://ant.design/components/form/

**Comment by zhechang520** [comment]
@benjycui   不好意思, 大意了, 在不抽离form为组件的前提下，原本的目的是想直接通过绑定一个state来实现绑定修改, 我直接绑定value,并在onChange事件中通过event.target直接取到该值后可以解决。。。
最好的做法i应该是要将表单封装~~
