### ISSUE TITLE
AutoComplete option key 无效

### ISSUE THREAD

**Issue by Veveue** [ant-design/ant-design#14969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/826o76wjr8)

### What is actually happening?
 

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.8.2 |
| System | linux |
| Browser | google |

**Comment by ycjcl868** [comment]
remove the `value` of `Option`.

![image](https://user-images.githubusercontent.com/13595509/53137829-307c7800-35bf-11e9-86c2-969310338ca0.png)

**Comment by zombieJ** [comment]
If `value` provided, `key` will set as `value`.
