### ISSUE TITLE
Long Anchor component into a Layout.Content, when the menu collapsed, the Anchor cannot move with the content.

### ISSUE THREAD

**Issue by shimingzhao** [ant-design/ant-design#14965]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v311oxwv6y)

### Steps to reproduce
Roll down the page, let the header out of the viewport.

### What is expected?
When the sider menu collapsed or extended, the anchor should move its position with the content layout.

### What is actually happening?
The anchor which inside the content, has the fixed position.

| Environment | Info |
|---|---|
| antd | 3.8.2 |
| React | 16.2.0 |
| System | Windows 10 64bit |
| Browser | Chrome Version 72.0.3626.109 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
手工触发一下 resize 强制 Anchor 刷新：https://codesandbox.io/s/p9m9nzym07
