### ISSUE TITLE
Select Option dropdown doesn't scroll in sync with table scroll

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#14963]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3xw09kw34m)

### Steps to reproduce
Please open the minimal production link.
https://codesandbox.io/s/3xw09kw34m

Click on any of the Select option of the age column.
While the dropdown is open scroll the table.
The select dropdown doesn't scroll with the table scroll.

### What is expected?
The option drop-down should close immediately or scroll in sync with the table scroll (after adding the scroll attributes to the Table)

### What is actually happening?
As of now the select dropdown is not scrolling in sync with the table scroll

| Environment | Info |
|---|---|
| antd | 3.10.0 |
| React | 16.5.2 |
| System | OSX |
| Browser | Google Chrome |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-scroll-with-the-page?
