### ISSUE TITLE
Slider with dual thumb mode (range) crash when press arrow keys (left, right, up, down).

### ISSUE THREAD

**Issue by luunc** [ant-design/ant-design#14962]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider/](https://ant.design/components/slider/)

### Steps to reproduce
Click to one end of dual mode slider, then press any arrow key

### What is expected?
The slider node will increase or decrease corresponding to arrow key pressed.

### What is actually happening?
Error occurs with these info:
TypeError: Cannot read property 'focus' of undefined
in ComponentEnhancer(Range) in t in div in u in t in section in section in t in div in t in div in t in article in DocumentTitle in SideEffect(DocumentTitle) in t in section in div in t in div in t in div in t in div in t in IntlProvider in t in RouterContext in Router.

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.8 |
| System | Latest Ubuntu |
| Browser | Latest Chrome |

**Comment by vydimitrov** [comment]
Came across the same bug.
https://codesandbox.io/s/znky6v3jrl

The first slider (the one on the top )with a number for defaultValue works when pressing any arrow key.
The second slider with range for defaultValue breaks the moment you press any of arrow key.

**Comment by ztplz** [comment]
Thanks for your report. I'll look into your demo.
