### ISSUE TITLE
走马灯提供卡片式交互方式

### ISSUE THREAD

**Issue by GFwer** [ant-design/ant-design#14961]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当前的走马灯只能一次显示一个面板，能否提供类似[Element](http://element-cn.eleme.io/#/zh-CN/component/carousel#qia-pian-hua)的卡片化模式？这样不仅能看出前后面板的一部分内容，感官上也会比当前模式令人感觉更有活力一点

### What does the proposed API look like?
添加一个`showType`的属性，默认是当前的模式，为`card`的时候展示卡片化的模式。

**Comment by afc163** [comment]
https://react-slick.neostack.com/docs/example/center-mode
