### ISSUE TITLE
Table组件设定了列宽度后显示错位

### ISSUE THREAD

**Issue by travonf** [ant-design/ant-design#14967]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/travonf/pen/omOqRa](https://codepen.io/travonf/pen/omOqRa)

下图表格第一列宽度应该是100px,但是很明显过长撑开了
![image](https://user-images.githubusercontent.com/18564432/53120101-08275600-358c-11e9-8adc-4297e9bf67f1.png)

### Steps to reproduce
设定Table组件属性scroll={{ x: 1200 }}，前两列设定width:100并固定

### What is expected?
列固定宽度，超出自动换行

### What is actually happening?
连续英文 数字 部分字符不会换行

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.6 |
| System | Windows 10 |
| Browser | Chrome 71.0.3578.98 |

---
按照官网提供的固定列案例实现之后，
开发环境正常，
build之后在生产环境显示错位，
发现是数据影响的，
最终查出是连续英文 数字 部分字符的情况造成的，
设定word-break:break-all时正常，这算不算bug?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by vaynevayne** [comment]
相同的问题
<img width="1246" alt="image" src="https://github.com/ant-design/ant-design/assets/124666577/c5806eba-a3fb-4076-8344-0fd90d32d2d1">
