### ISSUE TITLE
Popover: Position is incorrect when content size has changed

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#14977]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/popover-cn/](https://ant.design/components/popover-cn/)

### Steps to reproduce
https://codepen.io/AshoneA/pen/yZWyGK

### What is expected?
It should still has correct postion when content size has changed

### What is actually happening?
Is it possible to get correct position?

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16 |
| System | MacOS |
| Browser | Chrome |

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design/issues/14582

**Comment by zombieJ** [comment]
Popup don't listen content size since perf consider. You can force realign if needed: https://codesandbox.io/s/9q16jwl194

**Comment by ztplz** [comment]
那个bug不修了吗 dom-align在四个方向匹配不成功后会重置points 但是接下来 它又会尝试把元素移动到可视区域  但是箭头是根据points来算的

**Comment by zombieJ** [comment]
> 那个bug不修了吗 dom-align在四个方向匹配不成功后会重置points 但是接下来 它又会尝试把元素移动到可视区域 但是箭头是根据points来算的 我那个pr是根据两个元素的中心点来算的 只算四个方向

那个继续修的哈，我想要一个 example 来手工测一下。这个 issue 的问题和它不一样，因为它缺少检查时机。以前考虑过监听 size，感觉这些场景都是可以用户自己重定位的。
