### ISSUE TITLE
如何在transfer组件中使用tree组件呢

### ISSUE THREAD

**Issue by qwer5454554** [ant-design/ant-design#14974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/transfer-cn/#header](https://ant.design/components/transfer-cn/#header)

### Steps to reproduce
添加tree组件

### What is expected?
如何在transfer组件中使用tree组件呢

### What is actually happening?
不知如何添加

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.4.2 |
| System | windows |
| Browser | 谷歌最新 |

**Comment by afc163** [comment]
目前还不支持，你可以关注：#14932
