### ISSUE TITLE
如何在Select的onChange方法中拿到event?

### ISSUE THREAD

**Issue by astwyg** [ant-design/ant-design#1497]
各位, Select的onChange回调方法仅携带参数value和label, 除了直接修改rc-select源代码, 有没有其他方法获取event对象?

另外, 现在Input回调携带event, Select直接携带了value, 这样做是出于什么特殊的考虑么?

**Comment by afc163** [comment]
Input 是对原生 input 进行了简单封装，没有改变其行为。

Select 和原生 select 相比，是一个全新的组件，也就没有 event 事件。

**Comment by YouYII** [comment]
@astwyg 我想你可以使用bind 方法来传递参数,我这么做是可以的.
代码如下
```
handleChange(external_params,value){
    console.log(external_params,value);
}
render(){
let external_params=1;
return (<Select onChange={this.handleChange.bind(this, external_params)} value={answer_status}>
      {
          answerStatus.map((name,index)=>(
            <Option key={index} value={index}>{name}</Option>
          ))
        }
      </Select>);
}
```

**Comment by astwyg** [comment]
@YouYII 

其实我的意思是, 得到这个event, 比如获取我的动作是单击还是双击, 鼠标移入之类的**event**, 并不是需要绑定额外参数, :P

**Comment by asoqa** [comment]
@YouYII cool，对我有帮助！
