### ISSUE TITLE
RadioGroup 使用options后 onchange事件触发两次

### ISSUE THREAD

**Issue by headgreen** [ant-design/ant-design#14976]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/radio-cn/](https://ant.design/components/radio-cn/)

### Steps to reproduce
https://codepen.io/headgreen/pen/ZwNbjp?editors=0010

### What is expected?
onchange 事件只触发一次

### What is actually happening?
onchange 事件触发了2次

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16 |
| System | win10 |
| Browser | Chrome 70 |

**Comment by Yangzhedi** [comment]
[14984](https://github.com/ant-design/ant-design/pull/14984)
