### ISSUE TITLE
Collapse.Panel的header属性提供函数render

### ISSUE THREAD

**Issue by FEliuyg** [ant-design/ant-design#14980]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
据panel的状态做除了前面icon之外的其他事，比如header展开的时候右边显示extra icon，收起的时候隐藏extra icon。现在并没有途径可以在自定义渲染header中拿到isActive的状态值。

### What does the proposed API look like?
header: String | (props) => ReactNode

**Comment by afc163** [comment]
可以做成受控组件把状态拿到上层。
