### ISSUE TITLE
Transfer: `transferOnSelect` prop

### ISSUE THREAD

**Issue by billfienberg** [ant-design/ant-design#14988]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
>As a user that is trying to maintain a one-piece flow, I would like to pass a prop that causes a selected item to transfer to the other side as soon as the checkbox is selected so that I don't *have* to click the `direction` button, and can move items from side to side in the least number of clicks.

>As a keyboard user with is dealing with hundreds of results, I would like to transfer an item to the other side without having to tab through every other item in the list to get to the direction button, so that I can move items from side to side in the least number of clicks.

### What does the proposed API look like?
A `transferOnSelect` prop

```
      <Transfer
        transferOnSelect={true}
        dataSource={this.state.mockData}
        listStyle={{ width: 300, height: 300 }}
        targetKeys={this.state.targetKeys}
        onChange={this.handleChange}
        render={this.renderItem}
      />
```

**Comment by afc163** [comment]
It would be like prefixing `+` button in every item of left panel and `-` button in right.

**Comment by billfienberg** [comment]
> It would be like prefixing `+` button in every item of left panel and `-` button in right.

I think that would work, but I think that would mean it would still take 2 keypresses per selection for somebody tabbing through the list. Ideally, if I was tabbing through the list of items, it would only take one keypress per selection.

**Comment by ztplz** [comment]
How about using the arrow keys? `Right` means transfer to right and `Left` means transfer to left.

**Comment by billfienberg** [comment]
> How about using the arrow keys? `Right` means transfer to right and `Left` means transfer to left.

I like that idea. I think that would satisfy the one keypress per selection preference.

**Comment by zombieJ** [comment]
Since Transfer has 2 List. User always need to have the ability to choice the list they choice. Maybe Tab into left list, and another Tab to right list. And up & down to select current one and enter to move.
This may little different with mouse operation since user should alway have state to view and we should not save the key operation.

**Comment by zombieJ** [comment]
Transfer now support customize List. Close. #16026
