### ISSUE TITLE
[app] Delete merged branch

### ISSUE THREAD

**Issue by zy410419243** [ant-design/ant-design#14987]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When a pull request is merged, user must delete branch manually, and user sometimes forgets doing this. ~~like me~~

Check [here](https://github.com/apps/delete-merged-branch/).

Maybe this app would be helpful.

### What does the proposed API look like?
No need for code changing.

**Comment by yesmeck** [comment]
Added.

**Comment by zy410419243** [comment]
https://github.com/ant-design/ant-design/pull/14437

Seems not work...

**Comment by afc163** [comment]
It only works to branchs of original repository.
