### ISSUE TITLE
Transfer: `deletable` prop

### ISSUE THREAD

**Issue by billfienberg** [ant-design/ant-design#14989]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
>As a user that is reviewing a large data set (hundreds of items), I would like to pass a prop that allows items to be locally deleted from the list so that I have less noise in the items that I am reviewing.

### What does the proposed API look like?
A `deletable` prop
```
      <Transfer
        deletable={true}
        dataSource={this.state.mockData}
        listStyle={{ width: 300, height: 300 }}
        targetKeys={this.state.targetKeys}
        onChange={this.handleChange}
        render={this.renderItem}
      />
```

**Comment by afc163** [comment]
IMO it is not a suitable ability for a Transfer which is basicly a multiple select.
