### ISSUE TITLE
this hasn't been initialised - super() hasn't been called while i have write "super(props)"

### ISSUE THREAD

**Issue by HaoAlone** [ant-design/ant-design#14992]
![image](https://user-images.githubusercontent.com/30115419/53213885-874c8500-3685-11e9-8a8c-996aacd0ec5a.png)

 <Form onSubmit={this.handleSubmit} > 
                    <section className="my-reimburse title">
                        <div className="left">
                            <span className="logo">浮动工资设置</span>
                        </div>
                        <div className="btns">
                            <Button type="dashed" icon="check-circle"  htmlType="submit" >提交</Button>
                            <Button type="dashed" icon="rollback" onClick={this.reback}>返回</Button>
                        </div>
                    </section>

                    <div className="topTable table-header">
                        <span className="payApprove_title">
                            <i className="icon-square" />
                            <span className="diffMid">浮动工资<Icon type="plus-square" onClick={this.handleAddFloatSalary}/></span>
                        </span>
                        <Table  bordered pagination={false}  columns={this.floatSalaryColumns} dataSource={this.state.floatSalaryList} />
                    </div>
                    <div className="topTable table-header">
                        <span className="payApprove_title">
                            <i className="icon-square" />
                            <span className="diffMid">其他扣款项<Icon type="plus-square" onClick={this.handleAddFloatOtherSalary}/></span>
                        </span>
                        <Table bordered pagination={false}  columns={this.otherSalaryCutColumns} dataSource={this.state.floatOtherSalaryList} />
                    </div>
            </Form>

**_### I can run well locally ， but after  i  run command "npm run build ", when i run the build file , click the submit button , the error appeared;_**

"dependencies": {
    "antd": "^3.10.8",
    "axios": "^0.18.0",
    "babel-plugin-import": "^1.11.0",
    "gsap": "^2.0.2",
    "react": "^16.6.3",
    "react-app-rewired": "^1.6.2",
    "react-dom": "^16.6.3",
    "react-router-dom": "^4.3.1",
    "react-scripts": "2.1.1",
    "wangeditor": "^3.1.1"
  },
ndoe : v10.15.0
npm: 6.7.0

**Comment by Toototototo** [comment]
可能是babel版本不对。  我也遇到这个问题是因为使用了注解的写法，@Form.create().
将上面这个写法改为Form.create()(<Component />) 就解决了
