### ISSUE TITLE
希望能把QCON的PPT放在文献素材里面

### ISSUE THREAD

**Issue by doublelduob** [ant-design/ant-design#1499]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

听了QCON里面ant-design的分享

## What you would like to happen

希望能把QCON的PPT放在文献素材里面

## What actually happened

PPT是ant-design很好的介绍，除了ant-design本身，还介绍的很多团队文化。目前QCON可下载的PPT里没有ant-design的，可能漏掉了

## Online demo

(e.g. http://codepen.io/anon/pen/dMdjeo?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
http://2016.qconbeijing.com/schedule 这里有的。

**Comment by doublelduob** [comment]
多谢，抱歉占用你时间了哈
