### ISSUE TITLE
固定高度后表格head与body错位

### ISSUE THREAD

**Issue by a854363956** [ant-design/ant-design#14995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q34pzw2k09)

### Steps to reproduce
1. 设置表格属性  scroll={{ y: 440 }} 
2. 设置列的属性为数字类型的宽度
3. 填充超过宽度的数据

### What is expected?
表格组件的宽度不能与头部错位

### What is actually happening?
表格组件的宽度与头部组件错位了

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | latest |
| System | Window 10 |
| Browser | Google Chrome  72.0.3626.109（正式版本） （64 位） |

---

### 补充说明

不知道为什么,在表格计算body的时候似乎和计算head的宽度不一致,如果解决的了这个问题,是否就可以解决滚动条的问题? 
解决滚动条的思路

https://github.com/react-component/table/pull/285

**Comment by a854363956** [comment]
阅读相关 #13825  的问题的解决方案似乎也无法解决在这个问题

**Comment by afc163** [comment]
列宽度超过浏览器窗口宽度了导致浏览器自动排版异常，建议设小或者设置成百分比。

https://codesandbox.io/s/xl7o89nz8w
https://codesandbox.io/s/509m54zkpn
