### ISSUE TITLE
Add buttons location config in ConfigProvider

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design#14997]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In antd, the default confirmation button is on the right and the cancel button is on the left for example in Modal and Popconfirm components, but in some projects, the design specification requires the confirm button on the left and the cancel button on the right, so I thought we could add a configuration item to set it.
![qq 20190222113842](https://user-images.githubusercontent.com/16114101/53218084-b965e300-3695-11e9-8854-d6ffae4854f2.png)

### What does the proposed API look like?
Add a 'confirmButtonLoaction' api in ConfigProvider, it values are 'right(default)' or 'left'.

**Comment by yesmeck** [comment]
We should draw a line to indicate that what configs should be added to `ConfigProvider`.

I think the config you suggested should not be added to `ConfigProvider`. Instead, you should create your own Modal component based on the antd's.

**Comment by afc163** [comment]
@yesmeck may be right, we should not put everything what HOC can do in the ConfigProvider.

**Comment by kwzm** [comment]
@yesmeck @afc163 OK, I got it.
