### ISSUE TITLE
ant-table add a prop to dispaly rowselection in the last column.

### ISSUE THREAD

**Issue by rumsky** [ant-design/ant-design#14996]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Is it possible to add a configuration prop to decide whether the selected column is displayed on the left or right?
There are some situations  need to display the selection in the last column.

### What does the proposed API look like?
rowSelection add a prop like "rowselectionPosition:left|right"

**Comment by afc163** [comment]
I think you should create a column with Checkbox.
