### ISSUE TITLE
当使用Radio的Button样式时（Radio.Button）,onChange事件会触发两次

### ISSUE THREAD

**Issue by MilanLB** [ant-design/ant-design#15001]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/radio-cn/#header](https://ant.design/components/radio-cn/#header)

### Steps to reproduce
使用Radio.Group,包裹多个Radio.Button，  切换Radio.Button

### What is expected?
onChange事件会触发两次  

### What is actually happening?
onChange事件会触发一次

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | @16.8.3 |
| System | window10 |
| Browser | chrome |

---
已经阻止了，默认事件和冒泡

**Comment by afc163** [comment]
Fixed in #14984
