### ISSUE TITLE
Form中，getFieldProps设定Item验证规则后，设定了initialValue初始值，表单校验状态不准确

### ISSUE THREAD

**Issue by iambluebird** [ant-design/ant-design#1500]
props定义： 必填项、字符数不少于5个。
--------------------------------------------------------------------------------
    const nameProps = getFieldProps('name', {
      rules: [
        { required: true, min: 5, message: '用户名至少为 5 个字符' },
        { validator: this.userExists },
      ],
      initialValue: '3个字符'
    });
---------------------------------------------------------------------------------

FormItem定义：
---------------------------------------------------------------------------------
<FormItem
          {...formItemLayout}
          label="用户名："
          hasFeedback
          help={isFieldValidating('name') ? '校验中...' : (getFieldError('name') || []).join(', ')}>
          <Input {...nameProps} placeholder="实时校验，输入 JasonWood 看看" />
        </FormItem>
--------------------------------------------------------------------------------

如果不设置 initialValue 初始值，所有验证状态均正常

如果设置了initialValue初始值，如上所示，无论initialValue初始设置为何值（空字符串、null、或者是长度短于5个字符的），Feedback处都会出现sucess图标，当点击sumbit时才会实际验证并出现错误提示。初始时应该不给出这个状态来吧。

**Comment by benjycui** [comment]
这种不会修复，因为 `initialValue` 是程序提供的，调用方应该自行保证数据的合法性。
