### ISSUE TITLE
Missing radius-upright icon from doc?

### ISSUE THREAD

**Issue by pciapcib** [ant-design/ant-design#15002]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/icon/](https://ant.design/components/icon/)

### Steps to reproduce
There are radius-bottomleft, radius-bottomright and radius-upleft icons in Directional Icons category, but no radius-upright.

### What is expected?
Add the radius-upright icon to icon doc.

### What is actually happening?
The radius-upright icon is still missing from doc.

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | >=16.0.0 |
| System | macOS Mojave 10.14.2 |
| Browser | Chrome/72.0.3626.96 |

**Comment by afc163** [comment]
What is look like?

**Comment by pciapcib** [comment]
> What is look like?

https://github.com/ant-design/ant-design-icons/blob/master/packages/icons/svg/outline/radius-upright.svg
