### ISSUE TITLE
carousel bug

### ISSUE THREAD

**Issue by pengwenquan** [ant-design/ant-design#15005]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel-cn/](https://ant.design/components/carousel-cn/)

### Steps to reproduce
<Carousel >
      <div><h3>1</h3></div>
</Carousel>

If the carousel component has only one element, it will not display properly

### What is expected?
shuold display properly

### What is actually happening?
If the carousel component has only one element, it will not display properly

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by Yangzhedi** [comment]
@pengwenquan https://codesandbox.io/s/jlol1wxw4v it is OK
