### ISSUE TITLE
Render ReactNode inside Icon component

### ISSUE THREAD

**Issue by wildcookie007** [ant-design/ant-design#15019]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For example trying to build a display block for straight aligned inline items like Image and Icon together gets code heavy in terms of styling, unless you can wrap the Image element inside the antd's Icon component. If the image is not wrapped inside the Icon , the icon gets a separate fluid block. The background of this code at the moment would look like this:

```
<Layout>
    <img src='//path' />
    <Icon type='close' />
</Layout>
```

### What does the proposed API look like?
```
<Icon type='close'>
    <img src='//path' />
</Icon>
```

**Comment by zombieJ** [comment]
Icon component is designed for only Icon display usage. It should keep simple and not impact too much with element structure.
For your requirement, you can design to wrap with HOC for realization.
