### ISSUE TITLE
Request Help to Understand Antd Editable Cell

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#15017]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yp4yk8z95z)

### Steps to reproduce
Click on the Link.
Click on the Edit cell and try  to edit the cell.

1. Even though I have used a Select Component still on edit mode it is changing to Input Type.
2. Whatever data selected from Select Option doesn't reflect in edit mode.

### What is expected?
Whatever component used in the rows the same components should persist in the edit mode as well.

### What is actually happening?
It is not behaving as expected.  A short help is expected.

| Environment | Info |
|---|---|
| antd | 3.10.0 |
| React | 16.5.2 |
| System | OSX |
| Browser | Google Chrome |

---
May be if the documentation is expected with this scenario.. That will be Helpful.

**Comment by zombieJ** [comment]
Please ref official site demo: http://localhost:8001/components/table-cn/#components-table-demo-edit-row

You use `inputType` for checking but not set it.
