### ISSUE TITLE
Select组件在tags的模式下对相同的词不是精确判断

### ISSUE THREAD

**Issue by xpauline24** [ant-design/ant-design#15014]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lykl7q9kmz)

### Steps to reproduce
1. 输入 “测试的结果”
2. 再输入 “测试”
3. 再次输入 “测试”

### What is expected?
测试的结果，测试

### What is actually happening?
测试，测试

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.x |
| System | macOS |
| Browser | Chrome 72.0.3626.109 |

---
2.x 的官网上测试的结果是期望的结果，3.x 测试的时候就有问题。

**Comment by Yangzhedi** [comment]
https://github.com/react-component/select/blob/master/src/Select.tsx#L1078 
嗯嗯  应该使用indexOf判断的
