### ISSUE TITLE
设置不上 slider 不能向左滑，但是可以向右滑的情况  

### ISSUE THREAD

**Issue by yw8820** [ant-design/ant-design#15023]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider-cn/#header](https://ant.design/components/slider-cn/#header)

### Steps to reproduce
抽奖的赔率，当达到一定的数值之后，赔率不能再向左升高，即sldier 不能再向左滑动，可以向右滑减少赔率，现在设置不上 slider 不能向左滑，但是可以向右滑的情况  

### What is expected?
可以让开发设置不能向左滑，只能向右滑 的参数配置

### What is actually happening?
现在不能设置

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | react |
| System | 都存在 |
| Browser | 都有 |

---
抽奖的赔率，当达到一定的数值之后，赔率不能再向左升高，即sldier 不能再向左滑动，可以向右滑降低赔率，现在设置不上 slider 不能向左滑，但是可以向右滑的情况

**Comment by zombieJ** [comment]
动态更改最小值即可。
