### ISSUE TITLE
Select组件选项为空优化

### ISSUE THREAD

**Issue by xiamidaxia** [ant-design/ant-design#1502]
## 问题

Select组件如果没有选项，但是还是传了一个value进去，就会把value打印到到选择里，这样会有误导作用，下边是业务场景上的问题：

![image](https://os.alipayobjects.com/rmsportal/SKfobQBGKbYeMrp.png)

## 希望的优化点

希望直接显示空

## Online demo

http://codepen.io/xiamidaxia/pen/ZWMYJv?editors=001

## 环境

- 版本：v0.12.12
- OSX 10.11.13

**Comment by yiminghe** [comment]
受控组件，value 自己控制下
