### ISSUE TITLE
在使用Antd中的Upload组件是，如果将showUploadList设置为false,如何在上传过程中用户手动取消上传？

### ISSUE THREAD

**Issue by Gzbox** [ant-design/ant-design#15026]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在使用Antd中的Upload组件是，如果将showUploadList设置为false,在上传过程中用户可以手动取消上传

### What does the proposed API look like?
暴露出手动取消的props 或这其他方式，以便开发者使用

**Comment by Gzbox** [comment]
请大哥们指点， @sorrycc @afc163 @chenshuai2144

**Comment by zombieJ** [comment]
可以通过 `customRequest` 和 `fileList` 做成受控的列表来自己进行管理。

**Comment by Gzbox** [comment]
OK，我知道啦，谢谢
