### ISSUE TITLE
antd的组件API可以提供一份JSON格式的文件么？

### ISSUE THREAD

**Issue by xiyangjun** [ant-design/ant-design#15030]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前做antd的周边工具，需要知道antd的所有API。目前都是人肉copy。

### What does the proposed API look like?
能根据版本号给个JSON下载地址即可

**Comment by zombieJ** [comment]
Merge into #14940

**Comment by DiamondYuan** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 目前做antd的周边工具，需要知道antd的所有API。目前都是人肉copy。
> 
> ### What does the proposed API look like?
> 能根据版本号给个JSON下载地址即可

https://github.com/DiamondYuan/interface-comments-parser

老哥急用的化可以试试看这个。我把解析 interface 的抽了出来。

**Comment by xiyangjun** [comment]
> > * [ ]   I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> > 
> > ### What problem does this feature solve?
> > 目前做antd的周边工具，需要知道antd的所有API。目前都是人肉copy。
> > ### What does the proposed API look like?
> > 能根据版本号给个JSON下载地址即可
> 
> https://github.com/DiamondYuan/interface-comments-parser
> 
> 老哥急用的话可以试试看这个。我把解析 interface 的抽了出来。

感谢！！！

**Comment by xiyangjun** [comment]
@DiamondYuan 兄弟感谢！！！
