### ISSUE TITLE
DatePicker日期选择框 可以加一个设置方向的参数吗

### ISSUE THREAD

**Issue by wmy19930609** [ant-design/ant-design#15036]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
日期选择框出现遮挡

### What does the proposed API look like?
eg. widgetPositioning：{horizontal : 'auto' vertical: 'auto'}

**Comment by zombieJ** [comment]
现在所有的 Popup 已经是自动的了，它会尽可能的寻找页面可以放得下的位置放置。
如果有位置问题可以发个重现，issue 先关了~
