### ISSUE TITLE
`Input` Format Tooltip Input Demo Bug

### ISSUE THREAD

**Issue by ppbl** [ant-design/ant-design#15037]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input/#components-input-demo-tooltip](https://ant.design/components/input/#components-input-demo-tooltip)

### Steps to reproduce
1. input `-`  or `123.`
2. Mouse focus is removed

### What is expected?
'' or 123

### What is actually happening?
[object Object]

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.3 |
| System | windows10 |
| Browser | chrome72 |

---
### Seems to be this code：
```jsx
 // '.' at the end or only '-' in the input box.
  onBlur = () => {
    const { value, onBlur, onChange } = this.props;
    if (value.charAt(value.length - 1) === '.' || value === '-') {
      onChange({ value: value.slice(0, -1) });
    }
    if (onBlur) {
      onBlur();
    }
  }
```
```jsx
onChange({ value: value.slice(0, -1) }); probably is onChange(value.slice(0, -1)); 😄

中文文档是同样的问题🙏


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment]
Could you help to fix this demo?

**Comment by vitaliymaz** [comment]
@afc163  Can I fix that?

**Comment by afc163** [comment]
@vitaliymaz sure 😃

**Comment by ppbl** [comment]
I am very happy if I have a chance later.😄

**Comment by dj1109** [comment]
Hi
