### ISSUE TITLE
Cascader是否有类似Select中的getPopupContainer的参数可以配置？

### ISSUE THREAD

**Issue by cagen** [ant-design/ant-design#1503]
类似Select的定位问题，Cascader也同样存在：
http://codepen.io/anon/pen/JXaore?editors=001
  
  
请问能否有类似getPopupContainer的参数可以配置？  
或者组件本身还有其他的方法可以绕过这个问题？  
（在没法改动父级元素的overflow: scroll属性的前提下）

**Comment by afc163** [comment]
Reinstall antd.

**Comment by cagen** [comment]
@afc163 多谢修复！
忘了提了，DatePicker和扩展的RangePicker都有这个问题。。。

此外在使用getPopupContainer的时候，还碰到了一个问题，如果通过refs返回父级组件时，由于react本身的一个[问题](https://github.com/facebook/react/issues/1853)，可能导致Trigger.js中的componentWillUnmount代码取不到mountNode，导致错误，是否可以加入mountNode是否存在的判断或者捕获这个错误？
```js
  if (this.props.getPopupContainer) {
    var mountNode = this.props.getPopupContainer((0, _reactDom.findDOMNode)(this));
    mountNode.removeChild(popupContainer);
  }
```

**Comment by afc163** [comment]
这个应该已经修复了：https://github.com/react-component/trigger/blob/1.4.2/src/Trigger.jsx#L226-L231

可以试用 beta 版本，0.12 上应该不会再修复这个问题。

**Comment by cagen** [comment]
好的，谢谢！
不好意思，没注意看到DatePicker上有getCalendarContainer方法
