### ISSUE TITLE
Button component defaultProps and markdown api defaultProps are out of sync

### ISSUE THREAD

**Issue by skidrowe** [ant-design/ant-design#15044]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx](https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx)

### Steps to reproduce
* Look at markdown api default values - https://ant.design/components/button/#API.
* Look in code at defaultProps - https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx.

API lists four more defaultProp values than are in the code -  `disabled`, `htmlType`, `size` and `type`.

### What is expected?
Either the markdown file needs to be updated or the defaultProps values need to be updated

### What is actually happening?
Developer may think a default value is set but it is not.

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16 |
| System | Win 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Hi @skidrowe,

These props not set in defaultProps and added in document is aim to let user know what will behavior be when they not set.

For example, `size` is doc as `default` but not set in `defaultProps` and the code is like:
```jsx
switch (size) {
  case 'large':
    sizeCls = 'lg';
    break;
  case 'small':
    sizeCls = 'sm';
  default:
    break;
}
```

It's no need to set default since we only add related className with `lg` & `sm`.
