### ISSUE TITLE
Search Button with extra border at edge

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#15049]
<img width="205" alt="image" src="https://user-images.githubusercontent.com/507615/53386157-0d393a80-39bc-11e9-9a27-883429a0e576.png">

**Comment by afc163** [comment]
Here is another problem similar to https://github.com/ant-design/ant-design/issues/14959

https://codesandbox.io/s/qqvk7jzzk6

<img width="651" alt="image" src="https://user-images.githubusercontent.com/507615/53386604-debc5f00-39bd-11e9-9093-f740dec269b2.png">

**Comment by zombieJ** [comment]
现在的 border 是加在 addon 上的，为了展示 Button 去掉了 border & padding：
<img width="151" alt="2019-02-26 2 40 30" src="https://user-images.githubusercontent.com/5378891/53392500-893f7c80-39d4-11e9-8799-ecb4280aa43f.png">

先把 addonBefore 的 border 恢复，再考虑如果有用户 addonAfter 需求好了……
