### ISSUE TITLE
Input with suffix button does not align

### ISSUE THREAD

**Issue by vthinkxie** [ant-design/ant-design#15048]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v37qxyzkmy)

### Steps to reproduce
open codesandbox

### What is expected?
button align to right

### What is actually happening?
button not align to right

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | latest |
| System | mac |
| Browser | chrome latest |

**Comment by afc163** [comment]
It is by designed, maybe @code1986 are looking for `Search` component: https://codesandbox.io/s/oo8kplryz
