### ISSUE TITLE
添加依赖包版本锁定文件

### ISSUE THREAD

**Issue by CoolRice** [ant-design/ant-design#15045]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
请添加 package-lock.json 或者 yarn.lock 来锁定依赖包的版本

作用（来自 https://docs.npmjs.com/files/package-lock.json）：
1. Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
2. Provide a facility for users to “time-travel” to previous states of node_modules without having to commit the directory itself.
3. To facilitate greater visibility of tree changes through readable source control diffs.
4. And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

refs: [Should I commit yarn.lock and package-lock.json files?
](https://stackoverflow.com/questions/44552348/should-i-commit-yarn-lock-and-package-lock-json-files/44904494)

### What does the proposed API look like?
无

**Comment by zombieJ** [comment]
lock file can be generated by your project. You should manage it yourself if you need it.

**Comment by CoolRice** [comment]
@zombieJ ，你误解了我的意思，我说的是给 ant-design 这个项目加锁，就像react和vue给它的仓库加yarn.lock一样，我自己的项目当然由我来维护package-lock.json。

**Comment by zombieJ** [comment]
@CoolRice 组件库和框架有些不一样，我们的依赖的上层组件会有 patch 的 bug fix。所以我们遵循语义化版本管理。如果锁了版本，那每个 rc 组件有 bug fix 我们就都得重新发版本啦~

**Comment by guxingke201** [comment]
@afc163 @zombieJ  lock文件只会锁住文档系统的依赖版本号，不会锁住业务项目使用antd时的依赖版本号。所以文档系统增加增加lock文件并不会出现`如果锁了版本，那每个 rc 组件有 bug fix 我们就都得重新发版本啦~`

**Comment by guxingke201** [comment]
现在的情况是，下载antd历史tag版本，有时候文档系统代码检查会跑不过，有时候ts编译不通过

**Comment by zombieJ** [comment]
也有道理，目前 rc 依赖都是 ~version。感觉 @types 可能也需要这么设一下。

**Comment by guxingke201** [comment]
https://github.com/ant-design/ant-design 不仅仅是源码，还是一个文档系统，既然是系统，保留lock文件可以让系统稳定性更好。当然加了lock后，得定期更新lock，跑用例，业务系统第一次使用antd的时候有可能会自动更新依赖。我的建议是：至少提测的时候提交lock，打tag的时候保留lock

**Comment by afc163** [comment]
package-lock.json 不影响 `npm install antd` 吧？不影响就可以加，`npm run pub` 的时候自动更新。

**Comment by afc163** [comment]
不过有一点比较麻烦，就是本地用 cnpm 或 tnpm 的时候要注意安装的版本。

**Comment by DiamondYuan** [comment]
还有一个问题。yarn 用户怎么办

**Comment by zombieJ** [comment]
留档的话，我觉得有一个 lock 文件就够了。

**Comment by CoolRice** [comment]
赞同 @zombieJ ，保留一个就好

**Comment by CoolRice** [comment]
另外现在国内 npm 速度已经很不错了，感觉大部分人没必要继续用 cnpm。

**Comment by hk-ng** [comment]
> package-lock.json 不影响 `npm install antd` 吧？不影响就可以加，`npm run pub` 的时候自动更新。

please use npm ci to install version specified in package-lock.json

**Comment by afc163** [comment]
看上去必要性不高了。
