### ISSUE TITLE
Select with search field : The results of the search are inaccurate

### ISSUE THREAD

**Issue by Armyoftheworld** [ant-design/ant-design#15040]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mj701y71z8)

### Steps to reproduce
* Enter oppo in the input
* The options by searching include vivo and 三星

### What is expected?
Show only the options about oppo

### What is actually happening?
It's not just about showing oppo-related options

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.7.0 |
| System | Windows7 x64 |
| Browser | chrome 72.0.3626.81 x64 |

**Comment by afc163** [comment]
https://codesandbox.io/s/mj701y71z8

Select value should be always unique, like `key`.
