### ISSUE TITLE
日期选择器使用不够简便

### ISSUE THREAD

**Issue by xiaohongjin** [ant-design/ant-design#15053]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以单独选择，年月日录入，并带入年 ，月（年-月），日（年-月-日）

### What does the proposed API look like?
目前的很好

**Comment by zombieJ** [comment]
@xiaohongjin 感谢反馈，日期选择器样式是设计。按照你的需求可以通过 Select 来实现哈~
