### ISSUE TITLE
需求：form中extra属性请额外包一层容器，并加上classname

### ISSUE THREAD

**Issue by kasinooya** [ant-design/ant-design#1505]
### 现状

表单提示目前按规范应该是灰色，例如：

![img](https://os.alipayobjects.com/rmsportal/tSYMxGLHzytaEle.png)

目前要实现#999的灰色效果，每个都要写一层容器包含样式，很不方便：
```
extra={<span className="ft-gray">.....</span>}
```

### 结论

请为extra加上类似`ant-form-explain`一样的类名，方便全局样式修改

**Comment by benjycui** [comment]
刚发现已经有了 https://github.com/ant-design/ant-design/blob/develop-1.0.0/components/form/FormItem.jsx#L85 。。。

**Comment by benjycui** [comment]
之前 @yiminghe 加 `extra` 应该是为了处理 `Form.Item` 不支持多个 child 的情况，但现在已经支持多个 child https://github.com/ant-design/ant-design/commit/10dd78122b12591d7bda2b714b6990404324772c ，所以 `extra` 可以 deprecate 了？

**Comment by yiminghe** [comment]
ok

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/287c45292de6fc2bc244aaa9717d7f718232fc41

**Comment by afc163** [comment]
已默认置为灰色。
