### ISSUE TITLE
Drawer 组件只是简单了接受了handler 和onHandleClick ,而没有提前声明这两个属性，导致会在TS中报错

### ISSUE THREAD

**Issue by fanxiaokun** [ant-design/ant-design#15051]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/dashboard/analysis](https://preview.pro.ant.design/dashboard/analysis)

### Steps to reproduce
把settingDrawer.js改为settingDrawer.ts,Drawer组件会报handler onHandleClick属性不存在DrawerProps中

### What is expected?
handler onHandleClick属性存在DrawerProps中

### What is actually happening?
handler onHandleClick属性存在DrawerProps中

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.6.3 |
| System | MAC |
| Browser | chrome |

**Comment by afc163** [comment]
`onHandleClick` is a bad API that we should not use it, just removed in https://github.com/ant-design/ant-design-pro/pull/3602. And added the `handler` TypeScript definite at #15052.
