### ISSUE TITLE
Input component can not type in Chinese in React 16.7.0

### ISSUE THREAD

**Issue by Elson8080** [ant-design/ant-design#15054]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/evenToday/pen/eXYLPp](https://codepen.io/evenToday/pen/eXYLPp)

### Steps to reproduce
focus input，type in Chinese word will be canceled

### What is expected?
could type in Chinese

### What is actually happening?
could not

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.7.0 |
| System | mac os |
| Browser | chrome |

---
react@16.7.0 and antd@(any version) will show the problem

**Comment by ztplz** [comment]
It has been fixed by `React Team`. Please upgrade your `react`.

**Comment by Elson8080** [comment]
react@16.8.3 react-dom@16.8.3  fix it
thx
