### ISSUE TITLE
antd Table设置scroll.x，当没有数据时表头显示不全，且没有滚动条

### ISSUE THREAD

**Issue by githubyong** [ant-design/ant-design#15058]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kmlk8373vr)

### Steps to reproduce
打开链接，当state.data:[]时，表格的表头只能显示一部分，且没有水平方向的滚动条。

### What is expected?
表格数据为空时也能显示水平滚动条和全部表头

### What is actually happening?
表格数据为空时，表头显示不全

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.5.2 |
| System | windows7 |
| Browser | Chrome 71.0.3578.98 |

---
state.data:[{}]时能显示滚动条和全部表头

**Comment by zombieJ** [comment]
在没有数据的时候，表格头部还是跟着 scroll 属性做滚动的：
![kapture 2019-02-26 at 16 42 17](https://user-images.githubusercontent.com/5378891/53398812-84cf8f80-39e5-11e9-8df7-15ef7f0e7507.gif)

下面不一起滚是为了防止太宽用户看不到没有数据影响体验。

**Comment by qinyuhua** [comment]
没有滚动条，并且window系统鼠标不能拖动，体验太差了

**Comment by MSK0379** [comment]
![image](https://user-images.githubusercontent.com/22637327/67933343-8c90a500-fc00-11e9-860c-1da630072b2e.png)
设置了固定列，以及表头上的筛选。在没有数据的时候，没有滚动条。没办法使用了。
这个是BUG还是什么情况。

**Comment by kangzhaotong** [comment]
这个问题先看下你的style样式中看看有没有全局样式覆盖了antd-table的样式，一般出现这个问题就是吧antd-table原有的样式覆盖了，所以看下你的全剧样式，这可是一个谨慎操作。

**Comment by leiyangs** [comment]
真不理解为啥数据，表头也看不全

**Comment by mrdulin** [comment]
https://stackblitz.com/edit/react-gqv2dy?file=demo.tsx

列比较多时，有水平滚动条，但滚动后列展示不全
