### ISSUE TITLE
react-slick has memory leaks issue

### ISSUE THREAD

**Issue by 54huanan** [ant-design/ant-design#15062]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/akiran/react-slick/issues/1257](https://github.com/akiran/react-slick/issues/1257)

### Steps to reproduce
轮播一段时间就内存就会增加

### What is expected?
轮播组件使用了这个库，但是会有内存泄漏。能帮助解决吗？

### What is actually happening?
内存一直增加

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16 |
| System | windows10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
看起来是这行代码的问题：https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L308
<img width="649" alt="2019-02-26 5 32 09" src="https://user-images.githubusercontent.com/5378891/53402315-789b0080-39ec-11e9-95ec-85b03bb28725.png">

@afc163 `react-slick` 好几个月没更新了，要解决我们可能要自己搞一个了。

**Comment by jljsj33** [comment]
这货又冬眠了。。。。。哈哈。。。。

**Comment by ztplz** [comment]
有人已经提了pr了 fork过来改了

**Comment by Atlaswimming** [comment]
今天解决内存泄漏时，同样定位到 Carousel 组件，轮播图相关组件相关的 dom nodes 无法回收。
![image](https://user-images.githubusercontent.com/37287409/53568348-b8a0e580-3b9c-11e9-88dc-78019e2519ef.png)

**Comment by ycjcl868** [comment]
https://github.com/akiran/react-slick/pull/1397

**Comment by afc163** [comment]
We fork https://github.com/ant-design/react-slick in 4.0 now.

**Comment by Xavier0818** [comment]
> We fork https://github.com/ant-design/react-slick in 4.0 now.

It's still happening.

![image](https://user-images.githubusercontent.com/16759949/88881105-0a9ddd00-d261-11ea-8b43-abcae78f19d7.png)

the react-slick's version is 0.26.3, and ant-design's  version is 4.0.6.

**Comment by afc163** [comment]
@Xavier0818 PR welcome~

**Comment by yzz3730781** [comment]
i use react-slick@0.27.13,but it still happen memory leak.

**Comment by n0ruSh** [comment]
> 看起来是这行代码的问题：https://github.com/akiran/react-slick/blob/master/src/inner-slider.js#L308
> <img alt="2019-02-26 5 32 09" width="649" src="https://user-images.githubusercontent.com/5378891/53402315-789b0080-39ec-11e9-95ec-85b03bb28725.png">
> 
> @afc163 `react-slick` 好几个月没更新了，要解决我们可能要自己搞一个了。

@zombieJ  这个图是肿么复现出来的。我试着在官网的carousel组件demo里用chrome跑　 Memory -> Heap snapshot -> Take heap snapshot，但是好像没看出来内存泄漏了。。是我哪里姿势不对么。。

**Comment by linzhaoqiang** [comment]
如何解决这个问题？我当前依赖的版本是0.27.14，也出现了内存泄露的问题

**Comment by zombieJ** [comment]
Close since v3 is off maintain version.
