### ISSUE TITLE
onPanelChange method is not triggered

### ISSUE THREAD

**Issue by UlyC** [ant-design/ant-design#15061]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/qv2kvz0l6q?fontsize=14)

### Steps to reproduce
The date panel has changed when I click on a date in the calendar for the last month or the following month, but the onPanelChange method is not triggered, causing the page data to be unloaded,.

### What is expected?
When  date panel has changed when I click on a date in the calendar for the last month or the following month, onPanelChange method should be triggered.

### What is actually happening?
onPanelChange method is not triggered

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | react@16.8.3  |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
Nice catch

**Comment by aqnaruto** [comment]
still not work

**Comment by pingping2116** [comment]
not working yet

**Comment by polckatraceneje** [comment]
Still not (v 4.24.0)
