### ISSUE TITLE
responsive prop is not allowed on carousel with TypeScript

### ISSUE THREAD

**Issue by Tirlipinpin** [ant-design/ant-design#15065]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/my0pz79vvx)

### Steps to reproduce
Just use the provided sandbox, but with a react project working on typescript. The responsive prop isn't allowed

### What is expected?
The responsive prop to be allowed

### What is actually happening?
It is not allowed

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.7.0 |
| System | Windows |
| Browser | Chrome |

---
The sandbox isn't running on typescript because I don't know how to do it

**Comment by vitaliymaz** [comment]
It is just missed from the proptypes. Let me make a PR for that.
