### ISSUE TITLE
Ant Design React Footer stuck in content

### ISSUE THREAD

**Issue by fnoah** [ant-design/ant-design#15066]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j4ny399933)

### Steps to reproduce
Use the Ant Design layout from the minimal reproduction link (which adheres to the Ant Design documentation) and put enough content into the Content tag so the page will become scrollable.

### What is expected?
I am trying to create a layout using Ant Design where the footer should be at the bottom of the page and only visible when scrolling to the bottom of the page (not fixed).

### What is actually happening?
Now, this works perfectly fine as long as the main content can fit into the page without scrolling. As soon as there is enough content for scrolling, the footer will be stuck inside the content and is no longer on the bottom of the page (as soon as you start scrolling).

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.1 |
| System | Ubuntu 18.04 |
| Browser | Google Chrome 72.0.3626.119 |

**Comment by afc163** [comment]
https://codesandbox.io/s/j4ny399933

```diff
-       <Layout style={{ height: "100vh" }}>
+      <Layout>
```
