### ISSUE TITLE
Table header is rendered with Segoe UI Semibold on Chrome browser

### ISSUE THREAD

**Issue by Cadabrum** [ant-design/ant-design#15068]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/000vqw38rl)

### Steps to reproduce
Any Table component with default values has header rendered with Semibold font. 
![000vqw38rl - codesandbox - google chrome 2019-02-26 18 24 35](https://user-images.githubusercontent.com/8113127/53424450-4beae700-39f4-11e9-9e62-69ad826004b0.png)
![table - ant design - google chrome 2019-02-26 18 22 07](https://user-images.githubusercontent.com/8113127/53424502-61f8a780-39f4-11e9-8ab2-4d0966932a8b.png)

### What is expected?
Semibold UI Regular 

### What is actually happening?
Semibold UI Semibold

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.3 |
| System | Windows 10 |
| Browser | Chrome 72.0.3626.119 |

**Comment by afc163** [comment]
It is by designed, you can override it if you don't like default styles.

**Comment by Cadabrum** [comment]
But it is rendered Regular with Firefox and IE?

**Comment by Cadabrum** [comment]
![000vqw38rl - codesandbox - mozilla firefox 2019-02-26 18 34 42](https://user-images.githubusercontent.com/8113127/53424964-3c1fd280-39f5-11e9-84b5-7acd6ce23d76.png)

**Comment by afc163** [comment]
It may be a browser compatibility issue, we are using `font-weight: 500;` simplely.

**Comment by ztplz** [comment]
There is no difference on my mac. 
![image](https://user-images.githubusercontent.com/17755202/53426488-06dda980-3a22-11e9-9e17-558f16ec19fd.png)
