### ISSUE TITLE
Are there any components for headings and simple text?

### ISSUE THREAD

**Issue by SilencerWeb** [ant-design/ant-design#15069]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Well, it is always good to have such base components

**Comment by zombieJ** [comment]
Typography will release in next minor version: https://github.com/ant-design/ant-design/pull/14250

**Comment by SilencerWeb** [comment]
@zombieJ do you already know when it will be released?

**Comment by zombieJ** [comment]
We release minor version by each end of month.

**Comment by arolson101** [comment]
it's confusing because this unreleased feature is in the documentation: https://ant.design/components/typography/

**Comment by zombieJ** [comment]
> unreleased

Update your antd version: https://ant.design/changelog#3.14.0
