### ISSUE TITLE
Table 组件相关问题

### ISSUE THREAD

**Issue by yinzSE** [ant-design/ant-design#1507]
1. className 不会设置到 <table /> 元素上, 有点不方便
2. 内容过多没有很好的处理, 比如可以带 'table-layout fixed' 属性?
3. 点击 `rowSelection` 属性的 附带的 `checkbox ` 也会出发 `onRowClick`, 并且 `Function(record, index)` 也没有提供 `click event ` 给我进行判断. 

感觉table 抽象太高了, 不是特别好用

**Comment by afc163** [comment]
`table-layout fixed` 属性可以自行加上，作为通用组件，对表格布局还是不要太多约束较好。
