### ISSUE TITLE
tree 组件升级到最新版本后 异步请求，第一次展开之后，第二次展开就不做请求了

### ISSUE THREAD

**Issue by Gcherryzhang** [ant-design/ant-design#15074]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
1.每展开一个节点都会请求一次数据 2.反复展开发现只有第一次展开的时候请求了会有node请求参数，后面多次展开关闭就不会有

### What is expected?
希望和之前的版本一样，每次展开的时候都能有请求参数，做相应的请求

### What is actually happening?
在初始化加载的时候展开节点之后再对tree进行后台请求的搜索，得到的数据可能和初始化的数据是一样的，但是在前面展开过的节点，就无法获取当前node的参数进行异步请求

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.6.1 |
| System | win10 |
| Browser | Google Chrome最新版本 |

---
提供的antd官方的文档里面tree异步请求就可以重现这个问题

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/53462579-379ffc00-3a7f-11e9-86c8-f55dfc8bbffb.gif)

没发现有啥问题。

**Comment by Gcherryzhang** [comment]
> ![1](https://user-images.githubusercontent.com/507615/53462579-379ffc00-3a7f-11e9-86c8-f55dfc8bbffb.gif)
> 
> 没发现有啥问题。
你不要一直往下展开，展开用第一个节点再关闭再展开

**Comment by afc163** [comment]
数据已经加载过了，第二次点击肯定不需要再去后台加载了，这个逻辑目测是合理的吧。而且之前的版本也应该是这样的。

**Comment by Gcherryzhang** [comment]
模拟一个场景：我初始化加载的时候，把节点展开查看了，比如我根据时间段或者其它条件通过后端异步查询，重新渲染了数据，凡是我在搜索之前展开过的节点，现在都无法发起请求了。我看了下 loadData这个事件也无法获取到当前node参数

**Comment by afc163** [comment]
你最好给个 codesandbox 完整重现一下这个场景，给出详细的步骤，方便理解。

**Comment by afc163** [comment]
另外 TreeNode 上有一个 `isLeaf` 属性，用来标记这个节点是否可以被二次展开。如果你二次重新渲染数据，别忘了处理这个标记。https://ant.design/components/tree/#TreeNode-props

**Comment by zombieJ** [comment]
用 `loadedKeys` 做来控制你已经加载的节点就行了，如果想重新加载，onExpand 后把 key 从 `loadedKeys` 里删除就会重新加载了。

**Comment by afc163** [comment]
@zombieJ 👍 居然还有这么个属性

**Comment by Gcherryzhang** [comment]
@zombieJ  确实解决了，谢谢

**Comment by elmelloi** [comment]
非常有用，谢谢

**Comment by ChenXinGuang1003** [comment]
请问楼主，你这个怎么解决的，目前我也遇到这个问题，求解答，谢谢

**Comment by Gcherryzhang** [comment]
> 请问楼主，你这个怎么解决的，目前我也遇到这个问题，求解答，谢谢

用 loadedKeys 做来控制你已经加载的节点就行了，如果想重新加载，onExpand 后把 key 从 loadedKeys 里删除就会重新加载了。希望对你有用

**Comment by ps2qwert** [comment]
想问是通过什么时候去设置loadedKeys,onLoad的时候设置是在onExpand之前

**Comment by realEago** [comment]
😓

**Comment by 596121109** [comment]
> > 请问楼主，你这个怎么解决的，目前我也遇到这个问题，求解答，谢谢
> 
> 用 loadedKeys 做来控制你已经加载的节点就行了，如果想重新加载，onExpand 后把 key 从 loadedKeys 里删除就会重新加载了。希望对你有用
能贴一下代码吗

**Comment by zdJOJO** [comment]
> 用 `loadedKeys` 做来控制你已经加载的节点就行了，如果想重新加载，onExpand 后把 key 从 `loadedKeys` 里删除就会重新加载了。

牛的老哥。 找了好久， 终于找到解决方案乐
