### ISSUE TITLE
Table with fixed columns and horizontal scroll will lose the scroll bar on the fixed columns when sorting on IE11

### ISSUE THREAD

**Issue by martymcfly1985** [ant-design/ant-design#15072]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-grouping-columns](https://ant.design/components/table/#components-table-demo-grouping-columns)

### Steps to reproduce
Sort the Age column so that the sorting arrow is pointing down.

### What is expected?
The horizontal scrollbar will remain at the bottom of the entire table.

### What is actually happening?
The horizontal scrollbar only remain on the unfixed columns, thus overwriting the final row.

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.5.2 |
| System | Windows 8.1 Enterprise |
| Browser | 11.0.9600.19236CO |

**Comment by zombieJ** [comment]
Can't understand your meaning. Could you provide an gif for this?

**Comment by martymcfly1985** [comment]
The issue can be reproduced on your website through the link I provided. The issue is only visible if you are using Internet Explorer 11. Your example labeled "Grouping Table Head" is the example I am referring to.
![ant table error](https://user-images.githubusercontent.com/48028793/53497546-695e9600-3a72-11e9-8b4c-d076b8bd204f.gif)

**Comment by zombieJ** [comment]
Tested. It seems a IE 11 bug. render will ignore `max-height`. Since we can not assume the content height of Table. It may not fix in antd component. But you can set style to force keep the height correct:
```css
#somePrefix .ant-table-middle .ant-table-scroll {
  height: 240px; // Same as your scroll.y value
}
```

**Comment by martymcfly1985** [comment]
I dropped that into my style sheet, making sure to have the height match my scroll y value, but unfortunately, that didn't seem to change anything.

**Comment by zombieJ** [comment]
Hi, my code is example. You need to modify the selector to make it happen:
![kapture 2019-03-01 at 10 18 43](https://user-images.githubusercontent.com/5378891/53611996-72cf3600-3c0b-11e9-9ea6-0550a6c5051e.gif)
