### ISSUE TITLE
Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed 

### ISSUE THREAD

**Issue by reenan** [ant-design/ant-design#15073]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
Not applicable

### Steps to reproduce
Build a project with create-react-app and add antd (or any project with ant as a dependency)

### What is expected?
That the project still builds without warnings

### What is actually happening?
Because of a CSS property on antd it's throwing warnings regarding outdated spec.
<img width="655" alt="screen shot 2019-02-26 at 15 43 24" src="https://user-images.githubusercontent.com/13966837/53438225-366ac280-39de-11e9-9c9d-f6711d1e20e4.png">

| Environment | Info |
Not applicable

---
Seems like there is a property inside antd that is outdated and throws warnings on compilers.
The title is self-descriptive: Replace text-decoration-skip: ink to text-decoration-skip-ink: auto, because spec had been changed

**Comment by zombieJ** [comment]
Pls use latest version. This has already been fixed: https://github.com/ant-design/ant-design/commit/46a7a048dc16f4ccf71c3a197cdcf6fef2663f7e
