### ISSUE TITLE
Migrate demos into hooks

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#15084]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Usually developers always copy code from demo, while react encourages the usage of hooks. It could be a plan to migrate demos into hooks.

It can keep the demo simple and easy to use.

This may be a long-term task with label `plan` and `help wanted`.

### What does the proposed API look like?
Migrate demos into hooks

**Comment by zombieJ** [comment]
Since we still need to support react 15. We may not update demo about hooks to avoid confuse.
But for Form may add additional hooks demo after provided api.

**Comment by ztplz** [comment]
其实demo最大的作用不是用来展示组件的 是用来给别人抄代码的。。。  很多前端写项目 ctrl + v + qq群

**Comment by dancerphil** [comment]
> Since we still need to support react 15.

Ignored react 15 again😂. Will 15 be deprecated after react 17?

> 是用来给别人抄代码的。。。

是啊，为了提升他们的代码质量，才有这个建议的。

**Comment by afc163** [comment]
感觉早晚要上 hooks，顺便可以建议用户升级到 react@16。

**Comment by ztplz** [comment]
那rc-notifications可以用Portal重构了 https://github.com/ant-design/ant-design/issues/14101

**Comment by dancerphil** [comment]
给个 4.0 的计划呗，升级 react@16 肯定是要升大版本的，antd@3 继续支持 react@15，后续维护一段时间即可。

**Comment by zombieJ** [comment]
hooks 写起来方便，但是不一定能提升代码质量。class component 和 function component 都可以写出坨式代码。

（我本人其实还挺希望可以放下 15，毕竟用户升级成本其实不太大。）

**Comment by dvakatsiienko** [comment]
omg why you can't just write in english? it's oss ffs
