### ISSUE TITLE
It does not reflect when the progress bar reaches 99.9%

### ISSUE THREAD

**Issue by wqcstrong** [ant-design/ant-design#15099]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
```
npx create-react-app project-name
cd project-name
yarn add antd
```

### What is expected?
installed normally

### What is actually happening?
It does not reflect when the progress bar reaches 99.9%

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.3 |
| System | mac OS |
| Browser | Chrome 72.0.3626.119 |

---
1. 不是网络原因
2. 命令行代理模式/非代理模式下，安装都失败了
3. 发现问题后重启了电脑一次，依旧不成功

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/53494247-4070ec00-3ad8-11e9-807d-5062fc364590.png)
正常安装
你说的 99% 但是它一直在安装啊  而且这根本跟antd没任何关系

**Comment by zombieJ** [comment]
This is not antd issue. If you do believe it's not related with network. You can fire a issue to https://github.com/npm/npm
