### ISSUE TITLE
Form.Item 标题 label问题 出现( : )

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design#15094]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
             <Form.Item label={index === 0 ? '出访成员': <div style={{width: '71px'}}></div>}>
                {getFieldDecorator(`daasd8888[${k}]`)(
                  <Input />
                )}
              </Form.Item>

### What is expected?
去掉 : 

### What is actually happening?
动态增加的表单，需要去掉label

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 无 |
| System | windows |
| Browser | Google Chrome |

---
无
![1551262537 1](https://user-images.githubusercontent.com/23191825/53483422-6dafa100-3abc-11e9-9910-31c3c3cfb9b4.jpg)

**Comment by afc163** [comment]
There is a `colon` prop in Form.Item.
