### ISSUE TITLE
Stop using "P" tag for description in Empty component

### ISSUE THREAD

**Issue by slonoed** [ant-design/ant-design#15098]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://example.com](https://example.com)

### Steps to reproduce
Use custom description in Empty component

### What is expected?
Any content can be used as description

### What is actually happening?
Empty renders description in "P" tag. Which means we can't use for example "DIV" or "UL" inside.

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | any |
| System | any |
| Browser | any |

---
Link to component code https://github.com/ant-design/ant-design/blob/master/components/empty/index.tsx#L51

**Comment by zombieJ** [comment]
Use `children`: https://codesandbox.io/s/20m2vk16lj
