### ISSUE TITLE
When Radio checked, user can't cancel it

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#15109]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When Radio checked, user can't cancel it

### What does the proposed API look like?
isCanBeCancel

**Comment by yesmeck** [comment]
Use Checkbox if you want to cancel.

**Comment by Dolov** [comment]
My boss want Radio @_@

**Comment by Dolov** [comment]
> Use Checkbox if you want to cancel.
My boss want Radio @_@

**Comment by yesmeck** [comment]
I can't give you any other advice without context.

**Comment by Dolov** [comment]
> I can't give you any other advice without context.

thanks

**Comment by afc163** [comment]
Radio cannot cancel, native radio does not too.

**Comment by withzhaoyu** [comment]
> Radio cannot cancel, native radio does not too.

i think this situation is pretty normal, like when a radio form item which  not required checked by mistake, user must refresh this page!
