### ISSUE TITLE
Export destroyInactiveTabPane prop from rc-tabs

### ISSUE THREAD

**Issue by Lingxiao-Ma** [ant-design/ant-design#15102]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Give user the option to destroy Inactive TabPane.

In our case, when tabs switch event happens, we want to unmount inactive TabPane, when a TabPane is mounted, we update a context to update other portion of UI.
plus, we have hundreds of TabPane page with layer of Tabs and SubTabs, we don't really want to cache all pages.

### What does the proposed API look like?
add destroyInactiveTabPane to TabsProps

**Comment by zombieJ** [comment]
You can use `onChange` event to record active tab and destroy unnecessary one:
```jsx
function MyContext({ active }) {
  if (!active) return null;
  return (<h1>hello world</h1>);
}

<TabPane key="1">
  <MyContext active={activeKey === '1'}>...</MyContext>
</TabPane> 
```

**Comment by Lingxiao-Ma** [comment]
thanks - it works for sure, just curious why antd don't export destroyInactiveTabPane prop since rc-tabs support this anyway?

**Comment by zombieJ** [comment]
It's by product positioning design.

We hope rc component be much flexible so it may change api by new release (This may cause breaking change after user upgrade). But for antd, we should consider compatibility which means we need add api much carefully. So antd component api is not keep syncing with rc.

**Comment by tommyspot** [comment]
Currently, `destroyInactiveTabPane ` is already on Antd's Tabs

**Comment by girin-dev** [comment]
@tommyspot How can I check that? I can't see that on https://ant.design/components/tabs/

**Comment by alex-golubtsov** [comment]
> Currently, `destroyInactiveTabPane ` is already on Antd's Tabs.

Curious, why it's not documented https://ant.design/components/tabs/#API

**Comment by tommyspot** [comment]
> > Currently, `destroyInactiveTabPane ` is already on Antd's Tabs.
> 
> Curious, why it's not documented https://ant.design/components/tabs/#API

Hi @alex-golubtsov,

You missed a passage:  "More option at **rc-tabs** option"
https://github.com/react-component/tabs#tabs

**Comment by alex-golubtsov** [comment]
> Hi @alex-golubtsov,
> 
> You missed a passage: "More option at **rc-tabs** option"
> https://github.com/react-component/tabs#tabs

Right, haven't noticed that :)
