### ISSUE TITLE
UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design#1510]
在使用1.0.0-beta.3版本的时候，提示UNMET PEER DEPENDENCY react@^0.13.0 || ^0.14.0，但是依赖不应该是react-15.0.+的吗？

**Comment by afc163** [comment]
底层组件还未修改完毕。https://github.com/ant-design/ant-design/issues/1340

**Comment by WhatAKitty** [comment]
@afc163 好的，了解了
