### ISSUE TITLE
Modal无法二次调用静态方法

### ISSUE THREAD

**Issue by mebtte** [ant-design/ant-design#15106]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k52nrj8vyo?fontsize=14)

### Steps to reproduce
在Modal.confirm中的onOk调用Modal.alert，Modal.alert没有弹出显示

### What is expected?
Modal.alert正确弹出并显示

### What is actually happening?
Modal.alert没有正确弹出

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.3 |
| System | 所有系统 |
| Browser | 所有浏览器 |

**Comment by zombieJ** [comment]
Modal 没有 alert 这个方法………… https://codesandbox.io/s/l4ym551x0m
