### ISSUE TITLE
Dropdown 组件 在 手机版下面点击没反应（有时候只有第一次点了有反应）

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#15103]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w2nzwzyq0l)

### Steps to reproduce
我的手机环境：
iphonex
safari
chrome

复制 codesandbox 右侧的 https://w2nzwzyq0l.codesandbox.io/这个地址 ，发送到手机上面，我这里用的safari和chrome都测试了一下。点击一次更多有反应，再单击第二次就没反应了。

### What is expected?
多次点击更多应该有同样的效果

### What is actually happening?
最多只能点击一次更多才会出现下拉列表

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.6.3 |
| System | windows10 专业版 |
| Browser | chrome 71.0.3578.98  |

**Comment by imhele** [comment]
https://ant.design/components/dropdown/#components-dropdown-demo-trigger

**Comment by zombieJ** [comment]
移动端点会把 hover 做 hack，变成点击展示。取消时点击外面就行了。如果想要做成纯点击展示/隐藏 请参考上方 @imhele  的回复。

**Comment by xgj1988** [comment]
好的。。谢谢两位 。。
