### ISSUE TITLE
Add new StaticTag component

### ISSUE THREAD

**Issue by mgcrea** [ant-design/ant-design#15114]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Really like the style of the existing `Tag` component, however, it's actually a `CheckableTag` out-of-the-box with onClick animation & hand pointer-icon, etc.

That does not really fit well if you want to use it as a purely static styled element.

### What does the proposed API look like?

Add a new <StaticTag> component, maybe the existing `Tag` component could leverage it to keep things DRY.

An alternative could be to add a new prop (boolean `static`) to the existing component.

**Comment by zombieJ** [comment]
Do you mean you wish Tag component without wave effect. right?

**Comment by afc163** [comment]
Tag not clickable without hand pointer.

**Comment by 7Charlotte** [comment]
在标签（tag）控件的API并没有看到如何设置，请问应该如何设置才能达到“鼠标经过tag无需变为手型，且点击tag没有点击动画”的效果？

**Comment by afc163** [comment]
@7Charlotte We intend to make Tag not have hover/wave styles defaultly, it still on going.

**Comment by 7Charlotte** [comment]
> Remove hand pointer style of clickable Tag.



> @7Charlotte We intend to make Tag not having hover/wave styles defaultly, it still on going.

Then how long will it be ready?

**Comment by afc163** [comment]
This weekend I believe.

**Comment by 7Charlotte** [comment]
> This weekend I believe, please trace #15310

That's Great! Thanks so much!
