### ISSUE TITLE
Affix 固钉 When resize is doing, the outer div height will be lost.

### ISSUE THREAD

**Issue by hfuuss** [ant-design/ant-design#15112]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ppnrk50ozx)

### Steps to reproduce
just press  '''command   shift   i''' to open Chrome DevTools。It will cause 'resize' event

### What is expected?
the outer div height will be not lost.

### What is actually happening?
the outer div height will be lost.

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | lasted |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
Why not just use position: fixed? If you want to ping on the top? https://codesandbox.io/s/jj8jwkkkr3

**Comment by hfuuss** [comment]
> Why not just use `position: fixed` if you want to ping on the top? https://codesandbox.io/s/jj8jwkkkr3

Of course, there are many, many solutions. But when I upgraded antd yesterday, this problem occurred. So I want to know why the official is doing this.

**Comment by hfuuss** [comment]
俩个中国人 飙英文，很难受

**Comment by zombieJ** [comment]
这个可能要改一下 Affix 的测量流程，我先占个位。

**Comment by SilentFlute** [comment]
之所以这样解决这个问题，是因为一开始是边框有个颜色，但是看起来不好看，怪怪的，我就把边框去了，结果出问题了，而有边框的时候没问题，于是就干脆把边框颜色设为透明，没想到就阴差阳错的解决了这个问题

**Comment by yoyo837** [comment]
搞个 重现demo 看看
