### ISSUE TITLE
Tree, TreeSelect a new feature request

### ISSUE THREAD

**Issue by plandem** [ant-design/ant-design#1511]
Well, these components wants an array with nodes. I would like to have the abilty to get node (that i passed to TreeSelect) via id. You already have such functionality. The case is:
i have TreeSelect and Breadcrumb. I want to show 'path' at Breadcrumb, but i don't want to have 2 structures of items to get it - one for TreeSelect (flat array with nodes) and another for Breadcrumb (Object indexed by id). OnChange/OnSelect would help, but i also need to get event on initial render.

Right now i have to store in memory two copy - one array for tree and another for breadcrumb. In some cases i have about 18k nodes and about 2Mb of raw JSON data.

If it would be possible to pass object(with items) indexed by id to the TreeSelect, it would solve this task too. To summarise:
1) add event at render() and pass node (like onSelect, but for render) OR
2) add ability to pass Object (not only Array) with nodes indexed by id (like:
```
{
"1-2-3": { label: 'title 1', id: '1-2-3'},
"2-3": {label: 'title 2', id: '2-3'}
}
```

**Comment by warmhug** [comment]
I'm sorry I can't understand clearly. Better there are more codes or examples. In addition, `onChange`'s third parameter may be useful to you? try it.

![image](https://cloud.githubusercontent.com/assets/2011119/14912485/301191ee-0e2f-11e6-9def-1249cf406fe4.png)

**Comment by plandem** [comment]
the idea is: i need same hierarchy data for two components - TreeSelect and Breadcrumb. Right now i store locally my tree as **raw data**: 
```
{
100: { id: 100, title: "node 100", description: "desc 100", parent_id: null},
101: { id: 101, title: "node 101", description: "desc 101", parent_id: 100},
...
}
```

for my TreeSelect i have to transform it to **tree select** data:
```
[
{id: 100, label: "node 100", children: [ {id: 101, label: "node 101"} ]
]
```

and same time still keep **raw data** to use it at Breadcrumb, it's indexed by id, so it's not very hard to build path from leaf up to root like: node 100 -> node 101


About feature....i asked to have ability to use **raw data** for TreeSelect, in that case i will not need to transform indexed object into array and it will be possible to use same object to resolve path for Breadcrumb.


As i said, in my case, sometimes i have like 18K nodes and about 2Mb raw JSON, to having 2 copy of same data is not good idea. OnChange of TreeSelect can't help me because this happens only for changes and i can't use it to render initial state.

**Comment by warmhug** [comment]
Ok, I understand. I consider to support it (the transform like [this](https://github.com/warmhug/__/blob/master/misc/tree.html#L31) should work?). And some other `Tree` components have data transform features indeed.

**Comment by plandem** [comment]
Well...it's better, but still flatten array, a bit different, but still flatten :( i can't get path from leaf up to root without traversing tree. I can't use it like:
```
let node = node;
const path = [];
while(node) {
path.push(node.title);
node = items[node.parent_id];
}
```

What i need?
1) use same hierarchy data for differ components
2) have a way to get full node via id (TreeSelect uses ID of node to select it)

````
  render() {
    const { id, color, title, prefixCls, tree, searchPlaceholder, valuePlaceholder, intl: { formatMessage } } = this.props;
    const valuePath = id && items.size resolveTreePath(items, id);
    const valuePath = [];

    return (
<div>
              <TreeSelect className={`${prefixCls}-value-input`}
                          dropdownClassName={`${prefixCls}-value-dropdown`}
                          showSearch
                          treeLine
                          value={id}
                          treeData={tree}
                          dropdownMatchSelectWidth={false}
                          filterTreeNode={filterTreeNode}
                          showCheckedStrategy={TreeSelect.SHOW_ALL}
                          searchPlaceholder={searchPlaceholder || formatMessage(messages.searchPlaceholder)}
                          placeholder={valuePlaceholder || formatMessage(messages.valuePlaceholder)}
                          onChange={(id) => this.handleChanges({ id })}/>
            </Form.Item>
            <Breadcrumb>{
              valuePath.map((label, i) => (
                <Breadcrumb.Item key={i}>{label}</Breadcrumb.Item>
              ))}
            </Breadcrumb>
        }
      </div>
    );
  }
````
as you can see right now i have 2 copy of data: **items** and **tree**, where **items** is raw data (hash object indexed by ID) and **tree** array of nodes. I would like to use same hash object for TreeSelect and also be able to traverse tree to get path from leaf up to root.

This one:
```
    const valuePath = id && items.size resolveTreePath(items, id);
```

is just simple:
```
let node = node;
const path = [];
while(node) {
path.push(node.title);
node = items[node.parent_id];
}
```

**Comment by warmhug** [comment]
Yes, you're right. With a lot of data,  [this method](https://github.com/warmhug/__/blob/master/misc/tree.html#L31) also is not efficient. 

This data structure
```
{
100: { id: 100, title: "node 100", description: "desc 100", parent_id: null},
101: { id: 101, title: "node 101", description: "desc 101", parent_id: 100},
...
}
```
should be much better.

**Comment by warmhug** [comment]
try `rc-tree-select@1.6.0-beta`, demo is [here](http://react-component.github.io/tree-select/examples/basic.html). 
![image](https://cloud.githubusercontent.com/assets/2011119/14981241/58e4dcbe-1160-11e6-84fa-f46248e6f27b.png)
