### ISSUE TITLE
TreeNode 组件是否支持扩展内容

### ISSUE THREAD

**Issue by TongDaDa** [ant-design/ant-design#15123]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 TreeNode 右侧添加自定义按钮等操作 

### What does the proposed API look like?
TreeNode 的 child 不仅限于TreeNode 组件，可以使用 React.Fragment 来生产多个平级组件结构

**Comment by TongDaDa** [comment]
For example, I want to mount a tag myself on the right of NodeTree components.


<img width="502" alt="2019-03-01 11 45 31" src="https://user-images.githubusercontent.com/23241188/53615157-9f894a80-3c17-11e9-8e60-fe3ee988331a.png">

**Comment by zombieJ** [comment]
title 属性是可以接受 ReactNode 的，直接写就行了。

**Comment by TongDaDa** [comment]
@zombieJ 谢
