### ISSUE TITLE
build后dist中没有生成本地字体文件

### ISSUE THREAD

**Issue by hccao** [ant-design/ant-design#1512]
使用local-iconfont这个demo，build后dist目录中生成了index.css，index.js，common.js三个文件，没有字体文件，直接使用的话需要自行拷贝字体文件，而且需要修改index.css中字体文件的路径，否则浏览器一直会报找不到字体文件的异常
我用的是windows的操作系统，没有试过linux，不知道是不是一样的

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/local-iconfont/iconfont

你需要自行部署字体文件到自己的 cdn 或本地路径，或探索 webpack 的打包引用方案。

那个例子只是一个简单的本地示例，不是完整的工程项目。也欢迎给我们 PR~
