### ISSUE TITLE
collapse 面板改变单个面板的title字体颜色

### ISSUE THREAD

**Issue by 13273418301** [ant-design/ant-design#15126]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能够解决单个面板title字体的颜色设置

### What does the proposed API look like?
<nz-collapse>
            <nz-collapse-panel [nzHeader]="''" [nzActive]="true" style="color:red">
                <p style="margin:0;">
                 //可以改变单个面板nzHeader颜色 不影响其他面板的title颜色
                </p>
            </nz-collapse-panel>
</nz-collapse>

**Comment by afc163** [comment]
Try `<Panel className="xxx" style={{ ... }} />`.
