### ISSUE TITLE
This is a bug NOT just a issue

### ISSUE THREAD

**Issue by Queency1212** [ant-design/ant-design#15129]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
We import DatePicker from antd in our web page.

Requirement:  When we pick a date from the choice box, the date need to display in this page at the same time.

Development: Use the first parameter 'value' from onChange(value,dateString) to  transition to local time and display in page.

Testing: Sometimes when we pick 'Today' from choice box the date display is next day.

### What is expected?
After transform value._d  from GMT to format(YYYY-MM-DD), the time is 8 hours earlier than local time.

We need a right time for local or a right GMT time.

I think the time is right, but users (like me) need the right parameter from API antd offered.

### What is actually happening?
API antd provided is NOT perfect.

Sometimes incomplete is normalcy, and it need our concerted effort. 

Maybe it push us.

| Environment | Info |
|---|---|
| antd | 3.0.2 |
| React | 15.6.1 |
| System | Windows 7 |
| Browser | google |

---
Mutual encouragement!

**Comment by zombieJ** [comment]
Thanks for issue. It's caused by monent timezone. You can ref here to set it: https://github.com/ant-design/ant-design/issues/11012
