### ISSUE TITLE
customize spin indicator in Table component

### ISSUE THREAD

**Issue by mstao** [ant-design/ant-design#15132]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to customize indicator of Spin component in Table component, but I can't found that how to set the specified spin. From the api of table, I just found `loading` configuration.

### What does the proposed API look like?
```
<Table loading={loading} loadingIndicator={(<Icon type="loading"  />)} />
```

**Comment by zombieJ** [comment]
Maybe we can also support this in ConfigProvider.
@afc163 @ztplz

**Comment by mstao** [comment]
I found this code : https://github.com/ant-design/ant-design/blob/9a022b8aaca954bfca82234cfec812e801ba0c4e/components/table/Table.tsx#L987

So I can write this code:

```
    const tableLoading = {
      spinning: loading,
      indicator: <Icon type="loading"  />,
    }

  <Table loading={tableLoading} />
```

**Comment by afc163** [comment]
https://codesandbox.io/s/n15m5z0o34

**Comment by sydinh** [comment]
@mstao It works well. Thanks bro!
