### ISSUE TITLE
日期区间选择和时间区间选择布局不一致

### ISSUE THREAD

**Issue by guxingke201** [ant-design/ant-design#15135]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-presetted-ranges](https://ant.design/components/date-picker-cn/#components-date-picker-demo-presetted-ranges)

### Steps to reproduce
分别点击两个时间区间输入框
![image](https://user-images.githubusercontent.com/8326941/53632100-0b3ada00-3c4f-11e9-8377-861af0660f68.png)

![image](https://user-images.githubusercontent.com/8326941/53632143-1e4daa00-3c4f-11e9-9d7d-4b964d0dc971.png)

### What is expected?
不管是选择时间还是选择日期，布局能够一致

### What is actually happening?
1. 选择日期的输入框，开始日期和结束日期和输入框对齐
1. 选择时间的输入框，开始时间和结束时间和面板对齐

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.6.3 |
| System | win10 |
| Browser | Chrome |

**Comment by doter1995** [comment]
我想占个位，第一次试试为开源做贡献。
I want try, try to contribute to open source for the first time.

**Comment by zombieJ** [comment]
这是故意这么设计的。如果不需要这个样式，你可以用 css 覆盖掉它。

**Comment by guxingke201** [comment]
@zombieJ 请问这么设计的理由是因为时间比较长吗？如果把日期也改成和时间一样的，会有什么问题？

**Comment by zombieJ** [comment]
https://ant.design/docs/spec/proximity-cn  根据亲密性原则，相关联的内容应该更贴近。而日期格式的一个点特就是只要保证了 YYYY-MM-DD 长度可以显示就没有问题了。但是日期带时间格式长度比较难确定，太窄容易出现文字被遮挡的情况，太宽就和现在直接分开放没区别了。

**Comment by guxingke201** [comment]
谢谢
