### ISSUE TITLE
table组件，rowSelection开启多选框，点击任何checkbox，都会触发每行的expandedRowRender事件，请问这是否合理？

### ISSUE THREAD

**Issue by xiaojiazu** [ant-design/ant-design#15136]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xjrzx3473z)

### Steps to reproduce
第一行默认展开了expandedRowRender，点击任意一行checkbox，都会改变第一行的expandedRowRender中的值，点击checkbox触发此事件是否合理？？？ 如何禁用？

### What is expected?
不触发

### What is actually happening?
触发

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.7.0 |
| System | win |
| Browser | chrome |

**Comment by afc163** [comment]
合理的，这就是 React，每次状态变化 render 都会运行。
