### ISSUE TITLE
同时使用树形Table和可拖动Tree控件，数据源不同，Tree拖动后，Table数据源会更新

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#15131]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/340z01kpl6)

### Steps to reproduce
拖动Tree控件后，Table树形表格数据也会在原有的基础上更新。
在重现链接里举例：将Tree下的0-0移至0-2下，Table的0-2下也会出现0-0的数据，但是两个用的是不同的数据源，Tree移动后setState也只是更新了TreeData的数据。

### What is expected?
两者之间不会有数据冲突。

### What is actually happening?
Tree移动后，属性Table与之有数据冲突。

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | React16.7.0 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

**Comment by zombieJ** [comment]
建议了解一下浅拷贝和深拷贝的区别，data 和 gDate 里的 children 以及子 children 其实是相同的 children，导致你改了一个，另一个也跟着变了。
