### ISSUE TITLE
ScrollNumber.d.ts is wrong with ts check TS2314

### ISSUE THREAD

**Issue by zurex** [ant-design/ant-design#15134]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/3.13.6/components/badge/ScrollNumber.tsx](https://github.com/ant-design/ant-design/blob/3.13.6/components/badge/ScrollNumber.tsx)

### Steps to reproduce
see code in ./node_modules/antd/lib/badge/ScrollNumber.d.ts:27:41 

### What is expected?
renderNumberList(position: number): React.ReactElement<string | ((props: any) => React.ReactElement<any, string | any | (new (props: any) => React.Component<any, any, any>)> | null) | (new (props: any) => React.Component<any, any, any>)>[];

### What is actually happening?
renderNumberList(position: number): React.ReactElement<any, string | ((props: any) => React.ReactElement<any, string | any | (new (props: any) => React.Component<any, any, any>)> | null) | (new (props: any) => React.Component<any, any, any>)>[];

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.7.0 |
| System | mac os v10.14.2 |
| Browser | chrome 72.0.3626.119 |

---
ReactElement<P>, only support one argument.
The code in ScrollNumber.d.ts give two arguments.

The more error:

ERROR in [at-loader] ./node_modules/antd/lib/badge/ScrollNumber.d.ts:27:41 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/antd/lib/badge/ScrollNumber.d.ts:48:68 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/antd/lib/badge/index.d.ts:44:30 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/antd/lib/form/FormItem.d.ts:49:67 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/antd/lib/form/FormItem.d.ts:50:23 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/antd/lib/locale-provider/index.d.ts:50:48 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/antd/lib/statistic/Countdown.d.ts:18:25 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/antd/lib/statistic/Countdown.d.ts:18:247 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

ERROR in [at-loader] ./node_modules/antd/lib/tree/Tree.d.ts:157:59 
    TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

**Comment by zombieJ** [comment]
`@types/react` update the ReactElement definition. Please reinstall related deps instead.
