### ISSUE TITLE
InvalidPipeArgument: 'Missing locale data for the locale "ar".' for pipe 'DatePipe'

### ISSUE THREAD

**Issue by HDaghash** [ant-design/ant-design#15139]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
1-Set local provider for arabic 
2-add date picker component 
3-try to select date

### What is expected?
date picker popup should show up

### What is actually happening?
console error message showing : InvalidPipeArgument: 'Missing locale data for the locale "ar".' for pipe 'DatePipe'

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | Angular 7 |
| System | version": "7.0.0-rc.3 |
| Browser | chrome latest  |

---
this is hapning in angular ant design version   "version": "7.0.0-rc.3",

**Comment by HDaghash** [comment]
wrong repo sorry ..

**Comment by renilbabu03** [comment]
I still have this issue. Changed language to arabic but the datepicker is throwing this error.!
