### ISSUE TITLE
InputNumber blur triggering onChange prop when you type something in it

### ISSUE THREAD

**Issue by LoDornelles** [ant-design/ant-design#15140]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/LoDornelles/pen/jJqNbx?editors=0010](https://codepen.io/LoDornelles/pen/jJqNbx?editors=0010)

### Steps to reproduce
Focus on InputNumber with onChange prop, type a number on it and then lose focus

### What is expected?
That the InputNumber don't trigger onChange function when blurred after typing

### What is actually happening?
When blurring InputNumber it triggers the onChange function

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.6.3 |
| System | Windows 7 |
| Browser | Chrome 72.0.3626.119 |

**Comment by zombieJ** [comment]
It's by design. InputNumber will update the number after onBlur. You can type 33 and blur will find onChange trigger 33 and then 10 finally.

**Comment by luoyifanff** [comment]
> It's by design. InputNumber will update the number after onBlur. You can type 33 and blur will find onChange trigger 33 and then 10 finally.

Unfortunately, I had a problem.
 **_Scene_**: I set values for another component when **InputNumber** trigger **onChange** event; but I don't want to set the value when I lose focus.By the way, **InputNumber** will **autoFocus** at componentDidMount.The another component should **validate** value when I handleClick.
**_Result_**: This will cause the value to be set first and then validate.
