### ISSUE TITLE
关于自定义样式的疑问

### ISSUE THREAD

**Issue by WhatAKitty** [ant-design/ant-design#1514]
想问一下，如何进行覆盖样式的操作？由于版本升级频繁，不想直接在antd的less文件上进行样式的编辑。

**Comment by afc163** [comment]
直接定义单独的样式，全局进行覆盖即可。

**Comment by xileliu** [comment]
重置按钮或者input的 disable的颜色 button： @btn-disable-border； 但是input的是不是没有呢
