### ISSUE TITLE
Drawer弹出时动画效果错误

### ISSUE THREAD

**Issue by zlljqn** [ant-design/ant-design#15146]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q947510vw)

### Steps to reproduce
When the page have scrollbar, close Drawer and open it with 'bottom' placement. Drawer will flash on the top and then display on the bottom. (it may due to the offset of scrollbar haven't been calculated) 
当页面有滚动条时，关闭Drawer，以bottom方式再打开，Drawer会在顶部闪现，然后再在底部显示。（估计Drawer动画没有计算滚动条）
【新增问题】主窗口滚动条消失了

### What is expected?
Should not flash on the top. the animation should play on the bottom
正常在底部动画展现。
主窗口滚动条不希望消失，没有mask就是为了Drawer和主窗口内容联动。

### What is actually happening?
Drawer will flash on the top and then display on the bottom. (it may due to the offset of scrollbar haven't been calculated) 
Drawer会在顶部闪现，然后再在底部显示。（估计Drawer动画没有计算滚动条）
【新增问题】主窗口滚动条消失了

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.6.3 |
| System | Windows |
| Browser | Google Chrome 版本 72.0.3626.109（正式版本） （32 位） |

**Comment by afc163** [comment]
这个之前考虑过，因为真实业务不会这么用，就没有予以修复。

**Comment by zlljqn** [comment]
不是切换展开方向，方向一直是从底部展开，应该不是一个问题，https://codesandbox.io/s/q947510vw
这个Codesandbox可以复现，就选中Bottom方式，打开关闭打开关闭打开关闭，每次都可以复现

**Comment by zlljqn** [comment]
mmmm。。。。又发现一个问题是，如果打开从底部展开的Drawer会把主窗口的Scrollbar hide掉，是不是用了全局的overflow:hidden了。。。从底部展开的Drawer不应该影响主窗口的Scrollbar吧。

**Comment by afc163** [comment]
还是提供一下 GIF 图吧，不同的操作系统滚动条不一样，我不确定我看到的和你描述的是不是同一个问题。

**Comment by zlljqn** [comment]
![aaa](https://user-images.githubusercontent.com/13447784/53692423-9f7d7c00-3dca-11e9-960f-7506d138c612.gif)
录好了

**Comment by ztplz** [comment]
跟遮罩有关
