### ISSUE TITLE
DatePicker使用校验时报Uncaught TypeError: value.getTime is not a function

### ISSUE THREAD

**Issue by totothink** [ant-design/ant-design#1515]
定义发布时间的校验规则：
```jsx
const publishedAtProps = getFieldProps('published_at', {
  rules: [
    { required: true, message: '请选择时间', type: 'date' }
  ]
})
```

定义组件：
```jsx
<DatePicker {...publishedAtProps} showTime format="yyyy-MM-dd HH:mm" placeholder="请选择时间" />
```

提交时：
```jsx
    this.props.form.validateFields((errors, values)=>{
      ......
    })
```

在新创建时正常；编辑时，如果没有做任何修改提交会报：Uncaught TypeError: value.getTime is not a function。

- antd@0.12.12:
- OSX 10.11.4 (15E65):
- Chrome版本 50.0.2661.86 (64-bit):

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by benjycui** [comment]
> 编辑时，如果没有做任何修改提交
不是很能理解，麻烦提供 demo 和重现步骤。

**Comment by afc163** [comment]
没有反馈就关了啊，提供 codepen 的示例，我们无法重现。

**Comment by remxcode** [comment]
我也遇到了这个问题，解决方法如下：
在编辑时，你需要将published_at值的格式从String转换成Date，才会有getTime方法
`getFieldProps('published_at', {
        initialValue: published_at.value?new Date(published_at.value):undefined,
        rules: [{
          type: type,
          required: true,
          message: '请填写内容'
        }]
      })`

参考link：http://stackoverflow.com/questions/2627650/why-javascript-gettime-is-not-a-function

**Comment by benjycui** [comment]
信息不足，无法判断是 bug 还是使用方式的问题

**Comment by benjycui** [comment]
可能有问题，既然 `DatePicker` 的 `value` 可以是 `string`，那么在和 `getFieldProps` 一起用时，应该也要支持 `string`。

稍后有时间再排查，暂时用转为 `Date` 的方法解决。

**Comment by longang520** [comment]
嗯嗯，支持 @benjycui

**Comment by afc163** [comment]
1. 要么设定 type为 `date`。
2. 要么按 https://github.com/ant-design/ant-design/commit/9c28420468c637a6f891a1bd5d828a15230b0e96，把 `dateString` or ` timeString` 作为校验的值。

**Comment by hust419** [comment]
的确比较恶心，而我设置的是yyyyMMdd的格式，而且还自作主张的把 201675转成了20160705,结果就悲剧了，new Date(String)直接界面就nannana了。 



我的处理代码如下：
`	<FormItem
	          				label="预测时间"
	          			    required
	          				id="predictTime"
  							{...formItemLayout}
  							hasFeedback
	        			>
	        			<DatePicker format="yyyyMMdd" disabledDate={disabledDate}  {...getFieldProps('predictTime', {
	        				rules:[{required:true, type:'date', message:'预测时间不能为空'}] ,
	        				initialValue:data.predictTime ? new Date(data.predictTime) : ''
	        		     })} 
	        			/>
	        			</FormItem>


handleSubmit(e) {
	    this.props.form.validateFields((errors, values) => {
	      if (!!errors) {
	        return;
	      }
	      const url = window.icePageConfig.submitApi;
	      const data = {
	        ...values,
	        id: window.icePageConfig.id || '',
	        predictTime:getDate(values.predictTime)
	      };

 。。。 省略若干

const getDate = (date) => {
	debugger;
  if (typeof date != 'string') {
      return date.getFullYear() + ((date.getMonth() + 1) >=10  ?  ((date.getMonth() + 1) + '') : '0' + (date.getMonth() + 1) )
       +  (date.getDate() >=10 ? date.getDate() : ('0' + date.getDate()));
  } 
  return date;
}


	 const disabledDate = function (current) {
    	 	return current && current.getTime() < Date.now();
		};
`
