### ISSUE TITLE
PageHeader not support `className` prop

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15157]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zk45mjkwx4)

### Steps to reproduce
```jsx
<PageHeader className="not-works" />
```

### What is expected?
className should pass to top div element.

### What is actually happening?
Not pass.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
so soon~

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/53721703-d1601280-3e9e-11e9-839b-2ee5fa3040cb.png)
其实 style  title  class 都是元素里自带的属性
继承 AllHTMLAttributes 就行了   
这样我们 interface 更清晰
