### ISSUE TITLE
Form 支持 colon

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15161]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
避免 FormItem 每个都要设置一遍。

### What does the proposed API look like?
```jsx
<Form colon={false}>
  ...
</Form>
```

**Comment by DiamondYuan** [comment]
遇到这种怎么处理呢？

```javascript
<Form colon={false}>
  <Form.item colon={true}/>
</Form>
```

还是显示么。

**Comment by zombieJ** [comment]
> 遇到这种怎么处理呢？
> 
> ```js
> <Form colon={false}>
>   <Form.item colon={true}/>
> </Form>
> ```
> 
> 还是显示么。

嗯，和现在的 labelCol & wrapperCol 逻辑一样处理。

**Comment by DiamondYuan** [comment]
> > 遇到这种怎么处理呢？
> > ```js
> > <Form colon={false}>
> >   <Form.item colon={true}/>
> > </Form>
> > ```
> > 
> > 
> > 还是显示么。
> 
> 嗯，和现在的 labelCol & wrapperCol 逻辑一样处理。

写好了。

**Comment by DiamondYuan** [comment]
等发版之前在新增API前面增加 ?
```javascript
 /**
   * 
   * @since 3.x.xx
   */
```
这样以后就不需要自己一个个去看 changelog了。

**Comment by zombieJ** [comment]
> 等发版之前在新增API前面增加 ……

👌顺道给 PR 的 template 加一个备注吧，这样也可以提醒一下免得忘记了~

**Comment by DiamondYuan** [comment]
> > 等发版之前在新增API前面增加 ……
> 
> 👌顺道给 PR 的 template 加一个备注吧，这样也可以提醒一下免得忘记了~

假如一个人在 3.3.1 的时候提交了一个 feature 的 pr，而 3.4.1 的时候才发布到 npm。
这样注释很难写。无法预知他提交的功能会在什么时候被发布到npm。

**Comment by DiamondYuan** [comment]
只有写 changelog 的人才知道。

**Comment by afc163** [comment]
不用担心，下一个 feature 版本一定是 `3.15.0`。
