### ISSUE TITLE
Want to access Less variables in JS. 希望提供JS中的样式变量。

### ISSUE THREAD

**Issue by gqqazgogogo** [ant-design/ant-design#15168]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We use styled-components in our Project. I can not get the variables from Less. So I wish I can get variables in JS. Is there a solution that I haven't found yet? Thanks.
在项目开发中使用了styled-components，在编写StyledComponent时无法访问less变量，所以希望有js版本的less变量，或者现在是否已经有了解决方案，只是我没有找到？谢谢。

### What does the proposed API look like?
JSON

**Comment by afc163** [comment]
You can try https://github.com/michaeltaranto/less-vars-to-js

**Comment by WellerQu** [comment]
我也产生了同样的需求 ~
