### ISSUE TITLE
FormItem Context.Consumer key warning

### ISSUE THREAD

**Issue by izorg** [ant-design/ant-design#15166]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3qoyjmxm9)

### Steps to reproduce
- open https://codesandbox.io/s/j3qoyjmxm9
- open console

### What is expected?
No console warnings

### What is actually happening?
Warning: Each child in a list should have a unique "key" prop.

| Environment | Info |
|---|---|
| antd | 3.14.0 |
| React | 16.8.3 |

**Comment by afc163** [comment]
Fixed in #15160
