### ISSUE TITLE
执行antd-init报下面这种错，是我的环境没配置好吗

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design#1516]
请问一下我调用antd-init后，报了下面的错是我什么东西没配置好吗
gyp: binding.gyp not found (cwd: F:\shine\nodeproject\blog) while trying to load
 binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (F:\shine\node\node-global\node_modu
les\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)
gyp ERR! System Windows_NT 6.1.7601

**Comment by afc163** [comment]
检查本地 node 环境。https://www.google.co.jp/search?q=gyp:+binding.gyp+not+found&ie=utf-8&oe=utf-8&gws_rd=cr&ei=qQUfV8uSN-S-mwWB76GIBw
