### ISSUE TITLE
TypeScript: <Layout> requires a `tagName` property

### ISSUE THREAD

**Issue by ngolin** [ant-design/ant-design#15162]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/layout/layout.tsx](https://github.com/ant-design/ant-design/blob/master/components/layout/layout.tsx)

### Steps to reproduce
in .tsx define <Layout/>.

### What is expected?
No need to define `tagName` property. 

### What is actually happening?
Require to define `tagName` property.

| Environment | Info |
|---|---|
| antd | 3.14.0 |
| React | react 16.8.3 |
| System | MacOS 10.14 |
| Browser | Chrome 72 |

**Comment by afc163** [comment]
Why do you need `tagName`?

**Comment by ngolin** [comment]
@afc163 Read the code in: https://github.com/ant-design/ant-design/blob/master/components/layout/layout.tsx
```
export interface BasicProps extends React.HTMLAttributes<HTMLDivElement> {
  prefixCls?: string;
  hasSider?: boolean;
  tagName: 'header' | 'footer' | 'main' | 'section';
}
```
Now the `tagName` is required.

I suggest a fix:
```
export interface BasicProps extends React.HTMLAttributes<HTMLDivElement> {
  prefixCls?: string;
  hasSider?: boolean;
  tagName?: 'header' | 'footer' | 'main' | 'section';
}
```

**Comment by afc163** [comment]
PR is welcome~

**Comment by jdpigeon** [comment]
Can't wait for fix :pray:

**Comment by zy410419243** [comment]
+1, it breaks my ci test.

https://circleci.com/gh/zy410419243/zy410419243.github.io/429?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
