### ISSUE TITLE
Responsive menu not working with only one item collapsed

### ISSUE THREAD

**Issue by marinelligiovanna** [ant-design/ant-design#15179]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://0o1m9x916l.codesandbox.io/

### Steps to reproduce
1. Open the link provided above or the ant design menu page (https://ant.design/components/menu/)
2. Open Chrome Developer tools by pressing F12 and change to mobile view (Ctrl   Shift   M)
3. On the device selector, choose responsive
4. Decrease (or increase) the responsive device width so that only the last item of the menu is collapsed in the dropdown item with the ellipsis icon (in antd page, the menu refers to the Top Navigation Example)
5. Press F5 so that we reproduce the environment of a mobile device with a menu containing only one item collapsed.
6. Click on ellipsis icon and try to click on "Navigation Four - Link"

### What is expected?
When clicking on "Navigation Four - Link" it is expected that we are redirected to the ant design home page, as specified in its code. 

### What is actually happening?
Nothing happens when we click on this item. What is strange is that the menu works perfectly when we have more than 1 item collapsed or the menu is fully expanded. 

| Environment | Info |
|---|---|
| antd | 3.14.0 |
| React | 16.8.3 |
| System | Ubuntu 18 |
| Browser | Chrome 7.0.3626.81 |

---
I ran into this bug while using the Ant Menu to develop a PWA. In Iphone 6 and Moto Z2 play, only one of my menu's item collapses and form a dropdown item with the ellipsis icon. I noted that the onClick event was not working for the collapsed item, which is weird since it was perfectly working on my computer screen. I also noted that in smaller devices on which more than 1 item is collapsed the menu works perfectly. I checked that the same bug occurs in ant design menu page when I use the responsive mobile device feature of Chrome.

**Comment by marinelligiovanna** [comment]
Code Sandbox editor link: https://codesandbox.io/s/0o1m9x916l

**Comment by ztplz** [comment]
Does it only happen on the chrome browser?

**Comment by marinelligiovanna** [comment]
No it also happens on safari of an Iphone 6 and Iphone X. I will check the version of both browsers as soon as possible.

**Comment by afc163** [comment]
We don't offer offcial support on mobile devices now, please help by sending us pull request if you can and dig in and resolve the problem.

**Comment by marinelligiovanna** [comment]
Sure, afc. I will take a look!

**Comment by marinelligiovanna** [comment]
> We don't offer offcial support on mobile devices now, please help by sending us pull request if you can and dig in and resolve the problem.

Sure afc. I will take a look!

**Comment by ztplz** [comment]
It's not a issue relate to mobile. Actually it's a bug. This bug can still be reproduced on the desktop if you set the `triggerAction` to click.
