### ISSUE TITLE
setContentRef required for Typography component

### ISSUE THREAD

**Issue by dfee** [ant-design/ant-design#15188]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/2996d8e62569505d2a429ce35cdfd8a8c447a7fc/components/typography/Typography.tsx#L16](https://github.com/ant-design/ant-design/blob/2996d8e62569505d2a429ce35cdfd8a8c447a7fc/components/typography/Typography.tsx#L16)

### Steps to reproduce
Use <Typography>

### What is expected?
setContentRef should be optional.

### What is actually happening?
setContentRef is required.

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.2 |
| System | MacOS 13.1 |
| Browser | FF |

---
The solution is to make `setContentRef?: (node: HTMLElement) => void` or... just set it to `setContentRef?: React.Ref<HTMLElement>`...

**Comment by afc163** [comment]
`InternalTypographyProps` is not internal now. @zombieJ
