### ISSUE TITLE
RangePicker: end date shifted because of margin-left: -90px

### ISSUE THREAD

**Issue by kyriiherman** [ant-design/ant-design#15185]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yql0v89o91)

### Steps to reproduce
Click on range-picker input and see that end date in shifted to the left

### What is expected?
End date should be aligned with the second calendar

### What is actually happening?
End date in shifted to the left

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.5 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
It is by designed.
