### ISSUE TITLE
DatePicker显示语言错误

### ISSUE THREAD

**Issue by shishui508** [ant-design/ant-design#15180]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/date-picker-cn/](https://ant-design.gitee.io/components/date-picker-cn/)

### Steps to reproduce
已做zh-CN中文配置，但显示这种中文 英文的，也是醉了。

### What is expected?
修复bug

### What is actually happening?
已做zh-CN中文配置，DatePicker 点击后弹出中文 英文组合的框，如【2019年Mar】。经测3.13没问题，在此以后版本都有问题

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.3.2 |
| System | 5.4 |
| Browser | chrome |

**Comment by xyy94813** [comment]
1. Determine if the project is directly dependent on Moment
2. Check if the version of Moment is compatible with the version antd depends on
3. Try to use same version of moment

**Comment by zsio** [comment]
我也遇到了   
@afc163 
https://codesandbox.io/s/6y3xrx1wln?fontsize=14

**Comment by afc163** [comment]
https://ant.design/components/locale-provider-cn/

**Comment by yoyo837** [comment]
我也遇到几次，但特意想重现的时候又不知道怎么弄出来。

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/53950661-a298a500-4107-11e9-97a3-288682ab95ce.png)
@zsio 我加了之后没啥问题啊

**Comment by yoyo837** [comment]
@ztplz 非必现，我个人还没找到触发时机。

**Comment by xyy94813** [comment]
reproduce:
https://codesandbox.io/s/m7m4698n89

**Comment by afc163** [comment]
```idff
-   "moment": "2.22.2",
+   "moment": "^2.22.2",
```

**Comment by zsio** [comment]
@zaphz yes  这个反馈的code是我没加语言包  

但是我在 `antd pro` 上使用的时候即使手动引入了语言包  依然是英文的    我不确定是不是 `antd` 的问题, 也可能是 `Moment.js` 和 `antd` 的兼容问题, 现在我不得不把版本控制在之前.

**Comment by ztplz** [comment]
好像是moment配置的锅

**Comment by Tosiwe** [comment]
![image](https://user-images.githubusercontent.com/13794769/54403790-4982cf80-470c-11e9-8875-df6e53ae63ed.png)

**Comment by afc163** [comment]
请提供可重现的 GitHub 仓库，我会 reopen 并排查。

**Comment by Tosiwe** [comment]
卸载了antd 重装之后问题解决了。。。

**Comment by shaotianyu** [comment]
I also encountered similar problems in the test environment.
But the local environment is good.
Win10 Operating System I Used


> "antd": "^3.16.1"
> "moment": "^2.22.2"


my solution：

```
import moment from 'moment'
import 'moment/locale/zh-cn'
moment.locale('zh-cn')
......
<DatePicker defaultPickerValue={ moment(xxx) } ...
or
<DatePicker value={ moment(xxx) } ...
```
In some cases, it can solve the bug of mixing Chinese and English in DatePicker.
Hopefully this will help some people.
If you have better suggestions, please @ me.

**Comment by GrayFrost** [comment]
重装antd和moment

**Comment by ye-xiao-yu** [comment]
> 重装antd和moment
亲测有效

**Comment by LeeHarlan** [comment]
也遇到了这问题，最后把 moment 升级到了 2.24.0 显示正常了

**Comment by zlyyyy** [comment]
同遇到这个问题。
版本3.21.1
重装都不行，全局设了中文，然后组件又独立使用中文才生效，缺一不可。。

**Comment by afc163** [comment]
@zlyyyy Try 3.21.2

**Comment by zlyyyy** [comment]
@afc163 重装了昨天发布的3.21.2可以了

**Comment by CCSemicircle** [comment]
我也遇到过，不过是导包问题，一开始导入的是‘antd/lib/locale-provider/zh_CN’, 改为‘antd/es/date-picker/locale/zh_CN’就正常了
