### ISSUE TITLE
Accept moment duration for RangePicker range

### ISSUE THREAD

**Issue by FoxxMD** [ant-design/ant-design#15187]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We parse many component values from the request url when our app loads. Our users expect to be able to parse both absolute and relative dates. We represent absolute dates using [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) like `example.com?fromDate=2019-03-03&toDate=2019-03-04`, and relative dates using [ISO 8601 duration](https://en.wikipedia.org/wiki/ISO_8601#Durations) like this `example.com?dateRange=P1D`. A relative date allows our users to reuse a URL to see a view of data in our app knowing it will always be "1 day" or "7 days" of data, from today's date.

Previously (this was actually working -- accidentally? -- up until at least 3.10.2, maybe more recently, but not from 3.13.4 onwards) if I provided a [moment duration](https://momentjs.com/docs/#/durations/) to `ranges` I would receive the same duration object back in `onChange(dates)` -- this allowed me to determine a user's intention with respect to what kind of dates they wanted to use. If it was a duration object I would then parse out `[moment().subtract(duration), moment()]` and provide this to RangePicker `value` prop.
```js
ranges={{
                      'Last 24 Hours': moment.duration( 1, 'days' ),
                      'Last 30 Days': moment.duration( 30, 'days' ),
                      'Last 7 Days': moment.duration( 7, 'days' ),
                    }}
```

However with the current version passing a `duration` object returns this error when I choose a range:
```
RangePicker.js:27 Uncaught TypeError: arr[Symbol.iterator] is not a function
```

With the current implementation of RangePicker I am now forced to specify the values in `ranges` as absolute dates, which means I also receive absolute dates back in `onChange` so I can no longer determine the intention of the user's action and update the url accordingly.

### What does the proposed API look like?
Two approaches I can see for this:

**Revert `ranges` parameter logic to a previously working state**

Since this used to work I think it would be easiest to just revert to the old logic and let the developer handle what to do with `date` in `onChange`.

**Implement duration handling in `ranges`**

Use the assumption that a "range" is supposed to be from today's date to some previous time and then render RangePicker with that. Still return the duration object in `onChange`

**Comment by zombieJ** [comment]
Close since not plan about this. And v5 use dayjs instead.
