### ISSUE TITLE
table组件滚动条遮挡modal

### ISSUE THREAD

**Issue by 185172970** [ant-design/ant-design#15194]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/1a23f979](https://riddle.alibaba-inc.com/riddles/1a23f979)

### Steps to reproduce
首先滑动table出现滚动条，然后打开modal，然后鼠标移动到table滚动条位置，就会出现

![image](https://user-images.githubusercontent.com/21350840/53777660-1df62d00-3f35-11e9-88f5-45cf895a8580.png)

### What is expected?
不希望table滚动条遮挡，modal

### What is actually happening?
table滚动条遮挡了modal

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16 |
| System | macOS |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/507615/53787402-b4d4e080-3f59-11e9-9451-878081b803cd.png">

我这里无法重现。

**Comment by afc163** [comment]
chrome 和 macOS 的版本是？

**Comment by 185172970** [comment]
> chrome 和 macOS 的版本是？

这里问题复现的技巧是鼠标现在table上晃动，等table滚动条稳定，然后打开model，鼠标在table滚动条位置晃动就会复现，我这里有复现视频，你这里好像不能上传视频，不知道怎么上传

**Comment by afc163** [comment]
拖进输入框里就行。

**Comment by 185172970** [comment]
https://s19.aconvert.com/convert/p3r68-cdx67/3zteq-1wny5.gif

**Comment by zombieJ** [comment]
我重现不出来这个……能把 Chrome 和 Mac 版本发上来吗？

**Comment by 185172970** [comment]
macos 10.13.6
chrome 72.0.3626.121

**Comment by mjfunny** [comment]
我也遇到过这个问题，复现方法是横向拖动Table滚动条后放开，保证滚动条不消失的情况下点开modal，这时候滚动条就会浮现在modal上面

**Comment by ckinmind** [comment]
我也遇到过这种问题，而且更加神奇，我在自己的mac retina屏幕上没有这种modal透出的滚动条，但是我将浏览器拖到比较差的屏幕上，滚动条就投出来了，再移回mac屏幕又没有了，这居然还和屏幕有关系，我的antd版本是3.10.4

**Comment by afc163** [comment]
看上去是 MacOS 在多屏下的兼容性问题，作为组件库可能做不了啥。

**Comment by what-00** [comment]
@185172970 我也出现过这个问题,网上找了很久也没有找到答案,最近实在受不了, 暂时用这种方式把它屏蔽了
```
.ant-table-body {
  overflow-x: hidden !important;
  &:hover {
    overflow-x: auto !important;
  }
}
```

**Comment by ldwonday** [comment]
经常遇到这么问题，烦死了！还没有解决方案吗？

**Comment by ldwonday** [comment]
并不是多屏下的问题！就是table哪里的hover引起的！

**Comment by zombieJ** [comment]
@ldwonday 能帮忙录个屏不？我看一下

**Comment by 185172970** [comment]
[table.mov.zip](https://github.com/ant-design/ant-design/files/3260307/table.mov.zip)
我这里有录屏之前给 你们单独发过

**Comment by zombieJ** [comment]
@185172970 , 嗯，这个录屏试过重现不出来。所以推测是多屏兼容性问题。还是需要稳定重现才能找原因。

**Comment by NewSimpleLife** [comment]
这个BUG真的绝了 ， 和分屏有关系。

**Comment by afc163** [comment]
请升级到 antd 4.0 再试试。
