### ISSUE TITLE
Table排序图标点击排序有问题

### ISSUE THREAD

**Issue by Young-Wang** [ant-design/ant-design#15196]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o5j4rkryqq)

### Steps to reproduce
2.x版本的antd点击排序图标的逻辑是正常的，比如点击三次升序图标，那么排序顺序会是升序排序->取消排序->升序排序
3.x版本的antd点击排序图标的逻辑不正常，比如点击三次升序图标，那么排序顺序会是升序排序->降序排序->取消排序

### What is expected?
排序逻辑应该是2.x版本的逻辑，点击对应的排序图标，应该按照排序->取消排序->排序...的顺序执行

### What is actually happening?
实际结果是3.x版本的逻辑，不管点击哪个排序图标，都是按照升序->降序->取消排序->升序...的顺序

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.5.2 |
| System | Mac OS 10.13.6 |
| Browser | Chrome 72.0.3626.119 |

**Comment by afc163** [comment]
It is not a bug, check https://github.com/ant-design/ant-design/pull/12264

https://ant.design/changelog-cn#3.10.0
