### ISSUE TITLE
TitleProps should be exported

### ISSUE THREAD

**Issue by dfee** [ant-design/ant-design#15190]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/typography/Title.tsx#L8](https://github.com/ant-design/ant-design/blob/master/components/typography/Title.tsx#L8)

### Steps to reproduce
Try and import TitleProps from `antd/lib/typography/Title`

### What is expected?
you get `TitleProps`

### What is actually happening?
`TitleProps` is not exported.

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.2 |
| System | MacOS 13.1 |
| Browser | FF |

---
The solution is to `export interface TitleProps = {...}`.

**this also occurs on TextProps, EditableProps and others in `typography`!**

**Comment by afc163** [comment]
Those names should be renamed before exporting.

**Comment by dfee** [comment]
Who is this a `good first issue` for? I'd solve it but I don't know what the intended names are.

**Comment by ubaid-dev** [comment]
I'd like to help out with this issue.
