### ISSUE TITLE
Ability to customise List / Datasource root components

### ISSUE THREAD

**Issue by tonypee** [ant-design/ant-design#15195]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
By Using <ConfigConsumer> mobx cannot track the render of List, Grid etc. and toJS is required. 

By allowing a custom component to render the content (not simply a <div>, this could be fixed. It would also allow other customisations not related to mobx. 

[To fix issue](https://github.com/mobxjs/mobx-react/issues/649)

### What does the proposed API look like?
For the List component for example: #renderList we would do:

```
const MyList = div

renderList() {
   ...
   const ListComponent = this.props.contentWrapperComponent  || 'div'
    return (
      <ListComponent className={classString} {...rest}>
         ...
      </ListComponent>
    )
}
```

this means that to make antd work (or any other decoration of the component) we can do something like:

```
const ObserverWrapper = props => <Observer>{()=> <div {...props} />}</Observer>

<List contentWrapperComponent={ObserverWrapper} ... />


```

**Comment by abenhamdine** [comment]
see next version of Table : https://github.com/react-component/table/releases/tag/v7.0.0-alpha.16
