### ISSUE TITLE
The argument file.status of Upload onRemove is always 'removed'

### ISSUE THREAD

**Issue by vipcxj** [ant-design/ant-design#15192]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6zj7wn07k)

### Steps to reproduce
click the upload button, select a file, click ok, wait upload complete then delete the file and see the output of the console.

### What is expected?
error

### What is actually happening?
removed

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.8.3 |
| System | all |
| Browser | all |

---
Usually we clear the resource in the onRemove callback. for example request the server to delete the uploaded file (Which may be not exist because of upload error). So if `file.status` shows the last status, it will help us to decide what should do in the onRemove callback. On the other hand, only when `onRemove` return true, the status should become 'removed'.

**Comment by afc163** [comment]
Fixed in #18937

**Comment by dazjean** [comment]
Well, I just used the delete state in onremove
