### ISSUE TITLE
能否在TimePicker中 onChange的时候将当前操作项写入事件对象呢

### ISSUE THREAD

**Issue by hangpage** [ant-design/ant-design#15201]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ant-design/ant-design/issues/1408#issue-148052917
看到大家对这个交互有不同的理解，官方文档也提供了open用来控制是否关闭面板，我是想要自己来控制用户选择了时or分or秒的时候对面板进行关闭。

### What does the proposed API look like?
onChange回调中提供相关事件对象

**Comment by hangpage** [comment]
这个我想了下 感觉提供一个onItemClick事件对时分秒三个操作菜单进行监听比较好，这样我就可以获得我的点击项了，接下来的交互就可以按照自己想法搞了

**Comment by zombieJ** [comment]
这个对时分秒点击做不同操作的场景是什么？

**Comment by hangpage** [comment]
@zombieJ 您好， 就像上面链接中提到的不同人对TimePicker面板是否被关闭的理解是不一样的，我正好客户遇到要求点击完秒就要求自动关闭面板，所以希望可以提供这样更灵活一点的API

**Comment by zombieJ** [comment]
感觉这个需求不够普适性，应该不会特地加到 api 里。你这样取吧：https://codesandbox.io/s/5k9jjzkmpk

**Comment by hangpage** [comment]
@zombieJ 收到 谢谢您 我先按照这个方法搞吧
