### ISSUE TITLE
时间组件优化

### ISSUE THREAD

**Issue by songlizhao** [ant-design/ant-design#15208]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现有的TimePicker选择时分需要滚动鼠标，非常不方便。主要是因为组件提供的信息不够一目了然，建议增加一个新的时间选择组件。
样式如下：https://gw.alipayobjects.com/mdn/rms_4e9c4b/afts/img/A*nZ-ZS6WI7CUAAAAAAAAAAABjARQnAQ

### What does the proposed API look like?
和这个一样，只是展示不同。https://github.com/ant-design/ant-design/edit/master/components/time-picker/demo/hide-column.md

**Comment by afc163** [comment]
时间选择器是经过大量讨论和多次改版后才定型的，暂时不会再大改了。
