### ISSUE TITLE
Spin size not correct when set `fontSize`

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15206]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2o7l44j40y)

### Steps to reproduce
Open link will see Spin not center aligned.

### What is expected?
Center aligned.

### What is actually happening?
Not aligned.

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

---
It's caused by Spin less: https://github.com/ant-design/ant-design/blob/master/components/spin/style/index.less#L126
It should set as `1em` instead of `@spin-dot-size` directly.

**Comment by afc163** [comment]
Can it drop Spin in this situation?

https://codesandbox.io/s/r7z906rwqm

**Comment by zombieJ** [comment]
> Can it drop Spin in this situation?
> 
> https://codesandbox.io/s/r7z906rwqm

It's simple demo. You can see complex one: https://codesandbox.io/s/jnr931ylwy
