### ISSUE TITLE
email表单验证没有取消浏览器默认行为

### ISSUE THREAD

**Issue by huangyingjie** [ant-design/ant-design#1520]
`<Input {...emailProps} type="email" />`
我设置了一个email类型的表单验证，在onChange的时候可以正常触发验证；
但在form的onSubmit事件的时候，因为填写不合法，浏览器(chrome)会先调用其内置验证逻辑，结果表单验证和onSubmit事件都被截断了，没有触发。
但官网示例上也是这么写的，就没有阻断过，是有什么特殊的设置吗？

**Comment by huangyingjie** [comment]
antd官网的例子并没有直接注册submit事件，而是在button上注册了onClick。
手动禁用html5自带的表单验证可能有效。
http://stackoverflow.com/questions/3090369/disable-validation-of-html5-form-elements

**Comment by huangyingjie** [comment]
form添加novalidate属性可以解决问题。但antd没有添加novalidate属性的入口。
总结一下，使用了onSubmit，就不要指定input的type类型，默认为text即可。

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/14840038/ac5afd04-0c62-11e6-96d3-2dc696a5db3f.png)

其它属性，会直接传给 `input`。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/master/components/form/Form.jsx#L20

novalidate 可以直接传给 Form 。

**Comment by huangyingjie** [comment]
从React开发者工具上看Component结构，确实是传了。
但是从Elements审查元素入口来看，实际Form节点上并没有novalidate属性。

**Comment by afc163** [comment]
https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes

`noValidate`
