### ISSUE TITLE
The user can import Wave component

### ISSUE THREAD

**Issue by hileix** [ant-design/ant-design#15217]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The user can use Wave components, thus unified click animation.

### What does the proposed API look like?
```jsx
<Wave>
  <div>Click me!</div>
</Wave>
```

**Comment by afc163** [comment]
Sorry, we may not expose Wave which is not a independent UI component with solid entity. You can import it via `'antd/es/_util/wave'`. But don't use it in serious situation cause we may not change the path or refactor it in future.
