### ISSUE TITLE
Property to disable action item on Card

### ISSUE THREAD

**Issue by dnlfrst** [ant-design/ant-design#15216]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

#### Context
I use `Card`s to represent tasks (similar to Google Keep) which can be completed. The operations (i. e. `actions`) available for a task (i. e. `Card`) depend on their status of completion. Once the user completes a task, the `Card` should immediately reflect this fact by changing the available actions. For example, a completed task shall not be editable after it's completed.

#### Problem
Sticking to the example above, let's assume the editing operation is represented by an `<Icon type="edit" />` as `action` on the `Card`.
A user now completes said task and hence, it shall not be editable anymore. Currently, I see myself faced with two options to implement this behaviour:

 1. Remove the `Icon` from the actions such that it's not visible anymore.
 2. Use another component apart from `Icon` that iself can be disabled.

In turn, this poses the following problems:

 1. The change in visible actions is irritating to the user, espacially if there are multiple actions that get hidden on a completion of a task.
 2. The seems to be no other component apart from `Icon` that visually fits as `action` for a `Card` (in particular not the `Button`).

#### Question
 - Is there another way of solving the above descripted issue I was yet not able to come up with?
 - If not, would it be possible to allow `action`s to be disabled ([similar to how tabs inside a `Card` can be disabled](https://github.com/ant-design/ant-design/issues/11212))?

### What does the proposed API look like?
The above issue could be solved by allowing `action`s of a `Card` to be disabled. For that, similar to the tabs of a `Card`, the API for `action`s could be changed to:
```javascript
const actions = [{
	action: <Icon type="edit" />,
	disabled: this.completed
}, {
	action: <Icon type="delete" />
}];
```
introducing a new type in TS:
```typescript
export interface ActionType {
	action: React.ReactNode;
	disabled?: boolean;
}
```
Visually, disabled actions can use the predefined color for disabled components (`fade(#000, 25%)`) and  `cursor: not-allowed` allowing the user to easily depict disabled actions instead of hiding them while drastically changing the layout of `action`s in a `Card`.
A possible implementation would look as follows:  ![card](https://user-images.githubusercontent.com/13868083/53830325-7acc0480-3f82-11e9-8b89-181680e35b83.PNG)

**Comment by zombieJ** [comment]
`actions` is only for the position accept as footer nodes. User can use not only the Icon component. Add `disabled` prop in `actions` may not be the better api design. You can wrap the Icon as your requirement:
https://codesandbox.io/s/rrk0jpjo
