### ISSUE TITLE
Calendar component `Option is not defined`

### ISSUE THREAD

**Issue by MarshallChen** [ant-design/ant-design#1521]
`Option`的变量丢了

https://github.com/ant-design/ant-design/blob/develop-1.0.0/components/calendar/Header.jsx#L37

**Comment by MarshallChen** [comment]
#1522

**Comment by benjycui** [comment]
这个文件一开始就没有引入 `Option` https://github.com/ant-design/ant-design/commit/d950c63c8050bafcb33fabd6b05044a65739c461 ，居然到现在才发现 。。。

然后麻烦能提供重现步骤么，我无法重现，不可思议。。

**Comment by afc163** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLOptionElement/Option

window.Option 是浏览器自身存在的方法，所以一直没有重现。真是够奇葩的问题...

**Comment by benjycui** [comment]
Select 里并没有要求 Option 一定要是 `Select.Option` https://github.com/react-component/select/blob/master/src/FilterMixin.js#L24

。。。连环 bug

**Comment by MarshallChen** [comment]
是服务器端渲染报出的错，浏览器端渲染是没问题，所以也不难解释文档里的并没报错
