### ISSUE TITLE
Steps with progressDot overflows on mobile resolutions

### ISSUE THREAD

**Issue by gabrieldutra** [ant-design/ant-design#15215]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v1088po950)

### Steps to reproduce
1. Resize the sandbox to a narrower resolution (to approach mobile resolutions);
2. Verify that the progressDot will overflow while the regular one will turn into a vertical direction.

![antd-steps](https://user-images.githubusercontent.com/3356951/53816537-78e25100-3f42-11e9-94b1-71ce54ca1244.gif)

### What is expected?
The progressDot Steps should turn into a vertical direction as well as the regular one.

### What is actually happening?
The progressDot Steps overflows

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.3 |
| System | ElementaryOS/Linux |
| Browser | Chrome 71 |

**Comment by ztplz** [comment]
You can set `overflow:  "hidden"` in style of `Modal`.  In order not to change the existing behavior, I also recommend that you do this.  I updated your [demo](https://codesandbox.io/s/6xy666xn9z).

**Comment by gabrieldutra** [comment]
> You can set `overflow: "hidden"` in style of `Modal`. In order not to change the existing behavior, I also recommend that you do this. I updated your [demo](https://codesandbox.io/s/6xy666xn9z).

Thanks @ztplz, but I'm afraid the `overflow: 'hidden'` will only fix half of the issue :confused:. The overflow will still exist, even thought it's hidden. Also, if you check your demo and resize the sandbox to be narrower you'll see that it's visual buggy (the Steps component gets cut).

What I did to workaround this was hiding the Steps for small resolutions.

**Comment by saostad** [comment]
I confirm problem still exist in v4.0.4, if I use it without progressDot, it is responsive and no need any extra CSS. I think it will be better if it has same behavior as without progressDot
```
<Steps
      progressDot={true}
      current={current}
      onChange={onChange}
    >
      {sections.map(el => (
        <Step title={el} key={el} />
      ))}
    </Steps>
```

**Comment by ademidun** [comment]
Any updated on this please? @afc163 

This is still an issue in `~4.6.5`. My current workaround is removing `progressDot` attribute in `<Steps>` (thanks @saostad for the suggestion!)

![Screenshot from 2020-10-27 03-50-32](https://user-images.githubusercontent.com/9806858/97272156-e160fe80-1807-11eb-8d7a-8faac7bf038b.png)
![Screenshot from 2020-10-27 03-50-12](https://user-images.githubusercontent.com/9806858/97272158-e1f99500-1807-11eb-87a1-ec98b892f850.png)
![Screenshot from 2020-10-27 03-49-48](https://user-images.githubusercontent.com/9806858/97272159-e1f99500-1807-11eb-977e-f18d3a0e62c3.png)
![Screenshot from 2020-10-27 03-49-36](https://user-images.githubusercontent.com/9806858/97272160-e1f99500-1807-11eb-8ca7-9aaa095612f3.png)

**Comment by afc163** [comment]
Fixed in antd@4.x: https://codesandbox.io/s/v1088po950?file=/index.html

<img width="432" alt="图片" src="https://user-images.githubusercontent.com/507615/102681916-4a5d6500-4200-11eb-873e-40e015f7717a.png">
