### ISSUE TITLE
inputNumber parser 返回值类型错误

### ISSUE THREAD

**Issue by Grewer** [ant-design/ant-design#15226]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/input-number/index.tsx#L24](https://github.com/ant-design/ant-design/blob/master/components/input-number/index.tsx#L24)

### Steps to reproduce
```parser?: (displayValue: string | undefined) => number;```
现在的类型是这个,但是由于返回值必须是一个 number 类型  
如果我想输入 `.` 小数点,则需要返回为 string 类型,如果我转为 number ,`1.` 就会被转为 `1` ,就造成了小数点输入无效的问题

### What is expected?
改成如此即可```parser?: (displayValue: string | undefined) =>  string;```

### What is actually happening?
能正常输入小数点

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.7.0 |
| System | mac os |
| Browser | chrome |

**Comment by morenyang** [comment]
https://codesandbox.io/s/01y92n64z0

应该是没有绑定 `value` 吧...

**Comment by afc163** [comment]
@morenyang wrong issue.

**Comment by morenyang** [comment]
> @morenyang wrong issue.

点错页面了...

**Comment by jiangyh1024** [comment]
@Grewer
这个问题解决了吗？ 或者有什么 解决方案 求助 我也遇到了 不能输入 小数点

**Comment by jiangyh1024** [comment]
@afc163 
anybody can help me

**Comment by Grewer** [comment]
@jiangyh1024 这个还没解决吗

我当时就这样解决的
```
value as unknown as number
```

**Comment by Grewer** [comment]
我看了下 type 现在是这样的 `  parser?: (displayValue: string | undefined) => number | string;` 应该是没什么问题的

**Comment by jiangyh1024** [comment]
@Grewer 
什么鬼 ？ 能不能截个代码图  
![image](https://user-images.githubusercontent.com/34930870/69614938-02a4f200-106f-11ea-8151-cc794be14063.png)

parser 要如何写 才能输入小数点哦

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/69615001-1cded000-106f-11ea-912d-87d336a47e8e.png)


意思是 return undefined？

**Comment by Grewer** [comment]
@jiangyh1024 
不知道你报的什么错误,我之前是这样的
![image](https://user-images.githubusercontent.com/21995246/69615595-1c930480-1070-11ea-8a2d-e7b751abf246.png)

**Comment by jiangyh1024** [comment]
@Grewer 
谢谢 我去试试

**Comment by jiangyh1024** [comment]
@Grewer 
as unknown as number  是个什么语法哦？？？ 不会报错么

**Comment by Grewer** [comment]
@jiangyh1024 ts 的断言

**Comment by jiangyh1024** [comment]
@Grewer 
我的意思是 还可以 2个 as 连着写？

你这样写了以后 就可以输入小数点了吗？

**Comment by yoyo837** [comment]
试一试来得更快。

**Comment by jiangyh1024** [comment]
试了 不行

**Comment by Grewer** [comment]
@jiangyh1024  你为什么一直不把自己的报错发出来 我的方法当然是解决我当时的问题的,而这个问题应该是被修复了

**Comment by jiangyh1024** [comment]
不是报错  是无法输入小数点

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/69713425-79112500-113f-11ea-8d06-37a9837f936a.png)

format 显示的 百分比  填入的时候 无法在 %之前输入小数点

**Comment by jiangyh1024** [comment]
![image](https://user-images.githubusercontent.com/34930870/69713567-ba093980-113f-11ea-8a11-842013c425b3.png)
![image](https://user-images.githubusercontent.com/34930870/69713575-bd9cc080-113f-11ea-89c0-be98293e6851.png)

在2个数字之间 输入小数点是可以的

**Comment by Grewer** [comment]
@jiangyh1024 
```
+'51.%'.replace('%','')
```
结果是 51  数字, 你自己怎么保留小数点

**Comment by yoyo837** [comment]
这种截图无助于定位和修复问题，请提供可复现的在线demo。
