### ISSUE TITLE
table组件用rowSelection时报shiftKey undefined

### ISSUE THREAD

**Issue by MuKong95** [ant-design/ant-design#15229]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L526)

### Steps to reproduce
问一下，table组件使用rowSelection的onChange的时候会报错。我debug了一下，table组件里的handleSelect函数里，这里有用到一个nativeEvent.shiftKey，但nativeEvent是undefined的，不知道是什么原因

### What is expected?
问一下，table组件使用rowSelection的onChange的时候会报错。我debug了一下，table组件里的handleSelect函数里，这里有用到一个nativeEvent.shiftKey，但nativeEvent是undefined的，不知道是什么原因

### What is actually happening?
问一下，table组件使用rowSelection的onChange的时候会报错。我debug了一下，table组件里的handleSelect函数里，这里有用到一个nativeEvent.shiftKey，但nativeEvent是undefined的，不知道是什么原因
![wechatimg8889](https://user-images.githubusercontent.com/22429476/53863127-54f73c00-4024-11e9-8c09-d058df85b388.jpeg)

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.4 |
| System | 3.14.1 |
| Browser | chrome |

**Comment by devilsbibble** [comment]
@MuKong95 这个问题解决了吗？我们也遇到这个问题～～

**Comment by MuKong95** [comment]
没解决啊，我是改他内部代码了，不过不能更新，一更新就还原回去了

**Comment by Alberqing** [comment]
你好 ，这个问题解决了吗

**Comment by MuKong95** [comment]
> 你好 ，这个问题解决了吗
后来我好像是改他代码临时解决了，但不治本，一直在等他们更新修复
