### ISSUE TITLE
react-app-rewired  打包文件过大怎么解决

### ISSUE THREAD

**Issue by taojianghe** [ant-design/ant-design#15235]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://gitlab.adatafun.com/hzxs/hgh-guest-web](http://gitlab.adatafun.com/hzxs/hgh-guest-web)

### Steps to reproduce
执行npm run build 报错，搜索说是node打包过大，导致卡死

### What is expected?
期望打包成功

### What is actually happening?
打包失败

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.6.1 |
| System | win10 |
| Browser | 谷歌 |

**Comment by afc163** [comment]
这个不是 antd 问题。
