### ISSUE TITLE
Tabs组中 被激活的Tab页签的下划线在使用浏览器缩放时, 会显示错误

### ISSUE THREAD

**Issue by zzzmj** [ant-design/ant-design#15234]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
我一开始是跑本地项目发现了这个BUG
在官网即可重现.
1. 13.3寸的笔记本
2. 缩放比例110%或者125%的时候
3. 被选中tab标签的下划线没有被正确关闭
![](http://ww1.sinaimg.cn/large/006PpBLogy1g0t7gw77vzj310b0k775x.jpg)

### What is expected?
我期望被选中的Tab标签border-bottom能够被正确关闭
并知道是为什么导致的

### What is actually happening?
实际上他并不能正确关闭

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.3 |
| System | win10 |
| Browser | Chrome浏览器 版本 72.0.3626.121（正式版本） （64 位） |

---
我一开始是跑本地项目发现了这个BUG
我在缩放的我浏览器的时候, 发现被选中的tab标签的border不能正确的被关闭

**Comment by zombieJ** [comment]
缩放表现是和游览器相关，Chrome 缩放后像素计算精度偏差导致的：
<img width="580" alt="2019-03-06 6 23 45" src="https://user-images.githubusercontent.com/5378891/53874302-1f128180-403d-11e9-8343-e775336f4340.png">

另外，缩放尺寸因为不是用户常见行为。这边不会特殊处理。

**Comment by afc163** [comment]
```diff
.ant-tabs.ant-tabs-card .ant-tabs-card-bar .ant-tabs-tab-active {
-    padding-bottom: 1px;
+   padding-bottom: 1.2px;
    color: #1890ff;
    background: #fff;
    border-color: #e8e8e8;
}
```

试了下这样可以修。能修的而且成本不高没副作用的还是可以尽力搞搞。

**Comment by zzzmj** [comment]
> 缩放表现是和游览器相关，Chrome 缩放后像素计算精度偏差导致的：
> <img alt="2019-03-06 6 23 45" width="580" src="https://user-images.githubusercontent.com/5378891/53874302-1f128180-403d-11e9-8343-e775336f4340.png">
> 
> 另外，缩放尺寸因为不是用户常见行为。这边不会特殊处理。

呃呃呃, 其实我觉得对于小尺寸的电脑来说, 缩放还是挺常见的, 一般13寸的电脑用浏览器都需要缩放到125%或者150%

**Comment by zombieJ** [comment]
> 试了下这样可以修。能修的而且成本不高没副作用的还是可以尽力搞搞。

这样只是修了 Chrome，还有其他游览器。

Firefox （突出来 1 px）
<img width="310" alt="2019-03-06 8 56 16" src="https://user-images.githubusercontent.com/5378891/53882868-6e16e180-4052-11e9-8199-90db74225455.png">

Safari （没封头）
<img width="297" alt="2019-03-06 8 56 21" src="https://user-images.githubusercontent.com/5378891/53882877-75d68600-4052-11e9-9b1a-407aae4579b5.png">

我是不建议针对缩放做样式微调，容易给正常尺寸下埋坑。而且也不解决问题。

**Comment by afc163** [comment]
那找找更好的解决方案，缩放一定意义上也是可访问性问题。

当然，找不到合理方案就算了。

**Comment by afc163** [comment]
试了下确实没啥好办法，等 chrome 做渲染优化吧。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/15299 貌似解决了这个问题。
