### ISSUE TITLE
Attempted import error: 'Typography' is not exported from 'antd'.

### ISSUE THREAD

**Issue by rodrigofazenda** [ant-design/ant-design#15239]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4y8j1zk79)

### Steps to reproduce
Steps: create a new React project and try to import the Typography component from antd.

### What is expected?
It's expected to use the Typography component.

### What is actually happening?
On codesandbox.io it is working as expected, but when I try to import on my project, this gives the following error message:
Attempted import error: 'Typography' is not exported from 'antd'.

![screenshot_3](https://user-images.githubusercontent.com/12849476/53893030-29685780-400c-11e9-8099-33170cc6a222.png)

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | React 16.8.3 |
| System | Windows 10 |
| Browser | Chrome 70 |

---
I tried to search the typography on the antd folder on node_modules but could not find it.

**Comment by afc163** [comment]
Make sure your antd version >= 3.14.0.

Try to remove `node_modules` `yarn.lock` `package-lock.json` and reinstall agian.

**Comment by thangvynam** [comment]
> Make sure your antd version >= 3.14.0.
> 
> Try to remove `node_modules` `yarn.lock` `package-lock.json` and reinstall agian.

It works for me . Thanks u
