### ISSUE TITLE
Input.Search查询后台并重新渲染Table数据时，控制台输出警告信息

### ISSUE THREAD

**Issue by majinkai** [ant-design/ant-design#15243]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
<Input.Search onSearch={value => this.handleSearch(value)} placeholder="输入名称查询" />
<Table dataSource={list} loading={loading} rowKey="id">
     <Table.Column title="ID" dataIndex="id" align="center" sorter={(a, b) => a.id - b.id} defaultSortOrder="ascend" />
     ......
</Table>

### What is expected?
无警告信息

### What is actually happening?
index.js:1 Warning: When Input is focused, dynamic add or remove prefix / suffix will make it lose focus caused by dom structure change. Read more: https://ant.design/components/input/#FAQ

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.7.0 |
| System | osx |
| Browser | chrome 72.0.3626.121 |

**Comment by majinkai** [comment]
https://github.com/majinkai/ant-design-pro

**Comment by Yangzhedi** [comment]
![image](https://user-images.githubusercontent.com/11626454/53936533-052c7980-40e5-11e9-80eb-aae76e2ce54a.png)
@majinkai

**Comment by majinkai** [comment]
可是Input.Search是官方的组件，并且我也没有去动态改变

**Comment by majinkai** [comment]
https://8000-f6d06045-e035-4cf0-a4ed-fe1ad8bb41a3.ws-ap0.gitpod.io/test

**Comment by Yangzhedi** [comment]
gitpod有默认关闭时间，如果一会关上了，可能还是需要一个sandbox重现一下。。。

**Comment by agustingabiola** [comment]
The same is happening for `Input.Password` but I think the merged PR solves it for every input.
