### ISSUE TITLE
Collapse折叠面板 extra

### ISSUE THREAD

**Issue by 406224330** [ant-design/ant-design#15240]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/collapse-cn/](https://ant.design/components/collapse-cn/)

### Steps to reproduce
点击 extra内操作会触发折叠事件

### What is expected?
希望点击 extra不要触发折叠事件

### What is actually happening?
点击 extra ，折叠方法会被触发，体验很不好。

![image](https://user-images.githubusercontent.com/21120585/53926478-8b819500-40be-11e9-8f96-0993b668b0ab.png)

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | react  |
| System | WIN10 |
| Browser | GOOGLE |

**Comment by Yangzhedi** [comment]
https://codesandbox.io/s/616wkyw9nn
你可以先阻止一下冒泡

**Comment by 406224330** [comment]
> https://codesandbox.io/s/616wkyw9nn
> 你可以先阻止一下冒泡

谢谢，很有用，解决了图标点击问题
![image](https://user-images.githubusercontent.com/21120585/53928349-b8d14180-40c4-11e9-801a-1763475a85c4.png)
再请教下，menu怎么阻止冒泡？
Dropdown里的menu的onClick事件怎么获取event?
![image](https://user-images.githubusercontent.com/21120585/53928520-647a9180-40c5-11e9-9ba6-bf271735ec97.png)

**Comment by zombieJ** [comment]
`extra` 里不一定是交互性组件，也可能是说明性文字：
<img width="650" alt="2019-03-07 11 00 28" src="https://user-images.githubusercontent.com/5378891/53929309-45c9ca00-40c8-11e9-8006-8464f81a5ada.png">
所以组件层这边不会阻止事件传递，需要用户自己处理。

Dropdown 也是一样的，`stopPropagation` 即可：https://codesandbox.io/s/wz775z2y55

**Comment by afc163** [comment]
加个 FAQ 到底部好了，不然不断会有人问。

**Comment by 406224330** [comment]
> `extra` 里不一定是交互性组件，也可能是说明性文字：
> <img alt="2019-03-07 11 00 28" width="650" src="https://user-images.githubusercontent.com/5378891/53929309-45c9ca00-40c8-11e9-8006-8464f81a5ada.png">
> 所以组件层这边不会阻止事件传递，需要用户自己处理。
> 
> Dropdown 也是一样的，`stopPropagation` 即可：https://codesandbox.io/s/wz775z2y55

谢谢，外边包一层，这个思路很好。
