### ISSUE TITLE
关于Table排序

### ISSUE THREAD

**Issue by babizhu** [ant-design/ant-design#1524]
一：
对某列排序后，需要点击才能生效，是否能直接生效呢（当然如果有多列排序，可能存在一个按哪个列排序的问题）

二：
我不确定这是bug还是故意这么设计的
列标题的排序按钮，感觉是按一下，按照定义的函数排序，如果再点，就是恢复不排序的状态，而不是我直觉认为的**逆序**

确定了应该是故意这么设计的，只是觉得有些违反直接，提出来仅供参考吧
http://ant.design/components/table/的按年龄排序可看到这个状况

**Comment by afc163** [comment]
1. #1294 
2. 排序按钮有『上』『下』两个图标按钮，你点『上』就是正序，点『下』就是逆序。重复点同一个就是『排序』『不排序』之间切换。

**Comment by babizhu** [comment]
嗯，是的，我已经看出来了，只是觉得有些违反直觉，个人意见，仅供参考

**Comment by afc163** [comment]
感谢反馈。:smile:
