### ISSUE TITLE
Typography 使用editable时, 希望编辑前和编辑中, 组件的高度保持一致

### ISSUE THREAD

**Issue by VoliBearCat** [ant-design/ant-design#15248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
编辑前后, 组件的高度不一致, 容易在一些场景导致布局的闪动

### What does the proposed API look like?
编辑前后, 组件的高度一致

**Comment by afc163** [comment]
用 bug-report 模板重提。
