### ISSUE TITLE
Typography 使用editable时, 希望编辑前和编辑中, 组件的高度保持一致

### ISSUE THREAD

**Issue by VoliBearCat** [ant-design/ant-design#15249]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/typography-cn/#components-typography-demo-interactive](https://ant.design/components/typography-cn/#components-typography-demo-interactive)

### Steps to reproduce
1.点击编辑Paragraph
2.观察编辑前后, 组件高度

### What is expected?
编辑前后, 组件的高度一致

### What is actually happening?
编辑前后, 组件的高度不一致, 容易在一些场景导致布局的闪动

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.6.0 |
| System | macOS 10.14.2 |
| Browser | Chrom 72 |

**Comment by VoliBearCat** [comment]
https://codesandbox.io/s/km01znjz7v
提供一个解决方案的思路以供参考, 这种解决方式需要依赖 文本内容 去填充高度, 所以resize不太适用, 但是想了下这个组件在使用场景上, 使用resize: "none"感觉会更加合理一些
@zombieJ

**Comment by zombieJ** [comment]
用户输入了很多的时候，还是会希望可以拖高点看。可以让开发者来用样式设置这个值。组件内部还是开放给他们。

**Comment by afc163** [comment]
现在样式有点丑，编辑态至少要保持外层容器的样式，比如官方例子里的 p 的 margin。
