### ISSUE TITLE
select多选模式，希望可以增加最大选项限制，以及禁止用户直接输入

### ISSUE THREAD

**Issue by piscdong** [ant-design/ant-design#15244]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
应用场景就是多选希望有一个最大选项限制。
禁止用户直接输入是选项不多，让用户直接点选就行了，不要用户输入，用户看到光标，可能会误解可以自己增加自定义选项。如果是允许用户自己增加自定义选项，可以用tag模式

### What does the proposed API look like?
最大选项限制可以是maxSelected；
禁止用户直接输入可以是disableInput

**Comment by afc163** [comment]
- `maxSelected`: You can do it by control `value` of Select.

**Comment by piscdong** [comment]
> * `maxSelected`: You can do it by control `value` of Select.

试过了在onChange里根据value.length来return，然鹅并没有用

**Comment by afc163** [comment]
> 试过了在onChange里根据value.length来return，然鹅并没有用

给个重现：http://u.ant.design/codesandbox-repro

**Comment by morenyang** [comment]
https://codesandbox.io/s/01y92n64z0

应该是没有绑定 value 吧...

**Comment by piscdong** [comment]
> https://codesandbox.io/s/01y92n64z0
> 
> 应该是没有绑定 value 吧...

你这个是setState，我是直接return，不一样
看起来你这个方法是管用的，还是希望能简单点，通过api来直接控制
谢谢

**Comment by afc163** [comment]
@morenyang 是对的，这就是标准的 React 用法，没必要另开 API 了。

**Comment by piscdong** [comment]
> @morenyang 是对的，这就是标准的 React 用法，没必要另开 API 了。

实际试了一下，还是不行
我这边是用getFieldDecorator包装的控件，必须用setFieldsValue来设置控件的value，我实际测试的结果是，设置其他控件是没问题的，设置自身还是不行

**Comment by piscdong** [comment]
> @morenyang 是对的，这就是标准的 React 用法，没必要另开 API 了。

不要急着关啊，第二个需求还没说呢

**Comment by afc163** [comment]
getFieldDecorator 下可以用 getValueFromEvent 进行统一裁剪。

**Comment by piscdong** [comment]
> getFieldDecorator 下可以用 `getValueFromEvent` 进行统一裁剪。

具体要怎么用呢？
比如onChange={this.handleChange}
是不是getValueFromEvent: this.handleChange
我这边测下来，这样写的话，一个都选不上

**Comment by afc163** [comment]
https://codesandbox.io/s/4jl1619zow

用了 `getFieldDecorator` 就不用再用 `onChange` 这一套了，双向绑定了已经。

**Comment by piscdong** [comment]
> https://codesandbox.io/s/4jl1619zow
> 
> 用了 `getFieldDecorator` 就不用再用 `onChange` 和 `setFieldsValue/setState` 这一套了，双向绑定了已经。

谢谢，搞定了
第二个需求也麻烦关注一下

**Comment by afc163** [comment]
我们可以让 `showSeach` 对多选 Select 生效，默认为 `true`，为 `false` 时可以 focus，回退，但是不能输入。

**Comment by piscdong** [comment]
> 我们可以让 `showSeach` 对多选 Select 生效（目前不生效），默认为 `true`，为 `false` 时可以 focus，回退，但是不能输入。

这个好，希望可以早日支持

**Comment by DiamondYuan** [comment]
> showSearch

单选模式逻辑不变，多选模式为 false 的时候，input 能选择，能删除不能输入？

**Comment by Buhaiyang** [comment]
> > 我们可以让 `showSeach` 对多选 Select 生效（目前不生效），默认为 `true`，为 `false` 时可以 focus，回退，但是不能输入。
> 
> 这个好，希望可以早日支持

这个目前有解决吗

**Comment by edifangyi** [comment]
> > https://codesandbox.io/s/01y92n64z0
> > 应该是没有绑定value吧...
> 
> 你这个是setState，我是直接返回，不一样
> 看起来你这个方法是管用的，还是希望能简单点，通过api来直接控制
> 谢谢

我用    const [value, setSelectChange] = useState([]); 更新可以呢
但是 setState 不管用，state中的值确实不会再更新，但是 value={this.state.selectedTags} 没起作用

**Comment by Nikolay-Borzov-EPAM** [comment]
Even if it can be done by `antd` user it would be not convenient. It seems natural to be the `Select` prop to control max number of tags

**Comment by afc163** [comment]
>  禁止用户直接输入可以是disableInput

showSearch={false} 就可以了 https://codesandbox.io/s/duo-xuan-antd-4-21-6-forked-7n5pbg

**Comment by duanwei1273** [comment]
在onChange中判断value.length,超过限制了直接pop数组最后一个

**Comment by ostli** [comment]
<Form.Item
                    name="style"
                    noStyle={true}
                  >
                    <Select
                      mode="multiple"
                      allowClear
                      style={{ minWidth: '25%' }}
                      maxTagCount={3}
                      options={[
                        { label: '写实', value: '写实' },
                        { label: '二次元', value: '二次元' },
                        { label: '幻想', value: '幻想' },
                      ].map((item) => {
                        return {
                          ...item,
                          disabled: values.style?.length > 1 && !values.style.includes(item.value),
                        };
                      })}
                      onChange={(value: string[], b) => {
                        console.log(`==ab`, value, b);
                      }}
                      placeholder="风格"
                    />
                  </Form.Item>
