### ISSUE TITLE
步骤条组件的连接线在多步骤的初始状态下消失了

### ISSUE THREAD

**Issue by Kevin170113664** [ant-design/ant-design#1525]
我在使用步骤条组件时希望看到像这样带连接线，步骤太多时自动分行
##### 图1
![截图](http://imgsrc.baidu.com/forum/w%3D580/sign=552b89d333a85edffa8cfe2b795509d8/adc36110b912c8fc2ad4164efb039245d78821d3.jpg)

但是一开始是这样显示的：
##### 图2
![截图](http://imgsrc.baidu.com/forum/w%3D580/sign=fdeb6d8b9c504fc2a25fb00dd5dce7f0/6e7d15fa828ba61e7a1629ac4634970a314e5906.jpg)

当我点击Next按钮后，步骤条就如图1那样显示了

```javascript
//我在render里面是这样写的
  render() {
    return (<Steps size="default" current={this.state.currentStep}>
      {this.getSteps()}
    </Steps>)
  }
```
```javascript
//这里是上一步下一步按钮绑定的事件和单个步骤的生成代码
  next() {
    this.setState({currentStep: Math.min(this.state.currentStep + 1, this.props.steps.length - 1)});
  }

  previous() {
    this.setState({currentStep: Math.max(0, this.state.currentStep - 1)});
  }

  getSteps() {
    return this.props.steps.map((step, index)=> {
      return <Steps.Step key={index} title={step.name}/>
    });
  }
```
##### 下面是我的开发环境
- antd 0.12.12
- OSX 10.10.5
- Chrome Version 50.0.2661.86 (64-bit)

虽然对功能没有影响，但是看起来好怪呃>.<

**Comment by benjycui** [comment]
看起来是因为步骤太多，用 vertical 可好？http://ant.design/components/steps/#demo-vertical

**Comment by abbish** [comment]
是个变通的方法
