### ISSUE TITLE
分段进度条显示bug【应该是bug吧？】

### ISSUE THREAD

**Issue by piscdong** [ant-design/ant-design#15258]
![1551951956692](https://user-images.githubusercontent.com/4155976/53947773-63675580-4101-11e9-8855-98fd0d9aab53.jpg)

应该算是bug吧
如上图，分段进度条，在圆形和仪表盘上的圆角方向和直线上的不一样
这样会给人造成误解
比如直线上，很显然蓝色长，绿色短，都从左边为起点
圆形上实际是从12点为起点，但是因为圆角方向的问题，会误解为绿色长，蓝色短，7点为起点
仪表盘上实际是从左边为起点，但是因为圆角方向的问题，会误解为绿色长，蓝色短，中偏右为起点

**Comment by piscdong** [comment]
> Hello @piscdong, your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](http://new-issue.ant.design?repo=ant-design) to create an issue, thank you!
> 
> 你好 @piscdong，为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](http://new-issue.ant.design?repo=ant-design) 来创建 issue 以方便我们定位错误。谢谢配合！

你们的助手上不能上传图片，是要我用助手再发一次吗？

**Comment by imhele** [comment]
你可以试着先用小助手发文字，然后使用这里的编辑功能添加图片

**Comment by piscdong** [comment]
> 你可以试着先用小助手发文字，然后使用这里的编辑功能添加图片

谢谢提醒

**Comment by zombieJ** [comment]
不用了，我这边 reopen 了。

**Comment by piscdong** [comment]
> 不用了，我这边 reopen 了。

谢谢，但是label仍然是invalid，而且没有assignee
