### ISSUE TITLE
希望能添加DatePicker与Button的互动的API 

### ISSUE THREAD

**Issue by 434451580** [ant-design/ant-design#15255]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在项目中需要点击button出现日期选择弹框，目前可以通过open属性实现，不过无法添加点击空白，使open为fales，造成体验比较差

### What does the proposed API look like?
直接提供是否点击空白关闭弹框的api

**Comment by afc163** [comment]
Please listen to `onOpenChange` and change `open` in state.
