### ISSUE TITLE
message组件全局配置能否支持针对不同的类型做不同的配置

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#15269]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
场景：success需要2s消息，error可能需要4s才消失

### What does the proposed API look like?
message.config 支持个数组？或者额外加个属性

**Comment by afc163** [comment]
这个特性比较小众，建议封装二次方法来解决。
