### ISSUE TITLE
Modal.info / success / confirm 无法继承 ConfigProvider 中prefixCls的属性

### ISSUE THREAD

**Issue by soguagirl** [ant-design/ant-design#15260]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/93m9pv2mlo)

### Steps to reproduce
--

### What is expected?
--

### What is actually happening?
--

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.4 |
| System | Mac |
| Browser | Chrome |

**Comment by soguagirl** [comment]
message，也有这个情况

**Comment by zhongjie-chen** [comment]
```javascript
/* global Promise */
import * as React from 'react';
import Notification from 'rc-notification';
import Icon from '../icon';

let defaultDuration = 3;
let defaultTop: number;
let messageInstance: any;
let key = 1;
let prefixCls = 'ant-message'; // 这个自己写成常量了 没有去context里面拿
let transitionName = 'move-up';
let getContainer: () => HTMLElement;
let maxCount: number;
```

**Comment by zhongjie-chen** [comment]
这些都是脱离了provide存在，无法获取context。
官方文档没有写好 比如message的option可以设置。
```javascirpt
message.config({ prefixCls: 'yourPrefix-message' });
```

**Comment by beyondxgb** [comment]
这个怎么说呢，Icon，也有这个情况，目前看 Modal 问题比较大

**Comment by RubySakura** [comment]
同样遇到了Modal的这个问题，期待修复

**Comment by BurnhamZhang** [comment]
modal 没有config ，连统一配置的地方都没有

**Comment by yoyo837** [comment]
试试3.23.2

**Comment by yoyo837** [comment]
试试3.23.3

**Comment by jsers** [comment]
额，这个问题还有进展吗，3.23.3 貌似没有修复

**Comment by yoyo837** [comment]
估计得4.0再说了

**Comment by acsands13** [comment]
Still seeing issue in 3.25.1.

Temporary fix for `Modal.method()` is to apply the `prefixCls` directly:

```javascript
const showConfirm = () => {
  confirm({
      prefixCls: '{YOUR_PREFIX}-modal',
      title: 'This is a warning message',
      content: 'some messages...some messages...',
      okText: 'Yes',
      okType: 'danger',
      cancelText: 'Cancel',
      okButtonProps: {
        prefixCls: '{YOUR_PREFIX}-btn',
      },
      cancelButtonProps: {
        prefixCls: '{YOUR_PREFIX}-btn',
      },
      onOk() {
        console.log('OK');
      },
      onCancel() {
        console.log('Cancel');
      },
    });
};
```

```html
<Button onClick={showConfirm}>Confirm</Button>
```

Where `{YOUR_PREFIX}` should be replaced with the `prefixCls` set in your `ConfigProvider`.

**Comment by yoyo837** [comment]
fixed in #21275, pls try `4.0.0.rc-4`,  open a new issue for free if you have any new questions about that.

**Comment by yoyo837** [comment]
reopen by https://github.com/ant-design/ant-design/issues/21119#issuecomment-584288549

**Comment by hugobarragon** [comment]
@yoyo837 from notification only needs docs update, but modal using hooks still does'nt get the prefixCLS from ConfigProvider, so its not working :(

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/20949

**Comment by acsands13** [comment]
@afc163 this does not seemed fixed by #20949

`Modal.confirm()` still does not respect the `prefixCls` in `ConfigProvider`. 

[This line](https://github.com/ant-design/ant-design/pull/20949/files#diff-e791a37f365bc91348832a5a53e55aecR40) chooses the `prefixCls || 'ant-modal'`. Instead, `prefixCls` should come from `ConfigProvider` and append `-modal` automatically in order to solve this issue.

**Comment by afc163** [comment]
https://ant.design/components/modal/#FAQ

**Comment by albert-cai** [comment]
@afc163 it hasn't been fixed in 3.x version. Merge request was applied into antd4 version.

**Comment by hugobarragon** [comment]
@afc163 its not working, here you have the reproducion link confirm modal keeps "ant-modal"  
https://codesandbox.io/s/antd-modal-confirm-prefix-bug-5vno1

**Comment by DjVreditel** [comment]
Issue still reproducing, also prefix not updating automatically in the modal.
To fix prefix issue you need to use in global scope:

```JS
   useEffect(() => {
        Modal.config({ rootPrefixCls: prefix});
    }, [prefix]);
```

**Comment by kalagala233** [comment]
In `Modal.xxx` case ... To change the `ant` prefixCls to `ant-xxx`, you should do the following in a subcomponent:

```js
Modal.confirm({
    parentContext: this, // Ensures config-provider works in the current context
    prefixCls: 'ant-xxx-modal' // Don't forget to set this prop
});
````
