### ISSUE TITLE
将事件绑定到空白处，Modal组件不能关闭

### ISSUE THREAD

**Issue by lizhancheng** [ant-design/ant-design#15262]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/LaWzYj?&editable=true&editors=001](https://codepen.io/anon/pen/LaWzYj?&editable=true&editors=001)

### Steps to reproduce
点击空白处，然后点击关闭（不是esc），关闭不了Modal

### What is expected?
能够关闭Modal

### What is actually happening?
Modal还在，不能被关闭

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 18.3 |
| System | Windows |
| Browser | Chrome 72.0.3626.119 |

**Comment by zombieJ** [comment]
只因身在此山中：https://codepen.io/anon/pen/vPxega?editors=0010
