### ISSUE TITLE
Dynamic antd form intialValue set issue while use "valuePropName: 'defaultValue'".

### ISSUE THREAD

**Issue by jignesh-p-crest** [ant-design/ant-design#15263]
I am building dynamic form using antd form getfielddecorator from JSON and successfully created it. But When i am typing into into Input control, Whole component re-rendered on every time. So i have followed this issue: https://github.com/ant-design/ant-design/issues/13063 and fixed it. 

<FormItem className="ant col-lg-6 col-md-6 col-sm-12" label={'name'} >
		{getFieldDecorator('name', { trigger: 'onBlur',valuePropName: 'defaultValue', initialValue:data.name})
			(<Input type='text' autoComplete="off" onBlur={this.onChange}  />)
		}
</FormItem>

BUT I have faced another issue for bind Input value using initialValue. 

For example:

State of data:

1) In inital load

data: {
	name : ''
}

2) After fetched data from Ajax Call, 

data: {
	name: 'abcd'
}

After bind, On UI - it bind only blank value (''), rather than 'abcd'.

 Ant Version: "antd": "^3.13.2"

 So Can you please provide any help?

**Comment by leoaivy** [comment]
I also face the same issue with you. Did you solve it?

**Comment by ErtugrulBEKTIK** [comment]
Is there anyone that solve this problem?

**Comment by saintfirewater** [comment]
Same here. How to solve this?
