### ISSUE TITLE
weekpicker的周数显示BUG

### ISSUE THREAD

**Issue by taditang** [ant-design/ant-design#15273]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
跨年周的显示有问题，比如2018-12-31, 是算做2019年的第1周，weekpicker能取到第1周，但年份使用的是2018年，这样上一周显示2018年52周，这一周是2018年01周，下一周是2019年02周，很明显是错误的。

### What is expected?
应该是显示2019年01周。

### What is actually happening?
2018年01周。

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 无关 |
| System | 无关 |
| Browser | 无关 |

**Comment by taditang** [comment]
解决了，我自己的问题，研究了下moment的设置，之前用的format格式化YYYYWo用错了, 如果是周的话，正确年份获取是GGGG，而不是通常的YYYY

**Comment by afc163** [comment]
You can close this issue now.

**Comment by afc163** [comment]
@taditang
