### ISSUE TITLE
@ant-design/icons-react requires a peer of @ant-design/icons@~1.1.0 but misinstalled

### ISSUE THREAD

**Issue by AlbertAZ1992** [ant-design/ant-design#15277]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
```
yarn add antd@latest
yarn check
```

### What is expected?
yarn check with no error output

### What is actually happening?
```
yarn check v1.10.1
error "antd#@ant-design/icons-react#@ant-design/icons@~1.1.0" doesn't satisfy found match of "@ant-design/icons@1.2.1"
error Found 1 errors.
```

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.6.3 |
| System | MacOS 10.13.6 |
| Browser | chrome 71.0 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-icons/issues/51

**Comment by zombieJ** [comment]
`icons-react@1.1.4`released to fix this.
