### ISSUE TITLE
DatePicker日期面板和显示时间不一致

### ISSUE THREAD

**Issue by simonyouth** [ant-design/ant-design#15278]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/date-picker-cn/](https://ant-design.gitee.io/components/date-picker-cn/)

### Steps to reproduce
- DatePicker的value和defaultValue都为state传入，日期改变setState改变value
- 当用户点击了很久之前的日期，这种操作不被允许，但不能禁止，给出warn message，同时不会setState改变value
- 再次打开日期面板选择日期，时间会focus在上次选择的日期，和value不一致

### What is expected?
面板日期和显示一致

### What is actually happening?
不一致

| Environment | Info |
|---|---|
| antd | 3.8.4 |
| React | 16.4.1 |
| System | window 10专业版 |
| Browser | chorme Version 72.0.3626.119 (Official Build) (64-bit) |

**Comment by afc163** [comment]
关闭后应该清空掉面板里的 state。

@zombieJ

**Comment by simonyouth** [comment]
> 空掉面板里的 state。
面版没有state啊，传的是value，清除了还怎么显示呢

**Comment by afc163** [comment]
@simonyouth 我是在和 @zombieJ 讨论可选的 fix 方案。

**Comment by simonyouth** [comment]
不能让面板的state和传入的value一致吗
