### ISSUE TITLE
The scrollbar will squeeze the width of the Drawer

### ISSUE THREAD

**Issue by Kunoky** [ant-design/ant-design#15270]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.a.com](http://www.a.com)

### Steps to reproduce
*

### What is expected?
*

### What is actually happening?
*

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7 |
| System | win10 |
| Browser | chrom |

![image](https://user-images.githubusercontent.com/26639880/54003929-bf2bf000-418e-11e9-91f4-6490396164c9.png)
![image](https://user-images.githubusercontent.com/26639880/54003935-c226e080-418e-11e9-9f78-5297ca2728b9.png)

**Comment by afc163** [comment]
It is browser behavior, there is nothing we can do.

**Comment by Kunoky** [comment]
But I set the width to 360. When the scroll bar appears, the width becomes 344
