### ISSUE TITLE
【建议】新组件 - 照片墙

### ISSUE THREAD

**Issue by piscdong** [ant-design/ant-design#15280]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
方便展示多个图片时
用小方块展示图片，点击后放大展示，放大展示时可以左右切换
现在好像只能自己组装现有组件来模拟
Upload有一个照片墙，但是带上传和删除，而且预览图片的时候不能左右切换，要是能设置去掉上传和删除、增加预览时左右切换也不错

### What does the proposed API look like?
`<PicturesWall />`

**Comment by afc163** [comment]
trace #13719
