### ISSUE TITLE
Optizime code according to codebeat

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#15288]
https://codebeat.co/projects/github-com-ant-design-ant-design-master/quick_wins

<img width="885" alt="image" src="https://user-images.githubusercontent.com/507615/54020015-b86d9f00-41c7-11e9-82a0-f073393c9f04.png">

**Comment by saxenanihal95** [comment]
I am interested to work on it

**Comment by VariableVasasMT** [comment]
is this one taken?

**Comment by saxenanihal95** [comment]
yes i am working on it
