### ISSUE TITLE
Layout tagName bug

### ISSUE THREAD

**Issue by zzy1661** [ant-design/ant-design#15284]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/zzy1661/antd-bugs](https://github.com/zzy1661/antd-bugs)

### Steps to reproduce
npm install;
npm start;
in App.tsx,ts has an error report:"Property 'tagName' is missing in type '{ children: never[]; }'"
在 App.tsx中
```
class App extends Component {
  render() {
    return (
      <div className="App">
        <Layout>
        </Layout>
      </div>
    );
  }
}
```
ts 回报如下错误
Type '{ children: never[]; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<BasicProps, any, any>> & Readonly<BasicP...'.
  Type '{ children: never[]; }' is not assignable to type 'Readonly<BasicProps>'.
    Property 'tagName' is missing in type '{ children: never[]; }'.
经检查，layout.d.ts中，tagName为必选参数
```
export interface BasicProps extends React.HTMLAttributes<HTMLDivElement> {
    prefixCls?: string;
    hasSider?: boolean;
    tagName: 'header' | 'footer' | 'main' | 'section';
}
```

### What is expected?
set tagName optional
将tagName设为可选参数

### What is actually happening?
u must set tagName, which is not reasonable
因tagName为必选，导致ts报错，然而实际应用中，tagName的选项并不能满足业务需求

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.4 |
| System | windows |
| Browser | chrome 72.0.3626.119 |

---
It is a new bug in version 3.14.1
该bug是3.14新出现的

**Comment by zy410419243** [comment]
https://github.com/ant-design/ant-design/pull/15181

**Comment by guoerwei** [comment]
> #15181
> 
> 已经有修了，这周末就更了

额，发现3.16.1里直接移除了tagName的声明？不是应该改为选填的吗？
