### ISSUE TITLE
We should have the option to put an icon filled in the button component

### ISSUE THREAD

**Issue by marlomgirardi** [ant-design/ant-design#15294]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If we want to have a toggle for a favorite button we want to have an outlined to not favorite and filled to favorited items. Nowadays we have put an Icon component as children of a button. Why not have the option in the button?

### What does the proposed API look like?
```
// Option 1
<Button icon={{ type: "star", theme: "filled" }} />
<Button icon={{ type: "star", theme: "outlined" }} />
<Button icon="star" />

// Option 2
<Button icon="star-o" /> // detect that we put "-o" at the end and set theme to outlined
// or to mantain the compatibility "-f" for filled
<Button icon="star-f" />

// https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx#L238
```

**Comment by afc163** [comment]
```jsx
<Button icon={<Icon type="xx" theme="xx" />} />
```

I prefered this way.

**Comment by ztplz** [comment]
Relate to https://github.com/ant-design/ant-design/issues/12011. 
In order to reduce `budle` size, it would like be this。
![image](https://user-images.githubusercontent.com/17755202/54064218-58b9d700-424d-11e9-8f05-db4585191ae0.png)
