### ISSUE TITLE
Config antd with webpack and babel

### ISSUE THREAD

**Issue by Kadiem** [ant-design/ant-design#15295]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

Here is the issue I receive in the browser:

`ERROR in ./KQShopping/frontend/src/App.js
Module not found: Error: Can't resolve './index.css' in 'C:\Users\Kadiem\Desktop\KQShopping\KQShopping\frontend\src'
 @ ./KQShopping/frontend/src/App.js 25:0-21
 @ ./KQShopping/frontend/src/index.js

ERROR in ./node_modules/antd/dist/antd.css 15:5
Module parse failed: Unexpected token (15:5)
You may need an appropriate loader to handle this file type.
| /* stylelint-disable at-rule-no-unknown */
| html,
> body {
|   width: 100%;
|   height: 100%;
 @ ./KQShopping/frontend/src/App.js 24:0-28
 @ ./KQShopping/frontend/src/index.js
`

Here is App.js

`import React from "react";
import ReactDOM from "react-dom";
import { DatePicker, message } from "antd";
import "antd/dist/antd.css";
import "./index.css";

class App extends React.Component {
    state = {
        date: null,
    };

    handleChange = date => {
        message.info(`Selected Date: ${date ? date.format("YYYY-MM-DD") : "None"}`);
        this.setState({ date });
    };

    render() {
        const { date } = this.state;
        return (
            <div style={{ width: 400, margin: "100px auto" }}>
                <DatePicker onChange={this.handleChange} />
                <div style={{ marginTop: 20 }}>
                    Selected Date: {date ? date.format("YYYY-MM-DD") : "None"}
                </div>
            </div>
        );
    }
}

ReactDOM.render(<App />, document.getElementById("app"));`

.babelrc:
`{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "plugins": ["transform-class-properties", ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "true" }]]
}`

webpack.config.js:

`const path = require('path');
const fs  = require('fs');

const lessToJs = require('less-vars-to-js');
const themeVariables = lessToJs(fs.readFileSync(path.join(__dirname, './ant-theme-vars.less'), 'utf8'));

module.exports = {
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: {
                    loader: "babel-loader"
                }
            },
            {
                test: /\.less$/,
                use: [
                    {loader: "style-loader"},
                    {loader: "css-loader"},
                    {loader: "less-loader",
                        options: {
                            modifyVars: themeVariables
                        }
                    }
                ]
            }
        ]
    }
};`

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by YajJackson** [comment]
Running into the same issue.
