### ISSUE TITLE
3.15.0版本Typescript报错，无法编译。（已解决）

### ISSUE THREAD

**Issue by DougFlands** [ant-design/ant-design#15304]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/flands/Bug-commit](https://gitee.com/flands/Bug-commit)

### Steps to reproduce
打开项目，yarn后npm start，控制台有报错信息

### What is expected?
能正常运行

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.6.3 |
| System | WIN10 |
| Browser | Chrome 72.0 |

**Comment by zy410419243** [comment]
试试 npm

**Comment by DougFlands** [comment]
按楼上说的，解决了。感谢，可以关了。
