### ISSUE TITLE
vertical button group(垂直按钮组)

### ISSUE THREAD

**Issue by harry0071** [ant-design/ant-design#15309]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
vertical button group like bootstrap （可否像bootstrap的按钮组一样，有垂直方向的按钮组）
![捕获1.JPG](https://i.loli.net/2019/03/10/5c84ff61c32a4.jpg)

### What does the proposed API look like?
Reference react-bootstrap（参考react-bootstrap里的样子）：https://react-bootstrap.github.io/components/button-group/#vertical-variation

**Comment by DiamondYuan** [comment]
https://ant.design/components/menu-cn/

**Comment by afc163** [comment]
这个 UI 蛮奇怪的，暂无计划。
