### ISSUE TITLE
getMentions doesn't work when using multiple prefixes in 'Mention' component

### ISSUE THREAD

**Issue by mamsoudi** [ant-design/ant-design#15306]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5pl060jm4)

### Steps to reproduce
1. Type "#something" in the input
2. Type "@something" in the input
3. Use "getMentions" method to get mentions array list
4. It only contains the one (or the ones) with '@'

### What is expected?
When using multiple prefixes (e.g @, #, _), getMentions is expected to return all values coming after these characters.

### What is actually happening?
getMentions only returns values which begin with '@'.

| Environment | Info |
|---|---|
| antd | 3.10.2 |
| React | 16.4.2 |
| System | Mac |
| Browser | Chrome 72 |

---
It's useful to mention that onSelect works properly but since it doesn't provide the `trigger` argument, it's not possible to distinguish between `Tags (mentioned with #)` or `Users (mentioned with @)`.
What I basically wanted to achieve here was to be able to use # for mentioning user roles and @ for mentioning users directly.

**Comment by afc163** [comment]
It works in latest version of antd. Please check it and let me know if it still breaks.

**Comment by N00nDay** [comment]
still not working in antd 4.5.2

**Comment by j6k4m8** [comment]
I'd also like to +1 this — there doesn't seem to be a way to support #\hashtags and @\users in the same `<Mention />` right now?
