### ISSUE TITLE
Monthpicker:The year cannot be switched in the function of month selection

### ISSUE THREAD

**Issue by cassielpang** [ant-design/ant-design#15300]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
1.Looking at the last case, the function is to select a period of time in monthly units;
2.Click on the year switch in the panel, and then the panel returns to the month display, but the year at the top remains unchanged.
3.The same will happen in the function of choosing a single month.

### What is expected?
It is hoped that the year can be switched normally in the function of the selected month.

### What is actually happening?
The year cannot be switched in the function of month selection

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.0.0 |
| System | Windows 10 |
| Browser | Chrome   72.0.3626.121 |

**Comment by lucasdu4rte** [comment]
I have the same problem, in my case the month has a default value and is selected, the month X of last year, but shows how the month of the current year selected.

![Captura de Tela 2019-05-02 às 09 34 08](https://user-images.githubusercontent.com/22087517/57075592-8f482700-6cbd-11e9-912e-8975db3bb631.png)

![Captura de Tela 2019-05-02 às 09 34 21](https://user-images.githubusercontent.com/22087517/57075591-8eaf9080-6cbd-11e9-8c44-ce056cdae632.png)

![Captura de Tela 2019-05-02 às 09 34 25](https://user-images.githubusercontent.com/22087517/57075590-8eaf9080-6cbd-11e9-8e66-eac8e7076d57.png)

**Comment by zombieJ** [comment]
@lucasdu4rte , I think it may not the same issue as your met. This issue seems fixed in latest one.
Could you help to create a new issue with reproduce for your question?
