### ISSUE TITLE
Choosing a different empty image 

### ISSUE THREAD

**Issue by inian** [ant-design/ant-design#15307]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Right now the default empty image (https://github.com/ant-design/ant-design/blob/master/components/empty/empty.svg) is different from the default empty image which appears if a list, transfer and other components are empty (https://github.com/ant-design/ant-design/blob/master/components/config-provider/empty.svg)

I would like to use the second image with the Empty component. Is there an easier way of using the second image without downloading the image from the url and pointing towards it? 

Also, is there a rational behind using two different images? I think it would be more consistent to use the same image for both the cases. 

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | all |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
> I would like to use the second image with the Empty component. Is there an easier way of using the second image without downloading the image from the url and pointing towards it?

What is your proposal? What is the expected API you need?

> Also, is there a rational behind using two different images? I think it would be more consistent to use the same image for both the cases.

It is by designed. You can try https://ant.design/components/empty/#components-empty-demo-config-provider to override it globally.

**Comment by inian** [comment]
Since https://github.com/ant-design/ant-design/blob/master/components/config-provider/empty.svg is already packaged within antd is there a way to expose it? For example, 

`const EmptyImage = require("antd/empty")` // which returns ./node_modules/antd/lib/config-provider/empty.svg

`<Empty image={EmptyImage} />` // image attribute can be modified to take in a file on the local system. Most often I would want to take in a local file, instead of making request to an external URL.

OR

We can add https://github.com/ant-design/ant-design/blob/master/components/config-provider/empty.svg as an Icon? and then we can modify the api for Empty to take in a component like this
`<Empty image={<Icon type="empty-icon" />} />`

**Comment by DiamondYuan** [comment]
https://github.com/ant-design/ant-design/pull/15444

**Comment by inian** [comment]
Great, this addresses my use case of keeping the empty svg consistent across the different places where it is used.
