### ISSUE TITLE
Get onClick on select dropdown "Add Item"

### ISSUE THREAD

**Issue by zanisis** [ant-design/ant-design#15318]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My problem i select data but my api has been limit / give data per_page so i want load more data for selectable. so i need onClick or orChange when user click add item for get data more.

### What does the proposed API look like?
https://codesandbox.io/s/lll7131onq

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13448#issuecomment-449324251
