### ISSUE TITLE
依赖组件出现了多版本共存问题

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#15312]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pwlll4777m)

### Steps to reproduce
安装依赖后查看依赖锁定文件，`rc-tree` 和 `immutable` 出现了多版本共存的现象，会间接造成打包尺寸增大！

### What is expected?
不出现组件多版本共存

### What is actually happening?
出现组件多版本共存

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | React 16 |
| System | WIN10 |
| Browser | Chrome 72 |

![企业微信截图_20190311090757](https://user-images.githubusercontent.com/1730277/54094746-17a4fc80-43de-11e9-8f0c-e2ae3cdd0ad5.png)
![企业微信截图_20190311090733](https://user-images.githubusercontent.com/1730277/54094747-196ec000-43de-11e9-8d20-b1a9c8b96c90.png)

**Comment by afc163** [comment]
rc-tree

- https://github.com/react-component/tree-select/blob/4edf4367f7441e31d51ea3643a39b5386835213d/package.json#L58
- https://github.com/ant-design/ant-design/blob/master/package.json#L83

@zombieJ

**Comment by nuintun** [comment]
@afc163 又追了下，很多组件出现了重复引用，因为机制问题很难杜绝，不过还是希望可以尽量避免，
自己的库进行依赖同步，第三方库能尽量同步 

`rc-animate` `immutable`

**Comment by afc163** [comment]
keep it alive
