### ISSUE TITLE
iceworks materilas for ant-design ecosystem

### ISSUE THREAD

**Issue by topwood** [ant-design/ant-design#15316]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
we can use this materilas source for iceworks(https://ice.alibaba-inc.com/ice/docs/materials/devtools)

### What does the proposed API look like?
https://ice.alibaba-inc.com/ice/docs/materials/devtools

**Comment by afc163** [comment]
Maybe you should ask in https://github.com/alibaba/ice/issues
