### ISSUE TITLE
empty基本demo在ie系列下只显示部分图片

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#15314]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/empty-cn/#components-empty-demo-basic](https://ant.design/components/empty-cn/#components-empty-demo-basic)

### Steps to reproduce
empty组件 基本demo

### What is expected?
图片完整显示

### What is actually happening?
图片在ie下不缩放，导致只显示左上角部分
![image](https://user-images.githubusercontent.com/22299421/54098247-bdf8fe00-43ee-11e9-822d-9966ebfd4baf.png)

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react16 |
| System | win10 |
| Browser | ie11 |

**Comment by GuentherK** [comment]
The fix for this is very easy just use viewBox="0 0 184 152" instead of width="184" height="152" in /lib/empty/empty.svg
