### ISSUE TITLE
Replace Moment.js in Ant Design (Antd) with Day.js to reduce bundle size

### ISSUE THREAD

**Issue by xxyuk** [ant-design/ant-design#15311]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There are many discussion about replacing large size moment.js .

I just notice an article in Day.js ,  [Replace Moment.js in Ant Design (Antd) with Day.js](https://github.com/iamkun/dayjs/issues/529)  detailing  how to replace Moment.js with Day.js in 3 simple steps. Bundle size reduced from 65kb -> 4.19 kb.

It works good with me. May be we could add it to our docs?

|Name |Size|Size gzip|  
|------|---|---|
|Moment.js|231 kb |65.55 kb|
|Day.js|11.11 kb |4.19 kb|

<img width="283" alt="moment dayjs" src="https://user-images.githubusercontent.com/17680888/54087182-73926580-438b-11e9-9899-cd68849f9f8d.png">

<img width="295" alt="moment dayjs 2kb" src="https://user-images.githubusercontent.com/17680888/54087181-72613880-438b-11e9-878a-a01ff0fdf7bf.png">

### What does the proposed API look like?
No API change.

**Comment by yutingzhao1991** [comment]
Looks good, but although the API hasn't changed, breakchange may still occur. https://ant.design/components/date-picker/#Localization

Set moment locale will not work anymore.

**Comment by DiamondYuan** [comment]
I think antd 4.0 should consider this issue.

**Comment by afc163** [comment]
It will still break code in projects cause we expose moment object.

https://github.com/ant-design/ant-design/issues/10437#issuecomment-433612522

---

业务代码中还是会用到 moment，依然是一个 breaking change，即使未来的 4.0 我们也会尽量减小升级对用户的影响。

**Comment by sam-dingkang** [comment]
> It will still break code in projects cause we expose moment object.
> 
> [#10437 (comment)](https://github.com/ant-design/ant-design/issues/10437#issuecomment-433612522)
> 
> 业务代码中还是会用到 moment，依然是一个 breaking change，即使未来的 4.0 我们也会尽量减小升级对用户的影响。

很赞同尽量减小升级对用户的影响，moment 体积大可以抽出来减少打包体积，而且如果用户想要从antd切换day.js 可以自行按它的issue来完成。day.js是一个很好的库，用户可以在新项目使用它来。

**Comment by xxyuk** [comment]
> It will still break code in projects cause we expose moment object.
> 
> [#10437 (comment)](https://github.com/ant-design/ant-design/issues/10437#issuecomment-433612522)
> 
> 业务代码中还是会用到 moment，依然是一个 breaking change，即使未来的 4.0 我们也会尽量减小升级对用户的影响。

The exposed moment object react the same as Day.js, right?

With Webpack alias, even if our user use `import moment from 'moment'`, it will still represents as `import dayjs from 'dayjs'` and make no change to the user.

**Comment by afc163** [comment]
Developers may use a `moment.xxx` in their codes that dayjs cannot support without specified plugins.

**Comment by xxyuk** [comment]
Oh I see, but Day.js supports `.fromNow` through `relativeTime` plugin. That's how Day.js designed, to add methods with plugin.

And what is your main concern? Developer forget to import right plugin or it's hard to move to Day.js from all in one pack moment?

**Comment by afc163** [comment]
It is all for the compatibility, we should avoid breaking changes for the best.

**Comment by sam-dingkang** [comment]
> Oh I see, but Day.js supports `.fromNow` through `relativeTime` plugin. That's how Day.js designed, to add methods with plugin.
> 
> And what is your main concern? Developer forget to import right plugin or it's hard to move to Day.js from all in one pack moment?


The number of users of Antd is very large, it should avoid breaking changes, if you want to replace the moment, you should use day.js in your own project.

**Comment by xxyuk** [comment]
OK. One more question. 

Moment.js is mutable which is not a good practice. While Day.js is designed to be immutable. However, in order to replace moment in antd, Day.js has to introduce a plugin called `BadMutable` to make antd code work, but that would make Day.js mutable as well. This is a little hack I think. 

According to Day.js's author: 

> It would be better if Antd could make a little refactor of the way using moment.js.

> Treat moment object as immutable, and call clone each time before changing it's value like moment().clone().xxx.

> In this way, there's no need using BadMutable plugin anymore. And Day.js is immutable all the time.

Is this a considerable refactor? It make the code of antd more clear with no breaking change at all.

**Comment by sam-dingkang** [comment]
> OK. One more question.
> 
> Moment.js is mutable which is not a good practice. While Day.js is designed to be immutable. However, in order to replace moment in antd, Day.js has to introduce a plugin called `BadMutable` to make antd code work, but that would make Day.js mutable as well. This is a little hack I think.
> 
> According to Day.js's author:
> 
> > It would be better if Antd could make a little refactor of the way using moment.js.
> 
> > Treat moment object as immutable, and call clone each time before changing it's value like moment().clone().xxx.
> 
> > In this way, there's no need using BadMutable plugin anymore. And Day.js is immutable all the time.
> 
> Is this a considerable refactor? It make the code of antd more clear with no breaking change at all.



antd can replace or refactor the moment, but it will cause the user to replace the moment in their project. This is break change ok? I will also use day.js in the new project, but you have to understand that if antd is replaced Moment, all old items are replaced unless you lock the version of antd. Because you can't guarantee that the api of day.js is the same as the api of moment.

**Comment by xxyuk** [comment]
@sam-dingkang You are miss understanding what I mean. 

What I mean is can we use moment.js in an immutable way?  e.g.

```
var a = moment()
a.add(1, 'day') // a is mutable
var b = moment()
var c = b.clone().add(1, 'day') // b is immutable and c is the result
```
But there are some codes in antd are still modify object without cloning it.

Avoid using mutable object will make the whole code easy to understand and easy to debug.

**Comment by akirak** [comment]
Day.js is not totally compatible with moment.js. The former doesn't provide `isSameOrBefore` and `isSameOrAfter`: https://github.com/iamkun/dayjs/issues/129

**Comment by iamkun** [comment]
@akirak 

Hi, Day.js provide `isSameOrBefore` and `isSameOrAfter` out of box now. 
https://github.com/iamkun/dayjs/blob/dev/docs/en/Plugin.md#issameorafter

I've updated the old answer accordingly.
