### ISSUE TITLE
testing with macaca

### ISSUE THREAD

**Issue by xudafeng** [ant-design/ant-design#1532]
### support

- Both Mobile, Desktop Platforms Supported 
- Test case dev and debug become more easy
- Standard API according to W3 Webdriver [APIS](http://macacajs.github.io/macaca-wd/docs/)

### practice

live demo: https://github.com/xudafeng/autoresponsive-react
ci supported: https://travis-ci.org/xudafeng/autoresponsive-react/builds/126152787

Site: https://github.com/alibaba/macaca

**Comment by xudafeng** [comment]
practice: https://testerhome.com/topics/4755

**Comment by afc163** [comment]
:+1:

现在 antd 上 UI 测试写的很少。

**Comment by afc163** [comment]
赞不考虑迁移，antd 先用更靠近 react 的社区 jest。

@xudafeng 可以去 https://github.com/ant-tool/atool-test 这里把业务上的 UI 测试需求给吃掉。

**Comment by sorrycc** [comment]
业务上很少写 UI 测试，最多测测逻辑。

**Comment by afc163** [comment]
还有 https://github.com/react-component/rc-tools 的测试功能。

**Comment by silentcloud** [comment]
@afc163  atool-test 也不是专门写来用来测 UI 的
