### ISSUE TITLE
Bad position of collapsible submenu in sider when collapsed

### ISSUE THREAD

**Issue by roeibit** [ant-design/ant-design#15321]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout/#components-layout-demo-side](https://ant.design/components/layout/#components-layout-demo-side)

### Steps to reproduce
1. Press on one of the collapsible menu items (User/Team) to view the submenu items.
2. After the submenu has opened collapse the sider by pressing the arrow button on the buttom of the sider.
3. The submenu items will hang to the right of the collapsed sider with a big gap.
4. If you hover the menu again the submenu will pop into its right position.

### What is expected?
The submenu items should stay right beside their menu item parent when sider is collapsed.

### What is actually happening?
The submenu items will hang to the right of the collapsed sider with a big gap.

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | Windows 10 |
| Browser | Chrome / Firefox |

---
This bug didn't occur in version 3.14.

**Comment by afc163** [comment]
same as #14536

**Comment by roeibit** [comment]
It is not the same as #14536. Because the bug I described here doesn't happen in #14536.
It's a different bug there.

This bug is new to 3.15

**Comment by jamesallain** [comment]
We've experienced this same issue; here's a video of it happening in documentation link above:

https://www.dropbox.com/s/160su6zttq37g9h/SiderIssue.mov?dl=0

**Comment by ztplz** [comment]
Got it, I will start looking into it.

**Comment by roeibit** [comment]
Thank you

**Comment by afc163** [comment]
It broken by https://github.com/ant-design/ant-design/commit/7642cbf18d92b8868bbea4ec42f4ba7ed3d5dde5#diff-b5d7ebd6926cbb3981c237f2e491be13 seemingly, @zy410419243

**Comment by zy410419243** [comment]
Opps, let me have a check.

If necessary, revert first. It seems a serious bug.

**Comment by zhangwei900808** [comment]
same problem

**Comment by Andrew213** [comment]
same problem
