### ISSUE TITLE
Add block property to Button inside Upload does not behave as expected

### ISSUE THREAD

**Issue by henrych4** [ant-design/ant-design#15323]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/52qnl0j414)

### Steps to reproduce
Create two Button components with block property set to be true, wrap one of the buttons in Upload component.

### What is expected?
Both buttons should have same width.

### What is actually happening?
The button inside Upload component has smaller width than the normal one.

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | mac os |
| Browser | chrome |

---
Not sure whether this is expected.

Currently my solution is to add `width: 100%` on class ant-upload-select-{listType}

**Comment by afc163** [comment]
Upload has it's own `display: inline-block` layout that the children can break through, your solution is correct and we won't fix this cause it not proper way to do.

**Comment by henrych4** [comment]
Thanks for the explanation.
