### ISSUE TITLE
hash模式下Anchor锚点可以使用吗？

### ISSUE THREAD

**Issue by 406224330** [ant-design/ant-design#15326]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ant design pro地址用的hash模式，Anchor锚点可以通过什么方法正常使用吗？

### What does the proposed API look like?
如现有地址：http://localhost:8000/pc/#/ks/detail?id=10
现在页面内使用Anchor锚点，点击后页面会直接跳走，希望可以通过什么手段实现hash模式下，锚点之间也可以正常跳转。

**Comment by afc163** [comment]
没办法，Anchor 使用的 # 和 hash 是冲突的，你需要使用 browerHistory 模式才行。

**Comment by ctq123** [comment]
@406224330 可以试试这个，https://github.com/ctq123/rcAnchor这个控件不利用href转跳，在hash模式下可以正常使用
