### ISSUE TITLE
blocked button handler while moving one after another.

### ISSUE THREAD

**Issue by HamdyD** [ant-design/ant-design#15324]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z2nn5n1z44)

### Steps to reproduce
> Click on a handler button and move it.
> Directly click on the another button handler (do not click in another place)
> Try to move it (you can't).

### What is expected?
It's expected to be able to move a handler directly after selecting it. No matter what you clicked before.

### What is actually happening?
When a button have the focus and you click directly on the other one, you can't move it. You have to click aside and get back to the button in order to move it.

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.6.3 |
| System | macOs 10.13.6  |
| Browser | Chrome 72.0.3626.121  |

**Comment by ztplz** [comment]
@afc163  https://github.com/react-component/slider/commit/faab29dcac11cb2bea5bb0c81f777f1271036bb8 It caused this bug, so need to revert ?

**Comment by afc163** [comment]
react-component/slider@faab29d will keep focused state after dragging which is good for accessibility, I just created another PR to fix this: https://github.com/react-component/slider/pull/543

**Comment by HamdyD** [comment]
Thank you for your reactivity @ztplz @afc163
