### ISSUE TITLE
动态表单，initialValue不支持数组

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design#15327]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
直接渲染出对应表单项

### What does the proposed API look like?
 <Form.Item label='出访国家/地区'>
            {getFieldDecorator(`names[${k}]`, {
              initialValue: [2321321321, 2321313, 4213213]
            })(
              <Input />
            )}
          </Form.Item>

![image](https://user-images.githubusercontent.com/23191825/54117714-5eb9de80-442c-11e9-9eca-945d4b429f4e.png)

**Comment by afc163** [comment]
Input `value` prop does not accept array type.

**Comment by zheng1013757145** [comment]
Why not support it?
