### ISSUE TITLE
table components header colspan error

### ISSUE THREAD

**Issue by FightingJane** [ant-design/ant-design#15337]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4x6kqvy5p7)

### Steps to reproduce
click "添加父标题"，open devtools, grouped thead's colSpan is not correct.

### What is expected?
 grouped thead's colSpan should be 2

### What is actually happening?
 grouped thead's colSpan is 4,will cause thead incorrect and other bug

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react16.8.4 |
| System | win7 |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="1371" alt="image" src="https://user-images.githubusercontent.com/507615/63091371-b71f7a00-bf90-11e9-8460-76c1deeeee98.png">

Your codesandbox is not matched.
