### ISSUE TITLE
Select 的 dropdownRender中 加了单选框，点击单选按钮的文字下拉框就被关闭了

### ISSUE THREAD

**Issue by lovebslq** [ant-design/ant-design#15333]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p34l3q2577)

### Steps to reproduce
点击“单选按钮旁边的文字”下拉框就被关闭

### What is expected?
点击自定义窗口里面的任何地方下拉框都不会关闭，点击下拉列表与外面body的其它地方关闭

### What is actually happening?
我在父级DIV上面加了 onMouseDown={e => e.preventDefault()} 点击空白区域与单选按钮，还有保存按钮都没有问题，但是点击“单选按钮旁边的文字”下拉框就被关闭了

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | Reat |
| System | win10 |
| Browser | google 版本 71.0.3578.98 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13448#issuecomment-449324251

**Comment by afc163** [comment]
你的例子里没看到有单选按钮和单选按钮旁边的文字。

**Comment by lovebslq** [comment]
> 你的例子里没看到有单选按钮和单选按钮旁边的文字。

加好了，麻烦再帮助我看看，谢谢啦！  刚刚忘记点保存了

**Comment by afc163** [comment]
还是没有

**Comment by lovebslq** [comment]
> 还是没有

添加起了，刚刚没修改成功 https://codesandbox.io/s/p34l3q2577

**Comment by afc163** [comment]
Emmm, It works in Firefox but fail in chrome...

**Comment by lovebslq** [comment]
> Emmm, It works in Firefox but fail in chrome...

现在我们项目就是用 chrome 这个能调整支持吗？

**Comment by zombieJ** [comment]
Merge into #13448
