### ISSUE TITLE
MonthPicker keydown event can't work

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#15335]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-basic](https://ant.design/components/date-picker-cn/#components-date-picker-demo-basic)

### Steps to reproduce
点击月份选择器，点击面板让焦点在面板上，按照title提示按住ctrl 方向右键，不会跳向下一年
![image](https://user-images.githubusercontent.com/22299421/54173631-b6ecf100-44bd-11e9-8f67-f620684d8b33.png)

### What is expected?
按住ctrl 方向右键，跳向下一年

### What is actually happening?
按住ctrl 方向右键，不会跳向下一年

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by mraiguo** [comment]
https://github.com/react-component/calendar/commit/aeb19bf3ec88ef06f5d44bd2adb93c3590c739c2；这个pr修复了左右箭头点击无效，然后导致了按键事件无效了。

**Comment by susiwen8** [comment]
@mraiguo You are right, child component didn't change the prop name.

**Comment by afc163** [comment]
和 #12082 同一个问题，https://github.com/react-component/calendar/pull/401 里进行修复导致了 https://github.com/ant-design/ant-design/issues/12082 的问题，在 https://github.com/react-component/calendar/commit/aeb19bf3ec88ef06f5d44bd2adb93c3590c739c2 回滚了。
