### ISSUE TITLE
TreeSelect 多选时切换选中项，顶部输入框显示有误

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#15339]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/BbwVMx?editors=0011](https://codepen.io/mraiguo/pen/BbwVMx?editors=0011)

### Steps to reproduce
点击选中下拉框的'父节点-1'的checkbox，在点击取消'父节点-1'的checkbox
![bug.gif](https://raw.githubusercontent.com/mraiguo/image-respository/master/bug/tree-select.gif)
### What is expected?
ie9下输入框显示为空值

### What is actually happening?
ie9下值没有完全消失，切无法点击关闭

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react16 |
| System | win7 |
| Browser | ie9 |

**Comment by mraiguo** [comment]
![](https://raw.githubusercontent.com/mraiguo/image-respository/master/bug/tree-select_20190313110244.png)
经过追踪发现和rc-tree-select里面的Animate组件的transitionName有关，如果去掉特效就没有问题。但是antd里面默认启用了‘zoom’效果

**Comment by afc163** [comment]
3.x 不再维护了。
