### ISSUE TITLE
Button removing space when using interpolation in the children

### ISSUE THREAD

**Issue by florian-bd** [ant-design/ant-design#15342]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jvolkl16p3)

### Steps to reproduce
Use JSX interpolation in Button children together with normal string

### What is expected?
Space should be preserved just like when there is no interpolation

### What is actually happening?
Space does not show because extra spans are created

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | windows |
| Browser | Chrome |

**Comment by afc163** [comment]
Can you help us to fix this?

**Comment by ztplz** [comment]
Actually this is not a bug, it is the default behavior of the `span` element. Whitespace at the beginning and end of a text isn't rendered.  But It seems to be related to us because we used `span` to separate the text. @afc163 I am not sure if we need to handle this behavior.

**Comment by florian-bd** [comment]
Sorry I can't help fixing this.
I use a workaround with `&nbsp;`. I updated the codesandbox with it.
What I don't understand is why looping through the children and create a span for each? If you do that anyway then maybe join them to get a single string?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro-site/blob/e913cd52f59e4188767b48c9234faa38f7a60fe6/site/theme/template/Home/Page2.jsx#L67

<img width="173" alt="image" src="https://user-images.githubusercontent.com/507615/56267889-b1b93c80-6122-11e9-8ead-3f9f6f0dc5ba.png">
