### ISSUE TITLE
定制主题能否提供默认icon的颜色变量？

### ISSUE THREAD

**Issue by 409368038** [ant-design/ant-design#15343]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
区分默认icon的颜色和默认文字颜色。场景：菜单栏使用icon和文字，希望icon和文字的颜色有所区分。我整个体统的默认灰色的icon，而文字用黑色的，这样icon和文字放在一起，就更能凸显文字了，更有层次感。

### What does the proposed API look like?
@icon-default-color : #999

**Comment by afc163** [comment]
我加一个 `@icon-color` 吧，但是这样在一些场景比如 Menu/Tabs 里，定制图标的颜色可能会有问题，你需要自行二次处理。

**Comment by gestionpawn** [comment]
ok
