### ISSUE TITLE
Custom TreeSelect Input Tag content

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design#15344]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Eg: I have a department TreeSelect which has many levels, I choose a node department like 'Technical department' which parent dept is 'Company1', and then I select the same name dept in 'Company2', I find there are two tags named 'Technical department' in the input, so I can't distinguish between them.

![捕获](https://user-images.githubusercontent.com/16114101/54194617-9e99c800-44f7-11e9-96ff-dfc0cc23c7f6.PNG)

Online demo: [https://codepen.io/kwzm/pen/drVwza?editors=0010](https://codepen.io/kwzm/pen/drVwza?editors=0010)
### What does the proposed API look like?

TreeNode props add a prop 'tagName' which is the tag's name(default value is title), so I can custom tag name.

**Comment by afc163** [comment]
https://codepen.io/anon/pen/bZaGPJ?editors=0010

**Comment by kwzm** [comment]
@afc163 Thanks a lot!
