### ISSUE TITLE
Table Height improved

### ISSUE THREAD

**Issue by moonlitusun** [ant-design/ant-design#15340]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The height of the Table component is very difficult to define. I just want a scrolling height that inherits from the outside box, but the setting is always maxHeight. The fixed height in the react is hard to get. I think this is very difficult to use, can tell me Can it be improved?

### What does the proposed API look like?
Do not set the height so fixed

**Comment by afc163** [comment]
Try set height to `vh` value, like `100vh`.

same as https://github.com/ant-design/ant-design/issues/14379
