### ISSUE TITLE
Tab Underline disappeared

### ISSUE THREAD

**Issue by ctocto** [ant-design/ant-design#15352]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jp6wq7zklv?fontsize=14)

### Steps to reproduce
切换外层tab，再切换内层tab，再切换外层tab，会发现 下划线消失了，文字还是高亮

### What is expected?
切换tab 下划线会存在

### What is actually happening?
下划线消失了，文字还是高亮

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | react |
| System | MacOs |
| Browser | chrome |

---
子组件触发props 更新会异常显示，setState 不会

**Comment by YJKZHUZHU** [comment]
所以有解决办法吗

**Comment by yoyo837** [comment]
上面的#16013 不能解决问题吗？如果还有问题  上demo 开个新问题。

**Comment by YJKZHUZHU** [comment]
> 上面的#16013 不能解决问题吗？如果还有问题 上demo 开个新问题。
antd已经是最新版本的了，处理方法和上面提到的一样的，还是没解决，

**Comment by yoyo837** [comment]
到处留言没有用，提供有用信息！ new-issue.ant.design

**Comment by YJKZHUZHU** [comment]
> 到处留言没有用，提供有用信息！ new-issue.ant.design
好的呢，谢谢了

**Comment by abellee** [comment]
> > 到处留言没有用，提供有用信息！ new-issue.ant.design
> > 好的呢，谢谢了

你要看一下 你的Tabs是不是一直存活着，特别是被隐藏了的情况下，这个时候去刷activeKey就会出现这样的问题 我是这样的
