### ISSUE TITLE
sortOrder   resizable issue

### ISSUE THREAD

**Issue by AlwaysBeOk** [ant-design/ant-design#15350]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1zq8yr3v6q)

### Steps to reproduce
resizable拖拽

### What is expected?
期望拖拽时，sort不被触发

### What is actually happening?
期望拖拽时，sort依然被触发。

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.2.0 |
| System | mac os |
| Browser | chrome |

---
特别是往左拖拽时，拖动较快容易触发排序，并且 issue #14647 好像没有解决该问题。希望给出清晰的解决方案。十分感谢！

**Comment by AlwaysBeOk** [comment]
I have a idea,  check it please.  https://codesandbox.io/s/1q45y04x9q

**Comment by zombieJ** [comment]
Hi, @AlwaysBeOk. I updated the demo on #14647. Please check~
