### ISSUE TITLE
Typescript definition update for List component

### ISSUE THREAD

**Issue by pavolgolias** [ant-design/ant-design#15357]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using List component there are possibilities to improve Typescript definitions for this component.
1. Property itemLayout is type of string, but better would be something like: ListLayout = 'horizontal' | 'vertical'
2. Add generics to List component so item in renderItem would have the exact type (similar solution is used in Table component)

### What does the proposed API look like?
```javascript
export declare type ListLayout = 'horizontal' | 'vertical';

export interface ListProps {
    ...
    itemLayout?: ListLayout;
    ...
}
```

```javascript
<List<DataItem>
    itemLayout="vertical"
    dataSource={data}
    renderItem={dataItem => <span>{dataItem.text}</span>} />
```

**Comment by yesmeck** [comment]
@pavolgolias Could you open a PR?

**Comment by pavolgolias** [comment]
Yes, I will do it.
