### ISSUE TITLE
Will date picker support that only import the datepicker dropdown？

### ISSUE THREAD

**Issue by ifiknew** [ant-design/ant-design#15364]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to only use the dropdown of date picker.
For example, the dropdown shows when click an icon, some text or any other element.
Is it likely to be supported or I should just use rc-calendar(https://github.com/react-component/calendar)?

#### maybe a Component like:
const Dropdown = DatePicker.Dropdown
#### or a function in DatePicker's props to render my custom input element:
<DatePicker
  inputControlRender={props => <MyControl {...props} />}
/>

**Comment by afc163** [comment]
I think you are looking for http://ant.design/components/calendar

**Comment by ifiknew** [comment]
Sorry I just wanted the same dropdown like those for DatePicker and RangePicker.
But thanks for replying.
