### ISSUE TITLE
当Table中含有 img 标签，第一次渲染 fixed: right 高度有误

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#15361]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qk960p6zv9)

### Steps to reproduce
第一次渲染 fixed 高度有误。
![image](https://user-images.githubusercontent.com/18161513/54247975-f414ba00-4575-11e9-8a57-90cbd7fb0a09.png)

### What is expected?
第一次正确加载 fixed 高度。

### What is actually happening?
第一次渲染 fixed 高度与 Table 高度不匹配。

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.3 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

**Comment by afc163** [comment]
可以先固定大小来解决：https://codesandbox.io/s/n90z73zp94

完美的解决方案可以等这个 PR：https://github.com/react-component/table/pull/283
