### ISSUE TITLE
Input.Password icon not correct

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15369]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/pull/13342](https://github.com/ant-design/ant-design/pull/13342)

### Steps to reproduce
Ref the link, eye icon with show/hide is not correct.

### What is expected?
eye should see in show password

### What is actually happening?
Reverse 

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/54265860-314a6d80-45b1-11e9-8024-f97a886a1bbd.png)
看了下其他的  这个好像没统一的规范

**Comment by zombieJ** [comment]
按设计稿里的来，现在实现和设计稿是反的。

**Comment by zy410419243** [comment]
或者加个受控属性？毕竟没标准，比如我现在看改后的效果就有点难受...

**Comment by ztplz** [comment]
其实我对图标没感觉  那个图标的作用对我来说只是用来控制密码的显示的

**Comment by zombieJ** [comment]
不用做成受控的，antd 是有对应设计标准的：
<img width="221" alt="2018-11-29 2 11 35" src="https://user-images.githubusercontent.com/5378891/49202779-b8981a80-f3e0-11e8-9f5f-5a02944f743b.png">

**Comment by arezookhrirabedi** [comment]
how can i hide ant erro icon in pasword config
