### ISSUE TITLE
Table columns width and header width

### ISSUE THREAD

**Issue by moonlitusun** [ant-design/ant-design#15362]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the x-axis is scrolled, the width of the header and the width of the list are misaligned, not equal to the width I set.

### What does the proposed API look like?
Header width and table are always consistent

**Comment by afc163** [comment]
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/507615/54249887-bbc4aa00-457c-11e9-9a0d-3f2fc67d3fb1.png">

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/507615/54249897-c2532180-457c-11e9-8f9d-fcf4f9a2f9db.png">

https://ant.design/components/table/#components-table-demo-fixed-header

**Comment by afc163** [comment]
你也可能遇到的是这个问题：https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241
