### ISSUE TITLE
Height of Badge with `text` is little large

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15367]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/znol50109m)

### Steps to reproduce
Open link

### What is expected?
Badge with text should have same height as normal text

### What is actually happening?
Get additional 2px 

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12419
