### ISSUE TITLE
无法区分inputNumber 的上下按钮的onChange事件以及 在输入框删除触发的事件，需求是想在左侧输入区域，进行删除操作，只有在失去焦点，才会触发onChange事件，现在每一次删除都会触发Onchange事件

### ISSUE THREAD

**Issue by 15831929073** [ant-design/ant-design#15376]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
无法区分inputNumber 的上下按钮的onChange事件以及 在输入框删除触发的事件，需求是想在左侧输入区域，进行删除操作，只有在失去焦点，才会触发onChange事件，现在每一次删除都会触发Onchange事件

### What does the proposed API look like?
可以区分出来两者

**Comment by afc163** [comment]
Try listen to `onBlur` or `onKeyDown`.
