### ISSUE TITLE
PopConfirm确认后上传

### ISSUE THREAD

**Issue by frankyuan** [ant-design/ant-design#15374]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi，请问如果想在用户点击Upload控件时，先弹出Popconfirm，用户确认后再弹出选择文件的对话框，应该怎么实现？ 好像类似下面的代码不起作用
`<Popconfirm><Upload/></Popconfirm>`

### What does the proposed API look like?

`<Popconfirm><Upload/></Popconfirm>`

**Comment by afc163** [comment]
由于浏览器限制，`input[type="upload"]` 不能使用代码触发文件对话框，所以没有办法做到。
