### ISSUE TITLE
Antd Tabs 组件不支持 rc-tabs 的 SwipeableTabContent 吗？

### ISSUE THREAD

**Issue by coldice945** [ant-design/ant-design#15371]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Antd 的 Tabs 组件继承自 rc-tabs，我看 rc-tabs 有 SwipeableTabContent 功能。可以达到滑动切换 tabs 的目的。
我试验了下发现 Antd Tabs 不能使用。
[codesandbox](https://codesandbox.io/s/2z3v32p82r)

### What does the proposed API look like?
```
  <Tabs
    defaultActiveKey="1"
    onChange={callback}
    renderTabContent={() => <SwipeableTabContent />}
  >
    <TabPane tab="Tab 1" key="1">
      Content of Tab Pane 1
    </TabPane>
    <TabPane tab="Tab 2" key="2">
      Content of Tab Pane 2
    </TabPane>
    <TabPane tab="Tab 3" key="3">
      Content of Tab Pane 3
    </TabPane>
  </Tabs>
```

**Comment by afc163** [comment]
不支持，SwipeableTabContent 是给 antd-mobile 用的。
