### ISSUE TITLE
Form组件的表单验证功能，能否有一个统一添加验证规则的方法或者接口

### ISSUE THREAD

**Issue by hehuasa** [ant-design/ant-design#15372]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
**为了看起来清晰，加个序号表述**：  

**1**.  目前我基于antd，已经完成了一个针对国企客户的项目。项目比较大，表单页也挺多的。  
**2**.  但是现在有个问题，对方客户要求项目在表单验证这个环节，就应当添加验证与阻止sql注入的功能。。。  
**3**.  我们表单页面挺多的，要是一个一个的添加这个验证功能（我做了个正则的规则，用于验证和去筛除特殊字符），工作量挺大的。。。。。  

**so**:请问大佬们，有没有什么办法能够给各表单统一添加一个默认的表单验证功能（比如验证特殊字符的正则）呢？

### What does the proposed API look like?
From组件，统一添加验证规则。

**Comment by afc163** [comment]
阻止 sql 注入应该是后端接口的职责，只靠前端做这层校验是非常不靠谱的。

**Comment by hehuasa** [comment]
但是我觉得， 给表单统一添加验证功能，还是有这个需求的~

**Comment by ztplz** [comment]
前端防sql注入没有任何意义，你校验了一堆，然后人家轻松改个包就绕过去了。如果你一定要校验的话，自己可以写工厂函数封装。
