### ISSUE TITLE
树组件。节点前添了checkbox，无法控制只能选中一个节点(即单选)

### ISSUE THREAD

**Issue by LuckyWinty** [ant-design/ant-design#15379]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
明显选中某个节点时，进行一些操作。虽然现在的onSelect也能达到想要的效果，但是样式上无法做过多改变，且选中不够醒目！

### What does the proposed API look like?
checkMultiple:boolean

**Comment by afc163** [comment]
`checkStrictly={true}`
