### ISSUE TITLE
InputNumber support additional Input props

### ISSUE THREAD

**Issue by kaikun213** [ant-design/ant-design#15385]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be great if we can supply all input-props to InputNumber field.
For the Input component we can use all props from react-input but not for the InputNumber.
In our case this would help to hide the number field when using it in a field decorator. (but still providing its value)

### What does the proposed API look like?
simply add the properties of react-input as additional options to InputNumber

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14284#issuecomment-453390871
