### ISSUE TITLE
Cannot change endDate at the DateRangePicker by clicking on it 

### ISSUE THREAD

**Issue by dmarkin** [ant-design/ant-design#15387]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

### Steps to reproduce
The problem is reproducable at the https://ant.design/components/date-picker/ example 1 field 3.
Choose date range.
Click to field one more time and try to change endDate by keyboard input.

### What is expected?
The full input with endDate is editable by clicking

### What is actually happening?
The input with endDate is editable by clicking at only at the end of the input row block

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.3 |
| System | Ubuntu |
| Browser | Chrome, Firefox |

---
Cause

`<span class="ant-calendar-range-middle">~</span>` with z-index===1

overlaps part of the endDate input, click on the endDate value's input (with z-index===1050) directly don't provide the possibility to change it by keyboard input

**Comment by Yangzhedi** [comment]
![image](https://user-images.githubusercontent.com/11626454/54406692-02014100-4716-11e9-989f-ea8bc2c92533.png)
`ant-calendar-input-wrap` is in the wrong position

**Comment by afc163** [comment]
It could be change in antd v4 RangePicker now: https://ant.design/components/date-picker/
