### ISSUE TITLE
antd@3.14 conflicts with fast.fonts.com using open type features

### ISSUE THREAD

**Issue by leifmarcus** [ant-design/ant-design#15388]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/km16pjx3vr)

### Steps to reproduce
1. open the code sandbox url (https://codesandbox.io/s/km16pjx3vr)
2. wait until the page is loaded
3. page will freeze or be even really slow

### What is expected?
Page should not freeze, It should work together with fast.fonts.com and the webfontloader and open type fonts

### What is actually happening?
the page will freeze and run into some infinite loops that I can not really reproduce

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.7.0 |
| System | Mac Osx 10.14.3 |
| Browser | Chrome 72.0.3626.121 |

---
What I found out so far:

- antd version 3.12.3 works as expected (problem was introduces after this version)
- the problem is related to the https://fast.fonts.net/jsapi/core/mt_otf.js file that is loaded from fonts.com (here they replace `&amp;` with `<amp>`)
- the error only happens, when open type fonts are loaded.

**Comment by afc163** [comment]
I don't know what can you do, could you help us to fix proper solution?

**Comment by afc163** [comment]
close now, feel free to send us PR.

**Comment by leandropio** [comment]
I found a solution to this issue. The aforementioned script is (wrongly) mutating the content of elements having `font-feature-settings-base` CSS property set to any value other than `normal`. In my case, setting the `@font-feature-settings-base` LESS variable to `normal` prevented this to happen.
