### ISSUE TITLE
onExpandedRowsChange and components.body.wrapper used together trigger unmount of rows.

### ISSUE THREAD

**Issue by Aluok** [ant-design/ant-design#15383]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q8mm0o067j)

### Steps to reproduce
Click on any row to expand: **Warning** it opens an infinite loop

### What is expected?
The row to be expanded.

### What is actually happening?
There is a trigger of componentWillUnmount, which in turn triggers the onExpandedRowsChange, which update the state, and it loops

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | React 16.8.4 |
| System | Ubuntu 18.04 |
| Browser | Vivaldi 2.3.1440.60  |

---
If the wrapper in component.body is removed, the problem disapears. 
I not sure whether it's more an ant design issue, or a react-component/table one. ( this one with the wrapper commented [codesandbox](https://codesandbox.io/s/8lzmv1q289))

And thank you for your hard work!

**Comment by afc163** [comment]
It seems to have been resolved in antd 4.x
