### ISSUE TITLE
feature: Alert auto close after timeout

### ISSUE THREAD

**Issue by ycjcl868** [ant-design/ant-design#15394]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
auto close

### What does the proposed API look like?
duration: number (time(seconds) before auto-dismiss, don't dismiss if set to 0)

**Comment by afc163** [comment]
It is a strange feature, what is the scenario?

**Comment by zombieJ** [comment]
Why not use message?

**Comment by ycjcl868** [comment]
Some developers will let the `Alert` show for a few seconds, the message may be too small.

**Comment by afc163** [comment]
How did you use `Alert` in your project? A gif or screen shot would be nice.

**Comment by ycjcl868** [comment]
It's a backend developer need, maybe use `setTimeout` can meet the need.

**Comment by afc163** [comment]
I strongly believe they are using Alert in a wrong way.

**Comment by abhqy** [comment]
> Some developers will let the `Alert` show for a few seconds, the `Message` may be too small.

Have you tried using `notification`? It allows for more content to be displayed: https://ant.design/components/notification/
It also has a duration parameter with which you can display the `notification` for a constant amount of time.
