### ISSUE TITLE
Enable import of getFieldDecorator stateless component

### ISSUE THREAD

**Issue by enzolutions** [ant-design/ant-design#15391]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Decouple fields generation, to be used in auto form generation.

### What does the proposed API look like?
Right now the only to use a getFieldDecorator is via Form.Create(). but this makes difficult to use Antd in systems where the forms and dynamically generated.

Due to the getFieldDecorator is a stateless component, I suggest we could enable to do something like this

```
import { getFieldDecorator } from 'antd'; 
```

or

```
import { getFieldDecorator } from 'antd/lib/getFieldDecorator';
```
 
This change will enable to use Antd in projects like http://vulcanjs.org, the forms are created based in JSON Schema defined via https://github.com/aldeed/simple-schema-js

The form header/ helmet and fields are created dynamically and separated.

**Comment by zombieJ** [comment]
`getFieldDecorator` can not export since it deps on the form context. If you want to used for schema, it's possible to pass form to sub component as props.
It may be not best way but work.

**Comment by bendandoSolo** [comment]
This would be a good feature
