### ISSUE TITLE
Make table filterDropdown placement parameterized

### ISSUE THREAD

**Issue by mpiorowski** [ant-design/ant-design#15403]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Right now the filter dropdown appears only bottomRight. I manage to place the filter icon on the left of the table header, but cannot make the dropdown appear on the bottomLeft.

### What does the proposed API look like?
Make the table filterDropdown placement parameterized. Right now it's hardcoded into the code.

**Comment by mpiorowski** [comment]
Or maybe You can think about adding the option to place the filter button on the left side of the header? :) It just looks more familiar to me (maybe someone will like it too). Right now i just hardcoded the css to make it work. Here's a screen with my current setup.

![image](https://user-images.githubusercontent.com/26543876/54342707-7a480380-463d-11e9-9f6a-f20e83ee1a7e.png)

Btw. amazing work guys, love Your design.

**Comment by afc163** [comment]
> adding the option to place the filter button on the left side of the header?

Maybe we provide a `columnActionsPlacement: 'beside' | 'corner'` to place actions right after header text, instead of column header's corner.

**Comment by nkalinov** [comment]
Bumping this up. Could you prioritize this guys... please?

**Comment by buhichan** [comment]
Is there any progress on this feature?

**Comment by qiaolei1973** [comment]
我这边也有这个需求，可以来提个 pr ，不过实现方案上要先讨论下：
我看到当 table 有 sorter 时，对列的排序是点击列头即可进行排序，而 filter 则是点击右侧的 icon 后才显示，我想这也是 filter 在右侧的意图。
是否可以 columnActionsPlacement = 'beside' 时，禁用掉点击列排序的能力，只有点击 sorter、filter 图标后才可进行相应的操作？为了保持一致性，beside 下只有单 action 也是同样的行为。

**Comment by shengbeiniao** [comment]
mark

**Comment by ofarukcaki** [comment]
+1

It would be nice to use the same positioning props like the ones on the popover component.

**Comment by choudhuryankur** [comment]
is there atleast any way to style these filter dropdowns?????????

**Comment by d9k** [comment]
I think direction === 'rtl' would cause text to be printed from right to left? :thinking: 
So no choise to fix yet..

`components/table/hooks/useFilter/FilterDropdown.tsx`

```
  const { direction } = React.useContext(ConfigContext);

// . . . .
      <Dropdown
        // . . . .
        placement={direction === 'rtl' ? 'bottomLeft' : 'bottomRight'}
```

**Comment by Shaun-Li** [comment]
any reply？
