### ISSUE TITLE
setting error by setFields doesn't work

### ISSUE THREAD

**Issue by yue-qtl** [ant-design/ant-design#15408]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/34465z40wp)

### Steps to reproduce
Step 1. Enter something in input and click button to submit
Step 2. Click confirm and the value of input will disappear, which means the code of setFields working but the error message also missing

Link of official sample code for setFields  :
https://github.com/react-component/form/blob/3b9959b57ab30b41d8890ff30c79a7e7c383cad3/examples/server-validate.js#L74-L79

### What is expected?
bug fix

### What is actually happening?
bug fix

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.7.0 |
| System | windows 10 64bit |
| Browser | Chrome 69.0.3497.100 64bit |

**Comment by afc163** [comment]
```diff
-        error: [new Error("this message wont appear")]
+       errors: [new Error("this message wont appear")]
```
