### ISSUE TITLE
Page Header Disables Tree Shaking

### ISSUE THREAD

**Issue by DavidSichau** [ant-design/ant-design#15407]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/page-header/index.tsx#L6](https://github.com/ant-design/ant-design/blob/master/components/page-header/index.tsx#L6)

### Steps to reproduce
One line in the new Component Page Header includes the index file of antd:

https://github.com/ant-design/ant-design/blob/master/components/page-header/index.tsx#L6

This results that tree shaking of antd is impossible as soon as the page header is included. As then the main library of antd is included.

### What is expected?
That Page Header do not force whole antd to be included.

### What is actually happening?
The main index file of antd is included.

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react 16.8.3 |
| System | Any |
| Browser | Any |

**Comment by zombieJ** [comment]
working on #15354
