### ISSUE TITLE
antd List组件分页中的SizeChanger 不能切换

### ISSUE THREAD

**Issue by 52FTT** [ant-design/ant-design#15405]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://gitlab.iwhalecloud.com/lifuming/NBE8848](http://gitlab.iwhalecloud.com/lifuming/NBE8848)

### Steps to reproduce
1.使用antd
2.使用List组件
3.添加pagination属性
4.添加showSizeChanger: true,pageSizeOptions:[10,20,30]
5.SizeChanger不能切换

### What is expected?
antd List组件中的SizeChanger能够正常切换

### What is actually happening?
antd List组件中的SizeChanger不能切换

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16 |
| System | win10 |
| Browser | 72 |

**Comment by xusanduo08** [comment]
https://codesandbox.io/s/5v7pn3qwjk
这地方有问题重现

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design/blob/master/components/list/index.tsx#L80
https://github.com/react-component/pagination/blob/4b1c6b2c190ef15b84294c13224d4f36e17f0de4/src/Pagination.jsx#L224
逻辑冲突了 默认就给你设置为10了  这个改state的if怎么样也进不来

**Comment by zombieJ** [comment]
@xusanduo08 ，你的 pageSize 写死了：https://codesandbox.io/s/oqp7414orz

@ztplz @afc163 看起来不是 bug？

**Comment by ztplz** [comment]
@zombieJ  这个变受控了 不过也行

**Comment by zhangZYBX** [comment]
// 监听方法是下面这个，重新赋值下就好了
pagination: {
        total: 0,
        pageSize: 10,
        pageSizeOptions: ['10', '20', '30'],
        showSizeChanger: true,
        showTotal: (total, range) => {
          return range[0] + "-" + range[1] + " 共" + total + "条"
        },
        onChange: (page,pageSize) => {
          // 查询点击的第几页
          this.getList(page)
        },
        onShowSizeChange: (page,pageSize) => {
          // 查询分页数量
          this.pagination.pageSize = pageSize
          this.getList(page)
        }
