### ISSUE TITLE
table 中column的render 问题

### ISSUE THREAD

**Issue by HaveDreamMan** [ant-design/ant-design#1540]
我现在需要做一个类似股票行情列表。列表中的每一项需要跟上一次的对比，来显示不同的颜色。但是table控件没法满足我的要求啊。我可以将上次的数据保存起来。但是render方法中传递的三个参数中，我无法确定text是record中的那个属性。也就无法获取前一次的数据。

**Comment by superRaytin** [comment]
不太明白，既然上一次的数据已经保存了，每条数据应该有 id 之类的唯一值吧，应该很容易实现这个对比

**Comment by HaveDreamMan** [comment]
没错，当时有点晕了。不好意思啊

**Comment by superRaytin** [comment]
😂

**Comment by HaveDreamMan** [comment]
我试了一下，不行啊。股票的行情列表是每个字段发生变化了。字体颜色就不一样啊。我看了下API，只能在column中的render 做啊。
function columnRender(text, record, index){
  通过record.key 获取到了上一次的record。但是我怎么知道是这个column值发生变化了。这个三个参数，并没有告诉我这个text内容是从record的那个属性来的，我没法比较啊。
}

**Comment by benjycui** [comment]
`dataIndex` 是你传给 `Table` 的 

![image](https://cloud.githubusercontent.com/assets/3580607/14906597/b6ff5a82-0def-11e6-9848-471b9dc96839.png)

**Comment by HaveDreamMan** [comment]
column中的render中的index，就是dataIndex?

**Comment by superRaytin** [comment]
当前行在数组中的索引

**Comment by benjycui** [comment]
@HaveDreamMan `render` 得到的 `text` 是由你传入的 `dataIndex` 决定的，你说你知不知道是哪个 column 改了？

**Comment by HaveDreamMan** [comment]
`const columns = [{
  title: '最高价',
  dataIndex: 'HighPrice',
  key: 'HighPrice',
  render:commonRender
}, {
  title: '最低价',
  dataIndex: 'LowPrice',
  key: 'LowPrice',
  render:commonRender
}}
var pre={
  HighPrice:100,
  lowPrice:90
}

var cur={
  HighPrice:110,
  lowPrice:80
}
function commonRender(text,record,index){
  var ob=columns[index];
  if(pre.[ob.dataIndex]<cur[ob.dataIndex]){
    return <span style={{color:red}}>{text}</span>
  }else{
    return <span style={{color:blue}}>{text}</span>
  }
}`
是这么写吗？

**Comment by HaveDreamMan** [comment]
`const columns = [{
  title: '最高价',
  dataIndex: 'HighPrice',
  key: 'HighPrice',
  render:commonRender
}, {
  title: '最低价',
  dataIndex: 'LowPrice',
  key: 'LowPrice',
  render:commonRender
}}
var pre={
  HighPrice:100,
  lowPrice:90
}

var cur={
  HighPrice:110,
  lowPrice:80
}
function commonRender(text,record,index){
  var ob=columns[index];
  if(pre.[ob.dataIndex]<cur[ob.dataIndex]){
    return <span style={{color:red}}>{text}</span>
  }else{
    return <span style={{color:blue}}>{text}</span>
  }
}`

**Comment by HaveDreamMan** [comment]
![default](https://cloud.githubusercontent.com/assets/8551569/15038031/f3ce280c-12d2-11e6-8296-3acc64b69c00.png)
