### ISSUE TITLE
`undefined` cannot be removed from `sortDirections` 

### ISSUE THREAD

**Issue by roblingle** [ant-design/ant-design#15415]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/73n0or2rx1)

### Steps to reproduce
Set `sortDirections` to any set that does not include `undefined`. Sorting will still cycle between the defined directions and `undefined`.

### What is expected?
If `sortDirections` is `["ascend","descend"]` or `["ascend"]` then only the specified directions should be allowed.

### What is actually happening?
Clicking the column header multiple times will change direction and will always include the `undefined` sort order.

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | Mac? |
| Browser | Chrome |

---
My table loads remote data which will always be sorted by one column. If a user sorts by a column, they must change direction or sort by another column. It does not make sense here to specify a column with an order of `undefined`.

**Comment by SHITianhao** [comment]
@yesmeck @dengfuping 有没有人在修改这个bug? 我可以提供PR

**Comment by zombieJ** [comment]
It's not a bug. Column should aways enable user to set sort state back after `sortDirections` end.
If you want to lock the sortOrder without default. You can use controlled `sortOrder` instead: https://codesandbox.io/s/jz071jrm7y

**Comment by zzc5464** [comment]
@zombieJ thanks

**Comment by StallionV** [comment]
> It's not a bug. Column should aways enable user to set sort state back after `sortDirections` end.
> If you want to lock the sortOrder without default. You can use controlled `sortOrder` instead: https://codesandbox.io/s/jz071jrm7y

Well that way you are forcing users to write custom sortOrders. I agree with @roblingle where by default we should be able to specify if what states to allow for sorting. [ascend, descend, default] or only [ascend, descend]

**Comment by cesarnml** [comment]
Clever hack to only allow ascend/descend: [solution](https://github.com/ant-design/ant-design/issues/16747#issuecomment-612047300)
