### ISSUE TITLE
Table rowSelection is not working properly

### ISSUE THREAD

**Issue by zicbreeze** [ant-design/ant-design#15414]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1ykm8z4ovj)

### Steps to reproduce
1. Expand and click checkbox record Id 5, record 1,2,8 also checked
2. click check box record Id 6, record 3,4,9 also checked

### What is expected?
When click checkbox on children should also checked Parent or click Parent checkbox should also checked children checkbox.
ie. Click checkbox record Id 5, should also checked record Id 4 or click record Id 4 should also checked 5,6 

### What is actually happening?
1. Expand and click checkbox record Id 5, record 1,2,8 also checked
2. click check box record Id 6, record 3,4,9 also checked

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7.0 |
| System | Mac OS |
| Browser | Google chrome latest version |

---
https://ant.design/components/table/#components-table-demo-expand-children

**Comment by afc163** [comment]
https://codesandbox.io/s/wnvn78mlxl

```diff
        <Table
          style={{ fontSize: "0.85rem", width: "100%" }}
          rowSelection={rowSelection}
          columns={columns}
          dataSource={dataSource}
          pagination={false}
+         rowKey={record => record.id}
        />
```
