### ISSUE TITLE
Add gray to the preset colors of tag

### ISSUE THREAD

**Issue by willc001** [ant-design/ant-design#15422]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes we may need gray tag to stand for not actived or stateless.

### What does the proposed API look like?
Just add 'gray' and 'grey' to the preset colors of tag.

**Comment by afc163** [comment]
```
<Tag />
```

Is it what you need?

**Comment by willc001** [comment]
Not exactly. This one does not support the 'inverse' style.
