### ISSUE TITLE
Is a bug for required of deep rule 

### ISSUE THREAD

**Issue by xiaoblack163** [ant-design/ant-design#15424]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
#Steps to reproduce

```
rules: [{ 
   required: true, 
   message: '完善信息', 
   type: 'array', 
   defaultField: { 
       type: 'object', 
       fields:{
            name: {required: true, message: '完善信息',}
       }
 }}]
```

### What is expected?
正确校验结果

### What is actually happening?
``` async-validator: ["mediaTextList.0.name is required"]```

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | react16 |
| System | macos |
| Browser | Chrome |

---
后续版本有支持的计划吗

**Comment by afc163** [comment]
暂无计划支持。
