### ISSUE TITLE
DatePicker 组件禁用未来时间问题

### ISSUE THREAD

**Issue by nlx0201** [ant-design/ant-design#15429]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://dttest.mm.energymost.com/en-us/5662d/alarm/20___false_false______AlarmTime;true/1](https://dttest.mm.energymost.com/en-us/5662d/alarm/20___false_false______AlarmTime;true/1)

### Steps to reproduce
1、禁用未来日期
2、点击未来日期
3、当天日期被填充到输入框中

### What is expected?
期望未来日期不可选，而且不填充当天日期

### What is actually happening?
未来日期被点击，填充的是当天日期

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 15.4.2 |
| System | window 10 |
| Browser | chrome |

**Comment by DiamondYuan** [comment]
不要发内部网站

**Comment by nlx0201** [comment]
Hi

在sandbox上面无法重现此问题，应该是与某个第三方库有冲突导致的。

例如material-UI





Best Regards,


If you have any problems, pls let me know via email or skype.
________________________________________________________________________________________________________________________________________________________
Chart Nie (聂礼强)  |  Schneider Electric  |  Strategy & Business Development  |  Digital Service  |  Software Development Engineer
Phone: +86 027 5959 6611  |   Mobile:  +86 132 0716 6213
Email: liqiang-chart.nie@schneider-electric.com<mailto:liqiang-chart.nie@schneider-electric.com>  |   Site: www.schneider-electric.cn<http://>
Address: 武汉市东湖高新区光谷大道77号金融港B11栋3层 3th floor, B11 Block, Optics Valley Financial Harbour, No. 77 Guanggu Avenue, East Lake High-tech Development Zone, Wuhan

*** Please consider the environment before printing this e-mail

**Comment by nlx0201** [comment]
Hi

在sandbox上面无法重现此问题，应该是与某个第三方库有冲突导致的。

例如material-UI

**Comment by afc163** [comment]
请提供重现，这样提问没有足够的信息来排查。
