### ISSUE TITLE
input组件 defaultValue失效

### ISSUE THREAD

**Issue by xiejunfeng** [ant-design/ant-design#1542]
input 组件 二次渲染的时候 如果defaultValue值不一样， 不能被修改， 而有些场景下，是需要动态去修改defaultValue的  加一个这个方法就好使了

```js
componentWillReceiveProps(nextProps) {
        let { defaultValue } = nextProps;
        let { input } = this.refs;
        if (defaultValue && (defaultValue !== this.props.defaultValue)) {
            input.defaultValue = defaultValue;
        }
    }
```

**Comment by afc163** [comment]
defaultValue 不能被修改，这是 React 的规范。http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by xiejunfeng** [comment]
xiexie

**Comment by CXJoyce** [comment]
求问怎样才能填充不同的值呐

**Comment by guoguo616** [comment]
竟然追到这了都没找到正确答案。。
记录一下，只要给Input上加一个不一样的key值就会触发二次渲染，新的defaultValue就刷上去了。

**Comment by shixiaoxiang** [comment]
> 竟然追到这了都没找到正确答案。。 记录一下，只要给Input上加一个不一样的key值就会触发二次渲染，新的defaultValue就刷上去了。

但是每次触发onChange都是失去焦点,这.....
