### ISSUE TITLE
upload组件 不支持二次修改参数， 

### ISSUE THREAD

**Issue by xiejunfeng** [ant-design/ant-design#1543]
很多场景下， 上传东西，都要先去拿签名什么的，然后用签名当做参数实现最后的文件上传

**Comment by afc163** [comment]
你最好讲明白你需要什么，这样问我们没有场景，也不知道能做什么。

**Comment by xiejunfeng** [comment]
我们目前上传图片需要先拿到第三方的签名，  第三方签名会根据图片名称等各种算法生成秘钥， 每次上传图片的时候都需要不同的秘钥， 目前我的处理思路是在beforeupload的时候去调用第三方的秘钥接口，然后希望动态的改变upload的data参数， 但是好像不能被修改，不知道能不能提供解决方案？

**Comment by afc163** [comment]
https://github.com/react-component/upload#props

data 支持 function 的方式。这个文档里需要补上。

**Comment by sun-sheng** [comment]
data 设置为 function 时， 拿不到file参数

**Comment by afc163** [comment]
sorry，只有 1.0.0 的才支持，0.12 的文档写错了。

**Comment by afc163** [comment]
https://github.com/react-component/upload/commit/984b7674201bc2a965f10ce4265677bcd61c6346

在 rc-upload@1.9 的时候加入。
