### ISSUE TITLE
table 可编辑行demo `columns`使用fixed属性后数据无法保存

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#15437]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/pYLRvp?editors=0010](https://codepen.io/mraiguo/pen/pYLRvp?editors=0010)
![image](https://user-images.githubusercontent.com/22299421/54422100-b5832900-4748-11e9-88f0-b4e1151d75b2.png)

### Steps to reproduce
点击`editor`按钮，在address栏输入框输入，然后按`sava`保存

### What is expected?
输入的结果保存

### What is actually happening?
输入的结果还是最开始的值

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14634#issuecomment-458805894

**Comment by afc163** [comment]
https://codesandbox.io/s/62w416717r

@zombieJ We can fix it in rc-form maybe.

**Comment by zombieJ** [comment]
@afc163, seems it's caused by context set on EditRow but fixed table use 2 sub table and sub row for edit.
We can wrap it on the Table level: https://codesandbox.io/s/m6oyx874y

It's not rc-form issue.

**Comment by afc163** [comment]
@zombieJ We can update demo to fit `column-fixed` situation.

**Comment by PeterHassaballah** [comment]
I can't find a compatible solution with version 4 of ant design
