### ISSUE TITLE
Responsive Menu icon choice

### ISSUE THREAD

**Issue by zipang** [ant-design/ant-design#15439]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using the Menu component in horizontal mode as a responsive menu.
On desktop : it is an horizontal list of Menu.Item, on mobile, it is a dropdown menu accessible via the `...` button 
(i do not allow for a semi-collapsed mode because i don't think it's a desireable feature).
However, the `...` icon is not conventional when we expect to open/toggle a menu. 
It would be very handy to allow passing an optional icon parameter to specify this.

### What does the proposed API look like?
```html
<Menu mode="horizontal" responsiveIcon={<Icon type="hamburger"/>}>
</Menu>
```

**Comment by afc163** [comment]
`responsiveIcon` should be named to `overflowedIcon`.

**Comment by Yangzhedi** [comment]
`overflowedIndicator` in rc-menu

**Comment by watch-janick** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> I am using the Menu component in horizontal mode as a responsive menu. On desktop : it is an horizontal list of Menu.Item, on mobile, it is a dropdown menu accessible via the `...` button (i do not allow for a semi-collapsed mode because i don't think it's a desireable feature). However, the `...` icon is not conventional when we expect to open/toggle a menu. It would be very handy to allow passing an optional icon parameter to specify this.
> 
> ### What does the proposed API look like?
> ```
> <Menu mode="horizontal" responsiveIcon={<Icon type="hamburger"/>}>
> </Menu>
> ```

How do you disable semi-collapsed mode?

**Comment by JuanChaparroAvanzo** [comment]
Stills function in 2022? i cant do it
