### ISSUE TITLE
将 Cascader 封装为组件后，Form 表单验证功能无效

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#15430]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p2k3y6r19q)

### Steps to reproduce
Form 内 rules: [{ type: "array", required: true, message: "请选择地址" }]，选择后点击按钮依然提示 请选择地址。

### What is expected?
Form表单能监听到该选择。

### What is actually happening?
Form表单未能监听到该选择。

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.3 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

**Comment by yesmeck** [comment]
封装的组件需要调用 `props.onChange` 通知 form 数据变更。https://codesandbox.io/s/l7qvmr7nzl
