### ISSUE TITLE
新版本List.Item的actions的样式改了？

### ISSUE THREAD

**Issue by 406224330** [ant-design/ant-design#15436]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/list-cn/](https://ant.design/components/list-cn/)

### Steps to reproduce
更新到最新后，actions样式被改变，自动加了48的高度，不知道是在哪里设置的，是故意这么做的还是受了其它影响？

### What is expected?
还用原来的样式，不要自动设定高度为48px，如果需要自己调整，最好能给个方法，CSS实在无力。

### What is actually happening?
https://preview.pro.ant.design/list/basic-list 这应该是正常的样子
![image](https://user-images.githubusercontent.com/21120585/54421355-3e00ca00-4747-11e9-88d6-188f2d8137f6.png)
如果antd更新到最新，右侧按钮全部靠上，很不协调。
![image](https://user-images.githubusercontent.com/21120585/54421417-5f61b600-4747-11e9-8092-e65b6fbb40ee.png)

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react  |
| System | WIN10 |
| Browser | GOOGLE |

---
所有用到List的都受影响了

**Comment by afc163** [comment]
在 https://github.com/ant-design/ant-design/pull/15328 里修复了。
