### ISSUE TITLE
Table column 导致 Modal 中的 Input 输入变卡顿

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#15448]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1r988w42k3)

### Steps to reproduce
Modal 中的 Input 输入卡顿。

### What is expected?
Modal 中的 Input 输入不卡顿。

### What is actually happening?
Modal 中的 Input 输入卡顿。

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.3 |
| System | win10 |
| Browser | chrome71.0.3578.80 |

**Comment by afc163** [comment]
https://codesandbox.io/s/o3ojn5kyy

**Comment by zhang504988670** [comment]
如果按照Form.create()写在Modal内部的话，点击Table 修改的时候，无法采用form.setFieldsValue方法。
https://codesandbox.io/s/1r988w42k3

**Comment by 308787520huanhuan** [comment]
![image](https://user-images.githubusercontent.com/3348828/56498620-174b6580-6535-11e9-9d50-317be3ebccb4.png)
遇到同样的问题

**Comment by 308787520huanhuan** [comment]
![image](https://user-images.githubusercontent.com/3348828/56498637-31854380-6535-11e9-8393-5ee525111125.png)
上面是form表单 下面是table组件 把table的dataSource赋值为[]空数组就不卡顿

**Comment by codercatmomi** [comment]
同问

**Comment by cczz598** [comment]
我的Modal表单也是好卡，我一直没找到原因，原来是因为有table啊，症状一样啊。
我用的是antd3.x，但问题是一样的。
