### ISSUE TITLE
Improve Empty component

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#15442]
```jsx
<Empty mode="simple" />
```

<img width="99" alt="图片" src="https://user-images.githubusercontent.com/507615/54433811-b1b2cf00-4767-11e9-9384-4679c1b96948.png">

---

```jsx
<Empty imageSize={40} />
```

**Comment by DiamondYuan** [comment]
simple 代表什么？

**Comment by afc163** [comment]
代表截图里的那个。

**Comment by DiamondYuan** [comment]
> ```js-jsx
> <Empty mode="simple" />
> ```
> 
> <img alt="图片" width="99" src="https://user-images.githubusercontent.com/507615/54433811-b1b2cf00-4767-11e9-9384-4679c1b96948.png">
> 
> ```js-jsx
> <Empty imageSize={40} />
> ```

mode=sample 时候把图片换一张么。

**Comment by DiamondYuan** [comment]
> 对，这个图片现在单独想用用不了。

mode 和 image 参数重复了怎么办？以哪个为准？
我倾向于 image

**Comment by afc163** [comment]
`image` 是自定义图片，现在内建的图片要用不能让用户自己去找图片路径。

**Comment by afc163** [comment]
或者可以这样 `image: 'default' | 'simple' | 'https://xxx.com/xx.png'`?

**Comment by DiamondYuan** [comment]
> 或者可以这样 `image: 'default' | 'simple' | 'https://xxx.com/xx.png'`?

写好了，我也倾向于这种方法。

**Comment by DiamondYuan** [comment]
等有空了再提交一下。
