### ISSUE TITLE
antd Input loses focus when suffix is conditionally rendered

### ISSUE THREAD

**Issue by mlg87** [ant-design/ant-design#15445]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/033q6v1o30)

### Steps to reproduce
Conditionally rendering the `suffix` for the `Input` component will cause the `Input` to lose focus when the outcome fo the conditional render of the `suffix` changes. Where this occurs (at least for me) is when a `Spin` (or any component to indicate loading state for that matter) is conditionally rendered for an input used for fuzzy searching

### What is expected?
The `Input` should maintain focus

### What is actually happening?
When there is no `suffix` rendered (i.e. the conditional return `null`) there is an `<input />` tag rendered. As soon as the suffix conditional is met, there is a `<span />` rendered with the input and `suffix` in it, thus causing a rerender of the `<input />` and loss of focus

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.1 (any of them really) |
| System | macOS Mojave 10.14.3 |
| Browser | All |

---
I fixed this by having the conditional return an empty `<span />` instead of `null`, but this either needs to be documented or not drastically change the output of the `Input` component

**Comment by afc163** [comment]
https://ant.design/components/input/#Why-Input-lose-focus-when-change-prefix/suffix
