### ISSUE TITLE
为Carousel组件添加vertical属性报错

### ISSUE THREAD

**Issue by yewenjunfighting** [ant-design/ant-design#15449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yewenjunfighting/picture-waterfall-stream](https://github.com/yewenjunfighting/picture-waterfall-stream)

### Steps to reproduce
1.clone项目到本地，下载依赖：yarn add  用命令yarn start 运行项目
2点击首页的新闻项在控制台就会出现错误：`NaN` is an invalid value for the `top` css style property.（有vertical的情况）
2如果去掉vertical属性，错误消失

### What is expected?
不报错，并且有效果

### What is actually happening?
报错但效果还是有的

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.7.0 |
| System | Windows |
| Browser | Chrome |

---
Carousel上添加的属性
<Carousel effect="fade" autoplay vertical>

**Comment by DiamondYuan** [comment]
https://github.com/akiran/react-slick/blob/c8d24263517273ae86b982cf783cd4e05ec0be08/src/track.js#L56

**Comment by DiamondYuan** [comment]
定位到代码了，当设置 `effect="fade"` 时候，组件初始化的时候 `slideHeight` 为 null

**Comment by yewenjunfighting** [comment]
所以会有NaN，🆗了解

**Comment by DiamondYuan** [comment]
> 那你们会初始给个值吗，0之类的

这个是 react-slick 组件的问题。而且稍微搜了一下源码 slideHeight 似乎不是外部可以配置的。

**Comment by DiamondYuan** [comment]
不用 fade 应该不会报错。
要解决只能 fork 一份 react-slick 自己维护了。@afc163

**Comment by yewenjunfighting** [comment]
去掉fade确实不会报错

**Comment by DiamondYuan** [comment]
> 那你们会初始给个值吗，0之类的

如果你觉得烦，可以把 node_modules/react-slick/lib/track.js 第 114行 
从 `if (spec.vertical) {` 改成 `if (spec.vertical && spec.slideHeight) {`

**Comment by yewenjunfighting** [comment]
> > 那你们会初始给个值吗，0之类的
> 
> 如果你觉得烦，可以把 node_modules/react-slick/lib/track.js 第 114行
> 从 `if (spec.vertical) {` 改成 `if (spec.vertical && spec.slideHeight) {`
> 
> 不过重新安装依赖就没用了
我还是把fade去了，这种方式太粗暴了
感谢回答，学习了

**Comment by ztplz** [comment]
react-slick的作者好几个月没管过了  一堆issue和pr在那晾着

**Comment by yewenjunfighting** [comment]
> react-slick的作者好几个月没管过了 一堆issue和pr在那晾着

哈哈哈哈，这么秀的吗

**Comment by manbusiwei** [comment]
Carousel属性autoplay失效 v3.15.2，有遇到同样问题的嘛

**Comment by manbusiwei** [comment]
Carousel属性autoplay失效 v3.15.2，非必现。有遇到同样问题的嘛

**Comment by afc163** [comment]
@DiamondYuan 给 https://github.com/ant-design/react-slick 来个 PR。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/react-slick/commit/b42d87e8bcd6c649f352930d9f2a85e7dc9cceef
