### ISSUE TITLE
select 多选框的tag能否自定义

### ISSUE THREAD

**Issue by zhouweihua** [ant-design/ant-design#15452]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
下拉框选项希望展示的内容有点多 在input中尽可能的多显示tag

### What does the proposed API look like?
component like table

**Comment by afc163** [comment]
Try `optionLabelProp`.

**Comment by zhouweihua** [comment]
希望多选的 tag能够自定义显示 tag需要显示的内容少一点 下拉框中的信息多一点 例如 tag只显示‘a1’ 下拉框显示‘a1-公交'
