### ISSUE TITLE
The custom of form item have a bug

### ISSUE THREAD

**Issue by SpikeCowby** [ant-design/ant-design#15463]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/fourfishxiake/pen/qvYyoG?editors=0011](https://codepen.io/fourfishxiake/pen/qvYyoG?editors=0011)

### Steps to reproduce
当回调给上级组件的对象中有target字段时 (onChange(Object.assign({}, this.state, changedValue)); )，得到的props.value就是undefined.

### What is expected?
即使state对象中存在target字段，传回的props.value不为undefined。 输入框能正常使用。

### What is actually happening?
输入框不能输入。

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react |
| System | mac os 10.13.6 |
| Browser | chrome 72.0.3626.121 (Official Build) (64-bit) |

---
当把state对象的target字段替换成target_, 就能正常使用

**Comment by gjandsh** [comment]
我也遇到了这个问题

**Comment by FourEyebrowXiake** [comment]
Magical bug. For formitem, target may be a keyword.

**Comment by zombieJ** [comment]
form use target to track the event value like `event.target.value`.
When customize value is object and has field name `target` will let form thought it's an event object.
We should adjust check logic about this.

**Comment by afc163** [comment]
Is this resolved in new form component?

**Comment by zombieJ** [comment]
New Form still follow the fetch value logic as current one.

**Comment by zombieJ** [comment]
Find that `rc-field-form` will check the `valuePropName` in `target`. Seems it will not break in v4. Close.
