### ISSUE TITLE
Modal 框同时有两个显示时，后一个的mask无法覆盖前一个模态框

### ISSUE THREAD

**Issue by gitcyrabbit** [ant-design/ant-design#1546]
我有一个模态框，点击确认时，需要二次确认，也就是在弹出一个模态框，这时我希望，后一个能遮挡前一个，但ant-modal-mask 元素的z-index 为固定值990，所以后一个不能遮挡前一个

1. 能否自己配置z-index
2. 或者动态计算这个值

**Comment by benjycui** [comment]
这种交互不好吧，用个轻量级的 `Popconfirm`

**Comment by afc163** [comment]
![](https://os.alipayobjects.com/rmsportal/UbnLqYOjlGyekzY.png)

**Comment by RaoHai** [comment]
```jsx
<Modal zIndex={4321} >
  <p>content</p>
</Modal>
```

可以支持指定 Modal 的 mask 的 zIndex 的。。

**Comment by zhanfenghai** [comment]
我在modal上点击确定出现一个popconfirm，但是popconfirm被modal遮住了，我想的是popconfirm应该出现在最外层，尝试修改z-index，但是好像这个z-index会被重新计算

**Comment by benjycui** [comment]
@zhanfenghai 设置 `Popconfirm` 的 `getTooltipContainer` 为 Modal 内部某个元素。

**Comment by benjycui** [comment]
@afc163 `Tooltip` `Popover` `Popconfirm` 的 `getTooltipContainer` alias 为 `getPopupContainer` 可好？与 `Select` `Cascader` 等统一。

**Comment by afc163** [comment]
可行。

**Comment by zhanfenghai** [comment]
@benjycui 不是很明白 能给个demo嘛

**Comment by aNameHere** [comment]
@RaoHai 使用zindex后这个modal的里的一些下拉控件(select,日期等)显示不出来

**Comment by AlingChen** [comment]
> @RaoHai 使用zindex后这个modal的里的一些下拉控件(select,日期等)显示不出来
我也遇到这样的情况 请问怎么解决的

**Comment by sherryQwl** [comment]
给modal加上一个key,每次打开菜单图标modal,都指定新的key=Math.random(),层级重新渲染

**Comment by duoluodexiaoxiaoyuan** [comment]
> 

大佬你怎么知道是990的，我按F12点击元素没有看到
