### ISSUE TITLE
ant design 官网总是打不开

### ISSUE THREAD

**Issue by 15531400827** [ant-design/ant-design#15474]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
点开网址， 加载半天， 无响应

### What is expected?
antd 官网总是出现无法访问的情况啊， 是用的人太多了吗？， 之前还是几天遇到一次， 最近几乎每天都能遇到，隔一段时间就好了， 出现太频繁就很难受啊， 其他人没遇到这种情况吗？ 我怀疑过是网络问题， 但是其他网站， 包括github之类的访问都挺快， 希望优化一下

### What is actually happening?
经常出现无法访问现象

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 最新 |
| System | windows 7 |
| Browser | chrome 69 |

**Comment by shiny** [comment]
我也经常遇到网站访问缓慢的问题，其实这个问题可以通过 DNS 智能解析缓解的，再不济也可以在官方提供镜像链接，而不是只在 issue 区找到镜像链接。

**只能说官方对文档访问可用性很不上心。**

**Comment by afc163** [comment]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/507615/55141537-8ff91500-5175-11e9-9714-6e46d1f4f2e9.png">

**Comment by shiny** [comment]
确实没看到，是我的错误。但淹没在底下一排链接里。考虑下这个链接位置是不是有问题。也不说 element 那种提示，正常情况下网站会把镜像链接以更合理的位置展现。

另外，建议参考下 17ce 里全国访问 ant.design 的速度，尤其是晚高峰国际出口拥堵的时候。由于使用文档的频率非常高，经常需要等待那么几秒才能打开。虽说是个国际化框架，但用户群体在国内比例还是很大的，可以考虑改善国内开发者的体验。

**Comment by jiyarong** [comment]
http://ant-design.gitee.io
打不开啊

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/23472#issuecomment-633518311

**Comment by xrkffgg** [comment]
ant-design 国内镜像地址：https://github.com/ant-design/ant-design/issues/25661
