### ISSUE TITLE
1.0 beta5 没有 lib/index.js

### ISSUE THREAD

**Issue by flyinghail** [ant-design/ant-design#1547]
https://npmcdn.com/antd@1.0.0-beta.5/lib/ 下没有 index.js

`import {xxx} from 'antd';`
npm install 之后，没法像上面这样用，是有意这样改的？

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/5365d4bbd35ce1a4a1a064c0e548aed8d2253425

**Comment by afc163** [comment]
Try `1.0.0-beta.6`
