### ISSUE TITLE
getFieldDecorator里添加节流配置（主要是Input）

### ISSUE THREAD

**Issue by windyzoe** [ant-design/ant-design#15472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
getFieldDecorator相关的validate功能很棒，但是大型表单里Input的输入会影响性能，目前通过HOC方式给Input添加debounce会导致validate失效。更新的validate一直处于dirty=true的状态。

搞了两周Hoc，确实搞不定，麻烦加个功能吧，企业级表单太恶心了，联动太多，不能分拆多form的。

### What does the proposed API look like?
getFieldDecorator('xxxx', { debounce：200 })

**Comment by afc163** [comment]
> 目前通过HOC方式给Input添加debounce会导致validate失效

不如把这个写个重写出来，感觉是实现的方式有问题。

**Comment by windyzoe** [comment]
感谢回答，代码如下。参考的是知乎的例子。用state做了一层缓存，每一次都会重新覆盖input的value。感觉是validate的异步的问题。
```javascript
import React from 'react';
import _ from 'lodash';

export default (triggerMs = 0) => {
  return ReactElement => {
    class DebounceInput extends React.Component {
      constructor(props) {
        super(props);
        this.state = {};
        this.state.value = props.value;
      }

      onChange = (() => {
        let updb = this.props.onChange;
        if (triggerMs >= 0) {
          updb = _.debounce(value => {
            this.props.onChange(value);
          }, triggerMs);
        }
        return updb;
      })();

      handleOnChange = event => {
        const {target:{value}} = event;
        this.setState({ value });
        return this.onChange(value);
      };

      render() {
        const theProps = {
          ...this.props,
          ...this.state,
        };
        theProps.onChange = this.handleOnChange;
        return <ReactElement {...theProps} />;
      }
    }

    return DebounceInput;
  };
};
```

**Comment by afc163** [comment]
来个 http://u.ant.design/codesandbox-repro 好调试。

**Comment by windyzoe** [comment]
https://codesandbox.io/s/mzo1zqmpjp  来了。兄弟，可以关闭了，这种写法没有问题，我的代码问题。SB了，shouldComponentUpdate只给了value通过。把validate屏蔽了。啊，我的青春。

**Comment by afc163** [comment]
@windyzoe 可以自行关闭哦，antd 重现模板还是很有用的，不只是提问模板，也是帮助提问者简化代码和理清思路的工具。

**Comment by windyzoe** [comment]
是的，兄弟，贴上代码就发现不对了。满脸黑线。
