### ISSUE TITLE
in your official website in china , some chunk always load failed

### ISSUE THREAD

**Issue by qsg1215** [ant-design/ant-design#15481]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/tree-cn/](https://ant-design.gitee.io/components/tree-cn/)

### Steps to reproduce
no

### What is expected?
no

### What is actually happening?
no

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.4 |
| System | macOS 10.13.6 |
| Browser | Chrome  72.0.3626.121 |

**Comment by afc163** [comment]
It works on my network.

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/54528535-3e53cc00-49b8-11e9-8103-db9dc961d96e.png)

**Comment by zombieJ** [comment]
You can try https://ant-design.gitee.io/ as mirror.

**Comment by qsg1215** [comment]
> You can try https://ant-design.gitee.io/ as mirror.

I tried

**Comment by ztplz** [comment]
@qsg1215  It's work for me.
![image](https://user-images.githubusercontent.com/17755202/54575337-acd37100-4a2e-11e9-8cf7-bd4148739c3f.png)

**Comment by zombieJ** [comment]
> I tried

hi @qsg1215 , you mean view gitee still meats the issue? You may need check your network or browser plugin about this.

**Comment by afc163** [comment]
Nothing we can do about it, it is the service provided by http://gitee.com/.
