### ISSUE TITLE
[doc]icon shake in dropdown doc with Chrome

### ISSUE THREAD

**Issue by GFwer** [ant-design/ant-design#15485]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown/#components-dropdown-demo-dropdown-button](https://ant.design/components/dropdown-cn/#components-dropdown-demo-dropdown-button)

### Steps to reproduce
When the dropdown is expanded, the icon in menu-item will be shaken (move up), but it's work fine in Codesandbox or other browsers

![Kapture 2019-03-18 at 16 42 16](https://user-images.githubusercontent.com/14303098/54517508-db087080-499c-11e9-987e-e90fdaceb399.gif)

### What is expected?
like other browsers

### What is actually happening?
The icon may move up when dropdown expanded

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.4 |
| System | MacOS 10.14.3 |
| Browser | Chrome 73/74 |

**Comment by dengfuping** [comment]
![image](https://user-images.githubusercontent.com/14918822/54523391-63414280-49aa-11e9-9c82-a4cd95ef7fb0.png)

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/54570433-6c1d2d00-4a19-11e9-97f6-312711694a21.png)
I just found a very strange thing, the icon will shake when `vertical-align` between `1.5-2.0`px.

**Comment by zombieJ** [comment]
Seems we should optimize align logic to avoid decimal value: https://codesandbox.io/s/p5q05wx1kx

**Comment by GFwer** [comment]
It seems similar problems also exist in DatePicker with placeholder shake(only in the doc site using Chrome):

![Kapture 2019-03-19 at 12 30 16](https://user-images.githubusercontent.com/14303098/54580405-e3b38200-4a42-11e9-9a54-e5eb9f1b89eb.gif)

**Comment by afc163** [comment]
https://www.yuque.com/yuque/topics/3698

Here is a workaround: `transform: perspective(1px);`, don't know any effect yet.

**Comment by zombieJ** [comment]
Maybe adjust `dom-align` to remove decimal value first?

**Comment by afc163** [comment]
之前的修复貌似失效了：https://github.com/ant-design/ant-design/pull/13722

**Comment by zombieJ** [comment]
主要问题都是带小数点的像素对齐动画抖动，align 做完后还得看看有没有其他弹窗方式有没有像素对齐的问题。

**Comment by ztplz** [comment]
我老想着重构

**Comment by abenhamdine** [comment]
Why this issues is closed ?
The issues is still present, for example see the select component : https://ant.design/components/select/#header
With or withour an icon (only text), there's a visual shake on the option menu.
Is there another issue for reference to track this problem ?

**Comment by zombieJ** [comment]
@abenhamdine could you help to give a gif for this?
