### ISSUE TITLE
`.ant-input` style not loaded automatically with babel-plugin-import in `DatePicker`

### ISSUE THREAD

**Issue by dickeylth** [ant-design/ant-design#15483]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/dickeylth/antd-input-issue](https://github.com/dickeylth/antd-input-issue)

### Steps to reproduce
1. tnpm install;
2. npm run start;
3. see the bug in browser

### What is expected?
As shown in the README, should auto load the `.ant-input` class style.

### What is actually happening?
As shown in the README, the `.ant-input` class style is not automatically loaded.
After inserting an `<Input />` to the `<App />`, the `.ant-input` class style loaded correctly.

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | ^16.8.4 |
| System | macOS Mojave 10.14.3 |
| Browser | Chrome 72 |

Besides, FYI, tests on version `3.14.1` passed.

**Comment by yutingzhao1991** [comment]
https://github.com/ant-design/ant-design/commit/f9d8e50a1ff37c54f1cfa0ab63648abdc665e433 这个导致的 @zombieJ

**Comment by ChiaJune** [comment]
我也遇到了同样的问题，版本是 v3.15.1
临时解决办法是单独引一次 `Input` 组件的样式文件

``` js
import 'antd/lib/input/style/index';
```

**Comment by zombieJ** [comment]
嗯，看起来是多删了……
