### ISSUE TITLE
antd的时间段选择功能插件

### ISSUE THREAD

**Issue by INTMIN** [ant-design/ant-design#15486]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在业务逻辑上需要填写一个时间段，但是现在官方提供的时间段的只有一个集成在日期选择框的时间段的选择，能否在TimePicker新增一个时间段的选择，自己改源码很麻烦，然后在现在这个插件的基础上再自定义开发，样式很难调整

### What does the proposed API look like?
类似RangePicker，可以选择某一时间段，两个值；存在disabledTime，有可以自己定义的onchange事件，

**Comment by afc163** [comment]
Duplicate of #9582

**Comment by INTMIN** [comment]
我这个不要日期啊，有日期的选择是错误的

**Comment by INTMIN** [comment]
只要一个选择时间段的功能就行，不能让用户选择日期，而且这个表单内有很多这样的时间段的选择，全部拆分会让这个界面变的很长，并且限制的函数也会变得很多不好维护

**Comment by oychao** [comment]
这个Feature Request有日程安排吗？
