### ISSUE TITLE
Affix区域会被Table fixed列遮挡

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#15499]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ox722ox9k6)

### Steps to reproduce
重现链接中向下滚动页面，发现按钮被表格遮盖

### What is expected?
Affix不被遮盖

### What is actually happening?
Affix被遮盖

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.2.0 |
| System | Window |
| Browser | Chrome 73.0.3683.75 |

---
Table fixed列zIndex比Affix高

**Comment by zombieJ** [comment]
affix 比较特殊，感觉还需要考虑一下 `z-index` 插在哪儿比较适合。
ref：https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L252

**Comment by afc163** [comment]
`@zindex-table-fixed : 20;` is no longer needed cause we hide fixed-columns in body table now.

https://github.com/ant-design/ant-design/issues/13930 won't happen again.
