### ISSUE TITLE
How to style slider tooltips only

### ISSUE THREAD

**Issue by spsaucier** [ant-design/ant-design#15495]
Posting this for future searchers:

#### Problem
I wanted to style slider tooltips differently from other tooltips, but there is no documented method of passing props from the slider to its tooltips.

#### Solution
Use the `Slider`'s undocumented `tooltipPrefixCls` prop. You can thereby add an additional class to the tooltip, as long as you ensure that your value ends in ` ant-tooltip`.

In my case, I used something like:
```
<Slider tooltipPrefixCls="slider-tooltip ant-tooltip" />
```

From there, look for your tooltip element in the DOM to see how you can use the new class, which is added at three levels of the modal element.

**Comment by shaodahong** [comment]
这个是有需求的，建议重新打开 @afc163
