### ISSUE TITLE
Input field will ignore future non-empty defaultValue if passed an empty defaultValue at first

### ISSUE THREAD

**Issue by geodeath** [ant-design/ant-design#15497]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vqov564v95)

### Steps to reproduce
1. Use Input component with defaultValue that comes from server
2. Input will render with a blank value due to the HOC's (Wrapper.js) blank state, before putting the prop values in the state
3. When the data from the server/props are in the HOC's state they will be passed down to the Template.js and the Input component
4. At this time, it will not be re-rendered to show the new props. See just below the InputWrapper, how the same value paragraph appears fine

### What is expected?
The expected result is that the Input component will receive the new props and will rerender, so it will rerun the function generating the defaultValue (returnValueOrNull, coming from the parent HOC component), returning the 'new' value, as the paragraph does

### What is actually happening?
I believe the Input component gives priority to the 'value' field, rather than the 'defaultValue' field, so when it is first rendered with an undefined value it completely ignored the defaultValue, even if it is there (line 94 in Input.ts file -> var value = typeof props.value === 'undefined' ? props.defaultValue : props.value;)

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.4 |
| System | MacOS |
| Browser | Chrome 72.0.3626.119 (Official Build) (64-bit) |

---
We can work around this by using value instead of defaultValue but we need these components to be non controlled.

**Comment by yesmeck** [comment]
This is how React works. If you don't want use `value` prop, you can give input a different key when `defaultValue` change.

https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html#recommendation-fully-uncontrolled-component-with-a-key

**Comment by geodeath** [comment]
But if you change the Input to an input (so an html5 component instead of the ant d component) it works fine.

This is because that line i am referencing in the Input component is giving precedence to value over defaultValue if value is not 'undefined'. Changing that line to be more inclusive seems to work.

Using getDerivedStateFromProps also works, but in React, any time the data changes and triggers a re-render, it should be updating to the latest one.

**Comment by yesmeck** [comment]
> But if you change the Input to an input (so an html5 component instead of the ant d component) it works fine.

Because in antd we treat an empty value as a valid `defaultValue`.

Here is a working version https://codesandbox.io/s/ql798rk66q
