### ISSUE TITLE
Steps中的Step由另一个组件返回时生成的class名称中包含undefined

### ISSUE THREAD

**Issue by AllanJian** [ant-design/ant-design#15494]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

**Comment by AllanJian** [comment]
我是用那个issue助手创建的 但是自动跳转过来就成了这样...

https://codepen.io/allanjian/pen/aMKaBg?&editable=true&editors=001

期望是将Step包裹在一个组件里 作为最外层, 然后将这个组件放进Steps里, 但产生的html的class中出现了undefined-item undefined-item-wait

**Comment by afc163** [comment]
https://codepen.io/anon/pen/PLayPa?&editable=true&editors=001
