### ISSUE TITLE
建议Spin组件自适应父级宽度和高度，或设置高宽100%

### ISSUE THREAD

**Issue by niss2000** [ant-design/ant-design#1549]
Spin组件应该将整个container覆盖，但实际上发现它只会覆盖住子组件高宽，但很多时候子组件高宽在渲染之后才会确定，因此建议Spin能够以父级高宽为准，而不是子级的高宽，而由于Spin的存在，子组件设置100%无法参照到Spin的父组件
`<div style={{width: '300px', height: '300px'}}>
   <Spin>
      <div style={{width: '100%', height: '100%'}}>期望是一个300*300的容器，但实际上没有高宽</div>
   </Spin>
<div>`

只需要给.ant-spin-nested-loading添加高宽的设定，或者直接设置width: 100%; height: 100%;

**Comment by afc163** [comment]
当内嵌使用 spin 时，spin 可视为一段字符（类似 `加载中...`），需要自行定义 spin 的大小和位置。
