### ISSUE TITLE
Drawer header not aligned to Layout header

### ISSUE THREAD

**Issue by fabriziocucci** [ant-design/ant-design#15496]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://not-available.sorry](http://not-available.sorry)

### Steps to reproduce
* Create a simple page with a Layout header and a Drawer with a title
* Open the drawer

### What is expected?
The `Drawer` header should be aligned to the `Layout` header (i.e. same height).

### What is actually happening?
The `Drawer` header is actually smaller (`ant-drawer-header` is **55px**) than the the `Layout` header (`ant-layout-header` is **64px**). This causes the divider below the `Drawer` title to be misaligned with respect to the `Layout` header.

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.2 |
| System | macOS Mojave (10.14.2) |
| Browser | Chrome (72.0.3626.121) |

---

<img width="355" alt="issue" src="https://user-images.githubusercontent.com/8156463/54544103-ce811980-4996-11e9-935e-249ec86e943c.png">

**Comment by afc163** [comment]
Sorry, it is by designed.

**Comment by SalahAdDin** [comment]
> Sorry, it is by design.

So, we have to fix it by ourselves, right?
