### ISSUE TITLE
Steps组件的step节点过多的情况下, 内容会到窗口外， 没有自动伸缩

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design#15509]
Steps组件的step节点过多的情况下, 内容会到窗口外， 没有自动伸缩，大屏时不适合用vertical呈现。
![menu saveimg savepath20190319154844](https://user-images.githubusercontent.com/19385704/54588630-85949800-4a5e-11e9-9e6a-d4059e29cc4d.jpg)

**Comment by yoyo837** [comment]
自己容器加一下样式适配一下吧，横向式超出滚动，mobile时纵向定高加超出上下滚动
