### ISSUE TITLE
DatePicker组件 使用mode属性的时候 选择了时间之后无法自动关闭

### ISSUE THREAD

**Issue by Gcherryzhang** [ant-design/ant-design#15504]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在不同时间格式的情况下，datepicker组件中只通过mode属性显示不同格式的时间 

### What does the proposed API look like?
无论是在有mode属性还是无mode属性 在选中某一个时间之后，面板应该正常关闭，尝试过使用配合open属性控制显示与隐藏，但是用户体验不好

**Comment by afc163** [comment]
目前的设计如此，不要把 mode 当成 `MonthPicker` 来用，作用不一样。
