### ISSUE TITLE
I had some warning using menu component don't know how to solved them

### ISSUE THREAD

**Issue by zackfalcon** [ant-design/ant-design#15501]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j3xvwwv739)

### Steps to reproduce
Just create a menu

### What is expected?
DOn't have any warning

### What is actually happening?
I got like 300 warning about my menu see pictures.

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | react 16.6.3 |
| System | Linux |
| Browser | Chrome |

---
See picture to understand x)

**Comment by zackfalcon** [comment]
https://www.noelshack.com/2019-12-2-1552967021-capture-d-ecran-de-2019-03-19-04-42-33.png
https://www.noelshack.com/2019-12-2-1552967021-capture-d-ecran-de-2019-03-19-04-42-27.png
https://www.noelshack.com/2019-12-2-1552967022-capture-d-ecran-de-2019-03-19-04-42-22.png
https://www.noelshack.com/2019-12-2-1552967022-capture-d-ecran-de-2019-03-19-04-42-20.png
 here is all pictures of the error thanks a lot.

**Comment by afc163** [comment]
Your codesandbox didn't reproduce any warnings.

**Comment by zombieJ** [comment]
Seems no warning provided in reproduce?

**Comment by zackfalcon** [comment]
Of course my sandbox don't reproduce anything i didn't know why it happens 0 warning, in my sandbox and in my code got them for a simple menu

**Comment by zackfalcon** [comment]
Should i give you my menu code ?

**Comment by afc163** [comment]
There is nothing we can do if no reproduce.

**Comment by ztplz** [comment]
Or your can provide a mini `git repo`?
