### ISSUE TITLE
<Upload>组件能自定义渲染已上传文件列表吗？

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#15505]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
已上传的文件现在默认显示了文件名、删除按钮，我还想显示文件大小，或自定义条目左侧的icon，但是没找到相关的接口能自定义渲染。

### What does the proposed API look like?
希望能有接口能自定义渲染已上传文件的列表

**Comment by wufeng87** [comment]
![image](https://user-images.githubusercontent.com/1686808/54586589-77dc1400-4a58-11e9-8667-2638b2a9dae6.png)
想实现类似这样子的效果。

**Comment by afc163** [comment]
https://ant.design/components/upload-cn/#components-upload-demo-fileList

`showUploadList={false}`，然后外部拿到 `fileList` 自行渲染列表。
