### ISSUE TITLE
建议Icon组件支持其他图标库

### ISSUE THREAD

**Issue by niss2000** [ant-design/ant-design#1551]
目前Icon只能通过type指定iconfont的图标，建议增加lib和ext属性，指定图标库，比如lib='fa' type='fa-home' ext='fa-lg' 那么表示使用的是font-awesome图标库，生成图标 `<i class='fa fa-home fa-lg'/>`

**Comment by afc163** [comment]
你可以直接使用 font-awesome 图标库。https://www.npmjs.com/package/react-fontawesome
