### ISSUE TITLE
Statistic title color not correct

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15514]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/pull/14154](https://github.com/ant-design/ant-design/pull/14154)

### Steps to reproduce
参考设计稿，title 的默认颜色漏了：https://ant.design/components/statistic-cn/#header

### What is expected?
title 颜色变淡

### What is actually happening?
title 没设置颜色

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
我总感觉数值应该用 `@heading-color`，参考 https://preview.pro.ant.design/dashboard/analysis

**Comment by zombieJ** [comment]
大的是 `@heading-color` .85，这个小的应该是 `@text-color-secondary` .45。漏了：
<img width="159" alt="屏幕快照 2019-03-19 下午9 49 45" src="https://user-images.githubusercontent.com/5378891/54610939-fe144c80-4a90-11e9-9915-9b453f344328.png">
