### ISSUE TITLE
希望select提供可以输入自定义内容，也可以下拉选择的功能

### ISSUE THREAD

**Issue by wgt464649654** [ant-design/ant-design#15518]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前即能输入，又能选择只能用mode为tags。但是我只想选一个，tags的话交互会比较奇怪

### What does the proposed API look like?
mode里增加一个tag，tag单选或自定义，tags多选

**Comment by afc163** [comment]
https://ant.design/components/auto-complete/

**Comment by wgt464649654** [comment]
> https://ant.design/components/auto-complete/

good thanks

**Comment by CeleKing** [comment]
@wgt464649654 自动完成的这个能满足题目的功能吗 这样下拉只有新增的内容了吧？
