### ISSUE TITLE
3.15.1的anticon的css新增了一个color:inherit，该样式会和notification的icon颜色冲突

### ISSUE THREAD

**Issue by Lovelcp** [ant-design/ant-design#15512]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3njvv8z45)

### Steps to reproduce
跟诸岳在钉钉上聊过，他知道的

### What is expected?
notification的icon颜色正确，比如warning打开的就是一个黄色

### What is actually happening?
icon是黑色

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16 |
| System | MacOS |
| Browser | Chrome最新版本 |

**Comment by afc163** [comment]
例子里貌似没问题。

**Comment by dengfuping** [comment]
- 前天我也遇到了这个问题，不过不是每个项目都必现。初步怀疑是 3.15.1 版本中的这个 [PR](https://github.com/ant-design/ant-design/pull/15345) 可能会导致 CSS 样式权重发生变化。以下是两个版本的样式对比:

| 3.15.0 版本 | 3.15.1 版本 |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/14918822/54601527-2e9cbc00-4a7a-11e9-9e42-6704d55c4591.png) | ![image](https://user-images.githubusercontent.com/14918822/54601293-a1f1fe00-4a79-11e9-8f77-4c4a3248de5c.png) |

**Comment by Lovelcp** [comment]
@afc163 偏右大神，我是在bigfish的场景下遇到的，这个我也不太好提供重现的demo。你看 @dengfuping 诸岳的回复应该就明白了

**Comment by zombieJ** [comment]
感觉要看看项目样式引入方式，common style 应该是放最前的才对。不行就 notification 多搞一层包掉它……
