### ISSUE TITLE
Can not change validate message in real time after error message rendered via setState()

### ISSUE THREAD

**Issue by thiscallback** [ant-design/ant-design#15527]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z63jo12j1x/)

### Steps to reproduce
1. Note that 
```
rules: [{ required: true, message: this.state.msg }]
```
2. After rendered error message, the **message** value can not changed after executing setState({msg: 'Hello Jerry!'})

### What is expected?
Say "Hello Jerry!" to Jerry.
Change validate message in real time after error message rendered.

### What is actually happening?
Say "Hello Tom!" to Jerry

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.7.0 |
| System | macOS Mojave(10.14.3) |
| Browser | Chrome 72.0.3626.121 |

**Comment by zombieJ** [comment]
It's caused that `setState` on form submit is async state update. validate form is still use the origin state: https://codesandbox.io/s/72ozq10m30

You should validate after state really updated: https://codesandbox.io/s/y2wv7m8m8j

**Comment by thiscallback** [comment]
@zombieJ So, is there any way to change "message" state without call call method form.validateFields(), as the same as "placeholder" prop (`<Input placeholder={this.state.label} />`) or "required" prop ( `rules: [{ required: this.state.dynamic, message: this.state.msg }]` )

**Comment by zombieJ** [comment]
form use cache to save validate result. You can use `setFields` to change it manually.
