### ISSUE TITLE
Picker is changing a uncontrolled input of type undefined to be controlled

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#1552]
使用RangePicker（"antd": "^0.12.15",）组件出的问题，选择完时间单击确定的时候。

warning.js?7fcb:44 Warning: Picker is changing a uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

Demo如下
```
require('antd/style/index.less');

import React from 'react';
import ReactDOM from 'react/lib/ReactDOM';


import {DatePicker} from 'antd';
const RangePicker = DatePicker.RangePicker;

class Demo extends React.Component {
    constructor(props) {
        super(props);

    }
    render() {
        return (
            <div>
                <RangePicker showTime format="yyyy-MM-dd hh:mm a"/>
            </div>
        )
    }
}

ReactDOM.render(<Demo />, document.getElementById('test'));
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1340
