### ISSUE TITLE
dropdown in custom component not rendering

### ISSUE THREAD

**Issue by svenced** [ant-design/ant-design#15528]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6vr5krrlr3)

### Steps to reproduce
- create a simple component (see minimal reproduction)
- try rendering a dropdown by wrapping the custom component in the Dropdown tags

### What is expected?
When wrapping a custom component with the `<Dropdown>` tags and overlay props, it should render the dropdown on hover/click.

### What is actually happening?
Custom component renders properly and DOM applies the various Trigger tags, but on hover/click, the Dropdown event does not fire to render the overlay.

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.4 |
| System | OSXMojave 10.14.3 (18D109) |
| Browser | Chrome Version 72.0.3626.121 (Official Build) (64-bit) |

---
* We were trying to make reusable components and were not able to apply the `<Dropdown>` tags to the `<CustomComponent/>` without loosing the dropdown. 
* It **works** if wrapping the **SAME** custom component in any basic html tags, or even in AntD tags (ie. Card). 
* Tried going directly into **dropdown.js**->`_this.renderDropDown` to watch props, but did not notice any obvious missing things

* Any suggestions if we are missing something obvious would be much appreciated!

**Comment by afc163** [comment]
https://codesandbox.io/s/305m1vynjm

**Comment by svenced** [comment]
awesome! thank you, thought there would be something obvious i was missing. much appreciate the quick reply!

**Comment by afc163** [comment]
#15909
