### ISSUE TITLE
Select组件的suffixIcon无法在下拉列表展开和收起时进行旋转方向

### ISSUE THREAD

**Issue by HypnosNova** [ant-design/ant-design#15531]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://r7nx2mz1z4.codesandbox.io/)

### Steps to reproduce
创建Select组件，添加一个svg到suffixIcon属性。运行页面

### What is expected?
suffixIcon在下拉列表展开和收起时进行旋转方向

### What is actually happening?
suffixIcon不会在下拉列表展开和收起时进行旋转方向

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.7.0 |
| System | win10，mac |
| Browser | chrome最新 |

---
Select组件的suffixIcon无法在下拉列表展开和收起时进行旋转方向。也没有合适的api或事件来监听select的展开和收起事件来手动去修改suffixIcon的状态。因此此bug无法在实际项目里通过修改Select或者额外包一层东西来修复。

**Comment by afc163** [comment]
你的例子貌似运行的挺好的。

**Comment by HypnosNova** [comment]
@afc163 我在项目里是用suffixIcon属性塞了一个svg进去。但是自定义的svg箭头无法因为下拉的展开和收起进行旋转。我试过把antd默认的箭头svg代码拷贝出来，然后import {ReactComponent as ArrowIcon} from './arrow.svg'。那么我
<Select suffixIcon={<ArrowIcon/>}>
<Option value=1>1</Option>
</Select>
里面的ArrowIcon就不会旋转。我想知道这个Select有没有类似onExpend这样的事件监听到，这样我也可以手动去旋转svg。我不传svg，我随便写一个<div></div>放suffixIcon它也无法旋转
参看这个：https://5pwo8l4pl.codesandbox.io/

**Comment by afc163** [comment]
> 放suffixIcon它也无法旋转 参看这个：https://5pwo8l4pl.codesandbox.io/ 

你这个例子也是好的，貌似和顶楼的没啥区别。你可以点开试试。

**Comment by zombieJ** [comment]
试了一下，会转：https://codesandbox.io/s/zr9nnzxrnl

如果没有重现的话，我们也帮不了……

**Comment by qq34347476** [comment]
给 Icon 加个样式 pointer-events: none 就能直接解决

**Comment by Carry3** [comment]
点开下拉框的时候ant-select会多一个类.ant-select-open 增加一个css即可
.ant-select-open {
                svg {
                    transform: rotate(180deg);
                }
            }
