### ISSUE TITLE
Mouse up/down event catch under button

### ISSUE THREAD

**Issue by qqsea** [ant-design/ant-design#15536]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now user can catch click event for button or other component. Whether or not can catch mouse down/up event?
I want to implement a speed up button. For example, If user just click the button once, the value will be changed by step one, but if user mouse click this button not loose it, the value will be updated by multiple steps. Like the speed up button within a music player.

### What does the proposed API look like?
Does element-ui support such function or from other way? For react?

**Comment by afc163** [comment]
> Does element-ui support such function or from other way? For react?

Here is not element-ui repository, maybe you are asking at wrong place.
