### ISSUE TITLE
[feature] Pagination - quick jumper should be not display when pagination has only one page

### ISSUE THREAD

**Issue by marlo22** [ant-design/ant-design#15539]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be nice when quick jumper is not display when pagination has only one page.

### What does the proposed API look like?
Similar to hideOnSinglePage attribute - for example hideQuickJumperOnSinglePage(true/false[boolean])

**Comment by zombieJ** [comment]
Hmmm. Maybe we can default hide it if only one page... `hideQuickJumperOnSinglePage` seems over design.

**Comment by marlo22** [comment]
@zombieJ sounds good.

**Comment by afc163** [comment]
Released in `rc-pagination@1.17.9`
