### ISSUE TITLE
增加颜色选择组件

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#15533]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了颜色选择问题

### What does the proposed API look like?
返回颜色

**Comment by afc163** [comment]
You can try [react-color](http://casesandberg.github.io/react-color/) in https://ant.design/docs/react/recommendation-cn
