### ISSUE TITLE
Form表单中使用了this.props.form.getFieldDecorator(id, options)，在options中使用options.initialValue参数，参数值设置为this.state.xxx，当setState改变state.xxx的值之后表单域的值没有变

### ISSUE THREAD

**Issue by abbia0** [ant-design/ant-design#15532]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ping0000/pen/rRZvaJ?editors=0110](https://codepen.io/ping0000/pen/rRZvaJ?editors=0110)

### Steps to reproduce
重现链接中有

### What is expected?
重现链接中有

### What is actually happening?
重现链接中有

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.4 |
| System | MacOs 10.14.3 |
| Browser | Chrome Version 74.0.3729.6 (Official Build) dev (64-bit) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14915#issuecomment-464991519
https://github.com/ant-design/ant-design/issues/5109#issuecomment-283071388
