### ISSUE TITLE
Form.item label can't control Swtich

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#15549]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vnoo153ol3)

### Steps to reproduce
1. Click Switch label

### What is expected?
Switch can be controlled by label

### What is actually happening?
label can't control Swtich

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.1 |
| System | Windows10 |
| Browser | Chrome/72.0.3626.121 |

---
Switch switch cannot be controlled by clicking Form.Items label.

**Comment by junliuxian** [comment]
It's this line of [code ](https://github.com/ant-design/ant-design/blob/master/components/form/FormItem.tsx#L321) that prevents default behavior.

**Comment by afc163** [comment]
related issue: https://github.com/ant-design/ant-design/issues/9103

**Comment by junliuxian** [comment]
I've read [#9103](https://github.com/ant-design/ant-design/issues/9103). Because it creates the problems of the present.

**Comment by junliuxian** [comment]
It's been too long. It should be closed.
