### ISSUE TITLE
ant design table有没有暴露方法在table之外全选或者全不选

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#15548]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table之外全选或者全不选

### What does the proposed API look like?
给一个外部api全选或者全不选

**Comment by afc163** [comment]
Try `selectedKeys`

**Comment by wangxingxing123654** [comment]
> selectedKeys

这个只能清空吧。具体在table外全选做不到啊

**Comment by afc163** [comment]
selectedKeys 设为所有数据的 key 集合就行了。
