### ISSUE TITLE
DatePicker should not set width = 195 when props.showTime == true

### ISSUE THREAD

**Issue by ifiknew** [ant-design/ant-design#15545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p72pvl27jq)

### Steps to reproduce
set props showTime=true for date picker, and set css 'input { width: 300px }'

### What is expected?
datepicker's width is calculated as 300px

### What is actually happening?
it is set to 195px

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.3 |
| System | mac os 10.13.6 |
| Browser | chrome 69 |

---
https://github.com/ant-design/ant-design/blob/3.15.1/components/date-picker/createPicker.tsx
line 164
use min-width instead?

**Comment by rinick** [comment]
I think this issue should be re-opened and have a different solution.
