### ISSUE TITLE
2.x 版本的antd 的icon的 cdn文件挂了

### ISSUE THREAD

**Issue by captainbob** [ant-design/ant-design#15540]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2x.ant.design/components/icon/](https://2x.ant.design/components/icon/)

### Steps to reproduce
进入官网2.x的icon页面

### What is expected?
i
c
o
n
显
示

### What is actually happening?
....

| Environment | Info |
|---|---|
| antd | 2.13.14 |
| React | 16.7 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
检查一下你的网络看看是不是有屏蔽，这边是好的：
<img width="1021" alt="屏幕快照 2019-03-20 下午5 09 38" src="https://user-images.githubusercontent.com/5378891/54672449-00c77e00-4b33-11e9-9349-cf61cc4cc79f.png">

**Comment by afc163** [comment]
估计和阿里云故障有关系，我们啥也做不了，先关了。

**Comment by captainbob** [comment]
已经好了, 应该是阿里云的问题吧
