### ISSUE TITLE
ant design table表头能不能自定义图标呢。不是排序和过滤

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#15543]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
想在表头的一列里实现一个标题加icon的效果。不是过滤和排序两种。

### What is expected?
想在表头的一列里实现一个标题加icon的效果。

### What is actually happening?
只能加sort和filter

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16 |
| System | 10 |
| Browser | chrome |

**Comment by dengfuping** [comment]
@wangxingxing123654 直接在 `title` 里定义就行。

**Comment by wangxingxing123654** [comment]
title里面只能搞字符串把

**Comment by wangxingxing123654** [comment]
> @wangxingxing123654 直接在 `title` 里定义就行。

title里面只能搞字符串把

**Comment by wangxingxing123654** [comment]
> @wangxingxing123654 直接在 `title` 里定义就行。

多谢

**Comment by miaozilong** [comment]
this.columns = [
      {
        title: '<Icon type="edit" />',
        dataIndex: 'name',
        editable: true,
      },  这样好像不行啊

**Comment by wuyonglv** [comment]
> ```
> this.columns = [
>   {
>     title: '<Icon type="edit" />',
>     dataIndex: 'name',
>     editable: true,
>   },  这样好像不行啊
> ```
把引号去掉
this.columns = [
  {
    title: <Icon type="edit" />,
    dataIndex: 'name',
    editable: true,
  },
