### ISSUE TITLE
文档导航链接地址错误

### ISSUE THREAD

**Issue by imzshh** [ant-design/ant-design#1554]
这个页面上右上角导航栏的链接地址错了：
http://ant.design/docs/spec/layout#layout-demo-top

**Comment by afc163** [comment]
不明白哪里错了。

**Comment by imzshh** [comment]
1. 访问 http://ant.design/docs/pattern/navigation
2. 点击常见导航中的“常见布局”链接：http://ant.design/docs/spec/layout#layout-demo-top
3. 右上角的导航链接错掉了

**Comment by afc163** [comment]
还是没懂。。。

**Comment by Pasturn** [comment]
没错，可能第二个没显示完整，他以为错了

**Comment by imzshh** [comment]
要按照我之前说的步骤访问那个“常见布局”页面才会出现错误的导航链接，直接打开那个页面的话是没有问题的。

**Comment by afc163** [comment]
发现了，指的是页面最上方的导航链接。:+1:
