### ISSUE TITLE
npm start failed, Module not found: Can't resolve '@babel/runtime/helpers/esm/extends'

### ISSUE THREAD

**Issue by goeswind** [ant-design/ant-design#15542]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:8082/](http://localhost:8082/)

### Steps to reproduce
1、cnpm install
2、npm start

### What is expected?
visit my login page normally

### What is actually happening?
page cannot display, get following error:
Failed to compile
./node_modules/_history@4.9.0@history/esm/history.js
Module not found: Can't resolve '@babel/runtime/helpers/esm/extends' in 'E:\workdir\code\react\yzmall-admin4\node_modules\_history@4.9.0@history\esm'
This error occurred during the build time and cannot be dismissed.

| Environment | Info |
|---|---|
| antd | 3.1.0 |
| React | react: 16.2.0 |
| System | win10 |
| Browser | qq browser, 10.2 |

**Comment by zombieJ** [comment]
Hi @goeswind ,
The log you provided seems it's not caused by antd. Please check your code or dependencies instead.

**Comment by goeswind** [comment]
@zombieJ this is my source code problem, please try it 
https://github.com/goeswind/antd-problem

**Comment by zombieJ** [comment]
hi, we only handle antd issue in github. You can ask project question on stackoverflow or fire issue to history repo if you think it's a bug.
