### ISSUE TITLE
希望表格可以自定义列

### ISSUE THREAD

**Issue by SecretDubhe** [ant-design/ant-design#15559]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
后台业务在数据多的时候会存在一个表里需要展示十数个字段。
那么有的时候可能会根据不同部门的不同职能有需求去调整列的展示顺序，以及挑选哪些字段需要展示出来。

### What does the proposed API look like?
no

**Comment by afc163** [comment]
这里有一个简单的例子可以参考：https://codesandbox.io/s/wjx9o995
