### ISSUE TITLE
Cannot scroll down to the bottom if a fixed sider is collapsible

### ISSUE THREAD

**Issue by stubbornleaf** [ant-design/ant-design#15553]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/NJOyZE?&editable=true&editors=001#anon-login](https://codepen.io/anon/pen/NJOyZE?&editable=true&editors=001#anon-login)

### Steps to reproduce
Check the link:
https://codepen.io/anon/pen/NJOyZE?&editable=true&editors=001#anon-login

### What is expected?
Should be able to scroll down to the bottom of the sider

### What is actually happening?
Cannot scroll down to the bottom and last few items are not visible

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.3 |
| System | Mac OS |
| Browser | any |

---
If the link doesn't work, just modify this code in codepen to add more menu items there to get a repro.

**Comment by dengfuping** [comment]
@stubbornleaf Just add `margin-bottom` style for `Menu` like [this demo](https://codepen.io/dengfuping/pen/EMdeQp).
```js
<Menu style={{ marginBotton: 96 }} ...
```
