### ISSUE TITLE
select设置allowClear后,未选择值,但是hover的时候会显示清除按钮

### ISSUE THREAD

**Issue by wangjinghui-cn** [ant-design/ant-design#1555]
`<Select allowClear={true} placeholder="请选择" style={{ width: 120 }} onChange={handleChange} />
<Cascader options={options} onChange={handleChange} />`
当select支持allowClear后, 如果这个没有选择option, 当鼠标移动到区域内, 下拉的地方会变成清除的标志
而Cascader不会, Cascader只会在选择option后才会展示清除标志

**Comment by RaoHai** [comment]
这个其实在 develop-1.0.0 已经修复了的，升级一下 rc-select 的版本就好了……

**Comment by afc163** [comment]
确实，develop-1.0.0 上已修复。
