### ISSUE TITLE
设置Tree组件的loadedKeys为[]，会导致onLoad方法一直调用

### ISSUE THREAD

**Issue by baizn** [ant-design/ant-design#15556]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/a54a06b3](https://riddle.alibaba-inc.com/riddles/a54a06b3)

### Steps to reproduce
打开控制台，一直重复打印日志

### What is expected?
设置loadedKeys后，重置已展示的节点

### What is actually happening?
设置loadedKeys后，一直循环调用，导致浏览器卡死

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 0.16.x |
| System | mac |
| Browser | chorme最新 |

**Comment by dengfuping** [comment]
@baizn 重现步骤能否贴下？直接打开重新链接，控制台无打印信息。

**Comment by baizn** [comment]
https://codesandbox.io/embed/yjnjk5o28v。
操作步骤：点击展开按钮。

**Comment by zombieJ** [comment]
`loadedKeys` 本身就是控制判断哪些节点，onLoad 里告知了哪些节点被加载成功，你重置为空数组。当然会触发 Tree 重新调用 `loadData` 来加载数据了。

**Comment by Benpaodejiezai** [comment]
请问下，怎么解决的，谢谢

**Comment by lovemegowin** [comment]
This issues can be solved by 

```javascript 

const [loadedKeys, setLoadKeys] = useState([])

const loadData = async (treeNode) => {
    const data = treeNode.props.dataRef
    setLoadKeys([...loadedKeys, data.nodeId])
    // ...
  }

const handleExpand = (expandedKeys, {expanded, node}) => {
    const keys = node.props.dataRef.nodeId
    if (!expanded){
      setLoadKeys(loadedKeys.filter(item=>item!==keys))
    }
  }
```

**Comment by whateveryoudo** [comment]
@lovemegowin 收起最近的父级是没问题，隔几个节点的收起就会有问题

**Comment by whateveryoudo** [comment]
这里采用loadKeys,expandedKeys 都受控的方式实现，每次收起会去掉当前操作节点的所有字节点，这里贴出部分代码：
工具方法(用于获取指定节点下所有的子节点key)：`const childNodesDeep = (nodes, arr) => {
  if (nodes) {
    nodes.forEach((ele) => {
      arr.push(ele.id);
      if (ele.children) {
        childNodesDeep(ele.children, arr);
      }
    });
  }
}
export const getChild = (nodes, targetId, arr) => {
  for (const el of nodes) {
    if (el.id === targetId) {
      arr.push(el.id);
      if (el.children) {
        childNodesDeep(el.children, arr);
      }
    } else if (el.children) {
      getChild(el.children, targetId, arr);
    }
  }
  return arr;
}`
使用方法：`async onLoadData (treeNode) {
      this.loadedKeys = [...this.loadedKeys, treeNode.$vnode.key]
      ajax请求...
}
handleExpand (expandedKeys, { expanded, node }) { // 收起时处理(这里会重置下面所有节点展开keys,加载keys)
      const key = node.$vnode.key
      if (!expanded) { // 收起时
        const childKeys = getChild(this.treeData, key, []); // 获取当前节点下所有子节点（这里会包含自身）
        this.loadedKeys = this.loadedKeys.filter(item => !childKeys.includes(item))
        this.expandedKeys = this.expandedKeys.filter(item => !childKeys.includes(item))
      } else { // 展开时
        this.expandedKeys = expandedKeys;
      }
    }
`

**Comment by Paul3899** [comment]
> 这里采用loadKeys,expandedKeys 都受控的方式实现，每次收起会去掉当前操作节点的所有字节点，这里贴出部分代码：
> 
>  ```javascript
> 
> // 工具方法(用于获取指定节点下所有的子节点key)：
> 
> const childNodesDeep = (nodes, arr) => {
> 
>  if (nodes) {
> 
>     nodes.forEach((ele) => {
> 
>       arr.push(ele.id);
> 
>       if (ele.children) {
> 
>         childNodesDeep(ele.children, arr);
> 
>       }
> 
>     });
> 
>   }
> 
> }
> 
> export const getChild = (nodes, targetId, arr) => {
> 
>   for (const el of nodes) {
> 
>     if (el.id === targetId) {
> 
>       arr.push(el.id);
> 
>       if (el.children) {
> 
>         childNodesDeep(el.children, arr);
> 
>       }
> 
>     } else if (el.children) {
> 
>       getChild(el.children, targetId, arr);
> 
>     }
> 
>   }
> 
>   return arr;
> 
> }
> 
> // 使用方法：
> 
> async onLoadData (treeNode) {
> 
>       this.loadedKeys = [...this.loadedKeys, treeNode.$vnode.key] // 这里是antd-vue的获取key方式
> 
>       // ajax请求...
> 
> }
> 
> handleExpand (expandedKeys, { expanded, node }) { // 收起时处理(这里会重置下面所有节点展开keys,加载keys)
> 
>       const key = node.$vnode.key
> 
>       if (!expanded) { // 收起时
> 
>         const childKeys = getChild(this.treeData, key, []); // 获取当前节点下所有子节点（这里会包含自身）
> 
>         this.loadedKeys = this.loadedKeys.filter(item => !childKeys.includes(item))
> 
>         this.expandedKeys = this.expandedKeys.filter(item => !childKeys.includes(item))
> 
>       } else { // 展开时
> 
>         this.expandedKeys = expandedKeys;
> 
>       }
> 
>     }
> 
> ```
