### ISSUE TITLE
动态表单中不能同时设置表单项和值

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#15555]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/AshoneA/pen/oVaQzw?editors=0010](https://codepen.io/AshoneA/pen/oVaQzw?editors=0010)

### Steps to reproduce
官方的动态表单demo中，在componentDidMount的时候去设置了keys和names，但是names的值并不能设置进去，必须在keys被setFieldsValue之后才能设置进去names的值

### What is expected?
期望能够把两个值都设置进去

### What is actually happening?
现在有一个解决办法就是在设置keys之后，再用setTimeout异步的去更新names，这样是可以更新进去的。或者说setFieldsValue是否能跟setState一样，提供一个回调方法，使其能够在setFieldsValue之后进行操作

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16 |
| System | MacOS |
| Browser | Chrome |

**Comment by liaoyinglong** [comment]
https://codepen.io/anon/pen/GLoXMO?editors=0010

`key`不一定要放在`formStore`里的，放`state`里面就能用你想要的`setState`的回调了
