### ISSUE TITLE
table额外展开行在分页切换时如何隐藏

### ISSUE THREAD

**Issue by qwer5454554** [ant-design/ant-design#15563]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table额外展开行在分页切换时如何隐藏

### What does the proposed API look like?
控制额外展开行的显示隐藏

**Comment by afc163** [comment]
Try control `expandedRowKeys`.

**Comment by qwer5454554** [comment]
以及配合onExpandedRowsChange这个的使用

**Comment by WilliamFocus** [comment]
分页重置表格expandedRowKeys属性
