### ISSUE TITLE
【Steps】wrong `margin-left` for `small`, `progressDot` Steps's Icon

### ISSUE THREAD

**Issue by TiaossuP** [ant-design/ant-design#15566]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jvqy9mv7z9)

### Steps to reproduce
see link

### What is expected?
right icon position

### What is actually happening?
wrong icon position

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.3 |
| System | macOS 10.14.3 (18D109) |
| Browser | Chrome 75.0.3739.0 |

---
it seem https://github.com/ant-design/ant-design/pull/15256/files cause this issues

**Comment by afc163** [comment]
`progressDot` don't support `small` size for now, we can support though.

**Comment by TiaossuP** [comment]
emmm I noticed 
> progressDot 点状步骤条，可以设置为一个 function，labelPlacement 将强制为 vertical

but until I see the english doc, I got `labelPlacement` means `title` and `description`...

**Comment by TiaossuP** [comment]
and In face, `progreessDot` & `small` still looks good until [this pr](https://github.com/ant-design/ant-design/pull/15256/files)

**Comment by afc163** [comment]
Good catch, could you send us a PR to fix this?
