### ISSUE TITLE
table设置固定列，此时无数据的时候表头不能拖动

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#15569]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/PLyrjd?editors=0011](https://codepen.io/mraiguo/pen/PLyrjd?editors=0011)

### Steps to reproduce
使用 `固定头和列` demo,将data数据清空，此时缩小窗口，没有出现滚动条，不能看到后面的列
![image](https://user-images.githubusercontent.com/22299421/54741500-a80ee880-4bf9-11e9-922b-305e00d71b9b.png)

### What is expected?
可以拖动查看所有列

### What is actually happening?
无法拖动查看

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
表头可以拖动，body 内目前没有好的办法。

**Comment by mraiguo** [comment]
@afc163 表头可以拖动是指？

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/54742854-739d2b80-4bfd-11e9-9b62-b4c7b7817332.gif)

**Comment by guxingke201** [comment]
这是浏览器默认的交互吧，来个title提示一下如何？大部分用户不会想到用左右键滚动。
![image](https://user-images.githubusercontent.com/8326941/54743975-ab59a280-4c00-11e9-9f08-b4476ce0b1ce.png)

**Comment by afc163** [comment]
title 没有合适的地方放的，空数据看列感觉意义不大。目前的 UI 找不到合适方式解决。

**Comment by afc163** [comment]
Duplicate of #10490

**Comment by zjhjszwx** [comment]
windows拖动不了, 连看都看不全了
