### ISSUE TITLE
Typography组件在flex布局中无法正确断行

### ISSUE THREAD

**Issue by Durianicecream** [ant-design/ant-design#15564]
### 重现代码
```

import React from 'react'
import { Typography } from 'antd'

export default function Demo(props) {
	return (
		<div
			style={{
				width: '100px',
				display: 'flex',
				border: 'solid 1px red'
			}}
		>
			<div style={{ flexGrow: 1 }}>
				<Typography.Paragraph>
					测试一个比较长的数学表达式:100*100 100*100-100*100/100
				</Typography.Paragraph>
			</div>
		</div>
	)
}

```

### 结果演示
![image](https://user-gold-cdn.xitu.io/2019/3/21/1699f1d254ccbe46?imageView2/2/w/480/h/480/q/85/interlace/1)

### 环境信息
 
| 名称 | 版本 |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | win10 |
| Browser | chrome 72 |

**Comment by afc163** [comment]
和 flex/Typography 关系不大，这是浏览器默认的行为，你需要自行实现相关断行逻辑。
