### ISSUE TITLE
ConfigProvider support Drawer default width

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15568]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
do not need set drawer default width one by one

### What does the proposed API look like?
<ConfigProvider drawer={{ width: 720 }} />

**Comment by ztplz** [comment]
这个有必要吗  有那么多drawer要设置吗

**Comment by zombieJ** [comment]
> 这个有必要吗 有那么多drawer要设置吗

复杂应用中的嵌套表单场景还是很多的，非常非常多的抽屉。感觉是可以抽出来允许统一配置的。

cc @afc163 @chenshuai2144 ，一起讨论下

**Comment by yesmeck** [comment]
这样往 `ConfigProvider` 塞配置的话没个底的。

**Comment by zombieJ** [comment]
> 这样往 `ConfigProvider` 塞配置的话没个底的。

不塞写区块太蛋疼了，每个都要重写一遍。感觉应该有多少塞多少。

**Comment by afc163** [comment]
配一个 Drawer 的 less 变量？

**Comment by zombieJ** [comment]
> 配一个 Drawer 的 less 变量？

有两个尺寸要求，一个大 Drawer（720），一个小 Drawer（520）……
