### ISSUE TITLE
upload组件上传异常

### ISSUE THREAD

**Issue by lemondreamtobe** [ant-design/ant-design#15561]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/tree/master/components/upload](https://github.com/ant-design/ant-design/tree/master/components/upload)

### Steps to reproduce
```
export const beforeUpload = (file) => {
  
  if (!(file.type === 'image/jpeg' || file.type === 'image/png' || file.type === 'image/gif' || file.type === 'image/jpg')) {
    notification.warning({
      message: '只能上传 JPG, JPEG, PNG 和GIF文件哦！',
      duration: 3
    });
    return false;
  }
  return true;
}
```
即使校验了上传文件类型。但是上传了zip文件，return false了之后，还是出现了zip文件的缩略图

### What is expected?
校验非法文件直接不上传不出现缩略图

### What is actually happening?
即使校验了上传文件类型。但是上传了zip文件，return false了之后，还是出现了zip文件的缩略图

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.2.0 |
| System | mac |
| Browser | google |

**Comment by afc163** [comment]
这是符合预期的，`return false` 是阻止默认的 Ajax 上传动作，不会从列表中清空，你需要用受控模式控制 `uploadList` 属性来做到这一点。

**Comment by xyy94813** [comment]
@afc163 不太明白这个为什么这个为什么属于预期之内。

如果这个属于预期， `beforeUpload` return `false` 后 `file.status` 变更为 `error` 会不会比较好

**Comment by afc163** [comment]
`beforeUpload` return `false` 设计时是用于这个场景：https://ant.design/components/upload-cn/#components-upload-demo-upload-manually

用户选择后，不立刻上传，点击提交按钮后统一上传。默认设置成 `error` 是不太合适的，这里并没有出错。

**Comment by xyy94813** [comment]
那么如果我想限制文件上传的大小，类型之类的，应该怎么处理？
这也是个常见场景。

**Comment by afc163** [comment]
在 beforeUpload 里控制 uploadList 即可，修改你想要的任何状态。

**Comment by yansuan** [comment]
自己控制怎么都好说，手动上传方式为什么不改为受控模式呢 ？
在Form中在何处修改fileList值？在beforeUpload返回false时不修改值比较科学，希望能修改。

**Comment by rainyulei** [comment]
我的做法是, 验证位错误的文件删掉
```javascript
```

**Comment by rainyulei** [comment]
我的做法是把不符合格式的文件删掉，类似于这样
```javascript
 const handleBeforeUpload = (file) => {
    const isJpgOrPng =
      file.type === 'image/jpeg' ||
      file.type === 'image/png' 
    if (!isJpgOrPng) {
      message.error('You can only upload JPG/PNG file!');
    }
    if (isJpgOrPng ) {
      setFileList([...fileList, file]);
      return true;
    }
    return false;
  };
 const handleChange = ({ file, fileList }) => {
    if (file.status !== 'error') {
     const newFIleList =  fileList.filter(item=>item.uuid!==file.uuid)
      setFileList(newFIleList)
    }
    setFileList(fileList)
  };
```
有其他解决办法么？

**Comment by fshty** [comment]
关键是一选择就会将数据请给http。这个组件是不是傻？不校验你发起什么http请求。智能还是智障？
