### ISSUE TITLE
Range/DatePicker设置mode后，onChange失效

### ISSUE THREAD

**Issue by hk029** [ant-design/ant-design#15572]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/voidsky/pen/moQbwO](https://codepen.io/voidsky/pen/moQbwO)

### Steps to reproduce
可以查看console，所有`onChange`里事件都没有触发，只能在`onPanelChange`里进行值的修改，这不符合这两个事件的预期。

### What is expected?
`onChange`中能拿到改变的month

### What is actually happening?
`onChange`并没有触发

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.x |
| System | MacOS 10.14.3 |
| Browser | Chrome 72.0.3626.121 |

---
同时，mode="month"的时候，弹窗无法关闭（这点已经有其他人反映了），但是目前没有可用的`MonthRangePicker`的组件，因此只能用`RangePicker`去模拟`MonthRangePicker`的功能

**Comment by afc163** [comment]
`mode="xxxx"` 目前只是用于控制面板的展示方式，不会修改 RangePicker 的默认关闭逻辑。就像你说的，你需要用 `RangePicker` 去模拟 `MonthRangePicker` 的行为，可以用 `open` 和 `onOpenChange` 去控制面板的显示。

**Comment by zhangyanling77** [comment]
解决方案如下：
handlePanelChange = (value) => {
    // console.log(">>>>>", value)
    this.setState({
      time: value,
      isopen: false
    })
  }

  handleOpenChange = (status) => {
    // console.log(status)
    if(status){
      this.setState({isopen: true})
    } else {
      this.setState({isopen: false})
    }
  }

  clearValue = () => {
    this.setState({
      time: null
    })
  }

const { time, isopen } = this.state;
<DatePicker 
          value={time} 
          open={isopen} 
          mode="year" 
          placeholder='请选择年份'
          format="YYYY"
          onOpenChange={this.handleOpenChange}
          onPanelChange={this.handlePanelChange}
          onChange={this.clearValue}
        />

**Comment by zhangyanling77** [comment]
`
handlePanelChange = (value) => {
    console.log(">>>>>", value)
    this.setState({
      time: value,
      isopen: false
    })
  }

  handleOpenChange = (status) => {
    // console.log(status)
    if(status){
      this.setState({isopen: true})
    } else {
      this.setState({isopen: false})
    }
  }

  clearValue = () => {
    this.setState({
      time: null
    })
  }
const { time, isopen } = this.state;
<DatePicker 
          value={time} 
          open={isopen} 
          mode="year" 
          placeholder='请选择年份'
          format="YYYY"
          onOpenChange={this.handleOpenChange}
          onPanelChange={this.handlePanelChange}
          onChange={this.clearValue}
        />
`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16984
