### ISSUE TITLE
Cannot read property 'offsetHeight' of undefined

### ISSUE THREAD

**Issue by inoryFly** [ant-design/ant-design#15574]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/dashboard/analysis](https://preview.pro.ant.design/dashboard/analysis)

### Steps to reproduce
ant-design-pro随便一处加个不带showSearch的TreeSelect都行，第二次点击就会显示此错误，并且渲染卡顿，但是showSearch为True时，该组件正常

### What is expected?
不带showSearch也能用

### What is actually happening?
必须使用showSearch属性

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7.0 |
| System | windows10 |
| Browser | 谷歌最新 |

---
这个我直接clone的github上的官方代码，npm安装依赖后随处添加的TreeSelect都有该问题

**Comment by ztplz** [comment]
我感觉应该发在pro那边

**Comment by yang-ren-ting** [comment]
老哥解决了嘛，同样遇到这个问题

**Comment by ixiejun** [comment]
遇到同样的问题

**Comment by afc163** [comment]
Fixed in rc-tree-select@2.6.2, try reinstall `node_modules`.

**Comment by tdida** [comment]
@afc163 antd 3.16.3 还有这个问题，依赖的还是 2.6.0 的 rc-tree-select

**Comment by afc163** [comment]
@tdida Please remove `yarn.lock` and `package-lock.json` and reintall `node_modules`.

**Comment by li2215890610** [comment]
这个问题是不是官方还没解决呢？
