### ISSUE TITLE
个人感觉Select的onChange加一个（value,item）比较好 item是是选中项的对象

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-design#15578]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
个人感觉Select的onChange加一个（value,item）比较好 item是是选中项的对象
form提交的时候保存数据要保存选中项的除id外的其他数据，
form提交取值也不用a.b     a.c之类
form回显的时候只需要一个value就可以显示默认值，不用拼接对象信息，

### What does the proposed API look like?
onChange变成（value,item）和table的全选，单选一样（选中的ID，选中的集合）

list:[{id:1,name:'莉莉',key:'deli',mark:'AD0003'},{id:1,name:'莉莉',key:'deli',mark:'AD0003'}]

onChange(value,item){
/**
*value:1
*item:{id:1,name:'莉莉',key:'deli',mark:'AD0003'}
*/
}

**Comment by afc163** [comment]
Try `labelInValue`.

**Comment by XinYueXiao** [comment]
labelInValue  的使用只有 key 和  value 
因为key穿object 并不返回object而是字符串'[object] [object]'
提交的时候需要重新赋值提交（一般提交都是{id:1,name:'222'}而不是id:{key:1,label:'222'}）
而且回显的时候需要拼接对象回显
使用并不方便
如果只使用这个key,value 个人感觉目前版本onChange(value,arr)更编辑
但是这两种方式其他数据获取不到，如果需要其他数据，则还是要循环自取

**Comment by XinYueXiao** [comment]
labelInValue 的使用只有 key 和 value
因为key穿object 并不返回object而是字符串'[object] [object]'
提交的时候需要重新赋值提交（一般提交都是{id:1,name:'222'}而不是id:{key:1,label:'222'}）
而且回显的时候需要拼接对象回显
使用并不方便
如果只使用这个key,value 个人感觉目前版本中onChange(value,arr)更便捷
但是这两种方式其他数据获取不到，如果需要其他数据，则还是要循环自取

**Comment by afc163** [comment]
onChange 的第二个参数是 Option 对象。

**Comment by XinYueXiao** [comment]
是的，所以可以获取到option 的key 和 value 取到值 和 labelInValue一样

**Comment by XinYueXiao** [comment]
有的时候需要到不仅仅是这两个值，需要更多，就只能循环获取了
希望可以在option上加个参数，可以获取到 当前选中信息到对象

**Comment by afc163** [comment]
你可以把你需要的数据直接放在 Option 上，这样不需要二次读取了。

**Comment by XinYueXiao** [comment]
是的，你说的很对👍👍👍👍👍
谢谢你🌹🌹🌹🌹🌹🌹🌹

**Comment by XinYueXiao** [comment]
我可以在onChange里面获取到所有的自定义属性😱😱😱😱

**Comment by YEriin** [comment]
> 你可以把你需要的数据直接放在 Option 上，这样不需要二次读取了。
> 
> ```js-jsx
> <Option xxx yyy zzz  />
> ```
> 
> ```js-jsx
> <Option {...item}  />
> ```

在ts下面这个该怎么添加额外props呢

**Comment by tylerrrkd** [comment]
Emmm html 5 dataset 属性

**Comment by iaminvictus1993** [comment]
antd select onChange 获取对象解决方法

**Comment by 98DE9E1F** [comment]
> 我可以在onChange里面获取到所有的自定义属性😱😱😱😱

但是 form 里的数据还是 value 的，没啥用
