### ISSUE TITLE
Form表单使用validateFields 动态校验规则控制台Console会不断的打印出错误信息

### ISSUE THREAD

**Issue by wenmine** [ant-design/ant-design#15588]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-register](https://ant.design/components/form-cn/#components-form-demo-register)

### Steps to reproduce
1. 打开F12开发者工具，切到Console
2.  先在确认密码输入框随意输入内容
3. 再去密码输入框随意输入内容 
4. 即可在console中看到一系列的错误信息

### What is expected?
期望的结果是不要在console中错误提示

### What is actually happening?
如果不停的输入，console中会不断的打印错误信息

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | v16.8.3 |
| System | win7 |
| Browser | Google Chrome V73.0.3683.86（正式版本） （64 位） |

---
因为打印出那么多的错误信息，有可能会给别人造成误解认为页面有问题。实际上页面是没有问题的。而且感觉输入内容容易卡顿。

**Comment by afc163** [comment]
> 感觉输入内容容易卡顿。

不打开 console 是不会影响性能的。

**Comment by afc163** [comment]
We should remove `console.error` in production mode.

https://github.com/react-component/form/blob/e4fa26f4282b23723c565889c4c04ebaf40a1d8f/src/createBaseForm.js#L576

**Comment by wenmine** [comment]
@afc163 好的谢谢~~目前我们暂时采用本地源码去掉这边的console.error。期待下一版本的更新。

**Comment by afc163** [comment]
重装 node_modules 即可。
