### ISSUE TITLE
Table missing Empty render when loading is true

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15582]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7w3k17q026)

### Steps to reproduce
Click switch to mock table start loading

### What is expected?
Empty should keep in the view

### What is actually happening?
Empty lose

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9069

现在用了 Empty 之后，#9069 就会有点问题。
