### ISSUE TITLE
关于 ant-form-item-no-colon 选择器位置的建议

### ISSUE THREAD

**Issue by HsuanXyz** [ant-design/ant-design#15585]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在一些使用声明式模板的框架中（如 Angular）或者仅使用 ant design 样式的原生项目中，往往希望选择器作用的样式位于当前标签上，比如 `.ant-form-item-required`：

```html
<label  class="ant-form-item-required">
  Label
</label>
```

而 `.ant-form-item-no-colon` 在现在的设计中 `3.15.1` 位于其父级，这使得其使用方式变得有些怪异:

```html
<div class="ant-form-item-label ant-form-item-no-colon">
  <!-- 都是为了控制 label 自身的样式，却要将 class 声明在不同的层级 -->
  <label class="ant-form-item-required">
    Label
  </label>
</div>
```

### What does the proposed API look like?
`.ant-form-item-no-colon` 与 `.ant-form-item-required` 在同一层级上。

**Comment by afc163** [comment]
可以的，不影响兼容性的话，移动一下就行，发个 PR 来好了。
