### ISSUE TITLE
默认选中了被禁用的日期时的选中样式优化

### ISSUE THREAD

**Issue by attacking** [ant-design/ant-design#15580]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对于日期选择组件，部分业务场景下，会碰到如下问题：
禁用日期为2.1至2.20，但数据回显时假如选中的是2.3号，那么2.3号这个日期不具备选中样式，依然是禁用样式。这会给使用者带来不便。
效果可见 https://codepen.io/yummy/pen/ZPqZRv 中第一个日期选择组件

期望：在这种场景下也给出选中样式。

### What does the proposed API look like?
无需api，调整样式即可。

**Comment by afc163** [comment]
<img width="306" alt="图片" src="https://user-images.githubusercontent.com/507615/54877457-16ea7c80-4e5a-11e9-8dbd-33e8119de91f.png">

改成这样。

**Comment by attacking** [comment]
感谢实现。
