### ISSUE TITLE
Typography.Text ellipsis not work when use native css ellipsis

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15581]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/455rqn437)

### Steps to reproduce
Open the link.

Since native css ellipsis need calculate the width of element. Text ellipsis without `copyable` or `editable` makes it use native css ellipsis. Which makes ellipsis failed.

### What is expected?
Ellipsis it

### What is actually happening?
Not ellipsis

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by Vsion** [comment]
i got a tslint, before code this comment
```
(JSX attribute) TextProps.ellipsis?: boolean
不能将类型“{ rows: number; }”分配给类型“boolean”。ts(2322)
Text.d.ts(4, 5): 所需类型来自属性 "ellipsis"，在此处的 "IntrinsicAttributes & TextProps & { children?: ReactNode; }" 类型上声明该属性
```

**Comment by afc163** [comment]
`ellipsis` works when set `max-width: 100%` to Text: https://codesandbox.io/s/new-breeze-nh9pr?file=/index.js

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/pull/30777
