### ISSUE TITLE
Table filters should support number as value

### ISSUE THREAD

**Issue by SmallPolaris** [ant-design/ant-design#15593]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/SmallPolaris/antd-table-bug](https://github.com/SmallPolaris/antd-table-bug)

### Steps to reproduce
yarn
启动项目，选择table的过滤

### What is expected?
table的filters能正常显示样式

### What is actually happening?
table的filters的样式错误

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.4 |
| System | windows10 |
| Browser | chrome73 |

---
在antd v3.10.1版本是正确的

**Comment by SmallPolaris** [comment]
经过实践之后，发现filters的value只能为String，否则filters的样式发生错误。希望能支持其他类型的value

**Comment by qzmer1104** [comment]
发现同样的问题，确实转成字符串解决，不过，你别关了啊，关了他们不修复了。

**Comment by SmallPolaris** [comment]
打开了

**Comment by SmallPolaris** [comment]
> 发现同样的问题，确实转成字符串解决，不过，你别关了啊，关了他们不修复了。

打开了

**Comment by SmallPolaris** [comment]
github 项目已经删除了，原因已经说明

**Comment by SmallPolaris** [comment]
> Hello @SmallPolaris. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @SmallPolaris, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

已经创建好了，请查看，谢谢！
https://codesandbox.io/embed/4lxyyx69nx
