### ISSUE TITLE
DatePicker设置style={{width:300}}显示诡异

### ISSUE THREAD

**Issue by chanjettp** [ant-design/ant-design#1559]
DatePicker设置style={{width:300}}显示诡异
有什么办法解决么

**Comment by afc163** [comment]
具体是如何诡异呢？

**Comment by chanjettp** [comment]
<Form inline>
        <FormItem inline  label="日期">
           <DatePicker style={{width:500}} />
        </FormItem>
      </Form>

Form只要用 inline 那么设置width后，日期输入宽还是很短，小图标跑老远

**Comment by chanjettp** [comment]
<Form inline>
        <FormItem inline  label="日期">
           <DatePicker style={{width:500}} />
        </FormItem>
      </Form>

**Comment by chanjettp** [comment]
`<Form inline>
        <FormItem inline  label="日期">
           <DatePicker style={{width:500}} />
        </FormItem>
      </Form>`

**Comment by chanjettp** [comment]
<Form inline>
        <FormItem label="日期">
           <DatePicker style={{width:500}} />
        </FormItem>
      </Form>

**Comment by chanjettp** [comment]
`<Form inline>
        <FormItem label="日期">
           <DatePicker style={{width:500}} />
        </FormItem>
      </Form>`
