### ISSUE TITLE
Select的多选框需要显示下拉箭头

### ISSUE THREAD

**Issue by xiewangmei** [ant-design/ant-design#15597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Select单选多选都有下拉箭头，都是下拉框，为何多选不提供下拉小箭头？

### What does the proposed API look like?
单选/多选select都可以通过showArrow控制是否显示下拉小箭头

**Comment by afc163** [comment]
It works: https://codesandbox.io/s/208w9wjk1y
