### ISSUE TITLE
关于select组件在搜索时希望能添加事件防抖

### ISSUE THREAD

**Issue by gitCoy** [ant-design/ant-design#15590]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在我们在select下拉中会显示1000条数据，在输入搜索的时候非常卡，这个功能只能在组件内部更改，所以在此提交一个issue

### What does the proposed API look like?
希望能在select组件在搜索时希望能添加事件防抖

**Comment by afc163** [comment]
可以直接对 onSearch 进行节流处理。

**Comment by afc163** [comment]
https://ant.design/components/select-cn/#components-select-demo-select-users

**Comment by gitCoy** [comment]
感谢！

**Comment by gitCoy** [comment]
您好，我发现这里不能解决我的问题，我实际的条件是在optionFilterProp，filterOption这个属性进行搜索过滤时希望能事件节流，上面的例子只是更新option时可以
