### ISSUE TITLE
在Select组件中没有利用到类型推断

### ISSUE THREAD

**Issue by helios741** [ant-design/ant-design#15595]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L112](https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L112)

### Steps to reproduce

```javascript
export interface SelectProps<T = SelectValue> extends AbstractSelectProps {
  value?: T;
  defaultValue?: T;
  mode?: 'default' | 'multiple' | 'tags' | 'combobox' | string;
  optionLabelProp?: string;
  firstActiveValue?: string | string[];
  onChange?: (value: T, option: React.ReactElement<any> | React.ReactElement<any>[]) => void;
  onSelect?: (value: T, option: React.ReactElement<any>) => any;
  onDeselect?: (value: T) => any;
  onBlur?: (value: T) => void;
  onFocus?: () => void;
  onPopupScroll?: React.UIEventHandler<HTMLDivElement>;
  onInputKeyDown?: (e: React.KeyboardEvent<HTMLInputElement>) => void;
  onMouseEnter?: (e: React.MouseEvent<HTMLInputElement>) => any;
  onMouseLeave?: (e: React.MouseEvent<HTMLInputElement>) => any;
  maxTagCount?: number;
  maxTagPlaceholder?: React.ReactNode | ((omittedValues: T[]) => React.ReactNode);
  optionFilterProp?: string;
  labelInValue?: boolean;
  tokenSeparators?: string[];
  getInputElement?: () => React.ReactElement<any>;
  autoFocus?: boolean;
  suffixIcon?: React.ReactNode;
  removeIcon?: React.ReactNode;
  clearIcon?: React.ReactNode;
  menuItemSelectedIcon?: React.ReactNode;
}
```
在antd的Select组件的代码中明确写了，`defaultValue?: T; value?: T;`
按理来说我们的defaultValue/value为我们指定的类型（比如说string）的话，在我们调用`onChange`方法的时候(antd中定义的onChange为`onChange?: (value: T, option: React.ReactElement<any> | React.ReactElement<any>[]) => void;`),应该第一个参数为我们在defaultValue/value中指定的值（应为string）。请看下面的代码：

```javascript
<Select
  defaultValue='dsdsd'
  onChange={(value: string) => this.onChange('memoryType', value)}
 >
     <Option value="M">MB</Option>
    <Option value="G">GB</Option>
 </Select>
```
会有下面的错误
![image](https://user-images.githubusercontent.com/12036324/54822996-6a858a80-4ce1-11e9-9957-0b03468c4105.png)

如果我不用any的话，我的代码就会变得比较恶心，如下：

```javascript
<Select
  style={{ width: 80 }}
  defaultValue={quota.memory.substr(quota.memory.length - 1) }
  // onChange={value => this.onChange('memoryType', value as string)}
  onChange={(value: SelectValue) => this.onChange('memoryType', value as string)}
>
  <Option value="M">MB</Option>
  <Option value="G">GB</Option>
</Select>

```

### What is expected?
onChange的第一个参数类型被推断为*defaultValue/value*指定的属性类型。

### What is actually happening?
onChange/onSelect的第一个参数类型一直都是`SelectValue`

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16 |
| System | mac |
| Browser | chrome |

---
我查了一下原因是因为你们在声明Select类的时候并没有用到类型推断，
antd是这样写的：

```javascript
export default class Select<T = SelectValue> extends React.Component<SelectProps<T>, {}>{
  constructor(props: SelectProps<T>);
}
```
上面希望被推断的T类型，一直没有使用所有就不可能被推断出来，就一直走的默认值`SelectValue`，所以以上代码和下面代码没什么区别：

```javascript
export default class Select  extends React.Component<SelectProps, {}>{
  constructor(props: SelectProps);
}
```

请尽快修复

**Comment by yesmeck** [comment]
正确的用法是：

```javascript
<Select<string> onChange={handleChange}>
```

**Comment by jiangxiaopeng** [comment]
> 正确的用法是：
> 
> ```js
> <Select<string> onChange={handleChange}>
> ```

还得是你
