### ISSUE TITLE
DatePicker does not auto-focus when label for associated input field is clicked

### ISSUE THREAD

**Issue by BrownCow371** [ant-design/ant-design#15596]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://31j05w402p.codesandbox.io/)

### Steps to reproduce
A label is associated with a Date Picker Component via the Date Picker id property. However, the id prop is not passed down to the input element on the Date Picker Component so clicking on the label does not change the focus to be inside the input for the Date Picker. For comparison, this functionality is working properly on the Time Picker Component. 

### What is expected?
The date picker input should be in focus when the label for the element is clicked. 

### What is actually happening?
The input is not in focus when the label for the element is clicked. 

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.8.2 |
| System | Windows 10 |
| Browser | Chrome Version 72.0.3626.121 (Official Build) (64-bit), Firefox 65.0.2 (64-bit), Microsoft Edge 42.17134.1.0,  IE11,  |

**Comment by afc163** [comment]
Sorry, in current interaction design we cannot implement this feature.
