### ISSUE TITLE
Layout does not render correctly if <div> positioned inside

### ISSUE THREAD

**Issue by neilyoung** [ant-design/ant-design#15606]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/neilyoung2512/pen/gEqXvG](https://codepen.io/neilyoung2512/pen/gEqXvG)

### Steps to reproduce
Launch the pen. 

### What is expected?
I would like to have the button inside the content

### What is actually happening?
it is outside

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.2 |
| System | all |
| Browser | all |

---
maybe this is a CSS thingy, but I can't figure it out

**Comment by afc163** [comment]
```css
  position: relative;
  top: 200px;
```

Your css code caused that, not antd's issue.

**Comment by neilyoung** [comment]
That’s true. But do you have a suggestion how to achieve that? The sample is just a break down of a problem I have. I need to have positioned divs in my design. What could make the antd-content spread in height so that it wraps the positioned div? Suggestion appreciated.

**Comment by neilyoung** [comment]
I think your design is not properly handling the case, when content is consisting of positioned divs. It works if all is placed straight forward.

**Comment by neilyoung** [comment]
So, yes. Ignore. Best option.
