### ISSUE TITLE
Collapse widget - default "open all"

### ISSUE THREAD

**Issue by deborah-ufw** [ant-design/ant-design#15604]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Collapse widget currently allows only one item to be default open.  This means most of the content is hidden on load.  Widget should have a default setting to load with all open.

### What does the proposed API look like?
`<Collapse defaultOpenAll={true} onChange={callback}>`

**Comment by ztplz** [comment]
You can open the submenu you want to open by setting `defaultOpenKeys` in `Menu`.  See [this example](https://codesandbox.io/s/6l984l4wxr).

**Comment by deborah-ufw** [comment]
Yes, but I want all to open, not just one.  Hence, the “open all” in the request title :)

**Comment by ztplz** [comment]
`defaultOpenKeys` is a list of keys for submenu that you want to open by default. If you want to open all submenu, you can set all submenu keys in `defaultOpenKeys`. If there are not too many submenu, I think it's easy to do. Adding an extra api is not a good choice if this is easily done with other apis.

**Comment by deborah-ufw** [comment]
That sounds like a good solution.  I will use it.  Thank you!

**Comment by devuxer** [comment]
Note for anyone who is trying to open all panels in a `Collapse` (as opposed all items in a `Menu`) at once:

This can be done with `defaultActiveKey`.

This property is incorrectly named `...Key` instead of `...Keys`, but it actually takes an **array** of strings, so you can specify as many keys as you need. If you list the key for every panel you have, you will effectively have "expand all".

cc. @afc163, I suggest adding `defaultActiveKeys` to the API and docs and deprecating `defaultActiveKey`.

**Comment by devuxer** [comment]
In case anyone is confused, `defaultOpenKeys` has a different name for the `CollapseWidget`: `defaultActiveKey` 

Unfortunately, it was named `...Key`, not `...Keys`, but it does accept an **array** of keys, so you can achieve "expand all" by listing the key for every collapse panel.

**Comment by orianmarx** [comment]
Although you can set `defaultActiveKey` to an array of keys, it seems this can only be used to initialize a Collapse component. If you want to create say an expand all / collapse all button functionality, you can set a dynamic react key like this to get the component to rerender whenever you change the array of expanded keys:
`<Collapse defaultActiveKey={expandedKeys} key={expandedKeys.join()}>`

**Comment by fadhlaouir** [comment]
if you want it to be allways open 
     <Collapse
            defaultActiveKey={['2']}
else 
     <Collapse
            defaultActiveKey={['1']}

**Comment by zhuangya** [comment]
> key={expandedKeys.join()}

why do i have to write this `key` prop on `<Collapse />`? this is strange and nonintuitive

**Comment by sealman234** [comment]
> Although you can set `defaultActiveKey` to an array of keys, it seems this can only be used to initialize a Collapse component. If you want to create say an expand all / collapse all button functionality, you can set a dynamic react key like this to get the component to rerender whenever you change the array of expanded keys: `<Collapse defaultActiveKey={expandedKeys} key={expandedKeys.join()}>`

Thanks, using the `key` prop on `<Collapse />` solved my problem. However, it's not very intuitive why I needed to use this prop.

**Comment by rr-juleshwar** [comment]
> Although you can set `defaultActiveKey` to an array of keys, it seems this can only be used to initialize a Collapse component. If you want to create say an expand all / collapse all button functionality, you can set a dynamic react key like this to get the component to rerender whenever you change the array of expanded keys: `<Collapse defaultActiveKey={expandedKeys} key={expandedKeys.join()}>`

Solved my problem, too. I don't get why this is expected though 🙃
