### ISSUE TITLE
Table 如何实现 纵向 功能

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#15601]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对于字段特别多又很细碎的表格，纵向显示更加友好

### What does the proposed API look like?
<Table vertical />

**Comment by tolerance-go** [comment]
是从数据角度，去做转换还是实现 CSS 更加方便？

**Comment by tolerance-go** [comment]
![image](https://user-images.githubusercontent.com/37258382/54860760-d73c6b80-4d59-11e9-9f65-dcdfc4c90a52.png)

**Comment by dengfuping** [comment]
@tolerance-go 
> 对于字段特别多又很细碎的表格，纵向显示更加友好

- 如果记录条数少且确定，应该对表数据进行转换；
- 如果记录条数多且不确定，纵向显示意义不大，横向滚动更好；

**Comment by tolerance-go** [comment]
https://codesandbox.io/s/ooxzj6134z

**Comment by afc163** [comment]
可以关注下：https://github.com/ant-design/ant-design/pull/14645
