### ISSUE TITLE
关于table固定表头实现方式的建议

### ISSUE THREAD

**Issue by lizuncong** [ant-design/ant-design#15605]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在业务中基本都要用到table固定表头的功能，但是目前的使用方式是通过传递诸如scroll = {{ y: 300 }}实现的。这就会遇到一个问题。比如我有一个页面，上面是伸缩框，下面是table组件，伸缩框是可以伸缩的。我希望的是不论伸缩框展开或者收起的状态下，table组件都要撑满屏幕并且表头固定。table组件撑满屏幕可以使用flex布局实现。如果要固定表头，就需要给table传递scroll.y值。在伸缩框收起或展开时，scroll.y的值是不同的，这就需要使用js计算scroll.y的值，我觉得是不合理的。目前我是通过使用一层容器包裹table，然后覆盖table的css来达到固定表头的。如下
   
      .ant-table-wrapper{
                    height: 100%;
                    .ant-spin-nested-loading{
                        height: 100%;
                        .ant-spin-container{
                            height: 100%;
                            .ant-table-fixed-header{
                                height: 100%;
                                .ant-table-content{
                                    height: 100%;
                                    .ant-table-scroll{
                                        height: 100%;
                                        display: flex;
                                        flex-direction: column;
                                        .ant-table-body{
                                            flex:1;
                                            max-height: unset !important;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

### What does the proposed API look like?
希望table固定表头的实现方式能够通过css解决，而不是让开发者去设置sroll.y的值。这个可以通过flex布局实现。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15340#issuecomment-471927481
