### ISSUE TITLE
table 伸缩宽度使用react-resiable效果不理想

### ISSUE THREAD

**Issue by dreamHeroK** [ant-design/ant-design#15618]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yvqjx67ky1)

### Steps to reproduce
根据列宽设置滚动。伸缩时只影响操作的列。

### What is expected?
表格宽度不超出时无滚动条，宽度超出有滚动条。伸缩时左右列的宽度无影响。

### What is actually happening?
滚动条始终存在，伸缩时左右列的宽度受到影响。

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.7 |
| System | mac |
| Browser | chrome 73.0.3683.86 |

**Comment by afc163** [comment]
https://codesandbox.io/s/4826jll91w

<img width="788" alt="image" src="https://user-images.githubusercontent.com/507615/54893990-73e64100-4ef3-11e9-9b08-afc55eb8c767.png">

**Comment by dreamHeroK** [comment]
@afc163  你给的这个例子伸缩时左右宽度和底部滚动条一直存在的问题都还存在。
![QQ20190325-151329](https://user-images.githubusercontent.com/23441508/54901206-b36f5600-4f10-11e9-8afc-5bb1d2b31582.gif)

**Comment by afc163** [comment]
比较蛋疼，想不到好办法。

**Comment by dreamHeroK** [comment]
@afc163  你试着参考下element的[table](https://github.com/ElemeFE/element-react/tree/master/src/table)

**Comment by afc163** [comment]
一样的。确切的说，两边的实现原理是一样的。

<img width="897" alt="image" src="https://user-images.githubusercontent.com/507615/54906703-ce48c700-4f1e-11e9-8f44-5e1aeda8bf41.png">

**Comment by afc163** [comment]
https://codesandbox.io/s/4826jll91w

```diff

.react-resizable-handle {
  position: absolute;
  width: 10px;
  height: 100%;
  bottom: 0;
- right: -5px;
+ right: 0;
  cursor: col-resize;
}
```
