### ISSUE TITLE
inline Menu component  flash and shake when collapsed 

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#15614]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ouzhou/pen/MxxgZQ?&editable=true&editors=001](https://codepen.io/ouzhou/pen/MxxgZQ?&editable=true&editors=001)

### Steps to reproduce
click the top primary blue button 

### What is expected?
menu collapsed with no flash

### What is actually happening?
shake and flash

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.x |
| System | win10 |
| Browser | chrome 72.0.3626.121（正式版本） （64 位） |

**Comment by afc163** [comment]
@zy410419243
