### ISSUE TITLE
固定列表格体滚动条被遮挡问题

### ISSUE THREAD

**Issue by AlwaysBeOk** [ant-design/ant-design#15619]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vvlv9n8r15)

### Steps to reproduce
左右滚动表格

### What is expected?
期望tbody的滚动条不被左右固定列遮挡

### What is actually happening?
tbody的滚动条被左右固定列遮挡，无法进行用鼠标拖动滚动条。

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.2.0 |
| System | mac os |
| Browser | firefox、chrome |

**Comment by afc163** [comment]
目前的实现做不到在所有操作系统和浏览器下不遮挡。但是在我的 Mac 电脑上是好的。

<img width="651" alt="image" src="https://user-images.githubusercontent.com/507615/54894056-cf183380-4ef3-11e9-8e62-a45f2f5e767d.png">

**Comment by AlwaysBeOk** [comment]
<img width="745" alt="gdt1" src="https://user-images.githubusercontent.com/23167192/54894210-7eeda100-4ef4-11e9-97dd-05c11d0914f9.png">
<img width="745" alt="gft2" src="https://user-images.githubusercontent.com/23167192/54894218-8614af00-4ef4-11e9-9408-0b23a8792be1.png">
<img width="743" alt="gdt3" src="https://user-images.githubusercontent.com/23167192/54894225-8dd45380-4ef4-11e9-80e6-f3e6e1a9f894.png">

**Comment by afc163** [comment]
如果是系统自动隐藏滚动条的设置，目前的实现做不到不遮挡。

**Comment by AlwaysBeOk** [comment]
不是系统自动隐藏滚动条，是左侧固定列定位问题遮挡了滚动条。 @afc163

**Comment by afc163** [comment]
如果是在系统自动隐藏滚动条的设置的情况下，`左侧固定列定位问题遮挡了滚动条` 这个问题目前的实现是无法解决的。
