### ISSUE TITLE
Tabs - Tabs组件在右侧有Input时 焦点在input上 使用键盘左右键 移动的是Tabs

### ISSUE THREAD

**Issue by Vicky-w** [ant-design/ant-design#15610]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/VRgXQK?&editable=true&editors=001](https://codepen.io/anon/pen/VRgXQK?&editable=true&editors=001)

### Steps to reproduce
1.点击鼠标在input上
2.在input内输入些内容
2.按鼠标左右键

### What is expected?
焦点在input文字间移动

### What is actually happening?
焦点在tab间移动

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | react |
| System | All |
| Browser | All |

**Comment by afc163** [comment]
https://codepen.io/anon/pen/draKbq?&editable=true&editors=001
