### ISSUE TITLE
User can remove cursor in the TreeSelect

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design#15615]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a TreeSelect component which treeCheckable=true filterTreeNode=false, but there is a cursor in the input which is easy for users to misunderstand that the component can search data, and actually it can't.

Demo oneline: [https://codepen.io/kwzm/pen/eXXYWb?editors=0010](https://codepen.io/kwzm/pen/eXXYWb?editors=0010)

### What does the proposed API look like?
I expect add a new prop `cursor` which value is boolean (default value is true), when I set false, there will be no cursor in the input.

**Comment by zombieJ** [comment]
`filterTreeNode=false` means not hide TreeNode if filter not match...Not means not searchable.

**Comment by kwzm** [comment]
@zombieJ Ok, I see, but my problem has not been solved, if I don't want cursor in the TreeSelect, how can I do that, or what do I do if I don't want the search function?

**Comment by zombieJ** [comment]
It's more like `showSearch` should do. Move into another issue: #15921
