### ISSUE TITLE
不要依赖@types包，这会导致tsc报错error TS2300: Duplicate identifier

### ISSUE THREAD

**Issue by gwuhaolin** [ant-design/ant-design#15627]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by ztplz** [comment]
能说下是哪个包吗？

**Comment by gwuhaolin** [comment]
@types/react

**Comment by ztplz** [comment]
重复的字符串是什么？
