### ISSUE TITLE
upload how use graphql ??  

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [ant-design/ant-design#15628]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---
怎么在上传组件 使用graphql 去做上传？ 

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by hqman** [comment]
antd apollo upload client 完美整合
```
  const handleRemove = (file) => {
    if (file) {
      const nextState = produce(images, draftState => {
        draftState.splice(file.index, 1);//删除 指定的file

      });
      setImages(nextState);
    }
  }
  const submit = () => {
    uploadMutate({
      variables: {
        fileIns: images
      }, update(cache, { data: { myUploads: { ok } } }) {
        if (ok) {
          setImages([]);
        }
      }
    })
  }
//render
      <UploadList listType="picture-card" items={items} locale={{ previewFile: '' }} onRemove={handleRemove} />
```

**Comment by jaisonjjames** [comment]
> The issue which is not created via http://new-issue.ant.design will be closed immediately.
> 
> 怎么在上传组件 使用graphql 去做上传？
> 
> 注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

Did you fund any solutions? if yes, please provide guidance.

**Comment by nbouliol** [comment]
@jaisonjjames I just did it by adding [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) like said [here](https://medium.com/@dilipkumar/graphql-and-file-upload-using-react-and-node-js-c1d629e1b86b)

**Comment by jaisonjjames** [comment]
> @jaisonjjames I just did it by adding [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) like said [here](https://medium.com/@dilipkumar/graphql-and-file-upload-using-react-and-node-js-c1d629e1b86b)

Thanks, Will try out
