### ISSUE TITLE
Antd3.x 的 Select 多选下拉框，下拉选项的数据量才500条左右，点击下拉就很明显卡顿好几秒，Antd2.x的是好的

### ISSUE THREAD

**Issue by ximenchuixue** [ant-design/ant-design#15620]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/ （把官方3.x的demo用500条记录测试就好）](https://ant.design/components/select-cn/ （把官方3.x的demo用500条记录测试就好）)

### Steps to reproduce
Select 多选下拉框，下拉选项的数据量才500条左右，点击下拉就很明显卡顿好几秒，下拉显示之后再去勾选，每勾选一下就卡顿好几秒

### What is expected?
500条记录的数据量在Antd2.x没这么明显，2.x的用起来还是很流畅的。请问为何3.x反而不如2.x？另外，使用React-select，2千条记录都很快的，是否Antd没有实现好？

### What is actually happening?
2千条下拉记录数据量，希望不要卡顿

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.6.0 |
| System | win10 |
| Browser | chrome  版本 74.0.3702.0（正式版本） （64 位） |

**Comment by zombieJ** [comment]
Merge into #3789

**Comment by afc163** [comment]
我们需要对比一下 2.x 和 3.x，理论上性能应该是一样的。

**Comment by ztplz** [comment]
3.x打了不少bugfix了

**Comment by ximenchuixue** [comment]
@afc163 用一个干净的页面实测下来，确实2.x的多选Select比3.x的好太多了，请排查原因哈

**Comment by afc163** [comment]
@ximenchuixue 来两个 http://u.ant.design/codesandbox-repro ~

**Comment by ximenchuixue** [comment]
@afc163 https://codesandbox.io/s/wpovnqxr5?fontsize=14 已建立demo，用1000条记录测试，操作起来卡顿

**Comment by ztplz** [comment]
确实3.x卡一点   2.13.14 vs latest

**Comment by ximenchuixue** [comment]
@ztplz 是的

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/54902439-5fff0700-4f14-11e9-983f-eeeff027b968.png)
 刚开始的时候 3.x 多了次莫名其妙的rerender

**Comment by zombieJ** [comment]
https://github.com/react-component/select/commit/dd4f367247bba6a72a82a4243aa1b96e343c82c0#diff-42c78aeee9cd69869523e9f9538de29cR124

看起来是迁移到新的生命周期，多搞了一次 forcePopupAlign 导致能耗翻倍了。

**Comment by ztplz** [comment]
这个应该是因素之一

**Comment by ztplz** [comment]
注释了快一点 但是还是比2.x慢

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/54907872-8b3c2300-4f21-11e9-861d-db73ba5e766d.png)
这个函数130ms的执行

**Comment by zombieJ** [comment]
@ztplz ,
嗯。拉了一下 timeline 发现主要还是因为现在 Select 的结构变复杂了。看下来主要时间都是 Icon render 的碎片时间：
<img width="1439" alt="屏幕快照 2019-03-25 下午5 52 00" src="https://user-images.githubusercontent.com/5378891/54910274-f3d9ce80-4f26-11e9-9e61-3ba61cd46d11.png">
<img width="1440" alt="屏幕快照 2019-03-25 下午5 51 17" src="https://user-images.githubusercontent.com/5378891/54910279-f6d4bf00-4f26-11e9-8873-7c05fe878862.png">

source： https://codesandbox.io/s/wkn60vr5j5 , https://codesandbox.io/s/yqvk7lol6j

**Comment by ximenchuixue** [comment]
所有Option可否统一拼接字符串最后再append进select里，然后对下拉层父节点做事件绑定，勾选的时候再事件冒泡进去，这样应该几千条记录级别的下拉项都不存在性能问题

**Comment by zombieJ** [comment]
> 所有Option可否统一拼接字符串最后再append进select里，然后对下拉层父节点做事件绑定，勾选的时候再事件冒泡进去，这样应该几千条记录级别的下拉项都不存在性能问题

它是在因为每个 item 相比以前都多了 3 层的 Icon render，还没到 UI commit 阶段。这种需要通过虚拟化来解决。
（其实一直都该虚拟化，只是没有做。这次换成 svg icon 正好性能显著下降了……）

**Comment by afc163** [comment]
Icon render 有优化空间么？加个 memo？

**Comment by zombieJ** [comment]
第一次渲染不行，之后应该可以通过在 Menu Item 调整 shouldComponentUpdate 跳过去。

**Comment by ztplz** [comment]
只能虚拟化  这次1000 下次还会来个10000条很卡的问题 没止境的

**Comment by ximenchuixue** [comment]
@zombieJ 原来如此

**Comment by ximenchuixue** [comment]
@ztplz 上万条以上的需求只能异步的方式来做，希望未来版本Select也提供异步接口的方案。但是2千以内的场景还是很多的，2千以内纯前端理论上就可以hold得住

**Comment by SmallPolaris** [comment]
为什么不能像List那样，支持Options用virtualization的方式来实现，那样就不会卡了

**Comment by zombieJ** [comment]
> 为什么不能像List那样，支持Options用virtualization的方式来实现，那样就不会卡了

嗯，开了一个 issue 来跟这件事

**Comment by ximenchuixue** [comment]
俺想问一下，用 react-virtualized 的话，如果多选下拉框已经勾选的选项，在上头输入框里删除某些项之后，再滚动到对应这些项的位置，他们是否也会显示成取消勾选的状态？

**Comment by ximenchuixue** [comment]
俺想问一下，用 react-virtualized 的话，如果多选下拉框已经勾选的选项，在上头输入框里删除某些项之后，再滚动到对应这些项的位置，他们是否也会自动显示成取消勾选的状态？

**Comment by zombieJ** [comment]
@ximenchuixue 换成虚拟滚动对用户是无感知的

**Comment by ximenchuixue** [comment]
@zombieJ 明白

**Comment by AsukaSong** [comment]
any progress on this?

**Comment by aweiu** [comment]
any progress on this?

**Comment by Zeus-Iqd** [comment]
我现在600多条很卡。

**Comment by afc163** [comment]
Please try antd@4.0.0, it improve Select perfermance in big data: https://ant.design/components/select/#components-select-demo-big-data

**Comment by xiaosongshua** [comment]
为啥这么卡？？？

**Comment by arthur657834** [comment]
antd3 是不改这个问题了吗， 1000条数据卡出天际啊

**Comment by zombieJ** [comment]
@arthur657834 ,
v3 已经过了维护期了，请升级到 v4。

**Comment by githbq** [comment]
selectRef.current.rcSelect.forcePopupAlign = () => {};
