### ISSUE TITLE
Mention 组件 safari 中文搜索导致网页崩溃

### ISSUE THREAD

**Issue by sundway** [ant-design/ant-design#15624]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oj8z9ozpo9)

### Steps to reproduce
1. 删除变量测试一
2. 切换为中文输入法，输入“这”，无法进行搜索。（项目中直接卡死）

### What is expected?
可正常进行搜索

### What is actually happening?
无法搜索，且可能会浏览器卡死

| Environment | Info |
|---|---|
| antd | 3.0.3 |
| React | 16.6.3 |
| System | mac 10.12.6 |
| Browser | safari |

**Comment by ztplz** [comment]
没复现成功  给个gif？

**Comment by sundway** [comment]
这里选择一个变量之后，删除到 $，搜索另一个变量无法搜索，回车无法选中。
![mention](https://user-images.githubusercontent.com/7138669/54977745-365be380-4fd9-11e9-8ed6-cfc85c0e4292.gif)

**Comment by sundway** [comment]
[mention.zip](https://github.com/ant-design/ant-design/files/3006890/mention.zip)

这是视频压缩文件

**Comment by zombieJ** [comment]
试试新的 Mentions 组件哈~
