### ISSUE TITLE
It is expected that the label can support the width definition. When the label of the field is on the left side, the display is incomplete.

### ISSUE THREAD

**Issue by yuanguandong** [ant-design/ant-design#15633]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When doing data-intensive applications, it is bound to put multiple fields (input, etc.), which may be four. At this time, when the label text of the business layer is too long, if only the labelCol response is used, it cannot be guaranteed. All, expect to be able to specify the width of the label, this attribute can be given to fortemem

### What does the proposed API look like?
Form.Item#
labelWidth

**Comment by afc163** [comment]
Try `labelCol`
