### ISSUE TITLE
Including upload component css severely degrades performance in IE 11

### ISSUE THREAD

**Issue by Patrik-Lundqvist** [ant-design/ant-design#15639]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction links
Simple table **including** upload component css
[https://s.codepen.io/patriklundqvist/debug/EMMXEB/ZorBaKPgqxqM](https://s.codepen.io/patriklundqvist/debug/EMMXEB/ZorBaKPgqxqM)

Simple table **excluding** upload component css
[https://s.codepen.io/patriklundqvist/debug/PLLJQo/LQMExKpBGwnk](https://s.codepen.io/patriklundqvist/debug/PLLJQo/LQMExKpBGwnk)

### Steps to reproduce
1. Open the link **including** upload component css in IE 11
2. Hover the mouse over many different rows

### What is expected?
<details><summary>Click to view screen capture</summary>
<p>

![vlx7TbK](https://user-images.githubusercontent.com/5230331/54923213-11e50600-4f0a-11e9-8973-6e826dc80fed.gif)

</p>
</details>

Smooth interaction, just like the reproduction link excluding the upload component css

### What is actually happening?
<details><summary>Click to view screen capture</summary>
<p>

![vvu2Wgu](https://user-images.githubusercontent.com/5230331/54922639-df86d900-4f08-11e9-9ea3-eefa32bf7a00.gif)
</p>
</details>

IE 11 will cause a layout render of the parent node and its children (the table in this instance). This happens for **every** component in the application if the upload component css is included. The UI becomes unresponsive and laggy if the node contains a large or complex tree, like this table.

By simply removing this css rule:
https://github.com/ant-design/ant-design/blob/0a5ffa8f9bb0c9cffb090a43b83c3213764bad59/components/upload/style/index.less#L354-L357

The whole application becomes much more responsive in IE. That css selector seems to trigger a bug in the IE layout engine. It should probably be re-written using a less complex selector.

**A temporary solution for people experiencing IE performance issues is to not import this file:** ```components/upload/style/index.css```

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.5 |
| System | Windows 10 |
| Browser | IE 11 |

**Comment by afc163** [comment]
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/507615/76618622-fbddb480-6563-11ea-8502-c80d820e4c28.png">

It works on antd v4.
