### ISSUE TITLE
动态表单渲染不对，数据没问题呀

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design#15647]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
地址: https://codepen.io/anon/pen/gEyMEW?editors=0010
const { Form, Input, Icon, Button, } = antd;

let id = 0;

class DynamicFieldSet extends React.Component {
  remove = (k) => {
    const { form } = this.props;
    // can use data-binding to get
    const keys = form.getFieldValue('keys');
    // We need at least one passenger
    if (keys.length === 1) {
      return;
    }
    console.log(keys.filter(key => key.id !== k))
    // can use data-binding to set
    form.setFieldsValue({
      keys: keys.filter(key => key.id !== k),
    });
  }

  add = () => {
    const { form } = this.props;
    // can use data-binding to get
    const keys = form.getFieldValue('keys');
    const nextKeys = keys.concat({
      names: '',
      id:   id
    });
    // can use data-binding to set
    // important! notify form to detect changes
    form.setFieldsValue({
      keys: nextKeys,
    });
  }

  handleSubmit = (e) => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        console.log('Received values of form: ', values);
      }
    });
  }

  render() {
    const { getFieldDecorator, getFieldValue } = this.props.form;
    const formItemLayout = {
      labelCol: {
        xs: { span: 24 },
        sm: { span: 4 },
      },
      wrapperCol: {
        xs: { span: 24 },
        sm: { span: 20 },
      },
    };
    const formItemLayoutWithOutLabel = {
      wrapperCol: {
        xs: { span: 24, offset: 0 },
        sm: { span: 20, offset: 4 },
      },
    };
    getFieldDecorator('keys', { initialValue: [
      {
        names: 1111,
        id: 0
      }
    ] });
    const keys = getFieldValue('keys');
    const formItems = keys.map((k, index) => (
      <Form.Item
        {...(index === 0 ? formItemLayout : formItemLayoutWithOutLabel)}
        label={index === 0 ? 'Passengers' : ''}
        required={false}
        key={k}
      >
        {getFieldDecorator(`names[${index}]`, {
          validateTrigger: ['onChange', 'onBlur'],
          rules: [{
            required: true,
            whitespace: true,
            message: "Please input passenger's name or delete this field.",
          }],
        })(
          <Input placeholder="passenger name" style={{ width: '60%', marginRight: 8 }} />
        )}
        {keys.length > 1 ? (
          <Icon
            className="dynamic-delete-button"
            type="minus-circle-o"
            disabled={keys.length === 1}
            onClick={() => this.remove(index)}
          />
        ) : null}
      </Form.Item>
    ));
    return (
      <Form onSubmit={this.handleSubmit}>
        {formItems}
        <Form.Item {...formItemLayoutWithOutLabel}>
          <Button type="dashed" onClick={this.add} style={{ width: '60%' }}>
            <Icon type="plus" /> Add field
          </Button>
        </Form.Item>
        <Form.Item {...formItemLayoutWithOutLabel}>
          <Button type="primary" htmlType="submit">Submit</Button>
        </Form.Item>
      </Form>
    );
  }
}

const WrappedDynamicFieldSet = Form.create({ name: 'dynamic_form_item' })(DynamicFieldSet);
ReactDOM.render(<WrappedDynamicFieldSet />, mountNode);

### What is expected?
How to do it?

### What is actually happening?
渲染不对
![image](https://user-images.githubusercontent.com/23191825/54969410-f97ff480-4fb8-11e9-99ea-d83ecb4b6f11.png)

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | latest |
| System | windows |
| Browser | Google Chrome |

**Comment by afc163** [comment]
请给详细重现步骤，看不懂你想表达的是什么。

**Comment by zheng1013757145** [comment]
不好意思，点击任意位置的删除的，他总是会删除最后一个 ，但是我看过滤后的数据没问题

**Comment by afc163** [comment]
https://codepen.io/anon/pen/gEyLbQ?editors=0011

key 写错了。

**Comment by zheng1013757145** [comment]
并不是这个k的问题

添加一项
![image](https://user-images.githubusercontent.com/23191825/54980964-21d01900-4fe2-11e9-9233-f3b2568c29b5.png)

删除一项
![image](https://user-images.githubusercontent.com/23191825/54980980-30b6cb80-4fe2-11e9-943e-9b5b52373ad0.png)

比如我添加一项内容，我删除的时候这个值始终是空的

**Comment by zheng1013757145** [comment]
导致的情况是 ， 我前面输入的值，会因为我删除了任何一项，都会造成所有数据会清空
![image](https://user-images.githubusercontent.com/23191825/54981185-a58a0580-4fe2-11e9-8b38-28c9b7f28d32.png)

**Comment by afc163** [comment]
请给重现。

**Comment by zheng1013757145** [comment]
https://codepen.io/anon/pen/mogqjE?editors=0011
好多问题

**Comment by afc163** [comment]
key 要唯一且稳定，不要用 index 做 key，请演习 React key 的概念。https://reactjs.org/docs/lists-and-keys.html

**Comment by zheng1013757145** [comment]
> key要唯一且稳定，不要用index做键，请演习React key的概念[.https：](https://reactjs.org/docs/lists-and-keys.html) //reactjs.org/docs/lists-and-keys.html[](https://reactjs.org/docs/lists-and-keys.html)

听君一席话,胜读十年书 谢谢

**Comment by hqman** [comment]
> https://codepen.io/anon/pen/mogqjE?editors=0011
> 好多问题

@afc163  请教一下，这个动态表单初始化是有数据的， 但是提交时候 validate 还是有错误提示 这怎么解决?

**Comment by hqman** [comment]
@afc163  你好这个例子 https://codepen.io/anon/pen/mogqjE?editors=0011 为什么已经有数据了，但提交validate还是验证不通过？
