### ISSUE TITLE
row 支持设置子元素中全部 col 的默认值

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design#15643]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
只需要 row 配置一次就可以了，不需要重复配置。

### What does the proposed API look like?
类似于 form 中的 wrapperCol。实现方法类似。

```react
 <Row wrapperSpan={8}>
      <Col>
        <p>
          品牌名称：<span>{brandName}</span>
        </p>
      </Col>
      <Col>
        <p>
          客户类型：<span>{brandName}</span>
        </p>
      </Col>
    </Row>
```

```
 <Row>
      <Col span={8}>
        <p>
          品牌名称：<span>{brandName}</span>
        </p>
      </Col>
      <Col span={6}>
        <p>
          客户类型：<span>{brandName}</span>
        </p>
      </Col>
    </Row>
```

**Comment by DiamondYuan** [comment]
上下等价。

**Comment by DiamondYuan** [comment]
可以的话我来实现吧

**Comment by afc163** [comment]
不要这样。类似需求可以按 https://github.com/ant-design/ant-design/issues/7309#issuecomment-470050192 的 API 来解决。
