### ISSUE TITLE
antd升级后card样式错误

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#15646]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/ywrJRq?&editable=true&editors=001](https://codepen.io/mraiguo/pen/ywrJRq?&editable=true&editors=001)

### Steps to reproduce
如图所示，以前用旧版本的时候按照这种方式布局，最近升级了antd，发现布局有点乱了，垂直不居中了。后来发现是antd之前有个pr把Card组件的overflow: hidden；给删除了，导致没有形成BFC，块互相干扰了。

### What is expected?
正常布局。

### What is actually happening?
布局异常，垂直不居中

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | react16 |
| System | win10 |
| Browser | chrome |

---
正常我们自己加这个属性overflow也能正常。但是希望能告知为什么要删除这个属性，是有什么副作用吗？如果没有是否考虑加上？

**Comment by afc163** [comment]
`overflow: hidden` 会导致内部弹出层元素被隐藏的副作用，本身不应该有。Card 是默认的 div block 布局，没有考虑用户修改 `inline-block` 或其他布局的场景，这边建议自行加上 overflow 或者 `vertical-align`（更合理？）。
