### ISSUE TITLE
Tree组件, 节点drag过程中, 阻止触发loadData. 

### ISSUE THREAD

**Issue by ziChen0422** [ant-design/ant-design#15644]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7n9mq46w9)

### Steps to reproduce
onDrop = info => {
    info.event.preventDefault();
    info.event.stopPropagation();
  };

在drag过程中, 如何阻止loadData触发. 

### What is expected?
期望: 在同级之间拖动,不想触发展开
能阻止触发loadData操作

### What is actually happening?
无法阻止loadData触发和展开

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.2.0 |
| System | Max OS |
| Browser | chrome  72.0.3626.121 |

**Comment by zombieJ** [comment]
可以使用 `loadedKeys` 属性。

**Comment by ziChen0422** [comment]
sorry, 但是并不能阻止触发onLoad方法.
dragStart的保存loadedKeys,  dragEnd的时候恢复loadedKeys。onDrop过程中阻止冒泡事件
结果: 
   在拖拽释放鼠标的时候, 依旧会触发onLoad方法.

**Comment by zombieJ** [comment]
开始拖拽的时候，把所有节点都加入 loadedKeys。
