### ISSUE TITLE
表格分页页码激活项为中文

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#15645]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://xxx.com](http://xxx.com)

### Steps to reproduce
无 

### What is expected?
显示数字

### What is actually happening?
显示中文
![image](https://user-images.githubusercontent.com/29935583/54968192-c8052a00-4fb4-11e9-91de-e1f7abdb3871.png)

| Environment | Info |
|---|---|
| antd | 3.10.10 |
| React | 16.5.0 |
| System | win 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12925#issuecomment-435578106

**Comment by steady-join** [comment]
偶然出现的，用了这么久了，还第一次碰见，实在是无法提供链接，是不是antd国际化原因导致了？翻译出来就会有
