### ISSUE TITLE
React v15 不会给纯文本套 span 标签，造成样式没有应用

### ISSUE THREAD

**Issue by blade254353074** [ant-design/ant-design#1564]
# React v14

![效果](https://cloud.githubusercontent.com/assets/9346008/14942577/4c868de6-0ff3-11e6-83a1-e78f4e100a7a.png)

![DOM 结构](https://cloud.githubusercontent.com/assets/9346008/14956708/b8fb11d4-10b3-11e6-87f6-9d73eace8f43.png)

样式是这样的：

```css
.ant-checkbox+span {
  margin-left: 8px;
}
```

# React v15

![效果](https://cloud.githubusercontent.com/assets/9346008/14942581/7b0d5cda-0ff3-11e6-8d5d-86349a34744c.png)

![DOM 结构](https://cloud.githubusercontent.com/assets/9346008/14956720/cf7c508a-10b3-11e6-800e-fd91846f419d.png)

建议给 text 套一层 span 而不是让 react 自己管理

**Comment by afc163** [comment]
这个问题应该已经修复过了。

**Comment by afc163** [comment]
#1340

**Comment by blade254353074** [comment]
谢啦
