### ISSUE TITLE
from 使用 mapPropsToFields 时,  类型检查不能通过

### ISSUE THREAD

**Issue by angular-moon** [ant-design/ant-design#15642]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
重现链接是antd官网的示例, 改写为typescript版本类型检查不能通过

### What is expected?
修复返回类型的声明

### What is actually happening?
typescript 类型检查不匹配

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.0 |
| System | macos |
| Browser | chrome 版本 73.0.3683.86（正式版本） （64 位） |

**Comment by angular-moon** [comment]
重现实例:
https://codesandbox.io/s/53zw9o0w64

**Comment by afc163** [comment]
https://codesandbox.io/s/6y177k7nyk

**Comment by angular-moon** [comment]
```tsx
interface UserFormProps extends FormComponentProps {
  onChange: Function;
  username: { [key: string]: any };
}

const UserForm: React.SFC<UserFormProps> 
```
我的意思是, UserForm 并不需要 onChange 和 username
Form.create 也不应该把2个props传递下去, 所以不应该在UserFormProps上声明这2个prop
可不可以通过Form.create<Props> 设置返回组件的Props
不知道我的理解对不对

**Comment by yesmeck** [comment]
https://codesandbox.io/s/l9v6w8k3ml

**Comment by yesmeck** [comment]
`CustomizedForm` 的 props 类型是自动推导出来的，如果 `CustomizedForm` 的 props 要跟 `UserForm` 的 props 不一样，现在只能这么写。

**Comment by angular-moon** [comment]
好的, 谢谢, 后续的版本会修改吗? mixin Form.create<T>

**Comment by afc163** [comment]
先关了，欢迎继续讨论。

**Comment by yesmeck** [comment]
后续 Form 的 API 改成 Hook 版本的话就不需要有个中间组件 `CustomizedForm` 存在了。
