### ISSUE TITLE
Slider onAfterChange is not triggered, when moving slider with arrows

### ISSUE THREAD

**Issue by tylik1** [ant-design/ant-design#15640]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xl3mkl98mw)

### Steps to reproduce
Move slider with mouse to verify that  onAfterChange is triggered
Move slider with arrow keys to verify that onAfterChange is not triggered

### What is expected?
onAfterChange should be triggered not only on mouseup, but also on arrow change (keyup)

### What is actually happening?
onAfterChange is only triggered on mouseup

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | React |
| System | os x |
| Browser | Chrome |

---
Maybe is is possible to trigger change on blur somehow? This possibly could be a solution

**Comment by ztplz** [comment]
Why not use `onChange`? Actually the trigger timing of both of them is similar.

**Comment by tylik1** [comment]
`onChange` triggers when mousedrag is in progress, leading to many unnecessary calls. `onAfterChange` works fine, but it's useless if keyboard behavior is enabled.

**Comment by ztplz** [comment]
Got it. Thanks for your explanation.
