### ISSUE TITLE
DatePicker受控面板点击年份选择不生效

### ISSUE THREAD

**Issue by sdark1326632** [ant-design/ant-design#15659]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oxo7wqr975)

### Steps to reproduce
1.选择 RangePicker 组件，打开面板
2.点击年份title
3.随便选择某年某月

### What is expected?
界面上会选择对应的年月

### What is actually happening?
1.面板没变化
2.onChange的value也没变化

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.5.2 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
RangePicker 的交互只有点击日期才会触发 onChange，修改 mode 只是修改了展现的面板，不会改变这个默认交互。你可以监听 onPanelChange 并自行封装 MonthRangePicker。

**Comment by afc163** [comment]
点击年份这个面板没变化貌似确实有问题，可以排查一下。

**Comment by afc163** [comment]
#10330 同一个问题，合并到这里。

**Comment by fanlei1988** [comment]
请问一下，这个问题 最后解决了么？

**Comment by xchunzhao** [comment]
https://github.com/react-component/calendar/pull/595 
要等ant-design这边发版本
