### ISSUE TITLE
Icon icon appears two

### ISSUE THREAD

**Issue by Gamehu** [ant-design/ant-design#15657]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
After updating to the latest version

### What is expected?
the Message icon just one

### What is actually happening?
After updating to the latest version, the Message icon will become two (up and down)

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.3.1 |
| System | win10 |
| Browser |  72.0.3626.121 |

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/54981360-0f0a1400-4fe3-11e9-97d2-ac9c51160a3f.png)

**Comment by afc163** [comment]
检查是否加载了新老两个版本的 antd 样式。

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/54981471-50022880-4fe3-11e9-97de-6a2f371d690a.png)

我删了所有models，清空了npm 缓存，然后重新装了一遍还是一样的

**Comment by afc163** [comment]
检查控制台，看看样式从哪来的。

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/54981865-57760180-4fe4-11e9-8034-7ddd6bedf752.png)

**Comment by afc163** [comment]
你需要自己排查一下。

**Comment by Gamehu** [comment]
嗯 我看到了 有一个::before

**Comment by Gamehu** [comment]
这证明是加载了两个样式吗？

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/54981993-aa4fb900-4fe4-11e9-86f2-e683cdc51ed9.png)

**Comment by afc163** [comment]
一定是这个问题。

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/54982027-c05d7980-4fe4-11e9-8e36-f6ee9cdd2b58.png)

**Comment by Gamehu** [comment]
怎么避免呢。。您有好的方法吗。。我都删了重新来一遍了。。还这样

**Comment by Gamehu** [comment]
我看了 还是从ant.min.css来的

**Comment by afc163** [comment]
<img width="873" alt="image" src="https://user-images.githubusercontent.com/507615/54982144-031f5180-4fe5-11e9-8648-77ea4c5d96a2.png">

看看这个 antd.min.css 是哪里引用的？

**Comment by Gamehu** [comment]
![image](https://user-images.githubusercontent.com/10043320/54982237-50032800-4fe5-11e9-9472-091293ad5a6e.png)

**Comment by afc163** [comment]
你要自己排查。。。你截给我毫无意义。。

**Comment by chenshuai2144** [comment]
这个是从哪里加载的 是不是你在html里面写死的
npm 安装的不会显示的为antd.css

**Comment by afc163** [comment]
你看看是不是引用的 antd.min.css 的版本和你的 antd 版本是不匹配的。

**Comment by Gamehu** [comment]
我以为你要看。。。嗯 我正在查

**Comment by Gamehu** [comment]
> 这个是从哪里加载的 是不是你在html里面写死的
> npm 安装的不会显示的为antd.css

我看到确实有同事 直接在文件里用了ant的样式。。

**Comment by afc163** [comment]
- [x] 你看看是不是引用的 antd.min.css 的版本和你本地安装的 antd 版本是不匹配的。
- [x] 引用了新老两份 antd 的样式。

都是这两个原因，好好排查一下吧。
