### ISSUE TITLE
Select support options/data prop

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15653]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
To improve the perf of Select, we may add virtual list to handle this.
Let's add `options` or `data` like `treeData` in TreeSelect.

ref: #15620 #3789

### What does the proposed API look like?
```jsx
<Select options={[]} />
```

**Comment by ztplz** [comment]
react-window弄进来吧  再牺牲下一些功能

**Comment by zombieJ** [comment]
> react-window弄进来吧 再牺牲下一些功能

antd 需要处理一些过渡动画，react-window 和 react-virtualized 都不能满足需求。rc-tree 里有个 branch 在搞支持 rc-animate 的虚拟滚动。做完了会抽出来。

不过略忙，放了半年多……

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/54978882-88eacf00-4fdc-11e9-96c4-57137f379ff9.png)
标题typo了

**Comment by DiamondYuan** [comment]
有进展么

**Comment by afc163** [comment]
Supported in v4 now: https://ant.design/components/select/#components-select-demo-big-data
