### ISSUE TITLE
checkbox的一个bug

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#1565]
1.仅有两个节点一父一子的场景下，当选中子节点的时候会自动连带父节点，导致无法单独选择这个子节点，也无法保留父节点且取消这个只节点，一父多子的场景下则没有这个问题。
2.通过参数传递一个子节点的key或者父节点的key时，check框无法识别，显示为未选择状态。

**Comment by dyf2015** [comment]
tree组件的bug

**Comment by afc163** [comment]
1. `checkStrictly` https://github.com/react-component/tree 。antd 文档中没写。
2. 最好给 codepen demo。确认是使用了 `checkedKeys` 参数。

**Comment by dyf2015** [comment]
1、好的，我研究下
2、是使用checkedKeys 参数

**Comment by afc163** [comment]
麻烦提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by dyf2015** [comment]
问题2是我自己程序BUG，确定没问题，谢谢！

**Comment by dazhangyu0808** [comment]
一父多子父节点半选的情况下，如何使父节点的值也被写入？
![qq 20161202171432](https://cloud.githubusercontent.com/assets/24312170/20828509/d2b1b75c-b8b2-11e6-93e9-f9ef489539f9.png)
