### ISSUE TITLE
<Input /> 可以增加一个延迟触发change的属性/方法吗？

### ISSUE THREAD

**Issue by CharlesMoone** [ant-design/ant-design#15651]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
例如我在input中输入一些数据，但是我不希望立刻触发change进行更新，而是希望等待部分时间后进行更新 （节流/防抖）

### What does the proposed API look like?
`<Input delayChange={e => this.setState({ x: e.target.value })} delayTime={500} />` 
or
`<input onChange={e => this.setState({ x: e.target.value })} delayTime={500} />`

**Comment by chenshuai2144** [comment]
你可以通过loadsh.debounce 包装onchange 方法来去抖，antd本身只是ui组建，并不会增加这个

**Comment by chenshuai2144** [comment]
code 
```
onChange=debounce(()=>{
 // do something
})
render(){
return <input onChange={this.onChange}/>
}
```

**Comment by WangGuangCheng2018** [comment]
> code
> 
> ```
> onChange=debounce(()=>{
>  // do something
> })
> render(){
>     return <input onChange={this.onChange}/>
> }
> ```

大佬，这个方法我试了一下。防抖成功了，但是e参数传过来已经不对了
`
onChange = debounce( (e) => {
    console.log('event', e);
  },500);
`

**Comment by CharlesMoone** [comment]
onchange = e => debounce(...);

**Comment by GrayFrost** [comment]
This article may help you.
https://medium.com/@platonish/debouncing-functions-in-react-components-d42f5b00c9f5

**Comment by huangyiming9228** [comment]
`
onChange = (e) => {
      const { value } = e.target;
      this.debounceSearch(value);
  }

debounceSearch = debounce((value) => {
     console.log(value)
}, 800);

`

**Comment by WangGuangCheng2018** [comment]
@huangyiming9228 就是这个，真棒！

**Comment by Zhaojing0987** [comment]
@chenshuai2144 请问AutoComplete不支持debounce吗？
![image](https://user-images.githubusercontent.com/29828346/61522363-d637f400-aa44-11e9-908a-8dfb02a67eaa.png)
使用debounce后会延迟执行，但并没有去抖，会执行所有的

**Comment by WangGuangCheng2018** [comment]
![1563761573(1)](https://user-images.githubusercontent.com/35524901/61601725-5179ef80-ac69-11e9-8d5b-a533cf21361e.png)

@Zhaojing0987 像这样，在constructor中添加debounce

**Comment by Zhaojing0987** [comment]
@WangGuangCheng2018 这样写成功了，谢谢！

**Comment by WangGuangCheng2018** [comment]
@Zhaojing0987 客气啦

**Comment by mixj93** [comment]
My solution:

```jsx
<Input onChange={handleChange} />
```

```js
const deplayedChange = debounce((value) => {
  // do something...
}, 500);

const handleChange = (event) => {
  deplayedChange(event.target.value);
};
```
