### ISSUE TITLE
Mention 组件 safari 变量前无法输入

### ISSUE THREAD

**Issue by sundway** [ant-design/ant-design#15656]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oj8z9ozpo9)

### Steps to reproduce
1. 输入 $ ，选择变量。
2. 将光标移到变量前，切换问中文输入法，无法输入文字

### What is expected?
变量前可以输入其他文字。

### What is actually happening?
变量前无法输入其他文字。

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 3.0.3 |
| System | 16.6.3 |
| Browser | mac 10.12.6 |

**Comment by ztplz** [comment]
还是没复现成功  你什么输入法

**Comment by sundway** [comment]
自带的输入法
![image](https://user-images.githubusercontent.com/7138669/54980128-e5032280-4fdf-11e9-83ed-e5bdeb0e5f5f.png)

**Comment by GFwer** [comment]
录了个gif，不知道是不是这种情况，具体表现为为界面上输入会被清空
![img](https://user-images.githubusercontent.com/14303098/56880853-eddc8d80-6a90-11e9-9dfd-ece6c1665edb.gif)

**Comment by zombieJ** [comment]
试试新的 Mentions 组件哈~
