### ISSUE TITLE
set style={width : 170} on DatePicker with props showTime={true}  can not work

### ISSUE THREAD

**Issue by mingzepeng** [ant-design/ant-design#15661]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/5xq35v1rxl)

### Steps to reproduce
```
import React from "react";
import ReactDOM from "react-dom";
import { version, Button, DatePicker } from "antd";
import "antd/dist/antd.css";

class App extends React.Component {
  render() {
    return (
      <div className="App">
        <h1>DatePicker with props showTime={"{true}"}</h1>
        <div>
          <p>
            set style={"{width : 200}"},the width of DatePicker is 200, is ok{" "}
          </p>
          <DatePicker
            showTime
            placeholder="my real width is 200"
            style={{ width: 200 }}
          />
        </div>
        <br />
        <br />
        <br />
        <p>
          set style={"{width : 170}"},the width of DatePicker is 195, is error{" "}
        </p>
        <DatePicker
          showTime
          placeholder="my real width is 195"
          style={{ width: 170 }}
        />
      </div>
    );
  }
}
ReactDOM.render(<App />, document.getElementById("root"));


```

### What is expected?
set style={width : 170} on DatePicker with props showTime={true} ,the width of DatePicker  will be 170px

### What is actually happening?
set style={width : 170} on DatePicker with props showTime={true} ,the width of DatePicker  is 195px now 

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.4.0 |
| System | windows 10 |
| Browser | chrome73.0.3683.86 |

**Comment by afc163** [comment]
https://codesandbox.io/embed/5xq35v1rxl

https://github.com/ant-design/ant-design/issues/15545
