### ISSUE TITLE
getFieldError doesn't return correct error message when field onchange event first trigger

### ISSUE THREAD

**Issue by TabrisK** [ant-design/ant-design#15665]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.jiedai361.com/#/sign/up.html](https://www.jiedai361.com/#/sign/up.html)

### Steps to reproduce
1. Input 手机号(登录账号) field with 1 character(输入一个字符);
2. Input the same field with 1 character continually(再输入一个字符).

### What is expected?
show error message when inputing first character.

### What is actually happening?
Error message doesn't appear until inputing second character.

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.2.0 |
| System | macOS Sierra 10.12.6 |
| Browser | Google Chrome 72.0.3626.121 |

**Comment by conioX** [comment]
any new about this?
