### ISSUE TITLE
MonthPicker默认面板日期是有值的，文档显示默认是空

### ISSUE THREAD

**Issue by webzlb** [ant-design/ant-design#15662]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
<MonthPicker />

### What is expected?
默认没有月份高亮

### What is actually happening?
默认有高亮

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.3.1 |
| System | 3.4.1 |
| Browser | google |

**Comment by afc163** [comment]
面板是高亮默认当前日期，默认已选择的是空，没有问题。
