### ISSUE TITLE
Card with extra Button should keep same title height

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15668]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5z35wq5j34)

### Steps to reproduce
Card with extra Button.

### What is expected?
Same height

### What is actually happening?
Different height

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

---
和设计师同步了一下，Card 里附带标准大小按钮高度应该不变。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/39646
