### ISSUE TITLE
Theme Customization Not Working

### ISSUE THREAD

**Issue by iancdma** [ant-design/ant-design#15663]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v6vwyovrn5)

Please refer to this repo for the actual project: https://github.com/iancdma/antd-demo

### Steps to reproduce
All steps in https://ant.design/docs/react/use-with-create-react-app..

1. npm create react-app antd-demo
2. import {Button} from 'antd' and use in App.js
3. yarn add react-app-rewired customize-cra
4. /* package.json */
"scripts": {
-   "start": "react-scripts start",
    "start": "react-app-rewired start",
-   "build": "react-scripts build",
    "build": "react-app-rewired build",
-   "test": "react-scripts test",
    "test": "react-app-rewired test",
}
5.  yarn add babel-plugin-import
6. yarn add less less-loader
7. 
  const { override, fixBabelImports, addLessLoader } = require('customize-cra');

module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
-   style: 'css',
    style: true,
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { '@primary-color': '#1DA57A' },
  }),
);

### What is expected?
Green button

### What is actually happening?
Unstyled button

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.2. |
| System | Windows 10 64-Bit |
| Browser | Chrome Version 73.0.3683.86 (Official Build) (64-bit) |

---
I cloned your Github repo, `creact-react-app-antd`, and overriding works. The thing is, the packages there are outdated. Please update that project or help me with a fix, thanks! :D

**Comment by afc163** [comment]
```diff

const { override, fixBabelImports, addLessLoader } = require("customize-cra");

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
-   style: "true"
+   style: true
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { "@primary-color": "#1da57a" }
  })
);
```

**Comment by iancdma** [comment]
Thanks a lot 👍 It works now. Can't believe I never noticed that. One problem is, when overriding `primary-color`, it does not override the buttons' colors. What's causing the issue?

**Comment by summmmer** [comment]
有同样的问题，官方的例子不生效
