### ISSUE TITLE
是否可以提供组件的 Sketch 设计文件

### ISSUE THREAD

**Issue by angelathewebdev** [ant-design/ant-design#1566]
这样的话设计师排版的时候会比较方便～

目前在你们的官网上也只有找到一个 UX 类的设计文件。如果能够提供一版组件的话最好不过了

**Comment by Tinker404** [comment]
同希望能出

**Comment by Chinglik** [comment]
目前我们内部开发了一个资源共享工具，未来对外开放你们就能看到并且可以下载使用我们的组件了，到时候我们会对外公布消息，感谢大家的关注哈。
