### ISSUE TITLE
日期选择框 DatePicker  bug    "version": "0.12.16"

### ISSUE THREAD

**Issue by jiehe** [ant-design/ant-design#1567]
"version": "0.12.16"

日期选择框 `DatePicker`  对象并没有像文档描述的提供 `value`属性。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/JXeaGN?editors=001

貌似是有的。如果遇到问题，最好提供可重现的演示，否则难以确认问题。

**Comment by jiehe** [comment]
@afc163   
日期选择框 DatePicker `对象`没有`value`属性。
[http://codepen.io/combine/pen/ZWwjLR?editors=0011](http://codepen.io/combine/pen/ZWwjLR?editors=0011)

上个星期写个业务遇到这个的问题，现在已经解决。
