### ISSUE TITLE
Typography support Tooltip title

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15670]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codesandbox.io/s/xzrm2m19vp

Currently Typography with Tooltip and hover on the copy button will get 2 tooltip.
It should support by Typography

### What does the proposed API look like?
```jsx
<Paragraph tooltip="..." />
```

**Comment by afc163** [comment]
`StopPropagation` 就够了，这个新 API 可以直接用来代替 Tooltip，重复了。

**Comment by zombieJ** [comment]
讨论下来，tooltip 场景略重，还是推荐使用更轻的原生 title 来实现。对于强需求的文本，推荐使用 展开 按钮做额外内容展示。
