### ISSUE TITLE
table表格对齐

### ISSUE THREAD

**Issue by FuSimei** [ant-design/ant-design#15678]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header](https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header)

### Steps to reproduce
https://ant.design/components/table-cn/#components-table-demo-grouping-columns，ant-design中的这个例子表头和内容列也没有对齐。
我的需求也是：需要展示大量数据，然后用户可以滚动查看，表格列太多，所以我固定了开头和结尾最后两列。
经过公司其他人确认，我也没有覆盖表格其他样式。我猜想可能是表格中有的列内容过长，表格没有自动换行造成的。
我试了word-break等有关换行 的属性，并没有解决问题

### What is expected?
期望表头和内容列能正常对齐展示

### What is actually happening?
（1）表头和内容列并没有正常对齐，而且不仅仅是错位了一点点。
（2）参照这个https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header写出来的例子，在小屏幕下表格头最右边固定列前面一点点有留空列，猜想是因为左边的固定列固定布局fixed宽度比下面的表格宽度要大

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | create-react-app |
| System | windows/mac均不好使 |
| Browser | chrome |

---
因为这个问题已经找了公司比较厉害的很多人看，还是没有解决，故此向您提出问题，期待您的回信。

**Comment by afc163** [comment]
1. 固定列需要设定 width。
2. scroll.x 需要设置合适的值，如果你不知道啥是合适的值，可以无脑 `scroll={{ x: 'max-content' }}`
3. 确保没有过长的连续英文/数字打破布局。

**Comment by FuSimei** [comment]
1.https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header，参照此例，
 const columns = [{
            title: 'column1',
            dataIndex: 'job_id',
            width: 80,
            fixed: 'left',
            sorter: true,
        }, {
            title: 'column2',
            dataIndex: 'job_name',
            sorter: true,
        }, {
            title: 'column3',
            dataIndex: 'job_username',
            width: 100,
            sorter: adminVal && true,
        }, {
            title: '队列',
            dataIndex: 'job_queue',
            width: 115,
            sorter: true,
        }, {
            title: '状态',
            dataIndex: 'job_status',
            width: 110,
            sorter: true,
            render: (val) => <Badge status={statusMap[val]} text={val} />
       }]

<Table  
                        dataSource={dataSource}
                        columns={columns}
                        rowSelection={this.handleSelectRow}
                        rowKey="job_id"
                        bordered
                        pagination={pagination} 
                        onChange={this.handleTableChange}
                        // scroll={{ x: 1647 }}
                        scroll={{ x: 1700, y: 530 }}
                        rowClassName={this.addRowClassName}
                        onRow={this.onRowRecord}
                    />
部分代码如上：
我猜想是您说的第三个问题：表格中有过长的英文字符或者数字。
我不明白的是，我的代码在本地yarn start是完全没有问题的，但是不知道为什么上线以后字符过长那一列就会撑开，并没有换行。
我试了word换行的相关属性，并没有解决这个问题

**Comment by afc163** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/507615/55048452-2ac4f700-5083-11e9-855e-9edbdb791a36.png">

**Comment by afc163** [comment]
<img width="781" alt="image" src="https://user-images.githubusercontent.com/507615/55048473-45976b80-5083-11e9-9b0c-c195de3ad74c.png">

---

不要进行无效交流。给一个有问题的重现例子我帮你调好。

**Comment by afc163** [comment]
应该不是 antd 的问题，先关了。有进一步的信息欢迎继续讨论，我会帮你调好为止。

**Comment by FuSimei** [comment]
已经在codepen中重现：https://codesandbox.io/s/wqkrmz9pjw
这个例子中只是更改了一些数据，觉得主要原因还是由于表格内容过长导致表格撑开

**Comment by afc163** [comment]
https://codesandbox.io/s/0p69o8rrl0

**Comment by FuSimei** [comment]
这边现在的解决办法主要是通过调节css样式和修改没有撑开列的表头宽度，具体可以查看css文件
https://codesandbox.io/s/wqkrmz9pjw
学习了，非常感谢

**Comment by FuSimei** [comment]
另外还有一个问题想借这个机会向您请教：
我有一个需求，当点击表格的具体某一行时，表格背景颜色高亮，现在我的这种处理方法是，只有鼠标移开时，才能看到高亮效果，而我希望只要鼠标点击了，立马就能看到高亮效果。查阅了相关文档，现在index.css里面注释的三种方法都不好使，希望能得到您的帮助
https://codesandbox.io/s/wqkrmz9pjw
