### ISSUE TITLE
creat-react-app 创建的项目不能实现antd的按需加载

### ISSUE THREAD

**Issue by yyhLogin** [ant-design/ant-design#15676]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yyhLogin/my-app-1.git](https://github.com/yyhLogin/my-app-1.git)

### Steps to reproduce
1.creat-react-app my-app-1
2.yarn add 各种依赖
3.yarn eject
4.按照cssModuleRegex格式配置lessModuleRegex
5.package.json中配置
"babel": {
    "presets": [
      "react-app"
    ],
    "plugins": [
      [
        "import",
        {
          "libraryName": "antd",
          "libraryDirectory": "es",
          "stytle": true
        }
      ]
    ]
  }

### What is expected?
实现按需加载

### What is actually happening?
按需加载不生效

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.5 |
| System | win10 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://ant.design/docs/react/use-with-create-react-app-cn

**Comment by yyhLogin** [comment]
@afc163 你官网的例子未弹出配置，使用react-app-rewired@2.官网有这个提示
Note: Do NOT flip the call for the eject script. That gets run only once for a project, after which you are given full control over the webpack configuration making react-app-rewired no longer required. There are no configuration options to rewire for the eject script.
