### ISSUE TITLE
RangePicker does not support typing in start/end dates when in form

### ISSUE THREAD

**Issue by SaladFork** [ant-design/ant-design#15673]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Working example (`DatePicker` outside form)
- View first example [in `DatePicker` documentation](https://ant.design/components/date-picker/) for `RangePicker`
- Click on "Start date" to open range picker dropdown
- Click on "Start date" text field at top of dropdown
- Type in a date, e.g. `2019-01-01`
- Observe the day being selected in the calendar as a start
- Click on "End date" at top (note click area is offset to the right, another bug has already been reported for this)
- Type in a later date, e.g. `2019-01-04`
- Observe the range Jan 1 to Jan 4 is selected, and clicking off the dropdown maintains this selection

### Broken example (`DatePicker` inside form)
- View seventh example [in `Form` documentation](https://ant.design/components/form/) including `RangePicker`
- Repeat the above steps to attempt to type in a start and end date
- Note that after setting the start date, it is selected in the calendar but the input is cleared
- Note that typing in an end date does not select it
- Note that clicking out of the dropdown results in an empty state with no value

### What is expected?
The `RangePicker` should behave the same when inside a form, allowing the start and end dates to be set by typing.

### What is actually happening?
When in a form, the RangePicker gets stuck in an empty state

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.5 |
| System | Mac OS |
| Browser | Chrome |

**Comment by ztplz** [comment]
@SaladFork  I downgraded the `react` to 16.3.0 and it's work for me. See [this demo](https://codesandbox.io/s/8197p6rwj0). But I am not sure if it is related to `react`,

**Comment by remyvanderwereld** [comment]
@ztplz This does not work for me. Is there an update yet?

**Comment by remyvanderwereld** [comment]
No fix yet?

**Comment by ichirukia1566** [comment]
I am sorry for opening a duplicated issue, but is this going to be fixed?

**Comment by afc163** [comment]
same as #17779

**Comment by murny** [comment]
Encountered a very similar issue when setting "value" prop on RangePicker.

Without value prop, you can enter both start and end date without issues as noted above regarding outside a form:
` <RangePicker onChange={onChange} />`

With value prop, you get similar behaviour noted above regarding inside a form. After typing start date, input gets cleared when trying to type in end date: 
 `<RangePicker onChange={onChange} value={[]} />`

Could be related 🤔. Form could be setting the value prop?

**Comment by farzer** [comment]
same issue

**Comment by afc163** [comment]
Fixed in antd v4 RangePicker.

**Comment by rahulgsn178** [comment]
How can I get the fix of this issue. if anyone know please do reply.
