### ISSUE TITLE
An ability to check is form valid or not

### ISSUE THREAD

**Issue by gibbsfromncis** [ant-design/ant-design#15674]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For e.g. I want to display a form for user and be able to toggle an disabled prop of submit button if form is valid or not.  

### What does the proposed API look like?
It would be super if it would be possible to do by using accessing this boolean value like a form prop like:

```
this.props.form.isValid
```

**Comment by afc163** [comment]
Try `getFieldsError` or `validateFields`.

**Comment by gibbsfromncis** [comment]
@afc163 `getFieldsError` returns object where each field is undefined. `validateFields` is impossible to use on `render` method because it produce component render again and in result we have infinity component rerenders

**Comment by gibbsfromncis** [comment]
@zombieJ @afc163 guys please re-open the issue or lets discuss it because all work-arounds are difficult.

**Comment by zombieJ** [comment]
Hi @gibbsfromncis , this is not workaround. It's official recommend: https://ant.design/components/form/#components-form-demo-horizontal-login

**Comment by gibbsfromncis** [comment]
@zombieJ strange that I missed that example. Thank you!

**Comment by ealiaga** [comment]
In my case, I use the Form within a Modal and the submit of the form is done with the button in the footer of the Modal, therefore to know if the Form is valid I use the following:


``` js
const [form] = Form.useForm()

const isFormValid = () => form.getFieldsError().some((item) => item.errors.length > 0)
```

**Comment by nojvek** [comment]
The problem with ^ is that calling form.submit() and then using getFieldsError.

```
form.submit();
const isFormValid = headerForm
    .getFieldsError()
    .every((fieldErr) => fieldErr.errors.length === 0);
```

This always returns in `isFormValid === true`;

So it seems the internals of ant Forms are broken.

**Comment by jawadst** [comment]
@nojvek I had the same issue and it comes from the fact that the validation is asynchronous and finishes after your `getFieldsError()` is evaluated which is why you do not see any error.

The `submit` function does not return a promise so you cannot wait for the validation to finish via `submit` but, looking at the code, `submit` mainly calls `validateFields` so their behavior should be the same and `validateFields` does return a promise that you can wait on.

That gives you:
```js
const [form] = Form.useForm();

  const onFormSubmit = useCallback(async () => {
    form
      .validateFields()
      .then(() => {
        // Validation is successful
      })
      .catch((errors) => {
        // Errors in the fields
      });
  }, [form]);
```

**Comment by nojvek** [comment]
Yeah I ended up doing something similar.

Why is validation asynchronous? that part I don't understand.

**Comment by domjancik** [comment]
Is there a way to validate the form like `validateFields()` that does not end up showing error messages next to the form fields?

I am trying to continually know whether the form is valid or not and disable the submit button accordingly.

**Comment by giovannipds** [comment]
Can't it be just?
```tsx
const isFormValid = !form.getFieldsError().length
```

**Comment by rpelorosso** [comment]
@domjancik  where you able to trigger validation without displaying the error messages in the fields?

**Comment by FelipeFelizardo** [comment]
3 years and nothing about it?

**Comment by m3c-ode** [comment]
Similarly to @ealiaga I validate my form through a Modal. In my case, for example of deletion: The problem there is using `form.submit` is that it doesn't wait for the request in the form to be completed, it returns void and is not a promise. Before going to the next steps. I've tried some of the above-mentioned ideas, but can't seem to have my form completed properly then. I want the modal to close after the request is complete, but it just closes right after the submit button is clicked and does not update the data/wait for the request to finish.

**Comment by SpringsTea** [comment]
I came across this and ``form.getFieldsError()`` was not returning the validation errors, it was always empty.

I figured out I can just use the `form.validateFields()` function to accomplish this.

```
form.validateFields()
.then(() => {
  //form valid logic
})
.catch((errorfields) => {
  //form not valid logic
})
```

If any form items fail to validate, `form.validateFields` throws an exception.

**Comment by JEEVANJGA** [comment]
Hi,
Is there a way to exclude Form field validation on submit, if the field has been validated already to Success status through validation onchange

**Comment by anubhavKumawat92** [comment]
> form.validateFields()

can you please share your full piece of working code?
 I am trying to call the validations from a submit button which is placed outside the form but `form.validateFields` is not working and `form.getFieldsError()` is not returning empty error array for fields.
 I am using ref forwarding and trying to call the `form.validateFields` via `myRefname.current.validateFields`

**Comment by epiphaneSpecter** [comment]
no solution ?  😢

**Comment by FelipeGbFaria** [comment]
This should not be marked as closed. The issue at hand is that there is not a direct way to check if the FormInstance is valid that is reliably updated as the user interacts with the form items, there is still no solution close to four years after this issue has been opened.

**Comment by dayoolacodes** [comment]
this is a major bug. form.getFieldsError() returns an empty error array and form.validateFields() is not the best approach too because it runs before you interact with the form.

**Comment by stary71** [comment]
Oh my god. Seems I should have used Formik or anything. This topic has just took my last hope the task is doable without any monkey work. Once again, guys. We can not make sure a form is valid or invalid without making it touched (every single field). So, for example, if I have a requirement to make the submit button disabled for invalid form, I just cannot do it if I don't want to highlight all the fields. Can I? Thank you in advance.

**Comment by petro-shkuratenyuk** [comment]
It's been 4 years, and there is solution on how to toggle submit button based on form fields???

**Comment by danyrojj** [comment]
recent posts make me worry about this problem still being relevant in v4.x and 5.x. Can someone confirm? Considering upgrading would be glad to know if this is/not the magic pill

**Comment by danyrojj** [comment]
I am running on v 3.x and i would describe the problem with validateFields as such: when form is valid indeed it just returns nothing. If using callback - it never runs, if promise - it's never resolved/fullfilled...

**Comment by danyrojj** [comment]
WOW. I have just found the problem.

My case: custom validators. validateFields's callback/promise won't return/resolve when all form is valid.

Solution: 

validator should not only invoke the callback with error message in case field is invalid, but also invoke it with no argument if it is valid.

**Comment by xelhark** [comment]
Another problem is that it is currently impossible (afaik) to open a link on a new window if the form is valid (at least on mobile), since the async code that opens windows is blocked by popup blockers, and you need the validation function to be asynchronous.

**Comment by saad-riaz-on** [comment]
Pretty late to the party, but this is how I solved it.
I first checked for all fields if they have been touched. (apparently you explicitly need to give the field names)
Then I check for errors.

And then I trigger the validation function from `onValuesChange` form param because `onFieldsChange` fires thrice for some wired reason.

Here is an example. With a modal. (with Modal, form is behaving a bit weird)

```
    const [isValidForm, setIsValidForm] = useState(false);

    const handleFormChange = () => {
        const fieldsTouched = form.isFieldsTouched(['first_name', 'last_name', 'email'], true);
        const hasErrors = form.getFieldsError().some(({ errors }) => errors.length);
        setIsValidForm(fieldsTouched && !hasErrors);
    }
    
    const updateFormFields = (property: string, value: string) => {
        form.setFieldsValue({ [property]: value });
    };
    
        return (
            <Modal
                title='Add User'
                okButtonProps={{ disabled: !isValidForm }}
                okText={'Add user'}
            >
                <Form
                    form={form}
                    onValuesChange={handleFormChange}
                >
                    <Form.Item
                        name='first_name'
                        label='First Name'
                        rules={[{ required: true, message: 'Please enter the first name' }]}
                    >
                        <Input onChange={(event) => updateFormFields('first_name', event?.target.value)} />
                    </Form.Item>
                    <Form.Item
                        name='last_name'
                        label='Last Name'
                        rules={[{ required: true, message: 'Please enter the last name' }]}
                    >
                        <Input onChange={(event) => updateFormFields('last_name', event?.target.value)} />
                    </Form.Item>
                    <Form.Item
                        name='email'
                        label='Email'
                        rules={[
                            { required: true, message: 'Please enter the email', type: 'email' }
                        ]}
                    >
                        <Input onChange={(event) => updateFormFields('email', event?.target.value)} />
                    </Form.Item>
                </Form>
            </Modal>
    );
    
```

works like a charm now. 

Hope this helps!

**Comment by thoughtpalette** [comment]
Pretty sure this should be reopened.

**Comment by adarshaacharya** [comment]
25023 and the soltuion has not been found :( I want to open accordion if there is any errors in form but sadly can't :(

**Comment by MarcLopezAvila** [comment]
Not ideal, but this hack works: 

```js
const onValuesChange = () => {
    setTimeout(() => {
      const hasErrors = form.getFieldsError().filter((field) => field.errors.length).length
      console.log(hasErrors);
    }, 0)
  };`

**Comment by irina-the-developer** [comment]
2024 and we still have no simple `isFormValid` prop 😭

**Comment by codethenpizza** [comment]
In the end this works for me for the form with both - required and non required fields 

[validate only param doc](https://ant.design/components/form#components-form-demo-validate-only) 

```
  const [isSubmitDisabled, setIsSubmitDisabled] = useState(true)

  const values = Form.useWatch([], form);

  useEffect(() => {
    form.validateFields({ validateOnly: true })
      .then((formValues) => {
        setIsSubmitDisabled(!Object.values(formValues).length)  // check keys to handle init state
      })
      .catch(() => {
        setIsSubmitDisabled(true)
      })
  }, [values]);
```

**Comment by phuc-party** [comment]
thank @codethenpizza , this works for me

**Comment by bora89** [comment]
Another proof that you should not rely on 3-rd parties libs too much. Don't be a hostage to them

**Comment by mmighri** [comment]
turn validateFields into a synch function    

```
async function validateForm() {
        try {
            let res = await form.validateFields();
            // Validation successful, proceed with deletion or other actions
            return res
        } catch (errors) {
            // Validation failed, handle errors or inform the user
            return errors;
        }
    }
```

and then use it inside "async" method

```
 let validation = await validateForm()
 console.log(validation)
```

**Comment by k-a-t-h-e-e** [comment]
useWatch solution is neat. but useWatch hook is available in ant design from 4.20.0. it's  impossible to upgrade in my case hence I used onValuesChange in Form. which has setTimeOut :-1: 

```
const [isSaveDisabled, setIsSaveDisabled] = useState(true);

  const handleValuesChange = async (changedValues, allValues) => {
    
    const changedKeys = Object.keys(changedValues);

    const changedPaths = changedKeys.flatMap(key => {
      const value = changedValues[key];
      if (Array.isArray(value)) {
        return value.flatMap((item, index) => {
          const innerKeys = Object.keys(item);
          return innerKeys.map(innerKey => [key, innerKey]);
        });
      } else {
        return [[key]];
      }
    });

    setTimeout(() => {
      form
        .validateFields(changedPaths)
        .then((values) => {
          const hasErrors = form.getFieldsError().some(({ errors }) => errors.length > 0);
          setIsSaveDisabled(hasErrors);
        })
        .catch((errors) => {
          setIsSaveDisabled(true);
        })
    })
  }
```
```  
  <Form  onValuesChange={handleValuesChange} >
  </Form>       
   ```

**Comment by andreyk1512** [comment]
Hello from 2024

Found simple solution how to get error of specific fields:
```
const [isFormHasErrors, setIsFormHasErrors] = useState(false);
const [form] = Form.useForm();

const onFieldsChange = (changedFields, allFields) => {
  const isNameFieldHasError = Boolean(allFields.find((item) => item.name[0] === 'name').errors.length);
  const isSurnameFieldHasError = Boolean(allFields.find((item) => item.name[0] === 'surname').errors.length);
  setIsFormHasErrors(isNameFieldHasError || isSurnameFieldHasError);
};

return (
  <Form form={form} onFieldsChange={onFieldsChange}>
    <Form.item name='name' rules={[{required: true}]}>
      <Input />
    </Form.item>
    <Form.item name='surname' rules={[{required: true}]}>
      <Input />
    </Form.item>
  </Form>
)
```


Hope it will help somebody..

**Comment by Ahmad-Akel** [comment]
It's also possible to use
```ts
const isFormValid = form.isFieldsValidating()
```

**Comment by k-a-t-h-e-e** [comment]
The best way to handle button disabling is to place the submit button within a `<Form.Item>`  inside the form. This way, there's no need to call `form.validateFields()`, avoiding unnecessary processing. 

      ```
  <Form.Item shouldUpdate>
          {() => (
            <Button
              type="primary"
              htmlType="submit"
              disabled={
                !form.isFieldsTouched(true) ||
                !!form.getFieldsError().filter(({ errors }) => errors.length)
                  .length
              }
            >
              Submit
            </Button>
          )}
        </Form.Item>
```
