### ISSUE TITLE
在getFieldDecorator的id为复合类型时，validateFields/validateFieldsAndScroll 不触发回调

### ISSUE THREAD

**Issue by SevenGuns** [ant-design/ant-design#15675]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/SevenGuns/ant-design-issue/blob/master/CommodityCreate.js](https://github.com/SevenGuns/ant-design-issue/blob/master/CommodityCreate.js)

### Steps to reproduce
当getFieldDecorator('earningsRuleCmdList[0].recommendEarnings')这种复合类型时，validateFields/validateFieldsAndScroll的传入的回调不会被触发，你可以在上面的代码中注释/{["1", "2"].map(this.renderRuleItem)}/这一行

### What is expected?
我感觉是个bug，希望早日修复

### What is actually happening?
不触发回调

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.7.0 |
| System | macOS 10.14.1 |
| Browser | 72.0.3626.121 |

**Comment by zombieJ** [comment]
太零碎了，抽个最小重现吧：https://u.ant.design/codesandbox
