### ISSUE TITLE
Inputs and Selects zooming on mobile devices

### ISSUE THREAD

**Issue by birdzhanmyumyun** [ant-design/ant-design#15688]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Prevents clicking or entering input on components Input, Select and others to zoom on mobile device browsers.

### What does the proposed API look like?
Maybe a prop like noZoomOnMobile set to true by default or something else.

**Comment by afc163** [comment]
antd don't provide supports in mobile devices now. Try use antd-mobile instead.

**Comment by AbramovichCp** [comment]
` <meta
      name="viewport"
      content="initial-scale=1, maximum-scale=1"
    />`
Try to set `maximum-scale=1` it prevent zoom in on iphone

**Comment by archisvaze** [comment]
> ` <meta name="viewport" content="initial-scale=1, maximum-scale=1" />` Try to set `maximum-scale=1` it prevent zoom in on iphone

Thats it! thanks!

**Comment by ab-etemadi** [comment]
> ` <meta name="viewport" content="initial-scale=1, maximum-scale=1" />`
> Try to set `maximum-scale=1` it prevent zoom in on iphone

Thank you for your solution! Setting 'maximum-scale=1' worked perfectly to prevent zooming on my iPhone. Your help is much appreciated.

**Comment by kubk** [comment]
Sorry for necroposting, but I believe the correct way is to set the default font to 16. We shouldn't break zoom if people want to use zoom. 

You can override the default font via ConfigProvider:

```js
  <ConfigProvider
      theme={{
        token: {
          fontSize: 16,
        },
      }}
    >
```

**Comment by troyanvic** [comment]
it works for me as well
