### ISSUE TITLE
PageHeader extra button not middle align

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15680]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w797kr61y8)

### Steps to reproduce
extra button

### What is expected?
middle align

### What is actually happening?
not align

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
It works well in antd v4.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/507615/76618506-a86b6680-6563-11ea-94a1-8422f16802e9.png">
