### ISSUE TITLE
[site] API 里的标题应该在右侧中出现

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design#15687]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
最近在用 antd 开发网站，发现找API需要自己手动拉，很不方便。

### What does the proposed API look like?
无

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/55064958-e1da6600-50b5-11e9-9989-70a06a3c766f.png)


![image](https://user-images.githubusercontent.com/9692408/55064973-ed2d9180-50b5-11e9-8cbb-10a0c9ac1ad0.png)

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/55073484-d2184d00-50c8-11e9-8829-112ce93ada1f.png)


自己写了一个 chrome 插件

**Comment by chenshuai2144** [comment]
这个是因为demo 已经很长了 就没有搞 toc

**Comment by DiamondYuan** [comment]
先关了
