### ISSUE TITLE
Form表单提交的扩展问题

### ISSUE THREAD

**Issue by yanglihuiylh102** [ant-design/ant-design#1568]
你好，现在我这里有个需求，就是在表单里有不确定的子属性，这些子属性是以数组的形式存放的 比如：
传统的form表单提交的数据格式如下：
{name:"tom",age"18",sex:"0",salary:"6000"}
我所要实现的如下：
{

name:"tom",
age"18",
sex:"0",
salary:"6000",
family:[{name:"mom",age:"45",sex:"1"},{name:"father",age:"40",sex:"0"},{name:"sister",age:"23",sex:"1"}]
}
请问我要怎么定义Form才能获取形如第二种数据的数据格式？？？

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/1371

**Comment by yanglihuiylh102** [comment]
数组啊数组，不是对象啊

**Comment by yanglihuiylh102** [comment]
其实也可以用ReduxForm来解决吧？

**Comment by yanglihuiylh102** [comment]
我现在就是自己在提交的方法里自己进行的数据组装。。。等有时间再好好研究一下
