### ISSUE TITLE
PageHeader 两层面包屑不显示

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#15686]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yp7mykvrz1)

### What is expected?
2层面包屑出现

### What is actually happening?
没有出现

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | last |
| System | osx  |
| Browser | chrome |

**Comment by laixstx** [comment]
PageHeader 的 breadcrumb 显示不了

![image](https://user-images.githubusercontent.com/10735940/55220426-37437e00-5242-11e9-86f0-45d6f3f6b637.png)
![image](https://user-images.githubusercontent.com/10735940/55220437-3e6a8c00-5242-11e9-8ecc-fc7bb6dba75c.png)
