### ISSUE TITLE
希望 InputNumber 可以允许取消上下方向键的自增或自减功能

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ant-design/ant-design#15682]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有时，方向键作为它用，但是按下方向键后，InputNumber 中的值会改变，影响体验。

### What does the proposed API look like?
添加 unbindKeyDown 属性，默认为 false

**Comment by afc163** [comment]
> 方向键作为它用

方向键在 InputNumber 里还有哪些用处？

**Comment by gh-xiaoxiao** [comment]
> > 方向键作为它用
> 
> 方向键在 InputNumber 里还有哪些用处？

自定义可输入表格中，方向键用来移动光标，当上下行移动光标时，InputNumber 中的数字也跟着改变。

**Comment by zombieJ** [comment]
感觉需要支持 preventDefault ……

**Comment by gh-xiaoxiao** [comment]
而且，InputNumber 组件，在输入非法的字符时，应该是输不进去比较好。

**Comment by zombieJ** [comment]
InputNumber 的 `parser` 属性是支持自定义转换逻辑的，所以可以实现用户输入中文都能转成对应的数字。这个是故意放开的。

**Comment by Jkssns** [comment]
我也遇到了这个问题，复议。

**Comment by jy-githup** [comment]
有没有什么额外方法可以避免这个上下键自增和自减功能
