### ISSUE TITLE
跨多列的鼠标悬浮样式在固定的列上无效

### ISSUE THREAD

**Issue by 405go** [ant-design/ant-design#15684]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/vPwrGp?editors=0010](https://codepen.io/anon/pen/vPwrGp?editors=0010)

### Steps to reproduce
鼠标悬停的列表的最后一行会发现，被固定的最后一列背景色不会发生变化

### What is expected?
被固定的最后一列背景色同该行一致

### What is actually happening?
被固定的最后一列背景色同该行不一致

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.2 |
| System | w7 |
| Browser | 谷歌 |

**Comment by 405go** [comment]
原因是被固定的那一列只是生成了一个空的tr标签，并没有生成td标签，导致样式不同步

**Comment by 405go** [comment]
rc-table TableCell.js 89行不要返回空而是返回<td>{}</td>可以解决该问题

**Comment by zombieJ** [comment]
这是因为最后一列的 render 你设置 colSpan 为 0 了，而左边的部分不是 fixed 的，导致它就不显示了。直接render 的时候不要 span 就行了：https://codesandbox.io/s/3z98z526
