### ISSUE TITLE
Cascader是否可以增加类似TreeSelect的labelInValue功能

### ISSUE THREAD

**Issue by majinkai** [ant-design/ant-design#15681]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为用到了级联选择的场景，大部分都是异步加载，数据量比较大，使用了异步加载后，在编辑页面，级联选择的默认值需要默认选中，目前需要后端返回数据去支持，希望增加类似TreeSelect的labelInValue功能，这样就可以不用后端数据支持，前端即能显示对应的数据

### What does the proposed API look like?
```
<Cascader labelInValue={true} defaultValue={[{ value: 'op1', label: 'OptionOne' }, { value: 'op2', label: 'OptionTwo' }]} />
```

**Comment by afc163** [comment]
`labelInValue` 会把组件逻辑搞复杂，Select 本来也不应该支持。Cascader 应该不会加。

**Comment by majinkai** [comment]
因为Select本身没有多级异步加载，但是TreeSelect和Cascader有，实际业务只能后端返回一级数据和对应已选的钻取数据这一种方法吗

**Comment by afc163** [comment]
是的，建议后端吐回完整的信息，不然前端不太方便展示默认值。

**Comment by afc163** [comment]
你也可以上层封装一个封装成  labelInValue 格式的 Cascader。

**Comment by hilads** [comment]
你好 我也遇到了这样的问题 设置的动态加载 ， 表单回显时 要显示默认值 因为第一级省份是已有的 市区需要动态加载 所以 我显示的时候 就只能 显示出省份 求助 要怎办
