### ISSUE TITLE
Table Sort by arrow tapped

### ISSUE THREAD

**Issue by zeweidan** [ant-design/ant-design#15683]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Although antd provides sort api, but it does not all under our control. When use sort function, we want to sort by tap the arrow button (up and down) and then the data sort as we clicked(up and down).

### What does the proposed API look like?
If I clicked up arrow, the data sort with ascend order and descend order when tap down arrow.

**Comment by afc163** [comment]
目前的交互已经不是这样的了，修改交互建议自行封装列头。

https://github.com/ant-design/ant-design/pull/12264

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9911#issuecomment-378770274

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11543

**Comment by zeweidan** [comment]
> 目前的交互已经不是这样的了，修改交互建议自行封装列头。
> 
> #12264

所以您的建议是怎么封装列头？能给点思路吗？我是想点击上就能升序，点击下就能降序。

**Comment by afc163** [comment]
title 是一个 React.ReactNode，你可以自行渲染你需要的节点。

**Comment by umairfarooq44** [comment]
@afc163 thanks for your reply. I am facing same issue, it would be great if you could share code snippet with at least one column having sorting by clicking on sort icon. The functionality could be when ascending icon is clicked sort by ascending and when same icon is clicked again, it should not sort. Same for descending.

**Comment by MianUmer486** [comment]
any update on this ?
