### ISSUE TITLE
Mention 组件不加前后空格

### ISSUE THREAD

**Issue by sundway** [ant-design/ant-design#15694]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前产品中使用$唤醒，交互希望能唤醒次前不需要加空格。类似产品如微博等，@前不需要加空格。

### What does the proposed API look like?
目前产品中的变量${}，希望支持直接输入唤醒词$符号唤起列表组件，选中后变成${}。

**Comment by j-kings-huang** [comment]
我也等待这个问题,兄弟有没有什么解决办法

**Comment by tourze** [comment]
希望加强这部分功能啊

**Comment by afc163** [comment]
可以关一波 Mention 的 issue 了。

**Comment by zombieJ** [comment]
试试新的 Mentions 组件哈~
