### ISSUE TITLE
can't change initialValue in CheckboxGroup

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#15692]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ouzhou/pen/rRgbvg?editors=0011](https://codepen.io/ouzhou/pen/rRgbvg?editors=0011)

### Steps to reproduce
click choose all, it will choose all checkbox, that is correct,
but if you click a checkbox next row, and then click choose all , it is not work

### What is expected?
CheckboxGroup's initialValue can be changed

### What is actually happening?
CheckboxGroup's initialValue can not be changed

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.x |
| System | win10 |
| Browser | chrome 72.0.3626.121（正式版本） （64 位） |

---
this.props.form.setFieldsValue is not work either
i write it in line 33

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14915#issuecomment-464991519
https://github.com/ant-design/ant-design/issues/15532
#5109
https://github.com/ant-design/ant-design/issues/10612
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
