### ISSUE TITLE
Table with no data should use the Empty component

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#15698]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o559nlz32q)

### Steps to reproduce
1. Create a Table with an empty dataSource. 
2. Use the Empty component. 

### What is expected?
The Table component with no data should use the Empty component or at least use the same image as the Empty component.

### What is actually happening?
An empty Table and the Empty component use different images.

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.2 |
| System | Windows 10 |
| Browser | Chrome 73 |

**Comment by afc163** [comment]
Actually, this is another style of Empty component. 

https://github.com/ant-design/ant-design/pull/15444
