### ISSUE TITLE
Cannot traverse from and to the same ID

### ISSUE THREAD

**Issue by xfcf1** [ant-design/ant-design#1569]
为什么我用任意一个控件，点击的时候都会报错
Uncaught Invariant Violation: traverseParentPath(...): Cannot traverse from and to the same ID, ``.

react 15，babel 6

**Comment by afc163** [comment]
没有例子无法重现，你先试试 react@0.14 ？

**Comment by afc163** [comment]
#1340

**Comment by xfcf1** [comment]
14 我试过了 一样的
原因是因为  我本来的  content 的div 上面的react-id=.0； 然后比如我用datepicker会在页面下面生成一个div ，此div里面是日历的相关的东西，**并且这个div的react-id也是.0** 怎么会这样。。

**Comment by afc163** [comment]
可能是页面引入了多个 react 。

**Comment by xfcf1** [comment]
https://github.com/xfcf1/react_ant_ie8.git

帮我看看吧 大神。。

**Comment by benjycui** [comment]
@xfcf1 建议提供最小可重现 demo，这样扔一个项目过来，除非很闲，否则不会看的。

**Comment by xfcf1** [comment]
解决了。。。重装 node modules 就行了
