### ISSUE TITLE
antd 各个控件的覆盖问题请帮忙看下

### ISSUE THREAD

**Issue by wangjinghui-cn** [ant-design/ant-design#1570]
我在页面上有多个控件自上而下排列
第一个是级联Cascader 第二个是select
当第一个控件展开的时候, 鼠标在select的hover区域内会显示一个清除标记,如图
![image](http://alltest.oss-cn-hangzhou.aliyuncs.com/pic%2F20160225%2Fantd-bug.png)

**Comment by afc163** [comment]
我试了一下，重现不出来，有别的代码影响了？ http://codepen.io/anon/pen/KzrGjR?editors=0010

**Comment by wangjinghui-cn** [comment]
我先研究研究 看看是否有其他代码影响  谢谢右哥
