### ISSUE TITLE
Upload fails when folder contains too many files. 文件的数量过多时导致上传失败。

### ISSUE THREAD

**Issue by evanzombie** [ant-design/ant-design#15701]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8nmo2l6v29)

### Steps to reproduce
上传了一个文件数量30,000， 总大小200MB 的文件夹。有时候会报错 ERR_INSUFFICIENT_RESOURCES 有时候浏览器直接转成空白页。

### What is expected?
成功上传

### What is actually happening?
上传失败 

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.5 |
| System | MacOS |
| Browser | Chrome Version 71.0.3578.98 (Official Build) (64-bit) |

---
是不是因为文件过多 request发出的次数过多?

**Comment by afc163** [comment]
https://stackoverflow.com/questions/24122506/neterr-insufficient-resources-error-when-adding-numerous-img-elements-to-dom

看上去是的，浏览器的 bug 我们做不了啥。

**Comment by evanzombie** [comment]
ajax 请求过多 浏览器内存用光了， 上传文件夹的话，能不能只发送一个ajax请求？

**Comment by evanzombie** [comment]
上传文件夹的时候，组件把所有文件的request同时发出去导致占用了浏览器内存，应该只发一部分

**Comment by evanzombie** [comment]
这个问题可以用 async 里面的  queue(worker, concurrencyopt) 来解决， 在custom request 里面每次只发送n个请求，这样就不会占用过多的浏览器内存。希望对遇见这个问题的朋友有帮助。

queue 的用法链接
https://caolan.github.io/async/docs.html#queue
