### ISSUE TITLE
Pagination links with page number should take whole space of the li rectangle

### ISSUE THREAD

**Issue by tylik1** [ant-design/ant-design#15704]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xjl1pqzmrq)

### Steps to reproduce
Open example link and try to click page number, on the rectangle ( not on the number).
See that click is not triggered. Click is only triggered when clicked on the number, because number doesn't take whole space of the li item.

### What is expected?
Click on anchor should be triggered when page number rectangle is clicked. 

### What is actually happening?
Anchor is not clicked

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16 |
| System | osx |
| Browser | Chrome |

---
This is already implemented in next, prev buttons. Anchors take whole li space.
This is especially important when used with real links. e.g. Link from react-router-dom

**Comment by tylik1** [comment]
It seems that even border needs to be applied to `a` component. Styling `li`component is useless if someone wants to utilize anchor component

**Comment by ztplz** [comment]
Just take a look at it, but I didn't find the situation you described.
![Untitled7](https://user-images.githubusercontent.com/17755202/55274466-c076b580-5313-11e9-9ac3-8ffa3a0470f8.gif)
If I am wrong, please correct me.

**Comment by ztplz** [comment]
Hmm, sorry, I understand what you mean.

**Comment by ztplz** [comment]
@tylik1  Why not use `onChange`?

**Comment by tylik1** [comment]
@ztplz because i'm using `<Link to="path" />` from react-router-dom 
There is no need to use onChange on top of that.

**Comment by ztplz** [comment]
You can set `style` for `a`. 
``````
style = {{
    display: 'block',
    width: 46,
    height: 32
}}
``````

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/55276346-cda09e00-532d-11e9-8e39-ab9c0e3f034e.png)

**Comment by afc163** [comment]
```diff
.ant-pagination-item a {
-   margin: 0 6px;
+   display: block;
    color: rgba(0,0,0,0.65);
    text-decoration: none;
    transition: none;
}
```

Could we change styles in this way?

**Comment by tylik1** [comment]
Next and previous buttons are already styled properly. Though still border is applied to `li` and if you hover on the very edge it will hove, but won't trigger click
