### ISSUE TITLE
Can't run the "Button" demo following "Use in TypeScript"

### ISSUE THREAD

**Issue by hatakawas** [ant-design/ant-design#15700]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-in-typescript](https://ant.design/docs/react/use-in-typescript)

### Steps to reproduce
Just do following the documentation: https://ant.design/docs/react/use-in-typescript

### What is expected?
I just want to have the "Button" demo run.

### What is actually happening?
It just CANT, by following your documentation "Use in TypeScript"

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.5 |
| System | MacOS |
| Browser | Chrome 73.0.3683.86 |

**Comment by hatakawas** [comment]
The browser says: 
```
/Users/${HOME}/WebSpace/react-quickstart/src/App.tsx
TypeScript error: Type '{ children: string; type: "primary"; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Button> & Pick<{ readonly href: string; readonly target?: string | undefined; readonly onClick?: ((event: MouseEvent<HTMLAnchorElement, MouseEvent>) => void) | undefined; ... 262 more ...; readonly onTransitionEndCapture?: ((event: TransitionEvent<...>) => void) | unde...'.
  Property 'href' is missing in type '{ children: string; type: "primary"; }' but required in type 'Pick<{ readonly href: string; readonly target?: string | undefined; readonly onClick?: ((event: MouseEvent<HTMLAnchorElement, MouseEvent>) => void) | undefined; readonly type?: "default" | ... 4 more ... | undefined; ... 261 more ...; readonly onTransitionEndCapture?: ((event: TransitionEvent<...>) => void) | undefi...'.  TS2322

    28 |     return (
    29 |       <div className="App">
  > 30 |         <Button type="primary">Button</Button>
       |          ^
    31 |       </div>
    32 |     );
    33 |   }
```

It's very strange that just there was nobody found this.

**Comment by themindoverall** [comment]
This is related to [this change in @types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4d371be185ddd77264a8d7f30a7f7f8912738ed8#diff-96b72df8b13a8a590e4f160cbc51f40c) which changed the `type` property from a `string` to `"submit"|"button"|"reset"` which conflicts with the `Button`'s `type` property.

**Comment by asumaran** [comment]
Any workaround for this? I got the same problem

**Comment by ferdikoomen** [comment]
Same here, indeed related to this @types/react update:
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4d371be185ddd77264a8d7f30a7f7f8912738ed8#diff-5b1e41d6479609ff1a7f33979dcca466

@asumaran You can specify the compatible @types/react package in your package.json like this:

```
"resolutions": {
    "@types/react": "16.8.8"
}
```

**Comment by ferdikoomen** [comment]
It can be fixed using the following change in **antd/lib/button/button.d.ts**

```
// Added the Omit type to remove specific properties from a imported type
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>

// In the button.d.ts we omit the type from the React type (since we 
// overwrite it in the BaseButtonProps). After this the error is gone...
export declare type AnchorButtonProps = {
    ...
} & BaseButtonProps & Omit<React.AnchorHTMLAttributes<HTMLAnchorElement>, "type">;

export declare type NativeButtonProps = {
    ...
} & BaseButtonProps & Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, "type">;

```

I will check how to modify the source and get a PR ready for this.

**Comment by ferdikoomen** [comment]
Or alternatively convert them to interfaces:

```
export declare interface AnchorButtonProps extends BaseButtonProps, React.AnchorHTMLAttributes<HTMLAnchorElement> {
    ...
};

export declare interface NativeButtonProps extends BaseButtonProps, React.ButtonHTMLAttributes<HTMLButtonElement> {
    ...
};
```

This way the inheritance is correct and the type from React.ButtonHTMLAttributes is overwritten by BaseButtonProps. Plus we don't need this complex omit type.

**Comment by ferdikoomen** [comment]
PR ready and build results look OK, hope this will get merged soon.

**Comment by hatakawas** [comment]
> PR ready and build results look OK, hope this will get merged soon.

Nice work!
Thanks!

**Comment by asumaran** [comment]
Sticking to `@types/react@16.8.8` and `antd@3.13.2` worked for me.

**Comment by liuruomu** [comment]
同样的问题，在本地已经fixed，但在docker中一直存在....

**Comment by ztplz** [comment]
@liuruomu  Update your docker please.

**Comment by mkusold** [comment]
Was this ever fixed? I'm using 
"antd": "^4.16.7",
"@types/react": "^17.0.14",
"react": "^17.0.2",
"typescript": "^4.1.6"

and still running into this issue. I tried adding resolutions for "@types/react": "16.8.8" but it still doesn't work
