### ISSUE TITLE
Mention can not be changed initialValue in Form when change its state

### ISSUE THREAD

**Issue by Oliver-GMJ** [ant-design/ant-design#15706]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/oliver105397/pen/OqYdJE?editors=0010](https://codepen.io/oliver105397/pen/OqYdJE?editors=0010)

### Steps to reproduce
1) give an undefined state "initValue" to Mention in Form initialValue
2) try to setState({ initValue: Mention.toContentState("helloworld") })
3) the Mention Box has no changed
It looks like cannot be undefined at first when it was used with form

### What is expected?
I'm using Mention with Form in a Modal, while its "first initialValue" was undefined I cannot change the Box view by change state, the Box also is null

### What is actually happening?
Mention's defaultValue can't be set when its "first time" defaultValue is undefined

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | react |
| System | windows 10 |
| Browser | Chrome 72.0.3626.121 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14915#issuecomment-464991519
https://github.com/ant-design/ant-design/issues/15532
#5109
https://github.com/ant-design/ant-design/issues/10612
#15692
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
