### ISSUE TITLE
Layout.Sider problem

### ISSUE THREAD

**Issue by kestisk** [ant-design/ant-design#15703]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
none

### What is expected?
once render

### What is actually happening?
twice render

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | 16.8.2 |
| System | windows10 |
| Browser | chrome latest |

---
when i use sider component in react project i saw two times render WHY? how can i fix it

**Comment by ztplz** [comment]
Please create a repo for your problem, it's so hard to look into without a repo.

**Comment by afc163** [comment]
You can add `hasSider` prop  at `Layout` to avoid extra render.

**Comment by ireznik** [comment]
> You can add `hasSider` prop at `Layout` to avoid extra rendering.

This solved my issue with the sider
