### ISSUE TITLE
Drawer exist bug（UI组件：抽屉存在问题）

### ISSUE THREAD

**Issue by mengSurpass** [ant-design/ant-design#15713]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mengsurpass/pen/JzQBJv](https://codepen.io/mengsurpass/pen/JzQBJv)

### Steps to reproduce
给Drawer添加mask={false}属性之后就会出现问题

### What is expected?
希望去掉遮罩之后，页面有滚动条时，打开抽屉不要先在左侧先闪一下再在右侧弹出

### What is actually happening?
去掉遮罩之后（设置mask={false}属性），页面有滚动条时，打开抽屉先在左侧先闪一下再在右侧弹出

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 最新版本 |
| System | windows10 |
| Browser | Google Chrome（73.0.3683.86） |

**Comment by jljsj33** [comment]
[![Edit Drawer default menu](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z2357mzzrl?fontsize=14)

并没有闪一下的现象啊。。。

**Comment by mengSurpass** [comment]
有滚动条的时候  左边会先弹出一下

**Comment by mengSurpass** [comment]
@jljsj33  你是打开我发的那个链接测试的吗

**Comment by mengSurpass** [comment]
@jljsj33 你把你写的那个width调到100应该就可以看出来了

**Comment by jljsj33** [comment]
```css
.ant-drawer-right.ant-drawer-open.no-mask {
    right: 0;
}
```
加个 right：0 就可以了

**Comment by mengSurpass** [comment]
@jljsj33 这个我知道    只是用的时候看到这个问题就提一下

**Comment by jljsj33** [comment]
哦，，发现问题并已有解决方案，可以给我们提个 PR 啊。。。

**Comment by mengSurpass** [comment]
ok

**Comment by afc163** [comment]
<img width="944" alt="image" src="https://user-images.githubusercontent.com/507615/56859374-3bd39180-69bc-11e9-83aa-c8babe31fe86.png">

![图片](https://user-images.githubusercontent.com/507615/56859378-49891700-69bc-11e9-89c7-1ab0aecacbaf.gif)

**Comment by jljsj33** [comment]
说好的 pr 呢?

**Comment by jljsj33** [comment]
....

**Comment by mengSurpass** [comment]
@jljsj33 这个应该算bug吧，提PR干什么

**Comment by afc163** [comment]
@mengSurpass 

@jljsj33 的意思是不妨来个 PR 帮忙我们修复掉，一步到位。

**Comment by mengSurpass** [comment]
@ jljsj33  最近工作比较忙  我就没有弄

**Comment by giscafer** [comment]
奇怪，  "antd": "4.22.8", 还存在右侧弹出，左侧闪烁问题

**Comment by sishen654** [comment]
开发时没有问题，打包后就出现闪动问题了，antd: 4.24.12
