### ISSUE TITLE
Menu 导航菜单 inlineCollapsed 为 true， 首次 hover 渲染错误

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#15717]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/10z4rkon9j)

### Steps to reproduce
参考示例

### What is expected?
正确渲染

### What is actually happening?
渲染错误

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | React 16 |
| System | WIN10 |
| Browser | Chrome 73 |

![企业微信截图_20190328152446](https://user-images.githubusercontent.com/1730277/55139917-d9476580-5171-11e9-83c5-64441f02c7db.png)

**Comment by afc163** [comment]
@zy410419243

**Comment by nuintun** [comment]
@afc163 @zy410419243 

[Ant Design Pro](https://preview.pro.ant.design/dashboard/analysis) 还出现了收起菜单后第一次 hover 子菜单不弹出的 BUG。

![sorter](https://user-images.githubusercontent.com/1730277/55144632-3811dc80-517c-11e9-9abf-9726387ac580.gif)

**Comment by zy410419243** [comment]
子菜单不弹出的 bug 有复现代码吗

第一个问题在 https://github.com/ant-design/ant-design/pull/15705 里没复现，但第二个就不知道了...

**Comment by nuintun** [comment]
@zy410419243 
第二个问题 `Ant Design Pro` 官网就能复现。

> @afc163 @zy410419243
> 
> [Ant Design Pro](https://preview.pro.ant.design/dashboard/analysis) 还出现了收起菜单后第一次 hover 子菜单不弹出的 BUG。
> 
> ![sorter](https://user-images.githubusercontent.com/1730277/55144632-3811dc80-517c-11e9-9abf-9726387ac580.gif)

**Comment by UnicornXU** [comment]
![image](https://github.com/UnicornXU/New/blob/master/img/Menu.gif)

**Comment by afc163** [comment]
Fixed in #15868
