### ISSUE TITLE
Modal CSS Style Bug

### ISSUE THREAD

**Issue by jszjgqq** [ant-design/ant-design#15716]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3236j3877m)

### Steps to reproduce
如果css有设置这个样式
html {
    overflow-y: scroll;
}

那么，页面中如果有modal弹窗，并且页面滚动条scrollTop > 0，页面会自动回到顶部然后显示modal弹窗。

### What is expected?
页面不要回到顶部，跟overflow-y样式属性兼容。

### What is actually happening?
页面中如果有modal弹窗 && scrollTop > 0，页面会自动回到顶部然后显示modal弹窗。

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.0.0 |
| System | windows |
| Browser | chrome 71 |

**Comment by Ghost-Luu** [comment]
遇到同样的问题。

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/55313440-5d635b00-549a-11e9-913c-42f4d81b617d.png)

add `body { height: auto }`
