### ISSUE TITLE
Input组件点击padding区域光标会出现在文字最前面

### ISSUE THREAD

**Issue by HanGuihe** [ant-design/ant-design#15711]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
在输入框内输入文字，1.先失去焦点，2.点击padding区域(差不多是Input边框的位置)

### What is expected?
光标出现在文字后面

### What is actually happening?
出现在输入框最前面

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.4 |
| System | macOS Mojave 10.14.3 |
| Browser | chrome  73.0.3683.86 |

---
![WechatIMG77](https://user-images.githubusercontent.com/29910482/55128861-1438a180-5150-11e9-8fe8-710fd8e1d8d9.jpeg)

想问一下是预留的功能还是浏览器的bug

**Comment by afc163** [comment]
这是浏览器的功能吧，原生 input 也是这样的。

**Comment by alicekahei** [comment]
确实原生的input有这样的问题。而且去掉padding,border 也还是会有这样的问题。

但是你可以设置光标位置。setSelectionRange().并且我加了延迟20ms。
刚刚解决这个问题。
