### ISSUE TITLE
Table中使用footer展示统计信息，在IE和chrome上信息全部挤到左下角

### ISSUE THREAD

**Issue by juneryo** [ant-design/ant-design#1571]
FF上展现没什么问题。
"version": "0.12.16"
![qq 20160503164555](https://cloud.githubusercontent.com/assets/4101515/14978756/ae07516e-1150-11e6-8f21-9d970be09958.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by juneryo** [comment]
@benjycui Demo放到这里了，请用IE或chrome查看
http://codepen.io/juneryo/pen/KzrbeV?editors=001

**Comment by afc163** [comment]
确实有问题。https://github.com/react-component/table/commit/ac48c33da46d4bc9f20628eba591f358ec7cd950 这里已经修复了，试试 beta 版本先。

**Comment by afc163** [comment]
重新安装 0.12.x 即可。
