### ISSUE TITLE
SubMenu下使用map报错：TypeError Cannot read property 'isRootMenu' of undefined

### ISSUE THREAD

**Issue by dylan921208** [ant-design/ant-design#15724]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8z3rz5r778)

### Steps to reproduce
打开即可复现

### What is expected?
期待能遍历出submenu的子菜单

### What is actually happening?
实际运行即报错：var getPopupContainer = props.parentMenu.isRootMenu ? props.parentMenu.props.getPopupContainer : function (triggerNode) {
      return triggerNode.parentNode;
    };

props.parentMenu 属性不存在,是否指定即可

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | lastest |
| System | Mac Os 10.14 |
| Browser | Chrome 73.0.3683.86 |

**Comment by dylan921208** [comment]
如果debugger进入代码可以发现原型上存在改属性
```

  SubMenu.prototype.renderChildren = function renderChildren(children) {
    var props = this.props;
    var baseProps = {
      mode: props.mode === 'horizontal' ? 'vertical' : props.mode,
      visible: this.props.isOpen,
      level: props.level + 1,
      inlineIndent: props.inlineIndent,
      focusable: false,
      onClick: this.onSubMenuClick,
      onSelect: this.onSelect,
      onDeselect: this.onDeselect,
      onDestroy: this.onDestroy,
      selectedKeys: props.selectedKeys,
      eventKey: props.eventKey + '-menu-',
      openKeys: props.openKeys,
      openTransitionName: props.openTransitionName,
      openAnimation: props.openAnimation,
      onOpenChange: this.onOpenChange,
      subMenuOpenDelay: props.subMenuOpenDelay,
    // 这里存在isRootMenu: false
      parentMenu: this,         
      subMenuCloseDelay: props.subMenuCloseDelay,
      forceSubMenuRender: props.forceSubMenuRender,
      triggerSubMenuAction: props.triggerSubMenuAction,
      builtinPlacements: props.builtinPlacements,
      defaultActiveFirst: props.store.getState().defaultActiveFirst[(0, _util.getMenuIdFromSubMenuEventKey)(props.eventKey)],
      multiple: props.multiple,
      prefixCls: props.rootPrefixCls,
      id: this._menuId,
      manualRef: this.saveMenuInstance,
      itemIcon: props.itemIcon,
      expandIcon: props.expandIcon
    };
```

**Comment by dylan921208** [comment]
目前的替代方案解决方案[https://github.com/ant-design/ant-design/issues/1124](https://github.com/ant-design/ant-design/issues/1124)

**Comment by afc163** [comment]
https://codesandbox.io/s/7zm78y2l1j

**Comment by dylan921208** [comment]
@afc163 为何class递归组件的写法会不存在parentMenu

**Comment by afc163** [comment]
你的例子里没有重现出`不存在parentMenu`的问题。

**Comment by JaylyLiu** [comment]
巨坑

**Comment by EmiyaYang** [comment]
V4.2.0 仍存在上述问题。

**Comment by sanriqing** [comment]
抽个组件也会发生。。
```typescript
interface IMenuData {
  value: string;
  key: string;
  sub?: IMenuData[];
}
function MenuList(props: { menuData: IMenuData }) {
  const { menuData } = props;
  return menuData.sub ? (
    <SubMenu icon={<PlusOutlined />} key={menuData.key} title={menuData.value}>
      {menuData.sub.map((e) => (
        <MenuList menuData={e} key={e.key}></MenuList>
      ))}
    </SubMenu>
  ) : (
    <Menu.Item icon={<MinusOutlined />} key={menuData.key}>
      {menuData.value}
    </Menu.Item>
  );
}


// TypeError: Cannot read property 'isRootMenu' of undefined
```

**Comment by hectorpla** [comment]
Menu和Submenu之间不能嵌套Fragment，依然在4.6.2能再现。不知道为什么实际报错的stack trace显示的代码行不是在源代码里，而是在dependency 的node_modules/rc-menu/lib/SubMenu.js里。

**Comment by hectorpla** [comment]
Menu和Submenu之间不能嵌套Fragment，依然在4.6.2能再现。

**Comment by mohammadtaghian** [comment]
![image](https://user-images.githubusercontent.com/56147396/105729247-441a8100-5f42-11eb-80d7-812552e7a980.png)
why this errore?
whats horisental mode problem?
someone help me
thanks

**Comment by mohammadtaghian** [comment]
no one have solution for it?
