### ISSUE TITLE
tree select中设置treeCheckable 为 false, 重复点击某一节点，出错

### ISSUE THREAD

**Issue by wx198592** [ant-design/ant-design#1572]
**问题描述**

tree select中设置treeCheckable 为 false, 重复点击某一节点，出错

**发生环境**

- antd 版本：0.12.15
- 操作系统及版本：
- 浏览器及版本：
- 在线演示地址：

**重现步骤**
tree select中设置treeCheckable 为 false, 重复点击某一节点，
配置如下：
    const tProps = {
      treeData,
      value: this.state.value,
      onChange: this.onChange.bind(this),
      multiple: true,
      treeCheckable: false,
      showCheckedStrategy: SHOW_PARENT,
      searchPlaceholder: '请选择',
      style: {
        width: 130,
      },
      dropdownMatchSelectWidth: false,
    };
    return <TreeSelect {...tProps} />;

出错如下：
Uncaught TypeError: Cannot read property 'forEach' of undefinedgetDeselectedValue @ Select.js:542removeSelected @ Select.js:593onDeselect @ Select.js:375onSelect @ Select.js:290onSelect @ Tree.js:283onSelect @ TreeNode.js:72domProps.onClick @ TreeNode.js:310ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:71executeDispatch @ EventPluginUtils.js:79executeDispatchesInOrder @ EventPluginUtils.js:102executeDispatchesAndRelease @ EventPluginHub.js:43executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54forEachAccumulated @ forEachAccumulated.js:23EventPluginHub.processEventQueue @ EventPluginHub.js:259runEventQueueInBatch @ ReactEventEmitterMixin.js:18ReactEventEmitterMixin.handleTopLevel @ ReactEventEmitterMixin.js:34handleTopLevelWithoutPath @ ReactEventListener.js:93handleTopLevelImpl @ ReactEventListener.js:73Mixin.perform @ Transaction.js:136ReactDefaultBatchingStrategy.batchedUpdates @ ReactDefaultBatchingStrategy.js:62batchedUpdates @ ReactUpdates.js:94ReactEventListener.dispatchEvent @ ReactEventListener.js:204

**线上重现演示**

**Comment by warmhug** [comment]
抱歉。请去掉 showCheckedStrategy: SHOW_PARENT, 这个设置，这个设置的前提是设置了 treeCheckable 。

**Comment by afc163** [comment]
API 优化为 `treeCheckable={SHOW_PARENT}` 如何？

**Comment by warmhug** [comment]
@afc163 考虑过，不行。 https://github.com/ant-design/ant-design/blob/develop-1.0.0/components/tree-select/index.jsx#L36  
![image](https://cloud.githubusercontent.com/assets/2011119/14981811/727f81fc-1164-11e6-8f7f-8baa6587bb9a.png)

treeCheckable 可以设为任何值

**Comment by warmhug** [comment]
那个报错，我稍后会先修复掉。现在 先去掉 showCheckedStrategy: SHOW_PARENT, 这个设置就不会报错了。

**Comment by wx198592** [comment]
@afc163 @warmhug  非常感谢两位的快速回复哈。我先去掉showCheckedStrategy: SHOW_PARENT

**Comment by wx198592** [comment]
@warmhug 还有个问题，如果设置treeCheckable 为 true时，check 父节点，所有的子节点会被checked；反过来，所有的子节点被checked，则父节点被checked。 当设置treeCheckable 为 false时，感觉并没有以上的逻辑，是我配置有问题，还是原本就是这样设计的呢？

**Comment by afc163** [comment]
#1565

**Comment by warmhug** [comment]
报错问题已修复，升级到`rc-tree-select@1.4.6`。

> 如果设置treeCheckable 为 true时，check 父节点，所有的子节点会被checked；反过来，所有的子节点被checked，则父节点被checked。 

这是带父子关系的checkbox的「常见」行为、所以设置为组件默认行为（不常见的就像父子节点选中无关联）。当设置treeCheckable 为 false时、没有了checkbox、就是普通的选择操作、父子兄弟之间都无关联。

**Comment by wx198592** [comment]
@warmhug  tree select或者select的输入框和下拉框是结合在一起用的。如果我只需要下拉框，有没有哪个参数可以配置得到我期望的这种行为

**Comment by warmhug** [comment]
参考这个：http://react-component.github.io/tree/examples/dropdown.html 。或者自己把`tree select或select` 的输入框样式覆盖掉、做成自己想要的样子，

**Comment by afc163** [comment]
@warmhug 这个修复了么？
