### ISSUE TITLE
latest @types/react breaks ant buttons

### ISSUE THREAD

**Issue by evertbouw** [ant-design/ant-design#15722]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
n/a

### Steps to reproduce
use ant with @types/react@16.8.10

### What is expected?
no error

### What is actually happening?
throw errors `Property 'href' is missing in type`

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.6 |
| System | win10 |
| Browser | firefox 67 |

---

this change https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34194 is causing typescript to throw errors `Property 'href' is missing in type`

**Comment by afc163** [comment]
Fixed in #15702
