### ISSUE TITLE
可以确认的时候关闭 Popover ，并不是点击添加 或者 其他地方

### ISSUE THREAD

**Issue by rainbowMorelhahahah** [ant-design/ant-design#15728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.google.com](http://www.google.com)

### Steps to reproduce
<FormItem label="库存规格" {...formItemLayout}>
                                    {this.state.skus.map((e: any, i: any) => {
                                        return (
                                            <div className="specification" key={i}>
                                                <div className="specification-name">
                                                    规格名：
                                                
                                                <div className="specification-value">
                                                    规格值：
                                                <Popover placement="bottom" title={" 添加"} content={
                                                        <div>
                                                           <Col md={12}>
                                                                    <Button type="primary" block>确认</Button>
                                                                </Col>
                                                        </div>
                                                    } trigger="click">
                                                        <a href="javascript:void(0);"> 添加</a>
                                                    </Popover>
                                                </div>
                                            </div>
                                        )
                                    })}

### What is expected?
可以确认的时候关闭  Popover ，并不是点击添加 或者 其他地方

### What is actually happening?
可以确认的时候关闭  Popover ，并不是点击添加 或者 其他地方

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 最新 |
| System | win 10  |
| Browser | 谷歌72 |

**Comment by rainbowMorelhahahah** [comment]
> Hello @rainbowMorelhahahah. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @rainbowMorelhahahah, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/embed/pklmm2m3vx

生成多个Popover 不用数组的方式存储 visible 点击 确定和取消 可关闭 Popover 的事件

**Comment by afc163** [comment]
https://ant.design/components/popover-cn/#components-popover-demo-control

**Comment by rainbowMorelhahahah** [comment]
> https://ant.design/components/popover-cn/#components-popover-demo-control

这个需要一个 数组来存 visible !!!! 我想要一个关闭所有的当前的 因为我的这个Popover 是循环出来的 如果只定一个 visible  其他Popover 都会触发

**Comment by JanecineJohn** [comment]
请问题主最后是如何解决的？
