### ISSUE TITLE
Focused anchored are underlined except when they are hovered

### ISSUE THREAD

**Issue by Nouzbe** [ant-design/ant-design#15725]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k3439q7q1o)

### Steps to reproduce
* Click the link to focus it.
* Move your cursor out of the link.
* Move your cursor onto the link again.

### What is expected?
The `text-decoration` should not change. It should either be `underline` or none for all of `:focus`, `:active` and `:hover`.

### What is actually happening?
An underline appears/disappears on mouseleave/mouseenter.

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.0 |
| System | Windows 10 1803 |
| Browser | Google Chrome 73.0.3683.86 (official build) (64 bits) |

---
This is caused by [components/style/core/base.less#L235](https://github.com/ant-design/ant-design/blob/c5a4eef4145daa9345458fef27a180c90f0a81c2/components/style/core/base.less#L235).

It seems to be undone in a few places. At least:
* [on the website](https://github.com/ant-design/ant-design/blob/c5a4eef4145daa9345458fef27a180c90f0a81c2/site/theme/static/common.less#L125)
* [in notifications](https://github.com/ant-design/ant-design/blob/06745a654867bb2dd21e1c9db253176fb7af4572/components/notification/style/index.less#L114)

**Comment by afc163** [comment]
We should remove it now cause links cannot be tabbed by keyboard anymore: https://stackoverflow.com/a/45191208

Could you send us a PR?

**Comment by Nouzbe** [comment]
@afc163 here's my plan for this PR:

* Remove the 2 overrides I mentioned above so that links are underlined when focused through keyboard navigation.
* Keep the underline for links that are focused **and** hovered in order to avoid the style switch that is visible in the Codepen.

Is it OK with you?

**Comment by afc163** [comment]
Like I said, we could remove `underline` focus styles and other overrides now, because it is meaningless if brower not allow to navigate between links by <kbd>Tab</kbd>.
