### ISSUE TITLE
Form setFieldsValue 后，调用 this.props.form.getFieldInstance 返回 undefined

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design#1573]
0.12.16 版本；
栗子：
http://jsfiddle.net/wangdao/dnnqo1Ln/5/

**Comment by benjycui** [comment]
`rm -rf node_modules && npm i`

**Comment by benjycui** [comment]
See: https://github.com/react-component/form/pull/14

**Comment by wangdao** [comment]
谢谢
