### ISSUE TITLE
Tag不能删除如果短时间内连续点击Tag关闭按钮之外的区域之后再点击删除按钮

### ISSUE THREAD

**Issue by jihgao** [ant-design/ant-design#15733]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
1. 设置Tag的closeable为true
2. 快速点击几次Tag的文字部分(不要点击关闭按钮)
3. 点击关闭按钮
4. 会发现不能正常关闭Tag

### What is expected?
关闭Tag的时候能够正常关闭

### What is actually happening?
不能正常关闭

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | any |
| System | Mac |
| Browser | Chrome |

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/55211563-8af49e00-5227-11e9-9353-47e4729b706a.png)
You didn't save it?
