### ISSUE TITLE
form动态增减表单项，删除表单项，values中存在空值

### ISSUE THREAD

**Issue by changxia** [ant-design/ant-design#15738]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-dynamic-form-item](https://ant.design/components/form-cn/#components-form-demo-dynamic-form-item)

### Steps to reproduce
1、添加多个表单项['first value','second value','third value'] ，提交 
2、删除其中一个或多个 eg:delete second
参考 https://github.com/ant-design/ant-design/issues/15737

### What is expected?
['first value','third value'] 

### What is actually happening?
['first value',null,'third value'] 

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16 |
| System | 3.15.2 |
| Browser | chrome |

**Comment by SmallPolaris** [comment]
多层嵌套动态表单怎么处理循环的key值
比如 理想数据接口是这种的
```
  [
  a:'xx',
 b:[
  {
  bc:''
}
]
]
```

**Comment by zombieJ** [comment]
例子中有两个字段：
<img width="323" alt="屏幕快照 2019-04-02 下午5 36 25" src="https://user-images.githubusercontent.com/5378891/55392449-e4cdce80-556d-11e9-9e23-7c0854a13072.png">

`key` 是 `value` 对应值的位置。
