### ISSUE TITLE
设计调整

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#15734]
- [ ] 1. 优化 Card、PageHeader 的 padding 为24px
- [ ] 2. 给状态点的设置为颜色自定义
- [ ] 3. 表格头的排序位置跟随表格标题，且保持点击标题进行排序

**Comment by afc163** [comment]
PageHeader 这些问题不一块修掉么？

https://github.com/ant-design/ant-design/search?q=PageHeader&type=Issues

**Comment by zombieJ** [comment]
Typescript 那个会 block 不少人，先发掉一版再弄这些。

**Comment by Jiang-Xuan** [comment]
有个小问题, 像这种间距的调整是设计师要求调整的么, 如果是设计师要求调整的, 会反馈在设计资源中么, 不过我看设计资源中提供的设计稿只到 3.12.0 🧐

![image](https://user-images.githubusercontent.com/13357301/69302622-2f16d380-0c55-11ea-92e8-09f0bdb5e86a.png)
