### ISSUE TITLE
ANT DESIGN PRO

### ISSUE THREAD

**Issue by blueblue0817** [ant-design/ant-design#15735]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/user/login](https://preview.pro.ant.design/user/login)

### Steps to reproduce
点击预览跳转登录，无法看见中继台预览效果

### What is expected?
和之前一样可以看见中继台页面效果图，有表单 有详情

### What is actually happening?
现在停留在登录页面，无法进入查看，点击注册获取验证码，无短信接收

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | v1 |
| System | windows 10 企业版 2016长期服务版 |
| Browser | Google Chrome 版本 73.0.3683.86（正式版本） （64 位） |

**Comment by imhele** [comment]
账号 admin 密码 ant.design
