### ISSUE TITLE
form component password confirm error

### ISSUE THREAD

**Issue by laurensmartz** [ant-design/ant-design#15731]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#header](https://ant.design/components/form-cn/#header)

### Steps to reproduce
typing password and confirm password with the same string then change the password text,console will occur an error

### What is expected?
no error

### What is actually happening?
occur error

| Environment | Info |
|---|---|
| antd | 3.5.3 |
| React | 16.3.2 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
I think it is reasonable to throw error when password and confirm password don't match.

**Comment by laurensmartz** [comment]
thx
