### ISSUE TITLE
FormItem 中带有 addonAfter 的 Input 纵向位置偏移

### ISSUE THREAD

**Issue by Kingsley-Don** [ant-design/ant-design#15746]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j1zl8vkzr3)

### Steps to reproduce
第一行第一个为 FormItem 中有 addonAfter 的 Input，和右侧的没有对齐
无 FormItem 的正常

### What is expected?
FormItem 中带有 addonAfter 的 Input 和其余元素对齐

### What is actually happening?
FormItem 中带有 addonAfter 的 Input 在纵向向上偏移

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.3 |
| System | macOS 10.14.4 |
| Browser | Chrome/73.0.3683.86 |

**Comment by afc163** [comment]
https://codesandbox.io/s/7680z34x

You should use `Form.Item` in `Form`.
