### ISSUE TITLE
babel 升级到7？

### ISSUE THREAD

**Issue by bianlin** [ant-design/ant-design#15748]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
部分库要求babel7以上才能用

### What does the proposed API look like?
null

**Comment by afc163** [comment]
你遇到了什么问题？

**Comment by afc163** [comment]
<img width="485" alt="图片" src="https://user-images.githubusercontent.com/507615/55271784-90b4b700-52ed-11e9-805e-ad412f37a0d2.png">

**Comment by zombieJ** [comment]
先关掉了，有后续回复再重开。
