### ISSUE TITLE
Something to do before 1.0.0

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1574]
This close #978

- [x] http://012x.ant.design @ddcat1115
- [x] Official Changelog @afc163 #1614
- [x] Update antd-init @afc163 https://github.com/ant-design/antd-init/pull/36
- [x] Publish new site

And chore to do:

- [x] Site Problems #1259
- [x] #1397
- [x] #1453
- [x] #1546
- [x] #1589
- [x] #1605
- [x] #1572
- [x] #1273 
- [x] #1466
- [x] #1600 
- [x] #1561

**Comment by RaoHai** [comment]
我跟一下 #1546 #1453 吧

**Comment by afc163** [comment]
#1453 @ddcat1115 在做了。

**Comment by superRaytin** [comment]
@yiminghe 看下 react-component/menu#39，用于关掉 #1600

**Comment by afc163** [comment]
published
