### ISSUE TITLE
Cannot specify type and disabled property for Button when using Typescript

### ISSUE THREAD

**Issue by sidsethupathi** [ant-design/ant-design#15749]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/18j0qojqll)

### Steps to reproduce
1. Use Typescript (I was using v3.3.4000)
2. Install latest `@types/react` (I was using v16.8.10, but I think anything greater than 16.8.8 will do)
3. Create Button with `type` and `disabled` props

### What is expected?
Typescript compilation succeeds

### What is actually happening?
```
Type error: Type '{ children: string; type: "danger"; size: "small"; disabled: boolean; onClick: () => void; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Button> & Pick<{ readonly href: string; readonly target?: string | undefined; readonl
y onClick?: ((event: MouseEvent<HTMLAnchorElement, MouseEvent>) => void) | undefined; ... 262 more ...; readonly onTransitionEndCapture?: ((event: TransitionEvent<...>) => void) | unde...'.
  Property 'disabled' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Button> & Pick<{ readonly href: string; readonly target?: string | undefined; readonly onClick?: ((event: MouseEvent<HTMLAnchorElement, MouseEvent>) => void) | undefined; ... 262
more ...; readonly onTransitionEndCapture?: ((event: TransitionEvent<...>) => void) | undef...'.  TS2322
```

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.6 |
| System | Mac OSX |
| Browser | Chrome |

---
I believe https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34194 makes `ButtonHTMLAttributes` more restrictive for the `type` field, so when supplying a `type` prop to an Ant Button, the Ant typings use the `AnchorButtonProps` which does not have a `disabled` field.

**Comment by sidsethupathi** [comment]
Sorry, see that this was a duplicate now.

**Comment by ghayes7** [comment]
Since this is the first result in google: Related Issues: #15702 #20722 #15930 #15739 #15930
