### ISSUE TITLE
Table表头上面的sorter和filters图标，能否跟随在title文字后面

### ISSUE THREAD

**Issue by SmallPolaris** [ant-design/ant-design#15741]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果一个列的宽度很宽，然后又有filters或者sorter，那么，看起来就不像是这个列的filters和sorter，而像旁边列的

### What does the proposed API look like?
希望可以自定义 sorter和filters的位置
API 还没有想好

**Comment by SmallPolaris** [comment]
![image](https://user-images.githubusercontent.com/46179450/55216924-162a5f80-5239-11e9-99cf-d9c105238cf1.png)

**Comment by SmallPolaris** [comment]
https://codesandbox.io/embed/zl8rj6qz7p

**Comment by afc163** [comment]
trace #15734
