### ISSUE TITLE
ant design select 标签模式下后台请求来的数据和本地存的数据会重复

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#15745]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ant design select 标签模式下后台请求来的数据和本地存的数据会重复

### What does the proposed API look like?
点击后台请求来的数据，本地标签不会去重
![image](https://user-images.githubusercontent.com/28847126/55222273-75db3780-5246-11e9-978d-1238ebb7bfb7.png)

**Comment by ztplz** [comment]
数据建议自己去重

**Comment by wangxingxing123654** [comment]
你误会了。一个是显示默认数值。一个是从下拉框选择的数据（从后台返回来的），这样就不能默认选中了。

**Comment by wangxingxing123654** [comment]
> 数据建议自己去重
你误会了。一个是显示默认数值。一个是从下拉框选择的数据（从后台返回来的），这样就不能默认选中了。

**Comment by wangxingxing123654** [comment]
![image](https://user-images.githubusercontent.com/28847126/55226265-85ab4980-524f-11e9-9dc5-63a806780d33.png)
![image](https://user-images.githubusercontent.com/28847126/55226303-9fe52780-524f-11e9-9515-a563af619a6e.png)
![image](https://user-images.githubusercontent.com/28847126/55226339-bb503280-524f-11e9-8d0b-60c3f928b7ec.png)

**Comment by ztplz** [comment]
你可以value控制的，帮用户去重感觉没什么必要，因为用户完全可以自己轻松解决。
