### ISSUE TITLE
useform我更新到最新版本后还是无法使用

### ISSUE THREAD

**Issue by kejiacheng** [ant-design/ant-design#15743]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/12857#issuecomment-433777455](https://github.com/ant-design/ant-design/issues/12857#issuecomment-433777455)

### Steps to reproduce
无

### What is expected?
在hooks里使用useform

### What is actually happening?
useform为undefined

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.5 |
| System | mac |
| Browser | chrome |

---
我看https://github.com/ant-design/ant-design/issues/12857#issuecomment-433777455    这里是几个月前的了，现在这功能还没实现吗？

**Comment by ztplz** [comment]
以文档为准。

**Comment by kejiacheng** [comment]
> 以文档为准。

那有大致时间吗？毕竟hooks也出来2个月了，也算刚需了（伸手党就是这么不要脸）

**Comment by ztplz** [comment]
具体时间我也不清楚，但是最近应该不会，人手不够。

**Comment by exvu** [comment]
@kejiacheng 你是不是form的依赖包用错了。用成以前的兼容版本
