### ISSUE TITLE
@layout-header-height doesn't work with horizontal <Menu />

### ISSUE THREAD

**Issue by corysimmons** [ant-design/ant-design#15744]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/corysimmons/antd-bugs/tree/horizontal-menu-line-height](https://github.com/corysimmons/antd-bugs/tree/horizontal-menu-line-height)

### Steps to reproduce
1. Create a CRA demo via these instructions https://ant.design/docs/react/use-with-create-react-app#Customize-Theme
2. Add color variable to modifyVars to confirm variables are customizable
3. Change any height setting associated with Layout or Menu
4. Horizontal menu height doesn't change

### What is expected?
Horizontal menu height to change

### What is actually happening?
Horizontal menu height is not changing

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | ^16.8.6 |
| System | OSX |
| Browser | Chrome |

**Comment by corysimmons** [comment]
Specifically `.ant-menu-horizontal` still gets `line-height: 46px;` when I'd expect this line-height to be modified according to some LESS variable being changed.

**Comment by ztplz** [comment]
@corysimmons  It is hard coded. https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less#L280
You can change it via the `style` on the menu.

**Comment by corysimmons** [comment]
Thanks, but I just stopped using Ant.

**Comment by Duder-onomy** [comment]
@ztplz This should really be fixed. 

It is a terrible out of the box experience for this Framework. 
The first thing people usually do when building a website is build a navbar... When the menu is rendered inside the Layout.Header, it should get its height from the `@layout-header-height`.  The fact that it does not, makes the out-of-the box experience terrible.  

Adding inline `style={{ lineHeight` is simply a bad idea. It decouples the menu height from the theme.  I suspect most people will be using AntD to get the power of its Theme.  
If someone wanted to update the header height via a Theme, they would also need to dig through the source code and make sure that the new line-height was updated.
