### ISSUE TITLE
Support `name` attribute for Checkbox and Checkbox.Group

### ISSUE THREAD

**Issue by bencallaway** [ant-design/ant-design#15751]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`Checkbox` and `Checkbox.Group` currently do not support/render a `name` property/attribute, respectively. Doing so would better facilitate universal/isomorphic applications and would be consistent with the `Radio` and `Radio.Group` components.

### What does the proposed API look like?
I propose to add a `name?: string` type prop to both the `Checkbox` and `Checkbox.Group` components. If given a value it should be rendered as a name attribute for the checkbox input(s).

**Comment by ztplz** [comment]
The checkbox already supports name prop, but just no description in the documentation.
