### ISSUE TITLE
mapPropsToFields documentation

### ISSUE THREAD

**Issue by vanshady** [ant-design/ant-design#15769]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It occurs to me that many users encounter the problem that when using mapPropsToFields, the form can't getFieldsErrors like before. After some research, it looks like this is by design, but it's not clearly reflected in the documentation and demo.

很多用户都遇到了如果使用mapPropsToFields，error需要手动处理的问题。我查看了各种issues发现这是by design的行为，然而demo和文档里并没有很清晰的体现这个行为，请问可否更新文档注明？

### What does the proposed API look like?
At least add a line for mapPropsToFields, saying "This will also intercept errors, and you need to map errors to props to manually show errors."

**Comment by vanshady** [comment]
For reference, #13355 #13071 #9561 and so on

**Comment by ycjcl868** [comment]
PR welcome, enhance the [components-form-demo-global-state](https://ant.design/components/form/#components-form-demo-global-state) using `onFieldsChange` handle `errors`.
