### ISSUE TITLE
Typescript is complaining about missing "href" property

### ISSUE THREAD

**Issue by jannikbuschke** [ant-design/ant-design#15761]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jannikbuschke/reproduce-antd-button-typescript-bug.git](https://github.com/jannikbuschke/reproduce-antd-button-typescript-bug.git)

### Steps to reproduce
```
npm install
npm run build
```

### What is expected?
(typescript) compilation/build succeeds

### What is actually happening?
Following error message is thrown:

```
TypeScript error: Type '{ children: string; type: "primary"; onClick: () => void; }' is not assignable to type '(IntrinsicAttributes & IntrinsicClassAttributes<Button> & Pick<{ readonly href: string; readonly target?: string | undefined; readonly onClick?: ((event: MouseEvent<HTMLAnchorElement, MouseEvent>) => void) | undefined; ... 262 more ...; readonly onTransitionEndCapture?: ((event: TransitionEvent<...>) => void) | unde...'.
  Property 'href' is missing in type '{ children: string; type: "primary"; onClick: () => void; }' but required in type 'Pick<{ readonly href: string; readonly target?: string | undefined; readonly onClick?: ((event: MouseEvent<HTMLAnchorElement, MouseEvent>) => void) | undefined; readonly type?: "ghost" | ... 4 more ... | undefined; ... 261 more ...; readonly onTransitionEndCapture?: ((event: TransitionEvent<...>) => void) | undefine...'.


     6 |   return (
     7 |     <div className="App">
  >  8 |       <Button type="primary" onClick={() => console.log("test")}>
       |        ^
     9 |         test
    10 |       </Button>
    11 |     </div>
```

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.6 |
| System | Windows |
| Browser | any |

---
using typescript version 3.4.1

**Comment by JeromeDeLeon** [comment]
[#15739](https://github.com/ant-design/ant-design/issues/15739)

**Comment by ztplz** [comment]
Fixed via https://github.com/ant-design/ant-design/pull/15702.
