### ISSUE TITLE
Sider初始在折叠状态，鼠标第一次移入SubMenu没有反应

### ISSUE THREAD

**Issue by AsukaSong** [ant-design/ant-design#15776]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n3jkyj45o4)

### Steps to reproduce
刷新页面，鼠标移入test菜单这一项

### What is expected?
SubMenu的Popup出现

### What is actually happening?
SubMenu的Popup未出现

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.3 |
| Browser | Google Chrome Version 73.0.3683.86 (Official Build) (64-bit) |

---
只有在页面加载后第一次移入SubMenu会复现

**Comment by AsukaSong** [comment]
不知道和 https://github.com/ant-design/ant-design/issues/15717 后面讨论的是不是同一个问题

**Comment by zy410419243** [comment]
3.16.0 里看上去已经没这个问题了

**Comment by zy410419243** [comment]
![demo](https://user-images.githubusercontent.com/24520193/55317780-d0250400-54a3-11e9-9579-82ef08c747ea.gif)

**Comment by AsukaSong** [comment]
`
Module not found: Error: Can't resolve 'antd/dist/antd.less'
`

```antd/dist/antd.less```被移除了吗

**Comment by zy410419243** [comment]
查查 webpack 配置，估计是 babel plgins 哪出问题了

**Comment by AsukaSong** [comment]
还是有一点问题，如果鼠标开始的时候在灰色的区域并移入的话，还是有同样的问题

抱歉提了很多问题，感谢修复

**Comment by AsukaSong** [comment]
![Untitled](https://user-images.githubusercontent.com/26486891/55319390-58f16f00-54a7-11e9-8e4d-38642fa43c99.gif)

**Comment by afc163** [comment]
Fixed in #15868
