### ISSUE TITLE
layout布局中，左边菜单栏展开状态，切换收起是有bug闪现，影响用户体验怎样解决

### ISSUE THREAD

**Issue by shuangwy** [ant-design/ant-design#15771]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout-cn/](https://ant.design/components/layout-cn/)

### Steps to reproduce
侧边布局，子菜单展开，unfold状态下，点击toggle切换，子菜单出现忽闪的状态

### What is expected?
期望取消忽闪忽闪

### What is actually happening?
现在存在忽闪，

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.4 |
| System | window |
| Browser | chrome |

---
侧边布局，子菜单展开，unfold状态下，点击toggle切换，子菜单出现忽闪的状态

**Comment by ycjcl868** [comment]
transition 过渡效果，如果不期望的话，可自行 style 覆盖 transition。

**Comment by zy410419243** [comment]
https://github.com/ant-design/ant-design/pull/15625
