### ISSUE TITLE
tooltip的弹出层是否应该阻止冒泡？

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#15773]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lpooowwy5q)

### Steps to reproduce
当我在Collapse的Panel中使用popover时，在弹出层中点击总会触发Collapse的onChange事件，没法阻止弹出层本身的冒泡
![image](https://user-images.githubusercontent.com/23520283/55299301-ff685080-5464-11e9-9222-6b9cf23aea7d.png)

### What is expected?
点击弹出层不触发Collapse的onChange

### What is actually happening?
点击弹出层触发Collapse的onChange

| Environment | Info |
|---|---|
| antd | 3.13.4 |
| React | 16.6.3 |
| System | Windows 10 |
| Browser |  73.0.3683.86 |

**Comment by afc163** [comment]
You can prevent default propagation, check https://ant.design/components/collapse/#components-collapse-demo-extra

**Comment by Liu-Ya** [comment]
> You can prevent default propagation, check https://ant.design/components/collapse/#components-collapse-demo-extra

我能阻止弹出层中的Input的clike事件，但没法阻止ant-popover-content中padding或者其他空白部分的事件

**Comment by afc163** [comment]
Try `getPopupContainer={node => node.parentNode}`

**Comment by haiwin-sure** [comment]
我的解决方案是：
<div onClick={(e) => e.stopPropagation()}>your Tooltip</div>

这样可以阻止 Tooltip 内的所有冒泡...

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/49410/files#diff-ced6f422d0110bd90abedf7125f0750aa55da83ce91906821a21a8c857a912c4R45
