### ISSUE TITLE
如何修改Tabs组件中当前Tab的下划线的长度？

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#15777]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们期望可以通过props来修改inkBar的长度来适应文本的长度

### What does the proposed API look like?
可以提供类似 linkBarWidth: adaptText | full | number(固定的居中长度) 这样的属性来修改样式。

**Comment by zombieJ** [comment]
Tabs 的 InkBar 是组件设计的一部分。目前没有计划推出 api 进行修改。但是你仍然可以通过 css 来做固定长度：https://codesandbox.io/s/lyl5r2j5jq

**Comment by kairi1227** [comment]
好的。感谢！

**Comment by hyacinthsWang** [comment]
we can use :after content to show other width style for each nav bar item.
