### ISSUE TITLE
Keybindings for options are not working on Select component when visibility or display set to "hidden" or "none"

### ISSUE THREAD

**Issue by omniphx** [ant-design/ant-design#15770]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jnk6xo26w5?fontsize=14)

### Steps to reproduce
1. Create a `Select` component and give it a reference
2. Set the style of the `Select` to `visibility:'hidden'` or 'display:'none'`
3. Render the options using `dropdownRender` method from the Select component
4. With a separate call to action, call `reference.current.rcSelect.setOpenState(true, true)` to open the select options
5. Options will be visible/toggled, but keybindings will not work

### What is expected?
When Select is not visible, I should still be able to use dropdown keybindings to move up/down on a list of options

### What is actually happening?
I lose the ability to use keybindings to select an option

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.6 |
| System | Windows |
| Browser | Chrome 72.0.3626.121 |

---
The functionality I'm trying to build is a custom type-ahead in a text area that autocompletes for a specific word or phrase instead of the entire input. So using the antd Autocomplete component/feature will not accomplish what I'm trying to do.

**Comment by ycjcl868** [comment]
It's a very hack usage in `Select`, you can use [Mention](https://ant.design/components/mention-cn/) to meet your need.

**Comment by ztplz** [comment]
https://codesandbox.io/s/46824yjxx
https://github.com/react-component/select/blob/7fbaeb66563b5e40417c17f0a46c084ecf70b4eb/src/Select.tsx#L743
It seems that `onkeydown` won't fire in a hidden element.
