### ISSUE TITLE
Menu在pad上点击有时需要两次才能触发onClick事件

### ISSUE THREAD

**Issue by bestv2** [ant-design/ant-design#1578]
可能ant-design目前不针对触屏开发，但是确实会有用户在使用IPad操作的情况，在IPad safari和chrome浏览器中都存在该问题， 官网例子：http://ant.design/docs/spec/layout/#layout-demo-aside可以重现该问题，点击第一下，menu获得焦点但是没有触发onClick,点击第二下触发onClick

**Comment by afc163** [comment]
ipad 是这样的，所有的 onClick 事件都需要点两次，第一次可用于触发 hover 。这个和 antd 本身没关系哈。

**Comment by sornon** [comment]
自己用div+a写一个组件加onClick事件，就只需要点一次，但是用antd的menu组件就得点两次

**Comment by afc163** [comment]
另外，我们目前对移动端的没有提供官方支持，目前也确实没有精力去研究相关细节。如果确实是代码有问题，欢迎探索之后给我们提交 PR ~ 再次感谢反馈。@sornon
