### ISSUE TITLE
Table组件该加一个属性，控制表格里的文本是否可打断。（类似word-break：break-all）

### ISSUE THREAD

**Issue by songyangsy** [ant-design/ant-design#15789]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table组件一但遇上长英文或长数字文本，就会无视columns里设置的宽度，把当前格撑得很长甚至超出当前页面，搞的我每次都需要在css里单独设置一下（因为有的单元格不能打断，有的需要打断）。建议加个属性设置是否可打断，这样就不用但在css里单独设置。

### What does the proposed API look like?
在Table组件的columns属性里加个属性（类似break：true or false）

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/5753#issuecomment-452668949
