### ISSUE TITLE
在使用React的Table组件的时候，使用locale={{emptyText: ""}}还是在显示暂无=数据和一张图片

### ISSUE THREAD

**Issue by IversonzZ** [ant-design/ant-design#15785]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://无/](https://无/)

### Steps to reproduce
无

### What is expected?
当在Table组件中添加locale={{emptyText: ""}}时不显示暂无数据的文字和图片

### What is actually happening?
会有暂无数据的文字和图片

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | React-Table-emptyText |
| System | windows10 |
| Browser | 谷歌 |

**Comment by IversonzZ** [comment]
谢谢已解决！
用 locale={{emptyText: <span></span>}}代替locale={{emptyText: ""}}

**Comment by pengliheng** [comment]
完全无效....

**Comment by imeime** [comment]
同问，，
