### ISSUE TITLE
The z-index should be changed of Table component fixed columns

### ISSUE THREAD

**Issue by HelloSetsuna** [ant-design/ant-design#15780]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Firstly, the sidemenu's z-index is 10, and the antd-pro componment FooterToolbar's z-index is 9, but Table fixed column's z-index is 20.
When I use Table and FooterToolbar in the same page, the fixed columns will covered FooterToolbar.

### What does the proposed API look like?
I think Table fixed column's z-index should less than 9.

![615299355690926854](https://user-images.githubusercontent.com/19373382/55305298-4fa1db80-5482-11e9-8e8b-522ee55340cf.png)

**Comment by afc163** [comment]
You could change FooterToolbar z-index to a higher level.

**Comment by HelloSetsuna** [comment]
BUT, If I change  FooterToolbar z-index more than 10, it will covered sidemenu, also is a problem

**Comment by HelloSetsuna** [comment]
> You could change FooterToolbar z-index to a higher level.

BUT, if I change FooterToolbar z-index more than 10, FooterToolbar will covered SideMenu

**Comment by HelloSetsuna** [comment]
@afc163 BUT, if I change FooterToolbar z-index more than 10, FooterToolbar will covered SideMenu

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/14036

It is a tricky question now.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15499#issuecomment-478448956

**Comment by HelloSetsuna** [comment]
@afc163 Thanks a lot!
