### ISSUE TITLE
表单校验 是在什么时候开始进行的

### ISSUE THREAD

**Issue by WangGuangCheng2018** [ant-design/ant-design#15783]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w69pw7023k)

### Steps to reproduce
点击提交，在console中可以看到，第二个Form.Item的校验会进行校验，第三个却不会。是为什么呢

### What is expected?
表单校验是在什么时候进行的

### What is actually happening?
无状态组件和原始的三元表达式执行效果一样

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.4.1 |
| System | win7 |
| Browser | chrome |

**Comment by yesmeck** [comment]
Your codesandbox is not working.

**Comment by WangGuangCheng2018** [comment]
> Your codesandbox is not working.

你是不明白我什么意思吗？

> 点击提交的时候表单校验为什么会有两项不通过，页面上只展现了一个表单项
![1554105138(1)](https://user-images.githubusercontent.com/35524901/55311781-66eac400-5496-11e9-8445-f651a456d9c2.jpg)

**Comment by yesmeck** [comment]
你的代码可能没有保存，我看你的 codesandbox 链接现在是不能工作的。

**Comment by WangGuangCheng2018** [comment]
`import React from "react";
import ReactDOM from "react-dom";
import { Form, Input, Button } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const Hidden = props => (props.visible ? props.children : null);

@Form.create()
class App extends React.Component {
  onSubmit = e => {
    e.preventDefault();
    this.props.form.validateFieldsAndScroll((err, values) => {
      console.log(values);
      if (err) return;
      alert("success");
    });
  };

  render() {
    const {
      form: { getFieldDecorator }
    } = this.props;
    return (
      <Form className="App">
        <Form.Item label="itemA">
          {getFieldDecorator("itemA", {
            rules: [{ required: true, message: "input itemA" }],
            initialValue: ""
          })(<Input style={{ maxWidth: "280px" }} />)}
        </Form.Item>
        <Hidden visible={false}>
          <Form.Item label="itemB">
            {getFieldDecorator("itemB", {
              rules: [{ required: true, message: "input itemB" }],
              initialValue: ""
            })(<Input style={{ maxWidth: "280px" }} />)}
          </Form.Item>
        </Hidden>
        {false ? (
          <Form.Item label="itemC">
            {getFieldDecorator("itemC", {
              rules: [{ required: true, message: "input itemC" }],
              initialValue: ""
            })(<Input style={{ maxWidth: "280px" }} />)}
          </Form.Item>
        ) : null}
        <Form.Item>
          <Button type="primary" onClick={this.onSubmit}>
            submit
          </Button>
        </Form.Item>
      </Form>
    );
  }
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
`

**Comment by WangGuangCheng2018** [comment]
你再试下，我在同事电脑上看是没有问题的

**Comment by yesmeck** [comment]
第三个组件没有渲染，当然不会验证。

**Comment by WangGuangCheng2018** [comment]
这段代码粘上去显示不出来
![1554106298(1)](https://user-images.githubusercontent.com/35524901/55312789-e5486580-5498-11e9-8b81-8f227eede286.jpg)

你再看下这个，第二个组件也没有渲染出来啊

**Comment by yesmeck** [comment]
我说的渲染是指 React 调用组件的 render 方法。

**Comment by WangGuangCheng2018** [comment]
那我应该如何写这个Hidden才能不让 field 注册，实际场景中表单很复杂，三元表单式嵌套会很维护

**Comment by yesmeck** [comment]
你可以到 stackoverflow 上问问。
