### ISSUE TITLE
Modal's open animation doesn't start at the click point when rendering for the first time in Table

### ISSUE THREAD

**Issue by GFwer** [ant-design/ant-design#15795]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x2l04pz46z)

### Steps to reproduce
1. create a Table and add a modal function in each row
2. after the first render, trigger the modal function, Modal will transition from the middle of the page instead of from the click point, and after the first trigger, Modal will open with a normal transition

### What is expected?
`Modal` transition from the click point every time

### What is actually happening?
`Modal` transition from the click point after first trigger

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.3 |
| System | MacOS 10.14.3 |
| Browser | Chrome 75 |

**Comment by longlongago2** [comment]
> 我现在遇到的问题是第一次能正常动画，第二次就从中间弹出了

The same problem!

**Comment by ourfeel** [comment]
这代理一个问题。 再微前端下 可能存在重复注册事件
