### ISSUE TITLE
Can not find antd/dist/antd.less

### ISSUE THREAD

**Issue by HsuTing** [ant-design/ant-design#15790]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Yarn add `antd`

### What is expected?
`antd/dist/antd.less` should be included in `node_modules`

### What is actually happening?
`antd/dist/antd.less` missed after version >= 3.16.0

| Environment | Info |
|---|---|
| antd | 3.16.0 |
| React | 16.4.2 |
| System | Mac os 10.14.4 |
| Browser | Chrome 73.0.3683.86 |

**Comment by ztplz** [comment]
Could you create a mini repo?

**Comment by pavelprokes-avast** [comment]
+1

**Comment by crazyx13th** [comment]
+1

**Comment by afc163** [comment]
- https://unpkg.com/antd@3.15.2/dist/antd.less ✅ 
- https://unpkg.com/antd@3.16.0/dist/antd.less ❌

**Comment by afc163** [comment]
@zombieJ

**Comment by Phinome** [comment]
when i found 'antd/dist/antd.less' it's not founded, i face to face.
![image](https://user-images.githubusercontent.com/1940194/55322430-ec7a6e00-54ae-11e9-968e-9179ee139b34.png)

please fixed it, thx.

**Comment by zombieJ** [comment]
Working on this.

**Comment by litlelitleSunshine** [comment]
+1

**Comment by zombieJ** [comment]
Fixed. https://unpkg.com/antd@3.16.1/dist/
