### ISSUE TITLE
inline Menu inside Layout Sider still flash and shake when collapsed

### ISSUE THREAD

**Issue by panjiesw** [ant-design/ant-design#15797]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/o5wk5q9w15)

### Steps to reproduce
Click the menu Icon left side of the Header

### What is expected?
menu inside Layout Sider collapsed with no flash

### What is actually happening?
menu inside Layout Sider collapsed with flash

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | Manjaro 18 |
| Browser | FireFox Developer Edition 67.0b3 (64-bit) |

---
This is related to #15614. I believe this has been fixed in v3.16.0 with #15625. While it's no longer flashing and shaking if Menu is **NOT** inside a Layout Sider, it's still so when used inside Sider.

**Comment by keithort** [comment]
I see this on Chrome 73 on Win10 as well.

**Comment by afc163** [comment]
@zy410419243

**Comment by zy410419243** [comment]
I'm sorry for this bug, but I must focus on my own work this month.

**Comment by liar0720** [comment]
I also saw this Bug!

**Comment by afc163** [comment]
Fixed in #15868

**Comment by Shlok-Zanwar** [comment]
@afc163 It still does flicker for me !
What's the fix ?

**Comment by fedormoore** [comment]
problem still exists

**Comment by Shlok-Zanwar** [comment]
Reopen it ?
