### ISSUE TITLE
Table header is not aligned with table body content after using scroll prop.

### ISSUE THREAD

**Issue by italoborges** [ant-design/ant-design#15794]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0o94jwlmxp)

### Steps to reproduce
When is set a value for y on table prop scroll, the table header doesn't align with the table body content.
If you try to take the Y value away, the table works just fine.

### What is expected?
Table Header aligned with table body content, with the same size for each cell.

### What is actually happening?
Columns width are getting different than the cells content.
They are not aligned to each other.

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.4.1 |
| System | macOS Mojave 10.14.3 |
| Browser | Google Chrome Version 73.0.3683.86 |

---
I know this is a known issue here, but the trick here is that I don't know what will be inside each cell. The values are dynamic, so the columns. I generate the columns based on the source list. I extract the key name for each cell in order to create a new column, therefore, I can't set a fixed width for each column since I don't know what it has inside.

The values inside each column can be a short text, a large text, an image, an url, a boolean, a number, an empty value, etc.

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-fixed-header

> Specify width of columns if header and cell do not align properly. (Leave one column at least without width to fit fluid layout)

Sorry, you have to specify a proper width to columns in fixed header situation, something like`xx%` `xxpx` will be ok.

**Comment by italoborges** [comment]
Yes, I read this, but I thought we could think in some work around since I don't know what it will be inside each cell.

**The column render method** knows what it is its own content, but it cannot change the column width, right?

Thanks.

**Comment by afc163** [comment]
Could you ascertain the content width based on the column title which is something you can know ahead?

**Comment by johnzhu12** [comment]
+1,same issue here

**Comment by italoborges** [comment]
> Could you ascertain the content width based on the column title which is something you can know ahead?

Based on the title yes. What I'm going to try is to calculate a width % based on the cell value length.

**Comment by mrKorg** [comment]
I have the same problem. Doe's somebody have solution?

**Comment by afc163** [comment]
@mrKorg Give me a reproduce and I will fix for you.

**Comment by dcantu96** [comment]
I have the same problem :(

**Comment by triias** [comment]
Same problem here. Anyone found a solution?

**Comment by italoborges** [comment]
I did a workaround to solve this problem.

I don't know if it's the best approach, but to fix the width problem I had to calculate each column's width based on its cell value length.

Now the table will behave normally if you set XScroll, YScroll and fixed columns.

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-tree-ukyy5)

**Comment by quannv** [comment]
This is bug when ant design renders the head and body in different table, please check attached file
<img width="419" alt="GoPanda - Smart Travel System 2019-11-06 11-52-43" src="https://user-images.githubusercontent.com/1892676/68269685-479bc100-008d-11ea-82ac-d2a337dbf36a.png">

**Comment by ericafwalsh** [comment]
+1, same issue here

**Comment by Jeroen-Beljaars** [comment]
I had the same issue, and found a relatively easy workaround! not sure if this is the best approach, but hey it worked!

```
useEffect(() => {
    // Get the tables antd rendered
    const tables = document.getElementsByClassName('ant-table-fixed')

    // Check how many tables where found
    if (tables.length >= 2) {
      // Select the table which contains the header
      const headTable = tables[0];

      // Select the table which contains the body
      const bodyTable = tables[1];

      // Get the width of the table which contains the body
      const tableWidth = bodyTable.children[1].scrollWidth + 1

      // Give the thead table the same width as the tbody table
      headTable.style.width = tableWidth.toString() + 'px';
    }
  })
```

for the scroll on the table itself, set x to max-content.

That did the trick for me, hope it helps!

**Comment by omarragi** [comment]
Does version 4 fix the problem ? it seems it does
v4
https://codesandbox.io/s/fixed-header-ant-design-demo-7uc9e?file=/index.js
v3
https://codesandbox.io/s/cocky-fermat-mrth2?file=/index.js

**Comment by rahuls360** [comment]
I had the similar issue on v3

I set fixed widths for my columns, if their alignment wasn't proper for the header and body.
I determined the width size of column by approximating the largest data for a column I expect to get and setting that width based on trial and error. (75-200px for most fields, few important fields were around 350px)

Regarding the horizontal scroll, I set scroll {{ x: true | 600 }}, that fixed it for me. (Either set true, and antd automatically adds horizontal bar at certain table widths, or manually set at what table width below which horizontal scroll should come)

The scroll misalignment happens between header and content when scroll x is not set.

https://codesandbox.io/s/competent-leaf-fjp1z

**Comment by wang3620** [comment]
+1 same issue here in antd 3.x

**Comment by VaiBho** [comment]
Library uses multiple stacked tables to display one table, it causes it to misalignment of header and body.
I fixed the issue by setting different width for body & header.
There are 2 section under div with class `.ant-table-scroll` 
1. `.ant-table-header`
2. `.ant-table-body`

Set different suitable width for both and done!

**Comment by sharif51693** [comment]
For anyone having this issue, set a width for each of your columns and in the Table, add the following code: scroll={{ x: "max-content" }}. This will adjust your column width automatically.

**Comment by helianthuswhite** [comment]
> For anyone having this issue, set a width for each of your columns and in the Table, add the following code: scroll={{ x: "max-content" }}. This will adjust your column width automatically.

max-content helps!

**Comment by lalnunthar** [comment]
Give you example with Summary Item Report...
1. Add Div Row and Column for Table
2. Remove or comment out stickyHeaderOffsetLeft: and stickyHeaderOffsetRight: from JS

![image](https://user-images.githubusercontent.com/30281970/209567859-080b5a4c-705f-43ac-bd35-66dbc6e71e63.png)
![image](https://user-images.githubusercontent.com/30281970/209568073-2be4db1a-efc7-4818-b726-75153ce3bbaa.png)

result:
![image](https://user-images.githubusercontent.com/30281970/209568119-d05eae01-721b-4652-8fc5-2901bb153309.png)
![image](https://user-images.githubusercontent.com/30281970/209568146-627bafaf-835e-48cc-b741-92c8eebbbf7b.png)

**Comment by sandhya-gururaj** [comment]
max-content helps, but if we add scroll={{x:"max-content"}}, Im not able to add scroll vertically to the body. if I add both x and y scroll, it is breaking the table header and body alignment. Please help
