### ISSUE TITLE
[select] IE9 combobox 模式下 placeholder 盖住了 input

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#158]
由于奇怪的兼容性问题，无法通过 z-index 将 placeholder 设置到 input 下面。

是否可以点击 placeholder 就 focus 到 input 中。

http://ant.design/components/select/#demo-combobox

**Comment by yiminghe** [comment]
rc-select 4.7.2

**Comment by afc163** [comment]
rc-select@4.7.2 貌似 lib/ 和 index.js 都没了。

**Comment by yiminghe** [comment]
4.7.3
