### ISSUE TITLE
Menu 导航菜单 收缩时,首次hover出现闪现,点击后只出现一半图标

### ISSUE THREAD

**Issue by UnicornXU** [ant-design/ant-design#15800]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/UnicornXU/New/blob/master/img/MenuItem.gif](https://github.com/UnicornXU/New/blob/master/img/MenuItem.gif)

### Steps to reproduce
1.现阶段最新版本antd 3.16.0,当我尝试降版本至3.15.0时.没有上述问题出现

### What is expected?
期望升级后的版本相对稳定

### What is actually happening?
实际结果更新版本并没有解决Menu闪现问题

| Environment | Info |
|---|---|
| antd | 3.16.0 |
| React | 16.8.4 |
| System | Win10 |
| Browser | 谷歌    版本 73.0.3683.86 |

**Comment by UnicornXU** [comment]
@zy410419243 @afc163

**Comment by UnicornXU** [comment]
![image](https://github.com/UnicornXU/New/blob/master/GIF.gif)
antd  3.15.0版本效果

**Comment by ztplz** [comment]
@UnicornXU  给个重现？

**Comment by afc163** [comment]
Fixed in #15868

**Comment by UnicornXU** [comment]
谢谢  已解决

**Comment by UnicornXU** [comment]
谢谢  升级3.16.2版本  解决

**Comment by UnicornXU** [comment]
> @UnicornXU 给个重现？

重现困难,但升级后确实解决了我的问题
