### ISSUE TITLE
请填写简洁有效的标题

### ISSUE THREAD

**Issue by stand1921** [ant-design/ant-design#1580]
**问题描述**

（描述一下问题）

使用antd-init构建项目后
npm run dev后报以下错误：

ERROR in ./~/.npminstall/antd/0.12.16/antd/lib/index.css
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/home/u/blog/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/common/lib.js 3:0-29

ERROR in ./src/component/App.less
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (/home/u/blog/node_modules/.npminstall/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/loader.js:21:9)
 @ ./src/component/App.jsx 15:0-21

**发生环境**

- antd 版本：   antd-init 版本 0.8.3
- 操作系统及版本：ubuntu 14.04 server
- 浏览器及版本：无
- 在线演示地址：无

**重现步骤**
    sudo npm i antd-init -g
    mkdir blog && cd blog
    antd-init
    npm run dev

感觉目前ant design的几个库命名极为混乱，只有专业的ant design人员才能分清什么是什么，比如
“Ant-Tool” 标题下有 “ant-tool”，这两个是同一个东西吗？教程里有 "antd-init"这个和ant-tool是同一个东西吗？ 还有 atool-build、atool-test、atool-doc这些都是同一个项目的子集吗？同一个脚手架下为什么有这么多命名风格迥异的名字？统一一下是不是更好，比如都叫ant-init、ant-build、ant-doc这样子统一命名风格。

**Comment by afc163** [comment]
Try reinstall `rm -rf node_modules && npm i`.

Ant Tool 是蚂蚁金服的研发工程相关工具，Ant Design 是设计语言，关系不大。你在这里需要的关注和了解的只有脚手架 antd-init 。当然自己搞工作流也是可以的，都是 webpack + npm 的体系。
