### ISSUE TITLE
Tooltip does not work when children is a svg icon that use svg-sprite-loader

### ISSUE THREAD

**Issue by rumsky** [ant-design/ant-design#15802]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当被包裹元素是一个svg-sprite-loader引入的svg icon时， tooltip不生效

### What does the proposed API look like?
当被包裹元素是一个svg-sprite-loader引入的svg icon时， tooltip应该生效

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue with reproducible demo.

**Comment by xueerli** [comment]
您好，这个问题解决了吗？怎么解决的？
