### ISSUE TITLE
When set trigger: 'onBlur' in the options object of getFieldDecorator() the Input doesn't respond and antd doesn't collect the value on 'onBlur'

### ISSUE THREAD

**Issue by rhap5ody** [ant-design/ant-design#15818]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vqy3zklor3)

### Steps to reproduce
Start writing in the input box and nothing will be shown.

### What is expected?
Input to work normally, to show the text that you type in it. The idea is, antd to collect the written text when onBlur occurs, because with the default onChange trigger, it is very laggy.

### What is actually happening?
The input doesn't respond in any way, and inspecting the html, there is a value attribute on the input that doesn't change on onBlur event.

| Environment | Info |
|---|---|
| antd | 3.10.3 |
| React | 16.6.0 |
| System | Linux Mint 19 Cinnamon 3.8.9 |
| Browser | Google Chrome 72.0.3626.119 (Official Build) (64-bit) |

---
I have many forms in my app and they are all very laggy from the smallest to the largest one. I have to find a solution for this with antd, otherwise I'll have to rewrite the forms with some other library which is not the way I want to go.

**Comment by ztplz** [comment]
Do not use both `trigger` and `validateTrigger`. 
![image](https://user-images.githubusercontent.com/17755202/55681184-d9a3e580-5955-11e9-8180-f397ab1fe35a.png)
If your form has serious performance issues, you can split the form or validate it during input `blur`.

**Comment by rhap5ody** [comment]
@ztplz I accidentally left the `validateTrigger` option because I experimented with various options, but that doesn't change the behavior of the snippet. If you delete it, nothing changes. My idea is for `antd` to collect the text that I type in the input `onBlur` and not on every keystroke. For example I start typing in it, and I open dev tools, I see that the value on the input changes on every keystroke. I want to type in the input and `antd` to get the value when `onBlur` event occurs.

**Comment by zombieJ** [comment]
`trigger` means when to collect value. When your set to `onBlur`, it will not collect value on `onChange` event. 
In your case, you can keep `trigger` with `onChange` and `validateTrigger` with `onBlur`.


Since your reproduce not provides any laggy on it, we can't help more about this.

Please feel free to enhance your reproduce and I will reopen this issue.

**Comment by rhap5ody** [comment]
@zombieJ As I mentioned above, I incidentally left the `validateTrigger` option because of experimenting. Now with only the `trigger` as an option, it behaves the same. Nothing is written in the input, and also nothing happens when `onBlur` event happens. I hope my question is  more understandable now.

**Comment by zombieJ** [comment]
Hi @rhap5ody , please see my comment above:
> `trigger` means when to collect value. When your set to `onBlur`, it will not collect value on `onChange` event.

Input provides latest typing value on `onChange`. You should not set to `onBlur`.

**Comment by mikeyzhe** [comment]
I have the same issue. @rhap5ody ,   have you found any solution yet?

@zombieJ ,  the solution you suggest didn't work either.

**Comment by 1443658** [comment]
Is there any update?

**Comment by rhap5ody** [comment]
@mikeyzhe No I haven't found one yet, the forms are still slow. Were you able to find anything?

**Comment by 1443658** [comment]
I found that If you add ```valuePropName: 'defaultValue'``` prop on ```getFieldDecorator()```(see below), it seems solved the problem.

```
<FormItem {...formItemLayout} label="Name">
  {getFieldDecorator(`input_name`, {
	trigger: "onBlur",
	valuePropName: "defaultValue"
  })(<Input />)}
</FormItem>
```

Hope it helps!

**Comment by rhap5ody** [comment]
@1443658 Thank you for the response! This seems to solve the problem, but now I've run into another problem. When I use mapPropsToFields to store data in an upper component it doesn't work. When I open DevTools it changes the value as I type, like it did before. Any suggestions about this?

**Comment by 1443658** [comment]
@rhap5ody No problem, I'm glad it helped!

**Comment by annjawn** [comment]
I have use this in my forms to overcome the performance issues

```
trigger: 'onBlur',
valuePropName: 'defaultValue',
```
Everything works but it looks like `this.props.form.resetFields()` is not working (with and without field name array).

**Comment by duziten** [comment]
same question, solved: don't use `trigger: 'onBlur'` but `validateTrigger: 'onBlur'`

> `trigger` means when to collect value. When your set to `onBlur`, it will not collect value on `onChange` event.
> In your case, you can keep `trigger` with `onChange` and `validateTrigger` with `onBlur`.
> 
> Since your reproduce not provides any laggy on it, we can't help more about this.
> 
> Please feel free to enhance your reproduce and I will reopen this issue.

speaking very clearly

**Comment by ktualhu** [comment]
<ins></ins>

**Comment by ktualhu** [comment]
****

**Comment by ktualhu** [comment]
###

**Comment by ktualhu** [comment]
****
