### ISSUE TITLE
DatePicker 中文化后显示中英文混杂

### ISSUE THREAD

**Issue by anbee** [ant-design/ant-design#15814]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m7m4698n89)

### Steps to reproduce
已做zh-CN中文配置，DatePicker 点击后弹出中文 英文组合的框，如【2019年Apr】。

### What is expected?
DatePicker 中文化正常

### What is actually happening?
DatePicker 中英文混杂

| Environment | Info |
|---|---|
| antd | 3.16.0 |
| React | ^16.8.3 |
| System | 5.4 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/pkp40j4x8x

```diff
 - "moment": "2.22.0",
 + "moment": "^2.22.0",
}

https://codesandbox.io/s/pkp40j4x8x
