### ISSUE TITLE
normalize.css should be updated

### ISSUE THREAD

**Issue by dracupid** [ant-design/ant-design#1581]
Normalize.css is now v4.1.1, please consider to update it to the latest version (v3.0.3 now) and put it under the management of npm.

You can import a css file in less by
```less
@import (less) "../node_modules/normalize.css/normalize.css";
```

:)

**Comment by RaoHai** [comment]
PR: https://github.com/ant-design/ant-design/pull/1583

**Comment by afc163** [comment]
记录一下：https://github.com/ant-design/antd-init/issues/52
