### ISSUE TITLE
DatePicker控件手工输入日期需要支持简化格式以及手工输入公元前负数年的时候无法自动填充

### ISSUE THREAD

**Issue by AllenLiuGit** [ant-design/ant-design#15816]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
手工输入日期更友好

### What does the proposed API look like?
1、手工输入日期，例如，2019-1-1，可以自动识别为YYYY-MM-DD格式

2、负数输入时，也可以识别，有些公元前的需求，例如，-100-01-01，目前手工输入无法自动识别

3、年、月、日可以部分输入，例如，同一个日期框，可以只输入2019，也可以输入2019-01，或者2019-01-01

**Comment by zombieJ** [comment]
format 支持多个格式的，展示以第一个为准，转换都会试一遍。
