### ISSUE TITLE
Collapsed Menu/MenuItem when selected does not consistently display the selected blue border on right

### ISSUE THREAD

**Issue by kapso** [ant-design/ant-design#15819]
- [ X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yko3o47rk9)

### Steps to reproduce
- Click on the menu item to trigger selected item behavior - as expected you will notice light blue background and blue border on right for the selected menu item.
- Move the mouse away from the menu.
- Click on the menu item to trigger selected item behavior, notice how blue border on right is no longer visible.

### What is expected?
When a menu item is selected, it should display blue border on right.

### What is actually happening?
When a menu item is selected, it should display blue border on right. But as soon as you move the mouse away from the menu and click the menu item again, the behavior changes.

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.3 (18D109) |
| Browser | Chrome version 73.0.3683.86 |

---

**Comment by ztplz** [comment]
ref: https://github.com/ant-design/ant-design/issues/15801

**Comment by afc163** [comment]
Fixed in #15868
