### ISSUE TITLE
locale prop in TimePicker

### ISSUE THREAD

**Issue by slillo** [ant-design/ant-design#15813]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TimePicker should have locale prop like DatePicker.

### What does the proposed API look like?
    import {default as localeTimePicker} from 'antd/lib/time-picker/locale/it_IT'
    <TimePicker locale={localeTimePicker} />

**Comment by afc163** [comment]
Try http://ant.design/components/locale-provider-cn/

**Comment by slillo** [comment]
I know about LocaleProvider but I think that all component with predefined placeholder and other localized stuff should have locale prop like DatePicker as a matter of consistency among different components.

**Comment by afc163** [comment]
It is a bug that TimePicker cannot accept `locale`: https://codesandbox.io/s/w0lq4y3xzk, same as DatePicker did: https://github.com/lixiaoyang1992/ant-design/commit/5cb5d24b36134328118b86495673721376ad5f1d#diff-445124112dd9f0351d08fc65beceede5R83

**Comment by byFadili** [comment]
I encountered this same bug using antd version 3.16.1

**Comment by dengfuping** [comment]
@byFadili Fixed in version 3.16.2.
