### ISSUE TITLE
Drawer事件绑定问题

### ISSUE THREAD

**Issue by shouhe** [ant-design/ant-design#15823]
The issue which is not created via http://new-issue.ant.design will be closed immediately.
版本：antd v3.13.6
问题：
![image](https://user-images.githubusercontent.com/15084897/55452258-69b9f600-5609-11e9-8af7-4821c9be7fb5.png)
描述：为什么callback是null? 可以用哪空对象代替吗
---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/issues/477#issuecomment-479356986
