### ISSUE TITLE
希望antd的Button组件出一个文字按钮

### ISSUE THREAD

**Issue by SmallPolaris** [ant-design/ant-design#15826]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
纯 文字形式的按钮，但是具有Button的所有属性，就像Element-ui的文字按钮一样
http://element-cn.eleme.io/#/zh-CN/component/button#wen-zi-an-niu

### What does the proposed API look like?
type:text

**Comment by zombieJ** [comment]
为什么不用 `<a>content</a>` 呢？

**Comment by SmallPolaris** [comment]
我需要disabled属性，还有 size等等，嘻嘻嘻

**Comment by afc163** [comment]
a 有 `disabled` 属性，size 可以用 `font-size`。

**Comment by SmallPolaris** [comment]
好吧，还是希望你们能出一个

**Comment by afc163** [comment]
text button 是有强烈的设计规范考量的：https://material.io/design/components/buttons.html Material 里的 text button 对应的是 antd 的默认 `<Button><Button>` 按钮。Ant Design 设计规范里目前没有添加 text button 的考量。

**Comment by zombieJ** [comment]
感觉可以再探讨一下，`type="text"` 对标的应该不是 `<a />`，是占据相同空间的文本样式按钮：

* https://getbootstrap.com/docs/4.0/components/buttons/#examples
* https://material-ui.com/demos/buttons/#text-buttons
* http://element-cn.eleme.io/#/zh-CN/component/button#wen-zi-an-niu

ref #15892

**Comment by XianZhengquan** [comment]
就是这种感jio

**Comment by jim888666** [comment]
发现好多设计图需求这种文字按钮，建议官方推出  ，

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16289
