### ISSUE TITLE
TreeSelect组件的的的错误

### ISSUE THREAD

**Issue by GanBaby** [ant-design/ant-design#15820]
当TreeSelect组件的内容用的是json格式的时候第二次渲染时会报Uncaught TypeError: Cannot read property 'offsetHeight' of undefined异常，虽然不会影响数据的正常交互，但是还是希望蚂蚁大大能够解决这个小问题

**Comment by zhangwei900808** [comment]
同遇相同问题

**Comment by afc163** [comment]
Duplicate of #15574
