### ISSUE TITLE
使用Steps配合Form时，如何每一步都校验不同的Form

### ISSUE THREAD

**Issue by juneryo** [ant-design/ant-design#1582]
比如说有三个不同类型的自定义Form组件。
`<Form1 />` `<Form2 />` `<Form3 />`
分别都用_createForm()(xxx)_做了包装。
如何在切换步骤的时候，指定校验其中一个Form呢？
代码大概就类似下面的样子，点一下按钮，校验Form1，再点一下，校验Form2。
```
<div>
    <Steps>...<Steps>
    <Form1 />
    <Form2 />
    <Form3 />
    <Button />
</div>
```

**Comment by benjycui** [comment]
给 `Form` 传入一个 `current` 之类的属性，在 `componentWillRecieveProps` 中判断是否触发校验。

**Comment by juneryo** [comment]
@benjycui 
刚才这样试了以下，可以触发校验，不过存在一个问题。
外部修改current后，**_componentWillRecieveProps_**被触发，进行校验。
但是**this.props.form.validateFields**方法同样会触发**_componentWillRecieveProps_**，
然后就是无限循环了。。。

**Comment by juneryo** [comment]
目前是在自定义Form组件中额外添加一个状态，双重判断来避免循环校验。
不过还有一个问题，外部如何才能获取校验结果呢。。。

**Comment by benjycui** [comment]
目前没想到更好的方案 :-(

其实这个问题可以抽象为：owner 如何触发 ownee 的行为，在 jQuery 中直接调用就行了，但 React 并不鼓励这么做（除了 `this.ref.xxx.focus`） 。

现在这个方案是 owner 向 ownee 传一个属性作为信号，ownee 判断信号调整自身行为。在大多数情况下是 OK 的，但是因为 `Form` 调用了 HOC 的 `validateFields` 再次触发自身的 `componentWillRecieveProps`，就有坑了。

有时间再思索下。。。

**Comment by codering** [comment]
遇到类似的问题了。 现在有好一点的方案吗？

**Comment by WinterWoods** [comment]
有没有更好的解决方案现在.

**Comment by MrCuriosity** [comment]
路由
```jsx
<Route path={'/path/to/StepsWithForms/:current'} component={withRouter(StepsWithForms)} />
```
组件
```jsx
class StepsWithForms extends React.Component {
	constructor() {
		super(props)
	}
	render() {
		const current = parseInt(this.props.params.current, 10)
		return (
			<div>
				<Steps current={current}></Steps>
				{ current === 1 ? <Form1 /> : null }
				{ current === 2 ? <Form2 /> : null }
				{ current === 3 ? <Form3 /> : null }
			</div>
		)
	}
}
export default connect(mapStateToProps)(StepsWithForms)
```
model
这个`current`的改变，只能够通过子Form`dispatch action`给model，并且成功回调以后
```jsx
yield put(routerRedux.push({ pathname: 'path to next form' }))
```
这样数据流向还是比较清晰的闭环，既可以用`current`同步Steps和Forms状态，并且还能同步路由
不过我没实践过，都是脑补的，有问题欢迎指出

**Comment by ClausClaus** [comment]
emmmm......这个Steps配合Form的问题现在有比较好的解决方案了吗。。。

**Comment by fightingljm** [comment]
[解决方案](https://stackoverflow.com/questions/63807887/antd-v4-steps-and-form/63809607#63809607?newreg=0bb869e1372d4e48bcb9152d3003fcd9)
