### ISSUE TITLE
table fixed hover是设置高度，当点击左边的checkbox导致fixedtable 和 table row的高度不等

### ISSUE THREAD

**Issue by FrontCoder1** [ant-design/ant-design#15822]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jzk5y47o35)

### Steps to reproduce
点击上面的链接即可

### What is expected?
点击左边的checkbox两边的高度相等，或者鼠标移出后恢复原来的高度

### What is actually happening?
两边的高度不相等，鼠标移出后height保持

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | v16.6 |
| System | mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
虽然你使用方式有点奇怪，但是看上去确实是一个高度同步的 bug。

**Comment by FrontCoder1** [comment]
> 虽然你使用方式有点奇怪，但是看上去确实是一个高度同步的 bug。

这是业务上用到的，只不过我是用设置的高度的方法代替的具体业务需求

**Comment by afc163** [comment]
Duplicate of #14859
