### ISSUE TITLE
Upload组件 实现1) 上传列表数量的限制。  2) 读取远程路径并显示链接。  3) 按照服务器返回信息筛选成功上传的文件。

### ISSUE THREAD

**Issue by SmallPolaris** [ant-design/ant-design#15824]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oomyjz460q 和 官网 https://ant.design/components/upload-cn/#components-upload-demo-fileList)

### Steps to reproduce
选择一个文件上传，默认展示的文件被干掉了

### What is expected?
默认展示的文件依旧展示，并且上传之后的文件也展示

### What is actually happening?
默认展示的文件被干掉了

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.4 |
| System | windows10 |
| Browser | chrome73 |

---
上传到自己的服务器上面，根据服务器的返回状态进行展示文件列表

**Comment by travonf** [comment]
> POST https://jsonplaceholder.typicode.com/posts/ 503

> Access to XMLHttpRequest at 'https://jsonplaceholder.typicode.com/posts/' from origin 'https://oomyjz460q.codesandbox.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

看情况是测试用api的跨域问题, 无法拿到fileList

**Comment by SmallPolaris** [comment]
不是的，是fileList.filter 过滤掉了 默认的文件

**Comment by afc163** [comment]
```
    fileList: [{
      uid: '-1',
      name: 'xxx.png',
      status: 'done',
      url: 'http://www.baidu.com/xxx.png',
    }],
```

```
     if (file.response) {
        return file.response.status === 'success';
      }
```

状态判断不一致。
