### ISSUE TITLE
Statistic <Countdown>

### ISSUE THREAD

**Issue by heimaozi** [ant-design/ant-design#15821]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/statistic-cn/](https://ant.design/components/statistic-cn/)

### Steps to reproduce
..

### What is expected?
now: Countdown  value={1554431765241} format="D Days H : m : s" 
Render result： 1 1ay5 23 : 14 : 5

In rendering results 1ay5 ，It's not the result I want.

how to 'Days' rendered as string 'Days' ，Instead of   D to 1   , s to 5

### What is actually happening?
Render result： 1 1ay5 23 : 14 : 5

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | react |
| System | window |
| Browser | chrome |

---

**Comment by afc163** [comment]
Please create you issue with readable format.

**Comment by mtsalenc** [comment]
@heimaozi Did you figure out a solution to this?

**Comment by nbouliol** [comment]
from moments doc
> moment().format('YYYY [escaped] YYYY');                    // 2019 escaped 2019

```javascript 
<Statistic.Countdown value={new Date(data.date)} format={"D [Days] H : m : s"} />
```
