### ISSUE TITLE
how to set mode of popup menu

### ISSUE THREAD

**Issue by Lynn0108** [ant-design/ant-design#15838]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
how can I set mode in popup menu?
I found it is default vertical, but I would it to be inline mode. 

### What does the proposed API look like?
add a attribute in Menu component like popupMenuMode

**Comment by afc163** [comment]
Not support now and maybe won't.
