### ISSUE TITLE
Expose event object of onClick event for Select component

### ISSUE THREAD

**Issue by pdoongarwal** [ant-design/ant-design#15833]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In my case, I want to stop propogation of this event to its parent elements.

### What does the proposed API look like?
onClick(event) => {}

**Comment by afc163** [comment]
Why did you need the `onClick` prop?

**Comment by pdoongarwal** [comment]
I want to stop propogation of this event to its parent elements.

**Comment by afc163** [comment]
```jsx
<span onClick={e => e.stopPropagation()}><Select /></span>
```
