### ISSUE TITLE
TextArea in Form bring Assertion failed on Enter hit

### ISSUE THREAD

**Issue by Far3t** [ant-design/ant-design#15836]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l4p5prpzzq)

### Steps to reproduce
Add a TextArea in a Form.
Each time you hit the Enter button in the TextArea you'll get:

*Assertion failed: Input argument is not an HTMLInputElement*

Moreover, you can see the assertion failed on the form to create issue in the console: https://new-issue.ant.design/ 

### What is expected?
No error

### What is actually happening?
The TextArea element is an HTMLTextAreaElement.

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | Ubuntu 18.04.1 LTS |
| Browser | Chrome 73.0.3683.75 |

**Comment by Far3t** [comment]
Already a codesandbox example to reproduce it.
Or just the create issue form you provide to open issues on GitHub.

Just as I said in the issue.

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/55472614-1f536c00-563f-11e9-9ca0-ee1c3b36c264.gif)

Cannot reproduce in your demo.

**Comment by Far3t** [comment]
![Peek 03-04-2019 12-58](https://user-images.githubusercontent.com/1713404/55474093-a1786c00-5610-11e9-93a8-31c34de9721a.gif)

Maybe it's a browser issue?
But doesn't seem like it because it is the same error on Firefox or Chrome for me.

**Comment by afc163** [comment]
Could you check your browser plugin list?

**Comment by afc163** [comment]
I believe it is a problem from lastpass app: https://forums.lastpass.com/viewtopic.php?f=12&t=274205

**Comment by Far3t** [comment]
Oh...
Yes, you're right.
Launching browser without plugins is ok...
Sorry for the inconvenience :-(
