### ISSUE TITLE
on clicking Switch it gives a very bad vibration, also if the switch is clicked and holded then the circle of the switch gets bigger abroptly ,which looks like a bug

### ISSUE THREAD

**Issue by duke7able** [ant-design/ant-design#15835]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8x1y5j8m29?fontsize=14)

### Steps to reproduce
clicking and holding or just clicking the switch

### What is expected?
on clicking Switch it gives a very bad vibration,
 also if the switch is clicked and holded then the circle of the switch gets bigger abroptly ,which looks like a bug,
It creates a very bad UX

### What is actually happening?
bad UX

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.3 |
| System | mac OS 10.13 (17A405) |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36 |

**Comment by afc163** [comment]
It is by designed, to indicate the pressed state in UI.
