### ISSUE TITLE
treeSelect的onChange/onSelect是否支持获取选中节点的父节点信息?

### ISSUE THREAD

**Issue by soybeanxiaobi** [ant-design/ant-design#15831]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
通过treeData渲染的treeSelect组件,当选择其中一个子节点时,会返回当前节点信息,但无法获取其父节点.请问有什么办法解决？

### What does the proposed API look like?
onChange = keys=> {
   console.log(keys); // 希望keys包含父节点信息
}

**Comment by zombieJ** [comment]
从性能考虑，父节点信息是不透出的。但是你可以自己用 map 来处理一下：https://codesandbox.io/s/wk080nn81k

**Comment by afc163** [comment]
FAQ it?

**Comment by soybeanxiaobi** [comment]
> FAQ it?

yes...it is

**Comment by soybeanxiaobi** [comment]
> 从性能考虑，父节点信息是不透出的。但是你可以自己用 map 来处理一下：https://codesandbox.io/s/wk080nn81k
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/10e34a4561364757c0cba26405ba79cb73293541/68747470733a2f2f636f646573616e64626f782e696f2f6170692f76312f73616e64626f7865732f776b3038306e6e38316b2f73637265656e73686f742e706e67">CodeSandbox**[wk080nn81k - CodeSandbox](https://codesandbox.io/s/wk080nn81k)**The online code editor tailored for web applications

谢谢 我看看～

**Comment by zombieJ** [comment]
有道理，加个 FAQ 去。
