### ISSUE TITLE
DatePicker  defaultValue和defaultPickerValue 不能共存

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#15840]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)]

### Steps to reproduce
同时给 DatePicker 设置  defaultValue 和 defaultPickerValue 

### What is expected?
默认选中的日期defaultValue是当前日期的前7天或前几天，日期面板右侧显示当前月

### What is actually happening?
当月初月末的时候，看起来是正常的，如果默认选中日期defaultValue是月中，比如7号~12号，当前是12号， 默认面板左侧会展示当前月，右侧会展示下个月，而且这个demo看起来怪怪的，为什么左右显示相同月份

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | React 16 |
| System | Win10 |
| Browser | Chrome最新 |

---
应用场景比如记录日志，审计之类，只能选择当前日期之前的范围

**Comment by afc163** [comment]
- `3.15`: https://codesandbox.io/s/q9zq4y7w6q
- `3.16`: https://codesandbox.io/s/0pqo73jr9n

这里有个问题，3.15 是右边必须大于左边，https://github.com/react-component/calendar/pull/478 的修复后应该是右边必须大于等于左边。但是看例子，现在右边可以小于左边了。

<img width="564" alt="图片" src="https://user-images.githubusercontent.com/507615/55480385-c4c40b00-5652-11e9-9139-d8cb77cf9913.png">

**Comment by zombieJ** [comment]
嗯……
看下来受控做成可以选同一个月和 RangePicker 正常使用展示是冲突的。如果月份面板可以选择同一个月，打开后的日期面板肯定也是能选同一个月的。
感觉需要 Revert 掉。

**Comment by afc163** [comment]
#13302 的问题好像和受控做成可以选同一个月没啥关系，只是一个月份是否 disabled 的问题。就是影响了 Date 面板。

<img width="584" alt="图片" src="https://user-images.githubusercontent.com/507615/55485542-3b660600-565d-11e9-9bc9-4c9d1b1f5b02.png">

<img width="565" alt="图片" src="https://user-images.githubusercontent.com/507615/55485627-63ee0000-565d-11e9-84f4-f54cf54b49c2.png">

**Comment by zombieJ** [comment]
> #13302 的问题好像和受控做成可以选同一个月没啥关系，只是一个月份是否 disabled 的问题。就是影响了 Date 面板。

因为普通模式下，点击月份后会变成现实日期面板。如果这里选择同一个月，那其实还是可以打开同一个月份的日期面板。

**Comment by afc163** [comment]
原来如此，好纠结的设定。

**Comment by zombieJ** [comment]
我感觉先 Revert 掉后，改成点相同月份两次就变成选择同一个月，相对来说代价会小一点。就是用户很难感知到。

**Comment by afc163** [comment]
或者这样，保持现有的两边相同月份可点的逻辑。

然后在普通模式下，点击右边月份后，如果左边和右边相同，把左边挤到前一个月去？

**Comment by zombieJ** [comment]
有点反直觉……

**Comment by zombieJ** [comment]
不过我觉得可以

**Comment by zombieJ** [comment]
逻辑调整成：
* 日期面板时，相差一个月
* 任意一个面板在月份下点击切换成日期，如果另一个面板是相同月份就前/后推一个月

**Comment by afc163** [comment]
年比较蛋疼。。

**Comment by zombieJ** [comment]
年的话也一样，点击到日期后自动位移另一个。反正就是日期特殊处理一下下~

**Comment by afc163** [comment]
有点晕，到时候搞个 PR 实际操作看看。

**Comment by alex89lj** [comment]
目前日期和月份的耦合在一起 确实容易这里一改就会导致另一个地方有问题 上次还可以检查了一下  真是惭愧呀 我觉得后面这个方案没毛病

**Comment by zombieJ** [comment]
@alex89lj `rc-calendar` 坑挺多，的确是不好处理的说 😄

**Comment by alex89lj** [comment]
我清明应该有时间  如果需要的话 我可以试着提个PR

**Comment by Zero0331** [comment]
![image](https://user-images.githubusercontent.com/32761933/55529378-b964f400-56d3-11e9-99d4-4880949ee9be.png)
不知道这张图能不能加载出来，其实我更希望是这种展示
假设今天是3月19号，默认选中时间是12号~19号，默认面板是当前月和前一个月

**Comment by Zero0331** [comment]
如果没有defaultValue    默认面板defaultPickerValue就可以展示对应月份的

**Comment by Zero0331** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)]
> (https://codesandbox.io/s/k511r91z3o)
> 
> ### Steps to reproduce
> 同时给 DatePicker 设置 defaultValue 和 defaultPickerValue
> 
> ### What is expected?
> 默认选中的日期defaultValue是当前日期的前7天或前几天，日期面板右侧显示当前月
> 
> ### What is actually happening?
> 当月初月末的时候，看起来是正常的，如果默认选中日期defaultValue是月中，比如7号~12号，当前是12号， 默认面板左侧会展示当前月，右侧会展示下个月，而且这个demo看起来怪怪的，为什么左右显示相同月份
> 
> Environment	Info
> antd	3.16.1
> React	React 16
> System	Win10
> Browser	Chrome最新
> 应用场景比如记录日志，审计之类，只能选择当前日期之前的范围



> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)]
> https://codesandbox.io/s/988663kroo
> 
> * [https://codesandbox.io/s/988663kroo]
> 
> ### Steps to reproduce
> 同时给 DatePicker 设置 defaultValue 和 defaultPickerValue
> 
> ### What is expected?
> 默认选中的日期defaultValue是当前日期的前7天或前几天，日期面板右侧显示当前月
> 
> ### What is actually happening?
> 当月初月末的时候，看起来是正常的，如果默认选中日期defaultValue是月中，比如7号~12号，当前是12号， 默认面板左侧会展示当前月，右侧会展示下个月，而且这个demo看起来怪怪的，为什么左右显示相同月份
> 
> Environment	Info
> antd	3.16.1
> React	React 16
> System	Win10
> Browser	Chrome最新
> 应用场景比如记录日志，审计之类，只能选择当前日期之前的范围
> 
> * [ ]
> * [ ]
