### ISSUE TITLE
Add a height attribute to progress component

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#15848]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently there is no ability to control the height of the `ant-progress-bg` style as the div created by `Progress` sets an `8px` height on style. I'd like to be able to control this height for some certain applications

### What does the proposed API look like?
```
<Progress
  percent={progress}
  height={12}
/>
```

**Comment by ztplz** [comment]
https://codesandbox.io/s/m9qyq5qrny
`strokeWidth` work for me.
