### ISSUE TITLE
In the Table component's column prop, setting the align property to right only aligns the table rows not the table header if sorting is enabled

### ISSUE THREAD

**Issue by AustinGreen** [ant-design/ant-design#15846]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7269lj9n76)

### Steps to reproduce
- Create an antd Table with the columns prop set to an array of objects
- In one of those objects set the align property to `right` and the sorter property to `(a, b) => a.age - b.age`
- Observe that the column header is aligned left and the rows are aligned right

### What is expected?
That the column header would also be aligned right

### What is actually happening?
That the column header would also be aligned left

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | macOS 10.14.4 |
| Browser |  Google Chrome	73.0.3683.86 |

---
I believe this PR introduced the bug: #15758

**Comment by ztplz** [comment]
Looks like a default behavior. 
`version 3.12.0`
![image](https://user-images.githubusercontent.com/17755202/55490342-36f21b00-5666-11e9-8532-a00f65df2f02.png)

**Comment by ajorlando** [comment]
![Screenshot 2019-04-03 13 41 29](https://user-images.githubusercontent.com/4954736/55500375-36319880-5616-11e9-86f2-d32c552492dd.png)

The headers were working this way in 3.15.2 and are back to that behavior in 3.16

**Comment by afc163** [comment]
broken by #15758

**Comment by ajorlando** [comment]
Will a update that for this be coming in an upcoming version?
