### ISSUE TITLE
怎样去扩展ant-design才是最佳实践呢？

### ISSUE THREAD

**Issue by senro** [ant-design/ant-design#1584]
当某个ant-design组件不满足某个特殊需求的时候，直接改组件源码的话，下次安装容易被覆盖？如果重新拷贝该组件起一个新的名字，扩展完后再上传到npm，会导致同类型的组件变多，起名字也是个问题？有点疑惑，求高手指点，感激不尽！

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#how-to-extend-antds-components

Please read [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
