### ISSUE TITLE
Menu and Steps components do not properly render after antd version update

### ISSUE THREAD

**Issue by MFoksik** [ant-design/ant-design#15849]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/018ywp01ov)

### Steps to reproduce
Step component:
- props: 
  - progressDot={true}
  - size="small"

Menu component:
- props:
  - mode="inline"
  - inlineCollapsed={true}

### What is expected?
Step component:
- dots should be placed corectly

Menu component:
- menu should be collapsed on start
- after hover on menu element, there should be tooltip visible

### What is actually happening?
Step component:
- dots are misplaced, and shifted to the left

Menu component:
- even if props are defined properly, menu is not collapsed on start
- there is no tooltip visible after hovering on menu elements

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | Windows 10.0.17763 |
| Browser | Chrome 73.0.3683.86 |

---
Going back to ant 3.14.1 everything works fine:

https://codesandbox.io/s/4j6wmx4jl0

**Comment by afc163** [comment]
Menu problem trace in #15849 and I am fixing Steps style.

**Comment by afc163** [comment]
ref #15566

**Comment by MFoksik** [comment]
Hi, thanks for fixes. Steps works ok, default menu is now collapsed on start, but there is no tooltip on menu elements:

![image](https://user-images.githubusercontent.com/13439968/55720090-3d82e880-5a00-11e9-8682-87041e4fcb00.png)

Could you please fix this one too?
