### ISSUE TITLE
table onCell rowIndex is undefined

### ISSUE THREAD

**Issue by w521aaa** [ant-design/ant-design#15845]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.meiyou.com](http://www.meiyou.com)

### Steps to reproduce
const columns = [{          
  title: '姓名',          
  dataIndex: 'name',          
  key: 'name',          
  onCell: (record, rowIndex) => ({          
         onClick: () => {           
           console.log(rowIndex);            
          }          
  })          
}];          

### What is expected?
rowIndex该cell的正确行号

### What is actually happening?
undefined

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 5.6.0 |
| System | windows7 |
| Browser | chrome |

**Comment by xqliu** [comment]
Can you please share what's happening on your side?

I also facing this issue in onCell.

Thanks.

**Comment by xqliu** [comment]
Just FYI, rowIndex support was added on version 3.11.

The antd version I used is 3.10.3, that's the issue.

**Comment by w521aaa** [comment]
you are right.
