### ISSUE TITLE
Layout中的Menu收缩的异常闪动

### ISSUE THREAD

**Issue by Lzw2016** [ant-design/ant-design#15858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qv4wyzm73q)

### Steps to reproduce
浏览器打开 [https://codesandbox.io/s/qv4wyzm73q](https://codesandbox.io/s/qv4wyzm73q)  连接， 点击 收缩菜单按钮，看到明显的菜单闪动

### What is expected?
收缩菜单时菜单别闪动

### What is actually happening?
浏览器打开 [https://codesandbox.io/s/qv4wyzm73q](https://codesandbox.io/s/qv4wyzm73q)  连接， 点击 收缩菜单按钮，看到明显的菜单闪动

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.7.0 |
| System | win10 |
| Browser | 谷歌 火狐 |

---
官方虽然说 3.16.0  修复 Menu 收缩的异常闪动。[#15625](https://github.com/ant-design/ant-design/pull/15625)
但是当 Menu 与 Layout 联合使用就会有问题

**Comment by Lzw2016** [comment]
[https://codesandbox.io/embed/qv4wyzm73q](https://codesandbox.io/embed/qv4wyzm73q)

**Comment by afc163** [comment]
Fixed in #15868
