### ISSUE TITLE
History icon

### ISSUE THREAD

**Issue by pixelwiz** [ant-design/ant-design#15850]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi, could you add an icon for "History"  Maybe something that looks like a clock with an arrow around it indicating going back in time?

### What does the proposed API look like?
Maybe something like this icon https://www.iconfinder.com/icons/352426/history_icon

**Comment by ycjcl868** [comment]
@JuelChiang
