### ISSUE TITLE
notification  能不能添加自定义图片

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design#15857]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了又写通知消息能自定义图片 因为有时候icon 是不能满足需求得

### What does the proposed API look like?
可以又个img之类得标签 可以添加自己想定义得图片

**Comment by afc163** [comment]
`icon={<img src="xxx" />}`

**Comment by yehoan** [comment]
message:`恭喜您中奖! <span style="{color: red}">{nextProps.accountList[i].expect}</span>`,

**Comment by yehoan** [comment]
message 里面如何自定义标签 给特点的字加 style

**Comment by yehoan** [comment]
各种尝试都不行.....

**Comment by afc163** [comment]
```diff
- message: `<span>xxx</span>`,
+ message: <span>xxx</span>,
```

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55544410-9a7b5780-56fd-11e9-9c1e-af65b3fcdd65.png)
报错了把

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55544685-2db48d00-56fe-11e9-8c77-550631731091.png)
zhe'中报错了  后面我想着 这种 然后还是报错了
![image](https://user-images.githubusercontent.com/22631753/55544708-3b6a1280-56fe-11e9-91f7-42bdebc68bdc.png)

**Comment by yehoan** [comment]
你的意思是直接就可以传标签 不用字符串把 标签装进去

**Comment by afc163** [comment]
先系统学习一下 React 吧~ 💪

**Comment by yehoan** [comment]
写错了 抱歉

**Comment by yehoan** [comment]
btn 那个怎么改他的颜色啊  例子只有创建一个confirm 按钮

**Comment by yehoan** [comment]
我全局改了样式貌似不行

**Comment by yehoan** [comment]
最后一个问题了
