### ISSUE TITLE
Cannot select pagination size for List

### ISSUE THREAD

**Issue by MarkTuddenham** [ant-design/ant-design#15852]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/r436j82no4)

### Steps to reproduce
Try to change the pageSize: it doesn't change (even in the UI) and remains at the original value.

### What is expected?
The pageSize gets changed and the number of items in the List reflects this.

### What is actually happening?
Dropdown does nothing.

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | Ubuntu 18 |
| Browser | Chrome & Firefox |

**Comment by ycjcl868** [comment]
PR welcome, `onShowSizeChange` not handle in `List pagination`
