### ISSUE TITLE
Icon should be able to search

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#15854]
http://ant.design/components/icon/

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/55527415-7c94ff00-56cb-11e9-9836-b584e31348ae.png)


![image](https://user-images.githubusercontent.com/13595509/55527424-86b6fd80-56cb-11e9-9815-fc26b2c42dd3.png)

**Comment by afc163** [comment]
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/507615/55528124-5e7cce00-56ce-11e9-80ca-c818c49f329f.png">

**Comment by DiamondYuan** [comment]
我来

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/55540586-e0ccb880-56f5-11e9-926f-408f0e66e018.png)
