### ISSUE TITLE
expandRowByClick is getting ignored if onRow => onClick(...) present

### ISSUE THREAD

**Issue by Jiahao01121** [ant-design/ant-design#15851]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/2opjp3lnrp?fontsize=14)

### Steps to reproduce
1. Add `expandRowByClick` prop to `<Table />` component.
2. Add `onRow` prop to `<Table />` component, inside the `onRow`, add `onClick` event listener.
3. If click on row, the `expender` **won't get expend**.
4. Remove `onRow` prop.
5. Click on row, the `expender` **will get expend**.

### What is expected?
Expect when both `expandRowByClick` and `onRow`(with `onClick` inside) props present, click on anywhere on row will still expand the expander.

### What is actually happening?
If both `expandRowByClick` and `onRow`(with `onClick` inside) props present, the `expandRowByClick` got ignored. Thus when you click anywhere on row, the expander won't expand.

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | React: 16.8.6 |
| System | MAC OS X: 10.14.3 |
| Browser | Google Chrome: 73.0.3683.86 |

---
The onClick listener is doing the logging stuff by calling some endPoint. expandRowByClick I assume is also using `onRow` prop (with `onClick` inside) internally.

**Comment by ztplz** [comment]
This is not a bug. If you set `click` on `onRow`, we will let you control the `open` of the row.

**Comment by afc163** [comment]
I think we should keep consistency of row events.

**Comment by Jiahao01121** [comment]
> I think we should keep consistency of row events.

@afc163 
My use case is to call a side effect function when row is being clicked(eg: log this user behavior). IMO, the onClick should be independent to whether the row is expandable or not. With that being said, I think `expandRowByClick` would be better to have another handler to handle the expand behavior.

@ztplz 
From what I understand, the total control of how row expands is relied on `expandedRowKeys`. It is only **optional** to set `expandedRowKeys`'s value in `onClick`. so I would imagine the expected behavior would be if `expandedRowKeys` presents, then `expandRowByClick` prop would be disabled due to the developer's choice is taking total control of how row will expand.

Let me know if this makes sense.

**Comment by cryst4lMao** [comment]
> This is not a bug. If you set `click` on `onRow`, we will let you control the `open` of the row.

签名不错
