### ISSUE TITLE
inline Menu component flash and shake when collapsed

### ISSUE THREAD

**Issue by ouzhou** [ant-design/ant-design#15853]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout-cn/#components-layout-demo-side](https://ant.design/components/layout-cn/#components-layout-demo-side)

### Steps to reproduce
first,  click to to open a submenu , 
then click the close button

### What is expected?
with no flash and shake

### What is actually happening?
flash and shake

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.x |
| System | win10 |
| Browser | chrome 72.0.3626.121（正式版本） （64 位） |

---
Not fixed in https://github.com/ant-design/ant-design/issues/15614 ， 
when this component is in Sider component ，
而且为什么menu组件在sider组件里面就不用设置collapsed了？而且如果sider设置了collapsed 这个时候menu设置collapsed就无效了，是个bug吧？

**Comment by afc163** [comment]
Fixed in #15868
