### ISSUE TITLE
Does AutoComplete support loading ?

### ISSUE THREAD

**Issue by plainnany** [ant-design/ant-design#15855]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when I use autocomplete component, `datasource` is async data, before fetching data, I want to set select menu status is loading, but I can't find any api about this

### What does the proposed API look like?
Is there possible or plans to support it ?

**Comment by afc163** [comment]
https://codesandbox.io/s/m73zo8xmkx

```
notFoundContent={<Spin />}
```

**Comment by plainnany** [comment]
thanks

**Comment by 510846** [comment]
notFoundContent={<Spin />}     ------  not good!
