### ISSUE TITLE
the property of 'align:right' in table columns  doesn't work when I use 'sorter' in columns 【当columns 同时设置sorter和align:right，右对齐失效】

### ISSUE THREAD

**Issue by QingFlye** [ant-design/ant-design#15859]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/m4zlxr54ox)

### Steps to reproduce
const columns = [{
  title: '右对齐了吗',
  dataIndex: 'name',
  align:'right'
}, {
  title: '右对齐了吗',
  dataIndex: 'age',
  align: 'right',
  defaultSortOrder: 'descend',
  sorter: (a, b) => a.age - b.age,
}, {
  title: '右对齐了吗',
  dataIndex: 'address',
  defaultSortOrder: 'descend',
  sorter: (a, b) => a.age - b.age,
  align:'right'
}];

### What is expected?
the property of sorter shouldn't influence  align

### What is actually happening?
"align : right" doesn't work well

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by QingFlye** [comment]
const columns = [{
title: '右对齐了吗',
dataIndex: 'name',
align:'right'
}, {
title: '右对齐了吗',
dataIndex: 'age',
align: 'right',
defaultSortOrder: 'descend',
sorter: (a, b) => a.age - b.age,
}, {
title: '右对齐了吗',
dataIndex: 'address',
defaultSortOrder: 'descend',
sorter: (a, b) => a.age - b.age,
align:'right'
}];
![image](https://user-images.githubusercontent.com/7763656/55534891-1b2f5900-56e8-11e9-8a17-09713d797775.png)

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design/issues/15846

**Comment by afc163** [comment]
trace #15846

**Comment by shanjairaj7** [comment]
Does align:'right' work?
I am trying to implement it but it is giving me an error.
