### ISSUE TITLE
 Property 'className' does not exist on Table.ColumnGroup

### ISSUE THREAD

**Issue by joshuaavalon** [ant-design/ant-design#15860]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mo0lr87249)

### Steps to reproduce
```
<Table.ColumnGroup title="title" key="title" className="className" >
</Table.ColumnGroup>
```

### What is expected?
No errors

### What is actually happening?
Type '{ children: Element; title: string; key: string; className: string; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ColumnGroup> & Readonly<ColumnGroupProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ColumnGroup> & Readonly<ColumnGroupProps> & Readonly<{ children?: ReactNode; }>'.

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.4 |
| System | Window 10 |
| Browser | N/A |

---
Similar to #12492 but for `Table.ColumnGroup`.

**Comment by yesmeck** [comment]
`Table.ColumnGroup` don't support `className`.
