### ISSUE TITLE
Drawer jumping if css > body{ overflow-y: scroll; }

### ISSUE THREAD

**Issue by crazyx13th** [ant-design/ant-design#15864]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1o3w8ppo5j)

### Steps to reproduce
works:
![grafik](https://user-images.githubusercontent.com/8912561/55537457-8a8f5380-56bc-11e9-8009-aae652ce16c9.png)
- minimize height of codesandbox.io "Browser" to see an active scollbar
- click "Open" Button how often you want
> width from "Content-Box" is always the same

problem / not woking:
![grafik](https://user-images.githubusercontent.com/8912561/55537553-c4f8f080-56bc-11e9-8fa1-2132351b0254.png)
- maximize height of codesandbox.io "Browser" to see an inactive scollbar (body > overflow-y: scroll;)
- click "Open" Button how often you want
> width from "Content-Box" is JUMPING

### What is expected?
width from "Content-Box" is not JUMPING if I set css > body{ overflow-y: scroll; }

### What is actually happening?
viewport width is 100% (should be 100% - getScrollBarSize() )

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome |

---
node_modules/rc-drawer/lib/Drawer.js:370
`var right = document.body.scrollHeight > (window.innerHeight || document.documentElement.clientHeight) && window.innerWidth > document.body.offsetWidth ? (0, _getScrollBarSize2['default'])(1) : 0;`

- solution A: detect css > body{ overflow-y: scroll; }
- (solution B: a new option like forceSetScrollBarSize)

thx!!

Greetings
crazyx13th

**Comment by ztplz** [comment]
What confuse me is why you want to set `overflow-y: scroll` in `body`?  Any situation?

**Comment by crazyx13th** [comment]
hey ztplz,

is very simple. I don't want that the content-width is jumping.
(less content>no scollbar VV huge content>scollbar)
This is the reason I always want have a scollbar.
Or just look here https://stackoverflow.com/questions/9201968/content-jumps-horizontally-whenever-browser-adds-a-scrollbar

thx!!

Greetings
crazyx13th

**Comment by zombieJ** [comment]
Test in some way, since both css & drawer self will change body `overflow-y`, it's hard to detect the source by `getComputedStyle`. Close this.

If you have better solution, welcome PR to [`rc-drawer`](https://github.com/react-component/drawer)

**Comment by crazyx13th** [comment]
mhh, ok, thx. (my solution B was something like extra param like `forceCalcScrollBarSize`)

**Comment by zombieJ** [comment]
My thought that `forceCalcScrollBarSize` is little case specific. It may need more automatic solution.

**Comment by crazyx13th** [comment]
if someone have the same issue, here is my quick fix to force allways a "scrollbar-padding"

```javascript
export function forceAntDScrollBar(): void
{
   const scrollBarSize: number = (require('rc-util/lib/getScrollBarSize').default)()
   const {style} = document.body

   const observer: MutationObserver = new MutationObserver((mutations: MutationRecord[]) => mutations.forEach((mutationRecord: MutationRecord) =>
   {
      if (mutationRecord.target == document.body && mutationRecord.attributeName == 'style') {

         if (style.overflow == 'hidden' && style.position == '') {
            style.cssText = `position: relative; width: calc(100% - ${scrollBarSize}px); overflow: hidden;`
         }
         if (style.overflow == '' && style.position == 'relative') {
            style.cssText = ''
         }
      }
   }))
   observer.observe(document.body, {attributes: true, attributeFilter: ['style']})
}

```
