### ISSUE TITLE
better skeleton

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design#15878]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The skeleton is too simple and needs more types.
Such as breadcrumbs buttons, etc.

### What does the proposed API look like?
<skeleton.line />

**Comment by zombieJ** [comment]
How about this? https://codesandbox.io/s/qxkwj23kxj
