### ISSUE TITLE
my first row which not the fixed is hidden when I have too many rows

### ISSUE THREAD

**Issue by LiYanGang** [ant-design/ant-design#15873]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yw3xpzp819)

### Steps to reproduce
no action just see the UI

### What is expected?
Column 1  is show 

### What is actually happening?
Column 1  is hidden

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.7.0 |
| System | mac |
| Browser | chrome 72.0.3626.119 |

**Comment by LiYanGang** [comment]
detail see the link https://codesandbox.io/s/yw3xpzp819

**Comment by afc163** [comment]
<img width="573" alt="图片" src="https://user-images.githubusercontent.com/507615/55555255-74fb4780-5717-11e9-91a1-ab410fb27ff8.png">

Cannot find any problem in your codesandbox.

**Comment by J9th** [comment]
@afc163 

I can see his/her issue in CodeSandbox link...

![column1](https://user-images.githubusercontent.com/25644559/55634600-d4e00580-578c-11e9-9de8-301e124315a7.png)

I checked the html and Column 1 is being hidden under the fixed age column.
As well at column 24 at the end being cut off slightly by the fixed action column.

**Comment by afc163** [comment]
@LiYanGang Try a bigger scroll.x width or `scroll={{ x: 'max-content' }}`.

**Comment by LiYanGang** [comment]
when i use scroll = {{ x: 'max-content'}}，Column 1 is show。thanks
