### ISSUE TITLE
Disable browser autocomplete for Input fields

### ISSUE THREAD

**Issue by vladimirmoushkov** [ant-design/ant-design#15875]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have custom autocompletion feature within my web application that works when I type in `<Input.Search />` component.

However Safari and other browser tries to do additional autocomplete when I type in React And Design  `<Input />` field.

I would like to be able to disable browser autocomplete by setting autocomplete="off"  (see https://stackoverflow.com/questions/2530/how-do-you-disable-browser-autocomplete-on-web-form-field-input-tag ).

This issue is quite similar to https://github.com/ant-design/ant-design/issues/7659

### What does the proposed API look like?
`<Input autocomplete={false} /> 
`
where the autocompleted property will be **true** by default

**Comment by yesmeck** [comment]
It's already support, try `<Input autoComplete={false} />`

**Comment by vladimirmoushkov** [comment]
I did checked the [documentation](https://ant.design/components/input/) and that information indeed was missing there. Also did try to search for autocomplete (like [defined in html](https://www.w3schools.com/tags/att_input_autocomplete.asp)) in [InputProps](https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx) and did not find it, however autoComplete="off" indeed works!

Thank you @yesmeck !

**Comment by zomars** [comment]
`<Input autoComplete="off" />` stopped working on Chrome:

As per Chrome  76.0.3809.100 this happens with autocomplete="off" in the `Cascader` component:

code | browser
| - | - |
| ![Captura de Pantalla 2019-08-14 a la(s) 12 33 06](https://user-images.githubusercontent.com/3504472/63046889-86f0b200-be90-11e9-810a-9cff4647d310.png) | ![Captura de Pantalla 2019-08-14 a la(s) 12 33 26](https://user-images.githubusercontent.com/3504472/63046901-8f48ed00-be90-11e9-94cd-a9cdb0510a96.png) |

As per [this answer in stackOverflow](https://stackoverflow.com/a/30976223), the best way to handle this if by using a `autocomplete="newpassword"` attribute:

code | browser
| - | - |
|  ![Captura de Pantalla 2019-08-14 a la(s) 12 34 27](https://user-images.githubusercontent.com/3504472/63047797-632e6b80-be92-11e9-824a-9708bd1784bc.png) | ![Captura de Pantalla 2019-08-14 a la(s) 12 34 34](https://user-images.githubusercontent.com/3504472/63047796-6295d500-be92-11e9-9d2e-1227f5b4e153.png) |

Is this the right issue to ask or should I open another issue for this topic?

**Comment by avpaul** [comment]
Any plans to have  autocomplete on `<Select />` components?
When you set `showSearch={true}` browsers will try to autocomplete/suggest/fill the search input

**Comment by incodenet** [comment]
For someone who will be facing with this in future - try `autoComplete="nope`" if you're using AntD of version 4.x.x and 5.x.x

**Comment by yogithesymbian** [comment]
> For someone who will be facing with this in future - try `autoComplete="nope`" if you're using AntD of version 4.x.x and 5.x.x

doesnt works . 
my engine  mbpm1 ( chrome latest version ) 
```
"antd": "^5.20.2",
```

**Comment by vitalijalbu** [comment]
same on mine, any updates guys??

**Comment by henriquegarcia-web** [comment]
> For someone who will be facing with this in future - try `autoComplete="nope`" if you're using AntD of version 4.x.x and 5.x.x

This worked for me, I'm using **antd: ^5.16.2**. Thanks!!
