### ISSUE TITLE
Typography.Paragraph should render as p tag

### ISSUE THREAD

**Issue by Stephen2** [ant-design/ant-design#15883]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently renders as div, which is not as semantically correct.  p tag is perfect for a sentence of text.

Better semantic HTML = better SEO & better for screen readers

### What does the proposed API look like?
No API, just replace the div with the p tag

The Component is even called Paragraph.  This feels like a no brainer

**Comment by zombieJ** [comment]
Since Chrome will warning for `ul` element under `p`, we use `div` instead. If you want to use `p` as paragraph. We recommend use \<Typography> directly. It will tread as `article`: https://ant.design/components/typography/#components-typography-demo-basic

**Comment by Stephen2** [comment]
So answer is to use:
`<Typography><p>Hello</p></Typography>` right?

That makes sense, can you confirm?

**Comment by zombieJ** [comment]
Yes. Typography includes all the style sub components have. Please feel free to use like this if semantic needed.

**Comment by Stephen2** [comment]
Perfect, @zombieJ ... P.S. cool user name

**Comment by aderchox** [comment]
I think Typography needs to allow developers to decide on the actual DOM element generated. For example, if I use Ant's `Title` from the Typography component, it generates `h1`, `h2`, ... elements but it also adds an unwanted bottom margin. I've Googled and there's no good ways for getting rid of it unless I use `!important` which I don't like. So I decided to use the `Text` component instead, but it generates a `span` which is not semantic. I think this needs to be fixed.

**Comment by chimobi-justice** [comment]
Typography.Paragraph  rendering as `Div` tag instead of  `p`

**Comment by mishchief** [comment]
Reviving this because it's ridiculous that Typography.Paragraph renders a `div` and that we can't remove the `margin-bottom` without using `!imporant`

I use antd because my company uses antd and I don't have much of a choice, but this messes up SEO given that pages are not using correct semantic html using the antd Typography styles and we can't even change them without doing more ridiculous things that could affect SEO and accessibility.

Please allow us to choose the component of our choice or think thoughtfully about what component renders what element.

**Comment by yourAverageDeveloper** [comment]
It's strange how this is still an issue in Ant 5. It should have been resolved by now.

**Comment by aniketsingh98571** [comment]
It's not yet resolved, the margin bottom causes problem for Paragraph

**Comment by ArvindKarthi** [comment]
How cool is it to have such a basic issue still at version 5 of a component library. This is ridiculous, I'm using antd without any way due to my company.
