### ISSUE TITLE
Select 的 Option 中 key 为空字符串时导致页面崩溃

### ISSUE THREAD

**Issue by xc1427** [ant-design/ant-design#15881]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yq11pl4vy9)

### Steps to reproduce
Select 的 Option 中 key 赋值为空字符串

### What is expected?
页面不报错，只是 console 有警告

### What is actually happening?
页面报错崩溃

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | react 16.8 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
```diff
- <Option key="">Jack</Option>
+ <Option value="">Jack</Option>
```

**Comment by douzhuanxingyi** [comment]
when set mode multiple,if value is empty string, we can not deselect the option
