### ISSUE TITLE
上传组件Upload的怎么出入data里，当前上传图片的file.uid

### ISSUE THREAD

**Issue by camnpr** [ant-design/ant-design#1588]
描述： 上传图片，需要前端和后端，用统一的一个不重复的图片名称。 所以，我需要，前端图片生成的uid，传入后端来保存图片名称。

貌似，只有通过配置： data 参数来传递参数。 data在0.12.14版本里可以使用：data : function(file){这个file是undefined}。  

何时更新版本？或者，有没有其它方法？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1543
