### ISSUE TITLE
Custom Remove of uploaded file

### ISSUE THREAD

**Issue by JMA12** [ant-design/ant-design#15887]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If you want to create custom preview of files uploaded and then you create a custom remove button 

### What does the proposed API look like?
Clicking on the custom remove button removes a file from the fileList

**Comment by afc163** [comment]
You can do it by turing off default upload list: `showUploadList={false}`, and create your own upload list.

**Comment by JMA12** [comment]
> You can do it by turing off default upload list: `showUploadList={false}`, and create your own upload list.

yes but removing of a file doesn't have an api

**Comment by afc163** [comment]
It is all react: https://codesandbox.io/s/oojjp2rpp9

**Comment by JMA12** [comment]
yeah I see, already made it.
Thanks @afc163
