### ISSUE TITLE
InputNumber bug: 初始为禁用时值的状态错误

### ISSUE THREAD

**Issue by junhwong** [ant-design/ant-design#15889]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/embed/w23pq51j9k?fontsize=14](https://codesandbox.io/embed/w23pq51j9k?fontsize=14)

### Steps to reproduce
```js
<InputNumber min={min} max={max} parser={parser} style={{ width: '100%' }} onChange={this.onChange} disabled={!_editing} />
```
默认为禁用状态，并且设置了最大和最小的值，然后给一个在限制范围之外的值，显示的是min或max的值，解除禁用直接提交表单，获得的只是给定的值并不是min或max其中之一。

ps: 解除禁用后不做任何输入动作。

### What is expected?
应该：
1. 要么显示默认值，解禁后设置min或max
2. 要么显示min或max，提交的值为最新值

### What is actually happening?
默认值

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.7.0 |
| System | OS X |
| Browser | chrome |

**Comment by junhwong** [comment]
最小demo已经提供，https://codesandbox.io/embed/w23pq51j9k?fontsize=14

**Comment by junhwong** [comment]
@afc163

**Comment by zombieJ** [comment]
你的代码逻辑乱了，它本来显示的就是默认值：demo：https://codesandbox.io/embed/w23pq51j9k?fontsize=14

对于 InputNumber 而言，受控的 `value` 值优先级是高于自身范围逻辑的。所以当你给的 `initialValue` 不在范围内，它也是以你的输入为准。所以你在设置 initialValue 的时候就需要设置它为正确的值。

**Comment by junhwong** [comment]
@zombieJ 你这就关了？我代码那里乱了？请看清我的问题，谢谢！
期望：
要么显示默认值，解禁后设置min或max
要么显示min或max，提交的值为最新值

什么是默认值？initialValue 才是，而demo里显示的是 min 的值。

**Comment by zombieJ** [comment]
看一下我给的例子，你的代码里 val 的值是在 `componentDidMount` 时添加的并不是在初始化的时候添加在。你可以在 render 里打印一下看看：
<img width="155" alt="屏幕快照 2019-04-06 下午7 47 37" src="https://user-images.githubusercontent.com/5378891/55669019-dac90a00-58a4-11e9-97be-43b7f8e886cf.png">

**Comment by junhwong** [comment]
@zombieJ 请看InputNumber初始显示的值是多少？然后看提交的值是多少？
很明显的不一致好吧，不管componentDidMount给的是多少，正常的应该保持一致！

**Comment by zombieJ** [comment]
发现 CodeSandbox 出 BUG 了，我写的例子没保存成功。我再写一个，稍等。

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/55669491-a5271f80-58aa-11e9-9939-288e250d3ea5.png)
我的codesandboxzen怎么一直是这个

**Comment by junhwong** [comment]
我这边也是，你随便改一个字符它就恢复了

**Comment by zombieJ** [comment]
@junhwong , 这个：https://codesandbox.io/s/xpk92127x4

里面有几点要注意：
* `initialValue` 是给组件初始化时使用的，动态更改 `initialValue` 是不正确的用法。（虽然现在 Form 在组件没有触发 onChange 时修改 `initialValue` 仍然有效，这是为了兼容一些遗留的写法。它并不是正确的用法）
* Form 结果收集逻辑是以组件触发 onChange 为准，如果没有就用 `initialValue`。你的例子里 componentDidMount 改了 `initialValue`，由于没有输入，所以使用了新的值（原因如上，应该避免这么用）
* InputNumber 接收的值是 number 类型，这边传递 '0.00' 它内部会按照一定逻辑转换来展示（但是这并不是它真实的值，真实的值还是你设置的 `initialValue`），所以这边给 `0` 作为初始值时它便显示了 `0`。

**Comment by junhwong** [comment]
![image](https://user-images.githubusercontent.com/8044424/55669697-1071f100-58ad-11e9-9c92-b65cc9524b7b.png)
@zombieJ 我认为这是一个bug,我传入**5.00**,它默认显示的是**5**，而提交的时候说不正确，这就是状态不一致，如果控件不能改变值本身，那就应该按照传入值”原样“显示，而不是显示和行为不一致。

**Comment by junhwong** [comment]
@zombieJ 如果控件会按照一定规则转换，那么真实值就应该是转换后的值，至于最终提交至是否正确，这时候才是rule所要做的工作。

**Comment by junhwong** [comment]
@zombieJ 并且，InputNumber 提供了 parser 属性，但默认它也是未工作的。

**Comment by junhwong** [comment]
@zombieJ 我没去看源码，但我猜测它只是在render的时候转换并且显示，在用户有输入动作时才使用parser和验证，这就造成显示和行为不一致，这就失去了InputNumber本身的意图，和用一个普通input控件没有区别。

**Comment by zombieJ** [comment]
@junhwong InputNumber 有个 `precision` 属性，用于设置精度。转成 `5` 是符合预期的行为： https://codesandbox.io/s/0q84v7rj80
