### ISSUE TITLE
List component should have option to render as ol/ul and each item becomes wrapped in li

### ISSUE THREAD

**Issue by Stephen2** [ant-design/ant-design#15884]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A List of objects is generally best semantically marked up as an `<ol>` or `<ul>`

Improved semantics improves SEO & screen reader experience.  For example, when coming across an `<ol>` with 5 `<li>` inside the screen reader will say "List of 5 items".  This is very helpful to screen readers.

Currently the component just outputs a lot of `<div>` which isn't semantically great.

Further, if you try and use just straight `<ul>`/`<ol>` in antd, it is very unsatisfying to have to style it yourself, and hope you are sticking to Ant Design principles.

### What does the proposed API look like?
Maybe `htmlType` = ?"ol" | "ul".  If not provided, render as it currently does

**Comment by zombieJ** [comment]
Make sense.

**Comment by Stephen2** [comment]
We should allow option between `ol` or `ul` as they have different meaning.

`ol` = `Ordered List`.  When you know the list of things you're putting are in a certain order (maybe Alphabetical, or date order) you should always use `ol`

`ul` = `Unordered List`.  When the items are in random order, or have no ordering that makes sense.

**Comment by Stephen2** [comment]
@zombieJ I think this merged, right?  Can close issue?
