### ISSUE TITLE
QQ browser and Android origin browser can't scroll on Drawer component.

### ISSUE THREAD

**Issue by ryanyu104** [ant-design/ant-design#15894]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce
It also doesn't work When I use QQ browser on Antd official site. 

### What is expected?
Scroll Y success.

### What is actually happening?
It doesn't scroll.

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.8.3 |
| System | Android |
| Browser | 9.1.0.4850 |

**Comment by ztplz** [comment]
I am afraid we can't help anything. `Antd` focuses on the desktop, some components are not very well supported on mobile devices.

**Comment by zombieJ** [comment]
Tested in Chrome mobile. Seems it's QQ Browser Bug. We can do nothing on this.
