### ISSUE TITLE
Allow Button option to make it look exactly like Hyperlink

### ISSUE THREAD

**Issue by Stephen2** [ant-design/ant-design#15892]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When you want something to visually look like a Hyperlink, but it doesn't actually change your URL, you should definitely use a `<button type="button">` element.

At present, there is no way to style a `<Button />` component to look visually like a hyperlink

An example might be a "Forgot password?" button, which shouldn't appear as prominent as an actual `<button>` - being styled like an `<a>` is perfect.  But it doesn't actually change your URL, it just toggles the Login form to replace with Forgot Password form - so it should definitely be an HTML `<button>` element.

This is best practice for semantic HTML.  To have an `<a>` element do this, you either have:
 - no href (then you can't use keyboard to TAB to the `<a>` which breaks keyboard users completely)
 - a fake href (like `#` or `javascript:void(0)`) <-- screen readers can read this out, and it's bad.  Also you need to remember to `event.preventDefault` in the handler, which isn't good.

Better semantic HTML = better SEO & better accessibility, which is so important these days.

Bootstrap does this with classes `btn btn-link`

### What does the proposed API look like?
add `type="link"` or something

Only different behaviour is visual appearance is now exactly like an `<a>`

**Comment by zombieJ** [comment]
Since antd has the default button presents the secondary button which called text button in other UI framework. They're in the same design level.

We could add  `type='link'`( instead of `type='text'` in #15826) since we still recommend user to use default button as secondary one.

**Comment by XianZhengquan** [comment]
@zombieJ ok
