### ISSUE TITLE
需求：timeline支持自定义icon，副标题

### ISSUE THREAD

**Issue by ottomao** [ant-design/ant-design#1589]
如图，求timeline组件支持这种自定义icon，和副标题。
或者请step组件支持自定义icon。
其实我觉得timeline和step可以合并起来的.....

![](https://os.alipayobjects.com/rmsportal/mKqLPYYDXdDFgeG.png)

**Comment by afc163** [comment]
Step 组件本来就支持自定义图标。

Timeline 组件和 Step 组件语义上不一样。

Timeline 的图标我来加上。

Timeline 的副标题，目前没有限制 TimelineItem 组件的子节点内容，想写什么都可以。

**Comment by ottomao** [comment]
我看step的这个icon是类似` icon="cloud"`这样的？如果我想用自己的icon ?

**Comment by afc163** [comment]
那确实不行，我一并改掉。

**Comment by ottomao** [comment]
有大概的集成时间么？如果能满足我们业务，我就自己不搞hack了....

**Comment by afc163** [comment]
1.0.0 吧，就在这几天。
