### ISSUE TITLE
Drag stop (mouseup) on Overlay closes Modal

### ISSUE THREAD

**Issue by viensmorinjs** [ant-design/ant-design#15891]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal/](https://ant.design/components/modal/)

### Steps to reproduce
1. Click on the "Open Modal" button of the first example. 
(The modal will open.)
2. Do a mouse down on the modal.
3. Drag the mouse cursor outside of the modal on the shadowed part of the screen.
4. Do a mouse up.
(The modal will close.)

### What is expected?
When the click start on the modal, the modal should not close when the mouse up occurs outside the modal.

### What is actually happening?
The modal close on mouse up outside the modal when the mouse down occurred on the modal.

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | react Version 16.8.2 |
| System | macOS Mojave Version 10.14.3 |
| Browser | Chrome Version 73.0.3683.86 (Build officiel) (64 bits) |

---
If the user try to select the content f the modal and release the mouse button outside of the modal, the modal will close and the user will get frustrated.

**Comment by ggepenyan** [comment]
Any update on this???

**Comment by ArturBaybulatov** [comment]
This issue should be reopened. The bug still occurs.

**Comment by jorgsiegel** [comment]
Push. This is really annoying and I can't find any way around it.

**Comment by ascendedguard** [comment]
We're also experiencing this issue and waiting for a patch. Does a new issue need to be opened?

**Comment by ChuckJonas** [comment]
Here's a real world example of how this really messes up the UX:

- The modal has a text box.  
- The user attempts to select the text inside by clicking and dragging.  
- They are likely to end up outside of the modal before they release the mouse
- Modal closes unexpectedly

![QZW8PlAZ9l](https://user-images.githubusercontent.com/5217568/108766461-6a681800-7512-11eb-8dd9-ad379efe35b5.gif)

**Comment by qpIlIpp** [comment]
The same as above for me. Urer is selectiong text, modal closes.

**Comment by gnato** [comment]
I have a similar issue. In my case, I have a form in a modal, which contains a slider. When I move the cursor outside the modal area, it closes. The problem still exists in AntD 5.12.2 :(

**Comment by capfsb** [comment]
Have same issue with a Modal+Slider from previous commentary
