### ISSUE TITLE
建立离线版本时, 执行npm start,卡在building modules,无报错信息

### ISSUE THREAD

**Issue by Sjian1988** [ant-design/ant-design#15898]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/README-zh_CN.md    本地开发](https://github.com/ant-design/ant-design/blob/master/README-zh_CN.md    本地开发)

### Steps to reproduce
参照教程,依次执行git clone, npm install, npm start

### What is expected?
浏览器打开离线网站

### What is actually happening?
无法编译完成,且无报错信息
building modules(69%) 1833/1834 modules 1
active  bisheng-data-loader >> node_modules\bisheng\lib\utils\data.js

| Environment | Info |
|---|---|
| antd | 3.9.0 |
| React | 无 |
| System | win7, ubuntu |
| Browser | chrome |

**Comment by DiamondYuan** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [https://github.com/ant-design/ant-design/blob/master/README-zh_CN.md 本地开发](https://github.com/ant-design/ant-design/blob/master/README-zh_CN.md 本地开发)
> 
> ### Steps to reproduce
> 参照教程,依次执行git clone, npm install, npm start
> 
> ### What is expected?
> 浏览器打开离线网站
> 
> ### What is actually happening?
> 无法编译完成,且无报错信息
> building modules(69%) 1833/1834 modules 1
> active bisheng-data-loader >> node_modules\bisheng\lib\utils\data.js
> 
> Environment	Info
> antd	3.9.0
> React	无
> System	win7, ubuntu
> Browser	chrome

耐心多等一会儿？构建比较慢。

**Comment by afc163** [comment]
建议用 Mac，这个项目的调试没有针对 windows 做优化，或者你可以排查一下给我们 PR。
