### ISSUE TITLE
Popover and tooltip are not displayed for custom components

### ISSUE THREAD

**Issue by Dainius14** [ant-design/ant-design#15909]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4zo0kzm1yw)

### Steps to reproduce
Create a custom component and use it in a popover or tooltip.

### What is expected?
Popover/tooltip is shown when hovering over the element

### What is actually happening?
Popover/tooltip is not shown

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.3 |
| System | Windows 10 |
| Browser | Vivaldi 2.4.1488.35, Firefox 66.0.1 |

---
Wrapping the component inside a <div> or <span> in popover itself solves the problem. DOM is identical for both cases.

**Comment by afc163** [comment]
https://codesandbox.io/s/94y3wwyk4y

**Comment by afc163** [comment]
#15528

**Comment by afc163** [comment]
#15909

**Comment by awall** [comment]
Why was this issue closed? It still occurs in the latest version of AntD! Thank God I found this post, or I would never have figured out what was happening!

**Comment by naivefun** [comment]
> 

One workaround is to wrap your custom element with HTML tag

```jsx
<Popover content={}>
    <div className="inline-flex"><CustomComponent/></div>
</Popover>
```

**Comment by afc163** [comment]
https://ant.design/components/tooltip-cn#%E4%B8%BA%E4%BD%95%E6%9C%89%E6%97%B6%E5%80%99-hoc-%E7%BB%84%E4%BB%B6%E6%97%A0%E6%B3%95%E7%94%9F%E6%95%88
