### ISSUE TITLE
table组件出现空白

### ISSUE THREAD

**Issue by pureZjr** [ant-design/ant-design#15906]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/oOLKGN?editors=0010](https://codepen.io/anon/pen/oOLKGN?editors=0010)

### Steps to reproduce
直接打开就会重现

### What is expected?
每列自适应宽度

### What is actually happening?
出现空白

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.3 |
| System | mac |
| Browser | Google Chrome73.0.3683.86 |

---
当我用fixed固定最右边那一列，然后其他列都用了固定宽度的时候，当表格总宽度大于我设置 的 scroll.x 的话，就会出现一块空白

`const { Table } = antd;

const columns = [
{ title: 'Column 1', dataIndex: 'address', key: '1', width: 100, },
{ title: 'Column 2', dataIndex: 'address', key: '2' , width: 100},
{ title: 'Column 3', dataIndex: 'address', key: '3' , width: 100},
{ title: 'Column 4', dataIndex: 'address', key: '4', width: 100 },
{ title: 'Column 5', dataIndex: 'address', key: '5', width: 100 },
{ title: 'Column 6', dataIndex: 'address', key: '6', width: 100 },
{ title: 'Column 7', dataIndex: 'address', key: '7', width: 100 },
{ title: 'Column 8', dataIndex: 'address', key: '8' , width: 100},
{
title: 'Action',
key: 'operation',
fixed: 'right',
width: 100,
render: () => action,
},
];

const data = [{
key: '1',
name: 'John Brown',
age: 32,
address: 'New York Park',
}, {
key: '2',
name: 'Jim Green',
age: 40,
address: 'London Park',
}];

ReactDOM.render(<Table columns={columns} dataSource={data} scroll={{ x: 900 }} />, mountNode);`

**Comment by afc163** [comment]
https://codepen.io/anon/pen/YMGXMa?editors=0010

<img width="805" alt="图片" src="https://user-images.githubusercontent.com/507615/55681121-2d61ff00-5955-11e9-8b82-19bc05a97bb9.png">

**Comment by pureZjr** [comment]
好的，谢谢
