### ISSUE TITLE
日期选择器中请使用规范的format函数

### ISSUE THREAD

**Issue by HQidea** [ant-design/ant-design#1591]
`2016-05-06`的标准格式是`YYYY-MM-DD`而不是`yyyy-MM-dd`

请使用[ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Dates)规范来格式化日期对象
另外参考https://www.w3.org/TR/NOTE-datetime

**Comment by afc163** [comment]
duplicate and trace on https://github.com/yiminghe/gregorian-calendar-format/issues/9
