### ISSUE TITLE
日期控件初始值为空的时候,会出现invalid date

### ISSUE THREAD

**Issue by hedy0111** [ant-design/ant-design#15917]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/hedy0111/pen/OGRzRN](https://codepen.io/hedy0111/pen/OGRzRN)

### Steps to reproduce
<FormItem {...formLayout} label="有效期至">
              {getFieldDecorator('endActiveDate', {
                initialValue: moment(endActiveDate),
              })(<DatePicker format="YYYY-MM-DD" style={{ width: 300 }} />)}
            </FormItem>

### What is expected?
日期正常显示

### What is actually happening?
![image](https://user-images.githubusercontent.com/38686306/55693552-364ce200-59e2-11e9-9557-b07373c187b3.png)

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 3.13.0 |
| System | win10 |
| Browser | chrome |

---
在表格编辑的时候希望带出日期的初始值,但是日期有可能为空,就会导致这个问题

**Comment by zombieJ** [comment]
`moment('')` 不是空，是无效日期。所以基于无效日期算出来的所有的日期都是无效日期。`null` 才是空。

**Comment by afc163** [comment]
```diff
- defaultValue={moment('')}
+ defaultValue={null}
```

**Comment by zombieJ** [comment]
Working on adding warning with invalidate date.

**Comment by hedy0111** [comment]
thank you,已解决
