### ISSUE TITLE
Select Dropdown DatePicker TimePicker Popover Popconfirm 等组件使用getPopupContainer不方便

### ISSUE THREAD

**Issue by iwangx** [ant-design/ant-design#15918]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一般我们的后台管理系统都是采用Layout布局生成的，这样就意味着其实getPopupContainer的节点其实都会是同一个，所以如果在使用每个Select Dropdown DatePicker TimePicker Popover Popconfirm的时候都要增加一个getPopupContainer参数会让整个应用变得很复杂，所以能不能跟主题的配置一样增加一些通用的配置在初始化的时候？

### What does the proposed API look like?
可能类似于LocaleProvider这样的一个全局配置，直接传入参数即可

**Comment by zombieJ** [comment]
https://ant.design/components/config-provider-cn/#header
