### ISSUE TITLE
各种报错

### ISSUE THREAD

**Issue by Joanjiaying** [ant-design/ant-design#15929]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
https://ant.design/index-cn

### What is expected?
不报错

### What is actually happening?
打开官网就开始报错

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | react |
| System | 官网系统报错 |
| Browser | chrome |

**Comment by yesmeck** [comment]
清下浏览器缓存

https://github.com/ant-design/ant-design/issues/15925

**Comment by Joanjiaying** [comment]
时好时坏，您这边什么时候上线的，我把这之间的缓存都清了
在 2019-04-08 14:36:48，"Wei Zhu" <notifications@github.com> 写道：


清下浏览器缓存

#15925

**Comment by yesmeck** [comment]
刚刚重新发布了网站，缓存应该已经被刷新了。
