### ISSUE TITLE
ant design tree组件怎么能设置同级拖拽

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#15926]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如1,2,3三个层级：2层级之内的兄弟只能在2层级拖拽，3层级在3内拖拽

### What does the proposed API look like?
比如1,2,3三个层级：2层级之内的兄弟只能在2层级拖拽，3层级在3内拖拽

**Comment by wangxingxing123654** [comment]
![image](https://user-images.githubusercontent.com/28847126/55702509-5fcd3400-5a09-11e9-997b-0831cc8e9d82.png)

**Comment by vickychu** [comment]
希望给TreeNode加上draggable和droppable属性，默认true~

**Comment by guidogast** [comment]
Any updates on this? Would like to see this in a new version of Ant if that is possible :)

**Comment by holynova** [comment]
try this
```javascript
onDrop = info => {
    const dragNode = info.dragNode
    const dropNode = info.node
    const isSameLevel = (a, b) => {
        const aLevel = a.props.pos.split('-').length
        const bLevel = b.props.pos.split('-').length
        return aLevel === bLevel
    }
  const canDrop = isSameLevel(dragNode, dropNode)
 ...
}
```
@wangxingxing123654 @guidogast

**Comment by yes1am** [comment]
> try this
> 
> ```js
> onDrop = info => {
>     const dragNode = info.dragNode
>     const dropNode = info.node
>     const isSameLevel = (a, b) => {
>         const aLevel = a.props.pos.split('-').length
>         const bLevel = b.props.pos.split('-').length
>         return aLevel === bLevel
>     }
> 
>    const isSameParent = (a, b) => {
>         const aLevel = a.props.pos.split('-')
>         const bLevel = b.props.pos.split('-')
>         aLevel.pop()
>         bLevel.pop()
>         return aLevel.join('') === bLevel.join('')
>     } 
> 
>   const canDrop = isSameLevel(dragNode, dropNode)
> 
>  //  const canDrop = isSameParent(dragNode, dropNode)
>  if (!canDrop) {
>   return
> }
> }
> ```
> 
> @wangxingxing123654 @guidogast

似乎还有问题，上述代码只能保证拖拽的两个节点是同一级的。
但是无法避免，两个同级节点，一个拖拽成了另一个节点子节点的情况。查看 [codesanbox](https://codesandbox.io/s/antd-reproduction-template-forked-9gzxn?file=/tree.jsx)

![image](https://user-images.githubusercontent.com/25051945/100545028-a897c780-3294-11eb-9acc-7dc36088430d.png)
比如可以将 branch2.2 拖拽成 branch 2.1 的子节点，或者反过来 2.1 成了 2.2 的子节点。
而且 **将 branch2.2 拖拽成 branch 2.1 的子节点**，或者 **拖拽 2.1 成了 2.2 的子节点** 两种情况的 info.dropPosition 不一样，无法通过 info.dropPosition 这个值来判断。

在 element.ui 中有以下的判断方法可以阻止 **跨级拖拽，也不会成为子节点**

![image](https://user-images.githubusercontent.com/25051945/100545134-615e0680-3295-11eb-87cc-14113779e894.png)

有没有别的办法可以 **阻止跨级拖拽，也不会成为子节点**？

**Comment by MachiBarton** [comment]
element.ui  的 allowDrop API方式很方便的处理跨级拖曳，希望能处理

**Comment by JinJieTan** [comment]
我也遇到了这个问题，请问作者是怎么解决的呢？

**Comment by JinJieTan** [comment]
我也遇到了这个问题，请问作者是怎么解决的呢？ @wangxingxing123654

**Comment by JinJieTan** [comment]
这个代码可以解决

`     const isSameLevel = (a, b) => {
            const aLevel = a.props.pos.split('-').length;
            const bLevel = b.props.pos.split('-').length;
            return aLevel === bLevel;
        };

        const isSameParent = (a, b) => {
            const aLevel = a.props.pos.split('-');
            const bLevel = b.props.pos.split('-');
            aLevel.pop();
            bLevel.pop();
            return aLevel.join('') === bLevel.join('');
        };

        const canDrop = isSameParent(dragNode, dropNode) && isSameLevel(dragNode, dropNode) && info.dropToGap;`

**Comment by ccloveak** [comment]
> 这个代码可以解决
> 
> ```
> const onDrop = info => {
> const isSameLevel = (a, b) => {
>         const aLevel = a.props.pos.split('-').length;
>         const bLevel = b.props.pos.split('-').length;
>         return aLevel === bLevel;
>     };
> 
>     const isSameParent = (a, b) => {
>         const aLevel = a.props.pos.split('-');
>         const bLevel = b.props.pos.split('-');
>         aLevel.pop();
>         bLevel.pop();
>         return aLevel.join('') === bLevel.join('');
>     };
> 
>     const canDrop = isSameParent(dragNode, dropNode) && isSameLevel(dragNode, dropNode) && info.dropToGap;
> ```
> 
> }

攒点知识储备

**Comment by huangzongming** [comment]
并不可以啊，二级节点数据有多个时，下面的无法拖动到第一个。

**Comment by JinJieTan** [comment]
> 并不可以啊，二级节点数据有多个时，下面的无法拖动到第一个。 @afc163 有没有好的方法啊

可以拖拽，你只是拖拽的时候，没有放对位置，你要拖拽到第一个或者最后一个的时候，你得拖拽到那个节点的上方，然后看节点的上方那条细线变粗了才可以放下 ，我都上生产环境了，一年卖几千万的产品

**Comment by huangzongming** [comment]
并不可以啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月1日(星期二) 下午3:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ant-design/ant-design] ant design tree组件怎么能设置同级拖拽 (#15926)





  
并不可以啊，二级节点数据有多个时，下面的无法拖动到第一个。 @afc163 有没有好的方法啊
  
可以拖拽，你只是拖拽的时候，没有放对位置，你要拖拽到第一个或者最后一个的时候，你得拖拽到那个节点的上方，然后看节点的上方那条细线变粗了才可以放下 ，我都上生产环境了，一年卖几千万的产品

**Comment by yangmin4052** [comment]
var a = {props:{pos: '1-11-1' }}
var b = {props:{pos: '11-1-1' }}
isSameLevel(a,b)
isSameParent(a,b) // should be false but got true

**Comment by huangzongming** [comment]
![}OE_7HZ{{1S)DH~F9 1_EGL](https://user-images.githubusercontent.com/37889515/120291696-2d23db00-c2f6-11eb-906d-e32166aefc77.png)

**Comment by Ceilon** [comment]
[基于大家的总结实现](https://codesandbox.io/s/antd-reproduction-template-forked-i92fs?file=/tree.jsx:0-3850)

**Comment by Ceilon** [comment]
> 

发现如果不是顶层，拖动到第一个个是无效的，请问是否有解决办法

**Comment by Ceilon** [comment]
> > 
> 
> 发现如果不是顶层，拖动到第一个个是无效的，请问是否有解决办法
` //是否是同级
      const isPeer = () => {
        const dropPosL = dropPos.length;
        const dragNodePosL = dragNodePos.length;
        //判断目标元素和被拖动元素por长度是否相同
        if (dragNodePosL === dropPosL) {
          //相同则如果倒数第二个元素相同则说明是同一级并且判断是否是同级拖动
          return dragNodePos[dragNodePosL - 2] === dropPos[dragNodePosL - 2]&&info.dropToGap;
        }
        //如果不相同说明拖动到子集最顶部，被拖动元素和目标元素层级不同，获取最短por最后一个值和长的相同index上的值做对比，两个值相等说明是同级
        else {
          //获取短的por数组
          const shortPor = dropPosL < dragNodePosL ? dropPos : dragNodePos;
          //短数组的长度
          const l = shortPor.length;
          return (Math.abs(dragNodePosL - dropPosL) === 1) && (shortPor[l - 1] === dragNodePos[l - 1]);
        }
      };
      if (!isPeer()) {
        return;
      }`

其他的直接用官方文档的就可以

**Comment by wohaiwo** [comment]
```  
   /**
   * dragNode 拖动的值
   * dropNode 拖入的值
   */
  const isCanDrop = (dragNode, dropNode) => {
    let dragNodePos = dragNode.pos.split('-')
    let dropNodePos = dropNode.pos.split('-')
    // 两个pos 长度差值
    let differenceVal = dragNodePos.length - dropNodePos.length
    if (differenceVal === 0) {
      // 如果两个位置长度相同 就去除最后一个位置  然后判断两个是否相同
      dragNodePos.pop()
      let index = dropNodePos.pop()
      // 如果相同 可以放入
      if (dragNodePos.toString() === dropNodePos.toString()) {
        return +index + 1
      } else {
        return -1
      }
    } else if (differenceVal === 1) {
      // 这种情况会出现在 同级拖动 放到第一个位置上
      dragNodePos.pop()
      if (dragNodePos.toString() === dropNodePos.toString()) {
        return 0
      } else {
        return -1
      }
    } else {
      return -1
    }
  }
```
上面这个方法能解决问题  缺点是要根据对应的值 与接口最更新  返回最新的tree
能解决 
- 拖动到第一个问题
- 限制同级拖动

**Comment by tempoeric** [comment]
> > > 
> > 
> > 
> > It is found that if it is not the top layer, dragging to the first one is invalid. Is there a solution?
> > ` //是否是同级       const isPeer = () => {         const dropPosL = dropPos.length;         const dragNodePosL = dragNodePos.length;         //判断目标元素和被拖动元素por长度是否相同         if (dragNodePosL === dropPosL) {           //相同则如果倒数第二个元素相同则说明是同一级并且判断是否是同级拖动           return dragNodePos[dragNodePosL - 2] === dropPos[dragNodePosL - 2]&&info.dropToGap;         }         //如果不相同说明拖动到子集最顶部，被拖动元素和目标元素层级不同，获取最短por最后一个值和长的相同index上的值做对比，两个值相等说明是同级         else {           //获取短的por数组           const shortPor = dropPosL < dragNodePosL ? dropPos : dragNodePos;           //短数组的长度           const l = shortPor.length;           return (Math.abs(dragNodePosL - dropPosL) === 1) && (shortPor[l - 1] === dragNodePos[l - 1]);         }       };       if (!isPeer()) {         return;       }`
> 
> Others can directly use official documents

Hi can you update your codesandbox to see where you put this code thanks

**Comment by tempoeric** [comment]
Hi can someone share me a sandbox that i can drag the child tree at the very first top level index

**Comment by liufree** [comment]
解决拖动到第一个个是无效的，再加个判断就可以了

```
 const isSameLevel = (a, b) => {
    const aLevel = a.props.pos.split('-').length;
    const bLevel = b.props.pos.split('-').length;
    return aLevel === bLevel;
  };

  const isSameParent = (a, b) => {
    const aLevel = a.props.pos.split('-');
    const bLevel = b.props.pos.split('-');
    aLevel.pop();
    bLevel.pop();
    return aLevel.join('') === bLevel.join('');
  };

  const isDropToFirst = (a, b) => {
    const aLevel = a.props.pos.split('-');
    const bLevel = b.props.pos.split('-');
    aLevel.pop();
    return aLevel.join('') === bLevel.join('');
  };
  
  const canDrop = isDropToFirst(info.dragNode, info.node) || (isSameParent(info.dragNode, info.node) && isSameLevel(info.dragNode, info.node)) ;
```

**Comment by JefferyHo** [comment]
> 用你的试了一下，还是可以将子节点拖到父节点同级，在你的基础上调整成这样可以满足需求

    const canDrop = (isDropToFirst(info.dragNode, info.node) && !info.dropToGap) || (isSameLevel(info.dragNode, info.node) && isSameParent(info.dragNode, info.node));

**Comment by leevo303** [comment]
Here is my resolution, It works in my case:
`
export const isSameLevel = (a, b) => {
  const aLevel = a.props.pos.split('-').length;
  const bLevel = b.props.pos.split('-').length;

  return aLevel === bLevel;
};

export const isSameParent = (a, b) => {
  const aLevel = a.props.pos.split('-');
  const bLevel = b.props.pos.split('-');
  aLevel.pop();

  return aLevel.join('') === bLevel.join('');
}
`
`    const canDrop = (isSameLevel(info.dragNode, info.node) && info.dropToGap) || (isSameParent(info.dragNode, info.node) && !info.dropToGap);
`

**Comment by ixuxinyue** [comment]
基于楼上大家提供的解决方案，提供一个基于antd 5 的完整版能work的demo： https://codesandbox.io/p/sandbox/antd-reproduction-template-forked-nqkmcq?file=%2Ftree.jsx%3A155%2C1
