### ISSUE TITLE
index.js need a hash in filename

### ISSUE THREAD

**Issue by yesmeck** [ant-design/ant-design#15925]
<img width="579" alt="Screen Shot 2019-04-08 at 14 02 22" src="https://user-images.githubusercontent.com/465125/55701748-f4826280-5a06-11e9-9404-3035dd5a5d65.png">

Cloudflare uses `max-age` to cache the static resources, `index.js` need a hash to expire the cache.

**Comment by ycjcl868** [comment]
bisheng should add `?v=${version}` after `index.js`

**Comment by afc163** [comment]
`index-{hash}.js`
