### ISSUE TITLE
Table横向滚动条

### ISSUE THREAD

**Issue by longhuasishen** [ant-design/ant-design#1592]
这种固定表头列，通过横向滚动条来查看剩余内容 的有没有demo样例啊

**Comment by afc163** [comment]
#978

**Comment by afc163** [comment]
1.0.0 里会提供这个功能，建议关注下相关的 roadmap。

**Comment by longhuasishen** [comment]
好的，1.0.0大概什么时候发布

**Comment by Ben07** [comment]
本来想设置表格宽度长一点，然后外面套一层div来滚动，奈何表格的外层有一个div，结果因为中间多了一层div，滚动效果没有。
