### ISSUE TITLE
Button tsd error in  latest typescript@3.4.2

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design#15930]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/#header](https://ant.design/components/button-cn/#header)

### Steps to reproduce
- git clone ant-design source repo
- npm install (get latest typescript: 3.4.2)
- write some code in button/button.tsx, eg: 'const a = (<Button type="primary">Primary</Button>)'

### What is expected?
no ts error

### What is actually happening?
Type '{ children: string; type: "primary"; }' is missing the following properties from type 'Pick<Pick<(Readonly<AnchorButtonProps> & Readonly<{ children?: ReactNode; }>) | (Readonly<NativeButtonProps> & Readonly<{ children?: ReactNode; }>), "style" | "title" | "children" | ... 256 more ... | "onTransitionEndCapture"> & Pick<...> & Pick<...>, "style" | ... 257 more ... | "htmlType">': style, title, onClick, icon, and 252 more.ts(2740)

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | latest |
| System | any |
| Browser | any |

**Comment by paranoidjk** [comment]
![屏幕快照 2019-04-08 下午3 11 59](https://user-images.githubusercontent.com/7971415/55705162-b722d280-5a10-11e9-9ce7-9afd35b896e7.png)

**Comment by paranoidjk** [comment]
https://github.com/Microsoft/TypeScript/issues/20722

**Comment by qin9smile** [comment]
same error

**Comment by sdefauw** [comment]
same issue

**Comment by chenyong** [comment]
Same here. But I bypassed the problem by downgrading `@types/react` to `16.8.11`. I think it breaks in both `16.8.12` and `16.8.13`.

**Comment by qin9smile** [comment]
> Same here. But I bypassed the problem by downgrading `@types/react` to `16.8.11`. I think it breaks in both `16.8.12` and `16.8.13`.

it's work.

**Comment by zombieJ** [comment]
Seems @types/react change the merge logic: https://github.com/DefinitelyTyped/DefinitelyTyped/commit/836c2fa859f023fee1536d528a193f8c9b81287f#diff-96b72df8b13a8a590e4f160cbc51f40cR2771

**Comment by browsnet** [comment]
```typescript
// lib/button/button.d.ts
export declare type NativeButtonProps = {
    htmlType?: ButtonHTMLType;
    onClick?: React.MouseEventHandler<HTMLButtonElement>;
} & BaseButtonProps & React.ButtonHTMLAttributes<HTMLButtonElement>;
```
Both `BaseButtonProps` and `React.ButtonHTMLAttributes` have the same property `type`;
```typescript
{type?:"default", "primary", "ghost", "dashed", "danger"}  &
{type?:string}
// result
{type?:"default", "primary", "ghost", "dashed", "danger"}
```

After @types/react upgrade to `16.8.9`
```diff
- type?: string;
+ type?: 'submit' | 'reset' | 'button';
```
```typescript
{type?:"default", "primary", "ghost", "dashed", "danger"}  &
{type?: 'submit' | 'reset' | 'button'}
// result
{type:undefined}
```

Just exclude the `type` property from `React.ButtonHTMLAttributes`, it's work.
```typescript
// lib/button/button.d.ts
type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>
export declare type NativeButtonProps = {
    htmlType?: ButtonHTMLType;
    onClick?: React.MouseEventHandler<HTMLButtonElement>;
} & BaseButtonProps & Omit<React.ButtonHTMLAttributes<HTMLButtonElement>, 'type'>;
```

**Comment by shpetimselaci** [comment]
Same issue here.

**Comment by arantespp** [comment]
Same here

**Comment by zsirfs** [comment]
> Same here. Fixing by now adding `declare module 'antd';` to `typings.d.ts`

Now everything is the any.

**Comment by zsirfs** [comment]
![image](https://user-images.githubusercontent.com/22249411/55777857-ca4aa680-5ad3-11e9-8b0e-4712e40b1aaf.png)
This is the tsconfig. Hope to be able to help you.

**Comment by afc163** [comment]
Keep this open until release.

**Comment by genc6541** [comment]
> rd that



> Same here. But I bypassed the problem by downgrading `@types/react` to `16.8.11`. I think it breaks in both `16.8.12` and `16.8.13`.
> 
> Also heard that `16.8.9` does not work too. Suspicious change... [DefinitelyTyped/DefinitelyTyped#34194](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34194)

This solution did not worked for me :(

**Comment by chenyong** [comment]
@genc6541 check `node_modules/@types/react/package.json` and `yarn list` to see if it's cached?

**Comment by sysoft** [comment]
+1 downgrade to  @types/react@16.8.8 and resolved

**Comment by XianZhengquan** [comment]
@afc163 这个修复了吗？什么时候发布

**Comment by zombieJ** [comment]
> @afc163 这个修复了吗？什么时候发布

Patch version release each weekend.

**Comment by genc6541** [comment]
@chenyong Yes you are right.I saw  16.8.13 When I controlled node_modules. I have add @types/react as 16.8.11 in my package.json and now it is working. Thank you.

**Comment by hulkyuan** [comment]
set @types/react to 16.8.11 ,now working thx

**Comment by afc163** [comment]
Fixed in `3.16.3`.

**Comment by lawler61** [comment]
@afc163 how about antd-mobile?

**Comment by hulkyuan** [comment]
之前有一个项目改成@types/react to 16.8.11就成功了，现在换了个项目同样的操作，就解决不了，antd都升级成3.16.3了还是同样的报错,只有删掉button的type属性才能通过

**Comment by zombieJ** [comment]
@hulkyuan, 给 `@types/react` 提过 issue，它们今天发布了 `16.8.15` 可以升上来试试。
