### ISSUE TITLE
表格组件getFieldDecorator设置嵌套属性时，嵌套属性名为纯数字时会变成数组

### ISSUE THREAD

**Issue by linpengfei** [ant-design/ant-design#15934]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4qn769zor0)

### Steps to reproduce
点击页面上的提交

### What is expected?
输出的值里面应该是attr: {124: undefined}

### What is actually happening?
输出的值中attr为一个数组

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.6 |
| System | win10 |
| Browser | Google Chrome  版本 73.0.3683.103（正式版本） （64 位） |

**Comment by zombieJ** [comment]
内部使用的是 `lodash/set` 进行赋值：https://lodash.com/docs/4.17.11#set
纯数字时用数组表示是符合预期的。
如果需要 Object 的话，可以设置成 `${prefix}_${index}` 的形式。
