### ISSUE TITLE
Menu collapsed: no tooltip

### ISSUE THREAD

**Issue by MFoksik** [ant-design/ant-design#15943]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/018ywp01ov)

### Steps to reproduce
props:
- mode="inline"
- inlineCollapsed={true}

### What is expected?
after hover on menu element, there should be tooltip visible

![image](https://user-images.githubusercontent.com/13439968/55720090-3d82e880-5a00-11e9-8682-87041e4fcb00.png)

### What is actually happening?
no tooltip

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.6 |
| System | Windows 10.0.17763 |
| Browser | Chrome 73.0.3683.86 |

---
Mentioned in issue: https://github.com/ant-design/ant-design/issues/15849#issuecomment-480789440

**Comment by zombieJ** [comment]
Find that Menu.Item remove the title logic. Should revert: https://github.com/ant-design/ant-design/commit/ae8b52c290d5eb23d4b24496e8fc70d74b29c670
