### ISSUE TITLE
表格行hover效果取消

### ISSUE THREAD

**Issue by pennchester** [ant-design/ant-design#15944]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
涉及到一些复杂的表格，多行列的合并，各种颜色的展示，hover效果会带来视觉上的难受，希望可以得到控制

### What does the proposed API look like?
#<Table hover={false} {...props} />
或者 
#<Table hover={Function} {...props} />

**Comment by zombieJ** [comment]
It's by design. But you still can over-write this by css: https://codesandbox.io/s/j76jk8zx5w
