### ISSUE TITLE
table 合并行的问题

### ISSUE THREAD

**Issue by HaveDreamMan** [ant-design/ant-design#1595]
我有一个需求，需要合并行。
你们例子是这样的
```jsx
  render(value, row, index) {
    let obj = {
      children: value,
      props: {}
    };
    // 第三列的第三行行合并
    if (index === 2) {
      obj.props.rowSpan = 2;
    }

    // 第三列的第四行被合并没了，设置 rowSpan = 0 直接不用渲染
    if (index === 3) {
      obj.props.rowSpan = 0;
    }

    if (index === 4) {
      obj.props.colSpan = 0;
    }
    return obj;
  }
```

我的需求是我不知道我要合并第几行。我得判断这行的内容是否跟上一行一样，一样就合并，不一样就不合并。你们有什么好的方法吗？

**Comment by benjycui** [comment]
使用 `index` 和 `dataSource` 获取上一行的数据，后面就一样的逻辑了吧。

**Comment by HaveDreamMan** [comment]
您可以写个例子试试，我写了半天都没不行。obj.props.rowSpan = count,这个count也不好算啊。

**Comment by HaveDreamMan** [comment]
当然我采用了另外一个方法，但是我感觉不是特别好，如果只有一列合并还行。如果多列都需要这样的合并。写起来太费劲了。

**Comment by benjycui** [comment]
其实不是很懂你的问题，你说的是合并等，但是你代码又是合并列，我只能猜测着去回答。

**Comment by HaveDreamMan** [comment]
对，我可能多列都需要合并行。我目前的方式写一个列的合并行还可以。但是多列就不好写了。要合并多少行是需要根据数据来计算的。不是固定的。

**Comment by benjycui** [comment]
每个 `columns.render` 只是负责当前列的行合并，多个列都需要合并只是把逻辑重复下而已，不懂为什么会不好写。

相似的逻辑可以抽取成工具函数，所以也无法理解为什么会费劲。。。

**Comment by liu2080019** [comment]
@benjycui 说的没毛病，很好写的
