### ISSUE TITLE
对 td.ant-table-selection-column 设置 CSS 无效

### ISSUE THREAD

**Issue by HuYuee** [ant-design/ant-design#15968]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/04w9x55np)

### Steps to reproduce
设了上面的 CSS 后，th.ant-table-selection-column 宽还是 60px

### What is expected?
希望能通过css的方式来全局修改这个selection的宽度

### What is actually happening?
设了上面的 CSS 后，th.ant-table-selection-column 宽还是 60px

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.4.2 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
```diff
// rowSelection objects indicates the need for row selection
const rowSelection = {
  onChange: (selectedRowKeys, selectedRows) => {
    console.log(
      `selectedRowKeys: ${selectedRowKeys}`,
      "selectedRows: ",
      selectedRows
    );
  },
+ columnWidth: 30,
  onSelect: (record, selected, selectedRows) => {
    console.log(record, selected, selectedRows);
  },
  onSelectAll: (selected, selectedRows, changeRows) => {
    console.log(selected, selectedRows, changeRows);
  }
};
```

https://codesandbox.io/s/48nqwz5r14

**Comment by HuYuee** [comment]
可是我系统里面有很多地方都使用到了table，有没有一种统一的方案能方便全局调整宽度

**Comment by afc163** [comment]
那么你需要封装一个 HOC 的 Table 来统一调用。

**Comment by HuYuee** [comment]
那这样也意味着，我也要将以前的老代码重新改一遍。。。

**Comment by afc163** [comment]
#15990 我调整了一下，把默认宽度移到 css 里来。

**Comment by linpengfei** [comment]
本次改动导致firefox浏览器下选择器的宽度60不生效了
