### ISSUE TITLE
 React ant-design Upload reports an error while adding an attachment to the iosAPP

### ISSUE THREAD

**Issue by baizhiyou** [ant-design/ant-design#15960]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
upload 控件在iphoneAPP上，ios11.4.1中，点击上传附件卡顿，选择附件图片以后闪退，重新加载webview。AndroidApp正常。

### What is expected?
点击一次即可触发上传文件选择框，选择附件图片以后可以成功上传附件，不重新加载webview。iPhoneApp和AndroidApp共同适配。

### What is actually happening?
upload 控件在iPhoneAPP上点击一次即可触发上传文件选择框，选择附件图片以后可以成功上传附件，不重新加载webview。

| Environment | Info |
|---|---|
| antd | 3.10.1 |
| React | react |
| System | Android App ，iPhone App |
| Browser | chrome |

---
ios11中使用upload上传附件，点击选择要上传的图片以后，重新加载了webview，app退出到登录页面

**Comment by zombieJ** [comment]
antd don't provide supports in mobile devices now. Try use antd-mobile instead.

**Comment by afc163** [comment]
Or you can dig into this and send us PR to fix upload in iOS.

**Comment by baizhiyou** [comment]
What component does antd-mobile use to upload attachments? Recommend an iosApp component that can upload attachments? Thank you very much!（ antd-mobile 上传附件使用的是哪个组件？推荐一个iosApp 可以上传附件的组件？谢谢！）

**Comment by afc163** [comment]
Could be same problem as #15885
