### ISSUE TITLE
showQuickJumper=true,此时onChange发生变化，不会去改变输入框中的页码。

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design#15969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/YMpgpY](https://codepen.io/anon/pen/YMpgpY)

### Steps to reproduce
table  标签下 创建 pagination 标签 然后 设置onChange函数   传递 current 和limit 2个参数  

### What is expected?
发现 通过设置 showQuickJumper=true   然后回调触发onChange函数 可以手动的更改选中的页码

### What is actually happening?
发现 通过设置 showQuickJumper=true   然后回调触发onChange函数 无法手动的更改选中的页码

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.4.2 |
| System | win10 |
| Browser | chorme  |

**Comment by zombieJ** [comment]
你的例子不全，我试了一下是好的：https://codesandbox.io/s/3v92784rym

**Comment by yehoan** [comment]
同学给我的例子我试了 不对  不知道是不是因为要 触发请求回调的原因..

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55879967-5c38d900-5bd2-11e9-8288-67b810b0acc1.png)

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55880124-a621bf00-5bd2-11e9-8b7f-458214306542.png)

**Comment by yehoan** [comment]
我的数据是通过请求来的
我怀疑是不是因为请求然后导致你们出的问题

**Comment by zombieJ** [comment]
你的截图里漏了 `current`?

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55881745-d323a100-5bd5-11e9-8bb8-d0e076cecf53.png)

**Comment by yehoan** [comment]
这个有的

**Comment by yehoan** [comment]
当请求成功以后  他依然再之前触发请求的当前页

**Comment by zombieJ** [comment]
你的 `pagination` 里没有 `current` ...

**Comment by yehoan** [comment]
close 吧  我记下笔记
