### ISSUE TITLE
Sider 收起时，default Open 的 Menu 会在进入页面时自动展开

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#15966]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7ykvmxqlkj)

### Steps to reproduce
将 `Layout.Sider` 的 `collapsed` 属性默认开启，下面放一个菜单，设置 `defaultOpenKeys`，刷新页面，菜单会自动被自动弹出展示（并且展开的层级也貌似不太对）。必须要鼠标上去滑一下才消失。

### What is expected?
菜单不会被默认弹出展示。

### What is actually happening?
菜单被默认弹出展示，并且展开的层级也不太对。

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | latest |
| System | Mac OS X 10.14.4 |
| Browser | Chrome Canary 75.0.3759.0 |

**Comment by zombieJ** [comment]
默认弹出是符合预期的，但是层级少了的确是个 BUG。
