### ISSUE TITLE
CheckboxGroup 怎么设置key值 （使用options的方式）

### ISSUE THREAD

**Issue by aNewLearnerHere** [ant-design/ant-design#15964]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/checkbox-cn/](https://ant.design/components/checkbox-cn/)

### Steps to reproduce
error如下：
react-dom.development.js?61bb:506 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in div (created by Context.Consumer)
    in CheckboxGroup (at SearchDealers/index.jsx:44)

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.4.1 |
| System | mac  |
| Browser | chrome |

---
 使用方式；
<CheckboxGroup 
        options={checkOptions} 
        onChange={this.onCheckChange}
   />

**Comment by aNewLearnerHere** [comment]
只要用<CheckboxGroup 
                        options={checkOptions} 
                        onChange={this.onCheckChange}
                   /> 就会有checkOptions: [
        {label: '黎明1', value: {name: '黎明1', id: 12233}},
        {label: '黎明2', value: {name: '黎明2', id: 12233}},
        {label: '黎明3', value: {name: '黎明3', id: 12233}},
        {label: '黎明4', value: {name: '黎明4', id: 12233}},
        {label: '黎明5', value: {name: '黎明5', id: 12233}},
    ],

**Comment by aNewLearnerHere** [comment]
貌似在value 是对象的时候不可以，是string的时候可以，是否是封装的时候将value当作其key值

**Comment by zombieJ** [comment]
options 接收的 value 是 string 类型，如果要 Object 建议自己做一个 map 映射一下。
