### ISSUE TITLE
Table rowSelection checkbox问题

### ISSUE THREAD

**Issue by xianshannan** [ant-design/ant-design#1597]
## 通过setState动态二次以上添加数据

首次stateState初始展示化数据，
第二次通过数组push增加数据后stateState

## 问题-Checkbox全选后效果要多次全选后才正常

[在线console图片](https://leanote.com/api/file/getImage?fileId=572c5af8ab644141b1006fb5)

**Comment by afc163** [comment]
问题描述不清晰的话，定位有点困难。

**Comment by afc163** [comment]
麻烦给出 demo 或者 100% 的可重现步骤。
