### ISSUE TITLE
checkboxGroup 怎么在外界改变值可以影响到多选框的样式变更

### ISSUE THREAD

**Issue by aNewLearnerHere** [ant-design/ant-design#15975]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
问题是我在外部操作（非直接操作多选框）checkboxGroup的值，然后想要直接反应到页面的，实际上checkboxGroup的值已经变更了，但是页面上的多选框需要点击一次才能显示为正常的（如我的外部操作是删除value数组的某一个值，但页面上的那个值的多选框仍为选中状态，需要点击一次才行）

### What does the proposed API look like?
能够获取到点击事件，在外部改变值的时候可以直接触发，更新页面，或者其他更好的方式

**Comment by aNewLearnerHere** [comment]
有没有现实的解决办法呀？

**Comment by zombieJ** [comment]
hi, @aNewLearnerHere
Checkbox.Group 的值变更时本来就会对应改变。检查一下你的代码哈。

如果确信这是一个 BUG，欢迎提供重现~

**Comment by aNewLearnerHere** [comment]
> Checkbox.Group 的值变更时本来就会对应改变

嗯嗯 谢谢 另外就是我找到它没有改变的原因了：当赋值的时候如果是同一个array对象，变更的时候，样式不展示，如果是深拷贝的array对象，即可以
