### ISSUE TITLE
关于 Transfer穿梭框 的功能建议

### ISSUE THREAD

**Issue by Grewer** [ant-design/ant-design#15972]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. 穿梭框中渲染item只有一个api render,然而我想针对性的对右侧 target 中的选项做出其他渲染,比如:多一个输入框,render 中参数只有 record ,无法分辨哪个是 sources ,哪个是 targets

2. 如果 sources 中数据过多,我会选择分页,当然他并没有像表格的那种分页,所以我想将其做成一种 移动端的分页(即下滑到底部时加载下一页的数据),但是
onScroll 的 api 中值提供了 direction, event 两个参数,对于我帮助不大

结论: 因为穿梭框的种种需求无法解决,我只能使用两个表格混合的模式来开发

### What does the proposed API look like?
1. 能够在render中,和onScroll api 一样,告诉我哪个是 left,哪个是 right

2. 能够解决多数据的问题

**Comment by zombieJ** [comment]
Duplicate of #14705

**Comment by Grewer** [comment]
@zombieJ  第一点是相同的,
第二点暂时没人提出,麻烦也解决一下

**Comment by zombieJ** [comment]
有一个 PR 在做 customize render，能自定义就全解决了。
