### ISSUE TITLE
Icon自定义SVG图标在typescript中，一直报类型问题

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#15974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-SVG-%E5%9B%BE%E6%A0%87](https://ant.design/components/icon-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-SVG-%E5%9B%BE%E6%A0%87)

### Steps to reproduce
使用create=react-app --typescript创建项目，安装@svgr/webpack，配置webpack，然后import xxSvg from 'path/*.svg'，使用组件  <Icon component={xxSvg }

### What is expected?
能正确引入

### What is actually happening?
ts报错 Error:(12, 27) TS2322: Type 'string' is not assignable to type 'ComponentClass<CustomIconComponentProps, any> | FunctionComponent<CustomIconComponentProps> | undefined'.

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.13 |
| System | windows10 |
| Browser | chrome73 |

**Comment by XianZhengquan** [comment]
![image](https://user-images.githubusercontent.com/46179450/55783528-32ec5000-5ae1-11e9-8ea6-a4f41514cb3e.png)

**Comment by XianZhengquan** [comment]
才使用 yarn create react-app xx --typescript 创建的项目，https://ant.design/docs/react/use-in-typescript-cn，根据这个一直走，就是这个Icon组件的component一直报错

**Comment by zombieJ** [comment]
`component` 接收的是一个 Component，不是 svg……
<img width="776" alt="屏幕快照 2019-04-09 下午4 16 56" src="https://user-images.githubusercontent.com/5378891/55784332-e99d0000-5ae2-11e9-8917-b5f2f8015805.png">

**Comment by XianZhengquan** [comment]
@zombieJ 可以帮我看一下一个问题吗？

**Comment by 824527066** [comment]
用 styled-components 代替component.

**Comment by 824527066** [comment]
遇到同样问题，无法解决，只能使用如下workaround：
将svg 封装成一个‘组件’，然后引入.
import React from "react";

const Logo = props =>
  <svg > 
.... 
  </svg>;
export default Logo;

App.tsx:
import  Logo from './LogoComponet.js';

.....
<div>
    <Logo />
</div>
