### ISSUE TITLE
ant design tree组件怎么防止一个div拖进另外一个div内部

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#15983]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ant design tree组件防止一个div拖进另外一个div内部。本来是同级的拖拽，结果拖进了兄弟节点的子节点中

### What does the proposed API look like?
同级拖拽不能拖拽到内部

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
