### ISSUE TITLE
分页 Pagination组件 支持disable

### ISSUE THREAD

**Issue by piscdong** [ant-design/ant-design#15986]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
页面上有操作时希望能暂时禁止分页操作

### What does the proposed API look like?
disable={true}

**Comment by afc163** [comment]
Try https://ant.design/components/spin/？

**Comment by kanweiwei** [comment]
@piscdong  自己根据具体的业务，再封装一层吧

**Comment by zombieJ** [comment]
如果之后要做 EditableTable 的话，这个 `disabled` 感觉可以做做。

**Comment by piscdong** [comment]
> @piscdong 自己根据具体的业务，再封装一层吧

> Try https://ant.design/components/spin/ ？

我现在就是这么做的
