### ISSUE TITLE
Dropdown.Button support custom icon

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#15989]
```jsx
<Dropdown.Button icon={<Icon type="down" />}>
  button
</Dropdown.Button>
```

<img width="665" alt="image" src="https://user-images.githubusercontent.com/507615/55854933-ac934500-5b98-11e9-8d2a-ab4b8e398db1.png">

**Comment by DiamondYuan** [comment]
icon 要支持字符串么？如果字符串，是不是按需引用会有问题。

**Comment by afc163** [comment]
对，不支持字符串。

**Comment by DiamondYuan** [comment]
> 对，不支持字符串。

原有的那个 icon 怎么引入？

```react
import { AntDesignOutline, DashboardOutline, TwitterOutline } from '@ant-design/icons';
import AntdIcon from '@ant-design/icons-react';
AntdIcon.add(AntDesignOutline, DashboardOutline);
<AntdIcon type="ant-design-o" />
```

有什么参考吗？

**Comment by afc163** [comment]
这个 issue 暂时不考虑这个问题，不引入新的动态 icon API 就行。

**Comment by DiamondYuan** [comment]
> 这个 issue 暂时不考虑这个问题，不引入新的动态 icon API 就行。

demo 的 eslint 有什么自动修复的方法么。

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/55865914-ddcc3f00-5bb1-11e9-8a5f-7505dee7715f.png)

![image](https://user-images.githubusercontent.com/9692408/55865950-f2103c00-5bb1-11e9-946b-dc11590c3c6f.png)


奇怪了。

**Comment by afc163** [comment]
更新一下 node_modules
