### ISSUE TITLE
Tree组件是否可以增加点击节点勾选的功能

### ISSUE THREAD

**Issue by Zero0331** [ant-design/ant-design#15985]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
点击节点实现选中并勾选节点

### What does the proposed API look like?
onSelect  或者 新增api可以在选中节点的时候实现 onCheck的操作，当前只能通过onSelect的回调遍历选中节点再进行onCheck操作很繁琐，是否可以跟TreeSelect组件一样实现点击节点并勾选

**Comment by afc163** [comment]
```jsx
      <Tree
        checkable
        selectable={false}
```
