### ISSUE TITLE
Button在typescript中，一直报类型错误

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#15994]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/50jwovpk9n)

### Steps to reproduce
在typescript中使用Button组件

### What is expected?
Button组件能正常使用

### What is actually happening?
Button组件不能正常使用

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.3 |
| System | windows10 |
| Browser | chrome73 |

**Comment by XianZhengquan** [comment]
@zombieJ 用create-react-app --typescript创建的项目，只安装antd，然后使用Button组件，一直报 类型错误

**Comment by XianZhengquan** [comment]
![image](https://user-images.githubusercontent.com/46179450/55863921-10743880-5bae-11e9-883e-951b7f19423d.png)

**Comment by XianZhengquan** [comment]
刚刚在codesandbox上面试了一下，开始报错，后面打开就不报错了。。。
但是本地项目还是报错

**Comment by zombieJ** [comment]
新版 `@types/react` 的 BUG，已经给他们提过 issue 了。

**Comment by XianZhengquan** [comment]
我今天创建一个新的项目，一直在找我的问题，妈耶。结果是这个

**Comment by zmhweb** [comment]
我引入Input也报错

**Comment by zmhweb** [comment]
@XianZhengquan 你可以了吗

**Comment by XianZhengquan** [comment]
@zmhweb 不行，等待官方发布新的版本吧
