### ISSUE TITLE
根据数据的不同，显示不同的背景颜色

### ISSUE THREAD

**Issue by poetries** [ant-design/ant-design#15999]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不同单元格渲染不同的颜色

### What does the proposed API look like?
暂无

不同单元格渲染不同的颜色。有一种办法是在render函数里面写上块元素把td撑满，设置根据规则设置颜色即可。但是td里面有padding，填充不满怎么处理?请教一下怎么处理，还有其他处理方式吗
![](https://user-images.githubusercontent.com/16177576/55871294-f130d780-5bbc-11e9-9c80-f386ef8c790b.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/54z9yzk894
