### ISSUE TITLE
sub-table in table overflows  with size="middle"

### ISSUE THREAD

**Issue by sylsaint** [ant-design/ant-design#15991]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/limerary/pen/zXZxJR?&editable=true&editors=001#anon-login](https://codepen.io/limerary/pen/zXZxJR?&editable=true&editors=001#anon-login)

### Steps to reproduce
1. Given a Table with attribute size="middle"
2. Add attribute expandedRowRender to render sub-table
3. Set the attribute size of sub-table to "middle"

### What is expected?
no overflow is expected as the size="default"

### What is actually happening?
right edge of sub-table overflows

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.4.2 |
| System | OS X 10.13 |
| Browser | chrome Version 73.0.3683.86 (Official Build) (64-bit) |

---
method to solve the problem:

.ant-table-middle tr.ant-table-expanded-row td > .ant-table-wrapper {
    margin: -12px -8px -13px;
}

**Comment by afc163** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/507615/55864014-3d285000-5bae-11e9-97aa-31edd04080ad.png">

Great catch!
