### ISSUE TITLE
pagination  发现设置showQuickJumper = true 无法改变当前页码

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design#16001]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
发现设置showQuickJumper = true  改变onChange 没法手动改变 当前页码  还是停留再当前页

### What does the proposed API look like?
希望能改变当前页 因为有些操作需要改变当前页面得位置

**Comment by yehoan** [comment]
table 组件    真的发现这个问题 麻烦 别直接close

**Comment by yehoan** [comment]
https://codesandbox.io/s/v3l6p285zl

**Comment by yehoan** [comment]
这个是链接 我大致说下 就是当我再table 里面选择 paganation  得时候  然后触发o'nchange  当我进行另外一个操作得时候 触发那个请求 然后设置到第一页了 但是我没法回到首页了  还是停留再我触发请求的那一页

**Comment by afc163** [comment]
你没理解 reproduction 的意思，你的 codesandbox 不能运行，没有办法帮助你。

**Comment by afc163** [comment]
可以读一下：https://www.chiark.greenend.org.uk/~sgtatham/bugs-cn.html

**Comment by yehoan** [comment]
codesandbox 因为 我的是整个项目  你可以大致看下思路 很简单 就是一个触发 onchange 的函数 改变那个 currenPage ....

**Comment by afc163** [comment]
另外，我们的同学已经给了答复 https://github.com/ant-design/ant-design/issues/15969#issuecomment-481136670 你选择了不反馈然后开新 issue。

**Comment by afc163** [comment]
还可以读一下 https://zhuanlan.zhihu.com/p/25795393，有问题在 #15969 里继续回复就好。

**Comment by afc163** [comment]
💔

<img width="744" alt="image" src="https://user-images.githubusercontent.com/507615/55875115-ccd9f880-5bc6-11e9-85f5-c7848bf8647a.png">

**Comment by yehoan** [comment]
同学给我的那个例子我试了貌似不行  他那个是直接改变current 但是我这个不知道为什么触发请求以后貌似就不对了  我这个因为是要disptach 的  回调以后就不对了

**Comment by kanweiwei** [comment]
@yehoan  你的pagination没传current，你在外面直接setState({ current: 1 })，就不会影响到Pagination组件, Pagination组件没有接收到你的current，内部会使用自己的state来显示当前页

**Comment by zombieJ** [comment]
看来在 #15969 里应该解答了，这边先关了哈~
