### ISSUE TITLE
isFormField 返回错误

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#16007]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
 console.log(require("rc-form/lib/createFormField").isFormField(AntdForm.createFormField()))

### What is expected?
true

### What is actually happening?
false

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8 |
| System | mac |
| Browser | chrome73.0.3683.86 |

**Comment by zombieJ** [comment]
`isFormField` is not what antd provides. You should not use like this.
