### ISSUE TITLE
tab focus inside form at IE11

### ISSUE THREAD

**Issue by crazyx13th** [ant-design/ant-design#16003]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
At first two examples (Horizontal Login Form, Login Form) you can't jump from username to password with one Tab-Keypress at IE11

### What is expected?
normal Tab-Key behavior like at chrome

### What is actually happening?
 you can't jump from username to password with one Tab-Keypress, you need to press Tab two times at IE11

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.6 |
| System | Win 10 |
| Browser | IE11 |

---
I think the "label-icon" is focused on IE11

thx!

greetings
crazyx13th

**Comment by GuentherK** [comment]
What causes this problem are the SVG's that are displayed. Add focusable="false" to the SVG tag and it will work

![image](https://user-images.githubusercontent.com/5037536/55901730-3ad3ef00-5bca-11e9-9e5e-20a540e8bf95.png)

**Comment by crazyx13th** [comment]
thx GuentherK  for details and zombieJ for fix this tiny bug!
