### ISSUE TITLE
Picker 组件  onChange 只能传递一个值

### ISSUE THREAD

**Issue by yehoan** [ant-design/ant-design#16000]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了当需要同时传递2个值得时候得需求

### What does the proposed API look like?
期望可以根据data得结构来传递不同得值

**Comment by yehoan** [comment]
![image](https://user-images.githubusercontent.com/22631753/55873278-cdbc5b80-5bc1-11e9-91c3-1ecbbf1e82fb.png)

**Comment by yehoan** [comment]
data 得结构 如下  
![image](https://user-images.githubusercontent.com/22631753/55873323-edec1a80-5bc1-11e9-8812-23eb9112da64.png)

**Comment by afc163** [comment]
antd 中没有 Picker 组件，你大概提错地方了。

**Comment by yehoan** [comment]
希望能拿到value 和 type

**Comment by yehoan** [comment]
paganation 得showQuickJumper   回调 真的不会设置页数 我去哪些论坛提问 都 没人理会

**Comment by FTD-ZF** [comment]
我也遇到这问题了，不知道如何获取这个选中的值(label)，只能获取到value
