### ISSUE TITLE
Modal event propagation control

### ISSUE THREAD

**Issue by dimitar-nikovski** [ant-design/ant-design#16004]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When a modal is open, all events inside the modal content and over the modal mask propagate to the ancestors of the modal. This occurs even though in the real DOM the modal container is not a child element of the component which rendered the the modal.

![modal issue](https://user-images.githubusercontent.com/13254921/55878044-861edb00-5b93-11e9-86c9-8e86e97180f5.PNG)

In the real DOM, the modal container, which contains both the mask and the modal wrap, is a child of `body` and the component which rendered the modal is a child of the root element passed to `ReactDOM.render`. So in the real DOM, the event shouldn't propagate, yet it does because it propagates in the virtual DOM.

This causes draggable or selectable elements which are in the component which rendered the modal to respond to events over the modal mask and events inside the modal content. Which, obviously creates very noticeable bugs in the UI.

### What does the proposed API look like?
Not sure, perhaps a way of stopping virtual DOM propagation using React's `nativeEvent` prop over the `SynteticEvent` API as in: https://stackoverflow.com/a/24421834/4625144

**Comment by yesmeck** [comment]
It's React's issue https://github.com/facebook/react/issues/11387 rather than antd's.

**Comment by zombieJ** [comment]
It's the feature of React portal: https://reactjs.org/docs/portals.html#event-bubbling-through-portals

We may not prevent this in the antd side. If you want to not bubble, you wrap an HOC of Modal to handle this.

**Comment by nerdess** [comment]
@dimitar-nikovski  

I solved it for the click-event like this though it seems to be quite hacky: 

```
<div onClick={e => e.stopPropagation()}>
   <Modal ... />
</div>
```

**Comment by elitemineral** [comment]
` const handleWrapClick = useCallback((evt) => {
    evt.stopPropagation();
  }, []);

<Modal>
      {...rest}
      wrapProps={{ onClick: handleWrapClick }}
 >
      {children}
</Modal>
`
