### ISSUE TITLE
SubMenu 不会消失

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1600]
horizontal 和 vertical Menu。当鼠标在两个 SubMenu 直接移动时，前一个子菜单不会消失。

http://codepen.io/anon/pen/WwPwxv?editors=001

`antd@1.0.0-beta9`

**Comment by afc163** [comment]
速度看下，明天发布 1.0.0 。

**Comment by superRaytin** [comment]
正在看。。
