### ISSUE TITLE
DatePicker设置mode='year'时 ，无法点击选择年份

### ISSUE THREAD

**Issue by Arikatou123** [ant-design/ant-design#16018]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/PgmZBv?&editable=true&editors=001#anon-signup](https://codepen.io/anon/pen/PgmZBv?&editable=true&editors=001#anon-signup)

### Steps to reproduce
点击DatePicker ，点击选择年份

### What is expected?
选择年份后DatePicker的value值为选中的值，并且日期面板消失

### What is actually happening?
点击年份后无任何反应

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | mac os 10.14.4 |
| Browser | chrome  74.0.3729.61 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15572
