### ISSUE TITLE
Bottom Card Tabs missing tab line

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#16012]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mm78jw3p2y)

### Steps to reproduce
open reproduce

### What is expected?
Show the line

### What is actually happening?
miss it

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
@rinick here is a problem caused by https://github.com/ant-design/ant-design/pull/15458
