### ISSUE TITLE
Table 的“可编辑单元格”有性能瓶颈，希望可以优化！

### ISSUE THREAD

**Issue by gh-xiaoxiao** [ant-design/ant-design#16014]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当设置 Table 为可编辑行，在没有分页的情况下，行数超过1000行以后（或字段过多），将出现明显的卡顿现象，希望可以优化支持到2000行不卡顿（经常碰到很多业务，要求不能分页显示1000多行，并可以像 excel 一样编辑）。

### What does the proposed API look like?
没有新的API

**Comment by afc163** [comment]
目前可编辑单元格支持不了这么大的数据量，建议进行分页。
