### ISSUE TITLE
InputNumber Bug

### ISSUE THREAD

**Issue by pureZjr** [ant-design/ant-design#16022]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/input-number-cn/](https://ant-design.gitee.io/components/input-number-cn/)

### Steps to reproduce
1.清空输入框的内容。
2.让输入框失去焦点。
3.输入框的值没有重置为最小值。

### What is expected?
1.清空输入框的内容。
2.让输入框失去焦点。
3.输入框的值重置为最小值。

### What is actually happening?
1.清空输入框的内容。
2.让输入框失去焦点。
3.输入框的值没有重置为最小值。

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.3 |
| System | mac |
| Browser | Google Chrome73.0.3683.86 |

---
还试了一种情况就是：
1.在输入框输入非数字 eq:（英文）
2.失去输入框焦点，
3.重置为最小值（这是正常的）。
此时我清空了输入框，失去输入框焦点，输入英文，就重置为空了。

**Comment by 1010543618** [comment]
https://github.com/react-component/input-number/blob/906ce429f64b5fa2f69730670c4fe87c3ac22c01/src/index.js#L301

貌似一开始设计的就是为空字符串的时候还是空字符串。应该把 302 行改成这样比较好，看官方的说法吧

```js
this.props.min || '';
```

**Comment by zombieJ** [comment]
它的逻辑是输入非法字符串后，失去焦点重置为上一次正确的值。该正确的值包含数字和空字符串：
![Kapture 2019-04-16 at 15 38 30](https://user-images.githubusercontent.com/5378891/56190849-bbc53780-605d-11e9-9dfd-228d89ab6a76.gif)

原因是从组件角度其实不能确定 min / max / `empty` 哪个更符合预期，而上一次是确定的。

**Comment by pureZjr** [comment]
噢噢 如果包含空字符串的话就✅了
