### ISSUE TITLE
求指点，我这样编写代码，但什么效果也看不到呢？

### ISSUE THREAD

**Issue by jjwangel** [ant-design/ant-design#1602]
< scr ipt type="text/jsx">
    import { Button } from 'antd';

    ReactDOM.render(<div>
                <But ton type="primary" size="large">大号按钮</Button>
                <But ton type="primary">中号按钮(默认)</Button>
                <Butt on type="primary" size="small">小号按钮</Button>
            </div>
            ,document.getElementById('ant-div'));

</scr ipt>

**Comment by jjwangel** [comment]
我把代码粘上去，但看不到内容？

**Comment by jjwangel** [comment]
“<script type="text/jsx">
    import { Button } from 'antd';

    ReactDOM.render(<div>
                <Button type="primary" size="large">大号按钮</Button>
                <Button type="primary">中号按钮(默认)</Button>
                <Button type="primary" size="small">小号按钮</Button>
            </div>
            ,document.getElementById('ant-div'));

</script>”

**Comment by jjwangel** [comment]
在代码中加了些空格。

**Comment by afc163** [comment]
你为什么要加空格...
