### ISSUE TITLE
Modal Component, parent's lifecycle componentDidUpdate executed before child's 

### ISSUE THREAD

**Issue by gy134340** [ant-design/ant-design#16024]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/6y7wyjo7qr)

### Steps to reproduce
https://codesandbox.io/embed/6y7wyjo7qr

1.  在 iframe 的 body  元素上，右键 =》break on =》 attribute modification, 
  这样断点会在 Dialog 组件 update body 属性时停住，可以方便找到 Dialog 的 componentDidUpdate 位置。

  

2. 点击打开关闭 Modal, 会发现每次 Modal 执行 componentDidUpdate 都在 Dialog 前面

ps: Dialog 组件代码位置： https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L86

### What is expected?
parent's componentDidUpdate should be executed after child's componentDidUpdate

### What is actually happening?
parent's componentDidUpdate  executed before child's componentDidUpdate

| Environment | Info |
|---|---|
| antd | 2.13.14 |
| React | 16 |
| System | macOs |
| Browser | Chrome |

---

**Comment by gy134340** [comment]
![test12](https://user-images.githubusercontent.com/14243932/55939419-41b53d00-5c70-11e9-90b6-d9f4aad908ad.gif)

**Comment by zombieJ** [comment]
Hi @gy134340 , we don't maintains antd@2.x for the plan. Please try antd@3.x if possible.
