### ISSUE TITLE
List列表样式布局错乱

### ISSUE THREAD

**Issue by An0nymous0** [ant-design/ant-design#16023]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/list-cn/ ](https://ant.design/components/list-cn/ )

### Steps to reproduce
进入重现链接F12往内容里放些字符，图片就被挤出去了

### What is expected?
图片已经超出DIV了

### What is actually happening?
是否需要用户自己处理。

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.5 |
| System | mac |
| Browser | chrome 73 |

![image](https://user-images.githubusercontent.com/6836030/55938852-e0409e80-5c6e-11e9-9958-075bf93bb554.png)

**Comment by 1010543618** [comment]
这是由于内联盒子给元素撑开了（渲染时将上面一长串当成一个单词了），应该设置内联盒子的样式
比如使用`word-wrap: anywhere;`

**Comment by zombieJ** [comment]
默认情况下，文本带空格是会换行的。如果有超长文本的需求，就需要用户自己设置一下断行样式：https://codesandbox.io/s/v84y21jq4y
