### ISSUE TITLE
Input allowClear property fails to recognized

### ISSUE THREAD

**Issue by LJJ1996** [ant-design/ant-design#16027]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ljj1996/pen/eoWWxL?editors=0011](https://codepen.io/ljj1996/pen/eoWWxL?editors=0011)

### Steps to reproduce
```
<Input placeholder="input with clear icon" onChange={onChange} allowClear/>
```

### What is expected?
Input allowClear property can work well

### What is actually happening?
chrome console warning: React does not recognize the `allowClear` prop on a DOM element.
And this property fails to work

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.8.6 |
| System | windows |
| Browser | 73.0.3683.86 |

**Comment by afc163** [comment]
https://codesandbox.io/s/7j6nyo2n36

Cannot reproduce, it works well.

**Comment by afc163** [comment]
`allowClear` was added in 3.12.0, please upgrade to latest version of antd.

https://ant.design/changelog-cn#3.12.0

**Comment by pkyeck** [comment]
I can reproduce this - at least for TextArea and an older version of Antd (v3.23.2)

https://codesandbox.io/s/antd-reproduction-template-k7k6n

Maybe just add something to the docs about a minimum version ...
