### ISSUE TITLE
带页签的Card IE9下 tab高亮失效

### ISSUE THREAD

**Issue by soonyh** [ant-design/ant-design#16033]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/card-cn/#components-card-demo-tabs](https://ant.design/components/card-cn/#components-card-demo-tabs)

### Steps to reproduce
![demo](https://soonyh.coding.me/ppt-react/pic/333.gif)

### What is expected?
tab切换时 active 高亮跟随

### What is actually happening?
高亮失效

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.8.3 |
| System | win10 |
| Browser | ie9 |

**Comment by soonyh** [comment]
@afc163  能复现吗？  老版本没有这个问题，升级完出现的

**Comment by afc163** [comment]
我找不到 IE9 测试环境了，能尝试帮我们排查修复一下么？

**Comment by afc163** [comment]
@soonyh 给我一个可重现的 Git Repo 吧。

**Comment by afc163** [comment]
我尝试测试了一下最新版本，貌似没有问题：https://github.com/afc163/card-tabs-ie9

![1](https://user-images.githubusercontent.com/507615/58008014-0b47c900-7b1e-11e9-9462-6037dd23f553.gif)

如果还有问题，可以在这里回复并给一个重现 repo，我到时再 reopen。
