### ISSUE TITLE
PageHeader "back" button is just a clickable <div> which isn't semantically correct

### ISSUE THREAD

**Issue by Stephen2** [ant-design/ant-design#16038]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The "back" button should be an actual `<button>` element if it just exposes an `onClick`, OR it could possibly be an `<a>` element, if it accepted an `href` property.

Either way, a clickable `<div>` is no good, because keyboard users can't TAB to it - breaking accessibility

### What does the proposed API look like?
No API change, for starters, just make the back arrow render inside a `<button>`.

This might fit well with the propsed https://github.com/ant-design/ant-design/issues/15892 <-- allow Button to look like plain hyperlink/text

**Comment by zombieJ** [comment]
Nice catch.
@chenshuai2144 , it should use transButton instead: https://github.com/ant-design/ant-design/blob/master/components/_util/transButton.tsx
