### ISSUE TITLE
Radio dot not in center on firefox

### ISSUE THREAD

**Issue by Warix3** [ant-design/ant-design#16039]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

There were issues like this but all closed because you couldn't reproduce, or some other problem. 

### Reproduction link
[https://ant.design/components/radio/](https://ant.design/components/radio/)

### Steps to reproduce
No steps needed, just open link and look at radio button, when it's active the blue dot is not in center.

### What is expected?
![Chrome](https://i.imgur.com/iCymLWt.png)

### What is actually happening?
![Firefox](https://i.imgur.com/0chzfF0.png)

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | Version used on https://ant.design/components/radio/ |
| System | Windows 10 Pro 1809 |
| Browser | Firefox 66.0.2 (64-bit) and Firefox developer edition 67.0b9 (64-bit) |
| Resolution | 1920x1080 |
| Browser scaling | 100% |
| Windows font scaling | 100% |
---
If we remove border roundness the difference becomes very clear:
![Firefox vs Chrome](https://i.imgur.com/CPvJm1n.png)
I have attempted to fix this by increasing css scaling function to .876 instead of .875, it becomes centered but also it becomes thicker on both firefox and chrome:
![Firefox vs Chrome with .876 scaling](https://i.imgur.com/Lr7qOTx.png)
And without border roundness for clearer difference:
![Firefox vs Chrome with .876 scaling and no round borders](https://i.imgur.com/XbRcWQX.png)

It gets centered with .876 but it becomes thicker, ideally we need a solution without changing css scale. It could work with scaling if you can make the outer pixel border half transparent like in chrome, but I'm sure there is a more elegant solution.

**Comment by afc163** [comment]
#11640 #10167

**Comment by Warix3** [comment]
I've seen those issues but they haven't provided a solution. They were closed because you were unable to reproduce the issue. I tried to fix the issue myself as you can see in the submission but I'm not a css expert and I stuck there. I was hoping I can help you to reproduce the issue. 
I just tested with microsoft edge and it's not in the center there either:
![Edge](https://i.imgur.com/Rn91WmK.png)

Maybe you can reproduce it on edge if not on firefox? The root cause is probably the same. Also have you tried using the exact OS version? Maybe it's an issue with Windows 10 Pro 1809

**Comment by afc163** [comment]
I am using MacOS 10.14.3 and Firefox 66.0.3, I can't find your envioronment to reproduce the problem now.

<img width="43" alt="image" src="https://user-images.githubusercontent.com/507615/56009365-26027300-5d12-11e9-9fc1-4565c0b3244c.png">

**Comment by Warix3** [comment]
Your result seems to be a bit bigger. I'm assuming you are using resolution of more than 1920x1080. Have you tried with 1920x1080 resolution?

**Comment by Warix3** [comment]
I just tried with 4k (3840x2160) And I got the same result as you. So it's probably a problem with resolution. I think you need to use 1920x1080 resolution to see the issue.

**Comment by 1010543618** [comment]
https://codepen.io/1010543618/pen/vMZmKb?editors=0110

It‘s seem the firefox rendering bugs.

In firefox 66.0.3 : not in the center
![图片](https://user-images.githubusercontent.com/25266120/56013303-b5b01d80-5d22-11e9-8f14-4294d3cbc9a3.png)

In chrome 72.0.3626.119 : in the center 
![图片](https://user-images.githubusercontent.com/25266120/56013354-e1cb9e80-5d22-11e9-98cd-a86e3c8f7ca1.png)



<blockquote><div><strong><a href="https://codepen.io/1010543618/pen/vMZmKb?editors=0110">Attention Required! | Cloudflare</a></strong></div></blockquote>

**Comment by zombieJ** [comment]
Tested found the real size is 7px (`transform: scale(0.875)`):

> <img width="572" alt="屏幕快照 2019-04-15 下午3 07 13" src="https://user-images.githubusercontent.com/5378891/56113431-70912300-5f90-11e9-8b7c-d575e562df6b.png">

code: https://github.com/ant-design/ant-design/blob/master/components/radio/style/index.less#L119

ref commit: https://github.com/ant-design/ant-design/blame/df356a586c194e1050d6e5c66966dd6931e458d1/components/radio/style/index.less

**Comment by zombieJ** [comment]
Is that safe to remove this `transform`? @afc163

**Comment by afc163** [comment]
I don't think so, it is used for animation.

**Comment by zombieJ** [comment]
@Warix3 , could you test on your side to modify the `transform: scale(0.875)` to `transform: scale(0.75)` and have a look?

**Comment by Warix3** [comment]
@zombieJ using scale(0.75) makes it centered but also smaller. And using scale(0.876) makes it also centered but bigger.

**Comment by zombieJ** [comment]
@Warix3 ,
We changed size from 7px to 8px. It will resolve this but little large than before : )

**Comment by adred** [comment]
We are facing this issue. This is from the components page. 
![radiobutton](https://user-images.githubusercontent.com/607534/107730096-9d015c00-6d2d-11eb-9b7c-12e314329744.png)
Looks like an eye looking upwards.

**Comment by gugol2** [comment]
I fix it by setting the opacity as 1, which means commenting out the opacity:

```
.ant-radio-input {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    z-index: 1;
    cursor: pointer;
    /* opacity: 0; */
}
```
