### ISSUE TITLE
Cannot Re-Open Horizontal Menu in Mobile Browser after Scrolling

### ISSUE THREAD

**Issue by sagescrub** [ant-design/ant-design#16036]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://dlease.io/](https://dlease.io/)

### Steps to reproduce
- Open link in Android Firefox.
- Open the menu by tapping on the "..." Button at top of page
- Scroll down (menu closes automatically)
- Scroll back up (without tapping page)
- Try to open menu. Menu does not open a second time

### What is expected?
Expect the menu to open after tapping it a second time.

### What is actually happening?
The menu does not open a second time after it is opened and then scrolling (which causes the menu to close). However it is possible to open the menu a second time by tapping the page (placing focus on the page) and then tapping the menu icon.

| Environment | Info |
|---|---|
| antd | 3.10.4 |
| React | 16.6.0 |
| System | Android / iOS |
| Browser | Firefox / Opera |

---
In iOS safari the behavior is even worse. It is not possible to re-open the menu a second time even after tapping the page.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15688#issuecomment-477065182
