### ISSUE TITLE
TimePicker disabledMinutes是否可以动态控制？

### ISSUE THREAD

**Issue by qiaolb** [ant-design/ant-design#1603]
我有一个需求，需要根据Hour选择显示不同的Minutes，例如，0点-8点，分钟间隔30分钟，8点-23点，分钟间隔为5分钟。有没有办法实现呢？
谢谢！

**Comment by afc163** [comment]
disabledMinutes 是一个 function，可以动态计算。http://ant.design/components/time-picker/#picker-demo-disable-options
