### ISSUE TITLE
DatePicker allowClear is not consistent with TimePicker allowClear

### ISSUE THREAD

**Issue by alvaroortega** [ant-design/ant-design#16030]
- [ X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/alvaroortega/pen/Lvyjze?&editable=true&editors=001](https://codepen.io/alvaroortega/pen/Lvyjze?&editable=true&editors=001)

### Steps to reproduce
1. Select a Date.
2. Select a time
3. Manually select the value of the time and press delete. The value of he time restore itself as it is not allow to clear
4. Manually select the value in the input for the date and delete. The value does not restore

### What is expected?
If the datePicker is not allowed to Clear we should not be able to do it manually as it happens with the timePicker

### What is actually happening?
DatePicker value can be wiped out, onchange returns null value

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.5.2 |
| System | macOS Mojave 10.14.4 |
| Browser | Google Chrome 73.0.3683.86 |

---
TimePicker used to have allowEmpty but it was unified with allowClear but it does not seem to be a posibility to set a similar behaviour for datePicker

**Comment by afc163** [comment]
It is not about `allowClear`, just TimePicker has some a state problem.

**Comment by alvaroortega** [comment]
TimePicker or DatePicker has the problem? TimePicker behavior seems consistent to me

**Comment by afc163** [comment]
I believe DatePicker behavior is right, we should fix TimePicker.

**Comment by alvaroortega** [comment]
This issue has been closed with no more information. Are you going to take any action? are you modifying the TimePicker then? in that case how?

Will the elements then be allowed to manually clear the values even if allowClear is set to false?

**Comment by afc163** [comment]
<img width="573" alt="图片" src="https://user-images.githubusercontent.com/507615/56074421-abeeee80-5de4-11e9-98fa-c29fff3e27e3.png">

**Comment by nocarroll** [comment]
FWIW, this is going to change expected behaviour in our webapp which we are going to have to handle manually now.

I agree with @alvaroortega that the TimePicker implementation seemed more correct.
