### ISSUE TITLE
upload组件,文件数量超过两行时,上传按钮另起一行了

### ISSUE THREAD

**Issue by aNameHere** [ant-design/ant-design#16045]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ym52x4q1p1)

### Steps to reproduce
1.打开重现链接,这是官方的upload组件的例子; 把第48行代码,能上传的最大文件数量改大一点,比如改为8,然后在页面上测试上传文件的功能
2.上传的图片只有两三张, 还没有分行的时候, upload按钮跟在第一行图片后面
3.上传的图片到第五六张的时候, 图片自动分成了两行, 这个时候upload按钮另起一行了

### What is expected?
希望upload按钮跟在第二行图片后面, 即:当一行图片没有放满,还有空间的时候,upload按钮能跟在最后一张图片后面

### What is actually happening?
图片超过两行时,即使图片后还有放 上传图片按钮 的空间, 上传按钮还是另起一行了

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | latest |
| System | mac os |
| Browser | chrome |

**Comment by zombieJ** [comment]
Seems current dom layout can't handle this. Maybe we should create flatten layout for card view.

**Comment by afc163** [comment]
How about

```jsx
<Upload append={<Icon type="add" />} />
```

or

```jsx
<Upload renderUploadList={list => list} />
```

**Comment by zombieJ** [comment]
> How about ...

I like second one. But still need to consider how to inject children of Upload into UploadList.


ref: #16047

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/913d19113fdc140ac9053abc7de4b0512b5cc4c1 and https://github.com/ant-design/ant-design/commit/5742ae221c72d60b9a7c4de6ae3528678b043e48

**Comment by lihuanji** [comment]
现在，文件数量不超一行的时候，上传按钮另起一行了。
