### ISSUE TITLE
select 组件 下拉框里加了图片，选中后输入框里能不展示图片吗

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#16041]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
select 组件 下拉框里加了图片，选中后输入框里能不展示图片吗

### What is expected?
select 组件 下拉框里加了图片，选中后输入框里不展示图片。仅仅展示选中的文字

### What is actually happening?
select 组件 下拉框里加了图片，选中后输入框里展示图片

| Environment | Info |
|---|---|
| antd | 2.13.14 |
| React | 16 |
| System | 10 |
| Browser | chrome |

**Comment by afc163** [comment]
Try `optionLabelProp`
