### ISSUE TITLE
Upload itemRender

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#16047]
#11002
#8387
#17059

**Comment by DiamondYuan** [comment]
+1  前几次类似需求，都是把原先的列表屏蔽的。

**Comment by afc163** [comment]
Or `Upload.Item` that proposeed in #16505 by @StarryFire

**Comment by Ende93** [comment]
Any update?

**Comment by phoema** [comment]
这个Issue快1年了，没看太明白，是加render还是不加啊？

**Comment by Kermit-Xuan** [comment]
这个我来处理吧。

**Comment by Kermit-Xuan** [comment]
有个问题，加的时候是加每一项的自定义渲染器，还是整个列表的自定义渲染器呢？

**Comment by phoema** [comment]
![image](https://user-images.githubusercontent.com/8730272/89183534-f42db380-d5c9-11ea-8a78-f8045c7c3199.png)
之前render，我们的需求是类似能够自定义每行文件信息的扩展信息。
如上图，现在1年了，不知道大家是否有其他的需求。

**Comment by phoema** [comment]
[Common.zip](https://github.com/ant-design/ant-design/files/5016020/Common.zip)

**Comment by Kermit-Xuan** [comment]
> ![image](https://user-images.githubusercontent.com/8730272/89183534-f42db380-d5c9-11ea-8a78-f8045c7c3199.png)
> 之前render，我们的需求是类似能够自定义每行文件信息的扩展信息。
> 如上图，现在1年了，不知道大家是否有其他的需求。

你的这个需求其实本来直接改 `fileList` 是可以实现的，如果我们把 `uploadList` 的渲染完全自定义放开，用户要做的东西就比较做了，像进度条、删除操作等这些东西都需要自己去实现，这样可能就会有问题。

**Comment by afc163** [comment]
应该是每一项的自定义渲染。

**Comment by phoema** [comment]
我本来也以为只改fileList 就可以，但是渲染无法自定义，所以屏蔽了原来的fileList ，重新处理了进度条、删除、onChange等。

**Comment by Kermit-Xuan** [comment]
> 应该是每一项的自定义渲染。

如果是这样的话，用户想借助文件列表去实现列表的拖拽，这个怎么处理？这时候可能就需要用户屏蔽掉原有的文件列表，自己去实现了

**Comment by afc163** [comment]
这个应该可以用 itemRender 实现吧，参考 Table 的行拖拽例子。

**Comment by Kermit-Xuan** [comment]
OK，那我就把列表项的渲染全部开放出去了，包括进度条，预览、删除操作等等？

**Comment by afc163** [comment]
对，预期是能定义成任意模样。

**Comment by Geczy** [comment]
More than a year later and still no way to customize upload list?

**Comment by Kermit-Xuan** [comment]
It's very sorry and i will handle it in this weekend.

**Comment by ritingliudd01** [comment]
@Geczy the only way out now for me is to work on `name` when generating `fileList`. Instead of pure text, make its value a React node to go with more `props` needed like below

```
url = window.URL.createObjectURL(res)
images.push({

    // Pass resource_id by span attribute rel
    name: <span rel={ele}>{resourceMap[ele]?.filename || ele}</span>,
    status: 'done',

    // Leave uid as it is otherwise renaming it will cause unexpected error
    // uid: ele, 
    resource_id: ele,
    thumbUrl: url,
    url
})

**Comment by Kermit-Xuan** [comment]
Support in [#26333](https://github.com/ant-design/ant-design/pull/26333)
