### ISSUE TITLE
Collect current api standard

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#16048]
Since we have lots of components. It's time to collect the api into standard.
This will help to new components find api ref in future.

============================

# TODO:
* [x] Updated in wiki
* [x] English version
* [ ] Site PR document

**Comment by ztplz** [comment]
What's this for?

**Comment by zombieJ** [comment]
Currently we naming new api not have the rule guide, we may need have more standard about this.

**Comment by zombieJ** [comment]
## 命名规则
总体上，我们命名使用全称。尽量避免使用缩写。



### 属性
* 初始化属性，命名方式为： default + 属性名 
* 强制渲染属性： forceRender
  * 强制渲染子组件： force + 子组件名 + Render 
* 数据源： dataSource 
* children :
  * 主要展示区域内容 ，避免额外的属性名称
  * 选项相关诸如 Option 、TreeNode 
  * 自定义包裹组件可以考虑 coponent 如果 children 会存在它用的情况
* 展示相关命名方式为： show + 属性名 
* 功能相关命名方式为： 属性名 + able 
* 禁用子组件功能： disabled + 子组件名 
* 主图标： icon 
  * 多个图标： 功能 + Icon 
* 触发点： trigger 
  * 子功能触发： 子功能 + Trigger 
  * 在触发某个时间时处理某件事情： xxx + On + 事件名 （例：destroyOnClose）


### 事件
* 触发事件： on + 事件名 
* 在触发之前的事件： before + 事件名 
* 在触发之后的事件： after + 事件名 


### 现有 API
* ✅可以使用
* 🔒特殊组件使用
* ⚠️不推荐使用，理论上不再新增
* 🚫废弃，勿用


  | API | 相关组件 | 备注
-- | -- | -- | --
✅ | children | - | AutoComplete 的 children 支持自定数据源和输入框，是一个不好的设计。切勿模仿
✅ | disabled | auto-complete, button, cascader, checkbox, collapse, date-picker, dropdown, input-number, input, mention, menu, radio, rate, select, slider, switch, time-picker, transfer, tree-select, tree, typography, upload |  
✅ | size | avatar, button, card, cascader, date-picker, dropdown, input-number, input, list, pagination, radio, select, skeleton, spin, steps, switch, table, tabs, tree-select | small, middle, large, default （default 如果和其他相同，则只保留 default）
✅ | title | anchor, badge, card, drawer, list, menu, modal, page-header, popconfirm, popover, select, skeleton, statistic, steps, table, tooltip, tree-select, tree |  
✅ | value | auto-complete, calendar, cascader, checkbox, date-picker, input-number, input, mention, radio, rate, select, slider, statistic, time-picker, tree-select |  
✅ | defaultValue | auto-complete, calendar, cascader, checkbox, date-picker, input-number, input, mention, radio, rate, select, slider, time-picker, tree-select |  
✅ | type | alert, button, card, divider, dropdown, form, grid, icon, input, progress, table, tabs, typography |  
✅ | autoFocus | auto-complete, cascader, checkbox, date-picker, input-number, mention, radio, rate, select, slider, switch, time-picker |  
✅ | allowClear | auto-complete, cascader, date-picker, input, rate, select, slider, time-picker, tree-select |  
✅ | icon | alert, avatar, button, message, modal, notification, popconfirm, steps, tree | 主图标直接用 icon 不要 xxxIcon
✅ | loading | button, card, list, mention, select, skeleton, switch, table |  
✅ | width | drawer, icon, layout, modal, progress, skeleton, table |  
✅ | placeholder | auto-complete, cascader, date-picker, mention, select, time-picker, tree-select |  
✅ | description | alert, card, empty, list, notification, steps |  
⚠️ | locale | calendar, date-picker, list, locale-provider, table, transfer | 推荐使用 LocaleProvider 代替
✅ | footer | list, modal, page-header, table, transfer |  
✅ | mode | calendar, date-picker, menu, select, timeline | Menu: vertical / horizontal / inlineDatePicker: time\|date\|month\|yearSelect: 'multiple' \| 'tags'
✅ | suffixIcon | cascader, date-picker, select, time-picker, tree-select | 理论上带图标的组件，主图标应该是 icon ，而下拉箭头的图标用 suffixIcon 。这里各种 Picker 图标命名是 suffixIcon 其实不是很好的命名方式。
✅ | visible | drawer, dropdown, modal, tag, tooltip | 区别于 open ，从无到有使用 visible
✅ | extra | card, collapse, form, list, page-header | 操作区域，一般用于右上角，PageHeader提示信息，Form
✅ | placement | drawer, dropdown, mention, notification, tooltip | bottomLeft / bottomCenter / bottomRight / topLeft / topCenter / topRightMention: top, bottom
✅ | avatar | card, comment, list, skeleton |  
✅ | showSearch | cascader, select, transfer, tree-select |  
✅ | open | auto-complete, date-picker, select, time-picker | 所有打开、展开形式的组件优先使用 open
✅ | checked | checkbox, radio, switch, tag |  
✅ | name | checkbox, form, radio, upload |  
  | content | comment, message, modal, popover |  
✅ | format | date-picker, progress, statistic, time-picker |  
✅ | bordered | card, collapse, list, table |  
✅ | closable | alert, drawer, modal, tag |  
✅ | multiple | menu, tree-select, tree, upload |  
  | bodyStyle | card, drawer, modal |  
  | message | alert, form, notification |  
✅ | actions | card, comment, list |  
✅ | defaultChecked | checkbox, radio, switch |  
✅ | shape | avatar, button, skeleton | circle, round
  | target | affix, back-top, button |  
✅ | forceRender | collapse, modal, tabs |  
  | filterOption | auto-complete, select, transfer |  
✅ | color | badge, tag, timeline |  
  | dropdownClassName | date-picker, select, tree-select |  
✅ | status | badge, progress, steps | wait / process / finish / error
✅ | selectedKeys | menu, transfer, tree |  
✅ | dataSource | auto-complete, table, transfer | 数据源理论上都是这个
🔒 | trigger | dropdown, layout, tooltip | 触发器，Layout.Sider行为触发：click / hover / contextMenu，Dropdown
✅ | max | form, input-number, slider |  
✅ | min | form, input-number, slider |  
⚠️ | align | grid, table, tooltip |  
🔒 | theme | icon, layout, menu |  
✅ | prefix | input, mention, statistic | 如果一个组件不区分前缀内容，优先使用 prefix 而非 prefixIcon
⚠️ | notFoundContent | cascader, mention, select | 优先使用 ConfigProvider
✅ | options | cascader, checkbox, radio | 优先考虑一下 dataSource
✅ | selectable | menu, tree-select, tree |  
✅ | defaultActiveKey | collapse, tabs |  
✅ | expandIcon | collapse, table |  
✅ | count | badge, rate |  
✅ | header | collapse, list |  
✅ | dot | badge, timeline |  
✅ | showArrow | collapse, select |  
✅ | offset | badge, grid |  
✅ | href | anchor, button |  
  | popupStyle | date-picker, time-picker |  
✅ | dots | carousel, slider |  
⚠️ | vertical | carousel, slider | 已经有很多同类的方法了，不推荐。改用 mode 代替。
✅ | destroyOnClose | drawer, modal |  
🔒 | mask | drawer, modal |  
🔒 | maskClosable | drawer, modal |  
🔒 | maskStyle | drawer, modal |  
  | text | badge, table |  
🔒 | height | drawer, icon |  
🔒 | zIndex | drawer, modal |  
✅ | separator | breadcrumb, date-picker |  
  | overlayClassName | dropdown, tooltip |  
  | overlayStyle | dropdown, tooltip |  
✅ | id | form, input |  
✅ | label | form, select |  
  | popupClassName | cascader, time-picker |  
  | offsetBottom | affix, anchor |  
🔒 | gutter | grid, list |  
🔒 | xs | grid, list |  
🔒 | sm | grid, list |  
🔒 | md | grid, list |  
🔒 | lg | grid, list |  
🔒 | xl | grid, list |  
🔒 | xxl | grid, list |  
🔒 | showIcon | alert, tree | 只有默认没有 Icon，设置显示才需要。原本就有的通过 icon={false} 隐藏。
🔒 | precision | input-number, statistic |  
🔒 | decimalSeparator | input-number, statistic |  
✅ | step | input-number, slider |  
✅ | suffix | input, statistic | 如果一个组件不区分前缀内容，优先使用 suffix 而非 suffixIcon
  | optionLabelProp | auto-complete, select |  
  | offsetTop | affix, anchor |  
🔒 | rowKey | list, table |  
🔒 | pagination | list, table |  
🔒 | pagination.position | list, table | 限定组件支持 pagination 时位置设置
✅ | defaultSelectedKeys | menu, tree |  
✅ | defaultActiveFirstOption | auto-complete, select |  
✅ | activeKey | collapse, tabs | 区别于 selectedKeys ，这是鼠标/光标所选中的 keys
✅ | defaultOpen | auto-complete, select |  
🔒 | duration | message, notification |  
🔒 | top | message, notification |  
🔒 | cancelText | modal, popconfirm | 区别于 LocaleProvider 设置特殊按钮文字
🔒 | okText | modal, popconfirm | 区别于 LocaleProvider 设置特殊按钮文字
🔒 | okType | modal, popconfirm |  
🔒 | current | pagination, steps |  
✅ | autoClearSearchValue | select, tree-select |  
🚫 | dropdownMatchSelectWidth | select, tree-select | 这个属性很诡异，我们应该自己处理：小于原组件宽度，为原组件宽度大于原组件宽度，则自适应
  | dropdownStyle | select, tree-select |  
  | labelInValue | select, tree-select | 看看有没有其他组织形式
✅ | maxTagCount | select, tree-select |  
✅ | maxTagPlaceholder | select, tree-select |  
✅ | clearIcon | select, time-picker |  
  | filterTreeNode | tree-select, tree |  
🔒 | disableCheckbox | tree-select, tree |  
🔒 | isLeaf | tree-select, tree |  
  | defaultPickerValue | date-picker |  
🚫 | disabledTime | date-picker | 应该收束到一个属性上：disabled={{ time: true }}
  | defaultActiveTabKey | card |  
✅ | showTime | date-picker |  
⚠️ | showTime.defaultValue | date-picker | 看看有没有更好的表现形式
✅ | showToday | date-picker |  
🔒 | overflowCount | badge |  
🔒 | ranges | date-picker |  
🔒 | dashed | divider |  
🔒 | orientation | divider |  
🔒 | hoverable | card |  
🔒 | tabList | card |  
🔒 | showZero | badge |  
🔒 | affix | anchor |  
🔒 | bounds | anchor |  
🚫 | autoplay | carousel | 用 autoPlay 代替
  | overlay | dropdown |  
  | banner | alert |  
🔒 | easing | carousel |  
🔒 | effect | carousel |  
  | params | breadcrumb |  
🔒 | imageStyle | empty |  
🔒 | image | empty |  
  | form | form |  
  | hideRequiredMark | form |  
🔒 | labelAlign | form |  
🔒 | labelCol | form |  
⚠️ | layout | form | 'horizontal'\|'vertical'\|'inline'看起来也能用 mode 代替
🔒 | wrapperCol | form |  
🔒 | colon | form |  
🔒 | options.first | form |  
🔒 | options.firstFields | form |  
🔒 | options.force | form |  
🔒 | options.scroll | form |  
🔒 | options.getValueFromEvent | form |  
🔒 | options.getValueProps | form |  
🔒 | options.initialValue | form |  
🔒 | options.normalize | form |  
🔒 | options.preserve | form |  
🔒 | options.rules | form |  
🔒 | options.trigger | form |  
🔒 | options.validateFirst | form |  
🔒 | options.validateTrigger | form |  
🔒 | options.valuePropName | form |  
🔒 | help | form |  
🔒 | required | form |  
🔒 | validateStatus | form |  
🔒 | enum | form |  
🔒 | len | form |  
✅ | changeOnSelect | cascader |  
🔒 | pattern | form |  
🔒 | transform | form |  
🔒 | validator | form |  
🔒 | whitespace | form |  
✅ | expandTrigger | cascader |  
🔒 | justify | grid |  
🔒 | order | grid |  
🔒 | pull | grid |  
🔒 | push | grid |  
✅ | span | grid | 占据宽度使用
  | fieldNames | cascader |  
  | routes | breadcrumb |  
✅ | src | avatar |  
🔒 | ghost | button |  
🚫 | htmlType | button | 这引起了 typescript 类型问题，我们应该将 type 还给 button。原本的 type 应该转而使用 mode or status 代替？
✅ | srcSet | avatar |  
🚫 | popupPlacement | cascader | 使用 placement 代替
🔒 | spin | icon |  
🔒 | rotate | icon |  
✅ | component | icon | 自定义组件默认使用该字段， AutoComplete 是一个坏例子
🔒 | twoToneColor | icon |  
🔒 | scriptUrl | icon |  
  | extraCommonProps | icon |  
🔒 | fill | icon |  
🚫 | popupVisible | cascader | 使用 open 代替
🔒 | block | button |  
🔒 | addonAfter | input |  
🔒 | addonBefore | input |  
⚠️ | autosize | input | 应该是 autoSize
🔒 | enterButton | input.Search | 非常诡异的属性
🔒 | compact | input |  
🚫 | visibilityToggle | input | 风格不一致，应该用 showPassword 代替
🔒 | hasSider | layout |  
🔒 | breakpoint | layout |  
✅ | collapsed | layout |  
🔒 | collapsedWidth | layout |  
✅ | collapsible | layout |  
✅ | defaultCollapsed | layout |  
⚠️ | reverseArrow | layout | 按理说我们应该自己处理掉
🚫 | matchInputWidth | cascader | 参阅 dropdownMatchSelectWidth 建议
⚠️ | itemLayout | list | 使用 mode 代替
🔒 | loadMore | list |  
✅ | alt | avatar |  
🚫 | split | list | 应该是 showSplit
⚠️ | fullscreen | calendar |  
🔒 | column | list |  
🚫 | defaultSuggestions | mention |  
🚫 | multiLines | mention | 无所谓多行，根据组件 value 自己搞就行了
🚫 | readOnly | mention |  
🚫 | suggestions | mention | 可以和 options 合并，本质上差不多
🚫 | suggestionStyle | mention |  
✅ | defaultOpenKeys | menu |  
✅ | indeterminate | checkbox |  
✅ | forceSubMenuRender | menu |  
🔒 | inlineCollapsed | menu |  
🔒 | inlineIndent | menu |  
✅ | openKeys | menu |  
🔒 | visibilityHeight | back-top |  
🚫 | subMenuCloseDelay | menu | 伪需求？
🚫 | subMenuOpenDelay | menu | 伪需求？
🔒 | accordion | collapse |  
  | overflowedIndicator | menu |  
✅ | maxCount | message |  
⚠️ | destroyInactivePanel | collapse | 或许也适合 destroyOnInactive ？
  | validRange | calendar |  
🔒 | centered | modal |  
🔒 | confirmLoading | modal |  
  | backfill | auto-complete |  
  | showInkInFixed | anchor |  
  | okButtonProps | modal |  
  | cancelButtonProps | modal |  
  | wrapClassName | modal |  
  | activeTabKey | card |  
🚫 | autoFocusButton | modal | 使用 autoFoucs 代替
⚠️ | iconType | modal | 使用 type or status 代替，理论上状态是整体的，而非只有 Icon 才有。
🚫 | keyboard | modal | CloseOnESC
⚠️ | btn | notification | 参考 Modal， closeButton
⚠️ | bottom | notification |  
✅ | subTitle | page-header |  
✅ | backIcon | page-header |  
✅ | tags | page-header |  
🔒 | breadcrumb | page-header |  
🔒 | author | comment |  
✅ | defaultCurrent | pagination |  
✅ | defaultPageSize | pagination |  
✅ | hideOnSinglePage | pagination |  
🔒 | pageSize | pagination |  
🔒 | pageSizeOptions | pagination |  
🔒 | showLessItems | pagination |  
🔒 | showQuickJumper | pagination |  
🔒 | showSizeChanger | pagination |  
🔒 | showTotal | pagination |  
✅ | simple | pagination |  
🔒 | total | pagination |  
🔒 | percent | progress |  
✅ | showInfo | progress |  
🔒 | strokeLinecap | progress |  
🔒 | strokeColor | progress |  
🔒 | successPercent | progress |  
🔒 | strokeWidth | progress |  
🔒 | gapDegree | progress |  
🔒 | gapPosition | progress |  
  | buttonStyle | radio |  
🔒 | allowHalf | rate |  
🔒 | character | rate |  
🔒 | tooltips | rate |  
  | headStyle | card |  
🔒 | datetime | comment | 目前组件带时间的还没有适合的场景，还需要考虑一下这个名字是否适合
🔒 | autoInsertSpaceInButton | config-provider |  
🔒 | firstActiveValue | select |  
🔒 | csp | config-provider |  
🔒 | prefixCls | config-provider |  
  | optionFilterProp | select |  
✅ | removeIcon | select |  
⚠️ | menuItemSelectedIcon | select | 理论上不应该暴露给用户
⚠️ | tokenSeparators | select | separator 足够了
✅ | active | skeleton | 普遍用于出现动画效果时Progress 使用 status=active
🔒 | paragraph | skeleton |  
🔒 | rows | skeleton |  
🔒 | included | slider |  
🔒 | marks | slider |  
🔒 | range | slider |  
⚠️ | tipFormatter | slider | 应该用全称 tooltipFormatter
✅ | tooltipVisible | slider |  
🔒 | delay | spin |  
🔒 | indicator | spin |  
🔒 | spinning | spin | 似乎 active 也行，如果有类似需求优先看看能不能用 active
⚠️ | tip | spin | 不普遍，建议参考一下 message or notification api
  | wrapperClassName | spin |  
✅ | groupSeparator | statistic | 数字格式化专用
  | valueStyle | statistic |  
⚠️ | direction | steps | horizontal / vertical推荐使用 mode
🔒 | labelPlacement | steps |  
🔒 | progressDot | steps |  
🚫 | initial | steps | 使用 defaultCurrent 代替
  | checkedChildren | switch | 不是很好的命名方式，可以使用 checkedText
  | unCheckedChildren | switch | 不是很好的命名方式，可以使用 unCheckedText
🔒 | childrenColumnName | table |  
🔒 | columns | table |  
✅ | components | table |  
✅ | defaultExpandAllRows | table |  
🔒 | defaultExpandedRowKeys | table |  
🔒 | expandedRowKeys | table | 理论上使用 expandedKeys 就行了
⚠️ | expandRowByClick | table | expandRowOnClick
🔒 | indentSize | table |  
  | rowClassName | table |  
🔒 | rowSelection | table |  
🔒 | scroll | table |  
✅ | showHeader | table |  
✅ | colSpan | table |  
🔒 | dataIndex | table |  
✅ | defaultSortOrder | table |  
🔒 | filterDropdown | table |  
🔒 | filterDropdownVisible | table |  
🔒 | filtered | table |  
🔒 | filteredValue | table |  
✅ | filterIcon | table |  
🔒 | filterMultiple | table |  
🔒 | filters | table |  
✅ | sorter | table |  
✅ | sortOrder | table |  
🔒 | sortDirections | table |  
✅ | closeText | alert |  
✅ | cover | card | 封面类型
🔒 | autoExpandParent | tree |  
🔒 | blockNode | tree |  
✅ | checkable | tree |  
✅ | checkedKeys | tree |  
🔒 | checkStrictly | tree |  
✅ | defaultCheckedKeys | tree |  
🔒 | defaultExpandAll | tree |  
🔒 | defaultExpandedKeys | tree |  
🔒 | defaultExpandParent | tree |  
✅ | draggable | tree |  
✅ | expandedKeys | tree |  
✅ | loadedKeys | tree |  
✅ | switcherIcon | tree |  
🔒 | showLine | tree |  
🔒 | animated | tabs | animatable ?
🚫 | hideAdd | tabs | showAdd
🚫 | tabBarExtraContent | tabs | extra
🔒 | tabBarGutter | tabs |  
  | tabBarStyle | tabs |  
🔒 | tabPosition | tabs |  
🚫 | tab | tabs | title
🚫 | addon | time-picker | footerRender
🚫 | clearText | time-picker |  
🔒 | defaultOpenValue | time-picker |  
🚫 | disabledHours | time-picker | 参考 disabled
🚫 | disabledMinutes | time-picker | 参考 disabled
🚫 | disabledSeconds | time-picker | 参考 disabled
🔒 | hideDisabledOptions | time-picker | showDisabledOptions 更适合
🔒 | hourStep | time-picker |  
⚠️ | inputReadOnly | time-picker | 理论上不应该出现半锁死
🔒 | minuteStep | time-picker |  
🔒 | secondStep | time-picker |  
🔒 | use12Hours | time-picker |  
⚠️ | pending | timeline | 更像是个 placehoder
⚠️ | pendingDot | timeline | placehoderDot
✅ | reverse | timeline |  
⚠️ | arrowPointAtCenter | tooltip | 看起来像是个伪需求
🔒 | autoAdjustOverflow | tooltip |  
✅ | defaultVisible | tooltip |  
⚠️ | mouseEnterDelay | tooltip |  
⚠️ | mouseLeaveDelay | tooltip |  
🔒 | lazy | transfer |  
  | listStyle | transfer |  
✅ | operations | transfer |  
  | operationStyle | transfer |  
🔒 | targetKeys | transfer |  
✅ | titles | transfer | 多个标题
✅ | searchPlaceholder | tree-select |  
✅ | searchValue | tree-select |  
✅ | treeIcon | tree-select |  
🔒 | showCheckedStrategy | tree-select | 其实它不是一个展示， checkedStrategy 更适合
🔒 | treeCheckable | tree-select |  
🔒 | treeCheckStrictly | tree-select |  
🚫 | treeData | tree-select | dataSource
🚫 | treeDataSimpleMode | tree-select | dataSimpleMode
🔒 | treeDefaultExpandAll | tree-select |  
🔒 | treeDefaultExpandedKeys | tree-select |  
🔒 | treeExpandedKeys | tree-select |  
🔒 | treeNodeFilterProp | tree-select |  
🔒 | treeNodeLabelProp | tree-select |  
🚫 | expandAction | tree | expandTrigger
🔒 | code | typography |  
✅ | copyable | typography |  
🔒 | delete | typography |  
✅ | editable | typography |  
🔒 | ellipsis | typography |  
🔒 | mark | typography |  
🔒 | underline | typography |  
🔒 | strong | typography |  
✅ | level | typography |  
🔒 | accept | upload |  
🔒 | action | upload |  
🔒 | directory | upload |  
⚠️ | data | upload | 没法从命名一下子理解是干什么的
🔒 | defaultFileList | upload |  
🔒 | fileList | upload |  
🔒 | headers | upload |  
🔒 | listType | upload |  
🔒 | showUploadList | upload |  
⚠️ | supportServerRender | upload | 我们应该内部支持
🔒 | withCredentials | upload |  
🔒 | openFileDialogOnClick | upload |  
⚠️ | grid | list | 其实对于 List 而言有点太重了

### 渲染

  | API | 相关组件 | 备注
-- | -- | -- | --
✅ | render | cascader, table, transfer |  
✅ | itemRender | breadcrumb, pagination |  
⚠️ | renderExtraFooter | date-picker | renderFooter is enough
🔒 | monthCellContentRender | date-picker |  
🔒 | displayRender | cascader |  
🔒 | dateCellRender | calendar |  
🔒 | dateFullCellRender | calendar |  
🔒 | monthCellRender | calendar |  
🔒 | monthFullCellRender | calendar |  
✅ | dropdownRender | select |  
🔒 | renderEmpty | config-provider | render + Component only used in ConfigProvider
🔒 | dateRender | date-picker |  
🔒 | expandedRowRender | table |  
🚫 | renderTabBar | tabs |  

### 事件/方法

  | API | 相关组件 | 备注
-- | -- | -- | --
✅ | onChange | affix, auto-complete, calendar, cascader, checkbox, collapse, date-picker, input-number, input, mention, pagination, radio, rate, select, slider, switch, table, tabs, tag, time-picker, transfer, tree-select, typography, upload |  
✅ | onSelect | auto-complete, calendar, mention, menu, select, table, tree-select, tree |  
✅ | onClick | anchor, back-top, button, dropdown, menu, notification, switch |  
✅ | getPopupContainer | cascader, config-provider, dropdown, select, time-picker, tooltip, tree-select |  
✅ | onSearch | auto-complete, input, select, transfer, tree-select |  
🚫 | getContainer | anchor, drawer, message, modal, notification | getPopupContainer
✅ | onClose | alert, drawer, message, notification, tag |  
✅ | onBlur | auto-complete, mention, rate, select |  
✅ | onFocus | auto-complete, mention, rate, select |  
✅ | afterClose | alert, modal, tag |  
✅ | onOpenChange | date-picker, menu, time-picker |  
✅ | loadData | cascader, tree-select, tree |  
🔒 | onOk | date-picker, modal |  
🚫 | onDropdownVisibleChange | auto-complete, select | onOpenChange
🚫 | onVisibleChange | dropdown, tooltip | onOpenChange
🔒 | disabledDate | calendar, date-picker |  
🔒 | formatter | input-number, statistic |  
🔒 | onPanelChange | calendar, date-picker |  
🔒 | onDeselect | menu, select |  
🔒 | onCancel | modal, popconfirm |  
✅ | onExpand | table, tree |  
🔒 | onCalendarChange | date-picker |  
🔒 | onTabChange | card |  
✅ | afterChange | carousel |  
✅ | beforeChange | carousel |  
✅ | onSubmit | form |  
🔒 | mapPropsToFields | form |  
🔒 | validateMessages | form |  
🔒 | onFieldsChange | form |  
✅ | onValuesChange | form |  
🔒 | getFieldDecorator | form |  
🔒 | getFieldError | form |  
🔒 | getFieldsError | form |  
🔒 | getFieldsValue | form |  
🔒 | getFieldValue | form |  
🔒 | isFieldsTouched | form |  
🔒 | isFieldTouched | form |  
🔒 | isFieldValidating | form |  
🔒 | resetFields | form |  
🔒 | setFields | form |  
🔒 | setFieldsValue | form |  
🔒 | validateFields | form |  
🔒 | validateFieldsAndScroll | form |  
🔒 | hasFeedback | form |  
🔒 | parser | input-number |  
🚫 | onPopupVisibleChange | cascader | onOpenChange
✅ | onPressEnter | input |  
✅ | onCollapse | layout |  
🔒 | onBreakpoint | layout |  
🚫 | getSuggestionContainer | mention | getPopupContainer
🚫 | onSearchChange | mention | onSearch
✅ | onError | avatar |  
🔒 | onTitleClick | menu |  
🔒 | onBack | page-header |  
🔒 | onShowSizeChange | pagination |  
🔒 | onConfirm | popconfirm |  
⚠️ | onHoverChange | rate | 不常用，不建议，不学习
✅ | onKeyDown | rate |  
⚠️ | onInputKeyDown | select | onKeyDown 现行的实现不太好，理论上应该都在 Input 框内，区别在于 showSearch 时 Input 是可见的。
✅ | onMouseEnter | select |  
✅ | onMouseLeave | select |  
✅ | onPopupScroll | select |  
🚫 | onAfterChange | slider | AfterChange
✅ | onFinish | statistic |  
✅ | onRemove | upload |  
🔒 | onExpandedRowsChange | table |  
🔒 | onHeaderRow | table |  
🔒 | onRow | table |  
🔒 | onCell | table |  
🔒 | onFilter | table |  
🔒 | onFilterDropdownVisibleChange | table |  
🔒 | onHeaderCell | table |  
✅ | onSelectAll | table |  
🔒 | onSelectInvert | table |  
✅ | onEdit | tabs |  
🔒 | onNextClick | tabs |  
🔒 | onPrevClick | tabs |  
🔒 | onTabClick | tabs |  
✅ | onScroll | transfer |  
🔒 | onSelectChange | transfer |  
🚫 | getCalendarContainer | date-picker | 用 getPopupContainer 代替
🔒 | onTreeExpand | tree-select |  
✅ | onCheck | tree |  
✅ | onDragEnd | tree |  
✅ | onDragEnter | tree |  
✅ | onDragLeave | tree |  
✅ | onDragOver | tree |  
✅ | onDragStart | tree |  
✅ | onDrop | tree |  
✅ | onLoad | tree |  
✅ | onRightClick | tree | 仅限于子节点右击，标准右击使用 onContextMenu
✅ | beforeUpload | upload |  
🔒 | customRequest | upload | 理论上仅限 Upload 组件
✅ | onPreview | upload | 未来例如 Image 也可以使用




### 实例方法


  | API | 相关组件 | 备注
-- | -- | -- | --
✅ | blur() | auto-complete, cascader, checkbox, date-picker, input-number, mention, radio, rate, select, slider, switch, time-picker, tree-select |  
✅ | focus() | auto-complete, cascader, checkbox, date-picker, input-number, mention, radio, rate, select, slider, switch, time-picker, tree-select |  
⚠️ | goTo(slideNumber, | carousel | 使用受控属性代替
⚠️ | next() | carousel | 使用受控属性代替
⚠️ | prev() | carousel | 使用受控属性代替
🚫 | getMentions | mention |  
🚫 | toContentState | mention |  
🚫 | toString | mention |

**Comment by afc163** [comment]
写到 https://ant.design/docs/react/contributing-cn 里去吧，README 里也链一份。

**Comment by zombieJ** [comment]
[Wiki 里](https://github.com/ant-design/ant-design/wiki/API-Naming-rules)加过，这边链到 wiki 里好了~
