### ISSUE TITLE
antd Select自动弹出方向

### ISSUE THREAD

**Issue by jieny** [ant-design/ant-design#16046]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
打开控制台，单击下拉框，滚动页面到底部，下拉框的空间不足不会向上弹出。（模态框设了最大高度，最后底部有个下拉框内容比较多，不会向上弹出的话就选不到较后面的选项）

### What is expected?
默认向下，空间不足向上，和原生下拉框效果一致。 element ui的效果可以自动判断弹出方向 https://elemefe.github.io/element-react/#/zh-CN/select 

### What is actually happening?
一直向下弹出，但在页面底部的组件会向上弹出，模态框里的不会向上弹出

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
这个是有的，后来优化成了滚动可视区域内不再自动改变方向，只有浏览器边缘才会改变。原因为了避免 #5130 的问题。

---

https://github.com/ant-design/ant-design/issues/8497#issuecomment-351702425
https://github.com/ant-design/ant-design/issues/12153#issuecomment-420874541

**Comment by HEternally** [comment]
如果选择器展示在固定底部的容器中，下拉框没有向上弹，导致数据无法全部看到
![image](https://user-images.githubusercontent.com/26925078/99059982-4bd0b780-25da-11eb-8fde-9d370a6f80c9.png)

**Comment by frei-x** [comment]
负优化...我就想溢出在可视区域外就自动修改方向
