### ISSUE TITLE
Drawer Component keeps hiding body overflow (disabled scrollbar) even if there are no masks.

### ISSUE THREAD

**Issue by erdemkeren** [ant-design/ant-design#16056]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/erdemkeren/pen/gyREGL](https://codepen.io/erdemkeren/pen/gyREGL)

### Steps to reproduce
Open drawer, (try to) scroll body.

### What is expected?
It is expected the body scroll to work. (Better if I can push scrollbar out of drawer area)

### What is actually happening?
The open event sets body style to "overflow: hidden;" disabling the scroller feature until the drawer is closed.

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | ^16.2.0 |
| System | macOS 10.14.4 |
| Browser | Version 73.0.3683.86 (Official Build) (64-bit) |

---
It really interrupts the user's flow with no real reason Adding a 2-step complexity with no real reason. See https://v0.material-ui.com/#/components/drawer Docked vs Undocked for example.

**Comment by IslamicProgrammer** [comment]
useLayoutEffect(() => {
    if (visible) window.scrollTo(0, 0)
  }, [visible])

It is working for me :)
