### ISSUE TITLE
Default theme override.

### ISSUE THREAD

**Issue by garyham** [ant-design/ant-design#16057]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allows the default theme to be optionally, and indirectly, overridden using modifyVars.  This is preferable to directly modifying the theme vars using modifyVars (as is currently recommended) which requires a rebuild to take effect.    This method has the advantage of supporting hot-reload any changes to the theme.   It is also backward compatible with existing code base.

### What does the proposed API look like?
Could you add the following line to the end of the current default.less theme in the /es and /lib directories.

@import (optional) '${@theme-override}'

Then in the modifyVars option can be set to 
```code
      modifyVars: {
        'theme-override': '../../../../../myproject/mytheme.less'
      }
```

**Comment by zombieJ** [comment]
http://ant.design/docs/react/customize-theme#Customize-in-less-file

**Comment by afc163** [comment]
```
      modifyVars: {
        'theme-override': 'themes/dark.less',
      }
```

It is more like specifying theme rather than less variables.

**Comment by zombieJ** [comment]
Seems no need to use `modifyVars`? Or `NormalModuleReplacementPlugin` instead?
http://ant.design/docs/react/customize-theme#Configure-webpack-to-load-an-alternate-less-file-and-scope-global-styles

**Comment by garyham** [comment]
Thanks for the fast response.

I did try the other methods but I couldn't get them to support Hot Module
Reload when I changed the theme variables.
With the other methods the Less loader does not directly load the theme and
therefore does not watch/reload it if it changes.

I'll continue using in my private build.

Thanks.

Gary

**Comment by garyham** [comment]
Hi,

I just noticed I made a mistake in the @import statement.  

I should read

```
@import (optional) '@{theme-override}';
```
