### ISSUE TITLE
tooltip can't be triggered when mouseenter an SFC component or component

### ISSUE THREAD

**Issue by doudounannan** [ant-design/ant-design#16054]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9zwrzzn3nw)

### Steps to reproduce
1. hover on "text" trigger tooltip

2. hover on "sfc component"  trigger tooltip

### What is expected?
hover on "sfc component" text trigger tooltip

### What is actually happening?
hover on "sfc component" text don't trigger tooltip

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.8.3 |
| System | osx 10.13.4 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/mm962yr3q8
