### ISSUE TITLE
Expose setActiveKey for Collapse

### ISSUE THREAD

**Issue by gotjoshua** [ant-design/ant-design#16055]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a series of nested Collapse elements which takes 3  seconds to render. I want to programmatically set the activeKey. If i use state props, there is a long delay while the whole nested series re-renders. I tried to save a ref to the Collapse element, but it does not help because, there is no function to set the active key (even though setActiveKey is present in the Collapse class in modules). 

This should be a very simple addition to the API surface as the underlying function is already there (and used on user click).

### What does the proposed API look like?
`CollapseRef.setActiveKey([stringKey]);`

Collapse already has and uses the method internally, I just want it exposed on the CollapseRef.

**Comment by yesmeck** [comment]
I don't think we will expose a API like this, it's an anti-pattern in React.

**Comment by gotjoshua** [comment]
I also asked a question on stackoverflow:
[Dynamically Open and Close Collapse](https://stackoverflow.com/questions/55649308/dynamically-open-and-close-antd-react-collapse-component)

Is there any workaround that you know of?

It feels like an operation that should be easy to do... to collapse  without re-render.

Thanks for your reply.

**Comment by afc163** [comment]
Control `activeKey` and use `onChange`. You should learn React before using antd.

**Comment by gotjoshua** [comment]
Although it is true that I am still learning react (only one year so far), I tried to describe that using props ("controlling activeKey")  triggers a re-render that is simply too slow.

I want to set activeKey without triggering a re-render.
Collapse works fine on mouse click if i am NOT controlling activeKey, but as soon as I try to control activeKey, the full tree of nested Collapse Components re-renders with a painful delay.

I understand that you don't want to expose the function, but if someone can offer a workaround  (here or on the stackoverflow) for this specific situation, it would be really helpful.

**Comment by gotjoshua** [comment]
@afc163, I know you are super busy, but I'd like you to understand the use case a bit better. 
Even if you stay with your decision...

If I control activeKey via state and props, then collapsing a single top level element, takes over 3 seconds to render. If I am not controlling activeKey, clicking to collapse an element is instant (no re-render).

I now did a terribly ugly workaround:
```js
document.querySelector(`#${collapseElementID} > .ant-collapse-header`).click();
```
I would much prefer to use:
```js
collapseReactRef.setActiveKey( correctPanelKey || [] );
```

For me, it would be great if you could simply acknowledge that 3 seconds to open or close a collapse element is far too long. If you have a less ugly workaround - or way to use state+props without rerendering, even better... If you could reconsider exposing setActiveKey, that would be amazing.

Thanks.

**Comment by TheMostCuriousThing** [comment]
Hello,

I am seeing the same issue with Tabs. Switching the active key via `activeKey` and `onChange` is unresponsive (on the order of ~3 seconds as @gotjoshua says). If this is indeed an anti-pattern, then what is the idiomatic implementation of responsive programmatic key-switching?
