### ISSUE TITLE
treeselect 当输入框已有选项时，鼠标点击输入框发生报错bug

### ISSUE THREAD

**Issue by weiQing88** [ant-design/ant-design#16052]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mjyvl2o329/)

### Steps to reproduce
当选择下拉框的某一项后，自动填充到输入框，这时鼠标点击输入框就会报错 。 PS：【 在 codesandbox 中没报错， 复制代码到本地项目查看报错 】

![image](https://user-images.githubusercontent.com/13113454/56024190-19960e80-5d42-11e9-9ff2-bb8ba2aa8c9e.png)

### What is expected?
如果输入框已有选项，在鼠标点击时不会报错。

### What is actually happening?
输入框已有选项，在鼠标点击会报错。

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | ^16.1.0 |
| System | window 10 |
| Browser | chrome 版本 72.0.3626.121 |

**Comment by zombieJ** [comment]
没有重现出你的错误……要不然给的 mini-repo 我看一下？

**Comment by lilonghe** [comment]
同款问题。  
antd 问题版本 3.15.0, 回滚至 3.13.5 或者更新至 3.17.0 均正常.  
新开项目(3.15.0)无法复现, 同一package.json开新项目同样无法复现.
然后，把 yarn.lock 拷过去就复现了... 
所以我的解决方法为：升级至 3.17.0 或者移除 yarn.lock 文件
