### ISSUE TITLE
table 有滚动条时翻页，不会回到顶部

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#16053]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-header](https://ant.design/components/table-cn/#components-table-demo-fixed-header)

### Steps to reproduce
滚动底部的数据列表到底部，点击第二页，发现第二页的数据列表还是在底部

### What is expected?
翻页到第二页的时候数据列表在顶部

### What is actually happening?
翻页到第二页的时候数据列表还是在底部

![image](https://raw.githubusercontent.com/mraiguo/image-respository/master/bug/table_20190412163645.gif)
| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
对，默认不支持回到顶部，你可以找到相应的 dom 然后手动设置一下哦~~

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3084

**Comment by yoyo837** [comment]
ref table 调用 `getPopupContainer`:

```ts
  getPopupContainer = () => {
    return ReactDOM.findDOMNode(this) as HTMLElement;
  };
```
