### ISSUE TITLE
Input 在没有与 form ,也可以有错误样式。。比如判断输入的不是整数，那么就让他出现错误的样式（边框红色），而且界面自动滚动到这个组件。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#16060]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Input 在没有与 form ,也可以有错误样式。。比如判断输入的不是整数，那么就让他出现错误的样式（边框红色），而且界面自动滚动到这个组件。

### What does the proposed API look like?
errorEnable

**Comment by afc163** [comment]
建议用 Form，Input 应该不会单独提供错误样式，否则其他表单组件也都需要，工作量太大。

**Comment by xgj1988** [comment]
@afc163  你说的这个我最开始就考虑的，但是我是在table 的column render 里面进行  用Input 来进行验证。 但是试了一下好像不行  错误之后没有错误样式，，但是控制台有 输出错误信息。。

**Comment by afc163** [comment]
@xgj1988 可以来个重现的例子看看

**Comment by xgj1988** [comment]
@afc163   这个重现很复杂，，我不知道怎么搞啊。。。我不可能把我的代码全部搬到codesandbox 上面撒。。能远程看看吗？

**Comment by dmdoit** [comment]
是不是我提到的这个问题， https://github.com/ant-design/ant-design/issues/25417
