### ISSUE TITLE
Form.Item labelAlign does not work

### ISSUE THREAD

**Issue by joshuaavalon** [ant-design/ant-design#16067]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k3y5254l73)

### Steps to reproduce
```jsx
<Form.Item label="label" labelAlign="right">
     item
</Form.Item>
```

### What is expected?
Label align to left

### What is actually happening?
Label still align to right.

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | Window 10 |
| Browser | Chrome |

---
The third item  is what to be expected with `text-align: left;`

Also, it works on `<Form>` but the type definition and documentation also said  it is available on  `<Form.Item>`.

**Comment by afc163** [comment]
<img width="726" alt="图片" src="https://user-images.githubusercontent.com/507615/56088974-b5985500-5ebd-11e9-8b71-5ec3eefe5dbe.png">

It works when you expand browser window width.

**Comment by joshuaavalon** [comment]
@afc163  Please read the comment or code.

> The third item is what to be expected with text-align: left;

```jsx
<Form.Item label="label" labelAlign="left">
  a
</Form.Item>
<Form.Item label="label" labelAlign="right">
  a
</Form.Item>
<Form.Item label="label" className="align-left">
  a
</Form.Item>
```

The last item is correct because a apply CSS manually on it.

**Comment by afc163** [comment]
https://codesandbox.io/s/k3y5254l73

`labelAlign` is prop of Form, not Form.Item's.

**Comment by joshuaavalon** [comment]
https://github.com/ant-design/ant-design/blob/2950219864a45b38a36a0e465ba47eb178638e60/components/form/FormItem.tsx#L17-L32

See Line 22

**Comment by afc163** [comment]
@yoyo837

**Comment by eggachecat** [comment]
> <img alt="图片" width="726" src="https://user-images.githubusercontent.com/507615/56088974-b5985500-5ebd-11e9-8b71-5ec3eefe5dbe.png">
> 
> It works when you expand browser window width.
> 
> Form has a default responsive behavior that it will turn into `vertical` layout in small device width.

And is there an easy way for users to disable/overwrite this responsive behavior?

**Comment by Seven4X** [comment]
https://codesandbox.io/s/danchucengzhongdexinjianbiaodan-ant-design-demo-forked-vshdt?file=/index.js
when Form in Model align not work .

**Comment by nichitapasecinic** [comment]
still not working !!!!

**Comment by yoyo837** [comment]
Feel free to open a new issue please.

**Comment by Makentosh** [comment]
still not working, from Form & Form.item too

**Comment by RezaGhx** [comment]
have you reached any solutions guys?

**Comment by huypham501** [comment]
still not working
