### ISSUE TITLE
typing every single letter in the Input will trigger an onValuesChange event,

### ISSUE THREAD

**Issue by mikeyzhe** [ant-design/ant-design#16062]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I found that typing every single letter in the Input will trigger an onValuesChange event, which is too frequent. is there any way to make it only trigger after enter key hit?
我发现打字的时候每个字都会单独触发一次onValuesChange, 有没有什么办法可以让他只在enter键以后触发呢？ （或者submit 触发）

### What does the proposed API look like?
tigger: 'onEnter'

**Comment by DiamondYuan** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> I found that typing every single letter in the Input will trigger an onValuesChange event, which is too frequent. is there any way to make it only trigger after enter key hit?
> 我发现打字的时候每个字都会单独触发一次onValuesChange, 有没有什么办法可以让他只在enter键以后触发呢？ （或者submit 触发）
> 
> ### What does the proposed API look like?
> tigger: 'onEnter'

you can use onSearch https://ant.design/components/input-cn/#components-input-demo-search-input

**Comment by DiamondYuan** [comment]
https://ant.design/components/input-cn/#Input

or onPressEnter

**Comment by mikeyzhe** [comment]
@DiamondYuan , thanks , when using `onPressEnter ` or `onSearch`.  the input does not accept any change at all.    (typing will not change the value of input)
```
  <Form.Item {...formItemLayout} label="搜索">
                      {getFieldDecorator('keyword', {
                        trigger: 'onSearch',
                      })(<Input.Search enterButton />)}
                    </Form.Item>
```
