### ISSUE TITLE
Cascader通过setState更改值之后输入框的值与浮层的选中项不匹配

### ISSUE THREAD

**Issue by guanyx** [ant-design/ant-design#1607]
[codePen在线示例](http://codepen.io/guanyx/pen/jqdZQy?editors=1010)

具体的步骤是这样的，第一次render的时候，设置一个defaultValue给定一个默认值
然后异步通过setState改变value的值

输入框中的值会跟setState设置的值同步
但是浮层的选中项还是defaultValue的默认值

**Comment by afc163** [comment]
感谢反馈，reinstall 。
