### ISSUE TITLE
checkbox组件使用在a标签中，点击checkbox勾选框在火狐浏览器会跳转，但是在chrome浏览器是正常的，不会跳转

### ISSUE THREAD

**Issue by HuYuee** [ant-design/ant-design#16073]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mzv3vrp1w8)

### Steps to reproduce
点击checkbox勾选框

### What is expected?
点击checkbox勾选框，不会出现跳转，仅仅只需要勾选checkbox即可

### What is actually happening?
点击checkbox勾选框，在火狐浏览器出现了跳转

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.4.2 |
| System | windows |
| Browser | 火狐 |

**Comment by zombieJ** [comment]
包在 a 里的目的是什么呢？

**Comment by HuYuee** [comment]
类似于这种情况
![image](https://user-images.githubusercontent.com/12147318/56105046-07e47f00-5f6d-11e9-9f65-8fbd9ed89f6c.png)

**Comment by HuYuee** [comment]
我后面找到了问题所在，span没有盖住input，因为input设置了z-index。我自己在span上面也设置了z-index:1。盖住了input之后，就解决了我的问题。
![image](https://user-images.githubusercontent.com/12147318/56105090-36faf080-5f6d-11e9-8de5-dfd0c1e53091.png)
![image](https://user-images.githubusercontent.com/12147318/56105103-45490c80-5f6d-11e9-9b9b-7aced3769cdf.png)

**Comment by zombieJ** [comment]
我更倾向没有跳转是 bug……

**Comment by zombieJ** [comment]
监听一下 CheckBox 的 onClick 调用 stopPropagation 吧~

**Comment by HuYuee** [comment]
但是，我监听了onclick事件，调用 stopPropagation 也没有效果

**Comment by zombieJ** [comment]
试了一下，使用原生的 `<input type="checkbox" />`，点击在 checkbox框 上两个游览器表现也是 firefox 跳转，chrome 不跳转的：https://codesandbox.io/s/6wv7rkmxzz
看来不是 antd 的 bug。

另外加 `preventDefault` 可以阻止跳转，但是 checkbox 也被阻止了：https://codesandbox.io/s/w03wxkmk87

分两层做吧：
```jsx
<div>
  <a />
  <CheckBox />
</div>
```
