### ISSUE TITLE
SkeletonAvatarProps.size should accept Enum | number, just like Avatar does

### ISSUE THREAD

**Issue by Stephen2** [ant-design/ant-design#16078]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Skeleton currently can't mimic Avatar when you set a custom size.  Allowing custom size would make this more perfect.

When the loading is finished, it always looks the most amazing when the Skeleton size was as close as possible to the real size.

### What does the proposed API look like?
`SkeletonAvatarProps.size = number | string: large small default`

**Comment by MrHeer** [comment]
I want to help, but I'm a beginner, I'm not sure I can complete it. First, I will compare Avatar and SkeletonAvatar

**Comment by Stephen2** [comment]
Thanks
