### ISSUE TITLE
npm instsll antd --save && Error: 404 Not Found: @ant-design/icons@~1.2.0

### ISSUE THREAD

**Issue by miaowwwww** [ant-design/ant-design#16076]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/README-zh_CN.md](https://github.com/ant-design/ant-design/blob/master/README-zh_CN.md)

### Steps to reproduce
随便哪个新项目，npm install antd --save 就可以了。

### What is expected?
安装成功

### What is actually happening?
然而失败
404 Not Found: @ant-design/icons-react@~1.1.5

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | react@16.8.6 |
| System | mac10.13.5 |
| Browser | google 71.0.3578.98 |

---
@ant-design/icons 这边少了很多版本。可是npm antd 的时候却是需要的。

**Comment by ycjcl868** [comment]
it's okay for me.

![image](https://user-images.githubusercontent.com/13595509/56106189-7d9f1980-5f72-11e9-80dd-9f54047e229a.png)

**Comment by miaowwwww** [comment]
@ycjcl868  it is a new project. no package-lock. maybe i  should check my network and npm config. thinks
