### ISSUE TITLE
可以用React的方法获取Table下tbody.ant-table-tbody的DOM不能

### ISSUE THREAD

**Issue by America-first-melon** [ant-design/ant-design#16089]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
获取DOM相关属性

### What does the proposed API look like?
ref ?

**Comment by America-first-melon** [comment]
`Table.ref={“test”}` 
 this.refs.test下找不到“bodyTable”这个ref啊。

**Comment by zombieJ** [comment]
ref 顶层，`querySelector` 找吧，如果开接口那要开的实在太多了。

**Comment by America-first-melon** [comment]
好的。 谢谢
