### ISSUE TITLE
Input组件在type="hidden" ,allowClear={true}的情况下,如果有默认值,会显示出清除图标

### ISSUE THREAD

**Issue by UnicornXU** [ant-design/ant-design#16087]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n7qxlxo814)

### Steps to reproduce
  业务场景:  会需要表单中传入Id,但内容隐藏不可见,提交时随其他内容一起提交。
  问题: 发现当Input有默认值时,会有清除图标出现,仔细看了源码是当value有值是清除图标出现

### What is expected?
  期望结果是将type='hideen' 条件,也加入判断是否显示清除图标当中

### What is actually happening?
  如果公共的封装Input组件,带allowClear属性,在type值为hidden情况下,显得不那么适用

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.4 |
| System | Win10 |
| Browser | 谷歌    版本 73.0.3683.86 |

**Comment by zombieJ** [comment]
有意思，的确不该显示清除。不过为什么要给 `type='hidden'` 添加 `allowClear` 呢？

**Comment by UnicornXU** [comment]
> 有意思，的确不该显示清除。不过为什么要给 `type='hidden'` 添加 `allowClear` 呢？

这里是矛盾了,如果去了allowClear就没这个问题

**Comment by afc163** [comment]
其实 SPA 中完全不需要 `<input type="hidden" />` 这种东西，额外数据直接跟随表单数据提交就行了。
