### ISSUE TITLE
PageHeader tags property throw errors in typescript

### ISSUE THREAD

**Issue by wenchao24** [ant-design/ant-design#16092]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)]( https://codesandbox.io/s/n332mk5m2p?fontsize=14)

### Steps to reproduce
run by typescript

### What is expected?
no error throws

### What is actually happening?
Though it works well on codesanbox, in my local project Typescript will throw an error when writing things like `<PageHeader title="title" tags={<Tag color="red">Failed</Tag>} />`

TS2322: Type 'Element' is not assignable to type 'Tag[]'.

you may try `<PageHeader title="title" tags={[<Tag color="red">Failed</Tag>]} />`, but just got another one: `Type 'Element[]' is not assignable to type 'Tag[]'.`

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.6.3 |
| System | win10 |
| Browser | Google Chrome 73.0.3683.103 (Official Build) (64-bit) |

---
Why d.ts for `PageHeaderProps` is `tags?: Tag[];` ?

can it be `tags?: React.ReactNode;` ?

that will solve my problem.

writing like `<PageHeader title="title" tags={[new Tag({color: "red", children: 'Failed'})]} />` can eliminate the type error, but it comes out a react-dom error:

Uncaught Error: Objects are not valid as a React child (found: object with keys {props, context, refs, updater, state, handleIconClick, renderTag}). If you meant to render a collection of children, use an array instead.

react-dom.development.js?f8c1:15749 The above error occurred in the <span> component:
    in span (created by Context.Consumer)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in PageHeader (created by LogView)

react-dom.development.js?f8c1:55 Uncaught Error: Objects are not valid as a React child (found: object with keys {props, context, refs, updater, state, handleIconClick, renderTag}). If you meant to render a collection of children, use an array instead.

So, I am wondering. What's the right way to use it? THX

**Comment by ztplz** [comment]
As your `codeandbox` demo doesn't reproduce the problem, can you build a mini repo?
