### ISSUE TITLE
最新版的antd使用typescript时编译会抱错: TS1005: ';' expected. 

### ISSUE THREAD

**Issue by ke-chenyan** [ant-design/ant-design#16098]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
最新版的antd使用typescript时编译会抱错: TS1005: ';' expected. 

### What is expected?
能够正常使用

### What is actually happening?
使用typescript时编译会抱错: TS1005: ';' expected. 

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by ztplz** [comment]
Any repo?

**Comment by isaak-zmg** [comment]
Same question

**Comment by ke-chenyan** [comment]
> Same question

 "moduleResolution": "node"
我改了这个配置之后可以了
