### ISSUE TITLE
Form.create() break defaultProps in typescript.

### ISSUE THREAD

**Issue by fwh1990** [ant-design/ant-design#16095]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
```typescript
interface OwnProps {
  aa: string;
}

type Props = OwnProps & FormComponentProps;

class HiMan extends React.Component<Props> {
  static defaultProps: Partial<Props> {
    aa: 'default value',
  }

  render() {
    return 'ok';
  }
}

export default Form.create()(HiMan);

```

### What is expected?
Call the component exclude default props
```typescript
render() {
  return <HiMan />;
}
```

### What is actually happening?
prop `aa` is required when calling.
```typescript
render() {
  return <HiMan aa="Required now..." />;
}
```
| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | macos 10.14 |
| Browser | chrome 74 |

---
You can look up how react-connect hold defaultProps.

**Comment by afc163** [comment]
https://ant.design/components/form/#Using-in-TypeScript

**Comment by fwh1990** [comment]
> https://ant.design/components/form/#Using-in-TypeScript
> 
> > **[Ant Design - A UI Design Language](https://ant.design/components/form/#Using-in-TypeScript)**An enterprise-class UI design language and React-based implementation with a set of high-quality React components, one of best React UI library for enterprises

I have change my code as:
```typescript
interface Props extends FormComponentProps {
  aa: string;
}

class HiMan extends React.Component<Props> {
  static defaultProps: Partial<Props> {
    aa: 'default value',
  }

  render() {
    return 'ok';
  }
}

export default Form.create<Props>()(HiMan);
```

And nothing changed.

So, you shouldn't close this issue.

**Comment by fwh1990** [comment]
Had you tried `defaultProps` ever?

**Comment by fwh1990** [comment]
And `connect` can keep `defaultProps` well.

```typescript
import { connect } from 'react-redux'; 

interface Props {
  aa: string;
}

class HiMan extends React.Component<Props> {
  static defaultProps: Partial<Props> {
    aa: 'default value',
  }

  render() {
    return 'ok';
  }
}

export default connect()(HiMan);
```

```typescript
render() {
  return <HiMan />;
}

```

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/56207221-cba24300-6080-11e9-85db-b69c143ee719.png)
Any repo ？

**Comment by fwh1990** [comment]
The problem of defaultProps is resolved, but something get wrong.
```typescript
# node_modules/antd/lib/form/interface.d.ts

export declare type FormWrappedProps<TOwnProps extends FormComponentProps> = <C extends React.ComponentType>(component: C) => ConnectedComponentClass<C, Omit<TOwnProps, keyof FormComponentProps>>;
```

I guess you have missed `TOwnProps`.

I mean, the keyword `<C extends React.ComponentType>` should be written as `<C extends React.ComponentType<TOwnProps>>`. Otherwise, something get wrong when I export component.

![image](https://user-images.githubusercontent.com/11069720/56567227-03603c00-65e7-11e9-855f-3cb52647da2f.png)

![DF0BFC19-3754-4469-9C56-33E6D3FE6C72](https://user-images.githubusercontent.com/11069720/56567146-e0358c80-65e6-11e9-976a-38a7df203895.png)


@zombieJ

**Comment by zombieJ** [comment]
Yes. Added in new patch: https://github.com/ant-design/ant-design/commit/da9cef91b88c34b91f28fd4cbdae98afcc67100a#diff-6674060020d469d3799f602cd77df0cdR26

**Comment by Polqk** [comment]
Casting Form.create with Component Props works form me
`
interface Props extends FormComponentProps {
}

class MyCompoenent extends React.Component<Props> {
...
}

export default Form.create<Props>()(MyCompoenent)
`

**Comment by papasavvasn** [comment]
The solution of Polqk (https://github.com/ant-design/ant-design/issues/16095) worked for me.
