### ISSUE TITLE
在某些情况下自定义按钮样式会失效

### ISSUE THREAD

**Issue by liresky** [ant-design/ant-design#16099]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/liresky/ant-issue.git](https://github.com/liresky/ant-issue.git)

### Steps to reproduce
点击登陆按钮即可

### What is expected?
蓝色

### What is actually happening?
颜色变为绿色，点击页面任意位置才会恢复为蓝色。

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | mac 10.14.4 |
| Browser | chrome/73.0.3683.103 |

**Comment by yesmeck** [comment]
Your repo is empty.

**Comment by afc163** [comment]
Your repo is empty.

**Comment by liresky** [comment]
@yesmeck 已经提交代码

**Comment by afc163** [comment]
<img width="298" alt="image" src="https://user-images.githubusercontent.com/507615/56480861-a5502d80-64ee-11e9-9957-f297412c9d86.png">

你是不是写错了？

**Comment by afc163** [comment]
https://github.com/liresky/ant-issue/blob/219eee930ec1ec5d648e703518dac496bef1c197/src/pages/Login/Login.module.less#L59

这里写死了颜色。
