### ISSUE TITLE
Safari 的兼容性审查

### ISSUE THREAD

**Issue by zhujun24** [ant-design/ant-design#161]
- [x] Menu 左侧 icon 偏移，次级菜单 hover 边角溢出 733307d3defd2eded19f0122b071ac40bb7b0d35
- [x] Collapse 折叠动画闪动
- [x] Upload 完全失效
- [x] ~~Modal 对话框右侧边框不对齐~~

**Comment by shepherdwind** [comment]
我晚点看下

**Comment by yiminghe** [comment]
@shepherdwind 用 rc-animate 搞下
