### ISSUE TITLE
Let notifications accept their full configuration as argument

### ISSUE THREAD

**Issue by Nouzbe** [ant-design/ant-design#16107]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`notification` can currently be configured in two ways:
1. by calling `config` to set some configuration for all upcoming calls.
2. by providing the config as argument while triggering the notification.

While `placement` and `duration` can be configured via both methods; `top`, `bottom` and `getContainer` can only be configured via 1. (See [ConfigProps](https://github.com/ant-design/ant-design/blob/master/components/notification/index.tsx#L16) and [ArgsProps](https://github.com/ant-design/ant-design/blob/master/components/notification/index.tsx#L110))
Being able to provide all config options with method 2 would be nice:
- More consistent.
- Method 2 is arguably better because it does not create internal state on the lib's side.

Happy to send a PR!

### What does the proposed API look like?
`top`, `bottom` and `getContainer` would also become part of `ArgsProps` and would be wired properly to the underlying `rc-notification`, if provided.

**Comment by zombieJ** [comment]
PR is welcomed : )
