### ISSUE TITLE
自定义组件验证问题。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#16108]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7164k2ykjx)

### Steps to reproduce
1：打开重现链接。
2：根据自定义组件不同的radio进行验证后，应该会对其后面的Input或者select 选择性报错。
3：会看到不论我选择的是哪个radio，他都是对整个组件报错，其实并不希望如此。。

### What is expected?
自定义组件应该可以选择性的报错。其实我这里有几个自定义组件都是这样，比如一个table里面，有多个 render 之后的Input 然后我这个table 是一个自定义组件。但是导致table里面输对的input 也报错了（其实没报错，只是边框样式变红）。。这样用户很纳闷。为什么我对的地方也会出现“错误”呢。

### What is actually happening?
应该在validator的callback 有个参数或者什么之类的，可以对自定义组件里面的组件单独报错。。

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.6.3 |
| System | windows10 专业版 |
| Browser | chrome 71.0.3578.98  |

**Comment by afc163** [comment]
一个组件只有一个报错信息，要分开只能分成两个表单控件来做。

**Comment by xgj1988** [comment]
@afc163  那这样我这种效果如何解决呢？？难道要form里面嵌套form 以下图片是基于zent （有赞的一个react组件写的）。他这种效果如何做呢？
[https://oss.xyzy.online/image/623fc2f8-1280-4077-9228-0de5ff149ebb.png](url)
[https://oss.xyzy.online/image/269576fd-8d07-4d48-bef4-266eb249f591.png](url)

**Comment by xgj1988** [comment]
@afc163 我估计他是写了一个自定义组件，所以我也写了个和他类似的，，但是不知道如何做到这种效果。

**Comment by afc163** [comment]
把 Input 和 Select 各自封装在 FormItem 和 getDecorator 里试试。

**Comment by afc163** [comment]
或者从 getFieldsError 里拿到校验信息，手动实现样式。

**Comment by xgj1988** [comment]
@afc163  兄弟，，我觉得你说的第一个让我试试我有点慌，，但是第二个也需要把所有的组件封装在不同的getFieldDecorator 才行吧。。。也就是我说的首先自定义组件实在一个 getFieldDecorator ，然后我又要把form ，，然后自定义组件里面再 用一个Form.create 来包装自定义组件，这样吗？？

**Comment by xgj1988** [comment]
@afc163  https://codesandbox.io/s/rr9p62yxxo 你看看我各自封装在FormItem和getFieldDecorator的结果。。不忍直视啊

**Comment by xgj1988** [comment]
@afc163 你说的第二种 getFieldsError 拿到之后设置样式 ，我如何设置样式呢？？ 里面获取的是一个json对象。然后json对象里面输数组。。每个包含报错的信息。，。和属性。。
