### ISSUE TITLE
[需求]upload组件允许设置最大上传数量

### ISSUE THREAD

**Issue by ottomao** [ant-design/ant-design#1610]
http://ant.design/components/upload/

如题，咱这个组件能不能增加一个参数，指定最大上传文件数量？

**Comment by afc163** [comment]
http://ant.design/components/upload/#demo-filelist

**Comment by ottomao** [comment]
感谢！

**Comment by ottomao** [comment]
现在这个交互感觉很坑爹啊，用户先传上去，再直接slice掉，还以为是系统故障....
能不能指定一个max值，达到上限时隐藏按钮

**Comment by afc163** [comment]
用 uploadList 的长度自行判断控制一下就好。

**Comment by ottomao** [comment]
问题是,upload组件没有参数可以隐藏这个“上传”按钮...
我的需求：保留已经上传的内容，隐藏“上传”按钮。

现在我的做法是自己判断数量，然后加个class，对上传按钮做display:none

**Comment by afc163** [comment]
隐藏这么基础的功能为啥要参数呢？用属性也要看基本法呢，不要没参数就干不了活呀...

```jsx
<Upload>
  {this.state.fileList.length > 0 ? <Button>上传</Button> : null}
</Upload>
```

**Comment by ottomao** [comment]
我的场景里是`listType="picture-card"`，隐藏children不顶用啊....

![](https://zos.alipayobjects.com/rmsportal/aQVOQsMOMThQhRS.png@300w)

**Comment by ottomao** [comment]
`listType="picture-card"` 这个场景的问题，确认一下呗?
如果确实有问题，咱排个期优化下？
@afc163

**Comment by afc163** [comment]
我看看。

**Comment by afc163** [comment]
现在，`<Upload></Upload>` 里面没东西的话，就不显示上传按钮，包括了 `listType="picture-card"` 这个场景。

**Comment by ottomao** [comment]
赞效率！！！

On Thu, May 12, 2016 at 5:04 PM, 偏右 <notifications@github.com> wrote:

> 现在，<Upload></Upload> 里面没东西的话，就不显示上传按钮，包括了 listType="picture-card" 这个场景。
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/1610#issuecomment-218700379>
>



-- 
Mao Xiaofeng(茅晓锋)
*Profession: *F2E
*Tel:*(86) 15801916167
*Email:*ottomao@gmail.com
*SinaWeibo:*@茅晓锋Otto <http://www.weibo.com/ottomao>
*Blog:*ottomao.com

**Comment by ottomao** [comment]
这个改动有预期发布时间么？如果赶得上我们项目，我就把自己的兼容代码删了....

**Comment by afc163** [comment]
在 1.0.x 上修复，可能未来几天上。

估计你还是 0.12.x 的，未来改版再删吧。。。

**Comment by ottomao** [comment]
我已经搞到1.0了，发布之后ping一下，我来升

On Thursday, 12 May 2016, 偏右 <notifications@github.com> wrote:

> 在 1.0.x 上修复，可能未来几天上。
>
> 估计你还是 0.12.x 的，未来改版再删吧。。。
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/1610#issuecomment-218715104>
>


-- 
Mao Xiaofeng(茅晓锋)
*Profession: *F2E
*Tel:*(86) 15801916167
*Email:*ottomao@gmail.com
*SinaWeibo:*@茅晓锋Otto <http://www.weibo.com/ottomao>
*Blog:*ottomao.com
