### ISSUE TITLE
FormItem的Feedback和Input的addonAfter样式互相覆盖。

### ISSUE THREAD

**Issue by TotooriaHyperion** [ant-design/ant-design#16101]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/wZPvdK](https://codepen.io/anon/pen/wZPvdK)

### Steps to reproduce
如链接所示。

### What is expected?
不覆盖

### What is actually happening?
覆盖

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.4 |
| System | Mac mojave |
| Browser | Chrome 73.0.3683.86 |

**Comment by afc163** [comment]
It is hard to resolve in current implementation.

**Comment by afc163** [comment]
Sorry, we aren't able to find a proper solution now, don't use `hasFeedback` with `Input[addon]`, or using custom css to override it.
