### ISSUE TITLE
RadioGroup组件的onchange方法未执行，执行两遍父级方法～！

### ISSUE THREAD

**Issue by zhilianbi520** [ant-design/ant-design#16104]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pmmr0ljr9x)

### Steps to reproduce
RadioGroup 父级有方法，触发RadioGroup的 onChange事件会先触发父级的方法。

### What is expected?
求解。。

### What is actually happening?
求解。。

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.5.1 |
| System | macOS 10.14.4 |
| Browser | chrome 73.0.3683.103 |

**Comment by zombieJ** [comment]
这是游览器默认行为，点击 label 时，它会触发一次 label 的 onClick 再触发一次 input 的 onClick：https://codesandbox.io/s/v8zyymqr97

<blockquote><img src="https://codesandbox.io/api/v1/sandboxes/v8zyymqr97/screenshot.png" width="48" align="right"><div>CodeSandbox</div><div><strong><a href="https://codesandbox.io/s/v8zyymqr97">v8zyymqr97 - CodeSandbox</a></strong></div><div>The online code editor tailored for web applications</div></blockquote>
