### ISSUE TITLE
can the Form execute different validator by different trigger?

### ISSUE THREAD

**Issue by panjiefeng** [ant-design/ant-design#16105]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
eg:
There is an input-component, which need to validate the format and calculate the value. such as ID Card No input-component.
I want to validate the format while inputting and to calculate the value while being finished.
I wish when the inputting doesn't finish, it can't return an error. Because if return an error, it isn't friendly. But when the on-blur happened, it can return an error "Please input the correct format!"

codepen: https://codepen.io/panjunfen/pen/VNrLpr?editors=0010

### What does the proposed API look like?
in the rule object, add a key "trigger". 
such as,
[{
    pattern: /^([A-Z]{0,2}|[A-Z]{1,2}\d{0,6}|[A-Z]{1,2}\d{6}\([0-9A]{0,1}\){0,1})$/,
    trigger: 'onChange',
},{
    validator: (rule, value, callback)=>{
                console.log(`validator value:${value} rule:`,rule);
                if(!value || value.search(/^[A-Z]{1,2}\d{6}\([0-9A]\)$/) == -1){
                    callback();
                    return ;
                }
                if(validHKID(value)){
                    callback();
                } else {
                    callback("The ID is incorrect!");
                }
            },
    trigger: 'onChange'
},{
    pattern: /^[A-Z]{1,2}\d{6}\([0-9A]\)$/,
    trigger: 'onBlur'
}]

**Comment by zombieJ** [comment]
You can calculate the value after format pass:  https://codesandbox.io/s/ryrjzvpo0q

**Comment by panjiefeng** [comment]
The example you give to me is the same as what I provide. In your example, the correct format is "0000-0000", and the correct value is "1234-1234". but when I input 1234, the error is still showing. I think that is wired. so I want to achieve this effect。
1. when I am still inputting, the "1234" is the correct format and the error shouldn't be shown. Because the "0000-0000" contains it.
2. when I lose focus, another validator should be called and the error should be shown. Because the "1234" doesn't match the "0000-0000".
am I express clearly? if you think it is not necessary, please let me know your opinion.

**Comment by zombieJ** [comment]
Hmmm... I know what you mean. Currently provides the demo is that as workaround. Since internal logic only support one trigger. I will record this, but may not happen quickly.

**Comment by panjiefeng** [comment]
ok，thx.

**Comment by zombieJ** [comment]
Before it resolve. Let's keep this open ~

**Comment by mjfwebb** [comment]
@zombieJ Just to double-check: I want to make it so that errors aren't shown until something is actually wrong as it is quite unfriendly to see an error as soon as I enter a single character in the email validation example (https://codesandbox.io/s/0p4jn). Is this issue for exactly that problem?

**Comment by zombieJ** [comment]
https://codesandbox.io/s/jibenshiyong-antd4150-forked-k7rfu?file=/index.js


antd v4 enabled rules with different `triggerValidator`. Seems this issue can be closed now.
