### ISSUE TITLE
[Drawer] In the case of scroll bars, the top of the Title is not fixed and should be fixed by default

### ISSUE THREAD

**Issue by DreamPWJ** [ant-design/ant-design#16113]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/ng-zorro-antd-start-lijtrs](https://stackblitz.com/edit/ng-zorro-antd-start-lijtrs)

### Steps to reproduce
1. For array loop 2. Scroll down 3. View Title position

### What is expected?
The top of the Title should be fixed by default

### What does the proposed API look like?
The top of the Title is not fixed to follow the page scroll

**Comment by afc163** [comment]
You should create issue in https://github.com/NG-ZORRO/ng-zorro-antd

**Comment by DreamPWJ** [comment]
This is a style problem that should be an ant-design less code problem

**Comment by DreamPWJ** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/3274#issue-433527095

**Comment by DreamPWJ** [comment]
@afc163

**Comment by afc163** [comment]
You can try this way: https://codesandbox.io/s/z3wvjx65v3
