### ISSUE TITLE
请问如何在ant-design react中使用es7的async和await的

### ISSUE THREAD

**Issue by gakaki** [ant-design/ant-design#1611]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。

 try {
   9 |   let url      = "http://127.0.0.1:8360/adminapi/order/list";
> 10 |   let response = await fetch(url);
          |                        ^
  11 |   let data = response.json();
  12 |   console.log(data);
  13 | } catch(e) {

如此这般webpack便会报错

**Comment by afc163** [comment]
https://github.com/ant-tool/atool-build/issues/153
