### ISSUE TITLE
form menu  createFormField > select  defaultValue >   Error: must set key for <rc-animate> children 

### ISSUE THREAD

**Issue by 1121512088** [ant-design/ant-design#16112]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.google.com.hk/](https://www.google.com.hk/)

### Steps to reproduce
available

### What is expected?
How to do it right

### What is actually happening?
fix

| Environment | Info |
|---|---|
| antd | 3.0.0 |
| React | 16.4.2 |
| System | windows |
| Browser | Google |

---
This problem appears when using Google version 73.0.3683.86.【Error: must set key for <rc-animate> children 】---- there is no problem when using Google test version 65.0.3325.181. Do you need to upgrade the ant version?

**Comment by afc163** [comment]
Please try to upgrade antd to latest version.

**Comment by zombieJ** [comment]
Close since version too old. Please feel free to provide reproduce if still face this issue.
