### ISSUE TITLE
Affix 容器滚动，会跑出容器外

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#16120]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/affix-cn/#components-affix-demo-target](https://ant.design/components/affix-cn/#components-affix-demo-target)

### Steps to reproduce
先在容器里面滚动，然后滚动外面的滚动条，容器里面Affix就跑出容器了，我不知道这个算不算 BUG。

### What is expected?
容器里面Affix不应该跑出容器。

### What is actually happening?
容器里面Affix跑出容器了。

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | windows10 |
| Browser | chrome73 |

**Comment by XianZhengquan** [comment]
感觉就像是，指定了target，但是 在指定的target，也就是其父元素下滚动时，target变成了默认的window

**Comment by zombieJ** [comment]
是个 BUG，容器固定后是 fixed 布局，外部滚动的时候内部没有 scroll 所以就出去了。目前没有监听全局滚动是因为性能消耗比较大。

**Comment by XianZhengquan** [comment]
其实，昨年就发现了，还以为你们是这种设计模式呢

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/3938
https://github.com/ant-design/ant-design/issues/5642
https://github.com/vueComponent/ant-design-vue/issues/1

**Comment by XianZhengquan** [comment]
看了这3个issues，感觉你们不会修复了😂，你们会修复不？

**Comment by zombieJ** [comment]
@afc163 加一个 force 属性强制监听全局滚动如何？

**Comment by zys555** [comment]
在使用左侧为菜单栏右侧是内容区的布局后，Affix失效了。。

**Comment by suwanuo** [comment]
看来是不打算修复了🙃

**Comment by zylx** [comment]
使用左侧为菜单栏右侧是内容区的布局后，Affix失效，其实重新指定target父容器就行了。

**Comment by wzp-coding** [comment]
给子元素直接设置position:sticky;也许能解决你的问题
sticky
元素根据正常文档流进行定位，然后相对它的最近滚动祖先（nearest scrolling ancestor）和 containing block (最近块级祖先 nearest block-level ancestor)，包括table-related元素，基于top, right, bottom, 和 left的值进行偏移。偏移值不会影响任何其他元素的位置。
该值总是创建一个新的层叠上下文（stacking context）。**注意，一个sticky元素会“固定”在离它最近的一个拥有“滚动机制”的祖先上**（当该祖先的overflow 是 hidden, scroll, auto, 或 overlay时），即便这个祖先不是最近的真实可滚动祖先。这有效地抑制了任何“sticky”行为（详情见[Github issue on W3C CSSWG](https://github.com/w3c/csswg-drafts/issues/865)）。
[更多信息请前往MDN官网查看----position](https://developer.mozilla.org/zh-CN/docs/Web/CSS/position)

**Comment by Sdh-ui** [comment]
我是浏览器打开f12控制台的时候，这个affix包裹的容器会错位，我是选择监听window缩放给这个affix加个key重新渲染，就解决了，同样像其他情况就监听类似的事件
![image](https://github.com/ant-design/ant-design/assets/55343425/36149673-0b94-428a-bcdf-1ff098f91baa)
![image](https://github.com/ant-design/ant-design/assets/55343425/2e82ca70-bf50-4a42-a5d1-f46ea3dc36ea)
