### ISSUE TITLE
InputNumber 输入框的问题

### ISSUE THREAD

**Issue by HaveDreamMan** [ant-design/ant-design#1612]
![default](https://cloud.githubusercontent.com/assets/8551569/15109693/43db5b5a-160f-11e6-8123-5abcb3d83ce7.png)
当数值特别大时，输入框有点小啊。有什么解决方法吗？

**Comment by afc163** [comment]
`style={{ width: '100%' }}`

**Comment by HaveDreamMan** [comment]
好谢谢。
