### ISSUE TITLE
AutoComplete -  Lookup Patterns: Uncertain Category Demo BUG

### ISSUE THREAD

**Issue by wangdaners** [ant-design/ant-design#16122]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/auto-complete/](https://ant.design/components/auto-complete/)

### Steps to reproduce
Please see the demo of uncertain category in the link.
When I type too long characters, the front field will be obscured by the back field.
I think this is a bug.

### What is expected?
I hope it will be displayed properly.
The display can be omitted or the width can be automatically extended.

### What is actually happening?
The front field will be obscured by the back field.

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | react |
| System | macOS Mojave 10.14.4 |
| Browser | Chrome 73.0.3683.75 |

**Comment by ztplz** [comment]
I don't think this is a bug. @afc163

**Comment by zombieJ** [comment]
Hi @wangdaners ,
It's a demo of `dataSource` usage. Not fully consider the context length.
Maybe we can update the demo.
