### ISSUE TITLE
固定列的宽度没有固定

### ISSUE THREAD

**Issue by Long-Dress** [ant-design/ant-design#16124]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我所有列是固定宽度的，超出部分使用...展示，列可伸缩，table的最小宽度是100%。
我需要固定部分列，可是固定列的宽度被内容撑开了，导致滑动列有被覆盖的情况。

### What does the proposed API look like?
我希望以上情况下，固定列的宽度可以有参数固定。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
