### ISSUE TITLE
使用antd报错没有安装buffer，请问这个怎么装？

### ISSUE THREAD

**Issue by hellnaren** [ant-design/ant-design#1613]
[WARNI] Can't resolve `buffer` in file [/node_modules/antd/node_modules/rc-form
/node_modules/async-validator/node_modules/lodash.mergewith/node_modules/lodash.
_baseclone/index.js], did you miss `npm install buffer`?

**Comment by afc163** [comment]
一般来说，大多数情况是没装好，尝试重装。

**Comment by hellnaren** [comment]
重装了还是报错，请问跟node和npm版本有关系么？谢谢

**Comment by benjycui** [comment]
Try [cnpm](https://npm.taobao.org/)

**Comment by afc163** [comment]
建议 npm@3 版本，cnpm 是一个好选择。
