### ISSUE TITLE
Misleading/Wrong warning when using Nested Table with Fixed Header.

### ISSUE THREAD

**Issue by Selfron** [ant-design/ant-design#16135]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mz3l0p9pop)

### Steps to reproduce
Add a Nested Table (`expandedRowRender`) and **Fixed Header** (`scroll`) to the Table and then expand one of the Rows.

### What is expected?
No warning since everything is working as expected.

### What is actually happening?
Warning: [antd: Table] `expandedRowRender` and `scroll` are not compatible. Please use one of them at one time.

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Google Chrome 73.0.3683.103 |

---
Multiple issues reported a problem when using `expandedRowRender` with **Fixed Columns**.
- [Issue 7715](https://github.com/ant-design/ant-design/issues/7715)
- [Issue 9900](https://github.com/ant-design/ant-design/issues/9900)

To fix the issue @zombieJ made [Pull request 14193](https://github.com/ant-design/ant-design/pull/14193).  
Now you also get's a warning when using `expandedRowRender` with a **Fixed Header**.

Could the warning only be displayed if the user is actually using **Fixed Columns** instead (i.e. `fixed` as `ColumnProps` in one of the columns in combination with `expandedRowRender`)?

This way it would warn about the actual problem, which it isn't right now as you can see [here](https://codesandbox.io/s/wopoq9260l) where a **Fixed Column** is used with `expandedRowRender` but without `scroll`.

**Comment by zombieJ** [comment]
Hmmm. We should only warning if use `scrollX` & `expandedRowRender`.
