### ISSUE TITLE
form表单提交，校验内容不通过控制台会报警告

### ISSUE THREAD

**Issue by hongqiang12** [ant-design/ant-design#16132]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n9z2m9j3jp)

### Steps to reproduce
该官方案例也是如此，直接点击提交按钮

### What is expected?
希望界面有校验效果，但是控制台不要有警告

### What is actually happening?
控制台会报校验失败警告

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome72.0 |

**Comment by afc163** [comment]
#15588

https://github.com/react-component/form/commit/c573566c0d6e32cc3c14a18842e05a061e8a529d

只有开发环境会出现，生产环境不会。
