### ISSUE TITLE
No background of active item in pagination

### ISSUE THREAD

**Issue by orzechdev** [ant-design/ant-design#16139]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/orzechdev/pen/ZZrOxB](https://codepen.io/orzechdev/pen/ZZrOxB)

### Steps to reproduce
Set background on component in which pagination is placed

### What is expected?
Background of active item in pagination should be like other items

### What is actually happening?
Background of active item in pagination is transparent, not like other items

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.2 |
| System | Ubuntu 18.04.2 |
| Browser | Opera 58.0.3135.65 |

**Comment by MrHeer** [comment]
### I have found the reason for this phenomenon. How to deal with it, need official confirmation
![20190418093148](https://user-images.githubusercontent.com/18595761/56330966-ff828300-61bc-11e9-9013-4bc4d3a6f205.png)

![20190418093226](https://user-images.githubusercontent.com/18595761/56330967-001b1980-61bd-11e9-851e-fbb6b13ce84c.png)

### Below is the source code
![20190418094349](https://user-images.githubusercontent.com/18595761/56331379-8be17580-61be-11e9-96e2-b01d15a9395a.png)

**Comment by zombieJ** [comment]
@afc163 , Seems this should be `@component-background;`: https://github.com/ant-design/ant-design/commit/56570aa539cd5e6739524c114e837c6f1181d2ba
