### ISSUE TITLE
table加上排序后会 遮挡下边框 怎么处理 Firefox和edge浏览器

### ISSUE THREAD

**Issue by djl0415** [ant-design/ant-design#16131]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-ajax](https://ant.design/components/table-cn/#components-table-demo-ajax)

### Steps to reproduce
https://ant.design/components/table-cn/#components-table-demo-ajax

### What is expected?
修复

### What is actually happening?
修复

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 最新 |
| System | win10 |
| Browser | 66.0.3 |

**Comment by djl0415** [comment]
![Uploading image.png…]()

**Comment by djl0415** [comment]
![image](https://user-images.githubusercontent.com/49421184/56259194-c2f35080-6104-11e9-90cd-b18bcb0e344b.png)

**Comment by djl0415** [comment]
请问有解决办法吗

**Comment by zombieJ** [comment]
有点难搞：#14926
