### ISSUE TITLE
The package with prefix @types/ has wrong place.

### ISSUE THREAD

**Issue by fwh1990** [ant-design/ant-design#16149]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
yarn add --dev || npm install --save-dev

### What is expected?
The package with prefix `@types/` should be in devDependencies

### What is actually happening?
They are in dependencies.
```
@types/hoist-non-react-statics
@types/react-slick
```

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | all |
| System | all |
| Browser | all |

**Comment by zombieJ** [comment]
It's not bug. antd use / extend these deps.

ref: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-redux/package.json#L4
