### ISSUE TITLE
Setting 'scroll' attribute for table causes header to be misaligned

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#16147]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.screencast.com/t/lanmn0BuGQBM](https://www.screencast.com/t/lanmn0BuGQBM)

### Steps to reproduce
Create table with and without scroll attribute.

Screenshot:
https://www.screencast.com/t/lanmn0BuGQBM

1. Table on left has no scroll attribute, header is properly aligned with content
2. Table on right has scroll.y attribute, header is not aligned with content

### What is expected?
Setting scroll.y shouldn't affect alignment of header with content

### What is actually happening?
Setting scroll.y misaligns header with content

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 73 |

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-fixed-header

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/507615/56334123-ad942a00-61c9-11e9-983d-35fe6583e249.png">
