### ISSUE TITLE
Table not renew state when running this.setState

### ISSUE THREAD

**Issue by weidongdiao** [ant-design/ant-design#16152]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
```
render () {
  const columns=[{
  ...
},{
	title: '操作',
	dataIndex: 'opt',
	key: 'opt',
	render: (text, row, index) => {
	return <a onClick={() => {
		this.state.data[index].isHot = !this.state.data[index].isHot;
		this.setState({data});
	}}>
		{this.state.data[index].isHot ? '热门推荐' : '取消热门推荐'}
	    </a>;
	}
}];

return (
  <Table 
    dataSource={this.state.data}
    columns= columns
  />)
}

```

### What is expected?
After this.setState({data), it can renew the state.data, and the value of ```this.state.data[index].isHot``` will change

### What is actually happening?
When I use React Developer Tools in Chrome to inspect, this.state.data doesn't change and Table data does not change either. But when I did some operations like console.log(this.state.data), it shows the latest data.

After I try to use such way
```
...
render: (text, row, index) => {
	return <a onClick={() => {
		this.state.data[index].isHot = !this.state.data[index].isHot;
		this.setState({data,  [`title${index}`]: row.isHot ? '热门推荐' : '取消热门推荐'});
	}}>
		{this.state.data[index].isHot ? '热门推荐' : '取消热门推荐'}
</a>;
}
```

this.state.data can be changed and Table can be re-render.

I guess it is because the change of Object will not make re-render state happen, and it need to set additional components which difference from preState after running this.setState.

So why I cannot only running ```this.setState({data});``` to re-render Table.

Any better idea? Thanks~

| Environment | Info |
|---|---|
| antd | 3.8.4 |
| React | "16.2.0 |
| System | MAC |
| Browser | Chrome |

**Comment by afc163** [comment]
```diff
- this.state.data = ....
- this.setState({ data });
+ const newData = [...this.state.data]; // don't modify original state, clone one
+ newData[xx] = ...
+ this.setState({ data: newData });
```

**Comment by weidongdiao** [comment]
It works, thanks~~
