### ISSUE TITLE
有没有办法知道当前组件的form的resetFields方法执行了。

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#16153]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我希望通过 props.form 的一个字段知道我执行了 resetFields 方法，我好做其它的逻辑处理。

### What does the proposed API look like?
希望能知道调用过 resetFields 方法。

**Comment by afc163** [comment]
Please describe your situation, don't simply ask for solution.

**Comment by qq645381995** [comment]
我只是想要知道是否调用了 resetFields 方法，然后我好做业务的其它逻辑。

**Comment by afc163** [comment]
resetFields 是你自己调用的，你可以在你调用的地方执行任何其他逻辑。

**Comment by afc163** [comment]
https://coolshell.cn/articles/10804.html

<img width="471" alt="image" src="https://user-images.githubusercontent.com/507615/56334427-c94c0000-61ca-11e9-90fb-bd09ff76fd39.png">

**Comment by qq645381995** [comment]
https://codesandbox.io/s/0ov7l5nv8n?fontsize=14

这个是有2条初始化数据，点击添加一条，然后再点击重置，恢复成2条初始化时候的数据。
我现在是用 `isReset` 来判断表单点击了 `resetFields ` 然后重置数组的

**Comment by afc163** [comment]
`isFieldsTouched`

https://ant.design/components/form/#Form.create(options)

**Comment by qq645381995** [comment]
这个 api 是做什么的，看不懂呢？

**Comment by qq645381995** [comment]
`isFieldsTouched(['names[0].name'])` 要这个样子吗，那 additem 里面所有的字段全部都要拿出来判断。

**Comment by afc163** [comment]
`isFieldsTouched();`

**Comment by qq645381995** [comment]
这个其实不太理想，因为点击天机一条数据，不输入值，`isFieldsTouched()` 还是 false
