### ISSUE TITLE
treeSelect性能问题

### ISSUE THREAD

**Issue by BG5FD** [ant-design/ant-design#16151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在可勾选treeSelect组件中，当渲染的数据过大，达到几百个节点的时候，勾选复选框时会有明显的卡顿，排查过程中共发现了以下原因：
一、动画延迟，在rc-tree-select组件中，每个节点勾选的动画效果会造成300ms左右的延迟，这个是造成卡顿的最主要原因，在antd的源码中看到transitionName和choiceTransitionName是默认属性值，建议官方api将这两个属性开放，由使用者设定；
二、treeDefaultExpandedKeys导致卡顿。我在使用treeDefaultExpandKeys和不使用两种情况下，渲染效率明显不同。
其实我在去除了动画效果和treeDefaultExpandKeys后，在控制台中依然看到warning：[Violation] 'click' handler took <N>ms；Forced reflow while executing JavaScript took <N>ms。但是这两个耗时我尚未找到原因emmmmmmmmmmmmmm。

### What does the proposed API look like?
开放treeSelect的transitionName和choiceTransitionName属性

**Comment by zombieJ** [comment]
Duplicate of #16151

**Comment by qq645381995** [comment]
> Duplicate of #16151

你这回复错了吧？

**Comment by zombieJ** [comment]
> > Duplicate of #16151
> 
> �你这回复错了吧？

失误……

ref: #3789
