### ISSUE TITLE
Drawer getContainer设置为htmlElement导致前几次无法打开

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#16157]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/213mx04j1r)

### Steps to reproduce
点击open drawer，前几次Drawer没显示，多点几次会显示，如果把getContainer改成function就没有这个问题了

### What is expected?
getContainer传htmlElement也可以正常触发Drawer的显隐

### What is actually happening?
getContainer传htmlElement未正常触发Drawer的显隐

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Your codesandbox is empty.

**Comment by gonenoob** [comment]
https://codesandbox.io/s/213mx04j1r

**Comment by gonenoob** [comment]
猜测是因为第一次传了个null给getContainer导致的

**Comment by zombieJ** [comment]
@jljsj33 Please help to check.

**Comment by ztplz** [comment]
A hack way. https://codesandbox.io/s/xlrr7552mw

**Comment by jljsj33** [comment]
createRef 是在全部渲染完成后也会附值，不支持。。而且我API里写着也没有这样使用的。。
![image](https://user-images.githubusercontent.com/6802825/56403460-06c89000-6294-11e9-829c-64b948d90af4.png)

如果非要用 ReactNode， 请再套一层 func,,,,() => (this.drawerBoxRef.current);
![image](https://user-images.githubusercontent.com/6802825/56403511-3f686980-6294-11e9-857c-bd73929861d4.png)

**Comment by zombieJ** [comment]
@jljsj33 ，用户点击打开 Drawer 的时候，ref 已经有值了：https://codesandbox.io/s/lxl7y4nlol
