### ISSUE TITLE
chrome OTS parsing error: invalid version tag

### ISSUE THREAD

**Issue by nie-xin** [ant-design/ant-design#1615]
试着整合antd和 [react-redux-starter-kit](https://github.com/davezuko/react-redux-starter-kit)。在加载antd组件时出现warning：chrome OTS parsing error: invalid version tag，并且icon无法显示：

![capture d ecran 2016-05-09 a 18 21 18](https://cloud.githubusercontent.com/assets/3535692/15119826/0b6b1964-1613-11e6-8dd6-45637883c08b.png)

![capture d ecran 2016-05-09 a 18 23 20](https://cloud.githubusercontent.com/assets/3535692/15119855/2db23624-1613-11e6-9133-658bca7fa104.png)

在Firefox下无错误提示，但icon无法顺利解析：

<img width="306" alt="capture d ecran 2016-05-09 a 18 24 18" src="https://cloud.githubusercontent.com/assets/3535692/15119873/444bd098-1613-11e6-9670-f8c72be7f9b7.png">

最奇怪的是safari下一切正常：

<img width="317" alt="capture d ecran 2016-05-09 a 18 24 48" src="https://cloud.githubusercontent.com/assets/3535692/15119889/55ddd4f0-1613-11e6-9d2c-5305fecbe519.png">

demo地址：https://github.com/nie-xin/react-redux-starter-kit

**Comment by RaoHai** [comment]
这个 demo 里的 css， 在加载到页面里的时候，变成了类似于 `blob:http%3A//127.0.0.1%3A3000/93feaef9-75c3-4767-be89-fdb4300dc0d4` 这样的链接。。

里边 antd 的 iconfont，是这样写的： `//at.alicdn.com/t/font_1461567603_8950496.eot` 。。

应该是这样的写法跟 blob url 不兼容吧。。

**Comment by nie-xin** [comment]
找到一个类似问题：http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts

我试一下看看。

**Comment by nie-xin** [comment]
找到问题了，应该是webpack的某个loader没有正确处理index.css中font-face的url，加上明确的http后可以正确读取了。比较有趣的是三个浏览器在这种情况下的处理不一致。

稍后尝试加载local font取代hosted font。希望antd能提供sass版本，方便sass用户定制style。

**Comment by afc163** [comment]
直接设为 https 版本粗暴解决。
