### ISSUE TITLE
[Feature Request] 从浮层内关闭 Popover 非常不方便

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#16158]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
官方示例：https://ant.design/components/popover-cn/#components-popover-demo-control
应用场景：点击 Popover 浮层里的 “关闭” 触发 Popover关闭；但当 Popover 很多，且通过 map 等方式批量生成时，需要额外写很多代码

实现示例: https://codesandbox.io/s/1qwz4rw2mj

要点：

```jsx
const popTest = [1, 2, 3 /* ,4,5 unknow length */];

// 隐藏/显示状态
state = {
    visible: Array.from(popTest, () => false)
  };

// 点击隐藏
hide = i => {
    this.state.visible[i] = false;
    this.setState(this.state.visible.slice(0));
  };

handleVisibleChange = (i, visible) => {
    this.state.visible[i] = true;
    this.setState(this.state.visible.slice(0));
  };

<Popover
        content={<a onClick={this.hide.bind(this, i)}>Close</a>}
        trigger="click"
        visible={this.state.visible[i]}
        onVisibleChange={this.handleVisibleChange.bind(this, i)}
      />
```

### What does the proposed API look like?
期待实现：

```jsx
<Popover
        content={(popover) => <a onClick={popover.close()}>Close</a>}
        trigger="click"
        visible={this.state.visible[i]}
        onVisibleChange={this.handleVisibleChange.bind(this, i)}
      />
```

*或其他方便的实现方式*

**Comment by afc163** [comment]
你实现的方式没问题，三个卡片确实需要三个独立的状态进行控制，组件层面不适合去做过度封装。你可以在业务封装统一的逻辑，例如 usePopover 类似的 Hooks 来用。
