### ISSUE TITLE
`rowSelection.columnWidth` is not respected

### ISSUE THREAD

**Issue by hon2a** [ant-design/ant-design#16163]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/r0vpl302yp)

### Steps to reproduce
Create a table that has a row selection column with custom width (<Table rowSelection={{ columnWidth: 40, ... }} ... />).

### What is expected?
The width of the row selection column should be `40px`, as specified by `rowSelection.columnWidth`.

### What is actually happening?
The width of the column is the default `60px`, not the specified custom width.

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.9.0 |
| System | MacOS 10.14.4 (18E226) |
| Browser | Chrome 73.0.3683.103 (Official Build) (64-bit) |

---
Please note that `rowSelection.columnWidth` should be applied even when the row selection column is fixed.

**Comment by zombieJ** [comment]
@afc163 Seems this change breaks the `columnWidth`: https://github.com/ant-design/ant-design/commit/d922c377cba03bef39ddb7d271fce3f67c353be9#diff-e2a536684ed8b2684e0ae68f0ef1ffe9R319

**Comment by hon2a** [comment]
I've also looked at the changelog and expected this to be the case, but I don't see how that patch could possibly do it.

**Comment by zombieJ** [comment]
@hon2a , for current path you can use css to set the column width. Let me handle it in antd side.

**Comment by hon2a** [comment]
@zombieJ Thanks for the tip; I've already added a styling override for the default width in our projects.
