### ISSUE TITLE
select 存在两个相同的value时，搜索有bug

### ISSUE THREAD

**Issue by imdwpeng** [ant-design/ant-design#16160]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/MRVbRd?editors=0010](https://codepen.io/anon/pen/MRVbRd?editors=0010)
![微信图片_20190418165800](https://user-images.githubusercontent.com/19651568/56349797-e8af5100-61fb-11e9-897c-eba9853d28d3.png)

### Steps to reproduce
搜索，输入a

### What is expected?
匹配到a的结果

### What is actually happening?
匹配到Jack,再搜索b，匹配到两个Jack

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.X |
| System | win |
| Browser | chrome |

**Comment by afc163** [comment]
对，不应该有相同的 value，Select 就是一组不同的值的选择器。
