### ISSUE TITLE
Fixed row selection column doesn't respect its `columnWidth`

### ISSUE THREAD

**Issue by hon2a** [ant-design/ant-design#16161]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/r0vpl302yp)

### Steps to reproduce
Create a table that has a fixed row selection column with custom width (`<Table rowSelection={{ columnWidth: 40, fixed: true, ... }} ... />`).

### What is expected?
The width of the row selection column should be `40px`. (In other words, `columnWidth` in `rowSelection` should be applied even when the row selection column is fixed.)

### What is actually happening?
1. The real width of the column is the default `60px`, not the specified custom width.
1. In the "scroll" part of the table the custom width _is_ actually used, leading to either overlap or gap between the fixed and scrolling columns (depending on whether the custom width is above or below the default).

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | MacOS 10.14.4 (18E226) |
| Browser | Chrome 73.0.3683.103 (Official Build) (64-bit) |

---
_Note that this is the second time I've encountered this issue (it has been fixed previously). It might be useful to add a test for it._

**Comment by afc163** [comment]
https://codesandbox.io/embed/r0vpl302yp

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/507615/56350429-59a33880-61fd-11e9-8e7c-26aff1a670b3.png">

**Comment by hon2a** [comment]
@afc163: I was working initially with a slightly older version. I see now that with the latest version the issue (`rowSelection.columnWidth` is not respected) still remains, but is no longer limited to fixed row selection column. Let me create a new issue then (sigh)…
