### ISSUE TITLE
Mention组件中输入一段文字，不能触发@功能。必须需要加入一个空格

### ISSUE THREAD

**Issue by j-kings-huang** [ant-design/ant-design#16171]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
公司的留言板需要对不同用户进行@功能。所以希望使用Mention组件的@功能。但是上线后。用户反馈说并不能@,因为输入了一段文字后。不能触发@组件的功能。查看Mention组件源码，个人感觉是 getRegExp  那个文件夹的正则匹配逻辑不对。希望可以满足后面用户的功能。而做一些改变

### What does the proposed API look like?
<Mention
        style={{ width: '100%' }}
        onChange={onChange}
        placeholder="input @ to mention people, # to mention tag"
        prefix={['@', '#']}
        onSearchChange={this.onSearchChange}
        suggestions={this.state.suggestions}
        onSelect={onSelect}
      />
我希望这个组件的prefix 可以有提示说，可以写入正则匹配的代码。满足用户在不同场景下的使用

**Comment by afc163** [comment]
Duplicate of #15694
