### ISSUE TITLE
Cascader - loadData prop - automatic state update

### ISSUE THREAD

**Issue by MFoksik** [ant-design/ant-design#16173]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/32l1q3y34m)

### Steps to reproduce
Define `loadData` function to add dynamically suboptions. Modify proper node.

### What is expected?
I should manually set state with actual options.

### What is actually happening?
State is automatically updated according to options change.

I do not set it by myself.

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | Windows 10.0.17763 |
| Browser | Chrome 73.0.3683.86 |

---
preview: https://32l1q3y34m.codesandbox.io/

screen before selecting: https://ibb.co/RvP2WRm

screen after selecting: https://ibb.co/KKhRHSB

**Comment by ztplz** [comment]
Actually you have set it yourself. 
![image](https://user-images.githubusercontent.com/17755202/56372798-45c5f980-6232-11e9-81ce-0156d7640fe5.png)

**Comment by zombieJ** [comment]
`selectedOptions` is from the `this.state.options`. You change the `targetOption.children` which makes `this.state` changed.

```jsx
  loadData = selectedOptions => {
    const targetOption = selectedOptions[0];

    targetOption.children = [
      { value: "dynamic1", label: `${targetOption.label} Dynamic 1` },
      { value: "dynamic2", label: `${targetOption.label} Dynamic 2` }
    ];
  };
```

**Comment by MFoksik** [comment]
@zombieJ I know when options were added. Problem is that I do not save them to state manually, which should have happend if I want to update it.

It should not be updated without my intention.

In example on documentation: https://ant.design/components/cascader/#components-cascader-demo-lazy
There is a setState, but if I remove it, it still updates state.
![image](https://user-images.githubusercontent.com/13439968/56409265-8ba5b080-6278-11e9-9e61-d1bb4cd54890.png)

I assume it is some kind of React AntiPattern.

**Comment by MFoksik** [comment]
In this case I think this is a bug, not a feature.

@zombieJ , @ztplz  review this issue again, please.

**Comment by zombieJ** [comment]
Cascader will update after `loadData` called. In your code, you don't have timeout which makes render use the latest changed instance. It's not antd bug
Add timeout to mock ajax load: https://codesandbox.io/s/32l1q3y34m

**Comment by MFoksik** [comment]
@zombieJ My question is: why do state change in my component, even if I did not update it? This should not happen.

https://streamable.com/m55ys

I have added timeout, it is only to mock api communication. Problem is, that in my component (<LazyOptions />) I do not have any setState used, but state updated after all.

**Comment by zombieJ** [comment]
Cascader has its own state and update logic. You should not assume sub component state update time.
