### ISSUE TITLE
Drawer打开过程中加载数据会卡顿

### ISSUE THREAD

**Issue by pennchester** [ant-design/ant-design#16184]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们在项目中会使用Drawer作为页面容器，会在打开的过程中加载页面，目前是在componentDidMount中加载数据，会导致在Drawer弹出的过程中卡顿，希望可以优化下效果或者提供Drawer完全展开的回调

**Comment by jljsj33** [comment]
内容是你自已控制的，，你可以在打开时插入数据，这种接口没什么用。。
```jsx
<Drawer>
 {isLoad && XXXX}
</Drawer>
```

**Comment by afc163** [comment]
感觉有意义，下面的方式和放在 `componentDidMount` 里一样不解决问题。

```
<Drawer>
 {isLoad && XXXX}
</Drawer>
```

**Comment by jljsj33** [comment]
感觉空抽屉展开有意义？？意思是他在 componentDidMount 里把数据加载完成后，，再刷新 visible ，，，应该是 
```
<Drawer visible={isLoad}>{XXX}</Drawer>
```

**Comment by afc163** [comment]
动画完成后的回调。

**Comment by pennchester** [comment]
setTimeout不是根本解决问题的，我也试过，第一次会正常执行，后面的没有效果了

**Comment by l1nyanm1ng** [comment]
我通过使用一个hook来控制，使得在drawer动画完成后才显示容器内的内容，hook的代码如下：
```javascript
/**
 * Drawer 可见性
 */
export const useDrawerVisible = timeout => {
  /** drawer 可见性 */
  const [visible, setVisible] = useState(false);
  /** 内容可见性 */
  const [contentVisible, setContentVisible] = useState(false);
  const open = () => {
    setVisible(true);
    setTimeout(() => setContentVisible(true), timeout);
  };
  const close = () => {
    setVisible(false);
    setContentVisible(false);
  };
  return {drawerVisible: visible, contentVisible, open, close};
};
```

在需要用到Drawer的地方代码如下：
```javascript
const DrawerButton = () => {
  /** 抽屉可见性 */
  const {drawerVisible, contentVisible, open, close} = useDrawerVisible(350);

  return (
      <div>
        <a onClick={open}>
          点击显示Drawer
        </a>
        <Drawer
            width="700px"
            visible={drawerVisible}
            onClose={close}
        >
          {contentVisible &&
          <div>
            Drawer容器内的内容
          </div>}
        </Drawer>
      </div>
  );
};
```

这里的 timeout 设置为 350ms 是我猜想 Drawer 的动画时间应该在 350ms 左右

**Comment by pennchester** [comment]
> 我通过使用一个hook来控制，使得在drawer动画完成后才显示容器内的内容，hook的代码如下：
> 
> ```js
> /**
>  * Drawer 可见性
>  */
> export const useDrawerVisible = timeout => {
>   /** drawer 可见性 */
>   const [visible, setVisible] = useState(false);
>   /** 内容可见性 */
>   const [contentVisible, setContentVisible] = useState(false);
>   const open = () => {
>     setVisible(true);
>     setTimeout(() => setContentVisible(true), timeout);
>   };
>   const close = () => {
>     setVisible(false);
>     setContentVisible(false);
>   };
>   return {drawerVisible: visible, contentVisible, open, close};
> };
> ```
> 
> 在需要用到Drawer的地方代码如下：
> 
> ```js
> const DrawerButton = () => {
>   /** 抽屉可见性 */
>   const {drawerVisible, contentVisible, open, close} = useDrawerVisible(350);
> 
>   return (
>       <div>
>         <a onClick={open}>
>           点击显示Drawer
>         </a>
>         <Drawer
>             width="700px"
>             visible={drawerVisible}
>             onClose={close}
>         >
>           {contentVisible &&
>           <div>
>             Drawer容器内的内容
>           </div>}
>         </Drawer>
>       </div>
>   );
> };
> ```
> 
> 这里的 timeout 设置为 350ms 是我猜想 Drawer 的动画时间应该在 350ms 左右

多谢分享

**Comment by tianzhich** [comment]
也遇到了，这个感觉还是得优化下动画之类的，timeout不是一个常规办法吧
