### ISSUE TITLE
create a react hooks version without class component

### ISSUE THREAD

**Issue by leeseean** [ant-design/ant-design#16183]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
create a react hooks version without class component,best wishes!

### What does the proposed API look like?
`npm install antd@hooks`

**Comment by ztplz** [comment]
No such plan now, but it should be in the future.

**Comment by afc163** [comment]
You can use hooks in your problem with antd latest version now, it is not conflicted at all.
