### ISSUE TITLE
走马灯位置和自定义样式问题

### ISSUE THREAD

**Issue by yingxiaoqiang** [ant-design/ant-design#16186]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1、现走马灯的指示点位置只支持下边和右边（只有vertical一个参数），希望能支持左边或者上面；
2、走马灯的指示点能否支持自定义样式；

### What does the proposed API look like?
1、走马灯的指示点位置只支左边、右边、上边、下边；
2、走马灯的指示点支持自定义样式；

**Comment by leeseean** [comment]
这个可以自己写css解决
