### ISSUE TITLE
Select组件使用 OptGroup 分组时滚动位置不正确

### ISSUE THREAD

**Issue by lz-lee** [ant-design/ant-design#16181]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lxqk488379)

### Steps to reproduce
点击下拉菜单面板，鼠标hover至“热门/常用” 分组，滚动条初始位置则定位不正确；滚动至顶部，滚动条位置不会固定。

### What is expected?
点击下拉菜单面板，鼠标hover至“热门/常用” 分组，滚动条初始位置不变，滚动至顶部，滚动条不乱跳。

### What is actually happening?
点击下拉菜单面板，鼠标hover至“热门/常用” 分组，滚动条初始位置则定位不正确，滚动至顶部，滚动条乱跳。

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | 16.8.3 |
| System | macOS 10.13.4 |
| Browser | Chrome  73.0.3683.103 |

---
分组数据按照 A-Z 排列，但需要在A组前加一组 “热门/常用” 分组，加上这组就会出现滚动条滚动位置不正确的情况；只有 A-Z的分组数据时，没有这个现象。可注释第一组数据测试正常现象。
⚠️在不使用 `dropdownRender ` 方法覆盖css 的情况下可以复现。

**Comment by lz-lee** [comment]
解决办法：用 `dropdownRender` 自定义下拉框内容，添加css 覆盖 `ul.ant-select-dropdown-menu` 的 `overflow: auto` 样式。https://codesandbox.io/s/lxqk488379

**Comment by zombieJ** [comment]
能给个动图吗？有点不太明白……

**Comment by lz-lee** [comment]
> 能给个动图吗？有点不太明白……

![QQ20190429144603HD](https://user-images.githubusercontent.com/22316795/56881027-9ab70a80-6a91-11e9-9f90-4018caeb161e.gif)
注释 `dropdownRender ` 方法后复现。

**Comment by afc163** [comment]
hover 触发的 active item 就不要触发滚动条移动了。

**Comment by shbhsu** [comment]
> 解决办法：用 `dropdownRender` 自定义下拉框内容，添加css 覆盖 `ul.ant-select-dropdown-menu` 的 `overflow: auto` 样式。https://codesandbox.io/s/lxqk488379

建議這邊設hidden看起來會比較正常
.demo {
  overflow: hidden;
}
.demo .ant-select-dropdown-menu {
  overflow: initial;
}
