### ISSUE TITLE
Upload组件里面的fileList列表设置url后，生成链接<a target="_blank" rel="noopener noreferrer" class="ant-upload-list-item-name" ></a>，为什么加上rel，能去掉rel吗，我需要传递referrer信息

### ISSUE THREAD

**Issue by yansuan** [ant-design/ant-design#16192]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
通过referrer在后台可以做一些验证

### What does the proposed API look like?
不控制referrer

**Comment by afc163** [comment]
https://github.com/asciidoctor/asciidoctor/issues/2071
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md
https://support.performancefoundry.com/article/186-noopener-noreferrer-on-my-links

建议这种需求用自定义的文件列表。
