### ISSUE TITLE
Cascader组件在校验时如果使用hasFeedback，样式会有偏差

### ISSUE THREAD

**Issue by juneryo** [ant-design/ant-design#1619]
version：0.12.17

![qq 20160510104927](https://cloud.githubusercontent.com/assets/4101515/15134242/dd8e4446-169c-11e6-8ac0-a7a2e35c5c3d.png)

示例在这里：
http://codepen.io/juneryo/pen/RavmBO?editors=0010

**Comment by benjycui** [comment]
`hasFeedback` 不建议和 `Input` 以外的组件一起使用 http://ant.design/components/form/#demo-validate-static

**Comment by afc163** [comment]
修复了图标下移的问题，另外配合的控件宽度只能是 100%。如 @benjycui 所说，目前和 Input 之外的组件一起使用会有很多问题。
