### ISSUE TITLE
Tabs 组件设置 animated={false} 样式 .ant-tabs-tabpane{height: 100%;} 切换tab隐藏的tab虽然看不到但是还会占据空间

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#16191]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rj4w05qpom)

### Steps to reproduce
切换到第二个tab

### What is expected?
隐藏的tab不要再占据空间

### What is actually happening?
切换tab隐藏的tab虽然看不到但是还会占据空间

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.2.0 |
| System | Window |
| Browser | Chrome 73.0.3683.75 |

---
由于我需要ant-tabs-tabpane占满可用空间，超出出现滚动条，所以设置 .ant-tabs-tabpane{height: 100%;} ， 新版本不显示的tab是通过opacity:0来隐藏的。  不清楚算不算bug，希望隐藏后不要再占据空间

**Comment by zombieJ** [comment]
如果用 css 覆盖的话，把 inactive 的 css 也覆盖一下： https://codesandbox.io/s/ll029qxrom

Tabs 默认需要占据一下高度为 0 的空间，因为内部 content 如果有 dom 计算的需求 `display: none` 会导致尺寸获取不到的问题。

**Comment by ty-bt** [comment]
收到 谢谢..
