### ISSUE TITLE
Cannot call this.setState on custom button inside the renderExtraFooter of RangePicker

### ISSUE THREAD

**Issue by LucasBSC** [ant-design/ant-design#16208]
* [x] I have searched the issues of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8488p1xp7l?fontsize=14)

### Steps to reproduce
1 - Code layout with antd components `Row` and `RangePicker`

2 - Place `open` prop with `false` value on the `RangePicker />` component according to default state `pickerOpen`

3 - Call `handlePickerOpen` method to open the calendarDiv based on `onClick={this.handlePickerOpen}`

4 - Call `() => this.setState({pickerOpen: false}` on the `onClick` of OK `<button  />`

### What is expected?
It is expected the calendarDiv to close when one clicks the OK button

### What is actually happening?
Nothing happens, calendar keeps opened

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.2 |
| System | Windows 10 |
| Browser | Google Chrome |

---
I am trying to create buttons to change date values based on 'Last X months' and then submit it closing the calendar div. So I struggled firstly by trying to reproduce the behaviour of clicking on a button and closing the calendar.

**Comment by afc163** [comment]
button click event propagate to div which triggered the `handleOpenPicker`.

https://codesandbox.io/s/mmp1omr6vp
