### ISSUE TITLE
Select 在设置了labelInValue后，setFieldsValue设置选中失效，设置的值为{key:xx,label:xx}

### ISSUE THREAD

**Issue by liubin915249126** [ant-design/ant-design#16200]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lyxo1z730q)

### Steps to reproduce
直接设置 this.props.form.setFieldsValue()

### What is expected?
能够选中某项

### What is actually happening?
没有显示值，但是allowClear显示可以清空

| Environment | Info |
|---|---|
| antd | 3.8.4 |
| React | 16.6 |
| System | macos |
| Browser | chrome 73.0.3683.103 |

**Comment by afc163** [comment]
It works very well in your codesandbox:

<img width="492" alt="image" src="https://user-images.githubusercontent.com/507615/56480813-5bffde00-64ee-11e9-8b61-883a8765aab0.png">
