### ISSUE TITLE
Table's column property 'onFilter' should be ran on each descendant record of a tree 

### ISSUE THREAD

**Issue by gregoryforel** [ant-design/ant-design#16207]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk7z3vp308)

### Steps to reproduce
* Type 'semi' in the column search input and press Enter or validate.

### What is expected?
`onFilter` should be ran on each `records` of the `dataSource`, including all descendants.

### What is actually happening?
`onFilter` is only ran on each root `records` of `dataSource`, in my example 'Tesla' and 'Microsoft'. Therefore, I cannot filter out record 'cars' inside 'Tesla' if I type 'Semi' in the search input.

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.1 |
| System | Windows 10 x64 Version 1803 - OS Build 17134.706 |
| Browser | Chrome 73.0.3683.103 (Official Build) (64-bit) |

---
My goal is to be able to filter down to any descendant of a tree dataSource, I understand I have to use `onFilter` for this. If this is not the correct use, my apologies as I can't find the right way to do it in the docs.

**Comment by gregoryforel** [comment]
Hi @afc163! 

Any chance you help me with this please? Thanks in advance

**Comment by zombieJ** [comment]
It works on your sample. Could you help to describe more on this?
![Kapture 2019-05-01 at 22 06 21](https://user-images.githubusercontent.com/5378891/57020913-67c17200-6c5d-11e9-924a-ceaa955c94b1.gif)

**Comment by gregoryforel** [comment]
@zombieJ I updated the reproduction link using antd's template.
It partially works as you said, but what I'm really trying to accomplish is to also be able to hide Cars and its children in the example you used. If I type "semi" in the searchbox, I'd like to only show this hierarchy:
Tesla > Truck > Semi. everything else should disappear.

I can't think of other ways to do this than to be able to run onFilter on each descendant record of the tree.

**Comment by zombieJ** [comment]
Got what you mean. Since Table filter is by record level, current default filter function may not help on this.
You need to generate a filtered `dataSource` for the requirement.

**Comment by gregoryforel** [comment]
I'll investigate this, thank you.

**Comment by gregoryforel** [comment]
@zombieJ do you think that this would be a good requirement to make `onFilter` act on descendents too rather than only current default filter?

**Comment by zombieJ** [comment]
Table component provides the basic filter function. If user want to have some flatten filter logic, it may need user to customize dataSource themself. But this is not final conclusion, we will reconsider it if get more feedback about flatten filter requirement.

**Comment by AdamczykMaciej** [comment]
It would be really great to have this feature. We are really missing it - filtering Table's (tree structure) all records including descendants, not only parents and displaying parents that matched all filters or its children matched the all filters.
