### ISSUE TITLE
createForm bind stateless component causing error

### ISSUE THREAD

**Issue by colinshen** [ant-design/ant-design#1621]
## What you did
I'm using stateless component, and bind my login component to createForm. 
```
Login = createForm()(Login)
```
## What actually happened

I got an error.
```
  24:1  error  'Login' is constant  no-const-assign

✖ 1 problem (1 error, 0 warnings)


```

## Online demo

I'm sorry it's so compicated to create an online demo.

## Environment Information

- The version of antd(1.0.0-beta.9):
- Your operating system and it's version(e.g. OSX 10.11.4):
- Your browser and it's version(e.g. Chrome 50.0.2661.94(64-bit)):

I think the main issue here is that createForm doesn't accept stateless component

**Comment by benjycui** [comment]
Please spend some time on learning [JavaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/const).
