### ISSUE TITLE
TreeSelect 树选择 闪动问题

### ISSUE THREAD

**Issue by durongzhang** [ant-design/ant-design#1622]
TreeSelect的多选功能，切换选择二级及二级以下选项，输入框内容闪动

**Comment by durongzhang** [comment]
还有就是默写组件在ie8下依赖jquery?

**Comment by warmhug** [comment]
TreeSelect 确认下是否是动画的变化？可以设置下 `dropdownPopupAlign={{ overflow: { adjustY: 0, adjustX: 0 } }}` 视觉效果会更稳定。

ie8下依赖jquery，应该没什么问题吧。

**Comment by afc163** [comment]
Any progress? @durongzhang
