### ISSUE TITLE
Select组件设置showSearch后，先搜索，不选择下拉选项，直接点击下拉框外使下拉关闭，此时输入框会被清空，但onSearch并不会拿到清空后的值

### ISSUE THREAD

**Issue by jinboker** [ant-design/ant-design#16223]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://ant.design/components/select-cn/](http://ant.design/components/select-cn/)

### Steps to reproduce
Select组件设置showSearch后，先搜索，不选择下拉选项，直接点击下拉框外使下拉关闭，此时输入框会被清空，但onSearch并没有被调用，感觉与api doc中的“文本框值变化时回调	”说明不符

### What is expected?
因为点击下拉面板外部导致输入框被清空后，onSearch会被调用

### What is actually happening?
如重现步骤

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | 16.8.4 |
| System | OSX |
| Browser | chrome最新版 |

---
请问有没有其他方式能在因为点击下拉面板外部导致输入框被清空后知晓该变化的方式？

**Comment by zombieJ** [comment]
嗯，这个点击清空也应该触发一下 onSearch，否则漏了一个状态。

**Comment by zombieJ** [comment]
We may need keep the `onSearch` trigger.
ref: #10817
cc @afc163

**Comment by zsl1549** [comment]
考虑用这个 AutoComplete   @jinboker
