### ISSUE TITLE
Pull #16126 break the current code

### ISSUE THREAD

**Issue by vipcxj** [ant-design/ant-design#16229]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/84zk9696y8)

### Steps to reproduce
Test是用由forwardRef得到的可以传递ref的函数组件，TestClass是一般的ClassComponent

### What is expected?
`Form.create()(Test)`不会报错
`Form.create()(TestClass)`能接受wrappedComponentRef属性，或者更进一步，直接支持使用ref

### What is actually happening?
`Form.create()(Test)` 会导致typescript报错，说是不能接受Test
`Form.create()(TestClass)`不会报错，但返回的新组件不能接受wrappedComponentRef属性

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | 16.8.3 |
| System | all |
| Browser | all |

---
在那个pull合并前的版本是没问题的

**Comment by zombieJ** [comment]
看来得继续磕下去。。。
