### ISSUE TITLE
form 如何获取字段的 rules 等信息

### ISSUE THREAD

**Issue by tolerance-go** [ant-design/ant-design#16222]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
准备实现一个 validate 静默版本

### What does the proposed API look like?
form. getFieldsMeta

https://github.com/react-component/form/issues/282

**Comment by zombieJ** [comment]
这些信息本身就是开发者提供的，直接抽出来就行了：
```jsx
const rules = {
  'name': [{ isRequired: true }],
};

return (
  <Form>
    {getFieldDecorator('name', {
      rules: rules.name,
    })}
  </Form>
);
```

**Comment by tolerance-go** [comment]
就是抽不出来啊……开局一个 form 怎么破

**Comment by zombieJ** [comment]
你的有代码示例吗？不理解为什么会抽不出来

**Comment by tolerance-go** [comment]
```js
 render: (val, record, index, { form, editing, colDef }) => {
    return (
      <FormItem>
        {form.getFieldDecorator({
          rules: RULES_REQUIRED,
        })(<Select defaultOpen={editing} editing={editing} options={UNIT_ENUM_OPTIONS2} />)}
      </FormItem>
    );
  },
```
table 内部只能获取到装饰后的 form，现在对这个 form 的方法做了代理可以拿到了
