### ISSUE TITLE
RangePicker组件中当点选好时间段标签后不能选择具体的小时分钟时间

### ISSUE THREAD

**Issue by kevinpursuing** [ant-design/ant-design#16220]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
RangePicker中点选thismonth后，再次打开pick框时，showtime按钮是置灰掉的，还得重新选择

### What is expected?
showtime在选择时间段不应该是置灰掉的，应该可以设置具体的时间

### What is actually happening?
不能设置小时分钟

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.4.0 |
| System | mac |
| Browser | chrom最新版 |

**Comment by zombieJ** [comment]
![Kapture 2019-04-22 at 15 15 09](https://user-images.githubusercontent.com/5378891/56488621-7f885000-6511-11e9-87ab-66bb6d56c824.gif)
