### ISSUE TITLE
Select active item hover color is wrong

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#16234]
<img width="147" alt="image" src="https://user-images.githubusercontent.com/507615/56498418-27167a00-6534-11e9-97be-5abc9e49997f.png">

When hover on active item, item background should be blue like above image:

<img width="156" alt="image" src="https://user-images.githubusercontent.com/507615/56498421-2bdb2e00-6534-11e9-8b72-c3b05e1e7036.png">

**Comment by zombieJ** [comment]
Note:

> active 蓝色，selected 灰色。
> active 优先级我个人感觉应该高一点
