### ISSUE TITLE
antd InputNumber数字输入框如何确保每一个输入框的唯一性

### ISSUE THREAD

**Issue by Seeyoucm** [ant-design/ant-design#16237]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
在切换渲染内容输出的时候，前一个的分数的设定为切换后没有清零，仿佛是没有重新渲染
InputNumber
![Uploading image.png…]()

### What is expected?
每一个InputNumber输入值的设定，不会相互影响

### What is actually happening?
前一个模块索引1的值，在切换模块显示后，第二个模块相同索引处的初始值不再是0，而是上一个模块设定后的值

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16 |
| System | win 7 |
| Browser | no |

**Comment by Seeyoucm** [comment]
![image](https://user-images.githubusercontent.com/38176375/56501222-8b3f3b00-6540-11e9-8638-881de94abce1.png)

**Comment by afc163** [comment]
请使用不同的 state 控制不同的组件。

**Comment by Seeyoucm** [comment]
页面的渲染是通过reducer里面处理后输出的数据，每次输出的数组内容都是不一样的，所以每一个模块内容的渲染输出展示，数据都是不同的，------------------ 原始邮件 ------------------
发件人: "偏右"<notifications@github.com>
发送时间: 2019年4月22日(星期一) 晚上9:00
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "Seeyoucm"<2603140326@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design] antd InputNumber数字输入框如何确保每一个输入框的唯一性 (#16237)



请使用不同的 state 控制不同的组&#x4EF6;。
 
&mdash;
