### ISSUE TITLE
 Namespace 'React' has no exported member 'AriaAttributes'

### ISSUE THREAD

**Issue by TonyRyze** [ant-design/ant-design#16230]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/icon-cn/](https://ant.design/components/icon-cn/)

### Steps to reproduce
用Typescript使用Icon组件

### What is expected?
不要报类型错误

### What is actually happening?
Icon组件报 Namespace 'React' has no exported member 'AriaAttributes'，属于类型错误

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | react |
| System | win10家庭版 64位操作系统 |
| Browser | Google Chrome  73.0.3683.103（正式版本）（64 位） |

**Comment by zombieJ** [comment]
升级一下 `@types/react` 版本：https://unpkg.com/@types/react@16.8.14/index.d.ts

**Comment by smizel** [comment]
plase reopen

**Comment by ztplz** [comment]
@smizel   If you still running into it, please create a repo for your question.

**Comment by RichardNTran** [comment]
please reopen
