### ISSUE TITLE
Modal can't change border-radius

### ISSUE THREAD

**Issue by Meow-z** [ant-design/ant-design#16248]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
修改 Modal 外边框的圆角。

目前有：
bodyStyle, 用来设置 Modal body 样式。
style, 可用于设置浮层的样式，调整浮层位置等。

但是这两者都不能修改 Modal 的 border-radius. 我通过直接重写 class ant-modal-content 的方式可以满足这个需求，但是感觉不是一个优雅的解决方案。

### What does the proposed API look like?
bodyStyle 可以修改 ant-modal-content 样式。

**Comment by afc163** [comment]
目前的 dom 结构不太好直接修改 `.ant-modal-content`，就用 `className="xxxx"` 来支持吧。

```css
.xxxx .ant-modal-content {
  border-radius: 2px;
}
```

**Comment by Nikualla1** [comment]
Same problem

**Comment by Baraka-Mugisha** [comment]
You can add overflow and make it hidden or auto

```
.ant-modal-content {
    overflow: auto;
    border-radius: 24px
}

**Comment by ZeelChauhanHtree** [comment]
You can add like this in CSS :  [100% work]

.ant-modal {
  border:1px solid red;
  border-radius: 15px;
  box-shadow: 0px 0px 20px 0px var(--primary-color);
  overflow:hidden;
}

**Comment by NeginSal** [comment]
Hi, Is there any way to assign a border-radius with an inline style for Modal? Like: 
`bodyStyle={{ borderRadius: '20px' }}` I try this way but it doesn't work?

**Comment by ZeelChauhanHtree** [comment]
> modal {



> Hi, Is there any way to assign a border-radius with an inline style for Modal? Like: `bodyStyle={{ borderRadius: '20px' }}` I try this way but it doesn't work?

so you can add inline CSS directly in Modal components like
<Modal style={{border-radius:"20px"}}

**Comment by NeginSal** [comment]
> 

I try these ways for my Modal component but they don't work:
**1.**`bodyStyle={{ borderRadius: '20px' }}`
**2.**`style={{border-radius:"20px"}}`

**Comment by NeginSal** [comment]
> > modal {
> 
> > Hi, Is there any way to assign a border-radius with an inline style for Modal? Like: `bodyStyle={{ borderRadius: '20px' }}` I try this way but it doesn't work?
> 
> so you can add inline CSS directly in Modal components like <Modal style={{border-radius:"20px"}}> .....


I try these ways for my Modal component but they don't work:
**1.**`bodyStyle={{ borderRadius: '20px' }}`
**2.**`style={{ borderRadius: '20px' }}`

**Comment by ZeelChauhanHtree** [comment]
> 
style={{ borderRadius: '20px' }}
This style working i tried in my web
Are you using ANTD or ANTD pro and might be changing of version ...

**Comment by ZeelChauhanHtree** [comment]
> > > modal {
> > 
> > 
> > > Hi, Is there any way to assign a border-radius with an inline style for Modal? Like: `bodyStyle={{ borderRadius: '20px' }}` I try this way but it doesn't work?
> > 
> > 
> > so you can add inline CSS directly in Modal components like <Modal style={{border-radius:"20px"}}> .....
> 
> I try these ways for my Modal component but they don't work: **1.**`bodyStyle={{ borderRadius: '20px' }}` **2.**`style={{ borderRadius: '20px' }}`

style={{ borderRadius: '20px' }}
This style working i tried in my web
Are you using ANTD or ANTD pro and might be changing of version ...

**Comment by NeginSal** [comment]
> 

I tried it again, but nothing changes . my ant version:```"antd": "^4.20.7",```
