### ISSUE TITLE
Select组件，当值为null时和值为undefined时结果不一致，placeholder显示不出来，是否可以同等处理？

### ISSUE THREAD

**Issue by yansuan** [ant-design/ant-design#16243]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://yql217w22v.codesandbox.io/)

### Steps to reproduce
<Select
    showSearch
    allowClear
    value={null}
    style={{ width: 200 }}
    placeholder="Select a person"/>

### What is expected?
null和undefined一样，都是无值

### What is actually happening?
null作为一个数据，undefined为空

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | react@16.8.6 |
| System | windows 10 |
| Browser | chrome73 |

---
因为后台传递过来的一般都是null，不会是undefined

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2367
