### ISSUE TITLE
【新组件】请问有没有 图片预览 的开发计划，如果没有，能不能在官方文档的精选组件里提供一些好的三方组件呢

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design#16245]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当前的图片预览是基于upload的，功能不完善，没有放大、缩小、旋转、前后图切换等功能。

还有当前upload组件listType="picture-card"时，图片宽高比不一致时，长方形图片在预览框没有铺满，不美观。
![{238BC85A-8EDD-4BA8-A7FA-637C3922019B}_20190423120312](https://user-images.githubusercontent.com/19385704/56553488-3c85b580-65c1-11e9-8a8d-f005dcd5c370.jpg)

### What does the proposed API look like?
期望一个图片预览组件，可以实现放大、缩小、旋转、前后图切换等功能，同时图片列表支持长图和方图的铺满

**Comment by afc163** [comment]
Duplicate of #13719
