### ISSUE TITLE
table的checkbox无法选中，selectedRows一直为[]

### ISSUE THREAD

**Issue by pacific0437** [ant-design/ant-design#1624]
0.12.14没有这个问题  0.12.17有这个问题
贴部分代码

    const rowSelection = {
      onChange(selectedRowKeys, selectedRows) {
        updateButton(selectedRows);  //事实上选不中 因此selectedRows这里一直是空数组
      },
    };
下面是显示部分， 其实感觉没什么好贴得

          <FormItem>
            <Table
              rowSelection={rowSelection}
              columns={columns}
              dataSource={stocks}
              pagination={false}
              rowKey={rowKey}
            />
          </FormItem>

我debug了一下  发现event刚传进去的时候 event.target.checked就是错的
正常来讲 未选中改为选中时 这个值应该是 true.咱们demo页面就是正确的。  但17版本下传进去的是false。

**Comment by afc163** [comment]
鉴于 demo 页面就是 0.12.17 版本，所以不知道问题出在哪里。

麻烦提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by pacific0437** [comment]
升级到1.0.1之后 功能正常了。
