### ISSUE TITLE
menu active color not right while menu selected and collapsed

### ISSUE THREAD

**Issue by kuitos** [ant-design/ant-design#16241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ry24j9nq5q)

### Steps to reproduce
1. 点击任意二/三级导航项
2. 菜单折叠，选中色丢失
3. hover 菜单，选中色重现

### What is expected?
菜单折叠选中色正常

### What is actually happening?
菜单折叠，选中色丢失

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | latest |
| System | osx |
| Browser | chrome 73 |

**Comment by Hugo-seth** [comment]
我觉得问题出现的原因应该是你的设置的 `mode `是 `vertical`，`props `却使用了 `inlineCollapsed` ，这样做是有警告的。
![image](https://user-images.githubusercontent.com/17878774/56572366-85edf900-65f1-11e9-8c7d-e4f5c2665fee.png)
