### ISSUE TITLE
Feature request: <Paragraph /> localization

### ISSUE THREAD

**Issue by vladimirmoushkov** [ant-design/ant-design#16255]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
You define copyable paragraph like:
`<Paragraph copyable>TEXT</Paragraph>`
You will get copy icon that allows the child **TEXT** to be copied hitting the same icon. If you however hover the the same icon you will get english hint stating *copy*.

### What does the proposed API look like?
I wish to have localisation property on `<Paragraph locale={localizationProps} />` similar like on <Table /> one.
This will then allow to define **localizationProps**:
```
{
copyText: "копирай",
copiedText: "копирано!"
}

```

**Comment by afc163** [comment]
Try https://ant.design/components/locale-provider/
