### ISSUE TITLE
Tree checkbox animation not correct

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#16259]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#components-tree-demo-basic-controlled](https://ant.design/components/tree-cn/#components-tree-demo-basic-controlled)

![Kapture 2019-04-23 at 22 23 58](https://user-images.githubusercontent.com/5378891/56588946-e9d6e880-6616-11e9-8c10-abdc5a48c912.gif)

### Steps to reproduce
Click the checkbox twice

### What is expected?
square animation

### What is actually happening?
rect animation

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.0 |
| System | Mac |
| Browser | Chrome |

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/56650099-f7dd4580-66b8-11e9-9bc3-e67389310a60.png)


备注一下实现方法

父元素高度为宽度的 1.5 倍。所以 height 重写为 2/3 ，top 为 (1 - 2 / 3) / 2 =  1 / 6
