### ISSUE TITLE
使用redux时Form组件表单验证失效

### ISSUE THREAD

**Issue by JrIdeA** [ant-design/ant-design#1625]
你好

参考demo：http://codepen.io/jridea/pen/pyYoYZ

如 demo，使用 Form.create 将表单项的值与 redux 进行关联，使得表单值与 store 数据同步，比如 demo 中 store 存了数据 `{ name: '' }` ，但当清空 input 的内容，则必填的验证不会生效了，不会出现提示了

**Comment by benjycui** [comment]
你的代码里把 errors 扔掉了，参见例子的用法：http://react-component.github.io/form/examples/redux.html

![image](https://cloud.githubusercontent.com/assets/3580607/15169238/ce9b8e56-176b-11e6-8a7d-b3a9bfb8a6be.png)

**Comment by JrIdeA** [comment]
看上述的例子是要把 onFieldsChange 的返回的数据结构全部放置到 store 中？这样感觉有点不合适啊，我们直观的用法就是在 store 中直接存一个对象，key 表示表单项的 name，value 表示表单项的 value，然后验证是根据 value 进行验证，而不用把错误的信息也放到 store。
并且这样感觉通过其他方式改变 store 的数据就会变得很麻烦，必须了解到 Form 的数据结构，store 数据的初始化也必须构造成 Form 的数据结构，而且看 antd 的文档这方面也没有很好的说明。

**Comment by BiosSun** [comment]
+1

**Comment by ChiaJune** [comment]
+1
