### ISSUE TITLE
Specifying a Typography-Title type does not affect color

### ISSUE THREAD

**Issue by atarla** [ant-design/ant-design#16261]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/46nk16o8x)

### Steps to reproduce
<Title level={3} type="warning">some text</Title> is black

### What is expected?
text with warning color 

### What is actually happening?
text in black color

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.5 |
| System | na |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
Title do not have the `type` prop. It mistake added in document of Title part.
Sync with designer to handle this.
