### ISSUE TITLE
Carousel组件结合Typescript使用时，调用this.refs.myCarousel.prev会提示类型"ReactInstance"上不存在属性prev。类型"Element"上不存在属性prev。

### ISSUE THREAD

**Issue by wcy4025264** [ant-design/ant-design#16265]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel-cn/](https://ant.design/components/carousel-cn/)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
Carousel组件结合Typescript使用时，调用this.refs.myCarousel.prev会提示类型"ReactInstance"上不存在属性prev。类型"Element"上不存在属性prev。这个怎么解决呢

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.8.2 |
| System | win7-64bit |
| Browser | Chrome73 |

---
无

**Comment by jljsj33** [comment]
还在用 refs ？lint 能过？？
```jsx
carousel: Carousel

<Carousel ref={c => { this.carousel = c; }} />

this.carousel.prev();
```

**Comment by wcy4025264** [comment]
> 还在用 refs ？lint 能过？？
> 
> ```js-jsx
> carousel: Carousel
> 
> <Carousel ref={c => { this.carousel = c; }} />
> 
> this.carousel.prev();
> ```

那carousel组件的prev应该怎么用呢
