### ISSUE TITLE
Table columns width失效

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#16277]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/9142or5r9r)

### Steps to reproduce
打开就行了，设置了column的width，但是不生效

### What is expected?
column的width生效

### What is actually happening?
column的width不生效

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | latest |
| System | windows10 |
| Browser | chrome73 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by XianZhengquan** [comment]
啥时候提供一个API来设置哦？
