### ISSUE TITLE
Input with more than 2000 characters of form Regexp validation will get stuck

### ISSUE THREAD

**Issue by fenghuizhang** [ant-design/ant-design#16271]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n049rv7kwl)

### Steps to reproduce
Quickly enter a comma-separated email address with a length of 2000 characters or paste it directly

### What is expected?
no stuck

### What is actually happening?
the page get stuck

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16@latest |
| System | windows10 |
| Browser | chrome74 |

**Comment by zombieJ** [comment]
This performance issue is caused by your regex not antd:

<img width="359" alt="屏幕快照 2019-04-24 下午12 27 25" src="https://user-images.githubusercontent.com/5378891/56632433-57712c00-668c-11e9-903d-f5bb98e4b64d.png">

**Comment by fenghuizhang** [comment]
> This performance issue is caused by your regex not antd:
> 
> <img alt="屏幕快照 2019-04-24 下午12 27 25" width="359" src="https://user-images.githubusercontent.com/5378891/56632433-57712c00-668c-11e9-903d-f5bb98e4b64d.png">

![image](https://user-images.githubusercontent.com/19684413/56634434-960ae480-6694-11e9-86f3-42388dc21bd0.png)
Are you sure?

**Comment by zombieJ** [comment]
End with `23` and try again.

**Comment by fenghuizhang** [comment]
> End with `23` and try again.

@zombieJ  Okay but I don't think it's a regexp problem,  it just shouldn't be a real time validation and I implemented it with custom validation
[https://codesandbox.io/s/n049rv7kwl](url)

**Comment by zombieJ** [comment]
You can set `validateTrigger` to `onBlur` only validate when input blurred.
