### ISSUE TITLE
倒计时组件（Statistic.Countdown）倒计时结束后能自动增加一个class

### ISSUE THREAD

**Issue by piscdong** [ant-design/ant-design#16273]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
倒计时结束后希望显示的倒计时文字改成红色

### What does the proposed API look like?
结束后能自动增加一个class，比如antd-statistic-finished

**Comment by piscdong** [comment]
有个差不多类似的功能，单选框选中时，会增加一个后缀是“-checked”的class

**Comment by zombieJ** [comment]
Statistic 和 Checkbox 还是有点区别的，我们设计上倒计时完成没有额外样式。如果想要控制额外样式的话，你可以用 `onFinish` 事件处理一下哈~

**Comment by piscdong** [comment]
> Statistic 和 Checkbox 还是有点区别的，我们设计上倒计时完成没有额外样式。如果想要控制额外样式的话，你可以用 `onFinish` 事件处理一下哈~

如果是列表里的多个倒计时就很麻烦了

**Comment by zombieJ** [comment]
我指的是包一个 HOC 组件哈~~

**Comment by piscdong** [comment]
> 我指的是包一个 HOC 组件哈~~

还是希望官方能支持，更方便，毕竟懒惰是推动科学进步的不懈动力啊

**Comment by zombieJ** [comment]
antd 这边添加 api or className 会比较谨慎，因为会影响将来重构。目前倒计时没有额外样式设计，这个暂时不会加的 : )

**Comment by piscdong** [comment]
> antd 这边添加 api or className 会比较谨慎，因为会影响将来重构。目前倒计时没有额外样式设计，这个暂时不会加的 : )

😔
