### ISSUE TITLE
视觉 色彩 拂晓蓝色彩不对

### ISSUE THREAD

**Issue by wlwang12** [ant-design/ant-design#16279]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/spec/colors-cn](https://ant.design/docs/spec/colors-cn)

### Steps to reproduce
1.拖到最底，点击页面的颜色切换；
2.在回滚到颜色区域（拂晓蓝）；

### What is expected?
一种蓝色，而不是两种颜色；

### What is actually happening?
两种颜色，一种是当前页面的颜色和原本的蓝色；

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | react |
| System | macOS Sierra |
| Browser | 谷歌 |
![image](https://user-images.githubusercontent.com/40886939/56643041-64e9de80-66ab-11e9-81b5-3f8c4ede94bb.png)

**Comment by zombieJ** [comment]
6666，这都能发现

**Comment by afc163** [comment]
类似的问题：https://github.com/ant-design/ant-design/issues/14774

**Comment by zombieJ** [comment]
hi @mzohaibqc, could you help to check on this. Seems generate replace color back with variable change the `@blue-x` color: https://github.com/mzohaibqc/antd-theme-generator/blob/master/index.js#L368

**Comment by mzohaibqc** [comment]
@zombieJ You are right but this is what it is supposed to do. At the bottom of the page, there is a color picker to update `@primary-color` which is by default `@blue-6` so when you update `@primary-color` it updates every primary color and it's shades. I need to look into your code and see how this color shades are being shown and how we can avoid updating `@blue-x` colors when `@primary-color` gets updated.

@zombieJ @afc163 Let me know about your thoughts on this.

**Comment by zombieJ** [comment]
The color is like:
```less
@blue: xxx

@primary-color: @blue

.some-other {
  background: @blue
}
```

Which should only replace the `@primary-color`, not `@blue`. Currently it replace all the string color same into `@primary-color`

**Comment by mzohaibqc** [comment]
@zombieJ No, it first compiles all less/css/scss and then generates a less based on rules that contain colors and then replaces colors with matching color variables. so now here is another requirement comes, which I'll try to add this feature ASAP.

**Comment by afc163** [comment]
Same problem as #20079, merged in it.
