### ISSUE TITLE
antd有没有出富文本编辑器的计划？

### ISSUE THREAD

**Issue by lisun0459** [ant-design/ant-design#16274]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
**1、富文本编辑器不够开放**
官方推荐的两个富文本编辑器react-quill，braft-editor
不得不说react-quilll颜值很高，一路采坑下来最后，不支持内联样式是一个巨坑，其次里面的工具栏上的样式用的是class，这些class得同时放到前端文件，这操作。。。尤其在小程序上使用插件转译内容后完全失去了样式，表现有点er en~~~~braft-editor测试了一下也有这个问题，同时也测试了一下wangEdit部分功能不全。
**2、小编对富文本编辑器需求在扩大**
随着现在微信公众号，各种头条的发展，内容运营人员对于编辑器的要求越来越高，很多小编不满传统编辑器功能，基本是去什么135编辑器，秀米编辑器，360编辑器，把内容编辑好再copy过来，完蛋了，quill不支持内联样式，编辑人员一片抱怨。相反Ueditor比较开放一些，但颜值er en~~~~，关键配置起来不太友好。
**3、公司自己改造百DU编辑器**
成本太大，颜值太低，坑太多。
**4、个人觉得富文本编辑器是后台比较重要的一个部分。**

### What does the proposed API look like?
相对其他的编辑器是比较开放的，功能齐全的。

**Comment by afc163** [comment]
Not plan yet, check #1083
