### ISSUE TITLE
Upload in Mobile Firefox not working if using camera

### ISSUE THREAD

**Issue by JoeDevGeeeee** [ant-design/ant-design#16285]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload](https://ant.design/components/upload)

### Steps to reproduce
1. Open firefox in Android
2. Go to https://ant.design/components/upload
3. Scroll down to the drag and drop section
4. Click drag and drop
5. Choose camera to take a picture
6. finish taking photo and click ok
7. Upload is not working

### What is expected?
Upload should work after user take picture with mobile camera

### What is actually happening?
Upload is not working

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.2 |
| System | Android 7.1.1 |
| Browser | Android Firefox 66.0.2 |

**Comment by zombieJ** [comment]
Hi, antd is not totally compatible with mobile device. If Upload not work as expect, please try to use input instead.
