### ISSUE TITLE
Typography.Text使用prefixCls属性后, edit图标和enter图标表现怪异

### ISSUE THREAD

**Issue by VoliBearCat** [ant-design/ant-design#16288]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x950mzr7p)

### Steps to reproduce
Typography.Text同时使用prefixCls、editable属性

### What is expected?
![image](https://user-images.githubusercontent.com/11676384/56706728-9ebcf280-6748-11e9-8b87-4cba4463e358.png)
![image](https://user-images.githubusercontent.com/11676384/56706757-b3998600-6748-11e9-8a96-5149628bb33b.png)

### What is actually happening?

![image](https://user-images.githubusercontent.com/11676384/56706697-84831480-6748-11e9-88cd-2ee302f3dd30.png)
![image](https://user-images.githubusercontent.com/11676384/56706918-50f4ba00-6749-11e9-9eb8-4647fca390d7.png)

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.6.5 |
| System | macOS 10.14.2 |
| Browser | Chrom 73 |

**Comment by afc163** [comment]
prefixCls 修改是要配合自定义样式的补充的，这样用样式肯定会丢。

**Comment by VoliBearCat** [comment]
我只想稍微修改一点样式, 我尝试加className, 但是在编辑时, className会丢失. @afc163

**Comment by VoliBearCat** [comment]
https://codesandbox.io/s/x950mzr7p
![image](https://user-images.githubusercontent.com/11676384/56707434-5d7a1200-674b-11e9-83ba-2a45dfab6969.png)
![image](https://user-images.githubusercontent.com/11676384/56707446-6a970100-674b-11e9-8097-2931f0704601.png)

**Comment by afc163** [comment]
这个是 bug。
