### ISSUE TITLE
typescript form break in 3.16.5

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design#16284]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yuquewebclipper/yuque-web-clipper](https://github.com/yuquewebclipper/yuque-web-clipper)

### Steps to reproduce
git clone code https://github.com/yuquewebclipper/yuque-web-clipper

see src/pages/preference/userList/index.tsx

git reset 79780e0 可以恢复到无错的版本。

### What is expected?
no error
### What is actually happening?
error

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.6 |
| System | macos |
| Browser | chrome |

**Comment by DiamondYuan** [comment]
![image](https://user-images.githubusercontent.com/9692408/56665733-2ff67f80-66dd-11e9-8cfa-583079d5caea.png)

**Comment by DiamondYuan** [comment]
https://github.com/ant-design/ant-design/pull/16242

**Comment by lbrevetti** [comment]
has this been addressed and released yet
I am also receiving the same error

**Comment by zombieJ** [comment]
Hi @DiamondYuan , could you help to test the #16242 pr code. Check whether it can help to resolve this?

**Comment by DiamondYuan** [comment]
> Hi @DiamondYuan , could you help to test the #16242 pr code. Check whether it can help to resolve this?

how to build ? `npm run dist`?

**Comment by DiamondYuan** [comment]
> Hi @DiamondYuan , could you help to test the #16242 pr code. Check whether it can help to resolve this?

i use npm link,it resolve my problem.

**Comment by zombieJ** [comment]
@DiamondYuan ， Thanks.

**Comment by sbusch** [comment]
PR fixed the problem for me, thanks 👍

**Comment by dfee** [comment]
For anyone else who comes my way, here is what I did to get it to work:
```sh
PROJECTS_ROOT="~/code"
APP_DIR="$PROJECTS_ROOT/myapp"
ANTD_DIR="$PROJECTS_ROOT/ant-design"

cd $APP_DIR
npm un antd
cd $PROJECTS_ROOT
git clone https://github.com/ant-design/ant-design.git
cd $ANTD_DIR
npm run compile
npm run dist
cd $APP_DIR
npm run link $ANTD_DIR
```

Hope that helps :)

And, here's to hoping that this gets pushed to a release soon... 🍺

**Comment by A-limon** [comment]
please release this new version ASAP.

**Comment by DiamondYuan** [comment]
we can use ts-ignore before release 


![image](https://user-images.githubusercontent.com/9692408/56788353-d05db880-6831-11e9-9ada-9e1409ed0cbf.png)

**Comment by DiamondYuan** [comment]
@A-limon 
@dfee 
@sbusch

**Comment by afc163** [comment]
Fixed in #16242

**Comment by TotooriaHyperion** [comment]
After this fix,

Explicit type are fixed, but type inference and wrappedComponentProps check failed.

Which cause so many bugs that type check is almost useless.

```typescript
import * as React from "react";
import Form, { FormComponentProps } from "antd/lib/form";

interface InnerProps extends FormComponentProps {
  a: number;
}
const Inner: React.FC<InnerProps> = () => {
  return <>inner</>;
};
const Wrapped = Form.create()(Inner); // Property a does not exist on...
const Wrapped1 = Form.create<InnerProps>()(Inner); // works

const Inner2: React.FC<InnerProps & { b: string }> = () => {
  return <>inner2</>;
};
const Wrapped2 = Form.create<InnerProps>()(Inner2); // works

const d = (
  <>
    <Wrapped />
    <Wrapped a={1} />
    <Wrapped1 />
    <Wrapped1 a={1} />
    <Wrapped2 />
    <Wrapped2 a={1} />
    <Wrapped2 a={1} b={1} />
  </>
);
d;
```
![image](https://user-images.githubusercontent.com/16434801/57449216-f3568680-728d-11e9-8805-4b9b2490427e.png)

**Comment by TotooriaHyperion** [comment]
1.The 2nd Wrapped should work on type inference, and the 1st shouldn't.
2.The 3rd Wrapped2 should work, and the 1st and 2nd should not.
and the error should on Form.create<InnerProps>()(Inner2);
saying Inner2 needs b: string, but InnerProps didn't provide.

**Comment by zombieJ** [comment]
@TotooriaHyperion , you should always pass [correct props](https://ant.design/components/form/#Using-in-TypeScript) with Form.create:
```tsx
const Wrapped = Form.create()(Inner); // Need provides <InnerProps>
const Wrapped1 = Form.create<InnerProps>()(Inner); // Correct
const Wrapped2 = Form.create<InnerProps>()(Inner2); // Should also pass as <InnerProps & { b: string }> since your Inner2 is `React.FC<InnerProps & { b: string }>`
```

**Comment by TotooriaHyperion** [comment]
> @TotooriaHyperion , you should always pass [correct props](https://ant.design/components/form/#Using-in-TypeScript) with Form.create:
> 
> ```ts
> const Wrapped = Form.create()(Inner); // Need provides <InnerProps>
> const Wrapped1 = Form.create<InnerProps>()(Inner); // Correct
> const Wrapped2 = Form.create<InnerProps>()(Inner2); // Should also pass as <InnerProps & { b: string }> since your Inner2 is `React.FC<InnerProps & { b: string }>`
> ```

I know, I mean type check for (Inner2) failed. It's pretty an edge case, the type check chain break between outer with inner. I'd never use different type between Inner2 and create's type because I never use HOC. I'm just point out this problem.

**Comment by alanhg** [comment]
> @A-limon
> @dfee
> @sbusch


You do this by bypassing the problem, and our best solution must not be done.
