### ISSUE TITLE
Modal confirm() 方法 OK 按钮 hover 效果无效，需要点击一下别的地方放上去才有效果

### ISSUE THREAD

**Issue by 894620576** [ant-design/ant-design#16297]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/#components-modal-demo-confirm](https://ant.design/components/modal-cn/#components-modal-demo-confirm)

### Steps to reproduce
modal -> confim

### What is expected?
必须要有效果啊

### What is actually happening?
没有hover效果

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | react  |
| System | windows |
| Browser | QQ |

**Comment by zombieJ** [comment]
Modal 弹窗时，确认按钮是 focus 状态。用于用户键盘操作确认，这不是 bug。

**Comment by susiwen8** [comment]
@zombieJ 其实这个用户体验可以提升一下，现在的逻辑是打开自动聚焦到确认按钮，所以他是foucs状态，点击其他地方，焦点就不在按钮上，之后按回车也没有反应。我提供了一个两全的方案，麻烦你看一下

**Comment by susiwen8** [comment]
https://github.com/ant-design/ant-design/pull/16305
@zombieJ

**Comment by zombieJ** [comment]
Update: 如果不需要默认 focus 设置 `autoFocusButton={null}` 即可。
