### ISSUE TITLE
Upload组件在QQ浏览器中点击无反应 - Upload component is disabled in QQ browser

### ISSUE THREAD

**Issue by meiyouqing** [ant-design/ant-design#16298]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#header](https://ant.design/components/upload-cn/#header)

### Steps to reproduce
在QQ浏览器打开 https://ant.design/components/upload-cn/#header

### What is expected?
可以正常上传
be able to upload successfully

### What is actually happening?
点击按钮无反应
No effect when i click the button

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.3.2 |
| System | macOs 10.14.2  |
| Browser | QQ浏览器 1.2.5 |

**Comment by zombieJ** [comment]
非主流浏览器目前没有精力维护，如果有兴趣欢迎帮忙排查~

**Comment by meiyouqing** [comment]
@zombieJ QQ浏览器确实是非主流，但要命的是微信内置的是QQ浏览器，你能说微信不主流吗？

**Comment by meiyouqing** [comment]
qq浏览器真的烂啊，我用<input type='file' />也是不支持的💔
