### ISSUE TITLE
react+webpack4+ts搭建的多页面应用 如何按需引入antDesign 不eject的情况下

### ISSUE THREAD

**Issue by create13** [ant-design/ant-design#16294]
webpack.config.js 文件在根目录创建 文件内容如下
const webpack = require('webpack');
const glob = require('glob');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
 
const webpackConfig = {
    mode:'development',
    entry: {},
    output:{
        path:path.resolve(__dirname, './dist/'),
        filename:'[name]/[name].[chunkhash:6].js'
    },
    //设置开发者工具的端口号,不设置则默认为8080端口
    devServer: {
        inline: true,
        port: 8082,
        compress: true
    },
    module:{
        rules:[
            {
                test:/\.(js|jsx)$/,
                exclude:/node_modules/,
                use: [ 
                    {
                        loader:'babel-loader',
                        options:{
                            presets:['es2015','react'],
                            plugins: [['import', { "libraryName": "antd", "style": true }]]//--通过bable-plugin-import依赖 实现antd按需加载
                        },
                    }
                ]
            },
            {
                test: /\.(scss|sass|css)$/,
                loader: ExtractTextPlugin.extract({fallback: "style-loader", use: 'css-loader'}),
            },
            {
                test: /\.less?$/,
                use:[ 'style-loader','css-loader','less-loader']
            },
            {
                test: /\.tsx?$/,
                loader: 'ts-loader',
                exclude: /node_modules/
            }
            
        ]
    },
    resolve: {
        extensions: ['.js', '.jsx','.ts','.tsx', '.scss','.json','.css'], //后缀名自动补全
    },
    plugins: [
        new ExtractTextPlugin("[name]/[name].[chunkhash:6].css"),
        new CleanWebpackPlugin(
            ['dist'],
            {
                root: __dirname,　　　　　　　
                verbose:  true,        　　　　　　　　　　
                dry:      false        　　　　　　　　　　
            }
        )
    ],
};
 
// 获取指定路径下的入口文件
function getEntries(globPath) {
    const files = glob.sync(globPath),
    entries = {};
    files.forEach(function(filepath) {
        const split = filepath.split('/');
        const name = split[split.length - 2];
        entries[name] = './' + filepath;
    });
    return entries;
}
       
const entries = getEntries('src/pages/*/index.tsx');
Object.keys(entries).forEach(function(name) {
    webpackConfig.entry[name] = entries[name];
    const plugin = new HtmlWebpackPlugin({
       filename: name + '/' + name + '.html',
       template: './public/index.html',
       inject: true,
       chunks: [name]
    });
    webpackConfig.plugins.push(plugin);
})
module.exports = webpackConfig;
也试过在.babelrc和package.json上配置过  按需引入依然不生效 无法按照官网说的create-react-app和typescript上引入  查资料看说eject情况下 配置webpack相关的三个文件plugins: [['import', { "libraryName": "antd", "style": true }]] 可以用 但是此举不可逆 所以想问一下还有其他方案可以解决这个问题么 谢谢

**Comment by ferried** [comment]
oh shit
