### ISSUE TITLE
Calendar 在FireFox 下月份选择宽度问题。

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#16299]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rwjwk3pkxo)

### Steps to reproduce
界面显示问题

### What is expected?
正常显示

### What is actually happening?
界面显示问题

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | React16.9.0 |
| System | win10 |
| Browser | 66.0.2 |

**Comment by afc163** [comment]
『界面显示问题』

What is the problem?

<img width="666" alt="image" src="https://user-images.githubusercontent.com/507615/56718364-2cacd380-6771-11e9-98bc-cfd603a461fc.png">

**Comment by zhang504988670** [comment]
在中文的显示下。
https://codesandbox.io/s/wnmo51owvk
![image](https://user-images.githubusercontent.com/18161513/56718704-d7bd8d00-6771-11e9-8b0f-c158e1d63d05.png)

**Comment by zombieJ** [comment]
滚动条问题，得加宽一点……
