### ISSUE TITLE
Table cache filteredValue can't be cleared when clicking  the filterDropDown reset button one time(2 times is OK)

### ISSUE THREAD

**Issue by unknownHzy** [ant-design/ant-design#16308]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2ovv15v1op)

### Steps to reproduce
1. click Gender filter dropDown
2. input 'male'
3. click Search button, table was filtered, and the Gender filter dropDown is blue color
4. click the Gender filter dropDown again
5. click the Reset button, table was reset , and the Gender filter dropDown is still blue color
6. click the Gender filter dropDown again
7.  click the Reset button again, the input box was reset

### What is expected?
When clicking reset button after table has been filtered,  the table should reload with no filter condition, and the filter dropDown should be cleared.

### What is actually happening?
when clicking the reset, the filter can't be cleared. clicking again, it was cleared.

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | react@16.8.6  |
| System | Ubuntu 16.04.5 LTS |
| Browser | Version 73.0.3683.86 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit) |

---
Another issue: In my app(not the linked demo), after clicking the reset button, both  the table and input box were not reset(will reload, but table data was not reset,). 
I can't be reproduce this case, the demo table will reload the the data.  Pls check this case.

**Comment by zombieJ** [comment]
Your code use `sessionStorage` to cache the filterValue which makes `filteredValue` as controlled value. On the filter update, the props of `columns` still get the column with `filteredValue` makes the `selectedKeys` locked.

```jsx
genderCol = Object.assign(gender, { filteredValue: [defaultGender] });
```
