### ISSUE TITLE
select onSearch第一次促发查询出列表数据后，选中一个option，然后重新输入查询，这次没有查出数据， 此时失去焦点期望select为空，但实际上却是第一次选中的值

### ISSUE THREAD

**Issue by hualinIT** [ant-design/ant-design#16310]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/embed/n94yx206rl](https://codesandbox.io/embed/n94yx206rl)

### Steps to reproduce
1. select onSearch 输入查询条件，查询出数据， 选中一条数据的option
2. 此时调用接口，返回的数据为空数组， 没有option
3. select框此时失去焦点， 发现select框的值恢复成了第一次选中的值

### What is expected?
期望 步骤3的值为空

### What is actually happening?
实际结果恢复成步骤1选中的值了

| Environment | Info |
|---|---|
| antd | 2.13.14 |
| React | 16.2.0 |
| System | mac |
| Browser | 73.0.3683.103 |

**Comment by hualinIT** [comment]
步骤2，此时调用接口，返回的数据为空数组， 没有option

**Comment by XianZhengquan** [comment]
我的也是这个情况

**Comment by XianZhengquan** [comment]
repo: https://codesandbox.io/embed/xvox9o3zlz
输入 `a` 等待 1S，选择 a
再输入其他的，然后失焦

**Comment by zombieJ** [comment]
value 是受控属性。如果设置了 value，无论是否 Option 里是否有这个值都会展示它。

**Comment by hualinIT** [comment]
@ant-design-bot   demo案列 [](url) https://codesandbox.io/embed/n94yx206rl

**Comment by hualinIT** [comment]
> value 是受控属性。如果设置了 value，无论是否 Option 里是否有这个值都会展示它。它就是 Select 的值。

@zombieJ  要怎么处理它使它失去焦点为空呢，而不是恢复成以前的选中的值 [](url)  https://codesandbox.io/embed/xvox9o3zlz

**Comment by afc163** [comment]
```diff
  function handleSearch(val) {
    if (val === "a") {
      setTimeout(() => {
        setOptions([{ label: "a", value: "a" }]);
      }, 1000);
    } else {
      setOptions([]);
+     setValue(undefined);
    }
  }
```

https://codesandbox.io/s/n94yx206rl
