### ISSUE TITLE
Menu/Submenu with react-beautiful-dnd doesn't work

### ISSUE THREAD

**Issue by chaseWillden** [ant-design/ant-design#16319]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/2vq0v1jw1y)

### Steps to reproduce
Add react-beautiful-dnd and try to make the menu/submenu drag and droppable

### What is expected?
Should be able to drag and drop

### What is actually happening?
Since the direct child isn't a Menu.Item or Menu.SubMenu, it doesn't work

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.6 |
| System | Mac |
| Browser | Chrome 73.0.3683.103  |

**Comment by zombieJ** [comment]
Menu internal pass additional props to SubMenu. You should also pass it if you need wrap it. I'm not sure how `react-beautiful-dnd` works, but the props should not miss.
