### ISSUE TITLE
multi-step in modal

### ISSUE THREAD

**Issue by kalmndo** [ant-design/ant-design#16318]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://4zxzpnrok0.codesandbox.io/)

### Steps to reproduce
currently i wanna make multi-step form in a Modal.
but i think ant design doesn't support for it.

### What is expected?
because the Modal itself has its own button, that cant remove though.

### What is actually happening?
maybe you guys know how to remove the Button component from it and use conditional Button

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | react hooks |
| System | latest |
| Browser | latest |

---

**Comment by susiwen8** [comment]
@kalmndo it this what you want?
https://ant.design/components/modal/#components-modal-demo-footer

**Comment by afc163** [comment]
`footer={null}`
