### ISSUE TITLE
增加站点白屏加载文字和动画

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1632]
现在是一个灰页面，略丑。

**Comment by afc163** [comment]
改成白色，中间放一个 logo 旋转。类似 http://09x.ant.design/ 中间的加载动画。

**Comment by jljsj33** [comment]
不要白屏，，，banner黑的唉。。。。重新设计个load

**Comment by afc163** [comment]
其他页面是白底的，还是白的好。

**Comment by jljsj33** [comment]
哦，，全站的啊。。对了，，motion那我也去整个。。

**Comment by benjycui** [comment]
需要设计？

**Comment by jljsj33** [comment]
我操，，这也太丑了吧。。。用０.９的。。。。
