### ISSUE TITLE
core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#16325]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

装包时报警告：
```
warning antd > create-react-class > fbjs > core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
```

指示 `antd` 依赖的 `create-react-class` 依赖的 `fbjs` 依赖了过时停止维护的 `core-js`。

![image](https://user-images.githubusercontent.com/10294977/56781076-6256c880-6814-11e9-977e-1e8959548c37.png)

**Comment by zombieJ** [comment]
这个应该没用了，我删掉它去。
cc @afc163

**Comment by gamenic-babin** [comment]
yeah i need solution too can't run the app for current project due to this ..any solution ?

**Comment by jinliming2** [comment]
`antd@3.18.2` 还是有这个问题，只不过换了个包：
```
warning antd > rc-tree-select > rc-trigger > rc-animate > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
```
![image](https://user-images.githubusercontent.com/10294977/58144802-790d0580-7c82-11e9-9cf4-0e20a5bf1f06.png)

**Comment by afc163** [comment]
https://github.com/react-component/animate/issues/53

**Comment by yoyo837** [comment]
如果项目使用core-js@3, 由于antd的rc-*依赖的还是core-js@2，所以会有两份打入bundle。

**Comment by jinliming2** [comment]
（介意的不是 bundle size 而是 warning 🤣
