### ISSUE TITLE
当PageHeader和Typography一起使用的时候，Typography Title的样式不对

### ISSUE THREAD

**Issue by depkg** [ant-design/ant-design#16326]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wz24po35k)

### Steps to reproduce
直接打开浏览器

### What is expected?
Typography line-height 样式 与 backicon 对齐

### What is actually happening?
未对齐

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 最新 |
| System | mac |
| Browser | chrome 最新 |

**Comment by zombieJ** [comment]
Typography 的 Title 是文档排版标题。和 PageHeader 的 title 不是一个概念。
此外，PageHeader 的 title 是自带样式的，如果希望使用自定义 Node，则需要自己来手工设置一下样式。
