### ISSUE TITLE
InputNumber property width override

### ISSUE THREAD

**Issue by lucasbastianik** [ant-design/ant-design#16320]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/NmegjP](https://codepen.io/anon/pen/NmegjP)

### Steps to reproduce
Just use a `InputNumber`.

### What is expected?
Only one `width` attribute of `.ant-input-number`.

### What is actually happening?
Have 2 widths: one with 100% and another overriding the first with 90px.

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.5 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
It is not a bug, we are using less mixin that width has been defined in `.input`.

https://github.com/ant-design/ant-design/blob/cb2e7280ec07fffd2abcb57a49e8e920831bf7a8/components/input-number/style/index.less#L9
