### ISSUE TITLE
(Feature request) Floating label input boxes

### ISSUE THREAD

**Issue by leelakrishnak** [ant-design/ant-design#16323]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Floating input boxes are everywhere nowadays , it would be nice to have floating label input boxes in the ant design library

Examples:-
https://www.npmjs.com/package/react-floating-label-input
https://medium.com/@ilonacodes/creating-floating-label-placeholder-for-input-with-react-b912233b7005

### What does the proposed API look like?
<Input labelType="float" />

**Comment by leelakrishnak** [comment]
<img width="724" alt="Screen Shot 2019-04-25 at 4 53 38 PM" src="https://user-images.githubusercontent.com/6565989/56775719-39372900-677d-11e9-921f-48f6a8b37868.png">

**Comment by afc163** [comment]
Sorry, it is not in our design specification.

**Comment by avalanche1** [comment]
I think this should be reopened.
What would it take to change your design spec? Especially in the wake of the coming Antd 4.0.

**Comment by Vbboi24** [comment]
Yes, This is something the team can consider. Would probably be another reason why the world loves antd.

**Comment by AvneeshD** [comment]
Anytime soon?

**Comment by RixBai** [comment]
@afc163 Is _Float Label Input_ not developed yet?

**Comment by JesperWe** [comment]
@afc163 said:

> Sorry, it is not in our design specification.

When you are developing a library used by sooo many people, and you actively promote it for use in other peoples project that reach far beyond your "design specification", it comes across as rather childish to close a request for a very popular feature with such a remark.

**Comment by nikhil-mahirrao** [comment]
I have created one component called **FloatLabel** which can mock this behavior of floating labels like material UI.

You can check this code sandbox [link](https://codesandbox.io/s/antd-float-label-wrx4d)

**Comment by avalanche1** [comment]
@nikhil-mahirrao cheers! quite elegant :))
@afc163 any chance of this being baked into the framework?

**Comment by Gibbo3771** [comment]
Yeah it's a bit silly to disregards this feature. It's a nice way to break up the UI and save space.
Right now with the current design, if you want a clean form with labels, you have to align them to the left and that's just....old as shit.

**Comment by sowka1995** [comment]
> I have created one component called **FloatLabel** which can mock this behavior of floating labels like material UI.
> 
> Just take look this **FloatLabel** component,
> 
> ```
> import React, { useState } from "react";
> 
> import "./index.css";
> 
> const FloatLabel = props => {
>   const [focus, setFocus] = useState(false);
>   const { children, label, value } = props;
> 
>   const labelClass = focus || value ? "label label-float" : "label";
> 
>   return (
>     <div
>       className="float-label"
>       onBlur={() => setFocus(false)}
>       onFocus={() => setFocus(true)}
>     >
>       {children}
>       <label className={labelClass}>{label}</label>
>     </div>
>   );
> };
> 
> export default FloatLabel;
> ```
> 
> now you can wrap your antd input with **FloatLabel** component like this,
> 
> ```
> <FloatLabel label="First Name" name="firstName" value={firstName}>
>   <Input value={firstName} onChange={e => setFirstName(e.target.value)} />
> </FloatLabel>
> ```
> 
> You can check this [**code sandbox link**](https://codesandbox.io/s/antd-float-label-wrx4d)
It looks very pretty, nice work!
Can we use this for an existing Form.Item elements?

**Comment by adamerose** [comment]
@afc163 Please reconsider modifying the design spec to include floating labels in Antd. People keep opening duplicates of this issue and getting many upvotes every time.


For everyone who wants, here is a component to add floating labels in Antd
https://codesandbox.io/s/antd-float-label-wrx4d
https://stackoverflow.com/a/61474970/3620725

And here's my modified version using styled-components

```JavaScript
import React, { useState } from "react";
import styled from 'styled-components'

const Container = styled.div`
  position: relative;
  margin-bottom: 12px;

  &>.ant-input {
    padding: 16px 12px 4px 11px;
  }

  &>.ant-select .ant-select-selector {
    padding: 16px 10px 4px 11px;
  }

  &>.ant-select-single:not(.ant-select-customize-input) .ant-select-selector {
    padding: 16px 10px 4px 11px;
    height: 48px;
  }

  &>.ant-select-single .ant-select-selector .ant-select-selection-search {
    top: 16px;
  }

`

const Label = styled.label`
  font-size: 12px;
  font-weight: normal;
  position: absolute;
  pointer-events: none;
  left: 12px;
  top: 12px;
  transition: 0.2s ease all;
  ${({ float }) => float && 'top: 6px; font-size: 10px;'}
`
const FloatLabel = props => {
  const [focus, setFocus] = useState(false);
  const { children, label, value } = props;

  return (
    <Container
      onBlur={() => setFocus(false)}
      onFocus={() => setFocus(true)}
    >
      {children}
      <Label float={focus || (value && value.length !== 0)}>{label}</Label>
    </Container>
  );
};

export default FloatLabel;
```

**Comment by Rodrigo001-de** [comment]
thank's

Em sáb, 4 de jul de 2020 16:55, Adam <notifications@github.com> escreveu:

**Comment by arthurpankiewicz** [comment]
> Sorry, it is not in our design specification.

Maybe the design spec should be updated something more modern then?

**Comment by rohit-sourcefuse** [comment]
> @afc163 Please reconsider modifying the design spec to include floating labels in Antd. People keep opening duplicates of this issue and getting many upvotes every time.
> 
> For everyone who wants, here is a component to add floating labels in Antd
> https://codesandbox.io/s/antd-float-label-wrx4d
> https://stackoverflow.com/a/61474970/3620725
> 
> And here's my modified version using styled-components
> 
> ```js
> import React, { useState } from "react";
> import styled from 'styled-components'
> 
> const Container = styled.div`
>   position: relative;
>   margin-bottom: 12px;
> 
>   &>.ant-input {
>     padding: 16px 12px 4px 11px;
>   }
> 
>   &>.ant-select .ant-select-selector {
>     padding: 16px 10px 4px 11px;
>   }
> 
>   &>.ant-select-single:not(.ant-select-customize-input) .ant-select-selector {
>     padding: 16px 10px 4px 11px;
>     height: 48px;
>   }
> 
>   &>.ant-select-single .ant-select-selector .ant-select-selection-search {
>     top: 16px;
>   }
> 
> `
> 
> const Label = styled.label`
>   font-size: 12px;
>   font-weight: normal;
>   position: absolute;
>   pointer-events: none;
>   left: 12px;
>   top: 12px;
>   transition: 0.2s ease all;
>   ${({ float }) => float && 'top: 6px; font-size: 10px;'}
> `
> const FloatLabel = props => {
>   const [focus, setFocus] = useState(false);
>   const { children, label, value } = props;
> 
>   return (
>     <Container
>       onBlur={() => setFocus(false)}
>       onFocus={() => setFocus(true)}
>     >
>       {children}
>       <Label float={focus || (value && value.length !== 0)}>{label}</Label>
>     </Container>
>   );
> };
> 
> export default FloatLabel;
> ```

Cool work, just one issue notable to add required and rule on this.

` <Form.Item
            name="email"
            id="loginEmail"
            rules={[{ required: true, message: 'Please input your e-mail address' }]}
          >
            <FloatLabel
              label={formatMessage({ id: 'login.email' })}
              name="email"
              id="loginEmail"
              rules={[{ required: true, message: 'Please input your e-mail address' }]}
            >
              <Input
                size="large"
                placeholder={formatMessage({ id: 'login.email' })}
              />
            </FloatLabel>`

needed something like this on FloatLabel : 
`  rules={[{ required: true, message: 'Please input your e-mail address' }]}`

**Comment by eduardobalbo** [comment]
Hello everyone, is this idea not a part of the library yet?

**Comment by nameishari** [comment]
I wrote a medium post, on how to create a floatin-label using antd. If you are interested, please have a look here - https://nameishari.medium.com/how-to-build-a-floating-label-input-field-using-react-and-ant-design-antd-52d797b65f74

**Comment by vbogutskii-sh** [comment]
I made an example based on some previous https://codesandbox.io/s/antd-float-label-forked-k8p00?file=/Example.js

**Comment by LuckyArdhika** [comment]
should i migrate to MUI?

**Comment by aalirezamoradii** [comment]
Please added

**Comment by robertocerdasilva** [comment]
thanks @razr001  !! 👍 But this not working with Form.setFieldsValue

**Comment by razr001** [comment]
@robertocerdasilva fixed please update latest version. Thanks
