### ISSUE TITLE
当Table无数据的时候，底部多了一条border

### ISSUE THREAD

**Issue by depkg** [ant-design/ant-design#16327]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/empty-cn/#components-empty-demo-config-provider](https://ant.design/components/empty-cn/#components-empty-demo-config-provider)

### Steps to reproduce
打开连接可见

### What is expected?
不显示底部 border

把 `.ant-table-placeholder` class 里的 `border-bottom: 1px solid #e8e8e8; ` 移到 `.ant-table-bordered.ant-table-empty .ant-table-placeholder` class 里？

### What is actually happening?
底部显示 border

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | latest |
| System | mac |
| Browser | chrome latest |

**Comment by afc163** [comment]
这是合理的，表格设计上是始终有底边框的。
