### ISSUE TITLE
Transfer 穿梭框 两栏可以支持不同的数据源吗

### ISSUE THREAD

**Issue by li305263** [ant-design/ant-design#16329]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在有一个需求是 左边 source 数据跟右边target数据,不是同一个数据来源,
右边的只做保存数据, 左边的可以有不同的的数据来源 都可以保存在右边上

### What does the proposed API look like?
无

**Comment by afc163** [comment]
Transfer 本质上是一个多选框，有多个数据来源自行整合一下数据结构就可以了。

**Comment by li305263** [comment]
> 转移本质上是一个多选框，有多个数据来源自行整合一下数据结构就可以了。

左边数据是多个数据来源 ,但是右边数据只做保存,切换数据源 右边不会清空,左边更新
现在右边只能保存单独数据源的数据 不能整合一起保存

**Comment by PearpearS** [comment]
这个问题解决了吗？我也遇到这个需求

**Comment by PearpearS** [comment]
很头疼

**Comment by li305263** [comment]
> 这个问题解决了吗？我也遇到这个需求

解决了. 我是改了这个组件, 把它抽离出来, 再加一个props属性 自己处理

**Comment by PearpearS** [comment]
请问你是怎么抽离的，可以指导下吗

**Comment by PearpearS** [comment]
额，公司需求改了，不需要这么做了

**Comment by youxiaodao** [comment]
> 
> 
> Transfer 本质上是一个多选框，有多个数据来源自行整合一下数据结构就可以了。

如果要保存下右边已选中的数据源，该怎么整合数据结构，尝试了使用state去保存，却不能成功，可以提供一个demo吗？万分感谢！
