### ISSUE TITLE
tabs中renderTabBar使用报错react-dom.production.min.js:110 Error: Minified React error #130;

### ISSUE THREAD

**Issue by yichenw7** [ant-design/ant-design#16336]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
创建Tabs增加renderTabBar={props => <Tabs.DefaultTabBar {...props} />}

### What is expected?
无报错，可进行tabs bar 二次编辑

### What is actually happening?
报错react-dom.production.min.js:110 Error: Minified React error #130;

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | React v16.8.6 |
| System | windows7 |
| Browser | chrome |

**Comment by yichenw7** [comment]
你好，这样的方式可行吗
https://codesandbox.io/s/x90n204ww

**Comment by afc163** [comment]
https://codesandbox.io/s/93l9q4v4xy

**Comment by yichenw7** [comment]
谢谢，问题已经自行解决，此issue可关闭
(props, DefaultTabBar) => <DefaultTabBar {...props}  />
