### ISSUE TITLE
Table expandRowByClick combined expandIconAsCell and children in the data

### ISSUE THREAD

**Issue by ditiem** [ant-design/ant-design#16337]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/MRZRQG?&editable=true&editors=001](https://codepen.io/anon/pen/MRZRQG?&editable=true&editors=001)

### Steps to reproduce
You can click on a row and the row will be expanded, but the icon (the plus inside the square) is not shown.

### What is expected?
http://react-component.github.io/table/examples/expandedRowRender.html

### What is actually happening?
In this file 
```
https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx
```

In this function:
```
renderTable = (
    prefixCls: string,
    renderEmpty: RenderEmptyHandler,
    dropdownPrefixCls: string,
    contextLocale: TableLocale,
  ) => {
    const { style, className, showHeader, locale, ...restProps } = this.props;
    const data = this.getCurrentPageData();
    const expandIconAsCell = this.props.expandedRowRender && this.props.expandIconAsCell !== false;
```

expandIconAsCell is not correctly past to RcTable as expandedRowRender is not a property when using `tree data` (see https://ant.design/components/table/#components-table-demo-expand-children )

The condition hast to be something like:
``` 
   const expandIconAsCell = (this.props.expandedRowRender || isTreeData) && this.props.expandIconAsCell !== false;
```

where isTreeData is determined by check if there is a "children" field in any of the data elements.

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.4 |
| System | Mac OSX |
| Browser | chrome |

---
I did modify my local copy to directly pass the `expandIconAsCell` and it works like in RcTable.

**Comment by zombieJ** [comment]
antd is wrap of `rc-table` which means api is not all the same. Please ref the antd demo to realize the expand function instead: https://ant.design/components/table/#components-table-demo-expand

**Comment by ditiem** [comment]
@zombieJ  You did completely miss the point.

When you provide tree-data to the table (that means there is a children field in the data object, and you can read it from the same link you sent to me that is the same I provided in the description), antd deals with the expand by itself. This works pretty well. But there is a functionality that is really useful and it is that when you click on the row it expands, rather than having to click on the expand icon. For this, `expandRowByClick` is available in RcTable.

By passing this property, the thing works as expected, but the "expandable icon" is deleted from the list. To avoid this, `expandIconAsCell` has to be true.

But you guys forgot the case of using tree-data when deciding whether to pass or not `expandIconAsCell` to the RcTable or not.

**Comment by ztplz** [comment]
It seems to have this feature before, but it was deprecated in 3.0.

**Comment by megawac** [comment]
:+1: I'd like to show the expand icon with `expandRowByClick` set to true
