### ISSUE TITLE
希望增加：Table在使用服务器端排序时，可以有参数支持多列排序

### ISSUE THREAD

**Issue by Long-Dress** [ant-design/ant-design#16338]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
多列组合排序

### What does the proposed API look like?
以下两种方案：
1、提供排序multiple参数，如果为true则支持多列组合排序（仅支持服务端多列也可以，即提供样式与交互）；
2、sortOrder参数能完全控制样式，同时表格onChange函数的sorter参数在排序取消的情况下也能有值。

**Comment by afc163** [comment]
Duplicate of #10946
