### ISSUE TITLE
DatePicker时区问题

### ISSUE THREAD

**Issue by gp0014** [ant-design/ant-design#16333]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ox8ny76y0q?fontsize=14)

### Steps to reproduce
在DatePicker里面选择时间，onChange里面获得的moment对象始终是utc时区的。

### What is expected?
moment设置locale后，DatePicker中选的时间应该是该时区的时间

### What is actually happening?
moment设置locale后，DatePicker中选的时间是utc时间

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.7.0 |
| System | mac |
| Browser | chrome 73.0.3683.103 |

**Comment by afc163** [comment]
You need https://ant.design/components/locale-provider-cn/

**Comment by gp0014** [comment]
加入LocaleProvider后还是有同样的问题。

**Comment by afc163** [comment]
来个 codesandbox，写一下期待的结果和实际看到的结果。

**Comment by gp0014** [comment]
https://codesandbox.io/s/ox8ny76y0q?fontsize=14

**Comment by afc163** [comment]
看不出来有啥问题，你期待的结果和实际看到的结果是啥呢？

**Comment by gp0014** [comment]
补充一下
期望结果是，设置了locale为zh-cn以后，不管我怎么选日期时间，moment对象都应该是东八区的时间，
实际结果是，设置了locale为zh-cn以后，刚开始直接选择日期时间以后点“确定”按钮得到的moment对象是对的（东八区）。但是点了“此刻”以后，moment的时区就变成utc的了。

**Comment by afc163** [comment]
发现了一些不同，点『此刻』和点『确定』的属性略与不同。

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/507615/56798727-f2633500-6849-11e9-9485-ef66a3b8166d.png">

**Comment by gp0014** [comment]
注意“_isUTC”字段

**Comment by zombieJ** [comment]
`_isUTC` 不是代表 UTC 时间而是是否基于 utc 的 offset，判断是否为 UTC 是 `time.isUTC()`:
https://codesandbox.io/s/zl876l3n5x

ref: https://github.com/moment/moment/blob/master/src/lib/units/offset.js#L124

**Comment by afc163** [comment]
两种交互是不是应该统一返回结果？

**Comment by gp0014** [comment]
好的，谢谢各位
