### ISSUE TITLE
TreeNode的title属性渲染Tooltip报错的问题

### ISSUE THREAD

**Issue by jefybai** [ant-design/ant-design#1633]
```
 <Tree>
                <TreeNode className="first-level" title={
                    <div>
                        <span>什么是JAVA</span><span className="control">
                        <Tooltip placement="bottom" title="我是弹窗">
                            <span href="#">。。。</span>
                        </Tooltip>
                        <span>布置</span></span>
                    </div>
                    } key="1">
</Tree>
```

这样的结构，当鼠标放上去显示tooltip的时候会报出
Trigger.js:119 Uncaught TypeError: this.isMounted is not a function
这样的错误，但是不影响使用

**Comment by warmhug** [comment]
tree的TreeNode给title返回Tooltip报错，试试没发现。给个demo吧

**Comment by jefybai** [comment]
`import React, { Component, PropTypes } from 'react';

import {Tree, Tooltip,Table  } from 'antd';
const TreeNode = Tree.TreeNode;


class TestPage extends Component {
    constructor(props, context) {
        super(props, context)
    }

    render() {
        return (
            <Tree>
                <TreeNode className="first-level" title={
                    <div>
                        <span>什么是JAVA</span><span className="control">
                        <Tooltip placement="bottom" title="我是弹窗">
                            <span href="#">。。。</span>
                        </Tooltip>
                        <span>布置</span></span>
                    </div>} key="1">
                    </TreeNode>
            </Tree>
        )
    }

}

export default TestPage`

你能否把这个模块加到你的项目里面运行一下啊？

**Comment by warmhug** [comment]
麻烦用 `antd-1.0.0`版本 运行下看看有没问题

**Comment by jefybai** [comment]
为了这个BUG 我专门从v0.12.12升级到 v1.0.0还是有这个问题；

**Comment by warmhug** [comment]
http://codepen.io/anon/pen/reRGbG?editors=001#anon-login  我改下，没发现问题？

**Comment by jefybai** [comment]
不知道是不是，打包导致的错误？   codepen上面的运行的结果跟我现在不一样，现在我运行了点击树的结点，ant.js竟然在控制台还会打印出事件？而codepen上面没有
antd.js:45604 Uncaught TypeError: this.isMounted is not a function
onSelect 
SyntheticMouseEvent {dispatchConfig: Object, dispatchMarker: ".0.1.$=1$/tchome/techcenter/teching.$/tchome/techc….1:$0.$/tchome/techcenter/teching.1.1.0.$1/=1$1.2", nativeEvent: MouseEvent, target: a.ant-tree-node-selected, currentTarget: a.ant-tree-node-selected…} 123
antd.js:45086 onClick

**Comment by jefybai** [comment]
不知道是不是，打包导致的错误？ codepen上面的运行的结果跟我现在不一样，现在我运行了点击树的结点，ant.js竟然在控制台还会打印出事件？而codepen上面没有
antd.js:45604 Uncaught TypeError: this.isMounted is not a function
onSelect 
SyntheticMouseEvent {dispatchConfig: Object, dispatchMarker: ".0.1.$=1$/tchome/techcenter/teching.$/tchome/techc….1:$0.$/tchome/techcenter/teching.1.1.0.$1/=1$1.2", nativeEvent: MouseEvent, target: a.ant-tree-node-selected, currentTarget: a.ant-tree-node-selected…} 123
antd.js:45086 onClick @warmhug

**Comment by warmhug** [comment]
打包导致的错误？ 重新打包下看看？

**Comment by jefybai** [comment]
我自己整吧
