### ISSUE TITLE
I can´t get the type name from antd components

### ISSUE THREAD

**Issue by famadori** [ant-design/ant-design#16346]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w505nnql7)

### Steps to reproduce
To create a simple component and get the type.name from production build.

### What is expected?
I whant to get the type.name from components at production build. I created the same sample from sandbox in my production environment https://www.ginte.com.br/ and you can see at the console that return 'e' where in the sandbox return 'Button'

### What is actually happening?
The type name in production build with yarn build or npm build was equals 't' minified.

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 73.0.3683.103 |

**Comment by yesmeck** [comment]
It's expected behavior, don't rely on component type.

**Comment by famadori** [comment]
How can i  know whats is the type of components?

**Comment by yesmeck** [comment]
You can compare element type to the component directly. But still, don't recommend rely on component type.

```javascript
import { Button } from 'antd';

element.type === Button;
```
