### ISSUE TITLE
List component renders list items for all pages into current page if data for current page is not available in dataSource.

### ISSUE THREAD

**Issue by itsakt** [ant-design/ant-design#16349]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9310zn0n2y)

### Steps to reproduce
Click on 3rd pagination item

### What is expected?
Current page should be empty.

### What is actually happening?
All list items for all pages are being renders at once.

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | Win10 |
| Browser | Firefox Latest |

---
In components/list/index.tsx line 235 

````
let splitDataSource = [...dataSource];
````

I think splitDataSource should be initialized with an empty array and set it to dataSource only if pagination is disabled.

**Comment by MrHeer** [comment]
I think dataSource should be spliced when dataSource.length greater than paginationProps.pageSize
[Source Code](https://sourcegraph.com/github.com/ant-design/ant-design@master/-/blob/components/list/index.tsx#L239)
```diff
if (pagination) {
-  if (dataSource.length > (paginationProps.current - 1) * paginationProps.pageSize) {
+  if (dataSource.length > paginationProps.pageSize) {
    splitDataSource = [...dataSource].splice(
      (paginationProps.current - 1) * paginationProps.pageSize,
      paginationProps.pageSize,
    );
  }
}
```

**Comment by zombieJ** [comment]
It's by design. If current dataSource length is less than `total` config. List or Table will tread it as ajax mode and fully render list into view.
ref: https://github.com/ant-design/ant-design/blob/master/components/list/index.tsx#L239  https://github.com/ant-design/ant-design/blob/master/components/table/Table.tsx#L1056
