### ISSUE TITLE
Table组件 Column的align

### ISSUE THREAD

**Issue by sunguoxing0628** [ant-design/ant-design#16347]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/wk04r016q8)

### Steps to reproduce
1.创建'Table'对象
2.设置'Columns'参数'align'为'center'

```
import React from "react";
import ReactDOM from "react-dom";
import { version, Table } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const columns = [
  {dataIndex: 'name', title: '名称', align: 'center' }
];

const data = [
  {name: '测试1'}
];

ReactDOM.render(
  <div className="App">
    <h1>Please fork this codesandbox to reproduce your issue.</h1>
    <div>Current antd version: {version}</div>
    <div style={{ marginTop: "16px" }}>
      <Table columns={columns} dataSource={data} />
    </div>
  </div>,
  document.getElementById("root")
);
```
![image](https://user-images.githubusercontent.com/27573161/56845502-d5d00700-68f4-11e9-8783-fb72bbd85bc6.png)

### What is expected?
内容居中

### What is actually happening?
内容和列标题同时居中，组件介绍[Columns](http://ant.design/components/table-cn/#Column)的`align` 是设置列内容的对齐方式，不应该触发列标题的样式改变

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | macOS 10.14.4 |
| Browser | Google Chrome 73.0.3683.103 |

**Comment by afc163** [comment]
API 描述可能有点误导，是包括整列所有内容的。
