### ISSUE TITLE
upload的beforeUpload在一次拖拽多张或者点击上传多张会触发多次, 是不是触发一次比较合理,或者在beforeupload之前设置一个钩子每次操作触发一次

### ISSUE THREAD

**Issue by yisayu** [ant-design/ant-design#16355]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为我是通过自己处理上传逻辑的,所以beforeupload只是为了做一个图片张数限制, 但是当beforeupload多次触发,导致限制起来会很麻烦, 直接通过filelist限制是否超出,这样会多次提示, 如果通过每次触发beforeupload就状态的图片数量 1 的方式, 因为setState是一个异步,在下一次beforeUpload触发之前可能状态还没设置进去,所以也很难实现 ,所以我在想是不是按照每拖拽或者点击上传一次就触发一次beforeupload比较合理,如果不是,应该怎样实现比较好,请教各位大佬,感谢(因为有点多,怕用英文表达不清,勿怪)

### What does the proposed API look like?
beforeUpload一次上传多文件只上传一次或在beforeupload之前设置一个钩子每次操作触发一次

**Comment by afc163** [comment]
目前还不支持多文件单次上传。

可以关注 #8579

**Comment by njzydark** [comment]
https://github.com/ant-design/ant-design/issues/8579#issuecomment-619063013

**Comment by njzydark** [comment]
提了一个pr，希望加一个beforeMultipleUpload，与之前不同的是只会触发一次
https://github.com/react-component/upload/pull/243

**Comment by return-com** [comment]
upload多文件单次上传什么时候能支持啊，2.x版本的都还不支持

**Comment by 13548506407** [comment]
遇到同样的问题，一次上传多次验证提示
