### ISSUE TITLE
Select.Option同时设置key和value属性值，且出现多个相同value时，会出现报错

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design#16351]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4xknl8kzyw)

### Steps to reproduce
1. 点击Select组件，出现下拉框
2. 会看到console面板会提示出现重复key值

### What is expected?
1. 不出现重复key值错误
2. 使用Option中设置的key值，而不是使用value值作为最终key值

### What is actually happening?
1. 出现重复Key值的错误提示

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.9.0 |
| System | win 10 |
| Browser | chrome 73 |

---
看了代码，是由于rc-select组件中优先使用value值作为key值导致了问题的出现
这里有先关代码截图：
![image](https://user-images.githubusercontent.com/13702561/56857103-e2f40100-699b-11e9-8350-bb90d5645257.png)

![image](https://user-images.githubusercontent.com/13702561/56857105-e7201e80-699b-11e9-9ae0-e11a022fea72.png)

**Comment by Rhuaer** [comment]
https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

**Comment by catgu** [comment]
遇到同样问题。个人觉得不应该这样设置。有时候数据会有 value 是不唯一的，但是其他字段比如code 是可以用作key的。
