### ISSUE TITLE
RangePicker异常，RangePicker中timePicker的上下午无法实现中文

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#1635]
今天升级了antd到1.0版本，使用RangePicker时出现了控制台警告信息，如下：
```
Failed propType: Invalid prop `selectedValue` of type `array` supplied to `DateTBody`, expected `object`. Check the render method of `DateTable`.
```
当参数showTime设置了locale，无法将其中的timePicker的AM和PM转化为中文。
如图所示(抱歉，上传不了图，给个连接吧)：
http://static.oschina.net/uploads/space/2016/0511/131758_ZKZo_556334.png

当选择了日期后，显示正常， 如下图(抱歉，上传不了图，给个连接吧)：
http://static.oschina.net/uploads/space/2016/0511/131924_b8Fh_556334.png

## Online demo

http://codepen.io/xiaoyi_1222/pen/zqbZJr

**Comment by benjycui** [comment]
`PropTypes` 的问题要进 rc-calendar 修。

**Comment by benjycui** [comment]
fix in https://github.com/react-component/calendar/commit/f581b0973beea844a8280c1f24e0b154720a6baa

cc @yiminghe
