### ISSUE TITLE
切换页面时滚动条回到页面顶部

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1636]

**Comment by markkoo** [comment]
我也推荐这基本功能, 在ipad 阅读是个障碍. 当然scroll top 是scroll 去指定的位置, 而不是最顶端, 这必须依据device 来决定 !

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/commit/fa62cac0b394b35884980732e2764defcbc33e8b
