### ISSUE TITLE
合并单元格和fixed列一起使用，会出现显示问题

### ISSUE THREAD

**Issue by swwinone** [ant-design/ant-design#16364]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/jv13jw4ywy)

### Steps to reproduce
直接看

### What is expected?
fixed 有合并单元格的列

### What is actually happening?
不要出现空白列，以及内容错乱

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | macos |
| Browser | Chrome 73 |

**Comment by kuhami** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/embed/jv13jw4ywy)
> 
> ### Steps to reproduce
> 直接看
> 
> ### What is expected?
> fixed 有合并单元格的列
> 
> ### What is actually happening?
> 不要出现空白列，以及内容错乱
> 
> Environment	Info
> antd	3.16.6
> React	16.8.6
> System	macos
> Browser	Chrome 73

我在ant Table组件做了修改可以解决一些问题 https://github.com/kuhami/AntTableFinder
![](https://raw.githubusercontent.com/kuhami/AntTableFinder/master/image/antTable.jpeg)

**Comment by zombieJ** [comment]
rowSpan 用了 5 格，下面就要对应减少 4 个 row：https://codesandbox.io/embed/jv13jw4ywy
