### ISSUE TITLE
暴露更新表格固定列行高的方法

### ISSUE THREAD

**Issue by fiveLucky** [ant-design/ant-design#16366]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The text was changed asynchronously, and the table row height was not updated because the mobx fine-grained update did not re-render the table. So I need to manually update the fixed column row height, I need a hook to do this.

[problem demo](https://codesandbox.io/s/z20x6z9vpp)

### What does the proposed API look like?
just call

**Comment by zombieJ** [comment]
使用 `components` 属性可以自定义表格元素。

**Comment by fiveLucky** [comment]
antd版本2.x是不是没救了

**Comment by fiveLucky** [comment]
> 使用 `components` 属性可以自定义表格元素。

antd版本2.x是不是没救了

**Comment by zombieJ** [comment]
`2.x` 已经过了维护期，升级到 `3.x` 吧~

**Comment by fiveLucky** [comment]
> `2.x` 已经过了维护期，升级到 `3.x` 吧~

升级成本太大，先这样吧

**Comment by cooljser** [comment]
我用的是 v3.16.6 ，但是还存在这个问题
