### ISSUE TITLE
关于checkBoxGroup的key值问题

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design#16376]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/74qnkrljvq)

### Steps to reproduce
例如我删除了某一项，遍历的data变化了，checkboxGroup点击某项却保留了上次的key值，
例子中测试点击3 ，删除，data变化为[1,2]，再次点击其中一项，key值保留上次的3值

### What is expected?
key值应取checkboxGroup域内的选中的值

### What is actually happening?
checkboxGroup点击保留了上次的key值

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.4.1 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
改成 onChange 返回值过滤掉 UI 中不存在的值，而内部状态保留该值。
如果一个值被选中后移除，onChange 不透出，值加回来后 onChange 继续透出。

**Comment by WingGao** [comment]
@zombieJ 目前只是UI变化，但是内部数据还是没有触发，建议在 `cancelValue`的时候触发`onChange`
列子 https://codesandbox.io/s/modern-fire-zmuf0
