### ISSUE TITLE
AutoComplete's onSearch is broken

### ISSUE THREAD

**Issue by ostrebler** [ant-design/ant-design#16377]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/42o6x7n619)

### Steps to reproduce
Just use the AutoComplete component wrapped over an Input. Control the value and onSearch props.

### What is expected?
onSearch should always return the actual input value, a string.

### What is actually happening?
When choosing an item from AutoComplete's Select menu, onSearch is passed a ReactNode, not the search string. This breaks the app. This is only since Antd version 3.16.6. Version 3.16.5 works fine.

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | Window 10 |
| Browser | Chrome 73.0.3683.103 |

**Comment by ostrebler** [comment]
![console](https://user-images.githubusercontent.com/30187797/56889389-831e5880-6a76-11e9-8b8d-53463edf8779.jpg)

**Comment by ztplz** [comment]
You forgot to save your demo, demo is the original demo. 
![image](https://user-images.githubusercontent.com/17755202/56889534-2e480580-6aa9-11e9-9b02-67e2706f13e6.png)

**Comment by ostrebler** [comment]
> You forgot to save your demo, demo is the original demo.

Yep, sorry. Corrected.

**Comment by ztplz** [comment]
Thanks, I will  take a look at it.

**Comment by ztplz** [comment]
@zombieJ  https://github.com/react-component/select/commit/d897fd40cec04da464a20c3980f187f2b25467d1

**Comment by ostrebler** [comment]
I can see why this was done. But one doesn't necessarily have a string as direct child of `AutoComplete.Option`. In my case, this update broke a large app I'm working on.

**Comment by zombieJ** [comment]
`rc-select@9.1.1` is updated.
