### ISSUE TITLE
vertical divider not working properly

### ISSUE THREAD

**Issue by danyhiol** [ant-design/ant-design#16372]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://m385w10y0j.codesandbox.io/)

### Steps to reproduce
https://r529rr882o.codesandbox.io/

### What is expected?
Divider to be aligned at the center with a line with the same height as the Col component. If text is used, this should be positioned on the divider line: center left or right.

### What is actually happening?
No horizontal line display. Text not on the line. Divider at top of the right column or at the end.

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | MacOs Mojave 10.14.4 |
| Browser | Goocle Chrome Version 73.0.3683.103 |

**Comment by zombieJ** [comment]
vertical Divider not provides the style with content. And also Row only accepts the Col as children. When you use 2 Col with 12 span, it means occupy the full width (24 span) of the window.

If you want to have this view, you may need add some customize css for this.
