### ISSUE TITLE
Select在多选模式下，搜索功能启用后选中异常

### ISSUE THREAD

**Issue by linpengfei** [ant-design/ant-design#16374]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4qn769zor0)

### Steps to reproduce
在权限下拉框中先选中一个元素，之后搜索不存在的值，然后点击空白区域，搜索内容消失，点击提交按钮，结果获取到的值中有误

### What is expected?
获取到的值应该为选中的内容，而不是搜索内容

### What is actually happening?
获取到的值为搜索内容

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome 版本 73.0.3683.103（正式版本） （64 位） |

**Comment by zombieJ** [comment]
使用 `getFieldDecorator` 后你不应该再给组件赋值: https://codesandbox.io/s/72o6xlqvyj
