### ISSUE TITLE
React has no default export when use typescript

### ISSUE THREAD

**Issue by xujihui1985** [ant-design/ant-design#1637]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。

If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did
use typescript

## What you would like to happen
should be compiled at least

## What actually happened
can not be compiled

## Online demo
![image](https://cloud.githubusercontent.com/assets/1619030/15171734/71c8d6c6-1783-11e6-9c34-21e200748489.png)

## Environment Information
osx

suggestion: 

as antd.d.ts now is a part of antd, any change on the that will lead to a version bump on antd, it is strongly recommend to add test for the tsd.
 
- The version of antd(e.g. 1.0.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
@bang88

**Comment by bang88** [comment]
之前使用 `tsd` 来管理 `typings`，现在把`ant.d.ts`放在项目里面的话要使用 https://github.com/typings/registry 来管理，需要添加一个`antd`文件，可以发个PR要求添加

不知道`antd`已经发布新版本了，而且这个文件也没有及时更新。

@afc163 是不是有考虑过使用 `typescript`来生成文档。

@xujihui1985 可以先试试这个应该可以解决
```js
import * as React from "react";
```

**Comment by xujihui1985** [comment]
也不是一定要放到typings/registry管理，typescript会到node_modules去找，跟着antd走可以的，但必须保证和antd一致并且是正确的，否则如果要改d.ts就得升级antd, 这样就尴尬了。 目前我在本地是可以改成import * as  这种方式，但上服务器编译的现在是有问题的，我没有把node_modules提交进去

**Comment by xujihui1985** [comment]
我现在先退回到0.12, 这样我可以把typings提交到代码仓库，改这个typing文件，另外有些component的定义也有点问题， 比如Input, 没有onChange事件, 这样也会导致报错

![image](https://cloud.githubusercontent.com/assets/1619030/15172434/9c5896e2-1788-11e6-88e3-aa4f6b2c8852.png)

需要加上这些属性 

![image](https://cloud.githubusercontent.com/assets/1619030/15172453/b6654526-1788-11e6-9201-946c25cc1e3e.png)

**Comment by bang88** [comment]
没有及时同步更新，欢迎PR

可能你的使用场景跟我们的不太一样，我们一般是配置成这样，智能提示使用。
```js
{
    "compilerOptions": {
       ...
    },
    "exclude": [
        "node_modules"
    ]
}
```
默认排除了`node_modules`文件夹

**Comment by xujihui1985** [comment]
exclude node_modules不会影响 typescript 找d.ts文件，只是不会把node_modules下的文件编译，用typing的目的就是为了有编译时检查，我先把我碰到的问题提交个mr
