### ISSUE TITLE
form.getFieldDecorator 包装 react hooks 函数式组件控制台报 Warning:

### ISSUE THREAD

**Issue by javahuang** [ant-design/ant-design#16386]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rjn9oowzmn?fontsize=14)

### Steps to reproduce
打开控制台，会有如下 Warning 信息

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ScopeAttribute`.
    in SubComponent (created by ScopeAttribute)
    in div (created by ScopeAttribute)
    in div (created by ScopeAttribute)
    in ScopeAttribute (created by Form(ScopeAttribute))
    in Form(ScopeAttribute) (created by App)
    in div (created by App)
    in App
```

### What is expected?
不会 Warning

### What is actually happening?
会有 Warning

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 166 |
| System | macos |
| Browser | 版本 74.0.3729.108（正式版本） （64 位） |

**Comment by zombieJ** [comment]
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
<img width="568" alt="屏幕快照 2019-04-30 下午3 24 13" src="https://user-images.githubusercontent.com/5378891/56946185-0796d700-6b5c-11e9-9eb3-1e0883066f9d.png">

**Comment by qq645381995** [comment]
@zombieJ  有没有 hooks 的例子

**Comment by zoverdoser** [comment]
@javahuang 这个问题解决了么？

**Comment by Heshiyu1996** [comment]
> @javahuang 这个问题解决了么？

解决了。看@zombieJ发的antd官网里有关form的描述，里面有个示例。

大致代码如下：
```js
import React, { useEffect, forwardRef } from 'react';

const ChildComp = (props, ref) => {
    // 这里参数要写多一个ref，否则还会多一个请确认ref参数是否使用的warning
    const { value } = props;
    return <input value={value} onChange={(e) => props.onChange(e.target.value)} />;
};

const Child = forwardRef(ChildComp);

const Parent = props => {
    const {
        form: { getFieldDecorator }
    } = props;

    return (
        <FormItem>
            {getFieldDecorator('name',{})(<Child {...props} />)}
        </FormItem>
    );
};
```
