### ISSUE TITLE
Totals row on tables

### ISSUE THREAD

**Issue by rsmolkin** [ant-design/ant-design#16383]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi, we are trying to add a totals row on a table, but if we use the table footer for it, we can't find a good way to line up the values for totals with their respective columns in the table.  We also don't see any examples of your table using a totals row.  Can you please add support for having a totals row and provide an example?

### What does the proposed API look like?
Not sure, but something allowing us to put totals into some columns and leave some columns blank.

**Comment by zombieJ** [comment]
Merge into #5710
