### ISSUE TITLE
How to make a tree with CRUD options ? 

### ISSUE THREAD

**Issue by UrielZohar** [ant-design/ant-design#16385]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Give the option for more customized tree 

### What does the proposed API look like?
`<TreeNode title="root" key="0" create delete edit>`

**Comment by afc163** [comment]
`title` could be ReactNode.
