### ISSUE TITLE
table component, use onRow{onClick}, I just want to longPress copy row info, but still trigger click

### ISSUE THREAD

**Issue by wenisy** [ant-design/ant-design#16382]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k2z3ljn8zv?fontsize=14)

### Steps to reproduce
```javascript
          onRow={(r) => ({
            onClick: () => console.log('###############'),
          })}
```
When you just want to long press to copy a row info, but it would still trigger click when mouseup

### What is expected?
Long press won't trigger click

### What is actually happening?
Long press triggers click actually

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8 |
| System | mac mojave 10.14.4 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
It's default HTML behavior. If you want to realize long press:
1. Listen onMouseDown and record current row & timestamp.
2. Listen onMouseUp and compare row & timestamp.
3. Match to do your customize logic.

**Comment by ahsanali60** [comment]
I have a couple of  buttons inside a row but when i press on any button it trigger the onRowClick  but not the button's action
