### ISSUE TITLE
Compilation error: hoist-non-react-statics has no exported member 'NonReactStatics'.

### ISSUE THREAD

**Issue by shuangq** [ant-design/ant-design#16396]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://typescriptlang.com](https://typescriptlang.com)

### Steps to reproduce
Currently I'm using TypeScript 3.4.5 with `allowSyntheticDefaultImports` set to `true`.

### What is expected?
Success to compile.

### What is actually happening?
```
Failed to compile.
/project/node_modules/antd/lib/form/interface.d.ts
(9,166): Namespace '"/project/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.

```

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | macOS Mojave 10.14 |
| Browser | Chrome 72 |

---
I'm not sure if this is same as issue #16210 and #16224, since it breaks the compilation rather than just throwing a warning. And I have `allowSyntheticDefaultImports` set to `true`.

**Comment by ztplz** [comment]
Does your project also use ` react-router`?

**Comment by alessandrojcm** [comment]
I'm also having this issue while prototyping a component with Storybook (which uses webpack for the build process). I'm my case, I don't use `react-router` (and since I'm prototyping, no routing is involved at all).

**Comment by ztplz** [comment]
@alessandrojcm I guess maybe because you have other dependencies that depend on an old version of `hoist-non-react-statics` and install them before `antd`.  Under the rules since nobody else had any dependency on `hoist-non-react-statics` the package was installed at the top level of node_modules. Now `antd` is installed. It depends on `hoist-non-react-statics@3.3.0`. But, since an old version of  `hoist-non-react-statics` is already at the top level, it puts 3.3.0 in the node_modules folder under `antd`. So it appears that the dependency in `antd` of @types/hoist-non-react-statics@3.3.0 doesn't find it because it's not at the top level. 
BTW it would be more helpful if there was a mini repo.

**Comment by ztplz** [comment]
@shuangq  @alessandrojcm  Can your create a mini repo to help us figure out this problem? I guessed something but need to confirm it.

**Comment by alessandrojcm** [comment]
@ztplz Mmm, you're right. Minimal repro builds just fine. Let me check my dep tree to see which package is causing troubles.

**Comment by shuangq** [comment]
@ztplz  I think your assumption is correct. I checked my dependencies, and `hoist-non-react-statics@2.5.5` is used for other packages as well.

<img width="359" alt="Screenshot 2019-05-02 at 12 02 10" src="https://user-images.githubusercontent.com/11632200/57065451-26b77500-6cd2-11e9-9b25-97a380a9ba65.png">


But weird enough I tried to create a mini repo with these dependencies that uses still `hoist-non-react-statics@2.5.5` but it works just fine.  I'll try to see which one is actually causing the problem.

Currently, I downgraded to `antd@3.16.3` and it works.

**Comment by ztplz** [comment]
@shuangq  As an workaround, can you solve this problem by installing `hoist-non-react-statics` and `@types/hoist-non-react-statics` in your project ? Then tell me if it works.

**Comment by shuangq** [comment]
@ztplz Yes it did. 

This is a similar issue from the latest @types/react-redux package:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690

The current workaround would be explicitly installing `hoist-non-react-statics` or forcing resolution if using yarn.

**Comment by ztplz** [comment]
@shuangq   I have added this library to the `antd` dependencies https://github.com/ant-design/ant-design/pull/16397. But I think this library is not necessary, just to solve [this problem](https://github.com/ant-design/ant-design/issues/16095).

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/16397
