### ISSUE TITLE
Missing background fill on submenu dark theme when selected

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#16405]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/v802v0nyw5)

### Steps to reproduce
1. Open "minimal reproduction".

### What is expected?
Navigation Three - Dark Theme has a bright blue fill

### What is actually happening?
Navigation Three has no fill (or transparent fill)

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.3 |
| System | Windows 10.0.17763 Build 17763 |
| Browser | Chrome 73.0.3683.103 |

---
Problem may be here: https://github.com/ant-design/ant-design/blob/master/components/menu/style/dark.less

Screen capture:

![image](https://user-images.githubusercontent.com/1298521/57050405-3e8aec80-6c31-11e9-9c39-f2ba03efa252.png)

**Comment by zombieJ** [comment]
It's by design. Sub Menu selected in dark theme do not fill background color and only highlight the word:
<img width="619" alt="屏幕快照 2019-05-05 上午11 06 03" src="https://user-images.githubusercontent.com/5378891/57187724-f7994180-6f25-11e9-9303-aa12539edfa4.png">

**Comment by devuxer** [comment]
@zombieJ,

Why is the design different than the light theme? In the light theme, you get the nice blue underline.

**Comment by zombieJ** [comment]
In dark theme fill full background of secondary selection is too heavy. You can just override the style if you need highlight anyway.

**Comment by devuxer** [comment]
I think the problem is thinking of it as a "secondary selection".

In my situation "Navigation 3" is just as important as "Navigation 1", so it's confusing to not have it highlight the same way for both.

It is definitely possible to work around this with custom CSS/Less (which is what I did), but I think the design would be better if it were consistent. (At the very least, it would be nice to have the _option_ to full highlight items with children in dark mode.)
