### ISSUE TITLE
When i use Switch Component in Form Componet,   i click label of Switch , the value of Switch changed,

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#16406]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/switch-cn/](https://ant.design/components/switch-cn/)

### Steps to reproduce
      <Form.Item
        label={label}
      >
        {getFieldDecorator(name, {

        })(
          <Switch />
        )}
      </Form.Item>

### What is expected?
希望在点击组件的 label 的时候， Switch 组件的值不发生变化

### What is actually happening?
在点击组件的 label 的时候， Switch 组件的值发生变化

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by zombieJ** [comment]
This is by design. Switch follow's the behavior of checkbox:
```jsx
<label htmlFor="checker">Click Me</label>
<input type="checkbox" id="checker" />
```

ref: #15549

**Comment by vi-verma** [comment]
I am using two antd form . Both have switch with same name. On clicking second switch label it changes/ trigers 1st switch.
