### ISSUE TITLE
e.stopPropagation(); doesn't work on checkbox 

### ISSUE THREAD

**Issue by Ladvace** [ant-design/ant-design#16400]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/gorilla-devs/GDLauncher/blob/master/app/components/InstanceManagerModal/ModsManager/LocalMods/ModRow.js](https://github.com/gorilla-devs/GDLauncher/blob/master/app/components/InstanceManagerModal/ModsManager/LocalMods/ModRow.js)

### Steps to reproduce
set a e.stopPropagation  onChange on a checkbox

### What is expected?
stopping bubbling

### What is actually happening?
e.stopPropagation(); doesn't work on checkbox but yes on button

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | reactjs 16.8.4 |
| System | windows 10 |
| Browser | electron |

---
e.stopPropagation(); doesn't work on checkbox but yes on button

**Comment by afc163** [comment]
Try `onClick={e => e.stopPropagation()}`

**Comment by bradgreens** [comment]
@afc163 how about the `<label>` which is generated by the `<Checkbox />` component? I need to stop propagation on the generated `<label>` element as well.

**Comment by msaktor** [comment]
> @afc163 how about the `<label>` which is generated by the `<Checkbox />` component? I need to stop propagation on the generated `<label>` element as well.

it's ugly but this works for me
```
<Checkbox
    onClick={e => e.stopPropagation()}
>
    <span onClick={e => e.stopPropagation()}>Label</span>
</Checkbox>
```

**Comment by yohgen** [comment]
To further expound on @msaktor's suggestion, I fixed most of my cases where an antd component (`<Checkbox />`, `<NumberInput />`, `<Input />`, among others) would not block event propagation by wrapping them in a `<div>` with an `onClick` handler like so:
```
<div
  onClick={(e) => e.stopPropagation()}
>
  <Checkbox />
</div>
```
`e.stopPropagation()` on an antd child is no longer necessary with this `<div>` hack.
