### ISSUE TITLE
灌入table中的数据如果带特殊字符的会被react转义 有没有外置的dangerouslySetInnerHTML方案

### ISSUE THREAD

**Issue by AceLeeWinnie** [ant-design/ant-design#1640]

**Comment by benjycui** [comment]
`columns.render` http://ant.design/#/components/table?scrollTo=Column

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
