### ISSUE TITLE
Advance usage of dynamic form.

### ISSUE THREAD

**Issue by umair-khanzada** [ant-design/ant-design#16404]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
No doubt antd provided good example/demo of each component, Actually I have created a generic component for add field or multiple fields dynamically so it would be great if you guys take a look at my component and add this in example list if this gonna help community.

### What does the proposed API look like?
```
import React, {Component, Fragment} from 'react';
import { Form, Icon, Button } from 'antd';
import PropTypes from 'prop-types';

class DynamicFields extends Component {
	id = 1;

	add = () => {
		const { getFieldValue, setFieldsValue, name } = this.props,
			keys = getFieldValue(`${name}List`),
			nextKeys = keys.concat(this.id++);

		setFieldsValue({
			[`${name}List`]: nextKeys,
		});
	};

	remove = (k) => () => {
		const { getFieldValue, setFieldsValue, name } = this.props,
			keys = getFieldValue(`${name}List`);

		if (keys.length === 1) return;
		setFieldsValue({
			[`${name}List`]: keys.filter(key => key !== k),
		});
	};

	defaultValidation = (name) => (
		{
			validateTrigger: ['onChange', 'onBlur'],
			rules: [{
				required: true,
				whitespace: true,
				message: `Please input ${name}.`,
			}],
		}
	);

	addSingleField = () => {
		const { getFieldDecorator, getFieldValue, fields: obj, name } = this.props;
		getFieldDecorator(`${name}List`, { initialValue: [0] });
		const fieldCounter = getFieldValue(`${name}List`);
		return fieldCounter.map((k) => (
			<Form.Item
				key={k}
			>
				{
					getFieldDecorator(`${name}[${k}]`,
						obj.validation || this.defaultValidation(name))(obj.field())
				}
				{
					fieldCounter.length > 1 ? (
						<Icon
							className="dynamic-delete-button"
							type="minus-circle-o"
							onClick={this.remove(k)}
						/>
					) : null
				}
			</Form.Item>
		));
	};

	addMultipleFields = () => {
		const { getFieldDecorator, getFieldValue, fields, name } = this.props;
		getFieldDecorator(`${name}List`, { initialValue: [0] });
		const fieldCounter = getFieldValue(`${name}List`);

		return fieldCounter.reduce((preResult, k) => {
			const row = fields.map((obj, i) => (
				<Form.Item
					key={`${k}${obj.name}`}
				>
					{
						getFieldDecorator(`${name}[${k}][${obj.name}]`,
							obj.validation || this.defaultValidation(name))(obj.field())
					}
					{
						fieldCounter.length > 1 && (fields.length - 1) === i? (
							<Icon
								className="dynamic-delete-button"
								type="minus-circle-o"
								onClick={this.remove(k)}
							/>
						) : null
					}
				</Form.Item>
			));

			return [
				...preResult,
				...row
			]
		}, []);

	};

	render() {
		const {fields, name} = this.props;
		return (
			<Fragment>
				{Array.isArray(fields) ? this.addMultipleFields() : this.addSingleField()}
				<Form.Item>
					<Button type="dashed" onClick={this.add} style={{ width: '60%' }}>
						<Icon type="plus" /> Add &nbsp; {name}
					</Button>
				</Form.Item>
			</Fragment>
		);
	}

}

DynamicFields.propTypes = {
	name: PropTypes.string.isRequired,
	fields: PropTypes.oneOfType([
		PropTypes.object,
		PropTypes.arrayOf(PropTypes.object)
		//TODO: add object shape validation.
	]).isRequired,
	getFieldValue: PropTypes.func.isRequired,
	setFieldsValue: PropTypes.func.isRequired
};

export default DynamicFields;

//usage
<Divider orientation="left" className="first">Email Details</Divider>
				<DynamicFieldSet {...form} name="email" fields={{name: 'email', field: () => <Input placeholder={'Email'}  />}}/>
				<Divider orientation="left" className="first">Cell Details</Divider>
				<DynamicFieldSet {...form} name="name" fields={{name: 'mobile', field: () => <Input placeholder={'Mobile'}  />}}/>
				<Divider orientation="left" className="first">Address Details</Divider>
				<DynamicFieldSet {...form} name="address" fields={[
					{name: 'country', field: () => <Input placeholder={'country'}  />},
					{name: 'state', field: () => <Input placeholder={'state'}  />},
					{name: 'city', field: () => <Input placeholder={'city'}  />},
					{name: 'street', field: () => <Input placeholder={'street'}  />}
				]}/>
```

**Comment by umair-khanzada** [comment]
![dynamic_Fields](https://user-images.githubusercontent.com/8782817/57020632-4f445e00-6c43-11e9-9372-8dd2791b4204.png)

**Comment by umair-khanzada** [comment]
UI looks like this.

![dynamic_Fields](https://user-images.githubusercontent.com/8782817/57020671-7307a400-6c43-11e9-9c6a-71d76cf6fde4.png)

**Comment by zombieJ** [comment]
Since it may little complex as demo. Maybe you can create an https://codesandbox.io sample. I can help to add in FAQ.

**Comment by umair-khanzada** [comment]
Sure, Will do

**Comment by umair-khanzada** [comment]
Done, please have a look
https://codesandbox.io/s/jnpjpj2p55

**Comment by zombieJ** [comment]
`rules` should be a prop from outside. And style seems not correct:
<img width="425" alt="屏幕快照 2019-05-02 上午10 06 24" src="https://user-images.githubusercontent.com/5378891/57053654-10092200-6cc2-11e9-8182-e8a9a487c215.png">

**Comment by umair-khanzada** [comment]
Yup, you are right.

see I have created `defaultValidation` function that return default rules object if you want to override default rules object just validation key in fields object.

```
defaultValidation = (name) => (
  {
    validateTrigger: ['onChange', 'onBlur'],
    rules: [{
      required: true,
      whitespace: true,
      message: `Please input ${name}.`,
    }],
  }
);

//and here we apply rules.
obj.validation || this.defaultValidation(name)
```

### Style
I have not added style yet.

**Comment by itsmaqsoodecommdesk** [comment]
how can we use this in react functional component by using hooks and all ? please help

**Comment by ukhanzada-nisum-com** [comment]
@itsmaqsoodecommdesk `DynamicFields` fields are used inside the `From` component because of `DynamicFields` is dependent on some From props, but yes you can use inside function components.

```

const FunctionalComponent = ({ form }) => {
  return (
    <Form>
      <Divider orientation="left" className="first">
        Add Email
      </Divider>
      <DynamicFields
        {...form}
        name="email"
        fields={{
          name: "email",
          field: () => <Input placeholder={"Email"} />
        }}
      />
    </Form>
  )
}

export default Form.create({ name: "user_profile" })(UserProfile)

```

**Comment by itsmaqsoodecommdesk** [comment]
How will we get Form Data ?

**Comment by ukhanzada-nisum-com** [comment]
When you use `Form.crate` it will add some props in your components.

```
  <Form onSubmit={this.handleSubmit}>
    //inputs...
  </Form>

  handleSubmit = e => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        /*Do something.*/
      }
      console.log("Received values of form: ", values);
    });
  };
```

**Comment by itsmaqsoodecommdesk** [comment]
Hi, i want to store feature details data, which is an array of objects, so how will i get it can you please help me.   

this is what i am doing here -->  https://codesandbox.io/s/polished-dream-xkl34

**Comment by mustafahafidi** [comment]
Hope, this is going to be solved soon and integrated into the API in a cleaner way. Managing arrays in forms is pretty much usual, the way antd does it is tedious.

**Comment by zombieJ** [comment]
antd v4 provides `Form.List` to help handle list of dynamic fields. Please feel free to try on:

https://next.ant.design/components/form/?locale=en-US#components-form-demo-dynamic-form-item

**Comment by axxop** [comment]
> antd v4 provides `Form.List` to help handle list of dynamic fields. Please feel free to try on:
> 
> https://next.ant.design/components/form/?locale=en-US#components-form-demo-dynamic-form-item

I am using antd pro v4. Is there any plan support?

**Comment by zombieJ** [comment]
antd pro will release new version after antd v4 finish beta version.

**Comment by gino8080** [comment]
Form.List seems promising, can you provide a full example please? the one on the docs is not enought clear for me, thank you!

**Comment by zombieJ** [comment]
> Form.List seems promising, can you provide a full example please? the one on the docs is not enought clear for me, thank you!



> antd v4 provides `Form.List` to help handle list of dynamic fields. Please feel free to try on:
> 
> https://next.ant.design/components/form/?locale=en-US#components-form-demo-dynamic-form-item

**Comment by zombieJ** [comment]
Close since Form.List is ready in v4.

**Comment by mrkoch** [comment]
There is a way to add multiple fields in Form.List v4? In this example [https://github.com/ant-design/ant-design/blob/master/components/form/demo/dynamic-form-item.md](url) is not clear how to do it. Can you provide a full example? Thx

**Comment by ruruiye** [comment]
same problem with multiple fields and `Form.List`, please make the example more clear about this.

**Comment by chalupagrande** [comment]
> EDIT
> This code help me https://codesandbox.io/s/listshouldupdate2-70b7h

This saved my life. I cleaned it up a little bit to help others! 
https://codesandbox.io/s/lively-haze-cje76?fontsize=14&hidenavigation=1&theme=dark

**Comment by mxab** [comment]
Does anyone know if it possible to combine Form.List and a Table to have complex editable table, where all rows are editable and part of a form?

**Comment by vin0010** [comment]
I did some thing like this to fix this issue.
![image](https://user-images.githubusercontent.com/10086767/76039259-261fe880-5f4c-11ea-8177-a6c2011172ea.png)
`
<Form.List name="secondaryContacts">
                        {(fields, {add, remove}) => {
                            return (
                                <div>
                                    {fields.map((field, index) => (
                                        <Form.Item
                                            {...(formItemLayoutWithOutLabel)}
                                            label={index === 0 ? '' : ''}
                                            required={false}
                                            key={field.key}
                                        >
                                            <Form.Item
                                                {...field}
                                                validateTrigger={['onChange', 'onBlur']}
                                                rules={[
                                                    {
                                                        required: true,
                                                        validator: phoneNumberValidator
                                                    },
                                                ]}
                                            >
                                                <Input placeholder="Secondary Contact"
                                                       addonAfter={fields.length >= 1 ? (
                                                           <MinusCircleOutlined
                                                               onClick={() => {
                                                                   remove(field.name);
                                                               }}
                                                           />
                                                       ) : null}/>

                                            </Form.Item>

                                        </Form.Item>
                                    ))}
                                    <Form.Item {...formItemLayoutWithOutLabel}>
                                        <Button
                                            type="dashed"
                                            onClick={() => {
                                                add();
                                            }}
                                            style={{width: '100%'}}
                                        >
                                            <PlusOutlined/> Add Secondary Contact
                                        </Button>
                                    </Form.Item>
                                </div>
                            );
                        }}
                    </Form.List>
`

**Comment by FightingJane** [comment]
> There is a way to add multiple fields in Form.List v4? In this example [https://github.com/ant-design/ant-design/blob/master/components/form/demo/dynamic-form-item.md](url) is not clear how to do it. Can you provide a full example? Thx
> 
> EDIT
> This code help me https://codesandbox.io/s/listshouldupdate2-70b7h

So touched！saved me.

**Comment by osamasayed** [comment]
Does anyone have an example on how to add dynamic fields to a list for editing? For example, a list of 3 fields that I want to pre-load with their value for editing.

**Comment by nischalhubbler** [comment]
In antd v4.1.1 Form.List does not support scroll to top on error when submitting the form?

**Comment by yoyo837** [comment]
Try `scrollToFirstError`

**Comment by nischalhubbler** [comment]
have tried..but not working... it is scrolling to the field which are not inside Form.List

**Comment by AhmedCommando** [comment]
Is there a way to have a pre filled form with Form.list?

**Comment by bramantyoa** [comment]
@AhmedCommando you can provide intialValues props to the Form component to have a prefilled form items inside the form.list. Check out this codesandbox I forked from @chalupagrande  https://codesandbox.io/s/antd-form-list-multiple-formitem-dynamic-fields-gowd8?file=/src/App.js

**Comment by majugurci** [comment]
> 
> 
> Does anyone know if it possible to combine Form.List and a Table to have complex editable table, where all rows are editable and part of a form?

I also had this requirement and after experimenting found a solution which seems to work great.

In case anybody else needs it here is a working [codesandbox example ](https://codesandbox.io/s/gracious-kirch-nrnvw?file=/FormExample.tsx).

**Comment by xlanor** [comment]
Is there any sample in antdv4 to have nested Form.Lists?

For example - take it in the context that I am creating a multiple choice survey. 

The first Form.List should handle the creation of the question, while within every question, I will need to create options for each question.

I've seen examples of v3, but Ive tried to port them to v4 and I couldn't get it up and running

https://stackoverflow.com/questions/51782379/how-to-create-a-questionnaire-type-form-using-ant-design

**Comment by umair2k6** [comment]
I am trying to do dynamic validation on the dynamic form and the given example on the antd documentation workers with the regular form only. Wondering if someone came across any need like this and have already worked out the solution?

**Comment by Amit-Sagar** [comment]
can you make droppable any of the dynamic form

**Comment by tahiraydin** [comment]
hello, I want to change the input value in the form list field with a different button. How do I get the input value in the fields from the upper scope?
