### ISSUE TITLE
accordion first panel isn't expanded by default

### ISSUE THREAD

**Issue by estherj-hsu** [ant-design/ant-design#16407]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
no need to reproduce

### What is expected?
according to doc, the first panel should be expanded by default

### What is actually happening?
the first panel isn't expanded by default

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | 16.4.1 |
| System | mac os |
| Browser | chrome |

**Comment by zombieJ** [comment]
Thanks for report. Seems document is wrong, `accordion` do not default expanded panel since 2.x. I will update the document.
