### ISSUE TITLE
项目打包后createFromIconfontCN引入的图标失效

### ISSUE THREAD

**Issue by Y-qwq** [ant-design/ant-design#16401]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Y-qwq/createFromIconfontCN](https://github.com/Y-qwq/createFromIconfontCN)

### Steps to reproduce
项目build再dist（打包electron）后，安装运行，createFromIconfontCN全部失效，其余都正常。

### What is expected?
打包后图标和开发环境一致

### What is actually happening?
项目运行时没问题，打包后，所有通过createFromIconfontCN 引入的图标都失效，报错 Failed to load resource: net::ERR_FILE_NOT_FOUND

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.4 |
| System | win 10 |
| Browser | chrome 73 |

---
怀疑是homepage影响造成，但是因为要electron再打包，不能改homepage，所以不知道怎么解决这个问题。
部分package：
 ```
 "homepage": ".",
  "dependencies": {
    "antd": "^3.16.6",
    "axios": "^0.18.0",
    "d3-ease": "^1.0.5",
    "nedb": "^1.8.0",
    "react": "^16.8.4",
    "react-contexify": "^4.0.2",
    "react-dom": "^16.8.4",
    "react-move": "^5.2.1",
    "react-redux": "^6.0.1",
    "react-router-dom": "^5.0.0",
    "react-scripts": "2.1.8",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "typescript": "^3.4.5"
  },
  "devDependencies": {
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^5.2.0",
    "customize-cra": "^0.2.12",
    "electron": "^5.0.0",
    "electron-builder": "^20.39.0",
    "less": "^3.9.0",
    "less-loader": "^5.0.0",
    "node-sass": "^4.12.0",
    "react-app-rewired": "^2.1.1",
    "redux-logger": "^3.0.6"
  },
```

**Comment by zombieJ** [comment]
项目启动不起来，请给出具体步骤：
<img width="522" alt="屏幕快照 2019-05-01 下午9 35 24" src="https://user-images.githubusercontent.com/5378891/57019467-35ae1100-6c59-11e9-951f-4c152ccc9276.png">

**Comment by Y-qwq** [comment]
> 项目启动不起来，请给出具体步骤：
> <img alt="屏幕快照 2019-05-01 下午9 35 24" width="522" src="https://user-images.githubusercontent.com/5378891/57019467-35ae1100-6c59-11e9-951f-4c152ccc9276.png">

electron项目，运行项目后不能通过浏览器打开。只能再运行yarn ele-start或者npm run ele-start打开electron窗口运行。

**Comment by Y-qwq** [comment]
开发环境运行是没问题的，但是yarn build后再yarn dist（打包electron程序），点开安装的程序，其他都没问题，就是createFromIconfontCN引入的iconfont图标失效，但是控制台也有元素，列如：
```
<i tabindex="-1" class="anticon nav-icon nav-select">
    <svg width="1em" height="1em" fill="currentColor" aria-hidden="true" focusable="false" class="">
        <use xlink:href="#icon-faxian"></use>
    </svg>
</i>
```
怀疑是引入的链接受到"homepage": "."的影响而失效

**Comment by Y-qwq** [comment]
以更新问题，修改为出现问题的最小化仓库[https://github.com/Y-qwq/createFromIconfontCN](https://github.com/Y-qwq/createFromIconfontCN)
问题截图：
![问题截图](https://github.com/Y-qwq/createFromIconfontCN/blob/master/%E6%88%AA%E5%9B%BE.png "问题截图")

**Comment by zombieJ** [comment]
👌，我看看

**Comment by zombieJ** [comment]
还是跑不起来：
<img width="712" alt="屏幕快照 2019-05-01 下午11 06 17" src="https://user-images.githubusercontent.com/5378891/57023880-c12d9f00-6c65-11e9-8991-24358ed2345c.png">

推测应该是打包后相对 url 不对，试一试改成:
```diff
export default  Icon.createFromIconfontCN({
-  scriptUrl: '//at.alicdn.com/t/font_1094435_nfi2mw6fwzh.js', // 在 iconfont.cn 上生成
+  scriptUrl: 'https://at.alicdn.com/t/font_1094435_nfi2mw6fwzh.js', // 在 iconfont.cn 上生成
});
```

**Comment by Y-qwq** [comment]
> 还是跑不起来：
> <img alt="屏幕快照 2019-05-01 下午11 06 17" width="712" src="https://user-images.githubusercontent.com/5378891/57023880-c12d9f00-6c65-11e9-8991-24358ed2345c.png">
> 
> 推测应该是打包后相对 url 不对，试一试改成:
> 
> ```diff
> export default  Icon.createFromIconfontCN({
> -  scriptUrl: '//at.alicdn.com/t/font_1094435_nfi2mw6fwzh.js', // 在 iconfont.cn 上生成
> +  scriptUrl: 'https://at.alicdn.com/t/font_1094435_nfi2mw6fwzh.js', // 在 iconfont.cn 上生成
> });
> ```

😂我最小化项目后，就只是个网页项目了，yarn start运行项目 和  yarn build再点开build/index.html结果不同，我去试试你给的方法。

**Comment by Y-qwq** [comment]
可以了，咋没想到试一下加https头，麻烦大佬了😭
