### ISSUE TITLE
Select placeholder broken with value

### ISSUE THREAD

**Issue by bgold0** [ant-design/ant-design#16417]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kw431ww1q7)

### Steps to reproduce
A select that has a value or doesn't have a value

### What is expected?
If the value doesn't match any options, the placeholder should appear

### What is actually happening?
Placeholder is blank

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | ^16.4.1 |
| System | Mac |
| Browser | Chrome |

---
This is a big style issue.

**Comment by bgold0** [comment]
If `value={undefined}` the placeholder shows. It should also show if `value={null}` or `value` doesn't equal to any options.

**Comment by zombieJ** [comment]
Select support `value` not match any option in the children. This design is to simplify ajax fetch when options not ready.
`''` is a validate value, so it does not show the placeholder.

**Comment by afc163** [comment]
Duplicate of #2367

**Comment by shamseer-ahammed** [comment]
+1 for this
