### ISSUE TITLE
filterDropdown doesn't have proper typing

### ISSUE THREAD

**Issue by NickDubelman** [ant-design/ant-design#16413]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This is a Typescript library, there should be complete typings

### What does the proposed API look like?
Right now the props are just given Object type

I already see:

```
prefixCls: `${dropdownPrefixCls}-custom`,
setSelectedKeys: (selectedKeys: Array<any>) => this.setSelectedKeys({ selectedKeys }),
selectedKeys: originSelectedKeys,
confirm: this.handleConfirm,
clearFilters: this.handleClearFilters,
filters: column.filters,
getPopupContainer: (triggerNode: HTMLElement) => triggerNode.parentNode,
```

This should be an interface like:

```
interface FilterDropdownProps {
    prefixCls: string
    setSelectedKeys: (selectedKeys: string[]) => void
    selectedKeys: string[]
    confirm: () => void
    clearFilters: (selectedKeys: string[]) => void
    filters: ??
    getPopupContainer: (triggerNode: HTMLElement) => HTMLElement
}
```

It doesn't make sense developers would have to type this themselves and there are obviously many people using antd also using typescript.

**Comment by zombieJ** [comment]
Do you have interest to send a PR for this?

**Comment by NickDubelman** [comment]
I can try. I'm not sure what the type of filters is
