### ISSUE TITLE
`index` in table column render function always start from 0 without pagination offset 

### ISSUE THREAD

**Issue by neekey** [ant-design/ant-design#16414]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/neekey/pen/mgNjYR](https://codepen.io/neekey/pen/mgNjYR)

### Steps to reproduce
click the pagination to page 2, you should see the index is still `0, 1, 2, 3, 4`

### What is expected?
the index should be calculated with pagination

### What is actually happening?
the index always starts from 0 regardless of the pagination

this issue is related to this closed issue which I believe is not solved https://github.com/ant-design/ant-design/issues/8311#issuecomment-346791877

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.3 |
| System | mac os |
| Browser | chrome |

**Comment by zombieJ** [comment]
`index` means current page index not full list index. If you want to get full list index you should add additional index prop in records:
```jsx
const data = [];
for (let i = 0; i < 100; i++) {
  data.push({ name: `Name ${i}`, myIndex: i });
}
```

**Comment by neekey** [comment]
@zombieJ by adding extra field to the data does not work well with sorting. See this example https://codepen.io/neekey/pen/BEXvzY, as the internal data list is not exposed to the user:

![image](https://user-images.githubusercontent.com/499870/57122970-4ed2d100-6dc3-11e9-8940-b57507a416a5.png)

in this case, we still want to keep the `#` column as the index of the current sorted list.

I know this is not a bug, but it's because of antd Table does not provide sufficient data, makes this quite common UI very difficult to build. and to be honest, the fact that `index` is the index of the current page is not very useful.

**Comment by zombieJ** [comment]
Could you describe why need keep the index of it?  In my side, the index should be dis-order since other column sorted.

**Comment by neekey** [comment]
@zombieJ the `index` column in the data table acts as a `rank` for whatever sorting is currently applying to the table. It does not behaves as an unique `id`

for example, if you sort the table by `ub` in descending order, the `index` tells you what the rank of the row you are looking at in in terms of the current sorting. ( a `index` of 10, means there are 9 items having bigger `ub` then this item you are looking at)

**Comment by zombieJ** [comment]
Hmmm. For view of current rank seems easy for user to check.
cc @afc163 @yesmeck @ztplz

**Comment by neekey** [comment]
@zombieJ @afc163 @yesmeck @ztplz any feedback?

**Comment by zombieJ** [comment]
Thanks for pin. `index` by page level is keep align with async mode. It may not update about total index.
But you can still get the correct one with calculation of page number: https://codesandbox.io/s/reverent-darwin-4x3ml

**Comment by neekey** [comment]
Hey @zombieJ , thanks for the demo, that seems work, I will give it a try

**Comment by Meet-Bhalodia** [comment]
@zombieJ I had visit your pen : https://github.com/ant-design/ant-design/issues/16414 great 
I need one help 
{
title: "SrNo",
dataIndex="",
defaultSortOrder: "ascend",
sorter:(a, b) => a.id - b.id,
render:(value, item, index) => (tableParams.pagination.current - 1) * 10 + index+1,
width: "20%",
},
i am using antd Extension library for export to CSV functionality, library export column with header above dataIndex as header, i need srno when i used in render, to export file as srno column in render props it render only in antd table help me.
