### ISSUE TITLE
InputNumber: can't input Hiragana/Full-width Katakana/Full-width Alphanumeric number from the keyboard row

### ISSUE THREAD

**Issue by blue-lightning** [ant-design/ant-design#16415]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l7n1yqr8p9)

### Steps to reproduce
1. Switch keyboard input method to Japanese
2. Switch input key type to Hiragana/Full-width Katakana/Full-width Alphanumeric
3. Input a number from the keyboard row

### What is expected?
InputNumber recognized inputted number

### What is actually happening?
Number isn't inputted

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.3.2 |
| System | Windows 10 x64 |
| Browser | Chrome 71.0 |

---
Numeric keypad works as expected; only the keyboard row displays this behaviour.

**Comment by zombieJ** [comment]
You should use `parse` prop to customize your rule: https://codesandbox.io/s/zxnw7om99m

**Comment by blue-lightning** [comment]
In your code sample, full-width numbers typed in will be recognized by the onChange handler, but clicking outside InputNumber will reset it to the previous value.

**Comment by zombieJ** [comment]
I just provide the sample of how `parse`, convert string to specific format you should use `formatter`. Please ref the official document for more info: https://ant.design/components/input-number/#components-input-number-demo-formatter

**Comment by blue-lightning** [comment]
So I added both a `formatter` and a `parser` but the problem persists. I made a recording to better demonstrate it here: https://imgur.com/a/j873snI

**Comment by zombieJ** [comment]
https://codesandbox.io/s/73r5y5pn81

**Comment by blue-lightning** [comment]
Result here, error persists with number row: https://imgur.com/a/hfJYEx5

**Comment by zombieJ** [comment]
Can not reproduce your replay. Could you paste the string you input it?

**Comment by blue-lightning** [comment]
I only input a number and then press Enter, that is all. Maybe you did your tests with the numeric keypad? The error only shows up if you use the number row in the main keypad (the one right above the QWERTY row).

**Comment by blue-lightning** [comment]
Oh, and make sure you input in full-width numbers (with blank spaces surrounding them, like these: １２３４５), if they are half-width like normal English numbers (12345) then InputNumber works no problem.

**Comment by zombieJ** [comment]
@blue-lightning ，if using full width number, you should also includes them into your `parser` & `formatter` logic.

**Comment by blue-lightning** [comment]
So I fixed it following the suggestion of @zombieJ 
If anyone else wound up having this problem, here's my solution: https://codesandbox.io/s/6xvp9prqk

@zombieJ : I guess there's no plan to add support for international numbers like １, right?

**Comment by zombieJ** [comment]
InputNumber process the normal number like `<input type="number" />`. So may not integrate this.

**Comment by starfruit1009** [comment]
Hi all, 
I had another problem when trying to input numbers using the iPhone's **Japanese keyboard**. 
At some point, it auto-doubles the characters. For example: typing 123 would become 1223...
Please help if you have any suggestion or solution. 
Thank you very much.

**Comment by metapone** [comment]
@starfruit1009 You should open a new issue for that problem.
