### ISSUE TITLE
Checkbox Component add Checkbox.Button will be better

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#16424]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

Design draft display some conditions button, and conditions can be select more than one

### What does the proposed API look like?
like Radio.Component, but the value support Array

**Comment by zombieJ** [comment]
Hmmm... In my view it's more like a tag group: https://ant.design/components/tag-cn/#components-tag-demo-checkable

**Comment by Dolov** [comment]
> Hmmm... In my view it's more like a tag group: https://ant.design/components/tag-cn/#components-tag-demo-checkable
It's a solution，but not so elegant

**Comment by afc163** [comment]
@zombieJ is right.

**Comment by WeamAdel** [comment]
> @zombieJ is right.

I am so sorry, but a tag group is not a checkbox group. Tag checkables are not implemented using checkboxes and have very poor semantics and accessibility.

I had a quick look at similar feature requests, and found someone ready to implement it and even a [pull request](https://github.com/ant-design/ant-design/pull/11526) by someone who implemented it already (I by myself was ready to implement it), so why are you rejecting all these requests?

I've read the design related replies and they does not sound logical, as thousands of developers reimplement this feature to their checkboxes on every project to make their checkables accessible and semantically correct.
