### ISSUE TITLE
antd对IE8的支持

### ISSUE THREAD

**Issue by juneryo** [ant-design/ant-design#1642]
当前的版本对IE8不支持，好像是在es5-sham.min.js中会抛出异常。
```
SCRIPT5022: 引发了异常但未捕获 
component, 行33 字符3955
```
印象中0.12.14版本肯定是可以，后面不大确定，现在1.0.0是不行的。

刚看了下老版本的介绍页：
http://011x.ant.design/docs/spec/introduce
这个在IE8上是OK的

**Comment by xyzget** [comment]
1.0.0版本升级到了 React@15.x
react 15.x 并不支持ie8

**Comment by juneryo** [comment]
@xyzget 
刚才又重新下载了0.12.14,0.12.16和0.12.17这三个版本都试了一下，本地IE8还是抛出异常。
后来发现，是因为没有明确指定redux相关依赖，更新模块后导致。。。
最后明确指定了redux相关模块的版本，并且重新下载模块后，就没问题了。。。
```
    "react-redux": "4.4.5",
    "react-router": "2.2.4",
    "redux": "3.4.0",
    "redux-logger": "2.6.1",
    "redux-thunk": "2.0.1",
```
