### ISSUE TITLE
I want get webkitRelativePath when I use Upload.Dragger with directory, but it doesn't work

### ISSUE THREAD

**Issue by Da-Sheng** [ant-design/ant-design#16426]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://kdasheng.cn/opstool/#/dragger](http://kdasheng.cn/opstool/#/dragger)

### Steps to reproduce
dragger a folder(not click and select) and get children's path   the json is got onChange's file  file.originFileObj.webkitRelativePath

### What is expected?
webkitRelativePath is valid

### What is actually happening?
webkitRelativePath is null character string（ ''）

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | 16.7.0 |
| System | macos 10.12.6 |
| Browser | Chrome 71.0.3578.98 |

**Comment by Da-Sheng** [comment]
you can see console, there's log info

**Comment by Da-Sheng** [comment]
https://codesandbox.io/embed/oqpjmzqqv6

**Comment by Da-Sheng** [comment]
thanks

**Comment by afc163** [comment]
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/507615/57291668-704cf900-70f2-11e9-9d10-4c7ab7f39b11.png">

It works in your codesandbox.

**Comment by Da-Sheng** [comment]
Really? But I drag floder not work
![uploads](https://user-images.githubusercontent.com/23762820/57344183-bcdb1780-7178-11e9-9182-6815043402cd.jpeg)

**Comment by Da-Sheng** [comment]
大神，理我

**Comment by afc163** [comment]
你本地也有一样的问题么。我试了一下 codepen 没问题：https://codepen.io/anon/pen/eaJNqa?&editable=true&editors=001

codesandbox 拿到的是 `''`，我怀疑是 codesandbox 本身的沙箱环境限制。

**Comment by Da-Sheng** [comment]
我本地也有的，http://kdasheng.cn/opstool/#/dragger  这个是我还原我们项目的一小部分，放在这个网站上，并且有log打印的，如果加载不出来请尝试刷新，（common和bundle加载可能顺序变动）

**Comment by afc163** [comment]
不对，codepen 也不行。。

**Comment by Da-Sheng** [comment]
我也是碰到了这种业务才发现这个case的，不过可以跟交互商量先用点击上传的模式，但是这个点我觉得还是暴露一下

**Comment by afc163** [comment]
检查了一下，目前的信息是这样的：

1. Firefox 点击拖拽都能拿到。
2. Chrome 下点击上传能拿到，不过会弹出确认窗口和用户确认权限。
<img width="507" alt="image" src="https://user-images.githubusercontent.com/507615/57434229-1cb2ea80-726d-11e9-9f74-5a861cb3bc80.png">

3.  Chrome 下拖拽上传能拿不到，也不会弹出确认窗口，估计和这个有关系。

**Comment by afc163** [comment]
这个属性本身也不稳定，建议不要用。https://developer.mozilla.org/en-US/docs/Web/API/File/webkitRelativePath

<img width="713" alt="image" src="https://user-images.githubusercontent.com/507615/57434402-7d422780-726d-11e9-8e2e-95131a2c0b5f.png">

**Comment by afc163** [comment]
找到了一个方式做兼容，`webkitGetAsEntry` 可以读出来一个 `fullPath`，内容和 `webkitRelativePath` 是一样的：https://github.com/react-component/upload/pull/184

**Comment by Da-Sheng** [comment]
单膝跪谢
