### ISSUE TITLE
How to custom select dropdown position(top or bottom) by a property？

### ISSUE THREAD

**Issue by cjchnwscqwsbsy** [ant-design/ant-design#16428]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I don't know what's good about it, but users ask for it.

### What does the proposed API look like?
Fixed the drop-down box position through an attribute(top or bottom)

**Comment by afc163** [comment]
https://github.com/react-component/select/issues/254
