### ISSUE TITLE
Modal组件的入场动画过于单一

### ISSUE THREAD

**Issue by fubd** [ant-design/ant-design#16435]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以提供不同的动画props选择，如Side , Grow等

### What does the proposed API look like?
```
<Modal
          transitions="grow"
          title="Vertically centered modal dialog"
          centered
          visible={this.state.modal2Visible}
          onOk={() => this.setModal2Visible(false)}
          onCancel={() => this.setModal2Visible(false)}
        >
          <p>some contents...</p>
          <p>some contents...</p>
          <p>some contents...</p>
        </Modal>
```

**Comment by afc163** [comment]
`transitionName="fade"` `transitionName="slide-up"` `transitionName="slide-left`

**Comment by fubd** [comment]
@afc163 文档中似乎没有查找到有transitionName

**Comment by afc163** [comment]
对，`transitionName` 作为强设计属性，没有对外开放。

**Comment by huangyCode** [comment]
antd Modal组件打包后关闭动画为旋转

**Comment by ecccho** [comment]
transitionName=""
maskTransitionName=""

fade
zoom
zoom-big
zoom-big-fast
zoom-up
zoom-down
zoom-left
zoom-right
slide-up
slide-down
slide-left
slide-right
move-up
move-down
move-left
move-right

**Comment by YagamiNewLight** [comment]
为什么我设置了transitionName之后直接关闭不了Modal了呢
复现：https://stackblitz.com/edit/react-lf37fo-vdcr1u?file=index.js

**Comment by YagamiNewLight** [comment]
目前所有Modal动画都必须加上`ant-`前缀，如`ant-move-up`, 否则无法关闭modal

**Comment by vitalijalbu** [comment]
Hi guys, how to change transition of the modal? I don't like the zoom effect... want the slide-up
Using 5.5 version. Thanks
