### ISSUE TITLE
3.16.3 -> 3.16.4的升级中，编译出来的lib里面，每个组件最下面多了一行module.exports = exports.default;	

### ISSUE THREAD

**Issue by jinboker** [ant-design/ant-design#16433]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://unpkg.com/antd@3.16.4/lib/divider/index.js](https://unpkg.com/antd@3.16.4/lib/divider/index.js)

### Steps to reproduce
https://unpkg.com/antd@3.16.4/lib/divider/index.js
https://unpkg.com/antd@3.16.3/lib/divider/index.js 

对比最后一行 (diff过两个文件，只有最后一行有变化)

### What is expected?
var divider_1 = require("antd/lib/divider");
exports.Divider = divider_1.default;

可以拿到Divider这个组件

### What is actually happening?
我们有发一些基于antd组件的包
import方式为import Divider from 'antd/lib/divider'; 

tsc后的代码为：
var divider_1 = require("antd/lib/divider");
exports.Divider = divider_1.default;

但16.6.4中，lib/divider/index.js 中最后多出来了一行module.exports = exports.default;  导致上面的代码中拿到的default全部是undefined

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | 16.8.4 |
| System | OSX |
| Browser | chrom最新版 |

**Comment by ztplz** [comment]
改成这样 `import * as Divider from 'antd/lib/divider';`

**Comment by jinboker** [comment]
> 改成这样 `import * as Divider from 'antd/lib/divider';`

试过，包括import Divider = require('antd/lib/divider')，类型会出问题，得专门去处理

我很好奇的是为什么16.6.4中编译出来的代码里面会突然出现这个改动，这看起来并不是必须的

**Comment by ztplz** [comment]
这跟antd没关系啊    babel-plugin-add-module-exports改了

**Comment by jinboker** [comment]
> 这跟antd没关系啊 babel-plugin-add-module-exports改了

翻了下babel-plugin-add-module-exports的readme，这插件你们是在发布3.16.4的时候突然加的？
那可不可以option里面加个"addDefaultProperty": true，最后编译出来的时候多一个module.exports.default = exports['default']

**Comment by zombieJ** [comment]
一直都有的，以前 `babel-plugin-add-module-exports` 是 `1.0.0` 现在是 `1.0.2`。`addDefaultProperty` 我可以加一下，看看效果。

**Comment by ztplz** [comment]
加addDefaultProperty就行了  这个插件没用加进去做什么

**Comment by zombieJ** [comment]
远古的插件，先加上 `addDefaultProperty` 有问题再说了。

**Comment by ycjcl868** [comment]
这个是有必要的，特别是在 node 里，还有做 ssr 的场景

**Comment by fayhy** [comment]
语言包配置，3.170 -> 3.18.1，最后的 module.exports = exports.default; 被去掉了  
require('antd/lib/locale-provider/zh_CN') 和原本不一样了，这个还会改回去么？

https://unpkg.com/antd@3.17.0/lib/locale-provider/zh_CN.js  
https://unpkg.com/antd@3.18.1/lib/locale-provider/zh_CN.js

**Comment by zombieJ** [comment]
@fayhy , 不会了。之前是为了兼容 babel5 做的，这个老坑从 `3.18.1` 就舍弃了。如果使用 require 就改成 `require(xxx).default` 吧~
