### ISSUE TITLE
Menu selectedKeys not working with re-render

### ISSUE THREAD

**Issue by dancon** [ant-design/ant-design#16434]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/dancon/pen/NVWLOM](https://codepen.io/dancon/pen/NVWLOM)

### Steps to reproduce
Open the url above you can reproduce the issue

### What is expected?
The menu item is selected that is specified keys via prop `selectedKeys` when re-render with async fetch data.

### What is actually happening?
does not select the menu item

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.4 |
| System | Mac 10.14.4 |
| Browser | chrome 74.0.3729.131 |

**Comment by afc163** [comment]
`key` should be string: https://codepen.io/anon/pen/GaRXVM

https://reactjs.org/docs/lists-and-keys.html
