### ISSUE TITLE
常用布局添加侧边导航展开收起模式

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1643]
以演示的方式提供。

**Comment by ddcat1115** [comment]
不平滑问题调整 [http://gitlab.alipay-inc.com/ued/visual/issues/92]

**Comment by leejaen** [comment]
这个功能怎么用？api上没找到

**Comment by benjycui** [comment]
> 以演示的方式提供。

@leejaen 

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
