### ISSUE TITLE
Unable to control Dropdown Menu hiding when using Dropdown SubMenu

### ISSUE THREAD

**Issue by davidmcooper** [ant-design/ant-design#16430]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/GaRmXw?editors=0010](https://codepen.io/anon/pen/GaRmXw?editors=0010)

### Steps to reproduce
1. Expand menu
2. Expand submenu
3. Click submenu item

### What is expected?
Menu should remain open when submenu item not matching the specified key is clicked.

### What is actually happening?
Submenu and menu are closing

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 72.0.3626.121 |

---
It would be nice to be able to keep both the menu and submenu open when clicking a submenu whose key doesn't match the logic specified for opening and closing.  There doesn't seem to be a way to keep the submenu visible after clicking.

**Comment by zombieJ** [comment]
`visible` props is controlled by Dropdown component. SubMenu is controlled by Menu. So if you want to keep SubMenu visible can use `openKeys` props: https://codesandbox.io/s/5k8v71vq1l

**Comment by doerme** [comment]
but now openKeys option is not in ItemType
