### ISSUE TITLE
使用form.resetFields方法重置Slider后，Slider的画面显示效果不变

### ISSUE THREAD

**Issue by xuzhy** [ant-design/ant-design#1644]
前提：已通过form的create、getFieldProps等方法等关联Form与Slider组件。
现象：当调用form.resetFields方法重置组件后，Slider组件的value变为undefined，但画面显示效果不变。

代码片段
```jsx
<FormItem label="等级：" { ...formItemLayout }>
    <Slider marks={ ['0', '1', '2', '3', '4', '5', '6'] } min={ 0 } max={ 6 } { ...getFieldProps('level') } />
</FormItem>
```

画面显示效果
重置前
![sliderafterresetting](https://cloud.githubusercontent.com/assets/8393696/15172845/13ea0f90-178b-11e6-9f34-e3626b453340.png)
重置后
![sliderbeforeresetting](https://cloud.githubusercontent.com/assets/8393696/15172846/13f14788-178b-11e6-909f-68d90c6db42f.png)
期望结果
![sliderexpectresult](https://cloud.githubusercontent.com/assets/8393696/15172847/14106618-178b-11e6-84df-0966d53eab7c.png)
## 环境信息
- antd(<=1.0.0):
- 操作系统(Windows 7(64-bit)):
- 浏览器(Chrome 50.0.2661.94 m(64-bit)):

**Comment by benjycui** [comment]
```js
getFieldProps('level', { initialValue: 0 })
```

**Comment by benjycui** [comment]
Please read [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
