### ISSUE TITLE
Add features to the checkbox.

### ISSUE THREAD

**Issue by tranducit95** [ant-design/ant-design#16442]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently I am using the "image checkbox", it is not synchronized with ant design, I hope ant design will add this feature.

### What does the proposed API look like?
http://tabler-react.com/form-elements

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/57235832-5d84e680-7056-11e9-8ddb-2a88b7ceac34.png)
Broken link.

**Comment by tranducit95** [comment]
@ztplz https://github.com/tabler/tabler-react

**Comment by afc163** [comment]
We may not provide this feature recently, you have to wrap it by your own.

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/13719
