### ISSUE TITLE
Form可以提供一个方法比如clearFieldsValue来清除FormItem的InitialValue

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#16441]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现有的resetFields只是重置为InitialValue，遇到的很多场景都是重置时需要清除掉FormItem的值。不知道能否提供一个这种功能的api

### What does the proposed API look like?
clearFieldsValue

**Comment by afc163** [comment]
resetFieldsValue

**Comment by afc163** [comment]
resetFieldsValue 比较合理，因为没法好办法判断对一个表单控件来说什么是空值。

**Comment by gonenoob** [comment]
> resetFieldsValue

setFieldsValue ??  一般情况下空值不都是undefined吗？
或者提供一个获取所有name的方法（当然用getFieldsValue转换也能做）

**Comment by gonenoob** [comment]
用setFieldsValue就需要手动去map所有的key一个个设置了

**Comment by afc163** [comment]
undefined 不行的，表单控件约定上不一定会处理 `undefined`。

`<Control prop={undefined} />` 等效于 `<Control />`。

**Comment by afc163** [comment]
undefined 不行的，表单控件约定上不一定会处理 `undefined`。

`<Control prop={undefined} />` 等效于 `<Control />`。

**Comment by gonenoob** [comment]
对所有的formItem使用setFIeldsValue来设置值为undefined，就可以清空InitialValue了额。没有特殊的吧..
