### ISSUE TITLE
[1557220630323: "11", 1557220630628: "22"]  造成这种情况

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design#16456]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/pmJzOX?editors=0010](https://codepen.io/anon/pen/pmJzOX?editors=0010)

### Steps to reproduce
https://codepen.io/anon/pen/pmJzOX?editors=0010

### What is expected?
这是什么数组

### What is actually happening?
这是什么数组

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | ^16.4.0 |
| System | windows |
| Browser | Google Chrome |
![image](https://user-images.githubusercontent.com/23191825/57288671-7dff8000-70ec-11e9-8b06-46e03bcd4934.png)

**Comment by zheng1013757145** [comment]
> 你好@ zheng1013757145。请提供此链接https://u.ant.design/codesandbox-repro或最小的GitHub存储库，以提供在线复制。标记为的问题`Need Reproduce`将在7天内没有活动时关闭。
> 
> 你好@ zheng1013757145，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击[此处](https://u.ant.design/codesandbox-repro)创建一个代码盒或者提供一个最小化的GitHub仓库.7天内未跟进的问题会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codepen.io/anon/pen/pmJzOX?editors=0010

**Comment by zheng1013757145** [comment]
https://codepen.io/anon/pen/pmJzOX?editors=0010

**Comment by afc163** [comment]
What is your expection and what is actually happening? Please decrible your situation with readable style.

**Comment by zheng1013757145** [comment]
What is expected?
预期我想得到的结果是 names: [111, 222 ,333]

What is actually happening?
实际输出的结果是 names: [ 1557222592797: 111, 1557222592865: 222, 1557222592865: 333 ]

**Comment by afc163** [comment]
具体操作的步骤是什么呢？

**Comment by zheng1013757145** [comment]
> 具体操作的步骤是什么呢？

https://codepen.io/anon/pen/pmJzOX?editors=0010

**Comment by afc163** [comment]
你好像没有回答我的问题

**Comment by zheng1013757145** [comment]
> 你好像没有回答我的问题

不用了，谢谢

**Comment by afc163** [comment]
是解决了么，可以分享一下过程么，说不定也有其他人会碰到。

**Comment by zheng1013757145** [comment]
> 是解决了么，可以分享一下过程么，说不定也有其他人会碰到。

动态添加时需要一个唯一的ID，这个ID不能使用时间戳。
example中初始化阶段
`getFieldDecorator('keys', { initialValue: [{
      names: '',
      id: + new Date() // 此处我使用 时间戳作为数据的唯一ID
    }] });`
需要修改为 
`getFieldDecorator('keys', { initialValue: [{
      names: '',
      id: 0
    }] });`
添加时ID 自增+1
`const nextKeys = keys.concat({
      names: '',
      id: ++id
    });`
如果把时间戳作为ID，会造成这样的结果 [1557220630323: '11', 1557220630628: '22']
如果按照数组索引作为ID，结果为 ['11' , '22']

只是解决了，但我并不知道为什么会输出这种结果 [1557220630323: '11', 1557220630628: '22']

**Comment by afc163** [comment]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/507615/57346282-7f7a8800-7180-11e9-9224-14358b7216ef.png">

貌似控制台就是这样展示数组的。

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/57346956-2e1fc800-7183-11e9-882c-6d9ed4050f92.png)
索引值大了就这么表示了   v8的数组实现有快慢两种 快的是传统意义上内存连续的数组  慢的是`hashtable`

**Comment by zheng1013757145** [comment]
> <img alt="image" width="245" src="https://user-images.githubusercontent.com/507615/57346282-7f7a8800-7180-11e9-9224-14358b7216ef.png">
> 
> 貌似控制台就是这样展示数组的。

学习了，谢谢

**Comment by zheng1013757145** [comment]
> ![image](https://user-images.githubusercontent.com/17755202/57346956-2e1fc800-7183-11e9-882c-6d9ed4050f92.png)
> 索引值大了就这么表示了 v8的数组实现有快慢两种 快的是传统意义上内存连续的数组 慢的是`hashtable`

谢谢，我这是一个愚蠢的问题
