### ISSUE TITLE
Popover API文档error

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#1645]
发现一个小的文档问题：
Popover 组件：antd API文档里面，卡片内容参数名称现在是content，但不work，换成之前的overlay就work，看看这是变了代码没同步还是文案错误。
错误页面：http://ant.design/#/components/popover?_k=7q9s8g

**Comment by afc163** [comment]
http://ant.design/#/docs/react/changelog?scrollTo=1.0.0

http://012x.ant.design/

**Comment by tianyacsdn** [comment]
多谢！使用overlay属性之后，果然就可以了
