### ISSUE TITLE
对组件父层进行scale缩放会导致组件字体模糊

### ISSUE THREAD

**Issue by linxiangjun** [ant-design/ant-design#16458]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://n1joyr5kj.codesandbox.io/)

### Steps to reproduce
父级DOM设置transform：scale(.6, .6)会导致比如展开Select组件下拉列表时显示的文字模糊（请仔细比较字体的显示效果）

### What is expected?
显示的文字显示清晰

### What is actually happening?
文字模糊

| Environment | Info |
|---|---|
| antd | 3.16.2 |
| React | 16.7.0 |
| System | win10 |
| Browser | Chrome 74.0.3729.108 |

**Comment by afc163** [comment]
这应该是 Chrome 渲染问题，感觉我们啥也做不了。

**Comment by ztplz** [comment]
https://stackoverflow.com/questions/14677490/blurry-text-after-using-css-transform-scale-in-chrome

**Comment by afc163** [comment]
@linxiangjun 你能在本地试试 https://stackoverflow.com/a/16878602 这里面的方法能否修复么？

**Comment by linxiangjun** [comment]
@afc163 测试了下，这两个属性加上选择下拉框其他的元素不会抖动一下了，但是本身就变得模糊了...所以还是没有起到效果

**Comment by suedar** [comment]
请问有办法解决吗
