### ISSUE TITLE
希望Input组件defaultValue属性是受控的。

### ISSUE THREAD

**Issue by Freud-K** [ant-design/ant-design#16451]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前Input 组件的defaultValue是非受控的，值并不会动态更新，满足不了用户动态添加默认值的需求。react提供的input的defaultValue则是受控的。

### What does the proposed API look like?
defaulValue属性受控

**Comment by afc163** [comment]
这不符合 React 的规范，不能这么做，受控请使用 value 属性。

https://reactjs.org/docs/forms.html#controlled-components
