### ISSUE TITLE
How can i submit a form from parent componentt?

### ISSUE THREAD

**Issue by justinlazaro-ubidy** [ant-design/ant-design#16468]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi i want to submit the form, from parent component,

```
Class Parent extends Component {
  ....
  render() {
   return (
    <div>
       <ChildForm />

       <button>Submit </button>
    </div>
    )
  }
}

```

### What does the proposed API look like?
form

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#components-form-demo-form-in-modal
