### ISSUE TITLE
Only Drag and Drop Upload Component.

### ISSUE THREAD

**Issue by DavidSichau** [ant-design/ant-design#16463]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If one wants a text editor with the possibility to upload files. e.g. a markdown editor. One can currently not use the Upload Component as Wrapper as this would trigger on the Enter key the file dialog.

### What does the proposed API look like?
Add `openFileDialogOnClick` Prop to Upload.

Pull request for react-component/upload is done here: https://github.com/react-component/upload/pull/180

**Comment by afc163** [comment]
Please fix ci issue in https://github.com/react-component/upload/pull/180

**Comment by afc163** [comment]
Already supported in https://github.com/react-component/upload/pull/125 and https://github.com/ant-design/ant-design/pull/12347
