### ISSUE TITLE
table组件行列合并功能的优化

### ISSUE THREAD

**Issue by wd603546401** [ant-design/ant-design#16467]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
减轻工作量

### What does the proposed API look like?
# 场景：如果在一行数据中，A B C三列需要合并成一列

**Comment by afc163** [comment]
原生的 table 行列合并也需要去掉后面的单元格，不然会溢出。

https://codepen.io/anon/pen/wbaOEV

**Comment by wd603546401** [comment]
学习了
