### ISSUE TITLE
Theme customization via ant-theme-file does not work as documented

### ISSUE THREAD

**Issue by rtek** [ant-design/ant-design#16464]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/rtek/antd-theme-file-bug](https://github.com/rtek/antd-theme-file-bug)

### Steps to reproduce
Build the linked project: 
```
yarn install
webpack
```

Browse to public/

### What is expected?
The alert style could be red

### What is actually happening?
The alert style is the default of blue

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.6 |
| System | win7 x64 |
| Browser | chrome |

---
The method here: https://ant.design/docs/react/customize-theme#Customize-in-webpack does not work because the @ant-theme-file is resolved to ./override.js before modifiedVars is applied. Variables in an import are handled differently than all other variables in Less. It appears to import ASAP.

<del>
A workaround is to edit themes/index.less to force less to wait for the ant-theme-file definition.

```
@import './default.less';

//@ant-theme-file: ~'./override.less';
@import (optional) '@{ant-theme-file}';
```
</del>

A work around from https://github.com/less/less.js/issues/3179 is to hack the import statement using modify vars like so:

```
modifyVars: {
   'ant-theme-file': "; @import '" + path.resolve(__dirname, './assets/less/theme.less') + "'",
},
```

Which renders to

```
@ant-theme-file: ; @import '.../assets/less/theme.less';
```

**Comment by hutsi** [comment]
the same for me

**Comment by zombieJ** [comment]
Since `(optional)` will affect antd build as `Maximum call stack size exceeded` error when `@ant-theme-file` is not defined.
Maybe should find another way to handle this.

**Comment by zombieJ** [comment]
ref: https://github.com/webpack-contrib/less-loader/issues/184

**Comment by rtek** [comment]
Some background from less. Will investigate further... https://github.com/less/less.js/issues/3179

**Comment by rtek** [comment]
Added work around from https://github.com/less/less.js/issues/3179#issuecomment-368058264

**Comment by zombieJ** [comment]
Hmm... it's little strange for this. Let me test it later.

**Comment by rtek** [comment]
> Hmm... it's little strange for this. Let me test it later.

Agreed - but this little hack just appends custom theme import last, which is the "correct" way to do it in less. 

Reviewing the various discussions, the fundamental model for less variables is that they are evaluated after everything is parsed. This is fine for everything except imports because imports alter the order and content of what is being parsed depending on when you evaluate the import. It appears that they concluded with "evaluate the import as soon as possible", so modifyVars will only work if the variable is never defined.

**Comment by zombieJ** [comment]
Test and find the golden key:
```
modifyVars: {
  'hack': `true; @import "${lessPath}";`,
},
```
