### ISSUE TITLE
Table可编辑行

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#16476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lyz1m3r8m9)

### Steps to reproduce
把Index.js下
 ```
<a disabled={editingKey !== ''} onClick={() => this.edit(record.key)}>Edit</a>
 ```
替换为
 ```
<a  onClick={() => this.edit(record.key)}>Edit</a>
```

### What is expected?
单元格的内容不会同步改变。

### What is actually happening?
如果在编辑一行的同时，去编辑另一行就会一起改变。

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.7.0 |
| System | win 10 |
| Browser | google |

---
客户 可能会使用双击进入编辑，  可能会同时编辑多个行

**Comment by zombieJ** [comment]
官方示例是单行的，如果需要做多行编辑的话就需要自己写一下数据管理逻辑。
