### ISSUE TITLE
树形控件-可搜索，不匹配关键字的节点能否不展示

### ISSUE THREAD

**Issue by 7Charlotte** [ant-design/ant-design#16475]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
搜索的目的是为了快速找到目标节点，现状是发起搜索会展开所有的节点并将匹配节点标红，这种方式在节点数量很多且目标节点在层级树靠后位置的情况下，无法快速定位目标节点。

### What does the proposed API look like?
输入关键字搜索节点时，仅展开并显示匹配到关键字的节点及其祖先节点和子节点。其他不匹配的节点都不展示，以便能快速定位目标节点。

**Comment by zombieJ** [comment]
Duplicate of #7750

**Comment by Peachick** [comment]
可以写个过滤算法，重写渲染下treeData

**Comment by alienzhangyw** [comment]
https://github.com/ant-design/ant-design/issues/7750#issuecomment-974770043
