### ISSUE TITLE
Only Drag and Drop Upload Component.

### ISSUE THREAD

**Issue by DavidSichau** [ant-design/ant-design#16470]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

@afc163 I made an error on mixed the Enter and Click in the Description. This aims at providing a similar way to avoid on Enter as on Click as it is already implemented. I am really sorry for the error and caused confusion.

### What problem does this feature solve?
If one wants a text editor with the possibility to upload files. e.g. a markdown editor. One can currently not use the Upload Component as Wrapper as this would trigger on the Enter key the file dialog.

### What does the proposed API look like?
Add `openFileDialogOnEnter` Prop to Upload.

Pull request for react-component/upload is done here: https://github.com/react-component/upload/pull/181

**Comment by afc163** [comment]
https://github.com/react-component/upload/pull/182

Released in `rc-upload@2.6.5`.
