### ISSUE TITLE
how can I remove "x" feature for multiple Select 

### ISSUE THREAD

**Issue by Gamehu** [ant-design/ant-design#16472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
下拉框多选情况下，某种场景下，用户可添加数据但是不能删除已添加的

### What does the proposed API look like?
是否能有一个boolean类型的属性进行该设置，谢谢

**Comment by afc163** [comment]
Try `disabled` in Option.

https://codesandbox.io/s/zxj7z2x6om

**Comment by ps2qwert** [comment]
> Try `disabled` in Option.
> 
> https://codesandbox.io/s/zxj7z2x6om

这个时候，我想把默认的禁用值给删掉，有什么好办法么

**Comment by yoyo837** [comment]
state管理disabled或者相关的状态

**Comment by ps2qwert** [comment]
> state管理disabled或者相关的状态
![image](https://user-images.githubusercontent.com/13064300/90759749-754bb100-e313-11ea-8f29-0714adae621b.png)
是可以管理，但目前被禁用的已经没有×了，没有可以交互的地方。

**Comment by yoyo837** [comment]
你需要交互来删除，你就不要去掉`x`， state管理值或者状态，并不需要交互。

**Comment by ps2qwert** [comment]
事实上我并不想去掉×，但如果数据被禁用了以后，该组件会自动把×去掉。

**Comment by yoyo837** [comment]
那我没理解你想要什么

**Comment by ps2qwert** [comment]
把默认被禁用的值，通过交互的方式删掉。比如：之前有个枚举的数据，我选择了，后面我把其中的一条数据禁用。这时我还能看到它的存在，我想把它从选择中给删掉

**Comment by yoyo837** [comment]
前面说的做法就可以呀

**Comment by yoyo837** [comment]
前面说的做法就可以呀
