### ISSUE TITLE
Reduced distrubution size (currently 43MB)

### ISSUE THREAD

**Issue by sheerun** [ant-design/ant-design#16488]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currentl node package size is 43 MB which can be a problem when deploying to low-resource platforms when SSR is enabled (e.g. next.js   now or aws lambda). Most of the size takes full antd.js bundle, its sourcemap, minified version and its source map, plus locales versions:

```
   38M dist/                  6M antd-with-locales.
    2M lib/                   6M antd-with-locales.
    2M es/                    6M antd.min.js.map
                              6M antd.js
                              5M antd-with-locales.
                              5M antd.js.map
                              2M antd-with-locales.
                              2M antd.min.js
```

I think antd has become so huge it would be antipattern for anyone to use antd.js or antd.min.js which are 6MB and 2MB respectively. You could both reduce package size to 4MB and encourage using antd with bundlers by removing dist folder. If someone really wants to use distribution files he/she can use some CDN like cdnjs.

### What does the proposed API look like?
Just remove dist folder from npm package (of course with major bump in semver)

**Comment by zombieJ** [comment]
Remove `dist` folder is a breaking change which should be avoid. It should to do so in other way.

ref: #12011 #14542

**Comment by sheerun** [comment]
That's why I said it's reasonable to do it during major semver version
bump, not now.
