### ISSUE TITLE
Popover的子元素是自定义组件时会失效

### ISSUE THREAD

**Issue by redraiment** [ant-design/ant-design#16486]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/redraiment/antd-popover-issue](https://github.com/redraiment/antd-popover-issue)

### Steps to reproduce
1. git clone https://github.com/redraiment/antd-popover-issue.git
2. yarn
3. yarn start
4. 浏览器访问 http://localhost:3000
5. 鼠标移动到文字Hello world上。

### What is expected?
期望能弹出提示框。

### What is actually happening?
没有弹出提示框。

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.6 |
| System | macOS High Sierra 10.13.6 (17G5019) |
| Browser | 73.0.3683.103（正式版本）（64 位） |

---
换成 Welcome 换成 class 形式也一样有问题，但如果把 render 的内容直接写在 Popover 里是没问题的。两种形式的自定义的组件都有问题。

**Comment by afc163** [comment]
#4270
#15909
#12812
