### ISSUE TITLE
Cascader级联选择可以支持多选吗

### ISSUE THREAD

**Issue by Mike-Zhu** [ant-design/ant-design#16481]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
多品类场景需要

### What does the proposed API look like?
ui类型 => Tree树形控件的select化

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5026

**Comment by ZFtime** [comment]
弱弱的问一句，你们如何在ant里面写级联多选的

**Comment by afc163** [comment]
TreeSelect
