### ISSUE TITLE
Icon.createFromIconfontCN 的 scriptUrl 不支持使用本地js文件?

### ISSUE THREAD

**Issue by ishowman** [ant-design/ant-design#16480]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w0mkxmz8j7)

### Steps to reproduce
icon.js的scriptUrl使用默认值，图标展示正常。
将icon.js中的scriptUrl值改为注释掉的本地url，刷新页面，无法显示图标。

### What is expected?
图标正常显示

### What is actually happening?
devtool报错，图标不显示

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | react |
| System | macos |
| Browser | chrome |

---
业务场景：部分客户不支持cdn链接，希望使用本地图标

**Comment by afc163** [comment]
本地图标建议直接上 svg。iconfont 是需要部署到网络上的。

**Comment by FreeRide-Joe** [comment]
`scriptUrl` 传入空字符串，然后直接使用 `import './style/iconfont.js'` 即可

**Comment by he426100** [comment]
@FreeRide-Joe  import './style/iconfont.js' 这样会报错，在public/index.html里面直接用script引入没问题

**Comment by zphtown** [comment]
> `scriptUrl` 传入空字符串，然后直接使用 `import './style/iconfont.js'` 即可

人才啊，vue3+vite里面，使用createFromIconfontCN + import ./iconfont.js 一直提示以下错误
Uncaught SyntaxError: The requested module '/src/components/Iconfont/icons/iconfont.js?t=1662617840684' does not provide an export named 'default' 

是你的方法可以直接了，感谢

**Comment by cp3hnu** [comment]
> `scriptUrl` 传入空字符串，然后直接使用 `import './style/iconfont.js'` 即可

这是什么原理？
