### ISSUE TITLE
table组件的tree模式，能否像tree组件一样选择控制？

### ISSUE THREAD

**Issue by YangZhouChaoFan** [ant-design/ant-design#1649]
能否像tree一样选择控制，自己实现，有点困难，求大神发挥......
![image](https://cloud.githubusercontent.com/assets/13232941/15173893/53253616-1791-11e6-8163-f2ebcad7141e.png)

**Comment by afc163** [comment]
可以参考：http://ant.design/#/components/table?scrollTo=components-table-demo-row-selection-and-operation

**Comment by bombless** [comment]
问了他，他需要的是在勾选或者取消勾选的时候子树上的节点也跟着勾选过取消勾选的功能

**Comment by YangZhouChaoFan** [comment]
![image](https://cloud.githubusercontent.com/assets/13232941/15311898/146b21a6-1c32-11e6-8c18-66c94198a548.png)
等后期加入支持。。。
