### ISSUE TITLE
the mode about time in RangePicker is not effect

### ISSUE THREAD

**Issue by babycannotsay** [ant-design/ant-design#16492]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xp6p0z79yq)

### Steps to reproduce
click RangePicker

### What is expected?
the mode should be time

### What is actually happening?
the mode is date

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.9.0 |
| System | macOS Mojave 10.14.3 |
| Browser | chrome 73.0.3683.103 |

**Comment by Zhou-Bill** [comment]
i have the same problem, how to solve?
