### ISSUE TITLE
如何阻止在页面宽度较小时,form 自动变成vertical排版且colon消失

### ISSUE THREAD

**Issue by aNameHere** [ant-design/ant-design#16499]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/OYMRgK?&editable=true&editors=001](https://codepen.io/anon/pen/OYMRgK?&editable=true&editors=001)

### Steps to reproduce
浏览器宽度调整到最小

### What is expected?
表单排版不变, 冒号依然在

### What is actually happening?
当宽度比较小的时候, 就算form指定了是horizontal, colon={true},依然自动变成了vertical排版, colon消失

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | latest |
| System | mac os |
| Browser | chrome |

**Comment by zombieJ** [comment]
这是 Form 自带的响应式布局，如果你不需要的话可以直接覆盖掉样式。

**Comment by wenmin92** [comment]
> 这是 Form 自带的响应式布局，如果你不需要的话可以直接覆盖掉样式。

如何覆盖样式以去掉响应式？

**Comment by pysunday** [comment]
同问

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/42957#issuecomment-1588808558
