### ISSUE TITLE
Table 组件在屏幕缩放为 125% 时固定列宽度存在误差

### ISSUE THREAD

**Issue by zoffyzhang** [ant-design/ant-design#16495]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xjj1kyoqoq)

### Steps to reproduce
同时满足以下条件:
1. 屏幕缩放为 125% 或 175%
2. 至少存在两列固定列
3. 固定列的 width 满足某些组合，比如 [90,90]、[110,110]、[110,110,110]，我没观察出规律

### What is expected?
fix this bug

### What is actually happening?
固定列的宽度并不等于设置的 column width

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.9.0 |
| System | win10 |
| Browser | chrome 74 |

**Comment by afc163** [comment]
有截图么，我这里无法结束。

**Comment by zoffyzhang** [comment]
<img width="742" alt="微信图片_20190509170912" src="https://user-images.githubusercontent.com/11470090/57441855-5db2fb00-727d-11e9-8e68-b0c35b5f36ab.png">

**Comment by zombieJ** [comment]
能截一下没有审查元素的图吗，看看是哪里没对齐。

**Comment by zoffyzhang** [comment]
![TIM图片20190513204033](https://user-images.githubusercontent.com/11470090/57622105-7f82e980-75bf-11e9-92e6-c1f643e10c53.jpg)

我之前是在公司的13寸和24寸屏幕上发现的问题，上面是在我的15寸笔记本上截的图，都是1920*1080分辨率缩放125%。奇怪的是这里的固定列又是对齐的，但固定列的宽度依然存在偏差，导致横向滚动后看到了额外的竖线

**Comment by zombieJ** [comment]
试了一下，这个额外的竖线似乎是 Chrome 缩放计算 column 宽度的 bug。直接指定它渲染也是带小数点的：
<img width="500" alt="屏幕快照 2019-05-14 下午1 42 15" src="https://user-images.githubusercontent.com/5378891/57673378-45145d80-764e-11e9-8b47-a2f6ab06d6b8.png">

其他游览器没这个问题。
