### ISSUE TITLE
图标字体下载引用侵权问题

### ISSUE THREAD

**Issue by enjoy-wind** [ant-design/ant-design#16490]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
咨询下目前antd框架在线引用了https://at.alicdn.com/域名下的图标字体woff。目前公司想要下载字体然后部署到全球CDN服务器，然后再引用到antd项目里面，请问此操作是否会引起侵权。

### What does the proposed API look like?
回答是否侵权

**Comment by zombieJ** [comment]
图标和 antd 都是 MIT license:
<img width="992" alt="屏幕快照 2019-05-09 上午10 50 19" src="https://user-images.githubusercontent.com/5378891/57423863-43aaf580-7248-11e9-93e2-2c1d2f2674b5.png">
