### ISSUE TITLE
Dropdown.Button 的 overlay menu中如果只包含一个 Upload，overlay的位置第一次会偏移。

### ISSUE THREAD

**Issue by xpauline24** [ant-design/ant-design#16500]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7m8m71pvw1)

### Steps to reproduce
Dropdown.Button 的overlay menu中只设置一个menuItem，内容是 Upload 组件

### What is expected?
统一Dropdown overlay的位置，设置bottomRight后，一直都是bottomRight

### What is actually happening?
鼠标滑入第一次显示的位置总是bottomLeft，不符合预期

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.x |
| System | macOS |
| Browser | Chrome 72.0.3626.109 |

**Comment by xpauline24** [comment]
发现给 overlay menu 设置宽度可以解决。

**Comment by zombieJ** [comment]
嗯，Upload 为了支持 ssr 组件是在 didMount 之后添加的。这导致 dropdown 第一次渲染的时候 Upload 还是空的。目前没什么好办法去处理。按照你的解法做就行了。
