### ISSUE TITLE
Notification with custom Icon has displaced title & smaller icon

### ISSUE THREAD

**Issue by TeNNoX** [ant-design/ant-design#16503]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/k9l53oy86o)

### Steps to reproduce
Add `icon: <Icon type="smile" />` property to notification.success() call.

### What is expected?
Title is in same position as with non-custom icon. 
Icon is the same size as non-custom icon.

### What is actually happening?
Title is displaced.
Icon is too small.

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.6 |
| System | Deepin 15.9.3 |
| Browser | Chromium 66.0.3359.181 |

---
It happens because the element with class `anticon` is missing the class `ant-notification-notice-icon` and thus does not match the rule:
```css
.anticon.ant-notification-notice-icon {
    position: absolute;
}
```
Probably best to adapt the CSS rule matcher to e.g. only `.ant-notification-notice-icon` - fixes both issues.

**Comment by zombieJ** [comment]
ref #15512
