### ISSUE TITLE
If form fields rules validator is a 'async function', form validate would be called twice 

### ISSUE THREAD

**Issue by LIPSong** [ant-design/ant-design#16502]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2p16722zn?fontsize=14)

### Steps to reproduce
Tap submit and console will log same result twice

### What is expected?
Tab submit and console  should log same result once

### What is actually happening?
Tap submit and console will log same result twice

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | ^16.7.0 |
| System | MacOS mojave |
| Browser | chrome 74 |

**Comment by zombieJ** [comment]
validate support promise which mean callback should not use: https://codesandbox.io/s/km8xz76wwo
