### ISSUE TITLE
Select组件onSelect事件是否可以被阻止

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#1651]
##场景
使用select组件如下，option包含全部选项及各item选项
![image](https://cloud.githubusercontent.com/assets/17123400/15175887/08ef30ec-179b-11e6-847c-f218f5e1d701.png)
1、当选中【全部区域】时，取消之前已选的内容；
2、当选中的为为非全部时，检查已选项是否包含【全部区域】，若是，则弹框提示取消【全部区域】
以上逻辑可在onSelect或onChange事件中进行编写，但由于事件均无法被阻止，故计时添加以上逻辑，当前选中项依然会被加入到最后的结果中

有什么办法可以处理以上情景，多谢！

**Comment by benjycui** [comment]
`value` 是受控属性。

**Comment by hhhyaaon** [comment]
我又测试了一下，还是没有成功
由于以上操作会同时触发onSelect事件和onChange事件，其中onSelect事件是通过常规方式注册，而onChange事件是通过getFieldProps方式注册，而经过测试，onChange事件会在onSelect事件之后执行，且onSelect与onChange事件之间不会执行render()，故即使在onSelect事件中将当前选中的值从value中删除，onChange事件仍会将当前选中的值更新到value中

**Comment by benjycui** [comment]
用 `normalize` http://react-component.github.io/form/examples/normalize.html
