### ISSUE TITLE
treeSelect 如何自定义搜索？

### ISSUE THREAD

**Issue by stkevintan** [ant-design/ant-design#16517]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3kx7vx806q)

### Steps to reproduce
treeSelect目前搜索只能搜索value，我想搜索title，自己写了一个filter函数，已验证，我的filter函数是正确的

### What is expected?
可以搜索title

### What is actually happening?
不能搜索title

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 18.6.3 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
看下 `filterTreeNode`
