### ISSUE TITLE
RangePicker 选同一日期时，时间面板上的结束日期没有对应

### ISSUE THREAD

**Issue by nxt-hj** [ant-design/ant-design#16516]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/39750826/57511036-d4fa9480-733a-11e9-8a4e-be7dddbb94bd.png](https://user-images.githubusercontent.com/39750826/57511036-d4fa9480-733a-11e9-8a4e-be7dddbb94bd.png)

### Steps to reproduce
RangePicker 选同一日期时，时间面板上的日期没有对应

### What is expected?
时间面板上的日期能和输入值对应上

### What is actually happening?
时间面板上的日期没有对应

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | windows |
| Browser | Google Chorme |

**Comment by ZY2071** [comment]
https://github.com/ant-design/ant-design/pull/15427  一个月以前已经修复了，更新下antd版本即可
