### ISSUE TITLE
Tabs component: allow aligning left (so it's directly next to the last tab)

### ISSUE THREAD

**Issue by derblitz** [ant-design/ant-design#16511]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently the default add icon (  button) of the Tabs component is displayed on the outer right side of the component (meaning, it is right aligned).
There should be a way to make the add icon left aligned so it appears next to the last tab (like in Microsoft Excel).

### What does the proposed API look like?
alignAddIcon="left" | "right"

**Comment by zombieJ** [comment]
`editable-card` is full of design with its style. We may not add additional prop to handle this.
For your requirement, you can add an empty tab and listen `onTabClick` to handle that.

**Comment by derblitz** [comment]
Are you sure it's possible to hide the X on the empty tab you suggest? If so, can you please tell me how I can do this?

**Comment by zombieJ** [comment]
https://ant.design/components/tabs/#components-tabs-demo-editable-card

**Comment by derblitz** [comment]
Thank you!
