### ISSUE TITLE
List Component: Infinite & virtualized: This example on CodePen and CodeSandbox can not run

### ISSUE THREAD

**Issue by stone2014** [ant-design/ant-design#16514]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Example code can not run.

### What does the proposed API look like?
Example code can run correctly.

**Comment by GFwer** [comment]
Is https://codesandbox.io/s/jy004wxvy?
I find Dev like this:
![image](https://user-images.githubusercontent.com/14303098/57501403-f303cd00-7319-11e9-8f1a-6c0c9423b43b.png)
remove react-virtualized/* dependencies and add `react-virtualized` works
