### ISSUE TITLE
Steps组件中使用验证表单，怎么在验证通过后跳到下一步？

### ISSUE THREAD

**Issue by justable** [ant-design/ant-design#16519]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/Justable/pen/GaZjza](https://codepen.io/Justable/pen/GaZjza)

### Steps to reproduce
验证按钮在form组件中，控制步骤切换的点在外层组件中（不想通过redux管理Steps.current）。  

### What is expected?
在验证通过后执行外层组件的切换step逻辑。

### What is actually happening?
通过Form.create()()创建的高阶组件无法传递我的回调函数。

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.4 |
| Browser | Chrome 73 |

**Comment by zombieJ** [comment]
用 state 管理一下 Steps 进度。
