### ISSUE TITLE
List grid dosent support Multi Columns

### ISSUE THREAD

**Issue by itailv** [ant-design/ant-design#16528]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am trying to create a multi column grid inside a List component so that it stays within the ant scope and that I don't create new components for no reason.
What i am trying to achieve is a multi column grid **without fixed row size.**

#### My Code trying to achieve this:
```js
<List
    grid={{ column: 3 }}
    dataSource={data}
    renderItem={item => (
      <MyCard title={item.title} rows={item.rows}  />
    )}
/>
```

#### What I want to achieve:
![want](https://user-images.githubusercontent.com/40122948/57566511-ffe5f680-73d5-11e9-8d11-340a168526c8.jpg)

#### What ant gives me:
![reality](https://user-images.githubusercontent.com/40122948/57566521-13915d00-73d6-11e9-832f-12bc269897d1.jpg)

### What does the proposed API look like?
I dont know if this is possible to do, and if it isnt, i'm not sure about the correct way to propose it. but in pseudo, it could look something like this(?): 
```js
<List
    grid={{ column: 3, multiCol: true }}
    dataSource={data}
    renderItem={item => (
      <MyCard title={item.title} rows={item.rows}  />
    )}
/>
```

**Comment by afc163** [comment]
You can try https://github.com/didierfranc/react-waterfall

**Comment by itailv** [comment]
> You can try https://github.com/didierfranc/react-waterfall

@afc163 this is a react store library, how is it supposed to help?

**Comment by afc163** [comment]
Sorry, try https://github.com/eiriklv/react-masonry-component
