### ISSUE TITLE
问个Tree组件使用问题，如何设置点击节点时一直处于高亮的选中状态？

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#1652]
如下图，不设置multiple，checkable。
希望当再次点击'0-0-0-0' 时 还是处于选中状态

![image](https://cloud.githubusercontent.com/assets/2271825/15176028/c8bc77ae-179b-11e6-9d8c-a2a93d0f46bb.png)

**Comment by afc163** [comment]
这个交互不合适吧，那如何去掉选中状态呢。

**Comment by codering** [comment]
我的场景时这样的：一棵部门树，选中某部门，加载该部门下的员工信息。
因此就没有去掉选中的需求了。
 我当前的处理方案时在onSelect && selected=false时,重新把该节点的key放回selectedKeys 数组。。。。

**Comment by benjycui** [comment]
感觉这个场景应该用 http://ant.design/#/components/cascader + 列表的方式。

用 Tree 的话，交互很奇怪吧。。

**Comment by codering** [comment]
我的布局是左侧一棵树，顶级节点默认展开，右侧一个列表。 
我觉得用tree更直观些，cascader 不直观而且操作也会多一步，毕竟用户肯定会频繁切换部门。

**Comment by afc163** [comment]
建议修改使用方式，交互方面不合适进行修改。如果一定要这么做，建议用 tree 的受控模式自行控制选中状态。
