### ISSUE TITLE
自定义表单控件中表格的state的值被修改了

### ISSUE THREAD

**Issue by WangGuangCheng2018** [ant-design/ant-design#16521]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vmzzz8nyx0)

### Steps to reproduce
修改动态标签时候，可以在console中看到父组件的state被修改了,

### What is expected?
antd UI文档中的自定义表单控件并没有出现类似问题

### What is actually happening?
请问是什么原因导致的

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React |  3.17.0 |
| System | windows7 |
| Browser | chrome |

**Comment by afc163** [comment]
看不懂。

**Comment by WangGuangCheng2018** [comment]
如下图，我在修改表单之后，为什么组件state中的tags被修改了

![1557484883(1)](https://user-images.githubusercontent.com/35524901/57521714-96250880-7353-11e9-8b61-8e393974935e.jpg)
![1557484910(1)](https://user-images.githubusercontent.com/35524901/57521726-9fae7080-7353-11e9-8161-cf5b239f0364.jpg)

正常情况下不应该是不会改变吗

**Comment by zombieJ** [comment]
你改的是同一个数组，所以 tags 变了。
```jsx
const { tags } = this.state;
// ...
tags.push(inputValue);
```

**Comment by WangGuangCheng2018** [comment]
了然了，辛苦大佬！ 牢记血的教训...
