### ISSUE TITLE
select控件的初始值和placeholder的问题

### ISSUE THREAD

**Issue by windyyou** [ant-design/ant-design#1653]
## What you did
我在from中使用了一个select控件
      spec.type = '';

    const typeProps = getFieldProps('type', {
      rules: [
        { required: true, message: '请选资源类型' },
      ],
      onChange: this.props.handleObjectTypeChange,
      initialValue: spec.type,
    });

    <Select {...typeProps} placeholder="请选择资源类型" >
        <option value='1'>1</option>
        <option value='2'>2</option>
        <option value='2'>3</option>
    </Select>

## What you would like to happen

和input的效果一样
希望select控件的placeholder的值 在initialValue 为空的情况下生效

## What actually happened

同时设置了initialValue 和 placeholder

 initialValue 为空的情况下 placeholder不生效

## Online demo

代码如上

**Comment by afc163** [comment]
`initialValue` 不设置或设为 `undefined`，应该能解决。
