### ISSUE TITLE
Slider doesnt work in range mode

### ISSUE THREAD

**Issue by shlomyba** [ant-design/ant-design#16533]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?editors=0010](https://codepen.io/pen/?editors=0010)

### Steps to reproduce
Using the forked version in the link above doesn't reproduce it, but when I use it in local without any additional code it happens every time:
1. Install antd version 3.17.0
2. Use Slider component in range mode like that:
<Slider range defaultValue={[40, 80]} />

### What is expected?
See range slider like in the link above

### What is actually happening?
I got an error:
value.map is not a function
TypeError: value.map is not a function
    at ComponentEnhancer.Range (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:279050:24)
    at new ComponentEnhancer (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:280062:186)
    at constructClassInstance (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:314180:18)
    at updateClassComponent (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:317506:5)
    at beginWork (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:318463:16)
    at performUnitOfWork (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:322131:12)
    at workLoop (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:322171:24)
    at renderRoot (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:322254:7)
    at performWorkOnRoot (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:323161:7)
    at performWork (http://localhost:9009/vendors~main.31662cff02dc9c5f86e8.bundle.js:323073:7)

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | react |
| System | osx |
| Browser | chrome Version 74.0.3729.131 (Official Build) (64-bit) |

**Comment by ztplz** [comment]
Could you create a mini repo? So  hard to look into without reproduce.

**Comment by shlomyba** [comment]
If you try it locally it works for you?

**Comment by ztplz** [comment]
At least the demo work for me. https://codesandbox.io/s/znky6v3jrl  Let me test it locally.

**Comment by shlomyba** [comment]
Thanks! If it will work for you locally I will try again to reproduce it online

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/57580248-c8f90900-74d9-11e9-9da2-2af046316826.png)
I copied the code to the local, it still works for me. If you can't reproduce the problem online, it's best to build a mini repo.

**Comment by shlomyba** [comment]
Thanks to your test, I understood the issue happens only in storybook. I believe you will success to reproduce it like that.
Do you think it's in your hands or them?

**Comment by afc163** [comment]
We can't fix it if we don't know how to reproduce it.

**Comment by shlomyba** [comment]
It happens when you use the slider exactly the same but not in the App as you did but if you put the same slider code in stories file and view it using storybook UI

**Comment by ztplz** [comment]
@shlomyba  I tend to be a problem with the `storybook` because I can't reproduce it in `codepen`, `codesandbox` and app. If it works in other use cases but can't work on the `storybook`, it should be a problem with the `storybook`.

**Comment by shlomyba** [comment]
@ztplz Ok, thanks a lot!

**Comment by swapnilingle15** [comment]
@ant-design-bot I'm getting the same issue when I tried to map ant.design Range Slider component with redux-form. I also able to reproduce the issue https://codesandbox.io/s/modest-glitter-6ufyx?fontsize=14&hidenavigation=1&theme=dark

**Comment by yoyo837** [comment]
@swapnilingle15 It doesn't work. Pls feel free to open a new issue about this.

**Comment by imsushree** [comment]
Did anyone faced this issue with storybook, for me when I use this component in stories file, my slider is stuck
