### ISSUE TITLE
Ant calendar not support day view 

### ISSUE THREAD

**Issue by abgaryanharutyun** [ant-design/ant-design#16541]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use day view in ant calendar, but i think ant calendar not sported in the current version.

### What does the proposed API look like?
I think we can just pass as props view mode

**Comment by afc163** [comment]
What is day view?

**Comment by abgaryanharutyun** [comment]
@afc163 now ant calendar has only two options Month and Year view I think it will be good if we can add more options weekly/daily calendar

![image](https://user-images.githubusercontent.com/5097588/57600342-9ba86b80-756a-11e9-8088-c20f3995d7f7.png)

**Comment by afc163** [comment]
Duplicate of #8024
