### ISSUE TITLE
Transfer 虚拟化滚动

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design#16549]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
虚拟化

### What does the proposed API look like?
增加一个配置，如果为 true 则使用虚拟化的列表

**Comment by afc163** [comment]
默认已经是了。

**Comment by DiamondYuan** [comment]
> 默认已经是了，有个属性 `lazy={false}` 可以关闭虚拟化。

数据量大的时候还是非常卡。还以为没有使用。

**Comment by giscafer** [comment]
看新版 lazy 属性被去掉了呀。那只能用 react-virtualized 了

**Comment by giscafer** [comment]
> 看新版 lazy 属性被去掉了呀。那只能用 react-virtualized 了

pagination 支持
