### ISSUE TITLE
svg icon not align vertical center

### ISSUE THREAD

**Issue by SoYoung210** [ant-design/ant-design#16542]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/18658235/57590798-048ee400-7569-11e9-8cea-2048c5eb9a9a.png](https://user-images.githubusercontent.com/18658235/57590798-048ee400-7569-11e9-8cea-2048c5eb9a9a.png)

### Steps to reproduce
Sorry, my project must be private. So, I can't reproduce in sandbox. 
I guess this issue is produced because I use postcss with antd. 
> Just my guess.. Here's my Inspector.

### Inspector
https://user-images.githubusercontent.com/18658235/57590892-79621e00-7569-11e9-82a3-f6fadd5f4f8a.png  
https://user-images.githubusercontent.com/18658235/57590907-8ed74800-7569-11e9-88a6-569cc6f1cd79.png  
https://user-images.githubusercontent.com/18658235/57590909-94349280-7569-11e9-9b23-a449b109a982.png  

### What is expected?
svg icon align centered. 

### What is actually happening?
icon is on top.

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.8.1 |
| System | Mojave 10.14.2 |
| Browser | Chrome |

---
Here's my webpack config. and, postcss config.

### Webpack config
```js
module: {
		rules: [
			{
				test: /\.(ts|tsx|js)?$/,
				exclude: /node_modules/,
				use: [
					{
						loader: 'babel-loader',
					},
				],
			},
			{
				test: /\.(html)$/,
				use: {
					loader: 'html-loader',
				},
			},
			{
				test: /\.p?css$/,
				use: [
					'style-loader',
					{
						loader: 'css-loader',
						options: {
							importLoaders: 1,
							modules: true,
							localIdentName: '[path]_[local]',
							sourceMap: true,
						},
					},
					'postcss-loader',
				],
			},
			{
				test: /\.(gif|png|jpe?g)$/i,
				use: ['file-loader'],
			},
			{
				test: /\.less$/,
				use: [
					'style-loader',
					'css-loader',
					{
						loader: 'less-loader',
						options: {
							javascriptEnabled: true,
						},
					},
				],
			},
			{
				test: /\.svg$/,
				use: {
					loader: 'url-loader',
					options: {
						limit: 10000, // 10kb
					},
				},
			},
		],
	},
```

### postcss config
```js
module.exports = {
	plugins: [
		require('autoprefixer'),
		require('postcss-filter-gradient')({
			skipWarnings: true,
		}),
		require('postcss-utilities'),
		require('postcss-pseudo-content-insert'),
		require('postcss-svg'),
		require('postcss-import'),
		require('postcss-nested'),
		require('postcss-sorting')({
			order: [
				{
					type: 'at-rule',
					name: '@import',
				},
				'custom-properties',
				'dollar-variables',
				{
					type: 'at-rule',
					name: '@util',
					parameter: 'position',
				},
				{
					type: 'at-rule',
					name: '@util',
					parameter: 'clearfix',
				},
				'declarations',
				{
					type: 'at-rule',
					name: '@media',
				},
				'rules',
				{
					type: 'rule',
					selector: '^&',
				},
			],
			'properties-order': [
				'composes',
				'position',
				'z-index',
				'top',
				'right',
				'bottom',
				'left',
				'transform',
				'float',
				'clear',
				'display',
				'flex-direction',
				'flex-wrap',
				'justify-content',
				'align-content',
				'align-item',
				'order',
				'flex-grow',
				'flex-shrink',
				'flex-basis',
				'align-self',
				'visibility',
				'overflow',
				'clip',
				'box-sizing',
				'width',
				'min-width',
				'max-width',
				'height',
				'min-height',
				'max-height',
				'margin',
				'padding',
				'color',
				'border',
				'border-top',
				'border-collapse',
				'border-spacing',
				'border-radius',
				'background',
				'box-shadow',
				'opacity',
				'font',
				'font-family',
				'font-size',
				'font-weight',
				'font-style',
				'font-variant',
				'font-size-adjust',
				'font-stretch',
				'font-effect',
				'font-emphasize',
				'font-emphasize-position',
				'font-emphasize-style',
				'font-smooth',
				'line-height',
				'letter-spacing',
				'white-space',
				'word-break',
				'text-overflow',
				'transition',
				'animation',
				'cursor',
				'outline',
				'outline-width',
				'outline-style',
				'outline-color',
				'outline-offset',
			],
			'unspecified-properties-position': 'bottom',
		}),
	],
};

```

**Comment by afc163** [comment]
Please provide a minimal git repo to reproduce otherwise we can't help.

**Comment by Mystery-K** [comment]
hi,I reproduce this issue too.Did u fix it?

**Comment by yoyo837** [comment]
@Mystery-K Please provide an online reproduction demo link.

**Comment by Mystery-K** [comment]
@yoyo837 I just fixed it by adding '<!DOCTYPE html>' to the html...thx

**Comment by Ali-hd** [comment]
> @yoyo837 I just fixed it by adding '<!DOCTYPE html>' to the html...thx
I'm having the same problem.
isn't it added by default with react in public/index.html mine already has that but still need to remove vertical align because its not aligned

**Comment by brandonwisnicki** [comment]
> 
> 
> > @yoyo837 I just fixed it by adding '' to the html...thx
> 
> I'm having the same problem.
> isn't it added by default with react in public/index.html mine already has that but still need to remove vertical align because its not aligned

@Ali-hd Please see my comment in #13074 if you are using TailwindCSS. That seemed to be the culprit for me (as I already had <!doctype html> in my index.html. :)

**Comment by Noman12341** [comment]
My pagination previous and next arrow icons or not vertically centered so i remove the <!DOCTYPE html> from index.html and this issue fixed.
