### ISSUE TITLE
通过 ConfigProvider 配置的 prefixCls，在Icon组件不生效

### ISSUE THREAD

**Issue by soguagirl** [ant-design/ant-design#16547]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lpz27y0o4q)

### Steps to reproduce
查看源码，查看demo中 Icon 与 Button的 class

### What is expected?
Icon 也能遵循prefixCls的配置

### What is actually happening?
Icon无视prefixCls的配置

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.6 |
| System | MacOS |
| Browser | Chrome |

---
两个大版本共存的情况下，比如v2   v3，样式会有冲突，通过prefixCls来避免，但是Icon组件不支持。

**Comment by afc163** [comment]
You demo is empty, please check it.

**Comment by soguagirl** [comment]
https://codesandbox.io/s/lpz27y0o4q

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/15260#issuecomment-479351252

**Comment by soguagirl** [comment]
所以这是个bug吗？待修复？

**Comment by zombieJ** [comment]
有点不太一样， #15260 里是上下文， Icon 是因为没用 antd 的命名方式 `anticon`。干脆在 feature 里改了，统一起来？

**Comment by jsers** [comment]
这个还有进展吗？随着 antd 不断大版本升级，多版本并存的场景会越来越多

**Comment by jsers** [comment]
:worried: 看 v4 文档还是没有支持，望新版本能支持啊
