### ISSUE TITLE
封装Cascader以后不可使用resetFields()来清空值

### ISSUE THREAD

**Issue by Hansuku** [ant-design/ant-design#16548]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/j4486zj9jy)

### Steps to reproduce
- 选择一个选项
- 点击重置

### What is expected?
可以通过resetFields() 或者是 setFieldsValue()设置空来达到清空效果

### What is actually happening?
resetFields() 和 setFieldsValue() 都无效

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.9.0 |
| System | MacOS 10.14.4 |
| Browser | Chrome 74.0.3729.131（正式版本） （64 位） |

**Comment by afc163** [comment]
https://codesandbox.io/s/yvojpv679z

https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
