### ISSUE TITLE
Select 使用 getFieldDecorator 装饰后，选中项后 Select 值展示未更新

### ISSUE THREAD

**Issue by shuqinzhao** [ant-design/ant-design#16557]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/ppp6wzp2q7)

### Steps to reproduce
1. 未使用 getFieldDecorator 装饰过的 Select 选择后，展示值自动更新
2. 使用 getFieldDecorator 装饰过的 Select 选中项后，展示值未自动更新
3. 同一个 Form 中的 Select 选中项改变后，步骤2中的 Select 展示值改变了

### What is expected?
使用 getFieldDecorator 装饰过的 Select 选中项后，展示值自动更新

### What is actually happening?
使用 getFieldDecorator 装饰过的 Select 选中项后，展示值未自动更新

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | react@16.3.0 |
| System | node@8.4.0 |
| Browser | Chrome@74.0.3729.131 |

**Comment by afc163** [comment]
react@16.3.0 有一个 bug：https://github.com/facebook/react/pull/12528

升级到 react 最新版本即可。
