### ISSUE TITLE
FormItem中触发Form提交事件时拿到的数据错误

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#16563]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/0052o6k07n)

### Steps to reproduce
点击switch，查看控制台，打印出来的两个Switch的值不一致

### What is expected?
期望form拿到的Switch值保持一致

### What is actually happening?
两个Switch的值不一致

| Environment | Info |
|---|---|
| antd | 3.18.0 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
use `onValuesChange`: https://codesandbox.io/s/31k0j230j6
