### ISSUE TITLE
Press `Enter` key on DatePicker submits the form

### ISSUE THREAD

**Issue by dsumer** [ant-design/ant-design#16568]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xvkqqnqm1q?fontsize=14)

### Steps to reproduce
Click on a datepicker which is embedded as a field into a form and press Enter to select the date. The Form is being submitted automatically.

### What is expected?
As a user I expect a date to be selected if the datepicker modal is opened and to not automatically submit the form, because i maybe want to check again all the fields I've provided the form after selecting the date.

### What is actually happening?
Currently forms are being submitted automatically if the user chooses a date by pressing Enter, which results in unexpected behavior and in some cases very cumbersome outcome for the user because the form is being submitted.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | Any React Version |
| System | Any system |
| Browser | Any Browser |

---
Similar to the behavior of AutoComplete inputs here on this issue: https://github.com/ant-design/ant-design/issues/10861

**Comment by afc163** [comment]
It is native form behavior https://www.tjvantoll.com/2013/01/01/enter-should-submit-forms-stop-messing-with-that/

You can try drop `htmlType="submit"`.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9380#issuecomment-399120750

**Comment by dsumer** [comment]
If I drop the `htmlType="submit"` the button won't trigger submit events on the form anymore. And yes I agree, the default behavior of input fields should be, that a Enter keypress should trigger a submit event, but in the case of the DatePicker, the user wants the date to be picked on Enter, but not immediately submitting the form.

Same as you discussed it here on the AutoComplete case: https://github.com/ant-design/ant-design/issues/10861

**Comment by BuckAMayzing** [comment]
谢谢, @afc163!

**Comment by dsumer** [comment]
Thank you very much for solving! Is this already included in the 3.2.0 version release? Couldn't find it in the changelog here: https://github.com/ant-design/ant-design/releases/tag/3.20.0
