### ISSUE TITLE
建议在Table使用scroll属性, 且遇到空数据时, 默认隐藏水平滚动条

### ISSUE THREAD

**Issue by VoliBearCat** [ant-design/ant-design#16562]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一般使用Table的scroll属性时, 大多数场景只是因为&lt;td&gt;数据需要占据较大的空间, &lt;th&gt;可能不需要占太多的空间;
所以, 当空数据时, 多数场景介于Table和Empty中间的水平滚动条显得有些多余且不美观.
如果有其他因素的考虑, 也建议加入一个开关, 控制空数据时是否显示或隐藏水平滚动条

### What does the proposed API look like?
https://codesandbox.io/s/n5xr1w2n9l

**Comment by afc163** [comment]
感觉可行，唯一可能的问题是无数据到有数据的时候，列头会变化一下。

**Comment by VoliBearCat** [comment]
![image](https://user-images.githubusercontent.com/11676384/57612825-222f6e00-75a8-11e9-8470-2e725e22f388.png)

另外这里的overflow-x: scroll; 改成overflow-x: auto;是否会好一点?

**Comment by qwekelly** [comment]
scroll={ Total ? {x: '130%'} : undefined}  可以实现 (Total是传入table数据的长度)

**Comment by VoliBearCat** [comment]
> scroll={ Total ? {x: '130%'} : undefined} 可以实现 (Total是传入table数据的长度)

上方提供的demo已经是这么实现了, 只是建议这个可以由antd内部去实现

**Comment by AttackXiaoJinJin** [comment]
我觉得不行，
在多个column的title上自定义search，同时存在滚动条时，
我search一个条件，table没有数据符合，此时table显示no data，**但是水平滚动条要存在，因为我还要用鼠标拉滚动条移到目标column上，再点击search图标，来改变条件**

**Comment by afc163** [comment]
- 这个会造成 #7298 的问题，暂时不考虑去掉滚动条。
- https://github.com/react-component/table/pull/157 的解法又会造成 https://github.com/react-component/table/issues/163 的问题。

**Comment by dingchaoyan1983** [comment]
我这里有同样的问题，请问怎么解决？

**Comment by dingchaoyan1983** [comment]
现在主要是没有滚动条的情况下也会出现一个滚动条的placeholder，看起来很奇怪

**Comment by tangshuoup** [comment]
现在无数据的情况没有滚动条了啊

**Comment by chennng** [comment]
同时设置x 和 y ，水平虽然可以滚动，但是滚动条默认隐藏了。 这里感觉不太好。
