### ISSUE TITLE
能不能在 validateFields 方法中拿到 format 后的值

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#16574]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对于`DatePicker`类型的字段，因为格式是`Moment`，但是后端要求的是时间戳，现在做法是在`handleSubmit`中去`format`为时间戳。

### What does the proposed API look like?
希望能在`getFieldDecorator`中加一个`api`可以做提交时候的`format`，然后在`validateFields`中的回调的`values`就是`format`后的值，但是调用`getFieldsValue`可以依然是`Moment`格式的。

```jsx
<Form.Item label="date-picker">
     {getFieldDecorator("date-picker", {
         format: value => value.format("YYYY-MM-DD"),
         rules: [{ type: "object", required: true, message: "Please" }]
      })(<DatePicker />)}
</Form.Item>
```

**Comment by qq645381995** [comment]
https://codesandbox.io/embed/r0y9q5zwjp?fontsize=14

**Comment by zombieJ** [comment]
https://ant.design/components/form/?locale=en-US#getFieldDecorator(id,-options)-parameters
直接在 `getFieldDecorator` 处理就行了。

**Comment by qq645381995** [comment]
怎么用 我没看到能用的 api 啊

**Comment by zombieJ** [comment]
用 `getValueFromEvent` 把值直接转成 format 后的 string 来用哈~
form 不应该在提交和修改时使用不同的 value，format 这应该在业务逻辑里处理。觉得一个个处理麻烦的话直接写一个递归处理掉就行了~

**Comment by qq645381995** [comment]
> 用 `getValueFromEvent` 把值直接转成 format 后的 string 来用哈~
> form 不应该在提交和修改时使用不同的 value，format 这应该在业务逻辑里处理。觉得一个个处理麻烦的话直接写一个递归处理掉就行了~

是字段跟提交都不在一个 js 中，不想一个需求改了当前字段，还在再改提交代码的那个方法。

`getValueFromEvent ` 这个没法用，如果`Moment` 格式化成字符串，那就报错了。

**Comment by afc163** [comment]
`normalize`

**Comment by qq645381995** [comment]
> normalize

` normalize: value => value.format("YYYY-MM-DD"),`  这样了选择日期就选不中了。
![image](https://user-images.githubusercontent.com/7971419/57693673-5ffdc680-767c-11e9-96b3-d362640235ed.png)

**Comment by qq645381995** [comment]
😒 😒 😒

**Comment by qq645381995** [comment]
help me 🙏

**Comment by qq645381995** [comment]
![image](https://user-images.githubusercontent.com/7971419/57991236-1ed43f00-7ae0-11e9-9201-27d457a7e456.png)

**Comment by qq645381995** [comment]
@afc163 @zombieJ 
 https://codesandbox.io/embed/formatsubmitfields-lriu3?fontsize=14

这样行不行

**Comment by zombieJ** [comment]
实现了业务逻辑就行了哈，数据转换并不需要特别在 Form 里做成例子~

**Comment by qq645381995** [comment]
> 实现了业务逻辑就行了哈，数据转换并不需要特别在 Form 里做成例子~

动态增删你们还加了例子呢

**Comment by dh13899396662** [comment]
。。。。感情最后还是要在handleSubmit里手动处理

**Comment by dh13899396662** [comment]
> > 实现了业务逻辑就行了哈，数据转换并不需要特别在 Form 里做成例子~
> 
> 动态增删你们还加了例子呢

。。。。感情最后还是要在handleSubmit里手动处理

**Comment by crazyair** [comment]
> > > 实现了业务逻辑就行了哈，数据转换并不需要特别在 Form 里做成例子~
> > 
> > 
> > 动态增删你们还加了例子呢
> 
> 。。。。感情最后还是要在handleSubmit里手动处理

https://yforms.now.sh/examples#format-unformat-%E4%BD%BF%E7%94%A8

**Comment by one-pieces** [comment]
> 用 `getValueFromEvent` 把值直接转成 format 后的 string 来用哈~ form 不应该在提交和修改时使用不同的 value，format 这应该在业务逻辑里处理。觉得一个个处理麻烦的话直接写一个递归处理掉就行了~

为什么不能在 Form.Item 里加一个 transform 的 prop？如果 form 数据很复杂，比如有多层嵌套，然后又有数组，递归太麻烦了，直接在 Item 里转更方便
