### ISSUE TITLE
Awkward navigation of AutoComplete when `defaultActiveFirstOption=false` and no values are selected

### ISSUE THREAD

**Issue by ymzong** [ant-design/ant-design#16572]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1q4j8jzx7j)

### Steps to reproduce
Route 1):

* Enter "foo" into the `AutoComplete` bar
* Press enter without selecting the matching "foo" option in the dropdown

Route 2):

* Enter "apple" into the `AutoComplete` bar
* Press enter without selecting any options in the dropdown

### What is expected?
The outer form should be submitted, thereby alerting "submit" to the browser in the demo.

My rationale: Even though no options are selected in the dropdown, if the user enters some text and hits enter, s/he should expect `AutoComplete` to actually use the value and proceed to submit the form.

### What is actually happening?
Nothing happens since no option is selected.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | Windows |
| Browser | Chrome |

---
This glitch only occurs when `defaultActiveFirstOption={false}` because otherwise the first match always gets selected by default. Current workaround is for user to press `Esc` after entering the keyword and then press `Enter`, but I don't think that's ideal...

**Comment by afc163** [comment]
similar with #14544

**Comment by zombieJ** [comment]
Hmmm... seems close prevented by empty selection. It should adjust.

**Comment by ymzong** [comment]
Thanks for the quick turnaround @zombieJ @afc163!
