### ISSUE TITLE
Tree Select placeholder's style problem, when all node unchecked

### ISSUE THREAD

**Issue by LiuuY** [ant-design/ant-design#1657]
## What you did

Your official web site(http://ant.design/#/components/tree-select), 
'multiple: true' version, 
when I unchecked all tree nodes:
![](http://o70ctmglp.bkt.clouddn.com/treeselect.png)

In my project, i have same problem.

## Online demo

http://ant.design/#/components/tree-select

## Environment Information

- The version of antd: 1.0.0
- Your operating system and it's version(e.g. windows 10):
- Your browser and it's version(e.g. Chrome 50.0.2661.94 m):

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/15203267/74ee6a94-1834-11e6-9b62-8cd0246b21e8.png)

![image](https://cloud.githubusercontent.com/assets/2011119/15203284/9c3c61f0-1834-11e6-9fcf-16bcc2f8bfe2.png)

@afc163 select样式改了吧？
