### ISSUE TITLE
Cannot set custom attribute for testing in range picker

### ISSUE THREAD

**Issue by patrycjakretkiewicz-epm** [ant-design/ant-design#16571]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/NVRLaO?&editable=true&editors=001](https://codepen.io/anon/pen/NVRLaO?&editable=true&editors=001)

### Steps to reproduce
1. Right click on range picker
2. Inspect element

### What is expected?
Custom attribute (in this case 'data-testid') should be visible in DOM in range picker element. 

### What is actually happening?
Attribute is not available anywhere in the range picker tree.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 74 |

---
Checked it for antd buttons and inputs and the issue is not occurring.

**Comment by Kermit-Xuan** [comment]
It work correctly in `antd@4.x`. 

Please upgrade antd to 4.x

https://codesandbox.io/s/fanweixuanzeqi-ant-design-demo-forked-07r52
