### ISSUE TITLE
When the table can control the column width by dragging and dropping, if the rightmost column is fixed, there will be a blank area between the last column and the penultimate column.

### ISSUE THREAD

**Issue by SilenceOfNight** [ant-design/ant-design#16576]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://7jnr23vl40.codesandbox.io/#/resize-visible-table)

### Steps to reproduce
fixed the rightmost column

### What is expected?
There is no blank area between the last column and the penultimate column.

### What is actually happening?
There is a blank area between the last column and the penultimate column.
![image](https://user-images.githubusercontent.com/8108915/57667204-4a18e300-7635-11e9-804d-79e674f724e0.png)

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.5.2 |
| System | Window10 |
| Browser | Chrome |

**Comment by afc163** [comment]
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/507615/57680894-34211780-7661-11e9-9879-a80a8d4c93a9.png">
