### ISSUE TITLE
antd-react Slider组件 dots属性与step属性共同设置造成浏览器卡死

### ISSUE THREAD

**Issue by ahwgs** [ant-design/ant-design#16575]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4841vkwlkw)

### Steps to reproduce
1.打开https://ant.design/components/slider-cn/中的带标签的滑块demo 
2.将step={null} 删除后 设置dots={true} 
3.然后再设置step={null}属性  浏览器直接卡死

### What is expected?
不卡死或者得到其他解决

### What is actually happening?
浏览器卡死了

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.7.0 |
| System | win10 10.0.14393.2879 |
| Browser | Google Chrome 74.0.3729.131 |

---
业务上使用这个组件的时候先是设置了step={null} 然后看文档又设置了dots={true} 浏览器直接卡死了，然后使用文档中的codesandbox链接去做测试同样卡死了

**Comment by afc163** [comment]
Fixed in `rc-slider@8.6.10`, please try to reinstall `node_modules`.

**Comment by jddxf** [comment]
@afc163 https://github.com/react-component/slider/pull/812 introduced a regression.
