### ISSUE TITLE
cannot set Input value when use it  with AutoComplete

### ISSUE THREAD

**Issue by Zhaojing0987** [ant-design/ant-design#16589]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
use value and onChange to set Input(inside AutoComplete) value

### What is expected?
can set Input value

### What is actually happening?
cannot set Input value

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.6.3 |
| System | win10 |
| Browser | chrome74.0.3729.131 |

---
want to clear Input value in AutoComplete,  use the value property of AutoComplete will cause a problem, which is auto select option when input

**Comment by Zhaojing0987** [comment]
![image](https://user-images.githubusercontent.com/29828346/57742179-b7d71480-76f2-11e9-8ae1-0780d6c3daa6.png)
cannot set Input value and trigger onChange

**Comment by zombieJ** [comment]
Do not set `value` on Input. Set on AutoComplete instead.

**Comment by Zhaojing0987** [comment]
@zombieJ the value property of AutoComplete is to set selected option, if I trigger onChange to change autoComplete value, it will auto select a option, but I just want to change the input value.
for example, when I input "1", it will automatically fill in "value1", which means I cannot search anything start with "1".the moment I input a letter, it auto selected and changed Input value

**Comment by zombieJ** [comment]
AutoComplete is set to input value, not force require match the option: https://ant.design/components/auto-complete-cn/#components-auto-complete-demo-non-case-sensitive

**Comment by Zhaojing0987** [comment]
@zombieJ it will select option if you set value
![image](https://user-images.githubusercontent.com/29828346/57750043-2f1ca080-7713-11e9-92e2-f0046600a6d1.png)

**Comment by Zhaojing0987** [comment]
@zombieJ  updated reproduction link

**Comment by zombieJ** [comment]
Press ESC to close popup. Option in AutoComplete is optional. It do trigger onChange with user input.
