### ISSUE TITLE
forwardRef error

### ISSUE THREAD

**Issue by Vermouth1995** [ant-design/ant-design#16582]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ox435jm1vy)

### Steps to reproduce
I was trying to call child's method from parent and the child is a form component created by **Form.create**.But when I try to delivery props of **ref** from parent to child, it occurs an error.

### What is expected?
There is no error when I use forwardRef.

### What is actually happening?
Failed to compile.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | win 10 |
| Browser | Chrome 74.0.3729.131 |

**Comment by zombieJ** [comment]
`Form.create` wrap an component with Child. So if your `<ChildForm a={props.a} ref={childRef} />` get the ref is FormWrappedComponent not ref Child component.
Use `wrappedComponentRef` to get the origin component.
