### ISSUE TITLE
Antd 1.0, Spin 组件出现 React 警告

### ISSUE THREAD

**Issue by zhanjiaxia** [ant-design/ant-design#1658]
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

出错的代码片段：

```js
Spin.prototype.componentWillReceiveProps = function componentWillReceiveProps(nextProps) {
  var _this2 = this;

  var spinning = this.getSpinning(nextProps);
  if (this.debounceTimeout) {
    clearTimeout(this.debounceTimeout);
  }
  if (spinning) {
    this.debounceTimeout = setTimeout(function () {
      return _this2.setState({ spinning: spinning });   // 警告定位到此行
    }, 250);
  } else {
    this.setState({ spinning: spinning });
  }
};
```

使用的是` React 15 + Antd 1.0 `，目测是因为在 setTimeout 计时未完成时，Spin 组件已经被卸载了造成的

**Comment by afc163** [comment]
对，需要在 componentWillUnmount 的时候 clearTimeout 。 @RaoHai
