### ISSUE TITLE
Carousel lost slick dot active status after request

### ISSUE THREAD

**Issue by rdmclin2** [ant-design/ant-design#16583]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/mm99klq82y)

### Steps to reproduce
The following steps simulate a normal http request
1. initialize Carousel with empty slides
2. send a http request
3. **father componet trigger rerender , with empty slides**
3. get the request back, and render with data.

```js
import React, { PureComponent } from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Carousel } from "antd";

class Test extends PureComponent {
  state = {
    projects: []
  };

  componentDidMount() {
    // 一秒后置空
    setTimeout(() => {
      this.setState({
        projects: []
      });
    }, 1000);

    // 两秒后设置数组后，默认选中丢失
    setTimeout(() => {
      this.setState({
        projects: [1, 2, 3, 4, 5]
      });
    }, 2000);
  }

  render() {
    const { projects } = this.state;
    return (
      <div>
        <Carousel>
          {projects.map(project => (
            <div>
              <h3>{project}</h3>
            </div>
          ))}
        </Carousel>
      </div>
    );
  }
}

export default Test;

ReactDOM.render(<Test />, document.getElementById("container"));
```

### What is expected?
Carousel renders the first slide and the first slick dot set active 
![image](https://user-images.githubusercontent.com/4705237/57682692-f58d5c00-7664-11e9-8ff2-3e2468102d88.png)

### What is actually happening?
Carousel renders the last slide and  Lost slick dot active status

![image](https://user-images.githubusercontent.com/4705237/57681478-5c5d4600-7662-11e9-8de9-fd356c37611e.png)

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.9.0 |
| System | Mac |
| Browser | Chrome 74.0.3729.131 |

**Comment by svengiebel** [comment]
You could give the Carousel a key, to get it to properly rerender when the projects change:
```javascript
<Carousel key={projects.length.toString()}>...
```

(I dont know if this is the best Solution, i just tried it in you sandbox and it did work)

**Comment by zombieJ** [comment]
Seems it's `react-slick` bug. Should add some workaround for this.
