### ISSUE TITLE
rc-calendar 依赖版本修改，3.18.1版包中并未成功修改

### ISSUE THREAD

**Issue by ZY2071** [ant-design/ant-design#16588]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/releases/tag/3.18.1](https://github.com/ant-design/ant-design/releases/tag/3.18.1)

### Steps to reproduce
下载源码，打开查看package.json依赖部分

### What is expected?
"rc-calendar": "~9.13.3",

### What is actually happening?
"rc-calendar": "~9.12.1",

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.2.0 |
| System | windows |
| Browser | chrome |

---
紧急发个版？rc-calendar 组件显示部分的bug  https://github.com/ant-design/ant-design/issues/16516 被复现

**Comment by afc163** [comment]
可以来个 PR 发到 feature 上。

https://github.com/ant-design/ant-design/pull/16560 @susiwen8 做了一半跑路了

**Comment by susiwen8** [comment]
@afc163 哈哈哈哈，我不是跑路了.....是我觉得我不知道9.13版本新加了什么feature,我修的都是bug

**Comment by afc163** [comment]
https://github.com/react-component/calendar/pull/495

主要改动是这个，目测没有 antd 需要增加的新功能，那直接改 package.json 发 master 就好了。

**Comment by zombieJ** [comment]
嗯，下个 patch 会升级上来。 #16555

13 和 12 比多了一个 onBlur 关闭窗口的 fix，之前不放心就发了一个 minor 版本。

**Comment by susiwen8** [comment]
bot已经自动升级了

**Comment by Zhaojing0987** [comment]
@zombieJ 请问什么时候更新版本？

**Comment by qq645381995** [comment]
> 嗯，下个 patch 会升级上来。 #16555
> 
> 13 和 12 比多了一个 onBlur 关闭窗口的 fix，之前不放心就发了一个 minor 版本。

这个可能对 ie 有影响，点击切换月、年日期控件会关闭
