### ISSUE TITLE
Table 组件在onChange 事件中 通过sorter 手动对dataSource  进行排序 dataSource顺序和渲染的顺序不能对应

### ISSUE THREAD

**Issue by soeyi** [ant-design/ant-design#16598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mxy3jxk4j)

### Steps to reproduce
点击age的sort 序号会变乱。
但是打印的datasource 顺序正常

### What is expected?
序号根据datasource 的序号来变。

### What is actually happening?
序号根据datasource 的序号来变。

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | macos |
| Browser | chrome  74.0.3729.131 |

**Comment by afc163** [comment]
不太理解，你设置了按年龄排序，就会按年龄排序，不需要去设置 `dataSource`。如果希望完全控制，设置 sorter 为 `true` 后再自行 `setState` 即可。

**Comment by soeyi** [comment]
嗯。如果我设置 sorter 为 `true` 之后完全通过自己控制dataSource 就可以实现我想要的效果。
本来的意思是我 设置了 `sorter: (a, b) => a.age - b.age ` 
 这样再去自己完全控制dataSource 的值会被age的排序覆盖。
