### ISSUE TITLE
咨询下校验条件变更的问题

### ISSUE THREAD

**Issue by wangjinghui-cn** [ant-design/ant-design#1659]
代码如下, 一开始select控件选择一个, 然后点击提交, 然后变更select的值, 再点击提交, 这个时候的校验还是老的值, 该如何刷新?
http://alltest.oss-cn-hangzhou.aliyuncs.com/pic%2F20160225%2Findex.jsx

**Comment by wangjinghui-cn** [comment]
http://alltest.oss-cn-hangzhou.aliyuncs.com/pic%2F20160225%2Findex1.jsx
自己判断来确定是否加载该校验来解决了, 但是感觉这样不是太合适呀
{ this.state.isRequired ? <Input {...activeProps} placeholder="关联工单" /> : <Input placeholder="关联工单" /> }

**Comment by benjycui** [comment]
你的问题是动态修改校验规则不生效？

看了代码并没有缓存，可以提供个 Online Demo?

Please provide a re-producible demo: http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by wangjinghui-cn** [comment]
@benjycui 在线的demo貌似刷不出来 提示css js找不到
我有提供jsx文件  方便的话杰哥帮忙看下导入到在线demo

**Comment by afc163** [comment]
http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by wangjinghui-cn** [comment]
@benjycui @afc163 网站恢复了  demo已经提交
http://codepen.io/sywjh/pen/PNLxjZ?editors=0010

**Comment by benjycui** [comment]
加上 `force` 选项：

![image](https://cloud.githubusercontent.com/assets/3580607/15206288/9bc50ba2-1850-11e6-82c5-502f770d69ba.png)

然后在 Select `onChange` 时触发校验，不然 `Form` 无法感知改变了。

**Comment by wangjinghui-cn** [comment]
http://codepen.io/sywjh/pen/PNLxjZ?editors=0010   在handleChange内添加validateFields force true
效果有点诡异, 请帮忙看下

第一次选是  第二次选否
第一次选否  第二次选是
第一个控件不满足预期  第二个控件满足预期

第三次选是 第四次选否
第三次选否 第四次选是
两个控件均不满足预期 

PS 提交的时候是没问题的

**Comment by wangjinghui-cn** [comment]
已经解决 附上代码
`	handleChange: function(e) {
		this.setState({
			isRequired: e,
		}, function() {
  		this.props.form.validateFieldsAndScroll({force: true});
    });
	}`
