### ISSUE TITLE
Props.form and Effects Usage Problems

### ISSUE THREAD

**Issue by raybooysen** [ant-design/ant-design#16599]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
N/A
### Steps to reproduce
Create a functional react component that is wrapped in a Form.create()
In that functional component, use the useEffect hook to validate fields

```
useEffect(() => {
        props.form.validateFields({ force: true });
    }, [props.username, props.password, props.form]);
```

### What is expected?
Unsure, I'm looking for guidance here.  Because we're using props.form to validate the fields, the React guidance is to pass in props.form into the dependency array.

However, on each validate call, the props.form object is recreated, which causes an infinite loop of renders.

### What is actually happening?
We hit an infinite scheduled loop of re-rendering, re-validation because the hook determines that props.form has changed.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.17 |
| System | Linux Mint |
| Browser | Chrome 72 |

**Comment by ayayalar** [comment]
I am also running into this issue. I created codesandbox reproduces this issue. Please see comment in `useEffect`

https://codesandbox.io/s/small-star-wixy1

**Comment by PaulPCIO** [comment]
I have a similar issue just with updating the form fields if the initial props changes

https://codesandbox.io/s/antd-form-missing-in-effect-dependencies-z44s0

**Comment by yoyo837** [comment]
This may need to be try fixed in 4.0.

**Comment by PaulPCIO** [comment]
So one solution I found is to useRef, example:

```
  const savedForm = useRef()

  useEffect(() => {
    savedForm.current = form
  })

  useEffect(() => {
    savedForm.current.resetFields()
  }, [name])
```

**Comment by yoyo837** [comment]
It is best that the `form` does not include in the trigger condition of useEffect at the moment.

**Comment by ayayalar** [comment]
@PaulPCIO I will try your solution to see if it works for me. Thanks for sharing!
