### ISSUE TITLE
RangePicker时间选择结算时间月份错误

### ISSUE THREAD

**Issue by yylink0208** [ant-design/ant-design#16596]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
你们官网的例子 预设范围那一个月份显示为下一个月的

### What is expected?
月份为选择的月份

### What is actually happening?
月份显示为选择日期的下一个月

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.6.3 |
| System | win10 |
| Browser | chrome 74.0.3729.131 |

**Comment by afc163** [comment]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/507615/57760706-b4617e80-772e-11e9-858b-d71bd20ca976.png">

没发现问题。
