### ISSUE TITLE
Show table scroll by default

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#16608]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w23o7z5mzk)

### Steps to reproduce
Open the link & do a horizontal scroll to Column 1 to Column 8.
When the user hovers and does a scroll then the horizontal scroll is visible.

### What is expected?
Is there any property which will show the scroll by default

### What is actually happening?
Scrolls are hidden until the user doesn't scroll.  This creates confusion to the end-user and they are not able to figure out whether the columns/data are really available.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.9 |
| System | MacOSX |
| Browser | Chrome |

**Comment by afc163** [comment]
http://osxdaily.com/2011/08/03/show-scroll-bars-mac-os-x-lion/
