### ISSUE TITLE
Filled and twoTone icons are missing.

### ISSUE THREAD

**Issue by ibesty** [ant-design/ant-design#16601]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/icon/#components-icon-demo-iconfont](https://ant.design/components/icon/#components-icon-demo-iconfont)

### Steps to reproduce
Select Filled or Two Tone, the Application Icons are missing.

### What is expected?
Filled and Two Tone icons are the same as outlined icons.

### What is actually happening?
They are missing and blank.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | macOS 10.14.4 |
| Browser | Chrome 74.0.3729.131 |

**Comment by zombieJ** [comment]
Hmm...Some icons do not have Fill & TwoTone. Should removed from doc.
