### ISSUE TITLE
webpack如何全局引用antd？

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#1660]
比如全局引用react，把react的依赖提取，在webpack加入以下句子
externals: [
      {'react': 'React'},
      {'react-dom': 'ReactDOM'}
  ],
antd中如何写？

**Comment by afc163** [comment]
一样的，全局变量是 `'antd': 'antd'`。

**Comment by yeyuguo** [comment]
我想问一下，antd 已经从外部链接引入了，为什么打包出来的文件还是非常的大呢，一个.js 文件有4M 左右；里面引入的就是 antd 的组件

**Comment by benjycui** [comment]
@yeyuguo 因为你没有把 antd external，webpack 配置问题，建议自行学习 webpack

**Comment by zjdschnappi** [comment]
@benjycui  你好，全局引入最新版的ant3.0的时候报这个错
![image](https://user-images.githubusercontent.com/15072751/34764838-b9066418-f62a-11e7-8717-24eb6e365ddd.png)
这是我webpack代码 
![image](https://user-images.githubusercontent.com/15072751/34764862-cb52f65e-f62a-11e7-981a-f419ba8c54ac.png)
页面script标签已经引了ant.js了，版本2.x的时候还正常的，我换新版本就这样了。求教

**Comment by yesmeck** [comment]
@zjdschnappi 3.0 依赖 moment.

**Comment by afc163** [comment]
看下 changelog

**Comment by zjdschnappi** [comment]
@afc163 @yesmeck 好的。页面再引了moment.js就好了，谢谢大佬们。只不过我全局要引的js又多了一个。。。

**Comment by Alex1990** [comment]
使用`<script>`引入 moment 需要在引入 antd 之前，但是根据报的错误不一定容易发现

**Comment by fancymo** [comment]
> @benjycui 你好，全局引入最新版的ant3.0的时候报这个错
> ![image](https://user-images.githubusercontent.com/15072751/34764838-b9066418-f62a-11e7-8717-24eb6e365ddd.png)
> 这是我webpack代码
> ![image](https://user-images.githubusercontent.com/15072751/34764862-cb52f65e-f62a-11e7-981a-f419ba8c54ac.png)
> 页面script标签已经引了ant.js了，版本2.x的时候还正常的，我换新版本就这样了。求教

你好、请问是如何通过script标签引入antd的？

**Comment by bigbigEden** [comment]
> @afc163 @yesmeck 好的。页面再引了moment.js就好了，谢谢大佬们。只不过我全局要引的js又多了一个。。。

请问 如何在jsx里再使用antd组件呢。。 我这边总是出现antd is undefinded

**Comment by TTwilight** [comment]
@benjycui 我是直接引用的

**Comment by xuya227939** [comment]
@TTwilight   我直接引用报错了，请问你是怎么解决的？
index.html
```
<link href="https://cdn.bootcss.com/antd/3.20.7/antd.css" rel="stylesheet">
<script src="https://cdn.bootcss.com/antd/3.20.7/antd.js"></script>
```
webpack
```
externals: {
        antd: 'antd'
}
```
报错信息
```
external "antd"?08aa:1 Uncaught ReferenceError: antd is not defined
    at eval (external "antd"?08aa:1)
    at Object.antd (app.js:2137)
    at __webpack_require__ (app.js:64)
    at eval (index.jsx:8)
    at Module../src/index.jsx (app.js:2006)
    at __webpack_require__ (app.js:64)
    at Object.1 (app.js:2125)
    at __webpack_require__ (app.js:64)
    at app.js:198
    at app.js:201
```
这是我的配置

**Comment by marspal** [comment]
> @TTwilight 我直接引用报错了，请问你是怎么解决的？
> index.html
> 
> ```
> <link href="https://cdn.bootcss.com/antd/3.20.7/antd.css" rel="stylesheet">
> <script src="https://cdn.bootcss.com/antd/3.20.7/antd.js"></script>
> ```
> 
> webpack
> 
> ```
> externals: {
>         antd: 'antd'
> }
> ```
> 
> 报错信息
> 
> ```
> external "antd"?08aa:1 Uncaught ReferenceError: antd is not defined
>     at eval (external "antd"?08aa:1)
>     at Object.antd (app.js:2137)
>     at __webpack_require__ (app.js:64)
>     at eval (index.jsx:8)
>     at Module../src/index.jsx (app.js:2006)
>     at __webpack_require__ (app.js:64)
>     at Object.1 (app.js:2125)
>     at __webpack_require__ (app.js:64)
>     at app.js:198
>     at app.js:201
> ```
> 
> 这是我的配置

分开搞一下吧, production 用cdn, dev 就用node_modules的吧

**Comment by freewind** [comment]
> external "antd"?08aa:1 Uncaught ReferenceError: antd is not defined

要确保在引入antd.js之前引入moment.js，否则antd.js运行会报错，所以后面找不到
