### ISSUE TITLE
Precision decimals losing trailing zero 

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#16609]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5wzpnn7q1x)

### Steps to reproduce
Press   or - buttons multiple time for inputs for the second input.

### What is expected?
with precision={2} and step={0.1} it is expected for number to have trailing zero when changing number using buttons

### What is actually happening?
when InputNumber with precision prop is in a form or controlled, pressing   or - buttons makes it lose trailing zeros.
If value is normalized, then it loses trailing zeros only when input is not in focus and   or - is pressed first time

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.9.0 |
| System | windows |
| Browser | any |

**Comment by zombieJ** [comment]
Seems related with controlled value: https://codesandbox.io/s/confident-fermi-orfme

**Comment by afc163** [comment]
The reason of this issue is in controlled mode, the `value` of `onChange(value)` should be a number when pressing <kbd>up</kbd> or <kbd>down</kbd>. Otherwise it will break like #15575, I afraid we can't fix this problem cause it is against #15575 too.
