### ISSUE TITLE
after v.3.16.6 value in checkbox group is missing when use with form

### ISSUE THREAD

**Issue by wattanapongjack** [ant-design/ant-design#16602]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/1ry6ko6kvj)

### Steps to reproduce
1. check some box  ex.student1 [parker-student]
2. click teacher tap in left side and check some box ex.teacher1 [golf-teacher]
3. go back to student tab. value in checkbox is disappear 

### What is expected?
value in checkbox not disappear

### What is actually happening?
checkbox value is disappear after antd version 3.16.6

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | os |
| Browser | chrome |

**Comment by afc163** [comment]
something related to https://github.com/ant-design/ant-design/pull/16392

**Comment by zombieJ** [comment]
Checkbox.Group remove value which not exist in the group since `3.17.0`. If you want to keep prev values, just use different field name to hold that: https://codesandbox.io/s/fervent-water-3cbg9
