### ISSUE TITLE
table 所有列都固定宽度，内容过长时会跟表头不对齐

### ISSUE THREAD

**Issue by Hansuku** [ant-design/ant-design#16606]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/RmKBeb?editors=0010](https://codepen.io/anon/pen/RmKBeb?editors=0010)

### Steps to reproduce
这个是官方的实例，在73 行修改内容，后面多加几个 1 就崩了

### What is expected?
正常对齐

### What is actually happening?
与表头偏移

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.9.0 |
| System | MacOS 10.14.4 |
| Browser | Chrome 74.0.3729.131（正式版本） （64 位） |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241
