### ISSUE TITLE
Input.Search blur 事件失效

### ISSUE THREAD

**Issue by 434451580** [ant-design/ant-design#16603]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当用户在编辑某个表单但未保存时，触发inputSearch的onSearch(误触)会使得当前页的focus聚焦在inputSearch输入框上，无法使其他input再此时获得focus，也就无法帮用户快速定义到未保存的修改位置，用户体验较差

### What does the proposed API look like?
希望给inputSearch提供一个触发onSearch使inputSearch的input可以不自动获取焦点的api。谢谢！

**Comment by 434451580** [comment]
https://codesandbox.io/embed/52n0roynn?fontsize=14










------------------ 原始邮件 ------------------
发件人: "Ant Design GitHub Bot"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 下午5:38
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "冷火ou"<434451580@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ant-design/ant-design] Input.Search blur 事件失效 (#16603)




Hello @434451580. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
你好 @434451580, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by afc163** [comment]
没有看明白，重现步骤和预期表现是什么？

**Comment by 434451580** [comment]
触发onSearch时候，inputSearch会自动获取焦点，如果我在触发onSearch的时候想给其他input获取focus的，这时候会被inputSearch的自动获取焦点给覆盖掉，=》 如果我想在用户点击搜索的时候，不让他搜索，并且重新给他聚焦到之前的某个输入框就不行了，在我项目代码中我尝试用ref把inputSearch存起来，然后在特定的时间是他失去焦点，然后让我想获取焦点的input重新获得焦点，但是行不通。






------------------ 原始邮件 ------------------
发件人: "偏右"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 晚上8:07
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "冷火ou"<434451580@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ant-design/ant-design] Input.Search blur 事件失效 (#16603)




没有看明白，重现步骤和预期表现是什么？

**Comment by afc163** [comment]
1. 重现步骤是什么？
2. 预期表现是什么？
3. 实际表现是什么？

你写清楚这三个就行了，其他写一堆我也理解不了。

**Comment by 434451580** [comment]
重现步骤：在input里随便输入点内容是isChange为true标记为已经更改，然后触发InputSearch的onSearch；在触发onSearch的时候判断isChange如果为真，使input重新获得焦点
预期表现：使input重新获得焦点；

实际表现：onSearch事件触发InputSearch自动获取焦点；覆盖掉了在onSearch时收动给input获取的焦点






------------------ 原始邮件 ------------------
发件人: "偏右"<notifications@github.com>;
发送时间: 2019年5月15日(星期三) 晚上9:48
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "冷火ou"<434451580@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ant-design/ant-design] Input.Search blur 事件失效 (#16603)



 
重现步骤是什么？
 
预期表现是什么？
 
实际表现是什么？
  
你写清楚这三个就行了，其他写一堆我也理解不了。

**Comment by afc163** [comment]
点击搜索按钮会触发 focus 搜索框的行为，你这里加个 setTimeout 延迟一下就行：https://codesandbox.io/s/antd-reproduction-template-7vls6
