### ISSUE TITLE
根据文档使用babel-plugin-import按需加载antd，但是npm run build 之后的包依然有600kb

### ISSUE THREAD

**Issue by DemoHu** [ant-design/ant-design#16600]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

[https://github.com/DemoHu/create-react-app-demo](https://github.com/DemoHu/create-react-app-demo)

### Steps to reproduce
正确配置babel-plugin-import了之后，只引入了 import { Layout } from 'antd'，之后打包npm run build  ，查看打包之后的文件，主js文件依然有600度kb,这和未使用babel-plugin-import打包的大小几乎一样

可以clone 此项目后执行npm run build ，build后的文件有600多kb，但是我只引用了一个Layout组件而已

### What is expected?
按需加载

### What is actually happening?
打包后依然很大

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | Windows10 |
| Browser | chrome |

---
安装官网说明，完全正确的使用了babel-plugin-import，但是npm run build 之后好像包并没有减小

**Comment by As3ass1n** [comment]
用webpack-bundle-analyzer查看下，目测应该是icon全部打包的问题 #12011

**Comment by afc163** [comment]
使用了 `babel-plugin-import`：

```
File sizes after gzip:

  211.19 KB  build/static/js/2.8732238f.chunk.js
  4.38 KB    build/static/css/2.16190aad.chunk.css
  1.11 KB    build/static/js/runtime~main.80b062cb.js
  783 B      build/static/js/main.cc0ebb8b.chunk.js
  616 B      build/static/css/main.e5b1719f.chunk.css
  313 B      build/static/js/3.106ff31f.chunk.js
  313 B      build/static/js/5.935e454b.chunk.js
  310 B      build/static/js/4.e50d7138.chunk.js
```

去掉 `babel-plugin-import` 后：

```
File sizes after gzip:

  211.93 KB (+757 B)    build/static/js/2.d50863af.chunk.js
  53.84 KB (+49.46 KB)  build/static/css/2.cef57b64.chunk.css
  1.11 KB               build/static/js/runtime~main.14685ec1.js
  783 B                 build/static/js/main.d6aa08d1.chunk.js
  616 B                 build/static/css/main.e5b1719f.chunk.css
  313 B                 build/static/js/3.de10ddee.chunk.js
  313 B                 build/static/js/5.0384b93b.chunk.js
  310 B                 build/static/js/4.04593d71.chunk.js
```

可以看到 js 体积相差无几，css 体积增加了 50 KB。

原因是：

1. `antd` 本身支持 tree-shaking，https://github.com/ant-design/ant-design/blob/88364399e336cd5fdc494e7a18fbf7e6e0965d87/package.json#L32 效果和使用了 `babel-plugin-import` 差不多。
2. `antd` 的样式依然可以通过 `babel-plugin-import` 进行按需加载。

---

结论，楼主的例子已经是按需加载后的效果了。如果不需要样式部分的按需加载，去掉 `babel-plugin-import` 也问题不大。

**Comment by DemoHu** [comment]
@afc163   那在未开启gzip的情况下，达到了600kb，我试过在不安装antd的情况下，打包后只有200kb左右，那antd将近 400kb 是否过大？

**Comment by afc163** [comment]
antd 目前确实有这么大：https://github.com/ant-design/ant-design/issues/12011
