### ISSUE TITLE
Clicking a Slider inside a Popover closes Popover automatically on mobile

### ISSUE THREAD

**Issue by inconduit** [ant-design/ant-design#16610]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mobile-slider-popup-issue-4xlbw)

### Steps to reproduce
- open Chrome
- open DevTools, then select Toggle Device Toolbar (top left) to simulate mobile browser
- click 'Show Slider' button to open Popover
- click Slider handle

### What is expected?
The Popover should stay open.

### What is actually happening?
The Popover automatically closes.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8 |
| System | osx |
| Browser | chrome |

---
The issue does not occur on desktop chrome. I understand you do not support mobile, but if you can suggest an easy fix, I would be grateful.

This only happens for Slider, does not happen if Popover content is a Button.

**Comment by zombieJ** [comment]
Your demo not provides `Show Slider` Button...

**Comment by inconduit** [comment]
i updated the codesandbox link in my original comment, and here it is again:

https://codesandbox.io/s/mobile-slider-popup-issue-4xlbw

**Comment by mgrundkoetter** [comment]
I have forked the sandbox. The problem occurs when the marks are clicked: https://codesandbox.io/s/mobile-slider-popup-issue-t51f5

**Comment by AlexVKO** [comment]
do you guys have any workaround for that?

**Comment by inconduit** [comment]
@AlexVKO this is the workaround i came up with, it manually manages popover visibility using mouse events

```
import React, { Component } from 'react';
import { Popover } from 'antd';
import { object } from 'prop-types';

/*
  A wrapper for Popover to fix bug where Popover
  closes when trigger='click' on mobile and a
  antd Slider is pressed inside of the Popover
*/
class WorkaroundPopover extends Component {
  state = {
    isPopoverVisible: false,
  }

  triggerNode = null;
  contentNode = null;

  componentDidMount() {
    document.addEventListener('click', this.handleClick);
  };

  componentWillUnmount() {
    document.removeEventListener('click', this.handleClick)
  }

  handleClick = (e) => {
    if (this.triggerNode && this.triggerNode.contains(e.target)) {
      this.setState({ isPopoverVisible: !this.state.isPopoverVisible });
    } else {
      const isPopoverVisible =
        this.contentNode && this.contentNode.parentNode.contains(e.target);

      this.setState({ isPopoverVisible });
    }
  }

  render() {
    const { children, content, ...popoverProps } = this.props;
    const { isPopoverVisible } = this.state;

    return (
      <Popover
        {...popoverProps}
        content={
          <div ref={(node) => this.contentNode = node}>
            { content }
          </div>
        }
        trigger='externalMenu'
        visible={ isPopoverVisible }
      >
        <div ref={(node) => this.triggerNode = node}>
          { children }
        </div>
      </Popover>
    );
  }
}

WorkaroundPopover.propTypes = {
  content: object,
}

export default WorkaroundPopover;
```

**Comment by AlexVKO** [comment]
Thanks @inconduit

**Comment by thmohd** [comment]
I confirm I have the same issue on mobile

**Comment by thmohd** [comment]
@inconduit solution worked well for me, here is the Hook version of it with close button if anybody use Hooks:
`import React, { Component, useState, useEffect } from "react";
import { Popover } from "antd";

/*
  A wrapper for Popover to fix bug where Popover
  closes when trigger='click' on mobile and a
  antd Slider is pressed inside of the Popover
*/
const SliderPopoverFix = (props) => {
    const [isPopoverVisible, setIsPopoverVisible] = useState(false);
    const { children, content, ...popoverProps } = props;

    useEffect(() => {
        console.log('mounted')
        document.addEventListener("click", handleClick);
        return () => {
            console.log('UNmounted')
            document.removeEventListener("click", handleClick);
        }
    }, [])

    const handleClick = e => {
        if (document.triggerNode && document.triggerNode.contains(e.target) && e.target.className !== 'close') {
            setIsPopoverVisible(!isPopoverVisible);
        } else if(e.target.className === 'close'){
            setIsPopoverVisible(false);
        } else {
            const isPopoverVisible =
                document.contentNode && document.contentNode.parentNode.contains(e.target);
            setIsPopoverVisible(isPopoverVisible);
        }
    };

    return (
            <Popover
                {...popoverProps}
                content={<div ref={node => document.contentNode = node }>{
                    <div>
                        {content}
                        <a className="close">اغلاق</a>
                    </div>
                    }</div>}
                trigger="click"
                visible={isPopoverVisible}
            >
                <div ref={node => document.triggerNode = node}>{children}</div>
        </Popover>
    )
}

export default SliderPopoverFix;
`

**Comment by hieusmiths** [comment]
Any simple solution for it ?
Thank you

**Comment by afc163** [comment]
antd 5.x is no long have this problem, feel free to recreate a new issue if not.
