### ISSUE TITLE
Antd React Upload component adding extra content into files

### ISSUE THREAD

**Issue by spider58** [ant-design/ant-design#16617]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ljgoh)

### Steps to reproduce
-

### What is expected?
-

### What is actually happening?
I using Upload component but this component adding extra headers into uploaded file. I dont want to this.

For example:

     a.txt -->  

            test, test, test

after upload a.txt

        ---------WebKitFormBoundary1nIxckRK0S7nxb88
        Content-Disposition: form-data; name="file"; filename ="a.txt"
        Content-Type: text/plain

            test, test, test

 ---------WebKitFormBoundary1nIxckRK0S7nxb88

        

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | - |
| Browser | Chrome latest |

**Comment by afc163** [comment]
It is not bug, that how a upload works in web.

**Comment by spider58** [comment]
@afc163 Thanks for answer but i uploading some different file types, .dat, .xls, .cvs etc... This is corrupting files?

**Comment by spider58** [comment]
For example i tried to upload an XLS file but uploaded XLS file doesn't opened by office reason "corrupted"

**Comment by ZoeyanZh** [comment]
I have the same problem with .xlsx files. The original file is ok. By using <Upload> component to upload the  .xlsx file to the server, the file is corrupted. Hope to solve this problem.
![image](https://user-images.githubusercontent.com/39585790/60001444-0fc14d80-9699-11e9-8076-a18ce7d925ee.png)

**Comment by hon3g** [comment]
> It is not bug, that how a upload works in web.
> 
> https://stackoverflow.com/questions/4526273/what-does-enctype-multipart-form-data-mean
> 
> https://stackoverflow.com/questions/41188903/what-does-webkitformboundary-mean?rq=1

How can I remove WebKitFormBoundary part? With the extra part, images uploaded to s3 can't be displayed using img tag. It only works when the body is image file not form data with the WebKitFormBoundary part.

This does NOT work.
<img width="671" alt="Screen Shot 2021-12-09 at 9 39 25 PM" src="https://user-images.githubusercontent.com/54009957/145508121-42239d77-0b82-4476-914b-19345dc98c45.png">

This works

<img width="671" alt="Screen Shot 2021-12-09 at 9 39 49 PM" src="https://user-images.githubusercontent.com/54009957/145508201-3ac066ee-c161-4086-80ac-e2af66d2c3ad.png">
