### ISSUE TITLE
Modal 是否支持拖拽及最大化功能呢？

### ISSUE THREAD

**Issue by YvonneZh128** [ant-design/ant-design#16613]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.layui.com/demo/layer.html](https://www.layui.com/demo/layer.html)

### Steps to reproduce
Modal组件API中没有指出可以实现可以拖拽和实现弹窗最大化的功能

### What is expected?
期望Modal组件可以实现类似layui中弹出层的拖拽或者最大化的功能 

### What is actually happening?
Modal 拥有类似layui弹出层的拖拽或最大化的功能的API

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.6 |
| System | macOS/windows10 |
| Browser | chrome/IE10以上 |

---
因为现在在接入antd组件库，需求中需要Modal实现拖拽和窗口最大化的功能，当前弹窗可以实现在引入该组件的页面范围内可拖拽及最大化实现，

**Comment by zombieJ** [comment]
拖拽：https://github.com/ant-design/ant-design/issues/3012#issuecomment-386537987

最大化：设计中 Modal 用于非打断工作流，最大化和我们的设计目的不符，应该不会支持。

**Comment by YvonneZh128** [comment]
感谢，已经实现了最大化，参考实现了拖拽，感谢～

**Comment by effapp** [comment]
> 感谢，已经实现了最大化，参考实现了拖拽，感谢～

能把实现最大化的代码共享一下吗，我参考参考。

**Comment by YvonneZh128** [comment]
> > 感谢，已经实现了最大化，参考实现了拖拽，感谢～
> 
> 能把实现最大化的代码共享一下吗，我参考参考。

啊，其实就是强制做了一下弹窗的宽高……
