### ISSUE TITLE
Add Validation to Typography

### ISSUE THREAD

**Issue by DavidSichau** [ant-design/ant-design#16628]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
With Typography Editable one can design read friendly Pages. Where editing only happens infrequently. 

However there is missing a nice way to validate the input on changes. For example when an email field is changed to an invalid field.

It would be nice if one could provide some way to validate the input field like on Forms.

### What does the proposed API look like?
```
<Form.Item label="E-mail">
          {getFieldDecorator('email', {
            rules: [
              {
                type: 'email',
                message: 'The input is not valid E-mail!',
              },
              {
                required: true,
                message: 'Please input your E-mail!',
              },
            ],
          })(<Typography.Text editable />)}
</Form.Item>
```

**Comment by zombieJ** [comment]
Typography is a light way component with edit ability. Using Typography with Form is miss use by our design language. No recommend to do this.

But you can still wrap Typography as form-able [customize component](https://ant.design/components/form-cn/#components-form-demo-customized-form-controls).
