### ISSUE TITLE
DatePicker选择日期后能不能自动切换到时间面板？

### ISSUE THREAD

**Issue by Orangec765** [ant-design/ant-design#16627]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
主要是客户那边说选择完日期后要点选择时间太繁琐了，想改成选择日期后自动切换到时间面板

### What does the proposed API look like?
提供相应的函数

**Comment by afc163** [comment]
还不支持，合并到 #6539
