### ISSUE TITLE
后期是否会提供富文本编辑器

### ISSUE THREAD

**Issue by hjqhezgh** [ant-design/ant-design#1662]
后期是否会提供富文本编辑器

**Comment by benjycui** [comment]
Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/1083
