### ISSUE TITLE
当我在使用select组件的multiple mode的时候，可以支持自定义value的格式么

### ISSUE THREAD

**Issue by JokerOng** [ant-design/ant-design#16620]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前在使用select组件的multiple mode时，返回的值是List，但实际上我们在与服务端交互时，会需要不同格式的值，例如是一串以某个符号连接的字符串。

### What does the proposed API look like?
增加一个字段，值为某个连接的符号，或者增加一个钩子函数，参数为原来的list，我可以拿到这个参数处理后，return我处理后的结果，绑定到value。

**Comment by afc163** [comment]
建议自行封装一个上层组件处理输入输出格式。
