### ISSUE TITLE
ant design table 报错：Component definition is missing display name

### ISSUE THREAD

**Issue by SUH11** [ant-design/ant-design#16633]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://blog.csdn.net/qq_33603809/article/details/90268648](https://blog.csdn.net/qq_33603809/article/details/90268648)

### Steps to reproduce
1.写一个类A 
2.写一个类B，该类继承类A
3.在类B中使用table
4.table里的datasource，格式大概为：
fields: [
				{
                    title: '客户类型',
                    dataIndex: 'customer_type',
                    key: 'show_customer_type'
                },
                {
                    title: '申请人/申请日期',
                    dataIndex: 'last_save_name',
                    key: 'last_save_name',
                    render: (text, record) => (
                        <Fragment>
                            <div>{record.last_save_name || '无'}</div>
                            <div>{record.last_save_time || '无'}</div>
                        </Fragment>
                    )
                }
			]
这里的render有text和record
5.使用eslint
6.报错：Component definition is missing display name

### What is expected?
不报错

### What is actually happening?
报错了

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16 |
| System | MacOS |
| Browser | 最新版，随时更新 |

---
使用table，更改render并用text和record

**Comment by zombieJ** [comment]
你的 render 写法被 eslint 当成 SFC 了。这个不是 antd 的问题。

**Comment by sccassiel** [comment]
在函数组件中table的render
![image](https://user-images.githubusercontent.com/6365459/86266031-33499d00-bbf7-11ea-885c-2398c9e6980a.png)
这样写的话，eslint报这个错"Declare only one React component per file  react/no-multi-comp" 有大佬遇到过吗？
