### ISSUE TITLE
Select Component does not remove invalid tags when options changes

### ISSUE THREAD

**Issue by ayqy** [ant-design/ant-design#16634]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-8mih6)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/12402989/57850891-afc1c680-7811-11e9-8025-e5be8b16b8c1.png)

### What is expected?
Is there any way to sync Select.value with changed options, other than maintaining value prop manually ?

### What is actually happening?
![image](https://user-images.githubusercontent.com/12402989/57850891-afc1c680-7811-11e9-8025-e5be8b16b8c1.png)

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | "react": "16.8.6", |
| System | Mac Latest |
| Browser | Chrome Latest |

**Comment by zombieJ** [comment]
It's by design: https://github.com/ant-design/ant-design/issues/11922#issuecomment-418950280
