### ISSUE TITLE
table使用时,columns的第一项未设置dataIndex时,会导致的报warnging

### ISSUE THREAD

**Issue by wuyandefeixue** [ant-design/ant-design#16642]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xg3lp)

### Steps to reproduce
1.打开连接即可看到warning
2.将columns的第一项dataIndex: "name"注释放开，则正常不报warning

### What is expected?
1.table中已经设置了rowKey，那么dataIndex还是必须的么？
2.如果dataIndex是必须的，那为什么只有columns的第一项必须？当name添加了dataIndex,age未添加dataIndex时并不报warning

### What is actually happening?
报warning的时机没搞懂

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | react |
| System | win10 1709 |
| Browser | Chrome/74.0.3729.108 |

**Comment by zombieJ** [comment]
<img width="550" alt="屏幕快照 2019-05-17 上午11 26 04" src="https://user-images.githubusercontent.com/5378891/57901191-93b43880-7896-11e9-9829-fb623acee1d3.png">

ref: https://ant.design/components/table-cn/#Column

表格分行与列，设置了行的 key (rowKey)，列的 key 当然也需要设置啦~

**Comment by afc163** [comment]
奇怪的是

- 第一列设置 key，其他列都不设，也不会出现 warning。
- 第二列设置 key，其他列都不设，会出现 warning。
- 所有列都不设，会出现 warning。

**Comment by zombieJ** [comment]
因为代码内部是 `key={key || dataIndex}`，`key` 不设置的时候是 `index`，第一个变成了 `0 || undefined` => `undefined`。
