### ISSUE TITLE
Modal 快速打开关闭后页面无法滚动

### ISSUE THREAD

**Issue by 593273894** [ant-design/ant-design#16656]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/modal-cn/](https://ant-design.gitee.io/components/modal-cn/)

### Steps to reproduce
点击OpenModal按钮再关闭。此时焦点在按钮上，按下空格显示Modal，按下esc关闭Modal。空格和esc快速反复按几次，页面就会无法滚动。

### What is expected?
弹窗关闭后页面可以滚动

### What is actually happening?
页面无法滚动

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 最新 |
| System | macos 10.12.6 |
| Browser | chrome 74.0.3729.157 |

---
为了提高操作效率，我们的某些页面提供了快捷键来操作，会很快的打开和关闭弹框，导致页面无法滚动

**Comment by afc163** [comment]
@jljsj33 这个是不是修复了？

**Comment by jljsj33** [comment]
修了
