### ISSUE TITLE
DatePicker shouldn't have min-width as inline style

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#16651]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/15545](https://github.com/ant-design/ant-design/issues/15545)

### Steps to reproduce
the solution for the above issue is to add a min-width on date picker when showTime=true

### What is expected?
hard coded inline style should not be used in a generic purpose widget library like antd

### What is actually happening?
1. using a fixed min-width works really bad with different component size, like size = small
1. using inline min-with instead of css makes it totally impossible to add custom style to the component, like different font or adding icon with css pseudo element
1. it makes the component work inconsistently in the layout, when I shrink the parent div,  normal DatePicker and RangePicker will shrink with parent, but the DatePicker with showTime will be cut off

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome 71 |

---
it would be better to add a css class `ant-calendar-picker-showtime`, and give it proper width with css, as well as combined css for classes like ant-calendar-picker-small
also I would hope you won't use min-width, since the css width will solve 90% problem,   for the other 10% cases when parent is too small, it would still be better to cut off the date text rather than cut the whole component, which leave half of the picker overlap with other element (or hidden, which means you won't be able to click that X button )

**Comment by ifiknew** [comment]
agree with you

**Comment by afc163** [comment]
We don't use `min-width` in antd v4 now, `<input size={xx} />` instead.
