### ISSUE TITLE
DatePicker在iphone6 的浏览器上选择后无法再次选择

### ISSUE THREAD

**Issue by djl0415** [ant-design/ant-design#16654]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-date-render](https://ant.design/components/date-picker-cn/#components-date-picker-demo-date-render)

### Steps to reproduce
选择日期 再次选择不会弹出选择框

### What is expected?
修复问题

### What is actually happening?
选择之后再次点击选择不出现日期选择器

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 3.18.1 |
| System | ios |
| Browser | 未知 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15179#issuecomment-469636039

**Comment by djl0415** [comment]
> [＃15179（评论）](https://github.com/ant-design/ant-design/issues/15179#issuecomment-469636039)

？

**Comment by djl0415** [comment]
> [＃15179（评论）](https://github.com/ant-design/ant-design/issues/15179#issuecomment-469636039)

什么情况

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#antd-%E5%9C%A8%E7%A7%BB%E5%8A%A8%E7%AB%AF%E4%BD%93%E9%AA%8C%E4%B8%8D%E4%BD%B3%E3%80%82
