### ISSUE TITLE
TimePicker In IE browser, in the case of the selection value or the default value, it will flash in the upper left corner of the page when opened.

### ISSUE THREAD

**Issue by zhanghonghncs** [ant-design/ant-design#16657]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/time-picker-cn/](https://ant.design/components/time-picker-cn/)

### Steps to reproduce
Select a TimePicker component with had default value

### What is expected?
Not flashing

### What is actually happening?
flashing

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.0.0 |
| System | win7 |
| Browser | ie9+  |

**Comment by afc163** [comment]
Fixed in `rc-time-picker@3.6.6`, please try reinstall node_modules.
