### ISSUE TITLE
use AutoComplete in Form with get getFieldDecorator can not set validateTrigger as ['onFocus']

### ISSUE THREAD

**Issue by Xuyuey** [ant-design/ant-design#16653]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-herschel-yyk95?fontsize=14)

### Steps to reproduce
1. set the initialValue
2. click the AutoComplete
```
        <Form.Item label="Website">
          {getFieldDecorator("website", {
            initialValue: "xuyue",
            validateTrigger: ["onChange", "onFocus"],
            rules: [{ required: true, message: "Please input website!" }]
          })(
            <AutoComplete
              dataSource={["W", "x", "dfafd", "da", "xxxx", "xdjsad"]}
              placeholder="website"
            />
          )}
        </Form.Item>
```

### What is expected?
fieldValue will not change

### What is actually happening?
fieldValue will be clear

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.4 |
| System | macOS 10.14.4  |
| Browser | Chrome 74.0.3729.157 |

**Comment by zombieJ** [comment]
<img width="691" alt="屏幕快照 2019-05-23 下午11 59 13" src="https://user-images.githubusercontent.com/5378891/58267731-c8ece900-7db6-11e9-9902-319a53d71fed.png">

`onFocus` of AutoComplete do not provides the value of current input which makes Form get empty value from the blur event.
Just use `onChange` to handle this or you can wrap AutoComplete `onFocus` with value as argument 1.
