### ISSUE TITLE
可否添加类似Bootstrap的List group组件，这个组件重用性还是比较高的。

### ISSUE THREAD

**Issue by CrisLi** [ant-design/ant-design#1665]
看到之前有一个issue提到了list组件(https://github.com/ant-design/ant-design/issues/1128)

给出的回答是“目前难以沉淀高复用的组件”。可否参照Bootstrap的List Group 样式，给一个组件，在很多情况下，还是希望能显示一个简单的list，而不是Card。

https://getbootstrap.com/components/#list-group

**Comment by afc163** [comment]
后续可以考虑，敬请期待吧。
