### ISSUE TITLE
Ability to switch between a dark or light theme

### ISSUE THREAD

**Issue by andmev** [ant-design/ant-design#16661]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Future browser versions plan to support new media variable `prefers-color-scheme`.
https://drafts.csswg.org/mediaqueries-5/#prefers-color-scheme

https://caniuse.com/#search=prefers-color-scheme

My propose to make changes in the color palette of the Ant Design. By that when user change theme of the operating system the color scheme of the Ant Design also changes.
However, the user should be able to forcibly select a theme and disable theme change depending on the OS.

### What does the proposed API look like?
This is a simple example of depends on variable `prefers-color-scheme` by the theme.
*Currently works only in Safari 12.1 on macOS Mojave.*

```html
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      body {
        background-color: #d70;
      }

      @media (prefers-color-scheme: light) {
        body {
          background-color: #fff;
          color: #000;
        }
      }

      @media (prefers-color-scheme: dark) {
        body {
          background-color: #000;
          color: #fff;
        }
      }
    </style>
  </head>
  <body>
    <h1>@media (prefers-color-scheme) example</h1>
    <p>
      The <code>prefers-color-scheme</code> media query lets you create light and dark color schemes based on your system preferences.
    <p>
    <p>
      In browsers that support <code>prefers-color-scheme</code> queries, the background of this page will changed by theme of OS.
      Otherwise, the background will be orange.
    </p>
  </body>
</html>
```

**Comment by afc163** [comment]
You can try to custom theme by following https://ant.design/docs/react/customize-theme

**Comment by StallionV** [comment]
+1 for this.
Safari 12.1 + now supports this media query and so it would be great if we are able to set up Antd to specify theme and pick it based on user OS theme and also and option to override it.
