### ISSUE TITLE
在使用Slider的时候设置了tooltipVisible显示 但是切换了tab后tooltip的定位会错乱，导致tooltipVisible显示功能无法在tabs里用

### ISSUE THREAD

**Issue by JulesCesar** [ant-design/ant-design#16669]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider-cn/](https://ant.design/components/slider-cn/)

### Steps to reproduce
tabs组件的内容里引入slider 然后切换tab就会出现tooltip错位的问题，切换了tab但是tooltip还在页面上。

### What is expected?
我如何修复此bug

### What is actually happening?
tooilp显示功能无法在tabs里用

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.6.3 |
| System | mac |
| Browser | chrome |

这是正常的
![image](https://user-images.githubusercontent.com/19618696/58000084-51932d00-7b0a-11e9-91cb-4529e80bf8fa.png)

这个是我切换了tabs后的
![image](https://user-images.githubusercontent.com/19618696/58000113-68d21a80-7b0a-11e9-8184-3213ff4c228b.png)

**Comment by JulesCesar** [comment]
> 你好@JulesCesar。请提供此链接https://u.ant.design/codesandbox-repro或最小的GitHub存储库，以提供在线复制。标记为的问题`Need Reproduce`将在7天内没有活动时关闭。
> 
> 你好@JulesCesar，我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击[此处](https://u.ant.design/codesandbox-repro)创建一个代码盒或者提供一个最小化的GitHub仓库.7天内未跟进的问题会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)


地址您看一下可以打开嘛
https://codesandbox.io/s/antd-reproduction-template-p9zsk

**Comment by JulesCesar** [comment]
我创建了一个tabs 然后分别放入三个slider 切换tabs slider上面的toolip 就会一直在页面上  实际上应该跟着他的tabs一起消失

**Comment by afc163** [comment]
加个 `destroyInactiveTabPane`

https://codesandbox.io/s/antd-reproduction-template-3m18f

**Comment by JulesCesar** [comment]
> 加个 `destroyInactiveTabPane` 可行。
> 
> https://codesandbox.io/s/antd-reproduction-template-3m18f

但是这样是否就第二个tabs里的tooltip的默认显示也被销毁了？

**Comment by afc163** [comment]
确实有点问题。

**Comment by JulesCesar** [comment]
> 确实有点问题。

辛苦啦

**Comment by afc163** [comment]
可以帮我们排查一下来个 PR，可能没什么时间去跟进。

**Comment by yoyo837** [comment]
```jsx
import { alignElement, alignPoint } from 'dom-align';
```
`alignElement`的处理

初始第一个默认tab正常，切换到第二个时：

![image](https://user-images.githubusercontent.com/6134547/58082088-e409fe00-7be8-11e9-8597-fa66defc6741.png)

鼠标hover一下后：
![image](https://user-images.githubusercontent.com/6134547/58082116-ef5d2980-7be8-11e9-90d2-f1964e60407d.png)

怀疑与切换tab时children的mounted与alignElement执行时机有关；暂时看到这里，供参考。

**Comment by yoyo837** [comment]
应该是`transition: margin-left` 的原因。

**Comment by ztplz** [comment]
应该不是吧  我记得默认是根绝body定位的  我等下看看

**Comment by ztplz** [comment]
@yoyo837 `getcontainer`指定handle就行了

**Comment by yoyo837** [comment]
@ztplz 这算绕过问题本身吧!
