### ISSUE TITLE
TypeScript Form.create definition error when upgrade to 3.18.1 from 3.16.3.

### ISSUE THREAD

**Issue by XGHeaven** [ant-design/ant-design#16662]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-mcclintock-mvuni?fontsize=14)

### Steps to reproduce
正常编写

### What is expected?
Form.create 的时候应该自动将一些注入的 props 删除掉，也就是 form。这个在 3.16.3 是没有问题的，定义正常

### What is actually happening?
但是在升级到 3.18.1 之后，类型定义出现了问题。他无法继承类型，只剩下了 form 和 wrappedComponentRef 这两个 props.

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16.6.3 |
| System | MacOs |
| Browser | Chrome 74 |

---
我用了 antd 很久了，但是有一点我忍不了，就是类型定义能不能稳定并正确一点？
就是之前出现过升级降级都导致了类型的不正确，只有在某个版本才正确，而且有些类型定义也是缺失的。
讲道理，整个项目都是用 ts 写的，不应该出现这个问题才对，但是实际上确实出现了这个问题。
小吐槽一下，请勿介意。

**Comment by zombieJ** [comment]
参考一下文档：https://ant.design/components/form-cn/#%E5%9C%A8-TypeScript-%E4%B8%AD%E4%BD%BF%E7%94%A8
```tsx
interface UserFormProps extends FormComponentProps {
  age: number;
  name: string;
}

const App = Form.create<UserFormProps>()(UserForm);
```

我们的 TypeScript 定义会保持 `@types/react` 和 `typescript` 同步。有些时候 `@types/react` 更新会导致一些原有的写法失效，所以才会遇到升级降级定义出问题的情况。

举个例子，[Button](https://github.com/ant-design/ant-design/issues?utf8=%E2%9C%93&q=is%3Aissue+button+typescript) 的定义由于 `@types/react` 更新一段时间内反复出问题，因而我们也跟着一起来回调整。

关于定义缺失是由于 antd 依赖的 rc 组件大部分是 js 写的，所以定义在 antd 上难免会有疏漏。如果遇到少了的定义，欢饮发 PR 一起帮忙补全哈~
