### ISSUE TITLE
Re-word step 2 of the Ant Design PR Principle section in the PR Principles page

### ISSUE THREAD

**Issue by dmkato** [ant-design/ant-design#16665]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Makes the documentation more approachable to newcomers

### What does the proposed API look like?
Ant Design PR Principle

0. This principle is suitable for ant-design and ant-design-pro.
1. As current agreement, any new feature branch must PR to feature branch.
2. The new feature branch contains new features added, obviously UI modification, interactive update, reconstruction, etc.
3. feature branch is locked and not allow push code directly. All the modification must use Pull Request.

**Comment by afc163** [comment]
PR is welcome~

**Comment by afc163** [comment]
Feel free to send us PR and closing this now.
