### ISSUE TITLE
Add more information on where to find all scripts in development workflow section of contributing. 

### ISSUE THREAD

**Issue by dmkato** [ant-design/ant-design#16664]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Makes new users more aware of everything they can do with the project

### What does the proposed API look like?
Development Workflow#

After cloning antd, run npm install to fetch its dependencies. Then, you can run several commands:
npm start runs Ant Design website locally.
npm run lint checks the code style.
npm test runs the complete test suite.
npm run compile compiles TypeScript code to the lib and es directory.
npm run dist creates UMD build of antd.

These and more exist in the package.json file in the root of the repository.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16665#issuecomment-493816032

**Comment by afc163** [comment]
Feel free to send us PR and closing this now.
