### ISSUE TITLE
Add Popover "OnClose"

### ISSUE THREAD

**Issue by ChuckJonas** [ant-design/ant-design#16668]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently if you take  "control" a popover (EG pass in `visible` prop), there is no easy way to implement "close on click outside" functionality.  Adding a property `onClose: (e) => void` would be constant with the modal functionality.

I'm trying to use a popover, with a click trigger, which I can tell to close (for example, after clicking a button inside the popover).

### What does the proposed API look like?
`onClose: (e) => void`: Runs whenever a close event is fired.  Based on the trigger type?

**Comment by afc163** [comment]
`onVisibleChange`

**Comment by ChuckJonas** [comment]
sry, I didn't see that in the docs! (now, I see there is an example tho)

**Comment by TangMonk** [comment]
```
onVisibleChange
```
seems not work
