### ISSUE TITLE
Tooltip组件的title属性如果特别长的话，怎样控制换行和缩进？

### ISSUE THREAD

**Issue by tianyacsdn** [ant-design/ant-design#1667]
Table中的一些字段数据太长，为了美观，在Table中只截取一部分显示，鼠标移动到此字段上时，使用Tooltip显示所有数据，这个时候需要控制Tooltip的换行，怎样实现换行和缩进呢？？？

**Comment by tianyacsdn** [comment]
![image](https://cloud.githubusercontent.com/assets/19320333/15205660/d8950b68-184b-11e6-8cf9-93d16fc63b72.png)
Tooltip组件自己进行了换行，但是我看不出换行的规律是什么，而且我想要的效果是以JSON格式化显示，在alert()中是正常以JSON格式化的，但是在Tooltip中就变成了这样，怎样才能控制title属性的换行和缩进呢？

**Comment by benjycui** [comment]
Tooltip 也不是用来显示这么复杂的数据的：http://ant.design/#/components/tooltip?scrollTo=%E4%BD%95%E6%97%B6%E4%BD%BF%E7%94%A8

改用 Modal 如何？

**Comment by afc163** [comment]
大量数据建议用 Popover ，截断样式自行控制。

**Comment by afc163** [comment]
http://www.w3school.com.cn/cssref/pr_text_white-space.asp
http://www.w3school.com.cn/cssref/pr_word-wrap.asp

**Comment by tianyacsdn** [comment]
使用了Popover,但是title显示有值，content为空，这是什么原因啊？


发自 网易邮箱大师
在2016年05月12日 14:26，偏右 写道:

大量数据建议用 Popover ，截断样式自行控制。

**Comment by afc163** [comment]
你这么简约的问题，我也不知道原因啊。给我更多的信息？

**Comment by tianyacsdn** [comment]
代码截图在附件，都是按示例写的


发自 网易邮箱大师
在2016年05月12日 16:07，偏右 写道:

你这么简约的问题，我也不知道原因啊。给我更多的信息？

**Comment by afc163** [comment]
这是 GitHub ，哪来的附件。You must be kidding me...

**Comment by tianyacsdn** [comment]
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by tianyacsdn** [comment]
![Uploading image.png…]()

**Comment by tianyacsdn** [comment]
![image](https://cloud.githubusercontent.com/assets/19320333/15208874/a2f8a9d2-1860-11e6-94af-8aed22e5109c.png)
![image](https://cloud.githubusercontent.com/assets/19320333/15208879/aefe4976-1860-11e6-8d0c-02af7e68d307.png)
![image](https://cloud.githubusercontent.com/assets/19320333/15208892/b9734046-1860-11e6-8f65-022fc6f8e532.png)
![image](https://cloud.githubusercontent.com/assets/19320333/15208917/cff20654-1860-11e6-90f8-31563e178cd1.png)
![image](https://cloud.githubusercontent.com/assets/19320333/15208929/e3571f40-1860-11e6-88b4-b25ff94de35b.png)

你们遇到过这个问题吗？@afc163

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1645
