### ISSUE TITLE
<a href /> can not open new window in Popconfirm in some case

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#16671]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdhrefcannotopen-ctktq)

### Steps to reproduce
1. hover on `<h2 />` element
1. try click the link and failed
1. delete `<h1 />` element
1. try click the link and succeed

### What is expected?
the `<a href />` open a new window correctly

### What is actually happening?
it doesn't

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
ehmmm...that is crazy.
