### ISSUE TITLE
Having an issue in custom form control

### ISSUE THREAD

**Issue by justinlazaro-ubidy** [ant-design/ant-design#16676]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-custom-form-input-hooks-x3l2y205ow)

### Steps to reproduce
Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.

### What is expected?
Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.

### What is actually happening?
Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.1 |
| System | windows |
| Browser | chrone |

**Comment by afc163** [comment]
I didn't find any errors or warnings in your codesandbox.

**Comment by justinlazaro-ubidy** [comment]
Already fix, my issue is set defaultProps instead of initialValue thanks.
