### ISSUE TITLE
SideMenu component has no on focus state for accessibility.

### ISSUE THREAD

**Issue by davidakerr** [ant-design/ant-design#16682]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-forest-01ie7?fontsize=14)

### Steps to reproduce
Press Tab, expand link shows highlighted on focus but links do not.

### What is expected?
There should be a visual indication of when the user is focus on the selected menu item.

### What is actually happening?
No indication to user

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.6 |
| System | OSX 10.14.4 |
| Browser | Chrome 74.0.3729.131 |

**Comment by afc163** [comment]
Trace #22343
