### ISSUE TITLE
Timepicker allowClear is not working, but allowEmpty is working as allwoClear. Not documented properly 

### ISSUE THREAD

**Issue by jccgadam** [ant-design/ant-design#16687]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/time-picker/](https://ant.design/components/time-picker/)

### Steps to reproduce
Timepicker allowClear is not working, but allowEmpty is working as allwoClear. 
Not documented properly 

### What is expected?
allowClear works as documented or documentations list the right options 

### What is actually happening?
allowClear not working but allowEmpty is working as allowClear. 

| Environment | Info |
|---|---|
| antd | 3.6.4 |
| React | 16.4.1 |
| System | macOS |
| Browser | chrome |

---
Not sure under newest version, does allowClear is working properly

**Comment by afc163** [comment]
https://ant.design/changelog#3.13.0

<img width="787" alt="image" src="https://user-images.githubusercontent.com/507615/58063627-902ff280-7bb1-11e9-9336-4ef3eda7d7bc.png">
