### ISSUE TITLE
Modal组件和Drawer组件组合使用导致页面滚动条错误

### ISSUE THREAD

**Issue by shijunwen** [ant-design/ant-design#16680]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/495zk)

### Steps to reproduce
1、点击打开抽屉
2、接着打开Modal框
3、接着关闭Modal框

### What is expected?
点击打开抽屉，这时底层div无法滚动。打开Modal框接着关闭Modal框，底层div不出现滚动条，不能滚动

### What is actually happening?
点击打开抽屉，这时底层div无法滚动。打开Modal框接着关闭Modal框，底层div出现滚动条，能滚动。

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | react 16.8.6 |
| System | windows 10 |
| Browser | Google Chrome 版本 74.0.3729.131（正式版本） （32 位） |

**Comment by jljsj33** [comment]
重复了，看 #17323 ,,,这个先关闭了....

**Comment by bazoon** [comment]
is it fixed?

**Comment by jljsj33** [comment]
见 17323
