### ISSUE TITLE
Please add an important reminder in the manual

### ISSUE THREAD

**Issue by heytheww** [ant-design/ant-design#16689]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-global-state](https://ant.design/components/form/#components-form-demo-global-state)

### Steps to reproduce
Please tell the user that when you use onFieldsChange(props, changedFields) and mapPropsToFields(props), you should place the generated >>changedFields<< on top of the component props. If you need a prompt effect, the form component will also have a wrapper <Form.Item>

### What is expected?
show some tips

### What is actually happening?
no tips

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.7.0 |
| System | windows 10 |
| Browser | chrome 74.0.3729.157 |

**Comment by afc163** [comment]
Feel free to send us PR and closing this now. 😊
