### ISSUE TITLE
数字统计的Statistic.Countdown

### ISSUE THREAD

**Issue by zxt-gitDemo** [ant-design/ant-design#16699]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/statistic-cn/](https://ant.design/components/statistic-cn/)

### Steps to reproduce
倒计时点击后，<Countdown value={Date.now()  1000 * 60}  onFinish={()=>this.setState({status:false})} format="ss">  status状态无法改变，onFinish不执行。

### What is expected?
怎么样才能成功执行onFinish方法

### What is actually happening?
onFinish方法，不执行

| Environment | Info |
|---|---|
| antd | 3.13.5 |
| React | react  ^16.8.3 |
| System | window |
| Browser | 谷歌 |

**Comment by zxt-gitDemo** [comment]
访问https://www.xiaoniuzp.com/，注册发送验证码。




------------------ 原始邮件 ------------------
发件人: "Ant Design GitHub Bot"<notifications@github.com>; 
发送时间: 2019年5月21日(星期二) 下午2:26
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "落秋"<534211464@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ant-design/ant-design] 数字统计的Statistic.Countdown (#16699)




Hello @zxt-gitDemo. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
你好 @zxt-gitDemo, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by afc163** [comment]
https://u.ant.design/codesandbox-repro

**Comment by zombieJ** [comment]
不是网站，需要最小代码重现……

**Comment by zxt-gitDemo** [comment]
import React, { PureComponent } from 'react';
import { message,Button,Row,Col,Input,Statistic} from 'antd';
import {sendCode,goRegister} from '../../services/user'
import moment from 'moment';
import 'moment/locale/zh-cn';
moment.locale('zh-cn');
const Countdown = Statistic.Countdown;
export default class Register extends PureComponent {
    constructor(props){
        super(props)
        this.state={
        }
    }
    isPone (value) {  
        var myreg = /^[1][3,9,4,6,5,7,8][0-9]{9}$/; 
        if (!myreg.test(value)) {       
             if(!value){
              return true
            }else{
              return false
              }
        } else {  
                return true
        }  
    } 
    setTimer(){
        let {phone,status}=this.state
      
        if(phone){
            let isphone=this.isPone(phone)
            if(isphone){
                this.setState({
                    status:!status
                })
                if(!status){
                    sendCode({phone}).then(res=>{
                        if(res.code===0){
                            message.success('发送成功！')
                        }else{
                            this.setState({status:false})
                            message.error(res.msg||'发送失败，请重试！')
                        }
                    })
                }
            }else{
                 message.error('请输入正确的手机号！')
            }
        }else{
            message.error('请输入手机号！')
        }
     
    }
    subimit(){
        let {phone,code,password}=this.state
        if(phone){
            if(code){
                if(password){
                    this.setState({
                        loading:true
                    },()=>{
                        goRegister({phone,code,password}).then(res=>{
                            if(res.code===0){
                                message.success(res.msg||'注册成功！')
                                this.props.onChangeType()
                            }else{
                                this.setState({status:false})
                                message.error(res.msg||'注册失败，请重试！')
                            }
                            this.setState({loading:false})
                        })
                    })
                   
                }else{message.error('请输入密码！')}
            }else{message.error('请输入验证码！')}
        }else{message.error('请输入手机号！')}
    }
    render(){
        let {status,phone,code,password,loading}=this.state
        console.log(this.state.status)
        return (
            <div  style={{
                background:'#fff',width:'100%',height:'100%',padding:'0.45rem',position:'relative'}}>
                <div
                    onClick={()=>this.props.onChangeType()}
                    style={{position:'absolute',top:'0.3rem',right:'0.3rem',display:'flex',alignItems:'center',cursor:'pointer'}}>
                    <div 
                     className="loginimg"></div><span style={{color:'#999',fontSize:'0.16rem',marginLeft:'0.1rem'}}>登录</span>
                </div>
                <div style={{margin:'0.45rem 0 0.6rem',fontSize:'0.24rem',textAlign:'center',fontWeight:600}}>账号注册</div>
                <div style={{borderBottom:'2px solid #CBCBCB',marginBottom:10}}>
                <Input className="inputNoborder"
                value={phone}
                onChange={(e)=>this.setState({phone:e.target.value})}
                 style={{height:40}} placeholder="请输入手机号"/>
                </div>
                <Row style={{borderBottom:'2px solid #CBCBCB',marginBottom:10}}>
                    <Col span="16">
                    <Input className="inputNoborder"
                    value={code}
                    onChange={(e)=>this.setState({code:e.target.value})}
                     style={{height:40}} placeholder="请输入验证码" style={{border:'none'}}/>
                    </Col>
                    <Col span="8">
                    <Button style={{width:'100%',background:'#454545',color:'#fff'}} 
                    disabled={status}
                    onClick={()=>this.setTimer()}
                    >
                    {status?
                    <Countdown value={Date.now()+ 1000 * 60}  onFinish={()=>this.setState({status:false})} format="ss"
                    valueStyle={{color:'#fff',fontSize:14}} />
                    :'发送验证码'}
                    </Button>
                    
                    </Col>
                </Row>
                <div style={{borderBottom:'2px solid #CBCBCB',marginBottom:10}}>
                <Input.Password
                value={password}
                onChange={(e)=>this.setState({password:e.target.value})}
                className="inputNoborder" style={{height:40}} placeholder="设置密码"/>
                </div>
                <div style={{position:'absolute',bottom:'0.7rem',left:0,textAlign:'center',width:'100%'}}>
                    <Button style={{width:'3rem',borderRadius:30}} loading={loading} type="primary" onClick={()=>this.subimit()} >确认</Button>
                </div>
          </div>
        )
    }
}






------------------ 原始邮件 ------------------
发件人: "zombieJ"<notifications@github.com>; 
发送时间: 2019年5月21日(星期二) 下午2:31
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "落秋"<534211464@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [ant-design/ant-design] 数字统计的Statistic.Countdown (#16699)




不是网站，需要最小代码重现……

**Comment by zombieJ** [comment]
@zxt-gitDemo，用这个写一下可运行的最小重现：https://u.ant.design/codesandbox-repro

**Comment by afc163** [comment]
<img width="909" alt="image" src="https://user-images.githubusercontent.com/507615/58089074-8bd9f880-7bf6-11e9-9ecc-2d1dfe19a55d.png">
