### ISSUE TITLE
AutoComplete-bug

### ISSUE THREAD

**Issue by shuyancang** [ant-design/ant-design#16697]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-ii5bt)

### Steps to reproduce
1. 指定控件AutoComplete的value，在触发handleSerach时将参数保存作为下一次的value;
2. 使用中文输入法输入“这是”

### What is expected?
input搜索框内应该是'zheshi'

### What is actually happening?
zzhzhezheszheshzheshi；每次输入中文输入法会将上次的英文反复携带进行输入。

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.9.0 |
| System | windows |
| Browser | Google Chrome 70.0.3538.110 |

**Comment by zombieJ** [comment]
如果需要 `value` 受控，使用 `onChange`。 `onSearch` 是用于搜索，不是控制 `value` 的。
