### ISSUE TITLE
Select Component - Ability to show some custom text instead of selected values

### ISSUE THREAD

**Issue by manishbisht** [ant-design/ant-design#16696]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My dropdown has 100 values and out of which 99 are selected. Now showing 99 selected value on the screen is pain. Can we show something like "99 Values selected" or may be some custom text that can be passed as props to the component. It can be string or ReactNode.

### What does the proposed API look like?
<Select mode="multiple" customSelectedValue="99 Values Selected"></Select>

**Comment by afc163** [comment]
`maxTagPlaceholder`
