### ISSUE TITLE
upload button is wrapped with a span with incorrect height

### ISSUE THREAD

**Issue by picodoth** [ant-design/ant-design#16690]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oopjz45v66)

### Steps to reproduce
use dev tool to inspect the element

### What is expected?
the outmost dom wrapper should have correct height

### What is actually happening?
the outmost dom wrapper has an incorrect height

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | latest |
| System | macOS 10.12.6 |
| Browser | Chrome: Version 74.0.3729.157 (Official Build) (64-bit) |

![image](https://user-images.githubusercontent.com/1731837/58064143-90c98880-7bb3-11e9-9d21-8110dcc9ba9b.png)

**Comment by picodoth** [comment]
![image](https://user-images.githubusercontent.com/1731837/58064143-90c98880-7bb3-11e9-9d21-8110dcc9ba9b.png)

**Comment by afc163** [comment]
We can't change this now, what is the exact problem you meet.
