### ISSUE TITLE
当Table设置filter后，不会跳转到table的第一页？

### ISSUE THREAD

**Issue by seraphimrose** [ant-design/ant-design#1669]
假设table有10页数据，选择到第10页，设置filter后只剩5页，而由于当前是第10页，Table会显示“暂无数据”。

antd版本：0.12.12

**Comment by seraphimrose** [comment]
可能描述有点不清，是指选了 预先定义的某个filter 后导致数据量会减少 但因为本身不会跳转到第一页而出现 不存在的空页

**Comment by superRaytin** [comment]
使用官网的例子，按照这样操作貌似不能重现：http://012x.ant.design/components/table/#demo-paging

不地 0.12.x 没有 standalone 版本，也不好写 codepen，不过还是麻烦你提供下能重现的 demo：http://codepen.io/anon/pen/wGOWGW?editors=001 😂 方便测试

**Comment by seraphimrose** [comment]
直接提供中间的代码好了

const columns = [{
	title: '姓名',
	dataIndex: 'name'
}, {
	title: '年龄',
	dataIndex: 'age',
	filters: [{
		text: "大于30岁",
		value: "30"
	}],
	onFilter: (value, item) => parseInt(item.age) > parseInt(value)
}, {
	title: '住址',
	dataIndex: 'address'
}];

const data = [];
for (let i = 0; i < 46; i++) {
	data.push({
		key: i,
		name: `李大嘴${i}`,
		age: i,
		address: `西湖区湖底公园${i}号`
	});
}

return <Table columns={columns} dataSource={data}/>

就是生成View后，上述例子选到第五页，再进行filter设置，不会进行常规的首页跳转，而是现实无数据，这样应该会产生误导吧？

**Comment by seraphimrose** [comment]
上面的<Table 这几个字好像被github吞了
