### ISSUE TITLE
checkbox checked icon is not in the center of the input in selection table

### ISSUE THREAD

**Issue by GFwer** [ant-design/ant-design#16695]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-river-offof)

### Steps to reproduce
set Table with `bordered: true`

### What is expected?
the icon should be in the center of the input

### What is actually happening?
the icon is in the left of the input

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.6 |
| System | MacOS 10.14.3 |
| Browser | Chrome 76.0.3795.3 & 76.0.3800.0 |

![Kapture 2019-05-21 at 11 02 37](https://user-images.githubusercontent.com/14303098/58065434-48f93000-7bb8-11e9-940a-748994208dac.gif)

**Comment by MrHeer** [comment]
Can we do this:
[mixin.less#L64](https://sourcegraph.com/github.com/ant-design/ant-design/-/blob/components/checkbox/style/mixin.less#L64)
```diff
  top: 50%;
- left: 21%;
+ left: 50%;
  display: table;
```
[mixin.less#L99](https://sourcegraph.com/github.com/ant-design/ant-design/-/blob/components/checkbox/style/mixin.less#L99)
```diff
  border-left: 0;
- transform: rotate(45deg) scale(1) translate(-50%, -50%);
+ transform: rotate(45deg) scale(1) translate(-100%, -20%);
  opacity: 1;
```
[Preview](https://codepen.io/MrHeer/pen/yWzGGa?editors=0010)

**Comment by GFwer** [comment]
@MrHeer Great! My temporary solution is changing `21%` to `22%` but it 's too ugly 😂

**Comment by MrHeer** [comment]
I have tried your solution, I can't see the difference between them. :joy:

**Comment by zombieJ** [comment]
Seems a Chrome bug with collapsed bordered table. It get check box position as decimal:
```
$0.getBoundingClientRect()
DOMRect {x: 46.5, y: 164, width: 16, height: 21, top: 164, …}
```

Change percentage may be not best solution since we've adjust the percentage multiple time ...

**Comment by chiaweilee** [comment]
> Can we do this:
> [mixin.less#L64](https://sourcegraph.com/github.com/ant-design/ant-design/-/blob/components/checkbox/style/mixin.less#L64)
> 
> ```diff
>   top: 50%;
> - left: 21%;
> + left: 50%;
>   display: table;
> ```
> 
> [mixin.less#L99](https://sourcegraph.com/github.com/ant-design/ant-design/-/blob/components/checkbox/style/mixin.less#L99)
> 
> ```diff
>   border-left: 0;
> - transform: rotate(45deg) scale(1) translate(-50%, -50%);
> + transform: rotate(45deg) scale(1) translate(-100%, -20%);
>   opacity: 1;
> ```
> 
> [Preview](https://codepen.io/MrHeer/pen/yWzGGa?editors=0010)
This works for me.

**Comment by afc163** [comment]
https://codesandbox.io/s/magical-williams-36q12 from https://github.com/ant-design/ant-design/issues/19450
