### ISSUE TITLE
How to respond to github updated the content of the EAR

### ISSUE THREAD

**Issue by howel52** [ant-design/ant-design#16691]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
> [GitHub.com, GitHub Enterprise Server, and the information you upload to either product may be subject to US export control laws, including U.S. Export Administration Regulations (the EAR).](https://help.github.com/en/articles/github-and-export-controls)

Is there any legal risk in the future development of this warehouse?

There are many companies in China that use this repo. Is there any legal risk in the future development of this repo?

### What does the proposed API look like?
I hope there is a simple explanation

**Comment by afc163** [comment]
I don't think there is any risk: https://github.com/ant-design/ant-design/blob/master/LICENSE

https://zhuanlan.zhihu.com/p/66421045

**Comment by howel52** [comment]
> I don't think there is any risk: https://github.com/ant-design/ant-design/blob/master/LICENSE
> 
> https://zhuanlan.zhihu.com/p/66421045

thx :)
