### ISSUE TITLE
customized render of selected items in select control

### ISSUE THREAD

**Issue by DongShi** [ant-design/ant-design#16709]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
User can have different look and feel between options and selected items.
For example, in following senario, options can provide detailed information while selected items just provide some critical information.

![image](https://user-images.githubusercontent.com/5009987/58082165-03a12680-7be9-11e9-8519-5480c91f802f.png)

### What does the proposed API look like?
expose an api in select like renderSelectedItem so user can have different APIs to decide the look & feel of options and selected items/tags.

**Comment by afc163** [comment]
Try `optionLabelProp`

**Comment by DongShi** [comment]
thanks @afc163  for the quick tip.
However, I believe optionLabelProp is a nice fit for string based options, however for DOM based options (like in our case, it is a avatar(img) + text(div) comb), it will fail to work.
Any further thoughts / advices?

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-tk678

**Comment by DongShi** [comment]
Works like a charm! Thanks again.
