### ISSUE TITLE
<Menu> prop `inlineCollapsed` in <Sider> is  uneffective

### ISSUE THREAD

**Issue by 5201314999** [ant-design/ant-design#16701]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/buhaoyisiwoyao/pen/QRqzJj](https://codepen.io/buhaoyisiwoyao/pen/QRqzJj)

### Steps to reproduce
set inlineCollapsed={true} in  Sider

### What is expected?
set inlineCollapsed={true} but it is uneffective

### What is actually happening?
set inlineCollapsed={true} but it is uneffective

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome |

**Comment by leijingdao** [comment]
外面的sider  collapsed={true} 好像就变成inline了，这应该不算bug吧？

**Comment by zombieJ** [comment]
的确不算 bug，加个 warning 提醒一下用户好了。

**Comment by harish-madugula** [comment]
I have this issue, is there a way to get around this?
any help is appreciated...thanks in advance
