### ISSUE TITLE
Drawer doesn't animate when the prop "getContainer" is added

### ISSUE THREAD

**Issue by elderdog** [ant-design/ant-design#16707]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer/](https://ant.design/components/drawer/)

### Steps to reproduce
1. Add prop "getContainer" to a Drawer
2. Toggle prop "visible"

### What is expected?
Animation should be performed

### What is actually happening?
Drawer doesn't animate

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | Which https://ant.design/components/drawer/ is using |
| System | macOS 10.14.2 |
| Browser | Chrome 74.0.3729.157 |

**Comment by elderdog** [comment]
> Hello @elderdog. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @elderdog, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

this is the reproduction [https://codesandbox.io/s/antd-reproduction-template-ybdu4](url)
I have tried 3 ways:

1. Selectors `works well`
2. HTMLElement `works well`
3.() => HTMLElement `the first time when I opened the drawer, animation was performed, after that when I open or close, no animation is performed`

**Comment by sunclelee** [comment]
thanks for elderdog because i have the same problem.
when i change "() => HTMLElement " to "selectors"，it works correctly.
