### ISSUE TITLE
table 表头的筛选icon点击后错位

### ISSUE THREAD

**Issue by YAN7** [ant-design/ant-design#16704]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/n90m38q05p)

### Steps to reproduce
1. 点击筛选icon后发现icon向下偏移了

### What is expected?
点击筛选icon时icon不偏移

### What is actually happening?
点击筛选icon时icon向下偏移

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8 |
| System | macOS 10.13.4 |
| Browser | chrome 76.0.3795.3 |

---
官网的例子就有这个bug，这影响了筛选功能的基本使用了。

**Comment by afc163** [comment]
没发现问题，可以录一个 GIF 么。

**Comment by YAN7** [comment]
@afc163 
[截了个图](https://i.loli.net/2019/05/21/5ce3ae3504a8f58177.png)

**Comment by afc163** [comment]
<img width="682" alt="image" src="https://user-images.githubusercontent.com/507615/58079617-fb92b800-7be3-11e9-9c01-6d71a5f627d7.png">

`Mac Chrome 74.0.3729.157` 里没重现出来。

**Comment by YAN7** [comment]
把chrome退回稳定版，也试了其他浏览器，确实没重现，看来是chrome开发版的问题
