### ISSUE TITLE
DatePicker 设置format="YYYY-MM-DD" 提交的数据不正确

### ISSUE THREAD

**Issue by xiaopanghhh** [ant-design/ant-design#16711]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
<DatePicker
                  style={{ width: '100%' }}
                  format="YYYY-MM-DD"
                  placeholder={formatMessage({
                    id: 'bill.fieldTicketSummary.endTime.placeholder',
                  })}
                />

提交的数据变为 
endTime: "2019-05-22T09:46:33.392Z"

### What is expected?
endTime: "2019-05-22 00:00:00"

### What is actually happening?
endTime: "2019-05-22"

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.17 |
| System | MacOs |
| Browser | Chrome |

---
日期选择控件，选择日期后，提高的时候默认加入了当前时间的时分秒等信息。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13469#issuecomment-444858838
https://github.com/ant-design/ant-design/issues/14901#issuecomment-464698198
