### ISSUE TITLE
InputNumber set precision bug

### ISSUE THREAD

**Issue by cornwang** [ant-design/ant-design#16710]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-wave-23nll?fontsize=14)

### Steps to reproduce
1. Write the first input box as 2
2. Then write the second input box as 1.23
3. Then change the first input box to 1
4. At this point you can see that the second input box becomes 1.2. This is the result we want.
5. Then write the first input box as 0
6. Will you see the second input box become 1.23? ? ?

### What is expected?
希望输入0 应该变成1

### What is actually happening?
1.23

| Environment | Info |
|---|---|
| antd | 3.10.9 |
| React | 16.8.6 |
| System | mac |
| Browser | Google Chrome  74.0.3729.157 |

**Comment by MrHeer** [comment]
I think the reason is here: [input-number#517](https://sourcegraph.com/github.com/react-component/input-number/-/blob/src/index.js#L517)
```js
if (precision === 0) {
  return num.toString();
}
```

**Comment by michaelcopino** [comment]
inputNumber is accepting letter "e"

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/68372283-8445e600-017b-11ea-9c2d-ff24efe2cc2d.png)
