### ISSUE TITLE
Mention 组件 Mac 触摸板的点击速度过快会报错

### ISSUE THREAD

**Issue by shockerli** [ant-design/ant-design#16713]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/mention-cn/](https://ant.design/components/mention-cn/)

### Steps to reproduce
官方文档（版本 3.18）Mention 组件下的【配合 Form 使用】演示项就能复现。
https://ant.design/components/mention-cn/

【复现步骤】
对着含有@的值进行点击，出现一个相同的选项值，再对该选项值进行点击。反复如此操作就会出现问题。

关键操作：点击速度很重要、Mac 触摸板 触摸式点击操作（非按下）

关键代码：

```js
<FormItem
  id="control-mention"
  label="Top coders"
  labelCol={{ span: 6 }}
  wrapperCol={{ span: 16 }}
>
  {getFieldDecorator('mention', {
    rules: [{ validator: this.checkMention }],
    initialValue: this.state.initValue,
  })(
    <Mention
      defaultSuggestions={['afc163', 'benjycui', 'yiminghe', 'RaoHai', '中文', 'にほんご']}
    />,
  )}
</FormItem>
```
最关键的是`initialValue`，如果换成`Mention.defaultValue`进行初始化值，就不会有问题

### What is expected?
能正常选择

### What is actually happening?
手速快的触摸点击就会报错

| Environment | Info |
|---|---|
| antd | 3.10.9 |
| React | 16.5.1 |
| System | macOS 10.14.2 (18C54) MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports) |
| Browser | Chrome 74.0.3729.131 |

**Comment by yoyo837** [comment]
没试出来 🙃

**Comment by shockerli** [comment]
> 没试出来 🙃

与手速有关，有点人触摸的慢，那就复现不了。我每次都能复现😆

**Comment by yoyo837** [comment]
来个gif？

**Comment by zombieJ** [comment]
试试新的 Mentions 组件哈~

**Comment by afc163** [comment]
应该给个链接

**Comment by shen-zhao** [comment]
![image](https://user-images.githubusercontent.com/23046267/58780902-f20a4680-860c-11e9-8253-44d53780c510.png)
https://ant.design/components/mention-cn/#components-mention-demo-controlled

**Comment by shen-zhao** [comment]
> 应该给个链接

![image](https://user-images.githubusercontent.com/23046267/59018381-5a109500-8878-11e9-90d6-39339bdb6f61.png)
https://ant.design/components/mention-cn/#components-mention-demo-controlled
