### ISSUE TITLE
Tabs没有找到onNextClick,onPrevClick的示例

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#16719]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
查看了官方示例，没有找到，也在其他提问的交流网站上没有找到

### What is expected?
Tabs没有找到onNextClick,onPrevClick的示例

### What is actually happening?
Tabs有onNextClick,onPrevClick的示例

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | latest |
| System | windows10 |
| Browser | chrome74 |

**Comment by XianZhengquan** [comment]
@zombieJ 老哥，这个咋个用的？主要是不知道这个next按钮和prev按钮咋个出来的？没有示例

**Comment by afc163** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/507615/58142689-aeadf080-7c7a-11e9-889c-e037b114cedc.png">

https://ant.design/components/tabs-cn/#components-tabs-demo-slide

这个例子现在 tabs 不够多，可以加几个。

**Comment by XianZhengquan** [comment]
这样啊，我还是以为是上一步和下一步那种步骤条呢，了解了
