### ISSUE TITLE
"Transform" in the Form `getFieldDecorator` -> `validateFields` does not work; always returns a string. 

### ISSUE THREAD

**Issue by thisissami** [ant-design/ant-design#16724]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wandering-firefly-vu2jq?fontsize=14)

### Steps to reproduce
Create a form using `getFieldDecorator`. Pass it an option of `transform: value => parseFloat(value)`. then run `validateFields` (provided by antd Form).

### What is expected?
The expected `values` object in the `validateFields` callback will have an attribute with a number. 

### What is actually happening?
The `values` object has an attribute that is a string. 

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | latest |
| System | Ubuntu 18.04 |
| Browser | Firefox latest |

---
You can find a working demo of the bug here: https://codesandbox.io/s/wandering-firefly-vu2jq?fontsize=14

**Comment by afc163** [comment]
https://codesandbox.io/s/confident-haze-zzvb6

Try `normalize`.

**Comment by thisissami** [comment]
@afc163 thank you. Might I suggest that the documentation (in English) for `antd` `Form` be updated to express that `normalize` does this? there is currently zero indication it does this there. 

Adding a sentence like "You can use `normalize` to transform the value of an input for the `validateFields` function callback" to the documentation would make a big difference.

**Comment by thisissami** [comment]
Hi @afc163 & @chenshuai2144 - this doesn't actually work. see this example: https://codesandbox.io/embed/admiring-wilson-d90wi

`normalize` acts as soon as you switch from one field to another. it does not seem to work only when running `validateFields`. Is there any way to just transform the output of the fields as they are completed? 

When there are multiple numbers, anything that isn't a number automatically becomes `NaN` - not ok for an interface. Anything that is to be transformed into an object becomes `[object Object]` and is impossible to transform. this issue should be reopened.

**Comment by byzyk** [comment]
@thisissami hey! have you happened to find a workaround for this one?

**Comment by thisissami** [comment]
@byzyk within the `validateFields` function, I do my own manual transformation. 

However, this is clearly an issue with `antd` in my opinion. I assumed that my comment above would have gotten the team to re-open this issue. 

Would you be willing to open a new one with the team? My 2 code sandbox links that I've already created above should be sufficient to illustrate the issue (as would a link to this issue, so that they see the dialogue here).

**Comment by byzyk** [comment]
@thisissami thanks for getting back to me. I ended up making use of a combination of custom logic after validation passes and custom validator.

I don't think opening a new issue is a good idea since I'm pretty sure maintainers already working pretty hard and I don't wanna make their life more complicated while dealing with duplicate issues. Maybe the use case is quite rare and they've got something else to prioritize.

@afc163 can you confirm if this is a bug so maybe I'll try to scrap some time to pick it up?
