### ISSUE TITLE
How I create a horizontal table component？

### ISSUE THREAD

**Issue by LiuDuFenLi** [ant-design/ant-design#16726]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
many nees ues Horizontal table.
example:
<table>
<tbody>
<tr>
<th colspan="4">t1</th>
</tr>
<tr>
<th>t11</th>
<td>c11</td>
<th>t12</th>
<td>c12</td>
</tr>
<tr>
<th colspan="4">t2</th>
</tr>
<tr>
<th>t21</th>
<td>c21</td>
<th>t22</th>
<td>c22</td>
</tr>
</tbody>
</table>

### What does the proposed API look like?
I want:
1.support colspan incoming
const dataSource = [{
key: '1',
name: 't1',
colspan: 4,
}, {
key: '2',
name: 't2',
age: 4,
}];
const dataSource1 = [{
key: '1',
name: 't11',
}, {
key: '2',
name: 't12',
}, {
key: '3',
name: 't21',
}, {
key: '4',
name: 't22',
}];
If use children best.

Data:
const columns = [{
title: 'c11',
},{
title: 'c12',
},{
title: 'c21',
},{
title: 'c322',
}];

**Comment by afc163** [comment]
Trace #14645
