### ISSUE TITLE
className 污染

### ISSUE THREAD

**Issue by scarletsky** [ant-design/ant-design#1672]
## What actually happen
目前 antd 很多组件都有 ant-xxx 作为前缀，但有些常用的如 `row`, `col-xx` 之类的并没有带前缀。当我自定义了一些 `row` 的样式时，这时候就会出现冲突了。

希望 antd 所有组件的样式都保持一个规范的前/后缀，以免和用户自定义的样式冲突。

## Environment Information

- The version of antd(e.g. 0.12.0): 
1.0.1
- Your operating system and it's version(e.g. OSX 10.11.0):
OSX 10.11.4
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):
Chrome 50

**Comment by benjycui** [comment]
感觉这个是可以加上，毕竟 `Col` 和 `Row` 已经封装了，做这个修改用户应该是无感知的。

**Comment by afc163** [comment]
@ddcat1115

**Comment by imlida** [comment]
我也遇到了这个问题，希望能够改进。

**Comment by ddcat1115** [comment]
初步排查了一遍，目前有 `Col`  `Row`  `Icon`存在这个问题，稍后会fix掉

**Comment by afc163** [comment]
Icon 已经带了 `anticon` 这样的特殊前缀，不需要再加前缀了。

**Comment by ddcat1115** [comment]
好的~

**Comment by ddcat1115** [comment]
因为修改 className 会导致一些没有使用 Col、Row（直接使用 .col-xx） 的老项目样式不可用，本修改点会放在后续的大版本中完成。

**Comment by benjycui** [comment]
> 直接使用 .col-xx

这个在 0.10.x 后就不是推荐用法了，还需要考虑兼容么。。

主要是觉得 2.0 还有点远 😅 或者现在就可以修改了。

**Comment by ddcat1115** [comment]
恩，0.9版本的系统是很少了，但 `.col-xx` 这样用的应该还有一些，比如从0.9升上来的，因为这样用起来一直ok就没有改。。。。。主要还是感觉这种不兼容的写法还是应该在大版本中来做呢

**Comment by yiminghe** [comment]
1.2.0 可以做这个
