### ISSUE TITLE
Extending the Select component throws errors

### ISSUE THREAD

**Issue by prashantjain68** [ant-design/ant-design#16721]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/facebook/react-native/issues/16332](https://github.com/facebook/react-native/issues/16332)

### Steps to reproduce
import React, { Component } from 'react';
import { Select } from 'antd';

export default class FilterSelect extends Select {

}

### What is expected?
The FilterSelect component should work exactly as the Select component.

### What is actually happening?
Get an error:
Invariant Violation: Element type is invalid: expected a string( for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in.

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8 |
| System | Mac |
| Browser | Chrome |

---
Found this on stackoverflow:

https://github.com/facebook/react-native/issues/16332

**Comment by afc163** [comment]
Don't extend `Select`, compose it.

https://reactjs.org/docs/composition-vs-inheritance.html

**Comment by prashantjain68** [comment]
I tried extending the component and it didnt work. Thanks for the tip on composing it.

I do want to provide some feedback: I am new to React and new to antd. Having worked with a lot of UI frameworks including Adobe Flex, I have a lot of experience and a very strong background in component development ... the antd components are not very friendly for extending or for usage. The Select component creates a lot of private methods in the initialize props method with a reference to "this2" which is a completely different component than the original Select instance.

My suggestion to the team is ... dont try to encapsulate so much that the component becomes very rigid and consumers (developers) cannot mend and bend it the way they want. They will run away from this library. Keep the good work. Good luck.

**Comment by prashantjain68** [comment]
BTW, I applied an id attribute "<Select id='foo'/>" and the id was not rendered in the dom. Just pointing out one of the pain points I encountered.

My suggestion to the team is ... expose private methods (methods with underscore in the front) as public methods. You dont know how developers will consume it.
