### ISSUE TITLE
Input component add 'formatter' and 'parser' attribute

### ISSUE THREAD

**Issue by guoxin214** [ant-design/ant-design#16733]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I fount the InputNumber component has those two attribute, it's useful,  but the case in my project that input value not only number, so i must use Input, i think those attrbute can format the value to show better.

### What does the proposed API look like?
Input component has 'formatter' and 'parser' attribute
```javascript
<Input
     formatter={value => `${value}`.replace(/(\S{4})(?=\S)/g, "$1 ")}
     parser={value => value.replace(/\s/g, '')}
/>
```

**Comment by afc163** [comment]
We won't provide feature like this, you can customize Input to your own component.

**Comment by guoxin214** [comment]
> We won't provide feature like this, you can customize Input to your own component.

Customize Input become difficult when i use Form.Item.
