### ISSUE TITLE
setFieldsValue doesn't trigger any event on component

### ISSUE THREAD

**Issue by KrFeher** [ant-design/ant-design#16732]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Using setFieldsValue on a form item sets the value of the component correctly, but does not trigger any events (e.g. onChange, onSelect, etc) on the component.
Can we have setFieldsValue trigger an event on the component? Any event would do, as long as we can use that event to call further functions.

### What does the proposed API look like?
I'm not proficient enough to provide a solution.

**Comment by afc163** [comment]
It is intent behavior, just like `setState` don't trigger input's `onChange` event.

**Comment by KrFeher** [comment]
Thanks, how do we call further actions when something automatically changed then?
An example use case is:
- User enters a value in component 'A'
- component 'A' triggers a setFieldsValue on component 'B'
- component 'B' needs to change now component 'C'   (<--- this is the issue)

**Comment by afc163** [comment]
How do we solve this problem by `setState` in React? It is all the same, `setFieldsValue` is `setState` in form.

**Comment by KrFeher** [comment]
Thanks, I'm having a feeling that I maybe use setFieldsValue for the wrong purpose.

**Comment by ygmgbg** [comment]
> Thanks, how do we call further actions when something automatically changed then?
> An example use case is:
> 
> * User enters a value in component 'A'
> * component 'A' triggers a setFieldsValue on component 'B'
> * component 'B' needs to change now component 'C'   (<--- this is the issue)

@KrFeher ,in your example, how do you make 'B' trigger onChange event so 'C' can be updated?

**Comment by NorthwesternDirector** [comment]
> > Thanks, how do we call further actions when something automatically changed then?
> > An example use case is:
> > 
> > * User enters a value in component 'A'
> > * component 'A' triggers a setFieldsValue on component 'B'
> > * component 'B' needs to change now component 'C'   (<--- this is the issue)
> 
> @KrFeher ,in your example, how do you make 'B' trigger onChange event so 'C' can be updated?

用 getFieldValue() 监听B值的改变可以解决
