### ISSUE TITLE
English translation for Maintaining wiki documentation

### ISSUE THREAD

**Issue by hawthord** [ant-design/ant-design#16730]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The English documentation for the Ant Design Github wiki is nearly complete, except for the three pages listed under the Maintaining header. It would be very helpful for English-speaking developers looking to contribute to have a full set of documentation available. Thank you!

Ant Design GitHub Wiki:
https://github.com/ant-design/ant-design/wiki

Specific pages to be translated to English:
https://github.com/ant-design/ant-design/wiki/%E8%80%81%E7%89%88%E6%9C%AC%E5%92%8Cbeta%E7%89%88%E6%9C%AC%E6%96%87%E6%A1%A3%E5%8F%91%E5%B8%83%E6%B5%81%E7%A8%8B
https://github.com/ant-design/ant-design/wiki/%E8%AE%BE%E8%AE%A1%E6%96%87%E6%A1%A3%E4%B8%8A%E4%BC%A0%E6%B5%81%E7%A8%8B
https://github.com/ant-design/ant-design/wiki/%E8%BD%AE%E5%80%BC%E8%A7%84%E5%88%99%E5%92%8C%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E6%B5%81%E7%A8%8B

### What does the proposed API look like?
No API involved. This effects the GitHub documentation HTML only.

**Comment by afc163** [comment]
Those are some instructions only for core team who are all chinese. Feel free to translate it by Google and reply here, I will create English wiki from it.
