### ISSUE TITLE
Cascader displayRender doesn't capture some actions

### ISSUE THREAD

**Issue by KrFeher** [ant-design/ant-design#16738]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-sammet-4tfmc)

### Steps to reproduce
1. Create Cascader with displayRender
2. Add onMouseEnter or a Tooltip component within the render
3. Try to hover over the item.
4. Nothing happens
5. (onClick also doesn't work) 

### What is expected?
Hover expected to work as well as onClick

### What is actually happening?
Mouse hover doesn't work or mouse click on custom rendered item. 

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.9.0 |
| System | Windows 10 |
| Browser | Chrome Version 72.0.3626.121  |

**Comment by KrFeher** [comment]
It was once reported in 2018 for onClick not working. Apparently it was fixed, though it still doesn't work. 
https://github.com/ant-design/ant-design/issues/10433

**Comment by KrFeher** [comment]
Also that was about onClick. This is about hovering over mouse cursor.

**Comment by afc163** [comment]
Ehmm.. It was broken by https://github.com/ant-design/ant-design/pull/12407 again.

**Comment by KrFeher** [comment]
Thanks, is this going to be fixed?
