### ISSUE TITLE
initialValue在自定义hook组件中不能刷新问题

### ISSUE THREAD

**Issue by Cslove** [ant-design/ant-design#16736]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/infallible-buck-ykenk)

### Steps to reproduce
点击页面刷新

### What is expected?
hook组件中未获得期望的value值

### What is actually happening?
期望获得正确的值

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.3 |
| System | mac10.13.6 |
| Browser | chrome74 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14915#issuecomment-464991519
https://github.com/ant-design/ant-design/issues/15532
#5109
https://github.com/ant-design/ant-design/issues/10612
#15692
#15706
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by Cslove** [comment]
@afc163 initialValue is not going to change after first render, just like defaultValue.
为何上面重现链接中的自定义class组件可以二次刷新initialValue

**Comment by afc163** [comment]
You implement controlled comoponent of hooks in wrong way, check this one: https://codesandbox.io/embed/infallible-buck-ykenk

**Comment by Cslove** [comment]
thanks~
