### ISSUE TITLE
upload 缩略图图片内容显示不全模糊,这样会导致上传到文档服务器会是缩略图形式，正式预览时也会显示不全

### ISSUE THREAD

**Issue by chenzl0723** [ant-design/ant-design#16731]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
照片墙上传图片

### What is expected?
没有bug

### What is actually happening?
youbug

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome 70.0.3538.77 |

**Comment by ZhangXY-Magic** [comment]
我这边dev启动upload上传可完整显示预览图，build后部署服务器，上传图片被截取，并且模糊，长宽都是固定200*200px大小的预览图，上传到服务器图片正常

**Comment by chenzl0723** [comment]
好的，我在试一下



------------------ 原始邮件 ------------------
发件人: "ZhangXY-Magic"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 下午4:32
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "陈造龙"<849380131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design] upload 缩略图图片内容显示不全模糊,这样会导致上传到文档服务器会是缩略图形式，正式预览时也会显示不全 (#16731)




我这边dev启动upload上传可完整显示预览图，build后部署服务器，上传图片被截取，并且模糊，长宽都是固定200*200px大小的预览图，上传到服务器图片正常

**Comment by afc163** [comment]
预览和上传的图片不是一回事，我们不会对上传文件做特殊处理，请检查服务端逻辑。

**Comment by ZhangXY-Magic** [comment]
> 预览和上传的图片不是一回事，我们不会也没有对上传文件做特殊处理，请检查服务端逻辑。

但是预览的时候是会把图片截取，并且点击预览是模糊的图片，这个是bug

**Comment by chenzl0723** [comment]
好的，谢谢，你们这个bug会在什么时候可以修复？



------------------ 原始邮件 ------------------
发件人: "ZhangXY-Magic"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 下午5:18
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "陈造龙"<849380131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design] upload 缩略图图片内容显示不全模糊,这样会导致上传到文档服务器会是缩略图形式，正式预览时也会显示不全 (#16731)



 
预览和上传的图片不是一回事，我们不会也没有对上传文件做特殊处理，请检查服务端逻辑。
  
但是预览的时候是会把图片截取，并且点击预览是模糊的图片，这个是bug

**Comment by afc163** [comment]
现在有一个 `previewFile` 的属性可以自行定义预览图片的逻辑。

https://ant.design/components/upload-cn/#components-upload-demo-preview-file

**Comment by chenzl0723** [comment]
感谢




------------------ 原始邮件 ------------------
发件人: "偏右"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 下午5:22
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "陈造龙"<849380131@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design] upload 缩略图图片内容显示不全模糊,这样会导致上传到文档服务器会是缩略图形式，正式预览时也会显示不全 (#16731)




现在有一个 previewFile 的属性可以自行定义预览图片的逻辑。
 
https://ant.design/components/upload-cn/#components-upload-demo-preview-file

**Comment by afc163** [comment]
@zombieJ 这里截取的图片需要在 Modal 里展示，Modal 里的需要是完整的。

<img width="775" alt="image" src="https://user-images.githubusercontent.com/507615/58163327-68768280-7cb6-11e9-9d09-2a7b9d87e95c.png">

**Comment by ZhangXY-Magic** [comment]
> @zombieJ 这里截取的图片需要在 Modal 里展示，Modal 里的需要是完整的。
> 
> <img alt="image" width="775" src="https://user-images.githubusercontent.com/507615/58163327-68768280-7cb6-11e9-9d09-2a7b9d87e95c.png">
> 
> 我们可以在打开 Modal 的时候走完整的 read，这样不影响上传列表的性能。

谢谢大佬~麻烦问下这个时候时候会优化~

**Comment by zombieJ** [comment]
@afc163 做两份图片吧，preview 里如果用原图还是会遇到大尺寸下的性能问题。
