### ISSUE TITLE
当table使用fixed: 'right' 固定在右边时会出现1px空白线

### ISSUE THREAD

**Issue by hxyong** [ant-design/ant-design#16745]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
antd table 案列中的固定表头案列，当改变浏览器宽度使table 没有滚动条时，固定的action列的左侧会出现1px的白线

### What is expected?
不出现空白线

### What is actually happening?
出现

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 最新 |
| System | mac |
| Browser | 谷歌浏览器最新 |

---
使用固定列的时候改变浏览器宽度到table不出现横向滚动跳会出现这个问题

**Comment by afc163** [comment]
能否截个图

**Comment by hxyong** [comment]
![截图](https://user-images.githubusercontent.com/20831798/58236320-3d9f3380-7d75-11e9-9c46-58e0e63ffd7e.png)

**Comment by ouzhou** [comment]
借个楼

如果用了fixed right ， table组件加载的时候 如果鼠标正巧在列表上面，会有浅蓝色高亮，但是会先左边高亮 那块fixed的不会，但是如果鼠标移动了，就都正常了， 预期是都应该高亮才对

**Comment by kanweiwei** [comment]
@afc163  这个感觉不算个bug，这个的原因是受ant-col 栅格布局的影响，table外部的div宽度不是个整数的像素值，然后fixed right的部分是绝对定位且right：0px，就可能出现这个1px的白线。

**Comment by afc163** [comment]
@kanweiwei 和浏览器渲染机制也有一定的关系，确实找不到合适的解决方案，先关了。

**Comment by sinpor** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> https://ant.design/components/table-cn/
> 
> ### Steps to reproduce
> antd table 案列中的固定表头案列，当改变浏览器宽度使table 没有滚动条时，固定的action列的左侧会出现1px的白线
> 
> ### What is expected?
> 不出现空白线
> 
> ### What is actually happening?
> 出现
> 
> Environment	Info
> antd	3.18.2
> React	最新
> System	mac
> Browser	谷歌浏览器最新
> 使用固定列的时候改变浏览器宽度到table不出现横向滚动跳会出现这个问题

请问最终解决了吗?
我的版本是3.23.6，也出现这个问题了。
