### ISSUE TITLE
antd使用ES6语法部分组件报this.isMounted is not a function

### ISSUE THREAD

**Issue by jefybai** [ant-design/ant-design#1674]
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-is-mounted.md

**Comment by afc163** [comment]
麻烦提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by jefybai** [comment]
只有webpack的编译出的JS 会报出这个错误，
而在codepen上面直接写，
和在本地直接使用script标签引用antd类库，是没问题的？

**Comment by jefybai** [comment]
我只能告诉你antd.js的 45604行报的错误； 
在codeopen上面 确实没问题，我在本地直接引入antd类库也没问题；
只有webpack上面运行会报这个错 @afc163

**Comment by afc163** [comment]
具体是哪个组件呢，帮助我们缩小范围也行呢，这个信息我们排查到死也找不到呀...换位思考一下。

**Comment by afc163** [comment]
应该是这个问题：https://github.com/react-component/trigger/issues/9

**Comment by jefybai** [comment]
<Tree>
                <TreeNode className="first-level" title={
                    <div>
                        <span>什么是JAVA</span><span className="control">
                        <Tooltip placement="bottom" title="我是弹窗">
                            <span href="#">。。。</span>
                        </Tooltip>
                        <span>布置</span></span>
                    </div>
                    } key="1">
</Tree>
这样的结构，当鼠标放上去显示tooltip的时候会报出
Trigger.js:119 Uncaught TypeError: this.isMounted is not a function

但是只有在webpack上面才能复现，在codeopen上面是没问题的
@afc163

**Comment by jefybai** [comment]
```
<DropdownButton overlay={menu}  type="primary">
                        某功能按钮
            </DropdownButton>
``` @afc163 这个组件 一点开也不断的在报 this.isMounted is not a function

**Comment by jefybai** [comment]
你好，现在发现项目里面 只要是 弹出的 下拉的 比如说Select或者Tooltip弹出后，都会存在this.isMounted is not a function的问题。 版本是1.0开发环境是webpack。 但是codeopen上面或者使用<script>引入的js都不存在此问题。望提供解决方案 @benjycui

**Comment by afc163** [comment]
看上面的回复，在 rc-trigger 中等待修复中。

**Comment by yiminghe** [comment]
和 trigger 没关系，都是 React.createClass

**Comment by afc163** [comment]
和这个问题貌似一样：https://github.com/ant-design/ant-design/issues/1633 @warmhug

**Comment by jefybai** [comment]
https://github.com/ant-design/ant-design/issues/1633也是我提的，是没解决的问题；

**Comment by afc163** [comment]
务必帮助我们重现问题，否则无从下手。

**Comment by jefybai** [comment]
谢谢大家，也不知道到底是什么原因，最后我自己的代码拷出来，然后重新install了一下所有的包，问题就没了
