### ISSUE TITLE
面包屑组件当routes长度为1时不展示问题

### ISSUE THREAD

**Issue by perany** [ant-design/ant-design#16746]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求：现在面包屑长度为1时默认不展示面包屑，能否增加参数控制当长度为1时也能展示面包屑？

相关代码：
``` 
const routes = [{
    breadcrumbName: '应用查询'，
    path: "/app/query"
  }];
 <PageHeader title="应用查询"  breadcrumb={{routes}} >
     应用查询页面内容
 </PageHeader >
```
### What does the proposed API look like?
面包屑组件当routes长度为1时也能展示，可以接受默认是2个以上才展示，可通过参数手动控制。

**Comment by zombieJ** [comment]
太定制化了，你直接包一个 HOC 来处理吧~
```jsx
const MyHeader = ({ breadcrumb, ...props }) => (
  <PageHeader breadcrumb={breadcrumb.length > 1 : breadcrumb : null} {...props} / >
);
```
