### ISSUE TITLE
how can i implement auto focus and open after selecting? thanks

### ISSUE THREAD

**Issue by justinlazaro-ubidy** [ant-design/ant-design#16758]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/red-sky-q0051)

### Steps to reproduce
https://codesandbox.io/s/red-sky-q0051

### What is expected?
https://codesandbox.io/s/red-sky-q0051

### What is actually happening?
https://codesandbox.io/s/red-sky-q0051

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.1 |
| System | windows |
| Browser | chrome |

---
Good day, how can i implement auto open and focus after selecting one of the data?

scenario: after i select gender, another step or selection must be focus and open.

in my codesandbox example, i already implement that, but the problem i can't select and open again the selections

**Comment by zombieJ** [comment]
Could you help to provide more description? What component get auto focus and what's `after selecting`?

**Comment by yakkantiraja** [comment]
can i try 
showAction={['focus', 'click']}

https://codesandbox.io/s/auto-focus-and-scroll-pknos

**Comment by justinlazaro-ubidy** [comment]
@zombieJ done, and please check my sandbox

**Comment by justinlazaro-ubidy** [comment]
@yakkantiraja thanks, but there's a problem we can't select again the selection

**Comment by justinlazaro-ubidy** [comment]
got my solution here
@yakkantiraja thanks for the idea of showAction

https://codesandbox.io/s/auto-focus-and-scroll-final-hkreq

**Comment by afc163** [comment]
https://codesandbox.io/s/auto-focus-and-scroll-whz2d
