### ISSUE TITLE
iphone6 safari下，menu组件点击切换需要点两次才能切换选中项

### ISSUE THREAD

**Issue by sornon** [ant-design/ant-design#1675]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。

If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

在iphone6上，点击menu组件，想要切换不同menu.item

## What you would like to happen
应该跟pc端效果一致，点击立即切换到所点的menu上，并高亮显示

## What actually happened

但实际上点击后没反应，需要再点击一次才能高亮

## Online demo
使用iphone访问http://ant.design/#/components/menu
并点击menu切换选中项

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(IOS9.3.1):
- Your browser and it's version(e.g. safari):

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1578
