### ISSUE TITLE
Why can't I automatically select the first option in select

### ISSUE THREAD

**Issue by meitingshuoguo** [ant-design/ant-design#16751]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-lederberg-38igz)

### Steps to reproduce
Please see the link I provided.

### What is expected?
I just want select to select the first option by default, just like the native select component.

### What is actually happening?
The first option cannot be selected by default. And I don't know why the value set by the notFoundContent property is not displayed by default. Is my usage correct? If it is correct, why not select it by default, but need to click to see it.

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.9.0 |
| System | win10 10.0.17134  |
| Browser | chrome 74.0.3729.169（64 位） |

---
I hope that regardless of whether the option is asynchronous or synchronous, the default selection should always be in effect.

**Comment by zombieJ** [comment]
You can use `defaultValue` to set it.

**Comment by meitingshuoguo** [comment]
> You can use `defaultValue` to set it.

I don't think you have a good look at what I wrote. I am talking about automatic settings, just like the native select component! ! I know to use defaultValue, but if I can only set it this way, it would be too stupid. Why can't I load the first one by default like a native component? I don't know the value of the first option at any time, then set it. defaultValue. This feature should be preserved, giving the component some flexibility, rather than having to actively set it up for anything, which is stupid.

**Comment by afc163** [comment]
We don't design our component exact same as native controls.

**Comment by afc163** [comment]
> And I don't know why the value set by the notFoundContent property is not displayed by default. Is my usage correct?

You may need `placeholder` rather then `notFoundContent`.

**Comment by michakfromparis** [comment]
Having an option to select the first entry by default (especially when the options are set dynamically and there is only one) would still make sense to me.

**Comment by Maikel-Nait** [comment]
> Having an option to select the first entry by default (especially when the options are set dynamically and there is only one) would still make sense to me.

I have exactly the same issue... using defaultValue does not work in my situation. No other solution for this ?

**Comment by rahulkasana** [comment]
You can overcome this by using form @Maikel-Nait and @michakfromparis .

```
const options = this.state.suggestions.map((d) => (
      <Option key={d} value={String(d)}>
        {d}
      </Option>
    ));

<Form.Item
                  name="name"
                  label="Name"
                  rules={[{required: true, message: 'Name is required'}]}>
                  <Select
                    showSearch
                    style={{width: '100%'}}
                    placeholder="Enter Name"
                    onBlur={this.onBlur('name')}
                    defaultActiveFirstOption={true}
                    filterOption={false}
                    onSearch={this.handleSearch}
                    notFoundContent={null}>
                    {options}
                  </Select>
                </Form.Item>

onBlur = (key) => () => {
    const {suggestions, nickNames} = this.state;
    this.formRef.current.setFieldsValue({
      nick_name: nickNames[0],
      name: suggestions[0],
    });
  };

```
where the options are stored in state so that they are not lost. Setting the form onBlur function updates the Select with the first option available. Hope this helps.

**Comment by jideabdqudus** [comment]
Can anyone provide a solution for this issue? It's important with dynamic options, when you're mapping the select option and want the first item to be preselected.

**Comment by gitRacoon** [comment]
You should use `defaultActiveFirstOption` in `Select`.
Example: 
```
<Select
      defaultActiveFirstOption
    >
      {optionList.map((option) => (
        <Select.Option key={option.id} value={option.id}>
          {option.name}
        </Select.Option>
      ))}
    </Select>
```

**Comment by shivam-bit** [comment]
For me  this worked 
```
<template>
     <a-select
           style="width: 90px"
           :options="options"
           labelInValue
           :defaultValue="{ key: 'lucy' }"
    ></a-select>
</template>
<script>
export default {
  data(){
    return {
      options: [
              { value: 'jack', label: 'Jack' },
              { value: 'lucy', label: 'Lucy' },
            ]
  }
}
</script>

```

**Comment by dryleaf** [comment]
Not the official solution, but setting:
```
defaultActiveFirstOption={true}
filterOption={true}
```
- seems to work for me.
