### ISSUE TITLE
feat: add Latvian localization

### ISSUE THREAD

**Issue by kirbo** [ant-design/ant-design#16752]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Adding localization for Latvian

### What does the proposed API look like?
Localizations

**Comment by zombieJ** [comment]
PR is welcome : )

**Comment by kirbo** [comment]
@zombieJ This is pretty much done already, I just haven't pushed anything just yet, because I'm waiting my PRs' in rc-calendar and rc-pagination to be merged first. :)

**Comment by zombieJ** [comment]
@kirbo Thanks for notice. Merged `rc-calendar` & `rc-pagination` : )

**Comment by kirbo** [comment]
Pull request for this issue: https://github.com/ant-design/ant-design/pull/16780

**Comment by kirbo** [comment]
Now I could use help with that PR, since I'm not sure what should I do/whats wrong
https://github.com/ant-design/ant-design/pull/16780
