### ISSUE TITLE
table tree pagination bug

### ISSUE THREAD

**Issue by FightingJane** [ant-design/ant-design#16759]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4x6kqvy5p7)

### Steps to reproduce
expand the tree, click the "添加子树"button, then click page 2.  back to page 1

### What is expected?
expanded datas should not  show in page 2 and page 1

### What is actually happening?
expanded datas should not  show in page 2 and page 1

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.9.0 |
| System | win7 |
| Browser | chrome |

---
需要动态获取tree 的children

**Comment by zombieJ** [comment]
1. You do better create a new array to set as `dataSource` instead of change origin one.
2. number key will be convert to string so `11` is same as `'11'`

https://codesandbox.io/s/antd-table-7bn95
