### ISSUE TITLE
message 使用getContainer无效

### ISSUE THREAD

**Issue by smz8023** [ant-design/ant-design#16754]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7y4o2y3yr6)

### Steps to reproduce
https://codesandbox.io/s/7y4o2y3yr6

### What is expected?
可以自定义渲染节点

### What is actually happening?
始终渲染在body节点下

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8 |
| System | windows |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
使用 `getContainer` 设置容器。
