### ISSUE TITLE
Cascader: Scroller inside options not scrolling when using up/down arrow keys

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#16767]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/throbbing-cdn-hteg1)

### Steps to reproduce
When there are lot of options in the cascader list, automatically scroller will be enabled. Where user can scroll with mouse and choose options.

### What is expected?
When we use up/down arrow keys to navigate through options scroll bar should move accordingly

### What is actually happening?
scroll bar not miving with up/down arrow keys but focus is going beyond the visible options and showing the sub options

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | any |
| System | any |
| Browser | Any |

**Comment by afc163** [comment]
trace #24173
