### ISSUE TITLE
Cascader: Enable cursor/searching as soon as component gets focus through Tabbing

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#16765]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/long-surf-24z5qk)

### Steps to reproduce
When there are multiple components in the form , click TabKey to shift focus from one component to another component.
Cascader gets the focus but user has to click inside the cascader using mouse to start the search

### What is expected?
Cascader searching should be enable to search as soon as gets the focus

### What is actually happening?
User has to click manually to start searching

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | any |
| System | any |
| Browser | Any |

**Comment by shadab14meb346** [comment]
I would like to work on this issue.

**Comment by shadab14meb346** [comment]
The codesandbox demo [link](https://codesandbox.io/s/flamboyant-antonelli-5mlzz) shows it works.
When I click on the "Tab" key the focus shifts from one `Cascader` to another.
So I not exactly clear what needs to be done here?
![Untitled_ May 24, 2021 6_07 PM](https://user-images.githubusercontent.com/31199288/119348951-245e5400-bcbb-11eb-91ed-88f407cf7684.gif)

**Comment by zombieJ** [comment]
No an issue in v5. closed

https://codesandbox.io/s/long-surf-24z5qk?file=/index.js
