### ISSUE TITLE
Cascader: User has to press down arrow key twice to select the first option while searching

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#16762]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yq9pj460rx)

### Steps to reproduce
When searching in the cascader, to select item using key board user has to press the down arrow key twice to focus the list item.

Is there any option to select the first item by default when searching ?
Something like defaultActiveFirstOption ?

https://codesandbox.io/s/yq9pj460rx

### What is expected?
After entering search if user click down arrow the first option should select 

### What is actually happening?
After entering search  user has to click down arrow twice to select the first option 

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | any |
| System | Any |
| Browser | Any |

**Comment by yakkantiraja** [comment]
can it be added to patch release?

**Comment by Kermit-Xuan** [comment]
I will work it.
