### ISSUE TITLE
表格行合并  表格分页

### ISSUE THREAD

**Issue by gitchong** [ant-design/ant-design#16768]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http:xxx.com](http:xxx.com)

### Steps to reproduce
1、使用table 表格组件
2、使用表格行/列合并
3、一个表格中有13行数据，自动分为2页
4、第一列数据设置了多行合并
5、第一页都显示正常，第二页格式就不对了

### What is expected?
第二页和第一页效果相同，首列多行合并格式延续

### What is actually happening?
第二页表格和第一页表格格式不一样，表格合并乱了

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | react |
| System | window |
| Browser | chrome |

**Comment by gitchong** [comment]
https://codesandbox.io/s/antd-reproduction-template-yzcil?fontsize=14

**Comment by huntdream** [comment]
index并不会跟随页码递增，每次切换页index都是从0开始的
![image](https://user-images.githubusercontent.com/7903755/58746641-fd396700-8492-11e9-8613-76c1daeebfb4.png)
所以你应该结合页码去计算

**Comment by gitchong** [comment]
thank you very much!
