### ISSUE TITLE
message组件可以提供消息自动关闭后的回调？

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#1676]
我把一个全局消息内容放到了redux store里，有消息时我就用message组件提示，message消失后清理这个消息。但是message组件无回调，这个消息并不好清理。

**Comment by afc163** [comment]
`message.destroy()`

**Comment by codering** [comment]
好吧。。。看了源码，原来有onClose的回调  ```  info: function info(content, duration, onClose) ```
为啥文档没写？

**Comment by afc163** [comment]
可以 pr 一个补上~
