### ISSUE TITLE
table组件的onChange方法，无法区分具体是由分页还是排序还是筛选触发的

### ISSUE THREAD

**Issue by myadomin** [ant-design/ant-design#16760]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如点击筛选触发onChange后，我期望table的当前页码回到第一页。现在无法区分onChange具体是分页还是排序还是筛选触发的，这个需求完成不了

### What does the proposed API look like?
期望table组件的onChange方法，可以区分具体是由分页还是排序还是筛选触发的

**Comment by zombieJ** [comment]
https://codesandbox.io/s/adoring-hofstadter-jsxix
