### ISSUE TITLE
Typography.Paragraph组件的复制功能，复制的文字如果有换行在部分情况下（如微信）会失去换行效果

### ISSUE THREAD

**Issue by chaoyuwang** [ant-design/ant-design#16770]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[使用Typography.Paragraph复制有换行的文字（使用\r\n），在微信聊天面板复制该文字后换行功能消失。经查Typography组件的复制功能使用了copy-to-clipboard，而此插件粘贴的内容是放在span元素标签里面，会过滤掉"\r"。目前是直接找到copy-to-clipboard文件将span元素修改成pre。但这种方式缺点明显不足，或者复制一份copy-to-clipboard再对其进行修改，但这种方式又比较繁琐。想请问有没有更完美的实现方式。（[react-copy-to-clipboard数据复制显示问题](https://blog.csdn.net/qq_25152555/article/details/80737884)）

### What does the proposed API look like?
希望可以增加一个改变span元素的API方便修改换行时的问题

**Comment by zombieJ** [comment]
`copyable` 支持 `text` 属性，你可以直接设置需要复制的内容。
参考一下这个替换复制内容的例子：https://ant.design/components/typography-cn/#components-typography-demo-interactive

**Comment by chaoyuwang** [comment]
使用的就是 `copyable` 的 `text` 属性，现在是在该属性内使用\r\n换行，但是复制的内容在微信聊天窗口内并没有换行。目前是直接修改copy-to-clipboard文件的 `span` 元素为 `pre`。想了解有没有更合适的方法。[https://codesandbox.io/s/strange-wilbur-i7t1o](https://codesandbox.io/s/strange-wilbur-i7t1o)
![copyline](https://user-images.githubusercontent.com/20468376/58312798-a1416380-7e3e-11e9-9dcc-b44a4f56bf6c.png)

**Comment by zombieJ** [comment]
明白你的意思，方便给 `copy-to-clipboard` 开个 issue 吗？它没有暴露设置元素的接口，这边也做不了什么。

**Comment by chaoyuwang** [comment]
试了一下 `clipboard.js` [https://github.com/zenorocha/clipboard.js](https://github.com/zenorocha/clipboard.js) 可以解决目前问题。官方是否考虑 将 `copy-to-clipboard` 更换为 `clipboard`

**Comment by zombieJ** [comment]
愿意发个 PR 吗？
