### ISSUE TITLE
select 使用onSearch，onBlur的时候会再次触发onSearch返回空字符串

### ISSUE THREAD

**Issue by z784324922** [ant-design/ant-design#16771]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/bda8f915](https://riddle.alibaba-inc.com/riddles/bda8f915)

### Steps to reproduce
输入任意字符串，点击屏幕其他位置

### What is expected?
onBlur时候不应该触发onSearch，这样导致之前输入的内容被置空

### What is actually happening?
输入一段文字，点击屏幕位置，拿到空字符串。

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 15.6.2 |
| System | macOS10.14.4 |
| Browser | Chrome 74.0.3729.169（正式版本） （64 位） |

---
用户输入一串文字，然后点击一个button进行搜索。但是由于鼠标点击其他位置，导致onSearch的触发，并且返回的是空字符串，导致搜索内容为空。以前是正常的，应该是最近版本升级导致的。

**Comment by zombieJ** [comment]
以前不触发是 BUG，search 框更新的时候总是应该触发 `onSearch` 事件。因为它是事实清空了。
ref #16223

**Comment by z784324922** [comment]
哦，那意思是现在输入框搜索过后，还必须去手动点击下拉框，然后再点击搜索。这样不是多一步操作吗，不知道的用户还以为搜索用不了。触发onSearch能理解，为什么要清空呢，这难道不是bug吗？

**Comment by zombieJ** [comment]
Select 不同于 AutoComplete，Select 在非交互状态下是稳定的，搜索值如果保留会让人以为 Select 的值为搜索的值。

另外，`输入框搜索过后，还必须去手动点击下拉框，然后再点击搜索` 这个不太明白。选择值以后为何还要在点击搜索？

**Comment by z784324922** [comment]
![image](https://user-images.githubusercontent.com/31068244/58316012-347d9780-7e45-11e9-9687-05bdd6e1cb51.png)
搜索框是这样子的，我想实现的效果类似百度的搜索，可以从提示的列表里面选，也能输入任意内容，点击查询。之前输入的内容是能保存下来，现在鼠标一离开就返回空字符串，导致查询也是空字符串。现在只有通过触发onChange事件（点击下拉框中的某一项，或者敲回车），才能把输入内容持久化

**Comment by z784324922** [comment]
还有个问题，就是如果搜索内容不在下拉列表。无法将输入内容保存下来，因为鼠标一点其他位置就清空了。

**Comment by afc163** [comment]
你应该选用 AutoComplete 而不是 Select。

**Comment by z784324922** [comment]
@afc163 好的，我试试

**Comment by zsl1549** [comment]
@afc163  AutoComplete  谢谢可以使用！

**Comment by nmsn** [comment]
@afc163  如果我在 Modal 中 有一个 Select 且绑定了 onSearch 去查询接口，这种情况下，我在 Select 输入内容后直接点击 Modal 的关闭，会在关闭 Modal 同时 Select 失去焦点调用一次接口，这种情况如何避免
