### ISSUE TITLE
关于组建的建议

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#1677]
富文本编辑器虽然可以用draft但还需要学习，建议封装个富文本编辑器，另外最好再增加筛选器组件http://uxco.re/components/pickable/  及  http://uxco.re/components/mention/ 组件 这样就非常全了。

**Comment by benjycui** [comment]
Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/1083

**Comment by yuweilan** [comment]
uxcore的编辑器好像很好用,正在找适配ant比较好的富文本编辑器
