### ISSUE TITLE
Allow Form.getFieldDecorator.options.validateTrigger accept "false" which means don't validate until Form Submit

### ISSUE THREAD

**Issue by Stephen2** [ant-design/ant-design#16785]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Right now, I have a field that has validaton rules.

BUT I only want the error message to show/field to validate on Form Submit.  Not on Change or on Blur.

To achieve this, I have hacked `validateTrigger={false}` which I think is a good API for this, but it's technically outside of the `string | string[]` properties that are accepted.

### What does the proposed API look like?
`validateTrigger={false}` OR `validateTrigger={null}`

**Comment by zombieJ** [comment]
Maybe `onSubmit` is much meaningful ?

**Comment by Stephen2** [comment]
That sounds great

**Comment by Stephen2** [comment]
Please remove `inactive` label, and consider making this enhancement

**Comment by zombieJ** [comment]
Hi @Stephen2 , thanks for notice.
This feature realized in v4 as feature. Welcome to help on test this.

Merge into #16911

**Comment by Stephen2** [comment]
Thanks you @zombieJ :)
