### ISSUE TITLE
Clicking the button inside a Popover at the first time opening the Popover will close it when using <div> as a trigger

### ISSUE THREAD

**Issue by Otocolobus-manul** [ant-design/ant-design#16788]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pbrwc)

### Steps to reproduce
1. Refresh the page.
2. Click 'Click me'.
3. Click 'Then click here'.

### What is expected?
Popover should keep open.

### What is actually happening?
Popover closed.

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 74.0.3729.169 |

**Comment by Veveue** [comment]
[注](https://ant.design/components/popconfirm-cn/#%E6%B3%A8%E6%84%8F)
[demo](https://codesandbox.io/s/antd-reproduction-template-l34ff)

**Comment by zombieJ** [comment]
Very strange... Bubble event sequence is not correct on the first render. Should deep check why...

**Comment by Veveue** [comment]
@afc163 it's not a bug

**Comment by zombieJ** [comment]
@Veveue , could you provide more info about why it's not a bug?

**Comment by Veveue** [comment]
@zombieJ https://codesandbox.io/s/antd-reproduction-template-l34ff

**Comment by zombieJ** [comment]
Get it. Not pass mousedown 👍

**Comment by SunPeter** [comment]
### another case from [ant.design](https://ant.design/components/popover-cn/)
````
class App extends React.Component {
  state = {
    visible: false
  };

  hide = () => {
    this.setState({
      visible: false
    });
  };

  handleVisibleChange = visible => {
    this.setState({ visible });
  };

  render() {
    return (
      <Popover
        content={
          <div>
            <input type="text" />
            <a onClick={this.hide}>Close</a>
          </div>
        }
        title="Title"
        trigger="click"
        visible={this.state.visible}
        onVisibleChange={this.handleVisibleChange}
      >
        <Button type="primary">Click me</Button>
      </Popover>
    );
  }
````

### fix: use element to wrap Button
````
<span>
       <Button type="primary">Click me</Button>
</span>
````
