### ISSUE TITLE
Menu Hover Indicator

### ISSUE THREAD

**Issue by Nghtly** [ant-design/ant-design#16784]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The default indication for hover on a Menu Item is displayed on the bottom of the Menu Item, on the Antd website however, the hover indicator is displayed on the top. The option to choose where this indicator is displayed would be nice.

### What does the proposed API look like?
 A prop which could be used to control wether this is shown on the bottom or bottom of the Menu Item.

**Comment by afc163** [comment]
We may not provide this feature because we follow design spec in this way, and the menu in antd website is a whole new story though.
