### ISSUE TITLE
图标和样式要更改及后台交互问题

### ISSUE THREAD

**Issue by ksh033** [ant-design/ant-design#1678]
1.请问我本地项目中样式使用编译

      @import "~antd/lib/style/themes/default.less";
      @import "custom.less";
      @import "~antd/lib/style/core/index.less";
      @import "~antd/lib/style/components.less";
     那我是不是要把下面的这句话去除，不然会有两份的antd样式？
     webpackConfig.babel.plugins.push(['antd', {
         style: 'css' // if true, use less
        }]);
2.项目中自定义图标应用到Icon组件
   如果我需要一些项目中的自己定义的图标应用到Icon组件，我需要怎么做
    用上面那种方式iconfont-url地址改变，那所有组件的图标就会全部变了。
3.前后交互问题
   另外请教一下现在的组件跟后台交互的方式有是怎么交互的。控件都不提供远程的方式我开发的时候需        要怎么做呢

**Comment by benjycui** [comment]
可以稍微整理下排版么。。。

**Comment by afc163** [comment]
对，如果自定义加载了 less，就不要开启 babel-plugn-antd 的 style 属性，自行负责样式加载就好。

**Comment by afc163** [comment]
2. 单独另外搞一套图标并行使用。

**Comment by afc163** [comment]
三、建议自行探索相关 reflux/redux/relay 方案。

**Comment by ksh033** [comment]
@benjycuig
不好意思，下次我会注意排版的，我都是把问题列在txt文件拷过来的。没注意
