### ISSUE TITLE
Empty option for select not showing properly

### ISSUE THREAD

**Issue by MhdTlb** [ant-design/ant-design#16783]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-gqqmv)

### Steps to reproduce
- Create a dropdown using Select component
- Add multiple options with non empty text
- Add an option with empty text  

### What is expected?
the height of the empty option is the same as non-empty options

### What is actually happening?
the height of the empty option is very small and hard to select 

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.4 |
| System | windows 10 |
| Browser | Chrome 73 |

**Comment by keithort** [comment]
Instead of using `{" "}`, use `&nbsp;` and it will show the empty option at the correct height.

**Comment by MhdTlb** [comment]
Thank you @keithort  that works
