### ISSUE TITLE
Tabs Vertical Cards are not scrollable

### ISSUE THREAD

**Issue by KROT47** [ant-design/ant-design#16792]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/epic-hellman-xxcwh)

### Steps to reproduce
Just switch between `Line` and `Card`

### What is expected?
Scroll must be in both cases

### What is actually happening?
Scroll disappears

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | react |
| System | any |
| Browser | Chrome |

---
This can be fixed with:
```
.ant-tabs-vertical.ant-tabs-card {
    .ant-tabs-nav-container {
        height: 100% !important;
    }
}
```

**Comment by zombieJ** [comment]
Card Tabs not providing scroll is by design. Since when use card tab, it should be seems more like an entirety.

**Comment by KROT47** [comment]
I don't understand what you are saying.
First of all, if it is by design then why horizontal scroll is working?
And what entirety are you talking about? You really think that it is ok when tabs can not be accessed and even seen if height of component is not enough?

**Comment by zombieJ** [comment]
Reasonable. Let me reopen this.

**Comment by KROT47** [comment]
Thanks
GL HF :)
