### ISSUE TITLE
FieldsArray component for forms

### ISSUE THREAD

**Issue by AhmedSayed77** [ant-design/ant-design#16791]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This is not actually a feature request, I've already implemented the fields array component for antd's form.
Here's a [link for a sandbox where the component is implemented as a React class](https://codesandbox.io/s/antd-reproduction-template-19g12).
And here's [another box where it's implemented as a function component and uses hook]( https://codesandbox.io/s/antd-reproduction-template-v640j)

Now, I can migrate the code to typescript - I'll probably need help to do this - write tests, and make a pull request to rc-form, and you can make it part of the official antd package, or I can publish it as a third party library - I'll need to migrate to typescript or flow to add typing - and then I'd ask you to mention it in the documentation

What do you prefer?

P.S. Any one is welcomed to just copy and paste the code in his work, until it's published somehow
P.S. 2 Any feedback is appreciated

### What does the proposed API look like?
Something similar to [formik's field array](https://jaredpalmer.com/formik/docs/api/fieldarray) or [react-final-form-array](https://github.com/final-form/react-final-form-arrays)

**Comment by zombieJ** [comment]
We have plan to optimize the form component. Array of fields is one of the plan. Maybe you can hold and wait for our official support : )

related issue: #16404

**Comment by AhmedSayed77** [comment]
That's good news. Thanks a lot for your work. Any news when this will be released?

**Comment by zombieJ** [comment]
You can trace [this pr](https://github.com/react-component/form/pull/292). Not have a promise time since we are focus on the performance first. API may adjust with final release.

**Comment by AhmedSayed77** [comment]
Thank you very much
