### ISSUE TITLE
Select组件多选模式下应该以label为匹配过滤

### ISSUE THREAD

**Issue by attacking** [ant-design/ant-design#16795]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前的select组件多选模式下，当使用输入过滤功能时，用户输入的文本过滤出来的是选项中value和文本匹配的选项，而不是去匹配用户看到的label，这个交互很不符合用户的使用场景（当然组件提供了filterOption属性来改变这一行为）。
[示例](https://codepen.io/yummy/pen/gJGaje)

### What does the proposed API look like?
希望默认是以label来过滤select的选项。

**Comment by afc163** [comment]
label 可能是 ReactNode，默认的话会有问题，还是保持现有行为较妥。
