### ISSUE TITLE
How can i open date picker by ref.focus()

### ISSUE THREAD

**Issue by juztinlazaro** [ant-design/ant-design#16806]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/auto-focus-and-scroll-final-hkreq)

### Steps to reproduce
https://codesandbox.io/s/auto-focus-and-scroll-final-hkreq

### What is expected?
https://codesandbox.io/s/auto-focus-and-scroll-final-hkreq

### What is actually happening?
https://codesandbox.io/s/auto-focus-and-scroll-final-hkreq

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.8.1 |
| System | windows |
| Browser | chrome |

---
How can i open date picker by using ref.focus()? 
please check my codesandbox thanks

**Comment by afc163** [comment]
Try `open` prop: https://ant.design/components/date-picker/#components-date-picker-demo-start-end

**Comment by justinlazaro-ubidy** [comment]
@afc163 thanks po.
