### ISSUE TITLE
Typescript error

### ISSUE THREAD

**Issue by HsuTing** [ant-design/ant-design#16805]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Just install and run typescript.

### What is expected?
No error.

### What is actually happening?
```sh
node_modules/antd/lib/mentions/index.d.ts:25:51 - error TS2307: Cannot find module '_rc-mentions@0.3.1@rc-mentions/lib/Option'.

25     static Option: React.FunctionComponent<import("_rc-mentions@0.3.1@rc-mentions/lib/Option").OptionProps>;
                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/antd/lib/mentions/index.d.ts:34:50 - error TS2307: Cannot find module '_rc-mentions@0.3.1@rc-mentions/lib/util'.

34     getFilterOption: () => false | typeof import("_rc-mentions@0.3.1@rc-mentions/lib/util").filterOption | undefined;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/antd/lib/slider/index.d.ts:2:22 - error TS7016: Could not find a declaration file for module 'rc-slider/lib/Slider'. '/Users/hsuting/Desktop/work/meep-lerna/node_modules/rc-slider/lib/Slider.js' implicitly has an 'any' type.
  Try `npm install @types/rc-slider` if it exists or add a new declaration (.d.ts) file containing `declare module 'rc-slider/lib/Slider';`

2 import RcSlider from 'rc-slider/lib/Slider';
```

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.8.6 |
| System | Mac os 10.14.4 |
| Browser | Chrome 74.0.3729.157 |

**Comment by afc163** [comment]
Any reproduce?

**Comment by HsuTing** [comment]
@afc163 
https://github.com/HsuTing/antd-issue
Because `codesandbox` can not run `tsc`, I make a repo for this issue.

**Comment by Grewer** [comment]
I also have the same problem

**Comment by zombieJ** [comment]
Will patch to fix this.

**Comment by Minoyu** [comment]
I also found the same problem

**Comment by GarvenZhang** [comment]
![image](https://user-images.githubusercontent.com/20942047/61365785-e45a0900-a8ba-11e9-89b1-42b88759f446.png)

so???
what the hell is that?? some bug with antd??
debuged a whole afternoon but nothing to work

**Comment by zombieJ** [comment]
@GarvenZhang, could you help to create a mini repo for reproduce?

**Comment by Jarvvski** [comment]
@zombieJ I have the above issue too

I've quickly setup https://github.com/Jarvvski/rc-mention-break without most of my source code and just left the config files in to save my own time :)

`npm run dev` produces the error for me.

To 'stop' the error, just comment out lines in the `Page.tsx` component as such:

```
import React, { useEffect } from "react";
// import { notification } from "antd";

const openNotificationWithIcon = type => {
    // notification[type]({
    //     message: "Ant Design is working"
    // });
};

...
```

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/61596460-a7816f80-ac36-11e9-8f3e-9e11621a5c9f.png)
@JackieLs   I did what you said but did not produce an error.

**Comment by Jarvvski** [comment]
@ztplz interesting. Which version of Node are you using?

I’m on LTS 10.X

**Comment by ztplz** [comment]
@Jarvvski  My node version is `11.9`.
![image](https://user-images.githubusercontent.com/17755202/61708976-ba07c000-ad80-11e9-9574-edbb98fb2816.png)

**Comment by yifeikong** [comment]
```
ERROR in /Users/xxx/repos/xxx/node_modules/rc-mentions/lib/util.d.ts
[tsl] ERROR in /Users/xxx/repos/xxx/node_modules/rc-mentions/lib/util.d.ts(4,55)
      TS1110: Type expected.
```

**Comment by JoseyDon** [comment]
typescript  version: "2.1.5",
![image](https://user-images.githubusercontent.com/22424758/64433039-47fcf780-d0f0-11e9-85cc-c2e117876a94.png)
when I use import {Select} from ‘antd’

**Comment by e2o** [comment]
I'm having the same issue since upgrading from `antd@3.9.0` to `antd@3.23.3`.
(with `typescript@2.6.2`).

**Comment by e2o** [comment]
Update: Resolved by upgrading to `typescript@3.6.3`.

**Comment by MFullStack** [comment]
> ```
> ERROR in /Users/xxx/repos/xxx/node_modules/rc-mentions/lib/util.d.ts
> [tsl] ERROR in /Users/xxx/repos/xxx/node_modules/rc-mentions/lib/util.d.ts(4,55)
>       TS1110: Type expected.
> ```
> 
> This happens when I use `import {Layout} from 'antd';`

do you resolve the problem?  I also meet the problem
when i use with import Pagination from 'antd/es/pagination'; it can build success.
but when i use with import { Pagination } from 'antd';
it will build error , error message like @JoseyDon

**Comment by Genarito** [comment]
Updating Typescript fixed the issue for me
