### ISSUE TITLE
希望能够提供离线文档或者国内站点

### ISSUE THREAD

**Issue by nic329** [ant-design/ant-design#16802]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在使用过程中经常需要查阅文档，但是目前只有在线文档，国内时常访问不进去，使用特殊手段速度一点点迟钝

### What does the proposed API look like?
离线文档或国内站点的在线文档。谢谢你们！

**Comment by imhele** [comment]
国内镜像  https://ant-design.gitee.io/

**Comment by nic329** [comment]
> 国内镜像 https://ant-design.gitee.io/

thanks

**Comment by xrkffgg** [comment]
ant-design 国内镜像地址：https://github.com/ant-design/ant-design/issues/25661
