### ISSUE TITLE
Button icon 颜色显示不对 如下图

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design#16811]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/eaKNVO?editors=0011](https://codepen.io/anon/pen/eaKNVO?editors=0011)

### Steps to reproduce
https://codepen.io/anon/pen/eaKNVO?editors=0011

### What is expected?
和 https://ant.design/components/button-cn/ 第二板块一样

### What is actually happening?
具体看codepen的显示

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | latest |
| System | windows |
| Browser | Google Chrome |

---
无

**Comment by ycjcl868** [comment]
you can use `href` prop to replace the hyperlink.

```diff
const { Button } = antd;

ReactDOM.render(
  <div>
-    <Button type="primary" icon="download">
+    <Button type="primary" icon="download" href="xxxxxx">
-        <a href="xxxxxxxxx" download="xxxx.docx" >下载</a>
+下载
                      </Button>
  </div>,
  mountNode,
);
```
