### ISSUE TITLE
Twotone version of "calendar" icon is misspelled as "canlendar"

### ISSUE THREAD

**Issue by sheminusminus** [ant-design/ant-design#16810]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-t0wt3)

### Steps to reproduce
1. Make two icons, one with theme "outlined" and one with theme "twoTone"
2. Use type "calendar" on both of them
3. Notice twoTone renders nothing
4. Update the twoTone type to "canlendar" (a misspelling), then it works

### What is expected?
For all the icon types to be spelled the same way as their counterparts

### What is actually happening?
There are typos. So I'm coding for `const type = isTwoTone ? 'canlendar' : 'calendar';` (haha)

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.8.6 |
| System | macOS 10.14 |
| Browser | Chrome 74 |

**Comment by afc163** [comment]
Sorry, there is no `twoTone` version of `canlendar` icon now.

**Comment by afc163** [comment]
Sorry, there is no `twoTone` version of `canlendar` icon now.

**Comment by sheminusminus** [comment]
@afc163 I'm using it right now. It's just misspelled.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-icons/pull/63
