### ISSUE TITLE
Table 在不指定 pagination 的情况下，会显示错误的分页数据

### ISSUE THREAD

**Issue by superRaytin** [ant-design/ant-design#1683]
Demo: http://codepen.io/superRaytin/pen/xVeVxE?editors=001

**Comment by superRaytin** [comment]
一些线索：0.12.x 的 Demo 没有此问题 http://codepen.io/superRaytin/pen/RaOaaM?editors=001

**Comment by Yuanye** [comment]
刚刚也发现了。

**Comment by superRaytin** [comment]
好快 😂
