### ISSUE TITLE
Autocomplete - searching for numeric values populates input element

### ISSUE THREAD

**Issue by nachtm** [ant-design/ant-design#16847]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-yeicx?fontsize=14)

### Steps to reproduce
1. Type in the string "1" into the box

### What is expected?
The string 1 appears in the input element OR at least an event is fired. I expect the behavior to be the same between "1" and "a" as the first character typed into the box.

### What is actually happening?
The string "3333, ,3333" appears in the input element, making it impossible to search for any kind of numeric value

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | latest |
| System | Mac OS 10.14 |
| Browser | Chrome |

---
{3333} {3333} is a string stored in an `<Option />` component and is index 1 in the array of options, so I could see some use case where this would be helpful. But with no way to turn it off and no event fired when the autofill happens, searching and filtering for numeric values is not possible

**Comment by zombieJ** [comment]
When Option not provides `value` prop. It will take `key` as `value`. So tpying `1` match the value of key of `1` is `3333` and it display as `3333, ,3333`:  https://codesandbox.io/s/antd-reproduction-template-1w9v4
