### ISSUE TITLE
Input.Password background

### ISSUE THREAD

**Issue by cornwang** [ant-design/ant-design#16840]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-poitras-28epb?fontsize=14)

### Steps to reproduce
I want to set the background color of Input.Password, but directly to the interline style, I found that the style does not directly affect the input, but on the previous layer.

### What is expected?
Input.Password can set its background color by line style

### What is actually happening?
Color does not take effect on input

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | mac |
| Browser | Google Chrome |

---
Existing requirements, to pass a dynamic color, so you need to change the background color of the password box

**Comment by afc163** [comment]
`style` of component goes to wrapper element, you can try `className` for inner element style customization: https://codesandbox.io/s/hopeful-sound-hb0el
