### ISSUE TITLE
select focus style problem after upgrade to latest

### ISSUE THREAD

**Issue by Aggie123** [ant-design/ant-design#1684]
antd升级到1.0.1之后,select选中之后样式出现以下问题，是怎么回事呢：
![2016-05-13 11-40-46](https://cloud.githubusercontent.com/assets/14816026/15237680/da31f0a0-1902-11e6-9b35-4ac3880690bd.png)

**Comment by afc163** [comment]
麻烦提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by Aggie123** [comment]
不好意思，不太好复现，我描述一下问题，大概分析如下：

focus的样式问题，临时解决方案是把下面这个样式注掉就OK了：
.ant-select-combobox .ant-select-search__field:focus {
  /*box-shadow: 0 0 0 1px #57c5f7, 0 0 0 3px #d5f1fd;*/
}

我看官网API文档上的例子，区别是本地缺少这个mock-browser.less，这个文件在哪获取？
.ant-select-combobox .ant-select-search__field:focus {
    box-shadow: none;
}

希望描述的清楚，谢谢！

**Comment by afc163** [comment]
感谢提供进一步的信息，确实有问题，已在主干修复。

**Comment by Aggie123** [comment]
辛苦了！

**Comment by afc163** [comment]
尽量多一些细节就很有帮助，我们有时候官网看看没问题容易忽略掉。

**Comment by Aggie123** [comment]
Rogers!
