### ISSUE TITLE
LogRocket: Session quota exceeded. Please upgrade your plan. Disabling ...

### ISSUE THREAD

**Issue by rhamianiuk** [ant-design/ant-design#16848]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
Just go to the https://ant.design

### What is expected?
Main page is opened

### What is actually happening?
Blank page and following message in console: LogRocket: Session quota exceeded. Please upgrade your plan. Disabling ...

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | no react, the issue is related to the main page at https://ant.design |
| System | MacOS |
| Browser | Chrome |

---
I think this is a bug of LogRocket (at least they have few related issues in their bugtracker).
Navigating to the page from other browser or in incognito mode opens the page correctly.
BTW, cleaning cookies (and all other local browser data) doesn't help.

**Comment by zombieJ** [comment]
LogRocket is used for site error log record. It may not affect with browser open. Could you attach the network snapshot for more info to trace?

**Comment by rhamianiuk** [comment]
Hey ZombieJ,
Please see the HAR and log files attached. Let me know if this is not what you need.
[ant.design.har.zip](https://github.com/ant-design/ant-design/files/3231758/ant.design.har.zip)
[ant.design-1559122604265.log](https://github.com/ant-design/ant-design/files/3231760/ant.design-1559122604265.log)

**Comment by rhamianiuk** [comment]
Also, it worth to mention, LogRocket blocked me on two different hosts, though allowing me to access the home page in incognito mode. So I assume they track me somehow.

**Comment by zombieJ** [comment]
Could you try to disable extensions. The log should be as follow when it works:
![屏幕快照 2019-05-29 下午6 53 19](https://user-images.githubusercontent.com/5378891/58551645-2368c800-8243-11e9-835d-5b6f03c3cebf.png)

**Comment by rhamianiuk** [comment]
Hey ZombieJ, thanks for your input, I disabled the extensions one-by-one and found _Wizmage Image Hider_ is causing this issue. Just putting this note here if someone else will stumble upon this issue.
