### ISSUE TITLE
Mentions中能否响应onPaste事件

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#16858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在文本处理中，会遇到截图粘贴的处理事件，把截图的内容转出base64交给后端进行存储内容，如果响应不了则无法处理粘贴图片的响应

### What does the proposed API look like?
onPaste，响应默认粘贴事件

**Comment by zombieJ** [comment]
能具体描述一下吗？`onPaste` 事件是支持的：https://codesandbox.io/s/gifted-surf-h003c

**Comment by junhui75165** [comment]
@zombieJ 是想通过粘贴事件响应截图内容，然后在Mentions中插入一个图片
![image](https://user-images.githubusercontent.com/3411959/58607074-bb60c300-82d0-11e9-8b5f-3da3b8f0e280.png)

**Comment by afc163** [comment]
Mentions 就是 Textarea，应该不支持插入图片。

**Comment by zombieJ** [comment]
见上，Mentions 定位是轻量级提及组件。不会做的过重。
