### ISSUE TITLE
Transfer search crash with a large amount of data

### ISSUE THREAD

**Issue by ycjcl868** [ant-design/ant-design#16855]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[codesandbox](https://codesandbox.io/s/nameless-pine-s1o5t)

### What does the proposed API look like?
now `lazy` uses [react-lazy-load](https://github.com/loktar00/react-lazy-load), but then list dom tree still rendered. 

suggest using [react-virtualized](https://github.com/bvaughn/react-virtualized) insteaded.

**Comment by afc163** [comment]
Duplicate of #9703
