### ISSUE TITLE
Model.comfirm the ok btn default is focus

### ISSUE THREAD

**Issue by emily-juan** [ant-design/ant-design#16857]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
click the comfirm model, the ok btn is focus, then I hover or focus the color is not change.  

### What is expected?
when I hover the ok btn I want the color change. let customer know the btn can click

### What is actually happening?
the ok btn color no change, because the btn is default on the focus style

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | react 16.0 |
| System | window10 |
| Browser | chrom |

**Comment by afc163** [comment]
It is better for accessibility.

Try `autoFocusButton` prop if don't need that. (**strongly not recommended**)
