### ISSUE TITLE
@text-color-danger & @text-color-warning should inherit @error-color and @warning-color by default

### ISSUE THREAD

**Issue by Stephen2** [ant-design/ant-design#16856]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://no-repro-link.com](https://no-repro-link.com)

### Steps to reproduce
Set custom @error-color and @warning-color
Notice that `<Text type="danger">` uses default `@red-7`, and text warning uses default `@gold-7`

### What is expected?
Expected that the text colours follow the global variables for error/warning

### What is actually happening?
They use other default colours

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.4 |
| System | Manjaro linux |
| Browser | Chrome 74 |

**Comment by zombieJ** [comment]
Seems `@text-color-danger` & `@text-color-warning` is only used by Typography. It can be removed and use `@error-color` & `@warning-color` instead.

Do you have interested to send a PR about this?

**Comment by MrHeer** [comment]
so, can I do this?

---
[components/typography/style/index.less#L41](https://sourcegraph.com/github.com/ant-design/ant-design/-/blob/components/typography/style/index.less#L41)
```diff
&&-warning {
- color: @text-color-warning;
+ color: @warning-color;
} 
&&-danger {
- color: @text-color-danger;
+ color: @error-color;
}
```
---
[components/style/themes/default.less#L50](https://sourcegraph.com/github.com/ant-design/ant-design/-/blob/components/style/themes/default.less#L50)
```diff
- @text-color-warning: @gold-7;
- @text-color-danger: @red-7;
```

**Comment by zombieJ** [comment]
I think it's ok.

**Comment by MrHeer** [comment]
I'll PR as quickly as possible, thank you.

**Comment by MrHeer** [comment]
I found that the latest code(`master` branch) has a lot of test suites failed.

**Comment by zombieJ** [comment]
@MrHeer , could you try remove `node_modules` and install again. Seems it works well in CI:
<img width="751" alt="屏幕快照 2019-05-30 上午10 31 08" src="https://user-images.githubusercontent.com/5378891/58604209-1c36ce00-82c6-11e9-89f4-445b1d15556d.png">

**Comment by MrHeer** [comment]
I think you are right. I'll retry tonight. Thank you very much.
