### ISSUE TITLE
Form配合Steps使用，在返回上一个step时，Form已经输入的内容被清空

### ISSUE THREAD

**Issue by Symous** [ant-design/ant-design#16868]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/green-cdn-s5rcj)

### Steps to reproduce
在上方的重现链接中，Form搭配Steps使用时：
1. 第一个Step中在Form绑定的Input中输入内容（绑定了name属性）
2. 点击下一步，进入第二个Step
3. 点击上一步，然后返回第一个Step
4. 此时发现Input中绑定的内容被清空

经过实际测试中发现，在点击下一步渲染第二个Step时，可以从this.form.getFieldValue('name')中取到值，而点击上一步返回第一个Step时，this.form.getFieldValue('name')已经变为undefined。

### What is expected?
已经输入的Input的值应该保留（储存在this.props.form.name中）

### What is actually happening?
Input对应的值被清空

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.6.3 |
| System | WIndows 10 64 bit |
| Browser | 74.0.3729.169（正式版本） （64 位） |

**Comment by afc163** [comment]
value 是跟着 `getFieldDecorator` 装饰的组件走的，组件被卸载，value 也会被清空。

- 可以用 `style={{ display: 'none' }}` 去隐藏元素，而不是卸载。
- 或者把 value 同步到上层 state 中保留起来。
