### ISSUE TITLE
Input allowClear click clear icon need a callback event

### ISSUE THREAD

**Issue by tong233** [ant-design/ant-design#16862]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
input缺少点击清除按钮的事件

### What does the proposed API look like?
onClear

**Comment by yesmeck** [comment]
Just use `onChange`.

```javascript
<Input onChange={(e) => {
  if (e.target.value === '') {
    // input is cleared.
  }
}} />
```

**Comment by tong233** [comment]
> You can use `onChange`.
> 
> ```js
> <Input onChange={(e) => {
>   if (e.target.value === '') {
>     // input is cleared.
>   }
> }} />
> ```

onChange不能区分是手动删除的还是点击按钮清空的。。

**Comment by tong233** [comment]
@yesmeck @afc163

**Comment by yesmeck** [comment]
为什么要区分，需要解决什么问题？

**Comment by tong233** [comment]
> 为什么要区分，需要解决什么问题？

比如点清空我会自动去请求全部，手动删除可能是在更换搜索关键词，需要按回车或点🔍才请求。

**Comment by WangJM001** [comment]
需求+1

**Comment by afc163** [comment]
```js
<Input onChange={(e) => {
  if (e.target.value === '') {
    // input is cleared.
  }
}} />
```

or

```js
<Input onChange={(e) => {
  if (e.type === 'click') {
    // clear icon is clicked
  }
}} />
```

**Comment by sitepodmatt** [comment]
@afc163 
How does this work when Input is wrapped in Form.Item? I presume Form.Item registering onChange removes this behavior?

**Comment by daphne-jr** [comment]
Here is a workaround solution to wrap the Input in case if anyone need. I'm using 4x version with Typescript.

```typescript
import React from 'react';
import {  Input } from 'antd';
import { InputProps } from 'antd/lib/input';

interface MyInputProps extends InputProps {
  onClear?: () => void;
}

// forward Ref such that when you use <MyInput ref={ref} ... /> it will work
const MyInput = React.forwardRef<Input, MyInputProps>(
  ({ onClear, ...otherProps }: MyInputProps, ref) => {
    const myRef = React.useRef(null);

    const setRef: React.LegacyRef<Input> = (node) => {
      myRef.current = node;
      if(!ref) {
        return;
      }
      if(typeof ref === 'function') {
        return ref(node);
      }
      ref.current = node;
    };

    React.useEffect(() => {
      // inject own onClear() into Antd handleReset method
      const handleReset = myRef.current?.handleReset;
      myRef.current.handleReset = (e: React.MouseEvent<HTMLElement, MouseEvent>) => {
        handleReset?.(e);
        onClear?.();
      };
    }, []);

    return <Input ref={setRef} {...otherProps} />;
  }
);

```

then you can just use it as...

```typescript
<MyInput 
  onClear={() => {
    // ...implement
  }} 
/>
```

Hope it helps someone.

**Comment by ode10xers** [comment]
<Input
        allowClear={{ 
           clearIcon: <p 
              onClick={() => {
                    // ...implement
               }} > x <p/> 
        }}
      />

**Comment by 0xLDev** [comment]
> ```
> <Input
>         allowClear={{ 
>            clearIcon: <p 
>               onClick={() => {
>                     // ...implement
>                }} > x <p/> 
>         }}
>       />
>       ```
> ```

Thank you very much, it helped a lot

**Comment by li-jia-nan** [comment]
Support in #49905
