### ISSUE TITLE
Submenu containing selected item in inline mode is not highlighted

### ISSUE THREAD

**Issue by davidebianchi** [ant-design/ant-design#16866]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-stonebraker-5hz96)

### Steps to reproduce
It is already visible that the sub menu titles are not highlighted

### What is expected?
It is expected that SubMenu titles are active. e.g. https://codesandbox.io/s/vibrant-boyd-4wunz

### What is actually happening?
Sub menu titles are not active

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | OSX |
| Browser | Chrome v74 |

---
Maybe it is an expected behaviour, but the main issue is that if you close the submenu, it is not clear the selected menu item

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/17039
