### ISSUE TITLE
TreeSelect  Error with selectedOption duplicate key

### ISSUE THREAD

**Issue by ruoqianfengshao** [ant-design/ant-design#16860]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ruoqianfengshao/pen/EzeXGZ](https://codepen.io/ruoqianfengshao/pen/EzeXGZ)

### Steps to reproduce
全选所有 option 之后，反复勾选第一个 option，选中值会越来越多，同时报错 key 重复

### What is expected?
不报错，value 的值正确

### What is actually happening?
输入框内的显示值重复出现
![image](https://user-images.githubusercontent.com/2928664/58541477-2d340080-822e-11e9-90e3-8422c889f9d5.png)

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8 |
| System | maxOS |
| Browser | Chrome |

---
 codepen 的 demo 根据官方的 showcase 改造

**Comment by zombieJ** [comment]
Thanks for feedback. Fixed in `rc-animiate`. Pls reinstall `node_modules`: https://codesandbox.io/s/agitated-villani-595zb

**Comment by ruoqianfengshao** [comment]
Thanks for your fix. It works fine now.
