### ISSUE TITLE
When is recursive association selection for parent-child data supported

### ISSUE THREAD

**Issue by radish999** [ant-design/ant-design#16875]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Recursive association selection of parent-child data

### What does the proposed API look like?
Recursive association selection of parent-child data

**Comment by zombieJ** [comment]
Not get the point. Pls feel free leave more comment and I will reopen:
* Which component?
* What's mean of `recursive association selection for parent-child data supported`
