### ISSUE TITLE
Add odd number support to <List />

### ISSUE THREAD

**Issue by Jiahao01121** [ant-design/ant-design#16870]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently <List /> component only accepts even number, when grid prop in <List /> sets to something like {column: 5}, the class name assigned to each item is wrong. (It sets to ant-col-4, but supposed to be ant-col-5)

### What does the proposed API look like?
column prop,	column of grid,  number, 1-24

**Comment by zombieJ** [comment]
List column also follow the Design of [Grid](https://ant.design/components/grid-cn/#header) with 24 columns.
If 24 columns can't satisfy with requirement, you can use Grid with flex mode directly with more flexible grid ability:
https://codesandbox.io/s/silent-dawn-kz2z9
