### ISSUE TITLE
表格的嵌套表格功能，设置fix之后，子表格展开后，最后的一项不能同时在下面展示

### ISSUE THREAD

**Issue by liuyueji** [ant-design/ant-design#16878]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-germain-md2om)

### Steps to reproduce
定位表格最后一项

### What is expected?
跟随展开内容下降

### What is actually happening?
固定项目不动

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome 版本 71.0.3578.98（正式版本） （64 位） |

**Comment by afc163** [comment]
<img width="730" alt="image" src="https://user-images.githubusercontent.com/507615/58612220-6b8bf700-82e4-11e9-9369-60aa0f199e64.png">

```
Warning: [antd: Table] `expandedRowRender` and `Column.fixed` are not compatible. Please use one of them at one time.
```

**Comment by Bandersnatch0x** [comment]
换了个思路，使用数据处理将展开内容作为独立行插入自定义单元格渲染实现展开效果，原有交互方式不变

![Image](https://github.com/user-attachments/assets/44c3cb93-9191-4e9d-83cc-c63e7a15ebb0)

// ExpandableTable.tsx
import React, { useState } from 'react';
import { Table } from 'antd';

/**
 * 表格记录接口定义
 */
interface TableRecord {
  key: React.Key;
  [key: string]: any;
}

/**
 * 可展开表格组件属性
 */
interface ExpandableTableProps {
  columns: any[];               // 表格列配置
  dataSource: TableRecord[];    // 表格数据源
  expandedRowRender: (record: TableRecord) => React.ReactNode; // 展开行渲染函数
}

/**
 * 可展开表格组件
 */
const ExpandableTable: React.FC<ExpandableTableProps> = ({
  columns,
  dataSource,
  expandedRowRender
}) => {
  // 状态管理
  const [expandedRows, setExpandedRows] = useState<React.Key[]>([]);      // 当前展开的行key数组
  const [expandedData, setExpandedData] = useState<Record<string, any>>({}); // 展开行的数据

  /**
   * 处理行展开/收起
   * @param record 当前行记录
   */
  const handleExpand = (record: TableRecord) => {
    const key = record.key.toString();
    
    if (expandedRows.includes(key)) {
      // 如果已展开，则收起
      setExpandedRows(prev => prev.filter(k => k !== key));
      setExpandedData(prev => {
        const { [key]: _, ...rest } = prev;
        return rest;
      });
    } else {
      // 如果未展开，则展开
      setExpandedRows(prev => [...prev, key]);
      setExpandedData(prev => ({
        ...prev,
        [key]: {
          content: expandedRowRender(record),
          parentKey: key
        }
      }));
    }
  };

  /**
   * 处理数据源，添加展开行数据
   */
  const processedDataSource = dataSource.reduce<TableRecord[]>((acc, cur) => {
    acc.push(cur);
    if (expandedData[cur.key]) {
      acc.push({
        ...expandedData[cur.key],
        key: `${cur.key}-expanded`,
        isExpandedRow: true
      });
    }
    return acc;
  }, []);

  /**
   * 自定义单元格渲染逻辑
   * @param text 单元格文本
   * @param record 当前行记录
   * @param index 行索引
   * @param column 当前列配置
   */
  const customCellRender = (text: any, record: TableRecord, index: number, column: any) => {
    if (record.isExpandedRow) {
      // 展开行的特殊渲染
      if (column.dataIndex === columns[0].dataIndex) {
        return {
          children: record.content,
          props: { colSpan: columns.length }  // 第一列跨越所有列
        };
      }
      return { props: { colSpan: 0 } };  // 其他列隐藏
    }

    // 普通行使用列定义的render函数或直接显示文本
    if (column.render) {
      return column.render(text, record, index);
    }
    return text;
  };

  return (
    <Table
      // 处理列配置，添加自定义渲染函数
      columns={columns.map(col => ({
        ...col,
        render: (text: any, record: TableRecord, index: number) =>
          customCellRender(text, record, index, col)
      }))}
      // 处理后的数据源，包含展开行
      dataSource={processedDataSource}
      // 行key处理
      rowKey={record => record.isExpandedRow ? record.key : record.key.toString()}
      // 行点击事件，非展开行可点击展开
      onRow={record => ({
        onClick: () => !record.isExpandedRow && handleExpand(record)
      })}
    />
  );
};

export default ExpandableTable;

/**
 * 使用示例
 */
// const App = () => {
//   // 示例数据
//   const data = [
//     { key: '1', name: 'John', age: 32, address: 'New York', description: 'This is John\'s description' },
//     { key: '2', name: 'Jane', age: 28, address: 'London', description: 'This is Jane\'s description' },
//   ];
// 
//   return (
//     <ExpandableTable
//       columns={[
//         { title: 'Name', dataIndex: 'name', key: 'name' },
//         { title: 'Age', dataIndex: 'age', key: 'age' },
//         { title: 'Address', dataIndex: 'address', key: 'address' },
//         {
//           title: 'Action',
//           key: 'action',
//           fixed: 'right',
//           render: (_, record) => <a>Delete</a>,
//         }
//       ]}
//       dataSource={data}
//       expandedRowRender={record => (
//         <p style={{ margin: 0 }}>{record.description}</p>
//       )}
//     />
//   );
// };
