### ISSUE TITLE
Popover's content contains image and placement="top",but first hover it displays not top. 

### ISSUE THREAD

**Issue by LinkChenzy** [ant-design/ant-design#16879]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-dirac-utu6h)

### Steps to reproduce
view code

### What is expected?
content display top anywhere

### What is actually happening?
I find a way that content'img set width and height property,this can void above bug 

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | window |
| Browser | google |

**Comment by leeseean** [comment]
I need a job,anyone give me a chance?

**Comment by zombieJ** [comment]
This is not Popover bug. When the Popover first render, img is indeed no size and Popover calculate the position with 0 size img content. It's correct popup position.

Setting img size or content size your use is correct.
