### ISSUE TITLE
DatePicker组件onOpenChange和onChange执行顺序问题

### ISSUE THREAD

**Issue by perany** [ant-design/ant-design#16873]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date](https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date)

### Steps to reproduce
在封装自定义日期范围选择器时，点击事件选择器，选择时间。会先触发onOpenChange后再触发onChange，导致在onOpenChange时无法获取最新选择的时间

### What is expected?
要么在onOpenChange内返回最新选择时间，要么先触发onChange再触发onOpenChange。再或者就是在RangePicker中增加选择时间跨度长度限制的配置项，比如所选时间跨度不能超多一个月等，这样就不用自己封装了

### What is actually happening?
针对选择时间跨度长度限制的需求，现在需要自己使用两个DatePicker封装自定义的RangePicker，在实现开始时间和结束时间必须都填或者都不填效果时，要在onOpenChange回调内判断当前选择时间是否为空，而onChange再其后触发，所以在onOpenChange永远无法获取最新选择的值；若改为在onChange内判断是否有值，当用户不选择时间直接关闭面板不触发该回调。因此需要调整onOpenChange和onChange的执行顺序

| Environment | Info |
|---|---|
| antd | 3.18.0 |
| React | 16.7.0 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
`onOpenChange` 和 `onChange`  处理的时机并不相同，因而也不应该依赖其触发顺序。希望在 `onOpenChange` 获取之后更新的值的话，你可以对 `onOpenChange` 进行封装: https://codesandbox.io/s/exciting-fermat-rgyml

**Comment by perany** [comment]
非常感谢大神的解答！使用Promise后确实可以解决这个问题了，大赞

在 2019-05-30 14:07:55，"zombieJ" <notifications@github.com> 写道：


onOpenChange 和 onChange 处理的时机并不相同，因而也不应该依赖其触发顺序。希望在 onOpenChange 获取之后更新的值的话，你可以对 onOpenChange 进行封装: https://codesandbox.io/s/exciting-fermat-rgyml
