### ISSUE TITLE
table 组件Column 属性  下的 filterDropdown功能，希望加一个父级元素的设置，最好是基于当前th进行定位，不然，当table外层元素加height：100%,会出现表头滚动，filterDropdown固定不动的bug，

### ISSUE THREAD

**Issue by HeWenKe** [ant-design/ant-design#16876]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不然，当table外层元素加height：100%,会出现表头滚动，filterDropdown固定不动的bug

### What does the proposed API look like?
给当前的filterDropdown增加一个相对父元素的设置,类似getPopupContainer.

**Comment by zombieJ** [comment]
能写一个重现我看看不？

**Comment by haven2world** [comment]
刚刚发现了一个filterDropdown相对父元素的bug，如果筛选结果为空的话会导致下拉框显示不出来

**Comment by zombieJ** [comment]
@haven2world  方便开个 issue 看看不？

**Comment by haven2world** [comment]
> @haven2world 方便开个 issue 看看不？

ok, wait a minute

**Comment by haven2world** [comment]
> @haven2world 方便开个 issue 看看不？

[The filter dropdown displays ...](https://github.com/ant-design/ant-design/issues/16882#issue-450168104)

**Comment by HeWenKe** [comment]
这个table的父级元素设置很多的height：100%；，滚动条是父级的某个元素产生的，不是body的滚动条，才导致这种问题。我希望类似这个：table的clomun这个属性



加上fiexd以后，这个filterdropdown就是相对这个table第一个父级定位，

这样就不会出现那种问题。
------------------ 原始邮件 ------------------
发件人: "zombieJ"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 中午1:46
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "雪域之巅"<1027186808@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design] table 组件Column 属性  下的 filterDropdown功能，希望加一个父级元素的设置，最好是基于当前th进行定位，不然，当table外层元素加height：100%,会出现表头滚动，filterDropdown固定不动的bug， (#16876)




能写一个重现我看看不？

**Comment by HeWenKe** [comment]
这个可能和我的页面布局和样式有关系，布局也是用的antd的layout布局，目前这个filterdropdown 都不会随着容器的滚动而滚动，被top 值定位到一个位置固定死了，这个top值又不是基于当前滚动条容器产生的，而是基于body的。





------------------ 原始邮件 ------------------
发件人: "zombieJ"<notifications@github.com>;
发送时间: 2019年5月30日(星期四) 中午1:46
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "雪域之巅"<1027186808@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design] table 组件Column 属性  下的 filterDropdown功能，希望加一个父级元素的设置，最好是基于当前th进行定位，不然，当table外层元素加height：100%,会出现表头滚动，filterDropdown固定不动的bug， (#16876)




能写一个重现我看看不？

**Comment by songyule** [comment]
> 能写一个重现我看看不？

https://codesandbox.io/s/focused-margulis-jmtgq?file=/index.js
![image](https://user-images.githubusercontent.com/23656890/87529881-34340180-c6c2-11ea-9085-260cf757e0fc.png)
misplaced
@zombieJ

**Comment by yoyo837** [comment]
开个新issue吧如何？

**Comment by songyule** [comment]
> 开个新issue吧如何？
[new issue](https://github.com/ant-design/ant-design/issues/25637)

**Comment by Hallelujah1** [comment]
> > 能写一个我回头看看不？
> 
> https://codesandbox.io/s/focused-margulis-jmtgq?file=/index.js 错位 ![图片](https://user-images.githubusercontent.com/23656890/87529881-34340180-c6c2-11ea-9085-260cf757e0fc.png) @zombieJ

请问这个问题您解决了吗？
