### ISSUE TITLE
RangePicker默认当前日期显示问题

### ISSUE THREAD

**Issue by xiaoxintang** [ant-design/ant-design#16872]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://unreal](http://unreal)

### Steps to reproduce
RangePicker在当前日期是月末的时候，例如5月30日

### What is expected?
去掉其中一个的激活状态

### What is actually happening?
出现两个当前日的激活状态，跟时间选择了范围的样式太接近，让用户迷惑
![image](https://user-images.githubusercontent.com/24927686/58604136-ded24080-82c5-11e9-97e5-746159e5e6fd.png)
![image](https://user-images.githubusercontent.com/24927686/58604235-37a1d900-82c6-11e9-9b63-99488bb128a1.png)

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.7.0 |
| System | macos 10.14.4 |
| Browser | Google Chrome 73.0.3683.86 |

---
建议：rangePicker使用起来有点疑惑，可否将默认当前日的激活状态更改为其他样式，不要跟选择日期范围的时候显示的一样的样式

**Comment by xiaoxintang** [comment]
![image](https://user-images.githubusercontent.com/24927686/58604284-6cae2b80-82c6-11e9-9edd-54bc66f6d9b3.png)
![image](https://user-images.githubusercontent.com/24927686/58604299-7cc60b00-82c6-11e9-817c-6d8249bd43b7.png)

**Comment by afc163** [comment]
确实不好。

#17878
