### ISSUE TITLE
The filter dropdown displays in a wrong way when the table is empty and getPopupContainer is set as triggerNode.parentNode

### ISSUE THREAD

**Issue by haven2world** [ant-design/ant-design#16882]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/haven2world/pen/MdPOZg](https://codepen.io/haven2world/pen/MdPOZg)

### Steps to reproduce
- open the link above
- click the filter icon

### What is expected?
show the complete dropdown

### What is actually happening?
the dropdown is hidden in the short table 
![image](https://user-images.githubusercontent.com/17299418/58615855-ad219f80-82ee-11e9-8a71-cb82838746a1.png)

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome  74.0.3729.169 |

---
This is my temporary solution.
```
  getPopupContainer = (triggerNode)=>{
    if(triggerNode.parentNode.tagName === 'TH'){
      return document.body
    }
    return triggerNode.parentNode;
  }
```

**Comment by zombieJ** [comment]
Since Empty Table provides an div to hold the Empty content. The real table content is only the part of Header which makes height over the header to scroll. When you use `ConfigProvider` to set `getPopupContainer` this logic should handle by your code logic. My suggestion is to wrap it as a component:
```jsx
class MyTable extends React.Component {
  render() {
    const { dataSource } = this.props;
    return (
      <ConfigProvider getPopupContainer={(node) => dataSource.length ?  this.parentNode : document.body;}>
        <Table {...this.props} />
      </ConfigProvider>
    );
  }
}
```

**Comment by NeoYo** [comment]
I think use table header `document.querySelector?.('#root div.ant-table-container > div.ant-table-header') || document.body}` as PopupContainer is better to avoid cover by table body and get correct position

```js
class MyTable extends React.Component {
  render() {
    <Table
      columns={initColumn as any[]}
      dataSource={data}      
      getPopupContainer={() => document.querySelector?.('#root div.ant-table-container > div.ant-table-header') || document.body}
     />
  }
}
```
