### ISSUE TITLE
separate prop for Esc key support for Drawer

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#16883]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
if Drawer's maskClosable={false}, Esc won't work. And if maskClosable is true, no way to disable Esc

### What does the proposed API look like?
Same prop as Modal's, whether support press Esc to close - keyboard

**Comment by jljsj33** [comment]
keyboard={false}

**Comment by jljsj33** [comment]
原来陈帅这货留这 API 还是有用的。。。

**Comment by IndProgo** [comment]
Sorry, wasn't in documentation. it's already there

**Comment by IndProgo** [comment]
keyboard prop is there, but esc doesn't work if maskClosable={false}. It should be separate prop, independent of maskClosable
