### ISSUE TITLE
Cascader showsearch property breaks hover interactivity in displayRender.

### ISSUE THREAD

**Issue by KrFeher** [ant-design/ant-design#16887]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/distracted-bush-ivvrp)

### Steps to reproduce
1. Check if hover works (it won't)
2. Now comment out ShowSearch property
3. Try hover again (it works) 

### What is expected?
For displayRender interactivity to continue working

### What is actually happening?
It doesn't work.

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.9.0 |
| System | Windows 10 |
| Browser | Chrome Version 72.0.3626.121  |

---
This line is causing it to override "position: static" from ant-cascader-input class with relative.

https://github.com/ant-design/ant-design/blob/abb8692b59b461974332a43d38e9bce622df4094/components/cascader/style/index.less#L20
Removing this however stops the Showsearch to work.

**Comment by KrFeher** [comment]
Hi, is this going to be picked up / fixed ?

**Comment by KrFeher** [comment]
Hello?

**Comment by afc163** [comment]
It is a thorny problem.

**Comment by afc163** [comment]
It is fixed in 5.x now: https://stackblitz.com/edit/react-tugdgz?file=demo.tsx
