### ISSUE TITLE
form表单不支持动态赋值

### ISSUE THREAD

**Issue by yuankaifan** [ant-design/ant-design#16889]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当从后台拿到数据时是一个json array 表单通过便利这个数组动态生成 用这个数组动态赋值这个表单

### What does the proposed API look like?
setFieldsValue api希望赋值时不仅只支持字符串 也支持变量 类似于 `type[${index}]` index是数组便利的索引

**Comment by afc163** [comment]
可以支持，读取数据渲染出 fields 就行。

**Comment by yuankaifan** [comment]
但是就是不能普通的赋值 按照一个表单一样的赋值

**Comment by afc163** [comment]
如果遇到问题，请用 bug report 模板发一个新的 issue，务必提供 codesandbox 重现链接和重现步骤。
