### ISSUE TITLE
当Tbale的filterMultiple未flase指定为单选的时候返回值是否应该为单个元素而不是数组

### ISSUE THREAD

**Issue by zhaofinger** [ant-design/ant-design#16891]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5z1mpox56p)

### Steps to reproduce
1. F12打开控制台
2. 表头筛选地址（单选）
3. 查看控制台打印address值可以看到是数组类型

### What is expected?
filterMultiple为false单选的时候返回值是单项而不是数组

### What is actually happening?
filterMultiple为false单选的时候返回值是数组

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.7.0 |
| System | macOS Mojave |
| Browser | Chrome 74.0.3729.169 |

**Comment by afc163** [comment]
确实可以不是数组，数组问题也不大，而且 TypeScript 类型也比较稳定。

更重要的是，修改会是一个 break change，目前还是尽量保持原样吧。
