### ISSUE TITLE
V4 alpha prepare

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#16898]
## Mainly Target
- [ ] v4 branch
- [ ] Compatible package
- [ ] Remove Deprecated Content
  - [ ] Mention Component
    - [x] New Mentions Component #16532
  - [ ] Form.create
  - [ ] Icon with `type` #12011
  - [ ] Other with deprecated warning props
- [ ] Less v3
- [ ] Performance
  - [ ] `rc-animate` upgrade
    - [ ] concurrent mode support
    - [ ] Virtual scroll animation support
  - [ ] Virtual Scroll
    - [ ] rc component
    - [ ] Tree
    - [ ] Select
    - [ ] TreeSelect
  - [ ] Form: https://github.com/react-component/form/pull/292
    - [ ] Provides Hooks version
  - [ ] Table
    - [ ] templateAreas
    - [ ] Support `expand` & `scroll` co-work
- [ ] DatePicker with new design
  - [ ] YearPicker
  - [ ] RangePicker.YearPicker
  - [ ] RangePicker.MonthPicker
  - [ ] RangePicker.YearMonthPicker
  - [ ] RangePicker.WeekPicker
  - [ ] TimePicker.RangePicker

## Continue Target
- [ ] Accessibility
- [x] API standard
- [ ] React.StrictMode

**Comment by drcmda** [comment]
First of all congratulations, using this since version 1, which must’ve been years, and it’s come such a long way!

There’s one problem I’ve had with it that always used to be my biggest gripe, it clones children instead of context, see:

https://github.com/ant-design/ant-design/issues/7846

https://github.com/ant-design/ant-design/issues/4688

This makes custom leaf components so hard to do as well as writing connected components. Cloning overall is a scary thing. The workarounds of forwarding props are not feasible imo. Please consider using context! 🙏

**Comment by Nokecy** [comment]
Virtual Scroll应该还要加上Table组件 #3789

**Comment by zmayor** [comment]
> Virtual Scroll应该还要加上Table组件 #3789

`rc-component` includes `table` component.

**Comment by zombieJ** [comment]
Hi @drcmda, thanks for your support

Some of the Component is already used with context. But for perf consider, we may not move all the props into context. Wrapped component is still recommend to pass props to sub component. But after virtual scroll support, it may not have this problem.

My description about '`rc-animate` replacement' is not precise enough. Since React will support concurrent mode, we updated `rc-animate` with pure React way, to avoid some animation flash (#13308). And also, the virtual scroll component will be little coupling with `rc-animte` to support virtual collapse animation smooth. I've updated in the check list : )

**Comment by muzea** [comment]
I think `templateAreas` is not a good design.
- `Template literals` When there is a newline, the preceding space is part of the content and the formatting tool cannot handle it.
- String loses type, no intellisense, and it is difficult to do type checking.

**Comment by Frank1e0927** [comment]
关于：`templateAreas `

name      age 
address  company

这将会解析成什么？由于这是字符串模板，应该不会报任何错误。

另外cells乱写很神奇的item key 应该也不会有类型报错。

字符串和cells里面的对应关系只能由肉眼检查。

一切都交到给运行时再检查吗？0 0

**Comment by jas0ncn** [comment]
## About `templateAreas`

templateArea parses string at runtime, it will cause many unexcepted parsing error or slient error. And runtime parsing is also unfriendly to TypeScript. Would you consider the proposal below:

```jsx
const columnTemplate = [
  ['name', 'address', 'adress'],
  ['name', 'building', 'no']
]
```

## About dependence

Would AntTeam consider remove  `moment` dependence?

Currently, some TimePicker and DatePicker's props' type is moment object. It makes us cannot replace moment with datefns or other time library which smaller than moment.

## About Icon

Ant Icons should not be deprecated, the new Icon import way may cause common bundle chunk change when I add or remove one Icon.

I think Ant Team can provider two ways to use ant icon, the first is import whole ant icons with Webpack externals, and the second way is directly import the icon which be used.

**Comment by afc163** [comment]
Please discuss at #16911.

**Comment by afc163** [comment]
Merge this issue in https://github.com/ant-design/ant-design/issues/16911#issuecomment-497923110
