### ISSUE TITLE
add value prop to InputNumber, the component should becomes to a controlled component 

### ISSUE THREAD

**Issue by beizhedenglong** [ant-design/ant-design#16895]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-monad-fmx0c)

### Steps to reproduce
Just play with demo, the number still can change

### What is expected?
when add a value prop to InputNumber, the behaviour should like Input component. the component becomes to a  controlled component 

### What is actually happening?
InputNumber still is an uncontrolled component

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8 |
| System | MacOS |
| Browser | Latest Chrome |

**Comment by dengfuping** [comment]
@beizhedenglong Nothing wrong with your demo. In fact, `InputNumber` is a controlled component indeed.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14069#issuecomment-451468013

**Comment by bryantee** [comment]
@dengfuping It does _not_ appear to be a controlled component.

![image](https://user-images.githubusercontent.com/10674447/95618549-202e4080-0a22-11eb-841d-4f0ddb4cba56.png)

Here my `onChange` callback fires even when value is a string, the value is correctly set outside of the input, yet the input field still registers the string values.
