### ISSUE TITLE
and 使用 Row,Col布局，当不设置Col的span时，该Col会遮挡其他Col的显示

### ISSUE THREAD

**Issue by yunxifd** [ant-design/ant-design#16893]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-sinoussi-2i767)

### Steps to reproduce
查看第一行的显示

### What is expected?
不遮挡

### What is actually happening?
遮挡了其他列的显示

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.9.0 |
| System | win10  |
| Browser | chrome 74 |

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/58681431-f2050f00-839e-11e9-97bd-9045efa1f3ca.png)

使用问题

**Comment by yunxifd** [comment]
@ycjcl868 默认 span 是占满 24 栅格的

那理论上应该第一行显示不下，应该显示在第二行
