### ISSUE TITLE
Select Option 选中bug

### ISSUE THREAD

**Issue by ljg601105597** [ant-design/ant-design#1689]
Option固定的 如：
<Select default='1'>
<Option value='0'>李四</Option>
<Option value='1'>张三</Option>
</Select> 这样没问题
但是Option 是作为变量动态生成的的时候
var options={}
<Select default='1'>
{options}
</Select> 这个组件不会选中值 只会在这个组件上 显示 1

**Comment by afc163** [comment]
do not make duplicated issue #1690
