### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstChild' of undefined

### ISSUE THREAD

**Issue by ecafe8** [ant-design/ant-design#169]
按快速上手安装后,能正常跑起来服务. 
但是时间选择器的输入框点击后控制台里会有报错:
Uncaught TypeError: Cannot read property 'firstChild' of undefined

查了一下, 但是依然没有解决掉.
http://stackoverflow.com/questions/27153166/typeerror-when-using-react-cannot-read-property-firstchild-of-undefined

**Comment by afc163** [comment]
确实有这个问题。@sorrycc 看下。

**Comment by sorrycc** [comment]
React 不要直接引，加一行 `import React from 'react';` 就好了。
