### ISSUE TITLE
if childrenNode is empty the tree still show in table

### ISSUE THREAD

**Issue by linhaijian** [ant-design/ant-design#16900]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/twilight-lake-hlhl3)

### Steps to reproduce
children:[]

### What is expected?
if childrenNode empty the tree not show in table

### What is actually happening?
show 

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8 |
| System | mac os |
| Browser | Latest Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941
