### ISSUE TITLE
Calendar日历 通知事项日历，给5月8号一个通知事项，6月8号也显示了5月8号的事项

### ISSUE THREAD

**Issue by lvzhimingjobs** [ant-design/ant-design#16902]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar-cn/#components-calendar-demo-customize-header](https://ant.design/components/calendar-cn/#components-calendar-demo-customize-header)

### Steps to reproduce
https://ant.design/components/calendar-cn/#components-calendar-demo-customize-header

### What is expected?
期望只有在设置的月份和日期里显示通知事项

### What is actually happening?
实际是5月8号，6月8号、只要是8号都显示了通知事项

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.4 |
| System | windos |
| Browser | 谷歌 |

---
官方demo的bug'

![image](https://user-images.githubusercontent.com/37326179/58686512-93955c00-83b1-11e9-80ac-04002ae01e03.png)

**Comment by afc163** [comment]
例子没问题，这个例子只判断了日期，如果希望加上月份，需要你自行添加相关判断。

**Comment by lvzhimingjobs** [comment]
我觉得最起码官方的demo应该要存在这样的一个月份的判断
