### ISSUE TITLE
Steps component does not have onChange prop in latest npm release

### ISSUE THREAD

**Issue by jamieaitken** [ant-design/ant-design#16907]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://cdn.jsdelivr.net/npm/antd@3.19.1/lib/steps/index.d.ts](https://cdn.jsdelivr.net/npm/antd@3.19.1/lib/steps/index.d.ts)

### Steps to reproduce
yarn add antd

### What is expected?
For Steps to have a Prop of onChange

### What is actually happening?
onChange prop does not exist

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | React 16.8.3 |
| System | OSX 10.14.15 |
| Browser | Chrome Version 74.0.3729.169 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/16845
