### ISSUE TITLE
table Animation

### ISSUE THREAD

**Issue by douzhuanxingyi** [ant-design/ant-design#16904]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table组件在展示树型数据的时候，不能像tree组件或者Collapse一样在展开或者收起的时候有动画效果

### What does the proposed API look like?
animation: boolean

**Comment by zombieJ** [comment]
Table Tree 支持动画会显著提高维护成本，应该不会支持……
