### ISSUE TITLE
Select Option 选中bug

### ISSUE THREAD

**Issue by ljg601105597** [ant-design/ant-design#1690]
Option固定的 如：
\<Select defaultValue='1'>
\<Option value='0'>李四\</Option>
\<Option value='1'>张三\</Option>
\</Select> 这样没问题
但是Option 是作为变量动态生成的的时候
var options={}
\<Select defaultValue='1'>
{options}
\</Select> 这个组件不会选中值 只会在这个组件上 显示 1

**Comment by pixystone** [comment]
我之前遇到过，确保你的options里每一个value属性给的是字符串，number类型是无效的。看看是不是这个问题

**Comment by afc163** [comment]
麻烦提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
无法重现且楼主无后续响应，三天后一律超时关闭，有新反馈了就 reopen 。
