### ISSUE TITLE
Upload components can't get e.target.result

### ISSUE THREAD

**Issue by azl397985856** [ant-design/ant-design#1691]
i wanna check the file data instead of posting to backend . so i need a hook or something esle to get the file content.    For example, i use e.target.result to get the file result as usual, but now i can't

**Comment by yanglihuiylh102** [comment]
please see docs again

**Comment by azl397985856** [comment]
i used beforeUpload, but there's nothing about file data

**Comment by afc163** [comment]
What file data do your need? 

http://ant.design/#/components/upload?scrollTo=components-upload-demo-beforeUpload

https://developer.mozilla.org/en-US/docs/Web/API/File

It is better to supply code.

**Comment by azl397985856** [comment]
i wanna check the execel data . code just like that
![image](https://cloud.githubusercontent.com/assets/12479470/15254870/8d472292-196b-11e6-8ce9-1d1df8cb3c19.png)

**Comment by azl397985856** [comment]
![image](https://cloud.githubusercontent.com/assets/12479470/15255023/460beb50-196c-11e6-89c3-73e3948187a1.png)
when i use <input type="file" onChange={xxxxx}/>   it works
