### ISSUE TITLE
Tooltip.align - useCssTransform does not work

### ISSUE THREAD

**Issue by comerc** [ant-design/ant-design#16914]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-mcclintock-2yrqm)

### Steps to reproduce
Click Go!

### What is expected?
Tooltip move with animation

### What is actually happening?
Tooltip move immediatly

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | Ubuntu 18.04 |
| Browser | Chrome 73.0.3683.103 |

**Comment by comerc** [comment]
See example of dom-align with useCssTransform http://yiminghe.me/dom-align/examples/simple.html

**Comment by afc163** [comment]
We don't provide Tooltip usage like this, just don't use it this way.

**Comment by comerc** [comment]
Ok, I have Plan B with [popper](https://material-ui.com/components/popper/).

**Comment by comerc** [comment]
Update. It is work fine, if add `overlayStyle: { transition: 'transform 2s' }`. Note, `useCssTransform: true` need also. See example on CodeSandbox.
