### ISSUE TITLE
table组件的rowSelection和title同时设置时，table的横向滚动条位置会发生错误

### ISSUE THREAD

**Issue by shenzhim** [ant-design/ant-design#16912]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdtablebug-psgls)

### Steps to reproduce
https://codesandbox.io/s/antdtablebug-psgls

### What is expected?
rowSelection和title同时设置时，table的横向滚动条位置应该正确显示

### What is actually happening?
rowSelection和title同时设置时，table的横向滚动条位置会发生错误

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome 73 |

**Comment by afc163** [comment]
没发现有什么问题。

**Comment by shenzhim** [comment]
https://psgls.codesandbox.io/
麻烦看下这个链接呢？我这边看到的滚动条是有问题的

**Comment by afc163** [comment]
截个图描述一下。

**Comment by jas0ncn** [comment]
![image](https://user-images.githubusercontent.com/3380894/58746424-a0d54800-8490-11e9-830d-acaf7c412916.png)
这个？

**Comment by afc163** [comment]
Chrome 下还真有这个 bug ...

**Comment by afc163** [comment]
感觉是浏览器 bug，不太好修。

**Comment by afc163** [comment]
把 https://github.com/ant-design/ant-design/blob/19ae35f21ac37087b3824083447488454137f706/components/table/style/index.less#L274 这行删了就行了，我需要看看有没有副作用。

**Comment by jas0ncn** [comment]
`hidden` 去掉就没有圆角了

**Comment by jas0ncn** [comment]
> `hidden` 去掉就没有圆角了

不对，还是有的，对第一个单元格单独设置了。
