### ISSUE TITLE
Add option to pass closeIcon on Modal component

### ISSUE THREAD

**Issue by diogo-codengage** [ant-design/ant-design#16913]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to custom closeIcon to use another according my design, but now is not a prop, is a const passing by rc-dialog.

### What does the proposed API look like?
Move const closeIcon to prop and set current icon as defaultProp.

**Comment by afc163** [comment]
#16591

**Comment by afc163** [comment]
Supported in #18309
