### ISSUE TITLE
Form.create overwrites original ref.

### ISSUE THREAD

**Issue by rico345100** [ant-design/ant-design#16920]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I made a Form Modal, which used Ant Design's <Form /> and <Modal /> components. I needed to submit the form when click the "ok" button in modal, so to do that, I created ref and assigned it to my form component. However I needed to validate form fields before submit, so I made a function inside of my form component. Note that Form is a child component of Modal, but Modal just renders {children}, so I need to invoke validate function inside of my Form component from parent. I can do that simply: this.formRef.current.handleSubmit, which handleSubmit invokes validating function and literrally invoke submit if everything is fine. However this wasn't worked because after using @Form.create, this.formRef doesn't contain my child object instance, instead whole bunch of new functions related ant design's were exists and also there is no connection to my original ref.

### What does the proposed API look like?
Here is the parent component:

```javascript
class Container extends Component {
	formRef = createRef();

	validateBeforeSubmit() {
		this.formRef.current.handleSubmit();
	}

	render() {
		return (
			...
			<CreateFormModal visible={this.state.modalVisible} ...>
				<MyForm ref={this.formRef} />
			</CreateFormModal>
		);
	}
}
```

And this is my modal. It just renders children and handles buttons of modal:

```javascript
const CreateFormModal = ({ onOk, onCancel, visible, children }) => (
  <Modal title="Create new data" onOk={onOk} onCancel={onCancel} visible={visible}>
    {children}
  </Modal>
);
```

Any finally it's Form component.

```javascript
@Form.create()
class MyForm extends Component {
	...
	handleSubmit(ev) {
		if (ev) {
			ev.preventDefault();
		}

		const { form } = this.props;
		form.validateFields(this.validateFormFields);
	}
	validateFormFields(err) {
		...
	}
}
```

Key point is that MyForm has handleSubmit method, and I want to invoke this from parent container:

```javascript
class Container extends Component {
	formRef = createRef();

	validateBeforeSubmit() {
		this.formRef.current.handleSubmit();		// HERE
	}
```

However it gives me error, because inside of ref is something look like this,

```javascript
cachedBind: {title: {…}, landingUrl: {…}, priority: {…}, date: {…}}
cleanUpUselessFields: ƒ ()
clearField: ƒ ()
clearedFieldMetaCache: {}
context: {}
domFields: {title: true, landingUrl: true, priority: true, date: true}
fieldsStore: FieldsStore {setFieldsInitialValue: ƒ, getAllValues: ƒ, getFieldsValue: ƒ, getFieldValue: ƒ, getFieldsError: ƒ, …}
getCacheBind: ƒ ()
getFieldDecorator: ƒ ()
getFieldError: ƒ ()
getFieldInstance: ƒ ()
getFieldProps: ƒ ()
getFieldValue: ƒ ()
getFieldsError: ƒ ()
getFieldsValue: ƒ ()
getForm: ƒ ()
getRules: ƒ ()
instances: {title: Input, landingUrl: Input, priority: InputNumber, date: RadioGroup}
isFieldTouched: ƒ ()
isFieldValidating: ƒ ()
isFieldsTouched: ƒ ()
isFieldsValidating: ƒ ()
isSubmitting: ƒ ()
onCollect: ƒ ()
onCollectCommon: ƒ ()
onCollectValidate: ƒ ()
props: {onSubmit: ƒ}
recoverClearedField: ƒ ()
refs: {}
renderFields: {}
resetFields: ƒ ()
saveRef: ƒ ()
setFields: ƒ ()
setFieldsInitialValue: ƒ ()
setFieldsValue: ƒ ()
state: {submitting: false}
submit: ƒ ()
updater: {isMounted: ƒ, enqueueSetState: ƒ, enqueueReplaceState: ƒ, enqueueForceUpdate: ƒ}
validateFields: ƒ ()
validateFieldsAndScroll: ƒ ()
validateFieldsInternal: ƒ ()
__isMounted: true
_reactInternalFiber: FiberNode {tag: 1, key: null, elementType: ƒ, type: ƒ, stateNode: {…}, …}
_reactInternalInstance: {_processChildContext: ƒ}
__proto__: ReactClassComponent
```

How do I access my original ref? Seems like there is no way to do that currently. Thanks.

**Comment by zombieJ** [comment]
If you want to get ref after `Form.create`, you can use `wrappedComponentRef` provided by `rc-form`:

```jsx
class CustomizedForm extends React.Component { ... }

// use wrappedComponentRef
const EnhancedForm =  Form.create()(CustomizedForm);
<EnhancedForm wrappedComponentRef={(form) => this.form = form} />
this.form // => The instance of CustomizedForm
```

ref: https://ant.design/components/form/#Form.create(options)
