### ISSUE TITLE
 使用atool-build 报错：Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

### ISSUE THREAD

**Issue by xiaoxiao44443** [ant-design/ant-design#1692]
使用atool-build 报错：Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin

**Comment by benjycui** [comment]
应该是你修改 `webpackConfig` 时不小心把对应的配置删除了。

**Comment by xiaoxiao44443** [comment]
根据快速开始，安装antd-init自动生成的配置，用的demo，只要import css less 就提示，是extract-text-we pack-plugin版本不对么，是antd-init自动install的，新人不懂，卡在这了

**Comment by benjycui** [comment]
Try [cnpm](https://npm.taobao.org/)

**Comment by xiaoxiao44443** [comment]
我找到问题所在，我原先用的nodejs v6.1才报错，卸载了装回v4.4.4就能正常试用了

**Comment by benjycui** [comment]
@sorrycc 兼容 Node.js@6.0 的计划是?

**Comment by sorrycc** [comment]
等 webpack 本身兼容了 node 6 再说，定期(每两周)观察。

**Comment by iboying** [comment]
同样的错误，试着装了6.2稳定版，可以build了

**Comment by sorrycc** [comment]
@iboying 感谢提供信息，6.2 试了下果然没有问题。
