### ISSUE TITLE
DatePicker很大，有没优化方案？

### ISSUE THREAD

**Issue by mtsee** [ant-design/ant-design#16927]
能否推出一个简化版的日历插件，目前的DatePicker真的很重很大，而且配置语言包的时候，还必须要引入moment，moment.js 本来就是很大的一个包加上语言包有166kb，可以考虑有dayjs，推出一个简单版本的日历插件更受欢迎

**Comment by xxyuk** [comment]
@mtsee  https://github.com/iamkun/dayjs/issues/529 Replace Moment.js in Ant Design (Antd) with Day.js (在 Ant Design (Antd) 中使用 Day.js 替换 Moment)
