### ISSUE TITLE
Table header lost border radius in Firefox

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#16933]
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/507615/58789193-24716f00-8620-11e9-9c5f-bdbc58bdb046.png">

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/58875298-bb602900-86fd-11e9-83d4-b6ccdfa4f3f8.png)
我这里是正常的

**Comment by zombieJ** [comment]
> 我这里是正常的

神奇，这边看 Firefox@67.0 是不正常的。

**Comment by afc163** [comment]
@ztplz Firefox 版本和系统版本是多少？

**Comment by ztplz** [comment]
也是 67.0啊
![image](https://user-images.githubusercontent.com/17755202/58881688-44329100-870d-11e9-811e-7b9e287e35b5.png)

**Comment by ztplz** [comment]
系统 10.13
