### ISSUE TITLE
WeekPicker panel not updating if open and the value gets passed as prop

### ISSUE THREAD

**Issue by a-coruble** [ant-design/ant-design#16939]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-m862l](https://codesandbox.io/s/antd-reproduction-template-m862l)

### Steps to reproduce
Render a WeekPicker that is always open
**Click on a date**
Use a button or whatever to change the state of the parent component and pass the value as props of the weekpicker.

### What is expected?
The panel should update to jump to the selected value.

### What is actually happening?
The panel stays on the previously clicked element

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | React 16.2.0 |
| System | MacOS 10.14.5 |
| Browser | Chrome 74.0.3729.169 |

**Comment by a-coruble** [comment]
One solution we found while we wait for the bug to be solved, is to add a prop [here](https://github.com/ant-design/ant-design/blob/8ec38315588e236ac5ac431c3cdca15b83f1b3cb/components/date-picker/WeekPicker.tsx#L171)  : 

`value: pickerValue,`

**Comment by a-coruble** [comment]
By the way, found another bug related to props missing for Calendar inside WeekPicker.
When selecting the months or years with the header bar, the onChange is not triggered.
We can fix it by providing `onChange={this.handleChange}` at the same place as [above](https://github.com/ant-design/ant-design/blob/8ec38315588e236ac5ac431c3cdca15b83f1b3cb/components/date-picker/WeekPicker.tsx#L171)

**Comment by zombieJ** [comment]
Sorry for delay. Since v3 is not in maintain. This issue will be closed. Pls feel free to create new issue if still meet this problem.
