### ISSUE TITLE
关于官网中Checkbox使用方法

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#1693]
## 场景
查看官网Demo
![image](https://cloud.githubusercontent.com/assets/17123400/15242035/4244b542-1926-11e6-999d-dacd46b5bb1a.png)
此写法与Radio使用方法一致 https://github.com/ant-design/ant-design/pull/1029

测试Checkbox新使用方法

运行，控制台报错
![qq 20160513162406](https://cloud.githubusercontent.com/assets/17123400/15242162/2782f27c-1927-11e6-98b3-addb3be899a3.png)

## 版本
antd@0.12.17

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1645#issuecomment-218383842
