### ISSUE TITLE
[site] static SSR with correct title

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#16936]
view-source:https://ant.design/components/steps/#components-steps-demo-progress-dot

<img width="447" alt="image" src="https://user-images.githubusercontent.com/507615/58791168-4bca3b00-8624-11e9-924a-f47a9cde299a.png">

<img width="945" alt="image" src="https://user-images.githubusercontent.com/507615/58791208-5edd0b00-8624-11e9-998e-31e6a884d327.png">

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/58792599-0e1ae180-8627-11e9-82ed-1ec87e264505.png)
这个string里的This变成蓝色的了

**Comment by afc163** [comment]
Could anybody helps?
