### ISSUE TITLE
CheckBox is not checking when click Enter focused

### ISSUE THREAD

**Issue by Firetuy** [ant-design/ant-design#16940]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-iz98l)

### Steps to reproduce
Focus the checkbox by tabbing it, then click enter

### What is expected?
Its supposed to check

### What is actually happening?
Its not checking when focused

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | react 16.0.0 |
| System | Windows 7 Ultimate |
| Browser | Chrome 74 |

**Comment by afc163** [comment]
`<Checkbox />` share same keyboard behavior as native `<input type="checkbox" />` control that you can press <kbd>space</kbd> to check it.

https://codesandbox.io/s/antd-reproduction-template-5b089
