### ISSUE TITLE
Date RangePicker input 2019-06-10,it will display 2019-07-10

### ISSUE THREAD

**Issue by MargaretHsu41** [ant-design/ant-design#16948]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-mode](https://ant.design/components/date-picker-cn/#components-date-picker-demo-mode)

### Steps to reproduce
pick date 2019-06-01 ~ 2019-06-30.then user delete 3,then input 10 , click enter , it will become 2019-07-10

### What is expected?
we can choose to input date,and we can also disable input function or input what whatever user choose

### What is actually happening?
pick date 2019-06-01 ~ 2019-06-30.then user delete 3,then input 10 , click enter , it will become 2019-07-10

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | react |
| System | win10 |
| Browser | Chrome  74.0.3729.131 |

**Comment by Maktel** [comment]
Same as #15353

**Comment by afc163** [comment]
Duplicate of #15353
