### ISSUE TITLE
Table组件首行(某行)固定

### ISSUE THREAD

**Issue by SiroSong** [ant-design/ant-design#16942]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果想在table组件中达到第一行数据或者某一行数据可以像固定表头那样当表向下滑动时固定在表头的下方，有什么方法可以这样设置？

### What does the proposed API look like?
可以设置行的固定属性属性

**Comment by zombieJ** [comment]
这会严重消耗 Table 计算性能，应该不会支持。但是你可以使用 CSS 来实现固定：https://codesandbox.io/s/white-microservice-t4cl4
