### ISSUE TITLE
Can we have option to disable animation in some components?

### ISSUE THREAD

**Issue by hieuhlc** [ant-design/ant-design#16943]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be great if we have option to disable animation or at least customize them in some components such as Tree or Modal.

### What does the proposed API look like?
For example Tree component with prop `animation={false}` will render the tree without CSSMotion component wrapped around it

**Comment by zombieJ** [comment]
Hi, what's the background on don't want the animation?

**Comment by hieuhlc** [comment]
@zombieJ my Tree component have hundreds of item and I don't want to have animation to cost performance of the tree on expand / collapse (this is main reason). Also when the tree expands, it overflows the container's height, which is fine, but the scrollbar keeps changing during the animation. You can see the gif below

![record](https://user-images.githubusercontent.com/4828178/58926363-29940280-8775-11e9-82a0-4de216010fb1.gif)

^ This is minor, not very important.
Thanks for the good work on antd btw.

**Comment by zombieJ** [comment]
Since animation works close with component, make it configurable may not easy at the moment. We may need social Volunteer to help on this.

**Comment by muzea** [comment]
Is it acceptable to add ‘disable animation’ option to ConfigProvider?

**Comment by zombieJ** [comment]
@muzea, I'm OK with it.

**Comment by muzea** [comment]
Is there any good way to measure how much performance will improve after removing the animation? Is there any indicator for the user to measure whether it is worthwhile to remove the animation?

**Comment by zombieJ** [comment]
For above example. The best way is to support virtual list which has been planed in v4.

**Comment by samit4me** [comment]
This would be a great feature to help speed up testing

**Comment by kaiyoma** [comment]
Has there been any work done in this area? Or is there another issue that better tracks the discussion?

I would be interested in a way to easily disable all animations/transitions on all components. The reason is that we run a lot of UI tests (using Cypress) against our app and the Ant component animations cause random errors and test failures. We would like to disable animations, but only for our tests.

**Comment by Aaronius** [comment]
It seems like setting `motion={null}` on the Tree component works. It's not a documented prop, but you can see where it comes into play [here](https://github.com/ant-design/ant-design/blob/832aa81c821b7b5750673b5aacafa39c9978b09c/components/tree/Tree.tsx#L200-L203).
