### ISSUE TITLE
希望Popconfirm组件支持一个disabled的属性

### ISSUE THREAD

**Issue by lhyt** [ant-design/ant-design#16947]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
包住有可能disabled的Button的时候，如果按钮是disabled，点击还会弹出确认框：
```jsx
<Popconfirm
  onConfirm={this.handleConf}
  title="title"
  okText="确定"
  cancelText="取消"
>
  <Button type="danger" icon="delete" loading={deleteing} disabled={isDisabled}>
    删除
  </Button>
</Popconfirm>
```
这样子，就要加个判断，按照条件去掉外面那层Popconfirm，有点麻烦：
```jsx
{!isDisabled? (
  <Popconfirm
    onConfirm={this.handleConf}
    title="title"
    okText="确定"
    cancelText="取消"
  >
    <Button type="danger" icon="delete" loading={deleteing}>
      删除
    </Button>
  </Popconfirm>
) : (
  <Button type="danger" icon="delete" disabled>
    删除
  </Button>
)}
```
如果用的是`visible={!isDisabled}`来控制，那么此时如果不是disabled，不用点都会弹出了，这样子又要额外写state控制，也是麻烦。

**所以希望有一个disabled属性，可以少写这些逻辑**

### What does the proposed API look like?
支持disabled属性，使得点击都不会弹出确认框，最好能透传，连button都不用写disabled了
```jsx
<Popconfirm
  onConfirm={this.handleConf}
  title="title"
  okText="确定"
  cancelText="取消"
  disabled={isDisabled}
>
  <Button type="danger" icon="delete" loading={deleteing} disabled={isDisabled}>
    删除
  </Button>
</Popconfirm>
```

**Comment by afc163** [comment]
可以来个 PR~

**Comment by zombieJ** [comment]
这样？ https://codesandbox.io/s/youthful-bogdan-s6ld8

**Comment by lhyt** [comment]
> 这样？ https://codesandbox.io/s/youthful-bogdan-s6ld8

就是这个效果

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16985
