### ISSUE TITLE
module.exports = exports['default']; missing after v3.11.2

### ISSUE THREAD

**Issue by c19** [ant-design/ant-design#16953]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/c19/antd-bug-reproduce/tree/broken](https://github.com/c19/antd-bug-reproduce/tree/broken)

### Steps to reproduce
git clone https://github.com/c19/antd-bug-reproduce/tree/broken
npm run build
npm run server
open browser and see the runtime error of
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

the root cause is that after antd@3.11.2 all component exports missing:
module.exports = exports['default'];
 

### What is expected?
no error

### What is actually happening?
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | react@16.7.0 |
| System | Mac OS 10.13.6 (17G2208) |
| Browser | Google Chrome 74.0.3729.169 |

---
Checkout working branch to see the difference
https://github.com/c19/antd-bug-reproduce/tree/working

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/58871053-e47bbc00-86f3-11e9-90cc-d556ced860d2.png)
`npm install` failed,  no permission to install this library.

**Comment by zombieJ** [comment]
ref: https://github.com/ant-design/ant-design/issues/16433#issuecomment-492624920
