### ISSUE TITLE
Table set locale emptyText the empty icon lost

### ISSUE THREAD

**Issue by tong233** [ant-design/ant-design#16955]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-bgo6s)

### Steps to reproduce
locale={{ emptyText: "nothing" }}

### What is expected?
高度变小，空状态图标没了

### What is actually happening?
保留原有样式，只改变文本

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
空状态图标是预设在默认的 emptyText 里的，如果需要可以自行去 http://ant.design/components/icon/ 中引入。
