### ISSUE TITLE
webkitRelativePath of each file is empty if directory has dropped into dragger Upload component

### ISSUE THREAD

**Issue by yummyummyummy** [ant-design/ant-design#16956]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
Just create Drop-down style Upload component and just write some log when directory added.

### What is expected?
It should return relative path value.

### What is actually happening?
It is just empty string if it is dropped down. It works fine with selecting folder by clicking.

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.8.10 |
| System | Mac OS 10.13.6 |
| Browser | Chrome 74.0.3729.169 |

**Comment by afc163** [comment]
Fixed in #16426, could you confirm the version of antd you are using?

**Comment by yummyummyummy** [comment]
oh it is 3.16.1.
Thank you for reply and i will close this issue.
