### ISSUE TITLE
CheckableTag in Select

### ISSUE THREAD

**Issue by sujayjakhadi** [ant-design/ant-design#16954]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will add the ability to use CheckableTag  in Select so that user can select one/more options as primary.

### What does the proposed API look like?
An extra attribute in Select Tag

**Comment by afc163** [comment]
You can simply override multiple select tags style to meet your requirement.

**Comment by sujayjakhadi** [comment]
@afc163 How will I be able to attach onClick handler on tags to control select/deselect?
