### ISSUE TITLE
Transfer穿梭框 选中的值可以设置为整个对象而不是key,类似Select 的 labelInValue

### ISSUE THREAD

**Issue by zhengjianghao** [ant-design/ant-design#16967]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
直接获取到选中的对象值，不需要遍历获取。

### What does the proposed API look like?
类似Select 的 labelInValue  设置true的时候 targetKeys 中的值为对象本身

**Comment by zombieJ** [comment]
`labelInValue` 出发点并不是为了获取对象哈~

Select 支持 `labelInValue` 是为了处理异步加载时只有 `value` 没有 `label` 导致显示裸 `key` 的情况。而在 Transfer 里，提供的 item 本身就是全量的，因而不会只有 `value` 没有 `label` 的情况。
从 api 角度看，我们也是倾向能用 `key` 就用 `key`。不过多带上额外的信息。
