### ISSUE TITLE
Cascader 根据自定义的values 数组的长度显示展开的层级

### ISSUE THREAD

**Issue by akalittle** [ant-design/ant-design#16968]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在我使用的场景下:  我希望 用户在点击第一级的时候默认选中第二级和第三级的第一个选择项作为默认项。
但是现在点击第一级。可以设置3级的值。但是只会弹出2级的Cascader。这样就会有点干扰。明明已经显示了3级的值。但是只出现了2级的选择框。

复现这个问题的例子连接
https://codesandbox.io/s/thirsty-chaum-r541t

### What does the proposed API look like?
我觉得这个可以不用多余的API。
就只是根据当前的values 来判断展示的层级。
或者增加一个 `renderLayersFromValues：boolean`的属性就好！
谢谢！

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/60961396-a26f1700-a33e-11e9-835d-7537863a8cc7.png)
`Cascader` 没有`values` 属性把
![image](https://user-images.githubusercontent.com/8358236/60961430-b61a7d80-a33e-11e9-9847-2cda00e1a8d7.png)

https://github.com/react-component/cascader/commit/be3b20a12cac9ed57c65b0fc0ba3947990e4b978#diff-af6343eac544a21d4dce3ee9c3ce19c5R81

看了下代码是当`value`更新时，存在`loadData`则不更新`activeValue` 判断去掉就好了，但是不知道有没有其它什么影响

**Comment by zombieJ** [comment]
close since not an issue in latest version: https://codesandbox.io/s/immutable-lake-h42vp9?file=/index.js
