### ISSUE TITLE
Table组件中column设置了fixed出现空白区域

### ISSUE THREAD

**Issue by YaoKaiPeng** [ant-design/ant-design#16969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/fervent-bardeen-3h723)

### Steps to reproduce
在使用table组件时，会设置fixed来设置右边操作栏固定。
但当数据较少时，出现了空白区域

### What is expected?
希望去除空白区域

### What is actually happening?
当前组件中会出现错误的空白区域

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.9.0 |
| System | windows |
| Browser | Chrome 版本 73.0.3683.86（正式版本） （64 位） |

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-fixed-columns

![](https://gw.alipayobjects.com/zos/antfincdn/z9MjDf3Gee/cd0f9709-eb65-4efc-bfb8-df7e28ad5de1.png)

**Comment by chenmoran** [comment]
在列比较少的情况下，设了列宽也没有生效
