### ISSUE TITLE
TreeSelect、DatePicker组件在iframe中onBlur失效

### ISSUE THREAD

**Issue by DearGaz** [ant-design/ant-design#16963]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
1，在页面中嵌入一个iframe，iframe中含有TreeSelect（除了{key,treeDate: [], style:{ width: 300 } }外，其他属性均采用默认值）和DatePicker组件（属性全部采用默认值）
2，点击TreeSelect/DatePicker，下拉框/日期选择框会展开
3，点击iframe的父页面中的任意元素

### What is expected?
点击iframe的父页面中的任意元素，下拉框/日期选择框正常收起

### What is actually happening?
点击iframe的父页面中的任意元素，下拉框/日期选择框没有收起

| Environment | Info |
|---|---|
| antd | 3.15.2 |
| React | 16.8.8 |
| System | win10 |
| Browser | Chrome 74.0.3729.169（正式版本） （64 位） |

**Comment by afc163** [comment]
这个组件库不可能做到的，你需要在自己的 iframe 解决方案中解决这个问题。
