### ISSUE TITLE
DatePicker defaultValue not work with data from server

### ISSUE THREAD

**Issue by gechaoqing** [ant-design/ant-design#16964]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/JqVNLW?editors=0010](https://codepen.io/anon/pen/JqVNLW?editors=0010)

### Steps to reproduce
1.use setTimeout to simulate getting data from the server
2.set default date to the state
3.get default date from the state and  set the datePicker defaultValue 

### What is expected?
datePicker show the default date which get from the server

### What is actually happening?
datePicker do not show the default date

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.7.0 |
| System | windows 7 |
| Browser | google chrome 73.0.3683.103 (64) |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
