### ISSUE TITLE
Descriptions: add vertical / horizontal layout prop

### ISSUE THREAD

**Issue by ilanus** [ant-design/ant-design#16960]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

<img width="570" alt="Screenshot 2019-06-04 at 16 48 27" src="https://user-images.githubusercontent.com/9677898/58889042-98774a00-86e8-11e9-80d1-1ec683295524.png">

### What problem does this feature solve?
It would be great to control the Descriptions layout vertical, horizontal as It was possible with antd pro v2, now Descriptions have different DOM structure and quite not possible to use vertically just from modifying css

### What does the proposed API look like?

```
<Descriptions vertical>
  ...
</Descriptions>
``` 

or

```
<Descriptions layout="vertical">
  ...
</Descriptions>
```

**Comment by Ryan810** [comment]
<Descriptions>条件渲染显示':'，怎么处理？

**Comment by KovaSs** [comment]
Functional rendering inside <Descriptions render={() => <div>text</div>} /> implemented?

**Comment by ilanus** [comment]
#17330 👍
