### ISSUE TITLE
Transfer穿梭框 选中的值能获取整个对象 而不只是key吗

### ISSUE THREAD

**Issue by zhengjianghao** [ant-design/ant-design#16966]
我怎么获取穿梭框右边的选中值的对象？ 只能更加key 自己遍历吗？希望能提供一个字段设置，类似select的labelInvalue。

我尝试了rowKey={record => record} 但是会报 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

**Comment by crydear** [comment]
key值的类型为string，所以你的record可以转为json字符串格式就好，用的时候再转回来

**Comment by crydear** [comment]
> 我怎么获取穿梭框右边的选中值的对象？ 只能更加key 自己遍历吗？希望能提供一个字段设置，类似select的labelInvalue。
> 
> 我尝试了rowKey={record => record} 但是会报 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.



> 我怎么获取穿梭框右边的选中值的对象？ 只能更加key 自己遍历吗？希望能提供一个字段设置，类似select的labelInvalue。
> 
> 我尝试了rowKey={record => record} 但是会报 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

key值的类型为string，所以你的record可以转为json字符串格式就好，用的时候再转回来

**Comment by zhuiye** [comment]
> > 我怎么获取穿梭框右边的选中值的对象？ 只能更加key 自己遍历吗？希望能提供一个字段设置，类似select的labelInvalue。
> > 我尝试了rowKey={record => record} 但是会报 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
> 
> > 我怎么获取穿梭框右边的选中值的对象？ 只能更加key 自己遍历吗？希望能提供一个字段设置，类似select的labelInvalue。
> > 我尝试了rowKey={record => record} 但是会报 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
> 
> key值的类型为string，所以你的record可以转为json字符串格式就好，用的时候再转回来

还有其他方案吗?老兄

**Comment by crydear** [comment]
> > > 我怎么获取穿梭框右边的选中值的对象？ 只能更加key 自己遍历吗？希望能提供一个字段设置，类似select的labelInvalue。
> > > 我尝试了rowKey={record => record} 但是会报 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
> > 
> > 
> > > 我怎么获取穿梭框右边的选中值的对象？ 只能更加key 自己遍历吗？希望能提供一个字段设置，类似select的labelInvalue。
> > > 我尝试了rowKey={record => record} 但是会报 Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
> > 
> > 
> > key值的类型为string，所以你的record可以转为json字符串格式就好，用的时候再转回来
> 
> 还有其他方案吗?老兄

当时就是用这种方式解决的，用JSon.stringify和JSon.parse就行，取到了再处理
