### ISSUE TITLE
Can we have a callback function when allowClear button clicked in DatePicker?

### ISSUE THREAD

**Issue by YuFF2018** [ant-design/ant-design#16974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need search with DatePicker value or not, when I clicked allowClear button, I want to get a callback function which I can request new data or do something else in it.

### What does the proposed API look like?
onAllowClear, callback when clicked allowClear button in DatePicker, function(value)

**Comment by afc163** [comment]
Please use `onChange`.

**Comment by YuFF2018** [comment]
I solved my problem used onChange api, thank you for your answer.


------------------------------------------------------------------
发件人：偏右 <notifications@github.com>
发送时间：2019年6月5日(星期三) 15:04
收件人：ant-design/ant-design <ant-design@noreply.github.com>
抄　送：余芬芬 <yufenfen@aidigger.com>; Author <author@noreply.github.com>
主　题：Re: [ant-design/ant-design] Can we have a callback function when allowClear button clicked in DatePicker? (#16974)

Please use onChange.
