### ISSUE TITLE
[Question] Is there an API to get the display text of a form item? I did not find it.

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#16976]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Export file or print can be consistent with the page.

### What does the proposed API look like?
`getFieldDisplay(name): String`

**Comment by afc163** [comment]
Can't understand what you ask for, you can use Chinese to clearify.

**Comment by yoyo837** [comment]
@afc163 🙃  哥，有没有API 能从`form`上的得到显示值 ？ 比如:
```jsx
<Select.Option key={option.key} value={option.key}>
  {option.text}
</Select.Option>
```
里选中项的 `option.text`

**Comment by afc163** [comment]
`option.text` 你不是自己能拿到么？

**Comment by yoyo837** [comment]
它渲染到DOM了，现在源头上从`form.validateFields*`上拿到`formValues`即表单键值对，有没有直接拿显示值的快捷方式？不然只能自己拿着`value`, 判断表单项类型(`Select`, `DataPicker`等)然后自己再转换一遍，比如上面的`option`的`list`里去`find`匹配或者`moment(val)`去`format`

**Comment by afc163** [comment]
建议你自行取用，这不是 form 的职责。

**Comment by yoyo837** [comment]
3Q
