### ISSUE TITLE
Table排序后页数没有回到第一页

### ISSUE THREAD

**Issue by Veigar-C** [ant-design/ant-design#16978]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-greider-3563r)

### Steps to reproduce
点击下一页，然后排序

### What is expected?
排序后onChange的pagination.current为 1

### What is actually happening?
仍为当前页码

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.4.1 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
默认行为。
如果需要跳到第一页，在 `onChange` 里判断一下是否是排序设置一下。

**Comment by Veigar-C** [comment]
现在目前就是这样解决的，但是京东、淘宝这些哪些是筛选排序后仍在当前页面。
你认为排序后仍然是当前页这样合理吗？ @zombieJ

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/c9205f916cb5414ff00f7b11f6df5ec8870c6171/components/table/Table.tsx#L475

我们在 filter 的时候是回到第一页的，我感觉可以统一一下行为。

**Comment by stevenjlho** [comment]
但是这样修改只适合需要服务器端请求数据排序的情况吧，如果只需要在当前页面排序，这样就会造成onChange的时候不知道这个是否是换页操作还是排序操作了吧

**Comment by afc163** [comment]
需要再考虑一下，筛选的时候回到第一页是因为内容可能变少导致当前页没有数据了，排序理论上不会出现这个现象。

**Comment by Veigar-C** [comment]
我认为可以在 Table 或 Col 加个参数，判断是否排序后重置为首页。
例如按价格排序后，数量确实不会少，但是我希望看到的价格正序或倒叙第一的。
不然我在第N页点击排序，然后还要手动切回第一页

**Comment by fengyun2** [comment]
> 我认为可以在 Table 或 Col 加个参数，判断是否排序后重置为首页。
> 例如按价格排序后，数量确实不会少，但是我希望看到的价格正序或倒叙第一的。
> 不然我在第N页点击排序，然后还要手动切回第一页

如何手动切换到第一页呢？

**Comment by zlyyyy** [comment]
能问下现在4.0版本 只想筛选当前页数据，不回到第一页支持吗 @afc163
