### ISSUE TITLE
Divider orientation="center" is not working properly

### ISSUE THREAD

**Issue by francis36012** [ant-design/ant-design#16987]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-galois-no6lp)

### Steps to reproduce
<Divider orientation="center">Test<Divider>

### What is expected?
Style is consistent compared to the other orientation values

### What is actually happening?
Label is below the divider line.

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | latest |
| System | Windows 10 |
| Browser | Chrome |

**Comment by JediahDizon** [comment]
+1
