### ISSUE TITLE
Add the ability to hide a Form Item

### ISSUE THREAD

**Issue by LukeHackett** [ant-design/ant-design#16980]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be nice to be able to toggle the visibility of a form item by toggling a boolean flag, such as **hidden**. By default the value would be false, meaning that is is not hidden.

This would prevent having to wrap the component within an if statement to deduce whether or not the component is visible.

### What does the proposed API look like?
By default, all form items should be visible, e.g:
```
<Form.Item label="Username">
    <Input type="text" />
</Form.Item>
```

Setting the **hidden** prop to true, would hide the form item, e.g:
```
<Form.Item label="Username" hidden={true}>
    <Input type="text" />
</Form.Item>
```

**Comment by afc163** [comment]
```
<Form.Item label="Username" style={{ display: 'none' }}>
    <Input type="text" />
</Form.Item>
```

**Comment by icearith** [comment]
> <Form.Item label="Username" style={{ display: 'none' }}>
>     <Input type="text" />
> </Form.Item>

这样写了, 会影响 validation嘛, 比如说 这个 username 我留空了, 能提交嘛?

**Comment by yoyo837** [comment]
掩耳盗铃，隐藏和没有是两回事

**Comment by dzcpy** [comment]
Is it possible to add a syntax for `<input type="hidden" />`?

**Comment by henryzp** [comment]
@yoyo837 

```jsx
<Form.Item label="Username" noStyle>
    <Input type="text" type="hidden" />
</Form.Item>
```

**Comment by tommyspot** [comment]
> @ yoyo837
> 
> ```js-jsx
> <Form.Item label="Username" noStyle>
>     <Input type="text" type="hidden" />
> </Form.Item>
> ```

It should be:
`<Input type="hidden" />`

Link refer: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#Form_%3Cinput%3E_types

**Comment by diegolego** [comment]
I solved this by passing an "initialValue" yo your "<Form.Item> and passing "noStyle" so that the input is hidden visibly.
If you pass "style={{ display: 'none' }}" instead of the "noStyle prop" the input value will never be posted

```
<Form.Item 
       name={[name, 'eslabon_db_key']} 
       noStyle
       initialValue={'your_hidden_value'}
>
      <Input type="hidden"></Input>
</Form.Item>
```

**Comment by salchichongallo** [comment]
This works for me:
```jsx
<Form initialValues={{ token: 'foo' }}>
  <Form.Item hidden name="token">
    <Input type="hidden" />
  </Form.Item>
</Form>
```

**Comment by bombillazo** [comment]
thanks @salchichongallo ! Even though we needed a hidden Form.Item and thought we could avoid using a child for it, we still needed to pass something so the warning didn't pop up.

**Comment by daryazata** [comment]
@bombillazo which warning do you have? single tag form.item doesnt help?
