### ISSUE TITLE
wrappedComponentRef is not working with functional components

### ISSUE THREAD

**Issue by halitogunc** [ant-design/ant-design#16999]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/wrappedcomponentref-upzhn)

### Steps to reproduce
- Go to the link
- Click show form button
- Type your name and click OK.

### What is expected?
The instance of Form

### What is actually happening?
It could not get the instance.

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.5 |
| Browser | Chrome: Version 74.0.3729.169 (Official Build) (64-bit) |

---
- I am using fully functional components with new hooks api and trying to validate Form which is inside of a Modal. The weird thing is if I use withRef which is deprecated instead of wrappedComponentRef, it is working. 
- I have added both of the cases to the example.

**Comment by zombieJ** [comment]
https://reactjs.org/docs/hooks-faq.html#can-i-make-a-ref-to-a-function-component
