### ISSUE TITLE
Is a problem in working resizable dynamical table when the first column has status fixed left 

### ISSUE THREAD

**Issue by froii** [ant-design/ant-design#16992]
Case - i have a dynamical table with resizable columns and fixed the first column.
1 problem - if i have fixed 1 column it means that antd create two tables and use visibility: hidden to hide the first column - but  it is for use width in the table for cloning fixed column / but if i change quantity of columns to 2 i can see situation where the hidden column has half-width from 100% width of table ... but my first column has static width - so i have an empty area

i think it is not good things but the table is bad changing in css and have a lot problem..
i prefer to use div without table structure / but maybe you can fixe or give me some information about these cases.

Thank you 

![image](https://user-images.githubusercontent.com/20191368/59013487-beb0fd00-8842-11e9-94ce-05c15cc1068e.png)

**Comment by froii** [comment]
i have two variant - change width of columns after all dynamic changes or changes width of the first column on static
it will be working but i think it is not a good way - will be better if both first columns have similar dynamic width 

Also Is a problem in working resizable table when the first column has status fixed left.
 .ant-table-scroll table  width: auto doesn`t give me change the size of table. But if i change if on 100%e 
everything is working - without previous situation

**Comment by LidiaRamirez** [comment]
I am in the same solution, did you find any solution?

**Comment by LidiaRamirez** [comment]
I'm in the same situation, did you find any solution?
