### ISSUE TITLE
使用Menu菜单，嵌套Dropdown之后出现的事件BUG

### ISSUE THREAD

**Issue by YaoKaiPeng** [ant-design/ant-design#16991]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/intelligent-haslett-lnspj)

### Steps to reproduce
点击菜单下dropDown会展开下拉菜单，点击下拉菜单后会触发menu的事件

### What is expected?
希望下拉菜单中的事件独立

### What is actually happening?
目前的情况会出现触发上级menu的事件，自身dropDown的菜单事件没有被触发

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.9.0 |
| System | windows |
| Browser | Chrome 版本 73.0.3683.86（正式版本） （64 位） |

**Comment by zombieJ** [comment]
* 不要将同一个 `menu` 重复插入 jsx 中。
* 使用 `stopPropagation` 阻止冒泡。
ref: https://codesandbox.io/s/zen-mcnulty-w2hk5
