### ISSUE TITLE
table body with small and bordered has unnecessary margin

### ISSUE THREAD

**Issue by Wyntau** [ant-design/ant-design#16990]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-wilson-xkdqf)

### Steps to reproduce
```
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import { Table } from "antd";

const columns = [
  {
    title: "Name",
    dataIndex: "name",
    key: "name",
    width: 150
  },
  {
    title: "Age",
    dataIndex: "age",
    key: "age",
    width: 70
  },
  {
    title: "Address",
    dataIndex: "address",
    key: "address"
  }
];

const data = [];
for (let i = 1; i <= 5; i  ) {
  data.push({
    key: i,
    name: "John Brown",
    age: `${i}2`,
    address: `New York No. ${i} Lake Park`
  });
}

class Demo extends React.Component {
  render() {
    return (
      <Table
        size="small"
        bordered
        pagination={false}
        dataSource={data}
        columns={columns}
      />
    );
  }
}

ReactDOM.render(<Demo />, document.getElementById("container"));

```

### What is expected?
当 small 和 bordered 同时使用时, 表格行前后没有多余的margin

### What is actually happening?
当 small 和 bordered 同时使用时, 表格行前后出现多余的margin
![image](https://user-images.githubusercontent.com/2631733/59001910-0afc3d00-8843-11e9-97db-268245aa3ec0.png)

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.9.0 |
| System | OS X 10.14.5 |
| Browser | Chrome 74.0.3729.169 |

**Comment by afc163** [comment]
It is by designed.
