### ISSUE TITLE
架构建议

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#17]
1. 目前 markdown 写 js 十分不方便，希望抽取为单独的 js 里写
2. 希望网站能够用 react-router 做成单页面，这样后续响应快
3. 目前 watch 很多坑，经常构建文件不更新，建议用 middleware 内存构建

**Comment by afc163** [comment]
1. 考虑下
2. 没精力...

**Comment by warmhug** [comment]
第一条顶下，现在要两个地方复制demo文件，很不方便

**Comment by afc163** [comment]
middleware 搞过，没调通，@yiminghe 来个 PR？

**Comment by yiminghe** [comment]
nico server 不会搞啊，

如果本地有个 webpack.dev.config.js，搞下就行了

https://github.com/yiminghe/learning-react/blob/master/server.js#L11

**Comment by afc163** [comment]
3. 应该已经解决了。
