### ISSUE TITLE
table的分页器pagination能否支持自定义

### ISSUE THREAD

**Issue by xiaofeizao1996** [ant-design/ant-design#17019]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd提供的分页器。在不设置total时会获取数据后自动设置。然后无法点击下一页。

### What does the proposed API look like?
pagination支持ReactNode

**Comment by xiaofeizao1996** [comment]
我知道可以在table外面加自定义的分页。但是感觉会比较难看。此外pagination在获取第一次数据以后好像会自动设置total。麻烦你了，谢谢。

**Comment by zombieJ** [comment]
Pagination 提供了有限的自定义内容 `itemRender`，如果需要更自由的就只能像你自己提到的，自己搞个分页自行实现逻辑了。
