### ISSUE TITLE
<Menu.Item /> throws "Unable to find node on an unmounted component"

### ISSUE THREAD

**Issue by Robertmw** [ant-design/ant-design#17015]
Hello,

I'm porting my app to React 16.x and i saw that using `React.lazy` will make `Menu.Item` throw  

> Uncaught Invariant Violation: Unable to find node on an unmounted component

 whenever I try to navigate.  I know for sure that is something related to `React.lazy` because I reverted the imports and couldn't reproduce the problem anymore.

Versions:
- react: 16.8.6
- antd: 3.19.2

Stack trace:
![image](https://user-images.githubusercontent.com/7315642/59158656-098e7700-8ac6-11e9-8a92-77fe4cd0de0e.png)

**Comment by tanwei0425** [comment]
请问解决了吗
