### ISSUE TITLE
标题太长就看不见了  需要修改源码才行

### ISSUE THREAD

**Issue by miaozilong** [ant-design/ant-design#17017]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gist.github.com/miaozilong/e5d338da3ddfc2ffd6dbd498adc22577](https://gist.github.com/miaozilong/e5d338da3ddfc2ffd6dbd498adc22577)

### Steps to reproduce
将 defaultSettings.ts 中的title改成很多字  

### What is expected?
页面看到标题

### What is actually happening?
看不到标题

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 所有 |
| System | 所有 |
| Browser | 所有 |

**Comment by afc163** [comment]
You should report this to Ant Design Pro issues.

**Comment by miaozilong** [comment]
![image](https://user-images.githubusercontent.com/3994941/59161223-9eb75d00-8b12-11e9-812e-74740056e7d9.png)
