### ISSUE TITLE
获取指定年份的国家法定节假日

### ISSUE THREAD

**Issue by sunshaobin** [ant-design/ant-design#17014]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以根据节假日信息设计合理的课表

### What does the proposed API look like?
getHolidays(year){
//返回输入年份的所有法定节假日
}

**Comment by afc163** [comment]
这不是组件库的职责。

**Comment by sunshaobin** [comment]
> 这不是组件库的职责。

好的，谢谢回复

**Comment by afc163** [comment]
可以试试 https://www.npmjs.com/package/cn-holiday 和 https://www.npmjs.com/package/holiday-cn

**Comment by afc163** [comment]
- https://www.npmjs.com/package/is-chinese-holiday
- https://www.npmjs.com/package/chinese-holiday

**Comment by sunshaobin** [comment]
> * https://www.npmjs.com/package/is-chinese-holiday
> * https://www.npmjs.com/package/chinese-holiday
好的，好的，非常感谢，我来尝试一下
