### ISSUE TITLE
Heading tags do not show in correct relative sizes inside Layout Content

### ISSUE THREAD

**Issue by bassambst** [ant-design/ant-design#17018]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6wrbr)

### Steps to reproduce
1- Create a simple Layout with Content components.
2- Add h1, h2 and h3 into it. 

### What is expected?
Correct heading sizes which should relevant to the ones outside the Layout,

### What is actually happening?
Wrong sizes of heading texts

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | React 16.9.0 |
| System | Windows 10 Home x64 |
| Browser | Chrome Version 75.0.3770.80 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
It's from Chrome `user agent stylesheet`. If you want to use antd styled Heading, please use Typography.Title instead: https://codesandbox.io/s/antd-reproduction-template-ol9nh
