### ISSUE TITLE
Get Tree object when on its child TreeNode

### ISSUE THREAD

**Issue by qiluo** [ant-design/ant-design#17012]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I've created some Trees by array iteration, and I've listened to onCheck with same callback. The code looks like
```
{_.map(trees, (treeData, index) => {
            return (
              <Col span={4} key={index}>
                <Tree checkable={true} defaultExpandAll={true} onCheck={this.onTreeCheck} checkedKeys={this.state.checkedKeys}>
                  <TreeNode>
                    ...
                  </TreeNode>
                </Tree>
              </Col>
            );
          })}
```

I need to identify which tree was checked in `this.onTreeCheck`, but I've just found nothing to get tree object. What I've got was all about TreeNode.

Is there any way or it's a missed feature?

### What does the proposed API look like?
Add something like parentTree in event object of onCheck

**Comment by zombieJ** [comment]
You should get tree data by your logic own. No need from tree event:
```jsx
{_.map(trees, (treeData, index) => {
  return (
    <Col span={4} key={index}>
      <Tree
        checkable={true}
        defaultExpandAll={true}
        onCheck={(...args) => {
          // `treeData` is on your own here
          this.onSomeLogic(treeData, ...args);
        }}
        checkedKeys={this.state.checkedKeys}
     >
        <TreeNode>
          {/* some logic */}
        </TreeNode>
      </Tree>
    </Col>
  );
})}
```

**Comment by qiluo** [comment]
I meant the tree component object, not the treeData

**Comment by zombieJ** [comment]
Just `ref` it.

```jsx
<Tree
  ref={(node) => {
    this.treeNodes[index] = node;
  }}
/>
  ...
</Tree>
```

PS: Please reconsider your code logic. In most case, get a tree node instance is not necessary.
