### ISSUE TITLE
useState is not working with antd table

### ISSUE THREAD

**Issue by minhyeong-jang** [ant-design/ant-design#17023]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/17022](https://github.com/ant-design/ant-design/issues/17022)

### Steps to reproduce
```js
const [stockEdit, setStockEdit] = useState({
    key: "",
    value: ""
});
...
console.log(stockEdit); // { key: "changeKey", value: "changeValue" }
const columns = [{
      title: "asd",
      dataIndex: "",
      align: "center",
      key: "stockCount",
      width: 70,
      render: row => {
        console.log(stockEdit); // console.log({key: "", value: ""}
     }
}];
const updateStock = props => {
  setStockEdit(key: "changeKey", value: "changeValue");
}
...
console.log(stockEdit);  // console.log({key: "changeKey", value: "changeValue"}
```
### What is expected?
Why Hooks not working in antd table??

When I tried setStockEdit(key: "changeKey", value: "changeValue");,
Rendering is success. but only not work antd table.

Why not change stockEdit in columns render?

### What is actually happening?
state is not work in antd table

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | react 16.8.6 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
又不会自动关闭了 @yesmeck

**Comment by yoyo837** [comment]
`<Table columns={columns()} />`

```js
columns = () => ([{
   title: "asd",
      dataIndex: "",
      align: "center",
      key: "stockCount",
      width: 70,
      render: row => {
        console.log(stockEdit); // console.log({key: "", value: ""}
     }
}])
```
