### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by nxycdl** [ant-design/ant-design#1702]
node-v
v5.10.0
npm -v
3.8.3
antd-init -v
1.0.1
操作系统 win10 64位在执行demo前面几部都没有报错，最后一步 npm run dev
提示以下错误，不知道哪个大侠知道。

D:\project\antdesign\antdemo>npm run dev
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3

npm ERR! missing script: dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\project\antdesign\antdemo\npm-debug.log

**Comment by afc163** [comment]
`tnpm start`

antd-init 那边改掉了。
