### ISSUE TITLE
IE 浏览器下，Modal模态框closable=true内有Table组件，Table支持输入页码跳转，输入页码回车，Modal关闭

### ISSUE THREAD

**Issue by zzzzxiao** [ant-design/ant-design#17027]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://bigdata.cegn.cn](http://bigdata.cegn.cn)

### Steps to reproduce
1，点击详情按钮，弹出Modal弹框，弹框内展示Table数据列表。
2，弹框右上角有关闭按钮，Table组件showQuickJumper=true，
3，IE10（IE10一下所有版本）下输入页码，触发Modal关闭事件，
4，目前解决办法须修改源码，以下代码的<button>改为其他元素，
<button aria-label="Close" class="ant-modal-close"><span class="ant-modal-close-x"><i class="anticon anticon-close ant-modal-close-icon"><svg viewBox="64 64 896 896" class="" data-icon="close" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M563.8 512l262.5-312.9c4.4-5.2.7-13.1-6.1-13.1h-79.8c-4.7 0-9.2 2.1-12.3 5.7L511.6 449.8 295.1 191.7c-3-3.6-7.5-5.7-12.3-5.7H203c-6.8 0-10.5 7.9-6.1 13.1L459.4 512 196.9 824.9A7.95 7.95 0 0 0 203 838h79.8c4.7 0 9.2-2.1 12.3-5.7l216.5-258.1 216.5 258.1c3 3.6 7.5 5.7 12.3 5.7h79.8c6.8 0 10.5-7.9 6.1-13.1L563.8 512z"></path></svg></i></span></button>

### What is expected?
IE浏览器下，输入页码跳转，不触发Modal关闭

### What is actually happening?
IE浏览器下，输入页码跳转，Modal关闭

| Environment | Info |
|---|---|
| antd | 3.10.1 |
| React | react@16.6.3 |
| System | windows7 |
| Browser | IE10 |

**Comment by zzzzxiao** [comment]
由于这个项目是内部项目看不了源码，我截图展示
![image](https://user-images.githubusercontent.com/5946172/59190922-9ada1800-8bb0-11e9-949b-3cc312bd4717.png)
IE下，输入页码，回车，弹框关闭

**Comment by zzzzxiao** [comment]
https://github.com/zzzzxiao/myTestProject

**Comment by zzzzxiao** [comment]
@afc163 如果可以复现并且确定这个一个bug麻烦回复一下，谢谢了

**Comment by afc163** [comment]
可以帮忙排查么，手头没有 IE10

**Comment by zzzzxiao** [comment]
> 可以帮忙排查么，手头没有 IE10

原因找到了：IE下面，当你在input内敲回车时，IE会自动寻找第一个button标签并且触发它。恰好你们的Modal右上角的关闭按钮用看button包裹，
![image](https://user-images.githubusercontent.com/5946172/59247797-1d1b1880-8c53-11e9-80c2-9742f2d7ccf2.png)
所以，回车相当于触发了button的click事件，模态框关闭。

**Comment by afc163** [comment]
https://github.com/react-component/dialog/pull/120

**Comment by afc163** [comment]
在 rc-dialog@7.4.1 里修复了，试试升级 antd 到最新并且重新安装 node_modules。

**Comment by zzzzxiao** [comment]
@afc163 Thank you very much !!!

**Comment by zzzzxiao** [comment]
@afc163 另外的问题出现了，IE下面不会关闭弹框了 但是页面跳转事件触发不了了，麻烦仔细测试一下IE哇

**Comment by afc163** [comment]
我没有 IE 可以测试，帮忙排查吧。

**Comment by zzzzxiao** [comment]
@afc163 我正在排查，只是估计进度很慢，还是要麻烦你们在IE下排查一下页面跳转事件（类似的表单回车提交事件），我们本地的代码已经编译过了，查找源代码很难发现问题，麻烦咯
