### ISSUE TITLE
work with Jest

### ISSUE THREAD

**Issue by yanlee26** [ant-design/ant-design#17024]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/facebook/jest/issues/7957](https://github.com/facebook/jest/issues/7957)

### Steps to reproduce
yarn test

### What is expected?
pass

### What is actually happening?
fail

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.x |
| System | macOS |
| Browser | chorme 74 |

**Comment by yanlee26** [comment]
I fixed it by updating my CRA to `  "react-scripts": "^3.0.1",`

**Comment by crazylxr** [comment]
这个 pr 合了吗？我也遇到这个问题了，但是我没用 create-react-app，不知道怎么修复

**Comment by fobbyal** [comment]
@crazylxr 你試試
···
       [
            "import",
            {
                "libraryName": "antd",
                "libraryDirectory": "lib",
                "style": "css"
            }
        ]
···
