### ISSUE TITLE
Upload控件返参为xls二进制文件，怎么设置 responseType:  'blob'，并下载？

### ISSUE THREAD

**Issue by zhangyuanliang** [ant-design/ant-design#17033]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[no](http://new-issue.ant.design)

### Steps to reproduce
no

### What is expected?
Upload控件上传后返参为xls二进制文件，怎么设置 responseType: 'blob'并下载？

### What is actually happening?
Upload控件上传后返参为xls二进制文件，下载文件打开格式是乱的。
```
 downLoadFile (blob, fileName) {
    if (window.navigator.msSaveOrOpenBlob) {
        navigator.msSaveBlob(blob, fileName);
    } else {
        let link = document.createElement('a');
        link.style.display = 'none';
        link.href = URL.createObjectURL(blob); //创建一个指向该参数对象的URL
        link.download = fileName;
        link.click(); // 触发下载
        URL.revokeObjectURL(link.href); // 释放通过 URL.createObjectURL() 创建的 URL
    }
  }

  if (info.file.status === 'done') {
     message.success(‘文件上传成功’);
     const res = info.file.response
     let blob = new Blob([res], {type: ’application/vnd.ms-excel‘}); // 将服务端返回的文件流excel文件
     let fileName = “车检报告.xls”; // 保存的文件名
     this.downLoadFile(blob, fileName); 
   } else if (info.file.status === 'error') {
      message.error(“文件上传失败”);
   }
```

> 不好意思有点乱

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | react |
| System | mac os |
| Browser | Chrome  |

**Comment by zombieJ** [comment]
封装的 upload 方法如果不满足需求，可以自己实现上传方法：https://ant.design/components/upload-cn/#components-upload-demo-upload-manually

**Comment by hooljun** [comment]
have u solved it?

**Comment by 510846** [comment]
> have u solved it?

`beforeUpload` can help you ~

**Comment by fanyuzzz** [comment]
解决了没有，我也碰到了同样的问题

**Comment by 984958198** [comment]
> 封装的 upload 方法如果不满足需求，可以自己实现上传方法：https://ant.design/components/upload-cn/#components-upload-demo-upload-manually

这个办法太笨了，好像将responseType: 'blob'设置到请求中就行，怎么设置不清楚
