### ISSUE TITLE
Generate ColumnGroup by config

### ISSUE THREAD

**Issue by mnikn** [ant-design/ant-design#17037]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In Table docs, it provides "JSX" style API to wrap columns with ColumnGroup, but is it possible to provide "config" style to auto-generate ColumnGroup and wrap columns?

### What does the proposed API look like?
I think the api would look like:
```jsx
const columns = [{
    title: 'column1',
    group: 'g1',
}, {
    title: 'column2',
    group: 'g1',
}, {
    title: 'column3',
    group: 'g2',
}, {
    title: 'column4',
}];
const columnGroups = [{
    title: 'group1',
    key: 'g1'
}, {
    title: 'group2',
    key: 'g2'
}];
return <Table columns={columns} columnGroups={columnGroups}>
```

It should be same as:
```jsx
<Table>
    <ColumnGroup title="group1">
      <Column title="column1" />
      <Column title="column2" />
    </ColumnGroup>
    <ColumnGroup title="group2">
      <Column title="column3" />
    </ColumnGroup>
    <Column title="column4" />
</Table>
```

**Comment by zombieJ** [comment]
We have another thinking about grouping. Please check here #16911

**Comment by hugomn** [comment]
Is this supported in ant 4.0? Could not find anything in the docs.
