### ISSUE TITLE
Upload组件如何指定上传method为post

### ISSUE THREAD

**Issue by lynshir** [ant-design/ant-design#17047]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在Upload组件自动上传action的Request Method是OPTIONS,之前后端已存在上传接口且支持的方法是post，这样前端只需要指定一下method就可以了

### What does the proposed API look like?
上传时可以指定request method为post

**Comment by afc163** [comment]
是 `post` https://github.com/react-component/upload/blob/d228dde5aa34acf0a811a9cf6ade3572ed37807b/src/request.js#L71

你可能需要了解一下 `preflight request`：https://www.jianshu.com/p/b55086cbd9af

**Comment by yezongyang** [comment]
按道理这是简单请求吧，不会出现OPTIONS method, 但是我依然出现了。。。

**Comment by yoyo837** [comment]
是否涉及跨域？

**Comment by yezongyang** [comment]
@yoyo837  是因为onProgress，ajax监听上传进度，会发OPTIONS请求
