### ISSUE TITLE
antdesign select 设置了value。然后allowclear就无法清除了

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#17044]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
点击右侧的allowclear。无法清除select内的值。

### What is expected?
清除select内的值。

### What is actually happening?
没有清除select内的值。

| Environment | Info |
|---|---|
| antd | 3.11.1 |
| React | 16 |
| System | 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
建议理解一下受控组件的概念： https://reactjs.org/docs/forms.html#controlled-components
