### ISSUE TITLE
support custom style and width for ant-tabs-ink-bar in Tabs (The underline border) 

### ISSUE THREAD

**Issue by alirezavalizade** [ant-design/ant-design#17053]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
add custom width or style
https://codesandbox.io/s/exciting-euler-9mejc

### What does the proposed API look like?
https://codesandbox.io/s/exciting-euler-9mejc

**Comment by zombieJ** [comment]
You can override the style by css: https://codesandbox.io/s/mystifying-hooks-pctjy

**Comment by alirezavalizade** [comment]
can you please try width property also? :) @zombieJ

**Comment by alirezavalizade** [comment]
![image](https://user-images.githubusercontent.com/14992757/59346977-d04b4680-8d13-11e9-897e-dd34ffe79784.png)

**Comment by zombieJ** [comment]
Like this? https://codesandbox.io/s/spring-cherry-zq5yi

**Comment by alirezavalizade** [comment]
yeah buddy, thanks

**Comment by vlma98** [comment]
For anyone still having trouble to overwrite antd css rules in a global stylesheet, remember to import "antd/dist/antd.css" before index.css

**Comment by jash2810** [comment]
> Like this? https://codesandbox.io/s/spring-cherry-zq5yi

This worked for me! thanks.

**Comment by Musobek99** [comment]
__

**Comment by christophermetrikus** [comment]
None of the solutions above provide a way of changing the long grey bar.

Is there a way of achieving this?

**Comment by christophermetrikus** [comment]
Worth adding that if you wish to get rid of the grey bar beneath the active tab, below is the CSS/SASS for this:
```
.tabsContainerDefault {
  :global {
    .ant-tabs-nav {
      &:before {
        border: none;
      }
    }
  }
}
```

**Comment by Mrezagolbaba** [comment]
This is a custom `TabComponent` built using Ant Design's `Tabs` component and SCSS for custom styling. The component accepts an array of tabs with labels and children and allows for active tab management.

## Code

### React Component

```tsx
import React, { useState } from 'react';
import { Tabs } from 'antd';
import style from './styles.module.scss';

const { TabPane } = Tabs;

interface CustomTabsProps {
  tabs: { key: string; label: string, children: [] }[];
  onTabChange: (index: number) => void;
}

const TabComponent: React.FC<CustomTabsProps> = ({ tabs, onTabChange }) => {
  const [activeKey, setActiveKey] = useState<string>('0');

  const handleTabChange = (key: string) => {
    // Add logic to handle tab change
  };

  return (
    <div className={style.container}>
      <Tabs 
        activeKey={activeKey} 
        items={tabs} 
        onChange={handleTabChange} 
        aria-label="custom tabs" 
      />
    </div>
  );
};

export default TabComponent;
```


### SCSS for Custom Tab Styling

This SCSS code customizes the appearance of the Ant Design tabs. It modifies the active tab color, ink bar, and hover/focus states using a custom `--primaryColor` variable.

```scss
.container {
  :global {
    .ant-tabs-nav {
      .ant-tabs-nav-wrap {
        .ant-tabs-tab-active div {
          color: var(--primaryColor); // Custom color for active tab
        }
        .ant-tabs-ink-bar {
          height: 2px;
          background-color: var(--primaryColor); // Custom color for the ink bar
        }
        .ant-tabs-tab:hover {
          color: var(--primaryColor); // Custom color for hover state
        }
        .ant-tabs-tab:focus-visible {
          color: var(--primaryColor); // Custom color for focus-visible state
        }
      }
    }
  }
}
