### ISSUE TITLE
The Modal will change the body style when I set body style!

### ISSUE THREAD

**Issue by ElvenYao** [ant-design/ant-design#17050]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
(https://codesandbox.io/s/weathered-leftpad-cqmyx)

### Steps to reproduce
1.在设置```<body style="overflow-y: hidden;">...</body>```
2.设置布局
```
      <Layout style={{ minHeight: "100vh" }}>
        <HeaderArea />
        <Layout style={{ minHeight: "100vh" }}>
          <SiderArea />
          <Layout>
            <ContentArea />
          </Layout>
        </Layout>
      </Layout>
```
3.使用modal组件
4.页面的滚动条出现

1. set body ```<body style="overflow-y: hidden;">...</body>```
2. set Layout 
```
      <Layout style={{ minHeight: "100vh" }}>
        <HeaderArea />
        <Layout style={{ minHeight: "100vh" }}>
          <SiderArea />
          <Layout>
            <ContentArea />
          </Layout>
        </Layout>
      </Layout>```
3. use Modal component
4.the overflow show.

### What is expected?
隐藏的滚动条不会出现(The hidden overflow have be not show)

### What is actually happening?
隐藏的滚动条出现(The hidden overflow have be show)

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | react 16.8.6 |
| System | window 10 |
| Browser | chrome |

---
我需要一个布局，头部和左侧边栏固定，只有右侧的内容可以展示，并且可以滚动。所以我用了上面的布局。我使用到modal后会出现隐藏的滚动轴


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by ElvenYao** [comment]
https://codesandbox.io/s/weathered-leftpad-cqmyx
I create a mini project on codesandbox, but I can't set the body property. So how can I hidden the body overflow in this code

**Comment by ElvenYao** [comment]
At the same time. I want not show the body overflow when I use Modal

**Comment by MarschHuynh** [comment]
@ElvenYao Your Reproduction seem wrong.

Mine: https://codesandbox.io/s/antd-reproduction-template-4vjwj
