### ISSUE TITLE
按需 babel-plugin-import 导致打包后的部分页面丢失css/直接白屏

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design#17056]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design](https://ant.design)

### Steps to reproduce
.babelrc
![image](https://user-images.githubusercontent.com/23191825/59326931-a9444300-8d1a-11e9-8055-f192f72afbe7.png)
webpack.base.babel.js
![image](https://user-images.githubusercontent.com/23191825/59326963-beb96d00-8d1a-11e9-940a-803221062eed.png)
Webpack Bundle Analyzer
![image](https://user-images.githubusercontent.com/23191825/59327055-004a1800-8d1b-11e9-87d7-dd71e4ee442a.png)

### What is expected?
可以使用 babel-plugin-import 按需加载

### What is actually happening?
如果不用babel-plugin-import ，打包后是正常的

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | ^16.4.0 |
| System | Windows 10 |
| Browser | Google Chrome 75.0.3770.80 |

**Comment by zheng1013757145** [comment]
这个没办法提供实例，我这边配置上babel-plugin-import，部分页面是白屏，没有任何错误显示
![image](https://user-images.githubusercontent.com/23191825/59331427-8586fa00-8d26-11e9-97ab-f1e273a538b4.png)
开发一切都是正常的，打包后出现少部分组件没有定义
![image](https://user-images.githubusercontent.com/23191825/59331676-165dd580-8d27-11e9-8748-3f773a4bd3d7.png)

**Comment by zombieJ** [comment]
没有重现就没法看是什么问题了……

**Comment by zheng1013757145** [comment]
`{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
    "react",
    "stage-0",
  ],
  "env": {
    "production": {
      "only": ["app"],
      "plugins": [
        "transform-react-remove-prop-types",
        // "transform-react-constant-elements",
        // "transform-react-inline-elements"
      ],
    },
    "test": {
      "plugins": ["transform-es2015-modules-commonjs", "dynamic-import-node"]
    }
  },
  "plugins": [["import", {
    "libraryName": "antd",
    "style": "css",
  }], "transform-decorators-legacy"]
}
`
注释掉两个plugins，就正常了，babel-plugin-import 和 上述插件不兼容。

**Comment by zheng1013757145** [comment]
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ],
    "react",
    "stage-0",
  ],
  "env": {
    "production": {
      "only": ["app"],
      "plugins": [
        "transform-react-remove-prop-types",
        // "transform-react-constant-elements",
        // "transform-react-inline-elements"
      ],
    },
    "test": {
      "plugins": ["transform-es2015-modules-commonjs", "dynamic-import-node"]
    }
  },
  "plugins": [["import", {
    "libraryName": "antd",
    "style": "css",
  }], "transform-decorators-legacy"]
}
注释掉上面两个插件，就好了。 
react-redux-boilerplate配置的插件貌似和babel-plugin-import不兼容

**Comment by zombieJ** [comment]
@zheng1013757145，方便给个 github 地址吗？

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-import/issues/42
https://github.com/ant-design/babel-plugin-import/issues/47
https://github.com/ant-design/babel-plugin-import/issues/64

不兼容的，不要同时使用。
