### ISSUE TITLE
bordered 的表格在应用 #16950 的修改后 头部边框不能对齐

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#17051]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/spring-pine-7dzht)

### Steps to reproduce
https://github.com/ant-design/ant-design/pull/16950#issuecomment-500825220

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest |

**Comment by zombieJ** [comment]
<img width="510" alt="屏幕快照 2019-06-12 上午10 59 16" src="https://user-images.githubusercontent.com/5378891/59320488-2498fb00-8d01-11e9-967b-c7966747d4b4.png">

cc @afc163

**Comment by afc163** [comment]
蛋疼极了

**Comment by yoyo837** [comment]
我之前的一个评论里面提到过用过的一个奇葩方法：body定高的表格先用一个非拆分表头的表格添加到dom后计算宽度列款复制表头作为一个遮挡的显示用表头。

**Comment by afc163** [comment]
在 rc-table@6.6.1 里修复了，本地重新安装 node_modules 就行了。

**Comment by yoyo837** [comment]
一样的还是错位呐...

![image](https://user-images.githubusercontent.com/6134547/59322674-ddfbce80-8d09-11e9-8088-0474bfb0675a.png)

**Comment by afc163** [comment]
截图看看？我本地试了是好的。

**Comment by yoyo837** [comment]
就和之前一喵一样 🙃 

![image](https://user-images.githubusercontent.com/6134547/59323005-67f86700-8d0b-11e9-91fd-d433267aa387.png)

https://codesandbox.io/s/competent-goodall-mo9wn

**Comment by afc163** [comment]
`rc-table@6.6.2`

**Comment by yoyo837** [comment]
`rc-table@6.6.2` 也不可以，表现一样。

**Comment by afc163** [comment]
再试试 `rc-table@6.6.3`。

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/59333391-cb45c180-8d2a-11e9-8a3f-fd12589ba7b4.png)


![image](https://user-images.githubusercontent.com/6134547/59333428-e1538200-8d2a-11e9-8689-82c8bd85f858.png)

**Comment by afc163** [comment]
你配置是`滚动时`吧？

<img width="707" alt="image" src="https://user-images.githubusercontent.com/507615/59333933-f1b82c80-8d2b-11e9-9f72-04d7787ffa04.png">

**Comment by yoyo837** [comment]
不是

![image](https://user-images.githubusercontent.com/6134547/59334056-3b087c00-8d2c-11e9-8fb7-38c9c43da5cf.png)

**Comment by yoyo837** [comment]
值是16

![image](https://user-images.githubusercontent.com/6134547/59334231-99355f00-8d2c-11e9-9d42-0a4561c2f3f0.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/competent-goodall-mo9wn

这个例子在我本地已经没问题了。

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/507615/59334792-d51cf400-8d2d-11e9-8267-da54176d2fb1.png">

**Comment by yoyo837** [comment]
复制一下多加几列或者动一动配置比如titile使其update一下，不能保持...

图片的重现`rc-table`的三个path 版本我本机应用一直这样，可能就是哪儿多update了一下...我再多试试看能不能给个mini reproduction.

**Comment by yoyo837** [comment]
https://codesandbox.io/s/vigorous-forest-voog6 safari还是不可以，而且不兼容`overflow: x y`的写法

**Comment by afc163** [comment]
> https://codesandbox.io/s/vigorous-forest-voog6 safari还是不可以，而且不兼容overflow: x y的写法

Chrome 可以了是吧？

**Comment by yoyo837** [comment]
Chrome 的效果 上面 https://github.com/ant-design/ant-design/issues/17051#issuecomment-501182746

**Comment by afc163** [comment]
https://codesandbox.io/s/vigorous-forest-voog6 和 之前的https://codesandbox.io/s/competent-goodall-mo9wn 基本是同一个demo

这两个例子在我本地现在都没发现问题，我还漏了什么细节么？

**Comment by yoyo837** [comment]
https://codesandbox.io/s/vigorous-forest-voog6 点一下翻页来触发 https://github.com/ant-design/ant-design/issues/17051#issuecomment-501182746 里说的update

**Comment by yoyo837** [comment]
Safari 也能看到这种情况

![image](https://user-images.githubusercontent.com/6134547/59343489-97749700-8d3e-11e9-9a8a-7bda8e0f75b7.png)

，update一次后（有时候不需要）也能看见

![image](https://user-images.githubusercontent.com/6134547/59343562-bf63fa80-8d3e-11e9-9455-772f2830641c.png)

**Comment by afc163** [comment]
> update一次后

静态上目前没发现有这个东西，搞一个 codesandbox？

**Comment by afc163** [comment]
> update一次后

你说的 update 是不是指的是代码变化后的 HMR？

**Comment by yoyo837** [comment]
我指`rerender`，https://codesandbox.io/s/vigorous-forest-voog6 点一下翻页就看见了很明显呀 🙃

**Comment by afc163** [comment]
我看到了，继续 digging ~

**Comment by afc163** [comment]
rerender 的问题也在 react-component/table@72e84b2 里修复了，`rc-table@6.6.6`。

**Comment by yoyo837** [comment]
前面说的列头缺一块的问题Mac下三大浏览器基本没了。

不过，列较多时列头错位不知道是否与这个有关系，还是说另开issue？

Reproduction link：https://codesandbox.io/s/tender-moon-iwe95

**Comment by afc163** [comment]
https://codesandbox.io/s/wild-sea-h8124

宽度加起来超过表格容器宽度了，你需要设置 `scroll.x` 使其可以横向滚动。

```js
scroll={{ x: 一个合适的宽度 }}
```

或者无脑

```js
scroll={{ x: 'max-content' }}
``

**Comment by yoyo837** [comment]
https://codesandbox.io/s/confident-lewin-2xxyi

假如都设定了列宽，x 设置为列宽的总和，这种方案是否符合下面所说?

>宽度加起来超过表格容器宽度了，你需要设置 scroll.x 使其可以横向滚动。
>`scroll={{ x: 一个合适的宽度 }}`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by afc163** [comment]
另外建议不要写死 width，算起来很麻烦，`max-content` 在高级浏览器环境下很好用。

**Comment by yoyo837** [comment]
好吧，算是回到最早那个情况了，我先启用一些css来解决，期待慢慢完善...

**Comment by LewinJun** [comment]
> 好吧，算是回到最早那个情况了，我先启用一些css来解决，期待慢慢完善...

怎么解决？   头疼，搞这个玩意，设置了scroll  和 column的width就对不齐，  想自己封装了，  后面都不想用框架了

**Comment by yoyo837** [comment]
@LewinJun #13825, https://github.com/ant-design/ant-design/issues/13825#issuecomment-452942830

**Comment by LewinJun** [comment]
> #13825 (comment)

谢谢

**Comment by LewinJun** [comment]
> @LewinJun #13825, [#13825 (comment)](https://github.com/ant-design/ant-design/issues/13825#issuecomment-452942830)

谢谢
