### ISSUE TITLE
 Upload 列表在 disabled 时禁止上传文件，应支持移除已上传文件

### ISSUE THREAD

**Issue by SiminWong** [ant-design/ant-design#17059]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-banzai-rf6in)

### Steps to reproduce
无

### What is expected?
disabled 时禁止上传文件，但可移除已上传文件

### What is actually happening?
disabled 时禁止上传文件和移除文件

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.6 |
| System | macOS |
| Browser | chrome |

---
使用场景：限制上传文件数量

**Comment by afc163** [comment]
Maybe you should discuss with @Veveue. #16786

**Comment by zombieJ** [comment]
不能操作是对的，`disabled` 不应该响应用户交互。
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/disabled

如果要交互且禁止上传，可以参考一下这个例子：https://ant.design/components/upload-cn/#components-upload-demo-picture-card

**Comment by xyy94813** [comment]
使用 `<Upload.Dragger />` 的时候，无法参考 [https://ant.design/components/upload-cn/#components-upload-demo-picture-card](https://ant.design/components/upload-cn/#components-upload-demo-picture-card)
@zombieJ

**Comment by zombieJ** [comment]
感觉可以和这个 #16047 合并一下。

**Comment by missop** [comment]
这个问题解决掉了吗
