### ISSUE TITLE
Mention组件和表单一起使用，怎么@显示名称，提交的时候提交id

### ISSUE THREAD

**Issue by sticks0613** [ant-design/ant-design#17069]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/mention-cn/#components-mention-demo-custom-tag](https://ant.design/components/mention-cn/#components-mention-demo-custom-tag)

### Steps to reproduce
如果webFrameworks数组对象都有id, 怎么@显示name, 提交的时候显示id(配合表单一起使用)

### What is expected?
Mention组件和表单一起使用，怎么@显示名称，提交的时候提交id

### What is actually happening?
实现不了

| Environment | Info |
|---|---|
| antd | 3.10.3 |
| React | react |
| System | windouw |
| Browser | chrome |

**Comment by zombieJ** [comment]
建立一个 Map，在提交时对应替换一下。

另外，Mention 组件已经废弃，建议使用新的 Mentions 组件。
