### ISSUE TITLE
validateFields会直接触发所有组件的检验并且将错误表现出来，实际上很多场景并不需要组件表现错误或立刻表现错误，能否提供一个新的api？

### ISSUE THREAD

**Issue by roft418** [ant-design/ant-design#17074]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
validateFields会直接触发所有组件的检验并且将错误表现出来，实际上很多场景并不需要组件表现错误或立刻表现错误，需要一个新的api，只是拿错误信息的逻辑而不触发表现，这样可以省去组件样式覆盖相关操作的大量代码。

### What does the proposed API look like?
只是拿到错误信息，不触发组件的样式表现就好了哈。🙏🙏🙏

**Comment by zombieJ** [comment]
`validateFields` 拿到错误信息后直接 `setFields` 去掉错误信息即可。

**Comment by roft418** [comment]
@zombieJ 谢谢你提供了另外一种补救的措施👍👍👍。但是这种做法也会导致页面的一次render，如果render里有个组件是根据getFieldsError进行判断，返回值就会被重置为没有报错信息（因为我采用了setFields来补救），还是达不到效果，并没有从根本上解决我的问题。。。
如果有个api返回的错误信息没有副作用就好了。🙏🙏🙏

**Comment by zombieJ** [comment]
@roft418 给个重现我看一下

**Comment by roft418** [comment]
@zombieJ 你好！😊 我写了个例子，在例子里我的按钮状态不对了。这个就是我想问的，能不能给一个不会触发表现的api，这样不用通过覆盖补救。（引起新问题）
[https://codesandbox.io/s/brave-glitter-6j2sj](url)

**Comment by roft418** [comment]
[地址](https://codesandbox.io/s/brave-glitter-6j2sj)

**Comment by zombieJ** [comment]
提供一下：操作步骤，预期效果，实际效果……

**Comment by roft418** [comment]
@zombieJ 好的 😄
操作步骤：在didmount时通过调用一个api （类似validateFields）拿到错误信息，按钮禁用
预期效果：得到错误信息接可以判断，不引起副作用。
实际效果：现在没这个api，使用validateFields会导致副作用（组件立刻表现错误），例子里使用resetFieldsError补救又会导致错误信息被清除。。。

**Comment by zombieJ** [comment]
明白了，有几种方式：
* 在上层设置一个 className，如果不想显示的时候就用 css 隐藏掉它。
* 自己用 state 控制按钮 disabled 状态。

**Comment by gebin** [comment]
> @zombieJ 谢谢你提供了另外一种补救的措施。但是这种做法也会导致页面的一次render，如果render里有个组件是根据getFieldsError进行判断，返回值就会被重置为没有报错信息（因为我采用了setFields来补救），还是达不到效果，并没有从根本上解决我的问题。。。
> 如果有个api返回的错误信息没有副作用就好了。

validateFields(['field1', 'field2'], (errors, values) => {
  // ...
});

支持只对某些字段进行校验，你需要的是这个意思吗

**Comment by roft418** [comment]
> > @zombieJ 谢谢你提供了另外一种补救的措施。但是这种做法也会导致页面的一次render，如果render里有个组件是根据getFieldsError进行判断，返回值就会被重置为没有报错信息（因为我采用了setFields来补救），还是达不到效果，并没有从根本上解决我的问题。。。
> > 如果有个api返回的错误信息没有副作用就好了。
> 
> validateFields(['field1', 'field2'], (errors, values) => {
> // ...
> });
> 
> 支持只对某些字段进行校验，你需要的是这个意思吗

先谢谢你的回答。
不是的，我要的校验是逻辑上的校验，不需要直接引起表单的表现。。。我整个issue都是围绕着这个来说的，现在的校验只要表单有错都会引起红色的变化，这不是我要的，我只想要错误信息。。。

**Comment by rashuo** [comment]
问题没有解决，为何close了？

**Comment by andyyxw** [comment]
> 不是的，我要的校验是逻辑上的校验，不需要直接引起表单的表现。。。我整个issue都是围绕着这个来说的，现在的校验只要表单有错都会引起红色的变化，这不是我要的，我只想要错误信息。。。

自己加个样式，隐藏error相关的样式吧。也能控制到每个组件
