### ISSUE TITLE
DatePick 控件showTime的时候 上面日期输入框往后隐藏显示了时分秒，和后面的时分秒显示重复，是否可去掉前面的时分秒显示？

### ISSUE THREAD

**Issue by sammiewy** [ant-design/ant-design#1707]
在使用DatePick 控件showTime的时候 上面日期输入框往后隐藏显示了时分秒，和后面的时分秒显示重复，是否可去掉前面的时分秒显示？
![image](https://cloud.githubusercontent.com/assets/8556234/15279379/49c62ef4-1b56-11e6-8bd2-8b74eeb4b352.png)

**Comment by afc163** [comment]
呃，这个尝试去掉过好多次，一直没成功。所以用了一个 css trick 做临时方案，被细心的楼主发现了。

**Comment by RaoHai** [comment]
是否可以把 formatter 放出来？不过放出来的话配置可能会过于复杂了……

**Comment by afc163** [comment]
不好搞，我的想法是让用户没法拖到输入框后面去。

**Comment by afc163** [comment]
相关 issue ：https://github.com/ant-design/ant-design/issues/953

**Comment by superRaytin** [comment]
不好控制，键盘用 `cmd + >` 一样可以出现

**Comment by RaoHai** [comment]
![](https://os.alipayobjects.com/rmsportal/vitcYTAgUGCuQYQ.png)

其实如果自定义时间格式的话， css trick 貌似也不对的……

要么在 showTime 的时候，把日期格式和时间格式分开定义？类似于 

```jsx
<DatePicker showTime dateFormat="yyyy年MM月dd日" timeFormat="HH时mm分ss秒" />
```

不过日期和时间的分隔又没法定义了。类似于需求 `yyyy年MM月dd日，HH时mm分ss秒` 这样的格式。

还有个方案就是，showTime 的时候，展示时间格式不可配？---反正 onChange 的 value 跟这个 format 没关系。。

**Comment by RaoHai** [comment]
要不这样？
![](https://os.alipayobjects.com/rmsportal/yynGocwUJizbgbF.JPG)

**Comment by afc163** [comment]
这样又把 TimePicker 去掉了，交互要重做。

我的建议是：

1. 保留第一个输入框以及里面的完整格式，样式类似 `showTime={false}` 的面板。
2. 去掉 TimePicker 的输入框，用一个时间图标代替，作为触发器，放在 `x` 的位置。
3. 点击时间图标，弹出 TimePicker 面板选择。
4. `x` 的位置移到类似 Cascader 的清除图标的位置上，一并解决 #1708 的问题。
5. RangePicker 使用相同的改造方式。

**Comment by afc163** [comment]
![](https://os.alipayobjects.com/rmsportal/QCHwiWMReKEpAmb.png)

大概这样，不过有一个问题就是用户可能不知道要点 🕙 图标来展开，依旧去点时间文本。
