### ISSUE TITLE
getFieldDecorator 包裹DatePicker 通过state的形式插入页面 无法修改值

### ISSUE THREAD

**Issue by dwoniu** [ant-design/ant-design#17073]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
前景介绍：页面中有个form表单 但是表单里面的内容会根据操作不同显示不同，所以当操作时生成content 把content保存到state中 然后再插入页面中，表单需要验证是否必填项我使用了getFieldDecorator包裹

表单有一项是发生时间 编写如下
```
        <Form.Item label='发生时间'>
          {
            getFieldDecorator('happen_time', {
              rules: [{required: true, message: '请选择时间'}],
              initialValue: moment()
            })(
              <DatePicker showTime format='YYYY-MM-DD HH:mm:ss' placeholder='发生时间' />
            )
          }
        </Form.Item>
```

插入页面后DatePicker的显示值无法被修改、清除， 点击清除后表单能console出提示必填 但是显示值没有被清除，如果不使用getFieldDecorator包裹 一切操作正常

### What is expected?
期望使用getFieldDecorator 包裹也能正常修改显示的时间

==================分割线
不好意思 这个是渲染机制问题，setState会触发render导致值被刷新掉 所以无法更新最新值上去

**我要问的是 为什么不用getFieldDecorator就可以更新值 用了这个就无法把值更新上去**

### What is actually happening?
目前使用了getFieldDecorator包裹后 通过state插入页面的 DatePicker 显示值无法被修改 

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.4.1 |
| System | mac 10.12.6  window 10 |
| Browser | google 74.0.3729.157 |

**Comment by zombieJ** [comment]
感觉像是什么地方误用了，给个重现看一下

**Comment by dwoniu** [comment]
> 感觉像是什么地方误用了，给个重现看一下

https://codepen.io/anon/pen/WqvdpK?editors=0010 
这个是示例 基本上是这样的 只是我直接放到生命周期里面执行了

**Comment by zombieJ** [comment]
`getFieldDecorator` 会将值填入 Component 中，由于你的 Form 是在 didMount 中生成。因而之后怎么render `getFieldDecorator` 填入的值都是 `didMount` 中产生的值。所以就改不了了。

我建议是将多个表单抽成独立的 Form.create 或者提供一个 renderForm 的方法，render 时调用来生成同步的表单。

**Comment by FanJfly** [comment]
可以在onChange(date)中用setFieldsValue({'happen_time',date})方法手动设置
