### ISSUE TITLE
DatePicker清楚时间按钮在弹窗右上方，用户理解为关闭弹窗按钮

### ISSUE THREAD

**Issue by michael8335** [ant-design/ant-design#1708]
用DatePicker做时间控件时，时间选择弹窗的清楚按钮放置在右上角，结果很多用户以为这是一个关闭弹窗的按钮，导致不停点击都没有关闭的效果
- The version of antd(e.g. 0.12.0):
0.12.13

**Comment by benjycui** [comment]
1.0 已经没有这个问题了，升级下？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1707#issuecomment-220508749
