### ISSUE TITLE
Editable table performance issues

### ISSUE THREAD

**Issue by HsiaoKang** [ant-design/ant-design#17081]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/HsiaoKang/pen/BgNVxX](https://codepen.io/HsiaoKang/pen/BgNVxX)

### Steps to reproduce
The code is mainly from the official website. I changed and saved a copy:
https://codepen.io/HsiaoKang/pen/BgNVxX
The line: 38 and 165

### What is expected?
Changes in content can be quickly reflected in the table

### What is actually happening?
When I tried to enable editing for the entire table, there was a special cutout in chrome that repeatedly triggered the key, whereas in firefox it was much better.

This official site is an example of a page that I just opened for editing, which I think is quite a serious problem.

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome  74.0.3729.169 |

---
screenshots

![image](https://user-images.githubusercontent.com/30774799/59412085-45d81500-8def-11e9-8b75-1bd40ca2418c.png)

**Comment by HsiaoKang** [comment]
@chenshuai2144 请问有进展吗？

**Comment by zombieJ** [comment]
官网的例子都会尽量做的简单，便于用户理解，并不会做过多的性能优化。如果需要对性能进行优化，可以考虑使用 redux 封装降低 cell 的渲染频率。Provider更新会触发所有 Consumer 更新：

> All consumers that are descendants of a Provider will re-render whenever the Provider’s value prop changes. The propagation from Provider to its descendant consumers is not subject to the shouldComponentUpdate method, so the consumer is updated even when an ancestor component bails out of the update.

ref: https://reactjs.org/docs/context.html#contextprovider
