### ISSUE TITLE
Table 与react-dnd 配合的时候 当一个页面有2个需要拖拽元素时 表现不正常

### ISSUE THREAD

**Issue by soeyi** [ant-design/ant-design#17088]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-goldwasser-9f9h9)

### Steps to reproduce
不停由上往下的拖动 第二个Table。
然后数据就会变乱。
但是datasource 还是正常的。

### What is expected?
展示的数据和Datasource 一样

### What is actually happening?
实际展示的数据会乱掉。

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | macos |
| Browser | chrome  74.0.3729.131 |

**Comment by zombieJ** [comment]
你操作第二个，改的却是第一个的值：
```jsx
const { data } = this.state;
const dragRow = data[dragIndex];
```

https://codesandbox.io/s/cool-ritchie-1ijy6
