### ISSUE TITLE
Tree组件能做到父节点关联子节点，子节点不关联父节点吗？

### ISSUE THREAD

**Issue by wubin1998** [ant-design/ant-design#17085]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
节点勾选自定义关联问题。有这样的需求，父节点是勾选的状态，子节点不一定勾选。

### What does the proposed API look like?
可以参考zTree插件。http://www.treejs.cn/v3/demo.php#_201 希望能增加自定义关联父子节点勾选。

**Comment by zombieJ** [comment]
`checkStrictly` 可以脱离关联。
