### ISSUE TITLE
Input 组件样式不正常 与其他同尺寸组件不在同一水平线

### ISSUE THREAD

**Issue by azurefang** [ant-design/ant-design#17082]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/bPdxgv?editors=0010](https://codepen.io/anon/pen/bPdxgv?editors=0010)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/3921442/59418313-68702b00-8dfb-11e9-8d24-566111817ce3.png)

### What is expected?
Input 与其他同尺寸组件在同一水平线

### What is actually happening?
Input 与其他同尺寸组件不在在同一水平线

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | macos mojave 10.14.4 |
| Browser | chrome 74.0.3729.169 |

**Comment by afc163** [comment]
找了一个 safari 的 hacks 来解决这个问题。https://codepen.io/anon/pen/qzOymM?editors=0110

https://jeffclayton.wordpress.com/2015/04/28/css-hacks-for-safari-6-1-7-and-8-not-chrome/
