### ISSUE TITLE
Option does not exist attribute 'label'

### ISSUE THREAD

**Issue by jibenziliao** [ant-design/ant-design#17087]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-leftpad-7sj1r?fontsize=14)

### Steps to reproduce
Select 组件定制回填内容，在TypeScript下报错

the Select component has errors in TypeScript

```typescript
<Select
        placeholder="Please select store"
        optionLabelProp="label"
        style={{ width: "100%" }}
      >
        {items.map(item => (
         // got an error for label attribute
          <Option key={item} value={item} label={item}>
            <div>
              <Avatar style={{ background: "#10899e" }}>{item[0]}</Avatar>{" "}
              {item}
            </div>
          </Option>
        ))}
      </Select>
```

### What is expected?
antd/lib/select/index.d.ts OptionProps 缺少 label参数

antd/lib/select/index.d.ts OptionProps missing label param

```typessript
export interface OptionProps {
    disabled?: boolean;
    value?: string | number;
    title?: string;
    children?: React.ReactNode;
    className?: string;
    style?: React.CSSProperties;
// label: string （missing）
}
```

### What is actually happening?
const Option: React.ClassicComponentClass<OptionProps>

不能将类型“{ children: Element; key: string; value: string; label: string; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, any, any>> & Readonly<OptionProps> & Readonly<{ children?: ReactNode; }>”.
类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, any, any>> & Readonly<OptionProps> & Readonly<{ children?: ReactNode; }>”上不存在属性“label”。ts(2322)

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | Mac OS 10.14.5 |
| Browser | Chrome 75.0.3770.80 (official) (x64) |

**Comment by afc163** [comment]
<img width="523" alt="图片" src="https://user-images.githubusercontent.com/507615/59444022-b56df480-8e2f-11e9-9a37-08c4251b45db.png">

**Comment by afc163** [comment]
https://codesandbox.io/s/vibrant-grass-yrj8i

**Comment by vmc08** [comment]
@afc163 Hello, it seems the problem is back. The suggestion above isn't working for me. Please review. I'm using antd: ^3.25.0

**Comment by afc163** [comment]
Duplicate of #17493
