### ISSUE TITLE
Editable multiline paragraph

### ISSUE THREAD

**Issue by smddzcy** [ant-design/ant-design#17094]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/po774)

### Steps to reproduce
- Edit the paragraph and hit enter

### What is expected?
Ant design does not automatically concatenate the lines.
Also, the user can put a line-break by hitting Shift+Enter, or Ant design calls `onSave` after the user clicks a save button instead of hitting Enter.

### What is actually happening?
Ant design automatically concatenates the lines so the paragraph becomes a single-line and `onSave` gets called after hitting Enter on the editable input.

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | macOS 10.14.5 |
| Browser | Google Chrome 74.0.3729.169 |

**Comment by zombieJ** [comment]
Paragraph is design as single line paragraph. Edit one paragraph into multiple line breaking the definition of Paragraph.
Since it's a lightway of editable function, you can create your own Component if multiple line needed.

**Comment by ethansmith** [comment]
+1. Would be amazing to have stronger support for multiline editable paragraphs

**Comment by oliabka** [comment]
Has anyone found a solution for this? Maybe there is a custom component someone has created?

**Comment by evenmed** [comment]
I decided to write my own component for this.

I made it so edit mode is triggered via double click and then the content is saved using Cmd+Enter.

Content needs to be passed explicitly via `text` prop. The passed `onChange` handler should also update `text`.

````
import { Typography } from 'antd';
import React, { useEffect, useState } from 'react';
import PropTypes from 'prop-types';

export default function MultilineEditableText({ onChange, text, ...props }) {
  const [editing, setEditing] = useState(false);
  const [value, setValue] = useState(text);

  useEffect(() => {
    setValue(text);
  }, [text]);

  if (editing)
    return (
      <textarea
        rows={8}
        style={{ width: '100%' }}
        value={value}
        onChange={(e) => setValue(e.target.value)}
        // Trigger save when Cmd + Enter pressed
        onKeyDown={(e) => {
          if (e.metaKey && e.key === 'Enter') {
            onChange(value);
            setEditing(false);
          }
        }}
      />
    );

  return (
    <Typography.Text
      onDoubleClick={() => (onChange ? setEditing(true) : null)}
      {...props}
    >
      {text}
    </Typography.Text>
  );
}
MultilineEditableText.propTypes = {
  onChange: PropTypes.func,
  text: PropTypes.string
};
````
