### ISSUE TITLE
Slider component - misplaced tooltip

### ISSUE THREAD

**Issue by bravoeguizabal** [ant-design/ant-design#17093]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/bravoeguizabal/slider-bug](https://github.com/bravoeguizabal/slider-bug)

### Steps to reproduce
1. Start Ant Design Pro 
2. Visit the welcome page
3. Expand then collapse the menu

### What is expected?
If the menu is collapsed or expected the relative position of the slider should be kept

### What is actually happening?
If the menu is expanded or collapsed the slider is misplaced

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | Windows |
| Browser | Firefox 67.0.1, Chrome 74.0.3729 |

---
I found this bug while experimenting with ant-design components, in order to isolate it I just spawned a new ant-design-pro instance and introduced minimal changes to include a slider in the welcome page, the result was the one explained above.

**Comment by zombieJ** [comment]
Tooltip position align only happens when user interactive. We may not fix this since perf consideration.
