### ISSUE TITLE
Paragraph Ellipsis 在 table 中不生效

### ISSUE THREAD

**Issue by JiangWeixian** [ant-design/ant-design#17097]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/little-feather-dvkv0)

### Steps to reproduce
在table组件中
- 带有operation icon是生效的
- 直接使用是不生效的

### What is expected?
应该是带有省略号的

### What is actually happening?
撑开了table cell宽度

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | mac os |
| Browser | chrome 74.0.3729.169 |

**Comment by afc163** [comment]
https://codesandbox.io/embed/little-feather-dvkv0

这种情况先加一个来解决吧：

```
.ant-table table {
  table-layout: fixed;
}
```

**Comment by afc163** [comment]
Futher discussion: #17124

**Comment by afc163** [comment]
Pull Request sent: #17284
