### ISSUE TITLE
初始demo报错，

### ISSUE THREAD

**Issue by falltodis** [ant-design/ant-design#171]
![image](https://cloud.githubusercontent.com/assets/7006864/9378891/a704ad08-4757-11e5-9c3e-7c8fd49cbcc2.png)

昨天使用ant-bin 0.3的时候没见到这个错误，启动是ok的，今天提示webpack找不到，之后更新antd 创建新demo，出现了这个问题。

**Comment by ecafe8** [comment]
+1 同样遇到.

**Comment by afc163** [comment]
related #169
