### ISSUE TITLE
Overwriting component styles with css modules in combination with babel-plugin-import will stop loading styles

### ISSUE THREAD

**Issue by dysticus** [ant-design/ant-design#17107]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/dysticus/antd-modulecss-overwrite](https://github.com/dysticus/antd-modulecss-overwrite)

### Steps to reproduce
First, clone, npm install and npm start
Then inspect the Datepicker component. It comes without styles. 
Remove the css module options from the css-loader in webpack.dev.js, see how it works again

### What is expected?
I'm trying to overwrite the styles from this specific component by using css modules and importing it in the file. 

### What is actually happening?
No styling is applied(nor antd nor custom), only the css modules classname 

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | Win10 |
| Browser | Chrome latest |

**Comment by afc163** [comment]
Please exclude node_modules/antd` from  css-modules rule.
