### ISSUE TITLE
Input with text-mask

### ISSUE THREAD

**Issue by AndreyKuzmenko3** [ant-design/ant-design#17104]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1i8c8)

### Steps to reproduce
* Edit text in Input component
* First character will be added to the beginning, the rest to the end of the field
* Mask will not change

### What is expected?
Text is entered and rewrites the mask

### What is actually happening?
How mentioned in page with third-party libraries i should use text-mask for formatted Input.
Code work correctly if antd version 3.11.6 or less, but it does not work with the latest version

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.5 |
| Browser | Google Chrome 75.0.3770.80  |

**Comment by zombieJ** [comment]
Input update to new react life cycle method with `getDerivedStateFromProps`. We may not roll back to deprecated life cycle.

**Comment by AndreyKuzmenko3** [comment]
If you can't do anything with this problem, maybe you should remove the link to the text-mask from the page with third-party libraries ? Because it is wrong and leads to misunderstanding.
