### ISSUE TITLE
table组件如何可以支持行内数据编辑修改

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#1710]
table组件如何可以支持行内数据编辑修改

**Comment by clarkhan** [comment]
see #1377 and #1180 

其实我觉得这个场景很多，可以实现一个？
[这里](http://uxco.re/components/table/)有个。

**Comment by whx76** [comment]
自己封装兼容性和一致性肯定比较差，而且要大量研究底层，期望能有专门的行内编辑table，既保证目前table轻量又能统一组件风格

**Comment by whx76** [comment]
另外table及富文本编辑器组件的重要性及使用比重非常高，期望能有统一实现，期望ant组件越来越好。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/blob/design-pattern/docs/pattern/table/demo/edit-directly.md

这些会以 demo 的形式提供。
