### ISSUE TITLE
The onBack button on PageHeader component displays a pointer that is not always clickable

### ISSUE THREAD

**Issue by Clafouti** [ant-design/ant-design#17109]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/page-header/](https://ant.design/components/page-header/)

### Steps to reproduce
The first example from the documentation is enough to showcase the issue.
1. Approach your mouse pointer to the left-arrow
2. Put it between the left-arrow and the divider
3. The cursor will be a pointer but you can't click to go back unless you are precisely on top of the left-arrow (which acts as a button)

### What is expected?
The entire section where the cursor changes to a pointer should be clickable to go back. It is a bit misleading that the entire block (`ant-page-header-back` div) is not clickable.

### What is actually happening?
The button defined by the arrow-left icon is clickable but the entire `ant-page-header-back` div defines a `cursor: pointer`

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | macOS 10.14.3 |
| Browser | Chrome 74.0.3729.169 |

**Comment by afc163** [comment]
@chenshuai2144 It is a bug.
