### ISSUE TITLE
使用treeSelect多选的时候，修改key会出现之前选项消失的情况

### ISSUE THREAD

**Issue by ranzhu123** [ant-design/ant-design#1711]
如果在输入框输入了key值，选择某个value之后，重新输入一个key，在这次输入的key显示的value不同，例如第一次输入的1，找到1-1-1等等，然后选择了1-1-1，紧接着输入2，下拉框找到2-2,2-2-2，这时我选择2-2，则，之前选择的1-1-1就消失了。这种情况怎么处理，我是需要多选的，并且我搜索完一个结果可能还没结束，还需要更多的结果。

**Comment by ranzhu123** [comment]
现在发现问题好像不太一样了，最新版的1.0.1，我输入不同的key值选中对应的选项时，选中的却不是我点的，这是怎么回事呢？
![image](https://cloud.githubusercontent.com/assets/12227617/15308881/4d82c02a-1c14-11e6-88aa-0b5e8ea13bba.png)，我选择了鼎和，但是却自动跳了一下页面成了这个
![image](https://cloud.githubusercontent.com/assets/12227617/15308899/7701d4fe-1c14-11e6-802a-d47bb885ad15.png)

**Comment by ranzhu123** [comment]
当选项稍微多点的时候就会出现问题的

**Comment by warmhug** [comment]
注意 `treeNodeFilterProp` 的设置

**Comment by afc163** [comment]
无法重现的，5 天后统一关闭，有问题再开。
