### ISSUE TITLE
How to click elsewhere to close controlled components Popover 

### ISSUE THREAD

**Issue by zouxiaomingya** [ant-design/ant-design#17112]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design](http://new-issue.ant.design/?repo=ant-design)

### Steps to reproduce
http://new-issue.ant.design/?repo=ant-design

### What is expected?
How to click elsewhere to close controlled components Popover

### What is actually happening?
How to click elsewhere to close controlled components Popover

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8 |
| System | 64 |
| Browser | google |

**Comment by afc163** [comment]
https://ant.design/components/popover/#components-popover-demo-control
