### ISSUE TITLE
 Table component: Ability to add custom thead row (<tr>) 

### ISSUE THREAD

**Issue by yairEO** [ant-design/ant-design#17121]
- [✓] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
fixed, styled, table header row for added new table records 

### What does the proposed API look like?

see my question: https://stackoverflow.com/q/56619026/104380

```javascript
<Table dataSource={data}>
    <HeaderRow>
        <Column><input /></Column>
        <Column><input type='number' /></Column>
        <Column><select>...</select></Column>
    </HeaderRow>
    <Column title="Person's name" dataIndex="name" key="name" render={item => <strong>{item}</strong>} />
    <Column title="Person's age" dataIndex="age" key="age" />
    <Column title="gender" dataIndex="gender" key="gender" />
</Table>
```

Expected result should look like:

https://i.stack.imgur.com/gS2DA.png

**Comment by yairEO** [comment]
Why was this closed? This is a feature-request I've opened via your automatic issues creator tool, it is a valid feature request, is it not?

**Comment by afc163** [comment]
<img width="738" alt="图片" src="https://user-images.githubusercontent.com/507615/59565161-4f2ce000-9082-11e9-9d08-e9a1168c34c4.png">
