### ISSUE TITLE
select focus 样式出现重复

### ISSUE THREAD

**Issue by pacific0437** [ant-design/ant-design#1712]
![qq20160516-0](https://cloud.githubusercontent.com/assets/7251055/15282388/8edaf988-1b75-11e6-8812-11e8c1224cb2.png)

1.0.1 带搜索的selectInput 样式好像有问题啊 focus的时候 外边有focus样式 ant-select-focused
最里面的input 还有 focus样式 .ant-select-search__field:focus

button也没对齐， 但是官网上demo的例子却没有问题（我感觉官网demo这次的版本 还没升级到1.0.1吧， 我在changelog里面看到咱们antd对select样式做修改了）

![qq20160516-1](https://cloud.githubusercontent.com/assets/7251055/15282771/f8cb3a5e-1b77-11e6-9e57-6e38d81581bb.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1684
