### ISSUE TITLE
Can the table support both the head and the tbody while adding scroll bars, synchronous scrolling

### ISSUE THREAD

**Issue by dongyang19931108** [ant-design/ant-design#17129]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the number of lines exceeds the screen and scroll.y is not set, you need to pull to the bottom of the table to scroll the table. Can you also increase the scroll bar in the head position?

### What does the proposed API look like?
Just add scroll bars in the head position

**Comment by afc163** [comment]
`scroll={{ x: true }}` or `scroll={{ x: 'max-content' }}`.

**Comment by dongyang19931108** [comment]
> `scroll={{ x: true }}` or `scroll={{ x: 'max-content' }}`.
What I mean is when I slide the scroll bar in the header section, tbody will also slide.

**Comment by afc163** [comment]
That is it, you can try it.

**Comment by dongyang19931108** [comment]
> That is it, you can try it.

But the scroll bar appears at the bottom of the table, can the table add another scroll bar to the head position?

**Comment by afc163** [comment]
It is by designed, we don't want to display duplicated scrollbar in both.

**Comment by dongyang19931108** [comment]
> It is by designed, we don't want to display duplicated scrollbar in both.

Has the antd team considered adding arrows instead of scroll bars in the head slidable area?

**Comment by afc163** [comment]
We are used to be a switchable columns: https://012x.ant.design/components/table/#demo-paging-columns, not any more after 1.x: https://github.com/ant-design/ant-design/pull/1265

**Comment by dongyang19931108** [comment]
> We are used to be a switchable columns: https://012x.ant.design/components/table/#demo-paging-columns, not any more after 1.x: #1265

Maybe adding an api which can controls the sliding method is a reasonable solution.
Anyway, thank you for your reply!
