### ISSUE TITLE
Modal.info doesn't has api named 'cancelText'

### ISSUE THREAD

**Issue by howel52** [ant-design/ant-design#17136]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/howel52/pen/KjzRxQ](https://codepen.io/howel52/pen/KjzRxQ)

### Steps to reproduce
```
    Modal.info({
      content: 'Info',
      okText: 'Continue',
      cancelText: 'Close'
    })
```

Modal的各个命令式调用，支持的参数并不一致。

如： Modal.info 似乎并不支持 cancelText ，Modal.confirm 支持。 与提供的 [API 文档](https://ant.design/components/modal-cn/#%E6%B3%A8%E6%84%8F)不一致

### What is expected?
期望 Modal.method 支持的 options 统一，或者在文档里标注出不统一的参数部分

### What is actually happening?
文档没有标注 Modal.info 不支持 cancelText.

| Environment | Info |
|---|---|
| antd | 3.13.6 |
| React | 16.2.0 |
| System | macOS 10.14.3 |
| Browser | 74.0.3729.169 |

**Comment by zombieJ** [comment]
嗯，文档需要标注一下
