### ISSUE TITLE
同一个页面用了两个Tree组件，总时报Warning: '0-0-1' does not exist in the tree.这个警告

### ISSUE THREAD

**Issue by xiaoshui222** [ant-design/ant-design#17138]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://bufangbian](http://bufangbian)

### Steps to reproduce
同一个页面里用了两个Tree组件，children的key也不一样，点复选框时总是报警告Warning: '0-0-1' does not exist in the tree，不影响界面功能，但是总是有这个警告不太好

### What is expected?
求一个解决办法

### What is actually happening?
实际结果不影响功能，仅仅是Warning

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.7.0 |
| System | 2.3.1 |
| Browser | Chrome 74.0.3729.169 |

**Comment by YangRobin** [comment]
先加载树，然后再设置选中的key。出错的原因是你设置选中的key 时，树还没渲染完。
 make sure you have rendered the tree before set checkedKeys!

**Comment by Picktarget** [comment]
how to make sure you have rendered the tree before set checkedKeys!

**Comment by alienzhangyw** [comment]
> how to make sure you have rendered the tree before set checkedKeys!

You can set checkedKeys in useEffect when tree data is loaded
