### ISSUE TITLE
tabs宽度问题

### ISSUE THREAD

**Issue by longang520** [ant-design/ant-design#1713]
.ant-tabs-nav-scroll 的宽度为什么会有一个99999px ，该属性导致不限制宽度的容器，会很宽。

**Comment by longang520** [comment]
@luolonghao 这个问题怎么解决？

**Comment by longang520** [comment]
采用了重写class
.ant-tabs-nav-scroll{
  overflow: hidden;
  width:auto;
}

**Comment by afc163** [comment]
没看到具体的问题，这里的例子没问题。http://ant.design/#/components/tabs

有问题直接给 codepen ，一目了然。

**Comment by longang520** [comment]
你的例子是给外容器宽度，你写一个不给外容器宽度的例子，你就知道了。

**Comment by afc163** [comment]
帮助我们重现，否则只能猜了。:smile:
