### ISSUE TITLE
"export 'CardGridProps' was not found in './Grid'

### ISSUE THREAD

**Issue by heytheww** [ant-design/ant-design#17134]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/card/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/card/index.tsx)

### Steps to reproduce
Hello, everyone. I'm analyzing and disassembling the source code of ant. design. Which dependency can support it?

export { CardGridProps } from './Grid';
export { CardMetaProps } from './Meta';

### What is expected?
Obtaining dependencies

### What is actually happening?
node:
 
"export 'CardMetaProps' was not found in './Meta'

 warning  in ./src/components/grid/index.tsx

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome 74.0.3729.157 |

**Comment by zombieJ** [comment]
`./Meta` is a related path and not same dir with `./src/components/grid/index.tsx`.

**Comment by zombieJ** [comment]
`./Meta` is a related path and not same dir with `./src/components/grid/index.tsx`.

**Comment by heytheww** [comment]
I don't quite understand what you mean. I can locate CardGridProps through vscode.

**Comment by zombieJ** [comment]
`./Meta` is related with `components/card/index.tsx`. Your warning is:
```
"export 'CardMetaProps' was not found in './Meta'
warning in ./src/components/grid/index.tsx
```

**Comment by heytheww** [comment]
Sorry, sorry, I duplicated the wrong line, the right one is

**Comment by zombieJ** [comment]
`CardMetaProps` is actually exported in `Meta.tsx`. It seems not common error:
https://github.com/ant-design/ant-design/blob/master/components/card/Meta.tsx#L5

**Comment by heytheww** [comment]
Thank you for your help. You are a good man!!
