### ISSUE TITLE
RangePicker在Form的layout为inline时不垂直居中

### ISSUE THREAD

**Issue by TnWah** [ant-design/ant-design#17143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-bohdx?fontsize=14)

### Steps to reproduce
https://codesandbox.io/s/antd-reproduction-template-bohdx?fontsize=14

### What is expected?
垂直居中

### What is actually happening?
未居中

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.7.0 |
| System | Mac10.14.5 |
| Browser | Chrome 74.0.3729.169 |

**Comment by afc163** [comment]
We should use this fix: https://github.com/ant-design/ant-design/pull/17124

ref https://github.com/ant-design/ant-design/pull/17126#issuecomment-502635382

**Comment by afc163** [comment]
#17159
