### ISSUE TITLE
 this.props.form.getFieldValue() 获取的表单值是上一个值，不是最新值

### ISSUE THREAD

**Issue by wxb1123603312** [ant-design/ant-design#17144]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/wxb1123603312/antd-getFieldValue--issues.git](https://github.com/wxb1123603312/antd-getFieldValue--issues.git)

### Steps to reproduce
例子：

![Image of Yaktocat](https://github.com/wxb1123603312/antd-getFieldValue--issues/blob/master/482D7EDF-7988-4BFD-B58E-D4C58B17C20F.png?raw=true)

### What is expected?
 this.props.form.getFieldValue() 获取表单中的当前值

### What is actually happening?
 this.props.form.getFieldValue()  获取表单中上一个值

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | mac window |
| Browser | chorme |

**Comment by wxb1123603312** [comment]
小白写程序 有点难受。。

**Comment by afc163** [comment]
Try `onValuesChange`:

```jsx
CustomizedForm = Form.create({
  onValuesChange: (props, changedValues, allValues) => {
    console.log(allValues);
  },
})(CustomizedForm);
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/pull/2280
https://github.com/ant-design/ant-design-pro/issues/2776

**Comment by wxb1123603312** [comment]
蟹蟹大佬

**Comment by lili21** [comment]
可是如何在组件内部监听呢？
