### ISSUE TITLE
`Form`中使用`Upload`，`disabled`属性没有下发到隐藏的`type="file"`的`input`节点。

### ISSUE THREAD

**Issue by MuZiRuoYi** [ant-design/ant-design#17142]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`Form`中使用`Upload`组件，同时`Upload`是禁用的，组件本身禁用成功，但是点击`FormItem`的`label`后可以正常使用`Upload`功能。

### What does the proposed API look like?
`Form`中禁用`Upload`处于`disabled`状态，同时`label`也不可用。

**Comment by afc163** [comment]
Try latest version of antd: https://github.com/ant-design/ant-design/issues/16478
