### ISSUE TITLE
No option for styling TabPane headers individually

### ISSUE THREAD

**Issue by steveswork** [ant-design/ant-design#17146]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a super long that needs to be broken down in panes. I would like it to communicate to the user which inactive panes may contain inputs with errors in them by changing the inkBar and the title text for those panes to red. That way, the user can focus only the panes where error exists, instead of searching for errors by opening each pane. Currently, setting the tabPane style prop affects the styling of all items in the pane. This is undesirable. I have searched for other methods to achieve this but there does not seem to be any.

### What does the proposed API look like?
The TabPaneProps interface already has an optional className data member. The className prop is currently applied to the TabPane content but not to its header. The header only contains 'ant-tabs-tab' and 'ant-tabs-tab-active' for the active tab. The className prop value could be appended the header's classList as well.

The usage would still remain the same. Simply add the className prop to an individual TabPane as usual and style that particular TabPane's header along with its descendants as needed using style sheet.

**Comment by zombieJ** [comment]
Tabs provide `renderTabBar` to enable customize tab header. You can ref these samples to do so:
* https://ant.design/components/tabs/#components-tabs-demo-custom-tab-bar
* https://ant.design/components/tabs/#components-tabs-demo-custom-tab-bar-node

**Comment by steveswork** [comment]
I ended up having to do:
`
<Tabs 
    renderTabBar={(props, DefaultTabBar) => (
      <DefaultTabBar {...props}>
        {node => (
          <React.Fragment>
            {
              hasError(nodeData)
                  ? React.cloneElement( node, {
                      className: `${ node.props.className } error`
                  })
                  : node
              }
            </React.Fragment>
        )}
      </DefaultTabBar>
    )}
  >
...
</Tabs>
`
It is effective but long, super quirky and counterintuitive as far as maintainability is concerned. Props affecting the TabPane should added directly to the TabPane. What I usually do is to have a component accept all props passed to it, use the ones that satisfy the propTypes of the component and its children where possible and discard the rest of them. Using the TabPane as an example, if a container component passes any prop that satisfies the React.Div component propTypes, I will pass prop to down to the TabPanel's inner div.

**Comment by remo1** [comment]
> I ended up having to do:
> 
> ```
> <Tabs 
>     renderTabBar={(props, DefaultTabBar) => (
>       <DefaultTabBar {...props}>
>         {node => (
>           <React.Fragment>
>             {
>               hasError(nodeData)
>                   ? React.cloneElement( node, {
>                       className: `${ node.props.className } error`
>                   })
>                   : node
>               }
>             </React.Fragment>
>         )}
>       </DefaultTabBar>
>     )}
>   >
> ...
> </Tabs>
> ```
> 
> It is effective but long, super quirky and counterintuitive as far as maintainability is concerned.
> 
> Props affecting the TabPane should be assigned directly to the TabPane. What I usually do is to have a component accept all props passed to it, use the ones that satisfy the propTypes of the component and its children where possible and discard the rest of them. Using the TabPane as an example, if a container component passes any prop that satisfies the React.Div component propTypes, I will pass prop to down to the TabPanel's inner div.

Thats a great way to style the tabs and add validation. 

I can only add that when you encounter the:

> react_devtools_backend.js:6 Warning: Each child in a list should have a unique "key" prop.

add key prop to <React.Fragment> and it should fix it

**Comment by ChambreNoire** [comment]
> I ended up having to do:
> 
> ```
> <Tabs 
>     renderTabBar={(props, DefaultTabBar) => (
>       <DefaultTabBar {...props}>
>         {node => (
>           <React.Fragment>
>             {
>               hasError(nodeData)
>                   ? React.cloneElement( node, {
>                       className: `${ node.props.className } error`
>                   })
>                   : node
>               }
>             </React.Fragment>
>         )}
>       </DefaultTabBar>
>     )}
>   >
> ...
> </Tabs>
> ```
> 
> It is effective but long, super quirky and counterintuitive as far as maintainability is concerned.
> 
> Props affecting the TabPane should be assigned directly to the TabPane. What I usually do is to have a component accept all props passed to it, use the ones that satisfy the propTypes of the component and its children where possible and discard the rest of them. Using the TabPane as an example, if a container component passes any prop that satisfies the React.Div component propTypes, I will pass prop to down to the TabPanel's inner div.

Where's nodeData coming from ?

Thanks!

**Comment by steveswork** [comment]
@ChambreNoire `nodeData` is an earlier defined variable that had been enclosed within the `(node => (<React.Fragment...` anonymous function. Please take a further look into javascript closures.

**Comment by ChambreNoire** [comment]
> @ChambreNoire `nodeData` is an earlier defined variable that had been enclosed within the `(node => (<React.Fragment...` anonymous function. Please take a further look into javascript closures.

Ah yes I see. However in this example you aren't distinguishing between tabs for validation, correct ?

Thanks!

**Comment by steveswork** [comment]
That's right. It's by design though.

Where the need for individualization exists, an associative data structure might have been used for `nodeData` (if it is not already so) where the associated keys are mapped to some unique information that could be obtained from the `node` argument of the enclosing function. That is very likely to be some _**unique prop**_ you have passed to the child element.

Keep in mind that the `node` argument is really just a reference to a specific one of the child elements you had placed in the Tabs element. So you can access your _**unique prop**_ via `node.props.<some unique prop>`.

The wrangling I just described is the reason I concluded earlier that the workaround to the problem is super quirky and counterintuitive from maintainability perspective.

**Comment by steveswork** [comment]
Please disregard my advice in the previous post. I just recalled that the TabPane component basically discards additional props passed to it and would not provide the unique key data in the closure function.

Ok, so a couple of workarounds I can think of to deal with that issue: one would be to keep one state: an array of `hasError` statuses (true/false) per child TabPane and one ref of a counter. Something along the lines:

```
const NUMBER_OF_TABS = 3; // for example
const isNotEmpty = v => !isEmpty( v );    // referring to an existing lodash.isemtpy

const Test = props => {
    
    const counter = React.useRef( 0 );
    const [errorStatuses, setErrorStatuses] = React.useState([]);
    
    const updateErrorStatuses = useCallback(( status, index ) => {
        if( status === errorStatuses[ index ] ){
            return;
        }
        const newStatuses = errorStatuses.slice();
        newStatuses[ index ] = status;
       setErrorStatuses( newStatuses );
    }, [ errorStatuses ]);
    
    const validateInput = useCallback( params => {
        updateErrorStatuses( params.isValid( params.value ), params.tabIndex )
    }, [ updateErrorStatuses ] );
    
    const handleVanillaInputChange = useCallback( e => {
        const { dataSet, value } = e.currentTarget;
        ...
        validateInput({
            isValid: isNotEmpty,
            tabIndex: +dataset.tabIndex, 
            value
        })
        ...
    }, [ validateInput ] );

    const tabPanes = useMemo(() => {
        const tabPanes = [];
        for( let t = 1; t <= NUMBER_OF_TABS; t++ ) {
            tabPanes.push(
               <TabPane tab={ `Tab ${ p }` } key={ `${ p }` }>
                   <input onChange={  handleVanillaInputChange } data-tab-index="${ t - 1 }" />
                      ...
               </TabPane>
             );
         }
         return tabPanes;
    }, [ handleVanillaInputChange ]);
    
   useEffect(() => {
        if( counter.current === NUMBER_OF_TABS ) {
            counter.current = 0;
        }
    });
    
    return (
        <Tabs renderTabBar={(props, DefaultTabBar) => {
            counter.current++;
            return (
                <DefaultTabBar {...props}>
                    {node => (
                        <React.Fragment>
                            { errorStatuses[ counter.current - 1 ]
                                ? React.cloneElement( node, {
                                     className: `${ node.props.className } error`
                                })
                                : node
                            }
                        </React.Fragment>
                     )}
                 </DefaultTabBar>
            );
        )}
      >
          { tabPanes }
      </Tabs>
    );
};
```
The other approach I have is to apply the useLayoutEffect hook. Compatible with CSR. In universal rendering, checksums may not match. Dealing with UI components in this way is usually fraught and must be done sparingly. The tab error status recordkeeping is pretty much the same. The difference comes in the JSX rendering and direct DOM tracking. 

```
const NUMBER_OF_TABS = 3; // for example
const isNotEmpty = v => !isEmpty( v );    // referring to an existing lodash.isemtpy

const Test = props => {
    
    const tabContainer = React.useRef();
    const [errorStatuses, setErrorStatuses] = React.useState([]);
    
    const updateErrorStatuses = useCallback(( status, index ) => {
        if( status === errorStatuses[ index ] ){
            return;
        }
        const newStatuses = errorStatuses.slice();
        newStatuses[ index ] = status;
       setErrorStatuses( newStatuses );
    }, [ errorStatuses ]);
    
    const validateInput = useCallback( params => {
        updateErrorStatuses( params.isValid( params.value ), params.tabIndex )
    }, [ updateErrorStatuses ] );
    
    const handleVanillaInputChange = useCallback( e => {
        const { dataSet, value } = e.currentTarget;
        ...
        validateInput({
            isValid: isNotEmpty,
            tabIndex: +dataset.tabIndex, 
            value
        })
        ...
    }, [ validateInput ] );

    const tabPanes = useMemo(() => {
        const tabPanes = [];
        for( let t = 1; t <= NUMBER_OF_TABS; t++ ) {
            tabPanes.push(
               <TabPane tab={ `Tab ${ p }` } key={ `${ p }` }>
                   <input onChange={  handleVanillaInputChange } data-tab-index="${ t - 1 }" />
                      ...
               </TabPane>
             );
         }
         return tabPanes;
    }, [ handleVanillaInputChange ]);
    
   useLayoutEffect(() => {
        const tabNav = containerRef.current.querySelector(  '.ant-tabs-nav'  );
        tabNav.querySelectorAll( '.ant-tabs-tab' ).forEach(( tabEl, index ) => {
            errorStatuses[ i ]
                ? tabEl.classList.add( 'error' ) 
                : tabEl.classList.remove( 'error' )
    }, [ errorStatuses ]);

    return (
        <div className="test" ref={ tabContainer }>
             <Tabs>{ tabPanes }</Tabs>
        </div>
    );
};
```

**Disclaimer:** these are just general ideas to serve as a starting point. I did not go through the trouble of really testing them out. _ymmv_
