### ISSUE TITLE
antd typography overrides ol list-style-type unnecessarily

### ISSUE THREAD

**Issue by Stephen2** [ant-design/ant-design#17145]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-egyiw)

### Steps to reproduce
```
<Typography>
  <ol type="a">
     <li>This should have lower-alpha style</li>
  </ol>
</Typography>
```

### What is expected?
Expected `<li>` to have lower alpha `list-style-type` like `a.` `b.` etc...

### What is actually happening?
`<li>` has decimal `list-style-type` like `1.` `2.`

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.4 |
| System | MacOS |
| Browser | Google Chrome 75 |

---
```
.ant-typography ol li {
    list-style-type: decimal;
}
```
^^ This CSS from antd seems unnecessary, as it's the default `<ol>` styling I'm 99% sure

If you remove it, I think everything just works as expected in all browsers

**Comment by afc163** [comment]
It is by designed, you can override style if you don't need it.
