### ISSUE TITLE
message can not read value from Context

### ISSUE THREAD

**Issue by dancerphil** [ant-design/ant-design#17153]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-message-portal-qdmg2)

### Steps to reproduce
Click the button.

### What is expected?
message show that `Context value: value`

### What is actually happening?
message show that `Context value: defaultValue`

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8 |
| System | mac |
| Browser | chrome |

---
We are using ReactRouter.Link but this pattern failed, since ReactRouter is using Context now.
Seems like React.Portal solves this.

related: https://github.com/ant-design/ant-design/issues/15260

**Comment by zombieJ** [comment]
`message.xxx` is not the sub node of current context. If you want to use the context, you should read value in Button `onClick` and pass to  `message.info(<Item value={contextValue} />);`

**Comment by dancerphil** [comment]
I am assuming that `ReactDOM.createPortal` could solve this problem.

Since `react-router` and `react-redux` is using Context. This problem means that any Component with `ReactRouter.Link` or `ReactRedux.connect` fails.

That affects much, in my view.

**Comment by zombieJ** [comment]
`message.xxx` create a new React instance with creating dom element but React do not give the ability to pass context with `ReactDOM.render`. We can do nothing about this.

**Comment by JMVHill** [comment]
> We can do nothing about this.

There have been the `createPortal` method since React16 which should achive this. I believe it carries context and allows you to mount the child to an arbitary node is the DOM.

https://react.dev/reference/react-dom/createPortal
