### ISSUE TITLE
固定头和列bordered时固定列下方有空缺

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#17151]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/goofy-sea-zi7nk)

### Steps to reproduce
在官网demo的

https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header 里加上bordered就明细看到

### What is expected?
bordered时固定列下方无空缺

### What is actually happening?
bordered时固定列下方有明显空缺

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest |

**Comment by afc163** [comment]
截个图。

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/59659871-bdd08180-91d9-11e9-9a7f-30d34ecb3eb5.png)

**Comment by yoyo837** [comment]
另外问一下不支持任意列只支持两边连续的列左右冻结吗？我感觉能做到呀，隐藏不要的头和body，再加冻结测padding 什么的。是否考虑添加？接受PR？团队是否之前搞过有经验传递吗？

**Comment by afc163** [comment]
> 另外问一下不支持任意列只支持两边连续的列左右冻结吗

从设计角度考虑非常奇怪，应该不会支持。

**Comment by yoyo837** [comment]
比如有些大表格数据，20个列 [1, 2, 3 ... 19, 20]

不同的角色对不同列的数据关注度不同，张三冻结[13, 14, 16], 李四冻结[1, 3, 5]，感觉上蛮常见的需求；如果业务上能拆分不同的表格自然不存在这个问题；

很遗憾不考虑支持这个功能。
