### ISSUE TITLE
getFieldValue can not get the initialValue in the first time

### ISSUE THREAD

**Issue by chenziqi94** [ant-design/ant-design#17154]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/sharp-firefly-9o3v4)

### Steps to reproduce
open the link

### What is expected?
when username equals admin
expect two Input shown
others expect one Input

### What is actually happening?
the first time username value is admin but only one Input

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | window10 |
| Browser | chrome  74.0.3729.169  |

---
how can I to realize the function

**Comment by afc163** [comment]
This is intented behavior, it is not possible to get initialValue before `getFieldDecorator` excuted at first time.
