### ISSUE TITLE
form.setFields errors doesn't go to a new line

### ISSUE THREAD

**Issue by florianchevallier** [ant-design/ant-design#17156]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-morse-wy4wo)

### Steps to reproduce
Write something in "name", you'll see that the errors in days are alignes, not on a new line

### What is expected?
I'm expecting every error to be on a new line

### What is actually happening?
All errors are on the same line

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.9.0 |
| System | Mac OS Mojave |
| Browser | Chrome |

---
I don't know if it's by design, but it would be great to have a <p> on each error

**Comment by zombieJ** [comment]
You can use ReactNode as message if want additional style: https://codesandbox.io/s/restless-architecture-4s5cc
