### ISSUE TITLE
DatePicker uses LocaleProvider {zhCN} month week is still English

### ISSUE THREAD

**Issue by sachinye** [ant-design/ant-design#17164]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.sachin-ye.com](http://www.sachin-ye.com)

### Steps to reproduce
Click on the left side of the list(房源发布)
The following DatePicker(交房日||产证日期||开始日期||结束日期)

### What is expected?
DatePicker should display Chinese in the year, month and week

### What is actually happening?
DatePicker only displays Chinese in years

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | Windows10    1809    17763.557 |
| Browser | Chromium 69.0.3497.100 |

**Comment by afc163** [comment]
Make sure you installed same version of `moment` as antd.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16772#issuecomment-496095199
https://github.com/YoungHearts/antd-datePicker/pull/1
