### ISSUE TITLE
allowClear don't work in controlled TreeSelect?

### ISSUE THREAD

**Issue by duwei54** [ant-design/ant-design#17169]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I create a controlled TreeSelect component.and there is no way to clean the selection.

### What does the proposed API look like?
I hope to keep the `allowClear`  work.

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-Input/Select-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86%E3%80%82
