### ISSUE TITLE
Introduction modal on http://ant.design cannot be closed on iPad

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#1716]

**Comment by superRaytin** [comment]
Currently, we have no plans to support iPad, welcome your PR :)

**Comment by kvetoslavnovak** [comment]
The iPhone has the same issue. 
Is'nt quite limited point of view that your website (I am not talking about components themselves) does not work on Apple devices?

**Comment by afc163** [comment]
Thx for report, fixed above.
