### ISSUE TITLE
Layout.Sider‘s zero-width trigger stacked too low

### ISSUE THREAD

**Issue by nivekz** [ant-design/ant-design#17160]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nivekz/antd-sider-trigger-bug](https://github.com/nivekz/antd-sider-trigger-bug)

### Steps to reproduce
```
# Step 1
yarn start

# Step 2: Resize window to a small width

# Step 3: the Sider will disappear, zero-width trigger will show, but the trigger is not clickable.
```

### What is expected?
Trigger shall be clickable.

### What is actually happening?
The trigger is rendered below the <List>.

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | MacOS |
| Browser | Chrome |

---
Zero-width trigger shall have a high enough z-index to be rendered above common display components like `<List>`.

![image](https://user-images.githubusercontent.com/813121/59674551-17df4000-91f6-11e9-85b5-3f5d62f9070d.png)

**Comment by zombieJ** [comment]
Online reproduce: https://codesandbox.io/s/musing-bartik-wm0pv

**Comment by KuthorX** [comment]
Maybe add `z-index:999` to `.ant-layout-sider-zero-width-trigger` is a solution ?

**Comment by movaldivia** [comment]
2020 I got the same issue. I just copy de "responsive" example @afc163 

![image](https://user-images.githubusercontent.com/24725124/89132428-14824300-d4e2-11ea-8417-22c972b5599e.png)
