### ISSUE TITLE
Anchor Not working as expected

### ISSUE THREAD

**Issue by Jaskaran121** [ant-design/ant-design#17162]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-tree-9wuki)

### Steps to reproduce
Just run the link it is a online editor, you are good to go

### What is expected?
1.  The Link (href ) click should scroll to that specific part in the DOM.
2.  The anchor's Affix Ink Ballshould move along in a synchronized way alongside with the elements present in the DOM.

### What is actually happening?
1.  The href click is not working, onclicking it it is appending the href id to the address bar,but not scrolling to that specific link.
2.  The anchor's affix Ink Ball is not moving in a synchronized way i.e it is not moving according to the specific element of the Dom mapping to the Link.

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | Version 1803(OS Build 17135.829) |
| Browser | Chrome |

**Comment by afc163** [comment]
It works in https://9wuki.codesandbox.io/
