### ISSUE TITLE
DatePicker日期选择框 弹出框 起始时间与结束时间之间的 ~ 未居中

### ISSUE THREAD

**Issue by yichenw7** [ant-design/ant-design#17171]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/om5o0qnq6)

### Steps to reproduce
链接页面日期控件，点击弹出框

### What is expected?
起始时间与结束时间之间的 ~ 居中

### What is actually happening?
起始时间与结束时间之间的 ~ 未居中

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | v16.8.6 |
| System | windows7 |
| Browser | chorome |

**Comment by KuthorX** [comment]
These may resolve this bug

`.ant-calendar-range-right` remove `margin-left: -90px;`

`.ant-calendar-range .ant-calendar-input` add `text-align: center;`

`.ant-calendar-range-middle` remove `padding: 0 200px 0 0;`

**Comment by afc163** [comment]
It is by designed, not a bug.
