### ISSUE TITLE
使用了ant-design的component在渲染之后才去改变对应的css样式

### ISSUE THREAD

**Issue by bethinner** [ant-design/ant-design#1717]
使用了ant-design的component在渲染之后才去改变对应的css样式，导致页面会先很丑，然后闪动变成希望的样式

**Comment by afc163** [comment]
具体呢？

和调试时用了 style-loader 有关系？

**Comment by wssgcg1213** [comment]
生产环境请使用extract-text-webpack-plugin生成单独的css文件link引入

**Comment by afc163** [comment]
楼上正解。
