### ISSUE TITLE
当给AutoComplete.Option设置value参数时候为啥会出现react key的警告？

### ISSUE THREAD

**Issue by ZhangMingZhao1** [ant-design/ant-design#17179]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
官网例子里面循环中也是给Option组件设置的key参数，key的值没有重复的，value参数有重复的，就出现了react same key的警告。

### What does the proposed API look like?
比如代码为
```
<Option key={k} text={this.tools(v)} value={this.tools(v)}><div dangerouslySetInnerHTML={{__html: v}}></div></Option>
```
按说key应该没有重复的，但是设置value后就报了key重复的警告，我设置value参数是因为想用onSelect打印出这个value值。

**Comment by afc163** [comment]
value 不可以重复。
