### ISSUE TITLE
Collapsed sidebar-menu with one open sub-menu automatically opens tooltip menu of open sub-menu

### ISSUE THREAD

**Issue by jsefiani** [ant-design/ant-design#17174]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-6lk0d)

### Steps to reproduce
Create a sidebar-menu that is collapsible with three sub-menus, each sub-menu (title prop has icon and text) has one menu item. (Check link for minimal reproduction, it's the exact problem that I'm facing)

Features: 
- Only one sub-menu can be opened at a time
- Sidebar-menu can be collapsed
- When the sidebar menu is collapsed, only the icons are visible
- When I hover over an icon (in collapse mode), a tool tip is shown with the sub-menu's items (vertical)

Components:
- Layout
- Sider
- Menu
- Submenu
- Menu.Item
- Icon

### What is expected?
Whenever I collapse the sidebar-menu with an open sub-menu, the sub-menu's tooltip is not shown automatically. The tooltip menu is only shown when I hover over the icon.

### What is actually happening?
Whenever I collapse the sidebar-menu with an open sub-menu, the sub-menu's tooltip automatically pops up and only goes away when I hover over an icon of the sidebar menu.

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8.6 |
| System | Microsoft Windows 10 PRO |
| Browser | Firefox developer edition 68.0b9 (64-bit) |

---
When I collapse the sidebar menu without an open sub-menu, no menu tooltips are shown automatically which is the expected behavior.

**Comment by jsefiani** [comment]
Any updates on this issue?

**Comment by xyj404** [comment]
This bug still exist. Please give a response @yutingzhao1991

**Comment by xyj404** [comment]
It can be fixed by setting openKeys [] when collapsed. You can save previous openKeys, and set it to openKeys when expand. 
```
      if (collapsed) {
        preOpenKeys.current = [...openKeysRef.current];
        setOpenKeys([]);
      } else {
        setOpenKeys(preOpenKeys.current);
      }

```

**Comment by jsefiani** [comment]
Can you please give some more information?

**Comment by LeeRayno** [comment]
@xyj404 
But this experience is not good, there is a delay in the submenu hiding by setting openKeys `[]` when collapsed，not disappearing instantly.

**Comment by xyj404** [comment]
You can change openKeys and collapsed sync。

**Comment by LeeRayno** [comment]
@xyj404 how? can you show me the code
I put the `collapsed` in the `react-redux` and get it by the `props` and update when the `collapsed` changed
```js
useEffect(() => {
    collapsed ? setOpenKeys([]) : setOpenKeys(matchRoutes(routes, pathname).map(item => item.path));
  }, [collapsed, pathname]);
```
here is my code
```js
import React, { useState, useEffect } from 'react';
import { Menu, Icon } from 'antd';
import menus from 'config/menu.config';
import { withRouter } from 'react-router-dom';
import { matchRoutes, routes } from 'router/index';

const { SubMenu } = Menu;

function AppMenu(props) {
  const { history, collapsed, location: { pathname } } = props;

  const [rootSubmenuKeys] = useState(menus.map(item => item.path));
  const [openKeys, setOpenKeys] = useState(matchRoutes(routes, pathname).map(item => item.path) || []);
  const [selectedKeys, setSelectedKeys] = useState([]);

  useEffect(() => {
    setSelectedKeys([pathname]);
  }, [pathname]);

  useEffect(() => {
    collapsed ? setOpenKeys([]) : setOpenKeys(matchRoutes(routes, pathname).map(item => item.path));
  }, [collapsed, pathname]);

  const handleMenuClick = (v) => {
    history.push(v.key);
  };

  const handleOpenChange = (v) => {
    const latestOpenKey = v.find(key => openKeys.indexOf(key) === -1);
    if (rootSubmenuKeys.indexOf(latestOpenKey) === -1) {
      setOpenKeys(v);
    } else {
      setOpenKeys(latestOpenKey ? [latestOpenKey] : []);
    }
  };
  
  const renderMenuItem = (menu) => {
    const { title, path, icon, children, isLink } = menu;

    return (
      children ? renderSubMenuItem(menu) : (
        <Menu.Item key={path}>
          {icon && <Icon type={icon} />}
          {!isLink 
            ? <span>{title}</span> 
            : <a href={path} target="_blank" rel="noopener noreferrer">{title}</a>
          }
        </Menu.Item>
      )
    );
  };

  const renderSubMenuItem = (menu) => {
    const { title, icon, path, children } = menu;

    return (
      <SubMenu
        key={path}
        title={
          <span>
            {icon && <Icon type={icon} />}
            <span>{title}</span>
          </span>
        }
      >
        {
          children && children.map(child => {
            const copy = { ...child };
            copy.path = copy.isLink ? child.path : `${path}${child.path}`;

            return renderMenuItem(copy);
          })
        }
      </SubMenu>
    );
  };

  return (
    <Menu
      mode="inline"
      theme="dark"
      selectedKeys={selectedKeys}
      openKeys={openKeys}
      onClick={handleMenuClick}
      onOpenChange={handleOpenChange}
    >
      {
        menus.map(menu => renderMenuItem(menu))
      }
    </Menu>
  );
}

export default withRouter(AppMenu);

```

**Comment by xyj404** [comment]
You can send openKeys from parent component and let collapsed and openKeys changed sync.

**Comment by LeeRayno** [comment]
@xyj404 thank you, use the Lifting State Up, it works. but I don't understand why these code doesn't work
```js
useEffect(() => {
    collapsed ? setOpenKeys([]) : setOpenKeys(matchRoutes(routes, pathname).map(item => item.path));
}, [collapsed, pathname]);
```
`useEffect` is async ? or when the `collapsed` changed and it excute the `useEffect` callback?

**Comment by xyj404** [comment]
Yes, when the collapsed changed and it excute the useEffect callback

**Comment by scarcoco** [comment]
```
...
onOpenChange = (keys: string[]) => {
    prevOpenKeys = keys

    this.setState({
      openKeys: keys
    })
  }

  onToggleSider = () => {
    const { collapsed, openKeys } = this.state

    const state = {
      collapsed: !collapsed,
      openKeys
    }
    if (!collapsed) {
      prevOpenKeys = openKeys
      state.openKeys = []
    } else {
      state.openKeys = prevOpenKeys
    }
    this.setState(state)
  }
...
```

this can keep when just toggle menu, but loss some openkeys

**Comment by kairataliakbar** [comment]
it helped me
```
....
render() {
   let customProps = this.state.collapsed ? undefined : {
            openKeys: this.state.openKeys,
            onOpenChange = openKeys => {
                 const latestOpenKey = openKeys.find(
                      key => this.state.openKeys.indexOf(key) === -1
                  );
                  if (this.rootSubmenuKeys.indexOf(latestOpenKey) === -1) {
                       this.setState({ openKeys });
                   } else {
                        this.setState({
                             openKeys: latestOpenKey ? [latestOpenKey] : []
                         });
                    }
              };
     }
     return (
     .....
     <Menu theme="dark" mode="inline" {...customProps}>
     .....
     );
}
....

```

**Comment by HieuDevX** [comment]
> it helped me
> 
> ```
> ....
> render() {
>    let customProps = this.state.collapsed ? undefined : {
>             openKeys: this.state.openKeys,
>             onOpenChange = openKeys => {
>                  const latestOpenKey = openKeys.find(
>                       key => this.state.openKeys.indexOf(key) === -1
>                   );
>                   if (this.rootSubmenuKeys.indexOf(latestOpenKey) === -1) {
>                        this.setState({ openKeys });
>                    } else {
>                         this.setState({
>                              openKeys: latestOpenKey ? [latestOpenKey] : []
>                          });
>                     }
>               };
>      }
>      return (
>      .....
>      <Menu theme="dark" mode="inline" {...customProps}>
>      .....
>      );
> }
> ....
> ```

Can you select menu item in sub menu when menu collapsed (collapsed true) with this code? I try but it doesn't work :3

**Comment by Nagellan** [comment]
I just removed `defaultOpenKeys`, and the problem disappeared. As a temporary solution- it's ok, as I have `defaultSelectedKeys` passed so that the current SubMenu is highlighted, and in a collapsed state *visually* there is no difference. The problem is in the uncollapsed state - the SubMenu is folded by default (be the reasons described previously).

A better solution would be to add `defaultOpenKeys` **conditionally** depending on the collapsed state: if it's a **collapsed** state - there should be no `defaultOpenKeys` as `defaultSelectedKeys` already highlight the current SubMeny; if it's a **uncollapsed** state, set `defaultOpenKeys`, so no pop-up will appear anyway.

Hope it'll help somehow :)

**Comment by Nxtra** [comment]
@Nagellan , @scarcoco , @kairataliakbar, @xyj404 
Can you please provide a CodeSandbox with the working solution? I cannot make sense of this. :)

**Comment by huseyingoztok** [comment]
I want to change the defaultOpenKeys value according to the result of an asynchronous request. Although the component has rendered several times, the change is not reflected. How can I do it?
