### ISSUE TITLE
Add clickable prop for Icon component

### ISSUE THREAD

**Issue by Matthew1994** [ant-design/ant-design#17170]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I want to make a icon be clickable, I need to set its cursor attribute like this. 
```
<div>Title <span><Icon type="edit" theme="twoTone" style={{ cursor: 'pointer' }} onClick={edit} /><span></div>
```

### What does the proposed API look like?
```
<Icon type="edit" theme="twoTone" clickable />
```

**Comment by KuthorX** [comment]
https://codesandbox.io/embed/ant-designant-designissues1770-zfdy9
Actually, when I tried to only add `onClick` but not `style={{ cursor: 'pointer' }}`, I found that it can be clicked, and its style just like you add `style={{ cursor: 'pointer' }}`

**Comment by Matthew1994** [comment]
> https://codesandbox.io/embed/ant-designant-designissues1770-zfdy9
> 
> Actually, when I tried to only add `onClick` but not `style={{ cursor: 'pointer' }}`, I found that it can be clicked, and its style is just liked you add `style={{ cursor: 'pointer' }}`
> 
> So I don't think this is a valid issue

Got it！
