### ISSUE TITLE
设置 @line-height-base : 1.6，Table 在 IE 下样式有问题

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#17175]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ie-table-col-bug-jbw01?fontsize=14)

![image](https://user-images.githubusercontent.com/7971419/59765455-b213b680-92d0-11e9-81fe-b418c160804c.png)

在 css 中写了 
```css
.ant-table {
    line-height: 1.6 !important;
}
```
来重现设置全局变量 `@line-height-base : 1.6` 的效果

### Steps to reproduce
在 IE 下查看列展示是否正常

### What is expected?
header 无滚动条、列展示正常。

### What is actually happening?
header 有滚动条、列展示不正常。

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | latest |
| System | windows |
| Browser | IE 11 |

---
如果 IE 不能打开页面，就下载包后 run build 启动服务查看

**Comment by qq645381995** [comment]
有人在看嘛？

**Comment by afc163** [comment]
<img width="1193" alt="image" src="https://user-images.githubusercontent.com/507615/59897558-c0bcb380-941f-11e9-9593-ff1264fb78ad.png">

3.19.6 没重现出来。

**Comment by qq645381995** [comment]
@afc163  要没有数据。 有数据是没事的

![image](https://user-images.githubusercontent.com/7971419/59900957-58280380-942c-11e9-9323-2864e45729bc.png)

**Comment by afc163** [comment]
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/507615/59903180-df787580-9432-11e9-89d9-88947a3a0973.png">

还是没重现出来。

**Comment by qq645381995** [comment]
[build.zip](https://github.com/ant-design/ant-design/files/3313295/build.zip)
这个解压启动服务看下。
