### ISSUE TITLE
InputNumber组件格式化显示功能，后面单位是两个字符的时候删除内容会出现BUG

### ISSUE THREAD

**Issue by MI-Class** [ant-design/ant-design#17188]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/xoRyzB?&editable=true&editors=001](https://codepen.io/anon/pen/xoRyzB?&editable=true&editors=001)

### Steps to reproduce
将光标放在‘分钟’的右侧然后按下Backspace按键，数字不会被删除，反而会出现更多文字

### What is expected?
期望像官方例子中那样，只删除到数字，而不会影响到单位

### What is actually happening?
不会删除到数字，影响到了单位，必须要把光标定位到数字的位置删除才可以正常使用

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.7.0 |
| System | win10 |
| Browser | firefox67 |

---
想格式化显示后面跟随单位，以方便输入，有些单位不止一个字符，比如ppm,ppb等，都是多个字符的，而多个字符在删除输入的数字的时候光标必须要选中数字，负责会影响到单位

**Comment by muzea** [comment]
删除出现的bug是parser写错了导致的。
默认的parser是

https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L14-L16

你提供的是

`value => value.replace('分钟', '')`

当在input中触发change的时候，事件的value为 '100分'，paeser替换之后还是 '100分'，然后经过 `formatter` 变为 '100分分钟'。

----

The bug that occurred after deleting is caused by the wrong parser.

the default parser is

https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L14-L16

the parser you passed in is

`value => value.replace('分钟', '')`

When the change is triggered, the value of the event is '100分', after the paeser is replaced by '100分', and then after `formatter` becomes '100分分钟'.


https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L260-L271

https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L505-L512

**Comment by MI-Class** [comment]
> 删除出现的错误是解析器写错了导致的。
> 默认的解析器是
> 
> https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L14-L16
> 
> 你提供的是
> 
> `value => value.replace('分钟', '')`
> 
> 当在输入中触发改变的时候，事件的价值为'100分'，paeser替换之后还是'100分'，然后经过变为`formatter`'100分分钟'。
> 
> 删除后发生的错误是由错误的解析器引起的。
> 
> 默认解析器是
> 
> https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L14-L16
> 
> 你传入的解析器是
> 
> `value => value.replace('分钟', '')`
> 
> 当触发改变时，事件的值是'100分'，在用'100分'代替换行器后，然后`formatter`变为'100分分钟'。
> 
> https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L260-L271
> 
> https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L505-L512

你说的那个是defaultProps中的parser替换规则，我已经传入parser，那么他默认的parser函数已经被我传入的更新掉了，替换规则应该是用的value.replace('分钟', '')，而不是默认的input.replace(/[^\w\.-]+/g, '');，或者你说的我理解的不对，你能不能写一个正确的解析器，要求解析单位为两个字符以上的。谢谢

**Comment by muzea** [comment]
这里写的很清楚了，change里面的value实际是 '100分'，你的parser只处理了 '分钟'。

如果是说怎么解决这个问题，可以提供两个思路

- focus的时候去修正光标的位置
- focus的时候去掉formatter

我推荐后者，前者在复杂formatter的时候不好处理，这里给出[一个示例](https://codesandbox.io/s/xenodochial-davinci-5sebx)。

----
It is very clear here that the value in change is actually '100分', and your parser only processes '分钟'.

About how to solve this problem, I can provide two ideas.

- fix the position of the cursor when focus
- remove the formatter when focus

I recommend the latter. The former is not well handled in complex formatters. Here is an example [https://codesandbox.io/s/xenodochial-davinci-5sebx).

**Comment by MI-Class** [comment]
> 这里写的很清楚了，change里面的value实际是 '100分'，你的parser只处理了 '分钟'。
> 
> 如果是说怎么解决这个问题，可以提供两个思路
> 
> * focus的时候去修正光标的位置
> * focus的时候去掉formatter
> 
> 我推荐后者，前者在复杂formatter的时候不好处理，这里给出[一个示例](https://codesandbox.io/s/xenodochial-davinci-5sebx)。
> 
> It is very clear here that the value in change is actually '100分', and your parser only processes '分钟'.
> 
> About how to solve this problem, I can provide two ideas.
> 
> * fix the position of the cursor when focus
> * remove the formatter when focus
> 
> I recommend the latter. The former is not well handled in complex formatters. [Here is an example](https://codesandbox.io/s/xenodochial-davinci-5sebx).

你这个是能暂时解决我遇到的问题，但这个的本质并不是解析器错误或者使用错误的原因，onChange里面返回的value是‘分’的根本原因是‘分钟’按下删除键后把‘钟’字先删除了，然后返回了‘分’，所以造成了无法替换，正常应该是先替换，然后删除，官方的例子中单位只有一个字符，删除后返回了没有单位的数字，又在formater里又补上的单位，相当于光标左移一位，所以没有出现问题，多个字符的都会出现问题，我认为这个本质还是一个BUG

**Comment by muzea** [comment]
我上面说了原因，也贴了代码链接，**估计你也没看**。
"复杂formatter的时候不好处理"，此处指，光标位置（或者说操作位置）如何确定。
formatter可以做任意处理，同时你要在parser里面做对应的处理；并且我们只能拿到change event，却不知道他是如何变化的，比如在我使用的dde（deepin desktop environment）里面，可以一次输入多个字符（只触发一次change）；事件回调与parser也出现了割裂，要在这里面处理会很困难。比如当paser回调参数是'100分'但是state的value是'100'的时候，**你提供的parser**需要识别出**业务**在这里的实际意图是删除末尾的一个字符，这个时候parser应该返回'10'。

太长不看：这不是一个组件要处理的事情，onChange的参数实际是parser处理后的，实际是要**你传入的parser自行处理**。
最后，我推荐在 **focus的时候去掉formatter**。

----
This is a specific business problem, so I will not translate it.

**Comment by MI-Class** [comment]
> 我上面说了原因，也贴了代码链接，**估计你也没看**。
> "复杂formatter的时候不好处理"，此处指，光标位置（或者说操作位置）如何确定。
> formatter可以做任意处理，同时你要在parser里面做对应的处理；并且我们只能拿到change event，却不知道他是如何变化的，比如在我使用的dde（deepin desktop environment）里面，可以一次输入多个字符（只触发一次change）；事件回调与parser也出现了割裂，要在这里面处理会很困难。比如当paser回调参数是'100分'但是state的value是'100'的时候，**你提供的parser**需要识别出**业务**在这里的实际意图是删除末尾的一个字符，这个时候parser应该返回'10'。
> 
> 太长不看：这不是一个组件要处理的事情，onChange的参数实际是parser处理后的，实际是要**你传入的parser自行处理**。
> 最后，我推荐在 **focus的时候去掉formatter**。
> 
> This is a problem in a specific scenario, so I will not translate it.

谢谢，你发的源码我都看了，找到了问题所在，只需要在onChange函数最后一句 `onChange(this.toNumber(this.rawInput))`; 改为`onChange(this.getCurrentValidValue(this.rawInput))`就行了，组件中有解决这种情况的函数，我看只在失去焦点的时候用了，没有在修改的时候用
> 
Thank you, you send the source code I have read, found the problem, only need in the last onChange function `onChange(this.toNumber(this.rawInput));`To `onChange (enclosing getCurrentValidValue (enclosing the rawInput))`, the component of solve the function of this kind of circumstance, I think only when loses focus, not at the time of change

**Comment by muzea** [comment]
这不符合语义。

先说为啥看上去可以了。

https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L302-L312

`parseFloat('100分', 10)`，返回的是 `100`。

再说下为啥不能这么改。

- 三位加一个 ',' 的时候 `parseFloat('100,100', 10)` 返回 `100`
- https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L309 同步取了 value，但是value并不会随内部的change改变，它依赖 `componentWillReceiveProps`，只能在受控模式下使用，而且同步取value在输入速度快的时候没问题吗。。。

反正写出来的bug也不算我的，都行吧.webp

话说rc里面好多依赖`componentWillReceiveProps`的逻辑啊，antd4.0的升级来得及改掉吗。。。

PS:原本中午是在看setSelectionRange问题的，怎么就来回答这问题了。。。

**Comment by MI-Class** [comment]
> 这不符合语义。
> 
> 先说为啥看上去可以了。
> 
> https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L302-L312
> 
> `parseFloat('100分', 10)`，返回的是 `100`。
> 
> 再说下为啥不能这么改。
> 
> * 三位加一个 ',' 的时候 `parseFloat('100,100', 10)` 返回 `100`
> * https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L309 同步取了 value，但是value并不会随内部的change改变，它依赖 `componentWillReceiveProps`，只能在受控模式下使用，而且同步取value在输入速度快的时候没问题吗。。。
> 
> 反正写出来的bug也不算我的，都行吧.webp
> 
> 话说rc里面好多依赖`componentWillReceiveProps`的逻辑啊，antd4.0的升级来得及改掉吗。。。
> 
> PS:原本中午是在看setSelectionRange问题的，怎么就来回答这问题了。。。

对，这么改是不严谨，而且也不能输入小数了，如果真要修复这样的问题需要修改的地方挺多的

**Comment by muzea** [comment]
- `formatter`多种多样，组件无法做修改
- 这是业务问题，应由上层处理

**Comment by zombieJ** [comment]
`parser` 的目的就是为了让输入值通过提供的规则进行转换，无论是 `100分钟` 还是 `100分` 都是输入的值，都应该在 `parser` 里处理掉。

这不是 BUG，就像 @muze 说的，这是业务逻辑问题。不是组件 BUG。

**Comment by muzea** [comment]
@zombieJ 
![image](https://user-images.githubusercontent.com/7843281/59842874-ff079380-9389-11e9-9106-1befce7ce95c.png)

ID有提示的呀，为啥会打不对 QAQ

**Comment by MI-Class** [comment]
> `parser` 的目的就是为了让输入值通过提供的规则进行转换，无论是 `100分钟` 还是 `100分` 都是输入的值，都应该在 `parser` 里处理掉。
> 
> 就像 @muzE 说的，这是业务逻辑问题。不是组件 BUG。

你可以看下这个[例子](https://codepen.io/anon/pen/xoRyzB?&editable=true&editors=001)，如果光标在最右边，然后使用backspace，就会出错，我也写了parser进行规则替换，主要是如果替换的是单个字符是没有问题的，一个字符以上就会输出异常的内容了，删除数字没问题，只要不删除替换的字符就不会出错。
源码中
https://github.com/react-component/input-number/blob/9396c0c36e06c68ca363e6ea650c1df664bb79fe/src/index.js#L268
这里正常是应该通过parser转换回来的，但是因为字符被删了一个，无法匹配parser里的规则，所以造成无法转换回来。
所以才觉得是BUG，

**Comment by muzea** [comment]
朋友，`parser` 是一个函数，是你自己写的，`value => value.replace('分钟', '')`。
上面说了 **"当在input中触发change的时候，事件的value为 '100分'，parser替换之后还是 '100分'，然后经过 formatter 变为 '100分分钟'"**。
'parser替换之后还是 '100分'' 指的是 `'100分'.replace('分钟', '')` 的结果是 `'100分'`。

> 这里正常是应该通过parser转换回来的

- 传给 真实 `input` 的 `value` 是经过 `formatter` 转化的
- `change` 事件是浏览器触发的

我第一次回复贴了相关代码的。

换个说法就是，你的 `parser` 写错了，它没有覆盖到**所有的情况**。

说它是bug我觉得也行吧，但是组件没法帮用户cover掉。因为formatter可以加任何东西进去，不是只有后缀一个场景，也就是上面说的，这个一个具体的业务场景，应该由用户自行处理。

大概是我的表达能力有问题。

**Comment by MI-Class** [comment]
> 朋友，`parser` 是一个函数，是你自己写的，`value => value.replace('分钟', '')`。
> 上面说了 **"当在input中触发change的时候，事件的value为 '100分'，parser替换之后还是 '100分'，然后经过 formatter 变为 '100分分钟'"**。
> 'parser替换之后还是 '100分'' 指的是 `'100分'.replace('分钟', '')` 的结果是 `'100分'`。
> 
> > 这里正常是应该通过parser转换回来的
> 
> * 传给 真实 `input` 的 `value` 是经过 `formatter` 转化的
> * `change` 事件是浏览器触发的
> 
> 我第一次回复贴了相关代码的。
> 
> 换个说法就是，你的 `parser` 写错了，它没有覆盖到**所有的情况**。
> 
> 说它是bug我觉得也行吧，但是组件没法帮用户cover掉。因为formatter可以加任何东西进去，不是只有后缀一个场景，也就是上面说的，这个一个具体的业务场景，应该由用户自行处理。
> 
> 大概是我的表达能力有问题。

我也急死了，是哪里我没说清么？
先说结论：
第一、看**官网上举的例子**，官网是”100%“这种的，当光标在”%“右侧使用删除键，onchange中获取到的值是100，然后他使用了parser，相当于是**100.parser（”%“，”“）**，这个是没意义的（这就已经是BUG了,因为他相信用户删除的是数字，没有考虑删除到%的情况，直接对用户的输入进行了转换，没有进行判断），但是最终结果还是正确的是巧合，因为100经过parser之后还是100，但是，如果是光标在100右侧使用删除键，那onchange中获取到的值就是”10%“，经过“10%”.parser（”%“，”“），变成10，从这里应该能看出来，这一步处理的时候是相信用户只会在数字那里进行删除，不会把光标放在%后面进行删除，
还是你没看官方的举例，这个组件怎么用都是正常的，只是不能用删除键和Delete键，用了会出异常，官方举例是用的“%”,如果改成成“%%”，就会出错，但是当组件失去焦点就会变正常，说明组件内部是有应对这种情况的方法，只是再输入阶段没有使用
第二、这个组件假如说是用强类型语言去写，假如是java或者C#，那么onchange函数返回值应该是number（100），当formatter中替换字符为两个的时候，同时在输入的时候又删掉一个替换字符，这时候程序是要崩溃的，因为他的输出类型变成了字符串了（100分）。
第三、你第一次说的解决方案是能够解决这个问题，但是我想是违背了这个组件的用意，通过parser和formatter将数据来回转换，我感觉这个只是onchange里少了一个判断，判断用户是删除的数字，还是文字



第一种情况：我输入的100，经过formatter变成了100分钟，在change里setstate之前使用**parser将100分钟转换为100**，存储在rawInput中，返回为**数字类型的字符串**，经过formatter变成100分钟，在input中展现出来，当我删除一个0，变成10，经过同样的上述步骤都不会错。
第二种情况，同样的输入了100，变成了100分钟，我在钟字的后面使用删除键的时候，change里变成了”100分“，经过parser变成了**字符串**，这里相当于是最终返回的也是一个字符串，而不是数字类型的字符串，经过formatter变成了“100分分钟”，在input中展现出来，开始formatter是一个字符，比如是”100℃“经过同样的第二种情况，在”℃“右侧使用删除键，变成了”100“，经过parser之后还是100，实际这里的parser是没有用到的是100.parser（”%“，”“），是没有意义的，

**Comment by muzea** [comment]
嗯，你说的对。

**Comment by zombieJ** [comment]
`onChange` 是如果当前输入可以转成 number 就返回 number，反之返回当前被 parse 过的 string。目的是为了防止受控模式下，强制返回 number 导致用户输不进去的问题。并不一定是数字类型字符串。

**Comment by MI-Class** [comment]
> `onChange` 是如果当前输入可以转成 number 就返回 number，反之返回当前被 parse 过的 string。目的是为了防止受控模式下，强制返回 number 导致用户输不进去的问题。并不一定是数字类型字符串。

对，但是现在出现的问题就是他**没有返回被parse过的string**，因为删除操作使onChange中获取到的是**100分**，而不是**100分钟**，然后对获取到的值进行parse就匹配不到可以parse，返回的还是获取到的字符串

**Comment by zombieJ** [comment]
这里总结一下，目前的希望是光标在文字后，按删除键回到数字部分。这样理解是否正确？

**Comment by MI-Class** [comment]
> `onChange` 是如果当前输入可以转成 number 就返回 number，反之返回当前被 parse 过的 string。目的是为了防止受控模式下，强制返回 number 导致用户输不进去的问题。并不一定是数字类型字符串。

出现错误之后，只要组件失去焦点就能变回正常，我的想法是在onchange中进行parse之前进行一次判断，看parse之前和之后的有没有变化，如果没有变化就说明删到字符了，返回之前的value（像失去焦点时的做法一样），如果有变化，就说明是正常操作

**Comment by MI-Class** [comment]
> 这里总结一下，目前的希望是光标在文字后，按删除键回到数字部分。这样理解是否正确？

不回到数字也行，昨天我在onchange里修改了一下，提前进行判断，然后光标会自己向前移动一位，但是内容没有变化的，直到删除到数字才会有变化

**Comment by MI-Class** [comment]
> > 这里总结一下，目前的希望是光标在文字后，按删除键回到数字部分。这样理解是否正确？
> 
> 不回到数字也行，昨天我在onchange里修改了一下，提前进行判断，然后光标会自己向前移动一位，但是内容没有变化的，直到删除到数字才会有变化

只要不出现错乱就行，就像官网的那个例子里，在%后面按删除时没有变化的

**Comment by afc163** [comment]
这个光标问题不好解决，感觉 https://codesandbox.io/s/reverent-mclean-yckp6 才是最好的解决方式。

**Comment by muzea** [comment]
@MI-Class 
> 没有返回被parse过的string
实际上返回的就是parser处理过后的字符串，只是你提供的parser 没有处理 所有的场景

@zombieJ 
这个问题我仍然认为组件无法cover
formatter多种多样，并不是只有增加后缀一种形式

**Comment by muzea** [comment]
> 这个光标问题不好解决，感觉 https://codesandbox.io/s/reverent-mclean-yckp6 才是最好的解决方式。

![image](https://user-images.githubusercontent.com/7843281/59895520-79322980-9417-11e9-9b2c-f97cb6df75fc.png)

红红火火恍恍惚惚

**Comment by afc163** [comment]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/507615/59895676-0ffee600-9418-11e9-8d67-e4558dce438b.png">

这样好了。

**Comment by MI-Class** [comment]
> <img alt="image" width="665" src="https://user-images.githubusercontent.com/507615/59895676-0ffee600-9418-11e9-8d67-e4558dce438b.png">
> 
> 这样好了。

这样也可以，展示效果以及使用体验是一样的

**Comment by zombieJ** [comment]
嗯，现代游览器都支持 `type="number"`。是时候迁移一波了。

**Comment by muzea** [comment]
@zombieJ 
我前段时间才吹了InputNumber那个上下在hover的时候会变大（

这里的文档是不是应该提供一个更加复杂的示例，标注下增加后缀这种场景推荐用Input的suffix来实现？

**Comment by xeunglay** [comment]
:parser="value => value.replace(/[分钟]/g, '')"  使用正则替换 就可以了
