### ISSUE TITLE
Drawer component: afterVisibleChange is triggered twice

### ISSUE THREAD

**Issue by Leonsy** [ant-design/ant-design#17184]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/leonsy/pen/PrbBde](https://codepen.io/leonsy/pen/PrbBde)

### Steps to reproduce
Open the drawer by setting visible to true

### What is expected?
afterVisibleChange should be triggered only once 

### What is actually happening?
afterVisibleChange is triggered twice.

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8.6 |
| System | Mac Version 10.14: "Mojave" |
| Browser | Chrome 75.0.3770.80 |

**Comment by mohit-aicg** [comment]
happening to me again
