### ISSUE TITLE
timepicker不显示时分秒中的某个选项

### ISSUE THREAD

**Issue by mqliutie** [ant-design/ant-design#17185]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/time-picker-cn/](https://ant.design/components/time-picker-cn/)

### Steps to reproduce
选择timepicker

### What is expected?
时间pick现在是时分秒都要选, 可是我的需求可能只要小时和分 或者只要分和秒, 需要删掉某个部分(不是禁用,禁用用户还能看到)

### What is actually happening?
文档没有看到这样的参数

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.8.6 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
https://ant.design/components/time-picker-cn/#components-time-picker-demo-hide-column

**Comment by mqliutie** [comment]
我瞎了...sorry
