### ISSUE TITLE
关于Table列的一些建议

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design#17183]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在很多情况下，用户需要的并不是一个无滚动响应屏幕大小后可读性极差的table
如果列头或者关注的关键内容文字都是换行展示的会带来极差的体验

虽然当前可以通过 scroll 给列头定宽的方式解决 但期望可以增加一个属性来控制更好
抑或列头把对width的支持换成minWidth是否更好呢？

### What does the proposed API look like?
1.支持属性来生成无换行列头的table
2.column支持minWidth等属性

**Comment by yoyo837** [comment]
到这里讨论吧 #16911

**Comment by afc163** [comment]
Duplicate of #12088
