### ISSUE TITLE
Carousel is not compatible with IE 10

### ISSUE THREAD

**Issue by zhouzhonghao** [ant-design/ant-design#17189]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel/](https://ant.design/components/carousel/)

### Steps to reproduce
Use IE10 to open https://ant.design/components/carousel/

### What is expected?
The component works.

### What is actually happening?
The component is broken.

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.5.0 |
| System | Windows |
| Browser | IE 10 |

**Comment by zombieJ** [comment]
Official site not add polyfill with low version IE.  You should config your dist file target with related browser version: https://umijs.org/zh/config/#targets
