### ISSUE TITLE
上传文件（.zip）时某些浏览器下拿到的file.type是空值

### ISSUE THREAD

**Issue by chemdemo** [ant-design/ant-design#1718]
如题，

demo: https://codepen.io/dmyang/pen/NNVdbq

选择.zip格式的文件

正常情况下拿到正确值，即“application/x-zip-compressed”

但是在某些电脑的浏览器（chrome/firefox）下拿到的确是空值。

**Comment by superRaytin** [comment]
某些电脑？麻烦提供一下环境以及浏览器版本信息。

另外，beforeUpload 提供的是原生 File 对象，File 本身有其兼容性：https://developer.mozilla.org/en-US/docs/Web/API/File
