### ISSUE TITLE
antd-init初始化命令 报错      

### ISSUE THREAD

**Issue by qiansr** [ant-design/ant-design#1719]
peerDependencies WARNING [babel-preset-react-hmre@1.0.1] in /Users/qiansr/TEST/3S/blog/node_modules/.npminstall/babel-preset-react-hmre/1.0.1/babel-preset-react-hmre requires a peer of react@^0.14.1 but react@15.0.2 was installed

![image](https://cloud.githubusercontent.com/assets/13269138/15310707/5c465cfa-1c25-11e6-94b4-16374a776615.png)

**Comment by afc163** [comment]
@sorrycc 

https://github.com/danmartinez101/babel-preset-react-hmre/commits/master

升到 1.1 先。

**Comment by sorrycc** [comment]
已升级，dora-plugin-hmr@0.6

**Comment by afc163** [comment]
antd-init 也升级一下吧。

**Comment by sorrycc** [comment]
bumped antd-init@1.0.2
