### ISSUE TITLE
DatePicker 无法垂直居中

### ISSUE THREAD

**Issue by dandanhanzju** [ant-design/ant-design#17194]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://new-issue.ant.design/](http://new-issue.ant.design/)

### Steps to reproduce
                <div>
                    <Form layout="inline" onSubmit={this.handleSubmit}>
                        <Form.Item label="组员">
                            {getFieldDecorator('组员')(<Input />)}
                        </Form.Item>
                        <Form.Item style={{  height: "100%"}}>
                            <DatePicker format="YYYY-MM-DD"
                                        showTime={{ defaultValue: moment()}}
                                        defaultValue={moment()}
                                        style={{float:"right",   height: "100%" }}
                            />
                        </Form.Item>
                        <Form.Item>
                            {getFieldDecorator('提交')(<Button type="primary" htmlType="submit">
                                搜索
                            </Button>)}
                        </Form.Item>
                    </Form>
                </div>

### What is expected?
DatePicker 能够在表单中垂直对其

### What is actually happening?
只有 DatePicker 在表单中不能垂直对其

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8.6 |
| System | ubuntu 18.4 |
| Browser | chrome |

**Comment by dandanhanzju** [comment]
@yutingzhao1991 直接在你的链接里面创建吗？https://codesandbox.io/s/antd-reproduction-template-kn3s0?fontsize=14

**Comment by houshiduo** [comment]
You can try delete
`
style={{ float: "right", height: "100%" }}
`
