### ISSUE TITLE
Form表单中同时设置pattern和max验证规则时，浏览器会崩溃

### ISSUE THREAD

**Issue by xyhxyw** [ant-design/ant-design#17195]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cqs4u)

### Steps to reproduce
1 如链接所示，设置pattern验证规则，同时设置max为25（注意：当max>=25会出现卡死，max<=10左右，验证正常）。
2 连续输入字符，直到出现第一个错误提示“请输入名称”，然后敲空格键，此时，浏览器会直接卡死。
3 当去掉pattern这个规则时，验证又恢复了正常，浏览器不会卡死。

### What is expected?
可以正常验证且浏览器不会卡死。

### What is actually happening?
浏览器卡死

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8.6 |
| System | window7 |
| Browser | Chrome75 |

---
该情况在antd多个版本中测试均出现。

**Comment by zombieJ** [comment]
是你的正则性能太差卡死了，直接开个 console 跑一下：
```js
/^[^\s]+(.*[^\s]+)*$/.test('111111111111111111111111111 ');
```

**Comment by xyhxyw** [comment]
非常感谢，已经修正新的验证规则。
let reg = /^[^\s]$|^[^\s].*[^\s]$/；
console.log(reg.test("111111111111111111111111111111111111111  " ));
