### ISSUE TITLE
Modal.confirm okButtonProps bug

### ISSUE THREAD

**Issue by zouxiaomingya** [ant-design/ant-design#17193]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zouxiaomingya/pen/YopBby?editors=0010](https://codepen.io/zouxiaomingya/pen/YopBby?editors=0010)

### Steps to reproduce
1.clekc confirm buton
2.modal the confirmation button style exception, click elsewhere, button color change

### What is expected?
Verify that the button style is the same as the button component： Button type="danger">确认</Button

### What is actually happening?
hover No styling changes
There's an extra border

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8 |
| System | 64 |
| Browser | google |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16857#issuecomment-496806000
https://github.com/ant-design/ant-design/issues/16297#issuecomment-486567040
