### ISSUE TITLE
Breadcrumb 不支持react-router  1.x

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design#172]
Warning: Failed Context Types: Invalid context `router` of type `object` supplied to `Breadcrumb`, expected `function`. Check the render method of `ProdForecast`.

**Comment by yiminghe** [comment]
Breadcrumb 单纯点，不要和 react-router 绑定了

**Comment by afc163** [comment]
http://ant.design/components/breadcrumb/ 支持最单纯的用法。

**Comment by yiminghe** [comment]
现在和 react-router 1.x 不兼容，有warning，把绑定代码删掉

**Comment by yiminghe** [comment]
何苦一定要和 react-router 绑定，我们实际项目中 和 router 是对不起来的

**Comment by afc163** [comment]
能用的上的话，会很方便的。面包屑天生依赖 router 的数据。https://github.com/rackt/react-router/issues/404
