### ISSUE TITLE
Descriptions组件是否可以提供超出区域溢出省略 鼠标hover Tooltip 提示全部文本

### ISSUE THREAD

**Issue by wangxingkang** [ant-design/ant-design#17204]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Descriptions组件是否可以提供超出区域溢出省略 鼠标hover Tooltip 提示全部文本

比较常见的场景 有的文本并不想换行

### What does the proposed API look like?
<Descriptions.Item ellipsis showTooltip label="Product">Cloud Database</Descriptions.Item>

**Comment by zombieJ** [comment]
用 Typography 组件，提供了 ellipsis
