### ISSUE TITLE
请问Table组件加载树形数据能否像Tree和TreeSelect组件一样提供一个loadData异步加载数据函数

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design#17201]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table组件加载树形数据，例如加载省份，城市，地区多层数据时，一次性渲染页面太慢，甚至造成页面卡死，希望Table组件也像Tree和TreeSelect组件一样提供一个loadData异步加载数据函数。解决大数据量页面渲染卡死现象。

### What does the proposed API look like?
希望Table组件也像Tree和TreeSelect组件一样提供一个loadData异步加载数据函数。
![image](https://user-images.githubusercontent.com/37643958/59833289-57ce3080-9378-11e9-8746-68ab6f6eb0fe.png)

**Comment by afc163** [comment]
用 `onExpand` 即可。
