### ISSUE TITLE
Menu导航菜单的递归生成菜单，hover时背景增加颜色

### ISSUE THREAD

**Issue by 007GitHu** [ant-design/ant-design#17205]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
hover同时增加背景颜色更明显的知道当前鼠标位置，如果仅仅是改变字体颜色，比较单调而且不是很明显

### What does the proposed API look like?
类似于树组件的鼠标在树节点名称的hover效果，内部实现，不提供api对外开放

**Comment by afc163** [comment]
建议进行样式覆盖。
