### ISSUE TITLE
Slider 在IE10 显示报错

### ISSUE THREAD

**Issue by liuxing95** [ant-design/ant-design#17219]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider-cn/](https://ant.design/components/slider-cn/)

### Steps to reproduce
IE10 打开 https://ant.design/components/slider-cn/

### What is expected?
正常显示

### What is actually happening?
TypeError: 无法获取未定义或 null 引用的属性“value”

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8.3 |
| System | windows |
| Browser | IE10 |

**Comment by Chenjiayuan195** [comment]
我也遇到了，在IE9和IE10上都无效，想请问下，该如何解决这个问题

**Comment by liuxing95** [comment]
react-input-range

我用的另外的组件库


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jiayuan Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午3:35
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"MVP star"<1358974006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Slider 在IE10 显示报错 (#17219)




我也遇到了，在IE9和IE10上都无效，想请问下，该如何解决这个问题

**Comment by yoyo837** [comment]
我自己都懒得兼容IE11一下了... 😂

**Comment by liuxing95** [comment]
IE11 下还好点，最可怕的是要兼容IE9




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Amumu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午3:41
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"MVP star"<1358974006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Slider 在IE10 显示报错 (#17219)




我自己都懒得兼容IE11一下了... 😂

**Comment by Chenjiayuan195** [comment]
我们就是可怕的那一批，需要兼容IE9，IE10

**Comment by Chenjiayuan195** [comment]
目前都已经兼容了，就差这个Slider组件了，flex确实支持不了，用的栅格布局

**Comment by liuxing95** [comment]
我这边有时候也要兼容IE，要不加个微信吧，有问题交流下


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jiayuan Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午4:26
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"MVP star"<1358974006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Slider 在IE10 显示报错 (#17219)




目前都已经兼容了，就差这个Slider组件了，flex确实支持不了，用的栅格布局

**Comment by Chenjiayuan195** [comment]
可以，我邮件你吧，邮箱是你的个人信息里的吗

**Comment by liuxing95** [comment]
17625909724 你加我吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jiayuan Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月5日(星期二) 下午4:38
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"MVP star"<1358974006@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Slider 在IE10 显示报错 (#17219)




可以，我邮件你吧，邮箱是你的个人信息里的吗

**Comment by afc163** [comment]
3.x 不再维护了，4.x 也不支持 IE10 了，这里关掉了。
