### ISSUE TITLE
DatePicker 在 iframe中不能选择日期, 在使用 <ConfigProvider getPopupContainer={() => top.document.body}> 时

### ISSUE THREAD

**Issue by angular-moon** [ant-design/ant-design#17216]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hc215)

### Steps to reproduce
* codesandbox 不能加载iframe页面, 请下载运行
1. 在页面内 DatePicker 不能选择日期
2. 点击 open modal, 在 Modal 中 DatePicker 不能选择日期

### What is expected?
DatePicker 能正常工作

### What is actually happening?
DatePicker 不能选择日期

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | window 10 |
| Browser | chrome 版本 75.0.3770.100（正式版本） |

**Comment by zzxiexin** [comment]
这个问题解决了吗  老哥  我也遇到了这个问题

**Comment by zzxiexin** [comment]
@zombieJ @ant-design-bot @jhsu 这个问题怎么解决啊  求教
