### ISSUE TITLE
Circle progress bar does not animate when set to "active"

### ISSUE THREAD

**Issue by ben-deng** [ant-design/ant-design#17213]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/PrWBRJ?&editable=true&editors=001](https://codepen.io/anon/pen/PrWBRJ?&editable=true&editors=001)

### Steps to reproduce
Set a circular progress bar's status to active and you see that the stroke color changes to a lighter blue but does not animate.

### What is expected?
The color is expected to animate from a darker blue to a lighter blue as demonstrated in the line progress.

### What is actually happening?
The progress bar is stuck at the initial light blue color - it does not change to a darker blue color.

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8.6 |
| System | Windows 10 1809 |
| Browser | Chrome 75.0.3770.100 |

---
The API documentations indicate that status is an attribute shared by all progress types. If animation is only supported in line chart then it should be indicated appropriately.

**Comment by zombieJ** [comment]
Circle don't have `active` status. Doc should update for this.
