### ISSUE TITLE
onChange not rendering with AutoComplete box

### ISSUE THREAD

**Issue by ulsha** [ant-design/ant-design#17210]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-l14vn?fontsize=14)

### Steps to reproduce
Click on the first input box an enter something. onStockChange is actually called as can be seen from the console log.

Click on the second input box. Select something (e.g. UBER). The value changes to UBER as demonstrated on the side. However, the onStockChange event is actually never called which means that I cannot POST the input to my API. This is despite calling <AutoCompleteBox onChange={this.onStockChange} />. 

### What is expected?
the event onStockChange should be called when the AutoCompleteBox is changed, otherwise I am not able to post it.

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.4 (18E226) |
| Browser | 74.0.3729.169 (Official Build) (64-bit) |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-eve5z
