### ISSUE TITLE
InputNumber组件中格式化输出功能使用删除键会出现异常输出

### ISSUE THREAD

**Issue by MI-Class** [ant-design/ant-design#17214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/vqgvBJ?&editable=true&editors=001](https://codepen.io/anon/pen/vqgvBJ?&editable=true&editors=001)

### Steps to reproduce
![image](https://github.com/MI-Class/Mvc/blob/dev/11.gif)
在输入框最右侧，文本的右侧使用删除键，就会出现问题。比如本来是”100分钟“，使用一次删除键之后变成”100分分钟”
### What is expected?
期望能正常使用删除键不出现异常

### What is actually happening?
使用删除键如果删除到文本的时候会输出一样

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.7.0 |
| System | win10 |
| Browser | firefox67.0.3 |

---
格式化输入后面跟的是单位名称，比如KG，ppm，r/m,s/m等

**Comment by zombieJ** [comment]
修改一下 `parser` 逻辑：https://codesandbox.io/s/still-dawn-v1bg0

另外，可以继续在 #17188 里讨论。当前的格式化的逻辑是符合预期的，用户使用 `parser` 和 `formatter` 时需要自己处理逻辑。 InputNumber 只是两头对接一下。

Duplicate of #17188

**Comment by afc163** [comment]
光标的问题不好解决，下面那个 Input 还是删不掉，或者我们要在 focus 的时候把光标定位到数字的最后去。

**Comment by afc163** [comment]
有趣的是，当我用 <kbd>←</kbd> 把光标向左移动一格之后，再按 <kbd>DEL</kbd> 删除时，这时候就可以删数字了。所以我们可以想办法在『钟』后按 <kbd>DEL</kbd> 时，向前移动相应的光标位置。

**Comment by zombieJ** [comment]
开错了，重开 #17188 去

**Comment by Cxz0** [comment]
我最近也遇到了这个问题，发现可以这样parser={value => value.replace(/[^.\d]/g, '')}，用正则表达式替换掉所有非数字和小数点的部分
