### ISSUE TITLE
Cascader creates duplicate options on search

### ISSUE THREAD

**Issue by johnpc** [ant-design/ant-design#17212]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gist.github.com/johnpc/3032817275224913b3f1cfab17b18748](https://gist.github.com/johnpc/3032817275224913b3f1cfab17b18748)

### Steps to reproduce
Reproduce with the following steps:

1. npx create-react-app antd-bug
2. cd antd-bug
3. npm install antd && yarn add antd
4. copy this code into into src/index.js
5. npm start

Navigate to localhost:3000, add and remove "op" from the search box, notice that duplicate options are being added.

See example in [video form](https://www.youtube.com/watch?v=bc9fT4T87ek) or in [gif form](https://jpc.io/r/antd-bug.gif)

### What is expected?
The list of options should be filterable

### What is actually happening?
When filtering, duplicate items are created in the list

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | 16.8.6 |
| System | Mac 10.14.5 |
| Browser | Chrome 74.0.3729.169 |

**Comment by wmwilcox** [comment]
sandbox link: https://codesandbox.io/s/antd-reproduction-template-nkxyn

**Comment by johnpc** [comment]
Thanks @wmwilcox

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-hvish

**Comment by afc163** [comment]
PR is welcome

**Comment by zombieJ** [comment]
Seems `value` not provided: https://codesandbox.io/s/antd-reproduction-template-q4xxe

**Comment by zombieJ** [comment]
Should add warning if user not set `value` in options.

**Comment by johnpc** [comment]
Thanks! That makes sense - I saw the warning from React that there were duplicate keys, just didn't notice that the `option.value` was used to populate that.
