### ISSUE TITLE
Can we have a maxLength api in Input component?

### ISSUE THREAD

**Issue by YuFF2018** [ant-design/ant-design#17220]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when we use Input, we can see the content length currently and the maxLength, which is shown in the end of the Input.

### What does the proposed API look like?
```
<Input maxLength={30} hasLimitHint  />
// 有最大长度样式，可以显示当前输入内容长度和设置输入内容的最长长度
```

**Comment by afc163** [comment]
Yes, we support: https://codesandbox.io/s/yk7xzy9pr1

About chars calculator: https://github.com/ant-design/ant-design/issues/8148#issuecomment-372190822
