### ISSUE TITLE
关于react版与vue版auto-complete组件，在IE11下，导致内存增加问题

### ISSUE THREAD

**Issue by lettywiterock** [ant-design/ant-design#17224]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/auto-complete-cn/](https://ant.design/components/auto-complete-cn/)

### Steps to reproduce
制作临时的对象数组，然后通过demo进行输入，然后跳转路由再回来，内存没有清空，并且继续增加，一次几M，有时候10M左右
vue生命周期销毁之后，在创建，内存没有释放。

### What is expected?
重新输入，清空上一次的缓存

### What is actually happening?
每次进行检索，都会增加一些内存，并且短时间不会回收。在IE11下

| Environment | Info |
|---|---|
| antd | 3.19.6 |
| React | ^16.8.6 |
| System | windows 10 |
| Browser | IE11 |

---
IE需要兼容希望能提供销毁方法

**Comment by afc163** [comment]
是反馈 vue 的问题还是 react 的问题呢？

**Comment by lettywiterock** [comment]
> 是反馈vue的问题还是react的问题呢？

react 与vue 两个版本组件都有，并且在官网的案例使用IE11打开，也可以复现，跳转路由并没有释放缓存。

**Comment by lettywiterock** [comment]
在IE11浏览器下每次更换搜索的value，多搜索几次，内存稳定增长几M，
在QQ浏览器IE11内核（360极速浏览器IE11内核）下增长是双倍的.
别切通过频繁切换路由，每一次的缓存都会叠加

**Comment by afc163** [comment]
可以帮忙排查一下，最好能直接发个 PR。

**Comment by afc163** [comment]
试试 antd v4 版本的 AutoComplete，我们重现了底层应该不会有内存的问题了。
