### ISSUE TITLE
DatePicker 的format 属性支持函数

### ISSUE THREAD

**Issue by akalittle** [ant-design/ant-design#17222]
### What problem does this feature solve?
在我的一个场景下面。
当用户选择一个时间的时候。希望展示 具体的时间 和 这个时间距离现在相差多少日。

### What does the proposed API look like?
```javascript
format: (moment)=> `YYYY-MM-DD  ${timeago.format(moment)}`
```

**Comment by afc163** [comment]
#14455

需求还是蛮常见的，应该可以支持一下。

**Comment by hengkx** [comment]
这个有人在 处理吗？ 没有 我改一下

**Comment by Kermit-Xuan** [comment]
我正在处理

**Comment by afc163** [comment]
Any progress?

**Comment by Kermit-Xuan** [comment]
麻烦先review一下这个PR [#599](https://github.com/react-component/calendar/pull/599)  这个是依赖，这个没问题了，我再改这个里面的.  @afc163

**Comment by likepearl** [comment]
format={`YYYY-MM-DD  ${timeago.format(currentDate)}`}
onChange的时候保存日期到状态currentDate， 这样就可以了

**Comment by TIS-OMiddle** [comment]
@Kermit-Xuan 大佬现在还在跟这个问题吗。现在RangePicker卡在这里了，由于要同时修改开始时间和结束时间的文本，动态设置`format`字符串不太好使，需要一个format函数来搞

**Comment by Kermit-Xuan** [comment]
Supported in https://github.com/react-component/picker/pull/142#partial-timeline

使用自定义 format 的时候，函数返回的字符串会直接用于展示。

例如：

``` js
(moment)=> `custom format: YYYY-MM-DD`
```

渲染到 input 中的效果直接是 `'custom format: YYYY-MM-DD'`，如果想解析 `'YYYY-MM-DD'` 需要这样写：

``` js
(moment)=> `custom format: ${moment.format('YYYY-MM-DD')}`
```

由于不同的日期库（moment、dayjs、dateFns）对应的日期格式可能不太相同，所以对于 format 函数返回的字符串我们不会对其进行二次解析，而是直接渲染到 input。
