### ISSUE TITLE
CheckableTag  onChange 事件应该提供获取完整的 Event 属性，而不是仅提供一个布尔值

### ISSUE THREAD

**Issue by dyygtfx** [ant-design/ant-design#17235]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果把 CheckableTag 当作 CheckboxGroup 来用的话，他没有 CheckboxGroup 这么强大，比如想要获取 CheckableTag 上的 ID 的话必须得这么写 `onChange={checked => handleTag(checked, id) }`，因为获取不到完整的事件属性，不能用 ` data-xx ` 方式传递和获取数据。

### What does the proposed API look like?
``` 
handleChange = e => {
    this.setState({ e.target.checked });
  };
```
或者 checked 和 event 分开来
``` 
handleChange = (checked, event) => {
    this.setState({ checked });
  };
```

**Comment by afc163** [comment]
`onChange={checked => handleTag(checked, id) }`

这样写是对的，不是所有组件都有完整的 event 对象，即使有 event 对象也推荐这样写。

**Comment by dyygtfx** [comment]
行吧，既然你们这么认为的。不过为啥建议有 event 对象也推荐这样写呢？我的习惯就是避免在render  里面写箭头函数，因为它和在  render 里面 bind this 效果是差不多的，应该也是不被推荐的，不知道为啥你这么说。
还有一个 就是你们文档里面说 CheckableTag 可以实现类似 Checkbox 的效果，但是如果有一个 tagList 的时候，要实现 Checkbox.Group 效果就不方便了。我大概试了一下

```js
const onChangeTag = (e, id) => {
        if (checkedTagIds.includes(id)) {
            checkedTagIds.splice(checkedTagIds.indexOf(id), 1);
            setCheckedTagIds(checkedTagIds);
        } else {
            checkedTagIds.push(id);
            setCheckedTagIds(checkedTagIds);
        }
       setParams({ ...params, tag_id: checkedTagIds.join(',')});
}
```

```js
 { tagList.map(item => (
        <CheckableTag key={item.id} checked={checkedTagIds.includes(item.id)} onChange={e => onChangeTag(e, item.id)}>{item.name}</CheckableTag>
))}
```
我觉得用 Tag 组件，应该很容易遇到这个 tagList 场景， 个人觉得在不动 CheckableTag 的情况下，可以额外弄一个 Tag.Group 来处理这种场景。
