### ISSUE TITLE
tag component is very tiny and small and must be a little bigger to seem good

### ISSUE THREAD

**Issue by aminabvaal** [ant-design/ant-design#17231]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
hello guys...
tag component is very tiny as mush Users's eyes have a problem and does not seems good.
it is beautiful but is very small ..and it is better to get some larger widthically and heightically and fonttically(it means increase amount of them):))

thanks for attempting to first react design

### What does the proposed API look like?
hello guys...
tag component is very tiny as mush Users's eyes have a problem and does not seems good.
it is beautiful but is very small ..and it is better to get some larger widthically and heightically and fonttically(it means increase amount of them):))

thanks for attempting to first react design

**Comment by aminabvaal** [comment]
@yesmeck  :/

**Comment by afc163** [comment]
You can try to customzie theme: https://ant.design/docs/react/customize-theme
