### ISSUE TITLE
allow passing classname to Descriptions.Item

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#17234]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
a lot of times for a particular description item, you want to change the style, like set background to a different color based on value.
passing in a css style would accomplish this. 

### What does the proposed API look like?
```
<Descriptions.Item key={dim} label={label} className={cssStyle}>{v}</Descriptions.Item>
```

**Comment by yoyo837** [comment]
@afc163 

https://ant.design/components/descriptions-cn/#components-descriptions-demo-border

拆成俩className么？

**Comment by afc163** [comment]
@yoyo837 没看懂你的回复。

这个 issue 透传上 className 就行了。
