### ISSUE TITLE
Table filters provide function to get filter options

### ISSUE THREAD

**Issue by ycjcl868** [ant-design/ant-design#17246]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

#16552

### What problem does this feature solve?
I want to get different filter options according to the data from back-end server, if not provide function, I just write all filter enum options 

https://codesandbox.io/s/prod-glade-i4538

### What does the proposed API look like?
filters: (record) => { ... }

**Comment by zombieJ** [comment]
Could you give a sample of record level filters return?

**Comment by ycjcl868** [comment]
Use datasource instead.
