### ISSUE TITLE
Allow passing color props to UI components

### ISSUE THREAD

**Issue by HassanNemir** [ant-design/ant-design#17243]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I wonder if a feature of adding colors directly to UI components could be added, it will save the effort of editing the colors in style files specially that everybody uses css in a different way.

### What does the proposed API look like?
```
<Search
          placeholder="Type an interest"
          enterButton="Search"
          style={{ width: "300px" }}
          onSearch={value => console.log(value)}
          className="middle"
          color="red"
        />
```
That would change the blue button color to red directly, and also changes the outline color of the input field to red.

**Comment by afc163** [comment]
You can try theme customization or just override our styles.

https://ant.design/docs/react/customize-theme
