### ISSUE TITLE
Carousel lazy loading (anticipated)

### ISSUE THREAD

**Issue by flieks** [ant-design/ant-design#17242]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-ts3gj)

### Steps to reproduce
put 
lazyLoad = "anticipated"
on <Carousel>

### What is expected?
it working like in react-slick because antd uses this component
http://jsfiddle.net/dyfpt14j/

### What is actually happening?
it loads the next image when it slides to it

| Environment | Info |
|---|---|
| antd | 3.19.7 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | opera 60.0.3255.170 |

---
link to react-slick issue: https://github.com/akiran/react-slick/pull/1496

**Comment by pancho111203** [comment]
I'm having the same problem

**Comment by afc163** [comment]
react-slick don't support `lazyLoad="anticipated"` in it's offcial documentation: https://react-slick.neostack.com/docs/api#lazyLoad

**Comment by pancho111203** [comment]
@afc163 The official slick repository does: https://github.com/kenwheeler/slick/commit/5315900bed2a20b3fdf0b2335d85036ed2e49fad

**Comment by afc163** [comment]
We follow react-slick documentation and implementation.

**Comment by mattg66** [comment]
Can this please be added, It is supported in the official repository. https://github.com/kenwheeler/slick/releases/tag/1.7.1
