### ISSUE TITLE
typescript errors when upgrading antd to 3.19.7

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#17245]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com](https://github.com)

### Steps to reproduce
use:
"typescript: 3.5.2"
"@types/react": "16.8.22",
    "@types/react-dom": "16.8.4",

tons of compile errors.
errors go away when u downgrade to 3.19.6

### What is expected?
no errors as before in v3.19.6

### What is actually happening?
tons of typescript errors that go away when downgrade to 3.19.6

| Environment | Info |
|---|---|
| antd | 3.19.7 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome |

**Comment by grahnj** [comment]
I'm seeing the same issues after some refactoring today. Introducing `unknown` types in `FormComponentProps` specifically is causing a significant amount of my regressions.

**Comment by keke122765** [comment]
I encountered the same problem in ant design pro. Is there any solution?

**Comment by grahnj** [comment]
Reverting to 3.19.6 resolved the issue in antd.

**Comment by keke122765** [comment]
Any other solutions? Not to downgrade antd, because the upgrade is to standardize typescript. See https://ant.design/changelog-cn

**Comment by keke122765** [comment]
Any other solutions? Not to downgrade antd, because the upgrade is to standardize typescript. See https://ant.design/changelog-cn

**Comment by grahnj** [comment]
I can’t speak to all the changes that were made, but in my case I would’ve had to cast every time I referenced an unknown type (like getFieldValue).

Regardless of the intent to make the Typescript standardized (and I appreciate the commitment to Typescript), I’m not thrilled about breaking changes being introduced in a patch version. I suspect that’s why this was raised as an issue in the first place.

**Comment by keke122765** [comment]
I am Chinese, my English is not good, may not understand your meaning, but thank you very much

**Comment by afc163** [comment]
Any reproduce?

**Comment by afc163** [comment]
@pdeva @keke122765 @grahnj 

Could U guys help to confirm #17249 fix your problem? Is there anything I miss?

**Comment by ztplz** [comment]
As my understanding, `any` is assignable to `unknown`, but `unknown` isn’t assignable to `any` but itself and `any` without a type assertion or a control flow based narrowing. When replacing `any` with `unknown`, we  need asserting or narrowing to a more specific type.

**Comment by y-takey** [comment]
I got other type error. `TS2559: Type '{ index: number; moveRow: (dragIndex: any, hoverIndex: any) => void; }' has no properties in common with type 'TableEventListeners'.`
That is `onRow` of `Table` component.

Definition in 3.19.6: https://github.com/ant-design/ant-design/blob/3.19.6/components/table/interface.tsx#L168

```tsx
export interface TableProps<T> {
  ...
  onRow?: (record: T, index: number) => any;
```

Definition in 3.19.7: https://github.com/ant-design/ant-design/blob/3.19.7/components/table/interface.tsx#L176

```tsx
export interface TableProps<T> {
  ...
  onRow?: (record: T, index: number) => TableEventListeners;
  ...
}

export interface TableEventListeners {
  onClick?: (arg: React.SyntheticEvent) => void;
  onDoubleClick?: (arg: React.SyntheticEvent) => void;
  onContextMenu?: (arg: React.SyntheticEvent) => void;
  onMouseEnter?: (arg: React.SyntheticEvent) => void;
  onMouseLeave?: (arg: React.SyntheticEvent) => void;
}
```

However, when drag sorting, `onRow` is `(record, index) => ({ index, moveRow: (dragIndex, hoverIndex) => void })`.
https://ant.design/components/table/#components-table-demo-drag-sorting

**Comment by afc163** [comment]
@y-takey https://github.com/ant-design/ant-design/pull/17249/commits/8678c6acc0e64c2dc940fc7d158dfa790f788bff

**Comment by afc163** [comment]
More information about new `unknown` type: https://github.com/ant-design/ant-design/issues/14044

https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type

**Comment by y-takey** [comment]
@afc163 Thanks for the quick response :)
