### ISSUE TITLE
TimePicker with a range option

### ISSUE THREAD

**Issue by RubenMateus** [ant-design/ant-design#17256]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The idea comes from wanting to have an option to create a range of time using Time instead of Dates.
Example: Opening and closing hours of a restaurant or an office, there doesn't seem to exist a good option in ant design for that.

### What does the proposed API look like?
I don't know. I just had the idea, but I will gladly participate in the discussion

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/4524#issuecomment-480576884
