### ISSUE TITLE
Fragment 包裹的元素进行 setFieldsValue 会导致 getFieldsValue 变为{}

### ISSUE THREAD

**Issue by zjafei** [ant-design/ant-design#17255]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-44ogu?fontsize=14)

### Steps to reproduce
删除后重新修改值

### What is expected?
getFieldsValue 获取正常值

### What is actually happening?
getFieldsValue 变为{}

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.8.6 |
| System | windows10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
`getFieldDecorator` 跟的是一个受控组件。如果子元素需要传递一个 React.Fragment，你需要将其同样封装成一个组件来使用。
ref: https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
