### ISSUE TITLE
Modal.confirm and message Use them together and you get bugs

### ISSUE THREAD

**Issue by zouxiaomingya** [ant-design/ant-design#17250]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zouxiaomingya/pen/pXPNQR?editors=0111](https://codepen.io/zouxiaomingya/pen/pXPNQR?editors=0111)

### Steps to reproduce
1.点击 Confirm 
2.点击确认

### What is expected?
message 不会移动

### What is actually happening?
点击确认之后，message 会移动。因为弹窗关闭的滚动条距离没有算

| Environment | Info |
|---|---|
| antd | 3.19.7 |
| React | 16.8 |
| System | 64 |
| Browser | google |

**Comment by zombieJ** [comment]
有点不太好处理，感觉修它会产生的副作用会比它本身大。
