### ISSUE TITLE
Antd React Upload component corrupt the .xlsx file

### ISSUE THREAD

**Issue by ZoeyanZh** [ant-design/ant-design#17268]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://ant.design/components/upload](http://ant.design/components/upload)

### Steps to reproduce
<FormItem>
    <Upload action="/fileupload?folder=xxx" showUploadList={false} onChange={(info)=>{this.uploadFiles(info,"xxx")}}> <Button type="primary"><Icon type="upload" />上传文件</Button> </Upload>
</FormItem>

### What is expected?
the .xlsx file uploaded to the linux server is not corrupted. And can be opened in Windows correctly when downloaded from the server.

### What is actually happening?
the .xlsx file is corrupted and can not be opened.

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.0.0 |
| System | Windows 10 |
| Browser | Google Chrome 75.0.3770.80 |

---
Our platform is python   react   antd.

**Comment by ZoeyanZh** [comment]
our code is:
<FormItem>
    <Upload action="/fileupload?folder=xxx" showUploadList={false} onChange={(info)=>{this.uploadFiles(info,"xxx")}}> <Button type="primary"><Icon type="upload" />上传文件</Button> </Upload>
</FormItem>
and the result is:
![image](https://user-images.githubusercontent.com/39585790/60004769-caece500-969f-11e9-9ff5-c112665c3720.png)

**Comment by afc163** [comment]
I don't think it is a antd problem.

**Comment by ZoeyanZh** [comment]
I've worked with the problem a couple days. The .xlsx file which is uploaded to the server is different from the original one. What can I figure out the key to the problem is the difference. May I ask what the problem you think is?

**Comment by yoyo837** [comment]
Check the read and write operations of the server in each step.

**Comment by ZoeyanZh** [comment]
OK. Thanks.

**Comment by zombieJ** [comment]
Since it's not antd issue. We can do nothing on this. Please follow @yoyo837 's advise to check which step cause it.
