### ISSUE TITLE
[Input] Disable chrome brower option to save password.

### ISSUE THREAD

**Issue by smartsoul** [ant-design/ant-design#17263]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use ant input such as <Input.Password placeholder="input password" />. Could it have a option to stop chrome brower to remember password?

### What does the proposed API look like?
<Input.Password placeholder="input password" noRemerberPassword />

**Comment by smartsoul** [comment]
A lot of product managers believe remembering password in brower is a security issue.
We have other complicated way to implement it. However, I hope to have a elegant way in ant design.

**Comment by afc163** [comment]
https://stackoverflow.com/a/15917221/3040605

Try `autoComplete="new-password"`.

**Comment by smartsoul** [comment]
@afc163 It doesn't work in chrome 75.

**Comment by afc163** [comment]
Try autoComplete="off"?

I afraid nothing we can do if Chrome cut off all approaches. :sad:

<img width="704" alt="image" src="https://user-images.githubusercontent.com/507615/59994538-ce27a700-9686-11e9-98e2-743facf2d531.png">

**Comment by smartsoul** [comment]
autoComplete="off", autoComplete="false", autoComplete="new-password" don't work. I have to use 'text' intead of 'password', then hide password and submit hidden username and password.

**Comment by afc163** [comment]
Closing for nothing we can do about it.

**Comment by internet5** [comment]
add <input type="password" style={{ position: 'absolute', left: -1000 }} /> in form,
it works success at chrome 90.0.4430.212
