### ISSUE TITLE
[Tree] The tree component wants to add the property treeData

### ISSUE THREAD

**Issue by xuyaofang** [ant-design/ant-design#17267]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
treeNodes 数据，如果设置则不需要手动构造 TreeNode 节点

### What does the proposed API look like?
在Tree组件添加TreeData属性，类似TreeSelect组件

**Comment by hengkx** [comment]
本身是支持的 文档没有写 提了pr  ,参考[https://codepen.io/anon/pen/rEYZKv?editors=1111](https://codepen.io/anon/pen/rEYZKv?editors=1111)
