### ISSUE TITLE
popover 在Table fixed 中展示的时候 popover content 中的点击事件 有时候不会触发

### ISSUE THREAD

**Issue by soeyi** [ant-design/ant-design#17266]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/async-glitter-r0oqp)

### Steps to reproduce
点击 Table 右侧fixed popover content中的蓝色区域。
有时候 会触发 onClick 事件 有时候不会触发onClick 事件

### What is expected?
每次都能够触发onClick 事件。

### What is actually happening?
不太稳定。有时候能够触发。有时候不会触发。

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8.6 |
| System | macos |
| Browser | chrome  74.0.3729.131 |

**Comment by afc163** [comment]
Duplicate of #9262
