### ISSUE TITLE
Table 的 rowSelection 希望透出 checkbox 或者 radio 的显示配置

### ISSUE THREAD

**Issue by SunShinewyf** [ant-design/ant-design#17272]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前 table 的 rowSelection 只有 columnWidth 和 columnTitle 还有 type （多选/单选，checkbox or radio） 的配置，但是在实际的项目中，其实还有一些特殊的显示逻辑，比如 checkbox 为 disabled 的时候显示 tooltip 提示告知原因（如下图），但是现在没有办法根据已有配置实现这个功能。
![image](https://user-images.githubusercontent.com/11244400/60006338-c70e9200-96a2-11e9-82ed-964053f93675.png)

### What does the proposed API look like?
rowSelection 透出一个 columnRender 的配置，可以让使用者自己配置该列的显示逻辑

**Comment by soeyi** [comment]
同样有这个需求。

**Comment by kun1992** [comment]
同样有这个需求，希望作者多出一个配置项，可以配置checkbox的位置，可以配置在表头的左边或者是右边。目前fixed还不能支持一些需求

**Comment by afc163** [comment]
Merge to #29287

**Comment by linmaorong** [comment]
这个问题解决了吗？

**Comment by linmaorong** [comment]
同样的需求

**Comment by mrlmx** [comment]
> 同样的需求

如果你的 antd 版本 ≥ 4.1.0，可以看一下这个 [Demo](https://codesandbox.io/s/table-row-tooltip-v79j2v)（官方解决方案）
