### ISSUE TITLE
Change the position of static elements of the table

### ISSUE THREAD

**Issue by deebov** [ant-design/ant-design#17279]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It gives ability to change the static elements ( row selection checkbox, expand row icon, etc ) of the table. As at the moment of writing this issue i found no API to do this. And we can't go further with our product as long as ant.design's table does not fit our design.

### What does the proposed API look like?
<Table rowSelection={{ position: 'first' }} expandRow={{ position: 2 }} />

**Comment by afc163** [comment]
I afraid you have to customize your own table based our plain Table.

**Comment by deebov** [comment]
> I afraid you have to customize your own table based our plain Table.

hey buddy, that was pretty possible. `react-component`'s `rc-table` provides such an API for this situation ( ant.design uses `react-component` under the hood ). https://react-component.github.io/table/ if you set `expandIconAsCell` to false you can configure the position of the expand icon via `expandIconColumnIndex` prop of the Table component
