### ISSUE TITLE
动态设置carousel dotPosition 高度会变化

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#17278]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel-cn/#components-carousel-demo-position](https://ant.design/components/carousel-cn/#components-carousel-demo-position)

### Steps to reproduce
先点击top，再点击left,最后点击bottom
![image](https://raw.githubusercontent.com/mraiguo/image-respository/master/bug/carousel.gif)
### What is expected?
高度不变化

### What is actually happening?
高度变化

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
问题不大，真实场景中不会这么切换。
