### ISSUE TITLE
关于less文件中backgroud rgba \9无法编译

### ISSUE THREAD

**Issue by ztyjr888** [ant-design/ant-design#17270]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/17269](https://github.com/ant-design/ant-design/issues/17269)

### Steps to reproduce
你好, 我使用webpack打包, 通过引入按需加载, 使用的时候报如下错误:
background: #fff;
background: rgba(0, 0, 0, 0.65) \9;
^
Unrecognised input
in \node_modules\antd\es\menu\style\index.css (line 247, column 34)

### What is expected?
编译成功

### What is actually happening?
background: #fff;
background: rgba(0, 0, 0, 0.65) \9;
^
Unrecognised input
in \node_modules\antd\es\menu\style\index.css (line 247, column 34)

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 15.6.1 |
| System | win10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
忽略已经编译过的css文件再次编译？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14300#issuecomment-454257792
