### ISSUE TITLE
在redux下，Form中的验证提示没有样式

### ISSUE THREAD

**Issue by yesuanzao** [ant-design/ant-design#1727]
1、如果不用getFieldError获取错误，则无法自动验证
2、ValidateStatus无法自动生成，hasFeedback不生效
this.context.form是空，为啥会丢失呢？
目前是在form组件上添加个form props解决

**Comment by superRaytin** [comment]
请提供可重现问题的 Demo: http://codepen.io/anon/pen/wGOWGW?editors=001，不然我们也无能为力

**Comment by yanglihuiylh102** [comment]
按如下步骤查找：
首先，是否添加如下代码：CustomizedForm（自己的组件） = Form.create({})(CustomizedForm);
其次，查看提交按钮的点击方法是否应用正确
`<Button type="primary" onClick={this.handleSubmit}>提交</Button>`
   与提交对应的方法
handleSubmit(e) {
    e.preventDefault();
    this.props.form.validateFieldsAndScroll((errors, values) => {
      if (errors) {
        return;
      }
    console.log(values) ;
   }
  }
然后还有一点getFieldProps()方法会占用该控件的onChange()的方法建议将getFieldProps()里的触发事件改为onSelect或者你想改成什么样就是什么样
```
          rules: [
            { required: true, message: '请选择项目' }
          ],
          trigger:'onSelect',
          validateTrigger:'onSelect'
```

**Comment by yanglihuiylh102** [comment]
你这个问题和Redux没有关系，好好检查下代码吧，

**Comment by afc163** [comment]
#1625
