### ISSUE TITLE
The Modal in V2.13.4 doesn't removeEventlistener when component unmount

### ISSUE THREAD

**Issue by kagawa23** [ant-design/ant-design#17285]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/2.x-stable/components/modal/Modal.tsx](https://github.com/ant-design/ant-design/blob/2.x-stable/components/modal/Modal.tsx)

### Steps to reproduce
On the reproduction link above, line 132,  The modal component registered an event handler on componentDidMount, but I do not see anywhere remove this listener.

### What is expected?
The modal is destroyed, the event listener should be removed.

### What is actually happening?
The modal is destroyed,  the event listener still exists, listen to the onClick event of the page

| Environment | Info |
|---|---|
| antd | 2.13.14 |
| React | 15.6.2 |
| System | macOS high sierra |
| Browser | chrome 75.0.3770.100 |

---
If this is not a bug, can you please explain to why does not need remove listener here?

**Comment by afc163** [comment]
Sorry, antd@2.x is not maintained any more.
