### ISSUE TITLE
Unable to uncheck checkbox inside of checkbox.group

### ISSUE THREAD

**Issue by elyfuentes27** [ant-design/ant-design#17282]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-506yi)

### Steps to reproduce
Create Checkbox.Group and Add multiple checkbox inside > checkbox.group.

### What is expected?
 Be able to uncheck all checked box 

### What is actually happening?
Unable to uncheck checked box

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8.6 |
| System | 10.13.6 |
| Browser | Version 75.0.3770 |

---
https://codesandbox.io/embed/antd-reproduction-template-506yi

**Comment by zombieJ** [comment]
When you use Checkbox.Group, `value` control is on the group instead of each single Checkbox.

**Comment by vuatintac** [comment]
my solution is put checkbox.group into state.
constructor(props) {
```
        super(props);
        this.state = {
defaultValue: [1,3,4]
}  }
```

//react will call componentDidMount before render() call
```
componentDidMount() {
    this.setState({
      CheckboxGenre: (
        <Checkbox.Group
          style={{ width: "100%" }}
          defaultValue={this.state.defaultValue}
          onChange={this.onChangeGenre}>
          <Checkbox value={1}>Option 1</Checkbox>
          <Checkbox value={2}>Option 2</Checkbox>
          <Checkbox value={3}>Option 3</Checkbox>
          <Checkbox value={4}>Option 4</Checkbox>
          <Checkbox value={5}>Option 5</Checkbox>
        </Checkbox.Group>
      )
    });
  }
```
onchange() function
```
  onChangeGenre(checkedValues) {
    this.setState({
      selectedGenres: checkedValues
    });
    //console.log('checked = ', checkedValues);
    console.log("this.state.selectedGenres = ", this.state.selectedGenres);
  }
```
On render()
```
render() {
    return <div>{this.state.CheckboxGenre}</div>;
  }
```

complete code: 
[![Edit exciting-ellis-jn8tv](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exciting-ellis-jn8tv?fontsize=14&hidenavigation=1&theme=dark)
