### ISSUE TITLE
Progress type='circle' 不能设置strokeColor 为渐变色

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#17286]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/small-snow-j6ij6)

### Steps to reproduce
https://ant.design/components/progress-cn/#API
![image](https://user-images.githubusercontent.com/46179450/60077147-ea494800-975b-11e9-9692-d167dac7184a.png)

### What is expected?
Progress type='circle' 能设置strokeColor 为渐变色

### What is actually happening?
Progress type='circle' 不能设置strokeColor 为渐变色

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | latest |
| System | windows10 |
| Browser | chrome74 |

**Comment by afc163** [comment]
👍，可以用这种方式实现：https://codepen.io/plava/pen/BjavpN

可以帮我们来个 PR 么？

**Comment by XianZhengquan** [comment]
我看看  哈哈

**Comment by afc163** [comment]
ref https://github.com/ant-design/ant-design/pull/15524#issuecomment-474826480

**Comment by XianZhengquan** [comment]
@afc163 老哥，现在在赶项目，估计 帮不到你哦

**Comment by afc163** [comment]
supported in https://github.com/ant-design/ant-design/pull/17315
