### ISSUE TITLE
调试相关

### ISSUE THREAD

**Issue by liujian10** [ant-design/ant-design#1728]
调试模式下jsx文件改动无法实时响应
同样的改动，有时 livereload可以响应有时不行

**Comment by benjycui** [comment]
有时。。。可以给出必现的步骤么？

**Comment by liujian10** [comment]
比如只写一个日期选择框给一个margin，开启调试模式后，修改jsx中的margin有时会迅速livereload有时要等很久，我是菜鸟，求大神们指点0.0

**Comment by benjycui** [comment]
应该是构建速度的问题。。
