### ISSUE TITLE
Can't set align using TypeScript

### ISSUE THREAD

**Issue by siwymilek** [ant-design/ant-design#17281]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/siwymilek/antd-table-align-bug-reproduction](https://github.com/siwymilek/antd-table-align-bug-reproduction)

### Steps to reproduce
Clone repo and use `yarn start`

### What is expected?
The code should compile

### What is actually happening?
The code not compiling. Compiler throws an error that type of "align" property is incompatible.
```
      Types of property 'align' are incompatible.
        Type 'string' is not assignable to type '"right" | "left" | "center" | undefined'.  TS2322
```

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | react 16.8.6 |
| System | macOS Mojave 10.14.5 |
| Browser | Chrome 75.0.3770.100 |

**Comment by afc163** [comment]
```diff
-   align: 'right',
+   align: 'right' as 'right',
```

**Comment by afc163** [comment]
https://stackoverflow.com/a/50070473/3040605

**Comment by Butcher1023** [comment]
ugly solution!
