### ISSUE TITLE
InputNumber to separate 'step' prop into 'stepUp' and 'stepDown'

### ISSUE THREAD

**Issue by lafeer** [ant-design/ant-design#17283]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm using ant.d InputNumber component as a ticket counter for a tours/activity app.
However, for example, some tickets I'm working with will only accept valid values of 0,2,3,4,5...
Meaning a ticket count of 1 is not allowed, but the rest of the values stated above are... 
So when I'm at ticket count of 2, I am allowed to only either step up by 1, or step down by 2

### What does the proposed API look like?
I propose separating the 'step' prop into 'stepUp' and 'stepDown' props to achieve the functionality described above

**Comment by lafeer** [comment]
@chenshuai2144 please help!

**Comment by lafeer** [comment]
Any updates? :/ @chenshuai2144 @yutingzhao1991 @yesmeck @afc163 @jljsj33 @zombieJ

**Comment by zombieJ** [comment]
https://codesandbox.io/s/zealous-leavitt-6f2xo

**Comment by lafeer** [comment]
thank you! but how to use this with getFieldDecorator? It cannot accept value prop right?

**Comment by zombieJ** [comment]
Customize Component which wrap the InputNumber component

**Comment by lafeer** [comment]
yes... that's right, but when I use it like below with Form, according to ant.d docs I cannot set value using value prop:

**You cannot set value of form control via _value defaultValue_ prop, and you should set default value with initialValue in getFieldDecorator instead.**

```
{getFieldDecorator(ticket.id, {
  rules: [{ required: true }],
})(
  <InputNumber
    min={0}
    max={10}
  />
)}
```

**Comment by zombieJ** [comment]
> Customize Component which wrap the InputNumber component

**Comment by lafeer** [comment]
but then I cannot use value prop for the custom component

**Comment by zombieJ** [comment]
You can since customize component is controlled by your code logic.

ref: https://reactjs.org/docs/forms.html#controlled-components
