### ISSUE TITLE
Descriptions组件不设置label的显示问题

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#17290]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lingering-mountain-8cwwf)

### Steps to reproduce
修改官方实例，把label参数去掉，还能看到 ：

### What is expected?
没有label，不需要显示 ：。

### What is actually happening?
没有label时，显示：。

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.3.2 |
| System | windows |
| Browser | chrome |

**Comment by chenshuai2144** [comment]
什么时候会不需要label? 那不就是list了

**Comment by kairi1227** [comment]
我们正好有这样的需求。
比如有三行，第一行不需要label。第二行需要label，第三行又不需要label。
很神奇的设计吧？

**Comment by afc163** [comment]
来个 PR 吧~

**Comment by kairi1227** [comment]
@dengfuping 你那样改，没法处理有边框的情况。

**Comment by MoonSeeing** [comment]
> @dengfuping 你那样改，没法处理有边框的情况。

当为bordered 时候 还是会占一个空白的单元格把

**Comment by yanyumei** [comment]
bordered这种情况解决了吗
