### ISSUE TITLE
<TimePicker />组件报错

### ISSUE THREAD

**Issue by rfw** [ant-design/ant-design#17295]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/rfw/-TimePicker-](https://github.com/rfw/-TimePicker-)

### Steps to reproduce
yarn  && npm start  之后点击页面上的TimePicker

### What is expected?
此antd版本  TimePicker 组件可以正常使用

### What is actually happening?
Uncaught Invariant Violation: Element ref was specified as a string (input) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a function component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.

| Environment | Info |
|---|---|
| antd |3.6.4 |
| React | ^16.2.0 |
| System | window10 |
| Browser | Chrome v73.0.3683.103 |

---
由于其他原因，不能对antd升级

**Comment by afc163** [comment]
https://github.com/react-component/time-picker/pull/131

**Comment by afc163** [comment]
请尝试升级，老版本的问题没有办法修复。
