### ISSUE TITLE
Adding response codes in error for upload.

### ISSUE THREAD

**Issue by dbteku** [ant-design/ant-design#17299]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We are using the upload component, it has a generic function for handing onChange but the issue is we don't know what response came from the server. If we knew what response came from the server we could handle errors effectively.

We have a requirement to not allow uploads over another. Our server returns a 409 but we have no way of knowing what response code was returned because the component returns a generic error without the response object that includes the response code.

### What does the proposed API look like?
```javascript
onUploadChange = info =>{

  if(info.file.error){
   if(info.file.response.status === 409){
      message.error("You cannot upload over another file");
    }
  }

}
```

**Comment by dengfuping** [comment]
@dbteku It was supported already by using `file.response`.
![image](https://user-images.githubusercontent.com/14918822/60854214-f213ec80-a231-11e9-8ad8-43ef6aa13e2a.png)

**Comment by dbteku** [comment]
If the response isn't a 200 code, that status does not return. Its still a problem

**Comment by dbteku** [comment]
if a 400, or a 409, or a 401, or a 403 come back test that. It doesn't return a status you can differentiate and branch off of.

**Comment by dbteku** [comment]
> @dbteku It was supported already by using `file.response`.
> ![image](https://user-images.githubusercontent.com/14918822/60854214-f213ec80-a231-11e9-8ad8-43ef6aa13e2a.png)

If the response isn't a 200 code, that status does not return. Its still a problem

if a 400, or a 409, or a 401, or a 403 come back test that. It doesn't return a status you can differentiate and branch off of.
