### ISSUE TITLE
MonthPicker切换年份时无法

### ISSUE THREAD

**Issue by junhui75165** [ant-design/ant-design#17292]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fast-bush-ghbwf)

### Steps to reproduce
切换年份，无法正常切换年份

### What is expected?
可以自由切换年份

### What is actually happening?
正常切换年份

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 15.3.0 |
| System | windows |
| Browser | chrome-last |

**Comment by afc163** [comment]
15.6.2 也有类似问题。

**Comment by junhui75165** [comment]
怎么使用修正好的版本

**Comment by afc163** [comment]
在 rc-calendar@9.15.3 里修复了，重装 node_modules 即可。

**Comment by junhui75165** [comment]
刚试了下还是不行，更正后这个[演示](https://codesandbox.io/s/fast-bush-ghbwf)的是不是会正常~

**Comment by afc163** [comment]
@leijingdao could you confirm it?

**Comment by leijingdao** [comment]
我直接 export  to  zip, 然后本地安装依赖， 是没有问题的

**Comment by leijingdao** [comment]
![Jietu20190705-200238-HD (1)-min](https://user-images.githubusercontent.com/12496382/60722573-f4d9bd80-9f63-11e9-8071-7faf58bf57d4.gif)
