### ISSUE TITLE
select下拉框，下拉列表变换时默认选中项有问题

### ISSUE THREAD

**Issue by luke93h** [ant-design/ant-design#17294]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1zh16)

### Steps to reproduce
1、输入a；
2、2s后继续输入ab；
3、4s后继续输入abc；

### What is expected?
下拉列表变换后，默认选中项始终为第一位

### What is actually happening?
下拉列表变换后，默认选中项为上一次的选中项

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16 |
| System | win10 |
| Browser | chrome |

---
重现gif链接：http://i1.fuimg.com/671404/0512c174d524b6c5.gif

**Comment by zombieJ** [comment]
调整成只要输入新的值，就将 active 重置为第一个好了。

**Comment by hua1995116** [comment]
@luke93h  这貌似不是一个 antd 的 bug ，应该是react 更新的机制吧， 你把两边的key设置成不一样就是你想要想的效果。
```
const data1 = [
  {
    value: 0,
    text: 0
  },
  {
    value: 1,
    text: 1
  },
  {
    value: 2,
    text: 2
  },
  {
    value: 3,
    text: 3
  }
];
const data2 = [
  {
    value: 4,
    text: 3
  },
  {
    value: 5,
    text: 0
  },
  {
    value: 6,
    text: 4
  }
];
```

**Comment by luke93h** [comment]
> @luke93h 这貌似不是一个 antd 的 bug ，应该是 react 更新的机制吧， 你把两边的 key 设置成不一样就是你想要想的效果。
> 
> ```
> const data1 = [
>   {
>     value: 0,
>     text: 0
>   },
>   {
>     value: 1,
>     text: 1
>   },
>   {
>     value: 2,
>     text: 2
>   },
>   {
>     value: 3,
>     text: 3
>   }
> ];
> const data2 = [
>   {
>     value: 4,
>     text: 3
>   },
>   {
>     value: 5,
>     text: 0
>   },
>   {
>     value: 6,
>     text: 4
>   }
> ];
> ```

在我遇到的场景中，搜索结果的顺序变了，但是key没变

**Comment by afc163** [comment]
看上去 4.0 的逻辑已经是预期的了。
