### ISSUE TITLE
Checkbox.Group 的 onChange 回调目前的 value 是根据点击的先后顺序来排序的，可以提供一个稳定排序的版本么？根据 options 的顺序来排序

### ISSUE THREAD

**Issue by howel52** [ant-design/ant-design#17297]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们有需求是根据 Checkbox.Group 所选择的 values 来渲染背后的表格，我们需要将表格的列排序与 Checkbox 的排序保持一致。 目前通过使用重写 onChange 来实现，但排序感觉这块可以官方支持。

### What does the proposed API look like?
提供一个 sorted: true | false 的 api， [查看 Demo](https://codepen.io/howel52/pen/qzXaeZ?editors=0011)

**Comment by zombieJ** [comment]
不用提供额外的 api，如果性能没什么影响默认帮用户排序应该更好些。
