### ISSUE TITLE
radio包一个select的多选自动消失问题

### ISSUE THREAD

**Issue by aufula** [ant-design/ant-design#17291]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

https://codesandbox.io/s/ecstatic-antonelli-n1k9d

### Steps to reproduce
看链接

### What is expected?
看链接

### What is actually happening?
看链接

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16 |
| System | mac 10.14 |
| Browser | chrome 75 |

**Comment by zombieJ** [comment]
Radio 点击后，焦点会在 `<input type="radio" />` 上。导致 Select 丢失焦点所以关闭了。这是游览器的默认行为，要修就得不用了原生 radio 了。

**Comment by zombieJ** [comment]
fixed: https://codesandbox.io/s/old-snow-f5jn2
