### ISSUE TITLE
Modal组件，body内包含其他的antd组件，国际化未生效，因为LocalProvider和Modal是邻居关系，context拿不到值

### ISSUE THREAD

**Issue by shengbeiniao** [ant-design/ant-design#17308]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost](http://localhost)
![image](https://user-images.githubusercontent.com/3301995/60159715-69a34e00-9826-11e9-8b71-3f2fbcbd703d.png)

### Steps to reproduce
Modal组件，body内包含其他的antd组件，国际化未生效

### What is expected?
国际化生效

### What is actually happening?
国际化未生效

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 所有 |
| System | 所有 |
| Browser | 所有 |

**Comment by shengbeiniao** [comment]
其中DatePicker作为测试用，本bug是因为modal是独立于根节点，直接挂载在body上面，LocaleProvider的context并未生效

**Comment by Malcn** [comment]
为什么不使用getContainer属性指定 Modal 挂载的 HTML 节点？

**Comment by shengbeiniao** [comment]
> 为什么不使用getContainer属性指定 Modal 挂载的 HTML 节点？

这种可以，不过每个Modal都需要指定，应该改modal组件也可以实现国际化，毕竟确定，取消这些按钮都国际化了，说明能拿到当前语言

**Comment by howel52** [comment]
> > 为什么不使用getContainer属性指定 Modal 挂载的 HTML 节点？
> 
> 这种可以，不过每个Modal都需要指定，应该改modal组件也可以实现国际化，毕竟确定，取消这些按钮都国际化了，说明能拿到当前语言

这块其实可以考虑在外层 layout 声明一个 id，再已 hoc 的形式包装一下 Modal，使其每次实例都挂载都是外层 layout 的 children

**Comment by shengbeiniao** [comment]
> 为什么不使用getContainer属性指定 Modal 挂载的 HTML 节点？

```
getContainer:()=>document.getElementById('root')
实测无效
```

**Comment by shengbeiniao** [comment]
> > > 为什么不使用getContainer属性指定 Modal 挂载的 HTML 节点？
> > 
> > 
> > 这种可以，不过每个Modal都需要指定，应该改modal组件也可以实现国际化，毕竟确定，取消这些按钮都国际化了，说明能拿到当前语言
> 
> 这块其实可以考虑在外层 layout 声明一个 id，再已 hoc 的形式包装一下 Modal，使其每次实例都是外层 layout 的 children

可以放个伪代码么？

**Comment by jlq023** [comment]
https://ant.design/components/locale-provider-cn/

看一下这个

**Comment by Tankerx** [comment]
最后是怎么解决的啊。我也遇到同样的问题，在内部单独给组件设置locale都不生效.改变modal的渲染Dom节点也不管用

**Comment by effapp** [comment]
这个问题解决了吗？是怎么解决的，没有看到答案啊。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/20949
