### ISSUE TITLE
Drawer component: afterVisibleChange is not working on Edge

### ISSUE THREAD

**Issue by lyf007168** [ant-design/ant-design#17303]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-hill-7ox69)

### Steps to reproduce
1. Open browser dev tool 
2. Click Open button 

### What is expected?
When drawer open or close, console should print the visible value of true or false

### What is actually happening?
The Edge tab will be reloaded, and no any visible value printed in console

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8.6 |
| System | Windows 10 Pro v1903 |
| Browser | Microsoft Edge 44.18362.1.0 |

**Comment by hustKiwi** [comment]
BTW, the issue can be reproduced by using the Edge environment of [BrowserStack](https://www.browserstack.com/).

**Comment by jljsj33** [comment]
rc-drawer 没问题，，不知道啥子情况。。。

[![Edit beautiful-kalam-o9r81](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/beautiful-kalam-o9r81?fontsize=14)


![image](https://user-images.githubusercontent.com/6802825/60160522-1df1a400-9828-11e9-9fe2-3712b6381fcf.png)

**Comment by jljsj33** [comment]
感觉是这个问题，，

![image](https://user-images.githubusercontent.com/6802825/60162501-411e5280-982c-11e9-9d80-b787e11fa9de.png)

我看下吧。。

**Comment by hustKiwi** [comment]
@jljsj33 谢谢快速响应和修复。不过可能还需要帮忙更新下 ant-design 的 package.json 中的  rc-drawer 到 `~1.10.1` 。否则 ant-design 下次发版没法包含 rc-drawer 的更新。多谢了。

https://github.com/ant-design/ant-design/blob/master/package.json#L67

**Comment by hustKiwi** [comment]
另外一点建议，rc-drawer 的 `1.10.0` 和 `1.10.1` 都属于 bugfix 而不是 feature 。所以根据 [Semantic Versioning](https://semver.org/) 应该维持 `1.9.x` 的 patch 版本更新（比如用 `1.9.10` 和 `1.9.11`），而不应该跳到 `1.10.0` 这样的 minor 版本。这样 ant-design 的 patch range version 就不用更新了，受影响的第三方重新 npm install 问题自然就修复。不过现在既然 rc-drawer 已经发新的 minor version ，那就需要 ant-design 更新 package.json 并发新版，这样我们这种依赖的项目才能更新并修复这个问题。
