### ISSUE TITLE
Table组件加载数据时暂无数据和loading同时展示，切不受控

### ISSUE THREAD

**Issue by shengbeiniao** [ant-design/ant-design#17309]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost](http://localhost)
![image](https://user-images.githubusercontent.com/3301995/60160113-390fe400-9827-11e9-9da1-0123e1aae65a.png)

### What is expected?
期望暂无数据图片不显示，因为只有loading完成后，才能判断是暂无数据的，这样逻辑行得通

### What is actually happening?
双重显示

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 所有 |
| System | 所有 |
| Browser | 所有 |

**Comment by shengbeiniao** [comment]
呈现步骤，手动设置一个长连接5min，检查dom节点，发现无法简单的通过css控制

**Comment by afc163** [comment]
建议自行用 `locale={{ emptyText: 'xxx' }}` 去控制。

**Comment by shengbeiniao** [comment]
这样写Ok
```
locale={{emptyText:loading?' ':''}}
```
