### ISSUE TITLE
antd 本机和在线demo表现不一致

### ISSUE THREAD

**Issue by wangjinghui-cn** [ant-design/ant-design#1731]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。
本机运行截图
http://024028.oss-cn-hangzhou-zmf.aliyuncs.com/uploads/antp/fullstack21/47ece50f71c41fba0edbf9d16218ace7/image.png
在线demo运行截图
http://024028.oss-cn-hangzhou-zmf.aliyuncs.com/uploads/antp/fullstack21/4898a143f2781ebdb6e14d9f67c1fa9d/image.png

本机运行显示的效果和在线DEMO的不一致, 本机的tnpm run build/dev 无提示升级
第一种写法在本地不提示required 在线可以
第二种写法本地和在线都可以, 但是需要额外代码控制span不在下面

```jsx
      <Col span="10"  >
      <FormItem label="影响商户数量：" labelCol={{ span: 12 }} wrapperCol={{ span: 12 }}>
      <InputNumber   {...activeProps1}  style={{ width: 60 }} />
      <span className="ant-form-text">家</span>
      </FormItem>
      </Col>
        
      <Col span="10"  >
      <FormItem label="影响商户数量：" labelCol={{ span: 12 }} wrapperCol={{ span: 12 }}>
      <InputNumber   {...activeProps1}  style={{ width: 60 }} />
      </FormItem>
      <span className="ant-form-text">家</span>
      </Col>
```

## Online demo

http://codepen.io/sywjh/pen/PNLxjZ?editors=0010

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by benjycui** [comment]
升级到 1.0 吧
