### ISSUE TITLE
upload文件上传400错误

### ISSUE THREAD

**Issue by ljxyweb** [ant-design/ant-design#17313]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
使用upload上传大文件
                              
报错：Failed to load resource: the server responded with a status of 400 (Unable to parse form content)

### What is expected?
可以上传大文件

### What is actually happening?
报错：Failed to load resource: the server responded with a status of 400 (Unable to parse form content)

| Environment | Info |
|---|---|
| antd | 3.16.5 |
| React | 16.7.0 |
| System | win7 |
| Browser | chrome |

**Comment by afc163** [comment]
这不是 antd 的问题，建议排查一下服务端。

**Comment by ljxyweb** [comment]
已解决，多谢

**Comment by marlti7** [comment]
> 这不是 antd 的问题，建议排查一下服务端。
怎么解决的
