### ISSUE TITLE
the tree component rendering is slowly by using expandeKeys 

### ISSUE THREAD

**Issue by zhang110912** [ant-design/ant-design#17325]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对tree进行检索，将检索得到的node的key信息赋值给tree组件的expandedKeys，发现重新进行渲染非常耗时，8000个节点树重新渲染需要40多秒。
ant-design版本是1.8.0

### What does the proposed API look like?
可以根据节点key，自动展开节点

**Comment by afc163** [comment]
antd 1.x 已经不维护了，请升级到最新版本。
