### ISSUE TITLE
Input的size属性在Form组件中失效

### ISSUE THREAD

**Issue by juneryo** [ant-design/ant-design#1732]
version: 1.0.1

若Input组件放在Form中，即
```
<Form>
    <Input />
</Form>
```
或者
```
<Form>
    <FormItem>
        <Input />
    </FormItem>
</Form>
```
此时设置Input的size，是无效的。
若放在Form外面，则是没问题的。

**Comment by benjycui** [comment]
> 注：标准表单中一律使用大号控件。

http://ant.design/#/components/form?scrollTo=Input+%E8%BE%93%E5%85%A5%E6%A1%86

**Comment by henryzp** [comment]
@afc163 ，为什么不提供input的size配置呢？？

**Comment by benjycui** [comment]
@henryzp 显式覆盖 size 是可以的 see https://github.com/ant-design/ant-design/pull/1735
