### ISSUE TITLE
Browser zoom breaks table layout

### ISSUE THREAD

**Issue by rafaelodassi** [ant-design/ant-design#17324]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2oo5py14j0)

### Steps to reproduce
Open a page with a table and zoom in or out through the browser.

### What is expected?
What is independent of zoom, table layout does not break.

### What is actually happening?
The layout of the table has become unordered, losing the list size of some lines.

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.3.2 |
| System | Windows |
| Browser | Google Chrome |

**Comment by afc163** [comment]
It is hard to resolve those kind of problems, welcome to dig into it and give us PR~

**Comment by theghostcasper** [comment]
Just in case anyone got this issue. Solution is as follows: 

`.ant-table-header table {
  table-layout: auto !important;
}
`

**Comment by veiko** [comment]
> Just in case anyone got this issue. Solution is as follows:
> 
> `.ant-table-header table { table-layout: auto !important; } `

Verified that this fixes the issue.

@afc163 any reason why this change should not be made? I've tested on tables with different `tableLayout` set and it all seems to be working. Would there be concerns with the column width calculations if this change were made?
