### ISSUE TITLE
antd2.x是不支持react16吗？

### ISSUE THREAD

**Issue by jzzj** [ant-design/ant-design#17320]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 2.13.13 |
| React | react@16.4.2 |
| System | mac |
| Browser | chrome最新 |

**Comment by afc163** [comment]
对。2.x 已经不维护了。
