### ISSUE TITLE
Two scrollbars appears when using modal inside drawer with drawer and body with scroll

### ISSUE THREAD

**Issue by SrAnthony** [ant-design/ant-design#17323]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/SrAnthony/antd-drawer-scroll-bug](https://github.com/SrAnthony/antd-drawer-scroll-bug)

### Steps to reproduce
Click on Open Drawer and then on Open Modal

### What is expected?
When opening the drawer the body scroll should be hidden (ok).
When opening the modal the body and drawer scroll should be hidden (ok).
When closing the modal the body scroll should be kept hidden and the drawer scroll should be visible (not ok)
When closing the drawer the body scroll should be shown (ok).

### What is actually happening?
When closing the modal inside the drawer the body scroll is showing. If both body and drawer have scroll areas, two scrollbars are visible.

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8.1 |
| System | linux |
| Browser | Chrome 75.0.3770.90 |

**Comment by jljsj33** [comment]
跟 #16680 一样的吧，， modal 和 drawer 同时使用，都有对页面操作滚动条，冲突了。。。

**Comment by ztplz** [comment]
Just translate into English, he means it is relate to https://github.com/ant-design/ant-design/issues/16680. Both modal and drawer have scroll bars when used at the same time and they conflict with each other.

**Comment by SrAnthony** [comment]
I updated the reproduction repo to the latest antd version and the bug still occurs.
https://github.com/SrAnthony/antd-drawer-scroll-bug

**Comment by jljsj33** [comment]
What？？？
no problem here.
[![Edit bug-antd-modal-1](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bug-antd-modal-1-nuccz?fontsize=14)

**Comment by merlin-li** [comment]
> 跟 #16680 一样的吧，， modal 和 drawer 同时使用，都有对页面操作滚动条，冲突了。。。

在 16680 说跟 17323 一样，在 17323 说跟 16680 一样，你真秀。

**Comment by jljsj33** [comment]
> > 跟[＃16680](https://github.com/ant-design/ant-design/issues/16680)一样的吧，，模态和抽屉同时使用，都有对页面操作滚动条，冲突了。。。。
> 
> 在16680说跟17323一样，在17323说跟16680一样，你真秀。

没说错啊，字面意思是两个相关联啊。。。别挖坟行不？？

**Comment by merlin-li** [comment]
> > > 跟[＃16680](https://github.com/ant-design/ant-design/issues/16680)一样的吧，，模态和抽屉同时使用，都有对页面操作滚动条，冲突了。。。。
> > 
> > 
> > 在16680说跟17323一样，在17323说跟16680一样，你真秀。
> 
> 没说错啊，字面意思是两个相关联啊。。。别挖坟行不？？

害，开个玩笑，别当真。 被这个问题整的有点烦。

**Comment by merlin-li** [comment]
> What？？？
> 
> no problem here.
> [![Edit bug-antd-modal-1](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/bug-antd-modal-1-nuccz?fontsize=14)

这里应该还是存在问题, Drawer 属性改为下面 placement:bottm   maks:false： 就会复现。
      <Drawer visible={drawerVisible} placement='bottom' mask={false} onClose={toggleDrawer}></Drawer>

**Comment by jljsj33** [comment]
> > What？？？
> > no problem here.
> > [![Edit bug-antd-modal-1](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/bug-antd-modal-1-nuccz?fontsize=14)
> 
> 这里应该还是存在问题, Drawer 属性改为下面 placement:bottm maks:false： 就会复现。

他们后面改坏了，，请关注最近的更新。。。
