### ISSUE TITLE
menu 能否增加一个存储数据的变量，类似于tag

### ISSUE THREAD

**Issue by longang520** [ant-design/ant-design#1733]
menu 能否增加一个存储数据的变量，类似于tag，这样在点击的时候，传递的不光是key。

**Comment by afc163** [comment]
不明白。

**Comment by longang520** [comment]
Dropdown 在table，每行加入一个， 怎么使用？

**Comment by afc163** [comment]
columns.render

**Comment by longang520** [comment]
我现在是这样使用的
menu中的key “edit-1” “delete-1”
第二行  的key “edit-2” “delete-2”
在menu的onClick事件中将key拆分。使用。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/eZaPOa?editors=001

动态构造。

**Comment by longang520** [comment]
我知道这个是解决方案，但是这样真的好么？如果加一个扩展属性，用户可以自己存储。在onclick的时候在返回，这样判断起来更优。建议考虑。

**Comment by afc163** [comment]
超出 UI 组件的职责了。

**Comment by longang520** [comment]
过去我在使用
easyui，miniui，以及其他组件库的时候，这个属性都会存在。
好吧。我自己扩展吧。

**Comment by longang520** [comment]
http://www.material-ui.com/#/components/menu
你们看下这个组件库中也是有一个value属性，可以存储任何值。

**Comment by afc163** [comment]
menu 有选中的状态和相关属性的。你可以参考：https://github.com/react-component/menu
