### ISSUE TITLE
DatePicker日期控件左右箭头乱码

### ISSUE THREAD

**Issue by haro007** [ant-design/ant-design#17334]
在谷歌浏览器上偶尔会出现左右箭头乱码的情况，不是必然重现
![image](https://user-images.githubusercontent.com/40338214/60244932-13014700-98ee-11e9-8d7a-de9bc1df6c5b.png)

**Comment by wayofwade** [comment]
> 在谷歌浏览器上偶尔会出现左右箭头乱码的情况，不是必然重现
> ![image](https://user-images.githubusercontent.com/40338214/60244932-13014700-98ee-11e9-8d7a-de9bc1df6c5b.png)

我也出现这个问题，有时候箭头乱码，我感觉会不会是build之后，部署到服务器出现的问题，因为本地调试是正常的。不知道你后来解决了没有。

**Comment by steadyzeus** [comment]
请问楼上有解决这个问题吗？

**Comment by 895433995** [comment]
我也遇到这个问题了，我看是`.ant-select-selector:after{content: '\a0'}` 在chrome里content被解析成 A 了，不知道为什么

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19648#issuecomment-552169030

**Comment by 895433995** [comment]
加了 !DOCTYPE html 的，但是在mac上没出现过这个问题，在测试同事的windows   chrome里会偶现，也不知道为什么

**Comment by afc163** [comment]
看看是不是开了翻译。

**Comment by 895433995** [comment]
嗯，确实开了翻译，我让她关了看看还会不会出现，多谢😄

**Comment by 895433995** [comment]
![image](https://github.com/ant-design/ant-design/assets/39820191/1fed4a08-bfd8-4aec-b754-1bb675104ff9)
![image](https://github.com/ant-design/ant-design/assets/39820191/2e1389be-74a8-45df-b00c-502bf1940052)

测试说关了翻译，今天又出现了😭

**Comment by afc163** [comment]
你的 antd 版本是什么，我在这里专门修复过这个问题 https://github.com/ant-design/ant-design/pull/17480

**Comment by 895433995** [comment]
4.24.10

**Comment by afc163** [comment]
你这个截图不是 4.x 的 DatePicker，4.x 的长这样：

<img width="424" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/bf7be9dd-d536-4e0d-a8c9-413d30fee20e">

**Comment by afc163** [comment]
@895433995 有截图看看不

**Comment by 895433995** [comment]
![image](https://github.com/ant-design/ant-design/assets/39820191/932b4819-77bc-4279-813f-40a1e8ea640c)

**Comment by afc163** [comment]
@895433995 是看出问题的 Select 的截图，以及相关的 Chrome 版本。

**Comment by 895433995** [comment]
select截图上面已经发过了，
![image](https://github.com/ant-design/ant-design/assets/39820191/9871a4a8-6cbf-4cc6-845b-3145f0c433ca)

**Comment by 895433995** [comment]
![image](https://github.com/ant-design/ant-design/assets/39820191/82a18466-6af9-4f3b-89e6-c1f61f03bae0)
看这个图上，貌似mode=tags才有这个问题

**Comment by afc163** [comment]
<img width="1009" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/24ac9ddb-326b-4611-9c7a-69052da3c5ca">

`content: '\a0'` 这个伪元素上是有 `visibility: hidden;` 样式的，理论上应该是看不见的，你能否协助在可重现的电脑上打开 devtool 帮忙看看为啥 `visibility: hidden;` 没生效么？

**Comment by 895433995** [comment]
因为没在公司，所以不太方便让同事看，但是我在官网看多选的下拉框是没有`visibility: hidden;`样式的
![image](https://github.com/ant-design/ant-design/assets/39820191/e0f9463a-e2d1-462d-9094-0a29d34e24a0)

**Comment by afc163** [comment]
看上去多选也应该加个 `visibility: hidden;`。

**Comment by afc163** [comment]
方便来个 PR 不？

**Comment by 895433995** [comment]
好的我研究研究

**Comment by rawbin-** [comment]
我们昨天发现是这个
.ant-select-multiple .ant-select-selector:after {
    display: inline-block;
    width: 0;
    margin: 2px 0;
    line-height: 24px;
    content: "Â "
}

**Comment by heavenlyfate** [comment]
> 我用 Select 也遇到这个问题了，我看是`.ant-select-selector:after{content: '\a0'}` 在chrome里`\a0`被解析成 A 了，不知道为什么

有被解决吗， 4.2版本，看到组件库样式里有好多‘\a0’

**Comment by guguji5** [comment]
> 我们昨天发现是这个
> 
> ```
> 
> .ant-select-multiple .ant-select-selector:after {
>     display: inline-block;
>     width: 0;
>     margin: 2px 0;
>     line-height: 24px;
>     content: "Â "
> }
> ```

@rawbin- 两年过去了，我又碰到了。大佬怎么解决的
