### ISSUE TITLE
New Message, Notification and Modal API for fix context loss issues.

### ISSUE THREAD

**Issue by Frezc** [ant-design/ant-design#17343]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There are many issues about losing context in the message, notification and modal API. https://github.com/ant-design/ant-design/issues/15260 https://github.com/ant-design/ant-design/issues/17153 https://github.com/ant-design/ant-design/issues/14101 https://github.com/ant-design/ant-design/issues/12781 https://github.com/ant-design/ant-design/issues/9036

### What does the proposed API look like?
The simplest way to solve the above problems is by providing new components correspond to imperative API.
```jsx
import { Message, Notification, Modal } from 'antd';

<Message
  type="success"
  duration={5}
  visible={...}
  onClose={...}
/>

<Notification
  type="success"
  message="good morning"
  visible={...}
  onClose={...}
/>

<Modal.Confirm
  title="Are you sure?"
  visible={...}
  onOk={...}
  onCancel={...}
/>
```

**Comment by Frezc** [comment]
If API is accepted, I can work on this.

**Comment by zombieJ** [comment]
My thought of hooks to provide insert node about this:
```jsx
const [modal, holder] = Modal.useModal();

return (
  <div>
    <Button onClick={() => {
      modal.confirm(...);
    }}>Show</Button>
    {holder}
  </div>
);
```

**Comment by Frezc** [comment]
@zombieJ 
I forgot these components are created every time when API called. Component API may not be a good way.

Hooks you described is a good solution if you are ready to provider hooks API. 👍

**Comment by zombieJ** [comment]
For antd v4, we will move to the latest React. Since it's not plan to release this immediately in antd 4. You can help to create PR on this. `4.0-prepare` is the branch.

**Comment by afc163** [comment]
Duplicate of #14101

**Comment by oleg-brizy** [comment]
All your examples with notifications are `onClick: openNotification`. There is no proper way to render notifications from a preexisting array, and no way to destroy properly a single notification (automatically on component unmount). https://github.com/ant-design/ant-design/issues/23212#issuecomment-613543540

For our project we will create a wrapper component that encapsulates a notification with unique key and closes it on unmount.
