### ISSUE TITLE
InputNumber with JSX attribute 'type="number"' and formatter doesn't display data

### ISSUE THREAD

**Issue by trevornagy** [ant-design/ant-design#17344]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-inputnumber-doesnt-display-data-bfnbo)

### Steps to reproduce
* Add Input Number with JSX attribute type with a value of "number" or JSX attribute inputMode with a value of "numeric"
* Add formatter JSX attribute with any settings. (In the example, I am using exactly what is given in the [formatter example in the docs](https://ant.design/components/input-number/#components-input-number-demo-formatter).

### What is expected?
Data is displayed in the InputNumber as expected. Number keyboard is displayed on applicable devices. 

### What is actually happening?
No data is displayed in the InputNumber component. (The value is still outputted in the console though.) The only data that can be displayed when using `type="number"` from my tests are the ".", " ", "-" characters. When using `inputMode="numeric"` no data is displayed.

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8.6 |
| System | Windows 10, OS Build 17134.765 |
| Browser | Mozilla Firefox 66.0, Microsoft Edge 42.17134.1.0, Google Chrome Version 75.0.3770.100 |

---
I wanted the InputNumber component to display the number keyboard on mobile devices, so I applied `type="number"` to the component where I already had a formatter applied and I noticed this.

**Comment by afc163** [comment]
`<input type="number" />` don't allow non-numeric characters.

https://codesandbox.io/s/antd-inputnumber-doesnt-display-data-71fv5

**Comment by afc163** [comment]
Just don't add `type="number"`.

**Comment by trevornagy** [comment]
@afc163 While I was searching to see if this issue was a duplicate I noticed that you had [previously stated ](https://github.com/ant-design/ant-design/issues/9421#issuecomment-368721852) that the InputNumber component was designed to mimic the `type="number"` functionality. If I was to remove `type="number"` then the numeric keyboard that displays on mobile would no longer be present. I understand I could apply this keyboard by myself. Perhaps the InputNumber component should display the numeric keyboard by default?

**Comment by bouncydragon** [comment]
any update on this issue?
