### ISSUE TITLE
Add `hideOnNoData` API for Pagination component

### ISSUE THREAD

**Issue by CodeDaraW** [ant-design/ant-design#17348]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When `total` is 0 and `hideOnNoData` is true, hide the pager, just like the Table embed Pagination does by default.

### What does the proposed API look like?
Add `hideOnNoData` API, it's `false` by default.

**Comment by CodeDaraW** [comment]
I can help create PRs for `rc-pagination` and update the docs of ant-design.

**Comment by zombieJ** [comment]
You can use `hideOnSinglePage` instead. It includes 0 count.

**Comment by CodeDaraW** [comment]
But they are not the same thing, I want to hide the Pagination component **only when the count is 0**.  

If you won't provide this API, perhaps you should not hide the Pagination component when the count is 0 in Table component, or this will cause inconsistency.

https://github.com/ant-design/ant-design/blob/a5f495692e999f12546406d1f1ef9f06ae75e6f9/components/table/Table.tsx#L1008-L1019

This is sorely needed in our product.

**Comment by zombieJ** [comment]
Hmm. Maybe Table without data should auto hide Pagination.

**Comment by CodeDaraW** [comment]
I mean that maybe Table **should not** hide Pagination when the count is 0.

When the count is 0, some places that use Pagination directly will not be hidden, but the places that use Table will hide embed Pagination, and I can't control the default behavior of Table. This leads to inconsistency.

In my opinion, there are two ways to solve the problem, either Pagination provides an API to hide when the count is 0, or the Table should not hide Pagination when the count is 0.

**Comment by zombieJ** [comment]
Hi @CodeDaraW,
Could you describe why you want to display the Pagination when there is no data in Table?

**Comment by CodeDaraW** [comment]
心累……算了用中文和你说吧：  

如果直接使用分页组件，当 `total` 是 `0` 的时候（没有数据），分页组件默认会显示；而使用了表格里的分页组件，当 `total` 是 `0` 的时候，分页组件会默认隐藏。这在整个项目当中导致了交互的不一致性。  

我们不想设置成当数据只有一页时隐藏分页，这会导致数据较少时看不出来哪些页面支持了分页。  

我们只想在无数据的时候，要么表格里的分页会展示（和直接使用分页的默认行为一致），要么可以把分页组件在无数据时隐藏（和表格的默认行为一致）。两者皆可，只要保证一致性即可。

前者我们只能通过修改 `Table` 的实现来做到，后者我们可以在每次使用分页组件的时候加一个判断：

``` JavaScript
{total !== 0 && <Pagination defaultCurrent={1} total={total} />}
```

每次使用都加判断显然很蠢，所以我倾向于给分页组件加一个在无数据时隐藏的 API，默认值是 `false`，这样不会影响现有的用户；而表格组件中也可以不用再去判断 `total`，直接在使用分页的时候给这个 `prop` 传 `true` 来实现无数据时隐藏分页。

**Comment by zombieJ** [comment]
Pagination 组件本身其实不应该处理隐藏逻辑，`hideOnSinglePage` 其实不太适合放在 Pagination 中，但是已经有了就有了。额外的 `hideOnXXX` 不会再添加了。对于自定义组件带 Pagination，建议封装一下 Pagination 来处理。

**Comment by CodeDaraW** [comment]
@Leif1125 显然无法实现
