### ISSUE TITLE
用 OptGroup 进行选项分组, 有显示bug

### ISSUE THREAD

**Issue by azl397985856** [ant-design/ant-design#1734]
1.用 OptGroup 进行选项分组，分成两组，同时添加showSearch
2.选中第二个分组
![image](https://cloud.githubusercontent.com/assets/12479470/15346143/a2a2bfbe-1ce7-11e6-9cb1-bd38be204581.png)

3.开始搜索到第二个分组的内容
![image](https://cloud.githubusercontent.com/assets/12479470/15346150/ab063e4c-1ce7-11e6-9593-1df9b2afd318.png)

4.第一个分组会变成hover状态
![image](https://cloud.githubusercontent.com/assets/12479470/15346152/b32c4fb2-1ce7-11e6-880e-66f850a4a3b5.png)

- The version of antd(e.g. 0.12.10):
- My operating system is win7 64bit

**Comment by superRaytin** [comment]
文档加上了，使用 `defaultActiveFirstOption: false` 解决，这个属性之前没有从 https://github.com/react-component/select 同步过来

**Comment by azl397985856** [comment]
thanks
