### ISSUE TITLE
Tooltip still visible after mouseLeave in disabled Switch

### ISSUE THREAD

**Issue by GFwer** [ant-design/ant-design#17357]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-brahmagupta-lgx0m)

### Steps to reproduce
disabled Switch and toggle mouseEnter, then toggle mouseLeave
![Kapture 2019-06-28 at 17 10 04](https://user-images.githubusercontent.com/14303098/60332522-98a5f500-99c9-11e9-9bc1-722dc15dcdd6.gif)

### What is expected?
tooltip disappear

### What is actually happening?
tooltip still visible

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8.6 |
| System | MacOS 10.14.5 |
| Browser | Chrome 77.0.3833.0 & Safari 12.1.1  |

**Comment by arfeo** [comment]
Pull #17372 either hasn't been merged to the master or doesn't fixes the issue. Version `3.25.2` of the `antd` library still has the bug.

**Comment by damiangreen** [comment]
This is still a bug in the latest 4.2.5 version. This case needs re-opening

**Comment by aikodeio** [comment]
I have the same conflict

**Comment by itsmichaeldiego** [comment]
I am experiencing the same issue!

**Comment by itsmichaeldiego** [comment]
I am experiencing the same issue, came up with this workaround:

- Wrap the disabled button/input in another element.
- Add `{ pointer-events: none; }` style to the disabled button/input.
- Set `{ cursor: not-allowed; }` to the wrapper to fix cursor behavior that stops working with previous step (adding pointer-events: none;).

```javascript
<Tooltip title="Tooltip Title">
  <span style={{ cursor: disabled ? 'not-allowed' : 'pointer' }}>
    <Button disabled={disabled} style={{ pointerEvents: 'none' }} />
  </span>
</Tooltip>
```

Sources:
- https://github.com/react-component/tooltip/issues/18#issuecomment-307994107
- https://github.com/react-component/tooltip/issues/18#issuecomment-411476678
- https://github.com/react-component/tooltip/issues/18#issuecomment-650864750

Let me know if it works!

**Comment by Homingciu** [comment]
4.16.9版本依旧有问题！
