### ISSUE TITLE
<Upload /> updates fileList even though unsupported type is given (beforeUpload returns false)

### ISSUE THREAD

**Issue by dseljan** [ant-design/ant-design#17353]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-cori-94szv)

### Steps to reproduce
I have taken your sanbox link https://codesandbox.io/s/l0zo2 from Upload component page under example Avatar - "Click to upload user's avatar, and validate size and format of picture with beforeUpload".
I've changed showUploadList to true, and after trying to upload invalid file type, fileList gets updated with file even though the file with that type is not supported. 
This bug was introduced under this issue on the github page:
https://github.com/ant-design/ant-design/issues/8036

### What is expected?
Returning false in beforeUpload should work as before: nothing happens if we decide file is incorrect.

### What is actually happening?
File is being added when it shouldn't have.

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Google Chrome |

---

**Comment by afc163** [comment]
It is not a bug: https://github.com/ant-design/ant-design/issues/15561#issuecomment-481186693

**Comment by dseljan** [comment]
My apologies then.
Thanks for the help!
