### ISSUE TITLE
Cascader设置initialValue不显示,但是内部值是存在的

### ISSUE THREAD

**Issue by travonf** [ant-design/ant-design#17352]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/travonf/pen/YoYKwX](https://codepen.io/travonf/pen/YoYKwX)

### Steps to reproduce
Cascader加入到Form组件中并且设定initialValue

### What is expected?
能够正常显示初始值

### What is actually happening?
初始值为空, 但是点击提交可以获取到值

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.7.0 |
| System | MacOS |
| Browser | Chrome 75.0.3770.100 |

**Comment by afc163** [comment]
`options` 和 `value` 不匹配。

**Comment by travonf** [comment]
> `options` 和 `value` 不匹配。

value数组值必须是options里的对吗?

**Comment by afc163** [comment]
对的~

**Comment by travonf** [comment]
> 对的~

明白了, 我的数据都是Mock出来的随机数据触发了这个问题, 希望官网能够说明一下这种情况
