### ISSUE TITLE
select的allowClear清除属性，在清除数据之后能支持回调函数或者触发onSearch方法吗？

### ISSUE THREAD

**Issue by wangyuan0108** [ant-design/ant-design#17358]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为在支持搜索功能的时候，搜索完毕之后拉取后台的数据，然后allowClear清除value之后，没有再次调用api，因为清除功能没有触发onSearch属性。需要的是可以触发onSearch方法或者支持回调函数

### What does the proposed API look like?
allowClear可以触发onSearch方法或者支持回调函数

**Comment by ypli0629** [comment]
使用 onChange 处理下清除事件

**Comment by wangyuan0108** [comment]
> onChange

可以监听到这个事件是吧

**Comment by margox** [comment]
> 使用 onChange 处理下清除事件

只有在Select组件选中了某个值之后，点那个清除按钮才会触发onChange，如果只是单纯输入搜索关键字，点清除按钮之后输入的关键字会被清掉，但是此时无论onChange还是onSearch都没有被触发

**Comment by Su-CanYuan** [comment]
onChange 无法监听allowClear事件

**Comment by Su-CanYuan** [comment]
allowClear 的同时能不能触发函数？有没有什么办法

**Comment by adouwt** [comment]
onChange 可以检测到值的变化，包括清空后的值，监测它undefined 来手动触发回调

**Comment by Niefee** [comment]
```js
if(event.type ==='click' && event.target.value === '') {
      console.log('clear all:', );
      handleOk()
}
```
这个方法可以判断是否点击清空。

**Comment by corily** [comment]
onChange虽然可以检测到值的变化，但是对于多选来说，并不友好，如果只删除一项，并不需要触发api
