### ISSUE TITLE
Svelte Support

### ISSUE THREAD

**Issue by YajJackson** [ant-design/ant-design#17361]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would love to use this amazing UI framework while using [svelte](https://svelte.dev/)

### What does the proposed API look like?
```index.svelte
<script>
import { Button } from 'antd/svelte'
</script>

<h1>Svelte   Ant Design === awesome</h1>
<Button>Agree</Button>
```

**Comment by afc163** [comment]
We don't have enough energy to handle this, feel free to create a repo~

**Comment by YajJackson** [comment]
@afc163 why not leave the issue open to gauge interest? This seems like something you'll eventually want to implement.

**Comment by afc163** [comment]
https://ant.design/docs/spec/introduce#Front-end-Implementation

**Comment by joshua1** [comment]
@YajJackson someone started this few days ago https://ant-svelte.ddot.ink/docs/getting-started/. you can follow and give him your support

**Comment by saravanabalagi** [comment]
The lib [Ant-design-svelte](https://github.com/Jetsly/ant-design-svelte) is an awesome start with clean and neat docs (I couldn't read the language, the docs is perfectly usable), but it seems abandoned unfortunately :/
