### ISSUE TITLE
我在table的filter中添加一个select,用来设置过滤的条件,当通过点击来选择option时,filter面板会自动隐藏

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#1736]
![aaaa](https://cloud.githubusercontent.com/assets/11780264/15346891/d706de1e-1cee-11e6-9ae6-13384e18fbea.png)
![bbb](https://cloud.githubusercontent.com/assets/11780264/15346893/d736ae0a-1cee-11e6-9256-524f89f1d261.png)
![bug](https://cloud.githubusercontent.com/assets/11780264/15346894/d765601a-1cee-11e6-8bdf-9229fb1f8b71.gif)

**Comment by XUGAOBO** [comment]
跟踪原因是在选择数据项后,会先触发table的onChange()事件,然后在触发select的onChange()事件

**Comment by benjycui** [comment]
这种场景计划支持么？ @afc163

**Comment by afc163** [comment]
我先看看。

**Comment by afc163** [comment]
添加了一个 `column.filterDropdown` 用于自定义渲染筛选菜单的浮层。issue 中的 hack 用法就不予支持了。

**Comment by elearic** [comment]
@afc163 前辈您好，column.filterDropdown 我们在用，但是现在有个问题，我想拿得到这个图层的显示和隐藏事件，在图层显示和隐藏的时候做一些事情，但是现在table.column没有提供该属性，我还有其他办法获取吗？谢谢。
