### ISSUE TITLE
使用beforeUpload自定义上传时，如果文件为Blob，则不会出现略缩图 

### ISSUE THREAD

**Issue by LeeeoZhang** [ant-design/ant-design#17368]
- [ 暂无] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[demo](https://codesandbox.io/s/antd-reproduction-template-ipcfs?fontsize=14)

### Steps to reproduce
自定义上传一个Blob文件

### What is expected?
自定义上传一个Blob文件时，有预览缩略图

### What is actually happening?
自定义上传一个Blob文件时，没有预览缩略图

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.4.1 |
| System | macOS 10.13.6 |
| Browser | chrome75 |

---
```
    (items || []).forEach(file => {
      if (
        typeof document === 'undefined' ||
        typeof window === 'undefined' ||
        !(window as any).FileReader ||
        !(window as any).File ||
        !(file.originFileObj instanceof File) ||
        file.thumbUrl !== undefined
      ) {
        return;
      }
      file.thumbUrl = '';
      if (previewFile) {
        previewFile(file.originFileObj).then((previewDataUrl: string) => {
          // Need append '' to avoid dead loop
          file.thumbUrl = previewDataUrl || '';
          this.forceUpdate();
        });
      }
```
这是upload组件里的一段，会导致当文件类型时Blob的时候没有缩略图
还有就是当文件为Blob时，默认的上传逻辑构建FormData时没有传入第三个参数，导致后端不能正确获得文件名

**Comment by zombieJ** [comment]
可以使用 `previewFile` 自定义预览逻辑。

**Comment by LeeeoZhang** [comment]
> 可以使用 `previewFile` 自定义预览逻辑。

为什么就关闭了。
在`beforeUpload`里面处理文件，并`resolve`一个Blob类型的文件，`previewFile`并不会执行
根据源码里的内容:
```
    (items || []).forEach(file => {
      if (
        typeof document === 'undefined' ||
        typeof window === 'undefined' ||
        !(window as any).FileReader ||
        !(window as any).File ||
        !(file.originFileObj instanceof File) ||
        file.thumbUrl !== undefined
      ) {
        return;
      }
      file.thumbUrl = '';
      if (previewFile) {
        previewFile(file.originFileObj).then((previewDataUrl: string) => {
          // Need append '' to avoid dead loop
          file.thumbUrl = previewDataUrl || '';
          this.forceUpdate();
        });
      }
```
`file.originFileObj instanceof File` 中的`file.originFileOb`是一个Blob，表达式会为`false`，导致直接`return`，`previewFile`并没有用

**Comment by zombieJ** [comment]
提供一份代码重现，我看看。

**Comment by LeeeoZhang** [comment]
> 提供一份代码重现，我看看。

[demo](https://codesandbox.io/s/antd-reproduction-template-ipcfs?fontsize=14)

**为什么会有这样的操作**

前端上传图片时会有压缩图片的需求，因此会有有File进行base64、Blob互转的操作。

**把Blob转成File不就可以了吗**

目前就是这样做的，通过把Blob转成File。但是文档上面，`beforeUpload`和`previewFile`都是支持`resolve`一个Blob的，这和实际使用情况有出入。
@zombieJ

**Comment by zombieJ** [comment]
demo 跑不通 preview 是因为  code sandbox 设置了 `"infiniteLoopProtection": false,` 。去掉就正常了：
https://codesandbox.io/s/antd-reproduction-template-3q54t

**Comment by LeeeoZhang** [comment]
> demo 跑不通 preview 是因为 code sandbox 设置了 `"infiniteLoopProtection": false,` 。去掉就正常了：
> https://codesandbox.io/s/antd-reproduction-template-3q54t

[demo](https://codesandbox.io/s/antd-reproduction-template-3q54t?fontsize=14)

并没有哦，注意`beforeUpload`里面`resolve`的内容

@zombieJ

**Comment by zombieJ** [comment]
<img width="176" alt="屏幕快照 2019-07-01 下午4 44 18" src="https://user-images.githubusercontent.com/5378891/60422860-7d342780-9c1f-11e9-9a78-b5c8cf8acbc1.png">

**Comment by nannan0109** [comment]
> * [ 暂无] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [demo](https://codesandbox.io/s/antd-reproduction-template-ipcfs?fontsize=14)
> 
> ### Steps to reproduce
> 自定义上传一个Blob文件
> 
> ### What is expected?
> 自定义上传一个Blob文件时，有预览缩略图
> 
> ### What is actually happening?
> 自定义上传一个Blob文件时，没有预览缩略图
> 
> Environment	Info
> antd	3.19.8
> React	16.4.1
> System	macOS 10.13.6
> Browser	chrome75
> ```
>     (items || []).forEach(file => {
>       if (
>         typeof document === 'undefined' ||
>         typeof window === 'undefined' ||
>         !(window as any).FileReader ||
>         !(window as any).File ||
>         !(file.originFileObj instanceof File) ||
>         file.thumbUrl !== undefined
>       ) {
>         return;
>       }
>       file.thumbUrl = '';
>       if (previewFile) {
>         previewFile(file.originFileObj).then((previewDataUrl: string) => {
>           // Need append '' to avoid dead loop
>           file.thumbUrl = previewDataUrl || '';
>           this.forceUpdate();
>         });
>       }
> ```
> 
> 这是upload组件里的一段，会导致当文件类型时Blob的时候没有缩略图 还有就是当文件为Blob时，默认的上传逻辑构建FormData时没有传入第三个参数，导致后端不能正确获得文件名

我用你demo里的方法压缩，结果并没有压缩效果，原图15m 压缩后的blob我看也有14m多。。。
