### ISSUE TITLE
Props "menuItemSelectedIcon" not workin for Select at mode='default'

### ISSUE THREAD

**Issue by InFuz** [ant-design/ant-design#17360]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-v81ub)

### Steps to reproduce
1) Create select in default mode.
2) Add "menuItemSelectedIcon" props

### What is expected?
Props "menuItemSelectedIcon" add selected-icon for selected Option.

### What is actually happening?
Nothing! selected-icon did not appear.

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8.6 |
| System | macOS 10.14.5 |
| Browser | Google Chome 75.0.3770.100 |

**Comment by zombieJ** [comment]
`menuItemSelectedIcon` is a prop for multiple options. Should update doc for this.
