### ISSUE TITLE
Table组件暂无数据对齐问题

### ISSUE THREAD

**Issue by six-666** [ant-design/ant-design#17363]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用scroll配置高度后暂无数据在顶部，在高度非常高的情况下感觉这个布局是怪怪的。

### What does the proposed API look like?
Table组件的暂无数据应该可配置多种对齐方式。 一般来说应该是居中对齐比较符合实际情况。

**Comment by six-666** [comment]
loading也是这种情况，跑到顶部很奇怪。而且Table的节点嵌套太深通过样式改变就很复杂。 类似loading/暂无数据 我认为应该是在组件的下一层，通过简单的css就可以自定义的配置样式。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4722  https://github.com/ant-design/ant-design/commit/e008214f566c7855d7c0d4b940ce5a972a232ca3
https://github.com/ant-design/ant-design/issues/14486

**Comment by afc163** [comment]
可以自行覆盖样式，放在顶部是为了解决首屏看不到 loading 以为一大片空白出错了的问题，具体见上面链接。

**Comment by six-666** [comment]
@afc163 暂无数据怎么解决。

**Comment by afc163** [comment]
https://codesandbox.io/s/damp-firefly-qi7wl

空数据没有高度的。

**Comment by six-666** [comment]
@afc163 帮忙看看，  https://codesandbox.io/s/relaxed-sun-cq7xe?fontsize=14

**Comment by afc163** [comment]
可能需要多定制一点样式：https://codesandbox.io/s/focused-rhodes-4oo1i
