### ISSUE TITLE
logo for  navbar 

### ISSUE THREAD

**Issue by Johnsavadkuhi** [ant-design/ant-design#17374]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
im newbi  in ant design  i have created navbar but i could not use a logo in horizontal navbar  it seems that ant does not support or maybe it is hard to use   please help me  

### What does the proposed API look like?
<menu logo = {logo link } />

**Comment by zombieJ** [comment]
https://ant.design/components/layout-cn/#components-layout-demo-top-side-2
