### ISSUE TITLE
Antd Multiselect with "hide already selected" feature not properly wokring (label)

### ISSUE THREAD

**Issue by martinsura** [ant-design/ant-design#17371]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-thunder-ids9v)

### Steps to reproduce
Run sandbox and select some items

### What is expected?
Selected items has  name label

### What is actually happening?
Selected items has id label

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | latest |
| System | Windows 10 |
| Browser | Chrome |

---
Use "Hide already selected options in the dropdown." from documentation.

**Comment by zombieJ** [comment]
Select get display name from the list in the `children` of select. When you filter it, Select get not matched Option as display `key` instead. In your case, you can use `labelInValue` props for this.
