### ISSUE TITLE
Anchor组件缺少一个offset偏移API

### ISSUE THREAD

**Issue by chjiyun** [ant-design/ant-design#17379]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有时候页面的Layout布局是 顶部 固定的，点击锚点时锚点区域顶部会和window顶部对齐，这时候header 就遮住了锚点区域的内容（标题等），加一个offset属性就是为了偏移顶部一些距离，使锚点区域内容完全可见。

### What does the proposed API look like?
可以暴露一个方法，用来设置本组件内的点击跳转的偏移量：
```
configureAnchors({offset: -60, scrollDuration: 200})
```

**Comment by zombieJ** [comment]
`offsetTop`
