### ISSUE TITLE
Tabs 标签页，选中的项目底边颜色会应该变为选中的蓝色，当位置设置为左右两边的时候颜色改变不对

### ISSUE THREAD

**Issue by yuweilan** [ant-design/ant-design#1737]
Tabs 标签页，选中的项目底边颜色会应该变为选中的蓝色，当位置设置为左右两边的时候颜色改变不对

## Online demo

http://ant.design/#/components/tabs

## Environment Information
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
发现新版还丢失了原来的流动切换动效。
