### ISSUE TITLE
Table 能否新增如下功能。

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design#17384]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以根据用户选择的 行和列的数据进行渲染图表或者其他操作。目前用户是可以自定义表头，但是如果在 and-design 的 Table 中可配置就更完美了。

### What does the proposed API look like?
具体功能见图：
![image](https://user-images.githubusercontent.com/12181423/60405879-77215500-9be5-11e9-8881-8fcaa748af15.png)

**Comment by zombieJ** [comment]
`column 能够支持配置单选或者复选框返回选择的 column 的值` 指的是什么？给的代码例子？

**Comment by yoyo837** [comment]
很容易自己做哦，内置的话另讲。

![image](https://user-images.githubusercontent.com/6134547/60406014-50175300-9be6-11e9-81eb-9cf23827229e.png)

**Comment by hqwlkj** [comment]
@zombieJ  最近做了一个项目遇到了这样的需求，用户在操作表格的时候 需要操作行和列，并渲染出对应的图表。如图：
![image](https://user-images.githubusercontent.com/12181423/60406126-ff542a00-9be6-11e9-97da-8c4f726e3b5d.png)
`column的值是指的 ` 在行选中的情况下，返回对应行和列的 `value`，具体如下：
![image](https://user-images.githubusercontent.com/12181423/60406245-7f7a8f80-9be7-11e9-8623-7a0e5eef8344.png)

这个功能是自己可以通过自定义表头来实现，我说的是如果ant-design团队有余力:smile:看看能否将此功能提供成可配的选项  。

**Comment by hqwlkj** [comment]
@yoyo837  你的那个是一个下拉查询筛选，ant-design 已经有这样的api了。这个和我说的功能不是同一个功能。

**Comment by yoyo837** [comment]
@hqwlkj 不好意思，个人没理解到...

**Comment by afc163** [comment]
title 可以是 ReactNode。

```
title: <span>xxx<span>,
```

**Comment by hqwlkj** [comment]
@afc163   `title` 是可以 ReactNode ，但是 你要同时开启了排序的功能之后，你的 `tittle` 写的 ReactNode 事件是触发不了的，你可以测试一下， 把 title 设置为： `<Checkbox onChange={onChange}>Title</Checkbox>` ,同时开启 `column` 的 `sorter ` 属性。

**Comment by afc163** [comment]
https://codesandbox.io/s/cocky-snowflake-gu251

**Comment by hqwlkj** [comment]
@afc163  谢谢找到问题了。我忘记阻止 `Checkbox` 的 `onClick` 方法阻止事件冒泡到父元素了

**Comment by ysb25536** [comment]
@hqwlkj  render函数配置 CheckboxGroup 好像只会展示一个div标签 没有子元素 
![image](https://user-images.githubusercontent.com/14371960/60638688-f024e480-9e51-11e9-85e2-be9580ddae95.png)

**Comment by hqwlkj** [comment]
@ysb25536  你参数呢
