### ISSUE TITLE
Table组件的横向滚动时table的head没有移动

### ISSUE THREAD

**Issue by zjsxfly** [ant-design/ant-design#1738]
![z2n5jk q t64 r 1m6 jh](https://cloud.githubusercontent.com/assets/16100230/15358309/46947290-1d36-11e6-859a-e35ffd1a4f59.png)
![wa m37 mk b0 t 1iv](https://cloud.githubusercontent.com/assets/16100230/15358320/5a62bbc4-1d36-11e6-9e26-5bcc683e4e33.png)

Table组件的横向滚动时table的head没有移动

**Comment by afc163** [comment]
最好给出可重现的代码。

**Comment by afc163** [comment]
无法重现的，5 天后统一关闭，有问题再开。
