### ISSUE TITLE
Cascader showSearch not calling filter function to process search terms.

### ISSUE THREAD

**Issue by sgrobert** [ant-design/ant-design#17386]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-v0tko)

### Steps to reproduce
1. I used the official ANTD Cascader template issued on https://codesandbox.io/s/yq9pj460rx . 
2. Code reproduction placed in forked template https://codesandbox.io/embed/antd-reproduction-template-v0tko .

### What is expected?
While typing "zhe", a list result of any text containing "zhe", where search input is in lowercase, and the results still show case-insensitive results, eg. "Zhejiang... " etc. 

### What is actually happening?
The "normal" search worked but I wanted it to show search results when I typed in lowercase, which seemed to work on ANTD template but not too sure why it isn't working when I brought the code onto my platform. After some thorough testing, I realised the "showSearch" code didn't seem to call on the my filter function "filterCountries" shown in (https://codesandbox.io/embed/antd-reproduction-template-v0tko), which is the exact same code "filter", created on ANTD official Cascader sample on https://codesandbox.io/s/yq9pj460rx.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | react 16.8.6 |
| System | macosx 10.14.5 |
| Browser | chrome 75.0.3770.100 |

---
The website I have built seemed to have this problem quite some time ago, like 3-4 months back in March 2019. Now I am in the UAT phase and needing to iron out input problems, this is one of those that had user feedback that they prefer input with lowercase for search, though the results are capitalised. Eg. Typing in "zhe" and "Zhejiang.. " will appear, where search is case-insensitive.

**Comment by zombieJ** [comment]
`filter`, not `filterCountries`: https://codesandbox.io/embed/antd-reproduction-template-v0tko

**Comment by sgrobert** [comment]
> `filter`, not `filterCountries`: https://codesandbox.io/embed/antd-reproduction-template-v0tko

Thank you @zombieJ  .. didn't know the name of the method function being called actually mattered, as had presumed it can be any other method name. 

Thanks for highlighting it! Total lifesaver! ;)
