### ISSUE TITLE
Drawer组件多层嵌套时外层抽屉会被自动添加180px偏移量

### ISSUE THREAD

**Issue by lennokiki** [ant-design/ant-design#17381]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当使用Drawer组件嵌套时候，当内部Drawer显示时，外层Drawer会被自动添加180px的偏移量，并没有提供阻止此样式的props api，希望能提供一个可配的参数。

### What does the proposed API look like?
<Drawer
   title="Multi-level drawer"
   width={520}
   nestOffset={false}
   closable={false}
   onClose={this.onClose}
   visible={this.state.visible}
>
   <div>...</div>
</Drawer>
nestOffset: true; default 180px 默认当嵌套的抽屉展开时，偏移180px
nestOffset: flase; 不进行偏移
nestOffse: 具体数值; 开发者自定义设置

**Comment by afc163** [comment]
```diff
- <Drawer>
-   <Drawer />
- </Drawer>
+ <Drawer />
+ <Drawer />
```

改成这样。

**Comment by lennokiki** [comment]
👌 现在给父级Drawer加了个 style={{transform: 'translateX(0)'}}，暂时就不改业务逻辑了，~ ~

**Comment by lennokiki** [comment]
> ```diff
> - <Drawer>
> -   <Drawer />
> - </Drawer>
> + <Drawer />
> + <Drawer />
> ```
> 
> 改成这样。

3Q 感谢解答

**Comment by jljsj33** [comment]
这个我感觉是不是可以把 getPushTransform(depth) 直接暴露出来，，层级用深度来控制？？？@afc163

**Comment by pfdgithub** [comment]
从底部弹出，也会造成父级 Drawer 被加上 transform: translateX(-180px);
这就不符合预期了吧？

**Comment by Ray-56** [comment]
@pfdgithub 同样疑问

**Comment by luichooy** [comment]
> 从底部弹出，也会造成父级 Drawer 被加上 transform: translateX(-180px); 这就不符合预期了吧？

同疑问，有时候由于组件拆分和多层级嵌套，下面的方式并不是很方便

```jsx
- <Drawer>
-   <Drawer />
- </Drawer>
+ <Drawer />
+ <Drawer />
```

**Comment by pccai** [comment]
push | 用于设置多层 Drawer 的推动行为 | boolean \| { distance: string \| number } | { distance: 180 } | 4.5.0+

**Comment by Jinsdw** [comment]
到现在都没能解决这个问题吗 @ant-design-bot

**Comment by afc163** [comment]
@Jinsdw 看下 https://github.com/ant-design/ant-design/issues/17381#issuecomment-507098260 ？

**Comment by Jinsdw** [comment]
> @Jinsdw 看下 [#17381 (comment)](https://github.com/ant-design/ant-design/issues/17381#issuecomment-507098260) ？

感恩，但是组件嵌套太多层了，已经摘不出来了，没办法好像只能手搓了

**Comment by afc163** [comment]
`push={false}` 关掉这个行为也行。

**Comment by Jinsdw** [comment]
> `push={false}` 关掉这个行为也行。

可以的，谢谢
