### ISSUE TITLE
Add open in window icon

### ISSUE THREAD

**Issue by ranrib** [ant-design/ant-design#17393]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There is a very common icon of "open in new window/tab" which is always missing for me in antd icons. I would love if you can add it. for example:

https://www.google.com/search?q=open in new window icon&tbm=isch&source=iu&ictx=1&fir=rHYNIGlO2ZoQgM%253A%252CX7FJllfSkW3RmM%252C_&vet=1&usg=AI4_-kSH8uzWHrVGzw51vYW9nGt2bdEuew&sa=X&ved=2ahUKEwjFpqLGtpPjAhUHfFAKHXaxD7gQ9QEwAHoECAMQBA#imgrc=rHYNIGlO2ZoQgM:

Thanks!

### What does the proposed API look like?
just a new icon where the <Icon type="new-window" />

**Comment by afc163** [comment]
`<Icon type="export" />`

**Comment by ckarsan** [comment]
I figured out a roundabout way to make the "open in new window" icon- you can use <SelectOutlined rotate={90} /> - and put it in a <sup> tags - (superscript) incase that helps anyone!

**Comment by realleyriley** [comment]
any chance we can get a proper icon for this? I think it's a very relevant icon

**Comment by rvinzent** [comment]
@afc163 can we please re-open this issue? `Export` is clearly a different icon than the widely accepted "open in new tab" icon

Export:
<img width="22" alt="Screen Shot 2023-03-17 at 2 34 34 PM" src="https://user-images.githubusercontent.com/34038882/226058801-9ac6a030-17a3-4041-ab7f-e7bec9f0f02b.png">

Open in new tab:
<img width="341" alt="Screen Shot 2023-03-17 at 2 43 29 PM" src="https://user-images.githubusercontent.com/34038882/226058830-373e2800-6b66-4cda-b62d-185fc3e3a1d5.png">

AntD has to be the only icon library I've ever seen without a proper "open in new tab" icon
