### ISSUE TITLE
Set active flag for menus by multiple keys

### ISSUE THREAD

**Issue by samialmorshedi** [ant-design/ant-design#17398]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a menu and one of the options is 

```
<Menu.Item key="/posts">
  <Link to="/posts">Posts</Link>
</Menu.Item>

```
as you can see, it navigates to /posts page and when you refresh the page in a location of  /posts, you can see this menu has an active flag which is a blue underline. 

### What does the proposed API look like?
but I need to make this menu active by all extension of this menu. I mean this menu should be still active if the route is one of this list:

- /posts/new
- /posts/show/1
- /posts/...

everything, after /posts/, should not be important and this "Posts" menu should be marked as the active menu.
How can I do that?

**Comment by keithort** [comment]
Create a function that searches `window.location.pathname` for a given key, in your case `posts` and, if found, add the key to the `selectedKeys` prop of `<Menu>`

**Comment by samialmorshedi** [comment]
tnx. fixed.

```
currentMenuKey(key){
      if (this.props.location.pathname.search(key) >= 0) {
        return this.props.location.pathname;
      }else{
        return key
      }
    }
```

```
<Menu.Item key={this.currentMenuKey('/posts')}>
     <Link to="/posts">posts</Link>
  </Menu.Item>

  <Menu.Item key={this.currentMenuKey('/users')}>
     <Link to="/users">users</Link>
  </Menu.Item>
```
