### ISSUE TITLE
Upload component allows multiple upload when `multiple` is set to false

### ISSUE THREAD

**Issue by InsaLili** [ant-design/ant-design#17397]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/agYJxE?editors=0010](https://codepen.io/anon/pen/agYJxE?editors=0010)

### Steps to reproduce
1. in props, set `multiple` to `false`
2. drag and drop multiples onto the Upload zone
3. uploaded successfully

### What is expected?
There should be a validation (like a warning message) for the single upload when user is trying to upload multiple files

### What is actually happening?
Users can successfully upload multiple files when `multiple` is set to `false`

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.5 |
| System | Windows |
| Browser | Chrome |

---
It will be nice to add a validation for the `onFileDrop` function to detect whether the `fileList` length is not greater than 1 when the `multiple` props is set to `false`

**Comment by InsaLili** [comment]
Any updates for the issue? The pr looks good to me.

**Comment by vrunda-thacker** [comment]
Any updates on when this fix will be available?

**Comment by yoyo837** [comment]
```js
const { type, multiple } = this.props;
  if (type === 'drag' && !multiple && fileList.length > 0) {
      return;
}
```

Will this works?

**Comment by arpanEnbake** [comment]
Still getting this issue with dragger.
Setting multiple false allows to upload multiple files, in antd version 4.4.2

**Comment by anaalicefig** [comment]
I'm having problem with dragger too.
Setting multiple false allows to upload multiple files, in antd version 4.4.2

**Comment by muhsin-k** [comment]
Any update on this issue?

**Comment by arpanEnbake** [comment]
I did a work around for this by using following code.

`

  normFile = (e: { fileList: any }) => {
    if (Array.isArray(e)) {
      return e;
    }
    if (e.fileList.length > 1) {
      // this is a hack because of bug in antd multiple setting
      // https://github.com/ant-design/ant-design/issues/17397
      return [e.fileList[1]];
    }
    return e && e.fileList;
  };

 <Form.Item label="">
        <Form.Item
          name="dragger"
          valuePropName="fileList"
          getValueFromEvent={this.normFile}
          noStyle
          rules={[{ required: true, message: 'File is required to proceed.' }]}
        >
  <Upload.Dragger {...this.dragProps}>
            <p className="ant-upload-drag-icon">
              <InboxOutlined />
            </p>
            <p className="ant-upload-text">Click or drag file to this area to upload</p>
            <p className="ant-upload-hint">Support for a single file bulk upload.</p>
          </Upload.Dragger>
        </Form.Item>
      </Form.Item>

  dragProps = {
    name: 'file',
    multiple: false,
    accept: '.csv',
    onChange: (info: { file: { status: string; originFileObj: Blob; name: any } }) => {
      try {
        if (info.file.status === 'done') {
          message.success(`${info.file.name} file uploaded successfully`);
        } else if (info.file.status === 'error') {
          message.error(`${info.file.name} file upload failed. An error came`);
        }
      } catch (e) {
        message.error(`${info.file.name} file upload failed.`);
      }
    },
    beforeUpload: this.beforeUploadFunc,
    onRemove: () => this.props.onChange([]),
  };

`

**Comment by klenofjupiter** [comment]
> maxCount={1}>

Trevor, you are my hero, this worked like a dream and saved me an argument with a designer

**Comment by AbhiGhoghari** [comment]
same here bro i was fighting with my designer to change this!! thank you !!
