### ISSUE TITLE
连续 setState 时 Form 组件会警告

### ISSUE THREAD

**Issue by wangjianio** [ant-design/ant-design#17391]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7lonc)

### Steps to reproduce
连续 setState 两次，查看控制台，会有 warning

### What is expected?
没有报错

### What is actually happening?
```
Warning: Duplicate field names will result in both fields getting edited together. Field names must be unique
```

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | macOS |
| Browser | Chrome |

---
class 组件和 function 组件都有问题，class 组件可合并 setState 避免，function 组件不行。

**Comment by mastercbhw** [comment]
这个bug简直难受死我了

**Comment by wuyandefeixue** [comment]
不知道怎么报错的，从3.15升级过来，就报警告了，啥原因啊！！！

**Comment by Gjb7598189** [comment]
这个有解吗？

**Comment by wuyandefeixue** [comment]
getFieldDecorator时，报这个错，真的很奇葩啊！

**Comment by mastercbhw** [comment]
查看了一下本地安装的依赖包，rc-form版本是2.4.7，安装rc-form@2.4.6之后，没有再次出现此类问题。

**Comment by zombieJ** [comment]
`setState` 同时多次不会触发 `componentDidUpdate`，先 revert 掉 https://github.com/react-component/form/pull/297

**Comment by nannongrousong** [comment]
我 还以为是自己问题呢 找了半天。
