### ISSUE TITLE
Collapse.Panel Support Three Level Size

### ISSUE THREAD

**Issue by xyy94813** [ant-design/ant-design#17394]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When use `Collapse` in small size `Card` or `List`, It won’t look strange.

### What does the proposed API look like?
`<Collapse size="XXX" />`
(It is better all components use same size value. Should not be some `normal`, and some are `middle`)

**Comment by afc163** [comment]
No plan in our design, you can customize your own Collapse.
