### ISSUE TITLE
Require custom classname for suffix for Input.search 

### ISSUE THREAD

**Issue by zeel** [ant-design/ant-design#17395]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-0z605)

### Steps to reproduce
Click on search icon.

### What is expected?
There should be a prop for the class name of the search icon.

### What is actually happening?
There is no way to change the class name of the suffix - search icon.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | MacBook Pro |
| Browser | Google Chrome version 75.0.3770.100 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Your codesandbox not works.

**Comment by afc163** [comment]
```js
<Search className="xxx" />
```

```css
.xxx .ant-input-suffix {
}
```
