### ISSUE TITLE
组件RangePicker相关

### ISSUE THREAD

**Issue by liujian10** [ant-design/ant-design#1739]
> 备注：基于antd-init的antd-demo。

## 组件RangePicker在第一次点击时【之后不会】出现如下信息
![image](https://cloud.githubusercontent.com/assets/17332112/15349378/e42a7194-1d04-11e6-858d-df220b2dd0f8.png)

**Comment by afc163** [comment]
fixed in https://github.com/react-component/calendar/commit/f581b0973beea844a8280c1f24e0b154720a6baa

重装 antd 即可修复。
