### ISSUE TITLE
cascader 中 value 添加支持  number 类型

### ISSUE THREAD

**Issue by simdd** [ant-design/ant-design#17407]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### 问题描述：

cascader 组件中 value 只支持string，不支持 number

### 需求

支持 number 类型

### 相关代码：

https://github.com/ant-design/ant-design/blob/master/components/cascader/index.tsx#L60

### 如果是设计如此：

     请告诉一下我为什么设计成只支持 string，谢谢

### What does the proposed API look like?

支持 number

**Comment by afc163** [comment]
Could you create a PR to imporove it?

**Comment by hengkx** [comment]
Let me deal with it. before the encounter also needs `number` to be converted into `string` is very difficult

**Comment by XianZhengquan** [comment]
@simdd 你这个标题改的是不是有歧义啊，只支持number类型，也就是其他类型都不支持了。

**Comment by simdd** [comment]
> @simdd 你这个标题改的是不是有歧义啊，只支持number类型，也就是其他类型都不支持了。

修改啦

**Comment by afc163** [comment]
Thx! @Loogeek #24247
