### ISSUE TITLE
table 列头和内容可能不对齐

### ISSUE THREAD

**Issue by zinkey** [ant-design/ant-design#1740]
![image](https://cloud.githubusercontent.com/assets/1016267/15350622/fbfaad2c-1d0c-11e6-9aef-f7fe9880abfc.png)

问题：table 错位，columns中每一个都设置了 width。

antd 1.0.1

```js
<Table borderer scroll={{ y: 240 }} ... />
```

**Comment by afc163** [comment]
目前可以先这样解决：最后一列不设宽度，保证一定的伸缩性。

**Comment by yeyuguo** [comment]
的确只能留一列不设宽度，不设置多列宽度都是对不齐的...

**Comment by yeyuguo** [comment]
width 和 scroll.x 都设置的大一点，如果其中一个不够大时，都会有这个问题，今天终于解决了，以前就只设置了其中一个，才导致一直没有解决这个对齐问题。

**Comment by shanshanfei** [comment]
我这也遇到了表头和内容不对齐的问题，原因是：表格中有设置文字溢出的样式，表格列设置的宽度是120，.ellipsis的width也设置了120，最终内容的宽度超出了列宽，导致表头和内容不对齐，将.ellipsis的width也设置成小于120（100）后，问题解决。供大家参考

**Comment by aloehh** [comment]
同样遇到了这个问题，设置了y轴scroll，表头与数据对不齐

**Comment by America-first-melon** [comment]
> 同样遇到了这个问题，设置了y轴scroll，表头与数据对不齐

这个y写了， width也写了， 里面文字不断字的情况下 会直接超出

**Comment by JunlinZhu-Tommy** [comment]
遇到了同样的问题。

**Comment by mqliutie** [comment]
所以咋整

**Comment by mqliutie** [comment]
我通过调整 `table>th`,`table>td` 的 `padding` 弄对齐了； 

因为我把他俩`padding`都设置 **0** 以后内容和表头就对齐了

`antd`默认的`th`和`td`是**16px**,对于我的情况我调成**8px**就ok了， 希望对其他人有帮助

**Comment by Jad2wizard** [comment]
设置每列宽度后，可以设置 table.table-layout: fixed

**Comment by MaZhengA** [comment]
给每个columns设置宽，再在scroll里面给X设置一个相对大的值，就不会出现对不齐的情况了
