### ISSUE TITLE
Tooltip组件，触摸屏设备使用存在问题

### ISSUE THREAD

**Issue by jszjgqq** [ant-design/ant-design#17401]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Tooltip 的trigger默认是hover,在触摸屏使用的时候很难操作,但是又没办法像Dropdown组件一样, trigger支持array, 可以同时给两个触发事件, 这样就能解决在普通显示屏上用hover触发, 触摸屏又能用 click触发.

### What is expected?
trigger改为array, 同时支持多种事件的触发, 同Dropdown的 trigger方式.

### What is actually happening?
trigger只支持string, 无法同时满足普通屏幕跟触摸屏下的需求.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome 71 |

**Comment by zombieJ** [comment]
在移动设备上，Tooltip 的触发是点击弹出，点击外侧关闭。和 PC 是不一样的，不用特地设置。
