### ISSUE TITLE
Form label fixed width

### ISSUE THREAD

**Issue by farzer** [ant-design/ant-design#17409]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
當 labelAlign 為 left 的時候，屏幕寬度不同導致 label 和 input(獲取其他表單組件) 的間隙較大，不美觀

when `labelAlign` is `left`, different screen widths result in large gaps between label and Form component (like input or select), not beautiful 

example:

![image](https://user-images.githubusercontent.com/9881593/60496100-b2567d80-9ce4-11e9-87b3-27c314f2e7be.png)

### What does the proposed API look like?
```
<Form {...formItemLayout} labelAlign="left" labelWidth={200}>
...
</Form>
```

**Comment by afc163** [comment]
`<Form layout="inline">`

**Comment by yezongyang** [comment]
使用浮动百分比很奇怪啊，页面宽度变化，label 还会显示错位

**Comment by chengwb53** [comment]
这个需求还没处理吗？

**Comment by peakandyuri** [comment]
```tsx
<Form.Item labelCol={{style: {width: 200}}}>
...
</Form.Item>
```
