### ISSUE TITLE
when use getFieldDecorator，Warning: Duplicate field names will result in both fields getting edited together. Field names must be unique

### ISSUE THREAD

**Issue by wuyandefeixue** [ant-design/ant-design#17408]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9s9zb)

### Steps to reproduce
1.click search button 
2.console show warning

### What is expected?
no warning

### What is actually happening?
Report warning, prompt “Duplicate field names will result in both fields getting edited together. Field names must be unique”

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.9.0 |
| System | win10 1709 |
| Browser | Chrome/74.0.3729.108 |

---
The warning disappears when the antd is changed to 3.19.0.
For example：https://codesandbox.io/s/bvt1m

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/form/pull/308, try to reinstall antd.

**Comment by wuyandefeixue** [comment]
@afc163 
我发的codesandbox啊？这和重装antd有什么关系？那上面不就是antd 3.20.0么？我又没有说我自己的环境！

**Comment by afc163** [comment]
已经修复了，codesandbox 会有缓存延迟。

**Comment by wuyandefeixue** [comment]
@afc163 
```json
"rc-form": {
      "version": "2.4.7",
      "resolved": "https://registry.npmjs.org/rc-form/-/rc-form-2.4.6.tgz",
      "integrity": "sha512-v4QnbGJ0wgfTbekwSxt824l30Zr9fDXZYnPoi2PSJwb4vA5PvLibHAvlVaQBA9ZLgBjFMa4qo9f7fAuHgBSq/w==",
      "requires": {
        "async-validator": "~1.11.3",
        "babel-runtime": "6.x",
        "create-react-class": "^15.5.3",
        "dom-scroll-into-view": "1.x",
        "hoist-non-react-statics": "^3.3.0",
        "lodash": "^4.17.4",
        "warning": "^4.0.3"
      },
```
今天下午刚更新的rc-form啊，这个版本还不行么？

**Comment by afc163** [comment]
rc-form@2.4.8

**Comment by wuyandefeixue** [comment]
OK

**Comment by eeeqxxtg** [comment]
嗯。。。3.20.1又出现了这个问题

**Comment by ondc** [comment]
rc-form@2.4.8

解决这个问题

**Comment by citrusjunoss** [comment]
3.20.3, 这个问题依旧存在

**Comment by citrusjunoss** [comment]
> 3.20.3，这个问题依旧存在

3.20.3 的package.json 中 , rc-form 的版本为^ 2.4.5,  由于缓存, 重新安装antd 后, rc-form 版本未升级, 升级后不报错了

![image](https://user-images.githubusercontent.com/18432488/61434254-078ec200-a968-11e9-8112-a036ddbb337d.png)

**Comment by jeggy** [comment]
I'm also experiencing this on `3.20.3`. 

A workaround if you are using `yarn` is adding `"rc-form": "2.4.8"` to `resolutions` in your `package.json`.
