### ISSUE TITLE
message.loading 圈圈的颜色，没有受到定制主题颜色控制

### ISSUE THREAD

**Issue by YoFoon** [ant-design/ant-design#17406]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
message.loading 圈圈的颜色，没有受到定制主题颜色控制

### What is expected?
message.loading 圈圈的颜色，应该受到定制主题颜色控制

### What is actually happening?
message.loading 圈圈的颜色，没有受到定制主题颜色控制

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.4.2 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
It is by designed, try to override `@info-color`.
