### ISSUE TITLE
Table filter under the header

### ISSUE THREAD

**Issue by Timson020** [ant-design/ant-design#17417]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户体验

### What does the proposed API look like?
后台管理系统 的 filter 添加到 header 下面可能会更加符合用户体验

**Comment by afc163** [comment]
建议自行构建更贴近自身业务需求的表格。
