### ISSUE TITLE
Input：当自定义后缀图标和清除图标同时存在时，显示错误

### ISSUE THREAD

**Issue by ohhoney1** [ant-design/ant-design#17414]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/nifty-benz-gb7ml)

### Steps to reproduce
1. 已经自定义了后缀图标，且允许清除图标存在
2. 输入；输入足够多的内容

### What is expected?
1. 当输入的内容超过一定宽度时，清除图标正常显示；
2. 当后缀图标自定义了大小，例如为 20，清除图标居中

### What is actually happening?
1. 当输入的内容超过一定宽度时，清除图标覆盖到了文字上；
2. 当后缀图标自定义了大小，例如为 20，清除图标不居中

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8 |
| System | mac OS 10.14 |
| Browser | Chrome |

**Comment by yoyo837** [comment]
@LilyWakana 

![image](https://user-images.githubusercontent.com/6134547/61192294-e61ea380-a6e5-11e9-947d-bbb75d63e175.png)

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/61192324-0babad00-a6e6-11e9-85d8-4160ee4cf5b7.png)

**Comment by brickspert** [comment]
![image](https://user-images.githubusercontent.com/12526493/61196665-d6618800-a702-11e9-93a8-7cfdffd309bd.png)

**Comment by ohhoney1** [comment]
之前有注意到那个PR，没想到已经合了而且发布了。。 🤣建议发布个紧急版本吧

**Comment by yesmeck** [comment]
已发布 3.20.3

**Comment by yoyo837** [comment]
这个issue reopen 吧
