### ISSUE TITLE
DatePicker有showTime的情况下，ie下选中日期，panel立即关闭

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#17410]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-time](https://ant.design/components/date-picker-cn/#components-date-picker-demo-time)

### Steps to reproduce
点击日期输入框，随意选择一个日期，panel马上关闭
![date-picker](https://user-images.githubusercontent.com/22299421/60498194-bbe1e480-9ce8-11e9-80d8-92be421ce2bd.gif)
### What is expected?
点击日期输入框，随意选择一个日期，panel不关闭，还可以选择具体时间

### What is actually happening?
点击日期输入框，随意选择一个日期，panel马上就被关闭

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | react16 |
| System | win10 |
| Browser | ie9/10/11 |

**Comment by designersmallweb** [comment]
问题解决了吗？

**Comment by mraiguo** [comment]
@designersmallweb 修改了rc-calendar处理了这个，但是还是有一个小问题，所以没有提交pr
