### ISSUE TITLE
table filter 分页问题

### ISSUE THREAD

**Issue by zinkey** [ant-design/ant-design#1741]
table 的筛选应该只筛选当前页的数据，但是现在却会跟其他页数据有关，这样带来分页的问题。

比如：

第一页：[美元，人民币]

第二页：[人民币，美元]

操作：在第一页 筛选  “人民币”，应该是第一页出现一条记录，[人民币]。但实际会是 [人民币，人民币]。这样分页已经乱了。

antd 1.0.1

**Comment by zinkey** [comment]
demo: http://codepen.io/zinkey/pen/JXQdQN?editors=0010

**Comment by zinkey** [comment]
数据筛选应该是当前页的数据进行筛选而不是整个数据进行筛选。

**Comment by afc163** [comment]
应该根据整个数据进行筛选，单页筛选意义不大的。

**Comment by afc163** [comment]
去掉指定的 pagination.total 就好了，这个数字会根据筛选自动计算的，父层控制了肯定不变。

http://codepen.io/anon/pen/MyMaKK?editors=0010

**Comment by superRaytin** [comment]
@afc163 效果貌似是一样的

**Comment by afc163** [comment]
分页器不一样。
