### ISSUE TITLE
Allow custom SVG Icon for Button

### ISSUE THREAD

**Issue by potty** [ant-design/ant-design#17413]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
You can use your own icons for buttons.

### What does the proposed API look like?
```js
<Button shape="circle" icon={<Icon component={CustomSvg} />} />
```

**Comment by afc163** [comment]
```jsx
<Button shape="circle">
  <Icon component={CustomSvg} />
</Button>
```

**Comment by wujekpiotr** [comment]
`<Button shape="circle" className="ant-btn-icon-only">
  <Icon component={CustomSvg} />
</Button>`
