### ISSUE TITLE
Cascader: Not able to select search results second time using key board (after changing the search text)

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#17422]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-tharp-jlzh3)

### Steps to reproduce
1) Enter search text and filter the result in cascader
2) use keyboad(down arrow) keys to select the fliterd values and hit enter
3) value get selected
4) change the search text and results will be displayed based on new search
5) try selecting the values again using keyboad(down arrow)
6) Not able to select the values second time (after changing the search text)

### What is expected?
Able to select the values using the keyboard (down arrow) every time search results changes

### What is actually happening?
Only first time its working.Next time not working. Once changed the search text not able to select the values using keyboard 

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | any |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
trace #24173
