### ISSUE TITLE
关于Select中optionLabelProp指定的字符串在Select.Option中type不存在问题

### ISSUE THREAD

**Issue by Cslove** [ant-design/ant-design#17423]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-allen-towgy)

### Steps to reproduce
```
const Option: React.ClassicComponentClass<OptionProps>
不能将类型“{ children: (string | Element)[]; value: string; label: string; }”分配给类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, any, any>> & Readonly<OptionProps> & Readonly<{ children?: ReactNode; }>”。
  类型“IntrinsicAttributes & IntrinsicClassAttributes<Component<OptionProps, any, any>> & Readonly<OptionProps> & Readonly<{ children?: ReactNode; }>”上不存在属性“label”。
```
`<Option value="china" label="China">`

### What is expected?
不报属性不存在错误

### What is actually happening?
报属性不存在错误

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.1 |
| System | mac10.13.6 |
| Browser | chrome74 |

---
能否在OptionProps中加入:
```
export interface OptionProps {
    disabled?: boolean;
    value?: string | number;
    title?: string;
    children?: React.ReactNode;
    className?: string;
    style?: React.CSSProperties;
    [key: string]: React.ReactNode;   // 加入通用的optionLabelProp指定的string
 }
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17493
