### ISSUE TITLE
DatePicker is mixing timezones

### ISSUE THREAD

**Issue by pavolgolias** [ant-design/ant-design#17434]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pavolgolias/pen/VJdZoO](https://codepen.io/pavolgolias/pen/VJdZoO)

### Steps to reproduce
1. Load the page, click into date picker and manually type 2019-01-01
2. Open the console, you should see Tue Jan 01 2019 00:00:00 GMT+0100 (or your timezone)
3. Again click the date picker, choose anther date (for example 2019-01-02) and you should see Wed Jan 02 2019 00:00:00 GMT+0100 (or your timezone)
4. Now reload the page
5. Click into date picker and choose 2019-01-01 from the opened panel (do not type manually)
6. Look to the console, you should see something like Tue Jan 01 2019 10:47:40 GMT+0200 (or your timezone)
7. Again click the date picker and choose another date from panel (2019-01-02) and you should see something like Wed Jan 02 2019 10:47:40 GMT+0200 (or your timezone)

### What is expected?
I am not sure what was intended behavior, but I see two points to be the problem:
1. There should be no difference in time or even timezone depending on how I use date picker (by how I use date picker I mean typing the date manually to the input or choosing date from panel)
2. When using only date picker, why is there time or even time zone? It is only the day I am interested in. I understand it is build upon Moment, but still.

### What is actually happening?
Described behavior causes me problems in multiple ways.
For example, when the time is set to 00:00:00 (so I typed date manually), when I send it to the server, it moves the date one day back (it also depends on your time zone).

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | win 10 |
| Browser | chrome 75.0.3770.100 |

---
Please, when trying to reproduce, try to follow steps exactly as described above. It is possible that you will not reproduce it at the first try, but I was always able to simulate this bug.

**Comment by zombieJ** [comment]
By manual typing, it format your typing time with moment object. And by click the moment generate with moment and set date of it. All of them is return the same timezone. You can add additional console for check: https://codesandbox.io/s/modest-feather-9ozm8

For server post date back, most case is by the server & client not use same timezone or miss use time parse. To avoid that, you can just post time str without timezone like '2019-01-01' to let server to handle that. Or lock front end timezone sync with server.

**Comment by pavolgolias** [comment]
Good solution for me was this - as I mostly need to work with DatePicker only - [momentjs docs - toJSON](https://momentjs.com/docs/#/displaying/as-json/).
