### ISSUE TITLE
日历-Calendar-默认选中当天7月3日；切换到6月，会默认选中6月的3号，切换 到5月，会默认选中5月的3号；不希望非当前月默认选中day

### ISSUE THREAD

**Issue by 7Charlotte** [ant-design/ant-design#17436]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar-cn/#components-calendar-demo-customize-header](https://ant.design/components/calendar-cn/#components-calendar-demo-customize-header)

### Steps to reproduce
在官方控件案例中切换：比如今天是7月3号，默认选中了3号。切换到6月时，也选中了3号。切换到其他年份时，也会选中3号。但是非当前月的3号选中了没有任何意义。

### What is expected?
非当前月不要默认选中日期。如附件

### What is actually happening?
比如今天是7月3号，默认选中了3号。切换到6月时，也选中了3号。切换到其他年份时，也会选中3号。但是非当前月的3号选中了没有任何意义。

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 3.20.0 |
| System | Mac OS 10.14.5 |
| Browser | Chrome 版本 75.0.3770.100（正式版本） （64 位） |

![画板](https://user-images.githubusercontent.com/4272864/60579570-f06fa200-9db5-11e9-8934-ae11c348499b.png)

**Comment by 7Charlotte** [comment]
@@chenshuai2144 请关注一下这个问题

**Comment by yoyo837** [comment]
你的意思就应该是翻阅归翻阅，没确定选择，对当前日历组件的选中日期值不做更改吧？那不就需要一个“确定”的功能么？如果没有，是不是帮你切换也算合理？

**Comment by 7Charlotte** [comment]
> 你的意思就应该是翻阅归翻阅，没确定选择，对当前日历组件的选中日期值不做更改吧？那不就需要一个“确定”的功能么？如果没有，是不是帮你切换也算合理？

你的意思就应该是翻阅归翻阅，没确定选择，对当前日历组件的选中日期值不做更改吧？——是的。

那不就需要一个“确定”的功能么？如果没有，是不是帮你切换也算合理？——算是合理。但是也存在不希望帮用户选择的的场景，所以能不能开放这项设置。

**Comment by yomonah** [comment]
同类需求+1，希望可以属性配置不要默认选择切换月份后同一天的日期

**Comment by chm1n9** [comment]
+1， 我就是随便翻一下上下月，选中值不应该变，控制视图的value和选中的value不应该是同一个

**Comment by 0408jiahuicao** [comment]
+10086, i do not want to default to the same day as the switch month，Please pay attention to this issue

**Comment by afc163** [comment]
已经在 v4 中做了调整，现在切换月份没有默认选择的高亮日了。

**Comment by KylinDC** [comment]
我看官网的例子中，只是切换月份和年份，也会默认选择同一天的日期，使用时也是这样

**Comment by 0408jiahuicao** [comment]
是的 我希望能按照正常选择的日期进行显示 而不是显示相同的日期在月份不同的情况下



在 2020-04-26 19:24:20，"KylinDC" <notifications@github.com> 写道：

我看官网的例子中，只是切换月份和年份，也会默认选择同一天的日期，使用时也是这样

**Comment by hhwangS27** [comment]
> 已经在 v4 中做了调整，现在切换月份没有默认选择的高亮日了。

依然会默认选择高亮日啊 偏右大大 测试版本 antd 4.3.3

**Comment by wangyibinwangyi** [comment]
2021年4月份了，似乎还是没有上述配置诶大大。。。

**Comment by MaZhengA** [comment]
这个问题没有解决掉，为什么要closed呢？

**Comment by wangcongyi** [comment]
2021-09-09 still not fix

**Comment by sunsmeil** [comment]
同求

**Comment by l1shu** [comment]
> 已经在 v4 中做了调整，现在切换月份没有默认选择的高亮日了。

2022-4-27  目前依然不可以

**Comment by shellyao** [comment]
2025年了，这个问题还存在，我现在需要默认显示非当前月的，然后它默认选中了一号，其实不需要选中啊， @chenshuai2144
