### ISSUE TITLE
Select not rendering filtered options

### ISSUE THREAD

**Issue by Gervwyk** [ant-design/ant-design#17438]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-select-filter-issue-p5gwq)

### Steps to reproduce
Search select options.

### What is expected?
Select should only list options for which the label matches.
Render all options as filtered by search state.

### What is actually happening?
No options is rendered, although the options is returned correctly by search filter function.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | latest |
| System | ios |
| Browser | chrome |

---
Antd Rocks! :)

**Comment by zombieJ** [comment]
Select already provides `filterOption` prop. You need not to realize yourself.

And Select default filter option with its `value` prop. So you provides a `label` filtered options and Select filter with `value` cause nothing match. If you want to filter by `value` you can use `optionFilterProp` instead: https://ant.design/components/select-cn/#components-select-demo-search
