### ISSUE TITLE
自定义主题中table组件的title不支持自定义背景颜色

### ISSUE THREAD

**Issue by WangLinghang** [ant-design/ant-design#17431]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by sunwenli** [comment]
同问

**Comment by yoyo837** [comment]
`@table-header-bg`

**Comment by sunwenli** [comment]
<Table columns={columns} dataSource={data} title={()=> <div style={{
    marginLeft: -16,
    marginBottom: -16,
    marginRight: -16,
    marginTop: -16,
    paddingBottom: 10,
    paddingTop: 10,
    textAlign: "center",
    backgroundColor: "#a2e8c0",
  }} >居中对齐</div> } />;

**Comment by sunwenli** [comment]
```
<Table columns={columns} dataSource={data} title={()=> <div style={{
    marginLeft: -16,
    marginBottom: -16,
    marginRight: -16,
    marginTop: -16,
    paddingBottom: 10,
    paddingTop: 10,
    textAlign: "center",
    backgroundColor: "#a2e8c0",
  }} >居中对齐</div> } />;
```
