### ISSUE TITLE
treeSelect出现warning，但是数据中并未出现key值重复的数据？

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design#17441]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---
![image](https://user-images.githubusercontent.com/23158766/60587927-3d5c7400-9dc8-11e9-9903-71e76170494e.png)

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by Wangzongyao** [comment]
这个问题我也遇到了，是如何导致的呢？

**Comment by Wangzongyao** [comment]
我这里是因为没有写value
