### ISSUE TITLE
Col does disable component if span is missing 

### ISSUE THREAD

**Issue by ilkerceng** [ant-design/ant-design#17445]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/headless-dream-wbcqk)

### Steps to reproduce
- define 3 Col in one Row.
- add span prop to 2 of them
- define Button in each Col as a child component

### What is expected?
all of the buttons should be clickable

### What is actually happening?
If you apply steps defined in "step to reproduce", you will see that the buttons defined in Cols having span prop will not be clickable

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.9.0 |
| System | Windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
It is by designed, just don't miss `span`. Or you can try `<Row type="flex">`.

**Comment by ilkerceng** [comment]
Thanks. But i have just a confusion. I have just updated antd version from 3.9.2  to 3.20.0. I just didn't understand why it breaks. Is it a bug in version 3.9.2?
