### ISSUE TITLE
Message组件当为移动端触摸点击的时候，多次点击后会导致其永远不消失

### ISSUE THREAD

**Issue by mingChen2017** [ant-design/ant-design#17444]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/message-cn/](https://ant.design/components/message-cn/)

### Steps to reproduce
任何项目都一样，包括antd官网示例，只要使用了Message组件的页面，请打开你们的chrome浏览器，切换至手机模拟界面，或者用手机浏览器测试，只要Message出来后你快速连续的点击几下Message对象，他就永远都不会消失，修正一下，应该是在保持页面静止的时候会永远不消失，如果页面发生了变动（暂时未知是什么变动引起的变化）还是会消失，但是消失时间远远超过3秒（应该不是你们的设计初衷？）

### What is expected?
三秒后会自动消失

### What is actually happening?
永远不会消失

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 任意 |
| System | 任意 |
| Browser | 任意 |

**Comment by daweilv** [comment]
注意到 Message 组件在 PC 端鼠标 :hover 在上面的时候会一直显示，鼠标移开就隐藏。手机端的时候点击会模拟PC端的 :hover 并且焦点一直在上面，直到你点击其他区域后焦点消失，Message 组件隐藏。不知道这种问题怎么定义，Bug or Browser Feature?

**Comment by zombieJ** [comment]
Message 的行为是如果鼠标悬浮到它上方，计时器会暂停，移出后计时器重置。为了防止预留时间过短导致用户来不及阅读。
而在移动端，行为也是类似的。点击后暂停计时器，点击外侧后重新倒计时后关闭。

**Comment by DIamondstrip** [comment]
> 消息的行为是，手机会暂停播放，然后出现点击后显示，如果手机在一段时间内过短而出现 的端不出现点击。 ，点击温度后重新倒帐后关闭。

不能把鼠标移入暂停这个操作交给开发者自己决定吗

**Comment by xinghaiyang1994** [comment]
我这边使用 notification 也遇到了同样的问题。这里有个 hack 的方式解决：
将所有使用 notification 的地方统一入口，每次调用都生成一个唯一的 key,同时加上 onClick 的事件监听来延迟销毁对应的 notification。

```tsx
import { notification } from 'antd';
import { ArgsProps } from 'antd/es/notification';
import { v4 } from 'uuid';

type TConfig = Pick<ArgsProps, 'message' | 'duration' | 'key'>;

/** 生成 notification 的 id 和 onClick 解决移动端点击不消除的问题 */
const createNotificationIdAndOnClick = () => {
  const key = v4();
  return {
    key,
    onClick: () => {
      setTimeout(() => {
        notification.close(key);
      }, 1500);
    },
  };
};

/** 统一消息提示,方便后面统一替换 */
const basicNotification = {
  success: (config: TConfig) => {
    notification.success({
      ...createNotificationIdAndOnClick(),
      ...config,
    });
  },
  warning: (config: TConfig) => {
    notification.warning({
      ...createNotificationIdAndOnClick(),
      ...config,
    });
  },
  /** 兼容 */
  warn: (config: TConfig) => {
    notification.warning({
      ...createNotificationIdAndOnClick(),
      ...config,
    });
  },
  error: (config: TConfig) => {
    notification.error({
      ...createNotificationIdAndOnClick(),
      ...config,
    });
  },
  open: (config: TConfig) => {
    notification.open({
      ...createNotificationIdAndOnClick(),
      ...config,
    });
  },
  close: (key: string) => {
    notification.close(key);
  },
};

export default basicNotification;
```

**Comment by zystudios** [comment]
> 这个问题现在还没有解决方案吗

自己覆盖一下message的class就可以了

pointer-events: none !important;
