### ISSUE TITLE
Styling is messed up when using disabled Button inside Tooltip

### ISSUE THREAD

**Issue by Mohamed-Ghanem** [ant-design/ant-design#17449]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-cgeyn)

### Steps to reproduce
Look at the sandbox

### What is expected?
Buttons should be rendered with equal width inside the div

### What is actually happening?
The button with disabled property gets wrong width

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.9 |
| System | macOS mojave 10.14.5 |
| Browser | chrome 74.0.3729.169 |

---
This only happens when a button with disabled property set to true and is child of tooltip

**Comment by afc163** [comment]
<img width="521" alt="图片" src="https://user-images.githubusercontent.com/507615/60607125-3eed6280-9def-11e9-9fcc-86d8579b81a8.png">

**Comment by Mohamed-Ghanem** [comment]
@afc163 updated the link. is it working?

**Comment by schester44** [comment]
It's happening because the disabled button is wrapped in a `span` element which cancels the `flex:1` css property.

**Comment by Mohamed-Ghanem** [comment]
@schester44 Yes I know that there is a span inserted there, my questions to be more clearer:

1. Why is the button wrapped in span?
2. Why is it when the span gets the same css styles {display: flex, flex: 1} it still does not fill the space entirely?
3. Why css class or html attribute are not used in disabling behavior instead of html tag?
4. Why when I remove the tooltip tag the button renders normally without span?
5. Why cant I control the span nor add a class to it so i can use it?

Ultimately I want to know if this is a bug or not, if its a bug will it be fixed or not, if not how to do a workaround

**Comment by schester44** [comment]
Sorry, I was pointing out, to the maintainers, what the root cause was. 

To make the button flex inside the span, you need to flex:1 the span then set the button width to 100%. 

Being that you don’t have control over that from the surface of the component, id say this is a bug.

**Comment by afc163** [comment]
> Why is the button wrapped in span?

https://github.com/ant-design/ant-design/pull/4865

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-hsh0o

**Comment by Mohamed-Ghanem** [comment]
@afc163 Thank you the block attribute fixed the disabled button width inside tooltip issue. Is it somewhere in the documentation?

I have found another issue, if loading=true the width of the button is bigger than it should be. I updated the codesandbox to show some variations with diff attributes.

**Comment by areyouse7en** [comment]
@afc163  为什么disabled的时候要给Button外面加一层span？这样导致原来写在button上的classnames跑到span上了

**Comment by afc163** [comment]
#4865

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21404#issuecomment-586800984
