### ISSUE TITLE
treeSelect能不能提供官方异步加载的例子啊？  另外之前尝试使用tree组件的异步加载的方式在treeSelect上面，结果出现各种奇怪问题。

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design#17453]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/#header](https://ant.design/components/tree-select-cn/#header)

### Steps to reproduce
官方暂无案例

### What is expected?
期望提供官方treeSelect异步加载案例

### What is actually happening?
现在暂无

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8 |
| System | win10 |
| Browser | chorm |

**Comment by afc163** [comment]
欢迎社区贡献。
