### ISSUE TITLE
Change event on ant input doesn't update input value

### ISSUE THREAD

**Issue by amitpatil321** [ant-design/ant-design#17451]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rklir)

### Steps to reproduce
I have written 2 ways to change and text input but both test fails.

### What is expected?
Input should have new value set using enzyme 

### What is actually happening?
It doesn't change input value

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16 |
| System | Windows |
| Browser | Chrome 73.0 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#I-set-the-value-of-Input/Select(etc...),-and-then,-it-cannot-be-changed-by-user's-action.

**Comment by amitpatil321** [comment]
So what I doing (trying to update input value with enzyme) won't work because it's a controlled component, So the only valid (correct) way to do it is to pass a value to the component as props only?

**Comment by afc163** [comment]
You have to use `setState` or `setProps` in enzyme.

**Comment by afc163** [comment]
TBH, it is actually not a antd issue.

**Comment by amitpatil321** [comment]
Okay thanks!
