### ISSUE TITLE
Ant design Form do not update input value after document.getElementById().value call.

### ISSUE THREAD

**Issue by brenotx** [ant-design/ant-design#17450]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/wonderful-lalande-prcfn)

### Steps to reproduce
1 - Try to set an input value using the ```.value = 'Jack';``` notation inside your ```react-testing-library``` file. 

2 - Try to check the input value inside the ```validateFields()``` function.

### What is expected?
Expected to see the value provided by the ```getByLabelText(/username/i).value``` inside the ```validateFields()``` function.

### What is actually happening?
Using the react-testing-library and ant.design form. When you try to set the input value using ```getByLabelText(/username/i).value = 'Jack';``` or
    ```document.getElementById().value = 'Jack'``` you will always get a error inside ```this.props.form.validateFields((err, values) => {}) function.```

#### component
```
handleSubmit = e => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
       // We will never get here because the values will be always empty
        this.props.onCreateCategorySubmit(values.name, values.description);
      }
    });
  };
```

#### Test file
```
it('name input should update its value', () => {
    const handleSubmit = jest.fn();
    const { getByLabelText, } = render(
        <Add onCreateCategorySubmit={handleSubmit} />
    );

    getByLabelText(/name/i).value = 'Jack';
    // document.getElementById('add_category_name').value = 'jack';
    fireEvent.submit(getByTestId('form'));

    expect(handleSubmit).toHaveBeenCalledTimes(1);
  });
```

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | OSX 0.14.3 |
| Browser | Chrome 75.0.3770.100 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#I-set-the-value-of-Input/Select(etc...),-and-then,-it-cannot-be-changed-by-user's-action.

**Comment by brenotx** [comment]
Thank you @afc163. Is there another way to change the input value inside the test file and test the **onCreateCategorySubmit** function call?

**Comment by evanzombie** [comment]
@brenotx Have you found a solution for this kind of testing with Form? I'm having the same problem.

**Comment by brenotx** [comment]
@evanzombie I'm using change event to modify the value and test it. Eg.:

```
it('blank Title input should render error message', () => {
    const { getByLabelText, getByText } = render(<Add />);
    const searchPageTitleNode = getByLabelText('Title');

    fireEvent.change(searchPageTitleNode, {
      target: { value: 'a' },
    });

    fireEvent.change(searchPageTitleNode, {
      target: { value: '' },
    });

    const searchPageTitleErrMsgNode = getByText(
      /Please input search page title!/i,
    );
    expect(searchPageTitleErrMsgNode).toBeDefined();
  });
```

**Comment by yoyo837** [comment]
Isn't this an inadequate understanding of react?
