### ISSUE TITLE
Table中使用Paragraph ellipsis，导致Table浮动列计算高度不正确。

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#17454]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-guic7)

### Steps to reproduce
在首次加载完毕后，浮动列的高度计算不正确。

### What is expected?
希望在首次加载完毕后，浮动列的高度展示正确。

### What is actually happening?
在首次加载完毕后，浮动列的高度计算不正确。

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.7.0 |
| System | win10 |
| Browser | chrome 75.0.3770.100 |

**Comment by zombieJ** [comment]
ref: https://github.com/react-component/table/pull/283
