### ISSUE TITLE
Resizable 实现可伸缩列的表格 当对列宽进行拖拽时移动到表格数据行数据会消失

### ISSUE THREAD

**Issue by liuguangsen0409** [ant-design/ant-design#17455]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-resizable-column](https://ant.design/components/table-cn/#components-table-demo-resizable-column)

### Steps to reproduce
修改可伸缩的列宽，当鼠标移动到表格主体数据行内的时候，发现数据行里面的内容会消失
![image](https://user-images.githubusercontent.com/22491714/60637259-53ac1380-9e4c-11e9-9e0f-d0d837eff3e2.png)

### What is expected?
当鼠标移动到表格主体数据行内的时候，数据行内容不消失

### What is actually happening?
数据行里面的内容会消失

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8 |
| System | mac |
| Browser | chrome 75.0 |

**Comment by afc163** [comment]
把这个去掉就行了：https://github.com/ant-design/ant-design/pull/17198/files

**Comment by liuguangsen0409** [comment]
> 把这个去掉就行了：https://github.com/ant-design/ant-design/pull/17198/files

大佬 我在 官网 试了下 感觉 还是不可以呀 

![image](https://user-images.githubusercontent.com/22491714/60637777-527be600-9e4e-11e9-97f7-2d47491edf0c.png)

**Comment by loma18** [comment]
强制设置一下行的背景底色就可以，拖拽时table中的body上有一个className:react-draggable-transparent-selection,导致其下被拖选中的文字颜色为白色，背景变透明了。所以从哪列拖，拖到哪行，从那行开始颜色就变白色了，再拖下去，没有hover颜色的加持，就变透明，然后就看不到了

**Comment by loma18** [comment]
![image](https://user-images.githubusercontent.com/30955346/60643252-04261180-9e65-11e9-899b-8be8ac12ce7c.png)

**Comment by loma18** [comment]
![image](https://user-images.githubusercontent.com/30955346/60643568-0a68bd80-9e66-11e9-99d6-518d9faeeb02.png)
哈哈，暂时解决办法

**Comment by afc163** [comment]
可以给 demo 里的样式来个 PR。

**Comment by liuguangsen0409** [comment]
我看了下 .react-draggable-transparent-selection *::-moz-selection {background: transparent;}
.react-draggable-transparent-selection *::selection {background: transparent;}  这个其实是 选中文字的 background，把这个 改成 #4990FF 就好一些了
![image](https://user-images.githubusercontent.com/22491714/60643795-cde99180-9e66-11e9-8ab2-c386471f64c6.png)
我不知道 怎么 提 PR 尴尬

**Comment by loma18** [comment]
![Uploading image.png…]()

**Comment by loma18** [comment]
![image](https://user-images.githubusercontent.com/30955346/60644803-b9f35f00-9e69-11e9-9c5e-aabcefc117a6.png)

**Comment by loma18** [comment]
看贡献指南

**Comment by liuguangsen0409** [comment]
怎么还要写测试用例 不知道 怎么写 大佬看到了 记得改下 就好 也不是 什么大问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/18c05189cfe940921f8beee8f29061215a320e2d
