### ISSUE TITLE
Menu 内嵌 null 时报错

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1746]
用于动态表单。

https://gitter.im/ant-design/ant-design?at=5739a72bc61823687d3c3bcc

```jsx
let otherMenu =   false ? <Menu.Item key="2"><Icon type="book" />其他其他</Menu.Item> : null;
                <Menu mode="inline"  theme="light">
                    <Menu.Item key="sub0"><Icon type="home" />首页</Menu.Item>
                    <Menu.Item key="1"><Icon type="book" />其他</Menu.Item>
                    {otherMenu}
                </Menu>
```

**Comment by afc163** [comment]
codepen: http://codepen.io/anon/pen/ZWNmqJ?editors=001

**Comment by yesmeck** [comment]
Row 也是这样，Select [也是](https://github.com/react-component/select/issues/63)，不知道你们是怎么看这个问题的？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/c9e8423c7ebe6da4a84c0f13d5f8b07e5624a5e3/components/layout/row.jsx#L31

Row 应该是有处理的。

**Comment by yiminghe** [comment]
这是种约定，就像 select 下不能有 text，这种需求用动态数组解决

**Comment by yesmeck** [comment]
> 这是种约定，就像 select 下不能有 text，这种需求用动态数组解决

可以加个警告吧，就像直接在`table`下写`tr` React 会有警告。

**Comment by yesmeck** [comment]
奥，我碰到的 Row 的问题是我们自己的代码有问题。
