### ISSUE TITLE
Could TreeSelect support set the parent node to single-select, but the child node to multiple?

### ISSUE THREAD

**Issue by YuFF2018** [ant-design/ant-design#17470]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For example, there is a two-level treeData ，I need to set the first level node is single-selected, and the second level node is multi-selected.
When I selected a node (or some nodes) below parent node1, nodes below other parent node are not allowed to be seleted, only nodes below parent node1 can be selected.

### What does the proposed API look like?
I am sorry I don't know how to achieve this till this moment.

**Comment by zombieJ** [comment]
Use `treeCheckStrictly` to make node check Independent. And use `onChange` to customize your logic to control the `value`.
