### ISSUE TITLE
AutoComplete 组件受控模式，feature or bug ?

### ISSUE THREAD

**Issue by laonon** [ant-design/ant-design#17476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/billowing-frost-cpbwf)

### Steps to reproduce
输入 id 为 1 时命中 dataSource 中某项，且dataSource仅有 1 项时，输入框会自动填充

### What is expected?
阻止自动填充

### What is actually happening?
自动填充

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | react |
| System | macOS Majave 10.14.5 |
| Browser | 版本 75.0.3770.100（正式版本） （64 位） |

**Comment by afc163** [comment]
不是 bug，key 和 value 匹配就会自动填入 `children` 的值。

**Comment by laonon** [comment]
> 不是 bug，key 和 value 匹配就会自动填入 `children` 的值。

请问下，可以设置吗？我需要的场景不希望自动填入

**Comment by zombieJ** [comment]
但是受控状态会额外多一个 1 出来：
![Kapture 2019-07-05 at 11 15 19](https://user-images.githubusercontent.com/5378891/60695928-3479b880-9f16-11e9-9d89-d706de166f42.gif)

**Comment by afc163** [comment]
> 请问下，可以设置吗？我需要的场景不希望自动填入

`key` `value` 和 children 的值保持一致就行。

**Comment by laonon** [comment]
> 但是受控状态会额外多一个 1 出来：
> ![Kapture 2019-07-05 at 11 15 19](https://user-images.githubusercontent.com/5378891/60695928-3479b880-9f16-11e9-9d89-d706de166f42.gif)

这个不是受控组件的问题，是我 demo 里额外设置了 text

**Comment by zombieJ** [comment]
@laonon ,谢谢提醒。那的确不是 BUG。是预期的。

**Comment by laonon** [comment]
> > 请问下，可以设置吗？我需要的场景不希望自动填入
> 
> `key` `value` 和 children 的值保持一致就行。

不好意思，打扰下，就当前这个例子的场景是不是没法阻止自动填入

**Comment by afc163** [comment]
是的，自动完成场景，key value 和 children 的值应该保持一致。
