### ISSUE TITLE
当在 DatePicker 中使用 TimePicker 的时间选择能力时，23 时的 focus 样式依然存在问题

### ISSUE THREAD

**Issue by xiabaiyang** [ant-design/ant-design#17483]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
先选日期，再选时间，定位到 23 时，focus 样式问题依然存在

### What is expected?
选中 23 时，数字左下方不出现竖线

### What is actually happening?
选中 23 时，数字左下方出现异常竖线

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | mac 10.14.4 |
| Browser | chrome 75.0.3770.100 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/17447, will released in this weekend.
