### ISSUE TITLE
A lot of repeating helper functions

### ISSUE THREAD

**Issue by SweetsXob** [ant-design/ant-design#17488]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

#### 2个文件的头部，都有好几个helpers函数，比如：
```javascript
function _extends() { ... }
function _defineProperties(target, props) { ... }
...等等
``` 
#### 希望把helpers函数，都提取出来，让用户自己处理，比如：
```javascript
import _defineProperty from '@babel/runtime/helpers/esm/defineProperty'
```

**Comment by ztplz** [comment]
你看编译后的代码干什么。。。
编译符合ES6模块规范的代码放在es这个文件夹里

**Comment by SweetsXob** [comment]
> 你看编译后的代码干什么。。。
> 编译符合ES6模块规范的代码放在es这个文件夹里

因为最后你的打包文件里，会有一堆重复的代码
类似这样的代码_defineProperty，会出现很多很多次

**Comment by ztplz** [comment]
babel默认就是这样啊 。。。会给很多编译后的代码加很多模板函数 让这些函数只在当前模块内生效
可以用`external-helpers`减少模板编译代码  但是没必要的

**Comment by SweetsXob** [comment]
> babel默认就是这样啊 。。。会给很多编译后的代码加很多模板函数 让这些函数只在当前模块内生效
> 可以用`external-helpers`减少模板编译代码 但是没必要的

有必要呢，每个组件里，都会有一些公共的helper函数（压缩后大概2k左右），而且是重复的
提取出来，让webpack去处理，将这些helper放到一个统一的地方，能大大减少冗余呀
这样打出来的包，目测又能少个100K左右

现在Icon全量引入，导致包过大的问题，还没有解决。从这些地方省一些，应该说的过去吧

**Comment by ztplz** [comment]
就几个工具函数哪来的2k。。。

**Comment by SweetsXob** [comment]
#### 我随便挑选几个文件，看看使用了哪些工具函数，看看有没有2k

#### antd\es\input 这个文件夹下
input.js
![input](https://user-images.githubusercontent.com/9486141/60765058-97aa4d00-a0c6-11e9-8a34-2f70fff49fa3.jpg)

#### antd\es\checkbox 这个文件夹下
checkbox.js
![checkbox](https://user-images.githubusercontent.com/9486141/60765138-dbea1d00-a0c7-11e9-853f-e450a085ad06.jpg)

group.js
![checkbox-group](https://user-images.githubusercontent.com/9486141/60765139-dbea1d00-a0c7-11e9-90da-be42053c80d8.jpg)

## 以上每个文件，红框里的帮助函数，都超过了2k

#### 在看看打包后，文件的情况
![chrome-2](https://user-images.githubusercontent.com/9486141/60765131-bc52f480-a0c7-11e9-9036-a5df095419c2.jpg)
![chrome-1](https://user-images.githubusercontent.com/9486141/60765132-bceb8b00-a0c7-11e9-9c32-8e737c36e6b5.jpg)

#### 我使用 function _inherits 关键字，搜索了一下，出现了以上30多个搜索结果（使用其他工具函数名搜索，结果差不多）
#### 我这项目暂时只有5个页面（持续开发中）。用到的组件，还不是很多，工具函数就如此冗余了。希望能帮忙解决一下，谢谢

**Comment by SweetsXob** [comment]
@ztplz @chenshuai2144 
请问这个问题，可以帮忙解决一下嘛？
