### ISSUE TITLE
设计资源 下载

### ISSUE THREAD

**Issue by Complexf** [ant-design/ant-design#17482]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/spec/download-cn](https://ant.design/docs/spec/download-cn)

### Steps to reproduce
无法下载，报错

### What is expected?
提供下载

### What is actually happening?
提供下载

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 1 |
| System | win10 |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
能具体说说是哪个链接吗？

**Comment by afc163** [comment]
翻墙。
