### ISSUE TITLE
DatePicker日期选择框，开始时间会大于结束时间。

### ISSUE THREAD

**Issue by shyshyshyshy** [ant-design/ant-design#17490]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
1、找个日期选择器可以选择开始日期和结束日期
2、当点击开始日期和结束日期都是相同的日期后
3、在日期选择器里手动修改开始日期（大于结束日期）
4、会造成开始日期大于结束日期

### What is expected?
修复手动修改后开始日期大于结束日期的情况

### What is actually happening?
手动修改后开始日期小于结束日期

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | v16.6.3 |
| System | mac |
| Browser | Chrome  V75 |

---
用户选择日期区间的时候，可能会手动修改日期，会造成开始日期大于结束日期

**Comment by afc163** [comment]
Duplicate of #17135

**Comment by shyshyshyshy** [comment]
![image](https://user-images.githubusercontent.com/29090296/60715455-a0c4de00-9f4f-11e9-998b-e0a5e01228c0.png)
