### ISSUE TITLE
Modal在使用updater函数的形式切换visible时出错

### ISSUE THREAD

**Issue by Tan90Qian** [ant-design/ant-design#17491]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bug-antd-modal-1-zc4zz)

### Steps to reproduce
1. 点击Button按钮弹出Modal
2. 双击灰色遮罩处，在Modal关闭前使其重新弹出
3. 第三次点击遮罩处，关闭Modal

### What is expected?
Modal关闭后，屏幕能够正常滚动（设置body为200vh）

### What is actually happening?
屏幕无法滚动

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | macOS 10.12.6  |
| Browser | chrome 75.0.3770.100（正式版本） （64 位） |

---
根据DOM元素的class为ant-modal-mask-hidden可以看出 弹层确实被认为是关闭了

**Comment by jljsj33** [comment]
fix #17600
