### ISSUE TITLE
Warning: There must be `tab` property on children of Tabs.

### ISSUE THREAD

**Issue by drcmda** [ant-design/ant-design#17492]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Tabs are not dynamic, because they use cloning and injection. This in turn breaks composition and makes working with dynamic/connected components harder. 

### What is expected?
Antd should consider use context.

### What is actually happening?
```jsx
function Header() {
  const drawings = useStore(store => store.drawing_ids)
  // Tabs expects children to have the "tab" property, it doesn't exist at this level
  // nor is a name known at this point, because components are connected via ID
  return (
    <Tabs>
      {drawings.map(id => <Tab key={id} id={id} />)}


function Tab({ id }) {
  // This is where we get the actual "tab" name from the store ...
  // This component is bound to a store, it reacts to changes to its data-model
  const name = useStore(store => store.drawings[id])
  return <Tabs.TabPane tab={name} />
}
```

The above code will yield:

    Warning: There must be `tab` property on children of Tabs.

And of course it doesn't work.

I know i could use

```jsx
<Tabs.TabPane key={id} tab={<TabContent id={id} />} />
```

But it's a general problem we bump into all the time. 

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | MacOS |
| Browser | Chrome |

**Comment by drcmda** [comment]
I faced similar issues here: https://github.com/ant-design/ant-design/issues/4688

And here: https://github.com/ant-design/ant-design/issues/7846

Please consider using context. You make it very hard for us to use antd in dynamic situations. Components are always connected, you rarely build an entire header/table/menu from scratch on every store change.

This problem has led to us writing our own self made trees, menus and tabs in the past, just to be able to connect components properly. It is no good. 😓

**Comment by drcmda** [comment]
here's one: https://codesandbox.io/s/reverent-cache-yy8dy

**Comment by afc163** [comment]
You can only try this way now: https://codesandbox.io/s/distracted-wescoff-5yb3m

More info you can trace https://github.com/ant-design/ant-design/issues/4853
