### ISSUE TITLE
Custom selection render for the select component using Typescript

### ISSUE THREAD

**Issue by sagar7993** [ant-design/ant-design#17493]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am trying to create a custom selection render for the select component, as per the docs provided at this link - https://ant.design/components/select/#components-select-demo-option-label-prop

Here it says that I can pass a prop called optionLabelProp and give it any value which will be used as a prop on the `Select.Option` component. When i pass `optionLabelProp="label"` to `Select` component, I expect to be able to pass a prop called `label` to `Select.Option` but this will not work in `Typescript`, because the type definitions of the `Select. Option` component doesn't have any prop called `label`.

Am I doing something wrong here? How do I make this work in `Typescript`?

### What does the proposed API look like?
This can be solved by providing a fixed prop such as `label` on the `Select.Option` component which should be used for the custom select rendering

**Comment by afc163** [comment]
<img width="1008" alt="图片" src="https://user-images.githubusercontent.com/507615/60752957-e7bddc80-9ffe-11e9-9cd7-723d850e2919.png">

https://codesandbox.io/s/vibrant-grass-yrj8i
