### ISSUE TITLE
建议Table组件使用div改写一下吧,坑太多了,table天生不支持布局

### ISSUE THREAD

**Issue by miaozilong** [ant-design/ant-design#17495]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/throbbing-hooks-wqoi4)

### Steps to reproduce
打开链接即可

### What is expected?
建议Table组件使用div布局改写

### What is actually happening?
布局错乱

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 所有 |
| System | 所有 |
| Browser | 所有 |

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/pull/17284
