### ISSUE TITLE
Antd form skips values those are not mapped with UI components

### ISSUE THREAD

**Issue by nikhil-mahirrao** [ant-design/ant-design#17507]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wild-cloud-gmyzk)

### Steps to reproduce
1. Open link
2. Click on submit button
3. Check console logs

### What is expected?
On submit form data should return this object without missing any values
{ person: { name: "Nikhil", email: "nikhil.mahirrao@gmail.com", age: 31 }, mobile: 9812123223 }

### What is actually happening?
On submit form data removes age field from the object
{ person: { name: "Nikhil", email: "nikhil.mahirrao@gmail.com" }, mobile: 9812123223 }

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.9.0 |
| System | Mac on Google Chrome |
| Browser | Version 75.0.3770.100  |

---
If we are giving object to form it should return as it is without manipulating it. but in this case antd form removing values those are not mapped with any UI components

**Comment by afc163** [comment]
It is intented behavior.

**Comment by nikhil-mahirrao** [comment]
But then how can we get complete object at the end?

**Comment by afc163** [comment]
The state not contained in fields should be stored as plain variables or managed by state and setState.
