### ISSUE TITLE
Tab组件想隐藏添加按钮无法实现

### ISSUE THREAD

**Issue by xiamidaxia** [ant-design/ant-design#1750]
如题，场景如下：
![image](https://cloud.githubusercontent.com/assets/4162271/15354849/21cb07ee-1d22-11e6-9290-09edebd40575.png)

但目前没有该配置项：
![image](https://cloud.githubusercontent.com/assets/4162271/15354857/2e44e986-1d22-11e6-8f65-8b5c42961dbe.png)

**Comment by superRaytin** [comment]
@yiminghe 是否能增加一个配置？

**Comment by yiminghe** [comment]
加吧
