### ISSUE TITLE
DatePicker dropdown collapsing when component embedded inside Select Options

### ISSUE THREAD

**Issue by yrameshra0** [ant-design/ant-design#17516]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1qxrb)

### Steps to reproduce
In the sandbox link created above.
1. Expand the Selection dropdown
2. Click on the DatePicker
3. Issue happens where DatePicker expansion collapses

### What is expected?
The expected is DatePicker dropdown should not collapse when component embedded inside Select Options. The component was behaving correctly in v3.15.0.

### What is actually happening?
When trying to use `DatePicker` that's embedded inside `Select` components' `Option` the picker opens and shuts without actually giving any way for us to select an particular date.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.6 |
| System | Mac Mojave - 10.14.6 |
| Browser | Chrome 75.0.3770.100 |

---
As the `DatePicker` component was working as expected with `v3.15.0` and started displaying the collapsing behaviour only in `v3.20.0`  `

**Comment by dengfuping** [comment]
- Wrong link, need reproducible demo.

**Comment by yrameshra0** [comment]
Sorry My I behaved like ☝️
Not the link as updated code base which can reproduce the the issue. Alternatively the issue can also be seen using this [repository](https://github.com/yrameshra0/antd-datepicker-issue) also.

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-disappear-when-I-click-another-popup-component-inside-it,-How-to-resolve-it?

**Comment by afc163** [comment]
You are using Select in a strange way, I don't think we can provide support for it.

Maybe you should try https://ant.design/components/dropdown-cn/ than Select.

**Comment by yrameshra0** [comment]
Thanks for taking look at it and providing a quick turn-around.
