### ISSUE TITLE
createRef或者useRef可以取得form，为什么控制台会抛出警告呢？

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#17519]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-zyxfv)

### Steps to reproduce
https://codesandbox.io/s/antd-reproduction-template-zyxfv

### What is expected?
无警告

### What is actually happening?
有警告

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8  |
| System | win |
| Browser | chrome |

---
wrapperComponentRef跟createRef有何区别？

**Comment by yoyo837** [comment]
修复下你的reporoduce 
`props.form.getFieldDecorator('id')`

**Comment by zombieJ** [comment]
因为通过 `ref` 拿到的是 node instance 而不是 form instance。这里做了 polyfill 特地提供了相同的 api，但是不推荐用户这么用。这个 warning 是故意的：
https://github.com/react-component/form/blob/master/src/createBaseForm.js#L57
