### ISSUE TITLE
https://codesandbox.io/s/73vkjrkjkq

### ISSUE THREAD

**Issue by LENZAKON** [ant-design/ant-design#17515]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/73vkjrkjkq)

### Steps to reproduce
1. open the Select
2. hover on an Option and Tooltip appear
3. hover on Tooltip
4. long press and move the mouse
5. the word in the Tooltip can not be selected

### What is expected?
the word in the Tooltip can be selected

### What is actually happening?
the word in the Tooltip can not be selected

| Environment | Info |
|---|---|
| antd | 3.13.2 |
| React | 16.8.2 |
| System | macOS 10.14.5 (18F132) |
| Browser | Google Chrome 75.0.3770.100（正式版本） （64 位） |

**Comment by LENZAKON** [comment]
![image](https://user-images.githubusercontent.com/23180703/60782364-f3351300-a178-11e9-9532-3bcb0aca7181.png)

**Comment by afc163** [comment]
Sorry, `antd` is not optimized for mobile environment.

**Comment by LENZAKON** [comment]
> Sorry, `antd` is not optimized for mobile environment.

no, is in the desktop browser

**Comment by afc163** [comment]
It is been prevented in rc-select: https://github.com/react-component/select/blame/0596f8d9be0656d1c61aee95361188f99ad7be85/src/DropdownMenu.jsx#L129

I don't know why we prevent in first place, you can try this as workaround: https://codesandbox.io/s/great-morse-siml4

**Comment by LENZAKON** [comment]
> It is been prevented in rc-select: https://github.com/react-component/select/blame/0596f8d9be0656d1c61aee95361188f99ad7be85/src/DropdownMenu.jsx#L129
> 
> I don't know why we prevent in first place, you can try this as workaround: https://codesandbox.io/s/great-morse-siml4

ok，thanks a lot!
