### ISSUE TITLE
Remove pagination prev, current page, and next buttons when we have only one page of items, but left size changer visible

### ISSUE THREAD

**Issue by 1998MaxChykalo** [ant-design/ant-design#17524]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Seems that prev, next and currentPage buttons are useless when we have only a single page of items.
If I am wrong about that, please describe why leaving them on the page is better than hiding from the UX point of view.

### What does the proposed API look like?
Remove pagination next, prev, and current page buttons when we are on a single page.

**Comment by 1998MaxChykalo** [comment]
@zombieJ Hey! Are you going to close this issue or you have plans to do it?

**Comment by zombieJ** [comment]
Pure SizeChanger is not look likes a Pagination and confuse user what's the function of the Changer. It's not a good design. You can wrap a customize component if really need this.
