### ISSUE TITLE
comment 增加HTML格式内容的支持

### ISSUE THREAD

**Issue by qteamcheng** [ant-design/ant-design#17520]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
评论组件一般会有表情，图片等内容。当前的评论组件只支持纯文本

### What does the proposed API look like?
评论组件的内容（content）可以是内嵌HTML 片段

**Comment by afc163** [comment]
https://zh-hans.reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml

**Comment by qteamcheng** [comment]
谢谢！
