### ISSUE TITLE
table树形结构展示时，自定义展开图标后，子级tr无缩进，设置indentSize也无效

### ISSUE THREAD

**Issue by zhangshuai0101** [ant-design/ant-design#17523]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当自定义展开图标后，希望展开后的内容格式和未替换时一致

### What does the proposed API look like?
基于现有api

**Comment by zhangshuai0101** [comment]
展开前
![image](https://user-images.githubusercontent.com/40013310/60792309-0acfc400-a198-11e9-9171-316917a1b637.png)
展开后
![image](https://user-images.githubusercontent.com/40013310/60792326-14592c00-a198-11e9-996a-04424be35fee.png)
代码如下：
![image](https://user-images.githubusercontent.com/40013310/60792352-20dd8480-a198-11e9-9b88-d42f83b8e533.png)
![image](https://user-images.githubusercontent.com/40013310/60792383-32269100-a198-11e9-9628-51b8f74724ed.png)

**Comment by zhangshuai0101** [comment]
这是未自定义图标的
![image](https://user-images.githubusercontent.com/40013310/60792632-9fd2bd00-a198-11e9-97b7-de9e1c842461.png)

**Comment by zhangshuai0101** [comment]
> Hello @zhangshuai0101. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @zhangshuai0101, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

实例：https://codesandbox.io/s/antd-reproduction-template-ljo5b?fontsize=14 @afc163 多谢，帮忙看下原因

**Comment by afc163** [comment]
比想象中的难修很多，先这样解决吧：https://codesandbox.io/s/antd-reproduction-template-ljo5b?fontsize=14

**Comment by zhangshuai0101** [comment]
> 比想象中的难修很多，先这样解决吧：https://codesandbox.io/s/antd-reproduction-template-ljo5b?fontsize=14

没有看到您解决的方案 请问这个问题会修复吗？@afc163

**Comment by afc163** [comment]
没保存成功。。

看这个：https://codesandbox.io/s/antd-reproduction-template-os2to
