### ISSUE TITLE
能否设置默认字体和控件%大小?

### ISSUE THREAD

**Issue by roytan883** [ant-design/ant-design#1752]
ant design的控件感觉都不错，但是做完以后最大的问题就是整个页面看着累。
主要原因是控件和字体默认都特别特别小。
如果官方认为这种大小当前是最好的。
那么能不能给用户以选择，提供一个简单全局设置，比如设置150%，让控件和字体默认都变大一些？

**Comment by afc163** [comment]
目前是按照设计规范来的，如果有需要调大，可以自行覆盖样式。

另外我们有一个 less 变量 `@font-size-base`，你可以试试，但是可能没有覆盖全。

**Comment by huangyingjie** [comment]
同感，很多用户反馈字体太小。最好给body设置一个fontsize，然后子元素去继承或覆盖，而不是fontsize到处都是，覆盖起来很累。

**Comment by ThinkMe** [comment]
字体真的很小，眼睛真的不行啊，大哥。

**Comment by xd19831203** [comment]
我刚学着用ANT，平时不混GIT所以懂的不多，但在修改ANT的LESS里的样式时发现，很多控件根本没引用LESS里定义的基础字号，而且直接用如'12px'这样的方式定义了字体，所以要真想改改一下ANT的皮肤样式，是个非常疼苦的问题，不知道官方有什么好的解决方案

**Comment by afc163** [comment]
直接给我们 PR ~

**Comment by TangMonk** [comment]
真的很小。。

**Comment by benjycui** [comment]
@TangMonk 自定义 theme https://ant.design/docs/react/customize-theme-cn
