### ISSUE TITLE
checkbox组件的全选属性还有样式控制属性，受控模式下手动setState更改无效

### ISSUE THREAD

**Issue by dongyang19931108** [ant-design/ant-design#17528]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-kowalevski-q3b44)

### Steps to reproduce
点击页面上方的checkall而不通过勾选checkbox,只能正确设置勾选项，全选样式并没有发生变化。

### What is expected?
可以通过其他方式设置全选效果，勾选项，而不是只能通过触发checkbox的onchange方式更改

### What is actually happening?
实际只能设置选中项，全选样式不能改变

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.6.0 |
| System | win10 X64 |
| Browser | 最新版的chrome |

---
根据接口返回的数据或者根据特定条件，设置checkbox的全选半选效果

**Comment by afc163** [comment]
> 全选样式并没有发生变化

看不太懂，你的例子看上去没啥问题。

**Comment by dongyang19931108** [comment]
> > 全选样式并没有发生变化
> 
> 看不太懂，你的例子看上去没啥问题。

我希望可以通过点击div设置checkbox的全选，实际上只能设置选中项，Check all这个多选框的效果并不正确，我看了源码后发现只有把indeterminate设置为null才能实现Check all的全选样式

**Comment by dongyang19931108** [comment]
> > 全选样式并没有发生变化
> 
> 看不太懂，你的例子看上去没啥问题。

https://codesandbox.io/s/focused-kowalevski-q3b44 我把div换成button了，您可以点了试试

**Comment by afc163** [comment]
> https://codesandbox.io/s/focused-kowalevski-q3b44 我把div换成button了，您可以点了试试

没什么区别。

你期待的样式是什么？预期的结果是什么？两者有什么区别？

**Comment by dongyang19931108** [comment]
> > https://codesandbox.io/s/focused-kowalevski-q3b44 我把div换成button了，您可以点了试试
> 
> 没什么区别。
> 
> 你期待的样式是什么？实际的结果是什么？两者有什么区别？

我期待的样式是Check all这个多选框是全选的效果，而不是半选的效果，实际是半选的样式

**Comment by dongyang19931108** [comment]
> > > https://codesandbox.io/s/focused-kowalevski-q3b44 我把div换成button了，您可以点了试试
> > 
> > 
> > 没什么区别。
> > 你期待的样式是什么？实际的结果是什么？两者有什么区别？
> 
> 我期待的样式是Check all这个多选框是全选的效果，而不是半选的效果，实际是半选的样式

![Uploading TIM图片20190708185617.
![Uploading TIM图片20190708185628.png…]()
png…]()

**Comment by afc163** [comment]
`indeterminate` 表示半选状态，你例子里设置成 `true` 了，自然就是半选样式。

**Comment by dongyang19931108** [comment]
我以为的效果是indeterminate和checkall同时为true表示全选，indeterminate为true，checkall为false表示半选，二者均为false表示未选中

**Comment by afc163** [comment]
> 我以为的效果是indeterminate和checkall同时为true表示全选，indeterminate为true，checkall为false表示半选，二者均为false表示未选中

误解了，按上面的例子来就行了。
