### ISSUE TITLE
how to use React.createElement(Button , { } ) 

### ISSUE THREAD

**Issue by yupeilin123** [ant-design/ant-design#17532]
### Steps to reproduce

```javascript 
import * React from 'react';
import {Button} from 'antd';

React.create(Button,{
 type: 'primary',
 chidlren: 'button'
})
```

### What is expected?
code can run

### What is actually happening?
Argument of type 'typeof Button' is not assignable to parameter of type 'string | ComponentClass<Partial<{ href: string; target?: string | undefined; onClick?: ((event: MouseEvent<HTMLElement, MouseEvent>) => void) | undefined; } & BaseButtonProps & Pick<AnchorHTMLAttributes<any>, "style" | ... 257 more ... | "onTransitionEndCapture"> & { ...; } & Pick<...>>, any> | FunctionComponent<...>'.
  Type 'typeof Button' is not assignable to type 'ComponentClass<Partial<{ href: string; target?: string | undefined; onClick?: ((event: MouseEvent<HTMLElement, MouseEvent>) => void) | undefined; } & BaseButtonProps & Pick<AnchorHTMLAttributes<any>, "style" | ... 257 more ... | "onTransitionEndCapture"> & { ...; } & Pick<...>>, any>'.
    Types of property 'propTypes' are incompatible.
      Type '{ type: Requireable<string>; shape: Requireable<"circle" | "round" | "circle-outline">; size: Requireable<"small" | "default" | "large">; htmlType: Requireable<"button" | "submit" | "reset">; ... 4 more ...; block: Requireable<...>; }' is not assignable to type 'WeakValidationMap<Partial<{ href: string; target?: string | undefined; onClick?: ((event: MouseEvent<HTMLElement, MouseEvent>) => void) | undefined; } & BaseButtonProps & Pick<AnchorHTMLAttributes<any>, "style" | ... 257 more ... | "onTransitionEndCapture"> & { ...; } & Pick<...>>>'.
        Types of property 'type' are incompatible.
          Type 'Requireable<string>' is not assignable to type 'Validator<"link" | "primary" | "ghost" | "default" | "dashed" | "danger" | null | undefined>'.
            Types of property '[nominalTypeHack]' are incompatible.
              Type 'string | null | undefined' is not assignable to type '"link" | "primary" | "ghost" | "default" | "dashed" | "danger" | null | undefined'.
                Type 'string' is not assignable to type '"link" | "primary" | "ghost" | "default" | "dashed" | "danger" | null | undefined'.  TS2345

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.6 |
| System | macos majave 10.14.5  |
| Browser | google chorme 75.0.3770.100 |

**Comment by ztplz** [comment]
Please refer to the react documentation for use.
