### ISSUE TITLE
Conditional rendering for DescriptionItem

### ISSUE THREAD

**Issue by jaimehing** [ant-design/ant-design#17530]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Whenever you want to conditionally render DescriptionItem, you can pass something like {someCondition && <DescriptionItem />}.

Currently, It's returning an error.

### What does the proposed API look like?
Allow conditional rendering of DescriptionList's children.

**Comment by afc163** [comment]
https://codesandbox.io/s/s0nnq

It works.

**Comment by jaimehing** [comment]
I forgot to add that this issue is happening in version 3.19.2. Using the latest stable version resolves the issue. Thank you!
