### ISSUE TITLE
The filterDropDown   cannot slide with tables

### ISSUE THREAD

**Issue by anjing0524** [ant-design/ant-design#17548]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-austin-fgs8r)

### Steps to reproduce
1. open the link
2. slider the scroller

### What is expected?
Keep the custom condition displayed all the time

### What is actually happening?
The filterDropDown   cannot slide with tables

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16 |
| System | win7 |
| Browser | Chrome61 |

**Comment by zombieJ** [comment]
It's by design since scrollable table popup will be hidden out of scroll container.

But you still can use ConfigProvider to config the `getPopupContainer` behavior of Table popup.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/14864#issuecomment-490733847

We may need a `getFilterDropdownContainer`, too many usage questions.

**Comment by afc163** [comment]
#16876

**Comment by anjing0524** [comment]
I'm sorry I don't quite understand. Can you give me an example @zombieJ @afc163

**Comment by anjing0524** [comment]
it dows work in table filterDropdown , I also try to select ,and it worked fine
