### ISSUE TITLE
Cascader级联选择动态加载选项，loading和isLeaf同时为true时，加载图标错位

### ISSUE THREAD

**Issue by piscdong** [ant-design/ant-design#17547]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/piscdong/pen/BgGeBp](https://codepen.io/piscdong/pen/BgGeBp)

### Steps to reproduce
点击第一级出现加载图标会错位到文字旁边，并且加粗，过一段时间恢复

### What is expected?
加载图标在右侧，不加粗

### What is actually happening?
点击第一级出现加载图标会错位到文字旁边，并且加粗，过一段时间恢复

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.2.1 |
| System | macOS 10.13.6 |
| Browser | chrome 75.0.3770.90 |

**Comment by dengfuping** [comment]
- Incorrect usage. There is no `isLeaf` prop on Cascader `option`.

**Comment by piscdong** [comment]
> * Incorrect usage. There is no `isLeaf` prop on Cascader `option`.

你确定你不是在开玩笑？你们官方的示例代码里就有
![image](https://user-images.githubusercontent.com/4155976/60875971-8d768300-a26d-11e9-8cb0-8f039478f559.png)

**Comment by zombieJ** [comment]
加载时不要设置 `isLeaf=true`： https://codesandbox.io/s/naughty-platform-9kvj8

**Comment by piscdong** [comment]
> 加载时不要设置 `isLeaf=true`： https://codesandbox.io/s/naughty-platform-9kvj8

我是希望只允许点击加载一次，加载之后把isLeaf改成true，不允许重复点击

**Comment by zombieJ** [comment]
在 loadData 里处理一下，如果已经在加载了就跳过。

**Comment by piscdong** [comment]
> 在 loadData 里处理一下，如果已经在加载了就跳过。

我现在就是这么做的，但是你这个确实也算是个bug
还有一个问题，文档里没有找到options数据的格式信息

**Comment by zombieJ** [comment]
有道理，文档得更新一下。
