### ISSUE TITLE
在typescript中，使用Tabs组件的renderTabBar时出错

### ISSUE THREAD

**Issue by Sayid1** [ant-design/ant-design#17544]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-euler-38vft)

### Steps to reproduce
光标放在第22行，提示：JSX 元素类型“DefaultTabBar”不具有任何构造签名或调用签名

### What is expected?
不报错

### What is actually happening?
报错信息：JSX 元素类型“DefaultTabBar”不具有任何构造签名或调用签名

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | masOS |
| Browser | chrome |

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/60868334-687b1380-a25f-11e9-8be7-86f85ebd42bc.png)
你这个`DefaultTabbar`哪来的

**Comment by Sayid1** [comment]
> ![image](https://user-images.githubusercontent.com/17755202/60868334-687b1380-a25f-11e9-8be7-86f85ebd42bc.png)
> 你这个`DefaultTabbar`哪来的

形参啊，第17行 
![image](https://user-images.githubusercontent.com/29008437/60868527-d0c9f500-a25f-11e9-9499-caca49cff52c.png)

**Comment by ztplz** [comment]
我明白了 
![image](https://user-images.githubusercontent.com/17755202/60869430-86e20e80-a261-11e9-977c-847d1a9c8b21.png) 这是个实例  但是你拿它当构造函数在用

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/60869556-c7da2300-a261-11e9-8491-5ea3ba02d711.png)
dan但是改成这样又很不美观

**Comment by ztplz** [comment]
for example
``````
你写react的时候, 定义了一个组件
class A extends React.Component<any, any> {
    render() {
        return <div>Hello {this.props.value}</div>;
    }
}

你用它的时候
<A value="world" />

但是。。。
如果这个A是一个实例 
你这么用
<A value="world" /> 它就报错了 
``````

**Comment by Sayid1** [comment]
> ![image](https://user-images.githubusercontent.com/17755202/60869556-c7da2300-a261-11e9-8491-5ea3ba02d711.png)
> dan但是改成这样又很不美观

我在tsconfig.json里面加上严格模式："strict": true,

这时第28行又出错了，因为我的项目是用的umi预设的typescript配置
![image](https://user-images.githubusercontent.com/29008437/60870316-3075cf80-a263-11e9-93d3-d813ca275ac6.png)

**Comment by ztplz** [comment]
其实是里面导出的定义不对  
![image](https://user-images.githubusercontent.com/17755202/60876696-fca0a700-a26e-11e9-9754-8174ac44953e.png)
tabbar不会是string  number这些东西的
ReactNode 是 ReactElement 的超集

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/60877006-8a7c9200-a26f-11e9-8d80-262d778bbb78.png)

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/60877284-1bec0400-a270-11e9-94d4-288214bcdf09.png)
问题就在这里  它用了`clonelement` 你传个`reactnode`进去就类型推导错误了
因为`reactlement`是`reactnode`的子集  反过来就错了

**Comment by ztplz** [comment]
![image](https://user-images.githubusercontent.com/17755202/60877569-aa608580-a270-11e9-85ed-ea65350edca5.png)
同样的道理 官网那个例子改成ts版本后也会挂的

**Comment by ztplz** [comment]
@Sayid1  Wanna send a fix?

**Comment by Sayid1** [comment]
> @Sayid1 Wanna send a fix?

我不明白

**Comment by ztplz** [comment]
我意思是你想要发个pr吗

**Comment by Sayid1** [comment]
> 我意思是你想要发个pr吗

我没有提过pr，不清楚提交pr的流程，这个改动也不大，你可以改一下吗
