### ISSUE TITLE
Couldn't get mime type from file in Upload component.

### ISSUE THREAD

**Issue by zcmgyu** [ant-design/ant-design#17549]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zcmgyu/pen/rEQXVw](https://codepen.io/zcmgyu/pen/rEQXVw)

### Steps to reproduce
1. Download ipa file (https://iosninja.io/ipa-library)
2. Upload ipa file
3. Check Console's logs: file.type = empty string
4. Check again with apk or zip file (It works)

### What is expected?
Because mine type of ipa file is "application/zip" (check here https://htmlstrip.com/mime-file-type-checker), so mime type of ipa file is what i need for.
Thanks.

### What is actually happening?
file.type = empty string

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.9.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
It is not antd bug, please check native input file to confirm it.

**Comment by zcmgyu** [comment]
Sorry, it actually does not work.

```
<input type="file" multiple onchange="showType(this)">
function showType(fileInput) {
  var files = fileInput.files;

  for (var i = 0; i < files.length; i++) {
    var name = files[i].name;
    var type = files[i].type;
    alert("Filename: " + name + " , Type: " + type);
  }
}
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17549#issuecomment-509592577
https://github.com/ant-design/ant-design/issues/12838#issuecomment-541723714
