### ISSUE TITLE
Typography排版组件多行文本省略功能支持回车符换行

### ISSUE THREAD

**Issue by piscdong** [ant-design/ant-design#17541]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户提交的带回车换行的多行文本，显示的时候可以支持多行文本省略功能

https://codepen.io/piscdong/pen/rEQZWY

我目前使用了两种方法，一种是用css，一种是用dangerouslySetInnerHTML，都没有实现效果

### What does the proposed API look like?
支持将回车符换行显示

**Comment by zombieJ** [comment]
Paragraph 语义上就是段落，不应该支持换行功能。包括编辑也是不允许换行的。 

related: #17094

**Comment by glin7976** [comment]
这个功能还是很有必要的啊

**Comment by hydraZty** [comment]
**Can be resolved** after replacement
[Example](https://codesandbox.io/s/cool-napier-pllv7?file=/index.js)
