### ISSUE TITLE
rc-menu props not specified in Typescript menu props interface definition

### ISSUE THREAD

**Issue by eliasinho** [ant-design/ant-design#17551]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-haze-j9zdy)

### Steps to reproduce
- Create a Menu component
- Pass it any rc-menu prop that is not exposed in antd API, e.g. triggerSubMenuAction

### What is expected?
If I pass triggerSubMenuAction with the value "click", I'm expected to have SubMenus that open on click, and not on hover

### What is actually happening?
The compilation of my app fails, caused by a Typescript checking error: TypeScript error in C:/Users/[...]:
Type '{ children: Element[]; mode: "horizontal"; triggerSubMenuAction: string; selectable: false; style: { backgroundColor: string; color: string; }; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Menu> & Readonly<MenuProps> & Readonly<{ children?: ReactNode; }>'.
  Property 'triggerSubMenuAction' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Menu> & Readonly<MenuProps> & Readonly<{ children?: ReactNode; }>'.  TS2322

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.6 |
| System | Windows 10 Pro |
| Browser | Chrome 75.0.3770.100 |

---
The props is passed down, and when there is no Typescript check we see that the sub menus are clickable. It's just that the menu/index.tsx does not define the rc-menu props in the TS props definition

**Comment by zombieJ** [comment]
It's by design to provide part of the api in antd side, since if pass all the props from rc to user will make it hard to refactor. `triggerSubMenuAction` is one of them.

If you are sure want to use this prop from `rc-menu`. You can force transfer the type of it:
```tsx
const MyMenu = Menu as any; // Or define it more specific

<MyMenu {...props} />
```
