### ISSUE TITLE
Tree组件执行onSelect的时，获取当前节点的所有父节点信息

### ISSUE THREAD

**Issue by DragonCJ** [ant-design/ant-design#17552]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tree执行onSelect的时，获取当前节点的所有父节点信息

### What does the proposed API look like?
tree执行onSelect的时，获取当前节点的所有父节点信息

**Comment by zombieJ** [comment]
性能考量特意不加的，可以通过自己的 tree data 结构自行递归出来。
