### ISSUE TITLE
Button click in Collapse.Panel extra prop triggers panel to open/close

### ISSUE THREAD

**Issue by kade-robertson** [ant-design/ant-design#17556]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-lake-obdq7)

### Steps to reproduce
1. Create a `<Collapse>` component with a `<Panel>` containing anything to ensure this component renders properly on it's own
2. Add an `extra` prop containing a Button to the `Panel` object, like so: `extra={<Button size="small" onClick={buttonClick}>Click Me</Button>`

### What is expected?
Clicking the `<Button>` should not change the state of the `<Panel>` component. 

### What is actually happening?
Clicking the `<Button>` toggles the parent `<Panel>` to open/close each time it is clicked.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.9.0 |
| System | Mac OS 10.14.5 |
| Browser | Google Chrome Version 75.0.3770.100 |

**Comment by dengfuping** [comment]
@kade-robertson Use `e.stopPropagation()`. https://codesandbox.io/s/cool-moon-k2n7g

**Comment by yhc44** [comment]
Hey @dengfuping ,

i just wanted to open your codesandbox link, but it gives me a 404 error.

I have the same problem und would like to see your solution please :-)

Thank you very much.

**Comment by ChristopherHButler** [comment]
@dengfuping e.stopPropagation() is not working with any components (button, radio, checkbox) inside a collapse panel header. If there is a working solution, please post link; As @yhc44 said the link you posted is not working. 🙏🏼

**Comment by ChristopherHButler** [comment]
For anyone who comes across this here is a working code sandbox: [https://codesandbox.io/s/frosty-bush-8jbvr?file=/index.js](https://codesandbox.io/s/frosty-bush-8jbvr?file=/index.js).

solution is to just wrap the element you want to place in header (radio, checkbox, button...whatever) in a div and call stopPropagation() on click like this: 

```
<Collapse onChange={callback}>
    <Panel
      header="This is panel header with arrow icon"
      key="1"
      extra={
        <div onClick={e => e.stopPropagation()}>
          <Button size="small" onClick={buttonClick}>
            Click me
          </Button>
        </div>
      }
    >
      <p>{text}</p>
    </Panel>
  </Collapse>
```

**Comment by dharmik29patel8** [comment]
works like butter

**Comment by Mob-Anish** [comment]
> 
Thanks it was helpful

**Comment by PlugaruRoman** [comment]
<Collapse
        expandIconPosition="right"
        collapsible="icon"
        bordered={false}
        items={collapseItems}
      />  use collapsible icon for trigger only on Icon click
