### ISSUE TITLE
Tree控件，异步数据加载，更新整个树的数据时，会导致某些节点的展开按钮消失，该节点再也无法展开

### ISSUE THREAD

**Issue by zhengshuai1001** [ant-design/ant-design#17553]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/heuristic-worker-wcs2u)

### Steps to reproduce
点击重现链接的“update data”按钮，调用setState更新数据，当一个节点已更新后，展开那个节点，再点击“update data”按钮，该节点的展开按钮消失了，该节点无法展开了。

### What is expected?
如果一个节点的数据没有children，isLeaf，那么该节点的展开按钮应该是一直在的

### What is actually happening?
展开按钮消失。

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | latest |
| System | windows 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
Tree 默认只是对节点加载一次。如果动态更新，使用 `loadedKeys` 对节点加载状态进行控制。

**Comment by Benpaodejiezai** [comment]
请问下，怎么解决的，谢谢
