### ISSUE TITLE
连续的 Modal 导致 body 上的 overflow: hidden 属性未清空

### ISSUE THREAD

**Issue by noyobo** [ant-design/ant-design#17563]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/xommEp?editors=0010](https://codepen.io/anon/pen/xommEp?editors=0010)

### Steps to reproduce
打开 Modal 后取消2次后，页面无法滚动

### What is expected?
NaN

### What is actually happening?
NaN

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | NaN |
| System | NaN |
| Browser | NaN |

**Comment by afc163** [comment]
Duplicate of #17491
