### ISSUE TITLE
[PageHeader] Extra content should be aligned with title when breadcrumb exists

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#17564]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-shannon-hkgp0)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/14918822/60939266-9ddc3b80-a309-11e9-8980-2cc9834ef7d1.png)

### What is expected?
Extra content should be aligned with title when breadcrumb exists for PageHeader.

### What is actually happening?
Extra content is not aligned with title when breadcrumb exists for PageHeader.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.9.0-alpha.0 |
| System | Mac OS |
| Browser | Google Chrome 75.0.3770.100 |

**Comment by afc163** [comment]
Fixed in latest 3.x and 4.x version: https://codesandbox.io/s/snowy-fast-ngjzc
