### ISSUE TITLE
Select component support selectAll options

### ISSUE THREAD

**Issue by zwfun** [ant-design/ant-design#17578]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
add selectAll options user not needd select all option once

### What does the proposed API look like?
Property                     | Description               | Type             | Default
-------------- | --------------| --------- | ----
selectAll               | selectAll table      | boolean      | false

**Comment by afc163** [comment]
You could do it in your own component.
