### ISSUE TITLE
Table组件中onClick事件如何阻止？

### ISSUE THREAD

**Issue by PearpearS** [ant-design/ant-design#17575]
Table组件中每行都自定义了一个图标，点击这个图标，会显示出Modal组件，然后我在Modal组件里点击任何地方，都会触发Table的onClick事件，请问如何阻止Modal的onclick事件冒泡出去？

**Comment by ctq123** [comment]
如果Modal是属于Table子元素的话，可以通过stopPropagation阻止。否则的话只能改变策略，修改你自己业务的逻辑结构
