### ISSUE TITLE
Menu 组件重复嵌套 Menu

### ISSUE THREAD

**Issue by SDLyu** [ant-design/ant-design#1758]
引入 Menu 组件之后，查看 react dev-tool 发现 Menu 会重复嵌套

代码如下:

```jsx
import { Row, Col, Menu } from 'antd'

export const Header = () => (
  <Row>
    <Col>
      <Menu mode="horizontal">
        <Menu.Item key="list">
          <Link to="/">List</Link>
        </Menu.Item>
      </Menu>
    </Col>
  </Row>
)
```

<img width="697" alt="react_redux_starter_kit" src="https://cloud.githubusercontent.com/assets/2996108/15368608/40bdb8e2-1d61-11e6-8926-2765279443fc.png">

antd version: 1.0.1

这是正常的吗

**Comment by benjycui** [comment]
正常，外面那个是 `antd.Menu`，里面那个是 rc-menu。
