### ISSUE TITLE
Cascader级联选择样式优化

### ISSUE THREAD

**Issue by tazyong** [ant-design/ant-design#17582]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
新增以下样式，可以使Cascader级联选择器输入或者选中值超过本身宽度时，显示优雅一些

nz-cascader {
&nbsp;&nbsp;input {
&nbsp;&nbsp;&nbsp;&nbsp;padding-right: 24px;
&nbsp;&nbsp;&nbsp;&nbsp;text-overflow: ellipsis;
&nbsp;&nbsp;}
&nbsp;&nbsp;.ant-cascader-picker-label {
&nbsp;&nbsp;&nbsp;&nbsp;padding-right: 24px;
&nbsp;&nbsp;}
}

### What does the proposed API look like?
无API更新，仅优化样式建议

**Comment by afc163** [comment]
来个 PR，并写清楚问题和改进后的效果吧。

**Comment by tazyong** [comment]
> 来个 PR，并写清楚问题和改进后的效果吧。

我不会写PR，我只是因为喜欢Ant Design，才帮助你们一起优化产品的。我没有义务一定要这么做，希望不要设立过多门槛。以下是在ng-zorro-antd中改进前后的效果，从选择器右侧可以看出，当前版本的样式确实不够优雅。

改进前输入和选中效果：
![image](https://user-images.githubusercontent.com/24738011/61024733-2bd72580-a3e1-11e9-9e9d-58fdf1188f59.png)
![image](https://user-images.githubusercontent.com/24738011/61024789-48735d80-a3e1-11e9-860b-b6f9e0598a79.png)

改进后输入和选中效果：
![image](https://user-images.githubusercontent.com/24738011/61025050-00086f80-a3e2-11e9-8803-cbdf4954b14c.png)
![image](https://user-images.githubusercontent.com/24738011/61025070-0eef2200-a3e2-11e9-868b-f0e6044505ea.png)
