### ISSUE TITLE
Carousel autoplay doesn't word without set autoplaySpeed

### ISSUE THREAD

**Issue by Kariko** [ant-design/ant-design#17584]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/MMLMNW?&editable=true&editors=001](https://codepen.io/anon/pen/MMLMNW?&editable=true&editors=001)

### Steps to reproduce
set autoplay but not set autoplaySpeed

### What is expected?
images can autoplay

### What is actually happening?
images can not play instead of setting autoplaySpeed, and autoplaySpeed must less than 1000, or it doesn't autoplay.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | react |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
It works in your codepen.

**Comment by cmarabate** [comment]
There is nothing to reproduce, please re-open this...

He was pointing out that the Carousel allows us to **autoplay** but it does **NOT** provide a way for us to control the **speed(how long it waits before sliding to the next slide)** of the autoplay.

Adding the **autoplay** prop makes it switch slides far too fast... So unless you add a **autoplaySpeed** prop or something to allow us to slow it down, then I can't use the **autoplay** prop.
