### ISSUE TITLE
add vertical or text align for Description

### ISSUE THREAD

**Issue by Luna-zhao** [ant-design/ant-design#17585]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
if word wrap happened, vertical align would be useful.
textAlign of the label could be more flexible in some situation

### What does the proposed API look like?
verticalAlign: 'top' | 'bottom' | 'middle' ; 
textAlign: 'left' | 'right'

**Comment by zombieJ** [comment]
Too many props if we provide align:
* labelAlign
* labelVerticalAlign
* contentAlign
* contentVerticalAlign

Use `className` to handle this:
```less
.myClass th {
  text-align: right;
}
```
