### ISSUE TITLE
Select labelInValue not working when initialValue definded and havent changing select.   Select 组件 labelInValue属性在传了初始值(initialValue )且未更改的情况下会丢失label

### ISSUE THREAD

**Issue by monsuns** [ant-design/ant-design#17591]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/monsuns/pen/VJRvOz](https://codepen.io/monsuns/pen/VJRvOz)

### Steps to reproduce
1. open the codepen link , open console and watch it
2. click submit , console give you an object without label
3. change something on select, click submit again, console give you an object with label which is normal behavior.

1. 打开上面的codepen链接, 打开左下角console控制台并观察结果. 
2. 不更改选项, 点击提交, console打出了默认值 key:3, 但是对象中缺失 label
3. 随便更改select, 点击提交, console打出了正常的包含label的对象

### What is expected?
Select with labelInValue will give object with label when initialValue given and change nothing in Form.

给表单中有labelInValue 属性的select 传递initialValue 初始值, 提交后得到带有label的对象, 与是否更改了选项无关

### What is actually happening?
Select with labelInValue give an object without label when initialValue given and change nothing in Form.

给表单中有labelInValue 属性的select 传递initialValue 初始值, 提交后的结果缺失label字段

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.x |
| System | win 10 |
| Browser | chrome 75 |

**Comment by afc163** [comment]
The `initialValue` must same as the type of `this.list` item when `labelInValue` is true, which should include `name`.

```diff
- initialValue: { key: '3' },
+ initialValue: { key: '3', name: 'expressC' },
```
