### ISSUE TITLE
Wrong order of Focus and Blur events (InputNumber)

### ISSUE THREAD

**Issue by gpetrioli** [ant-design/ant-design#17593]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-ishizaka-6blub)

### Steps to reproduce
- Click on the first of the two InputNumber element in order to focus it. 
- Click on one of the up/down arrows (*that appear when you hover*)  the second InputNumber element.

### What is expected?
It should log the focus on the first element, then log the blur on the first element and lastly log the focus on the second element.

### What is actually happening?
It logs the focus on the first element, then logs the focus on the second element and lastly the blur on the first element.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.6 |
| System | MacOS |
| Browser | Any |

---
I am creating a combo box and need the correct order so i know if the overall component is focused or not.

**Comment by dengfuping** [comment]
- Compared with `Input`: https://codesandbox.io/s/nameless-platform-zux58

**Comment by gpetrioli** [comment]
Looks like this is a bug with the underlying rc-input-number component.

Updated original codesandbox to include a rc-input-number version that also exhibits the bug.

**Comment by gpetrioli** [comment]
Related issue: react-component/input-number#187

**Comment by zombieJ** [comment]
Hi @gpetrioli, since we need keep the `onBlur` with latest `value`. We need to call `setState` with latest `value` and then trigger `onBlur`. What's your use case of order high requirement?

ref: https://github.com/react-component/input-number/blob/master/src/index.js#L297

**Comment by gpetrioli** [comment]
The perhaps you should set the focus after setting the state, so that you cannot have two focused elements at the same time. 
So https://github.com/react-component/input-number/blob/master/src/index.js#L283 could become

```
onFocus = (e, ...args) => {
    e.persist();  // fix https://github.com/react-component/input-number/issues/51
    this.setState({
      focused: true,
    }, () => this.props.onFocus(e, ...args););
  }
```

**Comment by zombieJ** [comment]
This not resolve user focus from InputNumber to other non-InputNumber component like Input. Will still get: `focus` -> `blur`

**Comment by gpetrioli** [comment]
True, that would still not be resolved. But as it stands now it is a non-standards behaviour and it is also counter-intuitive (_illogical_).

My use-case is a component with two `InputNumber` which work as a range (_and it is styled differently when focused_). So i needed to know when the whole group had focus. 

Currently it cannot work by just adding using the `onFocus` and `onBlur` events, which i was hoping would be enough.

I will find a workaround (_with timings and checking the `activeElement`_), but i thought the irregular behavior should be noted.
