### ISSUE TITLE
Affix 悬浮时 不会随窗口大小变化

### ISSUE THREAD

**Issue by ty-bt** [ant-design/ant-design#17594]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-burnell-loowj)

### Steps to reproduce
向下滚动滚动条，使Affix悬浮，将浏览器窗口拉大

### What is expected?
Affix按照样式随浏览器大小变化

### What is actually happening?
Affix固定宽度

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.6 |
| System | Window 10 |
| Browser | Chrome 73.0.3683.75 |

**Comment by dengfuping** [comment]
@ty-bt https://codesandbox.io/s/beautiful-torvalds-b7cru
```css
.ant-affix {
  width: 100% !important;
}
```

**Comment by ty-bt** [comment]
@dengfuping 这样太暴力了吧， 而且这样悬浮之后的宽度和不悬浮的宽度不一样了

**Comment by dengfuping** [comment]
@ty-bt 元素 fixed 之后，宽度本身就不会受父元素影响了。这不是组件本身的问题，fixed 效果就是这样的。

**Comment by ty-bt** [comment]
@dengfuping 较老版本是可以的 https://codesandbox.io/s/zealous-microservice-s7gxe， 我觉得最好保持一致，或者在api中说明一下，不支持动态宽度

**Comment by afc163** [comment]
要排查一下哪个版本开始有了变动。

**Comment by zombieJ** [comment]
修 #15112 重构了测量逻辑，悬浮后原本占位空间长宽就固定了。我调整一下。
