### ISSUE TITLE
Time cannot be typed into a TimePicker using a keyboard if the format is set to "HH:mm z"

### ISSUE THREAD

**Issue by jf908** [ant-design/ant-design#17599]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-glade-43erz)

### Steps to reproduce
Try to type in a time using the keyboard into the TimePicker.

### What is expected?
Time will be updated to the new time that is typed in.

### What is actually happening?
Time is being reset to previous time.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | latest |
| System | macOS 10.14 |
| Browser | Chrome 75 |

**Comment by zombieJ** [comment]
close since not a problem in v5 
https://codesandbox.io/s/billowing-frost-hhvsc9?file=/index.js
