### ISSUE TITLE
表单中使用getFiledDecorator包裹的upload组件如何上传图片到oss, 能否提供一个小demo

### ISSUE THREAD

**Issue by Lin47** [ant-design/ant-design#17609]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表单使用getFiledDecorator对upload做双向绑定时，传入getValueFromEvent事件得到的file并不是file类型的，使用upload本身自带的beforeUpload则可以获得file类型的file，成功上传。如何不使用beforeUpload成功上传呢？

### What does the proposed API look like?
无

**Comment by afc163** [comment]
这个 issue 已经有了，可以帮忙探索一下：https://github.com/ant-design/ant-design/issues/15546

**Comment by Lin47** [comment]
> 这个问题已经有了，可以帮忙探索一下：[＃15546](https://github.com/ant-design/ant-design/issues/15546)

你好，我仔细的查看那个issue过了，其中并没有关于使用getFiledDecorator包裹的upload组件如何上传至阿里oss，如果单纯的使用beforeUpload上传我已经成功实现了
