### ISSUE TITLE
DatePicker Mobile Keyboard Problem.

### ISSUE THREAD

**Issue by GMArjun** [ant-design/ant-design#17605]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In Mobile while selecting the date in datepicker there is no need to trigger keyboard to type. we just select the date we needed.

### What does the proposed API look like?
https://www.malot.fr/bootstrap-datetimepicker/demo.php?utm_source=siteweb&utm_medium=demo&utm_campaign=Site%2BWeb.

Take a look  at this demo. here they eliminated the input field and somehow show the date in a div i think. thanks.

**Comment by afc163** [comment]
Mobile
