### ISSUE TITLE
能否把文档完善、更新一下？

### ISSUE THREAD

**Issue by Veitor** [ant-design/ant-design#1760]
请问有大神能把官网以及git上的文档完善一下吗？
对照着安装几次，也用示例代码测试过，都没任何效果啊

有时候把一处示例代码一部分拿过来，再把另一处示例代码拿过来拼起来才有用，所以就怀疑是不是文档一边没更新，另一边也只更新了一半。

所以还请大神检查一下文档上的内容是不是还有效啊？包括什么脚手架工具的，文档访问端口和代码中的似乎都不一样，不同步啊

另外麻烦完善一下，把要引用的文件什么的也些进去吧，有的地方都不清楚要引用哪些文件了

**Comment by afc163** [comment]
先确保你访问的文档版本和你使用的版本一致。

![](https://os.alipayobjects.com/rmsportal/UxzPfgeGyKCeHyN.png)

这个文档应该蛮详尽的，你可以参照 http://ant.design/#/docs/react/getting-started 跑一遍，按其他人的经验应该没有问题。

**Comment by afc163** [comment]
文档有明显错误的话，欢迎帮助我们修正。

**Comment by Veitor** [comment]
为什么按照文档`npm start`后通过浏览器无法访问127.0.0.1:8001啊，似乎没有启动成功。
代码里的端口是8001吧，文档上的示例是8989

![qq 20160519170826](https://cloud.githubusercontent.com/assets/7483890/15388401/63bb8620-1de4-11e6-99df-577f8daf1963.jpg)

**Comment by afc163** [comment]
是 8989 吧。

![](https://os.alipayobjects.com/rmsportal/NcOOCKqaKBqNbVx.png)

命令行里的提示是：

![](https://os.alipayobjects.com/rmsportal/kEmONNNlnFUtivP.png)

**Comment by afc163** [comment]
命令行的提示容易有疑惑，具体可见：https://github.com/dora-js/dora/issues/66

**Comment by Veitor** [comment]
dora有没有什么运行环境的要求？我在Windows平台下似乎没有什么效果，试过各种dora的命令都没效果

测试antd都没显示下面的proxy什么的，是不是会有什么冲突还是什么的

![qq 20160520090521](https://cloud.githubusercontent.com/assets/7483890/15414155/6fbbeb64-1e6a-11e6-8b70-d1dabd7b48cf.jpg)

![qq 20160520090954](https://cloud.githubusercontent.com/assets/7483890/15414191/ad079144-1e6a-11e6-80ea-6267c3a64044.jpg)

而且这个文档http://ant-tool.github.io/ 中似乎还是用的`npm run dev`，不是改成了`npm start`了吗？
