### ISSUE TITLE
table 组件中，column 的 render 函数拿到的 index 不是数据所在数组的 index

### ISSUE THREAD

**Issue by henrycjchen** [ant-design/ant-design#17608]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-68uko)

### Steps to reproduce
在上面例子中点击 table 的第 2 页

### What is expected?
第 2 页的第 1 行数据的 index 为 1，即为数据所在数组的 index

### What is actually happening?
第 2 页的第 1 行数据的 index 为 0，为显示位置的 index

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | latest |
| System | windows 10 |
| Browser | chrome 75 |

---
为了快速获取数据（对数据增删改查），index 为数据所在数组的 index 更有用，目前 index 是显示的位置，是不是有点问题

**Comment by zxhycxq** [comment]
@mrbeannnnn  请问你是如何解决的？

**Comment by zxhycxq** [comment]
已解决

**Comment by 544751779** [comment]
@zxhycxq  请问你是如何解决的？

**Comment by zxhycxq** [comment]
> @zxhycxq 请问你是如何解决的？

不好意思，时间太久了，我也不记得了。应该还是用官方的方法吧。要么就是自己存了一份
