### ISSUE TITLE
Incorrect LESS variable for Select's background

### ISSUE THREAD

**Issue by schester44** [ant-design/ant-design#17619]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
I can't create a minimal reproduction because it requires overriding LESS variables.

Steps to reproduce:
- Override the `@input-bg` variable with a color other than white.

### What is expected?
The background color of the Select component should use `@input-bg` or it's own separate variable so we can control the background color if it.

### What is actually happening?
It uses `@component-background` which results in mis-matched colors when overriding input styles.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8 |
| System | osx |
| Browser | chrome |

---
https://github.com/ant-design/ant-design/blob/master/components/select/style/index.less#L75

**Comment by zombieJ** [comment]
`@component-background` is the mainly background color of components. `@input-bg` is for Input which is sub set of `@component-background`.
Please feel free to create a PR if you think `@select-bg` is necessary.
