### ISSUE TITLE
table component border radius has no effect

### ISSUE THREAD

**Issue by Jiang-Xuan** [ant-design/ant-design#17611]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/weathered-tree-svrpd)

### Steps to reproduce
* Step 1: goto https://codesandbox.io/s/weathered-tree-svrpd
* Step 2: You should see ![](https://i.loli.net/2019/07/12/5d28543810d5041087.png)

### What is expected?
The  table has border radius.

### What is actually happening?
The table has no border radius.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.9.0 |
| System | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 |

**Comment by zombieJ** [comment]
ref: https://github.com/ant-design/ant-design/pull/16957#issuecomment-511255063
