### ISSUE TITLE
DatePicker 系列组件的 API 能否更加灵活

### ISSUE THREAD

**Issue by SilentTiger** [ant-design/ant-design#1761]
我有个数据搜索页面，需要用户搜索某个月份到某个月份的数据，搜索条件中我本想用 MonthPicker ，可是却发现 MonthPicker 好像没有指定选择范围的接口。

DatePicker 这个系列的组件能否参照 jQuery-UI 中 DatePicker 的 API 设计，提供更多功能，谢谢。

**Comment by afc163** [comment]
应该是支持 `disabledDate` 属性的，文档要补上。
