### ISSUE TITLE
On Tree Select, do not delete content in typeahead after selection

### ISSUE THREAD

**Issue by matgargano** [ant-design/ant-design#17618]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If a user types in and then selects something -- there should be an option to not clear the typeahead content -- a user may be looking for multiple items with the same string

see: https://recordit.co/xA5O5zWmJW/gif/notify

### What does the proposed API look like?
clearTypeaheadOnSelect: false

**Comment by zombieJ** [comment]
`autoClearSearchValue`
