### ISSUE TITLE
On Tree Select, do not collapse tree on selection

### ISSUE THREAD

**Issue by matgargano** [ant-design/ant-design#17617]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If a user types in and then selects something -- there should be the option of not collapsing and scrolling the dropdown to the top

see: https://recordit.co/xA5O5zWmJW/gif/notify

### What does the proposed API look like?
collapseOnSelect: false

**Comment by zombieJ** [comment]
use `treeExpandedKeys` to control collapse status.
