### ISSUE TITLE
Form async-validator not rendering

### ISSUE THREAD

**Issue by IgorMCesar** [ant-design/ant-design#17622]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/github/IgorMCesar/react-node-boilerplate](https://codesandbox.io/s/github/IgorMCesar/react-node-boilerplate)

### Steps to reproduce
Parent:
```javascript
import LoginForm from '../../components/LoginForm';
const HomePage = () => (
  <Layout className="layout" style={{ minHeight: '100vh' }}>
    <Header>Teste</Header>
    <Content className={_s.Content}>
      <LoginForm />
    </Content>
    <Footer style={{ textAlign: 'center' }}>React Node Boilerplate</Footer>
  </Layout>
);

export default HomePage;
```

Form:
```javascript
class LoginForm extends React.Component {
  handleSubmit = e => {
    e.preventDefault();
    this.props.form.validateFields((err, values) => {
      if (!err) {
        console.log('Received values of form: ', values);
      }
    });
  };

  render() {
    const { getFieldDecorator } = this.props.form;

    return (
      <Form onSubmit={this.handleSubmit} className={_s.loginForm}>
        <Form.Item>
          {getFieldDecorator('username', {
            rules: [{ required: true, message: 'Please input your username!' }]
          })(
            <Input
              prefix={<Icon type="user" style={{ color: 'rgba(0,0,0,.25)' }} />}
              placeholder="Username"
            />
          )}
        </Form.Item>
        <Form.Item>
          {getFieldDecorator('password', {
            rules: [{ required: true, message: 'Please input your Password!' }]
          })(
            <Input
              prefix={<Icon type="lock" style={{ color: 'rgba(0,0,0,.25)' }} />}
              type="password"
              placeholder="Password"
            />
          )}
        </Form.Item>
        <Form.Item>
          {getFieldDecorator('remember', {
            valuePropName: 'checked',
            initialValue: true
          })(<Checkbox>Remember me</Checkbox>)}
          <a className={_s.loginFormForgot} href="/">
            Forgot password
          </a>
          <Button type="primary" htmlType="submit" className={_s.loginFormButton}>
            Log in
          </Button>
          Or <a href="/">register now!</a>
        </Form.Item>
      </Form>
    );
  }
}

const WrapperLoginForm = Form.create()(LoginForm);

export default WrapperLoginForm;
```

### What is expected?

Rules on form rendering.

### What is actually happening?
I am trying to make a simple form, following the example on https://ant.design/components/form/#components-form-demo-normal-login
I am able to get all valid data if they are inputed and recive erros on console, if they are not: (async-validator: ["username is required"] async-validator: ["password is required"])
But the rules are not rendering.
![FORM](https://i.gyazo.com/0c41ec308f944cd67eb6d1a94639ac96.png)

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | react |
| System | Windows 10.0.18362 Comp 18362 |
| Browser | Chrome 75.0.3770.100 (64 bits) |

**Comment by IgorMCesar** [comment]
Foun the issue, apparently rc-form doesnt work with lodash-webpack-plugin. Any idea why is that?

**Comment by zombieJ** [comment]
hi @IgorMCesar,
`lodash-webpack-plugin` already provides config in doc of `paths`. And in antd side, it's not a good place to over docs about external package usage since they are too many package for user to choice.

ref:
* https://github.com/ant-design/ant-design/issues/7359#issuecomment-480815851
* https://github.com/lodash/lodash-webpack-plugin/issues/134

**Comment by gurusoft13** [comment]
So isn't it possible to use lodash on ant design?

**Comment by 07akioni** [comment]
> So isn't it possible to use lodash on ant design?

you can use lodash. If you want to use it with `lodash-webpack-plugin`, you may need some configuration.
