### ISSUE TITLE
Nested table data with editable cells , children cell edit not works as expected

### ISSUE THREAD

**Issue by hammerstrike** [ant-design/ant-design#17624]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-mirzakhani-c0csz)

### Steps to reproduce
Try to edit children data

### What is expected?
Children data should be updated

### What is actually happening?
Adding new updated record at last row

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.0.0 |
| System | Windows |
| Browser | Chrome |

**Comment by N1ck0lay** [comment]
any workarounds?
