### ISSUE TITLE
RangePicker 设置 mode={["time", "time"]}  showTime 默认还是选择日期模式

### ISSUE THREAD

**Issue by chinacoolboyzz** [ant-design/ant-design#17625]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-lamarr-q0xkz)

### Steps to reproduce
RangePicker 设置 mode={["time", "time"]}  showTime 默认状态还是日期模式
需要再次点击选择时间才可以切换为正确的时间模式

### What is expected?
期望设置 mode={["time", "time"]}  showTime 时默认是选择时间模式

### What is actually happening?
设置 mode={["time", "time"]}  showTime 时默认是选择日期模式

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.9 |
| System | mac 10.13.6 |
| Browser | chrome |

**Comment by TomLeel** [comment]
一、设置 mode={["time", "time"]} showTime 时日期显示错误 
![image](https://user-images.githubusercontent.com/24224985/62602644-c1090380-b926-11e9-9dac-55416e49f6aa.png)

二、并且没有初始值时，无法选择时间
![image](https://user-images.githubusercontent.com/24224985/62602755-104f3400-b927-11e9-99ef-0ea8ba637c3e.png)
