### ISSUE TITLE
为何table的columns的render中this是未定义，是bug吗

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#1762]
del()
  {
    alert('aa')
  }    
 
 
 const columns = [{ title: '种类', dataIndex: 'Kind', key: 'Kind', },
      { title: '键值', dataIndex: 'KeyName', key: 'KeyName', },
      { title: '值', dataIndex: 'Value', key: 'Value', },
      { title: '显示排序', dataIndex: 'Sort', key: 'Sort', },
      {
        title: '缺省选中', dataIndex: 'DefaultSelect', key: 'DefaultSelect',
        render(text, record, index) {
          return (
            
              //   <a href="javascript:void(0)" onClick={(e) => {debugger;this.Del()}} >删除</a>
            //    <Input type="number"  step={0.01}   style={{textAlign: 'right'}} placeholder="元"/> 
            record.DefaultSelect == true ? '是' : '否'
          );
        }
      },
      { title: '使用开放', dataIndex: 'Used', key: 'Used', },
      { title: '种类', dataIndex: 'IsOpen', key: 'IsOpen', },
      {
        title: '操作', dataIndex: 'DictId', key: 'operation',
        render(text, record, index) {

          return (

            <span>
                  **<a href="javascript:void(0)" onClick={(e) => {debugger;this.Del()}} >删除</a>**

            </span>
          );
        }
      },
    ];
错误提示： 
 DictListForm.js:189 Uncaught TypeError: Cannot read property 'Del' of undefined

**Comment by benjycui** [comment]
建议认真学习 JavaScript http://bonsaiden.github.io/JavaScript-Garden/zh/#function.this

**Comment by whx76** [comment]
可以告诉我哪里错了吗？

**Comment by whx76** [comment]
大神指点下

**Comment by whx76** [comment]
找到问题了 this的绑定位置坑

**Comment by lcoder** [comment]
有最佳实践吗？我columns是绑定在static defaultProps中的，所以this不好绑定
```javascript
class App extends Component {
   render(){
      var columns = [ {} ....{ render: ()=>{ return <a onClick={ this.handleClick.bind(this) } ></a> } } ]
  }
}
```
只能这样子吗？这样是不是没吃render都自动生成一遍了，感觉这个不变的东西是不是放外面的更好？你们是怎么解决的。谢谢

**Comment by afc163** [comment]
```js
constructor() {
  this.columns = [...];
}
```

**Comment by lcoder** [comment]
@afc163 嗯，谢谢，考虑到columns一般都会很长，放constructor里面有点臃肿了，所以还是放外面，在constructor绑定this了。
```javascript
export default class MyTasks extends Component {
    constructor( props ){
        super( props ) ;
        this.columns = this.props.getColumns.call( this ) ;
    }
    // 每次state change
    render(){
        return <Table columns={ this.columns } dataSource={ [ {} , {} , ... ] } />
    }
    static defaultProps = {
        getColumns: function(){
            return [
                {
                  title: '编号' ,
                  dataIndex: 'id' ,
                  key: 'opBaseId' ,
                } ,
                {
                  title: '操作' ,
                  key: 'operator' ,
                  render: ( text , record) => {
                    return <span>
                      { record.getable ?
                        <a href="javascript:void 0;" onClick={this.handlePick.bind(null,record)}>接手</a> :
                        <a href="javascript:void 0;" onClick={this.handleProcess.bind(null,record)}>处理</a> }
                    </span>
                  }
                }
            ] ;
        }
    }
}
```

**Comment by hu-ke** [comment]
It would be more clear:
```
export function getColumns() {
  return [
    {
      title: '编号' ,
      dataIndex: 'id' ,
      key: 'id' ,
    } ,
    {
      title: '操作' ,
      key: 'operator' ,
      render: ( text , record) => {
        return <a href="javascript:void 0;" onClick={this.handlePick.bind(null,record)}>删除</a>
      }
    }
  ];
}

import { getColumns } from './columns'

export default class MyTasks extends Component {
  constructor( props ){
    super( props ) ;
    this.columns = getColumns.call( this ) ;
  }
  render(){
    return <Table columns={ this.columns } dataSource={ [ {} , {} , ... ] } />
  }
}
```

**Comment by Joldnine** [comment]
Here is what I do to toggle the issue:
`onClick={() => this.handleClickDetails(index)}`
