### ISSUE TITLE
Modal中的内容的滚动条无法用键盘上下左右控制？

### ISSUE THREAD

**Issue by liuxilei** [ant-design/ant-design#17636]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-lo3vt)

### Steps to reproduce
modal内的内容不能用键盘上下左右来控制

### What is expected?
希望可以得到帮助，有什么解决办法呢，感谢

### What is actually happening?
Modal中的内容的滚动条无法用键盘上下左右控制？

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.8.6 |
| System | win10 |
| Browser | Chrome 74.0.3729.131 |

**Comment by zombieJ** [comment]
`div` 里监听键盘事件，对 scroll 做处理。
