### ISSUE TITLE
sider & Menu component collapsed dislocation

### ISSUE THREAD

**Issue by xjh22222228** [ant-design/ant-design#17631]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/cool-wind-p0n7w)

### Steps to reproduce
1、Click me Button

### What is expected?
none

### What is actually happening?
dislocation.

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.8 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
Reproduce is empty.

**Comment by xjh22222228** [comment]
@zombieJ Not empty.         https://codesandbox.io/s/cool-wind-p0n7w?fontsize=14

**Comment by afc163** [comment]
same as #17174.

**Comment by wuzhidexiaoheizi** [comment]
bug is still exist
