### ISSUE TITLE
AutoComplete Select -- allow auto-focus the input text box when tabbing on the form

### ISSUE THREAD

**Issue by macalinao** [ant-design/ant-design#17632]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Different UX. We have a lot of forms where we use this dropdown component and we would like it to behave like an input (text) box   show the dropdown when tabbed to.

### What does the proposed API look like?
Another prop: 
```<Select allowTypingOnInitialFocus={true} />```

**Comment by zombieJ** [comment]
AutoComplete is type-able when get focused: https://codesandbox.io/s/silly-borg-76d4j

**Comment by macalinao** [comment]
No, I am talking about the Select Autocomplete-- when you use a Select and have a typeahead in it.

**Comment by zombieJ** [comment]
Hi @macalinao,
Could you help to provide a reproduce for this to help understanding?
