### ISSUE TITLE
AutoComplete如何选中之后清空input框的值？

### ISSUE THREAD

**Issue by PearpearS** [ant-design/ant-design#17630]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1rs1h)

### Steps to reproduce
在AutoComplete中自定义了选项，每次选择一个，都会生成一个Tag，希望每次生成Tag后，能自动清空input框，来满足业务需求，不知道可不可以支持清空input？

### What is expected?
在AutoComplete中自定义了选项，每次选择一个，都会生成一个Tag，希望每次生成Tag后，能自动清空input框。

### What is actually happening?
无法清空input框，发现input的值是根据自定义选项中的key值显示的

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.4 |
| System | win10 |
| Browser | Chrome 75.0.3770.100 |

**Comment by zombieJ** [comment]
`onSelect` 在 `onChange` 之前触发，导致在 `onSelect` 里设置 `value` 值为空后，触发 `onChange` 又被设置回来使得不能受控。我们要不要把顺序调整一下，变成先 `onChange` 再 `onSelect`？https://codesandbox.io/s/antd-reproduction-template-487l2

@afc163 

ref:
https://github.com/react-component/select/blob/24bf6c729ca432e86000de7adbcf29ac60e478e1/src/Select.tsx#L445

**Comment by PearpearS** [comment]
感谢
