### ISSUE TITLE
Menu组件设置defaultSelectedKeys失效

### ISSUE THREAD

**Issue by alwaysRemember** [ant-design/ant-design#17638]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
使用Menu组件，在useEffect中动态设置了defaultSelectedKeys参数，参数变化可并没有ui变化

### What is expected?
参数变化后ui变化

### What is actually happening?
参数变化后ui无变化

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.8.6 |
| System | macos |
| Browser | chrome |

---
是否是因为props改变后组件内无监听导致并没有改变到组件内的数据

**Comment by xjh22222228** [comment]
@alwaysRemember defaultSelectedKeys 是非受控属性， 请改用 selectedKeys

**Comment by alwaysRemember** [comment]
> @alwaysRemember defaultSelectedKeys 是非受控属性， 请改用 selectedKeys

好的 ，感谢
