### ISSUE TITLE
Table pagination shows incorrent current page when sorting

### ISSUE THREAD

**Issue by aarifkhamdi** [ant-design/ant-design#17648]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lively-cookies-6pwmx?fontsize=14)

### Steps to reproduce
Navigate to page 2,
sort by clicking any table head

### What is expected?
current page = 2

### What is actually happening?
in console you can see that current page is 1

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
It is not a bug, please look https://github.com/ant-design/ant-design/issues/16978

**Comment by rohit-smpx** [comment]
This is a bug when using local sorter function. If I just want to do inline sort of just the current results it is currently not possible because the `pageChange` event resets my data. Resetting the page should be left upto the user to handle in `onChange` listener.

**Comment by DreFalPoetry** [comment]
希望能改回来 由场景控制是否回到第一页 而不是在sort的时候触发 pagination方法
