### ISSUE TITLE
table中切换不同数据的时候，Form表单中的Tree组件defaultCheckedKeys属性无效

### ISSUE THREAD

**Issue by shmmly** [ant-design/ant-design#17644]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/spring-meadow-yjqh4?fontsize=14)

### Steps to reproduce
点击 行1 的编辑 之后，再点击行2的编辑，tree组件数据没有发生变化。

### What is expected?
期望 点击不同的行，对应的tree组件的defaultCheckedKeys 可以一起变化。

### What is actually happening?
实际结果，defaultCheckedKeys 只在第一个编辑按钮点击之后，赋值成功了

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.8.6 |
| System | window7 |
| Browser | chrom  75.0.3770.100 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
