### ISSUE TITLE
How does the upload component change the default POST submission to the PUT request?

### ISSUE THREAD

**Issue by HSdiana** [ant-design/ant-design#17640]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
How does the upload component change the default POST submission to the PUT request?

### What does the proposed API look like?
How does the upload component change the default POST submission to the PUT request?

**Comment by afc163** [comment]
customRequest
