### ISSUE TITLE
table 列合并和分页功能同时使用时，出现跨页合并的情况，表格会乱掉

### ISSUE THREAD

**Issue by zhangjie2012** [ant-design/ant-design#17650]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-framework-dj6ci)

### Steps to reproduce
1. table 使用列合并
2. 使用分页
3. 源数据中的最后一个行横跨多个行导致分页

### What is expected?
第二页的合并列与第一页数据保持一致，其它行正常显示

### What is actually happening?
没有显示合并列内容数据，其它行自动排到了前面

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.8.0 |
| System | macOS |
| Browser | Google chrome 75.0.3770.100 |

**Comment by zombieJ** [comment]
Table 角度每个 record 是一行。如果要和分页配合的话，需要自行处理 pageSize 来让每页显示正确的何必状态。

**Comment by zhangjie2012** [comment]
> Table 角度每个 record 是一行。如果要和分页配合的话，需要自行处理 pageSize 来让每页显示正确的何必状态。

@afc163  关了是因为这就是解决办法吗？

**Comment by afc163** [comment]
是的，目前找不到更好的办法，如果有解，欢迎 PR
