### ISSUE TITLE
Tabs的容器为剩余高度

### ISSUE THREAD

**Issue by longang520** [ant-design/ant-design#1765]
怎么样设置tabs的ant-tabs-content 为剩余高度。不是随着内容的高度变化
如果高度超过剩余高度ant-tabs-content出现滚动条。

**Comment by afc163** [comment]
css 样式问题，请参考布局 http://zh.learnlayout.com/

非 Ant Design 和 antd 的问题不要来这里问，很耗费维护者的精力的。
