### ISSUE TITLE
[Feature] Arrows on the submenu not adhering to Menu `mode` when used in a Dropdown

### ISSUE THREAD

**Issue by lvybriage** [ant-design/ant-design#17654]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/6101](https://github.com/ant-design/ant-design/issues/6101)

### Steps to reproduce
It's similar with this issue#6101. I think it's a good issue, why not consider to support it?

### What is expected?
to support mode in dropdown with menu

### What is actually happening?
and now it doesn't support

| Environment | Info |
|---|---|
| antd | 3.8.1 |
| React | 16.7.0 |
| System | window |
| Browser | Chorm |

**Comment by afc163** [comment]
Sorry, dropdown menu don't support `mode` and won't support in current plan.
