### ISSUE TITLE
Table 拖拽排序demo失效，据此实现的功能也失效无法实现拖拽排序，请帮忙看看

### ISSUE THREAD

**Issue by perfylee** [ant-design/ant-design#17660]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting](https://ant.design/components/table-cn/#components-table-demo-drag-sorting)

### Steps to reproduce
BUG

### What is expected?
修复此DEMO

### What is actually happening?
原项目antd版本3.17 升级版本至 3.20.3后出现此问题

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.7.0 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
![Kapture 2019-07-16 at 10 50 45](https://user-images.githubusercontent.com/5378891/61262418-b8a22a80-a7b7-11e9-802a-4a5101b4dc6d.gif)
