### ISSUE TITLE
浮层下使用下拉框，滚动的时候，下拉框不动。

### ISSUE THREAD

**Issue by noonnightstorm** [ant-design/ant-design#1766]
### My problem
浮层下使用下拉框，滚动的时候，下拉框不动。
![bugImg](https://static.dingtalk.com/media/lALOInQGwM0B380CXw_607_479.png_620x10000q90.jpg)

### Code problem
* 下拉菜单在body下生成一个div并且是position:absolute的
* 浮层是position:fixed的
* 所以当滚动的时候两个位置对不上

###  My advance
* ant-modal-open这个类加上overflow: hidden，boostrap的modal-open也是的。保证打开浮层，body不能动
* 下拉菜单应该append到input框下面，不应该append到body，不过有可能是出于某些原因才append到body。顺便请教一下。

**Comment by benjycui** [comment]
http://ant.design/#/components/select?scrollTo=Select+props

![image](https://cloud.githubusercontent.com/assets/3580607/15381393/b17dcfae-1db1-11e6-84cb-25bd290cde26.png)

**Comment by afc163** [comment]
1. fixed in https://github.com/ant-design/ant-design/commit/a15b601e6d3b4e839f2728b6382c427bafe93fa9 and 1.1.0
2. 看楼上

**Comment by benjycui** [comment]
> 下拉菜单应该append到input框下面，不应该append到body，不过有可能是出于某些原因才append到body。顺便请教一下。

之前有 issue 讨论过这个，自行搜索下？

**Comment by noonnightstorm** [comment]
好的，我升级一下。最近没更新版本。
