### ISSUE TITLE
menu菜单collapsed的时候，使用iconfont字体样式出错

### ISSUE THREAD

**Issue by chaserstrong** [ant-design/ant-design#17666]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/RzzOBV](https://codepen.io/anon/pen/RzzOBV)

### Steps to reproduce
我引入了自定义的iconfont，但是menu收起来的时候，样式和用自带的Icon明显不一样了

### What is expected?
两者样式应该是一致的

### What is actually happening?
两者样式不一致

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.4.1 |
| System | mac os |
| Browser | chrome 75.0.3770.100 |

**Comment by afc163** [comment]
Try `Icon.createFromIconfontCN`

https://codepen.io/anon/pen/xoovgv
