### ISSUE TITLE
Input使用setFieldsValue 值是Number,加上whitespace 会校验不通过

### ISSUE THREAD

**Issue by furylee** [ant-design/ant-design#17661]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-sun-2huqm?fontsize=14)

### Steps to reproduce
去掉whitespace 时,校验通过,加上则校验不通过

### What is expected?
通过

### What is actually happening?
未通过

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.6 |
| System | win10 |
| Browser | 74.0.3729.169 |

**Comment by zombieJ** [comment]
https://github.com/yiminghe/async-validator#whitespace

> The rule must be a `string` type.

**Comment by furylee** [comment]
rules: [
              { required: true, message: "Please input your username!" },
              {transform:v=>`${v}`},
              { whitespace: true, message: "不能为空" },
              
            ]
fix
