### ISSUE TITLE
A bordered table is loses its border if it can scrolled

### ISSUE THREAD

**Issue by Jiang-Xuan** [ant-design/ant-design#17674]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silent-wildflower-7w2t2)

### Steps to reproduce
* Step 1: goto https://codesandbox.io/s/silent-wildflower-7w2t2
* Step 2: scroll the table
* Step 3: you can see ![](https://i.loli.net/2019/07/16/5d2d98cf975eb41511.png)

I am not sure if this is intentional😅.

### What is expected?
The table has 1px border when scrolling.

### What is actually happening?
The table has’t 1px border when scrolling.

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.9.0 |
| System | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3847.0 Safari/537.36 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3847.0 Safari/537.36 |

**Comment by yoyo837** [comment]
下、左、右以及上方设置不显示列头时是一样的情况

**Comment by Jiang-Xuan** [comment]
any progress ❓

**Comment by afc163** [comment]
It is hard to resolve than I imaged.

**Comment by Jiang-Xuan** [comment]
What can i help 👋

**Comment by shaodahong** [comment]
because it's set `border` in scroll element, should set in its wrapper

**Comment by Jiang-Xuan** [comment]
@shaodahong agree

**Comment by shaodahong** [comment]
@afc163 @Jiang-Xuan 这个如果不想设置包容器的 `border` 来解决的话可以设置 `box-shadow`，对页面交互来说更友好一点

![image](https://user-images.githubusercontent.com/14831261/61934474-f0c91a80-afba-11e9-8539-c19ef1201922.png)

**Comment by Jiang-Xuan** [comment]
i'll try @shaodahong

**Comment by jiangzm** [comment]
我的场景是使用鼠标系统就有默认滚动条，拔掉鼠标用触摸板就没有默认滚动条（有虚拟滚动条），有虚拟滚动条的场景外边框显示不全。#18742 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/currying-pond-dhfnl)

**Comment by afc163** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/507615/76628282-72d07880-6577-11ea-957f-c3f949691de6.png">

4.x 的 Table 统一加了滚动的阴影，用别的方式解决了这个问题。
