### ISSUE TITLE
Can't call setState on a component that is not yet mounted

### ISSUE THREAD

**Issue by alanhg** [ant-design/ant-design#17689]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:3000](http://localhost:3000)
I have not create demo url link
### Steps to reproduce

```
 geoChange = geo => {
    const regions = this.props.geos.filter(item => {
      return item.geo === geo;
    }).map(item => item.region);
    this.setState({
      regions
    });
  };

 <Select onChange={this.geoChange}>
                    {_.map(geos, value => (
                      <Select.Option key={value} value={value}>
                        {value}
                      </Select.Option>
                    ))}
                  </Select>
```

### What is expected?
setState success, not an error !

### What is actually happening?
error:
warning.js:33 Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the SettingPage component

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.4.2 |
| System | Mac 10.14.5 |
| Browser | Chrome Version 75.0.3770.100 |

**Comment by marciopamplona** [comment]
This is an anti-pattern, it is not supposed you code intentionally that way.
https://www.robinwieruch.de/react-warning-cant-call-setstate-on-an-unmounted-component/

**Comment by ztplz** [comment]
@marciopamplona  Totally agree, this looks like he is not using react correctly, but a repo will be more helpful.
@alanhg  Any repo for debugging?
