### ISSUE TITLE
Use form.setFieldsValue to set the Switch's value in form

### ISSUE THREAD

**Issue by jcedo** [ant-design/ant-design#17683]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/about-switch-in-ant-design-form-gclw6?fontsize=14)

### Steps to reproduce
I created a component named IForm that can build the <Form.Item/> dynamically by the props from its parents.
The Main component(parent) can use the setFormData function to set the data of the form in IForm.
I met some problem when I set the value of the Switch in IForm.

我创建了一个名为IForm的组件，可以通过其父组件传入的props动态地创建Form.Item标签。
组件Main（父组件）可以通过setFormData方法去设置IForm中表单的数据.
当我设置IForm中Switch的值时，我遇到了问题。

### What is expected?
The value of Switch is set , and the appearance of the Switch component has no changed when I set whatever true or false. 

当我从父组件设置位于IForm的Switch的值时，表单中的Switch的值已经发生了变化了，但是Switch的外观没有发生任何变化

### What is actually happening?
Set value of the Switch, the value and appearance will changed.

设置时，值与外观一齐变化

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.7.0 |
| System | macOS 10.14.4 |
| Browser | Google Chrome 75.0.3770.142 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10945#issuecomment-414148274
https://github.com/ant-design/ant-design/issues/9611#issuecomment-372025907
