### ISSUE TITLE
如何在jsx中更改less变量，来更改主题

### ISSUE THREAD

**Issue by smz8023** [ant-design/ant-design#17687]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-oxezk)

### Steps to reproduce
在webpack中设置	
1.	fixBabelImports('import', {
		libraryName: 'antd',
		libraryDirectory: 'es',
		//  style: 'css',
		style: true
	}),
2.addLessLoader({
		javascriptEnabled: true,
		modifyVars: { '@primary-color': '#1DA57A' }
	}),

### What is expected?
可以通过less.modifyVars 更改主题色

### What is actually happening?
没有改变

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.8 |
| System | windows |
| Browser | 谷歌 |

**Comment by yoyo837** [comment]
不支持

**Comment by smz8023** [comment]
我看咱的antd - pro 是支持一键换主题的额   是否可以提供一个小的实现仓库？

**Comment by yoyo837** [comment]
直接用antd - pro吧

**Comment by afc163** [comment]
https://github.com/mzohaibqc/antd-theme-generator
