### ISSUE TITLE
表格组件x轴的scrollbar，使用触摸板移动点击到滚动条，滚动条就不会隐藏了

### ISSUE THREAD

**Issue by daniel0code** [ant-design/ant-design#17685]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header](https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header)

### Steps to reproduce
将触摸板移动到滚动条，放置大约0.2秒，滚动条就不会消失。在table size为small的时候，就把table的最后一行内容给遮挡了

### What is expected?
希望可以滚动条在触摸板状态下移动至滚动条后，滚动条仍会消失

### What is actually happening?
表格组件x轴的scrollbar，使用触摸板移动点击到滚动条，滚动条就不会隐藏了

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | any |
| System | any |
| Browser | chrome |

---
官网的table组件的固定列示例就可以重现

**Comment by daniel0code** [comment]
![image](https://user-images.githubusercontent.com/14293002/61308796-95ad6000-a823-11e9-9a3b-786411ea854d.png)
官网示例为正常size的table，所以没有遮挡。
但是如果是small size的table，就看不见字了

**Comment by daniel0code** [comment]
我的项目中的截图如下
![image](https://user-images.githubusercontent.com/14293002/61308952-eb820800-a823-11e9-8712-3f1ed718cb66.png)

**Comment by daniel0code** [comment]
希望可以告知怎么修复或者调整。谢谢

**Comment by zombieJ** [comment]
mac 祖传的 bug，antd 这边做不了什么。
