### ISSUE TITLE
Table：change column sort will trigger onChange of pagination

### ISSUE THREAD

**Issue by zxpray** [ant-design/ant-design#17688]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-hofstadter-qr2pe)

### Steps to reproduce
1.change column age sort
2.view the console

### What is expected?
onchange will not be triggered

### What is actually happening?
onchange will be triggered

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.6 |
| System | window10 |
| Browser |  Google Chrome 75.0.3770.142 |

**Comment by zombieJ** [comment]
`sorter` is one of the `onChange` param.

**Comment by zxpray** [comment]
the onchange of question is one param of pagination.Why change column sort will affect the the param of pagination. @zombieJ

**Comment by zombieJ** [comment]
Sort will reset pagination to page 1.

**Comment by BernardZhang** [comment]
sort 变化，会出发pagination的onChange, 且无法区分是由sort触发的，这个我理解就是一个bug，要不别触发，触发了就要告诉是由哪个触发的，包括Table的onChange也是同样问题。

**Comment by jayguojianhai** [comment]
我也遇到了相同的问题，触发排序本身就只排序当前页的数据，为什么会把分页重置为1，搞不明白？

**Comment by jayguojianhai** [comment]
而且我还无法判断这个触发的来源，尴尬了
