### ISSUE TITLE
form Setfieldvalue is not working for switch

### ISSUE THREAD

**Issue by vidamomenzadeh** [ant-design/ant-design#17691]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
just try to setfieldvalue for switch in form 

### What is expected?
make switch on when value is true

### What is actually happening?
switch value is off

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | react |
| System | window 8.1 |
| Browser | chrome  |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17683
