### ISSUE TITLE
怎样让compact组合输入框的每一个输入框的错误提示信息都显示在下方啊，现在只显示第一个input框的错误提示

### ISSUE THREAD

**Issue by jialuoJiang** [ant-design/ant-design#17693]
不使用 <Form.Item> 使用<Form.Item>标签之后，就起不到compact的效果了

`<FormItem>
                                                       <InputGroup compact>
                                                        {getFieldDecorator(key[0] + index, { initialValue: initVal[0],rules:[{pattern:reg[0],message:msg[0]}] })(<Input placeholder={placeholder[0]} style={{ "width": "55%" }} />)}
                                                        {getFieldDecorator(key[1] + index, { initialValue: initVal[1],rules:[{pattern:reg[1],message:msg[1]}] })(<Select style={{ "width": '45%', "borderRight": "1px solid #d9d9d9" }} placeholder={placeholder[1]}>
                                                            {
                                                                relation.map((it, ind) => {
                                                                    return (
                                                                        <Option key={ind} value={it.value}>{it.name}</Option>
                                                                    )
                                                                })
                                                            }
                                                        </Select>)}
                                                        {getFieldDecorator(key[2] + index, { initialValue: initVal[2] ,rules:[{pattern:reg[2],message:msg[2]}]})(<Input placeholder={placeholder[2]} style={{ "borderTop": "none", "borderBottom": "none", "borderRight": "1px solid #d9d9d9" }} />)}
                                                        {getFieldDecorator(key[3] + index, { initialValue: initVal[3] ,rules:[{pattern:reg[3],message:msg[3]}]})(<Input placeholder={placeholder[3]} />)}
                                                    </InputGroup>
                                                    </FormItem>`

**Comment by komagic** [comment]
{first:true}
