### ISSUE TITLE
antd 3.20.3 版本 Cascader 组件对option选项的children的判断异常，以前支持children为null的现在只会判断undfined,导致组件异常

### ISSUE THREAD

**Issue by ooxx87** [ant-design/ant-design#17690]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/changelog-cn](https://ant.design/changelog-cn)

### Steps to reproduce
antd 3.20.3 版本 Cascader 组件对option选项的children的判断异常，以前支持children为null的现在只会判断undfined,导致组件异常

### What is expected?
对option的children判断支持null值判断

### What is actually happening?
对option的children判断支持null值判断

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.8 |
| System | win10 |
| Browser | ie11 |

**Comment by wyaihy** [comment]
![image](https://user-images.githubusercontent.com/22446639/61511682-1342bd00-aa2a-11e9-8454-cc363eebee3e.png)

**Comment by wyaihy** [comment]
3.19.6 版本里支持children为null，看更新日志是否是
![image](https://user-images.githubusercontent.com/22446639/61511851-a7ad1f80-aa2a-11e9-96a5-ad365045e848.png)
![image](https://user-images.githubusercontent.com/22446639/61511986-1ab69600-aa2b-11e9-8123-26783749c0a7.png)
这里限制了类型，但与后台交互子节点没有时会是null，希望当option里的children为null时组件能正常运行

**Comment by afc163** [comment]
这块最近貌似没有改动，来个重现看看？

https://codesandbox.io/s/react-ts

**Comment by ooxx87** [comment]
我这边项目里把children的值手工从null转为undefined是不会异常的，因为本地代码都修复过了，所以暂时没有可以重现的代码

**Comment by afc163** [comment]
https://codesandbox.io/s/react-ts

**Comment by wyaihy** [comment]
https://codesandbox.io/s/condescending-saha-02ekp

**Comment by wyaihy** [comment]
https://codesandbox.io/s/antd-reproduction-template-dpnep
![image](https://user-images.githubusercontent.com/22446639/61514873-a6342500-aa33-11e9-8ced-b6d57226cd8f.png)
当这个children为undefined或[ ]都正常，为null就不行

**Comment by ztplz** [comment]
@wyaihy  因为为null的时候  它不会设置默认值
![image](https://user-images.githubusercontent.com/17755202/61520219-48f2a080-aa40-11e9-9b7a-ff7672b08a33.png)
因为文档上没允许null  所以改了那个

**Comment by wyaihy** [comment]
@ztplz 所以，能改回来吗？因为后台处理的时候根节点没有的话都会返回为null，如果不允许为null的话，前端得遍历一遍树形结构，那么fieldNames这个属性个人觉得就失去意义了

**Comment by ztplz** [comment]
这就很尴尬了  原来的代码逻辑是支持null的   但是。。。 类型还有文档里没有说支持null
然后你们又都传了null进去  它以前是不会报错的

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design/commit/4a1d68c87f3cc034a2edcea85ae4468ce5764a36#diff-3141ae7cf791cd0b5edcad2c51dd6ddd
你可以看我这个pr  原来用null不会报错是因为 null会短路 然后给 options赋予一个空数组
我改成参数默认赋值后 null是不会被赋予空数组的 所以它报错了
但是我考虑过  如果有打算支持null的话 
![image](https://user-images.githubusercontent.com/17755202/61529477-fcb15b80-aa53-11e9-9879-73f1ec27ead1.png)这里应该是 CascaderOptionType[] | null  还有文档里也没写支持null 所以我改了

**Comment by wyaihy** [comment]
![image](https://user-images.githubusercontent.com/22446639/61530521-da6d0d00-aa56-11e9-8dcc-578b244fd230.png)
感觉把这里改回去就可以了

**Comment by glacierck** [comment]
我想说的是3.20.5也有这问题，话说null是有什么特殊意义的吗？，没有请把它跟[],undefined对齐。保证在这模块里他们是统一含义的就是没有子集，ok？给几个现场
![image](https://user-images.githubusercontent.com/21599896/61850364-bbeb9380-aee6-11e9-8044-f08b0660c576.png)
![image](https://user-images.githubusercontent.com/21599896/61850367-c0b04780-aee6-11e9-805a-ce9054723769.png)
还有就是官方演示的居然是没毛病（3.20.6）就差那么个0.0.1。调得我怀疑人生。

**Comment by wyaihy** [comment]
![image](https://user-images.githubusercontent.com/22446639/61850985-3c5ec400-aee8-11e9-9146-a19f94634923.png)
3.20.6已经修复了https://ant.design/changelog-cn

**Comment by ooxx87** [comment]
感谢谢谢
