### ISSUE TITLE
Select选择框是否支持回车事件远程搜索

### ISSUE THREAD

**Issue by yangslmp** [ant-design/ant-design#17701]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Select选择框是否支持回车事件远程搜索，由于后台数据上百万，搜索的时候如果使用onSearch方法，每输入一个字符就会到后台搜索一次，效率太低了，有没有大神有遇到和我一样的问题
在线等，急急急

### What does the proposed API look like?
通过开放回车接口，自己去调用后台接口

**Comment by afc163** [comment]
`onInputKeyDown`

**Comment by yangslmp** [comment]
类似接口官方文档里面为什么少不写啊

**Comment by afc163** [comment]
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/507615/61433708-9d295200-a966-11e9-88cf-b21783450322.png">

应该是中文文档里漏掉了，可以来个 PR 补齐。
