### ISSUE TITLE
Input.TextArea也支持Input的属性allowClear

### ISSUE THREAD

**Issue by hqzh** [ant-design/ant-design#17709]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一键清除内容

### What does the proposed API look like?
<Input.TextArea  allowClear />

**Comment by Rustin-Liu** [comment]
Hi @afc163, I just started working on this.

**Comment by Rustin-Liu** [comment]
大家对删除图标放在哪里有什么建议吗？

**Comment by Rustin-Liu** [comment]
#19310

**Comment by Rustin-Liu** [comment]
我的pr还没合，合了再关吧

**Comment by yoyo837** [comment]
close by #19310, it's merged into master. 

https://github.com/ant-design/ant-design/releases/tag/3.25.0
