### ISSUE TITLE
Progress 组件显示有锯齿

### ISSUE THREAD

**Issue by liran** [ant-design/ant-design#17706]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/22112008/61433799-d661c200-a966-11e9-81f2-a1a45384b526.png](https://user-images.githubusercontent.com/22112008/61433799-d661c200-a966-11e9-81f2-a1a45384b526.png)

### Steps to reproduce
直接看图，左边个就是，右边是svg做的，把背景变黑就会出现。

### What is expected?
高清无锯齿

### What is actually happening?
有锯齿

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | react |
| System | win10 |
| Browser | Chrome 版本 75.0.3770.90（正式版本） （64 位） |

**Comment by RanQiwu** [comment]
[官网](https://ant.design/components/progress-cn/) 的把背景变黑也有锯齿。

![image](https://user-images.githubusercontent.com/22112008/61434222-f6de4c00-a967-11e9-8870-60629db9c6b3.png)

**Comment by zombieJ** [comment]
Circle 是背景圈+进度圈，看起来像是渲染问题导致后面的背景圈透出来了一点点边。

**Comment by RanQiwu** [comment]
是的，有对比才会有伤害，有锯齿档次就掉下来了。
![image](https://user-images.githubusercontent.com/22112008/61435273-b207e480-a96a-11e9-9f7e-6cea86d54cbe.png)

**Comment by RanQiwu** [comment]
把第一个轨迹的颜色改改可以掩饰一下下。
![image](https://user-images.githubusercontent.com/22112008/61435896-2b540700-a96c-11e9-9020-5fec5f2dd9dc.png)

**Comment by muzea** [comment]
我这里还挺圆润的
![image](https://user-images.githubusercontent.com/7843281/61681276-793b8700-ad3f-11e9-8a1b-c96db233e657.png)

话说画圆没必要搞两笔吧，我现在是这样画的，M+a就完事了
https://codesandbox.io/s/goofy-thunder-hgbms

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35433
