### ISSUE TITLE
Table rowSelection select all bug

### ISSUE THREAD

**Issue by hanqizheng** [ant-design/ant-design#17704]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/hanqizheng/antd-issue-demo](https://github.com/hanqizheng/antd-issue-demo)

### Reproduction Picture
![](https://github.com/hanqizheng/antd-issue-demo/blob/master/src/public/issue.png?raw=true)

### Steps to reproduce
```
npm run start
```
然后点击表格中对应的`rowSelection`的全选，会发现被disable掉的row也被选中了

When you run this demo, you'll find a simple table at localhost:3000. Then the only one thing you need to do is click the `selectAll button` at the table header.

You 'll see the row which is disabled is checked!

### What is expected?
希望是全选按钮会跳过disable的row，只会选择没有disable的row

I hope the select all button can ignore the row witch was disabled.

### What is actually happening?
如果整个表格有4行是没有被disable的，那么全选就会选择表格的前四行`包括这前四行中有被disable的`

the row which is disabled is checked!

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
You miss `rowKey`: https://codesandbox.io/s/confident-rgb-fdyw8

**Comment by hanqizheng** [comment]
> You miss `rowKey`: https://codesandbox.io/s/confident-rgb-fdyw8

谢谢！
Thank you so much!
