### ISSUE TITLE
Transfer组件开启懒加载后更新dataSource后的渲染问题

### ISSUE THREAD

**Issue by andyyxw** [ant-design/ant-design#17716]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lively-fire-k1uzc)

### Steps to reproduce
开启了懒加载功能，手动过滤掉 dataSource 的前半部分，再更新 dataSource

### What is expected?
能正常显示数据

### What is actually happening?
后面部分的数据无法正常显示，内容区域空白，但是有滚动条，拖动一下滚动条，就显示出来了

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.8.4 |
| System | windows10 |
| Browser | Google Chrome 74.0.3729.131 |

---
开启懒加载后的渲染问题，请问有什么好的解决办法吗

**Comment by chengshaohui** [comment]
如果没有升级到v3版本，在v2版本有什么好办法强制刷新吗？
