### ISSUE TITLE
在使用Tree组件 的 checkable 和 checkStrictly 属性后，  halfChecked 出现问题

### ISSUE THREAD

**Issue by Chechengyi** [ant-design/ant-design#17712]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#header](https://ant.design/components/tree-cn/#header)

### Steps to reproduce
使用`Tree`组件做 权限菜单时，  设置 `Tree` 组件的 `checkable` 、和 `checkedKeys` 属性。  选中子节点， 在 `onCheck` 方法中观察参数。

### What is expected?
根据官方文档说明， 在设置 `checkable` 和 `checkedKeys` 属性后， 会提供一个 `checked` 属性 和 `halfChecked` 属性。   `checked`属性是当前选中的节点，  `halfChecked` 属性是 选中子节点的所有祖先节点。   期望在选中子节点后能给到祖先节点， 如下：
```
{
   checked: ["1102"],
   halfChecked: ["1100", "1000"]
}
```

### What is actually happening?
选中子节点没有给到 祖先节点
{
   checked: ["1102"],
   halfChecked: []
}

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | 16.8.6 |
| System | windows |
| Browser | chrom |

**Comment by zombieJ** [comment]
文档里说的是如果你用了 `checkStrictly`，你可以用 `halfChecked` 来设置节点的半选状态。你原本就没有提供 `halfChecked` 的话，触发的事件也不会有 `halfChecked`。

**Comment by superhuai** [comment]
楼主最后解决这个问题了吗？我也碰到这个问题，想UI层面更好的展示，似乎需要依赖组件 回传 halfchecked 的键值。不过 当不设置 `checkStricktly`  有不能实现 父子节点解绑的问题
