### ISSUE TITLE
时间轴里样式问题

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#17726]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在时间轴能否满足时间在左边内容在右边

### What does the proposed API look like?
时间轴的时间在左侧，显示内容在右侧。
![image](https://user-images.githubusercontent.com/48147837/61504906-a91d1e80-aa0f-11e9-9cad-9e7407fef833.png)

**Comment by wangluludehao** [comment]
Timeline是否能够实现左右都能添加呢？

**Comment by afc163** [comment]
https://ant.design/components/timeline-cn/#components-timeline-demo-label

https://github.com/ant-design/ant-design/pull/21560

已经支持。
