### ISSUE TITLE
The input box in Search and Select Users options can't get focus  搜索用户的选项中嵌入的输入框无法聚焦

### ISSUE THREAD

**Issue by Combo819** [ant-design/ant-design#17723]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-auto-complete-fjdtz)

### Steps to reproduce
type in anything in the Select box, when the dropdown shows up, click any of the input boxes. 
在选择器里输入任意文本，当下拉框出现时，点击任意一个选项中的输入框

### What is expected?
The input box in option gets focus.
小输入框能聚焦

### What is actually happening?
The input box in options can't get focus. User can't type in anything in the input box. That means the focus can only in Select.
小输入框不能聚焦，用户无法输入文本，强制聚焦在选择器上

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.8.6 |
| System | win10 |
| Browser | Chrome 75 |

---
developing a feature that user can add a description to the option
开发着客户可以为选中的选项添加描述的功能

**Comment by bachchanvinh** [comment]
Is this bug solved ?

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-auto-complete-forked-slq2kr?file=/index.js

**Comment by bachchanvinh** [comment]
> https://codesandbox.io/s/antd-auto-complete-forked-slq2kr?file=/index.js

It works, many thank for you
