### ISSUE TITLE
Table组件传入的columns数组设置key=0时，渲染后会自动变为key=1，造成key重复

### ISSUE THREAD

**Issue by hujinbo** [ant-design/ant-design#17721]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rzncv?fontsize=14)

### Steps to reproduce
1. Table组件传入的columns数组的第2个对象设置`key: 0`；
2. 渲染后TableCell标签里面变为key="1"，与第3个对象的`key: 1`重复。

代码如下：
```javascript
const dataSource = [
  {
    key: '1',
    seqNo: '1',
    0: '胡彦斌',
    1: 32,
    2: '西湖区湖底公园1号',
  },
  {
    key: '2',
    seqNo: '2',
    0: '胡彦祖',
    1: 42,
    2: '西湖区湖底公园1号',
  },
];

const columns = [
  {
    title: '序号',
    dataIndex: 'seqNo',
    key: 'seqNo',
  },
  {
    title: '姓名',
    dataIndex: 0,
    key: 0,
  },
  {
    title: '年龄',
    dataIndex: 1,
    key: 1,
  },
  {
    title: '住址',
    dataIndex: 2,
    key: 2,
  },
];

<Table dataSource={dataSource} columns={columns} />
```

### What is expected?
key能被正常设置，且不会产生警告信息

### What is actually happening?
1. 使用React Developer Tools查看key值，发现`{title:'姓名',dataIndex:0,key:0,}`对应的渲染后标签为`<TableCell key="1" ...`
2. F12查看控制台有警告信息：Warning: Encountered two children with the same key, `1`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | Windows 10 专业版 |
| Browser | Chrome 75.0.3770.90 |

**Comment by afc163** [comment]
key should be `string`.
