### ISSUE TITLE
antd 3.20.3 版本 Cascader 组件 当option选项的children字段为null时，组件异常

### ISSUE THREAD

**Issue by wyaihy** [ant-design/ant-design#17735]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-dpnep)

### Steps to reproduce
当option选项的children为undefined或[ ]都正常，为null就不行

### What is expected?
对option的children判断支持null值判断

### What is actually happening?
不支持children为null

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.9.0 |
| System | win 10 |
| Browser | Google Chrome 73.0.3683.86 |

---
当与后台交互子节点没有时会是null，希望当option里的children为null时组件能正常运行

**Comment by ztplz** [comment]
https://github.com/ant-design/ant-design/commit/a614b54c286d34ec2e74b3450195705157b6b3ed#commitcomment-34335862
@zombieJ 或者加个null类型？

**Comment by afc163** [comment]
1. 保持向下兼容。
2. 类型就不改了，null 没啥意义。
