### ISSUE TITLE
Select combobox 模式下，optionLabelProp设置是无效，请更新文档

### ISSUE THREAD

**Issue by jzlxiaohei** [ant-design/ant-design#1773]
```javascript
       //我直接用的dist版本
       if (combobox) {
	      notFoundContent = null;
	      // children 带 dom 结构时，无法填入输入框
	      optionLabelProp = 'value';
	    }
```
有这样段代码，也就是 `combobox` 模式下，`optionLabelProp`设置无效的，文档应该更新下

另外这样处理太粗暴了，这样的话 combobox的用处实在太有限了

antd能否加个`version`字段，我去官网上看没问题，首先想到的是，是不是版本和官网不一样，但是很难判断。

**Comment by afc163** [comment]
感谢反馈。

**Comment by renaesop** [comment]
fixed之后，貌似并没有改掉显示效果。因为combobox的渲染方式，看起来和非combobox很不一样
