### ISSUE TITLE
Table expandedRowRender

### ISSUE THREAD

**Issue by nibiru2O12** [ant-design/ant-design#17737]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hb9zs?fontsize=14)

### Steps to reproduce
Create a table with aleast 5 columns. Set the width of first column to 150 then fixed props to "left"

### What is expected?
component render to expandedRow will consume the width of the entire row.

### What is actually happening?
the component rendered on expandedRow only renders within the specified width of the first column.

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | React 16.8.6 |
| System | Windows 7 64 bit |
| Browser | Google Chrome Version 75.0.3770.142 (Official Build) (64-bit) |

**Comment by nibiru2O12** [comment]
tweaked the styling to remove on extra row on fixed column

`
{
    .ant-table-fixed-left {
      .ant-table-tbody {
        .ant-table-expanded-row {
          display: none;
        }
      }
    }
  }
`

**Comment by afc163** [comment]
Your codesandbox is empty.

**Comment by nibiru2O12** [comment]
i have updated the link please try again.
Failed to notice it earlier, the console throws a warning:

> Warning: [antd: Table] `expandedRowRender` and `Column.fixed` are not compatible. Please use one of them at one time.

then there's no way using the to props together?

**Comment by afc163** [comment]
Right, like the console message described.

**Comment by nibiru2O12** [comment]
ok thanks.

**Comment by yeter-yavan** [comment]
I have a same problem on antdv version 1. Still no solution?
