### ISSUE TITLE
Avatar 组件支持 responsive 的写法 

### ISSUE THREAD

**Issue by patrickmao93** [ant-design/ant-design#17738]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有时我们希望在不同屏幕尺寸上显示不同大小的 Avatar

### What does the proposed API look like?
<Avatar size={{sm: 26, lg: 46, xl: 64}} />

**Comment by vvitto** [comment]
I will do it.

**Comment by willamesoares** [comment]
Hi all, I see the PR for this issue was closed, not sure why based on the comments in the PR BUT I'd like to take on this one. Is that okay?

**Comment by yoyo837** [comment]
> Hi all, I see the PR for this issue was closed, not sure why based on the comments in the PR but I'd like to take on this one. Is that okay?

PR welcome
