### ISSUE TITLE
RangePicker 添加单面板选择功能

### ISSUE THREAD

**Issue by tonyzhou1890** [ant-design/ant-design#17730]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决日期范围不需要跨月的问题。

目前的 RangePicker 选择日期的面板是分为左右两部分的，但有的需求是要求不能跨月选择，虽然可以用两个 DataPicker 实现，但并不优雅。所以，希望官方有可能的话还是增加一个单面板日期范围选择的功能。

### What does the proposed API look like?
比如增加一个`single`或者`singlePanel`这样的属性，布尔值，默认`false`。
```
import { DatePicker } from 'antd';

const { RangePicker } = DatePicker;

ReactDOM.render(
  <div>
    <RangePicker single={true} />
  </div>,
  mountNode,
);
```

**Comment by afc163** [comment]
抱歉，暂无计划。

**Comment by VeejaLiu** [comment]
@afc163 
请问为什么暂无这样的计划？能阐述一下原因么？
