### ISSUE TITLE
New Mentions component autosize

### ISSUE THREAD

**Issue by ergenekonyigit** [ant-design/ant-design#17746]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-u3uv5)

### Steps to reproduce
- import Mentions and Input
- add autosize prop both of

### What is expected?
autosize work for Mentions

### What is actually happening?
autosize doesn't work for Mentions

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | 16.3.2 |
| System | macOS 10.14.5 |
| Browser | Chrome 75 |

---
Mentions component using textarea for input, it should autoresize

**Comment by afc163** [comment]
Mentions don't support `autoSize` now.

**Comment by orlandovallejos** [comment]
This is something I've been looking forward too!
It'd be nice also to have the same events we have in the Input.Textarea, specifically I need to execute an event when the user presses CMD + ENTER for example.

With these 2 features the Mentions component would be more complete 💪

**Comment by haohaitao** [comment]
I also encountered this problem

**Comment by Kermit-Xuan** [comment]
@afc163 I have add autoSize feature for `rc-mentions` with [PR](https://github.com/react-component/mentions/pull/20) following textarea component.

**Comment by Kermit-Xuan** [comment]
In progress?

**Comment by Kermit-Xuan** [comment]
@afc163 这个功能还做么？

**Comment by afc163** [comment]
@Kermit-Xuan 做。

**Comment by Kermit-Xuan** [comment]
OK，那我就按照textarea的方式来做吧。

**Comment by Kermit-Xuan** [comment]
这个是不是可以关掉了？
