### ISSUE TITLE
Modal中使用Tabs在Chrome中会出现闪烁

### ISSUE THREAD

**Issue by xuzhanhh** [ant-design/ant-design#17744]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-snow-gxrdt)

### Steps to reproduce
进入可看，在showModal的时候modal中的tabs会出现闪烁

### What is expected?
不引起闪烁

### What is actually happening?
出现闪烁

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | latest |
| System | macos 14 |
| Browser | Chrome 75.0.3770.142 |

---
tabs出现fps不足的情况引起闪烁，在safari和firefox上无问题

**Comment by stoutcat** [comment]
mark

**Comment by jljsj33** [comment]
可以自已在 TabPane 上加 style={{ willChange: 'transform' }}。。。modal 有缩放的动画，所以会导航内容闪烁。

**Comment by jljsj33** [comment]
能解决问题就关掉 issues 了哦，，这个是浏览器的问题，，所以我们组件上不会去更改东西。。

**Comment by GrinZero** [comment]
嘴巴真硬
