### ISSUE TITLE
treeSelect通过搜索出来的符合条件的项,选中某个时如何不让treeData重新洗牌,还保留搜索的结果

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#1776]

**Comment by superRaytin** [comment]
能否做个判断或加个配置？搜索后选取结果，不重新渲染搜索结果，只渲染已选中的。@afc163 @warmhug

**Comment by warmhug** [comment]
rc-tree-select@1.7.1 升级后自动支持，API兼容以前，表现上有变化、搜索后保留搜索条件和结果。
@superRaytin 可在 antd 的 bugfix版本升级时升级下。
