### ISSUE TITLE
New Component Badge.Ribbon

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#17768]
<img width="522" alt="图片" src="https://user-images.githubusercontent.com/507615/61590392-1fc24380-abeb-11e9-9b1e-ff73ec9f3297.png">

```jsx
<Badge.Ribbon text="首年享受优惠">
  <Card />
</Badge.Ribbon>
```

**Comment by orzyyyy** [comment]
What about this?

![image](https://user-images.githubusercontent.com/24520193/63026772-5899c380-bede-11e9-9ad5-3a5aa051b668.png)

**Comment by keithort** [comment]
@orzyyyy That seems more like a candidate for a blockquote-like component, not really related to a Badge.

@afc163 This looks useful. I think it would need to support a few additional props: 
- Size (Small, Middle, Large)
- Status/Type (Like regular Badge)
- Position (left or right)
- Icon (Similar to the support in Button)
- Color (Like regular Badge with some sensible preset options)
Just a few ideas.

**Comment by faradaytrs** [comment]
I wish this could get more attention

**Comment by hairarrow** [comment]
@afc163 I just started working on this.

I have the core css written for the feature, but I'm adding support for the props @keithort mentioned.

[Here's what it looks like so far:](https://github.com/ant-design/ant-design/compare/feature...hairarrow:feature)

<img width="174" alt="Screen Shot 2019-10-11 at 7 26 54 PM" src="https://user-images.githubusercontent.com/4682445/66693462-ce5fa880-ec5d-11e9-91b0-58e8dcf72791.png">

**Comment by faradaytrs** [comment]
@hairarrow are you still working on it?
