### ISSUE TITLE
setFieldsValue() not working if input contains some value  after using {getFieldDecorator('lastName', {   trigger: 'onBlur',   valuePropName: 'defaultValue',..

### ISSUE THREAD

**Issue by gauravchaware** [ant-design/ant-design#17766]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-mr8nu)

### Steps to reproduce
1) Enter some value in input 2  
2) Click button set value

### What is expected?
Input 1 value should be changed to a value from input 2

### What is actually happening?
Input 1 value not updating by logical update using  this.props.form.setFieldsValue({ input1: values.input2 });

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8 |
| System | all |
| Browser | all |

---
reference to https://github.com/ant-design/ant-design/issues/13063 
for the complex form to avoid slowness I used trigger: "onBlur"

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically.

**Comment by gauravchaware** [comment]
Finally, I am going to face a performance issue then, I already divided fields in multiple forms hope anyone can address this issue

**Comment by annjawn** [comment]
This is actually an annoying issue which makes the entire `getFieldDecorator` useless. It has massive performance issues and the `onBlur` and `valuePropName` workaround clearly breaks functions like `resetFields`. I have been trying to use resetFields now for hours and couldn't make it work simply because i used the `valuePropName`.
