### ISSUE TITLE
Tabs keep jumping when there are too many object in tabBarExtraContent

### ISSUE THREAD

**Issue by nvoisin** [ant-design/ant-design#17762]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-keller-dq2je)

### Steps to reproduce
Reduce window size and you'll see the tabs moving up and down.

### What is expected?
No moving.

### What is actually happening?
Tabs are moving up and down.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Version 75.0.3770.142 (Official Build) (64-bit) |

**Comment by nvoisin** [comment]
Any progress ?

**Comment by Yangzhedi** [comment]
you can add `width: xxx` onto `ant-tabs-extra-content` to limit extra width

**Comment by nvoisin** [comment]
This won't solve the problem - eventually at some specific width, the tabs will start jumping back and forth.

**Comment by zombieJ** [comment]
Hi @nvoisin , do you have interested to dig in?

**Comment by nvoisin** [comment]
I'm not sure I'm the right person for the job, but I'll look into it when I can.

**Comment by rafaelncarvalho** [comment]
Any news about this issue?

**Comment by zomars** [comment]
I'm having this exact issue.

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by zombieJ** [comment]
@Kermit-Xuan , hold since we will rewrite Tabs using flex layout which may resolve this.

ref: https://github.com/react-component/tabs/pull/265

**Comment by Kermit-Xuan** [comment]
OK
