### ISSUE TITLE
Combogrid (select show table layout for selection instead of just list)

### ISSUE THREAD

**Issue by geoffreylzf** [ant-design/ant-design#17769]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
To let the user to view more detail of each select option (instead of just 1 word)

### What does the proposed API look like?
```
ReactDOM.render(
  <div>
    <ComboGrid defaultValue="lucy" style={{ width: 120 }} onChange={handleChange}  headerRender={header=> (
      <div>
         <Column>Name</Column>
         <Column>Birthdate</Column>
         <Column>Gender</Column>
      </div>
    )}>
      <Option value="jack">
         <Column>Jack</Column>
         <Column>1990-02-21</Column>
         <Column>Male</Column>
      </Option>
      <Option value="lucy">
          <Column>Lucy</Column>
         <Column>1990-02-28</Column>
         <Column>Female</Column>
      </Option>
    </ComboGrid >
  </div>,
  mountNode,
);
```

**Comment by afc163** [comment]
https://ant.design/components/descriptions/

**Comment by geoffreylzf** [comment]
That is not the thing I imagine, for example pls refer below link

https://www.jeasyui.com/demo-vue/main/index.php?plugin=ComboGrid&theme=material-teal&dir=ltr&pitem=&sort=asc

**Comment by zombieJ** [comment]
Select support `dropdownRender`. You can use it to customize.
