### ISSUE TITLE
antd throw error when I use Babel7.x & core-js@3.x

### ISSUE THREAD

**Issue by jkiss** [ant-design/ant-design#17765]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jkiss/Antd-Bug](https://github.com/jkiss/Antd-Bug)

### Steps to reproduce
npm i && npm run dev && open url in broswer, then open console, you will see the error

### What is expected?
No errors in console. Show Slider component.

### What is actually happening?
Uncaught TypeError: Cannot read property 'assign' of undefined

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.1 |
| System | Mac OS 10.14.5 |
| Browser | Chrome 75 |

---
babel-runtime is outdate, should use @babel/runtime

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16852#issuecomment-499828630

**Comment by jkiss** [comment]
I don't think I have a wrong webpack config... I advice you can upgrade babel-runtime into @babel/runtime at v4 @afc163

**Comment by afc163** [comment]
That is strange issue.

**Comment by afc163** [comment]
https://github.com/jkiss/Antd-Bug/pull/1/

**Comment by jkiss** [comment]
It works!!! Thanks a lot, it's really hard to debug this......Regular Expression is difficult 😭
