### ISSUE TITLE
Table resets pagination current on sort/filter

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#17770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-table-pagination-bug-je62d)

### Steps to reproduce
open console (output comes from "onChange" handler)
1. go to 2nd page (see "current: 2" in console)
2. click any sorting (see "current: 1" in console, but pagination button and table remains on 2-nd page)

### What is expected?
Expected receive real current page in onChange handler

### What is actually happening?
Any sort or filter change resets current page in onChange handler to 1.

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8 |
| System | ubuntu, windows |
| Browser | chrome 75 |

---
It makes real problems when I use that pagination parameters in my state and return them back to the table as pagination prop. In this case page finally resets to 1 (also visually) on each sort/filter change

**Comment by zombieJ** [comment]
It's by design. #16978

**Comment by afc163** [comment]
It is by designed, check https://github.com/ant-design/ant-design/issues/16978

**Comment by urrri** [comment]
1. What can be "by design" in inconsistency?
Real page remains the same, just onUpdate receives different value.
2. Why you decide to reset selected page?
It should be done by user flag or in the onUpdate handler.
Is there any flag for it?
3. User can decide to sort inside the current page (not whole list). 
In this case that jump to 1 page looks idiotically.

**Comment by machao1990** [comment]
this is a very very very idiotically design.

**Comment by DreFalPoetry** [comment]
可以自己选择是否回到第一页为什么要在sort的时候current自己固定到第一页 这样有些困扰
