### ISSUE TITLE
关于 被 Form 组件 getFieldDecorator 包装过的 DatePicker.RangePicker 快捷输入时, 值丢失问题

### ISSUE THREAD

**Issue by raohong** [ant-design/ant-design#17779]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/34527p5m91?fontsize=14)

### Steps to reproduce
经过 Form 组件 getFieldDecorator 函数 包装过的 RangePicker.
点击 RangePicker , 在左边输入框输入日期 , 随后在右边输入结束日期 . 但是日期值被丢失.
是因为 没有响应 RangePicker 的 onCalendarChange 回调.

虽然可以通过 自己包装 RangePicker 来统一 onChange 回调 来避免这种情况 , 但是还是麻烦.
Form 组件 getFieldDecorator 函数 options.trigger 是否考虑支持 字符串数组 , 可能出现多个数据来源

### What is expected?
值正确录入

### What is actually happening?
值丢失

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8 |
| System | windows |
| Browser | chrome |

**Comment by kanweiwei** [comment]
trigger: 'onCalendarChange' 改成这个之后，没法清除了，清除触发的是 onChange

**Comment by raohong** [comment]
> trigger: 'onCalendarChange' 改成这个之后，没法清除了，清除触发的是 onChange

我说的是 可以传多个 trigger

**Comment by kanweiwei** [comment]
> > trigger: 'onCalendarChange' 改成这个之后，没法清除了，清除触发的是 onChange
> 
> 我说的是 可以传多个 trigger

我知道，我只是说一下有这个现象

**Comment by afc163** [comment]
同样的问题：

- https://github.com/ant-design/ant-design-pro/issues/4929
- https://github.com/ant-design/ant-design/issues/15673

**Comment by senf824** [comment]
动态清除组件的日期就需要写value属性，但是写上value属性就导致手动输入时间不生效

**Comment by fengyun2** [comment]
请问这个问题现在有没有被解决了，年前被测试发现了这个bug

**Comment by afc163** [comment]
这个问题已经在 4.x 的 RangePicker 里解决了。

**Comment by kangzechong** [comment]
The antd version of my program is v3. How can I solve this problem without upgrading to V4?
