### ISSUE TITLE
我想问问 List.Item.Meta 里面的 description  太长 可以自动 ellipsis 吗

### ISSUE THREAD

**Issue by wzht1991** [ant-design/ant-design#17771]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当 description 太长的时候可以自动ellipsis  能是页面更加清晰和干净 可以设置超过多少行后ellipsis

### What does the proposed API look like?
可以设置超过多少行后ellipsis 有一个下来的按钮 点击了就能看隐藏内容

**Comment by afc163** [comment]
https://ant.design/components/typography-cn/#components-typography-demo-ellipsis
