### ISSUE TITLE
Form表单的Form.Item的htmlFor属性没生效，设置的和input的id属性不一致，还能聚焦，理论上应该不能

### ISSUE THREAD

**Issue by lynshir** [ant-design/ant-design#17774]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-fog-3mqfr)

### Steps to reproduce
上面链接的74行，随意添加一个`htmlFor`属性以后 ，点击文字input框**不应该**聚焦，因为我要实现的功能是label也要自定义，这样的话只要点击label就立马聚焦到input框。

### What is expected?
htmlFor属性和input的Id属性不一致时，点击label不应该聚焦到input

### What is actually happening?
聚焦了

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.8.6 |
| System | macos |
| Browser | 75.0.3770.100 |

**Comment by zombieJ** [comment]
3.0 的设计里点击 label 就会聚焦组件，`htmlFor` 是为了防止找不到才让用户自行设置 `id` 来对上。对于你的需求，你可以将 `label` 内的内容包在一个 div 里然后监听点击事件，来阻止冒泡。
