### ISSUE TITLE
Calendar日历中没有可以回显的公众节假日

### ISSUE THREAD

**Issue by sdeass** [ant-design/ant-design#17773]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Meanwhile solved the event of onClick which was the data，having public holiday
解决了日期添加事件，但是没有阴历和节假日的回显

### What does the proposed API look like?
Meanwhile solved the event of onClick which was the data，having public holiday
可以提供回显阴历和节假日的回显，且不影响点击事件

**Comment by zombieJ** [comment]
Use `dateRender` to customize date cell.

**Comment by sdeass** [comment]
Hi,


   Could you provide an example for me ?




--

祝你，万事如意！
          身体健康！
              步步高升！
                                                  

At 2019-07-22 15:55:32, "zombieJ" <notifications@github.com> wrote:


Use dateRender to customize date cell.
