### ISSUE TITLE
The itemRender of Pagination can't support rewrite pageSizeOption

### ISSUE THREAD

**Issue by mistyjae** [ant-design/ant-design#17782]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The page size option displays in "10/page", but sometimes we don't want to show the suffix of  " /page", the itemRender can support rewrite 'page' | 'prev' | 'next', maybe also can support pageSizeOption.....

### What does the proposed API look like?
itemRender:   (page, type: 'page' | 'prev' | 'next ' | 'pageSizeOption', originalElement) => React.ReactNode

**Comment by dgreene1** [comment]
I agree that it would have been better accomplished through the `itemRender` function, but instead it is accomplished via the [selectComponentClass](https://github.com/ant-design/ant-design/pull/32132/files#diff-989d3a79c107c968fba1e6ee99b14c896db4485b7dd7b8eb8c4a2050844435e9R68). Please note that I have suggested a more wholesale override functionality in https://github.com/ant-design/ant-design/issues/36660

**Comment by afc163** [comment]
Trace #17782
