### ISSUE TITLE
从3.12.3版本升级到3.19.0版本，我项目所有页面涉及到Modal对话框关闭的功能都关闭不了

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design#17785]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
antd Modal

### What is expected?
可以正常关闭弹窗

### What is actually happening?
不能关闭弹窗

| Environment | Info |
|---|---|
| antd | 3.19.0 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by dongkeng001** [comment]
可能我代码的原因，我再自己找找原因吧

**Comment by JIACHENG9** [comment]
react 15 modal cant not close

https://github.com/ant-design/ant-design/issues/17837
