### ISSUE TITLE
Stop Misusing of Arrow Functions in Documentation

### ISSUE THREAD

**Issue by fuweichin** [ant-design/ant-design#17789]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Arrow function differs from normal function in "this", ".bind", and lacks of "arguments", ".prototype",  I found that a lot of antd demos using arrow function like this:

```jsx
class Foo extends React.Component {
  constructor(props){
    super(props)
    this.handleClick=this.handleClick.bind(this) //it makes no sense to let a arrow function bind this
  }
  render(){
    return <img onClick={this.handleClick} />
  }
  handleClick=(e)=>{
    this.setState({x:0})   //the this here is equivalent to this in global  scope, not the instance
  }
}
```

Since JS transpiler like Babel transforms arrow functions into the ES5-compatible normal functions by default, errors wouldn't occur. But that doesn't mean we may continue copying and teaching code like this.

### What does the proposed API look like?
Based on the Foo example above, just remove the equal sign and the arrow from handleClick,

```
handleClick(e){
  this.setState({x:0}) 
}
```

Now it safe & clean.

**Comment by afc163** [comment]
PR is welcome, issue closed.
