### ISSUE TITLE
Upload Pictures Wall Drag To Order

### ISSUE THREAD

**Issue by canyanolGitHub** [ant-design/ant-design#17794]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Upload Pictures Wall Drag To Order

### What does the proposed API look like?
Upload Pictures Wall Drag To Order

**Comment by afc163** [comment]
Duplicate of #8387
