### ISSUE TITLE
Table sorting always "ascend"

### ISSUE THREAD

**Issue by SimonyanGrno** [ant-design/ant-design#17791]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-cache-9cc62)

### Steps to reproduce
Table sorting always ascend

### What is expected?
sorter.field must be "ascend", "descend", undefined

### What is actually happening?
In handleTableChange sorter.field always "ascend" when function calls this.setState. If comment this.setState all works fine 

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | React |
| System | Ubuntu 18.04.2 LTS |
| Browser | Version 75.0.3770.142 (Official Build) (64-bit) |

**Comment by afc163** [comment]
https://codesandbox.io/s/elegant-field-idtge

or

https://codesandbox.io/s/great-haibt-d3d0l

---

https://github.com/ant-design/ant-design/issues/12737#issuecomment-431548253
