### ISSUE TITLE
Changed Button with type="danger" behavior - broken existing UI

### ISSUE THREAD

**Issue by ivanjuric** [ant-design/ant-design#17790]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/button-danger-after-antd-3204-13exr)

### Steps to reproduce
Update to antd >= 3.20.4 (i.e 3.20.5 with ghost button fix)

On hover over button nothing happens. Before update, button was filled with red color on hover,

### What is expected?
https://codesandbox.io/s/button-danger-prior-to-antd-3204-q53k8

### What is actually happening?
There is no way to achieve previous Button danger behavior

| Environment | Info |
|---|---|
| antd | 3.20.4 |
| React | react 16.8.6 |
| System | Windows 10 |
| Browser | Firefox 68.0.1 |

**Comment by afc163** [comment]
It is by designed. You can lock version to 3.20.3 if you don't like new design.

**Comment by ivanjuric** [comment]
I like the new design, but it changed my UI unexpectedly. And locking to specific version is bad solution.
Such changes should not be in patch versions. And if they already are in patch version, then there should also exist possibility of retaining old behavior with as little as possible extra effort, such as "invert" option in this case or something similar.

Also, please change link to PR in release notes for 3.20.4 for english version:
"Tweak less variables and UI to improve style customization. #17705"
=> #17697
