### ISSUE TITLE
表格从服务端获取数据可以设置排序列

### ISSUE THREAD

**Issue by jeffxu** [ant-design/ant-design#17795]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当表格从服务端获取数据的情况下也可以设置默认的排序列，而不是等用户点了列之后才触发排序

### What does the proposed API look like?
期望和本地排序一样，传递sorter属性告诉组件哪些列（有可能多个列可以排序）已经排序过了（是按照哪个倒序还是正序排序）

**Comment by afc163** [comment]
`defaultSortOrder` or `sortOrder`

https://ant.design/components/table-cn/#components-table-demo-head

**Comment by jonny-xhl** [comment]
defaultSortOrder可以通过默认排序，若在该字段上使用了state值判断是否使用默认排序可以支持吗？我试了下好像不行。
