### ISSUE TITLE
<Menu.Item> 组件Bug

### ISSUE THREAD

**Issue by HuoXiaoYe** [ant-design/ant-design#17799]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/HuoXiaoYe/nodeReactChat/blob/master/src/component/home/honeIndex.js](https://github.com/HuoXiaoYe/nodeReactChat/blob/master/src/component/home/honeIndex.js)

### Steps to reproduce
```javascript
<Menu theme="dark" defaultSelectedKeys={[window.location.hash.slice(1)]} mode="inline">
                            <Menu.Item key="/home/all">
                                <Icon type="profile" />
                                <span><Link to="/home/all" style={{ color: "white" }}>全部说说</Link></span>
                            </Menu.Item>
                            <Menu.Item key="/home/my">
                                <Icon type="message" />
                                <span><Link to="/home/my" style={{ color: "white" }}>个人说说</Link></span>
                            </Menu.Item>
                            <Menu.Item key="/home/mine">
                                <Icon type="user" />
                               <span> <Link to="/home/mine" style={{ color: "white" }}> 个人中心 </Link></span>    
                                
                            </Menu.Item>
                        </Menu>
```

### What is expected?
在span标签中放置一个link,如果点击持续地过快点击三个link，会出现 路由界面不切换地问题，去掉span标签，只放置link,则link无样式，但是没有出现上述问题。。。。

### What is actually happening?
在span标签中放置一个link,如果点击持续地过快点击三个link，会出现 路由界面不切换地问题，去掉span标签，只放置link,则link无样式，但是没有出现上述问题。。。。

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | React |
| System | win10 |
| Browser | Google |

---
在span标签中放置一个link,如果点击持续地过快点击三个link，会出现 路由界面不切换地问题，去掉span标签，只放置link,则link无样式，但是没有出现上述问题。。。。

**Comment by HuoXiaoYe** [comment]
@afc163  https://github.com/HuoXiaoYe/nodeReactChat
这个仓库下的 src/component/home/honeIndex.js   line 36~50

**Comment by afc163** [comment]
Try this way:

```js
<Menu.Item key="/home/mine">
  <Link to="/home/mine">
    <Icon type="user" />
    <span>个人中心</span>    
  </Link>
</Menu.Item>
```

**Comment by HuoXiaoYe** [comment]
@afc163  把link放在外面就好了，非常感谢您的帮助。 这是不是因为我让 span 标签嵌套了a标签出现的额问题呢

**Comment by afc163** [comment]
具体没细看，看着这种嵌套用法比较奇怪。
