### ISSUE TITLE
upload 删除报错reqs[uid].abort is not a function

### ISSUE THREAD

**Issue by yylink0208** [ant-design/ant-design#17801]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-snow-9yow8?fontsize=14)

### Steps to reproduce
点击上传一张图片,然后点击删除

### What is expected?
希望能够删除图片

### What is actually happening?
报错Uncaught TypeError: reqs[uid].abort is not a function

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.6.3 |
| System | win10 |
| Browser | chrome 74.0.3729.131 |

---
希望可以得到帮助 谢谢

**Comment by afc163** [comment]
customRequest should implement `abort` method: https://github.com/react-component/upload/blob/d228dde5aa34acf0a811a9cf6ade3572ed37807b/src/request.js#L94

**Comment by afc163** [comment]
Reinstall node_modules.

**Comment by yylink0208** [comment]
thanks
