### ISSUE TITLE
Circular dependency: antd/lib/menu/index.js -> antd/lib/menu/MenuItem.js -> antd/lib/menu/index.js

### ISSUE THREAD

**Issue by phthhieu** [ant-design/ant-design#17803]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[N/A](http://not_available.com)

### Steps to reproduce
There is clearly a circular dependency in the code base following

antd/lib/menu/index.js -> antd/lib/menu/MenuItem.js -> antd/lib/menu/index.js

### What is expected?
There is no circular dependency in the files:
antd/lib/menu/index.js -> antd/lib/menu/MenuItem.js -> antd/lib/menu/index.js

### What is actually happening?
I'm using rollup to bunding my code with antd packages, the above circular dependency breaks my application code

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.6 |
| System | Mac OS 10.14 |
| Browser | Chrome 75 |

---
I can open a PR for this

**Comment by afc163** [comment]
PR is welcome~
