### ISSUE TITLE
Dynamically added TreeNodes in the root level of a TreeSelect has unexpected behavior while using Search

### ISSUE THREAD

**Issue by GitEmGud** [ant-design/ant-design#17807]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-mestorf-4mzg4)

### Steps to reproduce
If a function returns an array of JSX.Element that are of type TreeSelect.TreeNode, one of the side effects is Search not functioning properly.

### What is expected?
The results of the search should shrink the list in the TreeSelect

### What is actually happening?
The correct results of the search are turning bold but not shrinking the list.  The error in the console is as follows:

TypeError: node.props is undefined

in Select.js at line 496:
`
var nodeValue = String(node.props[treeNodeFilterProp]).toUpperCase();`

The reason for this is the array of TreeNode elements, while valid for populating the TreeSelect, do not have have the property "props".  There is no check for this property in the object before attempting to extract the value.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8 |
| System | Windows 7 |
| Browser | FireFox 67.0.4 (64 bit) |

---
if you remove line 63 in the reproducible, the search will operate as expected.

**Comment by GitEmGud** [comment]
I forgot to mention that dynamically added TreeNodes to a parent TreeNode do not exhibit this issue.  See line 59 in the code sandbox

**Comment by zombieJ** [comment]
What should I type in the search box to get the error?

**Comment by GitEmGud** [comment]
Anything will cause the error to happen in the browser but unfortunately the error does not show in the code sandbox.   If you look closely,  the behavior does differ from the norm




-------- Original message --------

**Comment by afc163** [comment]
Nothing we can do if we can't reproduce it.

**Comment by GitEmGud** [comment]
You can reproduce the issue without getting an error in the console on codesandbox page, however the browser console should show an error.


1)      Note that when you type ‘my’ into the search box. The results from the search do not shrink, but only “my leaf” becomes bold in the list

2)      Delete line 63 from the code

3)      Now type ‘my’ into the search box.  The results of the search will shrink only showing the hierarchy “parent 1”, “parent 1-0”, and “my leaf”

I can see an error in the chrome browser console when I test it on the page https://codesandbox.io/s/suspicious-mestorf-4mzg4 but not on the codesandbox.io page.  I don’t understand why this is other than perhaps a deficiency in codesandbox.io.  This is the error I see in the browser console:

[cid:image001.png@01D54123.42EDF710]

**Comment by zombieJ** [comment]
TreeSelect only accept children as TreeNode. Your render is [TreeNode, Array<TreeNode>] which is not correct children. You should flatten it: https://codesandbox.io/s/young-https-g0ekr

**Comment by GitEmGud** [comment]
Thanks for a workaround to the bug, though it is a rather awkward one.

I don't understand the "Usage" tag however, something probably got lost in translation.  This was a bug report in which certain components behave fine in one circumstance, but unexpectedly in another.

In any case, thanks again for the workaround
