### ISSUE TITLE
Steps support Steps.Nav

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design#17814]
### What problem does this feature solve?

Steps support new style and activeIndex

![image](https://user-images.githubusercontent.com/1061968/61681843-bdc82200-ad41-11e9-9bac-e493519fc5bf.png)

### What does the proposed API look like?
Add `Steps.Nav` with new props `activeIndex` `defaultActiveIndex` `onActiveIndexChange`.

`Steps.Step` add new prop `progress`: 0 ~ 100(%).

```jsx
<Steps.Nav current={1} activeIndex={0}>
    <Step title="Finished" subTitle="xxxx" description="This is a description." />
    <Step title="In Progress" description="This is a description." progress={30}/>
    <Step title="Waiting" description="This is a description." />
</Steps.Nav>
```

**Comment by afc163** [comment]
<img width="65" alt="image" src="https://user-images.githubusercontent.com/507615/61681913-fff16380-ad41-11e9-961c-efcff93ad260.png">

还有个这个。

**Comment by yutingzhao1991** [comment]
再加一个 `subTitle`。

**Comment by zombieJ** [comment]
这个是不是可以直接作为 `chilren`?

**Comment by yutingzhao1991** [comment]
> 这个是不是可以直接作为 children?

这个是什么意思？subTitle 吗？感觉语义不太对，children 给人一种下面内容区的感觉。

**Comment by zombieJ** [comment]
> > 这个是不是可以直接作为 children?
> 
> 这个是什么意思？subTitle 吗？感觉语义不太对，children 给人一种下面内容区的感觉。

删掉了，我那个说的不对。

**Comment by yutingzhao1991** [comment]
API 调整了下，只要 rc-steps 的 dom 结构稍微改一下通过样式调整就能实现。所以只要加一个 `type=nav` 就可以，其它和原来的 steps 保持一致。

**Comment by yutingzhao1991** [comment]
还有一些 feature 后面再提 PR 实现：

- [ ] 支持进度
- [ ] 支持 subTitle
- [ ] 支持 disabled（不可点击触发 onChange）

**Comment by afc163** [comment]
看上去进度没有需求了，closed。
