### ISSUE TITLE
关于row-flex-space-between的显示问题

### ISSUE THREAD

**Issue by cagen** [ant-design/ant-design#1781]
类似于这个问题 #257
在[官网](http://ant.design/#/components/layout?scrollTo=components-layout-demo-flex)上使用row-flex-space-between的等宽排列显示效果好像还是不太正确

好像是因为伪类元素的影响：
![image](https://cloud.githubusercontent.com/assets/5174809/15392270/9075bac8-1df8-11e6-9bd5-4d4fed5214ae.png)
结果是伪类元素靠在了整个row的两端，所以出现了官网的显示效果

**Comment by emodo** [comment]
我也发现这个问题了，后来借鉴了[https://material.angularjs.org/latest/layout/alignment](Angular Material) 写了一套没有用`Row`

**Comment by afc163** [comment]
感谢反馈。
