### ISSUE TITLE
BreadcrumbItem的separator被父组件覆盖

### ISSUE THREAD

**Issue by long-zhuge** [ant-design/ant-design#17812]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/y372km8o4z)

### Steps to reproduce
在 Breadcrumb.Item 上写入 separator 属性后，并不生效。

### What is expected?
Breadcrumb.Item 的 separator 不被父组件覆盖。

### What is actually happening?
始终显示的是父组件的 separator。

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.5.2 |
| System | macOs |
| Browser | chrome |

---
在源代码 Breadcrumb.tsx 文件的第 150 行中，父组件的 separator 覆盖了子组件的属性。

**Comment by afc163** [comment]
应该是文档写错了，Breadcrumb.Item 不应该支持 `separator`。

**Comment by long-zhuge** [comment]
@afc163 

但是有些业务场景下需要 Item 也支持独立的 separator。

```
// 比如需要显示
当前位置：xxx > xxx >
```
我现在在本地通过给 Item 添加一个新的属性 `separatorItem` 来解决这样的问题。希望官方也能支持到。

![image](https://user-images.githubusercontent.com/14194437/61680421-198fac80-ad3c-11e9-903f-d1a544c495e0.png)

**Comment by afc163** [comment]
可以来个 `Breadcrumb.Separator`。

```jsx
<Breadcrumb separator="">  // 去掉分隔符
  <Breadcrumb.Item />
  <Breadcrumb.Separator />  // 默认分隔符
  <Breadcrumb.Item />
  <Breadcrumb.Separator>:</Breadcrumb.Separator> // 自定义分隔符
  <Breadcrumb.Item />
</Breadcrumb>
```

按这样的 API 来个 PR 如何？发到 `feature` 分支。

**Comment by long-zhuge** [comment]
@afc163  看下这个 PR 是什么问题，是需要你们 review 后才会合并吗？feature 分支上
[#17873](https://github.com/ant-design/ant-design/pull/17873)

**Comment by zombieJ** [comment]
@long-zhuge ，点开 CI 的信息，里面有错误描述的。
