### ISSUE TITLE
Input suffix overlap with text when suffix is too long

### ISSUE THREAD

**Issue by andyyxw** [ant-design/ant-design#17811]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 `Input` 的 `suffix` 中加入了自定义的内容，比如字数显示 100/100，它的宽度是动态变化的，所以希望 `input` 的 `padding` 也是动态可控的，这样这个功能就能做成公用的，否则只能在每次使用的时候用css控制，而且好像只能写死 交互不好。
目前 `style` 属性传入的样式放在了 `ant-input-affix-wrapper` 上。

### What does the proposed API look like?
希望提供个属性，比如 `<Input inputStyle={{ paddingRight: 50 }} />`

**Comment by afc163** [comment]
@zombieJ speak to the devil 😀

**Comment by zombieJ** [comment]
用 css select 调整 padding，间距应该由 Input 来控制，inputStyle 暴露有点多了。我们 4.0 里可以调整一下成 flex 布局来自适应。

**Comment by andyyxw** [comment]
> 用 css select 调整 padding，间距应该由 Input 来控制，inputStyle 暴露有点多了。我们 4.0 里可以调整一下成 flex 布局来自适应。

目前可以自适应控制padding吗，只用 css ？
还有，flex 兼容不了 ie9 呀

**Comment by zombieJ** [comment]
设置的稍微大一点，v4 只支持 IE 11+ 所以可以用 flex 布局。

**Comment by ztplz** [comment]
flex好啊  我flex一把梭

**Comment by ops1ops** [comment]
Guys maybe speak English so everyone being redirected to this page could understand?

**Comment by afc163** [comment]
@zombieJ Any plan to put this in 4.0?

**Comment by afc163** [comment]
Already resolved in v4, `flex` is the solution.
