### ISSUE TITLE
DatePicker添加可取指定区间的日期

### ISSUE THREAD

**Issue by CTheMyth** [ant-design/ant-design#17825]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以限定一个可选的日期区间

### What does the proposed API look like?
例如，disabledDate=current=>current<moment('2019-7-1') && current>moment('2019-7-31')时，就只能选择2019年7月份的日期，

**Comment by afc163** [comment]
Already supported: https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date

**Comment by CTheMyth** [comment]
我的意思是实现单个的DatePicker 组件能限制在一个日期区间内选值，而不是只能用一个日期点分隔能选和不能选。不使用RangePicker 组件

**Comment by CTheMyth** [comment]
> Already supported: https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date



> Already supported: https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date

我的意思是实现单个的DatePicker 组件能限制在一个日期区间内选值，而不是只能用一个日期点分隔能选和不能选。不使用RangePicker 组件
