### ISSUE TITLE
Form (Input) with "prefix" prop does not provide events

### ISSUE THREAD

**Issue by aarifkhamdi** [ant-design/ant-design#17821]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-bird-dnrto?fontsize=14)

### Steps to reproduce
Just look to console output

### What is expected?
test1 field has value "test1"

test2 field has value "test2"

### What is actually happening?
test1 field has value "undefined"

test2 field has value "test2"

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
```diff
- app.find("Input#test1").simulate("change", { target: { value: "test1" } });
- app.find("Input#test2").simulate("change", { target: { value: "test2" } });
+ app.find("Input #test1").simulate("change", { target: { value: "test1" } });
+ app.find("Input #test2").simulate("change", { target: { value: "test2" } });
```

**Comment by aarifkhamdi** [comment]
yes, it works.
but i think it should work or should NOT work in both cases

eg
Input#test1 - work
Input#test2 - work

or 

Input#test1 - not work
Input#test2 - not work

actually:
Input#test1 - work
Input#test2 - not work
