### ISSUE TITLE
<Select> 的 defaultValue 可以动态赋值嘛？

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#1782]
考虑这样的场景，有一个列表是动态获取的，数据结构如下：
```
[
	{
		code: '',
		name: ''
	}
	...
]
```

然后事先会知道一个被选中的 code（比如说，这个 code 是从浏览器上获取的），但是不知道 name，当列表获取完成后，再根据 code 获取对应的 name，然后赋值给 `defaultValue`

**Comment by ystarlongzi** [comment]
貌似当 `defaultValue `事先赋值，但 `<Option>` 动态加载后，也是无法展示正确的选项内容。

**Comment by dreamcatcher081210** [comment]
use initialValue

**Comment by dreamcatcher081210** [comment]
在getFieldProps方法里设置 initalValue

**Comment by benjycui** [comment]
Or: https://github.com/ant-design/ant-design/wiki/FAQ#it-doesnt-work-when-i-change-defaultvalue-dynamically

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by ystarlongzi** [comment]
@dreamcatcher081210 
谢谢。
设置 getFieldProps 的 initalValue 方案不可行


@benjycui 
谢谢。

根据你的链接，让我对 `defaultValue` 的理解又加深了。但是我问题的最终根源是如果 `<Option>` 动态添加了，那要怎么根据事先的值选中呢？

考虑一个 `<select>` html 元素，如果事先指定了选中的值，然后后期动态添加了 `<option>`，那此时 `<select>` 也不会选中(显示)到指定的 `<option>`，但是可以通过 DOM 方法选中(显示)指定的 `<option>` 或者在遍历 `<option>` 时动态添加属性 `selected` 都可以实现，但是 `ant-design <Select>` 有对方暴露方法或者其他方式可以实现嘛？

还有为自己辩解『关于`提问的智慧`』，我在 `antd-design` 和 `rc-select` 都有搜索过看有人遇到同样的问题没，但是无果，然后粗略看了下 `rc-select` 源码，也没找到对应的线索，所以新开了个 issue。

**Comment by benjycui** [comment]
> 还有为自己辩解『提问的智慧』

快捷回复，不是特别针对某人哈。

> 考虑一个 <select> html 元素，如果事先指定了选中的值，然后后期动态添加了 <option>，那此时 <select> 也不会选中(显示)到指定的 <option>，但是可以通过 DOM 方法选中(显示)指定的 <option> 或者在遍历 <option> 时动态添加属性 selected 都可以实现，但是 ant-design <Select> 有对方暴露方法或者其他方式可以实现嘛？

我不懂这个使用场景， `Select` 的 value` 应该是 `Option` 中已经存在的。

**Comment by ystarlongzi** [comment]
@benjycui 
恩恩。

`value`可以是事先已经已知的，但`<Option>` 可能是动态加载的。比如说省市县联动吧，省市县的获取都是异步的，然后事先后台返回的省市县的 code，而不是 name，然后根据这些 code 一级级获取省市县列表时，要根据这些 code 对应到正确的 `<Option>` 上的，然后就会在界面上显示对应 code 的 name

**Comment by benjycui** [comment]
即使是动态加载，也是要经过 `render`，在 `render` 里面设置 `Select[value]` 不就可以了么。

**Comment by ystarlongzi** [comment]
@benjycui 
谢谢，方案可行。

不过感觉有点不完美。考虑原生的 `<select>` 元素，当其 value 没有在 `<option>` 列表匹配到时，此时，`<select>` 在界面上不会选中任何元素，会展示空。

而在 `<Select>` 里，如果没有匹配到对应的 `<Option>`，此时 `<Select>` 会展示 value 的内容。

**Comment by chengandpeng** [comment]
@ystarlongzi  和你一样的问题，请问你现在是怎么解决的。

antd版本2.0.0

采用 @benjycui 所说的 Select[value] 方法后，选项栏确实显示这个value了，但是选择下面动态加载的其他选项则不会替换默认选项栏的值。
不清楚是不是我写的问题
``` javascript
<FormItem  label='频道'	labelCol={{ span: 2 }}  wrapperCol={{ span: 3 }} >
  <Select  {...getFieldDecorator('select')} value={'健身'}>
    { edit && this.renderOptions(edit)}
  </Select>
</FormItem>
```
``` javascript
renderOptions(edit) {
  return edit.map(element => <Option key={element.id} value={element.code}> {element.name}</Option>);
}
```
![image](https://cloud.githubusercontent.com/assets/668072/18939926/ce12af2a-8636-11e6-8ba4-e53db8529630.png)

如图，‘健身’选项会在载入后render到默认选项栏中，但是之后选择任意Option的值都无法替换选中值。我理解定义了select[value]就不更新了。

并且，比如我现在生成的option为
``` javascript
<Option value='jianshen'>健身</Option>
```
在<Select>中，如果我设置 value='jianshen'， 默认选项栏中显示的是'jianshen'。 
同理，设置 value='健身' ，才会显示’健身‘。 这样如何跟下面Option做匹配？

请问如何解决？ 谢谢

**Comment by benjycui** [comment]
@chengandpeng `getFieldDecorator` 用错了你。。。再看下文档或者 Change Log

**Comment by chengandpeng** [comment]
@benjycui 感谢，设置fieldsvalue搞定了
``` javascript
this.props.form.setFieldsValue({
  select:'健身',
});	
```

**Comment by IrisZhang** [comment]
如果只是单纯的使用select， 用不到 `getFieldDecorator` 等方法，异步加载Options， render刷新了两次，但`defaultValue`的设置仍然是失败的，有什么解决的方法吗？

**Comment by trytofix** [comment]
遇到了同样的问题，options是动态获取的，例如`[{id:1, name:'选项1', id:2, name:'选项2']`
select 代码是:
```
{getFieldDecorator('type', {
                rules: [{ required: true, message: '选择类型' }],
              })(
                <Select labelInValue mode="multiple">
                  {settings.type.map(d => <Option key={d.id} title={d.name}>{d.name}</Option>)}
                </Select>
              )}
```
赋值代码是
```
   this.props.form.setFieldsValue({
      type: [{key: 1, label: '选项1'}],
    });
```
其中的` [{key: 1, label: '选项1'}]`是从服务器动态获取的，渲染后，options出现了题主所说的不一致的问题，排查好久后，覆盖了默认的onChange方法，打印了value,发现options中的key必须是字符串，所以赋值语句改为
```
 this.props.form.setFieldsValue({
      type: [{key: '1', label: '选项1'}],
    });
```
即 1 -> '1' ,就可以同步了。。。
mmp...

**Comment by Bobcui001** [comment]
我是通过这种方式解决的，仅供参考
```
<FormItem label="是否保存原始数据">
                      {getFieldDecorator('selectSaveAllData',
                        {initialValue: '不保存'}
                        )(
                        <Select style={{ width: 100 }} onChange={this.isSaveAllData}>
                          <Option value="1">不保存</Option>
                          <Option value="2">自定义</Option>
                          <Option value="3">永久保存</Option>
                        </Select>
                      )}
                    </FormItem>
```

**Comment by allinshang** [comment]
https://codesandbox.io/s/ll1y17jq89
当select没有内容时，默认选中【‘不限’】
页面显示为空，但是通过this.props.form.getFieldsValue()查看，已变更。
求解答

**Comment by SolidZORO** [comment]
@trytofix 对。

Select 的  initialValue 一定要是 string，int 就是不行，非常奇怪，坑了一个下午。

**Comment by junhey** [comment]
> @trytofix 对。
> 
> Select 的 initialValue 一定要是 string，int 就是不行，非常奇怪，坑了一个下午。
> 
> ```js-jsx
> {
>     getFieldDecorator('product_style_id', {
>     initialValue: '1', // 这里必须是 string
>     })(productStyleSelect)
> }
> ```

可以在 getFieldDecorator 中的rules设置type
```
getFieldDecorator('key', {
                rules: [
                  {type: 'array'}
                ],
```

**Comment by lvybriage** [comment]
@junhey 我使用 this.props.form 但是打印出是undefined。。。这是为什么呢，所以组件要先继承FormComponentProps吗

**Comment by Soul-Stone** [comment]
有种投机取巧的办法，select设置labelInValue，然后setFieldsValue为 {key:xxx, label:'要显示的内容'} 就可以正常显示了

**Comment by atonesapple** [comment]
antd 2.x的版本，select赋值更新操作出问题，出现问题1：如果使用defaultValue，但是切换页面回来select 界面的值时上一次的数据；问题2：如果使用value, 页面出现点击一次之后就无法筛选下来的option，大神么如何解决的

**Comment by xiashulin** [comment]
antd 4.0版本里面怎么处理这个问题

**Comment by sdz123** [comment]
getFieldDecorator 这个方法  4.0之后的版本 不支持了吧

**Comment by clChenLiang** [comment]
setTimeout 延迟加载即可

**Comment by clChenLiang** [comment]
select 组件增加一个 key = {defaultValue}

**Comment by 68899** [comment]
当你的组件为受控组件时，你可以设置defaultValue来进行操作；当你的组件不是受控组件时，尽量使用Select的value属性进行值的渲染
