### ISSUE TITLE
Upload.Dragger：拖拽上传文件时如何阻止firefox默认弹框提示正在打开文件。

### ISSUE THREAD

**Issue by Nicoopy** [ant-design/ant-design#17824]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
在火狐浏览器中打开antd官网的Upload组件页，将文件夹中的文件拖拽进Dragger区域，会弹出弹框提示正在打开文件。

### What is expected?
拖拽上传时火狐浏览器不会有默认事件，并且Upload.Dragger可以继续实现拖拽上传

### What is actually happening?
本地测试时，在Upload.Dragger的外围元素添加对drop事件的监听并阻止默认事件和冒泡（preventDefault和stopPropagation）后，可以阻止弹框事件，但也会导致Upload.Dragger原有的拖拽事件（监听的也是drop事件）失效。

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.8.6 |
| System | windows |
| Browser | firefox60.0 |

**Comment by zombieJ** [comment]
给个录屏？我这边没显示这个提示。

**Comment by Nicoopy** [comment]
> 给个录屏？我这边没显示这个提示。

![image](https://user-images.githubusercontent.com/32139451/61703592-78711800-ad74-11e9-823f-84a1b40c3581.png)
![image](https://user-images.githubusercontent.com/32139451/61703643-9cccf480-ad74-11e9-8145-765abe821405.png)

**Comment by Nicoopy** [comment]
> 给个录屏？我这边没显示这个提示。

![image](https://user-images.githubusercontent.com/32139451/61703986-54620680-ad75-11e9-9e2e-9a027e24de4e.png)
![image](https://user-images.githubusercontent.com/32139451/61704011-5fb53200-ad75-11e9-8db2-59098f16b603.png)

**Comment by Nicoopy** [comment]
你好，已在issue中附上相关图片


 
---原始邮件---
发件人: "Ant Design GitHub Bot"<notifications@github.com>
发送时间: 2019年7月23日(星期二) 下午5:52
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "Mention"<mention@noreply.github.com>;"Nicoopy"<2014130003@email.szu.edu.cn>;
主题: Re: [ant-design/ant-design] Upload.Dragger：拖拽上传文件时如何阻止firefox默认弹框提示正在打开文件。 (#17824)



Hello @Nicoopy. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
你好 @Nicoopy, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by Nicoopy** [comment]
你好，已在issue中附上相关的照片


 
---原始邮件---
发件人: "zombieJ"<notifications@github.com>
发送时间: 2019年7月23日(星期二) 下午5:52
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "Nicoopy"<2014130003@email.szu.edu.cn>;"Author"<author@noreply.github.com>;
主题: Re: [ant-design/ant-design] Upload.Dragger：拖拽上传文件时如何阻止firefox默认弹框提示正在打开文件。 (#17824)



给个录屏？我这边没显示这个提示。
