### ISSUE TITLE
Use relative-to-font-size unit such as rem or em instead of plain px

### ISSUE THREAD

**Issue by namnm** [ant-design/ant-design#17835]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to make scaleable components when screen is bigger. When on a 4k screen the components are very small. By using relative size unit, we can easily scale up the components by increase the font size of root.

### What does the proposed API look like?
Change all px unit to rem or em

**Comment by afc163** [comment]
https://github.com/cuth/postcss-pxtorem that you can try out.

**Comment by AO19** [comment]
Could you think about a optional parameter or config for scaling the font-size. 4K resolution is getting more popular and we should start to think about supporting this scaling option.

**Comment by raphaelaleixo** [comment]
+1 on having this as an optional parameter for scaling content

**Comment by 07akioni** [comment]
if you just want make it larger, try `zoom` css prop.

**Comment by fulanovic** [comment]
Why is this thread closed? Is there a solution for adopting ant components to diferent resolutions?
