### ISSUE TITLE
列拖动改变位置

### ISSUE THREAD

**Issue by miracllife** [ant-design/ant-design#17831]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
new requests(新需求)

### What is expected?
columns can change position by drag (列可拖动改变位置)

### What is actually happening?
new requests (新需求)

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.2 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
If you are trying to request feature, please use feature-request template in http://new-issue.ant.design/ to create another issue.
