### ISSUE TITLE
【BUG】DatePicker 控件不能Callback表单验证的方法

### ISSUE THREAD

**Issue by likai757** [ant-design/ant-design#1783]
```
<FormItem label="日期：" {... frameLayout} >
    <DatePicker {... getFieldProps('docdate', { rules: [
      { validator: (rule, value, callback) => {
        debugger
        if (value) {
          console.log(value);
        }
        callback()
      }}
    ] })}
        onChange={ date=>{ this.handleDateChange(date, 'docdate')} }
        value={ this.state.dates.docdate}
        format="yyyy.MM.dd"/>
</FormItem>
```
当给DatePicker 设置onChange方法时，rules 中的 validator 将不会被调用，目前导致日期控件都无法通过validator 来验证。

**Comment by likai757** [comment]
PS：在提交表单时，validator 会被调用，但回调时value = undefined

**Comment by likai757** [comment]
![image](https://cloud.githubusercontent.com/assets/6234399/15394707/11d8f252-1e07-11e6-807f-8be8826062b7.png)

**Comment by afc163** [comment]
http://ant.design/#/components/form?scrollTo=%E7%89%B9%E5%88%AB%E6%B3%A8%E6%84%8F

**Comment by afc163** [comment]
相关问题...

#1151 
#1489 
https://github.com/ant-design/ant-design/issues/1286
https://github.com/ant-design/ant-design/issues/1280
https://github.com/ant-design/ant-design/issues/1234 
#1353
#1286
#1495
