### ISSUE TITLE
tsc no compiling

### ISSUE THREAD

**Issue by cesarve77** [ant-design/ant-design#17838]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/buildroot-x86.cfg](https://bellard.org/jslinux/vm.html?url=https://bellard.org/jslinux/buildroot-x86.cfg)

### Steps to reproduce
in the console:

```
git clone git@github.com:ant-design/ant-design.git
cd ant-design
yarn 
tsc

```

### What is expected?
tsc compile without any issue.
and js files been created

### What is actually happening?
throw a error:
```

components/menu/MenuItem.tsx:9:11 - error TS2304: Cannot find name 'Omit'.

9   extends Omit<
            ~~~~

components/table/interface.tsx:279:4 - error TS1009: Trailing comma not allowed.

279   },
       ~

node_modules/antd/lib/menu/MenuItem.d.ts:4:40 - error TS2304: Cannot find name 'Omit'.

4 export interface MenuItemProps extends Omit<React.HTMLAttributes<HTMLLIElement>, 'title' | 'onClick' | 'onMouseEnter' | 'onMouseLeave'> {


```
| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | N/A |
| System | osx 10.14.5 (18F132) |
| Browser | N/A |

---
Im working in a package in ts with use antd, but when it try to build fresh packages on postinstall, break for this issue.

**Comment by afc163** [comment]
Please upgrade TypeScript to lastest version.
