### ISSUE TITLE
升级到3.20.5之后，modal关不掉,回退到3.6.2就可以了

### ISSUE THREAD

**Issue by Sara1991908** [ant-design/ant-design#17839]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://gitlab.alipay-inc.com/KBSJ/finesee](http://gitlab.alipay-inc.com/KBSJ/finesee)

### Steps to reproduce
  当 testModalVisible=false时候，仍然关不掉
<Modal
          visible={testModalVisible}
          title='服务测试'
          width='960px'
          onOk={this.handleOk}
          className='detailModal-size'
          onCancel={this.handleCancel}
          footer={[
            <Button key='back' onClick={this.handleCancel}>
              返回
            </Button>
          ]}
        >...
中间代码
</Modal>

### What is expected?
  当 testModalVisible=false时候，关掉弹窗

### What is actually happening?
没关掉

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.6 |
| System | MacBook Pro (Retina, 15-inch, Mid 2015) |
| Browser | chrome 版本 75.0.3770.100（正式版本） （64 位） |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/util/commit/72f48e2ee581ba06d637b0bfb60cdc3ae02f6873

重新安装 node_modules 即可。
