### ISSUE TITLE
Cascader组件问题

### ISSUE THREAD

**Issue by Zhouxingzu** [ant-design/ant-design#17847]
### Reproduction link
https://ant.design/components/cascader-cn/

### Steps to reproduce
在谷歌浏览器中使用Cascader组件，并传入一个props(Array) 作为options值

### What is expected?
正常显示级联选择组件

### What is actually happening?
```
function warningValueNotExist() {
  var list = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : [];
  var fieldNames = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
  list.forEach(function (item) {
    var valueFieldName = fieldNames.value || 'value';
    warning(valueFieldName in item, 'Cascader', 'Not found `value` in `options`.');
    warningValueNotExist(item[fieldNames.children || 'children'], fieldNames);
  });
}
```
warningValueNotExist() 该函数报错，查看list为null值，导致js报错

Environment | Info
-- | --
antd | 3.20.5
React | 16.8.6
System | win10
Browser | Google Chrome

**Comment by ilikecandice** [comment]
你传入的options的值里面，children可能为null，如果没有children，可以返回[],或者不返回该字段
