### ISSUE TITLE
TimePicker display problem

### ISSUE THREAD

**Issue by realEago** [ant-design/ant-design#17842]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nn0jx8jk44  )

### Steps to reproduce
时间轮点开之后，鼠标放上去hover后再移开，选中的阴影部分会出现白条，目前在safari浏览器上有这个问题。
When the time wheel is clicked on, put the mouse on hover, and then move it, the selected shaded section will appear with a white bar, which is currently a problem in safari.

### What is expected?
没有白条
There is no white

### What is actually happening?
出现白条
There is white

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.5 |
| Browser | safari 12.1.1 |

**Comment by afc163** [comment]
无法重现，给个截屏或 gif？

**Comment by realEago** [comment]
[hover前](http://ww2.sinaimg.cn/large/006tNc79ly1g5b1vbgk4ej31690u0dro.jpg)
[hover时](http://ww1.sinaimg.cn/large/006tNc79ly1g5b1vdfyo9j31690u07g4.jpg)
[hover后注意看这张](http://ww4.sinaimg.cn/large/006tNc79ly1g5b1vevt1rj31690u0gxl.jpg)
注意是safari浏览器，刚在同事电脑上试了下，也可以复现
[复现地址，用safari打开](https://codesandbox.io/s/jzz3y5oz05)
@afc163
