### ISSUE TITLE
已解决！使用任何带功能的控件都会报错：invariant.js?2e0c:38Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

### ISSUE THREAD

**Issue by gasxia** [ant-design/ant-design#1784]
使用任何带功能的控件都会报错。
错误是：
`invariant.js?2e0c:38Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).`
我去查看了给出的这个网址的解决方案，第一个可能性是使用'ref'不当导致，这个是antd内部包装使用的。我解决不了。
而第二个可能性是react安装重复导致的，我本地环境没有出现这个问题。

```
import React from 'react';
import ReactDOM from 'react-dom';
import Home from './components/Home';
import { Button,InputNumber } from 'antd';

var Todo = require('./components/Todo');
function onChange(value) {
  console.log('changed', value);
}
ReactDOM.render(  <InputNumber min={1} max={10} defaultValue={3} onChange={onChange} />, document.getElementById("container"));
```

**Comment by afc163** [comment]
感觉是重复安装 React 导致的，最好给重现看一看。

**Comment by gasxia** [comment]
@afc163 把node_modules删了重装之后好了。应该是npm版本的问题，之前版本2.x，升级之后安装各个组件，就没有依赖问题了。谢谢您的指点！

**Comment by afc163** [comment]
下次可以自行关闭，我们就省心一点 ~

**Comment by Allen-vip** [comment]
很好的解决了问题。

**Comment by hbrls** [comment]
我也遇到了这个问题，如果先装 antd，它会自己装一个 react，假如这时候你再手动装一个 React，而且版本和 antd 自动装的不一样的话，就会遇到这个问题。删除 node_modules 并不能解决这个问题，因为 package.json 里面的 React 的版本是错的。应该先装 React 后装 antd，然后 antd 发现你先装的 React 通过了版本要求，就不另装了。

**Comment by afc163** [comment]
npm3

**Comment by hbrls** [comment]
@afc163 er，居然是因为这个，一直用的 npm3，好像上周升级 node 被重置回 2 了

**Comment by hi-bazinga** [comment]
确实，npm3解决了！

**Comment by ZhuGongpu** [comment]
npm version: 3.10.3

还是有这个问题，项目地址 https://github.com/ZhuGongpu/IsomorphicQuestionnaire/tree/drag-and-drop @afc163
