### ISSUE TITLE
Tree组件展开节点动画卡顿掉帧严重

### ISSUE THREAD

**Issue by zhishanggao** [ant-design/ant-design#17840]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/tree/master/components/tree](https://github.com/ant-design/ant-design/tree/master/components/tree)

### Steps to reproduce
我们项目在使用了pdf.js来预览PDF的同时, 右侧使用了tree组件, 渲染节点大约1000 , 最大深度大约为5-7层, 再打开PDF预览的情况下, 点击节点展开动画卡顿明显, 帧数惨不忍睹.
通过performance监测出动画耗时异常 Animation - 267ms, 帧数 8 fps左右
![image](https://user-images.githubusercontent.com/16753441/61770350-9c3d6800-ae1f-11e9-9fe5-cb877e51245b.png)
![image](https://user-images.githubusercontent.com/16753441/61770364-a52e3980-ae1f-11e9-8abe-0d91b77c8c70.png)

### What is expected?
可能存在的优化点, 以及其它解决方案

### What is actually happening?
目前通过openAnimation属性关闭了节点展开的动画 但是还是想了解关于这个问题的其它解决方案

| Environment | Info |
|---|---|
| antd | 3.15.1 |
| React | 16.8.3 |
| System | macOS 10.13.3 |
| Browser | Chrome 75.0.3770.142 |

**Comment by zombieJ** [comment]
Merge into #3789

v4 会使用虚拟滚动来解决展开性能问题。

**Comment by zilingziling** [comment]
请问openAnimation你是在哪里看到的，tree控件的API上没有这一个呢

**Comment by zhishanggao** [comment]
@zilingziling 但是是通过他组件的index.d.ts看到的, 现在最新版本的话这个属性的名称应该已经变成了 `motion`, 将值给成null即可取消掉节点展开/关闭的动画

**Comment by zhishanggao** [comment]
@zilingziling 忘了说了这个属性没有在文档里面, 不明白为什么不选择在文档里说明

**Comment by zilingziling** [comment]
> @zilingziling 忘了说了这个属性没有在文档里面, 不明白为什么不选择在文档里说明

谢谢小伙伴，你真棒

**Comment by zilingziling** [comment]
@zhishanggao 谢谢小伙伴，你真棒

**Comment by yjp1105286534** [comment]
结合楼上  <Tree motion={null}>  把动画去掉就不会很卡顿 但是数据多的时候 就要用到官网虚拟高度来解决，但是虚拟高度在搜索的时候 会有高度显示不全BUG  所以我把这两种方案结合在一起 就接近完美不卡顿 <Tree motion={null} height={某某数字}，virtual = {virtualScroll}>,virtualScroll 在搜索的时候动态设置为false 关掉虚拟高度 只用 motion ={null} 这样就不会有高度显示不全BUG, 然后搜索为空时 就开启虚拟高度virtualScroll  = true

**Comment by DPGZl** [comment]
对于Tree组件，加了height属性之后，节点下子节点特别多（上千个）的情况下，在Firefox里拖拽滚动条时tree组件内容区域会出现空白，有人遇到过相同的问题吗？

**Comment by RGideonX** [comment]
请问楼主解决了吗?Antd3没有height虚拟滚动条，如何解决？
