### ISSUE TITLE
Select 组件的onSelect 方法失效

### ISSUE THREAD

**Issue by webshi** [ant-design/ant-design#17843]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cold-lake-p10gd)

### Steps to reproduce
click on the same option multiple times and observe the handleChange function log, you can find the onSelect function is invalid

### What is expected?
click on the same option multiple times and the onSelect function can work

### What is actually happening?
click on the same option multiple times, the onSelect function is invalid

| Environment | Info |
|---|---|
| antd | 3.20.4 |
| React | 16.6.3 |
| System | macOS Mojave 10.14.5 |
| Browser | Chrome 75.0.3770.142 |

---
this problem arises in versions 3.20.4 and above.

**Comment by afc163** [comment]
Try `onChange` instead of `onSelect`.

**Comment by webshi** [comment]
sorry, the antd version in my codesandbox is 3.20.3. When the antd version is 3.20.4 or above, the onSelect method will fail.

I need to use onSelect to get the same option value.


![gif](https://user-images.githubusercontent.com/45506651/61783038-b4ba7c00-ae39-11e9-9bb0-e055cdbfd644.gif)

**Comment by webshi** [comment]
@afc163

**Comment by afc163** [comment]
@zombieJ broken in https://github.com/ant-design/ant-design/pull/17664
