### ISSUE TITLE
Drawer的destroyOnClose属性失效

### ISSUE THREAD

**Issue by 303394539** [ant-design/ant-design#17845]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/drawer/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/drawer/index.tsx)

### Steps to reproduce
Drawer增加destroyOnClose={true}

### What is expected?
关闭时销毁 Drawer 里的子元素

### What is actually happening?
关闭时没有销毁 Drawer 里的子元素

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.0 |
| System | macOS |
| Browser | Google Chrome |

**Comment by jljsj33** [comment]
destroyOnClose 只在 antd 里支持，，，你确定用的是 antd 的 drawer, 这问题已修复了，https://github.com/react-component/util/commit/50da3ad9739712541e49a0729abcb937d60fa356，删掉 node_modules 即可..

**Comment by 303394539** [comment]
项目内从3.20.0升到3.20.5发现的，估计是你们提交该版本的dist到npm的时候还未修复该问题。

**Comment by afc163** [comment]
dist 文件要等下一个版本发布了，使用 node_modules 的只需重新安装即可。
