### ISSUE TITLE
Alert 内的关闭按钮不应该使用a标签，因为如果在alert外面需要用a标签包裹的话，react 就会报告 warning：<a> cannot appear as a descendant of <a>.

### ISSUE THREAD

**Issue by geograous** [ant-design/ant-design#17853]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

之前有个类似的 issue，最终被 accept 并且修复了 https://github.com/ant-design/ant-design/issues/862

### What problem does this feature solve?
不让 react 报 `Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.`

### What does the proposed API look like?
Alert 中的关闭按钮不使用 <a> 标签包裹

**Comment by afc163** [comment]
PR is welcome~

**Comment by geograous** [comment]
好的，晚些时候提pr
