### ISSUE TITLE
Jest Error

### ISSUE THREAD

**Issue by yanlee26** [ant-design/ant-design#17859]
`

  ● Console

    console.error node_modules/jest-environment-jsdom/node_modules/jsdom/lib/jsdom/virtual-console.js:29
      Error: Uncaught [TypeError: Cannot read property 'scrollWidth' of undefined]
`
Jest puts an Error like above.

**Comment by Gervwyk** [comment]
@yanlee26 Could you resolve this?

**Comment by shidaying** [comment]
> @yanlee26 Could you resolve this? Getting the same error on MultipleSelect and react-test-renderer

Do you resolve this ? could you tell me

**Comment by shidaying** [comment]
@Gervwyk could you resolve this?

**Comment by Gervwyk** [comment]
@shidaying no unfortunately not. Please share if you find a solution.
