### ISSUE TITLE
Table Transfer 无法设置 table 的 pagination 属性，设置之后左右两边都显示

### ISSUE THREAD

**Issue by SunShinewyf** [ant-design/ant-design#17850]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-e39cb8](https://stackblitz.com/edit/react-e39cb8)

### Steps to reproduce
点击 table 的分页，重新动态请求数据，右边的 table 会同步更新

### What is expected?
左右两侧不应该同时生效

### What is actually happening?
左右两侧都有设置的 pagination

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8 |
| System | 10.13.6 |
| Browser | chrome |

**Comment by afc163** [comment]
可以利用 `direction` 参数进行判断。

**Comment by 389567702** [comment]
@SunShinewyf  请问有demo可以参考下吗，最近也要做这个功能，左右两个table都得分页，不知如何实现，请指导一二
