### ISSUE TITLE
Form 中 Input 组件使用 getFieldDecorator 包裹时，不能连续输入，键入字符后会失焦

### ISSUE THREAD

**Issue by Xuyuey** [ant-design/ant-design#17863]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ggdok?fontsize=14)

### Steps to reproduce
鼠标hover 到 "小1" 节点上，点击右侧加号，生成新输入框，在输入框中输入字符

### What is expected?
不会失焦

### What is actually happening?
键入单个字符后失焦

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8 |
| System | macOS 10.14.4  |
| Browser | Chrome 74.0.3729.157 |

**Comment by Xuyuey** [comment]
求助啊

**Comment by Xuyuey** [comment]
在注释掉 getFieldDecorator 之后，不会出现失焦问题

**Comment by afc163** [comment]
It is not antd problem, please check your code logic.

**Comment by Xuyuey** [comment]
> It is not antd problem, please check your code logic.

请问是怎么看出来不是的

**Comment by wangyuan0108** [comment]
> > It is not antd problem, please check your code logic.
> 
> 请问是怎么看出来不是的

我也遇到这个问题了，是什么原因造成的？

**Comment by Xuyuey** [comment]
应该是更新状态值之后，页面重新渲染，"新"生成了一个Input框，导致的失焦。
react在渲染中会根据组件的key值进行diff计算，如果key值相等，就不会“重新”生成。
好像是这样哈，我说的也不是很准确。
======
我的解决办法：
1. 给map 生成的组件，赋唯一key值。但是并没有解决我的问题，不知道是不是因为我的嵌套层次太深。
2. 将input 的组件的value 设为 this.XXX，绕过因为值更新带来的渲染。虽然感觉不是很友好，但暂时没有找到其他的方法。

如果你找到了解决办法的话，方便的话也请告诉我一下哈～
