### ISSUE TITLE
Popover doesn't work in Menu

### ISSUE THREAD

**Issue by amfoter** [ant-design/ant-design#17860]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/jgqeJM](https://codepen.io/anon/pen/jgqeJM)

### Steps to reproduce
Put a Popover inside a Menu and it will break the entire page on mouseover.

### What is expected?
To behave like when it's outside of the Menu. (opens below the item and closes when leaving the area)

### What is actually happening?
I put a popOver inside a Menu (I need to show a popOver on a menu item on hover), when I hover the item, all the page goes white! 

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | react 16.8.6 |
| System | WIndows 10 |
| Browser | Chrome |

**Comment by chachaxw** [comment]
I met the same problem, it didn't happen before.

**Comment by afc163** [comment]
same as #18022, merge with it.
