### ISSUE TITLE
可否修改this.props.form.getFieldProps()中获取的值

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#1786]
## 场景
Form组件中包含Checkbox组件
```
<Form>
    <Checkbox {...fieldProps.status }>默认启用</Checkbox>
</Form>
```
```
//定义枚举
expoet const Enum = {
    ProductState:{
       enable:0,
       disable:1
    }
}
```

```
let { getFieldProps } = this.props.form;
let {pdtActs} = this.props;
let fieldProps = {
    status:getFieldProps("status",{
        onChange:(e)=>{
            //将选中状态更新为对应的枚举值，更新到redux store
            let status = e.target.checked === true ? Enum.ProductState.enable : Enum.ProductState.disable;
            pdtActs.setPdt({status:status})
        }
    })
}
```

## 问题
由于this.props.form.getFieldProps()会在onChange时触发，且会在自定义onChange事件后执行，故redux store中status的值依然为选中状态(true/false)，而不是希望的枚举值(0/1)

是否有可以修改getFieldProps值的方法，或者有没有更好的解决方案？

## 版本
antd@1.0.1

**Comment by benjycui** [comment]
用 [`onFieldsChange`](https://github.com/react-component/form#formoptiononfieldschangeprops-fields) 如何?

**Comment by hhhyaaon** [comment]
可以是可以，但是这样的话还得在每次赋值前判断是不是status这个对象，我觉得这样并不是很好
![image](https://cloud.githubusercontent.com/assets/17123400/15418507/68618d74-1e92-11e6-9c1d-ece40682478d.png)
比如枚举、日期都可能存在这样的问题，需要在提交之前做转化

**Comment by benjycui** [comment]
> 需要在提交之前做转化

那就在 `onSubmit` 时 `getFieldsValue` 批量转换吧。

**Comment by hhhyaaon** [comment]
恩好的，多谢。
另外我还有一个问题，我目前对于表单的处理是在onFieldsChange事件中直接将当前变更的值同步到redux store中
```
Form.create({
    onFieldsChange:(props,fields)=>{
        let {actions} = props;
        actions.updateVal(fields);
    }
})
```
但是这样的话会触发当前页面Component重新render
如果在textarea中输入一大段文字，那么Component会不断render，这样对于性能会不会影响很大？
是不是不太建议在onFieldsChange中直接触发action？

**Comment by benjycui** [comment]
用 [_.debounce](https://lodash.com/docs#debounce) 包一下 `onFieldsChange`。
