### ISSUE TITLE
IE 11 对象不支持“startsWith”属性或方法

### ISSUE THREAD

**Issue by onlyawt** [ant-design/ant-design#17866]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/onlyawt/SPFX-React-Antd/blob/master/AwtWebpart](https://github.com/onlyawt/SPFX-React-Antd/blob/master/AwtWebpart)

### Steps to reproduce
首页在目前这个环境中，我的antd只可以使用3.10.0版本，
目前报错的现象是IE11  报 对象不支持“startsWith”属性或方法；其他浏览器正常；
网上查看引用import 'babel-polyfill';  但报错 错误溢出

### What is expected?
如何解决此问题？

### What is actually happening?
对象不支持“startsWith”属性或方法

| Environment | Info |
|---|---|
| antd | 3.10.0 |
| React | 16.8.6 |
| System | Wind |
| Browser | IE |

---
是在开发微软SPFX  需要引用一些微软SP依赖包。

**Comment by afc163** [comment]
You need polyfill, it is not antd issue.

**Comment by onlyawt** [comment]
> You need polyfill, it is not antd issue.
 添加上import 'babel-polyfill';
CALL STACK:
Error: 堆栈溢出
   at Collection (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:436:7)

**Comment by onlyawt** [comment]
代码已上传：https://github.com/onlyawt/SPFX-react-Antd-awt.git
可测试！

**Comment by afc163** [comment]
https://babeljs.io/docs/en/babel-preset-env#targets
