### ISSUE TITLE
rc pagination package is not updated in antd package.json

### ISSUE THREAD

**Issue by Nilanth** [ant-design/ant-design#17864]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/package.json](https://github.com/ant-design/ant-design/blob/master/package.json)

### Steps to reproduce
https://github.com/ant-design/ant-design/blob/master/package.json

### What is expected?
Need to update rc pagination with latest version on antd  package.json file

### What is actually happening?
Some dependencies are not updated frequently like rc pagination

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Please remove `node_modules` and `yarn.lock` and `package-lock.json` then reinstall.
