### ISSUE TITLE
使用antd-init安装redux项目后，npm start运行，页面出现'uncaught at root '错误

### ISSUE THREAD

**Issue by licanbluesea** [ant-design/ant-design#1787]
使用antd-init命令后使用了redux-for complex project 这个选项然后一切正常，中间出现了权限的问题，不过rm -rf node_modules 再用 sudo npm install 一下就好了。

不过在安装完，运行npm start之后，页面出现了‘uncaught at root'的错误

’
utils.js:186uncaught at root 
 at _callee 
 at watchTodosGet 
 at watchTodosGet 
 at getTodos 
 Invariant Violation: Objects are not valid as a React child (found: SyntaxError: Unexpected token < in JSON at position 0). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
‘

刚刚学习完redux，想用这个来做项目。

antd-init 版本 :1.1.1
webpack 1.12.15
node 5.3.0
system : OSX EI CAPITAN 10.11.4
chrome version : 50.0.2661.102 (64-bit)

**Comment by sorrycc** [comment]
先换用 nvm 安装 node，避免权限问题。
