### ISSUE TITLE
RangePicker Bug

### ISSUE THREAD

**Issue by rongzhx123** [ant-design/ant-design#17878]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-presetted-ranges](https://ant.design/components/date-picker-cn/#components-date-picker-demo-presetted-ranges)

### Steps to reproduce
点击打开日期范围组件

### What is expected?
此时，由于组件已经默认选择当前日期，点击选择另一日期，‘确定’按钮需要被激活

### What is actually happening?
‘确定’按钮未被激活，需要再次点击默认选择的日期

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 任意版本 |
| System | Mac |
| Browser | Google |

**Comment by xrkffgg** [comment]
@rongzhx123  我想这个默认显示的 当前日期，并不是表示选中状态，而是一个 提示 当前日期的意思吧。

**Comment by rongzhx123** [comment]
> @rongzhx123 我想这个默认显示的 当前日期，并不是表示选中状态，而是一个 提示 当前日期的意思吧。

但默认显示跟选中是同一状态，很容易误解

**Comment by afc163** [comment]
<img width="601" alt="图片" src="https://user-images.githubusercontent.com/507615/62052528-3a7a6500-b248-11e9-9b14-c7e61d229241.png">

这个激活样式有点问题。@zombieJ

RangePicker 的当前日期样式之前和 DatePicker 不一致（或是没有？）应该是合理的。

<img width="524" alt="图片" src="https://user-images.githubusercontent.com/507615/62052645-76152f00-b248-11e9-83c6-5801c4eeda9b.png">

**Comment by afc163** [comment]
相关 issue：https://github.com/react-component/calendar/pull/557#issuecomment-491662903

**Comment by afc163** [comment]
还有这个：https://github.com/ant-design/ant-design/issues/16872

可以换一个样式或者像 2.x 一样去掉当前选项。
