### ISSUE TITLE
[table] Send record props for Cell in Group table head 

### ISSUE THREAD

**Issue by marchenko-ia12** [ant-design/ant-design#17875]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Can't send props about record in row for Cell in Group table head. On Cell doesn't work

### What does the proposed API look like?
no idea

**Comment by afc163** [comment]
Please describe your requirement with ore infomation and then I will reopen it.
