### ISSUE TITLE
Antd@3.20.5 Button component's shape and type attributes are confused

### ISSUE THREAD

**Issue by DoubleMingZMM** [ant-design/ant-design#17870]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx](https://github.com/ant-design/ant-design/blob/master/components/button/button.tsx)

### Steps to reproduce
Source address these two lines of code in 255 and 256 [` ${prefixCls} - ${type} `] : type, [` ${prefixCls} - ${shape} `] : shape. If shape sets the attribute value of primary, such as shape= "primary".------------------------
源码地址255和256中这两行代码[`${prefixCls}-${type}`]: type, [`${prefixCls}-${shape}`]: shape。如果 shape 设置了 primary 的属性值，比如 shape=“primary”。

### What is expected?
The console should report an error that the property has no value. And set to the default style instead of the primary style.------------------------
控制台报错，该属性没有该属性值。并且设置为默认样式，而不是 primary 样式。

### What is actually happening?
For shape, it applies the style is. Ant-btn-primary, and the feature is primary.------------------------
对于 shape 来说，它应用的样式是 .ant-btn-primary。表现为 primary 的特性。

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 16.2.0 |
| System | windows 7 |
| Browser | chrome 75 |

---
It is recommended to change the CSS types to.ant-btn-type-xxx and.ant-btn-shape-xxx. Prevent confusion between the two properties.------------------------
建议将 css 类型修改为 .ant-btn-type-xxx 和 .ant-btn-shape-xxx。防止两个属性混淆。

**Comment by afc163** [comment]
虽然实现上是这样，但是 shape 的取值只有 `circle` 和 `square` 两种，尽可能不要设置其他的值吧。
