### ISSUE TITLE
Drawer组件3.20.4之后版本children的Ref首次不能正常获取

### ISSUE THREAD

**Issue by TivonJJ** [ant-design/ant-design#17886]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/tivonjj/pen/NQrMrX?editors=0011](https://codepen.io/tivonjj/pen/NQrMrX?editors=0011)

### Steps to reproduce
 this.setState({
      visible: true,
    },()=>{
      console.log(this.formRef)
    });
第一次显示，在setState回调内ref是undefined，children并未初始化，但是3.20.3及之前版本一直正常，升级到3.20.4及之后版本都存在此问题

### What is expected?
第一次显示可以获取children的Ref

### What is actually happening?
第一次显示无法获取children的Ref

| Environment | Info |
|---|---|
| antd | 3.20.4 |
| React | 16.4.1 |
| System | Window 10 |
| Browser | chrome |

**Comment by jljsj33** [comment]
额，，感觉是 getDerivedStateFromProps 里换线程了。。可以先用 setTimeout 解决。。。。
```jsx
this.setState({
  visible: true,
}, () => {
  setTimeout(() => {
    console.log(this.formRef)
  })
});
```

**Comment by TivonJJ** [comment]
> 额，ref 第一次进入时是 null，，可以先用 setTimeout 解决， 等 drawer didmount 后再做输出，，或者你用 forceRender。。。。
> 
> ```js-jsx
> this.setState({
>   visible: true,
> }, () => {
>   setTimeout(() => {
>     console.log(this.formRef)
>   })
> });
> ```

以前项目改动量大，暂时降低版本解决了，但是在setState回调里面还Timeout觉得有点奇怪

**Comment by jljsj33** [comment]
https://github.com/react-component/util/blob/master/src/Portal.js#L13

**Comment by afc163** [comment]
按 https://github.com/ant-design/ant-design/issues/21543#issuecomment-598514031 的描，Drawer 的 `forceRender` 实现貌似有问题。

**Comment by phifa** [comment]
so drawer does not take forceRender. any other way?

**Comment by afc163** [comment]
It had been fixed in antd 4.x, check https://codepen.io/afc163/pen/PomKdmJ?editors=0010
