### ISSUE TITLE
Upload 在移动端multiple属性失效

### ISSUE THREAD

**Issue by 330595524** [ant-design/ant-design#17882]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
Upload 在移动端multiple属性失效，将咱们的Upload 放到移动端，就会出现多选，在移动端的相册中

### What is expected?
单选

### What is actually happening?
Upload 在移动端multiple属性失效，将咱们的Upload 放到移动端，就会出现多选，在移动端的相册中

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 16 |
| System | mac 10.13.3 |
| Browser | chrome |

---
这个bug，需要将antdesign放到移动端，通过模拟器也可以复现

**Comment by 330595524** [comment]
https://codesandbox.io/s/antd-reproduction-template-v03nd

**Comment by 330595524** [comment]
import React from "react";
import ReactDOM from "react-dom";
import { version, Button, Upload, Icon } from "antd";
import "antd/dist/antd.css";
import "./index.css";

class Hello extends React.Component {
  render() {
    const props = {
      action: "https://www.mocky.io/v2/5cc8019d300000980a055e76",
      onChange({ file, fileList }) {
        if (file.status !== "uploading") {
          console.log(file, fileList);
        }
      },
      multiple: true //单文件上传开启，在pc、手机浏览器都是可以正常使用的，但是在原生APP的webview中失效，以及antd mobile的ImagePicker中也有同样的问题
    };
    return (
      <div>
        <Upload {...props}>
          <Button>
            <Icon type="upload" /> Upload
          </Button>
        </Upload>
      </div>
    );
  }
}

ReactDOM.render(
  <div className="App">
    <h1>Please fork this codesandbox to reproduce your issue.</h1>
    <div>Current antd version: {version}</div>
    <h2>
      multiple:true,//单文件上传开启，在pc、手机浏览器都是可以正常使用的，但是在原生APP的webview中失效，以及antd
      mobile的ImagePicker中也有同样的问题
    </h2>
    <div style={{ marginTop: "16px" }}>
      <Hello />
    </div>
  </div>,
  document.getElementById("root")
);

**Comment by afc163** [comment]
It is a browser compatibility issue, not antd's, nothing we can do about it.

**Comment by Lshanny** [comment]
遇到了同样的问题，设置了multiple为false之后在移动端不管用，依然支持单次多选
