### ISSUE TITLE
使用antd中带有checkbox的Table组件时，点击checkbox报错

### ISSUE THREAD

**Issue by Alberqing** [ant-design/ant-design#17885]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
<TableList
                                columns={this.columns}
                                rowKey={record => record.id}
                                dataSource={dataSource}
                                total={total}
                                pageSize={pageSize}
                                current={current}
                                rowSelection={rowSelection}
                                onShowSizeChange={this.onShowSizeChange}
                                onChange={this.handlePageChange}
                            />
中 
const rowSelection = {
            onChange: (selectedRowKeys, selectedRows) => {
                this.setState({ selectedRowKeys })
            },
        };
代码如上
选择每行中的CheckBox时报错

### What is expected?
能够点击CheckBox进行选择

### What is actually happening?
点击单个CheckBox时会报错

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 3.20.6 |
| System | macOS |
| Browser | Google |

**Comment by INTMIN** [comment]
const rowSelection = {
onChange: (selectedRowKeys, selectedRows) => {
this.setState({ selectedRowKeys })
},
};

这个函数写错了吧，你好好检查下
