### ISSUE TITLE
固定列的情况下，表头分组计算高度不一致

### ISSUE THREAD

**Issue by KotoriMinami** [ant-design/ant-design#17889]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/RXRBjb?&editable=true&editors=001](https://codepen.io/anon/pen/RXRBjb?&editable=true&editors=001)

### Steps to reproduce
固定的name列与未固定的other列及company列高度表现不一致

### What is expected?
期望高度能够一致

### What is actually happening?
分组的固定列只是单纯的平分了高度

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 16.2.0 |
| System | win10（17134） |
| Browser | chrome（75.0.3770.142） |

**Comment by afc163** [comment]
确实是一个问题，但是感觉没什么好办法去实现。

**Comment by KotoriMinami** [comment]
> 确实是一个问题，但是感觉没什么好办法实现。

不过我使用3.1.0版本的时候，固定列的高度是能够响应页面resize事件并进行高度计算的，升级以后就出现现在的问题了

**Comment by afc163** [comment]
5.x 目测已经修复了：https://codepen.io/afc163-1472555193/pen/RwmRzjZ?editors=001
