### ISSUE TITLE
Form.Item内部的Upload无法点击

### ISSUE THREAD

**Issue by 593273894** [ant-design/ant-design#17893]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/PMzVWd](https://codepen.io/anon/pen/PMzVWd)

### Steps to reproduce
Upload 的 list-type 设置为 "picture-card"，然后放入 Form.Item 下，Upload变得无法点击

### What is expected?
Upload可以点击

### What is actually happening?
Upload无法点击

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 最新 |
| System | macos 10.12.6 |
| Browser | chrome 74.0.3729.157 |

**Comment by wleven** [comment]
I encountered the same problem, Shenkeng, made an afternoon, thought the code had a problem.
