### ISSUE TITLE
Clunky animation when adding tabs from the left in line mode

### ISSUE THREAD

**Issue by stonecrafter** [ant-design/ant-design#17898]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/stonecrafter/pen/BXzMBP](https://codepen.io/stonecrafter/pen/BXzMBP)

### Steps to reproduce
The above code sample comes from [this](https://ant.design/components/tabs/#components-tabs-demo-editable-card), I just changed it to `line` mode instead of `editable-card` and for adding new tabs to `unshift` instead of `push`.

If you press "Add", a new tab will be added to the left, and there will be a slight flicker of the tab animation as it tries to catch up to active tab which has been moved one to the right. The animation doesn't flicker when tabs are added to the right of the active tab.

### What is expected?
That adding to the left does not cause this jerky animation, just like adding to the right? 🤔

### What is actually happening?
Animation is weird when adding to the left.

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 16.8.6 |
| System | OSX 10.14.2 |
| Browser | Chrome  75.0.3770.142 |

---
Have considered workarounds:
- disabling animations altogether
- enforcing tabs are never added to the left of the active tab

Both are not ideal for my project's use case, but can be done.

**Comment by zombieJ** [comment]
Hmmm... ink bar is on the bottom which means not pin the position with the any Tab. May should add check to disable animation when update is not append after.

**Comment by imabp** [comment]
This happens in `v4.1.4`, the animation becomes jerky
