### ISSUE TITLE
Mentions select the option,change the value in the textarea

### ISSUE THREAD

**Issue by symnetry** [ant-design/ant-design#17899]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
const list = [
	{email:'11@112.com',nickname:'work1'},
	{email:'aa@aaa.com',nickname:'work2'},
	{email:'11@114.com',nickname:'work3'},
	{email:'11@115.com',nickname:'work4'},
]

我有一个如上所示的list,我的需求是能够输入我的nickname或是email，一样能够at到对应的数据
我现在能够想到的是在option中把nickname和email拼在一起，这样使我能够键入关键词时能够匹配到它们
```<Option key={key} value={`${nickname}-${email}`} >{nickname}</Option>```
这么写确实能够匹配到我想要的数据，然而在textarea显示的则是我这个option的value，也就是它可能会是“aa@aaa.com-work2”这样的形式展示

### What does the proposed API look like?
希望能够增加一个配置的方法 能够使用户在选择option以后编辑这个option的值,比方说上述例子添加一个 option=>option.split('-')[1] 能够返回对应的值

**Comment by zombieJ** [comment]
用 `filterOption`
