### ISSUE TITLE
Table set to default settings (particularly column sorter) when new row inserted

### ISSUE THREAD

**Issue by abdulmoizlakhani** [ant-design/ant-design#17892]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In some scenarios the requirement is to set the table settings to default settings when new row is inserted.  Like sorting etc.
Like the user changes the sorter to ascending order but by default it was set to descending order, now when the new row inserted in the table it should automatically set to descending order again.

### What does the proposed API look like?
Attaching a property named refreshOnChange at TabbleWrapper like `<TabbleWrapper refreshOnChange={true}  />` which will refresh table when ever the new row is inserted.

**Comment by afc163** [comment]
https://ant.design/components/table/#components-table-demo-head

There are `sortOrder` of `defaultSortOrder` for it.
