### ISSUE TITLE
antd大佬们能否把Form设计的简单一些

### ISSUE THREAD

**Issue by Vibing** [ant-design/ant-design#17890]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd是我认为最好的UI组件库，但是Form的设计让我很抓狂(表单验证对我来api过于复杂)

### What does the proposed API look like?
希望在 v4 版本里，能把Form设计的简单一些，尤其是表单验证这块。

**Comment by zombieJ** [comment]
可以看看新版 API：https://github.com/ant-design/ant-design/blob/4.0-prepare/components/form/index.zh-CN.md

ref: #16911
