### ISSUE TITLE
Form item has errors which should be owned by other items(Because rc-form version is not up to date)

### ISSUE THREAD

**Issue by calefy** [ant-design/ant-design#17907]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
1. form has many items
2. some fields name is short, some fields name is long and has numbers
3. when validation, `fieldName` will be wrong

old rc-form version:
```js
                // Exist if match the field name
                var restPath = errorFieldName.slice(ruleFieldName.length   1);
                if (/\d /.test(restPath)) {  // <--- the regexp is wrong
                  fieldName = ruleFieldName;
                  return true;
                }
```

and the latest rc-form:
```js
                // Exist if match the field name
                const restPath = errorFieldName.slice(ruleFieldName.length   1);
                if (/^\d $/.test(restPath)) {  // <--- the regexp is right
                  fieldName = ruleFieldName;
                  return true;
                }
```

### What is expected?
update the version of rc-form

### What is actually happening?
...

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | mac 10.14.5 |
| Browser | chrome75 |

**Comment by afc163** [comment]
Please reinstall after removing `node_modules` and `yarn.lock` and `package-lock.json` to get lastest version for rc-form.
