### ISSUE TITLE
ant表单绑定redux问题

### ISSUE THREAD

**Issue by HoroXu** [ant-design/ant-design#17908]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
2个不同的表单分别属于不同页面。如果表单里面的元素getFieldDecorator的值相同，当前表单修改值，传到redux，另外表单的redux也跟着这个一样.

### What is expected?
期望的效果是，不同表单，即便是getFieldDecorator值相同，值也能隔离。

### What is actually happening?
没有隔离，值也跟着同步

| Environment | Info |
|---|---|
| antd | 3.12.1 |
| React | 16.8.3 |
| System | window |
| Browser | Google Chrome  版本 75.0.3770.142（正式版本） （64 位） |

**Comment by afc163** [comment]
和 antd 没关系，你需要在 redux store 里存两份数据，或者进入另一个表单前清空已有数据。
