### ISSUE TITLE
TreeSelect focus() blur() doesn't have the result as espect

### ISSUE THREAD

**Issue by Hideman85** [ant-design/ant-design#17900]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate (in English opened issues).

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ohmky)

### Steps to reproduce
Focus is trigger after 1s and blur is trigger after 3s
You can also open the select an click on blur button

### What is expected?
focus() focus and open the TreeSelect
blur() blur and close TreeSelect

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | react |
| System | Latest Ubuntu |
| Browser | Latest firefox |

**Comment by zombieJ** [comment]
Focus is mean of set activeElement to current TreeSelect. Not mean open it. But it seems `blur()` not working which is a bug.

**Comment by kanweiwei** [comment]
I will work for it. ```blur()``` is Error , because of this:
![image](https://user-images.githubusercontent.com/19727490/64077353-659e1b80-cd02-11e9-856a-23b04deaac1e.png)

https://github.com/react-component/tree-select/blob/fe33eb7c27830c9ac70cd1fdb1ebbe7bc679c16a/src/Base/BaseSelector.jsx#L97-L99

**Comment by dspacejs** [comment]
How can I get `blur()` to work for the `DatePicker` component? I'm using `ref.current.blur()` but it doesn't seem to be doing anything.

**Comment by theexplay** [comment]
Any updates? blur steel doesn't work

**Comment by afc163** [comment]
> Focus is mean of set activeElement to current TreeSelect. Not mean open it. But it seems blur() not working which is a bug.

antd v4 is working on blur now.
