### ISSUE TITLE
About Typography.Paragraph ellipsis, Can I change 展开 to 详细?

### ISSUE THREAD

**Issue by wzht1991** [ant-design/ant-design#17901]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
it can help us to  create  unique pages

### What does the proposed API look like?
providing a attribute in Typography.Paragraph element which can let us reset the text

**Comment by zombieJ** [comment]
使用 LocaleProvider 可以更改本地化文字。

**Comment by SwinBlackSea** [comment]
> 使用 LocaleProvider 可以更改本地化文字。

@zombieJ 请问这个是怎么修改的

**Comment by SwinBlackSea** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> it can help us to create unique pages
> 
> ### What does the proposed API look like?
> providing a attribute in Typography.Paragraph element which can let us reset the text

hi，请问这个后来是怎么修改的呀？我目前也碰到这个需求了呢帮忙看下撒

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/blob/master/components/locale/zh_CN.tsx#L56
