### ISSUE TITLE
'prefixCls' in ConfigProvider doesn't works on two groups of components. (Modal.confirm and message)

### ISSUE THREAD

**Issue by AmazingYuan** [ant-design/ant-design#17904]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-n5rzh)

### Steps to reproduce
1. click the `Confirm` button and check the modal.
2. click the `showMessage` button and check the message.

### What is expected?
Html elements without styles on it.

### What is actually happening?
Components are rendered normally.

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 16.8.6 |
| System | window 7 |
| Browser | chrome 53 |

**Comment by AmazingYuan** [comment]
Ok, duplicated issues.

**Comment by luruxi** [comment]
If I don't import “antd/dist/antd.css” this file, how do I solve this problem，Because I loaded on demand and changed the configuration of “webpack.config.js”.
I use the style by 'less'
modifyVars: {
    'ant-prefix': 'xx'
},
javascriptEnabled: true
