### ISSUE TITLE
按照快速上手一步一步来，npm start 后报错

### ISSUE THREAD

**Issue by renbennen** [ant-design/ant-design#1790]
安装node.js后，一步步来

首先升级npm
然后npm install antd-init -g
$ mkdir antd-demo && cd antd-demo
$ antd-init
$ npm install
接着npm start启动报错

错误信息如下
C:\Program Files\nodejs\antd-demo>npm start

> @ start C:\Program Files\nodejs\antd-demo
> dora -p 8001 --plugins 'webpack,hmr,proxy,livereload?enableJs=false,browser-hi
story?index=/src/entries/index.html'

C:\Program Files\nodejs\antd-demo\node_modules\.npminstall\dora\0.3.2\dora\lib\p
lugin.js:83
        throw new Error('[Error] ' + pluginName + ' not found in ' + resolveDir)
;
        ^

Error: [Error] 'webpack not found in C:\Program Files\nodejs\antd-demo
    at resolvePlugin (C:\Program Files\nodejs\antd-demo\node_modules\.npminstall
\dora\0.3.2\dora\lib\plugin.js:83:15)
    at C:\Program Files\nodejs\antd-demo\node_modules\.npminstall\dora\0.3.2\dor
a\lib\plugin.js:102:12
    at Array.map (native)
    at resolvePlugins (C:\Program Files\nodejs\antd-demo\node_modules\.npminstal
l\dora\0.3.2\dora\lib\plugin.js:101:22)
    at createServer (C:\Program Files\nodejs\antd-demo\node_modules\.npminstall\
dora\0.3.2\dora\lib\index.js:61:44)
    at Object.<anonymous> (C:\Program Files\nodejs\antd-demo\node_modules\.npmin
stall\dora\0.3.2\dora\bin\dora:32:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

看错误是找不到插件？

操作系统XP、2008都是如上错误

npm版本3.9.2
node版本4.4.4
antd-init版本1.1.1

**Comment by afc163** [comment]
`rm node_modules && npm install`

@sorrycc 可能要把自动运行 `tnpm install` 的给去掉了。看楼主应该是用了 tnpm@4

**Comment by sorrycc** [comment]
会根据 tnpm/cnpm/npm 的顺序自动选的。

**Comment by afc163** [comment]
估计是 tnpm@4 不支持 antd-init ？

**Comment by renbennen** [comment]
在 antd-demo目录删除 node_modules 再重新npm i 还是同样的问题。

**Comment by sorrycc** [comment]
先用这个命令吧，这边全栈培训也遇到这个问题了。(windows 下)

```bash
$ ./node_modules/.bin/dora --plugins webpack,proxy
```

**Comment by renbennen** [comment]
修改package.json
改为"start": "./node_modules/.bin/dora --plugins webpack,proxy",
这样可以启动了。
启动的时候
please trust the rootCA.crt in C:\Users\Administrator\.anyproxy_certs\
or you may get it via anyproxy webinterface
弹出文件夹，里边有rootCA.key文件，不是注册表文件，修改为rootCA.crt也不管用。不知道有没有影响？

**Comment by sorrycc** [comment]
没有影响，证书是用来做 https 代理用的。

**Comment by renbennen** [comment]
默认生成的package.json里
`"start": "dora --plugins 'proxy,webpack,webpack-hmr,livereload?enableJs=false,browser-history?index=/src/entries/index.html'",`
由于单引号的问题造成的，去掉单引号就可以了
`"start": "dora --plugins proxy,webpack,webpack-hmr,livereload?enableJs=false,browser-history?index=/src/entries/index.html",`

**Comment by sorrycc** [comment]
👍 ，帮忙试下用 `\"` 引起来会不会有问题?

**Comment by zhaojianrun** [comment]
转义成双引号可以正常运行，转义成单引号会有错误。

**Comment by marsDes** [comment]
win10 系统 删除 node_modules 文件下文件 重新 install 
执行 npm start
可以通过主机 8989 端口访问
直接打开 dist/index.html文件 是 404 
编译后的js 不能直接引用吗？

**Comment by afc163** [comment]
npm@2 下会报这个错误，还需要再看一下。

**Comment by afc163** [comment]
又没问题了，见鬼。

**Comment by afc163** [comment]
dora-plugin-atool-build 改名为 dora-plugin-webpack 了，相应的 scripts 里的启动命令也要修改。
