### ISSUE TITLE
Modal覆盖住Spin?

### ISSUE THREAD

**Issue by joesonw** [ant-design/ant-design#1791]
##  What you did
一个全局的Spin 里面放了Router等Component
然后会有一个Modal

## What you would like to happen
Spin遮挡住Modal, 防止操作
## What actually happened
Modal遮挡住Spin.

## Environment Information

antd 0.12.11

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by joesonw** [comment]
@benjycui 
Here it is, http://codepen.io/anon/pen/xVoWBj?editors=001

**Comment by RaoHai** [comment]
Hi,

`Click on mask then hide the Modal`, is not a default behavior, it's a user-custom function..

You can show or hide your `Model` by `visible` props.

http://ant.design/#/components/modal?scrollTo=components-modal-demo-basic

**Comment by afc163** [comment]
@RaoHai 貌似不是你说的问题...

**Comment by RaoHai** [comment]
好吧我理解错了。。。

**Comment by benjycui** [comment]
在 Chrome 开发者工具中，把 `Modal` 的 DOM 节点手动挪到 `Spin` 中就正常，所以问题在于 `Modal` 是渲染到 `body` 中，而非 `Spin` 中。

然后 `Modal` 并非基于 rc-trigger，所以无法设置 `getPopupContainer`。

感觉不需要支持这种场景，毕竟处于 loading 状态的应该是 `Modal` 中的内容，而非 `Modal` 自身。

```jsx
      <Modal visible={true}>
        <Spin size='large' spining={true}>
          Really?
        </Spin>
      </Modal>
```

**Comment by joesonw** [comment]
@benjycui 或者Modal如果有一个loading属性? 可以block掉所有对于modal的操作 (关闭, 点击外面关闭, etc)

**Comment by benjycui** [comment]
@joesonw 先自行在 `Modal` 外面包一层实现这个 `loading` 吧，需求多了再考虑集成进 `antd`

**Comment by afc163** [comment]
```jsx
<span style={{ pointerEvents: this.state.loading ? 'none' : ''}}>
  <Modal />
</span>
```

**Comment by AaronJan** [comment]
我现在写的Modal都直接屏蔽了所有按钮，在Modal内部的Form的“取消”按钮上绑定了Modal的关闭方法，Form提交的时候整个Form外层的Spin被触发…

如果采用Modal自带的按钮，并且“提交”是触发一个异步事件（例如耗时2秒），此时用户可以点击右上角的叉或者“取消”来关闭Modal我是感觉很奇怪的。

所以，需求+1……

**Comment by myqianlan** [comment]
@afc163 同此问题，confirmLoading的时候觉得屏蔽掉其他操作比较好，或者可以添加一个配置项。个人觉得这个需求比较常规
