### ISSUE TITLE
AutoComplete 设置受控后，onSearch方法没法输入中文

### ISSUE THREAD

**Issue by gc654321** [ant-design/ant-design#17916]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-frog-xkmht)

### Steps to reproduce
在AutoComplete输入中文

### What is expected?
在能通过AutoComplete输入中文

### What is actually happening?
无法在AutoComplete输入中文

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | window |
| Browser | Chromo |

**Comment by jin-benben** [comment]
我遇到这个问题

**Comment by afc163** [comment]
You need `onChange`: https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-Input/Select-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86%E3%80%82

**Comment by gc654321** [comment]
我使用onChange，但是没有办法得到我想要的。
例子：使用onChange，然后输入Option 中没有的，这个时候我去按回车，得到的结果一定是Option 中有的。我不需要这样的结果，我只是想把输入的展现出来

**Comment by afc163** [comment]
Try `defaultActiveFirstOption={false}`

**Comment by gc654321** [comment]
good ， thank you
