### ISSUE TITLE
webpack4.0production模式下打包 antd组件TreeSelect报错

### ISSUE THREAD

**Issue by HoroXu** [ant-design/ant-design#17911]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
        <FormItem label="活动城市" {...shortWrapper}>
          {getFieldDecorator("activityCities", {
            rules: [{ required: true, message: "活动城市必选" }]
          })(<TreeSelect {...tProps} />)}
        </FormItem>

### What is expected?
打包不报错

### What is actually happening?
start build 模式下没有问题，production模式下打包报错。webpack4.0生产模式下默认启用UglifyJsPlugin插件，可能混淆压缩出问题了。

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.3 |
| System | window |
| Browser | Google Chrome  版本 75.0.3770.142（正式版本） （64 位） |

---
报错信息
main.bundle.js:formatted:224812 Uncaught TypeError: Object(...) is not a function
    at _t (main.bundle.js:formatted:224812)
    at main.bundle.js:formatted:226251
    at u (main.bundle.js:formatted:226242)
    at value (main.bundle.js:formatted:226250)
    at ar (main.bundle.js:formatted:98068)
    at sr (main.bundle.js:formatted:98140)
    at Ci (main.bundle.js:formatted:98966)
    at main.bundle.js:formatted:100624
    at Yo (main.bundle.js:formatted:100767)
    at Uo (main.bundle.js:formatted:100791)

具体报错的位置
  function wt(e) {
        var t = e.title
          , n = e.label
          , a = e.key
          , r = e.value
          , i = st({}, e);
        return n && !t && (ct || (Je()(!1, "'label' in treeData is deprecated. Please use 'title' instead."),
        ct = !0),
        i.title = n),
        a || (i.key = r),
        i
    }
    function _t(e) {
        return Object(Xe.g)(e, {
            processProps: wt
        })
    }

**Comment by shaodahong** [comment]
建议把 webpack 配置贴出来

**Comment by HoroXu** [comment]
我当时yarn install 一个私库，导致了报错，但根据当时的问题定位看，是组件打包报错了，我贴个配置。

**Comment by HoroXu** [comment]
这是common配置

const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");
const CompressionWebpackPlugin = require("compression-webpack-plugin");
const autoprefixer = require("autoprefixer");
const webpack = require("webpack");
const devMode = process.env.NODE_ENV !== "production";

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "[name].bundle-[hash].js",
    chunkFilename: "[name].bundle.js",
    path: path.resolve(__dirname, "dist")
  },
  stats: {
    entrypoints: false,
    children: false,
    colors: true,
    env: true,
    performance: true
  },
  devServer: {
    contentBase: "./dist",
    hot: true,
    disableHostCheck: true,
    inline: true,
    port: 8080,
    proxy: {
      "/": {
        target:
          // "http://mock.cnsuning.com/mock/http://witdev.cnsuning.com:8080/",
          "http://witpre.admin.cnsuning.com/", //pre环境
        // "http://witsit.admin.cnsuning.com/", //sit环境
        secure: true,
        changeOrigin: true
      }
    },
    stats: {
      entrypoints: false,
      children: false,
      colors: true,
      env: true,
      performance: true
    }
  },
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        uglifyOptions: {
          comments: true
        }
      }),
      new OptimizeCSSAssetsPlugin({})
    ],

    splitChunks: {
      chunks: "all", //默认只作用于异步模块，为`all`时对所有模块生效,`initial`对同步模块有效
      minSize: 30000, //合并前模块文件的体积
      minChunks: 1, //最少被引用次数
      maxAsyncRequests: 5,
      maxInitialRequests: 3,
      automaticNameDelimiter: "~", //自动命名连接符
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          minChunks: 1,
          priority: -10 //优先级更高
        },
        default: {
          test: /[\\/]src[\\/]js[\\/]/,
          minChunks: 2, //一般为非第三方公共模块
          priority: -20,
          reuseExistingChunk: true
        }
      }
    },
    runtimeChunk: {
      name: "manifest"
    }
  },

  plugins: [
    new CleanWebpackPlugin(["dist"]),
    // new webpack.DllReferencePlugin({
    //   manifest: path.resolve(__dirname, "public/dll", "manifest.json")
    // }),
    new HtmlWebpackPlugin({
      filename: "index.html",
      template: "./index.html"
    }),
    new MiniCssExtractPlugin({
      filename: "[name].[hash].css",
      chunkFilename: "[id].[hash].css"
    })
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        use: {
          loader: "babel-loader?cacheDirectory"
        },
        exclude: /node_modules/,
        include: path.resolve(__dirname, "src") // 精确指定要处理的目录
      },
      {
        test: /\.(sa|sc|le)ss$/,
        use: [
          devMode ? "style-loader" : MiniCssExtractPlugin.loader,
          "css-loader",

          {
            loader: "postcss-loader",
            options: {
              plugins: [
                require("autoprefixer"),
                autoprefixer({
                  flexbox: "no-2009"
                })
              ],
              javascriptEnabled: true
            }
          },
          "less-loader"
        ]
      },
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, "css-loader"]
      },
      {
        test: /\.styl$/,
        use: [
          devMode ? "style-loader" : MiniCssExtractPlugin.loader,
          "css-loader",
          {
            loader: "postcss-loader",
            options: {
              plugins: [
              ],
              import: [path.join(__dirname, "./src/assets/stylus/index.styl")],
              paths: [
                path.join(__dirname, "./src/assets/"),
                path.join(__dirname, "./")
              ]
            }
          },
          {
            loader: require.resolve("stylus-loader"),
            options: {
              import: [path.join(__dirname, "./src/config/stylus/index.styl")]
            }
          }
        ]
      },
      {
        test: /\.(woff|woff2|svg|ttf|eot)$/,
        use: {
          loader: "url-loader",
          options: {
            limit: 100000, //这里要足够大这样所有的字体图标都会打包到css中
            name: "images/[name].[ext]"
          }
        }
      }
    ]
  },
  resolve: {
    alias: {
      "@": path.join(__dirname, "/src"),
      react: path.resolve("./node_modules/react")
    }
  }
  // externals: {
  //   'echarts': 'echarts'
  //   }
};

**Comment by HoroXu** [comment]
这是prod配置

const webpack = require("webpack");
const merge = require("webpack-merge");
const common = require("./webpack.common.js");
const UglifyJSPlugin = require("uglifyjs-webpack-plugin");
const path = require("path");
module.exports = merge(common, {
  mode: "production",
  devtool: "cheap-module-source-map",
  plugins: [
    new UglifyJSPlugin({
      uglifyOptions: {
        compress: {
          drop_debugger: true,
          drop_console: true
        }
      }
      // sourceMap: true
    }),
    new webpack.DefinePlugin({
      "process.env.NODE_ENV": JSON.stringify("production")
    }),
    new webpack.DllReferencePlugin({
      manifest: path.resolve(__dirname, "public/dll", "manifest.json")
    })
  ],
  module: {
    rules: [
      {
        test: /\.(png|svg|jpg|gif)$/,
        loader: "file-loader",
        options: {
          name: "images/[name].[ext]",
          publicPath: "/project/"
        }
      }
    ]
  }
});

**Comment by ztplz** [comment]
贴配置没多大用  最好有复现的git repo

**Comment by shaodahong** [comment]
这种情况最好的测试方式就是把这个注释掉，屡试不爽
```js
new UglifyJSPlugin({
uglifyOptions: {
compress: {
drop_debugger: true,
drop_console: true
}
}
// sourceMap: true
}),
```

**Comment by afc163** [comment]
Closing for no reproduce, I will reopen if reproduce repository is provided.

**Comment by achenjs** [comment]
optimize-css-assets-webpack-plugin 把这个plugin干掉
