### ISSUE TITLE
antd中ConfigProvider对Modal.confirm和Popconfirm不起效果 

### ISSUE THREAD

**Issue by huban2** [ant-design/ant-design#17918]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://new-issue.ant.design/?repo=ant-design](http://new-issue.ant.design/?repo=ant-design)

### Steps to reproduce
无

### What is expected?
使用配置的ConfigProvider的个性化的样式配置名称

### What is actually happening?
还是默认的前缀名称

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 14.2 |
| System | windows 7 |
| Browser | chrome53 |

**Comment by afc163** [comment]
Duplicate of #15260
