### ISSUE TITLE
Button动画的关系 在1000个input下导致onClick触发太慢 

### ISSUE THREAD

**Issue by fangkyi03** [ant-design/ant-design#17926]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/fangkyi03/nextjs-antd-dva-form-demo.git]

### Steps to reproduce
使用自己重写的一个表单架子 创建了一个1000input的表单 这个时候 如果快速点击button的时候 onClick触发时间是有延迟的 看了一下button的代码 是因为还有一个动画操作要处理 所以才导致的onClick触发缓慢

### What is expected?
button可以外部控制是否需要动画效果 保持onClick正常触发

### What is actually happening?
使用自己重写的一个表单架子 创建了一个10000input的表单 这个时候 如果快速点击button的时候 onClick触发时间是有延迟的 看了一下button的代码 是因为还有一个动画操作要处理 所以才导致的onClick触发缓慢

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.4 |
| System | 10.14.5 |
| Browser | 75.0.3770.142 |

![image](https://user-images.githubusercontent.com/30390014/61990611-46aec880-b076-11e9-971e-b40e46c4665f.png)

**Comment by fangkyi03** [comment]
问题依旧存在 有一点好转 但是还是有性能问题

**Comment by fangkyi03** [comment]
已升级最新3.20.7版本

**Comment by afc163** [comment]
这个 PR 还没有发布哦

**Comment by fangkyi03** [comment]
![image](https://user-images.githubusercontent.com/30390014/62184405-7fa9ae80-b390-11e9-9dfd-c3e941e628ec.png)
我看3.20.7这里已经有这个修复的代码了

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commits/3.20.7

没有的。

**Comment by fangkyi03** [comment]
在3.21.0中 问题依旧存在 这个问题应该是setTimeOut的关系 只改一个css样式无法解决这个问题的
我测试的是疯狂点击的情况下 会出现卡顿问题 而不是单次点击
