### ISSUE TITLE
Timeline Pending Icon Background Always White

### ISSUE THREAD

**Issue by wcatron** [ant-design/ant-design#17927]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/YmpEWv](https://codepen.io/anon/pen/YmpEWv)

### Steps to reproduce
Use the Timeline component with any none white background.

### What is expected?
The rendering dot has a transparent background.

### What is actually happening?
The rendering dot has a white background. Specifically the .ant-timeline-item-head class.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | N/A |
| System | macOS |
| Browser | Chrome |

**Comment by shaodahong** [comment]
maybe can provide a prop like `backgroundColor` to set them, In my see the initial value `transparent `  it's not good

**Comment by KuthorX** [comment]
I try fixed this by [ant-timeline-item-pending_background-color_transparent](https://github.com/ant-design/ant-design/pull/17951), but maybe there is better solution for this issue
