### ISSUE TITLE
Enter in modal form field does not submit the form

### ISSUE THREAD

**Issue by accuware** [ant-design/ant-design#17924]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-vaughan-2m62q)

### Steps to reproduce
Click "New Collection"
Enter some text in the first form field
Press ENTER

### What is expected?
Form should submit and modal should close

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.4.1 |
| System | macOS 10.14.5 |
| Browser | Chrome 75.0 |

**Comment by accuware** [comment]
Found a workaround maybe:

`<Input prefix={<Icon type="home" />} placeholder="Room which should be joined" autoFocus onPressEnter={onCreate}/>
`
Adding "onCreate" to all Inputs. Requires `destroyOnClose={true}` for the Modal, otherwise strange behaviour.

**Comment by afc163** [comment]
> Form should submit and modal should close

I don't think it is reasonable without binding any keypress events.

**Comment by accuware** [comment]
Well, it reacts on cancel, so it could react on enter too. No issue

Sent from my iPhone
