### ISSUE TITLE
Option to unmount tab content when tab is inactive

### ISSUE THREAD

**Issue by guidogast** [ant-design/ant-design#17920]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using the Tabs component, the content of the tabs is mounted when a tab is activated. But when you switch to another tab, the old one is not unmounted. It would be nice to have an option to unmount the tab content when a tab is not active. 

We have a use case where we have a component mounted in the tab content. We want this component to be in other tabs as well, but it can't be mounted at the same time, because it listens to certain events that should only be listened to by the active tab. An option to unmount an inactive tab seems like a really nice addition, also because it would increase the performance.

### What does the proposed API look like?
`<Tabs unmountInactiveTabs={true} >`

The default would obviously be `false`

**Comment by afc163** [comment]
`destroyInactiveTabPane`: https://github.com/react-component/tabs

**Comment by jayanthbondi** [comment]
This issue is still not resolved, could you please look into it.
Thanks in advance

**Comment by ngmiduc** [comment]
Is there any progress in this ? 
Any possibilities to unmount tab pane if not active ?

**Comment by linonetwo** [comment]
Do it like

```jsx
          <Tabs
            destroyInactiveTabPane
            onChange={(activeKey: string) => {

            }}
          >
```

This is undocumented in 3.x branch, but we can use it.
