### ISSUE TITLE
createBaseForm.js:256 Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined     at Object.getRules

### ISSUE THREAD

**Issue by yuejie89** [ant-design/ant-design#17923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-x46p6)

### Steps to reproduce
连接有点问题
动态添加 form.getFieldValue（-个form.getFieldValue集合 包括几个字段和几个图片） 上传图片 正常    但删除一个后 再上传就报错

### What is expected?
createBaseForm.js:256 Uncaught (in promise) TypeError: Cannot read property 'filter' of undefined     at Object.getRules 解决这个报错

### What is actually happening?
删除一个后 再上传就报错

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.6 |
| System | windows10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
https://xfby6.csb.app/

**Comment by yoyo837** [comment]
@yuejie89 使用`getContainer` https://5buml.csb.app/

**Comment by yoyo837** [comment]
```JSX
  refHandle = dom => {
    if (dom) {
      this.dom = dom; // <----
      this.props.registerFullScreenContainer(dom);
    }
  };
```

```JSX
<Modal
  visible={this.state.visible}
  onCancel={this.handleTrigger}
  onOk={this.handleTrigger}
  getContainer={() => this.dom} // <----
  >
    Woo!!!
 </Modal>
```

**Comment by yoyo837** [comment]
我是不是回复错了issue !? 🙃  #17925 @DengXuening

**Comment by yuejie89** [comment]
大神 我的是动态添加上传图片 出问题了

**Comment by DengXuening** [comment]
@yoyo837 emmm... 确实回复错了issue 🙂

**Comment by tancgo** [comment]
> @yoyo837 emmm... 确实回复错了issue 😄

请问你最后咋解决这个错误的  我也遇到了

**Comment by tancgo** [comment]
> 大神 我的是动态添加上传图片 出问题了

请问你最后咋解决这个错误的 我也遇到了

**Comment by zlqGitHub** [comment]
遇到了相同的问题，大家有解决方案了吗？

**Comment by MsmileLDM** [comment]
输入框遇到了同样的问题，有什么解决方案吗？

**Comment by 1623311678** [comment]
> 输入框遇到了同样的问题，有什么解决方案吗？
这个我也遇到了，本质上就是dom销毁，重建，我的解决方案有3个 1 删除的之后的动作setimeout异步渲染，删除前后设置flag标志是否删除，强制rerender即可，2 删除的时候先清空数据源,在设置数据，3 如果你是table的话，我理解还可以动态添加删除列，

**Comment by HaoCao216** [comment]
How about tooltip, popover,... Theyhad the same problem as Modal. I am stuck with Popover. Please help 👯
