### ISSUE TITLE
Table sorting by text length or alphabetically?

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#1792]
The table sorter is sorting text strings by length not alphabetically. I do not know how is this in Chinese language but in euro american countries sorting of text is done alphabetically.

**Comment by afc163** [comment]
```
[{
  title: 'age',
  dataIndex: 'age',
  sorter: (a, b) => a.age - b.age,
}]
```

You can specify your own sort algorithm. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

**Comment by KirillYoYo** [comment]
for sort by alpgavite:
`
function compareByAlph (a, b) {
		if (a > b) {
			return -1;
		}
		if (a < b) {
			return 1;
		}
		// a must be equal to b
		return 0;
	}
...
sorter: (a, b) => compareByAlph(a.lastName, b.lastName),
`

**Comment by Leong21** [comment]
It would be better to use JavaScript String#localeCompare function:

sorter: (a, b) => { return a.title.localeCompare(b.title)},

**Comment by tzs007** [comment]
thx @Leong21 for this clever solution

**Comment by ghoshnirmalya** [comment]
I'm still unable to figure out how can we sort columns using Dates.

**Comment by Leong21** [comment]
@ghoshnirmalya try using moment.js if possible.

sorter: (a, b) => { return moment(a.publishedAt).unix() - moment(b.publishedAt).unix()}

**Comment by ghoshnirmalya** [comment]
@Leong21 Thank you! That works as expected.

**Comment by MrMuhammadRizwan** [comment]
Good work @ leong21 
actually The localeCompare() method compares two strings in the current locale.
and it would be better 
sorter: (a, b) => { return a.title.localeCompare(b.title)},

**Comment by dcantu96** [comment]
@Leong21 Thank you! This should be explained or mentioned here:[https://vue.ant.design/components/table/](url)

**Comment by atayahmet** [comment]
There is also a solution like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator/Collator
