### ISSUE TITLE
<Modal> can not work in full screen mode

### ISSUE THREAD

**Issue by DengXuening** [ant-design/ant-design#17925]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xfby6?fontsize=14)

### Steps to reproduce
Key Word: `requestFullscreen `, `Modal`

Note: sandbox can not completely reproduce the problem(element in ifame can not requestFullscreen ???)

Reproduce Step: 
* open the sandbox above
* click **Enter FullScreen** button, browser enter full screen mode
* click **Trigger Modal** button, the modal can not display.
* press `ESC`, browser exits full screen,
* click **Trigger Modal**, the modal works well

### What is expected?
Modal component can work in browsers full screen mode.

### What is actually happening?
Modal component don't work in browsers full screen mode

| Environment | Info |
|---|---|
| antd | 2.13.14 |
| React | 15.6.1 |
| System | Mac OS 10.14.5 |
| Browser | 75.0.3770.142 |

---
My team develop a editor. In order to increase the area of the editing area, the editor can switch to full screen mode. But, `Modal` component don't work in full screen mode.  I hope you can give me some advice, Tks.

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/17923#issuecomment-515540485

**Comment by DengXuening** [comment]
It works. Thank you

**Comment by yoyo837** [comment]
`getContainer={false}` 好像更方便一点，不过有问题在修... #18215

**Comment by leineveber** [comment]
@yoyo837 what about selects and dropdowns? they're also not working in fullscreen
