### ISSUE TITLE
Antd Webpack build failing (Can't resolve 'css-animation/es/Event')

### ISSUE THREAD

**Issue by ashvin777** [ant-design/ant-design#17928]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://donthaveanylink.com](http://donthaveanylink.com)

### Steps to reproduce
Import antd package and try to build in webpack project. 

### What is expected?
Build should be done without any error

### What is actually happening?
Getting below error

ERROR in ../node_modules/antd/es/_util/wave.js
Module not found: Error: Can't resolve 'css-animation/es/Event' in '/Users/***/Documents/git/***/node_modules/antd/es/_util'
 @ ../node_modules/antd/es/_util/wave.js 7:0-54 53:12-28 54:12-28 135:12-28 136:12-28
 @ ../node_modules/antd/es/tag/index.js
 @ ../node_modules/antd/es/index.js
 @ ./app/components/home/body/layouts/fullscreen-layout.jsx
 @ ./app/components/home/body/body.js
 @ ./app/components/home/home.js
 @ ./app/app.js
 @ ./index.js

| Environment | Info |
|---|---|
| antd | 3.11.2 |
| React | 16.8.6 |
| System | Mac |
| Browser | Chrome Version 75.0.3770.142 (Official Build) (64-bit) |

---
This error is coming from the last few hours only. And it looks like that few hours back something is changed in css-animation repo which is breaking the application. Please check

**Comment by shamseerahammedm** [comment]
This just happened a few hours ago I believe, everything was working till evening and then bang.

**Comment by ashvin777** [comment]
Yes and the culprit is css-animation package. Because few hours back it was updated to latest version 1.6.0 and since we have declared the package dependency such as ^1.5.0 it took the 1.6.0 and broke the build. Removing ^ from antd package.jaon will fix this problem.

Make sure always use fixed version because such upgrades can lead to unwanted failures.

**Comment by shamseerahammedm** [comment]
@ashvin777 I am using create-react-app and i dont have this css animation thing in my dependancy list of package json file ? how i can revert back to the version u mentioned?

**Comment by guyb7** [comment]
@shamseerahammedm if you're using yarn, add this to your package.json and run yarn again:
```json
"resolutions": {
  "css-animation": "1.5.0"
}
```

**Comment by jasonbellamy** [comment]
This is broken for us as well as of a couple of hours ago.

**Comment by stolenng** [comment]
Having same issue :/

**Comment by fostergn** [comment]
I wish I had checked this a few hours ago. Seeing the same thing

**Comment by Nilegfx** [comment]
same here, and [this](https://github.com/ant-design/ant-design/issues/17928#issuecomment-515718166) fixed it "temporarily"

**Comment by Nilegfx** [comment]
css-animations already release 1.0.7 which solves this issue, just reinstall your packages and things will work just fine.

**Comment by Nilegfx** [comment]
I had the same issue, @guyb7 [comment](https://github.com/ant-design/ant-design/issues/17928#issuecomment-515718166) fixed it temporarily.

**Comment by shaodahong** [comment]
Because of @yiminghe change `css-animation` output directory, so `antd` not-found

```
// old output 
- es
- lib

// now
- dist-src
- dist-web
```

**Comment by hansfpc** [comment]
How to (temporarily?) fix:

- `yarn add css-animation`

- go to package.json and add: 

```
"resolutions": {
  "css-animation": "1.5.0"
}
```

**Comment by stacksoda** [comment]
you can add
`
alias: {
            "css-animation/es/Event": "css-animation/dist-src/Event"
        }
`
in your webpack.config.js

**Comment by kenlist** [comment]
"resolutions": {
  "css-animation": "1.5.0"
}
worked.

**Comment by CarberryChai** [comment]
> you can add
> `resolve: { ... alias: { "css-animation/es/Event": "css-animation/dist-src/Event" } }`
> in your webpack.config.js.
> It will make your webpack find the Event.js

这个管用！

**Comment by ekatzenstein** [comment]
Note on @stacksoda's comment: this worked for me if I also have css-animation in my root. `npm install --save css-animation@latest`

**Comment by ChaeWonKong** [comment]
change import statement would help:

from /antd/es/_util/wave.js:

`javascript
// Change 'es' to 'dist-src'
import TransitionEvents from "css-animation/dist-src/Event";
`

**Comment by Hudsonzp** [comment]
Added the following to my webpack config:
```
resolve: {
    alias: { 'css-animation/lib/Event': 'css-animation/dist-src/Event' },
  },
```

and 
`"css-animation": "1.6.0", to my package.json depencies.`

**Comment by zhouhaoxiang** [comment]
resolve: {
    alias: { 'css-animation/es/Event': 'css-animation/dist-src/Event' },
  },

resolve: {
    alias: { 'css-animation/lib/Event': 'css-animation/dist-src/Event' },
  },

根据错误信息， 修改路径

**Comment by ppremk** [comment]
Hi stuck with this same issue too. Is there any examples on how to resolve using the `config-overrides.js` with react-app-rewired? Thanks in advance!

**Comment by shamseerahammedm** [comment]
added `"css-animation": "1.5.0",` to my devDependencies and resolutions in my package.json file. I did `npm uninstall` after than and then again `npm install` after , it worked for me. you need the exact 1.5.0 version of css-animation for this to work.
My package.json file 
```
"devDependencies": {
    "antd": "^3.20.7",
    "axios": "^0.19.0",
    "css-animation": "1.5.0",
    "react-router-dom": "^5.0.1"
  },
  "resolutions": {
    "css-animation": "1.5.0"
  }
```

**Comment by HEROGWP** [comment]
Reason:
https://github.com/ant-design/ant-design/issues/17928?fbclid=IwAR3ujRy4NHX_erU0vRSYVWNjg6CvMtzTk88l2tYaoN-AI5Mmmh3Mug-Z2x0#issuecomment-515713272

**Comment by zombieJ** [comment]
reinstall node modules.  css-animation patch fixed now.

**Comment by vidhu** [comment]
@zombieJ In retrospect, would it be work pinning package versions to avoid something like this in the future?

**Comment by ppremk** [comment]
The solution proposed in this [comment](https://github.com/ant-design/ant-design/issues/17928#issuecomment-515762819) by user @shamseerahammedm worked for me. I had also deleted the node_modules folder and reinstalled to be sure. Thanks!

**Comment by zombieJ** [comment]
Lock version is long discussion story in the node module management. Lock version may cause fragmentation in module side, and if some fix will also miss with this. And also, if a package depends on another with another with another package patch a bug. It's out of antd side control of lock version.

In project side, you can use `package-lock.json` or `yarn.lock` to lock the version you want.
