### ISSUE TITLE
Hover styles on row not working if table has small size

### ISSUE THREAD

**Issue by kamilszkutnik** [ant-design/ant-design#17922]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-morse-i7ftp)

### Steps to reproduce
Set size for table to small, then check how hover mouse working on rows in table.

### What is expected?
Row should change background color on hover.

### What is actually happening?
Valid class is added to tr, but some styles override background: color to transparent, so on ui user will not see change.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | MacOS 10.14.3 |
| Browser | Chrome 75.0.3770.100 |

**Comment by sonhgc00016** [comment]
same here

**Comment by afc163** [comment]
It is by designed.
