### ISSUE TITLE
Chart tab keeps growing when it is contained in a flex layout and the chart is configured as forceFit

### ISSUE THREAD

**Issue by j14bis** [ant-design/ant-design#17934]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/j14bis/pen/qeqGGr?editors=1010](https://codepen.io/j14bis/pen/qeqGGr?editors=1010)

### Steps to reproduce
Click Tab 2

### What is expected?
The "Tab 2" tab panel shows a chart once it is activated.

### What is actually happening?
The tab panel's width keeps growing 

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8 |
| System | Windows 10 |
| Browser | Chrome 75.03770 |

---
It happens when the tabs are placed in a 'row' flex layout where the tabs flex is set to 1 and the chart is set to be 'forceFit'

**Comment by huntdream** [comment]
encountered same issue before, my solution is to set a width to the `flex: 1` div with specific pixel, the width you set will be the minimal width to the div

**Comment by zombieJ** [comment]
You can set `width` of `flex: auto` item to help browser calculate the size: https://codesandbox.io/s/ancient-glade-0034d

**Comment by j14bis** [comment]
@huntdream The work around solution you proposed does work. Thanks.

**Comment by j14bis** [comment]
@zombieJ @ant-design-bot 
I disagree this is a usage issue because it is not a standard way of using 'flex: 1' by specifying a 'width' attribute. Also, it only becomes a problem when more than one tabs are used and one of the tab contains a chart with 'forceFit=true'.

Please keep the issue open as a bug so that it can be improved and others won't fall into the same crack. To fundamentally fix the problem, I suspect it requires someone who is both familiar with the implementation of 'Tabs' and with 'Chart resizing'.

**Comment by j14bis** [comment]
Also, in a more complicated layout situation it can be really difficult for a developer to figure out what is going on. The example I posted to reproduce the problem has been largely simplified and is the result of a full day's of debugging work on the real product I've been developing.

**Comment by zombieJ** [comment]
Hi @j14bis ,
Thanks for feedback. But it's not a bug of Tab, it's related with the flex layout module calculation. We can do nothing about this.

**Comment by j14bis** [comment]
@zombieJ 
Yes or no. How do you explain that it is only an issue when there are two tabs? Maybe it has something to do with how tabs are managed. This could be the argument from the BizCharts side. That's why I'm afraid issues like this can easily fall through the crack.

**Comment by zombieJ** [comment]
Thanks for reply, could you help to send PR if you have interested?

**Comment by j14bis** [comment]
Ok I'll see how I can help when I get a chance. Thanks.
