### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by Doubi666** [ant-design/ant-design#17931]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://127.0.0.1](http://127.0.0.1)

### Steps to reproduce
新建安装的react应用，引入antd组件后按照官方文档的配置运行，出现如下报错:

./node_modules/antd/es/_util/wave.js
Module not found: Can't resolve 'css-animation/es/Event' in 'D:\react_first\node_modules\antd\es\_util'

### What is expected?
解决的过程思路

### What is actually happening?
解决的方案

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.X |
| System | win10 |
| Browser | Google Chrome 73.0.3683.86 |

**Comment by SagiSan** [comment]
I have the same issue. Plz help

**Comment by xuqplus** [comment]
刚刚排查了这个问题..
原因应该是antd依赖的一个项目刚刚更新了一次... => 该项目地址(https://github.com/yiminghe/css-animation)

**Comment by xuqplus** [comment]
应急的解决方法如下, 路径问题, 把import和requere的路径都改下就好了

 * css-animation/es/Event in ./node_modules/antd/es/_util/wave.js
 * css-animation/lib/Event in ./node_modules/antd/lib/_util/wave.js

es/_util/wave.js, line 21:
  import TransitionEvents from "css-animation/dist-src/Event";
es/_util/wave.js line 12:
  var _Event = _interopRequireDefault(require("css-animation/dist-src/Event"));

**Comment by xuqplus** [comment]
require, 官方后来会修复的

**Comment by xuqplus** [comment]
参考 https://github.com/ant-design/ant-design/issues/17928
改下 dependency version=> "css-animation": "1.5.0"

**Comment by aminsoheyli** [comment]
I have the same issue.

**Comment by zombieJ** [comment]
reinstall node modules.  css-animation patch fixed now.

**Comment by Doubi666** [comment]
> I have the same issue. Plz help

I don't have a solution yet.

**Comment by Doubi666** [comment]
> 参考 #17928
> 改下 dependency version=> "css-animation": "1.5.0"

非常感谢，我尝试一下

**Comment by Doubi666** [comment]
> reinstall node modules. css-animation patch fixed now.

非常感谢，我尝试过了，好像没有效果

**Comment by Doubi666** [comment]
> > 参考 #17928
> > 改下 dependency version=> "css-animation": "1.5.0"
> 
> 非常感谢，我尝试一下



> 参考 #17928
> 改下 dependency version=> "css-animation": "1.5.0"

早上比较忙，但是还是抽时间出来测试了一下，发现这个方法可行，完美解决，非常感谢你百忙之中给出解答~
