### ISSUE TITLE
关于主题的建议

### ISSUE THREAD

**Issue by kevinwon1985** [ant-design/ant-design#1793]
现在所有组件的less中都引入了@import "../../style/themes/default";

在使用npm引入antd的情况下，导致不修改node_modules/antd下的主题文件是无法自定义主题的。
而通常，node_modules下的东西我们是不会保存到git之类的版本管理数据里，所以通过修改node_modules/antd下的主题文件来自定义主题不可取。

因此建议取消组件的less文件中对主题的引入。

这样，我们可以在外部通过antd中定义的less变量，和引入相应的主题less来达到自定义主题的目的。

**Comment by kevinwon1985** [comment]
例如：
`
@primary-color          : darken(#428bca, 6.5%);
@info-color             : #5bc0de;
@success-color          : #5cb85c;
@error-color            : #d9534f;
@warning-color          : #f0ad4e;

@import "~bootstrap/less/buttons.less";
`
通过在我的工程中，自定义这样的less文件，我就拥有了bootstrap默认主题的antd的按钮。

**Comment by liekkas** [comment]
+1

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme#less

先试试这个。

**Comment by afc163** [comment]
第三种方法好像确实失效了，我看看。

**Comment by liekkas** [comment]
@afc163 能否保留原来的style包，如果想做深层次修改的话就得到具体某个组件了，因为还有一些组件的样式是写死的，这样我只要拷贝style包出来修改提交git就行。

**Comment by afc163** [comment]
这个已经拆到各个模块中了，回不去了~~

**Comment by kevinwon1985** [comment]
@afc163 antd-init中的1，2方法，我没试过，也不想试，在webpack的配置文件里配置less变量的方式太丑了。我用的是第三种方式，这种方式是无效的，因为各个组件的less中又再次引入了themes/default.less，导致自定义的less变量又被覆盖了。

**Comment by kevinwon1985** [comment]
我现在用了一个也比较丑的办法就是，在webpack.config.js里吧我的定义主题变量的less文件拷到antd中，覆盖default.less

**Comment by kevinwon1985** [comment]
其实修改方法很简单，就是把lib/component*/style/index.less中`@import "../../style/themes/default";`去掉。就能满足方便的自定义主题和引入单个组件样式的需求。这样也不会影响其他用法。

**Comment by afc163** [comment]
你试试跑下我那个例子，我本地测试修改 `primary-color` 是有效的。

**Comment by afc163** [comment]
不行的，单独引入某个组件时就会报编译错误。

**Comment by afc163** [comment]
点错了

**Comment by afc163** [comment]
你要先引用默认的 less 变量文件，再进行覆盖，这样下面组件内引用的 `themes/default.less` 就已经被合并到前面来了。

```
@import "~antd/lib/style/themes/default.less";
@import "your-theme-file"; // 用于覆盖上面定义的变量
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";
```

**Comment by kevinwon1985** [comment]
@afc163 这几天忙。。实在没空测试为啥你们这个可以。空了再试下。我的代码是这样的：
`@import "your-theme-file"; // 用于覆盖上面定义的变量
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";
`
直接定义了一份包含全部变量的主题less， 跟你的比，少引入了`themes/default.less`。
不过就在打字的时候我想到一个可能性，会不会是因为你主动引入了`themes/default.less`，那么在后面组件的style里在引入的时候，就不会再次引入了。

而我没有主动引入，组件的style里再引入的时候，就把这个文件在我的主题less之后引入，又覆盖了我定义的主题文件。我现在去试试

**Comment by kevinwon1985** [comment]
@afc163 已经测试过了。确实是必须先引入默认主题less 。 `@import "~antd/lib/style/themes/default.less";`

**Comment by xd19831203** [comment]
@primary-color 修 改是有效的，可是修改字体是无效的，进了组件的样式里看一眼就懵比了……里面直接写的“12px"

**Comment by yesmeck** [comment]
@xd19831203 如果发现可以用 less 变量，但是没有用的地方可以提 PR。

**Comment by chinawzc** [comment]
为什么我的没效果。。。。。
import "antd/lib/style/themes/default.less"
import './index.less'
import "antd/lib/style/core/index.less"
import "antd/lib/style/components.less"

**Comment by kevinwon1985** [comment]
@chinawzc 
```
@import "~antd/lib/style/themes/default.less";
@import "your-theme-file"; // 用于覆盖上面定义的变量
@import "~antd/lib/style/core/index.less";
@import "~antd/lib/style/components.less";
```
注意antd前面的`~`

**Comment by chinawzc** [comment]
@kevinwon1985  
谢谢  
我之前写在index.js文件里了，现在写在.less文件里就好了

**Comment by xuhen** [comment]
how did you guys config you webpack to parse the less files, need some guid there.

**Comment by zmGitHub** [comment]
@afc163 你好 老哥 在 webpack 中定制主题中 官方文档存在一些问题:
webpack(4.27.1) 如果要覆盖 antd 的样式 其中:
`["import", {"libraryName": "antd", "libraryDirectory":"es", "style": true}]`
不能放在 .babelrc中 这样死活不生效
只有放在:
![image](https://user-images.githubusercontent.com/6838405/50678314-0a177300-1039-11e9-874d-994b02b0fdff.png)

能否在文档中说明 或者有更好的解决方案
