### ISSUE TITLE
在create-react-app中配置antd按需加载会报错

### ISSUE THREAD

**Issue by mwj666** [ant-design/ant-design#17933]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-with-create-react-app-cn](https://ant.design/docs/react/use-with-create-react-app-cn)

### Steps to reproduce
1.npm install antd

2.npm install react-app-rewired customize-cra

3./* package.json */
"scripts": {
   "start": "react-app-rewired start",
  "build": "react-app-rewired build",
  "test": "react-app-rewired test",
}

4.然后在项目根目录创建一个 config-overrides.js 用于修改默认配置。

module.exports = function override(config, env) {
  // do stuff with the webpack config...
  return config;
};

5.npm insatll babel-plugin-import

6.修改 config-overrides.js文件
 const { override, fixBabelImports } = require('customize-cra');
 module.exports = override(
   fixBabelImports('import', {
     libraryName: 'antd',
     libraryDirectory: 'es',
     style: 'css',
   }),
 );

7.然后移除前面在 src/App.css 里全量添加的 @import '~antd/dist/antd.css'; 样式代码，并且按下面的格式引入模块。
  // src/App.js
  import React, { Component } from 'react';
- import Button from 'antd/es/button';
  import { Button } from 'antd';

8.npm start

### What is expected?
正常显示内容

### What is actually happening?
Failed to compile

./node_modules/antd/es/_util/wave.js
Module not found: Can't resolve 'css-animation/es/Event' in 'E:\WebStrom\workspace\react-admin_client1\node_modules\antd\es\_util'

This error occurred during the build time and cannot be dismissed.

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 16.8.6 |
| System | win10 |
| Browser | Google Chrome75.0.3770.100 |

---
都是按照https://ant.design/docs/react/use-with-create-react-app-cn做的，不知道为什么会报错

**Comment by aminsoheyli** [comment]
I have the same problem!

**Comment by BruceHong666** [comment]
same

**Comment by BruceHong666** [comment]
[#17928 ](https://github.com/ant-design/ant-design/issues/17928)

- use old dependencies(I try this)：使用旧的依赖，我是这么干的
package.json
```
 "resolutions": {
    "css-animation": "1.5.0"
  }
```

or you can try this
- change the alias to resolve can't find path:使用别名，让错误的路径指向正确的路径
```
resolve: {
alias: { 'css-animation/es/Event': 'css-animation/dist-src/Event' },
},

resolve: {
alias: { 'css-animation/lib/Event': 'css-animation/dist-src/Event' },
},
```

**Comment by zombieJ** [comment]
reinstall node modules.  css-animation patch fixed now.
