### ISSUE TITLE
Form组件会将我的错误隐瞒掉

### ISSUE THREAD

**Issue by cyj1209** [ant-design/ant-design#17944]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-my7fv?fontsize=14)

### Steps to reproduce
在输入框中输入，我一开始设置了最小的长度是6，但是我下面的自定义的validate里面有错误，不会被捕获到，导致了终止了我的验证，不会在下面显示我的message信息了

### What is expected?
就是反馈一下，看看是不是一个bug

### What is actually happening?
自定义的验证器中的错误需要我自己手动捕获在抛出，不然就会被form隐藏掉。

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | windos |
| Browser | 版本 75.0.3770.142（正式版本） （64 位） |

---
一直在用你们的组件库，辛苦了

**Comment by cyj1209** [comment]
如果注释掉我自定义的代码就是正常的会显示message的情况

**Comment by zombieJ** [comment]
表单验证会等待所有 rule 都结束统一返回以展示所有错误信息，你自定义验证没有调用 `callback` 导致表单一直在等待你的验证结果。

**Comment by cyj1209** [comment]
加上callback 也一样，例子里面我没加了

Ant Design GitHub Bot <notifications@github.com> 于2019年7月29日周一 下午5:06写道：

**Comment by cyj1209** [comment]
我例子里面是想说我在我的方法里面调用了this.a.foreach()，我根本没有a字段。在undefined上面调用forEach
会报错。但是这个错误并没有抛出来。而是中断了整个验证除非我收到的try catch才能在控制台上看到错误

yongjun cao <959584026cyj@gmail.com> 于2019年7月29日周一 下午5:37写道：

**Comment by cyj1209** [comment]
你可以打开我的例子加上callback 看看，照样是不会显示应该检测出来的message

yongjun cao <959584026cyj@gmail.com> 于2019年7月29日周一 下午5:41写道：

**Comment by zombieJ** [comment]
一样的，你代码报错了就没有调用到 callback。改成：
```js
try {
   isExit(flag.getUsernameFlag(value), "用户名", callback);
} catch(err) {
  callback(err);
} finally {
  callback();
}
```

**Comment by cyj1209** [comment]
懂了，谢谢，就是报错了也得调用callback


zombieJ <notifications@github.com> 于2019年7月29日周一 下午5:46写道：

**Comment by cyj1209** [comment]
刚刚回去仔细看了文档的链接，发现以前就有探讨，没有仔细看文档，增加了你的工作量，不好意思😐

yongjun cao <959584026cyj@gmail.com> 于2019年7月29日周一 下午5:49写道：
