### ISSUE TITLE
DatePicker onChange event typing error

### ISSUE THREAD

**Issue by pihentagy** [ant-design/ant-design#17949]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/onchange-typing-u3wcb)

### Steps to reproduce
Correct typing. When you select a date and after that use the X button to clear the date, the onChange handler will get null as a first argument.

### What is expected?
Correct typing of datePicker

### What is actually happening?
When you press the X on a datePicker, you will get null, not a valid moment.Moment

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.9 |
| System | irrelevant |
| Browser | irrelevant |

---
"Offending" line: https://github.com/ant-design/ant-design/blob/master/components/date-picker/interface.tsx#L35

**Comment by KuthorX** [comment]
I think this makes sense. Since you clear the DatePicker's value, onChange will get null value, or any other values will confuse developers

**Comment by pihentagy** [comment]
That's fine having a null value. The mentioned line should be:
```
onChange?: (date: moment.Moment | null, dateString: string) => void;
```

**Comment by pihentagy** [comment]
Btw how come `onChange` accepts `moment.Moment | null` but `disabledDate` `moment.Moment | undefined`? :confused:
