### ISSUE TITLE
动态配置Input的suffix会导致输入失去焦点

### ISSUE THREAD

**Issue by janryWang** [ant-design/ant-design#17947]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/beautiful-brook-sgpb1)

### Steps to reproduce
持续输入

### What is expected?
不失焦

### What is actually happening?
输入少量字符就会失去焦点

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
https://ant.design/components/input-cn/#FAQ
