### ISSUE TITLE
Menu组件，设置openKeys属性后，在缩小时，会自动弹出submenu的浮动样式，且与收起的菜单栏不对齐。

### ISSUE THREAD

**Issue by 826327700** [ant-design/ant-design#17946]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/OKWjoR?editors=0010](https://codepen.io/anon/pen/OKWjoR?editors=0010)

### Steps to reproduce
点击预览页面中的【收起】按钮，左侧栏收起，收起时，自动弹出submenu的浮动样式。

### What is expected?
收起时，不弹出submenu的浮动样式，或者即使自动弹出浮动样式，也应该与收起的菜单宽度对齐。

### What is actually happening?
收起时，自动弹出submenu的浮动样式。

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.1 |
| System | window |
| Browser | chrome 75.0.3770.142 |

---
当menu组件设置openKeys属性时才会发生以上问题。

**Comment by afc163** [comment]
展开是合理的，错位的问题和 #17174 重复。

**Comment by aforme** [comment]
just like this 
https://codepen.io/aforme/pen/wVyYzm
