### ISSUE TITLE
expandedRowRender和bordered属性冲突

### ISSUE THREAD

**Issue by guoxunbo** [ant-design/ant-design#17948]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-nested-table](https://ant.design/components/table-cn/#components-table-demo-nested-table)

### Steps to reproduce
> 我已知的是嵌套表格和fixed无法混用，和bordered也不能混用么？
- 在现有的`表格`上的`嵌套表格`上的外层table上直接添加个bordered属性就会出现样式错乱

### What is expected?
期望样式不变。但有表格边框

### What is actually happening?
样式改变，边框样式错乱

| Environment | Info |
|---|---|
| antd | 3.16.6 |
| React | 16 |
| System | macosx |
| Browser | chrome |

**Comment by afc163** [comment]
设计上里面那个表格是没有边框的，如果希望有，最好自行样式调整，这边没有提供这样的设计。
