### ISSUE TITLE
`current` for `Steps` should be optional in documentation

### ISSUE THREAD

**Issue by opiation** [ant-design/ant-design#17957]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-sound-mqu0m)

### Steps to reproduce
<Steps current={null}>
  <Step title="Step 1" />
  <Step title="Step 2" />
</Steps>

### What is expected?
According to the [documentation][0], the `current` props is required (since other optional props are explicitly marked as _optional_) and must be a `number`.  Thus, I expect rendering to fail.

[0]: https://ant.design/components/steps/#Steps

### What is actually happening?
The <Steps> component renders fine simply with no highlighted step.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 15 |
| System | Ubuntu 18.04 |
| Browser | Chrome 75 |

---
Having no selected <Step> seems to be supported and so the `current` prop should be documented as optional.

**Comment by ztplz** [comment]
First of all, sorry to make you confused. Most of `API` of `antd` are optional, so we have no special indication. The default value also has this meaning, if you don't set it, use the default value.
@afc163  Maybe we can add the `required` flag to the `antd@4.0` document to make the document clearer.

**Comment by opiation** [comment]
No problem.  I assumed that properties not marked as _optional_ were required because:
- `Steps.Step.description` has _optional property_ in the documentation
- `Steps.Step.icon` has _optional property_ in the documentation
- `Steps.Step.status` has _Optional values are: `wait` `process` `finish` `error`_ in the documentation

If _most_ props are optional, it may then be helpful to explicitly document those which are _required_ as such.  Or, for the typescript/flow community, perhaps suffixing the types with `?` may well indicate a prop being optional.

In any case, you know best what intent you wish to convey in your documentation.  I was only pointing out some inconsistencies between optional/required component props.  Thanks for the quick response!  Cheers!

**Comment by ztplz** [comment]
I noticed this, and some inconsistent descriptions of apis have caused confusion for users. But this may be the work of 4.0. In fact, not only the documentation of this component needs to be clear.

**Comment by opiation** [comment]
Sounds good.  I'm not sure then what would be an appropriate use or categorization for this issue.  If this won't be fixed in 3.x but will in 4.x, perhaps you can close this as some _won't fix_-like status.

**Comment by afc163** [comment]
I prefer `current={-1}` when you don't need any highlighted step.
