### ISSUE TITLE
Table Filter执行筛选后，react脚本中提示错误

### ISSUE THREAD

**Issue by iambluebird** [ant-design/ant-design#1795]
antd版本  1.1.0
react版本 15.0.2

按照官方DEMO里的TABLE，配置好Filter部分的代码

filters: [
                    {
                        text: '管理员',
                        value: '管理员',
                    },
                    {
                        text: '客服人员',
                        value: '客服人员',
                    }
                ],
                filterMultiple: false,
                onFilter: (value, record) => record.RoleName.indexOf(value) === 0,

选择一项并点确定后，控制台输出错误提示

Uncaught TypeError: o.onChange is not a function
react-with-addons.min.js:14

筛选没有效果，数据没发生变化。

请问这是antd的问题还是我代码的问题？我这检查了好几遍了，代码都是按照官方DEMO来做的。
谢谢

**Comment by afc163** [comment]
麻烦提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
。。。。。。。。。。。。。追着要重现，各种没反馈也是难做。

**Comment by iambluebird** [comment]
家里出了点事，回了趟老家
我去整理一下代码 下午发上来
