### ISSUE TITLE
validator自定义表单验证代码异常无抛出

### ISSUE THREAD

**Issue by Kreedzt** [ant-design/ant-design#17954]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/kreedzt/pen/KOaeNB?editors=0011](https://codepen.io/kreedzt/pen/KOaeNB?editors=0011)

### Steps to reproduce
1.使用getFieldDecorator注册表单
2.对表单项中rule使用validator执行错误的代码
3.验证无任何信息

### What is expected?
在控制台输出报错信息，方便开发阶段调试

### What is actually happening?
验证代码异常，但无任何信息输出

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8 |
| System | windows/macos |
| Browser | chrome 75.0.3770.142 / firefox 68.0.1 |

---
当表单验证抽离为公共方法时，该结果可能影响较大

**Comment by Kreedzt** [comment]
导致最后表单验证validateFields时函数无法成功调用

**Comment by afc163** [comment]
<img width="445" alt="图片" src="https://user-images.githubusercontent.com/507615/62051020-0d788300-b245-11e9-87d3-f7d1c892e6b8.png">

这不是有输出么。

**Comment by Kreedzt** [comment]
> 
> 
> <img alt="图片" width="445" src="https://user-images.githubusercontent.com/507615/62051020-0d788300-b245-11e9-87d3-f7d1c892e6b8.png">
> 
> 这不是有输出么。

我后来又改了下codepen的内容，
输入整数时候validateFields无法调用了，因为验证代码报错了，但是信息没有输出

**Comment by afc163** [comment]
确实有点问题，错误直接被吞掉了：https://codepen.io/anon/pen/bXgmOj?editors=0011

@zombieJ

**Comment by zombieJ** [comment]
和 #17944 一样，你要么使用 asnyc 将函数返回为一个 Promise，要么就用 try catch 保住始终确保 `callback` 被调用到。

**Comment by zombieJ** [comment]
我去更新一下 FAQ
