### ISSUE TITLE
the margin of the icon under the table placeholder

### ISSUE THREAD

**Issue by Jiang-Xuan** [ant-design/ant-design#17950]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-boyd-bdu8t)

### Steps to reproduce
1. goto https://codesandbox.io/s/quizzical-boyd-bdu8t
2. you should see ![](https://i.loli.net/2019/07/29/5d3ebe3031a9d33008.png)

### What is expected?
the icon has no margin right

### What is actually happening?
the icon has margin right

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.9.0 |
| System | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 |

---
code location: https://github.com/ant-design/ant-design/blob/1f8f4bca2dc74ecb1fcf274bb14ededc7b670cb8/components/table/style/index.less#L425

May be this is not a bug, but i don't understand why added this style 🧐.

**Comment by KuthorX** [comment]
> May be this is not a bug, but i don't understand why added this style 🧐.

After I remove `<br />` and
```html
<div>
  <Icon type="question" />
  <span>no Data</span>
</div>
```
I find that the `margin-right: 4px` may be used to this situation: icon and text at the same line and don't want to developer do extra margin work. 
But it seems that it makes opposite effect.

**Comment by Jiang-Xuan** [comment]
@KuthorX @yesmeck 

I think this style can be controlled by developer, rather than framework.

Another, document is not include this also 😅.
