### ISSUE TITLE
Table Pagination - Please add "all" option to pageSizeOptions

### ISSUE THREAD

**Issue by eyildiz** [ant-design/ant-design#17953]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Almost every pagination patterns includes "all" option. User needs all data in some circumstances such as exporting table to excel, etc. That's why we need this feature.

### What does the proposed API look like?
example usage : pageSizeOptions = ['10', '20', '30', 'all']

**Comment by KuthorX** [comment]
Maybe duplicated with [#4501](https://github.com/ant-design/ant-design/issues/4501)

**Comment by afc163** [comment]
No plan for now.

**Comment by nikzanda** [comment]
@afc163 Will this feature be considered in the future? Is there currently a workaround?
