### ISSUE TITLE
form表单域disabled为true时，是不是自动禁用校验规则呢？

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design#1796]
现在是每个都单独写个验证方法

**Comment by benjycui** [comment]
现在 `getFieldProps` 无法感知表单域是否 disabled，更多参见：https://github.com/ant-design/ant-design/issues/1533

现在你可以在某个表单域 disabled 时同时设置 `rules` 为 空数组，毕竟这两个都是外部传入的。
