### ISSUE TITLE
Timeline mode支持左右同时显示风格

### ISSUE THREAD

**Issue by fifsky** [ant-design/ant-design#17966]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当前的timeline mode支持 left right和左右轮替显示alternate，是否可以添加一个选项，支持在同一行左右都可以显示内容，比如左边显示时间，右边显示事件内容，比如：
```
2015-09-01  O  Create a services site  
            |
2015-09-01  O  Solve initial network problems 
            |
2015-09-01  O  Technical testing
```

### What does the proposed API look like?
```
<Timeline>
    <Timeline.Item lable="2015-09-01">Create a services site</Timeline.Item>
    <Timeline.Item lable="2015-09-01">Solve initial network problems</Timeline.Item>
    <Timeline.Item lable="2015-09-01">Technical testing</Timeline.Item>
</Timeline>
```

**Comment by MrHeer** [comment]
May be I can try it

**Comment by MrHeer** [comment]
Need to add a new mode?

**Comment by xrkffgg** [comment]
see https://github.com/ant-design/ant-design/pull/18032 😏

**Comment by xrkffgg** [comment]
还有点问题。。。有点不太对，我再改改

**Comment by Kermit-Xuan** [comment]
I will work it.
