### ISSUE TITLE
<Icon> component does not render custom SVG well & also mentioned props for custom icon component does not work

### ISSUE THREAD

**Issue by vidushigupta** [ant-design/ant-design#17962]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-08w2u)

### Steps to reproduce
Please check the example of codesandbox.
Step1 - take a custom svg icon. 
Step2 - render it in antD <Icon> component prop. It renders.
Step3 - now use <Icon> component prop 'type'. The custom SVG does not render anymore.
Step4 - Use the prop 'fill' - this does not effect the color of rendered custom SVG
Step5 - Use the prop 'width'/'height' - this does not effect the width / height of rendered custom SVG

### What is expected?
> 'Type' prop does not override 'component' prop when used both in same time.
> The props be working & customizing the rendered custom Icons dynamically

### What is actually happening?
> Prop 'component' is not overriding prop 'type'
> The props are not replicating the effect to SVG. There is no changes in the rendered Icon.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | MacOs Mojave |
| Browser | Chrome 75.0 |

---
As noticed in the code for <Icon> component in antD:-
> The innerNode is getting overridden by 'type' check
>  There is an 'i' element wrapping the actual SVG & the props are not propagating to actual SVG element.

**Comment by afc163** [comment]
Don't use `type` and `component` together, it is conflicted.

**Comment by vidushigupta** [comment]
As per the documentation - "The component used for the root node. This will override the type property.". Per this official documentation, it seems that when both the properties used, the component prop will override the type prop. Am I misinterpreting it???? Seems a bug, since ideally the component prop should be given precedence over type prop.

**Comment by vidushigupta** [comment]
Apart from the above issue, the other issue is that if I use the prop 'component', the props mentioned in the documentation does not work :( 

Example : In the below snapshot following definition does not effect the custom icon.

ReactDOM.render(<Icon component={MessageSvg}  fill={"red"}/>, mountNode);
ReactDOM.render(<Icon component={MessageSvg}  width={30px}/>, mountNode);

<img width="1514" alt="Screen Shot 2019-07-29 at 9 39 43 PM" src="https://user-images.githubusercontent.com/5883060/62101262-9e515d80-b249-11e9-9d55-67d4ca68e449.png">

**Comment by kanweiwei** [comment]
@afc163  https://github.com/ant-design/ant-design/blob/a111e6221cae3a0d7cd41a4f67444db779b8b6af/components/icon/index.tsx#L140 
这里component传进去的props都是写死的，中文文档里写的是只读值，英文的是default，这里造成了误解不对。

**Comment by ZengMX** [comment]
@kanweiwei 我的版本3.1.6的升级到3.20.2，本地图标会显示，用Jenkins升级的就不显示图标了，这中间的版本需要配置吗

**_3.1.6版本的_**
![image](https://user-images.githubusercontent.com/9668119/64686929-14d5b200-d4bc-11e9-91ab-0b6e94cb9009.png)

_**3.20.2版本的**_
![image](https://user-images.githubusercontent.com/9668119/64687069-63834c00-d4bc-11e9-9762-fc41373d575a.png)

**Comment by afc163** [comment]
@ZengMX 请检查是否加载了多份不同版本的 antd 的样式。

**Comment by afc163** [comment]
fixed in #18592

**Comment by ZengMX** [comment]
@afc163 Jenkins上如何检测是否加载多分antd样式

**Comment by yoyo837** [comment]
@ZengMX Jenkins 无关

**Comment by ZengMX** [comment]
@yoyo837 我本地升级的antd版本到20.2是正常显示图标的，没啥问题，主要是Jenkins上升级的antd就会不显示图标，这个图标加载和node版本有关吗

**Comment by yoyo837** [comment]
@ZengMX 不可能依赖node版本的，只能靠你自己调试定位...

**Comment by wuliupo** [comment]
> If anyone has stumbled upon this page looking for an answer, here's what worked for me:
> 
> ```js
> import MessageSvg from "./Message.svg";
> <Icon component={() => <MessageSvg fill="green"/>}/>
> ```
> 
> [Source](https://stackoverflow.com/questions/53004353/with-antd-custom-svg-icons-how-to-pass-props-down-to-svg)

How did you configured the webpack with config-overrides.js?
