### ISSUE TITLE
onFieldsChange called 3 times if setFieldsValue and validateFields

### ISSUE THREAD

**Issue by dibericky** [ant-design/ant-design#17960]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-scof1)

### Steps to reproduce
1) Click on the button "Click me!". ->  onFieldsChange will be called 3 times
2) Write something inside the input-text -> onFieldsChange will be called 2 times.

### What is expected?
If I type a character inside a inputText, onFieldsChange should be called once.
If I make a setFieldsValue and a validateFields, onFieldsChange should be called once. If not possible, could be useful a `setFieldValueAndValidate` function.

### What is actually happening?
onFieldsChange is called more than one time.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.9.0 |
| System | Ubuntu 18.04.2 LTS |
| Browser | Chrome 75 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5212#issuecomment-284972900
