### ISSUE TITLE
希望transfer能够自定义搜索栏，例如多条件搜索

### ISSUE THREAD

**Issue by zhoujun165** [ant-design/ant-design#17977]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义搜索栏，如根据多个条件进行搜索

### What does the proposed API look like?
searchBar={<ReactNode></ReactNode>}

**Comment by shaodahong** [comment]
使用 `filterOption` 可以的吧

**Comment by zhoujun165** [comment]
> 使用 `filterOption` 可以的吧

不行。我的意思是增加多个搜索组件，比如增加个下拉框，多选框等。

**Comment by afc163** [comment]
建议自定义 title 吧。
