### ISSUE TITLE
在 Typography.Paragraph 自动溢出省略中，能修改展开按钮的样式吗？我想做成像Dropdown 这样的下拉效果, 或者Dropdown 能限制隐藏行数吗

### ISSUE THREAD

**Issue by wzht1991** [ant-design/ant-design#17975]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能让我们做出更加个性化的网站

### What does the proposed API look like?
希望能提供一个属性来修改效果

**Comment by shaodahong** [comment]
这个可以自己包一层，然后自定义按钮来实现吧

**Comment by afc163** [comment]
```
<Paragraph ellipsis={{ symbol: '……' }} />
```

我们需要增加自定义省略符号才行。

**Comment by shaodahong** [comment]
恩，`symbol` 类型是 `string|ReactNode` 扩展更好

**Comment by fireairforce** [comment]
Try to solve it

**Comment by maze-runnar** [comment]
@afc163  can we enable the user to set the standard to expand icons as a prop in place of adding a string.
![Screenshot from 2020-05-27 17-43-23](https://user-images.githubusercontent.com/56407566/83019024-e39a1380-a043-11ea-83b8-dd5d60aeb0c7.png)

![Screenshot from 2020-05-27 17-40-15](https://user-images.githubusercontent.com/56407566/83019187-26f48200-a044-11ea-82f6-2661cf9590f4.png)

**Comment by maze-runnar** [comment]
for example <DownOutlined />, <DownCircleOutlined />, <CaretDownFilled />, <DownCircleTwoTone />, <DownSquareTwoTone />

**Comment by yoyo837** [comment]
Please try send a new PR for that.

**Comment by warmhug** [comment]
因为 suffix 只支持 string ，发现 symbol 既然是 ReactNode 类型，但真不必要跟 expand 行为绑定呀。
