### ISSUE TITLE
使用 browserHistory, 服务器能处理这个 URL 返回 index.htmlt跳转到404页面

### ISSUE THREAD

**Issue by CoCoyh** [ant-design/ant-design#17973]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/CoCoyh/ant-design-pro-egg](https://github.com/CoCoyh/ant-design-pro-egg)
@chenshuai2144 @afc163 
### Steps to reproduce
1. 打包前端页面
```
yarn build 
```
2. 将打包好的dist文件夹这个拷贝到egg-demo项目的/app目录下，dist改名为public
3. egg-demo的config.default.js文件中添加静态资源配置
```
config.static = {
    maxAge: 31536000,
    prefix: '/',
  };
```
4. 启动egg-demo
```
yarn dev
```
5. 访问页面localhost:7001/index.html，为404
<img width="969" alt="屏幕快照 2019-07-30 上午11 45 58" src="https://user-images.githubusercontent.com/24558814/62100392-270cdf80-b2c4-11e9-8a36-c8cfcc906585.png">

点击“back Home”跳到首页localhost:7002，正确显示
<img width="954" alt="屏幕快照 2019-07-30 下午12 09 12" src="https://user-images.githubusercontent.com/24558814/62100385-2116fe80-b2c4-11e9-9b89-f8cee91a9a14.png">

点击刷新页面，又错了
<img width="899" alt="屏幕快照 2019-07-30 下午12 16 10" src="https://user-images.githubusercontent.com/24558814/62100371-12304c00-b2c4-11e9-8eb6-12baf217c3a5.png">

看了官网[ant-design-pro](https://pro.ant.design/docs/deploy-cn)的解释：还是没明白怎么处理，：
![1564460489367_12_21_28__07_30_2019](https://user-images.githubusercontent.com/24558814/62100513-9682cf00-b2c4-11e9-9f18-f55acdb529ce.jpg)

我的demo代码仓库地址：
[https://github.com/CoCoyh/ant-design-pro-demo](https://github.com/CoCoyh/ant-design-pro-demo)
[https://github.com/CoCoyh/ant-design-pro-egg](https://github.com/CoCoyh/ant-design-pro-egg)

### What is expected?
访问/index.html正确显示或刷新其他页面路由

### What is actually happening?
1. 404
2. 页面的路由被当作了egg接口路由

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | react |
| System | mac 10.14.5 |
| Browser | chrome |

**Comment by afc163** [comment]
这不是 antd 的问题，这里只反馈组件库问题。

**Comment by CoCoyh** [comment]
@afc163 这个和打包没关系吗？
