### ISSUE TITLE
TreeSelect treeData reload, already loaded treeNode expand icon disappear  

### ISSUE THREAD

**Issue by murphywuwu** [ant-design/ant-design#17979]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/withered-monad-hfc0b)

### Steps to reproduce
展开一个节点后， 点击重新加载按钮， 节点前面的展开按钮消失

### What is expected?
treeNode expand icon exist

### What is actually happening?
treeNode expand icon disappear

| Environment | Info |
|---|---|
| antd | 3.16.3 |
| React | 16.8.6 |
| System | masOS Mojave 10.14 |
| Browser | chrome 75.0.3770.142 |

---
related issue: https://github.com/ant-design/ant-design/issues/10821

**Comment by zombieJ** [comment]
TreeSelect 没有暴露 `loadedKeys`，来个 PR 吧。

**Comment by lininn** [comment]
当    loadedKeys={[]},如果请求一级目录的某个子项返回的的是[],那么将陷入死循环,不断发送请求,直到浏览器卡死,如何解决?

**Comment by lininn** [comment]
属性值loadedKeys一直为[],时候,tree组件以前值可保留,但当返回子项为[],时候,tree会陷入死循环调用

**Comment by nicewahson** [comment]
有什么办法可以重置loadedkeys呢

**Comment by zombieJ** [comment]
@nicewahson 标记为 `help wanted` 的 issue 欢迎社区同学自发发 PR 添加支持。
