### ISSUE TITLE
The type of getPopupContainer of Dropdown is not precious and it will cause a type error when using TypeScript

### ISSUE THREAD

**Issue by ElizurHz** [ant-design/ant-design#17981]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/65eb713fe897f65bbf187e215c664e5f9b468252/components/dropdown/dropdown.tsx](https://github.com/ant-design/ant-design/blob/65eb713fe897f65bbf187e215c664e5f9b468252/components/dropdown/dropdown.tsx)

### Steps to reproduce
The API of dropdown has a link to the demo of getPopupContainer on https://codepen.io/afc163/pen/zEjNOy?editors=0010. In this page, the usage of getPopupContainer is `getPopupContainer={() => document.getElementById('area')}`, and there is also a default value `() => document.body` in the API documentation.
However, it will cause an error when using in TypeScript:
```
Type '() => HTMLElement | null' is not assignable to type '(triggerNode: HTMLElement) => HTMLElement'.
  Type 'HTMLElement | null' is not assignable to type 'HTMLElement'.
    Type 'null' is not assignable to type 'HTMLElement'.ts(2322)
```

### What is expected?
`(triggerNode?: HTMLElement) => HTMLElement | null`
Because `document.getElementById` could return a null value.

### What is actually happening?
Code running error

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.4 |
| System | macOS Mojave 10.14.5 |
| Browser | Chrome 75.0.3770.142 |

**Comment by afc163** [comment]
`document.getElementById('area') as HTMLElement`

**Comment by rohitKashyap-toddleapp** [comment]
> Member

please explain this

**Comment by roevieDev** [comment]
getPopupContainer={trigger => trigger.parentNode as HTMLElement}  for me this works the error not shown
