### ISSUE TITLE
ant-design --- 安装依赖后，npm start 老出一种错误。

### ISSUE THREAD

**Issue by wayso** [ant-design/ant-design#1798]
**# OS: windows 7/10**

C:\Users\Arvin\Documents\GitHub\ant-design (master) (antd@1.1.0)
λ npm start

> antd@1.1.0 start C:\Users\Arvin\Documents\GitHub\ant-design
> antd-tools run start

antd-tools run start
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Arvin\Documents\GitHub\ant-design\node_modules\antd-tools\node_modules\dora\bin\dora ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:429:9)
    at process._tickCallback (node.js:343:17)
    at Function.Module.runMain (module.js:477:11)
    at startup (node.js:117:18)
    at node.js:951:3

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Arvin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v4.1.1
npm ERR! npm  v3.8.1
npm ERR! code ELIFECYCLE
npm ERR! antd@1.1.0 start: `antd-tools run start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the antd@1.1.0 start script 'antd-tools run start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the antd package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     antd-tools run start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs antd
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls antd
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Arvin\Documents\GitHub\ant-design\npm-debug.log

以上错误我在两台机器上试过均有问题，请指教！

**Comment by superRaytin** [comment]
@sorrycc 知道吗？

**Comment by sorrycc** [comment]
antd-tool ? @benjycui 看下。

**Comment by benjycui** [comment]
`antd` 自身的开发不建议在 Windows 下搞，主要是我们没有 Windows 的环境，不需要也没精力去适配，见谅。

可以装个 Ubuntu，挺好用的。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1352
