### ISSUE TITLE
form.Item的 label会删除末尾`|`  应该是正则写错了

### ISSUE THREAD

**Issue by ilimei** [ant-design/ant-design#17980]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/blue-microservice-slidz)

### Steps to reproduce
<Form.Item label="||">
</Form.Item>

### What is expected?
label显示||

### What is actually happening?
label显示|

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16 |
| System | windows |
| Browser | chrome 75 |

---
看代码应该是正则写错了
原正则 ： labelChildren = (label as string).replace(/[：|:]\s*$/, '');
可能需要正则： labelChildren = (label as string).replace(/(：|:)\s*$/, '');

**Comment by afc163** [comment]
`|` 应该去掉。

**Comment by ilimei** [comment]
好吧

**Comment by afc163** [comment]
怎么关了？来个 PR 吧。

**Comment by shaodahong** [comment]
这个我改下吧
