### ISSUE TITLE
希望新增颜色选择组件

### ISSUE THREAD

**Issue by lazybear1017** [ant-design/ant-design#17998]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
方便直接在antd中调用，不用再额外的引入其他第三方库。

### What does the proposed API look like?
类似与日期选择组件一样，弹出可以选择颜色

**Comment by afc163** [comment]
https://casesandberg.github.io/react-color/ 很好用，要做到这个程度要花大量精力，我们就不重复造轮子了。
