### ISSUE TITLE
npm run dev 报错

### ISSUE THREAD

**Issue by marsDes** [ant-design/ant-design#1799]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。

If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

$ nmp run dev

## What you would like to happen

(e.g. I should be full)

## What actually happened

 info it worked if it ends with ok
1 verbose cli [ 'C:\\Soft\\nodejs\\node.exe',
1 verbose cli   'C:\\Soft\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@3.7.3
3 info using node@v5.8.0
4 verbose stack Error: missing script: dev
4 verbose stack     at run (C:\Soft\nodejs\node_modules\npm\lib\run-script.js:147:19)
4 verbose stack     at C:\Soft\nodejs\node_modules\npm\lib\run-script.js:57:5
4 verbose stack     at C:\Soft\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:345:5
4 verbose stack     at checkBinReferences_ (C:\Soft\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:309:45)
4 verbose stack     at final (C:\Soft\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:343:3)
4 verbose stack     at then (C:\Soft\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:113:5)
4 verbose stack     at C:\Soft\nodejs\node_modules\npm\node_modules\read-package-json\read-json.js:232:12
4 verbose stack     at C:\Soft\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:414:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
5 verbose cwd D:\Study\antdTest
6 error Windows_NT 10.0.10240
7 error argv "C:\\Soft\\nodejs\\node.exe" "C:\\Soft\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
8 error node v5.8.0
9 error npm  v3.7.3
10 error missing script: dev
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

## Online demo

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information

- The version of antd(1.1.1):
- Your operating system and it's version(win10):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by superRaytin** [comment]
antd-init 版本太低？方便的话麻烦贴一下 package.json 内容

**Comment by zhaojianrun** [comment]
你好，我按照快速上手的里指南操作（url:http://ant-tool.github.io/quick-start.html#reffn_1)
我运行cnpm run dev直接报错。
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\AlexanderZhao
\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\AlexanderZhao\
/mirrors/node" "--registry=https://registry.npm.taobao.org" "run" "dev"
npm ERR! node v6.2.0
npm ERR! npm  v3.9.2

npm ERR! missing script: dev
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\blog\npm-debug.log
我发现package.json里的scripts里没有dev
我手动加入了dev：
运行后还是有错：

Error: [Error] atool-build not found in D:\blo
    at resolvePlugin (D:\blog\node_modules\.np
    at D:\blog\node_modules\.npminstall\dora\0
    at Array.map (native)
    at resolvePlugins (D:\blog\node_modules\.n
    at createServer (D:\blog\node_modules\.npm
    at Object.<anonymous> (D:\blog\node_module
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.j
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by zhaojianrun** [comment]
加入的文本为："dev":"dora -p 8001 --plugins atool-build,proxy,hmr"
我又修改为：
"dev":"dora -p 8001 atool-build --plugins proxy,hmr"
出现如下提示：
> @ dev D:\blog
> dora -p 8001 atool-build --plugins proxy,hmr

          proxy: load rule from proxy.config.js
(node:18584) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
temp certs cleared
          proxy: listened on 8989
'openssl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'openssl' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
=============
rootCA generated at :
C:\Users\username\.anyproxy_certs
=============
rootCA generated
please trust the rootCA.crt in C:\Users\username\.anyproxy_certs\
or you may get it via anyproxy webinterface
请问我该如何操作？？

**Comment by superRaytin** [comment]
`"dev": "dora -p 8001 --plugins atool-build,proxy,hmr"` 这样跑起来是报什么错误呢？

**Comment by zhaojianrun** [comment]
刚才上面有发：
D:\blog>cnpm run dev

> @ dev D:\blog
> dora -p 8001 --plugins atool-build,proxy,hmr

D:\blog\node_modules\.npminstall\dora\0.3.2\dora\lib\plugin.js:83
        throw new Error('[Error] ' + pluginName + ' not found in ' + resolveDir);
        ^

Error: [Error] atool-build not found in D:\blog
    at resolvePlugin (D:\blog\node_modules\.npminstall\dora\0.3.2\dora\lib\plugin.js:83:15)
    at D:\blog\node_modules\.npminstall\dora\0.3.2\dora\lib\plugin.js:102:12
    at Array.map (native)
    at resolvePlugins (D:\blog\node_modules\.npminstall\dora\0.3.2\dora\lib\plugin.js:101:22)
    at createServer (D:\blog\node_modules\.npminstall\dora\0.3.2\dora\lib\index.js:61:44)
    at Object.<anonymous> (D:\blog\node_modules\.npminstall\dora\0.3.2\dora\bin\dora:32:20)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)

**Comment by zhaojianrun** [comment]
跟之前有个bug类似，跟npm start那个报webpack not found的错误。

**Comment by superRaytin** [comment]
#1790

**Comment by zhaojianrun** [comment]
对的，然而去掉单引号并没有用。

**Comment by superRaytin** [comment]
Ping @sorrycc

**Comment by zhaojianrun** [comment]
@sorrycc 你好，这个问题要怎样解决？谢谢。

**Comment by afc163** [comment]
`missing script: dev`

报错信息已经很清楚了吧，没有 dev 命令。https://github.com/ant-design/antd-init/blob/master/boilerplates/plain-react/package.json#L41

`npm start`

**Comment by afc163** [comment]
` throw new Error('[Error] ' + pluginName + ' not found in ' + resolveDir);` 的问题继续到 #1790 里跟踪。
