### ISSUE TITLE
Descriptions 换行问题

### ISSUE THREAD

**Issue by HowardTangHw** [ant-design/ant-design#17992]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hep4k?fontsize=14)

### Steps to reproduce
Descriptions.Item的内容超长后不会换行 会无限延申。

### What is expected?
为样式ant-descriptions-item-content加上word-break: break-all; 

### What is actually happening?
https://codesandbox.io/s/antd-reproduction-template-hep4k?fontsize=14

| Environment | Info |
|---|---|
| antd | 3.19.8 |
| React | 16.8 |
| System | WIN10 |
| Browser | chrome |

**Comment by HowardTangHw** [comment]
在` layout='vertical'` 模式下会更明显,容器宽度会被内容撑开,无限延申

**Comment by afc163** [comment]
`word-break: break-all;` 组件层面不宜统一加，这个会破坏英文单词断行，建议需要强制断词的地方自行包裹 div + style 来解决。

**Comment by dkvirus** [comment]
@afc163  

- 响应式布局下，大屏幕都能正常显示，但是小屏幕时就会截断，写的时候测试所有屏幕的显示状况不太现实。
- 给每个 Descriptions.Item 内部包裹 div + style(word-break: break-all;) 也是相当麻烦，属性很多时代码写起来麻烦，看起来也不好看。

建议：能否给 Descriptions 提供个属性 wordBreak，作用于所有子  Descriptions.Item ，至于用户想要使用什么值由用户自己决定好了。
