### ISSUE TITLE
The button type is Link, button's height auto and padding is 0, so is it more like a element?

### ISSUE THREAD

**Issue by zb188** [ant-design/ant-design#17996]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In some cases, our application wants to use the appearance of the a element. The actual operation is a button event. When the selection type is Link, the height is auto and padding is 0. Is it more like an a element?

### What does the proposed API look like?
The button type is Link ，height is auto and padding is 0
```css
.ant-btn-link{
    height: auto;
    padding: 0;
}
```

**Comment by afc163** [comment]
`<Button type="link" />` 和 `<a />` 不一样，设计上就是默认带 padding 的。
