### ISSUE TITLE
Antd 中文官网中 ‘快速上手’模块代码出现问题

### ISSUE THREAD

**Issue by mantionqwer** [ant-design/ant-design#17997]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/getting-started-cn](https://ant.design/docs/react/getting-started-cn)

### Steps to reproduce
在‘使用组件’的模块，替换了官方提供的 js 代码，该代码有bug。当把日期置为空时，出现日期format 错误

### What is expected?
当日期为空时，显示日期格式错误提示，而不是报错

### What is actually happening?
当日期置为空的时候或者逐个删除日期直至为空时，报错了

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.0 |
| React | latest |
| System | win10 |
| Browser | google |

---
将 handleChange 定义语块中的  message.info(`您选择的日期是: ${date.format('YYYY-MM-DD')}`);
改成 
date
      ? message.info(`您选择的日期是: ${date.format("YYYY-MM-DD")}`)
      : message.info(`日期错误`);
即可

**Comment by afc163** [comment]
感谢反馈，已修复。

下次可以点击此处直接发 PR：

<img width="460" alt="image" src="https://user-images.githubusercontent.com/507615/62199657-7c291e00-b3b6-11e9-8459-e8c85ba171b5.png">
