### ISSUE TITLE
Modal的Header和Footer，Less主题定制变量是否能提供更细节化一点？

### ISSUE THREAD

**Issue by wuchu** [ant-design/ant-design#17991]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Modal定制化主题Less变量，改不了头部的padding以及close按钮的大小等等，自带提供的theme定制太过简单😐：

```less
// Modal
// --
@modal-body-padding: 24px;
@modal-header-bg: @component-background;
@modal-footer-bg: transparent;
@modal-mask-bg: fade(@black, 65%);
```

### What does the proposed API look like?
改变padding值
```less
@modal-header-padding-vertical
@modal-header-padding-horizontal
@modal-footer-padding-vertical
@modal-footer-padding-horizontal
@modal-body-padding-vertical
@modal-body-padding-horizontal
```

改变close大小
```
@modal-close-x-size // 假如能暴露额外属性能调整边距最好了，不过源码宽高好像也是写死的...
```

改变高度
```
@modal-title-height or @modal-title-line-height
```

改变分割线样式或者宽度
```
@modal-header-border-xxx
@modal-footer-border-xxx
```

and, 其它组件细节定制，比如调整默认两个button顺序（UI设计妹子惹不起的），希望通过组件属性控制，而不是非要自己定制写一个Footer组件

**Comment by afc163** [comment]
可以发个 PR 来看看。

**Comment by fengyun2** [comment]
同求，其他空间都用了size="small", 边距都变窄了，唯独Modal组件的标题栏太高且没法通过全局变量定制...

**Comment by hicrystal** [comment]
May I work on it?

**Comment by xrkffgg** [comment]
> May I work on it?

PR welcome.
