### ISSUE TITLE
How can I reset all the filter in table filters with search text?

### ISSUE THREAD

**Issue by NevenLiang** [ant-design/ant-design#18001]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[example in docs](https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel)

Now the filter with search text can be set separately, and work together.

After I set more than one filter with search text, I need to reset the filter one by one if I want to display all the data on the table.

Also, after I set the filter with filter text, if I don't remember which filters I set, I need to check the filter text of each column one by one.

Any approach to do this?  

Thx a lot!

### What does the proposed API look like?
```js
<Button onClick={ () => this.resetFilters() }>Reset Filters</Button>

<Table resetFilters={ this.resetFilters }>
  <Columns />
  ...
</Table>
```

**Comment by afc163** [comment]
> I need to reset the filter one by one if I want to display all the data on the table.

Yeah, you have to reset one by one.

**Comment by mupinnn** [comment]
@NevenLiang heyy, how you configure it? i have the same problem right now, and can't find perfect answer for this issues

**Comment by caseychoiniere** [comment]
For anyone coming here looking for a way to do this and not satisfied with the non-answer given above, this can be achieved by forcing a re-render of the table. Obviously you'll want to make sure this won't have any unintended side effects for your own implementation. 

Example:

javascript```
const [tableKey, setTableKey] = useState(0);
...
const handleReset = () => {
    setTableKey(tableKey => tableKey + 1);
};
...
<Button onClick={ () => resetFilters() }>Reset Filters</Button>

<Table key={tableKey}>
  ...
</Table>
```

**Comment by ColeBW** [comment]
> For anyone coming here looking for a way to do this and not satisfied with the non-answer given above, this can be achieved by forcing a re-render of the table. Obviously you'll want to make sure this won't have any unintended side effects for your own implementation.
> 
> Example:
> 
> ```js
> const [tableKey, setTableKey] = useState(0);
> ...
> const resetFilters = () => {
>     setTableKey(tableKey => tableKey + 1);
> };
> ...
> <Button onClick={ () => resetFilters() }>Reset Filters</Button>
> 
> <Table key={tableKey}>
>   ...
> </Table>
> ```

Beautiful, thanks
