### ISSUE TITLE
Support pika dev

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#18002]
- https://www.pika.dev/blog/pika-web-a-future-without-webpack/
- https://www.pika.dev/
- https://www.pika.dev/packages/antd#releases
- https://www.pika.dev/cdn
- https://github.com/yiminghe/css-animation/commit/d77899fd77075b355893be6630deadaa20c7d08c

---

TODO:

- [ ] pack to pika cdn via `@pika/pack`
- [ ] documentation about how to use antd in `@pika/web`

**Comment by Jiang-Xuan** [comment]
looks good. can be used directly in the browser😅. may be not need codesandbox anymore😂?
