### ISSUE TITLE
Treeselect treedata in the dropdown menu cannot send request after filtering input values 

### ISSUE THREAD

**Issue by se7en00** [ant-design/ant-design#18004]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-haibt-pupzk)

### Steps to reproduce
input value in the treeselect

### What is expected?
the filtered treedata can be clicked, and sent async request

### What is actually happening?
can not be clicked

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | react |
| System | windows, mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
It's by design. ref #15085
