### ISSUE TITLE
Table组件 列数较少时，固定一两列， 表格中间会出现大片空白将固定列和非固定列分开两处

### ISSUE THREAD

**Issue by DivinerSQQ** [ant-design/ant-design#18008]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-lovelace-j7d7h)

### Steps to reproduce
```
javascript

import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Table } from "antd";

const columns = [
  {
    title: "Full Name",
    width: 100,
    dataIndex: "name",
    key: "name",
    fixed: "left"
  },
  {
    title: "Age",
    width: 100,
    dataIndex: "age",
    key: "age",
    fixed: "left"
  },
  { title: "Column 1", dataIndex: "address", key: "1", width: 50 }
];

const data = [
  {
    key: "1",
    name: "John Brown",
    age: 32,
    address: "New York Park"
  },
  {
    key: "2",
    name: "Jim Green",
    age: 40,
    address: "London Park"
  }
];

ReactDOM.render(
  <Table columns={columns} dataSource={data} />,
  document.getElementById("container")
);

```

### What is expected?
去掉中间空白，  向固定列靠拢

### What is actually happening?
有空白

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.2.0 |
| System | Ubuntu 18 |
| Browser | Chrome  |

![image](https://user-images.githubusercontent.com/48466881/62218836-cb377900-b3df-11e9-8463-fda654c68550.png)

**Comment by afc163** [comment]
<img width="944" alt="图片" src="https://user-images.githubusercontent.com/507615/62219199-72b4ab80-b3e0-11e9-9656-ffc39cd7921c.png">

**Comment by zuoshoudaoying** [comment]
1: 限制列宽
    出现的问题： 如果数据量少的时候中间会出现空白列。
2: 不限制列宽宽度设置为column
    出现的问题： 如果数据量过大的时候表格的头和表格的数据会有不对齐的情况。
解决：
    采用第二种情况不限制列宽， 可以为table设置table-layout: fixed!important属性。（在mac上测试是有效的, win上面有可能会出现意外的情况）。
