### ISSUE TITLE
Tree，TreeSelect 异步加载数据后，一些设置项失效

### ISSUE THREAD

**Issue by kxcy001123** [ant-design/ant-design#18000]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-murdock-y10k4)

### Steps to reproduce
1. 初始时  `Expand to load` 不可选择
2. 点击   `Expand to load`  异步加载子节点后
3. `Expand to load` 变成了可点击

### What is expected?
1. 初始时  `Expand to load` 不可选择
2. 点击   `Expand to load`  异步加载子节点后
3. `Expand to load` 仍不可可点击

### What is actually happening?
Tree，TreeSelect 异步加载数据后，一些设置项失效

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.4 |
| System | mac |
| Browser | chrome 75.0.3770.100 |

**Comment by zombieJ** [comment]
你的代码逻辑里没有子节点的时候用的是 `{...item}` 有子节点没有解构导致 `selectable` 被你漏了。

**Comment by kxcy001123** [comment]
> 你的代码逻辑里没有子节点的时候用的是 `{...item}` 有子节点没有解构导致 `selectable` 被你漏了。
我太蠢了
