### ISSUE TITLE
Need tooltipProps prop for Slider tooltip

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#18016]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
设置 tooltip 的样式

### What does the proposed API look like?
tooltipProps

### Related Issues
#13416
#15495

**Comment by shaodahong** [comment]
这三个属性都可以合并到 `tooltipProps ` 里面
![image](https://user-images.githubusercontent.com/14831261/62265076-51da6d80-b455-11e9-98b7-9377c48c26ad.png)

**Comment by shaodahong** [comment]
看了下源码是支持设置 `tooltipPrefixCls` 来自定义 `tooltip` 样式的，但是我没看到文档有，这个是属于默认的一种规范么

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/37043
