### ISSUE TITLE
DatePicker问题咨询

### ISSUE THREAD

**Issue by longang520** [ant-design/ant-design#1801]
http://codepen.io/longang/pen/xVoNZK?editors=001
点击测试按钮赋值，然后点击添加按钮提交。报错。
Uncaught TypeError: value.getTime is not a function
请问我是哪里错误了么？

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/1515#issuecomment-217367933

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
