### ISSUE TITLE
Empty snapshots diff between Linux/MacOS and Windows

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#18017]
- https://github.com/ant-design/ant-design/pull/17903#issuecomment-516774413
- https://github.com/ant-design/ant-design/pull/18006/files#diff-efa591f057303d0aee87cd2a1e6a6f88L1234
- https://github.com/ant-design/ant-design/pull/17858/files#diff-efa591f057303d0aee87cd2a1e6a6f88L1221

**Comment by shaodahong** [comment]
这个我也遇到过，我本地 `test-all` 是报错的，但是提交到线上是 ok 的

**Comment by zombieJ** [comment]
需改造一下这两个，把换行符过滤掉：
* https://www.npmjs.com/package/babel-plugin-inline-import
* https://github.com/ant-design/antd-tools/blob/master/lib/jest/imagePreprocessor.js
