### ISSUE TITLE
引入树形控件的DirectoryTree，运行报错

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design#18013]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
在index.js文件里面使用了DirectoryTree控件，发现报错，版本也升到最新版本，还是报错，按照提示的命令去安装也一样报错

These dependencies were not found:

* antd/es/directory-tree in ./src/pages/index.js
* antd/es/directory-tree/style in ./src/pages/index.js
* antd/es/tree-node in ./src/pages/index.js
* antd/es/tree-node/style in ./src/pages/index.js

To install them, you can run: npm install --save antd/es/directory-tree antd/es/directory-tree/style antd/es/tree-node antd/es/tree-node/style

### What is expected?
不报错，正常使用

### What is actually happening?
报错，不能正常使用

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by afc163** [comment]
```diff
- import { TreeNode, DirectoryTree  } from 'antd';
+ import { Tree } from 'antd';
+ const { TreeNode, DirectoryTree } = Tree;
```

**Comment by dongkeng001** [comment]
没事了，是我的错

**Comment by dongkeng001** [comment]
> ```diff
> - import { TreeNode, DirectoryTree  } from 'antd';
> + import { Tree } from 'antd';
> + const { TreeNode, DirectoryTree } = Tree;
> ```

是的，我刚发现了，是我的错，哎...粗心大意
