### ISSUE TITLE
Tooltip arrow is the wrong color (it should match the tooltip body background)

### ISSUE THREAD

**Issue by leeschmidt4** [ant-design/ant-design#18010]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-jcg22)

### Steps to reproduce
1. Use a tooltip like normal
2. Set the page background color to anything other than white in order to see the error
3. Notice that the tooltip arrow color is #404040, and the tooltip body background is rgba(0, 0, 0, 0.75)

### What is expected?
The tooltip arrow color should match the color of the tooltip body background color of rgba(0, 0, 0, 0.75)

### What is actually happening?
The tooltip arrow color is #404040 and the tooltip body background color is rgba(0, 0, 0, 0.75)

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.3 |
| System | macOS Mojave (10.14.5) |
| Browser | Chrome 75 |

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/pull/17740
