### ISSUE TITLE
Menu Item throw errors inside React.Fragment

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#18022]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ancient-night-g9rcx)

### Steps to reproduce
悬浮即可

### What is expected?
可以插入fragment

### What is actually happening?
不可插入fragment

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8  |
| System | win |
| Browser | chrome |

---
用数组方式可以，但是大部分情况还是会写<></>

**Comment by KuthorX** [comment]
我在14行append了 `<Fragment><div>a</div></Fragment>` 好像没问题？

**Comment by zombieJ** [comment]
Fragment 在 React 中是一个 ReactNode，与数组是不等价的。

**Comment by ztplz** [comment]
以前有提过 被关了  有时间重构吧  还有个item固定的问题

**Comment by yoyo837** [comment]
类似的还有`Tabs`、`TabPane`, `TabPane`如果使用`React.Children.map`就能复现

**Comment by shaodahong** [comment]
建议加个 warning 提示，不需要去处理 Fragment，内部摊平处理 Fragment 涉及到的太多了，Fragment 和正常的 Element 是没区别的，还有 key

**Comment by shackra** [comment]
any workaround to this while is being fix?

**Comment by yoyo837** [comment]
> any workaround to this while is being fix?

Not yet.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17860

**Comment by afc163** [comment]
It is one problem of #4853

**Comment by fungjj92** [comment]
Just came upon this same issue. Here's a screenshot of the `Item` classNames getting prefixed with `undefined`

![Screen Shot 2020-04-23 at 5 05 30 PM](https://user-images.githubusercontent.com/10568752/80149463-b6f66600-8584-11ea-912d-a4702538da8a.png)

**Comment by JuraJuki** [comment]
How to fix this?

**Comment by bengurion** [comment]
HI All, is there a plan to fix this issue, expand Menu.Item / Pane.... as individual Component. @AntDesigners 
Thank you for the answer !

**Comment by weihomechen** [comment]
> HI All, is there a plan to fix this issue, expand Menu.Item / Pane.... as individual Component. @AntDesigners
> Thank you for the answer !

+1

**Comment by manikandasankar** [comment]
@fungjj92 is the issue resolved for you? I am still facing the same issue reported by you.

**Comment by fungjj92** [comment]
@manikandasankar We have a workaround and will likely not be revisiting that code, so I'm not sure!

**Comment by mehtanilay10** [comment]
I'm also facing the same issue, I found the below alternative way to solve this. 
Posting here, so it can be helpful to others.
I used the below hack for that. Instead of using React Fragment, I have created an array of each `Menu.Item` and pass that in the menu. Here `menuItems1` uses Fragment way, where `menuItems2` uses array syntax.

```js
const menuItems1 = (
  <>
    <Menu.Item key="add1">Add - 1</Menu.Item>
    <Menu.Item key="edit1">Edit - 1</Menu.Item>
    <Menu.Divider />
    <Menu.Item key="edit1">Delete - 1</Menu.Item>
  </>
);

const menuItems2 = [
  <Menu.Item key="add2">Add - 2</Menu.Item>,
  <Menu.Item key="edit2">Edit - 2</Menu.Item>,
  <Menu.Divider />,
  <Menu.Item key="edit2">Delete - 2</Menu.Item>
];

const menu1 = <Menu>{menuItems1}</Menu>;   // This will have wrong css class
const menu2 = <Menu>{menuItems2}</Menu>;   // This will work fine.
```

**Comment by savvopulo** [comment]
The same issue appears with Form.List during iterating on fields. 

```
<Steps>
    <Form.List >
        {(fields) => (
            <>
                {fields.map(field => (
                    <Step ... />
                ))}
            </>
        )}
    </Form.List>
</Steps>
```
All rendered steps will have "undefined-item undefined-item-wait undefined-item-custom".
I can't use workaround with array here as (fields) => () expects a jsx node returned.

@AntDesigners Please suggest what workaround we have for this situation?

**Comment by kotAPI** [comment]
> The same issue appears with Form.List during iterating on fields.
> 
> ```
> <Steps>
>     <Form.List >
>         {(fields) => (
>             <>
>                 {fields.map(field => (
>                     <Step ... />
>                 ))}
>             </>
>         )}
>     </Form.List>
> </Steps>
> ```
> 
> All rendered steps will have "undefined-item undefined-item-wait undefined-item-custom". I can't use workaround with array here as (fields) => () expects a jsx node returned.
> 
> @AntDesigners Please suggest what workaround we have for this situation?

Same with `Link` 

```jsx
 <Link to={to}>
      <Menu.Item
      ....
```

**Comment by nikhil-mathews-siterecon** [comment]
Has there been any update on this? facing the same issue.
