### ISSUE TITLE
使用按需加载的时候好报以下错误，整体加载到没有问题

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#1802]
使用fis3按需加载的时候报以下错误

import Button from 'antd/lib/button'
mod.js:141Uncaught [ModJS] Cannot find module `classnames`

import DatePicker from 'antd/lib/date-picker'
mod.js:141 Uncaught [ModJS] Cannot find module `rc-calendar`

使用以下方式整体加载没有问题
import { Button } from 'antd'
import { DatePicker } from 'antd';

使用fis-parser-babel-5.x编译

看你们说到babel-plugin-antd，不知道这个如何配合fis3使用，或者在使用fis3工具的前提下，有其他好的解决方案。

尝试过用fis3的以下方法，
fis.unhook('components'); 
fis.hook('node_modules'); 

但是需要以下设置这个，只能一个html，并不能解决现在问题
fis.set('project.files', '/index.html'); // 按需编译

现在使用的fis3的components就出现刚开始描述的症状。
求解决方案。

**Comment by afc163** [comment]
fis3 的问题去 fis 那里进行咨询吧，我们不了解的。
