### ISSUE TITLE
design a  magnifying glass component

### ISSUE THREAD

**Issue by TeAmo-Zss** [ant-design/ant-design#18028]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The screen is blocked by dialog  and users need to close that to fill in the form.

### What does the proposed API look like?
It is hoped that magnifying glass components can be used not only independently but also nested before

**Comment by afc163** [comment]
No plan.
