### ISSUE TITLE
Table 的 expandedRowRender如果没有可以展开的数据

### ISSUE THREAD

**Issue by 1334310385** [ant-design/ant-design#18023]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表格的该行前边仍有一个加号，点击的时候会展示空白的一行，感觉不太友好，能不能把这个加号去掉

### What does the proposed API look like?
用法和原来的一样，只是要在有expandedRowRender属性的表格中没有可展开数据的行前边不要显示加号

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941

**Comment by 1334310385** [comment]
> [#1365 (comment)](https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941)

我说的不是树形展示表格数据，是嵌套表格的时候

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13253#issuecomment-454326778
