### ISSUE TITLE
Statistic统计数值的默认字体有问题

### ISSUE THREAD

**Issue by BugHiding** [ant-design/ant-design#18038]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-xi06h)

### Steps to reproduce
```js
<Statistic value="¥ 1000" title="总值(¥)" />
```

### What is expected?
两个人名币符号应该显示一致，我查了一下也没有弄清楚一横是对的，还是两横是对的。但是我看了支付宝的显示应该是两横的。
![image](https://user-images.githubusercontent.com/6602889/62337307-b0135900-b506-11e9-838e-cd30d3aed175.png)

### What is actually happening?
两次人名币符号显示不一致

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | macOS 10.14.5 |
| Browser | Chrome  75.0.3770.142 |

**Comment by afc163** [comment]
不应该用 Tahoma。@zombieJ
