### ISSUE TITLE
table filter 弹出框里的内容支持完全自定义

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design#1803]
![image](https://cloud.githubusercontent.com/assets/2011119/15447344/f24bb250-1f71-11e6-83de-8c3b7bdfd948.png)
现在的filter里是 menu + button 写死、不够灵活。如 #1736 想要在 filter 弹框里放一个 select 或者 input 等，不需要`确定 / 重置`按钮和menu。

**Comment by afc163** [comment]
暂时不支持这么复杂的需求，需求从设计那头就控制住。能节约很多成本，不然没完没了。

**Comment by MarloweW** [comment]
需要这个功能。比如：

有一列数据是数字，想过滤值大于 100 的。我可以提供菜单给用户选择 > = < ，但是这个数字要给用户自己填写，现在好像做不到。

**Comment by patientayo** [comment]
Could you please reopen this issue? It's a common scenario. @afc163

**Comment by afc163** [comment]
@patientayo There is a `filterDropdown` now.

https://ant.design/components/table/#components-table-demo-custom-filter-panel
