### ISSUE TITLE
Table with a Input.TextArea and fixed columns inside does not autosize when TextArea resize

### ISSUE THREAD

**Issue by banyudu** [ant-design/ant-design#18039]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-enbhr)

### Steps to reproduce
Type texts in "textarea" column, with new lines.

### What is expected?
All cells' height should change corresponding to 'textarea' content.

### What is actually happening?
Only 'textarea' column changes.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | macOS 10.14.5 |
| Browser | Chrome 75.0.3770.142 64bit |

---
After window resizes, the table auto-adjust itself to a good state. 
But change contents in Input.TextArea won't resize the window.

**Comment by banyudu** [comment]
![image](https://user-images.githubusercontent.com/2416493/62342090-32584900-b518-11e9-9633-29e124976435.png)

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/14859

trace https://github.com/react-component/table/pull/283

**Comment by banyudu** [comment]
Thanks
