### ISSUE TITLE
Cell Range Selection in antd table

### ISSUE THREAD

**Issue by piby180** [ant-design/ant-design#18031]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like to have the functionality of copy a range of cells and paste it into another location. 

Antd table perfectly fits my use case except the copy paste functionality. 

### What does the proposed API look like?
A similar example is shown [here](https://www.ag-grid.com/javascript-grid-clipboard/#example-simple)

The proposed solution is for the API to provide a function onCellRangeSelected which will be called when a range of cells are selected.

**Comment by afc163** [comment]
Sorry, we have no plan to provide excel-like Grid component for now~
