### ISSUE TITLE
Input组件无法通过ref清空input元素的value

### ISSUE THREAD

**Issue by y805939188** [ant-design/ant-design#18030]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-mountain-u35of)

### Steps to reproduce
靠ref获取到input的元素实例后，通过input实例的 .value = '' 清空input的value，然后马上触发setState，发现input框中的value没有被重置。

### What is expected?
期望input的值能被清空

### What is actually happening?
input的value被清空了，但是执行完setState后又回来了

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.6 |
| System | mac |
| Browser | chrmoe |

---
想对input框使用防抖，所以没有使用受控组件。当点击了提交按钮后希望通过ref重置input的value。但是发现重置完后如果马上执行setState的话，input的value会回复到清空之前

**Comment by afc163** [comment]
这是合理的，请先学习 React。

**Comment by y805939188** [comment]
@afc163 您好，我个人认为不合理，这不是react的setState造成的。因为使用html原生input，并不存在这种问题。
另外我看了Input组件源码，发现了些问题。
![屏幕快照 2019-08-02 下午1 20 38](https://user-images.githubusercontent.com/28889103/62346344-663b6a80-b528-11e9-8b0c-88e22d01c00d.png)
在源码里每次输入都触发setValue，如果用户没有在外部往里传value，就会自动触发setState({ value })；然后在每次render 原生的input的时候，value会从fixControlledValue(value)函数获取。
<img width="567" alt="屏幕快照 2019-08-02 下午1 26 53" src="https://user-images.githubusercontent.com/28889103/62346582-3d67a500-b529-11e9-95aa-a4ecaa05d642.png">
这里fixControlledValue参数的value就是之前每次setValue触发的setState改变的value，所以就算在外部使用ref.value = '';清空了元素实例的value，每次到这儿还是会把上一次的值给赋值回来。
综上我认为只要在不想使用受控组件的时候就会存在这个问题。
所以我个人希望您评估一下是否需要修改该问题

**Comment by afc163** [comment]
看了下，antd 的 Input 在非受控模式下会维护一个内部状态 `this.state.value`，直接修改 input value 不会清空这个状态。目前的实现上没有问题，这种情况很难避免。

建议不要使用 dom 操作维持状态，而是直接用 value。

**Comment by y805939188** [comment]
您好，我发现这个问题是因为我想对input组件的onChange使用防抖，使用防抖的话由于是异步触发，所以没办法给input组件外部添加value属性，如果给外部添加value作为受控组件的话，input中的值不会随着输入时时改变。所以我认为当外部通过ref修改value的时候，是否可以通过给Input组件源码中的this.input.value做proxy或是通过definproperty做拦截，然后setState改变内部维护的value。
当然只是我个人的提议。防抖的问题我已经通过别的方案解决了。

**Comment by afc163** [comment]
> 是否可以通过给Input组件源码中的this.input.value做proxy或是通过definproperty做拦截

会把事情搞复杂，防抖不要给 onChange 加，可以给真正需要防抖的函数加（比如发请求的函数）。

**Comment by y805939188** [comment]
> > 是否可以通过给Input组件源码中的this.input.value做proxy或是通过definproperty做拦截
> 
> 会把事情搞复杂，防抖不要给 onChange 加，可以给真正需要防抖的函数加（比如发请求的函数）。

后来我确实是把防抖给放到里面了。既然不好避免的话，那这个问题就先这样吧。希望未来的版本里能有更好的解决方案~谢谢解惑

**Comment by wtl1019** [comment]
@y805939188  遇到同样的问题，是用的函数组件么？函数组件设置state value时，debounce函数会被重新创建，就不能做到防抖了

**Comment by y805939188** [comment]
> @y805939188 遇到同样的问题，是用的函数组件么？函数组件设置state value时，debounce函数会被重新创建，就不能做到防抖了

建议给 debounce 使用 useMemo 之类的缓存起来或者直接用一些星星多的第三方防抖库。另外建议如果不是一定必须的话，最好不用 ref 控制 input 的 value，建议使用受控去做状态

**Comment by wtl1019** [comment]
> > @y805939188 遇到同样的问题，是用的函数组件么？函数组件设置state value时，debounce函数会被重新创建，就不能做到防抖了
> 
> 建议给 debounce 使用 useMemo 之类的缓存起来或者直接用一些星星多的第三方防抖库。另外建议如果不是一定必须的话，最好不用 ref 控制 input 的 value，建议使用受控去做状态

嗯嗯，是用受控做的，但每次change设置setSatate(inputValue)时函数组件都会重新执行，那么防抖函数也就被重新创建，导致防抖不生效。。。。昨天已经使用useCallback解决了，感谢回复

**Comment by zongyanglaobiao** [comment]
> > 是否可以通过给Input组件源码中的this.input.value做proxy或是通过definproperty做拦截
> 
> 会把事情搞复杂，防抖不要给 onChange 加，可以给真正需要防抖的函数加（比如发请求的函数）。

您好打扰了，以上的问题我也遇到了，我看官方文档其中没有提到Inout更新输入框的值的方法，请问通过useRef获取的Input实例没有提供类似setValue方法嘛

**Comment by yoyo837** [comment]
react应该用受控模式，啥情况必须得ref设置值？

**Comment by y805939188** [comment]
> > > 是否可以通过给Input组件源码中的this.input.value做proxy或是通过definproperty做拦截
> > 
> > 
> > 会把事情搞复杂，防抖不要给 onChange 加，可以给真正需要防抖的函数加（比如发请求的函数）。
> 
> 您好打扰了，以上的问题我也遇到了，我看官方文档其中没有提到Inout更新输入框的值的方法，请问通过useRef获取的Input实例没有提供类似setValue方法嘛

陈年老 bug 了，人家不愿意改，咱也没办法。建议不用 ref 而改成受控。
