### ISSUE TITLE
checked checkbox caused buggy overflow

### ISSUE THREAD

**Issue by picodoth** [ant-design/ant-design#18040]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/xvLPxM?editors=0010](https://codepen.io/anon/pen/xvLPxM?editors=0010)

### Steps to reproduce
the container div with black border has a scroll behavior

### What is expected?
the container div should not scroll

### What is actually happening?
the container div scrolls 

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | latest |
| System | macOS 10.12.6 |
| Browser | Chrome: Version 74.0.3729.157 (Official Build) (64-bit) |

suspicious line:

https://github.com/ant-design/ant-design/blob/master/components/checkbox/style/mixin.less#L10

![image](https://user-images.githubusercontent.com/1731837/62342739-819f7900-b51a-11e9-828f-845e926d496d.png)
![scrollcheckbox](https://user-images.githubusercontent.com/1731837/62342805-be6b7000-b51a-11e9-96d9-775284780294.gif)

unchecked box has no such behavior

**Comment by picodoth** [comment]
![image](https://user-images.githubusercontent.com/1731837/62343173-4aca6280-b51c-11e9-8dae-864b76f0fdc8.png)

acc4061eebe9f83210c63379202b90fb5e791238

**Comment by afc163** [comment]
和对齐没关系，我提了 PR：https://github.com/ant-design/ant-design/pull/18059
