### ISSUE TITLE
设置scroll={{ x: false, y: 160 }} 顶部出现白边

### ISSUE THREAD

**Issue by skyunBoss** [ant-design/ant-design#18042]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://i1.fuimg.com/695898/9deec5e6eed32674.png](http://i1.fuimg.com/695898/9deec5e6eed32674.png)

### Steps to reproduce
本地使用antd会出现，部署服务器不会出现，不明白为啥

### What is expected?
希望不要出现白色块

### What is actually happening?
出现白色块

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.0 |
| React | 16.8 |
| System | window10 |
| Browser | chrome75.0.3770.100 |

**Comment by Jiang-Xuan** [comment]
给个 codesandbox 仓库?

**Comment by skyunBoss** [comment]
> 给个 codesandbox 仓库?

公司项目

**Comment by Jiang-Xuan** [comment]
可以写一个 demo

**Comment by skyunBoss** [comment]
> 可以写一个 demo

https://github.com/skyunBoss/test-antd-table

**Comment by skyunBoss** [comment]
> Hello @skyunBoss. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @skyunBoss, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://github.com/skyunBoss/test-antd-table

**Comment by skyunBoss** [comment]
为什么ant-table-header会设置scroll？

**Comment by Reborn-dada** [comment]
版本问题，使用老版本antd就不会了

**Comment by afc163** [comment]
https://github.com/skyunBoss/test-antd-table/pull/1

可以这样更新一下。
