### ISSUE TITLE
Table 's td > div use text-overflow:ellipasis，fixed columns  overflow-hiden invalid

### ISSUE THREAD

**Issue by ChipmunkJerry** [ant-design/ant-design#18048]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
render:(text)=>(<div className='text-wrap'>{text}</div>)

table{
   table-layout:fixed;
}
.text-wrap{
    word-break: keep-all;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
}

### What is expected?
所有td中div不换行，溢出省略

### What is actually happening?
fixed列 溢出隐藏无效  

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.0 |
| React | 16 |
| System | win10 |
| Browser | chrome49 |

---
这个页面的table表头也是动态生成，列宽由数据决定，fixed列 宽度不能设置固定值
不希望用 width:固定px 解决

**Comment by ChipmunkJerry** [comment]
![微信截图_20190802161004](https://user-images.githubusercontent.com/46549467/62354729-1cf71500-b540-11e9-8557-d0665511ec6f.png)

**Comment by ChipmunkJerry** [comment]
![微信截图_20190802161143](https://user-images.githubusercontent.com/46549467/62354808-3c8e3d80-b540-11e9-9579-facd47031b4f.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17097#issuecomment-502361194

trace #17284
