### ISSUE TITLE
Descriptions -   Setting bordered can make the width of (Descriptions.Item children )different

### ISSUE THREAD

**Issue by meihuanyu** [ant-design/ant-design#18047]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-lake-62ztm)

### Steps to reproduce
click button

### What is expected?
width is the same

### What is actually happening?
width different

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.0 |
| React | 16 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
It has to be it for now, we can't use flex layout cause we need to be compatible with IE9/10.
