### ISSUE TITLE
不通过编译直接在html引用antd.js 在IE9和IE8没办法使用？

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#1804]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。

If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by benjycui** [comment]
> 不通过编译直接在 xxx 中引用 yyy.cpp 在 Windows 中没办法使用？

`antd` 是用 ES2015 写的，老浏览器不支持，所以必须先编译为 ES5。

**Comment by afc163** [comment]
可能是兼容性的问题，需要排查一下。

**Comment by afc163** [comment]
给个报错的例子？

**Comment by afc163** [comment]
麻烦提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
除了上面的问题，目前构建文件在 IE8 下仍然跑不通，报下面的错误。

![](https://os.alipayobjects.com/rmsportal/RvkojmXHHTeiPko.png)

**Comment by afc163** [comment]
http://www.2ality.com/2015/12/babel6-loose-mode.html

不知道能否解决。@sorrycc

**Comment by sorrycc** [comment]
https://github.com/reactjs/react-router/issues/3466
看起来是这个的问题。

**Comment by sorrycc** [comment]
试试把 react-router 换成 2.3 是不是好了，我的 IE8 太差了，连上面的 `throw new TypeError` 问题都定位不出来。

**Comment by afc163** [comment]
没有 react-router，只有 antd 和它的依赖。

**Comment by afc163** [comment]
要到 ant-design 目录重新构建 `npm run dist`，之前没加 es3ify。

**Comment by afc163** [comment]
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!-- 引入样式 -->
    <link rel="stylesheet" href="http://npmcdn.com/antd/dist/antd.css">
    <!-- Polyfills -->
    <!--[if lt IE 10]>
    <script src="http://npmcdn.com/es5-shim@4.5.8/es5-shim.js"></script>
    <script src="http://npmcdn.com/es5-shim@4.5.8/es5-sham.js"></script>
    <script src="https://as.alipayobjects.com/g/component/??console-polyfill/0.2.2/index.js,html5shiv/3.7.2/html5shiv.min.js,media-match/2.0.2/media.match.min.js"></script>
    <script src="http://npmcdn.com/jquery@1.x"></script>
    <![endif]-->
    <script src="http://npmcdn.inc.alipay.net/react/dist/react"></script>
    <script src="http://npmcdn.inc.alipay.net/react-dom/dist/react-dom"></script>
    <script src="antd.js"></script>
  </head>
  <body>
    <div id="root"></div>
  </body>
  <script>
  console.log(antd);
  </script>
</html>

```

**Comment by sorrycc** [comment]
还有，react@15 也不支持 IE8，我换成 react@0.14 就好了。

**Comment by afc163** [comment]
确实，我居然忘了改。

**Comment by afc163** [comment]
下个版本会修复。

**Comment by nail2008** [comment]
昨天升级到antd1.1.0，react 15.0.2 确实不支持ie8了，还在继续试

**Comment by benjycui** [comment]
@nail2008 用 react@14 + antd@1.0

**Comment by aw6658913** [comment]
是不是太缺少一个browser.min.js来解析jsx语言？不然好像没办法运行吧，然后那段代码我运行了下 在9可以，在8下还是爆antd错误 @afc163

**Comment by fhqdgv** [comment]
@afc163 
https://github.com/ant-design/ant-design/wiki/Template-for-Bug-Report-in-IE8-9
这个文档是不是过期了，复制运行ie8还是报错
![qq 20170214163016](https://cloud.githubusercontent.com/assets/6103043/22921086/3c08b1f6-f2d3-11e6-8f0d-06a01a70e8ea.png)

**Comment by afc163** [comment]
对的，antd 2.x 已经不支持 IE8 了。

**Comment by fhqdgv** [comment]
但是我用IE8访问官网https://ant.design/components/button-cn/
组件是可以显示的，能透露下你们是怎么处理的吗？我按
https://github.com/xcatliu/react-ie8的处理也还是报错
@afc163
