### ISSUE TITLE
The text in Tooltip display abnormal in minimum window

### ISSUE THREAD

**Issue by Kol96** [ant-design/ant-design#18045]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-4qqfi)

### Steps to reproduce
1、open codesandbox demo in new window（do not left panel）
2、minimize the window to 200px using develop tool
3、hover the text

### What is expected?
The text in Tooltip should be displayed as usual

### What is actually happening?
The text in Tooltip displayed a word per line

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8 |
| System | mac os X |
| Browser | Chrome 75.0.3770.142 |

---
I set the ant-tooltip with position:relative and display:inline-block fix the problem, but i still wonder why. It seems the absolute element nest absolute element cause the problem.

**Comment by afc163** [comment]
不太理解，截个图看看？

**Comment by Kol96** [comment]
> 不太理解，截个图看看？

![image](https://user-images.githubusercontent.com/12791334/62349693-0f875e00-b533-11e9-860b-1272100270d8.png)

**Comment by afc163** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/507615/62364171-73218380-b553-11e9-9a9b-4dc5f72debd1.png">

你给的例子是不是重现不出来。

**Comment by Kol96** [comment]
> <img alt="image" width="470" src="https://user-images.githubusercontent.com/507615/62364171-73218380-b553-11e9-9a9b-4dc5f72debd1.png">
> 
> 你给的例子是不是重现不出来。

那个codesandbox里的demo打开新页面去看 直接看是看不到的 在新页面里缩小窗口调试

**Comment by afc163** [comment]
看了下，这是浏览器对文本渲染的逻辑，组件库这边不好处理，如果不希望被换行，可以给内容设置一个最小宽度。

```jsx
<Tooltip title={<div style={{ minWidth: 200 }}></div>}>
```

**Comment by Kol96** [comment]
> 看了下，这是浏览器对文本渲染的逻辑，组件库这边不好处理，如果不希望被换行，可以给内容设置一个最小宽度。
> 
> ```js-jsx
> <Tooltip title={<div style={{ minWidth: 200 }}></div>}>
> ```

我给ant-tooltip设置了position:relative和display:inline-block解决了 但不清楚会不会有什么副作用
