### ISSUE TITLE
DatePicker日期选择框组件 选择 今天 按钮之后 会对当前日历组件所有时间有影响

### ISSUE THREAD

**Issue by lvbaiying** [ant-design/ant-design#18056]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
选择日期选择组件，正常点击 想要选择的日期 ，打印的时间正常
点击 今天 按钮 选择后 打印的时间会加一天，并且一旦操作今天按钮后 日期组件内所有时间都会被加一天
官方组件上就也有这个问题！

### What is expected?
点击今天后与原来一致

### What is actually happening?
时间不一致

| Environment | Info |
|---|---|
| antd | 3.19.7 |
| React | 16.8.6 |
| System | mac OS |
| Browser | Google Chrome 75 |

**Comment by afc163** [comment]
Duplicate of #13795
