### ISSUE TITLE
No matching version found for rc-editor-mention@1.1.13

### ISSUE THREAD

**Issue by hyoseon-kim** [ant-design/ant-design#18054]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://no link](http://no link)

### Steps to reproduce
1. type 'npm install antd'
2. error occured

### What is expected?
no error exist and install normally

### What is actually happening?
npm ERR! code ETARGET
npm ERR! notarget No matching version found for rc-editor-mention@1.1.13
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | window10 |
| Browser | no browser |

---
The stable version is written on the github as 1.1.13, but the actual version of 1.1.12 is installed.

**Comment by afc163** [comment]
There is it: https://unpkg.com/rc-editor-mention@1.1.13
