### ISSUE TITLE
Tree view search have unicode issue

### ISSUE THREAD

**Issue by shifanahamedlebbe** [ant-design/ant-design#18052]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/shifanalas/pen/YmxRvW?editors=0011](https://codepen.io/shifanalas/pen/YmxRvW?editors=0011)

### Steps to reproduce
Try to search with following text "හෙලෝ වර්ල්ඩ" and delete the search letter one by one and you can see the difference in tree view that appends unknown characters

### What is expected?
Tree node content no to be manipulate while searching

### What is actually happening?
Tree node content is manipulating while searching

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | react |
| System | Mac |
| Browser | chrome latest |

**Comment by shifanahamedlebbe** [comment]
![Screen Shot 2019-08-02 at 3 55 18 PM](https://user-images.githubusercontent.com/16117166/62364099-53cc2b80-b53e-11e9-9acf-567d2dda507e.png)

**Comment by afc163** [comment]
I don't think it is antd-related issue.
