### ISSUE TITLE
components/descriptions/demo/border.md  console报错

### ISSUE THREAD

**Issue by zancheng** [ant-design/ant-design#18057]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/edit/master/components/descriptions/demo/border.md](https://github.com/ant-design/ant-design/edit/master/components/descriptions/demo/border.md)

### Steps to reproduce
25    <Descriptions.Item label="Usage Time" span={3}>

25行  span应该是2

### What is expected?
25行  span={2}

### What is actually happening?
span={3}

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
Actually, it should be `3`.

**Comment by zancheng** [comment]
> Actually, it should be `3`.

index.js:1375 Warning: [antd: Descriptions] Sum of column `span` in a line exceeds `column` of Descriptions.

I have no problem from the list to the details page.
But this warning will appear if you refresh the details page directly.
Screen size greater than 1600 will be replayed.

**Comment by 951759534** [comment]
2 or 3 ?  3 has warn

**Comment by 951759534** [comment]
compute it should 2
