### ISSUE TITLE
locale config of Table.emptyText in LocaleProvider does't work

### ISSUE THREAD

**Issue by jeezlee** [ant-design/ant-design#18053]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hudn0)

### Steps to reproduce
```javascript
<LocaleProvider locale={{ Table: { emptyText: "Nothing Here" } }}>
    <Table />
</LocaleProvider>
```

### What is expected?
Display "Nothing Here" as the empty text of Table

### What is actually happening?
defalt emptyText of Table component

| Environment | Info |
|---|---|
| antd | 3.20.2 |
| React | 16.8.6 |
| System | macOS |
| Browser | Chrome 75.0.3770.100 |

---
the same situation in Select component

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-dmows

**Comment by jeezlee** [comment]
> https://codesandbox.io/s/antd-reproduction-template-dmows

Means `Table.emptyText` in  LocaleProvider is useless? and I must set `emptyText` in every Table?
How can config it as GLOBAL.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-mvc43
