### ISSUE TITLE
Input addonBefore and addonAfter values do not join value of Input

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#18060]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-hamilton-n7e1f)

### Steps to reproduce
1. Create an Input with an addonAfter and/or addonBefore prop using the Select component. Add an onChange prop on the Input element that console.log's e.target.value
1. Change the value of the Select component in either the addonBefore or addonAfter.
1. Change the value of the Input. 

### What is expected?
The value of the Select component(s) from addonBefore and/or addonAfter is prepended and/or appended to the value of the input text field respectively. In the reproduction example, if the user selects 'Https://" from the addonBefore, enters 'www.google' in the text input, and selects '.com' from the addonAfter, the logged value should be 'Https://www.google.com'.

### What is actually happening?
Only changes made to the text input field are logged.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.7 |
| System | any |
| Browser | any |

---
I know I can merge the data on my own by using form.getFieldDecorator on addonBefore and/or addonAfter but that solution should be built into the Input component.

**Comment by afc163** [comment]
Input with addon don't affect it's value.

**Comment by keithort** [comment]
@afc163 that is what I am saying is the bug. those values should merge together.

**Comment by doantientai** [comment]
I agree with @keithort , otherwise addonBefore serves nothing.

**Comment by ardaorkin** [comment]
Why is this issue closed? Are addons and input values merged now?

**Comment by mcanas** [comment]
A solution I found was to wrap the addon element in a `<Form.Item />` tag with an appropriate name. You can see an example here with in the ContactEditor.js component:

[![Edit hardcore-moon-h2xof](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-moon-h2xof?fontsize=14&hidenavigation=1&theme=dark)

**Comment by Jiyr0119** [comment]
> A solution I found was to wrap the addon element in a `<Form.Item />` tag with an appropriate name. You can see an example here with in the ContactEditors.js component:
> 
> [![Edit hardcore-moon-h2xof](https://camo.githubusercontent.com/90808661433696bc57dce8d4ad732307b5cec6270e6b846f114dcd7ee7f9458a/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/hardcore-moon-h2xof?fontsize=14&hidenavigation=1&theme=dark)

good job
---------
解决 input 中 addonBefore 和 addonAfter的值 没有合并到input的值

**Comment by chess99** [comment]
another solution, manual combine Components, example:
```
const DEFAULT_UNIT = 'dp'
const allUnits = ['dp', 'pt', 'px', 'rpx']
const unitOptions = allUnits.map(unit => ({ label: unit, value: unit }))

export const InputLength: React.FC<{
  value?: string
  onChange?: (value: string) => void
  disabled?: boolean
  style?: React.CSSProperties
  onBlur?: any
}> = props => {
  const [unit, setUnit] = useState(DEFAULT_UNIT)
  const [number, setNumber] = useState(0)

  useEffect(() => {
    if (typeof props.value === 'string' && props.value !== '') {
      const [parsedNumber, parsedUnit] = props.value?.split(/(?<=\d)(?=[a-z%])/)
      setNumber(Number(parsedNumber))
      setUnit(parsedUnit)
    } else if (typeof props.value === 'number') {
      setNumber(props.value)
      setUnit(DEFAULT_UNIT)
    } else {
      setNumber(0)
      setUnit(DEFAULT_UNIT)
    }
  }, [props.value])

  const handleNumberChange = (value: number | null) => {
    if (value === null) {
      setNumber(0)
      props.onChange?.(`0${unit}`)
    } else {
      setNumber(value)
      props.onChange?.(`${value}${unit}`)
    }
  }

  const handleUnitChange = (value: string) => {
    setUnit(value)
    props.onChange?.(`${number}${value}`)
  }

  return (
    <InputNumber
      value={number}
      onChange={handleNumberChange}
      disabled={props.disabled}
      style={props.style}
      onBlur={props.onBlur}
      addonAfter={
        <Select
          value={unit}
          onChange={handleUnitChange}
          onBlur={props.onBlur}
          disabled={props.disabled}
          options={unitOptions}
          showSearch
        ></Select>
      }
    />
  )
}
```

**Comment by BlackBearFTW** [comment]
This still isn't resolved in v5 of ant design, will this change?

**Comment by qomhmd** [comment]
+1
