### ISSUE TITLE
希望FormItem的label在layout="Vertical"时支持拓展

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#18064]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在需要引导输入时提供快捷方法，如充值时填入恰当的数字，为日期填入七天后、三天后等

### What does the proposed API look like?
现在的label允许为string|ReactNode，希望添加一个Object，内容为
```
{
  title: String|ReactNode,
  extra: ReactNode
}
```
如：
```
{
  title: "充值金额",
  extra: <a onClick={value=defaultValue*-1}>抹平</a>
}
```

### 实现效果
![image](https://user-images.githubusercontent.com/23520283/62407563-c1369580-b5ec-11e9-9d25-7e1d073955d8.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/wizardly-violet-pmnrn

可以这么做，这个 extra 在其他布局下没有地方放，还是不加了。
