### ISSUE TITLE
Table border error in chrome of Win10

### ISSUE THREAD

**Issue by Junyan** [ant-design/ant-design#18068]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-voice-tuhq5)

### Steps to reproduce
- Win10 System > Settings > Display > Scale and layout settings page 150%. It's a default setting of  notebook.
- Width of column has percentage.

### What is expected?
Correct border.

### What is actually happening?
- Border is wrong now, beacause scrollbar of header table is wrong.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 76.0.3809.87 |

![image](https://user-images.githubusercontent.com/17005098/62413064-ab04f580-b63d-11e9-8678-580ad46f56e7.png)

![image](https://user-images.githubusercontent.com/17005098/62413048-506b9980-b63d-11e9-9a17-b2c80c205fb3.png)

![image](https://user-images.githubusercontent.com/17005098/62413055-801aa180-b63d-11e9-97e4-e6b89dac6f8f.png)

**Comment by Junyan** [comment]
Related issue: https://github.com/react-component/table/issues/362

**Comment by Junyan** [comment]
Maybe we can place a decoration over scrollbar instead of hiding scrollbar by css.

**Comment by afc163** [comment]
should be fixed in https://github.com/ant-design/ant-design/pull/19986
