### ISSUE TITLE
关于antd组件默认值设置文档补充

### ISSUE THREAD

**Issue by ShawDanon** [ant-design/ant-design#18065]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
让开发者更方便的使用antd，比如我看过文档后不知道设置默认值，我大概会对组件二次封装，然后设置默认值方便使用，比如模态框的居中效果。在咨询了antd开发者后知道了可以使用defaultProps来设置antd组件默认值，很方便，希望加入文档。

### What does the proposed API look like?
将这个问题加入FAQ。具体如下：
如何给组件设置默认props？
在开发过程中会遇到想给某个antd组件设置统一props的情况，例如模态框居中显示的centered。你可以在antd组件渲染之前设置（例如umi中layouts组件中）
```js
import { Modal } from 'antd';
Modal.defaultProps.centered = true;
```
这样之后引入的所有Modal都会有居中效果。

**Comment by afc163** [comment]
不推荐这么用，建议直接封装上层组件。

**Comment by ShawDanon** [comment]
这么用是有什么风险吗？感觉只是一个centered封一个组件有点多余，还就就是已经写过的项目，突然要把所有的模态框居中，我是经历过搜索模态框，然后挨个加centered的痛苦滴 :stuck_out_tongue:，或者消息提示的顶部高度啥的。

**Comment by Eric-Leng** [comment]
@afc163 用高阶组件包裹的话 ts提示没了...

**Comment by KAROTT7** [comment]
@Eric-Leng 
这样写就会有 ts 提示
```
import React from 'react'
import { Modal } from 'antd'
import type { ModalProps } from 'antd/es/modal'

const MyModal: React.FC<ModalProps> = props => {
  const {
    centered = true,
    ...rest
  } = props

  return (
    <Modal {...props} centered={centered} />
  )
}
```

**Comment by KAROTT7** [comment]
@Eric-Leng 
上面 return 里写错了，不是props，是rest
```
<Modal {...rest} centered={centered} />
```

**Comment by Eric-Leng** [comment]
@KAROTT7 没找到太好的办法
