### ISSUE TITLE
Table scroll x not disappearing when table has only one row

### ISSUE THREAD

**Issue by Nilanth** [ant-design/ant-design#18066]
@

- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/2oo5py14j0)

### Steps to reproduce
scroll horizontally a table with single row from bottom

### What is expected?
The scroll x should be disappear on focus out of table

### What is actually happening?
When the table has single row it scrolls horizontal but the scroll bar does not disappear on focus out

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | react 16.8 |
| System | mac |
| Browser | chrome latesh |

**Comment by afc163** [comment]
I don't reproduce your problem in your codesandbox, could you provide more infomation and gif maybe?

**Comment by Nilanth** [comment]
![ezgif-1-6cb902c00304](https://user-images.githubusercontent.com/28811774/62409666-686cfa00-b5f8-11e9-850e-53df44b21073.gif)

**Comment by zombieJ** [comment]
Is Mac bug, all the scrollable element with mouse move in can cause same issue. We can do nothing on antd side.
