### ISSUE TITLE
Infinite Scroll for Tables / Data Grids

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#18062]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
Although I have seen this being raised multiple times before, but the issues seem to be closed without concrete conclusion.

### What problem does this feature solve?
All modern applications are moving to the idea of using an infinite scroll when using tables or data grids.
Currently Ant Design supports only pagination.
With infinite scroll, a user simply keep scrolling with new records being dynamically loaded providing a much better user experience as opposed to viewing and clicking page numbers.

### What does the proposed API look like?
Add a table property "InfiniteScroll". Recommend setting to true by default but not necessary. 
If this is set "pagination" should be off.
The API will behave exactly like pagination does, by submitting the request to the server just like when the next button on the pagination component is clicked.
It should be triggered when user scroll all the way down to the bottom of the table and displayed records are less than total records indicating more records need to be fetched.
Also recommend using it in combination with Footer which will displayed number of records 1-500 of 2500.
Indicating very clearly to the user that there are more records, since here we do not have page numbers to give this kind of information to the user.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/12670

**Comment by StallionV** [comment]
> #12670

Thanks, so you are effectively stating that we use https://github.com/Leonard-Li777/antd-table-infinity 
I did not know about it thanks for pointing out.
Would be good at some point if the feature though comes built in with Ant Design :)

**Comment by StallionV** [comment]
> > #12670
> 
> Thanks, so you are effectively stating that we use https://github.com/Leonard-Li777/antd-table-infinity
> I did not know about it thanks for pointing out.
> Would be good at some point if the feature though comes built in with Ant Design :)

I have tried using this library and it does not work well unfortunately
