### ISSUE TITLE
Table组件里的拖拽排序表格该怎么导出？  直接export default不行

### ISSUE THREAD

**Issue by 904492381** [ant-design/ant-design#18078]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting](https://ant.design/components/table-cn/#components-table-demo-drag-sorting)

### Steps to reproduce
import { Table } from 'antd';
import { DndProvider, DragSource, DropTarget } from 'react-dnd';
import HTML5Backend from 'react-dnd-html5-backend';
import update from 'immutability-helper';
就是这个组件

### What is expected?
导入成功

### What is actually happening?
index.js:1 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

| Environment | Info |
|---|---|
| antd | 3.21.0 |
| React | react |
| System | win10 |
| Browser | 无关 |

**Comment by afc163** [comment]
不是 antd 的问题。
