### ISSUE TITLE
Duplicate ids generated with Enzyme test

### ISSUE THREAD

**Issue by JESii** [ant-design/ant-design#18074]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate. 

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-brook-u7sds)

### Steps to reproduce
Generate the app, then run the tests. The number of ids found is four, when it should be one

### What is expected?
Used the id once, it should be found only once.

### What is actually happening?
There are actually four ids in the code generated by Enzyme.

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.8.4 |
| System | MacOS 10.14.5 |
| Browser | Chrome Version 76.0.3809.87 (Official Build) (64-bit) |

---
I wanted to test that this id was acting properly when the dropdown was clicked, but when four such ids were found, the test failed as 'click' can occur only a a single node. Here's a portion of the dump from wrapper.debug()
```
 <MediaRoleSelect id="media-role-select" defaultValue="Select Asset Type" onChange={[Function: bound dispatchAction]}>
...

<Select id="media-role-select" defaultValue="Select Asset Type" ...">
<Select inputIcon={{...}} removeIcon={{...}} clearIcon={{...}} menuItemSelectedIcon={{...}} showArrow={[undefined]} id="media-role-select" ...}>
...
<div id="media-role-select" style={[undefined]} onBlur={[Function]}...}>
 ```
you'll notice that there are four `id="media-role-select"` in the generated code from Enzyme

**Comment by zombieJ** [comment]
You should use `ComponentName#id` to find the node instead of `id` or use `hostNodes` to find the dom node: https://airbnb.io/enzyme/docs/api/ShallowWrapper/hostNodes.html
