### ISSUE TITLE
Transfer table 分页时 左上角数量期望显示总数而不是当前页码数量

### ISSUE THREAD

**Issue by LiYanGang** [ant-design/ant-design#18079]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
必现

### What is expected?
总页数

### What is actually happening?
当前页码数量

| Environment | Info |
|---|---|
| antd | 3.21.0 |
| React | 16.7 |
| System | mac |
| Browser | chrome |

**Comment by LiYanGang** [comment]
![image](https://user-images.githubusercontent.com/20022163/62437701-e3f4b580-b776-11e9-9917-cf5ae3ce0f56.png)

**Comment by zombieJ** [comment]
重现是空的……
