### ISSUE TITLE
ant-design 编译方面的咨询

### ISSUE THREAD

**Issue by freestyle21** [ant-design/ant-design#1807]
你好，我想咨询从[github repo](https://github.com/ant-design/ant-design)，怎么编译成 `npm`上的[安装包](https://www.npmjs.com/package/antd)。

我的理解是，github上项目是官网的源码和 `Ant Design` 的 `JSX` 的源码，npm 上的项目是编译后的，试着执行了  `npm run dist` ，但是生成的dist文件夹里面，是 `common.js` 和 `common.js.map`。

由于内网限制，需要把定制后的`antd`的源码编译后，发布到内部npm源上。

期待回复。

**Comment by afc163** [comment]
是 `npm run dist`，这是我编译的结果：

```
🎯   ant-design@1.1.0 git:❨master❩ tree dist
dist
├── antd.css
├── antd.css.map
├── antd.js
├── antd.js.map
├── antd.min.css
├── antd.min.css.map
├── antd.min.js
└── antd.min.js.map

0 directories, 8 files
```

**Comment by freestyle21** [comment]
在`npm install antd`生成的文件夹里面执行 `npm run dist` 有`common.js`，然后clone的文件夹里面也是一样，奇怪了。。现在好了

抱歉，issue先关了。

**Comment by benjycui** [comment]
`git clone` 本项目到本地，然后在 `ant-desgin` 的目录下 `npm install && npm run dist` 才对。

**Comment by freestyle21** [comment]
发现问题了。

通过`cnpm install`安装的依赖包，执行 `npm install dist`会生成 
`
antd.css
antd.min.css
antd.js
antd.min.js
common.js
`
通过`npm install`安装的依赖包会生成正常的文件。

估计是 `cnpm`源很久没有更新了，以后有朋友遇到可以做个参考。

**Comment by afc163** [comment]
`cnpm sync **`

**Comment by benjycui** [comment]
cc @fengmk2

**Comment by fengmk2** [comment]
我执行了 `cnpm install antd`，看了 dist 目录，文件是正常的啊

```bash
$ cnpm install antd

  tree node_modules/antd/dist/
node_modules/antd/dist/
├── antd.css
├── antd.css.map
├── antd.js
├── antd.js.map
├── antd.less
├── antd.min.css
├── antd.min.css.map
├── antd.min.js
└── antd.min.js.map

0 directories, 9 files
```

**Comment by fengmk2** [comment]
antd-tools run dist 抛了一个异常，估计找 atool-build 没找对地方。

```
> antd@1.1.0 dist /Users/mk2/git/ant-design
> antd-tools run dist

antd-tools run dist
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn atool-build ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by fengmk2** [comment]
https://github.com/ant-design/antd-tools/blob/master/lib/gulpfile.js#L27 看了这段代码，是没有从 node_modules/antd-tools/node_modules/.bin 从这个 PATH 找 atool-build cmd 的

**Comment by fengmk2** [comment]
@guangao @afc163 antd-tools 里面的 runCmd 又是强依赖了 npm3 的模块提升机制来寻找到 atool-build

**Comment by fengmk2** [comment]
@afc163 https://github.com/ant-design/antd-tools/pull/8 只解决 PATH 问题，但是 es3ify-loader 没找到的问题是类似的，目前 antd-tools 的路径查找都是强依赖 npm3 的模块提升的，一定有2个子目录同时依赖了 es3ify-loader 或者 atool-build，那么这2个被提升的模块版本就不确定了。

**Comment by maxid** [comment]
这个问题最终要怎么解决啊?

**Comment by zhaoyueer** [comment]
请问您是如何发布到npm源上的，为何我npm run pub 会抛异常

**Comment by zhaoyueer** [comment]
请问您是如何发布到npm源上的，为何我npm run pub 会抛异常
