### ISSUE TITLE
Velocity: IE8 and below require jQuery to be loaded before Velocity. 这是什么情况，我引入了ANTDESIGN的menu控件，在IE8不支持

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#1808]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。

If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did
import {
  Button,Row, Col,Icon,Cascader,Checkbox,Rate,Select,DatePicker,Menu
  } from 'antd';
const SubMenu = Menu.SubMenu;

import React from 'react';
import {
  Button,Row, Col,Icon,Cascader,Checkbox,Rate,Select,DatePicker,Menu
  } from 'antd';

const CheckboxGroup = Checkbox.Group;
const SubMenu = Menu.SubMenu;
const optionsCascader = [{
  value: 'zhejiang',
  label: '浙江',
  children: [{
    value: 'hangzhou',
    label: '杭州',
    children: [{
      value: 'xihu',
      label: '西湖',
    }],
  }],
}, {
  value: 'jiangsu',
  label: '江苏',
  children: [{
    value: 'nanjing',
    label: '南京',
    children: [{
      value: 'zhonghuamen',
      label: '中华门',
    }],
  }],
}];
const plainOptions = ['Apple', 'Pear', 'Orange'];
const optionsCheckboxGroup = [
  { label: '苹果', value: 'Apple' },
  { label: '梨', value: 'Pear' },
  { label: '橘', value: 'Orange' },
];
//<Menu mode="horizontal">
//  <Menu.Item key="mail">
//    <Icon type="environment-o" />导航
//  </Menu.Item>
//  <Menu.Item key="app" disabled><Icon type="team" />找同事</Menu.Item>
//  <SubMenu title={<span><Icon type="edit" />建议</span>}>
//    <Menu.Item key="setting:1">新的建议</Menu.Item>
//    <Menu.Item key="setting:2">历史建议</Menu.Item>
//  </SubMenu>
//  <Menu.Item key="alipay">
//    <a href="http://www.baidu.com/" target="_blank"> <Icon type="question-circle-o" />帮助</a>
//  </Menu.Item>
//</Menu>
let TestAntd1 = React.createClass({
  getInitialState() {
    return {
    };
  },
  onChangeEvent(value) {
      console.log(value);
  },
  onChangeData(value, dateString) {
    console.log(value, dateString);
  },
  render() {
      return <div>
          <Row>
            <Button type="primary" icon="search">搜索</Button>
            <Icon type="caret-right" />
            <CheckboxGroup options={optionsCheckboxGroup} defaultValue={['Pear']} onChange={this.onChangeEvent} />
          </Row>
          <Row>
            <Cascader options={optionsCascader} onChange={this.onChangeEvent} placeholder="请选择地区" />
            <DatePicker onChange={this.onChangeData} />

          </Row>
        <Row>

        </Row>
      </div>
  }
});

export default TestAntd1;

在IE8上不支持啊，不兼容，我使用的ANTDESIGN的0.12.17版本，100%能重现
(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.17):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by afc163** [comment]
IE8 下加个 jQuery 试试先？

**Comment by wuhaih** [comment]
加拉，还是报一样的错误

**Comment by wuhaih** [comment]
BUILD之后在IE8下提示以下错误
/*****************
	       Dependencies
	    *****************/

	    var $,
	        isJQuery = false;

	    if (global.fn && global.fn.jquery) {
	        $ = global;
	        isJQuery = true;
	    } else {
	        $ = window.Velocity.Utilities;
	    }

	    if (IE <= 8 && !isJQuery) {
	        throw new Error("Velocity: IE8 and below require jQuery to be loaded before Velocity.");
	    } else if (IE <= 7) {
	        /* Revert to jQuery's $.animate(), and lose Velocity's extra features. */
	        jQuery.fn.velocity = jQuery.fn.animate;

	        /* Now that $.fn.velocity is aliased, abort this Velocity declaration. */
	        return;
	    }

**Comment by afc163** [comment]
全局 script 引入试试？

**Comment by afc163** [comment]
https://github.com/julianshapiro/velocity/blob/9c9c052a5fb6d5854c9aad931d9410c6790816ee/velocity.js#L554

**Comment by wuhaih** [comment]
你给的方案，不行啊，你们没试过antd0.12.17 menu组件嚒，BUILD之后在IE是不行的

**Comment by wuhaih** [comment]
velocity-animate 被antd引用，是antd组件***.jsx要写import $ from 'jQuery'，还是在静态页面使用script 引入

**Comment by benjycui** [comment]
看之前的回复 https://github.com/ant-design/ant-design/issues/1808#issuecomment-220841953

全局引入就 OK 了。

**Comment by afc163** [comment]
dist 文件在 IE8 下有问题，下个版本会修复。详见 #1804
