### ISSUE TITLE
怎么避免 antd 组件重复打包

### ISSUE THREAD

**Issue by Go7hic** [ant-design/ant-design#18080]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当我用 antd 写了一个小项目或者组件，然后在其他新项目里面通过 npm 方式引入这个组件，然后那个项目也用了 antd，这时候要是新项目和那个 npm包里面用了相同组件，貌似会打包两份 antd 的组件，目前我只能通过 submodule 方式引入这个小项目或组件，不能通过 npm 方式引入，但是要是多几个这种小项目组件感觉就不好维护了，不知道官方有没有啥好的建议，或者是已经有方案了只是我不知道的。

### What does the proposed API look like?
API 暂时没想到，但是希望能有一个工具打包的时候 检查是否已经有该组件了  有就不再打包了。或者官方有更好的解决方案

**Comment by jszjgqq** [comment]
https://ant-design.gitee.io/docs/react/use-with-create-react-app-cn#%E4%BD%BF%E7%94%A8-babel-plugin-import

**Comment by Go7hic** [comment]
@jszjgqq  不是这个按需加载，你仔细看我的描述

**Comment by yoyo837** [comment]
@Go7hic 你使用的项目和你的一起编译吗？[babel-plugin-import](https://github.com/ant-design/babel-plugin-import), 如果你使用那个项目编译后的，应该不行

**Comment by Go7hic** [comment]
@yoyo837 是的，如果通过npm方式引入的项目组件是打包编译后的，已经把用到的 antd 组件打包进去了，babel-plugin-import 不能解决这个问题的。

**Comment by yoyo837** [comment]
@Go7hic 你这个应该发到你使用的这个项目的issue里去，让他们支持源码编译

**Comment by Go7hic** [comment]
@yoyo837 嗯

**Comment by qlniu** [comment]
请问是如何解决的

**Comment by onezhaoyn** [comment]
同问是怎么解决的呢？ @Go7hic

**Comment by onezhaoyn** [comment]
有问题的可以参考这个：https://zhuanlan.zhihu.com/p/54255260
