### ISSUE TITLE
Form中给Checkbox.Group监听change事件validateFields的值错误！

### ISSUE THREAD

**Issue by lynshir** [ant-design/ant-design#18086]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-star-45ni5)

### Steps to reproduce
进入以上重现链接，可直接勾选checbox数组，看console,理论上values数组的leng和勾选的chebox的length应该一致，现在情况是取消勾选时才能输出正确，勾选反而是错的。

### What is expected?
勾选和校验结果一致

### What is actually happening?
勾选和校验结果不一致

| Environment | Info |
|---|---|
| antd | 3.21.1 |
| React | 16.8.6 |
| System | macos |
| Browser | 75.0.3770.100 |

**Comment by lynshir** [comment]
刚才试了一下 在change函数中添加setTimeout可以输出正确的结果(因为点击submit是可以正确校验值的)，猜想：状态合并更新的bug

**Comment by zombieJ** [comment]
不要在 `onChange` 中对表单进行校验，表单的状态管理不是同步的。
