### ISSUE TITLE
When <Layout.Sider/> collapsed and set collapsedWidth，the <Menu /> width not same as collapsedWidth, still 80px。

### ISSUE THREAD

**Issue by codelegant** [ant-design/ant-design#18084]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/codelegant/pen/GVOyZr](https://codepen.io/codelegant/pen/GVOyZr)

### Steps to reproduce
Click collapsd icon.

### What is expected?
When Side collapsed, <Menu/> width same as collapsedWidth (60px)。

### What is actually happening?
<Menu /> width still 80px。

| Environment | Info |
|---|---|
| antd | 3.20.6 |
| React | 18.6.0 |
| System | macOS 10.14.6 |
| Browser | Chrome 76.0.3809.87 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11422#issuecomment-408652273
https://github.com/ant-design/ant-design/issues/8601
