### ISSUE TITLE
Prefix/suffix Input string vertical align

### ISSUE THREAD

**Issue by izorg** [ant-design/ant-design#18087]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/pensive-paper-di2wk)

### Steps to reproduce
Open link https://codesandbox.io/embed/pensive-paper-di2wk

### What is expected?
Correct vertical align

### What is actually happening?
"$" too hight

| Environment | Info |
|---|---|
| antd | 3.21.1 |
| React | 16.8.6 |
| System | macOS 10.14 |
| Browser | Chrome 76 |

**Comment by afc163** [comment]
又有问题了。。。。。。。。。。

https://github.com/ant-design/ant-design/pull/17684

@LilyWakana

**Comment by zombieJ** [comment]
= =，'$' 不是个图标。那段图标居中的逻辑得 revert 掉。

**Comment by songhuizhang** [comment]
size为large时也有问题

[https://codesandbox.io/embed/pensive-breeze-3rw1f](https://codesandbox.io/embed/pensive-breeze-3rw1f)

**Comment by zombieJ** [comment]
看起来没什么好办法，Icon 大小不同不居中的问题相对次要一些。还是先 Revert 掉。

fix preview: https://5d481c70cdb1f00008aa9758--ant-design.netlify.com/components/input-cn/#header

**Comment by LilyWakana** [comment]
抱歉考虑不周
