### ISSUE TITLE
Table. Pagination object. onChange method triggered on change sorting by clicking on table column header

### ISSUE THREAD

**Issue by exileX** [ant-design/ant-design#18099]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gallant-dewdney-1uom1)

### Steps to reproduce
1. Click on Table column header
2. Take a look to console

### What is expected?
Table=>pagination=>onChange shouldn't fire

### What is actually happening?
Table=>pagination=>onChange fired. But pagination not changed.

| Environment | Info |
|---|---|
| antd | 3.21.1 |
| React | 16.8.5 |
| System | Linux |
| Browser | Google Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16978
https://github.com/ant-design/ant-design/issues/17648
https://github.com/ant-design/ant-design/issues/17770

**Comment by Samuel-Montoya** [comment]
Hello there,

I am still getting this same issue. Every time I filter/sort the table, the page resets back to one.

Using the onChange function, the pagination parameter has the value of 1, instead of what was currently on state. Has this been fixed or am I doing something wrong here?

Thanks!
