### ISSUE TITLE
babel plugin import 改了吗

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#18095]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://暂无](https://暂无)

### Steps to reproduce
看截图

### What is expected?
不应该自动加前缀

### What is actually happening?
加了前缀

| Environment | Info |
|---|---|
| antd | 3.21.1 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by zombieJ** [comment]
* 没改：https://www.npmjs.com/package/babel-plugin-import
* 没看到截图

有了再开……

**Comment by Fled8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/62462587-59ce4080-b7ba-11e9-8a1c-b48c37a68e34.png)
![image](https://user-images.githubusercontent.com/35049517/62462601-618de500-b7ba-11e9-9b8f-8142ef902d01.png)
不好意思网络延迟

**Comment by Fled8617** [comment]
@zombieJ

**Comment by zombieJ** [comment]
给个最小项目重现看看

**Comment by Fled8617** [comment]
太难复现了。。我也不知道什么情况，但怎么看都感觉像分包的时候出现的问题
![image](https://user-images.githubusercontent.com/35049517/62470386-eb46ae00-b7cc-11e9-875d-afff0010e878.png)
![image](https://user-images.githubusercontent.com/35049517/62470418-fac5f700-b7cc-11e9-847a-f717b426a417.png)
![image](https://user-images.githubusercontent.com/35049517/62470543-3f519280-b7cd-11e9-9492-5b309676e50f.png)
![image](https://user-images.githubusercontent.com/35049517/62470549-44aedd00-b7cd-11e9-8f9b-9d080a12f995.png)
不行就先关了吧

**Comment by zombieJ** [comment]
唔…… 你可以 git check 到一个正常版本再一步步看过来。
