### ISSUE TITLE
PageHeader should let developer decide the visibility of onBack icon button no matter whether the breadcrumb is shown

### ISSUE THREAD

**Issue by tangye1234** [ant-design/ant-design#18094]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We can use onBack icon button from ant-design-pro's pageHeaderWrapper component

### What does the proposed API look like?
```jsx
<PageHeader onBack=? backIcon=? breadcrumb=? />
```
If either onBack or backIcon is defined, then the page header will render back icon regardless of the value of breadcrumb

**Comment by zombieJ** [comment]
Back icon is no related with breadcrumb. Check the demo: https://ant.design/components/page-header-cn/#components-page-header-demo-basic

**Comment by tangye1234** [comment]
@zombieJ, you should be responsible for reviewing the issue. If pageheader get breadcrumb routes, then it will no longer render back icon

**Comment by zombieJ** [comment]
Got it.

@chenshuai2144, what's the design not to show the back when `breadcrumb` provides?

**Comment by chenshuai2144** [comment]
Both return and breadcrumbs are a kind of navigation, and we think that these two should not be used at the same time.

**Comment by tangye1234** [comment]
@chenshuai2144, I have thought about that, but breadcrumb actually acts like a static navigation, so antd pro uses it as a standard navigation bar. Back button does not act like that, it will take you to the last place u visitied, where the page is mostly located at a dynamic route. So page header should let the user decide the case.

**Comment by tangye1234** [comment]
@chenshuai2144, in antd pro, we always set a back icon manually on the title, so that we can get back from the detail page to the page list, and mostly the pagination is not at the first page number.

If we use breadcrumb to navigate it,  it can only navigate to the very first page of the list, and that should not be a good user experience.

**Comment by tangye1234** [comment]
Could you please re-considerate that?

**Comment by tangye1234** [comment]
new feature of pageheader update will fix this issue, great.

**Comment by dengfuping** [comment]
@chenshuai2144 
- The problem exists still, although #18128 has been merged. According to the design of PageHeader, `onBack` icon could coexist with `breadcrumb` navigation.
![image](https://user-images.githubusercontent.com/14918822/64149562-c0e22200-ce58-11e9-9143-7fd9e71ab413.png)

- The design demo from `Tech UI`:

![image](https://user-images.githubusercontent.com/14918822/64149682-2504e600-ce59-11e9-87a3-60538a8a7634.png)

**Comment by tangye1234** [comment]
@dengfuping according to the UI spec, onBack icon now will take over the breadcrumb when the both are given.

I partially agree with that design idea, because there is barely need to show breadcrumb navigations when the back icon is shown, at which time the page is possibly routed toward a detailed page of the list.

But I also agree that developers should decide for its own user case.
