### ISSUE TITLE
IE9 Upload组件出现文件File未定义

### ISSUE THREAD

**Issue by wangru1993** [ant-design/ant-design#18109]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/date-picker-cn/#components-upload-demo-defaultFileList](https://ant-design.gitee.io/components/date-picker-cn/#components-upload-demo-defaultFileList)

### Steps to reproduce
已有上传文件，用IE9浏览器打开，报File未定义

### What is expected?
正确显示

### What is actually happening?
File未定义

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | windows10 |
| Browser | IE9 |

**Comment by zombieJ** [comment]
错误信息贴一下

**Comment by wangru1993** [comment]
> 错误信息贴一下
![error](https://user-images.githubusercontent.com/15643700/62510577-14edec80-b842-11e9-9abc-d39deb59d381.png)

**Comment by afc163** [comment]
File API 在 IE9 下没有，可能需要加个判断。

**Comment by wangru1993** [comment]
> File API 在 IE9 下没有，可能需要加个判断。

对的，查了一下文档说是File只支持到IE10,不过antd3.20.0版本是好的，3.20.1就坏了，代码差异也就是一个判断的提取，不清楚具体哪里出了问题，请官方查一下吧
 var isValidateFile = file.originFileObj instanceof File || file.originFileObj instanceof Blob;

**Comment by afc163** [comment]
broken by https://github.com/ant-design/ant-design/commit/b5143df1a4347bc7d41a14529cbf2685ac79ca19#diff-817c52a860d640732d841c46abc102efR45
