### ISSUE TITLE
Support for 5 Column in Grid

### ISSUE THREAD

**Issue by Piero87** [ant-design/ant-design#18104]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/grid/](https://ant.design/components/grid/)

### Steps to reproduce
The documentation doesn't talk about the options to make 5 columns in Grid

### What is expected?
To have 5 columns in Grid

### What is actually happening?
I don't know how insert in in the prop span of Col

| Environment | Info |
|---|---|
| antd | 3.21.1 |
| React | 16.8.6 |
| System | MacOs Mojave |
| Browser | Chrome 78.0.3874.0 |

**Comment by keithort** [comment]
By default, the grid uses 24 columns. You can change that in your `config-overrides.js` with the `@grid-columns` variable. If this is just 1 location, you can use standard CSS on the `Col` and set the width to 20%.

**Comment by afc163** [comment]
trace #14407

**Comment by Piero87** [comment]
@keithort How I can do it? there is a documentation?

**Comment by keithort** [comment]
@Piero87 There is partially. Assuming you have configured your React app to use `react-app-rewired`, run 'yarn add react-app-rewire-less`. Then in your `config-overrides.js` file, import it (`const rewireLess = require("react-app-rewire-less");`). 
YMMV but if I was doing it on the apps I have that utilize Ant Design, I would do it like this: 
```
module.exports = {
  webpack: function override(config, env) {
    ...
    config = rewireLess.withLoaderOptions({
      modifyVars: {
        "@grid-columns": "5"
      }
    })(config, env);
    ...
  }
}
```
Then you could do
```
<Row type="flex" gutter={16}>
    <Col span={1}>Col 1</Col>
    <Col span={1}>Col 2</Col>
    <Col span={1}>Col 3</Col>
    <Col span={1}>Col 4</Col>
    <Col span={1}>Col 5</Col>
  </Row>
```

If you only want a 5 column grid in 1 location, then you could probably use this code https://codesandbox.io/s/unruffled-darkness-54352.

**Comment by vitalijalbu** [comment]
Hi guys, any other alternatives??
