### ISSUE TITLE
最近做的页面很多组件都提示Velocity: IE8 and below require jQuery to be loaded before Velocity. 在IE8不支持，谁能给个解决方案，我加了jquery也不行

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#1810]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。

If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

**Comment by wuhaih** [comment]
BUILD之后在IE8下提示以下错误
/*****************
	       Dependencies
	    *****************/

	    var $,
	        isJQuery = false;

	    if (global.fn && global.fn.jquery) {
	        $ = global;
	        isJQuery = true;
	    } else {
	        $ = window.Velocity.Utilities;
	    }

	    if (IE <= 8 && !isJQuery) {
	        throw new Error("Velocity: IE8 and below require jQuery to be loaded before Velocity.");
	    } else if (IE <= 7) {
	        /* Revert to jQuery's $.animate(), and lose Velocity's extra features. */
	        jQuery.fn.velocity = jQuery.fn.animate;

	        /* Now that $.fn.velocity is aliased, abort this Velocity declaration. */
	        return;
	    }

**Comment by afc163** [comment]
不要重复提 issue 啊，当贴吧就不好玩了。#1808
