### ISSUE TITLE
button  + calendar-picker +  button 的布局时会出现对不齐的情况

### ISSUE THREAD

**Issue by zhrln** [ant-design/ant-design#18107]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ijqdh)

### Steps to reproduce
直接复现

### What is expected?
button   calendar-picker   button 能正常对齐

### What is actually happening?
不能对齐

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.3.2 |
| System | Mac 10.14.5 |
| Browser | Google Chrome Version 76.0.3809.87 (Official Build) beta (64-bit) |

---
有看到几个月前对这部分代码做了hack：
https://github.com/ant-design/ant-design/blame/master/components/button/style/index.less#L18
line-height 从 1.5 变为 1.499。

在 demo 里将其手动改为 1.5 则可以正常对齐

**Comment by yoyo837** [comment]
ref: #13214

**Comment by aniznik1** [comment]
I opened the reproduction link with the newest antd version (4.21.5) and looks like it's still broken.
<img width="247" alt="image" src="https://user-images.githubusercontent.com/73177825/177959353-a01df3a5-0875-46dd-8081-857865c7a564.png">
