### ISSUE TITLE
A space character should not be inserted into the middle of two Chinese character of Button Component when the type is link

### ISSUE THREAD

**Issue by feibinyang** [ant-design/ant-design#18118]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
- similar issues: [link](https://github.com/ant-design/ant-design/issues/12314)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-sara-6j4ml)

### Steps to reproduce
If button text is two Chinese character, one space character inserted. But this is weird when the type is "link".

### What is expected?
No space character inserted when the button type is link.Or at least support to modify the default behavior.

### What is actually happening?
A space character inserted.

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | macOS 10.13.2  |
| Browser | Google Chrome 75.0.3770.100 正式版 64位 |

---
I think the space character is weird when the type is link.

**Comment by xrkffgg** [comment]
### 判断是否2个汉字
https://github.com/ant-design/ant-design/blob/109bd4ecde8879b9a4cd4a3048041d350f265dcd/components/button/button.tsx#L14

### 加入空格
https://github.com/ant-design/ant-design/blob/109bd4ecde8879b9a4cd4a3048041d350f265dcd/components/button/button.tsx#L37

是可以加个属性， 在这里的判断条件加上，看看官方的意思吧

**Comment by xrkffgg** [comment]
https://ant.design/components/button/#FAQ

**Comment by Yangzhedi** [comment]
https://codesandbox.io/s/distracted-bhabha-xzo6c
