### ISSUE TITLE
Popconfirm内嵌button设置disabled，依然可以触发点击事件弹出确认框

### ISSUE THREAD

**Issue by Aluww77** [ant-design/ant-design#18117]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/PMExBw?&editable=true&editors=001](https://codepen.io/anon/pen/PMExBw?&editable=true&editors=001)

### Steps to reproduce
<Popconfirm placement="topLeft" title={text} onConfirm={confirm} okText="Yes" cancelText="No">
        <Button disabled>TL</Button>
      </Popconfirm>

### What is expected?
希望能够处理一下

### What is actually happening?

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.4.7 |
| System | mac |
| Browser | 谷歌 版本 75.0.3770.142 |

**Comment by Aluww77** [comment]
官网示例代码稍作修改：
<Popconfirm placement="topLeft" title={text} onConfirm={confirm} okText="Yes" cancelText="No">
        <Button disabled>TL</Button>
</Popconfirm>

**Comment by Aluww77** [comment]
官网示例代码，button添加disabled属性，仍可触发确认框弹出：
’<Popconfirm placement="topLeft" title={text} onConfirm={confirm} okText="Yes" cancelText="No">
        <Button disabled>TL</Button>
      </Popconfirm>‘

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13351
https://github.com/ant-design/ant-design/issues/16947
https://github.com/ant-design/ant-design/pull/16985
