### ISSUE TITLE
progress gradient color settings

### ISSUE THREAD

**Issue by wendzhue** [ant-design/ant-design#18113]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/progress-gradient-5llyc](https://codesandbox.io/s/progress-gradient-5llyc)

### Steps to reproduce

\-

### What is expected?
The second circle should not have gradient color.

### What is actually happening?
The second circle progress has gradient color, too (the same with the first).

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | latest |
| System | macOS |
| Browser | Chromee |

---
Should not use the universal id `url(#gradient)`. Better to assign a unique id for each progress component.

**Comment by wendzhue** [comment]
@afc163 OK. I will fix this.

**Comment by xrkffgg** [comment]
测试：
https://codesandbox.io/embed/progress-gradient-w30qe

发现  单个的 在使用的时候 是可以的

当在使用变色时，同时加上 successPercent 
- 后台报错
- 样式失效

在看怎么解决😂😂😂

**Comment by xrkffgg** [comment]
报的是  warning  ， 不是  error

**Comment by wendzhue** [comment]
Fixes in rc: https://github.com/react-component/progress/pull/76/.

**Comment by xrkffgg** [comment]
@wendzhue success-color 支持修改 会好点 😂😂

**Comment by wendzhue** [comment]
@xrkffgg 

```ts
const isGradient = Object.prototype.toString.call(strokeColor) === '[object Object]'
```

因为这一句判断没过。不过渐变的 progress 用 success percent 很奇怪，颜色都是一样的。

cc @afc163 这里设计上要明确下。

WIP：https://github.com/react-component/progress/pull/76/files

**Comment by wendzhue** [comment]
> @wendzhue success-color 支持修改 会好点 😂😂

现在 antd 代码是固定用那种绿色的，底包里逻辑修改下只对最后一个 path 用渐变色看起来效果会好些……_

**Comment by xrkffgg** [comment]
其实 感觉 渐变色 在实际的项目中 很少用到吧，太花了

**Comment by wendzhue** [comment]
This cannot be closed for now. We still need to change less files.

<img width="1081" alt="Screen Shot 2019-08-14 at 22 15 29" src="https://user-images.githubusercontent.com/12122021/63028262-0efea800-bee1-11e9-862e-b9b3bd8e03a2.png">

You can see that `stroke: url(#gradient)` is wrong.
