### ISSUE TITLE
table 设置表头固定，可滑动，划到最后一列，导致表格错位，解决方案

### ISSUE THREAD

**Issue by qinyuhua** [ant-design/ant-design#18119]
![image](https://user-images.githubusercontent.com/28893646/62538381-37552980-b885-11e9-9515-1fe7836ca1f0.png)

最后发现，最新版的把表头的滑动条没有显示，但是滑动条的宽度保留了，
保留就保留，但是宽度不够，到时滑动到最后面，列表错位，
重新给设置宽度：
.ant-table-header::-webkit-scrollbar {
    width: 20px;
  }

**Comment by yoyo837** [comment]
ref: #13825
