### ISSUE TITLE
Input.TextArea with autosize prop displays scrollbar when width is set to a small number

### ISSUE THREAD

**Issue by woshiguabi** [ant-design/ant-design#18111]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/b4p17)

### Steps to reproduce
请看codesandbox

### What is expected?
按照codesandbox中右边的textarea展示

### What is actually happening?
codesandbox中左边的textarea出现了不需要的滚动条

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | latest |
| System | win10 |
| Browser | chrome latest |

---
业务场景是比较复杂的表单，所以textarea没有太多空间放，在宽度较小的情况下，设置了autosize会在多几次换行后出现滚动条，这个换行需要用内容来撑开，直接换行符无效。
这是否是chrome本身的问题？我目前是通过设置overflow:hidden来解决，但这样resize也必须设置成none才行。

**Comment by zombieJ** [comment]
测了一下 safari 也有这个问题，我具体看看

**Comment by SoftwareEngineerPalace** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/ecd139ba9847d0c77607c86339eb8ee6939ca85143a92ae16ebf20f58325e1b6/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/b4p17)
> 
> ### Steps to reproduce
> 请看codesandbox
> 
> ### What is expected?
> 按照codesandbox中右边的textarea展示
> 
> ### What is actually happening?
> codesandbox中左边的textarea出现了不需要的滚动条
> 
> Environment	Info
> antd	3.21.2
> React	latest
> System	win10
> Browser	chrome latest
> 业务场景是比较复杂的表单，所以textarea没有太多空间放，在宽度较小的情况下，设置了autosize会在多几次换行后出现滚动条，这个换行需要用内容来撑开，直接换行符无效。 这是否是chrome本身的问题？我目前是通过设置overflow:hidden来解决，但这样resize也必须设置成none才行。

啥是 resize ?

**Comment by yoyo837** [comment]
> > * [x]   I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> > 
> > ### Reproduction link
> > [![Edit on CodeSandbox](https://camo.githubusercontent.com/ecd139ba9847d0c77607c86339eb8ee6939ca85143a92ae16ebf20f58325e1b6/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/b4p17)
> > ### Steps to reproduce
> > 请看codesandbox
> > ### What is expected?
> > 按照codesandbox中右边的textarea展示
> > ### What is actually happening?
> > codesandbox中左边的textarea出现了不需要的滚动条
> > Environment	Info
> > antd	3.21.2
> > React	latest
> > System	win10
> > Browser	chrome latest
> > 业务场景是比较复杂的表单，所以textarea没有太多空间放，在宽度较小的情况下，设置了autosize会在多几次换行后出现滚动条，这个换行需要用内容来撑开，直接换行符无效。 这是否是chrome本身的问题？我目前是通过设置overflow:hidden来解决，但这样resize也必须设置成none才行。
> 
> 啥是 resize ?

https://developer.mozilla.org/zh-CN/docs/Web/CSS/resize
