### ISSUE TITLE
Checkbox Group设置label为0时，checkbox后面为空

### ISSUE THREAD

**Issue by xiaxianlin** [ant-design/ant-design#1811]
Checkbox Group设置label为0时，checkbox后面为空

**Comment by RaoHai** [comment]
Thanks for your feedback.

It seems work perfect during my [Demonstration](http://codepen.io/RaoHai/pen/PNMWLv?editors=001)... So Please provide me another demonstration ?

**Comment by afc163** [comment]
Maybe this: http://codepen.io/anon/pen/eZqvXj?editors=001

**Comment by RaoHai** [comment]
这个如果让 CheckboxGroup 简单粗暴的把 label toString 也不好吧，万一 label 要传一个 React Component 进去怎么整……

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/20b248a70dc7a3ada593a44745c620ba2e4f7d14/components/checkbox/index.jsx#L20

`{children ? <span>{children}</span> : null}`

=>

`{children === undefined ? <span>{children}</span> : null}`
