### ISSUE TITLE
nextjs,config-provider做国际化后与locale-provider分包不同？

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#18121]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://暂无](https://暂无)

### Steps to reproduce
截图

### What is expected?
分包怎么算合理呢？

### What is actually happening?
分包怎么算合理呢？

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8  |
| System | win |
| Browser | chrome |

---
分包怎么算合理呢？

**Comment by Fled8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/62539558-06c2bf00-b888-11e9-8de6-9ec3a2ed0608.png)
![image](https://user-images.githubusercontent.com/35049517/62539574-16da9e80-b888-11e9-887b-a81ecb9863c4.png)

![image](https://user-images.githubusercontent.com/35049517/62539653-4ee1e180-b888-11e9-9c99-978cd04f87b2.png)
![image](https://user-images.githubusercontent.com/35049517/62539690-6751fc00-b888-11e9-96f2-4f3850ca086d.png)
用了configprovider后发现moment跟icon都没有被打进commonthunk

**Comment by afc163** [comment]
你能自行排查一下给我们具体建议或 PR 么？

**Comment by zombieJ** [comment]
Close since no more feedback.
