### ISSUE TITLE
tree组件中使用checkbox时第一次触发了onChange事件，第二次点击时不触发onChange

### ISSUE THREAD

**Issue by fridaydream** [ant-design/ant-design#18120]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-napier-4k9i7)

### Steps to reproduce
tree组件中使用checkbox时第一次点击触发了onChange事件，第二次点击时不触发onChange

### What is expected?
期望第二次点击checkbox时触发onChange事件

### What is actually happening?
第二次点击checkbox时触发onChange事件不走

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | react |
| System | macOS |
| Browser | Chromee |

---
业务需要tree中加入checkbox，需求页面截图：https://cdn.yonyoucloud.com/cp-cdn-video/wo_Jbv5Q2~4gMa~6lewAeWechatIMG30.png

**Comment by yoyo837** [comment]
没有rerender 造成的，title已经确定了

**Comment by fridaydream** [comment]
@yoyo837 那有解决方案不？

**Comment by zombieJ** [comment]
https://codesandbox.io/s/adoring-darkness-0k70g
