### ISSUE TITLE
测试SearchInput样例，inputGroup的样式style没有编译到生成的css文件中

### ISSUE THREAD

**Issue by foxgaga** [ant-design/ant-design#1812]
http://ant.design/#/components/form?scrollTo=components-form-demo-search-input

**Comment by RaoHai** [comment]
Thanks for your feedback.

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by foxgaga** [comment]
@RaoHai 
http://ant.design/#/components/form?scrollTo=components-form-demo-search-input

**Comment by afc163** [comment]
It works in you link.... What the problem?

**Comment by foxgaga** [comment]
@afc163 
I use the 'antd-init' for initialization
and copy the codes to  the 'entries/index.js'.
It does not work.

I have no idea,
but It works when the 'InputGroup' is wraped with the a empty '<div>'

**Comment by afc163** [comment]
You need `ant-search-input-wrapper` like http://ant.design/#/components/form?scrollTo=components-form-demo-search-input

**Comment by foxgaga** [comment]
@afc163 

I coped the code of the demo `form-demo-search-input` with no changes
while it does not work.

I do as follows:
```
import { Input, Button,Form } from 'antd';
const FormItem = Form.Item;
```

**Comment by afc163** [comment]
I will try later.

**Comment by foxgaga** [comment]
@afc163 
刚开始接触，不是很了解。可能上面描述的不清楚也比较乱，不好意思。

`antd-init`配置完成之后，把`form-demo-search-input`的代码拷贝到`entries\index.js`测试，运行结果样式有问题，对比官网样例发现`.input-group`的编译到css文件中
http://ant.design/#/components/form?scrollTo=components-form-demo-search-input

`form-demo-input-group`也用到了`InputGroup`
http://ant.design/#/components/form?scrollTo=components-form-demo-input-group

对比两个样例后，在`form-demo-search-input`加上
```
import { Input, Button,Form } from 'antd';
const FormItem = Form.Item;
```
运行样式正常，但`form-demo-search-input`中并没有使用`FormItem `

**Comment by afc163** [comment]
大概知道了，你试试把 antd 升级到 `1.1.0`。`1.0.0` 上误把 search-input 的样式放到 Form 里面了。

https://github.com/ant-design/ant-design/commit/ca849c8ee35ff2215ad3cd682a6a5938f9d698df

**Comment by foxgaga** [comment]
@afc163 
昨天更新的，版本应该是对的...
```
"dependencies": {
    "antd": "^1.1.0",
```

**Comment by afc163** [comment]
感谢反馈，确实有问题，等待后续更新吧。
