### ISSUE TITLE
Mentions组件在文档中还存在focus和blur两个方法，但是原型上不存在这两个方法，希望可以添加这两个方法

### ISSUE THREAD

**Issue by 513107329** [ant-design/ant-design#18131]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Mentions组件由开发者掌握是否自动获取焦点

### What does the proposed API look like?
Mentions组件可以使用focus和blur两个方法

**Comment by yoyo837** [comment]
你是说主动调用而非事件监听？

**Comment by 513107329** [comment]
是的，我看文档上是存在这两个方法的，但是原型链上并不存在这两个方法。
![image](https://user-images.githubusercontent.com/19640501/62589909-57c0ca80-b8fd-11e9-88af-e101f4e096a9.png)

**Comment by ztplz** [comment]
啥原型链。。。
