### ISSUE TITLE
Tooltip still visible after mouseLeave in disabled Checkbox

### ISSUE THREAD

**Issue by laysent** [ant-design/ant-design#18137]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-bash-2jpx1)

### Steps to reproduce
disable Checkbox, move mouse in then out.

![out](https://user-images.githubusercontent.com/1191606/62599857-eba38e00-b91f-11e9-8d02-bb2a411247b7.gif)

### What is expected?
Tooltip should disappear.

### What is actually happening?
Tooltip is still available

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | MacOS |
| Browser | Chrome 75 |

**Comment by kaiyoma** [comment]
@afc163 I'm still seeing a variation of this issue in the latest version of Ant. I have lots of checkboxes in a table and the disabled ones have a tooltip explaining why they're disabled. If I mouse over the checkbox and mouse out quickly, the tooltip appears and then never goes away. Is there an open issue tracking this?

**Comment by yoyo837** [comment]
free to Please open a new issue with new reproduce

**Comment by itsmichaeldiego** [comment]
@kaiyoma @laysent I am experiencing the same issue, came up with this workaround:

- Wrap the disabled button/input in another element.
- Add `{ pointer-events: none; }` style to the disabled button/input.
- Set `{ cursor: not-allowed; }` to the wrapper to fix cursor behavior that stops working with previous step (adding pointer-events: none;).

```javascript
<Tooltip title="Tooltip Title">
  <span style={{ cursor: disabled ? 'not-allowed' : 'pointer' }}>
    <YourDisabledComponent disabled={disabled} style={{ pointerEvents: 'none' }} />
  </span>
</Tooltip>
```

Sources:
- https://github.com/react-component/tooltip/issues/18#issuecomment-307994107
- https://github.com/react-component/tooltip/issues/18#issuecomment-411476678
- https://github.com/react-component/tooltip/issues/18#issuecomment-650864750

Let me know if it works!

**Comment by laysent** [comment]
@itsmichaeldiego This issue should have been fixed by #18138 with similar workaround as you have mentioned. Related unit test snapshot can be found [here](https://github.com/ant-design/ant-design/blob/75b090aff3a0e0bec1eb24360e8c207b3d8dfb6e/components/tooltip/__tests__/__snapshots__/tooltip.test.js.snap#L20).

**Comment by itsmichaeldiego** [comment]
@laysent Your fix seem to work for checkbox, but it does not work for `<button disabled>` for example, or other components

**Comment by laysent** [comment]
@itsmichaeldiego i see. Tooltip only adds some hack for Checkbox, Button, Switch component, it will not work for other components. I think your way of workaround should work for general cases.

**Comment by itsmichaeldiego** [comment]
@laysent The fix for Button does not work for me, I think its because I am using v3?

**Comment by laysent** [comment]
@itsmichaeldiego The fix is available in v3. When I tried the following code, it will work properly (i.e. hide tooltip when mouse leave):
```jsx
```

**Comment by itsmichaeldiego** [comment]
@laysent Yes but it is buggy most of the time, specially if you've more than one tooltip

**Comment by laysent** [comment]
@itsmichaeldiego I am not sure if you are using `Button` inside `Tooltip` or using `button`. For `Button`, it should work as there are some special treatment inside `Button` for this scenario, but not for `button`. If you are using `button` or any other own component, you might need to wrap it with `span` to make it work.
