### ISSUE TITLE
Is there any way to rewrite the `renderCopy` method in typography/Base.tsx

### ISSUE THREAD

**Issue by yanyu0517** [ant-design/ant-design#18134]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I've been work on replacing the copy icon of [Paragraph](https://github.com/ant-design/ant-design/blob/109bd4ecde8879b9a4cd4a3048041d350f265dcd/components/typography/Paragraph.tsx) for a while. But no props or configs could let me fulfill it.

### What does the proposed API look like?
Export [Base](https://github.com/ant-design/ant-design/blob/109bd4ecde8879b9a4cd4a3048041d350f265dcd/components/typography/Base.tsx) as Component and I can extend and rewrite whatever what I need
or
Maybe a props is a good idea.

**Comment by yanyu0517** [comment]
Is there any news about this issue？

**Comment by rexuli** [comment]
Currently using 3rd party react component and want to migrate to Ant Design, the product is big and hard to do it once. However, the icon could not be changed and it is hard using two styles in the product.

**Comment by afc163** [comment]
See https://ant.design/components/typography-cn#copyable
