### ISSUE TITLE
table可选项和展开项问题？

### ISSUE THREAD

**Issue by JoeBBChen** [ant-design/ant-design#1813]
![image](https://cloud.githubusercontent.com/assets/12586787/15459765/5a92fed0-20db-11e6-8692-f9ded93493ec.png)

(借问一个问题可以吗？)红色部分是表格的可展开内容，黄色部分是可选择框，借问各位大哥，怎么将红色和黄色部分位置互换一下？

**Comment by RaoHai** [comment]
展开按钮固定在第一列。暂时没办法互换。

**Comment by JoeBBChen** [comment]
@RaoHai 那再借问一下，之所以要那个黄色部分的选择框，是因为需要选中一条数据来进行相应的操作，那个rowSelection虽然可以响应一些函数，但是我需要做的是让用户看到已经选中了一条数据再进行删改操作，而现在table那些行只有当鼠标放上去的时候才高亮，而不是单击选中数据然后高亮，因此有了那个选择框，同时那个按钮框是显示备注的。我实现选中一条数据的想法是不是错了？不然左边那个框和加号的位置感觉有点突兀。谢谢大哥~
![image](https://cloud.githubusercontent.com/assets/12586787/15467444/2a30d920-2111-11e6-8fe3-02756d0a07d9.png)
