### ISSUE TITLE
How can I replace svg pic of Icon Component

### ISSUE THREAD

**Issue by yanyu0517** [ant-design/ant-design#18136]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I've got some icons to be replaced, some like <Icon type="copy">, what all I need is to replace the little svg pic. 
I've been looking for little resolutions after upgrade to 3.9.0

### What does the proposed API look like?
Is there a way to replace the svg pic?

**Comment by afc163** [comment]
https://ant.design/components/icon/#components-icon-demo-custom

**Comment by yanyu0517** [comment]
I guess I didn't make myself clear. What I exactly mean is replacing the icon of antd built component but not the <Icon> component. 

The red circles in the below pic are original icon,  how can I use other svg replace them?

![image](https://user-images.githubusercontent.com/5326851/62603675-fd3d6380-b928-11e9-8be7-36e40453fd9f.png)

**Comment by afc163** [comment]
Sorry, you can't. 😢

**Comment by yanyu0517** [comment]
Bad news
I have an idea that is put the dist file into the AST, parse the code, retrieve the svg HTML string,  replace it and re-generate
Do you think it works?

**Comment by afc163** [comment]
Seems complicated, I can't give you suggestion.

**Comment by yanyu0517** [comment]
Is there any plan to support the feature?

**Comment by sanusart** [comment]
Was just trying to play with it myself, seems like this setup works (described in a gist) https://gist.github.com/sanusart/52311c413b10aa4f2c6cc29de8254f73

**Comment by afc163** [comment]
trace #18134
