### ISSUE TITLE
请问antd团队有没有计划开发新手导航组件的计划啊？

### ISSUE THREAD

**Issue by azl397985856** [ant-design/ant-design#1814]
一些网站都会有新手导航，就是将背景置会，高亮显示一块区域。可以点击下一步切换高亮区域的那种。
不知道你们有没有开发这个的计划

**Comment by afc163** [comment]
暂时没有，个人认为这种交互蛮反人类的。感谢关注~

**Comment by azl397985856** [comment]
哈哈，好吧

**Comment by afc163** [comment]
你可以试试：https://github.com/jakemmarsh/react-tour-guide

**Comment by azl397985856** [comment]
哇！ 找了好久，thank u
