### ISSUE TITLE
antd select 组件，不通过onchange事件，如何动态控制select的选中值?

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design#18144]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需求是，点击按钮后需要动态改变select的选中值

### What does the proposed API look like?
有没有什么方法可以快速实现？

**Comment by afc163** [comment]
`value`

**Comment by liyue118** [comment]
没懂怎么控制啊
