### ISSUE TITLE
ConfigProvider renderEmpty 不生效

### ISSUE THREAD

**Issue by gitHber** [ant-design/ant-design#18146]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-beaver-k1j44)

### Steps to reproduce
确定ConfigProvider renderEmpty是有用的？官网示例都不生效！

### What is expected?
empty样式改变

### What is actually happening?
并没有变化

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
![](http://g.recordit.co/ZU3rl4WW5g.gif)

Your codesandbox works fine.
