### ISSUE TITLE
Distorted button with icon inside Card actions

### ISSUE THREAD

**Issue by filipjnc** [ant-design/ant-design#18154]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-antd-o1hfwp?file=index.js](https://stackblitz.com/edit/react-antd-o1hfwp?file=index.js)

### Steps to reproduce
Create a button with icon inside the Card actions section

### What is expected?
Renders as normal button with icon

### What is actually happening?
Icon takes most of the space within button and is rendered in gray, text overflows.

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 75 |

---
Happened after this commit: https://github.com/ant-design/ant-design/commit/28d70f57fc22c1c92ef4a4491b6bb01a82fee27d

**Comment by liyuanqiu** [comment]
Absolutely a bug. Please fix it. If needed, I can raise a PR.
![image](https://user-images.githubusercontent.com/24999464/62648415-51763100-b985-11e9-91b5-f8d17ccc8195.png)
