### ISSUE TITLE
动态创建Form表单，报Uncaught TypeError: Cannot read property 'validate' of undefined

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design#1815]
表单项实用了Row 布局，如果Row 设置key以后，表单项编辑的时候报Uncaught TypeError: Cannot read property 'validate' of undefined。不设置则正常。
栗子：
http://codepen.io/wangdao/pen/RadgRb?editors=0010

**Comment by benjycui** [comment]
`key` 要稳定且唯一，建议认真学习 [React](https://facebook.github.io/react/docs/multiple-components.html#dynamic-children).

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by maotan** [comment]
how do you solve this problem?
