### ISSUE TITLE
Bug in documentation - Use in create-react-app - LESS customize theme

### ISSUE THREAD

**Issue by Aka4Code** [ant-design/ant-design#18156]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-with-create-react-app#Advanced-Guides](https://ant.design/docs/react/use-with-create-react-app#Advanced-Guides)

### Steps to reproduce
Current version of Create-React-App is version 3.0.1.
At Ant Design documentation, you suggest that to customize theme, we should use `react-app-rewired` instead of `react-scripts`, combined with `customize-cra` and `babel-plugin-import`.

This is wrong! 
WHY?

Because:
1. At react-app-rewired github README is Dan Abramov comment "Stuff can break".
2. react-app-rewired is not compatible with Create-React-App version 3!

### What is expected?
1. Remove from documentation, section that suggest to use `react-app-rewired` instead of `react-scripts`, combined with `customize-cra` and `babel-plugin-import`. (https://ant.design/docs/react/use-with-create-react-app#Advanced-Guides)
2. Add to documentation soultion described at https://dev.to/agmm/simple-way-of-modifying-ant-design-default-theme-3g4h

### What is actually happening?
Documentation is wrong, and suggest to use outdated solution that will break CRA based project.

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Google Chrome 76.0.3809.87 |
| create-react-app | 3.0.1 |
---
Lost too much time because of outdated documentation.

**Comment by afc163** [comment]
`npm install less -g` is not a good idea, `react-app-rewired` is still working now.

**Comment by Aka4Code** [comment]
@afc163 Why `npm install less -g` is not a good idea?
