### ISSUE TITLE
Descriptions list can't display correctly based on the setting on span props of description item

### ISSUE THREAD

**Issue by NevenLiang** [ant-design/ant-design#18155]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/prod-cherry-clvzc?fontsize=14)

### Steps to reproduce
I want to use `span={2}` in two description item which are at the center of the description list with `column={4}`. They should have almost equal width. 

![image](https://user-images.githubusercontent.com/52629607/62642653-c68f3980-b978-11e9-9349-253d05931932.png)

### What is expected?
The `span` should be works as `flex` property of flex item in flex layout.

They should be work like this.

```
| 1 | 1 | 1 | 1 |
|   2   |   2   |  <-----  The effect at second row is what I want.
| 1 | 1 | 1 | 1 |
|       4       |
```

### What is actually happening?
The `span={2}` in two description item doesn't work well.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | 5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36" |
| Browser | Chrome 75.0.3770.100 |

---
Because the layout of the description list is based on the number and the order of description item, the layout is not easily in the control as table.

Every item may need to be set `span` or the correct order in the list.

If the number of item is not a composite number（合数）, I need to use the `span` to some specific items to control the layout of the list.

**Comment by mercteil** [comment]
I experience exactly the same issue. Tried almost every setting, but a  2-2 row is displayed as 3-1!

**Comment by TranNgocKhoa** [comment]
Same issue here

**Comment by rightroad** [comment]
Same issue here with Descriptions not being responsive. Or let's say it's working but still throwing an error on the console saying: Warning: [antd: Descriptions] Sum of column `span` in a line not match `column` of Descriptions. 

I'm trying to achieve the following: 
 on Desktop:
```
       4
1 | 1 | 1 | 1
       4
   2   |    2
```

on Tablet:
```
       4
   2   |    2
   2   |    2
       4
   2   |    2
```

onMobile: 
```
       4
       4
       4
       .
       .
```

**Comment by iTzMeRafa** [comment]
Any updates on this? I still face this issue

**Comment by chillyistkult** [comment]
Looks like the issue is still present in 4.15.1.

**Comment by dalivk** [comment]
3.x版本，layout='vertical'会出现span异常的问题，渲染后的html中span有些怪异，暂未解决...

**Comment by dalivk** [comment]
3.x版本，layout='vertical'会出现span异常的问题，渲染后的html中span有些怪异，暂未解决...

**Comment by chillyistkult** [comment]
Someone should disable or adjust the bot, because it makes no sense to close tickets because someone mentioned an old version.

**Comment by morix-gao** [comment]
4.17遇到同样问题

**Comment by shaoyi-robin-zhou** [comment]
因为,该方法,通过用table 来实现,span=colspan,所以无解

**Comment by CTX-Rachel** [comment]
5.19.4 仍有相同問題
