### ISSUE TITLE
Attributes 'suffix' and 'allowClear' of component 'Input' is sometime conflicted

### ISSUE THREAD

**Issue by thisrabbit** [ant-design/ant-design#18150]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-ng1un)

### Steps to reproduce
1. Type something on both input component so that the clear icon can show up;

### What is expected?
The position of clear button in the second input component will be exactly the same with the first input component.

### What is actually happening?
The position of clear button in the second input component is wrong.

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 76 |

---
I actually want to create an input component with maximum input length hint, so I put the number in the suffix attribute, but it seems that the clear button only work correctly when the suffix is an icon. I also recommend you guys support the maximum length hint feature because it's useful when developer need to restrain the length user typed in!

**Comment by afc163** [comment]
same as #17414

**Comment by thisrabbit** [comment]
Sorry for duplicate :)
