### ISSUE TITLE
Collapse doesn't work for prop `activeKey` of type number and shows a warning of invalid prop in react hooks

### ISSUE THREAD

**Issue by kushalmahajan** [ant-design/ant-design#18166]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-collapse-keyprop-issue-17qld)

### Steps to reproduce
Just open the console of the project to see the warning due to which collapse doesn't run.

### What is expected?
Prop `activeKey` of type number should be accepted as listed in API of Collapse component

### What is actually happening?
Explained

| Environment | Info |
|---|---|
| antd | 3.20.5 |
| React | 16.8.6 |
| System | MacOS |
| Browser | Chrome |

---
Prop of type string | string []  is working

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/17557

ping @thylsky

**Comment by ztplz** [comment]
https://github.com/react-component/collapse/blob/master/src/Collapse.jsx#L142
It is actually supported, it is wrong here.
