### ISSUE TITLE
Tooltip和disabled Button一起使用，mouseout的时候Tooltip没有隐藏

### ISSUE THREAD

**Issue by zation** [ant-design/ant-design#1816]
http://codepen.io/zation/pen/NNQjaY?editors=001

从button上mouseout不会隐藏tooltip，必须要hover到tooltip上，再mouseout，才会隐藏

**Comment by afc163** [comment]
trace on https://github.com/react-component/tooltip/issues/18

貌似是 chrome 的 bug。
