### ISSUE TITLE
table可编辑表格

### ISSUE THREAD

**Issue by OnPure** [ant-design/ant-design#18162]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/OnPure/EditableTable/tree/master/)

### Steps to reproduce
add a row，我把新加的行的name置为“”，name是可编辑的，但是却不能修改

### What is expected?
即使name为空字符串，也可以修改

### What is actually happening?
不能修改

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.7.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
这是交互设计上的问题，这个例子没有考虑到空字符串的场景，建议用这个交互：https://ant.design/components/table/#components-table-demo-edit-row

**Comment by OnPure** [comment]
> 这是交互设计上的问题，这个例子没有考虑到空字符串的场景，建议用这个交互：https://ant.design/components/table/#components-table-demo-edit-row

也就是说，表格每行需要一个操作控制可编辑是么

**Comment by ZRainc** [comment]
可以改成兼容空字符穿串的场景嘛，具体怎么实现呢

**Comment by 1195002442** [comment]
现在可编辑表格兼容空字符串了吗
