### ISSUE TITLE
Table scroll when some columns set { display: none }, there will be a space in the tail

### ISSUE THREAD

**Issue by LeeSPeed0709** [ant-design/ant-design#18174]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-52qqp?fontsize=14)

### Steps to reproduce
set table scroll to right

### What is expected?
no space

### What is actually happening?
has space

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | react |
| System | windows10 |
| Browser | 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 |

---
在columns中删掉该列可以解决 但是某些时候需要该列存在去保存某些数据。

**Comment by afc163** [comment]
这种情况和 Table 渲染机制有关，不太好办：https://stackoverflow.com/a/916549

建议去掉 column ，把数据保存在 state 中。

**Comment by LeeSPeed0709** [comment]
@afc163 感谢您的回复，我这边通过给该列设置className从样式角度绕过了这个问题。
