### ISSUE TITLE
TreeSelect with showSearch enabled does not obtain scroll position

### ISSUE THREAD

**Issue by laysent** [ant-design/ant-design#18170]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-meitner-2vxlt)

### Steps to reproduce
1. Open `TreeSelect`
2. Click on sub node
3. Reopen `TreeSelect`

![out](https://user-images.githubusercontent.com/1191606/62692455-46fa7c80-ba03-11e9-9d21-410a2ca9e2a8.gif)

### What is expected?
Scroll position should remain the same

### What is actually happening?
Scroll position has been changed.

Notice: if `showSearch` is `false`, it does not have this strange behavior.

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | MacOS |
| Browser | Chrome 75 |

**Comment by bchurlinov** [comment]
I have exactly the same issue, anyone was able to fix this? 

antd: 4.23.0
react: 17.0.1
