### ISSUE TITLE
error logs miss in rc-form

### ISSUE THREAD

**Issue by zhouhaoxiang** [ant-design/ant-design#18175]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/form/blob/master/src/createBaseForm.js#L575](https://github.com/react-component/form/blob/master/src/createBaseForm.js#L575)

### Steps to reproduce
在开发中， 引用 rc-form ，并没有错误提示。 发现 rc-form 打包后，process.env.NODE_ENV !== 'production' 导致开发中没有 error 提示

### What is expected?
希望在控制台能输出 error log

### What is actually happening?
保留 console.error 结果

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | react |
| System | mac |
| Browser | all |

**Comment by afc163** [comment]
这是特意去掉的：https://github.com/ant-design/ant-design/issues/15588
