### ISSUE TITLE
Upload component cannot preview images in JFIF format

### ISSUE THREAD

**Issue by where-picturesque** [ant-design/ant-design#18183]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/bold-meitner-vfk1b)

### Steps to reproduce
null

### What is expected?
Upload component can preview images in JFIF format by fileList attribute.

### What is actually happening?
 Upload component cannot preview images in JFIF format by fileList attribute.
But it can  preview images in JFIF format  when uploading images. 

| Environment | Info |
|---|---|
| antd | 3.21.1 |
| React | 16.2.0 |
| System | windows |
| Browser | chrome 75.0.3770.142 |

**Comment by yoyo837** [comment]
`/^data:image\//.test(url) || /(webp|svg|png|gif|jpg|jpeg|bmp|dpg)$/i.test(extension)`

**Comment by where-picturesque** [comment]
@yoyo837  并不想限制上传图片的格式

**Comment by yoyo837** [comment]
我贴的是Upload组件里面的代码，就认这些，应该改一下就好了

**Comment by where-picturesque** [comment]
@yoyo837  是的，在UploadList 改成` /(webp|svg|png|gif|jpg|jpeg|bmp|dpg|jfif)$/i.test(extension)` jfif格式的图片可以显示了。希望可以加上这个修改 @yesmeck

**Comment by yoyo837** [comment]
请问下你的项目jfif文件都是怎么产生的？这个格式不常见

**Comment by where-picturesque** [comment]
网上下载的图片 通过画图保存时修改保存类型及文件后缀名也可以生成
