### ISSUE TITLE
设置expandedRowKeys属性后点击动作收起动作无效

### ISSUE THREAD

**Issue by elevensky** [ant-design/ant-design#1818]
初始化一个table之后设置expandedRowKeys，默认展开扩展内容，但是展开后点击收缩，无反应。定位在onRowDestroy，改变keys的时候无法获取正常expandedRowkeys.
从state导入expandedRowKeys时，组件内定义的方法，点击报错
onExpandedRowsChange(rows) {
    this.setState({
      expandedRowKeys: rows,
    });
  }
为非function

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by elevensky** [comment]
对不起，我没把问题描述好。
起了个示例[示例](http://codepen.io/elevensky/pen/VaoWjr?editors=001)。
给默认展开keys之后点击就不生效了。

**Comment by afc163** [comment]
expandedRowKeys 写死了，请自行研习 React 受控组件概念。http://facebook.github.io/react/docs/forms.html#controlled-components
