### ISSUE TITLE
DatePicker.MonthPicker组件缺少对monthCellContentRender属性的类型定义

### ISSUE THREAD

**Issue by JonathanLee-LX** [ant-design/ant-design#18186]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-fog-c240y)

### Steps to reproduce
- 打开链接就会看到ts的错误提示

### What is expected?
MonthPicker能添加monthCellContentRender的类型提示

### What is actually happening?
现在的MonthPicker没有为monthCellContentRender提供类型定义，会导致TypeScript的用户无法使用这个属性

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | macOS 10.14.5 (18F203) |
| Browser | 75.0.3770.142 |

**Comment by afc163** [comment]
#18192
