### ISSUE TITLE
Description List column property not working

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#18194]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-p2zpy)

### Steps to reproduce
Create a Description List with prop *'column'* set to 1. 

### What is expected?
Should render 1 description item per row

### What is actually happening?
Renders 3 description items per row which is the default setting

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | Mac OS Mojave |
| Browser | Safari, Chrome, Firefox |

---
Work around is to use *'span'* in the description item list and set it to 1.
But should really work instead with *'column'* prop

**Comment by zombieJ** [comment]
`column={1}` instead of `column="1"`

**Comment by StallionV** [comment]
Thank you I appreciate it. I though it was a bug which is why I posted it here using the official link.
Thanks I will double check before posting.
