### ISSUE TITLE
table rowClassName can't set margin or borderStyle work

### ISSUE THREAD

**Issue by x670783915** [ant-design/ant-design#18191]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我想更多的定制一下 table 里面row的样式，比如设置 margin 或者 border border-radius 使得 tr 更为突出内容，显示数据

### What does the proposed API look like?
目前在rowClassName中设置 margin 或者 border border-radius 不会生效，其他的一些方法都较为繁琐且编码规范不统一 ，希望能够直接通过rowClassName直接设置

**Comment by afc163** [comment]
这个和原生 table 的样式机制有关系，组件库做不了什么事情。
