### ISSUE TITLE
Dynamic left menu

### ISSUE THREAD

**Issue by SimonyanGrno** [ant-design/ant-design#18193]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I get from server number and want to show in left menu. The number will updated every 1 sec.

### What does the proposed API look like?
Before -> https://prnt.sc/oqlpd0  
After -> https://prnt.sc/oqloon

**Comment by keithort** [comment]
This should be handled by your state management implementation, not Ant Design.

**Comment by afc163** [comment]
Like @keithort said.
