### ISSUE TITLE
Table 在拥有 rowSelection 并 fixed 的时候，鼠标高亮有问题

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#18195]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ln13s)

### Steps to reproduce
1. 放置 `Table`
2. 设置 `rowSelection` 为 `fixed`
3. 勾选全选框
4. 把鼠标移上去

### What is expected?
鼠标所在行整行高亮

### What is actually happening?
鼠标所在行只有行首的选择框被高亮。

而把鼠标移动到选择框上，选择框不再高亮，而其余部分高亮。

如果 `columns` 里有 `fixed` 列，也会出现类似的情况，行高亮不正常：鼠标移动到 `fixed` 列上，非固定列高亮；鼠标移到非固定列上，`fixed` 列高亮。

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | latest |
| System | Windows 10 1903 |
| Browser | Chrome Canary 78.0.3877.0 |

**Comment by SHITianhao** [comment]
@afc163 这里是不是应该是 当被选中后鼠标所在行行首也不高亮？这样和非固定的保持一致

**Comment by SHITianhao** [comment]
这个bug 的问题是因为当设定 `fixed:true` 的情况，固定列是在另外一个table里，所以当鼠标移到行上的时候没有触发固定列的`hover`属性。是不是可以考虑只通过className `ant-table-row-hover` 判断？不添加`&:hover` 的判断

**Comment by zmayor** [comment]
所以现在只要选中了就不会有hover是正常的表现吗? 但是我觉得体验不太好呢.
