### ISSUE TITLE
select 选当前已选中的 option 不会收起

### ISSUE THREAD

**Issue by hanai** [ant-design/ant-design#182]
就是这样设计的么？

**Comment by afc163** [comment]
https://github.com/react-component/menu/blob/8a8dd800fbe6ff6ab66814e03298151080f656a2/src/MenuItem.jsx#L61

**Comment by afc163** [comment]
还有一个问题，目前多选框选择之后弹层收起了，应该是不变的。

**Comment by afc163** [comment]
@hanai Thx, fixed it in `beta` version.
