### ISSUE TITLE
Affix组件使用时，到达偏移量后，未添加width

### ISSUE THREAD

**Issue by xueyuchen** [ant-design/ant-design#1820]
Affix组件，在到达偏移量后，组件少了with样式，导致Affix组件内部样式混乱

## What you did（你做了什么）

```javascript
<Affix offsetTop={60}>
          <div className="md-menubar">
            {this._getModeBar()}
            {this._getToolBar()}
          </div>
        </Affix>
```

## What you would like to happen（你期待的结果）

```javascript
<div class="ant-affix" data-reactid=".0.1.$/=11.0.$/=10.1.$/=10.0.0.$/=10.0.3.0.0" style="width: ???px; position: fixed; top: 60px; left: 193.234px;">
```

## What actually happened（实际上的结果）

```javascript
<div class="ant-affix" data-reactid=".0.1.$/=11.0.$/=10.1.$/=10.0.0.$/=10.0.3.0.0" style="position: fixed; top: 60px; left: 193.234px;">
```

## Online demo（可重现的在线演示）

无

## Environment Information（本地环境信息）

- The version of antd: 1.1.0
- Your operating system and it's version: 10.11.4
- Your browser and it's version:  50.0.2661.86 (64-bit)

- antd 版本: 1.1.0
- 操作系统及其版本：10.11.4
- 浏览器及其版本:   50.0.2661.86 (64-bit)

**Comment by afc163** [comment]
也可以用 `ant-affix`（固定时会加上） 样式自行处理。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/0.12.17/components/affix/index.jsx#L65

貌似升级 1.0 的时候搞丢了。@RaoHai 可以 PR 过来，只加 width 就好。
