### ISSUE TITLE
Property 'children' does not exist on type 'IntrinsicAttributes & UploadProps & { height?: number | undefined; }' in Dragger component

### ISSUE THREAD

**Issue by chachaxw** [ant-design/ant-design#18207]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/chachaxw/react-typescript-admin/blob/aa7d9fb6856f574a7fd6a819f3510f682ad0bfb5/src/pages/Dashboard/Dashboard.tsx#L72](https://github.com/chachaxw/react-typescript-admin/blob/aa7d9fb6856f574a7fd6a819f3510f682ad0bfb5/src/pages/Dashboard/Dashboard.tsx#L72)

### Steps to reproduce
npm install && npm start

### What is expected?
Project can run normally.

### What is actually happening?
There's a typescript error with Property 'children' does not exist on type 'IntrinsicAttributes & UploadProps & { height?: number | undefined; }'

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.3 |
| System | Mac OS |
| Browser | Chrome Version 76.0.3809.100  |

---
I checked the source code, Ant design version 3.20.4 changed Upload.Dragger as a JSX Element, but before that version, Upload.Dragger is a react component, this caused typescript errors, please fix this.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/18196

**Comment by chachaxw** [comment]
@afc163 Good Job, thanks👍
