### ISSUE TITLE
getFieldDecorator trigger 在无状态组件中报错

### ISSUE THREAD

**Issue by Here21** [ant-design/ant-design#18200]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
![image](https://user-images.githubusercontent.com/12051024/62820902-1ef35080-bb9e-11e9-9a0e-7f1e18e1aead.png)

复现方式：
```jsx
<Form.Item label="站点">
          {getFieldDecorator('siteIds', {
            trigger: 'onChange',
          })(<AddStationModal />)}
</Form.Item>
```

如果`<AddStationModal />`组件为无状态组件，则会报错：
```jsx
function AddStationModal({ data, onChange }) {
  const [visible, setVisible] = useState(false);

  return (
    <div>
      <Button onClick={() => setVisible(true)}>添加站点</Button>
      <Modal
        title="添加站点"
        visible={visible}
        onOk={() => {}}
        onCancel={() => setVisible(false)}
        width={800}
      >
        <AddStationForm
          onSubmit={() => {
            onChange([1, 2, 3, 4]);
          }}
        />
        <Transfer
          styleName="station-transfer"
          dataSource={[]}
          onChange={() => {}}
          lazy={false}
          targetKeys={[]}
          render={item => item.title}
          listStyle={{
            width: 300,
            height: 300,
          }}
        />
      </Modal>
    </div>
  );
}
```

如果为`Class Component`则正常：
```jsx
export default class StationModal extends Component {
  render() {
    return (
      <div>
        <Button>站点</Button>
      </div>
    );
  }
}
```

### What is expected?
在无状态组件中不报错

### What is actually happening?
在无状态组件中报错

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | MacOS |
| Browser | Chrome |

**Comment by huntdream** [comment]
用`forwardRef`包一下就好了

**Comment by tancgo** [comment]
> > 用`forwardRef`包一下就好了
> 
> 确实， `Antd.Form` 里自定义函数组件要用 `forwardRef` 处理

用forwardref处理之后会报这个错误 ： forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component?    不设置propTypes后eslint又会报错

**Comment by huntdream** [comment]
@tancgo 能贴那块的代码看看吗？

**Comment by huntdream** [comment]
@tancgo 能贴那块的代码看看吗？

**Comment by Here21** [comment]
> > > 用`forwardRef`包一下就好了
> > 
> > 
> > 确实， `Antd.Form` 里自定义函数组件要用 `forwardRef` 处理
> 
> 用forwardref处理之后会报这个错误 ： forwardRef render functions do not support propTypes or defaultProps. Did you accidentally pass a React component? 不设置propTypes后eslint又会报错

可以看一下[这个](https://github.com/facebook/prop-types/issues/200)，可以在这个组件内不使用propTypes检查，可以在改组件文件的头部添加`/* eslint-disable */`来告诉Eslint忽略这个文件

如果对propTypes有强制需求，可以像上面链接中的，做一个Component PropTypes
