### ISSUE TITLE
New component example codes for function component

### ISSUE THREAD

**Issue by Frezc** [ant-design/ant-design#18212]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
From react@16.8, function component may be a more efficient way to write components. For beginner learn React from function component, legacy class component may be confusing and force them to understand class components.

### What does the proposed API look like?
Add a tab "show code in function component" or rewrite examples in 4.0

**Comment by zombieJ** [comment]
For updated component in 4.0, we have updated with Hooks & typescript. Others is welcome for volunteer.
ref: https://github.com/ant-design/ant-design/tree/4.0-prepare

Merge into #16911

**Comment by Frezc** [comment]
I have not found the plan about rewriting examples in the issue you mentioned. IMO, we should keep a issue to trace this.
