### ISSUE TITLE
Modal使用getContainer={false}时wrap层阻碍页面操作

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#18215]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-sun-6ubji)

### What is expected?
getContainer={false} 不应该影响页面其他内容

### What is actually happening?
getContainer={false} 的Modal关闭后会因为wrap层阻碍页面操作

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest |

**Comment by yoyo837** [comment]
默认`getContainer`:

![image](https://user-images.githubusercontent.com/6134547/62844740-e6668a80-bcf5-11e9-81e6-1bdbc05627e8.png)

默认`getContainer={false}`:

![image](https://user-images.githubusercontent.com/6134547/62844764-0e55ee00-bcf6-11e9-9a41-18c916fc3c51.png)

**Comment by jljsj33** [comment]
漏了，，没深入了解 dialog 的问题，，实现跟 drawer 不一样，，还要在 didMount 里控制 dom。。。

**Comment by yoyo837** [comment]
@jljsj33 大佬，还得改改，第二次打开就只剩mask了显示了，wrap是持续`display: none;`

**Comment by yoyo837** [comment]
先reopen放着吧，避免遗漏...

**Comment by jljsj33** [comment]
不会啊，，第二次会把 display 去掉的啊

**Comment by jljsj33** [comment]
我日，，好像还忘了个默认打开状态，，我擦。。。

**Comment by jljsj33** [comment]
😭

**Comment by jljsj33** [comment]
dialog v7.5.4

**Comment by yoyo837** [comment]
@jljsj33 我这边的场景OK了。
