### ISSUE TITLE
TextArea props autosize={{ minRows: 2, maxRows: 6 }} scrollbar blinking

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#18216]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input/](https://ant.design/components/input/)

### Steps to reproduce
Press the Enter key 6 times
![bug](https://user-images.githubusercontent.com/8358236/62847258-e1aad200-bd07-11e9-9c07-d2d688eac5ca.gif)

### What is expected?
no blinking

### What is actually happening?
blinking

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | latest |
| System | windows 10 |
| Browser | chrome |

**Comment by SuZhenYu2** [comment]
设置 autosize属性后 TextArea 就会出现这个问题

**Comment by afc163** [comment]
http://recordit.co/1hKxBdERqm

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/62850788-a532a280-bd16-11e9-949b-090c40d4afac.gif)

**Comment by yafeicui** [comment]
现在antd的官网上这个问题还在

**Comment by best-lucky1030** [comment]
@afc163
I'd like to make Input Textarea with maxRows number.
In this case, how can I make this?
My code is like below, but I got the error and didn't run it correctly.

`<Input.TextArea  autoSize={maxRows} />`
