### ISSUE TITLE
When the title of the tree component is multi-select, the subsequent multi-selection box does not work properly.

### ISSUE THREAD

**Issue by wyj1242** [ant-design/ant-design#18214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-kilby-b1pn5)

### Steps to reproduce
Click the multi-box component on the title repeatedly

### What is expected?
Ability to properly select and cancel selected like normal multi-box components

### What is actually happening?
After selecting or unchecking, you need to click multiple times. When the first one is selected, you cannot uncheck it again. In short, it cannot be selected or unchecked.

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | windows10 |
| Browser | Chrome 74.0.3729.169 |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/inspiring-wiles-uj4l4 `stopPropagation`

**Comment by wyj1242** [comment]
Thank you very much!!!




------------------ 原始邮件 ------------------
发件人: "zombieJ"<notifications@github.com>; 
发送时间: 2019年8月12日(星期一) 下午3:21
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 
抄送: "科技"<1040158177@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ant-design/ant-design] When the title of the tree component ismulti-select, the subsequent multi-selection box does not work properly.(#18214)




https://codesandbox.io/s/inspiring-wiles-uj4l4 stopPropagation
