### ISSUE TITLE
Popconfirm onConfirm 第一次点击不触发方法

### ISSUE THREAD

**Issue by jinpanpan66** [ant-design/ant-design#18213]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。
Popconfirm onConfirm 第一次点击不触发onConfirm 绑定的方法，第二次后会正常触发

**Comment by isaak-zmg** [comment]
这个问题解决了吗  今天也遇到到同样的问题 @jinpanpan66
