### ISSUE TITLE
select 的 showSearch 搜索框的 onSearch 在不选中任何一条数据鼠标离开后能不能不请求接口

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#18222]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在是输入框输入文字，接口请求一次，然后不选中任何一条数据，鼠标离开其他地方点击一次，搜索结果关闭，但是 onSearch 又执行了一次。

### What does the proposed API look like?
期望是鼠标离开不选中情况下，不调用 onSeach 方法，因为输入框清空跟鼠标离开的 value 都是空，我没法判断是搜索的空值，还是没有选中一条数据。

例子就是官网的这个 https://ant.design/components/select-cn/#components-select-demo-search-box

**Comment by qq645381995** [comment]
现在是鼠标离开照样请求了一次 q='' 的请求

![image](https://user-images.githubusercontent.com/7971419/62854690-a2d64580-bd22-11e9-960c-ff1ae20d1b7b.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16771

**Comment by qq645381995** [comment]
不试用 AutoComplete 把，搜索不到的条件，不能留在文本框中的。

**Comment by qq645381995** [comment]
真心希望  onSearch 添加第二个参数 type = change | blur

**Comment by qq645381995** [comment]
搜索框清空，跟鼠标离开就不能是2种状态吗

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/29a47b0c7d075f6346218b141d448dc6fe659bce

**Comment by qq645381995** [comment]
想着搜索栏输入内容检索出来模糊数据然后鼠标离开后再点击搜索栏还能看到刚才的结果。
