### ISSUE TITLE
tree组件：checkable功能造成expandedKeys  树展开失效

### ISSUE THREAD

**Issue by 723179766** [ant-design/ant-design#18223]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-frog-evttm)

### Steps to reproduce
tree 组件官网例子，可搜索的树，加上checkable，搜索失效，无法搜索3层以下的节点，输出expandedKeys 数值正确

### What is expected?
可以展开深层级

### What is actually happening?
只能展开到第二级

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
Your codesandbox don't works.

**Comment by 723179766** [comment]
https://codesandbox.io/s/antd-reproduction-template-kq4rq   试一下这个呢   搜索深层以下节点无法展开




------------------ 原始邮件 ------------------
发件人: "Ant Design GitHub Bot"<notifications@github.com>;
发送时间: 2019年8月12日(星期一) 下午5:59
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "侯超瑜"<723179766@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ant-design/ant-design] tree组件：checkable功能造成expandedKeys  树展开失效 (#18223)




Hello @723179766. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
你好 @723179766, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
