### ISSUE TITLE
skeleton prop for Button/Avator/Input/Progress

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#18237]
```jsx
<Button skeleton />
<Avator skeleton />
<Input skeleton />
```

or

```jsx
<Skeleton.Button />
<Skeleton.Avatar />
<Skeleton.Input />
```

ref: https://github.com/mui-org/material-ui/pull/16786

**Comment by Rustin-Liu** [comment]
我想做这个，按照顺序一个一个做吧。

**Comment by Rustin-Liu** [comment]
@afc163  The Progress still in progress.😂

**Comment by afc163** [comment]
再单独做就好了，Progress 不是很常用，我只是想到写在这里，肯定也不止 Progress，Table/Card/List/PageHeader/Alert/Steps/Menu 等等组件都可以做也更常用。

**Comment by Rustin-Liu** [comment]
> 再单独做就好了，Progress 不是很常用，我只是当时想到就写在这里。肯定也不止 Progress，Table/Card/List/PageHeader/Alert/Steps/Menu 等等组件都可以做也更常用。

要不我晚点建个issue，然后加个help label就可以慢慢做了。
