### ISSUE TITLE
[typescript] Transfer need generic like Table

### ISSUE THREAD

**Issue by zmayor** [ant-design/ant-design#18236]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-transfer-interface-jut39)

### Steps to reproduce
I wrote a table transfer followed the official demo [Table Transfer](https://ant.design/components/transfer-cn/#components-transfer-demo-table-transfer) in `typescript`. But there was some type error.

### What is expected?
I expect I can set a generic for Transfer like Table:
```
interface IItem {...}
<Transfer<IItem>
...
/>
```

### What is actually happening?
Some type errors happened.

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.8.6 |
| System | windows server 2008 |
| Browser | chrome 76 |

**Comment by n0ruSh** [comment]
@afc163 I would like to pick this one. Shall the pr go against feature branch (i.e. a feature) or master branch (i.e. a fix)?

**Comment by afc163** [comment]
TypeScript improvement can go to master.

**Comment by afc163** [comment]
supported in https://github.com/ant-design/ant-design/pull/27630
