### ISSUE TITLE
some error About Table Border Line(Alignment Problem)

### ISSUE THREAD

**Issue by BeautifulHao** [ant-design/ant-design#18239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/still-dust-gqr9k?fontsize=14)

### Steps to reproduce
you set Table like this  " scroll={{ y: 300 }}",the table's Border Line may take Alignment Problem

### What is expected?
NO Alignment Problem

### What is actually happening?
Alignment Problem

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome 76 |

**Comment by afc163** [comment]
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/507615/62917779-28fc9580-bdd0-11e9-8211-6cf70462a15a.png">

https://ant.design/components/table/#components-table-demo-fixed-columns

**Comment by BeautifulHao** [comment]
我觉得你这个关闭处理的原因太牵强了吧！！！！

示例中我只是设置了scroll.y的值，就出现了表头和表体不对齐问题， 而且列数没有很多，不需要横向滚动条+锁定行。如果按照你这么处理，效果很难看。明明是表格内容和表头不对齐的问题，为什么不修改边框宽度的计算方式，而用scoll.x这种不人性化的方式处理。@afc163

**Comment by BeautifulHao** [comment]
表格表体对齐 真的这么难么 @afc163

**Comment by afc163** [comment]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/507615/62920968-db852600-bdd9-11e9-9949-ff25e420feaa.png">

**Comment by afc163** [comment]
没这么简单的，目前的实现需要制定列宽度，有什么好的解决方案，欢迎 PR。
