### ISSUE TITLE
mobx加form表单，当mobx中绑定到form表单的数据改变时，不会触发mapPropsToFields方法

### ISSUE THREAD

**Issue by mqyun** [ant-design/ant-design#18234]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mqyun/antd-mobx](https://github.com/mqyun/antd-mobx)

### Steps to reproduce
npm install 后， npm start运行进入 /login 页面，输入表单信息，点击重置按钮mobx中数据清空了，但是不会触发antd form的mapPropsToFields方法，页面上仍显示input内容

### What is expected?
数据清空后和mobx中的数据保持一致，form表单信息清空

### What is actually happening?
form表单显示未清空，实际mobx中的数据已清空

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.4 |
| Browser | 76.0.3809.100 |

**Comment by afc163** [comment]
加上这句话就好了，看上去和 antd 没关系：https://github.com/mqyun/antd-mobx/pull/1

**Comment by mqyun** [comment]
这个并没有解决根本的问题，在父组件加了这句话也只是因为触发了父组件的重渲染，进而使子组件进行了渲染

**Comment by afc163** [comment]
看看 https://github.com/ant-design/ant-design/issues/12904

**Comment by w345731923** [comment]
我也遇到了相同问题，mapPropsToFields只加载了一次，store数据刷新后，form没有反应。
但是通过点击按钮是可以获取到store的值，比如在componentDidMount加了一个store的方法，去测试mapPropsToFields方法，结果还是无效
