### ISSUE TITLE
antd v3.10.10升级到v3.21.2导致该问题。AutoComplete受控时，使用onSearch监控输入事件，不能输入中文。

### ISSUE THREAD

**Issue by superwyk** [ant-design/ant-design#18230]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/autocomplete-bug-recurrent-odfuk)

### Steps to reproduce
1、AutoComplete受控
2、使用onSearch监控输入事件
3、输入中文

### What is expected?
期望能输入中文

### What is actually happening?
不能输入中文

| Environment | Info |
|---|---|
| antd | 3.21.2 |
| React | 16.8.6 |
| System | macOS 10.12.6 |
| Browser | chrome75.0.3770.142 |

---
虽然可以用onChange事件代替onSearch事件，但是不管怎样，不能输入中文(还有日文、韩文IME等)，影响还是挺大的。

追根溯源，该问题是由于使用了setState function updater导致的。
react-component/select/blob/master/src/Select.tsx  -> setInputValue():
```js
const { onSearch } = this.props;
if (inputValue !== this.state.inputValue) {
      this.setState(prevState => {
        // Additional check if `inputValue` changed in latest state.
        if (fireSearch && inputValue !== prevState.inputValue && onSearch) {
          onSearch(inputValue);
        }
        return { inputValue };
      }, this.forcePopupAlign);
    }
```
react-component/select/blob/master/src/Select.tsx  -> getDerivedStateFromProps():
```js
if ('value' in nextProps) {
      const value = Select.getValueFromProps(nextProps);
      newState.value = value;
      if (nextProps.combobox) {
        newState.inputValue = Select.getInputValueForCombobox(nextProps, optionsInfo);
      }
    }
```
解读:
setState function updater里调用onSearch，当前子组件和父组件生命周期调用顺序如下：
当前子组件render -> 父组件render -> 当前子组件render，因为当前子组件先render一遍，而inputValue是从Props获取值的，inputValue会被设置两次值，并且第一次设置会把IMF最后一个输入字符去掉，这样input value会被设置两次不同的值，导致不能输入中文。

经测试，
onSearch在setState里面调用，会导致当前子组件render两次，父组件render一次；
onSearch在setState外面调用，当前子组件、父组件都只会render一次。所以onSearch放在setState外面调用也没关系。

我写了个小例子，input元素不能输入中文，重现上面的情况。
[https://codesandbox.io/embed/disable-imf-z2zkj](https://codesandbox.io/embed/disable-imf-z2zkj)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17916#issuecomment-515856654

**Comment by zombieJ** [comment]
`onSearch` 不是受控的时机，AutoComplete 里应该是 `onChange` 配合 `value`。这边文档会改一下。
