### ISSUE TITLE
Timezone is not visible in spite of correct moment() format

### ISSUE THREAD

**Issue by inaps** [ant-design/ant-design#18232]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-4vol9)

### Steps to reproduce
Look at timezone format

### What is expected?
Value is 08/12/2019 5:29 PM (MSK)

### What is actually happening?
Value is 08/12/2019 5:29 PM ()

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | React 16.8.6 |
| System | Windows 10 |
| Browser | Google Chrome 76.0.3809.100  |

---
z - option is for timezone and it's lost

**Comment by afc163** [comment]
I don't think it is relevant with antd: https://codesandbox.io/s/antd-reproduction-template-b6skl
