### ISSUE TITLE
form.validateFields中err参数会打印出其他表单message的东西，怎样才能让它跟其它表单不关联呢

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design#18246]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
form.validateFields中err参数会打印出其他表单message的东西，怎样才能让它跟其它表单不关联呢

### What is expected?
可以跟当前表单单独使用

### What is actually happening?
会关联到其它表单

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by dongkeng001** [comment]
form.validateFields((err, fieldsValue) => {
//err 会打印出其他表单message的东西，怎样才能让它跟其它表单不关联呢
      if (err) return;
      const values = {
        ...fieldsValue,
        updatedAt: fieldsValue.updatedAt && fieldsValue.updatedAt.valueOf(),
      };
});

**Comment by yoyo837** [comment]
表单独立没？是否嵌套表单

**Comment by dongkeng001** [comment]
独立的，一个是查询表单，一个是弹窗里面的input输入框表单，都是分开的，我点击查询，把弹窗的表单提示信息都给返回来了


在2019年08月13日 21:03，Amumu 写道：

表单独立没？是否嵌套表单

**Comment by yoyo837** [comment]
你弹窗的容器确认下是不是在查询表单内

**Comment by dongkeng001** [comment]
> 你弹窗的容器确认下是不是在查询表单内

最后发现弹窗没有单独使用Form.create导致的
