### ISSUE TITLE
RangePicker国际化配置，中文部分生效

### ISSUE THREAD

**Issue by fe-linjin** [ant-design/ant-design#18247]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

![image](https://user-images.githubusercontent.com/42307527/62941555-ea370180-be08-11e9-91fc-4b3d4b373066.png)

![image](https://user-images.githubusercontent.com/42307527/62941236-27e75a80-be08-11e9-9025-85ab3d14ca4b.png)

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by liangGeek** [comment]
> The issue which is not created via http://new-issue.ant.design will be closed immediately.
> 
> ![image](https://user-images.githubusercontent.com/42307527/62941555-ea370180-be08-11e9-91fc-4b3d4b373066.png)
> 
> ![image](https://user-images.githubusercontent.com/42307527/62941236-27e75a80-be08-11e9-9025-85ab3d14ca4b.png)
> 
> 注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

我也遇到这样的问题了  怎么解决的啊

**Comment by fe-linjin** [comment]
> > The issue which is not created via http://new-issue.ant.design will be closed immediately.
> > ![image](https://user-images.githubusercontent.com/42307527/62941555-ea370180-be08-11e9-91fc-4b3d4b373066.png)
> > ![image](https://user-images.githubusercontent.com/42307527/62941236-27e75a80-be08-11e9-9025-85ab3d14ca4b.png)
> > 注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。
> 
> 我也遇到这样的问题了 怎么解决的啊

用旧的国际化配置暂时解决了这个问题
`
/** antd 国际化配置中文 */
import { LocaleProvider } from 'antd' //  将日历从英文处理为中文
import zhCN from 'antd/lib/locale-provider/zh_CN' //  将日历从中文处理为英文
....
<LocaleProvider locale={zhCN}>
                    <RangePicker
                        className="search-time search-font-style"
                        showTime={{ format: 'HH' }}
                        format= 'YYYY-MM-DD HH'
                        onChange={handleTimeChange}
                    />
                </LocaleProvider>
.....
`
