### ISSUE TITLE
ie突然打不开react项目  Minified React error #31

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design#18240]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%24%24typeof%2C%20type%2C%20key%2C%20ref%2C%20props%2C%20_owner%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.  

### What does the proposed API look like?
是ie突然不支持某种写法吗   百思不得其解

**Comment by liyue118** [comment]
上周打包后是正常的，这周就打不开了。

**Comment by afc163** [comment]
你最好自行排查一下，这样提问基本上没有有效信息。
