### ISSUE TITLE
编译都通过entry/index.jsx为出口，那么如果是ReactDOM.render的节点在不同html，打开html就会由于ReactDOM.render包含该页面不存的节点而报错

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#1825]
> 特别提示：报告 bug 前请确保你的问题是可复现的，并务必提供复现步骤，否则恕难解决。

If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

提问之前，建议先阅读[这份提示](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question)。:-)

If you are going to report a bug, please answer the following questions, thank you!

如果是报告 bug，请按照下列格式编辑问题，非常感谢！

## What you did（你做了什么）

(e.g. I ate a hamburger)

（例如，我吃了一个汉堡）

## What you would like to happen（你期待的结果）

(e.g. I should be full)

（例如，我应该饱了）

## What actually happened（实际上的结果）

(e.g. But I am still hungry now T_T)

（例如，我还是饿的，肯定是哪里出问题了）

## Online demo（可重现的在线演示）

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information（本地环境信息）

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by afc163** [comment]
非 antd 问题，建议系统学习 http://facebook.github.io/react/ 并到相关论坛提问。

另外，这种格式提交问题，相当不负责任。

**Comment by aw6658913** [comment]
不好意思，下次会注意，感谢您耐心回答

**Comment by afc163** [comment]
多一份换位思考，社区会更美好。:santa:

**Comment by aw6658913** [comment]
下次一定清空~
