### ISSUE TITLE
antd with TinyMCE: Correct use of antd's getFieldDecorator implementation with TinyMCE

### ISSUE THREAD

**Issue by ankur17** [ant-design/ant-design#18258]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tinymce-antd-qmsp9)

### Steps to reproduce
We wanted to know the correct way of implementing TinyMCE with antd using getFieldDecorator.
Issue:
1. The problem we are facing is, when the component with Editor as a child is destroyed and getFieldDecorator's rule is {required:true}, then there is error when the component is destroyed for the 2nd time(not for the first time).
2. When we press enter after writing some text. the current line goes to 2nd line and the cursor gets to the first.

### What is expected?
Expected result for the issue (respectively):
1. No error should come after any number of component destroys 
2. Upon Enter keyboard event the cursor should go to the next line.

### What is actually happening?
issue(respectively):
1. When the rule required is true, the code still checks for the input field even when it is destroyed., so because of this it is creating error, as the data field it is checking is null, but since the rule is required, returns an error to the destroyed component. And that happens only when the component is destroyed for the 2nd time.
2. When we press enter after writing some text. the current line goes to 2nd line and the cursor gets to the first.

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | MAC   Windows   Ubuntu |
| Browser | Chrome |

---
We implemented based on the docs but could not find the solution for the correct implementation of TinyMCE with antd using getFieldDecorator

Image for the issue(respectively):
1. https://drive.google.com/open?id=1VV25MN6X_HHAEc3rlgrR9Pdu1udW-Eha
2. https://drive.google.com/open?id=1t7_DWu7c4AUKtXWrW5s1pLzIrXaIvNbx

**Comment by zombieJ** [comment]
In most case, strange behavior of cursor is caused by customize component logic. Since in the Form side, it's simply set `value` and get value by `onChange` event.
You can help `TinyMCE` to dig into for the reason of it (I see it use iframe to handle component, not sure if there exist some gap in it).
