### ISSUE TITLE
Get error when compile project by ts.

### ISSUE THREAD

**Issue by linlingyu** [ant-design/ant-design#18259]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/linlingyu/hello-antd](https://github.com/linlingyu/hello-antd)

### Steps to reproduce
when start to compile the ts project, it will get error from the page which use the Tooltip component of antd.
try to run command: npm run compile

### What is expected?
compile the project no error.

### What is actually happening?
get error when compile the ts project.

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | darwin, windows, linux |
| Browser | chrome |

**Comment by afc163** [comment]
```diff
+ "allowSyntheticDefaultImports": true,
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18273
