### ISSUE TITLE
月份区间控件切换年份后默认值还继续高亮

### ISSUE THREAD

**Issue by Somnus001** [ant-design/ant-design#18252]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
月份区间控件打开下拉面板切换年份后，默认的月份仍然高亮显示（例如：默认值的开始时间是‘2019-09’，将年份切换到2018年，09月仍然高亮，给人的感觉像是已经切换到了‘2018-09’），而此时并不代表控件的值发生了变化

### What does the proposed API look like?
在下拉面板切换年份后默认的月份不高亮

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
