### ISSUE TITLE
Console the output other than option select in autocomplete

### ISSUE THREAD

**Issue by renjiie** [ant-design/ant-design#18254]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-huxpr)

### Steps to reproduce
Choose autocomplete from antd

### What is expected?
Only the selected values from dropdown are getting logged in console with onSelect . The other typing inputs are not logged . onSearch is triggering on every input .

### What is actually happening?
Only the selected values from dropdown are getting logged in console with onSelect . The other typing inputs are not logged . onSearch is triggering on every input .

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.7  |
| System | Windows 10 |
| Browser | chrome 76.0.3809.100 |

---
How can I log the values on press enter or on click of search Icon

**Comment by afc163** [comment]
Try onSelect over onSearch.
