### ISSUE TITLE
How to format number currency suffix in component InputNumber?

### ISSUE THREAD

**Issue by phucvo0709** [ant-design/ant-design#18267]
As the title, I have tried many times the code without success, hoping for help from the community

this code format currency prefix!

```
<InputNumber
   defaultValue={1000}
   formatter={value => `$ ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
   parser={value => value.replace(/\$\s?|(,*)/g, '')}
/>

```

**Comment by afc163** [comment]
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
