### ISSUE TITLE
升级1.1.0后 Popover的属性content不可用

### ISSUE THREAD

**Issue by yayamommy** [ant-design/ant-design#1826]
* 升级1.1.0后，Popover用属性content填充内容，鼠标放上去没有内容出现。
* 退回版本0.12.0后，用属性overlay，内容出现。
* 这是不是一个bug啊？

**Comment by afc163** [comment]
升级不看 changelog，不专业。

http://ant.design/#/docs/react/changelog?scrollTo=1.0.0
