### ISSUE TITLE
How to format number currency suffix in component InputNumber?

### ISSUE THREAD

**Issue by phucvo0709** [ant-design/ant-design#18269]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As the title, I have tried many times the code without success, hoping for help from the community
this code format currency prefix!

### What does the proposed API look like?
```
<InputNumber
   defaultValue={1000}
   formatter={value => `$ ${value}`.replace(/\B(?=(\d{3}) (?!\d))/g, ',')}
   parser={value => value.replace(/\$\s?|(,*)/g, '')}
/>
```

**Comment by mcyleung** [comment]
I used 'react-number-format' with Intl.NumberFormat. That way I didn't have to write any prefixes. And if you want ant design's styling, you just have to do className='ant-input' and it solves the issue

**Comment by phucvo0709** [comment]
> I used 'react-number-format' with Intl.NumberFormat. That way I didn't have to write any prefixes. And if you want ant design's styling, you just have to do className='ant-input' and it solves the issue

I used and succeeded, but I had the problem of not showing the error of antd rules

**Comment by Utkarshbhimte** [comment]
@phucvo0709 You can check out my implementation [here](https://codesandbox.io/s/currency-wrapper-antd-input-3ynzo)

**Comment by burakkilic** [comment]
> I used 'react-number-format' with Intl.NumberFormat. That way I didn't have to write any prefixes. And if you want ant design's styling, you just have to do className='ant-input' and it solves the issue

Have you used in Ant form item?

**Comment by mauron85** [comment]
> @phucvo0709 You can check out my implementation [here](https://codesandbox.io/s/currency-wrapper-antd-input-3ynzo)

yours and also implementation in antd manual has an UX issue, so when you type 1234 you will end up with 1,002.34. Also when you tried to delete all digits you will end up cursor on 0.00 so it's not possible to type integer number, without moving cursor either with mouse or arrow key.

**Comment by afc163** [comment]
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
