### ISSUE TITLE
命令创建项目后引入组件时报错

### ISSUE THREAD

**Issue by singgl** [ant-design/ant-design#18263]
/node_modules/ant-design-vue/es/style/index.less (./node_modules/css-loader??ref--10-oneOf-3-1!./node_modules/postcss-loader/src??ref--10-oneOf-3-2!./node_modules/less-loader/dist/cjs.js??ref--10-oneOf-3-3!./node_modules/ant-design-vue/es/style/index.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in F:\Example\Vue3.0\antd-demo\node_modules\ant-design-vue\es\style\color\bezierEasing.less (line 110, column 0)

**Comment by chenshunyu** [comment]
```js
module.exports = {
	css: {
		loaderOptions: {
			css: {
				url: false,
			},
		},
	},
};
```
I resolve this problem: turn css.url to 'false'
