### ISSUE TITLE
TreeSelect newly added nodes not automatically expanded when treeDefaultExpandAll=true.

### ISSUE THREAD

**Issue by aaronperkins** [ant-design/ant-design#18278]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sharp-liskov-5661b?fontsize=14)

### Steps to reproduce
1. Create a TreeSelect with treeDefaultExpandAll=true and treeData set to a object with children
2. Add a new node with children to treeData

### What is expected?
Newly added nodes should also have their children expanded when treeDefaultExpandAll=true.

### What is actually happening?
The original nodes have their children expanded, but the new node does not have it's children expanded by default.

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | NA |
| Browser | All |

**Comment by afc163** [comment]
Like `defaultValue` to input, `treeDefaultExpandAll` only works in first render.

**Comment by daryl0313** [comment]
After the first render use `treeExpandedKeys` and include all the keys of all the nodes that need to be expanded.
