### ISSUE TITLE
Select 选择器问题

### ISSUE THREAD

**Issue by durongzhang** [ant-design/ant-design#1827]
## 操作

![image](https://cloud.githubusercontent.com/assets/15725537/15491754/5f7cbd7a-21a6-11e6-800b-f6182da06297.png)

选择超过一行，关掉这个选项时内容不跟随

![46b14e4d-dc10-4dd3-a655-39abab115687](https://cloud.githubusercontent.com/assets/15725537/15491748/47358756-21a6-11e6-90ae-74c2f70235cb.jpg)

## 本地环境信息

- antd 版本: 1.1.0
- 操作系统及其版本：win
- 浏览器及其版本: All

**Comment by RaoHai** [comment]
http://codepen.io/RaoHai/pen/aNeRYo?editors=001

**Comment by durongzhang** [comment]
#### 先选择超过两行
![image](https://cloud.githubusercontent.com/assets/15725537/15496414/98a06392-21c7-11e6-9280-75eb865156c2.png)
#### 再关掉最后一个
![image](https://cloud.githubusercontent.com/assets/15725537/15496422/a878abe4-21c7-11e6-8b92-56634144160c.png)
### 就会出现间隙
![image](https://cloud.githubusercontent.com/assets/15725537/15496438/ba70c75a-21c7-11e6-828b-8da29581259a.png)

**Comment by RaoHai** [comment]
嗯。这个我已经知道是什么状况了。谢谢反馈。

**Comment by superRaytin** [comment]
这个问题的原因是：

1. dom-align 依赖于 dom 位置发生变化
https://github.com/react-component/align/blob/master/src/Align.jsx#L76
2. 取消选中最后一个（导致折行的），向下渲染执行到 dom-align 调整下拉框位置的时候，此时 value state 虽然更新了，但输入框上的选中列表 dom 还未渲染完成，所以 dom-align 计算后还是原有位置 https://github.com/react-component/select/blob/master/src/Select.jsx#L757

解决方案应该为：保证选中列表的 dom 更新完成时，再调用 dom-align 计算位置。

**Comment by superRaytin** [comment]
将通过 https://github.com/react-component/select/commit/e117897088ec6aa22b965bd1d2863333a36012c5 修复，等待新版本发布。
