### ISSUE TITLE
Typescript TS1259，React 的引用方式变化造成的错误

### ISSUE THREAD

**Issue by lidianhao123** [ant-design/ant-design#18273]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/commit/63b33d4020a8cb0dda7ff80356b3ece6367e7ffb](https://github.com/ant-design/ant-design/commit/63b33d4020a8cb0dda7ff80356b3ece6367e7ffb)

### Steps to reproduce
如下三处代码在 [fix: unexpected changes of snapshots](https://github.com/ant-design/ant-design/commit/63b33d4020a8cb0dda7ff80356b3ece6367e7ffb) 提交时对于 React 的引用方式进行了改变，造成 Ts 验证出错。
[badge/ScrollNumber.tsx#L1](https://github.com/ant-design/ant-design/blob/master/components/badge/ScrollNumber.tsx#L1)
```tsx
// components/badge/ScrollNumber.tsx
import React, { createElement, Component } from 'react'
```
[breadcrumb/Breadcrumb.tsx#L1](https://github.com/ant-design/ant-design/blob/master/components/breadcrumb/Breadcrumb.tsx#L1)
```tsx
// components/breadcrumb/Breadcrumb.tsx
import React, { cloneElement } from 'react'
```
[tooltip/index.tsx#L1](https://github.com/ant-design/ant-design/blob/master/components/tooltip/index.tsx#L1)
```tsx
// components/tooltip/index.tsx
import React, { cloneElement } from 'react'
```

### What is expected?
tsx 验证正确

### What is actually happening?
```shell
node_modules/antd/lib/badge/ScrollNumber.d.ts(1,8): error TS1259: Module 
"/Users/yun/Code/projects/testBase/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts(1,8): error TS1259: Module '"/Users/yun/Code/projects/testBase/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
node_modules/antd/lib/tooltip/index.d.ts(1,8): error TS1259: Module '"/Users/yun/Code/projects/testBase/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag
```

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | macOS |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18259 应该是同一个问题，来个 PR 吧。

cc @orzyyyy

**Comment by xiaoyu2er** [comment]
tsconfig.json

```json
{
  "compilerOptions": {
    "esModuleInterop": true,
  }
}

```
