### ISSUE TITLE
wish Tabs will able to change  background of ant-tabs-tab-active

### ISSUE THREAD

**Issue by stephanieDL** [ant-design/ant-design#18286]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When we active a tab, we need high light the background of that bar, but .ant-tabs.ant-tabs-card .ant-tabs-card-bar .ant-tabs-tab-active is not able to change the background

### What does the proposed API look like?
wish we will able to change the .ant-tabs.ant-tabs-card .ant-tabs-card-bar .ant-tabs-tab-active background color

**Comment by afc163** [comment]
https://ant.design/docs/react/customize-theme-cn

**Comment by keithort** [comment]
Look at the available options for your config-overrides.js file here: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L488

**Comment by stephanieDL** [comment]
> https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L488

got it, thank you
