### ISSUE TITLE
Ant Design Pro website too slow taking over a minute to render

### ISSUE THREAD

**Issue by bfreis** [ant-design/ant-design#18281]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://bfreis-internal-us-east-1.s3.amazonaws.com/public/ant-design-slow.mov](https://bfreis-internal-us-east-1.s3.amazonaws.com/public/ant-design-slow.mov)

### Steps to reproduce
Open the https://pro.ant.design/ website on Firefox, and grab a cup of coffee.

### What is expected?
The website to load in a reasonable amount of time

### What is actually happening?
The website is taking well over 1 minute just to render the initial view, and I gave up waiting

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | n/a |
| System | Mac OS 10.14.6 |
| Browser | Firefox 68.0.1 |

---
Powerful mac mini 2018 (12 cores, 64GB ram, Radeon Vega 56 eGPU) under almost no load. With Chrome the page opens relatively fast. Please see video on the link.

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design-pro/issues/5041
