### ISSUE TITLE
getPopupContainer of <Menu> does not working

### ISSUE THREAD

**Issue by aprilandjan** [ant-design/ant-design#18288]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-971zo)

### Steps to reproduce
Add custom `getPopupContainer` method for `<menu>` components. just like `<select>` or any other. 

### What is expected?
The custom `getPopupContainer` method is called as expected, the alert() in this method is showed.

### What is actually happening?
The custom `getPopupContainer` method is called not called at all

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.23 |
| System | mac ox |
| Browser | chrome 73 |

**Comment by zombieJ** [comment]
你的 `getPopupContainer` 应该设置在 Dropdown 上面，而不是 Menu 上。

**Comment by shamseer-ahammed** [comment]
+1
