### ISSUE TITLE
add `style?: React.CSSProperties` to `CheckableTagProps`

### ISSUE THREAD

**Issue by escapiststupor** [ant-design/ant-design#18299]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Since you are spreading the `restProps` [here](https://github.com/ant-design/ant-design/blob/master/components/tag/CheckableTag.tsx#L33) could you add `style?: React.CSSProperties` to `CheckableTagProps` so we can pass in a style object?

### What does the proposed API look like?
```
export interface CheckableTagProps {
  prefixCls?: string;
  style?: React.CSSProperties;
  className?: string;
  checked: boolean;
  onChange?: (checked: boolean) => void;
}

```

**Comment by escapiststupor** [comment]
Sure I can do it. Should this go to `feature` or `master`? Not sure if this classifies as bug or new feature...

**Comment by afc163** [comment]
master I believe.
