### ISSUE TITLE
table: scroll 与嵌套表格expandedRowRender 目前不能同时使用，未来会可以同时使用吗

### ISSUE THREAD

**Issue by zlyyyy** [ant-design/ant-design#18297]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
issue内看了下，这个功能业务中还是很常见的，这么久了没看到有修复同时使用产生的问题

### What does the proposed API look like?
希望可以解决这个问题，antd还是很多人喜欢的，谢谢

**Comment by afc163** [comment]
这个主要是交互问题，这两种功能设计上没法解决，不建议同时用。
