### ISSUE TITLE
table固定列和rowSelection问题

### ISSUE THREAD

**Issue by kurten** [ant-design/ant-design#1829]
![ttt](https://cloud.githubusercontent.com/assets/589831/15493013/a2cd4672-2146-11e6-81b9-61bf4e6be3ab.png)

表格如果有rowSelection，同时使用column fixed left，会导致rowSelection的check box被覆盖

@afc163 

- antd 版本: 1.0.0
- 操作系统及其版本：fedora 21
- 浏览器及其版本: chrome 47.0.2526.106 (64-bit)

**Comment by RaoHai** [comment]
@afc163 table 在有列 fixed left 时，自动把 rowSelection 的 checkbox 也 fixed 在最左边如何？

**Comment by afc163** [comment]
嗯，左边和中间的都要有，右边的不需要，昨天改了一个和 rowExpandIcon 配合的问题很类似。

https://github.com/ant-design/ant-design/issues/1819

**Comment by afc163** [comment]
另外，有不对齐的问题。在 fixed 的时候，还是要限定列高度。

https://github.com/react-component/table/blob/192e41e1b15afd24462f029c44cd3ea15d5391c1/assets/index.less#L17-L21

**Comment by RaoHai** [comment]
这个 case 里，在有列 fixed 在左边的时候，直接把 `SelectionColumn`  也 fixed left 就能解决。
