### ISSUE TITLE
Table 表头分组在宽度缩小到一定程度会错位

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#18294]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-grouping-columns](https://ant.design/components/table-cn/#components-table-demo-grouping-columns)

### Steps to reproduce
缩小窗口宽度， 表头与下面的内容错位
![image](https://user-images.githubusercontent.com/22299421/63081711-e4f7c500-bf76-11e9-81fe-3e2187637b16.png)

### What is expected?
表头与下面的内容不错位

### What is actually happening?
表头与下面的内容错位

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
```diff
-   scroll={{ x: '130%', y: 240 }}
+  scroll={{ x: 'max-content', y: 240 }}
```

即可。
