### ISSUE TITLE
message.error 不弹出效果

### ISSUE THREAD

**Issue by mar105** [ant-design/ant-design#18292]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mar105/aoyoxFront.git](https://github.com/mar105/aoyoxFront.git)

### Steps to reproduce
启动后 输入input 调用了 message.error 不展示 我都把该用最新的用上最新的了，还是不行

### What is expected?
启动后 输入input 调用了 message.error 展示

### What is actually happening?
启动后 输入input 调用了 message.error 不展示

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | mac |
| Browser | google |

**Comment by zombieJ** [comment]
麻烦提供一个精简的重现。

**Comment by mar105** [comment]
发现用你们的模板是可以展示，我就把我的代码一一还原到你们的例子上，发现还能展示就是在最下面，因为我的页面一直是调试状态，根本就没有关注是在最下面内容，我用的是dva最新版，发现确实是这样，以前用的dva 2.0之前没有这样。 找到总是所在
不过最新版dva（）=>import方式用不了。
