### ISSUE TITLE
月份区间控件切换年份后默认值还继续高亮

### ISSUE THREAD

**Issue by Somnus001** [ant-design/ant-design#18296]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pny08802m)

### Steps to reproduce
在月份区间控件有默认值的情况下，单击控件弹出时间面板，切换年度标签，此时对应的月份仍然高亮显示

### What is expected?
切换年度标签后，默认的月份不要高亮显示；只有当年度标签显示的值与月份区间控件显示值相同时该月份才高亮显示 

### What is actually happening?
无论年度标签怎么切换，默认的月份始终高亮显示

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.3 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
已经在 v4 中解决。
