### ISSUE TITLE
Add the possibility to choose the type of the link in a rich-text tool

### ISSUE THREAD

**Issue by SKaistrenko** [ant-design/ant-design#18302]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When content editors use the tool, it might be to complex for them to type in raw HTML like <a href="blah" target="_blank">foo</a>. Improves user-friendliness. 

### What does the proposed API look like?
Provide additional input when a user chooses to add a link, allowing to set the link to be external.

**Comment by SKaistrenko** [comment]
Also, we are currently on Angular 7

**Comment by afc163** [comment]
I don't it is related to antd, maybe you are looking for https://github.com/NG-ZORRO/ng-zorro-antd/issues?
