### ISSUE TITLE
table 合并单元格问题

### ISSUE THREAD

**Issue by zlyyyy** [ant-design/ant-design#18308]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
重现需求https://codesandbox.io/embed/zealous-gates-yojw8
第二行的rowSpan我设为3时，第一行的rowSpan支持跟第二行的合并嘛，目前实际效果是只有两个的，想问下支不支持这么使用

### What does the proposed API look like?
rowSpan可以合并上一行的

**Comment by afc163** [comment]
rowSpan 是向下合并的，这是 table 原生组件的逻辑，目前貌似没有办法向上合并。

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/507615/63154125-8c8df980-c042-11e9-90c7-013e2b0f5e4b.png">

**Comment by zlyyyy** [comment]
@afc163 好吧谢谢，table支持最后列插入一个自定义div吗

**Comment by zlyyyy** [comment]
![image](https://user-images.githubusercontent.com/22760932/63155303-e1cb0a80-c044-11e9-88fd-c36e63209dd0.png)
就像这种，想着如果table支持的话，高亮当前的元素对应高亮此框效果会更好点

**Comment by lemovel** [comment]
![image](https://user-images.githubusercontent.com/26155101/88248816-0f98e480-ccd5-11ea-9675-9d84b9b41f5e.png)
借楼，请问一下，分组表头不是最后一行，合并行会出现这个错位的问题，该怎么解决呢

**Comment by yoyo837** [comment]
应该是你自己的问题，提供复现开个新问题吧
