### ISSUE TITLE
Regression in 3.21.4 generates tons of compilation errors

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#18301]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://none.com](http://none.com)

### Steps to reproduce
run `tsc` on codebase that uses antd

### What is expected?
Compilation should work without errors. (like it did in 3.21.2)

### What is actually happening?
Getting tons of errors like this while compiling

```

node_modules/antd/lib/badge/ScrollNumber.d.ts:1:8 - error TS1259: Module '"D:/code/dashboard/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import React, { Component } from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:55:1
    55 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts:1:8 - error TS1259: Module '"D:/code/dashboard/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react';
```

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome 76 |

---
This doesnt happen in 3.21.2. Regression in 3.21.4

**Comment by ddzy** [comment]
**Same issue**

## Current feature

- error message

```ts
d:/frontend_related/practices/GitHubGoods/public/ts-web-diary/node_modules/antd/lib/badge/ScrollNumber.d.ts
(1,8): Module '"d:/frontend_related/practices/GitHubGoods/public/ts-web-diary/node_modules/@types/react/index"' has no default export.
```

- error code

```ts
// tslint:disable-next-line:export-just-namespace
export = React;
export as namespace React;
```

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/18282
