### ISSUE TITLE
Modal组件是否考虑和Modal.method()一样支持自定义关闭icon？

### ISSUE THREAD

**Issue by gaoac** [ant-design/ant-design#18307]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不同项目可能会设计不同的关闭图标，支持自定义是个很重要的需求

### What does the proposed API look like?
icon= string|ReactNode

**Comment by afc163** [comment]
Modal 组件是完全自定义内容的，不存在 icon 这个属性。

**Comment by gaoac** [comment]
@afc163 这里的icon指的是右上角关闭图标,并不是指Modal内容区

**Comment by gaoac** [comment]
@afc163 目前Modal只支持是否显示右上角的关闭按钮的closable属性，不支持自定义（方法调用支持）
