### ISSUE TITLE
RangePicker默认值失效

### ISSUE THREAD

**Issue by durongzhang** [ant-design/ant-design#1830]
## 描述
RangePicker日期选择方式下，设置了defaultValue，但在展开的日历上不展现出来,返回后也被置空了。
###### 触发前：
![image](https://cloud.githubusercontent.com/assets/15725537/15496212/abbb6068-21c6-11e6-868e-189651ef30dc.png)
###### 触发后：
![image](https://cloud.githubusercontent.com/assets/15725537/15496215/b0baad8a-21c6-11e6-89f4-169604394c10.png)
![image](https://cloud.githubusercontent.com/assets/15725537/15496302/094bc196-21c7-11e6-9b5f-58277c025083.png)

## 本地环境信息

- antd 版本:1.1.0
- 操作系统及其版本：win
- 浏览器及其版本:all

**Comment by benjycui** [comment]
本地测试正常。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001
