### ISSUE TITLE
TreeSelect

### ISSUE THREAD

**Issue by jiangdexiao** [ant-design/ant-design#18303]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vz6lj)

### Steps to reproduce
TreeSelect 当showSearch 设置为false 时候  点击控件 报错 focus  是 undefined
_this.inputRef.current.focus();

### What is expected?
当关闭搜索框功能不报错

### What is actually happening?
关闭搜索框功能报错

| Environment | Info |
|---|---|
| antd | 3.11.0 |
| React | 16.2.0 |
| System | win10 |
| Browser | chrome72.0.3626.81 |

**Comment by afc163** [comment]
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/507615/63139850-59337680-c012-11e9-9265-84232be95b4b.png">

Your codesandbox is not reproducible.

**Comment by jiangdexiao** [comment]
> Hello @jiangdexiao. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @jiangdexiao, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

我创建了codesandbox了，https://codesandbox.io/s/antd-reproduction-template-vz6lj
