### ISSUE TITLE
Progress change text color not possible

### ISSUE THREAD

**Issue by fnoah** [ant-design/ant-design#18312]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-pjrok)

### Steps to reproduce
Open CodeSandbox and look at the color of the "40%" text.

### What is expected?
The color of the text should be red.

### What is actually happening?
The color of the text is unchanged. Hence, it remains black.

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | Ubuntu 18.04 |
| Browser | Chrome 76.0.3809.100 |

---
As you can see, when using CSS to style the text on another Ant Design element (button) red, it works flawlessly. However, the same CSS styling does not work on the Progress element.

**Comment by afc163** [comment]
Try `className`: https://codesandbox.io/s/antd-reproduction-template-pokm2
