### ISSUE TITLE
form 获取 日历控件跟时间控件值的问题

### ISSUE THREAD

**Issue by xfcf1** [ant-design/ant-design#1831]
能不能getFieldsValue的时候获取日历控件的值为string（2020-02-02）这种，而不是一个Date()对象？
就想jquery的datepicker 那种。

<br/><br/><br/><br/><br/><br/>
<hr/>
下面的是我的情况，没时间看请无视。。。

当用getFieldsValue或者validateFieldsAndScroll获取 日历和时间控件的时候得到的是一个 Date 的obj，通过JSON.stringify转了以后传到后端交互后，再拿回来的时候是一个 字符串，这个时候setFieldsValue到对应的日历控件里面。目前看来是完美的！！！值也会显示正确。

但是如果这个日历控件设置了required属性，当再次点这个form提交的话就会报错，报错语句
```js
if (value) {
    _rule2["default"].range(rule, **value.getTime()**, source, errors, options);
}
```

value.getTime() 会报错，  因为setFieldsValue是字符串不是Date对象。

当然有人会说  自己setFieldsValue之前new Date（）不就行了吗？
的确如此！！！

但是我要是不知道json里面那个是我存的日历的value， 那我要怎么办？

**Comment by longang520** [comment]
我也建议控件获取的时间为 “yyyy-MM-dd HH:mm:ss” 这种。前后台交互省下不少麻烦。

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/1515

只要让 DatePicker 支持 String 值即可。

> 但是我要是不知道json里面那个是我存的日历的value， 那我要怎么办？

这个你不可能不知道的，因为 JSON 里面的值和表单域的 `id` 是一一对应的，看源码即可。

**Comment by afc163** [comment]
`onChange(value, dateString)`

**Comment by longang520** [comment]
validateFields 返回的是时间类型。

**Comment by benjycui** [comment]
https://github.com/react-component/form#optiongetvaluefromevent

用 `getValueFromEvent` 处理下，就可以把第二个参数作为 `value` 存进 `Form` 了。

**Comment by afc163** [comment]
@benjycui 👍
