### ISSUE TITLE
Prop style is getting duplicated on Table

### ISSUE THREAD

**Issue by SrAnthony** [ant-design/ant-design#18315]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-2slps)

### Steps to reproduce
Use the prop style on the Table component

### What is expected?
Style to be applied once on the table wrapper

### What is actually happening?
Style is getting applied twice

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9.0 |
| System | Linux |
| Browser | Chrome 76.0.3809.100 |

---
This bug started on version 3.21.3

**Comment by MrHeer** [comment]
## I found the reason that style applied twice.
#### First time:
https://github.com/ant-design/ant-design/blob/3bc3cf43f29584a90e93ad0cb29aa433a8555b42/components/table/Table.tsx#L1318
#### Second time:
https://github.com/react-component/table/blob/5b1ee3eda6335b409a3ad61fddeef50e7e8b33e5/src/Table.js#L516
#### I want to solve it as follows:
[ant-design/components/table/Table.tsx#L1318](https://github.com/ant-design/ant-design/blob/3bc3cf43f29584a90e93ad0cb29aa433a8555b42/components/table/Table.tsx#L1318)
```diff
-  <div className={classNames(`${prefixCls}-wrapper`, className)} style={style}>
+  <div className={classNames(`${prefixCls}-wrapper`, className)}>
```
