### ISSUE TITLE
[Modal] body.scroll = hidden does not work in ios

### ISSUE THREAD

**Issue by HsuTing** [ant-design/ant-design#18318]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal/](https://ant.design/components/modal/)

### Steps to reproduce
1. Open this page in ios.
2. Click "Open Modal".

### What is expected?
After opening Modal, the page under Modal should not be scrolled.

### What is actually happening?
The page under Modal will be scrolled.

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.9 |
| System | Mac os 10.14.4 |
| Browser | ios |

**Comment by jljsj33** [comment]
modal 不支持在 ios 下锁定滚动，，目前只有 drawer 会锁定滚动。。。

如果要支持，，把 drawer 里的那块锁定滚动抽到 util 里做调用就行了，，不过好像安卓下有问题。。

**Comment by HsuTing** [comment]
Will this problem be fixed?

**Comment by jljsj33** [comment]
不影响使用，，后续有时间了再改进。。。
