### ISSUE TITLE
Request for a prop in antd Link to open path in new tab or new window.

### ISSUE THREAD

**Issue by archita-sarda** [ant-design/ant-design#18310]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Like the <a> tag has a target attribute to specify where to open the linked document, similarly could a prop be introduced for this use case?

### What does the proposed API look like?
a prop to determine the target window

**Comment by afc163** [comment]
Try target: `<a href="" target="_blank" />`

**Comment by archita-sarda** [comment]
I am using antd components anchor and link to create a hyperlink.

**Comment by afc163** [comment]
Could u send us a PR to add `target` prop to `Anchor.Link`?

**Comment by afc163** [comment]
> What does the proposed API look like?

You don't answer this question, cause me confused.

**Comment by DiamondYuan** [comment]
I am working on it.

**Comment by archita-sarda** [comment]
thank you for looking into this issue.
