### ISSUE TITLE
Progress当type='dashboard'时设置StrokeColor无效，文档最后一个example也失效了！！！

### ISSUE THREAD

**Issue by boomsi** [ant-design/ant-design#18319]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/progress-cn/](https://ant.design/components/progress-cn/)

### Steps to reproduce
使用Progress组件，设置type=dashboard，strokeColor={{'0%': '#108ee9', '100%': '#87d068',}}

### What is expected?
会呈现渐变的颜色

### What is actually happening?
无渐变效果，只会显示默认的蓝色和当百分之百时候显示的绿色

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.6 |
| System | uabntu18.04 |
| Browser | The newest chrome and Firefox |

---
文档（https://ant.design/components/progress-cn/）的最后一个example也失效了！！！

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/18284

@wendzhue

**Comment by wendzhue** [comment]
You problem will be fixed in #18284.
