### ISSUE TITLE
getPopupContainer works on TimePicker but not on DatePicker

### ISSUE THREAD

**Issue by Anne-Anq** [ant-design/ant-design#18316]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-wd6ig)

### Steps to reproduce
with the minimal implementation on sandbox, if you click on the time picker, you get an alert, hence the `getPopupContainer` is triggered, but if you click on the date picker you don't get the alert, hence it is not being called at all.

### What is expected?
getPopupContainer should be called also for date picker so that I could give it the function `triggerNode => triggerNode.parentNode`. And see the dates selection field even in a popup modal.

### What is actually happening?
Instead it is not triggered and I can't see the date fields  of my data picker when used in a modal. Although time picker works just fine

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.6.3 |
| System | windows 10 Pro version 1809 |
| Browser | chrome |

---
please let me know should you need any more info to de-bug

**Comment by afc163** [comment]
Should be `getCalendarContainer`

**Comment by Anne-Anq** [comment]
thanks
