### ISSUE TITLE
Drawer support bodyClass and maskClass

### ISSUE THREAD

**Issue by gabrieltong** [ant-design/ant-design#18321]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
in order to reuse less variables, need to assign less variable to less class, and can't pass less variable to bodyStyle and maskStyle

### What does the proposed API look like?
simple bodyClass props and maskProps, It's will be better to add more style class to other antd component

**Comment by afc163** [comment]
Try `className`.

**Comment by gabrieltong** [comment]
sorry, I'm a little confused.

There're 3 styles for `drawer`, `style', `bodyStyle`, 'maskStyle`, Is a single `className` suit for all 3 cases ?

**Comment by gabrieltong** [comment]
> Try `className`.

@afc163 can you help me . ?

**Comment by gabrieltong** [comment]
stupid fix

**Comment by afc163** [comment]
https://codesandbox.io/s/heuristic-hertz-3v29b
