### ISSUE TITLE
treeSelect通过onSelect方法来改变选择项时,在文本框中点击x号不能去除

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#1832]
![aaa](https://cloud.githubusercontent.com/assets/11780264/15496886/6aa792aa-21ca-11e6-9ce1-35da65474d8c.png)
![bug1](https://cloud.githubusercontent.com/assets/11780264/15496885/6aa6ff34-21ca-11e6-9758-55b788a40772.gif)

**Comment by RaoHai** [comment]
`onChange` 的回调里把 TreeSelect 的 value 改下。
