### ISSUE TITLE
引用国际化包报错

### ISSUE THREAD

**Issue by Greatwallycc** [ant-design/ant-design#18336]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-pyg3j)

### Steps to reproduce
import {ConfigProvider} from 'antd';
import zhCN from 'antd/es/locale/zh_CN';
<ConfigProvider locale={zhCN}></ConfigProvider>

### What is expected?
正常使用

### What is actually happening?
(node:99704) UnhandledPromiseRejectionWarning: D:\学习\React\EDS\node_modules\antd\es\locale\zh_CN.js:1
import Pagination from "rc-pagination/es/locale/zh_CN";
       ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Module._compile (D:\学习\React\EDS\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.newLoader [as .js] (D:\学习\React\EDS\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\学习\React\EDS\src\ssr/App.js:5:1)
(node:99704) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:99704) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.6 |
| System | windows |
| Browser | chrome 69.0.3497.81（正式版本） （32 位） |

---
ctrl 点击可以跳转，应该也不是babel编译的问题，其他的引用都是正常的

**Comment by Greatwallycc** [comment]
![image](https://user-images.githubusercontent.com/26137974/63236131-24702b00-c26f-11e9-9120-af4afe71a748.png)
已经写了例子了，是在我本地搭建脚手架时出现的这个问题，脚手架还没有搭完，所以没办法给你们在线的例子，但是我已经把报错部分的代码贴出来了。

**Comment by afc163** [comment]
没有重现没有办法排查问题耶

**Comment by Greatwallycc** [comment]
import zhCN from 'antd/lib/locale-provider/zh_CN';
我尝试了旧版本的写法，这样是可以的。。好奇怪

**Comment by TabrisK** [comment]
I also have this issue.
antd@3.21.4
react@16.9.0
MacOS 10.13.6
Chrome@76.0.3809.100

**Comment by TabrisK** [comment]
Change
```javascript
import zhCN from 'antd/es/locale/zh_CN';
```
to
```javascript
import zhCN from 'antd/lib/locale/zh_CN';
```
fix this problem.

**Comment by TabrisK** [comment]
The resource provided by the [document](https://ant.design/docs/react/i18n-cn) is wrong.

**Comment by ZekeXu** [comment]
Same error: 

`
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Pagination from 'rc-pagination/es/locale/zh_CN';
                                                                                                    ^^^^^^^^^^

    SyntaxError: Unexpected identifier

    > 1 | import zhCN from 'antd/es/locale-provider/zh_CN';
        | ^

`

thx @TabrisK , it works.

**Comment by weiQing88** [comment]
我的使用的是 next.js ,再开发的时候是没问题，但是一打包。就报错。
![image](https://user-images.githubusercontent.com/13113454/65665311-d02a4900-e06d-11e9-9eda-97b4c141505d.png)

**Comment by YinshawnRao** [comment]
同用nextjs，官网上的demo是引用的es目录的，要改成lib目录才是commonjs的形式。。

**Comment by ruizhang-chowbus** [comment]
import enUS from 'antd/lib/locale/en_US';

**Comment by ruizhang-chowbus** [comment]
import enUS from 'antd/lib/locale/en_US';

./node_modules/antd/lib/locale/ar_EG.d
 ts-loader will not compile .ts files in node_modules.
antd4.1.4
nextjs 9.3.5

**Comment by ruizhang-chowbus** [comment]
import enUS from 'antd/lib/locale/en_US';
./node_modules/antd/lib/locale/fr_FR.d.ts 2:8
Module parse failed: Unexpected token (2:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| import { Locale } from '../locale-provider';
> declare const localeValues: Locale;
| export default localeValues;

**Comment by Little-Phoenix** [comment]
jest 进行单元测试，总是提示SyntaxError Unexpected identifier， 找到这里终于发现 是本地化的包引用错了

**Comment by chiove** [comment]
改成import zhCN from 'antd/lib/locale/zh_CN'; 没有转成中文，但是不报错了。

**Comment by amaury-diallo** [comment]
> Change
> 
> ```js
> import zhCN from 'antd/es/locale/zh_CN';
> ```
> 
> to
> 
> ```js
> import zhCN from 'antd/lib/locale/zh_CN';
> ```
> 
> fix this problem.
> The resource provided by the [document](https://ant.design/docs/react/i18n-cn) is wrong.

This worked fine for me. Thanks @TabrisK

**Comment by xingqiwu55555** [comment]
> Change
> 
> ```js
> import zhCN from 'antd/es/locale/zh_CN';
> ```
> 
> to
> 
> ```js
> import zhCN from 'antd/lib/locale/zh_CN';
> ```
> 
> fix this problem. The resource provided by the [document](https://ant.design/docs/react/i18n-cn) is wrong.

这个修改还可以解决 jest 测试时的问题，太感谢
