### ISSUE TITLE
The document is incomplete for `Popover` component of props `popupAlign` and `popupClassName`

### ISSUE THREAD

**Issue by unmem** [ant-design/ant-design#18337]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/react-tutorial/blob/33d77c3794235148a778198e91d78a07033dbff6/src/component/NoticeIcon/index.js#L91-L94](https://github.com/ant-design/react-tutorial/blob/33d77c3794235148a778198e91d78a07033dbff6/src/component/NoticeIcon/index.js#L91-L94)

### Steps to reproduce
Poor documentation, bear it. https://ant.design/components/popover/

### What is expected?
i can't found any documentation about props with `popupClassName` and `popupAlign`.

### What is actually happening?
Please fill the documentation now

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.9.0 |
| System | Darwin |
| Browser | Chrome |

**Comment by afc163** [comment]
We don't encourage to use these props because it is advanced usage.

**Comment by unmem** [comment]
But you should write the documentation about the "advanced" usage, and let the user make the choice. btw, they are just some CSS work.
