### ISSUE TITLE
Cannot compile namespaces when the '--isolatedModules' flag is provided.

### ISSUE THREAD

**Issue by oldmannt** [ant-design/ant-design#18342]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/oldmannt/unit-rx](https://github.com/oldmannt/unit-rx)

### Steps to reproduce
https://ant.design/docs/react/use-with-create-react-app-cn
按照上面这个链接的步骤，
1. yarn add react-app-rewired customize-cra
2. yarn add babel-plugin-import
3. 编辑 config-overrides.js
```
const { override, fixBabelImports } = require('customize-cra');
module.exports = override(
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: 'true',
  }),
);

```
4. yarn start  
然后就出错了  

https://github.com/oldmannt/unit-rx 这个代码库可以重现  
把 isolatedModules 设为 false，编译时又会被自动设成 true  

### What is expected?
没有出错

### What is actually happening?
出错
TypeScript error in /Users/llin/Documents/projects/usnit-rx/config-overrides.js(1,1):
Cannot compile namespaces when the '--isolatedModules' flag is provided.  TS1208

  > 1 | const { override, fixBabelImports } = require('customize-cra');
      | ^
    2 | module.exports = override(
    3 |   fixBabelImports('import', {
    4 |     libraryName: 'antd',

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.8.6 |
| System | macOS 10.14.2 |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/oldmannt/unit-rx/pull/1
