### ISSUE TITLE
在部分macbook pro机型上，ant-design的table组件显示异常

### ISSUE THREAD

**Issue by withzhaoyu** [ant-design/ant-design#18349]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://user-images.githubusercontent.com/30406289/63256452-33280380-c2aa-11e9-8336-9e537a2e9bd5.png](https://user-images.githubusercontent.com/30406289/63256452-33280380-c2aa-11e9-8336-9e537a2e9bd5.png)

### Steps to reproduce
1、使用2015 mid款 macbook pro打开 https://ant-design.gitee.io/components/table-cn/#components-table-demo-fixed-columns-header
2、显示异常

### What is expected?
该版本macbook pro显示正常

### What is actually happening?
部分2015 mid款 macbook pro显示异常；

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.6.0 |
| System | macOS 10.14.6  集中出现在2015 mid款 macbook pro上 |
| Browser | chrome 76 ； safari  |

---
部分2015 mid款 macbook pro显示异常；
样本如下：
1、 2015 mid macbookpro 15inch  AMD 显卡  1台 显示正常；
2、2015 mid macbookpro 15inch NVIDIA显卡  3台  显示异常；
3、2015 mid macbookpro 15inch  intel集成显卡 2台 显示异常；
4、2014 mid macbookpro 15inch intel集成显卡  1台 显示正常；
5、2017 iMac Radeon 27inch 1台 显示正常；

**Comment by yoyo837** [comment]
应该硬件无关吧，最多系统版本和浏览器版本差异

**Comment by withzhaoyu** [comment]
> 应该硬件无关吧，最多系统版本和浏览器版本差异

我看了版本和浏览器基本一致。BTW，safari上也同样有这问题啊！

**Comment by afc163** [comment]
没看出有什么异常。

**Comment by withzhaoyu** [comment]
> 没看出有什么异常。麻烦定义一下正常和异常是什么表现

抱歉，我描述不准确。是滚动条区域展示不一致。。。
今天早上问了几个朋友他们的mac有没有复现。。
最终经提醒是使用了非apple官方鼠标的会有滚动条不会自动隐藏的问题。。
那我这边关掉这个issue了。

**Comment by afc163** [comment]
<img width="352" alt="image" src="https://user-images.githubusercontent.com/507615/63315674-ae3af980-c33e-11e9-9214-8dca59329016.png">

这里也可以设置的。

**Comment by withzhaoyu** [comment]
> <img alt="image" width="352" src="https://user-images.githubusercontent.com/507615/63315674-ae3af980-c33e-11e9-9214-8dca59329016.png">
> 
> 这里也可以设置的。

啊！谢谢，谢谢！好丢人哈哈
