### ISSUE TITLE
Select tabPosition="left" 时 size=default 或者small 大小没有任何变化

### ISSUE THREAD

**Issue by pacific0437** [ant-design/ant-design#1834]
Tabs tabPosition="left" 时 size=default 或者small 没有任何变化
当tabPosition是top的时候  能看出两种差异。

升级到1.1.0 还有这个问题

**Comment by RaoHai** [comment]
是 Select 还是 Tabs…… Select 貌似没有 tabPosition 这个属性吧？

**Comment by pacific0437** [comment]
@RaoHai 是的  是tabs  我写错啦

**Comment by RaoHai** [comment]
竖状的线性标签页，

大号 tab 中文字字号 14px，行高 21px；

小号 tab 中文字字号 12px，行高 18px；

与设计稿一致。

**Comment by pacific0437** [comment]
@RaoHai  好的 已找到原因，被团队其他人写的样式覆盖了。
