### ISSUE TITLE
Class constructor FileManager cannot be invoked without 'new'

### ISSUE THREAD

**Issue by Meow-z** [ant-design/ant-design#18343]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
编译报错
./node_modules/antd/es/tag/style/index.less

Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)

### What is expected?
成功编译

### What is actually happening?
./node_modules/antd/es/tag/style/index.less

Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.2 |
| System | macOs Mojave 10.14.5 |
| Browser | 任何 |

**Comment by Meow-z** [comment]
锁定之前版本 3.16.0，不会报错。

**Comment by afc163** [comment]
https://github.com/less/less.js/issues/3414

**Comment by montanaflynn** [comment]
What's this fix for this? All our builds stopped working, here's the error:

```
./node_modules/antd/es/style/index.less
Module build failed: 

Class constructor FileManager cannot be invoked without 'new'
      in undefined (line undefined, column undefined)
```

**Comment by afc163** [comment]
It is a bug of less, not antd's, please trace less/less.js#3414 for further fix.

**Comment by montanaflynn** [comment]
@afc163 they suggest locking the less version, which would be done in antd's package.json.

**Comment by afc163** [comment]
antd didn't depend less.

**Comment by montanaflynn** [comment]
@afc163 less-loader then, we fixed it by adding:

```
  "devDependencies": {
    "less-loader": "^5.0.0"
  }
```

**Comment by afc163** [comment]
`devDependencies` won't affect your project.

**Comment by montanaflynn** [comment]
@afc163 it did, and it fixed the issue for us. Literally that's all we added and the problem went away.
