### ISSUE TITLE
Vertical Dot Steps Tail No Longer Aligning

### ISSUE THREAD

**Issue by davidpanzarella** [ant-design/ant-design#18354]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-k5dlc)

### Steps to reproduce
Create a vertical dot stepper

### What is expected?
Alignment of tail

### What is actually happening?
Misalignment of tail

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | Latest |
| System | Unix |
| Browser | Any |

---
Easy - Simply remove left and padding:

.ant-steps-vertical > .ant-steps-item > .ant-steps-item-container > .ant-steps-item-tail {
  position: absolute;
  top: 0;
  /* left: 16px; */
  width: 1px;
  height: 100%;
  /* padding: 38px 0 6px; */
}`

**Comment by afc163** [comment]
broken in https://github.com/ant-design/ant-design/pull/17994

**Comment by davidpanzarella** [comment]
Thanks for addressing this issue so quickly!

Also, just as a recommendation, increasing class specificity like this will continue to cause these sort of bugs. I would recommend starting to put modifier classes on the component's outer most container. Ex: `.ant-steps--is-vertical` and then just set the necessary modifications under that class's state. Eg. `.ant-steps--is-vertical .ant-steps-tail` 

I know this seems trivial with this example, but as an avid Ant Design user, I run across these all the time where the specificity is so high I have to either include the same amount of class specificity or use `!important`.

A better example to see what I mean would be looking at Badge state: https://github.com/ant-design/ant-design/blob/65eb713fe897f65bbf187e215c664e5f9b468252/components/badge/style/index.less#L74

Notice that `processing` is 4 levels deep. You could solve this with only 2 classes by putting it at the top of the component's container as `ant-badge--processing` or something similar and accomplish the same outcome with less specificity.
