### ISSUE TITLE
Drawer组件，渲染在指定dom里并visible={true}之后，路由切换，会在渲染的dom下残留一个空div片段。

### ISSUE THREAD

**Issue by 303394539** [ant-design/ant-design#18358]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/drawer/blob/master/src/DrawerWrapper.tsx](https://github.com/react-component/drawer/blob/master/src/DrawerWrapper.tsx)

### Steps to reproduce
Drawer组件，渲染在指定dom里并visible={true}之后，路由切换，会在渲染的dom下残留一个空div片段。

### What is expected?
路由切换能不残留div节点，或者是提供和Modal.destroyAll();一样的Drawer路由监听清理方法。

### What is actually happening?
路由切换残留空div节点

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.9.0 |
| System | macOS |
| Browser | Google Chrome |

---
猜测是Drawer使用rc-util/Portal.js通过ReactDOM.createPortal外部包裹了一个div，但是经过路由切换没有清除掉这个div，而且没有给予路由监听清理的方法。导致残余垃圾节点，并造成某些css匹配到残留div形成bug

**Comment by jljsj33** [comment]
搞个重现看看？？

**Comment by 303394539** [comment]
https://codesandbox.io/embed/antd-reproduction-template-xy7pq
