### ISSUE TITLE
Breadcrumb to support data-* and aria-* attributes

### ISSUE THREAD

**Issue by samit4me** [ant-design/ant-design#18350]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allow developer to store data against the component, which could be useful in many scenarios. My immediate use case is so I can add data-testid for testing purposes.

As shown in this example Breadcrumb.Item supports data-* and aria-* but Breadcrumb does not https://codesandbox.io/embed/adoring-sea-r5rej

### What does the proposed API look like?
Propose to spread remaining props much like what has been done in Breadcrumb.Item, see https://github.com/ant-design/ant-design/blob/c5344bde529a2f2ec814f46e7ec5d249eac8d608/components/breadcrumb/BreadcrumbItem.tsx#L30

Happy to open PR if feature allowed.

**Comment by shaodahong** [comment]
closed via #18941
