### ISSUE TITLE
Select Option在使用Popover时候，点击Popover也会触发Option选中，能不能给Popover加一个阻止冒泡事件的属性

### ISSUE THREAD

**Issue by gitHber** [ant-design/ant-design#18355]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Select Option在使用Popover时候，点击Popover也会触发Option选中，能不能给Popover加一个阻止冒泡事件的属性

### What does the proposed API look like?
stopPropagation: Boolean
[codesanbox](https://codesandbox.io/s/yy3em)

**Comment by afc163** [comment]
https://codesandbox.io/s/elastic-water-i0yvb
