### ISSUE TITLE
Select的dropdownRender无法添加事件

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#18357]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/modest-taussig-0b081)

### Steps to reproduce
给dropdownRender中的div添加click事件，事件不执行

### What is expected?
事件执行

### What is actually happening?
事件不执行

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | latest |
| System | windows10 |
| Browser | chrome74 |

**Comment by afc163** [comment]
Duplicate of #13448
