### ISSUE TITLE
andt tree defaultExpandedKeys,defaultCheckedKeys Sometimes it doesn't work

### ISSUE THREAD

**Issue by mynameismaosheng** [ant-design/ant-design#18363]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-gs4e9)

### Steps to reproduce
The code in the link is simple, just set the correct value in the callback and it will show

### What is expected?
defaultExpandedKeys,defaultCheckedKeys   Getting the value in the callback will work fine

### What is actually happening?
defaultExpandedKeys,defaultCheckedKeys it doesn't work

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.6 |
| System | win10 |
| Browser | 谷歌 76.0.3809.100 |

---
都是翻译出来的~   不知道看不看得懂这意思...

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
