### ISSUE TITLE
this.props.form.getFieldsValue的疑问

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#1836]
在Form的典型表单的例子中`
getFieldsValue 无法取得 id="userName 大眼萌 minion  值 ，同样setFieldsValue 也无法设置userName值，这种情况下非编辑内容只能用disabled属性处理吗？这样界面不美观，是否有其他方法？

`    <FormItem
          {...formItemLayout}
          label="用户名：">
          <p className="ant-form-text" id="userName" name="userName">大眼萌 minion</p>
        </FormItem>`

**Comment by benjycui** [comment]
用 `state`：

```jsx
<FormItem {...formItemLayout} label="用户名：">
  <p className="ant-form-text" id="userName" name="userName">{this.state.userName}</p> 
</FormItem>
```

**Comment by whx76** [comment]
用 state是可以，但这样既要用etFieldsValue还要用state，显示提交查询数据时复杂化了
