### ISSUE TITLE
Antd@2.12.4   react-router-dom@4.0.0 开发时Breadcrumb组件时，是否可设置参数？

### ISSUE THREAD

**Issue by tengzj** [ant-design/ant-design#18364]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

In project development, we need to set parameters in routing, but also in breadcrumbs, we need to set parameters in ice display. In antd@2.12.4 react-router@2.x version, this requirement can be met, but when we use react-router@4.0.0 development, breadcrumbs are configured as map, so we do not know. How can Tao set parameters for breadcrumb components and display them, hoping to help

### What does the proposed API look like?
我期望可以通过配置直接可以展示，或者官方能够提供breadcrumb组件在react-router4.x版本能提供一个示例，就像react-router2.x / react-router3.x版本那样，谢谢

**Comment by afc163** [comment]
看看 https://2x.ant.design/components/breadcrumb-cn/#components-breadcrumb-demo-router-4
