### ISSUE TITLE
Upload component's beforeUpload not working properly

### ISSUE THREAD

**Issue by Kishan033** [ant-design/ant-design#18362]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exciting-engelbart-j0om9?fontsize=14)

### Steps to reproduce
Just upload the file more than 1 MB.

### What is expected?
The file shouldn't be added in the list if I return false from beforeUpload function.

### What is actually happening?
It's added in the list.

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.9.0 |
| System | Ubuntu 16.04 |
| Browser | Any |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15561#issuecomment-481186693
