### ISSUE TITLE
descriptions 组件当 一行descriptions.Item的span的总数大于descriptions的column时，不会自动换行

### ISSUE THREAD

**Issue by zhutiancheng2** [ant-design/ant-design#18361]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-yww4s)

### Steps to reproduce
const { Descriptions } = antd;

ReactDOM.render(
  <Descriptions title="User Info">
    <Descriptions.Item label="UserName" column={3}>Zhou Maomao</Descriptions.Item>
    <Descriptions.Item label="Telephone">1810000000</Descriptions.Item>
    <Descriptions.Item label="Live" span={10}>Hangzhou, Zhejiang</Descriptions.Item>
    <Descriptions.Item label="Remark">empty</Descriptions.Item>
    <Descriptions.Item label="Address">
      No. 18, Wantang Road, Xihu District, Hangzhou, Zhejiang, China
    </Descriptions.Item>
  </Descriptions>,
  mountNode,
);

### What is expected?
descriptions 组件当 一行descriptions.Item的span的总数大于descriptions的column时，能换到下一行

### What is actually happening?
descriptions 组件当 一行descriptions.Item的span的总数大于descriptions的column时，不会自动换行

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8 |
| System | windows10 |
| Browser | chrome |

**Comment by chenshuai2144** [comment]
descriptions 和 table 的表现相同。
你可以设置 span 来让上一个占满一行来完成换行的功能

**Comment by zombieJ** [comment]
要善于查看错误信息：

<img width="719" alt="屏幕快照 2019-08-30 下午2 49 09" src="https://user-images.githubusercontent.com/5378891/63999195-7e0d0b00-cb35-11e9-9b74-32a200514457.png">
