### ISSUE TITLE
Highlight matched text in bold using Autocomplete #5243 reopen

### ISSUE THREAD

**Issue by idoo** [ant-design/ant-design#18368]
I have searched this issue — and found it's duplicate of https://github.com/ant-design/ant-design/issues/5243 , however, I could not comment that anymore 

### Reproduction link
[https://ant.design/components/auto-complete/#components-auto-complete-demo-uncertain-category](https://ant.design/components/auto-complete/#components-auto-complete-demo-uncertain-category)

### Steps to reproduce
Created AutoComplete with matched text

### What is expected?
Matched text highlighted

### What is actually happening?
Currently we able to create a custom render option, however, there are no passed `query` pattern to highlight matched text 

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | do not highlight matched text |
| System | any |
| Browser | any |

---
Any ideas about how to implement it?

**Comment by PillowSkyscraper** [comment]
I recently solved this by saving the query to state in onSearch. Code pen for Select; Autocomplete works similarly: [https://codepen.io/PillowSkyscraper/pen/dybOggQ](url)

**Comment by idoo** [comment]
@PillowSkyscraper it is a nice idea, however for me looks like it should be inside autocompleted by default

**Comment by afc163** [comment]
@PillowSkyscraper 👍
