### ISSUE TITLE
v3.22.0-TextArea 受控模式并使用maxRows，输入时滚动条闪烁

### ISSUE THREAD

**Issue by lich-yoo** [ant-design/ant-design#18366]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-fast-u53et)

### Steps to reproduce
必现

### What is expected?
输入时不闪动滚动条

### What is actually happening?
输入时闪动滚动条

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.9.0 |
| System | v3.22.0-TextArea 受控模式并使用maxRows，输入时滚动条闪烁 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/upbeat-fast-u53et 无法重现。

![CleanShot 2019-08-20 at 17 02 54](https://user-images.githubusercontent.com/507615/63333678-659a3500-c36c-11e9-9876-44e4f5e3e103.gif)

**Comment by lich-yoo** [comment]
> https://codesandbox.io/s/upbeat-fast-u53et 无法重现。
> 
> ![CleanShot 2019-08-20 at 17 02 54](https://user-images.githubusercontent.com/507615/63333678-659a3500-c36c-11e9-9876-44e4f5e3e103.gif)

不好意思刚才调试 把左侧Dependencies antd 版本改成 3.21.0 了，就不复现了，可能我改的时候 你正好使用。
改成 3.22.0 是复现的。
![1](https://user-images.githubusercontent.com/18572962/63334535-3684c300-c36e-11e9-981f-3514b0c40bf8.gif)

**Comment by afc163** [comment]
这个 3.22.0 的例子 https://codesandbox.io/s/upbeat-fast-u53et 依然无法复现。

**Comment by afc163** [comment]
- [x] 打开滚动条。
- [x] 输入字符。

输入过程中滚动条小时，结束后出现，导致连续输入的闪动。

@zombieJ

**Comment by plainnany** [comment]
这个问题在v3.22.0依旧存在，虽然更新日志有提到解决了这个问题，
![image](https://user-images.githubusercontent.com/27320655/63431841-61e0de00-c452-11e9-80e1-846688ddd307.png)
