### ISSUE TITLE
allow opening DatePicker without need for input box

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#18376]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A lot of times you want to show a datepicker as a result of a button click or a dropdown menu click.
For example, depending on UI, one may have a button or a dropdown like 'Custom Time Range' clicking on which the DatePicker should be shown.

In these cases, showing a separate dropdown box doesnt make sense

### What does the proposed API look like?
DatePicker might have a `asPopup` boolean field which renders the datepicker as a dialog without need for input to trigger it.

**Comment by afc163** [comment]
https://codesandbox.io/s/blazing-resonance-eegnq

**Comment by pdeva** [comment]
It would be great if there was an example of this in the documentation

**Comment by Phengsouphal** [comment]
> https://codesandbox.io/s/blazing-resonance-eegnq

but when we click on the button, it did not hide the datepicker. can you make it toggle hide and show when click the button.

**Comment by osamajavaid** [comment]
thanks for this solution, it would be more better if you guys mention this in documentation

**Comment by bombillazo** [comment]
I agree, this is really needed in the documentation, it is not an obscured use case...

**Comment by arjunghimire** [comment]
> I agree, this is really needed in the documentation, it is not an obscured use case...
> 
> Code for those who cant access the sandbox
> 
> ```ts
> import React, { useState } from "react";
> import ReactDOM from "react-dom";
> import "antd/dist/antd.css";
> import "./index.css";
> import { DatePicker } from "antd";
> 
> const YourDatePicker = () => {
>   const [open, setOpen] = useState(false);
>   return (
>     <span>
>       <DatePicker
>         open={open}
>         style={{ visibility: "hidden", width: 0 }}
>         onOpenChange={open => setOpen(open)}
>       />
>       <button onClick={() => setOpen(!open)}>Open DatePicker</button>
>     </span>
>   );
> };
> 
> ReactDOM.render(<YourDatePicker />, document.getElementById("container"));
> ```

Property 'open' does not exist on new version of calendar

**Comment by shahnewaz-gain** [comment]
It doesn't work on this version `antd": "^5.18.0`

**Comment by saurabh317** [comment]
the above solution doesn't seems to be working for me , hence i achieved the same through `slotProps` props on `DatePicker`

```
    <DatePicker
      open={props.openDatePicker}
      onClose={() => props.setOpenDatePicker(false)}
      format={dateFormat}
      onChange={handleChange}
      slotProps={{
        textField: { variant: 'standard', sx: {'.MuiInput-root': {
          width: 0,
          top: 50
        }}},
      }}
    />
```
