### ISSUE TITLE
Menu horizontal Mode causes error with MutationObserver， MutationObserver still worked after unmount

### ISSUE THREAD

**Issue by SnowCrock** [ant-design/ant-design#18379]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/great-morse-3lmgs)

### Steps to reproduce
It will be displayed automatically.

### What is expected?
No mistakes will occur

### What is actually happening?
it used findDOMNode after unmount, then error occurred

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | react 16.8.6 |
| System | macos |
| Browser | chrome 76.0.3809.100 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17016#issuecomment-523279934
