### ISSUE TITLE
Align labels in description items

### ISSUE THREAD

**Issue by FoxxMD** [ant-design/ant-design#18373]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the `Descriptions` component is `bordered` all of the labels for the `Description Items` are aligned (like a table) regardless of the label content. When the Descriptions component has `bordered={false}` the labels are only as long as their text, leading to no Items being aligned unless all label text is the same length.

I would propose that when `bordered={false}` there is another option to force all labels to the same size (size of the largest label in the column) so that that column is aligned.

### What does the proposed API look like?
Add a prop to `Descriptions` to allow aligning labels, like `alignLabels={true}`

**Comment by zombieJ** [comment]
It's by design to not to align label in borderless style.
You can use pure table to customize it if you have strong willing with this.
