### ISSUE TITLE
Form 表单-演示页面的【输入框组合】中有样式需要修复

### ISSUE THREAD

**Issue by jasonperk** [ant-design/ant-design#1837]
http://ant.design/#/components/form?scrollTo=components-form-demo-input-group

页面的【select 标签输入框】有错位现象

**Comment by RaoHai** [comment]
http://codepen.io/RaoHai/pen/yJBNqQ?editors=001

demo 上看是对齐的，应该不影响使用。页面上的下次更新应该就好了。

**Comment by jasonperk** [comment]
恩 还是提醒一下 因为 我是在实际使用的时候发现也是有错位现象
更新页面的时候留意一下 修复的结果是 修改源码 还是 修复的是样式页面的demoCSS

**Comment by afc163** [comment]
already fixed in https://github.com/ant-design/ant-design/commit/15bb8650377339f3b2dc0dfa000c2bb98126fa29
