### ISSUE TITLE
Tree: Different onSelect action for each branch in a tree

### ISSUE THREAD

**Issue by ericdiliu** [ant-design/ant-design#18375]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently in a multi-level Tree, you can only have one onSelect action for the entire tree, defined at the root. It would be great to have the ability to define different onSelect actions for different branches.
```
Tree (onSelect={onRootSelect)
    - BranchOne (onSelect={onBranchOneSelect})
        -- Leaf 1a
        -- Leaf 1b
        -- Leaf 1c
    - BranchTwo (onSelect={onBranchTwoSelect})
        -- Leaf 2a
        -- Leaf 2b
        -- Leaf 2c
    - BranchThree (onSelect={onBranchThreeSelect})
        -- Leaf 3a
        -- Leaf 3b
        -- Leaf 3c
```

### What does the proposed API look like?
```
Tree (onSelect={onRootSelect)
    - BranchOne (onSelect={onBranchOneSelect})
        -- Leaf 1a
        -- Leaf 1b
        -- Leaf 1c
    - BranchTwo (onSelect={onBranchTwoSelect})
        -- Leaf 2a
        -- Leaf 2b
        -- Leaf 2c
    - BranchThree (onSelect={onBranchThreeSelect})
        -- Leaf 3a
        -- Leaf 3b
        -- Leaf 3c
```

**Comment by zombieJ** [comment]
You can use second param of Tree Select with `node` to get the node info with branch.
