### ISSUE TITLE
Version 3.9.3 not support Tab's renderTabBar props, but CHANGELOG.md says 3.9.0 has supported

### ISSUE THREAD

**Issue by yes1am** [ant-design/ant-design#18381]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rdur2)

### Steps to reproduce
1. In the codesandbox the antd version is 3.13.0, its ok with renderTabBar props
2. change to the version which is lower than 3.13.0, its not work

### What is expected?
expect version 3.9.0 works as the CHANGELOG.md says

### What is actually happening?
but version 3.9.0 not work

| Environment | Info |
|---|---|
| antd | 3.9.3 |
| React | 16.8.4 |
| System | macOS Hish Sierra 10.13.6 (17G65) |
| Browser | chrome 76.0.3809.100 |

---
Seems the dependencies in antd about rc-tabs is wrong, only after antd 3.13.0 requires rc-tabs ~9.6.0 version,  while rc-tabs only support renderTabBar props after 9.6.0.  

I always check the CHANGELOG.md for component props change，hope its correct.

**Comment by afc163** [comment]
Actually it is supported in 3.9.0.

https://codesandbox.io/s/antd-reproduction-template-lbtpj

3.13.0 upgraded the `rc-tabs` to `9.6.0` for render props of DefaultTabBar: https://github.com/react-component/tabs/commit/63b51b559fbee9cf47cb70c44143c4f848017f16#diff-88dc7475eedf918122374be6d7c2c151R6
