### ISSUE TITLE
ant-design现在有文字水平轮播组件么，应用在网站顶部来展示公告消息。

### ISSUE THREAD

**Issue by zoutong123** [ant-design/ant-design#18388]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
应用在网站顶部来展示公告消息

### What does the proposed API look like?
类似Carousel组件

**Comment by afc163** [comment]
暂无。

公告可以用 https://ant.design/components/alert-cn/#components-alert-demo-banner

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/22751
