### ISSUE TITLE
select自定义下拉框如何响应键盘事件

### ISSUE THREAD

**Issue by ppxu** [ant-design/ant-design#18386]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我使用dropdownRender自定义select的下拉框列表，好像默认的键盘事件都失效了，包括上下选择，回车选中，请问要如何设置才能响应键盘事件

### What does the proposed API look like?
none

**Comment by bianliuzhu** [comment]
我也遇到了相同问题
