### ISSUE TITLE
IE11 Incorrect position of Input and Select within Form Items

### ISSUE THREAD

**Issue by mstanuch** [ant-design/ant-design#18389]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
View "Customized Form Controls" demo. 

### What is expected?
Text input and select should be aligned.

### What is actually happening?
Text input is higher than select.

| Environment | Info |
|---|---|
| antd | 3.20.1 |
| React | 16.8.4 |
| System | Windows 10 |
| Browser | IE11 |

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/pull/18348
