### ISSUE TITLE
Ant design 2.x official website can't normally access!

### ISSUE THREAD

**Issue by tjx666** [ant-design/ant-design#18396]
- [ √] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My project is built by ant design 2.x，so 2.x document is important to me.
I can't switch the language to Chinese, and the code of example also can't be expanded.

### What does the proposed API look like?
Browser: latest chrome and firefox developer edition.
OS: mac os

**Comment by afc163** [comment]
gh-pages is broken...

**Comment by afc163** [comment]
Fixed.
