### ISSUE TITLE
Hover on Checkbox has some strange, mis-aligned border when global css excluded

### ISSUE THREAD

**Issue by sanusart** [ant-design/ant-design#18399]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sharp-pasteur-zfxgo)
NOTE: pleas see `index.css` for more details

### Steps to reproduce
Hover the checked checkbox in reproduction example

### What is expected?
Hover should not affect checkbox as with strange border (from animation)

### What is actually happening?
Changes introduced in https://github.com/ant-design/ant-design/pull/18059 add strange border mis-alignment to appear upon hovering checkbox component

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.0 |
| System | MacOs |
| Browser | Google chrome |

---

**Comment by afc163** [comment]
Don't reset `box-sizing` globally, all components styles depend on it.

**Comment by sanusart** [comment]
I don't. The example in codesandbox resets, just to show the behaviour. 
This is what's one would get if one want to avoid modifying global css https://ant.design/docs/react/customize-theme#How-to-avoid-modifying-global-styles because base.less https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less is actually a reset, but it is also has global styles?

**Comment by netusco** [comment]
Why is this issue closed?
Has it been fixed?

**Comment by sanusart** [comment]
Hey @netusco 
Temp fix is to apply reset as more specific to ant if you in the same situation
```
[class*='ant-'],
[class*='ant-']::before,
[class*='ant-']::after {
  box-sizing: border-box;
}
```
