### ISSUE TITLE
Unable to Close Modal in Form Item after edit.

### ISSUE THREAD

**Issue by Gigaclank** [ant-design/ant-design#18394]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-template-np5cw)

### Steps to reproduce
# Normal Operation
* Open Modal
* Close Modal
# Use Case (1)
* Open Modal
* Select an option
* Close Modal
# Use Case (2)
* Open Modal
* Edit Text
* Close Modal

### What is expected?
During Normal operation it should open and close the Modal without issue
Edit the text either via drop down selection or manual edit and be able to close the form

### What is actually happening?
Edit the text either via drop down selection or manual edit and be able to Unable to  close the form

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.9.0 |
| System | Any |
| Browser | Any |

---
I have tested with react-dom v16.4.0  to replicate this however it does not fail with react v16.3.3

**Comment by afc163** [comment]
It is not relevant with antd, your component works in a wrong way at controlled mode.

https://codesandbox.io/s/react-template-jixns

**Comment by Gigaclank** [comment]
> It is not relevant with antd, your component works in a wrong way at controlled mode.
> 
> https://codesandbox.io/s/react-template-jixns

this makes no sense! your code sandbox doesn't work, since it does not contain the antd package. and it is relevant to antd since its an incompatibility!

**Comment by afc163** [comment]
Try refresh again, I mean it is not relevant with antd Form.

**Comment by afc163** [comment]
https://codesandbox.io/s/react-template-dbkos

Basiclly, you should not pass visible as in controlled value.

**Comment by Gigaclank** [comment]
> https://codesandbox.io/s/react-template-dbkos
> 
> Basiclly, you should not pass `visible` as in controlled value.

I think your missing the point. The point of this component is to be used **INSIDE** a form to allow for validation on the values. So yes i agree that it works outside a form, but it does **NOT** work inside a form. What you have done to 'fix' the issue is to remove it out of the form and this is **not** a solution but a workaround. I followed the this example https://codesandbox.io/s/d623d to create a custom component for the form

**Comment by afc163** [comment]
Check this 2 codesandbox, both works whether container `form` or not.

- https://codesandbox.io/s/react-template-5777x
- https://codesandbox.io/s/react-template-dbkos

**Comment by Gigaclank** [comment]
> Check these 2 codesandboxes, both work fine whether contain `Form` or not.
> 
> * https://codesandbox.io/s/react-template-5777x `with Form`
> * https://codesandbox.io/s/react-template-dbkos `without Form, controlled mode`

thank you, this helps. how would you go about using the form and controlled mode then?
This is not very well documented.

**Comment by afc163** [comment]
`getDecorator` is controlled mode without manully adding `value` and `onChange`:

https://ant.design/components/form/#components-form-demo-customized-form-controls

**Comment by Gigaclank** [comment]
> `getDecorator` is controlled mode without manully adding `value` and `onChange`:
> 
> https://ant.design/components/form/#components-form-demo-customized-form-controls

i mean this is the example i used. and still got this issue. i have found a solution now. 

``` js 

static getDerivedStateFromProps(nextProps) {
        // Should be a controlled component.
        if ("value" in nextProps) {
            delete nextProps.value.visible // work around for form not closing after edit
            return {
                ...(nextProps.value || {})
            };
        }
        return null;
    }
```

this is the work around i used since the demo you linked does not show how to handle this scenario.
