### ISSUE TITLE
antd is undefined when I use `import antd from 'antd'`

### ISSUE THREAD

**Issue by yanyu0517** [ant-design/ant-design#18395]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For some reasons, I need to get the whole reference of antd.
I have got undefined when I used `import antd from 'antd` or `import antd from 'antd/dist/antd'` or `import * as antd from 'antd'`

### What does the proposed API look like?
Is it possible for me to get the whole reference of antd?

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-rwk9k
