### ISSUE TITLE
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### ISSUE THREAD

**Issue by sharp0111** [ant-design/ant-design#18400]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-keldysh-ofb5j)

### Steps to reproduce
1. create a Form
2. inside Form.Item, use Upload.Dragger component
3. Use getFieldDecorator's setup similar to the docs' in the Form section 

### What is expected?
not expected to receive this warning: index.js:1437 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

### What is actually happening?
getting this warning: index.js:1437 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | "react": "^16.8.4" |
| System | macOS Mojave Version 10.14.6 |
| Browser | Chrome Version 76.0.3809.100 (Official Build) (64-bit) |

**Comment by yoyo837** [comment]
react-component/form/issues/287

**Comment by sharp0111** [comment]
@yoyo837 it doesn't work for the Upoad.Dragger component.

**Comment by yoyo837** [comment]
@sharp0111 Did you try [React.forwardRef](https://reactjs.org/docs/forwarding-refs.html)

**Comment by sharp0111** [comment]
@yoyo837 thank you!

**Comment by N00nDay** [comment]
What was the solution to this?  I am encountering the same situation.  If I use just Upload I receive no error message but if I use Upload.Dragger I get it.  I am wrapping the Upload.Dragger in forwardRef().  What am I missing?

**Comment by TIS-OMiddle** [comment]
> What was the solution to this? I am encountering the same situation. If I use just Upload I receive no error message but if I use Upload.Dragger I get it. I am wrapping the Upload.Dragger in forwardRef(). What am I missing?

I have the same problem before, and
```
const C = React.forwardRef((props, ref) => (
  <div ref={ref}>
    <Upload.Dragger {...props} />
  </div>
));
```
It work fine for me
