### ISSUE TITLE
在360浏览器的兼容模式下input的placeholder文字不对齐

### ISSUE THREAD

**Issue by GOGOGOSIR** [ant-design/ant-design#18407]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
将360浏览器啊的模式调为兼容模式

### What is expected?
input的placeholder的文字和前面的icon对齐

### What is actually happening?
input的placeholder的文字和前面的icon不对齐

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | react： 16.8.6 |
| System | windows |
| Browser | 360浏览器10.0.1977.0 |

**Comment by afc163** [comment]
360浏览器的兼容模式不是浏览器，你需要提供具体的浏览器渲染引擎信息。

**Comment by afc163** [comment]
可能在 https://github.com/ant-design/ant-design/pull/18348 这里修复了。
