### ISSUE TITLE
select multiple 如何获取第一个tag元素？

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design#18402]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户希望第一个tag是不可以清除且是有tooptie组件解释为何不能清除，我想知道如何获取第一个tag元素以便做单独处理。（option只有在onselect,onchange才不为空，componentdidmount的时候为[]）

### What does the proposed API look like?
https://codesandbox.io/embed/musing-booth-npjip

**Comment by yoyo837** [comment]
既然用React, 就尽量不优先从DOM的角度思考问题吧，提交PR修改API吧

**Comment by yoyo837** [comment]
修改API支持部分已选不可去选，或者重新设计产品交互，使用`select`以外的东西来传达`第一个不能去掉`相同的信息给用户。

**Comment by afc163** [comment]
https://codesandbox.io/s/misty-http-y8pyy
