### ISSUE TITLE
【help】How to use ant-defined-colors by alias in my code ?

### ISSUE THREAD

**Issue by qxchen6** [ant-design/ant-design#18404]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Use ant-defined-color in my code .

### What does the proposed API look like?
```

import {antDesignColors} from 'antd';

<div style={{background : antDesignColors.primary}}>
    this is a "primary color" div
</div>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-colors
