### ISSUE TITLE
Upload组件data字段是否允许异步

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#1840]
## 场景
上传接口接收图片的base64编码，故在data方法中将file转换为base64
![image](https://cloud.githubusercontent.com/assets/17123400/15527820/a0500b34-2270-11e6-8bda-4e0050bd0672.png)
由于FileReader的文件读取为异步操作，故无法直接在data方法内返回要提交的参数
是否有比较好的解决方案？

## 版本
antd@1.0.1

**Comment by afc163** [comment]
beforeUpload

**Comment by hhhyaaon** [comment]
beforeUpload可以阻止上传，但阻止后如何继续本次上传逻辑？

**Comment by afc163** [comment]
beforeUpload 返回值支持 Promise 。

**Comment by afc163** [comment]
http://react-component.github.io/upload/examples/beforeUpload.html

**Comment by hhhyaaon** [comment]
非常感谢
