### ISSUE TITLE
Allow custom keys for Descriptions.Item instead of just indexing an array of children

### ISSUE THREAD

**Issue by shkarupa-alex** [ant-design/ant-design#18408]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7mtno)

### Steps to reproduce
Look at react component tree (in provided example but not in sandbox due to some sandbox limitations).
Escpecially look at Descriptions.Item keys in comparsion with List.Item keys

### What is expected?
Descriptions should use user-provided keys for Item-s

### What is actually happening?
Descriptions enumerates children components from zero to length-1 and use that values as keys.

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | react 16.8.6 |
| System | any |
| Browser | any |

---
Provided example is search results for multiple categories.
Each user query will return different number of categories (blog posts, news, events, regular website pages...)

While Descriptions component does not use provided keys for Items, all children will be re-rendered after each query/response change.

**Comment by zombieJ** [comment]
Can help on keep the Col key. But it may still re-render if row is changed.

**Comment by shkarupa-alex** [comment]
It's better to rerender a part of desrcriptions and a part of lists instead of rerender all descriptions and all lists every time (in my case on every key press).
