### ISSUE TITLE
日期选择面板

### ISSUE THREAD

**Issue by mynameismaosheng** [ant-design/ant-design#18415]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有一个按钮 点击展开日期选择的面板  选择完成关闭这个面板 并记录当前这次选择.  这样可以实现多个日期的筛选
展示形式和日历的卡片模式类似. 但是那个日历的卡片模式不支持选择范围

### What does the proposed API look like?
同目前的就可以

**Comment by afc163** [comment]
建议用 RangePicker 自行进行上层封装。
