### ISSUE TITLE
Strange behaviour prevent user input from typing (with react-hook-form)

### ISSUE THREAD

**Issue by bluebill1049** [ant-design/ant-design#18411]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-wave-3i6tz)

### Steps to reproduce
start to type something in the input, and look the input and log.

### What is expected?
user can type.

### What is actually happening?
user typing is blocked for some reason.

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8 |
| System | Mac  |
| Browser | Chrome |

**Comment by bluebill1049** [comment]
React hook form do attach event listener on the input itself, let me know if that's the root cause of the issue :) 

Would love to know the solution to get around it and what's the root cause as well.

**Comment by bluebill1049** [comment]
looks like the problem is you need a `value` attribute which is strange to me.

https://codesandbox.io/s/elastic-ptolemy-cr5xz

**Comment by afc163** [comment]
I believe it it not a bug of antd's Input.
