### ISSUE TITLE
ConfigProvider在ie11下不可用

### ISSUE THREAD

**Issue by YZHyyy** [ant-design/ant-design#18417]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-c3ldd?fontsize=14)

### Steps to reproduce
import 'react-app-polyfill/ie11';
import 'react-app-polyfill/stable';
import React from 'react';
import ReactDOM from 'react-dom';
import './global.less'
import App from './App';
import moment from 'moment';
import 'moment/locale/zh-cn';
import {  ConfigProvider } from 'antd'

moment.locale('zh-cn');

ReactDOM.render(
    <ConfigProvider>
        <App />
    </ConfigProvider>
        , document.getElementById('root')
    );

### What is expected?
在ie11下运行

### What is actually happening?
在ie11下报错

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | ^16.9.0 |
| System | win10 |
| Browser | ie11 |

---
错误为：SCRIPT5022:objects are not valid as a React child(found:object with keys {$$typeof,type,key,ref,props,_owner,_store} ).if you meant to render a collectiono of children,use an array instead.

**Comment by YZHyyy** [comment]
![2019-08-22 16-26-43屏幕截图](https://user-images.githubusercontent.com/42372392/63501903-120c2080-c4ff-11e9-8d76-b32309a64c43.png)

**Comment by YZHyyy** [comment]
https://codesandbox.io/embed/antd-reproduction-template-tbi4t?fontsize=14

**Comment by YZHyyy** [comment]
> Hello @YZHyyy. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @YZHyyy, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/embed/antd-reproduction-template-tbi4t?fontsize=14

**Comment by afc163** [comment]
codesandbox 本身在 IE11 里就跑不起来，最好给一个 git repo。

**Comment by YZHyyy** [comment]
我新建的例子可以在ie11打开  但是不知道为什么在项目中使用ConfigProvider后在ie11就打不开 在不使用的时候是可以打开的  项目的源码不方便提供  我使用ConfigProvider是为了引入中文语言包  请问除了使用ConfigProvider还有什么其它的办法把组件的英文转为中文吗  比如表格的分页器  谢谢了

**Comment by afc163** [comment]
给个可重现的最小化精简例子吧。

**Comment by smallchicken** [comment]
https://github.com/smallchicken/parcel-ts-react 这个demo使用ConfigProvider在ie11就报错

**Comment by realEago** [comment]
> https://github.com/smallchicken/parcel-ts-react 这个demo使用ConfigProvider在ie11就报错

解决了么？

**Comment by chaichunyang** [comment]
当前在使用3.x最新版，今天也遇到了同样的问题，`<ConfigProvider>`内放`<App/>`会有此错误。但是放一个`antd`组件就正常。最后在App内引入了`message`，并在`componentDidMount`中`message.config({})`解决。感觉这应该是antd的bug，但是能力有限，找不到根本原因。希望对后面的人会有帮助。

```js
import { message } from "antd";

class App extends React.Component {
    componentDidMount() {
        message.config({});
    }
}
```

**Comment by HereChen** [comment]
**问题** 我这边的场景是，在 polyfill 引入前引入了 `ConfigProvider`，会报错：

`SCRIPT5022: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.`

```js
import { ConfigProvider } from "antd";
import zhCN from "antd/lib/locale/zh_CN";
import "react-app-polyfill/ie11";
import "react-app-polyfill/stable";
```

**解决** 在其他代码之前引入 polyfill：

```js
import "react-app-polyfill/ie11";
import "react-app-polyfill/stable";
import { ConfigProvider } from "antd";
import zhCN from "antd/lib/locale/zh_CN";
```

**参考**

> you should run any global polyfills before any other code in the bundle.

* <https://github.com/facebook/react/issues/8379#issuecomment-264867090>
* <https://github.com/ant-design/ant-design/issues/19187#issuecomment-541509920>
