### ISSUE TITLE
allow forcing TreeSelect dropdown direction (revisited)

### ISSUE THREAD

**Issue by matgargano** [ant-design/ant-design#18429]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I saw https://github.com/ant-design/ant-design/issues/9468 was opened by @xuchaoying which referenced https://github.com/ant-design/ant-design/issues/5130 -- however 5130 does not clearly show how to force the direction of the dropdown fro the treeselect

### What does the proposed API look like?
add a 'dropdownDirection' or 'forceDropdownDirection' prop to <TreeSelect />

**Comment by matgargano** [comment]
any update here?

**Comment by matgargano** [comment]
checking back in

**Comment by Mako-L** [comment]
When will 'forceDropdownDirection' be available? I also need it to only go down and make the container longer.

**Comment by afc163** [comment]
trace #35986
