### ISSUE TITLE
table设置不分页，使用过滤时会出错

### ISSUE THREAD

**Issue by r0nn** [ant-design/ant-design#1842]
table设置不分页，使用过滤时会出错，错误信息：
`Uncaught TypeError: pagination.onChange is not a function`

跟踪发现是因为设置 pagination={false} 时应用过滤仍会调用 pagination.onChange
![2016-05-25_142622](https://cloud.githubusercontent.com/assets/1700787/15530186/7cbac280-2285-11e6-8174-45992f7a3198.png)

**Comment by superRaytin** [comment]
拔出萝卜带出坑。。
