### ISSUE TITLE
在Carousel里面只加载了一张图片，渲染后却会显示三张图片

### ISSUE THREAD

**Issue by wustdjf** [ant-design/ant-design#18428]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce
33

### What is expected?
33

### What is actually happening?
33

| Environment | Info |
|---|---|
| antd | 3.5.4 |
| React | 16.3.2 |
| System | Windows 7 |
| Browser | Chrome 76.0.3809.100 |

**Comment by jljsj33** [comment]
这个自已检查下样式嘛好了，，，肯定是样式没加，，，Carousel 如果前后循环是加载三个图片的。。。
