### ISSUE TITLE
表头数据与表格数据不对齐

### ISSUE THREAD

**Issue by miracllife** [ant-design/ant-design#18436]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#Table](https://ant.design/components/table-cn/#Table)

### Steps to reproduce
表头数据与表格数据不对齐

### What is expected?
表头数据与表格数据对齐

### What is actually happening?
表头数据与表格数据不对齐

| Environment | Info |
|---|---|
| antd | 3.12.3 |
| React | 16.8.2 |
| System | suse linux |
| Browser | 火狐31.6.0 |

**Comment by afc163** [comment]
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/507615/63575385-88228d00-c5bc-11e9-9549-be2a3dbe04e1.png">

**Comment by miracllife** [comment]
scroll.x我设置为max-content,在window下没问题，只有在suse linux下的火狐不兼容
