### ISSUE TITLE
Modal with fixed height & scrollable body to display long content

### ISSUE THREAD

**Issue by thisrabbit** [ant-design/ant-design#18434]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When displaying some long content in a Modal (such like EULA), by default, Modal's height is the height of content, and user should scroll to the bottom to click the footer buttons if there are. While in my prospect, Modal's body can be scrollable and Modal has it's fixed height.

### What does the proposed API look like?
```jsx
<Modal
  scrollableBody={true}
  maxHeight="75%"          //"50%" by default if not specificted, "800px" is also ok. When content's height is lesser than maxHeight, just use content's height. Prop `Centered` will also work in this circumenstance.
>
  some long content
</Modal>
```

**Comment by thisrabbit** [comment]
I have found alternative ways to do it...

**Comment by thisrabbit** [comment]
While, it would be better if there have a prop `fullHeigh` which means sum of  height of Modal's title, body and footer is "100%" (full size of broser window's height so that it will auto change when user resize the window).

**Comment by danvln** [comment]
@thisrabbit - what is the solution that you found?

**Comment by thisrabbit** [comment]
> @thisrabbit - what is the solution that you found?

@danvln Sorry for late, I believe that I just set a fixed number of height or use break-point to adjust it when user resize window.
