### ISSUE TITLE
Steps样式冲突

### ISSUE THREAD

**Issue by lv900901** [ant-design/ant-design#18439]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/020u5)

### Steps to reproduce
在官网 自定义点状步骤条 例子上(https://codesandbox.io/s/020u5) 加入size="small"属性 样式会有冲突

### What is expected?
样式无冲突

### What is actually happening?
样式有冲突

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | * |
| System | * |
| Browser | * |

**Comment by yoyo837** [comment]
ref: #18390 #18393

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/18393
