### ISSUE TITLE
使用upload时有什么方法可以清除所选的文件吗？

### ISSUE THREAD

**Issue by beiciye** [ant-design/ant-design#1843]
正在使用Modal配合upload 做图片上传，弹出浮层后可以上传图片。我现在遇到的问题是，当浮层关闭后，upload里面的图片还会一直显示在哪里，只有手动点击才能去掉图片。
我的想法，在浮层关闭的时候出发一个事件，清除所有添加的上传图片

**Comment by beiciye** [comment]
Form组件和Select组件配合Modal组件使用也会产生这样的问题，请问有什么方法吗

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
`Modal` 开关是通过 `visible` 设置的，还需要 `Modal` 再告诉你它要关闭了？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1876
