### ISSUE TITLE
table组件优化

### ISSUE THREAD

**Issue by idujiawei** [ant-design/ant-design#18443]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table组件现在设置scroll，需要去计算所有列宽度，如果是动态列，很不方便，还需要去写计算方法，为什么不像 elment 的 table 组件一样，自动去计算所有列宽度，来赋值到活动 table 上，而不是使用者去计算

### What does the proposed API look like?
像 elment 的 table 组件一样，自动去计算所有列宽度，来赋值到活动的 table 上，而不是使用者去计算

**Comment by yoyo837** [comment]
4.0 应该会考虑这些

**Comment by afc163** [comment]
Duplicate of #12088
