### ISSUE TITLE
Configurable heading font-weight

### ISSUE THREAD

**Issue by jbe456** [ant-design/ant-design#18442]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Current heading font-weight is hardcoded to 600 under the typography less file https://github.com/ant-design/ant-design/blob/4.0.0-alpha.2/components/typography/style/index.less#L15

In our application, we have designed a typography in which headers (h1, h2, h3 and h4) have a 400 font-weight. Having a configurable font-weight would allow us to change it via a less variable.

### What does the proposed API look like?
In https://github.com/ant-design/ant-design/blob/4.0.0-alpha.2/components/style/themes/default.less, add:

```diff
+  @title-fontWeight: 600;
```

and then in https://github.com/ant-design/ant-design/blob/4.0.0-alpha.2/components/typography/style/index.less

```diff
.typography-title(@fontSize; @lineHeight) {
  margin-bottom: 0.5em;
  color: @heading-color;
-  font-weight: 600;
+  font-weight: @title-fontWeight;
  font-size: @fontSize;
  line-height: @lineHeight;
}
```

**Comment by afc163** [comment]
`@typography-title-font-weight` would be better.
