### ISSUE TITLE
给表格插入数据的时候能给表格数据某个属性绑定事件吗？比如说点击表格数据里的导入明细，弹出对应的modal控件

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#1844]

**Comment by aw6658913** [comment]
想上传图片一遍展示，好像上传不了，不知道是不是我上传操作有误

**Comment by afc163** [comment]
```js
render() {
  return <span onClick={ ... }>某个单元格的数据</span>
}
```

**Comment by aw6658913** [comment]
const columns = [{title: '操作',dataIndex: 'action',key: 'action'}];
const data = [{action: <a onclick="obj .houseEnter.importShowModal">点击弹出</a>}];
const obj = {
houseEnter: React.createClass({
    getInitialState() {
      return {
        importvisible: false,
      };
    },
    importShowModal() {
      this.setState({
        importvisible: true,
      });
    },
    importHandleCancel(e) {
      this.setState({
        importvisible: false,
      });
    },
    render(){
      return (
        <div>
            <Table columns={columns} dataSource={data} pagination={pagination} bordered />
              <Modal title="导入小区明细" visible={this.state.importvisible} onCancel={this.importHandleCancel}>
              </Modal>
        </div>
      );
    }
  })
}



如代码所写的 data数据获取在定义onclick方法之前，编译后 打开页面点击是不会触发importShowModal事件的

**Comment by aw6658913** [comment]
const columns = [{title: '操作',dataIndex: 'action',key: 'action'}];
const data = [{action: 点击弹出}];
const obj = {
houseEnter: React.createClass({
getInitialState() {
return {
importvisible: false,
};
},
importShowModal() {
this.setState({
importvisible: true,
});
},
importHandleCancel(e) {
this.setState({
importvisible: false,
});
},
render(){
return (
    <div><Table columns={columns} dataSource={data} pagination={false} bordered /></div>


);
}
})
}

看这个~第一个没发全 漏了return的内容

**Comment by aw6658913** [comment]
table 组件在 return中，不过好像发出去都会自动没掉了~调用的数据 就是定义的data

<Table columns={columns} dataSource={data} pagination={false} bordered />

**Comment by aw6658913** [comment]
我已经自己摸索出来了，将data放在return中赋值就能获取到importShowModal事件

**Comment by aw6658913** [comment]
我已经自己摸索出来了，将data放在render中赋值就能获取到importShowModal事件

**Comment by x007xyz** [comment]
补充一下代码，亲测可用。
```javascript
import React from 'react';
import { Table, Icon, Modal} from 'antd';

const columns = [{
  title: '名称',
  dataIndex: 'name',
  key: 'name'
}, {
  title: '负责人',
  dataIndex: 'manager',
  key: 'manager',
}, {
  title: '地址',
  dataIndex: 'address',
  key: 'address',
}, {
  title: '操作',
  key: 'operation',
  render: (text, record) => (
    <span>
      <a href="javascript:void(0)" onClick={record.edit}>编辑</a>
    </span>
  ),
},{
	title: '编辑',
	key: 'edit',
	colSpan: 0
}];

const data = [{
  key: '1',
  name: '新华书店',
  manager: '无',
  address: '西湖区湖底公园1号',
}, {
  key: '2',
  name: '三味书屋',
  manager: '无',
  address: '西湖区湖底公园1号',
}, {
  key: '3',
  name: '草堂书屋',
  manager: '无',
  address: '西湖区湖底公园1号',
}];

const LibraryMgmt = React.createClass({
	getInitialState() {
	    return { visible: false };
	},
	showModal() {
	    this.setState({
	      visible: true,
	    });
	},
	handleOk() {
	    console.log('点击了确定');
	    this.setState({
	      visible: false,
	    });
	},
	handleCancel(e) {
	    console.log(e);
	    this.setState({
	      visible: false,
	    });
	},
	render() {
		for(let i in data){
			data[i].edit = this.showModal;
		}
		return (
			<div>
				<Table columns={columns} dataSource={data}/>
				<Modal title="书商设置" visible={this.state.visible}
		          onOk={this.handleOk} onCancel={this.handleCancel}>
		          <p>对话框的内容</p>
		          <p>对话框的内容</p>
		          <p>对话框的内容</p>
		        </Modal>
			</div>
		);
	}
});

export default LibraryMgmt;
```
