### ISSUE TITLE
Slider onAfterChange causes infinite recursion with useEffect hook

### ISSUE THREAD

**Issue by steveswork** [ant-design/ant-design#18449]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6f011)

### Steps to reproduce
use useEffect to synchronize incoming value prop with value state as done in line 26 of the index.js file.  
Then adjust the knobs on the rendered component - just a little bit.
observe the console output

### What is expected?
The parent value prop should only change when incoming value prop from its parent is different from its current value state.

### What is actually happening?
onAfterChange prop designed to help the Slider component update its parent's value state also changes its parent's incoming value prop, thereby causing an infinite recursion.

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.9.0 |
| System | 64-bit Window |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-mrwii

It is not antd's bug.

**Comment by steveswork** [comment]
@afc163 Just checked your posted link. It is not using a Button instead of the Slider. Could you use my posted repro link? The reported issue is expressly linked with the Slider component. 

The most head-scratching part is how and why the Slider component is affecting the its parent components incoming value prop when the Slider component onAfterChange event is triggered.

**Comment by steveswork** [comment]
As of 8/28/2019, a _workaround_ solution had been implemented into the repro program to avoid problem. My apologies to others facing this type of issue, that it took me quite a while to call attention to it.

Please go to [slider/range-value/component.js](https://codesandbox.io/s/antd-reproduction-template-6f011?file=/slider/range-value/component.js). The relevant logic is in lines 5 and 69-81.
