### ISSUE TITLE
Want <Input.Group /> to support vertical mode

### ISSUE THREAD

**Issue by thisrabbit** [ant-design/ant-design#18452]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-m364w?fontsize=14)

### Steps to reproduce
1. Open page.
2. Look at border radius of components.

### What is expected?
Correct border-radius that make <Input.Group /> as a whole component.

### What is actually happening?
Wrong border-radius.

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 76 |

---
<Input.Group /> now can merge children components by changing their border radius correctly, but when developers **want pages to be responsive** and need childrens in <Input.Group /> to display vertical, their new border radius are not correct in this case. By the way, it's good to support <Col> in <Input.Group conpact>

**Comment by afc163** [comment]
Sorry, Input.Group not designed for vertical usage. Thx for understand~
