### ISSUE TITLE
Cascader 的 option 里面渲染一个 Modal，Modal 中的 Input 无法被 focus

### ISSUE THREAD

**Issue by lhmiao** [ant-design/ant-design#18453]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vmccd)

### Steps to reproduce
点击选项，弹出 Modal，但 Modal 中的 Input 点击后无法被 focus

### What is expected?
希望能被 Modal 中的 Input 能被 foucs

### What is actually happening?
Modal 中的 Input 无法被 foucs

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.1 |
| System | macOs 0.14.3 (18D109) |
| Browser |  Chrome 76.0.3809.100（正式版本） （64 位） |

---
- antd 3.16.2 版本没有这个问题
- 用 Modal.confirm 打开的弹窗中的 Input 能被 focus
- 能触发 Input 鼠标事件，当没法触发 focus 事件
- 可以获取 Input 的 ref ，在 click 事件触发时手动 focus

**Comment by afc163** [comment]
不要这么使用，这个交互太奇怪了，Cascader 选项就是用来做选择的。

**Comment by lhmiao** [comment]
我这儿业务场景，当没有可用的选项时，出现一个选项为「新建」，点击该选项可以弹出弹窗进行新建操作。麻烦能告知下大概是什么原因引起的么

> 不要这么使用，这个交互太奇怪了，超过了合理扩展的范围，Cascader 选项就是用来做选择的。

我这儿业务场景，当没有可用的选项时，出现一个选项为「新建」，点击该选项可以弹出弹窗进行新建操作。麻烦能指点一下大概是什么原因引起的么？避免以后遇到相同情况，谢谢！！！

**Comment by lhmiao** [comment]
已探明是 rc-cascader 里阻止了 option 的 mousedown 事件的默认行为，外加自动 foucs 到 Cascader 组件造成的。我这的用法确实超过了合理扩展的范围，这个我们自己处理下，感谢回复！！！

**Comment by afc163** [comment]
> 我这儿业务场景，当没有可用的选项时，出现一个选项为「新建」，点击该选项可以弹出弹窗进行新建操作。麻烦能指点一下大概是什么原因引起的么？避免以后遇到相同情况，谢谢！！！

可以试试自定义 `notFoundContent` 来做新建。

**Comment by lhmiao** [comment]
> > 我这儿业务场景，当没有可用的选项时，出现一个选项为「新建」，点击该选项可以弹出弹窗进行新建操作。麻烦能指点一下大概是什么原因引起的么？避免以后遇到相同情况，谢谢！！！
> 
> 可以试试自定义 `notFoundContent` 来做新建。

嗯嗯，目前我们的处理方式是将弹窗挂载到 #app 的 React 树之外（和 `Modal.confirm` 的处理方式一样），这样弹窗中的合成事件就不会冒泡至 `Cascader ` 组件，也就不会有上述的问题，再次感谢回复！！！😁
