### ISSUE TITLE
表单编辑时CheckBox没有根据真假值设定是否选中

### ISSUE THREAD

**Issue by totothink** [ant-design/ant-design#1845]
我在表单中显示CheckBox，使用以下代码：

```javascript
    const internalCodeProps = getFieldProps('internal_code', {})
   ...

   <Checkbox {...internalCodeProps} >内部号段</Checkbox>
```

在实际过程中，编辑时internal_code = true，CheckBox也没有默认选中。以下是HTML输出：
```html
<span class="ant-checkbox" data-reactid=".5.$dialog.0.2.0.4.$wrapper.0.0:$/=10">
  <span class="ant-checkbox-inner" data-reactid=".5.$dialog.0.2.0.4.$wrapper.0.0:$/=10.0"></span>
  <input value="true" id="internal_code" type="checkbox" class="ant-checkbox-input" data-reactid=".5.$dialog.0.2.0.4.$wrapper.0.0:$/=10.1">
  内部号段
</span>
```

是哪里配置不正确？

**Comment by benjycui** [comment]
`valuePropName` http://ant.design/#/components/form?scrollTo=this.props.form.getFieldProps%28id%2C+options%29

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
