### ISSUE TITLE
Dragger has no prop to show upload percentages

### ISSUE THREAD

**Issue by boraikizoglu** [ant-design/ant-design#18454]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When you use `Dragger` component to upload files, there is no prop to show percentages of uploads on the upload list.

<img width="436" alt="63643871-e772c100-c6d2-11e9-8c0c-ebac1d3cc96b" src="https://user-images.githubusercontent.com/17179767/63643984-feb2ae00-c6d4-11e9-848a-ba4368b559b3.png">

### What does the proposed API look like?
API could look like:

```
<Dragger {{showItemPercentage: true}}>
```

**Comment by afc163** [comment]
https://codesandbox.io/s/ecstatic-wildflower-rhii3

This way you can try

**Comment by boraikizoglu** [comment]
> https://codesandbox.io/s/ecstatic-wildflower-rhii3
> 
> This way you can try

@afc163 Your answer doesn't look like a proper solution.

`TypeError: Cannot assign to read only property 'name' of object '#<File>'`

How can you update name of the file if name field of a file is read only?
