### ISSUE TITLE
Locale changed when click button, when using Modal before ConfigProvider mount

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#18450]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-bedoo)

![bug](https://user-images.githubusercontent.com/29817353/63634701-b7a0ca80-c68c-11e9-828d-3a3dcb8c0ffe.gif)

### Steps to reproduce
1 Modal called before ConfigProvider mount
2 ConfigProvider mount with locale 'zh-cn'
3 click 'OK', 'OK' changed to '我知道了'

### What is expected?
one of below is better:
1, re-render 'OK' into '我知道了' when ConfigProvider mount
2, keep 'OK' till destroyed

### What is actually happening?
'OK' changed to '我知道了' on click

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | latest |
| System | mac os 10.14.4 |
| Browser | chrome 78 |

**Comment by afc163** [comment]
Correct, locale depends on ConfigProvider.
