### ISSUE TITLE
使用DatePicker中的RangePicker时，在本月中选择上个月或者下个月的日期时，并没有高亮，是bug还是设计如此？

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#18461]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-start-end](https://ant.design/components/date-picker-cn/#components-date-picker-demo-start-end)

### Steps to reproduce
hover

### What is expected?
本月中上月或下月的日期高亮

### What is actually happening?
并没有高亮

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.0 |
| System | mac |
| Browser | chrome |

我鼠标当前移动到2019年8月30日

<img width="578" alt="屏幕快照 2019-08-25 下午8 31 10" src="https://user-images.githubusercontent.com/29935583/63649975-5275d380-c777-11e9-859c-114668f793e3.png">

**Comment by afc163** [comment]
设计如此。

**Comment by steady-join** [comment]
@afc163  请问是基于什么理念呢？
