### ISSUE TITLE
Menu.item 第二个元素 不是 span时，折叠时 未被隐藏

### ISSUE THREAD

**Issue by fiveLucky** [ant-design/ant-design#18468]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/9c1l4)

### Steps to reproduce
当 collapsed: true 时，Menu.item 第二个元素不是span标签，此时菜单layout折叠，option1 文字未被隐藏

### What is expected?
Menu.item 第二个元素不限定元素类型

### What is actually happening?
Menu.item 第二个元素限定为 span 标签

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.8 |
| System | mac 10.14.6 |
| Browser | chrome 76.0.38 |

---
从使用角度看 应该是 限定了 span 标签，具体原因没看源码

**Comment by afc163** [comment]
目前是这么约定的，支持所有标签实现复杂且意义不大，建议改一改。

**Comment by fiveLucky** [comment]
如果限定的话，建议在文档里说明一下，不然开发者在使用时遇到这个问题比较浪费时间

**Comment by afc163** [comment]
可以帮忙在 Menu 下面加个 FAQ 么

**Comment by fiveLucky** [comment]
可以的

**Comment by afc163** [comment]
https://ant.design/docs/react/contributing-cn
