### ISSUE TITLE
Select选择时getValueProps和getValueFromEvent同时使用时 initialValue不起作用

### ISSUE THREAD

**Issue by beihaifeiwu** [ant-design/ant-design#18469]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/blissful-swirles-6crfo)

### Steps to reproduce
可以看demo

### What is expected?
初始值显示

### What is actually happening?
初始值不显示

| Environment | Info |
|---|---|
| antd | 3.22.1 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome  74.0.3729.131 |

**Comment by afc163** [comment]
```diff
- transporation
+ transportation
```

---

另外，你应该不需要 `getValueProps` 和 `getValueFromEvent`：https://codesandbox.io/s/silent-pine-uuj9r

**Comment by beihaifeiwu** [comment]
已经更正回来了，还是一样的结果
不用 getValueProps 和 getValueFromEvent 提交时的 value 是
```json
{"transportation":"bus"} 
```
而需要的格式是
```json
{"transporation":{"name":"bus","cost":"$5"}} 
```

**Comment by afc163** [comment]
https://codesandbox.io/s/peaceful-diffie-wtj39

建议提交的时候封装出需要的数据。

**Comment by beihaifeiwu** [comment]
getValueProps 和 getValueFromEvent 配合也是可以工作的，这样可以封装一个Select的业务选择组件，不用把逻辑泄漏到表单组件，只是现在initialValue不起作用，用Select的defaultValue antd又会报Warning

**Comment by afc163** [comment]
initialValue 见名思义是会作为 value 直接传给 Select 的，中间不会做任何转换。
