### ISSUE TITLE
Using babel-plugin-import generates duplicate css file on build

### ISSUE THREAD

**Issue by Nilanth** [ant-design/ant-design#18463]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-with-create-react-app#Use-babel-plugin-import](https://ant.design/docs/react/use-with-create-react-app#Use-babel-plugin-import)

### Steps to reproduce
import and css using babel-plugin-import and run yarn run build

### What is expected?
No duplicate css chuck files should be generated

### What is actually happening?
Duplicate css chuck files are generated and it increases the build size

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.9 |
| System | mac,windows |
| Browser | chrome,safari, |

**Comment by afc163** [comment]
What the exact duplicate css chuck files are generated?
