### ISSUE TITLE
关于动态添加classname表格边框2px变成1px的现象

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design#18467]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/group-highlighting-78fgl)

### Steps to reproduce
https://codesandbox.io/s/group-highlighting-78fgl

### What is expected?
https://codesandbox.io/s/group-highlighting-78fgl

### What is actually happening?
2px变成1px的原因为何？
设置的上下左右边框为2，左右效果没有实现

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16 |
| System | window10 |
| Browser | chrome ie |

**Comment by afc163** [comment]
如果自行覆盖样式，需要你自行排查问题了。
