### ISSUE TITLE
键盘上下键移动选择table表格行

### ISSUE THREAD

**Issue by wangruizhan** [ant-design/ant-design#18476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户体验问题

### What does the proposed API look like?
在选中行有一个方法，能让键盘上下键移动选择table表格行

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/4102#issuecomment-452666470
