### ISSUE TITLE
下载的源文件 在win7系统下 编译不了 ，请问下大神 我如何才能正常的编译这个控件哈

### ISSUE THREAD

**Issue by zhddzr** [ant-design/ant-design#1847]
我下载之后 运行 npm install
然后在运行     npm run compile 编译不过去
我是在win7下的，貌似我们的源码只支持linux下的编译
请问下 如果在win7下该如何才能编译成功 谢谢，我们目前好多页面也都是基于antd的，现在想改点东西 发现更改不了源码

**Comment by afc163** [comment]
抱歉，现在没有精力支持，可以到参照这里的回答。https://github.com/ant-design/ant-design/issues/1352
