### ISSUE TITLE
Can't read Input.Password property 'input' of null

### ISSUE THREAD

**Issue by hjiawei** [ant-design/ant-design#18473]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-wg6vn)

### Steps to reproduce
In the demo
1. Click "Show Form" button
2. Click PageHeader back button

### What is expected?
Back to "Show Form" button

### What is actually happening?
Uncaught TypeError: Cannot read property 'input' of null

| Environment | Info |
|---|---|
| antd | 3.22.1 |
| React | 16.9.0 |
| System | Ubuntu 19.04 |
| Browser | Google Chrome 76.0.3809.100 (official build) |

---
I think this is 3.22.1 only and caused by https://github.com/ant-design/ant-design/pull/18441 but I am not 100% sure.

**Comment by XianZhengquan** [comment]
升级了，项目就崩了，哈哈哈
