### ISSUE TITLE
can I have an API to wrap modal?

### ISSUE THREAD

**Issue by meihuanyu** [ant-design/ant-design#18474]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
drag and drop

### What does the proposed API look like?
```
const parentComponent  = (props) => {
       return <ResizableBox>{props} <ResizableBox/>
}

<Modal
parentComponent = {parentComponent }>
balabala
</Modal>

```

**Comment by meihuanyu** [comment]
#3012

**Comment by afc163** [comment]
Right, you can find workaround solution in #3012
