### ISSUE TITLE
Unable to change CSS for table row hover. 

### ISSUE THREAD

**Issue by PraveenVerma17** [ant-design/ant-design#18487]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-27r6l)

### Steps to reproduce
hover css is not working 

.RCM_two_level_table1 tbody tr:hover {
  background: unset;
}

### What is expected?
need ability to chnage hover css

### What is actually happening?
hover css is not changing row color, background etc

| Environment | Info |
|---|---|
| antd | 3.22.1 |
| React | 16.9 |
| System | windows |
| Browser | all |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-ffdtn
