### ISSUE TITLE
表格列宽度拖动时会触发table的onChange方法

### ISSUE THREAD

**Issue by gaorubin1990** [ant-design/ant-design#18484]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-resizable-column](https://ant.design/components/table-cn/#components-table-demo-resizable-column)

### Steps to reproduce
参照antd表格列拖动宽度章节编写代码。进行列拖动时会触发表格的onChange方法

### What is expected?
不会触发表格的onChange方法

### What is actually happening?
触发了onChange方法

| Environment | Info |
|---|---|
| antd | 3.22.1 |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14647#issuecomment-467865540
