### ISSUE TITLE
Input相关组件 allowClear 属性设置为 true 之后组件的交互问题.

### ISSUE THREAD

**Issue by MLDIE** [ant-design/ant-design#18481]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/MLDIE/pen/eYOvPvN?editors=0010](https://codepen.io/MLDIE/pen/eYOvPvN?editors=0010)

### Steps to reproduce
已显示

### What is expected?
Input 组件 allowClear 属性设置为 true 之后交互能与 Select 组件统一:
1. Input 组件 disabled之后 不显示 clearIcon;
2. Input 组件 有默认值时, 鼠标 hover 才显示 clearIcon;

### What is actually happening?
1. Input 组件 disabled 之后也显示了 clearIcon;
2. Input 组件有默认值时, 直接显示 clearIcon, 与 Select 交互不统一;

| Environment | Info |
|---|---|
| antd | 3.22.1 |
| React | ^16.8.6 |
| System | windows 10 |
| Browser | Chrome 74.0.3729.131 |

---
不清楚是设计如此还是怎么回事, 希望能有统一的交互, 谢谢

**Comment by ZzNb0813** [comment]
Input 组件有默认值时, 直接显示 clearIcon, 与 Select 交互不统一;
