### ISSUE TITLE
Input.Password支持allowClear时，清除图标跟Password显示图标不对齐

### ISSUE THREAD

**Issue by xiewangmei** [ant-design/ant-design#18489]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-shtern-ushnq)

### Steps to reproduce
添加allowClear 属性给Input

### What is expected?
两个图标垂直对齐

### What is actually happening?
图标垂直不对齐

| Environment | Info |
|---|---|
| antd | 3.22.1 |
| React | 16.9.0 |
| System | Windows |
| Browser | chrome  78.0.3887.7（正式版本）dev （64 位） |

**Comment by afc163** [comment]
<img width="113" alt="image" src="https://user-images.githubusercontent.com/507615/63745556-12c4fe00-c8d5-11e9-93fe-8e5a845967de.png">

好像没啥问题。

**Comment by xrkffgg** [comment]
刚才试了一下，发现

- 第一个 icon 的尺寸是 12×12，靠顶部显示
- 第二个 icon 的尺寸时 14×14，全行显示

这样就使得，第一个稍微靠上了一点

😂😂😂
