### ISSUE TITLE
Modal.method() not visible In the production environmen（build and deploy on nginx）

### ISSUE THREAD

**Issue by rengeng1986** [ant-design/ant-design#18499]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://none](http://none)

### Steps to reproduce
开发环境下Modal.info等方法均正常弹出，但是build部署到服务器后，无法弹出。

### What is expected?
部署后，程序里的modal可以弹出

### What is actually happening?
未弹出，只有遮罩层

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.6 |
| System | centos7 |
| Browser | Chromeium 70 |

---
经测试，antd@3.20.3版本正常，后续版本均有问题

**Comment by hoangvlbk61** [comment]
I met same error as u 
just check your cloud :)) 
I checked my cloudfare then it works like a charm !
