### ISSUE TITLE
当Avatar头像加载失败后，使用onError方法替换默认头像

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#18495]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-o39ff)

### Steps to reproduce
能显示默认头像

### What is expected?
希望能显示默认头像

### What is actually happening?
希望能显示默认头像

| Environment | Info |
|---|---|
| antd | 3.22.1 |
| React | 16.8 |
| System | win10 |
| Browser | chrome 75.0.3770.100 |

**Comment by yesmeck** [comment]
https://codesandbox.io/s/antd-reproduction-template-kh395

**Comment by zhang504988670** [comment]
如果在map中返回10个头像，用 state 状态去控制是不是不太合理。
https://codesandbox.io/s/antd-reproduction-template-gtmg3
@yesmeck

**Comment by yesmeck** [comment]
@zhang504988670 封装成独立的组件
