### ISSUE TITLE
 Warning: componentWillReceiveProps has been renamed --> componentDidUpdate

### ISSUE THREAD

**Issue by code0n-kn33s** [ant-design/ant-design#18506]
react-dom.development.js:12029 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Animate, Form
---

**Comment by Cuiyansong** [comment]
Any response?

**Comment by SweetSweetME** [comment]
我也遇到了这个警告⚠️
