### ISSUE TITLE
Slect onChange TS类型错误，无法推断

### ISSUE THREAD

**Issue by jieny** [ant-design/ant-design#18505]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
create-react-app xxx --typescript，然后全是最新包，<Select value={1} onChange={(value) => console.log(value)}></Select>，报错，onChange里无法推断value是number类型，之前3.4.5好像正常

### What is expected?
正常运行，ts提示value的类型

### What is actually happening?
Parameter 'value' implicitly has an 'any' type.ts(7006)

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.9.0 |
| System | Windows10 |
| Browser | 最新 |

**Comment by zombieJ** [comment]
```tsx
<Select<number> {...props} />
```
