### ISSUE TITLE
Form表单自定义校验函数内部的语法报错未抛出错误

### ISSUE THREAD

**Issue by leidenglai** [ant-design/ant-design#18519]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/affectionate-tree-piedm)

### Steps to reproduce
自定义校验，如果校验函数内有语法报错，比如：获取value.length，但是当value为undefined的时候，应该抛出错误，但是现在没有任何反应！！

### What is expected?
抛出错误

### What is actually happening?
没有任何反应

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | latest |
| System | Mac os |
| Browser | Chrome |

**Comment by afc163** [comment]
确实有这个问题，由于各种原因目前不太好改。

https://github.com/ant-design/ant-design/issues/17944

**Comment by zombieJ** [comment]
3.x 中应该是不会修了，4.x 里如果返回的不是 promise 且报错会抛出错误提示。

ref: https://ant.design/components/form-cn/#%E8%87%AA%E5%AE%9A%E4%B9%89-validator-%E6%B2%A1%E6%9C%89%E6%95%88%E6%9E%9C
