### ISSUE TITLE
Upload Component's property `transformFile` type incorrect

### ISSUE THREAD

**Issue by tangye1234** [ant-design/ant-design#18512]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/7458a9abcd6fc6e6abe6c776e3c9274d33ceb8c7/components/upload/interface.tsx#L56](https://github.com/ant-design/ant-design/blob/7458a9abcd6fc6e6abe6c776e3c9274d33ceb8c7/components/upload/interface.tsx#L56)

### Steps to reproduce
* open vscode in a typescript environment
* add a `transformFile` handler to an existing Upload component using .tsx file

### What is expected?
* fix the type definition of `TransformFileHandler

### What is actually happening?
* the handler argument `UploadFile.originFileObj` is `undefined`
* the handler argument is `RcFile` rather than `UploadFile`

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16 |
| System | macOS |
| Browser | safari/chrome |

**Comment by wangweiwg** [comment]
这个问题解决了吗？

**Comment by yoyo837** [comment]
更新版本
