### ISSUE TITLE
Select组件多选模式的一个问题

### ISSUE THREAD

**Issue by cagen** [ant-design/ant-design#1851]
在Select组件为多选模式的时候，如果输入的value的数组中有空字符串的话，会导致渲染时候报错，
[例子](http://codepen.io/anon/pen/OXLbpp?editors=0010)：
`Uncaught Error: must set key for <rc-animate> children`

原因我大概猜测是：value的key[被赋值为了value的值：空字符串](https://github.com/react-component/select/blob/master/src/Select.jsx#L506) -> 将LI元素的key[设置为了空字符串的singleValue.key](https://github.com/react-component/select/blob/master/src/Select.jsx#L633) -> 将带有空key的LI[放入到Animte的子节点中](https://github.com/react-component/animate/blob/master/src/Animate.js#L285) -> Animate节点中[校验报错](https://github.com/react-component/animate/blob/master/src/Animate.js#L285)

我不太确定这算不算一个问题，因为数据上问题是这个错误的根本来源。
但是我个人觉得这里不应该抛出一个无关的异常，并且阻止了程序的正常运行。

**Comment by RaoHai** [comment]
原因确实是这样。

**Comment by cagen** [comment]
现在我的做法就是在外层自己做过滤空字符串来避免这种问题。
但我觉得是否会在Select组件中做一层过滤会比较好呢？或者说抛出一个value数组中不能有空字符串的错误？
纯属个人愚见。

**Comment by afc163** [comment]
还是保证一下数据的准确性吧，做太多容错性不一定是个好的模式。

**Comment by shengbeiniao** [comment]
分组多选的时候遇到同样的问题，我觉得这是个bug

**Comment by eruca** [comment]
我也碰到同一个错误提示，可是好像可以排除是key或者value为undefined 或 ""的情况，
```javascript
<Option key={value + i} value={value?value:'空的'}>{text ? text : value}</Option>
```

**Comment by weita0** [comment]
@eruca  传给Select的值里包含undefined或者空string也会抛出这个错误，不一定是Option的key为undefined导致的

**Comment by CandyQiu** [comment]
mode 设置成multiple or tags就会有上述问题

**Comment by shelleyIstar** [comment]
I also encountered the same situation, 
code as follows：
<Selete 	
    mode="multiple" 
    defaultValue={record.notice_way}
    ...
>
...
</Selete>
warning: must set key for <rc-animate> children
after change: 
<Selete 	
    mode="multiple" 
    defaultValue={record.notice_way == '' ? undefined: record.notice_way}
    ...
>
...
</Selete>
no warning

**Comment by shelleyIstar** [comment]
I also encountered the same situation,
code as follows：
<Selete
mode="multiple"
defaultValue={record.notice_way}
...>
...
</Selete>
warning: must set key for children
after change:
<Selete
mode="multiple"
defaultValue={record.notice_way == '' ? undefined: record.notice_way}
...>
...
</Selete>
no warning

**Comment by happier2** [comment]
截止到今天，还是存在这个问题，使用Select，mode是tags或者multiple时一定要注意检查value是否为空字符串或者undefined

**Comment by Nerosen** [comment]
依然存在
