### ISSUE TITLE
Description 组件中的 Description.Item sapn属性错误问题，设置为2，HTML生成的为7，造成样式错乱

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design#18527]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/upbeat-glade-yyw4r)

### Steps to reproduce
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/ant-design-bug2.l2qprkovsir.gif)

```
<Descriptions
  layout="vertical"
   column={8}
 >
          <Descriptions.Item span={2} label="名称">张三</Descriptions.Item>
          <Descriptions.Item span={2} label="移动电话">18735818888</Descriptions.Item>
          <Descriptions.Item span={2} label="邮箱">123@qq.com</Descriptions.Item>
          <Descriptions.Item span={2} label="电话">电话123</Descriptions.Item>
          <Descriptions.Item span={2} label="传真">传真123</Descriptions.Item>
          <Descriptions.Item span={1} label="邮政编码">000000</Descriptions.Item>
          <Descriptions.Item span={1} label="时区">UTC 1</Descriptions.Item>
          <Descriptions.Item span={2} label="语言">中文</Descriptions.Item>
          <Descriptions.Item span={2} label="特性行业类别">行业类别123</Descriptions.Item>
          <Descriptions.Item span={6} label="通讯地址">上海市松江区上海市松江区上海市松江区</Descriptions.Item>
          <Descriptions.Item span={2} label="销售冻结">否</Descriptions.Item>
</Descriptions>
```

生成的HTML代码最后一栏销售冻结的 `colspan` 为 `7`，而不是设置的 `2`。
具体可以查看重现链接和 GIF 图

### What is expected?
根据 span 属性，生成正确的 colspan

### What is actually happening?
生成的colspan错误，导致样式错误

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome |

**Comment by maxmeng93** [comment]
更新了 git 图，应该能比较清楚的描述我的问题

**Comment by chenshuai2144** [comment]
span 是 Description.Item 的数量。 span={2} 会占用两个 DescriptionItem 的宽度。

**Comment by maxmeng93** [comment]
span 就是表格跨列的意思吧？一行设置了8列 `column={8}`，然后最后一行，通讯冻结跨6列，销售冻结2列，应该正好是8列呀，为什么生成的HTML代码，销售冻结会变成`colspan="7"`，我看到其他数据都是按照 设置的span生成的，只有销售冻结不是。难道是我用错了？

**Comment by maxmeng93** [comment]
这是我想实现的布局，图中数字是我设置的span。`column={8}`
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/ant-design-bug3.tstll7vqr3.png)

**Comment by afc163** [comment]
@chenshuai2144 看看是否符合预期

**Comment by zombieJ** [comment]
最后一行看起来像是 bug：https://codesandbox.io/embed/upbeat-glade-yyw4r
