### ISSUE TITLE
使用antbuild内置webpark 打包 想例外过滤掉react/ant部分，webpark.external = {jquery:'jquery'} 无效啊

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#1852]
webpack.config.js 配置举例
使用
内置对象
entry
output
devtool
resolve
resolveLoader
node
loader
plugins
这个是官网提供的

**Comment by benjycui** [comment]
webpack 具体用法请参考 webpack 官方文档，谢谢。
