### ISSUE TITLE
输入框格式化展示中，Tooltip title在初始为空的前提下，于输入框中输入字符后未显示tooltip

### ISSUE THREAD

**Issue by babycannotsay** [ant-design/ant-design#18529]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-germain-lnif3)

### Steps to reproduce
直接在输入框输入字符不展示tooltip，只有在输入字符后失去焦点之后，再切回来才展示。
renderTooltip里对visible的处理有问题吧

### What is expected?
空字符不显示tooltip，输入字符后显示tooltip

### What is actually happening?
空字符不显示tooltip，输入字符后仍不显示tooltip

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
你给的例子里写死了 `title = '';`，这样肯定不会展示 tooltip。

**Comment by babycannotsay** [comment]
@afc163 再开一下，我忘了。已经在codesanbox上改好了

**Comment by afc163** [comment]
这种情况没考虑到，可以这么修改一下：https://codesandbox.io/s/zen-sound-kr0fe

**Comment by babycannotsay** [comment]
不行啊，这样输入字符之后，失去焦点也一直存在了。

**Comment by babycannotsay** [comment]
不行啊，这样输入字符之后，失去焦点也一直存在了。

**Comment by afc163** [comment]
https://codesandbox.io/s/billowing-lake-13mnw

**Comment by babycannotsay** [comment]
改了什么逻辑吗 没看出来 输入框有字符之后，失去焦点 还是会存在tooltip一直在的情况

**Comment by afc163** [comment]
刷一下，我刚才也没保存成功。

**Comment by babycannotsay** [comment]
你上面这个demo。直接在空输入框上输入kkk之类的字符，tooltip就会一直存在
<https://codesandbox.io/s/beautiful-fast-h9gwq>
把this.setState({ visible: !!value })移到if逻辑里就好了。
