### ISSUE TITLE
npm start (node:17106) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead events.js:167       throw er; // Unhandled 'error' event       ^

### ISSUE THREAD

**Issue by naxiaoguang** [ant-design/ant-design#18526]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://new-issue.ant.design](http://new-issue.ant.design)

### Steps to reproduce
(node:17106) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
events.js:167
      throw er; // Unhandled 'error' event
      ^

### What is expected?
跑起来

### What is actually happening?
跑不起来

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 3.22.2 |
| System | max |
| Browser | mac |

**Comment by afc163** [comment]
It is not a antd-related issue.

**Comment by naxiaoguang** [comment]
> It is not a antd-related issue.
文件下载后执行nom start 报错了！

**Comment by afc163** [comment]
不知道你反馈什么问题，一般来说 webpack 配置不属于 React 组件库的范畴。
