### ISSUE TITLE
Cascader: add distinct item highlight when navigating via keyboard

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#18536]
- [v ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will allow for clear UX when using KB navigation

### What does the proposed API look like?
I propose the focused item has a distinct light-blue background, similar to when hovering with mouse.
Unclear:
![image](https://user-images.githubusercontent.com/10534563/63881280-25742b80-c9d8-11e9-9197-31d3137e9c6f.png)
Clear:
![image](https://user-images.githubusercontent.com/10534563/63881291-30c75700-c9d8-11e9-8f6e-75566e915dae.png)

**Comment by avalanche1** [comment]
bump

**Comment by afc163** [comment]
5.x 已经是了！

<img width="453" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/bcace5d0-4441-485a-b9e8-c1afec71891b">
