### ISSUE TITLE
Popconfirm - keyboard shortcut to force confirm

### ISSUE THREAD

**Issue by liesislukas** [ant-design/ant-design#18532]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I use Popconfirm on all "Delete" buttons. I want to have the ability to skip the confirmation when holding some key on the keyboard. E.g. Shift or Option/Alt (mac/windows).

Key should be in props. 

### What does the proposed API look like?
`<Popconfirm .... forceConfirmKey={'Shift'} />`

**Comment by afc163** [comment]
Sorry, I don't think we should support this feature.
