### ISSUE TITLE
Tooltip: Style disorder when the tooltip component wraps the Button component to be disabled

### ISSUE THREAD

**Issue by xinpuchen** [ant-design/ant-design#18534]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-disabled-itwkg)

### Steps to reproduce
- Wrap the Button component with the tooltip component
- Set the Button component to disabled
- Add an inline style to the Button component

### What is expected?
Adding className and style to the Button component does not affect it.

### What is actually happening?
Adding className and style to the Button component is placed on the span of the wrapped Button component, which affects the style.

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.9.0 |
| System | MacOS Mojave Version 10.14.6 |
| Browser |  Version 76.0.3809.100 (Official Build) (64-bit) |

---
I know that you are using a span tag on the outside of the Button component. I also used the same solution during the development process. I want to discuss whether there is a perfect solution or a better method. Thanks very much！

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17449#issuecomment-508321870

**Comment by afc163** [comment]
#4865
