### ISSUE TITLE
Select组件：希望添加trigger参数，可以选择鼠标移入就打开下拉，鼠标离开关闭下拉

### ISSUE THREAD

**Issue by pl2476** [ant-design/ant-design#18530]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在原来的基础上多一种下拉触发方式选择，项目上有这样的需求，如果组件支持的话就不要重新封装实现了

### What does the proposed API look like?
trigger?：'default' | 'mouseControl'；  default：默认方式；mouseControl：鼠标控制

**Comment by afc163** [comment]
建议自行封装吧~

**Comment by pl2476** [comment]
ok, Thanks
