### ISSUE TITLE
CheckboxGroup inside a table doesn't work

### ISSUE THREAD

**Issue by techandmedia** [ant-design/ant-design#18548]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/window-table-basic-example-o1bkh)

### Steps to reproduce
1. Fork window-table from codesandbox
2. Add antd deps
3. Import Checkbox from antd
4. Add the Checkbox and Chekboxgroup as component of window-table

### What is expected?
A single checkbox on each row

### What is actually happening?
Array of checkboxess on each row

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | React or Nextjs |
| System | Windows 10, Intel i5, RAM 8GB, SSD |
| Browser | Chrome latest |

**Comment by afc163** [comment]
It is not antd's problem, please use different state for each row.
