### ISSUE TITLE
CheckboxGroup inside a table doesn't work

### ISSUE THREAD

**Issue by techandmedia** [ant-design/ant-design#18540]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using window-table for rendering large data-table, and combine several ant components, and they work; except for the CheckboxGroup.

### What does the proposed API look like?
The CheckboxGroup renders all options (array) in a single row. And they repeated in the next row and so on so the height of the row becomes much taller and same for the table height.

I am following this link when using the Checkbox: https://ant.design/components/checkbox/
This is the Header Component:

      <Checkbox
        checked={checkBoxAll}
        indeterminate={indeterminate}
        onChange={handleCheckAll}
      />

And this is the "Cell" Component

      <CheckboxGroup
        onChange={handleSingleCheck}
        options={checkBoxOptions}
        value={checkBoxAll}
        onChange={handleSingleCheck}
      />

How can I use Checkboxgroup in a custom table like window-table?

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
