### ISSUE TITLE
Fixed Column Height doesn't correspond to expanded row in ant table

### ISSUE THREAD

**Issue by 1998MaxChykalo** [ant-design/ant-design#18554]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-u3rki)

### Steps to reproduce
Create ant table with expanded rows and fixed column

### What is expected?
Ant table expanded row height to correspond to row height in fixed column

### What is actually happening?
row heights don't match

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.6 |
| System | macOC Mojave 10.14.6 (18G87) |
| Browser | Version 76.0.3809.87 (Official Build) (64-bit) |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16135
