### ISSUE TITLE
InputNumber - Disallow non-digits

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#18556]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently InputNumber allows any character as input.

### What does the proposed API look like?
Only accept digits; other characters must be discarded.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9421#issuecomment-446812723
