### ISSUE TITLE
select multiple第二次选中同一个value value会被删除

### ISSUE THREAD

**Issue by liyue118** [ant-design/ant-design#18550]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
select multiple第二次选中同一个value value会被删除，如何关闭这个功能？

### What does the proposed API look like?
select multiple添加一个value后，第二次选中同一个value，value会被删除，如何关闭这个功能？https://codesandbox.io/s/g0dec。
如何阻止这个默认功能？

**Comment by afc163** [comment]
这个是设计如此，目前没有办法删除。
