### ISSUE TITLE
Tree select text overflow

### ISSUE THREAD

**Issue by Rajesh-kumar-r** [ant-design/ant-design#18557]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-fermat-fy7g9)

### Steps to reproduce
open tree select

### What is expected?
text shouldn't overflow

### What is actually happening?
text over flows

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.9.0 |
| System | mac os 10.14.5 |
| Browser | chrome 76 |

**Comment by afc163** [comment]
```diff
-         dropdownStyle={{ maxHeight: 400, overflow: "auto" }}
+        dropdownStyle={{ maxHeight: 400, overflowY: "auto", overflowX: 'hidden' }}
```

or

```diff
-               title="my leafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleaf"}
+              title={<div style={{ wordWrap: 'break-word', wordBreak: 'break-all' }}>my leafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleafleaf</div>}
```

**Comment by maxid** [comment]
not work

**Comment by gustavosizilio** [comment]
It was closed without a fix?

**Comment by gustavosizilio** [comment]
I think that `dropdownMatchSelectWidth={false}` did the trick.
