### ISSUE TITLE
InputNumber: add allowClear

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#18566]
- [v ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
InputNumber will be uniformal with other Inputs

### What does the proposed API look like?
add `allowClear` prop

**Comment by dengfuping** [comment]
- 功能上应该是可以支持的，不过 `InputNumber` 由于会有 `step operator`，加上 `clear icon` 不确定是否符合设计规范。 @afc163

![image](https://user-images.githubusercontent.com/14918822/64245390-6b337580-cf3d-11e9-9a78-5fee9ce0ff34.png)

**Comment by afc163** [comment]
设计上有冲突，这个场景不做 clear 了。

**Comment by avalanche1** [comment]
huh?

**Comment by avalanche1** [comment]
Why did you close?

**Comment by yoyo837** [comment]
@avalanche1 This feature is not supported from the design at the moment.

**Comment by WarBean** [comment]
其实也可以考虑把step operator挪到左边，右边就能留出clear icon了

**Comment by edward-simpson** [comment]
Bad decision 👎🏼 allow us to choose whether we want step operator or clear icon!
