### ISSUE TITLE
upload上传带有特殊中文汉字乱码，导致上传失败

### ISSUE THREAD

**Issue by pengxiaobao** [ant-design/ant-design#1856]
#967 

## 问题 特殊字 “照”(暂时只发现这个)
上传文件名为：证件照反面.bmp
后台java得到的是：è¯ä»¶ç§åé¢.bmp
<b>java会在拦截器中就报不符合后缀要求格式</b>
```java
InvalidUploadFileException: 上传的文件"è¯ä»¶ç§åé¢.bmp"后缀名不符合要求，只能为"*.jpg,*.gif,*.bmp,*.png,*.*,*"
```
![](https://os.alipayobjects.com/rmsportal/dFJQQAUlXSKhrVL.jpg)

## 在前端试过如下方法都不好使
1.在请求的链接中加上了`_input_charset=utf-8 `
2.在上传组件加上`headers`这个不好使
```javascript
headers:{
     'Content-Type': 'multipart/form-data; charset=utf-8'
 }
```

### 归根结底就是能否在前端设置传参的编码

1. 后台用这个方式是可以转码 ` new String(input.getBytes("ISO-8859-1"),"utf-8");`
    但是这个是拦截器中，暂时没法改。
2. 组件中能否在`Request Header` 中在 `Content-Type`追加charset=utf-8
```javascript
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryhXLVPLbLAqAMqzuv
```
3. 组件中能否在`Request Payload` 中的 `Content-Type`中设置编码
4. 组件中能否在`headers`参数中设置 `Request Header  Content-Type`中的`boundary` 值和 `Request Payload` 中的`boundary`值

![](https://os.alipayobjects.com/rmsportal/EIGJsiDqOHVSCir.jpg)

antd版本0.12.x

**Comment by nikogu** [comment]
修改页面编码为utf-8，在sofa的controller里面配置

**Comment by pengxiaobao** [comment]
页面编码是`<meta charset="utf-8">`

**Comment by afc163** [comment]
建议修改服务端吧，前端貌似做不了什么。
