### ISSUE TITLE
Form API: rename setFieldsValue to setFieldValue

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#18579]
- [v ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This should be consistent with `getFieldValue` api. Also `setFieldsValue` sounds like it is setting multiple fields, whereas it only sets one.

### What does the proposed API look like?
rename `setFieldsValue` to `setFieldValue`

**Comment by afc163** [comment]
There is `getFieldsValue` to match `setFieldsValue`.

More discusstion about why we don't have a `setFieldValue`: https://github.com/react-component/form/issues/4

**Comment by avalanche1** [comment]
![image](https://user-images.githubusercontent.com/10534563/64019872-f3c6a600-cb38-11e9-90cf-c143bb725637.png)
![image](https://user-images.githubusercontent.com/10534563/64019892-ffb26800-cb38-11e9-9f33-306486c30b85.png)
Can you spot the difference in api naming and meaning?

ps. https://github.com/react-component/form/issues/4 this doesn't shed any light on `why we don't have a setFieldValue`
