### ISSUE TITLE
官网 TreeSelect 组件，搜索的时候，匹配的是节点的 value 而不是title

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design#18570]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
搜索 my 搜索不到节点，搜索 leaf1，匹配到了 my 的节点

### What is expected?
匹配title

### What is actually happening?
匹配value

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.6 |
| System | macos 10.14.3  |
| Browser | chrome  76.0.3809.132 |

---
本地 antd 3.20.6 也有此问题
![image](https://user-images.githubusercontent.com/51696361/63997139-32a42e00-cb30-11e9-898b-ef45b45b6aed.png)
![image](https://user-images.githubusercontent.com/51696361/63997147-38017880-cb30-11e9-828d-d74e9ed01185.png)
![image](https://user-images.githubusercontent.com/51696361/63997156-3df75980-cb30-11e9-8681-585744120c7d.png)
![image](https://user-images.githubusercontent.com/51696361/63997170-43ed3a80-cb30-11e9-957b-092345e500c0.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12726
