### ISSUE TITLE
火狐日期选择不会往上弹

### ISSUE THREAD

**Issue by xxx6668** [ant-design/ant-design#18577]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
火狐上 选择日期 在浏览器靠下方点击的时候，点开的时间选择框朝下显示而且只显示一半，而谷歌会往上弹

### What is expected?
跟谷歌保持一致

### What is actually happening?
点开的时间选择框朝下显示而且只显示一半，而谷歌会往上弹

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | react >=16.0.0 |
| System | windows |
| Browser | 火狐 68.0.1 |

**Comment by afc163** [comment]
本地测试谷歌也不会往上弹。

**Comment by zombieJ** [comment]
> 原来的自动上弹在页面还有滚动空间时会造成 #5130 浮层频繁抖动的问题。所以我们优化了这个逻辑，只有在页面的真实区域边缘外才会自动定位，能滚动到的地方都不重新定位。

ref #5130
