### ISSUE TITLE
Cannot read property 'prefixCls' of undefined

### ISSUE THREAD

**Issue by dyywork** [ant-design/ant-design#18573]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/index-cn](https://ant.design/index-cn)

### Steps to reproduce
Tree 组件渲染时出现这个错误

### What is expected?
这个错误怎么解决

### What is actually happening?
组件渲染不出来，页面白屏

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | react |
| System | window |
| Browser | 谷歌 |

**Comment by taoeer** [comment]
我也遇到了同样的问题

**Comment by zombieJ** [comment]
@taoeer , 给个重现看看是什么原因。

**Comment by taoeer** [comment]
@zombieJ 找原因了，我把Tree组件的子组件写成了TreeSelect.TreeNode导致的

**Comment by Timikcool** [comment]
Faced the same issue

**Comment by sauravexodus** [comment]
> Faced the same issue.
> `TypeError: Cannot read property 'prefixCls' of null`

You need to use `TreeSelect.TreeNode`. Check your code, you must be using `Tree.TreeNode` which is wrong implementation

**Comment by IgorSousaFront** [comment]
To me is a bug using `Image` component from Antd and using `Image()` constructor
use:
`import { Image as ImageTag } from 'antd';`

instead of:
`import { Image } from 'antd';`

**Comment by zjz1993** [comment]
> To me is a bug using `Image` component from Antd and using `Image()` constructor use: `import { Image as ImageTag } from 'antd';`
> 
> instead of: `import { Image } from 'antd';`

nice! help me so much

**Comment by lizeze** [comment]
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getPrefixCls')
    at useConfigInject_default (useConfigInject.js:71:34)
    at setup78 (Tabs.js:165:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:155:22)
    at setupStatefulComponent (runtime-core.esm-bundler.js:7204:29)
    at setupComponent (runtime-core.esm-bundler.js:7159:11)
    at mountComponent (runtime-core.esm-bundler.js:5508:13)
    at processComponent (runtime-core.esm-bundler.js:5483:17)
    at patch (runtime-core.esm-bundler.js:5085:21)
    at ReactiveEffect.componentUpdateFn [as fn] (runtime-core.esm-bundler.js:5622:21)
    at ReactiveEffect.run (reactivity.esm-bundler.js:187:25)
```



```
"dependencies": {
    "@lib/core": "workspace:^1.0.0",
    "ant-design-vue": "^3.2.13",
    "axios": "^1.1.3",
    "vue": "^3.2.37"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^3.1.0",
    "less": "^4.1.3",
    "typescript": "^4.6.4",
    "vite": "^3.1.0",
    "vite-plugin-html": "^3.2.0",
    "vue-tsc": "^0.40.4"
  }
```

**Comment by Akash9630** [comment]
I am facing .....  Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'prefixCls') can someone please explain what causes this error in english?
