### ISSUE TITLE
table filters values should is function

### ISSUE THREAD

**Issue by zouxiaomingya** [ant-design/ant-design#18581]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
filters option needs value in the dataSource 

### What does the proposed API look like?
filters:  (value, record)  => record.name.map(item=> {
 text: item,
 value: item,
})

**Comment by afc163** [comment]
I believe you can get everything you need from `record` object.

**Comment by zouxiaomingya** [comment]
of course, but so I have to put columns in the FunctionComponent.

**Comment by afc163** [comment]
Could you describe your situation with more details, now you confuse me.

**Comment by zouxiaomingya** [comment]
hum.. I think my suggestion is redundant, thx for your prompt reply.
