### ISSUE TITLE
Parent disabled TreeNode's children are not disabled

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#18585]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vi402)

### Steps to reproduce
1. Create a Tree
1. Create a TreeNode with disabled prop set to true
1. Create a TreeNode as a child without the disabled prop

### What is expected?
Children TreeNodes should be disabled if their parent is disabled.

### What is actually happening?
Children TreeNodes are still enabled.

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.9 |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
It is not, disabled property only affect current node.

**Comment by zombieJ** [comment]
It's by design. Disabled only affect current TreeNode which not conduct check status instead.
