### ISSUE TITLE
RangePicker组件月份和星期显示为英文

### ISSUE THREAD

**Issue by TUBB** [ant-design/ant-design#18582]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[效果图](http://tubb.github.io/h5-imageviewer/1567158482.jpg)

### Steps to reproduce
只在公司项目中出现，新开项目无法重现

### What is expected?
RangePicker组件月份和星期显示为中文

### What is actually happening?
RangePicker组件月份和星期显示为英文

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | win7 |
| Browser | chrome 75.0.3770.100 |

---
使用LocaleProvider做的国际化（antd/es/locale-provider/zh_CN）

**Comment by afc163** [comment]
https://ant.design/components/locale-provider-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86-LocaleProvider-%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%9F

**Comment by liangGeek** [comment]
> https://ant.design/components/locale-provider-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86-LocaleProvider-%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%9F

解决了吗，老哥，我设置了，还是不行

**Comment by yoyo837** [comment]
试试 3.23.2

**Comment by yoyo837** [comment]
试试 3.23.3

**Comment by liangGeek** [comment]
> 试试 3.23.3

我把antd升级到3.23.3还是不行呢

**Comment by yoyo837** [comment]
来个重现demo

**Comment by liangGeek** [comment]
> 来个重现demo

很奇怪，自己demo是正常显示中文，但项目中显示中英文

**Comment by TUBB** [comment]
> > 来个重现demo
> 
> 很奇怪，自己demo是正常显示中文，但项目中显示中英文

解决了，老哥。通过debug发现，这种情况跟antd框架RangePicker组件没关系，是moment设置的问题

**Comment by liangGeek** [comment]
> > > 来个重现demo
> > 
> > 
> > 很奇怪，自己demo是正常显示中文，但项目中显示中英文
> 
> 解决了，老哥。通过debug发现，这种情况跟antd框架RangePicker组件没关系，是moment设置的问题

怎么设置的 老哥

**Comment by TUBB** [comment]
> > > > 来个重现demo
> > > 
> > > 
> > > 很奇怪，自己demo是正常显示中文，但项目中显示中英文
> > 
> > 
> > 解决了，老哥。通过debug发现，这种情况跟antd框架RangePicker组件没关系，是moment设置的问题
> 
> 怎么设置的 老哥
https://ant.design/components/locale-provider-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86-LocaleProvider-%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%9F
按这个文档设置的，我升级到ConfigProvider了
