### ISSUE TITLE
All form-components support readOnly props

### ISSUE THREAD

**Issue by yeliex** [ant-design/ant-design#18587]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, we can make a form-component like `Select` read-only by setting `value` props, but the dropdown menu could also open. So we should add an `open=false` props at the same time.

What about add a `readOnly` props to all the form-components, make the same experience and appearance.

I can make a PR if the request is accepted.

- [ ] AutoComplete
- [ ] Checkbox
- [ ] Cascader
- [ ] DatePicker
- [ ] InputNumber (make the step icon gray to avoid ambiguity)
- [ ] Mentions
- [ ] Rate
- [ ] Switch
- [ ] Slider
- [ ] Select
- [ ] TreeSelect
- [ ] Transfer
- [ ] TimePicker
- [ ] Upload

### What does the proposed API look like?
```javascript
// like
<Select readOnly />
```

**Comment by afc163** [comment]
Try controlled mode: `<Select value="xxx" />`, it is same as readOnly.

**Comment by yeliex** [comment]
@afc163 As i described in issue, the dropdown menu cloud open after setting value prop

**Comment by tempoeric** [comment]
hi i saw this issue can we add a readOnly props for checkbox needed to support some checkbox that are disabled but retains their css colors
