### ISSUE TITLE
受控fileList数据源的Upload组件  onRemove方法无法回调

### ISSUE THREAD

**Issue by lione0** [ant-design/ant-design#1859]
在页面中创建n个Upload组件（ listType: 'picture-card'），上传成功时通过
onChange: (info)=> {
                        if (info.file.status === 'done') {...略}}
分别将其对应的fileList放到状态机的数组里里实现数据源受控（只允许上传一张图片等）

当点击删除按钮时，onRemove回调不成功

-----------------------------------------------------------------------------
追加：onPreview回调同样不成功
卡片显示样式上面的浏览icon点击无反应，在0.12中会打开一个新标签页，chrome developerTools 查看Element，未看出端倪，经过尝试去掉data-reactid则正常打开一个新标签页

**Comment by lione0** [comment]
现在实现是根据normalize:e=>{}方法的参数e.status='removed' 来自行实现onRemove回调控制fileList数据源

请问这是什么原因？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1887#issuecomment-222319730

注意版本。
