### ISSUE TITLE
The horizontal scroll bar scrolls to the end, and the header and body of the table are misplaced.

### ISSUE THREAD

**Issue by liumemgmei** [ant-design/ant-design#18591]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-xdd4u)

### Steps to reproduce
There are no extra-long fields in the table content, and all column widths have been set.Set horizontal scroll length and vertical scroll length，Drag the horizontal scroll bar to the end.

### What is expected?
Header alignment with body

### What is actually happening?
The header and body of the table are misplaced.Only when both horizontal and vertical scrolls are set at the same time will it appear. It is good only when horizontal scrolls are set.

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.6 |
| System | Windows 10家庭中文版 |
| Browser |  Google Chrome 76.0.3809.132 |

---
In the Mac Google browser environment, the tables above are not misplaced, and in the Windows 10 Google browser environment, the tables are misplaced.

**Comment by afc163** [comment]
Could you add a screenshot of misplaced?

**Comment by liumemgmei** [comment]
![38881EF756B08589226B0757C1FFB9F1](https://user-images.githubusercontent.com/33617202/64072907-551d7f00-ccc9-11e9-8229-2c16f016df4d.png)

**Comment by afc163** [comment]
Could you try leave one column which don't set width?

**Comment by liumemgmei** [comment]
I just tried it, but it didn't work. You can open the link https://codesandbox.io/s/antd-reproduction-template-xdd4u and try it.

**Comment by liumemgmei** [comment]
This problem has been solved by setting the style.
`.ant-table .ant-table-header.ant-table-hide-scrollbar::-webkit-scrollbar {
  width: 20px !important;
}`
20px is the width of the scroll bar of the browser.

The reason for this problem is that if there are both vertical and horizontal scrollbars, the width of the table body should be the width of the table head minus the width of the scrollbar. The actual situation is that the width of the text equals the width of the table head, leading to the table body plus the width of the scroll bar, which exceeds the width of the table head, resulting in misalignment.

**Comment by afc163** [comment]
Fixed in latest 3.x and 4.x version.
