### ISSUE TITLE
The Carousel needs to add the function of dragging left and right.

### ISSUE THREAD

**Issue by MarxZhou** [ant-design/ant-design#18597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At present, the operable area of the component is too small, and the user's mouse operation has difficulty clicking.This experience is especially bad when we provide browsing for multiple images in a dialog box.

### What does the proposed API look like?
<Carousel effect="fade" dragEnable />

**Comment by afc163** [comment]
https://react-slick.neostack.com/

There are `arrows` in react-slick.
