### ISSUE TITLE
import CSS后取对象为空

### ISSUE THREAD

**Issue by IDrinkMoreWater** [ant-design/ant-design#1860]
用最新antd-init脚手架初始化的项目,没有修改webpack配置情况下

问题:
impor  styles from  './abc.css'
console.log('styles ',styles )

引用原生css打印出来的styles 的对象为empty,如果是less是ok的,虽然知道是css-loader的问题但是在antd-init下搭建的怎么去尝试就是不行,其他简略demo都没有问题,我想要的结果是如果是css就不启用css-moudle了,这样子能够实现css和less混编,不熟悉less的团队成员可以先用纯css,有些特殊需要覆盖的地方也可以用;希望能给个解决方案,谢谢

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/blob/7d98b4cfe96fcc272a1b83aca3baf554a67fcf64/boilerplates/plain-react/webpack.config.js#L21-L29

这行把 less 文件用 css-modules 进行处理了。css 没有。

非 css-modules 的文件是没有返回值的。

`import './abc.css'`

**Comment by IDrinkMoreWater** [comment]
@afc163 非常感谢这么快回复,那如果要实现css 返回值,有方案么,现在就卡着这了
