### ISSUE TITLE
InputGroup 有没有合适的api获取被包裹元素的值

### ISSUE THREAD

**Issue by FloaJa** [ant-design/ant-design#18605]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
InputGroup作为一组输入框, 得能获取到里面的值吧, 文档里面没有写, 网上也搜不到, 难道要一个一个获取?
form表单get不到, 那怎么用

 我试着使用form.getFieldDecorator的自定义校验获取值, 但是得到的只有最后一次输入的那个表单的值, 
![1567476252(1)](https://user-images.githubusercontent.com/26762352/64139076-43a3b680-ce32-11e9-878c-1e9b4a213ad7.png)

### What does the proposed API look like?
可以被form.getFieldDecorator包装的组件, 能被表单获取到值, 值最好是个数组, 接收数组能回显数据

**Comment by afc163** [comment]
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
