### ISSUE TITLE
select 获取上一次的值 

### ISSUE THREAD

**Issue by heyizhiyuan** [ant-design/ant-design#18602]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
直接获取Select上一次的值

### What does the proposed API look like?
onSelect(currValue,option,preValue)

**Comment by afc163** [comment]
建议使用受控模式自行解决。

**Comment by heyizhiyuan** [comment]
每次都自己获取感觉有点麻烦
