### ISSUE TITLE
Drawer open animation inconsistent when placement=‘right’ & mask={false}

### ISSUE THREAD

**Issue by johnnylc** [ant-design/ant-design#18607]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-antonelli-lj1m9)

### Steps to reproduce
在antd官网drawer的“渲染在当前 DOM
”的代码基础上修改，设置mask={false}。示例中，当placement="right"时，点击open打开drawer显示动画的过程container内容会随之移动，当placement="left"时，仅drawer移动container内容稳定不变。

### What is expected?
在drawer的显隐过程中，应当仅drawer发生移动，container不应发生变化。

### What is actually happening?
placement="right" mask={false} getContainer={false} style={{position: 'absolute'}}时，container内容随drawer的出现动画发生移动。

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.9.0 |
| System | mac |
| Browser | Chrome 76.0.3809.132 |

---
https://ant.design/components/drawer-cn/#components-drawer-demo-render-in-current 示例中仅添加mask={false}即可复现。

**Comment by jljsj33** [comment]
神奇的 bug

**Comment by jljsj33** [comment]
在 drawer 上的 right: 0 改成 right: 1px 就可以了。。。
