### ISSUE TITLE
【bug】antd-TreeSelect

### ISSUE THREAD

**Issue by ywy94ywy** [ant-design/ant-design#18610]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
基本用法中，输入my搜索含有my字符串的节点

### What is expected?
展开节点my leaf

### What is actually happening?
暂无数据

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.6 |
| System | windows 7 |
| Browser | chrome版本 75.0.3770.142（正式版本） （64 位） |

---
antd-TreeSelect 搜索功能有问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12726
