### ISSUE TITLE
when click to another menu item firstly show title but clicked link don't change

### ISSUE THREAD

**Issue by slavakam** [ant-design/ant-design#18615]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu/](https://ant.design/components/menu/)
https://codesandbox.io/s/strange-currying-zgu54

### Steps to reproduce
1. go to https://ant.design/components/menu/ from iphone
2. go to third example (Collapsed inline menu)
3. click on collapse button
4. Click to second item => firstly showed title (Option 2) but item didn't select.
    Click to third item => firstly showed title (Option 3) but item didn't select.
    Then click to second item => item selected

### What is expected?
when click to another menu item switch to clicked item by first click

### What is actually happening?
when click to another menu item firstly show title but clicked link did not change

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | your current version |
| System | ios |
| Browser | safari |

<!-- generated by ant-design-issue-helper. DO NOT REMOVE --

**Comment by dengfuping** [comment]
- `antd` is designed for PC and don't consider to support for interactions in mobile.
