### ISSUE TITLE
List and React Hooks: Invariant Violation: Invalid hook call

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#18617]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/avalanche1/pen/RwbLGjO?editors=0010](https://codepen.io/avalanche1/pen/RwbLGjO?editors=0010)

### Steps to reproduce
Pipe a functional component that contains Hooks through `List renderItem` prop

### What is expected?
Error-free behaviour

### What is actually happening?
Console error: `Uncaught Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.`

| Environment | Info |
|---|---|
| antd | 3.23.0 |
| React | 16.8 |
| System | macOs |
| Browser | Chorme 75 |

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/VwZMmKw?editors=0011

**Comment by afc163** [comment]
> Hooks can only be called inside of the body of a function component.

**Comment by avalanche1** [comment]
Strange, because I'm calling it exactly as a function.

**Comment by GheorgheP** [comment]
@avalanche1, I had a similar problem like yours, mine was because I used `npm link`.
https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24176#issuecomment-630607366
