### ISSUE TITLE
 There is no way to pass "focus" props into the input component

### ISSUE THREAD

**Issue by Seresigo** [ant-design/ant-design#18613]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input/](https://ant.design/components/input/)

### Steps to reproduce
don't need

### What is expected?
Can throw props

### What is actually happening?
Can't throw props

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.9.0 |
| System | Mac OS Latest |
| Browser | 76.0.3809.100 |

**Comment by afc163** [comment]
Could you understand your issue?

**Comment by Seresigo** [comment]
Pass props in to component

**Comment by afc163** [comment]
input don't have focus prop.

https://codesandbox.io/s/antd-reproduction-template-28nsf
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input

**Comment by Seresigo** [comment]
https://www.w3schools.com/jsref/event_onfocus.asp

**Comment by afc163** [comment]
```js
<Input onFocus={() => {} />
```

**Comment by afc163** [comment]
https://reactjs.org/docs/events.html#mouse-events
