### ISSUE TITLE
Publish SCSS / Stylus packages

### ISSUE THREAD

**Issue by snebjorn** [ant-design/ant-design#18611]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi, I was wondering if it would be feasible to supply SCSS and/or Styles versions along with the LESS styles you currently have. You've closed similar requests in the past with the reason that it would be way to much work. However they're a few years old. So I was wondering if this has changed.

It would be nice to be able to write syles in your favorite format.

Style converters exist but I don't know if they actually work.

### What does the proposed API look like?
Not relevant

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Are-you-going-to-provide-Sass/Stylus(etc.)-style-file?

**Comment by LinboLen** [comment]
related #38406
