### ISSUE TITLE
Upload component can't upload more than 1 file

### ISSUE THREAD

**Issue by theprimone** [ant-design/ant-design#18618]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y5wq8)

### Steps to reproduce
It's invalid that upload more than 1 file after change antd to upper 3.23.0 and clear all initial pictures

### What is expected?
Upload 8 files

### What is actually happening?
Only upload 1 file successfully

| Environment | Info |
|---|---|
| antd | 3.23.0 |
| React | 16.8.6 |
| System | win10 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/06d7f0deecda4d831a998358fe2bf410dd7e8543#diff-ed7c05e544978302b73eec6e193cb92bR86-R88

Upload can't upload file any more. @zombieJ
