### ISSUE TITLE
Pagination component needs a page flipping table to automatically scroll to the top of the api

### ISSUE THREAD

**Issue by MarxZhou** [ant-design/ant-design#18623]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the amount of data in the table is relatively large, after the user turns the page, the scroll bar position is positioned at the bottom. If you want to see the top data and need extra operations, the experience is not very good.

### What does the proposed API look like?
<Pagenation scroolTop />

**Comment by MrHeer** [comment]
I'm trying it.
