### ISSUE TITLE
Message组件能不能提供类似Notification设置key的功能保证输出的是同一个

### ISSUE THREAD

**Issue by Anoiing** [ant-design/ant-design#18621]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在接口报错的时候使用了message，但是如果后端服务整体不可用，某一个页面多个接口报错就会出现多次弹出message且内容一样的问题，Notification可以设置同一个key来保证只出现一次，不知道message能否支持一下

### What does the proposed API look like?
message支持设置key值，同一个key值的只出现一次

**Comment by wendzhue** [comment]
应该统一调用一个函数，由该函数负责 debounce 等操作。让组件库处理这个事情不是很合理，而且意味着你要在代码里设置一些 magic string。

**Comment by dengfuping** [comment]
- 感觉是可以支持的，参考 Notification 的实现就可以。https://github.com/ant-design/ant-design/blob/master/components/notification/index.tsx#L100

**Comment by wendzhue** [comment]
@dengfuping 可以的话我想做这个（最近在练习 React）

**Comment by dengfuping** [comment]
@wendzhue 可以直接提 PR，已经 assign 给你了。

**Comment by wendzhue** [comment]
This issue is not closed autometically.

**Comment by afc163** [comment]
<img width="560" alt="image" src="https://user-images.githubusercontent.com/507615/65576573-d6082780-dfa4-11e9-93d7-b72c8138e146.png">

Need mannully operation.
