### ISSUE TITLE
TreeSelect 多选的时候suffixIcon 不生效

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#18625]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-leavitt-9d63s)

### Steps to reproduce
treeSelect设置属性 `multiple：true`
再设置` suffixIcon={ <Icon type="plus" /> } `

### What is expected?
在多选的情况下，可以显示这个Icon

### What is actually happening?
不显示自定义的icon.

| Environment | Info |
|---|---|
| antd | 3.23.0 |
| React | 16.2.0 |
| System | window 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
4.0 版本会支持，3.x 中不大动了。

**Comment by SamKirkland** [comment]
> 4.0 版本会支持，3.x 中不大动了。

As of alpha **antd-v4 alpha 11** it's still an issue, [see recreation](https://codesandbox.io/s/silent-rgb-knu92)

**Comment by chinhoe** [comment]
Does this mean this issue will not be fixed in 3.x and we'll have to wait till 4.0 to be released? I am currently having problem with this in my project too :/

**Comment by yoyo837** [comment]
Move to #20723

**Comment by yoyo837** [comment]
@zombieJ You want to reopen this？

**Comment by yoyo837** [comment]
We should at least fix it in version 4.0.
