### ISSUE TITLE
The "label Col" and "content Col" in the "Description List" have the same key when the props "bordered" is existing.

### ISSUE THREAD

**Issue by Swind** [ant-design/ant-design#18633]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-b65h7)

### Steps to reproduce
Create a Description List with "bordered" props

### What is expected?
The Col key of label and content should be different

### What is actually happening?
The Col key of label and content are the same

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.8.6 |
| System | Ubuntu |
| Browser | Chrome 75.0.3770.142 |

---
The root cause is this  https://github.com/ant-design/ant-design/commit/4dfed8d0b7665016a4f6454904c0789c1386e5f9#diff-8497d724f049f0645ecf05ee488bbe9f

**Comment by zhangcy4553** [comment]
When i use a loop to render a DescriptionItem List, the list item needs a key, but the key will be used in two col.
[![Edit antd reproduction template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-360wq?fontsize=14)
And I got a ```Encountered two children with the same key``` Error

**Comment by lc-stevenzhang** [comment]
Still got this problem.
