### ISSUE TITLE
form.getFieldProps的事件中是否可以更新当前表单组件显示的值

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#1863]
## 场景
![image](https://cloud.githubusercontent.com/assets/17123400/15566590/6e0a3368-2354-11e6-9f5a-d0b1677d861c.png)
Select组件位于表单中，添加onChange事件，判断：若当前选中全部，则清除之前所有已选项，仅显示全部

## 代码
```
render(){
    
    return (
        <Form>
             <FormItem>
                 <Select {...getFieldProps("select",{onChange:})}></Select>
            </FormItem>
        </Form>
    )
}
_getFieldProps(){
    let {getFieldProps,setFieldsValue} = this.props.form;
    return {
        select:getFieldProps("select",{
            onChange: (keys) => {
                    if (keys.slice(-1)[0] == opt_all.id) {
                        //更新表单组件的值
                        setFieldsValue({
                            select: [opt_all.id]
                        })
                    }
                }
        })
    }
}
```
由于getFieldProps默认会占用onChange，且会在自定义onChange后执行，故希望通过以上方式更新表单显示的值，但没有成功
是否有其他方式解决这个问题？

## 版本
antd@1.0.1

**Comment by benjycui** [comment]
用 [setFieldsValue](https://github.com/react-component/form#setfieldsvalueobj-object) 吧，不过要在 `componentWillRecieveProps` 里面判断下，不然会死循环。

**Comment by hhhyaaon** [comment]
已使用setFieldsValue，但仍无法实现，提供demo：
http://codepen.io/hyaaon/pen/bebJKV?editors=1010

**Comment by benjycui** [comment]
用 [`normalize`](http://react-component.github.io/form/examples/normalize.html) 才对，这样也不需要处理死循环的问题。。。 😅

**Comment by hhhyaaon** [comment]
恩恩成功了，多谢！
更新后的demo：http://codepen.io/hyaaon/pen/bebJKV?editors=1111
