### ISSUE TITLE
Table设置scroll={{ y: 240 }} bordered时，表格列数过多会出现thead的border和tbody的border移位不对齐

### ISSUE THREAD

**Issue by 1416246152** [ant-design/ant-design#18634]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/sandy_cc/pen/RwbLMyQ?&editable=true&editors=001#anon-signup](https://codepen.io/sandy_cc/pen/RwbLMyQ?&editable=true&editors=001#anon-signup)

### Steps to reproduce
点击链接里的demo即可

### What is expected?
Table设置scroll={{ y: 240 }} bordered时，表格列数过多的border不要移位

### What is actually happening?
Table设置scroll={{ y: 240 }} bordered时，表格列数过多的border移位

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | ^16.7.0 |
| System | MacOS |
| Browser | Google Chrome 76.0.3809.132 |

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/pozWLGo?editors=0010

**Comment by afc163** [comment]
Or: https://codepen.io/afc163/pen/LYPzdvz?editors=0110

**Comment by jackywq** [comment]
@afc163 你给的demo，在表格的最后几列，依旧存在列不对齐的情况
