### ISSUE TITLE
关于tab右键菜单的问题

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#18635]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有看到issue有相关问题，不过对tabTitle的边缘地方似乎无效，只有对文字右键才有效。

使用type:'card'，比较明显：https://codesandbox.io/s/condescending-moon-ytgvd

尝试使用onTabClick函数，自定义右键菜单，不过只有左键能触发函数？

### What does the proposed API look like?
tab右键出现菜单

**Comment by afc163** [comment]
你需要 `renderTabBar`：https://ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar
