### ISSUE TITLE
antd 升级 2.9.1 -> 3.22.2 控制台报错，不影响启动

### ISSUE THREAD

**Issue by UncleWang8898** [ant-design/ant-design#18631]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://dev-admin.moufans.com/#/](http://dev-admin.moufans.com/#/)

### Steps to reproduce
antd 升级之后控制台有个警告

### What is expected?
解决警告的问题

### What is actually happening?
antd 升级之后控制台有个警告

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.9.0 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
请提供未压缩版本的在线重现
