### ISSUE TITLE
ie11下checkbox group报对象不支持findIndex方法

### ISSUE THREAD

**Issue by TiamoJrZhang** [ant-design/ant-design#18641]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-b5n5p?fontsize=14)

### Steps to reproduce
在ie11使用CheckboxGroup组件并点击选择复选框

### What is expected?
兼容ie11

### What is actually happening?
未兼容

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 16.8.4 |
| System | windows |
| Browser | ie11 |

**Comment by afc163** [comment]
You need polyfill: https://ant.design/docs/react/getting-started#Compatibility

**Comment by TiamoJrZhang** [comment]
大佬你好， antd-tools在编译打包的时候不进行polyfill么

> You need polyfill: https://ant.design/docs/react/getting-started#Compatibility

**Comment by afc163** [comment]
不的，否则不需要兼容 IE 的项目就浪费了。

**Comment by TiamoJrZhang** [comment]
> 不的，否则不需要兼容 IE 的项目就浪费了。

嗯好，谢谢
