### ISSUE TITLE
input 组件内输入文字后连续点两个空格会打出一个点

### ISSUE THREAD

**Issue by BurnhamZhang** [ant-design/ant-design#18647]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-3hhdr)

### Steps to reproduce
 input组件内随便输入文字后连续打两个空格第二个空格会变成一个点

### What is expected?
当然是两个空格
23    

### What is actually happening?
23 .

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.9 |
| System | mac 10.15 |
| Browser | Google Chrome 76.0.3809.132 |

**Comment by BurnhamZhang** [comment]
![截屏2019-09-03下午10 43 27](https://user-images.githubusercontent.com/5702449/64183318-4b984080-ce9c-11e9-8854-997cb9a21e62.png)

**Comment by wendzhue** [comment]
![屏幕快照 2019-09-04 10 56 17](https://user-images.githubusercontent.com/12122021/64222436-a5cbec80-cf02-11e9-8969-783e49ce48a7.png)
