### ISSUE TITLE
点击 table 单元格，想拿到列名

### ISSUE THREAD

**Issue by puretang** [ant-design/ant-design#18640]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
点击单元格，获取它在table中的 row 和 column，用来标示在json里的地址。

### What does the proposed API look like?
column render 目前是 Function(text, record, index) {}，期望增加一个 column 参数，即 Function(text, record, index, column) {}

**Comment by afc163** [comment]
自己传进去就行了，你已经知道是哪一列了。

```
const columnNames = ['column 1', 'column 2', 'column 3'];
const columns = columnNames.map(name => ({
  name,
  render: (text, record, index) => {
   console.log('column:', name);
  }, 
});

columns={columns}
