### ISSUE TITLE
选择按钮RadioGroup 能给对应的每个选项 下方多一行描述吗

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#1865]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

---

提问之前，建议先阅读[这份提示](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question)。:-)

如果是报告 bug，请按照下列格式编辑问题，务必提供复现步骤，否则恕难解决，非常感谢！

## 你做了什么？

（例如，我吃了一个汉堡）

## 你期待的结果是：

（例如，我应该饱了）

## 实际上的结果和抱怨：

（例如，我还是饿的，肯定是哪里出问题了）

## 可重现的在线演示

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## 本地环境信息

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by benjycui** [comment]
http://doc.zengrong.net/smart-questions/cn.html

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1825#issuecomment-220986508

你又这样空白格式直接提交问题，不需要的话哪怕清空一下。

**Comment by afc163** [comment]
建议用 `Radio` 自行封装。
