### ISSUE TITLE
Anchor组件 能否提供一个监听当前激活的Link的回调  滚动页面的时候右边有个激活的小圆点会跟随 所以我想在滚动的时候取到当前的激活的那个小圆点的href

### ISSUE THREAD

**Issue by cszo** [ant-design/ant-design#18655]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Anchor组件 能否提供一个监听当前激活的Link的回调  滚动页面的时候右边有个激活的小圆点会跟随 所以我想在滚动的时候取到当前的激活的那个小圆点的href

### What does the proposed API look like?
一个function 页面滚动的时候  如果右边的小圆点变化  便会拿到当前的active-link的相关信息

**Comment by shaodahong** [comment]
恩。可以加一个 `onChange` 事件

**Comment by orzyyyy** [comment]
Close via #18715
