### ISSUE TITLE
Vertical Tabs jumps when activated

### ISSUE THREAD

**Issue by pmsoltani** [ant-design/ant-design#18652]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7eui2)

### Steps to reproduce

- Use a `Tabs` component with ` tabPosition="left"`
- Use a longer title for one of the `TabPane`s
- Activating and deactivating that tab will cause the tab line and the content to move

### What is expected?
Activating and deactivating any tabs should take place in a fixed position

### What is actually happening?
Activating a tab makes its title **bold**. That increases the space needed for the title and so the tab bar moves to left a bit.

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.9.0 |
| System | Win 10 |
| Browser | Google Chrome 76.0.3809.132 |

**Comment by dengfuping** [comment]
- @pmsoltani Maybe we could use `pseudo element` to avoid it, as the [demo](https://jsbin.com/sizanunedi/edit?html,css,output) shows.

**Comment by pmsoltani** [comment]
@dengfuping Thanks for the reply.

> Maybe we could use `pseudo element` to avoid it, as the demo shows.

Perhaps, but for now, I am going to use `tabPosition="top"` until the issue got fixed.

I should probably mention that even the horizontal tabs act a little twitchy. You can see it for yourself in the first example at [https://ant.design/components/tabs/](https://ant.design/components/tabs/). **Try switching between "Tab 1" & "Tab 3". That would cause "Tab 2" to move a bit.**

**Comment by dengfuping** [comment]
- Yeah, it's just the side effect of `font-weight` and doesn't matter with `tabPosition`.

**Comment by pmsoltani** [comment]
@dengfuping Sadly, I must decline the offer of creating a Pull Request. Perhaps I can be of assistance in some other time.

**Comment by dengfuping** [comment]
- @pmsoltani  That's OK, just feel free about it.

**Comment by afc163** [comment]
Closed by #24284
