### ISSUE TITLE
provide native Web Component 

### ISSUE THREAD

**Issue by lithic** [ant-design/ant-design#18654]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Provide native web components, so we can use them without dependency hell.

### What does the proposed API look like?
Standards web component api

**Comment by afc163** [comment]
no plan.

**Comment by lithic** [comment]
@afc163 why?

**Comment by lithic** [comment]
Please reopen this issue. So others can share their ideas

**Comment by lithic** [comment]
Having support for web component allows us to use this on any web app

**Comment by afc163** [comment]
https://ant.design/docs/spec/introduce#Front-end-Implementation
