### ISSUE TITLE
Antd tree-shaking not working with rollup.

### ISSUE THREAD

**Issue by B-Esmaili** [ant-design/ant-design#18650]
I have working on a library and i am using antd as UI library.i import components with es6 format like `import DatePicker from 'antd/es/date-picker' but when i generate bundle with `rollup` the entire library gets bundled.but as mentioned :

> Note: antd support ES6 tree shaking by default even without the below plugin.
only `datepicker` code should be included.here is my rollup config :

```
import babel from 'rollup-plugin-babel'
import commonjs from 'rollup-plugin-commonjs'
import external from 'rollup-plugin-peer-deps-external'
import postcss from 'rollup-plugin-postcss'
import nodeResolve from 'rollup-plugin-node-resolve'
import url from 'rollup-plugin-url'
import svgr from '@svgr/rollup'
import json from 'rollup-plugin-json' 
import autoNamedExports from 'rollup-plugin-auto-named-exports';
import {terser} from 'rollup-plugin-terser'

import pkg from './package.json'

export default {
  input: 'src/index.js',
  output: [
    {
      file: pkg.main,
      format: 'cjs',
      sourcemap: true, 
      name : 'timeline'
    },
    {
      file: pkg.module,
      format: 'es',
      sourcemap: true,
      name : 'timeline'
    },
    {
      file: pkg.browser,
      format: 'iife',
      sourcemap: true,
      name : 'timeline'
    }
  ],  
  plugins: [
    nodeResolve({
      jsnext: true,                                                                                                                     
      main: true,                                                                                                                      
      browser: true
    }) ,
    commonjs({
      include: 'node_modules/**'
    }),  
    postcss({
      modules: true
    }),
    babel({
      exclude: 'node_modules/**',

      plugins: [
        ['import', { 'libraryName': 'antd', 'libraryDirectory': 'dist', 'style': 'css' }],
        ['import', { 'libraryName': 'antd-mobile', 'libraryDirectory': 'dist', 'style': 'css' }, 'antd-mobile']
      ]
    }), 
    external({
      ...Object.keys(pkg.peerDependencies)
    }),    
    json(),
    url(),
    svgr(),    
    terser()  ,             
  ]
}
```
am i missing something?

**Comment by Mihai-github** [comment]
@B-Esmaili I'm having an issue also with rollup not including 'I guess' the antd design CSS into the build... Have you figured out a solution?

**Comment by B-Esmaili** [comment]
@Mihai-github  No I couldn't find solution to this problem. But I wanna give you a clue which I believe could solve your problem. If lack of support for UMD build is an option for you then you can completely get off of rollup and use babel to bundle for COMMON-JS only.

**Comment by Mihai-github** [comment]
@B-Esmaili At the moment rollup did a good job creating the build the only issue I have with him is not including my project CSS in the bundle and for some kind of reason the CSS from the ant library is not also included... I guess this is will all libraries but for antd is the first one I can see.....

**Comment by B-Esmaili** [comment]
@Mihai-github  Are you authoring a library based on antd? if so I'm afraid you better stop targeting UMD build cause the whole antd will be included in your UMD bundle.

**Comment by Mihai-github** [comment]
I'm building a React app that will be used as a package, it works but the only problem I'm facing is with the style (CSS, scss etc....)

**Comment by B-Esmaili** [comment]
Ok then chances are very high you'll be using this package in a SPA react application (and not in a monolith app) right? if this is the case then why you bother with bundling this package with rollup? transpiling your app into a `common-js` bundle should be enough I think.

**Comment by Mihai-github** [comment]
Make sense what are you saying, but I started this route and now I just wanna finish this .... because I don't have any idea why CSS is not included in the bundle, and everything I tried/did nothing...

**Comment by B-Esmaili** [comment]
Then I hope al the best for you in this journey. But one last thing worth mention that not any library is completely `tree-shakable` and maybe this applies to `antd` as well.

**Comment by Mihai-github** [comment]
I made it work.

**Comment by osamamammar** [comment]
I have the same problem.. what are you doing to solve it? @Mihai-github

**Comment by georgezouq** [comment]
same problem, any solution? @osamamammar @B-Esmaili @Mihai-github

**Comment by B-Esmaili** [comment]
@georgezouq If you want a solution for this specific problem , then I would beg your pardon for not being able to help you out. But if you want an overall solution for "How to build a component library using Ant Design?" problem, then I have some suggestions based on my personal experience. I went through a lot of options to accomplish what I was indented to do, from `manually setting up a component library from scratch` to `tsdx`  and `create-react-library`, but none of them worked for me. Eventually I ended up using 'NX' which apart being a library creation tool it is a robust `mono-repo` tool which has a lot of integration for a lot of other `tools` and `libraries` (here is where NX really shines compared to other options). But there is other points really worth mention is , if you don't wanna target `UMD/AMD` bundle then you don't have to worry about title of this post. That means if you wouldn't be using your library in browser based dev environment (which chances are very high you wouldn't) then you can completely ignore about rollup and use `bable` directly to `transpile` your linrary into a `common-js`  bundle. I Hope my experiences would come helpful for you.

**Comment by georgezouq** [comment]
> B-Esmaili

Thanks, it helps me a lot.
