### ISSUE TITLE
table 组件 树型结构 获取正确的index

### ISSUE THREAD

**Issue by kawaiiz** [ant-design/ant-design#18666]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
获得一条信息正确的index,有助于快速找到点击的那条数据

### What does the proposed API look like?
```
 render: (text: IRoute, record: IRoute, index: number) => {}
```
当列表是树形列表时，index返回的是那条数据所在的子列表的序号，希望能获得相对与整个列表的一个序号，比如[1,10,2] 第一列的子列表的第十项的子列表的第二个数据

**Comment by dengfuping** [comment]
- 可以将你需要的 `index` 信息提前写入到 `record` 中，`Table` 组件本身不应该做这些事情。

**Comment by kawaiiz** [comment]
点击列表中某一条的时候这个index才会确定，怎么提前写？
