### ISSUE TITLE
对于获取 Form 组件所有字段的初始值加改动后的值有什么好的方法。

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#18660]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我不关心什么状态下，获取到的 fieldsValue 都是最新的。而不是第一次渲染的 undefined。

### What does the proposed API look like?
我写了一个例子 https://codesandbox.io/s/fervent-albattani-ipzop

**Comment by dengfuping** [comment]
- 第一次渲染 `getFieldsValue` 肯定获取不到初始值的，因为 `getFieldsValue` 和初始化是在同一次渲染过程里。将 `getFieldsValue()` 与 `initialValue` 列表进行 `merge`，就是你要的 `最新值` 了。

**Comment by qq645381995** [comment]
> * 第一次渲染 `getFieldsValue` 肯定获取不到初始值的，因为 `getFieldsValue` 和初始化是在同一次渲染过程里。将 `getFieldsValue()` 与 `initialValue` 列表进行 `merge`，就是你要的 `最新值` 了。

因为很多时候初始值这样写 initialValue: data.xxx || 1 ，等在定义字段的地方写，就没法 merge 合并了

**Comment by qq645381995** [comment]
能不能让所有字段初始化完毕后，让组件重新 render 一次。

**Comment by qq645381995** [comment]
或者 推荐使用 setFieldsInitialValue 来设置初始值吗?

**Comment by dengfuping** [comment]
> 或者 推荐使用 setFieldsInitialValue 来设置初始值吗?
- 这样也可以，相当于手动触发一次 render。

**Comment by qq645381995** [comment]
> > 或者 推荐使用 setFieldsInitialValue 来设置初始值吗?
> 
> * 这样也可以，相当于手动触发一次 render。

你看下例子，修改了，使用 setFieldsInitialValue 怎么 note 没有值呢？

**Comment by qq645381995** [comment]
![image](https://user-images.githubusercontent.com/7971419/64246472-6c65a200-cf3f-11e9-8315-d5ea277f62fe.png)

这样行不行，第一次到最后了重新 render 一次，然后其 note2 显示出来了 再根据判断字段的多少，再次重新 render。

**Comment by dengfuping** [comment]
- 参考 https://codesandbox.io/s/getfieldsresultvalue-5gxwk 的实现。

**Comment by qq645381995** [comment]
> * 参考 https://codesandbox.io/s/getfieldsresultvalue-5gxwk 的实现。

这种就是要限制使用者 不能再 getFieldDecorator 后面直接写  initialValue

**Comment by qq645381995** [comment]
> * 参考 https://codesandbox.io/s/getfieldsresultvalue-5gxwk 的实现。

你这个实现如果把 Note 的 1 删掉，在输入 1，那 Note 值会是 undefined、Note3 也不会显示。

**Comment by dengfuping** [comment]
- 更复杂的逻辑你可以根据业务上的需求自行处理。

**Comment by qq645381995** [comment]
刚写了自定义 hook

```
```javascript
import { useEffect, useRef, useState } from 'react';

// Form 值变更并且隐藏显示的字段都结束后重新 reload
export const useChangeInitialValueReload = getFieldsValue => {
    const setReload = useState()[1];
    const ref = useRef();

    const values = getFieldsValue();
    useEffect(() => {
        const valuesKeys = Object.keys(getFieldsValue()).join();
        // 字段隐藏显示有变化，才 reload
        if (ref.current !== valuesKeys) {
            ref.current = valuesKeys;
            setReload(r => !r);
        }
    }, [values, getFieldsValue, setReload]);
    return values;
};
```
```


有改动就 render 一次。
