### ISSUE TITLE
Theming individual components impossible

### ISSUE THREAD

**Issue by mucluck** [ant-design/ant-design#18669]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7v146)

### Steps to reproduce
If customize the theme by Ant Design Less variables. 
Impossible override interior component style.

### What is expected?
Full ability to customize a component using the default variables.

### What is actually happening?
Сhanging color, font size etc. 
Minor changes in appearance.

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.9 |
| System | Mac OS Mojave |
| Browser | Chrome 76.0.3809.132 |

**Comment by dengfuping** [comment]
- You should customize `less variables` inherited by `interior component` instead of modifying CSS style.

**Comment by keithort** [comment]
@mucluck check the list of exposed variables to customize: https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L41
