### ISSUE TITLE
Select doesn't allow creating custom options in single select mode

### ISSUE THREAD

**Issue by shuotongli** [ant-design/ant-design#18674]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Custom options are only allowed under 'tag' mode. For 'default' mode, the user wants to create custom options as well. Like react select: https://react-select.com/home#creatable

### What does the proposed API look like?
It'll look similar to single select but when searching for the option and it's not in the dropdown, it'll be created. Like this: Creatable Example https://react-select.com/home#creatable

**Comment by dengfuping** [comment]
- It's by design that `creatable` is only for `tags` mode.

**Comment by shuotongli** [comment]
> * It's by design that `creatable` is only for `tags` mode.

Is there a reason why we cannot create custom option in `default` mode like react-select?

**Comment by Lantianyou** [comment]
@dengfuping Hi, do you mind me reopening the issue? 
However, `tags` mode by default allow multiple options, but `react-select` createable can work for single option.
