### ISSUE TITLE
版本信息不一致问题

### ISSUE THREAD

**Issue by enjoy-wind** [ant-design/ant-design#18676]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/table-cn/](https://ant-design.gitee.io/components/table-cn/)

### Steps to reproduce
我看更新日志Antd3.0.0版本table组件有onCell属性事件，实际依赖包结果没有，请问具体哪个版本有。

### What is expected?
有

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 15.6 |
| System | 无 |
| Browser | 无 |

**Comment by dengfuping** [comment]
- `onCell` 是设置在 `column` 上的，参考 https://codesandbox.io/s/old-architecture-3bh8m.

![image](https://user-images.githubusercontent.com/14918822/64306687-3a4b5300-cfc6-11e9-841e-177222dcdff6.png)
