### ISSUE TITLE
Form without getFieldDecorator show error on console on pressing "Enter" button

### ISSUE THREAD

**Issue by tonywei92** [ant-design/ant-design#18672]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-validate-static](https://ant.design/components/form/#components-form-demo-validate-static)

### Steps to reproduce
on any text input, press enter, and it will show you error on browser's console

### What is expected?
the error message would be:

Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:formatted:31172)
    at HTMLFormElement.formKeydownListener (onloadwff.js:formatted:31084)

### What is actually happening?
don't know yet

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.9.0 |
| System | Ubuntu 19.04 |
| Browser | Chrome Latest |

---
please fix ASAP

**Comment by dengfuping** [comment]
- Would you give a GIF picture to show it? Because it's not reproducible here.
