### ISSUE TITLE
table columns render 怎么调用父级this方法？

### ISSUE THREAD

**Issue by ansonchen** [ant-design/ant-design#1867]
比如：
```javascript
let columns =[{
  title: 'name',
  dataIndex: 'name',
  render(text,i) {
   return (<a href="javascript:void(0)" onClick={this.ModelFn.bind(null,i)}  >{text}</a>);
}]
```
如果把ModelFn写在这个render里，不是每行都会增加一个Model ?
如果写在父级
```javascript
let test = React.createClass({
 ModelFn(i){
console.log(i)
},
render(){

return(
<div>
  <Model .../>
  <Table columns={columns } dataSource={data} pagination={pagination}/>
</div>

)
}

})

```

columns 里的 `onClick` 应该怎么写才能调到 test 的` ModelFn` ？

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/1762

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
