### ISSUE TITLE
Radio组件，disable 情况下 border颜色样式问题

### ISSUE THREAD

**Issue by hytStart** [ant-design/ant-design#18679]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://hytstart.github.io/react](https://hytstart.github.io/react)

### 引入`antd`的`Radio`组件，使用`disabled`的情况下（`Radio.Group`中第二个为默认选中）。会出现蓝色border。

``` javascript
import { Radio } from 'antd'

 <Radio.Group disabled defaultValue="b" size="large">
    <Radio.Button value="a">Hangzhou</Radio.Button>
    <Radio.Button value="b">Shanghai</Radio.Button>
    <Radio.Button value="c">Beijing</Radio.Button>
    <Radio.Button value="d">Chengdu</Radio.Button>
</Radio.Group>
```

### 效果如图（放大一定倍数），发现默认选中，左侧border有蓝色背景。（不清晰，但是可以发现一点点）

![](https://user-gold-cdn.xitu.io/2019/9/5/16cff435707b5e52?w=1531&h=718&f=png&s=129321)

### 蓝色可能不太明显，换成红色试试看

![](https://user-gold-cdn.xitu.io/2019/9/5/16cff4458bba0fbd?w=1304&h=721&f=png&s=127200)

### 修改：

```
.ant-radio-button-wrapper-checked.ant-radio-button-wrapper-disabled:not(:first-child)::before {
    background-color: #d9d9d9 !important;
}
```

### 如图，可见问题解决

![](https://user-gold-cdn.xitu.io/2019/9/5/16cff4acb3781b53?w=1434&h=666&f=png&s=106940)

### What is expected?
::before伪元素在`disabled`情况下，显示正常颜色。

### What is actually happening?
::before伪元素在`disabled`情况下，被正常选中情况下的样式覆盖。

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | v16 |
| System | windows |
| Browser | chrome 版本 70.0.3538.77（正式版本） （64 位） |

**Comment by dengfuping** [comment]
- @hytStart 能否给一个 `CodeSandbox` 的例子，目前 https://codesandbox.io/s/eloquent-dawn-7r2ss 无法重现这一问题。

**Comment by xrkffgg** [comment]
@hytStart 你可以直接提PR啦

**Comment by hytStart** [comment]
sorry，看了下，3.18.x  3.19.x, 会有这个问题，抱歉刚才选错版本好了，你选的好像是4.X。[https://codesandbox.io/s/goofy-mclean-6u0zw](https://codesandbox.io/s/goofy-mclean-6u0zw)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/17775

https://ant.design/changelog-cn#3.20.6

**Comment by hytStart** [comment]
@dengfuping sorry，看了下，3.18.x  3.19.x, 会有这个问题，抱歉刚才选错版本好了，你选的好像是4.X。[https://codesandbox.io/s/goofy-mclean-6u0zw](https://codesandbox.io/s/goofy-mclean-6u0zw)

**Comment by hytStart** [comment]
@afc163 偏右老哥还是稳
