### ISSUE TITLE
打印Description列表生成的页面，边框会消失

### ISSUE THREAD

**Issue by YvonneZh128** [ant-design/ant-design#18687]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://iiot-next.boranet.cn](http://iiot-next.boranet.cn)

### Steps to reproduce
使用Descriptions列表生成的报告类页面，选择打印，想打印出当前页面，打印预览显示的页面上边框类会消失；

### What is expected?
使用Descriptions列表生成的报告类页面，选择打印，想打印出当前页面，打印预览显示的页面上边框还在

### What is actually happening?
使用Descriptions列表生成的报告类页面，选择打印，想打印出当前页面，打印预览显示的页面上边框类会消失

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8 |
| System | macOS/windows10 |
| Browser | chrome/IE10以上 |

**Comment by dengfuping** [comment]
- @YvonneZh128 Could give an image to show it? Your link is not reproducible.

**Comment by YvonneZh128** [comment]
Hi, 
感谢您可以帮助我，下面给出了一些我的问题描述截图：


1. 追溯报告给出的是一个使用 Description 列表组件生成的一个报告页面，点击打印可以弹出浏览器的打印预览，预览界面是第二张图，失去了边框，










At 2019-09-06 10:36:04, "诸岳" <notifications@github.com> wrote:

@YvonneZh128 Could give an image to show it? Your link is not reproducible.

**Comment by YvonneZh128** [comment]
![image](https://user-images.githubusercontent.com/32048607/64398276-ccbb2780-d096-11e9-970c-70240b2962f2.png)

![image](https://user-images.githubusercontent.com/32048607/64398257-b44b0d00-d096-11e9-8ee5-228974ad7970.png)

**Comment by dengfuping** [comment]
- 但在 `Descriptions` 的这个 [demo](https://codesandbox.io/s/vigilant-grothendieck-wtwby) 中，边框效果是保留的，不知道是否为浏览器版本的原因。

![image](https://user-images.githubusercontent.com/14918822/64399453-1ad22a00-d09b-11e9-9f1e-44150e5d59af.png)

**Comment by YvonneZh128** [comment]
是我用的打印组件有问题，不是组件的问题，get了，感谢。
在 2019-09-06 11:45:51，"诸岳" <notifications@github.com> 写道：

但在 Descriptions 的这个 demo 中，边框效果是保留的，不知道是否为浏览器版本的原因。
