### ISSUE TITLE
form的getFieldDecorator和Table components body wrapper冲突

### ISSUE THREAD

**Issue by OnPure** [ant-design/ant-design#18682]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可编辑表格 页尾添加，如添加总计功能

### What does the proposed API look like?
无

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
