### ISSUE TITLE
巨坑：怎么解决清除form.validateFields的缓存问题??

### ISSUE THREAD

**Issue by 520github198** [ant-design/ant-design#18681]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://5hsgs.csb.app/](https://5hsgs.csb.app/)

### Steps to reproduce
点击3次Add field按钮之后，再删除最后1个新增的input框，keys=[0,1],但是为什么没有删除names(2)呢？ 

### What is expected?
keys=[0,1],应该同时删除names(2)！！！！ 

### What is actually happening?
keys=[0,1],但是为什么没有删除names(2)呢？ 

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.8.6 |
| System | mac 10.14.6 |
| Browser | 火狐开发者版本 |

---
项目紧急，求助！！！！！！！！十万火急！！！！！

**Comment by dengfuping** [comment]
- @520github198 请给出带源码的例子，而不是构建好的页面。

**Comment by outNapGnaw** [comment]
> * @520github198 请给出带源码的例子，而不是构建好的页面。

[https://codesandbox.io/s/5hsgs](https://codesandbox.io/s/5hsgs)
文档demo的render 里增加了一行
`console.log(1123, this.props.form.getFieldsValue())`

**Comment by afc163** [comment]
render 之后才知道第三个元素被清空了，例子中 getFieldsValue 执行的时机是在 render 之前。你点击提交就会发现 `names{2}` 没了。

需要同步拿到数据的话，建议监听 onValuesChange。
