### ISSUE TITLE
Rc-menu@7.4.23 crashed after menu unmounted

### ISSUE THREAD

**Issue by yoonthe** [ant-design/ant-design#18689]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-black-bk3xc)

### Steps to reproduce
在menu被unmount后又更新了对应的dom，会导致react尝试获取对应的dom报错，菜单对应的dom如何被泄露的暂时还不清楚，报错在DomWrap.js

### What is expected?
不会报错

### What is actually happening?
react报错导致页面崩溃

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome 76.0.3809.132 |

---
目前使用antd pro在退出到登录时，将BasicLayout 移除并加载LoginLayout时会遇到这个问题

**Comment by yoonthe** [comment]
![image](https://user-images.githubusercontent.com/17765956/64331400-502c3880-d005-11e9-9480-f4d64211944b.png)
![image](https://user-images.githubusercontent.com/17765956/64331415-56221980-d005-11e9-91aa-788a9a4240b9.png)

**Comment by yoonthe** [comment]
mutationObserver 未在 `unmount` 时正常取消监听，并且在响应函数中引用了 `ReactDom.findNode` 这种依赖于组件绑定的函数

**Comment by afc163** [comment]
Try rc-menu@7.4.28
