### ISSUE TITLE
inputValue, autoClearSearchValue, not working on Select component

### ISSUE THREAD

**Issue by denvash** [ant-design/ant-design#18683]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-bug-nrsy3)

### Steps to reproduce
Type in any `Select` box

### What is expected?
Persist search value after losing focus.

### What is actually happening?
The search value is cleared

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.9.0 |
| System | Ubuntu 19.04 |
| Browser | Version 76.0.3809.132 (Official Build) (64-bit) |

---
Tried to display the search value in case of losing a focus of the `Select` box,
using `inputSearch` and `searchValue`.

- Related [PR?](https://github.com/ant-design/ant-design/pull/18629)

Tried on several `3.x` versions and still won't work.

**Comment by dengfuping** [comment]
- It's by design and we have no plan to change this behavior.

**Comment by denvash** [comment]
In such a case, is there any use case for `inputValue` at `Select` component?

**Comment by dengfuping** [comment]
- I just found that `searchValue` is persisted when `option` is selected and `autoClearSearchValue` is `true`.  Maybe it could be supported also when Select is blur. We need a discussion about it.

**Comment by denvash** [comment]
> * I just found that `searchValue` is persisted when `option` is selected and `autoClearSearchValue` is `true`.  Maybe it could be supported also when Select is blur. We need a discussion about it.

Tried and couldn't reproduce, any reference, please?

**Comment by dengfuping** [comment]
- See https://codesandbox.io/s/select-bug-zq4pw.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/19003
