### ISSUE TITLE
Antd form custom validation

### ISSUE THREAD

**Issue by piby180** [ant-design/ant-design#18693]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/misty-violet-xgp2d?fontsize=14)

### Steps to reproduce
Please check the above link

### What is expected?
1. ) Error feedback at the bottom of the field when the validator fails
2) Submit the form when validator succeed

### What is actually happening?
Unable to submit the form. No error feedback

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16,9 |
| System | Windows |
| Browser | Chrome |

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/64338178-b15b0880-d013-11e9-9e43-ce731322289d.png)

```js
// validateStatus={turbineCountError ? "error" : ""}
// hasFeedback
```

**Comment by piby180** [comment]
Ok, so the error was that I was not calling the callback in the try block. 

```
validator(rule, value, callback) => {
  try {
   if (condition) {
        throw new Error('Something wrong!');
    }
    callback() // < -- this
  } catch (err) {
    callback(err);
  }
}
```
