### ISSUE TITLE
I need instructions for the Menu component upgrade

### ISSUE THREAD

**Issue by walk-liuyan** [ant-design/ant-design#18696]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
**Story background：**
when my package.json file 's antd version from 2.12.X upgrade to 3.3.3,
1、 i found menu component the secondary menu is lower than the primary menu 4px？
2、 i found the last menu in the secondary menu floats upward, and the penultimate menu floats downward. in 2.12.x all floats downward。
I would like to get a antd compontns design document～～

**Why would I ask that?**
In the past, when I used the menu component, I would dynamically calculate the marginBottom of menu. After the upgrade and when the last level menu is opened, the distance of the marginBottom is redundant.
Look at the picture：
![image](https://user-images.githubusercontent.com/24427505/64336370-5b846180-d00f-11e9-9250-017de5472025.png)

**END:**
You guys helped me decide and calculate distance very friendly but it affected my previous UI.
I would like to get a antd compontns design document～～

### What does the proposed API look like?
I would like to get a antd compontns design document～～

**Comment by dengfuping** [comment]
- The [migration guide](https://ant.design/changelog#%E2%9A%A0%EF%B8%8F-Read-it-before-migration) from 2.x to 3.x maybe help you that.
