### ISSUE TITLE
The column render function defines the getFieldDecorator in the editable state，input box focus on the problem

### ISSUE THREAD

**Issue by OnPure** [ant-design/ant-design#18699]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-pkxnp?fontsize=14)

### Steps to reproduce
I don't know why codesandbox won't run, but the code does run.

### What is expected?
Input box can continue to get focus

### What is actually happening?
Unable to get focus, just remove getFieldDecorator

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.7.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
We need a runnable codesandbox to confirm and debug.

**Comment by OnPure** [comment]
> Hello @OnPure. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @OnPure, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966

创建组件引用会报错，不知道什么原因
