### ISSUE TITLE
menu className didn't pass to popup while the old version did

### ISSUE THREAD

**Issue by kuitos** [ant-design/ant-design#18703]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-submenu-margin-issue-le8dc)

### Steps to reproduce
1. hover navigation one and popup showed
2. popup not margin left as the class name at SubMenu not passed through

### What is expected?
popup margin left with the css specified, the behavior is correct with antd 3.16.5, see https://codesandbox.io/s/antd-submenu-margin-issue-q3i0t 

### What is actually happening?
popup not margin left

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | latest |
| System | osx 10.14.6 |
| Browser | chrome 76 |

**Comment by jljsj33** [comment]
旧版是错误的，，className 本来就不应该传递给 popup

**Comment by jljsj33** [comment]
popup className use `popupClassName `,  className is item class
