### ISSUE TITLE
Button: link: should have the dimensions of it's contents

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#18704]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Problem: button has implicit height, width, margin and padding. When using it as a link - it makes a lot of invisible space around it's contents (text, icon, etc) hoverable and clickable. Which is not what a link should have.

### What does the proposed API look like?
Since Ant.d doesn't have an explicit Link component - make `Button: link` behave as `<a>` and not have height, width, margin and padding css.

**Comment by afc163** [comment]
Use `<a />` directly if you need a link text.

**Comment by avalanche1** [comment]
What is the use case for Button Link in it's current edition??

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15826
https://github.com/ant-design/ant-design/issues/15892
