### ISSUE TITLE
Wrong font-size for middle and large round Button

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#18705]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-moon-rpjok)

### Steps to reproduce
- See the demo.
- ![image](https://user-images.githubusercontent.com/14918822/64406979-c4beb000-d0b5-11e9-9063-90a122ea1d69.png)

### What is expected?
- The font-size of middle round Button should be 14px.
- The font-size of middle round Button should be 16px.

### What is actually happening?
- The font-size of middle round Button is 16px.
- The font-size of middle round Button should be 18px.

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.9.0 |
| System | Mac OS |
| Browser | Google Chrome 75.0.3770.100 |

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/pull/18701
