### ISSUE TITLE
表单验证信息，如何不让在控制台显示async-validator: ["name value 534rewrwe does not match pattern /^[a-z,A-Z]\d{6,}$/"]

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#1870]
表单验证信息，如何不让在控制台显示
async-validator: ["name value 534rewrwe does not match pattern /^[a-z,A-Z]\d{6,}$/"]

**Comment by ddcat1115** [comment]
不太明白，请提供下可重现的demo    http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by yiminghe** [comment]
故意的，帮助排查验证
