### ISSUE TITLE
Form page with react ref warning

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#18707]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/507615/64413401-06eeee00-d0c4-11e9-982f-d44af65f5383.png">

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/63b33d4020a8cb0dda7ff80356b3ece6367e7ffb#diff-1a8fbe5646a52f57f1356528b8145bebL7

**Comment by afc163** [comment]
这里很奇怪，按道理 function component 不用 React.forwardRef 会有问题？但是 Dragger 运行好像很正常。@zombieJ 帮忙看看？

**Comment by fireairforce** [comment]
我也很好奇= =

**Comment by fireairforce** [comment]
函数式组件如果用form.create包裹之后，然后父组件利用hooks API去调用子组件的方法，调用不到QAQ
