### ISSUE TITLE
ie浏览器下，如果指定组件渲染的容器即调用getPopupContainer， 组件获取焦点以后会导致页面闪烁

### ISSUE THREAD

**Issue by xuwenjia** [ant-design/ant-design#18714]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://bigdata.autohome.com.cn/smartRD/assert/#/RdCompete](https://bigdata.autohome.com.cn/smartRD/assert/#/RdCompete)

### Steps to reproduce
ie浏览器下指定组件父容器

### What is expected?
不闪烁

### What is actually happening?
获取焦点就会闪烁

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16以上 |
| System | windows |
| Browser | ie |

**Comment by yoyo837** [comment]
We need a runnable codesandbox to confirm and debug.

**Comment by afc163** [comment]
可以帮忙排查一下么

**Comment by xuwenjia** [comment]
> We need a runnable codesandbox to confirm and debug.

ie cant open codesandbox

**Comment by xuwenjia** [comment]
> 可以帮忙排查一下么

ie 打不开在线链接。。。，有滚动条的时候需要指定父容器这个时候ie就会闪烁

**Comment by wongfugui** [comment]
> > 可以帮忙排查一下么
> 
> ie 打不开在线链接。。。，有滚动条的时候需要指定父容器这个时候ie就会闪烁

老哥，我也碰到一样的问题了，你是怎么解决的？

**Comment by stupid2013** [comment]
> > 可以帮忙排查一下么
> 
> ie 打不开在线链接。。。，有滚动条的时候需要指定父容器这个时候ie就会闪烁

@xuwenjia 请问你们解决这个问题了吗  我也遇到了 如果你们已经解决的话 能不能分享一下 谢谢～

**Comment by wufeng87** [comment]
你们ie都不注明版本吗？我这边是ie11有这个问题。原因还不明。

**Comment by lidaguang1989** [comment]
```
<div class="blink-class">
  <Select
	defaultValue="lucy"
	style={{ width: 120 }}
	getPopupContainer={(trigger) => trigger.parentNode}
  >
	<Option value="jack">Jack</Option>
	<Option value="lucy">Lucy</Option>
	<Option value="yiminghe">yiminghe</Option>
  </Select>
</div>
```
然后对父组件添加伪元素样式：
```
.blink-class:after{
  content: '';
  position: fixed;
  display: block;
}
```

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/21039

**Comment by liqin1059** [comment]
我也遇到了好烦
