### ISSUE TITLE
Tooltip display bug

### ISSUE THREAD

**Issue by azl397985856** [ant-design/ant-design#1871]
![image](https://cloud.githubusercontent.com/assets/12479470/15597367/eb769082-2401-11e6-8fa8-74970a5fb51c.png)
I added a span tag surrounded with Tooltip, it woked fine, but when the span remove from the dom, the Tooltip wont disapear at once, goes to the (0,0) point instead.
![image](https://cloud.githubusercontent.com/assets/12479470/15597432/6cd23096-2402-11e6-8d56-e7e2c46bc6db.png)

I think it should disappear with the removed dom.

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by azl397985856** [comment]
http://codepen.io/anon/pen/bebyvr?editors=0011#anon-signup

**Comment by afc163** [comment]
http://codepen.io/anon/pen/bebyvr?editors=0011

默认 Tooltip 是渲染到 body 的，可以加一个 getTooltipContainer 属性改成渲染到父元素上。

**Comment by azl397985856** [comment]
谢谢，不过还是希望你们可以在antd 官网API后面附上   更多api 请参考：（一个地址，指向rc的）。

**Comment by azl397985856** [comment]
就像这样：
![image](https://cloud.githubusercontent.com/assets/12479470/15599771/19c0af84-2418-11e6-8927-e5950eabba79.png)

**Comment by azl397985856** [comment]
其实还是有问题的、
以下是你门rc-trigger源码：
componentWillUnmount: function componentWillUnmount() {
    var popupContainer = this.popupContainer;
    if (popupContainer) {
      _reactDom2['default'].unmountComponentAtNode(popupContainer);
      if (this.props.getPopupContainer) {
        var mountNode = this.props.getPopupContainer();
        mountNode.removeChild(popupContainer); // 这一步没有加判断。如果我的mountNode被我移除了，比如display：none   你就会报错
      } else {
        document.body.removeChild(popupContainer);
      }
      this.popupContainer = null;
    }
    if (this.delayTimer) {
      clearTimeout(this.delayTimer);
      this.delayTimer = null;
    }
    if (this.clickOutsideHandler) {
      this.clickOutsideHandler.remove();
      this.touchOutsideHandler.remove();
      this.clickOutsideHandler = null;
      this.touchOutsideHandler = null;
    }
  },
