### ISSUE TITLE
Tree组件设置showLine属性后switcherIcon属性不起作用

### ISSUE THREAD

**Issue by baizn** [ant-design/ant-design#18717]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义Tree组件的样式：支持虚线和实线两种样式，并且当设置showLine属性为true后，支持switcherIcon属性。

### What does the proposed API look like?
增加一个lineType属性，默认为dashed，可选项为dashed 和 solid，分别表示虚线和实线。

预览效果如下：
![image](https://user-images.githubusercontent.com/9443867/64423813-f6497280-d0d9-11e9-803b-dcff8ff61378.png)

**Comment by dengfuping** [comment]
- 需求一: `showLine=true` 时也需要能自定义图标，目前 `switcherIcon` 是不生效的。
- 需求二: `showLine=true` 时，期望 `同级节点` 收起时，节点之间没有 `line` 连接，展开后有 `line` 连接。目前 Tree 组件的 `同级节点` 展开和收起均有 `line` 相连。
- 展开:
![image](https://user-images.githubusercontent.com/14918822/64425388-2abf2d80-d0de-11e9-8f62-3c8a52b9d502.png)
- 收起:
![image](https://user-images.githubusercontent.com/14918822/64425407-36aaef80-d0de-11e9-8ef1-23164d48e5c8.png)

**Comment by baizn** [comment]
@dengfuping 需求2中，收起后的连线要是能做成可配置的，那就更完美了！

**Comment by kener** [comment]
路过，帮顶~
