### ISSUE TITLE
FormItem colon disappers on responsive layout(grid)

### ISSUE THREAD

**Issue by hugobarragon** [ant-design/ant-design#18719]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7twl5)

### Steps to reproduce
Form items with a responsive layout like this:

```javascript
const formItemLayout = {
      labelCol: {
        xs: { span: 24 },
        sm: { span: 8 },
      },
      wrapperCol: {
        xs: { span: 24 },
        sm: { span: 16 },
      },
    };
```  
Open the running page on a new window and resize until the inputs go below the labels (mobile devices)
When reduce to mobile the inputs break a line down, witch is good, but the ':' colon disappears

### What is expected?
on mobile and desktop, only the layout changes, so if the colon=true it should keep the ':' on mobile

### What is actually happening?
the ':' disappears  
![colon-disapers](https://user-images.githubusercontent.com/35630927/64435426-5defc580-d0ba-11e9-8bbf-1b9fe0f157a5.gif)

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.1.1 |
| System | Windows 10 |
| Browser | Google Chrome Version 76.0.3809.132 (Official Build) (64-bit) |

---
we use antd for 2 years on internal projects

**Comment by afc163** [comment]
It is by designed, vertical layout don't have colon.

**Comment by hugobarragon** [comment]
> It is by designed, vertical layout don't have colon.
 1º the repo layout is `'horizontal'`, only the grid system|css changes it
 2º  where is that written at? 
`colon | change default props colon value of Form.Item | boolean | true`

consider reopening, and if its feature update the DOCS?

**Comment by delphin92** [comment]
> It is by designed, vertical layout don't have colon.

Ok, it can be default behavior. But why I can change it and force vertical form to have colons?

I can write this:
```
<Form
  layout="vertical"
  colon={true}
>
```
And this:
```
<Form.Item
  colon={true}
>
```
But no one works as expected.

Please, reopen this issue.

**Comment by delphin92** [comment]
WA:

```css
.with-colons.ant-form-vertical .ant-form-item-label > label::after {
  &:extend(.ant-form-item-label > label::after);
  display: block;
}
```
```jsx
<Form className="with-colons">
```
