### ISSUE TITLE
<BackTop/> component not working

### ISSUE THREAD

**Issue by d-ivashchuk** [ant-design/ant-design#18725]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://st3h0.csb.app/](https://st3h0.csb.app/)

### Steps to reproduce
Component seems to be doing nothing neither in the project nor in the codesandbox or codepen

### What is expected?
I expect the icon/button to appear when I scroll the page down beyond the initial viewport

### What is actually happening?
Nothing is happening when I scroll

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.9.0 |
| System | Mac os Mojave  |
| Browser | Latest Chrome |

**Comment by afc163** [comment]
Your reproduce link works fine: https://st3h0.csb.app/

<img width="1439" alt="图片" src="https://user-images.githubusercontent.com/507615/64483125-168b4580-d230-11e9-8143-261a4466502d.png">

**Comment by JonathanSolisCeballos** [comment]
If someone has this same issue it might be due missing antd css. I had the same issue and realize I wasn't importing the antd styles on that component, so I just moved the import to app.jsx
