### ISSUE TITLE
Value prop on Switch, Checkbox, Upload warning

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#18721]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-nash-tfuxc)

### Steps to reproduce
Create a Form using the Switch component.

### What is expected?
No warning if the Switch, Checkbox, or Upload component does not have the value prop set.

### What is actually happening?
Warnings are being thrown even without the value prop existing on the component.

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.7 |
| System | any |
| Browser | any |

---
Issue was introduced in https://github.com/ant-design/ant-design/pull/18497

**Comment by afc163** [comment]
<img width="1130" alt="图片" src="https://user-images.githubusercontent.com/507615/64445322-d2e9ec00-d108-11e9-99ee-50dd56197e5c.png">

Cannot reproduce in your codesandbox.

**Comment by keithort** [comment]
![image](https://user-images.githubusercontent.com/1872665/64445977-aa7cd600-d0a5-11e9-8db9-44dcce8ca84c.png)
```
<Switch
 checkedChildren="Yes"
 unCheckedChildren="No"
 onChange={() => this.onToggleIsHandFigured()}
/>
```
The warnings only show when `process.env.NODE_ENV !== 'production'` and i don't know how to set that on codesandbox.

**Comment by keithort** [comment]
In fact, all of the validation checks are incorrect. They are saying it is invalid if `!('value' in this.props)` the `!` shouldn't be in the validation check.

**Comment by yoyo837** [comment]
Maybe the warning comes from another switcher using `value`. Check your code.

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/64457802-32a2c000-d126-11e9-828c-100ab9346261.png)

**Comment by afc163** [comment]
@yoyo837 is correct.

**Comment by keithort** [comment]
@yoyo837 and @afc163 
I was able to replicate it on a new Sandbox. It seems to be related to setting an initialvalue through getFieldDecorator.
[Reproduction](https://codesandbox.io/s/objective-firefly-s8zg7).

**Comment by Ivocin** [comment]
@afc163  可以复现，楼上的地址就能复现：https://codesandbox.io/s/objective-firefly-s8zg7。
能帮忙看看什么原因么。

**Comment by macc6579** [comment]
answer from here：
https://github.com/ant-design/ant-design/issues/20803
it works for me!

For anyone having this warning as well, I just found the answer in the doc:
https://ant.design/components/form/#components-form-demo-validate-other

<Form.Item name="switch" label="Switch" valuePropName="checked">
  <Switch />
</Form.Item>
Please note the valuePropName="checked"

**Comment by nameJw** [comment]
`
<Form.Item name="avatar" label="头像" valuePropName="fileList">
  <Upload />
</Form.Item>
`
为什么这样写还是有警告？
**Warning: [antd: Upload] `value` is not a valid prop, do you mean `fileList`?**

**Comment by georgeportillo** [comment]
Same issue as above. Anyone know how to fix it?
