### ISSUE TITLE
How to make InputNumber always display ?

### ISSUE THREAD

**Issue by lengockyquang** [ant-design/ant-design#18728]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to make input number always display the spinner instead only hover on it, i think it wiil make UX better
![image](https://user-images.githubusercontent.com/45225905/64485502-d33ed000-d24b-11e9-834a-17e50a8bfb03.png)

### What does the proposed API look like?
add spinner-display prop

**Comment by afc163** [comment]
You have to override antd orignal styles.
