### ISSUE TITLE
Add an "onClickOutside" callback to any persistent popups, like Popover and Popconfirm

### ISSUE THREAD

**Issue by aej11a** [ant-design/ant-design#18730]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My site involves opening a popover with a form inside of it. Instead of / alongside with clicking a close button, users expect to be able to click outside the popover to close it.
My specific use case would be setting the popover's visibility to false.

### What does the proposed API look like?
`<Popover onClickOutside={ () => { console.log("Clicked outside!" } }> {content}</Popover>`

**Comment by aej11a** [comment]
@yutingzhao1991 I took a quick look at the code, looks to me like this would involve adding the prop to the `Tooltip` component.

If you're interested in this feature, I can work on implementing it. Please let me know.

**Comment by afc163** [comment]
`onVisibleChange` is what you are looking for.

**Comment by aej11a** [comment]
@afc163 I don't think so... wouldn't that **respond** to a visibility change? I'm talking about adding `onClickOutside` for the purpose of changing the visibility. for example `onClickOutside={toggleVisibility}`

I realize now this is the same as `onVisibleChange` for Tooltips, but it's not the same for persistent popups like Popover and Popconfirm

**Comment by ashah2193** [comment]
@aej11a Hello, did you find any solution for this issue?

**Comment by aej11a** [comment]
@ashah2193 Nope, nothing. Hoping @afc163 will respond again

**Comment by standbyoneself** [comment]
Any plans on implementation?
