### ISSUE TITLE
希望modal能使用高度百分比

### ISSUE THREAD

**Issue by nlx0201** [ant-design/ant-design#18738]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
modal无法设置高度百分比，导致modal高度超出页面高度

### What does the proposed API look like?
height="70%"

**Comment by ycjcl868** [comment]
手动用样式控制下内容区域的高度：


```diff
   <Modal
          title="20px to Top"
          style={{ top: 20, height: '70vh' }}
          visible={this.state.modal1Visible}
          onOk={() => this.setModal1Visible(false)}
          onCancel={() => this.setModal1Visible(false)}
        >
+       <div style={{ height: '60vh', overflowY: 'auto' }}>
            <p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p><p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p>

            <p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p>
            <p>some contents...</p><p>some contents...</p>
            <p>some contents...</p><p>some contents...</p>
+       </div> 
        </Modal>
```

**Comment by nlx0201** [comment]
试过

> 手动用样式控制下内容区域的高度：
> 
> ```diff
>         <Modal
>           title="20px to Top"
>           visible={this.state.modal1Visible}
>           onOk={() => this.setModal1Visible(false)}
>           onCancel={() => this.setModal1Visible(false)}
>         >
> +       <div style={{ height: '60vh', overflowY: 'auto' }}>
>             <p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p><p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p>
> 
>             <p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p>
>             <p>some contents...</p><p>some contents...</p>
>             <p>some contents...</p><p>some contents...</p>
> +       </div> 
>         </Modal>
> ```

试过，但是没有用处，主要是外部modal无法设置高度，内部设置百分比没有参考依据，所以无法生效

**Comment by ycjcl868** [comment]
Modal 的高度根据内部来的

**Comment by nlx0201** [comment]
你可以尝试下，内部高度使用百分比是无效的，这个时候modal的高度会自适应。问题在于当我在一个页面使用modal的时候，我并不知道用户浏览器是多高，所以如果设置modal内部内容的高度的话，会导致页面内部出现一个滚动条，modal自身也会出现滚动条，滚动鼠标滑轮的时候两者会同时滚动，体验效果不好

**Comment by afc163** [comment]
可以使用 `height: calc(100vh - 200px)`

**Comment by nlx0201** [comment]
希望增加一个可以设置modal整体高度百分比的属性，类似width的
