### ISSUE TITLE
ConfigProvider locale do not work in first time

### ISSUE THREAD

**Issue by drmflying** [ant-design/ant-design#18731]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/](https://ant.design/components/config-provider-cn/)
<img width="554" alt="WX20190909-093046@2x" src="https://user-images.githubusercontent.com/3291182/64498117-9b846680-d2e5-11e9-9f3f-bd0887ba5bb7.png">

### Steps to reproduce
when init

### What is expected?
it is not work

### What is actually happening?
it is work

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | react |
| System | mac os |
| Browser | chrome |

**Comment by yoyo837** [comment]
ref: #15260

**Comment by drmflying** [comment]
https://ant.design/components/config-provider-cn/

**Comment by yoyo837** [comment]
@afc163 先访问主页https://ant.design 再点菜单到 config-provider-cn , 能看到

**Comment by yoyo837** [comment]
直接访问 https://ant.design/components/config-provider-cn/ 不会看到

**Comment by ycjcl868** [comment]
https://github.com/umijs/umi/issues/3088#issuecomment-527082934

**Comment by ycjcl868** [comment]
> @afc163 先访问主页https://ant.design 再点菜单到 config-provider-cn , 能看到

没能复现

**Comment by yoyo837** [comment]
1.  新window访问https://ant.design进入主页，勿在原页面点主页菜单。
2. 点击“开始使用”
3. 点击菜单“ConfigProvider全局化配置”

百分百复现。

**Comment by yoyo837** [comment]
之前切换到了英文的话，先切一次中文，再按上方步骤重试；

**Comment by afc163** [comment]
感谢反馈，感觉能解决不少 Modal 国际化失效的问题。
