### ISSUE TITLE
jest mock validateFields

### ISSUE THREAD

**Issue by LuJiaNan** [ant-design/ant-design#18735]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
validateFields 的单元测试
有没有用jest mock 的写法

### What does the proposed API look like?
validateFields((errors, values) => {
  // ...
});
validateFields(['field1', 'field2'], (errors, values) => {
  // ...
});
validateFields(['field1', 'field2'], options, (errors, values) => {
  // ...
});

**Comment by shaodahong** [comment]
可以换个思路，mock cb，像这样

```js
const cb = jest.fn()

validateFields(cb);

expect(cb.mock.calls).toEqual([null, values]);
```
