### ISSUE TITLE
input输入框希望添加tag功能，类似select下拉框里的tag，或者select框在tag模式下可以固定高度，超过时出现滚动条

### ISSUE THREAD

**Issue by lanll** [ant-design/ant-design#1873]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

---

提问之前，建议先阅读[这份提示](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question)。:-)

如果是报告 bug，请按照下列格式编辑问题，务必提供复现步骤，否则恕难解决，非常感谢！

## 你做了什么？

（例如，我吃了一个汉堡）

## 你期待的结果是：

（例如，我应该饱了）

## 实际上的结果和抱怨：

（例如，我还是饿的，肯定是哪里出问题了）

## 可重现的在线演示

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## 本地环境信息

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by ddcat1115** [comment]
可以考虑在 `Select` `tag` 模式的基础上自己做样式覆盖

**Comment by yourenA** [comment]
@ddcat1115 请问一下如何才能使tag模式不支持多选

**Comment by yesmeck** [comment]
@yourenA You can ask questions on https://segmentfault.com/t/antd
