### ISSUE TITLE
Add a "size" property to the Tag API

### ISSUE THREAD

**Issue by dylanavery720** [ant-design/ant-design#18745]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allows Tag to be used more dynamically inside of table rows, or description lists for instance. Allows Tag to behave more like Button, or other components which have a size property. 

### What does the proposed API look like?
"size - "can be set to small large or omitted" /	string / default

Small tag would fit in small table row.

**Comment by afc163** [comment]
There is no `size` for Tag in design.

**Comment by dylanavery720** [comment]
> There is no `size` for Tag in design.

Can I add this property to the API then? I can make a pull request.

**Comment by afc163** [comment]
In our design specificity, we don't provider differece size of Tags. You can customize your own Tag component based on our Tag.
