### ISSUE TITLE
希望Transfer支持自定义title

### ISSUE THREAD

**Issue by Mu-xue** [ant-design/ant-design#18740]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Transfer的标题有时显示的信息不单单是一个string，如果能支持ReactNode，会更加方便

### What does the proposed API look like?
<Transfer titles={(option: 'left' | 'right') => ReactNode} />

**Comment by afc163** [comment]
支持的：https://codesandbox.io/s/nostalgic-goldwasser-7t8xh

**Comment by Mu-xue** [comment]
> 支持的：https://codesandbox.io/s/nostalgic-goldwasser-7t8xh

当使用typescript时，由于titles的类型被声明为string[]，因此会报错

**Comment by afc163** [comment]
@Mu-xue 我上面改了文档，ts 的问题可以来个 PR

**Comment by Homebrew1** [comment]
for Vue的可以给个codesandbox吗，光加button，无法加事件没用的
