### ISSUE TITLE
table组件固定头或者列，外边框显示不全

### ISSUE THREAD

**Issue by jiangzm** [ant-design/ant-design#18742]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/currying-pond-dhfnl)

### Steps to reproduce
设置table组件显示边框，固定头或列，在之前（升级mac系统）table会默认显示滚动条，升级之后没有默认显示滚动 鼠标移动会出现虚拟滚动条，并且左边和下面外边框不显示。

-我猜测可能和系统级别的虚拟滚动条有关（在`系统-通用`能找到相关设置），所以在默认不显示滚动条情况下边框应该完整展示

### What is expected?
1、默认显示滚动条情况下，能看到外边框
2、默认不显示滚动条（虚拟滚动条），同样能看到外边框

### What is actually happening?
默认不显示滚动条情况下，鼠标移动有虚拟滚动条，左边和下面外边框不显示

(不显示外边框)
![WX20190909-200013](https://user-images.githubusercontent.com/1632856/64529211-f4cbb480-d33c-11e9-80af-d16a0a378a2f.png)

(显示外边框)
![WX20190909-200134](https://user-images.githubusercontent.com/1632856/64529223-fbf2c280-d33c-11e9-86c1-daff04a2439c.png)

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | React 16.9 |
| System | macOS 10.14.6 |
| Browser | Chrome 76.0.3809.132 |

**Comment by afc163** [comment]
Duplicate of #17674

**Comment by jiangzm** [comment]
不是系统升级影响的，区别在插了外置鼠标和使用触摸板。
之前一直用鼠标 页面默认有滚动条， 昨天没用鼠标用触摸板，页面没有默认滚动条（有虚拟滚动条），导致table组件边框不显示问题。需要组件兼容系统虚拟滚动条也显示外边框。

**Comment by szpilm** [comment]
将position设置为绝对定位可解决问题
