### ISSUE TITLE
Tree能否做到第一次点击时能获取到选中的key，第二次点击不取消？

### ISSUE THREAD

**Issue by DragonCJ** [ant-design/ant-design#18749]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
点击树节点展开/收缩节点，比如奇数次点击展开节点，偶数次点击收缩节点，现在onselect中返回的参数，第一次点击没问题，第二次点击就为空了，取消选中了

### What does the proposed API look like?
奇数次点击展开节点，偶数次点击收缩节点，而不是取消选中

**Comment by DragonCJ** [comment]
onselect能获取到当前节点信息，然后该节点的key操作展开还是收缩

**Comment by UnicornXU** [comment]
大佬  最后解决了么

**Comment by yoyo837** [comment]
受控模式应该可以

**Comment by UnicornXU** [comment]
> 受控模式应该可以
  官网例子,受控操作也是一样,第二次操作是取消当前选择,想问该怎么处理

**Comment by yoyo837** [comment]
受控了就自己控制key。想怎么控制就怎么控制。
