### ISSUE TITLE
RangePicker组件Calendar面板的显示问题

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#1874]
在使用RangePicker的时候，我们有这样一个需求。
当日历面板打开时，不要挡住输入框。
也就是：1、当日历面板向上打开时，日历面板的底部与input框的顶部对齐。
             2、当日历面板向下打开时，日历面板的顶部与input框的底部对齐。

**Comment by afc163** [comment]
这个暂时不支持了，之前这样的交互有很多历史原因，现在改起来比较费劲。感谢建议。
