### ISSUE TITLE
让Modal组件能够感知它的子组件的相关API

### ISSUE THREAD

**Issue by hLinx** [ant-design/ant-design#18744]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在业务开发中当Modal的子组件是一个Form时，确定按钮对应Form的提交操作，取消按钮对应Form的重置操作，如果Modal通过约定的方式能自动感知Form的相关操作API，开发者就可以减少大量为映射这种关联而消耗的时间。更详细的问题说明（因为有点多）如果愿意可以查看https://juejin.im/post/5d748b836fb9a06b0a279a3f

### What does the proposed API look like?
```
<Modal>
  <RegisterForm />
</Modal>
```
组件RegisterForm有submit，reset方法。Modal组件可以在componentMounted时获取子组件实例，当Modal的onOk调用时自动执行子组件的submit，当onCancel调用时自动执行子组件的reset   

> 往往在实际业务开发中，开发者为完成这种映射关系需要做很多重复的工作

**Comment by yoyo837** [comment]
不同的组件有不同的功能API，按什么逻辑决定与Modal 按钮关系？

**Comment by yoyo837** [comment]
你项目的Modal里使用Form的场景较多你可以自己再封装。

**Comment by afc163** [comment]
> 往往在实际业务开发中，开发者为完成这种映射关系需要做很多重复的工作

建议自行封装一个符合自己需求的 FormModal 出来。
