### ISSUE TITLE
DatePicker 受控展示日期不受控

### ISSUE THREAD

**Issue by farzer** [ant-design/ant-design#18759]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-allen-b9fs0)

### Steps to reproduce
1. 先选择一个日期范围
2. 点击关闭后重新打开日期选择面板
3. 只选择开始时间，然后点击关闭
4. 重新打开

### What is expected?
日期选择面板和input上的显示不一致

### What is actually happening?
日期选择面板和input上的显示应该一致

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.9.0 |
| System | MACOS 10.14.5 |
| Browser | Version 76.0.3809.132 (Official Build) (64-bit) |

**Comment by ycjcl868** [comment]
没选结束时间，不会触发 value 改变
