### ISSUE TITLE
校验DatePicker，输出date is not a string

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#1875]
## 场景
1）利用表单校验一个必选的DatePicker
2）选中日期，显示校验失败，控制台提示`async-validator: [date is not a string]`
![image](https://cloud.githubusercontent.com/assets/17123400/15599484/29dc6220-2416-11e6-82ef-7e1bfc17bc0d.png)

## demo
http://codepen.io/hyaaon/pen/BzBerR?editors=1011

## 版本
antd@1.0.1

**Comment by afc163** [comment]
参考这里的例子：http://ant.design/#/components/form?scrollTo=components-form-demo-validate-other

可以到相关 issue 继续讨论：#1515

**Comment by miclay** [comment]
http://ant.design/#/components/form?scrollTo=components-form-demo-validate-other
链接打不开了

**Comment by afc163** [comment]
http://ant.design/components/form/#components-form-demo-validate-other

**Comment by answer185** [comment]
书写rules的时候 ，是不是写成rule: [ condition && {required: true, message: "不能为空"}]， 这种写法会触发上面的错误 ，改成 rules: condition ? [{required:true, message: "不能为空"}] : [] 即可，不知道 你们是不是这种 情况

**Comment by afc163** [comment]
@answer185 可以来个 PR

**Comment by cooper1x** [comment]
正常情况下condition应该写啥 @answer185
我现在是选择任意日期都会出现message提示，表单校验不通过。
