### ISSUE TITLE
Button in selected menu alway be white

### ISSUE THREAD

**Issue by TiaossuP** [ant-design/ant-design#18752]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/staging-framework-j16yh?fontsize=14)

### Steps to reproduce
Just see reproduction link above

### What is expected?
In selected menu, button & span in Popover can display well

Maybe we should not use button & popover in Menu, but at lease,  I think it should not direct use `span` selector without class in less. 

[https://github.com/ant-design/ant-design/blob/master/components/menu/style/dark.less#L111](https://github.com/ant-design/ant-design/blob/master/components/menu/style/dark.less#L111)

### What is actually happening?
text color is #fff in Button & span.

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8 |
| System | macOS 10.14.3 |
| Browser | Chrome 76.0.3809.132 |

**Comment by afc163** [comment]
没看懂，没发现例子里有啥问题，可以用中文描述一下么。

**Comment by TiaossuP** [comment]
TAT，不好意思没说明白

第二个菜单项出于 selected 状态时，按钮中的文字看不到了
![image](https://user-images.githubusercontent.com/9267217/64921124-bb3df200-d7f1-11e9-82a5-d58dd5368902.png)

第四个菜单项出于 selected 状态时，popover 中的按钮中的文字看不到了
![image](https://user-images.githubusercontent.com/9267217/64921134-e0326500-d7f1-11e9-92f4-9fcd51abf6cb.png)
