### ISSUE TITLE
Drawer Routing Problem

### ISSUE THREAD

**Issue by GMArjun** [ant-design/ant-design#18751]
while drawer component opens, there is a class added to the body ( position: relative; width: calc(100% - 17px); overflow: hidden; touch-action: none; )
I'm having a link in drawer component, while page changes to the route while clicking that link the class not removing so the page gets collapsed.

**Comment by tclxtommy-hu** [comment]
参见：https://github.com/ant-design/ant-design/issues/24572 里的方法

**Comment by 0x15d3v2** [comment]
its chinese can someone give english answer?
