### ISSUE TITLE
上传图片后点击移除后利用onRemove回调可以把远端服务器的图片删除但本地预览的图片依然存在,要怎么同时去除本地预览图呢?

### ISSUE THREAD

**Issue by laolu87** [ant-design/ant-design#1876]
图片样式定义:        
   <FormItem  key = '5'
              label="图片："
              labelCol={{ span: 4 }}
              wrapperCol={{ span: 17 }}
              help="请上传图片"
              required>
              <div className="clearfix">
               <Upload name="File" action={`${SERVER_HOST}/uploads?token=${token}`} listType="picture-card" name='uploadFile'
               onRemove={this.onRemove}
                {...getFieldProps('pics', {
                  valuePropName: 'fileList',
                  normalize: this.normFile,
                })}>
                 <Icon type="plus" />
                 <div className="ant-upload-text">上传图片</div>
               </Upload>
               <Modal visible={this.state.priviewVisible} footer={null} onCancel={this.handleCancel}>
                 <img alt="example" src={this.state.priviewImage} />
               </Modal>
              </div>
            </FormItem>

 onRemove回调函数:
  onRemove(file){
    const uid = file.uid
    const token = localStorage.getItem('token')
    superagent
    .delete(`${SERVER_HOST}/uploads/${file.response.id}?token=${token}`)
    .end((err, res)=>{
      const text = JSON.parse(res.text)
      // console.log(text)
      if(!err && !text.message){
        message.success('删除成功')
      }else{message.error('删除失败')}
    })
  },

麻烦大家帮我看看需要怎么改写,谢谢了!

**Comment by laolu87** [comment]
<FormItem  key = '5'
              label="图片："
              labelCol={{ span: 4 }}
              wrapperCol={{ span: 17 }}
              help="请上传图片"
              required>
              <div className="clearfix">
               <Upload name="File" action={`${SERVER_HOST}/uploads?token=${token}`} listType="picture-card" name='uploadFile'
               onRemove={this.onRemove}
                {...getFieldProps('pics', {
                  valuePropName: 'fileList',
                  normalize: this.normFile,
                })}>
                 <Icon type="plus" />
                 <div className="ant-upload-text">上传图片</div>
               </Upload>
               <Modal visible={this.state.priviewVisible} footer={null} onCancel={this.handleCancel}>
                 <img alt="example" src={this.state.priviewImage} />
               </Modal>
              </div>
            </FormItem>

**Comment by laolu87** [comment]
onRemove回调函数:
onRemove(file){
const uid = file.uid
const token = localStorage.getItem('token')
superagent
.delete(${SERVER_HOST}/uploads/${file.response.id}?token=${token})
.end((err, res)=>{
const text = JSON.parse(res.text)
// console.log(text)
if(!err && !text.message){
message.success('删除成功')
}else{message.error('删除失败')}
})
},

**Comment by benjycui** [comment]
`fileList` 是受控属性 http://ant.design/#/components/upload?scrollTo=components-upload-demo-fileList

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by laolu87** [comment]
@benjycui  问题解决了,谢谢大神提醒!有时候没有点破还真的看不懂!谢谢了!

**Comment by smithbeyond** [comment]
@hong26 请问您是怎么解决点击删除之后既能够出发onRemove方法，又能够删除已上传的文件显示？

**Comment by weishijun14** [comment]
@hong26 请问您是怎么解决删除已上传的文件显示？
