### ISSUE TITLE
我之前的antd版本是3.1.6，Jenkins升级了antd到3.23.2版本有些组件图标不显示

### ISSUE THREAD

**Issue by ZengMX** [ant-design/ant-design#18760]
**这是升级后的**
<img width="977" alt="WeChat52f6abc4f99e56241e2501b9e521c5d5" src="https://user-images.githubusercontent.com/9668119/64676910-23669e00-d4a9-11e9-9e2a-22b87a0543cc.png">
**这是升级前的**
![image](https://user-images.githubusercontent.com/9668119/64676992-4c872e80-d4a9-11e9-91f6-e690967ec26d.png)

希望能得到回答

**Comment by yoyo837** [comment]
更多是检查自己的css 样式覆盖吧
