### ISSUE TITLE
Popover trigger="focus" and onVisibleChange bugs on Firefox

### ISSUE THREAD

**Issue by tylik1** [ant-design/ant-design#18766]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/weathered-grass-y8jul)

### Steps to reproduce
Open link in Chrome. 
Click on the button.
Popup is opened.
Click outside button.
Popup is closed

Do the same with Firefox.
Nothing happens. Popup never opens

### What is expected?
Firefox behavior should be the same as in Chrome

### What is actually happening?
Popup is not opened. trigger="focus" and onVisibleChange doesn't work as expected

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.2 |
| System | OS X |
| Browser | Chrome latest, Firefox latest, Safari latest |

**Comment by afc163** [comment]
It works fine in my Firefox.

![CleanShot 2019-09-11 at 18 14 19](https://user-images.githubusercontent.com/507615/64688978-07222b80-d4c0-11e9-8aea-2523ad729046.gif)

<img width="670" alt="image" src="https://user-images.githubusercontent.com/507615/64688843-cc1ff800-d4bf-11e9-80ab-39a4a5350798.png">

**Comment by afc163** [comment]
In chrome, clicking button will trigger `onFocus` in native button: https://codesandbox.io/s/suspicious-dream-klgft

That is a compatibility issue from chrome and other browsers. Sorry, there is nothing we can do about it.
