### ISSUE TITLE
Antd AutoComplete Custom Dropdown Styling Issue

### ISSUE THREAD

**Issue by SeunghunSunmoonLee** [ant-design/ant-design#18763]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/SeunghunSunmoonLee/pen/qBWYbRE?editors=0010](https://codepen.io/SeunghunSunmoonLee/pen/qBWYbRE?editors=0010)

### Steps to reproduce
dropdownStyle doesn't get applied. I want to show 100% of dropdown without users having to scroll down. 
```
    <AutoComplete style={{ width: 120 }} dropdownStyle={{ maxHeight: 1000, overflowY: 'visible' }} onChange={handleChange}>
    {opsList}
    </AutoComplete>
```
This also doesn't work. 
```
  .ant-select-dropdown-menu {
    max-height: none !important;
    overflow-y: visible !important;
  }
```

### What is expected?
dropdownStyle doesn't get applied. I want to show 100% of dropdown without users having to scroll down. 

### What is actually happening?
dropdownStyle doesn't get applied. I want to show 100% of dropdown without users having to scroll down. 

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.9 |
| System | Mac OSX Majove |
| Browser | 76.0.3809.132 |

**Comment by afc163** [comment]
There is a undocumented prop `dropdownMenuStyle` for it: https://codepen.io/afc163/pen/oNvdzob?editors=0010

Welcome to send us a PR to Select and AutoComplete API documentation.

**Comment by rdeepk** [comment]
@SeunghunSunmoonLee Were you able to apply a wrapper css class to dropdown?
