### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by CastroM13** [ant-design/ant-design#18772]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-validate-other](https://ant.design/components/form/#components-form-demo-validate-other)

### Steps to reproduce
Upload an archive in the example Upload Component

### What is expected?
An error text in the tooltip

### What is actually happening?
Showing a HTML file as the text

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | ? |
| System | ? |
| Browser | Google Chrome |

---
I know this isn't really relevant at all, but still, i think it's worth to report these kind of bugs, also, by seeing the issue helper i got the idea that it's intended to bugs on AntD funcionalities, but i didn't find any alternative focused on the website

**Comment by ycjcl868** [comment]
This is because of an upload server error, so you can use `normFile` to custom the error message.

```diff
 normFile = e => {
    console.log('Upload event:', e);
    if (Array.isArray(e)) {
      return e;
    }
-   return e && e.fileList;
+    const fileList = (e ? e.fileList : []).map(file => ({
+      ...file,
+     response: file.status === 'error' ? 'Server Error' : file.response,
+    }));
+    return fileList;
  };

```

like this:

![image](https://user-images.githubusercontent.com/13595509/64748745-cb31a980-d545-11e9-82dd-93b3756cd816.png)
