### ISSUE TITLE
Ability to close panels in Collapse (accordion) through other actions other than clicking the collapse icon in a Panel

### ISSUE THREAD

**Issue by azeezolaniran2016** [ant-design/ant-design#18779]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- Ability to collapse panels through other actions aside clicking the collapse arrow but still be able to open them by clicking the expand Icon in a panel through managing the activeKey of the Collapse

### What does the proposed API look like?
1. Each Panel in a Collapse exposes an onExpand and onCollapse function prop. With these callback function, the Collapse activeKey can be set there by allowing users still expand a collapse even if it was collapsed by setting activeKey to -1 or something invalid.

**Comment by afc163** [comment]
Please use `activeKey` to control the state.
