### ISSUE TITLE
Popover is obscured by the boundary when it is first displayed

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#18776]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/competent-jepsen-d12h9)

### Steps to reproduce
click button then Popover first display

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest |

ref: #14582

**Comment by afc163** [comment]
There is no perfect solution for this situation, popover card height should be fixed.
