### ISSUE TITLE
国际化 Form label 的冒号样式问题

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1877]
来自 @青栀

![](https://os.alipayobjects.com/rmsportal/pdaJFXqQZHgtdrE.png)

![](https://os.alipayobjects.com/rmsportal/lCOjjROytojuqDP.png)

做国际化时我们需要将中文的冒号翻译成英文冒号，由于英文冒号不如种冒号来的长。。于是。。

## 建议

1. 去掉所有的冒号，label 和 input 之间留固定一段空白间距
2. 英文下特殊处理，增加空白间距

个人建议选择 1，比较简单

**Comment by afc163** [comment]
### 解决方案：

1. 统一保留 `：` 。
2. 表单组件使用时，不应需要手动写冒号。
   ```js
   <FormItem label="姓名：" />   // 原来是这样
   ```
   改为 =>
   ```js
   <FormItem label="姓名" />   // 应该是这样
   ```

3. 国际化时，不需要对冒号做翻译处理，只针对具体文案翻译。

4. 统一由 FormItem 组件来加这个冒号和相应的间距。

5. 针对原来写了中文冒号的情况，组件检查并做兼容化处理。

**Comment by superRaytin** [comment]
这样的话，如果用户不想要这个冒号，是否有办法禁用

**Comment by afc163** [comment]
再补个 `colon={false}`。

**Comment by benjycui** [comment]
或者干脆纳进设计规范。。就像 Button 两个中文中的空格。

**Comment by afc163** [comment]
确实是设计规范，我们自己是不会修改这个的。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/bf1cf10adf2628f01ead9518c49b278312462d08#diff-a854f46c9dd5d48ffcb8a5aeecae42c5R80

这里原来做过英文冒号的处理，只需要设置页面 `<html lang="en">` 就行。

**Comment by afc163** [comment]
不过还是需要写 `：` 号，略麻烦，还是按上面说的修改一遍。

**Comment by Lxyour** [comment]
中文页面本来有冒号，升级了一下没有冒号是什么情况？

**Comment by afc163** [comment]
@Lxyour 给代码。

**Comment by Lxyour** [comment]
@afc163 解决了，谢谢
