### ISSUE TITLE
Do we need to pass in a triggerNode to getPopupContainer in Select

### ISSUE THREAD

**Issue by escapiststupor** [ant-design/ant-design#18797]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-surf-ye3zj)

### Steps to reproduce
In your example repo we don't need to pass anything to getPopupContainer

[but the type file says `getPopupContainer?: (triggerNode: HTMLElement) => HTMLElement;`](https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L34)
What exactly should we pass as `triggerNode`?

### What is expected?
Not sure, maybe  `getPopupContainer?: () => HTMLElement;`

[The type should be the same as in `RcSelect`](https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L278) where  [`getPopupContainer` is typed as `React.ReactNode | (() => React.ReactNode);`](https://github.com/react-component/select/blob/bc567e1826/src/interface/index.ts#L4
)

### What is actually happening?

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.6 |
| System | Mac OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
You don't have to pass argument to `getPopupContainer`, the definite works fine: https://codesandbox.io/s/keen-davinci-3o1fu

**Comment by mtadams007** [comment]
Shouldn't the triggerNode be optional then?
`(triggerNode?: HTMLElement) => HTMLElement` ?
