### ISSUE TITLE
加载spin的时候报错

### ISSUE THREAD

**Issue by readyou** [ant-design/ant-design#1879]
用spin来表示加载中，当ajax请求获取数据后，不再显示spin，当时间较短的时候出现错误：
vendor.0503e916.js:1 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the undefined component.

查源代码发现，有如下代码：
      this.debounceTimeout = setTimeout(function () {
        return _this2.setState({ spinning: spinning });
      }, 250);
从这里可以看出，如果在250ms内，spin被unmount，而定时器到时的时候_this2.setState({ spinning: spinning });中的_this2将不复存在，故报错。

初步感觉将250改为0应该就好了。

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/1658

升级。
