### ISSUE TITLE
RangePicker component has no "name" attribute when mounting on the DOM

### ISSUE THREAD

**Issue by jsefiani** [ant-design/ant-design#18792]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-wx9dz?fontsize=14)

### Steps to reproduce
1. Import the RangePicker component
2. Add a name attribute to it
3. Inspect the input element via chrome dev tools and try to look for a name attribute (you won't find it)

### What is expected?
The input element should have a "name" attribute.

### What is actually happening?
The input element has NO "name" attribute, while I included that property on the RangePicker component.

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.0 |
| System | Microsoft Windows 10 pro |
| Browser | Chrome |

---
A similar problem occurred before with the DatePicker component, but it was resolved by your team. Here is a link to the ticket: https://github.com/ant-design/ant-design/issues/14990

**Comment by kavience** [comment]
@jsefiani @yesmeck 
Hi, guys, I just did it, PR is [here](https://github.com/ant-design/ant-design/pull/19207)

**Comment by afc163** [comment]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/507615/76630268-b5478480-657a-11ea-90ae-8d1aec6d4d59.png">
