### ISSUE TITLE
Component Select > show search input: change the autocomplete="off" to "new-password"

### ISSUE THREAD

**Issue by ywtsang** [ant-design/ant-design#18808]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We find that the search input of "Select" component will be polluted by Chrome's autocomplete even the search input has attached autocomplete="off".

### What does the proposed API look like?
Tried to change autocomplete="off" to "new-password" via inspector can shutdown Chrome's autocomplete

ref: https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands

**Comment by MildTomato** [comment]
I actually ended up here for the opposite problem.

trying to get a Antd Select component to have autoComplete = "on" when inside a Form.Item in a Form

Does Select in Antd just ignore the autocomplete behaviour ?
