### ISSUE TITLE
Table filterMultiple: false should display filter options as radios instead of checkboxes

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#1880]
Reffering to sorter example from Ant-design website 
- http://ant.design/#/components/table?scrollTo=components-table-demo-head

Property `filterMultiple: false` displays filter options as checkbocks. But they probably should be displayed as radios (because they behave as raidos).

**Comment by ddcat1115** [comment]
A reasonable suggestion ~
