### ISSUE TITLE
Add choice to remove up/down step icon (Ref #6556)

### ISSUE THREAD

**Issue by j14bis** [ant-design/ant-design#18809]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature has been requested before (Ref #6556) but is closed. I think it makes sense in some situation. One argument against it in the comment is that the step icon distinguish it from normal Input. Although it is a valid point, an InputNumber field distinguishes itself also by number validation and min/max value.

### What does the proposed API look like?
Add a property like 'disableStep'.

**Comment by afc163** [comment]
You can try to customize css to hide it.

**Comment by j14bis** [comment]
Yes, I can, But, I think it would be better for the design of the API to discourage such hackish way of doing things in general. Being able to show/hide form field action icons is a quite common feature and should be readily available for a well designed API.
