### ISSUE TITLE
Layout 和 Menu 组合使用时，收起侧边导航会导致展开的子菜单脱离导航

### ISSUE THREAD

**Issue by ihaichao** [ant-design/ant-design#18807]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/broken-sun-o9g44?fontsize=14)

### Steps to reproduce
1. 使用 antd 的 Layout 的 [侧边布局](https://ant.design/components/layout-cn/#components-layout-demo-side)
2. 使用 antd 的 Menu 的 [只展开当前父级菜单](https://ant.design/components/menu-cn/#components-menu-demo-sider-current) 的代码
3. 将 Layout 和 Menu 组合起来

### What is expected?
当有子菜单展开时，此时收起侧边导航，应该不展示任何子菜单

### What is actually happening?
当有子菜单展开时，此时收起侧边导航，刚刚展开的子菜单会脱离侧边导航展示

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.6 |
| System | macOS 10.14.6 |
| Browser | Chrome 76.0.3809.132 |

**Comment by afc163** [comment]
https://codesandbox.io/s/elegant-monad-goosq
