### ISSUE TITLE
expandedRow across all columns

### ISSUE THREAD

**Issue by j14bis** [ant-design/ant-design#18804]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Two customized behaviors can be added
I) Make it possible to choose whether the expanded row can span across all columns or better any number of columns in the middle.  
II) Make it possible to add customized render before and after the current expandedRowRender
Currently, the first column is reserved with empty content. It would be nice in some case to customize the content of this empty column.

### What does the proposed API look like?
One way is to make the 'expandedRowRender' property to be either a render function as normal or a configuration object like below
{
    render: the main render function (span from startCol   1 to endCol) for the expanded row
    startCol?: number
    endCol?: number
    beforeRender?: a render function (span from 0 to startCol)
    afterRender?: a render function (span from endCol   1 to the end)
}

**Comment by afc163** [comment]
My suggestion is that you could customize a HOC via `expandedRowRender` in your application.

**Comment by j14bis** [comment]
Maybe I can. But at least a choice can be added to make it span across all columns to make the design cleaner instead of having to develop ad hoc work around.
