### ISSUE TITLE
Allow leading zeros on InputNumber

### ISSUE THREAD

**Issue by JLucasAmorim** [ant-design/ant-design#18806]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When we type a number starting with 0, the input removes it, and it shouldn't be removed.

### What does the proposed API look like?
If possible, the input should allow the leading zeros by default or it should have a property to allow it.

**Comment by afc163** [comment]
You can try `formatter` and `parser`: https://codesandbox.io/s/shy-rain-dmcjk

**Comment by JLucasAmorim** [comment]
Hi!, Well, I've tested it, and it doesn't work very well as you can see here: https://codesandbox.io/s/flamboyant-hugle-lphd7

**Comment by iShubhamPrakash** [comment]
Any update on this issue? I'm facing the same problem. I need a number input that allows numbers with leading 0s.

**Comment by brycesenz** [comment]
@iShubhamPrakash - I had a similar use case, and can outline my solution below, as well as my logic.  First, I would make three points:

1. The use case of the `InputNumber` is to handle data that is stored as a numeric input.  Note that the library that this class is built on (https://www.npmjs.com/package/rc-input-number) natively converts the value to a decimal.
2. In cases where we have leading zeroes, we are really talking about *string* representations of numbers, so we need a solution that is built on handling the input as a string.
3. To have our `string` input function correctly for storing strings of numbers, we need to make sure that we aren't allowing non-digits to the input.

I built a custom component to handle this, which uses the normal antd `Input` class, and the `getValueFromEvent` method to serve as a filter for the input going into the `Form.Item` class.


```
import React from 'react';
import PropTypes from 'prop-types';
import { Form, Input } from 'antd';

const NumericStringInput = ({ name, required, label, placeholder, ...restProps }) => {
  const fieldPlaceholder = placeholder || label;
  const className = 'numeric-string-input';

  // This is used to transform the value from the raw field event
  const handleChange = (event) => {
    const value = event.target.value;
    return value.toString().replace(/\D/g,'');
  }

  // You could add whatever default rules you want here
  let rules = [];
  if (required) { rules = rules.concat([{ required: true }]) }

  return (
    <div className="numeric-string-input-wrapper">
      <Form.Item
        className="form-item"
        getValueFromEvent={handleChange}
        label={label}
        name={name}
        rules={rules}
        {...restProps}
      >
        <Input
          placeholder={fieldPlaceholder}
          type="text"
          name={name}
          className={className}
          {...restProps}
        />
      </Form.Item>
    </div>
  );
};

NumericStringInput.defaultProps = {
  required: false,
  label: undefined,
  placeholder: undefined
};

NumericStringInput.propTypes = {
  name: PropTypes.oneOfType([PropTypes.string, PropTypes.array]).isRequired,
  required: PropTypes.bool,
  label: PropTypes.string,
  placeholder: PropTypes.string,
};

export default NumericStringInput;
```
