### ISSUE TITLE
Ant Tree switcherIcon prop not working

### ISSUE THREAD

**Issue by Nilanth** [ant-design/ant-design#18810]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-hermann-w82n2?fontsize=14)

### Steps to reproduce
Check the sandbox 

### What is expected?
on passing custom icon to switcherIcon prop expand and collapse icons to be changed

### What is actually happening?
On passing custom icon to switcherIcon there is no change

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.9 |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
same as #18717

**Comment by zombieJ** [comment]
This can not be fix in v3 since `showLine` is hack and strong rely on the style which ping the icon. We should add warning for this.

**Comment by afc163** [comment]
https://deploy-preview-18829--ant-design.netlify.com/components/tree/#components-tree-demo-switcher-icon

I think we can fix it?

**Comment by Nilanth** [comment]
> https://deploy-preview-18829--ant-design.netlify.com/components/tree/#components-tree-demo-switcher-icon
> 
> I think we can fix it?

How to fix it
