### ISSUE TITLE
4.0版本Tree控件受控模式失效

### ISSUE THREAD

**Issue by daihy8759** [ant-design/ant-design#18812]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sad-hawking-xcvw2)

### Steps to reproduce
点击根节点

### What is expected?
子节点能正常勾选

### What is actually happening?
实际没有勾选子节点，与3.x版本表现不一致

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.2 |
| React | 16.9.0 |
| System | osx |
| Browser | chrome |

**Comment by zombieJ** [comment]
reproduce: https://codesandbox.io/s/vibrant-bhabha-xvokk
