### ISSUE TITLE
Table的Columns如果不指定width属性或使用百分比，使用react-resizable插件无效

### ISSUE THREAD

**Issue by yangbinlovegis** [ant-design/ant-design#18818]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-bush-qp289)

### Steps to reproduce
1. columns中的width字段配置为百分比或者不配置
2. 使用react-resizable插件
鼠标hover在表头结果：列宽无法改变

### What is expected?
鼠标hover在表头，列宽可以改变

### What is actually happening?
鼠标hover在表头，列宽无法改变

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.4 |
| System | win7 |
| Browser |  chrome 67.0.3396.99 |

**Comment by zombieJ** [comment]
`react-resizable` 的 `width` 是必填项，值必须为 `number` 类型：
ref: https://www.npmjs.com/package/react-resizable

**Comment by PeiTianHuang** [comment]
其实也可以算是一个bug，毕竟列伸缩是table中比较重要的功能，react-resizable的支持不大友好，建议将其内置到库里头（新旧版本都有该问题）
