### ISSUE TITLE
getFieldsValue（） 方法无法获取值

### ISSUE THREAD

**Issue by leowang199303** [ant-design/ant-design#18826]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当页面中有两个form时，getFieldsValue（）方法获取不到我想要的哪个表单的值，文档上说，输入控件的值，但是我整个表单。。。怎么输入？同时我两个表单有出现重复的控件值

### What does the proposed API look like?
页面中出现多个form时，getFieldsValue（）方法能获取指定的表单值

**Comment by yoyo837** [comment]
Form.create 与<From>一对一
