### ISSUE TITLE
按钮组里面如果给按钮添加a标签连接，按钮组效果失效。

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#1882]
`<ButtonGroup>
          <a href="./unfinishedWork.html"><Button type="primary" size="large">看板视图</Button></a>
          <Button type="primary" size="large">列表视图</Button>
          <a href="./finishedWork.html"><Button type="primary" size="large">已完成任务</Button></a>
        </ButtonGroup>`

现在这样修复了下
`<ButtonGroup>
          <Button type="primary" size="large"><a href="./unfinishedWorkKanban.html">看板视图</a></Button>
          <Button type="primary" size="large"><a href="./unfinishedWorkList.html">列表视图</a></Button>
          <Button type="ghost" size="large"><a href="./finishedWork.html">已完成任务</a></Button>
        </ButtonGroup>`

`
// ant-btn-group
.ant-btn-group{
  .ant-btn-primary a{
    color: #fff;
  }
  .ant-btn-ghost a{
    color: #666;
  }
}
`

**Comment by superRaytin** [comment]
确实需要优化一下，Button 中的链接颜色需要继承一下。http://codepen.io/superRaytin/pen/GqRjVK?editors=0010  感谢反馈

**Comment by afc163** [comment]
不推荐下面那样做，不符合 HTML5 规范：http://stackoverflow.com/a/17253457

---

上面那样写确实样式会错乱，目前只能推荐这样写：

```js
<ButtonGroup>
  <Button onClick{() => location.href="./unfinishedWork"}>按钮</Button>
  <Button onClick{() => location.href="./unfinishedWork"}>按钮</Button>
</ButtonGroup>
```

**Comment by superRaytin** [comment]
好吧

> So, if you are writing invalid HTML, expect unexpected behavior ;-)

**Comment by afc163** [comment]
还是为了展现加了颜色的继承，不过依然不推荐这么用。
