### ISSUE TITLE
Table rendering is slower and slower when adding fixed amount of items

### ISSUE THREAD

**Issue by florian-bd** [ant-design/ant-design#18824]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/weathered-bash-cnf2y)

### Steps to reproduce
Add a fixed amount of items to a table. Then add the same amount of item to the same table. Rendering is slower even though you added the same number of items

### What is expected?
Rendering time should depend on number of items added, not on number of items already in the table

### What is actually happening?
Rendering time increases based on number of items already in the table

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.9.0 |
| System | windows |
| Browser | Chrome |

**Comment by ERrorMAKros** [comment]
Any news? Table selection is very-VERY slow! ;(

**Comment by afc163** [comment]
Duplicate of #10431

**Comment by sagar-noovosoft** [comment]
@chenshuai2144 any updates on this?

**Comment by mohamedRhaiem** [comment]
Any updates for this Issues 🤔
