### ISSUE TITLE
Carousel Autoplay Bug

### ISSUE THREAD

**Issue by Xiodra** [ant-design/ant-design#18823]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/exciting-moon-cxv1e)

### Steps to reproduce
Click on the switch to switch

### What is expected?
The autoplay of carousel component can be changed according to the state.

### What is actually happening?
Whether the carousel component can stop playing automatically, but stop can't play automatically again

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | latest |
| System | Window 10 家庭中文版（1809） |
| Browser | chrome x64（76.0.3809.132） |

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/pull/1349

**Comment by afc163** [comment]
#11830

**Comment by Kermit-Xuan** [comment]
3.x don't maintain, please upgrade to 4.x version.
