### ISSUE TITLE
请问你们是否有实现其它框架版本的antd的计划？

### ISSUE THREAD

**Issue by ibufu** [ant-design/ant-design#1883]
比如angular2、vue。
如果暂时没有的话，是否允许其他人实现呢？

**Comment by afc163** [comment]
http://ant.design/#/docs/spec/introduce?scrollTo=%E5%89%8D%E7%AB%AF%E5%AE%9E%E7%8E%B0

https://github.com/ant-design/ant-design/wiki/FAQ#are-you-going-to-provide-angularvueetc-edition

**Comment by xiexingen** [comment]
期待angular4版的ant
