### ISSUE TITLE
select showSearch 在移动设备使用时 选中select会调用软键盘，想关闭软键盘后依然保持下拉显示状态

### ISSUE THREAD

**Issue by 13954555255** [ant-design/ant-design#18836]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
移动端 点击select =》搜索内容=》关闭移动端软键盘  下拉列表 下拉状态关闭

### What is expected?
select 用 showSearch时， 在移动设备使用时，再输入完搜索内容后，隐藏小键盘，下拉列表需要保持下拉显示状态，

### What is actually happening?
select 用 showSearch时， 在移动设备使用时，再输入完搜索内容后，隐藏小键盘，下拉列表关闭下拉状态，无法做到 搜索完 隐藏小键盘 来进行浏览搜索到的内容

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | vue |
| System | ios 12 |
| Browser | safari |

---
没有重现连接， 不过 随便点个 select  showSearch  都回重现

**Comment by afc163** [comment]
移动端我们不太能投入精力去支持，欢迎直接 PR。
