### ISSUE TITLE
Type check error when using generic type on "Select" component

### ISSUE THREAD

**Issue by zhz26826** [ant-design/ant-design#18838]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-typescript-znwr0)

```typescript
import * as React from "react";
import Select, { SelectProps } from "antd/es/select";
import "antd/es/input/style/css";

class MySelect<T> extends React.Component<SelectProps<T>, {}> {
  render() {
    return <Select {...this.props} />;
  }
}

export default MySelect;
```

### Steps to reproduce
In react project with Typescript, using generic type on "Select" component will cause type error. Check out the type error in the "select.tsx" of the code sandbox. (The same usage works for "Table" component)

### What is expected?
No type error when using generic type on "Select" component

### What is actually happening?
Type error appears when passing  generic type on "Select" component

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.9 |
| System | macOS |
| Browser | chrome |

**Comment by afc163** [comment]
Try this way?

https://codesandbox.io/s/react-typescript-cb9uj

**Comment by zhz26826** [comment]
@afc163 Thanks for your reply. But unfortunately this doesn't work in TypeScript strict mode. I try to add `"strict": true` to tsconfig "compilerOptions", error still appears.

https://codesandbox.io/s/react-typescript-pu6dl
