### ISSUE TITLE
Drawer Component / top and bottom missing from props

### ISSUE THREAD

**Issue by jsthack** [ant-design/ant-design#18844]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-gkbif)

### Steps to reproduce
There isn't really anything you can do to reproduce this.

### What is expected?
What is expected is a drawer component, that opens vertically (top).

### What is actually happening?
In the Drawer properties, it's showing that "top" isn't defined. In your documentation is clearly shows left | right | top | bottom.  When looking in the Ant Design package source only left and right are defined. placement?: 'left' | 'right';

```tsx
export interface DrawerProps {
    closable?: boolean;
    destroyOnClose?: boolean;
    getContainer?: string | HTMLElement | getContainerfunc;
    maskClosable?: boolean;
    mask?: boolean;
    maskStyle?: React.CSSProperties;
    style?: React.CSSProperties;
    title?: React.ReactNode;
    visible?: boolean;
    width?: number | string;
    wrapClassName?: string;
    zIndex?: number;
    prefixCls?: string;
    push?: boolean;
    placement?: 'left' | 'right';
    onClose?: (e: EventType) => void;
    className?: string;
}
```

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | React 16.4.2 |
| System | OSX 10.14.6 |
| Browser | Chrome 76.0.3809.132 |

---
The main problem is your documentation isn't matching your libraries source code.

**Comment by jsthack** [comment]
https://ant.design/components/drawer/ I forgot to include the link in your documentation where it lists 'top' | 'right' | 'bottom' | 'left'.  And we are using "antd": "3.8.4",

**Comment by yoyo837** [comment]
2ca3661e87533794aecafd8da8a00d6204565d0c cc2bd76595091dbc0bf58a9a5a687d22fec8686f

**Comment by yoyo837** [comment]
Please try version v3.9.0 and above.
