### ISSUE TITLE
Popconfirm is confused by CSS sticky position

### ISSUE THREAD

**Issue by isacvale** [ant-design/ant-design#18843]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/embed/antd-reproduction-template-5owwl?fontsize=14](https://codesandbox.io/embed/antd-reproduction-template-5owwl?fontsize=14)

### Steps to reproduce
Create a tall container. In it place a div with position sticky. Inside it, put a button with a Popconfirm.

### What is expected?
When you scroll and the div with the button sticks to the top. If you pressed the button, the popconfirm it should go down and be within the page.

### What is actually happening?
When you scroll and the div with the button sticks to the top. If you press the button, the popconfirm goes up instead of down, ans is unreachable going beyond the page.

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | react |
| System | Debian 9 |
| Browser | Chrome 76.0.3809.132 64 bits |

---
Same issue happens with position fixed.

**Comment by afc163** [comment]
[https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-scrolls-with-the-page?](https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-scrolls-with-the-page?)
