### ISSUE TITLE
New icon: External link

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#18841]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Informs the user that the link they are clicking goes to a site outside of the current application.

### What does the proposed API look like?
An icon similar to https://image.flaticon.com/icons/svg/25/25284.svg

**Comment by afc163** [comment]
`<Icon type="export" />`

**Comment by PaddyMann** [comment]
The export icon is _similar_ to what's being asked for, but it's not right.

A Google search for either "external link icon" or "open in a new window icon" demonstrates that it's a well understood icon: It should be a box with an arrow pointing to the top right (and not just to the right).

So, the existing icon works fine for "export", but not for "external link".

Please reopen this issue :)

**Comment by flying-sheep** [comment]
Temporary, kinda inadequate workaround: `<LogoutOutlined rotate={-45} />`
