### ISSUE TITLE
Setting the searchValue value does not work in Select.

### ISSUE THREAD

**Issue by tuphampro** [ant-design/ant-design#18847]
Setting the searchValue value does not work in Select.

**Comment by youyi2016** [comment]
这个问题什么时候可以修复，同样遇到这个问题。

**Comment by xiaojixuansu** [comment]
同样遇到这个问题，还希望尽快修复

**Comment by afc163** [comment]
不存在 `searchValue` or `inputValue` 这个属性，完全是一个误解：https://github.com/ant-design/ant-design/pull/18584#issuecomment-534927550

**Comment by yoyo837** [comment]
咦？那这个是为什么？ 4cac0a98223ec9bc1a39c7798f7ed34049f8e2f4 

![image](https://user-images.githubusercontent.com/6134547/65586912-8ed76200-dfb7-11e9-8b16-c124e849eacb.png)

**Comment by afc163** [comment]
1. 一个用户发了 PR 需要加 `inputValue` 属性的定义，但是他看错了，rc-select 里没这个属性。https://github.com/ant-design/ant-design/pull/18584#issuecomment-534927550 我也看出了，手误给合并了。
2. @zombieJ 认为 `inputValue` 不符合命名规范，改成了 `searchValue` 并添加了 warning。https://github.com/ant-design/ant-design/pull/18629
3. 实际上 `inputValue` 只是 `rc-select` 里的一个 state，不是属性，`inputValue` 和 `searchValue` 都没有作用。

我发个 PR 把相关代码都干掉：https://github.com/ant-design/ant-design/pull/19003
