### ISSUE TITLE
Select Multiple does not show options

### ISSUE THREAD

**Issue by lcorniglione** [ant-design/ant-design#18840]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/wispy-sea-em822)

### Steps to reproduce
Type on select and wait until settimeout resolve the callback. You will see that the option is not displayed into the select.

### What is expected?
See the option rendered into the select.

### What is actually happening?
The option does not appear.

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.6 |
| System | linux ubuntu |
| Browser | Mozilla |

---
If I change the key of the option to key={it.name} the option is displayed, but I need the id as the key of the option.

**Comment by afc163** [comment]
```diff
  onChange = value => {
    console.log(value);
+   this.setState({ value });
  };
```

**Comment by afc163** [comment]
https://codesandbox.io/s/pedantic-rosalind-v0o8f

**Comment by lcorniglione** [comment]
Hi! Thanks for your response.

Maybe I think that I was not clear about the issue. The problem is when I write on the input the handleSearch method is dispatched, but then, the render method is executed again but the option items are not displayed into the Select component. Even though, when I list the options into the select with **key={it.name}** the options are displayed. Maybe I am wrong but I spect the same behavior in both cases. I will try to illustrate the issue.

> Expected behavior

[https://www.loom.com/share/1a1cfe82de784912a85c983eddb3c237](url)

> Select bug

[https://www.loom.com/share/0c60418ca6fd49e4b384e17e1e10654b](url)

**Comment by oceandrama** [comment]
I can reproduce it too. When I use number or smth that can be convert to number as key - options doesn't display
@lcorniglione You can use smth like key={`${it.id}-${it.name}`}

**Comment by oceandrama** [comment]
@lcorniglione You should use `filterOption={false}` because Select component filters options itself even with `handleSearch`

**Comment by lcorniglione** [comment]
@oceandrama Thank for your response! That did the trick!
