### ISSUE TITLE
Input 中addonAfter 节点为Icon 时会存在0.25高度差

### ISSUE THREAD

**Issue by MrRENGE** [ant-design/ant-design#18856]
解决办法是全局覆盖掉行高，
` 
 .ant-input-group-addon{
     line-height: normal !important;
  } `。官网上异常截图
![image](https://user-images.githubusercontent.com/42133962/65019739-610e6f80-d95e-11e9-883e-3968a49b90ae.png)

**Comment by yoyo837** [comment]
发 PR 吧
