### ISSUE TITLE
Tooltip TypeScript definition causes problems when used with Emotion

### ISSUE THREAD

**Issue by hsz** [ant-design/ant-design#18868]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/hsz/antd-tooltip-typescript-issue](https://github.com/hsz/antd-tooltip-typescript-issue)

### Steps to reproduce
Wrap Tooltip component with Emotion's styled:

```javascript
import styled from '@emotion/styled';
import { Tooltip } from 'antd';

const StyledTooltip = styled(Tooltip)`
  color: red;
`;
```

### What is expected?
Return wrapped Tooltip component

### What is actually happening?
TypeScript throws an error:

```
TypeScript error in /home/hsz/Projekty/antd-tooltip-typescript-issue/src/index.tsx(6,30):
No overload matches this call.
  Overload 1 of 2, '(tag: ComponentType<any>, options?: StyledOptions | undefined): CreateStyledComponentBaseThemeless<any, {}>', gave the following error.
    Argument of type 'typeof Tooltip' is not assignable to parameter of type 'ComponentType<any>'.
      Type 'typeof Tooltip' is not assignable to type 'ComponentClass<any, any>'.
        Types of property 'getDerivedStateFromProps' are incompatible.
          Type '(nextProps: TooltipProps) => { visible: boolean | undefined; } | null' is not assignable to type 'GetDerivedStateFromProps<any, any>'.
            Types of parameters 'nextProps' and 'nextProps' are incompatible.
              Type 'Readonly<any>' is not assignable to type 'TooltipProps'.
                Property 'overlay' is missing in type 'Readonly<any>' but required in type 'TooltipPropsWithOverlay'.
  Overload 2 of 2, '(tag: "symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 154 more ... | "view", options?: StyledOptions | undefined): CreateStyledComponentBaseThemeless<...>', gave the following error.
    Argument of type 'typeof Tooltip' is not assignable to parameter of type '"symbol" | "object" | "a" | "abbr" | "address" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | "canvas" | ... 154 more ... | "view"'.
      Type 'typeof Tooltip' is not assignable to type '"view"'.  TS2769

    4 | import ReactDOM from 'react-dom';
    5 | 
  > 6 | const StyledTooltip = styled(Tooltip)`
      |                              ^
    7 |   color: red;
    8 | `;
    9 | 
```

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.9.0 |
| System | any |
| Browser | any |

---
Issue is caused because of this commit:

https://github.com/ant-design/ant-design/commit/b029e3870524850f5f0d12cc5a2bfe4e53e48255#diff-186839a30bf8b9d67a4b10bf7c091d5f

Downgrading to `antd@3.22.2` (version without above commit) makes everything working correctly.

**Comment by afc163** [comment]
@laysent Could you help to check this problem?

**Comment by laysent** [comment]
> @laysent Could you help to check this problem?
> 
> #18515

I think this issue is caused due to conflict definition of static API between Tooltip component and `@emotion/styled`. In Tooltip, `getDerviedStateFromProps` API requires the passed in props to have required field (i.e. `nextProps: TooltipProps`), while the definition in `@emotion/styled` uses `React.ComponentType<any>`, which has `getDerviedStateFromProps(nextProps: any)` definition instead. `Readonly<any>` is not assignable to `TooltipProps`.
I have raised a PR (https://github.com/emotion-js/emotion/pull/1514), see if that will fix the issue.

**Comment by paulsouche** [comment]
Hi !

```
export const StyledTooltip = styled<React.ComponentType<TooltipProps>>(Tooltip) 
```
solves the issue but `Exported variable 'StyledTooltip' has or is using name 'TooltipPropsWithOverlay' from external module "/node_modules/antd/lib/tooltip/index" but cannot be named.`

Need to export union types

**Comment by laysent** [comment]
Hi @paulsouche, would you mind to take a look at this PR (https://github.com/ant-design/ant-design/pull/19846) and see if this is what you are looking for?

**Comment by laysent** [comment]
For anyone who has encountered this issue, @emotion/styled has updated their TypeScript definition, which should have fixed this issue, please feel free to take a look: https://github.com/emotion-js/emotion/pull/1501

**Comment by paulsouche** [comment]
Hi @laysent yes ! Thank you ! #19846 fixes my issue. Can be closed now I think
