### ISSUE TITLE
PageHeader back button should use the same color as PageHeader title

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#18869]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently the button is hard coded to use `#000` (https://github.com/ant-design/ant-design/blob/master/components/page-header/style/index.less#L28). I propose this be changed to use `@heading-color` to keep the design consistent when the color variables are changed.

### What does the proposed API look like?
The style would use the same color value as the header title text

```
    &-button {
      .operation-unit();
      color: @heading-color;
      cursor: pointer;
    }
```

**Comment by afc163** [comment]
It is by designed, you can send us a PR that add variable like `@page-header-back-color` for customization.
