### ISSUE TITLE
menu添加徽标数

### ISSUE THREAD

**Issue by onLing** [ant-design/ant-design#18862]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在菜单中，目前只能显示icon和name。但实际在我的后台管理系统中，需要明显的提醒用户某个子菜单有数据更新，在子菜单上显示徽标数是很好的用户体验。

### What does the proposed API look like?
menu中提供api，用来显示以及更新徽标数

**Comment by shaodahong** [comment]
可以自行结合 [Badge](https://ant.design/components/badge-cn/) 组件来使用
