### ISSUE TITLE
在父组件如何获取Drawer组件对象

### ISSUE THREAD

**Issue by jiangzm** [ant-design/ant-design#18865]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需要监听Drawer中滚动条事件，设置ref获取组件对象时提示 `Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()` , 且ref值也是空的。

看了下源码因为使用了withConfigConsumer才使Class Component变成了Function Component，原版rc-drawer设置ref没问题。

### What does the proposed API look like?
不在外面加一层Container的情况下，怎么方便拿到Drawer组件对象？

**Comment by yoyo837** [comment]
你让监听 Drawer 的children Container吧，这个是你自己提供的

**Comment by jiangzm** [comment]
@yoyo837 滚动条事件在`ant-drawer-wrapper-body`节点不在children Container上， 除非通过{children Container}.parentNode.parentNode找到

**Comment by yoyo837** [comment]
你控制内部包装容器的高度，转移一下滚动对象，使`ant-drawer-wrapper-body`不滚动
