### ISSUE TITLE
ExpandAll props for ant-tree

### ISSUE THREAD

**Issue by Nilanth** [ant-design/ant-design#18864]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ExpandAll props make the tree controlled to expand and collapse all using single prop because expandedKeys props is not convenient if  have more than thousands of nodes . 

### What does the proposed API look like?
There would be a ExpandAll boolean  props if it is true all the nodes are expanded or on false all are collapsed

**Comment by afc163** [comment]
I believe `expandedKeys` is more accurate.

https://github.com/ant-design/ant-design/issues/12669#issuecomment-430126753

**Comment by Nilanth** [comment]
> I believe `expandedKeys` is more accurate.
> 
> [#12669 (comment)](https://github.com/ant-design/ant-design/issues/12669#issuecomment-430126753)

If there are Thousands of data how to we need pass all 1000 key to expand all
