### ISSUE TITLE
Form onChange inconsistent, not triggered when Select field changes

### ISSUE THREAD

**Issue by rodrigolive** [ant-design/ant-design#18867]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1r202)

### Steps to reproduce
The `onChange` event in `<Form onChange={ () => ... } /> ` is triggered when an `<input />` field data changes, but not when a `<Select />` value changes. The link, which uses code from the Antd documentation, exemplifies the problem. The "form changed!" console message is only shown when the `<input />` changes, but not when the `<Select />` changes. 

### What is expected?
`onChange` should be consistent across all form fields. For instance the `getFieldDecorator({ rules:[ { validator: ... } ] })` validator is triggered every time the `Select` or `input` changes, which is correct, but the Form `onChange` is inconsistent.

### What is actually happening?
The `<Form />` event `onChange` is only triggered when an `<input />` field is modified. We are following the example from this link  https://github.com/ant-design/ant-design/blob/master/components/form/demo/customized-form-controls.md#en-us in the Ant Design documentation.

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.8.6 |
| System | MacOS 10.14 |
| Browser | Chrome 76 |

**Comment by afc163** [comment]
There is no `onChange` we have provided in Form, try `onValuesChange`: https://codesandbox.io/s/distracted-wind-2103c

**Comment by lust-for-code** [comment]
Please provide a solution to it @afc163. CodeSandbox link has errors.

**Comment by hansiemithun** [comment]
Is there a fix for this? form onChange or onValuesChange, both doesnt work with Select Items

**Comment by zgq354** [comment]
Using `onValuesChange` works, it is because `onChange` is an event handler for the `<form />` DOM element, and it is triggered only when a form DOM element such as `<input />` changes, but the `<Select />` component does not render a form element so it not triggered the Change Event.

<img width="831" alt="image" src="https://user-images.githubusercontent.com/9024954/226271969-e47e8ac5-61ae-46e6-aa3e-2e2620d01fdd.png">
