### ISSUE TITLE
table 组件中 rowSelection 设置onChange 传值问题

### ISSUE THREAD

**Issue by jonnyhaha** [ant-design/ant-design#1886]
在使用rowSelection.selectedRowKeys 来控制选中项的例子如果出现分页，会出现传值问题：

const rowSelection = {
      selectedRowKeys,
      onChange: this.onSelectChange,
    };
onSelectChange(selectedRowKeys,selectedRows) {
    console.log('selectedRowKeys changed: ', selectedRowKeys,'selectedRows',selectedRows);
    this.setState({ selectedRowKeys });
  }
如果table有分页，在选择新的一页的时候，selectedRows会重新初始化，没有保留以前选择记录，而selectedRowKeys可以保存以前选择记录。

**Comment by afc163** [comment]
selectedRowKeys 是受控属性，保存在父组件里了。selectedRows 只是个参数，没有状态。
