### ISSUE TITLE
Modal's destroyOnClose attribute is no longer valid in Hooks

### ISSUE THREAD

**Issue by elmelloi** [ant-design/ant-design#18872]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/great-kalam-f1w3s)

### Steps to reproduce
1. Click on the open button to open Modal
2.  Click Button 'change Text'
3.  'hehe' becomes 'xixi' in the first line
4.   Close Modal and  open it again 
5.   first line content  is still 'xixi'

### What is expected?
first line content  is 'hehe',Hooks  should be destroyed in  DestroyOnClose properties is true

### What is actually happening?
first line content  is 'xixi',Hooks are not destroyed, the changed contents are still there in  DestroyOnClose properties is true

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | react 16.8.6 |
| System | win 10 |
| Browser | Chrome 76 |

**Comment by afc163** [comment]
I think you have a misundertand about the `destroyOnClose`, it only destory the Modal children and any state inside it.

<img width="551" alt="image" src="https://user-images.githubusercontent.com/507615/65123216-510d9300-da25-11e9-82bf-f57864493a6a.png">

`text` is a state of App component which is outside Modal, we shouldn't update it.
