### ISSUE TITLE
Checkbox使用 控制台输出Warning

### ISSUE THREAD

**Issue by zhenzong** [ant-design/ant-design#1887]
我在代码中使用：
```
import { Checkbox, message } from 'antd';
import 'antd/lib/index.css';

var Agreement = React.createClass({
    render: function() {
        var text = this.props.isAgreed ? '我已经同意安全协议' : '同意安全协议';
        return (
            <Checkbox
                defaultChecked={this.props.isAgreed} 
                onChange={ this.props.onAgreementCheck}>
                {text}
            </Checkbox>
        );
    }
});
```
控制台提示：
Warning: input is a void element tag and must not have `children` or use `props.dangerouslySetInnerHTML`. Check the render method of Checkbox.

antd版本：^0.12.17
浏览器： safari

但是同样在safari上看官方的例子，并没有这个Warning， 是我哪里写错了？求指导。

**Comment by afc163** [comment]
http://ant.design/#/docs/react/changelog?scrollTo=1.0.0

注意版本，看看升级文档。

**Comment by zhenzong** [comment]
升级版本的改动太大，1.0.0 和 react-bootstrap 的 布局  系统的 似乎 是冲突了。  虽然是想去掉react-bootstrap了，但是现在还没有办法全部完成。 

那意思是低版本里的CheckBox 是存在这个问题吗？

**Comment by afc163** [comment]
升级文档里写的很清楚了吧，用 0.12 就去看 0.12 的文档。

https://github.com/ant-design/ant-design/issues/1645#issuecomment-218383842
