### ISSUE TITLE
list里description的宽度会根据actions的变化而变化

### ISSUE THREAD

**Issue by wangchong19940101** [ant-design/ant-design#18874]
![image](https://user-images.githubusercontent.com/30942709/65126270-5371ec00-da29-11e9-83ec-ae2c9e3eabe1.png)

**Comment by wangchong19940101** [comment]
@afc163

**Comment by yoyo837** [comment]
你直接忽略了上面的提示么？

**Comment by wangchong19940101** [comment]
@yoyo837  大哥，我这个问题是bug吗？

**Comment by yoyo837** [comment]
> 为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 issue 助手 来创建 issue 以方便我们定位错误。谢谢配合！

http://new-issue.ant.design
