### ISSUE TITLE
Input  with props onChange， then when you entering Input will onBlur

### ISSUE THREAD

**Issue by wcl1ll** [ant-design/ant-design#18875]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://106.15.26.10:10080/main/expense-parent-report/expense-report](http://106.15.26.10:10080/main/expense-parent-report/expense-report)

### Steps to reproduce
antd-design Input  有onchange事件时输入失去焦点

### What is expected?
Input 不失去焦掉

### What is actually happening?
Input 失去了焦点

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 2 |
| System | ios |
| Browser | chrome |

**Comment by afc163** [comment]
不可能是 antd Input 的问题，请排查业务代码。
