### ISSUE TITLE
list里description的宽度会根据actions的变化而变化

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#18876]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-jones-mye0l)

### Steps to reproduce
请查看后面的布局

### What is expected?
我希望不要因为后面的actions的内容而影响整体布局

### What is actually happening?
而实际布局错乱了

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.6 |
| System | mac |
| Browser | 谷歌 |

---
请大佬解答

**Comment by yoyo837** [comment]
给你右侧添加样式 固定宽
```css
.ant-list-item-action {
    width: xxx
}
```

**Comment by ISBN9527** [comment]
好，很赞。
