### ISSUE TITLE
TreeSelect shoud support removeIcon property

### ISSUE THREAD

**Issue by luqimin** [ant-design/ant-design#18870]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`<TreeSelect/>` component should aslo support `removeIcon` property just like `<Select />`

### What does the proposed API look like?
```jsx
<TreeSelect removeIcon={<MyNaughtyIcon />} />
```

**Comment by afc163** [comment]
```
<TreeSelect clearIcon={<MyNaughtyIcon />} />
```

We will keep it undocumented cause we don't encourage to change it.

**Comment by luqimin** [comment]
> ```
> <TreeSelect clearIcon={<MyNaughtyIcon />} />
> ```
> 
> We will keep it undocumented cause we don't encourage to change it.

Sorry, but was it possible to make `removeIcon` configurable just like `clearIcon`? These two are definitily different functions. `removeIcon` was omitted in the source codes.

**Comment by afc163** [comment]
Sorry for closing it, you are right, could you send us PR to make it work? and keep it undocumented as well, just like Select.
