### ISSUE TITLE
Scrollbar in Table Header in IE11 when scroll y value is set in Table

### ISSUE THREAD

**Issue by ObscureStrength** [ant-design/ant-design#18879]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-j6n0n?fontsize=14)

### Steps to reproduce
Load up a Table and make sure the scroll attribute is filled with the y value.

e.g. `<Table columns={columns} dataSource={data} scroll={{ x: 1300, y: 1000 }} />`

### What is expected?
The Table Header has no scrollbar

### What is actually happening?
The Table Header has a scrollbar

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.8 |
| System | Windows 10 |
| Browser | Internet Explorer 11 |

**Comment by afc163** [comment]
Could you provide screenshot of it?

**Comment by ObscureStrength** [comment]
On Chrome
<img width="1347" alt="Screenshot 2019-09-18 at 5 01 57 PM" src="https://user-images.githubusercontent.com/28682648/65206843-743a5000-dac2-11e9-85ae-2b3c690fdf4e.png">

On IE11
![Screenshot 2019-09-18 at 5 01 40 PM](https://user-images.githubusercontent.com/28682648/65206813-5967db80-dac2-11e9-9ccd-0c48ee7c1639.png)

**Comment by afc163** [comment]
Could you provide a reproduce demo, because codesandbox cannot work in IE11.

**Comment by caowenhai888** [comment]
我也有相同的问题   table 设置 y轴滚动的时候错位

**Comment by caowenhai888** [comment]
chrome 也是如此

**Comment by ObscureStrength** [comment]
Sorry that it took a while but I made a repo that showcases the issue in IE11:
https://github.com/ObscureStrength/antd-18879-ie11-scrollbar-in-table-header-y-val-set

![ie11](https://user-images.githubusercontent.com/28682648/65413407-f8266c00-de23-11e9-983a-d646540c1c9d.png)

It also shows up on Microsoft Edge.
![edge](https://user-images.githubusercontent.com/28682648/65413424-007ea700-de24-11e9-8357-7eb01586dbe0.png)

**Comment by yoyo837** [comment]
#4637
#5274
#6800
#8414
#9952
#13994
#16950
react-component/table#333

**Comment by ObscureStrength** [comment]
Currently solved with
```
.ant-table-header {
  overflow-y: auto !important;
}
```

**Comment by fgblomqvist** [comment]
What's the status of this issue? Seems like something fairly simple to fix?

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/6800#issuecomment-314427186
