### ISSUE TITLE
Show placeholder instead of selected value

### ISSUE THREAD

**Issue by Triyugi** [ant-design/ant-design#18883]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
What is happening is that when first time the component is loaded it shows placeholder but when I select some value and then again trying to change, then at the place of placeholder selected value is showing. That is correct as per default behavior. But I would like to show placeholder every time the select box is clicked. It will be helpful in the case when we have to use fields without label to identify which field we are editing.

### What does the proposed API look like?
It can be solved by making `allowClear` option automatic. Current we have to click on clear button to clear values but it can be altered to take values as:

`allowClear='auto'`

Or by making another option to select as:

`allowClear`

`autoClear={true/false}`

**Comment by Triyugi** [comment]
Asked [related question on stackoverflow.com](https://stackoverflow.com/questions/57991960/show-placeholder-instead-of-selected-value).

**Comment by afc163** [comment]
I am afraid we won't provide feature like this, we should keep `allowClear` simple.

**Comment by Triyugi** [comment]
OK. Then if you can look into second option:

`autoClear={true/false}`
