### ISSUE TITLE
Notification的description过长时被截断了

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design#18880]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Notification的description过长时被截断了

### What does the proposed API look like?
[链接](https://codesandbox.io/embed/trusting-hoover-vwnno)

**Comment by afc163** [comment]
建议自行包裹 div 加样式来处理超长字符。

**Comment by afc163** [comment]
FYI, if you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
