### ISSUE TITLE
<Select /> component seems to use wrong LESS variable

### ISSUE THREAD

**Issue by mgilarmo** [ant-design/ant-design#18886]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
Example when '@text-color': '#ffffff' and '@input-color': 'fade(@black, 65%)',
[https://drive.google.com/file/d/1RSlxT7D1yB-a4iZHk5u0qwQqQjnJeOmC/view?usp=sharing](https://drive.google.com/file/d/1RSlxT7D1yB-a4iZHk5u0qwQqQjnJeOmC/view?usp=sharing)

Example when '@text-color': 'red' and '@input-color': 'fade(@black, 65%)',
[https://drive.google.com/file/d/1i39RjEwcViCQUsyx756W_3GzbXa77PaY/view?usp=sharing](https://drive.google.com/file/d/1i39RjEwcViCQUsyx756W_3GzbXa77PaY/view?usp=sharing)

### Steps to reproduce
Change the LESS variables as such:
'@text-color': 'red',
'@input-color': 'fade(@black, 65%)',

Then, add a Select component in a Form.

### What is expected?
I expect that the <Select /> component renders with styling similar to other inputs.  For example, using the same font color.

### What is actually happening?
It looks like the <Select /> component renders using the '@text-color' LESS variable instead of the '@input-color' variable

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.9.0 |
| System | macOS 10.14.6 |
| Browser | Chrome Version 76.0.3809.132 |

---
In the Google Drive screenshot I provided, notice that the font color of the 'City' input field is rgba(0, 0, 0, 0.65).  However, the font color of the Select options is #ffffff (my custom override).  This is the same color as my customized '@text-color'.  If I change '@text-color': 'red', then the font color in the Select component changes to red as well.  I expect Select to use '@input-color' ... OR maybe its own variable '@select-item-text-color'

**Comment by zombieJ** [comment]
`@input-color` is what used on `<input />` sub component and not the dropdown item color. Dropdown item color is follow the `@text-color`.

**Comment by mgilarmo** [comment]
But, why is this true?  Isn't <select> a type of input?  You use it to
collect user data.  Shouldn't Select use the same font color as Input?

Is there a way to change the color of the text displayed in the <Select>
component without changing the overall @text-color?
[image: image.png]

**Comment by zombieJ** [comment]
You can help to create a PR with new less variable to handle this instead of reuse current variable : )

**Comment by mgilarmo** [comment]
Will do! Thanks!
