### ISSUE TITLE
DatePicker无法选择年份

### ISSUE THREAD

**Issue by heyizhiyuan** [ant-design/ant-design#18899]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/heyizhiyuan/pen/GRKYaVm?editors=0010](https://codepen.io/heyizhiyuan/pen/GRKYaVm?editors=0010)

### Steps to reproduce
https://codepen.io/heyizhiyuan/pen/GRKYaVm?editors=0010

### What is expected?
日期组件能正常选择年份

### What is actually happening?
日期组件无法选择年份

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 15.4.0 |
| System | Windows NT 10.0; Win64; x64 |
| Browser | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E6%8C%87%E5%AE%9A%E4%BA%86-DatePicker/RangePicker-%E7%9A%84-mode-%E5%B1%9E%E6%80%A7%E5%90%8E%EF%BC%8C%E7%82%B9%E5%87%BB%E5%90%8E%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E5%B9%B4%E4%BB%BD/%E6%9C%88%E4%BB%BD%EF%BC%9F
