### ISSUE TITLE
ie8 下报 缺少‘：’

### ISSUE THREAD

**Issue by xfcf1** [ant-design/ant-design#1889]
```js

	  return { take: take, put: put, close: close,
	    get __takers__() {
	      return takers;
	    },
	    get __closed__() {
	      return closed;
	    }
	  };
	}
```
	

这里报错SCRIPT1003: 缺少 ':'
文件: index.js，行: 6424，列: 10

要怎么弄？

**Comment by benjycui** [comment]
这行代码应该不是 `antd` 里面的，请确认你自己或你依赖的其它库没有使用 getter

See: https://babeljs.io/docs/usage/caveats/#getterssetters-8-and-below

**Comment by benjycui** [comment]
已确认不是 `antd` 里的代码，关了。

**Comment by xfcf1** [comment]
谢谢。

不过我没有在antd-init （type是redux的）项目里面加任何自己的东西。就是起项目，按照指示把配置改成支持ie8的。

如果用type是plain-react的，自己加上redux了以后也会报错。
还请大神有时间跑一下antd-init redux ie8下的例子。。。

**Comment by afc163** [comment]
type 为 `redux` 的脚手架依赖了 redux-saga，这玩意不支持 IE8 https://github.com/yelouafi/redux-saga/issues/313

另外，react 和 react-router 的最新版本也不支持 IE8。

你可以使用 type 为 `plain-react` 的脚手架，并进行兼容改造 https://github.com/ant-design/antd-init#dont-work-in-ie8-
