### ISSUE TITLE
Form.validateFields错误

### ISSUE THREAD

**Issue by readyou** [ant-design/ant-design#1890]
```jsx
 <Input id="name" {...nameProps} value={this.state.name} defaultValue={this.state.name} onChange={this.handleNameChange}/>
```
通过如上方式设置input来取得初始值与输入值，显示正常。

但初始化的时候form.validateFields((error, data) => {})中的data为null，而不是初始化出来的字段的值。从而导致如果没有值的修改，form的验证就会失败。

**Comment by benjycui** [comment]
麻烦再认真看下文档，谢谢 http://ant.design/#/components/form?scrollTo=this.props.form.getFieldProps%28id%2C+options%29

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
