### ISSUE TITLE
用Form getFieldDecorator 包围创建的子组件，rules会一直校验

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design#18905]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
父组件：
{getFieldDecorator("radio", {
rules: [{ required: ques && ques.required, message: '请选择!' }],
})(

)}
子组件RadioCom：
<Radio.Group>
1
</Radio.Group>

### What is expected?
在子组件中选择后，提交表单，可以校验通过

### What is actually happening?
在子组件中选择后，提交表单，校验不通过，一直提示没有选择

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | react |
| System | MAC |
| Browser | Chrome |

**Comment by liangchaofei** [comment]
复现链接：https://codesandbox.io/s/eloquent-hertz-h39kt

**Comment by liangchaofei** [comment]
![image](https://user-images.githubusercontent.com/37739354/65297763-9fdd3900-db9b-11e9-802d-1da1d1c7a214.png)
父组件包含子组件，即使选择了单选项，rules一直提示没有选择

**Comment by afc163** [comment]
这不是 antd Form 的问题，你需要仔细研习一下自定义表单控件的写法：https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by liangchaofei** [comment]
> 这不是 antd Form 的问题，你需要仔细研习一下自定义表单控件的写法：https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

看了文档，文档中需要对需要的条件做判断。我这的需求是：一个表单中有多个动态渲染的单选组合，有的单选组合需要必选，有的不需要。这种情况下，有什么办法吗
