### ISSUE TITLE
Tree Component Support TreeNode Label Click Action

### ISSUE THREAD

**Issue by IsmetAkyurek** [ant-design/ant-design#18908]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, TreeNode labels doesn't support collapsing it's tree by clicking. I believe it would be better if we could define it's behavior whether it would check, select or collapse the node. 

### What does the proposed API look like?
`<Tree onLabelClick="collapse" />`

**Comment by afc163** [comment]
Try `<Tree title={<div onClick={xxx}>title</div>} />`

**Comment by tewarig** [comment]
hi @afc163  can you tell me some work around in <TreeNode /> ?
