### ISSUE TITLE
DatePicker onBlur 乱回调

### ISSUE THREAD

**Issue by iwangx** [ant-design/ant-design#18913]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/52z5zpxzqx)

### Steps to reproduce
把代码复制到重现链接里面看控制台
```

import React from 'react';
import ReactDOM from 'react-dom';
import 'antd/dist/antd.css';
import './index.css';
import { DatePicker } from 'antd';

function onChange(date, dateString) {
  //console.log(date, dateString);
}

function onBlur(){
  console.log('onBlur')
}

ReactDOM.render(
  <div>
    <DatePicker showTime onBlur={onBlur} onChange={onChange} />
    <br />
  </div>,
  document.getElementById('container'),
);
          
          
```

### What is expected?
期望在点击日期或者时间的时候不要执行onBlur回调

### What is actually happening?
每次点击日期或者时间，或者其他操作都会执行onBlur回调

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.7.0 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
similar to #11249

**Comment by afc163** [comment]
BTW @iwangx, you can save the codesandbox.

**Comment by iwangx** [comment]
@afc163 复制那个代码到codesandbox 里面就可以了，只要是点击具体日期都会出发onBlur的回调，这是个大问题啊，我其实是选了值，但是并没有失去焦点啊？

**Comment by iwangx** [comment]
@afc163 
![image](https://user-images.githubusercontent.com/11516318/65302198-f99a2f00-dbac-11e9-9256-6429bee9c6f0.png)
我猜测是这个文本框失焦导致的回调，因为这个也是一个input，并且是获得焦点的

**Comment by afc163** [comment]
trace #11249
