### ISSUE TITLE
`Option` in `Select` throwing warning

### ISSUE THREAD

**Issue by aihornmac** [ant-design/ant-design#1891]
## What you did

```
...
const Option = Select.Option;
...
<Select
  combobox
  defaultActiveFirstOption={true}
  value={this.state.keywords}
  onSearch={this.onKeywordChange}
  filterOption={yep}
  children={this.props.viewer.suggestion.map(
    ({ text }) => <Option key={text}>{this.highlightKeyword(text)}</Option>
  )}
/>
...
```

## What you would like to happen

render without issues

## What actually happened

warnings were thrown, same number as how many `Option`s were rendered.
```
Warning: the children of `Select` should be `Select.Option` or `Select.OptGroup`, instead of `Option`.
```

## Online demo

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information

- The version of antd: 1.1.0
- Your operating system and it's version: OS X 10.10.5
- Your browser and it's version: 50.0.2661.102 (64-bit)50.0.2661.102 (64-bit)

**Comment by hypocenter** [comment]
Me too...

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by aihornmac** [comment]
@benjycui I can't reproduce it, yet I tracked down the error stack, and found the error was thrown [here](https://github.com/react-component/select/blob/779502753b3db315a772ba4a6c892196ac0d3e3b/src/FilterMixin.js#L50-L54). I reckon the info shall be sufficient. Could you help out to check this?

**Comment by benjycui** [comment]
Both of `child.type.constructor` and `Option.constructor` are `Function`, it is meaningless to check this condition.

It's just a warning, just ignore it.

**Comment by benjycui** [comment]
Actually, I don't understand why you wrap `Select.Option`, it's just a carrier and it will be throw away after `Select` get all the information.

**Comment by aihornmac** [comment]
@benjycui I didn't do it intentionally. It was the hot reload module that wrapped up components automatically. Although it can be ignored, the keep-throwing warnings kinda interfere with other info printed in console. I would love it if it throws no warnings.

**Comment by benjycui** [comment]
Yep, it's annoying. But this warning is used for debugging, so I am not going to remove it. Sorry.

**Comment by knightf** [comment]
@benjycui 可以解释一下为什么需要留着这个语句debug么？因为在`Select`组件下面试图渲染非`Option`节点都会报错，我没有看到它有什么在debug上的意义。

**Comment by benjycui** [comment]
See: https://github.com/ant-design/ant-design/issues/1521
