### ISSUE TITLE
input.password使用后，跳转的后画面无法渲染

### ISSUE THREAD

**Issue by cx5168** [ant-design/ant-design#18917]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在A画面中使用input.password控件，点击按钮通过navlink跳转到B画面，URL显示已正确跳转，但是B画面空白显示。请问怎么解决这个问题？
package.json:
"antd": "^3.22.1",
"moment": "^2.24.0",
"react": "^16.9.0",
"react-app-polyfill": "^1.0.2",
"react-dom": "^16.9.0",
"react-router-dom": "^5.0.1",
"react-scripts": "3.1.1"
使用：
<Input.Password
allowClear
visibilityToggle={false}
placeholder="input the password"
prefix={<img src={require("../images/logo192.png")} style={{ width: 16, height: 16 }} alt="" />}
style={{ width: '20%', height: 40, marginTop: '2%' }}
/>

### What does the proposed API look like?
如果我把input.password控件注释掉，能正常跳转并显示画面

**Comment by yoyo837** [comment]
把你的prefix 注释掉试试

**Comment by cx5168** [comment]
试过了，只剩下placehold。问题依旧

**Comment by yoyo837** [comment]
提供的信息太少，只能靠你自己。

**Comment by cx5168** [comment]
目前曲线解决：<input type="password" ..../>

**Comment by yoyo837** [comment]
@cx5168 你是绕过了未发现的问题，不是解决问题的根本原则。除非时间不允许。

**Comment by cx5168** [comment]
确实没实质解决，不过没时间了。先将就吧

**Comment by cx5168** [comment]
做个新画面，代码如下，问题依旧。
import React, { Component } from 'react';
import { Input, Icon } from 'antd';
import { NavLink } from 'react-router-dom';
class temp extends Component {
    render(){
        return(
            <div style={{
                width: '100vw', height: '100vh', backgroundColor: '#fff',
                display: 'flex', flexDirection: 'column', alignItems: 'center'
            }}>
                <Input.Password/>
                    <NavLink to={{ pathname: "/calendar", state: { activedKey: 1 } }}>
                <div style={{width: 100, height: 200, backgroundColor: 'red'}}>

                </div>
                </NavLink>
            </div>
        )
    }
}

export default temp;

**Comment by yoyo837** [comment]
提供在线重现demo吧

**Comment by cx5168** [comment]
出问题的版本是 antd: 3.22.1,  
升级到最新版本：  antd: 3.23.3.  问题解决。
