### ISSUE TITLE
Docs - Upload component default props data description is not clear enough

### ISSUE THREAD

**Issue by plainnany** [ant-design/ant-design#18911]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when I using `Upload` and set props `data={{ myParams }}`,  I find ajax request params contains default params `file` , and docs description about data is `Uploading params or function which can return uploading params. `, I think it better be described as `Uploading extra params or function which can return uploading extra params`

### What does the proposed API look like?
docs about upload props data is better to be described as  'Uploading *extra* params or function which can return uploading *extra* params'

**Comment by shaodahong** [comment]
closed via #18915
