### ISSUE TITLE
Config table selection box on the right

### ISSUE THREAD

**Issue by Lingxiao-Ma** [ant-design/ant-design#18912]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Current table selection box is on the left, I am wondering if we can expose an API to make it on the right

### What does the proposed API look like?
Add a new prop in TableRowSelection?

**Comment by afc163** [comment]
I suggest you customize selection column of  right position by using `render`.

**Comment by Lingxiao-Ma** [comment]
> My suggestion is you can customize selection column of right position by using `render`.

thanks for the prompt feedback, as always.
can you be more specific or point me an example? I didn't find a way to hook into selection render process...
