### ISSUE TITLE
Ant table with tree data displays expand icon on empty children

### ISSUE THREAD

**Issue by Nilanth** [ant-design/ant-design#18928]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/naughty-hofstadter-u81hv)

### Steps to reproduce
Check the above link and see the Empty children name which displays expand icon when the children in empty

### What is expected?
When children is empty expand icon should not be displayed

### What is actually happening?
When the children is empty array the expand icon is displayed

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.9 |
| System | All |
| Browser | All |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941

**Comment by WilliamPriorielloGarda** [comment]
This issue is still reproducible on my current version (^4.6.6)

https://codesandbox.io/s/black-silence-hfyoo

**Comment by WilliamPriorielloGarda** [comment]
I suggest re-opening this one if you agree
