### ISSUE TITLE
Input key events should return value

### ISSUE THREAD

**Issue by jurajkocan** [ant-design/ant-design#18926]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
restrict user to write something in to the input eg. dont allow to write uppercase, numbers or anything i want to

from ts definition this is void function.

onKeyPress?: ((event: React.KeyboardEvent<HTMLInputElement>) => void) | undefined

### What does the proposed API look like?
same but these events should return function value

onKeyPress?: ((event: React.KeyboardEvent<HTMLInputElement>) => boolean) | undefined

and in implementation you should add these props in to the input as a return value 

<input type="text" onkeypress="return props.onKeyPress()()" />

**Comment by jurajkocan** [comment]
[as this example](https://www.qodo.co.uk/assets/files/uploads/javascript-restrict-keyboard-character-input.html) you would be able to restrict anything

**Comment by yoyo837** [comment]
For form item: https://reactjs.org/docs/forms.html#controlled-components  This should be more suitable!

**Comment by jurajkocan** [comment]
@yoyo837  this issu is about to provide classic html5 behavior. Now its force me to use state like this even i dont need it

**Comment by jurajkocan** [comment]
[as it sais in documentation](https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue)

Note: While returnValue has been adopted into the DOM standard, it is present primarily to support existing code. You should use preventDefault(), and defaultPrevented instead of this historical property.

using preventDefault is right and working. I close issue.
