### ISSUE TITLE
would be great to have some themes and a theme builder

### ISSUE THREAD

**Issue by chris-a-g** [ant-design/ant-design#1892]
First of all congrats on creating this framework, you've done an excellent job. 
Themeing is a pretty common requirement, and while it is possible to do so by hand, it would be great to be able to drop in a couple of pre-built css themes (light, dark), and eventually have a theme builder like kendo ui has. I might work on this if I have time, if I do I'll share what I come up with. 
Thanks for your work, keep it up!

**Comment by ddcat1115** [comment]
Thank you for your suggestion!

The original intension of Ant Design is to improve development efficiency, by presetting an obvious ‘And Design’ style. So, we only support(and recommend) the default theme at this stage.

Now our designers are combing the variables of the style, we will offer a certain degree of freedom to customize your theme in the futrue, at that time the frame will also provide the corresponding unified support.

**Comment by neekey** [comment]
Sorry to comment in a closed issue! 

I just created a still very rough version of [Ant Design Theme Builder](https://insiight.github.io/ant-design-theme-builder/#/button),  just in case anyone would need it.

It is based on Less.js (compile less in browser), so the initial load will be a little slow, give it a little patient.
