### ISSUE TITLE
Alert 组件 文字 换行 效果有问题 看图

### ISSUE THREAD

**Issue by suyunlongsy** [ant-design/ant-design#18923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/suyunlongsy/pen/VwZVxKQ](https://codepen.io/suyunlongsy/pen/VwZVxKQ)

### Steps to reproduce
![GitHub Error](https://github.com/suyunlongsy/imgs/blob/master/alert%20issue.jpg?raw=true)

### What is expected?
正常折行 word-break break-all 

### What is actually happening?
没有正常折行

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | codePen |
| System | codePen |
| Browser | codePen |

**Comment by suyunlongsy** [comment]
![word-break](https://user-images.githubusercontent.com/25949206/65369424-261e7b80-dc7f-11e9-80c1-c60dd4bff65d.jpg)

这个留白的效果 可以接受吗

**Comment by shaodahong** [comment]
`word-break` 和 `word-wrap` 的区别就在首次换行，我看了下大多数的处理确实都是 `word-break: break-word`, 比如你看 GitHub 的处理

`java.sql.SQLException: Could not open client transport with JDBC Uri: jdbc:hive2://192.168.xx.xxxx:10000/quick_start_dev_db;principal=hive/_HOST@HADOOP.COM: GSS initiate failed`
