### ISSUE TITLE
the maxTextLength in tree-select component is a hidden or unpublished prop?

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#18920]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to ask whether the maxTextLength in tree-select component is a hidden or unpublished prop

我想问一下maxTagTextLength是不是一个隐藏的prop，最近在使用form的时候给select加上了maxTagTextLength，然后尝试在treeSelect组件上加上，prop是有效的，但是存在一些问题，它对指定maxTagCount下的maxTagPlaceholder内容也进行了截取，与select的api表现不一致

### What does the proposed API look like?
x

**Comment by zombieJ** [comment]
`maxTagTextLength` 在 antd 的 TreeSelect 中并没有暴露出来，这个在 v4 会统一逻辑。

**Comment by zombieJ** [comment]
merge into #16911
