### ISSUE TITLE
Layout (in particular Footer) doesn't work properly

### ISSUE THREAD

**Issue by Piero87** [ant-design/ant-design#18931]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-e1okh)

### Steps to reproduce
If you open the preview you can see that the footer is over the Content

### What is expected?
The footer stay in position

### What is actually happening?
The footer cover the content

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.8.6 |
| System | Mac OS Mojave |
| Browser | Chrome 76.0.3809.132  |

**Comment by Piero87** [comment]
I have also this error that I cannot reproduce on the sandbox, the left and right arrow of the paging is not vertical aligned. I attach an image

<img width="193" alt="Schermata 2019-09-20 alle 18 33 28" src="https://user-images.githubusercontent.com/768952/65343434-48f45580-dbd5-11e9-99af-b1dd41ad887a.png">

**Comment by mjfwebb** [comment]
Looks like the issue is being caused `min-height: 0;` in `.ant-layout-content`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/12295

cc @scharepmc2hr

**Comment by scharepmc2hr** [comment]
@afc163, I've just seen your message now. sorry I missed the notifications.
I think the problem doesn't come from ```min-height``` property.

Check it:
<img width="1440" alt="Screen Shot 2019-10-07 at 3 22 56 PM" src="https://user-images.githubusercontent.com/22997685/66309420-73a11680-e916-11e9-81b3-ee71b63501fb.png">
