### ISSUE TITLE
Select does not scroll on keyboard events

### ISSUE THREAD

**Issue by smajl** [ant-design/ant-design#18939]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select/](https://ant.design/components/select/)

### Steps to reproduce
Use any Select directly from demo page where options overflow the dropdown, e.g. the "Search box" example.
1) type e.g. "a" to get plenty of results
2) press down arrow key until the highlight/selection exits the scrolled area
3) observe

### What is expected?
That Select's dropdown will auto-scroll to keep highlight (selection) visible.

### What is actually happening?
The dropdown does not scroll to keep selection in viewport, therefore rendering the keyboard navigation completely useless.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | Windows 10 |
| Browser | Chrome 76.0.3809.132 |

---
This works in antd 2.x, therefore this is a regression.

**Comment by vanphudhsp2015** [comment]
May I ask you. Has the fix been uploaded yet? And upload how many versions

**Comment by afc163** [comment]
Try to remove `node_modules` and `yarn.lock` and `package-lock.json` then reinstall.

**Comment by vanphudhsp2015** [comment]
Thanks
