### ISSUE TITLE
Table should be able to have a caption

### ISSUE THREAD

**Issue by snirp** [ant-design/ant-design#18934]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently there is no way to add a caption tag to a table that is generated by Ant design.

### What does the proposed API look like?
Add an optional `caption` property to the Table api. It should accept a ReactNode (or perhaps a function that renders a ReactNode). The content should appear inside a <caption> tag as the first child of the <table> tag.

**Comment by zombieJ** [comment]
Could you describe more detail about what `caption` will do?

**Comment by afc163** [comment]
Closing for no response.
