### ISSUE TITLE
Switch组件如何在onChange事件里阻止checked？

### ISSUE THREAD

**Issue by wzlee** [ant-design/ant-design#18930]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在设置开关的时候可能由于某些判断逻辑错误导致操作不能生效，但开关还是无法控制，会自动根据点击操作改变

### What does the proposed API look like?
onChange事件支持返回一个Promise来支持开关可以被阻止开启或关闭

**Comment by shaodahong** [comment]
`Switch` 是受控组件，可以设置 `checked` prop 来控制

**Comment by yoyo837** [comment]
受控就可以了，想怎么操作就怎么操作

**Comment by wzlee** [comment]
@shaodahong @yoyo837 我是table里渲染的行里用switch,如果用state来控制会导致所有行都会被影响
![image](https://user-images.githubusercontent.com/4182865/65390005-c6fb5c80-dd8d-11e9-8a35-6842e13ef912.png)
我期望能单独控制某个switch组件，能根据请求响应来决定这个组件的开启和关闭

**Comment by yoyo837** [comment]
@wzlee 我们没办法提供React培训噢亲。

**Comment by yoyo837** [comment]
既然每行要分开控制你就每行一个状态嘛

**Comment by wangwufan** [comment]
字段值如果绑定到Swich的checked属性，只能在Swich的onChange里修改数据集然后重新set回去，Swich的显示状态才会变，
> @shaodahong @yoyo837 我是table里渲染的行里用switch,如果用state来控制会导致所有行都会被影响 ![image](https://user-images.githubusercontent.com/4182865/65390005-c6fb5c80-dd8d-11e9-8a35-6842e13ef912.png) 我期望能单独控制某个switch组件，能根据请求响应来决定这个组件的开启和关闭
