### ISSUE TITLE
无法运行ANT DESIGN上面的组件

### ISSUE THREAD

**Issue by RocChiu2015** [ant-design/ant-design#1893]
用web storm运行“快速上手”的例子可以运行成功，网页上面呈现一个日历的组件，但是复制其他组件的代码写在webstorm上面，不能运行，网页上什么也不显示，请问这是怎么回事啊？联系邮箱：nemozp@sina.cn   QQ：387762609

**Comment by ddcat1115** [comment]
请先看下控制台及页面是否有报错？

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by RocChiu2015** [comment]
http://codepen.io/anon/pen/wGOWGW?editors=001  这个东西是我把代码拷进去然后点run就可以了吗？你们就能收到了吗？

**Comment by afc163** [comment]
...Fork 一份。

**Comment by RocChiu2015** [comment]
我用chrome浏览器，上面显示的错误是Uncaught ReferenceError: ReactDOM is not defined

**Comment by afc163** [comment]
呃... 请确保 react-dom 依赖已安装，并且 import 进来了。

**Comment by RocChiu2015** [comment]
fork完了，http://codepen.io/anon/pen/qNBKKG?editors=001

**Comment by RocChiu2015** [comment]
我现在把rect-dom引入了，但是现在报错是Uncaught ReferenceError: mountNode is not defined，fork了我的代码，烦请您帮我查看一下错误，谢谢！http://codepen.io/anon/pen/GqRGYq?editors=001
