### ISSUE TITLE
form 自定义radios组合组件 rules不受控

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design#18938]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-moon-v24gf)

### Steps to reproduce
选择一个单选，点击提交按钮

### What is expected?
在父组件中设置了rules为必选，勾选单选按钮后， 不会提示未选了

### What is actually happening?
在父组件中设置了rules为必选，勾选单选按钮后， 仍然提示未选

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | react |
| System | MAC |
| Browser | Chrome |

**Comment by shaodahong** [comment]
自定义受控组件你要自行处理 value，我看到你没处理

**Comment by liangchaofei** [comment]
> 自定义受控组件你要自行处理 value，我看到你没处理

我这单选是动态生成的，有很多单选组合，有需要必选的，有不需要选的，所以不能处理value吧

**Comment by shaodahong** [comment]
可以的，加个 `onChange` 或者不要包一层壳试试

**Comment by liangchaofei** [comment]
> 可以的，加个 `onChange` 或者不要包一层壳试试

可以提供下demo吗？ 我这加了onchange

**Comment by shaodahong** [comment]
```jsx
<Radio.Group onChange={e => {
  this.props.onChange(e.target.value)
}}>
  <Radio value="a">a</Radio>
  <Radio value="b">b</Radio>
</Radio.Group>
```

**Comment by liangchaofei** [comment]
> ```js-jsx
> <Radio.Group onChange={e => {
>   this.props.onChange(e.target.value)
> }}>
>   <Radio value="a">a</Radio>
>   <Radio value="b">b</Radio>
> </Radio.Group>
> ```

子组件里 我就是这样写的，还是不行
