### ISSUE TITLE
DatePicker default selected dates

### ISSUE THREAD

**Issue by thomasbarone** [ant-design/ant-design#18948]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/datepicker-default-selected-dates-4imdl)

### Steps to reproduce
1. Open the DatePicker
2. Click to browse previous months

### What is expected?
There should be no selected dates on the calendar for previous months.

### What is actually happening?
There is a selected date on each previous month.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Google Chrome Version 77.0.3865.90 |

---
It would be great to have an option to set no default selection! (So there are no highlighted boxes on any month)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6146#issuecomment-308927566
