### ISSUE TITLE
getFieldDecorator 第一个参数 id，可以写嵌套的，我想问源码中哪里是解析成 'a[0].b' => {d:[{b}]} 这种的方法

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#18944]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
想知道怎么具体用的哪个方法

**Comment by zombieJ** [comment]
https://lodash.com/docs/4.17.11#get

**Comment by qq645381995** [comment]
> https://lodash.com/docs/4.17.11#get

我说的不清楚吗？不是 get ，是反过来的。

**Comment by yoyo837** [comment]
@qq645381995 Table组件只取值，当然只与get相关，我猜你需要这个
```js
import lodashGet from 'lodash/get';
import lodashSet from 'lodash/set';
```

他俩一对

**Comment by qq645381995** [comment]
> @qq645381995 Table组件只取值，当然只与get相关，我猜你需要这个
> 
> ```js
> import lodashGet from 'lodash/get';
> import lodashSet from 'lodash/set';
> ```
> 
> 他俩一对

不是，我要的是 Form 提交方法 validateFields 或者调用 getFieldsValue 得到的值。
```
a[0].b.c =>  { 'a': [{ 'b': { 'c': 3 } }] }
```

**Comment by yoyo837** [comment]
那就是上面@zombieJ 的回答。

**Comment by qq645381995** [comment]
> 那就是上面@zombieJ 的回答。

他的是 

```
{ 'a': [{ 'b': { 'c': 3 } }] } =>  a[0].b.c
```

**Comment by yoyo837** [comment]
抱歉，可能没理解你的意思，爱莫能助。🤷‍♂️
