### ISSUE TITLE
关于uxcore

### ISSUE THREAD

**Issue by transtone** [ant-design/ant-design#1894]
今天在微博转发中又看到了 ```阿里巴巴信息平台 UED 团队``` 的 uxcore： https://github.com/uxcore 。请问两个项目有何关系？

看了一下uxcore的源码，发现也是用的 https://github.com/react-component 的组件。

**Comment by afc163** [comment]
https://gitter.im/ant-design/ant-design?at=56e637749f24605773d7d6c0
