### ISSUE TITLE
ConfigProvider supports configuration of global dark mode?

### ISSUE THREAD

**Issue by ppbl** [ant-design/ant-design#18943]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
chrome77 (或许76) 和 ios13 开始支持黑暗模式，（反正就是黑暗模式），我注意到 antd 的官方网站已经开始适配暗风格的样式了，是否可以在 `ConfigProvider` 里面增加一个全局配置，让所有的支持 `theme`  切换的组件（比如 `Layout`）默认从全局配置里面设置。局部优先级高于全局。😊

Chrome77 (maybe 76) and ios13 started to support dark mode (in any case, dark mode), I noticed that the official website of antd has begun to adapt to the dark style, can you add a global configuration in `ConfigProvider`, so that all support The component that `theme` switches (such as `Layout`) is set by default from the global configuration. Local priority is higher than global.😊

### What does the proposed API look like?
比如：
theme   设置主题风格 	`'light'|'dart'`     `'light'`    4.0.0

**Comment by chenshuai2144** [comment]
这样包会非常大的。我们应该不会默认提供。

而且黑色主题是需要开发者适配，这个工作量还是蛮大的。官网适配也做了很久
