### ISSUE TITLE
Button组件的icon属性，可否支持ReactNode类型？

### ISSUE THREAD

**Issue by 303394539** [ant-design/ant-design#18954]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为Icon组件支持createFromIconfontCN和scriptUrl参数，如果Button的icon属性支持ReactNode类型并能使用Icon，这样能增强Button的表现能力，不至于因为Icon不是antd包含的图标就需要开发者自己写一个按钮组件。

### What does the proposed API look like?
<Button icon={< Icon type="Click" />}>Click</Button>

**Comment by shaodahong** [comment]
换种方式

```jsx
<Button><Icon type="Click" scriptUrl /></Button>
```
