### ISSUE TITLE
Todo 实例npm start 报错，Cannot read property 'presets' of undefined

### ISSUE THREAD

**Issue by fighting300** [ant-design/ant-design#1895]
##启动Todo实例，没有运行成功
报错如下：
/Users/qunar/Desktop/Code/Web/QPlatform/node_modules/dora-plugin-hmr/lib/index.js:72
        loader.query.presets.push('react-hmre');
                    ^
TypeError: Cannot read property 'presets' of undefined

## 本地环境信息

- antd 版本:1.1.2
- 操作系统及其版本：ox 10.11.6 Beta
- 浏览器及其版本: chrome

**Comment by ddcat1115** [comment]
node版本？

**Comment by fighting300** [comment]
v5.4.1

**Comment by afc163** [comment]
#1884
