### ISSUE TITLE
希望支持表单组件的呈现态

### ISSUE THREAD

**Issue by janryWang** [ant-design/ant-design#18958]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
考虑到现在的表单页面，大多需要从编辑态切换到呈现态，比如Input切换为呈现态就是一个纯文本展示，类似的还有，Select/NumberPicker/DatePicker等，现在都是用户手动控制的，但是对于一些核心属性的转换还得手工处理，比如Input的innerAfter/addonAfter之类的，所以最好还是官方支持一下比较合适

### What does the proposed API look like?
比如`<Input editable={false}/>`

**Comment by shaodahong** [comment]
您说的这个是大部分公司遇到的，比如 **编辑/查看** 的切换，您应该基于公司的业务状态和需求自行封装一个适合快速落地和快速开发的业务组件

**Comment by janryWang** [comment]
就因为这是个通用需求，而且是通用的交互需求，才应该收敛到组件体系上来

**Comment by yoyo837** [comment]
目前应该不会考虑支持这个想法，就应用内封装一套吧

**Comment by janryWang** [comment]
> 目前应该不会考虑支持这个想法，就应用内封装一套吧

这不应该让应用开发者每次都来处理的，明显是个通用需求，就是具体组件的呈现态，首先，它是个状态型交互

**Comment by janryWang** [comment]
@afc163 @zombieJ 麻烦给点意见吧，因为这个就类似于readOnly的一个状态UI，目前在uform这样的顶层表单解决方案上想要整体的把控呈现态的东西，则需要做蛮多的compat处理，所以期望官方能支持这个能力

**Comment by zombieJ** [comment]
个人感觉 `readOnly` 足够了，如果需要从组件角度出发，应该自行定制。因为除了一些官方的组件，还会有出现自定义组件的需求，对于这类组件，如何展示纯文本是由用户来控制的。
