### ISSUE TITLE
[table] resizable-column conflict with sorter/ 【表格控件】可伸缩列与排序器冲突

### ISSUE THREAD

**Issue by p2227** [ant-design/ant-design#18955]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blissful-hill-zlrsm)

### Steps to reproduce
鼠标调整 Date 列的宽度

### What is expected?
鼠标调整 Date 列的宽度（当鼠标为  col-resize时），不触发Date 列的排序

### What is actually happening?
鼠标调整 Date 列的宽度（当鼠标为  col-resize时），触发了Date 列的排序

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.8.4 |
| System | windows 10  |
| Browser | chrome  76.0.3809.132 |

---
尝试过用 onHeaderCell onClick 方法，但无奈此方法是在排序后才调用的，完全没有控制效果

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14647#issuecomment-467865540
https://github.com/ant-design/ant-design/issues/13335#issuecomment-505409967
