### ISSUE TITLE
Breadcrumb warning with react-router 4

### ISSUE THREAD

**Issue by ouyuran** [ant-design/ant-design#18968]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-72c8t)

### Steps to reproduce
Refresh the demo page

### What is expected?
There should not be any warning.

### What is actually happening?
There is a warning : 
Warning: [antd: Breadcrumb] Only accepts Breadcrumb.Item and Breadcrumb.Separator as it's children 

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9 |
| System | WIN10 |
| Browser | Chrome |

---
Actually, I think the demo code in this page(https://ant.design/components/breadcrumb-cn/) using breadcrumb with react-router@4 doesn't make sense.
In that example code, it trys to decode split url, but react-router can do that for us, check the demo code I offered.
But, there is a warning when I try to run it.
It says that only Breadcrumb.Item can be a child of Breadcrumb, it does make sense in many cases, while with react-router@4, do you guys agree Route is also acceptable?
Because I don't want to split url myself, it might introduce some issues.

**Comment by zombieJ** [comment]
https://ant.design/components/breadcrumb-cn/#components-breadcrumb-demo-router
