### ISSUE TITLE
How can I change the state of Switch Programatically?

### ISSUE THREAD

**Issue by mdsadique2** [ant-design/ant-design#18962]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

So I have a switch which when toggled, makes an API call. if call fails, I want to bring it back to its original state. How can I do that?
---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by keithort** [comment]
You are looking for the `checked` prop. Depending on your implementation will determine how you are setting that prop to true or false.
