### ISSUE TITLE
支持flex-direction: column;吗？

### ISSUE THREAD

**Issue by elaijuh** [ant-design/ant-design#1896]
在Col里希望元素在垂直轴上进行布局，类似`<Col direction="column"></Col>`这样的语法。请问有准备支持吗？

**Comment by ddcat1115** [comment]
直接给 `Col` 加样式就可以实现，`style` 或 `className` 都可以的。

**Comment by afc163** [comment]
有这方面需求可以直接给 PR ~ 🎅
