### ISSUE TITLE
Select Multiple does not show options

### ISSUE THREAD

**Issue by lcorniglione** [ant-design/ant-design#18960]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/wispy-sea-em822)

### Steps to reproduce
Type on select and wait until settimeout resolve the callback. You will see that the option is not displayed into the select.

### What is expected?
See the option rendered into the select.

### What is actually happening?
The option does not appear.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.8.6 |
| System | Linux Ubuntu |
| Browser | Mozilla |

---
If I change the key of the option to key={it.name} the option is displayed, but I need the id as the key of the option.

Related Issue without response: https://github.com/ant-design/ant-design/issues/18840

**Comment by afc163** [comment]
https://codesandbox.io/s/fervent-northcutt-ygss5

```diff
  onChange = value => {
    console.log(value);
+  this.setState({ value });
  };
```

https://reactjs.org/docs/forms.html#controlled-components

**Comment by oceandrama** [comment]
I can reproduced it too. When I use number or smth that can be convert to number as key  - options doesn't display
