### ISSUE TITLE
How to import Ant Design components without default class names?

### ISSUE THREAD

**Issue by amerllica** [ant-design/ant-design#18963]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/58070076](https://stackoverflow.com/questions/58070076)

### Steps to reproduce
<Title className="root-23-07">....

### What is expected?
I wanna my class name CSS override the default.

### What is actually happening?
I pass `className` to the Title component of Typography but the default component class name is `.ant-typography` and its less file CSS selection started with `h4.ant-typography` and it causes my class name `.root-23-07` doesn't override the default. actually CSS selection with tag name ruins everything.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | Mac OSX |
| Browser | Google Chrome 77 |

---
If I import the Ant Design component without its default class name I definitely can reach my goal.

**Comment by afc163** [comment]
```css
h1.root-23-07 {
  font-size: 100px;
  color: red;
}
```

https://codesandbox.io/s/reverent-hypatia-hyqkp

**Comment by amerllica** [comment]
Dear @afc163, Thanks for your effort to help me and I don't know why you close my issue, Actually, its `Ant-Design` issue.

I know about CSS priority numbers, the `[1, 10, 100, 1000]` and I know when you add an `h1` to the head of class name the priority will be equal to the `Ant-Design` class name selecting so my CSS will override the default CSS of `And-Design`.

But I'm using [`ReactJSS`](https://cssinjs.org/react-jss?v=v10.0.0) for generating CSS and in JSS solution I cannot add an `h1` or anything else.

It's a bug for `Ant-Design`. because there are some situations that Developer's CSS cannot override the default CSS of `Ant-Design`.
