### ISSUE TITLE
table的树形数据展示demo如果设置scroll属性，有一列数据过多，表格不对齐

### ISSUE THREAD

**Issue by ahauzq** [ant-design/ant-design#18971]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dark-tree-26vxb)

### Steps to reproduce
可以直接看效果吧

### What is expected?
不应该列对齐吗？

### What is actually happening?
列不对齐

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | react |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18893#issuecomment-533000528

https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241
