### ISSUE TITLE
照片墙初始化图片长度过大，其显示效果和上传同样图片的显示效果不同

### ISSUE THREAD

**Issue by theprimone** [ant-design/ant-design#18989]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pictureswall-130nv)

### Steps to reproduce
下载已初始化的图片重新上传

### What is expected?
初始化和上传都达到预期的铺满效果

### What is actually happening?
新上传图片显示效果和初始化的图片不同

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 77.0.3865.90 |

---
发现上传后的图片是经过裁剪得到的缩略图，又因为如果将这张图片旋转90°，初始化和上传后的显示效果是一致的。所以应该是初始化图片的未被正确裁剪导致的问题。

**Comment by zombieJ** [comment]
嗯，这里是可以优化一下。

**Comment by afc163** [comment]
@theprimone 楼主是资深用户了，可以尝试直接给 PR~

**Comment by theprimone** [comment]
@afc163 我刚好发现了原因，如果上传成功不赋值 url 和 thumbUrl， Upload 组件会自动截取缩略图。当有了 url 之后，Upload 就不会截取了。下次尝试直接 PR 吧 _(:3J∠)_
