### ISSUE TITLE
Pagination simple input 0

### ISSUE THREAD

**Issue by drmflying** [ant-design/ant-design#18985]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
<img width="764" alt="WX20190925-101054@2x" src="https://user-images.githubusercontent.com/3291182/65563749-33887e00-df7d-11e9-85f8-c05016a23b3e.png">

### Reproduction link
[https://ant.design/components/pagination-cn/](https://ant.design/components/pagination-cn/)

### Steps to reproduce
input 0 and press Enter

### What is expected?
return 1

### What is actually happening?
no thing

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by shaodahong** [comment]
except 0, maybe -1 or 10000, should control with self

**Comment by drmflying** [comment]
@shaodahong How do I control it?
