### ISSUE TITLE
Form as a dependency to useEffect causes infinite loop

### ISSUE THREAD

**Issue by ayayalar** [ant-design/ant-design#18983]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/small-star-wixy1)

### Steps to reproduce
the dependency (form) in useEffect is commented. Just need to uncomment. **Warning, the browser may become unresponsive due to infinite scrolling in the console.**

### What is expected?
Infinite scrolling should not occur.

### What is actually happening?
Infinite scrolling and possibly the browser may become unresponsive due to infinite scrolling in the console.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16 |
| System | Windows 10 |
| Browser | Chrome Or Edge Latest Version as of 9-24-19 |

**Comment by zombieJ** [comment]
`form` prop is [generate](https://github.com/react-component/form/blob/183d2b40e025cac1d61cf42fe3e18af7227f7248/src/createForm.js#L6) by each render to avoid `FormStore` not sync when reset. You can not put `form` as `useEffect` condition. 

PS: Why put `validateFields` in `useEffect`?

**Comment by ayayalar** [comment]
`validateFields` is just an example to repro this issue. I could pass `form` to useEffect for various reasons. E.g. fetch fields values, etc. If we cannot pass the form as a dependency, does that mean, antd doesn't fully support functional components?

**Comment by ayayalar** [comment]
Why did you close this issue?

**Comment by zombieJ** [comment]
> form prop is generate by each render to avoid FormStore not sync when reset. You can not put form as useEffect condition.

**Comment by ayayalar** [comment]
I understood what you said. My question is how do I use form in useEffect? if I cannot pass it as a dependency? Should we conclude antd forms do not support functional components?

**Comment by zombieJ** [comment]
* Form support function component. `Form.create` work as expect with both FC or CC.
* `form` prop is dynamic generated object which should not trade as diff condition.

And I still not get why use `form` within the condition of `useEffect`. Could you help to provide more info about 'fetch fields values' or some real usage example?

**Comment by ayayalar** [comment]
Before I give you a real-world scenario, I don't understand how can you assume that the `form` prop would never be used in `useEffect`. That troubles me. Every business scenario is different.

Based on the documentation from [list-of-dependencies](https://reactjs.org/docs/hooks-faq.html#is-it-safe-to-omit-functions-from-the-list-of-dependencies) in order to use `form` in `useEffect` you **have to** pass it as a dependency.

Here is a real-world scenario.
What we do in our application is to display a prompt for the user if they are navigating away and have unsaved changes in the form. The logic is in `useEffect` cleanup. We use `form.isFieldTouched` method along with some other business logic to display a prompt before the component is unmounted.

**Comment by ayayalar** [comment]
Please re-open this ticket. This is a bug with the framework and it should be tracked.

**Comment by zombieJ** [comment]
Just put the function in condition instead of put full form object. What you depend on is function not form object: https://codesandbox.io/s/vibrant-haibt-v2mb4

**Comment by ayayalar** [comment]
I will try this first thing tomorrow morning and update the ticket. I thought of doing this but I wasn’t sure if it would still get updates...

**Comment by ayayalar** [comment]
Unfortunately, this approach doesn't work. Using `getFieldsValue` doesn't return the updated values. `isFieldTouched` doesn't detect if the field has touched.

**Comment by ayayalar** [comment]
Any updates?

**Comment by zombieJ** [comment]
@ayayalar , could you update the reproduce so I can check on this?

**Comment by ayayalar** [comment]
Updated example
 https://codesandbox.io/s/vibrant-haibt-v2mb4

**Comment by zombieJ** [comment]
`isFieldTouched` only return `true` when field is touched. When you call in `useEffect` by `[isFieldTouched]`, it always trigger when the component init. That's why it return `undefined`.

**Comment by ayayalar** [comment]
In your previous comment, you provided this example as a work-around. You did not mention it would only work for certain functions of the form. Please open this issue. This is a bug in ant design. Clearly functional components are not fully supported and it should be fixed.

**Comment by ayayalar** [comment]
Could you open this ticket please?

**Comment by zombieJ** [comment]
Hi @ayayalar,
`isFieldTouched` is worked as expect since you use `[isFieldTouched]` as the `useEffect` condition. My comment above describe your code logic only and put `isFieldTouched` as condition works correctly.

**Comment by csandanov** [comment]
I've stumbled upon a similar issue, in my case what I want to achieve is to set a default value in a form's `<Select>` via `form.setFieldsValues`. I can't use `initialValues` because the `<Select>` populated dynamically after the form render. And I can't preload options before form render because I want to display loading animation of the `Select`. 

Currently, I just don't add `form` in the deps array and it works but I guess that's a bad practice. I could move it to the function but this won't solve anything because I normally should put the function in the deps as well.

**Comment by ayayalar** [comment]
Not being able to pass the form to the dependency array is definitely a problem. As you can see from my previous conversation, they don’t want to recognize it as a problem.

**Comment by Artoria-0x04** [comment]
Passing by for `setFieldsValue()` called in `useEffect()` producing `You cannot set a form field before rendering a field associated with the value.` error. I presume when a field is rendered and ready `isFieldTouched` will also be `true` ?

**Comment by Nicole1991** [comment]
> Just put the function in condition instead of put full form object. What you depend on is function not form object: https://codesandbox.io/s/vibrant-haibt-v2mb4

Hi, When I use ant-design 4.0.3, is there have any way to disable submit button when the fields validate failed as you example shows?For antd 4, I can't rerender the form when the fields validate failed.

Thanks.

**Comment by singagain** [comment]
我也遇到了类似的问题，我的表单是放在Modal中的，我想在props更新时更新我的表单数据，但是在useEffect中使用form就会出现‘ Warning: Instance created by `useForm` is not connected to any Form element. Forget to pass `form` prop?’，如果不在props中更新我的表单，那么Modal除了第一次打开，之后每次打开都是上一次的props，且destroyOnClose不能销毁有initialValues的表单，请问应该怎么做？

**Comment by singagain** [comment]
我有个类似的问题，我的<Form>是写在<Modal>里的，做表格回填，每次拿到的都是上一次的props，在useEffect中使用form会报Instance created by `useForm` is not connected to any Form element. Forget to pass `form` prop?，destroyOnClose无法销毁有initialValues的form，请问这种情况应该怎么做

**Comment by wbobeirne** [comment]
For those who want to use this to call functions on `form`, the best way to get around this is to use `useRef`:

```ts
export const ModalWithForm = ({ isVisible }) => {
  const [form] = Form.useForm();
  const formRef = useRef(form);

  // Update the form ref
  useEffect(() => {
    formRef.current = form;
  }, [form]);

  // Reset form every time the modal opens
  useEffect(() => {
    if (isVisible) {
      formRef.current.resetFields();
    }
  }, [isVisible]);
}
```

**Comment by csandanov** [comment]
@wbobeirne this solution work as long as you use only read operations, when you update the form (e.g. `form.setFieldsValue` this will cause an infinite loop

**Comment by pzyryanov1995** [comment]
In v4.20.0 added new `useWatch` hook & its work as expected:

```

  const enabledField = Form.useWatch('enabled', form)
  const viewer = viewerModel.useViewer()
  
  
  useEffect(() => {
     ...some logic
  }, [enabledField])
```

**Comment by dvlptuankiendo** [comment]
> In v4.20.0 added new `useWatch` hook & its work as expected:
> 
> ```
> 
>   const [form] = Form.useForm();
>   const enabledField = Form.useWatch('enabled', form)
>   
>   useEffect(() => {
>      ...some logic
>   }, [enabledField])
> ```

helped a lot, thanks!
