### ISSUE TITLE
AutoComplete Options are also not supporting value as integer.

### ISSUE THREAD

**Issue by storesbuzz** [ant-design/ant-design#18982]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/2857](https://github.com/ant-design/ant-design/issues/2857)

### Steps to reproduce
add integer value to AutoComplete Options

### What is expected?
as it's a value field, it should support integer values

### What is actually happening?
getting error as - 

Uncaught Error: Invalid valueof type numbersupplied to Option, expected stringwhen tags/comboboxis true.

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | "react": "^16.8.6", |
| System | any |
| Browser | any |

---
AutoComplete Options are not supporting value as an integer. getting error -

Uncaught Error: Invalid valueof type numbersupplied to Option, expected stringwhen tags/comboboxis true.

Kindly support here, values ​​are most commonly used as integers only.

**Comment by afc163** [comment]
AutoComplete is one kind of Input, which don't accept non-strings as it's value.

**Comment by storesbuzz** [comment]
Why there are such restrictions? When it's used in forms depending on use it can have both types of inputs and most often of type integer.

It takes an extra line of code inside form.validateFields to change the type of field values as required.
