### ISSUE TITLE
循环依赖警告

### ISSUE THREAD

**Issue by warmWarmHeart** [ant-design/ant-design#18999]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/warmWarmHeart/worm-ui](https://github.com/warmWarmHeart/worm-ui)

### Steps to reproduce
(!) Circular dependency: node_modules/antd/es/icon/index.js -> node_modules/antd/es/icon/IconFont.js -> node_modules/antd/es/icon/index.js
(!) Circular dependency: node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/config-provider/renderEmpty.js -> node_modules/antd/es/config-provider/index.js
(!) Circular dependency: node_modules/antd/es/icon/index.js -> node_modules/antd/es/icon/IconFont.js -> node_modules/antd/es/icon/index.js

### What is expected?
没有循环依赖

### What is actually happening?
项目启动的时候会报循环依赖警告

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | macOS 10.13.5 (17F77) |
| Browser | Google Chrome 77.0.3865.90 |

**Comment by warmWarmHeart** [comment]
https://github.com/warmWarmHeart/worm-ui @ant-design-bot

**Comment by yoyo837** [comment]
提供在线的复现demo

**Comment by warmWarmHeart** [comment]
@yoyo837 codesandbox无法复现命令行警告， 请问该怎么办？

**Comment by yoyo837** [comment]
你自己的eslint不要检查node_modules下的内容

**Comment by 849203846** [comment]
您好，我在使用时也遇到了同样的问题，请问您那边有解决方案了吗
