### ISSUE TITLE
Select在对选中内容的长度处理

### ISSUE THREAD

**Issue by lLeahDizon** [ant-design/ant-design#18995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在选中内容长度超出选择框宽度的时候，如果给Select选择器设置了百分比宽度，那么选择框就会被撑大，影响界面布局效果

### What does the proposed API look like?
期望能够对长度超出选择框宽度的内容做文本缩略处理，类似Select.Option的title

**Comment by lLeahDizon** [comment]
大概效果就是这样，https://codesandbox.io/embed/antd-reproduction-template-d59pb

**Comment by afc163** [comment]
> 那么选择框就会被撑大，影响界面布局效果

没看出有啥问题。

**Comment by lLeahDizon** [comment]
> > 那么选择框就会被撑大，影响界面布局效果
> 
> 没看出有啥问题。

>
>如果有多个Col的话，选择框的长短不一就会变得不是很理想，https://codesandbox.io/embed/antd-reproduction-template-d59pb

**Comment by afc163** [comment]
你可以说的更详细一点，也可以配合一些截图，你的例子点进去看目前没法看出有啥问题。

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/507615/65578430-5bd9a200-dfa8-11e9-867e-78537507b828.png">

**Comment by lLeahDizon** [comment]
实际上，我在项目中，在做这个处理的时候，默认状态下展示如下，
![image](https://user-images.githubusercontent.com/16300255/65578522-80ce1500-dfa8-11e9-9f05-a28928c46588.png)
![image](https://user-images.githubusercontent.com/16300255/65578601-a824e200-dfa8-11e9-99c6-3d570676681d.png)

在我选取了一项数据之后，导致我的label被覆盖了
![image](https://user-images.githubusercontent.com/16300255/65578728-f6d27c00-dfa8-11e9-9559-d8cc666d202c.png)

代码是这样的
![image](https://user-images.githubusercontent.com/16300255/65578802-1cf81c00-dfa9-11e9-880d-58289594ef7d.png)
组件封装的相关代码
![image](https://user-images.githubusercontent.com/16300255/65578862-326d4600-dfa9-11e9-8b8c-db4b30bbf2aa.png)

**Comment by yoyo837** [comment]
自己加样式可以解决，分享一下我自己的
![image](https://user-images.githubusercontent.com/6134547/65579170-cf2fe380-dfa9-11e9-9eb5-189d3e519afb.png)

**Comment by lLeahDizon** [comment]
@yoyo837 我给Select设置的百分比宽度，处理样式没成功，用固定值虽然可以解决问题，但是不好适配不同界面

**Comment by yoyo837** [comment]
@lLeahDizon 用`flex`

**Comment by lLeahDizon** [comment]
好吧，那只能这么弄了
