### ISSUE TITLE
希望 TreeSelect 提供 API，支持设置鼠标 hover 输入框时显示的内容

### ISSUE THREAD

**Issue by yangchch6** [ant-design/ant-design#18992]
- [ √] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- 在选择值后，鼠标 hover 输入框，显示的 title 可以自定义。目前 title 和 传入的JSON 数据中的 title 字段是一致的，且不支持修改。

![image](https://user-images.githubusercontent.com/33412781/65565671-2e2e3200-df83-11e9-96ef-6360fdb17ba8.png)

- 需要自定义 title 的场景很多，希望可以在组件层面支持该属性

### What does the proposed API look like?
- 希望可以新增 API （如：tipsField），支持设置 title 对应的字段，假如我传入的 treeData 如下所示：
```
const treeData = [
  {
    title: 'Node1',
    value: '0-0',
    key: '0-0',
    code: 'a1',
    children: [
      {
        title: 'Child Node1',
        value: '0-0-1',
        key: '0-0-1',
        code: 'a2'
      },
      {
        title: 'Child Node2',
        value: '0-0-2',
        key: '0-0-2',
        code: 'a3'
      },
    ],
  },
  {
    title: 'Node2',
    value: '0-1',
    key: '0-1',
    code: 'a4'
  },
];
``` 

那么当我设置 tipsField="code" 的时候，应该把鼠标 hover 显示的内容，显示为 code 字段对应的值。

**Comment by yangchch6** [comment]
请问组件层面是否可以支持呢？

**Comment by afc163** [comment]
```
<TreeNode value="parent 1" title={<span title="xxx">parent 1</span>} key="0-1">
```

你可以试试。

**Comment by yangchch6** [comment]
> ```js-jsx
> <TreeNode value="parent 1" title={<span title="xxx">parent 1</span>} key="0-1">
> ```
> 
> 你可以试试。

嗯嗯，可以了，非常感谢。
