### ISSUE TITLE
模态框(Modal)组件的问题

### ISSUE THREAD

**Issue by ReadingSteiner** [ant-design/ant-design#190]
使用了模态框组件遇到两个问题

1. 模态框的top值是强行写的**内联样式**，不可以改变，很不方便，希望可以修改或者**提供配置项**。
2. 模态框出现时，背景（比如是body）如果有滚动条，发现是**可以滚动的**，感觉非常**不合理**，希望可以得到修改，或者**提供一个配置项**来控制背景是否可滚动。

万分感谢~

**Comment by ReadingSteiner** [comment]
顺带捎一个Table组件的文档的问题，就是渲染每一栏的`render函数`的参数，文档中没有给出具体说明。我是一个一个试出来的，分别是(该栏数据,所有数据,数据index)

**Comment by yiminghe** [comment]
dialog 设置

```
align
```

https://github.com/react-component/dialog/blob/b3487330a22c7445aadbad243ffe01dc3651a125/src/DialogWrap.jsx#L112


2.  https://github.com/react-component/dialog/issues/9

**Comment by ReadingSteiner** [comment]
感谢更新~
