### ISSUE TITLE
documentation needs to be update

### ISSUE THREAD

**Issue by ermanzohre** [ant-design/ant-design#19004]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-with-create-react-app](https://ant.design/docs/react/use-with-create-react-app)

### Steps to reproduce
you can try and find it here: https://ant.design/docs/react/use-with-create-react-app

### What is expected?
antdesign documantation should be updated for react

### What is actually happening?
doesn't work

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | react version 16.9.0 |
| System | microsoft |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="519" alt="image" src="https://user-images.githubusercontent.com/507615/65653488-048b0e80-e048-11e9-819f-9cffee0fe5e1.png">

Feel free to send us PR.
