### ISSUE TITLE
InputNumber组件在validateTrigger: 'onBlur'情况下的问题

### ISSUE THREAD

**Issue by Yu-Rain** [ant-design/ant-design#19000]
- [ * ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-burnell-t995q?fontsize=14)

## 说明:  
   * <金额onBlur> 输入框, `name`为 `jiner_onBlur`,  设置`validateTrigger: 'onBlur'`
   * <金额onChange> 输入框 `name`为 `jiner_onChage`, 设置 `validateTrigger: 'onChange'`

## 测试步骤:
1. 在<金额onBlur> 输入框中 输入 33333, 页面会显示 33,333 (特别注意不要失去焦点)

2. 在不失去焦点的情况下查看控制台, 会发现 `changedValues` 和 `fields` 中的 `jine_onBlur` 的值都是Number类型的 33333

3. 点击其他地方, 让<金额onBlur> 输入框失去焦点, 此时查看控制台, 会发现`changedValues` 中的`jine_onBlur`的值是字符串"33,333.00", 而`fields`中的`jine_onBlur`值是字符串"33333.00". 
(重点是在`validateTrigger`为 `'onBlur'`情况下`onValuesChange`方法无法获取`parser`后的值)

4. <金额onChange> 输入框的测试步骤与前3步相同. 但会发现 `changedValues` 和 `fields` 中的 `jine_onChange` 的值都是Number类型的 33333, **不会变为字符串类型**

5. 有趣的是 一旦在 <金额onChange> 输入框 中输入一个数字触发了onChange后,   **会发现`changedValues` 中的`jine_onBlur`的值又变成了字符串"33333.00".**

### What is expected?
我期望无论 validateTrigger 设置的是什么, 在onValuesChange方法中我都能获取到 parser后的值, 而不是自定义格式化的值

### What is actually happening?
在validateTrigger设置为onBlur 时, 在 onValuesChange方法中只能获取到自定义格式化的值, 而不是 parser后的值.

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.6 |
| System | Mac 版本10.13.6 (17G65) |
| Browser | Chrome  版本 76.0.3809.132（正式版本） （64 位） |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11379#issuecomment-442483415

**Comment by Yu-Rain** [comment]
你好, @afc163  
在发Issue之前我看过 #11379 (comment), 但是当时我认为这和我的问题不一样.
这次你再次发给我, 我又仔细认真的看了@zombieJ 的回复, 那么就是说现在有关validateTrigger所引发的问题并没有其他的解决方案, 只能等待antd的以后的优化了, 是吗?
