### ISSUE TITLE
Documentation site has broken functionality in Internet Explorer 11 due to a syntax error

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#19005]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce](https://ant.design/docs/react/introduce)

### Steps to reproduce
1. Load the documentation site in Internet Explorer 11
1. Open the console.

### What is expected?
Site functions the same as it does on evergreen browsers.

### What is actually happening?
All interactive components do not function. For example, expanding sample code, opening Select components, and toggling Switch components.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9 |
| System | Windows 10 |
| Browser | Internet Explorer 11 |

**Comment by shaodahong** [comment]
like function default parameter syntax broke it

**Comment by yoyo837** [comment]
@shaodahong No, it looks like broken by allow function.

**Comment by yoyo837** [comment]
https://github.com/formatjs/react-intl/issues/1486

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/65782743-e8d75380-e180-11e9-96ab-7341daa6adea.png)
