### ISSUE TITLE
引入与Icon组件相关的任何组件都会报错，但引入与Icon无关的组件则没有报错

### ISSUE THREAD

**Issue by warmWarmHeart** [ant-design/ant-design#19002]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/warmWarmHeart/worm-ui](https://github.com/warmWarmHeart/worm-ui)

### Steps to reproduce
npm run dev 后显示如下错误：
Uncaught TypeError: Unknown theme type: undefined, name: undefined
    at withSuffix (utils.js:97)
    at Icon.js:80
    at Array.forEach (<anonymous>)
    at Function.add (Icon.js:79)
    at index.js:38
    at index.js:5

### What is expected?
正常显示Icon

### What is actually happening?
项目启动的时候会报错

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | macOS 10.13.5 (17F77) |
| Browser | Google Chrome 77.0.3865.90 |

**Comment by yoyo837** [comment]
提供在线的复现demo

**Comment by warmWarmHeart** [comment]
@yoyo837 我这里的打包配置和codesandbox不相同，只提供github仓库地址不可以吗？，另外请教下大佬 可否从上面显示的报错信息推断出 可能是哪儿出的问题（
Uncaught TypeError: Unknown theme type: undefined, name: undefined
at withSuffix (utils.js:97)
at Icon.js:80
at Array.forEach ()
at Function.add (Icon.js:79)
at index.js:38
at index.js:5
）

**Comment by yoyo837** [comment]
每个人出问题都希望社区全包定位、复现、解决是很不高效、不实际的。社区每个人的精力是有限的...

**Comment by usernameisMan** [comment]
> @yoyo837 我这里的打包配置和codesandbox不相同，只提供github仓库地址不可以吗？，另外请教下大佬 可否从上面显示的报错信息推断出 可能是哪儿出的问题（
> Uncaught TypeError: Unknown theme type: undefined, name: undefined
> at withSuffix (utils.js:97)
> at Icon.js:80
> at Array.forEach ()
> at Function.add (Icon.js:79)
> at index.js:38
> at index.js:5
> ）
是啥问题？

**Comment by usernameisMan** [comment]
> @yoyo837 我这里的打包配置和codesandbox不相同，只提供github仓库地址不可以吗？，另外请教下大佬 可否从上面显示的报错信息推断出 可能是哪儿出的问题（
> Uncaught TypeError: Unknown theme type: undefined, name: undefined
> at withSuffix (utils.js:97)
> at Icon.js:80
> at Array.forEach ()
> at Function.add (Icon.js:79)
> at index.js:38
> at index.js:5
> ）

是啥问题？

**Comment by suzyvivi** [comment]
> @yoyo837 我这里的打包配置和codesandbox不相同，只提供github仓库地址不可以吗？，另外请教下大佬 可否从上面显示的报错信息推断出 可能是哪儿出的问题（
> Uncaught TypeError: Unknown theme type: undefined, name: undefined
> at withSuffix (utils.js:97)
> at Icon.js:80
> at Array.forEach ()
> at Function.add (Icon.js:79)
> at index.js:38
> at index.js:5
> ）

请问后面是如何解决的呢？

**Comment by yoyo837** [comment]
@warmWarmHeart 还是 https://github.com/warmWarmHeart/worm-ui 这个链接吗？稍后我看一下。

**Comment by franklinfee** [comment]
@warmWarmHeart 请问解决了吗

**Comment by yoyo837** [comment]
这个问题还在？

**Comment by franklinfee** [comment]
> 这个问题还在？

@yoyo837 嗯，请问是修复了嘛

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/99475106-cc9c0480-2988-11eb-833b-b7fdafb6986a.png)

`ReactIcon.add(...Object.keys(allIcons).map(key => (allIcons as any)[key]));` 多了这俩属性。
确实，但我自己项目没遇到。 @afc163 @zombieJ 这个3.x的还弄不？

**Comment by yoyo837** [comment]
我在想是不是rollup的原因呢？你搞个webpack的试试？

`__moduleExports` 和 `default`

**Comment by yoyo837** [comment]
要么就`@ant-design/icons@2.x`兼容下`rollup`

**Comment by yoyo837** [comment]
`3.x`不维护了，改不了。

**Comment by franklinfee** [comment]
@

> ![image](https://user-images.githubusercontent.com/6134547/99475106-cc9c0480-2988-11eb-833b-b7fdafb6986a.png)
> 
> `ReactIcon.add(...Object.keys(allIcons).map(key => (allIcons as any)[key]));` 多了这俩属性。
> 确实，但我自己项目没遇到。 @afc163 @zombieJ 这个3.x的还弄不？

@yoyo837 是的，我认为是因为 @ant-design/icons 不支持 ES Module 导出导致被 rollup-plugin-commonjs 处理了

**Comment by yoyo837** [comment]
升级到4.x吧

**Comment by Mater1996** [comment]
![image](https://user-images.githubusercontent.com/26322213/101121159-67a00a00-362a-11eb-8914-11edac7cf26a.png)
主要是import * as allIcons 导致的，
由于 '@ant-design/icons/lib/dist 是common js 所以会导出 一个default 导致出错 
改为 
![image](https://user-images.githubusercontent.com/26322213/101121213-8b635000-362a-11eb-99ef-b342c0e665fa.png)
就会修复这个bug

**Comment by abear-eatsfish** [comment]
报错之后，在另外个ISSUES找到个解决方案，就是：
`import { Space, Button, Carousel, Form, Icon, Input } from 'ant-design-vue/lib`

但是使用Vite打包之后很大，不知为何，没有深入，所以还是原着
`import { Space, Button, Carousel, Form, Icon, Input } from 'ant-design-vue`
的方式找方案，最后直接把“node_modules\@ant-design\icons-vue\es\components\Icon.js”下，第25行修改之后，暂时无问题；
原：
`
    // icons.forEach(function (icon) {
    //   Icon.definitions.set(withSuffix(icon.name, icon.theme), icon);
    // });
`

修改為：
```
Object.keys( icons[0])
.map(o=>{return icons[0][o]})
.forEach(function (icon) {
    Icon.definitions.set(withSuffix(icon.name, icon.theme), icon);
  });
```

![image](https://user-images.githubusercontent.com/50629909/122265247-1642d280-cf0b-11eb-93e5-cec2e60916cc.png)



但是这时候就不能使用 
`import { Space, Button, Carousel, Form, Icon, Input } from 'ant-design-vue/lib` 會報錯

**Comment by BeADre** [comment]
或者在初始化ant-design之前直接重写Object.keys方法
```javascript
function mockKeys() {
  const keys = Object.keys

  Object.keys = obj => {
    // 这里如果其他对象也恰好有该属性的话会出现问题
    if (obj.default && obj.default.AntDesignOutline) return keys(obj.default)

    return keys(obj)
  }
}

mockKeys()
```

**Comment by anilpixel** [comment]
该问题的原因是 **vite** 使用的 **esbuild** 导入 **commonjs** 模块时会添加 **default** 属性，具体原因可以参见这个 [issue](https://github.com/evanw/esbuild/issues/668)。**esbuild** 的作者认为这个特性符合标准。
综上所述，只要我们在项目中使用的 **@ant-design/icons** 是 **esmodule** 即可，在 **vite.config.js** 添加如下配置，就能修复这个问题：

```javascript
// vite.config.js
import { defineConfig } from 'vite'

export default defineConfig({
    resolve: {
      alias: {
        '@ant-design/icons/lib/dist': '@ant-design/icons/lib/index.es.js'
      },
    },
})
```
