### ISSUE TITLE
Transfer组件是否可以指定数据源主键

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#1900]
## 场景
官网demo中数据源包含字段key，该字段会默认为组件Transfer item的主键
![image](https://cloud.githubusercontent.com/assets/17123400/15641241/15ed95c8-2672-11e6-9e14-a39971782ac8.png)
当数据源中不包含key字段，则Transfer无法被渲染出来
demo：http://codepen.io/hyaaon/pen/dXyjoG

Transfer组件是否可以如Table组件(rowKey)，让用户自定义数据源主键？

## 版本
antd@1.2.1

**Comment by RaoHai** [comment]
像这样？ https://github.com/ant-design/ant-design/pull/1905

**Comment by ddcat1115** [comment]
是的~
