### ISSUE TITLE
Table Title render function does not have enough information about the current column that is sorted

### ISSUE THREAD

**Issue by swillis12** [ant-design/ant-design#19007]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/elastic-banach-9ztse)

### Steps to reproduce
Open the codesandbox console and click sort on name, observe the log message.

"ascend/descend, but no column name 
Object {filters: Object, sortOrder: null}"

### What is expected?
The object should contain the "dataIndex" of the currently sorted column/columns

### What is actually happening?
DataIndex is not available to the title render function so the ascending/descending information cannot be used to render a header for a specific column.

### Other
This has already been mentioned here a couple of times: https://github.com/ant-design/ant-design/issues/11246#issuecomment-430943407

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | Mac OS X Mojave |
| Browser | Chrome |

**Comment by afc163** [comment]
You already know which is the column when setting title.

```js
const renderTitle = (dataIndex, info) => {
  console.log(dataIndex, info);
  return "Title";
};

...

  {
    title: renderTitle('name'),
    dataIndex: "name",
    key: "name",
    render: text => <a>{text}</a>,
    sorter: (a, b) => (a.name > b.name ? (1 ? b.name > a.name : -1) : 0)
  },
  {
    title: renderTitle('age'),
    dataIndex: "age",
    key: "age"
  },
```

**Comment by swillis12** [comment]
@afc163 There is know way to tell which column is sorted from the `info` argument that is passed in in your example. All we get is "ascend/descend" regardless of which column is currently sorted.

E.g. Sort the age column "asecnding"  and the the `info` object passed to the `renderTitle` function for the NAME column will only contain `{ sortOrder: "ascend" }` even though the name column is not even sorted.
