### ISSUE TITLE
Tabs组件的新增左右滑动功能

### ISSUE THREAD

**Issue by cqiang1993** [ant-design/ant-design#19015]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在手机浏览器上最展示的时候，出现tabs比较多的情况下，屏幕占比会被左右翻页的按键占用，缩小了可操作的空间，而且移动端希望的是能够尽量简化操作，滑动的用户操作体验会比翻页的好，所以希望能够增加相应的功能。

### What does the proposed API look like?
添加一个是否滑动的参数，并且支持隐藏左右翻页按键

**Comment by afc163** [comment]
Tabs 提供了自定义 renderTabBar 的能力，rc-tabs 也里有可滑动的 tab node：https://github.com/react-component/tabs#libswipeabletabcontent 楼主可以尝试自习定制一下：https://github.com/ant-design/ant-design/blob/46d0ff3e00bebe1b91ea640bbcc3035be1e759db/components/tabs/TabBar.tsx#L65

目前在移动端的支持不会投入太多精力，楼主有精力的话，也欢迎来 PR。

**Comment by afc163** [comment]
trace in #24284
