### ISSUE TITLE
Collapse header 里面如何支持标签

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#1901]
Collapse header 里面如何支持标签

`<Collapse defaultActiveKey={['1']} onChange={callback}>
    <Panel header="This is panel header 1<span>111</span>" key="1">
      <p>{text}</p>
    </Panel>
    <Panel header="This is panel header 2" key="2">
      <p>{text}</p>
    </Panel>
    <Panel header="This is panel header 3" key="3">
      <p>{text}</p>
    </Panel>
  </Collapse>`

**Comment by afc163** [comment]
`header={This is panel header 1<span>111</span>}`

建议先系统学习 React 。http://facebook.github.io/react/
