### ISSUE TITLE
ssr下avatar内部文字初始渲染变形

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#19017]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.lsz8617.com/](https://www.lsz8617.com/)

### Steps to reproduce
https://www.lsz8617.com/
刷新观察右上角头像

### What is expected?
文字scale能否从0开始，挂载后或者用动效变成适应尺寸

### What is actually happening?
初始渲染右侧偏离

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by Fled8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/65666959-5dbb6800-e071-11e9-95ad-d8b29e50d748.png)
![image](https://user-images.githubusercontent.com/35049517/65666981-62801c00-e071-11e9-8ab2-99db76e26469.png)

**Comment by zombieJ** [comment]
ssr 时没有真实 dom，尺寸是默认大小。感觉可以调整成初始化时不显示文字，didMount 后再展示。
