### ISSUE TITLE
Tabs组件的在手机端默认选中某个tabs的时候，没有出现在tabs的中间

### ISSUE THREAD

**Issue by cqiang1993** [ant-design/ant-design#19016]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在移动端显示的时候，默认选中的tab不会移动到屏幕的中间

### What does the proposed API look like?
添加一个是否参数，进行判断将默认选中的tabs放在屏幕的中间

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/19015#issuecomment-535374504
