### ISSUE TITLE
table设置了scroll.y之后出现了错位

### ISSUE THREAD

**Issue by Jkanon** [ant-design/ant-design#19018]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/Jkanon/pen/oNvOvKP](https://codepen.io/Jkanon/pen/oNvOvKP)

### Steps to reproduce
看demo

### What is expected?
能够正常对齐

### What is actually happening?
表头和内容错位

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.8.6 |
| System | win7 |
| Browser | chrome 77 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18893#issuecomment-533000528

https://github.com/ant-design/ant-design/issues/18971

https://github.com/ant-design/ant-design/issues/18436

https://github.com/ant-design/ant-design/issues/18239

https://github.com/ant-design/ant-design/issues/5825

**Comment by Jkanon** [comment]
但是我指定width或者保留一列不设宽度，并没有用，现在又解决方案吗

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13825#issuecomment-449889241

**Comment by Jkanon** [comment]
@afc163 好的谢谢，在demo中直接嵌套添加style是可以的，我一开始有在我系统中添加全局样式，不知怎的没有效果，那我还是再嵌套一层好了。

**Comment by Jkanon** [comment]
@afc163 我更新了demo，给其中的两个长字段都添加上了<div style={{ wordWrap: 'break-word', wordBreak: 'break-word' }}>，但是还是有些许错位
![JPB)~%D{TQUZBGD TIJNUN](https://user-images.githubusercontent.com/21964895/65701976-d1329900-e0b4-11e9-9fdb-e8f6a64196bc.png)

**Comment by afc163** [comment]
```
.wrapper .ant-table .ant-table-scroll .ant-table-header {
  padding-right: 3px;
}
```

Remove this.

**Comment by Jkanon** [comment]
@afc163 我已经去除了这个样式了，但是还是不行的。可能在某些分辨率的窗口下是正常的，我昨天也是这样被骗了，但是你可以改变浏览器窗口看下，还是会错位的

**Comment by Jkanon** [comment]
好吧，可能是width总和超过了窗口大小就会出现这问题，添加了scroll.x就正常了。
目前表格使用起来有点变扭
1、用户的屏幕尺寸我们控制不了，强行width无法适配所有的电脑
2、感觉没有标准的解决方案，遇到问题得各种尝试
同时我就纳闷了，不设置scroll.y就没问题

**Comment by Jkanon** [comment]
我更新了demo，又出现了个问题，我本来想设置scroll.x为max-content已解决后顾之忧，但是配合上fixed:right的列的情况下，最后一个非fixed列被挡住了

**Comment by afc163** [comment]
目前的方案是这样的，需要适应的情况很多，4.0 会想办法从底层做一次技改。
