### ISSUE TITLE
WeekPicker showed there was a problem

### ISSUE THREAD

**Issue by SherryWu7** [ant-design/ant-design#19028]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
DatePicker-> WeekPicker  
![7A00A5C4-7907-45B0-80B1-FD218EA92A94](https://user-images.githubusercontent.com/26374147/65740585-dd057600-e11b-11e9-8d5b-783d8e80ed99.png)

### What is expected?
show correct

### What is actually happening?
showed there was a problem

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.8.6 |
| System | mac |
| Browser | Chrome 77.0.3865.90 |

**Comment by afc163** [comment]
They are the Week numbers, not a problem.
