### ISSUE TITLE
Overwrite Tooltip arrow css

### ISSUE THREAD

**Issue by agnesching19** [ant-design/ant-design#19026]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/anon/pen/JVvyGr](https://codepen.io/anon/pen/JVvyGr)

### Steps to reproduce
.ant-tooltip-placement-bottom .ant-tooltip-arrow, .ant-tooltip-placement-bottomLeft .ant-tooltip-arrow, .ant-tooltip-placement-bottomRight .ant-tooltip-arrow {
    border-bottom-color: green;
}

### What is expected?
I expected the colour of the Tooltip arrow would be overwrite with green (rather than the original black colour).

### What is actually happening?
I added the code to overwrite colour of the Tooltip arrow, which used to work last month. From some point this month, the colour of the arrow was switched back to black.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.8.4 |
| System | Mac 10.14.6 |
| Browser | Version 77.0.3865.90 (Official Build) (64-bit) |

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/gOYyWEE
