### ISSUE TITLE
DatePicker增加选择时间功能，点击“此刻”，无效

### ISSUE THREAD

**Issue by JovenPan** [ant-design/ant-design#1902]
## 你期待的结果是：

点击“此刻”，填入当前时间

## 实际上的结果和抱怨：

点击后没有反应

## 可重现的在线演示

[官方demo就无效，日期时间选择](http://ant.design/#/components/date-picker)

## 本地环境信息

- antd 版本: 1.2.1

**Comment by afc163** [comment]
1.6.5 里修复了 https://github.com/ant-design/ant-design/issues/2399 。

导致这里依然有问题，还需要看看如何修改。
