### ISSUE TITLE
使用上传功能，限制文件类型，修改文件后缀beforeUpload事件返回的file.type还是文件原来的类型

### ISSUE THREAD

**Issue by Judyya** [ant-design/ant-design#19022]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://ai.hua-cloud.com.cn/discernCar](http://ai.hua-cloud.com.cn/discernCar)

### Steps to reproduce
选择一个.jpg格式的图片，修改后缀为.jfif，上传，console.log返回的是image/jpeg

### What is expected?
beforeUpload返回的file.type为文件当前类型

### What is actually happening?
beforeUpload返回的file.type为文件后缀修改前的类型

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 3 |
| System | win10 |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
这个文件类型是游览器读取文件读出来的，和后缀没有关系。
