### ISSUE TITLE
@table-header-bg isn't working on Table if a `size` is set.

### ISSUE THREAD

**Issue by gbreux** [ant-design/ant-design#19021]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
- Add the Table component with the size (small) set
- Change the variable `@table-header-bg` to `red`

### What is expected?
The header should be red

### What is actually happening?
```.ant-table-small > .ant-table-content > .ant-table-scroll > .ant-table-header > table > .ant-table-thead > tr > th```

will overide with a transparent background `.ant-table-thead > tr > th` that use the `@table-header-bg` 

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | React |
| System | All |
| Browser | All |

**Comment by yoyo837** [comment]
It's all by design or bug when size='small' ? @afc163

**Comment by zombieJ** [comment]
It's by design. Table small do not have header background.
