### ISSUE TITLE
在锁列的情况下使用 position: sticky 无法实现表头吸顶

### ISSUE THREAD

**Issue by Wiolem** [ant-design/ant-design#19020]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
通过 sticky 简单的实现表头吸顶

### What does the proposed API look like?
```
const StyledTable = styled(Table)`
  .ant-table-thead > tr > th {
    position: sticky;
    top: 0;
    z-index: 10;
  }
`
```
在锁列的情况下 Chrome 最新版下 sticky 无法生效，表头无法吸顶

但是不锁列的情况是可以吸顶的

demo 地址：https://codesandbox.io/s/nice-galileo-p5il2

**Comment by zombieJ** [comment]
固定列会做一个额外的 Table 用于锁定效果，如果想通过 css 做一些额外的特性，需要自行研究哈。

**Comment by hblz** [comment]
在锁列的情况下 Chrome 最新版下 sticky 无法生效，表头无法吸顶   
--------有找到办法了吗

**Comment by douhua-d** [comment]
有大佬有解决的办法了吗

**Comment by DreamLee1997** [comment]
> 有大佬有解决的办法了吗

你好，想问下你后来怎么解决的？

**Comment by DreamLee1997** [comment]
> 

想问下你后来怎么解决的？

**Comment by DreamLee1997** [comment]
> 在锁列的情况下 Chrome 最新版下 sticky 无法生效，表头无法吸顶 --------有找到办法了吗

想问下你后来怎么解决的？
