### ISSUE TITLE
autoFocusButton not working in Modal

### ISSUE THREAD

**Issue by chinhoe** [ant-design/ant-design#19033]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hnn8i)

### Steps to reproduce
1. Create a antd Modal with modal.confirm()
2. Hover on okButton

### What is expected?
okButton not focused by default so it will provide hover effect on hover.

### What is actually happening?
okButton is still focused by default.

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | any |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
Yes, according to documentation, it is a specified property for Modal.xxx.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-1q0vg
