### ISSUE TITLE
Table组件表头固定，如何结合react-custom-scrollbars给Table内容做自定义滚动条的效果? 

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design#19036]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决给table设置自定义滚动条的问题

### What does the proposed API look like?
能够给Table内容添加相应的容器  用来达到 添加自定义滚动条的目的

**Comment by afc163** [comment]
暂不支持，建议自行探索。

**Comment by wo-de-ping-er** [comment]
> 暂不支持也不建议自定义滚动条，建议自行探索。

请问大神   有什么好的建议不？
