### ISSUE TITLE
Form下Input.Password eye Icon 错位

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#19032]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-darkness-bnnd7)

### Steps to reproduce
link

### What is expected?
icon位置是正常的

### What is actually happening?
icon位置存在偏移

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.4 |
| System | win10 |
| Browser | 谷歌浏览器 |

**Comment by afc163** [comment]
```diff
  validateToNextPassword = (rule, value, callback) => {
    if (value === "123") {
      callback();
    }
+  callback();
  };
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5155
