### ISSUE TITLE
ConfigProvider 引用了moment，但是项目中没用到了，能不能moment单独配置呢？

### ISSUE THREAD

**Issue by gitHber** [ant-design/ant-design#19030]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ConfigProvider 引用了moment，但是项目中没用到了，能不能moment单独配置呢？打包会多出moment的打包，moment最好能单独配置

### What does the proposed API look like?
moment自己有国际化的方式，完全可以交还给moment自己处理

**Comment by zombieJ** [comment]
嗯，有计划剥离。
