### ISSUE TITLE
windows 环境下，upload 组件拖拽上传，上传不了 accept 参数对应文件格式的文件

### ISSUE THREAD

**Issue by lz-lee** [ant-design/ant-design#19038]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-fermi-c2lb5)

### Steps to reproduce
windows 电脑打开，拖拽上传 .csv 格式的文件，上传不成功。重现链接里 accept 设置成了 "text/csv"。

### What is expected?
windows 环境能拖拽上传 accept 参数对应文件格式的文件

### What is actually happening?
拖拽上传无效，但能点击上传。

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.8.3 |
| System | win10 64 bit |
| Browser | Chrome  77.0.3865.90 |

---
用户可能是windows环境，拖拽上传，导致上传文件不成功。

**Comment by afc163** [comment]
```diff
-   accept: "text/csv",
+  accept: ".csv",
```

Try this.

**Comment by afc163** [comment]
https://stackoverflow.com/questions/33147930/how-to-accept-csv-format-input-file-cross-browsers/33496186#33496186

**Comment by lz-lee** [comment]
> ```diff
> -  accept: "text/csv",
> +  accept: ".csv",
> ```
> 
> Try this.
已解决
windows下 csv 文件拖拽上传的type竟然是：`application/vnd.ms-excel`
![企业微信截图_15695795184513](https://user-images.githubusercontent.com/22316795/65763544-3f7b6800-e156-11e9-8c73-c01d42eeda14.png)
