### ISSUE TITLE
Uploader 上传组件能否将多文件合并传递?

### ISSUE THREAD

**Issue by astwyg** [ant-design/ant-design#1903]
请问, uploader的multiple为true时, 能否将多个上传文件合并成一个请求发送?

目前每个文件一个请求在后端整合比较复杂.

谢谢.

**Comment by ddcat1115** [comment]
你好，暂时没有支持计划，有这方面需求欢迎直接pr  : )

**Comment by encorehe** [comment]
您好 我这边也有这个类似的需求 我想问的是 能否得到多个选中的文件 把这个文件放到一个参数并传递过去？

**Comment by benjycui** [comment]
Use `beforeUpload` to stop upload automatically, and collect all the files.

Then, upload all the files at the same time.

**Comment by encorehe** [comment]
thanks .

**Comment by astwyg** [comment]
thanks @benjycui
