### ISSUE TITLE
ant design pro table title 国际化切换语言需要手动刷新

### ISSUE THREAD

**Issue by well-monkey** [ant-design/ant-design#19039]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://preview.pro.ant.design/dashboard/analysis 
1.以官网例子来讲，我严格的按照官网的进行了国际化 并在table 数组 columns 的title进行了国际化 。
当切换语言的时候 table 表头的语言并没有更新  需要手动的刷新一下
2.个人中心也有类似的问题。需要刷新才会更换语言

### What does the proposed API look like?
ant design table 国际化切换语言 table表头及时更新 不需要手动刷新页面

**Comment by afc163** [comment]
pro 的问题请去 pro 那里反馈。

**Comment by yysfwls** [comment]
请问解决了吗

**Comment by huangchongmm** [comment]
我这里也碰到了，主要是出现在加了class加了connect之后语言切换就需要重新刷新页面，删除就不需要，不知道应该如何解决，现在只能切换语言页面整个刷新
