### ISSUE TITLE
Pass any component inside editable Paragraph in Ant Design

### ISSUE THREAD

**Issue by deadcoder0904** [ant-design/ant-design#19048]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a use-case where I want to make a link content-editable as well as clickable. Currently, it looks like:

[![Ant Design Paragraph][1]][1]

This does solve the content-editable issue but is not clickable. And no other way to make it clickable.

I'm unable to do it since Ant Design only supports `string` as a `child`. I've tried different ways but can't make this work.

  [1]: https://i.stack.imgur.com/13vlW.png

### What does the proposed API look like?
The proposed API looks like:

```js
<Paragraph
        href={editableText}
        editable={{
          onChange: updatedLink => {
            if (editableText !== updatedLink) {
              changeEditableText(updatedLink)
              onLinkChange(id, updatedLink, changeLink)
            }
          },
        }}
      >
        <a href={editableText}>{editableText}</a>
</Paragraph>
```

**Comment by deadcoder0904** [comment]
I've attached the Codesandbox → https://codesandbox.io/s/antd-paragraph-not-work-mqgoy

It contains 2 things - a working case & a non-working case. I need the non-working case to be working :)

**Comment by deadcoder0904** [comment]
@shaodahong I did add a repro, can u re-open it?

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/antd-paragraph-not-work-y1ewd

**Comment by deadcoder0904** [comment]
@afc163 I already did, if u click on the edit button & then click outside it opens the URL which I don't want as I need to edit text without changing URLs

**Comment by RonLek** [comment]
@afc163 how did you work around this? I have a similar use-case where I need to be able to edit the link inside the Paragraph while also being able to click on it.

**Comment by NDresevic** [comment]
> [@afc163](https://github.com/afc163) how did you work around this? I have a similar use-case where I need to be able to edit the link inside the Paragraph while also being able to click on it.

I have a similar use case. What is the status of this issue? It doesn't seem to have any recent activity, but it is not resolved as far as I can see.
