### ISSUE TITLE
【feature】message.loading 的返回提供message 实例以及类似modal.update的方法

### ISSUE THREAD

**Issue by kanweiwei** [ant-design/ant-design#19043]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
页面在进行复杂响应时，需要在一个message.loading不同时段内显示不同的提示信息，因为目前该组件显示时有个延迟动画，频繁调用message.loading体验差。希望提供类似modal.update的方法，允许用户直接更新现有的message的内容。

### What does the proposed API look like?
```javascript
let l = message.loading('xxx');
l.instance.update('bbb'); // 更新
l(); // 关闭loading
```

**Comment by afc163** [comment]
Fixed by https://github.com/ant-design/ant-design/pull/18678
