### ISSUE TITLE
es6 modules do not work with the jest

### ISSUE THREAD

**Issue by DenysVuika** [ant-design/ant-design#19047]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
just a generic link as you form enforces that
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
1. generate app with create react app
2. use Layout component
3. run "yarn test"

### What is expected?
tests run

### What is actually happening?
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Layout from './layout';
                                                                                                    ^^^^^^

    SyntaxError: Unexpected identifier

    > 1 | import Layout from 'antd/es/layout';

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | macOS |
| Browser | all |

**Comment by shaodahong** [comment]
https://jestjs.io/docs/en/tutorial-react

**Comment by DenysVuika** [comment]
how that answers the question and closes the ticket?

**Comment by shaodahong** [comment]
your question is `Jest` issue, you can report in `Jest` repository
