### ISSUE TITLE
Tooltip configuration

### ISSUE THREAD

**Issue by dimitrov-adrian** [ant-design/ant-design#19051]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tooltips on mobile devices or touch devices where touch is used, displays the tooltip without triggering the action behind (for example if wrap a button), then it need another click/tap with displayed tooltip to trigger the action, and then the tooltip is still visible.

### What does the proposed API look like?
Possible configuration could be similar to notification, and to include option to complete disable tooltip trigger, like:

```javascript
tooltip.config({
  trigger: 'none'
})
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14424
