### ISSUE TITLE
Select and autocomplete issue with react-fastclick

### ISSUE THREAD

**Issue by dimitrov-adrian** [ant-design/ant-design#19050]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-03jix)

### Steps to reproduce
Click on select and try to pick some item

### What is expected?
Picking item

### What is actually happening?
Nothing happen

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.5 |
| React | react 16.10.0 |
| System | macOS |
| Browser | Chrome |

---
If remove fastclick, it goes as expected

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14424#issuecomment-455457137
