### ISSUE TITLE
table use 'sort' and 'title' with 'span' and 'setState' in onChange callback， always "ascend"

### ISSUE THREAD

**Issue by lchunxiu** [ant-design/ant-design#19058]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-wu-v2hct?fontsize=14)

### Steps to reproduce
点击name表头，sorter不会切换

### What is expected?
sorter在 ascend descend '' 之前切换

### What is actually happening?
sorter不会切换

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 3.23.4 |
| System | mac |
| Browser | chrome 76 |

**Comment by shaodahong** [comment]
https://ant.design/components/table-cn/#components-table-demo-ajax

**Comment by afc163** [comment]
Add column key or move column out of render.

**Comment by lchunxiu** [comment]
@afc163 it works,thank you!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19398
https://github.com/ant-design/ant-design/issues/19636

**Comment by xiaosu12138** [comment]
I have the same problem in v3.26.5
maybe it is better to change '(a && b && a.key && a.key === b.key)' to '(a && b getColumnKey(a)=== getColumnKey(b))'  on line 66 in 'ant-design/components/table/Table.tsx'.
because  key is not required
