### ISSUE TITLE
使用Typography.Text组件产生warning

### ISSUE THREAD

**Issue by pennchester** [ant-design/ant-design#19064]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-kgnlf?fontsize=14)

### Steps to reproduce
直接打开看console

### What is expected?
无warning

### What is actually happening?
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.8.6 |
| System | win10 |
| Browser | Chromium 74.0.3729.169 |

**Comment by afc163** [comment]
为啥会有这个问题，最好排查一下。

@zombieJ

**Comment by zombieJ** [comment]
`rc-resize-observer` 把 `findDOMNode` 改成了 `ref`，FC 没有 ref 导致报错了。Typography 需要 forward 一下。
