### ISSUE TITLE
what's the best practice usage to make icon and text verticalAlign with difference fontSize

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design#19060]
### What problem does this feature solve?
It's great that antd use `vertical-align: -0.125 rem` to solve part problem of verticalAlign for icon and text, it works well when icon and text keep the same fontSize just like following
```
<div style={{ fontSize: 14 }}><Icon type="plus" /> Add</div>
```

But the problem is when they use different fontSizes, it's hard to align them again, such as the following common case
```
<div><Icon style={{ fontSize: 14 }} type="plus" /> Add</div>
```

So what's the best practice usage in this situation?

### What does the proposed API look like?
Maybe export a util function under ant design principle like
```
generateVerticalStyle = (fontSize: number, iconSize: number) => number;
```

**Comment by Stephen2** [comment]
```
<Row type="flex" align="center">
  <Icon style={{ fontSize: 14 }} type="plus" /> Add
</Row>
```
https://codesandbox.io/embed/busy-sutherland-blcro

**Comment by Stephen2** [comment]
Very easy with the magic of Flexbox
