### ISSUE TITLE
能否给一个高级搜索中通过标签选择搜索条件的demo

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#1906]
我是在 http://ant.design/#/docs/pattern/advanced-search 看到的

![image](https://cloud.githubusercontent.com/assets/2271825/15645429/df8c6d1a-268a-11e6-8c4d-d96c5b92edff.png)

**Comment by ddcat1115** [comment]
目前『模式』导航下罗列的一些场景更多是用作设计原则指导，官方暂未coding化，需要自己依靠组件拼装等方式实现。

**Comment by afc163** [comment]
回答完就及时关掉吧。@ddcat1115
