### ISSUE TITLE
Any events triggered while dragging files that are not in 'accept' to Upload.Dragger?

### ISSUE THREAD

**Issue by BenzLeung** [ant-design/ant-design#19068]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有一个文档上传控件，使用'accept'限制了仅允许上传Office文件。
产品经理要求，拖拽不允许的文件进来时需要弹出警告。
但是，通过拖拽的方式加入的不允许的文件并没有触发 'beforeUpload' 事件，我也没有找到其他事件被触发。
如果不使用'accept'，又会影响'点击上传'功能的体验。
那么，请问我该如何满足产品经理的这个要求？

There is an <Upload.Dragger> component that uses 'accept' to restrict uploading of only MS Office files.
The PM requires a warning to pop up when dragging files that are not allowed.
However, the files that are not allowed added by drag and drop did not trigger the 'beforeUpload' event, and I did not find other events being triggered.
If I don't use 'accept', it will affect the 'click to upload' feature.
So, how can I meet this requirement of the PM?

### What does the proposed API look like?
希望 'beforeUpload' 事件不要过滤不允许的文件，或者加一个是否自动过滤的开关。

Hopefully the 'beforeUpload' event does not filter unallowed files, or add a switch that turns off automatic filtering.

**Comment by yoyo837** [comment]
不符合要求的文件拖拽后被忽略，欢迎PR to https://github.com/react-component/upload

**Comment by yoyo837** [comment]
我感觉目前的情况也能理解吧，`accept`的才有资格`beforeUpload `

**Comment by BenzLeung** [comment]
@yoyo837 我也想给 rc-upload 发PR，但是因为涉及API的修改，我觉得贸然去掉`beforeUpload`的过滤功能是个 breaking change，影响面可能有点大了。所以依你们看，有没有什么比较好的兼容方案？

**Comment by yoyo837** [comment]
@BenzLeung 你可以先按你想法提，尽量兼容当下，如果不够好，owner应该会给建议和意见的。

**Comment by zombieJ** [comment]
允许所有文件类型，在 `beforeUpload` 里做判断。fileList 做成受控的。

**Comment by afc163** [comment]
> 允许所有文件类型，在 beforeUpload 里做判断。fileList 做成受控的。

可以按这个来实现。
