### ISSUE TITLE
Where are the typescript definite files(*.d.ts) of antd components, I did not find in the github 

### ISSUE THREAD

**Issue by Lonecy** [ant-design/ant-design#19067]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 I want to know the revision histofy of d.ts files. Where are the typescript definite files(*.d.ts) of antd components. I did not find in the github.

### What does the proposed API look like?
no

**Comment by yoyo837** [comment]
The source code is written with typescript and does not require an additional type declaration.

npm:
`node_modules/antd/es/{components}/*.d.ts`
`node_modules/antd/lib/{components}/*.d.ts`
