### ISSUE TITLE
缩小浏览器比例的时候出现Form表单错乱

### ISSUE THREAD

**Issue by huangcheng1** [ant-design/ant-design#19063]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://img.monunu.com/QQ20190930-135500-HD.mp4](http://img.monunu.com/QQ20190930-135500-HD.mp4)

### Steps to reproduce
Form组件 => 改变浏览器缩放到90% => 提示错误导致表单FormItem错乱

### What is expected?
在缩放时正常

### What is actually happening?
表单错乱

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | Antd官网 |
| System | mac 10.14.5 |
| Browser | Chrome 76.0.3809.132 |

**Comment by shaodahong** [comment]
这是因为浮动元素在缩放的分辨率下高度不一致造成的，两种解决办法

1. 给 `Form.Item` 设置个最小高度
2. 不考虑 IE 9 浏览器的兼容可以使用 `type` [Flex](https://ant.design/components/grid-cn/#Row) 试试
