### ISSUE TITLE
Scrollbar is not disabled when opening a Modal

### ISSUE THREAD

**Issue by remyml57** [ant-design/ant-design#19072]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-modal-reproduction-ddsp8)

### Steps to reproduce
Open the modal

### What is expected?
The scrollbar must be disabled.

### What is actually happening?
The scrollbar is not disabled and we can scroll.

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.8.6 |
| System | Linux 18.04 |
| Browser | Chrome 77.0.3865.90 |

---
I have searched in many issues, there is some tricks.
For example, if you let the settings by default, the scrollbar is hidden, and the body width is resized to simulate a false scrollbar. The problem is that the background image is shifted to the right by 15px (the original scrollbar size) and the visual rendering is not what I expect.
The scrollbars are always displayed in my application.

Sorry for english.

**Comment by zombieJ** [comment]
@jljsj33 , 这里 getContainer 产生 combo 了：
* https://github.com/react-component/dialog/blob/28911814769b73a25e7dde22b9f14127c6e75d54/src/DialogWrap.tsx#L19
* https://github.com/ant-design/ant-design/pull/17600/files#diff-52e85eb6b25a706f4e5d5dc78dfa04acR148

**Comment by jljsj33** [comment]
这是个问题，用 confirm 创建的，由于有创建 dom 里渲染的，不应该去操作 body，想个办法去改 confirm 的实现方式吧，，， getContainer 的使用没有问题。。

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/blob/4680ddc009b1ecbc1bfe70594508301dd8888846/components/modal/confirm.tsx#L149

这里为什么不用 
```
 ReactDOM.render(<ConfirmDialog getContainer={false} {...props} />, div);
=>
 ReactDOM.render(<ConfirmDialog {...props} />, document.body);
```

confirm 里的主要逻辑是搞什么的？？为啥非要整个 dom。。

**Comment by zombieJ** [comment]
https://codesandbox.io/s/kind-margulis-xegcc

**Comment by remyml57** [comment]
@zombieJ i don't understand your sandbox
@jljsj33 what should I do ?
