### ISSUE TITLE
TreeSelect - searching and then selecting multiple items

### ISSUE THREAD

**Issue by arahman** [ant-design/ant-design#19070]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3bfz7)

### Steps to reproduce
Search for 0-1 and then select an item, after selecting the first item, you are unable to select another item as the popup closes.

However, if you choose not to search but expand the tree you are able to select multiple items without the tree closing.

### What is expected?
I would expect the tree not to close when you search and select the first item from the resulting tree. The behaviour should be same as when you expand the tree and select.

### What is actually happening?
The tree popup closes as soon as you select an item from the tree after a search.

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | react |
| System | OSX |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Search will auto expand all tree nodes by filter for user easy to search. After select, it will back to origin expanded state. If you want to keep the search content, you can set `autoClearSearchValue` to `false`.

**Comment by arahman** [comment]
Thanks @zombieJ .
