### ISSUE TITLE
DatePicker的value值传入的是一个string类型，则点击input框后会

### ISSUE THREAD

**Issue by mocha-xsy** [ant-design/ant-design#1907]
当DatePicker的参数value为一个String类型时，例如 "value":"2016-12-12" ，点击input框后会提示Invalid prop `value` supplied to `Picker`

/node_modules/rc-calendar/lib/Picker.js 该文件中的value验证只有 object和array类型：

 value: _react.PropTypes.oneOfType([_react.PropTypes.object, _react.PropTypes.array]),

**Comment by afc163** [comment]
这里 http://ant.design/#/components/date-picker 没有报错，最好给重现。
