### ISSUE TITLE
Slider: custom styles for handle

### ISSUE THREAD

**Issue by ops1ops** [ant-design/ant-design#19073]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/slider-t9sp9)

### Steps to reproduce
1. Change handle width and height to 25px (for example)
2. Focus ant slider and change value from default
3. Change tab in browser or just use alt-tab
4. See that slider value changes

### What is expected?
Slider's value shouldn't change

### What is actually happening?
I dont really understand what is happening, but the same styles on rc-slider works well and considering that ant slider uses rc-slider probably problem is in  ant styles, but i'm not sure

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | react 16.8.6 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 76.0.3809.100 |

**Comment by ops1ops** [comment]
@afc163 
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/slider-t9sp9)

**Comment by shaodahong** [comment]
The reason is `.ant-slider-handle` class has a `marginLeft`, if you change `width` or` height`, should be together changed `marginLeft`, but in `rc-slider` new version, used `transform`, so I send a PR update `rc-slider` version and remove `marginLeft`

https://github.com/react-component/slider/blob/62b949f39f3edc6da657e1a720392d74193f34fb/src/Handle.jsx#L81

**Comment by yoyo837** [comment]
@shaodahong Has #19120 fixed this?

**Comment by shaodahong** [comment]
yep, but #19206 merged will be auto close it

**Comment by yoyo837** [comment]
Aha, my bad.  It's on the `feature` branch.
