### ISSUE TITLE
Ant Design Tag Remove Confirmation

### ISSUE THREAD

**Issue by bishalDores** [ant-design/ant-design#19077]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently ant design Tag has a onClose api reference which is a callback function and is executed when Tag is closed but I need a confirmation before closing the Tag. So it would be better if Ant Design had a callback function which would fire before closing the Tag.

### What does the proposed API look like?
A simple API that would fire before closing the Tag, maybe something like "beforeClose"

**Comment by afc163** [comment]
https://ant.design/components/tag/#components-tag-demo-basic

prevent default
