### ISSUE TITLE
Handle's color should be gray when value of <Slider /> is undefined

### ISSUE THREAD

**Issue by thisrabbit** [ant-design/ant-design#19081]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
While using a <Slider /> in a form, initially it's value should be undefined. However, styles when slider's value is undefined and 0 are same which is hard for users to distinguish.

### What does the proposed API look like?
--

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
