### ISSUE TITLE
Regression: Unused moment.js is now included in bundle

### ISSUE THREAD

**Issue by tony-scio** [ant-design/ant-design#19086]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-l7t2h)

### Steps to reproduce
- Build a trivial app with a single <Input> like https://codesandbox.io/embed/antd-reproduction-template-l7t2h
- Bundle with webpack treeshaking
- Verify that moment.js is not included in bundle

### What is expected?
A trivial webpack app that uses <Input> should not include moment.js in the bundle. In 3.20.7 and earlier, this was the case. 

### What is actually happening?
In 3.21.0 and newer, this simple app pulls in moment.js which bloats the bundle by about 40k even though it's unused. It looks like this was introduced by https://github.com/ant-design/ant-design/pull/17816 which made ConfigProvider depend on LocaleProvider which depends on moment. I believe a fix would be to separate ConfigProvider and ConfigConsumer into separate files.

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.10.1 |
| System | OSX 10.14.6 |
| Browser | Chrome 77.0.3865.90 (Official Build) (64-bit) |

---
This bundle size regression is blocking our ability to upgrade past 3.20.7.

**Comment by afc163** [comment]
same as https://github.com/ant-design/babel-plugin-import/issues/352

**Comment by tony-scio** [comment]
Yep, without being able to read that bug exactly, it looks the same. But it seems to talk a lot about locales. So I'd also like to clarify that the issue isn't just about locales.

We strip moment locales via:
```js
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
```

But even the base moment.js without locales is still too bloated for our initial bundle.

**Comment by yoyo837** [comment]
ref: #19030
