### ISSUE TITLE
Firefox - When scrolling, the first column of the fixed header moves under the fixed column

### ISSUE THREAD

**Issue by serhiitymchenko** [ant-design/ant-design#19091]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-fixed-columns-header](https://ant.design/components/table/#components-table-demo-fixed-columns-header)

### Steps to reproduce
Try diagonal scroll (bottom and right at the same time), and return to the initial position, and you can see that the first column of the fixed header is cut off

### What is expected?
The first column of the fixed header looks normal

### What is actually happening?
The first column of the fixed header cut off after diagonal scroll

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.9.0 |
| System | macOS Mojave 10.14.5 |
| Browser | Firefox Quantum 69.0.1 (64-bit) |

---
It looks like something wrong with a diagonal scroll because in Chrome I can't repro it, (Chrome have scroll only in one direction at the same time).

Video how to reproduce it 
[link](https://drive.google.com/file/d/1kce_928wzB0MWiD5JSwpqXsl_kGNbGBw/view?usp=sharing)

**Comment by afc163** [comment]
Could you test new Table in antd v4? https://ant.design/components/table/

**Comment by afc163** [comment]
Closing for no response.
