### ISSUE TITLE
Add 'replace' icon to Upload component

### ISSUE THREAD

**Issue by shlomitsur** [ant-design/ant-design#19095]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently for changing image you need to press 'remove' and then upload again, we need a simple 'replace' icon like in Twitter profile image

### What does the proposed API look like?
Upload.showUploadList will also allow { showReplaceIcon = True }

**Comment by afc163** [comment]
trace #16047
