### ISSUE TITLE
antd-modal是的真实DOM为何没有渲染在调用它的组件内

### ISSUE THREAD

**Issue by letyougo** [ant-design/ant-design#1909]
- 我自己在写react的时候， 组件的结构是 A-->B->Modal （表示最外层组件A组件有子组件B，B组件内点击某个按钮会弹出antd-modal）这时候弹出的modal的真是DOM结构是在最外层，而并不是在B组件的真是DOM内部，

- 这样做很棒，因为弹出层需要宽高相对浏览器是百分百的，如果真是DOM在B组件内反而实现不了了，所以我很惊叹antd-design到底是如何实现的，能做到改变此时的Modal的真实DOM结构

**Comment by RaoHai** [comment]
https://github.com/react-component/trigger/blob/master/src/Trigger.jsx#L235

**Comment by benjycui** [comment]
对底层有兴趣，建议看源码，谢谢。

**Comment by zhongjie-chen** [comment]
https://github.com/ant-design/ant-design/blob/master/components/modal/confirm.tsx

**Comment by xinwei2016** [comment]
`Modal.info({
        title: '模型检索',
        content: ‘test’,
        closable: true,
        maskClosable: true,
        getContainer: document.querySelector('.uwd-app-view')
});`
我这样写为什么没有挂在制定的 HTMLElement 下，而是直接在 body 下
