### ISSUE TITLE
Handle's color should be gray when value of <Slider /> is undefined

### ISSUE THREAD

**Issue by thisrabbit** [ant-design/ant-design#19090]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1p0mm?fontsize=14)

### Steps to reproduce
Open link and view.

### What is expected?
Before user touch this field, handle's color should be gray or don't display this handle. After user touch it, handle appears with color blue.

### What is actually happening?
There is no differience between value `undefined` and `0`

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 76 |

---
While using a <slider /> in a **form**, initially it's value should be undefined. However, styles when slider's value is undefined and 0 are same which is hard for users to distinguish.

**Comment by shaodahong** [comment]
In my see, the problem is not in Slider component, if Slider visible, they can have an initial value, but sometimes we want to trigger with the user to activate it, you may have to set a custom style, or maybe you need [Rate](https://ant.design/components/rate/) component
