### ISSUE TITLE
Collapse hover open?

### ISSUE THREAD

**Issue by roeljohn** [ant-design/ant-design#19099]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Drag and Drop feature

### What does the proposed API look like?
I'm trying to implement react beautiful drag and drop in collapse. But my boss trying to implement if I drag the item the collapse should open. Is there a way I can implement it? Thanks.

**Comment by afc163** [comment]
```js
const [activeKey, setActiveKey] = useState('');



  <Collapse activeKey={activeKey} onChange={callback}>
    <Panel header={<div onMouseEnter={() => setActiveKey('1')}>This is panel header 1</div>} key="1">
      <p>{text}</p>
    </Panel>
    <Panel header="This is panel header 2" key="2">
      <p>{text}</p>
    </Panel>
    <Panel header="This is panel header 3" key="3" disabled>
      <p>{text}</p>
    </Panel>
  </Collapse>
```
