### ISSUE TITLE
Add switcherIcon to TreeSelect component (as it is in Tree component)

### ISSUE THREAD

**Issue by sergioadimedia** [ant-design/ant-design#19093]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The icon that expands and collapses the tree would be customizable (as it is in Tree component)

### What does the proposed API look like?
The API part for this new prop would look exactly as the API for the Tree component

**Comment by kyle-copeland** [comment]
I'd like to work on this issue 👍

**Comment by sergioadimedia** [comment]
Hi @kyle-copeland ! I've seen you opened a PR nearly a month ago. What is the status of this?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/22489/
