### ISSUE TITLE
Problem with table column positioning

### ISSUE THREAD

**Issue by avifatal** [ant-design/ant-design#19105]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-browser-q4tvh)

### Steps to reproduce
look at the link, create a table with the configurations i wrote

### What is expected?
no spacing in the columns

### What is actually happening?
see image below and the link
![image](https://user-images.githubusercontent.com/12430740/66265193-b251a680-e81a-11e9-8566-c6db789d70d9.png)

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | react latest |
| System | windows 10 pro |
| Browser | chrome lated |

**Comment by afc163** [comment]
https://codesandbox.io/s/vibrant-mcnulty-xmk3q

<img width="1216" alt="image" src="https://user-images.githubusercontent.com/507615/66265591-c9f55300-e84b-11e9-8aec-db14bd9db7a0.png">
