### ISSUE TITLE
about descriptions demo

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#19110]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/descriptions-cn/#components-descriptions-demo-vertical-border](https://ant.design/components/descriptions-cn/#components-descriptions-demo-vertical-border)

### Steps to reproduce
x

### What is expected?
此例子中，Order Time   Usage Time的span为1 3=4，column默认为3，理论来说应该会触发descriptions的exceeds warning，但是为什么浏览器console没有warning？是我对这里span的理解有问题吗

### What is actually happening?
x

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | x |
| System | win10 |
| Browser | chrome 77 |

---
x

**Comment by zombieJ** [comment]
在 Dev 下会报 warning。这个例子要修一下。

**Comment by zkwolf** [comment]
好的，我知道了
