### ISSUE TITLE
Timeline.Item  attribute position has failed.

### ISSUE THREAD

**Issue by alexchen1875** [ant-design/ant-design#19117]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/elegant-feather-b5ukq)

### Steps to reproduce
Open the connection above ,change the Timeline.Item's  position property,left or right ,
not work

### What is expected?
Should be consistent with the configuration

### What is actually happening?
its default 

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.9.0 |
| System | windows |
| Browser | chrome  latest |

---
default

**Comment by alexchen1875** [comment]
ok,i made a mistake ....
when used `mode='alternate'` ,its worked .
maybe we Should be stated in the documentation?

**Comment by zxq08** [comment]
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/46339071/204093147-bf1d2796-b8a7-401b-833a-30bc85a31b90.png">
maybe you should add an explain in the doc...
