### ISSUE TITLE
Cannot get DOM-elements of `<Select />`

### ISSUE THREAD

**Issue by sokki** [ant-design/ant-design#1911]
## What you did

I use `<Select showSearch />`as a auto-complete field

## What you would like to happen

I want to get the DOM-element of the search-input to focus it programatically. 
The used `rc-select` already provide an API to get the DOM-element.

## What actually happened

I'm not able to get the `rc-select` element from antd's `<Select />`. 

## Online demo

http://codepen.io/sokki/pen/rLNQQa?editors=0011

## Environment Information

- antd 1.2.1 

## Possible Solution

add `ref="select"` to `<RcSelect />` in the `render` method of antd's `<Select />`:
https://github.com/ant-design/ant-design/blob/master/components/select/index.jsx#L44
```
      <RcSelect {...this.props}
        ref="select"
        className={cls}
        optionLabelProp={optionLabelProp || 'children'}
        notFoundContent={notFoundContent} />
```

**Comment by RaoHai** [comment]
using `ReactDOM.findDOMNode(this.refs.select).click();` can also focus the search input.

**Comment by sokki** [comment]
Thanx @RaoHai that works for my case!

I think, for other cases the ref would be nice anyway!?

**Comment by RaoHai** [comment]
You can have a try 😄

**Comment by xxgjzftd** [comment]
我去。I don't understand why antd don't add ref to <RcSelect />.

**Comment by bkniffler** [comment]
Me neither.. it would only require a tiny change!

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/3790
