### ISSUE TITLE
Bad example in documentation

### ISSUE THREAD

**Issue by giorgi-m** [ant-design/ant-design#19112]
I created issue this way because it is related to problematic code in the antd documentation.
Here: https://ant.design/components/tabs/
Example with closable tabs(https://codesandbox.io/s/13gos)
There is code which is mutating state directly, which IMHO is[ bad practice](https://stackoverflow.com/questions/37755997/why-cant-i-directly-modify-a-components-state-really):
```
 // code from docs
 add = () => {
    const { panes } = this.state;
    const activeKey = `newTab${this.newTabIndex++}`;
    
    // NOTE: Directly mutates state
    panes.push({ title: 'New Tab', content: 'Content of new Tab', key: activeKey });
    
    this.setState({ panes, activeKey });
  };
```

**Comment by giorgi-m** [comment]
@afc163 sorry for including you, wanted to bring this issue to someone's attention. There's no reason to use the issue helper for this issue.

**Comment by afc163** [comment]
Could you send us a PR for fix?

**Comment by giorgi-m** [comment]
@afc163 I've never used pull feature before, which means I'd have to familiarize myself with it, but I am very busy at the moment, so no, maybe other time.
