### ISSUE TITLE
React Beautiful Drag and Drop Open Collapse Problem

### ISSUE THREAD

**Issue by roeljohn** [ant-design/ant-design#19118]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I having this issue on react beautiful dnd that every time I drag something close collapse it's working but everytime I click or open the collapse and then close it then I try to drag again some item that I have it never allow me to drop it. But if I dont click the panel or collapse it's working properly it's just happen when I click it and then close it again. So I need to refresh again the browser and dont click the collapse to make sure my item drop properly on all close collapse,

I found solution which is forceRender but the problem is that when I use it it will add more issue like problem on animation of droppable. Hmm not sure if this react beautiful dnd or collapse component.

As you can see i am the one who create this issue https://github.com/ant-design/ant-design/issues/19099 which I thought it will fixed the problem but it's not. 

### What does the proposed API look like?
Nothing more I can add on this.

**Comment by zombieJ** [comment]
Hi @roeljohn,
Please fire an issue **with reproduce** instead of feature request. So that we can help to check on it.

**Comment by TrixSc** [comment]
i have a silimar issue, and i would love to get some help on it.
i'm using ant design in a react project, and i want to sort some panels with dnd, but when I try to map the panels inside the collapse, the panels does not open anymore.
Similar example in : https://codesandbox.io/s/sad-bogdan-56si1?file=/src/App.js

thank you
