### ISSUE TITLE
当有children的时候table的hover样式会出现在多行中，有什么办法可以更改

### ISSUE THREAD

**Issue by D-KaiDi** [ant-design/ant-design#19124]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
![image](https://user-images.githubusercontent.com/44960282/66444274-3606cf80-ea75-11e9-8a93-db031e08a853.png)

我固定了第一列以后，当鼠标移入某一行，hover样式出现在了多行，这不是我希望的结果，不知道如何更改，
看控制台发现是由于Hover 是根据data-row-key这个类名判断的

### What does the proposed API look like?
希望能够只在鼠标所在行显示hover
现在是hover会出现在多行

**Comment by yoyo837** [comment]
table的rowspan和colspan，天生不行的。

**Comment by manzxiao** [comment]
天生不行是指的啥，可以有更具体一点的解释吗？谢谢。 @yoyo837

**Comment by yoyo837** [comment]
```html
<tr>
  <td rowspan="2"></td>
</tr>
```

当 td rowspan 大于1时,这个td就会侵占掉下面行的位置,但他属于自己的tr下的元素
