### ISSUE TITLE
A RangePicker‘s problem, It is can not focus on the start input box if i focus on the end input box first

### ISSUE THREAD

**Issue by arielta** [ant-design/ant-design#19128]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/inspiring-bird-5eeod)

### Steps to reproduce
step1：Choose a date range
step2：focus on the end date input box
step3： try to focus on the start date input box

### What is expected?
It is can focus on the start input box

### What is actually happening?
can not

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | IE11 |

**Comment by mullwaden** [comment]
Having the same issue. Also the input looks broken in ie11:

![image](https://user-images.githubusercontent.com/72881/74651923-3894d680-5185-11ea-86a6-f672f714ef16.png)

**Comment by afc163** [comment]
We fixed this problem in antd v4.
