### ISSUE TITLE
affix在modal中会报错 ResizeObserver loop limit exceeded (通过window.error可捕获

### ISSUE THREAD

**Issue by SherryQueen** [ant-design/ant-design#19129]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/suspicious-framework-1o82l?fontsize=14)

### Steps to reproduce
点击 显示弹窗. 即可在控制台观察到错误

### What is expected?
不会报错

### What is actually happening?
提示 ResizeObserver loop limit exceeded

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.8.6 |
| System | mac os 10.15 |
| Browser | chrome 77.0.3865.90  |

---
可以说明下原因吗?

**Comment by shaodahong** [comment]
Ref: https://github.com/WICG/ResizeObserver/issues/38

Google 了一下发现是 Chrome 64 版本之后出现的错误，原因是 `observe()` 之后触发回调导致无限循环超出上限了，看了下目前的一个兼容方案是放到 `requestAnimationFrame` 执行，不知道后续 Chrome 会不会修复

**Comment by mcshaman** [comment]
I encounter this issue with a few components. [The issue seems to be with re-resize-observer.](https://github.com/react-component/resize-observer/issues/236)
