### ISSUE TITLE
Button active <a> tag font color variable

### ISSUE THREAD

**Issue by gharrold-cpr** [ant-design/ant-design#19122]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We want higher contrast active page colours. We want to make the button background primary colour and the font dark with white on hover. We can't currently override the font-colour through variables. It would just make it a lot easier and better follow material design standards. You could also just add a flag for reverse colouring so you swap the background and foreground colours for higher contrast?

### What does the proposed API look like?
None

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by gharrold-cpr** [comment]
If it is adding a variable option then it would be identical to:
@pagination-item-bg-active: @component-background;
But instead adding:
@pagination-item-font-active: @primary-color;

If someone wanted to add an flag to do high-contrast that would be more complicated. As it could be applied to all the CSS in ant. So I doubt that would happen.

**Comment by afc163** [comment]
closing for no more response
