### ISSUE TITLE
Check loosely prop on Tree component

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#19138]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am building a tree with checkboxes and some of the tree nodes have children tree nodes. 
- [ ] Grandparent 1
  - [ ] Parent 1
    - [ ] Child 1
    - [ ] Child 2

Currently the only way that I can check Parent 1 without Child 1 and Child 2 getting checked is to use the 'checkStrictly' prop. This has a limitation that Grandparent 1 does not move into a half-checked state. 

### What does the proposed API look like?
KendoReact does support this behavior through a (helper function)[https://www.telerik.com/kendo-react-ui/components/treeview/checkboxes/helper-functions/]. Perhaps a prop 'checkLoosely' where the checked state can bubble up from Parent 1 to Grandparent 1.

**Comment by zombieJ** [comment]
`checkLoosely` is similar with `checkStrictly`, you can pass `halfChecked` with `checkStrictly` for customize half checked logic.

**Comment by mohit000001** [comment]
I'm facing same issue. We are using antd 3.7.3. But I'm not able to find checkLoosely prop anywhere in Ant docs.  @zombieJ please provide solution.
