### ISSUE TITLE
disable a form.item

### ISSUE THREAD

**Issue by THAIMENN** [ant-design/ant-design#19134]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
To disable the form.item but not hiding it.

### What does the proposed API look like?
disabled={true} and the standard of disabled is false
Disabled would be same for a button in ant.design u can see it but not click it

**Comment by yoyo837** [comment]
Form.Item just a wrapper component for Form layout, you need to control the actual form element disabled state yourself.
