### ISSUE TITLE
Tree.DirectoryTree - defaultExpandAll does not work when using treeData

### ISSUE THREAD

**Issue by pfcodes** [ant-design/ant-design#19132]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pfcodes/pen/WNNvpOP](https://codepen.io/pfcodes/pen/WNNvpOP)

### Steps to reproduce
Use: <Tree.DirectoryTree treeData={[]} defaultExpandAll></Tree.DirectoryTree> instead of <Tree.DirectoryTree defaultExpandAll>{TreeNode[]}</Tree.DirectoryTree>

### What is expected?
All tree nodes should be expanded.

### What is actually happening?
Tree nodes are not expanded.

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | react 16.10.2 |
| System | macOS 10.14.6 |
| Browser | Version 77.0.3865.90 (Official Build) (64-bit) |

---
I needed to recursively create `TreeNodes`. The `DirectoryTree` component does not allow any component other than `TreeNode` to be used as a child. Since I could not use custom components (i.e., DirectoryNode/FileNode) that were output from a recursive function that first determines whether a node is a directory or file, I found `treeData` and used that instead. I noticed the bug then.

**Comment by kavience** [comment]
I have find the bug and I have make a new PR in [https://github.com/ant-design/ant-design/pull/19148](https://github.com/ant-design/ant-design/pull/19148), can you take a look ? @afc163

**Comment by jeremypeters** [comment]
I'm experiencing this issue when the tree data is updated. When using `defaultExpandAll={true}` the tree is expanded, but when the tree data is updated, the tree collapses.

**Comment by jonathaninacio** [comment]
> I'm experiencing this issue when the tree data is updated. When using `defaultExpandAll={true}` the tree is expanded, but when the tree data is updated, the tree collapses.

I had the same problem and realize it was because all keys in treedata has changed.
New nodes are collapsed by default, only the original ones (default) are expanded. But in tree data when all keys are different from the original one, the tree is deleted and replaced with a new one (so it's not the default tree anymore).

**Comment by blazephoenix** [comment]
Was this resolved?

**Comment by calllpso** [comment]
you should to add a v-if condition, after that it will work
`
<a-tree
      v-if="treeData.length>0"
      :defaultExpandAll="true"
      :tree-data="treeData"
      >
            
</a-tree>	 
`

**Comment by codeiland** [comment]
To those who have these problem, you just have to render Tree conditionaly, and render it only if treeDta already ready, something like this treeData.length && <Tree    defaultExpandAll={true}    treeData={ treeData }  />

**Comment by DinhChinh170603** [comment]
it's still not working, I have a tree by parsed XML, when component render, the tree still not expand all, why?
![image](https://github.com/user-attachments/assets/ba87d25f-cf48-485d-ae06-bface0465c17)
