### ISSUE TITLE
动态增删表单内容的校验问题

### ISSUE THREAD

**Issue by zjb19970804** [ant-design/ant-design#19131]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zjb19970804/project/editor/ZWRqvq](https://codepen.io/zjb19970804/project/editor/ZWRqvq)

### Steps to reproduce
按照官网的动态增加表单filed的例子，我从服务端填充初始值时，更改field，不会发出错误警告，值也无法更改，如果没有初始值，校验是正常的。我初步判断是表单field名称变化，错误消息无法绑定到新的field，因为每次render，key都会变，field也跟着变化了。请帮助我解决这个问题，thank 。

According to the example of dynamically adding form files on the official website, when I fill in the initial value from the server, I change the field without giving an error warning or changing the value. If there is no initial value, the validation is normal. My preliminary judgment was that the form field name changed, and the error message could not be bound to the new field, because every render, the key changed, and the field changed. Please help me solve this problem, thank you.

### What is expected?
能正确的显示错误信息。如果是官网的用法有问题，请给出正确示例

Can display error information correctly. If there is a problem with the use of the official website, please give a correct example.

### What is actually happening?
校验的错误信息没有显示， field值无变化

The error message of the check is not displayed and the field value is unchanged

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.8.1 |
| System | window 64 |
| Browser | google |

**Comment by kavience** [comment]
初步看了一下代码，不是 ant-design 的问题，是你使用方式不对。
1. timeRangeStart 不要用这种格式 '9:00, 10:00, 12:00'，请使用数组，例如：
```
rule: [
    {
        timeRangeStart: '9:00',
        timeRangeEnd: '9:30'
    },
    {
        timeRangeStart: '10:00',
        timeRangeEnd: '10:30'
    },
    {
        timeRangeStart: '12:00',
        timeRangeEnd: '12:30'
    },
]
```
2. 把 keys.map((item, index) 那一块封装出去，作为一个组件，传入 prefix 和 index，在组件中添加 onChange 事件，如下：
```
handleChange = e => {
        const { form, index } = this.props;
        const prefix = `${this.props.prefix}[${this.props.index}]`;
        form.setFieldsValue({
            [`${prefix}.index`]: index + 1,
            [`${prefix}.timeRangeStart`]: e.xxx,
            [`${prefix}.timeRangeEnd`]: e.xxx,
        });
    }
```
3. add item 和 remove item 主要就是对数组元素进行添加和删除操作，大致就是这样子。

**Comment by zjb19970804** [comment]
> 初步看了一下代码，不是 ant-design 的问题，是你使用方式不对。
> 
> 1. timeRangeStart 不要用这种格式 '9:00, 10:00, 12:00'，请使用数组，例如：
> 
> ```
> rule: [
>     {
>         timeRangeStart: '9:00',
>         timeRangeEnd: '9:30'
>     },
>     {
>         timeRangeStart: '10:00',
>         timeRangeEnd: '10:30'
>     },
>     {
>         timeRangeStart: '12:00',
>         timeRangeEnd: '12:30'
>     },
> ]
> ```
> 
> 1. 把 keys.map((item, index) 那一块封装出去，作为一个组件，传入 prefix 和 index，在组件中添加 onChange 事件，如下：
> 
> ```
> handleChange = e => {
>         const { form, index } = this.props;
>         const prefix = `${this.props.prefix}[${this.props.index}]`;
>         form.setFieldsValue({
>             [`${prefix}.index`]: index + 1,
>             [`${prefix}.timeRangeStart`]: e.xxx,
>             [`${prefix}.timeRangeEnd`]: e.xxx,
>         });
>     }
> ```
> 
> 1. add item 和 remove item 主要就是对数组元素进行添加和删除操作，大致就是这样子。

我把keys存到redux了，只要不在render里面执行id++就行了，不然每次的field都会变化。
