### ISSUE TITLE
Input.Search fires onSearch on clear

### ISSUE THREAD

**Issue by rodrigoehlers** [ant-design/ant-design#19137]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/relaxed-brahmagupta-er79n)

### Steps to reproduce
IGNORE THE MISSING CSS!

1. Open the `console` tab on the bottom of the right hand side.
2. Enter some text into the input field. You will see `change` is logged for each change.
3. If you click on the little x which is produced by `allowClear`, you will see that `search` and `change` are logged.

### What is expected?
Clicking x from `allowClear` should not fire `onSearch` event.

### What is actually happening?
Clicking x from `alloweClear` is firing `onSearch` event.

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.10.2 |
| System | Mac OS Catalina 10.15 |
| Browser | Chrome Version 77.0.3865.90 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18729

**Comment by rodrigoehlers** [comment]
Okay, I wasn't aware this was intended. Documentation for `onSearch` in `Input` states:

> The callback function that is triggered when you click on the search-icon or press Enter key.

Should contain clicking clear-icon produces the same. Something like:

> The callback function that is triggered when you click on the search-icon, **the clear-icon** or press Enter key.

**Comment by afc163** [comment]
Could u send us a PR to fix documentation?

**Comment by rodrigoehlers** [comment]
Will do! Will only be English one though. Hope that's fine.
