### ISSUE TITLE
Select value in antd Select

### ISSUE THREAD

**Issue by iBobo5** [ant-design/ant-design#19143]
Hello.
I've a question: I've got my Select component of ant-design and an array of objects ({id: xxx, name: xxx}).
I'd like to search by the name (Apples, Bananas...) but I'd like to get the id code when I choose one item from the options. How can I do?
Here's my code:

const options= [
  { id: 1, name: 'Apples' },
  { id: 2, name: 'Nails' },
  { id: 3, name: 'Bananas' },
  { id: 4, name:  'Helicopters' }
];

class MySelect extends React.Component {
  state = {
    selectedItems: [],
  };

  handleChange = selectedItems => {
    this.setState({ selectedItems });
  };

  render() {
    const { selectedItems } = this.state;
    const filteredOptions = options.filter(o => !selectedItems.includes(o.id));
    return (
      <Select
        mode="multiple"
        placeholder="Inserted are removed"
        value={selectedItems}
        onChange={this.handleChange}
        style={{ width: '100%' }}
      >
        {filteredOptions.map(item => (
          <Option key={item.id}>{item.name}</Option>
        ))}
      </Select>
    );
  }
}

In this way I can get the id code but I'm not able to search by the name.
Can someone help me?

**Comment by keithort** [comment]
Something like this is probably what you are looking for.
```
<Select
                allowClear
                filterOption={(inputValue, option) =>
                  option.props.children
                    .toString()
                    .toLowerCase()
                    .includes(inputValue.toLowerCase())
                }
                showSearch
              >
                {options.map(option=> (
                  <Option key={option.id}>{option.name}</Option>
                ))}
              </Select>
```

**Comment by iBobo5** [comment]
@keithort it works! Thank you very much !

**Comment by ali-alamine** [comment]
@keithort @ibigbug how to access the key (item.id) ?

**Comment by KbnCodes** [comment]
iam also having same question . how to get id of selected item?

**Comment by urakovaliaskar** [comment]
> iam also having same question . how to get id of selected item?
You can set prop value in Option like 
`<Option value-{option.id}>`
then get the id in filterOptions like option.props.value
If you want to search both then
`filterOption={(input, option) =>
    option.props.label
      .toString()
      .toLowerCase()
      .indexOf(input.toLowerCase()) >= 0 ||
    option.props.value
      .toString()
      .toLowerCase()
      .indexOf(input.toLowerCase()) >= 0
}`
