### ISSUE TITLE
类型定义，table中fixed校验

### ISSUE THREAD

**Issue by steady-join** [ant-design/ant-design#19146]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?editors=0010](https://codepen.io/pen/?editors=0010)

### Steps to reproduce
<img width="827" alt="屏幕快照 2019-10-10 上午9 07 10" src="https://user-images.githubusercontent.com/29935583/66531265-b7299980-eb3d-11e9-85c0-a2661d266e35.png">
<img width="613" alt="屏幕快照 2019-10-10 上午9 10 29" src="https://user-images.githubusercontent.com/29935583/66531293-d45e6800-eb3d-11e9-8575-9954fdc911c6.png">
<img width="851" alt="屏幕快照 2019-10-10 上午9 19 06" src="https://user-images.githubusercontent.com/29935583/66531657-16d47480-eb3f-11e9-88c4-251201efdb7c.png">

### What is expected?
类型校验通过

### What is actually happening?
未通过

| Environment | Info |
|---|---|
| antd | 3.23.5 |
| React | 16.9.0 |
| System | mac |
| Browser | chrome |

**Comment by steady-join** [comment]
@afc163 ,你好，我无法通过上面的链接重现这个问题，但是我可以提供代码片段和截图。
<img width="693" alt="屏幕快照 2019-10-10 下午12 40 24" src="https://user-images.githubusercontent.com/29935583/66539618-3bd6e080-eb5b-11e9-9048-d0f3320a0091.png">
<img width="1040" alt="屏幕快照 2019-10-10 下午12 40 37" src="https://user-images.githubusercontent.com/29935583/66539619-3c6f7700-eb5b-11e9-9585-cef919988879.png">
<img width="1056" alt="屏幕快照 2019-10-10 下午12 40 46" src="https://user-images.githubusercontent.com/29935583/66539620-3c6f7700-eb5b-11e9-899f-e8bd30504309.png">
下面是代码
```
class Demo extends Component {
  public render() {
    const columns = [
      {
        title: '作业编号',
        dataIndex: 'workNumber',
        key: 'workNumber',
      },
      {
        title: '作业名称',
        dataIndex: 'workName',
        key: 'workName',
      },
      {
        title: '作业人数',
        dataIndex: 'userNum',
        key: 'userNum',
      },
      {
        title: '作业工时',
        dataIndex: 'hourNum',
        key: 'hourNum',
      },
      {
        title: '作业总工时',
        dataIndex: 'hourNumTotal',
        key: 'hourNumTotal',
      },
      {
        title: '所属设备',
        dataIndex: 'equipmentName',
        key: 'equipmentName',
      },
      {
        title: '操作',
        key: 'action',
        fixed: 'right',
        render: () => <div>123</div>,
      },
    ];

    return <Table scroll={{ x: 1200 }} columns={columns} dataSource={[]} />;
  }
}

export default Demo;

**Comment by afc163** [comment]
`fixed: 'right' as 'right',`，你可以先这么写。

这块应该要用 tuple 的方式重写一下枚举定义，有兴趣帮忙来个 PR 么。

**Comment by GOWxx** [comment]
用 ts 开发时遇到这个问题 可以参照文档
https://ant.design/components/table-cn/#%E5%9C%A8-TypeScript-%E4%B8%AD%E4%BD%BF%E7%94%A8
为 columns 和 data 添加类型
