### ISSUE TITLE
Upload 组件如何操作fileList

### ISSUE THREAD

**Issue by Maopy** [ant-design/ant-design#1914]
![image](https://cloud.githubusercontent.com/assets/4091726/15665832/02517c40-2740-11e6-97f2-d55993448c48.png)
如图，我想根据服务端返回的JSON判断图片是否上传成功。如果上传失败，则去除fileList最后一项。请问正确姿势是什么样的

**Comment by afc163** [comment]
http://ant.design/#/components/upload?scrollTo=components-upload-demo-fileList

参考这个。

**Comment by Maopy** [comment]
谢谢~ 刚提完就找到文档了。。 好尴尬。。
