### ISSUE TITLE
Drawer body css offset is not reset when drawer is destroyed

### ISSUE THREAD

**Issue by pierre-b** [ant-design/ant-design#19159]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ibb.co/dGbz96K](https://ibb.co/dGbz96K)

### Steps to reproduce
1. go to https://ant.design/components/button/
2. then go to https://ant.design/components/drawer/
3. open the drawer
4. go the the previous page via your browser history
5. open the DOM inspect and you will see the <body style="width: calc(100% - 15px)"> is not reset

### What is expected?
The drawer css body offset should not remain in the body when the drawer is not visible

### What is actually happening?
the body css "width: calc(100% - 15px)" will stay forever and destroy my app design

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16 |
| System | MacOS |
| Browser | All |

---
To avoid overloading my render compute, I place a lot of drawers into "if" statements like: {this.state.drawerVisible && <Drawer...></Drawer}
When the drawer is not visible anymore, it's killed by the render and the hiding animation doesn't complete the css cleanup.

**Comment by pierre-b** [comment]
Great work, thanks for the fix 👍

**Comment by GaboMendez** [comment]
still happens on version 4.17.0

**Comment by mortezanjfi** [comment]
this is my sulution to both keep animation and fix issue:
i create something like middleware with useState and first of all we should set it true/false and then with little timeout we kill it by setting false inside useEffect

```
const [visible, setVisible] = useState(false);

  const showDrawer = () => {
    setVisible(true);
  };

  const onClose = () => {
    setVisible(false);
  };
  return (
        <CustomDrawer onClose={onClose} visible={visible} />  
  );


------------------------------------------------------------------------------

const CustomDrawer = ({ onClose, visible }) => {
  const [flag, setFlag] = useState(visible);
  useEffect(() => {
    if (visible) {
      setFlag(true);
    } else {
      setTimeout(() => {
        setFlag(false);
      }, 500);
    }
  }, [visible]);
  return (
    <>
      {flag && (
        <Drawer
          onClose={onClose}
          visible={visible}
        >
         ...
        </Drawer>
      )}
    </>
  );
};

export default CustomDrawer;
```
