### ISSUE TITLE
table 切换数据源分页器不回到第一页

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design#19152]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-feather-1rd7h)

### Steps to reproduce
1、跳转到 数据源1 的第十页
2、点击切换按钮，分页器位于数据源二的第五页

### What is expected?
切换数据源后，分页器应该是位于第一页，展示第一页的数据

### What is actually happening?
实际结果的是不是第一页，与之前切换的页数有关

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.9.0 |
| System | macos |
| Browser | chrome |

---
从服务器获取数据每次获取10条，会造成，切换数据源后，分页器是第n页，但是数据展示的是第一页的数据也就是前十条

**Comment by afc163** [comment]
建议自行控制当前页码，切换数据源保持当前页目前看来是合理的默认需求。

**Comment by Benpaodejiezai** [comment]
数据源都切换了还要保持当前页？真的合理吗？那这样的话数据源2为什么不是第10页显示无数据，而是第五页呢？

**Comment by Benpaodejiezai** [comment]
> 建议自行控制当前页码，切换数据源保持当前页目前看来是合理的默认需求。
数据源都切换了还要保持当前页？真的合理吗？那这样的话数据源2为什么不是第10页显示无数据，而是第五页呢？

**Comment by Benpaodejiezai** [comment]
> 建议自行控制当前页码，切换数据源保持当前页目前看来是合理的默认需求。

数据源都切换了还要保持当前页？真的合理吗？那这样的话数据源2为什么不是第10页显示无数据，而是第五页呢？

**Comment by yoyo837** [comment]
状态自己维护啊，哪怕是错误的，也是自己维护。我觉得和是否默认保持无关吧。

**Comment by afc163** [comment]
数据源切换对于 antd 来说是很难区别的，比较下面两个切换方式：

```jsx
this.setState({
  dataSource: [...this.state.dataSource, { name: 'new record' }],
})
```

```jsx
this.setState({
  dataSource: [{ name: 'new record' }],
})
```

对这两种场景，显然第一个应该保持先前的所有状态（分页/筛选/排序），后一个应该重置。

但是从 js 的角度来说，这两种用法对 Table 来说都是两个新的 dataSource，无法区别是哪一个是在老 dataSource 上做修改，还是完全新的 dataSource。保持状态是目前的默认逻辑，需要重置状态，可以用受控模式去清空。

**Comment by Valar103769** [comment]
> > 建议自行控制当前页码，切换数据源保持当前页目前看来是合理的默认需求。
> 
> 数据源都切换了还要保持当前页？真的合理吗？那这样的话数据源2为什么不是第10页显示无数据，而是第五页呢？

我支持你的观点
