### ISSUE TITLE
DatePicker组为showTime时，能否支持选完日期就弹出时分秒选项框

### ISSUE THREAD

**Issue by Devvvin** [ant-design/ant-design#19156]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
选完日期后，再点击选择时间才弹出时分秒选项框

### What is expected?
DatePicker组为showTime时，支持选完日期就弹出时分秒选项框

### What is actually happening?
选完日期后，再点击选择时间才弹出时分秒选项框

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | ^16.3.1 |
| System | window |
| Browser | chrome |

**Comment by yoyo837** [comment]
It's by design.

**Comment by shaodahong** [comment]
我认同，现在的设计需要用户点一下才可以选择时间，不够直观，对于有对应需求的用户来说选择日期和选择时间其实是一个同步的操作，我在实际项目中也遇到过

有选择时间应该和日期同步展示

![image](https://user-images.githubusercontent.com/14831261/66566354-5169fb80-eb97-11e9-9126-bceb625d8ca8.png)

**Comment by shaodahong** [comment]
Ref: #6539

**Comment by Devvvin** [comment]
[Image]
非常感谢您的回复，现在在用时间范围组件也一样，能否支持像element UI组件库那样直观，并且支持自定义快捷选项，我这边需求，最近3个小时等，不都是最近一个星期，最近一个月，最近3个月这样，如果支持这种交互方式的话，大概什么时候可以使用！
不管是否支持我想要的交互效果，都期待您的回复，以便我确认下，谢谢！😀

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 骗你是小猫咪 <notifications@github.com>
发送时间: Thursday, October 10, 2019 8:02:37 PM
收件人: ant-design/ant-design <ant-design@noreply.github.com>
抄送: Devvvin <shiyonglee@outlook.com>; Author <author@noreply.github.com>
主题: Re: [ant-design/ant-design] DatePicker组为showTime时，能否支持选完日期就弹出时分秒选项框 (#19156)


Ref: #6539<https://github.com/ant-design/ant-design/issues/6539>

**Comment by shaodahong** [comment]
@afc163 4.0 版本 DatePicker 有相关的改进计划没

**Comment by Devvvin** [comment]
非常感谢你们的回复，请问4.0大概什么时候发布
