### ISSUE TITLE
Add prop to change close icon for Drawer

### ISSUE THREAD

**Issue by dspacejs** [ant-design/ant-design#19153]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Our design has a custom icon for our mobile sidebar's close button. It would be great if there were a prop to change the close icon for the Drawer component.

### What does the proposed API look like?
A prop for rendering the icon. E.g:

```jsx
<Drawer icon={<SomeIcon />} />
```

**Comment by knowankit** [comment]
Can I take this issue?

**Comment by yoyo837** [comment]
PR welcome

**Comment by orenk86** [comment]
Any news on this?
