### ISSUE TITLE
Select在设置labelInValue后，Option中如果设置了value，事件取到的值key是value，不适用于mode=tags模式

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design#19151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-3lh69)

### Steps to reproduce
步骤在重现链接的示例里

### What is expected?
期望在重现链接的示例里

### What is actually happening?
实际结果在重现链接的示例里

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.7 |
| System | windows7 |
| Browser | chrome |

---
我在使用select的mode="tags"模式，设置了labelInValue，我输入选项中不存在的值时，能动态添加一个并保存数据库

**Comment by dmdoit** [comment]
我看了一些Issues，很多Option是非循环的，那么就没有key，那么在labelInValue时，如何使在Options设置了value的情况下，事件function(value, option:Option/Array<Option>)中value打印出来
{"key":"此处是实际业务中的id","label":"张三"}

**Comment by zombieJ** [comment]
`optionFilterProp`
