### ISSUE TITLE
Docs: amend InputNumber API with 'type'

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#19157]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For now InputNumber accepts letters as input. Which is counter-intuitive.
Unless you find this issue - https://github.com/ant-design/ant-design/issues/9421#issuecomment-446812723
And set `type={"number"}`.

### What does the proposed API look like?
Amend the docs with `type` prop.
Also make it `true` by default.

**Comment by shaodahong** [comment]
@afc163 这可以优化的吧，从语义上来说 InputNuber 不应该支持数字以外的字符

**Comment by afc163** [comment]
We have `formatter` property which allows non-digit chars.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17344#issuecomment-506376039

**Comment by avalanche1** [comment]
At least you could amend the docs..
