### ISSUE TITLE
Rows not expanded by default

### ISSUE THREAD

**Issue by DeveloperFromUkraine** [ant-design/ant-design#19166]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-functional-component-b4t7j?fontsize=14)

### Steps to reproduce
https://codesandbox.io/s/react-functional-component-b4t7j?fontsize=14

### What is expected?
expanded all by default

### What is actually happening?
not expand

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | latest |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment]
`defaultXxx` only works on first render, just like `defaultValue` for input.

https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically
