### ISSUE TITLE
Upload组件支持粘贴上传

### ISSUE THREAD

**Issue by xuanxuan321** [ant-design/ant-design#19164]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
客服每天会处理大量的投诉，投诉中的图片要在工单系统中做备案，每次下载下来再通过选择上传太麻烦，如果Upload组件能够通过粘贴上传，那就减少了很多重复的劳动力

### What does the proposed API look like?
Api不用变更，只是希望Upload.Drag能支持粘贴上传

**Comment by kavience** [comment]
可以自己改装，弹出一个 model，然后在这个 model 内增加粘贴上传功能，这个功能应该不输入 upload 组件，毕竟它只是负责上传文件

**Comment by xiahaichao11** [comment]
想看看你的上传照片的功能代码可以吗

**Comment by xuanxuan321** [comment]
@kavience 正解
