### ISSUE TITLE
Ability to turn off expanded table extra row

### ISSUE THREAD

**Issue by snax4a** [ant-design/ant-design#19162]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using expanded row in antd table there is automatically created extra row on the left side of the expanded row body and currently its not possible to get rid of that
End user would need this for example on mobile screens when there is less space and we want to use expanded rows feature this extra row takes a lot of space

### What does the proposed API look like?
Add prop to the Table component called expandedRowIndent={false}

**Comment by afc163** [comment]
https://codesandbox.io/s/stupefied-napier-ckkyj

https://github.com/react-component/table
