### ISSUE TITLE
inputnumber组件增加加减按钮显示开关

### ISSUE THREAD

**Issue by llfylwg** [ant-design/ant-design#19168]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
inputnumber组件增加加减按钮显示开关

### What does the proposed API look like?
一个字段即可

**Comment by afc163** [comment]
隐藏按钮相当于直接用 `<Input />` 了。

建议用样式直接覆盖。

**Comment by yoyo837** [comment]
我在想TA是不是这个意思？

![image](https://user-images.githubusercontent.com/6134547/66693979-87b39200-ece1-11e9-8541-2e6c59a99b83.png)

**Comment by llfylwg** [comment]
不是，我只想要输入数字的input，不是input能输入英文字目给出提示这种

**Comment by afc163** [comment]
Try `<Input type="number" />`.

**Comment by 510846** [comment]
> 我在想TA是不是这个意思？
> 
> ![image](https://user-images.githubusercontent.com/6134547/66693979-87b39200-ece1-11e9-8541-2e6c59a99b83.png)

这个应该怎么实现？请指教 ~

**Comment by yoyo837** [comment]
自己封装

**Comment by 510846** [comment]
> 自己封装

这个应该很常见？找了一圈没找到。。。。
自己不太擅长 CSS，写不动 @@ 兄弟，有分享吗？

**Comment by yoyo837** [comment]
没有哈，移动端这种风格比较常见

**Comment by 510846** [comment]
> 没有哈，移动端这种风格比较常见

嗯，Vue 用的就是上面图片的风格，其实挺喜欢的，因为比较直观，直接可以操作 加/减，很多电商基本也采用了这样的设计 ~

**Comment by Moderation-T** [comment]
> 不是，我只想要输入数字的input，不是input能输入英文字目给出提示这种

可以试试用 css 进行隐藏

.ant-input-number-handler-wrap {
  display: none;
}
