### ISSUE TITLE
Volunteer for 4.0 `rc-trigger` upgrade

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#19169]
## Why

For [antd@4](https://github.com/ant-design/ant-design/issues/16911) plan, we will use new lifecycle method for removing React legacy warning. [`rc-trigger`](https://github.com/react-component/trigger) has finished migration. Dependencies react component should also update:

## React Component

- [x] 🚀rc-select @zombieJ https://github.com/react-component/select/pull/430
- [x] 🚀rc-tree-select @zombieJ 
- [x] 🚀rc-calendar @chenshuai2144 
- [x] 🐾rc-cascader @shaodahong 
- [x] ☀️rc-dropdown @shaodahong 
- [x] 🚀rc-menu @zombieJ 
  - [x] ☀️rc-mentions @shaodahong 
- [x] ☀️rc-time-picker @afc163 
- [x] ☀️rc-tooltip @orzyyyy 
- [x] 🏆antd @shaodahong 

### Priority
🚀High (Before end of October)
☀️Normal (Before middle of November)
🐾Pending (Need some code refactor before upgrade)

**Comment by afc163** [comment]
Any collaborator would like to help can update issue and assign self.

**Comment by afc163** [comment]
Is it a deadline for each component?

**Comment by zombieJ** [comment]
> Is it a deadline for each component?

Thanks for tips, add the priority in desc.

**Comment by zombieJ** [comment]
Move `rc-mentions` under `rc-menu` since dependency.

**Comment by shaodahong** [comment]
@zombieJ `antd` component step by step migration?

**Comment by zombieJ** [comment]
@shaodahong,
`antd` task is to check if any component rely on the component which missing update with latest version. Should follow above volunteer PR process and make sure react component version updated in `4.0-prepare` and motion is work as expect.

You can use `npm ls rc-trigger` for a quick check:

<img width="555" alt="屏幕快照 2019-10-09 下午4 43 20" src="https://user-images.githubusercontent.com/5378891/66697520-e9d3bd80-ed08-11e9-88bd-28b3661abce9.png">

In process:
* https://github.com/react-component/tooltip/pull/195

**Comment by shaodahong** [comment]
ok, so I change #19179  title to `WIP`, I will check to relate component PR progress until finished migration

**Comment by zombieJ** [comment]
hi Contributors,
Assign list updated. Need more help on rest `rc-component` update. Thanks for all your volunteer.

**Comment by shaodahong** [comment]
@zombieJ `rc-cascader` now **Pending** status, wait for a new design or other something

**Comment by shaodahong** [comment]
and we should be migration by Typescript, abandon like this `declare module 'rc-*';`, use `Omit` or `Pick` or `extend` combination type

**Comment by afc163** [comment]
rc-time-picker: https://github.com/react-component/time-picker/pull/170

**Comment by zombieJ** [comment]
* `rc-calendar` & `rc-cascader` can use `rc-select` generator to generate accessibility version. But it's not blocking issue just a mark. (We can adjust these after v4 release step by step)
* Yes. All the component is better consider use typescript since definition already has in antd and can be moved into rc easily.

**Comment by shaodahong** [comment]
@zombieJ [rc-slider](https://github.com/react-component/slider) should migration, dependencies has `rc-trigger`.

**Comment by zombieJ** [comment]
`rc-slider` use `rc-trigger` as dev deps for example usage. It's better to upgrade but not must have for this issue.

**Comment by shaodahong** [comment]
not for example, dependencies `rc-tooltip` used it, and `rc-tooltip` has upgraded

**Comment by zombieJ** [comment]
👌

**Comment by shaodahong** [comment]
Closed via https://github.com/ant-design/ant-design/pull/19179
