### ISSUE TITLE
Error evaluating function `darken`: Argument cannot be evaluated to a color

### ISSUE THREAD

**Issue by a044161** [ant-design/ant-design#19171]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/search?q=%40table-header-sort-active-bg%3A darken%28%40table-header-bg%2C 3%25%29&unscoped_q=%40table-header-sort-active-bg%3A darken%28%40table-header-bg%2C 3%25%29](https://github.com/ant-design/ant-design/search?q=%40table-header-sort-active-bg%3A darken%28%40table-header-bg%2C 3%25%29&unscoped_q=%40table-header-sort-active-bg%3A darken%28%40table-header-bg%2C 3%25%29)

### Steps to reproduce
```js
modifyVars: {
    'table-header-bg': 'linear-gradient(-180deg, rgba(219, 219, 219, 0.22) 0%, rgba(181, 181, 181, 0.22) 100%)',
}
```

定位到的问题是：`@table-header-sort-active-bg: darken(@table-header-bg, 3%)` 中 `darken` 并不支持 `linear-gradient`

### What is expected?
3.9.x的版本中还不存在`@table-header-sort-active-bg`，所以这样的写法是可以的，现在更新后就无法使用了，有点难追溯是哪个版本调整的。

### What is actually happening?
抛出`Error evaluating function `darken`: Argument cannot be evaluated to a color`

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | react 16.8.4 |
| System | osx 10.14.6 |
| Browser | chrome 77.0.3865.90 |

**Comment by zombieJ** [comment]
你的版本太老了：https://github.com/ant-design/ant-design/pull/12775/files

可以替换 `@table-header-sort-active-bg` & `@table-header-filter-active-bg` 这两个变量。
