### ISSUE TITLE
 选择器Select组件 disabled后，点击下拉三角依然可用

### ISSUE THREAD

**Issue by JovenPan** [ant-design/ant-design#1917]
## 你做了什么？

选择器Select组件 disabled

## 你期待的结果是：

组件完全禁用

## 实际上的结果和抱怨：

点击下拉三角组件依然可用

## 可重现的在线演示

[线上demo就可重现，第一组](http://ant.design/#/components/select)

## 本地环境信息

- antd 版本: 1.2.1

**Comment by ddcat1115** [comment]
@yiminghe 看一下呢？好像rc-select是有这个问题...
