### ISSUE TITLE
calling "this" context function breaks sorting

### ISSUE THREAD

**Issue by raytorres280** [ant-design/ant-design#19178]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/raytorres280/antd-bug](https://github.com/raytorres280/antd-bug)

### Steps to reproduce
clone repo, then uncomment setState() from onTableChange on line 40-45. 

Either comment back out the setState(), or remove the filters, and sorting behaves as normal.

### What is expected?
Expected behavior is I can use filtering and "this" context functions within Table onChange.

### What is actually happening?
Any function referred to from "this" context within onChange function for Table forces sorting into inital sort order direction.

This only happens if both filtering and sorting is enabled. if you remove filtering, it functions as normal, cycling asc, desc, default.

Also, if you remove this context function calls, both filtering and sorting behave as normal. It's only when both filtering is enabled on the column and you call a "this" context function.

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.10.2 |
| System | Windows 10 |
| Browser | Chrome 77.0.3865.90 |

---
I think it fails deep object comparison at antd/es/table/Table.js isSameColumn(sortColumn, column) when conditions above are met.
Since it always returns false in that case it stays stuck at initial sort direction, sortDirections[0]

**Comment by raytorres280** [comment]
Looks like shallowEqual might be the cause. The columns are identical in inSameColumn from my eyes and the deep object compare we do with shallowEqual doesnt return true when it should.

I can get around this by applying the "key" property to my columns, but my dataIndex's are unique without providing key and I still dont feel this is expected behavior. Thankfully a quick work around is forcing the key property of all columns in the table.

**Comment by zombieJ** [comment]
https://ant.design/components/table-cn/#components-table-demo-reset-filter
