### ISSUE TITLE
Table的rowClassName能否支持CSS Module

### ISSUE THREAD

**Issue by guoxunbo** [ant-design/ant-design#19188]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的业务中，大量都已经用了cssModule。但是Table的RawClassName好像不支持。或者说用法不清楚？

### What does the proposed API look like?
> API不变。Demo代码如下：
```js
getRowClassName = (record, index) => {
        const {selectedRows} = this.state;
        if (selectedRows.indexOf(record) >= 0) {
            return 'selected-row';
        } else {
            if(record["status"] == "Doing") {
                return "doing-row";
            }
            if(record["status"] == "Watching") {
                return "watching-row";
            }
            return ''; 
        }
    };
```
> 但是呢，能否换成如下代码类似的。如下是伪代码：
```js
import styles from './QuestionTable.scss';

getRowClassName = (record, index) => {
        const {selectedRows} = this.state;
        if (selectedRows.indexOf(record) >= 0) {
            return {styles.selectedRow};
        } else {
            if(record["status"] == "Doing") {
                return "doing-row";
            }
            if(record["status"] == "Watching") {
                return "watching-row";
            }
            return ''; 
        }
    };
```

**Comment by afc163** [comment]
```diff
-             return {styles.selectedRow};
+            return styles.selectedRow;
```

**Comment by guoxunbo** [comment]
这种这么写，CSS没起效果。如下图：
doingRow已经写了，但是没有效果呈现。
![image](https://user-images.githubusercontent.com/14329149/67174834-2b91f180-f3f6-11e9-8f50-e7108a3a9841.png)
![image](https://user-images.githubusercontent.com/14329149/67174836-2f257880-f3f6-11e9-8976-9cbdc9e852fb.png)

**Comment by guoxunbo** [comment]
@afc163

**Comment by yoyo837** [comment]
props里传进去的css module, 不是全局的

**Comment by guoxunbo** [comment]
@yoyo837 不是全局的？没搞懂这个意思。
因为不同的Table有不同的rowClassName。需要一下子都定义到全局里面？而不能个别引用？比如这样：
![image](https://user-images.githubusercontent.com/14329149/67175049-1f5a6400-f3f7-11e9-83a6-41935b198e51.png)

**Comment by yoyo837** [comment]
你自己在用全局的，你得从styles上使用`styles.xxx` 才是css module

**Comment by yoyo837** [comment]
提供在线demo吧，讲不清的话。

**Comment by guoxunbo** [comment]
@yoyo837 可以了。多谢。忘记Cssmodule的规范了。要xx.module.scss这种命名了。多谢多谢。
