### ISSUE TITLE
ConfigProvider在ie11下会报错

### ISSUE THREAD

**Issue by smallchicken** [ant-design/ant-design#19187]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/smallchicken/parcel-ts-react](https://github.com/smallchicken/parcel-ts-react)

### Steps to reproduce
clone项目install依赖后，在ie11下运行就会报错Objects are not valid as a React child (found object with keys {$$typeof, type, key, ref, props, _owner, _store}). If you meant to render a collection of children, use an array instead.

### What is expected?
可以在ie下运行

### What is actually happening?
报错无法运行，去掉ConfigProvider直接用<App>不会报错

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.9.0 |
| System | mac |
| Browser | ie11 |

**Comment by zombieJ** [comment]
https://github.com/facebook/react/issues/8379#issuecomment-264858787
