### ISSUE TITLE
RangePicker设置初始时间范围后，选择日期范围时不能选择

### ISSUE THREAD

**Issue by Sayid1** [ant-design/ant-design#19186]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-hypatia-bq1s2)

### Steps to reproduce
背景：我设置了一个初始时间范围
此时不能选择日期范围

### What is expected?
可以选择起始日期和结束日期

### What is actually happening?
选择结束日期时，直接重新回到了第一次设置的日期范围

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.8 |
| System | macOS |
| Browser | Chrome |

**Comment by yoyo837** [comment]
受控模式通过onchange 处理

**Comment by yoyo837** [comment]
https://codesandbox.io/s/dazzling-monad-t0rq2

**Comment by Sayid1** [comment]
@yoyo837 但是我想点击确定的时候再改变日期范围，而不是点击结束日期的时候就改变；

比如我选择起止日期后，我点击其它地方关闭了日期面板，这时候我应该还是之前选择的日期范围

**Comment by yoyo837** [comment]
@Sayid1 不使用“确定”能不能满足你需求？

![image](https://user-images.githubusercontent.com/6134547/66694362-1f66af80-ece5-11e9-9869-41bfda2e39c8.png)

**Comment by Sayid1** [comment]
@yoyo837 但是要显示时分秒

**Comment by yoyo837** [comment]
组合使用Form吧。
