### ISSUE TITLE
checkbox 自定义样式的问题

### ISSUE THREAD

**Issue by xfcf1** [ant-design/ant-design#1918]
能否把多个checkbox渲染方式跟radio一样，就是自己来循环group里面的checkbox而不是用options这个属性？

checkbox在表单里面都是 用checkbox.group 包住 用 options 来渲染的，结果就是options里面的{ label }这一项就只能是 字符串了？**如果我想在每个checkbox的标题下面加上一个图片要怎么做？**

**Comment by ddcat1115** [comment]
label 的类型可以是或 `String` 或 `React.Element`

**Comment by xfcf1** [comment]
谢谢@ddcat1115
