### ISSUE TITLE
antd官网打开太过卡顿，官网有时候都打不开，影响效率

### ISSUE THREAD

**Issue by xiwadai** [ant-design/ant-design#19191]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

![image](https://user-images.githubusercontent.com/24467843/66698707-d6c5eb00-ed12-11e9-9945-ce40fb00ace8.png)

**Comment by xiwadai** [comment]
Ant Design: http://ant-design.gitee.io国内镜像挂了

**Comment by ferried** [comment]
> Ant Design 系列官网由于某些众所周知的原因无法访问，建议翻墙或访问国内镜像站点。
> ## 官网
> 
>     * Ant Design: https://ant.design
> 
>     * Ant Design Pro: https://pro.ant.design
> 
>     * Ant Design Pro Preview : https://preview.pro.ant.design
> 
>     * Ant Design Mobile: https://mobile.ant.design
> 
>     * Ant Motion: https://motion.ant.design
> 
> 
> ## 国内镜像
> 
>     * Ant Design: http://ant-design.gitee.io
> 
>     * Ant Design Pro: http://ant-design-pro.gitee.io
> 
>     * Ant Design Mobile: http://antd-mobile.gitee.io
> 
>     * Ant Motion: http://ant-motion.gitee.io
> 
>     * Ant Design Pro Preview : https://prosite.z23.web.core.windows.net
> 
> 
> ![image](https://user-images.githubusercontent.com/24467843/66698707-d6c5eb00-ed12-11e9-9945-ce40fb00ace8.png)

现在国内镜像也挂了。。。

**Comment by yoyo837** [comment]
https://ant-design.gitee.io/ 可以访问哒。

**Comment by webCoderJ** [comment]
怎么这么卡啊 我心态崩了....

**Comment by SpiritQAQ** [comment]
国内镜像也总是等待响应...

**Comment by xrkffgg** [comment]
ant-design 国内镜像地址：https://github.com/ant-design/ant-design/issues/25661

**Comment by baozoudashijian** [comment]
这个官网我是服了 一直转圈圈

**Comment by xrkffgg** [comment]
@baozoudashijian https://github.com/ant-design/ant-design/issues/25661

**Comment by wangchuang168** [comment]
这么大家大业的，国外搞这么牛逼  国内的卡的一逼 也是佩服

**Comment by zhanls** [comment]
我也是来转了一圈才知道要用那个“国内镜像”，百度出来的官网打开慢的要死、服了

**Comment by yanlijun** [comment]
主要服务于国外，国内市场太小了呗 [抠鼻]
