### ISSUE TITLE
antd.js怎么在页面直接引入使用？

### ISSUE THREAD

**Issue by zhaoqize** [ant-design/ant-design#1919]
../build/react.js
../build/react-dom.js
../build/browser.min.js
../build/antd.js
../build/antd.css

页面中这么引入了antd.js文件，但是浏览器一直报错：
>antd is not defined

应该怎么正确使用？
且谷歌不支持ES6？

**Comment by afc163** [comment]
http://ant.design/#/docs/react/install?scrollTo=%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5

另外 http://codepen.io/anon/pen/wGOWGW?editors=001 的例子就是直接引入的。
