### ISSUE TITLE
页面引入两个Form，一个在底层，一个在Modal弹出层，若两个Form中Form.Item的id一致，在弹出层鼠标移入表单某一项的label时，选中了底层的输入框

### ISSUE THREAD

**Issue by ZhangXY-Magic** [ant-design/ant-design#19190]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/antd-reproduction-template-v81dh

### Steps to reproduce
定义两个Form组件，一个为主页面表格筛选表单，一个为弹出层新增记录表单，两个Form中都有同样的Item id为userName的输入项，当鼠标移入弹出层Modal的userName域的label时，默认选中了底部的Form的input域
![QQ截图20191012161954](https://user-images.githubusercontent.com/25630228/66698227-a2503000-ed0e-11e9-9fe2-b2654730a9d0.png)
![QQ截图20191012162047](https://user-images.githubusercontent.com/25630228/66698233-a8461100-ed0e-11e9-91f4-caa8389bc8f6.png)
![QQ截图20191012161709](https://user-images.githubusercontent.com/25630228/66698251-cf044780-ed0e-11e9-857c-8023c1eacad0.png)
![QQ截图20191012161322](https://user-images.githubusercontent.com/25630228/66698252-d0ce0b00-ed0e-11e9-8c7d-d55b84c7b299.png)

### What is expected?
可以正常选中希望选中的元素

### What is actually happening?
错误的选中了先挂载的form中的input框

| Environment | Info |
|---|---|
| antd | 3.21.0 |
| React | 16.7.0 |
| System | windows10 |
| Browser | chrome版本 77.0.3865.90 |

---
是否需要区分同一个页面不允许引入相同id的formItem，需要具体业务中自己区分

**Comment by ZhangXY-Magic** [comment]
> Hello @ZhangXY-Magic. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @ZhangXY-Magic, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-v81dh

**Comment by yoyo837** [comment]
分别绑定Form, 同一个Form里不能重复字段名。

**Comment by yoyo837** [comment]
不能嵌套Form; 另外，相对简单的表单，比如你Modal里面只有一个项的，可以手动处理错误和校验，就不用那么麻烦分别From.create了。

**Comment by ZhangXY-Magic** [comment]
> 不能嵌套Form; 另外，相对简单的表单，比如你Modal里面只有一个项的，可以手动处理错误和校验，就不用那么麻烦分别From.create了。

首先 为了方便提交demo 我简单的复用了下Form，其次现在新的demo没有复用Form，而且为了方便我只写了两个表单项，我觉得项目中一个页面有展示记录列表的筛选项和记录的新增Modal很正常，而且后台接口设计肯定是都有userName这一项，这样一个需要业务设置不同的FormItem的id我觉得不太人性化，希望能认真看下我的问题谢谢。
PS：新的demo还是https://codesandbox.io/s/antd-reproduction-template-v81dh

**Comment by yoyo837** [comment]
还是那个问题啊，Form.create对应一个Form, 同一个Form里不要重复name, 没有人不允许你新增Modal。

**Comment by ZhangXY-Magic** [comment]
> 还是那个问题啊，Form.create对应一个Form, 同一个Form里不要重复name, 没有人不允许你新增Modal。

没搞懂，两个Form.create()创建的是同一个Form么？

**Comment by yoyo837** [comment]
包装一下你前面这个Form引出的第二个Modal里使用的Form使用的`form: { getFieldDecorator }` 也`Form.create()`一下即可。
意思就是`Form.create()` 得到一个`form` 实例，它的`getFieldDecorator` 数据存储到一起的，name自然必须唯一。如果分别通过`Form.create()` 得到不同的`form` 实例，两个之间就互不干扰了。

**Comment by ZhangXY-Magic** [comment]
我新上传的demo两个form是分别通过两个form.create()创建的





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by yoyo837** [comment]
@ZhangXY-Magic 表单项的label使用的是
```html
<label for="id">lable</lable>`
```
的方式，`for`的`id`必须唯一，你还是尽量换个名字，提交时更名吧！
