### ISSUE TITLE
1140无槽宽的栅格太弱，建议增加槽宽20，整体可视宽度至1180

### ISSUE THREAD

**Issue by Erwin11** [ant-design/ant-design#192]
layout的栅格系统,为什么col的padding:5px 0呢？左右边距为0，一行多列不是会没有槽宽？ 是考虑到具体网页布局，间隔可以自己写，写死在框架里实用性不高吗？现在1140 太窄，col槽宽设为20，row共1200，显示面积1180不是更好，模块间的槽宽都不用设置，3列4列的宽度都是整数多好！太弱了这栅格！

**Comment by pizn** [comment]
Hi，
1. col 的样式仅在 DEMO 中演示加的样式，实际使用之中，我们倾向于 padding: 0 0 这样的用法。
2. 如你所说，我们的间隔是可以通过 less 配置的。
3. 不要被 DEMO 给误导，栅格都是差不多这样的。呵呵~

**Comment by Erwin11** [comment]
@pizn  用padding的话，槽宽要计算， 多列div用margin-left做槽宽，然后外面的div负值一个margin-left抵充偏移比较简单维护起来是不是？
