### ISSUE TITLE
Will ant-design support mathematical formula?

### ISSUE THREAD

**Issue by luneice** [ant-design/ant-design#19200]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Ant-design components are awesome, but there is no component for mathematical formula, because academy fields use ant-design also and other solutions to fix ant-design are not good.

### What does the proposed API look like?
it would be better that ant-design support LaTex standards.

**Comment by afc163** [comment]
https://github.com/talyssonoc/react-katex you can try on
