### ISSUE TITLE
Modal 修改了body的overflow属性却没有恢复回来

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#19204]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/xxxZeab?&editable=true&editors=001](https://codepen.io/mraiguo/pen/xxxZeab?&editable=true&editors=001)

### Steps to reproduce
1. 设置body的overflow-y: hidden;
![image](https://user-images.githubusercontent.com/22299421/66728233-38529a80-ee76-11e9-90d2-be920d269a4d.png)

1. 点击打开modal;
1. 点击关闭modal

### What is expected?
关闭modal后body上最开始设置的overflow-y: hidden;恢复回来

### What is actually happening?
body上overflow-y: hidden被清除了

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | react16 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
如果你在 React 中直接设置了 DOM 属性，那也应该自行维护 DOM 样式。监听一下 `afterClose` 事件重置一下 DOM 样式。

**Comment by mraiguo** [comment]
@zombieJ 我觉得不合理吧，示例中用js设置DOM属性就是做个demo。如果我在样式表中设置了overflow属性，Modal组件去修改了DOM属性却需要我去做另外的属性维护？

**Comment by zombieJ** [comment]
cc @jljsj33

**Comment by jljsj33** [comment]
建议 css 上设置呗，，modal之类的会对 body 的 style 进行强行处理。。
```jsx
body {
  overflow-y: hidden；
}
```

**Comment by mraiguo** [comment]
@jljsj33 我意思是Modal可以在设置body的style的时候记住当时的属性，close的时候恢复一下。现在这样不就相当于管杀不管埋嘛

**Comment by jljsj33** [comment]
哈哈哈，，对，没错，，就是管杀不管埋，，，你可以 pr 来搞搞？？
