### ISSUE TITLE
当用antd 的 upload组件上传一个wps创建的docx文件时，返回的文件类型的type是个空字符串，但是当本地用office创建的docx文件，返回的文件类型是正确的，即application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

### ISSUE THREAD

**Issue by smallwebbird** [ant-design/ant-design#19211]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
用wps和office创建docx文件，然后用upload组件上传，就会发现type类型一个为空，一个是正确的值

### What is expected?
wps文件创建的docx，返回的type正确

### What is actually happening?
wps文件创建的docx，返回的type为空

| Environment | Info |
|---|---|
| antd | 3.8.4 |
| React | 16.2 |
| System | window 10 |
| Browser | 谷歌浏览器 |

---
网址书写错误，是因为是公司的运营后台，涉及机密，所以不方便提供
当用antd 的 upload组件上传一个wps创建的docx文件时，返回的文件类型的type是个空字符串，但是当本地用office创建的docx文件，返回的文件类型是正确的，即application/vnd.openxmlformats-officedocument.spreadsheetml.sheet， 在antd的官网上用upload组件测试也出现该问题

**Comment by smallwebbird** [comment]
antd的版本是3.8.4，上文的是错误的

**Comment by yoyo837** [comment]
分别贴俩附件上来吧，不然还得去找文件或者下载wps/office

**Comment by smallwebbird** [comment]
ok刚才用了不同版本的office测试，upload组件对于office创建的docx文件，type类型也是空字符串

**Comment by smallwebbird** [comment]
[new-user.docx](https://github.com/ant-design/ant-design/files/3723683/new-user.docx)

**Comment by smallwebbird** [comment]
已经上传了

**Comment by smallwebbird** [comment]
![image](https://user-images.githubusercontent.com/28871189/66740006-a44bf780-eea4-11e9-9893-5fed9517b4fa.png)

**Comment by zombieJ** [comment]
MAC 上看有的，都弄个 WIN 10 看看：
<img width="605" alt="截屏2019-10-14下午5 20 31" src="https://user-images.githubusercontent.com/5378891/66740949-f0983700-eea6-11e9-96b5-abfa794ecc23.png">

**Comment by smallwebbird** [comment]
我也拿mac试一下

**Comment by smallwebbird** [comment]
好的多谢了

**Comment by smallwebbird** [comment]
win 10 上面有的也好用，我刚才拿另一台win 10 但是他上面装的是office版本，然后用他的电脑上传是有type类型的

**Comment by yoyo837** [comment]
@zombieJ 他这个文件，我这边一台win 10一台Mac，都有。

**Comment by shaodahong** [comment]
@smallwebbird 建议用普通的 `input` 标签试下获取到的 `type` 是不是有，先区分是组件的问题还是系统的问题

**Comment by smallwebbird** [comment]
可能真的跟系统有关，我用input获取的这个文件类型也为空，如下
![image](https://user-images.githubusercontent.com/28871189/66742687-cea0b380-eeaa-11e9-97e1-d8453dd5062e.png)
我这边好几个都有这个问题，麻烦你们了

**Comment by zombieJ** [comment]
antd 用的原生方法，如果原生也是空的。那我们这边做不了什么。

**Comment by afc163** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/File/type

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/66791666-bcb12600-ef27-11e9-986a-a56cbd5231f2.png)

没有问题，edge 和 chrome 都可以拿到，你是不是加了文件保护什么的

**Comment by Shhuy** [comment]
> 可能真的跟系统有关，我用input获取的这个文件类型也为空，如下 ![image](https://user-images.githubusercontent.com/28871189/66742687-cea0b380-eeaa-11e9-97e1-d8453dd5062e.png) 我这边好几个都有这个问题，麻烦你们了

之前也好好像遇到过，当时排查好像是新的系统没有装office并且没有装wps（至于是否有装wps这个不太确定了）然后是获取不到的type，搜索其他的资料有以下描述：
首先，Chrome会检测一个硬编码列表（不能被覆盖）源码中的kPrimaryMappings，然后如果没有找到符合的，Chrome会从操作系统注册表中找，最后会扫描一个二级硬编码列表，源码中的kSecondaryMappings，用来捕获可以推断但是也希望允许操作系统覆盖的类型。
例如：从安装了Microsoft Excel的Windows系统上传CSV文件时，Chrome会将其报告为application/vnd.ms-excel。这是因为.csv未在第一个硬编码列表中指定，因此浏览器会回退到系统注册表。HKEY_CLASSES_ROOT\.csv有一个名为的值Content Type设置为application/vnd.ms-excel。
