### ISSUE TITLE
Tooltip 依赖的 rc-trigger问题

### ISSUE THREAD

**Issue by azl397985856** [ant-design/ant-design#1921]
之前提了一个issue， 你们给关了。我不能reopen。https://github.com/ant-design/ant-design/issues/1871
其实还是有问题的、
以下是你门rc-trigger源码：
componentWillUnmount: function componentWillUnmount() {
var popupContainer = this.popupContainer;
if (popupContainer) {
_reactDom2['default'].unmountComponentAtNode(popupContainer);
if (this.props.getPopupContainer) {
var mountNode = this.props.getPopupContainer();
// 这一步没有加判断。如果我的mountNode被我移除了，比如display：none 程序就会报错
mountNode.removeChild(popupContainer); 
} else {
document.body.removeChild(popupContainer);
}
this.popupContainer = null;
}
if (this.delayTimer) {
clearTimeout(this.delayTimer);
this.delayTimer = null;
}
if (this.clickOutsideHandler) {
this.clickOutsideHandler.remove();
this.touchOutsideHandler.remove();
this.clickOutsideHandler = null;
this.touchOutsideHandler = null;
}
},

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by azl397985856** [comment]
我看你们1.0版本之后依赖的rc-trigger‘  修复了这个问题
谢谢~

**Comment by afc163** [comment]
:+1:
