### ISSUE TITLE
Tree 组件 defaultExpandAll 与 loadData 同时存在时，怎么屏蔽默认的 loadData 事件？

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design#19212]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-field-rvopr?fontsize=14)

### Steps to reproduce
设置展开全部节点，直接就执行 loadData

### What is expected?
正常展开节点，不执行 loadData

### What is actually happening?
默认执行了 loadData

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.9.0 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
`loadedKeys` 控制加载。

**Comment by Benpaodejiezai** [comment]
> `loadedKeys` 控制加载。

使用 loadedKeys 控制，节点就不能 loadData  我希望的是，节点依旧可以 loadData ，但不是在初始化的时候，而是在我点击它的时候

**Comment by yoyo837** [comment]
那你根节点呢？一开始留白？

**Comment by zombieJ** [comment]
点击的时候从 `loadedKeys` 去掉你要加载的 `key`
