### ISSUE TITLE
onCalendarChange prop on RangePicker does nothing

### ISSUE THREAD

**Issue by renatoruk** [ant-design/ant-design#19214]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-28fnd)

### Steps to reproduce
1. Open range picker (click)
2. Change visible range in any way (previous/next month or previous/next year on start or end date)

### What is expected?
 The onCalendarChange callback should execute on visible range change with range logged to console

### What is actually happening?
Nothing happens (no callback execution)

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.9.0 |
| System | OSX 10.14.6. |
| Browser | Chrome 77 |

**Comment by kavience** [comment]
@renatoruk sorry, but I did't find the bug, code running all well.

**Comment by yoyo837** [comment]
As @kavience  said.

![image](https://user-images.githubusercontent.com/6134547/66797162-8500a900-ef3c-11e9-8b50-8305b8a9afdd.png)

**Comment by renatoruk** [comment]
Hey guys, I've recorded a [video with reproduction steps].(https://www.youtube.com/watch?v=JxRB1viAXWM)

Maybe this behavior I'm trying to achieve is not possible. Is that function only triggering after the range in calendar popup is changed with a click on a specific date?

**Comment by yoyo837** [comment]
I watched your video and I didn't figure out what happened to the calendar selection area at the beginning of the video.

**Comment by renatoruk** [comment]
here's a new video. https://www.youtube.com/watch?v=2zOphZ62MFg

I just click on the input to open the calendar popup

**Comment by yoyo837** [comment]
It' s the expected behavior. You didn't make some select.

**Comment by renatoruk** [comment]
I see. I thought it will trigger the change even on visible range change. Thanks for the clarification!
