### ISSUE TITLE
Our intended mouse click and cursor position is different  in antd input  type='Number'

### ISSUE THREAD

**Issue by SojinAntony** [ant-design/ant-design#19210]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-elgamal-kdqgy)

### Steps to reproduce
the cursor should come to the position where I am clicking on the Input

### What is expected?
setup a normal Antd input and set pass props type='Number' and type some numbers in the input box using the keyboard and now click on somewhere in the input box. if click at 2nd or 3rd number cursor points to some other places.  cant focus to a position where I want to be

### What is actually happening?
Cant focus to a position where I want to be

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.8 |
| System | all |
| Browser | All browser |

**Comment by yoyo837** [comment]
Some about `SelectionRange`. 🤔

**Comment by zombieJ** [comment]
Hmmm. Seems chrome bug: https://codesandbox.io/s/floral-field-qvukg

**Comment by kavience** [comment]
@zombieJ  No, I just try it into ant-design source, this is only occur in component Intput instead input, I'm trying to solve it~

**Comment by zombieJ** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1014033&q=input%20number%20cursor&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by kavience** [comment]
ok, i have tried it, it's occur in chrome but not safari, and it's due to style height and panding, if you close height and panding the bug will disappear.

**Comment by SojinAntony** [comment]
This is working fine with normal input. I think the issue is clearly with antd input.
It is working fine when I remove the class  "ant-input"  using chrome dev tools(Elements).
