### ISSUE TITLE
Typography.Paragraph 截取行数显示不正确

### ISSUE THREAD

**Issue by shijunwen** [ant-design/ant-design#19219]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-ives-qjb65)

### Steps to reproduce
访问官网https://ant.design/components/typography-cn/#components-typography-demo-ellipsis

### What is expected?
ellipsis={{ rows: 3, expandable: true }} 设置属性是3行，浏览器显示3行

### What is actually happening?
ellipsis={{ rows: 3, expandable: true }} 设置属性是3行，浏览器显示4行

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | react 16.10.02 |
| System | windows 10 |
| Browser | Google Chrome  版本 77.0.3865.90（正式版本） （32 位） |

---
当浏览器放大，缩小到一定的分辨率时也会导致行数显示错误

**Comment by shijunwen** [comment]
![image](https://user-images.githubusercontent.com/33819581/66807958-cbfe9680-ef5c-11e9-8bce-a4d80f3c5e41.png)

**Comment by zombieJ** [comment]
我这里无法复现，能截个 gif 缩放看一下吗？

**Comment by shijunwen** [comment]
![typography](https://user-images.githubusercontent.com/33819581/66879488-db2f2400-eff0-11e9-873a-00f0d037a24d.gif)

**Comment by shijunwen** [comment]
![image](https://user-images.githubusercontent.com/33819581/66879514-f4d06b80-eff0-11e9-9172-277d111634de.png)
我本机分辨率如上图，官网显示的示例ellipsis={{ rows: 3, expandable: true }} 显示如下图
![image](https://user-images.githubusercontent.com/33819581/66879586-5690d580-eff1-11e9-8cc8-4332f30bffd3.png)

**Comment by zombieJ** [comment]
缩放产生的精度问题 😣

**Comment by WangJM001** [comment]
typography/util.tsx这个字符串截取的算法是不是有点问题，当childNodes的第1个node不是text类型且长度超过限制时，就会显示空

**Comment by Lpmvb** [comment]
https://codesandbox.io/s/flamboyant-sammet-rhgrx?file=/src/App.tsx

**Comment by loddit** [comment]
我也遇到了一样的问题， 可以在 https://ant.design/components/typography/ 这里直接复现
（已经在我的 Linux Chroimum 和几个同事的 Mac Chrome 复现 ，但是需要浏览器不同的缩放级别）

![image](https://user-images.githubusercontent.com/394562/113830944-ad780500-97b9-11eb-8a03-19937076f742.png)

看起来问题在于 https://github.com/ant-design/ant-design/blob/master/components/typography/util.tsx#L76
maxHeight 的计算，这样可以保证高度是足以渲染 rows 里定义的函数，但是这样计算很危险，和可能让也高度足以装下 rows + 1 行的内容。

**Comment by afc163** [comment]
Reproduce: https://codesandbox.io/s/jibenyongfa-antd4168-forked-hnye0?file=/index.js
