### ISSUE TITLE
Typography.Paragraph 字符切割失效

### ISSUE THREAD

**Issue by shijunwen** [ant-design/ant-design#19218]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-curie-qgwvg)

### Steps to reproduce
当字符串为纯数字、纯字母、数字字母混合时，设置rows失效

### What is expected?
rows设置后能正确截取字符串

### What is actually happening?
rows设置无效

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | react 16.10.02 |
| System | windows 10 |
| Browser | Google Chrome  版本 77.0.3865.90（正式版本） （32 位） |

**Comment by zombieJ** [comment]
带拓展按钮的省略是通过 DOM 渲染计算出来的，和原生的 ellipsis 不太一样。需要设置长文字断行：https://codesandbox.io/s/eager-lichterman-ep7k9

感觉可以加个 FAQ 提示一下。

**Comment by afc163** [comment]
wordBreak 默认加上？
