### ISSUE TITLE
关于动态路由，怎么自己定义一串数据去显示，而不是走config.js里面的路由数据呢

### ISSUE THREAD

**Issue by Sakkkkki** [ant-design/ant-design#19220]
根据官方文档修改BasicLayout.jsx下的menuDataRender，自己写了一个死的路由数据，但是只显示了父级菜单，子级菜单没有显示，下面是自己在BasicLayout.jsx写的死数据，并且随便定义变量，最终都是走的config.js 的数据，这是走的哪里的方法呢

const testMenuRoutes = [
  {
    path: '/form',
    icon: 'form',
    name: 'form',
    routes: [
      {
        name: 'basic-form',
        path: '/form/basic-form',
        component: './form/basic-form',
      },
      {
        name: 'step-form',
        path: '/form/step-form',
        component: './form/step-form',
      },
      {
        name: 'advanced-form',
        path: '/form/advanced-form',
        component: './form/advanced-form',
      },
    ],
  },
]
const menuDataRender = testMenuroutes =>
testMenuroutes.map(item => {
    const localItem = { ...item, children: item.children ? menuDataRender(item.children) : [] };
    return Authorized.check(item.authority, localItem, null);
  });

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design-pro
