### ISSUE TITLE
我用antd做了一个嵌套表格，如何设置一个按钮全部展开和全部收缩呢？

### ISSUE THREAD

**Issue by fenghuolibie** [ant-design/ant-design#19225]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by fenghuolibie** [comment]
@jhsu

**Comment by wang-jiji** [comment]
可以使用expandedRowKeys控制
https://blog.csdn.net/Web_J/article/details/124017298?spm=1001.2014.3001.5501
