### ISSUE TITLE
ant Carousel goTo Function not found

### ISSUE THREAD

**Issue by wmtjaychhatrola** [ant-design/ant-design#19223]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel/](https://ant.design/components/carousel/)

### Steps to reproduce
I'm facing problem to using goTo function of Carousel.

 componentDidMount() {
   const { imageIndex } = this.props;
   this.carousel.goTo(imageIndex);
 }

it gives an error : `TypeError: this.carousel.goTo is not a function

### What is expected?
I Want To call Specific index call from component did mount for display image. 

### What is actually happening?
Can't Call Method goTo 

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.0.0 |
| System | Linux |
| Browser | 75.0.3770.100 (Official Build) (64-bit) |

---
Please Help me to resolve this issue

**Comment by wmtjaychhatrola** [comment]
https://codesandbox.io/s/wonderful-fast-1vbyi

**Comment by afc163** [comment]
https://codesandbox.io/s/nifty-dew-xe2jr

**Comment by wmtjaychhatrola** [comment]
Thanks :+1:
