### ISSUE TITLE
How to control width of rowSelection checkbox column?

### ISSUE THREAD

**Issue by aihornmac** [ant-design/ant-design#1922]
I wonder if there is official way to control the width of rowSelection checkbox column. since other columns are given fixed width, it makes checkbox column exceptionally wide.

Thank you!

**Comment by RaoHai** [comment]
Currently not.

but you can override css :

```css
.ant-table th.ant-table-selection-column
```

to modify the width of selection column.

**Comment by afc163** [comment]
:+1:
