### ISSUE TITLE
Antd is vulnerable to code injection

### ISSUE THREAD

**Issue by jimmy-e** [ant-design/ant-design#19234]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Antd says [here](https://ant.design/docs/react/customize-theme) that inline javascript should be enabled in less with the `javascriptEnabled: true` option. However, this option has been deprecated for Less as of version 3.0.0 due to security concerns as it is vulnerable to code injection, which is mentioned [here](http://lesscss.org/usage/) (search for "Enable Inline JavaScript (Deprecated)") and [here](https://stackoverflow.com/questions/58343406/how-to-replace-the-deprecated-javascriptenabled-option-in-less-loader-with-a-new). 

Trying to fix this problem with Ant seems impractical as we will likely need to create a new plugin for every new inline javascript function used in less, and it is unclear how many instances there are and how complex that is.

Is there any horizon for Ant to resolve this issue or possible work arounds?

### What does the proposed API look like?
inline javascript should probably be removed from less stylesheets.

**Comment by jimmy-e** [comment]
Why was this issue closed?

**Comment by yoyo837** [comment]
It is not closed.

**Comment by Airkro** [comment]
+1

`\node_modules\antd\es\style\color\bezierEasing.less`

**Comment by channprj** [comment]
I agree with this issue. We can use `@plugin` instead.

- [lesscss.org - Enable Inline JavaScript (Deprecated)](http://lesscss.org/usage/#less-options-enable-inline-javascript-deprecated-)
- [lesscss.org - @plugin](http://lesscss.org/features/#plugin-atrules-feature)

**Comment by alex-albericio** [comment]
less-loader 6.0.0 has been released and it complains that javascriptEnabled is not a valid option anymore. So, I' think this is a must now.

**Comment by afc163** [comment]
@alex-albericio 

#23603
#23596

**Comment by alex-albericio** [comment]
> @alex-albericio
> 
> #23603
> #23596

Thanks @afc163 . I had not paid attention to the new "lessOptions" property.

**Comment by afc163** [comment]
#23624

**Comment by Airkro** [comment]
I hope the team can remove `TinyColor` too because it messes up my source map.

**Comment by kajan-bolt** [comment]
Any updates on this? Are you planning to support this in the future?

**Comment by afc163** [comment]
same issue with #11097 and potential solution https://github.com/ant-design/ant-design/pull/20470
