### ISSUE TITLE
mentions异步加载输入中文问题

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#19235]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/mentions-cn/#components-mentions-demo-async](https://ant.design/components/mentions-cn/#components-mentions-demo-async)

### Steps to reproduce
1.中文状态下进入文档异步加载demo进行输入

2.首先输入@

3.输入查询字符串，点击enter

### What is expected?
和正常结果一样，进行异步加载数据

### What is actually happening?
在进入loading状态后返回暂无数据

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | x |
| System | win10 |
| Browser | chrome 77 |

**Comment by shaodahong** [comment]
输入的什么字符，是不是没有匹配的？

**Comment by zkwolf** [comment]
@shaodahong 那肯定不是啊。。你可以自己试试，这个demo是访问github api搜用户的，很难无结果的，等下我给你个gif复现吧

**Comment by shaodahong** [comment]
控制台的 network 也看下，我这边是正常的

**Comment by zkwolf** [comment]
唔，发现数据加载真的有可能是我网络问题，或者api限制，英文输入@展示notFoundContent,中文输入@不展示有解决办法吗

**Comment by shaodahong** [comment]
https://github.com/react-component/mentions/blob/c5cca9c269c7752266864c16bd609eb8ef78df48/src/Mentions.tsx#L294 这里触发了默认的 filter function

**Comment by zkwolf** [comment]
这么fix不会导致其他demo没法进入defaultFilterOption进行过滤吗

**Comment by shaodahong** [comment]
@zombieJ 这个默认的情况下不应该 filter 吧，filter 按理说应该是用户来控制

**Comment by zombieJ** [comment]
默认就要 filter:
![Kapture 2019-10-16 at 16 37 49](https://user-images.githubusercontent.com/5378891/66902496-54e80180-f033-11e9-909a-af6adc9b3e72.gif)

**Comment by zombieJ** [comment]
@zkwolf ，
应该是 github 把你拦住了，它对 IP 有访问数量限制。所以看起来像是没有数据一样。组件本身没问题。

> 英文输入@展示notFoundContent,中文输入@不展示有解决办法吗

可以通过 `validateSearch` 来决定是否触发提示

**Comment by shaodahong** [comment]
是默认的 filter `value.toLowerCase().indexOf(lowerCase) !== -1;` 匹配字符，支持不了你输入 `大`，返回 `da | da12 | da123` 这种
