### ISSUE TITLE
日历组件切换月份时不希望有默认选中的日期

### ISSUE THREAD

**Issue by yomonah** [ant-design/ant-design#19237]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有应用场景：用户通过日历表查看某天行程，是需要点击日期来触发，而不是切换月份时就出现选中日期的

### What does the proposed API look like?
日历表初始化默认显示当天日期，但是切换月份时，会默认高亮切换月份后同一天日期，我不希望有默认高亮的效果

**Comment by yoyo837** [comment]
ref: #19289

**Comment by afc163** [comment]
4.0 中已修复：https://github.com/ant-design/ant-design/issues/21656

**Comment by elaoshi** [comment]
4.4.1 还未修复， 请问要如何才能 **没有** 默认选中的日期？

**Comment by l1shu** [comment]
> 4.0 中已修复：#21656

2022-5-2 依然没有修复
