### ISSUE TITLE
官网Tree控件 可搜索的树筛选demo 算法bug

### ISSUE THREAD

**Issue by ZhaoJianXXXXX** [ant-design/ant-design#19232]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
在可搜索的树demo中

const title = 'anything';

const searchValue= 'n';

const index = item.title.indexOf(searchValue);

const beforeStr = item.title.substr(0, index);

const afterStr = item.title.substr(index   searchValue.length);

const title =
          index > -1 ? (
            <span>
              {beforeStr}
              <span style={{ color: '#f50' }}>{searchValue}</span>
              {afterStr}
            </span>
          ) : (
            <span>{item.title}</span>
          );

对于title的拼接算法有误

### What is expected?
当搜索项中有重复的值的时候 
每一个所筛选的值都应该标红或其他显著标识
比如说搜索输入栏搜索“啊”
那么加入有一个搜索项“啊/啊/啊”中的每个“啊”都应该有所改变

const name = 'anything';

const searchValue= 'n';

const index = item.title.indexOf(searchValue);

let title = <React.Fragment>{ name }</React.Fragment>;
			if(index > -1){
				const otherStringArr = name.split(searchValue); 
				title = <React.Fragment/>;
				for(let i = 0; i < otherStringArr.length; i  ){
					title = (
						<React.Fragment>
							{ title }
							{ otherStringArr[i] }
							{ i < otherStringArr.length - 1 ? <span style={{ color: '#f50' }}>{ searchValue }</span> : null }
						</React.Fragment>
					)
				}
			}

### What is actually happening?
目前只改变了第一个搜索值，使其变为红色，如果title中仍有与searchValue相同的值，并没有处理
比如说搜索输入栏搜索“啊”
那么加入有一个搜索项“啊/啊/啊”中的只有第一个“啊”的颜色有所改变

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 任意版本 |
| System | win10 |
| Browser | 搜狗浏览器 8.6.1.31486 |

**Comment by zombieJ** [comment]
Demo 只是举例，实际业务中按照自己的需求改造即可。

**Comment by afc163** [comment]
也可以来个 PR 帮我们改进 : )
