### ISSUE TITLE
antd table bug: rowSelection config type can't apply

### ISSUE THREAD

**Issue by zhaoPengInGithub** [ant-design/ant-design#19239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://localhost](https://localhost)

### Steps to reproduce
```javascript
const rowSelection = {
      type: "radio",
      selectedRowKeys,
      onChange: this.onSelectChange
}
<Table<TrainingDataColumn> scroll={{y: 290}} bordered={true} rowSelection={rowSelection} columns={this.columns} dataSource={formListData} />
```

### What is expected?
table behavior normal and radio works right，not checkbox

### What is actually happening?
Type '{ type: string; selectedRowKeys: number[]; onChange: (selectedRowKeys: any) => void; }' is not assignable to type 'TableRowSelection<TrainingDataColumn>'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type '"radio" | "checkbox" | undefined'.  TS2322

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.9.0 |
| System | mac OS mojave |
| Browser | chrome newest |

**Comment by afc163** [comment]
```dif
-      type: "radio",
+      type: "radio" as "radio",
```

**Comment by zhaoPengInGithub** [comment]
> ```
> -      type: "radio",
> +      type: "radio" as "radio",
> ```

@afc163 done! but I don't know why
