### ISSUE TITLE
怎么官网突然挂了？

### ISSUE THREAD

**Issue by meibin08** [ant-design/ant-design#19244]
官网怎么突然挂了？？

**Comment by duanzheng** [comment]
有 3 版本的国内镜像吗？现在不 FQ 完全没法用

**Comment by yoyo837** [comment]
右上角有版本切换呀

**Comment by duanzheng** [comment]
> 右上角有版本切换呀

切换后的地址是 3x.ant.design，这个站也是用的 cloudflare，所以也没法正常访问

**Comment by ferried** [comment]
ant design 3.x无法访问

**Comment by wuhao5436** [comment]
真特么慢 加载个js文件47s
![image](https://user-images.githubusercontent.com/21374949/87512496-b401a200-c6a9-11ea-84e7-df6ccb1436ea.png)

**Comment by lulg** [comment]
> Ant Design 系列官网由于某些众所周知的原因无法访问，建议翻墙或访问国内镜像站点。
> 
> ## 官网
> * Ant Design: https://ant.design
> * Ant Design Pro: https://pro.ant.design
> * Ant Design Pro Preview : https://preview.pro.ant.design
> * Ant Design Mobile: https://mobile.ant.design
> * Ant Motion: https://motion.ant.design
> 
> ## 国内镜像
> * Ant Design: http://ant-design.gitee.io
> * Ant Design Pro: http://ant-design-pro.gitee.io
> * Ant Design Mobile: http://antd-mobile.gitee.io
> * Ant Motion: http://ant-motion.gitee.io
> * Ant Design Pro Preview : https://prosite.z23.web.core.windows.net

ant design charts 这个的国内镜像没有吗
