### ISSUE TITLE
select等可以下拉选择框动态修改后缀图标

### ISSUE THREAD

**Issue by songxiao1124** [ant-design/ant-design#19248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在Select中suffixIcon改变后缀图标之后，图标在下拉状态也不会改变的问题。

### What does the proposed API look like?
suffixIconUp 替换下拉状态下的图标，如果不写则和suffixIcon相同

**Comment by afc163** [comment]
建议配合 open 属性自行控制图标展现。
