### ISSUE TITLE
Export the actual Table as well along with the "withStore" HOC

### ISSUE THREAD

**Issue by spideeee** [ant-design/ant-design#19249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We have been using Antd Table a lot in our Web app, however we have overridden the "renderPagination" function of the Table component to not to render pagination if the data is only for a single page. We do not wanted to see the pagination when there is only one page.

```
const renderPagination = Table.prototype.renderPagination;
Table.prototype.renderPagination = function (param, position) {
    if(condition to check for only 1 page){
        return renderPagination.apply(this, arguments);
    }
    return null;
}
```

But after 3.24.0, this stopped working.

### What does the proposed API look like?
`export Table;`
in Table.tsx.

**Comment by afc163** [comment]
Don't use `prototype` to do that, it is not correct way. Please try to create a Upper Table Component for customized needs.

**Comment by spideeee** [comment]
@afc163 , can you please elaborate what do you mean by **Upper Table Component** please?

**Comment by spideeee** [comment]
@pierre-H , we need to export the table as well.
