### ISSUE TITLE
Table has lost type definitions

### ISSUE THREAD

**Issue by DennisBaekgaard** [ant-design/ant-design#19252]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
n/a

### Steps to reproduce
Make any <Table<T>> in typescript.

```
interface MyType {
}

const test = () => {

return (
    <Table<MyType>>
    </Table>
);

}
```

Aditionally static Column was removed from Table.d.ts

### What is expected?
It should be possible to use Table with generic types as written in the documentation.

### What is actually happening?
There are type compilation errors.

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | 16.10.2 |
| System | Windows |
| Browser | Chrome |

**Comment by JoeDevGeeeee** [comment]
ran into the same problem today. Worth noting my typescript version is 3.6.4

**Comment by eapearson** [comment]
Same here, reverting to 3.23.6.
It looks like it has been worked on, perhaps fixed, but is not released it yet:
https://github.com/ant-design/ant-design/commit/7d32f992838d486ae29ba4db2c4d9ed62afce53d

**Comment by lLeahDizon** [comment]
me too, reverting to 3.23.6.

**Comment by yoyo837** [comment]
ref: #18953

**Comment by icslearn** [comment]
`const { Column } = Table;`
The "Column" does not exist in the type "typeof Table".

**Comment by yoyo837** [comment]
Release [3.24.1](https://github.com/ant-design/ant-design/releases/tag/3.24.1)

**Comment by yoyo837** [comment]
If this problem still occurs, please feel free to open a new issue.

**Comment by leshalv** [comment]
> 如果仍然出现此问题，请随时打开一个新问题。
我升级到了最新版本，还是报错
![image](https://user-images.githubusercontent.com/30397655/67255161-53935a80-f4b3-11e9-81d8-391436614e88.png)
我也并没有找到文档描述

**Comment by yoyo837** [comment]
Ref: #19327
