### ISSUE TITLE
IE下表格组件中操作栏中用tooltip的时候表格内容会出现闪动

### ISSUE THREAD

**Issue by ylf123** [ant-design/ant-design#19260]
IE下表格组件中操作栏中用tooltip的时候，鼠标移上去出现提示的时候表格内容会闪动，操作是，直接跨行移动到tooltip上去

**Comment by wzskyline** [comment]
"antd": "^4.0.3"  IE 11 真的是弹出文字后再次快速弹一次 有闪烁的感觉
