### ISSUE TITLE
Convert all Less to SCSS, and provide a choice for styles.

### ISSUE THREAD

**Issue by mucluck** [ant-design/ant-design#19265]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/tree/master/components/style](https://github.com/ant-design/ant-design/tree/master/components/style)

### Steps to reproduce
All styles in Less

### What is expected?
The choice between Less, SCSS, CSS

### What is actually happening?
All styles in Less or CSS

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | 16.10.2 |
| System | macOS Catalina 10.15 |
| Browser | Chrome 77.0.3865.90 |

**Comment by yoyo837** [comment]
This is a so huge job and no support has been considered yet.

**Comment by shaodahong** [comment]
https://ant.design/docs/react/faq#Are-you-going-to-provide-Sass/Stylus(etc)-style-file

**Comment by loia5tqd001** [comment]
Is there a workaround to achieve using (theming as well as accessing less variables) for an scss project?
I've stumbled upon this package but it looks like outdated and doesn't work anymore...
https://intoli.com/blog/antd-scss-theme-plugin/

**Comment by loia5tqd001** [comment]
Is there a workaround to achieve using (theming as well as accessing less variables) for an scss project?
I've stumbled upon this package but it looks like outdated and doesn't work anymore...
https://intoli.com/blog/antd-scss-theme-plugin/

**Comment by LinboLen** [comment]
related #38406
