### ISSUE TITLE
Pagination中的showQuickJumper是怎么用的？

### ISSUE THREAD

**Issue by yuweilan** [ant-design/ant-design#1926]
http://ant.design/#/components/pagination
示例里只提到怎么添加，没有提到怎么使用，这个东西不会只能看看吧

**Comment by afc163** [comment]
参考示例：http://ant.design/#/components/pagination?scrollTo=components-pagination-demo-jump

**Comment by yuweilan** [comment]
快速跳页容器能添加，但是填数字并不能影响分页页数的改变啊，填完跳转的数字能触发onChange事件么？
