### ISSUE TITLE
IE下table组件操作栏用了tooltip 鼠标移上去之后会闪动

### ISSUE THREAD

**Issue by ylf123** [ant-design/ant-design#19261]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/  可编辑单元格里操作的那样](https://ant.design/components/table-cn/  可编辑单元格里操作的那样)

### Steps to reproduce
鼠标移上去

### What is expected?
不会闪动

### What is actually happening?
会闪动

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | 15 |
| System | windows |
| Browser | IE11 |

**Comment by bnuzhengshan** [comment]
我也遇到了这个问题，ie 9、10、11都有

**Comment by afc163** [comment]
Duplicate of #21039

**Comment by ycBi** [comment]
我是table里面的某列的单元格嵌套tooltip，然后mouseenter事件触发tooltip里面又是个table，而且表格的第一二行和最后2行没哈问题，但是中间的会出现外面的table和tooltip里的table都会闪动
