### ISSUE TITLE
通过后端接口返回值渲染Table组件筛选菜单报错

### ISSUE THREAD

**Issue by xiaofeng1991** [ant-design/ant-design#19269]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-head](https://ant.design/components/table-cn/#components-table-demo-head)

### Steps to reproduce
```javascript
@connect(({ users, loading}) => ({
  allRoles: users.allRoles || [],
  loading: loading.models.users,
}))

......

componentDidMount() {
    const { dispatch } = this.props;
    dispatch({
      type: 'users/getRoles',
      payload: {},
    });
  }

......

render() {
  const { allRoles } = this.props;
   const rolesFilters = allRoles.map(role => ({ text: role.name, value: role.name }));
   const tableParams = {
      columns: [
        {
          align: 'center',
          title: '所属角色',
          dataIndex: 'roles',
          width: 80,
          filters: rolesFilters,
        },
     ];
......

  return <Table {...tableParams} />;

}
```

### What is expected?
希望能通过后端接口的返回值渲染筛选菜单

### What is actually happening?
报错 Uncaught TypeError: Cannot read property 'appendChild' of null
The above error occurred in the <Portal> component:

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | 16.8.6 |
| System | windows 10 家庭中文版 1903 18362.418 |
| Browser | 360极速浏览器 11.0.2216.0 |

**Comment by xiaofeng1991** [comment]
我晚点写一个，刚刚看了 https://github.com/ant-design/ant-design/issues/19274#issue-508578005，有可能是相同原因

**Comment by afc163** [comment]
合并到 #19274 讨论跟踪。
