### ISSUE TITLE
3.24.0 table组件添加了一个WithStore，但是文档并没有描述具体意思，然后项目typescript一路错误

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design#19267]
3.24.0 table组件添加了一个WithStore，但是文档并没有描述具体意思，然后项目typescript一路错误
![image](https://user-images.githubusercontent.com/30397655/66992531-91cbfb00-f0fc-11e9-8308-6739af542bd2.png)
![image](https://user-images.githubusercontent.com/30397655/66992630-b9bb5e80-f0fc-11e9-9c2d-06050b3cabf0.png)

**Comment by YaoKaiLun** [comment]
> Duplicate of #19252

No, It doesn't same with #19252.
Before 3.24.0 is
![image](https://user-images.githubusercontent.com/11460856/67058515-ba4d0700-f187-11e9-8636-348bc31af581.png)
And in 3.24.0 , TableProps extends withStore
![image](https://user-images.githubusercontent.com/11460856/67058534-d5b81200-f187-11e9-8d04-b084f2c1788a.png)
So now the tsc reports errors like this
![image](https://user-images.githubusercontent.com/11460856/67058614-2891c980-f188-11e9-90d7-6aa389b1f2a0.png)

**Comment by JounQin** [comment]
+1 For this.

@yoyo837

I have something like 

```ts
export interface ActionsTableProps<T extends Base = Base>
  extends TableProps<T>,
    ActionsContext<T> {
  pagination?: PaginationConfig;
}
```

Now it requires `WithStore` properties, which is definitely unexpected!

![image](https://user-images.githubusercontent.com/8336744/67155125-887ca180-f33b-11e9-9816-623b510e712b.png)
