### ISSUE TITLE
自定义select多选样式 

### ISSUE THREAD

**Issue by Zuojiangtao** [ant-design/ant-design#19263]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义select多选的样式，优化用户体验

### What does the proposed API look like?
可暴露一个字段用于传入自定义模板，类似于:
----
```
selectOption: '<div class="option-checkedbox">'  
        '<ul class="checkedbox-list"></ul>'  
        '</div>', // 更改容器的多选模板;
```

使用方法: 
----
```
<a-select-option :selectOption="selectOption" v-for="(item, index) in developerList" :key="index" :value="item.id">{{ item.name }}</a-select-option>
```

**Comment by Zuojiangtao** [comment]
实现效果图:
----
![image](https://user-images.githubusercontent.com/22252182/66986442-87583400-f0f1-11e9-9f27-813e1114132d.png)

**Comment by yoyo837** [comment]
React 肯定不能玩模版的方式。但是你要定制什么没理解到。

**Comment by Zuojiangtao** [comment]
> React 肯定不能玩模版的方式。但是你要定制什么没理解到。

react是用JSX的方式；就是想自定义多选的样式，就像我图中所示

**Comment by yoyo837** [comment]
@Zuojiangtao 你截图拿颜色圈一下，个人不太明白说的哪里的样式。

**Comment by Zuojiangtao** [comment]
> @Zuojiangtao 你截图拿颜色圈一下，个人不太明白说的哪里的样式。

![image](https://user-images.githubusercontent.com/22252182/66989051-2f6ffc00-f0f6-11e9-98c0-28497a444bca.png)

![image](https://user-images.githubusercontent.com/22252182/66989088-41ea3580-f0f6-11e9-90d1-6130a07b3ff8.png)

原来的多选是在文本后面打对勾，想能够改成checkbox的形式

**Comment by afc163** [comment]
你这是 ant-design-vue 吧，反馈错地方了。

**Comment by Zuojiangtao** [comment]
> 你这是 ant-design-vue 吧，反馈错地方了。

那个也是根据你们的封装实现的，你们都没有这个功能，他们怎么实现呢？只能来这边来反馈一下了

**Comment by yoyo837** [comment]
@Zuojiangtao `dropdownRender`、`dropdownStyle`, `dropdownMenuStyle`, `dropdownClassName` 这几个配合应该能满足你的需要吧
