### ISSUE TITLE
Table的columns属性发生变化时，设置scroll属性，页面报错

### ISSUE THREAD

**Issue by admire7444** [ant-design/ant-design#19274]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-m9qb3)

### Steps to reproduce
please see the page link above
请看重现链接

### What is expected?
show a normal table
显示正常表格

### What is actually happening?
page error, according to the error log, i think the error was that the filterDropdown can not find the mount node
页面报错，根据排查，应该是filterDropdown渲染的节点找不到引起的问题

| Environment | Info |
|---|---|
| antd | 3.24.1 |
| React | 16.9.0 |
| System | windows10 |
| Browser | Chrome 77.0.3865.120 |

---
i run 'yarn upgrade' in 2019.10.16, and i got the error, in the pervious version, every thing is ok
2019.10.16号执行yarn upgrade后，出现该问题，此前版本无该问题

**Comment by yoyo837** [comment]
https://github.com/react-component/trigger/blob/master/src/index.tsx#L518 

`mountNode.appendChild(popupContainer);` 

TypeError: Cannot read property 'appendChild' of null.

**Comment by afc163** [comment]
@zombieJ 应该和 https://github.com/ant-design/ant-design/pull/19205 有关系，我看不动了，你来看一下。

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/18726/files#diff-9e758b938531cabc07bf62e7314948fdR509

这里把 `findDOMNode` 换成了 ref.tableNode 而 tableNode 是空导致的。我看看怎么修。

**Comment by yoyo837** [comment]
https://github.com/react-component/table/pull/379 didn't fix this.
