### ISSUE TITLE
notification and message api doesn't auto hiding itself

### ISSUE THREAD

**Issue by KInGATiLLa** [ant-design/ant-design#19273]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-lsccv)

### Steps to reproduce
message.warn("content", 2000);
it is not closing after duration itself.
And also notification api. I probably wrong doing it?.

### What is expected?
it is not closing after duration itself.

### What is actually happening?
message.warn("content", 2000);
it is not closing after duration itself.
And also notification api. I probably wrong doing it?.

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | 16.10.2 |
| System | Windows 10 64bit |
| Browser | Chrome 77 |

**Comment by yoyo837** [comment]
The unit is seconds instead of milliseconds.

<img width="1191" alt="截屏2019-10-1800 19 22" src="https://user-images.githubusercontent.com/6134547/67027920-03c43480-f13d-11e9-867d-d8721fd099ca.png">
