### ISSUE TITLE
【BUG】Upload 组件行为表现和原生 input file 表现不一致

### ISSUE THREAD

**Issue by silentcloud** [ant-design/ant-design#19288]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2x.ant.design/components/upload/](https://2x.ant.design/components/upload/)

### Steps to reproduce
1. 鼠标点击 Upload 上传按钮
2. 鼠标点击取消按钮
3. 敲击键盘回车
4. 弹出的选文件然后选择一个文件

### What is expected?
敲击回车之后，选择完文件，文件出现在列表，同时弹出框消失

### What is actually happening?
敲击回车之后，第一次弹窗选了文件之后并没有将文件加到列表，同时又弹了一次选文件到窗

| Environment | Info |
|---|---|
| antd | 3.24.1, 2.x |
| React | 15.x，16.x |
| System | mac， windows |
| Browser | ALL |

**Comment by yesmeck** [comment]
![38377B04-1B32-4F28-A9E8-385F01E9EA14](https://user-images.githubusercontent.com/465125/67077646-3f551200-f1c2-11e9-8cd0-3b1798e4cba3.gif)
