### ISSUE TITLE
【强烈建议】关于时间范围组件的UI改进，以提高日期范围中时间选择的效率。

### ISSUE THREAD

**Issue by sguot** [ant-design/ant-design#19289]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://ant.design/components/date-picker-cn/#components-date-picker-demo-time

在使用日期范围组件时，我个人感觉其中对于“时间选择”不够友好，主要有以下几点感受：

1. “选择时间”按钮以文字链接的形式不够直观，是否能更突出？
2. 点击“选择时间”按钮后会打开一个独立的层覆盖在日期选择上，这样就多出了一个操作步骤。能否能消灭多出的步骤？
3. 呼出的“时间选择”层虽然很大，但是整体上与日期的对应上不是很明显，另外时间选择个人感觉也没必要使用这么大的空间，反而感觉空旷。

个人建议，如果能将时间选择与日期选择放在一个层中同时进行，在操作上与体验上会更好，我认为这能达到以下的效果：

1. 解决日期选择与时间选择的操作不连贯问题。
2. 提高日期范围中时间选择的效率。
3. 日期范围选择中日期选择与对应的时间选择更直观。

### What does the proposed API look like?
增加一个参数来控制时间组件的展示风格。
```js
<DatePicker showTime={{style:'inline'}}
```

**Comment by leollllll** [comment]
我也觉得当前时间组件的使用方式不便捷，右下角不明显，而且只是一个时分秒的选择占了整个界面

**Comment by yoyo837** [comment]
Ref: #18545

**Comment by sguot** [comment]
> Ref: #18545

能否考虑基于我给的参考实现呢？

**Comment by yoyo837** [comment]
这个怕是要等设计师先推翻重做一版，大量交互相关。

**Comment by sguot** [comment]
> 这个怕是要等设计师先推翻重做一版，大量交互相关。

好的！感谢您们的反馈，非常希望关于这个在未来的版本中会有所改进。

**Comment by theDoinb** [comment]
是有些难用，现在都是将日期时间拆成两个输入框给用户，因为反馈说有点难用。
感觉element 这种比较容易接受？
https://element.eleme.cn/#/zh-CN/component/datetime-picker#ri-qi-he-shi-jian-fan-wei

**Comment by afc163** [comment]
4.0 已经进行了相关设计升级：https://github.com/ant-design/ant-design/issues/21656
