### ISSUE TITLE
版本0.12.14  tree组件异步加载获取不到展开的key 

### ISSUE THREAD

**Issue by alvin6233** [ant-design/ant-design#1928]
onExpand=(treeNode, expand, expandedKeys) =>{
        debugger;
        console.log('onExpand', treeNode,expand, expandedKeys);
        this.setState({
            expandedKeys
        });
    }

展开节点时 参数expandedKeys 为[]  为什么获取不到它的key

**Comment by warmhug** [comment]
请先确认下 jsx 或 es6 的语法有没写错

**Comment by alvin6233** [comment]
语法没有错误 在展开一个节点时  expandedKeys 为[]  按道理来说应该有至少一个展开的节点才对

**Comment by warmhug** [comment]
麻烦提供下演示demo

**Comment by ddcat1115** [comment]
请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001
