### ISSUE TITLE
Locale tag downloadFile

### ISSUE THREAD

**Issue by DemetriusHR** [ant-design/ant-design#19297]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature is for resolve the tag `downloadFile` of Upload. In the new version `3.24.1`, was added the tag of locale `downloadFile` and not was added in the locales exists in Antd now. 

### What does the proposed API look like?
```js
Upload: {
  ....
  downloadFile: "translate for the languages existents"
}

```

**Comment by afc163** [comment]
Could you help to update it?

**Comment by DemetriusHR** [comment]
@afc163 I can try help, I can open a PR for this?

**Comment by yoyo837** [comment]
@DemetriusHR Of course. Welcome!

**Comment by afc163** [comment]
#19361
