### ISSUE TITLE
Table 设置 rowSelection，点击列表复选框报错无反应

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#19294]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/prod-dawn-ikvrx)

### Steps to reproduce
生成带复选框的表格

### What is expected?
复选框正常工作

### What is actually happening?
复选框不能正常工作

| Environment | Info |
|---|---|
| antd | 3.24.1 |
| React | React 16 |
| System | WIN10 |
| Browser | Chrome 77 |

---
复现链接没问题，估计因为复现链接用的是打包好的代码，用 babel 按需打包的报错！

![table](https://user-images.githubusercontent.com/1730277/67083717-3d914b80-f1ce-11e9-976d-eebb91733d4b.gif)

**Comment by nuintun** [comment]
#18511
#18503
#18502
#15229
#15227
#19293
#13601

**Comment by yoyo837** [comment]
demo 无法复现

**Comment by nuintun** [comment]
@yoyo837 周一我看能不能本地复现个 DEMO 上传到 Github，好几个项目更新完都炸了！

**Comment by nuintun** [comment]
问题关闭，已发现问题，项目同时使用了 antd 和 ant-mobile，而且 antd 和 ant-mobile 都依赖 rc-checkbox，使用 yarn 安装的时候低版本的 rc-checkbox 被装在了 node_modules 根目录，而我在 webpack 中设置了 `modules: [path.resolve('Assets/src'), path.resolve('node_modules')]` 造成 webpack 只从根目录下的 node_modules 读取依赖，打包了错误的版本 :joy:
