### ISSUE TITLE
Upload组件在钉钉内打开浏览器上传，后台获取不到后缀名

### ISSUE THREAD

**Issue by zhang504988670** [ant-design/ant-design#19298]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-water-jugx7)

### Steps to reproduce
在钉钉内打开网址，上传图片后，在上传图片后后台获取不到后缀。

### What is expected?
能正常获取到后缀名。

### What is actually happening?
获取不到后缀名

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.7.0 |
| System | Win10 |
| Browser | 钉钉内自带浏览器 |

**Comment by zhang504988670** [comment]
只在手机钉钉打开的时候无法上传，其他浏览器一切正常。

**Comment by afc163** [comment]
antd 目前没有精力对移动端进行支持，欢迎自行排查然后给我们发 PR。
