### ISSUE TITLE
Upload组件UploadFile类中的url地址 /load.html?f=xxx.jpg 时无法显示图片,只能使用url为/load/xxx.jpg

### ISSUE THREAD

**Issue by yangankang** [ant-design/ant-design#19299]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
-

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.24.1 |
| React | 16.8.6 |
| System | mac 10.15 |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/11684/files
