### ISSUE TITLE
Original text of column.ellipsis would not appear in Chrome

### ISSUE THREAD

**Issue by cheneyxwong** [ant-design/ant-design#19293]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ctob4)

### Steps to reproduce
Hover on the ellipsis.

### What is expected?
The original text of hovered ellipsis would appear.

### What is actually happening?
Works in Safari but not in Chrome.

| Environment | Info |
|---|---|
| antd | 3.24.1 |
| React | 16.9.0 |
| System | macOS 10.15 |
| Browser | Chrome 77.0.3865.120 |

**Comment by afc163** [comment]
Try reinstall `node_modules`.
