### ISSUE TITLE
Menu 默认样式 与react-router之间冲突

### ISSUE THREAD

**Issue by jun880529** [ant-design/ant-design#1929]
``` 场景：
<Menu.Item key="1">
      <Link key="app1" to={`/app/1`}>添加应用</Link>
</Menu.Item>
默认会给menu加一个selected的样式，但是我操作浏览器后退。前进按钮时无法触发选中状态导致显示错误
react－router提供了一个默认触发的active的样式，请问如何取消and menu 默认的选中样式？

**Comment by weishiji** [comment]
constructor(props){
		super(props);
		this.state = {
			current: '1',
			openKeys: ['sub1']
		}
	}
	componentWillUpdate(){
		console.log(this.state,'this is componentWillUpdate')
	}
	render() {
		return (
			<Menu
					mode="inline"
					key="left_menu"
					openKeys={this.state.openKeys}
					selectedKeys={[this.state.current]}
					onOpen={this.onToggle}
					onClose={this.onToggle}
					onClick={this.HandleClick}>
					<SubMenu key="sub1" title={<span><Icon type="user" />应用管理</span>}>
						<Menu.Item key="1">
							<Link key="app1" to={`/app/1`}>添加应用</Link>
						</Menu.Item>
						<Menu.Item key="2">
							<Link key="app2" to={`/app/2`}>启用/关闭</Link>
						</Menu.Item>
						<Menu.Item key="3">
							<Link key="app3" to={`/app/3`}>菜单设置</Link>
						</Menu.Item>
						<Menu.Item key="4">
							<Link key="app4" to={`/app/4`}>权限设置</Link>
						</Menu.Item>
					</SubMenu>
				
				）
			｝

直接在``componentWillUpdate``这个函数中去每次更新这个状态，因为浏览器在回退和前进的时候，都会触发这个函数，这样就可以在不改动ant design的前提下，menu里还可以套用Link

**Comment by codering** [comment]
@weishiji  componentWillUpdate方法里setState会导致死循环的

**Comment by weishiji** [comment]
@codering 有道理，没考虑到，只是做了一个DEMO，打印了一下数据，让你这么一提醒，肯定是会死循环的，那你有什么解决方案吗？

**Comment by codering** [comment]
可以试试 把 Menu.Item的 key 设置成路由的路径， 然后在 componentWillReceiveProps改变状态
```js
    componentWillReceiveProps(nextProps) {
       this.setState({selectedKeys: [nextProps.location.pathname]})
    }
```
