### ISSUE TITLE
官网列出了很多颜色配置的方案，但是我如何在项目中进行修改？

### ISSUE THREAD

**Issue by Tinker404** [ant-design/ant-design#193]
antd文件里只有个index.css文件，要修改如此大量的色彩很复杂，是否有less或者其他的文件？

**Comment by afc163** [comment]
antd 的模板采用全局主色调变量的方式进行扩展，自定义可以参考以下的步骤：

```
git clone git@github.com:ant-design/ant-design.git
cd ant-design
npm install
```

修改 https://github.com/ant-design/ant-design/blob/master/style/themes/default/custom.less 里的主色调 `@primary-color`。

然后在根目录运行：

```
npm run release
```

会在 dist 下打包出包含修改配色方案的新的样式文件。

**Comment by Tinker404** [comment]
Good，npm下的没less，原来在这，已解决

**Comment by doublelduob** [comment]
想请教一下，能否在自己的项目中直接覆盖@primary-color变量的方式来修改呢？
这样修改可以和项目在git中保持一致

**Comment by afc163** [comment]
try `0.10.x`.

In your project's `package.json`:

```json
  "theme": {
    "primary-color": "#f60"
  },
```

**Comment by afc163** [comment]
#384

**Comment by doublelduob** [comment]
非常感谢！我从历史的issue里也找到了，准备来关闭问题，没想到回复这么快，antdesign是个好轮子

**Comment by afc163** [comment]
感谢支持，特别欢迎贡献代码！

**Comment by xuxuepu** [comment]
@afc163 
1、修改style: true后；
2、删除以下webpack配置代码，antd组件的样式正常，但自己写的less样式不正常显示；
3、若留下以下的代码，antd组件的样式不正常，自己写的less样式正常显示。

```
webpackConfig.module.loaders.forEach(function(loader, index) {
    if (typeof loader.test === 'function' && loader.test.toString().indexOf('\\.less$') > -1 ) {
      loader.test = /\.dont\.exist\.file/;
    }
    if (loader.test.toString() === '/\\.module\\.less$/' ) {
      loader.test = /\.less$/;
    }
  });
```

**Comment by afc163** [comment]
https://github.com/ant-design/babel-plugin-antd/issues/26#issuecomment-234964542

@sorrycc

**Comment by zjyfantasy** [comment]
@xuxuepu 问你一下webpackConfig.module.loaders.forEach里webpackConfig怎么引入的，是安装的组件吗

**Comment by xuxuepu** [comment]
@zjyfantasy 用@sorrycc 大神的dva-cli [https://github.com/dvajs/dva-cli]

**Comment by wangguozheng666** [comment]
我想让标签浮动，添加类名设置了根本不起作用，好无语呀，是不是这个框架跟boothstrap差不多呢，有自己内部的可供类名可以设置样式呢，还是……？该怎么样去修改呢

**Comment by WSYProject** [comment]
请问一下，怎么清除antd的input框聚焦后出现的阴影

**Comment by suwu150** [comment]
请问，react-native中使用ant-design-mobile的时候，怎么对样式进行覆盖，比如覆盖 tabs组件的高度
[hight](https://github.com/ant-design/ant-design-mobile/issues/2543)
