### ISSUE TITLE
React does not recognize the `headerStyle` prop on a DOM element.

### ISSUE THREAD

**Issue by fredwin-o** [ant-design/ant-design#19306]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer/](https://ant.design/components/drawer/)

### Steps to reproduce
Attempt to add style to headerStyle.

### What is expected?
Styling is applied accordingly

### What is actually happening?
Warning: React does not recognize the `headerStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `headerstyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.10.2 |
| System | Windows |
| Browser | Chrome Version 77.0.3865.120 |

**Comment by afc163** [comment]
Try upgrade to latest antd version: 3.24.2
