### ISSUE TITLE
字段名是filter[xname]，  getFieldDecorator 总是产生嵌套结构，如何转义 " [ "和 " ] " 符号，

### ISSUE THREAD

**Issue by fubd** [ant-design/ant-design#19315]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
getFieldDecorator 转义符号

### What does the proposed API look like?
filter\[xname\] -> filter[xname]

**Comment by zombieJ** [comment]
v3 版本中不支持转义，需要自己换个字段名。
v4 中支持改写法。
