### ISSUE TITLE
[Select] 多选问题

### ISSUE THREAD

**Issue by 957184448** [ant-design/ant-design#19319]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当我选择全部选项时 其他选项不选择，当我把去其他选项全部勾选时，转换为全部选项

如果设置这样的字段或者字符串时 需要操作原生dom节点来获取‘全部’完成这个需求
需要好多判断与setState 这样每个页面得多选框都需要处理

### What does the proposed API look like?
建议！
可设置一个字符串或字段来完成
例如：当我设置 SelectType 为’全部‘时，
           其他选项不选中
           当我选择其他选项时 '全部'不选中，
           当另外所有选项选中后，
           当前选中项为全部
希望采纳一下这个问题 或者有更好得处理方法
谢谢

**Comment by yoyo837** [comment]
我觉得你只需要基于antd的select再封装一个，然后在自己应用内使用即可。

**Comment by 957184448** [comment]
> 我觉得你只需要基于antd的select再封装一个，然后在自己应用内使用即可。

现在就是这样做的 但是我想是不是大家都有这种需求

**Comment by zombieJ** [comment]
听起来是 TreeSelect？

**Comment by 957184448** [comment]
> 听起来是TreeSelect？

就是Select

**Comment by 957184448** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 当我选择全部选项时 其他选项不选择，当我把去其他选项全部勾选时，转换为全部选项
> 
> 如果设置这样的字段或者字符串时 需要操作原生dom节点来获取‘全部’完成这个需求
> 需要好多判断与setState 这样每个页面得多选框都需要处理
> 
> ### What does the proposed API look like?
> 建议！
> 可设置一个字符串或字段来完成
> 例如：当我设置 SelectType 为’全部‘时，
> 其他选项不选中
> 当我选择其他选项时 '全部'不选中，
> 当另外所有选项选中后，
> 当前选中项为全部
> 希望采纳一下这个问题 或者有更好得处理方法
> 谢谢

--
自己封装的话
如果用到了这个页就要写state 用来改变Select的value
然后getFieldDecorator也不可以用了 实现起来其实还是有点麻烦的

**Comment by zombieJ** [comment]
hi @957184448  ~

从设计上来说，这个场景其实就是一层的树状结构，TreeSelect 的 `showCheckedStrategy` 就是为了这个目的设计的。

如果是样式上不满足，可以自定义 dropdownClassName 覆盖掉。当然，如果还是硬要 Select，可以用 `dropdownRender` 自定义。只是觉得没有什么必要就是了。

ref: https://codesandbox.io/s/peaceful-field-okny4
