### ISSUE TITLE
TreeSelect依赖的包rc-tree版本有问题

### ISSUE THREAD

**Issue by wzy12589git** [ant-design/ant-design#19320]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
下载最新的antd版本，TreeSelect依赖的包rc-tree版本是2.1.3,使用直接报错。把rc-tree版本改回2.1.0就没问题.     

### What is expected?
TreeSelect正常使用

### What is actually happening?
TreeSelect正常使用

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.8.6 |
| System | win11 |
| Browser | Google Chrome 73.0.3683.86（正式版本） （32 位） |

---

**Comment by wzy12589git** [comment]
你好，是antd内部的package.json里面依赖的rc-tree自动下载了最新版本的2.1.3。https://codesandbox.io/s/wk04r016q8里面的代码实例，好像没法指定antd内部package.json内部的依赖包，所以我不知道https://codesandbox.io/s/wk04r016q8内部的代码依赖的哪个版本的rc-tree的包.

**Comment by pssgo** [comment]
+1

**Comment by afc163** [comment]
codesandbox 里也是用最新的依赖。

**Comment by afc163** [comment]
closing for no reproduce.
