### ISSUE TITLE
Remove table row hover background

### ISSUE THREAD

**Issue by jLemmings** [ant-design/ant-design#19326]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/5067](https://github.com/ant-design/ant-design/issues/5067)

### Steps to reproduce
Idea: Try to remove hover background of table row
Set CSS:
```
tr:hover {
    background: none;
}

td:hover {
    background: none;
}

.tr:hover {
    background: none;
}

.td:hover {
    background: none;
}
```

### What is expected?
I expect the there wont be any background on hover

### What is actually happening?
The default set background is still set

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.10.02 |
| System | Macos: 10.15 (19A583) |
| Browser | Firefox: 69.0.2 |

**Comment by afc163** [comment]
Try to life up your css selector priority, make sure higher then antd's styles.

**Comment by viniciusrma** [comment]
I have the very same doubt, but it seems like impossible to cancel/change the hover of the table rows

**Comment by meetzaveri** [comment]
I found out what was causing issue. 

Initially you can change `table` , `tr` and `thead` hover color by applying !important. But still issue was persistent. So I found out that on hovering row  the `td` field was applied background color . i.e. `tr.ant-table-row:hover > td`

So solution was 
```css

table:hover,
tr:hover,
thead:hover {
    background: #20293c !important;
}

.ant-table-tbody > tr.ant-table-row:hover > td {
    background: none !important;
}
```  

you can replace your color in `thead:hover` css line in above code snippet 

I hope you find this helpful

**Comment by Fauzdar1** [comment]
Tried everything on the internet, none of these answers in abundance work. The max result I can get is the color set in this `table:hover,
tr:hover,
thead:hover {` flashing. That's it. Whatever the color provided in it flashes for few milliseconds before going to a color no one knows coming from where.

Working on this project, One thing I've realized is styling Ant Design is messy and anti-productive, too much dependency on old school CSS, I want control in JS.

**Comment by balboFK** [comment]
Hello everyone! 
I know this is an old one but i found myself having issues with this again, and i was thinking that maybe we should ship a prop to control if you want the hover effect or not. 
Because most of the cases, when using custom selection specifically, the `rowClassName` prop is used to control the coloring and hover backgrounds, and it ends up bringing small issues like when you hover over a row that is being styled by `rowClassName` it gets overrided by the default styles. Also when you have fixed columns, on the left or on the right, these columns will end up having no change by the `rowClassName` definition.

What do you think @afc163 ?

**Comment by jayminnie** [comment]
Hello, I was also finding the same problem, but since I was using a normal table (without antd), the solution was simply:

`tr:hover td {
      background-color: none
}`

or

`tbody > tr:hover > td {
      background-color: none
}`

**Comment by satyam73** [comment]
Here's the solution which worked for me

I added a class with `onRow` prop and added classname on cell with `onCell` prop under columns prop, then I wrote css something like this

.rowClassname:hover {
  background: none;
  .columnClassname {
    background-color: #1890ff !important;
    color: white;
  }
}

**Comment by riyazshaikh-osplabs** [comment]
Thanks it is working for me

**Comment by reid105** [comment]
@viniciusrma https://stylesheets.space/questions/attempting-to-change-the-background-color-of-a-table-row-when-hovering-in-react-but-experiencing-no-success

**Comment by Farnis** [comment]
<Table
                    columns={columns}
                    dataSource={data}
                    pagination={false}
                    rowHoverable={false}
                />

just rowHoverable is false
 antd: "5.24.7"
