### ISSUE TITLE
tabs切换时候 affix的anchor消失问题

### ISSUE THREAD

**Issue by liuyueji** [ant-design/ant-design#19325]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-yalow-nn5j1)

### Steps to reproduce
在第二个tab滚动过 第一页的导航就消失了 。 在第三个tab滚动滑轮。前两个tab的导航就全部消失了

### What is expected?
能正常切换tab

### What is actually happening?
导航消失

| Environment | Info |
|---|---|
| antd | 3.12.4 |
| React | 16.7 |
| System | windows |
| Browser | chrome最新版 |

**Comment by afc163** [comment]
4.4.3 里已经是好的了：https://codesandbox.io/s/determined-fog-e8564?file=/index.js

建议升级到最新版本，
