### ISSUE TITLE
InputNumber 为什么不能选中

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design#19324]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mutable-paper-b6pff)

### Steps to reproduce
https://codesandbox.io/s/mutable-paper-b6pff

### What is expected?
https://codesandbox.io/s/mutable-paper-b6pff

### What is actually happening?
点不了框子

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | latest |
| System | windows |
| Browser | Google Chrome |

**Comment by yoyo837** [comment]
Form、Form.Item 本身具备布局能力，这属于你Grid的使用的问题吧。

**Comment by afc163** [comment]
https://codesandbox.io/s/keen-bhabha-x3nfw
