### ISSUE TITLE
Upload component - Multiple file upload not in alphabetical order

### ISSUE THREAD

**Issue by nitannn** [ant-design/ant-design#19322]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdesign-yohb4)

### Steps to reproduce
Use Upload Module with CustomRequest: 
1. Upload multiple images (Around 15). 

### What is expected?
Images should be uploaded in the Alphabetical order by default. rc-upload also follows this convention.

### What is actually happening?
Images are uploaded in random order (Might need to try a couple of times)
rc-upload numbering also follows the alphabetical order  (As seen in the demo). However - fileList returns random order as well:

*e.g. Sample FileList: *
rc-upload-1571641189804-2 (a.jpg)
rc-upload-1571641189804-3 (b.jpg)
rc-upload-1571641189804-4 (c.jpg)
rc-upload-1571641189804-5 (d.jpg)
rc-upload-1571641189804-6 (e.jpg)
rc-upload-1571641189804-7 (f.jpg)
rc-upload-1571641189804-8 (g.jpg)
rc-upload-1571641189804-9 (h.jpg)
rc-upload-1571641189804-11 (j.jpg) <--- This should be last
rc-upload-1571641189804-10 (i.jpg) <--- This should be before 11

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.10.2 |
| System | macOS Mojave 10.14.6 |
| Browser | 77.0.3865.90 |

**Comment by nitan84** [comment]
Hello, any updates on this?

**Comment by nitan84** [comment]
Hello, any updates on this?

**Comment by afc163** [comment]
In my machine it works well: https://codesandbox.io/s/antdesign-sinw4?file=/index.js

Feel free to comment if I miss something.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/85544288-76cb6680-b64d-11ea-9b26-f54da597bea1.png">
