### ISSUE TITLE
Option for hide selection column in ant table

### ISSUE THREAD

**Issue by akaguny** [ant-design/ant-design#19335]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We have interface with one selection in the table, but now we must reproduce select logic for implement selection logic.
We can use CSS hacks for antd, but it is not good
now we write something like this:
```
                    className: classnames({
                      [`${tableRowClassName}-selected`]: isProductSelected(productClass),
                    }),
```
and some handlers for update state (isProductSelected we calculate from state)

I was looking for:
#14198
#8766
#8741
but don't find any solution for this
#14198 is most similar for us, but we want to provide select ability all the time, but without checkbox, only by click

### What does the proposed API look like?
```
<Table {...props}
hideSelectionColumn: true
      />
```

**Comment by swillis12** [comment]
This would be a useful option, sometimes we want to select a row but do not need the radio/checkbox.

**Comment by afc163** [comment]
https://codesandbox.io/s/cool-lederberg-6j2zw

Custom css is a workaround.

**Comment by akaguny** [comment]
@afc163, any suggestions for feature?
css workaround is not best practice =(

**Comment by afc163** [comment]
Currently we may not add this feature for default design specification reason. It is a best practice to encapsulate new Comoponent for custom needs.

**Comment by akaguny** [comment]
Ok, thanks. Maybe ant 4.0 feature?

**Comment by prashanthsaka** [comment]
Just FYI ... if the table has grouping as well ... then the custom css should be:
```
.ant-table-selection-col, .ant-table-selection-column {
  display: none;
}
```

**Comment by superadminfabian** [comment]
This solves the problem, but it doesn't allow us to control whether the select checkbox is visible dynamically. I'd like to allow our users to control whether to show the checkbox when selecting an item. 

Is there a way to pass an additional 'classname' to the ant-table-selection-column rather than overriding it?

**Comment by superadminfabian** [comment]
Just in case anyone else is having the same issue. I was able to pass a className through getCheckboxProps.

**.tableSelectCheckboxOverride** .ant-checkbox-inner {
	background: transparent;
}

		const rowSelection ={
						selectedRowKeys: this.state.selectedRowKeys,
						onChange: this.onSelectedRowKeysChange,
						type: kTableConfig.selectionType, //checkbox/radio
						**getCheckboxProps: () => ({
							className: "tableSelectCheckboxOverride"
						})**
				  };

**Comment by almeidapaulooliveira** [comment]
Only changing the CSS was broking the Table alignment for me, if you have the same issue, try this:
```
	const rowSelection = {
                ... // Your own properties and add:
		columnWidth: 0, // Set the width to 0
		renderCell: () => "", // Render nothing inside
	};

```
and then override the CSS property as suggested above:
```
.ant-table-selection-column {
	display: none;
}
```

**Comment by luzhiy123** [comment]
https://codesandbox.io/s/polished-fast-7s6b0?file=/index.js
做样式隐藏，列表宽度设置出现错误

**Comment by shivamrsoft** [comment]
I have been trying to hide a column in the table as the data is coming from database. Is there any way to perfectly do this without effecting every other table in the website or can It be based on the props that only the first column in the table should be hidden.

**Comment by VigneshPT** [comment]
> Only changing the CSS was broking the Table alignment for me, if you have the same issue, try this:
> 
> ```
> 	const rowSelection = {
>                 ... // Your own properties and add:
> 		columnWidth: 0, // Set the width to 0
> 		renderCell: () => "", // Render nothing inside
> 	};
> ```
> 
> and then override the CSS property as suggested above:
> 
> ```
> .ant-table-selection-column {
> 	display: none;
> }
> ```

Thanks. The rowSelection option object worked fine, but only without the css `display:none`.. The `display:none` on the `.ant-table-selection-column` was messing with the width of the first column.

**Comment by davidfig** [comment]
Here's another method using scss:

```
.table-to-hide {
  tr > td:first-child, tr > th:first-child {
    display: none;
  }
}
```

**Comment by gmkhussain** [comment]
Try out. it's works for me

`<Table rowSelection={null} />`
