### ISSUE TITLE
Fixed column gets clipped if table doesn't require horizontal scroll

### ISSUE THREAD

**Issue by devuxer** [ant-design/ant-design#19338]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/devuxer/pen/yLLgMqV?&editable=true&editors=001](https://codepen.io/devuxer/pen/yLLgMqV?&editable=true&editors=001)

### Steps to reproduce
1. Open minimal reproduction (CodePen) and scroll the table to the bottom using the *scrollbar*.
2. Scroll back to the top using the scrollbar.
3. Use the *scroll wheel* to scroll the "Full Name" column to the bottom.

### What is expected?
- Nothing should be cut off.
- The scroll position of the columns should never get out of sync.

### What is actually happening?
- If you scroll using the scrollbar or the main part of the table, the "Full Name" cell of the last row is cut off.
    ![image](https://user-images.githubusercontent.com/1298521/67238566-3ce0fb00-f402-11e9-8e62-bf8f335547c4.png)
- If you scroll the "Full Name" column using the scroll wheel, the "Full Name" column scrolls further than the main part of the table, and the scroll positions get out of sync.
    ![image](https://user-images.githubusercontent.com/1298521/67238602-4ec29e00-f402-11e9-982e-1fa48a368fb7.png)

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.8.6 |
| System | Windows 10 Professional Version 10.0.18362 Build 18362 |
| Browser | Chrome Version 77.0.3865.120 (Official Build) (64-bit) |

---
For now, I'm working around this by setting `fixed` to `left` only if I know the table is going to be wider than the viewport (if it's not going to be wider, I set `fixed` to `undefined`). This is only possible because I'm using fixed column widths and can calculate the total width. If not, this bug would be very difficult to work around.

**Comment by afc163** [comment]
Cannot reproduce it in your codepen.

**Comment by devuxer** [comment]
@afc163 , I just tried it again in Chrome, Firefox, and Edge. The problem shows up in all three (though it looks slightly different in Chrome now).

What browser are you using? Can you post a screen capture of how it renders for you?

**Comment by afc163** [comment]
I reproduce it by turn off scrollbar in my Mac.

<img width="280" alt="图片" src="https://user-images.githubusercontent.com/507615/68067660-837d1080-fd85-11e9-8a9a-284b446af864.png">

**Comment by devuxer** [comment]
I should have mentioned, all my tests have been on Windows machines.

**Comment by afc163** [comment]
When any column is fixed, you have to set `scroll.x` to `true` or pixels value that makes table scrollable horizontally, otherwise fixed columns is meaningless.

https://codepen.io/afc163/pen/KKKQQPv?editors=0010

**Comment by devuxer** [comment]
If you set scroll.x to true, then you get a horizontal scroll bar even if there is nothing to scroll. This is not good. The table should be responsive to how much space the columns take up, and only show a scroll bar and fix columns if necessary.

**Comment by afc163** [comment]
> If you set scroll.x to true, then you get a horizontal scroll bar even if there is nothing to scroll

We have to in current implementation, which is not responsive as wish.

**Comment by devuxer** [comment]
@afc163 , OK, any plans to improve this in next version of antd?

**Comment by afc163** [comment]
You can trace our new Table in 4.0, but I can't give any guarantee.

https://github.com/react-component/table/pull/380
