### ISSUE TITLE
Pagination: add commas for large number of pages ( more than 1,000) 

### ISSUE THREAD

**Issue by brucean52** [ant-design/ant-design#19337]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently working on a project where we have a large number of paginated results. I would like large page number counts to be comma separated for better readability. example 1,230 instead of 1230. 

### What does the proposed API look like?
pageNumber.toLocaleString('en-US'); before rendering the page number.

**Comment by afc163** [comment]
Try `itemRender`
