### ISSUE TITLE
When sorting is enabled on a column the only sorting options should be ascending and descending. Not ascending, descending and none

### ISSUE THREAD

**Issue by marley-accelerize360** [ant-design/ant-design#19334]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Most applications use tables and to improve end user experience add the ability to filter, sort and search. Currently sorting, after being enabled on a column, is almost completely optional. Most apps using tables would prefer if when sorting is enabled that it be required, this makes it less confusing on the end user since they will always know how their table is being sorted. Currently its extremely confusing to have a table sorted descending and when you click the column to try to swap to ascending instead you disable the sort. This also forces you to check on the back-end if the table is sorted, and have a default sort case if its not. Overall I think it just wasted the user and developers time having sorting currently setup like this. 

### What does the proposed API look like?
I propose that when sorting is enabled on a column and if you define a default sort order that sorting should stay required. If the user tries to swap that columns sort order they shouldn't be able to disable the sorting. This just wastes the users time, makes an unnecessary DB call, and I can't think of a use case where you would want the results of some data completely unsorted (like why would you want your records ordered randomly in the table). If you want to leave in the older functionality just add a Boolean prop to the table object that is called sortingRequired if there are use cases I'm not seeing but currently this is wasting developer and user time.

**Comment by mrhodas107** [comment]
It would be convenient if sortDirections would follow the array given with a third option of 'default' along with 'ascend' and 'descend'.  Then remove default from being a forced option.

**Comment by miyamirz** [comment]
Any update on this?

**Comment by marley-accelerize360** [comment]
Nothing yet, I read somewhere that this is 'by design' but am surprised to not find a work around. I'd like to hear a explanation for what use case this fits because I can't think of any.

**Comment by mrhodas107** [comment]
In our app, we either want ascending or descending.  The default option is not useful to a user ever and they will always end up double clicking to move past default.

**Comment by marley-accelerize360** [comment]
Don't know why this is labeled inactive, still can't figure out why anyone would want to use the default option...

**Comment by swillis12** [comment]
I need this as well, current workaround I use is to implement my sorting outside of the table.

**Comment by lucksp** [comment]
PLEASE, let's prioritize this.  None should not be part of the table API. Additionally, the API docs clearly indicate only 2 choices

**Comment by Yakoot** [comment]
any news? I need this option

**Comment by zombieJ** [comment]
```tsx
sortDirections: ['ascend' | 'descend' | 'ascend']
```

**Comment by lucksp** [comment]
> ```tsx
> sortDirections: ['ascend' | 'descend' | 'ascend']
> ```
> 
> Should update faq for this.


I do not follow this suggestion, as it will not toggle.  The 4th click will be `ascend` again, which will make it feel like the click does nothing.

**Comment by zombieJ** [comment]
@lucksp , could you help to provide a reproduce? Seems it works as expect: https://codesandbox.io/s/relaxed-night-96skb

**Comment by lucksp** [comment]
> @lucksp , could you help to provide a reproduce? Seems it works as expect: https://codesandbox.io/s/relaxed-night-96skb

One of the differences is we are on V3, not V4.

**Comment by lucksp** [comment]
OK, well, that array tuple as suggested definitely seems to solve it for v3 & v4.  Regardless, if I have `["ascend" , "descend"]`, why would the next click also not be `ascend`?  Why do I need 3 options for that array, when the documentation says:

> Order of sorted values: 'ascend', 'descend', false

Additionally, the "unsorted" value is `null` correct?

**Comment by zombieJ** [comment]
@lucksp , antd table sort always need set to default state and thus no need to add `false` in the sorter. But for the no need back to default requirement, it seems not a good design. We do not update this since it will make breaking change.

**Comment by swillis12** [comment]
> @lucksp , antd table sort always need set to default state and thus no need to add `false` in the sorter. But for the no need back to default requirement, it seems not a good design. We do not update this since it will make breaking change.

Can we at least have an option to disable this default behavior? People just want ascend and descend. Suggesting to not make a breaking change, but make it opt-in. So if people do not want the "null" value they can have an option for it. I've completely disabled the AntD in-built sort since I started using it in 2016 for this exact reason.

**Comment by Ahmad129096** [comment]
well, i guess this issue is still not resolved and we have to somehow deal with default option by ourselves
