### ISSUE TITLE
打开两个Modal，当一起关闭时报错  _this.cacheOverflow is undefined

### ISSUE THREAD

**Issue by feibi** [ant-design/ant-design#19332]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-hoover-4xr3d)

### Steps to reproduce
1. 点击按钮，打开Modal 1
2. 点击按钮，打开Modal2
3. 点击ok或cancel
4. 页面空白

### What is expected?
正常关闭

### What is actually happening?
页面空白 ，控制台报错_this.cacheOverflow is undefined

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.10.2 |
| System | window 10 |
| Browser | chrome 77 |

**Comment by shaodahong** [comment]
原因是因为多个 `Modal` https://github.com/react-component/dialog/blob/14331d458a9a3d62b33c8916a61853eeb449b4d3/src/Dialog.tsx#L378 只会调一次，所以关闭时候 https://github.com/react-component/dialog/blob/14331d458a9a3d62b33c8916a61853eeb449b4d3/src/Dialog.tsx#L391 没有造成错误
