### ISSUE TITLE
【BUG】：modal依赖的rc-dialog的bug

### ISSUE THREAD

**Issue by wssgchungang** [ant-design/ant-design#19346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://1qq3r.csb.app](https://1qq3r.csb.app)

### Steps to reproduce
【BUG】：modal依赖的rc-dialog有2个bug，目前昨天官方只修复了一个bug
另一个Bug是一个modal的visible从true置为false,然后立刻将另外一个modal的visible置为true 也就是在this.setState({visible1:false, visible:true})两个弹框的显示和隐藏同时进行会导致 body一直是overflow:hidden 第二个弹框关闭的时候也不会把overflow：hidden去掉 导致页面的滚动条全部消失了

### What is expected?
第二个弹框关闭的时候会把overflow：hidden去掉

### What is actually happening?
第二个弹框关闭的时候也不会把overflow：hidden去掉

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 最新 |
| System | windows |
| Browser | 所有 |

**Comment by afc163** [comment]
Duplicate of #19340
