### ISSUE TITLE
父级容器将一个组件通过props传递给子组件，如何绑定事件？

### ISSUE THREAD

**Issue by miaojiuchen** [ant-design/ant-design#1934]
我有一个Modal的父组件，我给Modal传递了一个叫trigger的prop
![image](https://cloud.githubusercontent.com/assets/9482138/15733884/1d0744ce-28bd-11e6-81b8-cae6492ad7b2.png)

现在我想在这个容器中，给传进来的这个trigger绑定事件
![image](https://cloud.githubusercontent.com/assets/9482138/15733916/9c12b366-28bd-11e6-83e0-c11e9d330d64.png)

我知道这个问题和antd本身没关系，而且这样写肯定不对，因为这个属性是只读的，就是实在找不到资料，想问下正确的姿势是要怎样用？

**Comment by afc163** [comment]
https://facebook.github.io/react/docs/top-level-api.html#react.cloneelement

**Comment by miaojiuchen** [comment]
@afc163 万分感谢，正是我想要的！👍🏼
