### ISSUE TITLE
[feature]modal.method 支持footer，且支持自定义footer渲染函数，默认将onOk，onCancel回调函数作为参数传入footer函数中

### ISSUE THREAD

**Issue by kanweiwei** [ant-design/ant-design#19344]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不仅可以自定义footer，而且不定义onOk,onCancel的情况下,可以直接使用modal内部的onOk和onCancel。由于现有的modal.method不支持自定义footer，就自己封装了一个ButtonModal的组件，内部用state.visible控制modal的显示和隐藏。类似的功能，在实际项目中很多地方都会用到。

### What does the proposed API look like?
footer: string | ReactNode | ({onOk, onCancel}) => any;

```typescript
const H: React.Fc = (props: any) => {
  const showModal = () => {
    Modal.confirm({
      footer: ({ onOk, onCancel }: any) => {
        return <Button onClick={onCancel}>关闭</Button>;
      },
    });
  };
  return <Button onClick={showModal}>测试</Button>;
};
```

**Comment by yoyo837** [comment]
这个也先应用内封装Modal自用吧。修改的话算不能兼容的break change。就算要讨论支持也估是4了吧。

**Comment by yoyo837** [comment]
理解错意思了。忽略...

**Comment by afc163** [comment]
Duplicate of #16644
