### ISSUE TITLE
Menu组件模式切换后 <a>无法高亮显示

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#1935]
## 你做了什么？
 
Menu 的mode为 inline
MenuItem 内容为 <a href="javascript:;" > link1</a>

选中link1

Menu 的mode参数 由 inline --> vertical， 发现 link1 没有正确高亮显示

## 可重现的在线演示

http://codepen.io/anon/pen/dXyQYG?editors=0110

## 本地环境信息

- antd 版本: 1.2.1
- 操作系统及其版本： ubuntu 16.04
- 浏览器及其版本:  chrome 50.0.2661.102 Ubuntu 16.04 (64-bit)

**Comment by ddcat1115** [comment]
貌似是一个样式问题，三个条件同时存在时可以重现：
1. theme='dark'
2. mode='vertical'
3. 有<a>标签
