### ISSUE TITLE
Modal对话框

### ISSUE THREAD

**Issue by yangjchen** [ant-design/ant-design#19352]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
模态对话框应当必须响应对话框内容，但是目前的文档前三个案例都可以通过点击蒙层关闭对话框，这种案例会误导用户错误的使用模态弹窗

### What is expected?
模态对话框点击蒙层不能关闭

### What is actually happening?
模态对话框点击蒙层关闭对话框

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 文档 |
| System | 文档 |
| Browser | chrome |

**Comment by afc163** [comment]
Try `maskClosable={false}`。
