### ISSUE TITLE
[rfc] icon of avatar support React.ReactNode

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design#19359]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
```
    <Avatar size="small" src={o.avatar} icon={<IconFont type="xx"></IconFont>} />
```

### What does the proposed API look like?
```
    <Avatar size="small" src={o.avatar} icon={<IconFont type="xx"></IconFont>} />
```

**Comment by DiamondYuan** [comment]
i can make a pr.

**Comment by yoyo837** [comment]
@DiamondYuan  This issue will automatically close when #19368 is merged into the **master**.

**Comment by DiamondYuan** [comment]
> @DiamondYuan This issue will automatically close when #19368 is merged into the **master**.

the pr was merged to dev,so i close this issue.
