### ISSUE TITLE
upload多选上传问题

### ISSUE THREAD

**Issue by 1334310385** [ant-design/ant-design#19363]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
upload组件多选文件问题，会多次触发onchange,附带的参数的fileList中会保存上次选择的文件，这样会导致重复上送文件，不知道是我的用法问题还是组件时这个机制呢。

### What does the proposed API look like?
希望能够多选的时候，onchange只走一次，参数info.fileList里边只有本次选择的文件

**Comment by afc163** [comment]
这是预期的，所有变化状态会同步到 onChange，你可以用 file.status 做具体的逻辑判断。

**Comment by Mathround** [comment]
> 这是预期的，所有变化状态会同步到 onChange，你可以用 file.status 做具体的逻辑判断。

我现在也遇到这问题，比如10个文件上传直接导致10个后台请求，我想要的效果是上传文件能不能只走一次onchange，也就是只调一次接口？
