### ISSUE TITLE
Table 组件排序功能会自动触发 pagination 的 onChange 事件

### ISSUE THREAD

**Issue by DelBlank** [ant-design/ant-design#19369]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/DelBlank/pen/abbJJay?&editable=true&editors=001](https://codepen.io/DelBlank/pen/abbJJay?&editable=true&editors=001)

### Steps to reproduce
对 Table 组件进行筛选或排序，会自动触发 pagination 的 onChange 事件

### What is expected?
对 Table 组件进行筛选或排序，不会自动触发 pagination 的 onChange 事件

### What is actually happening?
对 Table 组件进行筛选或排序，会自动触发 pagination 的 onChange 事件

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16 |
| System | windows10 |
| Browser | chrome 77.0.3865.90 (正式版本) （64 位） |

**Comment by yoyo837** [comment]
可能是因为排序需要重置分页到第一页

**Comment by afc163** [comment]
是的，具体见 https://github.com/ant-design/ant-design/issues/16978

**Comment by DelBlank** [comment]
排序后不一定要重置到第一页啊，这种行为应该交给开发者去控制，我记得之前的版本是开发者自己控制的

**Comment by DelBlank** [comment]
@afc163
