### ISSUE TITLE
DatePicker能不能自己改造成选择季度时间段的

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#1937]

**Comment by ddcat1115** [comment]
目前官方只支持日历和月历以及选择时间，如果有此类需求可以自己尝试改造，欢迎pr 😃

**Comment by afc163** [comment]
可以关注：https://github.com/ant-design/ant-design/issues/1418

**Comment by XUGAOBO** [comment]
![qq 20160604100934](https://cloud.githubusercontent.com/assets/11780264/15797002/83e8fcd4-2a3c-11e6-8a3f-4ee83ea8ce07.png)
![qq 20160604100941](https://cloud.githubusercontent.com/assets/11780264/15797003/8425fe18-2a3c-11e6-841c-eff082143bf1.png)

**Comment by XUGAOBO** [comment]
@ddcat1115 ,因为目前要用,等不到版本更新了

**Comment by Ms-Yan** [comment]
可以把改造的这个共享一下吗？我现在也遇到这个需求

**Comment by XUGAOBO** [comment]
已经离职,没有代码了

**Comment by Ms-Yan** [comment]
那你可以把大概的思路给我说下嘛？ 我不太会弄这个 没头绪

**Comment by Ms-Yan** [comment]
我觉得你可以提交到你的github  这样可以分享给大家呢

**Comment by XUGAOBO** [comment]
你稍等,我下午提交到我的github上

**Comment by Ms-Yan** [comment]
好的 谢谢

**Comment by XUGAOBO** [comment]
https://pan.baidu.com/s/1i55W7KL,下载下来看看把,不做维护了,现在工作中用不到,希望对你有帮助

**Comment by XUGAOBO** [comment]
https://pan.baidu.com/s/1i55W7KL。          下载下来看看把,不做维护了,现在工作中用不到,希望对你有帮助
