### ISSUE TITLE
Descriptions组件 内容过长 右边内容不可见

### ISSUE THREAD

**Issue by xuzhenyang** [ant-design/ant-design#19373]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
内容过长或低分辨率，该组件无法展示全内容

### What does the proposed API look like?
增加横向滚动，提高适配性

**Comment by xrkffgg** [comment]
横向滚动条的话，感觉不太好看。我这里是修改成了换行。

如果你非要加滚动条的话，可以在项目中增加这个

```
.ant-descriptions-view {
    overflow: auto;
}
```
