### ISSUE TITLE
setFieldsValue not working in Select mode multiple

### ISSUE THREAD

**Issue by CarlosAmaral** [ant-design/ant-design#19375]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-tesla-nfx1g)

### Steps to reproduce
Click on the option All in the Select

### What is expected?
To set the values of the fields

### What is actually happening?
Not setting the the values of the fields

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.10 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
`normalize`: https://codepen.io/afc163/pen/JJVXzG?editors=001

https://ant.design/components/form/#getFieldDecorator(id,-options)-parameters

<img width="988" alt="image" src="https://user-images.githubusercontent.com/507615/67387027-a27ee400-f5c8-11e9-9907-b3cedfb5586a.png">
