### ISSUE TITLE
Support Select value to be an object

### ISSUE THREAD

**Issue by caibirdme** [ant-design/ant-design#19379]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我使用需要选中多个用户。用户经常是用`user = [{id, name, extra_info}]`来表示。当选中某些项之后，我希望value能够是完整的`{id, name, extra_info}`，而不是key，或者label 或者label key。这样可以让用户指定选中后提交的值长什么样，避免拿到key再回过头去做一次反向查找

### What does the proposed API look like?
`<Option fullvalue={d} key={d.key}>{d.text}</Option>`

**Comment by afc163** [comment]
不行的，字面量对象有比较问题，没办法判断 value 是不是同一个。建议拿着 string 自行去数据中二次筛选。
