### ISSUE TITLE
Include response header in onSuccess callback of rc-upload for ant-design upload component

### ISSUE THREAD

**Issue by makersPalm** [ant-design/ant-design#19386]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
AWS s3 sends important information in the response headers of an upload which can be used to store data with app API. One example is the version-id header that can be used to distinguish between multiple versions of the same file. Right now only the response body is accessible in the upload component onChange callback. Since rc-Upload contains a xhrheader arg in the onSuccess callback. We can also return that value in the onChange callback of upload component.

### What does the proposed API look like?
in following component: 
https://github.com/ant-design/ant-design/blob/master/components/upload/Upload.tsx

I have added xhrHeader argument and assign it to targetItem so it is accessible in the onChange callback
```
onSuccess = (response: any, file: UploadFile, xhrHeader: any) => {
    this.clearProgressTimer();
    try {
      if (typeof response === 'string') {
        response = JSON.parse(response);
      }
    } catch (e) {
      /* do nothing */
    }
    const { fileList } = this.state;
    const targetItem = getFileItem(file, fileList);
    // removed
    if (!targetItem) {
      return;
    }
    targetItem.status = 'done';
    targetItem.response = response;
    targetItem.headerResponse = xhrHeader;
    this.onChange({
      file: { ...targetItem },
      fileList,
    });
  };
```

**Comment by afc163** [comment]
closed by #19539
