### ISSUE TITLE
Conic-radial gradient for Progress (types 'circle' and 'dashboard')

### ISSUE THREAD

**Issue by BenjaBobs** [ant-design/ant-design#19397]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently you can only specify linear gradient for `Progress`, and when doing a circular type, such as `circle` or `dashboard` this can result in weird behaviour.

Example: [https://codesandbox.io/s/bold-mcnulty-xqpg2](https://codesandbox.io/s/bold-mcnulty-xqpg2)

### What does the proposed API look like?
If allowing conic-gradient in the `stroke-color` could solve this problem:

[Conic-gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/conic-gradient)

Api could look like this:
```typescript
  <Progress
    type="dashboard"
    percent={75}
    strokeColor={{
      "50deg": "#ff0000",
      "100deg": "#ffaa00",
      "150deg": "#ffff00",
      "360deg": "#00ff00"
    }}
  />
```

**Comment by afc163** [comment]
@BenjaBobs could you help us to fix this by sending PR to https://github.com/react-component/progress/ ?

**Comment by afc163** [comment]
https://codepen.io/daleyjem/pen/OyLepO

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/44404
