### ISSUE TITLE
Modal在ie11环境下打开后关闭会导致滚动条出现问题

### ISSUE THREAD

**Issue by huozw** [ant-design/ant-design#19393]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
打开modal时会给body加上overflow:hidden的样式，关闭后却没有取消，导致ie环境下滚动条body上的滚动条消失

### What is expected?
恢复正常滚动

### What is actually happening?
滚动条消失

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.8.6 |
| System | windows |
| Browser | ie11 |

**Comment by yoyo837** [comment]
ref: #19340 https://github.com/react-component/dialog/pull/153
@shaodahong 看看这个IE上是不是不行。

**Comment by shaodahong** [comment]
是的，也没报错，迟点我调试下

**Comment by shaodahong** [comment]
IE browser doesn't merge `overflow` style, so need to set it separately, I will fix it
