### ISSUE TITLE
antd.table，当head名过长时，边框变白

### ISSUE THREAD

**Issue by 13996477276** [ant-design/ant-design#19391]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/13996477276/file-C-Users-pc-Desktop-371.gif.git](https://github.com/13996477276/file-C-Users-pc-Desktop-371.gif.git)

### Steps to reproduce
将table里head内容设置很长，body内边框变白

### What is expected?
body内边框正常显示

### What is actually happening?
body内边框变白

| Environment | Info |
|---|---|
| antd | 3.19.1 |
| React | 16.6.0 |
| System | window10， |
| Browser | Google Chrome 70.0.3538.102（正式版本） （64 位） |

---
head内容不长时，不会出现该问题，内容过长时，部分电脑出现上述问题，变换了电脑分辨率的，问题还是一样

**Comment by afc163** [comment]
closing for no reproduce.
