### ISSUE TITLE
SortDirections property of column of table can't work properly with react hooks.

### ISSUE THREAD

**Issue by Fire-Kirin** [ant-design/ant-design#19398]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-antd-basic-table-sort-ki5y7)

### Steps to reproduce
1. click column to sort data.
2. data will be set by react hooks in 'onChange' event.

### What is expected?
First click, sorted in descending order. Second click, sorted in ascending order. Third click, sorted by default. And repeat it.

### What is actually happening?
- With react v16.11.0 and antd v3.24.2, first click and second click are both sorted in descending order, third click is sorted in ascending order. And repeat it.
- With react v16.4.1 and antd v3.21.0, it's always sorted in descending order.

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.11.0 & 16.4.1 |
| System | macOS Catalina v10.15 |
| Browser | chrome v77.0.3865.120 |

---
I suspect that the auto sort timer is reset after setting the data.

**Comment by afc163** [comment]
Add key or move `columns` out render function.

https://codesandbox.io/s/react-antd-basic-table-sort-xfi7i
