### ISSUE TITLE
TreeSelect使用搜索的时候，每次失去焦点关闭搜索输入框的时候搜索的内容就会丢掉，希望搜索后失去焦点能够继续保留上一次搜索输入的内容

### ISSUE THREAD

**Issue by jinjunss** [ant-design/ant-design#19395]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
每一次搜索之后会从后台请求对应的数据，然后选中一个后，搜索的内容会清空，希望不要清空

### What does the proposed API look like?
```javascript

```

**Comment by zombieJ** [comment]
用 `searchValue` 和 `onSearch` 做成受控模式即可。
