### ISSUE TITLE
ButtonGroup: text button is not aligned with the icon button

### ISSUE THREAD

**Issue by hsuanxyz** [ant-design/ant-design#19392]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-beaver-rmsrb)

![image](https://user-images.githubusercontent.com/22736418/67451359-b2dba100-f652-11e9-8b7b-6a0ea240a5b7.png)

### Steps to reproduce
*

### What is expected?
aligned

### What is actually happening?
not aligned

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | * |
| System | * |
| Browser | * |

---
This problem caused by `.ant-btn-icon-only`

**Comment by xrkffgg** [comment]
![](https://github.com/xrkffgg/Kimg/blob/master/ant-design/2019.10/button.png?raw=true)

- 用了官网最新的 `master` 代码测试的，两种 `ICON` 的形式都没有问题啊
- 你的代码，我用了第一种 `ICON` 方式，样式正常

😂😂😂
