### ISSUE TITLE
getFieldProps能绑定2个属性值吗？

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#1939]
我封装了一个控件，我希望这个控件能在使用时，通过getFieldProps绑定2个属性值。
貌似一个控件只能对应一个属性值？
那是不是第二个属性值我只能通过get接口取了？

**Comment by ddcat1115** [comment]
没太明白你的需求，请结合demo说明下 
http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
超过 5 天没有反馈，关了。

**Comment by wufeng87** [comment]
不好意思，反馈太迟了。
我还是自己通过别的方式获取了另外一个值。
我想，一个trigger对应一个属性值应该是合乎常理的；
如果一个trigger对应传入两个属性值，也不知道该怎么匹配。

例子，其实就是最简单的场景，代码如下。
我希望属性能收集到value和value对应的显示在页面的值，比如下面例子中的"jack"和"杰克"
`import { Select } from 'antd';
const Option = Select.Option;

function handleChange(value) {
  console.log(`selected ${value}`);
}

ReactDOM.render(
  <Select showSearch
    style={{ width: 200 }}
    placeholder="请选择人员"
    optionFilterProp="children"
    notFoundContent="无法找到"
    onChange={handleChange}
  >
    <Option value="jack">杰克</Option>
    <Option value="lucy">露西</Option>
    <Option value="tom">汤姆</Option>
  </Select>
, mountNode);`

**Comment by afc163** [comment]
可以试试 Select 的 `labelInValue` 属性。http://ant.design/components/select/#components-select-demo-label-in-value
