### ISSUE TITLE
文档配色方案不太好，屏幕较差或者弱视的同学查看困难

### ISSUE THREAD

**Issue by yujiangshui** [ant-design/ant-design#194]
颜色小而浅，在非 Retina 的 显示器 或者 iMac 下面效果比较差，阅读吃力，更不敢想象 PC 下面的效果。

**Comment by Erwin11** [comment]
颜色可以通过style/themes/custom.less进行自定义修改

**Comment by yujiangshui** [comment]
@Erwin11 我是说目前官方线上文档。
