### ISSUE TITLE
Table component onChange callback is not triggered when filters are set programmatically and not changed by table header filter elements

### ISSUE THREAD

**Issue by rumtraubenuss** [ant-design/ant-design#19415]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-antd-styled-template-73yxh)

### Steps to reproduce
Open the codesandbox example. Make use of the filter elements from the table's header very right. When filters are applied the callback of `onChange` sets the filter to a local state and logs a message to the codesandbox console. Reset the filters. Use the bottom button to set the filter via the local state directly. The filters are applied but the `onChange` callback is not triggered.

### What is expected?
`onChange` callback should be triggered when filters change, regardless of using the table filter elements or setting the filter condition in a programmatic way.

### What is actually happening?
When setting the filter without using the table's filter elements the `onChange` callback is not triggered.

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.8.6 |
| System | os x |
| Browser | chrome, firefox, safari |

---
Is there another way to get `currentDataSource` which I currently try to get from `onChange` callback `extra` attribute. Which works fine in general, but not when the `onChange` callback is not triggered.

**Comment by afc163** [comment]
```jsx
{
  const [value, setValue] = useState('');
  const onChange = () => {
    console.log('onChange');
  };

  return <input value={value} onChange={onChange} onClick={() => setValue('not trigger onChange')} />
}
```

Like native input, programmatically setState won't trigger `onChange`.
