### ISSUE TITLE
Is Alert closing state reversed in source code？

### ISSUE THREAD

**Issue by 4074** [ant-design/ant-design#19426]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/alert/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/alert/index.tsx)

### Steps to reproduce
none

### What is expected?
none

### What is actually happening?
none

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | none |
| System | none |
| Browser | none |

---
[https://github.com/ant-design/ant-design/blob/master/components/alert/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/alert/index.tsx)

I have a puzzle when watching the source code of `Alert` component.

Initial, the `state.closing` is `true`.

After click close button, set `state.closing`  to `false`.

I think the value of `state.closing` is reversed, if `state.closing` meaning the `Alert` component is clsoing.

Is that so? If i have a wrong understanding, please let me know.

Thank you.

**Comment by afc163** [comment]
`closing` means start to close and not finished, closed means close animation finished.

**Comment by yoyo837** [comment]
表示关闭进行时，关闭的动画效果处理需要。

**Comment by 4074** [comment]
@afc163 So `closing` should be `false` initial? But it is `true` in source code.

**Comment by afc163** [comment]
Ehhh..
