### ISSUE TITLE
Tree. When the child nodes have multiple levels, there is no horizontal scroll bar or the width is not increased.

### ISSUE THREAD

**Issue by xupengkun** [ant-design/ant-design#19422]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://bossfs.sammbo.com/3/1/A_300149/2019/10/SIMWEB-1571987148026-eb806991.png](http://bossfs.sammbo.com/3/1/A_300149/2019/10/SIMWEB-1571987148026-eb806991.png)

### Steps to reproduce
Load a node that can exceed the width of the outer element and observe how to preview the node of the overflow

### What is expected?
Components can increase the width of the horizontal scroll bar or component to adapt to the width

### What is actually happening?
The component has no nodes that handle overflow

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | ^16.11.0 |
| System | macOS Catalina |
| Browser | Google Chrome  79.0.3945.8 |

**Comment by xupengkun** [comment]
https://codesandbox.io/s/adoring-jepsen-39j44?fontsize=14

**Comment by zombieJ** [comment]
`width: "max-content"`

https://codesandbox.io/s/determined-snow-fnc1s

**Comment by VladislavYeremeyev** [comment]
> `width: "max-content"`
> 
> https://codesandbox.io/s/determined-snow-fnc1s

That doesn't work when Tree component has `height` prop.
