### ISSUE TITLE
TypeScript 如何写出符合 <Dropdown /> 中符合 getPopupContainer 类型声明规范的回调？

### ISSUE THREAD

**Issue by codelegant** [ant-design/ant-design#19420]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://tva1.sinaimg.cn/large/006y8mN6gy1g8a7g7z2hjj32bk0u0qeo.jpg](https://tva1.sinaimg.cn/large/006y8mN6gy1g8a7g7z2hjj32bk0u0qeo.jpg)

### Steps to reproduce
N/A

### What is expected?
写法可以符合 drowdrop.d.ts 中 getPopupContainer 的类型声明

### What is actually happening?
二者不符合。

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | 16.10.2 |
| System | macOS 10.15 (19A602) |
| Browser | Chrome 78.0.3904.70 |

**Comment by yoyo837** [comment]
你这是可能为null造成的类型错误吧

**Comment by codelegant** [comment]
> 你这是可能为null造成的类型错误吧

这个 null 如何避免呢？

**Comment by yoyo837** [comment]
getPopupContainer 确保始终能得到一个`HTMLElement`, 比如
```tsx
// 只是举例
getPopupContainer={() => document.getElementById('xxx') || document.body}
```

**Comment by codelegant** [comment]
> getPopupContainer 确保始终能得到一个`HTMLElement`, 比如
> 
> ```tsx
> // 只是举例
> getPopupContainer={() => document.getElementById('xxx') || document.body}
> ```

鬼才。
