### ISSUE TITLE
columns设置属性fixed: left，在大屏上，样式出错。

### ISSUE THREAD

**Issue by ZhaoTim** [ant-design/ant-design#19428]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/elated-swartz-iz9ks)

### Steps to reproduce
将右侧预览窗口在新的页面中打开即可（也就是塑造出大屏效果），就可以看到fixed的列旁边有很大的空白。
具体设置可以看code-link的代码。
![t](https://www.notion.so/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fbfc2890a-9ffa-4c48-8173-d4d831f72ee6%2FUntitled.png?table=block&id=4ef2db23-573b-4e81-a746-a680a2818f0e&width=3940&cache=v2)
### What is expected?
WHY It happened？
HOW to fix it ?

### What is actually happening?
fix.

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.11.10 |
| System | Mac |
| Browser | Chrome |

**Comment by shaodahong** [comment]
Can you try to remove `width`?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14789#issuecomment-463553191

**Comment by afc163** [comment]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/507615/67630455-d73db480-f8c2-11e9-8d00-393baf2e11e9.png">
