### ISSUE TITLE
edge浏览器下ant design的表格在固定表头的情况下有问题  表头上有个滚动条

### ISSUE THREAD

**Issue by miaozilong** [ant-design/ant-design#19438]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/table-cn/#components-table-demo-fixed-header](https://ant-design.gitee.io/components/table-cn/#components-table-demo-fixed-header)

### Steps to reproduce
用edge打开就能看到

### What is expected?
看不到表头上的滚动条

### What is actually happening?
看到表头上的滚动条

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16 |
| System | WIN10 |
| Browser | edge |

**Comment by miaozilong** [comment]
![a](https://user-images.githubusercontent.com/3994941/67616015-2f62b100-f806-11e9-9b21-6baeb85cf411.jpg)

**Comment by shaodahong** [comment]
yep, the default overflow style is `scroll`, should be set to `auto`

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/18879#issuecomment-534016149
