### ISSUE TITLE
InputNumber组件在form表单内收集时机为blur会导致组件上下加减失效

### ISSUE THREAD

**Issue by chenyjam** [ant-design/ant-design#19435]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-rgb-qoh5g)

### Steps to reproduce
点击InputNumber组件加减不生效

### What is expected?
希望生效

### What is actually happening?
不生效

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.11 |
| System | win7 |
| Browser | chrome |

**Comment by afc163** [comment]
#11379
