### ISSUE TITLE
Any temprory solution for DatePicker input readonly mode or onInpute interface ?

### ISSUE THREAD

**Issue by ArunAaron77** [ant-design/ant-design#19431]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/17605 temporary solution ](https://github.com/ant-design/ant-design/issues/17605 temporary solution )

### Steps to reproduce
Any temprory solution for DatePicker input readonly mode or onInpute interface ?

### What is expected?
DatePicker input readonly api for give readonly for the datepicker input

### What is actually happening?
In Mobile while selecting the date in datepicker there is no need to trigger keyboard to type. we just select the date we needed.

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | react js |
| System | linux |
| Browser | chrome |

**Comment by afc163** [comment]
No temprory solution now.
