### ISSUE TITLE
Grid component use Flexbox by default

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#19430]
In `antd` [4.0 plan](https://github.com/ant-design/ant-design/issues/16911), **Internet Explorer 11, our lowest supported IE version**, so we should use Flexbox by default, `Grid` component can refactor

Ref: #16635

**Comment by afc163** [comment]
Duplicate of #7309

**Comment by shaodahong** [comment]
@afc163 similar but differentiated, this issue I want to remove lower than IE11 **legacy code**, the #7309 is a new feature

**Comment by afc163** [comment]
You can reply in #7309, #16635 is exactly what you want to do, which is remove IE9/10 support by using flex. Also reduce huge css bundle size in Grid.

**Comment by shaodahong** [comment]
ok, thank you for your reply

**Comment by afc163** [comment]
Could you help on #16635, @zombieJ is short of hands to handle it now.

We are plan to make `<Row type="flex" />` as default and the only mode (no need `type` prop anymore).

**Comment by shaodahong** [comment]
I try, in my plan, next, I will upgrade  #19169 `rc-dropdown` and fix #19408 typescript type error, both 4.0 plan
