### ISSUE TITLE
Popconfirm onConfirm 页面刷新后第一次confirm不触发回调函数

### ISSUE THREAD

**Issue by Xianbei233** [ant-design/ant-design#19437]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/18213](https://github.com/ant-design/ant-design/issues/18213)
[codebox](https://codesandbox.io/s/antd-reproduction-template-w6w4r?fontsize=14)

### Steps to reproduce
在popConfirm所在页面，刷新页面，点击confirm，onConfirm回调不会执行，第二次点击，onConfirm执行

### What is expected?
刷新后第一次点击onConfirm执行

### What is actually happening?
点击confirm，onConfirm回调不会执行，第二次点击，onConfirm执行

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | ^16.7.0 |
| System | Windows 10 1903 |
| Browser | Chrome 77.0.3865.120 |

**Comment by Xianbei233** [comment]
有相同的单，但那个憨憨没按流程来单子被bot关了

**Comment by Xianbei233** [comment]
codesandbox这种最简依赖似乎复现不出来，我这边直接给开发环境线上地址和对应部分的组件代码可以吗

**Comment by afc163** [comment]
重现不出来我们没办法定位问题的。

**Comment by Xianbei233** [comment]
好，我复现出来了，要和Radio搭配使用
https://codesandbox.io/s/antd-reproduction-template-w6w4r?fontsize=14

**Comment by yoyo837** [comment]
如果直接提供代码，那么就需要花时间去准备运行条件、启动，沟通交互和操作，如果每个人都只提供代码无形中就需要开销很多时间，把这个时间分摊给每个问题人会比较高效。

**Comment by afc163** [comment]
> 如果每个人都只提供代码无形中就需要开销很多时间

开销时间倒是其次，主要是只提供代码基本解决不了问题。

**Comment by Xianbei233** [comment]
已复现
https://codesandbox.io/s/antd-reproduction-template-w6w4r?fontsize=14

**Comment by afc163** [comment]
你给的例子我无法重现。

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-w6w4r?fontsize=14
@afc163 我试过能复现的, 准确的来说就是Popconfirm 第一次显示出来，点按钮没用，第二次就可以；如果不点击按钮，Popconfirm 隐藏一次再显示，直接点按钮也是可以的。

**Comment by yoyo837** [comment]
请再确认下吧，`Need Reproduce` 后面会关闭 issus.

**Comment by afc163** [comment]
![Nov-01-2019 11-15-07](https://user-images.githubusercontent.com/507615/67999879-ef357f80-fc98-11e9-8a43-e9df68ef09ec.gif)

这是我本地的效果。

**Comment by yoyo837** [comment]
你用啥录制的我给你录一个，我这里确实 **100%** 会，Chrome  78.0.3904.87, MacOS Catalina 10.15.1

**Comment by yoyo837** [comment]
![屏幕录制2019-11-0111 25 59](https://user-images.githubusercontent.com/6134547/68001095-90bed000-fc9d-11e9-8298-6d7bdf233490.gif)

gif 有点大...

**Comment by yoyo837** [comment]
[屏幕录制2019-11-0111.25.59.zip](https://github.com/ant-design/ant-design/files/3796603/2019-11-0111.25.59.zip)

暂时没找到合适的gif录制工具，把视频也放上来...

**Comment by afc163** [comment]
同样是 Chrome 78.0.3904.87，为啥表现不一样。你试试无痕窗口。

**Comment by yoyo837** [comment]
无痕窗口 指 隐私模式吗？

**Comment by afc163** [comment]
对。

**Comment by yoyo837** [comment]
情况相同。

**Comment by Xianbei233** [comment]
试了下，table里面render里套popconfirm似乎也会有概率出现一样的情况

**Comment by ZiQiangWang** [comment]
遇到了相同的情况，这个例子我可以重现，https://codesandbox.io/s/antd-reproduction-template-w6w4r?fontsize=14

Environment | Info
-- | --
antd | 3.25.2
React | ^16.8.4
System | macOS 10.15.1
Browser | Chrome 78.0.3904.108

**Comment by Evoque** [comment]
同遇到这个问题，第一次无效，第二次触发。

**Comment by guojunhao118** [comment]
这个问题解决了么？我也发现了这个问题，版本是3.x

**Comment by afc163** [comment]
@yoyo837 最新的 antd 4.x 里再测试一下试试？

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-9lootk?file=/package.json

看上去正常

**Comment by afc163** [comment]
现场无法恢复了，先关了。

**Comment by QiZhou-Tang** [comment]
3.x想解决这个问题，有人解决了吗？
