### ISSUE TITLE
[Table] Inifinite loop update when using Table.Column with sortOrder

### ISSUE THREAD

**Issue by ycycwx** [ant-design/ant-design#19443]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-antd-column-sort-order-5idj9)

### Steps to reproduce
Broken currently and toggle comment ***L27*** `setTableData(1);` or ***L36*** `sortOrder="ascend"` will solve the problem.
And there is **no** problem using props `columns` directly with `Table`.

``` jsx
// no error
<Table columns={columns} />
```

### What is expected?
Use `sortOrder` with `Table.Column` correctly.

### What is actually happening?
Infinite loop.

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.11.0 |
| System | macOS Catalina |
| Browser | Chrome 77.0.3865.120 |

---
The reason I *guess*:

These lines will create **new** columns (**and also new column in columns**) in every update when using Table.Column.

https://github.com/ant-design/ant-design/blob/99d8f07607f07b5bc81d1931b267f1a5d6b94ab5/components/table/Table.tsx#L176-L177

More details in `util.normalizeColumns`.

https://github.com/ant-design/ant-design/blob/99d8f07607f07b5bc81d1931b267f1a5d6b94ab5/components/table/util.tsx#L60-L62

But `nextState.sortColumn` still get `prevState.sortColumn` here.

https://github.com/ant-design/ant-design/blob/99d8f07607f07b5bc81d1931b267f1a5d6b94ab5/components/table/Table.tsx#L179-L183

Which may cause `sortState.sortColumn !== sortColumn` to be always `true` in `componentDidUpdate`. Because `sortState` is derived by new `columns`.

https://github.com/ant-design/ant-design/blob/99d8f07607f07b5bc81d1931b267f1a5d6b94ab5/components/table/Table.tsx#L287

**Comment by kliakos** [comment]
`defaultSortOrder` doesn't work either in `<Table.Column/>`, while the same works fine with `columns` prop. Could be the same bug.
