### ISSUE TITLE
动态表单添加表单项后如何触发onFieldsChange或onValuesChange

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#19449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对外store保存数据及时刷新UI

### What does the proposed API look like?
可以自动触发上述事件

连接https://codesandbox.io/s/antd-reproduction-template-nlyk4?fontsize=14

**Comment by afc163** [comment]
> 如何触发onFieldsChange或onValuesChange

你的例子看上去没问题，修改的时候都会触发。

**Comment by Fled8617** [comment]
@afc163 我是手动在useEffect里调用的setFieldsValue，是不是应该自动触发俩事件呢

**Comment by afc163** [comment]
不应该的，就像 `<input value={this.state.value} onChange={onChange} />`，手动设置 `setState({ value: '' })` 也不应该触发 `onChange`。
