### ISSUE TITLE
Table 设置x: 'max-content'， 表格默认会显示横向滚动条

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#19445]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
默认不显示滚动条，超过宽度后，在显示

### What does the proposed API look like?
使用chrome浏览器，默认显示横向滚动条，查看样式后发现生成 overflow-x: scroll;
期望样式生成 overflow-x: auto;

**Comment by afc163** [comment]
这是合理的，`overflow-x: auto` 会产生很多宽度对齐问题。不需要滚动条就关闭 x 就好。

**Comment by l745230** [comment]
> 这是合理的，`overflow-x: auto` 会产生很多宽度对齐问题。不需要滚动条就关闭 x 就好。


在笔记本上，内容不够显示，这时候出现横向滚动条合理，能接受
但是到21寸显示器，表格内容够显示，默认展示一个无法拖动的横向滚动条，看起来很丑

或者能不能提供个方案，主动设置生产的为overflow-x: auto;

**Comment by l745230** [comment]
@afc163

**Comment by afc163** [comment]
你可以试试 `!important` 强制样式覆盖。
