### ISSUE TITLE
Cascader search

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1944]
![](https://os.alipayobjects.com/rmsportal/tjyEqocefyJtrDT.png)

**Comment by lanll** [comment]
赞，最好能支持拼音搜索

**Comment by lanll** [comment]
你好，我想问一下这边的搜索是前端搜索还是后台搜索

**Comment by benjycui** [comment]
> 赞，最好能支持拼音搜索

> 你好，我想问一下这边的搜索是前端搜索还是后台搜索

匹配函数做成可配置的就可以了。

**Comment by ericshao** [comment]
非常期待此项改进

**Comment by benjycui** [comment]
rc-cascader 需要支持定义 Menus 中 Menu 的高度和宽度。

**Comment by benjycui** [comment]
https://github.com/react-component/cascader/pull/14
