### ISSUE TITLE
 when disabled table rowSelection then selectedRowKeys not working

### ISSUE THREAD

**Issue by durgapatra** [ant-design/ant-design#19440]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/adoring-shockley-94d44] 
(https://codesandbox.io/s/adoring-shockley-94d44)

### Steps to reproduce

 Select all row in table (rowSelection)  > disabled rows  getCheckboxProps: record => ({
        disabled: true
      }) like this   (now all selected check is unchecked )

### What is expected?
When I disabled all rows. table row looks like disable with checked.

### What is actually happening?
 check on there https://codesandbox.io/s/adoring-shockley-94d44,

| Environment | Info |
|---|---|
| antd | 3.13.1 |
| React | 16.8.6 |
| System | 3.23.5 |
| Browser | 77.0.3865.120  Google Chrome |

**Comment by durgapatra** [comment]
Hi  @yesmeck 
can you please solved these issues.

**Comment by xiaofengqqcom123** [comment]
I have this problem，too
demo: https://codesandbox.io/s/kexuanze-ant-design-demo-qy2pd?file=/index.js:786-794

**Comment by xiaofengqqcom123** [comment]
You can do this by modifying the style：
.ant-checkbox-disabled .ant-checkbox-inner::after {
    position: absolute;
    display: table;
    border: 2px solid #fff;
    border-color: #f2f4f7;
    border-color: rgba(0, 0, 0, 0.25);
    border-top: 0;
    border-left: 0;
    border-collapse: separate;
    -webkit-transform: rotate(45deg) scale(1) translate(-50%, -50%);
    -ms-transform: rotate(45deg) scale(1) translate(-50%, -50%);
    transform: rotate(45deg) scale(1) translate(-50%, -50%);
    opacity: 1;
    transition: all 0.2s cubic-bezier(0.12, 0.4, 0.29, 1.46) 0.1s;
    -webkit-animation-name: none;
    animation-name: none;
    content: ' ';
  }
demo：https://codesandbox.io/s/kexuanze-ant-design-demo-qy2pd?file=/index.css

**Comment by paulussimanjuntak** [comment]
Is there any way to set the indeterminate to be checked?
I'm using a third-party library to check what needs to disable
here my code with validator.js

```javascript
getCheckboxProps: (record) => ({
    disabled: isIn(record.key, selectedKeys),
    key: record.key
  })
```

here demo link: https://codesandbox.io/s/ant-design-table-indeterminate-not-checked-5r973

What I expect is the indeterminate will be checked when there is a checked item even when the item is disabled
