### ISSUE TITLE
[CheckBox] √ icon not display in the  center

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#19450]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Related Issue
https://github.com/ant-design/ant-design/issues/16695

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-williams-36q12)

### Steps to reproduce
set style `{ width: "1px", margin: "0 auto" }` to outside wrapper

### What is expected?
the icon should be in the center

### What is actually happening?
the icon is not in the center

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | latest |
| System | mac os 10.14.4 |
| Browser | chrome 78 |

**Comment by chiaweilee** [comment]
https://github.com/ant-design/ant-design/issues/16695#issuecomment-494272954 did fix this.

**Comment by afc163** [comment]
Thx for reporting, trace in #16695
