### ISSUE TITLE
Drawer: overflowed content cannot be hidden when placement is top

### ISSUE THREAD

**Issue by hsuanxyz** [ant-design/ant-design#19454]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-voice-zoc96)

### Steps to reproduce
Click the open button and click on the mask

![drawer-issue](https://user-images.githubusercontent.com/22736418/67658916-fce7be00-f995-11e9-8d18-06f087637d0a.gif)

### What is expected?
Hide overflowed the content

### What is actually happening?
Not hide overflowed the content

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | * |
| System | * |
| Browser | * |

**Comment by shayminsky** [comment]
the wrapper's height is unhandled when placement is top  and it is set to be  256px.
i tried this in index.css, although i think the wrapper's height should adapt to the ant-drawer-body's height automatically
```
.ant-drawer-content-wrapper {
    overflow: auto;
}
.ant-drawer-body {
    background: #fff;
}
```
