### ISSUE TITLE
请问一下，Tree 树形控件如何清除已选择的项？

### ISSUE THREAD

**Issue by wishflyer** [ant-design/ant-design#1945]
请问一下，Tree 树形控件如何清除已选择的项？应该调用什么方法呢？
我删除了某个节点，然后选择其他节点时候，发现之前选择的节点数据（包括已删除的）都还在，不知道怎么清除selected~~~求解~~

还有，能否获得选择节点的下属全部子节点？

非常感谢！

**Comment by ddcat1115** [comment]
@warmhug  看一下呢 ~

**Comment by warmhug** [comment]
再仔细看下API怎么用？受控和非受控 这些概念。

**Comment by wishflyer** [comment]
通过每次onSelect时设置this.state.selectedKeys来保存选择项，同时该受控项也可用来设置选择状态。

结贴，谢谢！
