### ISSUE TITLE
走马灯第一次加载后高度为1

### ISSUE THREAD

**Issue by lawrsp** [ant-design/ant-design#1946]
代码如下：
```
bannerView = (<Carousel autoplay>
        {banners.map(item => (
          <img
            src={item.image}
            key={item.id}
            alt={item.image}
          />
        ))}
      </Carousel>);
```

刷新一下就可以了，但是第一次打开总是高度为1

**Comment by ddcat1115** [comment]
请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by jljsj33** [comment]
图片没加载吧。。设个固定高度就没了吧，。应该？

**Comment by afc163** [comment]
学习下 markdown 吧。https://guides.github.com/features/mastering-markdown/

**Comment by lawrsp** [comment]
@ddcat1115 
这是个例子：
http://codepen.io/anon/pen/qNdZyQ
这个应该是必现的吧
用原版的react-slick没这个问题，Carousel和react-slick貌似只是差在了css上？
Carousel里有个min-height ＝ 1px

**Comment by lawrsp** [comment]
@jljsj33 设固定高度也没有用

**Comment by jljsj33** [comment]
在 img 外面加个标签吧。。。

**Comment by lawrsp** [comment]
@jljsj33 这个有效

**Comment by lawrsp** [comment]
@jljsj33 这个有副作用，多个点时候，不能自动调整高度，还看这个例子：http://codepen.io/anon/pen/qNdZyQ

**Comment by jljsj33** [comment]
你这例子确定说的是自动调整高度？？？

**Comment by jljsj33** [comment]
官例里也没有多个时自动调整高的吧。。

**Comment by jljsj33** [comment]
如果是根据resize改变宽度而改变高度。。。把 img 的 width='100%' 加上。。

```
<span key={item.id} >
          <img
            src={item.image}
            alt={item.image}
            width='100%'
          />
          </span>
```

总共只有三个，一页显示3个干嘛？？

**Comment by lawrsp** [comment]
@jljsj33 
我说的没有自动调整高度，因为图片本身的比例是固定的，所以再变的矮一些，就可以显示完整了

总共三个，只是做个例子，找一张图，比找三张一摸一样的图，来的方便些：）而且用了resposive特性，只要变窄浏览器，会剩下一个的

自动调整高，是因为之前老是一条线（height＝1px），才加的，加上adpativeHeight的效果就是
1. 单张图片等重复多次：第一次一条线，然后滚一次，出全了
2. 两张图片：第一次，一条线，滚一次，出全了，再滚一次，又一条线

现在看起来没问题了

看来结论就是：
span ＋ width＝100%  ＋ 不需要adpativeHeight

有机会再试试这个新的昂：）
