### ISSUE TITLE
Feat : DayJs instead of Moment JS 

### ISSUE THREAD

**Issue by sabesansathananthan** [ant-design/ant-design#19460]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It reduce the leading to a huge bundle size

### What does the proposed API look like?
API with Day Js https://github.com/iamkun/dayjs

**Comment by sabesansathananthan** [comment]
Can I do it

**Comment by yoyo837** [comment]
Need owner to accept this suggestion.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10437
