### ISSUE TITLE
Pagenation please provide style that fix the position of "<" ">" button

### ISSUE THREAD

**Issue by fengertao** [ant-design/ant-design#19466]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Pagenation组件，当有多页时候，我们会发现上一页和下一页按钮(通常用 < 和 > button表示)的位置是变动的。
比如一共12页，当用户选中第1页或者选中第4页，或者选中第5页时，上一页按钮的位置都不一样。

如果用户时居中对齐，那么上一页以及下一页按钮的位置都会随着页面变动。
这样的UI给用户带来的困扰就是，当用户连续点击上一页或者连续点击下一页时，用户往往会点到其它按钮上。需要按一下后，调整鼠标位置，再按第二下，很难受。

### What does the proposed API look like?
建议除了"simple" style外，再提供一个新的style。采用这个style后，上一页和下一页的位置固定。里面的页面按钮的数量如果不足可以留白。

**Comment by yoyo837** [comment]
用产品教育一下用户行为吧，改掉这个“没看清就啪啪几下连续点”的习惯。就好比Windows上安装软件，各种隐藏的☑️，要是不习惯连点下一步，就不会全家桶了。

**Comment by afc163** [comment]
暂时不做改动。
