### ISSUE TITLE
Does not automatically scroll to the top when change page size on the non-first page

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#19464]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-dream-ccg6e)
ref: #18726
### Steps to reproduce
1.打开重现链接;
2.切换到第二页, 手动往下滚动部分距离;
3.更换每页大小;

### What is expected?
与切换页码相同，更换pageSize时也能自动滚动到表格顶部

### What is actually happening?
更换pageSize时不能自动滚动到表格顶部

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest |

**Comment by yoyo837** [comment]
ping @MrHeer

**Comment by MrHeer** [comment]
first page does not work also, because I never do it. Need add it?
