### ISSUE TITLE
Table component please privide parameter "minLines"

### ISSUE THREAD

**Issue by fengertao** [ant-design/ant-design#19467]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用Table component时，比如一共45条记录，每页10条记录，分5页，最后一页5条记录。
这样用户跳到最后一页时，页面的高度会突然变小，页面布局调整，很难看。

### What does the proposed API look like?
希望提供 minLines参数。

<Table minLines=10>

如果页面内的记录不足10行，则仍然显示10行，不足的行留白。保证整个table的高度不变。

**Comment by afc163** [comment]
这个建议用自定义样式来设置一个 `min-height` 就好。

**Comment by fengertao** [comment]
min-height的话需要码农自己去计算行高。
特别是在不同浏览器、不同Theme、不同分辨率下，行高可能都不同。码农很难算出一个兼容各种情况的行高。
