### ISSUE TITLE
[SO没人回答，只能来这问了]antd 2.2 兼容React 16吗？

### ISSUE THREAD

**Issue by panlina** [ant-design/ant-design#19468]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[CHANGELOG.en-US.md](https://github.com/ant-design/ant-design/blob/2.x-stable/CHANGELOG.en-US.md#220)
这里有写

> Not rely on specific version of React now.

代表2.2 是兼容React 16的吗？

如果要从2.11.1升级到3，有没有codemod？好像只见到有1.x->2.x的。

### What does the proposed API look like?
.

**Comment by afc163** [comment]
1. 没有测试过，你可以试试。
2. https://ant.design/changelog-cn#%E4%B8%8D%E5%85%BC%E5%AE%B9%E6%94%B9%E5%8A%A8
