### ISSUE TITLE
Tab change animation laggy on rerenders

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#19479]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/megawac-the-scripter/pen/xxxXKvP?&editable=true&editors=001](https://codepen.io/megawac-the-scripter/pen/xxxXKvP?&editable=true&editors=001)

### Steps to reproduce
Rerender a `Tabs` component multiple times during a tab change animation. In my example I do this by simply setting the state of the parent component causing `Tabs` to have to rerender. In practice this is likely due to app store changing and the parent component needing to pass data down to the child tab panes.

From the codepen:

```jsx
class TabStuff extends React.Component {
  state = {
    currentTab: "1",
    content: 0,
  };
  
  componentDidMount() {
    this.generateContent();
  }

  generateContent = () => {
    this.setState({
      content: this.state.content  + 1,
    });
    setTimeout(this.generateContent, (100 * Math.random()) +  25)
  }

  onChange = (key) => {
    this.setState({ currentTab: key });
  }

  render() {
    return (
      <Tabs activeKey={this.state.currentTab} onChange={this.onChange}>
        <TabPane tab="Tab 1" key="1">
          Content of Tab Pane 1
        </TabPane>
        <TabPane tab="Tab 2" key="2">
          Content of Tab Pane 2
        </TabPane>
        <TabPane tab="Tab 3" key="3">
          Content of Tab Pane 3
        </TabPane>
      </Tabs>
    );
  }
}
```

### What is expected?
The animation to be smooth.

### What is actually happening?
The tab change animation is extremely laggy. As I show in the example, if the interval between rerenders is inconsistent the tab animation will jump periodically forward and backwards.

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.x |
| System | Ubuntu 16.04 |
| Browser | Firefox 70 |

**Comment by afc163** [comment]
Should be fixed in #24552
