### ISSUE TITLE
Select组件在定位为fixed的容器中,下拉框会随着滚动条移动

### ISSUE THREAD

**Issue by juneryo** [ant-design/ant-design#1947]
- antd 版本: 1.2.1

示例在这里
http://codepen.io/juneryo/pen/BzNjzP?editors=0010
打开下拉框之后，移动Y轴滚动条，下拉框会跟着动。。。

**Comment by ddcat1115** [comment]
因为下拉框跟select不属于同一个容器，所以目前没有fixed，优化的话应该需要针对fixed的情况做特殊处理...

**Comment by afc163** [comment]
http://ant.design/#/components/select?scrollTo=Select+props 

已有解决方案，看 getPopupContainer 的说明。
