### ISSUE TITLE
Table set ellipsis will automatically display the browser's tooltip

### ISSUE THREAD

**Issue by ldd27** [ant-design/ant-design#19473]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-ellipsis](https://ant.design/components/table-cn/#components-table-demo-ellipsis)

### Steps to reproduce
Mouse over the ellipsis column of the table and pause for a few seconds

### What is expected?
Use the tooltip that comes with antd instead of the tooltip of the browser.

### What is actually happening?
Display the browser's tooltip

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.8.6 |
| System | Mac 10.14.6 |
| Browser | Chrome 78 |

**Comment by afc163** [comment]
I think native browser tooltip is better for annoying Tooltip in ellipsis situation.

**Comment by ldd27** [comment]
But the browser's tooltip needs to hover for about 2 seconds to open, some people may not find this feature.
