### ISSUE TITLE
table中每个表格可绑定自己的组件

### ISSUE THREAD

**Issue by luochangyuan** [ant-design/ant-design#19478]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table的每个表格项都可可选地绑定自己的select、checkbox（表示这个表格项被选中，类似选中一整行，但这一功能只选中这一格）等。
功能需求来源：
一个表格（x，y）展示了信息，然后每一格都有同类别的属性。选中某几个表格项，然后提交，则只提交选中的表格项，包括里面的组件信息，如select的value等。即除了按行来选中，也希望可以按（x，y）的某一项选中，且可附加信息（其他组件）。
类似月份，而非一个list，然后每条属性不一致。而是每个单元格的属性是类似的，所以按行来选中是不够的。

### What does the proposed API look like?
类似：
（x，y）表格项，可以获取每个项里的信息，如其中选择了安装select组件，则可以获取到select的vaule等值。每个项是否checkbox被选中也是可以获取的。

扩展，不同表格项在不同情况下可以绑定不同类型的组件，如部分绑定select，部分绑定button，部分绑定modal等等。

虽然目前可以通过内嵌jsx的方式来绑定某个组件，但无法使得两个不同组件绑定在同一个单元格里，使得两个组件是相关联的，即可交互的，所以急需这一功能。

**Comment by yoyo837** [comment]
个人觉得，功能倒是好，感觉太复杂了，做到UI库不一定合适。

**Comment by luochangyuan** [comment]
好的，确实应用情况比较少。已收到请确认-------- 原始邮件 --------主题：Re: [ant-design/ant-design] table中每个表格可绑定自己的组件 (#19478)发件人：Amumu 收件人：ant-design/ant-design 抄送：luochangyuan <1278948646@qq.com>,Author 个人觉得，功能倒是好，感觉太复杂了，做到UI库不一定合适。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ant-design/ant-design/issues/19478?email_source=notifications\u0026email_token=AFNMLFOEF6CQKV6N5WC5GZ3QQ7RBVA5CNFSM4JGEQ3A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECPQGJY#issuecomment-547291943",

"url": "https://github.com/ant-design/ant-design/issues/19478?email_source=notifications\u0026email_token=AFNMLFOEF6CQKV6N5WC5GZ3QQ7RBVA5CNFSM4JGEQ3A2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOECPQGJY#issuecomment-547291943",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by afc163** [comment]
建议自行封装上层业务组件。
