### ISSUE TITLE
React Warning for Affix: FunctionComponents cannot be given refs. Check the render method of `ResizeObserver`

### ISSUE THREAD

**Issue by hfknight** [ant-design/ant-design#19470]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-hooks-0i3ce?fontsize=14)

### Steps to reproduce
1. Run the provided reproduction example
2. Check the console

### What is expected?
No warnings

### What is actually happening?
The console prints:
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ResizeObserver`.
    in TestButton (created by ResizeObserver)
    in ResizeObserver (created by Context.Consumer)
    in div (created by Context.Consumer)
    in div (created by ResizeObserver)
    in ResizeObserver (created by Context.Consumer)
    in Affix (created by Demo)
    in div (created by Demo)
    in div (created by Demo)
    in Demo
```

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.10.1 |
| System | macOS Catalina |
| Browser | Google Chrome |

**Comment by XSmarter** [comment]
我这里控制台仍然有这个错误，应该怎么处理掉呢？ @yesmeck

**Comment by afc163** [comment]
@XSmarter 移除 yarn.lock 或者 package-lock.json 再重装 node_modules。

**Comment by XSmarter** [comment]
> @XSmarter 移除 yarn.lock 或者 package-lock.json 再重装 node_modules。

我按照您说的试了下还是控制台报错，重新安装后antd版本已经是3.26.6了

**Comment by XSmarter** [comment]
在yarn.lock 中
antd version "3.26.6" 下
看到rc-resize-observer "^0.1.0"，是不是这个版本还没有解决这个问题呢？ @afc163

**Comment by afc163** [comment]
https://www.npmjs.com/package/rc-resize-observer

最新版本应该是 0.1.3  你检查一下实际安装的版本。

**Comment by XSmarter** [comment]
在node_modules中检查了一下确实是0.1.3版本了 但是项目启动 有Affix组件的还是报错

```javascript
index.js:1 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ResizeObserver`.
    in ConnectFunction (created by ResizeObserver)
    in ResizeObserver (created by Context.Consumer)
    in div (created by Context.Consumer)
    in div (created by ResizeObserver)
    in ResizeObserver (created by Context.Consumer)
    in Affix (created by Unship)
    in div (created by Unship)
    in Unship (created by ConnectFunction)
    in ConnectFunction (created by DynamicComponent)
    in DynamicComponent (created by Context.Consumer)
    in Route (created by RouteWithProps)
    in RouteWithProps (created by Context.Consumer)
```

**Comment by afc163** [comment]
@XSmarter 可以提供一个 codesandbox，你上面的链接已经看不到 warning 了。

**Comment by jasper-pan** [comment]
我也遇到了同样的问题，依赖版本"rc-resize-observer": "^0.1.3"

**Comment by lucksp** [comment]
Why is this closed?

I also have the same issue:

I have tried `rm -rf package-lock.json node_modules` and reinstalling.  My rc-resize-observer v is `"0.1.3"`, my ant-design version is `"3.26.17",`
