### ISSUE TITLE
Select选择器 allowClear={true}  .ant-select-selection-selected-value的padding-right: 16px; 是来干什么的， 个人感觉多余， 导致宽度少了16px

### ISSUE THREAD

**Issue by johnJine** [ant-design/ant-design#19483]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#rowSelection](https://ant.design/components/select-cn/#rowSelection)

### Steps to reproduce
<Select defaultValue="lucy" allowClear style={{ width: 120 }} onChange={handleChange}>
      <Option value="jack">Jack</Option>
      <Option value="lucy">Lucy</Option>
      <Option value="disabled" disabled>
        Disabled
      </Option>
      <Option value="Yiminghe">yiminghe</Option>
    </Select>
增加allowClear，  发现Select选择器值回填的区域少了16px

### What is expected?
回填值区域的宽度和没有allowClear的回填值区域宽度一样

### What is actually happening?
少了16px

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | react  |
| System | win10 |
| Browser | chrome |

---
个人猜测之前的清除的叉号， 不是position: absolute;

**Comment by afc163** [comment]
应该可以删掉，现在有了 margin-right 来避免重叠了。

@johnJine 来个 PR 吧。
