### ISSUE TITLE
Upload组件在remove时会触发onChange

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#19488]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-grothendieck-v4ikj)

### Steps to reproduce
click remove icon

### What is expected?
只触发onRemove事件，3.17.0版本是只触发了onRemove事件，api上注明的触发onChange不包括remove

### What is actually happening?
触发了onChange

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
这是对的，原来不触发 onChange 是一个 bug，在 https://github.com/ant-design/ant-design/pull/18937 里修复了。
