### ISSUE TITLE
Customize Ant Design Theme in React-Native

### ISSUE THREAD

**Issue by kvnlee777** [ant-design/ant-design#19482]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'm trying to customize the Ant Design Theme in React-Native. I only know how to customize the theme for React-Web thru https://ant.design/docs/react/use-with-create-react-app. I cannot find the recommended way for React-Native. I'm using expo-cli for React-Native.

### What does the proposed API look like?
Should i install less transformer for react-native and customize the theme by overriding variables inside antd.less with another .less file?

**Comment by afc163** [comment]
Please create issue in https://github.com/ant-design/ant-design-mobile-rn/issues
