### ISSUE TITLE
无法正确导入@import "~antd/dist/antd.less"

### ISSUE THREAD

**Issue by JoyNop** [ant-design/ant-design#19493]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://i.loli.net/2019/10/30/kPpaen3xlq862cO.png](https://i.loli.net/2019/10/30/kPpaen3xlq862cO.png)

### Steps to reproduce
使用create-react-app- typescript 创建一个新项目
安装antd
安装react-app-rewired customize-cra
配置config-overrides.js
```js
const { override, fixBabelImports, addLessLoader, addBundleVisualizer } = require('customize-cra');
module.exports = override(
  //do stuff with the webpack config...
 
  addBundleVisualizer({
    "analyzerMode": "static",
    "reportFilename": "report.html",
  }, true),
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    // style: 'css',
    style: true,
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { '@primary-color': '#1DA57A' },
  }) ,
) 

```

在app.css中引入
@import "~antd/dist/antd.less";

方式二：通过`yarn eject`暴露webpack，为webpack配置less后依旧出现该问题

### What is expected?
正常使用

### What is actually happening?
![微信截图_20191030172350.png](https://i.loli.net/2019/10/30/kPpaen3xlq862cO.png)

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.11 |
| System | windows 10  |
| Browser | chrome  77.0.3865.90 |

**Comment by huntdream** [comment]
应该要导入antd.css吧

**Comment by yoyo837** [comment]
`css` 不能引入 `less`吧应该 , 我之前试过`create-react-app` 好像默认是配置支持`scss`, 要支持`less` 自己`eject` 后修改`webpack`配置。

**Comment by JoyNop** [comment]
> 应该要导入antd.css吧

https://ant.design/docs/react/use-with-create-react-app-cn#%E5%BC%95%E5%85%A5-antd

有提到
修改 `src/App.css`，在文件顶部引入 `antd/dist/antd.css`。

https://ant.design/docs/react/customize-theme-cn#%E5%9C%A8-create-react-app-%E4%B8%AD%E5%AE%9A%E5%88%B6%E4%B8%BB%E9%A2%98

提到
如果你是通过 `'antd/dist/antd.css'` 引入样式的，改为` antd/dist/antd.less`。

**Comment by yoyo837** [comment]
我感觉你理解错了文档意思。这样哈，你先试试自己新建一个less文件随便写个样式，然后引入，能不能正常使用先。

**Comment by JoyNop** [comment]
> 我感觉你理解错了文档意思。这样哈，你先试试自己新建一个less文件随便写个样式，然后引入，能不能正常使用先。

我自己写的 a.modules.less 
```
.Hello{
  color:red
}
```
```
import React from "react";
import "./App.css";
import { Button } from "antd";
import * as Style from "./a.module.less";
const App: React.FC = () => {
 
  console.log(Style);

  return (
    <div className="App">
      hello world
      <div className={Style.Hello}>hellllllllllllllllllo</div>
    </div>
  );
};

export default App;

````

这样子是可以正常展示样式的

**Comment by huntdream** [comment]
那是不是可以把App.css改为App.less试试?

**Comment by JoyNop** [comment]
![0001](https://user-images.githubusercontent.com/25074750/67914636-abc10f80-fbcb-11e9-91d6-a0aaa526d9a1.jpg)
这样子是不是可以表明，我的less可以正常使用？

**Comment by yoyo837** [comment]
@JoyNop 不一定，你把你这个less里写点less特有的语法试试，比如把这个红色先声明为less变量，然后使用。

**Comment by JoyNop** [comment]
> 那是不是可以把App.css改为App.less试试?

我的天，我怎么把这事给忘了！ 😅

十分感谢

**Comment by JoyNop** [comment]
> @JoyNop 你把你这个less里写点less特有的语法试试，比如把这个红色先声明为less变量，然后使用。
 声明变量也是没问题的，刚刚 @huntdream  的由`app.css`改为`app.less`这样就正常了


谢谢两位的帮助 😃 

![微信截图_20191031105241](https://user-images.githubusercontent.com/25074750/67915001-b4661580-fbcc-11e9-9c9b-1a17230311e0.png)
