### ISSUE TITLE
基于 bisheng 的一些站点问题收集

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#1949]
- [x] `http://ant.design/CHANGELOG` => `http://ant.design/changelog`
- [x] http://ant.design/CHANGELOG 页面的 toc 应该不显示，md 文件里有个 `toc: false` 的配置。
- [x]  ~~http://ant.design/components/input#components-input-demo-basic demo 代码展开按钮，鼠标移上去会有跳动问题~~ 无法重现
- [x] `"Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.` fixed in https://github.com/benjycui/bisheng/commit/eb874ba3dbd3a38a270325958b4c0268651d8ace
- [x] 播放按钮样式。http://ant.design/docs/spec/transition

![](https://zos.alipayobjects.com/rmsportal/NwmNdEpKPjlzsqs.png)

- [x] 搜索框输入并回车之后，会出现 `components/xxxx` 的字样。
- [x] 建议加回原来的顶部进度条，因为现在切换页面时需要加载。http://011x.ant.design/

http://ricostacruz.com/nprogress/

- [x] ![](https://zos.alipayobjects.com/rmsportal/TTVXhkVKeODnLse.png)
- [x] breadcrumb 页面的奇怪警告。

```
index.js:5884 Warning: React.createElement(...): Expected props argument to be a plain object. Properties defined in its prototype chain will be ignored.
```

- [x] 网站在 IE10 下无法访问。
- [x] 左侧菜单没有高亮。http://ant.design/changelog
- [x] 本地上传文件失效。https://github.com/afc163/dora-plugin-upload https://github.com/ant-design/ant-design/commit/1903748d8c97af830f34352ea037fb6fc2336360
- [x] 第一次访问任何页面，会加载很多无关的 `index.md.js`，看上去是 demo 下面的文件。例如访问首页。
- [x] 加了 es6-shim 后网站在 IE10/11 下依然无法访问。报错 `Symbol 不存在`。
- [ ] 构建速度略慢，1800+ 个模块。
- [ ] HMR support
- [x] bisheng 对主题没有提供入口文件，对于一些第一次页面加载完成要做的事，没地方放。https://github.com/ant-design/ant-design/blob/cc4cab5b1e0470fec12ea986ae8be0a256ed8c5f/site/theme/template/Layout/index.jsx#L51 这里每次跳转都会运行。

- [ ] demo 文件 `only: true` 不支持
- [ ] 动态加载 demo 组件的 meta 值，现在重启一次 npm start 成本略高
- [x] 页面锚点丢失 http://ant.design/docs/pattern/navigation （http://012x.ant.design/docs/pattern/navigation）
- [x] 点击 # 时不应触发这里。https://github.com/ant-design/ant-design/blob/e0c0830a04d91419147a7907ac2d786e07c84ff7/site/theme/template/Content/MainContent.jsx#L15-L24
- [x] 导航收起状态不对。![](https://zos.alipayobjects.com/rmsportal/kumjiKYEjduecwE.png)
- [x] 演示文档有问题。http://ant.design/components/calendar/#components-calendar-demo-notice-calendar 
- [ ] 老旧链接适配。

**Comment by afc163** [comment]
- [ ] `"Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.`

**Comment by superRaytin** [comment]
![image](https://cloud.githubusercontent.com/assets/2723376/15815443/b272c98a-2bff-11e6-820e-45b0e503affb.png)

滑过时出现，停下来半秒之后重新浮上来。

**Comment by afc163** [comment]
这个是我加上的，不然有些会被挡住演示。

**Comment by superRaytin** [comment]
@afc163 OK。

**Comment by afc163** [comment]
- [ ] 播放按钮样式。

![](https://zos.alipayobjects.com/rmsportal/NwmNdEpKPjlzsqs.png)

**Comment by guangming21** [comment]
发现错别字
![qq 20160607174539](https://cloud.githubusercontent.com/assets/18028721/15853761/00621e1e-2cd9-11e6-8887-3812068e0936.png)

**Comment by benjycui** [comment]
@guangming21 通假字不能算错别字……通假字！……读书人的事，能算错别字么？

**Comment by afc163** [comment]
- [ ] 搜索框输入并回车之后，会出现 `components/xxxx` 的字样。

**Comment by afc163** [comment]
- [ ] 建议加回原来的顶部进度条，因为现在切换页面时需要加载。http://011x.ant.design/

**Comment by afc163** [comment]
- [ ] ![](https://zos.alipayobjects.com/rmsportal/TTVXhkVKeODnLse.png)

**Comment by afc163** [comment]
- [ ] breadcrumb 页面的奇怪警告。

```
index.js:5884 Warning: React.createElement(...): Expected props argument to be a plain object. Properties defined in its prototype chain will be ignored.
```

**Comment by afc163** [comment]
- [ ] 网站在 IE10 下无法访问。

**Comment by afc163** [comment]
- [ ] 左侧菜单没有高亮。http://ant.design/changelog

**Comment by afc163** [comment]
- [ ] 本地上传文件又失效了。

**Comment by afc163** [comment]
- [ ] 第一次访问任何页面，会加载很多无关的 `index.md.js`，看上去是 demo 下面的文件。例如访问首页。

**Comment by afc163** [comment]
- [ ] 加了 es6-shim 后网站在 IE10/11 下依然无法访问。报错 `Symbol 不存在`。

**Comment by yesmeck** [comment]
我发现所有带 anchor 的链接一点整个页面就卡死。

**Comment by afc163** [comment]
修复了。

**Comment by frontwindysky** [comment]
官网组件文档的api表格里，组件参数的“必选”“可选”信息，目前混在说明里，格式不一致，还有些组件遗漏此信息，希望能明示，或者独立成一列

**Comment by jljsj33** [comment]
这播放按钮谁整的。。。。。。。。。。。。。。

**Comment by afc163** [comment]
- [ ] 构建速度略慢，1800+ 个模块。
- [ ] HMR support

**Comment by ocyangel** [comment]
http://ant.design/docs/spec/principle
![qq 20160624101940](https://cloud.githubusercontent.com/assets/6308331/16325954/14dff040-39f5-11e6-9e86-f0791bae6c9d.jpg)
点击之后不会回到顶部，卡在半中间，总要自己滑动到顶部才能开始查看，体验不好。windows 下360和MAC OSX下都这样

**Comment by afc163** [comment]
@OUZICHENG fixed above.

**Comment by afc163** [comment]
- [ ] bisheng 对主题没有提供入口文件，对于一些第一次页面加载完成要做的事，没地方放。https://github.com/ant-design/ant-design/blob/cc4cab5b1e0470fec12ea986ae8be0a256ed8c5f/site/theme/template/Layout/index.jsx#L51 这里每次跳转都会运行。

**Comment by afc163** [comment]
- [ ] demo 文件 `only: true` 不支持
- [ ] 动态加载 demo 组件的 meta 值，现在重启一次 npm start 成本略高

**Comment by afc163** [comment]
- [ ] 页面锚点丢失 http://ant.design/docs/pattern/navigation （http://012x.ant.design/docs/pattern/navigation）

**Comment by afc163** [comment]
- [ ] 点击 # 时不应触发这里。https://github.com/ant-design/ant-design/blob/e0c0830a04d91419147a7907ac2d786e07c84ff7/site/theme/template/Content/MainContent.jsx#L15-L24

**Comment by afc163** [comment]
- [ ] 导航收起状态不对。![](https://zos.alipayobjects.com/rmsportal/kumjiKYEjduecwE.png)

**Comment by afc163** [comment]
- [ ] 演示文档有问题。http://ant.design/components/calendar/#components-calendar-demo-notice-calendar

**Comment by afc163** [comment]
先关了，有问题单独再开。
