### ISSUE TITLE
Popover should have the ability to change placement based on the available spaces

### ISSUE THREAD

**Issue by bhavikji** [ant-design/ant-design#19495]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature will give flexibility to tooltips and popovers to let them choose placement dynamically based on the available space from the viewport offset. 

One of the fine examples of the following can be seen here.

![When the popover doesn't have space to fit in the viewport. ](https://i.imgur.com/GKyPs4d.jpg)

When the popover doesn't have space to fit in the viewport.

![When the popover has enough space to fit in the viewport. ](https://i.imgur.com/Hsnw1zN.jpg)

When the popover has enough space to fit in the viewport. 

As you can see the markers which are close to the top of viewport are forcing popover to slide in the bottom while the markers which are in the center or far from the top continue to show with top placement. I feel that would be a great inclusion in the antd if it gives support of dynamic placement of tooltip and popover.

### What does the proposed API look like?
The possible way is to add one more parameter in API something like fitToScreen which allows the user to control when they wish to slide in the popover. This must not be the default parameter so that the user will have full flexibility to use in whichever way they wish to.

     <Popover
        content={Content}
        key={id}
        fitToScreen={true}
      >
        <div  key={id}>
          Hover Me!
        </div>
      </Popover>

This [SO question](https://stackoverflow.com/questions/41684320/how-can-i-get-the-coordinates-of-my-component-that-is-outside-of-the-viewport-in?rq=1) gives the initial approach to achieve this, though this is a naive way to fix this it might be helpful to get the initial idea to achieve this.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12153#issuecomment-420874541
