### ISSUE TITLE
Table 表格只要设置固定列 鼠标单击后 设置一个样式，在1920 屏幕下会失效。

### ISSUE THREAD

**Issue by zynyy** [ant-design/ant-design#19508]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-matsumoto-dh3s7?fontsize=14)

### Steps to reproduce
1. 点击表格行 设置 class 
2. 在 1920 分辨率 鼠标移开会丢失 设置的 class

### What is expected?
鼠标离开表格行不要丢失 class

### What is actually happening?
丢失 设置的 class

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | window |
| Browser | Google Chrome 77.0.3865.120(64位) |

---

**Comment by afc163** [comment]
Please use `rowClassName`.
