### ISSUE TITLE
Table bug 

### ISSUE THREAD

**Issue by wenbinobject** [ant-design/ant-design#19507]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#scroll](https://ant.design/components/table-cn/#scroll)

### Steps to reproduce
添加
const scroll = {
  y: 370
}
添加滚动后 ant-table-tbody th和 ant-table-thead td 宽度不一致 导致样式错乱

### What is expected?
添加scroll 和不添加的时候一样 table 排列完整

### What is actually happening?
样式问题
![image](https://user-images.githubusercontent.com/21998076/67943573-3bd77700-fc15-11e9-8823-64fe12473431.png)

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | ant-table-tbody和ant-table-thead样式错乱 |
| System | mac 10.14.6 |
| Browser | chrome |

---
希望得到你的回复 微信WeChat ID: wenbinObject 可以详细聊

**Comment by afc163** [comment]
Please read documentation carefully.

**Comment by afc163** [comment]
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/507615/67944514-95d93c00-fc17-11e9-9830-3d55b492072c.png">

**Comment by wenbinobject** [comment]
if i add&nbsp;
const scroll = {
  y: 370
}









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"偏右"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月31日(星期四) 晚上7:51
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"海深灬不蓝"<273082441@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Table bug  (#19507)




Closed #19507.

**Comment by wenbinobject** [comment]
I don't have a lot of content In my sense I don't think that will happen。i know width="?px"  can solve this priblem。
