### ISSUE TITLE
How to fix TS issues for <a> 标签没有disable 属性？

### ISSUE THREAD

**Issue by TRUEJASONFANS** [ant-design/ant-design#19503]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-bpve8)

### Steps to reproduce
`
<a disabled={editingKey !== ''} onClick={() => this.edit(record.id)}>
                  Edit
</a>
`

### What is expected?
Type '{ children: string; disabled: boolean; onClick: () => void; }' is not assignable to type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
  Property 'disabled' does not exist on type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.ts(2322)

### What is actually happening?
Type '{ children: string; disabled: boolean; onClick: () => void; }' is not assignable to type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.
  Property 'disabled' does not exist on type 'DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>'.ts(2322)

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome |

**Comment by yoyo837** [comment]
`html5`规范里`a`没有没有`disabled`属性吧，当然不能用。

**Comment by TRUEJASONFANS** [comment]
@yoyo837  这段代码是antd 样例代码 我把它写在ts 里面。

**Comment by afc163** [comment]
https://stackoverflow.com/a/42803465/3040605
https://www.vincecampanale.com/blog/2018/01/12/dynamically-properties-to-typescript-interfaces/

可以试试

**Comment by CuriosityLxn** [comment]
Button 是有 disabled 属性的，我用 <Button type="link"></Button> 代替 <a> 标签规避了这个 lint。

**Comment by jackyr** [comment]
扩展React默认的A标签属性即可，index.d.ts：
```ts
import type { HTMLAttributes } from 'react';

declare module 'react' {
  interface AnchorHTMLAttributes<T> extends HTMLAttributes<T> {
    disabled?: boolean;
  }
}
```
