### ISSUE TITLE
Menu.Item 循环的问题

### ISSUE THREAD

**Issue by swim1986** [ant-design/ant-design#1950]
如题，
使用map循环Menu.Item最终生成的页面上样式错乱。
![image](https://cloud.githubusercontent.com/assets/8966984/15771003/45027b32-299a-11e6-964d-01079739758a.png)
下面是自己定义的MenuItem组件
![image](https://cloud.githubusercontent.com/assets/8966984/15771008/510ae8a6-299a-11e6-8cc5-4f3cb9345668.png)
最终生成的Dom
![image](https://cloud.githubusercontent.com/assets/8966984/15771025/77341016-299a-11e6-98ab-628b9ac0b1d1.png)
![image](https://cloud.githubusercontent.com/assets/8966984/15771032/7d9d205a-299a-11e6-8406-cc9f2916ed39.png)
请教，是不是我写错了？

**Comment by RaoHai** [comment]
为什么 map 的时候是  ` MenuItem ` 不是 ` Menu.Item ` 呢

**Comment by swim1986** [comment]
MenuItem是我自己写的组件，里面return的是menu.item

**Comment by swim1986** [comment]
如果写成这样是可以的，但是为什么不能写在另一个组件里。
![image](https://cloud.githubusercontent.com/assets/8966984/15771215/c813d786-299b-11e6-8802-c6e9d1aa2322.png)

**Comment by afc163** [comment]
你自己封装的 MenuItem 没有透传 prefixCls 等属性，丢失了信息。

**Comment by dxiuxiu** [comment]
你好，你的MenuItem 是怎么封装的，我也想做Menu.item的封装但是一直报错不成功
