### ISSUE TITLE
Header 组件嵌入 Menu 之后导致其他组件无法显示

### ISSUE THREAD

**Issue by ntop001** [ant-design/ant-design#19505]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
让 Header 组件像  flex 布局一样可以嵌入任意的其它组件

### What does the proposed API look like?
类似这样的布局：

`<header><img/> <menu></menu> <div>hello</div></header>
`

应该可以正常显示出 hello

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.

**Comment by ntop001** [comment]
@afc163 maybe you make some mistakes, it's not a bug. if close issue can help you reduce issues, just close it, keep happy, love life.

**Comment by afc163** [comment]
> 导致其他组件无法显示

You described this issue like a bug, we need online reproduce to find out what mistake we meet. So please using bug-report template instead of a feature request.

**Comment by ntop001** [comment]
@afc163 when I created the issue at  [https://new-issue.ant.design](https://new-issue.ant.design/)  , I choose feature not bug! You: "You described this issue like a bug,", it seems that the platform is useless, cause you will always judge the issue type by your personal opinion.
