### ISSUE TITLE
.ant-modal 多了个pointer-events: none，why??

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#19502]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不知道哪个版本更新加上的。因为之前使用的是3.17.0是没有这条属性的。之前modal里的select等getPopupContainer是设置在class: ant-modal上的。更新到最新版antd后导致无法操作了

### What does the proposed API look like?
是否可以移除掉pointer-events: none

**Comment by yoyo837** [comment]
ref: #17229

**Comment by gonenoob** [comment]
> ref: #17229

无法点击是因为有padding导致的吧，为什么要限制modal区域的点击行为？

**Comment by yoyo837** [comment]
来个在线的复现demo

**Comment by gonenoob** [comment]
> 来个在线的复现demo

https://codesandbox.io/s/crimson-moon-ipv8x

这个例子可以看ant-modal的样式，无法点击下面24px是因为padding

**Comment by yoyo837** [comment]
对啊，#17229 就是修复它的。你现在的问题是啥呢？

**Comment by gonenoob** [comment]
> 对啊，#17229 就是修复它的。你现在的问题是啥呢？

那个问题只用把padding去掉就可以修复的
多增加了pointer-events: none

**Comment by gonenoob** [comment]
> 对啊，#17229 就是修复它的。你现在的问题是啥呢？

多增加的pointer-events: none，导致了之前弹窗里Select无法选择，因为设置了getPopupContainer到ant-modal

**Comment by gonenoob** [comment]
> See: [a15b601](https://github.com/ant-design/ant-design/commit/a15b601e6d3b4e839f2728b6382c427bafe93fa9) 这24px加的比较早了，不太敢动呀。@afc163
> 
> @gonenoob 再来个
> 
> > 设置了getPopupContainer到ant-modal, Select无法选择
> 
> 的复现demo

https://codesandbox.io/s/mutable-wood-7i38c

**Comment by yoyo837** [comment]
得先弄清楚为什么保留24px， 包括 #17229 也在继续维护这24px，而不是去掉，不然我个人不太敢动，或者等 Owner 来处理。

**Comment by afc163** [comment]
https://codesandbox.io/s/condescending-mendel-g193d

建议 getPopupContainer 到一些自定义的固定 node 上。渲染到 antd 里的内建节点有风险，不确定未来会不会修改样式。

这个 24px 是为了保证滚到页面底部时 Modal 不会贴在底部，这样会很丑。

**Comment by gonenoob** [comment]
> https://codesandbox.io/s/condescending-mendel-g193d
> 
> 建议 getPopupContainer 到一些自定义的固定 node 上。渲染到 antd 里的内建节点有风险，不确定未来会不会修改样式或者类名。
> 
> 这个 24px 是为了保证滚到页面底部时 Modal 不会贴在底部，这样会很丑。

因为是在ConfigProvider统一配置的，getPopupContainer到modal是比较方便的做法了。如果使用自定义的话，每个modal都要做额外的处理了

**Comment by yoyo837** [comment]
@afc163 是不是可以换成 `margin-bottom` ?

**Comment by afc163** [comment]
`.ant-modal-body` 也比较好，本身是内容区域的节点，未来也不太可能加不可选择的样式。`.ant-modal` 本身是包括了 mask 的，渲染上来是有一定风险的。

**Comment by gonenoob** [comment]
ths，我现在的处理是加到ant-modal-content。


> `.ant-modal-body` 也比较好，本身是内容区域的节点，未来也不太可能加不可选择的样式。`.ant-modal` 本身是包括了 mask 的，渲染上来是有一定风险的。

ths，我现在的处理是加到ant-modal-content。
后面希望多考虑下风险问题...
现在升级版本的风险有点大
