### ISSUE TITLE
when valuePropName: 'value' setted, input doesn't work.

### ISSUE THREAD

**Issue by bestseob93** [ant-design/ant-design#19519]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-7p5y5](https://codesandbox.io/s/antd-reproduction-template-7p5y5)

### Steps to reproduce
input doesn't work

### What is expected?
input works

### What is actually happening?
initialValue setted and valuePropName: 'value' setted, input doesn't work

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.9 |
| System | macOS Catalina 10.15.1 |
| Browser | Chrome 78.0.3904.70 |

**Comment by bestseob93** [comment]
https://codesandbox.io/s/antd-reproduction-template-7p5y5

**Comment by afc163** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/507615/68004705-7d1b6580-fcad-11e9-82eb-a2ac6984e963.png">

Your codesandox does not reproduce the problem.
