### ISSUE TITLE
Anchor doesn't follow scroll position and doesn't jump

### ISSUE THREAD

**Issue by annache** [ant-design/ant-design#19513]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5lvmz)

### Steps to reproduce
I followed your example https://ant.design/components/anchor/

### What is expected?
Anchor follows scroll position and  jumps

### What is actually happening?
Anchor doesn't follow scroll position and doesn't jump

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.11.0 |
| System | Windws 10 enterprice  1803 |
| Browser | Chrome |

**Comment by afc163** [comment]
Your codesandbox works fine in my chrome, nothing jumps.

**Comment by annache** [comment]
@afc163 yes, when I click on link it doesn't jump, but it has to jump to necessary section.

**Comment by annache** [comment]
Here is reproduction link https://codesandbox.io/s/antd-reproduction-template-k48ts

**Comment by afc163** [comment]
It will works fine when open new window form codesandbox: https://k48ts.csb.app/

I believe it is a problem of codesandbox preview window.

**Comment by annache** [comment]
Thanks!
