### ISSUE TITLE
TreeSelect value incorrectly type-hinted

### ISSUE THREAD

**Issue by mindplay-dk** [ant-design/ant-design#19512]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-design-playground-p5lvj)

### Steps to reproduce
The value prop of TreeSelect is type-hinted (in TypeScript) as number[] - but attempting to fill it with a value such as [1,2,3] the TreeSelect does not work.

The onChange callback gives a value like [{ value: 1 }, { value: 2 }] so I attempted to pass something similar to the value-prop, and it does work - but now I get a TypeScript inspection saying the type { value: number } is not assignable to 'number'.

### What is expected?
The type-hint appears to be wrong - it probably should be { value: string; label?: string } or something like that?

### What is actually happening?
Failed inspection from TypeScript when passing object values similar to those returned to the onChange callback.

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.8.4 |
| System | Windows |
| Browser | Chrome 78 |

---

Images to show the TreeSelect control functioning correctly with value that fails inspection:

![image](https://user-images.githubusercontent.com/103348/67969288-4724a580-fc09-11e9-8a8c-d404a6afa366.png)

![image](https://user-images.githubusercontent.com/103348/67969307-51df3a80-fc09-11e9-9400-cdd7261034ce.png)

**Comment by afc163** [comment]
Could you try antd 4.x?

**Comment by mindplay-dk** [comment]
Well, the sandbox link is there, but I couldn't get it to build or run at all - and this is pretty low-priority for me right now, as I don't use and don't currently have plans to use antd, sorry...

**Comment by afc163** [comment]
😊 Thx for reporting anyway, I will reopen if anyone run into same issue.
