### ISSUE TITLE
table

### ISSUE THREAD

**Issue by Grafaceio** [ant-design/ant-design#19518]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-http-wmeog)

### Steps to reproduce
set table fixed and with less than screen

### What is expected?
Want to display normal

### What is actually happening?
table cell display chaos

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | last |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14545#issuecomment-465415548
