### ISSUE TITLE
ConfigProvider locale not working with Modal in some situation

### ISSUE THREAD

**Issue by Chastrlove** [ant-design/ant-design#19517]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-pine-smj3d)

### Steps to reproduce
将用ConfigProvider包裹的组件卸载，会导致Modal.confirm组件的locale失效(父组件已用ConfigProvider包裹)

### What is expected?
Modal.confirm 永远受最新的ConfigProvider 影响

### What is actually happening?
当程序中存在两个LocaleProvider 的时候，当一个被卸载，另一个无法影响modal.confirm 这种类型的组件的locale

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.10.0 |
| System | macOS Catalina |
| Browser | chrome 78.0.3904.70 |

---
```javascript
//locale-provider index.tsx
 componentWillUnmount() {
    changeConfirmLocale();
  }

//原因是因为Modal中的locale.tsx 在LocaleProvider被卸载时被置为undefined
export function changeConfirmLocale(newLocale?: ModalLocale) {
  if (newLocale) {
    runtimeLocale = {
      ...runtimeLocale,
      ...newLocale,
    };
  } else {
    runtimeLocale = {
      ...defaultLocale.Modal,
    };
  }
}

export function getConfirmLocale() {
  return runtimeLocale;
}

```

**Comment by yoyo837** [comment]
用俩`ConfigProvider`的考虑是想局部使用另一种配置？

**Comment by Chastrlove** [comment]
是的，局部定义某个组件的配置

**Comment by lileilei** [comment]
我设置了okText: "确认", cancelText: "取消", 偶现 竟然变成了英文。太神奇了。目前没找到原因，正在排查！！！

**Comment by Chastrlove** [comment]
any progress ？

**Comment by akaguny** [comment]
> 我设置了okText: "确认", cancelText: "取消", 偶现 竟然变成了英文。太神奇了。目前没找到原因，正在排查！！！ antd： v3.23.6

on English please

**Comment by ohhoney1** [comment]
had same problem.
any update?

**Comment by afc163** [comment]
Resolved by https://github.com/ant-design/ant-design/pull/20949

**Comment by albert-cai** [comment]
@afc163 it hasn't been fixed in 3.x version. Merge request was applied into antd4 version.

**Comment by VoliBearCat** [comment]
@afc163 3.X遇到同样的问题, 会在3.X版本解决吗?

**Comment by VoliBearCat** [comment]
> @zombieJ @afc163 3.X遇到同样的问题, 会在3.X版本解决吗?

这里提供一种临时的解决思路, 留给遇到同样问题的小伙伴
![image](https://user-images.githubusercontent.com/11676384/79406617-217a3580-7fca-11ea-8872-5ead802fa446.png)

ConfigProvider卸载后, 创建一个新的ConfigProvider放到DOM上

**Comment by MinJieLiu** [comment]
4.20 问题依然存在

**Comment by xiaodun** [comment]
可以看下这篇文章   [Umi2.x 中Modal.confirm底部按钮显示为中文](https://www.jianshu.com/p/3968ce87c1b7)
