### ISSUE TITLE
DatePicker onChange prop receiving unexpected and inconsistent inputs arguments to callback function

### ISSUE THREAD

**Issue by dhassouni** [ant-design/ant-design#19516]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ui2xq)

### Steps to reproduce
Change the date of each of the two DatePickers to any day, let's say 2019-10-31. Observe the console log. Note that the first DatePicker with no value prop shows the date and dateString as having matching date portions (2019-10-31). The date is a moment, and thus also includes a time component. 

Note that the second DatePicker with a value prop defined shows the date and dateString as having different date portions. The date is a moment with a date portion still at the date of the value passed in (2019-01-01), but the dateString has a date matching the newly selected date (2019-10-31)

### What is expected?
First and foremost, I believe the date and dateString should match. It does not make sense to have a callback where the two values diverge. This is where you would handle what you want to do with the new date, but it is only passing me the previous date. A common use case here would be to have redux update the store with the new `date` value in the callback.

### What is actually happening?
When the value prop is passed to DatePicker, it does not update the `date` argument passed to the onChange callback, but it does for the `dateString` argument.

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | React@16.10.2 |
| System | Mac OS Mojave (10.14.6) |
| Browser | Google Chrome Version 77.0.3865.120 (Official Build) (64-bit) |

---
I ran into this bug because my redux store update would not change the date as I had anticipated. Diving in, I noticed that the date and dateString diverged when using the value prop. Note that I encounter the same issue if I use defaultValue instead of Value for a prop.

**Comment by afc163** [comment]
It is correct behavior of React controlled component.

**Comment by dhassouni** [comment]
@afc163 can you please elaborate? I have waited for over half a year on this, but the response just says that is expected without any details. I do not understand why one would expect the date and date string to diverge. I viewed the datestring as a convenience prop to the onchange more than one we would expect to have a different value than the date input argument.

**Comment by afc163** [comment]
You can try this demo: https://codesandbox.io/s/antd-reproduction-template-12w3e?file=/index.js

Compare two input in this demo, typing `2` in each, you can see the second one works like DatePicker with `value`.

Check `uncontrolled` and `controlled` component in React docs:

- https://reactjs.org/docs/uncontrolled-components.html
- https://reactjs.org/docs/forms.html#controlled-components

**Comment by dhassouni** [comment]
@afc163 Thank you for diving into this in more detail for me. I think the source of the problem was my understanding of what the `dateString` represents. After reading your explanation, it sounds to me like it is intended to be a passthrough of the user input. I had not thought of it like that (I stated in my opening of the case that I thought it was a "convenience prop" - i.e. a formatted string removing the need to manipulate a moment). I guess this interpretation error is my fault, but I think the documentation could be improved - there is almost no documentation of the props passed to the callback other than their types. 

I also recognize the problem with my reproduction example. In reality, I did not have the input as a hard-coded value but was trying to come up with a simpler example as my application was using redux to manage state - and one of those pieces of state was the date. As such, you need to pass down the value when the component re-renders so it has the date filled in. In effect, it was a controlled component, but connected via react-redux.

It has been long enough that I can't recall the original example where I hit a problem so I'll have to do a better job of creating a reproduction that is more representative of my situation going forward. Thanks again.
