### ISSUE TITLE
Icon自定义component图标 颜色需求

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#19527]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决在使用自定义图标时可以随意的选择颜色。而不是固定的颜色，
另一个问题如何在使用icon的下 怎么使用hover变色

### What does the proposed API look like?
在使用自定义图标时可以传入颜色。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13137#issuecomment-472456561
