### ISSUE TITLE
Upload warning

### ISSUE THREAD

**Issue by kelvin1984** [ant-design/ant-design#19524]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-nvltl)

### Steps to reproduce
Warning: [antd: Upload] `value` is not validate prop, do you mean `fileList`? 

### What is expected?
no warning

### What is actually happening?
Warning: [antd: Upload] `value` is not validate prop, do you mean `fileList`? 

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.8  |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/18497

Please search `options.valuePropName` in https://ant.design/components/form-cn/

**Comment by kelvin1984** [comment]
sorry，My fault

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10277#issuecomment-518089919

**Comment by nameJw** [comment]
`
<Form.Item label='avatar' valuePropName='fileList'>
    <Upload />
</Form.Item>
`
这样写吗？可还是报警告：
Warning: [antd: Upload] `value` is not a valid prop, do you mean `fileList`? 

"antd": "^4.6.3",
"react": "^16.13.0",

ant-design-pro 4.x
System: windows
Browser: chrome

>
