### ISSUE TITLE
Tree组件，我一个节点下面大约有1000多个子节点 。在展开和选择时候，页面非常卡顿

### ISSUE THREAD

**Issue by DawnL6** [ant-design/ant-design#19522]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree组件，我一个节点下面大约有1000多个子节点  ,操作非常卡顿，希望能有方案解决这个问题，或者能够提供解决思路 不胜感激。

### What does the proposed API look like?
暂无

**Comment by afc163** [comment]
Duplicate of #3789

**Comment by Mathround** [comment]
> Duplicate of #3789

我进去看了半天也没找到怎么关于优化Tree的东西，难道用这个react-virtualized？

**Comment by zombieJ** [comment]
v4 自带虚拟滚动，设置 `height` 即可

**Comment by wxf-start** [comment]
v4 自带虚拟滚动，设置 height 即可，可以解决，但是他没办法设置横向滚动条啊，感觉这个组件设计有所欠缺

**Comment by zombieJ** [comment]
嗯，虚拟滚动后，就不知道最深的节点会占多宽了。这的确是一个缺陷。

**Comment by Jeggery** [comment]
我也在找这个解决方案

**Comment by RGideonX** [comment]
请问V3，没有虚拟滚动，有好的办法解决页面卡顿吗？

**Comment by RGideonX** [comment]
> v4 自带虚拟滚动，设置 即可`height`
大佬，请求帮助呀，Antd3的版本没有虚拟滚动，多子节点页面卡顿，有解决办法吗？
