### ISSUE TITLE
RangePicker控件我设置的时间格式format="yyyy/MM/dd HH:mm:ss"，为何提交的时候时间格式是Mon Jun 27 2016 15:22:23 GMT+0800 (中国标准时间)，而不是类似于2016-01-01 15:22:23的格式呢？

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#1952]

**Comment by afc163** [comment]
。。。这样的标题让人怎么阅读呢。

**Comment by aw6658913** [comment]
这样写看不懂吗？不然我删掉重新写下 把描述写在下面？其实主要就是日期格式的问题，我打印出来发现跟我设置的格式是不一样的

**Comment by afc163** [comment]
issue 可以修改的。

**Comment by afc163** [comment]
http://ant.design/components/date-picker#RangePicker

注意 onChange 的两个参数。你打出来的是标准的 Date 对象。https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

另外，学习下 [提问的智慧](http://doc.zengrong.net/smart-questions/cn.html) 吧，有好处。
