### ISSUE TITLE
for some properties it is better to use not a short record, in a few detailed

### ISSUE THREAD

**Issue by bezdna** [ant-design/ant-design#19530]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If I suppose I want to make a border with an input only on one side, then I use this option:
border: @border-width-base @border-style-base @input-border-color;, it will not be possible using the structure and variables stored in the design system
separate properties must be used:
border-color: @border-width-base
border-style: @border-style-base;
border-width: @input-border-color;

### What does the proposed API look like?
separate properties must be used:
border-color: @border-width-base
border-style: @border-style-base;
border-width: @input-border-color;

**Comment by afc163** [comment]
Done in antd v4.
