### ISSUE TITLE
动态添加删除checkbox value属性,完全删除后状态不对称

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design#19531]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-gix2q)

### Steps to reproduce
点击添加，在点击删除

### What is expected?
value属性移除后对应checkbox选中消失

### What is actually happening?
value属性移除后对应checkbox选中未消失

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-wvomu

受控模式要稳定，不能一会有 value 一会没有。
