### ISSUE TITLE
Table固定列是否必须放在columns数组头部或尾部？

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#19532]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ui70o?fontsize=14)

### What is expected?
fixed 列课出现在任意位置

### What is actually happening?
`fixed: 'right'`如果不在最后会导致样式问题

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.11 |
| System | Windows 10 |
| Browser | 78.0.3904.70 |

---
当需要动态拼接`columns`时需要注意fixed列是否在正确位置，这是设计如此吗？如果是，是不是需要修改下文档？
![image](https://user-images.githubusercontent.com/23520283/68065098-22dadd00-fd5f-11e9-8601-8c6783351499.png)

**Comment by yoyo837** [comment]
我个人看法是，固定列只保留一个方向，比如靠左，固定的按顺序fixed起来，整体占用左侧一定的空间，其他列照常排列、左右滚动！

**Comment by yoyo837** [comment]
比如1-10列，设置固定，2、6、8，则2、6、8靠一起fixed在左侧，1、3、4、5、7、9、10靠一起常规排列在背后。

**Comment by Liu-Ya** [comment]
> 我个人看法是，固定列只保留一个方向，比如靠左，固定的按顺序fixed起来，整体占用左侧一定的空间，其他列照常排列、左右滚动！

业务上只保留一个方向不合适吧？ 比如操作列和标识列

**Comment by afc163** [comment]
对，需要保持顺序，中间某列固定在右边是很奇怪的语义。

**Comment by yoyo837** [comment]
我觉得操作列不是问题，大不了把它也加入fixed，我个人也觉得比两边fixed要好，且实现复杂度也会低很多，不知道有没有和我同样想法的人！🤔

**Comment by yoyo837** [comment]
Just for ref: https://github.com/ant-design/ant-design/issues/17151#issuecomment-502975150
