### ISSUE TITLE
upload 组件添加【选中状态】功能

### ISSUE THREAD

**Issue by wufangjian** [ant-design/ant-design#19548]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
上传多张图片后，我可以【选中】其中一张图，或多张图片进行操作。 比如为每一张图片添加描述信息。

### What does the proposed API look like?
自己实现这个功能相对比较麻烦，如果能从 API 层面支持就更好了。

1.添加一个【是否选中】状态属性。并支持onSelected回调函数。

![image](https://user-images.githubusercontent.com/6982055/68099085-7d10a500-fefb-11e9-9efb-b3e56c8e8c5a.png)

**Comment by afc163** [comment]
Merged into #16047
