### ISSUE TITLE
table中filters筛选菜单没有滚动条

### ISSUE THREAD

**Issue by mgoann** [ant-design/ant-design#19542]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit modest-cloud-fv3d9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-cloud-fv3d9?fontsize=14)

### Steps to reproduce
点击name列的筛选按钮

### What is expected?
如果内容过多，自动出现滚动条，而不是全部展示出来

### What is actually happening?
没有任何滚动条，下来菜单占满整个屏幕，体验非常不好

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.7.0 |
| System | window |
| Browser | chrome版本 70.0.3538.77 |

**Comment by xrkffgg** [comment]
```
.ant-table-filter-dropdown .ant-dropdown-menu {
    max-height: 500px;
    overflow-y: auto;
}
```

这里你可以在自己项目中增加个自定义样式，具体高度看自己合适了
