### ISSUE TITLE
spin 加载时自定义文本遮罩高度不够

### ISSUE THREAD

**Issue by suxi-lu** [ant-design/ant-design#19541]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以选中遮罩下的输入元素

### What does the proposed API look like?
可以完全遮罩全屏的元素，最好可以调整加载提示信息距屏幕顶部的高度(现在是居中显示)

**Comment by suxi-lu** [comment]
这个是示例，主要是modal 的index 1000 和spin的index 10
一开始发现的是text的文本高度400px超过400 也可以遮罩

https://codesandbox.io/s/antd-reproduction-template-skem7

**Comment by afc163** [comment]
Modal 本身不占据 body 页面空间的，相当于 Spin 只包裹住了 Button。这种情况和 antd 关系不大，需要你自行设定好全屏 loading 的空间。
