### ISSUE TITLE
<Silder>和<Menu>组件手动设置openKeys后，样式错乱

### ISSUE THREAD

**Issue by kyo4311** [ant-design/ant-design#19552]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-montalcini-bjkuv?fontsize=14)

### Steps to reproduce
1. 点击User菜单
2. 点击底部折叠按钮

### What is expected?
可以正确显示二级菜单

### What is actually happening?
二级菜单显示的位置不正确

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | React |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
受控模式需要你完全控制属性：https://codesandbox.io/s/inspiring-jones-zq8su
