### ISSUE TITLE
自定义 font 图标，不能额外自定义class

### ISSUE THREAD

**Issue by wlfei0502** [ant-design/ant-design#19551]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-unwfc?fontsize=14](https://codesandbox.io/s/antd-reproduction-template-unwfc?fontsize=14)

### Steps to reproduce
第一步：自定义iconfont图标
const IconFont = Icon.createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/font_1480569_9kv2a7p2gcw.js',
    extraCommonProps:{
        className: 'iconfont'
    }
});

export default IconFont;

第二步：使用该图标
<IconFont type={'icon-visual'} className={'icon-visual'} />

### What is expected?
自定义类名icon-visual，可以融入到组件<IconFont>中

### What is actually happening?
当配置了
extraCommonProps:{
        className: 'iconfont'
    }，之后 icon-visual类名无法加到组件中。不配置共通类名的情况下是可以自定义类名的

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.10.2 |
| System | window 10 |
| Browser | chrome 73.0.3683.103 (64位） |

**Comment by yoyo837** [comment]
挂梯子，基本技能。

**Comment by wlfei0502** [comment]
已创建codesandbox，链接地址：https://codesandbox.io/s/antd-reproduction-template-unwfc?fontsize=14

**Comment by afc163** [comment]
是个 Bug，直接来 PR 吧

**Comment by yoyo837** [comment]
` <Icon {...restProps} {...extraCommonProps}>`  `extraCommonProps` 应该放前面
