### ISSUE TITLE
Input组件在FormItem中所占高度变为33px

### ISSUE THREAD

**Issue by freedom12** [ant-design/ant-design#1955]
## 你做了什么？

一个Form中的Input组件在设置addonBeafore前后高度不一致
当不设置时高度为33px
当设置时高度为32px

## 你期待的结果是：
input组件高度应该统一为32px
这样在切换状态时不会产生抖动

## 可重现的在线演示

官网的Form例子就是这样

**Comment by benjycui** [comment]
有无 `addon` 都是 32px 哦 http://ant.design/components/form#components-form-demo-input-group

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by freedom12** [comment]
之前表达有误 是将input放入FormItem中
input外层的div .ant-form-item-control高度会在增加addonBefore前后高度有1px变化

**Comment by afc163** [comment]
整理了一下你发的例子：http://codepen.io/anon/pen/ZObmmj?editors=001
