### ISSUE TITLE
Progress of type line is not effective in Descriptions

### ISSUE THREAD

**Issue by dengfuping** [ant-design/ant-design#19554]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/progress-in-descriptions-ymk0l)

### Steps to reproduce
- See the demo.
![image](https://user-images.githubusercontent.com/14918822/68103627-9d982980-ff12-11e9-97c4-8542bdd89281.png)

### What is expected?
- Progress of type line could be rendered.

### What is actually happening?
- Progress of type line is not rendered.

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.11.0 |
| System | Mac OS |
| Browser | 78.0.3904.70 |

**Comment by afc163** [comment]
Fixed in 4.16.0

https://codesandbox.io/s/progress-in-descriptions-ymk0l?file=/index.js
