### ISSUE TITLE
Table component doesn't allow custom sort icons

### ISSUE THREAD

**Issue by joeheyming** [ant-design/ant-design#19561]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Our team is using Ant tables, but we would like to change the sort icon to be an arrow instead of a triangle.  We were wondering if we could send the sort icon via a prop type, but we could not find any prop type that satisfies this.

### What does the proposed API look like?
`<Table sortUpIcon={<MyIconAscend />}  sortDownIcon={<MyIconDescend />} sortNoneIcon={<MyIconNoSort />} />`

**Comment by zjoshi** [comment]
Hi, newbie here, I would like to look into this if I may.

**Comment by Haqverdi** [comment]
have same issue
any possible ways?

**Comment by M7Arman** [comment]
I have the same issue too.

**Comment by govi74** [comment]
Any updates???

**Comment by zohaib-enquizit** [comment]
Need this feature.

**Comment by reload07** [comment]
.ant-table-column-sorter {
      visibility: collapse;
}

**Comment by muralimallow** [comment]
Any updates?

**Comment by SoumyoNawab8** [comment]
Any update on this?

**Comment by chathurabuddi** [comment]
Any updates?

**Comment by EvgeniiFaleev** [comment]
Any updates?

**Comment by NamJiwony778** [comment]
Any updates?

**Comment by ldv-orbyta** [comment]
any updates?

**Comment by arthurdenner** [comment]
I looked into this feature recently and noticed the current implementation has a sortDown and a sortUp icon.
I was wondering if we should keep the same or change it to support a sortNone prop as the OP suggested.

@afc163, I'd appreciate your input into the desired API.
For those interested, [this commit](https://github.com/arthurdenner/ant-design/commit/bd16fa91bd915764d2326553fc4c6b5202acb829) has some changes to support `sortDownIcon` and `sortUpIcon` props keeping the default as it is today.

**Comment by bathinaMounika** [comment]
@arthurdenner 
When will this be available in antd?

**Comment by curly210102** [comment]
@afc163 Maybe provide a render props (sortByAscend: boolean) => ReactNode?

**Comment by E1emN** [comment]
any updates??

**Comment by sawadyecma** [comment]
To follow the implementation of the current sortIcon, we should design API like below.

```
sortDownIcon?: (sortOrder: SortOrder) => React.ReactNode)
sortUpIcon?: (sortOrder: SortOrder) => React.ReactNode)
```

However it seems to be a little complicated therefore I would like to implement API like below and refactor the logic in useSorter.tsx

```
sortIcon?: (sortOrder?: SortOrder) => React.ReactNode)
```

To refactor like this, I must know the parts which would be affected.

Would you let me know iyou have any ideas.

**Comment by joeheyming** [comment]
That implementation seems right to me @sawadyecma

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/42498
