### ISSUE TITLE
Hide Edit Icon in Paragraph.Typography

### ISSUE THREAD

**Issue by roeljohn** [ant-design/ant-design#19562]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I like to create my own way on how to open edit ui instead of click edit icon. Even though I can hide it in CSS maybe you can give a better way to do it

### What does the proposed API look like?
Gave the ability of the user to create there own edit function

**Comment by yoyo837** [comment]
For example, `onStart` return false as to prevent the internal default edit mode?

Let us know what your proposed API is like?

**Comment by roeljohn** [comment]
as you can see here
![image](https://user-images.githubusercontent.com/8347743/68176917-8c5a2600-ffc1-11e9-89fe-81b02832e316.png)
I already had a edit comment in dropdown since I already had that I don't need the edit icon anymore

**Comment by yoyo837** [comment]
`editable={false}` This should be what you want.

**Comment by yoyo837** [comment]
If you have any other questions related this, please feel free to open a new issue.

**Comment by afc163** [comment]
Maybe we can add a icon for customzition:

```diff
<Paragraph
  editable={{
+   icon: <Icon type="xxx />,
  }}
>
```

**Comment by roeljohn** [comment]
> Maybe we can add a icon for customzition:
> 
> ```diff
> <Paragraph
>   editable={{
> +   icon: <Icon type="xxx />,
>   }}
> >
> ```

Yap this should work =)

**Comment by shaodahong** [comment]
Maybe like this, `editable` can also be `React.ReactElement`

```jsx
<Paragraph
  editable={<Icon type="xxx />}
>
```

**Comment by afc163** [comment]
Also we should support to custom copyable button:

```diff
<Paragraph
  copyable={{
+  icon: <Button>复制代码</Button>,
  }}
>
```
