### ISSUE TITLE
Transfer  listStyle 样式报错

### ISSUE THREAD

**Issue by ywww** [ant-design/ant-design#19565]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://nome](http://nome)

### Steps to reproduce
                <Transfer
                    dataSource={dataSource}
                    showSearch={true}
                    listStyle={{
                        width: 250,
                        height: 300,
                    }}
                    titles={[leftTitle, rightTitle]}
                    targetKeys={targetKeys}
                    onChange={this.handleChange}
                    render={(item) => `${item.title}`}
                    footer={this.renderFooter}
                />

                    listStyle={{
                        width: 250,
                        height: 300,
                    }}

TS2322: Type '{ width: number; height: number; }' is not assignable to type '(style: ListStyle) => CSSProperties'.
  Object literal may only specify known properties, and 'width' does not exist in type '(style: ListStyle) => CSSProperties'.

### What is expected?
ts应该不报错呀

### What is actually happening?
报错

TS2322: Type '{ width: number; height: number; }' is not assignable to type '(style: ListStyle) => CSSProperties'.
  Object literal may only specify known properties, and 'width' does not exist in type '(style: ListStyle) => CSSProperties'.

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | win10 |
| Browser | chrome 78.0.3904.87 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/19330/files#r342373678

这里写错了，来个 PR 吧~

**Comment by afc163** [comment]
cc @lxnxbnq
