### ISSUE TITLE
Modal组件能提供最大化的功能吗？

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design#19566]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Modal组件能提供最大化的功能

### What does the proposed API look like?
Modal组件能提供最大化的功能

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/16613#issuecomment-492902226
