### ISSUE TITLE
Cannot customize 'trigger' of Layout Sider when collapsedWidth={0}

### ISSUE THREAD

**Issue by plainnany** [ant-design/ant-design#19571]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-voice-r452j)

### Steps to reproduce
set `collapsedWidth=0 trigger={<Icon type="setting" />}`

### What is expected?
icon should replace default trigger

### What is actually happening?
it doesn't change  custom

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | latest |
| System | Mac OS 10.14.2 |
| Browser | chrome 77.0.3865.120 |

---
I found similar [issue 11153](https://github.com/ant-design/ant-design/issues/11153)，but it closed, and I read [code](https://github.com/ant-design/ant-design/blob/master/components/layout/Sider.tsx#L206), I found when `collapsedWidth=0`，`trigger` is not set custom trigger first, is this a question?

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/68262170-672aed80-007d-11ea-99df-95546191dc3d.png)

**Comment by yoyo837** [comment]
Your understanding is wrong. If you want to use a trigger, the collapsedWidth must be greater than 0, regardless of whether it is custom or not.
