### ISSUE TITLE
InputNumber support only 6 decimal places

### ISSUE THREAD

**Issue by joanna2014** [ant-design/ant-design#1957]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

```
const latitudeProps = getFieldProps('latitude', {
            rules: [{required: true, type: 'float', message: 'Latitude cannot be empty'}],
        });
<InputNumber min={0} max={90} step={0.0000000001} {...latitudeProps} id="latitude"
                                         placeholder="Please enter 0 - 90" style={{ width: '100%' }}/>
```

## What you would like to happen

enter in InputNumber   23.1234567891

## What actually happened

23.1234567891 to 23 , error:Latitude cannot be empty

## Environment Information

- antd v1.1.0
- Windows 10 
- Chrome 50.0.2661.102(64-bit)):

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/681

**Comment by afc163** [comment]
欢迎 PR ~

**Comment by afc163** [comment]
暂不支持，有大数字的需求可以直接 PR ~
