### ISSUE TITLE
dropdown Menu.ItemGroup style mess

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design#19576]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

![image](https://user-images.githubusercontent.com/5318333/68201916-ab76a900-fffd-11e9-84af-35b0c590434e.png)

### Reproduction link
[http://riddle.alibaba-inc.com/riddles/a7e9645c](http://riddle.alibaba-inc.com/riddles/a7e9645c)

### Steps to reproduce
use Menu.ItemGroup under Dropdown > Menu

### What is expected?
The padding and list-style of Menu.ItemGroup should be correct

### What is actually happening?
The padding of ItemGroup is strange, looks like antd doesn't take control the style

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | * |
| System | * |
| Browser | * |

**Comment by yoyo837** [comment]
这位阿里的同志，内网链接，其他同志望尘莫及啊！

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/19150 didn't fix it...
