### ISSUE TITLE
<Column>上使用sorter会无限循环导致程序崩溃

### ISSUE THREAD

**Issue by HHChaos** [ant-design/ant-design#19589]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://无，工作项目中发现，之后补充](http://无，工作项目中发现，之后补充)

### Steps to reproduce
1、使用 JSX 风格的 API的包装数据（使用<Column>组件而非columns={columns}的方式），隐藏Header；
2、设置某一列上的sorter，并且设置sortOrder为true（或者其他有效值）。

### What is expected?
数据按所在列上的排序规则排序显示

### What is actually happening?
排序函数无限循环，导致程序崩溃

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.9.9 |
| System | macOS Catalina |
| Browser | Chrome 78 |

---
在不使用 JSX 风格的 API，转而使用columns={columns}的方式来展示数据的case下不会发生这个错误

**Comment by afc163** [comment]
Duplicate of #19443

Fixed in #19558
