### ISSUE TITLE
form.resetField does not effect Checkboxes

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#19580]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-night-7mdct)

### Steps to reproduce
1. Enter any value for User Name and Password
1. Click the checkbox to 'Remember Me'
1. Click 'Log in'

### What is expected?
Both input fields and the checkbox values are reset

### What is actually happening?
The input fields values get cleared out but the checkbox remains checked.

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.10.0 |
| System | any |
| Browser | any |

**Comment by yoyo837** [comment]
```js
{getFieldDecorator("remember", {
    + valuePropName: 'checked', // add this line, man...
})(<Checkbox>Remember Me</Checkbox>)}
```
