### ISSUE TITLE
Descriptions doesnt align on smaller screens

### ISSUE THREAD

**Issue by ntselishchev** [ant-design/ant-design#19584]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/descriptions/](https://ant.design/components/descriptions/)

### Steps to reproduce
open large text description on small screen (iphone 5/SE)

### What is expected?
mobile-friendly responsive descriptions container

### What is actually happening?
description table content overlaps container border

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | any |
| System | any |
| Browser | any |

**Comment by ntselishchev** [comment]
![image](https://user-images.githubusercontent.com/42913137/68246956-e93df680-002a-11ea-87d8-46858b03e4d4.png)

**Comment by afc163** [comment]
```diff
<Descriptions.Item label="Config Info">
+ <div style={{ wordBreak: 'break-all' }}>
    Data disk type: MongoDB
+ </div>
</Descriptions.Item>
```
