### ISSUE TITLE
Implementation .NET Razor

### ISSUE THREAD

**Issue by kal-el52** [ant-design/ant-design#19583]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi, I have a question. If I wanted to implement the Ant Design styles, for NET, where do I get the base style? HTML, CSS and JS.
Where can I download a base template, without it being tied to the React, Angular or Vue implementation.

Regards.

### What does the proposed API look like?
download html, css and js

**Comment by afc163** [comment]
Sorry, we have no plan for plain html/css/js implementation.
