### ISSUE TITLE
Popover's hover  doesn't work when using a single component.

### ISSUE THREAD

**Issue by jssullivan** [ant-design/ant-design#19585]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/falling-cherry-x41o4?fontsize=14)

### Steps to reproduce
1. Create a Functional Component
2. Render the Component in a Popover
3. Attempt to hover the Functional Component. See that the hover doesn't work.

### What is expected?
Hover should work on this single component.

### What is actually happening?
The hover doesn't work.

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | 16.11.0 |
| Browser | Firefox 71, Chrome 78 |

---
I included a workaround in the Code Sandbox which adds a span to get the hover to work.

Strangely this works with the hover
```
<Popover>
  <Button />
</Popover>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15909

---

https://github.com/ant-design/ant-design/issues?q=is%3Aissue+label%3A%E2%9D%93FAQ+is%3Aclosed

**Comment by afc163** [comment]
Please search FAQ before file new issue.

<img width="59" alt="image" src="https://user-images.githubusercontent.com/507615/68263351-c4746e00-0080-11ea-8ee8-5ca88b130bb4.png">
