### ISSUE TITLE
form require:true 不能检测空格

### ISSUE THREAD

**Issue by pingmouren** [ant-design/ant-design#19595]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[ https://codepen.io/hzzlyzz/pen/gOOWQNx?editors=0010]( https://codepen.io/hzzlyzz/pen/gOOWQNx?editors=0010)

### Steps to reproduce
谢谢

### What is expected?
全是空格的话校验为空

### What is actually happening?
全是空格的话校验通过

| Environment | Info |
|---|---|
| antd | 3.19.4 |
| React | 16.8.1 |
| System | windows7 |
| Browser | Chrome70 |

**Comment by yoyo837** [comment]
空格也是字符串，满足填写要求，要不要空格应该是业务上的事情。

**Comment by xrkffgg** [comment]
我觉得自己在前台控制下比较好
