### ISSUE TITLE
React项目中：当我设置父容器postion: fixed时，antd table pagination的显示列表被固定在底部的div遮盖。

### ISSUE THREAD

**Issue by JeanZhao** [ant-design/ant-design#19590]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2x.ant.design/components/pagination/](https://2x.ant.design/components/pagination/)

### Steps to reproduce

<div style={{postion: fixed, top: 0px}}>
    <div>
      <Table pagination={getPagination()} />
    </div>
</div>
<div style={{postion: fixed, bottom: 0px}}>
{...}
</div>

其中getPagination定义：
const getPagination = () => {
return {
        total: total,
        showTotal:(total)=>{return `总数 ${total} 条`},
        current: pageNumber,
        pageSize: .pageSize,
        onChange(page) {... },
        showSizeChanger: true,
        pageSizeOptions: ['10', '100'],
        onShowSizeChange(curPage, pageSize) {... },
}
}

### What is expected?
antd table pagination的显示列表不会被固定在底部的div遮盖。

### What is actually happening?
antd table pagination的显示列表被固定在底部的div遮盖。

| Environment | Info |
|---|---|
| antd | v2.x |
| React | 0.14.0 |
| System | windows |
| Browser | chrome 78.0.3904.70 |

---
使用场景：滚动整个浏览器窗口的滚动条时，需要置顶table，方便用户查看更多内容。
版本：antd v2.x.（因为一些原因，所以不能直接升级v3.x.）

**Comment by JeanZhao** [comment]
提供的链接打不开，没法提供online.
麻烦先看一下我贴的代码，我觉得这些描述已经足够清楚了~

**Comment by JeanZhao** [comment]
给国外团队提issue的时候，人家都不会因为我没有提供Online demo而卡着不继续分析我的问题描述。。。难道没有提供online demo就不给分析问题么

**Comment by afc163** [comment]
由于我们的水平问题，没有 online demo 很有可能找不到是哪里出问题了。

**Comment by mxdneu** [comment]
这个问题我也遇到，还有没有解决方案吗
