### ISSUE TITLE
table default text-align

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#19592]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前想要表格单元格居中，只能设置`column.align`，想要所有表格居中，设置太繁琐

### What does the proposed API look like?
1. 提供一个less变量
2. configProvider
3. table增加一个align属性，可以被Column的align覆盖

**Comment by zlab** [comment]
为什么我的样式优先级没有antd的高？

![image](https://user-images.githubusercontent.com/2288630/68269265-17a3ec00-0094-11ea-87bd-027becec42d1.png)

![image](https://user-images.githubusercontent.com/2288630/68269194-d90e3180-0093-11ea-977f-8fb38a5e38b3.png)

**Comment by afc163** [comment]
建议自行搞一个高层的 Table 来统一封装行为。
