### ISSUE TITLE
Select onBlur Type error

### ISSUE THREAD

**Issue by dolphinlin** [ant-design/ant-design#19591]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L71](https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L71)

### Steps to reproduce
- 

### What is expected?
應該要與 onFocus 為一樣的type

### What is actually happening?
onBlur?: (value: T) => void;
onFocus?: () => void;

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | all |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
按这个定义，onBlur 是有当前值的，应该不是问题。

**Comment by dolphinlin** [comment]
> 按这个定义，onBlur 是有当前值的，应该不是问题。

可是文件上面是沒有的

**Comment by dolphinlin** [comment]
![image](https://user-images.githubusercontent.com/15712556/68270583-a450a900-0098-11ea-896f-8472b6f8e1dd.png)

**Comment by afc163** [comment]
可以发个 PR 帮我们补上~ 😁

**Comment by dolphinlin** [comment]
最主要會發現這問題 是因為用 `React-Final-Form` 客製自己得 `Component`
把 `onBlur` 放進去會發現 `Type` 錯誤 所以想要請問前輩 在 `params` 放入 <T> 是為了什麼嗎？
因為這樣應該是不正規的

**Comment by yoyo837** [comment]
它在这里被添加。#12865
