### ISSUE TITLE
Tooltip bug 动态效果展示问题

### ISSUE THREAD

**Issue by wenbinobject** [ant-design/ant-design#19598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tooltip-cn/](https://ant.design/components/tooltip-cn/)

### Steps to reproduce
        <Input
          placeholder=""
          className="scan"
          allowClear
          onPressEnter={onPressEnter}
          suffix={
            <Popover  trigger="click" placement="bottom" 
              visible={visible}
              onVisibleChange={handleVisibleChange}
              content={
                visible?
               test
                :null
                }
              >
              <i className="svg-scan">
                <svg  xmlns="http://www.w3.org/2000/svg"  width="14.583" height="14" y="5" viewBox="0 0 14.583 14">
                  <path id="Path_75" data-name="Path 75" d="M55.295,77.81h1.021a.146.146,0,0,0,.146-.146V74.455H59.67a.146.146,0,0,0,.146-.146V73.289a.146.146,0,0,0-.146-.146H56.388a1.239,1.239,0,0,0-1.24,1.24v3.281A.146.146,0,0,0,55.295,77.81Zm9.333-3.354h3.208v3.208a.146.146,0,0,0,.146.146H69a.146.146,0,0,0,.146-.146V74.382a1.239,1.239,0,0,0-1.24-1.24H64.628a.146.146,0,0,0-.146.146V74.31A.146.146,0,0,0,64.628,74.455ZM59.67,85.83H56.461V82.622a.146.146,0,0,0-.146-.146H55.295a.146.146,0,0,0-.146.146V85.9a1.239,1.239,0,0,0,1.24,1.24H59.67A.146.146,0,0,0,59.815,87V85.976A.146.146,0,0,0,59.67,85.83ZM69,82.476H67.982a.146.146,0,0,0-.146.146V85.83H64.628a.146.146,0,0,0-.146.146V87a.146.146,0,0,0,.146.146h3.281a1.239,1.239,0,0,0,1.24-1.24V82.622A.146.146,0,0,0,69,82.476Zm.292-2.99H55a.146.146,0,0,0-.146.146v1.021A.146.146,0,0,0,55,80.8H69.295a.146.146,0,0,0,.146-.146V79.632A.146.146,0,0,0,69.295,79.487Z" transform="translate(-54.857 -73.143)" fill="#3d3d3d"/>
                </svg>
              </i>
              {f({id: 'header_scan_text'})}
            </Popover>
          }
        />

### What is expected?
期望得到正确的展示效果

### What is actually happening?
我可以发视频给你哇～～～

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 样式问题 |
| System | mac 10.14.6 |
| Browser | 78.0.3904.70 (Official Build) (64-bit) |

**Comment by wenbinobject** [comment]
我可以给你视频 你可以详细看下这个样式问题是怎么样产生的

**Comment by afc163** [comment]
You can upload video on this issue.

**Comment by wenbinobject** [comment]
https://codesandbox.io/embed/antd-reproduction-template-sigz0?fontsize=14
 you can see this bug

**Comment by afc163** [comment]
What should I do excatly to reproduce the problem?

**Comment by wenbinobject** [comment]
> What should I do excatly to reproduce the problem?

you can repeat click scan and see the view.  
你可以重复点击扫描按钮 然后看取消显示时的效果～～～ 会额外看到一个白色的样式

**Comment by afc163** [comment]
看上去这不是一个问题，visible 为 false 时卡片还在隐藏动画中，此时设置内容会空会导致卡片大小跳动。不知道你这么做的需求是什么？

**Comment by wenbinobject** [comment]
由于visible == true的时候 我调用了一个第三方库 他他并没有提供关闭摄像头功能 所以我只能清除这个dom 
            <Popover  
              trigger="click" 
              placement="bottom" 
              visible={visible}
              onVisibleChange={handleVisibleChange}
              content={
                visible?
                <div className="class-QrReader" >
                  <QrReader
                    delay={100}
                    onError={handleError}
                    onScan={handleScan}
                    style={{ width: '100%' }}
                    showViewFinder={false}
                  />
                </div>
                :null
                }
              >
              <i className="svg-scan">
                <svg  xmlns="http://www.w3.org/2000/svg"  width="14.583" height="14" y="5" viewBox="0 0 14.583 14">
                  <path id="Path_75" data-name="Path 75" d="M55.295,77.81h1.021a.146.146,0,0,0,.146-.146V74.455H59.67a.146.146,0,0,0,.146-.146V73.289a.146.146,0,0,0-.146-.146H56.388a1.239,1.239,0,0,0-1.24,1.24v3.281A.146.146,0,0,0,55.295,77.81Zm9.333-3.354h3.208v3.208a.146.146,0,0,0,.146.146H69a.146.146,0,0,0,.146-.146V74.382a1.239,1.239,0,0,0-1.24-1.24H64.628a.146.146,0,0,0-.146.146V74.31A.146.146,0,0,0,64.628,74.455ZM59.67,85.83H56.461V82.622a.146.146,0,0,0-.146-.146H55.295a.146.146,0,0,0-.146.146V85.9a1.239,1.239,0,0,0,1.24,1.24H59.67A.146.146,0,0,0,59.815,87V85.976A.146.146,0,0,0,59.67,85.83ZM69,82.476H67.982a.146.146,0,0,0-.146.146V85.83H64.628a.146.146,0,0,0-.146.146V87a.146.146,0,0,0,.146.146h3.281a1.239,1.239,0,0,0,1.24-1.24V82.622A.146.146,0,0,0,69,82.476Zm.292-2.99H55a.146.146,0,0,0-.146.146v1.021A.146.146,0,0,0,55,80.8H69.295a.146.146,0,0,0,.146-.146V79.632A.146.146,0,0,0,69.295,79.487Z" transform="translate(-54.857 -73.143)" fill="#3d3d3d"/>
                </svg>
              </i>
              {f({id: 'header_scan_text'})}
            </Popover>

**Comment by afc163** [comment]
你可以在 `afterVisibleChange` 动画结束后的回调后去清除。

**Comment by wenbinobject** [comment]
好的 谢谢～～～

**Comment by wenbinobject** [comment]
> afterVisibleChange

这个属性在3.25.0的文档上 并未发现～～～


已解决 

            <Popover  
              trigger="click" 
              placement="bottom" 
              visible={visible}
              onVisibleChange={handleVisibleChange}
              afterVisibleChange={afterVisibleChange}
              content={
                visible&&afterVisible?
                <div className="class-QrReader" >
                  <QrReader
                    delay={100}
                    onError={handleError}
                    onScan={handleScan}
                    style={{ width: '100%' }}
                    showViewFinder={false}
                  />
                </div>
                :null
                }
              >
              <i className="svg-scan">
                <svg  xmlns="http://www.w3.org/2000/svg"  width="14.583" height="14" y="5" viewBox="0 0 14.583 14">
                  <path id="Path_75" data-name="Path 75" d="M55.295,77.81h1.021a.146.146,0,0,0,.146-.146V74.455H59.67a.146.146,0,0,0,.146-.146V73.289a.146.146,0,0,0-.146-.146H56.388a1.239,1.239,0,0,0-1.24,1.24v3.281A.146.146,0,0,0,55.295,77.81Zm9.333-3.354h3.208v3.208a.146.146,0,0,0,.146.146H69a.146.146,0,0,0,.146-.146V74.382a1.239,1.239,0,0,0-1.24-1.24H64.628a.146.146,0,0,0-.146.146V74.31A.146.146,0,0,0,64.628,74.455ZM59.67,85.83H56.461V82.622a.146.146,0,0,0-.146-.146H55.295a.146.146,0,0,0-.146.146V85.9a1.239,1.239,0,0,0,1.24,1.24H59.67A.146.146,0,0,0,59.815,87V85.976A.146.146,0,0,0,59.67,85.83ZM69,82.476H67.982a.146.146,0,0,0-.146.146V85.83H64.628a.146.146,0,0,0-.146.146V87a.146.146,0,0,0,.146.146h3.281a1.239,1.239,0,0,0,1.24-1.24V82.622A.146.146,0,0,0,69,82.476Zm.292-2.99H55a.146.146,0,0,0-.146.146v1.021A.146.146,0,0,0,55,80.8H69.295a.146.146,0,0,0,.146-.146V79.632A.146.146,0,0,0,69.295,79.487Z" transform="translate(-54.857 -73.143)" fill="#3d3d3d"/>
                </svg>
              </i>
              {f({id: 'header_scan_text'})}
            </Popover>

**Comment by afc163** [comment]
对，在 https://github.com/react-component/tooltip 但是没有写到官方文档上。

**Comment by wenbinobject** [comment]
其实除了afterVisibleChange 结束动画之后执行 ，也还可以放一个空白的dom站位 这样也不会产生问题。 还是谢谢你的解答
