### ISSUE TITLE
Table组件新增可编辑行时，如果此时页码不是在第一页，表格中的数据会丢失（无法显示）

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design#19596]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-bas-k8j1q)

### Steps to reproduce
1. 在页码为1时，点击新增，新增行出现在表格最上方
2. 点刷新按钮，重置页面（页面功能比较复杂，有些问题没有处理）
3. 点击页码2，显示第2页的数据，然后再点击新增按钮，数据出现丢失

### What is expected?
表格能在任何页码新增数据

### What is actually happening?
表格只能在第一页新增数据

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | windows 10 |
| Browser | chrome |

---
具体演示请看以下动图
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/ant_design_bug1.mjzszeiacre.gif)

**Comment by afc163** [comment]
这只是一个例子，具体业务实现中需要根据你自己的需求进行调整。

**Comment by maxmeng93** [comment]
不是加到所有数据的最前面，而是加到本页数据的最前面

**Comment by zombieJ** [comment]
`rowIndex` 指的是当前展示的 index，翻页后肯定和你的 editIndex 不匹配呐。如果要标注是哪一个，用 `key` 不要用 `index`。参考[官方例子](https://ant.design/components/table-cn/#components-table-demo-edit-row)

**Comment by maxmeng93** [comment]
问题应该是点击新增时，多了一条数据，而pageSize设置的是10，现在本页却有11条数据，所以把前十条数据放到了其他其他页码上，本页只剩下最后一条数据

**Comment by maxmeng93** [comment]
> `rowIndex` 指的是当前展示的 index，翻页后肯定和你的 editIndex 不匹配呐。如果要标注是哪一个，用 `key` 不要用 `index`。参考[官方例子](https://ant.design/components/table-cn/#components-table-demo-edit-row)

用 `key` 也是不行的，因为还是会自动分页

**Comment by maxmeng93** [comment]
现在只能为 `<Table />`  单独加一个 `<Pagination />` ，然后把表格的pagination设置为false，这样才能避免数据量超出pageSize，而自动分页
