### ISSUE TITLE
使用导航菜单Menu，浏览器控制台会冒出一堆警告语

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design#19594]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
当导航菜单超过一定长度后面会隐藏起来，当鼠标移动到隐藏那部分，控制台就开始冒一堆警告提示了，例子是直接官方demo照搬过来的，不知道为什么会这样，下面是控制台警告提示

Warning: setState(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

### What is expected?
控制台不会出现警告提示

### What is actually happening?
控制台会出现警告提示

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by afc163** [comment]
Fixed in https://ant.design/changelog-cn#3204

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/17657

**Comment by dongkeng001** [comment]
> #17657

请问这个bug你们在哪个版本更新了？我用3.25.0最新版本还是有这个bug的，还是在下个版本更新上？

**Comment by afc163** [comment]
3.20.4

**Comment by dongkeng001** [comment]
> 3.20.4, please see changelog https://ant.design/changelog-cn#3.20.4

亲，我把我目前3.20.0版本更新到3.20.4，问题还存在，难道我更新的方法不对？

**Comment by afc163** [comment]
`cat node_modules/antd/package.json` 看看安装的版本。如果依然有这个问题，可以用 http://u.ant.design/codesandbox-repro 重现一下回复在这里。

**Comment by dongkeng001** [comment]
> `cat node_modules/antd/package.json` 看看安装的版本。如果依然有这个问题，可以用 http://u.ant.design/codesandbox-repro 重现一下回复在这里。

node_modules/antd/package.json 里面版本也是3.20.4，说明我是更新成功了，问题也是依旧存在的
`{
  "name": "antd",
  "version": "3.20.4",
  "title": "Ant Design",
   ...
`
你发的那个重现链接，默认版本是3.25.0的，那我该怎么降级呢？在index.d.ts里面改版本？
//index.d.ts
declare var _default: "3.25.0";
export default _default;

**Comment by yoyo837** [comment]
重现链接 修改codesandbox 依赖降级

**Comment by afc163** [comment]
不需要降版本，如果你本地最新版本有问题，codesandbox 里理论上 3.25.0 也会有问题。

**Comment by dongkeng001** [comment]
> 不需要降版本，如果你本地最新版本有问题，codesandbox 里理论上 3.25.0 也会有问题。

重现链接中的3.25.0版本是正常的，但我本地项目升到3.20.4或者升到3.25.0还是会提示以下警告的，把node_modules删掉重新装还是一样，奇怪...

`Warning: setState(...): Cannot update during an existing state transition (such as within render or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to componentWillMount.`

**Comment by afc163** [comment]
确保你用的是 node_modules 里面的 antd，而不是 cdn 或者是其他库里依赖进来的老版本 antd。

**Comment by afc163** [comment]
确保你用的是 node_modules 里面的 antd，而不是 cdn 或者是其他库里依赖进来的老版本 antd。

**Comment by dongkeng001** [comment]
> 确保你用的是 node_modules 里面的 antd，而不是 cdn 或者是其他库里依赖进来的老版本 antd。

我用了两种方法去更新antd
第一种在node_modules里面删掉antd这个文件，然后通过命令cnpm install antd@3.20.4 -S -D去更新的；
第二种直接把node_modules包删掉，直接cnpm install重新安装依赖包；
