### ISSUE TITLE
Form表单校验异常

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design#19600]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-hooks-lnzk7)

### Steps to reproduce
1. 将Item的formId按照这样的规则命名：`getFieldDecorator('password'...`, `getFieldDecorator('password-1'...`, `getFieldDecorator('password-2'...`, `getFieldDecorator('password-3'...`
2. 点击demo中的的submit即可出现校验异常

### What is expected?
1. 异常信息能正确显示到对应的元素上

### What is actually happening?
1. 异常信息都堆积到一个元素上
2. 看了[代码](https://github.com/react-component/form/blob/efa40fd8a77b34f43ff35e4e7bf4b4f27441ce2f/src/createBaseForm.js#L475)是这里的处理问题，但不明白为什么这么写

| Environment | Info |
|---|---|
| antd | 3.xx, 4.0 |
| React | 16.11.0 |
| System | win 10 |
| Browser | chrome 78 |

**Comment by yoyo837** [comment]
This is really a biiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiig problem.

**Comment by yoyo837** [comment]
[代码](https://github.com/react-component/form/blob/efa40fd8a77b34f43ff35e4e7bf4b4f27441ce2f/src/createBaseForm.js#L475)

```js
    // Skip if not match array type
    if (rules.every(({ type }) => type !== 'array') && errorFieldName.indexOf(ruleFieldName) !== 0) {
        return false;
    }

    // Exist if match the field name
    const restPath = errorFieldName.slice(ruleFieldName.length + 1);
    if (/^\d+$/.test(restPath)) {
        fieldName = ruleFieldName;
        return true;
    }
```

https://github.com/react-component/form/pull/257 这里是刻意兼容`xxx-xxx`的写法的，不知为何 @zombieJ

**Comment by zombieJ** [comment]
There exist `type='array'` for the validation which does not export path array so used string slice here. This is a bug should fix.
