### ISSUE TITLE
Modal can custom closeIcon, why notification not ?

### ISSUE THREAD

**Issue by zlv-thisF** [ant-design/ant-design#19603]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
notification and modal functionally is the same to user, so their ui or ux should be the same in my opinion, now the problem is modal support closeIcon , but notification is not; 

besides, notification based on rc-notification which support closeIcon already, however notificaiton in ant-design not pass it down to rc-notification

### What does the proposed API look like?
just as modal or rc-notification does, pass 'closeIcon' down to support custom close icon in notificaion
type  closeIcon = ReactNode

**Comment by afc163** [comment]
close in favor of #19618
