### ISSUE TITLE
RangePicker设置required错误

### ISSUE THREAD

**Issue by slertness** [ant-design/ant-design#1960]
使用RangePicker，设置rules:[{required: true}]。

当我选择完值以后，提交会报xx is not a string。因为它的value其实是一个数组。虽然可以自定义validator去校验。但是我还想要设required的时候label前面的红*。

所以请看下这个问题是不是需要修复。

或者先告诉我怎么在不设required的情况下在label前面弄出红*。

## 本地环境信息

- antd 版本: 1.3.0

**Comment by afc163** [comment]
`type: 'array'`
