### ISSUE TITLE
Column reordering through drag-and-drop

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#19604]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There are situations where the user wants to customize the order of the columns to fit their use. (TelerikReact)[https://www.telerik.com/kendo-react-ui/components/grid/columns/reordering/] supports this functionality

### What does the proposed API look like?
A simple `Table` prop of `reorderable` would be sufficient.

**Comment by afc163** [comment]
Try https://github.com/ant-design/pro-table/

**Comment by keithort** [comment]
I don't see any way to reorder columns in the browser.

**Comment by afc163** [comment]
![2020-03-14 13-38-41 2020-03-14 13_39_47](https://user-images.githubusercontent.com/507615/76675896-49f0c780-65f9-11ea-84f8-754bd792d2a2.gif)

**Comment by keithort** [comment]
@afc163 Where is that demo available? I am not seeing it in any of the [documentation](https://github.com/ant-design/pro-table).

**Comment by afc163** [comment]
https://protable.ant.design/

**Comment by anhpt97** [comment]
@keithort I found this, it may solve your problem https://github.com/ant-design/ant-design/issues/9282
