### ISSUE TITLE
有没有办法能够获取 Form 注册的所有字段，不包括 value

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#19612]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我需要能够获取到表单所有字段然后判断字段数量变更来处理事情，但是现在 `Object.keys` 无法得到 children 的字段，要想获取所有字段，没有办法区分字段的值是真实的值，还是 Form 的字段。

### What does the proposed API look like?
如上

**Comment by afc163** [comment]
`Object.keys(this.props.form.getFieldsValue())` 不行么？

`Object.keys 无法得到 children 的字段` 具体是指什么？

**Comment by qq645381995** [comment]
> `Object.keys(this.props.form.getFieldsValue())` 不行么？
> 
> `Object.keys 无法得到 children 的字段` 具体是指什么？
所有字段
![image](https://user-images.githubusercontent.com/7971419/68379004-0c31ed00-0188-11ea-9bdd-6a408683497c.png)
表单数据
![image](https://user-images.githubusercontent.com/7971419/68379056-1d7af980-0188-11ea-8672-b8a8777d65e6.png)

我现在大致做出来了，不过判断感觉不严谨。

**Comment by qq645381995** [comment]
全部代码
```
import moment from "moment";
import { mapKeys, keys, get } from "lodash";

const obj = {
  first: "1",
  second: {
    name: "abc",
    third: {
      age: "30",
      mykey: "3"
    }
  },
  demo: "aa",
  time: new Date(),
  moment: moment()
};
const getAllKeys = obj => {
  const list = [];
  const func = (obj, keyPath) => {
    const _obj = keyPath ? get(obj, keyPath) : obj;
    mapKeys(_obj, (value, key) => {
      const _currentKey = keyPath ? `${keyPath}.${key}` : key;
      if (
        keys(value).length > 0 &&
        keys(value)[0] !== "0" &&
        !moment.isMoment(value)
      ) {
        return func(obj, _currentKey);
      } else {
        list.push(_currentKey);
      }
    });
    return list;
  };
  func(obj);
  return list;
};
console.log("allFormKey", getAllKeys(obj));
```

**Comment by dengfuping** [comment]
- @qq645381995 可以自己封装一个 `util` 函数实现，感觉这不是一个很通用的需求，毕竟不需要通过遍历去拿所有的值。

**Comment by qq645381995** [comment]
> * @qq645381995 可以自己封装一个 `util` 函数实现，感觉这不是一个很通用的需求，毕竟不需要通过遍历去拿所有的值。

我这判断 value 的值是字段的值还是 Form 的 filed ，不太严谨，不能有办法获取所有注册的字段吗。

**Comment by dengfuping** [comment]
> 而是要获取所有的字段！

- 获取所有的字段做什么呢？平时很少会这么用吧

**Comment by qq645381995** [comment]
> > 而是要获取所有的字段！
> 
> * 获取所有的字段做什么呢？平时很少会这么用吧

我这里的场景是 字段有项目依赖，比如 a 字段 = 1 就显示 b 字段，这样会触发一次 change，但是如果 b 字段有 initialValue  那 getFieldsValue 其实是拿不到 b 字段的值的，但是如果 c 字段依赖 b字段的值而显示隐藏，那这时候就没地方能够获取 b 的值了。

**Comment by janglikv** [comment]
可以用 getFieldsError
