### ISSUE TITLE
onCollapse 更新不及时 Layout

### ISSUE THREAD

**Issue by cutanzi1997** [ant-design/ant-design#19611]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-pro/issues/5539](https://github.com/ant-design/ant-design-pro/issues/5539)

### Steps to reproduce
来回拖动浏览器的 边框

### What is expected?
随着边框的拖动 触发函数

### What is actually happening?
onCollapse触发

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.8 |
| System | macos |
| Browser | chrome 78 |

**Comment by afc163** [comment]
和 antd 关系不大，具体可能和 https://github.com/ant-design/ant-design-pro-layout/blob/6bd845351ba74518cdfb8eafc3f7ee248f1b9788/src/GlobalHeader/index.tsx#L27-L33 这个有关，请到 ant-design/ant-design-pro#5539 讨论和定位问题。
