### ISSUE TITLE
自定义表单控件，如何resetFields 

### ISSUE THREAD

**Issue by zehuichan** [ant-design/ant-design#19615]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-wave-7wky8)

### Steps to reproduce
改变select的值后，点击reset按钮

### What is expected?
点击reset按钮后，select变成默认值

### What is actually happening?
点击reset按钮后，select值无变化

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | react |
| System | win7 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/wandering-morning-j6c7r

**Comment by zehuichan** [comment]
@afc163 超级感谢！
