### ISSUE TITLE
Upload 上传，如何修改列表位置，从新定义了一个fileItems，this.handleChange在里面this.setState不管用

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#1961]
http://ant.design/components/upload/#components-upload-demo-fileList
使用上面的例子，如果使用默认的fileList，布局不是想要的布局，重新定义了一个fileItems，this.handleChange里面this.setState不管用了。

`class Files extends React.Component {
  constructor(props){
      super(props);
      this.state = {
        fileItems: [{
          name: '00文字说明文字说明文字说明文字说明文字说明',
          icon: './static/images/excel.png',
          url: 'http://www.baidu.com/xxx.png'
        }]
      };
  }
  handleChange(info) {
    this.setState({filelist:[{
      name: '00文字说明文字说明文字说明文字说明文字说明',
      icon: './static/images/excel.png',
      url: 'http://www.baidu.com/xxx.png'
    }]})
  }
  render() {
    //上传文件
    const UploadProps = {
      name: 'file',
      listType: 'picture',
      action: '/upload.do',
      onChange: this.handleChange
    }
    return (
      <QueueAnim delay={300}>
        <div className="pad-20 clearfix" key="1">
          <div className="pull-left">
            <Classify current={3} />
          </div>
          <div className="pull-right">
            <Upload {...UploadProps} fileItems={this.state.fileItems}>
              <Button type='dashed' icon="upload" size="large">上传文件</Button>
            </Upload>
          </div>
        </div>
        <div className="pad-20" key="2">
          <ul className="clearfix list">
            {this.state.fileItems.map((data, index) => <li key={index}>
              <Icon type="delete" />
              <img src={data.icon} />
              <p>{data.name}</p>
            </li>)}
          </ul>
        </div>
      </QueueAnim>
    )
  }
}`

**Comment by afc163** [comment]
fileItems 是什么？

**Comment by EagleWolf** [comment]
主要想怎么修改，图片列表的默认布局。

**Comment by afc163** [comment]
关闭 Upload 自带的列表 `showUploadList`，用 fileList 自行渲染出一个文件列表。

**Comment by afc163** [comment]
或者自行覆盖样式。

**Comment by EagleWolf** [comment]
onChange事件进来了3次

`const UploadProps = {
      name: 'file',
      fileList:[{
        name: '00文字说明文字说明文字说明文字说明文字说明',
        icon: './static/images/excel.png',
        url: 'http://www.baidu.com/xxx.png'
      }],
      showUploadList: false,
      action: 'http://rap.t.nxin.com/mockjs/1/common/file/upload?fileName=2',
      onChange: function(info){
        //let fileList = info.fileList;
       //打印了3次console.log(info);
        console.log(info);
      }
    }`

**Comment by EagleWolf** [comment]
handleChange(info) {this.setState({ fileList });}

this.setState也不能用。
