### ISSUE TITLE
Can't make card body scrollable when components overflow

### ISSUE THREAD

**Issue by Timunas** [ant-design/ant-design#19621]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-otq7u?fontsize=14)

### Steps to reproduce
Have a Card with a Collapse element and then several Panels.

### What is expected?
I Expected the card body to have a scrollbar

### What is actually happening?
Now scroll bar is shown and child components overflow the card

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | Linux |
| Browser | Firefox |

---
If I add the overflow prop to the card it works but then the header is also scrollable. I just wanted to have the scrollbar in the body.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-nw3vv
