### ISSUE TITLE
怎么通过JS动态修改Input里面的值

### ISSUE THREAD

**Issue by millertiga** [ant-design/ant-design#19628]
Input API里面的defaultValue 只能设置一次，而如果使用value，就不能通过键盘输入了

**Comment by yoyo837** [comment]
请学习React 受控模式！

**Comment by yoyo837** [comment]
https://reactjs.org/docs/forms.html#controlled-components

**Comment by millertiga** [comment]
好的，谢谢，刚在看这方面



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;; 
发送时间: 2019年11月8日(星期五) 下午4:51
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "永不ぉ放弃"<594238949@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 怎么通过JS动态修改Input里面的值 (#19628)




https://reactjs.org/docs/forms.html#controlled-components
