### ISSUE TITLE
怎么通过JS动态修改Input里面的值

### ISSUE THREAD

**Issue by millertiga** [ant-design/ant-design#19629]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Input API里面的defaultValue 只能设置一次，而如果使用value，就不能通过键盘输入了。 版本：3.24.2

### What does the proposed API look like?
希望能有一个API能够实时通过JS修改input里面的值

**Comment by afc163** [comment]
Try `value`.

https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
