### ISSUE TITLE
how to remove umi ui bubble

### ISSUE THREAD

**Issue by axelginepro** [ant-design/ant-design#19620]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://drive.google.com/open?id=1JU52HPDikMn_8oRWvhlJwsasyoN51Asu](https://drive.google.com/open?id=1JU52HPDikMn_8oRWvhlJwsasyoN51Asu)

### Steps to reproduce
tell me how to remove this umi ui bubble please

### What is expected?
remove it

### What is actually happening?
new in the project

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.10 |
| System | windows 10 |
| Browser | chrome, brave |

**Comment by dengfuping** [comment]
- `UMI_UI=none umi dev`

**Comment by renanwilliam** [comment]
Doesn't work for me. Any changes in V5?
