### ISSUE TITLE
DatePicker  style 设置宽度,没法改变宽度

### ISSUE THREAD

**Issue by ywww** [ant-design/ant-design#19626]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://nome](http://nome)

### Steps to reproduce
                <DatePicker
                    style={{width: 200}}
                    value={momentValue}
                    format={df}
                    showTime={true}
                    disabled={this.props.disabled}
                    onChange={(date, dataString) => onChange(dataString)}
                />

### What is expected?
style能设置 控件宽度

### What is actually happening?
style不能设置 控件宽度

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | win10 |
| Browser | chrome 78.0.3904.87 |

**Comment by afc163** [comment]
https://codesandbox.io/s/restless-thunder-rk1f5

It works.

**Comment by afc163** [comment]
Oh, you have to set `minWidth` too if showTime is on. There is min width for DatePicker with time to avoid time text being cut.

https://codesandbox.io/s/eager-brook-i3wxp

**Comment by ywww** [comment]
3Q
