### ISSUE TITLE
Import svg with create-react-app for use as a custom icon gives type error

### ISSUE THREAD

**Issue by Rocinante89** [ant-design/ant-design#19638]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/sholsyjy/antd-svg-type-error](https://github.com/sholsyjy/antd-svg-type-error)

### Steps to reproduce
1.import svg using create-react-app
2.use svg as custom icon prop
3.there is a type error (cra icon type is React.SVGProps<SVGSVGElement> and ant is looking for CustomIconComponentProps )

### What is expected?
As this is the preferred way of importing svg icons in create react app, the interface should be extended to React.FunctionComponent<CustomIconComponentProps | SVGProps<SVGSVGElement>>

### What is actually happening?
Reacts documentation has a specific way of importing svgs that ant design does not support

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | Windows 10 |
| Browser | Chrome Latest |

**Comment by afc163** [comment]
For reference: https://github.com/ant-design/ant-design/issues/13205#issuecomment-462195137
