### ISSUE TITLE
antd form组件 validator 出现异常

### ISSUE THREAD

**Issue by idujiawei** [ant-design/ant-design#19634]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-vnx85?fontsize=14)

### Steps to reproduce
在form元素定义初始值后，
多个元素都使用自定义校验方法 validator，
直接保存，
校验不同过的元素，
提示消息不止出现方法回调返回的文案，还会出现 ${key} fails

### What is expected?
只出现 validator 方法 定义的文案

### What is actually happening?
提示消息不止出现方法回调返回的文案，还会出现 ${key} fails

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.3.2 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
```diff
   // 校验长度
    if (no.length !== 15 && no.length !== 18) {
      callback && callback("身份证号长度错误");
-     return true;
+     return;
    }
```

返回值我也不了解有什么意义，去掉就好了。
