### ISSUE TITLE
How to center the tabs inside antd？

### ISSUE THREAD

**Issue by large-plate-chicken** [ant-design/ant-design#19631]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to place the tabs in the middle, but there is no such function. Using the renderTabBar does not seem to solve the problem, save the child!

### What does the proposed API look like?
Need to be able to specify tabs from left to right or right to left sort。

**Comment by large-plate-chicken** [comment]
My dear dalao please daidaiwo!

**Comment by afc163** [comment]
https://stackoverflow.com/questions/57495837/ant-design-tabs-alignment
