### ISSUE TITLE
Table - Sorting doesnt work properly in server side sortin/filtering mode

### ISSUE THREAD

**Issue by alesdvorakcz** [ant-design/ant-design#19636]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-leftpad-wwzj2?fontsize=14)

### Steps to reproduce
1. Click Gender column to sort ascending
2. Click it again to sort descending -> it will not work

### What is expected?
After column is clicked it should change sort order

### What is actually happening?
Table is refreshed but sorting does not change

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | mac os x 10.15.1 |
| Browser | Safari 13.0.3 |

---
It happends when table is configured for remote sorting/filtering and when columns definition is inside component/render - when columns definition is static, it works. But then its improssible to set filters, traslate titles, etc

**Comment by afc163** [comment]
https://codesandbox.io/s/little-grass-g2drw

https://github.com/ant-design/ant-design/issues/19398
https://github.com/ant-design/ant-design/issues/19058
