### ISSUE TITLE
Synthetic event warning triggered a lot with draggable tree example

### ISSUE THREAD

**Issue by guidogast** [ant-design/ant-design#19637]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x7jrvy5vqp)

### Steps to reproduce
Start dragging over another item and keep it there for a second.

### What is expected?
No warnings/errors in the console

### What is actually happening?
`console.error` warnings in the console, saying: `Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.`

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | latest |
| System | Windows 10 |
| Browser | Chrome 78.0.3904.97 |

---
Here's a GIF of the problem: ![Image of bug](https://media.giphy.com/media/YMupLPEoIRzpqIUFmc/giphy.gif)

**Comment by naoey** [comment]
It's also triggered frequently for all tree events, not just drag events. I'm encountering it with `onSelect` as well as `onExpand` in a `DirectoryTree`. This is a pretty serious regression imo and is causing several breakages in our application after upgrading.

Using antd version 3.26.7 (latest).

**Comment by zombieJ** [comment]
This warning is caused by codesandbox want to print event content in its `console` panel.  Click open in new tab and you will find no more error out:
<img width="52" alt="截屏2020-01-20下午1 46 40" src="https://user-images.githubusercontent.com/5378891/72701728-4ad22380-3b8b-11ea-84ce-d3a80b25e967.png">

**Comment by naoey** [comment]
Codesandbox is not the issue, we are facing this in our application as well. Antd seems to be passing on native events to our tree event handlers without persisting them as the error indicates.

**Comment by zombieJ** [comment]
@naoey , 
Could you help to provide reproduce about this?
