### ISSUE TITLE
Table componet select all failure

### ISSUE THREAD

**Issue by yifanya** [ant-design/ant-design#19640]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-ptolemy-j1052?fontsize=14)

### Steps to reproduce
click button update data，select all features has failure. I'm not good at English......

### What is expected?
Normal function

### What is actually happening?
can't support select all

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | latest |
| System | macos  |
| Browser | chrome latest |

**Comment by afc163** [comment]
https://codesandbox.io/s/serene-dust-rmexp
