### ISSUE TITLE
MonthPicker组件默认显示的是英文而不是中文

### ISSUE THREAD

**Issue by 7777sea** [ant-design/ant-design#19642]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
项目中直接引入MonthPicker组件

### What is expected?
面板显示中文月份

### What is actually happening?
面板显示英文月份

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.10.2 |
| System | macOS 10.13.4 |
| Browser | Google Chrome 78.0.3904.87 |

**Comment by afc163** [comment]
https://ant.design/components/config-provider-cn/

**Comment by 7777sea** [comment]
> https://ant.design/components/config-provider-cn/

全局已经配置，其他组件国际化没有问题，只有MonthPicker组件存在此问题

**Comment by afc163** [comment]
Could you provide a re-producible demo to help us, by forking and editing this codepen: http://codepen.io/benjycui/pen/KgPZrE?editors=001

(A good and minimum codpen will save a lot of time 😃)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/c9682fcd6eb4778646b9245c9d05632358c92730

**Comment by 7777sea** [comment]
antd 3.25.0 官网示例也会复现这个bug
