### ISSUE TITLE
日期选择器上一页下一页表格分页上一页下一页等不垂直居中

### ISSUE THREAD

**Issue by zzxqd** [ant-design/ant-design#19648]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/zzxqd/antd-issueReport/tree/master](https://github.com/zzxqd/antd-issueReport/tree/master)

### Steps to reproduce
install 之后 run start

### What is expected?
箭头按钮中的箭头都是居中

### What is actually happening?
顶部对齐 不居中
![image](https://user-images.githubusercontent.com/23022401/68532881-b31bb200-035d-11ea-9c33-aec53e8f034b.png)

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.0.1 |
| System | win10 |
| Browser | edge(chromium v.79) / firefox v.71 |

---
demo里的实际渲染的样式和线上文档里渲染样式是一致的，但结果确不一样

**Comment by dengfuping** [comment]
- CodeSandbox 上的 [例子](https://codesandbox.io/s/cold-moon-pcq8j) 是 OK 的，应该是项目配置的问题。可以自行检查下，或者按照 [这篇文档](https://ant.design/docs/react/use-with-create-react-app-cn) 看下能否重现。
> demo里的实际渲染的样式和线上文档里渲染样式是一致的，但结果确不一样
- 应该是垂直居中的样式没生效。

**Comment by afc163** [comment]
https://github.com/zzxqd/antd-issueReport/pull/1

**Comment by zzxqd** [comment]
是的 就是没加文档声明，导致了使用怪异模式进行渲染的问题，虽然样式是一致的，渲染出来的效果却略微不同
![图片](https://user-images.githubusercontent.com/23022401/68540325-f4967680-03ca-11ea-8bba-8b99f09c867c.png)
