### ISSUE TITLE
Upload 上传 handleChange连续进入3次的bug。

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#1964]
http://ant.design/components/upload/#components-upload-demo-fileList

handleChange方法里面会连续进入3次。

在handleChange里面log下，会连续打印3次。

**Comment by afc163** [comment]
没有问题，注意 `file.status`，只有最后一次是 done，前面的是上传状态变化。

http://ant.design/components/upload#components-upload-demo-fileList
