### ISSUE TITLE
`getFieldDecorator` does not get the field value if the field is wrapped with redux/dva connect

### ISSUE THREAD

**Issue by jamalabo1** [ant-design/ant-design#19649]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-tu0kl)

### Steps to reproduce
offer a top-level API to give the `getFieldDecorator` the field value

### What is expected?
the `getFieldDecorator` get's the field value

### What is actually happening?
return error that the field is required

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | Windows 10 |
| Browser | Chrome 78 |

---
In this case, I'm using `dva`,
but anyway simply the `getFieldDecorator` does not support wrapped fields

**Comment by jamalabo1** [comment]
https://codesandbox.io/s/antd-reproduction-template-tu0kl

**Comment by jamalabo1** [comment]
@afc163  any updates?

**Comment by afc163** [comment]
https://ant.design/components/form/#components-form-demo-customized-form-controls

Please check this demo.
