### ISSUE TITLE
Document Update: formatting number for currencies and other thing in the NumberInput Component

### ISSUE THREAD

**Issue by Utkarshbhimte** [ant-design/ant-design#19645]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hey, I have created this example to figure out how to format the ant.design InputNumber component for currencies using the Intl.NumberFormat API. 
You can check out my implementation [here](https://codesandbox.io/s/currency-wrapper-antd-input-3ynzo)

### What does the proposed API look like?
I am just asking for adding that to the docs as it would be helpful for other people. Localization on the number formatting is a pretty common usecase.

**Comment by Utkarshbhimte** [comment]
@zombieJ If it helps you, I can pick this issue up myself?

**Comment by Utkarshbhimte** [comment]
will do

**Comment by afc163** [comment]
@Utkarshbhimte

**Comment by afc163** [comment]
@Utkarshbhimte ping

**Comment by Utkarshbhimte** [comment]
Hey @afc163, I wasn't able to get time to add this. I will try to do it this weekend, else you are free to pick it up.

**Comment by baohouse** [comment]
@Utkarshbhimte the sample code is not usable. If you start typing and deleting numbers, you get a lot of unexpected behavior (e.g. in a long number, move the cursor to the middle of the number text, and then start deleting numbers)

**Comment by Utkarshbhimte** [comment]
@baohouse Let me check and get back to you on that

**Comment by baohouse** [comment]
@Utkarshbhimte I updated my above comment with a few test cases.
