### ISSUE TITLE
InputNumber is not able to handle more than 15 digit number.

### ISSUE THREAD

**Issue by lawteo** [ant-design/ant-design#19653]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://c7z61.csb.app/](https://c7z61.csb.app/)

### Steps to reproduce
1. Key in 16 digits of 9 and it will round off to 17 digits (i.e. 9,999,999,999,999,999 -> 10,000,000,000,000,000)
2. It is not able to limit the input to the maximum as specified by the max props, max={9999999999999999} 16 digits of 9, when more than 15 digits

### What is expected?
1. It should not round up the number unless it is less than the minimum specified by min props.
2. On entering 17 digits of 9's it should limit to a maximum of 16 digits of 9 as specified by max props of InputNumber

### What is actually happening?
See steps to reproduce.
It seems that InputNumber is unable to handle any number larger than 15 digits accurately.

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | latest 16.11 |
| System | Windows |
| Browser | Chrome Version 78.0.3904.97 (Official Build) (64-bit) |

---
Hope that this can be fixed quickly.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5235#issuecomment-285665328

**Comment by Messiahhh** [comment]
请问最新版本InputNumber有办法处理这种大数吗？

**Comment by yoyo837** [comment]
> 请问最新版本InputNumber有办法处理这种大数吗？

这种情况改用input的string吧
