### ISSUE TITLE
textarea will allowClear can't resize smaller

### ISSUE THREAD

**Issue by liuchao233** [ant-design/ant-design#19652]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
带移除图标的demo中，先放大textarea，然后就没法缩小了。

### What is expected?
可以自由的调整尺寸

### What is actually happening?
只能放大不能缩小

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | macos |
| Browser | 74.0.3729.169 |

**Comment by afc163** [comment]
It seems like Chrome-only problem.

**Comment by afc163** [comment]
@Rustin-Liu

**Comment by Rustin-Liu** [comment]
> @Rustin-Liu

I will try to check and fix it.

**Comment by Rustin-Liu** [comment]
The cause of this problem same because ant-input have min-height.
https://github.com/ant-design/ant-design/commit/7cde9c8ffe8376f8d40ce5ce8f6c7445ccf7c9d9

**Comment by Rustin-Liu** [comment]
It same a bug of chromium.

I check the related issue https://bugs.chromium.org/p/chromium/issues/detail?id=94583 .

I have try in sandbox it same still have problem.

Demo test:
[![Edit wild-surf-c3e3h](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wild-surf-c3e3h?fontsize=14)

**Comment by Rustin-Liu** [comment]
ping~

**Comment by Rustin-Liu** [comment]
[I created a bug report to chromium.](https://bugs.chromium.org/p/chromium/issues/detail?id=1023823)

**Comment by afc163** [comment]
Cannot reproduce in latest Chrome now.
