### ISSUE TITLE
Get back support for search value for Select

### ISSUE THREAD

**Issue by flucivja** [ant-design/ant-design#19658]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In previous version (don't remember which one anymore) there was support for search value for Select component.
In newer version this support disappeared and we have to do a lot of workarounds in order to implement select properly.

Here are scenarios in which searchValue needs to be controlled from higher tree:

**Responsive design**
- on large screen there is text box and list under it for searching items
- on small screen there is Select and list is part of the select
When screen is resized then we need to synchronise value of text box between text box and Select

**Async loading and virtual list**
- We have implemented async loading with virtual list in Select but we use Select only for showing selected value/s, not for options list. List is shown by the Dropdown component. And as we don't have control over search value, it is very painful to implement it properly and we have a lot of workarounds in there to have expected behaviour.

### What does the proposed API look like?
<Select {...props} searchValue={'Hello'} />

**Comment by afc163** [comment]
https://codesandbox.io/s/dreamy-butterfly-vdrne

`searchValue` of antd v4 Select is controlled prop now.
