### ISSUE TITLE
danger类型的button点击出现蓝色水纹

### ISSUE THREAD

**Issue by Elon-Yan** [ant-design/ant-design#19663]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-yguih)

### Steps to reproduce
先点击蓝色button，再点击红色button

### What is expected?
红色button应该出现红色水纹

### What is actually happening?
出现了蓝色水纹

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome |

**Comment by orzyyyy** [comment]
![test](https://user-images.githubusercontent.com/24520193/68556604-e51c3980-046d-11ea-887e-bfa5927a83a1.gif)
重现需要一定的手速及动态视力。点下第一个按钮，需要在第一个按钮波纹消失前点击第二个按钮，这样第一个按钮还未消失的波纹就会变成第二个点击按钮的波纹疾走。

目测是 Wave 里的 PesudoStyle 被每个按钮共享了。
https://github.com/ant-design/ant-design/blob/master/components/_util/wave.tsx#L88

**Comment by afc163** [comment]
目前的实现是共享的，个人感觉这种情况比较极端，正常操作很难重现。

**Comment by uedkx** [comment]
![QQ20191111-172227](https://user-images.githubusercontent.com/14989849/68575829-e8ccb200-04a7-11ea-906a-2b412032c263.gif)

在我的mac chrome  78.0.3904.70上好像每次都可以重现

**Comment by ycjcl868** [comment]
重现靠手速 ~ 😂

**Comment by xrkffgg** [comment]
4.0 未发现该问题了
