### ISSUE TITLE
Warning: [antd: Checkbox] `value` is not validate prop, do you mean `checked`?

### ISSUE THREAD

**Issue by leshalv** [ant-design/ant-design#19667]
Warning: [antd: Checkbox] `value` is not validate prop, do you mean `checked`?
![image](https://user-images.githubusercontent.com/30397655/68565110-76e76f00-048d-11ea-8f4d-6cd18321cf52.png)

**Comment by yoyo837** [comment]
文档上只有`checked ` 没有 `value`

**Comment by leshalv** [comment]
但是，源码里有，我用ID就没事，因为我需要一个标志来处理程序

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/68565973-0ee65800-0490-11ea-8d9a-438ed4c5874f.png)

**Comment by yoyo837** [comment]
就cheched 就可以啊

**Comment by leshalv** [comment]
checked  我怎么取到某个标识，知道选中的这个元素ID是那个呢？

**Comment by gotjoshua** [comment]
the issue may be in the wrong format, but the warning is still thrown as of today...
