### ISSUE TITLE
p 样式乱附值

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#19668]
https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less#L129

这个是干吊用啊？？管 p 的样式干啥？？？

导至 landings 里的编辑时样式错乱。。。https://github.com/ant-design/ant-design-landing/issues/161#issuecomment-552266325

**Comment by jljsj33** [comment]
组件库不应该管全局标签样式。。。

**Comment by jljsj33** [comment]
`@import "~antd/lib/style/v2-compatible-reset.less"; ` 和 base.less 的 build 顺序
![image](https://user-images.githubusercontent.com/6802825/68565611-06d9e880-048f-11ea-9c6b-a370e0ad9ab8.png)

**Comment by jljsj33** [comment]
一看 blame 两年前的，，就没人来反馈？？？

**Comment by afc163** [comment]
Reset 样式部分直接参考的 bootstrap，没有问题。

https://github.com/twbs/bootstrap/blob/bba97a93243e2d08e125170356afb0cf053ff2a1/scss/_reboot.scss#L129-L137

**Comment by jljsj33** [comment]
是有问题的，，，像 bisheng, 是项目里的样式先 build 的，，会导至在全局加 p 覆盖都覆盖不了，，我觉得不应该加值，，`margin: 0; padding: 0` 才更通用。。如果要设，可自已在项目里设。

**Comment by jljsj33** [comment]
人家是有变量可控，我们是直接写死？？？

**Comment by afc163** [comment]
@jljsj33 可以来加个变量。

**Comment by jljsj33** [comment]
我上面的截图你没看吗？？？

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design-landing/blob/master/site/templates/static/common.less#L2

**Comment by k644606347** [comment]
全局样式的确头疼，我正在尝试在一个旧项目里使用antd，发现影响到了现有布局，不得不改造下antd的样式了；作为组件库，我更希望antd保持纯粹，样式只作用于组件内
