### ISSUE TITLE
babel-plugin-antd 插件用过之后,webpack 内联css,自己的CSS在and的css后面

### ISSUE THREAD

**Issue by ah-kevin** [ant-design/ant-design#1966]
babel-plugin-antd 插件用过之后,webpack 内联css,自己的CSS在and的css后面. normalize.css

**Comment by benjycui** [comment]
ping @sorrycc

**Comment by sorrycc** [comment]
自己的 css 在 antd css 后面，有什么问题吗?

**Comment by ah-kevin** [comment]
@sorrycc  现在是自己的css 在css的前面- -打错了
![image](https://cloud.githubusercontent.com/assets/10068519/15810381/54d31f20-2bd0-11e6-9738-515fe74c6bd5.png)
箭头的是自己的css

**Comment by gitcyrabbit** [comment]
+1

**Comment by benjycui** [comment]
超过 5 天没有反馈，关了。

**Comment by abbish** [comment]
+1

**Comment by ah-kevin** [comment]
@gitcyrabbit  这个问题你可解决了?

**Comment by abbish** [comment]
这个问题我的解决方法是在静态页面中单独引入 antd 的 css 文件在 head 中

**Comment by ah-kevin** [comment]
@abbish 那你是整个啊 不是模块的啊- -那 bable的那个插件不就没用了 - -

**Comment by abbish** [comment]
@ah-kevin 是的，我目前的场景是允许单独引入的，所以就目前看这么做不会增加额外的负担给项目

**Comment by gitcyrabbit** [comment]
@ah-kevin  我还没有解决

**Comment by afc163** [comment]
这个问题目前不好解决，如果 antd 加载的全局样式不满足你的需求，可以通过 https://github.com/ant-design/antd-init/blob/master/examples/customize-antd-theme/README.md 的方式去覆盖相关变量。
