### ISSUE TITLE
fixed rowSelection 与 expandedRow 一起使用会显示错乱

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#19671]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-davinci-ej33e)

### Steps to reproduce
为表格使用 rowSelection 和 expandedRow，并展开表项。

### What is expected?
正常显示

### What is actually happening?
显示错乱
![image](https://user-images.githubusercontent.com/10294977/68572685-08aca780-04a1-11ea-963b-d2c0f40f3044.png)

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | latest |
| System | Mac OS X 10.15.1 |
| Browser | Chrome Canary 80.0.3962.0 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9900
