### ISSUE TITLE
官网关于DataPicker  disabledDate 例子的一些问题

### ISSUE THREAD

**Issue by zjhjszwx** [ant-design/ant-design#19672]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-bouman-50rzc)

### Steps to reproduce
假设当前时间是2019-11-11 16:00
选中开始日期为2019-11-05 16:30:00， 则结束日期无法选中2019-11-05

### What is expected?
结束日期可以选中2019-11-05

### What is actually happening?
结束日期无法选中2019-11-05

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.8 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17964#issuecomment-517528811

**Comment by pro-xiaoy** [comment]
我也是遇到这个问题，不知道有没有解决的而方案
