### ISSUE TITLE
Pagination input page number show infinity value when change it max number

### ISSUE THREAD

**Issue by manyuanrong** [ant-design/ant-design#19670]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-cr2cg)

### Steps to reproduce
Input a very very big number

### What is expected?
should not be infinity value

### What is actually happening?
show infinity value
![image](https://user-images.githubusercontent.com/7514524/68568123-a8fccf00-0495-11ea-83c7-854fb0134708.png)
![image](https://user-images.githubusercontent.com/7514524/68568145-bd40cc00-0495-11ea-9e0e-dc9f0b15f7da.png)

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.11.0 |
| System | MacOS |
| Browser | Chrome |

---
only by simple mode

**Comment by afc163** [comment]
It works well now.

<img width="262" alt="image" src="https://user-images.githubusercontent.com/507615/76954562-800caf00-694b-11ea-81a6-1a6e9dc231dd.png">
