### ISSUE TITLE
antd v10.0.0 open状态的Modal组件在ie8浏览器按回车键会自动关闭，其他浏览器不会，这是bug？

### ISSUE THREAD

**Issue by haolee1990** [ant-design/ant-design#1967]
## What you did

Modal组件open状态下按了键盘回车键

## What you would like to happen

不应该有任何动作

## What actually happened

Modal组件被关闭了

## Environment Information

- The version of antd(e.g. 10.0.0):
- Your operating system and it's version(e.g. ubuntu 12):
- Your browser and it's version(e.g. IE8(64-bit)):

**Comment by benjycui** [comment]
`Modal` 的显隐是用 `visible` 控制的 http://ant.design/components/modal#API

估计是 IE8 下自动 focus 到关闭按钮上了，所以回车就触发了关闭事件。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
超过 5 天没有反馈，关了。
