### ISSUE TITLE
componentWillReceiveProps在新的react中即将被删除

### ISSUE THREAD

**Issue by hanhua1994** [ant-design/ant-design#19675]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://zh-hans.reactjs.org/docs/react-component.html](https://zh-hans.reactjs.org/docs/react-component.html)

### Steps to reproduce
message.info("2222");

### What is expected?
正常运行

### What is actually happening?
发出警告

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.11.0 |
| System | windows10 |
| Browser | Google Chrome |

---
注意:

下述方法即将过时，在新代码中应该避免使用它们：

UNSAFE_componentWillUpdate()
UNSAFE_componentWillReceiveProps()

**Comment by afc163** [comment]
Would be removed in 4.0 completely: https://github.com/ant-design/ant-design/issues/16911

**Comment by yoyo837** [comment]
Seems that it wants to delete `componentWillUpdate`, `componentWillReceiveProps` ... not `UNSAFE_componentWillUpdate `, `UNSAFE_componentWillReceiveProps `.
