### ISSUE TITLE
message's className still is 'ant-message' when ConfigProvider's prefixCls was setted 

### ISSUE THREAD

**Issue by Eward-Wang** [ant-design/ant-design#19674]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-01v7l)

### Steps to reproduce
none

### What is expected?
message's className prefixCls should be ConfigProvider's prefixCls;

### What is actually happening?
message's className is 'ant-message'

![image](https://user-images.githubusercontent.com/8791349/68574673-65aa5c80-04a5-11ea-86ff-1bd82c7b2457.png)

[it was fixed to 'ant-message' ?? ](https://github.com/ant-design/ant-design/blob/master/components/message/index.tsx#L9)

![image](https://user-images.githubusercontent.com/8791349/68574996-1f093200-04a6-11ea-92dc-066ef5f38842.png)

[and it only can be change by option??](https://github.com/ant-design/ant-design/blob/master/components/message/index.tsx#L139)

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.10.0 |
| System | all |
| Browser | all |

**Comment by yoyo837** [comment]
Duplicated of #19673
