### ISSUE TITLE
[Modal][v3.25.1] 开启弹窗页面偏移丢失

### ISSUE THREAD

**Issue by lich-yoo** [ant-design/ant-design#19676]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
官网必现

### What is expected?
body 滚动条消失，页面手动设置偏移量，页面不发生抖动偏移

### What is actually happening?
开启/关闭任意弹窗，页面抖动，出现偏移
![1](https://user-images.githubusercontent.com/18572962/68580827-1dde0200-04b2-11ea-90a5-bb534932b538.gif)

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | latest |
| System | window 7 |
| Browser | chrome |

---
之前版本应该没有问题

**Comment by afc163** [comment]
估计是这个导致的：https://github.com/ant-design/ant-design/pull/19233

**Comment by shaodahong** [comment]
No, caused by me, I will fix it

**Comment by jljsj33** [comment]
不是 19233 的问题...要把 https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L393 提到 overflow = 'hidden' 前面

**Comment by jljsj33** [comment]
@shaodahong pr 来一个

**Comment by yangdongMC** [comment]
> No, caused by me, I will fix it

你并没有完全修复，下面一个场景你没有覆盖到：
       当header 出现了固定定位，此时页面有弹框出现，header 部分还是会出现抖动。
问题重现：
       ant.design 的官网，将header 的定位方式换成fixed,width：100%。
建议：
       有可能这样的使用场景不多，建议将utils下switchScrollingEffect.js里面在body 上再增加一个class,这样就可以结合它来解决头部抖动问题

**Comment by shaodahong** [comment]
@yangdongMC 谢谢，我修复的是之前是好的，后来我改动造成了失效，你这个问题我建议重新开一个 Issue

**Comment by zzc-z** [comment]
:global {
  .ant-scrolling-effect {
    min-width: 100%;
  }
}

**Comment by zzc-z** [comment]
完美解决

**Comment by NaroXing** [comment]
> :global { .ant-scrolling-effect { min-width: 100%; } }

你是我  的 神！
