### ISSUE TITLE
Slider marks position is wrong when slider is reversed

### ISSUE THREAD

**Issue by franklinharvey** [ant-design/ant-design#19682]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-t4d90?fontsize=14)

### Steps to reproduce
Apply `marks` to a slider and then apply `reverse`

### What is expected?
`marks` on the slider should be aligned

### What is actually happening?
`marks` are not aligned when the slider is reversed

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.11.0 |
| System | MacOS Catalina 10.15 |
| Browser | Chrome 77 |

**Comment by yoyo837** [comment]
ref: #18708

**Comment by mllanka** [comment]
I would like to start working on this if possible, I am a newbie!

**Comment by yoyo837** [comment]
welcome
