### ISSUE TITLE
全局模式下message组件丢失

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#1968]
如题

**Comment by dyf2015** [comment]
notification 也无法调用了

**Comment by dyf2015** [comment]
externals: [
      {'react': 'React'},
      {'react-dom': 'ReactDOM'},
      {'antd': 'antd'}
  ],

**Comment by afc163** [comment]
确实有问题。https://github.com/ant-design/ant-design/commit/777692a207089d950f7c41b185e001814143bfdc 这里搞把大小写搞错了。

**Comment by dyf2015** [comment]
先把首字母该大写临时解决？

发自我的 iPhone

在 2016年6月5日，01:14，偏右 <notifications@github.com<mailto:notifications@github.com>> 写道：


确实有问题。777692a<https://github.com/ant-design/ant-design/commit/777692a207089d950f7c41b185e001814143bfdc> 这里搞把大小写搞错了。

―

**Comment by dyf2015** [comment]
谢谢，影响比较大，所以先自行修改掉。
