### ISSUE TITLE
使用 React hook，Table 动态列获取不到新的 useState

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design#19686]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-http-f51th?fontsize=14)

### Steps to reproduce
1、点击 name 列，打印的是默认的 default string
2、点击 Set Colume 按钮，将 table 添加一个 age 列
3、点击 Set Data 按钮，setdefaultData 一个新值，
4、点击 name 列，打印的是新值，state data
5、点击 age 列，打印的却是默认值 default string

### What is expected?
动态列，打印的更新后的 state 值

### What is actually happening?
动态列，打印的是默认值

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | react |
| System | macos |
| Browser | chrome |

**Comment by yoyo837** [comment]
与hooks无关，你可以这样`<Table columns={columns()} />`,  `columns` 指定成一个方法

**Comment by Benpaodejiezai** [comment]
> 与hooks无关，你可以这样`<Table columns={columns()} />`, `columns` 指定成一个方法

还是不行呀，只要是更新 columns 那么打印的就是不是 set 后的值

**Comment by yoyo837** [comment]
try https://codesandbox.io/s/intelligent-breeze-85u6d
