### ISSUE TITLE
使用表单包裹的Select组件的初始值能不能在组件内部判断，传递 '' 、null 、 undefined 都判定为空值

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#19695]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在表单中，使用Select组件，如果没有选择值，则这个数据为undefined，不会传递给后端，能不能传递的初始值为 `''` 、`null` 、 `undefined`，而且，后端返回的一般都是 null 或者 具体的值，null 和 undefined又匹配不上，'' 和 undefined也匹配不上，每次都需要大量的判断去给表单赋值

### What does the proposed API look like?
Select组件 getFieldDecorator 的 initialValue可以为 `''`  || ` null`  ||  `undefined`

**Comment by yoyo837** [comment]
> 需要大量的判断去给表单赋值

之所以需要这样，是你自己的业务需要（依赖了你的后台），比如我个人的业务，则没任何影响；

建议你应用内封装。

**Comment by XianZhengquan** [comment]
> > 需要大量的判断去给表单赋值
> 
> 之所以需要这样，是你自己的业务需要（依赖了你的后台），比如我个人的业务，则没任何影响；
> 
> 建议你应用内封装。

如果没有选择值，就为 `undefined` ，浏览器就会过滤掉这个字段，后端接收不到，传递的时候就需要判断一次，然后后端返回值，重新给表单赋值的时候，后端为 `null`，这时候又要重新判断一次，在Select组件特别多的情况下，工作量增大而且繁琐

**Comment by XianZhengquan** [comment]
> > 需要大量的判断去给表单赋值
> 
> 之所以需要这样，是你自己的业务需要（依赖了你的后台），比如我个人的业务，则没任何影响；
> 
> 建议你应用内封装。

我只是想知道为什么 `Select`组件的value一定要是 `undefined `

**Comment by yoyo837** [comment]
因为 `null` 和 `undefined` 不是一回事，现在前端基本都严谨处理这俩值, 但后台却没所谓；

**Comment by XianZhengquan** [comment]
> 因为 `null` 和 `undefined` 不是一回事，现在前端基本都严谨处理这俩值, 但后台却没所谓；

所以我就想 能不能 Select 内部 ，value 为[`''`, `null`, 'undefined'] 都是初始值。

**Comment by yoyo837** [comment]
不能哦，这是刻意为之。

**Comment by XianZhengquan** [comment]
> 不能哦，这是刻意为之。

也就只有我自己逐个去判断咯哦

**Comment by yoyo837** [comment]
你可以考虑用https://ant.design/components/form-cn/#Form.create(options) 时添加内部处理逻辑，让它三个同等对待。供你自己应用内使用。

**Comment by XianZhengquan** [comment]
> 你可以考虑用https://ant.design/components/form-cn/#Form.create(options) 时添加内部处理逻辑，让它三个同等对待。供你自己应用内使用。

看到这个API，我只能想到使用 `onFieldsChange` 进行处理

**Comment by XianZhengquan** [comment]
> 你可以考虑用https://ant.design/components/form-cn/#Form.create(options) 时添加内部处理逻辑，让它三个同等对待。供你自己应用内使用。

有点懵了，可以给一个 demo吗

**Comment by yoyo837** [comment]
直接封装个util方法，表单值取出来挨个判断一下加处理后给你后台行不？

**Comment by XianZhengquan** [comment]
> 直接封装个util方法，表单值取出来挨个判断一下加处理后给你后台行不？

这个可以
