### ISSUE TITLE
Allow Configuration of breakpoints in Layout Component

### ISSUE THREAD

**Issue by atanasgeorgiev93** [ant-design/ant-design#19694]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently there is no way for a developer to configure the breakpoints for the Layout component. This feature would allow to the developer to pass a property with the breakpoints to the Layout component, and the Layout would use these variables as breakpoints instead of the default ones.

**Note** - If issue is accepted, I am happy to contribute and raise a PR.

### What does the proposed API look like?
| Property | Description  | Type  | Default |
| ------------- |:-------------:| ---------:|  --------:|
| breakpoints | custom breakpoints for layout | ``` Object { xs: string , sm: string, md: string, lg: string, xl: string, xxl: string }```| ```{ xs: '480px', sm: '576px', md: '768px', lg: '992px', xl: '1200px', xxl: '1600px' }``` |

**Comment by atanasgeorgiev93** [comment]
I'm starting dev work on this

**Comment by OArnarsson** [comment]
@atanasgeorgiev93 any update on this? 🤓

**Comment by shadab14meb346** [comment]
@atanasgeorgiev93 are you working on this?
If you are busy or need if need some help I will be happy to do so.

**Comment by dabljues** [comment]
Also, it would be good to define additional breakpoints, like something below `xs` or above `xxl`

**Comment by kiril-daskalov** [comment]
UP

**Comment by YinglunQ** [comment]
would be great if we can customize our own breakpoints instead of following bootstrap's fixed breakpoints

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/39105
