### ISSUE TITLE
Modal.confirm中的okText，cancelText默认状态不是中文，而是英文

### ISSUE THREAD

**Issue by Agagy** [ant-design/ant-design#19692]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
打开confirm 对话框

### What is expected?
对话框内的按钮默认文字是中文的

### What is actually happening?
对话框内的按钮默认文字是英文的

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.11.0 |
| System | mac os |
| Browser | Firefox 70.0.1 |

**Comment by Agagy** [comment]
![68649559-ee84cf00-055d-11ea-8df7-0830e1d22069](https://user-images.githubusercontent.com/33778021/68651800-1dea0a80-0563-11ea-8763-5f6997b2670c.png)
![68649431-a9f93380-055d-11ea-9633-245705a60491](https://user-images.githubusercontent.com/33778021/68651802-1f1b3780-0563-11ea-8d0a-c771c7432171.png)
![68649389-90f08280-055d-11ea-887e-d045a25268d9](https://user-images.githubusercontent.com/33778021/68651803-1fb3ce00-0563-11ea-860e-dc959b6b6a5b.png)

**Comment by Agagy** [comment]
> Hello @Agagy. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @Agagy, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

官网上就有现成的例子，这个已经很明显了

**Comment by Agagy** [comment]
https://ant.design/components/modal-cn/

**Comment by yoyo837** [comment]
官网并不能复现

**Comment by Agagy** [comment]
> 官网并不能复现

![图片](https://user-images.githubusercontent.com/33778021/68653346-825a9900-0566-11ea-95e1-7dfdfc6eae5b.png)
这个是我当时候截的图，幸好留了个证据。。。

**Comment by Agagy** [comment]
我刚才复现了一下：
1、
![图片](https://user-images.githubusercontent.com/33778021/68653538-ebdaa780-0566-11ea-9cc0-a094358e14b3.png)
点击这个
2、再次切换到Modal

然后就出现这种情况了

**Comment by yoyo837** [comment]
当时是什么时候？因为之前确实有反馈这个问题；

可能和demo 干扰有关，一般情况下一个应用只需要一个`ConfigProvider`.

**Comment by Agagy** [comment]
我那样复现了之后，Modal基础组件和Modal.confirm打开的弹框按钮文字中英文也不一样，是不是哪里的默认值判断错了。

![图片](https://user-images.githubusercontent.com/33778021/68654632-51c82e80-0569-11ea-9780-b4cf7f8ad93c.png)

**Comment by Agagy** [comment]
我看了源码之后发现了点不一样的地方，希望有帮助：
1、confirm：
![图片](https://user-images.githubusercontent.com/33778021/68656122-2d218600-056c-11ea-9a11-70881ee03aa0.png)
2、modal：
![图片](https://user-images.githubusercontent.com/33778021/68656186-504c3580-056c-11ea-923b-eb1146ad52af.png)

**Comment by afc163** [comment]
Duplicate of #19517

**Comment by xiaodun** [comment]
可以看下这篇文章 [Umi2.x 中Modal.confirm底部按钮显示为中文](https://www.jianshu.com/p/3968ce87c1b7)

**Comment by stjdydayou** [comment]
官网也有这个问题，使用<Modal></Modal>的时候不会，但是使用Modal.method()的时候第一次点开不会，但是当你第一次关了，再次点击就出现了，官网也有这个问题，我也碰到了这个问题，希望能早日解决
