### ISSUE TITLE
pagination能够提供自定义文案

### ISSUE THREAD

**Issue by shenlm203** [ant-design/ant-design#197]
现在的分页中文案都是固定的，有时候产品要求的分页文案 分页组件提供的不一致，可否提供一个共性化的文案配置接口呢？

如在jumper之前，现在是没有文案的：{第10页}。 需要加上文案， 变成     **跳至**： {第10页}  。

**Comment by afc163** [comment]
我们希望少做这样的配置，最大程度的简化内部产品的差异性，所以才有了设计规范。如果你的产品已经有了成形的设计风格和交互要求，则不建议用 antd，只有满足 Ant Design 设计规范的后台产品才建议用这个框架。

**Comment by afc163** [comment]
这个可能不会修改，抱歉~

**Comment by shenlm203** [comment]
好的，这点可以理解
