### ISSUE TITLE
推荐一个在线编辑代码网站

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#19708]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What does the proposed API look like?

https://stackblitz.com/  这个网站下载依赖非常快，比 https://codesandbox.io 快多了，希望后面官网可以支持。

**Comment by afc163** [comment]
可以来个 PR

**Comment by wendzhue** [comment]
@afc163 如果 @qq645381995 没有时间的话我可以做这个，之前 Angular 那边用的就是 stackblitz 。

**Comment by qq645381995** [comment]
@wendzhue  我刚在看 api 在做测试，你做过的话那你加上吧。

**Comment by qq645381995** [comment]
@afc163 @wendzhue  我感觉要不把之前 riddle 的位置给 StackBlitz，然后 svg 当时是谁上传到 `https://gw.alipayobjects.com/zos/rmsportal/OtZslpOjYXijshDERXwc.svg` 地址的，再把这个也上传一下。

**Comment by afc163** [comment]
直接用 `<Icon type="thunderbolt" />` 就行了，riddle 还是要留着，内部用得上。

**Comment by qq645381995** [comment]
@afc163 @wendzhue #19714

**Comment by wendzhue** [comment]
@qq645381995 👍

**Comment by afc163** [comment]
<img width="629" alt="image" src="https://user-images.githubusercontent.com/507615/68751193-23ffea00-063c-11ea-90ed-65d253b54de0.png">

有了！👍

**Comment by yoyo837** [comment]
站点的部署时机是怎样的？手动触发吗？还是。。。？

**Comment by orzyyyy** [comment]
release 的时候机器人发布，下次是这周末

**Comment by qq645381995** [comment]
@afc163 其实可以有个 master 站点可以访问的地址。

**Comment by orzyyyy** [comment]
@qq645381995 你发的 pr 里，nelify 部署的就能访问了

**Comment by yoyo837** [comment]
那刚才#19714 的合入是手动触发的吧？

**Comment by afc163** [comment]
这次是我手动的，自动部署其实一直有个 https://ant-design.netlify.com 在跑。

**Comment by qq645381995** [comment]
ok

**Comment by yoyo837** [comment]
那个PR 预览的部署我知道，就是不知道主站部署时机，所以问问。

**Comment by jljsj33** [comment]
额，，icon 真多哦。。。卖 icon 吗？？

**Comment by yoyo837** [comment]
设计师应该是不喜欢那么重复功能的icon。

**Comment by qq645381995** [comment]
不喜欢映入眼帘的，那应该用 ... 默认隐藏，页面只吐出 1、2 个。

**Comment by yoyo837** [comment]
这些事情antd team内部决断，咱们都散了吧。

**Comment by orzyyyy** [comment]
别啊，我想学一下这类“对功能相似的 icon”的处理方式...哪怕没个准确结论，看看过程也是好的。

我是觉着该给这三个代码演示的 icon 跟剩下两个演示代码的 icon 加个分割线，方便识别，应该算不错。

**Comment by yoyo837** [comment]
主编码的人设计感一般偏差，设计师会code的倒是挺多。 反正我个人对视觉和用户体验的思维一塌糊涂。
