### ISSUE TITLE
set a fixed height for table 

### ISSUE THREAD

**Issue by prince1456** [ant-design/ant-design#19705]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
currently if the data is small and table height will decrease to the number of row we have. 
if we could set height to table we can have same table with same height even if we have just one record in our data.

### What does the proposed API look like?
<Table
defaultHeight= "300"
/>

**Comment by afc163** [comment]
`<Table scroll={{ y: 300 }} />`

**Comment by prince1456** [comment]
![Screen Shot 2019-11-13 at 11 41 30 AM](https://user-images.githubusercontent.com/20523380/68798074-9952c700-060a-11ea-8f61-545ec747ea9d.png)
I set <Table scroll={{ y: 400  }} /> but as you see my table still is so small when i have just one row in my table :(

**Comment by mellis481** [comment]
This shouldn't be closed. `scroll={{ y: 400 }}` does not solve the reported issue which has merit.

**Comment by drex44** [comment]
Reopen this please!

**Comment by weeklyTea** [comment]
The only way I've found is setting height in table style: `style={{ height: '400px' }}`, maybe it would help someone..

**Comment by blephy** [comment]
This is really paintfull. I have a lot of table with nzLoading properties and : 
- When no data is set / found, i would be able to set a min-height to print "no-data" state
- When new data is loading and no data was set, the loader is on the table header.

How can i fix the header please ? I try so many things.

**Comment by b-zac** [comment]
> The only way I've found is setting height in table style: `style={{ height: '400px' }}`, maybe it would help someone..

Doesn't work. It stretches the height of <tr> elements even if you set max-height on them.

**Comment by balboFK** [comment]
Hello everybody!
I also think this shouldn't be closed.
For my workaround right now, im using both properties as follows:

`style={{ height: '400px' }}`
and 
`scroll={{ y: 400 }}`

But. even with this, sometimes the scroll height is bigger than the table size, and the rows overlap the table bottom.

Antd should provide a way to set the fixed height of a table, and in cases where we have only one record, the table should stay the same height as we defined, otherwise, if our content has more rows than the size of the table, the table should automatically set the scroll Y to active, since this property right now seems to be the one in charge of handling the table height.

**Comment by blephy** [comment]
Maybe ant should subscribe for a height event and recompute the table.

**Comment by balboFK** [comment]
@afc163 any news on this topic? Still not fixed and my workaround stop working aswell.
Could you please help?

**Comment by kellerdebord** [comment]
> @afc163 any news on this topic? Still not fixed and my workaround stop working aswell.
> Could you please help?

A bad solution would be to add blank rows by pushing an empty object onto your `dataSource` array. I tried this method and it works, but if you don't define the height of the blank rows the height is small.

**Comment by kellerdebord** [comment]
> @afc163 any news on this topic? Still not fixed and my workaround stop working aswell.
> Could you please help?

A bad solution would be to add blank rows by pushing an empty object onto your `dataSource` array. I tried this method and it works, but if you don't define the height of the blank rows (which you can) the height is small. Another issue with this is that you need to account for any custom rendering you have using the `dataSource`. Instead of pushing an empty object, you could push something like `{blankRow: true}` and use that as your check or you could just leave it blank and account for null.

**Comment by ozgurkisa** [comment]
maybe it will work for you...

```
html, body{
     height: 100vh;
}

.ant-table-wrapper {
    height: 100%;
    overflow: hidden;
  
    .ant-spin-nested-loading {
      height: 100%;
  
      .ant-spin-container {
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          height: 100%;
          
          .ant-table {
              max-height: 90%;
              overflow: auto;
          }
      }
    }
  }
```

**Comment by sajinsha9595** [comment]
> The only way I've found is setting height in table style: `style={{ height: '400px' }}`, maybe it would help someone..

not working

**Comment by matood** [comment]
Thanks to @ozgurkisa 

Since: ALL class names in the CSS file changed their names
I changed a little here.

```ts
import style from "./index.module.scss";
```

```html
<Table className={style.table}></Table>
```

in index.module.scss fle:

```scss
.table {
  > div {
    height: 600px;

    > div {
      height: 600px;

      > div {
        height: 600px;

        > div {
          min-height: 547px;
        }
      }
    }
  }
}
```

600px works in my situation, you can change to your specified settings.

**Comment by voigtito** [comment]
I just set an "id" on the table as `table-fixed-height` and added to the global or module css class:

```
#table-fixed-height tbody{
  height: 400px;
}
```

Not the best solution, but it works for me for now

**Comment by dsoklic** [comment]
I agree with the other comments, this issue isn't resolved and should be reopened.

**Comment by thisisaj1999** [comment]
> maybe it will work for you...
> 
> ```
> html, body{
>      height: 100vh;
> }
> 
> .ant-table-wrapper {
>     height: 100%;
>     overflow: hidden;
>   
>     .ant-spin-nested-loading {
>       height: 100%;
>   
>       .ant-spin-container {
>           display: flex;
>           flex-direction: column;
>           justify-content: space-between;
>           height: 100%;
>           
>           .ant-table {
>               max-height: 90%;
>               overflow: auto;
>           }
>       }
>     }
>   }
> ```

Thanks for your help, this worked like magic 🙌🏼

**Comment by MeroZemory** [comment]
> maybe it will work for you...
> 
> ```
> html, body{
>      height: 100vh;
> }
> 
> .ant-table-wrapper {
>     height: 100%;
>     overflow: hidden;
>   
>     .ant-spin-nested-loading {
>       height: 100%;
>   
>       .ant-spin-container {
>           display: flex;
>           flex-direction: column;
>           justify-content: space-between;
>           height: 100%;
>           
>           .ant-table {
>               max-height: 90%;
>               overflow: auto;
>           }
>       }
>     }
>   }
> ```

I made some improvements—give it a try and see if it works for you guys!

```
.ant-table-wrapper {
  height: 100%;
  overflow: hidden;

  .ant-spin-nested-loading {
    height: 100%;

    .ant-spin-container {
      display: flex;
      flex-direction: column;
      height: 100%;

      .ant-table {
        height: 100%;
        overflow: hidden;
        flex: 1;

        .ant-table-container {
          height: 100%;
          overflow: hidden;
          display: flex;
          flex-direction: column;

          .ant-table-header {
            flex: 0 0 auto;
          }

          .ant-table-body {
            flex: 1;
            min-height: 0;
            overflow: auto;
          }
        }
      }
    }
  }
}
```

**Comment by mnlfischer** [comment]
@afc163 statement? 
@all just use other libs, antd is in a bad state.

**Comment by Duke0503** [comment]
I found a simple workaround that doesn’t require hacking deep into `.ant-spin-container` or wrapping the entire table.

```tsx
<Table
  className=" [&_.ant-table-body]:min-h-[300px]"
  dataSource={data}
  columns={columns}
  scroll={{ y: 400 }}
/>

**Comment by LiuZHolmes** [comment]
Antd maintainer always close issue without confirming if the issue is resolved
