### ISSUE TITLE
Add a droppable prop to a TreeNode to allow/deny dropping on a node

### ISSUE THREAD

**Issue by guidogast** [ant-design/ant-design#19702]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At the moment, you can turn on `draggable`, but it doesn't allow you to disable nodes for dropping. I would like to have the ability to deny specific nodes to be dropped on.

A use case could be like this:

- Level 1-0 `index: 0`
  - Level 2-0 `index: 1`
  - Level 2-1 `index: 2`
     - Level 3-0 `index: 3`
     - Level 3-1 `index: 4`
- Level 1-1 `index: 5`
   - Level 2-2 `index: 6`
      - Level 3-2 `index: 7`
      - Level 3-3 `index: 8`

I don't want the levels to be able to change, however, they may change position. `index 0` can swap with `index 5` (since it doesn't change levels) and `index 3` can swap with `index 4`, `index 7` and `index 8`. But you can't swap `index 0` with `index 6`, since they're on different levels.

### What does the proposed API look like?
A `droppable: boolean` prop on the TreeNode would be great to achieve this. When `droppable` is `true`, you may drop the node on it. When it's `false`, you're not able to drop on that Node (Including it's children). The default value of `droppable` would be `true`.

**Comment by guidogast** [comment]
Is there any progress on this feature?

**Comment by guidogast** [comment]
Still nothing?

**Comment by zombieJ** [comment]
Duplicate of #15926
