### ISSUE TITLE
下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题

### ISSUE THREAD

**Issue by 93336406** [ant-design/ant-design#19707]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/;https://ant.design/components/select-cn/](https://ant.design/components/tree-select-cn/;https://ant.design/components/select-cn/)

### Steps to reproduce
带搜索的下拉框，输入关键字查询时，由于浮动列表高度变化重新定位，此时搜索框新输入的值在最左边，初步怀疑是搜索框重获焦点时光标定位在最左边的问题。

### What is expected?
期望光标定位在搜索框值的最右边

### What is actually happening?
光标定位在搜索框值的最左边

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16 |
| System | window10 |
| Browser | ie11 |

**Comment by xrkffgg** [comment]
我看到的交互都是靠左边的啊，没有输入是靠右的

**Comment by 93336406** [comment]
您好，如果下拉框面板高度是随着搜素条件变化在变化，面板显示有个自适应，如果内容多的时候，面板稍高，下面不够显示，就会显示在选择框上方，一旦检索内容少了，面板高度变低，面板会跳到下方，这时搜索框里的光标就会跳到最左




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 下午4:42
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)




我看到的交互都是靠左边的啊，没有输入是靠右的
 
&mdash;

**Comment by 93336406** [comment]
您好，如果下拉框面板高度是随着搜素条件变化在变化，面板显示有个自适应，如果内容多的时候，面板稍高，下面不够显示，就会显示在选择框上方，一旦检索内容少了，面板高度变低，面板会跳到下方，这时搜索框里的光标就会跳到最左。如果面板的位置不变则是正常的。




------------------ 原始邮件 ------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 下午4:42
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)




我看到的交互都是靠左边的啊，没有输入是靠右的

**Comment by xrkffgg** [comment]
我看下拉的选项，设了一个最大高度是 250px , 超过就有滚动条啊

**Comment by 93336406** [comment]
嗯，滚动条是有。面板的高度不是固定的，默认下拉面板会显示在选择框的下方，那如果页面下方如果容不下面板，则会重新定位到选择框的上方去。如果这个位置变化后，搜索框里的光标就会定位到最左边。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 晚上6:05
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)




我看下拉的选项，设了一个最大高度是 250px , 超过就有滚动条啊
 
&mdash;

**Comment by xrkffgg** [comment]
如果这个下拉框位于屏幕底部，我觉得可以直接设置下拉框从上面显示





------------------ 原始邮件 ------------------
发件人: 93336406 <notifications@github.com&gt;
发送时间: 2019年11月14日 18:09
收件人: ant-design/ant-design <ant-design@noreply.github.com&gt;
抄送: xrkffgg <xrkffgg@vip.qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)

**Comment by 93336406** [comment]
就是位置不确定呢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 晚上6:13
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)



如果这个下拉框位于屏幕底部，我觉得可以直接设置下拉框从上面显示 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 93336406 <notifications@github.com&amp;gt; 
 发送时间: 2019年11月14日 18:09 
 收件人: ant-design/ant-design <ant-design@noreply.github.com&amp;gt; 
 抄送: xrkffgg <xrkffgg@vip.qq.com&amp;gt;, Comment <comment@noreply.github.com&amp;gt; 
 主题: 回复：[ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707) 
&mdash;

**Comment by xrkffgg** [comment]
你的意思是，当已经有了选项了之后，如果这时下拉框发生改变，光标会变成最左边，而不是你选项的右边？





------------------ 原始邮件 ------------------
发件人: 93336406 <notifications@github.com&gt;
发送时间: 2019年11月14日 18:20
收件人: ant-design/ant-design <ant-design@noreply.github.com&gt;
抄送: xrkffgg <xrkffgg@vip.qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)



就是位置不确定呢 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "xrkffgg"<notifications@github.com&amp;gt;;  
 发送时间: 2019年11月14日(星期四) 晚上6:13 
 收件人: "ant-design/ant-design"<ant-design@noreply.github.com&amp;gt;;  
 抄送: "易成(Esong)"<93336406@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;;  
 主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707) 
 
 
 
 如果这个下拉框位于屏幕底部，我觉得可以直接设置下拉框从上面显示  
   
   
   
   
   
  ------------------ 原始邮件 ------------------  
  发件人: 93336406 <notifications@github.com&amp;amp;gt;  
  发送时间: 2019年11月14日 18:09  
  收件人: ant-design/ant-design <ant-design@noreply.github.com&amp;amp;gt;  
  抄送: xrkffgg <xrkffgg@vip.qq.com&amp;amp;gt;, Comment <comment@noreply.github.com&amp;amp;gt;  
  主题: 回复：[ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)  
 &amp;mdash;

**Comment by 93336406** [comment]
嗯，是的，下拉框位置如果由下方自动调整到上方时，或由上方调整到下方时，搜索框里的光标就会跑到最左边。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月14日(星期四) 晚上6:25
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)



你的意思是，当已经有了选项了之后，如果这时下拉框发生改变，光标会变成最左边，而不是你选项的右边？ 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 93336406 <notifications@github.com&amp;gt; 
 发送时间: 2019年11月14日 18:20 
 收件人: ant-design/ant-design <ant-design@noreply.github.com&amp;gt; 
 抄送: xrkffgg <xrkffgg@vip.qq.com&amp;gt;, Comment <comment@noreply.github.com&amp;gt; 
 主题: 回复：[ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707) 
 
 
 
 就是位置不确定呢  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: &quot;xrkffgg&quot;<notifications@github.com&amp;amp;gt;;   
  发送时间: 2019年11月14日(星期四) 晚上6:13  
  收件人: &quot;ant-design/ant-design&quot;<ant-design@noreply.github.com&amp;amp;gt;;   
  抄送: &quot;易成(Esong)&quot;<93336406@qq.com&amp;amp;gt;; &quot;Mention&quot;<mention@noreply.github.com&amp;amp;gt;;   
  主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)  
   
   
   
  如果这个下拉框位于屏幕底部，我觉得可以直接设置下拉框从上面显示   
     
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: 93336406 <notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2019年11月14日 18:09   
   收件人: ant-design/ant-design <ant-design@noreply.github.com&amp;amp;amp;gt;   
   抄送: xrkffgg <xrkffgg@vip.qq.com&amp;amp;amp;gt;, Comment <comment@noreply.github.com&amp;amp;amp;gt;   
   主题: 回复：[ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)   
  &amp;amp;mdash;  
  You are receiving this because you were mentioned.  
  Reply to this email directly, view it on GitHub, or unsubscribe.  
 — 
 You are receiving this because you commented. 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
&mdash;

**Comment by 93336406** [comment]
您好，我录了个视屏，您看看呢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xrkffgg"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 晚上6:25
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"易成(Esong)"<93336406@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)



你的意思是，当已经有了选项了之后，如果这时下拉框发生改变，光标会变成最左边，而不是你选项的右边？ 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 93336406 <notifications@github.com&amp;gt; 
 发送时间: 2019年11月14日 18:20 
 收件人: ant-design/ant-design <ant-design@noreply.github.com&amp;gt; 
 抄送: xrkffgg <xrkffgg@vip.qq.com&amp;gt;, Comment <comment@noreply.github.com&amp;gt; 
 主题: 回复：[ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707) 
 
 
 
 就是位置不确定呢  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "xrkffgg"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2019年11月14日(星期四) 晚上6:13  
  收件人: "ant-design/ant-design"<ant-design@noreply.github.com&amp;amp;gt;;   
  抄送: "易成(Esong)"<93336406@qq.com&amp;amp;gt;; "Mention"<mention@noreply.github.com&amp;amp;gt;;   
  主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)  
   
   
   
  如果这个下拉框位于屏幕底部，我觉得可以直接设置下拉框从上面显示   
     
     
     
     
     
   ------------------ 原始邮件 ------------------   
   发件人: 93336406 <notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2019年11月14日 18:09   
   收件人: ant-design/ant-design <ant-design@noreply.github.com&amp;amp;amp;gt;   
   抄送: xrkffgg <xrkffgg@vip.qq.com&amp;amp;amp;gt;, Comment <comment@noreply.github.com&amp;amp;amp;gt;   
   主题: 回复：[ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)   
  &amp;amp;mdash;

**Comment by xrkffgg** [comment]
@93336406 
https://codepen.io/xrkffgg/pen/abbQboW

这个例子里
- 你先输入一项
- 然后点击 Add item 
- 下拉框就会从下方变成上方
- 输入框内，光标是正常的啊

**Comment by 93336406** [comment]
搜素框需要在浮动面板上



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 中午11:31
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)




@93336406
 https://codepen.io/xrkffgg/pen/abbQboW
 
这个例子里
  
你先输入一项
 
然后点击 Add item
 
下拉框就会从下方变成上方
 
输入框内，光标是正常的啊
  
&mdash;

**Comment by xrkffgg** [comment]
你写个例子看看

**Comment by 93336406** [comment]
我写了例子，您看看呢。https://codesandbox.io/embed/wizardly-ganguly-6383l?fontsize=14&amp;hidenavigation=1&amp;theme=dark




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 中午11:41
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)




你写个例子看看
 
&mdash;

**Comment by xrkffgg** [comment]
用你例子试了下

![](https://github.com/xrkffgg/Kimg/blob/master/ant-design/2019.11/select.gif?raw=true)

- 光标在输入前后没有变化啊，是在输入内容的右侧啊，没有变到左侧啊。。。。

**Comment by 93336406** [comment]
主要是ie11及以下的浏览器才会有这种情况




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 下午5:13
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)




用你例子试了下
 

  
光标在输入前后没有变化啊，是在输入内容的右侧啊，没有变到左侧啊。。。。
  
&mdash;

**Comment by xrkffgg** [comment]
😂😂😂 ie11 打扰了

**Comment by 93336406** [comment]
，这个是什么原因造成的呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 下午5:24
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)




😂😂😂 ie11 打扰了
 
&mdash;

**Comment by xrkffgg** [comment]
兄弟为啥这么想不开，要用IE

**Comment by 93336406** [comment]
客户要用，没办法呀






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2019年11月15日(星期五) 下午5:33
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "易成(Esong)"<93336406@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 下拉框和下拉树的搜索框获取焦点后光标定位到最左的问题 (#19707)




兄弟为啥这么想不开，要用IE
 
&mdash;

**Comment by meng556677** [comment]
我也遇到和上述一模一样的问题，IE11上就会有，怎么解决呢？谢谢

**Comment by hxswen** [comment]
> 我也遇到和上述一模一样的问题，IE11上就会有，怎么解决呢？谢谢

请问解决了吗？？？

**Comment by afc163** [comment]
请试一试 4.x 版本，3.x 不再维护了。
