### ISSUE TITLE
Icons disappear after page load

### ISSUE THREAD

**Issue by agnesching19** [ant-design/ant-design#19704]
### Reproduction link
[https://www.staging.fixter.co.uk/the-five-footballers-who-play-the-fewest-minutes-to-afford-their-most-expensive-car#MostExpensiveCarsFleet](https://www.staging.fixter.co.uk/the-five-footballers-who-play-the-fewest-minutes-to-afford-their-most-expensive-car#MostExpensiveCarsFleet)

### Steps to reproduce
Just click through the link above, you'll find 2 tables displayed.

### What is expected?
Being able to see the "caret-up" and "caret-down" icons the thead of the tables in this page.

### What is actually happening?
The icons in the "thead > tr > th .ant-table-column-sorter" div on the tables created with ant-design tables disappear after page load. Yet when you refresh the page, you will be able to see the icons for a few seconds. Actually not only these two "caret-up" and "caret-down" icons; tried to use other icons from ant design, many of which had the same issue.

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.8.6 |
| System | Node 10.9.0 |
| Browser | Chrome Version 78.0.3904.87 |

**Comment by yoyo837** [comment]
Online code demo, please.
