### ISSUE TITLE
MenuItemGroupProps's title type should be string | React.ReactNode as per the docs, but is only 'string'

### ISSUE THREAD

**Issue by gregoryforel** [ant-design/ant-design#19716]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu/#Menu.ItemGroup](https://ant.design/components/menu/#Menu.ItemGroup)

### Steps to reproduce
Try use this piece of code in a `Menu`:

```
    <Menu.ItemGroup key='g1' title={<div>Test</div>}>
        <Menu.Item key='1'>Option 1 <Button onClick={(e) =>{e.stopPropagation();  alert('hello')}}>Test</Button></Menu.Item>
        <Menu.Item key='2'>Option 2</Menu.Item>
    </Menu.ItemGroup>
```

### What is expected?
It should not give a warning

### What is actually happening?
It gives a warning that `title` should be a `string`

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.10.1 |
| System | Windows 10 x64 Version 1803 - OS Build 17134.706 |
| Browser | Chrome 73.0.3683.103 (Official Build) (64-bit) |

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/68757641-39c6dc80-0647-11ea-86a2-9d71cbe0529e.png)

Can't reproduce

**Comment by Clafouti** [comment]
This typings issue is still bundled with antd 3.26.2
The issue comes from the package rc-menu, but since antd uses rc-menu 7.5.1, I'm not sure I can go on the corresponding github page to create an issue...

Anyway, here are the typings :

`
export interface MenuItemGroupProps {
    disabled?: boolean;
    renderMenuItem?: (item: React.ReactElement, index: number, key: string) => React.ReactElement;
    index?: number;
    className?: string;
    subMenuKey?: string;
    rootPrefixCls?: string;
    title?: string;
    onClick?: MenuClickEventHandler;
}
`

As you can see, the title is specified as `string` and it should be `string | React.ReactNode`

**Comment by ricky-at-genomics-england** [comment]
This was an issue as late as v3.26.20. It's definitely reproducible, and confounded by the fact that the feature now appears to be based on a sub-dependency called RC Menu - https://github.com/fis-components/rc-menu.
