### ISSUE TITLE
1.3.0 modal中用upload,报错如下：

### ISSUE THREAD

**Issue by ZXiner** [ant-design/ant-design#1971]
#1942 提到这个issue，升级成1.3.0, upload还是有如下警告：
1. Warning: validateDOMNesting(...): <form> cannot appear as a descendant of <form>. See AddBanner > Form > form > ... > Upload > Upload > AjaxUploader > form
2. modal里用upload， 还会直接报错：
main_newba4.0.js:16122 Uncaught Invariant Violation: findComponentRoot(..., .1.1.$dialog.0.2.0.0.$wrapper.0.0:$/=10.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.

**Comment by wwlweihai** [comment]
同样，也遇到这个问题，我是在 form 自定义了一个 包装了Upload的组件，还是遇到这个问题了。求解答

**Comment by afc163** [comment]
使用 npm 的话，重新 install 即可解决。

使用 dist 里的预构建文件的话，就需要等下一个版本发布。
