### ISSUE TITLE
如何在ant-design中实现下载

### ISSUE THREAD

**Issue by cc18314552041** [ant-design/ant-design#19712]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
文件下载功能

### What does the proposed API look like?
对于后端返回的文件流，实现自动开始下载

**Comment by yoyo837** [comment]
#19711

**Comment by yoyo837** [comment]
描述与 antd 无关。

**Comment by yoyo837** [comment]
挂个a标签、url直接post到新窗口也可以，很简单的，antd/react都无关。

**Comment by cc18314552041** [comment]
太感谢你了，没想到会收到回复。谢谢哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;; 
发送时间: 2019年11月13日(星期三) 中午11:47
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "陈畅"<1204477670@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 如何在ant-design中实现下载 (#19712)




挂个a标签、url直接post到新窗口也可以，很简单的，antd/react都无关。
