### ISSUE TITLE
Row flex mode set vertical gutter invalid

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#19728]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-grid-flex-mode-fys0h)

Ref: https://github.com/ant-design/ant-design/pull/16635#issuecomment-553475822

### Steps to reproduce
1. open codesandbox demo

2. compare float and flex mode Row vertical gutter

### What is expected?
vertical gutter valid

### What is actually happening?
vertical gutter invalid

| Environment | Info |
|---|---|
| antd | 3.25.1, 4.0 |
| React | 16.3 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by shaodahong** [comment]
@afc163 @zombieJ Help me check this is bug?

**Comment by xrkffgg** [comment]
In my environment(win10 chrome 78.0.3904.97), it's like this:

![](https://github.com/xrkffgg/Kimg/blob/master/ant-design/2019.11/row-float.png?raw=true)

Vertical gutter invalid

**Comment by shaodahong** [comment]
yep, me too, this is antd site demo

**Comment by zombieJ** [comment]
In my view, `gutter` only works on the Col of Row.  Flex view seems correct than the float one:
<img width="519" alt="截屏2019-11-14下午5 47 20" src="https://user-images.githubusercontent.com/5378891/68845767-e025e700-0706-11ea-9e0b-36b7ba87dbbe.png">

@afc163 , pls double confirm
