### ISSUE TITLE
Form 组件项目过多的时候巨卡。。

### ISSUE THREAD

**Issue by Maopy** [ant-design/ant-design#1972]
![image](https://cloud.githubusercontent.com/assets/4091726/15805646/436faa72-2b63-11e6-83b0-47d37471c87d.png)
如图，使用了RadioGroup CheckboxGroup
现在单选和复选框每点一项大概一秒之后才触发被选中的效果
Input组件输入也是每输入一个字符就卡很久
当我尝试删除，只保留少量组件的时候，卡顿的现象就消失了

**Comment by benjycui** [comment]
@superRaytin 优化下性能。

**Comment by afc163** [comment]
最好也看下使用代码可否有优化的地方。

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by superRaytin** [comment]
我先尝试复现分析一下...

**Comment by superRaytin** [comment]
我试着写了一个 demo：http://codepen.io/superRaytin/pen/YWXmJY?editors=0010

貌似重现不了 `卡顿` 的现象。 @Maopy 方便的话麻烦用楼上的 codepen 贴下你的代码，方便我们定位。 😄

**Comment by Maopy** [comment]
http://codepen.io/maopy208/pen/aZvbjr?editors=0010
@superRaytin 简单粘了一下。。搞得有点乱~

**Comment by Maopy** [comment]
@superRaytin 我没用getFieldProps的时候不卡，加上就卡了~ 然后我没用Form组件的时候，自己在onChange里面setState也会卡，不setState就不卡。。

**Comment by benjycui** [comment]
问题应该是大量的组件 re-render 的原因。

**Comment by benjycui** [comment]
@superRaytin Checkbox 和 Radio 都加上 `shouldComponentUpdate`?

`Form` 和 `Form.Item` 这边我也补上。

**Comment by superRaytin** [comment]
@benjycui OK

**Comment by superRaytin** [comment]
Github 可以 assign 给多人了，正好试一下 😂

**Comment by benjycui** [comment]
* [ ] Checkbox
* [ ] Radio
* [ ] Form.Item
* [ ] Form

**Comment by superRaytin** [comment]
那些可能会被大量复制，并且有用户交互的组件，都需要做这个处理。

**Comment by yiminghe** [comment]
确认加 shouldComponentUpdate 行么？ checkbox 很简单，rerender 应该也不费时间

**Comment by afc163** [comment]
来一波性能测试 https://facebook.github.io/react/docs/perf.html 试试。

**Comment by yiminghe** [comment]
这个问题应该拆分 form 解决，一个 form 内不要有很多组件

**Comment by afc163** [comment]
@superRaytin 的例子里没加 key 。

**Comment by superRaytin** [comment]
加上了。。

**Comment by afc163** [comment]
没加 key 会重新渲染，看看是否加上 key 就没性能问题了。

**Comment by wuhaih** [comment]
Form 组件项目过多的时候巨卡 我的也是，经分析原因是 form表单只要FormItem里面添加的组件有更新，整个form表单都会更新，应该要控制做局部更新，谁有方案

**Comment by yesmeck** [comment]
很复杂的表单的值放在一个 state 里确实会有性能问题（https://github.com/erikras/redux-form/issues/529），我们目前的做法就是切分 form，然后自己写`shouldComponentIUpdate`。

**Comment by huangyingjie** [comment]
我觉得可以引进mobx，只更新局部。

**Comment by linjieAda** [comment]
我还以为是我代码写的有问题，才导致大表单巨卡，这里标记一下

**Comment by AdamChrist** [comment]
我之前遇到一个动态的表单大概有200个字段,也是很卡..后来改成.不控制表单的状态.给他每个表单加上onChange的监听..把表单的值放到redux中.这样就不卡了..因为改变表单的时候不会触发render.

**Comment by batouy** [comment]
目前是通过拆分表单来优化的，比较痛苦，需要修改的地方比较多，表单复杂的情况下，有些组件还要重构

**Comment by bluetomlee** [comment]
100个列表不到，巨卡

**Comment by zuiidea** [comment]
感受到了，打字卡顿
