### ISSUE TITLE
开启弹窗页面偏移丢失 没有被完全修复

### ISSUE THREAD

**Issue by yangdongMC** [ant-design/ant-design#19729]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/getting-started](https://ant.design/docs/react/getting-started)

### Steps to reproduce
下面一个场景没有覆盖到：  
      &emsp;&emsp;当header 出现了固定定位，此时页面有弹框出现，header 部分还是会出现抖动。  
问题重现：  
    &emsp;&emsp; ant.design 的官网，将header 的定位方式换成fixed,width：100%。  
建议：  
     &emsp;&emsp;有可能这样的使用场景不多，建议将utils下switchScrollingEffect.js里面在body 上再增加一个class,这样就可以结合它来解决头部抖动问题

### What is expected?
期望当页面又固定的定位的元素，例如header,不能受弹框出现（设置了body的样式）而发生抖动问题。

### What is actually happening?
由于是固定定位，body里面的计算宽度，影响不到固定定位的元素，导致最后在设置滚动条overflow：hidden的时候，固定定位元素出现了抖动。

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.11.0 |
| System | mac ios |
| Browser | chrome |

**Comment by jljsj33** [comment]
这种加个 body { transform: translate(0,0); } 就能解决了。。。不用加 className，有些东西外部能解决的就外部解决，，方法里不要涉及太多功能。。

**Comment by shaodahong** [comment]
不行的，transform 我知道会影响定位元素，但是也会影响到 modal，留个白边太难看了

jiang <notifications@github.com>于2019年11月14日 周四19:22写道：

**Comment by shaodahong** [comment]
这个我第一时间想到的也是 transform 来干扰定位元素, 而且 transform 的兼容性也很好, 但是很难兼容现在的这个, width 肯定是需要的, 不然就会抖动, 但是加了 width 就会有白边 @jljsj33 有没有什么好的解决方案

![image](https://user-images.githubusercontent.com/14831261/68861690-02c7f800-0727-11ea-89a1-3a87737f97b5.png)

**Comment by jljsj33** [comment]
恩。。。。好吧，，，我犯混了。。。那就加吧。。。

**Comment by shaodahong** [comment]
嗯, 加个 effect class, 以后用户有这种需要兼容的可以自行搞定

**Comment by jljsj33** [comment]
改了下，，用 switch-scrolling-effect

**Comment by jljsj33** [comment]
单词拼错了

**Comment by jljsj33** [comment]
4.15.6

**Comment by yangdongMC** [comment]
> 这种加个 body { transform: translate(0,0); } 就能解决了。。。不用加 className，有些东西外部能解决的就外部解决，，方法里不要涉及太多功能。。@shaodahong

外部解决可以这样,但是每个调用者遇到这样的问题都要在组件里面写一遍，有点冗余。
```
componentDidMount() {
    const bodyObserver = document.querySelector('body');
    this.customObserver = new MutationObserver(function(){
      const headerNode = document.querySelector('.layout-header');
      const bodyStyle = document.querySelector('body');
      if(bodyStyle.style.width.includes('calc')){
        headerNode.style.width = 'calc(100% - 15px)'
      }else{
        headerNode.style.width = '100%'
      }
      
      
    });
    const customObserverConfig = {
      attributes:true
    }
    this.customObserver.observe(bodyObserver,customObserverConfig);
  }
componentWillUnmount(){
    this.customObserver.disconnect();
  }
```
