### ISSUE TITLE
文档的描述是否有点不太妥当

### ISSUE THREAD

**Issue by lmxyjy** [ant-design/ant-design#19724]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---
![image](https://user-images.githubusercontent.com/48620706/68820871-a386cb00-06c7-11ea-9600-17a77151c2b5.png)
适应文本高度的文本域
autoSize 属性适用于 textarea 节点，并且只有高度会自动变化。另外 autoSize 可以设定为一个对象，指定最小行数和最大行数。

**3.24.0 后 autosize 被废弃，请使用 autoSize。**

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by yoyo837** [comment]
只是做个重命名
