### ISSUE TITLE
Cascader 中间disabled 是否可以让其可以展开，只是不能选中作为值。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#19725]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有这种需求，比如 省市区（县），我必须要用户选择 第三级，也就是 区（县）级别，选择省或者市是不行的，但是如果我在省市 的option上面加上disabled ，那么连展开都不会展开了。。但是我不设置为disabled。用户又可以选择省作为值。。

### What does the proposed API look like?
希望可以让Cascader 支持只能选择某一个纬度的值。

**Comment by shaodahong** [comment]
去掉 `changeOnSelect ` 试试
