### ISSUE TITLE
how can i disable the whole form without fieldset

### ISSUE THREAD

**Issue by zhumengyue** [ant-design/ant-design#19732]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when developing a middle platform system, there can be a very complexity form, which has many form items, different types and different data structure. And the edit pages and details pages always appear in pairs. When i reach the details page, i want to see the whole form info i edited. Maybe just disable the whole form is an efficient way.

### What does the proposed API look like?
a props on `Form`, like `<Form disabled></Form>`, or expand the ability of the api `setFields`, like `setFields({ name: { value: xxx, errors: [], disabled: true } })`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/743
https://github.com/ant-design/ant-design/issues/5562
