### ISSUE TITLE
关于antd解藕moment的可能方案

### ISSUE THREAD

**Issue by otakustay** [ant-design/ant-design#19738]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

在仓库的issue中有很多和moment有关的讨论，但这个issue旨在提供一种可行的方案，而不是单纯地说问题。

### What problem does this feature solve?

当前的antd在处理日期上，相关的prop均使用`moment`对象，一直以为这产生了2个问题：

1. antd与moment成为硬耦合，而moment的体积并不小，对用户会造成一定的影响
2. 一个应用系统无论是不是使用moment作为日期处理的库，在对接antd的组件时，必须去使用moment

而moment一直被诟病的体积和对象可变问题，在antd与之强绑定的情况下几乎无法绕过。

antd 4.0是一个比较好的机会，在引入一定量的breaking change的同时尝试解决这一问题。但antd开发组显然并不希望moment作为接口的事实在4.0中仓促改变，以加重用户升级的成本

### What does the proposed API look like?

但其实我们完全可以采用另一种方案，在antd 4.0依然提供接口不变的组件的情况下，增加用户的选择度，允许用户低成本地摆脱掉moment的依赖：

首先，antd实现一个基础的`GenericDatePicker`组件，这个组件使用原生`Date`对象作为接口，内部尽量使用`date-fns`或`dayjs`等体积足够小巧的库，并将这个组件也一同对外导出。

随后，依然实现名为`DatePicker`的组件，但这个组件仅仅对`Date`对象做一次封装处理，转为`moment`对象，类似于：

```js
import moment from 'moment';
import GenericDatePicker from './GenericDatePicker';

const DatePicker = ({value, onChange, ...props}) => {
    // 如果担心组件更新次数问题，此处尝试使用`useMemo`或其它方式做缓存即可
    const momentValue = moment(value);
    const dateOnChange = momentValue => onChange(momentValue.toDate());
    return <GenericDatePicker value={momentValue} onChange={dateOnChange} {...props} />;
};

export default DatePicker;
```

在这样的形式下，旧用户可以无损地进行升级，`DatePicker`任然使用`moement`对象为接口，没有任何的breaking change。

而对于想要摆脱moment的用户来说，它可以直接使用`GenericDatePicker`，并且由于webpack的tree shaking能力，这样子使用会让webpack判断出来在使用antd的过程中没有依赖moment，整个moment都不会进入到最后的bundle中，有助于体积的减小。

我相信这种形式并不会给antd开发团队带来太多的负担，同时对各种需求的用户也很有利，除开moment成为可选这一事实以外，如用户大量使用dayjs也同样可以参考上面的代码简单地封装出`DayJsDatePicker`来，提供了很好的灵活性

**Comment by dogbutcat** [comment]
如果使用不同的库那么选择日期的返回结果实例还得统一 或可以考虑设计一个类似DateInterface接口，如果用户需要更改默认的则自己选择用什么日期工具去实现这个接口，这样选择出来的结果也对使用者可控一点

**Comment by otakustay** [comment]
> 可以考虑设计一个类似DateInterface接口

我觉得原生的`Date`就是最好的接口，所有的日期库都会最终适配原生对象

**Comment by dogbutcat** [comment]
原生Date简单用用还好 复杂场景就不好用了 要不然也就不会出那么多日期库了

**Comment by otakustay** [comment]
用户有选择日期库的权利，但是组件作为整个逻辑的终点（给进去就不用管了），它就应该是`Date`这种最基础的类型，因为无论用户选什么日期库，都一定能兼容到原生对象，这样组件就不会用自己的实现绑架用户

**Comment by zombieJ** [comment]
We consider provides generator function to support customize date library:

```jsx
// Draft
const MomentDatePicker = generatePicker({
  parse: (str, props) => moment(str),
  format: (date, props) => date.format(),
});
```

Moment is default provided to compatible with v3 user, but user can chose to use customize one like DayJS or native Date with generate.

**Comment by otakustay** [comment]
@zombieJ I still believe a HOC could be more community compliant and easier to understand:

```js
const parse = (str, props) => moment(str);
const format = (date, props) => date.toDate();
const MomentDatePicker = withDateHandling(parse, format)(AntDesignDatePicker);
```

**Comment by iamkun** [comment]
之前在这个文章 https://github.com/iamkun/dayjs/issues/529 里调研过使用 Day.js 直接替换 Moment.js 的可行性。
考虑做一个 webpack 插件 (antd-dayjs-webpack-plugin)，当使用了这个插件，将会使用 webpack 的 alias 功能直接替换。

插件主要做了两件事：
1. 在 Entry 中增加了 dayjs.js 主要是集中初始化一些 插件、多语言文件
2. 在 Alias 中 使用 dayjs 替换 moment

对于用户来说，只需要在 webpack 配置文件中使用这个插件，就可以无感知地使用 Day.js 替换 Moment.js

需要考虑的问题：
Antd 目前的源码在使用 moment 时有直接修改操作对象的用法，这种 mutable 的写法并不是那么优雅，也是 Day.js 所不建议的，需要我们修改小部分 antd 的源码来统一使用 immutable 的用法。

**Comment by afc163** [comment]
@iamkun 的方案最后也会作为官方推荐的替换方案之一放在文档里。

**Comment by otakustay** [comment]
我认为最关键的问题是，antd不应该在组件的prop上选择任何一个框架，既不应该是moment，也不应该是dayjs、luxon等其它任何的库

提供一种方式将moment转为dayjs，只能解决打包体积的问题，但无法解决用户的技术选型与antd存在不兼容的问题

**Comment by iamkun** [comment]
@otakustay  moment luxon dayjs 等时间日期库存在的意义并不只是方便开发少写几行代码，而是封装了对很多不同浏览器浏览器，不同国家时间、夏令时区别等等的兼容逻辑。

换句话说，即使 antd 全部使用 native Date 来完成开发，该做的兼容逻辑一样也不能少，反而增加了组件库的开发者的开发负担

**Comment by yoyo837** [comment]
> @otakustay moment luxon dayjs 等时间日期库存在的意义并不只是方便开发少写几行代码，而是封装了对很多不同浏览器浏览器，不同国家时间、夏令时区别等等的兼容逻辑。
> 
> 换句话说，即使 antd 全部使用 native Date 来完成开发，该做的兼容逻辑一样也不能少，反而增加了组件库的开发者的开发负担

这话说到重点了。

**Comment by otakustay** [comment]
@iamkun 我并不是说antd需要用原生Date完成开发，antd完全可以在其内部选择任意的日期库做开发，即便用moment也没关系顶多被诟病体积有点大

但是antd不应该在接口上吐出或接收非原生Date的对象，无论内部使用什么样的实现，都应该封装在内部

**Comment by yoyo837** [comment]
@otakustay 那你 https://github.com/ant-design/ant-design/issues/19738#issuecomment-554242327 的想法就很难实现，或者极其复杂。

**Comment by otakustay** [comment]
我觉得我们说的单纯点，antd内部dayjs随便用，但对外是Date对象，我觉得这样就满足了希望解决的问题了

**Comment by yoyo837** [comment]
我个人想支持对外是时间戳毫秒值这种。

**Comment by otakustay** [comment]
我也支持用number，还省去了引用相等的处理之类的麻烦事，总之是原生类型就好😂

**Comment by shaodahong** [comment]
and an idea we may extract the time function used internally, into `context config`, if you need another time handler, can replace it

example

```js
isBefore(date) {
 return moment(date).isBefore
}
```

```js
isBefore(date) {
 return dayjs(date).isBefore
}
```

 @iamkun  https://github.com/iamkun/dayjs/issues/529 is same，also replace，only officially exposed to increase fault tolerance

**Comment by zombieJ** [comment]
Some special function like first day of week by locale may not get from native Date. Currently will extract these ability out and Picker will only read from proxy so user can just use same value if not care of this.

ref: https://github.com/react-component/picker/blob/c08b4d81fb0e8fd0c5dc030c87445b255c6ce0a5/src/generate.tsx

**Comment by zzlit** [comment]
支持，只希望不要规定使用哪一种库而能让我们来进行自由选择

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/20515

Thx to @xiaohuoni  !

**Comment by xiaoxiangmoe** [comment]
@afc163 https://github.com/tc39/proposal-temporal 已经 stage 3 了。我们可以考虑切换到 temporal API

**Comment by yoyo837** [comment]
> @afc163 https://github.com/tc39/proposal-temporal 已经 stage 3 了。我们可以考虑切换到 temporal API

有polyfill了吗？

**Comment by xiaoxiangmoe** [comment]
@yoyo837 有，https://github.com/tc39/proposal-temporal/tree/main/polyfill

**Comment by yoyo837** [comment]
> @yoyo837 有，https://github.com/tc39/proposal-temporal/tree/main/polyfill

我看它没有明确写兼容浏览器，是node.js

**Comment by jianghai** [comment]
为什么不考虑 prop 接受时间戳，与任意日期库解耦

**Comment by mytharcher** [comment]
> > 可以考虑设计一个类似DateInterface接口
> 
> 我觉得原生的`Date`就是最好的接口，所有的日期库都会最终适配原生对象

同意 @otakustay 的建议，当用到 `DatePicker` 的时候，传 value 居然要包一层其他库的处理结果，这体验实在太糟糕了。

不管 moment 还是 dayjs，antd 可以在内部选用来转换，但应该支持最基本的原生 Date 类型，甚至 ISOString 的类型都要比用一个库来包装好。

**Comment by xiaoxiangmoe** [comment]
> 我看它没有明确写兼容浏览器，是node.js

@yoyo837 在浏览器跑需要webpack或者vite之类的打包一下才能跑🤔️你是遇到什么问题跑不起来了吗？
