### ISSUE TITLE
Support multiple sizes for Rate component

### ISSUE THREAD

**Issue by Arman92** [ant-design/ant-design#19735]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently the Rate component is single sized and hence it wont look good in different design requirements.

Could you guys add different size support? something like: ```<Rate size="lg" /> <Rate size="md" />```, etc

### What does the proposed API look like?
```<Rate size="lg" />, <Rate size="md" />, <Rate size="sm" />```

**Comment by afc163** [comment]
You can try `fontSize`: https://codesandbox.io/s/ecstatic-dubinsky-yznhh

**Comment by irvv17** [comment]
> You can try `fontSize`: https://codesandbox.io/s/ecstatic-dubinsky-yznhh

works like a charm

**Comment by alramalho** [comment]
Not working on my end

> You can try `fontSize`: https://codesandbox.io/s/ecstatic-dubinsky-yznhh

link not working (sandbox broken)
