### ISSUE TITLE
checkbox size changed 

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#19736]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when changed the checkbox size ,the ✅cannot be centered in the checkbox

### What does the proposed API look like?
how✅ to center in checkbox

**Comment by xrkffgg** [comment]
The `checkbox` API on the official website does not support changing `size`
I think you must have changed the size of this CSS
```
.ant-checkbox-inner {
    width: 16px;
    height: 16px;
}
```

Then you can adjust this to fit the changed size

```
.ant-checkbox-checked .ant-checkbox-inner::after {
    transform: rotate(45deg) scale(1) translate(-50%, -50%);
    -webkit-transform: rotate(45deg) scale(1) translate(-50%, -50%);
    -ms-transform: rotate(45deg) scale(1) translate(-50%, -50%);
}
```

**Comment by zhesunAtHengshi** [comment]
someone had an answer which helped me https://github.com/ant-design/ant-design/pull/7374#issuecomment-876157174

**Comment by Rysted** [comment]
None of them worked for me, but this did help:
```javascript
<Form.Item className={styles.loginCheck}>
    <Checkbox>Remember me</Checkbox>
</Form.Item>

.loginCheck span {
    transform: scale(1.2);
}
```
