### ISSUE TITLE
[4.0] New DatePicker design

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#19747]
![1536906714495-06aa9d17-b459-4280-8e8b-c2d4e5e560b9](https://user-images.githubusercontent.com/5378891/68920552-8843ba80-07b0-11ea-99ed-8a5ef20d6110.png)

ref https://github.com/ant-design/ant-design/issues/16911 https://github.com/ant-design/ant-design/issues/4524#issuecomment-480576884

**Comment by afc163** [comment]
wow~

**Comment by shaodahong** [comment]
Ref: #19289

**Comment by shaodahong** [comment]
looking forward to new DatePicker, and thanks for antd designer
