### ISSUE TITLE
const declarations are not supported in strict mode. safari

### ISSUE THREAD

**Issue by zuizuihao** [ant-design/ant-design#1974]
官网无法再safari下面是用。
http://ant.design
报错SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
(anonymous function) — index.js:44264

**Comment by Catlite91** [comment]
＋1
safiri 9.1.1 (11601.6.17)

**Comment by benjycui** [comment]
fixed, thanks!
