### ISSUE TITLE
在嵌套table的同时能够不影响默认使用chidlren渲染出来的树状结构

### ISSUE THREAD

**Issue by 314278548** [ant-design/ant-design#19746]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在嵌套table的同时能够不影响默认使用chidlren渲染出来的树状结构

**Comment by afc163** [comment]
If you are tring to report a bug, please use bug-report template in http://new-issue.ant.design/ to create another issue.
