### ISSUE TITLE
select tags模式下，输入下拉列表中的内容会过滤出两条数据

### ISSUE THREAD

**Issue by fly-sheep** [ant-design/ant-design#19748]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-kdwp6)

### Steps to reproduce
两个组件依次输入下拉列表中的选项a10,会出现不同的效果

### What is expected?
组件2中输入a10时，只出现下拉列表中已存在的a10选项（同组件1的效果）

### What is actually happening?
组件2输入a10时，下拉列表中会出现两条相同的数据；一条是用户输入的，一条是下拉列表匹配到的选项

| Environment | Info |
|---|---|
| antd | 3.23.3 |
| React | 16.9.0 |
| System | ios |
| Browser | chrome |

---
实际应用场景中，下拉列表的选项都是{id: ***, name: ***}的形式，我们需要的是选中项的id而非name

**Comment by xiangchunyu** [comment]
遇到同样的问题，想请问一下这个问题解决了么，或者可以用什么方法来避免呢？

**Comment by afc163** [comment]
```js
for (let i = 10; i < 36; i++) {
  children1.push(
    <Option key={i.toString(36) + i}>{i.toString(36) + i}</Option>
  );
  children2.push(<Option key={i}>{i.toString(36) + i}</Option>);
}
```

```js
    <Select mode="tags" style={{ width: "100%" }} tokenSeparators={[","]}>
      {children1}
    </Select>
```

```js
    <Select
      mode="tags"
      style={{ width: "100%" }}
      tokenSeparators={[","]}
      filterOption={(input, option) =>
        option.props.children.toLowerCase().includes(input.toLowerCase())
      }
    >
      {children2}
    </Select>

原因是源码里的 key 取值不一样，第一个 Select 没有指定 filterOption，默认是去 `value` 和 `key` 中搜索，`a10` 不会匹配到 `key="10"` 这一项，只会留下 tags 模式下默认生成的输入项。

第二个 Select 定义了 `filterOption`，`a10` 能匹配到，同时还有 tags 模式下默认生成的输入项，于是就有两个。
