### ISSUE TITLE
Drawer footer demo not fixed to bottom correctly

### ISSUE THREAD

**Issue by RaoHai** [ant-design/ant-design#19743]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-lake-q04gx)

### Steps to reproduce
Scroll drawer's content, the footer can not fixed to bottom correctly, which works well in last version.
![image](https://user-images.githubusercontent.com/566097/68913821-9afdc580-0797-11ea-8b6b-eb541e1b7a7c.png)

### What is expected?
The problem commit is: 4ded5e6#r35964872

### What is actually happening?
Will antd provide an official drawer footer?

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | latest |
| System | Macintosh; Intel Mac OS X 10_15_2 |
| Browser | Chrome/78.0.3904.97 |

**Comment by yoyo837** [comment]
ref: #19506

**Comment by RaoHai** [comment]
另外真心建议官方出一个 footer。现在内部各种 Drawer 的 footer 用得飞起，设计还不统一。有的按钮摆左边有的摆右边……

**Comment by shaodahong** [comment]
@RaoHai https://github.com/ant-design/ant-design/pull/19720#discussion_r346115650 先看下这个解决方案吧，官网的确实有 bug，会更新下的

**Comment by shaodahong** [comment]
Ref: https://github.com/ant-design/ant-design/pull/19720

**Comment by RaoHai** [comment]
> @RaoHai [#19720 (comment)](https://github.com/ant-design/ant-design/pull/19720#discussion_r346115650) 先看下这个解决方案吧，官网的确实有 bug，会更新下的

是不是我自己能不能解决的问题。而是由于 antd 没有提供官方的 footer，所以用户用之前官网的写法来实现 footer 的肯定不会少。。。

**Comment by RaoHai** [comment]
更新官网的意思是用户之前业务代码里按旧 DEMO 写的不管了是么。。

**Comment by shaodahong** [comment]
现在已经有 PR 了，可以帮忙 review

**Comment by jljsj33** [comment]
https://stackblitz.com/edit/react-jjmuro?embed=1&file=index.js

**Comment by jljsj33** [comment]
3.0 用这个，，吖的，，@shaodahong  先把这个更新到 demo 上去。。。

**Comment by afc163** [comment]
#15204
