### ISSUE TITLE
4.0 `rc-trigger` blink with focus element

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#19745]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/pull/19678#issuecomment-554190132](https://github.com/ant-design/ant-design/pull/19678#issuecomment-554190132)

### Steps to reproduce
Click to open
Blur to close

### What is expected?
No blink

### What is actually happening?
Blink

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.8 |
| React | latest |
| System | IOS |
| Browser | chrome |

**Comment by shaodahong** [comment]
yep, In new Table I Found blink, but in the demo i can't reproduce, maybe i can view new table code

https://codesandbox.io/s/antd-reproduction-template-804cc

System Info:

Firefox version: 70.0 (64 位)
OS: macOS 10.15.1

**Comment by shaodahong** [comment]
![Kapture 2019-11-15 at 12 48 30](https://user-images.githubusercontent.com/14831261/68917670-4ca3f300-07a6-11ea-8dae-77feedd118b7.gif)

**Comment by zombieJ** [comment]
Will release alpha version today. And then patch validate reproduce.

**Comment by shaodahong** [comment]
reproduce demo

https://codesandbox.io/s/antd-reproduction-template-q3zht

**Comment by shaodahong** [comment]
this bug not relate to `antd` Input, now I use a normal input tag reproduce, it's also has

Trigger `popupTransitionName` compose inner children transform in Firefox, it too weird, but I don't think this its Firefox bug

in the code review, i found two ways close when Trigger popup open (action click)

1. click the source element
https://github.com/react-component/trigger/blob/0da83e0b822f71e8d564dbd4167ade706ccf733a/src/index.tsx#L317

2. click outside source(document listened to click event)
https://github.com/react-component/trigger/blob/0da83e0b822f71e8d564dbd4167ade706ccf733a/src/index.tsx#L367

the 1 it's good, but 2 it's may trigger some default event(like focus), cause the popup to leave animation with children transform weird

and there is a bad solution

```js
onDocumentClick = () => {
  setTimeout(() => {
    ...
  })
}
```

@zombieJ @afc163 i found `rc-trigger` refactor animation code in the new version, but i don't know why? now it controlled by `status(stable, align, afterAlign, etc...)`, performance?

**Comment by zombieJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-u1uqf
Dig into motion may be the correct way, I check the event that `focus` not re-fire with this.

**Comment by afc163** [comment]
https://codesandbox.io/s/ji-chu-yong-fa-fei-qi-de-yu-fa-tang-antd-4-24-1-forked-89t28x?file=/demo.tsx

看上去最新版本已经没有这个闪烁问题了。
