### ISSUE TITLE
为表单的InputGroup，添加rules.validator（请求接口，异步验证）时，样式抖动/错误

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design#19741]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-silence-8ktks)

### Steps to reproduce
在输入框输入内容，左侧的select的小箭头图标位置会发生变化

### What is expected?
左侧的select的小箭头图标位置不变化

### What is actually happening?
在输入框输入内容，左侧的select的小箭头图标位置会发生变化

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.11.0 |
| System | windows 10 |
| Browser | chrome |

![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-bug.gif)

**Comment by maxmeng93** [comment]
@afc163

**Comment by maxmeng93** [comment]
FormItem没有设置hasFeedback，但是当它包裹了一个 InputGroup，InputGroup里有Select时，Select 的箭头图标位置错误

请看以下GIF演示
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-bug1.ls3ktii2jqk.gif)

Select 的箭头图标位置错误，向左偏移，空了一个validateStatus图标的位置

**Comment by afc163** [comment]
尝试给我们来个 PR 修复吧。

**Comment by maxmeng93** [comment]
components/form/formItem.tsx 第244行  renderValidateWrapper 方法。

即使我没有设置 `hasFeedback`，这个方法也会根据验证状态来设置 `has-feedback`这个className。
只要 `this.getValidateStatus()` 的结果是 `validating`，就会添加 `has-feedback`这个className。

不知道 `'has-feedback': props.hasFeedback || validateStatus === 'validating',`，后面的 ` || validateStatus === 'validating'` 是否有必要呢？

``` jsx
  renderValidateWrapper(
    prefixCls: string,
    c1: React.ReactNode,
    c2: React.ReactNode,
    c3: React.ReactNode,
  ) {
    const { props } = this;
    const onlyControl = this.getOnlyControl;
    const validateStatus =
      props.validateStatus === undefined && onlyControl
        ? this.getValidateStatus()
        : props.validateStatus;

    let classes = `${prefixCls}-item-control`;
    console.log('\n')
    console.log('************')
    console.log('props.hasFeedback = ', props.hasFeedback)
    console.log('this.getValidateStatus() = ', this.getValidateStatus());
    console.log('validateStatus = ', validateStatus)
    if (validateStatus) {
      classes = classNames(`${prefixCls}-item-control`, {
        'has-feedback': props.hasFeedback || validateStatus === 'validating',
        'has-success': validateStatus === 'success',
        'has-warning': validateStatus === 'warning',
        'has-error': validateStatus === 'error',
        'is-validating': validateStatus === 'validating',
      });
    }
    console.log('classes = ', classes);

    let iconType = '';
    switch (validateStatus) {
      case 'success':
        iconType = 'check-circle';
        break;
      case 'warning':
        iconType = 'exclamation-circle';
        break;
      case 'error':
        iconType = 'close-circle';
        break;
      case 'validating':
        iconType = 'loading';
        break;
      default:
        iconType = '';
        break;
    }

    const icon =
      props.hasFeedback && iconType ? (
        <span className={`${prefixCls}-item-children-icon`}>
          <Icon type={iconType} theme={iconType === 'loading' ? 'outlined' : 'filled'} />
        </span>
      ) : null;

    return (
      <div className={classes}>
        <span className={`${prefixCls}-item-children`}>
          {c1}
          {icon}
        </span>
        {c2}
        {c3}
      </div>
    );
  }
```
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-bug.hb8qrxmehyw.gif)

**Comment by maxmeng93** [comment]
这个问题，即使是单个 Select 组件时也存在，不需要包裹在 InputGroup 里。
