### ISSUE TITLE
抽屉滚动后footer不能固定在底部

### ISSUE THREAD

**Issue by liujiayii** [ant-design/ant-design#19758]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer-cn/](https://ant.design/components/drawer-cn/)

### Steps to reproduce
比较长的抽屉向下滚动

### What is expected?
footer应该固定在底部

### What is actually happening?
footer跟随滚动条一起滚上去了

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.12.0 |
| System | windows |
| Browser | Chrome78 |

**Comment by afc163** [comment]
Fixed in #19751
