### ISSUE TITLE
Popover does not work with Tree

### ISSUE THREAD

**Issue by panlina** [ant-design/ant-design#19754]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-tree-popover-issue-d28we)

### Steps to reproduce
Hover on the only tree node and try to play with the checkbox in the popover.

### What is expected?
The checkbox works.

### What is actually happening?
The checkbox can be checked once but not be unchecked again.

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16 |
| System | MacOS |
| Browser | chrome 78 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18120#issuecomment-526928189
