### ISSUE TITLE
Carousel add arrows but not show

### ISSUE THREAD

**Issue by blissCheng** [ant-design/ant-design#19759]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/goofy-ives-yp5g9)

### Steps to reproduce
Carousel add a arrows prop

### What is expected?
The toggle arrow displays

### What is actually happening?
not show

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.9.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4423#issuecomment-269749265
https://github.com/ant-design/ant-design/issues/5458#issuecomment-288713585
https://github.com/ant-design/ant-design/issues/12479

**Comment by vahe-nikoghosyan** [comment]
```
.slick-arrow.slick-prev {
  background-color: red;
  color: red;
}
.slick-arrow.slick-next {
  background-color: red;
  color: red;
}

```
