### ISSUE TITLE
Datepicker prevent mobile keyboard onClick

### ISSUE THREAD

**Issue by 3dw1np** [ant-design/ant-design#19755]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
On iOS or Android, when a user is touching the antd datepicker it will automatically wrap up the virtual keyboard of the mobile phone.

### What does the proposed API look like?
How can we can access to onClick method to do a e.preventDefault() ?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15688#issuecomment-477065182

**Comment by peterwiebe** [comment]
use the `inputReadOnly` prop 👍
