### ISSUE TITLE
表格额外的展开行expandedRowRender如何设置才能默认为展开状态而不是收起的

### ISSUE THREAD

**Issue by aNameHere** [ant-design/ant-design#1975]
如何才能让其默认为展开状态, 如果希望满足某条件的行才显示前面的展开按钮该如何设置
![image](https://cloud.githubusercontent.com/assets/8602772/15811637/85accc24-2bdd-11e6-9f8e-47e39be44e15.png)

**Comment by benjycui** [comment]
![image](https://cloud.githubusercontent.com/assets/3580607/15813189/76c4aa9e-2bef-11e6-9afe-44ef16f04ae2.png)

http://ant.design/components/table#Table

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
