### ISSUE TITLE
4.0 alpha.9 Table的summary为何返回一个reactNode而不是一组数据？

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#19769]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的方式会出现类似下面的问题

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-engelbart-qexyy?fontsize=14&hidenavigation=1&theme=dark)

汇总行无法与固定列兼容，且使用起来非常复杂

### What does the proposed API look like?
以我的业务情景为例，一般都是后端分页，汇总数据也是后端计算，前端分页后的数据合并计算并不是需要的数据
期望 summary支持返回一组或多组数据，使用Table的columns，以render实现合并
```
const {summary} = this.props;
<Table
  summary={summary}
>
</Table>
```
感觉实际上我们的业务场景需要的合计只是在Table分页的情况下，pageSzie=10的情况下，组件不会截断我传入11行数据

**Comment by yoyo837** [comment]
因为summary 各式各样的设计

**Comment by Liu-Ya** [comment]
> 因为summary 各式各样的设计

那不是相当于实现了一个支持滚动条的footer吗？

**Comment by Liu-Ya** [comment]
summary 的结构类似这样
```
{
  col1: {
    children: value | reactNode,
    props: { colSpan: 2}
  },
}
```

**Comment by zombieJ** [comment]
收集信息里看用户 summary 的结构比较自由，所以当前版先提供了一个直出 ReactNode 的版本允许用户自定义。 固定列混用想法是先看看当前 `summary` 使用如何后再加支持。

Summary content is free constructor, so in the first version we only provides ReactNode for customization. Fixed column mix usage will add after current `summary` feedback collection.

**Comment by Liu-Ya** [comment]
@zombieJ 可能是我这里业务逻辑比较简单，一般订单或者其他列表需要渲染些复杂东西的时候是用不到`summary`的，用到的都是报表这样用于展示数据的业务，像这些地方不会让用户操作表格内容，`summary`顶多合并下单元格
我认为如果考虑到给用户自由渲染，可以拓展下`footer`(感觉footer的使用率实在是很低，像`pro`也没有相关的业务场景)，给一个跟随表格滚动条的属性，我想效果和现在的`summary`应该很类似
而`summary`允许用户传入一个对象，避免最简单的应用也要手搓每个`<td>`
```jsx
<Table
  summary={(data)=>{
    // do something...
    const summary = {
      col1: 1200,
      col2: {
        children: <a></a>,
        props: { colSpan: 2}
      }
    }
    return {...summary}
  }}
>
</Table>
```
以目前的方式，要实现下图中的合计实在是要写很多繁琐的代码，且当`columns`发生变化的时候调整也比较复杂（甲方经常有要求改变`columns`顺序的情况）
![image](https://user-images.githubusercontent.com/23520283/69029889-246bfc80-0a11-11ea-8957-7c56acb0e1cb.png)

**Comment by yoyo837** [comment]
感觉好像并没有哪种方式是能够是默认的方式，通用性都不够（与复杂或者简单无关）。

**Comment by zombieJ** [comment]
`footer` 和 `title` 一样是非固定部分，考虑到兼容性问题才会额外提供一个 `summary` 作为额外的 Table 注入属性。关于 summary config object 见上，会观望后考虑是否、以何种形式添加。

`footer` is like `title` to  add no fixed part. Since change origin `footer` is breaking change, we add `summary` instead. For the config object to see above, will consider to update with more feed back.

link with main issue #16911

**Comment by Liu-Ya** [comment]
@yoyo837 @zombieJ 无论是 config object 还是 reactNode都是相互可实现的，只是我认为既然`summary`是表格内容的一部分而不像`header`或`footer`在表格之外，应该与columns保持高度一致

**Comment by yoyo837** [comment]
我个人不太赞同这个说法，summary 应该不一定与columns 有所谓的高度一致。完全看需要，甚至可以是个单纯的提示语。可能与数据整体滚动，也可以在header fixed的时候自己也固定在下方，仅滚动数据。

**Comment by yoyo837** [comment]
或者是`summary` 这个名字诱导了思维； “数据汇总”只是其一表现，最终需要的到底是`summary`还是`footer`。

**Comment by Liu-Ya** [comment]
@yoyo837 我认为`summary`的业务场景很明确啊，就是用来放汇总数据的，其他场景不应该使用`dataSource`或这`footer`吗

**Comment by alexchen1875** [comment]
也许这个玩意儿我们应该把他和header 放在同一层级.使得 "汇总"与body本身分离.以便解决出现滚动或长列时这个玩意儿就被顶到最后,变成了body的一部分.
我支持这种做法[show aggregation statistics data](https://github.com/ant-design/ant-design/issues/5710#issuecomment-531619036)

maybe we can put the SUMMARY together with the HEADER in same level.
y ?  i think when we need to know the summary data,we can ignore how many rows in the table .we just see the summary with each columns. 
i support this[show aggregation statistics data](https://github.com/ant-design/ant-design/issues/5710#issuecomment-531619036)

**Comment by PeiTianHuang** [comment]
> > 或者是`summary` 这个名字诱导了思维； “数据汇总”只是其一表现，最终需要的到底是`summary`还是`footer`。
> 
> 应该是要一个拥有summary功能的的footer 😃
> 
> 也许这个玩意儿我们应该把他和header 放在同一层级.使得 "汇总"与body本身分离.以便解决出现滚动或长列时这个玩意儿就被顶到最后,"变"成了body的一部分.
> 我支持这种做法[show aggregation statistics data](https://github.com/ant-design/ant-design/issues/5710#issuecomment-531619036)
> 
> maybe we can put the SUMMARY together with the HEADER in same level.
> y ? i think when we need to know the summary data,we can ignore how many rows in the table .we just see the summary with each columns.
> i support this[show aggregation statistics data](https://github.com/ant-design/ant-design/issues/5710#issuecomment-531619036)

同求，且目前summary无法与固定列并存

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/23647
