### ISSUE TITLE
带搜索的select中，能否自定义选中option返回的属性

### ISSUE THREAD

**Issue by yesuanzao** [ant-design/ant-design#1976]
版本：ant-1.0
问题：
    我在使用”带自动补全的输入框“，比如我筛选出了一些商品，当我选中的时候希望能获取到商品的价格、id、名称，我在哪个hook中能拿到呢？我看了optionFilterProp，应该不能满足这个需求

**Comment by benjycui** [comment]
只要获得 `id` 就可以了，自己再做个 map。

```js
var map = {
  [id]: {
    price: ..
    name: ..
  },
  ...
}
```
