### ISSUE TITLE
Structured Filters in Autocomplete

### ISSUE THREAD

**Issue by shobhitsinghal624** [ant-design/ant-design#19765]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need ability to define a `key <operator> value` type query in input box. See a sample demo here: http://summitroute.github.io/react-structured-filter/demo.html

Sample screenshots below:
<img width="1169" alt="Screenshot 2019-11-16 at 5 41 28 PM" src="https://user-images.githubusercontent.com/4579093/68993148-b56c9780-089a-11ea-8d45-89824c72f882.png">
<img width="1172" alt="Screenshot 2019-11-16 at 5 41 39 PM" src="https://user-images.githubusercontent.com/4579093/68993150-ba314b80-089a-11ea-8845-c6fbf2519367.png">
<img width="1171" alt="Screenshot 2019-11-16 at 5 41 49 PM" src="https://user-images.githubusercontent.com/4579093/68993151-bc93a580-089a-11ea-8cca-cc8d4944f1dd.png">
<img width="1162" alt="Screenshot 2019-11-16 at 5 42 00 PM" src="https://user-images.githubusercontent.com/4579093/68993152-bf8e9600-089a-11ea-8065-e8a049ff22cf.png">

### What does the proposed API look like?
I think it would be similar to a multi tag Autocomplete component with conditional UI.

**Comment by afc163** [comment]
Try https://ant.design/components/mentions/
