### ISSUE TITLE
Trying to use react-beautiful-dnd but can't use ref or innerRef on List component

### ISSUE THREAD

**Issue by idanlo** [ant-design/ant-design#19764]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-currying-lymsm)

### Steps to reproduce
1. Add `react-beautiful-dnd`
2. Wrap your content with `<DragDropContext>`
3. Render an `antd` `<List>` as a child of `<Droppable>`
4. innerRef/ref??? - not working for `Droppable`
5. Render children as `<Draggable><List.Item /></Draggable>`
6. innerRef/ref??? - not working for `Draggable`

(There are also errors in the console from `react-beautiful-dnd` saying that the ref was not provided

### What is expected?
`ref` prop should be the `ref` of the HTML element.

### What is actually happening?
`ref` is ignored by `antd`

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.11.0 |
| System | Windows 10 |
| Browser | Chrome Version 78.0.3904.97 (Official Build) (64-bit) |

**Comment by nirvdrum** [comment]
My solution in the meanwhile is to wrap `List` and `List.Item` in `div`. This, however, affects styling as Ant uses `:last-child` in selectors like `.ant-list-item:last-child`. Since each list item is wrapped in a `div`, each is a last child.

**Comment by salimhamed** [comment]
This is still an issue for me. Here's my current workaround, using `ReactDOM.findDOMNode`. This issue with this implementation is `ReactDOM.findDOMNode` will be [depreciated in future versions of React](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage).

```javascript
<Draggable draggableId="myId" index={1}>
    {(provided, snapshot) => (
        <List.Item
            ref={(node) =>
                provided.innerRef(ReactDOM.findDOMNode(node) as HTMLElement)
            }
            {...provided.draggableProps}
            {...provided.dragHandleProps}
        >
            {children}
        </List.Item>
    )}
</Draggable>
```

**Comment by hengkx** [comment]
I've been using `react-dnd` recently.I look at this.

**Comment by talkl** [comment]
https://medium.com/versatileai/react-beautiful-dnd-with-antd-list-19ed6d77ae42

**Comment by afc163** [comment]
- [ ] Card
- [ ] Collapse

https://github.com/ant-design/ant-design/issues/28582

**Comment by buhichan** [comment]
Collapse and Collapse.Panel are class components in rc-collapse, so need to wait until they are refactored to FunctionalComponent to support ref forwarding. Unless name their ref props to 'innerRef', which i think is a bad idea because of the inconsistency naming.
How about just implement ref forwarding for List, List.Item and Card for now?

> * [ ]  Card
> * [ ]  Collapse
> 
> #28582

**Comment by piyushk96** [comment]
Issue for me too can't `react-dnd` with List

**Comment by Tirlipinpin** [comment]
Hello there! I'm currently facing this same issue with the Collapse.Panel component. I'm working on a file dropping system and would need to have a ref on the Panel component - which would allow me to track whether the user is dragging a file over it.
Is it still planned to forward the ref at this point?

**Comment by mistycal98** [comment]
Also facing difficulty with draggable tab feature just like in chrome

**Comment by sangeetha-armtek** [comment]
I need exactly this feature in our application, collapse panel with drag and drop.
Is there a work around or a different solution to this? Does anybody have an idea?

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/35321

**Comment by roddc** [comment]
@afc163 Do you plan to refactor Collapse to forward the ref? I need to use the ref with another library

**Comment by umagon** [comment]
@afc163 Hello! Any plans for adding ref to Collapse and Panel? I wanted to implement a drag and drop feature for my collapsible panels.
