### ISSUE TITLE
MonthPicker 插件无法中文化BUG

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design#19762]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
<MonthPicker format="YYYY-MM" onChange={this.changeMonth} placeholder="年月不限" /> 已在全局配置中文

### What is expected?
显示中文

### What is actually happening?
英文

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | react |
| System | mac |
| Browser | 谷歌78.0.3904.97 |

---
顺便说一下蚂蚁金服应该是中国企业，你们是中国人。

**Comment by yfPanne** [comment]
遇到同样问题, 直接从官网把用例使用 CodeSandbox 打开并配置一下中文设置即可复现此问题.
![image](https://user-images.githubusercontent.com/28749080/69393260-a448de00-0d13-11ea-9764-1388073adc17.png)

**Comment by yoyo837** [comment]
请把demo 链接发到这里。

**Comment by yfPanne** [comment]
https://codesandbox.io/s/great-dewdney-encro

**Comment by afc163** [comment]
https://codesandbox.io/s/tender-fast-zm65j

<img width="955" alt="image" src="https://user-images.githubusercontent.com/507615/69401653-9786b300-0d30-11ea-8fbe-022da7fbdf5c.png">
