### ISSUE TITLE
swipeToSlide for carousel

### ISSUE THREAD

**Issue by adrianescat** [ant-design/ant-design#19767]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Regarding React Slick documentation (https://react-slick.neostack.com/docs/example/swipe-to-slide) you can put swipeToSlide prop. I can't accomplish this with ant design carousel.

### What does the proposed API look like?
I think we just need to make available this prop in the Carousel interface.

**Comment by yoyo837** [comment]
<img width="1049" alt="截屏2019-11-1711 17 53" src="https://user-images.githubusercontent.com/6134547/69002523-ec3ebe00-092b-11ea-982c-198318541742.png">
