### ISSUE TITLE
[BUG] Bad bug fix from #19689 on 3.25.2

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#19776]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
# 3.25.2
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/beautiful-shape-301y1)
# 3.25.1
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-chaum-98xtx)

### Steps to reproduce
# 3.25.2
https://codesandbox.io/s/beautiful-shape-301y1

![2](https://user-images.githubusercontent.com/29817353/69021227-178be080-09f2-11ea-9ab8-20769795bcfc.gif)

# 3.25.1
https://codesandbox.io/s/dazzling-chaum-98xtx

![1](https://user-images.githubusercontent.com/29817353/69021238-1eb2ee80-09f2-11ea-83c3-8b2a91847258.gif)

### What is expected?
upload or remove uploaded file, style works correctly.

### What is actually happening?
upload or remove uploaded file, style works badly.

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | latest |
| System | mac os 10.14.4 |
| Browser | chrome 78 |

**Comment by chiaweilee** [comment]
https://github.com/ant-design/ant-design/pull/19689

**Comment by qq645381995** [comment]
嗯

**Comment by qq645381995** [comment]
#19783
