### ISSUE TITLE
Typescript error: when use ref in a From.create wrapped component 

### ISSUE THREAD

**Issue by kwzm** [ant-design/ant-design#19773]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dawn-http-1tzwc?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Create a component use Form.create wrapped.
2. Create a ref by useRef in parent Comp. `const childRef = useRef<typeof ChildComp>()`
3. Add ref in child comp.
4. Use `childRef.crrent.validate()`.
5. If you use vscode then you will see errors hint in validate and componet ref.

There are some screenshots:
![QQ截图20191117185214](https://user-images.githubusercontent.com/16114101/69006895-fa62fd80-0970-11ea-9cf2-fd8fdf4ecd2f.png)
![QQ截图20191117185228](https://user-images.githubusercontent.com/16114101/69006896-fafb9400-0970-11ea-9049-230025134aa9.png)
![QQ截图20191117185250](https://user-images.githubusercontent.com/16114101/69006897-fafb9400-0970-11ea-95a9-4c894c303422.png)

### What is expected?
No ts error.

### What is actually happening?
Property 'validateFields' does not exist on type 'ConnectedComponentClass<FunctionComponent<Props>, Pick<Props, "data" | "onChange" | "wrappedComponentRef">>'.ts(2339)

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
You have to do it in this way now: https://codesandbox.io/s/xenodochial-sound-cw4n2

**Comment by LingVuDev** [comment]
For this please use the hook `useForm` which provides an instance as you would do with createRef

```js
import { useForm } from 'antd/lib/form/Form';
export function SomeForm() {
  const [form] = useForm();
  return (
    <Form
      form={form}
    >...</Form>
  )
}
```
