### ISSUE TITLE
怎么切换到jsx的源代码，找不到入口或是需要其他什么操作。

### ISSUE THREAD

**Issue by amelonsamy** [ant-design/ant-design#19777]
需求描述：切换了几个分支和tag发现都是tsx的源码，目前还未使用ts，仅仅想看看下jsx源码的实现，但是无法直接找到入口，只能通过搜索的模式。

**Comment by yoyo837** [comment]
如果了解Typescript的话，会发现只是在js的基础上加了类型系统罢了，同一个文件tsx => jsx => js 三者编译中的任何一个环节阅读起来应该是没差别的；

你本地clone后运行、编译一下，jsx文件就出来了。

![image](https://user-images.githubusercontent.com/6134547/69054314-3f0c9880-0a46-11ea-9acb-1b159b44a62d.png)
