### ISSUE TITLE
Form表单中没有隐藏域类型的表单项

### ISSUE THREAD

**Issue by Siwellewis** [ant-design/ant-design#19784]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些参数需要提交时获取表单数据的对象后加进去，单个表单还可以手动加一下，但是多个表单加起来就很麻烦

### What does the proposed API look like?
Form.Item中加一个属性hide，代表隐藏域，提交的时候能获取到隐藏域的数据

**Comment by yoyo837** [comment]
antd 的表单更多是与排版和校验绑定的逻辑，也就是UI强关联的，传统的form之所以存在`hidden`项，是因为大都使用整个表单提交并返回结果页html的方式，只要非页面提交的东西，`hidden`的作用就不明显，比如ajax，完全可以在表单提交前自行补充数据，提交到后台。

**Comment by yoyo837** [comment]
多个表单你可以考虑抽取一个通用函数来复用，这完全是你业务层面的需要。

**Comment by yoyo837** [comment]
之前也有人提过，应该不会考虑支持吧？需要实现的时候再打开。

**Comment by archcra** [comment]
> antd 的表单更多是与排版和校验绑定的逻辑，也就是UI强关联的，传统的form之所以存在`hidden`项，是因为大都使用整个表单提交并返回结果页html的方式，只要非页面提交的东西，`hidden`的作用就不明显，比如ajax，完全可以在表单验证并得到UI数据后自行补充或者修改数据，再提交到后台。

这个是正解。
