### ISSUE TITLE
AutoComplete: function components cannot be given refs

### ISSUE THREAD

**Issue by ops1ops** [ant-design/ant-design#19782]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-lop91)

### Steps to reproduce
Use function components as children in `AutoComplete`

### What is expected?
Warning should not appear

### What is actually happening?
When you pass function components as children in `AutoComplete` appears warning:
`Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.8.6 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 76.0.3809.100 |

**Comment by zombieJ** [comment]
AutoComponent need to get DOM instance of customize input component. You should use `forwardRef` to pass the DOM node.
