### ISSUE TITLE
InputNumber，设置 setFieldsValue 时出现错误

### ISSUE THREAD

**Issue by wwlweihai** [ant-design/ant-design#1979]
代码如下

```
componentDidMount(){
                this.props.form.setFieldsValue({'jpje':12});
    }
```

`
<InputNumber
                            min={1}
                            max={9999}
                            {...getFieldProps('jpje')}
                        />
`

出现如下错误

> `Warning: InputNumber is changing a uncontrolled input of type undefined to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component.`

**Comment by benjycui** [comment]
`{...getFieldProps('jpje', { initialValue: 0 })}`
