### ISSUE TITLE
增加对 rollup 支持和示例

### ISSUE THREAD

**Issue by qianL93** [ant-design/ant-design#19799]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd基于的rc组件对rollup支持并不好，诸如 https://github.com/react-component/select/issues/362 https://github.com/react-component/menu/issues/246
希望能够更好的支持rollup进行打包

### What does the proposed API look like?
无

**Comment by afc163** [comment]
https://github.com/MrStevenHill/rollup-antd-library-typescript
https://stackoverflow.com/questions/53338345/how-to-build-a-component-library-using-typescript-ant-design-and-rollup

**Comment by qianL93** [comment]
> https://github.com/MrStevenHill/rollup-antd-library-typescript
> https://stackoverflow.com/questions/53338345/how-to-build-a-component-library-using-typescript-ant-design-and-rollup

看起来这例子只是extern掉antd依赖的场景？那并没有什么问题，但是如果要输出一个完整的无其他依赖的包（根据使用场景），就涉及到我前面提到的issue，我没有找到特别好的方法，我还是重新用webpack了。

**Comment by afc163** [comment]
rc 组件里开发打包用的 https://github.com/umijs/father/ 也是用的 rollup，具体的问题可以到对应的 rc 组件里面直接去提 PR，这里先关了。
