### ISSUE TITLE
Cascader 搜索交互方式

### ISSUE THREAD

**Issue by ppxu** [ant-design/ant-design#19793]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Cascader 组件现在做搜索时会把整个路径拿来做匹配，有没有方法只过滤第一层选项，还是保留级联选择的交互方式

### What does the proposed API look like?
none

**Comment by afc163** [comment]
https://ant.design/components/cascader-cn/#components-cascader-demo-search

Try: `showSearch={{ filter }}`
