### ISSUE TITLE
4.0 `@ant-design/compatible` follow up

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#19800]
ref https://github.com/ant-design/compatible

- [x] Icon development
  - [ ] Release confirm
- [x] Form development
  - [ ] Release confirm
- [ ] Document ready

#### Updated

- [ ] Mention development
  - [ ] Release confirm

**Comment by zombieJ** [comment]
Basic development has finished. But still need additional check for this package and document update. Need volunteer help to follow up.

cc @yoyo837 @shaodahong @orzyyyy @ztplz

**Comment by zombieJ** [comment]
@shaodahong , Please help to add `Mention` component into compatible package.

**Comment by shaodahong** [comment]
> Please help to add `Mention` component into compatible package.

OK, I will try at night, and `LocaleProvider` also need into?

**Comment by zombieJ** [comment]
codemod by @vagusX will help to handle convert `LocaleProvider` into `ConfigProvider`. It's safe to leave it.

**Comment by zombieJ** [comment]
@shaodahong , safe to close?

**Comment by shaodahong** [comment]
>  safe to close?

@zombieJ yup
