### ISSUE TITLE
期望checkbox组件可以同时获得label和value

### ISSUE THREAD

**Issue by yctjb1** [ant-design/ant-design#19803]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户可以选择他处显示已经勾选的checkbox的label值

### What does the proposed API look like?
达到Select组件的labelInValue属性这样的效果

**Comment by afc163** [comment]
建议自行拿到 value 去取 label。
