### ISSUE TITLE
form 表单项二次渲染后就获取不了上层传递的数据了

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design#19808]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-antd-styled-template-sj3xr)

### Steps to reproduce
点击`否`后再切换回`是`

### What is expected?
状态切换不影响数据的展示

### What is actually happening?
不符合预期

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome 70 |

**Comment by yezongyang** [comment]
添加initialValue 是可以解决的，但是有没有办法不这样处理

**Comment by afc163** [comment]
https://codesandbox.io/s/react-antd-styled-template-snhtq

**Comment by yezongyang** [comment]
@afc163  这个我知道哈， 但是onSubmit 的时候会是全量数据， 如果用display实现关联关系展示可能还得增加删除字段参数的逻辑

**Comment by afc163** [comment]
https://codesandbox.io/s/react-antd-styled-template-69r62
