### ISSUE TITLE
4.0 Clean up all version info in document

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#19815]
v3 provides the version info in each component. For v4 version, this will be all available in 4.0.0. Should clean up with these in documents.

### How to operate

Checkout  [`4.0 prepare`](https://github.com/ant-design/ant-design/tree/4.0-prepare) branch and create new PR to update related document. PR should ref #19815

<img width="888" alt="截屏2019-11-20上午11 21 32" src="https://user-images.githubusercontent.com/5378891/69206547-f0ffae00-0b87-11ea-80b4-1ec43e9b7d45.png">
Remove `3.3.0`

---------

v3 提供了版本信息。v4 版本将会都是默认 4.0.0 可用。需要清除过时的版本信息。

### 操作流程
在 [4.0 prepare](https://github.com/ant-design/ant-design/tree/4.0-prepare) 的基础上开启一个新分支，将所有的 version 信息列删除完毕后，发起一个 PR， 将其合并到 4.0-prepare)
提 pr 的时候引用一个这个 issue . 中英文都要检查一下  ` ref: #19815` 

<img width="888" alt="截屏2019-11-20上午11 21 32" src="https://user-images.githubusercontent.com/5378891/69206547-f0ffae00-0b87-11ea-80b4-1ec43e9b7d45.png">
移除 `3.3.0`

## General
- [x] Button @zhangyanling77 11.25 finish
- [x] Icon @zhangyanling77  11.25 finish
- [x] Typography @likeDoMine 11.25 finish

## Layout

- [x] Grid @likeDoMine 11.25 finish
- [x] Layout @ShawDanon 11.25 finish

## Navigation

- [x] Affix @ShawDanon 11.25 finish
- [x] Breadcrumb @BensonChen 11.25 finish
- [x] Dropdown @BensonChen 11.25 finish
- [x] Menu @likeDoMine 11.25 finish
- [x] Pagination @likeDoMine 11.25 finish
- [x] PageHeader @likeDoMine 11.25 finish
- [x] Steps @likeDoMine 11.25 finish

## Data Entry
- [x] AutoComplete @577281375 11.25 finish
- [x] Checkbox @577281375 11.25 finish
- [x] Cascader @yehq 11.25 finish
- [x] DatePicker @yehq 11.25 finish
- [x] Form @xiaohuoni
- [x] InputNumber  @qhanw 11.25 finish
- [x] Input @qhanw 11.25 finish
- [x] Mentions @qhanw 11.25 finish
- [x] Rate @qhanw 11.25 finish
- [x] Radio @qhanw 11.25 finish
- [x] Switch @qhanw 11.25 finish
- [x] Slider  @wangxingkang  11.25 finish
- [x] Select  @wangxingkang  11.25 finish
- [x] TreeSelect @wangxingkang  11.25 finish
- [x] Transfer @wangxingkang  11.25 finish
- [x] TimePicker @wangxingkang  11.25 finish
- [x] Upload @wangxingkang  11.25 finish

## Data Display

- [x] Avatar @seognil 11.25 finish
- [x] Badge   @seognil 11.25 finish
- [x] Comment @seognil 11.25 finish
- [x] Collapse @seognil 11.25 finish
- [x] Carousel @seognil 11.25 finish
- [x] Card @seognil 11.25 finish
- [x] Calendar  @seognil 11.25 finish
- [x] Description List  @seognil 11.25 finish
- [x] Empty  @seognil 11.25 finish
- [x] List  @seognil 11.25 finish
- [x] Popover  @seognil 11.25 finish
- [x] Statistic @seognil 11.25 finish
- [x] Tree @zhangxiuling 11.25 finish
- [x] Tooltip @zhangxiuling 11.25 finish
- [x] Timeline @chouchouovo 11.25 finish
- [x] Tag @jhsu 
- [x] Tabs @chouchouovo 11.25 finish
- [x] Table @xiaohuoni 

## Feedback 

- [x] Alert @xiaohuoni 
- [x] Drawer @xiaohuoni 
- [x] Modal @xiaohuoni 
- [x] Message @xiaohuoni 
- [x] Notification @xiaohuoni 
- [x] Progress @xiaohuoni 
- [x] Popconfirm @xiaohuoni 
- [x] Result @xiaohuoni 
- [x] Spin @xiaohuoni 
- [x] Skeleton @xiaohuoni 

## Other

- [x] Anchor @ColinCLL 11.25 finish
- [x] BackTop @ColinCLL 11.25 finish
- [x] ConfigProvider @ColinCLL 11.25 finish
- [x] Divider @ColinCLL 11.25 finish

**Comment by ShawDanon** [comment]
@zombieJ

**Comment by zombieJ** [comment]
@ShawDanon, which do you want to pick?

**Comment by yoyo837** [comment]
Do wu need to delete the version number content or delete the table column?

**Comment by zombieJ** [comment]
> Do we need to delete the version number content or delete the table column?

Delete number is enough since this will add back by future feature.

**Comment by zombieJ** [comment]
Thanks all your effort. Task finished! 🚀

**Comment by xiaohuoni** [comment]
🚀🚀🚀🚀🚀🚀🚀
