### ISSUE TITLE
message组件在传参错误以后再次调用不能使用

### ISSUE THREAD

**Issue by awefeng** [ant-design/ant-design#19817]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-brown-cvzfi)

### Steps to reproduce
首先传给message一个错误参数 ， 报错。然后不刷新界面的情况下传入正确的参数给message。

### What is expected?
期望结果是message被调用 界面显示信息

### What is actually happening?
实际结果是message组件被破坏 界面未显示信息

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome lastest |

**Comment by afc163** [comment]
感觉组件库不应该做太多兼容，这样直接挂掉反而有助于帮助应用发现问题。

**Comment by awefeng** [comment]
> 感觉组件库不应该做太多兼容？这样直接挂掉反而有助于帮助应用发现问题。

这不是兼容问题，传参错误导致以后都不能用，这应该是属于缺陷问题。

最好是ant design在控制台中打印出错误栈，但再次使用传入正确参数的时候，组件还能用。

你说的兼容应该是指这种情况：传入错误参数，不生效也不打印错误。

**Comment by kavience** [comment]
看了源代码会发现因为用的 message 实例是同一个，即第一个出现问题，导致后面的也出现问题，因为实例还是原来的

**Comment by afc163** [comment]
现在的表现是会直接报错干掉应用，应该是符合预期的，错误的调用导致应用白屏。

<img width="699" alt="image" src="https://user-images.githubusercontent.com/507615/76953386-96197000-6949-11ea-80a7-2a44561fe742.png">
