### ISSUE TITLE
封装自定义校验方法时，validator里获取不到form属性

### ISSUE THREAD

**Issue by ArcherWong** [ant-design/ant-design#19814]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在编写校验逻辑时,可能会用到表单内其他字段的值，如：密码二次确认。这时，如果把自定义校验方法封装到单独的文件里，validator方法获取不到form属性。

### What does the proposed API look like?
```js
export const comfirmPassword = (rule, value, callback, form) => {
    if (value && value !== form.getFieldValue('newPassword')) {
        callback(formatMessage({ id: 'form.validator.confirmPassword' }));
    } else {
        callback();
    }
}
```

**Comment by yoyo837** [comment]
args: (rule, value, fn, source, options)

**Comment by yoyo837** [comment]
你自己在实现里引用自己表单的当前form实例，validator 方法的回调参数是上面这些。
form是`antd`的form, 验证是 [async-validator](https://github.com/yiminghe/async-validator), 和 [element-ui](https://github.com/ElemeFE/element) 是同一个验证库，它不可能反向依赖。
