### ISSUE TITLE
Antd 4.0, Form.Item使用getValueFromEvent,normalize,valuePropName时, 控制台报错

### ISSUE THREAD

**Issue by VoliBearCat** [ant-design/ant-design#19824]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-gqxjb)

### Steps to reproduce
刷新页面, 观察控制台日志

### What is actually happening?
![image](https://user-images.githubusercontent.com/11676384/69215007-75135f00-0ba3-11ea-83df-4742c66b45ad.png)

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.9 |
| React | 16.12.0 |
| System | macOS 10.14.2 |
| Browser | Chrom 78 |

**Comment by changzhn** [comment]
I had the same problem

我遇到了同样的问题
