### ISSUE TITLE
Make Compoenent `Select` support change input value with onSearch.

### ISSUE THREAD

**Issue by ahuigo** [ant-design/ant-design#19822]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Support custom format function for input value.

### What does the proposed API look like?
```
<Select onSearch={value=>{
       return formatUpperCase(value);
}} >

</Select>
```

**Comment by afc163** [comment]
You should use custom `filterOption`.
