### ISSUE TITLE
Spin里的例子，wording有误

### ISSUE THREAD

**Issue by insekkei** [ant-design/ant-design#1982]
http://ant.design/#/components/spin

“切换加载状态”这里举的例子，&lt;Spin **spinning**={this.state.loading}&gt;，应该是&lt;Spin **spining**={this.state.loading}&gt;

**Comment by afc163** [comment]
不对，是 `spinning`。

https://github.com/ant-design/ant-design/pull/1420

注意看 changelog。http://ant.design/changelog#1.0.0
