### ISSUE TITLE
select maxTagPlaceholder={omittedValues = > null} 超过maxTagCount时，期望不显示tag

### ISSUE THREAD

**Issue by ffalconjs** [ant-design/ant-design#19828]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://暂无](http://暂无)

### Steps to reproduce
<Select maxTagCount={3} maxTagPlaceholder={omittedValues = > null}>...</Select>
选择超过3个tag时，会显示一个空tag，期望不显示

### What is expected?
选择超过3个tag时，会显示一个空tag，期望不显示

### What is actually happening?
必现

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.8.6 |
| System | macOS 10.14.6 |
| Browser | 78.0.3904.87 |

---
特殊场景下会有这种需求，返回null或者undefined都无法得到不显示tag的效果

**Comment by tychenjiajun** [comment]
@afc163 Please reopen this. Version 4.x has the same issue. 


```jsx
const {  useState  } = React;
const {  TreeSelect  } = antd;

const { TreeNode } = TreeSelect;

const Demo = () => {
  const [value, setValue] = useState(undefined);
  const onChange = () => {
    setValue(value);
  };
  return (
    <TreeSelect
      showSearch
      style={{ width: '100%' }}
      value={value}
      dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
      placeholder="Please select"
      allowClear
      maxTagCount={1}
      maxTagPlaceholder={null}
      treeDefaultExpandAll
      treeCheckable
      onChange={onChange}
    >
      <TreeNode value="parent 1" title="parent 1">
        <TreeNode value="parent 1-0" title="parent 1-0">
          <TreeNode value="leaf1" title="leaf1" />
          <TreeNode value="leaf2" title="leaf2" />
        </TreeNode>
        <TreeNode value="parent 1-1" title="parent 1-1">
          <TreeNode value="leaf3" title={<b style={{ color: '#08c' }}>leaf3</b>} />
        </TreeNode>
      </TreeNode>
    </TreeSelect>
  );
};

ReactDOM.render(<Demo />, mountNode);
```

https://codepen.io/chankcccc/pen/RwxogpZ?editors=001

By the way, http://new-issue.ant.design is totally unusable, I can't delete the whole title if type in something wrong.
