### ISSUE TITLE
Perhaps 'side' is better than 'sider' in the layout component

### ISSUE THREAD

**Issue by Sunzhuoyi** [ant-design/ant-design#19839]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout-cn/#Layout.Sider](https://ant.design/components/layout-cn/#Layout.Sider)

### Steps to reproduce
https://ant.design/components/layout-cn/#Layout.Sider

### What is expected?
Sider means advocate, supporter at the same time side means 'right, left , doge' and so on.

### What is actually happening?
Perhaps 'side' is better than 'sider' in the layout component.

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | v16.12 |
| System | macOS |
| Browser | Google Chrome 78.0.3904.97（正式版本） （64 位） |

**Comment by zombieJ** [comment]
Thanks for feedback. Name of `Sider` is intentionally since it's close to like `Header`, `Footer`. And currently may not consider rename this.

Thanks
