### ISSUE TITLE
timePicker trigger to show is too long time

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#19831]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/form-cn/#components-form-demo-validate-static](https://next.ant.design/components/form-cn/#components-form-demo-validate-static)

### Steps to reproduce
trigger timePicker input

### What is actually happening?

![Kapture 2019-11-20 at 16 52 35](https://user-images.githubusercontent.com/14831261/69223364-3044f380-0bb6-11ea-8a1f-5a4d042d3287.gif)

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.9 |
| React | 16.3 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by afc163** [comment]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/507615/69224483-9aaa6380-0bb7-11ea-8b51-ce3f9b1d2360.png">

All feedback icons are missing too.

**Comment by zombieJ** [comment]
close for: https://github.com/react-component/trigger/commit/5331f76d1ea616e19a54091547c2c7d733f5b4d9
