### ISSUE TITLE
Button 没有多种颜色可选

### ISSUE THREAD

**Issue by xutou12** [ant-design/ant-design#1984]
建议预设一些按钮颜色，或者添加颜色的参数，用来区分操作级别。

**Comment by benjycui** [comment]
已有的 4 种按钮就可以区分操作级别 http://ant.design/components/button#components-button-demo-basic

antd 是 Ant Design 规范下的一个组件库，不会做超出规范的事的。

**Comment by stelioschar** [comment]
@benjycui is there any way from the framework to add more coloured buttons. A good option could be by adding a `type="#myColor"`. Are there any thoughts on this?

**Comment by zhengzhou1992** [comment]
> @benjycui is there any way from the framework to add more coloured buttons. A good option could be by adding a `type="#myColor"`. Are there any thoughts on this?

you can custom button color like this:
<Button style={{backgroundColor: "#2db7f5"}} type="primary"> </Button>

**Comment by wmdzkey** [comment]
可以看下  **《扩展Ant Design Pro 按钮 组件配色方案》** **https://blog.csdn.net/wwmmddz/article/details/85702807**

**Comment by passioncsu** [comment]
好像是本身内置了几个颜色,但是没有放出来?

添加
class="ant-btn-success"  绿色
class="ant-btn-error"  红色
class="ant-btn-warning"  橙色
