### ISSUE TITLE
[4.0] Table validation in IE 11

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#19850]
Since IE 11 do not support sticky. Should validate downgraded style works correctly.

- [ ] Validate Table in IE 11
  - [ ] Provides additional style if not well performed by default

https://next.ant.design/components/table/#components-table-demo-dynamic-settings

**Comment by xiaohuoni** [comment]
在ie11上
![image](https://user-images.githubusercontent.com/11746742/69340428-74adbd80-0ca2-11ea-8619-db877aaa7282.png)
会报错，还没进到table页面
![image](https://user-images.githubusercontent.com/11746742/69340408-6a8bbf00-0ca2-11ea-9284-3d14c94d2f7f.png)
使用umi 跑了最后一个demo，expand 和 fixed 同时使用，看起来表现是ok的
![image](https://user-images.githubusercontent.com/11746742/69345881-d2470780-0cac-11ea-8de9-12dec2a551ce.png)

**Comment by xiaohuoni** [comment]
有一个疑问，
Table Layout: 选择 Uset 和 Fixed 都没看出有什么差别，在谷歌浏览器上一样的表现

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/69346481-cdcf1e80-0cad-11ea-9d24-061e3054802b.png)

**Comment by xiaohuoni** [comment]
## 固定列
![image](https://user-images.githubusercontent.com/11746742/69349897-8e0b3580-0cb3-11ea-9344-66a347a60bfd.png)

**Comment by xiaohuoni** [comment]
# 固定列+展开 Error
![image](https://user-images.githubusercontent.com/11746742/69350449-8a2be300-0cb4-11ea-9f09-1718dddd5550.png)

**Comment by xiaohuoni** [comment]
其他常规用法都简单的测试了一波。暂时没发现多的问题

**Comment by zombieJ** [comment]
Chrome please provides Codesandbox directly.

**Comment by xiaohuoni** [comment]
明天吧

**Comment by xiaohuoni** [comment]
使用ie访问 https://next.ant.design/components/table-cn/#components-table-demo-dynamic-settings
直接无响应，还会闪退。无法定位问题。

**Comment by xiaohuoni** [comment]
手写了一个简单的,在ie11下失效了
```html
<div style={{ height: '200px', overflowY: 'scroll' }}>
    <div style={{ position: 'sticky', top: '0' }}>top</div>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
    <p>123213</p>
</div>
```

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/69551409-9a570180-0fd7-11ea-9fc6-90ef52491db9.png)

![image](https://user-images.githubusercontent.com/11746742/69553513-43532b80-0fdb-11ea-96ae-d03fbe9e46ba.png)

https://github.com/xiaohuoni/antd-4-table-ie

**Comment by xiaohuoni** [comment]
@zombieJ
