### ISSUE TITLE
增加状态栏组件

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#19857]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户体验需求，类似vs code下的状态栏，如下：
![image](https://user-images.githubusercontent.com/18542211/69307555-ed425900-0c65-11ea-9cf8-e3446b6daca4.png)

### What does the proposed API look like?
和antd保持一样的。

**Comment by yoyo837** [comment]
请反馈到https://github.com/ant-design/ant-design-pro 或者https://github.com/ant-design/ant-design-pro-layout

**Comment by kaoding** [comment]
https://github.com/ant-design/ant-design-pro-layout/issues/203
