### ISSUE TITLE
[4.0] Add Space component for styled spacing

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#19860]
# This is a record, should not start before design

Since antd require `8 * n` padding/margin between components. Should provides a quick Spaced component for layout usage.

#### Auto insert 8px spacing between buttons

```jsx
<Space>
  <Button>Operation 1</Button>
  <Button>Operation 2</Button>
  <Button>Operation 3</Button>
</Space>
```

#### Auto insert 18px spacing between buttons

```jsx
<Space size={16}>
  <Button>Operation 1</Button>
  <Button>Operation 2</Button>
  <Button>Operation 3</Button>
</Space>
```

#### Auto insert 8px spacing between Table vertically

```jsx
<Space size={24} direction="vertical">
  <Table />
  <Table />
</Space>
```

#### use `size: 'small' | 'middle' | 'large'` as presets gutters

```jsx
<Space size="small">
  <Button>Operation 1</Button>
  <Button>Operation 2</Button>
  <Button>Operation 3</Button>
</Space>
```

| size | gutter |
| --- | --- |
| small | 8px |
| middle | 16px |
| large | 24px |

**Comment by afc163** [comment]
干脆搞一个 Space 新组件吧，和栅格的概念区分开。

**Comment by rdmclin2** [comment]
恩，相当于css盒子的组件化配置？

**Comment by afc163** [comment]
不做页面布局，只做组件/区块间距管理。

**Comment by zombieJ** [comment]
Should support ConfigProvider to customize global spacing size.

**Comment by nejcm** [comment]
I suggest that the size behaves similar to Row gutter. Meaning you can provide a single number or an array for 2 or all 4 directions.
Would it also make sense to have a type on it for margin or padding?
