### ISSUE TITLE
table组件在设置expandedRowKeys后 展开按钮无效

### ISSUE THREAD

**Issue by shangwanzheng** [ant-design/ant-design#19869]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
      <Table
        bordered={true}
        loading={loading}
        columns={columns}
        dataSource={tableData}
        rowKey="customer_id"
        expandedRowRender={record => <p style={{ margin: 0 }}>111</p>}
        expandedRowKeys = { expandedRowKeys }
        pagination={{
          current: pagination.page,
          total: pagination.total,
          pageSize: pagination.pageSize,
          showTotal,
          onChange: handlePageChange
        }}
      />
如上 expandedRowKeys 初始为空数组  导致展开功能不可用

### What is expected?
正常使用

### What is actually happening?
无法正常使用

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.5.2 |
| System | mac |
| Browser | chrome78 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by shangwanzheng** [comment]
???? 这个应该不是defaultvalue吧

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-Input/Select-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86%E3%80%82

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1818#issuecomment-220925494
