### ISSUE TITLE
slider: focusing the wrong handle when using range

### ISSUE THREAD

**Issue by wendellhu95** [ant-design/ant-design#19879]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider-cn/#components-slider-demo-basic](https://ant.design/components/slider-cn/#components-slider-demo-basic)

### Steps to reproduce
Drag a handle across the other.

### What is expected?
The dragging handle should be focused.

### What is actually happening?
The other handle is focused.

![Snipaste_2019-11-22_11-35-22](https://user-images.githubusercontent.com/12122021/69396190-6f8d5480-0d1c-11ea-91fb-70297836f3a8.png)

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | latest |
| System | Not relevant |
| Browser | Not relevant |

**Comment by wendzhue** [comment]
I guess it's related to how you get the dragging handle here: 

https://github.com/react-component/slider/blob/62b949f39f3edc6da657e1a720392d74193f34fb/src/utils.js#L22-L33

**Comment by wendzhue** [comment]
Sure. Will do!

**Comment by afc163** [comment]
@wendellhu95 Any progress?

**Comment by wendellhu95** [comment]
@afc163 I am occupied by other job recently. I will try to fix it on the weekend. No garantee though. So if you're going to re-assign this issue it would be ok. Sorry for my delay.

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by Kermit-Xuan** [comment]
I have fix it and create PR at rc-slider [#621](https://github.com/react-component/slider/pull/621). And need to add style to slider at slider component of ant-design.
