### ISSUE TITLE
Improved Table children

### ISSUE THREAD

**Issue by tranducit95** [ant-design/ant-design#19886]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
if children = [] still showing the expand button.
![Screenshot from 2019-11-22 14-49-16](https://user-images.githubusercontent.com/26267956/69407554-4b8b3c80-0d37-11ea-861e-75e40797c025.png)

### What does the proposed API look like?
can it be fixed to children = [] hiding the expand button?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941
