### ISSUE TITLE
Table key 为什么不拿dataSource的索引作为key键那？还必须要求后台程序生成索引

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#1988]
Table key 为什么不拿dataSource的索引作为key键那？还必须要求后台程序生成索引，要不还的拿到json数据自己重组加入key

1.1.0

**Comment by hhhyaaon** [comment]
可以设置rowKey属性，自定义主键
![image](https://cloud.githubusercontent.com/assets/17123400/15843889/37b2b8ce-2c98-11e6-89c3-d204c70d75d2.png)

**Comment by afc163** [comment]
@hhhyaaon :+1:
