### ISSUE TITLE
Tree组件设置了默认展开所有节点，但是增加新的子节点并没有默认展开

### ISSUE THREAD

**Issue by yangxueyou** [ant-design/ant-design#19882]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#header](https://ant.design/components/tree-cn/#header)

### Steps to reproduce
初始化默认展开所有节点，但是动态添加的子节点，不是默认展开的

### What is expected?
添加子节点可以默认展开

### What is actually happening?
添加子节点默认是收起的，需要点击点开按钮才能展开（有的时候是默认展开的，不知道什么原因）

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.0.0 |
| System | react |
| Browser | chrom |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12663#issuecomment-430135880
https://github.com/ant-design/ant-design/issues/11724
