### ISSUE TITLE
[4.0] Input clear icon color not correct

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#19896]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/input-cn/#components-input-demo-allowClear](https://next.ant.design/components/input-cn/#components-input-demo-allowClear)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/14831261/69432568-e9e9c300-0d74-11ea-92ab-5a23a9e9cd8d.png)

### What is expected?
light color

### What is actually happening?
to dark

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.9 |
| React | 16.3 |
| System | windows 10 |
| Browser | chrome 75.0.3770.100  |

**Comment by shaodahong** [comment]
is bug or new design? [Cascader](https://next.ant.design/components/cascader-cn/#components-cascader-demo-basic) is too

**Comment by afc163** [comment]
It is a bug.
