### ISSUE TITLE
[4.0] Select option select unusual when search

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#19891]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/select-cn/#components-select-demo-search](https://next.ant.design/components/select-cn/#components-select-demo-search)

### Steps to reproduce
input `j` and enter, 3.0 select option directly hide, but 4.0 hide after display all select option

### 4.0
![4](https://user-images.githubusercontent.com/14831261/69427391-65924280-0d6a-11ea-8b1a-fc32fa8f0d4c.gif)

### 3.0
![3](https://user-images.githubusercontent.com/14831261/69427394-66c36f80-0d6a-11ea-9c74-ffd4e91c14ea.gif)

### What is expected?
select normal when search

### What is actually happening?
select unusual when search

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.9 |
| React | 16.3 |
| System | windows 10 |
| Browser | chrome 75.0.3770.100  |

**Comment by bryanrasmussen** [comment]
I believe this is similar to something I'm encountering - I am on Antd 3.25.3 

I have a select like the following
```
<Select
                            mode="multiple"
                            value={this.props.value}
                            allowClear={true}
                            open={true}
                            
                            defaultActiveFirstOption={false}
                            showArrow={true}
                            style={{ width: "180px", marginLeft: "10px" }}
                           
                            onChange={this.handleChange}
                            notFoundContent={null}
                            
                        >
                        {myCurrentItems}
                        </Select>
```

myCurrentItems is a bunch of options, they work fine if I select the box and move down and click on the options I want. That's fine. As you can see my open property is set to true, I'd expect this means the dropdown should always be visible no matter what but as soon as I type something into the input box the dropdown disappears, even if it is a letter that is in the options.

**Comment by shaodahong** [comment]
@bryanrasmussen can you reproduce a demo with [codesandbox](https://codesandbox.io/dashboard/recent)?

**Comment by bryanrasmussen** [comment]
@shaodahong  I updated my earlier comment.
