### ISSUE TITLE
现在还能在 feature 提 pr 吗

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#19901]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
#19888 

### Steps to reproduce
-

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | - |
| System | - |
| Browser | - |

**Comment by yoyo837** [comment]
当然能！

**Comment by qq645381995** [comment]
为啥没人看呢

**Comment by yoyo837** [comment]
你这个PR 是21个小时前的，几个月前的PR未处理的都有。虽然那些PR可能是因为什么原因block了、又或者是暂时不紧要、又或者对那部分相对熟悉的人因为什么原因没来得及处理其他人一般也不会优先动它，等等的原因... 总的来说，并不时时时刻刻有人守在github的，加上今天又是周末，虽然我自己在加班 😭。 亲，不要着急哈，总是会处理的。感谢你的贡献！

**Comment by qq645381995** [comment]
没事，主要现在快月底了，我怕被拖到下个月才能把这个 feature 带上，还有我比较急性子。

**Comment by yoyo837** [comment]
着急落地到项目吗？只能受antd的发布周期被动，除非紧急的hotfix patch release。

**Comment by qq645381995** [comment]
对公司我持拒绝的态度。然后我下面开始做支持。。。

**Comment by qq645381995** [comment]
还有件事，什么时候 feature merge master

**Comment by yoyo837** [comment]
一般情况下是：当master发版之后并且计划下一个release是 `MINOR` version时。
