### ISSUE TITLE
table树形数据展示时增加children是否为空数组的判断

### ISSUE THREAD

**Issue by sinofaneliu** [ant-design/ant-design#19906]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
children为空数组时仍然会渲染展开的加号

### What does the proposed API look like?
由于后台接口限制，返回的树形数据如果没有子项时children显示的时空数组，而不是null或undefined

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1365

**Comment by afc163** [comment]
建议使用前自行处理一下数据。
