### ISSUE TITLE
table中缺省排序问题

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#1991]
sorter	排序函数，本地排序使用一个函数，需要服务端排序可设为 true，

设置sorter为true， 数据来源于服务器端，取得数据是按某个具体字段排序的，如何程序能设置当前table的排序箭头正确？默认table排序箭头都是灰色。

componentDidMount 时
 this.fetch({
      results: pagination.pageSize,
      page: pagination.current,
      sortField: ‘Name‘,
      sortOrder:'descend'  
    });

但是显示数据后 name列上的排序标志是灰色的，能程序控制吗？

**Comment by afc163** [comment]
可以的，用 `filteredValue` 和 `sortOrder` 进行控制，参考例子：http://ant.design/components/table#components-table-demo-reset-filter
