### ISSUE TITLE
Using ant design as base library to create our own library

### ISSUE THREAD

**Issue by helabenkhalfallah** [ant-design/ant-design#19910]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/helabenkhalfallah/atomify/tree/master](https://github.com/helabenkhalfallah/atomify/tree/master)

### Steps to reproduce
We tried to use ant design as a base library to create our own library.
We just create 'proxy' components without changing antd source nor organisation (for some particular accessibilities needs).
We choosed antd thanks to modular import.

We tried to use all modularity recommendations from antd : 
https://github.com/helabenkhalfallah/atomify/blob/master/.babelrc#L11
https://github.com/helabenkhalfallah/atomify/blob/master/src/lib/at-button/ATButton.jsx#L2
https://github.com/helabenkhalfallah/atomify/blob/master/src/lib/at-button/ATButton.jsx#L4

But when we import our library we loose this modularity and we got a big bundle size :
https://github.com/helabenkhalfallah/react-sortable-grid-pages/blob/master/webpack-config/webpack.config.js
https://github.com/helabenkhalfallah/react-sortable-grid-pages/blob/master/src/pages/HomePage.jsx#L9
https://github.com/helabenkhalfallah/react-sortable-grid-pages/blob/master/package.json#L27

### What is expected?
Because we haven't changed antd and we only do 'proxy' components (for custom accessibilities), we expected that customised library will be modular as antd.

### What is actually happening?
We have a big non modular and no ES modules :( 

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.12.0 |
| System | windows, mac |
| Browser | IE, Chrome, Firefox |

---
Have you some suggestions and recommendations how we can achieve and keep modularity on our based antd library ?
Thanks.

**Comment by helabenkhalfallah** [comment]
Library based on antd bundle :
![LIB-BUNDLE](https://user-images.githubusercontent.com/1331451/69497457-947cf580-0edd-11ea-954e-c683dc1c33da.png)
 
Project using this lib bundle : 
![PROJECT-IMPORTING-BUNDLE](https://user-images.githubusercontent.com/1331451/69497458-947cf580-0edd-11ea-987b-f40c7d6a481f.png)

**Comment by yoyo837** [comment]
ref: #12011

**Comment by helabenkhalfallah** [comment]
Hello @yoyo837 , thank you, I have seen this reference, my issue isn't about bundle size but how to keep ant design modularity if I just do a top layer without changing code and configuration.

> What is expected?
> Because we haven't changed antd and we only do 'proxy' components (for custom accessibilities), we expected that customised library will be modular as antd.

Thanks :)

**Comment by yoyo837** [comment]
Do you need this? 
https://webpack.js.org/guides/tree-shaking
https://ant.design/docs/react/introduce#Use-modularized-antd

**Comment by helabenkhalfallah** [comment]
Hello @yoyo837 I already used react modularity recommendation to import antd and it works well. For our need we must have a layer above antd because we have some accessibility particularities : we use antd as base, instead directly use antd we make an intermediate component. But doing this we loosed modularity. I take a look inside webpack tree shaking.

I have put our library approach link :
https://github.com/helabenkhalfallah/atomify/blob/master/.babelrc#L11

And a project using it:
https://github.com/helabenkhalfallah/react-sortable-grid-pages/blob/master/src/pages/HomePage.jsx#L9

**Comment by otakustay** [comment]
By importing components from `antd/es/xxx` and exporting ES version from your own UI lib, webpack's tree shaking is able to remove unimported components from bundle, this could be a recommended solution for building lib above antd

**Comment by helabenkhalfallah** [comment]
Hello @otakustay ok I will try your recommendation. Thanks :) :)

**Comment by helabenkhalfallah** [comment]
Hello, I succeed to do es module for my library, if you are interested how :
https://github.com/webpack/webpack/issues/10034#issuecomment-560164204

Thanks for all your help :)
