### ISSUE TITLE
Switch shake in Safari browser

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#19915]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/switch-cn/#components-switch-demo-basic](https://ant.design/components/switch-cn/#components-switch-demo-basic)

### Steps to reproduce
1. Continuous click

![Kapture 2019-11-25 at 14 39 44](https://user-images.githubusercontent.com/14831261/69518031-7ec90800-0f91-11ea-8690-31e65cb208f0.gif)

### What is expected?
no shake

### What is actually happening?
shake

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.3 |
| System | Mac OS X |
| Browser | Safari Version 13.0.3 (15608.3.10.1.4) |

**Comment by afc163** [comment]
不太好解决，看上去像是 safari css `transition` 的 bug。
