### ISSUE TITLE
建议对transfer 组件搜索算法进行优化

### ISSUE THREAD

**Issue by CofeeWithRose** [ant-design/ant-design#19918]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当dataSource数据超过500条，搜索响应超过2s（mac peerformace shadown x4).
目前源码搜索是循环遍历完成。

### What does the proposed API look like?
对搜索算法优化。

**Comment by shaodahong** [comment]
这个和搜索算法关系不大，影响的是 react-lazy-load，它并不能解决大型列表数据的渲染和更新性能，建议替换掉使用 `react-window`，我看到 4.0 的也在用 @afc163

**Comment by mushan0x0** [comment]
确实是react-lazy-load的问题，把`lazy`设置为`false`搜索就不卡了，但选择就会卡

**Comment by shaodahong** [comment]
@mushan0x0 恩，还是和列表数据的渲染有关，我本地用 `react-window` 渲染 10000 条（左右各 5000）数据还是很丝滑的

![Kapture 2019-11-26 at 16 14 15](https://user-images.githubusercontent.com/14831261/69611006-de91e280-1067-11ea-8e88-2087a5cccdf4.gif)

**Comment by CofeeWithRose** [comment]
是的，仔细看了下主要性能瓶颈在删除dom操作后的一次渲染,,

**Comment by afc163** [comment]
@zombieJ 看看 4.0 是否需要替换成 https://github.com/react-component/virtual-list/

**Comment by afc163** [comment]
4.0 里 react-lazy-load 和 `lazy` 属性已经一并移除了。
