### ISSUE TITLE
autocomplete flickering when keyboard shows up on android

### ISSUE THREAD

**Issue by psywalker** [ant-design/ant-design#19922]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
When the keyboard isn't there yet, you focus on the search field, and here's how the keyboard pops out (because you've focused on the field) the autocomplets leave and flickering the field. This happens only when the keyboard appears. In other cases, the autocomplet does not flickering.

### What is expected?
autocomplete should not flicker when it appears at the same time as the keyboard

### What is actually happening?
autocomplete flickers when it appears at the same time as the keyboard

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | Create React App |
| System | Chrome 78.0,3904.108 |
| Browser | Chrome on Android |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15688#issuecomment-477065182
