### ISSUE TITLE
export 部分对象的 prop-types, 以便于 JS 写的业务系统做静态检查

### ISSUE THREAD

**Issue by howel52** [ant-design/ant-design#19927]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
业务系统的技术栈如为：react   js，则类型检查一般都基于 prop-types 来做.    目前如 Form.create()  inject 的 props 在 JS 中没办法做类型检查，如开启 [react/forbid-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md),  则在业务系统不定义 form propTypes 的前提下，必须 ignore 这条 rule 才能保持静态检查通过.

example:
```javascript
@Form.create()
class A extends React.Component {
  static propTypes = {
    // eslint-disable-next-line react/forbid-prop-types
    form: PropTypes.object.isRequired
  }
}
```

### What does the proposed API look like?
在 antd 的构建过程中, 将部分 interface 转为 prop-types 后 export, 如: [Form.create](https://github.com/ant-design/ant-design/blob/master/components/form/Form.tsx#L137)

则在业务系统中可直接使用定义后的 prop-types

```javascript
import { formTypesbalabla } form 'antd/balabala'

@Form.create()
class A extends React.Component {
  static propTypes = {
    form: formTypesbalabala.isRequired
  }
}

```

**Comment by afc163** [comment]
有了 TypeScript 后，`prop-types` 基本已经是鸡肋了，社区也不推进这个方向了，建议关掉 `prop-types` 所有规则。

**Comment by howel52** [comment]
👌

**Comment by howel52** [comment]
> 有了 TypeScript 后，`prop-types` 基本已经是鸡肋了，社区也不推进这个方向了，建议关掉 `prop-types` 所有规则。

👌
