### ISSUE TITLE
Switch component

### ISSUE THREAD

**Issue by mslotvinskij** [ant-design/ant-design#19924]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-z8f1h)

### Steps to reproduce
Switch component on loading state, loading icon/spinner click parent clicks start working

### What is expected?
prevent outside clicks on spining icon

### What is actually happening?
I going to other view on loading state clicking spinner icon

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.9 |
| React | React |
| System | Windows |
| Browser | All |

**Comment by afc163** [comment]
Outside click is prevented in my machine now.
