### ISSUE TITLE
lib中Col样式丢失

### ISSUE THREAD

**Issue by jssoscar** [ant-design/ant-design#19929]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://didi.com](http://didi.com)

### Steps to reproduce
暂无

### What is expected?
源码中antd/lib/col/style/index.css
Col的style中缺少了index.css文件

我们封装了一个npm组件，由于外部用户使用babel-plugin-import引用我们组件，我们组件用引用Col，因此在我们的组件中直接引用了Col的样式从而避免外部用户Col样式丢失。

但是今天发现新版本中，Col的index.css文件丢失。目前只发现Col的index.css丢失

### What is actually happening?
源码中提供antd/lib/col/style/index.css文件

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16 |
| System | mac |
| Browser | Chrome |

<img width="427" alt="WechatIMG1246" src="https://user-images.githubusercontent.com/4252175/69545230-57dbf780-0fcc-11ea-9c0e-b66a6fcb329e.png">

**Comment by afc163** [comment]
这不是 bug，Col 和 Row 组件的样式在 Grid 里面。`antd/lib/col/style/index.css` 这个文件 2.x 版本以后就没有提供过。
