### ISSUE TITLE
How do you generate documentation site?

### ISSUE THREAD

**Issue by liesislukas** [ant-design/ant-design#19925]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Looking for automated way to get all components and properties together with property type, default value and documentation in a structural way, e.g. JSON.

sample:
```
{
  "errors": [
    {"type": "DOCUMENTATION_NOT_FOUND", "component": "Alert", "property": "onClick"}
  ],
  "data": 
  [
    {
      "type": "component",
      "name": "Card",
      "properties": {
        "children": {
          "type": "node",
          "documentation": "The content of the component"
        },
        "raised": {
          "type": "bool",
           "default": false,
          "documentation": "If true, the card will use raised styling"
        }
      }
    }
  ]
}
```

I see that the documentation site's tables are in md files and it seems like those are written manually? Do you have any automated process to scan out all properties & components of ant.design and generate md files like this one: extras/ant-design-master/components/alert/index.en-US.md

Do you have an automated script that would show if documentation md file is missing some property? 

https://prnt.sc/q1p6zl

would you consider building such a script?

### What does the proposed API look like?
some helper script which would generate documentation site's tables and/or check if documentation prop tables do have all properties from all components

**Comment by liesislukas** [comment]
@material-ui/core has some automated script to work with documentation:

https://github.com/mui-org/material-ui/blob/master/CONTRIBUTING.md#updating-the-component-api-documentation

**Comment by afc163** [comment]
We may not have energy to provide such script, welcome to find solution and give us PR~

**Comment by liesislukas** [comment]
if I would make an effort to create something like this, you would be interested to adopt it and continue using it? An automated checker before a new release if the documentation does have all the details about all properties.

**Comment by afc163** [comment]
There is a lot work to do, I prefer a hand-writing documentation instead of auto generation, which has better readability. Also we maintians both English and Chinese documentation and it is hard to create a compatible tsdoc format in code for both languages.

**Comment by liesislukas** [comment]
I'm referring to documentation parts that deliver pure technical value, the text describing in human-friendly what is what needs to stay manually to have a human touch.

![image](https://user-images.githubusercontent.com/2733862/69539351-f7799580-0f8c-11ea-83eb-51ea8734eb4d.png)

For translations, there could be a translation file and deploy script could just detect missing translations and/or translations that may be outdated. E.g. prop was updated but translation is the same. 

as a nice side bonus, the automated structure would allow having translations to other languages too with little effort, if there would be budget, it could be even auto connected to human translation api and would be done automatically on updates.
