### ISSUE TITLE
无法安装antd throw unexpected end of file , 减少node_modules文件的大小

### ISSUE THREAD

**Issue by JennerChen** [ant-design/ant-design#19931]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如下问题仅仅发生在CI构建中
ci构建中由于依赖文件过大,导致偶发性报错， 且这个问题越来越严重了。报错如下
```
Error: http://npm.suiyi.com.cn/antd/-/antd-3.24.3.tgz: unexpected end of file
      at Gunzip.zlibOnError (zlib.js:153:15)
```
[yarn-error.log](https://github.com/ant-design/ant-design/files/3889766/yarn-error.log)

我发现大概antd版本升为 3.22.0 以上时，开始出现报错的概率，并且随着版本越高，频率越高, 小于这个版本并不会出错。
我仔细研究了这些版本的区别，发现应该是文件过大导致的。 3.24.3 版本 zip之后已经超过50M了, 3.20.0 版本47M。
我安装的其他包都没有类似的报错过。
我们内部自己搭建了私有npm服务器, 指向cnpm镜像。ci工具是 jenkins

### What does the proposed API look like?
dist目录占用了大量的空间.  移除生成的dist目录下面的内容，改为cdn,或者另外一个包: 例如 antd-dist 的方式
```
import { Input } from "antd"
```
// 如果要全量引入 或者 直接使用cdn
```
import  antd from "antd-dist"
```

**Comment by afc163** [comment]
这不是 antd 的问题，如果从 npmjs.com 和 cnpmjs.org 安装没问题的话，请检查内部私有 npm 服务器的配置、服务器磁盘大小和网络。

**Comment by JennerChen** [comment]
> 这不是 antd 的问题，如果从 npmjs.com 和 cnpmjs.org 安装没问题的话，请检查内部私有 npm 服务器和 ci 服务器的配置、服务器磁盘大小和网络。

我知道这很有可能是ci环境配置问题导致网络被限制了, 但是一个超过50M的以依赖实在是太大了。这还不包过dependencies的大小

**Comment by afc163** [comment]
现在没有好的办法，主要一堆 map 文件得提供。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17655 这个 issue 增加了不少体积。

**Comment by JennerChen** [comment]
@afc163  也许这有可能是npm的一个bug https://github.com/yarnpkg/yarn/issues/7521
