### ISSUE TITLE
Modal在iframe下弹出位置不对

### ISSUE THREAD

**Issue by luolonghao** [ant-design/ant-design#1993]
再现步骤：

1. http://react-component.github.io/dialog/examples/ant-design.html 里的 show dialog 按钮移到页面底部位置。

2. 把上面页面嵌入到高度为1000px的iframe里。

3. 滚动到底部，点击 show dialog 按钮。

**Comment by yiminghe** [comment]
没问题，请给出问题描述和 demo
![2016-06-08 11 11 49](https://cloud.githubusercontent.com/assets/200876/15881609/e6bb1916-2d69-11e6-9bac-dd0119e7b484.png)

**Comment by yiminghe** [comment]
iframe 内的窗口都是相对 iframe 定位的，如果滚动了主体就没办法了
