### ISSUE TITLE
the latest version Table column add property className, when value is "hidden", the Table isn't responsive

### ISSUE THREAD

**Issue by Willworkgogogo** [ant-design/ant-design#19934]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ine12e](https://stackblitz.com/edit/react-ine12e)

### Steps to reproduce
in Table component,  in any column add className property，the value is “hidden” （for hide the column）

### What is expected?
the table is responsive

### What is actually happening?
the table isn't responsive

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | latest |
| System | macOS |
| Browser | Chrome 78.0.3904.108(latest) |

**Comment by Willworkgogogo** [comment]
set Table "tableLayout=auto" can fix this  issue

**Comment by afc163** [comment]
> set Table "tableLayout=auto" can fix this issue

👍 This wordaround is correct, you can see https://github.com/ant-design/ant-design/pull/17284 for more detail of current behavior.

**Comment by afc163** [comment]
Also, it is better to hidden column by remove culumn for data then hide it by className.
