### ISSUE TITLE
DatePicker 组件在设置mode={'year'} disabledDate不生效， 不能禁止年单位的选择

### ISSUE THREAD

**Issue by machinister** [ant-design/ant-design#19932]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在组件mode={'year'} 时 我需要操作disabledDate设置不可选的年的区间，现在实现不了

### What does the proposed API look like?
添加一个disabledyear 方法 或者在disabledDate 里面添加对于年的操作

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16984
https://github.com/ant-design/ant-design/issues/4524

**Comment by machinister** [comment]
不对我是说添加disabledDate不生效 mode={'year'}的情况下 年单位还是可以点击的 做不出来 比如禁止选择今年以后的 年份这样的需求 请认真看我的问题 不要拿之前的答案 来敷衍我 可好

**Comment by afc163** [comment]
Duplicate of #9008

**Comment by machinister** [comment]
看下问题行吗  DatePicker 组件 mode = {'year'} disabledDate不生效 三个条件放一起读行吗 不要断章取义行吗

**Comment by afc163** [comment]
我补充了一下 FAQ：https://github.com/ant-design/ant-design/commit/75ed2e074576cc4152150d5e18ad07a7018570d5，如果有不理解的地方可以在此继续反馈，4.0 的新 Picker 们现在已经有 demo 可以参考了 https://next.ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date

**Comment by Ashuangshuang** [comment]
我也遇到了相同的问题，请问你解决了嘛？

**Comment by WaveStill** [comment]
同问，现在有解决方案了吗？

**Comment by 531431988** [comment]
我是看明白了，上面问的是mode=year的时候 disabledDate 不能禁用指定的年份

**Comment by xiaoheikejj** [comment]
现在3.x版本这个问题还是无解，不打算修复了？

**Comment by xiao-qiangLn** [comment]
看了半天也没找到解决办法

**Comment by Easy-MJ** [comment]
没看懂最终的解决方案是什么呢？

**Comment by CodeGod007** [comment]
怎么解决啊

**Comment by huanlirui** [comment]
我擦。我们老板版本用户直接被放弃了。怎么可能人人升级v4 。我服了

**Comment by elfinc** [comment]
提供一种思路：可以在disabledDate函数里面调用一个debounce函数。这个函数触发的时候，通过querySelectorAll捕获日历中的所有年份按钮，添加禁用样式。顺带再给日历面板加个点击事件，每次点击都触发样式修改，让日历翻页时也能更新样式。
亲测在1.x版本可用
