### ISSUE TITLE
配置颜色@table-header-bg，对size="small"无效

### ISSUE THREAD

**Issue by wengdongyang** [ant-design/ant-design#19936]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/table/style/size.less](https://github.com/ant-design/ant-design/blob/master/components/table/style/size.less)

### Steps to reproduce
104行是否考虑替换一下？

### What is expected?
@table-header-bg对于size="small"有效？

### What is actually happening?
无效

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | ^16.8.6 |
| System | windows |
| Browser | Google Chrome 78.0.3904.97 |

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/19021#issuecomment-535772238
