### ISSUE TITLE
className should accept both string and object

### ISSUE THREAD

**Issue by knobo** [ant-design/ant-design#19930]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This makes Ant Design comply with React and enable the use of libraries like https://github.com/albburtsev/bem-cn.
React applies .toString() method on values passed in to className.

### What does the proposed API look like?
import { block } from 'bem-cn';
const b = block('my-component');

<tag className={ b('my-block') } /> instead of <tag className={ b('my-block').toString() } />

**Comment by afc163** [comment]
It is not antd's problem. Maybe you should report it to bem-cn.

**Comment by knobo** [comment]
the problem is that antd does only accept strings, not objects:
https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L110
antd uses only string, while react uses:
```
  className: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.object
  ]),
```
Of course antd is free not follow ReactJs and use its own standard.

**Comment by afc163** [comment]
React accept `string` in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f460f9a287a015b6d156f511209da74245344639/types/react/index.d.ts#L1658

**Comment by knobo** [comment]
https://github.com/facebook/react/blob/master/fixtures/attribute-behavior/AttributeTableSnapshot.md
```
className=(object) | (changed) | "result of toString()"
```

**Comment by knobo** [comment]
example: https://codepen.io/knobo/pen/ExxBboG?editors=0010

**Comment by afc163** [comment]
OK, PropTypes will be all removed in antd 4.0 cause TypeScript will cover prop typings: https://github.com/ant-design/ant-design/blob/4.0-prepare/components/select/index.tsx

**Comment by knobo** [comment]
Does that mean objects in className will be supported?

**Comment by knobo** [comment]
If antd is going to join strings to user-provided className, then antd needs to do toString on the object.

```
  userClasses = new classes("foo", "bar");
  className={ antdClasses + " " + userClasses }
```
Will work, but you might end up with extra spaces.
