### ISSUE TITLE
select控件的value和placeholder问题

### ISSUE THREAD

**Issue by windyyou** [ant-design/ant-design#1994]
## What you did
如下代码，同时设置了select的value和placeholder

当this.state.ipVersion的值为空或者null得时候

      <Select
        {...ipVersionProps}
        style={{ width: '110px' }}
        value={this.state.ipVersion}
        placeholder="网络版本"
      >

## What you would like to happen

当value的值为空或者null的情况下，select框应该显示placeholder的内容

## What actually happened

显示为空

## Environment Information

- The version of antd(e.g. 1.2.1):
- Your operating system and it's version(e.g. win 7 64bit):
- Your browser and it's version(e.g. Chrome 49.0.2623.112 m):

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1833

**Comment by afc163** [comment]
改成 Select 的 value 和所有 Option 的 value 不匹配时，出现 placeholder ？@yiminghe

**Comment by yiminghe** [comment]
combobox/tag 模式并不适用

**Comment by afc163** [comment]
参照 https://github.com/react-component/select/pull/91 的处理。
