### ISSUE TITLE
Table ellipsis和fixed 同时使用 ellipsis不生效

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design#19946]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-2evo6z?file=index.js](https://stackblitz.com/edit/react-2evo6z?file=index.js)

### Steps to reproduce
ellipsis和fixed 同时使用 ellipsis不生效

### What is expected?
ellipsis和fixed 同时使用 ellipsis 生效

### What is actually happening?
ellipsis和fixed 同时使用 ellipsis不生效

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12.0 |
| System | win 10 |
| Browser | chrome |

**Comment by fwtcumt** [comment]
我也试了很多方法，没发在表格中实现溢出显示...

**Comment by PeiTianHuang** [comment]
我的antd版本是3.26.0，也有同样的问题

**Comment by showonne** [comment]
同遇到这个问题，希望能提下优先级修复，这个场景很常见

**Comment by shenqihui** [comment]
同样遇到。"3.26.14" 版本。

**Comment by xtongtong** [comment]
遇到同样问题，4.2.4的版本，把文档里的示例代码复制粘贴过来都不生效。

**Comment by afc163** [comment]
4.4.3 里生效了：https://stackblitz.com/edit/react-2evo6z-mg8alw?file=index.js

**Comment by HU-gq** [comment]
https://zhuanlan.zhihu.com/p/113579466
这个人的解决方案，一验证可行，我当前antd版本1.5.0

**Comment by kyriejoshua** [comment]
贴一下楼上链接里具体的解决方案。对应的样式文件里添加以下代码，如果不生效可以查看样式优先级。

```less
.ant-table-fixed-left table,
.ant-table-fixed-right table {
  width: min-content;
}
```
