### ISSUE TITLE
Upload外层元素的click会被触发两次

### ISSUE THREAD

**Issue by Jeffy2012** [ant-design/ant-design#19948]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/8983273b](https://riddle.alibaba-inc.com/riddles/8983273b)

### Steps to reproduce
```jsx
ReactDOM.render(
  <div onClick={() => {console.log(1111)}}>
    <Upload {...props}>
      <Button>
        <Icon type="upload" /> Click to Upload
      </Button>
    </Upload>
  </div>,
  mountNode,
);
```

### What is expected?
log一次

### What is actually happening?
log两次

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in `rc-upload@2.9.3`.
