### ISSUE TITLE
Safari 浏览器下，表单校验输入汉字出现灰色错误提示并立即消失

### ISSUE THREAD

**Issue by wfk007** [ant-design/ant-design#19944]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#表单域](https://ant.design/components/form-cn/#表单域)

### Steps to reproduce
1、代码演示第一个例子
2、在 Username 里输入汉字
3、表单校验框出现灰色错误提示并立即消失，输入英文不会出现，chrome 下不会出现

### What is expected?
期待和 Chrome 下保持一致，输入中文的时候不出现立即消失的灰色提醒文字

### What is actually happening?
Safari 下出现了立即消失的灰色提醒文字

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.8 |
| System | macOS Catalina 10.15.1 |
| Browser | Safari |

**Comment by afc163** [comment]
@jljsj33 看上去和动画有关系。

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/14218

**Comment by jljsj33** [comment]
加个延时呗，，输入法的问题没啥办法啊，，，

**Comment by wfk007** [comment]
> 加个延时呗，，输入法的问题没啥办法啊，，，

如果是输入法的问题，Chrome 下为啥就没问题

**Comment by jljsj33** [comment]
有些事件自已去尝试下就了解了。。https://stackblitz.com/edit/react-czskj4

**Comment by jljsj33** [comment]
![image](https://user-images.githubusercontent.com/6802825/69710575-9c85a100-113a-11ea-98e1-8568498b719b.png)

**Comment by franklingu** [comment]
解决方法在这里

https://segmentfault.com/a/1190000008023476

antd 3有这个问题。但是4没有这个问题。也许dev可以解释一下4的优化

**Comment by franklingu** [comment]
> > 加个延时呗，，输入法的问题没啥办法啊，，，
> 
> 如果是输入法的问题，Chrome 下为啥就没问题

Chrome的比较老的version我认为也是不可以的。具体的话这篇文章都解释啦https://segmentfault.com/a/1190000008023476

**Comment by afc163** [comment]
4.x 的 Form 已经没有这个问题，3.x 不再深挖了。
