### ISSUE TITLE
Upload.Dragger - Incorrect style prop propagation

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#19945]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-xkjxew?file=index.js](https://stackblitz.com/edit/react-xkjxew?file=index.js)

### Steps to reproduce
see the repro link

### What is expected?
I pass styles to Dragger expecting the topmost el to recieve the styles. namely, `div.ant-upload.ant-upload-drag`

### What is actually happening?
Instead, `span.ant-upload.ant-upload-btn` recieves the style.

| Environment | Info |
|---|---|
| antd | next |
| React | latest |
| System | any |
| Browser | chrome 77 |

**Comment by yoyo837** [comment]
But `className` is on the `span` tag wrapper.

**Comment by yoyo837** [comment]
`className` and `style` should be propagated to the same destination, right?

**Comment by avalanche1** [comment]
> But className is on the span tag wrapper.
In that case `className` target should be changed as well.
