### ISSUE TITLE
Button disabled with loading not prevent mouse event

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#19954]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-button-disabled-with-loading-5tipk)

Ref: #19924 

### Steps to reproduce
1. open F12 console panel
2. click Button

### What is expected?
prevent mouse event

### What is actually happening?
not prevent mouse event

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.3 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by afc163** [comment]
```diff
- .ant-btn-loading {
-   pointer-events: none;
- }
+ .ant-btn-loading:not([disabled]) {
+   pointer-events: none;
+ }
```
