### ISSUE TITLE
InputNumber数字输入框报错 Uncaught TypeError: Cannot read property 'left' of undefined

### ISSUE THREAD

**Issue by AllenJacen** [ant-design/ant-design#19955]
> [-] [ ] I have [searched] the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
InputNumber数字输入框报错 Uncaught TypeError: Cannot read property 'left' of undefined。
在antd官网的 InputNumber数字输入框文档中就能复现，只要选中数字就报错。
鼠标选中，类似与复制选中数字的加深选中。

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 3.13.0 |
| React | 15.4.2 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Cannot reproduce it.

**Comment by AllenJacen** [comment]
> Cannot reproduce it.
只要在https://ant.design/components/input-number-cn/的例子中，输入框中的数字，选中后，控制台就会报错

**Comment by AllenJacen** [comment]
> Hello @AllenJacen. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @AllenJacen, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

只要在https://ant.design/components/input-number-cn/的例子中，输入框中的数字，选中后，控制台就会报错

**Comment by afc163** [comment]
我这里无法重现，怀疑是你的某些 Chrome 插件导致的，你可以试试隐身模式。

**Comment by AllenJacen** [comment]
> 我这里无法重现，怀疑是你的某些 Chrome 插件导致的，你可以试试隐身模式。

感谢，的确是插件的问题，是Collamark插件的问题
