### ISSUE TITLE
三重模态对话框关闭后页面 body 无法滚动

### ISSUE THREAD

**Issue by concefly** [ant-design/ant-design#19956]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
Edit on CodeSandbox
https://codesandbox.io/s/hardcore-margulis-l75o0?fontsize=14&hidenavigation=1&theme=dark

### Steps to reproduce

![image](https://user-images.githubusercontent.com/6647656/69692265-6cbfa480-110c-11ea-985a-b5ec2a08c676.png)

1. 打开抽屉
1. 打开 m1(模态框1)，然后关闭
1. 关闭抽屉
1. 打开 m2(模态框2)，然后关闭
1. 页面 body 不滚动了

### What is expected?
关闭 m2 后，页面 body 要能滚动

### What is actually happening?
关闭 m2 后，页面 body 不能滚动

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.9.0 |
| System | mac |
| Browser | chrome Version 78.0.3904.97 (Official Build) (64-bit) |

### 补充说明
问题排查记录：
抽屉里弹出浮层，然后关闭浮层，rc-dialog 的 openCount ===1 并且 cacheOverflow 记录为全 hidden（因为抽屉打开的情况下，body 确实是 overflow hidden 的）

![image](https://user-images.githubusercontent.com/6647656/69691943-8c0a0200-110b-11ea-9355-fa115ec61d42.png)

再打开页面根部的浮层时，rc-dialog 的 openCount === 1，但 cacheOverflow 已经是全 hidden 了，没有重新记录 overflow 值，因此 cacheOverflow 记录仍然为全 hidden

![image](https://user-images.githubusercontent.com/6647656/69691961-9926f100-110b-11ea-934a-a079001a5d67.png)

浮层关闭时，body 被赋值成 cacheOverflow 的值，因此 body 无法滚动了

![image](https://user-images.githubusercontent.com/6647656/69691964-9f1cd200-110b-11ea-8781-55828e708db1.png)

rc-dialog@7.5.13
https://github.com/react-component/dialog/blob/master/src/Dialog.tsx#L379

**Comment by shaodahong** [comment]
这个原因是 `Modal` 用的是 `rc-dialog`, `Drawer` 用的是更底层的 `rc-util/lib/PortalWrapper`, 所以造成切换没办法统一，这个要抽出去

@jljsj33 这个是不是把 `switchScrollingEffect` 抽到 `rc-util/lib/PortalWrapper` 这里比较好

**Comment by hunter2009** [comment]
这个问题近期会修复么？

**Comment by shaodahong** [comment]
会，我会跟进下

**Comment by KaiEi1020** [comment]
这个问题仍然未被修复
