### ISSUE TITLE
4.0 preview site table component : remote load data ( ajax ) demo has bug——4.0预览站点 Table组件：远程加载数据（AJAX）的演示有BUG

### ISSUE THREAD

**Issue by thding** [ant-design/ant-design#19957]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/table-cn/#components-table-demo-ajax](https://next.ant.design/components/table-cn/#components-table-demo-ajax)

### Steps to reproduce
Switching page numbers using the pagination component——使用Pagination组件进行换页操作

### What is expected?
The current page displays correctly after switching pages——换页后当前页能正常显示

### What is actually happening?
The current page is still displayed as the first page after the page is changed——换页后仍然显示为第一页

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.9 |
| React | react |
| System | macOS Catalina 10.15.1 |
| Browser | chrome |

---
在升级之后我的项目中分页组件Pagination也变成了和演示页面上相同的情况，点击换页后数据切换正常，但是分页组件显示当前页（页码变蓝）还是第一页和目标页，然后鼠标点击其他区域后目标页的选中状态消失（不蓝了），数据已经切换了，但是分页器显示有问题。

**Comment by VoliBearCat** [comment]
same issue
