### ISSUE TITLE
表单渲染问题

### ISSUE THREAD

**Issue by yeliex** [ant-design/ant-design#1995]
使用react-redux的connect包裹一个Form.create()生成的表单以后,改变store的内容会导致表单重新渲染从而丢失输入的内容,不知是有意为之还是bug?

## 你做了什么？

`
TestForm = connect(({ store }) => {
  return {
    store
  }
})(Form.create({ mapPropsToFields: (...props) => props })(TestForm));
`
## 你期待的结果是：

在表单中调用一个action以后,用户输入的内容不会改变

## 实际上的结果和抱怨：

然而什么都没有了

## 本地环境信息

- antd 版本: 1.3.2
- 操作系统及其版本：OSX 10.11
- 浏览器及其版本: Chrome

## 另一种正常结果的使用
`
const TestForm = Form.create()(connect(({ store }) => {
  return {
   store
  };
})(TestForm));
`

**Comment by benjycui** [comment]
首先确认 `mapPropsToFields` 返回的结果没有重置 Form 的值。

**Comment by yeliex** [comment]
没有

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
没进一步反馈就关掉了，有问题再 reopen 。
