### ISSUE TITLE
安全问题: Input 组件 value 在控制台中显示明文问题, 即使设置type = password

### ISSUE THREAD

**Issue by zclzye** [ant-design/ant-design#19959]
**问题描述**

在Form组件中 包裹使用Input组件并将Input type设置为 password , 输入密码时在界面显示是无法看到,但是在控制台可以看到value是明文显示的. 

并且可以使用DOM相关操作进行获取。

**参照图**
控制台value显示

![value](https://user-images.githubusercontent.com/46665123/69695346-fd9b7d80-1116-11ea-8e65-e87ed4519ed7.png)

控制台获取值

![getValue](https://user-images.githubusercontent.com/46665123/69695435-51a66200-1117-11ea-9c93-870581553bd6.png)

**反馈**

希望官方基于一定支持，类似 github 和 天猫处理方式 ，不显示value 、" * "代替或者是其他好的解决方案。

天猫

![tianmao](https://user-images.githubusercontent.com/46665123/69695668-1bb5ad80-1118-11ea-9dca-eb8d148edf81.png)

github

![gihtub](https://user-images.githubusercontent.com/46665123/69695842-b1513d00-1118-11ea-8fe9-12dbde0bb9e7.png)

提交人: zclzye
时    间: 2019年 11 月 27日
邮    箱: zclzye@163.com

**Comment by iszmxw** [comment]
所有的密码只要浏览器保存了就可以获取到，手动审查元素，将input中`type = password`改为`type = type`照样可以查看密码

**Comment by zclzye** [comment]
> 所有的密码只要浏览器保存了就可以获取到，手动审查元素，将input中`type = password`改为`type = type`照样可以查看密码

是的,去除type是可以在界面上看到的，但这是属于用户自己操作，在自己的界面上看到的。

现在的问题是:在控制台源码里面可以看到明文的value,这是两个情况。如果你了解过chrome extension 使可以通过contentjs来获取到用户输入的密码，这可能存在一定的危险性。

另外，及时是这样。通过更改type属性看到和直接F12可以看到这应该是两个不一样的情况。

**Comment by zclzye** [comment]
另外，刚对比了一下在 material、antd-vue、vuetify 均有做这样的处理

**Comment by purple-force** [comment]
这样处理其实没什么用。
![image](https://user-images.githubusercontent.com/16146970/103325474-f9aefd00-4a86-11eb-8d51-5f8028018b79.png)
打开这个还是能看到，包括你说的天猫、github。 @zclzye
