### ISSUE TITLE
表格纵向滚动后在有滚动条的浏览器中列表会出现奇奇怪怪的对不齐

### ISSUE THREAD

**Issue by fwtcumt** [ant-design/ant-design#19952]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header](https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header)

### Steps to reproduce
在window系统中，给Table组件设置 scroll={y: 600} 后，给表格滑到最右边时，表格体和表头会有一个滚动条的错位。我已经发现原因了，因为纵向能滚动后，.ant-table-body 该元素有纵向的滚动条，而 .ant-table-header 没有纵向滚动条，这时候就完犊子啦。好吧，我就手动设置一下他们的滚动条宽度吧。这时候又引出一个小问题，就是设置横向滚动后，如果有左右列固定的情况，固定的列底部会有个17px的空位，我查了原因，应该是让出的17px是默认滚动条的宽度。我又手动给这个-17px的margin值去掉。然后表格完美运行。
随后发现，实际上并没有完美解决，在windows 谷歌上没事了，可是在Mac上出事儿了，一点点我设置的4px的距离没对齐，卧槽！

### What is expected?
期望表格组件无论设置横向还是纵向滚动，都能平稳运行。并且对齐。

### What is actually happening?
一旦设置纵向滚动，列对不齐。edge中表格体和头在滑动时有明显的延迟。

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.11.0 |
| System | windows |
| Browser | 谷歌、edge |

---
我把我的解决代码放这里吧：
.ant-table {

    //设置表格头部竖向滚动宽度
    .ant-table-header::-webkit-scrollbar {
      width: 4px;
    }

    //设置表格体滚动宽度
    .ant-table-body, .ant-table-body-inner {
      &::-webkit-scrollbar {
        width: 4px;
        height: 4px;
      }
      &::-webkit-scrollbar-thumb {
        border-radius: 4px;
        box-shadow: inset 0 0 5px rgba(0,0,0,0.2);
        background: #909090;
      }
      &::-webkit-scrollbar-track {
        box-shadow: inset 0 0 5px rgba(0,0,0,0.2);
        border-radius: 4px;
        background: #EDEDED;
      }
    }

    //解决固定列底部预留的空隙
    .ant-table-fixed-left, .ant-table-fixed-right {
      .ant-table-body-outer {
        margin-bottom: 0 !important;
      }
    }
  }

**Comment by fwtcumt** [comment]
错位问题在edge上没有，只在Windows的谷歌浏览器上有。Windows的谷歌浏览器上官方表格示例中横竖滚动的例子就是错位的。我就不弄啥复现现场了。

**Comment by afc163** [comment]
能帮忙截一些图么？

**Comment by fwtcumt** [comment]
我的电脑是 华为metebook X Pro 2019，谷歌浏览器版本  78.0.3904.108。
一下是表格组件的几张截图：
![横向滚时](https://user-images.githubusercontent.com/21078500/69730805-aec80500-1163-11ea-8b99-fd9b2526085b.png)
![横向不滚时](https://user-images.githubusercontent.com/21078500/69730824-b7b8d680-1163-11ea-95a0-3d7485c651e9.png)
![官方demo1](https://user-images.githubusercontent.com/21078500/69730837-be474e00-1163-11ea-85f4-4f9edd9bcb09.png)
![官方demo2](https://user-images.githubusercontent.com/21078500/69730846-c30c0200-1163-11ea-9d9b-1ff5f03ed2a3.png)

**Comment by afc163** [comment]
看上去是 windows 滚动条宽度的计算有点问题。

**Comment by afc163** [comment]
Chrome 的版本号是多少？

**Comment by afc163** [comment]
我这里重现不出来，能麻烦差看下你本地控制台，发一下这里的 dom 结构出来么？

<img width="903" alt="image" src="https://user-images.githubusercontent.com/507615/69777960-6b11e180-11dd-11ea-8875-70111bafb69a.png">

**Comment by fwtcumt** [comment]
> 我这里重现不出来，能麻烦查看下你本地控制台，发一下这里的 dom 结构出来么？
> 
> <img alt="image" width="903" src="https://user-images.githubusercontent.com/507615/69777960-6b11e180-11dd-11ea-8875-70111bafb69a.png">

没问题，下班回家我发😂

**Comment by afc163** [comment]
找到原因了，我发个 PR。

**Comment by fwtcumt** [comment]
> 我这里重现不出来，能麻烦查看下你本地控制台，发一下这里的 dom 结构出来么？
> 
> <img alt="image" width="903" src="https://user-images.githubusercontent.com/507615/69777960-6b11e180-11dd-11ea-8875-70111bafb69a.png">

好像不一样，我还是发一下吧
![微信截图_20191128220956](https://user-images.githubusercontent.com/21078500/69812828-eac69d00-122b-11ea-9f3e-8e3289af3fba.png)

**Comment by hanguihe** [comment]
@afc163 我这边也有个类似的问题，但不是滚动条引起的。复现方法：表格多设置几个列，最后一列fixed右边，x设置滑动，再设置可展开行。点击展开后，fixed的那一列严重不对齐。截图如下
<img width="1171" alt="截屏2019-11-28下午11 47 52" src="https://user-images.githubusercontent.com/29910482/69819371-cb367100-1239-11ea-8a03-f5aa0546c25a.png">

**Comment by fwtcumt** [comment]
> @afc163 我这边也有个类似的问题，但不是滚动条引起的。复现方法：表格多设置几个列，第一列和最后一列都设置fixed，x设置滑动，再设置可展开行。点击展开后，fixed的那两列严重不对齐。截图如下
> <img alt="截屏2019-11-28下午11 51 59" width="1155" src="https://user-images.githubusercontent.com/29910482/69819648-56176b80-123a-11ea-9774-f94c07c6b82e.png">

噗哈哈哈哈哈哈😂，看来可折叠的表格不适合固定列[手动滑稽]

**Comment by fwtcumt** [comment]
![微信截图_20191130000211](https://user-images.githubusercontent.com/21078500/69880350-b5da4900-1304-11ea-98bf-d6ec820c3622.png)
还是不行，放弃吧，这破Windows Chrome。

**Comment by afc163** [comment]
手动没 windows，周一找 @chenshuai2144 借一下再找找彻底的解决方案。当前暂时加上下面这段样式作为 workaround 应该可以修复。

```css
.ant-table-hide-scrollbar::-webkit-scrollbar {
  width: 15px;
}
```

**Comment by fwtcumt** [comment]
> 手动没 windows，周一找 @chenshuai2144 借一下再找找彻底的解决方案。当前暂时加上下面这段样式作为 workaround 应该可以修复。
> 
> ```css
> .ant-table-hide-scrollbar::-webkit-scrollbar {
>   width: 15px;
> }
> ```

NB了哥，我的电脑设置成 17px 妥了！！

**Comment by afc163** [comment]
不一样的，rc-table 里是 js 算出来的。

**Comment by fwtcumt** [comment]
我检查啦，我电脑没问题啦。谢谢antd团队的大佬支持，尽快组织发版把😄
![WechatIMG23](https://user-images.githubusercontent.com/21078500/70198323-8040c000-1749-11ea-8f54-a82c3f35d543.png)
![WechatIMG24](https://user-images.githubusercontent.com/21078500/70198324-8040c000-1749-11ea-8f7a-221c1299ae69.png)

**Comment by enjkvbej** [comment]
> @afc163 我这边也有个类似的问题，但不是滚动条引起的。复现方法：表格多设置几个列，第一列和最后一列都设置fixed，x设置滑动，再设置可展开行。点击展开后，fixed的那两列严重不对齐。截图如下 <img alt="截屏2019-11-28下午11 51 59" width="1155" src="https://user-images.githubusercontent.com/29910482/69819648-56176b80-123a-11ea-9774-f94c07c6b82e.png">

hi，我也遇到了同样的问题，请问解决了吗

**Comment by a405575711** [comment]
![image](https://user-images.githubusercontent.com/69945095/193009451-3ec8ba42-ccaf-42fb-9b43-53e29b4c0de4.png)
![image](https://user-images.githubusercontent.com/69945095/193009520-cb836c5d-b825-4341-94ce-2c0d45bc022b.png)
请问一下，这个版本之前不是修复了嘛？
