### ISSUE TITLE
When the Upload is wrapped in form.getFieldDecorator, the removed file is still in the submission 

### ISSUE THREAD

**Issue by blusoul** [ant-design/ant-design#19953]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-lumiere-c14d4?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. select a file, then remove it
2. submit and watch the console

### What is expected?
the fileUpload field's value is undefind

### What is actually happening?
but it's an object { file: { status: 'removed'}, fileList: []}

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.12.0 |
| System | mac |
| Browser | Chrome 78.0.3904.108 |

---
there is no problem before version 3.23.0, we used the 3.15.2 before.

**Comment by fwtcumt** [comment]
返回的这个值确实很难搞

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10277#issuecomment-518089919
