### ISSUE TITLE
message updating with key ,但是不能手动移除了

### ISSUE THREAD

**Issue by czbczb** [ant-design/ant-design#19950]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-meadow-ro2lp?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
let loadingKey = 'loading'
let hideLoading = message.loading({content: '正在加载数据．．．', key: loadingKey, duration: 0})
hideLoading()     // not work

### What is expected?
不需要自动移除，我需要调用hideloading方法手动移除message

### What is actually happening?
duration：0
此时无法移除，
duration不为0时，antd设置默认3秒后会移除

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.9.0 |
| System | 1 |
| Browser | Google Chrome 已是最新版本 版本 78.0.3904.108（正式版本） （64 位） |

**Comment by yoyo837** [comment]
ref: #18621 @wendzhue

**Comment by czbczb** [comment]
您好，我看过这个issues，我希望的是通过callback去移除message，不需要更新操作

**Comment by czbczb** [comment]
能不能给个异步移除的例子呢 @yoyo837

**Comment by wendzhue** [comment]
@yoyo837 好的，我会处理这个

**Comment by yoyo837** [comment]
@czbczb 再提供个旧版本时功能正常的在线demo。

**Comment by czbczb** [comment]
@yoyo837 
![image](https://user-images.githubusercontent.com/23630100/69688285-94107480-1100-11ea-898a-11dd5b8dc6c0.png)
旧的，您看这个是可以的，https://ant.design/components/message-cn/

**Comment by wendzhue** [comment]
Reason:

https://github.com/ant-design/ant-design/blob/bed1f7775b2ceb52be6da84cf6106ed7a1a29c30/components/message/index.tsx#L69-L83

**Comment by Aemple** [comment]
@yoyo837 这个问题可以交给我来处理吗？😀

**Comment by czbczb** [comment]
thank u @yoyo837
