### ISSUE TITLE
希望antd - table组件，单选和多选情况下，点击某一行的任何位置都可以选中某一行，而不是只有点击复选框才可以选中某一行

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#19962]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
方便用户选中某行列表数据并进行相关操作。

### What does the proposed API look like?
配置某个参数（rowSelection.xxx  = true）可以开启点击某一行的任何位置都可以选中某一行。

**Comment by afc163** [comment]
<img width="696" alt="image" src="https://user-images.githubusercontent.com/507615/69709312-2122f000-1138-11ea-8b7e-67e9b06ff0fd.png">

https://ant.design/components/table-cn/#components-table-demo-row-selection

**Comment by VoliBearCat** [comment]
![image](https://user-images.githubusercontent.com/11676384/76298831-0b0afb00-62f5-11ea-8536-694cd4400356.png)

![image](https://user-images.githubusercontent.com/11676384/76298911-270e9c80-62f5-11ea-847c-0c1ba115e969.png)
