### ISSUE TITLE
Upload禁止在弹窗离进行拖拽

### ISSUE THREAD

**Issue by qingming418** [ant-design/ant-design#19965]
点击Upload后，浏览器会出现弹窗，在非IE浏览器下可以从该弹窗拖拽文件。
![image](https://user-images.githubusercontent.com/20061205/69717586-4c610b80-1147-11ea-9be0-a6d7e0336b3b.png)
在windows系统上，这样操作后容易导致浏览器崩溃。
所以请问有没有办法可以禁止这种拖拽方式？

**Comment by yoyo837** [comment]
这是系统行为。拖拽后崩溃可以来个在线demo, 新开issue。

**Comment by qingming418** [comment]
官方组件地址就能复现。不知道能不能禁止这种行为

**Comment by yoyo837** [comment]
那并不是崩溃，那表示你叫浏览器打开那个图片。就和你平时往浏览器tab里拖文件一样的效果。

**Comment by yoyo837** [comment]
你自己打开个百度，开文件管理器/finder 往里拖个文件看看啥效果就知道了，一毛一样！

**Comment by qingming418** [comment]
哦。卸载了搜狗输入法，往里面拖文件就不会卡死了

**Comment by yoyo837** [comment]
ref: #11787 #10799

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11787#issuecomment-481160600
