### ISSUE TITLE
antd官网components页面左右两栏的滚动不顺，当我鼠标在左边时，有时只能滚动右边

### ISSUE THREAD

**Issue by xyj404** [ant-design/ant-design#19969]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar-cn/](https://ant.design/components/calendar-cn/)

### Steps to reproduce
滚动左右两栏

### What is expected?
鼠标在哪，滚动哪儿

### What is actually happening?
鼠标和滚动行为没有发生在同侧

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.8.6 |
| System | macOS Mojave 10.14.3 |
| Browser | chrome 76.0.3809.100 |

**Comment by afc163** [comment]
这个浏览器本身有关系，有时候需要点击一下激活当前区域来滚动，我们这边可能做不了什么。
