### ISSUE TITLE
【upload】uoload 直传 oss 返回状态码 204 ，无法认为上传成功

### ISSUE THREAD

**Issue by limerickgds** [ant-design/ant-design#19966]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#components-upload-demo-fileList](https://ant.design/components/upload-cn/#components-upload-demo-fileList)

### Steps to reproduce
官网 oss demo ，action 改为 oss 链接，即可复现。

### What is expected?
上传返回 204 ，认为成功

### What is actually happening?
一直认为上传中

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16 |
| System | macos 10.15.1 |
| Browser | chrome 78 |

**Comment by afc163** [comment]
The problem you describe had been fixed in https://github.com/react-component/upload/pull/35 two years ago.
