### ISSUE TITLE
【bug】Tabs标签滑动最后一页的第一个Tab点击后没有自适应效果

### ISSUE THREAD

**Issue by neko0623** [ant-design/ant-design#19961]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/#components-tabs-demo-slide](https://ant.design/components/tabs-cn/#components-tabs-demo-slide)

### What is expected?
Tabs标签滑动至第二页，第二页的第一个Tab只显示了一半，点击后Tab向右移动，完整显示该Tab。

### What is actually happening?
Tabs标签滑动至第二页，第二页的第一个Tab只显示了一半，点击后没有向右移动，还是只显示了半个。

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| System | macOS Mojave 10.14.6 |
| Browser | Google Chrome 78.0.3904.108（正式版本）64位 |

---
抱歉，我不是开发人员，描述的可能不是特别准确，我在AntDesign文档中试过，的确是缺失了这个效果

**Comment by afc163** [comment]
目前的逻辑是固定移动一页的宽度，不是移到某个具体的 tab。

**Comment by neko0623** [comment]
不不不，不是这个意思，不是说移动页的宽度，不是最后一页的翻页没有问题，但如果翻到最后一页，这页的最右端是最后一个tab，最左端的第一个tab就可能只显示了一半，按理说，点击这半个tab，整个标签组应该会向右移动，定位在这个tab的起点，让这个tab被完整显示才对，测试过如果不是在最后一页，当前页的第一个tab或最后一个tab显示一半，点击它都是会向右或向左移动完整显示这个tab，只有最后一页的第一个tab不行。

**Comment by neko0623** [comment]
> 目前的逻辑是固定移动一页的宽度，不是移到某个具体的 tab。

不不不，不是这个意思，不是说移动页的宽度，不是最后一页的翻页没有问题，但如果翻到最后一页，这页的最右端是最后一个tab，最左端的第一个tab就可能只显示了一半，按理说，点击这半个tab，整个标签组应该会向右移动，定位在这个tab的起点，让这个tab被完整显示才对，测试过如果不是在最后一页，当前页的第一个tab或最后一个tab显示一半，点击它都是会向右或向左移动完整显示这个tab，只有最后一页的第一个tab不行。

**Comment by neko0623** [comment]
@afc163 不不不，不是这个意思，不是说移动页的宽度，不是最后一页的翻页没有问题，但如果翻到最后一页，这页的最右端是最后一个tab，最左端的第一个tab就可能只显示了一半，按理说，点击这半个tab，整个标签组应该会向右移动，定位在这个tab的起点，让这个tab被完整显示才对，测试过如果不是在最后一页，当前页的第一个tab或最后一个tab显示一半，点击它都是会向右或向左移动完整显示这个tab，只有最后一页的第一个tab不行。

**Comment by neko0623** [comment]
> 目前的逻辑是固定移动一页的宽度，不是移到某个具体的 tab。

@afc163 不不不，不是这个意思，不是说移动页的宽度，不是最后一页的翻页没有问题，但如果翻到最后一页，这页的最右端是最后一个tab，最左端的第一个tab就可能只显示了一半，按理说，点击这半个tab，整个标签组应该会向右移动，定位在这个tab的起点，让这个tab被完整显示才对，测试过如果不是在最后一页，当前页的第一个tab或最后一个tab显示一半，点击它都是会向右或向左移动完整显示这个tab，只有最后一页的第一个tab不行。

**Comment by afc163** [comment]
没太理解你的意思，能不能录一个 gif 说明一下？

**Comment by neko0623** [comment]
我没有图床，挂个外链放gif图来说明一下吧，麻烦看一下这个链接，具体问题描述卸载里面了。@afc163 https://www.notion.so/Tabs-90e3832fece04b36a84816d7a2287822

**Comment by afc163** [comment]
Fixed in #24284
