### ISSUE TITLE
firefox浏览器 Table 添加 scrol l导致滚动及其缓慢

### ISSUE THREAD

**Issue by lixiaoyang1992** [ant-design/ant-design#1996]
## 你做了什么？

Table添加了scroll参数{{ x: true, y: 300 }}

## 你期待的结果是：

右侧出现滚动条正常滚动

## 实际上的结果和抱怨：

滚动的非常缓慢，滚动条失灵

## 可重现的在线演示

官网示例在火狐下也会出现问题

http://ant.design/components/table#components-table-demo-fixed-header

## 本地环境信息

- antd 版本:1.3.2
- 操作系统及其版本：windows
- 浏览器及其版本:火狐

**Comment by benjycui** [comment]
没有 windows 的环境，然后 mac firefox 是没问题的。

先更新下浏览器看看。

**Comment by lixiaoyang1992** [comment]
更新到了47.0 ，依然会有迟缓的问题。
同事的imac上也测出了相同的问题。 @benjycui

**Comment by afc163** [comment]
我怎么也没测出来。。。我就是用 Firefox 进行的开发。

**Comment by lixiaoyang1992** [comment]
目前只是鼠标滚轮滚动的时候，滚动的非常慢，没有其它问题。

**Comment by afc163** [comment]
在 windows 下的 Firefox 里重现出来了。

1. 滚动缓慢，无论是滚轮滚动还是点击滚动条。
2. 滚动条样式有时会奇异性的消失。

等我有空时再看下。lixiaoyang1992 有空也可以帮忙研究一下。

**Comment by afc163** [comment]
重新安装最新版 antd 即可修复。

原来的逻辑在所有浏览器下都可能有性能问题。
