### ISSUE TITLE
Not supporting LabeledValue as Select value makes it very difficult to identify deleted items

### ISSUE THREAD

**Issue by xedef** [ant-design/ant-design#19970]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/xedef/pen/JjjgjKm](https://codepen.io/xedef/pen/JjjgjKm)

### Steps to reproduce
In the provided CodePen link set `UNSUPPORTED` to Select's value property and check that control fails to render.

### What is expected?
Control should render, supporting an array of LabeledValue objects as value property

### What is actually happening?
The control fails to render with error "Objects are not valid as a React child (found: object with keys {key, label})."

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | 16.10.2 |
| System | macOS |
| Browser | Chrome |

---
* This was tested with property `mode` set to "tags"
* As per documentation, the value for Select control should support LabeledValue and LabeledValue[]. 
* This is specially needed for controlling which items were removed/deselected.

**Comment by afc163** [comment]
Try `labelInValue`

**Comment by fgblomqvist** [comment]
To clarify: to be able to pass a `LabeledValue` or `LabeledValue[]` to a `Select`, you need to also pass the property `labelInValue` as true. This is not mentioned in the docs to this day.
