### ISSUE TITLE
Inconsistent vertical text position in <Button />

### ISSUE THREAD

**Issue by AntonBramsen** [ant-design/ant-design#19972]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/delicate-lake-hk14y)

### Steps to reproduce
Render multiple `<Button />` components on top of eachother 

### What is expected?
Consistent vertical placement of the text inside the `<Button />` component.

### What is actually happening?
In every other `<Button />` component the text seems to be one pixel closer to the bottom and not vertically centered.

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | "react": "^16.9.0" |
| System | macOS Catalina v 10.15 |
| Browser | Chrome Version 77.0.3865.90 (Official Build) (64-bit) |

---
This also happens when you have icons inside the button.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/18603

cc @zombieJ

**Comment by zombieJ** [comment]
Seems Chrome adjust align logic, need more investigate: https://codesandbox.io/s/optimistic-babbage-lt3c8
