### ISSUE TITLE
validateFields校验object类型数据只返回一次error

### ISSUE THREAD

**Issue by fnll** [ant-design/ant-design#19975]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/async-fast-yc0sp)

### Steps to reproduce
第一点击提交时可以在控制台看到错误信息，再次点击时error就变为null了

### What is expected?
多次点击，getFieldsError可以正常返回error

### What is actually happening?
第二次点击时，getFieldsError返回为null

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.12.0 |
| System | macos |
| Browser | chrome 78 |

**Comment by afc163** [comment]
> 第一点击提交时可以在控制台看到错误信息

你给的链接第一次提交时看不到任何错误信息。

**Comment by fnll** [comment]
@afc163 sorry，麻烦重新打开链接试下

**Comment by fnll** [comment]
似乎和initValue有关系，如果去掉InitValue一切正常
