### ISSUE TITLE
使用 typescript   antd 时 CheckableTagProps 中没有 style?: React.CSSProperties; 不能通过 style 来改变样式。

### ISSUE THREAD

**Issue by chbinghu** [ant-design/ant-design#19978]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以使用改变 CheckableTag 的样式

### What does the proposed API look like?
CheckableTagProps 中添加 style

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/18300

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/69772587-4b71bd80-11cb-11ea-8bc5-7d52d807f925.png)
