### ISSUE TITLE
给<ConfigProvider>组件加上getPopupContainer属性后，<Modal>组件报错

### ISSUE THREAD

**Issue by fwtcumt** [ant-design/ant-design#19974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/](https://ant.design/components/config-provider-cn/)

### Steps to reproduce
1. 给全局配置组件 ConfigProvider 设置getPopupContainer，设置成：<ConfigProvider getPopupContainer={node => node}>，因为我想统一使用父元素。
2. 业务组件中使用 Modal 组件，使用visible控制显示。<Modal visible>。然后你就发现报错了。
3. 错误信息：PortalWrapper.js:185 Uncaught TypeError: Cannot read property 'appendChild' of undefined。

### What is expected?
希望给全局配置组件加上getPopupContainer配置，让选择框、日期等，统一渲染到其父元素上。

### What is actually happening?
能实现统一渲染到父元素的功能，但是影响了Modal的使用。去掉该配置，Modal恢复正常。

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.11.0 |
| System | windows Mac OS |
| Browser | 谷歌 78.0.3904.108 |

部分错误截图：
![微信截图_20191127235829](https://user-images.githubusercontent.com/21078500/69738964-d625ce80-1171-11ea-83b0-8b84d2d8b4a0.png)

**Comment by afc163** [comment]
```diff
- <ConfigProvider getPopupContainer={node => node}>
+ <ConfigProvider getPopupContainer={node => node.parent}>
```

**Comment by fwtcumt** [comment]
> ```diff
> - <ConfigProvider getPopupContainer={node => node}>
> + <ConfigProvider getPopupContainer={node => node.parent}>
> ```

我点击按钮让MOdal显示，仍然报错，我查看了这个node，居然是 undefined。回头我弄一个小的demo仓库，你们再试试。

**Comment by afc163** [comment]
我写错了，node.parentNode

**Comment by fwtcumt** [comment]
我建了一个demo，运行一下试试呗。运行环境最好是windows上的谷歌浏览器，可以顺便检查一下表格纵向滚动。
git地址：https://github.com/fwtcumt/feedback-antd.git

**Comment by afc163** [comment]
```
- <ConfigProvider getPopupContainer={node => node}>
+ <ConfigProvider getPopupContainer={node => node.parentNode}>
```

**Comment by fwtcumt** [comment]
> ```diff
> - <ConfigProvider getPopupContainer={node => node}>
> + <ConfigProvider getPopupContainer={node => node.parentNode}>
> ```

和 node => node 效果一模一样，不好使😂

**Comment by afc163** [comment]
https://github.com/fwtcumt/feedback-antd/pull/1

因为 Modal 的 `getContainer` 不存在 node 参数，所以需要判断一下。
