### ISSUE TITLE
Table – expandRowRender children element

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#19973]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
First of all – love the library!

I have a table with `expandRowRender` set. I would like to place the same table inside the `expandRowRender`component so the columns have the same widths. Right now `tr.ant-table-expanded-row` has 2 child elements – first `td` that is there to indent the table because of the expand icon cell, and the second `td` where `expandedRowRender` content is placed.

Question – is it possible to remove the first `td`, so the `expandRowRender` content takes the whole width of the row?

### What does the proposed API look like?
If the thing before is not possible, maybe a `indentExpandRow` attribute could be introduced, set to `true` by default. When set to `false` the table would not render the first `td` of `tr.ant-table-expanded-row`, and the second `td` would have the `colspan` set to the number of columns the table has.

**Comment by zombieJ** [comment]
In antd v4, first td removed: https://next.ant.design/components/table/#components-table-demo-expand

**Comment by Sean-Tay** [comment]
Hi, is there any way to get back the first ```td``` in v4?  

My Table in v3:
<img width="836" alt="Screenshot 2020-05-21 at 12 57 38 PM" src="https://user-images.githubusercontent.com/10514942/82524963-d45a2800-9b62-11ea-9123-b4c9f7ca2ed9.png">

My Table in v4:
<img width="836" alt="Screenshot 2020-05-21 at 12 57 44 PM" src="https://user-images.githubusercontent.com/10514942/82524970-d7edaf00-9b62-11ea-9328-12524760bb08.png">

**Comment by vincentFzzf** [comment]
how to fix at the v3.x ?
