### ISSUE TITLE
antd@4 Row Col flex auto width

### ISSUE THREAD

**Issue by ycjcl868** [ant-design/ant-design#19981]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
```jsx
<Row
  type="flex"
  align="middle"
>
  <Col}>
    Hello
  </Col>
  <Col>
    World
  </Col>
</Row>
```

### What is expected?
![image](https://user-images.githubusercontent.com/13595509/69781748-fee9aa80-11e9-11ea-8f67-aa122f9e7042.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/13595509/69781751-014c0480-11ea-11ea-9277-e97940feba5b.png)

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.10 |
| React | latest |
| System | OS X |
| Browser | Chrome |

**Comment by shaodahong** [comment]
yep, Col default width `100%`

**Comment by ycjcl868** [comment]
It's a breaking change

**Comment by ycjcl868** [comment]
Row flex type should be compatible.

**Comment by zombieJ** [comment]
@shaodahong , is that possible to keep the v3 behavior?

**Comment by shaodahong** [comment]
ok, i revert this
