### ISSUE TITLE
官网菜单滚动会触发页面滚动

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#19988]
#### 条件
- 当前页面的 scrollTop 不等于 0时;
- 滚动左侧菜单时经过 menu item 时会触发右侧页面滚动。

#### 问题判断

menu 的 item 的 scrollHeight 和 innerHeight 不相等，，好像在整 drawer 时就发现了这个问题。。。

![Kapture 2019-11-28 at 20 32 44](https://user-images.githubusercontent.com/6802825/69806617-4427cf80-121e-11ea-8c65-b93b9b467ecd.gif)

**Comment by afc163** [comment]
无法重现。

**Comment by yoyo837** [comment]
我遇到过。

**Comment by jljsj33** [comment]
> 无法重现。

gif 不是放在上面了，，，把页面拉到底部，，，然后滚动左侧菜单。。。

**Comment by jljsj33** [comment]
Menu 的 item 好像比 menu 要宽或高一像素的，导至会触发 onScroll 事件。。

**Comment by jljsj33** [comment]
![image](https://user-images.githubusercontent.com/6802825/69863081-e1463f00-12d6-11ea-81d5-8e8b8dac76f8.png)

![image](https://user-images.githubusercontent.com/6802825/69863091-e7d4b680-12d6-11ea-85da-7f3254fd077d.png)

**Comment by Liu-Ya** [comment]
![pro](https://user-images.githubusercontent.com/23520283/69925248-19719b80-14ea-11ea-8661-a7da3e319254.gif)

我之前还以为是个feature

**Comment by shaodahong** [comment]
@Liu-Ya 你这个就是浏览器默认行为 https://github.com/ant-design/ant-design/issues/20062#issuecomment-561131309

**Comment by Liu-Ya** [comment]
@shaodahong 不是的，到底之后向上滚动浏览器也应该是先滚动左侧菜单，刚试了下pro就是正常的，也是这个屏录得问题，其他位置也会是这种情况

**Comment by Liu-Ya** [comment]
![error](https://user-images.githubusercontent.com/23520283/70050754-a9a70200-160a-11ea-98c3-358ab165b04a.gif)
这个应该比较明显

**Comment by jljsj33** [comment]
搞得我骗你们一样，大爷的。。。

**Comment by shaodahong** [comment]
看着确实有问题，但是我这边很难复现

**Comment by fwtcumt** [comment]
官网左侧的菜单滚动是不大好用，但是能用，不碍事儿。我选择性忽略之😂
