### ISSUE TITLE
Tabs 组件 type="card" 时，size="small" 无效

### ISSUE THREAD

**Issue by Lpmvb** [ant-design/ant-design#19984]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/late-worker-6ibci)

### Steps to reproduce
https://codesandbox.io/s/late-worker-6ibci

### What is expected?
small 样式正常

### What is actually happening?
small 样式无效

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | latest |
| System | Mac OS |
| Browser | Google Chrome 78.0.3904.108（正式版本） （64 位） |

**Comment by afc163** [comment]
目前是这样的，card 样式的 Tabs 设计规范上没有大小号，只有一套。
