### ISSUE TITLE
测试时，如何模拟触发Upload组件的beforeUpload方法

### ISSUE THREAD

**Issue by nqdy666** [ant-design/ant-design#1998]
项目需要写单元测试，beforeUpload方法下的代码因为无法模拟选择文件，无法被覆盖到。
请问如何能够模拟触发beforeUpload方法呢？

**Comment by afc163** [comment]
目前我们也没有好的方案，建议搜索和自行探索：https://www.google.com.hk/search?q=input+upload+unit+test&ie=utf-8&oe=utf-8&client=firefox-b-ab&gws_rd=cr,ssl
