### ISSUE TITLE
Select 组件添加getPopupContainer属性以后在IE11上进行选择操作时会闪

### ISSUE THREAD

**Issue by stupid2013** [ant-design/ant-design#19999]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://react-component.github.io/select/?path=/story/rc-select--getpopupcontainer](http://react-component.github.io/select/?path=/story/rc-select--getpopupcontainer)

### Steps to reproduce
选择Select时，页面会闪。

### What is expected?
不闪。

### What is actually happening?
每选择一次，屏幕就会闪一次。

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.6 |
| System | windows |
| Browser | IE 11.1130.17134.0 |

---
这个链接貌似是antd自己的？在IE11里面根本打不开，会直接报错。所以没办法直接验证。请排查。

**Comment by afc163** [comment]
Duplicate of #21039
