### ISSUE TITLE
Tree Select filterTreeNode true with treeNodeFilterProp only emphasizes matching nodes

### ISSUE THREAD

**Issue by steveswork** [ant-design/ant-design#19997]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-treeselect-custom-filter-test-7qnj4)

### Steps to reproduce
Type in the search box.

### What is expected?
Non matching items will be removed from the dropdown.

### What is actually happening?
 Matching dropdown items emphasis is increased but non-matching items are not removed from dropdown.

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.12.0 |
| System | 64-bit Window |
| Browser | Chrome |

---
Also discovered is that setting treeNodeFilterProp="key" has no effect at all. This behavior is not in the docs as far as I can tell. Is that part of the specification?

**Comment by steveswork** [comment]
@afc163, have you gotten a chance to take a quick look at this ticket? Any idea what might be causing the reported issue?

**Comment by afc163** [comment]
I don't realy understand your problem, it there any unexpected behavior?

<img width="656" alt="image" src="https://user-images.githubusercontent.com/507615/75409651-4e0fba80-5954-11ea-91f2-9eefc202a94f.png">

**Comment by steveswork** [comment]
I have over 300 nodes in the tree. I would like to use the `treeNodeFilterProp` to reduce the size of this tree. Instead what I observed to be happening is that non-matching nodes were not removed - matching node titles were simply highlighted. Is the tree filter not supposed to "filter" away non-matching nodes?

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-treeselect-custom-filter-test-fn6rs

`treeNodeFilterProp` works well to reduce item counts of Tree.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/507615/76953666-0aecaa00-694a-11ea-8611-98aac7849bc0.png">

**Comment by steveswork** [comment]
Just tested your claim, @afc163 . It is currently factual for antd@3.26.14. I suppose the actionable solution to this will be to upgrade to version 3.26.14. That seems to work for me.
