### ISSUE TITLE
tabs页面切换性能消耗过大,在ie11下切换卡顿

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#20003]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ly2011/antd-tabs-bug](https://github.com/ly2011/antd-tabs-bug)

### Steps to reproduce
必须把代码拉取到本地运行(在 codesandbox 中没办法复现此问题)，并且不断切换或者频繁左右切换两个tab页面，打开chrome的性能监控页面，可以看到cpu使用率飙升

![image](https://user-images.githubusercontent.com/8147202/69848393-fad68f00-12b4-11ea-80e0-22cdc1f571b0.png)

看了一下，官网的也有这个问题：

![image](https://user-images.githubusercontent.com/8147202/69849276-340ffe80-12b7-11ea-9607-913a54a5cdab.png)

### What is expected?
不断切换或者频繁左右切换两个tab页面，可以看到cpu使用率占用不高。

### What is actually happening?
不断切换或者频繁左右切换两个tab页面，打开chrome的性能监控页面，可以看到cpu使用率飙升。

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.12.0 |
| System | win 10 |
| Browser | Chrome 78.0.3904.70 |

**Comment by afc163** [comment]
Try active `forceRender` prop for TabPane, avoid render perf cost during animation.

**Comment by fengyun2** [comment]
@afc163 `forceRender` 属性会一次性把所有tab页面的搜索请求接口和控件接口都触发吧，会造成更大的性能开销吧，为何不能将已经打开的tab页面缓存起来从而提胜渲染性能呢？

**Comment by afc163** [comment]
> 为何不能将已经打开的tab页面缓存起来从而提胜渲染性能呢

现在默认已经是这么做的。

**Comment by fengyun2** [comment]
> Try active `forceRender` prop for TabPane, avoid render perf cost during animation.

![image](https://user-images.githubusercontent.com/8147202/69893368-6ff4a380-134b-11ea-9454-12aab1491721.png)

已按要求加上了 `forceRender` 参数，但是性能依然还是那么堪忧，官方是不是得重新考虑一下这个问题呢？

```js
const { TabPane } = Tabs;

const tabs = [
  { id: 1, title: "cest1", children: "文本1" },
  { id: 2, title: "cest2", children: "文本2" }
];

class TabTable extends React.Component {
  state = {};

  render() {
    return (
      <Tabs defaultActiveKey="1">
        {tabs.map(item => (
          <TabPane tab={item.title} key={item.id} forceRender>
            {item.children}
          </TabPane>
        ))}
      </Tabs>
    );
  }
}

```

**Comment by afc163** [comment]
可以帮忙排查一下具体消耗在哪里了，或者试试 `animated={false}` 关掉动画。

**Comment by fengyun2** [comment]
> 可以帮忙排查一下具体消耗在哪里了，或者试试 `animated={false}` 关掉动画。

尝试过 `animated={false}` 关掉动画，但是没什么效果。

![image](https://user-images.githubusercontent.com/8147202/69911303-4e331380-1454-11ea-95e2-e22863a0f883.png)

![image](https://user-images.githubusercontent.com/8147202/69911378-a7e80d80-1455-11ea-8001-eb7dff855338.png)

**Comment by afc163** [comment]
可以试试不要把大块内容放在 TabPane 内，把 Tabs 只做 Tabs 头。内容独立放在 Tabs 外面，依赖当前 tab 状态做显隐。

**Comment by fengyun2** [comment]
> 可以试试不要把大块内容放在 TabPane 内，把 Tabs 只做 Tabs 头。内容独立放在 Tabs 外面，依赖当前 tab 状态做显隐。

试过了，没有效果，而且就算去掉了 `Tabs`, 改为 `Button` 方式去切换显隐都是消耗资源。下面的演示方案均为 `内容独立放在 Tabs 外面，依赖当前 tab 状态做显隐` 下的效果。

- 方案一：用 `antd` `Button`组件去切显隐的源码及效果:

```js
<>
  <div className="btns">
    <Button onClick={() => this.onChange(tabs[0].id)}>
      {tabs[0].title}
    </Button>
    <Button
      onClick={() => this.onChange(tabs[1].id)}
      style={{ marginLeft: "8px" }}
    >
      {tabs[1].title}
    </Button>
  </div>
  <div className="tab-content">
    {tabs.map(item => (
      <div
        className="tab-item"
        key={item.id}
        style={{
          display: item.id === this.state.activeKey ? "block" : "none"
        }}
      >
        {item.children}
      </div>
    ))}
  </div>
</>
```

![image](https://user-images.githubusercontent.com/8147202/70012524-90249c80-15af-11ea-9107-cb783a2a99a6.png)

- 方案二: 用原生的 `button` 去切显隐的源码及效果:

```js
<>
  <div className="btns">
    <button onClick={() => this.onChange(tabs[0].id)}>
      {tabs[0].title}
    </button>
    <button
      onClick={() => this.onChange(tabs[1].id)}
      style={{ marginLeft: "8px" }}
    >
      {tabs[1].title}
    </button>
  </div>
  <div className="tab-content">
    {tabs.map(item => (
      <div
        className="tab-item"
        key={item.id}
        style={{
          display: item.id === this.state.activeKey ? "block" : "none"
        }}
      >
        {item.children}
      </div>
    ))}
  </div>
</>
```

![image](https://user-images.githubusercontent.com/8147202/70012730-425c6400-15b0-11ea-9f13-376e20ab2ba0.png)

总结：
所以是不是有可能是 `antd`  整个框架的动画机制导致页面性能变差了呢？而不仅仅是 `Tabs` 组件引起的问题呢？

**Comment by afc163** [comment]
是的，动画本身有一定的性能消耗。

**Comment by lishaoh** [comment]
的确，当tab中内容稍微过多一些，切换很卡顿，CPU占用很高，现在有具体解决办法吗？

**Comment by fengyun2** [comment]
@afc163  我这边的产品需要打开的页面都保留在tab页面，打开十几个tab列表页面后，win10 16G的机器在最新版本的chrome下接近卡死状态，目前有什么办法解决吗？旧的项目是用iframe挂载tab页面，无限多tab页面的性能相差不大，现在项目改为 `react`+ `antd` 技术栈后，被产品经理多次吐槽及质疑技术问题了。

**Comment by afc163** [comment]
1. tabs 里的内容如果 keep alive 的话，注意用 `shouldComponentUpload` 去优化 react 性能，避免修改 A 组件页面的内容 rerender 了其他页面的内容。这个本身和 Tabs 关系不大。
2. 如果不希望 keep alive，建议用 `<Tabs destroyInactiveTabPane />` 彻底销毁隐藏 tab 的内容，避免无谓的 rerender。缺点是切换的时候需要重新渲染。

**Comment by fengyun2** [comment]
是切换的时候cpu瞬间飙升，切换完之后的2s后cpu趋于平稳，页面内容多的话，应该是动画效果导致的性能问题

**Comment by afc163** [comment]
我个人不建议在 React SPA 下做多 tabs 形态的产品，内存里放太多东西了。除了 iframe 也可以看看微前端架构：https://github.com/umijs/qiankun

**Comment by zoxiyo** [comment]
> 我个人不建议在 React SPA 下做多 tabs 形态的产品，内存里放太多东西了。除了 iframe 也可以看看微前端架构：https://github.com/umijs/qiankun

我通过Single-SPA框架做的微前端架构(antd+react)，然后是多Tabs形态的产品(头部是Antd-tabs，只不过content是通过redux+css display控制显示隐藏)。Keep-Alive保存Tab页内的缓存。卡顿还是没有很好的提升。

**Comment by fengyun2** [comment]
> > 我个人不建议在 React SPA 下做多 tabs 形态的产品，内存里放太多东西了。除了 iframe 也可以看看微前端架构：https://github.com/umijs/qiankun
> 
> 我通过Single-SPA框架做的微前端架构(antd+react)，然后是多Tabs形态的产品(头部是Antd-tabs，只不过content是通过redux+css display控制显示隐藏)。Keep-Alive保存Tab页内的缓存。卡顿还是没有很好的提升。

`keep-alive` 是自己实现的呢还是使用了哪个第三方库实现的呢？

**Comment by fengyun2** [comment]
> > 我个人不建议在 React SPA 下做多 tabs 形态的产品，内存里放太多东西了。除了 iframe 也可以看看微前端架构：https://github.com/umijs/qiankun
> 
> 我通过Single-SPA框架做的微前端架构(antd+react)，然后是多Tabs形态的产品(头部是Antd-tabs，只不过content是通过redux+css display控制显示隐藏)。Keep-Alive保存Tab页内的缓存。卡顿还是没有很好的提升。

我的项目只有一个项目，场景是每次打开一个页面就新增一个tab，具体的外观如下：

![image](https://user-images.githubusercontent.com/8147202/78763423-b45a1500-79b7-11ea-8835-978fffca4601.png)

**Comment by ddtramp** [comment]
这个应该是 props 的问题， 新的状态导致 tab content 重新渲染
用 pureComponent 或者 memo 应该可以解决掉

**Comment by concefly** [comment]
补充一个卡顿 case。

当页面 dom 复杂之后，rc-tab 默认的 tab 滚动到激活项的行为会导致比较严重的 reflow 消耗。

https://github.com/react-component/tabs/blob/a3150988c5f8819f88a4d7bb7f438047aafeba5d/src/ScrollableTabBarNode.js#L104

![image](https://user-images.githubusercontent.com/6647656/82026124-e2242f00-96c4-11ea-8dbc-e6ebff1674c7.png)

希望可以提供一个配置开关，业务上可以禁用这个行为
