### ISSUE TITLE
when autocomplete is controlled and text includes value，cann't delete the value .

### ISSUE THREAD

**Issue by yunlei23** [ant-design/ant-design#20000]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-fast-sdxbf?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
```javascript
const dataSource = [{ text: "apple（", value: "apple" }];

class App extends React.Component {
  render() {
    const { getFieldDecorator } = this.props.form;

    return (
      <Form.Item>
        {getFieldDecorator("fruit")(
          <AutoComplete dataSource={dataSource} style={{ width: 200 }} />
        )}
      </Form.Item>
    );
  }
}
```

- choose apple
- delete the input

### What is expected?
value delete

### What is actually happening?
value is autocomplete

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.9.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
如果需要使用受控的 AutoComplete，需要保证 onChange 的内容和 value 是一致的，也就是 value 和 label 的内容必须一致。这也是 AutoComplete 组件的特性之一，option 选中的内容和填入的内容需要一致，才能受控可改。
