### ISSUE TITLE
是否可以在Form的normalize方法中更新其他表单元素的值

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#2000]
## 场景
如图：
![image](https://cloud.githubusercontent.com/assets/17123400/15928237/59560544-2e78-11e6-9f75-743d1e0554fb.png)
表单中输入1（select）通过normalize格式化输出，并将最终格式化后的值填写在输入2（input）中

## 问题
在normalize中调用this.props.form.setFieldsValue会出现死循环
或者有没有其他方式处理上述问题？

## Demo
http://codepen.io/hyaaon/pen/BzBerR?editors=0010

**Comment by hhhyaaon** [comment]
输入2可以修改，同时也可以响应输入1的变化

**Comment by benjycui** [comment]
监听 `Select` 的 `onChange` 事件，在 `onChange` 里面 `setFieldsValue`。

事件坚挺方式参见文档：http://ant.design/components/form#this.props.form.getFieldProps(id, options)

**Comment by hhhyaaon** [comment]
提供具体场景：
【下拉选】中包含三个选项，通过选中值的不同，获取选中值的子项，更新到【结果】中
![image](https://cloud.githubusercontent.com/assets/17123400/15990340/a00fb484-30c2-11e6-9ae6-b71fcbfccfb9.png)
下拉选变更时存在以下逻辑：
1、已选中【全部】后，不允许再选中其他项，提示先取消选中全部
2、当前选中项为【全部】，清除此前选中项，只选中全部

以上逻辑在normalize中编写，normalize获取最终值后，通过该值更新【结果】

## 问题
在normalize中调用this.props.form.setFieldsValue会出现死循环
或是否有其他方法可以解决此问题

## Demo
http://codepen.io/hyaaon/pen/bebJKV?editors=1010

**Comment by yiminghe** [comment]
http://react-component.github.io/form/examples/normalize.html

**Comment by hhhyaaon** [comment]
明白了，多谢多谢 :）
