### ISSUE TITLE
Upload 组件，使用 fileList 属性预览已有的图片时，样式错误

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design#20001]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-austin-8oq9r)

### Steps to reproduce
Upload 组件，使用 fileList 属性预览已有的图片时，样式错误。打开控制台可以发现，预览已有图片比上传图片，DOM结构中多了一个div，导致样式错误。

### What is expected?
Upload 组件，使用 fileList 属性预览已有的图片时，能正确显示图片

### What is actually happening?
Upload 组件，使用 fileList 属性预览已有的图片时，样式错误。

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | chrome |

---
请看一下图片：
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-upload-bug1.ulc0fsxi1i.png)
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-upload-bug2.sqv7vi4d9mi.png)

**Comment by maxmeng93** [comment]
问题应该是这段代码。
components / upload / uploadList.tsx  第237、243行的 <div></div> 标签，应该使用 <></>
``` jsx
      const dom = (
        <div className={infoUploadingClass}>
          <div>
            <div className={`${prefixCls}-list-item-info`}>{iconAndPreview}</div>
            {actions}
            <Animate transitionName="fade" component="">
              {progress}
            </Animate>
          </div>
        </div>
      );
```

**Comment by afc163** [comment]
@qq645381995

**Comment by qq645381995** [comment]
不能用 <></> 旧版本不支持，我看下问题

**Comment by yoyo837** [comment]
`Fragment` ?

**Comment by qq645381995** [comment]
这个要用块元素，不然不是图片类型的展示不显示文件名

**Comment by yoyo837** [comment]
那只能改之前的样式来兼容它了，加一层`> div`行不？

**Comment by qq645381995** [comment]
#20008
