### ISSUE TITLE
Mentions 配合 Form 使用示例，点击Reset清空表单，但未清空Mentions框中内容

### ISSUE THREAD

**Issue by greateidea** [ant-design/ant-design#20005]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/mentions-cn/](https://ant.design/components/mentions-cn/)

### Steps to reproduce
按示例输入内容后，点击Submit，再点击Reset, Mentions内容未清空但会提示表单错误

### What is expected?
再点击Reset, Mentions内容应清空

### What is actually happening?
Mentions内容未清空但会提示表单错误

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | React |
| System | Win10 |
| Browser | Chrome 78.0.3904.70 |

**Comment by legendjw** [comment]
@afc163  @greateidea  实际使用过程中我们也发现了这个问题，官方的案例也有这个问题，最后经过我们测试发现设置initialValue为空字符串可以避免这个问题。也就是说初始值不设置或者设置为undefined会产生这个BUG。
```js
{getFieldDecorator('content', {
    initialValue: '',
})(
    <Mentions rows="2">          
    </Mentions>
)}
```
