### ISSUE TITLE
TimePicker组件选中值时需要将该行拉到最顶部，当初始值在23:59:59时 只显示一行，不美观。建议选中行在下拉框中间

### ISSUE THREAD

**Issue by shiningWolf** [ant-design/ant-design#20029]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/time-picker-cn/](https://ant.design/components/time-picker-cn/)

### Steps to reproduce
将时间拖到23:59:59，只显示一行

### What is expected?
23:59:59能出现在下拉框的中间

### What is actually happening?
出现在下拉框的顶部

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.6.3 |
| System | windows |
| Browser | chrome |

---
测试要求= =

**Comment by afc163** [comment]
这是按我们的设计要求来的，非常抱歉。
