### ISSUE TITLE
Is there a way to make api call when expanding table to show nested table?

### ISSUE THREAD

**Issue by nsksaisaravana** [ant-design/ant-design#20027]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/57378786/is-there-a-way-to-make-api-call-when-expanding-table-to-show-nested-table](https://stackoverflow.com/questions/57378786/is-there-a-way-to-make-api-call-when-expanding-table-to-show-nested-table)

### Steps to reproduce
```
  expandedRowRender={(rowData)=>{
          //eachRow(rowData);
          return this.returnNestedRows(rowData);
        }}
```

    private returnNestedRows=(rowData)=>{
  
      const menu = (
        <Menu>
          <Menu.Item>Action 1</Menu.Item>
          <Menu.Item>Action 2</Menu.Item>
        </Menu>
      );
      
      const columns = [
        { title: 'Date', dataIndex: 'date', key: 'date' },
        { title: 'Name', dataIndex: 'name', key: 'name' },
        {
          title: 'Status',
          key: 'state',
          render: () => (
            <span>
              <Badge status="success" />
              Finished
            </span>
          ),
        },
        { title: 'Upgrade Status', dataIndex: 'upgradeNum', key: 'upgradeNum' },
        {
          title: 'Action',
          dataIndex: 'operation',
          key: 'operation',
          render: () => (
            <span className="table-operation">
              <a>Pause</a>
              <a>Stop</a>
              <Dropdown overlay={menu}>
                <a>
                  More <Icon type="down" />
                </a>
              </Dropdown>
            </span>
          ),
        },
      ];
  
  
     
  
   
        return ComponentServicesTrainigDetail.getTrainingHeader(rowData.Id).then((trainingDetailItems)=>{
          return <Table columns={columns} dataSource={trainingDetailItems}  pagination={{ pageSize: 5 }} />;
   
        });
     
  
  
  
  
    }

### What is expected?
showing the expected nested table

### What is actually happening?
showing the below error

![image](https://user-images.githubusercontent.com/17681573/69912348-3d969380-147c-11ea-86b0-fb7d03ac648e.png)

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.8.3 |
| System | Windows |
| Browser | Google chrome |

**Comment by nsksaisaravana** [comment]
I tried with async await for the function but still, I am getting the same error.

```
 await ComponentServicesTrainigDetail.getTrainingDetail(rowData.Id);
       let trainingDetailItems=ComponentServicesTrainigDetail.returnTrainingDetail();
       return <Table columns={columns} dataSource={trainingDetailItems}  pagination={{ pageSize: 5 }} />
```

![image](https://user-images.githubusercontent.com/17681573/69922330-9eab7f00-14ef-11ea-86a9-f75b0361b059.png)

**Comment by huntdream** [comment]
try `onExpand`

**Comment by nsksaisaravana** [comment]
@huntdream i tried as per your suggestion but i am getting the below error 

private onTableRowExpand(expanded, rowData){
   

      const columns = [
        { title: 'Training Name', dataIndex: 'Title', key: 'title' },
        { title: 'Name', dataIndex: 'name', key: 'name' },
        {
          title: 'Status',
          key: 'state',
          render: () => (
            <span>
              <Badge status="success" />
              Finished
            </span>
          ),
        },
        { title: 'Upgrade Status', dataIndex: 'upgradeNum', key: 'upgradeNum' },
        {
          title: 'Action',
          dataIndex: 'operation',
          key: 'operation',
          render: () => (
            <span className="table-operation">
              <a>Pause</a>
              <a>Stop</a>
              {/* <Dropdown overlay={menu}>
                <a>
                  More <Icon type="down" />
                </a>
              </Dropdown> */}
            </span>
          ),
        },
      ];

      if(expanded){
        // ajax call to get expanded data 
        ComponentServicesTrainigDetail.getTrainingDetail(rowData.Id).then((trainingDetailItems)=>{
          return <Table columns={columns} dataSource={trainingDetailItems}  pagination={{ pageSize: 5 }} />;
          // this.setState({
          //   trainingDetails:trainingDetailItems
          // });
        });
        //return <Table columns={columns} dataSource={[]}  pagination={{ pageSize: 5 }} />;
      }
    }

![image](https://user-images.githubusercontent.com/17681573/69924622-7710e280-1500-11ea-9519-744f8274c1f1.png)

**Comment by huntdream** [comment]
![Kapture 2019-12-02 at 9 55 11](https://user-images.githubusercontent.com/7903755/69925263-2db59880-14ea-11ea-826f-a64cb5b8aeab.gif)
Do you want to make table work like this ?

**Comment by nsksaisaravana** [comment]
exactly, but the child one data is coming as a promise, but when I use the promise I am getting the error.

if you have any code repo please let me know, I will check the code.

**Comment by huntdream** [comment]
You can make a request in `onExpand`, then feed the retrieved  data to correspond nested table

**Comment by nsksaisaravana** [comment]
Below is my code, how do i feed data to the nested table

```
onExpand ={this.onTableRowExpand}

private onTableRowExpand(expanded, rowData){
 if(expanded){
        // ajax call to get expanded data 
        ComponentServicesTrainigDetail.getTrainingDetail(rowData.Id).then((trainingDetailItems)=>{
          return <Table columns={columns} dataSource={trainingDetailItems}  pagination={{ pageSize: 5 }} />;
       
        });
        
      }
}

private  returnNestedRows=  (rowData)=>{
return <Table columns={columns} dataSource={[]}  pagination={{ pageSize: 5 }} />
}
```

**Comment by huntdream** [comment]
Hello, I wrote a repo, check it 
https://codesandbox.io/s/naughty-wescoff-w1jhd

**Comment by afc163** [comment]
I found no errors in your codesandbox.

**Comment by huntdream** [comment]
> I found no errors in your codesandbox.

I wrote this example repo for @nsksaisaravana , not for problem reproduction
(我这写给楼主的 🤣 )

**Comment by nsksaisaravana** [comment]
@huntdream OMG it works like charm. Tons of thanks.

I have converted your code to class component and really that itself took me hours because i don't know how to put the key-value array in SetSate.

Once again @huntdream thanks and closing this issue.

**Comment by nsksaisaravana** [comment]
@huntdream I found only one issue, when you open the second row, first-row child data is getting vanished. Please check the screenshot below.

![image](https://user-images.githubusercontent.com/17681573/69934368-d2a19700-1525-11ea-99d5-580dada30942.png)

**Comment by huntdream** [comment]
You should merge your new state into the previous one rather than overwrite it

**Comment by hypeople** [comment]
> https://codesandbox.io/s/naughty-wescoff-w1jhd

What if I want use another onExpand ? I have tried ı need to show third table when ı use onExpand for second table with new function it's not working it's opens itself again.
