### ISSUE TITLE
menu 组件的箭头样式

### ISSUE THREAD

**Issue by ohhoney1** [ant-design/ant-design#20035]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
查看menu组件的箭头样式问题

### What is expected?
正常显示

### What is actually happening?
1. chrome ：箭头向上时，显示有个小圆点，并不是真正的箭头，请参考图片1。
2. safari ：箭头向下时，显示有问题，请参考图片2。

简单调试了下，因为不同浏览器对有小数点像素的渲染不同，[components/menu/style/index.less#L233](https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less#L233) 这里的高度改为 2px ，在两个浏览器下显示都正常了

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.9 |
| System | mac OS 10.14 |
| Browser | Chrome |

**Comment by ohhoney1** [comment]
![image](https://user-images.githubusercontent.com/20284707/69936561-18a12f80-1513-11ea-87f3-94a373944443.png)

![image](https://user-images.githubusercontent.com/20284707/69936493-f14a6280-1512-11ea-991a-599e011042e3.png)

**Comment by afc163** [comment]
@jljsj33 来看看？

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/27565

**Comment by qinghua5453** [comment]
话说  有没有发现 这个属性overflowedIndicator    根本就不生效

**Comment by OWRIG** [comment]
> 话说 有没有发现 这个属性overflowedIndicator 根本就不生效

+1

**Comment by Jasonlee6789** [comment]
请问下怎么把这个箭头从右边换到左边啊？
