### ISSUE TITLE
select组件远程搜索时有value重复项时导致继续搜索不能重置下拉列表

### ISSUE THREAD

**Issue by rongj** [ant-design/ant-design#20031]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-nvhjt1?file=index.js](https://stackblitz.com/edit/react-nvhjt1?file=index.js)

### Steps to reproduce
输入查询结果，下拉列表更新，如果列表中包含相同的value, 进一步查询时搜索结果不会重置更新

### What is expected?
有重复value时不影响接下来的搜索结果展示

### What is actually happening?
有相同的value项导致进一步搜索下拉列表不对，下拉列表项越来越多，导致浏览器卡死

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | * |
| System | * |
| Browser | * |

**Comment by afc163** [comment]
value 不应该有重复项，否则 Select 不知道你选了哪个。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12334

**Comment by rongj** [comment]
问题不是选择报错，是搜索的时候数据展示的下拉列表不对

**Comment by sharonroseyu** [comment]
这个问题解决了嘛？
