### ISSUE TITLE
antd table中的columns如果render设置为一个组件做优化，切换页数componentdDidMount还是会执行！！

### ISSUE THREAD

**Issue by yizhengfeng-jj** [ant-design/ant-design#20032]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/test-columns-4or0j

### Steps to reproduce
点击页数，看打印结果

### What is expected?
antd table中的columns如果render设置为一个组件做优化，切换页数shouldComponentUpdate还是会执行！！ 我想要的是，切换页数的时候，是否重新渲染可以在shouldComponentUpdate里面控制，现在每次都是新的控制不了

### What is actually happening?
实际结果不是我希望的那样的

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12 |
| System | windows10 64 |
| Browser | chrom 78 |

---
这个问题是在2016提出来的，当时其他优秀开发者提出了pr,我看了你们的讨论，当时是说要做一个columns的管理机制，但是现在还是有这个问题，请您看看我的问题，希望得到回复，万分感谢
这是之前讨论的链接：https://github.com/react-component/table/pull/95

**Comment by yizhengfeng-jj** [comment]
我刚刚又看了一下以前的讨论和自己的测试，其实是每次切换页数是column会返回新的，shouldComponentUpdate没有作用

**Comment by afc163** [comment]
你这个例子中相当于每一行都有一个 Column 组件，行每次都会重新渲染生成，Column 也会生成新的，`componentDidMount` 就会触发，和有没有 shouldComponentUpdate 关系不大。

**Comment by yizhengfeng-jj** [comment]
> 你这个例子中相当于每一行都有一个 Column 组件，行每次都会重新渲染生成，Column 也会生成新的，`componentDidMount` 就会触发，和有没有 shouldComponentUpdate 关系不大。

感谢您的回复，这个场景确实是这样的，我现在明白了，谢谢
