### ISSUE TITLE
less nested import doesn't work properly

### ISSUE THREAD

**Issue by lunaticusgreen** [ant-design/ant-design#20036]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8jx9y)

### Steps to reproduce
*  Follow this guild https://ant.design/docs/react/customize-theme#Configure-webpack-to-load-an-alternate-less-file-and-scope-global-styles and add any selector to wrap antd import
* Add collapse panel into your wrapper
* Done, it's broken

### What is expected?
Everything works as there is not wrapper selector

### What is actually happening?
In source code of collapse panel I have seen this example of code ( pay attention to & > &-item):

```
.@{collapse-prefix-cls} {
  .reset-component;

  background-color: @collapse-header-bg;
  border: @border-width-base @border-style-base @border-color-base;
  border-bottom: 0;
  border-radius: @collapse-panel-border-radius;

  & > &-item {
```

when I don't use wrapper or just import antd.less into javascript directly, it compiles into something like this:
```
.ant-collapse > .ant-collapse-item > .ant-collapse-header .ant-collapse-arrow svg {
  display: inline-block;
}
```

but when I'm importing antd.less this way:
```
#antd-wrapper {
  @import "antd/dist/antd.less";
}

```

I'm getting:
```
#antd-wrapper .ant-collapse > #antd-wrapper .ant-collapse-item > .ant-collapse-header .ant-collapse-arrow svg {
  display: inline-block;
}
```

This second #antd-wrapper seems an error to me

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.11.0 |
| System | macos 10.15.1 (19B88) |
| Browser | Firefox developer edition 71.0b12 (64-bit) |

---
I've just found it when I isolated my application as it was written in guide and than noticed that some components are broken, while most of them are not.
for some reason less not imports well in codesandbox, but it can be easily reproduced locally

**Comment by afc163** [comment]
It simply cannot works in this way.

**Comment by lunaticusgreen** [comment]
But it does, I have created simple repo with less import into `.strange-wrapper`

https://github.com/lunaticusgreen/antd-react-less-test

Here we are with wrapper:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/9621964/70144767-add92b00-16af-11ea-9df0-5d2f05ce9f4e.png">
And without:
<img width="1405" alt="image" src="https://user-images.githubusercontent.com/9621964/70144969-1a542a00-16b0-11ea-9dc4-678ddbae2dd3.png">

**Comment by lunaticusgreen** [comment]
I'm just trying to understand if it's considered as a bug, or it's expected behavior and this guide https://ant.design/docs/react/customize-theme#Configure-webpack-to-load-an-alternate-less-file-and-scope-global-styles cannot be used and I need to create some workaround for style isolation purposes

**Comment by zj1024** [comment]
Hi, That's a problem I have, too, I use lessc compile tiwce to fix it.
just like this: [https://codesandbox.io/s/adoring-hill-422qf?file=/src/theme/antd.dark.less](https://codesandbox.io/s/adoring-hill-422qf?file=/src/theme/antd.dark.less)

step1: lessc compile antd less to antd css
step2: create scope less file, include step1 result - antd css
step3: lessc compile scope less 🎉

![image](https://user-images.githubusercontent.com/34162213/145701488-b3d1a18c-3502-42b4-9513-f59bf258ca4b.png)

so, I think add antd css socpe is operations that are not frequently modified, this way available, I hope it helps!
