### ISSUE TITLE
small table 表头分组右边框问题

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#20030]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-sammet-43ts4)

### Steps to reproduce
之前在v3.23.2有提过，表头分组时缺失边框的问题，现在似乎只要存在表头分组，右侧就会多边框

### What is expected?
正常的边框

### What is actually happening?
边框重复了

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.4.1 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
related issue https://github.com/ant-design/ant-design/issues/18762
