### ISSUE TITLE
select dropdown 在pagination中与Select中表现不一致

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#20037]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-gauss-yms3w?fontsize=14&hidenavigation=1&theme=dark)

### What is expected?
select dropdown 内容靠左

### What is actually happening?
select dropdown 内容靠右

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome 版本 78.0.3904.108（正式版本） （64 位） |

---
这个算不算问题？觉得内容靠右有点别扭
![image](https://user-images.githubusercontent.com/23520283/69938923-7fc1e280-1519-11ea-8da7-526faa2fa089.png)
![image](https://user-images.githubusercontent.com/23520283/69938942-8d776800-1519-11ea-8205-48e663820356.png)

**Comment by afc163** [comment]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/507615/69940251-c7963900-151c-11ea-9089-e362d23097da.png">

是你设置的样式影响了 Select 的默认样式，请自行排查。
