### ISSUE TITLE
RangePicker not close automatically

### ISSUE THREAD

**Issue by hec9527** [ant-design/ant-design#20046]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.baidu.com/s?wq="no link, why requred?"](https://www.baidu.com/s?wq="no link, why requred?")

### Steps to reproduce
```js
// this not close after selected end time 
<RangePicker mode={['month','month'} />

// this close automatically 
<RangPicker />

//  select month by <RangePicker /> component, it not close automatically but others do
```

### What is expected?
it close automatically

### What is actually happening?
close it by click outside the component 

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12  |
| System | mac osX 10.14.5 |
| Browser | chrome  v 78 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E6%8C%87%E5%AE%9A%E4%BA%86-DatePicker/RangePicker-%E7%9A%84-mode-%E5%B1%9E%E6%80%A7%E5%90%8E%EF%BC%8C%E7%82%B9%E5%87%BB%E5%90%8E%E6%97%A0%E6%B3%95%E9%80%89%E6%8B%A9%E5%B9%B4%E4%BB%BD/%E6%9C%88%E4%BB%BD%EF%BC%9F
