### ISSUE TITLE
DatePicker: Day of the month remains selected as month is changed

### ISSUE THREAD

**Issue by megawac** [ant-design/ant-design#20047]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

### Steps to reproduce
1) Have a date selected in the date picker  
2) Change the month
3) Notice that the day of the month (e.g. the 2nd) that was selected previously will remain selected on the next month.

### What is expected?
The selected day state should not be set on the previously selected day of the month

### What is actually happening?
The day of the month that was selected will remain selected between month changes

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3475472/69980628-9c9cec80-14fe-11ea-84b5-d721aedc2ccb.gif)

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | Ubuntu |
| Browser | Firefox |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6146#issuecomment-308927566 and it will be removed in 4.0 new DatePicker.

https://github.com/ant-design/ant-design/pull/20023
