### ISSUE TITLE
Tooltip在Table的FilterIcon下不显示正确的title内容

### ISSUE THREAD

**Issue by ReganxZheng** [ant-design/ant-design#20049]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-ives-m1gik)

### Steps to reproduce
https://codesandbox.io/s/infallible-ives-m1gik

### What is expected?
Tooltip展示正确填入的title内容

### What is actually happening?
Filter menu

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.8 |
| System | MacOS |
| Browser | Chrome |

**Comment by hustKiwi** [comment]
看起来是这行代码对上述逻辑有影响：https://github.com/ant-design/ant-design/blob/master/components/tooltip/index.tsx#L269

如果改下 title 和 overlay 的顺序，就应该默认用 title 覆盖 overlay 的取值：
```javascript
overlay={overlay || title || ''}
```
