### ISSUE TITLE
Colorful buttons and select reset value

### ISSUE THREAD

**Issue by FGCorp** [ant-design/ant-design#20044]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1-if button component have a color props we can more customize the buttons.
2-Sometimes i need to reset the select's selected value to noting.i want to looklike as the first start noting selected.when the select rendered what value i send it. for exmaple, think it use with field decorator. i m trying initialValue: booleanValue ? 1 : null. if i type like this it start with a 0 value which not in the select ids.

### What does the proposed API look like?
<Button color="#F3F3F3">
                TEST
              </Button>

                {getFieldDecorator('selectedId', {
                  rules: [{ required: true, message: 'select an option!' }],
                  initialValue: boolValue!== -1 ? 1 : null
                })(
                  <Select>
                    {optionsForSelect.list.map(item => (
                      <Select.Option key={item.id} value={item.id}>
                        {item.name}
                      </Select.Option>
                    ))}
                  </Select>
                )}

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14915#issuecomment-464991519

**Comment by FGCorp** [comment]
i want to learn select component value set like clear button do. mean, set it value noting. when i try to set it null or undefined it show 0 value.i dont want to see 0. i want to see notting.

**Comment by afc163** [comment]
你可以用中文，说实话我不太看得懂。
