### ISSUE TITLE
Antd Table 表格控件的rowSelection 选中效果，会一直冒泡到顶层组件

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#20043]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-stpnx)

### Steps to reproduce
只需要点击下选中，即可看见控制台输出checkBox的选中事件，该onChange事件会一直冒泡到顶层组件

### What is expected?
希望能够阻止下table中的checkBox的选中事件冒泡，这样我在外层组件就不需要再阻止一次了

### What is actually happening?
该事件如果不阻止，会冒泡到顶层组件，在父组件有onChange属性的时候，会出现value变成event类型

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | win7 |
| Browser | Google Chrome  78.0.3904.70（正式版本） |

**Comment by afc163** [comment]
div 为什么会绑定 onChange？有什么其他场景我不了解的么？

**Comment by Catsbe** [comment]
我们有个需求是做个可编辑的表格弹框控件，然后表格内容输入完毕，点击确认按钮，将表格的内容以拼接字符串的方式回填到父组件控件中。我在做的时候发现父组件拥有onChange属性的时候，选中table的时候就会触发onChange事件。我觉得既然rowSelection作为table组件的一部分，那么选中事件应该止于table，而不应该继续冒泡到顶层组件。

**Comment by afc163** [comment]
可以在 codesandbox 还原一下最小真实场景么，我相信你代码里 onChange 是没有放在 div 上的。

**Comment by Catsbe** [comment]
我们的项目是基于redux构建的，所以父组件需要onChange属性来传递子组件值的变化，并且真实场景是在可编辑表格里的明细组件，需要弹框一个可编辑的表格组件。复现起来有点复杂，你就可以把div当成是父组件一样的意思，这个样例只是为了证明table的checkBox选中事件的确会一直冒泡到顶层组件（如果不加阻止的话）
我只能贴个图给你看看，这个onChange属性是放在table的columns里的onCell属性里
![Uploading image.png…]()

**Comment by afc163** [comment]
你的 CheckBox 列是自行构造的么？我这样指定 onCell 不是会包裹到 rowSelection 里的选择列的。 https://codesandbox.io/s/antd-reproduction-template-8x0fp

> stopPropagation 可能不是最好的解决方案，原生 input 控件的 onChange 冒泡 antd 现在很少去特别处理，我希望看看问题全貌。

**Comment by Catsbe** [comment]
https://codesandbox.io/s/antd-reproduction-template-878qs
我已经最小化还原场景了，具体实现步骤，点击TEST_COL2输入框中左边的图标，弹出可编辑表格，然后点击添加按钮，添加完一行数据后，点击选中，即可看见控制台输出的冒泡事件，该事件冒泡到了最外层的可编辑表格的onChange函数中

**Comment by afc163** [comment]
```diff
  renderCell = () => {
    const {
      inputType,
      nowValue,
      dataIndex,
      children,
      width,
+     onChange,
      ...restProps
    } = this.props;
    return <td {...restProps}>{this.renderInput()}</td>;
  };
```

试试不要把 `onChange` 加到原生 td 元素上，而是赋给内部真实的 Input 如何？

**Comment by Catsbe** [comment]
我照你这样试了一下，发现确实没有继续冒泡了。感谢~

**Comment by afc163** [comment]
理论上所有 input 的 onChange 都会向上冒泡，如果**原生父元素**上有 onChange 就会捕捉到，这是浏览器的默认行为。但是问题是，我不清楚为啥要给**原生父元素**（比如 body、div、td 等等）加 `onChange`，看上去是没有意义的。

**Comment by Catsbe** [comment]
好的，多谢提醒，我以后会注意的~
