### ISSUE TITLE
Make td removable expandable row in table

### ISSUE THREAD

**Issue by Firetuy** [ant-design/ant-design#20048]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Makes table more flexible

### What does the proposed API look like?
<table removeTd={true} />

**Comment by afc163** [comment]
Cannot understand your issue.

**Comment by Firetuy** [comment]
Sorry, its not an issue, is a complement to the expandable row in table, that have a "column" in the left that gets in the way

**Comment by Firetuy** [comment]
https://codesandbox.io/s/dank-glitter-9o3um

**Comment by Firetuy** [comment]
This issue is duplicated, sorry #19973
