### ISSUE TITLE
又快到圣诞节了

### ISSUE THREAD

**Issue by wfucksky** [ant-design/ant-design#20051]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
又快到圣诞节了

### What does the proposed API look like?
又快到圣诞节了

**Comment by stupid2013** [comment]
哈哈哈哈哈哈哈  所以呢 又有新的特效吗

**Comment by wfucksky** [comment]
666

**Comment by wfucksky** [comment]
6
