### ISSUE TITLE
should need add new attribute show/hide delete button for each item on the Upload List.

### ISSUE THREAD

**Issue by vankhoadesign** [ant-design/ant-design#20055]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We should need add new attribute show/hide delete button for each item on the Upload List. Because They want to show delete button for only owner and other permission.

### What does the proposed API look like?
[{
        uid: file.id,
        name: file.title,
        status: 'done',
        url: file.url,
       showRemove: false
    },{
        uid: file.id,
        name: file.title,
        status: 'done',
        url: file.url,
       showRemove: true
    }]

**Comment by Rustin-Liu** [comment]
I am working on it.

**Comment by mooSylla** [comment]
Hello any updates ?

**Comment by saruuman** [comment]
would be great to implement this

**Comment by afc163** [comment]
Supported via https://github.com/ant-design/ant-design/pull/26684
