### ISSUE TITLE
this.popupInstance.alignInstance.forceAlign is not a function

### ISSUE THREAD

**Issue by pasturn** [ant-design/ant-design#2005]
提问之前，建议先阅读[这份提示](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question)。:-)

如果是报告 bug，请按照下列格式编辑问题，务必提供复现步骤，否则恕难解决，非常感谢！

## 你做了什么？

使用Select组件实现一个多选的功能

## 实际上的结果和抱怨：

Select多项选择选项后又取消选项，

浏览器报一个错误：

this.popupInstance.alignInstance.forceAlign is not a function    --Trigger.js

看了一下rc-trigger的Trigger.js代码：

`forcePopupAlign() {
    if (this.state.popupVisible && this.popupInstance && this.popupInstance.alignInstance) {
      this.popupInstance.alignInstance.forceAlign();
    }
  },`

想知道forceAlign()这个方法在哪里实现?

## 可重现的在线演示

简单环境下，没有报错。

## 本地环境信息

- antd 版本:1.3.2 
- rc-trigger 版本:1.5.0
- 操作系统及其版本：MacOS 10.11 
- 浏览器及其版本:Chrome 50.0.2661.102 (64-bit)

**Comment by benjycui** [comment]
[官网例子](http://ant.design/components/select#components-select-demo-multiple) 正常，麻烦提供可重现的在线 demo 和步骤？

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
> 简单环境下，没有报错。

这么一句话，实在的判断不了是否有问题。

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by pasturn** [comment]
问题找到了[align](https://github.com/react-component/align/commit/51f8bd81d63564c9a39d92a40c7b0c2619d53a8c)新加了forceAlign方法，本地没更新，感谢各位
