### ISSUE TITLE
typescript 导出并没有组件的 Props 及一些内部 interface 如无法 import { TableProps, ColumnProps } from 'antd'

### ISSUE THREAD

**Issue by eczn** [ant-design/ant-design#20060]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比方说，在 TypeScript 语境下需要自定义 Table 组件渲染的时候，就很有必要使用内部的 ColumnProps 接口用于定义表格「每行的数据及组件」

### What does the proposed API look like?
希望 antd 能直出如下能力：

``` ts
import { TableProps, ColumnProps } from 'antd';

interface MyDBRecord {
    name: string;
    age: number;
    foo: string;
    bar: string;
}

interface MyDBRecordColumn extends ColumnProps<MyDBRecord> { }

export function buildCustom(columns: MyDBRecordColumn[]) {
    /* some code here */
}
```

**Comment by eczn** [comment]
![image](https://user-images.githubusercontent.com/13131724/70034325-f4fde800-15eb-11ea-9d00-681e120cbea0.png)

应该是这个问题，我在 node_modules 里的 lib/index.d.ts 里加上这个之后就可以 import 了

**Comment by eczn** [comment]
最小化 demo : 
https://github.com/eczn/antd-mininal-demo/blob/master/src/test.ts

**Comment by afc163** [comment]
Try `import { TableProps, ColumnProps } from 'antd/lib/Table';` of `import { TableProps, ColumnProps } from 'antd/es/Table';`

**Comment by eczn** [comment]
> Try `import { TableProps, ColumnProps } from 'antd/lib/Table';` of `import { TableProps, ColumnProps } from 'antd/es/Table';`

这个在 linux 下跑不动，antd/lib/Table 里面的 table 要换成小写的，mac 大小写不敏感
