### ISSUE TITLE
Scrolling lags on the antd docs website

### ISSUE THREAD

**Issue by csandanov** [ant-design/ant-design#20062]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce](https://ant.design/docs/react/introduce)

### Steps to reproduce
Visit the docs site https://ant.design/docs/react/introduce, open any article with a long body (e.g. https://ant.design/components/table), scroll up/down the body and left menu in-and-out by moving your cursor in the left menu zone and out with touchpad gestures (I use trackpad but I don't think that matters), at some point the position of your cursor on the left menu will be ignored and the scrolling with be applied only to the page. It's super annoying and leaves a negative impression about the UI framework (why should I use this UI framework if even their docs site has a buggy UI?) I personally like antd and just wanted to let you know.

In chrome console I see the following error:
```
scrollama error: step elements cannot be children of a scrollable element. Remove any css on the parent element with overflow: scroll; or overflow: auto; on elements with fixed height. <html lang=​"en" class=​"en-us gr__ant_design nprogress-busy" data-rh=​"lang">​<head>​…​</head>​<body data-gr-c-s-loaded=​"true">​…​</body>​</html>​
```

### What is expected?
The left menu should always be scrolled if a cursor positioned on it

### What is actually happening?
Sometimes the article body scrolled instead of the left menu although the cursor positioned on the left menu

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | - |
| System | - |
| Browser | Chrome 78.0.3904.108 (macOS 10.15.1) |

**Comment by shaodahong** [comment]
This is the browser default behavior, when sidebar scroll boundary is reached body will then start to scroll

Ref: [Google overscroll-behavior](https://developers.google.com/web/updates/2017/11/overscroll-behavior)

**Comment by csandanov** [comment]
@shaodahong Hi, please see this short screencast of the bug https://imgur.com/v88jv4V

**Comment by afc163** [comment]
It should be fixed in v4 docs.

**Comment by maksnester** [comment]
> It should be fixed in v4 docs.

nah, it's not. 

Just spotted it here https://ant.design/components/tree/

```
index-8fc86fc4.js:315 scrollama error: step elements cannot be children of a scrollable element. Remove any css on the parent element with overflow: scroll; or overflow: auto; on elements with fixed height. <body data-theme=​"default" data-new-gr-c-s-check-loaded=​"14.991.0" data-gr-ext-installed>​…​</body>​
v @ index-8fc86fc4.js:315

```
