### ISSUE TITLE
Icon position is incorrect when Input.Search with enterButton property uses hasFeedback to display validateStatus status

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#20061]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-jackson-3swlu)

### Steps to reproduce
N/A

### What is actually happening?
 

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/16101#issuecomment-485803143
