### ISSUE TITLE
Uncaught Error: A DOM element reference is required

### ISSUE THREAD

**Issue by leolee815** [ant-design/ant-design#2006]
使用antd select组件，加载显示没有什么问题，当点击select之后，就会报错：

Uncaught Error: A DOM element reference is required；有的时候还会报：

Uncaught TypeError: _reactDom2.default.unstable_renderSubtreeIntoContainer is not a function这个错

我安装antd就是在项目中install然后import到js中使用的

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by leolee815** [comment]
问题没办法在线上再现，这是我本地调试报错的信息
![image](https://cloud.githubusercontent.com/assets/4264036/15988615/166e2306-308a-11e6-874d-459f6698566d.png)

**Comment by afc163** [comment]
信息不足，无法定位。

**Comment by leolee815** [comment]
![image](https://cloud.githubusercontent.com/assets/4264036/15988840/da1c008c-3091-11e6-8fff-015486909415.png)
![image](https://cloud.githubusercontent.com/assets/4264036/15988845/f9b466dc-3091-11e6-9801-4a3e86614523.png)
上面是正常情况下el的值，下面是报错情况下el的值，感觉是没有取到输入框下面隐藏的div

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
无进一步反馈。

**Comment by sven0726** [comment]
我也出现了类似问题

**Comment by Geczy** [comment]
Same issue

**Comment by davidfurlong** [comment]
I'm still seeing this issue, not sure where though.

**Comment by jessicaleen** [comment]
Same issue

**Comment by LukerSpringtree** [comment]
Same issue

**Comment by Comeandcheck** [comment]
Same issue

**Comment by TianJianJun** [comment]
遇到类似情况

**Comment by Lee-shrk** [comment]
遇到同样情况

**Comment by indown** [comment]
Same issue

**Comment by zhihongzhong** [comment]
同样问题

**Comment by zhihongzhong** [comment]
定时器导致的， 组件在销毁的时候使用200ms 定时器调用了更新css类方法， 而200ms以后组件已经被销毁所以css类无法更新。

**Comment by ruiuii** [comment]
那请问应该怎么处理呢？


> 定时器导致的， 组件在销毁的时候使用200ms 定时器调用了更新css类方法， 而200ms以后组件已经被销毁所以css类无法更新。

**Comment by zhihongzhong** [comment]
> 那请问应该怎么处理呢？
> 
> > 定时器导致的， 组件在销毁的时候使用200ms 定时器调用了更新css类方法， 而200ms以后组件已经被销毁所以css类无法更新。

console.error = function() {} [狗头]

**Comment by Adaer** [comment]
@zhihongzhong @ruiuii  虽然这个问题过去很久了，但是今天我也遇到了，`A DOM element reference is required`
渲染form表单的时候使用了setTimeout 去更新<a-form-item>的值是没问题的，但是我同时使用了2种form，
<a-form-model>这种form就不能使用延时器，而是直接更新<a-form-model-item>的值就行，然后就不报错了

**Comment by OctopussyO** [comment]
same issue

**Comment by ruiuii** [comment]
我最后是这么解决的，提供一个思路，版本信息"ant-design-vue": "^1.7.6"
`<a-select
        :getPopupContainer="getContainer"
      >
        <a-select-option v-for="item in options" :key="item.value">{{ item.label }}</a-select-option>
      </a-select>
....
getContainer (triggerNode) {
  if (triggerNode) {
    return triggerNode.parentNode
  } else {
    return document.body
  }
}
`
