### ISSUE TITLE
Menu导航菜单

### ISSUE THREAD

**Issue by wenbinobject** [ant-design/ant-design#20072]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我希望可以修改选中 class="ant-menu-item ant-menu-item-selected" 时 可以在里面切换 伪类元素 before和after 目前只可以用after 不过我想用before

### What does the proposed API look like?
pseudoClass:默认after 我可以选择修改改为before

**Comment by wenbinobject** [comment]
或者告诉我 如果我想伪类元素用before 而不是after 我应该怎么做～～～ 谢谢

**Comment by afc163** [comment]
自定义样式进行覆盖 antd 的样式。
