### ISSUE TITLE
Popover can't use in Menu Component ?

### ISSUE THREAD

**Issue by gitHber** [ant-design/ant-design#20076]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-sry8bj](https://stackblitz.com/edit/react-sry8bj)

### Steps to reproduce
Hover Popover, Get an error that is "Cannot read property '1' of undefined"

### What is expected?
get a Popover Content

### What is actually happening?
 rc-align component Align props is empty object that have no point attribute

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
Try this way: https://stackblitz.com/edit/react-sry8bj-vk2blq?file=index.js
