### ISSUE TITLE
Scroll bottom component

### ISSUE THREAD

**Issue by justforuse** [ant-design/ant-design#20073]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For now, we have BackTop, I think ScrollBottom is also useful

### What does the proposed API look like?
Just like BackTop

**Comment by afc163** [comment]
Sorry, ScrollBottom is not a common component in backend application situation.
