### ISSUE TITLE
Provide a before-run hook for the table component.

### ISSUE THREAD

**Issue by fanzkday** [ant-design/ant-design#20074]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Background
Our project depth depends on antd design, in which the table component is used 600+ times.
Now we need to set the width property in the columns uniformly, and compute the value of table.props.scroll.x. So, we want to provide a hook for that.

### What problem does this feature solve?
Set the common configuration in Table component props uniformly.

### What does the proposed API look like?

```ts
// Table Component
class StoreTable<T> extends React.Component<TableProps<T>> {
  
  // ...

  static hooks: { before?: <K>(props: TableProps<K>) => TableProps<K> } = {};

  config: TableProps<T> = {};

  // ...

  render() {
    this.config = this.props;
    if (StoreTable.hooks.before) {
      this.config = StoreTable.hooks.before<T>(cloneDeep(this.props));
    }
    return (
      <Table<T>
        {...this.config}
        store={this.store}
        checkboxPropsCache={this.CheckboxPropsCache}
        setCheckboxPropsCache={this.setCheckboxPropsCache}
      />
    );
  }
}

```

```js
// usage
import { Table } from 'antd';

Table.hooks.before = (props) => {
  let x = 0;
  props.columns.forEach(column => {
    // column.width = 150 / 120 / 200
    x += column.width;
  });
  props.scroll.x = x;
  props.size = 'small';
  return props;
};

```

**Comment by afc163** [comment]
I don't think it is right method to use a React Component.

**Comment by fanzkday** [comment]
I've changed it so it's based on user input and doesn't break the react component design.
```js
// usage
import { Table } from 'antd';

Table.hooks.before = (props) => {
  // ...
 props.size =  props.size || 'small'; // It has been revised again
 // ...
};
```

**Comment by fanzkday** [comment]
I've changed it so it's based on user input and doesn't break the react component design.
To do so, the project team needs to agree in advance, but I don't think this is a problem.
This is the safest and most convenient for complex large projects.
```js
Table.hooks.before = (props) => {
  props.size = props.size || 'small'; // changed
  return props;
};
```

**Comment by afc163** [comment]
You should customize a new Table component based on antd's Table, and use it instead use antd Table directly.

**Comment by fanzkday** [comment]
Yes, we have.
We hope to get your support for the above plan. At present, we give up. Thank you very much.
