### ISSUE TITLE
Tree Drag & Drop support for mobile.

### ISSUE THREAD

**Issue by quangv** [ant-design/ant-design#20082]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently the "draggable" Tree component example doesn't work on mobile / mobile-safari. Is it suppose to?

Thank you.

https://ant.design/components/tree/ - "Draggable" example, not working on mobile.

### What does the proposed API look like?
API the same, or workaround will include an additional option.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15688#issuecomment-477065182

**Comment by quangv** [comment]
Thanks for first response!
