### ISSUE TITLE
modal关闭之后会自动回到页面顶部

### ISSUE THREAD

**Issue by Gamehu** [ant-design/ant-design#20081]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
1.打开官网的modal页就能重现。
2.打开最下面的modal，关闭会自动回到顶部

### What is expected?
当操作完改modal窗口后，关闭应该停留在该位置。

### What is actually happening?
关闭modal后，直接回到了顶部，影响用户操作。

| Environment | Info |
|---|---|
| antd | 3.9.4 |
| React | 16.3 |
| System | windows10 |
| Browser | 78.0.3904.97 |

---
因为业务代码很复杂不太好用sandbox重现，不过官网刚好也有这个效果，所以可以通过官网看效果。
设置了getContainer也不好使。

谢谢！

**Comment by afc163** [comment]
@shaodahong 看看是不是之前改挂了。

**Comment by shaodahong** [comment]
[Demo](https://codesandbox.io/s/serene-banzai-c5q34) 我试了是没有问题的，@Gamehu 这个可能是和什么组件组合使用导致的事件冲突，麻烦提供下其它使用的组件

**Comment by ycjcl868** [comment]
4.0 也有这个

**Comment by shaodahong** [comment]
我单独看了 rc-dialog 也是 ok 的

**Comment by shaodahong** [comment]
我怀疑是某个组件的 effect

**Comment by afc163** [comment]
官网是有问题的。

**Comment by Gamehu** [comment]
@shaodahong shaodahong

> [Demo](https://codesandbox.io/s/serene-banzai-c5q34) 我试了是没有问题的，@Gamehu 这个可能是和什么组件组合使用导致的事件冲突，麻烦提供下其它使用的组件


你好 ，是在TabPane里用一堆Card，点击某个Card弹出modal

**Comment by shaodahong** [comment]
@Gamehu 谢谢，看来是 `Card` 的 bug

**Comment by shaodahong** [comment]
53eee985f0e40d9c773eb38db5e2e708d68b5bcd 官网是这个 commit 导致的，@afc163 偏右帮忙看下

@Gamehu 你看下你的样式是不是也有这问题

**Comment by shaodahong** [comment]
而且现在还是会有错
![image](https://user-images.githubusercontent.com/14831261/70139145-ca379080-16cc-11ea-95b7-11c612858416.png)
