### ISSUE TITLE
antd 4.0 版本的table 如果rowSelection 中指定为fixed属性，会出现遮罩穿透现象

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#20098]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-zyky4)

### Steps to reproduce
打开链接，点击测试按钮，即可看到div的zIndex没有成功遮罩住 rowselection那部分的div

### What is expected?
希望zIndex成功遮罩住 rowselection那部分的div

### What is actually happening?
div的zIndex没有成功遮罩住 rowselection那部分的div

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.13 |
| React | 16.12.0 |
| System | win7 |
| Browser | Google Chrome 78.0.3904.70（正式版本） （64 位） |

---
实际业务需求，是需要打开一个新的div，遮罩住当前页面，所有需要用到zIndex，但是没法遮罩rowSelection 那部分，antd 3.26.0的版本是OK的

**Comment by zombieJ** [comment]
例子改掉了？

**Comment by Catsbe** [comment]
不好意思，我马上补上
