### ISSUE TITLE
Modal在一级弹窗显示ok,二级弹窗蒙层没有显示

### ISSUE THREAD

**Issue by Jessie-D** [ant-design/ant-design#2009]
打开一个弹窗正常，但是在弹窗中点击按钮生成新的弹窗，蒙层没有正常显示
![qq 20160612105626](https://cloud.githubusercontent.com/assets/10069496/15988690/8166774c-308c-11e6-9b89-0a514ca6bc37.jpg)

期待的结果是： 
多级弹窗正常显示    
![qq 20160612110015](https://cloud.githubusercontent.com/assets/10069496/15988707/e105df76-308c-11e6-92bc-894194c38fc6.png)

- antd 版本:1.1.0
- 操作系统及其版本：win7-64-pc
- 浏览器及其版本: Chrome

**Comment by yesmeck** [comment]
我这里把`@zindex-modal-mask`也设置成 1000 就 ok 了。

**Comment by afc163** [comment]
来个 PR ~

**Comment by Jessie-D** [comment]
是的，两个一样就好了

**Comment by yesmeck** [comment]
@Jessie-D 你来吧 😄

**Comment by afc163** [comment]
@Jessie-D 等你呦~

**Comment by Jessie-D** [comment]
master/components/style/themes/default.less中@zindex-modal;@zindex-modal-mask这两个值一样就好，但是我不知道会不会引起其他问题，就不pr了哈
<img width="488" alt="3cb92f4d-dd39-4f38-95a8-c04466152f57" src="https://cloud.githubusercontent.com/assets/10069496/15992089/1c8ba4da-30f7-11e6-8d9f-04f506542301.png">

**Comment by afc163** [comment]
没问题啊，PR 啊，这么好的贡献机会~

**Comment by afc163** [comment]
...没反馈啊。@Jessie-D

**Comment by afc163** [comment]
还得靠自己..

**Comment by revier** [comment]
我内嵌一段文字在modal里面，发现什么都没有。code就如下：
```
   <FormItem>
            <Modal visible={true} footer={null} onCancel={this.handleCancel.bind(this)}>
                <p>Bla bla ...</p>
              <p>Bla bla ...</p>
             </Modal>
      </FormItem>
```
改了下zindex也不行。
antd版本用的是1.4.1

效果就是一个蒙板什么都没有。

求指导。
谢谢

**Comment by yesmeck** [comment]
@revier 你这是另外的问题，新开个 issue，附个 demo 吧。
