### ISSUE TITLE
[4.0] Demo use react hooks

### ISSUE THREAD

**Issue by xiaohuoni** [ant-design/ant-design#20093]
# TodoList

## General
- [ ] Button  https://github.com/ant-design/ant-design/pull/20139
- [x] Icon  无需修改
- [ ] Typography https://github.com/ant-design/ant-design/pull/20218

## Layout

- [ ] Grid https://github.com/ant-design/ant-design/pull/20233
- [ ] Layout https://github.com/ant-design/ant-design/pull/20279

## Navigation

- [ ] Affix @orzyyyy https://github.com/ant-design/ant-design/pull/20124
- [x] Breadcrumb无需修改
- [ ] Dropdown https://github.com/ant-design/ant-design/pull/20348
- [ ] Menu
- [ ] Pagination
- [ ] PageHeader
- [ ] Steps

## Data Entry
- [ ] AutoComplete
- [ ] Checkbox
- [ ] Cascader
- [ ] DatePicker
- [ ] Form
- [ ] InputNumber
- [ ] Input
- [ ] Mentions
- [ ] Rate
- [ ] Radio
- [ ] Switch
- [ ] Slider
- [ ] Select
- [ ] TreeSelect
- [ ] Transfer
- [ ] TimePicker
- [ ] Upload

## Data Display

- [ ] Avatar
- [ ] Badge
- [ ] Comment
- [ ] Collapse
- [ ] Carousel
- [ ] Card
- [ ] Calendar
- [ ] Description List
- [ ] Empty
- [ ] List
- [ ] Popover
- [ ] Statistic
- [ ] Tree
- [ ] Tooltip
- [ ] Timeline
- [ ] Tag
- [ ] Tabs
- [ ] Table

## Feedback

- [ ] Alert
- [ ] Drawer
- [ ] Modal
- [ ] Message
- [ ] Notification
- [ ] Progress
- [ ] Popconfirm
- [ ] Result
- [ ] Spin
- [ ] Skeleton

## Other

- [ ] Anchor
- [ ] BackTop
- [ ] ConfigProvider
- [ ] Divider

## 规定
1、title 需要添加 `docs:  ` （注意冒号后面有一个空格）
2、ts代码 必须使用 '```tsx' 不能使用 '```jsx' 就算是不需要修改的 demo ，也要确认一下这一点
3、顺便有修改的全改成tsx

**Comment by orzyyyy** [comment]
What about refactor demo with typescript?
https://material-ui.com/components/selects/
![image](https://user-images.githubusercontent.com/24520193/70321246-cee17d80-1861-11ea-947a-5327c86f2bdc.png)

**Comment by afc163** [comment]
<img width="780" alt="图片" src="https://user-images.githubusercontent.com/507615/70323090-da837300-1866-11ea-81b8-d84817aa648f.png">

We can support TypeScript code now, hooks and ts could be updated at the same time.

**Comment by zombieJ** [comment]
Close since may cause conflict with merge master.
