### ISSUE TITLE
Dropdown will cover the text when menu is too many

### ISSUE THREAD

**Issue by n313893254** [ant-design/ant-design#20107]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dazzling-wiles-t9fh9?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Move the cursor to 'Cascading menu'

### What is expected?
The dropdown menu will show below the 'Cascading menu'.

### What is actually happening?
'Cascading menu' is covered, and the position is changed.

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | Mac |
| Browser | chrome |

**Comment by n313893254** [comment]
I also use `getPopupContainer` but it still covers the text.

**Comment by afc163** [comment]
https://codesandbox.io/s/winter-cdn-s4r8j

**Comment by afc163** [comment]
It is by designed, we show overlay as more as possible if there is no enough vertical space.

**Comment by n313893254** [comment]
Tank you, it solved my answer.
