### ISSUE TITLE
Table 表格 如何生成左侧是表头，右侧是数据，2列的table

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#2010]
Table 表格 如何生成左侧是表头，右侧是数据，2列多行的table

或者用表单的时候

`<Form horizontal>
            <FormItem
              {...DetailLayout}
              label="项目名称">
              <p className="ant-form-text">1{this.state.projectName.projectName}</p>
            </FormItem>
....
</FormItem>`

{this.state.projectName.projectName}  如何获取this.state数据

**Comment by afc163** [comment]
不知道你要表达什么，建议自行组织 dataSource 或尝试拼接组件。

**Comment by chounanzi** [comment]
@EagleWolf 请问你想要的这种效果实现了么？我现在也是想表头在左侧，不知道怎么做
