### ISSUE TITLE
Slider set custom color

### ISSUE THREAD

**Issue by rever96** [ant-design/ant-design#20108]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In the Slider APIs there isn't the color set property.
In my use case I can't use the same color as primary-color on the slider

### What does the proposed API look like?
```<Slider color='#fff'  ....... />```

**Comment by afc163** [comment]
There are `handleStyle` `trackStyle` and other style props you can try: https://github.com/react-component/slider/

**Comment by jwa5426** [comment]
@afc163 is this still valid in v4.3.5? I don’t see those available as props. 谢谢🙏

**Comment by xrkffgg** [comment]
You can use `@slider-handle-background-color` like 
- https://ant.design/docs/react/customize-theme#Ant-Design-Less-variables

**Comment by jwa5426** [comment]
That is helpful but it would be nice to be able to dynamically change the track color via props

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/eager-chatelet-7zcxw

**Comment by jwa5426** [comment]
Locally I am getting `Property 'trackStyle' does not exist on type 'IntrinsicAttributes & SliderProps & RefAttributes<unkown>'. TS2322`. Seems to be TypeScript related 🤔
