### ISSUE TITLE
[4.0] Checkbox value inside Form missing in onFinish

### ISSUE THREAD

**Issue by csandanov** [ant-design/ant-design#20106]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-wd7is)

### Steps to reproduce
- Create `<Form>` with a single `<Form.Item>` with a `<Checkbox />` inside
- Inside `onFinish`, `values` won't contain a checkbox value

### What is expected?
Checkbox value should be available inside onFinish

### What is actually happening?
Checkbox value is missing in onFinish values

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.13 |
| React | 16.12.0 |
| System | macOS |
| Browser | Chrome 78.0.3904.108  |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-djwhi
