### ISSUE TITLE
table同时设置了rowSelection以及onRowClick属性

### ISSUE THREAD

**Issue by babizhu** [ant-design/ant-design#2011]
## What you did

table组件，同时设置了rowSelection以及onRowClick属性

## What you would like to happen

点每一行的checkbox的时候并不会执行rowSelection指定的函数,如果这个函数是跳转到另外页面的话，这个情况就比较糟糕了

## What actually happened

实际上执行了rowSelection指定的函数

## Online demo

http://codepen.io/anon/pen/ezZmdP?editors=001

## Environment Information

- The version of antd(1.3.2):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

---

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/commit/5cc87ede0b5cbab480f5fd400b3ba67e9c2895c5

**Comment by afc163** [comment]
感觉你描述的逻辑上有问题，看不太懂。

确认下是否和 https://github.com/ant-design/ant-design/issues/1470 描述的一样吧。
