### ISSUE TITLE
4.0 Typography 在 Form 中的样式

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#20112]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-meninsky-2q29w)

### Steps to reproduce
1、文字偏上，加上 ant-form-text 可恢复正常。
2、点击编辑，文本框会覆盖到 label 后面的 : 。

### What is expected?
样式 OK

### What is actually happening?
样式不好。

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.12 |
| React | last |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
close via #20216
