### ISSUE TITLE
IE11 iframe中加载Button组件，然后销毁iframe时，会出现内存泄漏

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#20110]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://none.com 暂时没有，需要iframe环境](http://none.com 暂时没有，需要iframe环境)

### Steps to reproduce
IE11，在子iframe中加载antd Button组件，然后销毁子iframe，会出现内存泄漏，发现一部分内存没法被回收（且暂用内存较大）

### What is expected?
IE11，在子iframe中加载antd Button组件，然后销毁子iframe，不会出现内存泄漏，大部分内存能被回收

### What is actually happening?
会出现内存泄漏，发现一部分内存没法被回收（且暂用内存较大）

| Environment | Info |
|---|---|
| antd | 3.23.4 |
| React | 16.9.0 |
| System | mac |
| Browser | ie11 |

**Comment by wufeng87** [comment]
同样的环境，我把Button改成div，销毁完iframe就能回收掉大部分内存，实在没辙了，看是否有人遇到过类似的问题，给点指导，谢谢。

销毁iframe时用到的代码：
```
      const isIE11 = !!window.MSInputMethodContext && !!document.documentMode;
      if (!isIE11) {
          return;
      }
      var _i = document.getElementById('taskIframe');
      if (!_i) {
          return;
      }

      try {
          _i.src = 'about:blank';
          _i.contentWindow.document.write('');
          _i.contentWindow.document.clear && _i.contentWindow.document.clear();
          _i.contentWindow.close();
          _i.remove();
          console.log('done');
      } catch (e) {
          console.log('removeIframe error');
      }
      if (typeof window.CollectGarbage === 'function') {
          window.CollectGarbage();
      }
```

**Comment by PeachScript** [comment]
@wufeng87 (codepen)[https://codepen.io] 之类的 demo 平台的编辑模式是基于 iframe 的，使用 IE11 在上面能复现吗？

**Comment by wufeng87** [comment]
@PeachScript 他们网站不支持ie11。。。

**Comment by wufeng87** [comment]
SO 链接 https://stackoverflow.com/questions/59206323/ie11-iframe-memory-leak-with-reactjs-and-antd

**Comment by ztplz** [comment]
这跟antd没多大关系  ie11的老bug  ms那是won't fix的  button只是偶然触发了

**Comment by wufeng87** [comment]
@ztplz 是的。莫名的就触发了。

**Comment by ztplz** [comment]
stackoverflow 上搜索下处理ie11 上 ifrme 泄漏的问题吧 很多的  先关了  这不是组件库的问题 
ie的内存泄漏其实一直就有  以前大家浏览网页 网页也不复杂 看完就关了或者刷新了 问题没这么严重  现在都是spa 就在一个网页上跳来跳去  一堆事件绑定 面向对象和闭包

**Comment by wufeng87** [comment]
![image](https://user-images.githubusercontent.com/1686808/70710885-275dc280-1d1b-11ea-8d46-4cae2c89fa76.png)

@ztplz 真是有内存泄漏哦，写了个最简单的demo，mount、unMount 含有iframe的组件，ie11下内存不会得到释放。iframe src赋值的是 https://ant.design/components/button-cn/

**Comment by wufeng87** [comment]
![image](https://user-images.githubusercontent.com/1686808/70712505-e2d42600-1d1e-11ea-8068-a3d230b4db1d.png)
开2个cra服务，切换一个有一个Button的iframe，内存也会涨不少。切换20来下，能涨到快400M了。

```
import React from 'react'
import IframeContainer from './IframeContainer'
export default class IframeTest extends React.Component {
  state = {
      showIframe: false,
  };

  componentDidMount() {
  }
  switchIframe = () => {
      this.setState({ showIframe: !this.state.showIframe })
  }

  render() {
    const { showIframe }  = this.state;
    return (
      <React.Fragment>
            <button onClick={this.switchIframe}>switch iframe</button>
            { showIframe && <IframeContainer ></IframeContainer>}
      </React.Fragment>
    );
  }
}


// IframeContainer
import React from 'react'

export default class IframeContainer extends React.Component {
  state = {
  };

  componentDidMount() {
  }
  componentWillUnmount() {
      console.log('un')
  }

  render() {

    let host = 'http://192.168.64.68:3001/'
    host = 'https://ant.design/components/button-cn/'
    host = 'http://192.168.64.68:3000/'

    const iframeSrc = `${host}`
    return (
      <React.Fragment>
            
            { <iframe src={iframeSrc}></iframe>}
      </React.Fragment>
    );
  }
}

```

**Comment by wufeng87** [comment]
链接换成 vue element的： https://element.eleme.cn/#/zh-CN/component/button   也会有类似问题，只是影响小多了，当然，本身都是用开发服务测试的，也会有影响。

**Comment by ztplz** [comment]
@wufeng87   你也看到了  这不是个library special 的问题  组件库这边不好处理的

**Comment by wsz7777** [comment]
@wufeng87 给这个iframe加key呢？

**Comment by wsz7777** [comment]
现在是怎么解决的~？

**Comment by Rabbitzzc** [comment]
针对于 iframe，建议直接使用 iframe.remove() iframe.src='' 等方式手动在 unmouted 时清空
