### ISSUE TITLE
Fixed column group not aligned in no-bordered Table

### ISSUE THREAD

**Issue by LuThrash** [ant-design/ant-design#20126]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-morning-b6n9s)

### Steps to reproduce
- Group fixed columns
- The table must have no borders

### What is expected?
Fixed and scrollable columns both to be aligned

### What is actually happening?
Disrupting Fixed columns alignment (a bit higher)

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | latest |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
What is your expected result looks like?

**Comment by LuThrash** [comment]
@afc163 
Like this: https://codesandbox.io/s/dk4lv
Note that the fixed columns are aligned with the scrollable ones. But when I group them, it kind of mess the alignment

**Comment by afc163** [comment]
<img width="228" alt="图片" src="https://user-images.githubusercontent.com/507615/70451413-49b7cc00-1ae0-11ea-9e69-48fe98ccc01a.png">

Did you mean this column not aligned?

**Comment by LuThrash** [comment]
No, I mean right here:
![image](https://user-images.githubusercontent.com/8965805/70549172-87553d00-1b52-11ea-9ef1-bf6404b5872f.png)

**Comment by afc163** [comment]
Fixed in `rc-table@6.10.7`, reinstall node_modules and try it.
