### ISSUE TITLE
Select : no Event bubbling?

### ISSUE THREAD

**Issue by gregg-cbs** [ant-design/ant-design#20128]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-cfrtt)

### Steps to reproduce
Change select and inspect console

### What is expected?
It is expected that Ant Components would be in line with the javascript spec and scope. Not to disregard them as this makes it harder to integrate the components.

### What is actually happening?
No real event being passed on onchange, only ants value. Therefore I cannot use event bubbling techniques to leverage performance and clean code.

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | Latest |
| System | Mac Catalina |
| Browser | Chrome |

---
Ant design has some performance issues in my eyes. A lot of re-renders and draws for no reason. Please, you need to be considerate.

**Comment by susahin80** [comment]
Also why antd Select onChange does give only the value of selected item? Normal html select gives SynheticEvent.

**Comment by afc163** [comment]
antd's Select is not a portal of native select, we recommend to use https://ant.design/components/form
