### ISSUE TITLE
在Checkbox 里自定义了一个id属性，没有渲染出来。

### ISSUE THREAD

**Issue by xd199153** [ant-design/ant-design#2012]
问题：在Checkbox 里自定义了一个id属性，没有渲染出来。其它属性也没渲染出来。

代码
![4b11660a-9b6d-4ba6-932f-ad1c8f56f367](https://cloud.githubusercontent.com/assets/4395188/15989165/2e66b18c-30a1-11e6-998d-3087e97354f5.png)

渲染结果
![be36eea9-e7f5-466d-8024-047248eddbcb](https://cloud.githubusercontent.com/assets/4395188/15989166/2e67372e-30a1-11e6-8264-b36863cb2bbf.png)

**Comment by afc163** [comment]
https://github.com/react-component/checkbox/pull/14 

去这里提 PR ，一个个加吧。https://github.com/react-component/checkbox/pull/15
