### ISSUE TITLE
Cascader In List  删除非最后一个时，显示删除了最后一个Cascader 

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#20134]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-pike-92uut)

### Steps to reproduce
顺序选择不同的级联值，删除List中的第二个，但是显示最后一个没有了。

### What is expected?
删除List中的第二个，能够正确渲染

### What is actually happening?
删除List中的第二个，但是显示最后一个没有了。

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.8 |
| System | Windows 10 |
| Browser | QQ浏览器10.4.2 |

---
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { List, Cascader, Icon } from "antd";
const data = [
  "Racing car sprays burning fuel into crowd.",
  "Japanese princess to wed commoner.",
  "Australian walks 100km after outback crash.",
  "Man charged over missing wedding girl.",
  "Los Angeles battles huge wildfires."
];
const options = [
  {
    children: [
      {
        value: "hangzhou",
        label: "Hanzhou",
        children: [
          {
            value: "xihu",
            label: "West Lake"
          }
        ]
      }
    ],
    value: "其他文档",
    label: "其他文档"
  },
  {
    value: "官方来文",
    label: "官方来文",
    children: [
      {
        value: "通知书",
        label: "通知书",
        children: [
          {
            value: "缴费通知书",
            label: "缴费通知书"
          }
        ]
      },
      {
        value: "回执",
        label: "回执"
      }
    ]
  }
];
class Demo extends React.Component {
  state = {
    data: [
      "Racing car sprays burning fuel into crowd.",
      "Japanese princess to wed commoner.",
      "Australian walks 100km after outback crash.",
      "Man charged over missing wedding girl.",
      "Los Angeles battles huge wildfires."
    ]
  };

  onCascaderChange(value, index) {
    console.log(value, index);
  }
  onRemove = (e, index) => {
    this.state.data.splice(index, 1);

    this.setState({
      data: [...this.state.data],
      autoExpandParent: false
    });
    console.log(data, index);
  };
  render() {
    return (
      <div>
        <List
          header={<div>Header</div>}
          footer={<div>Footer</div>}
          bordered
          dataSource={this.state.data}
          renderItem={(item, index) => (
            <List.Item
              actions={[
                <Icon
                  type="delete"
                  onClick={() => this.onRemove(item, index)}
                />
              ]}
            >
              <Cascader
                key={"Cascader"   index}
                style={{ width: "40%", marginRight: 10 }}
                fieldNames={{
                  label: "label",
                  value: "value",
                  children: "children"
                }}
                placeholder="请选择文件类型"
                options={options}
                onChange={value => this.onCascaderChange(value, index)}
                changeOnSelect
              />
              <List.Item.Meta description={item} />
            </List.Item>
          )}
        />
      </div>
    );
  }
}

ReactDOM.render(<Demo />, document.getElementById("container"));

**Comment by afc163** [comment]
Missing rowKey: https://codesandbox.io/s/proud-leftpad-hso7d
