### ISSUE TITLE
Collapse another table row then click expand row

### ISSUE THREAD

**Issue by yotewach** [ant-design/ant-design#20132]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When use the nested table expand I want to collapse all row is not current expanding including children

### What does the proposed API look like?

` <Table columns={columns}
                    dataSource={this.state.invoiceData}
                    onExpand={(expanded, record) => this.tableExpandHandler(expanded, record)}
                    expandedRowRender={(props) => this.expandDetail(props)}
                    expandedRowKeys={this.state.expandedRows}
                    awayExpandOneRow="true" 
                    size="default"
                />`

**Comment by afc163** [comment]
Try control it by `expandedRowKeys`
