### ISSUE TITLE
Table columns render 触发问题

### ISSUE THREAD

**Issue by America-first-melon** [ant-design/ant-design#20141]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/adoring-wright-tlen5)

### Steps to reproduce

Table columns 没有设置 fixed的时候， render函数只触发一次。

Table columns 的某一项设置 fixed 之后， render 函数会一直触发。（鼠标hover行也会触发）

### What is expected?
Table columns 的某一项设置 fixed 之后， render 函数只触发一次

### What is actually happening?
Table columns 的某一项设置 fixed 之后， render 函数会一直触发。

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | window 7 |
| Browser | chrome |

**Comment by afc163** [comment]
这是符合预期的，目前的实现方式会是这个效果。

**Comment by afantyLius** [comment]
数据发生改变触发 render 可以理解，鼠标移入移出触发 render 是为什么呀？ @afc163
