### ISSUE TITLE
Switch 控件的默认值问题

### ISSUE THREAD

**Issue by pigletfly** [ant-design/ant-design#2015]
Switch 控件之前的默认值是false，现在是undefined。是否可以保持一致？
官方demo里面可以复现。

**Comment by benjycui** [comment]
之前是哪个版本？

**Comment by pigletfly** [comment]
之前是0.12，现在是最新的1.3

**Comment by afc163** [comment]
能否描述的具体一点，我没有太明白，可以的话提供一个演示是最好了。

**Comment by benjycui** [comment]
看了之前的代码并没有设置 `checked` 的 `defaultProps` 哎。。

**Comment by pigletfly** [comment]
示例：http://codepen.io/anon/pen/Pzzobg?editors=0010
1.刚打开时，提交表单，switch 的值是 ```undefined```
2.选中switch,值是 ```true```
3.取消选中，值是```false```，和初始时未选中的值不一样
之前的版本，刚加载时和取消选中时值都是 ```false```

**Comment by afc163** [comment]
感觉之前的版本（麻烦给出是哪个版本）是有问题的，初始值在没有设定的情况下，如何知道是 `false`？undefined 反而是合理的。

建议用 Form 里的 initialValue 指定初始值。

**Comment by pigletfly** [comment]
之前版本是0.12
