### ISSUE TITLE
Whether input.search onSearch is triggered when allowClear is true should be determined by configuration

### ISSUE THREAD

**Issue by lihuanji** [ant-design/ant-design#20168]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[#18729](https://github.com/ant-design/ant-design/issues/18729)
Just want to clear the entered data and don't want to trigger a search.

### What does the proposed API look like?
```
<Input.Search
   allowClear
   clearTriggerSearch
/>
```

**Comment by afc163** [comment]
You can add your code in `onChange` to diff those two behaviors.

**Comment by jsoncode** [comment]
I solved this problem like this:

```
onSearch = (value, event) => {
    if (event.nativeEvent.type === 'click' && value === '') {
        // listen click
        setTimeout(() => {
            // TODO
        }, 300);
    }

    
    if (event.nativeEvent.type === 'enter' && value === '') {
        // Enter
        setTimeout(() => {
            // TODO
        }, 300);
    }


    if (value === '') {
        return;
    }

    // search
};
```

**Comment by LuoJimmy** [comment]
> You can add your code in `onChange` to diff those two behaviors.
<Input.Search
    placeholder="input code"
    allowClear
    style={{ width: 216, marginRight: 8 }}
    onSearch={(value: string) => {
        setTimeout(() => {
            if(!isInputSearchChanged) {
                setKeywords(value.trim());
                handleSearch();
            }
        }, 100);
    }}
    onChange={(e: any) => {
        isInputSearchChanged = true;
        setKeywords(e.target.value.trim());
        setTimeout(() => {
            isInputSearchChanged = false;
        }, 200)
    }}
    value={keywords}
/>

But I think it's more elegant!

```
<Input.Search
   allowClear
   clearTriggerSearch
/>
```

**Comment by LuoJimmy** [comment]
> > You can add your code in `onChange` to diff those two behaviors.
> 
> ```
> <Input.Search
>     placeholder="input code"
>     allowClear
>     style={{ width: 216, marginRight: 8 }}
>     onSearch={(value: string) => {
>         setTimeout(() => {
>             if(!isInputSearchChanged) {
>                 handleSearch();
>             }
>         }, 100);
>     }}
>     onChange={(e: any) => {
>         isInputSearchChanged = true;
>         setKeywords(e.target.value.trim());
>         setTimeout(() => {
>             isInputSearchChanged = false;
>         }, 200)
>     }}
>     value={keywords}
> />
> ```
> 
> But I think it's more elegant!
> 
> ```
> <Input.Search
>    allowClear
>    clearTriggerSearch
> />
> ```

another way in antd@4.7.3
```
<Input.Search
    placeholder="input code"
    allowClear
    style={{ width: 216, marginRight: 8 }}
    onSearch={(value: string, event: any) => {
        if (!event?.__proto__?.type) {
              // filter clear trigger
              handleSearch();
          }
    }}
    onChange={(e: any) => {
        setKeywords(e.target.value.trim());
    }}
    value={keywords}
/>
```

**Comment by chindathorn** [comment]
It's really more elegant! Please add this API property to diff those two behaviors.
`<Input.Search
   allowClear
   clearTriggerSearch
/>`

**Comment by saiponethaaung** [comment]
@LuoJimmy thank you very very much.
