### ISSUE TITLE
react-dom.development.js:4525 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.  Check the render method of `Context.Consumer`.

### ISSUE THREAD

**Issue by zhenliliu** [ant-design/ant-design#20163]
我是按照官网的按需加载进行配置的，使用一些组件的时候比如List，如果dataSource是空的话，就会报这个错误
这个是babel.config.js

![image](https://user-images.githubusercontent.com/19882458/70494644-05134b80-1b47-11ea-96e4-2bbe5e1dbeaf.png)
这个是引入
![image](https://user-images.githubusercontent.com/19882458/70494657-14929480-1b47-11ea-83db-b83862b54710.png)

这个是报错
![image](https://user-images.githubusercontent.com/19882458/70494667-2411dd80-1b47-11ea-8294-8622d06f3401.png)
这个问题应该怎么解决啊，搜索了全网没有查到解决方案

**Comment by codermango** [comment]
Same here

**Comment by Aysnine** [comment]
Same here
