### ISSUE TITLE
使用react-loadabel 或者loadable-component进行代码分割时，List组件和Table组件如果数据源是空数组时，会报错导致页面崩溃，而不是显示无数据

### ISSUE THREAD

**Issue by zhenliliu** [ant-design/ant-design#20173]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
使用react-loadable或者loadable-component进行代码分割后，其他组件都是OK的，List和table组件数据源如果是空数组时，会报错，如果loading为true没有问题，会一直显示loading，如果loading为false且数据源如果是空数组时，会报错导致页面崩溃

### What is expected?
正确渲染

### What is actually happening?
页面崩溃

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | MacOS 10.13.6 |
| Browser | Chrome  78.0.3904.108 |

**Comment by fwtcumt** [comment]
我就用的是react-loadable，兵没有这个问题呀🤔

**Comment by yoyo837** [comment]
我也没有
