### ISSUE TITLE
Drawer, switchScrollingEffect prop on DOM element

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#20175]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-leavitt-55dvg)

### Steps to reproduce
open browser console and press Open button to open drawer

### What is expected?
Not forwarding react prop to DOM element

### What is actually happening?
Console shows error warning: React does not recognize the `switchScrollingEffect` prop on a DOM element.

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16 |
| System | windows |
| Browser | any |

---
DrawerChild component forwards switchScrollingEffect prop from PortalWrapper to div element.

**Comment by shaodahong** [comment]
Will fixes by https://github.com/react-component/drawer/pull/120

**Comment by Lind-pro** [comment]
@zombieJ 这个BUG什么时候可以解决呢？

**Comment by gaoruyi** [comment]
在线催

**Comment by yoyo837** [comment]
`rc-drawer@3.1.0` released.

**Comment by Lind-pro** [comment]
> `rc-drawer@3.1.0` released.

升级了rc-drawer版本为3.1.0还是有这个错误。。
把```import { Drawer } from "antd";``` 替换成 ```import Drawer from 'rc-drawer';```好像也不少错误。

**Comment by yoyo837** [comment]
`antd` 升依赖.

**Comment by shaodahong** [comment]
Wait for me fix this, now `rc-drawer` not upgraded in `antd`

**Comment by Lind-pro** [comment]
> Waiting for me fix this, now `rc-drawer` not upgraded in `antd`

好吧。等你升级

**Comment by SiegeSailor** [comment]
The warning message is still popping up on the console with version `4.10.2`.

```
Warning: React does not recognize the `switchScrollingEffect` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `switchscrollingeffect` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

**Comment by yoyo837** [comment]
> The warning message is still popping up on the console with version `4.10.2`.
> 
> ```
> Warning: React does not recognize the `switchScrollingEffect` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `switchscrollingeffect` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
> ```

Cloud you open a new issue for that?

**Comment by yoyo837** [comment]
trace in #28818

**Comment by hdwong** [comment]
同样的问题

使用 `getContainer` 返回指定 DOMElement 时，会提示

> Warning: React does not recognize the switchScrollingEffect prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase switchscrollingeffect instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**Comment by YangJ0605** [comment]
Warning: React does not recognize the `scrollLocker` prop on a DOM element.

**Comment by pirate-x** [comment]
> Warning: React does not recognize the `scrollLocker` prop on a DOM element.

just remove yarn.lock, and run yarn install again
