### ISSUE TITLE
4.0 Form support top level config

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#20174]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Support:
* disabled
* ~readOnly~
* size

### What does the proposed API look like?
```tsx
<Form size="large" readOnly disabled>
  <Form.Item>
    ...
  </Form.Item>
</Form>
```

**Comment by afc163** [comment]
`readOnly` cannot be supported to all antd form controls, it could be removed.
