### ISSUE TITLE
Tabs - Popconfirm when close tab and disable keyboard arrow

### ISSUE THREAD

**Issue by tnduc** [ant-design/ant-design#20180]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs/](https://ant.design/components/tabs/)

### Steps to reproduce
https://codesandbox.io/s/happy-thompson-sji3d

### What is expected?
- Show warnings when closing tabs, like Popupconfirm.

- Disable tab moving with the arrow keys.

### What is actually happening?
- Tab close button easily mistakenly lost unwanted data, can add a warning when closing the tab? I'm warning in the remove () function, it's better to use Popupconfirm.

- using tabBarExtraContent with the input field, Use arrow keys, moved to the characters in the input box, instead moving the tab.
step 1: Enter data into the input
step 2: Move between characters, using the keyboard's arrow keys
result: Don't move between characters, instead move tabs

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | ^16.8.6 |
| System | Ubuntu 18.04 |
| Browser | Chrome latest |

**Comment by tranducit95** [comment]
@afc163 updated issue.

**Comment by HuyAms** [comment]
We can listen to the 'remove' action (check the onEdit props) then show a confirm modal.
https://ant.design/components/modal/#components-modal-demo-confirm

**Comment by HuyAms** [comment]
> @afc163 updated issue 11 days ago.

We can listen to the 'remove' action (check the onEdit props) then show a confirm modal. 
https://ant.design/components/modal/#components-modal-demo-confirm

**Comment by leftstick** [comment]
`Popconfirm` when close the tab is great, may I ask is there any update on it?
