### ISSUE TITLE
使用table组件的scroll属性，当数据量少时候，也会出现纵向的滚动条。

### ISSUE THREAD

**Issue by liuhaoliang** [ant-design/ant-design#20188]
antd的table组件在数据少的时候怎么隐藏右边的滚动条，类似overflow：autoi这个效果。这个是demo，https://codesandbox.io/s/admiring-meadow-v5eki?fontsize=14&hidenavigation=1&theme=dark

**Comment by liuhaoliang** [comment]
上一个issue被关闭了，说是和#12088 重复，我检查了是不同的两个问题，希望这个问题不要沉下去被关闭

**Comment by afc163** [comment]
可以到 #12088 里补充回复，在我们看来是同一大类的问题，scroll.y 目前是固定的 `max-height` 和 `overflow-y: scroll`，还做不到自适应和或者固定高度或者设置 min-height，需要后面整体做方案去解决。

**Comment by liuhaoliang** [comment]
我的意思是，为什么不设置成overflow-y: auto？

**Comment by afc163** [comment]
`overflow-y: auto` 会有列对齐问题的。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2328
