### ISSUE TITLE
在AutoComplete的dataSource中不支持select的options的value属性为number和其他类型的参数

### ISSUE THREAD

**Issue by oldturkey** [ant-design/ant-design#20186]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-chaum-qsybt?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
option的value值是number类型的时候，react报错

### What is expected?
支持number类型

### What is actually happening?
只支持string类型

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.12 |
| System | mac |
| Browser | chorme |

**Comment by zombieJ** [comment]
AutoComplete 是一个支持下拉的 Input，只支持 string 类型。

ref: https://github.com/ant-design/ant-design/blob/1bf0bab2a7bc0a774119f501806e3e0e3a6ba283/components/auto-complete/index.tsx#L11

**Comment by oldturkey** [comment]
上面代码的例子是官方文档里的例子，AutoComplete的datasource里面塞了直接塞了Option，而从源码也可以看到Option的来源是rc-select，报错信息看到的也是所依赖的rc-select里面的util.js的校验报的错误，我记得现在的select组件是支持 option的value值为nuber/string的,是否可以对AutoComplete支持到。
