### ISSUE TITLE
Without importing @import '~antd/dist/antd.less' theme customisation not work

### ISSUE THREAD

**Issue by helabenkhalfallah** [ant-design/ant-design#20189]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/helabenkhalfallah/atomify/blob/master/src/styles/theme.less#L1](https://github.com/helabenkhalfallah/atomify/blob/master/src/styles/theme.less#L1)

### Steps to reproduce
I created a library on top of antd.
I want to customise the lib with my custom style, but customisation not work if I don't import ~antd/dist/antd.less.
This will disable babel plugin import and I will hava a huge bundle without modular import.

Lib link :
https://github.com/helabenkhalfallah/atomify/blob/master/src/styles/theme.less#L1

Project using this lib :
https://github.com/helabenkhalfallah/react-sortable-grid-pages/blob/master/src/index.js#L4
https://github.com/helabenkhalfallah/react-sortable-grid-pages/blob/master/.babelrc

On the project importing the lib I got a huge bundle form theme.less which import ant less.

### What is expected?
Modular theme import or theme customisation work without import ~antd/dist/antd.less.

### What is actually happening?
We must import ~antd/dist/antd.less which result on a non modular css import.

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.12.0 |
| System | All |
| Browser | All |

**Comment by zombieJ** [comment]
You can just import component less file you want. For example: https://unpkg.com/browse/antd@3.26.2/es/button/style/index.less
