### ISSUE TITLE
TreeSelect 下拉树控件是否能点击父节点才去异步加载子节点

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2019]
不知道loadData这个属性是不是就是要的，但是官网没有提供该属性的用法我也不确定是不是

**Comment by afc163** [comment]
需要的，可以参考：http://react-component.github.io/tree-select/examples/dynamic.html

**Comment by afc163** [comment]
需要的，可以参考：http://react-component.github.io/tree-select/examples/dynamic.html

**Comment by aw6658913** [comment]
getNewTreeData, generateTreeNodes 这两个是什么模块？怎么我搜索自己的模块中没有这两个

**Comment by aw6658913** [comment]
import这两个模块就报错了

**Comment by afc163** [comment]
https://github.com/react-component/tree-select/blob/master/examples/util.js

**Comment by aw6658913** [comment]
搞了一个上午经过修改终于搞定了，感谢支持

**Comment by wangYaNan112618** [comment]
请问异步加载的时候，第一次展开的时候要点两次才能将新的子元素渲染出来，但是组件treedata属性已经被改变了，是怎么回事

**Comment by wo-de-ping-er** [comment]
> 搞了一个上午经过修改终于搞定了，感谢支持

请问一下  你是怎么修改的？   我这边修改出现了很多问题。
