### ISSUE TITLE
Table组件（设置了 scroll [x]）在数据为空的状态时，是否可以将横向滚动条的位置从表头顶部转移到表格底部（于有数据时的位置一致）？

### ISSUE THREAD

**Issue by Uni-sako** [ant-design/ant-design#20197]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在一个实际项目中，用户对表格（column比较多，使用了scroll）在空数据和有数据时，**横向滚动条所处位置** 不一致提出了优化需求！
虽然个人从外部做了一些调整，但尚不能很好地处理这个体验性的需求。

如下图，表格**有数据**时：
![has data table](https://img2018.cnblogs.com/common/1532752/201912/1532752-20191211180943331-1151013828.jpg)

表格**空数据**时：
![no data table](https://img2018.cnblogs.com/common/1532752/201912/1532752-20191211180927835-839295400.jpg)

### What does the proposed API look like?
是否可以在以后的版本中提供一个方案来解决 **Table** 组件使用 _scroll(x)_ 时空数据和有数据状态下 _横向滚动条位置_ 不一致的情况🤔

```javascript
// example

<Table 
    scroll={{ x: 1600 }}
    hideXScrollWhenEmpty
/>

// or

<Table 
    scroll={{ x: 1600 }}
    xScrollPlacement="tableBottom"
/>

```

另外目前Table中的滚动条是浏览器自带的，这样的话，在不同浏览器下，Table中的滚动条就会出现不同的样式效果，用户体验不好！
谢谢 🤠

**Comment by afc163** [comment]
Duplicate of #10490

**Comment by Uni-sako** [comment]
3Q
