### ISSUE TITLE
Form设置this.state.value给子组件的initialValue后, 子组件内部管理数据不会更新state?

### ISSUE THREAD

**Issue by travonf** [ant-design/ant-design#20199]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-initialvalue-issue-fyd2r)

### Steps to reproduce
点击加号更新输入框的值, 表单中确实是更新了, 但是state并未更新

### What is expected?
最佳实践

### What is actually happening?
提交时是表单值, state未变化.

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.8.4 |
| System | Windows10 |
| Browser | Chrome 78.0.3904.108 |

---
我想知道这样写有没有什么问题?
Form包裹自定义组件后, 将this.state.value设置为initialValue, 
自定义组件内部管理通过this.props.onChange修改this.props.value, 
如果想同步更新this.state.value是否需要处理onChange事件?
但是官网文档上说"你不再需要也不应该用 onChange 来做同步，但还是可以继续监听 onChange 等事件。", 没太理解.

https://next.ant.design/components/form/v3-cn/#%E5%88%9D%E5%A7%8B%E5%8C%96%E8%B0%83%E6%95%B4
在 v3 版本中，修改未操作的字段 initialValue 会同步更新字段值，这是一个 BUG。但是由于被长期作为一个 feature 使用，因而我们一直没有修复。在 v4 中，该 BUG 已被修复。initialValue 只有在初始化以及重置表单时生效。
还有这句话不太理解是什么意思, 有人能具体解释一下吗?

**Comment by travonf** [comment]
![image](https://user-images.githubusercontent.com/18564432/70618350-89e88d00-1c4d-11ea-9e20-54c3a042842e.png)

**Comment by travonf** [comment]
仔细想想不自动更新state应该是正常的 = =!

**Comment by afc163** [comment]
initialValues 和 defaultValue 一样，只有第一次 render 才生效。

**Comment by travonf** [comment]
> initialValues 和 defaultValue 一样，只有第一次 render 才生效。

这句话太官方了，好几个地方都是这句话，但是例子里赋值给initialValue能更新是因为bug？

**Comment by yoyo837** [comment]
一定产生了销毁后重新渲染

**Comment by afc163** [comment]
最佳实践是用 setFieldValue 或者 mapPropsToFields 去控制表单的值。

**Comment by yoyo837** [comment]
> > initialValues 和 defaultValue 一样，只有第一次 render 才生效。
> 
> 这句话太官方了，好几个地方都是这句话，但是例子里赋值给initialValue能更新是因为bug？
> 如果需要更新value只能用setFieldValue？最佳实践是什么？

一定产生了销毁后重新渲染
