### ISSUE TITLE
Tree 组件 showLine 的同时 Tree 用了 icon 导致图标重叠

### ISSUE THREAD

**Issue by bammoo** [ant-design/ant-design#20192]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-wilbur-lwsuf)

### Steps to reproduce
直接看得到

### What is expected?
不重叠

### What is actually happening?
重叠了

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.8.6 |
| System | macos 10.14 |
| Browser | chrome 78 |

**Comment by afc163** [comment]
没看出什么问题。

**Comment by bammoo** [comment]
我另外建了个 3.25.2 版本的： https://codesandbox.io/s/upbeat-snow-4oty6  我需要的就是 + 号和 TreeNode 的 icon 同时存在。

**Comment by afc163** [comment]
是根据 https://github.com/ant-design/ant-design/issues/20090 的反馈这里做的修改，我再考虑一下。

**Comment by baizn** [comment]
> https://codesandbox.io/s/upbeat-snow-4oty6

有些需要的是只有一个，TreeNode 如果设置了 icon，那就只显示设置的一个。
![image](https://user-images.githubusercontent.com/9443867/70876075-354d6500-1ff3-11ea-9f79-8971ed1a4225.png)
应该使用红色的icon替换框起来的。

**Comment by afc163** [comment]
用 switcherIcon，不应该用 icon。

**Comment by baizn** [comment]
> 用 switcherIcon，不应该用 icon。

两种都需要，switcherIcon 是用到 Tree 组件上的，定义的是父级前面的图标，icon 是用到 TreeNode 组件上的，定义的是叶子节点前面的图标。

![image](https://user-images.githubusercontent.com/9443867/70877087-fb7e5d80-1ff6-11ea-9bf3-1cbe8c8d4d94.png)

像上面这个，使用 switcherIcon 定义了实心三角的Icon， 叶子节点中不需要这个，需要的使用红色的icon替换实心三角。
