### ISSUE TITLE
reset form won't work on having trigger:"onBlur" and valuePropName: "defaultValue"

### ISSUE THREAD

**Issue by bidva** [ant-design/ant-design#20203]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-chatterjee-jrn6q?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
after adding an Input field with trigger:"onBlur" and valuePropName: "defaultValue" reset field not flushing the state of input
here is 2 sample codes which reproduces the error   
https://codesandbox.io/s/bold-chatterjee-jrn6q?fontsize=14&hidenavigation=1&theme=dark
you can see this other one as well
https://codesandbox.io/s/crazy-water-5j383?fontsize=14&hidenavigation=1&theme=dark

### What is expected?
all fields get clear after triggering reset form 

### What is actually happening?
the input value remains 

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.9.0 |
| System | mac 10.14.6 (18G1012) |
| Browser | 78.0.3904.108 (Official Build) (64-bit) |

---
I needed to use trigger:"onBlur" and valuePropName: "defaultValue"
now when I want to reset the form the state of the input does not get flush and still keep the last state

**Comment by afc163** [comment]
trigger should not be `onBlur` in any situation, neither valuePropName should not be `defaultValue`.

**Comment by bidva** [comment]
@afc163 so what can I do when I want get changes onblur? I don't want to get changes being triggered by onChange . because system gonna be too chatty to backend. what is the solution for that?

**Comment by afc163** [comment]
You can't, you can validate field on blur only: https://codesandbox.io/s/flamboyant-tdd-8ft3n

**Comment by thangtran2307** [comment]
Hi @afc163, is there any solution for this issue now?

Btw when I try to use this component: https://www.npmjs.com/package/react-number-format as the input inside FormItem. I can set the trigger="onBlur" and valuePropName: "value" to get the changes onBlur as well as using setFieldValue function.

But when I applied this with the Input component then I was facing the same problem that mentioned above.
