### ISSUE TITLE
验证的时候，如何在进行ajax验证前，先自动进行客户端的规则验证

### ISSUE THREAD

**Issue by himyspace** [ant-design/ant-design#2020]
If you want to ask a question, please read [some tips](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question) first :-)

If you are going to report a bug, please answer the following questions, thank you!

## What you did

(e.g. I ate a hamburger)

## What you would like to happen

(e.g. I should be full)

## What actually happened

(e.g. But I am still hungry now T_T)

## Online demo

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## Environment Information

- The version of antd(e.g. 0.12.0):
- Your operating system and it's version(e.g. OSX 10.11.0):
- Your browser and it's version(e.g. Chrome 48.0.0.0(64-bit)):

---

提问之前，建议先阅读[这份提示](https://github.com/ant-design/ant-design/blob/master/.github/CONTRIBUTING.md#do-your-homework-before-asking-a-question)。:-)

如果是报告 bug，请按照下列格式编辑问题，务必提供复现步骤，否则恕难解决，非常感谢！

## 你做了什么？

（例如，我吃了一个汉堡）

## 你期待的结果是：

（例如，我应该饱了）

## 实际上的结果和抱怨：

（例如，我还是饿的，肯定是哪里出问题了）

## 可重现的在线演示

(e.g. http://codepen.io/anon/pen/wGOWGW?editors=001)

## 本地环境信息

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by himyspace** [comment]
userExists(rule, value, callback) {
    if (!value) {
      callback();
    } else {
      const { validateFields } = this.props.form;
      console.log(rule);
      // 这里如何自动验证规则后，再进行下一步ajax操作
      $.post(window.didi.nameUrl,{"_token": window.didi.token, 'name': value})
        .done(function(data){
          if(data.success){
            var a = callback();
            console.log(a);
          } else {
            callback([new Error(data.errors.name[0])]);
          }
      });
        
    }
  },    

const nameProps = getFieldProps('name', {
      rules: [
        { required: true, min: 6, message: '用户名至少6位' },
        { validator: this.userExists },
      ],
    });           

 <FormItem className={style.myFormItem} style={style2} key="ae"
              {...formItemLayout}
              hasFeedback>
              <Input {...nameProps}  placeholder="输入用户名" />
            </FormItem>

**Comment by bang88** [comment]
没看懂你要说什么。。

**Comment by benjycui** [comment]
```js
      // 这里如何自动验证规则后，再进行下一步ajax操作
      // 验证代码直接写这里就好，建议认真学习 JavaScript event loop 
      $.post(window.didi.nameUrl,{"_token": window.didi.token, 'name': value})
        .done(function(data){
          if(data.success){
            var a = callback();
            console.log(a);
          } else {
            callback([new Error(data.errors.name[0])]);
          }
      });
```

**Comment by benjycui** [comment]
希望我没有理解错你的问题 😅

**Comment by himyspace** [comment]
```
rules: [
        { required: true, min: 6, message: '用户名至少6位' },
        { validator: this.userExists },
      ],
```

我的意思是：rules 里的设置的规则，有没有办法在ajax 验证前先操作

**Comment by himyspace** [comment]
现在我发现，比如长度至少位6， 那么我要在post之前，写上：

```
if(value.length < 6) {
   callback();
}
```

有没有什么方法，先对rules设置的规则先进行检验，而不需要我重新写上面的代码

**Comment by benjycui** [comment]
ping @yiminghe

**Comment by yiminghe** [comment]
validateFirst

**Comment by yiminghe** [comment]
提醒：以后这种 提 issue 内容直接关掉了，内容要有意义，有 demo

**Comment by himyspace** [comment]
感谢大神的提醒，是提问的逻辑不好， 现在重新梳理一下：
**我做的东西**
```
直接上代码
const { DatePicker } = antd;

const { Button, Form, Input } = antd;
const createForm = Form.create;
const FormItem = Form.Item;

function noop() {
  return false;
}

let BasicDemo = React.createClass({
  handleReset(e) {
    e.preventDefault();
    this.props.form.resetFields();
  },

  handleSubmit(e) {
    e.preventDefault();
    this.props.form.validateFields((errors, values) => {
      if (!!errors) {
        console.log('Errors in form!!!');
        return;
      }
      console.log('Submit!!!');
      console.log(values);
    });
  },

  userExists(rule, value, callback) {
    if (!value) {
      callback();
    } else {
      $.post("http://testajax.com", function(){
        callback();
      });
     
      
    }
  },


  render() {
    const { getFieldProps, getFieldError, isFieldValidating } = this.props.form;
    const nameProps = getFieldProps('name', {
      rules: [
        { required: true, min: 5, message: '用户名至少为 5 个字符' },
        { validator: this.userExists },
      ],
    });
    
    const formItemLayout = {
      labelCol: { span: 7 },
      wrapperCol: { span: 12 },
    };
    return (
      <Form horizontal form={this.props.form}>
        <FormItem
          {...formItemLayout}
          label="用户名"
          hasFeedback
          help={isFieldValidating('name') ? '校验中...' : (getFieldError('name') || []).join(', ')}
        >
          <Input {...nameProps} placeholder="实时校验" />
        </FormItem>

        

        <FormItem wrapperCol={{ span: 12, offset: 7 }}>
          <Button type="primary" onClick={this.handleSubmit}>确定</Button>
          &nbsp;&nbsp;&nbsp;
          <Button type="ghost" onClick={this.handleReset}>重置</Button>
        </FormItem>
      </Form>
    );
  },
});

BasicDemo = createForm()(BasicDemo);

ReactDOM.render(<BasicDemo />, document.getElementById("container"));
```


**我期待的结果**
先对name字段做必填与长度校验，当符合后在进行服务端的远程校验

**实际情况**
对name字段做必填与长度校验，不符合的情况向服务端远程校验，所以现在我需要增加代码:
```
 userExists(rule, value, callback) {
    if (!value) {
      callback();
    } else {
     // 增加的代码
     if(value.length < 5){
          callback();
          return;
      }
      $.post("http://testajax.com", function(){
        callback();
      });
    }
  },
```
**可重现的在线演示**
http://codepen.io/himyspace/pen/LZNJJE?editors=0010

**Comment by yiminghe** [comment]
```
 const nameProps = getFieldProps('name', {
      validateFirst: true,
      rules: [
        { required: true, min: 5, message: '用户名至少为 5 个字符' },
        { validator: this.userExists },
      ],
    });
```

**Comment by himyspace** [comment]
非常感谢
