### ISSUE TITLE
两个关于Modal和警告提示的痒点小bug

### ISSUE THREAD

**Issue by fwtcumt** [ant-design/ant-design#20209]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
小bug1： 不给Modal组件设置title，关闭按钮“X”会把内容压住；
小bug2：因为react从React 17.x开始废弃 componentWillMount 和 componentWillReceiveProps ，但是antd现在的一些组件还在用，导致控制台很多警告信息。可以不改，但是看着有些难受😣

### What is expected?
小bug1： 不给Modal组件设置title，关闭按钮“X”不会把内容压住；
小bug2：没有 componentWillMount 和 componentWillReceiveProps 的警告信息

### What is actually happening?
小bug1： 不给Modal组件设置title，关闭按钮“X”会把内容压住；
小bug2：有 componentWillMount 和 componentWillReceiveProps 的警告信息

### 提供两张图吧
问题一
<img width="873" alt="WX20191212-115218@2x" src="https://user-images.githubusercontent.com/21078500/70681997-5c94f100-1cd8-11ea-8794-bcb59f16a851.png">
问题二
<img width="843" alt="WX20191212-115432@2x" src="https://user-images.githubusercontent.com/21078500/70682009-661e5900-1cd8-11ea-9059-d5aadfc57ebf.png">

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.11.0 |
| System | mac、windows |
| Browser | 谷歌 78.0.3904.108 |

**Comment by zombieJ** [comment]
1. Modal 无标题时，关闭按钮会复用内容区域。别于铺满的情况，该设计普适于大部分场景。可以通过 `closable` 取消按钮展示。当然，欢迎有更好的设计建议。
2. 底层的 Animate 已经更新过了，清除一下 `node_modules` 和 `package-lock` 重新安装一下试试。
