### ISSUE TITLE
Blanks out entire page when I get this error

### ISSUE THREAD

**Issue by Garwin4j** [ant-design/ant-design#20202]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://loage](https://loage)

### Steps to reproduce
Click on a combo box when the value is not a valid value. 

### What is expected?
To continue to show the screen

### What is actually happening?
The entire react application goes blank. 

util.js:176 Uncaught Error: Invalid `value` of type `object` supplied to Option, expected `string` when `tags/combobox` is `true`.
    at util.js:176
    at Select.js:1158
    at D (react.production.min.js:234)
    at e (react.production.min.js:212)
    at H (react.production.min.js:226)
    at Object.forEach (react.production.min.js:271)
    at t.n.renderFilterOptionsFromChildren (Select.js:1112)
    at t.n.renderFilterOptions (Select.js:1051)
    at t.value (Select.js:1510)
    at Ea (react-dom.production.min.js:3785)
(anonymous) @ util.js:176
(anonymous) @ Select.js:1158
D @ react.production.min.js:234
e @ react.production.min.js:212
H @ react.production.min.js:226
forEach @ react.production.min.js:271
n.renderFilterOptionsFromChildren @ Select.js:1112
n.renderFilterOptions @ Select.js:1051
value @ Select.js:1510
Ea @ react-dom.production.min.js:3785
Pa @ react-dom.production.min.js:3776
Na @ react-dom.production.min.js:3960
qi @ react-dom.production.min.js:5514
Gi @ react-dom.production.min.js:5536
Vc @ react-dom.production.min.js:5958
Tc @ react-dom.production.min.js:5925
Ac @ react-dom.production.min.js:6020
kn @ react-dom.production.min.js:1737
o @ build.umd.js:2805

| Environment | Info |
|---|---|
| antd | 3.18.1 |
| React | 16 |
| System | Window 10 |
| Browser | Chrome |

**Comment by keithort** [comment]
You are passing an invalid type to Option. This isn't a framework issue.

**Comment by Garwin4j** [comment]
While that is true, the real issue is that this causes the entire
application to blank out. It happened a few times.

**Comment by keithort** [comment]
Syntax errors will always cause your app to crash when the browser tries to execute that code.
