### ISSUE TITLE
Layout.Sider trigger has incorrect position for padded menus

### ISSUE THREAD

**Issue by chrisui** [ant-design/ant-design#20200]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antdesign-hmus5?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Look at the sider trigger button. 

### What is expected?
Sider trigger button should be within the layout container

### What is actually happening?
Sider trigger button is at bottom of the screen (outside of the padded content)

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16 |
| System | OSX, Windows, Linux, any... |
| Browser | Chrome, Firefox, Edge, any... |

---
We have a nested content with a sider which is not flush against the bottom edge of the screen.

`position: absolute` or `position: sticky` should be a better alternative to `position: fixed` for the trigger styles as it would allow for controlled parent layout relativity.

**Comment by Kermit-Xuan** [comment]
@afc163 我打算把`position`改为`absolute`,但是会有这样一个问题，原来是`fixed`，所以当内容高度很高时，折叠按钮始终通常都会在页面最底部，用户可以直接看到使用，现在改为`absolute`后，相对于父元素定位，当内容高度很高时，折叠按钮会在内容的最底部，用户在首屏看不见。

**Comment by afc163** [comment]
It is by designed, sider trigger which fixed in bottom of screen is used for fixed layout appliaction.
