### ISSUE TITLE
4.0 Table - Editable Cells not working (even in demo links)

### ISSUE THREAD

**Issue by CusthomeDev** [ant-design/ant-design#20201]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/37ssl)

### Steps to reproduce
Use the demo code of Table - Editable Cells and see the console throwing an error about "Cannot read property 'render' of undefined" in EditableRow

### What is expected?
It is expected that Editable Cells works, and also in the demo link for Editable Cells in Table documentation

### What is actually happening?
It crash and throw errors

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.14 |
| React | 16.12.0 (latest) |
| System | macOS 10.15.2 |
| Browser | Chrome Version 78.0.3904.108 |

**Comment by zombieJ** [comment]
Caused by codesandbox using v3 as antd deps. Need update site create reproduce logic: https://codesandbox.io/s/vibrant-platform-22pdl

**Comment by CusthomeDev** [comment]
Hi,

Codesandbox works now with next version of antd.

But I was still a problem with EditableCell component when it is insert in a CRA project.
This component crash the app when it is called = TypeError: Cannot read property 'render' of undefined.
The error itself means nothing about the problem. After digging hours on it, it appears that it's a Ref forwarding problem when passed in `<td>` of EditableCell component.
In fact, the ref is not forwarding in the `<td>` element that result at the application crash.

So, to resolve this ref problem I have to force forwarding ref in EditableCell component.
See the fix below for people with can encounter this problem too.

In your example (and demo) EditableCell component looks like this :
`const EditableCell = ({
  title,
  editable,
  children,
  dataIndex,
  record,
  handleSave,
  ...restProps
}) => { ... same code as in example ... })`

After patch, EditableCell looks like this :
`const EditableCell = React.forwardRef (
  (
    { title, editable, children, dataIndex, record, handleSave, ...restProps },
    ref,
  ) => { ... same code as in example ... })`

Now every things works as expected.

**Comment by zombieJ** [comment]
@CusthomeDev, could you provide the crash example?

**Comment by CusthomeDev** [comment]
Hi,

I have made a repo with the crash example.
[View crash example](https://github.com/CusthomeDev/editable-table-crash)

**Comment by zombieJ** [comment]
https://codesandbox.io/s/flamboyant-blackburn-ffljc

What's the crash reproduce step?

**Comment by CusthomeDev** [comment]
You can't reproduce the crash in codesandbox. That's why I made a public GitHub repo that you can download.
Because it's a Create-React-App project with an App.js which call a component with exactly the same code as in your example for Editable Cell (or your sandbox).

Once you download project, just `yarn install && yarn start`.

**Comment by zombieJ** [comment]
Thanks for feedback. Fixed.
