### ISSUE TITLE
Antd 4.0.0 <DatePicker /> uses setFieldsValue update error in <Form />

### ISSUE THREAD

**Issue by SolidZORO** [ant-design/ant-design#20206]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-400-datepicker-uses-setfieldsvalue-update-error-in-form-efrp9)

### Steps to reproduce
```typescript
export const DatePickerUpdateTest = () => {
  const initTime = '2077-07-07 07:07:07';

  const [form] = Form.useForm();

  useEffect(() => {
    form.setFieldsValue({ time: moment(initTime) });
  }, [form]);

  return (
    <div style={{ padding: 20 }}>
      <Form form={form} name="infoForm" layout="vertical">
        <Form.Item name="time" rules={[]} label="TIME">
          <DatePicker showTime />
        </Form.Item>
      </Form>

      <Button type="primary" onClick={() => form.setFields([{ name: 'time', value: moment() }])}>
        Success Update
      </Button>

      <Button
        danger
        style={{ marginLeft: 10 }}
        // TODO console get some error
        // Uncaught TypeError: val.isValid is not a function
        // The above error occurred in the <PickerWrapper> component:
        onClick={() => form.setFieldsValue({ time: moment() })}
      >
        Fail Update
      </Button>
    </div>
  );
};

```

more code: https://codesandbox.io/s/antd-400-datepicker-uses-setfieldsvalue-update-error-in-form-efrp9

### What is expected?
setFieldsValue can correctly verify moment() or Date.

### What is actually happening?
setFieldsValue check for moment() or Date error. but setFields succeeds. why?

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.14 |
| React | 16.12.0 |
| System | macOS 10.15.1 (19B88) |
| Browser | Chrome 78.0.3904.108 |

**Comment by wpbjiuy** [comment]
##我也遇到了同样的问题，请问解决了吗？
`refForm.current?.setFieldsValue({ ...slcData.current, birthday: '2020-01-22' })`
### Error:
`moment.js:105 Uncaught TypeError: date.clone is not a function
    at Object.format (moment.js:105)`

**Comment by yoyo837** [comment]
birthday 给 moment实例

**Comment by manjoine** [comment]
Same error here with form.lists can not get it to render with initialValues at all

https://codepen.io/ergomesh/pen/ZEywWyW?editors=0110

**Comment by ergomesh** [comment]
https://codepen.io/ergomesh/pen/ZEywWyW?editors=0110

Same here can not get any initialValues to load correctly and it breaks the whole page I have tried moment date and string representations. This particular example is in a form.list but it also happens outside of it.

**Comment by robertusAdrian** [comment]
anyone get solve about this issue ? I get same issue error 
Version 4.19.5

**Comment by ppulwey** [comment]
If you cast your Date object into moment object first, this error disappears.

**Comment by Hassanjankhan** [comment]
@ppulwey please provide and example

**Comment by QiuYeDx** [comment]
今天我也出现了这个报错，然后发现，在set之前，用dayjs库给入参（元数据）的日期时间字符串包裹一下生成dayjs的日期对象就没有那个报错了，just like this: 

```ts
value: dayjs(eventInfo.date)
```

**Comment by Raza9798** [comment]
import dayJs first `import dayjs from 'dayjs';`

set value like 
```
 const productsWithMomentDates = data.items.map(item => ({
    ...item,
     expiry_date: item.expiry_date ? dayjs(item.expiry_date, "YYYY-MM-DD") : null, // instead of moment use dayjs
  }));
```
