### ISSUE TITLE
[4.0] button text not align center

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#20210]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/button-cn/](https://next.ant.design/components/button-cn/)

### Steps to reproduce
x

### What is expected?
文字垂直方向没有居中

### What is actually happening?
文字垂直方向居中

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | x |
| System | win10 |
| Browser | chrome 79 |

---
相同问题https://github.com/ant-design/ant-design/issues/20058 ，4.0版本需要同步一下样式

**Comment by zombieJ** [comment]
Hmmm... still cause of `line-height`:

### 21px

<img width="189" alt="截屏2019-12-12下午4 13 45" src="https://user-images.githubusercontent.com/5378891/70694370-67607d80-1cfa-11ea-81f3-add9e3db038f.png">


### 22px

<img width="191" alt="截屏2019-12-12下午4 13 11" src="https://user-images.githubusercontent.com/5378891/70694345-5adc2500-1cfa-11ea-9ab4-dd8d36e1d0ef.png">

**Comment by shaodahong** [comment]
Closed by #20300
