### ISSUE TITLE
[4.0] Selection no longer works when selectedRowKeys provided in Table

### ISSUE THREAD

**Issue by csandanov** [ant-design/ant-design#20214]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

*I saw a few similar issues but they were more complex and weren't 4.0*

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vbtx6?fontsize=14&hidenavigation=1)

### Steps to reproduce
Create a table with `rowSelection` and at least two records with one of them enabled via `selectedRowKeys` option

### What is expected?
Despite having one record selected by default you should be able to select an additional record or select all

### What is actually happening?
No records can be selected anymore

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | 16.12.0 |
| System | macOS |
| Browser | Version 78.0.3904.108 (Official Build) (64-bit) |

---
It would be great to be able to control which records are always selected, so even if you select All and unselect the provided records should remain selected

**Comment by zombieJ** [comment]
Control mode should aways be the single source of truth by `selectedRowKeys`.  It's same in v3:

https://codesandbox.io/s/antd-reproduction-template-m3c2i

Please feel free to comment if I misunderstand the issue.

**Comment by csandanov** [comment]
@zombieJ  do you mean this is the by-design behavior? If `selectedRowKeys` specified then the UI won't work? Is it implied that I should set `selectedRowKeys` from a state that will be manually changed in the `onChange` callback?

**Comment by zombieJ** [comment]
Yes. [controlled components](https://reactjs.org/docs/forms.html#controlled-components) always follow single source of truth. But it's welcomed to PR for additional `defaultSelectedRowKeys` prop for this requirement.
