### ISSUE TITLE
Table原来从ref中获取的state消失

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#20217]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-d5bcx)

### Steps to reproduce
console中table无state

### What is expected?
原来是有state的，自定义一些搜索取分页排序等非常方便

### What is actually happening?
console中table无state

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by fred8617** [comment]
https://codesandbox.io/s/antd-reproduction-template-fnuov
大概看了下，3.22版本中还有

**Comment by afc163** [comment]
不应该这么用，这个不是 React 组件正确的使用方式。
