### ISSUE TITLE
Ant Design Select component had minor issue!

### ISSUE THREAD

**Issue by caocuong2404** [ant-design/ant-design#20225]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/billowing-dew-kknte)

### Steps to reproduce
Check it...

![image](https://user-images.githubusercontent.com/50004497/70728425-f63dbc00-1d33-11ea-8a0d-8a6733131da9.png)

### What is expected?
Fix it :D

### What is actually happening?
Minor issue for ux when using packages

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | latest |
| System | linux |
| Browser | chrome |

**Comment by keithort** [comment]
You need to set a width through CSS on the Select component.

**Comment by afc163** [comment]
https://codesandbox.io/s/boring-bhaskara-itsvz
