### ISSUE TITLE
Upload组件是否允许在beforeUpload事件中异步修改data字段的值

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#2022]
## 场景
beforeUpload事件可以通过return Promise实现该事件内部的异步逻辑
![image](https://cloud.githubusercontent.com/assets/17123400/15995346/6f2777b4-314c-11e6-9668-19baa2dab8cf.png)
图中将待上传的图片转换为base64编码，将待提交的参数合并到file对象中，希望在data中可以获取，
但data并不会等待beforeUpload中异步逻辑完成后再执行

## 问题
是否我的配置项编写有问题 
或是否有另外的解决办法

## 版本
antd@1.3.2

**Comment by hhhyaaon** [comment]
麻烦告知以上对于upload的修改何时release？

**Comment by superRaytin** [comment]
@hhhyaaon 重新 install 即可。

**Comment by hhhyaaon** [comment]
@superRaytin 看到了，多谢 ！
