### ISSUE TITLE
Input component freezes when inputting Chinese characters in safari browser

### ISSUE THREAD

**Issue by MarxZhou** [ant-design/ant-design#20228]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/form/advanced-form](https://preview.pro.ant.design/form/advanced-form)

### Steps to reproduce
Enter the page and type Chinese characters directly in the input box to freeze.

### What is expected?
Able to input Chinese characters normally in the current environment

### What is actually happening?
Severe freeze or even crash when typing Chinese characters

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.8.6 |
| System | 10.14.6 |
| Browser | 13.0.4 |

---
I see someone saying the reason is that the overflow property of .ant-table is set to hidden. But my component does not include the Table component at all

**Comment by afc163** [comment]
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/507615/70765308-5749ac00-1d95-11ea-8c85-bec1ce4d1ca6.png">

It works fine in my safari.

**Comment by MarxZhou** [comment]
> <img alt="image" width="1769" src="https://user-images.githubusercontent.com/507615/70765308-5749ac00-1d95-11ea-8c85-bec1ce4d1ca6.png">
> 
> It works fine in my safari.

I just tested it with other Apple devices and found that everything is normal. I am currently locating the cause of this stuttering phenomenon.
Do you have any suggestions on this?

**Comment by MarxZhou** [comment]
I don't know why my test code in the sandbox is accessible using my colleague's Apple device. But in the project of antd pro, the input box will be severely stuck.
Currently I can't provide an online demo program other than the demo program of antd pro.
This problem is just an example for me. Other colleagues' Apple devices are able to enter content normally

**Comment by vanjoechang** [comment]
On MacOS 10.14, in Safari antd input freezes when typing Chinese. MacOS 10.13 is OK.
Older antd version is OK.

**Comment by MarxZhou** [comment]
> On MacOS 10.14, in Safari antd input freezes when typing Chinese. MacOS 10.13 is OK.
> Older antd version is OK.
I don't know much about safari browser at the moment. I have given this information back to testers. Can this function be controlled by code?

**Comment by vanjoechang** [comment]
> > On MacOS 10.14, in Safari antd input freezes when typing Chinese. MacOS 10.13 is OK.
> > Older antd version is OK.
> > I don't know much about safari browser at the moment. I have given this information back to testers. Can this function be controlled by code?

I don't know and I met same issue on my side. But only found you raised it and it had been closed ...
I am sure I still have this issue with latest antd.

**Comment by MarxZhou** [comment]
> > > On MacOS 10.14, in Safari antd input freezes when typing Chinese. MacOS 10.13 is OK.
> > > Older antd version is OK.
> > > I don't know much about safari browser at the moment. I have given this information back to testers. Can this function be controlled by code?
> 
> I don't know and I met same issue on my side. But only found you raised it and it had been closed ...
> I am sure I still have this issue with latest antd.

I haven't solved this problem so far, I have given up temporarily

**Comment by vanjoechang** [comment]
> > > > On MacOS 10.14, in Safari antd input freezes when typing Chinese. MacOS 10.13 is OK.
> > > > Older antd version is OK.
> > > > I don't know much about safari browser at the moment. I have given this information back to testers. Can this function be controlled by code?
> > 
> > 
> > I don't know and I met same issue on my side. But only found you raised it and it had been closed ...
> > I am sure I still have this issue with latest antd.
> 
> I haven't solved this problem so far, I have given up temporarily

Would you please reopen this issue? or i will create a new one?
