### ISSUE TITLE
Select. Hide Already Selected

### ISSUE THREAD

**Issue by cyberspacedk** [ant-design/ant-design#20240]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nameless-cdn-9sj4x?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Chose option in select option
Option should be removed from options and selected option should shown as Select value

### What is expected?

The task is to filter options by removing them from the options array and showing chosen `content `value as `Select value`. 

The selected option should:
- disappear from the options array
- displayed as select value

### What is actually happening?
There is an array containing objects with a simple structure `{value: 1, content: 'text'}`
In this example with this structure `{value: 1, content: 'text'}`, only the `value` field is displayed, and the `field` not displayed

| Environment | Info |
|---|---|
| antd | 3.20.7 |
| React | 16.9.0 |
| System | Ubuntu 19.04 |
| Browser | Chrome 77 |

---
There is a similar example in the library (example : "Hide Already Selected"), but it works exclusively with an array of simple structure like `['text-1', 'text-2', 'text-3']`

**Comment by afc163** [comment]
You can try `labelInValue` to store label in selected values.

https://codesandbox.io/s/ant-select-filtering-mqmj1
