### ISSUE TITLE
pc

### ISSUE THREAD

**Issue by genggengqianduan** [ant-design/ant-design#20241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
打开upload，选择一张长度很长的图片，在保存这张图片并且再次进去查看的时候，图片溢出

### What is expected?
图片正常显示，居中，不溢出

### What is actually happening?
打开upload，选择一张长度很长的图片，在保存这张图片并且再次进去查看的时候，图片溢出

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | upload组件上传图片过长，回显的时候图片溢出 |
| System | win10 |
| Browser | 谷歌 |

**Comment by yoyo837** [comment]
用的哪张图片 放上来。
