### ISSUE TITLE
functional code writing not fully supported compared to class?

### ISSUE THREAD

**Issue by MariuzM** [ant-design/ant-design#20247]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-lichterman-o0dpr)

### Steps to reproduce
Pressing the <> keys will remove all data from the boxes with functional code, but with Class based like your example all working fine. 

### What is expected?
After clicking either <> keys data should be present as it does with Class based code. 

### What is actually happening?
Data being removed after clicking <> keys 

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.12 |
| System | Mac Mojave |
| Browser | Brave/Chrome |

**Comment by keithort** [comment]
Your `setState` function is deleting `state.mockData`. Modifying the `handleChange` function gives the desired behavior.
`const handleChange = targetKeys => setState({ targetKeys, mockData: state.mockData });`

A better option would be to not have the `mockData` in `state` but as it's own variable.
