### ISSUE TITLE
Can Popconfirm add `confirmLoading` API like Model ?

### ISSUE THREAD

**Issue by glitchboyl** [ant-design/ant-design#20249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to submit request by using Popconfirm, and it will gives me a loading status.

### What does the proposed API look like?
```jsx
<Popconfirm
  title="Are you sure?"
  onConfirm={(e, api) => {
    api.loading();
    setTimeout(() => {
        message.success('Success!');
        api.close();
    });
  }}
>
  <a>Confirm</a>
</Popconfirm>
```

**Comment by afc163** [comment]
You can try controlled mode by `visible` and `onVisibleChange`.

**Comment by glitchboyl** [comment]
@afc163 no, i want a loading status, like this:

![1576313998_1_.jpg](https://i.loli.net/2019/12/14/pqftAL1DMTnIgRc.png)

if the image is not loaded, pls checkout this link: https://i.loli.net/2019/12/14/pqftAL1DMTnIgRc.png

**Comment by forrest-keller** [comment]
Why was this closed? I want this feature too.

**Comment by hengkx** [comment]
Is supported https://codesandbox.io/s/tiaojianhongfa-ant-design-demo-gfv8y?file=/index.js

I'll add a `confirmLoading` property like `Modal`

**Comment by hengkx** [comment]
@afc163 need add `confirmLoading` ?

**Comment by afc163** [comment]
LGTM

**Comment by hengkx** [comment]
changed doc.

**Comment by glitchboyl** [comment]
@hengkx where is the docs ? pls post link in here, thks~

**Comment by afc163** [comment]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/507615/81152871-f1b0c300-8fb4-11ea-8193-990ea7ab9f9a.png">

**Comment by yoyo837** [comment]
Not published yet

**Comment by hengkx** [comment]
@glitchboyl  https://ant.design/components/popconfirm/#API

![image](https://user-images.githubusercontent.com/8358236/81154236-4c96ea00-8fb6-11ea-8ea3-4dcd8685ab29.png)

**Comment by glitchboyl** [comment]
@hengkx it s still cant working. what version will be released? [demo](https://codesandbox.io/s/jiben-ant-design-demo-w2pqw?file=/index.js)

**Comment by hengkx** [comment]
see https://ant.design/components/modal/#components-modal-demo-async

**Comment by glitchboyl** [comment]
i still cant figure it out how to use it, pls update the docs and demo. :pray:

**Comment by forrest-keller** [comment]
The problem is that it impossible to control the visibility of the component like you can with a modal. There needs to be the attributes `visible` and `onCancel` like there is with the modal. Because this is internally controlled, it immediately closes.

**Comment by hengkx** [comment]
demo: https://codesandbox.io/s/asynchronously-close-ant-design-demo-forked-43x90?file=/index.js
