### ISSUE TITLE
Table组件不再支持columnsPageRange，columnsPageSize ？ 

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2025]
我更新到1.4后，原来使用columnsPageRange columnsPageSize的，现在样式不对了
表格内容只占了一半，另一半是空白

![qq 20160613142316](https://cloud.githubusercontent.com/assets/2271825/15998672/bf9644fc-3172-11e6-842f-fec29c9a7e41.png)

**Comment by afc163** [comment]
1.0 之后，加入了横向滚动和列固定功能，用于取代原来的 columnsPageRange columnsPageSize 功能。（两者解决的问题是一致的）

并没有移出这两个属性，但是样式可以会误伤，我来看看。

另外建议使用固定列进行重构。

**Comment by codering** [comment]
我个人觉得 columnsPageRange 比 横向滚动条好看。
换成横向滚动后，发现固定列设置了宽度，如果内容超过宽度，会出现覆盖滚动列的情况。
不过话说回来，感觉table对大量数据的展示是有限的， 还是得借助 tooltip类的提示，才能让结构的相对稳定些。。。

**Comment by afc163** [comment]
视觉上会好看些，但是用起来麻烦多了。我们的设计师也是纠结之后才做出这个改动的。
