### ISSUE TITLE
Input.TextArea won't auto-scroll past the maxRows

### ISSUE THREAD

**Issue by DenysVuika** [ant-design/ant-design#20257]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ydpxh)

### Steps to reproduce
Start typing multiple lines, use Enter to jump to new line. Create new lines until reaching the maxRows threshold.

### What is expected?
Users should see what they are typing

### What is actually happening?
The text area is always showing the first lines, users won't see the text they are typing without manually scrolling the text area.

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.12.0 |
| System | macOS |
| Browser | Firefox 71 |

**Comment by Kermit-Xuan** [comment]
I try it in reproduction link, it's normal.
Maybe the latest version have been fixed.
@afc163

**Comment by afc163** [comment]
Fixed in #22014
