### ISSUE TITLE
Row Col 疑问 当Row为flex时候style设置为wrap，Col有显示疑问

### ISSUE THREAD

**Issue by hebehan** [ant-design/ant-design#20256]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-cerf-vqpbb)

### Steps to reproduce
上面链接打开后，拖动右面的窗口宽度，不加span可以自动换行，加了就不能自动换行了

### What is expected?
加了span仍然可以自动换行，不知道是bug还是前端机制

### What is actually happening?
实际结果是Col不加span可以自动换行，加了span不能自动换行

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 15.6.2 |
| System | mac 10.14.6 |
| Browser | Chrome 79 |

**Comment by afc163** [comment]
这是对的，`span={8}` 相当于 `width: 33.3%`，三个 Col 凑一行，空间够了自然不会换行。

**Comment by dxh141130** [comment]
如果在一个row里面有n个col(n >3)，每个col的span是8， 那么档浏览器宽度更改的时候，col就无法实现自动换行。 有同样的问题
