### ISSUE TITLE
Invalid colspan value in Description List for vertical layout

### ISSUE THREAD

**Issue by pwolaq** [ant-design/ant-design#20255]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hvb3q (example of vertical layout from docs))

### Steps to reproduce
Inspect `colspan` attribute on elements that visually span over multiple columns.

### What is expected?
For *Status* element - `colspan="3"`
For *Usage time* element - `colspan="2"`

### What is actually happening?
For *Status* element - `colspan="5"`
For *Usage time* element - `colspan="3"`

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.12.0 |
| System | Mac OS Catalina |
| Browser | Chrome 79 |

---
Due to this bug it is impossible to create layouts like this:
```
[  ][  ][  ][  ]  // 4x single column
[      ][      ]  // 2x double column
```
In second row, the `colspan` attributes would be `colspan="3"` and `colspan="3"`, thus resulting in:
```
[  ][  ][  ][  ]
[          ][  ]
```

**Comment by zombieJ** [comment]
Use `column` prop of `Descriptions` to the column count.

**Comment by pwolaq** [comment]
@zombieJ  - https://codesandbox.io/s/romantic-ptolemy-4dopr
column set to 4, 
4 single columns in first row
2 * 2 columns in second row
behaviour as I described in the first post

I have read the code prior to writing this issue and I'm telling you the math is wrong, you can clearly see it on other example, including those from the docs, that `colspan` attribute is calculated incorrectly.

**Comment by zombieJ** [comment]
Thanks for notice again. It's a bug of refacto.
ref https://github.com/ant-design/ant-design/pull/17560

**Comment by zombieJ** [comment]
Reopen for  v3

**Comment by afc163** [comment]
Closing for 3.x no longer been maintained.
