### ISSUE TITLE
Animate uses componentWillReceiveProps and receives error

### ISSUE THREAD

**Issue by ppedrazzi** [ant-design/ant-design#20262]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
N/A

### Steps to reproduce
Use animate in form.

### What is expected?
No error should happen when using Animate.

### What is actually happening?
Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Animate, Form(WrappedComponent)

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | Latest |
| System | Mac |
| Browser | Chrome |

**Comment by gungorbudak** [comment]
Here is the online reproduction:

https://codesandbox.io/s/antd-reproduction-template-hrz09?file=/index.js

To reproduce, click "Open" and see the second console log.

Thanks

**Comment by rahulthewall** [comment]
I have the same issue, can we please reopen this bug?

**Comment by yoyo837** [comment]
ref: #22493

**Comment by yoyo837** [comment]
It's StrictMode warning.

**Comment by JiaweiTan** [comment]
Hi, I have the same issue too. What's the solution to it?

**Comment by gungorbudak** [comment]
> Hi, I have the same issue too. What's the solution to it?

@JiaweiTan Just get rid of these guys:

```javascript
ReactDOM.render(
  <React.StrictMode> // <-- remove this
    <App />
  </React.StrictMode>,  // <-- remove this too
  document.getElementById("root")
);
```

**Comment by langarus** [comment]
@gungorbudak you should be in strict mode when developing.

**Comment by gungorbudak** [comment]
@langarus I'm 100% with you, it is a cool feature to detect issues during development but unfortunately antd does not support it. :(

**Comment by langarus** [comment]
@gungorbudak it's more like antd is using an unsafe lifecycle method

**Comment by SyedAsimAliSE** [comment]
stumbled upon this too.

![image](https://user-images.githubusercontent.com/44644354/99670516-7b783780-2a92-11eb-9e17-1382ba696620.png)
