### ISSUE TITLE
You are using prebuilt antd, please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#2026]
You are using prebuilt antd,
please use https://github.com/ant-design/babel-plugin-antd to reduce app bundle size.

引用的方式哪里不对 我下载了 /babel-plugin-antd  也用的
import {Form, Input, Button, Checkbox, Row, Col} from 'antd';

但是还是出这个警告！

**Comment by afc163** [comment]
可以参照这个例子：https://github.com/ant-design/antd-init/blob/master/boilerplates/plain-react/webpack.config.js#L11

我们自己是没问题的。

**Comment by qq645381995** [comment]
webpackConfig.babel.plugins.push(['antd', {
    style: 'css',  // if true, use less
  }]);  

这个我不知道在哪里写，我用的yo构建的项目，！

**Comment by mobei** [comment]
https://github.com/ant-design/ant-design/blob/master/index.js
