### ISSUE TITLE
Form - Performance Customized Form Controls

### ISSUE THREAD

**Issue by tranducit95** [ant-design/ant-design#20261]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-customized-form-controls](https://ant.design/components/form/#components-form-demo-customized-form-controls)

### Steps to reproduce
https://codesandbox.io/s/sleepy-http-2gflh

### What is expected?
The onChange input is very slow.

### What is actually happening?
I work with ~ 100 inputs, change the input value very slowly, is there a way to fix it or replace it?

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | latest |
| System | Ubuntu 18 |
| Browser | Chrome latest |

**Comment by afc163** [comment]
https://codesandbox.io/s/pedantic-ritchie-i2bvr

It is not a antd issue, you should learn how to optimize perf of function component by `useCallback` and `React.memo`.

**Comment by tranducit95** [comment]
> https://codesandbox.io/s/pedantic-ritchie-i2bvr
> 
> It is not a antd issue, you should learn how to optimize perf of function component by `useCallback` and `React.memo`.

Sorry, the problem I encountered with the ant table, I tried to apply your way, but it did not work, I am not sure because of the ant table or my error code, can you help me with a solution?

question on stackoverflow: https://stackoverflow.com/questions/59346576/reactjs-how-to-use-usecallback-usememo-optimizes-performance
