### ISSUE TITLE
Table组件设置横纵滚动并且有右固定列时，右固定列与表格会有些许错位

### ISSUE THREAD

**Issue by fwtcumt** [ant-design/ant-design#20269]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header](https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header)

### Steps to reproduce
给Table组件设置横纵滚动并且有右边固定列，内容设置多点，表格能左右上下滚动。

### What is expected?
表格中各条线都对齐

### What is actually happening?
表格右边固定列没有对齐

### example image
我的项目中：
<img width="425" alt="WX20191216-112245@2x" src="https://user-images.githubusercontent.com/21078500/70879048-f45b4d80-1ffe-11ea-9a29-8aa97176baf9.png">
官方示例中：
![1576466667061](https://user-images.githubusercontent.com/21078500/70879062-03420000-1fff-11ea-9d1b-5d7d728b1d02.jpg)

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.11.0 |
| System | mac、windows |
| Browser | 谷歌 78.0.3904.108 |

**Comment by fwtcumt** [comment]
这是固定列滚动时的样子，出现两个不一样大的滚动条。是不是表格滚动和浮起来的列滚动计算的有差异导致的呢。
<img width="295" alt="WX20191216-195627@2x" src="https://user-images.githubusercontent.com/21078500/70905192-3eafef00-203e-11ea-8d97-772914cc19df.png">

**Comment by fwtcumt** [comment]
咋整

**Comment by lf75152798** [comment]
你们官网的 demo上就能看出问题：表头分组，name和gender的高度都小了一个像素

**Comment by afc163** [comment]
Broken by https://github.com/react-component/table/commit/4aa8aa3a66b1b7c277a234b84c1bca2a06403ff5

**Comment by afc163** [comment]
Fixed in `rc-table@6.10.9`, reinstall node_modules and try it.

**Comment by LoveXMin** [comment]
我也出现有这样的现象,我是升级webpack和babel出现的
webpack2.7.0+babel6.26.0没有问题
webpack4.41.3+babel7.7.0出现该问题
table表头无换行,无rowSelection时没有问题
表头有换行或者rowSelection必现

**Comment by fwtcumt** [comment]
> Broken by [react-component/table@4aa8aa3](https://github.com/react-component/table/commit/4aa8aa3a66b1b7c277a234b84c1bca2a06403ff5)

我不再新提啦，我再给你说一种情况吧。现在我发现表格纵横同时滚动并且有固定列时，表格是对齐的，那1px错位没啦。但是，当设置表格可以选择时，也就是出现一列可选框后，右边固定列的1px错位还在。呜呜。。。

**Comment by afc163** [comment]
@fwtcumt 来个重现看看

**Comment by fwtcumt** [comment]
> @fwtcumt 来个重现看看
antd：3.26.5，react：16.11.0

<img width="1238" alt="xsjkjew23" src="https://user-images.githubusercontent.com/21078500/71616968-ce839a80-2bf3-11ea-856e-4f041a0f0e38.png">

**Comment by afc163** [comment]
这不是重现，http://u.ant.design/codesandbox-repro

**Comment by fwtcumt** [comment]
> 这不是重现，http://u.ant.design/codesandbox-repro

https://codesandbox.io/s/antd-reproduction-template-wrhfk
在codesandbox中好像没事，表格也挺丝滑，我本地有问题，表格滚动也生硬。我再看看吧。

**Comment by fwtcumt** [comment]
antd 3.26.6，都没有升级 rc-table 呢，那个1px的问题还在。
@afc163 
<img width="693" alt="WX20200108-115546@2x" src="https://user-images.githubusercontent.com/21078500/71949313-03a07600-320e-11ea-9d28-7ee1cace870e.png">

**Comment by afc163** [comment]
@fwtcumt 学习一下 npm 语义化版本的意思。

**Comment by fwtcumt** [comment]
> @fwtcumt 学习一下 npm 语义化版本的意思。

你这人说话真的是，我只知道现在我升级到了最新的antd，删除node_modules 重新下载了依赖，表格错位的问题还在。你给我说学习是啥意思。我写错了吗？

**Comment by Yongwang110** [comment]
您好 这个问题您解决了吗 我现在也碰到了同样的问题  请问您时怎么解决的啊
