### ISSUE TITLE
Add prop to catch Escape key event for editable Paragraph

### ISSUE THREAD

**Issue by mmarkelov** [ant-design/ant-design#20276]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-fermat-iqnjn)

### Steps to reproduce
Using Editable Paragraph, I want to clear text when user start typing, and if new value is empty I want to reset it to placeholder
1. Click on icon to start editing - it will clear paragraph

### What is expected?
If I close it with Escape, I want it to be reseted to placeholder. But if I close it by clicking outside TextArea it will fire onChange event and reset it to placeholder

### What is actually happening?
I want to catch on Escape event.

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome |

---
I don't know what is the best approach for this.
1. Add some additional prop to fire it with Escape key press
2. Fire onChange event like on clicking outside of TextArea
3. Maybe add some another prop to select whole text of TextArea

**Comment by afc163** [comment]
```diff
        <Paragraph
          editable={{ onStart: this.onStart, onChange: this.onChange }}
 +       onKeyDown={e => console.log(e)}
        >
```

**Comment by mmarkelov** [comment]
@afc163 thanks! But it isn't what I what. It doesn't catch Escape when I try to catch it in **TextArea**
