### ISSUE TITLE
fixed column width does not work when fixed columns are used with ellipsis

### ISSUE THREAD

**Issue by Aedless** [ant-design/ant-design#20272]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-0znd1)

### Steps to reproduce
When the fixed column is set with the ellipsis property, the width of the fixed column has no effect
```javascript
 {
    width: 100,
    fixed: "left",
    ellipsis: true
  }
```
in the reproduction, i set the width of "name" 100,  but it renders with 256

### What is expected?
fixed column width can take effect when fixed columns are used with ellipsis

### What is actually happening?
fixed column width does not work when fixed columns are used with ellipsis

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | latest |
| System | win10 |
| Browser | chrome 78 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-4r6w4

https://github.com/ant-design/ant-design/issues/14545#issuecomment-465415548

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/507615/70890474-1ca77400-2020-11ea-8ec0-cc443ab619e1.png">

**Comment by dhaval-radadiya** [comment]
above sandbox link breaking work but not an ellipsis. So any solution?
