### ISSUE TITLE
setFieldsValue is not working in Select component

### ISSUE THREAD

**Issue by lylpixin2121** [ant-design/ant-design#20273]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/lylpixin2121/pen/bGNBGKw?editors=0011](https://codepen.io/lylpixin2121/pen/bGNBGKw?editors=0011)

### Steps to reproduce
1、clicking on the select component
2、triggering the onchange event
3、Select the non-first option
4、fail to reset the state

### What is expected?
success to reset the state correctly

### What is actually happening?
clicking on the select component and triggering the onchange event，Failed to reset the state correctly

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16 |
| System | macos |
| Browser | chrome |

---
In some cases, when the user selects an option, it needs to be reminded of the reason it is not currently optional and reset to the correct option

**Comment by afc163** [comment]
You misunderstand how antd form works, please read documentation: https://ant.design/components/form-cn/#this.props.form.getFieldDecorator(id,-options)

The usage you are looking for is `options.normalize` probably.

**Comment by lylpixin2121** [comment]
@afc163 Thanks for the answer. I like ant-design very much. It seems that I still have a lot to learn

**Comment by roqkabel** [comment]
### 

> [`_hello****_`](

- 

1. url

)

**Comment by roqkabel** [comment]
### **_

> `[hello](

- 

1. url

)`

_**
