### ISSUE TITLE
是否有 sketch 组件资源，方便制作设计稿

### ISSUE THREAD

**Issue by anson0370** [ant-design/ant-design#2027]
请问是否有较完整的 sketch 组件资源，官网上的 Ant UX sketch 资源，里面的基本是交互原型，样式上并不完整。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1566

**Comment by anson0370** [comment]
Sorry, my bad. 没搜一下就问了。所以现在还没有准确的开放时间点是吗？
