### ISSUE TITLE
DatePicker的onChange事件如果点选了同一天不再触发onChange

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#20285]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表单提交时，如果值没有改动不做提交操作，但是现在DatePicker的onChange点击同一天会重复调用。

### What does the proposed API look like?
如果点选了同一天，不再触发onChange

### reproduce
[reproduce](https://codesandbox.io/s/antd-reproduction-template-njqyc)

**Comment by zhangzhi93** [comment]
[Reproduce](https://codesandbox.io/s/antd-reproduction-template-njqyc)

**Comment by afc163** [comment]
目前是实现是这样的，改掉的话会是 breakchange，我倾向于保持现状。

**Comment by zhangzhi93** [comment]
> 目前是实现是这样的，改掉的话会是 breakchange，我倾向于保持现状。

好的，自己再处理一下吧
