### ISSUE TITLE
TypeError: null is not an object (evaluating 'e.getBoundingClientRect')

### ISSUE THREAD

**Issue by stemtra** [ant-design/ant-design#20288]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://do-not-click-this-it-was-a-mandatory-field.com](http://do-not-click-this-it-was-a-mandatory-field.com)

### Steps to reproduce
No idea :(

### What is expected?
Not to happen

### What is actually happening?
...

| Environment | Info |
|---|---|
| antd | 3.15.0 |
| React | 16.6.3 |
| System | Mac |
| Browser | Safari |

---
Sentry sent me a notification about a random error, which I describe next. I believe it has something to do with an Affix. This has never happened to me and did not raise any concerns on the test suites. 

These are my Sentry logs:

On the Full tab:
TypeError
null is not an object (evaluating 'e.getBoundingClientRect')

On the Raw tab:
TypeError: null is not an object (evaluating 'e.getBoundingClientRect')
  at getTargetRect(../node_modules/antd/es/affix/utils.js:3:1)
  at value(../node_modules/antd/es/affix/index.js:390:34)
  at value([native code])
  at ? (../node_modules/antd/es/_util/throttleByAnimationFrame.js:30:1)

On utils.js I have this (I have not modified the original antd code):
import addEventListener from "rc-util/es/Dom/addEventListener";
export function getTargetRect(target) {
  return target !== window ? target.getBoundingClientRect() : {
    top: 0,
    bottom: window.innerHeight
  };
}

Any help is HIGHLY appreciated

**Comment by Juviro** [comment]
I have the same issue. I don't know exactly what causes the error, but it only occurs on mobile devices and only if you scrolled before unmounting the component that includes the Affix.

Minimal reproducible project: https://github.com/Juviro/antd-affix-demo
