### ISSUE TITLE
Disabled time can selected and onChange is triggered for that same.

### ISSUE THREAD

**Issue by balavishnuvj** [ant-design/ant-design#20280]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8sx75)

### Steps to reproduce
1. Click on DatePicker/TimePicker.
2. Select any time (for Datepicker select any date). 
3. Now the disabled time is selected(visible in UI). and onChange for the same is called.
4. Click outside that modal. The selected value is still selected.

### What is expected?
Disabled time shouldn't show in UI. onChange for invalid dates shouldn't be called.

### What is actually happening?
Disabled time is shown. Even though ok is disabled. User can click outside modal and input will have the disabled value.

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | All |
| Browser | All |

---
ran into this bug, when the default value was not a valid date. But then select time was enabled. by this user can trick into selecting disabled time.

**Comment by afc163** [comment]
If all hours are disabled, you should hide hour column by setting `format="mm a"`.

**Comment by balavishnuvj** [comment]
@afc163 even then `am/pm` will be enabled.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
