### ISSUE TITLE
[4.0] Table style details

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20291]
| Problem | 3.x ✅ | 4.x ❌ |
|---|---|---|
| 筛选列头 hover 背景色 | <img width="397" alt="image" src="https://user-images.githubusercontent.com/507615/70970156-956a0700-20d8-11ea-86aa-24a94cfed5a0.png"> | <img width="379" alt="image" src="https://user-images.githubusercontent.com/507615/70970145-8e42f900-20d8-11ea-931e-781567855846.png"> |
| 行 hover 背景色是不是应该和列头一样比较美观 | - | <img width="1175" alt="image" src="https://user-images.githubusercontent.com/507615/70970244-ce09e080-20d8-11ea-9630-11c04725ae95.png"> |
| 自定义筛选图标没有鼠标 ✋ 手型 | - | <img width="89" alt="image" src="https://user-images.githubusercontent.com/507615/70970504-7c158a80-20d9-11ea-899e-9c13885de546.png"> |

**Comment by stunaz** [comment]
And also with `size="small"`, they are some issues. i.e `tr->th` no longuer grayed, issue wiith fixed column
