### ISSUE TITLE
Make the focusing input be optional, when trigger the "onSearch" event on Input.Search component

### ISSUE THREAD

**Issue by YaoKaiLun** [ant-design/ant-design#20297]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I use Input.Search component in my website, and my website is responsible. When i click search button in  the mobile, it will trigger focusing input, and it cause keyboard pop up.
I think it will be better to have a parameter to controller this feature that if focusing input after triggering the "onSearch" event.

### What does the proposed API look like?
Add a parameter "focusAfterSearch", the default value is "true".

https://github.com/ant-design/ant-design/blob/333f63bd05db2d5dcc6e051022a5487cb2aa2082/components/input/Search.tsx#L50

**Comment by afc163** [comment]
We can add mobile device detection before focus input by using https://github.com/juliangruber/is-mobile

```js
if (!isMobile()) {
  this.input.focus(); 
}
```

Could you send us a PR to fix it?

**Comment by yoyo837** [comment]
Why not use prop like `autoFocus`, 交由业务去做?

**Comment by yoyo837** [comment]
开先河的感觉。

**Comment by afc163** [comment]
@yoyo837 It is not `autoFocus` but a `focusAfterSearch` prop like @YaoKaiLun propoksed.

But I think it is better to reduce those props which are too complex to understand by setting a default hehavior.
