### ISSUE TITLE
Typography.Paragraph 截取行数显示不正确

### ISSUE THREAD

**Issue by shijunwen** [ant-design/ant-design#20292]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-meitner-6ujzl)

### Steps to reproduce
当电脑系统的显示分辨率为1920x1080,在显示设置里面设置缩放与布局：更改文本，应用等项目的大小为 150% 或者 125%。

### What is expected?
<Paragraph ellipsis={{ rows: 3，expandable: true  }}> ，当rows等于3，显示3行，然后省略号。

### What is actually happening?
<Paragraph ellipsis={{ rows: 3，expandable: true  }}>，当rows等于3，实际显示4行，然后省略号

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | react 16.12.0 |
| System | windows 10 |
| Browser | 版本 78.0.3904.108（正式版本） （64 位） |

**Comment by shijunwen** [comment]
![image](https://user-images.githubusercontent.com/33819581/70971264-88024c00-20db-11ea-8086-905d7b576484.png)

**Comment by afc163** [comment]
Duplicate of #19219
