### ISSUE TITLE
Tree: disabled node is not counted for checked state of parent node

### ISSUE THREAD

**Issue by panlina** [ant-design/ant-design#20299]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-tree-checked-state-issue-sq7ny)

### Steps to reproduce
Just run the code.

### What is expected?
`a` is checked, and `x` is not checked.

### What is actually happening?
`a` is not checked, and `x` is checked.

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16 |
| System | any |
| Browser | any |

---
It's a changed behavior in antd 3. In antd 3 disabled tree nodes are not counted for checked states of their parents, and are not affected by checking/unchecking their parents either.

Disabled-ness of nodes should not affect parent node state, because whether a node is disabled reflects a restriction of the operation, while the checked state reflects the current state.

In this demo, it just looks illogical that a node is not checked while its only child is checked, and another node is checked while obviously its 1st child is not checked.

**Comment by panlina** [comment]
@afc163 Have you reviewed this issue?

**Comment by afc163** [comment]
I believe it is a bug, could you help to fix it by sending us a PR?

**Comment by panlina** [comment]
Sure. I'll work on it. Thanks for your confirmation.

**Comment by cnt-null** [comment]
Hi, this issue is still relevant for antd 4.15.2.
Please see the Reproduction link from the first message: https://codesandbox.io/s/antd-tree-checked-state-issue-sq7ny
