### ISSUE TITLE
npm 2 中使用 antd 可能会遇到的问题

### ISSUE THREAD

**Issue by pigcan** [ant-design/ant-design#2030]
### 场景

项目自身因为需要兼容 IE8 引用了 React 0.14.x 的版本，但是又引用了 antd 大于 1 的版本

在这种场景下，在 npm2 中会有很多奇怪的报错，报错不出现在构建环境，而是页面访问时候。

### npm2 中

项目自身有依赖 `react 0.14.x`, 而 `antd^1.1.0` 的 devDependencies 存在 react 0.15.0，在 2 的环境下 install 完之后 react 0.15.0 会在 antd 的 node_moduels，最终项目在构建的时候项目内会打包进两个 react 版本。进而引发报错。

### npm3 中

在如上场景中，install 完之后 react 0.15.0 并不会出现在项目的 node_modules 中，所以构建出来之后只有一个 react 符合预期。

### 大致原因

不同 npm 版本 对于 devDependencies 的处理不同 。

### 结论

还是不要推荐使用 npm2，也不要再考虑 npm2 了吧 - -！

**Comment by afc163** [comment]
不是 npm2 的问题。

是这里引入了 https://github.com/ant-design/ant-design/blob/fbe17bf458f7adfb727f9bb33e6bbc3d95333928/package.json#L73 把 react@0.15 带进来了。

@superRaytin 是不是不要直接引用这个包。

**Comment by superRaytin** [comment]
修改为一个低版本的 react-addons-pure-render-mixin ?

**Comment by superRaytin** [comment]
直接使用 shallowEqual 如何：

https://github.com/facebook/react/blob/eb050727ee691702ac6a489c378582bff34acd9e/src/addons/shallowCompare.js

**Comment by afc163** [comment]
不要依赖 react ，直接拷过来。或者用 https://www.npmjs.com/package/pure-render-mixin

**Comment by superRaytin** [comment]
上面这个也有依赖 react https://github.com/francoislaberge/pure-render-mixin/blob/master/package.json#L30

**Comment by afc163** [comment]
对，不是这个问题。`react-addons-pure-render-mixin` 里也没有依赖 react 。

还是 npm2 的问题，npm2 里会安装 `peerDependencies`。

**Comment by afc163** [comment]
OK，结论是，不要使用 npm2 了，确实会有很多问题。

**Comment by afc163** [comment]
@superRaytin 还是改掉，目前 react-addons-pure-render-mixin@15.1.0 的 peerDependencies 依赖是 `react:"^15.1.0"`，对于依赖了 react@0.14.x 的项目，由于版本不兼容，会导致两个版本的 react 都被 npm2 安装。

**Comment by superRaytin** [comment]
OK。

**Comment by superRaytin** [comment]
才发现原来 rc-util 已经提供了 shallowEqual 方法 :sweat_smile:

那就把所有用 pureRenderMixin 的都改成 shallowEqual 方式好了。

**Comment by afc163** [comment]
还是用 npm3 吧。。。
