### ISSUE TITLE
4.0 Form Input and Select placeholder overlap

### ISSUE THREAD

**Issue by ycjcl868** [ant-design/ant-design#20304]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-swartz-k9591)

### Steps to reproduce
Because of form 4.0 rule https://github.com/ant-design/ant-design/issues/20221，all empty Input and Select will fill the placeholder, so it possibly appears the overlap when using both Input and Select.

### What is expected?
not overlap

### What is actually happening?
overlap

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | latest |
| System | OS X |
| Browser | Chrome |

**Comment by zombieJ** [comment]
AutoComplete with customize input should only have one `placeholder`.
