### ISSUE TITLE
[4.0] Can't resolve '@ant-design/icons/lib/manifest'

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20319]
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/507615/71054706-d839e680-218d-11ea-83c9-b96173af51fb.png">

本地开发模式下任何页面有这个报错。

**Comment by zombieJ** [comment]
git 同步一下，把 tsx 生成的 jsx 临时去掉即可。
