### ISSUE TITLE
4.0 Table will show expand icon even when children is null or false

### ISSUE THREAD

**Issue by julianwachholz** [ant-design/ant-design#20310]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-sinoussi-sihx2)

### Steps to reproduce
```
<Table dataSource={[
  { key: 0 },  // only working solution now
  { key: 1, children: null },
  { key: 2, children: false },
]}/>
```

### What is expected?
Rows where `children` is `null` or `false` should not show expand icon.

### What is actually happening?
Rows where `children` is `null` or `false` shows expand icon.

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | 16.12.0 |
| System | All |
| Browser | All |

**Comment by afc163** [comment]
https://github.com/react-component/table/pull/382

@zombieJ

**Comment by afc163** [comment]
`+ rc-table@7.0.0-alpha.21`
