### ISSUE TITLE
打包之后'antd.less'体积过大

### ISSUE THREAD

**Issue by zhishanggao** [ant-design/ant-design#20322]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
项目中引用了样式文件 import 'antd/dist/antd.less', 并且自定义了主题色, 打包出来体积过大
![image](https://user-images.githubusercontent.com/16753441/71060562-c57cdd00-21a0-11ea-88c1-2751bdc07a51.png)
![image](https://user-images.githubusercontent.com/16753441/71060587-db8a9d80-21a0-11ea-835c-e49ad463e12d.png)

### What is expected?
icon全部被打入这个问题我看到其它解决方案了,  但是antd.less这么大我表示不能理解;

### What is actually happening?
实际上 antd.less 打包完大小550kb, icon也被全部打进去了

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.11 |
| System | macOS 10.14.6 |
| Browser | Chrome 79.0.3945.79 (正式版本) （64 位） |

**Comment by yoyo837** [comment]
Duplicated of #12011

**Comment by afc163** [comment]
`antd/dist/antd.less` 的体积只有这么大。

https://unpkg.com/browse/antd@3.26.3/dist/
https://unpkg.com/browse/antd@3.26.3/dist/antd.less

**Comment by zhishanggao** [comment]
> `antd/dist/antd.less` 的体积只有这么大。
> 
> https://unpkg.com/browse/antd@3.26.3/dist/
> https://unpkg.com/browse/antd@3.26.3/dist/antd.less

我知道 但我不知道为什么我打出来的会这么大

**Comment by afc163** [comment]
给个重现的 repo 看看

**Comment by zhishanggao** [comment]
> 给个重现的 repo 看看

吐血, 原来根本就没有这么小, 里面引用了很多其它样式表
![image](https://user-images.githubusercontent.com/16753441/71061876-193cf580-21a4-11ea-946c-a4d5accc80d2.png)
![image](https://user-images.githubusercontent.com/16753441/71061894-22c65d80-21a4-11ea-9f8e-9a4e241818f4.png)

**Comment by zhishanggao** [comment]
> Duplicated of #12011

@yoyo837 
这个我看到了呀 我说icon全部被打入的问题我看到解决方案了, 我问的是打出来的样式表文件这么大怎么搞
