### ISSUE TITLE
Tree 组件 全部反选后 check 勾选框 不能恢复

### ISSUE THREAD

**Issue by MysteriousRookie** [ant-design/ant-design#2032]
最近的React项目中用到了 ant-design 
在使用Tree组件时出现了如下问题：
请问这种情况是不是框架本身的bug

初始化时Tree组件的check 根据后台传递过来的数据自动选中
Tree 在 Modal 里面 打开Modal 的时候 把后端数据传给Tree
反选几个check后 然后点击 Modal 的取消 (点击取消不做任何改动 确定按钮是修改作用)
然后再打开Modal组件 Tree组件的 check 会恢复到初始的勾选状态
如果全部反选
在点击取消 然后再打开 Modal 组件 check 全部为反选状态 

## 期待的结果是：

打开Tree组件 全部反选后，点击取消 然后再打开Tree组件 会恢复原来勾选的check

## 本地环境信息

- antd 版本: 1.1
- 操作系统及其版本： windows 10
- 浏览器及其版本: Chrome 50.0.2661.102 m

**Comment by afc163** [comment]
Modal 就是个容器，取消隐藏时，不会对容器内组件的状态做任何改变。

Tree 是有受控属性的，建议用 checkedKey 做精确的控制。

另外，最好给出在线演示 http://codepen.io/anon/pen/wGOWGW?editors=001 这样也可以看看你现在的代码逻辑是否可优化。

**Comment by MysteriousRookie** [comment]
<Tree className="myCls" showLine multiple={true} checkable={true} 
                      autoExpandParent={autoExpandParent}
                      expandedKeys={expandedKeys}     
                      onExpand = {this.onExpand} 
                      checkedKeys={Codes} 
                      onCheck={this.onCheck}>
                      {this.getTreeNode(nodeData)}
                    </Tree>
我就是使用的受控属性 checkedKey  如果不使用受控属性  那不是全部反选的时候 就会出问题了 现在 只是在 全部反选的时候 出现问题 其他情况 全部正常

**Comment by MysteriousRookie** [comment]
我刚刚写了个Demo 现在故障可以重现了 

-----------------------------------------------------------------------------------------------
const { Tree,Modal,Button } = antd;
const TreeNode = Tree.TreeNode;

const x = 3;
const y = 2;
const z = 1;
const gData = [];

const generateData = (_level, _preKey, _tns) => {
  const preKey = _preKey || '0';
  const tns = _tns || gData;

  const children = [];
  for (let i = 0; i < x; i++) {
    const key = `${preKey}-${i}`;
    tns.push({ title: key, key });
    if (i < y) {
      children.push(key);
    }
  }
  if (_level < 0) {
    return tns;
  }
  const level = _level - 1;
  children.forEach((key, index) => {
    tns[index].children = [];
    return generateData(level, key, tns[index].children);
  });
};
generateData(z);
const App = React.createClass({
  getInitialState() {
    return { 
      visible: false,
      expandedKeys: [],
      autoExpandParent: true,
      checkedKeys: ['0-0-0'],
    };
  },
  onExpand(expandedKeys) {
    this.setState({
      expandedKeys,
      autoExpandParent: false,
    });
  },
  onCheck(checkedKeys) {
    this.setState({
      checkedKeys,
    });
  },
  showModal() {
    this.setState({
      expandedKeys: ['0-0-0', '0-0-1'],
      checkedKeys:['0-0-0'],
      visible: true,
    });
  },
  handleOk() {
    this.setState({
      visible: false,
    });
  },
  handleCancel(e) {
    this.setState({
      visible: false,
    });
  },
  render() {
    const loop = data => data.map((item) => {
      if (item.children) {
        return (
          <TreeNode key={item.key} title={item.key} disableCheckbox={item.key === '0-0-0'}>
            {loop(item.children)}
          </TreeNode>
        );
      }
      return <TreeNode key={item.key} title={item.key} />;
    });
    return (
      <div>
        <Button type="primary" style={{fontSize:"50px"}} onClick={this.showModal}>ShowModal</Button>
        <Modal title="TestDemo" visible={this.state.visible} onOk={this.handleOk} onCancel={this.handleCancel}>
          <Tree checkable multiple={this.props.multiple}onExpand={this.onExpand} 
            expandedKeys={this.state.expandedKeys}
            autoExpandParent={this.state.autoExpandParent}
            onCheck={this.onCheck} 
            checkedKeys={this.state.checkedKeys}
          >
            {loop(gData)}
          </Tree>
        </Modal>
      </div>
    );
  }
});

ReactDOM.render(<App/>, document.getElementById('container'));
-------------------------------------------------------------------------------------
在非全部反选的情况下 重新打开 模态框  没有问题。 如果全部反选 重新打开模态框 就会变成全部反选状态

**Comment by afc163** [comment]
1. 排版都乱了。
2. 你可以 fork 一份 codepen 出来。

**Comment by afc163** [comment]
@warmhug 看看。

**Comment by warmhug** [comment]
已修复，谢谢反馈

**Comment by MysteriousRookie** [comment]
好的
