### ISSUE TITLE
Tabs中触发一次onChange事件render两次TabPane

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design#20321]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.暂时没有.com](https://www.暂时没有.com)

### Steps to reproduce
TabPane的内容是一个从服务端远程取数据的列表，当切换到该Tab时，render了两次该TabPane的内容

### What is expected?
希望只render一次该TabPane的内容

### What is actually happening?
render了两次该TabPane的内容，重复渲染了。

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 最新版 |
| System | windows10 |
| Browser | chrome 版本 73.0.3683.103（正式版本） （32 位） |

**Comment by effapp** [comment]
没有服务端远程取数据，codesandbox不好写啊

**Comment by yoyo837** [comment]
延时模拟

**Comment by lovelyJason** [comment]
我猜楼主问的不是这个,是tabs下面那条线的动画问题吧
