### ISSUE TITLE
Fixed Sider: Zero-width-trigger not displaying

### ISSUE THREAD

**Issue by Altair312** [ant-design/ant-design#20333]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout/#components-layout-demo-fixed-sider](https://ant.design/components/layout/#components-layout-demo-fixed-sider)

### Steps to reproduce
Add an "overflow:scroll" or "overflow: auto" to <aside> element

### What is expected?
The custom width trigger to be available

### What is actually happening?
The custom width trigger, when using a fixed Sider and being collapsible for smaller screens, is gone, being placed behind the rendered content. 

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | Ubuntu 18.02 |
| Browser | Mozilla 71, Chrome 79 |

**Comment by Altair312** [comment]
https://codesandbox.io/s/antd-reproduction-template-tgfrg - reproducing the issue

Note that, without overflow: scroll or overflow:auto, the custom width trigger displays correctly.

**Comment by afc163** [comment]
zeroWidthTrigger belongs to `.ant-layout-sider` in dom structure, which make the trigger hidden if it has `overflow` style. Nothing we can do about it.
