### ISSUE TITLE
antd 4.0 Virtual Table Demo support more props

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design#20339]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-kare-riocq)

### What is expected?
固定列

### What is actually happening?
只固定了表头

| Environment | Info |
|---|---|
| antd | 4.0-bate0 |
| React | 16.12.0 |
| System | win 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
虚拟滚动 Demo 只实现了滚动以展示自定义内容的 API。欢迎提交 PR 帮助完善固定列的功能~

Virtual scroll demo is only apply scroll to show the customize body API. Welcome PR to fullfill the demo~

**Comment by Nokecy** [comment]
这个问题怎么处理 ，有没有方向？各位的大佬~~~

**Comment by hejinhua** [comment]
用了虚拟表格，表格的其他功能都不能用了，大佬们有没有解决方法啊！

**Comment by crawler-django** [comment]
> 用了虚拟表格，表格的其他功能都不能用了，大佬们有没有解决方法啊！

可以试一下 'virtuallist-antd'. 
(try 'virtuallist-antd')

**Comment by WangYang-Rex** [comment]
用了虚拟滚动，固定列失效，rowselection也失效了，如何解决？有没有解决方法啊

**Comment by yxwangcs** [comment]
Sadly the current virtualization demo on the documentation breaks many functionalities of antd Table.

For anyone who is also struggling to get it working, [virtuallist-antd](https://github.com/crawler-django/virtuallist-antd) is definitely something worth trying. Meanwhile if you have time and don't mind adding an extra dependency to your project, you can use BaseTable from [react-base-table](https://github.com/Autodesk/react-base-table) which has similar features that antd Table offers, but with built-in virtualization and a lot more flexibilities/customization supports.

Hopefully antd will have built-in virtualization for Table component as well in the future.  😃

**Comment by PaulPCIO** [comment]
This solution seems to work fine https://github.com/ant-design/ant-design/issues/24383#issuecomment-635963733

**Comment by Nokecy** [comment]
考不考虑 5.0 原生支持虚拟滚动～～～～

**Comment by bthulu** [comment]
> 考不考虑 5.0 原生支持虚拟滚动～～～～

感觉难, 搜了下全网react对虚拟滚动的支持都不咋的, 基本都是基于react-window这些来的, 要么功能缺失, 要么不支持pageup, pagedown, home, end导航

**Comment by shen4-4** [comment]
I refer this link 【https://codesandbox.io/embed/2jvl09przn?codemirror=1】，two grids are used to archieve fixed column，and change the scroll bar css style to unity，but there are still imperfection

**Comment by hairgc** [comment]
愈发怀念使用Angular ng-zorro的快乐时光，React的虚拟滚动太恶心了

**Comment by zpaul** [comment]
所以这个问题解决了吗

**Comment by lianer3588** [comment]
有关于解决虚拟表格固定列失效问题的方案吗～

**Comment by AsuraKev** [comment]
I am interested in this topic too. So currently there are no in detail example of how to use Table features like row selection, editable cell together with virtual list. I assume that most features of Table will break when used with virtual list? Hopefully this problem can be treated with number 1 priority :) thanks

**Comment by yoyo837** [comment]
After #44349 was merged, virtual tables support almost all properties requested here that are not yet supported and will be released in the next minor release.

There is all about it here #44526.

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/releases/tag/5.9.0 it out. Let's close this.

**Comment by AsuraKev** [comment]
Will virtual table support pagination in next minor releases? I see it currently cannot handle it :) thanks

**Comment by zhouzhongyuan** [comment]
> https://github.com/ant-design/ant-design/releases/tag/5.9.0 it out. Let's close this.

Yoyo, will this feature support Antd 4? For there are lots of Antd 4 project.

**Comment by yoyo837** [comment]
> > https://github.com/ant-design/ant-design/releases/tag/5.9.0 it out. Let's close this.
> 
> Yoyo, will this feature support Antd 4? For there are lots of Antd 4 project.

Actually, no. Not in plan.

**Comment by SunXinFei** [comment]
官方的虚拟列表示例，真的是demo，在fixed列、合并单元格等场景存在不支持的问题，目前改了一版，目前看效果还可以。在antd4版本的table虚拟化列表的同时，支持表格的 拖拽、编辑、行高不一致、fixed、预览，合并单元格等

**Comment by RunFishes** [comment]
> 官方的虚拟列表示例，真的是demo，在fixed列、合并单元格等场景存在不支持的问题，目前改了一版，目前看效果还可以。在antd4版本的table虚拟化列表的同时，支持表格的 拖拽、编辑、行高不一致、fixed、预览，合并单元格等

有具体方案可以参考下吗，我这边也有同样的需求

**Comment by SunXinFei** [comment]
> > 官方的虚拟列表示例，真的是demo，在fixed列、合并单元格等场景存在不支持的问题，目前改了一版，目前看效果还可以。在antd4版本的table虚拟化列表的同时，支持表格的 拖拽、编辑、行高不一致、fixed、预览，合并单元格等
> 
> 有具体方案可以参考下吗，我这边也有同样的需求

最近比较忙，还没有开源计划
