### ISSUE TITLE
Form 组件 getFieldDecorator 注册结构化的 name ，数据结构发生错误变化

### ISSUE THREAD

**Issue by hayderGo** [ant-design/ant-design#20334]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/getfielddecorator-shujujiegoufashenggaibianwenti-dmse5?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
看 codesandbox 里的注释和 console 结果

### What is expected?
希望能够解决或提供规避的方案

### What is actually happening?
这一项是啥意思？

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16 |
| System | win10 |
| Browser | chrome |

---
动态添加表单项，每个表单项有多个子属性需要控制，类似于动态添加表格的行，一行有多列，整个表格作为 form 的一个 field

**Comment by zombieJ** [comment]
`getFieldDecorator` 用于注册字段，嵌套结构只需要注册子字段 `payInfo[0].name`，不要注册 `payInfo`。

ref: https://ant.design/components/form-cn/#components-form-demo-dynamic-form-item

**Comment by hayderGo** [comment]
只注册子字段后，对 payInfo 进行 setieldValue 进行动态新增删除就失效了。
ref: https://codesandbox.io/s/formsetfieldsvalue-shixiao-j9xx7?fontsize=14&hidenavigation=1&theme=dark

**Comment by zombieJ** [comment]
不能对 `payInfo` 直接设置值，只能对 `payInfo[0].name` 设置值。

**Comment by hayderGo** [comment]
如果不能对`payInfo`直接设置值，那该怎么进行动态删除`payInfo`中某一项的操作呢？
并且我尝试了几种方式对 `payInfo[0].xxx`设置值，依然是失效或者报错
（设置值得本意是为了新增一行，`form.setFieldsValue(`payInfo[${payload.length}]`, {});`报错的原因应该是还没有注册过对应字段，就进行了赋值草错导致）
ref: https://codesandbox.io/s/formsetfieldsvalue-shixiao-linex?fontsize=14&hidenavigation=1&theme=dark
App.jsx 91行

**Comment by hayderGo** [comment]
貌似找到问题所在了，需要用一个单独的字段`keys`控制新增/删除...
