### ISSUE TITLE
table Column的filters能不能自定义实现

### ISSUE THREAD

**Issue by dreamcatcher081210** [ant-design/ant-design#2033]
table Column的filters能不能实现点击筛选图标后弹出文本框，然后根据所输入的value进行筛选？

**Comment by afc163** [comment]
可以考虑。

目前可以自定义列头来实现。

**Comment by dreamcatcher081210** [comment]
@afc163 自定义列的话那这个分页器和每页显示大小就会发生问题啊，比如现在


我查询出了10条数据，然后我再向data里增加一条空数据用以显示自定义行，可是，结果显示9条数据加一条自定义行

**Comment by wufeng87** [comment]
@dreamcatcher081210 是自定义列头，不是自定义列

**Comment by dreamcatcher081210** [comment]
收官。。。
