### ISSUE TITLE
form.setFieldsValue 失效

### ISSUE THREAD

**Issue by hayderGo** [ant-design/ant-design#20342]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formsetfieldsvalue-shixiao-j9xx7?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
点击第一列单元格（添加/删除）无效

### What is expected?
希望能够确定这是一个bug，还是我哪里使用方式不对

### What is actually happening?
。

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16 |
| System | win10 |
| Browser | chrome |

---
使用类似文档中的实现方式，但是没有生效 ref: https://ant.design/components/form-cn/#components-form-demo-dynamic-form-item

**Comment by zombieJ** [comment]
<img width="782" alt="截屏2019-12-20上午10 47 08" src="https://user-images.githubusercontent.com/5378891/71226222-1d892000-2316-11ea-9c1e-3605ee94d05c.png">

例子里没有直接对 `payInfo` 进行操作，操作的是 key：
```tsx
form.setFieldsValue({
  keys: nextKeys,
});
```

加减都需要通过注册的字段进行操作。
