### ISSUE TITLE
Require set Form layout to vertical when it's created by From.create

### ISSUE THREAD

**Issue by xupea** [ant-design/ant-design#20352]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
can be able to set the layout to vertical when Form is created by Form.create method

### What does the proposed API look like?
hm.. not sure, it could be in the options in Form.create method?

**Comment by zombieJ** [comment]
`layout` is a prop of `Form` component. `Form.create` is a HOC that generate with `form` prop, not Form component.

ref: https://reactjs.org/docs/higher-order-components.html
