### ISSUE TITLE
List of icons documentation page very slow

### ISSUE THREAD

**Issue by prcdpr** [ant-design/ant-design#20354]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/icon/#List-of-icons](https://ant.design/components/icon/#List-of-icons)

### Steps to reproduce
Open icon documentation
Type something in search field

### What is expected?
It searches normally without freezes

### What is actually happening?
It's very slow and freezes page

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | * |
| System | * |
| Browser | Firefox 71.0 (64-bit) |

**Comment by afc163** [comment]
It works well now.
