### ISSUE TITLE
补充关于类型(typescript)的说明文档

### ISSUE THREAD

**Issue by p2227** [ant-design/ant-design#20359]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在typescript的趋势越来越明显了，antd中有很多类型的定义，但只是放在那里，没有使用说明
类似这样的结果 https://ant.design/components/table-cn/#%E5%9C%A8-TypeScript-%E4%B8%AD%E4%BD%BF%E7%94%A8
但希望能补全

前期可以先针对一些faq先收集，比如 
https://github.com/ant-design/ant-design/issues/15578#issuecomment-475486287
这个场景下，总是会提示type错误，可以怎么去定义解决？

像这种问题没有什么好的关键字去查，可能收集到faq是个好办法

### What does the proposed API look like?
没有，关于文档的

**Comment by afc163** [comment]
可以的，文档是个长期的过程，欢迎发现问题给我们直接 PR 补充到 FAQ。

另外，4.0 的演示代码已经支持 ts 类型，也欢迎来帮忙改造。

**Comment by p2227** [comment]
![image](https://user-images.githubusercontent.com/4214942/71241475-a9b33b80-2346-11ea-9704-2ca78308e9d1.png)
@afc163 如果我要看4.0，应该要以哪个分支的代码为准？

**Comment by afc163** [comment]
4.0-prepare
