### ISSUE TITLE
Doc: Form example  icon not correct and scrolling break

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#20358]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-register](https://ant.design/components/form-cn/#components-form-demo-register)

### Steps to reproduce
1. icon not correct
2. break scroll when input focus
![image](https://user-images.githubusercontent.com/14831261/71226558-2f1ef780-2317-11ea-8c6a-7cd732a6b13c.png)

### What is expected?
icon correct and can scroll when input focus

### What is actually happening?
icon not correct and scroll break

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.3 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by afc163** [comment]
来个 PR

**Comment by xrkffgg** [comment]
😂😂😂 我没有理解啥意思啊，我怎么点不出来你说的问题

**Comment by xrkffgg** [comment]
@afc163 
而且这两个按钮间隔，是不是有一点大 😂

**Comment by afc163** [comment]
对，这是 bug。
