### ISSUE TITLE
select 下拉框位置偏移

### ISSUE THREAD

**Issue by ShenganLee** [ant-design/ant-design#20368]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-fidsr8](https://stackblitz.com/edit/react-fidsr8)

### Steps to reproduce
```js
<div
    style={{
      position: "absolute",
      top: "10%",
      left: "10%",
      width: 200,
      height: 200,
      transform: "scale(1.5)"
    }}
  >
    <Select
      defaultValue="lucy"
      style={{ width: 120 }}
      onChange={handleChange}
      getPopupContainer={triggerNode => triggerNode}
    >
      <Option value="jack">Jack</Option>
      <Option value="lucy">Lucy</Option>
      <Option value="disabled" disabled>
        Disabled
      </Option>
      <Option value="Yiminghe">yiminghe</Option>
    </Select>
  </div>
```

### What is expected?
下拉框位置正确

### What is actually happening?
![下拉框位置偏移](https://user-images.githubusercontent.com/50688524/71248334-88a61700-2355-11ea-895f-4d4fa10f4965.png)

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | react |
| System | win10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`scale(1.5)` 会影响位置计算，暂时没有什么好办法解……

**Comment by ntscshen** [comment]
@zombieJ Are there plans to fix this problem

**Comment by afc163** [comment]
Duplicate of #26681

**Comment by afc163** [comment]
Duplicate of #26681

**Comment by Flourad** [comment]
这个问题怎么解决呢？

**Comment by laughing-pic-zhu** [comment]
没人解决吗？

**Comment by Bigbig-Huang** [comment]
这个问题解决了嘛？

**Comment by xiaoying23** [comment]
这个问题 有解决方法么？
