### ISSUE TITLE
less nested import doesn't work properly

### ISSUE THREAD

**Issue by lunaticusgreen** [ant-design/ant-design#20369]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
I have already created issue, but it was closed without real checking, please look at comments below in this task https://github.com/ant-design/ant-design/issues/20036, I reproduced proplem and attached link to repo with reproduction. It also can be reproduced in any online LESS compiler .
I dont know, what else evidence i can provide if this is not enough.

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8jx9y)

### Steps to reproduce
*  Follow this guild https://ant.design/docs/react/customize-theme#Configure-webpack-to-load-an-alternate-less-file-and-scope-global-styles and add any selector to wrap antd import
* Add collapse panel into your wrapper
* Done, it's broken

### What is expected?
Everything works as there is not wrapper selector

### What is actually happening?
In source code of collapse panel I have seen this example of code ( pay attention to & > &-item):

```
.@{collapse-prefix-cls} {
  .reset-component;

  background-color: @collapse-header-bg;
  border: @border-width-base @border-style-base @border-color-base;
  border-bottom: 0;
  border-radius: @collapse-panel-border-radius;

  & > &-item {
```

when I don't use wrapper or just import antd.less into javascript directly, it compiles into something like this:
```
.ant-collapse > .ant-collapse-item > .ant-collapse-header .ant-collapse-arrow svg {
  display: inline-block;
}
```

but when I'm importing antd.less this way:
```
#antd-wrapper {
  @import "antd/dist/antd.less";
}

```

I'm getting:
```
#antd-wrapper .ant-collapse > #antd-wrapper .ant-collapse-item > .ant-collapse-header .ant-collapse-arrow svg {
  display: inline-block;
}
```

This second #antd-wrapper seems an error to me

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.11.0 |
| System | macos 10.15.1 (19B88) |
| Browser | Firefox developer edition 71.0b12 (64-bit) |

---
I've just found it when I isolated my application as it was written in guide and than noticed that some components are broken, while most of them are not.
for some reason less not imports well in codesandbox, but it can be easily reproduced locally

**Comment by lunaticusgreen** [comment]
@yutingzhao1991 Hello, is there any news?

**Comment by zombieJ** [comment]
That's what less work. We can do nothing on this. Please fire requirement issue to [less](https://github.com/less/less.js) instead.

**Comment by me6iaton** [comment]
I used mixins to get around the nesting problem
```
#ant {
  .airy-collapse() {
    @ant-prefix: 'ant-airy';
    @collapse-prefix-cls: ~'@{ant-prefix}-collapse';
    @collapse-content-padding: 16px 0px;

    @import (multiple) '../../../node_modules/antd/es/collapse/style/index-pure.less';

    .@{collapse-prefix-cls} {
      & > &-item {
        > .@{collapse-prefix-cls}-header {
          font-weight: 500;
        }
      }
    }
  }
}

#ant.airy-collapse();
```
