### ISSUE TITLE
upload组件不支持预览从服务器根据链接获取的ico文件

### ISSUE THREAD

**Issue by Xianbei233** [ant-design/ant-design#20360]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[demo](https://codesandbox.io/s/antd-reproduction-template-gp6j7)

### Steps to reproduce
从服务器获取的ico文件的url，写入fileList中file的url中，listType为 "picture-card"，组件不支持内部预览

### What is expected?
ico文件链接可以组件内预览

### What is actually happening?
ico文件链接不能预览

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | ^16.7.0 |
| System | Windows 10 1903 |
| Browser | Chrome 77.0.3865.120 |

**Comment by Xianbei233** [comment]
demo更新,https://codesandbox.io/s/antd-reproduction-template-gp6j7

**Comment by afc163** [comment]
1. 可以自行补充 `file.type`：https://codesandbox.io/s/antd-reproduction-template-h1xp6
2. 也可以给我们 PR，修改默认的图片判断正则：https://github.com/ant-design/ant-design/blob/6e27c62eb36feee8c1c0c1b4c07cd92ba341f544/components/upload/utils.tsx#L76

**Comment by Xianbei233** [comment]
thanks

**Comment by Rustin-Liu** [comment]
I am working on it.
