### ISSUE TITLE
select 下拉框偏移错误

### ISSUE THREAD

**Issue by ShenganLee** [ant-design/ant-design#20367]
在 transform: scale 缩放后 select 下拉菜单偏移位置错误。地址https://stackblitz.com/edit/react-fidsr8
![select](https://user-images.githubusercontent.com/50688524/71247594-06692300-2354-11ea-9ffc-f0211bf7efec.png)

**Comment by jason19901028** [comment]
我也遇到同样的问题，弄了好久，通过看官方文档，最终解决了，用getPopupContainer，希望能有帮助@ShenganLee
![image](https://user-images.githubusercontent.com/25576700/89168942-27634900-d5b0-11ea-88c2-012cd1155ab7.png)
代码参考如下：
![image](https://user-images.githubusercontent.com/25576700/89169086-5974ab00-d5b0-11ea-8cbb-c722a7088ef6.png)
![image](https://user-images.githubusercontent.com/25576700/89169051-4cf05280-d5b0-11ea-808f-0184daf54664.png)

**Comment by ShenganLee** [comment]
多谢，问题已解决∠(｀ω´*)敬礼

DaiLinBo <notifications@github.com> 于 2020年8月3日周一 17:42写道：

**Comment by jing-wu** [comment]
是不是通过这种方式，能较好地让 antd 支持 scale 了？

**Comment by lijingyu1538** [comment]
我用的是4.6.1版本，按照这种方式没有生效呢😭

**Comment by RITAWONG** [comment]
我的做法是 getPopupContainer 结合一个反缩放的 dom。这样就不用写具体的css去调整偏移量了

**Comment by Flourad** [comment]
> 我的做法是 getPopupContainer 结合一个反缩放的 dom。这样就不用写具体的css去调整偏移量了

反缩放的dom，是怎么写的，请问有例子么？

**Comment by RITAWONG** [comment]
> > 我的做法是 getPopupContainer 结合一个反缩放的 dom。这样就不用写具体的css去调整偏移量了
> 
> 反缩放的dom，是怎么写的，请问有例子么？

大致思路是：
在被缩放后的dom下生成一个反向缩放的dom，所有的modal、tooltip等都通过全局的getPopupContainer生成到这个反向缩放的dom下。简单的例子没有，我是用在两三个复合项目中做解决方案时顺带写的这个。

**Comment by lh13140929** [comment]
> > > 我的做法是 getPopupContainer 结合一个反缩放的 dom。这样就不用写具体的css去调整偏移量了
> > 
> > 
> > 反缩放的dom，是怎么写的，请问有例子么？
> 
> 大致思路是： 在被缩放后的dom下生成一个反向缩放的dom，所有的modal、tooltip等都通过全局的getPopupContainer生成到这个反向缩放的dom下。简单的例子没有，我是用在两三个复合项目中做解决方案时顺带写的这个。

思路可以的，想问一下，两年了，那个目前有别的问题吗？

**Comment by shj065060117** [comment]
> > 我的做法是 getPopupContainer 结合一个反缩放的 dom。这样就不用写具体的css去调整偏移量了
> 
> 反缩放的dom，是怎么写的，请问有例子么？

这思路非常好，就是有点小问题，
![Uploading WX20240912-111510@2x.png…]()
