### ISSUE TITLE
Input.Search 在启用 allowClear 后，有内容输入时应隐藏放大镜icon

### ISSUE THREAD

**Issue by qwIvan** [ant-design/ant-design#20362]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/42zgl)

### Steps to reproduce
<Input.Search allowClear

### What is expected?
Input.Search 在启用 allowClear 后，有内容输入时隐藏放大镜icon

### What is actually happening?
在交叉icon和放大镜icon同时出现后，宽度会变宽

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 3.26 |
| System | Arch Linux |
| Browser | Chrome |

---
Input.Search 在启用 allowClear 后，有内容输入时应隐藏放大镜icon，否在当有内容输入后，出现的交叉icon与放大镜同时出现，会把宽度撑宽。

**Comment by xrkffgg** [comment]
这个放大镜的操作是查询啊，为啥要隐藏？

**Comment by afc163** [comment]
<img width="239" alt="image" src="https://user-images.githubusercontent.com/507615/71233906-f93b3c80-2331-11ea-863c-718ccb8c4349.png">

现在是符合预期的，我没发现宽度撑宽的问题。
