### ISSUE TITLE
RadioGroup是否可支持对其非直接子元素Radio的管理

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#2036]
## 场景
有时单选组可能存在更复杂的结构，如图：
![image](https://cloud.githubusercontent.com/assets/17123400/16034172/d6c54d64-3242-11e6-8f56-207450819090.png)
此时`<Radio>`标签不为`<RadioGroup>`的直接子元素，且组内`<Radio>`也不是兄弟元素

## 问题
此时RadioGroup无法对Radio进行管理，无法进行存取值及单选逻辑操作

## Demo
http://codepen.io/hyaaon/pen/WxwKpv?editors=1010

## 版本
antd@1.4.1

**Comment by afc163** [comment]
```jsx
<RadioGroup>
  <Radio>
    <Row><Col>复杂的结构</Col><Col>复杂的结构</Col></Row>
  </Radio>
  <Radio>
    <Row><Col>复杂的结构</Col><Col>复杂的结构</Col></Row>
  </Radio>
<RadioGroup>
```

**Comment by yiminghe** [comment]
是否可以 radiogroup 不管理数据？ @afc163 http://react-component.github.io/form/examples/radio-group.html

**Comment by afc163** [comment]
这个不冲突的，用户还是可以用 Radio 配合 rc-form 实现。

antd 里的 RadioGroup 只是简单场景的封装。
