### ISSUE TITLE
Custom validator and validateFields are not working together as expected

### ISSUE THREAD

**Issue by sklinov** [ant-design/ant-design#20361]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confident-goodall-4f0bx)

### Steps to reproduce
Click `validate` button on empty fields.

### What is expected?
I expect to form errors to appear as usual - red messages underneath and error messages in console. 
The `status` should be changed to `error` and shown below button.

### What is actually happening?
There's just a warning with errors in the console. `status` state is not changed.

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome 79.0.3945.79 |

**Comment by afc163** [comment]
Your codesandbox is empty.

**Comment by sklinov** [comment]
> Your codesandbox is empty.

Sorry, I forgot to save.
https://codesandbox.io/s/confident-goodall-4f0bx
Now it's good.

**Comment by afc163** [comment]
<img width="640" alt="image" src="https://user-images.githubusercontent.com/507615/71572699-56e23c80-2b1b-11ea-962d-3479f6897d67.png">

It works as your expectation?

**Comment by sklinov** [comment]
I got this issue fixed as said [here]( https://stackoverflow.com/questions/59449960/antd-custom-validator-and-validatefields-are-not-working-together-as-expected/59454750#59454750)
I needed an extra `value` check and `callback()`
