### ISSUE TITLE
AutoComplete的onSearch使用debounce还是触发多次

### ISSUE THREAD

**Issue by Sayid1** [ant-design/ant-design#20370]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-qmfng)

### Steps to reproduce
快速输入123

### What is expected?
3秒后打印3

### What is actually happening?
3秒后打印1 2 3

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.8 |
| System | macOS |
| Browser | chrome latest |

---
去掉受控是正常的

**Comment by Sayid1** [comment]
使用函数式组件

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-fb2uz

**Comment by JadeDruid** [comment]
这个issue的原因是啥？

**Comment by flycj** [comment]
最后怎么处理，我也遇到这个问题了

**Comment by flycj** [comment]
> 使用函数式组件

使用函数式组件也没解决
