### ISSUE TITLE
antd的动态表单校验顺序有问题

### ISSUE THREAD

**Issue by Sayid1** [ant-design/ant-design#20376]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-nmt66)

### Steps to reproduce
类型切换为手动输入，然后单击submit按钮

### What is expected?
设备名称输入框下面应该提示必填

### What is actually happening?
播放次数下面先提示了必填

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.8 |
| System | masOS |
| Browser | chrome latest |

---
设置了{ first: true }, 碰到第一个失败了的校验规则后停止校验

**Comment by Sayid1** [comment]
@chenshuai2144 帅哥看下撒

**Comment by zombieJ** [comment]
`conut` 先于 `dev` 注册，所以 first 先校验的 `count`，它和展示顺序无关。
