### ISSUE TITLE
Literally impossible for popovers to have margins

### ISSUE THREAD

**Issue by itayganor** [ant-design/ant-design#20378]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-t2dfo?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Have a Popover.
2. Try to apply margins to it using `overlayClassName` or `overlayStyle`.
3. Fail.

### What is expected?
I expect the margin to work as it should be.

### What is actually happening?
The `left` property is calculated against the margin value, meaning when I apply something like `margin-left: 16px` using `overlayClassName`, `left` will be equal to `THE_LEFT_I_WANT - 16px`.

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Latest Chrome |

---
In the reproduction, my goal is to have the popover arrow right beneath the menu icon. As you can see it's not the case by default, and I want to push the popover a bit from the left in order to achieve it.

**Comment by abdih** [comment]
I'm looking into this.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/11942#issuecomment-417195388

**Comment by itayganor** [comment]
> [#11942 (comment)](https://github.com/ant-design/ant-design/issues/11942#issuecomment-417195388)

I find this solution a bit weird. I don't think setting this kind of stuff inline is a good practice. Don't you think antd should allow the developer to use basic properties as margin?
