### ISSUE TITLE
Select in Input.Group icon not correct when hover

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#20371]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/input-cn/#components-input-demo-group](https://next.ant.design/components/input-cn/#components-input-demo-group)

![Kapture 2019-12-21 at 21 14 21](https://user-images.githubusercontent.com/14831261/71308379-e8282380-2436-11ea-9bc8-d903316c65e0.gif)
### Steps to reproduce
hover Select in Input.Group

### What is expected?
correct show icon

### What is actually happening?
not correct

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | 16.3 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by jyash97** [comment]
@shaodahong @afc163 I went on and created a fix for this. The issue was that for showing the border we are updating the z-index and the z-index of the arrow icon is not updated that's why it hides behind the container on hover and focus. Do check the PR if it makes sense.

**Comment by jyash97** [comment]
@zombieJ I think this issue can be closed now.
