### ISSUE TITLE
可编辑table里面请求接口会卸载掉该组件

### ISSUE THREAD

**Issue by jayguojianhai** [ant-design/ant-design#20389]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jayguojianhai/demo](https://github.com/jayguojianhai/demo)

### Steps to reproduce
直接再select里面搜索

### What is expected?
期望搜索完以后可以显示下拉列表并且输入框里面有搜索条件

### What is actually happening?
输入框里面没有搜索条件 下拉列表没有数据

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12.0 |
| System | macos Mojave 10.14.4  |
| Browser | Google Chrome 78.0.3904.70（正式版本）（64 位） |

**Comment by jayguojianhai** [comment]
https://github.com/jayguojianhai/demo写了呀，没法访问？

**Comment by jayguojianhai** [comment]
https://github.com/jayguojianhai/demo
写了呀，没法访问？

**Comment by yoyo837** [comment]
请优先尝试从 https://u.ant.design/codesandbox-repro 创建一个 **线上** demo来复现问题。

**Comment by jayguojianhai** [comment]
要加入dva，不知道怎么配置

**Comment by yoyo837** [comment]
灵活一点，dva的作用无非是对redux的封装，你把dva、redux都拆了，写常量代替，才是mini demo.

**Comment by yoyo837** [comment]
重点是table 而不是dva。

**Comment by jayguojianhai** [comment]
这个问题我猜是dispatch的时候更改了props，所以最好是要有dva

**Comment by jayguojianhai** [comment]
要不就跑下github里面的例子？谢谢啦

**Comment by jayguojianhai** [comment]
没人帮忙看看吗？

**Comment by zombieJ** [comment]
例子跑不起来，推测是使用问题。如果重现是 bug 再重开 issue。

<img width="485" alt="截屏2019-12-28下午10 20 16" src="https://user-images.githubusercontent.com/5378891/71544963-508b7d80-29c0-11ea-9794-e4a938b5f575.png">
