### ISSUE TITLE
QueueAnim导致的jQuery绑定失败

### ISSUE THREAD

**Issue by 4eyescat** [ant-design/ant-design#2038]
**问题描述**

QueueAnim导致内部的div无法用jQuery绑定change事件

**发生环境**

- antd 版本：1.4.1
- 操作系统及版本：win7 64
- 浏览器及版本：chrome
- 在线演示地址：

**重现步骤**

1. ...
2. ...

**线上重现演示**

http://codepen.io/anon/pen/pgdXYp?editors=001

**Comment by afc163** [comment]
你重现什么了。。。

另外，使用 React 就不要使用 jQuery 来绑定事件了。
