### ISSUE TITLE
TreeSelect treeCheckStrictly=true，通过表单setFieldsValue设置的选中节点不能显示节点的title

### ISSUE THREAD

**Issue by W1821** [ant-design/ant-design#20383]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-yvdf4)

### Steps to reproduce
打开重现连接，直接看到TreeSelect的显示不正常

### What is expected?
TreeSelect能显示2个设置的节点的title

### What is actually happening?
TreeSelect不能显示2个设置的节点的title

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.12 |
| System | windows 10 |
| Browser | Google Chrome  79.0.3945.88 （64 位） |

---

**Comment by afc163** [comment]
<img width="711" alt="image" src="https://user-images.githubusercontent.com/507615/71338607-84633f00-258b-11ea-9d45-aa355f22fd53.png">

https://codesandbox.io/s/antd-reproduction-template-gybye
