### ISSUE TITLE
InputNumber trigger change 2 time

### ISSUE THREAD

**Issue by duongkhoangiam** [ant-design/ant-design#20393]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number/](https://ant.design/components/input-number/)

### Steps to reproduce
In example at block 
```
Decimals
A numeric-only input box whose values can be increased or decreased using a decimal step. The number of decimals (also known as precision) is determined by the step prop.
```
When change first time i see log, and when i click any place in browser, trigger change call,
that mean , Trigger onChange two time when change

### What is expected?
Bug

### What is actually happening?
Need fix

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.12.0 |
| System | MacOs cataline |
| Browser | Chrome |

**Comment by afc163** [comment]
#9939
https://github.com/ant-design/ant-design/issues/15140
