### ISSUE TITLE
Table固定头和列的时候，不确定列宽情况下，设置了scroll.y的值之后，设置scroll.x:max-content无法自适应

### ISSUE THREAD

**Issue by lLeahDizon** [ant-design/ant-design#20397]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exciting-water-4ieuu?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
不设置列宽，设置scroll.x和scroll.y

### What is expected?
需要大量使用Table的时候，去给每一项设置列宽，而无法通过max-content自适应的话，处理起来会比较复杂

### What is actually happening?
设置了纵向滚动之后，再去给scroll.x设置max-content，不固定列宽，列就会被挤压

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | latest |
| System | windows |
| Browser | latest |

**Comment by lLeahDizon** [comment]
设置了tableLayout之后会出现内容穿透的情况

**Comment by afc163** [comment]
固定头/列必须设置列宽。

**Comment by afc163** [comment]
<img width="975" alt="图片" src="https://user-images.githubusercontent.com/507615/71361119-ef813580-25cc-11ea-909f-802c3fe74449.png">
