### ISSUE TITLE
4.0 smaller bundle size

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#20392]
### What problem does this feature solve?
- [ ] Replace `webpack` with `rollup`
- [ ] Remove loop style code in Grid

ref: #20356

**Comment by FortisFortuna** [comment]
Still an issue for me (worse actually) after upgrading to antd 4.0
![Screenshot from 2020-02-28 14-15-00](https://user-images.githubusercontent.com/33413876/75591498-ba61eb00-5a34-11ea-9796-328eb4cc9e4f.png)
![Screenshot from 2020-02-28 14-15-38](https://user-images.githubusercontent.com/33413876/75591530-cf3e7e80-5a34-11ea-82b2-f5363f3b8c71.png)

**Comment by zombieJ** [comment]
You need to enable TreeShaking to remove useless icons from webpack.

**Comment by afc163** [comment]
Close for no more actions to do.
