### ISSUE TITLE
升级1.4.1之后，报如下错误

### ISSUE THREAD

**Issue by babizhu** [ant-design/ant-design#2039]
invariant.js?568c:39Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

由于没有头绪，我也不知道该如何贴代码，见谅

**Comment by afc163** [comment]
试试 npm3

#2030

**Comment by babizhu** [comment]
秒回，谢谢，我马上试试看

**Comment by HelloListen** [comment]
我也遇到了这个问题，使用了npm3以后可以解决。

**Comment by babizhu** [comment]
换了npm3之后，由于我使用了react-router-redux，现在轮到这个组件报错了：
sync.js?dcab:104Uncaught TypeError: Cannot read property 'listen' of syncHistoryWithStore
头大
