### ISSUE TITLE
Need to pass table record data in table row component as one of props.

### ISSUE THREAD

**Issue by alex-knyazev** [ant-design/ant-design#20390]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature lets to have access to table record data while overriding row component of table

### What does the proposed API look like?
```
function TableTaskRow(props) {
  if (props.record.status ===  'closed') {
     // return  something else
  }
  return <tr {...props}>{props.children}</tr>;
}
```

**Comment by afc163** [comment]
React don't works in this way.

**Comment by YaNokk** [comment]
It's possible with onRow={(record, rowIndex) => {}} Table prop
