### ISSUE TITLE
关于treeSelect组件的selectable属性

### ISSUE THREAD

**Issue by zhangyuhuihh** [ant-design/ant-design#20399]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
tree node的属性描述错误：selectable变成了checkable

### What is expected?
是否可以使用checkable属性

### What is actually happening?
checkable属性不起作用，selectable属性起作用

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/20341

@wwwxy80s

**Comment by wwwxy80s** [comment]
之前的文档是selectable，我想实现父级checkbox不可选的效果，搜了半天试了半天都不成功(无论是我当前在用的比较旧的antd还是3.26.3版本都不行)
之后我去rc-tree看属性，发现selectable已经没有了（应该是看错了），有个checkable，试了下可以实现需要的效果，就把文档给替换了，然后昨天又试了下，才发现selectable代表的含义与checkable其实是不一样的。
按照上面的问题来看，selectable属性应该是有的，所以之前的修改其实不应该改selectable属性，而是新增checkable属性描述并且标注添加版本（还是说这个checkable属性没有打算暴露出来。。之前用antd的时候也遇到过一些属性有了但是也是在对应版本的doc里没写的情况）？

**Comment by zhangyuhuihh** [comment]
昨天记得早上看的还是selectable,我用这个属性用来使父级选项不可选。下午再看官网，忽然这个属性就没有了~找了下官网更新的记录好像也没有说明。去3.26.4和3.26.3的源码里面看了下，还是有selectable这个属性的。也正常可用

**Comment by afc163** [comment]
@wwwxy80s 可以把 selectable 加回来，selectable 和 checkable 应该是两个属性。

**Comment by wwwxy80s** [comment]
@afc163 好，之前是我理解错误了，以为checkable替代了selectable。我去检查一下checkable是什么时候添加的，感觉最好标一下版本

**Comment by afc163** [comment]
应该是 3.17.0：https://ant.design/changelog-cn#3.17.0 ，漏更新了 TreeSelect 的文档。

https://github.com/ant-design/ant-design/pull/16369

**Comment by zhangyuhuihh** [comment]
贼了，关我pr的大佬感觉没有认真看我这个问题出现的情境啊~T.T

**Comment by zombieJ** [comment]
原来是有的改没了，先合了。我再开一个 issue 跟一下样式。
