### ISSUE TITLE
fixed table header and body do not scroll together some times

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#20405]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-mountain-v9bd2)

### Steps to reproduce
横向滚动头部或者主体，另一边不跟随滚动

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest, Firefox latest， |

**Comment by afc163** [comment]
https://codesandbox.io/s/withered-fire-2fcft

目前还是需要手动加 `scroll.x` 才行。
