### ISSUE TITLE
mentions 在form中使用无法重置表单

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#20407]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/mentions-cn/#components-mentions-demo-form](https://ant.design/components/mentions-cn/#components-mentions-demo-form)

### Steps to reproduce
1.输入字符，点击reset

### What is expected?
表单重置

### What is actually happening?
表单无法重置

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | x |
| System | win10 |
| Browser | chrome 79 |

**Comment by shaodahong** [comment]
Ref: #20005
