### ISSUE TITLE
IE中报Object.assign is undefined错误

### ISSUE THREAD

**Issue by zzuwzj** [ant-design/ant-design#2041]
IE内核的浏览器还不支持Object.assign，但我用webpack打包出来的代码中__extends已经都被替换成_Object.assign_了，不知道是什么情况？

**Example**:
源码：
.../antd/lib/date-picker/locale/zh_CN.js  line#7 & line#24
```
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
...
var locale = _extends({}, _zh_CN2["default"]);
```
打包后：(line#7 没了，extends被替换了）
`var locale = Object.assign({}, _zh_CN2["default"]);`

IE无法执行，页面空白。。。

## 本地环境信息

- antd 版本: 1.3.0
- 浏览器及其版本: IE内核类浏览器

**Comment by afc163** [comment]
在你的工作流，忽略 node_modules/antd 下面的代码，这里是已经处理过的代码了。

另外这个不是 antd 问题呀，尽量到 webpack 和 babel 相关论坛提问吧~ 感谢支持。
