### ISSUE TITLE
Tree组件的onDrop拖拽事件，鼠标拖动元素时，无法触发鼠标滚动事件

### ISSUE THREAD

**Issue by kathy-ping** [ant-design/ant-design#20410]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
应用场景中，列表内容很多，在元素的上下拖拽过程中，如果有鼠标滚动事件，那么可以轻松的将拖拽节点放到目标位置，目前鼠标按下拖拽元素后，由于无法触发鼠标滚动事件，导致了拖拽功能不够灵活，甚至无法实现。

### What does the proposed API look like?
请大神指导

**Comment by PWDream** [comment]
我也遇到同样的问题了，请问怎么解决？
