### ISSUE TITLE
getPopupContainer返回为null或undefined时，程序会报错。

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#20416]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://none.com 暂时没有](http://none.com 暂时没有)

### Steps to reproduce
getPopupContainer返回为null或undefined时，程序会报错。

### What is expected?
getPopupContainer这里能不能兼容下返回值为空的情况，返回为空的话，默认使用document.body。谢谢。
应用自己判空不是很方便。（findDOMNode在render里用不了；ref有时候以为有hoc也不太方便使用）

webpack:///./node_modules/_rc-trigger@3.0.0-rc.3@rc-trigger/es/index.js?f530
```
var mountNode = props.getPopupContainer ? props.getPopupContainer(findDOMNode(_this5)) : props.getDocument().body;
mountNode.appendChild(popupContainer);
```

### What is actually happening?
getPopupContainer返回为null或undefined时，程序会报错。

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.9.0 |
| System | mac |
| Browser | all |

**Comment by wufeng87** [comment]
错误堆栈
```
react-dom.development.js:11365 Uncaught TypeError: Cannot read property 'appendChild' of undefined
    at Object.getContainer (index.js?f530:665)
    at Portal.createContainer (Portal.js?3aef:56)
    at Portal.componentDidMount (Portal.js?3aef:37)
    at commitLifeCycles (react-dom.development.js:20049)
```

**Comment by afc163** [comment]
可以给 rc-trigger 发个 PR。
