### ISSUE TITLE
datePicker mode为year时无法选中当前面板第一个年份和最后一个年份会触发翻页

### ISSUE THREAD

**Issue by sensao** [ant-design/ant-design#20429]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-lntg7)

### Steps to reproduce
点开年份组件面板的第一个年份和最后一个年份，通过onPanelChange、onChange无法获取到选中年的值

### What is expected?
能正常获取组件面板的第一个年份和最后一个年份

### What is actually happening?
触发翻页无法关闭面板，无法获取值

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
> 点开年份组件面板的第一个年份和最后一个年份

这个相当于翻页，并不是选择行为。
