### ISSUE TITLE
Create a tool that will generate a namespaced Ant Design set of components to allow for easy overriding

### ISSUE THREAD

**Issue by charlex** [ant-design/ant-design#20428]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For those of who don't want to directly use Ant Design, it would be helpful if we could simply generate an organized module that has all of Ant's components with a namespace.

### What does the proposed API look like?

I use a snippet in VSCode to do this for me, but it would be helpful to have a push button solution. This is my vscode snippet:

```
{
	"Namespaced AntD": {
		"prefix": "antdnamespaced",
		"body": [
			"import { $1 } from 'antd';",
			"",
			"export const MyNamespace$1 = $1;",
		]
	}
}

``` 

Which generates:

```
import { XYZ } from 'antd';

export const MyNamespaceXYZ = XYZ;
```

Which I can then override if I need to:

```
// It's not always so easy to import the XYZProps, but this is for illustration purposes
import { XYZ, XYZProps } from 'antd';

export const MyNamespaceYZ = ({ ...props }: XYZProps & { customProp?: string; }) => {
  /* my custom logic */
  if (customProp) {
    doABC();
  }
  return <XYZ {...props} />
};
```

**Comment by afc163** [comment]
Feel free to create tool you describe and I would like to recommend in antd site. 😊

**Comment by charlex** [comment]
@afc163 Thanks!
