### ISSUE TITLE
TreeSelect 与后端一起做模糊筛选 筛选后的数据treeData被更新了  但是没有重新渲染出来列表

### ISSUE THREAD

**Issue by zhenzhen-H** [ant-design/ant-design#20420]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
使用TreeSelect与后端一起做模糊查询 根据用户输入发送给后端 后端模糊查询返回列表 之后前端再次setState 列表的值 渲染出列表

### What is expected?
模糊查询之后渲染出新拿到的列表

### What is actually happening?
在进行模糊查询之后列表是空的

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 2.23.1 |
| System | mac |
| Browser | 79.0.3945.88 |

---
<FormItem style={{ float: 'left', width:'100%' }}  label={`架构域`}>
                  {getFieldDecorator(`domainsId`, {
                    rules: [{
                      required: false,
                    }],
                    // initialValue: "1",
                  })(
                    <TreeSelect
                      showSearch
                      onSearch={this.onSearch}
                      style={{ width: 150 }}
                      dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
                      treeData={this.state.BUList}
                      placeholder="请选择"
                      treeDefaultExpandAll
                      // onChange={this.onChange}
                      allowClear={true}
                      treeDefaultExpandAll={false}
                    >
                    </TreeSelect>
                    )}
                    {console.log(this.state.BUList,'this.state.BUList')}
                </FormItem>
进行模糊查询之后这个地方的BUList是有数据的  但是列表展示是空的

  onSearch = (searchValue) => {
   ......
//调接口从后端拿到数据并setState
        this.setState({
          BUList: [...result.data]
        }); 
   
  }

**Comment by zhenzhen-H** [comment]
https://codesandbox.io/s/antd-reproduction-template-4tfo5?fontsize=14&hidenavigation=1&theme=dark

**Comment by zhenzhen-H** [comment]
https://codesandbox.io/s/antd-reproduction-template-4tfo5?fontsize=14&hidenavigation=1&theme=dark 这个可以访问吗

**Comment by yoyo837** [comment]
It don't work.

**Comment by ZeroJsus** [comment]
遇到了一样的问题 key 都是唯一的 不知道怎么进行解决

**Comment by waylon-gmail** [comment]
一样的问题。 onSearch发网络请求后更新treeData，页面不会渲染。

**Comment by waylon-gmail** [comment]
有办法了，使用 treeNodeFilterProp="key"， 把 "wm"与"我们"，都拼接到key上，就可以了。

**Comment by huangtiti** [comment]
我也一样，把treeNodeFilterPro设置为title可以解决，我的title是名称

**Comment by jackywq** [comment]
> 有办法了，使用 treeNodeFilterProp="key"， 把 "wm"与"我们"，都拼接到key上，就可以了。

实测有用 @waylon-gmail

**Comment by codeusb** [comment]
> 有办法了，使用 treeNodeFilterProp="key"， 把 "wm"与"我们"，都拼接到key上，就可以了。

有用
