### ISSUE TITLE
当父组件为 DirectoryTree 时，TreeNode 设置自定义 icon 后还显示默认的图标

### ISSUE THREAD

**Issue by baizn** [ant-design/ant-design#20422]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
父组件换成 DirectoryTree 后表现完全同 https://github.com/ant-design/ant-design/issues/20090

### What is expected?
不展示默认的 Icon

### What is actually happening?
展示默认的 Icon
![image](https://user-images.githubusercontent.com/9443867/71412285-ff118480-2687-11ea-9e32-2af9a7acc314.png)

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 0.16.x |
| System | mac |
| Browser | chorme最新 |

**Comment by yoyo837** [comment]
#20456 fixed this?

**Comment by afc163** [comment]
线下沟通不存在这个问题。
