### ISSUE TITLE
Select base usage disappear default select when input

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#20421]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/select/#components-select-demo-basic](https://next.ant.design/components/select/#components-select-demo-basic)

![Kapture 2019-12-24 at 19 41 43](https://user-images.githubusercontent.com/14831261/71411776-b8228f80-2685-11ea-9bcb-b83315ccc521.gif)

### Steps to reproduce
1. active select
2. input some character
3. select option disappear

### What is expected?
don't disappear

### What is actually happening?
disappear

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | 16.3 |
| System | windows 10 |
| Browser | chrome 75.0.3770.100  |

**Comment by shaodahong** [comment]
Maybe cause #20394

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/20229#issuecomment-565284231
