### ISSUE TITLE
local development losing styles

### ISSUE THREAD

**Issue by YumcoderCom** [ant-design/ant-design#20426]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://e4ba9bab-f5cb-46b3-9455-15925b40f082.ws-eu01.gitpod.io/](https://e4ba9bab-f5cb-46b3-9455-15925b40f082.ws-eu01.gitpod.io/)

### Steps to reproduce
click on gitpod button in the GitHub page 
also in local development I got the same result

### What is expected?
component loaded in a stylish format

### What is actually happening?
the css is not loaded

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | any |
| System | ubuntu 18.04 |
| Browser | chromium |

---
https://github.com/ant-design/ant-design/issues/20414

**Comment by afc163** [comment]
@svenefftinge

**Comment by afc163** [comment]
Mabye you should ask for help in https://github.com/gitpod-io/gitpod/issues

**Comment by YumcoderCom** [comment]
I got the same result in local development

**Comment by afc163** [comment]
I reproduce in my machine, strange issue and no clue now.

**Comment by YumcoderCom** [comment]
result of  runing in my machine (ubuntu):

![image](https://user-images.githubusercontent.com/29568969/71445118-30439080-272c-11ea-8ff5-c33212226784.png)

**Comment by YumcoderCom** [comment]
base on lesscss.org:
![image](https://user-images.githubusercontent.com/29568969/71446068-c976a500-2734-11ea-8d16-89fac64a03d7.png)

I guess the problem is related to missing the following line:
```
<script src="//cdnjs.cloudflare.com/ajax/libs/less.js/3.9.0/less.min.js" ></script>
```

![image](https://user-images.githubusercontent.com/29568969/71446061-b82d9880-2734-11ea-8d35-6c251e6d04dd.png)

after adding the script to site/theme/static/template.html I got the following error:

![image](https://user-images.githubusercontent.com/29568969/71446152-73eec800-2735-11ea-8b7f-0123db34bb59.png)

then I add the following code:

![image](https://user-images.githubusercontent.com/29568969/71446355-9550b380-2737-11ea-9d09-e881c3e39595.png)

 and finally, styles loaded but:
1- as shown in the below image, and by comparing with original site styles still have problem 
2- inline javascript option is deprecated

![image](https://user-images.githubusercontent.com/29568969/71446399-16a84600-2738-11ea-95dd-2598f69d28ac.png)

**Comment by afc163** [comment]
```
+ bisheng@1.4.6
```
