### ISSUE TITLE
Is Select.onChange called before Select.onSelect so intentionally designed?

### ISSUE THREAD

**Issue by Hughen** [ant-design/ant-design#20423]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-dew-3ub50)

### Steps to reproduce
`3.20.3` and before: https://codesandbox.io/s/heuristic-dew-3ub50
after `3.20.3`: https://codesandbox.io/s/ecstatic-kapitsa-q5xgw

### What is expected?
`Select.onChange` is called after `Select.onSelect` which same as `3.20.3` and before.

### What is actually happening?
The version after `3.20.4` is not the same as the version before `3.20.3`, and I traced all calls of `ant-design` codes and found that this was caused by a change in the order of `rc-select` calls, but there is no explanation here.
**Is this a bug?**

| Environment | Info |
|---|---|
| antd | 3.20.4 and 3.20.3 |
| React | 16.7.0 |
| System | Linux 4.12.6-041206-generic |
| Browser | Chrome 77.0.3865.120 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/17664

https://github.com/ant-design/ant-design/issues/17630#issuecomment-511258424

Yes, it is a intented behavior.
