### ISSUE TITLE
关于mentions组件的getPopupContainer问题

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#20430]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-elion-bd7mk?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
输入@

### What is expected?
下拉框显示

### What is actually happening?
下拉框不显示

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | x |
| System | win10 |
| Browser | chrome 79 |

---
mentions组件如果使用全局的trigger.parentNode的话，下拉框不显示，mentions组件的getPopupContainer配置有什么最佳实践吗，可以补到文档里

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/mentions/pull/12
