### ISSUE TITLE
按需加载 当style设置为 true时 没有加载样式

### ISSUE THREAD

**Issue by dxd1102** [ant-design/ant-design#20431]
`
  fixBabelImports('import', {
    libraryName: 'antd',
    libraryDirectory: 'es',
    style: true ---> 设置为'css' 时样式没有问题，设置为true时 样式无法加载。
  }),
  addLessLoader({
    modifyVars: {
      '@primary-color': '#1DA57A',
      "brand-primary": "#FCC900"
    },
    javascriptEnabled: true,
  })
`

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by NAMANANAS** [comment]
请问解决了吗
