### ISSUE TITLE
fix @ant-design/icons@4.0.0-alpha.13 icons size

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20437]
`@ant-design/icons@4.0.0-alpha.13` 已经对 `4.0-prepare` snapshot 产生影响了。先合了。再开个 PR 来修一下部分图标的大小。 @vagusX

_Originally posted by @zombieJ in https://github.com/ant-design/ant-design/pull/20427#issuecomment-568829052_

**Comment by vagusX** [comment]
我跟设计师对下看看是重画这几个图标，还是继续维持现在的处理通过 font-size 来控制

**Comment by vagusX** [comment]
icons-svg 回滚了，这边同步这个回滚 https://github.com/ant-design/ant-design-icons/pull/213

**Comment by afc163** [comment]
这十几个图表 @vagusX @zombieJ 记得后续推进设计师重绘完把 viewbox 改成一致。
