### ISSUE TITLE
next.ant.design header postion abnormal when locale English

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#20445]
### Reproduction link
https://next.ant.design/components/button/

![image](https://user-images.githubusercontent.com/14831261/71440454-190aa000-2738-11ea-84f4-2ce5135abc8c.png)

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | 16.3 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by afc163** [comment]
空间不太够了。

**Comment by zombieJ** [comment]
Thanks for reply. Adjust Home page.
