### ISSUE TITLE
Drawer can't scroll 

### ISSUE THREAD

**Issue by and2352000** [ant-design/ant-design#20447]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/tree/master/components/drawer](https://github.com/ant-design/ant-design/tree/master/components/drawer)

### Steps to reproduce
Create a long list in Drawer and try to scroll.

### What is expected?
when the list is too long I can scroll down.

### What is actually happening?
It stuck

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | react 16.8.4 |
| System | ubuntu  18.04 |
| Browser | chrome |

**Comment by and2352000** [comment]
It work on version 3.23.1

**Comment by jvaclavik** [comment]
I noticed a similar issue in `4.0.0-rc1`. Sometimes you can't scroll after the situation when the drawer was opened.

**Comment by monolithed** [comment]
`@5.21.2` same
