### ISSUE TITLE
DatePick日期选择组件，希望能提供一个API，用来禁用掉输入框的输入功能，日期只能通过点选来获取

### ISSUE THREAD

**Issue by xuanxuan321** [ant-design/ant-design#20442]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
手机端的页面用antd来写，当选日期的时候，在输入框可以输入的时候，会自动唤起键盘，导致日期不好点选

### What does the proposed API look like?
disableInput   
true：可以手动输入日期  
false：不能手动输入，只能点选

**Comment by aLIEzsss4** [comment]
迫切需要这样的api支持

**Comment by puppyer** [comment]
当showTime=true的时候，虽然用disabledTime来禁选了部分时间，但是在DatePicker的输入框是可以输入这些被禁掉的时间的。
希望有一个属性来禁用用户的输入

**Comment by laokey** [comment]
同楼上，需要禁止用户手动输入，只能通过面板选择时间，否则disabledTime禁用的时间就不起作用了
![image](https://user-images.githubusercontent.com/13959383/72581285-cb89e900-3919-11ea-94cd-3d58c36e6bc4.png)

**Comment by aLIEzsss4** [comment]
在官方正式添加api之前，可以这么实现：
```javascript
const getPopupContainer = trigger =>{
  trigger.querySelector('input').setAttribute("readOnly", "")
  return trigger
}
```

**Comment by xuanxuan321** [comment]
@aLIEzsss4 你加的那段代码要放在组件的什么地方呢？方便提供一个结合组件的demo吗，感谢🙏

**Comment by yoyo837** [comment]
@aLIEzsss4 
`getCalendarContainer` 吧？

**Comment by afc163** [comment]
我们可以加个 `inputReadonly` 属性。

**Comment by afc163** [comment]
We already support `inputReadonly` now: https://codesandbox.io/s/thirsty-sea-8758l

Documentation is needed.
