### ISSUE TITLE
4.0.0-bata.0版本Input组件在safari下无法输入中文

### ISSUE THREAD

**Issue by devforma** [ant-design/ant-design#20452]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sad-herschel-kq0qp)

### Steps to reproduce
切换中文输入法，输入框输入中文

### What is expected?
输入框能输入中文

### What is actually happening?
输入中文后输入框为空

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | 16.12.0 |
| System | macOS 10.15.2 |
| Browser | safari 13.0.4 |

---
试了系统自带的中文输入法和搜狗输入法，输入中文的时候都不行，输入英文、数字、标点等都没问题
chrome下测试没这个问题

另外发现输入框先输入英文，接着输入中文是可以的

附带测试的截图（输入法的文字候选框没截到）
![capture](https://raw.githubusercontent.com/devforma/clouddisk/master/uPic/2019-12-26-10.04.00.gif?token=AA2PEQTVEKIPMWU4YXBKY6C6AQNR2)

**Comment by afc163** [comment]
确实输入不了。

另外，在 Firefox 下，例子里最后的 Textarea 疯狂闪动。
