### ISSUE TITLE
Filter in select multiple or tags mode works failed

### ISSUE THREAD

**Issue by FINAs** [ant-design/ant-design#20453]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-cartwright-jcow6)

### Steps to reproduce
type "1"  in the select box

### What is expected?
Show all options related with "1"

### What is actually happening?
Only show the "12"

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | lastest |
| System | windows 10 |
| Browser | chrome |

---
The options array is set  ["123", "12", "1","11"].
By the way,it there any function for filter sort like "1" then show ["1","11","12","123"]

**Comment by plainnany** [comment]
you should set Option value={datasource[i]}

**Comment by afc163** [comment]
https://codesandbox.io/s/keen-water-v9cn3

**Comment by FINAs** [comment]
Solved. Thanks a lot
