### ISSUE TITLE
Modal component breaks Transitions in Concurrent Mode.

### ISSUE THREAD

**Issue by qq181621732** [ant-design/ant-design#20459]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-shtern-4qcex)

### Steps to reproduce
Click open profile button.

### What is expected?
React will let it stay on the previous screen, and show a progress indicator there. 

### What is actually happening?
React will go to Receded state immediately.

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | experimental |
| System | win10 |
| Browser | chrome 79.0.3945.88 |

---
It's ok when we use ReactDom.createPortal.

**Comment by afc163** [comment]
Duplicate of #13308
