### ISSUE TITLE
Tree 组件 全部反选后 勾选框 不能恢复

### ISSUE THREAD

**Issue by MysteriousRookie** [ant-design/ant-design#2045]
const { Tree,Modal,Button } = antd;
const TreeNode = Tree.TreeNode;

const x = 3;
const y = 2;
const z = 1;
const gData = [];

const generateData = (_level, _preKey, _tns) => {
const preKey = _preKey || '0';
const tns = _tns || gData;

const children = [];
for (let i = 0; i < x; i++) {
const key = ${preKey}-${i};
tns.push({ title: key, key });
if (i < y) {
children.push(key);
}
}
if (_level < 0) {
return tns;
}
const level = _level - 1;
children.forEach((key, index) => {
tns[index].children = [];
return generateData(level, key, tns[index].children);
});
};
generateData(z);
const App = React.createClass({
getInitialState() {
return { 
visible: false,
expandedKeys: [],
autoExpandParent: true,
checkedKeys: ['0-0-0'],
};
},
onExpand(expandedKeys) {
this.setState({
expandedKeys,
autoExpandParent: false,
});
},
onCheck(checkedKeys) {
this.setState({
checkedKeys,
});
},
showModal() {
this.setState({
expandedKeys: ['0-0-0', '0-0-1'],
checkedKeys:['0-0-0'],
visible: true,
});
},
handleOk() {
this.setState({
visible: false,
});
},
handleCancel(e) {
this.setState({
visible: false,
});
},
render() {
const loop = data => data.map((item) => {
if (item.children) {
return (

{loop(item.children)}

);
}
return ;
});
return (

ShowModal

expandedKeys={this.state.expandedKeys}
autoExpandParent={this.state.autoExpandParent}
onCheck={this.onCheck} 
checkedKeys={this.state.checkedKeys}
>
{loop(gData)}

);
}
});
ReactDOM.render(, document.getElementById('container'));

在非全部反选的情况下 重新打开 模态框 没有问题。 如果全部反选 重新打开模态框 就会变成全部反选状态
你可以 直接 paste 到 http://codepen.io/anon/pen/wGOWGW?editors=001 里面 RUN 一下就可以重现了

**Comment by afc163** [comment]
为何重复提 issue？duplicate #2032

**Comment by MysteriousRookie** [comment]
没人 answer  我，就又发了一遍，我就想知道 是不是 框架本身的问题
