### ISSUE TITLE
Tree component demo about draggable description is not right 

### ISSUE THREAD

**Issue by plainnany** [ant-design/ant-design#20455]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#components-tree-demo-draggable](https://ant.design/components/tree-cn/#components-tree-demo-draggable)

### Steps to reproduce
```
if (!info.dropToGap) {
      // Drop on the content
      loop(data, dropKey, item => {
        item.children = item.children || [];
        // where to insert 示例添加到尾部，可以是随意位置
        item.children.push(dragObj);
      });
    } else if (
      (info.node.props.children || []).length > 0 && // Has children
      info.node.props.expanded && // Is expanded
      dropPosition === 1 // On the bottom gap
    ) {
      loop(data, dropKey, item => {
        item.children = item.children || [];
        // where to insert 示例添加到尾部，可以是随意位置
       // **这里描述应该是  示例添加到头部，可以是随意位置**
        item.children.unshift(dragObj);
      });
    } else {
      let ar;
      let i;
      loop(data, dropKey, (item, index, arr) => {
        ar = arr;
        i = index;
      });
      if (dropPosition === -1) {
        ar.splice(i, 0, dragObj);
      } else {
        ar.splice(i   1, 0, dragObj);
      }
    }

```

### What is expected?
else if 那里，应该是 where to insert 示例添加到**头部**，可以是随意位置

### What is actually happening?
描述为：**where to insert 示例添加到尾部，可以是随意位置**

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | latest |
| System | Mac OS 10.14.2 |
| Browser | chrome 77.0.3865.120 |

**Comment by afc163** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/507615/71457353-7c4c0f00-27d8-11ea-81ce-149f3afeaeda.png">

PR welcome~
