### ISSUE TITLE
antd 4.0 table no support IE11?

### ISSUE THREAD

**Issue by Nokecy** [ant-design/ant-design#20469]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 
![image](https://user-images.githubusercontent.com/12318131/71467564-39049700-27fe-11ea-9639-2a95bbcf268f.png)

**Comment by afc163** [comment]
antd 4.0 依然会支持 IE11，只是一些高级特性会降级处理。
