### ISSUE TITLE
tabs的tabPosition="left/right"失效，一直都横向，官网demo也这样

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#2046]
如题

**Comment by dyf2015** [comment]
啥时候发新版。。

发自我的 iPhone

在 2016年6月15日，11:34，偏右 <notifications@github.com<mailto:notifications@github.com>> 写道：


Closed #2046<https://github.com/ant-design/ant-design/issues/2046> via 9f132f6<https://github.com/ant-design/ant-design/commit/9f132f63aac832d681ab2f5eccbe449ea64404d6>.

―

**Comment by afc163** [comment]
预计明天。

**Comment by dyf2015** [comment]
谢了！
