### ISSUE TITLE
treeselect能否实现点击父节点文字展开该节点

### ISSUE THREAD

**Issue by jtc23** [ant-design/ant-design#20462]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
实现点击父节点文字展开该节点

### What does the proposed API look like?
点击父节点不会直接选中父节点而是展开下一层

**Comment by afc163** [comment]
目前不支持。这个交互比较复杂也不统一，预计暂时没有计划支持。
