### ISSUE TITLE
select mode="tags" 优化

### ISSUE THREAD

**Issue by smallbaoo** [ant-design/ant-design#20465]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
很多时候，用tags模式的时候，我们希望的是能够自定义选项，但是，不希望展开下拉菜单,
于是，就设置open属性为false，但是此时，之前的默认选中第一个的回车事件已经无效了，
于是改变了一些思路，给下面的选项设置隐藏，但是，这任然存在问题，会默认选中第一个，输入值回车生产确实也没有问题了，
但是问题出现在了：不输入值的时候（因为此时默认选中了第一个选项），此时的回车会取消掉选中的数据，看到的结果就是，一直回车就会一直删掉前面所选中的值。

### What does the proposed API look like?
希望能够提供一个解决办法，或直接加上输入替代的回车事件

**Comment by smallbaoo** [comment]
https://codesandbox.io/s/antd-reproduction-template-50eyi?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
可以这样 hack：https://codesandbox.io/s/antd-reproduction-template-cexyt

**Comment by afc163** [comment]
- [ ] 我再去给 Select 加个优化，隐藏的 select dropdown 不再响应 enter 选择事件。

**Comment by smallbaoo** [comment]
谢谢您提供解决方案

**Comment by afc163** [comment]
Fixed in `rc-select@9.2.2`，现在你可以用更简单的方式来使用：https://codesandbox.io/s/antd-reproduction-template-bxvbt

**Comment by smallbaoo** [comment]
好的，谢谢

**Comment by goldEli** [comment]
> 可以这样 hack：https://codesandbox.io/s/antd-reproduction-template-cexyt

这样hack后， tags 不能删除了
