### ISSUE TITLE
tree控件有点对不齐

### ISSUE THREAD

**Issue by ziaochina** [ant-design/ant-design#20474]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
https://ant.design/components/tree-cn/

### What is expected?
对齐

### What is actually happening?
不齐

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | react |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/20456

**Comment by ArthurBZhou** [comment]
下面的不对齐和这个BUG里说的是一回事不？

![image](https://user-images.githubusercontent.com/4514193/126476440-97081397-d15e-41d6-a732-9d871b930134.png)
