### ISSUE TITLE
Default value of input component (Select) is not used while submitting Form

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#20475]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-cherry-1vuks)

### Steps to reproduce
- Click on submit button without selecting anything and check console (Form's `onFinish` method's data is logged)

### What is expected?
The data received in `onFinish` should reflect the `defaultValue` prop value in Select component (that is also displayed to the user)
`{ test: [1], test2: [], test3: [1] }`

- First the Select component must be initialised by the defaultValue provided.
- Then if `initialValues` prop is provided in Form then the value in Select should be replaced by that value 

### What is actually happening?
The data received in `onFinish` is not initialised with defaultValues as shown in UI: ```{test: undefined, test2: undefined, test3: [1]}```

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome (Version 78.0.3904.108) |

---
This behaviour is also present in other form inputs. 

The reason we are not using `initialValues` to set defaults is because our forms are dynamic and consists of different types of inputs (select, checkbox, etc) where each input type handles it's own defaults.

**Comment by afc163** [comment]
You should use Form `initialValues` instead of `defaultValue`.

**Comment by piyushk96** [comment]
There is  problem in using `initialValues`.
For e.g. if we are using `Form.List` that contains a complex form and we want some of the fields in  that form to have some default value then we can't assign it using `initialValues` in form because at that time we don't know how many items will going to be added

**Comment by afc163** [comment]
@zombieJ Any suggestion for @piyushk96 ?

Also we should remove all `defaultValue` usage in examples: https://next.ant.design/components/form-cn/

**Comment by zombieJ** [comment]
Form example with field binding do not provides the `defaultValue` usage sample.

For dynamic fields, maybe we can extend `add` function to support init values: https://github.com/react-component/field-form/blob/c677a9ea18d2568897ea1b9c7712c15f5fe81a52/src/List.tsx#L14

**Comment by afc163** [comment]
https://next.ant.design/components/form-cn/#components-form-demo-validate-static

**Comment by zombieJ** [comment]
These `Form.Item` not bind data. It's used for validate status demo.

**Comment by afc163** [comment]
It would mislead our users.

**Comment by zombieJ** [comment]
Hmmm. It's little strange if only these field use data bind. Remove firstly.

**Comment by bananatron** [comment]
I guess I don't understand the purpose of `defaultValue` if it's not going to be used for validation, but maybe I'm missing something.

<img width="673" alt="Screen Shot 2020-04-16 at 9 05 52 AM" src="https://user-images.githubusercontent.com/5759818/79459584-7c5b5f00-7fc1-11ea-98f5-2a8ed1e89122.png">

**Comment by yoyo837** [comment]
When you add input item into the Form and Form.Item and set a name for Form.Item, the input item is completely controlled by the Form. You need to use the Form's api to control the input item.

For the default value, you can use the `initialValues` in this case.

**Comment by ericzon** [comment]
do we have any update on this?  I have a form to create a resource. Editing the resource, there are some dropdown selections  that come from backend, for that reason I can't assign it using initialValues in form because as @piyushk96 said at that time we don't know how many items will going to be added

**Comment by piyushk96** [comment]
@ericzon you can probably load your form only after fetching initial data in edit case. Then you can use Form's initialValues prop.

**Comment by bennik88** [comment]
The solution you all are looking for is to set it in `<Form initialValues={{ yourDesiredFormInputName: true }} >`

**Comment by AzimShaikhIorta** [comment]
> 

Do you have any example or sandbox to show?

**Comment by iVapor** [comment]
What a stupid design!

**Comment by nanxiaobei** [comment]
> 

This does not solve the problem @piyushk96  mentioned

> if we are using Form.List that contains a complex form and we want some of the fields in that form to have some default value then we can't assign it using initialValues in form because at that time we don't know how many items will going to be added

**Comment by npanti** [comment]
Hey, 
I still have the same problem as @piyushk96.
I use a Select component in a dynamic form, similarly as in [antd doc here](https://ant.design/components/form#components-form-demo-dynamic-form-items). 
How can we define a default value when a new line is added to the form?

**Comment by rabiya-b** [comment]
Hey,

Any solution to this problem?
I am also having the same problem @npanti 
exactly the same functionality
