### ISSUE TITLE
[4.0]antd表格 summary 总结栏能够进行固定位置

### ISSUE THREAD

**Issue by zynyy** [ant-design/ant-design#20472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当数据较多的时候出现滚动条,希望能够一眼就看到表格的数据总结汇总，而不需要滚动到最下面,因为目前设计`<tfoot></tfoot>`是放在滚动的body内，3.0版本 在 `dataSource` 多插入 几条汇总也可以实现

### What does the proposed API look like?
```
<Table 
    components={{
        summary: {
          wrapper?: any;
          row?: any;
          cell?: any;
        }
   }}
/>
```

## 希望能达到下面的效果

![image](https://user-images.githubusercontent.com/28705449/71472738-2181da00-280f-11ea-95ee-48c4e589e0b7.png)

**Comment by NnnLillian** [comment]
附议

**Comment by MrSuperLi** [comment]
比较好的做法：汇总栏在表头下面；当表格滚动时，汇总栏可以跟表头一起sticky在页面顶部。

**Comment by afc163** [comment]
https://github.com/react-component/table/pull/618
