### ISSUE TITLE
Select auto-sized based on options width

### ISSUE THREAD

**Issue by thomaslc66** [ant-design/ant-design#20471]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature can improve the way select is displayed. For now the select width need to be set manualy. This feature would take all the options length and then render the width of the select based on the widthest of all options. Like this the width will not look weird when we have small names in large select width or big names in small select width.

### What does the proposed API look like?
(8* this.state.biggestValueOptions.length)   100

**Comment by afc163** [comment]
It is hard to detect which option is longest in a visual list select. We may not implement this feature.
