### ISSUE TITLE
I have a problem with customization

### ISSUE THREAD

**Issue by IgorSobol** [ant-design/ant-design#20476]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less)

### Steps to reproduce
// Input
// ---
@input-height-base: 32px;
@input-height-lg: 40px;
@input-height-sm: 24px;
@input-padding-horizontal: @control-padding-horizontal - 1px;
@input-padding-horizontal-base: @input-padding-horizontal;
@input-padding-horizontal-sm: @control-padding-horizontal-sm - 1px;
@input-padding-horizontal-lg: @input-padding-horizontal;
@input-padding-vertical-base: 4px;
@input-padding-vertical-sm: 1px;
@input-padding-vertical-lg: 6px;
@input-placeholder-color: hsv(0, 0, 75%);
@input-color: @text-color;
@input-border-color: @border-color-base;
@input-bg: @component-background;
@input-number-hover-border-color: @input-hover-border-color;
@input-number-handler-active-bg: #f4f4f4;
@input-number-handler-hover-bg: @primary-5;
@input-number-handler-bg: @component-background;
@input-number-handler-border-color: @border-color-base;
@input-addon-bg: @background-color-light;
@input-hover-border-color: @primary-5;
@input-disabled-bg: @disabled-bg;
@input-outline-offset: 0 0;

### What is expected?
Change according to variables

### What is actually happening?
Variables do not work

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | React 16.10.1 |
| System | Linux |
| Browser | Chrome |

---
Hello!
Now I am engaged in customization of ant design for my project. Before that, I figured out everything and everything works. But when I got to the input, I noticed that the variables did not work.
Buttons, text, etc. Everything is customizable normally and works.
All variables are here:
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less
But tees don't work:
// Input
// ---
@input-height-base: 32px;
@input-height-lg: 40px;
@input-height-sm: 24px;
@input-padding-horizontal: @control-padding-horizontal - 1px;
@input-padding-horizontal-base: @input-padding-horizontal;
@input-padding-horizontal-sm: @control-padding-horizontal-sm - 1px;
@input-padding-horizontal-lg: @input-padding-horizontal;
@input-padding-vertical-base: 4px;
@input-padding-vertical-sm: 1px;
@input-padding-vertical-lg: 6px;
@input-placeholder-color: hsv(0, 0, 75%);
@input-color: @text-color;
@input-border-color: @border-color-base;
@input-bg: @component-background;
@input-number-hover-border-color: @input-hover-border-color;
@input-number-handler-active-bg: #f4f4f4;
@input-number-handler-hover-bg: @primary-5;
@input-number-handler-bg: @component-background;
@input-number-handler-border-color: @border-color-base;
@input-addon-bg: @background-color-light;
@input-hover-border-color: @primary-5;
@input-disabled-bg: @disabled-bg;
@input-outline-offset: 0 0;

Who can tell what is the reason?

**Comment by keithort** [comment]
You need to change them in your `config-overrides.js` file with this module: https://www.npmjs.com/package/react-app-rewire-less

**Comment by IgorSobol** [comment]
Unfortunately I can’t show you the main project. But I created a mini-project with all the settings as on the main one. I also added an example with buttons there (button customization works).
And an example with inputs ... But customization with variables does not work there.
https://github.com/IgorSobol/custom-antdesign-themplate

I did everything like you asked or not?

**Comment by keithort** [comment]
@IgorSobol Follow the documentation to customize the theme: https://ant.design/docs/react/customize-theme#How-to-do-it

**Comment by IgorSobol** [comment]
> @IgorSobol Follow the documentation to customize the theme: https://ant.design/docs/react/customize-theme#How-to-do-it


Hello!
Sorry for the long reply, holidays ...

According to your answer - but I already did according to the documentation. Or do you mean something specific? Can you tell me why exactly these variables do not work? Vedas otherwise everything is working fine!

**Comment by keithort** [comment]
@IgorSobol Which approach did you implement to customize the theme? Did you try [these solutions](https://ant.design/docs/react/customize-theme#Not-working)?

**Comment by IgorSobol** [comment]
**Hello!**
I gave you a link to my approach.
Duplicate: `https://github.com/IgorSobol/custom-antdesign-themplate`

1. In `src/stylesheets/applications.less` I have an assembly of all the variables for customization.

2. For convenience, I divided customization into folders by component. For instance:
`src/components/input`
Here is the problem! I take from the example on your site variables for customizing inputs and nothing works. But when you try to immediately change the styles for the buttons (for example), everything works. Button styles also change through variables.

3. Also in my project I use styleguidist. How to quickly start a project I described in [Readme.md](https://github.com/IgorSobol/custom-antdesign-themplate/blob/master/README.md)


It turns out with my approach, only the inputs do not work .... Everything else works fine!

Can you describe in more detail what I'm doing wrong?

**Comment by keithort** [comment]
I'm not 100%, just spit-balling, but have you tried consolidating the variables to override in your `applications.less` file?

**Comment by IgorSobol** [comment]
In fact, yes ... 
But on my part, the idea was different. Namely, look from the other side. 
I am trying to split a large file with variables into logical components.

I have been using your project for a long time. And comparing it with other popular libraries, I can firmly say that this is number 1 :)

At the moment, I need to make a custom project using your variables for general customization. In the future, I will integrate it into others and already add my own styles for the necessary customization by design.

**Comment by keithort** [comment]
@IgorSobol I'm not a maintainer of Ant Design. Just dev trying to help another dev. 

Based on what you said, I think that is your issue. Doing a quick search and many of those variables are used in other components. You would need to set your values for the variables in the root `applications.less` and you create any custom rules in your component stylesheet.

**Comment by IgorSobol** [comment]
At the moment, the question can be considered closed. I found what was priin and corrected. In my approach, everything works as I wanted. Much later, I will be freed from work and will try to explain in more detail what the problem was and offer a solution.
Thanks for your help!
