### ISSUE TITLE
Select 控件默认选中必填校验

### ISSUE THREAD

**Issue by pigletfly** [ant-design/ant-design#2048]
Select 控件有默认选中值，设置rules为required，但是提交表单时提示要输入。
示例：
http://codepen.io/anon/pen/zBBYzd?editors=0010

**Comment by afc163** [comment]
你没有传校验的 type 啊，默认是 string。

- http://codepen.io/anon/pen/VjjwxV?editors=0010
- https://github.com/yiminghe/async-validator#type
