### ISSUE TITLE
Some typecript definition problems

### ISSUE THREAD

**Issue by capdiem** [ant-design/ant-design#20480]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[1](https://github.com/ant-design/ant-design/blob/4.0-prepare/components/form/FormItem.tsx#L21)

### What is expected?
Everythin goes fine

### What is actually happening?
1. Error: `Interface 'FormItemProps' incorrectly extends interface 'FieldProps'.Types of property 'children' are incompatible.`

    Should be:
    ```typescript
    import { FieldProps } from "rc-field-form/lib/Field";
    declare type RcFieldProps = Omit<FieldProps, "children">;
    export interface FormItemProps extends FormItemLabelProps, FormItemInputProps, RcFieldProps {...}
    ```

2. At rc-field-form\lib\interface.d.ts, `ValidateErrorEntity.errorFields` should be array, but it is object now

3. `RcTableProps<RecordType>['scroll].x(y)` type definition should be `number | true | string`

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.0 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google chrome |

**Comment by farzer** [comment]
因为没有把 `rc-field-form` 列在依赖清单导致 eslint `import/no-extraneous-dependencies` 是怎么解决的？
