### ISSUE TITLE
4.0 Form.Item chilren 添加其他元素异常

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#20481]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/field-form/blob/master/examples/basic.tsx#L31](https://github.com/react-component/field-form/blob/master/examples/basic.tsx#L31)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
```jsx
   <Form.Item name='demo' label='demo'>
       <div>
           <Input />
           <div>xxxx</div>
       </div>
   </Form.Item>
```
如果用 div 包起来，这里会有 value
![image](https://user-images.githubusercontent.com/7971419/71497194-13c16880-2892-11ea-960e-a39b19a70b9c.png)

而 field-form 的 demo 没有 
![image](https://user-images.githubusercontent.com/7971419/71497274-7a468680-2892-11ea-85dd-35d33f4b0d39.png)

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | last |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
这是对的，4.0 里 Form.Item 会默认给子元素添加 value 和 onChange 属性，相当于 3.0 的 `getFieldDecoretor()()`

**Comment by qq645381995** [comment]
> 这是对的，4.0 里 Form.Item 会默认给子元素添加 value 和 onChange 属性，相当于 3.0 的 `getFieldDecoretor()()`

```jsx
<Form.Item name="demo" label="demo">
    {control => (
        <div>
            I am render props
            <Input {...control} placeholder="render props" />
        </div>
    )}
</Form.Item>

```
但是这样写不行啊

**Comment by afc163** [comment]
Form 上有 onFieldsChange 和 onValuesChange 可以用。

**Comment by qq645381995** [comment]
我不是想要这个功能，我就是想给 Input Checkbox 等外面包一层 div，在 Form.Item 里面。类似于要做这个。
![image](https://user-images.githubusercontent.com/7971419/71497724-70258780-2894-11ea-9a63-13bc3f364699.png)

**Comment by afc163** [comment]
```
<Form.Item name="demo" label="demo">
    {control => (
        <div>
            I am render props
            <Input {...control} placeholder="render props" />
        </div>
    )}
</Form.Item>
```

你给的这种方式是对的。

**Comment by qq645381995** [comment]
> ```
> <Form.Item name="demo" label="demo">
>     {control => (
>         <div>
>             I am render props
>             <Input {...control} placeholder="render props" />
>         </div>
>     )}
> </Form.Item>
> ```
> 
> 你给的这种方式是对的。

好，那等着修复了。

**Comment by afc163** [comment]
修复啥？现在有什么问题？

**Comment by qq645381995** [comment]
![image](https://user-images.githubusercontent.com/7971419/71497948-651f2700-2895-11ea-94b1-2226c4977d0b.png)

现在会报错，并且不渲染组件。

**Comment by afc163** [comment]
给个重现。

**Comment by qq645381995** [comment]
https://codesandbox.io/s/aged-currying-7vg9p

**Comment by afc163** [comment]
@zombieJ 这种现在是不能使用是么，我看文档上没有透出。

**Comment by zombieJ** [comment]
嗯，FormItem 的状态依赖于子元素，所以带 `name` 的 FormItem 不支持 `renderProps`，因而文档里也不做透出。这种需求应该这么写：
```tsx
<Form.Item label="demo">
  <div>
    I am render props
    <Form.Item name="demo" noStyle>
      <Input placeholder="render props" />
    </Form.Item>
  </div>
</Form.Item>
```

ref: https://codesandbox.io/s/amazing-morse-slsok

**Comment by qq645381995** [comment]
我知道，但是 Form.Item 跟 children 强绑定，感觉可以放开。

**Comment by zombieJ** [comment]
例子里有 required 的使用示例，`noStyle` 的所有校验状态都会被提升至顶层 FormItem。
之前有考虑过是否开放 `Field` 组件，考虑这样组件过多会不好记忆，因而全合入 FormItem 中来。

**Comment by qq645381995** [comment]
> 例子里有 required 的使用示例，`noStyle` 的所有校验状态都会被提升至顶层 FormItem。
> 之前有考虑过是否开放 `Field` 组件，考虑这样组件过多会不好记忆，因而全合入 FormItem 中来。

嗯，有 noStyle 那 Form.Item 跟 children 强制绑定也没问题。只是怎么告诉用户， rules label name 要写在哪里？
感觉可以再拆个组件专门就是注册 field 的，更明确些
Form.Field

**Comment by zombieJ** [comment]
动态表单里其实有 `noStyle` 的示例：https://next.ant.design/components/form/?locale=en-US#components-form-demo-dynamic-form-item

考虑到 beta 版本没有重大问题 api 不会变动，Field 应该不会提供出来。现在的 `notStyle` 也是满足需求的。

**Comment by qq645381995** [comment]
ok

**Comment by afc163** [comment]
noStyle 要单独写个 demo。

**Comment by afc163** [comment]
noStyle 要单独写个示例，引导用户写非自定义组件方式的复杂表单项。

**Comment by qq645381995** [comment]
那其实这个就是个 bug 
![image](https://user-images.githubusercontent.com/7971419/71501387-36a94800-28a5-11ea-806c-be7b16d366d6.png)
![image](https://user-images.githubusercontent.com/7971419/71501393-3f9a1980-28a5-11ea-84a7-d54c15c7bb1a.png)

rerequired 的判断就不是 rules:[{required: true}] 而是 required={true}

**Comment by qq645381995** [comment]
```jsx
export default (props) => {
    const { name, rules, component, addonAfter, ...rest } = props;
    let _required;
    // 根据 rules required 判断外部 Form.Item 是否必填
    forEach(rules, item => {
        if ('required' in item) _required = item.required;
    });
    return (
        <Form.Item required={_required} {...rest}>
            <>
                <Form.Item noStyle name={name} rules={rules}>
                    {component}
                </Form.Item>
                {addonAfter}
            </>
        </Form.Item>
    );
};

```
这样 required 可以同步无感知。对于 children 只写一个  field 的。

**Comment by zombieJ** [comment]
`required` 属性是设置是否展示 *，和 `rules` 中的 `required` 不是同一个东东。

**Comment by qq645381995** [comment]
> `required` 属性是设置是否展示 *，和 `rules` 中的 `required` 不是同一个东东。

对于一个字段，想让它同步。多个的时候，就不管了。

![image](https://user-images.githubusercontent.com/7971419/71540349-2916bf80-2984-11ea-9fcc-003a13767116.png)

**Comment by qq645381995** [comment]
@zombieJ 还有个问题

```jsx
  <Form.Item {...tailLayout}>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
        <Button htmlType="button" onClick={onReset}>
          Reset
        </Button>
        <Button type="link" htmlType="button" onClick={onFill}>
          Fill form
        </Button>
      </Form.Item>
```

https://next.ant.design/components/form-cn/#components-form-demo-control-hooks

Form.Item 里面不能写多个元素。

        类型“Element[]”提供的内容与签名“(form: FormInstance): ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)>”不匹配。ts(2322)

**Comment by zombieJ** [comment]
嗯，没有 `name` 的时候的确没有必要 ReactElement。有兴趣来个 PR 不？

**Comment by qq645381995** [comment]
https://github.com/react-component/field-form/pull/51 这个都没看，心寒了。

**Comment by zombieJ** [comment]
哈哈，@ 我一下，消息实在太多了。

**Comment by qq645381995** [comment]
@zombieJ 刚尝试修改了发现 
![image](https://user-images.githubusercontent.com/7971419/71621619-575a0080-2c0b-11ea-8410-670df96bf563.png)
field-form 方法类型中有 control=> value、onChange。meta、最后才是 FormInstance，为什么 antd 的 form 把前面2个去掉了，真的没必要传吗？

FormItem 是否支持数组元素不重要，div 包一下就不报错，关键还是 `(control: ChildProps, meta: Meta, form: FormInstance)`

**Comment by qq645381995** [comment]
![image](https://user-images.githubusercontent.com/7971419/71621781-4e1d6380-2c0c-11ea-9f5a-fe88e4bda01e.png)
这样就不报错了。

**Comment by zombieJ** [comment]
* `rc-field-form` 提供的比较裸，antd 在此之上封装。因而有些 Field children 特地不做透出。
* `children` 应该是只有 `name` 属性不存在的时候才允许 `ReactElement[]` 类型。

**Comment by qq645381995** [comment]
有 name 才有 `ReactElement[] ` 这个类型要怎么写

**Comment by zombieJ** [comment]
```tsx
interface XXX1 {
  name: string | number | ...;
  children: ReactElement | ...;
}

interface XXX2 {
  // Without name prop
  children: ReactNode;
}

type XXXX = XXX1 | XXX2;
```

**Comment by qq645381995** [comment]
我觉得类型没必要拆分 2 个，可以判断如果是数组有 name 就 warning

**Comment by zombieJ** [comment]
也可以~

**Comment by qq645381995** [comment]
#20577

**Comment by qq645381995** [comment]
@zombieJ  

FormItem https://next.ant.design/components/form-cn/#Form.Item 这么多 api ，还是无法区分哪些要用在外部，哪些用在内部（有 noStyle）。

**Comment by afc163** [comment]
- 有 `name` 属性就可以关联管理 field，没有则不能。
- 其他属性都是一样的。

**Comment by qq645381995** [comment]
> * 有 `name` 属性就可以关联管理 field，没有则不能。
> * 其他属性都是一样的。

好吧，那就全给，只区分给不给 name

**Comment by qq645381995** [comment]
@afc163  发现了还有问题 😓
https://codesandbox.io/s/antd-reproduction-template-m3uhn

`omit(data, "name")` 外部只去除 name 会这样出现2个 warning 
这里是必须 `omit(data, "name", "rules")`  才会好，其他不知道还会存在什么问题。

**Comment by qinghua5453** [comment]
> required={true}

牛，完美解决了我的bug。

**Comment by nannan0109** [comment]
遇到了同样的问题，请问最后是怎么解决的 上面的方法都试过了 没起作用
