### ISSUE TITLE
Table组件设置横纵滚动并且有固定列时，固定列与表格会有些许错位

### ISSUE THREAD

**Issue by LoveXMin** [ant-design/ant-design#20495]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-4ukrhw](https://stackblitz.com/edit/react-4ukrhw)

### Steps to reproduce
打开链接可以看到两个table都出现了固定列与表格错位

### What is expected?
固定列与表格对齐

### What is actually happening?
固定列与表格有一个像素错位

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.9.0 |
| System | win64 |
| Browser | 谷歌最新版 |

---
1.当使用固定列,表头出现有换行时
a.表头内容换行出现在中间滚动区,出现左右固定列与表格有一个像素错位
b.表头内容换行出现在中间固定列,出现右固定列与表格有一个像素错位

**Comment by afc163** [comment]
Broken by https://github.com/react-component/table/commit/4aa8aa3a66b1b7c277a234b84c1bca2a06403ff5 and https://github.com/react-component/table/commit/1129f4345a6475f4bb65b848cd84a424e4190b71 ...

**Comment by afc163** [comment]
ref ant-design/ant-design#20126 and https://github.com/ant-design/ant-design/issues/20269

**Comment by afc163** [comment]
Fixed in rc-table@6.10.10, reinstall node_modules and try it.

**Comment by LoveXMin** [comment]
现在antd内置依赖rc-table版本已经升级,重新安装一下就能解决问题
