### ISSUE TITLE
[4.0] Select[size="small"] arrow padding is missing

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20490]
<img width="142" alt="image" src="https://user-images.githubusercontent.com/507615/71504047-c30e3780-28b2-11ea-859c-669928c4ff7d.png">

- ❌：https://codesandbox.io/s/black-fog-5vro4

**Comment by jyash97** [comment]
Hey @afc163  Can I look into this ?

**Comment by afc163** [comment]
@jyash97 sure
