### ISSUE TITLE
Error when using tooltip, popover and menu component while scrollbar is in drawer component

### ISSUE THREAD

**Issue by edrmsgl** [ant-design/ant-design#20501]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/popover/ use https://ant.design/components/drawer/ with https://www.npmjs.com/package/react-custom-scrollbars](https://ant.design/components/popover/ use https://ant.design/components/drawer/ with https://www.npmjs.com/package/react-custom-scrollbars)

### Steps to reproduce
The contents of the drawer component are too long and the reactor scrollbar custom component is active. No change

I shot a video, but I don't know how to send it

### What is expected?
Solution or solution suggestion

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.11.0 |
| System | windows |
| Browser | chrome |

---
-

**Comment by edrmsgl** [comment]
I'm sending you a case study, when there is a window scrollbar in the Drawer, when you hover over any of the components (Popover, Tooltip) and move the page down with the mouse scroll, the components do not move relative to the window scrollbar, but remain constant. Can you interpret this in other components?

https://codepen.io/Durmusoglu/pen/PowOmqV

Thank you

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-scrolls-with-the-page

**Comment by afc163** [comment]
Please read FAQ first before open issue.
