### ISSUE TITLE
InputNumber flicker issue on trying to change the value

### ISSUE THREAD

**Issue by adinnc** [ant-design/ant-design#20502]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number/](https://ant.design/components/input-number/)

### Steps to reproduce
    1) Use the 2nd Input group of InputNumbers
    2) Select the InputNumber value by double clicking on it and change the value
    3) Cursor will flicker in InputNumber field and value will not change until we move mouse or use touch pad to focus out

### What is expected?
It should change the value without any flicker

### What is actually happening?
It is not changing the value until & flicker will happen until we foucs out from the field

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.8.3 |
| System | Mac OS X 10.13.6 |
| Browser | firefox - 71 - 64bit |

**Comment by afc163** [comment]
Could you record a gif or video?

**Comment by adinnc** [comment]
> Could you record a gif or video?

![image](https://user-images.githubusercontent.com/4592445/71540010-ba793800-296a-11ea-90bd-e8b2eb5a236c.png)

**Comment by afc163** [comment]
I can't reproduce your problem in my machine.
