### ISSUE TITLE
In Modal, Disable Cancel Button Dynamically

### ISSUE THREAD

**Issue by sainipray** [ant-design/ant-design#20514]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In Modal,  If I click on Ok Button and promise waiting from server response this time we also have cancel button and user can easily click on cancel button, so we should have option, if user click on Ok button then cancel button should disable that time, because we can wok on one button at a time, 

Suppose we have functionality of delete something on server, user click first on Ok button then request went to server but in mean time user click on cancel, it's does nothing for us, Because request already gone, Cancel button only for Modal Close.

### What does the proposed API look like?
I didn't try any code regarding this, but I think, we should have attribute that should represent "processing" with True or False and we can pass through CancelButtonProps:

cancelButtonProps: {
      disabled: processing,
    },

**Comment by afc163** [comment]
```
          cancelButtonProps={{ disabled: this.state.processing }}
```
