### ISSUE TITLE
Wrong Notification Behavior if I use it in useEffect hook 

### ISSUE THREAD

**Issue by LittleboyHarry** [ant-design/ant-design#20513]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elastic-villani-95yd2)

### Steps to reproduce
1. 在组件中使用 react hooks 的 useEffect (use in a component)
2. 通过循环若干次调用 notification.open(call it for a few times)，其中 btn 属性自定义(set custom btn property)
3. 绑定(bind) btn 点击事件(click handle function)，点击后调用(call) notification.close(key)

### What is expected?
1. 每个通知框纵向分布，互不重叠 (show separately)
2. 每个自定义按钮都能独立关闭其对应的通知框 (I can close each notification by custom button dependently)

### What is actually happening?
1. 全部通知框堆在一起 (show stacked together)
2. 除了最顶层按钮能关闭通知框外，其他按钮点击没有任何反应 (I can only close the top notification, but not others)

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome 79 |

**Comment by zombieJ** [comment]
Fixed in v4 of #21531. Welcome volunteer help to fix on v3.
