### ISSUE TITLE
Tree控件异步加载，当叶子节点的children属性为null时，switcherIcon一直显示

### ISSUE THREAD

**Issue by mybedhome** [ant-design/ant-design#20511]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
https://ant.design/components/tree-cn/

### What is expected?
如果是叶子节点，或树节点的children属性为null，不应该显示switcherIcon图标

### What is actually happening?
只要在Tree控件配置了switcherIcon，所有树节点都会显示switcherIcon图标

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.2 |
| Browser | Chrome 79.0.3945.88 |

**Comment by xrkffgg** [comment]
我觉得可以在拿到数据的时候过滤到 `null` ，或者服务端的数据就不应该返回包含 `null`

**Comment by mybedhome** [comment]
> 我觉得可以在拿到数据的时候前端过滤 `null` ，或者服务端的数据就不应该返回包含 `null`

没用的，就算没有null，它也还是会显示

**Comment by CyfforPro** [comment]
据测试，这个问题跟异步加载无关，3.26.3及以上版本才有这个问题——只要在tree上自定义了switcherIcon，即使是叶子节点也会有那个switchIcon——
![image](https://user-images.githubusercontent.com/19570481/71948521-3a28c180-320b-11ea-845f-ca0131bc4953.png)
如下是3.26.2的表现
![image](https://user-images.githubusercontent.com/19570481/71948609-83791100-320b-11ea-82bb-682ee657d3d0.png)
看了下3.26.3的realease log，猜测和这个修复有关
![image](https://user-images.githubusercontent.com/19570481/71948635-9d1a5880-320b-11ea-9868-934ae39e69cc.png)
源码我就没去看了哈，望修复~
codesandbox地址: https://codesandbox.io/s/condescending-hopper-346gb
