### ISSUE TITLE
4.0 Select arrow missing

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#20510]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/form-cn/?locale=en-US#components-form-demo-complex-form-control](https://next.ant.design/components/form-cn/?locale=en-US#components-form-demo-complex-form-control)

### Steps to reproduce
Hover Select

![Kapture 2019-12-28 at 13 20 39](https://user-images.githubusercontent.com/5378891/71539298-05984880-2975-11ea-86ed-ab9509c8eab1.gif)

### What is expected?
Show arrow

### What is actually happening?
Missing arrow

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | latest |
| System | IOS |
| Browser | chrome |

**Comment by jyash97** [comment]
Hey @zombieJ I think this: https://github.com/ant-design/ant-design/pull/20504 will fix this issue.

**Comment by zombieJ** [comment]
Duplicate of #20371
