### ISSUE TITLE
Table组件，排序功能与可拉伸功能的兼容问题

### ISSUE THREAD

**Issue by zed12138** [ant-design/ant-design#20526]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可拉伸表格列，会导致触发排序的点击回调

### What does the proposed API look like?
应当要在可拉伸事件触发的时候阻止排序按钮功能的回调触发

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18955
https://github.com/ant-design/ant-design/issues/14647#issuecomment-467865540
https://github.com/ant-design/ant-design/issues/13335#issuecomment-505409967
