### ISSUE TITLE
when Pagination component is simple type Number Input max length is not limit

### ISSUE THREAD

**Issue by LuHaikun** [ant-design/ant-design#20523]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/pagination-cn/](https://ant.design/components/pagination-cn/)

### Steps to reproduce
Infinity

### What is expected?
length limit

### What is actually happening?
Infinity

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.8.4 |
| System | MacOS |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/16951645/71556736-ff8a9080-2a76-11ea-8d9e-4acb5c156d56.png)

i hope add maxLength

**Comment by LuHaikun** [comment]
@ant-design-bot https://codesandbox.io/s/antd-reproduction-template-bi9uz?fontsize=14&hidenavigation=1&theme=dark

**Comment by LuHaikun** [comment]
> Hello @LuHaikun. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @LuHaikun, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-bi9uz?fontsize=14&hidenavigation=1&theme=dark

**Comment by yoyo837** [comment]
What's the steps to reproduce:

**Comment by LuHaikun** [comment]
> What's the steps to reproduce?

random input large Number 12312312313123123123123123342234234234234234324

**Comment by Kermit-Xuan** [comment]
I will work it

**Comment by Kermit-Xuan** [comment]
I have create PR at react-component/pagination [#246](https://github.com/react-component/pagination/pull/246), please review it. @afc163
