### ISSUE TITLE
表格表头是白色的

### ISSUE THREAD

**Issue by vipcxj** [ant-design/ant-design#20530]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-bordered](https://ant.design/components/table-cn/#components-table-demo-bordered)

### Steps to reproduce
直接肉眼观察

### What is expected?
和@table-header-bg表现一致

### What is actually happening?
不一致

| Environment | Info |
|---|---|
| antd | 3.22.0 |
| React | 16.8.3 |
| System | windows |
| Browser | chrome |

---
准确来说，我希望表头是白色的，但某一次我发现表头是灰色的，我用chrome的debug工具查看了样式，表头th的background也确实是#fafafa，而不是#ffffff。然后查了源码，发现表头样式中背景色由@table-header-bg指定，并且这个变量就是#fafafa。现在问题来了，不论是我其他用到表格的地方，还是官网样例，表头都是白色的，并且我也查了样式，和灰色时候的样式一模一样，background一项都是#fafafa，我以为是我眼睛看不出色差，于是将之改为ffffff，然而完全没变化。所以我就搞不懂@table-header-bg设成#fafafa的意义，并且为什么有时生效有时又不生效（官网就没生效，表头都是白色的~）
update: 进一步测试发现mac上的chrome相同版本，表头又成灰色的了，windows上相同版本chrome表头则是白的，这可能和平台有关？

**Comment by vipcxj** [comment]
#3581 这个issue貌似也是差不多的情况，不过没有给予一个准确的答复，另外他提到官网是灰色的，自己用变成了白色，然而我现在官网看到的是白色的。虽然我也觉得白色比较顺眼，但这种看脸的情况实在太让人难受了

**Comment by zombieJ** [comment]
没明白，上个截图看看？

**Comment by vipcxj** [comment]
@zombieJ 
![bug](https://user-images.githubusercontent.com/9250084/71572184-e33f3000-2b18-11ea-9d1e-c15956737495.png)
这是官网的截图，表格表头都是白色的，并且貌似没做什么特别设定

**Comment by zombieJ** [comment]
<img width="917" alt="截屏2019-12-30下午3 29 17" src="https://user-images.githubusercontent.com/5378891/71572260-25687180-2b19-11ea-9f11-e2d0fe6587af.png">

不太明白，这不是灰色的么？

**Comment by vipcxj** [comment]
@zombieJ 
明显是白色的，表头和身体颜色一模一样~
我再截个mac上的，刚刚试了，window上chrome和ie都是白的，mac上chrome和safari都是灰色的。不过mac我没截图工具，得稍等

**Comment by zombieJ** [comment]
是不是显示器把对比度 or 亮度调太高了？你的截图里表头就是灰色的。

**Comment by afc163** [comment]
你给的截图是我目测是灰色的。

<img width="178" alt="image" src="https://user-images.githubusercontent.com/507615/71572414-f0a8ea00-2b19-11ea-920e-bb33d54ebfbb.png">

**Comment by vipcxj** [comment]
@afc163 你能看出表头和表体的色差，表头表体明显一个颜色，我待会在发个mac上的，表头表体明显2个颜色

**Comment by afc163** [comment]
你可以找同事的电脑一起看看。

**Comment by vipcxj** [comment]
@afc163 @zombieJ  貌似破案了，我换mac，看之前我发的截图，又变成灰色了~ 这显示器有毒，你们这种小色差直接就给弄没了~ 最可怕的是我还没发给证据，因为截的图也跟着一起变

**Comment by zombieJ** [comment]
你的截图看来表头也是有颜色的，推测是你的显示器的问题。你可以通过拾取颜色工具来拾取一下你截图中的表头和表格，看看是否是相同的颜色。

**Comment by afc163** [comment]
该找 IT 换屏幕了。😹

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/71572622-fb17b380-2b1a-11ea-83ea-ab8ce45444f0.png)

**Comment by vipcxj** [comment]
第一次发现不同显示器差距那么大~ fa和ff就差一丁点，垃圾显示器估计就直接忽略了~

**Comment by vipcxj** [comment]
为了挽回名誉，我拍了张照，证明我所言非虚
![IMG_0641 HEIC](https://user-images.githubusercontent.com/9250084/71573083-0835a200-2b1d-11ea-9f97-090c5799fbc5.jpg)
