### ISSUE TITLE
maxLength of TextArea is not effective

### ISSUE THREAD

**Issue by mxt142114** [ant-design/ant-design#20537]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
在TextArea设置maxLength属性值为100，输入100字符后，输入法切换为中文，接着输入字符，不点击空格，鼠标在页面空白处点击

### What is expected?
多余输入的字符不会输进TextArea

### What is actually happening?
多余输入的字符也输进TextArea中了

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | react |
| System | win10 |
| Browser | Chrome 79.0.3945.88 |

**Comment by afc163** [comment]
原生受控的 textarea 存在这个问题：https://codesandbox.io/s/eager-hamilton-7h8mm

应该是 React 自身的 bug，我们好像没啥办法，可以尝试去给 React 提个 issue。
