### ISSUE TITLE
antd@1.4.1 安装报错

### ISSUE THREAD

**Issue by frankywen** [ant-design/ant-design#2053]
##antd 安装报错
```hash
cnpm install antd --save
```
执行上面的命令一直报error unknown compression method (antd@1.4.1)
![image](https://cloud.githubusercontent.com/assets/9948618/16071966/d41a1472-3310-11e6-830d-c45541c96e74.png)

##antd-init安装也报错
```hash
cnpm install antd-init -g
antd-init
```
执行上面的命令后，同样报error unknown compression method (antd@1.4.1)
![image](https://cloud.githubusercontent.com/assets/9948618/16071981/ea36b1d4-3310-11e6-8727-682bb722bd76.png)

**Comment by afc163** [comment]
测试 antd 本身可以安装。建议检查本地环境，或到 npm 或 cnpm 进行提问。
