### ISSUE TITLE
getValueFromEvent是否支持异步函数，返回promise

### ISSUE THREAD

**Issue by hxkuc** [ant-design/ant-design#20542]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
getValueFromEvent这个函数目前好像只支持同步的功能，我有个上传图片的功能，上传到阿里云后返回地址，通过异步的方式把返回的地址赋值给当前input，但是getValueFromEvent这个函数是同步的，所以目前不支持

### What does the proposed API look like?
我期望的方式是getValueFromEvent: async function () { return promise }

**Comment by afc163** [comment]
这个函数被设计为同步的纯函数，异步 Upload 请参考 https://ant.design/components/upload-cn/#components-upload-demo-upload-with-aliyun-oss 进行封装实现。

**Comment by zombieJ** [comment]
方向错了，应该让 `onChange` 触发时总是保持最新值才对。你的场景应该获取后触发 `onChange`。
