### ISSUE TITLE
Add dropdownMatchSelectWidth props in AutoComplete component.

### ISSUE THREAD

**Issue by faremax** [ant-design/ant-design#20549]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now, the width of dropdown panel in AutoComplete is not match the Input of itself. I hope to add `dropdownMatchSelectWidth` props as same as the Select Component.

### What does the proposed API look like?
<AutoComplete dropdownMatchSelectWidth />

**Comment by afc163** [comment]
https://codesandbox.io/s/nameless-hooks-8tkzx

It works.
