### ISSUE TITLE
I can see Input.Password's value in html, how can i hide it?

### ISSUE THREAD

**Issue by TCLCommunityFrontEnd** [ant-design/ant-design#20541]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
检查Input.Password的html代码

### What is expected?
看不到value

### What is actually happening?
能看到value

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.6 |
| System | windows,linux,macOS |
| Browser | 71.0.3573.0 |

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/7761#issuecomment-332829560

**Comment by zhongpan** [comment]
此问题解决方法是在componentDidMount，onFocus，onBlur，onChange四个时机删除value属性，但是我遇到两种场景，这种解决方法无效。
场景一：页面update，并没有触发input上述的四个时机，此时value又会出现。
场景二：包裹在Form.Item或getFieldDecorator里面的Input不是第一层节点，此时Input失去焦点时，value也会又出现。
为什么不在Input的componentDidUpdate中删除value属性呢？
