### ISSUE TITLE
upload上传前后台对接问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2054]
upload 设置了action属性后，请问下传到后台的是什么类型呢?因为不知道什么类型后台不知道要怎么对接，一下是我data: (file) => {console.log(file);}打印出来的数据，仔细看了下 好像没有后台能接收代表这上传文件的字段
lastModified: 1457503943423
lastModifiedDate: Wed Mar 09 2016 14:12:23 GMT+0800 (中国标准时间)
name: "add-icon.png"
size: 2064
type: "image/png"
uid: "rc-upload-1465976535986-2"
webkitRelativePath: ""

**Comment by afc163** [comment]
post 请求。

可以参考这里的服务端实现 https://github.com/blueimp/jQuery-File-Upload/wiki#server-side
