### ISSUE TITLE
onCalendarChange returns undefined value

### ISSUE THREAD

**Issue by chinhoe** [ant-design/ant-design#20557]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dry-wood-0hcwt)

### Steps to reproduce
1. Select any date in RangePicker
2. Check returned value in console

### What is expected?
Return an array of date in strings, similar to onChange

### What is actually happening?
Returns 'undefined' instead

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.12.0 |
| System | macOS Catalina (10.15.2) |
| Browser | Google Chrome (79.0.3945.88) |

**Comment by yoyo837** [comment]
@zombieJ 根据 [react-component/calendar](https://github.com/react-component/calendar) 的git历史，`onCalendarChange` 从未支持过第二个参数，文档和类型从 #8355 加入，#17373 补充其版本since 3.10.9 也是不正确的。现在是修复这个问题还是从文档中删除呢？

**Comment by zombieJ** [comment]
如果一直没有的话就清理一下文档吧。
