### ISSUE TITLE
【table】windows电脑下，fixed header、small size table描边的样式问题

### ISSUE THREAD

**Issue by 7Charlotte** [ant-design/ant-design#20563]
![table的描边样式问题](https://user-images.githubusercontent.com/4272864/71612574-4f369c80-2bdc-11ea-907a-24d5100c5162.PNG)
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-dynamic-settings](https://ant.design/components/table-cn/#components-table-demo-dynamic-settings)

### Steps to reproduce
windows电脑下，table-动态控制表格属性中，选择开启Fixed Header、Size选择small时

### What is expected?
描边依然为1px

### What is actually happening?
出现了额外的描边，见附件红框

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 3.20.0 |
| System | Window 10 |
| Browser | Chrome 版本 75.0.3770.100（正式版本） （64 位） |

**Comment by xrkffgg** [comment]
`small` 的时候，有边框，不知道是不是设计的原因

**Comment by 7Charlotte** [comment]
请问这个问题什么时候可以解决呢……？

**Comment by xrkffgg** [comment]
我看 4.0.0-rc1 没这问题了
