### ISSUE TITLE
Skeleton for Table/Card/List/PageHeader/Alert/Steps/Menu/Progress

### ISSUE THREAD

**Issue by hi-rustin** [ant-design/ant-design#20574]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Add skeleton for Table/Card/List/PageHeader/Alert/Steps/Menu/Progress.

### What does the proposed API look like?
```js
<Skeleton.Button />
<Skeleton.Avatar />
<Skeleton.Input />
```

- [x] Skeleton.Button
- [ ] Skeleton.Table
- [ ] Skeleton.Card
- [ ] Skeleton.List
- [ ] Skeleton.PageHeader
- [ ] Skeleton.Alert
- [ ] Skeleton.Steps
- [ ] Skeleton.Menu
- [ ] Skeleton.Progress
- [x] Skeleton.Image

**Comment by afc163** [comment]
Any progress?

**Comment by Rustin-Liu** [comment]
@afc163  Recently I am very busy, I have no time work on it.  I think you can add help want label let other contributor notice this issue.

**Comment by afc163** [comment]
`Skeleton.Image`

<img width="102" alt="image" src="https://user-images.githubusercontent.com/507615/75994495-07aef280-5f36-11ea-95b7-18b80552951e.png">

**Comment by Rustin-Liu** [comment]
Now I am working on Skeleton.Image, please feel free pick up other component.

**Comment by Rustin-Liu** [comment]
@afc163  Could you please add a help-want label?

**Comment by vikasprashar99** [comment]
hey can i work on this issue?

**Comment by Rustin-Liu** [comment]
> hey @Rustin-Liu can i work on this issue?

Of course. Give it a shot.

**Comment by vikasprashar99** [comment]
okay i will try working on Skeleton.Button

**Comment by Rustin-Liu** [comment]
> okay i will try working on Skeleton.Button

Sorry, the comment out of date. I have completed the button component. I will update the comment.

**Comment by vikasprashar99** [comment]
yea i just checked , will work on Skeleton.List

**Comment by fireairforce** [comment]
I will work on Skeleton.Card

**Comment by vikasprashar99** [comment]
![image](https://user-images.githubusercontent.com/45934592/83951205-752c3100-a84d-11ea-9013-49abe0d15214.png)
@Rustin-Liu getting this error while pushing to feature branch

**Comment by Rustin-Liu** [comment]
> getting this error while pushing to feature branch

You get this error because you can not directly push it to antd's repo.
I suggest you read the contributing guide  https://ant.design/docs/react/contributing#Sending-a-Pull-Request.

**Comment by fireairforce** [comment]
> `Skeleton.Image`
> 
> <img alt="image" width="102" src="https://user-images.githubusercontent.com/507615/75994495-07aef280-5f36-11ea-95b7-18b80552951e.png">

Should I use css to implement a such Image or maybe just use icon-font?

**Comment by afc163** [comment]
Try svg.

**Comment by fireairforce** [comment]
ok~I just do in this way~

**Comment by vikasprashar99** [comment]
@Rustin-Liu  i have created a new branch from the feature branch still i am getting the same error while pushing

**Comment by Rustin-Liu** [comment]
>  i have created a new branch from the feature branch still i am getting the same error while pushing

I think you should fork this repo for your github account. And you can push it to your repo, then you can send a PR from your repo to this repo.

You can not push a new branch to this repo. You can refers https://ant.design/docs/react/contributing#Sending-a-Pull-Request.

**Comment by chathurabuddi** [comment]
> I will work on Skeleton.Card

any progress?

**Comment by DawnLck** [comment]
Elements in the skeleton should be customizable, wait for me(if i have time)
