### ISSUE TITLE
Do not include momentjs in the browser bundle if DatePicker and/or TimePicker are not used

### ISSUE THREAD

**Issue by lhz516** [ant-design/ant-design#20579]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/lhz516/hanzluo](https://github.com/lhz516/hanzluo)

### Steps to reproduce
1. `npm i antd`, but don't import momentjs related components
2. Use webpack to bundle the app

### What is expected?
`moment` won't be included in the browser bundle if `DatePicker` and/or `TimePicker` are not used

### What is actually happening?
`moment` is in the browser bundle no matter if `DatePicker` and/or `TimePicker` are used. At least the locales shouldn't be included.
![image](https://user-images.githubusercontent.com/9879279/71648164-a9eff700-2cb5-11ea-8bb2-87198fe3193e.png)

Run `npm ls moment`
![image](https://user-images.githubusercontent.com/9879279/71648168-bb390380-2cb5-11ea-9648-3b3c7255d643.png)

| Environment | Info |
|---|---|
| antd | 3.26.3 (Also tested 3.26.5) |
| React | 16.12.0 |
| System | Win 10 |
| Browser | Any |

**Comment by afc163** [comment]
It should be fixed in #19115 already.

**Comment by lhz516** [comment]
@afc163 I already set `mode: 'production'` in my [webpack config](https://github.com/lhz516/hanzluo/blob/master/webpack/config.client.js). I assume the tree shaking is enabled. Is there anything else I need to do to get rid of these unnecessary modules?

**Comment by afc163** [comment]
https://github.com/lhz516/hanzluo/pull/3

**Comment by zombieJ** [comment]
@lhz516 ,could you help to check which component case moment import?

**Comment by lhz516** [comment]
@zombieJ Tree shaking worked by adding `libraryDirectory: 'es'` into `babel-plugin-import`'s config.

cc: https://github.com/lhz516/hanzluo/pull/3 @afc163
