### ISSUE TITLE
如何在 getFieldDecorator 中使用 number 类型的层级路径？

### ISSUE THREAD

**Issue by zhumengyue** [ant-design/ant-design#20583]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-ishizaka-8z9qc)

### Steps to reproduce
点击button收集表单，查看log

### What is expected?
getFieldDecorator("username.1") 收集到的数据是 { username: { 1: xxx } }

### What is actually happening?
getFieldDecorator("username.1") 收集到的数据是 { username: [ , xxx] }

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | 16.2.0 |
| System | macOS 10.14.6 |
| Browser | Chrome 79.0.3945.88 |

---
后端在 thritf 中定义 map<enum, string> 时，enum 的值只能是 number，导致前端注册表单不太友好，在后端不修改的情况下，有没有较好的解决办法

**Comment by afc163** [comment]
目前没有办法实现：https://github.com/lodash/lodash/issues/1316#issuecomment-118177733

建议使用 normalize 自行转换一下。
