### ISSUE TITLE
Color Coded buttons

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#20587]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There should be an option to set color of button using general color labels like `primary, success, danger, warning, info` 

### What does the proposed API look like?
There can be prop to specify type of button
```
<Button color="warning">Warning</Button>
<Button color="success">Success</Button>
<Button color="info">Info</Button>
```
![image](https://user-images.githubusercontent.com/41179062/71652983-ec661200-2d4f-11ea-993f-e2b67ef83a36.png)

**Comment by piyushk96** [comment]
Also, the `type` prop of button supports `danger` value which is not mentioned in documentation

**Comment by piyushk96** [comment]
There are separate props for `ghost` and `danger` and `type` prop also supports `ghost` and `danger` values so that looks confusing.
So, there should be only two props one for specifying type (dashed, default etc) and other to specify color

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4770#issuecomment-278217817

**Comment by afc163** [comment]
> There are separate props for ghost and danger. Also type prop supports ghost and danger values so that looks confusing.

We documented `type="danger"` in https://ant.design/components/button/#API
