### ISSUE TITLE
DatePicker可不可以支持多选，类似elementUI框架的DatePicker那样？

### ISSUE THREAD

**Issue by cctvmikeowen** [ant-design/ant-design#20582]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些场合下DatePicker组件需要选择多个日期，类似elementUI框架的DatePicker那样，DatePicker的文档我看了，没有提及相关功能的扩展

### What does the proposed API look like?
希望DatePicker能增加，日期多选功能，这个的应用场景还是很广泛的

**Comment by yoyo837** [comment]
范围选择不就等同于多选？

**Comment by cctvmikeowen** [comment]
文档是这样描述的：
自定义日期范围选择
当 RangePicker 无法满足业务需求时，可以使用两个 DatePicker 实现类似的功能。用户可能会选择几十个日期，那是不是要用几十个DatePicker 来实现吗？

**Comment by afc163** [comment]
Duplicate of #4447
