### ISSUE TITLE
DatePicker.RangePicker  控制弹层显示隐藏问题

### ISSUE THREAD

**Issue by jiayuu** [ant-design/ant-design#20594]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
清除按钮与 onFocus 冲突

### 我想通过onFocus 控制弹层显示隐藏， 但是点击清除按钮会走onFocus方法，就达不到清除的效果了

```javascript
<RangePicker
  placeholder={['开始月份', '结束月份']}
  format="YYYY-MM"
  value={timeValue}
  mode={['month', 'month']}
  open={isOpenTime}
  onPanelChange={this.handlePanelChange}
  onChange={this.handleChange}
  onBlur={this.timerBlur}
  onFocus={this.timerFocus}
/>
```
- 上面代码不会走onChange为什么

**Comment by zombieJ** [comment]
Close since it's not a feature requirement and also not provides reproduce as bug.
