### ISSUE TITLE
upload控件beforUpload问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2059]
我按照官网该控件beforUpload最后一个案例进行实验，一模一样的代码限制只能上传jpg格式的，上传png报错，然后点击控件就再也没有效果了，而官网却可以，唯一的区别是官网是我自己要这样引入：
import React from 'react';
import ReactDOM from 'react-dom';
import { Upload, Button, Icon, message } from 'antd';

而官网是
import { Upload, Button, Icon, message } from 'antd';

想通过在线演示结果发现在线演示把自己本地的代码拷过去，发现也是可以的，唯一的却别是在线演示是
const { Upload, Button, Icon, message } = antd;

请问这到底是怎么回事呢？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2004

你不是提过这个问题么，看不懂回复么。。

**Comment by afc163** [comment]
重新安装本地的 antd ，确保其依赖的 rc-upload 的版本是 1.13.2 及以上。

**Comment by aw6658913** [comment]
上次你是指个链接给我看 并没有告诉我要更新rc-upload版本~~然后我进去看有段是你写的说要复位什么的，我才问复位是什么~~已更新可以用了

**Comment by afc163** [comment]
我什么时候说复位了。。。。
