### ISSUE TITLE
4.0 Countdown remove moment deps

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#20598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Countdown use moment to convert string to number which should be removed.

### What does the proposed API look like?
No moment in Countdown

**Comment by jyash97** [comment]
Hey @zombieJ  I can take a look at this. Can you please add more details like do we need to replace `moment` with any other lib or we already have some utils defined?

**Comment by zombieJ** [comment]
@jyash97 , it's best to use native lib instead of any other date lib. Since we only use it to get the timestamp.
