### ISSUE TITLE
EnterAnimation能否搭配前端路由

### ISSUE THREAD

**Issue by thewei** [ant-design/ant-design#206]
尝试用搭配 react-router 使用EnterAnimation，发现没法起作用。
不知是不是用法的问题，我希望是 hash 变化渲染的页面能加上进场，离场动画。
这种场景应该如何用EnterAnimation

**Comment by afc163** [comment]
@jljsj33 搞之~

**Comment by jljsj33** [comment]
搞完，0.9.0-beta9 已支持，详细 API 看 http://ant.design/components/enter-animation

**Comment by afc163** [comment]
:+1:

**Comment by baixiaoji** [comment]
@jljsj33    链接失效了，最新的ant-design去掉了EnterAnimation 这个组件了吗

**Comment by jljsj33** [comment]
@baixiaoji 请用 [queue-anim](https://motion.ant.design/components/queue-anim)
