### ISSUE TITLE
 Button style issues

### ISSUE THREAD

**Issue by denfils** [ant-design/ant-design#20600]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-33wf2)

### Steps to reproduce
If the button has only an icon and no text,You will notice that the icon is not centered vertically

### What is expected?
https://guides.github.com/features/mastering-markdown/

### What is actually happening?

.ant-btn-icon-only > i {
    vertical-align: middle;
}

If this style is disabled, it will be centered vertically

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | Chrome 79.0.3945.88 |

**Comment by afc163** [comment]
In my chrome, text will not align center if `vertical-align: middle` is removed.

## with `vertical-align: middle`

<img width="482" alt="image" src="https://user-images.githubusercontent.com/507615/71663748-5a7ef900-2d91-11ea-9a05-c669615b15eb.png">

## without `vertical-align: middle`

<img width="430" alt="image" src="https://user-images.githubusercontent.com/507615/71663755-62d73400-2d91-11ea-877e-f24950407753.png">

**Comment by shaodahong** [comment]
maybe ref by #20210

**Comment by denfils** [comment]
### **Not disabled**
![image](https://user-images.githubusercontent.com/24760335/71705240-9d84af00-2e19-11ea-9a1f-3fbb1f1ca718.png)
### **Disabled**
![image](https://user-images.githubusercontent.com/24760335/71705260-b1c8ac00-2e19-11ea-8b7c-11ec8fb28fa5.png)
Obviously, the style is centered vertically if the style is disabled
May be caused by different versions of Google Chrome?

**Comment by enzeberg** [comment]
Will this be fixed in version 3.x?
I am still using antd v3, because it takes time to migrate to v4.

**Comment by enzeberg** [comment]
@afc163

**Comment by yoyo837** [comment]
IMHO, I didn't get the point.
