### ISSUE TITLE
Error in Dropdown menu location

### ISSUE THREAD

**Issue by baibaibaibai** [ant-design/ant-design#20611]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-b3ge8)

### Steps to reproduce
Move the mouse over the button and a drop-down menu will pop up. The pull-down menu must contain the Upload component. Placement set to "bottomCenter"

### What is expected?
When hovering, the drop-down menu should be centered

### What is actually happening?
Refresh the page. The first time hover is used, the drop-down menu is left aligned

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.12.0 |
| System | mac 10.15 |
| Browser | Chrome 79.0.3945.88 |

**Comment by afc163** [comment]
At current implementation, Upload renders with a delay when dropdown menu renders, you can add `forceRender` for Dropdown to avoid it.

https://codesandbox.io/s/antd-reproduction-template-274yy
