### ISSUE TITLE
Pagination pageSize responsive 

### ISSUE THREAD

**Issue by CarolineBoyer** [ant-design/ant-design#20615]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using gridLayout and pagination options in a List, they should corresponds automatically when it comes to pageSize. 
Also, pageSize could be a number or an object representing the responsive one like in grid ( xs: 1, sm: 2, md: 4, lg: 4, xl: 6, xxl: 3).

### What does the proposed API look like?
pageSize	Number of data items per page number | object { xs: 1, sm: 2, md: 4, lg: 4, xl: 6, xxl: 3}
if grid is set, transfer automatically the {xs...} to the pageSize option.

**Comment by afc163** [comment]
There is a `showLessItems` prop that you can try.

**Comment by CarolineBoyer** [comment]
I am not sure what you mean by that. 
showLessItems is a boolean, how do you want to correspond it to a grid entity ?

**Comment by afc163** [comment]
Something like:

```jsx
const { isWide } = useMedia();

return <Pagination showLessItems={!isWide} />;
```

**Comment by francecil** [comment]
Solved?
I looked at the code of `showLessItems` and found that this is just adjusting the size of the pager.
What the author wants is to be able to set the responsive pagination size.
In other words，when the page size changes, select the corresponding pagesize and trigger `onShowSizeChange` callback.

Of course, there are still some pits here.
For example, if the pagesize has changed, should the page number also change?
So, I think it’s better to be implemented by external developers

**Comment by tanDjent** [comment]
Something like that would definitely be great as of right now I needed something similar so had to make a useEffect that checks the innerHeight of the window and change the page size according to what I've manually set in that function 
But this doesn't work if you zoom in or zoom out 
not the best code but kinda gets the job done 
`useEffect(() => {
    const { innerHeight } = window;

    if (innerHeight < 700) setTablePageSize(3);
    else if (innerHeight >= 700 && innerHeight < 800) setTablePageSize(4);
    else if (innerHeight >= 800 && innerHeight < 900) setTablePageSize(5);
    else if (innerHeight >= 900 && innerHeight < 1000) setTablePageSize(6);
    else if (innerHeight >= 1000 && innerHeight < 1100) setTablePageSize(7);
    else if (innerHeight >= 1100 && innerHeight < 1200) setTablePageSize(8);
    else if (innerHeight >= 1200 && innerHeight < 1300) setTablePageSize(9);
    else if (innerHeight >= 1300) setTablePageSize(10);
  }, [window]);`
