### ISSUE TITLE
穿梭框组件，数据特别大，会卡死，怎么可以优化？

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design#20624]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
穿梭框组件，数据特别大，不会卡

### What does the proposed API look like?
设置字段，数据量大，不会卡

**Comment by afc163** [comment]
Duplicate of #9703

**Comment by liangchaofei** [comment]
> #9703

这个链接没有解决吧？

**Comment by liangchaofei** [comment]
> > #9703
> 
> 这个链接没有解决吧？

加上了lazy=true 还是会卡

**Comment by liangchaofei** [comment]
https://codesandbox.io/s/upbeat-brown-5qkm9  可以看下这个demo

**Comment by afc163** [comment]
It is not resolved now, you can reply your reproduce in #9703

**Comment by liangchaofei** [comment]
> It is not resolved now, you can reply your reproduce in #9703

回复了，什么时候可以解决那？或者有没有其他临时方法？
