### ISSUE TITLE
Select组件如何取消回车选中下拉选项

### ISSUE THREAD

**Issue by lynshir** [ant-design/ant-design#20625]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g0dec)

### Steps to reproduce
1.展开选项下拉
2.将鼠标移入某个下拉选项，不点击，只hover
3.回车会自动选中选项

### What is expected?
回车不选中，由用户自己点击来选中，因为回车选中事件会和自定义回车事件的某些功能冲突，或者给出一个配置项来取消默认的回车选中事件

### What is actually happening?
回车会自动选中选项

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.6.3 |
| System | macos |
| Browser | 79.0.3945.88 |

**Comment by lynshir** [comment]
在node_modules/rc-select/es/Select.js的第259行,可否将这一部分外放出一个配置来
```
// if (domEvent.type === 'keydown' && domEvent.keyCode === KeyCode.ENTER) {
      //   _this.removeSelected(getValuePropValue(item));
      //   return;
      //
 }//
```
rc-select所用版本是8.6.9

**Comment by afc163** [comment]
> 因为回车选中事件会和自定义回车事件的某些功能冲突

看看你具体是什么冲突场景。

**Comment by lynshir** [comment]
> > 因为回车选中事件会和自定义回车事件的某些功能冲突
> 
> 看看你具体是什么冲突场景。

在业务中用户会先用鼠标哐哐一顿选，然后会直接回车做一次查询，与此同时，回车的时候如果鼠标hover在下拉选项上，就会先触发取消勾选当前hover的选项，然后再做业务查询，这里回车查询用了`onInputKeyDown`配置

**Comment by zombieJ** [comment]
> > > 因为回车选中事件会和自定义回车事件的某些功能冲突
> > 
> > 
> > 看看你具体是什么冲突场景。
> 
> 在业务中用户会先用鼠标哐哐一顿选，然后会直接回车做一次查询，与此同时，回车的时候如果鼠标hover在下拉选项上，就会先触发取消勾选当前hover的选项，然后再做业务查询，其实用户已经用鼠标选好了，不希望回车的时候取消他之前的勾选，这里回车查询用了`onInputKeyDown`配置

这个和 Select 的键位是冲突的，如果要实现这个效果，可以再外层 `stopPropagation` 一下。如果要精确控制，就判断一下 Select 的 open 状态做处理。

**Comment by LJCandyCrush** [comment]
面临同样的问题，请问解决了吗？如何解决的呢

**Comment by indexw** [comment]
同问

**Comment by NetworkNull** [comment]
同问，是否有办法禁用回车选中和取消选项的功能

**Comment by jiangyijie27** [comment]
@LJCandyCrush @indexw @NetworkNull 

try this:

```js
 onInputKeyDown={(e) => {
    if (e.key === "Enter") {
      // do server search
      e.stopPropagation()
    }
  }}
```

**Comment by xushuosean** [comment]
我的场景是在dropdownRender中存在一个inputNumber组件，在input组件上添加onPressEnter属性，并在上面添加冒泡，就可以了，仅供参考
`
dropdownRender={() => (
    <InputNumber onPressEnter={(e) => {e.stopPropagation()}} />
)}
`

**Comment by Whiteyingshan** [comment]
找了好久的资料自己写了个，给大家个参考

[![Edit distracted-joana-zxyvzj](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-joana-zxyvzj?fontsize=14&hidenavigation=1&theme=dark)

下面是主要添加的代码：
```
onInputKeyDown={(e) => {
      //  阻止回车选中事件
      e.key === "Enter" && e.stopPropagation();
      //  执行提交代码
      console.log("submit");
}}
```
