### ISSUE TITLE
Typography.Paragraph ellipsis 展开后收起功能

### ISSUE THREAD

**Issue by Lpmvb** [ant-design/ant-design#20639]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Typography.Paragraph ellipsis 目前展开后无法收起

### What does the proposed API look like?
Typography.Paragraph ellipsis 展开后提供收起功能

**Comment by wenguangji** [comment]
我在form中设置Typography.Paragraph ellipsis，只省略不展开，省略并没有生效，并且样式显示异常；在改为省略并可以展开后样式正常。

**Comment by zombieJ** [comment]
设计如此，故意不加的。如果需要可以通过 `suffix` 自行实现。

**Comment by Lpmvb** [comment]
Typography 貌似没有提供 `suffix` 吧

**Comment by zombieJ** [comment]
https://next.ant.design/components/typography/#components-typography-demo-suffix

**Comment by linxianxi** [comment]
> https://next.ant.design/components/typography/#components-typography-demo-suffix

打不开了   Typography怎么设置suffix呢

**Comment by zhangyanling77** [comment]
https://www.yuque.com/yijiangxiliu/pwblsg/bx75ka   可以参考下这个实现

**Comment by zhoujingsai** [comment]
> 设计如此，故意不加的。如果需要可以通过 `suffix` 自行实现。

实际业务场景中，有大段的文字，在展开之后，还有可能需要折叠回去（不然页面内容太多），所以希望能支持展开后收起功能

**Comment by drdevelop** [comment]
@Lpmvb @zhoujingsai Maybe you can try @typography-org/react

**Comment by mcfly001** [comment]
> 

问题是你咋知道一定要有展开呢？有时候可能只有几个字符

**Comment by yxf18** [comment]
> https://www.yuque.com/yijiangxiliu/pwblsg/bx75ka 可以参考下这个实现

稍微优化一下
```javascript
<Paragraph
    ellipsis={
        visible ? false
            : {
                rows: 2,
                expandable: true,
                symbol: <span onClick={(e)=>{
                    e.stopPropagation();
                    setVisible(true)
                }}><DownOutlined /> 展开</span>
            }
    }
>
    {i.content}
    {visible && <a onClick={() => setVisible(false)}><UpOutlined /> 收起</a>}
</Paragraph>
```

**Comment by eternallycyf** [comment]
http://wangxince.site/my-demo-markdown/components/my-components/custom-tooltip 楼上的那个收起展开按钮位置不对 直接用它自带的就可以 不用自己写

**Comment by HankWang1999** [comment]
> http://wangxince.site/my-demo-markdown/components/my-components/custom-tooltip 楼上的那个收起展开按钮位置不对 直接用它自带的就可以 不用自己写

链接好像失效了：）

**Comment by eternallycyf** [comment]
@HankWang1999 https://codesandbox.io/s/gifted-fire-h7xzkt

**Comment by easonchen3** [comment]
> > https://www.yuque.com/yijiangxiliu/pwblsg/bx75ka 可以参考下这个实现
> 
> 这里的在copyable可复制场景 & 当自适应长度足够无需ellipsis时会有点问题，处理了一下，代码可参考：
> 
> ```tsx
> // 段落收起展开功能
> const genExpandableParagraph: FC<{ content: string; key: string }> = (props) => {
>   const [visible, setVisible] = useState<boolean>(false) // 是否全部展示
>   const [ellipsis, setEllipsis] = useState(false) // 是否开启省略模式
>   const { content, key } = props.  // content是段落内容
> 
>   // 自定义展开按钮
>   const ExpandBtn = () => {
>     return (
>       <div
>         style={{
>           position: 'absolute',
>           bottom: '0px',
>           right: '22px',
>           visibility: ellipsis ? 'visible' : 'hidden' // 如果内容长度较少不需要省略，则不展示这个展开按钮
>         }}
>       >
>         <a onClick={() => setVisible(true)}>Expand</a>
>       </div>
>     )
>   }
> 
>   return (
>     <div style={{ position: 'relative' }} key={key}>
>       <Paragraph
>         copyable={{
>           text: content // 只复制值部分
>         }}
>         ellipsis={
>           visible
>             ? false
>             : {
>                 rows: 1,
>                 expandable: true,
>                 onEllipsis: () => {
>                   setEllipsis(true)
>                 },
>                 // 必须要加占位符，用来展示ExpandBtn。占位符内容与自定义的展开按钮的一致，但不可见
>                 symbol: <span style={{ visibility: 'hidden' }}>Expand</span>
>               }
>         }
>       >
>         {content}
>         {/* 收起按钮 */}
>         {visible && (
>           <a
>             onClick={() => {
>               setVisible(false)
>             }}
>           >
>             <UpOutlined />
>           </a>
>         )}
>       </Paragraph>
>       {/* 以下自定义展开按钮 */}
>       {!visible && <ExpandBtn />}
>     </div>
>   )
> }
> ```

真棒

**Comment by HankWang1999** [comment]
> @HankWang1999 https://codesandbox.io/s/gifted-fire-h7xzkt

看到啦，3Q～

**Comment by decadez** [comment]
> https://www.yuque.com/yijiangxiliu/pwblsg/bx75ka 可以参考下这个实现

进一步优化，仅供参考

```javascript
<div style={{ position: 'relative' }}>
     {
        visible ? <>
          {text}
          {<a onClick={() => setVisible(false)}>收起</a>}
        </> : <Paragraph
          ellipsis={{
            rows: rows,
            expandable: true,
            onExpand: () => setVisible(true)
          }}
        >
          {text}
        </Paragraph>
      }
</div>
```

**Comment by cloudmoonocus** [comment]
我是直接刷新<Typography.Paragraph />的 key，这样是可以的吗🤔🤔🤔

**Comment by lk19940215** [comment]
> 我是直接刷新<Typography.Paragraph />的 key，这样是可以的吗🤔🤔🤔

我也是直接刷 key,感觉不该这样，现在找到这里，感觉刷key也可以接受了。
