### ISSUE TITLE
4.0 border-radius

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#20635]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
4.0中 发现很多组件边框将 `border-radius` 都从 `4px` 改为了 `2px`了，感觉没有之前的自然。

### What does the proposed API look like?
期望可以保持原有 `4px` 或 可配置。

**Comment by afc163** [comment]
这是新的设计规范，可以用主题变量进行全局配置。
