### ISSUE TITLE
Cascader级联选择是否可以支持最后一个节点能多选

### ISSUE THREAD

**Issue by seamanm** [ant-design/ant-design#20633]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Cascader级联选择是否可以支持最后一个节点能多选.比如用来选择省市，最后一个市节点我希望可以多选

### What does the proposed API look like?
可通过 props.multiple = true 来开启多选模式

**Comment by afc163** [comment]
#6674
#5026
