### ISSUE TITLE
Form 和 Modal 组件混合使用时，预期不一致。

### ISSUE THREAD

**Issue by capdiem** [ant-design/ant-design#20646]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-fire-klz5f)

### What is expected?
form.resetFields 似乎不能正确得地执行。

### What is actually happening?
先点击第一个按钮，再点击第二个按钮，表单没有正常的显示初始值。反过来点击，表单没有正确的清空值。

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.1 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google chrome |

**Comment by afc163** [comment]
试试这么写：https://codesandbox.io/s/wonderful-fire-klz5f

initialValues 里面的值不应该是动态值。

**Comment by capdiem** [comment]
不行~~~，想到的办法只能通过`form.setFieldsValue()`了。
``` javascript
useEffect(() => {
  if (initialValues) {
    form.setFieldsValue(initialValues);
  } else {
    form.resetFields();
  }
}, [visible]);
```
