### ISSUE TITLE
Deselecting option in Select inside Popover closes Popover

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#20649]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/popover-select-bug-nhyn2)

### Steps to reproduce
* click on button (Popover will open)
* select some options from select box
* click on cross(x) to deselect option and popover will close

### What is expected?
Popover should remain open and option should be deselected from select

### What is actually happening?
On clicking cross(x) of selected option popover gets closed

| Environment | Info |
|---|---|
| antd | 4.0.0-beta.1 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome (Version 78.0.3904.108) |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-disappears-when-I-click-another-popup-component-inside-it.-How-do-I-resolve-this

**Comment by piyushk96** [comment]
> https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-disappears-when-I-click-another-popup-component-inside-it.-How-do-I-resolve-this

The solution provided in above link doesn't solve the issue
Also, the issue that I mentioned is not occuring on clicking anywhere in `Select`'s overlay but the occuring when I click the cross(x) button of option tag which is displayed inside the input

**Comment by piyushk96** [comment]
This issue is occuring in `4.0.0-beta.1` but working properly in `3.26.5`

**Comment by abdih** [comment]
I intend to work on this bug.

**Comment by la99er** [comment]
This issue does  still appear to me in `4.0.0` with a `DatePicker` inside the `Popover` content. Clearing the DatePickers value will close the Popover. Is this the right place here to reactivate the issue? Or should I create a new issue for that?  
Thanks in advance!
