### ISSUE TITLE
Icon Request: UPI

### ISSUE THREAD

**Issue by manan10101996** [ant-design/ant-design#20653]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
UPI is an important part of indian banking solutions. A lot of system provides UPI feature on their web portals. Such portals/systems requires UPI icon for good UI experience. It would be great if antd (which is an awesome UI library and is used by lot of indian web developers) can add this icon in their icon suite.

### What does the proposed API look like?
https://cdn.iconscout.com/icon/free/png-512/bhim-3-69845.png

**Comment by afc163** [comment]
Thx, merged to https://github.com/ant-design/ant-design-icons/issues/71#issuecomment-570996429
