### ISSUE TITLE
antd包装组件的时候能不能提供ref

### ISSUE THREAD

**Issue by czjxy881** [ant-design/ant-design#2065]
## 你做了什么？

我想对多选的Select在选择一个后自动关闭选择框。需要用到Select的setOpenState，但是antd包装后的没有对真实的Select提供ref，造成没法调用

## 你期待的结果是：

提供真实Select的ref

## 实际上的结果和抱怨：

没有

## 可重现的在线演示

http://riddle.alibaba-inc.com/riddles/f0b0d2f

**Comment by afc163** [comment]
不要调用方法，只能用 props 进行通信。

**Comment by afc163** [comment]
另外，不要贴内网链接。

**Comment by afc163** [comment]
另外，内网那个链接里，我给你改好了。
