### ISSUE TITLE
Table filter dropdown hidden when using scroll prop

### ISSUE THREAD

**Issue by mikeyshing88** [ant-design/ant-design#20655]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-morse-gwdet)

### Steps to reproduce
- Open the `Name` column filter and select `Fake value`
- No results should be rendered
- Open the filter again (the filter will now be hidden due to the overflow scroll)

### What is expected?
Filter should still be visible if the table result element height is smaller than the filter height

### What is actually happening?
Filter element is hidden due to the overflow scroll

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | Latest |
| System | MacOS |
| Browser | Chrome |

**Comment by ex8** [comment]
+1

**Comment by afc163** [comment]
```diff
    <Table
      columns={columns}
      dataSource={data}
      scroll={{ x: 1000 }}
-    getPopupContainer={trigger => trigger}
    />
```

**Comment by mikeyshing88** [comment]
@afc163 if `getPopupContainer` is removed, then the filters will be appended to the body instead of the table container - meaning if you scroll down the page, the filter box will also scroll down.

Here is an example of what I mean with your suggestion (open the filter and scroll down):

https://codesandbox.io/s/thirsty-kilby-yxqtu

**Comment by afc163** [comment]
It is a dilemma, we can not resolve both problems now.

**Comment by Nastya-Piu** [comment]
Any updates on this issue?

**Comment by ex8** [comment]
+1 on any updates. Kind Regards.
