### ISSUE TITLE
异步加载树节点，使用 treeDataSimpleMode 时，TreeSelect组件的treeExpandedKeys属性不会自动打开子节点

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#20657]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/fengyun2/pen/abzVaOo?&editable=true&editors=001](https://codepen.io/fengyun2/pen/abzVaOo?&editable=true&editors=001)

### Steps to reproduce
设置 `treeDataSimpleMode=true`, 点击打开 TreeSelect 控件，发现一直在loading，没法自动加载对应层级的节点数据

### What is expected?
点击打开 TreeSelect 控件，根据预设的 `treeExpandedKeys`，可以自动加载对应层级的节点数据

### What is actually happening?
点击打开 TreeSelect 控件，发现一直在loading，没法自动加载对应层级的节点数据

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.8.6 |
| System | win 10 |
| Browser | Chrome 78.0.3904.70 |

---
改为 `treeDataSimpleMode=false` 的模式可以正确展开对应层级的节点数据，正确的效果如下： https://codepen.io/fengyun2/pen/BaymOBw?editors=0010

**Comment by zombieJ** [comment]
<img width="374" alt="截屏2020-01-15下午4 10 42" src="https://user-images.githubusercontent.com/5378891/72416421-9793b400-37b1-11ea-90f9-0ce363ddd722.png">


https://codesandbox.io/s/crazy-silence-gizn3
