### ISSUE TITLE
table设置scroll.x 并且所有列宽固定,设置一列fixed ，当屏幕比较宽，不触发固定列的时候，会出现空白问题。

### ISSUE THREAD

**Issue by pureZjr** [ant-design/ant-design#20659]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-rbkt8z?file=index.js](https://stackblitz.com/edit/react-rbkt8z?file=index.js)

### Steps to reproduce
直接打开网址能看见

### What is expected?
不出现空白

### What is actually happening?
出现空白

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12.0 |
| System | mac |
| Browser | 谷歌 79.0.3945.88 |

---
这个好像是一直都存在的问题？
 除了保留一列不固定宽度还有其他解决方法么？

**Comment by afc163** [comment]
>   除了保留一列不固定宽度还有其他解决方法么？

也可以设置百分比宽度，保证加起来等于 100%。

**Comment by tylerrrkd** [comment]
> > 除了保留一列不固定宽度还有其他解决方法么？
> 
> 也可以设置百分比宽度，保证加起来等于 100%。

Hello, @afc163 I've try this way, but it doesn't work.

**Comment by tylerrrkd** [comment]
Solved.

String too long.

```
/**
 * generate cell with title
 * @param {string} text content
 * @param {number} length preserve length
 */
export const generateTitleCell = (text, length = 8) => {
  const textString = String(text || "")
  return {
    children: length === -1
      ? text
      : textString.length > length
        ? textString.substring(0, length) + "..."
        : textString,
    props: {
      title: text
    }
  }
}

...
const columns = [
  {
    dataIndex: "planName",
    title: "计划名称",
    // width: CELL_MIN_WIDTH,
    fixed: "left",
    width: 160,
    render: text => generateTitleCell(text)
  },
]
...

<Table
  columns={columns}
  dataSource={list}
  scroll={{ x: columns.reduce((sum, item) => sum += (item.width || 100), 0) }}
/>

```

Hope it could help somebody.
