### ISSUE TITLE
如何在浏览器控制台中设置Datepicker的值

### ISSUE THREAD

**Issue by wtyang** [ant-design/ant-design#20663]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用antdesign pro 2
由于公司在推进自动化测试， 在测试时脚本代理跑的操作无法改变datepicker的值。测试人员需要测试多个日期用例，通过脚本跑完。需要实现在测试软件中填写日期用例，测试软件在浏览器自动设置日期。 在issue并没有发现类似需求。https://github.com/ant-design/ant-design/issues/12118 这个有点像，但是应该如何在浏览器执行？

### What does the proposed API look like?
能够暴露一个公共方法设置即可，或者有更好的方式

**Comment by afc163** [comment]
https://www.npmjs.com/package/mockdate

**Comment by wtyang** [comment]
其实是想设置datepicker组件中的值 @afc163

**Comment by yoyo837** [comment]
这与antd无关，一般编译后的代码都通过webpack的IFEE引入浏览器，你可以考虑写一个模块，在测试环境引入，持有antd的form对象（或者ref 表单元素），添加全局统一访问方式调用，满足你的自动化测试！不过更推荐jest的headless方式！
