### ISSUE TITLE
TextArea 回车触发清空输入框会遗留一个回车

### ISSUE THREAD

**Issue by yyzclyang** [ant-design/ant-design#20665]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-haibt-bpixq)

### Steps to reproduce
在 TextArea 组件中输入内容，使用 onPressEnter 来触发清空输入框

### What is expected?
期望清空输入框

### What is actually happening?
清空输入框之后会遗留一个回车，但是使用 setTimeout 异步触发清空操作，就没问题

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | latest |
| System | macOS 10.14.6 |
| Browser | chrome 79.0.3945.88 |

**Comment by yoyo837** [comment]
它是先执行你的`onPressEnter`再做内部逻辑keyDown即回车，调换代码后应该能够满足你的需求。
“先down后press?”
```tsx

  handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    const { onPressEnter, onKeyDown } = this.props;
    if (e.keyCode === 13 && onPressEnter) {
      onPressEnter(e);
    }
    if (onKeyDown) {
      onKeyDown(e);
    }
  };
```

**Comment by yoyo837** [comment]
你这个还是换成这个吧，要么你继续timeout。
```js
          onKeyUp={e => {
            if (e.keyCode === 13) {
              this.setState({ value: '' });
            }
          }}
```

**Comment by morenyang** [comment]
Use `e.preventDefault()` can work. 

```js
onPressEnter={(e) => {
  e.preventDefault();
  this.setState({ value: "" });
}}
```

**Comment by Evoque** [comment]
why closed when it won't resolve?
