### ISSUE TITLE
Upload component: thumbnail preview only shown when upload next image

### ISSUE THREAD

**Issue by psantos10** [ant-design/ant-design#20669]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-gates-30fed)

### Steps to reproduce
1 - Clique "Upload" to upload an image. 
2- Select the image to Upload

### What is expected?
Thumbnail image to be shown when upload completed. Like the Pictures Wall example here: https://ant.design/components/upload/#components-upload-demo-picture-card

### What is actually happening?
It does not show the thumbnail until you upload the next image or click to preview the previews image if exists. It only show the text "Uploading..." even when the upload is completed.

<img width="355" alt="Screenshot 2020-01-04 at 22 59 07" src="https://user-images.githubusercontent.com/374424/71772674-de2e1680-2f46-11ea-8c1c-1d72eda7f656.png">

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.2 |
| Browser | Brave Version 1.1.23 Chromium: 79.0.3945.88 (Official Build) (64-bit) |

**Comment by afc163** [comment]
```diff
-   const handleFileListChange = ({ fileList }) => setFileList(fileList);
+   const handleFileListChange = ({ fileList }) => setFileList([...fileList]);
```
