### ISSUE TITLE
Textarea with autoSize flickering in Firefox

### ISSUE THREAD

**Issue by inian** [ant-design/ant-design#20674]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dark-shadow-2n9mr)

### Steps to reproduce
Go to link in Firefox

### What is expected?
No flickering

### What is actually happening?
Flickering

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | all |
| System | mac |
| Browser | Firefox |

---
Seems to be okay in Chrome. Bug is only in Firefox

**Comment by yoyo837** [comment]
Can not to reproduce.

**Comment by inian** [comment]
Hi, can you click on the codesandbox link in Firefox browser on a mac? 
https://codesandbox.io/s/dark-shadow-2n9mr

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/20452#issuecomment-568954563

**Comment by yoyo837** [comment]
我这边不闪，只是一次只能拖着变化一下，然后就不动了，只能松手再拖。

**Comment by afc163** [comment]
@yoyo837 需要系统设置里打开滚动条。

**Comment by zombieJ** [comment]
Import `antd.min.css` since TextArea should have 100% width: https://codesandbox.io/s/stupefied-hooks-pid1f

Still deep check.

**Comment by inian** [comment]
Will this be ported over to the 3x version of antd as well? The latest version of 3x antd still has this bug

**Comment by afc163** [comment]
@inian 3.16.14

**Comment by inian** [comment]
It is not fixed in 3.26.14 - https://codesandbox.io/s/morning-microservice-vdypp (see in firefox)

**Comment by afc163** [comment]
Please import antd styles: https://codesandbox.io/s/sleepy-cookies-u4ekw

**Comment by sultangaleev** [comment]
https://codesandbox.io/s/sleepy-cookies-u4ekw
still not fixed for me even with imported styles:
Firefox 76.0
MacOS Catalina 10.15
Antd 3.26.14

**Comment by williamOnsare** [comment]
Experiencing the same issue of **antd TextArea** flickering on Firefox browser only, while it works well on Chrome
