### ISSUE TITLE
doc: email error

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#20678]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/spec/work-with-us-cn](https://ant.design/docs/spec/work-with-us-cn)

### Steps to reproduce
- UI/UE 设计师的 email 地址
- ADI 工程师的 email 地址
- 中英文版本都书写错误
- v4.0 仍存在
### What is expected?
- 正确书写

### What is actually happening?
- 书写错误

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
你是说那个`#`号吗？ 应该是故意的吧，避免爬虫发抓到邮箱地址发垃圾邮件。

**Comment by xrkffgg** [comment]
这样啊 😂😂
