### ISSUE TITLE
select placeholder position not correct

### ISSUE THREAD

**Issue by DiamondYuan** [ant-design/ant-design#20679]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/form-cn/#components-form-demo-register](https://next.ant.design/components/form-cn/#components-form-demo-register)

### Steps to reproduce
https://next.ant.design/components/form-cn/#components-form-demo-register

### What is expected?
正常

### What is actually happening?
正常

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | - |
| System | - |
| Browser | chrome / 79.0.3945.88 / 64  |

**Comment by ycjcl868** [comment]
Duplicate https://github.com/ant-design/ant-design/issues/20679
