### ISSUE TITLE
Table 功能组合使用时发生的问题

### ISSUE THREAD

**Issue by WittCsharp** [ant-design/ant-design#2068]
### span与scroll同时使用时

> 跨行或者跨列操作时，同时加入固定表头后，样式会发生混乱。

### 同时固定表头与左侧栏时
> 同时固定表头与左侧栏时,表头列无法左右移动

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by WittCsharp** [comment]
[span问题](http://codepen.io/Witt/pen/LZZeqY?editors=001)

[列固定问题](http://codepen.io/Witt/pen/EyyoJz?editors=001)

**Comment by afc163** [comment]
好的，看到了，着手修复ing

**Comment by afc163** [comment]
1. 问题一，你指定的列 colSpan 总数超过了总的列数，而且在固定表头时，需要指定列宽度，否则因为实现时分成了两个表格，难免有错误问题。http://codepen.io/anon/pen/MeeVZp?editors=001
