### ISSUE TITLE
图形化页面文案错误

### ISSUE THREAD

**Issue by hiyangguo** [ant-design/ant-design#20687]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/docs/spec/illustration-cn#%E5%85%83%E7%B4%A0%E7%BB%84%E4%BB%B6](https://next.ant.design/docs/spec/illustration-cn#%E5%85%83%E7%B4%A0%E7%BB%84%E4%BB%B6)

### Steps to reproduce
页面右侧的图片
![image](https://user-images.githubusercontent.com/15609339/71798760-2c99fd00-308e-11ea-951f-8ab5ec2c1eb7.png)

### What is expected?
圆角的数值是以8的倍数递增

### What is actually happening?
圆角的数值是以8的背书递增

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16 |
| System | osx |
| Browser | chrome |

**Comment by zombieJ** [comment]
@myeunhyuk
