### ISSUE TITLE
V4 Input allowclear属性在form validator校验下图标闪动

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#20680]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-kyvw8)

### Steps to reproduce
输入框输入即可

### What is expected?
不闪动

### What is actually happening?
闪动

| Environment | Info |
|---|---|
| antd | 4.0.0rc.0 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by yoyo837** [comment]
ref: #20017

**Comment by yoyo837** [comment]
只有验证过程ing 才会这样吧。

**Comment by fred8617** [comment]
@yoyo837 目前发现是这样的，required等没出现这个问题

**Comment by afc163** [comment]
<img width="275" alt="image" src="https://user-images.githubusercontent.com/507615/71794800-13895000-307e-11ea-8486-c9c32b9bf230.png">

到底是哪个版本

**Comment by fred8617** [comment]
@afc163 v4 rc。issue助手没这个选项，就忘改了

**Comment by afc163** [comment]
有的：
<img width="490" alt="image" src="https://user-images.githubusercontent.com/507615/71794904-84306c80-307e-11ea-80b0-ea55eb4d6b32.png">

**Comment by fred8617** [comment]
@afc163 我是说没有4.0.0rc.0的下拉选项 - -

**Comment by fred8617** [comment]
@afc163  找到了，都要拉到底了。。。。能不能往上提一提

**Comment by afc163** [comment]
靠搜索吧。

**Comment by zombieJ** [comment]
我去更新一下 issue helper。

**Comment by afc163** [comment]
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/507615/71801637-74248700-3096-11ea-9dbe-6fb2779175c9.png">

右边多了两个 `1`。

**Comment by zombieJ** [comment]
还没更新，这两个 1 应该是你上次填了没提交记录在 localStorage 里的。

**Comment by VoliBearCat** [comment]
@afc163 3.26.11版本存在该问题, 希望3.X版本也能修复这个问题

**Comment by VoliBearCat** [comment]
> @afc163 3.26.11版本存在该问题, 希望3.X版本也能修复这个问题
> ![image](https://user-images.githubusercontent.com/11676384/76743816-2cb12a00-67ae-11ea-9287-f655f2c2566f.png)

@afc163 @zombieJ Help!!!
