### ISSUE TITLE
Affix 组件 Fixed at the top of container 超出 container

### ISSUE THREAD

**Issue by Huihuawk** [ant-design/ant-design#20694]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/affix-cn/](https://next.ant.design/components/affix-cn/)

### Steps to reproduce
滚动容器到最底部，再滚动浏览器

### What is expected?
Affix 在 container 内

### What is actually happening?
滚动浏览器后，Affix 在 container 外
![image](https://user-images.githubusercontent.com/24917797/71803968-21020280-309d-11ea-974f-0c57cc58bef3.png)

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | latest |
| System | mac os |
| Browser | latest |

**Comment by afc163** [comment]
https://ant.design/components/affix-cn/#Affix-%E4%BD%BF%E7%94%A8-target-%E7%BB%91%E5%AE%9A%E5%AE%B9%E5%99%A8%E6%97%B6%EF%BC%8C%E5%85%83%E7%B4%A0%E4%BC%9A%E8%B7%91%E5%88%B0%E5%AE%B9%E5%99%A8%E5%A4%96%E3%80%82
