### ISSUE TITLE
antd官网更新日志日期错误

### ISSUE THREAD

**Issue by zcSkr** [ant-design/ant-design#20693]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/changelog-cn](https://ant.design/changelog-cn)

### Steps to reproduce
打开官网看更新日志

### What is expected?
3.36.6的更新日期是2020-01-03

### What is actually happening?
日期是2019-01-03

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.6 |
| System | mac |
| Browser | chrome |

**Comment by zcSkr** [comment]
<img width="652" alt="WeChat8d867a8366ffc3abe93350e9364b3313" src="https://user-images.githubusercontent.com/30515821/71802000-80f5aa80-3097-11ea-9bee-eb10fdd83283.png">

**Comment by yoyo837** [comment]
#20670 fix this. 官网部署后可见。
