### ISSUE TITLE
Datepicker not setting focus in other datepicker

### ISSUE THREAD

**Issue by Firetuy** [ant-design/ant-design#20707]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-o9dfy)

### Steps to reproduce
Select a date in the first datepicker, and then onChange will try to set focus in the second datepicker and vice-versa (using ref)

### What is expected?
Its expected that the focus works

### What is actually happening?
Focussing its not working (using refs)

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 12.0.0 |
| System | Windows 7 |
| Browser | Chrome |

**Comment by afc163** [comment]
You can try `setTimeout`: https://codesandbox.io/s/antd-reproduction-template-pueln

**Comment by Firetuy** [comment]
setting timeout works on datepicker, but the second datepicker cant focus in the button

https://codesandbox.io/s/antd-reproduction-template-mi09p
