### ISSUE TITLE
Input组件message不能国际化

### ISSUE THREAD

**Issue by imythu** [ant-design/ant-design#20704]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/imythu/input_bug](https://github.com/imythu/input_bug)

#### 步骤
- 1.从GitHub下载项目
- 2.yarn start
- 3.打开 [http://localhost:3000](http://localhost:3000)
- 4.输入框不要输入任何字符，点击登录，红色输入警告提示出现后，点击右上方语言切换按钮切换英文，会发现Input 组件的 message 国际化没有生效
#### 本项目中 Input组件代码实例，message 值如下设置
```ejs
<Form.Item>
	{getFieldDecorator('username', {
		rules: [{ 
    		required: true, message: i18n.get('prompt_input_username')}],
    	})(
			<Input
				whitespace={'true'}
				allowClear
				prefix={<Icon type='user' style={{ color: 'rgba(0,0,0,.25)' }} />}
					placeholder={i18n.get('prompt_input_username')}
			/>,
	)}
</Form.Item>
```

### What is expected?
Input 组件的 message能够像其 placeholder 值一样随着语言 locale 变化而变化

### What is actually happening?
Input 的提示信息 message 并不能支持国际化，只有第一次显示时会根据当前 locale 显示，之后 locale 变化并不会变化

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome 79.0.3945.88 |

---
Input 提示消息 message 国际化设置

**Comment by afc163** [comment]
I can't find any form code in https://github.com/imythu/input_bug/blob/master/src/App.js

**Comment by imythu** [comment]
代码库刚刚已经更新了

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/72415345-3b2f9500-37af-11ea-9647-cfa7c67bc612.png)

就是想要已经显示出来的验证信息，能实时同步国际化。倒不如实现成切换语音后重置表单验证信息！

**Comment by zombieJ** [comment]
同上，表单校验信息只与当时的 `validateTrigger` 设置的触发时机所对应，更改信息不会额外触发校验。如需动态设置语言，需要在设置后重新触发校验。

**Comment by Bonnie8ni** [comment]
請問要如何重新触发校验

**Comment by Bonnie8ni** [comment]
@zombieJ 請問重新觸發效驗是指哪個方式？

**Comment by mrhaoxiaojun** [comment]
遇到同样的问题，改用validator根据条件返回国际化信息，而不直接传递message

**Comment by shardul321** [comment]
![image_2022_08_03T12_55_44_263Z](https://user-images.githubusercontent.com/80515228/182613186-fd6968ac-aeb8-4647-bda0-f6202440c51f.png)

@mrhaoxiaojun  Could you please share how you use validator internationalized information according to the condition?
I have multiple languages like English, Japanese, etc.
