### ISSUE TITLE
Table，设置rowkey之后，rowkey为undefined会默认设置为index，有可能会和存在rowkey的条目冲突

### ISSUE THREAD

**Issue by liusiasi** [ant-design/ant-design#20716]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
**在采用ant.design的Table组件时，给table组件赋值了rowkey为id**
```js
<Table
  columns={columns}
  dataSource={this.state.data}
  pagination={false}
  rowKey={record => record.id}
/>
```
**初始数据格式如下**
```js
{
      key: `OLD_TEMP_ID_0`,
      image: image,
      audio: audio,
      id:2,
    }
```
**默认的data中有初始数据，显示效果如下，这些默认的数据都是有id的**
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200107101406820.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM2NDAwMjA2,size_16,color_FFFFFF,t_70)
**点击新建绘本，新建两个绘本，新建的数据条目没有id，数据格式如下**
```js
{
      key: `NEW_TEMP_ID_0`,
      editable: false,
      isNew: true,
      image: image,
      audio: audio,
    }
```
**新建成功两条绘本数据**
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200107101705659.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3FxXzM2NDAwMjA2,size_16,color_FFFFFF,t_70)
**然后删除第一个条目的时候就没有反应，删除第三个条目成功，再删除第一个条目的时候就报错**
![在这里插入图片描述](https://img-blog.csdnimg.cn/20200107102211538.png)
**后来发现 初始的第一条数据id为2，也就是key为2，后来新建了两条数据，设置了rowkey为id，ant.design的Table组件当检测到rowkey为undefined的情况下会自动将rowkey设置为index，所以第三条数据key为2，与第一条数据相同，导致后来删除数据的时候按照key操作会出现渲染错误的情况，将Table的rowKey设置为index之后就会有不同且唯一的key**

### What is expected?
当rowkey为undefined的时候可不可以不设置默认值index，或者设置默认值的时候可不可以设置一个随机数值。

### What is actually happening?
当设置一个rowkey为record中某一属性的时候，属性存在就会取值，不存在就会默认设置为index，使得两个条目的值可能会出现同样的key

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 3.23.1 |
| System | Windows 7 |
| Browser | Google Chrome 79.0.3945.88（正式版本） （64 位） |

**Comment by yoyo837** [comment]
新增行自行填充个临时id吧，如何？

**Comment by afc163** [comment]
@yoyo837 is right

**Comment by liusiasi** [comment]
> 新增行自行填充个临时id吧，如何？

感谢您的指导，但是在项目需求中新增的行没有id，只有初始数据编辑行有id。id是表示数据库里面某条指定数据的，如果新建创建了临时id，提交表单的时候需要在识别哪些是新建哪些是编辑。现在是以index作为rowkey解决这个问题。或者在重新创建一个唯一，存在且不重复的key作为rowkey

**Comment by yoyo837** [comment]
灵活一点：比如你为新增的行添加自定义id，假如以`temp-`开头，例`temp-123`, 在提交时可以识别一下前缀抹掉id再提交给服务器。又或者是补充一个`isNew` 属性来识别。

**Comment by liusiasi** [comment]
> 灵活一点：比如你为新增的行添加自定义id，假如以`temp-`开头，例`temp-123`, 在提交时可以识别一下前缀抹掉id再提交给服务器。又或者是补充一个`isNew` 属性来识别。

嗯，明白 感谢
