### ISSUE TITLE
多选 select 复制和粘贴内容

### ISSUE THREAD

**Issue by wuzhao** [ant-design/ant-design#2071]
比如邮箱地址的场景，经常需要拷贝出来并粘贴到其他邮件地址栏使用。

现在凤蝶遇到的问题是：
- 活动组里面有成员列表，是用多选的 select 存放的，类似邮件地址。
- 活动组管理员经常需要创建成员类似的新的活动组，所以很需要考虑的功能。

**Comment by afc163** [comment]
https://github.com/react-component/select/issues/36

**Comment by yiminghe** [comment]
自己旁边做个按钮：点击复制

**Comment by benjycui** [comment]
支持粘贴，但是复制还是额外加按钮把，选择 DOM 元素感觉很奇怪。

**Comment by benjycui** [comment]
antd 这边还要更新依赖和文档 https://github.com/react-component/select/commit/d86d6de449cef15022b467a0e16a3cb9cc7e0695

**Comment by yesmeck** [comment]
Released in 2.3.0.
