### ISSUE TITLE
3.23.1版本的Descriptions组件不加layout属性会报错，而官方文档并没有指出这是必要属性

### ISSUE THREAD

**Issue by fairySusan** [ant-design/ant-design#20715]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/descriptions-cn/](https://ant.design/components/descriptions-cn/)

### Steps to reproduce
无

### What is expected?
根据文档例子能正常使用Descriptions组件

### What is actually happening?
不能正常使用

| Environment | Info |
|---|---|
| antd | 3.23.1 |
| React | 16.9.0 |
| System | macos |
| Browser | chrome |

**Comment by yoyo837** [comment]
layout 有默认值的。
