### ISSUE TITLE
When the table uses both scroll and react-resizable, and table displacement meter

### ISSUE THREAD

**Issue by junjieit** [ant-design/ant-design#20719]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-microservice-ceeq9?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. 打开 [官方文档](https://ant.design/components/table-cn/#components-table-demo-resizable-column) 中的 CodeSandbox 代码
2. 在 `Table` 组件上添加 `scroll` 属性，让横向变为可滚动
3. 去掉 `columns` 数组中第二项的 `width`

- Open the online code in [Official Documentation](https://ant.design/components/table-cn/#components-table-demo-resizable-column)
- Add a `scroll` property to the `Table` component to make the landscape scrollable
- Remove the `width` of the second item in the `columns` array

### What is expected?
表格功能正常
Everything as work.

### What is actually happening?
表格错位
THeade And Tbody misplaced.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | React 16.12.0 |
| System | Mac 10.14.6 |
| Browser | Firefox DEV 72.0b11(64) |

**Comment by afc163** [comment]
不能去掉宽度。
