### ISSUE TITLE
antd@4.0.0-rc.0 Table 在显示与隐藏的过程出现闪烁

### ISSUE THREAD

**Issue by MinJieLiu** [ant-design/ant-design#20714]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-0vb95)

### Steps to reproduce
在 demo 中点击显示与隐藏按钮

在 Performance 中可看到 表格的 header 出现的瞬间是挤在一块的

![image](https://user-images.githubusercontent.com/6167727/71862279-42fa9400-3134-11ea-9c83-b324fb553ca3.png)

### What is expected?
不出现闪烁

### What is actually happening?
显示与隐藏的过程中有闪烁

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12 |
| System | mac |
| Browser | chrome |

**Comment by MinJieLiu** [comment]
#20744

**Comment by yoyo837** [comment]
Duplicated of #20744.

**Comment by zombieJ** [comment]
@yoyo837 , 两种的时机应该不太一样，需要再确认一下。
