### ISSUE TITLE
suffixIcon does not work when TreeSelect is multi-selecte

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#20723]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-leaf-pb6kb)

### Steps to reproduce
https://github.com/ant-design/ant-design/issues/18625#issuecomment-560858759

### What is expected?
-

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest |

---

**Comment by chinhoe** [comment]
不好意思 想问下是否有计划在近期里修好这问题吗？

**Comment by yoyo837** [comment]
@zombieJ rc-select的这个逻辑的原因, 我不熟不敢乱动：
```jsx
var mergedShowArrow = showArrow !== undefined ? showArrow : loading || !isMultiple && mode !== 'combobox';
```

Setting `showArrow` to true can fix this at the moment, https://codesandbox.io/s/nifty-leaf-pb6kb,

**Comment by yoyo837** [comment]
Maybe related issue #20711 .

**Comment by zombieJ** [comment]
Let's merge into #20711

**Comment by zombieJ** [comment]
Wait... Your example shows the suffixIcon:
<img width="534" alt="截屏2020-01-07下午7 50 41" src="https://user-images.githubusercontent.com/5378891/71893573-0310cc80-3187-11ea-89c4-73263b22c233.png">

**Comment by yoyo837** [comment]
@zombieJ Added `showArrow={true}`

**Comment by yoyo837** [comment]
This is for tracking in 4.0.

Not works: https://codesandbox.io/s/prod-moon-r1v57
Works: https://codesandbox.io/s/nifty-leaf-pb6kb

**Comment by yoyo837** [comment]
Please confirm again... @zombieJ

**Comment by zombieJ** [comment]
multiple mode always need use `showArrow` to display suffix icon is by design.

**Comment by yoyo837** [comment]
All right!

**Comment by yoyo837** [comment]
I’ll try to update the docs.

**Comment by chinhoe** [comment]
Just curious, is this issue going to be fixed for 3.x where the arrow is not showing and suffixIcon does not take effect?

**Comment by yoyo837** [comment]
@chinhoe https://github.com/ant-design/ant-design/issues/18625#issuecomment-527328633

**Comment by abhishekahuja87** [comment]
Hi I still see the issue exists with latest 4.x version- https://codesandbox.io/s/basic-usage-ant-design-demo-forked-dvd8c?file=/index.js
I see the click on the icon doesn't work, but click outside it works fine

Although i see its works fine in version 3.x- https://codesandbox.io/s/basic-usage-ant-design-demo-forked-l7pz2?file=/index.js

I alse see that the icon doesn't animate on click(options Expand and Collapse)

**Comment by 350832850** [comment]
> 



> Hi I still see the issue exists with latest 4.x version- https://codesandbox.io/s/basic-usage-ant-design-demo-forked-dvd8c?file=/index.js I see the click on the icon doesn't work, but click outside it works fine
> 
> Although i see its works fine in version 3.x- https://codesandbox.io/s/basic-usage-ant-design-demo-forked-l7pz2?file=/index.js
> 
> I alse see that the icon doesn't animate on click(options Expand and Collapse)

I have the same problem, how did you solve it ?
