### ISSUE TITLE
tree 组件被直接裁断, 并且没有办法显示省略号

### ISSUE THREAD

**Issue by Jiang-Xuan** [ant-design/ant-design#20727]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-satoshi-o5uxm)

### Steps to reproduce
1. 访问重现链接

### What is expected?
tree 组件不是直接裁断, 而是可以选择超出显示省略号或者是换行, 因为直接裁断对用户很不友好

### What is actually happening?
tree 组件被直接裁断了

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 |

---
![](https://beta.i.tuchuang.space/58c7af20ad3c9c7811c8e327517eb2f9.png)

**Comment by yoyo837** [comment]
Can not reproduce.

**Comment by Jiang-Xuan** [comment]
@yoyo837 我已经更新了 codesandbox, 你可以再次进入  https://codesandbox.io/s/practical-satoshi-o5uxm 🥂

**Comment by yoyo837** [comment]
就目前，可以给tree 下面的 li 加文本溢出样式来解决。

**Comment by Jiang-Xuan** [comment]
![Screen Shot 2020-01-07 at 17 49 51](https://user-images.githubusercontent.com/13357301/71886034-778f3f80-3176-11ea-80f0-7fa787ed89a5.png)

你可以按照这样试下, 在浏览器中会有 bug, 无法正常的显示省略号, 全部文字都会被隐藏

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/71886741-b07be400-3177-11ea-8c69-75d66c331e28.png)

**Comment by Jiang-Xuan** [comment]
所有的文字都被隐藏成了省略号, 这应该不是正常的文字溢出显示省略号

**Comment by afc163** [comment]
https://codesandbox.io/s/sad-carson-hmydh

**Comment by yoyo837** [comment]
https://codesandbox.io/s/stoic-brook-j77tz

**Comment by Jiang-Xuan** [comment]
@afc163 @yoyo837 感谢
