### ISSUE TITLE
希望穿梭框组件的titles API具备修改穿梭框左侧框和右侧框左上角文本内容

### ISSUE THREAD

**Issue by kingwubin** [ant-design/ant-design#20728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
穿梭框左上角文本内容的修改

### titles API传入数组，数组里面有两个元素，分别定义左侧内容和右侧内容，每个元素是一个数组，可以定义左侧或者右侧框的左右两个标题内容，可以是一个返回ReactNode函数，该函数传入两个参数，一个是选中项数，一个是总项数，也可以是一个文本字符串。
```javascript
<Transfer
targetKeys={targetKeys}
dataSource={transferDataSource}
selectedKeys={selectedKeys}
filterOption={filterOption}
className="tree-transfer"
titles={[
[string|(select, all) => ReactNode, string|(select, all) => ReactNode]
[string|(select, all) => ReactNode, string|(select, all) => ReactNode]
]}
>
```

**Comment by zombieJ** [comment]
<img width="789" alt="截屏2020-01-07下午4 47 36" src="https://user-images.githubusercontent.com/5378891/71881527-6aba1e00-316d-11ea-87c3-b2c002dec1dc.png">

**Comment by kingwubin** [comment]
![image](https://user-images.githubusercontent.com/19777851/71947699-aeae3100-3208-11ea-85b2-7d6d252c41bf.png)
现在title无法修改穿梭框左上角文本内容，但是现在项目有这方面的需求，左上角不是统一显示“n/m项”这样文本内容。

**Comment by zombieJ** [comment]
title 已经用过了，或许要换个名字。

**Comment by kingwubin** [comment]
好的,我尽快提供.

**Comment by morenyang** [comment]
I can take a look on this issue.
