### ISSUE TITLE
[4.0] DatePicker styling problem

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20726]
<img width="635" alt="image" src="https://user-images.githubusercontent.com/507615/71878804-88848480-3167-11ea-9009-ad9dddb29bfe.png">

- [ ] 选中样式上月/禁用样式重叠，建议改回。
- [ ] 底部多了一个分割线。

**Comment by afc163** [comment]
另外，链接处的 border-radius 可以改成方形，`2px 0 0 2px`。

<img width="55" alt="image" src="https://user-images.githubusercontent.com/507615/71878902-ca152f80-3167-11ea-9b57-779dae94f4f3.png">

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/71952732-b37be080-321a-11ea-9f57-c82fef9b706d.png)

看起来是 footer 没内容时，dom 还在
