### ISSUE TITLE
Can't surround inputs with other components since v4.0.0

### ISSUE THREAD

**Issue by Thanaen** [ant-design/ant-design#20738]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-not-working-template-input-4kwzf)

### Steps to reproduce
1. Type "p" in the input
2. Delete the previously entered letter

### What is expected?
Both steps should triggers validation errors.

### What is actually happening?
Nothing is happening.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | Windows 10 1809 |
| Browser | Firefox 71.0 |

---
See the equivalent code in v3:
https://codesandbox.io/s/antd-working-template-input-t7zwq

In the working example, if you type something in the input field, the validation is triggered, and the result is logged when the validation is passed. (the letter "p" triggers an error, but anything else will work)
In the broken example (reproduction link), the input validation isn't triggered when we're typing inside it.
I believe this is because Form.Item requires only one children, which prevents me to put text before and after the Input.

I could easily write stuff before and after the Form.Item (instead of the Input), but this would make it visually inconsistent.
How would you proceed to achieve what I achieved with ant design v3, using ant design v4?

Thanks in advance.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-not-working-template-input-sk6nf

https://next.ant.design/components/form/#components-form-demo-complex-form-control

**Comment by Thanaen** [comment]
Oh, it looks like I read the documentation too quickly, sorry!
Thanks for your codesandbox fork!
