### ISSUE TITLE
Tree of 4.0.0-rc.0 with Big Data has poor response speed during click/expand

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#20732]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/holy-feather-m9rkm?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Render a tree with Big data.
2. Click to expand the treeNode.
3. It will take over 2 seconds until the tree responses. The bigger the data is, the longer it takes.

### What is expected?
With virtual scroll, the tree should response quickly not only during scroll, but also in interaction like CLICK and EXPAND.

### What is actually happening?
With virtual scroll, the tree responses quickly during scroll, but has poor response speed in interaction like CLICK and EXPAND.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | Google Chrome  version79.0.3945.88 |

**Comment by zombieJ** [comment]
Thanks for feedback. It's a known issue with expanded calculation. We should handle this.

ref: https://github.com/react-component/tree/blob/6c6e1fd0c6f2656572aefb5fbc80085abf2f19b8/src/Tree.tsx#L839

**Comment by ghostg00** [comment]
I have also found this problem. When will it be fixed
