### ISSUE TITLE
Tables that have `onRow` and `onClick` for each row should have `cursor: pointer`

### ISSUE THREAD

**Issue by m-weeks** [ant-design/ant-design#20740]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When a table has an `onClick` set for a row, the cursor should change to inform the user that it is clickable. Without this, it is not evident that the row is clickable, without the developer adding CSS for each table that has `onClick` set on the rows.

### What does the proposed API look like?
It should be as simple as adding a new CSS class to the rows when an `onClick` is specified. Perhaps `.ant-table-row-interactive`.

**Comment by afc163** [comment]
You can add it by youself by `rowClassName`.

**Comment by m-weeks** [comment]
Would it not be best for user experience though that all clickable rows are clearly clickable by default?

**Comment by AleksandrHovhannisyan** [comment]
Why was this ever closed? :/

**Comment by abhilashlr** [comment]
How do you set an active class for a row that was clicked? Or should we consume `selection` based table?

**Comment by hekmatnajafi** [comment]
you may use `style` or `rowClassName`

eg: `style={{cursor: "pointer"}}`

**Comment by RaynorCraft** [comment]
You may wrap it inside a styled component like this 

```
import { Table as AntDTable } from 'antd'

export const Table = styled(AntDTable)`
  ${(props) => {
    const onRowImplementation = props.onRow && props.onRow({})
    if (onRowImplementation?.onClick) {
      return `
        tbody tr:hover {
          cursor: pointer;
        }
        `
    }
  }}
`
```

**Comment by portolucas** [comment]
> You may wrap it inside a styled component like this
> 
> ```
> import styled from 'styled-components'
> import { Table as AntDTable } from 'antd'
> 
> export const Table = styled(AntDTable)`
>   ${(props) => {
>     const onRowImplementation = props.onRow && props.onRow({})
>     if (onRowImplementation?.onClick) {
>       return `
>         tbody tr:hover {
>           cursor: pointer;
>         }
>         `
>     }
>   }}
> `
> ```

It works!

**Comment by mostlylikeable** [comment]
In case it's useful, with ant v4.x, it seems that `onCell` in column defs should work:
```ts
const columns: ColumnsType<Foo> = [
  {
    dataIndex: 'id',
    key: 'id',
    onCell: () => ({ hidden: true }),
  },
  {
    dataIndex: 'bar',
    key: 'bar',
  },
]

export const FooTable = ({ data }: { data: Foo[] }) => {
  return (
    <Table
      rowKey="id"
      columns={columns}
      dataSource={data}
      onRow: {{
        onClick: (row, i) => console.log(`Row ${i} clicked`, row)
      }}
    />
  )
}
```
