### ISSUE TITLE
表格单元格内渲染 DatePicker 组件，打开日期面板，然后滚动表格内容，日期面板不会随之移动位置，产生错位

### ISSUE THREAD

**Issue by yangchch6** [ant-design/ant-design#20746]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8 链接右侧预览一直白屏)

## 复现代码：
```
import React , {Component} from 'react';
import { Table, DatePicker } from 'antd';
import "antd/dist/antd.css";

const dataSource = [
  {
    key: '1',
    name: '胡彦斌',
    age: 1,
    address: '西湖区湖底公园1号',
  },
  {
    key: '2',
    name: '胡彦祖',
    age: 2,
    address: '西湖区湖底公园1号',
  },
  {
    key: Math.random() * 10,
    name: '胡彦祖',
    age: 3,
    address: '西湖区湖底公园1号',
  },
  {
    key: Math.random() * 10,
    name: '胡彦祖',
    age: 4,
    address: '西湖区湖底公园1号',
  },
  {
    key: Math.random() * 10,
    name: '胡彦祖',
    age: 5,
    address: '西湖区湖底公园1号',
  },
  {
    key: Math.random() * 10,
    name: '胡彦祖',
    age: 6,
    address: '西湖区湖底公园1号',
  },
  {
    key: Math.random() * 10,
    name: '胡彦祖',
    age: 7,
    address: '西湖区湖底公园1号',
  }
];


class App extends Component {
  constructor(props) {
    super(props);
  }
  columns = [
    {
      title: '姓名',
      dataIndex: 'name',
      key: 'name',
      render: () => {
        return <DatePicker />
      }
    },
    {
      title: '年龄',
      dataIndex: 'age',
      key: 'age',
    },
    {
      title: '住址',
      dataIndex: 'address',
      key: 'address',
    },
  ];
  render(){
    return(
      <Table dataSource={dataSource} columns={this.columns} scroll={{ y: 250 }}/>
    )
  }
}

export default App;
```

## 复现步骤：

1. 点开一个日期面板，保持打开状态
2. 滚动表格滚动条

### What is expected?
日期面板能够跟随日期输入框一起移动

### What is actually happening?
滚动表格的时候，日期面板没有移动位置，但日期输入框移动了位置，造成错位现象。

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | react: 16.12.0 |
| System | mac OS |
| Browser | Chrome 版本 79.0.3945.88（正式版本） （64 位） |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F
