### ISSUE TITLE
v4 table在transfer中的问题

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#20743]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-61lh9)

### Steps to reproduce
点击按钮有机会复现

### What is expected?
empty组件有时候宽度计算不准确

### What is actually happening?
计算准确，并且动画是否可以优化？

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.8  |
| System | win |
| Browser | chrome |

---
当scroll设置x true,以及tableLayout为auto并且在modal->transfer中会出现问题，也有可能是我用法问题

**Comment by fred8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/71939144-b7910980-31ec-11ea-8a3c-2743306b4ae2.png)

**Comment by MinJieLiu** [comment]
![未命名](https://user-images.githubusercontent.com/6167727/71945212-2d9f6b80-3201-11ea-9d33-2a3056f87342.gif)

**Comment by fred8617** [comment]
@MinJieLiu 
![image](https://user-images.githubusercontent.com/35049517/71945364-9850a700-3201-11ea-910c-99978affa4bf.png)
这个看脸。。
