### ISSUE TITLE
add flyout extra form to Input.Search to allow advanced search

### ISSUE THREAD

**Issue by herbertpimentel** [ant-design/ant-design#20742]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
allows rich UI seach feature with extra props direct from the input.search as a flyout just like gmail does see it here https://drive.google.com/file/d/1Gjh0N8uQA1bY6EL6WXDd5zNNiu8VpfHX/view?usp=sharing

### What does the proposed API look like?
Example of gmai like search input https://drive.google.com/file/d/1Gjh0N8uQA1bY6EL6WXDd5zNNiu8VpfHX/view?usp=sharing

add a new property to Input.Search to allow specify an extra node like so:

```jsx
<Input.Search extra={( 
   <form>
     Start date: <DatePicker />
     End date: <DatePicker />
     ...
    <Button>Search</Button>
  </form>
)} />
```

**Comment by afc163** [comment]
Try Input.Group

**Comment by herbertpimentel** [comment]
@afc163  I think this is not the same idea. Please try take a look at the image in the link. I really belive we cannot achieve a similar result using input.group

**Comment by afc163** [comment]
It is better way to compose your own component instead of adding extra to Search component in that case. https://ant.design/components/form/#components-form-demo-customized-form-controls
