### ISSUE TITLE
Table's column className and rowClassName don't work on antd 4.0 RC

### ISSUE THREAD

**Issue by hsluoyz** [ant-design/ant-design#20756]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/table-bug-ni1gu)

### Steps to reproduce
See the link

### What is expected?
See row colors.

![image](https://user-images.githubusercontent.com/3787410/71956576-7c133100-3226-11ea-8ff3-c2b54bf10b3a.png)

### What is actually happening?
No row colors.

![image](https://user-images.githubusercontent.com/3787410/71956612-8d5c3d80-3226-11ea-94f4-ef89a2b75ee6.png)

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | Win 10 x64 |
| Browser | Chrome 79.0.3945.88 |

**Comment by zombieJ** [comment]
<img width="458" alt="截屏2020-01-09上午11 16 38" src="https://user-images.githubusercontent.com/5378891/72034981-8807fd00-32d1-11ea-826a-d9e581557b12.png">

`className` & `rowClassName` works but current table has default background color which overwrite the background by select priority.

CC @ycjcl868

**Comment by hsluoyz** [comment]
Before it get fixed, is there a workaround for now? Like disable the default background color?

**Comment by zombieJ** [comment]
Rise the priority: https://codesandbox.io/s/table-bug-z6kcl

**Comment by zombieJ** [comment]
Since new Table use sticky to realize fixed effect. td always set the background color. First to reduce cell background priority and then update change log that which is breaking change about rowClassName background color.
