### ISSUE TITLE
bug: docs in dark style 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#20761]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/button-cn/](https://next.ant.design/components/button-cn/)

### Steps to reproduce
- 打开网站
- 选择暗黑模式

### What is expected?
- 按钮显示，颜色同其他为灰色

### What is actually happening?
3 个功能按钮 无法直接看出

- CodePen 颜色与背景一致
- CodeSandBox  颜色与背景一致
- 显示代码 颜色与 背景一致

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
没懂，具体是什么问题。

<img width="272" alt="image" src="https://user-images.githubusercontent.com/507615/72034482-0f547100-32d0-11ea-9a1a-40d01c0734fd.png">

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/72034662-999cd500-32d0-11ea-838a-b2a8df24fc23.png)

**Comment by xrkffgg** [comment]
![](https://github.com/xrkffgg/Kimg/blob/master/ant-design/2020.01/color.png?raw=true)

我看着是这样的

**Comment by afc163** [comment]
浏览器版本和操作系统分别是？

**Comment by xrkffgg** [comment]
@afc163 
mac 10.15.2
chrome 79.0.3945.88

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/72043693-c19a3180-32ec-11ea-9cbd-45d95d1ceb68.png)

看着正常

**Comment by yoyo837** [comment]
我个人这边三大浏览器都不行，macOS 10.15.2, 浏览器都是最新版本。

**Comment by zombieJ** [comment]
@yoyo837 ，能录屏不？让我们看看操作步骤

**Comment by afc163** [comment]
我们的锅，马上修复。

**Comment by zombieJ** [comment]
![image](https://user-images.githubusercontent.com/5378891/72044735-8a794f80-32ef-11ea-939d-81806c7fa1e9.png)

（啥，已经找到原因了?!...~~）

**Comment by ycjcl868** [comment]
原来是这样

**Comment by xrkffgg** [comment]
![](https://user-images.githubusercontent.com/5378891/72044735-8a794f80-32ef-11ea-939d-81806c7fa1e9.png)

**Comment by yoyo837** [comment]
![](https://user-images.githubusercontent.com/5378891/72044735-8a794f80-32ef-11ea-939d-81806c7fa1e9.png)

**Comment by ycjcl868** [comment]
复现了  
![image](https://user-images.githubusercontent.com/13595509/72044981-14c1b380-32f0-11ea-9406-4c9242fec479.png)

**Comment by yoyo837** [comment]
@zombieJ 操作没啥特别的，就点一下月亮就这样了。
