### ISSUE TITLE
unexpected warning in Descriptions

### ISSUE THREAD

**Issue by kagawagao** [ant-design/ant-design#20769]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-gzfex)

### Steps to reproduce
- set `Descriptions` `span` as `3`
- set `Descriptions.Item` `span` as `1` 
```jsx
    <Descriptions span={3}>
      <Descriptions.Item span={1} label="测试">数据</Descriptions.Item>
    </Descriptions>
```

https://github.com/ant-design/ant-design/blob/37b61c1adae5fa3aee96f39ceda765dd79349b0d/components/descriptions/index.tsx#L92-L96

### What is expected?
no warnings

### What is actually happening?
```
Warning: [antd: Descriptions] Sum of column `span` in a line exceeds `column` of Descriptions. 
    in Context.Consumer (created by Descriptions)
    in Descriptions
```

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | 81.0.4020.0 |

**Comment by zombieJ** [comment]
It should warning since your Item span summary is not full with 3. But warning message should update.

**Comment by ngotuandev** [comment]
At antd 5.3.3
in Descriptions has span = {{ xs: 2 }}, it resolved my problem
