### ISSUE TITLE
Table custom components  do not cache component when pass React.memo

### ISSUE THREAD

**Issue by FINAs** [ant-design/ant-design#20773]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-firefly-c5il6)

### Steps to reproduce
There are two tables in above link, open the console in right panel,click the sort arrow to check log.

### What is expected?
Both TableBodyWrapper log in render and shouldComponentUpdate or areEqual function.

### What is actually happening?
First table logs 'ClassComponent -- shouldUpdate ' and 'ClassComponent -- render'.
But second table  logs 'memoFunc -- render ' only.

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | lastest |
| System | windows 10 |
| Browser | chrome |

---
It seems table cached wrapper component if pass Class name(string?),but renew  when pass memoFunc(object ref?).

PS:
I do need a solution to bind some props in TableBodyWrapper. But Class can't bind any props,is it available in React.memo ?
Thanks.

**Comment by zombieJ** [comment]
```diff
const memoFunc = React.memo(
  function(props) {
    console.log("memoFunc -- render");
    return (
      <tbody className="ant-table-tbody" key={props.index}>
        {props.children}
      </tbody>
    );
  },
  function areEqual(preProps, nextProps) {
    console.log("memoFunc -- areEqual");
+    return true;
  }
);
```

**Comment by FINAs** [comment]
> ```diff
> const memoFunc = React.memo(
>   function(props) {
>     console.log("memoFunc -- render");
>     return (
>       <tbody className="ant-table-tbody" key={props.index}>
>         {props.children}
>       </tbody>
>     );
>   },
>   function areEqual(preProps, nextProps) {
>     console.log("memoFunc -- areEqual");
> +    return true;
>   }
> );
> ```

Hi, i have add this snippet in my demo.But the log print the same result as before.
Only `memoFunc -- render` .

**Comment by zombieJ** [comment]
Hi @FINAs, 
Thanks for reply. It seems a bug of v3 table not support memo component. But we may not fix this since it's not a critical issue and may cause potential bug if fix this.

Test in v4, it work as expect: https://codesandbox.io/s/ecstatic-rosalind-rvrx6

**Comment by FINAs** [comment]
very useful
