### ISSUE TITLE
progress组件，增加successPercent颜色自定义功能

### ISSUE THREAD

**Issue by yangdanself** [ant-design/ant-design#20770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
增加successPercent颜色自定义可使组件更灵活，ui更丰富

### What does the proposed API look like?
successStrokeColor

**Comment by Sanjay-Jeyavel** [comment]
Hi!
It's my understanding that the feature proposed is to allow color customization of the progress percent text i.e 70%? I could only use google translate to understand the feature proposed.
 I believe antd progress renders rc-progess for the circle and line progress bars. rc-progress seems to expose props to change only trail and stroke color.
I would love to work on this feature if you could clarify more on it.

**Comment by morenyang** [comment]
Hi @yangdanself , could you describe more details?

**Comment by shaodahong** [comment]
I don't think we need a new prop to set the success stroke color

`strokeColor` can also be used 

```jsx
<Progress
      strokeColor="green"
      percent={50}
    />
```

or

```jsx
<Progress
      status={isSuccess ? "normal" : "exception"}
      strokeColor={isSuccess ? "green" : "red"}
      percent={50}
    />
```

**Comment by fireairforce** [comment]
I will work on this~

**Comment by fireairforce** [comment]
solved at：https://github.com/ant-design/ant-design/pull/24655
