### ISSUE TITLE
Missing role attribute on <div class="ant-menu-submenu-title"> is causing W3C validation error

### ISSUE THREAD

**Issue by aaronsarnat** [ant-design/ant-design#20779]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://validator.w3.org/nu/?doc=https%3A%2F%2Fant.design%2F#vnuId2](https://validator.w3.org/nu/?doc=https%3A%2F%2Fant.design%2F#vnuId2)

### Steps to reproduce
1. Build a project that uses `<Menu mode="horizontal">` dropdown structure
2. Validate it through https://validator.w3.org/
3. See validation errors that look like this:
    ```
    Error: Element div is missing one or more of the following attributes: role.
    <div class="ant-menu-submenu-title" aria-expanded="false" aria-haspopup="true">
    ```

### What is expected?
Ant output should be W3C valid markup

### What is actually happening?
Some Ant output is not W3C valid markup

| Environment | Info |
|---|---|
| antd | 3.25.1 |
| React | 16.9.0 |
| System | Mac OS 10.14.6 |
| Browser | Chrome 79.0.3945.117 |

---
I discovered this validation bug on a project I'm building for work. I checked the Ant Design website to see if the bug existed there too, and it did. That's why I linked above to the W3C validator pointing at https://ant.design/

**Comment by afc163** [comment]
@aaroncawte Could you send us a PR?

**Comment by aaroncawte** [comment]
> @aaroncawte Could you send us a PR?

Wrong Aaron, perhaps? 😂(cc: @aaronsarnat)

**Comment by aaronsarnat** [comment]
Upon further investigation, the error appears to be inherited from `rc-menu`. So it seems the fix would need to happen in that repo, then `antd` would need to be updated to use the latest `rc-menu`.

**Comment by aaronsarnat** [comment]
@afc163 Upon further investigation, the error appears to be inherited from `rc-menu`. So it seems the fix would need to happen in that repo, then `antd` would need to be updated to use the latest `rc-menu`.

**Comment by yoyo837** [comment]
You can send PR to [rc-menu](https://github.com/react-component/menu).
