### ISSUE TITLE
RangePicker focus start date input entry on open

### ISSUE THREAD

**Issue by renatoruk** [ant-design/ant-design#20778]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature would make the behaviour of DatePicker and RangePicker a bit more similar. 
Currently, by clicking on closed DatePicker input does get focused. But for RangePicker, an additional click on input after opening the popup is needed to get the focus for entry with a keyboard.

### What does the proposed API look like?
I would prefer that we don't change the API for this, just the behaviour. I believe UX can be improved by removing that "extra click". I saw that for 4.0 that a similar behaviour for a new RangePicker is planned, but until then, what can we do to achieve that behaviour with version ^3.26.6?

**Comment by afc163** [comment]
We won't optimize behaviour in 3.x now, please try to upgrade.

**Comment by renatoruk** [comment]
OK, that's reasonable. Thanks for the quick response.
