### ISSUE TITLE
[4.0] Different behaviours on `Select` and other input components

### ISSUE THREAD

**Issue by stonexer** [ant-design/ant-design#20776]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-input-4-ijkgo)

### Steps to reproduce
Antd 4

https://codesandbox.io/s/antd-input-4-ijkgo

Antd 3

https://codesandbox.io/s/antd-input-3-yt2dv

### What is expected?
Same behaviour in `Controlled` ways

### What is actually happening?
Select presents `Controlled` in 3.x while `Uncontrolled` in 4.x

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | - |
| System | - |
| Browser | - |

---
IMO It would be better if they behave as same as native form components. Currently there are no clear or consistent results in both `Input` and `Select`, `3.x` and `4.x`.

**Comment by zombieJ** [comment]
Hmmm. Input seems should be uncontrolled also.

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/commit/31ee4bea303c5d1ec3ad0567f76ef356f60f551d

**Comment by zombieJ** [comment]
Seems https://github.com/ant-design/ant-design/commit/f10cb764e4bc91a24e1fdf66d3370c47cb7af178 has already change
