### ISSUE TITLE
V4 Need export types from table

### ISSUE THREAD

**Issue by Renderz** [ant-design/ant-design#20771]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-framework-e61ef)

### Steps to reproduce
cannot import TableProps from 'antd/lib/table' or 'antd/es/table'

### What is expected?
TableProps can be imported from 'antd/lib/table' or 'antd/es/table'

### What is actually happening?
cannot import TableProps from 'antd/lib/table' or 'antd/es/table'

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | mac |
| Browser | chorme |

**Comment by LunaGod** [comment]
```
import * as React from "react";
import { render } from "react-dom";
import { Table } from "antd";
import { TableProps } from "antd/lib/table/Table";

import "antd/dist/antd.css";
import "./styles.css";

interface Col {
// column 项的类型
}
interface ExTableProps extends TableProps<Col> {}

const ExTable: React.FC<ExTableProps> = props => {
  return <Table {...props}  />;
};

const rootElement = document.getElementById("root");
render(<ExTable />, rootElement);
```

**Comment by yoyo837** [comment]
由antd输出直接可用的类型感觉更好吧。

**Comment by Renderz** [comment]
> 由antd输出直接可用的类型感觉更好吧。

我也觉得, 最好是统一位置输出类型.

**Comment by zombieJ** [comment]
TS 定义是会随着代码重构而变化的，不适合直接在顶层暴露出来。但是在组件层保留，用于服务深度用户。

**Comment by fjc0k** [comment]
+1，希望以后可以这样：

```js
import { Table, TableProps, Input, InputProps } from "antd"
```
