### ISSUE TITLE
https://npmcdn.com/antd/dist/antd.min.css body class 污染

### ISSUE THREAD

**Issue by TangMonk** [ant-design/ant-design#2077]
其中有段css定义body的属性为

![image](https://cloud.githubusercontent.com/assets/3498786/16138841/3be83bec-3474-11e6-911c-932669a5dbb4.png)

想在项目单个页面里使用ant-design, 然后这会导致之前的css错乱, 我觉得应该加上个namespace避免这种问题

**Comment by afc163** [comment]
antd 一直是这样的，不需要全局样式的话，可以自行引入各个组件的子样式。

**Comment by TangMonk** [comment]
@afc163 多谢

**Comment by secreter** [comment]
单独引用子样式也有bug，有的图标是全局定义的，单独引用的时候就会失效。建议还是加上上全局作用域，不然项目中如果还用到别的类库，简直就是坑

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4331
