### ISSUE TITLE
table表格带有fixed固定列.切换size属性会产生样式错乱

### ISSUE THREAD

**Issue by guiyu1230** [ant-design/ant-design#20788]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-firefly-0gdik?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1.  设置带有fxied属性固定列表格. 且列足够多, 能横向滚动
2.  切换table size属性.  会使得样式错乱 (fixed列的size样式不会跟随切换)

### What is expected?
切换table size属性.  样式依然整齐

### What is actually happening?
切换table size属性.  样式错乱 (fixed列的size样式不会跟随切换)

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome  79.0.3945.88 |

**Comment by guiyu1230** [comment]
@zombieJ    不好意思  其实里面还有另外一个问题 我所有列设置了宽度总计1100  我scroll.x设了 1300 
滚动列和固定列之间会有空白

**Comment by zombieJ** [comment]
> @zombieJ 不好意思 其实里面还有另外一个问题 我所有列设置了宽度总计1100 我scroll.x设了 1300
> 滚动列和固定列之间会有空白

总的宽度需要大于 scroll 的值。

**Comment by Tobycct** [comment]
table组件都设置了固定列宽, 列对不齐, 设置fixed后更为严重, 有时还会错位, 望修复, 不知道别人遇到过吗?我第一次用

**Comment by zombieJ** [comment]
v3 版本为了兼容 IE 使用了模拟的方式实现行高同步，目前无法解决。v4 已经没有这个问题了。

Duplicate of #14859
