### ISSUE TITLE
Modal组件中使用umi-plugin-locale的formatMessag()进行多语言化时报错

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design#20782]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.暂无.com](http://www.暂无.com)

### Steps to reproduce
Modal组件中使用umi-plugin-locale的formatMessag()进行多语言化时报错：
[React Intl] Could not find required intl object. needs to exist in the component ancestry.

### What is expected?
期望不要报错。

### What is actually happening?
不报错

| Environment | Info |
|---|---|
| antd | 3.26.3 |
| React | React 16.12.0 |
| System | win10 |
| Browser | chrome |

**Comment by effapp** [comment]
不会创建sandbox，我是在实际的项目中碰到的这个问题。

**Comment by yoyo837** [comment]
很难开展定位工作。sandbox不会试一试就会了。

**Comment by afc163** [comment]
你可以通过点击 此处 创建一个 codesandbox 或者**提供一个最小化的 GitHub 仓库**。

**Comment by effapp** [comment]
我在百度上搜索到了同样的问题：
https://segmentfault.com/q/1010000016492693

**Comment by afc163** [comment]
这种场景用 Modal 不要用 Modal.xxx 。

**Comment by afc163** [comment]
#17308
