### ISSUE TITLE
AutoComplete input space weird

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#20785]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/auto-complete-cn/#components-auto-complete-demo-basic](https://next.ant.design/components/auto-complete-cn/#components-auto-complete-demo-basic)

### Steps to reproduce
![Kapture 2020-01-09 at 10 17 44](https://user-images.githubusercontent.com/14831261/72032260-cbf70400-32c9-11ea-8580-56a9190c5935.gif)

1. `control mode` input space
2. delete `control mode` space
3. `input here` input space

### What is expected?
normal

### What is actually happening?
weird

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.9 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by zombieJ** [comment]
It's demo logic not a bug:
<img width="423" alt="截屏2020-01-09上午11 31 30" src="https://user-images.githubusercontent.com/5378891/72035715-a2db7100-32d3-11ea-8c92-59228ae8bef9.png">
