### ISSUE TITLE
message 隐藏时阴影被切割

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20798]
https://ant.design/components/message-cn/

1. 点开一个 message。
2. 等待关闭。
3. 仔细观察阴影部分，会在消失的时候被切割掉。

version: 3.x

**Comment by shaodahong** [comment]
Modal 也有这种情况

**Comment by GFwer** [comment]
我看 [4.x](https://next.ant.design/components/message-cn/) 也有这种情况，阴影被动画的`overflow:hidden`给裁了，删掉应该就好了
[index.less#L57](https://sourcegraph.com/github.com/ant-design/ant-design/-/blob/components/message/style/index.less#L57:33)

```diff
  &-notice.move-up-leave.move-up-leave-active {
-   overflow: hidden;
    animation-name: MessageMoveOut;
    animation-duration: 0.3s;
  }
```
