### ISSUE TITLE
suffixIcon attribute not working on TreeSelect component

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#20797]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select-cn/](https://ant.design/components/tree-select-cn/)

### Steps to reproduce
Add Icon component to suffixIcon

### What is expected?
icon show on suffix

### What is actually happening?
nothing happens

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.8.6 |
| System | Mac os 10.13.6 |
| Browser | chrome |

**Comment by zombieJ** [comment]
`showArrow`

**Comment by zombieJ** [comment]
Duplicate of #20723
