### ISSUE TITLE
V4 table doesn't update the UI when a dataSource row is deleted via splice()

### ISSUE THREAD

**Issue by hsluoyz** [ant-design/ant-design#20793]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/table-row-delete-bug-x4bv2)

### Steps to reproduce
See the link

![image](https://user-images.githubusercontent.com/3787410/72040453-8c3d1600-32e3-11ea-9d09-e7d119b1a7bf.png)

### What is expected?
The table row is deleted in UI.

### What is actually happening?
The table row is NOT deleted in UI.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | Win 10 x64 |
| Browser | Chrome 79.0.3945.88 |

**Comment by zombieJ** [comment]
https://reactjs.org/docs/optimizing-performance.html#the-power-of-not-mutating-data
