### ISSUE TITLE
Progress 进度条IE8 下js报错

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2079]
代码如下：
import React from 'react';
import ReactDOM from 'react-dom';
import {Progress} from 'antd';
const exportArr = {
  head: React.createClass({
    getInitialState() {
      return {
        percent: 0,
      };
    },
    render(){
        return (
            <Progress type="circle" percent={this.state.percent}/>
        )
    }
  }),
}
ReactDOM.render(<exportArr.head />, document.getElementById('drowlist-menu'));

JS报如下错：
SCRIPT438: 对象不支持“createElementNS”属性或方法 
common.js, 行22 字符21947

**Comment by afc163** [comment]
IE8 不支持 svg，不要使用 Progress circle。
