### ISSUE TITLE
自定义react   typescript开发环境，ant-design设置了按需加载，但是如果引入多个组件，只有最后一个组件有样式！

### ISSUE THREAD

**Issue by WUSO01** [ant-design/ant-design#20807]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/WUSO01/react-typescript-ant-design-issue](https://github.com/WUSO01/react-typescript-ant-design-issue)

### Steps to reproduce
引入多个组件，只有最后一个组件有样式。
webpack配置如下：
```javascript
const tsImportPluginFactory = require('ts-import-plugin')

module.exports = {
  module: {
    rules: [
      {
        test: /\.(ts|tsx)$/,
        loader: 'ts-loader',
        options: {
          transpileOnly: true,
          getCustomTransformers: () => ({
            before: [
              tsImportPluginFactory({
                libraryName: 'antd-mobile',
                libraryDirectory: 'lib',
                style: 'css'
              })
            ]
          }),
          compilerOptions: {
            module: 'es2015',
            sourceMap: true
          }
        },
        exclude: /node_modules/
      },
    ]
  }
}
```

组件代码：
```javascript
import { Tag, Button } from 'antd-mobile'

function App() {
  return (
    <div>
      <Button type='primary'>primary</Button>
      <Tag>Selected</Tag>
    </div>
  )
}
```

### What is expected?
实际应该每个引入的组件，都能有自己的样式

### What is actually happening?
但实际只有最后引入的组件有样式。 如图所示：![issue](https://user-images.githubusercontent.com/21070775/72074446-e6ae9480-332c-11ea-8696-5a3d9b72266e.png)

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12.0 |
| System | macos |
| Browser | chrome79 |

**Comment by zombieJ** [comment]
https://ant.design/docs/react/introduce-cn#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD

如果不使用 `babel-plugin-import`，则需要手工引入样式。

**Comment by WUSO01** [comment]
> https://ant.design/docs/react/introduce-cn#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD
> 
> 如果不使用 `babel-plugin-import`，则需要手工引入样式。

那`ts-import-plugin`这个库存在的意义在于？

**Comment by afc163** [comment]
建议提给 ts-import-plugin 的作者。

**Comment by Brooooooklyn** [comment]
@WUSO01  https://github.com/webpack-contrib/style-loader/issues/445
