### ISSUE TITLE
Any way to workaround this checkable tree disabled item issue?

### ISSUE THREAD

**Issue by panlina** [ant-design/ant-design#20800]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

---
I'm sorry to start another issue but I didn't get reply from previous post for long and I felt hard(if possible) to workaround it. Can you give some thought? Thanks.

Detailed descriptions are omitted. See original issue #20299. Feel free to move on to original issue and close this.

**Comment by afc163** [comment]
Duplicate of #20299
