### ISSUE TITLE
Cascader能否增加expand方法或者自动判断如果子级只有一项则自动选择该项。

### ISSUE THREAD

**Issue by eaTong** [ant-design/ant-design#2080]
有这么个需求：
本身有三层数据，有部分数据第二层只有一条。然后则觉得能否选择只有一条数据的那一层自动展开第三层？
类似于淘宝的地址选择控件。
![qq 20160617112550](https://cloud.githubusercontent.com/assets/17243933/16139858/4a68a850-347e-11e6-995f-342fb3bc7b26.jpg)
如图：选择第一个北京市之后第二个北京市也自动选择，然后弹出第三层。

我通过onChange和设置value可以实现input的值的改变，但是无法让第三层主动弹出。

**Comment by afc163** [comment]
重新安装 antd，然后下面的代码是有效的。

```js
import { Cascader } from 'antd';

const options = [{
  value: 'zhejiang',
  label: '浙江',
  children: [{
    value: 'hangzhou',
    label: '杭州',
    children: [{
      value: 'xihu',
      label: '西湖',
    }],
  }],
}, {
  value: 'jiangsu',
  label: '江苏',
  children: [{
    value: 'nanjing',
    label: '南京',
    children: [{
      value: 'zhonghuamen',
      label: '中华门',
    }],
  }],
}];

const App = React.createClass({
  getInitialState() {
    return {
      value: [],
    };
  },
  onChange(value, selectedOptions) {
    const lastSelected = selectedOptions[selectedOptions.length - 1];
    if (lastSelected.children && lastSelected.children.length === 1) {
      value.push(lastSelected.children[0].value);
      this.setState({ value });
      return;
    }
    this.setState({ value });
  },
  render() {
    return (
      <Cascader options={options} value={this.state.value} changeOnSelect onChange={this.onChange} />
    );
  },
});

ReactDOM.render(<App />, document.getElementById('container'));
```

**Comment by eaTong** [comment]
![qq 20160617152547](https://cloud.githubusercontent.com/assets/17243933/16143520/cc569ce8-349f-11e6-8b68-c41c79cd7845.jpg)
现在的效果是这样，下面的值确实会变，但是第三级不会展开，当前版本是1.4.1.刚更新的。。

**Comment by afc163** [comment]
用的是 npm 上的 antd？

**Comment by eaTong** [comment]
是的，通过npm安装的，刚才也确实将node_modules中的文件清空了，然后重新安装了一遍。。。

**Comment by afc163** [comment]
确认下本地 rc-cascader 的版本是否是 `0.9.10`。

**Comment by eaTong** [comment]
最后一次查看本地的 rc-cascader 版本确实是0.9.10.但是还是不行。后来再次将antd删除，并运行 npm cache clean之后再重新npm install antd，现在就可以了。
非常感谢！！！

**Comment by afc163** [comment]
你不会直接使用的 dist 下的 antd.js 吧？

**Comment by eaTong** [comment]
额，原来是因为我一直都是import { Cascader } from 'antd';的问题啊。。。
一开始没理解你说的底层rc-cascader已更新，哈哈。。不好意思了

**Comment by eaTong** [comment]
额，原来是因为我一直都是import { Cascader } from 'antd';的问题吗？

**Comment by afc163** [comment]
没问题。

按道理说重新安装应该就能好。
