### ISSUE TITLE
How to clear input when trigger custom event function in event onInputKeyDown on Select multiple?

### ISSUE THREAD

**Issue by cuongdevjs** [ant-design/ant-design#20801]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-djchc)

### Steps to reproduce
_ add input by custom event
_ clear input in select 

### What is expected?
Clear input manual.

### What is actually happening?
Don't have method support do this

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | lastest |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
I believe you need https://github.com/ant-design/ant-design/issues/20465#issuecomment-569180727

**Comment by cuongdevjs** [comment]
> I believe you need [#20465 (comment)](https://github.com/ant-design/ant-design/issues/20465#issuecomment-569180727)

Can you see my example? I use method onSearch remote + onInputKeyDown and cannot apply your way in this case?

**Comment by cuongdevjs** [comment]
[(https://codesandbox.io/s/antd-reproduction-template-xjpi8)](https://codesandbox.io/s/antd-reproduction-template-xjpi8)
please see my example. And how can fix it?

**Comment by cuongdevjs** [comment]
@afc163

**Comment by afc163** [comment]
Is this same issue as #20198 ?
