### ISSUE TITLE
[antd: Checkbox] `value` is not validate prop, do you mean `checked`?

### ISSUE THREAD

**Issue by gotjoshua** [ant-design/ant-design#20803]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-checkbox-value-instead-of-checked-bug-when-inside-fielddecorator-4urh6)

### Steps to reproduce
Wrap a checkbox in a field decorator:
```jsx
    <Form>
      <Form.Item label={"Form.Item with Checkbox"}>
        {getFieldDecorator("areDatesFlexible")(
          <Checkbox defaultChecked={event.areDatesFlexible} />
        )}
      </Form.Item>
    </Form>
```

### What is expected?
no warning

### What is actually happening?
warning

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | react@^16.12.0:   version "16.12.0" |
| System | Mac OSX 10.13 |
| Browser | Chrome Canary [Version 81.0.4019.3 (Official Build) canary (64-bit)] |

---
related to https://github.com/ant-design/ant-design/issues/19667 which was flagged as invalid

**Comment by gotjoshua** [comment]
![ValueInsteadOfChecked](https://user-images.githubusercontent.com/8686454/72061682-49bd0e80-32ce-11ea-8035-2284b21514cf.png)

**Comment by yoyo837** [comment]
Your reproduce not works.

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/72061972-d76e1d80-3311-11ea-9e5f-77dae5456e3d.png)

**Comment by gotjoshua** [comment]
please check again, (I left a code artifact in there - but now removed):  
![Foo](https://user-images.githubusercontent.com/8686454/72066141-b688d680-32d7-11ea-91c3-b29569794058.png)

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-checkbox-value-instead-of-checked-bug-when-inside-fielddecorator-tdq26

**Comment by yoyo837** [comment]
https://ant.design/components/form/

**Comment by gotjoshua** [comment]
ok... so forms need even more boilerplate...
and is there no way to do that internally (I mean, couldn't a form know where to look for a checkbox? or couldn't a checkbox silently return checked when asked for value?)
but thanks for the codepen fork - i understand now.

**Comment by yoyo837** [comment]
The form component has been rewritten in v4, and its API is more friendly! https://next.ant.design/components/form/

**Comment by ChristopheBougere** [comment]
For anyone having this warning as well, I just found the answer in the doc:
https://ant.design/components/form/#components-form-demo-validate-other
```
<Form.Item name="switch" label="Switch" valuePropName="checked">
  <Switch />
</Form.Item>
```
Please note the `valuePropName="checked"`

**Comment by ELI7VH** [comment]
thank you @ChristopheBougere that is exactly what I needed, perhaps we need this in the `<Switch />` demo code examples?

**Comment by Trontor** [comment]
> valuePropName="checked"

This should really be in the documentation, I was struggling to get the checkbox to recognise the value without having to make it a controlled component.

**Comment by weiliang903** [comment]
> For anyone having this warning as well, I just found the answer in the doc:
> https://ant.design/components/form/#components-form-demo-validate-other
> 
> ```
> <Form.Item name="switch" label="Switch" valuePropName="checked">
>   <Switch />
> </Form.Item>
> ```
> 
> Please note the `valuePropName="checked"`

It's cause type error in Typescript.

It's ok.

```jsx
<Form.Item name="checkbox">
  {getFieldDecorator('order_receiver', {
      defaultChecked: true,
      rules: [
          {
              required: false,
              message:
                  'Offer!',
          },
      ],
      valuePropName:"checked"
  })(
      <Checkbox className="ps-checkbox">Order Receiver</Checkbox>,
  )}
</Form.Item>
```

**Comment by haptn** [comment]
> For anyone having this warning as well, I just found the answer in the doc: https://ant.design/components/form/#components-form-demo-validate-other
> 
> ```
> <Form.Item name="switch" label="Switch" valuePropName="checked">
>   <Switch />
> </Form.Item>
> ```
> 
> Please note the `valuePropName="checked"`

Really appreciate your note!

**Comment by ark-davegoodchild** [comment]
> For anyone having this warning as well, I just found the answer in the doc: https://ant.design/components/form/#components-form-demo-validate-other
> 
> ```
> <Form.Item name="switch" label="Switch" valuePropName="checked">
>   <Switch />
> </Form.Item>
> ```
> 
> Please note the `valuePropName="checked"`

Legend, thanks for this!
