### ISSUE TITLE
ant-design 4.0 remove @border-radius-sm => @border-radius-base

### ISSUE THREAD

**Issue by soeyi** [ant-design/ant-design#20817]
### What problem does this feature solve?
Lots of projects written before are using  @border-radius-sm. So It would be better not to change this variable one by one.

### What does the proposed API look like?
add  @border-radius-sm back to make it compatible ?

**Comment by yoyo837** [comment]
It's a break change in 4.0. Please try to follow the changes if upgrade your project.

**Comment by soeyi** [comment]
Ok.

**Comment by yoyo837** [comment]
@soeyi  Team leader accepts your suggestion, please continue to work in #20818.
