### ISSUE TITLE
table的components的body:{row}没有data-row-key属性；异步加载表格头数据，header:{cell}获取column上的属性值报错

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#20814]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-bird-bcglt?fontsize=14&hidenavigation=1&theme=dark)

### table
```jsx
<Table
        onRow={(record, index) => ({
          record,
          index,
          tableData: { name: "自定义数据" }
        })}
        onHeaderRow={(column, index) => ({
          column,
          index,
          tableData: { name: "自定义数据" }
        })}
        components={{
          header: {
            cell: props => this.tableHeaderCell(props)
          },
          body: {
            row: props => this.tableBodyRow(props)
          }
        }}
        columns={columns}
        dataSource={dataSource}
/>
```

### Row
```jsx
tableHeaderCell = props => {
    console.log("tableHeaderCell", props);
    return <th {...this.props}>{props.children}</th>;
  };

  tableBodyRow = props => {
    console.log("tableBodyRow", props);
    const key = props["data-row-key"];
    return <tr {...this.props}>{props.children}</tr>;
  };
```

### What is expected?
3.x有data-row-key属性，4.x是否不再支持该属性？3.x异步加载表格头，重写header->cell的函数取column没有问题，4.x必须等到表格头数据加载完成再渲染table才可以

### What is actually happening?
没有data-row-key属性；异步加载表格头如果不等到数据加载完成获取props.column是undefined

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12 |
| System | windows10 |
| Browser | chrome79 |

**Comment by zombieJ** [comment]
v3 版本中 `columns` 为空 Table 整个不渲染，v4 版本中至少会留一列用于防止页面抖动。`data-row-key` 会补上，占位列没有 `column` 需要在升级文档里提一下。

v3 ref: https://codesandbox.io/s/cocky-mendeleev-9xo8o
