### ISSUE TITLE
cra脚手架下使用dynamic import icon与locale抛出大量warning

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#20811]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/fred8617/cra-antd-dynamic-import-warning](https://github.com/fred8617/cra-antd-dynamic-import-warning)

### Steps to reproduce
安装启动，查看控制台

### What is expected?
无警告

### What is actually happening?
大量警告

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.8  |
| System | win |
| Browser | chrome |

---
项目中需要图标与语言包的动态引入，会抛出大量警告，包括antd组件
![image](https://user-images.githubusercontent.com/35049517/72118837-69673c00-338d-11ea-8fb1-1adb0254dc5c.png)
![image](https://user-images.githubusercontent.com/35049517/72118847-72580d80-338d-11ea-90a4-49c51d92307c.png)

**Comment by fred8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/72119565-d4197700-338f-11ea-82ea-cfca877e3025.png)
加上文件后缀倒是不报警告了，感觉是webpack的配置问题

**Comment by zombieJ** [comment]
嗯，看起来是它引用了 ts 导致的报错。

PS：你这个高亮挺酷炫的……

**Comment by fred8617** [comment]
@zombieJ 哈哈，一起分享https://marketplace.visualstudio.com/items?itemName=RobbOwen.synthwave-vscode
