### ISSUE TITLE
node 5.9.0/5.9.1 can't install: npm ERR! cb() never called! 

### ISSUE THREAD

**Issue by guox191** [ant-design/ant-design#2081]
## What you did

`npm install --save antd`

## What you would like to happen

install successfully

## What actually happened

`npm ERR! cb() never called!`

## Online demo

I had used vnm (version 0.31.1) test this problem on a new vps , node 5.10/ 5.4.0/ 5.7.0/ 5.8.0/ 5.10.0 is fine, only 5.9.0 and 5.9.1 did.

## Environment Information

- The version of antd: 1.4.1
- Your operating system and it's version: both OSX 10.11.2 and centos 7.0 x64
- Npm version: 3.7.3
- Node version: 5.9.0 / 5.9.1

THANKS

**Comment by afc163** [comment]
建议排查本地环境，或到 npm 上进行咨询。这个不太可能是我们的问题。
