### ISSUE TITLE
DatePicker

### ISSUE THREAD

**Issue by puppyer** [ant-design/ant-design#20816]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望有一个属性，可以禁止在输入框手动输入

### What does the proposed API look like?
disableInput

**Comment by zombieJ** [comment]
能说说这个需求的原因吗？

**Comment by margox** [comment]
有时候通过配合设置默认value和设置allowClear为false，再加上禁止手动输入的话，就可以保证用户不会选择一个空的日期了

**Comment by margox** [comment]
> 能说说这个需求的原因吗？

有时候通过配合设置默认value和设置allowClear为false，再加上禁止手动输入的话，就可以保证用户不会选择一个空的日期了

**Comment by afc163** [comment]
Duplicate of #20442

**Comment by puppyer** [comment]
需求是能够有一个属性来禁用DatePicker组件的手动输入
原因： 当showTime=true的时候，虽然用disabledTime来禁选了部分时间，但是在DatePicker的输入框是可以输入这些被禁掉的时间的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"超能刚哥"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月15日(星期三) 晚上8:57
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"~~雪"<1309571292@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] DatePicker (#20816)



 
能说说这个需求的原因吗？
  
有时候通过配合设置默认value和设置allowClear为false，再加上禁止手动输入的话，就可以保证用户不会选择一个空的日期了

**Comment by afc163** [comment]
可以到 #20442 下回复相关需求。
