### ISSUE TITLE
表格单元格默认内边距有点大

### ISSUE THREAD

**Issue by yujingwyh** [ant-design/ant-design#20819]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表格单元格默认内边距有点大，与其它组件默认大小不协调

### What does the proposed API look like?
期望表格单元格默认尺寸内边距为8像素

**Comment by yoyo837** [comment]
`@table-padding-vertical` 
`@table-padding-horizontal`

**Comment by yoyo837** [comment]
https://next.ant.design/docs/react/customize-theme-cn

**Comment by yujingwyh** [comment]
我知道这样可以改为8像素，但你不觉得默认16像素的内边距有点大吗？有没有体验过8像素整体显示效果会更好。表格作为展示组件，内边距更应该默认8像素来显示更多的信息。

**Comment by yoyo837** [comment]
这是antd 设计师定的，设计这个东西，见仁见智！
