### ISSUE TITLE
Select placeholder position not correct when set to mode multiple on form with inline layout

### ISSUE THREAD

**Issue by nkrekow** [ant-design/ant-design#20828]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6opvo)

### Steps to reproduce
Set `<Form>` to `layout='inline'` and `<Select>` to `mode='multiple'`

### What is expected?
Select should be at least as long as the placeholder text (like it is when mode is single select) when set to `mode='multiple'`

### What is actually happening?
Select is extremely short and the placeholder text is overflowing

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | macOS 10.14.5 |
| Browser | firefox/safari/chrome |

**Comment by shaodahong** [comment]
The bug is not default width as long as placeholder text but placeholder display not correct

![image](https://user-images.githubusercontent.com/14831261/72215568-1fc64f00-354f-11ea-98e2-0ff4ab7da947.png)

**Comment by afc163** [comment]
Other problem of Select placeholder: https://github.com/ant-design/ant-design/issues/20850
