### ISSUE TITLE
min-width for switch components

### ISSUE THREAD

**Issue by LuisRodriguezLD** [ant-design/ant-design#20826]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
**Hello,**

The Switch component uses a [less variable](https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L632) to set the height,

it would be great if you we could have the same but for width.

**Why?**
I was trying to make my switch bigger but I could only make it larger not wider

I'll be more than happy to submit a PR, 
just let me know what you all think.

### What does the proposed API look like?
@switch-min-width: 100px;
@switch-sm-min-width: 100px;

**Comment by abdih** [comment]
@LuisRodriguezLD I've implemented your request [here](https://github.com/ant-design/ant-design/pull/20829). Hope it's what you want.

**Comment by LuisRodriguezLD** [comment]
this is great! thank you!!
