### ISSUE TITLE
Exposed SiderContext to ant-desgin user so that we can consume the SiderContext.siderCollapsed on our react component

### ISSUE THREAD

**Issue by yunikoro** [ant-design/ant-design#20820]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
English: I have just looked through your team's UI components source code of Menu, SubMenu, Layout.Sider. I think use the "React Context Provider & Consumer" to pass down the sider Collapse status is a good practice. It makes the UI Component high Cohesion. So, if you expose the SiderContext to us that our UI component will better like yours. Thanks.
中文：我在使用Ant Design Menu和Sider的时候，发现Menu组件可以监听到Sider的状态进而做样式变更。在简单浏览了贵团队源码之后，觉得用React Context特性实现折叠状态的传递真是个优雅的实现。但是我们自己实现的组件无法消费到这个SiderContext.siderCollapsed，如果能把SiderContext这个Context对象暴露给普通用户的话，我相信我们的代码也能像贵团队的代码一样优雅了。 谢谢。

### What does the proposed API look like?
```javascript
import React from 'react'
import { Layout } from 'antd'
// Maybe like this
const { SiderContext } = Layout.Sider

export default class MyComponent extends React.Component {
    constructor(props, context) {
        super(props)
    }
    render() {
        return (
            <SiderContext.Consumer>
                {(context: SiderContextProps) => {<ConsumeSomeThing/>}}
            </SiderContext.Consumer>
        )
    }
}
```

**Comment by zombieJ** [comment]
You can import from `antd/es/layout/Sider` for usage. But should take care that `SiderContext` is internal usage and we do not promise it will keep exist by code refactor in future.
