### ISSUE TITLE
Don't concat className to make code purgable by purgecss

### ISSUE THREAD

**Issue by Alex-Ferreli** [ant-design/ant-design#20823]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
PurgeCSS is a tool that read all css classes, search in HTML, JSX, etc. (is up to you specify which files to analyze) the classes, if it didn't find a correspondence it delete the class. This is usefull to remove all classes not needed.

Using Tailwind along antd to style own components require PurceCSS to remove so much variants classes generated automatically by Tailwind. Concatening classes broke PurgeCSS classes, the best practic should be to not concat class at all, but instead write them in it's completeness to make PurgeCSS works.

### What does the proposed API look like?
No example, just don't concat classes but write them and apply them with conditions.

**Comment by Alex-Ferreli** [comment]
No difficult to reproduce, just use purgecss and antd in the same project.
There is a simple CRA + antd + tailwindcss project:
https://github.com/Alex-Ferreli/antd-purgecss-issue

**Comment by afc163** [comment]
Sorry, I don't think not concatening classes at all is a good idea for React stying development.

**Comment by Alex-Ferreli** [comment]
> Sorry, I don't think not concatening classes at all is a good idea for React stying development.

IMHO it's more clean, you can read the full classes and search it in CSS files without margin of errors.

The little downside is that it increase the file size (but i think it's worth with GZIP).

Using tools like purgecss you can delete ALL unedeed classes and will not send useless classes, reducing file size of CSS against little overhead on JS.

This point on Tailwindcss documentation explain how https://send.firefox.com/ delivery only 4k of gziped CSS using it, explain why it's an important tool: https://tailwindcss.com/docs/controlling-file-size#removing-unused-css.

If it's a huge rework i can do a PR to let you calculate size between builds.
