### ISSUE TITLE
Nested dataIndex in Table is not working

### ISSUE THREAD

**Issue by jvaclavik** [ant-design/ant-design#20837]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-zcj1e?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Create some table with nested `dataIndexes` like `dataIndex: "categories['cheese']"`. It is working in `3.26.6` but not in `4.0.0.rc0`. You can try it attached codesandbox.

Example:
```
...
const tableData = [
  { id: 1, categories: { cheese: 10, meat: 23 } },
  { id: 2, categories: { cheese: 22, meat: 25 } }
];

const columns = [
  {
    title: "id",
    dataIndex: "id",
    key: "id",
    render: id => id
  },
  {
    title: "cheese",
    dataIndex: "categories['cheese']",
    key: "categories['cheese']",
    render: cheeseCount => cheeseCount
  },
  {
    title: "meat",
    dataIndex: "categories['meat']",
    key: "categories['meat']",
    render: meatCount => meatCount
  }
];

...

<Table dataSource={tableData} columns={columns} />,
```

### What is expected?
Data from the nested object (`category.cheese` and `category.meat`) should be visible

### What is actually happening?
render function is getting `undefined`

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12.0 |
| System | Mac OS X 10.14.6 |
| Browser | Chrome, Version 79.0.3945.88 (Official Build) (64-bit) |

**Comment by shaodahong** [comment]
https://next.ant.design/components/table/#Migrate-to-v4

**Comment by ArthurBrito** [comment]
`Besides, the breaking change is changing dataIndex from nest string path like user.age to string array path like ['user', 'age']. This help to resolve developer should additional work on the field which contains ..`

The above link was not working, this one below works:
https://ant.design/components/table/#Migrate-to-v4

**Comment by dubrova-ta-ma** [comment]
@ArthurBrito thanks a lot!

**Comment by hieund20** [comment]
@ArthurBrito thank a lot

**Comment by MinaSamir11** [comment]
is it working if index of type array !?
ex: dataIndex: ["users", "name"]

**Comment by RahulBhoir-GSLab** [comment]
No it's not working

**Comment by ahmadysalah** [comment]
pass data index as object, and pass the key at render attribute 😀
