### ISSUE TITLE
找不到如何在非react项目中运用的教程

### ISSUE THREAD

**Issue by HS5458** [ant-design/ant-design#2083]

**Comment by afc163** [comment]
我们是 react 的组件库，不提供非 react 的教程还是比较自然的吧。

**Comment by HS5458** [comment]
http://ant-tool.github.io/quick-start.html
你们这里有说到非react项目

**Comment by benjycui** [comment]
@HS5458 建议你再认真阅读下 ant-tool 和 ant-design 这两个项目的 introduction。
