### ISSUE TITLE
Form from the @ant-design/compatible won't follow the labelCol and wrapperCol layout

### ISSUE THREAD

**Issue by mayinghan** [ant-design/ant-design#20834]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ufcsa/airpick-new/tree/antdv4](https://github.com/ufcsa/airpick-new/tree/antdv4)

### Steps to reproduce
npm start 

### What is expected?
In the log in page, the form should follow the layout:
 ```const formItemLayout = {
      labelCol: {
        xs: { span: 20 },
        sm: { span: 8 },
      },
      wrapperCol: {
        xs: { span: 18 },
        sm: { span: 10 },
      },
    };
```

### What is actually happening?
The layout wasn't working

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | React 16.12 |
| System | Mac os |
| Browser | Chrome latest |

**Comment by chemicalkosek** [comment]
Is this really fixed? I have migrated to V4 with @ant-design/codemod-v4. Everything works fine (really cool) excluding this. labelCol and wrapperCol don't work as usual.

```
    "@ant-design/compatible": "0.0.1-rc.1",
    "@ant-design/icons": "^4.0.0-rc.0",
    "antd": "^4.0.0-rc.3",
```

Btw at the end of codemod it says:
```
Please install the following dependencies:

* antd^4.0.0-rc.0
* @ant-design/icons^4.0.0-rc.0
* @ant-design/compatible^1.0.0-rc.0
```

but the latest `@ant-design/compatible` is 0.0.1-rc.1

**Comment by shaodahong** [comment]
@chemicalkosek yep, it's fixed, if still have, can you reproduce a demo?
