### ISSUE TITLE
[4.x] InputNumber 在Form表单中 数据错误

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#20848]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/form-cn/#components-form-demo-size](https://next.ant.design/components/form-cn/#components-form-demo-size)

### Steps to reproduce
1、鼠标移入 InputNumber组件，点击一下上或者下
2、快速在 上或者下 左右移动(移入和移除)

### What is expected?
数据不受干扰

### What is actually happening?
数据错误

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | latest |
| System | win10 |
| Browser | chrome 79 |

**Comment by XianZhengquan** [comment]
我要怎么上传gif

**Comment by yoyo837** [comment]
粘贴在Write框

**Comment by yoyo837** [comment]
拖拽亦可。

**Comment by XianZhengquan** [comment]
![bug](https://user-images.githubusercontent.com/46179450/72232599-1e536000-35fd-11ea-96e4-ba58ba982cb0.gif)

**Comment by XianZhengquan** [comment]
@yoyo837 在数字4的时候 就跳到7了

**Comment by yoyo837** [comment]
无法重现

**Comment by yoyo837** [comment]
你是移动过程中不小心点到了吧？

**Comment by XianZhengquan** [comment]
减 也是一样，
我点击 你能看见有黄色的背景

**Comment by XianZhengquan** [comment]
我再录一个

**Comment by XianZhengquan** [comment]
在Form里面有这个情况，纯 InputNumber 没有重现

**Comment by yoyo837** [comment]
按住不松是可以连续增减的，你是不是触发了这个效果！

**Comment by XianZhengquan** [comment]
松开了的

**Comment by XianZhengquan** [comment]
![bug1](https://user-images.githubusercontent.com/46179450/72232835-9bcba000-35fe-11ea-9f2f-e10bb6db377c.gif)

**Comment by XianZhengquan** [comment]
按住不送，只会增加一个

**Comment by XianZhengquan** [comment]
这个是按住不松的，可以看到一只有黄色背景
![bug3](https://user-images.githubusercontent.com/46179450/72232873-e64d1c80-35fe-11ea-88cc-d17d8bc3a682.gif)

**Comment by XianZhengquan** [comment]
> 按住不松是可以连续增减的，你是不是触发了这个效果！

要手速快，移动的准确，多试几次，点击后马上快速移动

**Comment by yoyo837** [comment]
作实试不出来。

**Comment by XianZhengquan** [comment]
我去同事电脑试试

**Comment by XianZhengquan** [comment]
> 作实试不出来。

没试出来。。。 可能是我的电脑卡，

**Comment by afc163** [comment]
看上去是一个个例，不准备继续花时间去重现，也欢迎帮助排查具体原因然后给 PR 建议，我这里先关了。

**Comment by XianZhengquan** [comment]
> 看上去是一个个例，不准备继续花时间去重现，也欢迎帮助排查具体原因然后给 PR 建议，我这里先关了。

好的
