### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by cutanzi1997** [ant-design/ant-design#20842]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
<Form.Item
          label="手机号"
          name="phone"
          rules={[
            { type: 'string', required: true, message: '请输入手机号' },
            // {
            //   pattern: /^[1][0-9]{10}$/,
            //   message: '请输入正确的手机号',
            // },
          ]}
        >
          <Input maxLength={11} />
        </Form.Item>

### What is expected?
正常出现

### What is actually happening?
ReferenceError: regeneratorRuntime is not defined validateUtil.js:93

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.11 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome70 |

**Comment by cutanzi1997** [comment]
https://github.com/cutanzi1997/dome

``` shll
npm i

npm run dev
```

导航管理 ---》 新增 在输入框中输入1

**Comment by yoyo837** [comment]
404

**Comment by cutanzi1997** [comment]
现在试试
刚刚是private

**Comment by cutanzi1997** [comment]
Property 'onStoreChange' in type 'Field' is not assignable to the same property in base type 'FieldEntity'.

**Comment by yoyo837** [comment]
这个类型错误和前面说的问题不是同一个吧？

**Comment by yoyo837** [comment]
ref: https://github.com/react-component/field-form/issues/67

**Comment by cutanzi1997** [comment]
不是

**Comment by mark9462** [comment]
I have the same problem:
![](https://i.imgur.com/2nw0QLW.png)

Here is I find path:
node_modules/rc-field-form/es/utils/validateUtil.js

It seems like rc-field-form problem

**Comment by zombieJ** [comment]
ref: https://github.com/babel/babel-preset-env/issues/112

**Comment by sreetamdas** [comment]
@zombieJ what's the solution for this error then? The issue that you've linked is 4 years old and doesn't seem to highlight any solutions itself either :/

**Comment by ztplz** [comment]
@sreetamdas   As a quick fix,  you can `npm install @babel/plugin-transform-runtime --dev`, then in your `babelrc`: 
`````
"plugins": [
    ["@babel/plugin-transform-runtime",
      {
        "regenerator": true
      }
    ]
  ],
``````

**Comment by sreetamdas** [comment]
@ztplz thanks, but that still doesn't resolve the issue 😞

**Comment by ztplz** [comment]
@sreetamdas  Can you create a mini repo?

**Comment by cutanzi1997** [comment]
对的还有一个问题 regeneratorRuntime is not defined
前提条件
```javascript
const [form] = Form.useForm();
```

之后

```javascript
<Button
                      block
                      onClick={getCode}
                      style={{
                        height: '100%',
                      }}
                    >
                      发送验证码
</Button>
```

函数中使用
```javascript
form.getFieldValue('phone')
```
就会有这个问题
试试看吧

**Comment by cutanzi1997** [comment]
如果直接 from 就不会出现这个问题

**Comment by hugobarragon** [comment]
@zombieJ 
hi, i am having the same problem when using tsc to compile my package with "antd": "4.0.0-rc.3", any workarount ? i read zombieJ comment and when to babel applied some plugins but nothing solves it.
for now i went directly to node_modules and manual changed
from `onStoreChange: (prevStore: Store, namePathList: InternalNamePath[], info: NotifyInfo) => void;`
to
`onStoreChange: (prevStore: Store, namePathList: InternalNamePath[] | null, info: NotifyInfo) => void;`

**Comment by crazyair** [comment]
yarn test 也需要加 `@babel/polyfill`  才不报错

**Comment by hugobarragon** [comment]
> yarn test 也需要加 `import '@babel/polyfill'` 才不报错

i cant apply the polyfill, as the bug is on an npm module, the end user is the one that can decide to polyfill, and i am using tsc to only compile and not to build....

**Comment by zombieJ** [comment]
@hugobarragon ,  can not reproduce this ts error. Could you help to update TS version. If still has the error, could you provide a reproduce for this?

**Comment by hugobarragon** [comment]
> @hugobarragon , can not reproduce this ts error. Could you help to update TS version. If still has the error, could you provide a reproduce for this?

yes, but probably will need to create a repo its when i compile with `tsc` with this config:
`tsc -p ./tsconfig.json`  

```
{
  "compilerOptions": {
    "noImplicitAny": true ,
    "resolveJsonModule": true,
    "target": "ES5" ,
    "module": "commonjs" ,
    "jsx": "react" ,
    "declaration": true ,
    "declarationMap": true ,
    "sourceMap": true ,
    "outDir": "lib" ,
    "strict": true ,
    "typeRoots": [
      "node_modules/@types/",
      ".src/global.d.ts"
    ] ,
    "esModuleInterop": true 
  },
  "include": ["src"],

  "exclude": ["src/index.tsx", "src/serviceWorker.ts"]
}

```

**Comment by zombieJ** [comment]
Could you help to create a issue with reproduce?

**Comment by hugobarragon** [comment]
@zombieJ i was trying to replicate but i cant anymore because it was already fixed here: https://github.com/react-component/field-form/pull/81
thanks anyway
