### ISSUE TITLE
lib/button引入全部icon

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#20847]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://暂无](https://暂无)

### Steps to reproduce
import Button from 'antd/lib/button'

### What is expected?
图标拆分

### What is actually happening?
全部引入

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12 |
| System | win |
| Browser | chrome |

**Comment by fred8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/72231345-f3b1d900-35f5-11ea-9428-84845229b073.png)

**Comment by yoyo837** [comment]
来张 webpack-bundle-analyzer 分析图？

**Comment by afc163** [comment]
Try `import Button from 'antd/es/button'`.

**Comment by fred8617** [comment]
@afc163 嗯，这么样是可以的，只不过有时候ts的import提示会自己去找lib下的文件，不注意的话就会把全部icon引进来
@yoyo837 
![image](https://user-images.githubusercontent.com/35049517/72232478-5c9c4f80-35fc-11ea-99ce-8a1cba046e35.png)
![image](https://user-images.githubusercontent.com/35049517/72232504-805f9580-35fc-11ea-9932-ebb7e64ce8b4.png)
试了下，应该不是button的锅，可能主要是lib/table的问题
这几种写法都会导致icon全引入
`import Table from 'antd/lib/table';`
`import { Button } from 'antd';
import Table from 'antd/lib/table';`
`import Button from 'antd/lib/button';
import Table from 'antd/lib/table';`
`import Button from 'antd/lib/button';
import { Table } from 'antd';`

**Comment by afc163** [comment]
`antd/es` 可以 完全替代 `antd/lib`。

**Comment by afc163** [comment]
不过 lib 貌似也可以改改。cc @zombieJ

**Comment by zombieJ** [comment]
TreeShaking 只能 es module 才支持。编译成 `lib` 一定是全量引入的。

> [Tree shaking](https://webpack.js.org/guides/tree-shaking/)
> Tree shaking is a term commonly used in the JavaScript context for dead-code elimination. It relies on the static structure of ES2015 module syntax, i.e. import and export. The name and concept have been popularized by the ES2015 module bundler rollup.
