### ISSUE TITLE
DatePicker值置空使用null和undefined结果不一致

### ISSUE THREAD

**Issue by capdiem** [ant-design/ant-design#20857]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elastic-jennings-253gt)

### Steps to reproduce
`DatePicker` 组件选择日期，点击 `using undefined` 不能清空，点击 `using null` 可以清空。

### What is expected?
null 和 undefined 都可以清空。

### What is actually happening?
手动选择的值，使用`form.setFieldsValue({date: null})`可以清空值，使用`{date: undefined}`却不能。
还有种情况，使用`form.setFieldsValue({date: moment()})`设置的值，用`null`和`undefined`都能清空。

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google chrome |

**Comment by zombieJ** [comment]
用 `resetFields` 重置表单，React 对于原生组件处理 `value` 改成 `undefined` 也是不改变展示值的：https://codesandbox.io/s/eager-neumann-ulnbv
