### ISSUE TITLE
DatePicker 选择日期不能删除。设置有值可编辑，没值disabled时，有日期时进行编辑，删除值后，弹出层无法关闭，必须选择一个值

### ISSUE THREAD

**Issue by pengxiaobao** [ant-design/ant-design#2085]
## 你做了什么？

1.DatePicker 选择日期不能删除。
2.设置有值可编辑，没值disabled时，有日期时进行编辑，删除值后，弹出层无法隐藏，必须选择一个值才行能隐藏

## 你期待的结果是：

1. 能正常删除，像正常文本框一样可以选择删除
2. 删除值后能隐藏弹出选择日期层

## 实际上的结果和抱怨：

1.选择日期后不能删除
2.删除值后，无法隐藏日期弹出层

## 可重现的在线演示
http://codepen.io/anon/pen/ezzXxR?editors=001#anon-signup

## 本地环境信息

- antd 版本: antd 0.12.17
- 操作系统及其版本：windows
- 浏览器及其版本: chrome 51.0.2704.84 m

![](https://zos.alipayobjects.com/rmsportal/vwYRBziyswXFeHN.jpg)
![](https://zos.alipayobjects.com/rmsportal/yQfdGAktDBEfZlO.jpg)

**Comment by afc163** [comment]
对，不能编辑，用右上角的清除进行删除。

**Comment by afc163** [comment]
> 2.删除值后，无法隐藏日期弹出层

这应该是个 bug 。

**Comment by pengxiaobao** [comment]
能支持表单内的可以编辑吗？

**Comment by afc163** [comment]
目前的实现比较困难。

**Comment by pengxiaobao** [comment]
还有一个问题。在点击日期输入框后弹出日期控件，必须还要点击一下才能输入。 这个能改成点击输入框后能直接输入吗？
