### ISSUE TITLE
[4.x] Select/Input placeholder have different padding-left and color

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#20850]
4.x：https://codesandbox.io/s/antd-reproduction-template-spwm9
3.x：https://codesandbox.io/s/antd-reproduction-template-7dq7e

<img width="190" alt="image" src="https://user-images.githubusercontent.com/507615/72233223-febe3680-3600-11ea-885b-033304b40f56.png">

**Comment by xrkffgg** [comment]
- 我这里看他们的颜色是一样的，都是 `rgba(0, 0, 0, 0.65)`

- 多选的 left 有点不一致，其他都是 `11px` 

多选的是 `12px`
```
.ant-select-multiple .ant-select-selection-placeholder {
    left: 12px;
}
```

**Comment by afc163** [comment]
确实，颜色问题只在 Firefox 下可重现。padding 问题都有。

**Comment by xrkffgg** [comment]
@afc163 
后两种的 placeholder 是包在了 input 中
可以通过设置 input 的 placeholder  强制颜色 可以达到统一

```
input::-webkit-input-placeholder,
textarea::-webkit-input-placeholder {
  color: rgba(0, 0, 0, 0.65) !important;
}
input:-moz-placeholder,
textarea:-moz-placeholder {
  color: rgba(0, 0, 0, 0.65) !important;
}
input::-moz-placeholder,
textarea::-moz-placeholder {
  color: rgba(0, 0, 0, 0.65) !important;
}
input:-ms-input-placeholder,
textarea:-ms-input-placeholder {
  color: rgba(0, 0, 0, 0.65) !important;
}

```

但是这样 谷歌上 颜色 又不一致了 😂😂😂

**Comment by afc163** [comment]
发现是我的锅 https://github.com/ant-design/ant-design/pull/20356/commits/747dc4dff523b4a8265d67bc28ae72327fa4d873#diff-68c855179f0ac7cd7c5a5269b185ac20L6

**Comment by afc163** [comment]
修了颜色的问题 https://github.com/ant-design/ant-design/commit/e3b0104c53aff9a3d0152a96817271044349b46c ，留着 padding 的问题你们来看看。

**Comment by xrkffgg** [comment]
@zombieJ 有人在改了吗？

**Comment by zombieJ** [comment]
@xrkffgg, 我加了一个 `someone working` 的 label 额……

**Comment by xrkffgg** [comment]
@zombieJ  恩，那我关了

**Comment by zombieJ** [comment]
不用
在你的上面继续改就行了，我已经把我的关了。

**Comment by fjc0k** [comment]
颜色这个，Chrome 也是这样的啊，Select 和 Input 占位文字的效果明细不同：

![image](https://user-images.githubusercontent.com/13151189/72251911-7740e980-3639-11ea-9b58-e821ae35d31b.png)
