### ISSUE TITLE
<Table /> 组价的 rowSelection.getCheckboxProps 会被执行多次

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#2086]
如题，[查看 demo](http://codepen.io/ystarlongzi/pen/wWWZWG)

注意，打开控制面板，查看打印记录

**Comment by afc163** [comment]
对的，针对每条记录都会执行。

**Comment by afc163** [comment]
你的例子里只有一条记录。我稍后看看实现。

**Comment by dunhuang** [comment]
@afc163  自1.5.0你优化后运行如下demo，checkbox的状态不能根据每行数据来变化，仅决定于第一行record的值，这个方法失去意义了：
https://github.com/ant-design/ant-design/blob/63941ae665fb34878e6f5d05b7c4d5dbe59c5c58/components/table/demo/row-selection-props.md

**Comment by afc163** [comment]
对，使用 checkedRowKeys 来控制。

**Comment by MiaoStudio** [comment]
数据一定要有rowKey，没有唯一key，会不起作用
