### ISSUE TITLE
Volunteer for UI testing ci build

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#20866]
Since we have a lot of component. Modify style file may cause breaking that we need a UI test for each PR.

ref https://www.argos-ci.com/

**Comment by zombieJ** [comment]
Please feel free to assign self if you have time.

@shaodahong @ztplz @yoyo837 @xiaohuoni @orzyyyy @DiamondYuan

**Comment by yoyo837** [comment]
What should we do? Is there a quick start?

**Comment by orzyyyy** [comment]
How to manage the token [there](https://www.argos-ci.com/ant-design/ant-design/builds)?

**Comment by zombieJ** [comment]
Since I did not read related document yet. May not provide helpful info. But if you want to help on this, you can fork `ant-design` repo and investigate the UI test ci.

If get ready, create a PR to antd and told what should we do if need additional token.

**Comment by zombieJ** [comment]
@yoyo837 @orzyyyy

**Comment by orzyyyy** [comment]
Ok, I just have a try with `argos-cli` and github action:
1. Add token to secret, name as `ARGOS_TOKEN`.
2. Add workflow as [this](https://github.com/orzyyyy/memo/blob/argos/.github/workflows/ui-test.yml#L39).
3. Finally, you can find an upload info [here](https://github.com/orzyyyy/memo/commit/943e4d93a2e3f7470d3051096c52171b30ac56b4/checks?check_suite_id=398919644), and result of argos [here](https://www.argos-ci.com/orzyyyy/memo/builds/60181).

Then there are two questions:

1. How to generate the images of components those should be upload to argos? I have tried searching offical documentation, but found nothing.

2. Another predictable thing is how and where to place the diff images?

**Comment by zombieJ** [comment]
@orzyyyy , material-ui has related code. Maybe we can ref:
https://github.com/mui-org/material-ui/blob/b6585b5660d6187c420656b49eecd7b124603004/package.json#L7

**Comment by orzyyyy** [comment]
Sadly, when `vrtest` had its last commit was in 2017, which is used in material-ui. One more important thing is that it can't work in my environment and it seemed hard to search for solution. So I'm going to find another way to generate images and diff.

I prefer `[puppeteer](https://github.com/puppeteer/puppeteer)` for screenshot, [`pixelmatch`](https://github.com/mapbox/pixelmatch) for image diff for now.

Any other competition?

**Comment by zombieJ** [comment]
That's OK. Any solution is welcome : )

**Comment by fa93hws** [comment]
I believe storybook is a good support for visual regression test.
https://github.com/ant-design/ant-design/pull/22956
We can build a storybook page with components with all sorts of properties and send them to visual regression platform such as percy and agros as you mentioned.
