### ISSUE TITLE
Table固定列宽度在某些情况下不是预期结果

### ISSUE THREAD

**Issue by LuMaowei** [ant-design/ant-design#20863]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-fog-2ufwg?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
将第一列的宽度设为40和100分别查看效果

### What is expected?
第一列宽度在此样式下应该始终是40

### What is actually happening?
第一列宽度在固定后不是40

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.8.4 |
| System | Window 10 1903 |
| Browser | Chrome  79.0.3945.117 |

**Comment by LuMaowei** [comment]
抱歉，样式不知为何丢失了，这是新链接
https://codesandbox.io/s/romantic-fog-2ufwg?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
```
td {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
```

你的样式把单元格宽度顶开了。

**Comment by LuMaowei** [comment]
> ```
> td {
>   overflow: hidden;
>   text-overflow: ellipsis;
>   white-space: nowrap;
> }
> ```
> 
> 你的样式把单元格宽度顶开了。

好吧，现在我通过此样式达到预期效果

```
.ant-table-fixed-left table, .ant-table-fixed-right table{
  width:fit-content;
}
```

**Comment by afc163** [comment]
试了一下 `width: min-width;` 兼容性更好，我改改。

**Comment by afc163** [comment]
又仔细看了下，` width: fit-content;` 和 `width: min-content;` 在某些不添加宽度的场景会导致固定列消失，就不全局修改了。你的方式在你的场景下是可用的。
