### ISSUE TITLE
how to expand treeSelect childrens on select

### ISSUE THREAD

**Issue by Matheus-Ribeiro95** [ant-design/ant-design#20877]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
none, just trying to make this possible

### What does the proposed API look like?
no proposal at all, just a doubt

**Comment by zombieJ** [comment]
`onSelect` + `expandedKeys`

**Comment by Matheus-Ribeiro95** [comment]
this render the expanded but close immediately, i'm passing the data with "treeData" prop without children TreeNode elements. I will try to repeat the scenario using childrens then i will post here.

Thanks for the help!
