### ISSUE TITLE
在 iPhone6s 下，dropdown 第一个 hover demo 在点击后就再也无法呼出了，其他机型没有发现该问题

### ISSUE THREAD

**Issue by BlackGanglion** [ant-design/ant-design#20871]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pkj25l3mk0.csb.app/#](https://pkj25l3mk0.csb.app/#)

### Steps to reproduce
打开重新链接直接尝试就行

### What is expected?
dropdown 点击后能正常呼出

### What is actually happening?
dropdown 点击第一次正常，后面就不行了

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | react16 |
| System | iphone6s |
| Browser | 任意浏览器 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15688#issuecomment-477065182

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9377
