### ISSUE TITLE
Access function inside form.validateFields after Submit

### ISSUE THREAD

**Issue by CarolineBoyer** [ant-design/ant-design#20875]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/59661274/jest-access-function-in-antd-form-validate-after-a-submit](https://stackoverflow.com/questions/59661274/jest-access-function-in-antd-form-validate-after-a-submit)

### Steps to reproduce
Posting after lack of response https://stackoverflow.com/questions/59661274/jest-access-function-in-antd-form-validate-after-a-submit

### What is expected?
I expect a function called inside this.props.form.validateFields to be seen by Jest as toHaveBeenCalled() = true.

### What is actually happening?
The test expect(myFunc).toHaveBeenCalled() doesn't work. It doesn't seem to reach inside the function. It does work if it is outside the function this.props.form.validateFields (but still inside the handleSubmit function).

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | react 16 |
| System | Windows 10 |
| Browser | Chrome |

---
It looks like a duplicate of https://github.com/ant-design/ant-design/issues/5608 but I don't understand chinese. Sorry if it is.

**Comment by zombieJ** [comment]
https://github.com/react-component/form/blob/master/tests/async-validation.spec.js#L91

**Comment by CarolineBoyer** [comment]
I don't see how this is going to help :/
The link you have sent seems to explain how to test field validation not what I am looking for.

To explain again, I have a function A called inside the form.validateFields block that is located inside the submit function passed to my form.
After simulating a submit on my form, I want to check if function A hasbeenCalled.

This test `expect(functionA).toHaveBeenCalled` works if : 

```javascript
handleSubmit() {
    functionA();
}
```

But not if 
```javascript
handleSubmit() {
   form.validateFields() {
         functionA();
    }
}
```

**Comment by zombieJ** [comment]
You can pass functionA as jest mock:
```
handleSubmit() {
   form.validateFields() {
         if (process.env.NODE_ENV !== 'production' && this.props.checker) {
          checker();
        }
    }
}
```

```js
const checker = jest.fn();

const wrapper = mount(<App checker={checker} />);
```

**Comment by CarolineBoyer** [comment]
This is what I did :(
```javascript
const props = {
        functionA: jest.fn(), //the function is mocked
};
it('+++ check functionA is called when clicking on save', () => {
        wrapper.find(Form).simulate('submit', { preventDefault: ()=> {jest.fn()}});
        expect(props.functionA).toHaveBeenCalled(); // THIS FAILS
});
```
