### ISSUE TITLE
AutoComplete待选option，默认选中第一个，当按键盘下键时要按两次才能选到第二个选项

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#20879]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-blackburn-mejrl?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
随便输入，比如auto，出现下拉选择，此时向下选择，要按两次才能选到第二个。

### What is expected?
已经选中第一个了，当再按键盘下的时候直接选中第二个

### What is actually happening?
要按两次才能选中第二个

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome79 |

**Comment by zombieJ** [comment]
当前值和选择值是分开的，可以优化一下：
<img width="210" alt="截屏2020-01-14上午10 25 35" src="https://user-images.githubusercontent.com/5378891/72308848-448a0600-36b8-11ea-93d3-2fcdfdadcd82.png">

**Comment by zombieJ** [comment]
看了一下，直接用 `defaultActiveFirstOption` 即可。

**Comment by zhangzhi93** [comment]
> 看了一下，直接用 `defaultActiveFirstOption` 即可。

好的👌
