### ISSUE TITLE
在使用Form表单时 切换 用connect链接redux的表单元素时，会报错

### ISSUE THREAD

**Issue by TaurusWood** [ant-design/ant-design#20870]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-sun-wigig?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
通过state来控制第二个输入框是Input，还是连接redux的自定义组件<FormInOrNot/>。
eg: 当选择field类型是 从‘string’切换到'int'时，在 FormInOrNot中输入值，会报错。
原因是：node_modules/rc-form/es/createBaseForm.js
```
saveRef: function saveRef(name, _, component) {
        if (!component) {
          var _fieldMeta = this.fieldsStore.getFieldMeta(name);
          if (!_fieldMeta.preserve) {
            // after destroy, delete data
            this.clearedFieldMetaCache[name] = {
              field: this.fieldsStore.getField(name),
              meta: _fieldMeta
            };
            this.clearField(name);
          }
          delete this.domFields[name];
          return;
        }
       ...,
```

 中的saveRef会在我切换组件时运行，  `function saveRef(name, _, component) {}`
用connect连接redux的组件就是参数component，此时的值为null，导致运行this.clearField(name)。然后我在输入值的时候，`./node_modules/rc-form/es/createFieldsStore.js`中的`getFieldMeta`报错

### What is expected?
因为自定义组件<FormInOrNot/>我需要在不同层级多处使用，需要连接redux。所以期望支持一下这个功能

### What is actually happening?
```
createBaseForm.js:257 Uncaught TypeError: Cannot read property 'filter' of undefined
    at Object.getRules (createBaseForm.js:257)
    at createBaseForm.js:397
    at Array.forEach (<anonymous>)
    at Object.validateFieldsInternal (createBaseForm.js:384)
    at Object.onCollectValidate (createBaseForm.js:142)
```

| Environment | Info |
|---|---|
| antd | 3.23.2 |
| React | 16.8.6 |
| System | mac os 10.14.6 |
| Browser | chrome  79.0.3945.117 |

---
我还遇到一个问题，这么写，验证没有生效，验证的文案dom没有显示出来

**Comment by yoyo837** [comment]
用一个包裹组件 `truthy ? <Component /> : ? <Component2 />` 是不是更方便？

**Comment by zombieJ** [comment]
有 warning 修 warning，console 已经告诉你缺少 ref 了，表现当然不正常了。
https://codesandbox.io/s/gallant-darkness-s7d45

**Comment by TaurusWood** [comment]
@zombieJ  在`connect()`第四个参数传入`{ forwardRef: true }`也能解决，它会通过
```
React.forwardRef(function forwardConnectRef(
        props,
        ref
      ) {
        return <Connect {...props} forwardedRef={ref} />
      })
```
。但我还是不明白，为什么需要ref,才不会报错

**Comment by zombieJ** [comment]
Form 需要 ref 来实现错误滚动屏幕到对应位置的功能。
