### ISSUE TITLE
Card footer buttons ignore font-size less variable

### ISSUE THREAD

**Issue by michelemilani91** [ant-design/ant-design#20876]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/benjycui/pen/KgPZrE?editors=001](https://codepen.io/benjycui/pen/KgPZrE?editors=001)

### Steps to reproduce
Use card with footer buttons and increase font-size overriding the less variable

### What is expected?
These label in card footer buttons increase like other labels

### What is actually happening?
The size still remain the same

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.9 |
| System | Windows, iOS |
| Browser | Safari, Chrome, Firefox |

![8FE377F8-E46D-4B42-98B2-F62239F6134A](https://user-images.githubusercontent.com/14330303/72289900-60f05900-364c-11ea-8d1f-c03aeb707f50.png)

**Comment by yoyo837** [comment]
I can't find things you describe in your reproduce.

**Comment by michelemilani91** [comment]
> I can't find things you describe in your reproduce.

'cause I haven't known how to set a less variable on the snippet. Anyway it's easy to reproduce in a local environment. It's a css bug. The component ignore the font size less variable. I'm not a great css developer but I'll try to fix this bug by my self...
