### ISSUE TITLE
Issue with getFieldsError and getFieldError methods of form: they return undefined for field with errors for nested fields. 

### ISSUE THREAD

**Issue by alex-knyazev** [ant-design/ant-design#20878]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/alex-knyazev/antd-validation-bug-reproduction](https://github.com/alex-knyazev/antd-validation-bug-reproduction)

### Steps to reproduce
1. Click to 'Add new' button.
2. Click 'Confirm' button.

### What is expected?
I expected to see all errors in result of getFieldsError() . If it is - errors will be shown below the table

### What is actually happening?
Fields from and to are empty, but there are no errors at screen.

If you debug handleSubmit() at src/components/task/create/index.js - you will see that after calling of validateFields function we have errors in 'trips' property.

But in result of getFieldsError() we see that 'trips' is undefined.

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12.0 |
| System | ubuntu |
| Browser | chrome |

**Comment by alex-knyazev** [comment]
P.S: 
In process of debug I found interesting thing in rc-form/lib/createBaseForm.js, at validateFieldsInternal() method. 
Here lib  call such getter:
var fieldErrors = (0, _get2['default'])(errorsGroup, name);
And for case of 'name' form field (simple input) as an answer we have object with errors property. Code below expect that we always have fieldErrors.errors property. But for case of 'trips' field getter returns array with errors

**Comment by zombieJ** [comment]
Form.Item only accept direct error by field to display. You should use `validator` to customize flatten error for the nest error.

**Comment by alex-knyazev** [comment]
> Form.Item only accept direct error by field to display. You should use `validator` to customize flatten error for the nest error.

But async-validator lib is supported  validation function with nested rules, and I did all like in their documentation.

And, again validateFields function can find errors. I think that if validate function can find errors - they should be saved to errors of field. I already have good way to describe nested fields rules, so I don't want to create my custom function.

I've created the related issue here: https://github.com/react-component/form/issues/363

**Comment by zombieJ** [comment]
@alex-knyazev , could you help to create a PR if possible?

**Comment by alex-knyazev** [comment]
> @alex-knyazev , could you help to create a PR if possible?

I can't do it now, but I already found solution for my issue (thank you for advice). The solution is similar to what I had before

[https://github.com/alex-knyazev/antd-validation-bug-reproduction/commit/e613f80da8fb36394f5d1b17c4f3eb691347e124](url)
