### ISSUE TITLE
API  Card组件的tabBarExtraContent参数添加版本是3.23.0  

### ISSUE THREAD

**Issue by lss3813057** [ant-design/ant-design#20882]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/card-cn/](https://ant.design/components/card-cn/)

### Steps to reproduce
API  Card组件的tabBarExtraContent参数添加版本是3.23.0   api中未标明，一开始以为所有版本都有，查了GIT才看到

### What is expected?
在API中添加版本信息

### What is actually happening?
在API中添加版本信息

| Environment | Info |
|---|---|
| antd | undefined |
| React | react  |
| System | 所有 |
| Browser | 所有 |

**Comment by yoyo837** [comment]
Close #20882 via #20890.
