### ISSUE TITLE
Form表单InputNumber设置校验最小长度，会触发is not a string规则

### ISSUE THREAD

**Issue by satan31415** [ant-design/ant-design#20895]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-snow-m5fo3)

### Steps to reproduce
InputNumber 输入的值取出来确认不是 string 类型

### What is expected?
 不会触发校验 string

### What is actually happening?
 Form 表单 Input rules=[{min:7}] 会触发 string 类型校验

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | 16.12.0 |
| System | macOs 10.13.6 |
| Browser | Chrome  79.0.3945.117 |

![image](https://user-images.githubusercontent.com/7278892/72332600-42926800-36f5-11ea-9479-783ca0e8cca4.png)

**Comment by yoyo837** [comment]
严格来说，number 是不应该支持length 的，你可以试试html input type="number" 的length, 所以你要么改为<Input />，要么写validator, 如果作者接受，你也可以发PR https://github.com/yiminghe/async-validator

**Comment by satan31415** [comment]
谢谢你的建议，我试下
