### ISSUE TITLE
rc-drawer makes memory leak

### ISSUE THREAD

**Issue by oustn** [ant-design/ant-design#20903]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shy-bash-vvw95)

### Steps to reproduce
Click the button and rerender the Drawer component.

### What is expected?
No detached html canvas dom

### What is actually happening?
The detached canvas dom make memory leak

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.7.0 |
| System | Window10 17763.864 |
| Browser | Chrome  78.0.3904.108 |

![image](https://user-images.githubusercontent.com/16217347/72350977-69af6080-371a-11ea-953e-8f02e11cfed4.png)

[rc-drawer relative bug](https://github.com/react-component/drawer/issues/125)

**Comment by jljsj33** [comment]
把 test 提到 util 里去呗，，不要放 didmount 里呗。。pr welcome...

**Comment by jljsj33** [comment]
@shaodahong 跟一下？

**Comment by oustn** [comment]
> 把 test 提到外面里去呗，，不要放 didmount 里呗。。pr welcome...

解决当然好解决，但是没仔细看这里加个这个用来干嘛，所以没随意提 pr

**Comment by shaodahong** [comment]
@oustn 
晚点我看下，这个是 function support 用的，https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

**Comment by oustn** [comment]
> @oustn
> 晚点我看下，这个是 function support 用的，https://developers.google.com/web/tools/lighthouse/audits/passive-event-listeners

这个之前还真的没注意 官方给的 polyfill 可能更好一点

**Comment by jljsj33** [comment]
这是在无线端拦截 touch 事件冒泡，我们的抽屉在展开时是锁定背景滚动的。
