### ISSUE TITLE
docs: 各组件中 API 中 string 的一致性

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#20907]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/button-cn/](https://next.ant.design/components/button-cn/)

### What is expected?
- 描述方式一致

### What is actually happening?
- 描述方式不一致

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | The latest |

### 各组件中描述 概览

| 组件         | 属性                                | 类型定义方式                                                 | 备注                                                  |
| ------------ | ----------------------------------- | ------------------------------------------------------------ | :---------------------------------------------------- |
| Typography   | type                                | `secondary`, `warning`, `danger`                             |                                                       |
| Grid         | align 、justify                     | `top` `middle` `bottom`                                      |                                                       |
| Menu         | mode、theme                         | string: `vertical` `horizontal` `inline`                     |                                                       |
| Steps        | type 等                             | string                                                       | 可选值在说明中列出                                    |
| Cascader     | expandTrigger、popupPlacement、size | string                                                       | 可选值在说明中，其中 popupPlacement 的类型写成了 Enum |
| DatePicker   | mode、picker                        | `date`, `week`, `month`, `year`                              | 我看描述，是不是 4.0 已经取消了 mode 呢？             |
| Form         | labelAlign、layout 、size           | 'left' \| 'right'                                            | size 使用 `small \| middle \| large`                  |
| InputNumber  | size                                | string                                                       | 说明中未列出可选                                      |
| Input        | size                                |                                                              | 同 Steps 组件                                         |
| Mentions     | placement                           | 'top' \| 'bottom'                                            |                                                       |
| Radio        | size、buttonStyle                   | `large` \| `default` \| `small`                              |                                                       |
| Switch       | size                                |                                                              | 同 Steps 组件                                         |
| TreeSelect   | size                                |                                                              | 同 Steps 组件                                         |
| Upload       | listType                            |                                                              | 同 Steps 组件                                         |
| Collapse     | expandIconPosition                  | `left`                                                       | 可选值在说明中列出，类型中写了默认值                  |
| Carousel     | dotPosition                         |                                                              | 同 Steps 组件                                         |
| Card         | size                                |                                                              | 同 Radio 组件                                         |
| Calendar     | mode                                |                                                              | 同 Steps 组件                                         |
| Descriptions | size、layout                        |                                                              | 同 Radio 组件                                         |
| List         | size、position                      |                                                              | size 同 Radio 组件，position 同 From 组件             |
| Tree         | expandAction                        |                                                              | 同 Steps 组件                                         |
| Tooltip      | placement、trigger                  |                                                              | 同 Steps 组件                                         |
| Timeline     | mode、position                      |                                                              | 同 Radio 组件                                         |
| Tabs         | size、tabPosition、type             |                                                              | 同 Radio 组件                                         |
| Table        | size                                | default \| middle \| small                                   |                                                       |
| Alert        | type                                |                                                              | 同 Steps 组件                                         |
| Drawer       | placement                           |                                                              | 同 From 组件                                          |
| Progress     | status                              |                                                              | 同 Steps 组件                                         |
| Result       | status                              | `'success' \| 'error' \| 'info' \| 'warning'\| '404' \| '403' \| '500'` |                                                       |
| Spin         | size                                |                                                              | 同 Steps 组件                                         |
| Skeleton     | shape、size                         | Enum{ 'large', 'small', 'default' }                          |                                                       |
| Divider      | orientation、type                   | enum: `left` `right`                                         |                                                       |

### 各组件描述 总结
| 分类 | 类型                               | 说明       |
| ---- | ---------------------------------- | ---------- |
| 1    | string                             | 列出可选值 |
| 2    | default \| middle \| small         |            |
| 3    | 'default' \| 'middle' \| 'small'   |            |
| 4    | `default` \| `middle` \| `small`     |            |
| 5    | `default` `middle` `small`         |            |
| 6    | `default`, `middle`, `small`       |            |
| 7    | string: `default` `middle` `small` |            |

### 疑问

- 是否需将各组件中 描述信息保持一致？
- 各组件采用相同定义方式？
- 还是根据不同情况（如意义、可选值数量）进行分别定义？

**Comment by zombieJ** [comment]
第 4 种感觉好点

**Comment by shaodahong** [comment]
size 这种可以抽出来放到公用的，直接跳过去

**Comment by xrkffgg** [comment]
> 第 4 种感觉好点

有些可选值多的，那一项会列出很多

**Comment by zombieJ** [comment]
> size 这种可以抽出来放到公用的，直接跳过去

`size`  内部是同一个接口，文档里不建议跳走。没多少字，用户还要切页面反而不太方便。

**Comment by xrkffgg** [comment]
### Tip
- List：grid props 英语 API 中 有 size 属性，中文无
- Form：validateMessages属性 英文 API 中显示中文，未翻译
- Pagination：showLessItems属性 中文 API 中显示英文
- 有些组件文档中有 “版本”，有些没有，并且有的均为空，该定义是否在 4.0 中取消？或是正式版本该值 再开始维护？

**Comment by yoyo837** [comment]
版本 是当初为4.0清理掉了，相当于从0开始就有的。和3.x无关了。

**Comment by xrkffgg** [comment]
@yoyo837 👌

**Comment by xrkffgg** [comment]
@yoyo837 要不要 我提个 PR 把所有API 中 “版本” 都去掉？

**Comment by xrkffgg** [comment]
还有那 2 个 中英文 未翻译的 要怎么处理？

**Comment by xrkffgg** [comment]
还有一个 中 英文 API 不一致

**Comment by yoyo837** [comment]
😂，可以给PR 打[WIP]。

**Comment by yoyo837** [comment]
> @yoyo837 要不要 我提个 PR 把所有API 中 “版本” 都去掉？

4.0 正式版以后新增的API还是需要它的呀。
