### ISSUE TITLE
Transfer异步加载数据时，已选择的总数不对

### ISSUE THREAD

**Issue by wind1996** [ant-design/ant-design#20901]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/93xeb)

### Steps to reproduce
在第一页选择两条数据，移到右边，此时右边显示已选择的条数为2 items，然后左边翻页 2 items 变为0 items

### What is expected?
在第一页选择两条数据，移到右边，此时右边显示已选择的条数为2 items，然后左边翻页 2 items 不变，或可以通过props控制已选则总数

### What is actually happening?
在第一页选择两条数据，移到右边，此时右边显示已选择的条数为2 items，然后左边翻页 2 items 变为0 items

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1|
| React | 16.12 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
选择总是展示当前页的选中项，移过去后就不算了。
