### ISSUE TITLE
Allow `filterDropdown` to be auto-confirmed on visibility change

### ISSUE THREAD

**Issue by cusspvz** [ant-design/ant-design#20905]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, if we set a `filterDropdown` option on the `Table` `column` prop, [it stops being confirmed](https://github.com/ant-design/ant-design/blob/3ee0e4a58e0f93aaf3cec89dad1488c7a060ef02/components/table/hooks/useFilter/FilterDropdown.tsx#L155) everytime the visibility changes.

I think this feature might also be useful for those who set custom components as long as developers are able to turn it off. Right now there's no way to go around it.

### What does the proposed API look like?
I'd propose a flag for either making it available or to turn it off in case you're willing to introduce a functional breaking change. As so, either one of both:

```
<Table columns={[
  {
    filterConfirmClickedOutside: true, // default: true (in case you're willing to introduce a functional bc)
    filterDropdown () {
      return null
    },
  }
]} />
```

**Comment by zombieJ** [comment]
Thanks for feedback. We may not add additional prop to handle this. Please use customize dropdown if need this feature.
