### ISSUE TITLE
Button 在Table为Empty时，被空状态覆盖

### ISSUE THREAD

**Issue by macc6579** [ant-design/ant-design#20919]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-jshx9)

### Steps to reproduce
1.改变button与表格的相对位置（通过滚动鼠标或者调整位置）
2.Table数据为空

### What is expected?
Table为空 Button 也可以展示在顶层

### What is actually happening?
Table为空 Button 被空状态覆盖

| Environment | Info |
|---|---|
| antd | 3.26.4 |
| React | 16.10.2 |
| System | macOS Catalina 10.15.2 |
| Browser | Chrome  79.0.3945.88（正式版本） （64 位） |

---
附注：Table中有数据Button展示正常。
【也可能是我的使用姿势不对。。。望大佬指点！感激不尽

**Comment by zombieJ** [comment]
`z-index`: https://codesandbox.io/s/antd-reproduction-template-jshx9

**Comment by yoyo837** [comment]
`.ant-table-placeholder` 上有个`z-index`,   功能需要不能去掉是吧？

**Comment by zombieJ** [comment]
特意的。

ref: https://github.com/ant-design/ant-design/issues/7142

**Comment by yoyo837** [comment]
ref: https://github.com/ant-design/ant-design/commit/f321596e044d1f19e1f5245cc98dd718d3ffc687
