### ISSUE TITLE
在IE9浏览器中，Modal弹窗中的内容在设置了文字超出部分以省略号展示时省略号消失

### ISSUE THREAD

**Issue by hter1988** [ant-design/ant-design#20917]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-modal-ie9-dge9i)

### Steps to reproduce
```javascript
 <Modal
    title={'详情'}
    width={300}
    visible={true}
    footer={null}
>
    <div
        style={{
            width: 250,
            height: 20,
            overflow: 'hidden',
            whiteSpace: 'nowrap',
            textOverflow: 'ellipsis'
        }}
    >
        这个是为了验证在WIN7中IE9浏览器下面，Modal弹窗中的内容在设置了文字超出部分以省略号展示时的问题
    </div>
</Modal>
```

### What is expected?
在IE9浏览器中展示，文字超出部分的省略号正常展示

### What is actually happening?
在IE9浏览器中展示，省略号消失没有展示出来

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.5.2 |
| System | win7 |
| Browser | IE9 |

**Comment by afc163** [comment]
https://stackoverflow.com/a/13260224/3040605
