### ISSUE TITLE
Table固定列高度不会变化

### ISSUE THREAD

**Issue by LuMaowei** [ant-design/ant-design#20916]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-bohr-k3g5h?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
拖动textarea右下角调整高度

### What is expected?
固定列行高度随动

### What is actually happening?
固定列行高度不变

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | Window 10 1903 |
| Browser | Chrome  79.0.3945.117 |

**Comment by afc163** [comment]
你声明的 antd 版本和你提供的 codesandbox 里的 antd 版本不一致。

**Comment by afc163** [comment]
https://codesandbox.io/s/hungry-rhodes-eujwg

`4.0.0-rc.1` 里已经修复了。
