### ISSUE TITLE
增加下拉列表在分组模式下支持搜索功能

### ISSUE THREAD

**Issue by insomniahl** [ant-design/ant-design#20918]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
下拉列表分组模式下数据过多的时候，可以快速对内嵌内容进行搜索

### What does the proposed API look like?
跟未分组搜索结果一致(带上分组名)

**Comment by zombieJ** [comment]
哪个组件？Menu 还是什么？

**Comment by insomniahl** [comment]
> 哪个组件？Menu 还是什么？

Select组件 OptGroup，在设置了showSearch, optionFilterProp="children"后，不能对分组里的内容进行搜索
并且通过filterOption方法找不到OptGroup 里的组内数据

**Comment by zombieJ** [comment]
![Kapture 2020-01-15 at 16 33 33](https://user-images.githubusercontent.com/5378891/72417916-d1b28500-37b4-11ea-8eac-b33471a6e0bb.gif)

 应该是你的 `children`不是 `string` 导致的。

ref: https://codesandbox.io/s/serene-nobel-0pwf5

**Comment by insomniahl** [comment]
> ![Kapture 2020-01-15 at 16 33 33](https://user-images.githubusercontent.com/5378891/72417916-d1b28500-37b4-11ea-8eac-b33471a6e0bb.gif)
> 
> 应该是你的 `children`不是 `string` 导致的。
> 
> ref: https://codesandbox.io/s/serene-nobel-0pwf5

找到问题了，因为需求原因，给文字加了Tooltip组件，导致不能够搜索
