### ISSUE TITLE
In Select component, avoid clear icon to hide trigger icon

### ISSUE THREAD

**Issue by abenhamdine** [ant-design/ant-design#20927]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

Remark: it's not the same as https://github.com/ant-design/ant-design/issues/20887 which deals with overlap between clear icon and token selection

### What problem does this feature solve?

See https://next.ant.design/components/select/#header, Basic Usage, 4th Select component : 

the current behaviour in Select component regarding the trigger is :  when a value is selected and when the user hover the arrow icon, the icon change to become the clear icon.  

IMO, it's not a good design to change the icon and the corresponding behaviour on hover : it's confusing because if the user only want to expand the select, he tries to click the trigger, but instead of expanding the Select, it clears the field.

**Example :** 

here, the user should want to expand the Select to choose an other value : 

![image](https://user-images.githubusercontent.com/7466144/72427376-e62e5780-378b-11ea-90d4-68a6e82950ce.png)

...but it will clear the field instead  

![image](https://user-images.githubusercontent.com/7466144/72427387-ef1f2900-378b-11ea-975a-6af5d8375129.png)

It would be more convenient to display clear icon left to the arrow icon.

For instance, it's that some other libraries do : 

- SyncFusion : https://ej2.syncfusion.com/react/demos/#/material/combo-box/default (on click on field)
![image](https://user-images.githubusercontent.com/7466144/72427430-04945300-378c-11ea-9741-d1463f0fce6c.png)

- https://github.com/jedwatson/react-select  : https://react-select.com/home (icon always visible)
![image](https://user-images.githubusercontent.com/7466144/72432716-0106c900-3798-11ea-88a3-a7b97e9e084b.png)

- fomantic-ui : https://fomantic-ui.com/modules/dropdown.html#clearable-selection (icon always visible)
![image](https://user-images.githubusercontent.com/7466144/72432867-65298d00-3798-11ea-92b3-ac7c46510612.png)

- Kendo UI for React : (on hover) : https://www.telerik.com/kendo-react-ui/components/dropdowns/combobox/
![image](https://user-images.githubusercontent.com/7466144/72432972-9dc96680-3798-11ea-8a4f-e1d40ce4ca87.png)

### What does the proposed API look like?
On hover on Select, display clear icon left to arrow icon

**Comment by xrkffgg** [comment]
You can click directly inside the box instead of necessarily using the icon

**Comment by zombieJ** [comment]
Thanks for feedback.  Our designer have considered this, the clearIcon overlap the dropdown is assume that user already know the whole block of Select can be selectable (as native select), so we reuse the place to make it much place for display content.

Another consider is that currently antd is still focus on the PC experience. If apply for mobile, there is no hover state. Which may adjust clear logic & place. But not so quick, we do not have plan yet.

**Comment by bali48** [comment]
how can we make display clear Icon conditionally. since currently we don't have any option for it

**Comment by benbenbuhben** [comment]
I strongly agree with @abenhamdine that the overlapping placement of the clear icon and arrow icon presents a UX problem. Whenever I've used this component, I always receive the feedback that users accidentally clear all of the selected options when they try to open the dropdown. So I need to add custom styles to shift the clear icon to the left (as in the examples provided in the original post). I would suggest re-opening this issue to make the offset placement the default styling.

**Comment by Andrik264** [comment]
Same problem. I would also suggest re-opening this issue to make the offset placement the default styling.
