### ISSUE TITLE
Edit cell in table will take the unsaved value to next editing cell if i change the edit row when editing? 我在编辑单元格的时候，如果未保存单元格的值而直接点击下一行单元格编辑会把当前编辑的值带过去，请问这是什么原因？

### ISSUE THREAD

**Issue by owiki** [ant-design/ant-design#20923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-lamport-m8q9m?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. 点击第一行单元格进入编辑状态，随便输入几个值改变编辑单元格的值；
2. 然后直接点击第二行单元格，这时会看到前面未保存的编辑值带了过去

### What is expected?
点击下一行编辑的话，当前未保存的编辑值不会影响到下一行编辑状态

### What is actually happening?
未保存当前行而点击下一行，就会把当前编辑的值带过去，影响到下一行表单初始值的显示

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | latest |
| System | win10 1903 |
| Browser | chrome版本 79.0.3945.117（正式版本） （64 位） |

---
我这边是将可编辑单元格拿了出来作为一个单独的组件，并且对initialValue进行了内部封装，获取表格的值，不知道这个是否会有影响

**Comment by zombieJ** [comment]
`toggleRowEdit` 在处理切换时已经重置掉输入的值。

ref: https://ant.design/components/table-cn/#components-table-demo-edit-row

**Comment by owiki** [comment]
😥抱歉，没懂你的意思是什么🤣，`toggleRowEdit`并没重置输入的值啊？我并没有用可编辑行那个去实现，是可编辑单元格的。这个`initialValue`我也是从`record`拿过来的呀
