### ISSUE TITLE
[4.0 rc1][form] setFieldsValue 如何为 NamePath 是 array 类型的字段设置

### ISSUE THREAD

**Issue by lich-yoo** [ant-design/ant-design#20924]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crimson-waterfall-8exev)

### Steps to reproduce
点击 SetFields 无法为 Name 字段设置 value

### What is expected?
调用 setFieldsValue 接口，可以为 NamePath 是 array 类型的字段设置 value

### What is actually happening?
无法为 NamePath 是 array 类型设置

| Environment | Info |
|---|---|
| antd | undefined |
| React | latest |
| System | window 7 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/peaceful-shannon-dfn1v

**Comment by lich-yoo** [comment]
> https://codesandbox.io/s/peaceful-shannon-dfn1v

好的，了解。谢谢
