### ISSUE TITLE
Is there any way to use Simple and Mini size mode of Ant design pagination together in pagination props inside Table?

### ISSUE THREAD

**Issue by oemremolla** [ant-design/ant-design#20929]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---  The simple mode of pagination provides control like : < 1 / 5 /> but without show size changer that gives drop-down with options 10/page, 20/page and so on.

I need to show "showsizechanger" with pagination control of simple mode, I tried this, but it doesn't help to show the showSizeChanger drop-down.

`<Pagination simple size="small" total={50} showSizeChanger  />`

Expected result: Simple mode pagination control < 1/ 5/> with the showSizeChanger drop-down control which comes up with Mini size mode of pagination.

Actual: Simple mode of pagination not able to integrate with showSizeChanger

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by oemremolla** [comment]
The pagination takes up a lot of space on the page. We can fix this problem using simple mode, but we cannot use pagination props in simple mode.
The props of pagination must be available in simple mode.

https://codesandbox.io/s/bold-snow-2vkgh

https://codesandbox.io/s/priceless-moon-4xt65

**Comment by yoyo837** [comment]
https://ant.design/components/pagination/#API
