### ISSUE TITLE
Input.TextArea组件带上清除图标属性（allowClear）时，只能拉大输入框，缩小输入框无效

### ISSUE THREAD

**Issue by flyfinec** [ant-design/ant-design#20920]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pnd6n)

### Steps to reproduce
https://ant.design/components/input-cn/ 文档中 带移除图标 的demo就能重现，只能拉大不能缩小TextArea输入框

### What is expected?
跟随鼠标放大与缩小输入框

### What is actually happening?
只能放大，不能缩小输入框

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | win 10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
Duplicated of #19652.
