### ISSUE TITLE
InputNumber: can't handle event propagation in onChange callback since we can only access value instead of event.

### ISSUE THREAD

**Issue by haowen737** [ant-design/ant-design#20922]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8hy03)

### Steps to reproduce
Using InputNumber in nested antd component:
1. Change InputNumber value by clicking increase/decrease button in InputNumber component.
2. Step1 cause Checkbox value change.

### What is expected?
If event was passed from onChange callback, we can handle this situation by controlling event propagation.

### What is actually happening?
onChange callback only passed value as param.

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | macOS High Sierra |
| Browser | Google Chrome 79.0.3945.88 |

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/antd-reproduction-template-ibslk
