### ISSUE TITLE
Slider doesnt work in range mode

### ISSUE THREAD

**Issue by swapnilingle15** [ant-design/ant-design#20938]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-glitter-6ufyx?fontsize=14&hidenavigation=1&theme=dark)
ref: #16533
### Steps to reproduce
1. import ant design Slider component with range mode (Pass range property)
2. Passed Slider component to the redux form <Field component={Slider} /> component

### What is expected?
Slider component with range mode should work 

### What is actually happening?
getting below error - 
value.map is not a function
ComponentEnhancer.Range
https://6ufyx.csb.app/node_modules/rc-slider/lib/Range.js:123:24
new ComponentEnhancer(Range)
https://6ufyx.csb.app/node_modules/rc-slider/lib/common/createSlider.js:92:143
constructClassInstance
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:14204:18
updateClassComponent
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:18413:5
beginWork$1
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:20186:16
HTMLUnknownElement.callCallback
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:336:14
Object.invokeGuardedCallbackDev
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:385:16
invokeGuardedCallback
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:440:31
beginWork$$1
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25780:7
performUnitOfWork
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24695:12
workLoopSync
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24671:22
performSyncWorkOnRoot
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24270:11
scheduleUpdateOnFiber
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:23698:7
updateContainer
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27103:3
eval
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27528:7
unbatchedUpdates
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:24433:12
legacyRenderSubtreeIntoContainer
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27527:5
Object.render
https://6ufyx.csb.app/node_modules/react-dom/cjs/react-dom.development.js:27608:10
evaluate
/src/index.js:11:9
8 |
9 | const rootEl = document.getElementById("root");
10 |

11 | ReactDOM.render(
| ^
12 |
13 | <div style={{ padding: 15 }}>
14 |

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | Ubuntu 18.04 |
| Browser | Chrome - Version 79.0.3945.117 (Official Build) (64-bit) |

**Comment by swapnilingle15** [comment]
@yoyo837 Yes that's the issue I'm getting. If you remove **range** parameter from <Slider /> component it will work but I'm looking for range slider in redux-form.

**Comment by zombieJ** [comment]
Your value pass `''` which is not an array:
<img width="214" alt="截屏2020-01-19下午3 15 11" src="https://user-images.githubusercontent.com/5378891/72676635-7e9b4380-3ace-11ea-9b57-1bb1e9e6f969.png">

You can also get the value type error in console:
<img width="1020" alt="截屏2020-01-19下午3 15 48" src="https://user-images.githubusercontent.com/5378891/72676647-9d013f00-3ace-11ea-9647-32e125f3cbca.png">
