### ISSUE TITLE
table组件隐藏列无效果，不知道官方有没有发现

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2093]

**Comment by afc163** [comment]
请描述清楚问题。

**Comment by wuhaih** [comment]
columns: [{
      title: '专业公司编码1',
      dataIndex: 'andywu1',
      key: 'andywu1',
     with:0
    },{
      title: '专业公司编码2',
      dataIndex: 'andywu2',
      key: 'andywu2',
     with:100
    }
],

我想隐藏专业公司编码1，故设置with:0 然而界面毫无效果，并没有被隐藏，请问我该怎么做

**Comment by afc163** [comment]
with => width

注意拼写，以及问题的质量。

**Comment by wuhaih** [comment]
不好意思，回复你的时候手写的，如果不显示第一列，可以不配置，但官方提供的width =0确实没效果

**Comment by wuhaih** [comment]
我觉得你们可以试一下，虽然很微小的一功能，确实是一个bug

**Comment by afc163** [comment]
我看看。

**Comment by afc163** [comment]
确实有问题，因为表格默认布局是 `table-fixed: auto`。这种情况下，width 会依赖内容本身的宽度，如果有文字则无法设置为 0。如果改为 `table-fixed: fixed` 可以解决，但会带来其他布局问题。

因此还是推荐用数据或 className 来隐藏列。http://codepen.io/anon/pen/RRGaxV?editors=0110

**Comment by wuhaih** [comment]
好的，非常感谢
