### ISSUE TITLE
Upload组件能否加个图标接口

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#20937]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可自定义Upload组件上传后展示的文件列表的右侧删除Icon、上传Icon

### What does the proposed API look like?
| 参数            | 说明                                                                                                  | 类型                                         | 默认值                |
| --------------- | ----------------------------------------------------------------------------------------------------- | -------------------------------------------- | --------------------- |
| `closeIcon` | 文件列表的删除按钮                      | React.ReactElement             | `undefined`           |
| `downloadIcon`      | 文件列表的下载按钮                             | React.ReactElement                                   | `undefined`                |

**Comment by yoyo837** [comment]
可以尝试改造`showUploadList` 支持`Icon`或`React.ReactNode`。

**Comment by xrkffgg** [comment]
一般情况下，我觉得这种都不会改吧

如果你要自己用，可以在本地改下
https://github.com/ant-design/ant-design/blob/ff079e7d2a1f42487b2c57702c11cd1f2c1efecb/components/upload/UploadList.tsx#L174-L179
`DeleteOutlined`  `DownloadOutlined `  改成你想要的图标就行，但是要自定义引入

**Comment by yoyo837** [comment]
@xrkffgg 你这回答，倒不如直接说不支持！😂

**Comment by xrkffgg** [comment]
因为我觉得这个需求可能不太符合设计规范吧 😂

**Comment by yoyo837** [comment]
其实就是对内置的`Icon`不满意。

**Comment by xrkffgg** [comment]
要想满足所有人很难啊，不过能自定义也不错~
