### ISSUE TITLE
Error component demo

### ISSUE THREAD

**Issue by futirstanjo** [ant-design/ant-design#20930]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/auto-complete/](https://next.ant.design/components/auto-complete/)

### Steps to reproduce
demo has bug 

### What is expected?
the icon of the same size as the input

### What is actually happening?
the icon is smaller than the input

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 00000 |
| System | mozila firefox |
| Browser | 71.0 |

---
Lookup-Patterns - Uncertain Category this component has bug.

**Comment by afc163** [comment]
https://next.ant.design/components/auto-complete/#components-auto-complete-demo-uncertain-category
