### ISSUE TITLE
transfer表格穿梭框 当全选后，两栏之间转移后如果剩带有禁用的数据，全选框是勾着的

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#20933]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/transfer-cn/#components-transfer-demo-table-transfer](https://next.ant.design/components/transfer-cn/#components-transfer-demo-table-transfer)

### Steps to reproduce
 当全选后，两栏之间转移后如果剩下带有禁用的数据，全选框是勾着的且去不掉

### What is expected?
两栏之间转移后如果剩下带有禁用的数据，全选应该是不可用状态且不是勾选状态

### What is actually happening?
还是之前勾选的状态
![image](https://user-images.githubusercontent.com/48147837/72492342-cebca080-3857-11ea-8209-4cfab267479e.png)

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | win 10 |
| Browser | google |

**Comment by xrkffgg** [comment]
这个其实是 Table  的 bug

**Comment by zombieJ** [comment]
添加一个 codesandbox：https://codesandbox.io/s/interesting-edison-oro08
