### ISSUE TITLE
Drawer 的 关闭按钮可以自定义位置

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#20935]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些需求 需要关闭按钮在 Drawer Header的左边，这样就要去修改Drawer原有的css

### What does the proposed API look like?
closePosition: left | right

**Comment by XianZhengquan** [comment]
好的

**Comment by fupengl** [comment]
这个之前的版本都是在右边的,现在这个改动有些粗暴
