### ISSUE TITLE
Form用getFieldDecorator时，子组件如果是函数组件，会报React警告说函数组件不能用refs

### ISSUE THREAD

**Issue by ytyjxym** [ant-design/ant-design#20932]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/20870#issuecomment-573973963
