### ISSUE TITLE
Transfer组件，加载时父组件的display为none，之后再将父组件修改为显性，Transfer组件里面的选项都不会渲染，除非用鼠标滚动下

### ISSUE THREAD

**Issue by bingjiu** [ant-design/ant-design#20945]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/](https://github.com/ant-design/ant-design/)

### Steps to reproduce
Transfer组件，加载时父组件的display为none，之后再将父组件修改为显性，Transfer组件里面的选项都不会渲染，除非用鼠标滚动下

### What is expected?
Transfer组件里面的选项应该是正常显示的

### What is actually happening?
Transfer组件里面的选项都不会渲染，除非用鼠标滚动下

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | 谷歌 |

**Comment by afc163** [comment]
`lazy={false}`
