### ISSUE TITLE
tooltip配合checkbox.group的disabled状态使用，移出不消失

### ISSUE THREAD

**Issue by wjeek** [ant-design/ant-design#20940]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-emh8nk](https://stackblitz.com/edit/react-emh8nk)

### Steps to reproduce
鼠标移到checkbox上，然后再左移出去

### What is expected?
鼠标移到checkbox上，然后无论怎么移出去，tooltip均消失

### What is actually happening?
鼠标移到checkbox上，然后再左移出去，发现tooltip不消失

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.9.0 |
| System | mac |
| Browser | 79.0.3945.117 |

**Comment by afc163** [comment]
这是 Chrome 的一个老问题，建议用这样的方式规避：https://stackblitz.com/edit/react-emh8nk

https://github.com/ant-design/ant-design/pull/4865/files#diff-186839a30bf8b9d67a4b10bf7c091d5fR88
https://github.com/react-component/tooltip/issues/18
https://github.com/ant-design/ant-design/issues/17449
#18534

**Comment by wjeek** [comment]
> 这是 Chrome 的一个老问题，建议用这样的方式规避：https://stackblitz.com/edit/react-emh8nk
> 
> https://github.com/ant-design/ant-design/pull/4865/files#diff-186839a30bf8b9d67a4b10bf7c091d5fR88
> [react-component/tooltip#18](https://github.com/react-component/tooltip/issues/18)
> #17449
> #18534

 我这里内部组件是input，pr里解决的是button，貌似还没解决

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-emh8nk

**Comment by rinick** [comment]
> https://stackblitz.com/edit/react-emh8nk

用这个链接仍然可以重现这个bug

**Comment by rinick** [comment]
> https://stackblitz.com/edit/react-emh8nk

@afc163  用这个链接仍然可以重现这个bug
