### ISSUE TITLE
请问下antd图片上传(Upload)的预览框可不可以设置大小和样式呢?

### ISSUE THREAD

**Issue by laolu87** [ant-design/ant-design#2094]
制作列表时我使用的listType是文档示例中的那个'picture-card',请问它的上传框和预览框可不可以设置大小呢?如果可以需要怎么设置呢?

**Comment by afc163** [comment]
样式覆盖。

**Comment by laolu87** [comment]
@afc163  谢谢,明白了,已经弄好啦!
