### ISSUE TITLE
Jumpy and unstable side menu in Internet IE 11 and animations are not smooth

### ISSUE THREAD

**Issue by ali-h2010** [ant-design/ant-design#20947]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce](https://ant.design/docs/react/introduce)

### Steps to reproduce
access the website with IE and browse the introduction page. Scroll up and down and notice the change in the side menu

### What is expected?
the side menu should not be moved when scrolling up and down.

### What is actually happening?
Side menu is jumpy and unstable

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | React |
| System | Windows 10 |
| Browser | IE 11.1565 |

**Comment by ali-h2010** [comment]
This is a screen recording of what is happening in my side. Notice the side menu and the chating icon
[AntDesign.zip](https://github.com/ant-design/ant-design/files/4071107/AntDesign.zip)

**Comment by afc163** [comment]
We probably won't take time to optimize site expierence in IE11 now which will only use to debug component, please use modern browser for good.

**Comment by ali-h2010** [comment]
@afc163 but most enterprise companies still uses IE browser. If the demo is not working fine there, which is the first time experience, many clients will lose interest in your solution.
