### ISSUE TITLE
Selecting an Autocomplete item that defines labels and values fills out the value in the autocomplete textbox

### ISSUE THREAD

**Issue by heuristicAL** [ant-design/ant-design#20955]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6c1ms?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Select an autocomplete option
2. Value gets filled into the textbox instead of the label.

### What is expected?
The label should be shown in the textbox, not the value.

### What is actually happening?
The value is filled into the textbox instead of the label.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | MacOS 10.14.6 |
| Browser | Edge Chromium 79.0.309.58, Chrome 79.0.3945.117, Firefox Dev 73.0b5 |

**Comment by zombieJ** [comment]
AutoComplete is an Input with additional helper list. It works as Input. If you want to display `label` in selection field. Use Select instead.

**Comment by EugeneSnihovsky** [comment]
[Select component](https://ant.design/components/select) with `showSearch={ true }` attribute is almost equal to `Autocomplete` component.
