### ISSUE TITLE
Unmet dependency warning@'^2.0.0' 

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#2095]
When installing via `npm install --save antd `I have got this warning in a console:

> unmet dependency /home/developer/Documents/ttt/node_modules/antd/node_modules/rc-tabs/node_modules/history requires warning@'^2.0.0' but will load /home/developer/Documents/ttt/node_modules/antd/node_modules/warning, which is version 3.0.0

**Comment by afc163** [comment]
Programmers ignore warnings.
