### ISSUE TITLE
[4.x] Suggestion of timeline component styling

### ISSUE THREAD

**Issue by Ta2Rim** [ant-design/ant-design#20953]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It's a screenshot of [Timeline page](https://next.ant.design/)
I just removed all styles of .code-box-demo element, so now we can see the first timeline item is truncated.
![image](https://user-images.githubusercontent.com/41318449/72541620-ba3dcf80-387a-11ea-8c56-58b1afa07775.png)

It's because .ant-timeline-item-content elements are given a negative top property(-7.0001px).

![image](https://user-images.githubusercontent.com/41318449/72542629-5b795580-387c-11ea-8f2a-e2d617ef7d1b.png)

It also makes the last timeline item take unused space.

### What does the proposed API look like?
I think it's better to
1. remove the negative top property of ant-timeline-item-content elements and give top property to tail and head.
2. remove padding-bottom of the last ant-timeline-item.

**Comment by zombieJ** [comment]
Welcome to add new less variable of item padding to support customize requirement.

ref: https://github.com/ant-design/ant-design/blob/32e80157c68256209334ac83e07a961e1283650b/components/timeline/style/index.less#L20
