### ISSUE TITLE
Can't use Tooltip with Step

### ISSUE THREAD

**Issue by uturnr** [ant-design/ant-design#20957]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-field-hdlsd?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Unless using `progressDot` style which has a function that allows to override the dot component, a `Step` (`Steps.Step`) cannot be wrapped in a `Tooltip`. 

### What is expected?
Wrapping a `Step` in a `Tooltip` causes a tooltip to appear on hover.

### What is actually happening?
Wrapping a `Step` in a `Tooltip` causes the `Step` to disappear.

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | macOS 10.15.2 |
| Browser | Safari 13.0.4 |

**Comment by zombieJ** [comment]
Current Steps will loop children to add additional prop. Maybe should refactor with context instead.

**Comment by oaksharks** [comment]
Is there any progress in this issue？ I want to use Tooltip with Step too

**Comment by sangeetha-armtek** [comment]
Does anybody know a work around for this?

**Comment by kartikey-gen** [comment]
https://stackoverflow.com/questions/77190220/i-want-to-use-tooltip-with-steps-stepper-in-antdesign-i-am-not-able-to-do-so-is

**Comment by EmilyyyLiu** [comment]
You can try using Tooltip on the title attribute of the Step.
Using it this way should meet your expectations.

Here is an example.
 https://codesandbox.io/p/sandbox/tooltip-steps-forked-fgsgvy?workspaceId=ws_T98hW5dcqudRAGy3wbJh83

**Comment by zombieJ** [comment]
Ref to @EmilyyyLiu 's sample. Since v5 recommend to use `items` instead of jsx structure. We may not do more action on this.
