### ISSUE TITLE
被 Form 包裹的 DatePicker 如果有 initialValue 参数，日期会提前一天

### ISSUE THREAD

**Issue by Benpaodejiezai** [ant-design/ant-design#20958]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-gnzfhz-wx3gr6?file=index.js](https://stackblitz.com/edit/react-gnzfhz-wx3gr6?file=index.js)

### Steps to reproduce
选择两个日期，点击提交

### What is expected?
正确打印出所选时间

### What is actually happening?
第一个 DatePicker 会减少一天，时间归到16点，因为有 initialValue 参数
第二个 DatePicker 时间会提8小时

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | macOS |
| Browser | chrome |

---
第一个 DatePicker 使用 .format() 会添加8小时，变为所选当天的0点
第二个 DatePicker 使用 .format() 添加8小时后，变为正确的所选年月日和当前的时分秒
被form包裹的DatePicker必须使用 .format() 来格式化时间吗？这是唯一的解决办法？antd pro 项目，有没有全局解决办法

**Comment by afc163** [comment]
看上去和 antd 没关系，你可以打印一下：

```js
console.log(moment('2020-01-01'));  // 2019-12-31T16:00:00.000Z
console.log(moment('2020-01-01').format());  // 2020-01-01T00:00:00+08:00
```

`2020-01-01T00:00:00+08:00` 和 `2020-01-01T00:00:00+08:00` 本质上是同一个时间。

**Comment by Benpaodejiezai** [comment]
> 看上去和 antd 没关系，你可以打印一下：
> 
> ```js
> console.log(moment('2020-01-01'));  // 2019-12-31T16:00:00.000Z
> console.log(moment('2020-01-01').format());  // 2020-01-01T00:00:00+08:00
> ```
> 
> `2019-12-31T16:00:00.000Z` 和 `2020-01-01T00:00:00+08:00` 本质上是同一个时间，format 之后添加了时区信息而已。

那为什么有无 initialValue 参数，打印出来的时间会不一样呢

**Comment by zombieJ** [comment]
因为你写的是 `moment('2020-01-01')`，你写成 `moment()` 打印的就是一样的。你在 StackBlitz 的 console 里看到的是被 toString 转换过的字符串。实际上你打印的是个对象：

<img width="976" alt="截屏2020-01-17上午11 56 38" src="https://user-images.githubusercontent.com/5378891/72583251-8c12cb00-3920-11ea-86df-0e26d73f8343.png">

你直接加个 `toString` 看看：
<img width="360" alt="截屏2020-01-17下午12 05 33" src="https://user-images.githubusercontent.com/5378891/72583552-ab5e2800-3921-11ea-8f9f-b0d1c97fb6af.png">

<img width="291" alt="截屏2020-01-17下午12 05 28" src="https://user-images.githubusercontent.com/5378891/72583553-af8a4580-3921-11ea-8f11-33bfd10c10f7.png">
