### ISSUE TITLE
Trigger sider on Hover mouse event 

### ISSUE THREAD

**Issue by Yogesh1807** [ant-design/ant-design#20952]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
when hover on collapsed sider then it is trigger and added width eg as 200px. right now there is only onclick trigger function.
but we want same functionality for onHover.

### What does the proposed API look like?
just add onHover event in sider props

**Comment by afc163** [comment]
https://codesandbox.io/s/jolly-river-vohqd

**Comment by gugol2** [comment]
> https://codesandbox.io/s/jolly-river-vohqd

What is wrong with the demo?
