### ISSUE TITLE
form表单有些校验，如果在必填项填完之前，点击保存，会提示如下错误：Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2096]
这是部署到测试环境提示的错误信息，报错的文件是文件: common.js，行: 30315，列: 8

common.js是 将react、 antd、 react-touter等公共的依赖抽取到common.js  

请问我该如何解决，才不会报这个错，如果必填项全部填完就OK，不会报JS错误

**Comment by benjycui** [comment]
打包时把开发环境的代码也打包进去了，建议使用 [atool-build](https://github.com/ant-tool/atool-build)，或者在你的 webpack.config.js 中加上 https://github.com/ant-tool/atool-build/blob/master/src/build.js#L34

**Comment by wuhaih** [comment]
我就是使用的antbuild，很多插件脚手架都内置了，将react antd 及react-router打包在一起，因为他们是公共的，抽comm.js。，难道不压缩在一起，extener例外构建？

**Comment by benjycui** [comment]
可以压缩在 common.js 内，确认下你用的 atool-build 版本，里面是否有这行代码 https://github.com/ant-tool/atool-build/blob/master/src/build.js#L34

**Comment by wuhaih** [comment]
我的"atool-build": "0.6.x", 看了里面的代码，貌似是没有new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'production'),
      }),
这个代码，我升级下atool-build 试试

**Comment by wuhaih** [comment]
"atool-build": "0.7.x", 最新版本脚手架和老版本的变化比较大，直接替换原来的atool-build 会不会导致IE兼容性问题，我怕有些BABEL没有loader进来，但目前打包看好像看起来一切正常，不知道有没有其他隐患？ 

备注： 我只是替换了atool-build 这个库

**Comment by wuhaih** [comment]
经测试，换了atool-build，common.js 还是会提示Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.   ,而且只有谷歌浏览器才会爆这错，其他浏览器都不会

**Comment by wuhaih** [comment]
经定位是这句代码导致的
this.props.form.validateFieldsAndScroll((errors, values) => {
          if (!!errors) {
            Modal.error({content: errors});  这句代码有问题，提示上面那个错误
            return;
          }
        });

Modal弹出框是非阻塞的，调用这句就出差，有办法解决麽

**Comment by benjycui** [comment]
信息不足。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by wuhaih** [comment]
import { Button, Form, Input, Modal } from 'antd';
const createForm = Form.create;
const FormItem = Form.Item;

let BasicDemo = React.createClass({
  handleReset(e) {
    e.preventDefault();
    this.props.form.resetFields();
  },

  handleSubmit(e) {
    e.preventDefault();
    this.props.form.validateFields((errors, values) => {
      if (!!errors) {
        console.log('Errors in form!!!');
        Modal.error({content: errors});  //这句加上执行会有问题，谷歌浏览器会报错
        return;
      }
      console.log('Submit!!!');
      console.log(values);
    });
  },

  render() {
    const { getFieldProps, getFieldError, isFieldValidating } = this.props.form;
    const nameProps = getFieldProps('name', {
      rules: [
        { required: true, min: 5, message: '用户名至少为 5 个字符' },
      ],
    });

    return (
      <Form horizontal form={this.props.form}>
        <FormItem>
          <Input {...nameProps} placeholder="实时校验，输入 JasonWood 看看" />
        </FormItem>
        <FormItem wrapperCol={{ span: 12, offset: 7 }}>
          <Button type="primary" onClick={this.handleSubmit}>确定</Button>
          &nbsp;&nbsp;&nbsp;
          <Button type="ghost" onClick={this.handleReset}>重置</Button>
        </FormItem>
      </Form>
    );
  },
});

BasicDemo = createForm()(BasicDemo);
ReactDOM.render(<BasicDemo />, mountNode);

这个是我测试的代码，你可以试试

**Comment by afc163** [comment]
学会格式化代码吧，这让人怎么看。

https://guides.github.com/features/mastering-markdown/

**Comment by benjycui** [comment]
我帮你格式化了。。就不能提供个在线 demo 么。。。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by wuhaih** [comment]
不好意思，codepen编写的demo跑不起来，公司禁止上传代码，上面代码格式化之后，你们谷歌浏览器会不会报Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.

**Comment by afc163** [comment]
```
Uncaught Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings. 
```

读一下这个文字，这个报错是压缩后的，你需要在非压缩环境重现才有可能排查。

**Comment by wuhaih** [comment]
我就是无压缩也报了这种错误，就是加了我备注的那句modal.error你们可以试下把我哪个小例子复制到本地

**Comment by afc163** [comment]
在开发环境的报错信息如下：

```
Error: Objects are not valid as a React child (found: object with keys {name}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons.
```

原因是 `Modal.error` 方法的 `content` 参数接收类型是 `React.Node`。而 errors 是一个 js 对象，无法直接渲染。请按照 API 要求进行正确的使用。

```jsx
Modal.error({
  content: 'xxxx', // or <span>xx</span>
})
```
