### ISSUE TITLE
Button禁用后Tooltip不会正常消失。

### ISSUE THREAD

**Issue by eaTong** [ant-design/ant-design#2097]
![qq 20160618093113](https://cloud.githubusercontent.com/assets/17243933/16170153/a9c1c252-357b-11e6-8522-fcdc2d86d294.jpg)
截图如上，其他地方Tooltip的表现是离开该组件之后会自动消失，但是如果是在禁用后的Button上的话则不会消失了。测试代码如下：
`<Tooltip title="禁用后Tooltip">
          <Button disabled>禁用按钮</Button>
        </Tooltip>`
实际上一开始是用的`<Tooltip title="编辑"><Button type="ghost" shape="circle" icon="edit"></Tooltip>`这种方式，后来测试的时候写成上面那种格式。

**Comment by afc163** [comment]
#1816
