### ISSUE TITLE
[3.x]Footer in Table not rendered to be a native <tfoot> tag

### ISSUE THREAD

**Issue by chrysalis1215** [ant-design/ant-design#20975]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-bordered](https://ant.design/components/table-cn/#components-table-demo-bordered)

### Steps to reproduce
1、Inspect  Footer element 
2、you will find footer is renderde as a div tag , not tfoot tag

### What is expected?
i wash to have  a flexible api to render real <tfooter>.

when i print a big table  which should has footer and header in every paper ,  but antd table can only show table header(thead) in every paper.
Footer is  not  real tfoot, and it don't have the ablibity of page group like "table-footer-group" , so it can not appear to every paper.

### What is actually happening?
footer is rendered as <div class="ant-table-footer">

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.7 |
| System | macOS Mojave10.14.6 |
| Browser | chrome 79.0.3945.117 |

---

**Comment by zombieJ** [comment]
We may not adjust `footer` structure since it will cause breaking change.

But you can use `summary` prop to render `tfoot` in v4:
https://next.ant.design/components/table/#components-table-demo-summary
