### ISSUE TITLE
Dropdown hover时偶尔会出现闪烁的情况

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#20973]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-sinoussi-tsqiq?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
hover时偶尔出现闪烁

### What is expected?
不出现闪烁

### What is actually happening?
来回hover不通按钮时会出现闪烁

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | mac |
| Browser | safari |

![屏幕录制 2020-01-13 下午3 19 24](https://user-images.githubusercontent.com/16435301/72592801-58df3480-393e-11ea-81da-b4c4fa9d322a.gif)

**Comment by zombieJ** [comment]
重现不出来……还有什么线索不，比如 safari 版本？

**Comment by zhangzhi93** [comment]
> 重现不出来……还有什么线索不，比如 safari 版本？

mac 10.14.4
safari 12.1

**Comment by zhangzhi93** [comment]
> 重现不出来……还有什么线索不，比如 safari 版本？

下拉的都会出现，官方文档上在这个版本的系统和浏览器下就可以复现

**Comment by zhangzhi93** [comment]
![屏幕录制 2020-01-19 下午3 22 21_1](https://user-images.githubusercontent.com/16435301/72676783-1ea59c80-3ad0-11ea-9f88-3df91b4fd15c.gif)

**Comment by zombieJ** [comment]
系统和 Safari 版本升级一下看看

**Comment by ludaokai** [comment]
Mac OS  10.14.4
Safari 版本 12.1 (14607.1.40.1.4)
![屏幕录制 2020-01-19 15 35 15](https://user-images.githubusercontent.com/50224242/72682074-752cce00-3b04-11ea-82a2-3857ae9b9a5e.gif)

**Comment by ludaokai** [comment]
> 系统和 Safari 版本升级一下看看

升级过了，还是一样。别外升级并不能解决用户的问题吧，咱不能要求用户都去升级浏览器对吧。
![111](https://user-images.githubusercontent.com/50224242/72684790-97cbe080-3b1e-11ea-9c89-6c9e7f90c8fb.gif)

**Comment by ludaokai** [comment]
> 系统和 Safari 版本升级一下看看

Mac 10.12.6  Safarit升级到最新了，还是一样
![111](https://user-images.githubusercontent.com/50224242/72684933-c0a0a580-3b1f-11ea-8a1a-92673a127a87.gif)

**Comment by zombieJ** [comment]
Safari 最新是 13.x：

<img width="296" alt="截屏2020-01-20上午10 56 04" src="https://user-images.githubusercontent.com/5378891/72695435-76491400-3b73-11ea-9e61-ad62b37591c1.png">

**Comment by yoyo837** [comment]
他的Mac 系统版本那么低，可能升不上来。

**Comment by zombieJ** [comment]
MAC OS 10.x 下 Safari 渲染有问题，能升级的尽量升级吧……

Merge into #9731

**Comment by ludaokai** [comment]
> MAC OS 10.12.x 下渲染有问题，能升级的尽量升级吧……
> 
> Merge into #9731

咱不能要求用户都去强行升级吧？

**Comment by yoyo837** [comment]
咱不支持，他总用不了吧？其实一个道理，你参考Chrome, Windows XP等版本演进，支持总是需要有个度的，范围或者时间长短而已。

**Comment by ludaokai** [comment]
> 咱不支持，他总用不了吧？其实一个道理，Mac OS 10.12 第一个版本发布于2016年中，你参考Chrome, Windows XP、7、8等版本演进，支持总是需要有个度的，范围或者时间长短而已。

好吧，那我就不纠结这个了
