### ISSUE TITLE
当Menu导航菜单设置为水平时，超出隐藏部分菜单怎么改它样式呢？

### ISSUE THREAD

**Issue by dongkeng001** [ant-design/ant-design#20976]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/](https://ant.design/components/menu-cn/)

### Steps to reproduce
当Menu导航菜单设置为水平时，超出隐藏部分菜单怎么改它样式呢？
如果直接覆盖样式的话，会直接影响到其它页面的导航菜单，我通过添加className，发现只能添加到当前的MenuItem里面，但没啥用，样式覆盖要在MenuItem往上父节点才能覆盖，请问这个该怎么解决呢

### What is expected?
可以给超出隐藏的菜单父节点上添加className唯一的名字，而不会影响到其它页面的Menu导航菜单样式

### What is actually happening?
覆盖样式会直接污染到其它页面的menu导航菜单样式

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | react |
| System | windows |
| Browser | 谷歌等其它浏览器 |

**Comment by ronglanly** [comment]
解决了吗？

**Comment by dh1021** [comment]
![Uploading custom.png…]()

自己造一个div加上className挂到body上，放到getPopupContainer，就不会污染页面的样式了
