### ISSUE TITLE
树形控件在使用treeData的时候希望可以定制TreeNode

### ISSUE THREAD

**Issue by liujiayii** [ant-design/ant-design#20971]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在控件比较复杂的情况下也可以不用手动构建Tree，手动构建多次嵌套代码会比较冗余，希望大佬们考虑一下，谢谢！

### What does the proposed API look like?
*

**Comment by zombieJ** [comment]
`title` 支持 renderProps，可以裹一个来处理。

```jsx
const treeData = [
  {
    title: () => 2333,
    key: '0-0-0',
  },
];
```
