### ISSUE TITLE
[4.x] Drawer添加了 footerStyle后，控制台报错

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#20978]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-bouman-21723?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
给Drawer添加footerStyle属性

### What is expected?
控制台不报错

### What is actually happening?
控制台报错

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | latest |
| System | win10 |
| Browser | chrome 79 |

**Comment by XianZhengquan** [comment]
![image](https://user-images.githubusercontent.com/46179450/72596274-afe90780-3946-11ea-9ec5-e738bb5b013d.png)
应该是把这个属性挂到 `div` 上面去了

**Comment by XianZhengquan** [comment]
还有， `headerStyle` 里面写 `height`不生效
![image](https://user-images.githubusercontent.com/46179450/72596761-61883880-3947-11ea-98ef-7fe8c8d2d0ec.png)

**Comment by XianZhengquan** [comment]
@yoyo837  `footerStyle` 这个，看了一下，感觉是 在这里加上 `footerStyle`就行了
![image](https://user-images.githubusercontent.com/46179450/72597570-fe97a100-3948-11ea-8615-490be6d08443.png)

---
但是 `headerStyle` 里面写 `height` 不生效，这个我不知道了，写 `line-height` 可以

**Comment by yoyo837** [comment]
css优先级相关。

**Comment by XianZhengquan** [comment]
> css优先级相关。

![image](https://user-images.githubusercontent.com/46179450/72597789-75cd3500-3949-11ea-9210-c958e1d3416f.png)
 !important 都不行

**Comment by XianZhengquan** [comment]
感觉只能根据 下一级 的 `.ant-drawer-title` 的高度来撑

**Comment by XianZhengquan** [comment]
@yoyo837 找到了，原因是 `.ant-drawer-body`写了 `flex-grow : 1`，我改成了 `flex : 1` 就行了
![image](https://user-images.githubusercontent.com/46179450/72598195-4b2fac00-394a-11ea-85ed-a31200839d26.png)

**Comment by XianZhengquan** [comment]
@yoyo837  ` Pull Request ` 这个流程太麻烦了，还是麻烦你们改一下吧

**Comment by yoyo837** [comment]
正常情况下每个人都是PR的方式来修改的，方便跟踪和记录。包括那边Team里的人。

**Comment by XianZhengquan** [comment]
@yoyo837 我是不是要新建一个分支，但是好像没有权限

**Comment by yoyo837** [comment]
先fork到自己名下。

**Comment by XianZhengquan** [comment]
现在已经修改完了，正在 pr

**Comment by XianZhengquan** [comment]
@yoyo837 changeLog 需要我写吗

**Comment by yoyo837** [comment]
更新下你的 reproduce 体现一下

>headerStyle 里面写 height不生效

**Comment by XianZhengquan** [comment]
> 更新下你的 reproduce 体现一下
> 
> > headerStyle 里面写 height不生效

好的，但是目前我的网络好像不怎么好 `codesandbox` 一直出不来

**Comment by yoyo837** [comment]
"科学上网法"

**Comment by XianZhengquan** [comment]
> 更新下你的 reproduce 体现一下
> 
> > headerStyle 里面写 height不生效

盒子里面又可以设置了，。。。

**Comment by XianZhengquan** [comment]
但是我本地的项目，写了 `height`还是不行

**Comment by yoyo837** [comment]
`headerStyle={{ height: 32 }}`试了是可以的.

**Comment by yoyo837** [comment]
`custom-drawer` 是你自己的样式，并且`flex`了它。

**Comment by XianZhengquan** [comment]
那这个就不算吧，我现在在怀疑我的电脑了
![image](https://user-images.githubusercontent.com/46179450/72603263-a7e39480-3953-11ea-9365-76dc56815a60.png)
随时都是 90度以上，浏览器卡
