### ISSUE TITLE
[4.x] Select onChange value set to undefined not working properly

### ISSUE THREAD

**Issue by harshil-shipmnts** [ant-design/ant-design#20979]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/white-worker-r0kyv?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1) Select a value
2) Click on "Clear" button

### What is expected?
It should reset the component value

### What is actually happening?
The state is changing to undefined but the component still shows the old value

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | macOS Catalina |
| Browser | Chrome |

**Comment by yoyo837** [comment]
ref: https://github.com/react-component/select/issues/434

**Comment by yoyo837** [comment]
@zombieJ 改成`'value' in props`吗？

**Comment by zombieJ** [comment]
> @zombieJ 改成`'value' in props`吗？

值切换成 `undefined` 后重置一下值即可，`undefined` 做成非受控是故意的。
