### ISSUE TITLE
Icon找不到模块“@ant-design/icons”

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#20982]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/icon-cn/](https://next.ant.design/components/icon-cn/)

### Steps to reproduce
import { createFromIconfontCN } from '@ant-design/icons';

### What is expected?
找得到

### What is actually happening?
找不到模块“@ant-design/icons”

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | win 10 |
| Browser | google |

**Comment by afc163** [comment]
```
npm i @ant-design/icons --save`
```

```
yarn add @ant-design/icons
```
