### ISSUE TITLE
v4 FormInstance 无法更新自定义校验的状态和结果

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ant-design/ant-design#20987]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5f7tu?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
在手机号输入框中输入 11 未的手机号

### What is expected?
1. 手机号输入框提示 “手机号可以使用”是 username 可以输入，按钮可以点击
2. 控制台不应该提示 FormInstance 未绑定到 form 元素上

### What is actually happening?
1.  username 一直不能输入，按钮一直不能点击
2. 控制台提示 FormInstance 未绑定到 form 元素上

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.0 |
| React | 16.12 |
| System | win10 |
| Browser | chrome |

**Comment by sergiofilhowz** [comment]
I actually found that if you define an useEffect putting the form instance as dependency it unnecessarily executes several times (on each state change) which can indicate that the useForm hook may have an issue creating several instances

**Comment by xiaosongxiaosong** [comment]
isFieldTouched & getFieldError worked by add shouldUpdate props on Form.Item, but isFieldValidating still not work

在Form.Item上添加shouldUpdate 属性后 isFieldTouched 和 getFieldError 可以正常工作，但是isFieldValidating 仍然有问题

[![Edit antd reproduction template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5f7tu?fontsize=14&hidenavigation=1&theme=dark)

**Comment by xiaosongxiaosong** [comment]
这个 issue 关闭掉重新提一个

@sergiofilhowz I think form  instance was changed after use input, this should be a feature and not a problem
if you do not want run useEffect every time when form changed，you can use useRef to point to useForm
```js
const [form] = Form.useForm();
const ref = React.useRef(form);
React.useEffect(() => {
  ref.current = form;
}, [form]);
React.useEffect(() => {
  // use ref.current replace form
}, []);
```
Please excuse me for my broken English.
