### ISSUE TITLE
Should hide dropdown list when disable Select component

### ISSUE THREAD

**Issue by Rey-Wang** [ant-design/ant-design#20999]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-lake-1orh1?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. focus on input
2. click Select component directly

### What is expected?
hide dropdown list when diable Select

### What is actually happening?
Observed that we can still see the dropdown list when diable Select

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12 |
| System | codesandbox |
| Browser | chrome 79 |

**Comment by Rey-Wang** [comment]
Or I think we should provide some interface can hide dropdown list directly

**Comment by zombieJ** [comment]
It's a bug, `disabled` should close popup.

**Comment by abdih** [comment]
I'm working on this.

**Comment by morenyang** [comment]
Try to fix in this pr: https://github.com/react-component/select/pull/447

**Comment by morenyang** [comment]
Seems the same issue in antd 4.x, I will take a look later

**Comment by zombieJ** [comment]
fixed in v4. Reopen for v3.
