### ISSUE TITLE
(4.0Table) 交换columns项的位置, 表头和子项的宽度不统一. (有demo地址)

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#20995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-minsky-yldt3)

### Steps to reproduce
setColumns()  to change order of columns.
用setColumns去交换columns的顺序.

### What is expected?
表头和子项能统一宽度. uniform width.

### What is actually happening?
表头和子项宽度错乱, 不统一.  width confusion

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome 79 |

---
经发现, 表头的宽度顺序 跟 table > colgroup这个节点里的内容有关.
如果setColumns只是修改宽度的话, 表头宽度也是正常显示, colgroup正常宽度变化.
但如果是更改columns项的顺序, colgroup的顺序却不会变, 所以会导致表头和子项的宽度不统一.

**Comment by zombieJ** [comment]
key 不变导致 Table 以为 column 宽度没有变化，得调整一下。
