### ISSUE TITLE
v4 Form.Item shouldUpdate 中 isFieldValidating 异常，isFieldTouched 和 getFieldError 可以正常工作

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ant-design/ant-design#20992]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5f7tu?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. 注释掉 App.js 中 41 行的 isFieldValidating('cellphone') 判断条件
2. 用户未输入手机号时 usernam 无法输入，输入的手机号不是 1 开头的 11 数字时 usernam 也无法输入，delay 1秒的校验时 usernam 可以输入
3. 将 isFieldValidating('cellphone') 判断条件的注释取消，cellphone 校验成功后 usernam 任然无法输入
4. 将其他判断条件都注释掉，用户未输入时 usernam 可以输入，只要有输入 usernam 就不能输入了

录制了一个视频放到 B 站：https://www.bilibili.com/video/av83926342/

### What is expected?
- 使用 isFieldValidating('cellphone')  时，cellphone 校验成功后 usernam 应该能够输入
- 仅使用 isFieldValidating('cellphone') 做判断条件时，仅 feedback 显示校验中时 usernam 才不能输入，其他时候 usernam 都应该可以输入

### What is actually happening?
isFieldValidating('cellphone')  只有开始返回 false，其他时候一直返回 true

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12 |
| System | win10 |
| Browser | chrome |

---
用户注册时需要校验手机号是否已经被使用，校验完成后才允许获取验证码

**Comment by zombieJ** [comment]
加一个： `dependencies={['cellphone']}`: https://codesandbox.io/s/antd-reproduction-template-th7yp

**Comment by xiaosongxiaosong** [comment]
@zombieJ 非常感谢，加上 `dependencies={['cellphone']}` 可以满足需求了

只是稍微一点点疑惑，看文档里面 dependencies 和 shouldUpdate  都可用用来触发更新，我看文档的理解是 dependencies 相比 shouldUpdate 来说同时触发更新和校验，而 shouldUpdate 只会触发更新，但是实际使用并不是这样：
- shouldUpdate 可以更新 isFieldTouched 和 getFieldError 的结果
- shouldUpdate 加上 dependencies 可以更新 isFieldValidating
- 单独使用 dependencies 好像没有办法更新 isFieldTouched  isFieldValidating getFieldError 等状态

[![Edit antd reproduction template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5f7tu?fontsize=14&hidenavigation=1&theme=dark)

**Comment by zombieJ** [comment]
`shouldUpdate` 用于处理整个表单的数据更新，如果值变了，通过它来确定是否需要更新。
`dependencies` 顾名思义是用于处理依赖关系的，你的场景里上游不仅仅是数据变化，同时校验也发生了变化，因而它需要将依赖进行通知更新。
