### ISSUE TITLE
Modal组件能否增加个afterOpen回调

### ISSUE THREAD

**Issue by mkanako** [ant-design/ant-design#20997]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前，我modal打开后，会有一个ajax请求，请求会带个全屏loading动画，而modal打开也有一个动画，这样2个动画会同时进行，视觉效果很不好，所以如果能有个afterOpen回调在modal动画完成后，再进行我的操作，就完美了

总结就是如果在打开modal后进行一些有动画效果的操作，那么这个afterOpen就很有帮助

### What does the proposed API look like?
类似afterClose

**Comment by junxiongchu** [comment]
这个我理解请求是不是可以在Modal下children组件的生命周期中自己处理，同时开启destroyOnClose

**Comment by zombieJ** [comment]
按你的需求感觉这不是 Modal 必须的一个 API，可以自己处理一下 or HOC 包一个 Modal。

```
[visible, setVisible] = React.useState(false);

function triggerVisible() {
  setVisible(!visible);
  if (visible) {
    setTimeout(() => {
      // ...
    }, 300);
  }
}
```

**Comment by mkanako** [comment]
@zombieJ 关键在于我需要在modal打开动画完成后执行我的代码，像你这样setTimeout为啥是300呢,200行不行500行不行，不太靠谱啊

**Comment by yoyo837** [comment]
@zombieJ watch `visible` 由falsely 变为 truly 吧。

**Comment by mkanako** [comment]
@yoyo837  watch visible 没用啊，visible只是表示modal是否可见，visible为truly之后modal的打开动画才开始执行

**Comment by yoyo837** [comment]
那 setTimeout 没错了，300应该是动画时长。你找找css

**Comment by mkanako** [comment]
@yoyo837 我知道如果css动画时长300,那么setTimeout 300也不是不可以
只是这样其实不完全靠谱，不完美，明明有更完美的做法。。。不过这个问题说来也行不大，我有点强迫症😬

**Comment by yoyo837** [comment]
> 按你的需求感觉这不是 Modal 必须的一个 API，可以自己处理一下 or HOC 包一个 Modal。

那没有，这个已经回答你了。

**Comment by mkanako** [comment]
@yoyo837  好吧，刚看了代码，modal组件依赖了 https://github.com/react-component/m-dialog ，而这个组件并未提供afterOpen选项，还得更新这个组件，才能让modal提供这个api,动作有点大必要性又没那么强。。。理解😅

**Comment by tangxininjava** [comment]
3.8增加了吗？ 还是打死就是不加这个afterOpen回调
