### ISSUE TITLE
RangePicker中的defaultPickerValue无法正确更新

### ISSUE THREAD

**Issue by Chocolatl** [ant-design/ant-design#21001]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/chocolatl/pen/LYEgaKN](https://codepen.io/chocolatl/pen/LYEgaKN)

### Steps to reproduce
等一秒

### What is expected?
DatePicker.RangePicker的defaultPickerValue随着状态改变

### What is actually happening?
DatePicker的defaultPickerValue正确更新了，但DatePicker.RangePicker没有

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | Win10 |
| Browser | Chrome78 |

**Comment by Chocolatl** [comment]
重新试了一遍，貌似DatePicker.RangePicker的defaultPickerValue从来就不会生效

**Comment by zombieJ** [comment]
`defaultPickerValue` 用于设置默认打开的面板，比如你的例子里设置了 2019-12-11，打开的 RangePicker 面板就是 2019-12 的：
<img width="563" alt="截屏2020-01-19下午2 45 35" src="https://user-images.githubusercontent.com/5378891/72676277-61647600-3aca-11ea-9503-756936eff030.png">

反之则是当前的：
<img width="568" alt="截屏2020-01-19下午2 45 25" src="https://user-images.githubusercontent.com/5378891/72676282-6aedde00-3aca-11ea-9f15-99136873dbe3.png">

**Comment by Chocolatl** [comment]
@zombieJ 
![image](https://user-images.githubusercontent.com/22774786/72676614-219f8d80-3ace-11ea-981d-474bd5b0e2d2.png)

DatePicker.RangePicker没有响应更新，但是DatePicker的正确更新了面板日期

**Comment by zombieJ** [comment]
`DatePicker` 应该是有问题的，default 属性不应该受控。不过 `rc-calendar` 底层代码比较老旧，v3 版本应该不会特意去修免得引发额外的 bug。

**Comment by Chocolatl** [comment]
@zombieJ  这个default和受控非受控应该没什么关系，只是命名用了default而已。如果的确是非受控那应该同时提供一个受控的参数。我现在有个需求是需要动态切换时区，目前由于defaultPickerValue挂载后不会变化，导致默认面板的今天会是错误的

希望v4能修复这个问题吧

**Comment by JackDan9** [comment]
这个bug修复了吗？

**Comment by nqsjd178559344** [comment]
22年12月挖坟，这个bug修了吗
