### ISSUE TITLE
Antd4.0 table组件文档关于scroll属性的定义与依赖的rc-table中的定义不一致

### ISSUE THREAD

**Issue by w91** [ant-design/ant-design#21008]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/table-cn/#scroll](https://next.ant.design/components/table-cn/#scroll)

### scroll
  x	设置横向滚动，也可用于指定滚动区域的宽和高，可以设置为像素值，百分比，true 和 'max-content'	   `number | true`
  y	设置纵向滚动，也可用于指定滚动区域的宽和高，可以设置为像素值，百分比，true 和 'max-content'	   `number | true`

## rc-table中scroll定义y只能是number：
```
export interface TableProps<RecordType = unknown> extends LegacyExpandableProps<RecordType> {
    scroll?: {
        x?: number | true | string;
        y?: number;
    };
}
```

### What is expected?
文档与实际定义一致

### What is actually happening?
文档与实际定义不一致

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | mac 10.14.6 |
| Browser | chrome |

**Comment by yoyo837** [comment]
这属于再封装吧。

**Comment by w91** [comment]
属性定义是从rc-table那里继承过来的
![image](https://user-images.githubusercontent.com/2599455/72677417-1ac94880-3ad7-11ea-9936-777a642329d4.png)

**Comment by zombieJ** [comment]
看了一下，应该是文档更新失误把 x 的定义复制到 y 上了。我去更新一下。

https://github.com/ant-design/ant-design/commit/90a77c0f02790e9c220333af346efd38c1dabaf2#diff-08c5536cd53338ac98747edd84d7e5f1L87
