### ISSUE TITLE
在 Modal 弹出的动画阶段内，在其内部渲染 Table 产生样式异常

### ISSUE THREAD

**Issue by uni-zheng** [ant-design/ant-design#21002]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/unizheng/pen/QWwZPpY?editors=0010](https://codepen.io/unizheng/pen/QWwZPpY?editors=0010)

### Steps to reproduce
打开 Modal

### What is expected?
Table 样式显示正常

### What is actually happening?
Table 样式显示异常

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | latest |
| System | max os 10.15.2 |
| Browser | safari 13.0.4 |

---
当在 Modal 中插入一个 Table 组件。

Table 组件满足了
1. row 的 cell 中有超过一行的文字或内容
2. 存在 fixed 列，且 fixed 列的 cell 中仅一行内容
3. dataSource 值的更新在 Modal 打开的动画时间内

会产生 fixed 列 cell 高度小于 row 高度

**Comment by uni-zheng** [comment]
<img width="543" alt="image" src="https://user-images.githubusercontent.com/9986421/72674648-0889e300-3ab4-11ea-8c30-6ee7030409a6.png">

**Comment by zombieJ** [comment]
Duplicate of #9900

**Comment by uni-zheng** [comment]
@zombieJ  明显不是相同问题。

**Comment by uni-zheng** [comment]
@zombieJ 我很明确的描述了问题

Table 组件满足了

1. row 的 cell 中有超过一行的文字或内容
2. 存在 fixed 列，且 fixed 列的 cell 中仅一行内容
3. dataSource 值的更新在 Modal 打开的动画时间内

会产生 fixed 列 cell 高度小于 row 高度

最重要的在于第3步，在 Modal 动画时间内弹出的 Table 会有错误的高度计算。

在 Table 样式异常的情况下，任意操作引起了组件重新 render 就会使样式正常。

和 #9900 不是一个问题

**Comment by zombieJ** [comment]
谢谢提醒，是 #14859。连错了。

**Comment by Jsmond2016** [comment]
遇到同样的问题，技术上无法实现，只能和产品更改需求了，【在不锁列的情况下】，每个 column 都设定固定宽度，可以实现需求，截图如下：

![011](https://user-images.githubusercontent.com/25282180/76157820-5bddf080-6149-11ea-9e0b-83a0a6978559.png)
