### ISSUE TITLE
关于TABLE中，字段的默认值问题

### ISSUE THREAD

**Issue by Montage-LSM** [ant-design/ant-design#2101]
建议在table指定的列中，可以设置默认值这个东西，这样不用用户判断，有一个defaultValue的选项。

**Comment by afc163** [comment]
根本看不懂。

**Comment by Montage-LSM** [comment]
table中不是有个选项 【columns】 是指定Column列名，里面设置title=>列名，dataIndex,key 的多维数组么。希望在同级别的下面，增加一个选项，defaultValue选项，用来做默认值，如果这个列没有值，或者说返回的值是undefind,null这类情况的时候，可以设置一个默认值，而不用去render中去判断了。当然，如果有render的话，default就不去判断了。

**Comment by afc163** [comment]
```jsx
render(text) {
  return text || '默认值'
}
```

这样就可以了，单独加 API 太重了。
