### ISSUE TITLE
Cannot clear AutoComplete value in v4

### ISSUE THREAD

**Issue by samit4me** [ant-design/ant-design#21018]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serverless-cdn-56dwv)

### Steps to reproduce
Typing text into the bottom input (control mode).

### What is expected?
Input text should not appear in the input.

### What is actually happening?
Input text is appearing in the input.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 79 |

---
This is a contrived example, but in our app, we are clearing the text after performing a search, which is not possible in v4.

Contrived examples:
- Version 3 working (https://codesandbox.io/s/cranky-pine-lxir3).
- Version 4 not working (https://codesandbox.io/s/serverless-cdn-56dwv)

**Comment by samit4me** [comment]
After further investigation, I've managed to get it working by passing the value to the props `value` and `searchValue`. 

e.g.
`<AutoComplete value={value} searchValue={value} {...otherProps} />`

_NOTE: you must pass both props as either one on there own don't work._

The `<AutoComplete />` component is using the `<Select />` component from `rc-select` internally and if you look at the [documentation](https://github.com/react-component/select#select-props) it does not specify the `searchValue` prop, but looking at the [source code](https://github.com/react-component/select/blob/f3f8c42a3ac71e580e3c1e18c39328fc55888c30/src/generate.tsx#L62-L183) you can see it does accept the `searchValue` prop.

To see it working, look at this example:
https://codesandbox.io/s/quirky-ives-zthwz

Not sure how to best address this issue, but either the documentation could be updated or antd could pass the `searchValue` prop???

**Comment by yoyo837** [comment]
Maybe duplicated of #20979

**Comment by samit4me** [comment]
Yeah possibly, but it should also clear with an empty string also. It looks like the fix merged will only work when value is `undefined`.

**Comment by zombieJ** [comment]
AutoComplete reuse the `searchValue` but it should use `value` instead. #20979 may not work since `searchValue` not clean up in AutoComplete mode.
