### ISSUE TITLE
能不能提供一个表单里有upload上传图片的小Demo，点击表单提交按钮，拿到图片的base64

### ISSUE THREAD

**Issue by Jidahan** [ant-design/ant-design#21011]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能不能提供一个表单里有upload上传图片的小Demo，点击表单提交按钮，拿到图片的base64。
希望点击提交按钮，图片和其他输入框的内容可以同时拿到

### What does the proposed API look like?
上传图片最好是多图上传，拿到的值 期望是一个数组内包着多个json，一个json表示一个图片的base64格式

**Comment by yoyo837** [comment]
使用`Upload`的`customRequest`, 用`FileReader`读取。

**Comment by zombieJ** [comment]
有兴趣可以自行 PR 加一个 codesandbox 示例，这个是使用问题，就不在 issue 里追踪了。
