### ISSUE TITLE
How to create different triggers for different form item rules

### ISSUE THREAD

**Issue by jimmy-e** [ant-design/ant-design#21019]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-working-template-input-u8y08?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
* Open up the code sandbox in the link provided.
* If you immediately click the 'register' button you get the message 'Please input your E-mail!'
* If you start typing, you are then given the message 'This is not valid E-mail!'

### What is expected?
* User clicks the 'register button' and you get the message 'Please input your E-mail!'
* User starts typing in the input field and all messages go away.
* User clicks on the register button. If what has been entered is an invalid email address, the user will be notified via message again.

### What is actually happening?
The user is notified of the email validation as they type.

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12 |
| System | mac OSX |
| Browser | Chrome |

**Comment by zombieJ** [comment]
v4 support set `validateTrigger` by rule level. v3 may not support this.

ref: https://next.ant.design/components/form/#header
