### ISSUE TITLE
RangePicker使用showTime.defaultValue时无法粘贴时间到输入框

### ISSUE THREAD

**Issue by Pengjee** [ant-design/ant-design#21012]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
* 复制时间格式 '2020-01-17 14:36:06'
* 粘贴到时间范围选择器的第一个输入框
* 粘贴时间被初始化时间格式 2020-01-17 00:00:00
```javascript
<RangePicker
      value={dateValue}
      format="YYYY-MM-DD HH:mm:ss"
      showTime={{
        defaultValue: [moment('00:00:00', 'HH:mm:ss'), moment('23:59:59', 'HH:mm:ss')]
      }}
      onChange={(time) => {
        setDateValue(time)
      }}
      onCalendarChange={(time) => {
        const [startTime, endTime] = time
        setDateValue(time)
      }}
/>
```

### What is expected?
RangePicker使用showTime.defaultValue时能够直接粘贴时间到输入框

### What is actually happening?
无法粘贴

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | react |
| System | macos |
| Browser | Chrome 79.0.3945.117 |

**Comment by xiaohuoni** [comment]
![image](https://user-images.githubusercontent.com/11746742/72788205-68c38500-3c6c-11ea-84f6-66d54031e0f9.png)
我这里好像可以

**Comment by Pengjee** [comment]
> ![image](https://user-images.githubusercontent.com/11746742/72788205-68c38500-3c6c-11ea-84f6-66d54031e0f9.png)
> 我这里好像可以

![image](https://user-images.githubusercontent.com/30884882/72789208-403c8a80-3c6e-11ea-8745-d56a4ef846d8.png)
这写过后，渲染出来的**时间范围选择器**，如果直接粘贴2020-01-17 14:36:06这个到输入框中，会自动帮你重置为2020-01-17 00:00:00

**Comment by Pengjee** [comment]
![image](https://user-images.githubusercontent.com/30884882/72789208-403c8a80-3c6e-11ea-8745-d56a4ef846d8.png)
这样写过后，渲染出来的**时间范围选择器**，如果直接粘贴2020-01-17 14:36:06这个到输入框中，会自动帮你重置为2020-01-17 00:00:00

**Comment by afc163** [comment]
`showTime.defaultValue` 相当于初始化了内建 TimePicker 的默认状态，目前的设计不会根据具体的 value 去重置和修改这个状态，表现出来就相当于写死了时间为 00:00:00 。
