### ISSUE TITLE
Form.useForm不在hooks模式下使用

### ISSUE THREAD

**Issue by WinterWoods** [ant-design/ant-design#21014]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在正常class模式下,无法使用Form.useForm.

### What does the proposed API look like?
希望class模式也能正常使用.

**Comment by afc163** [comment]
hooks 在 class 模式下是无法使用的，这是 React 的限制。

**Comment by exvu** [comment]
@afc163 我试图尝试修饰器使用hooks 传递给class都不行吗
![image](https://user-images.githubusercontent.com/25115931/75125432-0e489900-56f0-11ea-8e4e-6bdd951c4f7b.png)

![image](https://user-images.githubusercontent.com/25115931/75125439-14d71080-56f0-11ea-9ee0-8ee247ee39e4.png)

![image](https://user-images.githubusercontent.com/25115931/75125441-1c96b500-56f0-11ea-9fa3-0cac757dfbc3.png)

**Comment by exvu** [comment]
@afc 
### 已解决此问题，位置放错了
![image](https://user-images.githubusercontent.com/25115931/75153536-98bbe780-5746-11ea-821c-32b34ca754bf.png)

**Comment by liuyun521** [comment]
> @afc
> 
> ### 已解决此问题，位置放错了
> ![image](https://user-images.githubusercontent.com/25115931/75153536-98bbe780-5746-11ea-821c-32b34ca754bf.png)

遇到同样问题，你这个是怎么解决的

**Comment by ZhaoXinNian** [comment]
> > @afc
> > ### 已解决此问题，位置放错了
> > ![image](https://user-images.githubusercontent.com/25115931/75153536-98bbe780-5746-11ea-821c-32b34ca754bf.png)
> 
> 遇到同样问题，你这个是怎么解决的

也遇到同样问题，请问怎么解决的？
