### ISSUE TITLE
官网的在线换肤方案是怎么实现的？

### ISSUE THREAD

**Issue by Jackieboy29** [ant-design/ant-design#21021]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
给用户提供在线更换主题的体验

### What does the proposed API look like?
有无具体实现方案
![image](https://user-images.githubusercontent.com/21135807/72693972-2c116400-3b6e-11ea-893b-291c27962b44.png)

**Comment by zombieJ** [comment]
通过[这个脚本](https://github.com/ant-design/ant-design/blob/master/scripts/generateColorLess.js) 达到换肤效果，但是这只是给开发者预览使用。没有提供直接的动态换肤功能。
