### ISSUE TITLE
Input.Group 内嵌Input / InputNumber 组件报错

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#21028]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-snow-uz5l7)

### Steps to reproduce
刷新页面，控制台报错

具体报错信息如下：

![image](https://user-images.githubusercontent.com/8147202/72713687-7283b480-3ba8-11ea-94db-07d0878037b3.png)

### What is expected?
Input.Group 内嵌Input / InputNumber 组件，控制台不报错

### What is actually happening?
Input.Group 内嵌Input / InputNumber 组件，控制台报错

具体错误信息如下：

![image](https://user-images.githubusercontent.com/8147202/72713687-7283b480-3ba8-11ea-94db-07d0878037b3.png)

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | win 10 |
| Browser | Chrome 78.0.3904.70 |

**Comment by zombieJ** [comment]
你的字段绑定的不对，InputGroup 本身没有 `value` 和 `onChange`。需要自定义个组件来实现你的需求。

ref: https://ant.design/components/form-cn/#components-form-demo-customized-form-controls
