### ISSUE TITLE
table虚拟滚动按照文档上的做的话，很多table原本的功能都不能使用了，比如展开，多选

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#21022]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以使用table原本的功能，在此基础上加虚拟滚动

### What does the proposed API look like?
暴露一个tablerow组件，或者HOC？

**Comment by yoyo837** [comment]
“很多”是哪些？最好是提供复现按bug 反馈。

**Comment by zombieJ** [comment]
demo 只是展示自定义 body 的例子，虚拟滚动是其中一个实现。如果想要固定列和展开，可以帮忙完善一下这个例子。

Merge into #20339

**Comment by vronifuchsberger** [comment]
I think it still would be very helpful to mention in the documentation that most of the table functions wont' be working anymore
