### ISSUE TITLE
在 Modal 弹出的动画阶段内，在其内部渲染 Table 产生样式异常，并没有使用 expendedRowRender! 

### ISSUE THREAD

**Issue by uni-zheng** [ant-design/ant-design#21025]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/unizheng/pen/QWwZPpY?editors=0010](https://codepen.io/unizheng/pen/QWwZPpY?editors=0010)

### Steps to reproduce
打开 Modal

### What is expected?
Table 样式显示正常

### What is actually happening?
Table 样式显示异常

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | latest |
| System | max os 10.15.2 |
| Browser | safari 13.0.4 |

---
当在 Modal 中插入一个 Table 组件。

Table 组件满足了

1. row 的 cell 中有超过一行的文字或内容
2. 存在 fixed 列，且 fixed 列的 cell 中仅一行内容
3. dataSource 值的更新在 Modal 打开的动画时间内

会产生 fixed 列 cell 高度小于 row 高度

最重要的在于第3步，在 Modal 动画时间内弹出的 Table 会有错误的高度计算。

在 Table 样式异常的情况下，任意操作引起了组件重新 render 就会使样式正常。

和 #9900 不是一个问题 这里没有使用 Expanded row!! 没有!!

**Comment by zombieJ** [comment]
Duplicate of #14859

**Comment by zombieJ** [comment]
v3 用的多 Table 实现行高同步，会有一些 edge case 覆盖不到。你可以试试 v4 的 Table，不用兼容老版 IE，就没有这个问题了。

ref：https://zhuanlan.zhihu.com/p/102037418
