### ISSUE TITLE
run build後 打開localhost:5000就空白了(after run build and .serve ./dist, at localhost:5000 is empty page)

### ISSUE THREAD

**Issue by JonathanSum** [ant-design/ant-design#21038]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/JonathanSum/JonathanSum.github.io](https://github.com/JonathanSum/JonathanSum.github.io)

### Steps to reproduce
serve ./dist

### What is expected?
不是空白,not empty

### What is actually happening?
run build後 打開localhost:5000就空白了(after run build and .serve ./dist, at localhost:5000 is empty page)

| Environment | Info |
|---|---|
| antd | undefined |
| React | newest |
| System | W10 |
| Browser | Chrome |

---
Here is my code.
https://github.com/JonathanSum/blog
https://github.com/JonathanSum/JonathanSum.github.io
兩個repo都一樣,只是config.js set了blog,而另外一個沒有

![image](https://user-images.githubusercontent.com/21982975/72752779-f40f1e80-3b77-11ea-89c6-c8c43d56ddb3.png)

**Comment by zombieJ** [comment]
Close since not an antd issue.

**Comment by JonathanSum** [comment]
@zombieJ 這個好像是老問題來的

**Comment by yoyo837** [comment]
来个最小化的复现。
