### ISSUE TITLE
TypeError: Cannot read property '__ANT_BUTTON' of undefined     at Tooltip.getDisabledCompatibleChildren

### ISSUE THREAD

**Issue by LaurenceM10** [ant-design/ant-design#21037]
Exception from Tracker recompute function:
TypeError: Cannot read property '__ANT_BUTTON' of undefined
    at Tooltip.getDisabledCompatibleChildren 
    at Tooltip.render
    at finishClassComponent 
    at updateClassComponent 
    at beginWork$1 
    at HTMLUnknownElement.callCallback
    at Object.invokeGuardedCallbackDev (
    at invokeGuardedCallback 
    at beginWork$$1
    at performUnitOfWork
    at workLoopSync
    at renderRoot
    at runRootCallback
    at unstable_runWithPriority
    at runWithPriority$2 

This error does not occur to me locally. But when it runs on the server in AWS, the error appears and my application crashes.

My version `" antd ":" ^ 3.10.8 ",` and my node version is v8.12.0

The code is this:
```
const validationMessage = (
  <div>
    <div style={{ padding: "3px", minWidth: "450px" }}> 
        My text message
    </div>
  </div>
);

<Tooltip
   placement="left"
   title={validationMessage}>
         <Input.Password
             name="password"
             id="password"
             placeholder="New Password"
          />
</Tooltip>
```

**Comment by afc163** [comment]
回复一下，蚂蚁内部 Bigfish 框架中配合 antd 4.0 时，如下代码：

```jsx
import { Icon } from '@alipay/bigfish/antd';

<Icon type="xxx" />;
```

这段代码不会渲染出图标，因为 antd 4.0 中 Icon 已经移到 `@ant-design/icons` 这个包里了。

但是这段代码在 dev 时不会报错，构建也不会出错，但是构建到生产环境后，浏览器打开时会报这个 issue 里的问题：`TypeError: Cannot read property '__ANT_BUTTON' of undefined`。

解决方式是改为 antd 4.0 的图标引用方式：

```diff
- import { Icon } from '@alipay/bigfish/antd';
+ import { SearchOutlined } from '@ant-design/icons';
```

---

cc @ycjcl868

后续 umi 和 Bigfish 框架会修改，让本地开发时也出错，及时提示用户。
