### ISSUE TITLE
prefixCls removing default styles

### ISSUE THREAD

**Issue by jyash97** [ant-design/ant-design#21036]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-hertz-k2ps8)

### Steps to reproduce
- Add custom `prefixCls` to `ConfigProvider`

### What is expected?
Expected to change the default class prefix from `ant` to the prefix passed with all the default styles intact.

### What is actually happening?
Default styles are not working.

| Environment | Info |
|---|---|
| antd | 3.18.2 |
| React | 16.12.0 |
| System | macOS Catalina: 10.15.1 |
| Browser | Chrome: 79.0.3945.130 |

---
I think the docs are missing on how to use the `prefixCls`. Any help is appreciated. Thanks

@afc163 @zombieJ  Is this the correct way to use `prefixCls` ?

**Comment by yoyo837** [comment]
I think when you use `prefixCls`, it means that you want to completely discard the styles provided by `antd` and provide a copy yourself.

**Comment by jyash97** [comment]
Hey @yoyo837 thanks for clarifying the usage. Will it make sense to add a note about this on docs?

**Comment by yoyo837** [comment]
Yes, that would be very useful. Welcome to send a PR to make it.
