### ISSUE TITLE
Form getFieldProps 'nodeName' conflict with react lib

### ISSUE THREAD

**Issue by kamushin** [ant-design/ant-design#2103]
## What you did

use 'nodeName' as a field props of Form
```
      <FormItem >
        <Input
          {...getFieldProps("nodeName")}
        />
      </FormItem>

```

## What actually happened

conflict with react lib 
```
function shouldUseChangeEvent(elem) {
  var nodeName = elem.nodeName && elem.nodeName.toLowerCase();
  return nodeName === 'select' || nodeName === 'input' && elem.type === 'file';
}

```

## Environment Information

-  antd(0.12.x):
- react(0.14.x)
-  OSX 10.11.0
-  Chrome  50.0.2661.102 (64-bit)

**Comment by kamushin** [comment]
Maybe add a transition of user props. eg add "__" before react actually get it.

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
Close for no response for a long time.
