### ISSUE TITLE
RangePicker placeholder display weird

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#21034]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-cerf-3yip2)

### Steps to reproduce
/

### What is expected?
normal

### What is actually happening?
weird

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.9 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by zombieJ** [comment]
RangePicker accept array as `placeholder`:
<img width="415" alt="截屏2020-01-21上午11 09 26" src="https://user-images.githubusercontent.com/5378891/72772320-8974e600-3c3e-11ea-95e8-aec62c485913.png">

**Comment by shaodahong** [comment]
But RangePicker does not display single string placeholder in 3.0

**Comment by zombieJ** [comment]
No need to handle this since is not a correct usage.
