### ISSUE TITLE
Components with Dropdown Flash in IE11

### ISSUE THREAD

**Issue by notamazing** [ant-design/ant-design#21039]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/notamazing/test-ant-select](https://github.com/notamazing/test-ant-select)

### Steps to reproduce
Run `yarn` to install all dependencies
Run `yarn dev` to run the application
Click on the select or the tooltip component in Internet Explorer 11

### What is expected?
The dropdown of the select/tooltip should render as it does in other browsers

### What is actually happening?
The dropdowns of each component flash when the parent is selected

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Internet Explorer 11 |

---
next.ant.design crashes on IE11 so it's difficult to know whether this is an issue everywhere or just in our project. The reproduction project uses Next.js as a framework

**Comment by zombieJ** [comment]
<img width="324" alt="截屏2020-01-21上午11 05 04" src="https://user-images.githubusercontent.com/5378891/72772049-e45a0d80-3c3d-11ea-8684-2cecfcbe16e6.png">

**Comment by notamazing** [comment]
I updated the config file so the 500 error showing up after running `yarn build` `yarn start` should be resolved!

**Comment by notamazing** [comment]
Hi @zombieJ @ant-design-bot, the error is resolved. Any updates on whether this will be resolved in a future release? Thanks!

**Comment by zombieJ** [comment]
Hi @notamazing, could you help to update the gif for snapshot also? Since currently is in spring festival, I need delay some days for finding a window PC.

**Comment by notamazing** [comment]
@zombieJ Thanks for the update! Here's a gif of the issue
![antScreen](https://user-images.githubusercontent.com/21027446/73080681-3dbb7a00-3e94-11ea-812a-c1665a00992b.gif)

**Comment by dtkelch** [comment]
@zombieJ are there any plans to address this? I'm running into this as well with antd@4.0.0-rc.3

It's a pretty significant rendering issue on IE 11. On our application, it will cause the whole page to flash / re-render. It seems to be more noticeable on larger applications.

![IE 11 re-rendering](https://github.com/dtkelch/ant-design-ie11-bug/blob/master/IE11Bug.gif?raw=true)

**Comment by mullwaden** [comment]
We are also having the same issue in ie11. Applies to both popups and drop-downs. I would say the issues is quite significant

**Comment by zombieJ** [comment]
Hi all, is that Select in the web only happen or other component also will?

**Comment by dtkelch** [comment]
@zombieJ based on my testing, it's happening to all components with a dropdown effect - such as a `Select`, `Popover`, `AutoComplete`.

**Comment by zombieJ** [comment]
@dtkelch,
Thanks for testing. It may affect by `rc-trigger` which should deep dig.

**Comment by ywy94ywy** [comment]
为什么antd的官网在IE11打开这么的卡啊，随便点一下datapicker组件，浏览器就卡着不动了

**Comment by xue1206** [comment]
请问一下 这个问题大概什么时候修复好啊

**Comment by xiaoyanzheng** [comment]
什么时候修复呀

**Comment by rashiq-ahmd** [comment]
Is there any update on this?

**Comment by xiaoyanzheng** [comment]
> @dtkelch,
> Thanks for testing. It may affect by `rc-trigger` which should deep dig.

antd@4.2.4 版本还这个问题仍然存在

**Comment by asha-simon** [comment]
Any updates on this issue ?

**Comment by afc163** [comment]
@asha-simon @xiaoyanzheng @rashiq-ahmd 

PR welcome~

**Comment by Sivan-Wu** [comment]
Has the problem been solved?

**Comment by allenYetu211** [comment]
![image](https://user-images.githubusercontent.com/17957079/82824569-280a9f80-9edc-11ea-89aa-71eb5d9881a5.png)
一个临时的很糟糕的解决方式，可以针对IE11做特殊处理。

修改animation rcDropdownSlideDownIn

**Comment by xiaoyanzheng** [comment]
> ![image](https://user-images.githubusercontent.com/17957079/82824569-280a9f80-9edc-11ea-89aa-71eb5d9881a5.png)
> 一个临时的很糟糕的解决方式，可以针对IE11做特殊处理。
> 
> 修改animation rcDropdownSlideDownIn

本地按照你的思路改了下，覆盖了antd里面的动画，dropdown、autocomplete、datepick都ok了
@keyframes slAntSlideUpIn {
  0% {
    transform: scaleY(0.8);
    transform-origin: 0% 0%;
    opacity: 0;
  }
  110% {
    transform: scaleY(1);
    transform-origin: 0% 0%;
    opacity: 1;
  }
}
.slide-up-enter.slide-up-enter-active,
.slide-up-appear.slide-up-appear-active {
  animation-name: slAntSlideUpIn;
  animation-play-state: running;
}

@keyframes slAntSlideDownIn {
  0% {
    transform: scaleY(0.8);
    transform-origin: 100% 100%;
    opacity: 0;
  }
  110% {
    transform: scaleY(1);
    transform-origin: 100% 100%;
    opacity: 1;
  }
}

.slide-down-enter.slide-down-enter-active,
.slide-down-appear.slide-down-appear-active {
  animation-name: slAntSlideDownIn;
  animation-play-state: running;
}

.ant-select-dropdown.slide-up-enter.slide-up-enter-active.ant-select-dropdown-placement-bottomLeft,
.ant-select-dropdown.slide-up-appear.slide-up-appear-active.ant-select-dropdown-placement-bottomLeft {
  animation-name: slAntSlideUpIn;
}

**Comment by saneksa** [comment]
Is there any update on this?

**Comment by YinRenjie1993** [comment]
有比较完美的解决方案吗

**Comment by xrkffgg** [comment]
@xiaoyanzheng 
IE: 11.959.18362.0 我用你的方法，没生效。

**Comment by SerZubkov** [comment]
very sad from this problem

**Comment by xrkffgg** [comment]
@allenYetu211 @xiaoyanzheng 
what's your IE version?

**Comment by xrkffgg** [comment]
> Dropdown doesn't even show up

Maybe it's because I'm using the Demo from the official website, so I should create a new project to import components.

**Comment by zombieJ** [comment]
@xrkffgg 
Try to use umi to create IE11 compatible repo. It will help to create polyfill of IE

**Comment by xiaoyanzheng** [comment]
> @allenYetu211 @xiaoyanzheng
> what's your IE version?

ie 11

**Comment by yoyo837** [comment]
> > @allenYetu211 @xiaoyanzheng
> > what's your IE version?
> 
> ie 11

应该是想问具体的小版本号吧

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/88178970-c22d6080-cc5d-11ea-9258-66eb3ea8a574.png)

@zombieJ I feel very bad about IE11.

**Comment by 07akioni** [comment]
> ![image](https://user-images.githubusercontent.com/29775873/88178970-c22d6080-cc5d-11ea-9258-66eb3ea8a574.png)
> 
> @zombieJ I feel very bad about IE11.

苦行僧既视感，为了一些虚无缥缈的理由

**Comment by 532758463** [comment]
> > ![image](https://user-images.githubusercontent.com/17957079/82824569-280a9f80-9edc-11ea-89aa-71eb5d9881a5.png)
> > 一个临时的很糟糕的解决方式，可以针对IE11做特殊处理。
> > 修改animation rcDropdownSlideDownIn
> 
> 本地按照你的思路改了下，覆盖了antd里面的动画，dropdown、autocomplete、datepick都ok了
> @Keyframes slAntSlideUpIn {
> 0% {
> transform: scaleY(0.8);
> transform-origin: 0% 0%;
> opacity: 0;
> }
> 110% {
> transform: scaleY(1);
> transform-origin: 0% 0%;
> opacity: 1;
> }
> }
> .slide-up-enter.slide-up-enter-active,
> .slide-up-appear.slide-up-appear-active {
> animation-name: slAntSlideUpIn;
> animation-play-state: running;
> }
> 
> @Keyframes slAntSlideDownIn {
> 0% {
> transform: scaleY(0.8);
> transform-origin: 100% 100%;
> opacity: 0;
> }
> 110% {
> transform: scaleY(1);
> transform-origin: 100% 100%;
> opacity: 1;
> }
> }
> 
> .slide-down-enter.slide-down-enter-active,
> .slide-down-appear.slide-down-appear-active {
> animation-name: slAntSlideDownIn;
> animation-play-state: running;
> }
> 
> .ant-select-dropdown.slide-up-enter.slide-up-enter-active.ant-select-dropdown-placement-bottomLeft,
> .ant-select-dropdown.slide-up-appear.slide-up-appear-active.ant-select-dropdown-placement-bottomLeft {
> animation-name: slAntSlideUpIn;
> }

我试着用你这方法,发现没有解决掉,antd版本4.2.5

**Comment by sconstantinides** [comment]
This would be great to have fixed 🙏

A temporary solution is to set the animation duration to be instant in only IE:

```scss
@media only screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .ant-dropdown,
    .ant-select-dropdown,
    .ant-picker-dropdown {
        animation-duration: 0s;
    }
}
```

**Comment by zhdarry** [comment]
Has this problem been solved??

**Comment by xrkffgg** [comment]
@zhdarry You can try the solutions upper.

**Comment by zhdarry** [comment]
> @zhdarry You can try the solutions upper.

I have tried,It does not work.
I used components with Layout + Select, when I add the <body> a fixed height,such as 1200px,It seems worked.
When the body's height is 100%,and the children element's height is higher than body's,this problem appear

**Comment by fygethub** [comment]
> > @zhdarry You can try the solutions upper.
> 
> I have tried,It does not work.
> I used components with Layout + Select, when I add the a fixed height,such as 1200px,It seems worked.
> When the body's height is 100%,and the children element's height is higher than body's,this problem appear

Yes I have the same issues ， when the warp container has scroll bar it will absolute happen

**Comment by JdaieLin** [comment]
> > > @zhdarry You can try the solutions upper.
> > 
> > 
> > I have tried,It does not work.
> > I used components with Layout + Select, when I add the a fixed height,such as 1200px,It seems worked.
> > When the body's height is 100%,and the children element's height is higher than body's,this problem appear
> 
> Yes I have the same issues ， when the warp container has scroll bar it will absolute happen

same issue.
I solved this by appending a pseudo element to the scroll container, where dropdown menus will mounted on:

```
.scroll-container-class:after{
  content: '';
  position: fixed;
  display: block;
}
```

**Comment by xiaoyanzheng** [comment]
> @allenYetu211 @xiaoyanzheng
> what's your IE version?

IE11.1550.17134.0

**Comment by hy08** [comment]
In ie11 environment，When the ancestor element has a scroll bar, the display of the select component drop-down box or other pop-up type components will cause the page to re-render

**Comment by tangguodada** [comment]
> > > > @zhdarry You can try the solutions upper.
> > > 
> > > 
> > > I have tried,It does not work.
> > > I used components with Layout + Select, when I add the a fixed height,such as 1200px,It seems worked.
> > > When the body's height is 100%,and the children element's height is higher than body's,this problem appear
> > 
> > 
> > Yes I have the same issues ， when the warp container has scroll bar it will absolute happen
> 
> same issue.
> I solved this by appending a pseudo element to the scroll container, where dropdown menus will be mounted on:
> 
> ```
> .scroll-container-class:after{
>   content: '';
>   position: fixed;
>   display: block;
> }
> ```

unsolved

**Comment by pig800509** [comment]
any solution here?
I tried all solution above, but not working

**Comment by realEago** [comment]
help~ help us~

**Comment by realEago** [comment]
plz help, it's already 8 months...

**Comment by tangguodada** [comment]
I solved this buy remove CSS："overflow auto" from [html, body, #root].

**Comment by tangguodada** [comment]
> plz help, it's already 8 months...

Try the following

**Comment by realEago** [comment]
> I solved this by remove CSS："overflow auto" from [html, body, #root].

no use

**Comment by libyasdf** [comment]
Select组件 IE11 加getPopupContainer={trigger => trigger.parentNode}后，导致整个浏览器闪烁。

**Comment by lidaguang1989** [comment]
```
<div class="blink-class">
  <Select
	defaultValue="lucy"
	style={{ width: 120 }}
	getPopupContainer={(trigger) => trigger.parentNode}
  >
	<Option value="jack">Jack</Option>
	<Option value="lucy">Lucy</Option>
	<Option value="yiminghe">yiminghe</Option>
  </Select>
</div>
```
然后对父组件添加伪元素样式：
```
.blink-class:after{
  content: '';
  position: fixed;
  display: block;
}
```

**Comment by 0xAC7** [comment]
结合了以上两种解决思路，是好用的。
对于 Select 组件来说，其自身弹出层可能会有滚动条，所以直接采用：
```
@media only screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
    .ant-dropdown,
    .ant-select-dropdown,
    .ant-picker-dropdown {
        animation-duration: 0s !important;
    }
}
```

如果 Select 等组件所在页面（有可能是页面也有可能是 Modal 弹出框中等等）有滚动条，那找到这个滚动条所在的元素，然后为其添加伪元素（xxxxx 是滚动条所在元素）：
```
xxxxx:after{
  content: '';
  position: fixed;
  display: block;
}
```

**Comment by yzq777** [comment]
这块还没解决吗？

**Comment by lishuli** [comment]
ie11下，menu是无法打开下拉框的，4.15.3还是是可以打开的，4.15.4到现在的4.16.1无法打开
https://user-images.githubusercontent.com/26503575/120417387-55ace300-c391-11eb-8389-d014fab747ce.mp4

**Comment by huahmj** [comment]
这个问题并没有在版本中解决吧

**Comment by afc163** [comment]
IE11 is no long supported.
