### ISSUE TITLE
自定义表格定制的validator  确认后不提示 但是在控制台提示

### ISSUE THREAD

**Issue by jtc23** [ant-design/ant-design#21046]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义表格定制的validator  确认后不提示 但是在控制台提示

### What does the proposed API look like?
希望能够解决提示问题

**Comment by jtc23** [comment]
https://codesandbox.io/s/antd-reproduction-template-vijdy  代码演示

**Comment by yoyo837** [comment]
操作步骤说一下。
另外，反馈问题请使用缺陷模版，而不是功能请求模版。

**Comment by jtc23** [comment]
> 操作步骤说一下。
> 另外，反馈问题请使用缺陷模版，而不是功能请求模版。

点击按钮操作 但不显示提示 console里面有提示
