### ISSUE TITLE
在 Modal.confirm 下 Input 受控组件功能错误

### ISSUE THREAD

**Issue by AntoninSorrento** [ant-design/ant-design#21044]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rxt0s)

### Steps to reproduce
```
  const [value, setValue] = useState('');
  
    Modal.confirm({
      title: '创建应用',
      content: (
        <Input
          placeholder="请输入应用名称"
          value={value}
          onChange={event => setValue(event.target.value)}
        />
      ),
    });
```

### What is expected?
value 受控于 onChange

### What is actually happening?
页面input组件无法输入值

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12.0 |
| System | MacOS 10.15.2 |
| Browser | Chrome |

**Comment by AntoninSorrento** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/antd-reproduction-template-rxt0s)
> 
> ### Steps to reproduce
> ```
>   const [value, setValue] = useState('');
>   
>     Modal.confirm({
>       title: '创建应用',
>       content: (
>         <Input
>           placeholder="请输入应用名称"
>           value={value}
>           onChange={event => setValue(event.target.value)}
>         />
>       ),
>     });
> ```
> 
> ### What is expected?
> value 受控于 onChange
> 
> ### What is actually happening?
> 页面input组件无法输入值
> 
> Environment	Info
> antd	4.0.0-rc.1
> React	16.12.0
> System	MacOS 10.15.2
> Browser	Chrome

**Comment by yoyo837** [comment]
Try this https://codesandbox.io/s/antd-reproduction-template-3o32r

**Comment by wangcongyi** [comment]
@yoyo837  如果是 class component 该怎么写？ 类似么？
感觉没有从根本上解决这个 bug

**Comment by yoyo837** [comment]
来个demo看看

**Comment by wangcongyi** [comment]
```js

class NewWords extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      oneText: '',
    };
  }

  addOne = (e) => {
    e.stopPropagation();
    e.preventDefault();
    confirm({
      title: '添加敏感词',
      content: <Input
        autoFocus={true}
        onChange={e => this.setState({ oneText: e.target.value })}
        placeholder='请输入'
        size='small'
        maxLength={8}
      />,
    });
  };

```

老项目:  
  react v16.4.1  
  antd  v3.26.0

**Comment by yoyo837** [comment]
在线demo吧，方便交流些。

**Comment by chaosJS** [comment]
针对这个demo
https://codesandbox.io/s/antd-reproduction-template-rxt0s
我也遇到这个问题了 @AntoninSorrento 
把`value={value}` 改为 `defaultValue={value}` 就好了
