### ISSUE TITLE
关于1.4.0之后遇到的问题

### ISSUE THREAD

**Issue by durongzhang** [ant-design/ant-design#2104]
1.4.0之后开始报下面的错误
![image](https://cloud.githubusercontent.com/assets/15725537/16183046/6d78e5c2-36df-11e6-9666-680364a44f17.png)

node版本：6.2.0
antd版本：1.4.0和以后版本
react版本：15.1.0

**Comment by afc163** [comment]
你把 `react` 给 alias 到 `react/dist/react.min` 上了吧。

**Comment by durongzhang** [comment]
是的，为了减少上线包的大小
![image](https://cloud.githubusercontent.com/assets/15725537/16184801/d3de4ee4-36f1-11e6-87ef-b4a515b0ebc5.png)

请问现在这样有办法解决吗

**Comment by afc163** [comment]
https://github.com/webpack/webpack/issues/1339

**Comment by afc163** [comment]
https://github.com/survivejs/webpack/issues/35

**Comment by durongzhang** [comment]
上面的问题解决了，真的非常感谢！

**Comment by xd199153** [comment]
@afc163 
还有这个问题， 1.4.0 之前的版本我都正常使用  ， npm install antd@1.4.0 之后就有这个错误。

![image](https://cloud.githubusercontent.com/assets/4395188/16189480/327ecc6a-370d-11e6-8fed-b8f84f5ad3e4.png)

**Comment by afc163** [comment]
@durongzhang 可以把你的解决方案贴一贴。

**Comment by kasinooya** [comment]
@durongzhang 求解决方案
