### ISSUE TITLE
table向下滚动时能否支持表头相对浏览器顶部悬浮

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design#21043]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当table向下滚动时，表头很可能会消失，不利于观察数据，现在版本实现了通过控制table y轴高度实现滚动，但是这样会导致一个页面两个滚动条，体验不佳，是否可以通过属性控制table向下滚动到表头时，表头相对于浏览器顶部悬浮

### What does the proposed API look like?
<Table
          scroll={{
            y: true,
          }}
        />

**Comment by yoyo837** [comment]
表格的y值动态 从可视区域减去表头、分页高度能间接满足你的想法。

**Comment by zombieJ** [comment]
https://ant.design/components/affix-cn/#header

**Comment by lishaoh** [comment]
@zombieJ 固钉实现不了，期望实现的是window滚动条控制表格滚动，支持表头悬浮

**Comment by zombieJ** [comment]
那就是 @yoyo837  的解法

**Comment by yoyo837** [comment]
我自己项目就是这样，content内部滚动，header和面包屑一直在，如果有表格（通常是单一表格）就再做一层，把表格内部滚动。resize 重置 y。

**Comment by PunkClergy** [comment]
scroll={{ x: 1800,y:window.innerHeight-(window.innerHeight/3) }}
y:window.innerHeight-(window.innerHeight/3) 这段代码是可以实现的；
