### ISSUE TITLE
自定义表格定制的validator 确认后不提示 但是在控制台提示

### ISSUE THREAD

**Issue by jtc23** [ant-design/ant-design#21051]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vijdy )

### Steps to reproduce
点击按钮 但是没有提示

### What is expected?
希望有提示

### What is actually happening?
控制台有提示 但是没有页面内的提示

| Environment | Info |
|---|---|
| antd | undefined |
| React | 最新 |
| System | win10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
两点：
* callback 的回调是 string 不是 boolean
* 最后一个 validator 的 if 判断 value 为空导致 `value.length` 出错，使得 validator 一直在等待 callback 调用。

https://codesandbox.io/s/antd-reproduction-template-09k40
