### ISSUE TITLE
404 when open sub-page in new tab 當打開分頁時是404

### ISSUE THREAD

**Issue by JonathanSum** [ant-design/ant-design#21055]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/JonathanSum/JonathanSum.github.io](https://github.com/JonathanSum/JonathanSum.github.io)
[https://jonathansum.github.io/blog](https://jonathansum.github.io/blog)

### Steps to reproduce

Go to https://jonathansum.github.io/
Or download the package at [https://github.com/JonathanSum/JonathanSum.github.io](https://github.com/JonathanSum/JonathanSum.github.io)
after that, run npm run build, .serve , and go to localhost:5000

### What is expected?
it should not be 404

### What is actually happening?
404 when open sub-page in new tab 當打開分頁時是404
這個問題連 npm run dev 時(local)也出現。
| Environment | Info |
|---|---|
| antd | undefined |
| React | newest |
| System | W10 |
| Browser | Chrome |

---
你可以到 Jonathansum.github.io.試試, 當你click sub menu item 時是沒事,是可以打開 work page, 但以打開 new tab方式來打開時就會到404。
![image](https://user-images.githubusercontent.com/21982975/72802184-12206180-3c00-11ea-8cd6-c2d8d13a9fb9.png)
![image](https://user-images.githubusercontent.com/21982975/72802258-39772e80-3c00-11ea-8fb3-2f48b60e046f.png)

**Comment by shaodahong** [comment]
Ref: https://github.com/facebook/create-react-app/issues/1765#issuecomment-285114194

**Comment by JonathanSum** [comment]
@shaodahong 我是用umi的,不是create react app

**Comment by shaodahong** [comment]
我没发现和 Antd 有关的问题，Umi 我没用过，可以去 Umi 那边看看有没有相关的 Issue，可能是配置什么问题

> Github Page 我记得以前是不支持 History Router 的，现在不确定

**Comment by JonathanSum** [comment]
我用ant design pro 根據 doc 建立了一個基本website,然後 用個npm run build 之後.serve,之後localhost:5000, 也是一樣有問題,很明顯不是github page.
而且問題上方我已經寫清楚"這個問題連 npm run dev 時(**local**)也出現。"

**Comment by shaodahong** [comment]
> 我用ant design pro 根據 doc 建立了一個基本website,然後 用個npm run build 之後.serve,之後localhost:5000, 也是一樣有問題,很明顯不是github page.
> 而且問題上方我已經寫清楚"這個問題連 npm run dev 時(**local**)也出現。"

https://umijs.org/zh/guide/faq.html#build-%E5%90%8E%E8%AE%BF%E9%97%AE%E8%B7%AF%E7%94%B1%E5%88%B7%E6%96%B0%E5%90%8E-404%EF%BC%9F

**Comment by JonathanSum** [comment]
@shaodahong 好吧,我試試,如果也有問題我會上來問,感謝。

**Comment by JonathanSum** [comment]
Ok, I did not solve it by the solution above. But I will try it.
However, I solved by this way: https://github.com/umijs/umi/issues/1268
To be honest, I don't really like how ant-design managing the issue. They always close the issue without proper handing the issue. They just see the issue and quickly close and reply to it no matter it is wrong or not.
