### ISSUE TITLE
Submenu Inside Submenu

### ISSUE THREAD

**Issue by jigardarji318** [ant-design/ant-design#21059]
Hello Team,

I am using airui template and i am creating submenu inside submenu in the left panel, but when i define children inside children its not working.

Can you please help me out on this

**Comment by JonathanSum** [comment]
I am not the mod. However, could you at least show us some code? If you want some examples, you can check the official doc. Or you could check out my code: https://github.com/JonathanSum/JonathanSum.github.io/tree/before_build
http://jonathansum.github.io/
I built it yesterday.
