### ISSUE TITLE
Table固定右边列后，出现无法行对齐的问题

### ISSUE THREAD

**Issue by zsea** [ant-design/ant-design#2106]
在Table的某列中嵌入了Switch，固列右边列后，右边列与整个表格无法行对齐。

**Comment by afc163** [comment]
给个 demo 方便调试。

**Comment by zsea** [comment]
`import React, { Component } from 'react';
import { Table, Icon, message, Switch } from 'antd';
import MainLayout from '../../layouts/MainLayout/MainLayout';
var data=[{ id: 1, username: 'admin', disabled: 0, roles: ['登录', '账户管理'] }
      , { id: 2, username: 'zsea', disabled: 1 }
      , { id: 3, username: 'super', disabled: 0 }
    ];
const Main = React.createClass({
    getInitialState() {
        return {
            rows: data,
            pagination: {
                showTotal: function (total) {
                    return '共  ' + total + ' 条'
                },
                pageSize: 15,
                showQuickJumper: true
            },
            loading: false,
        };
    },
    handlePager(pagination, filters, sorter) {
        const pager = this.state.pagination;
        pager.current = pagination.current;
        this.setState({
            pagination: pager,
        });
        this.getdata({
            results: pager.pageSize,
            page: pager.current,
            sortField: sorter.field,
            sortOrder: sorter.order,
            ...filters
        });
    },
getdata(params = {}) {
    this.setState({ loading: true });
    var self = this;
    $.get('/json/super', params, function (response) {
        if (response && response.success) {
            const pager = self.state.pagination;
            pager.total = response.total;
            self.setState({
                loading: false,
                rows: response.rows,
                pagination: pager
            });
        }
        else {
            self.setState({
                loading: false
            });
            message.error(response.message, 10);
        }
    }, 'json');
},
componentDidMount() {
    //this.getdata();
},
SwitchChange(checked, superid) {
    //console.log(`switch to ${checked}`);
    $.post('/json/super/disabled', { id: superid, disabled: checked ? 1 : 0 }, function (response) {
        if (response.message) {
            if (response.success) {
                message.info(response.message);
            }
            else {
                message.error(response.message);
            }
        }
    }, 'json');
},
render() {
    var self = this;
    const columns = [{
        title: '##',
        dataIndex: 'id',
        key: 'id',
    }, {
            title: '账户',
            dataIndex: 'username'
        }, {
            title: '状态',
            dataIndex: 'disabled',
            render: (v, row) => {
                return <Switch defaultChecked={!v} onChange={(checked) => self.SwitchChange(checked, row.id) } />
            }
        }, {
            title: '角色',
            dataIndex: 'roles',
            render: (v) => {
                if (v) {
                    return v.join(',')
                }
                else {
                    return '';
                }
            }
        }, {
            title: '操作',
            key: 'operation',
            fixed: 'right',
            render: (text, record) => (
                <span>
                    <a href="#" data-id={record.id}>删除</a>
                    <span className="ant-divider"></span>
                    <a href="#">重设密码</a>
                </span>
            ),
        }];

    return (
        <MainLayout name='账户管理'>
            <Table columns={columns}
                rowKey={record => record.id}
                dataSource={this.state.rows}
                pagination={this.state.pagination}
                loading={this.state.loading}
                onChange={this.handlePager}
                />
        </MainLayout>
    );
}
});

export default Main;`

**Comment by zsea** [comment]
`直接贴代码有问题‘

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by zsea** [comment]
我正在努力打开以上链接。。。

**Comment by zsea** [comment]
搞好了，麻烦你瞧一瞧。
http://codepen.io/zsea/pen/QEKroM?editors=001

**Comment by afc163** [comment]
水平方向的对齐，需要设定列的宽度。http://codepen.io/anon/pen/LZRrRY?editors=001

垂直方向的对齐，我正在改。

**Comment by afc163** [comment]
在 rc-table@4.2.2 里修复，尝试重新安装 antd 。
