### ISSUE TITLE
V4 Form.List onChange 全部刷新

### ISSUE THREAD

**Issue by qq645381995** [ant-design/ant-design#21065]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/listshouldupdate2-cry4i?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
点击右边`switch`，索引 0、1都会刷新。

### What is expected?
只有改的地方刷新

### What is actually happening?
都会刷新

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | last |
| System | mac |
| Browser | chrome |

---
问题是要用哪个 api 去改变值 

1. `setFieldsValue` 不支持 path 写法，`switch`改变后，会全部刷新。
2. `setFields` 执行后，没有触发`shouldUpdate`

**Comment by zombieJ** [comment]
`setFields` 用法是对的，我看看为什么没有触发 `shouldUpdate`。

**Comment by qq645381995** [comment]
还有个问题

![image](https://user-images.githubusercontent.com/7971419/72860395-a2929b00-3d01-11ea-9c9c-9a733f9bb15b.png)
https://codesandbox.io/s/blissful-platform-pymkl
类型报错了

**Comment by zombieJ** [comment]
👌

**Comment by qq645381995** [comment]
@zombieJ  你试了吗，我怎么试了还是没触发

**Comment by yoyo837** [comment]
只是改了上游，antd的依赖没更新。

**Comment by yoyo837** [comment]
你应该需要等下一个rc 版本

**Comment by qq645381995** [comment]
@yoyo837 机制变了吗 我添加了  rc-field-form 。

**Comment by qq645381995** [comment]
@zombieJ 发现 form 还有很多问题。
1、第一个文本框改变值，打印一次，是正常的，但是当第二个文本框输入内容，再回来改第一个文本框内容，就打印很多次。
```jsx
 <Form name="demo">
      <Form.Item name={["name"]}>
        <Input />
      </Form.Item>
      <Form.Item
        name={["age"]}
        dependencies={["name"]}
        rules={[
          ({ getFieldValue }) => {
            console.log("1", getFieldValue());
            return { validator: () => Promise.resolve() };
          }
        ]}
      >
        <Input />
      </Form.Item>
    </Form>

```

2、之前说的 Form.Item 嵌套的方式，只要不传 name 其他都全部传就可以，但是现在不显示 children 了
https://github.com/ant-design/ant-design/issues/20481#issuecomment-570506067

```jsx

<Form name="demo">
      <Form.Item name={["name"]}>
        <Input />
      </Form.Item>
      <Form.Item noStyle dependencies={["name"]}>
        <Form.Item
          name={["age"]}
          dependencies={["name"]}
          rules={[
            ({ getFieldValue }) => {
              console.log("1", getFieldValue());
              return { validator: () => Promise.resolve() };
            }
          ]}
        >
          <Input />
        </Form.Item>
      </Form.Item>
    </Form>

```

**Comment by qq645381995** [comment]
还有这个  https://github.com/ant-design/ant-design/issues/20481#issuecomment-570538332 
都是嵌套 Form.Item 衍生的。

**Comment by zombieJ** [comment]
@qq645381995 ，方便分别开几个新的 issue 吗？

**Comment by qq645381995** [comment]
> @qq645381995 ，方便分别开几个新的 issue 吗？

耗时耗力，问题其实都息息相关，希望能重头梳理下，各种场景都跑下。可以提交以后，我本地验证下。

**Comment by qq645381995** [comment]
我是急性子，强迫症，就想把这些问题一股脑全修好。我好接着封装我的东西。

**Comment by zombieJ** [comment]
把代码拷贝下来本地可以运行，你本地重新安装试试看：
![Kapture 2020-01-22 at 20 07 08](https://user-images.githubusercontent.com/5378891/72893038-0a250680-3d53-11ea-8526-dbd431945cd4.gif)

**Comment by zombieJ** [comment]
> 1、第一个文本框改变值，打印一次，是正常的，但是当第二个文本框输入内容，再回来改第一个文本框内容，就打印很多次。

这个是预期行为，通过 context 创建的动态 rule 会在每次更新都检查以确定是否有 `required` 属性。

> 2、之前说的 Form.Item 嵌套的方式，只要不传 name 其他都全部传就可以，但是现在不显示 children 了

没有设置 `name` or renderProps 却设置了 `dependencies` 是错误的行为，可以看一下 console 的 warning 信息：
<img width="671" alt="截屏2020-01-22下午8 15 06" src="https://user-images.githubusercontent.com/5378891/72893543-3e4cf700-3d54-11ea-85e9-159b1ca45b20.png">

**Comment by qq645381995** [comment]
那其实 外部的 FormItem 不能加 dependencies  和 rules 了

**Comment by zombieJ** [comment]
* 和字段渲染相关的，用 `name`、`dependencies` 、renderProps
* 只用 FormItem 样式的，不用上述字段

**Comment by qq645381995** [comment]
因为是封装一个 FormItem 需要写死。需要明确。

**Comment by zombieJ** [comment]
封装的话可以参考一下这个 [fix](https://github.com/ant-design/ant-design/pull/20963)，判断一下是否要绑定字段再传属性。

**Comment by qq645381995** [comment]
```jsx
export default (props) => {
    const { name, children, addonAfter, ...rest } = props;
    const { rules } = rest;
    let _required: boolean | undefined = false;
    // 根据 rules required 判断外部 Form.Item 是否必填
    forEach(rules, item => {
        if ('required' in item) _required = item.required;
    });
    return (
        <Form.Item required={_required} {...rest}>
            <>
                <Form.Item noStyle name={name} {...rest}>
                    {children}
                </Form.Item>
                {addonAfter}
            </>
        </Form.Item>
    );
};

```
这样 required 可以同步无感知。对于 children 只写一个  field 的。

**Comment by qq645381995** [comment]
```jsx
export default (props) => {
    const { name, children, addonAfter, ...rest } = props;
    let _required = false;
    // 根据 rules required 判断外部 Form.Item 是否必填
    forEach(props.rules, item => {
        if ('required' in item) _required = item.required;
    });

    return children ? (
        <Form.Item required={_required} {...omit(rest, ['rules', 'dependencies'])}>
            <Form.Item noStyle name={name} {...rest}>
                {children as RenderChildren}
            </Form.Item>
            <React.Fragment>{addonAfter}</React.Fragment>
        </Form.Item>
    ) : null;
};
```

那是外部排除 `rules` `dependencies`

**Comment by qq645381995** [comment]
> 把代码拷贝下来本地可以运行，你本地重新安装试试看：
> ![Kapture 2020-01-22 at 20 07 08](https://user-images.githubusercontent.com/5378891/72893038-0a250680-3d53-11ea-8526-dbd431945cd4.gif)

我本地下载试了，确实可以触发，但是用上面的的  Form.ItemChildren 就无法触发了。

**Comment by zombieJ** [comment]
上面的代码更新成一个完整示例，我弄下来跑一下看看。

**Comment by qq645381995** [comment]
> 上面的代码更新成一个完整示例，我弄下来跑一下看看。

示例更新了

**Comment by zombieJ** [comment]
```diff
+  const passName = {};
+  if (name) {
+    passName.name = name;
+  }

  return children ? (
-    <Form.Item required={_required} {...omit(rest, ['rules', 'dependencies'])}>
-      <Form.Item noStyle {...rest}>
+    <Form.Item required={_required} {...omit(rest, ['rules', 'dependencies', 'shouldUpdate'])}>
+      <Form.Item noStyle {...passName} {...rest}>
        {children}
      </Form.Item>
      <React.Fragment>{addonAfter}</React.Fragment>
    </Form.Item>
  ) : null;
```

**Comment by zombieJ** [comment]
另外，你可以考虑一下优化层级结构。`noStyle` + 没有任何绑定/更新，这个 FormItem 就等同于 Fragment 没有必要多一级。

<img width="535" alt="截屏2020-01-23上午10 08 47" src="https://user-images.githubusercontent.com/5378891/72951135-5a8a7b80-3dc8-11ea-88fa-6b08d8bf12d1.png">

**Comment by qq645381995** [comment]
> 另外，你可以考虑一下优化层级结构。`noStyle` + 没有任何绑定/更新，这个 FormItem 就等同于 Fragment 没有必要多一级。
> 
> <img alt="截屏2020-01-23上午10 08 47" width="535" src="https://user-images.githubusercontent.com/5378891/72951135-5a8a7b80-3dc8-11ea-88fa-6b08d8bf12d1.png">

因为有传 `addonAfter` 的情况，我先不做判断`addonAfter`  是否存在而返回一层还是二层，因为触发的几率低。


`passName` 的问题应该是判断 name 的条件不严谨导致的这个问题。应该判断有没有 name 这个属性，而不是判断是否为空。因为有的地方传了 name ，但是获取的时候为空了，就把它原来的逻辑给混掉了。

**Comment by qq645381995** [comment]
开工了。。。 @zombieJ 是否需要添加 `addonAfter` `addonBefore` 呢？

**Comment by zombieJ** [comment]
暂时不加，目前也是可以实现同样的效果。免得加了之后发现更好的方式导致 API 无法收回。

**Comment by crazyair** [comment]
注册字段用的是 `children`，追加其他元素没有影响。现在排除了 `"name", "rules", "dependencies", "shouldUpdate"` ，不知道遇到其他场景会不会暴露出其他问题。

**Comment by crazyair** [comment]
又一个问题

![image](https://user-images.githubusercontent.com/7971419/73585029-e3479c80-44d7-11ea-9bb2-7e7ed3b2a170.png)

这里没有校验 `*` 了，

**Comment by zombieJ** [comment]
哪个 codesandbox？

**Comment by crazyair** [comment]
https://codesandbox.io/embed/listshouldupdate2-cry4i?fontsize=14&hidenavigation=1&theme=dark

**Comment by zombieJ** [comment]
Nice catch.  Move into #21167
