### ISSUE TITLE
Table auto resize feature

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#21066]
![New Wireframe 1](https://user-images.githubusercontent.com/14831261/72861831-fd2df600-3d05-11ea-8eff-219fc7fad268.png)

基于真实的业务场景和长期使用人员的反馈，页面上除了固定宽度的 SideBar 和面包屑之外，Table 需要自动撑满

使用人员的屏幕尺寸区别，比如 13 寸(非 Retina )笔记本的长宽可以显示的 Table 区域很小，每页只展示十条都需要拉很长一段距离才能翻页，如果页面上再加上 SearchBar 那么可视的范围就更加有限，不利于使用人员长期操作

现在体验好的方案就是手动给每个 `Column` 设置宽度，或者利用 js 计算宽度，但是开发时有时候并不知道接口返回字段的平均宽度，还需要等接口开发完毕之后才能每个调整来达到完美体验

需求：
**固定表头**的的情况下 Table 自动伸缩宽高

之前和 @zombieJ 讨论的时候可能会加个 `{scroll: { y: true }}`

代码示例：
https://codesandbox.io/s/friendly-night-9pd6u

Ref：
https://github.com/ant-design/ant-design/issues/20885
https://github.com/ant-design/ant-design/issues/15340#issuecomment-471927481
https://github.com/ant-design/ant-design/issues/10901
...

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | last |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
你这是主要的高吧，那和列宽是什么关系？因为我自己已经简单实现了高度表格高度自适应 https://github.com/ant-design/ant-design/issues/21043#issuecomment-576604380

**Comment by shaodahong** [comment]
@yoyo837 你的这个解决方案是固定表头么

**Comment by yoyo837** [comment]
而且感觉还是有点业务强关联性，在pro模版里实现一个高级组件如何？

**Comment by yoyo837** [comment]
> @yoyo837 你的这个解决方案是固定表头么

不是，是动态`min-height`，也就是y

**Comment by zombieJ** [comment]
同一个意思，就是让 Table 可以通过 css 设置高度。然后由 `{ y: true }` 撑满 `calc(100vh - XXXpx)` 这种场景。

**Comment by shaodahong** [comment]
> 同一个意思，就是让 Table 可以通过 css 设置高度。然后由 `{ y: true }` 撑满 `calc(100vh - XXXpx)` 这种场景。

XXXpx 这个很难算，表头会换行，你看我给的例子就是

**Comment by yoyo837** [comment]
管它表头换不换行，从table header wrapper里拿最终的Dom高，也就是先用最小高度渲染落地再拿。

**Comment by yoyo837** [comment]
因为我自己的项目和你画的图基本一毛一样。😂

**Comment by zombieJ** [comment]
> > 同一个意思，就是让 Table 可以通过 css 设置高度。然后由 `{ y: true }` 撑满 `calc(100vh - XXXpx)` 这种场景。
> 
> XXXpx 这个很难算，表头会换行，你看我给的例子就是

只是举例，更确切些就是 scrollY 根据 Table 的高度自适应。

**Comment by shaodahong** [comment]
> 因为我自己的项目和你画的图基本一毛一样。😂

因为这个就是真实的业务场景，大同小异

**Comment by zombieJ** [comment]
`{ y: true }` 还是能节省开发者时间的

**Comment by yoyo837** [comment]
> `{ y: true }` 还是能节省开发者时间的

话是没错，但是我感觉也就五五开吧，一种是表格页面，一种是其他页面。

**Comment by shaodahong** [comment]
@yoyo837 你这个有没有例子什么的，瞅瞅？

**Comment by yoyo837** [comment]
@shaodahong dingtalk 私我

**Comment by yoyo837** [comment]
我试试做个demo 支持 scroll:{ x: true, y: true}

**Comment by yoyo837** [comment]
会迟一些日子弄。

**Comment by lishaoh** [comment]
@yoyo837 页面内容不止table存在，包括Search、其他内容，现在我的解决办法是resize时计算table中各个dom style

**Comment by yoyo837** [comment]
@lishaoh 我知道，就是要表格滚动区域 + 表头 + 分页 一共刚好可视区域那么高，滚过table后继续滚body。所以其他内容没影响

**Comment by lishaoh** [comment]
@yoyo837我这需求是table里面不能有滚动条，只能通过body滚动控制table表头悬浮

**Comment by yoyo837** [comment]
@shaodahong 你觉得按哪个做？

**Comment by shaodahong** [comment]
> 你觉得按哪个做？

就之前说的那个场景 `scroll:{ x: true, y: true}`

**Comment by yoyo837** [comment]
我是说滚动方式,  @lishaoh 说的是stricky那种，我说的是table body max-height.

**Comment by shaodahong** [comment]
table body max-height.

**Comment by lishaoh** [comment]
是的，我说的是stricky这种

**Comment by yoyo837** [comment]
stricky 是必须考虑多个表格，table body max-height. 是不用考虑的。

**Comment by zombieJ** [comment]
从 Table 角度看，当 `{ y: true }` 时，它不管外面怎么处理布局，直管自己最后可以用的高度是多少来处理剩余空间。

**Comment by ludaokai** [comment]
我们也是自己尝试使用这种布局，也是要自己算高度。只是确实体验不上是很完美
<img width="1381" alt="image" src="https://user-images.githubusercontent.com/50224242/73126229-0f9c7e00-3feb-11ea-99e1-11e8c43fd27d.png">

**Comment by FoxxMD** [comment]
This isn't a true solution but I was able to get "good enough" results using this.

```js
import { Table } from 'antd';
import React, { useEffect, useMemo } from 'react';
import useWindowDimensions from './' // https://stackoverflow.com/a/59185109

// a conservative estimate for total pixel width of page elements that aren't the table (in my solution)
// this could be moved into the function and determined with any other number of solutions
const magicOffset = 250;

const MinWidthTable = ({columns, ...props}) => {
    const { width } = useWindowDimensions();

    useEffect(() => {
            console.log('Trigger update on width change', width);
    }, [width]);

    const columnData = useMemo(() => {
        // treat 'width' property on column as min-width -- remove it if the average width of a column
        // *should* be larger than the width specified so that antd lets the column be responsive
        if(columns.some(x => x.width !== undefined && ((width - magicOffset) / columns.length) > x.width )) {
            // do some() calc first so that we only return a new object if a change is made
            return columns.map((x) => {
                const { width: xWidth, ...rest } = x;
                if(x.width === undefined || x.width > ((width - magicOffset) / columns.length)) {
                    return x;
                }
                return rest;
            });
        }
        return columns;
    }, [columns, width]);

    return <Table {...props} columns={columnData} />;
};

// used like regular <Table/>
export default MinWidthTable;
```

**Comment by zombieJ** [comment]
@shaodahong @yoyo837 ,
how about this issue? And who of you will work on this if needed?

**Comment by yoyo837** [comment]
🙋我预计复工后看一下

**Comment by lucasleelz** [comment]
一直都有这个业务场景~ 特别是在表格会有复选框的情况下。

**Comment by bald-newcomer** [comment]
能够设置table最小列宽(min-width),来控制table内容超长换行吗？还是用其他的解决方案

**Comment by StallionV** [comment]
Can we try having newer issues and comments in English for general benefit of all the users :) ?

**Comment by afc163** [comment]
supported in https://github.com/ant-design/ant-design/pull/25939

**Comment by Chris-myEdOnline** [comment]
@afc163 #25939 Does not support vertical height auto fill. 从 "Table 角度看，当 { y: true } 时，它不管外面怎么处理布局，直管自己最后可以用的高度是多少来处理剩余空间。" Has not been implemented in #25939.

How can a react library element unable to fit itself in a cell given width and height?
scroll={{ y: 500 }} does not account for the header/pagination which makes it impossible to calculate the row's height.

**Comment by afc163** [comment]
Try `scroll={{ y: 'calc(100vh - 200px)' }}`

**Comment by Chris-myEdOnline** [comment]
> Try `scroll={{ y: 'calc(100vh - 200px)' }}`

Thank you for that, we have something like that already. It's just the size of header/pagination within antd table are not taken into calculation. This makes it impossible to fit within a window correctly.

![Untitled](https://user-images.githubusercontent.com/36211804/95532816-3db4d780-0a2d-11eb-8031-934aec0f29a6.png)

**Comment by jordanmkoncz** [comment]
@Chris-myEdOnline did you ever find a solution for this issue? I'm having the same problem, also caused by the fact that the table header height is dynamic and not taken into account for the `scroll` calculation.

**Comment by Chris-myEdOnline** [comment]
@jordanmkoncz No. It's forcing all my pages that contains a table to be scrollable. I think the challenge here is that `display: table` is not going to play nice with % height or overflowing. With flex, it's quite hard make sure of cells alignments. With table, it's quite hard to make elements sticky.

@yoyo837 Will able to explain further.
