### ISSUE TITLE
form表单, class component，通过 ref 获得实体达不到预期效果

### ISSUE THREAD

**Issue by WinterWoods** [ant-design/ant-design#21060]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
// antd v4
class Demo extends React.Component {
  formRef = React.createRef();

  componentDidMount() {
    this.formRef.setFieldsValue({
      username: 'Bamboo',
    });
  }

  render() {
    return (
      <Form ref={formRef}>
        <Form.Item name="username" rules={[{ required: true }]}>
          <Input />
        </Form.Item>
      </Form>
    );
  }
}

### What does the proposed API look like?
这段代码中this.formRef为空.

**Comment by WinterWoods** [comment]
https://codesandbox.io/s/antd-reproduction-template-lu87h?fontsize=14&hidenavigation=1&theme=dark

**Comment by WinterWoods** [comment]
我在使用const [form] = Form.useForm();在function模式下会出现一个警告

> Warning: Instance created by `useForm` is not connect to any Form element. Forget to pass `form` prop?

https://codesandbox.io/s/antd-reproduction-template-rwrij

**Comment by yoyo837** [comment]
<Form form={form}></Form>

**Comment by zombieJ** [comment]
Modal 在打开之前，里面的子元素还没创建。所以 `formRef` 是空的。

ref: https://codesandbox.io/s/antd-reproduction-template-p581v
