### ISSUE TITLE
小表格在指定scroll属性时首行行高被标题行影响，敬请修复

### ISSUE THREAD

**Issue by leejaen** [ant-design/ant-design#2107]
表现在设置scroll属性时第一行行高明显比其他行行高大不少，而且表格的标题单元格与表格行单元格不对齐，不设置scroll属性时则无问题。另外，小表格显示边框，可否支持配置去掉此设置？

问题效果：
![](http://7xjl1j.com1.z0.glb.clouddn.com/error_table.png)

正常效果：
![](http://7xjl1j.com1.z0.glb.clouddn.com/normal_table.png)

代码：
```
const { Form, Row, Col, Table } = antd;
const columns = [{
    title: '姓名',
    dataIndex: 'name',
}, {
    title: '年龄',
    dataIndex: 'age',
}, {
    title: '住址',
    dataIndex: 'address',
}];
const data = [{
    key: '1',
    name: '胡彦斌',
    age: 32,
    address: '西湖区湖底公园1号',
}, {
    key: '2',
    name: '胡彦祖',
    age: 42,
    address: '西湖区湖底公园1号',
}, {
    key: '3',
    name: '李大嘴',
    age: 32,
    address: '西湖区湖底公园1号',
}];

const App = React.createClass({
    render() {
        return (
            <Form>
                <Form.Item>
                    <Row>
                        <Col span={12} push={12}>
                            <h4>大号表格（紧凑型）</h4>
                            <Table columns={columns} dataSource={data} scroll={{ y: 350 }}/>
                            <h4>中号表格（紧凑型）</h4>
                            <Table columns={columns} dataSource={data} size="middle" scroll={{ y: 350 }}/>
                            <h4>小号表格</h4>
                            <Table columns={columns} dataSource={data} size="small" scroll={{ y: 350 }}/>
                        </Col>
                    </Row>
                </Form.Item>
            </Form>
        );
    }
});

ReactDOM.render(<App />, document.getElementById('container'));
```

**Comment by afc163** [comment]
> 1. 表现在设置scroll属性时第一行行高明显比其他行行高大不少

无法重现这个问题：http://codepen.io/anon/pen/YWGLeo?editors=001

> 2. 而且表格的标题单元格与表格行单元格不对齐

注意看文档，固定表头需要设置列的 width。

> 3. 小表格显示边框，可否支持配置去掉此设置

自行样式覆盖。

**Comment by leejaen** [comment]
![image](https://cloud.githubusercontent.com/assets/1638970/16187581/bdbad814-3703-11e6-8585-1b5e0495e54b.png)

**Comment by afc163** [comment]
你看我发的链接呢，codepen 里无法重现。如果重现了，麻烦给我发一个能看到效果的 codepen 。

**Comment by afc163** [comment]
建议先升到 antd 最新的最新版本试试。

**Comment by leejaen** [comment]
@afc163 ，多谢指教，不过我已经升级到最新版本，且在上面的链接里同样出现首行高度的问题，下面连接是我在codepen里的链接：http://codepen.io/leejaen/pen/gMwJaw?editors=001

我这里运行看到的效果：
![image](https://cloud.githubusercontent.com/assets/1638970/16215056/14ab5ac6-3791-11e6-8612-9e7b3a5929e8.png)

**Comment by afc163** [comment]
![](https://zos.alipayobjects.com/rmsportal/kdrsznkyGxzgfkE.png)

你是什么浏览器，我在 chrome 51 下看到的是这样的。

**Comment by wufeng87** [comment]
我也是chrome51, 我这看例子也有问题目测是这个样式引起的：
`
.ant-table-fixed-header .ant-table-header {
    
    overflow-x: scroll;
    overflow-y: hidden;
    padding-bottom: 20px;...`

**Comment by afc163** [comment]
我知道了，这个样式在这里修复了。https://github.com/ant-design/ant-design/commit/56f7f9926c903197add7a9ca0877e7428dd33ba0

**Comment by afc163** [comment]
中小表格也需要修复，感谢反馈~

**Comment by afc163** [comment]
1.5.1

**Comment by playwolsey** [comment]
都没修复就close了么，官网的小表格都对不起你们自己不知道吗
