### ISSUE TITLE
Importing separate modules without babel-plugin-import

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#21078]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
So, I don't use babel for my build. I use typescript compiler instead. Therefore I cannot use `babel-plugin-import`. How do I only import the modules I need and not the whole lib?

### What does the proposed API look like?
Are there plans to make an api for this scenario? Guess I'm not unique here...

**Comment by zombieJ** [comment]
https://ant.design/docs/react/getting-started#Import-on-Demand

**Comment by avalanche1** [comment]
Thank you.
I'm getting this error: `/node_modules/antd/es/style/index.less: Inline JavaScript is not enabled. Is it set in your options?`
I'm useing `parcel` as my bundler.

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/7927#issuecomment-369099450
