### ISSUE TITLE
Manual upload for Upload.Dragger component

### ISSUE THREAD

**Issue by rahulborah** [ant-design/ant-design#21072]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The Dragger component for Upload should allow manual upload.

### What does the proposed API look like?
Dragger should accept **beforeUpload** and **onRemove** attributes like Upload component.

**Comment by zombieJ** [comment]
Please check your code. Dragger already support these props: https://codesandbox.io/s/autumn-shape-1ixyi
