### ISSUE TITLE
Do I have to show "Ant Design ©2018 Created by Ant UED" on the bottom of the page 要寫上Ant Design ©2018 Created by Ant UED嗎?

### ISSUE THREAD

**Issue by JonathanSum** [ant-design/ant-design#21087]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jonathansum.github.io/](https://jonathansum.github.io/)

### Steps to reproduce
https://github.com/JonathanSum/JonathanSum.github.io/tree/before_build

### What is expected?
Do I have to show "Ant Design ©2018 Created by Ant UED" on the bottom of the page?

### What is actually happening?
Do I have to show "Ant Design ©2018 Created by Ant UED" on the bottom of the page?

| Environment | Info |
|---|---|
| antd | undefined |
| React | newest |
| System | W10 |
| Browser | Chrome |

---
Do I have to show "Ant Design ©2018 Created by Ant UED" on the bottom of the page?

要嗎?

**Comment by keithort** [comment]
No.
