### ISSUE TITLE
Antd Components don't work properly when used inside other modal libraries

### ISSUE THREAD

**Issue by nachmo5** [ant-design/ant-design#21081]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-zibxc)

### Steps to reproduce
First scenario : Bug with  react-responsive-modal
1. click on "Bug with react-responsive-modal" button
2. click on the select
3. try to choose an option

Second scenario: Bug with material ui modal
1. click on "Bug with material ui" button
2. hover the button
3. try to write something on the input

### What is expected?
First scenario : The select option should be chosen  ///
Second Scenario: Ability to edit the input 

### What is actually happening?
First scenario: The clicked option isn't selected ON THE FIRST TRY ///
Second scenario : Can't edit the input

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | codesandbox |
| Browser | Chrome |

**Comment by zombieJ** [comment]
These lib prevent default event globally that we can not get correct event trigger. Please fire issue with them instead since we can do nothing about this.

**Comment by nachmo5** [comment]
Thank you for your response.
I don't think the problem comes from the modal lib preventing the event, 
because when i use another select lib ( normal html select or react-select ), i don't have this bug, the event is received from the first click. 
This means the select component receives the event.

**Comment by Evavic44** [comment]
In my situation, I was using a Shadcn Drawer with the antd Select and it wasn't getting triggered. Finally solved it by adding point event to the select input:

```js
<Select
  title="gender"
  options={options}
  onChange={onValueChange}
  value={value}
  popupClassName="pointer-events-auto"
/>
```

For reference: https://github.com/ant-design/ant-design/issues/13905
