### ISSUE TITLE
Form.Item type issue introduced in 4.0.0-rc.2

### ISSUE THREAD

**Issue by samit4me** [ant-design/ant-design#21085]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-typescript-kojjv)

### Steps to reproduce
Try to use the Form.Item component like "<Form.Item label="Username" name="username" />"

### What is expected?
To work as it did in previous versions (e.g. 4.0.0-rc.1 is fine).

### What is actually happening?
TypeScript error:
JSX element type 'ReactNode' is not a constructor function for JSX elements.
  Type 'undefined' is not assignable to type 'Element | null'.ts(2605)

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.12.0 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 79 |

---
Working in rc1: https://codesandbox.io/s/antd-typescript-mrvve

Not working in rc2: https://codesandbox.io/s/antd-typescript-kojjv

**Comment by samit4me** [comment]
Oh dang, just found that this has been fixed in #21067 
Didn't see this as the the issue was closed but fix not yet released.

**Comment by gino8080** [comment]
yeah it does not seems to be released in rc2

rolled back to rc1 for now
