### ISSUE TITLE
programmitically deselect all ant design select selected tags

### ISSUE THREAD

**Issue by Ammar11013** [ant-design/ant-design#21089]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
general issue

### Steps to reproduce
general issue

### What is expected?
to deselect all tags with giving value = null

### What is actually happening?
when value is given null select is no more editable

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | react/react js |
| System | windows 10, ide Visual Studio Code |
| Browser | chrome |

---
how to deselect all select tags after button click

**Comment by kaikun213** [comment]
I have the same issue for a normal select, setting the value to null will not clear it in the new 4.0 RC. I believe this worked in 3.x.

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#I-set-the-value-of-Input/Select(etc.),-and-then-it-cannot-be-changed-by-user's-action

**Comment by kaikun213** [comment]
@afc163 This is about clearing the value that is shown, not about changing them. I made a separate issue with reproduction: https://github.com/ant-design/ant-design/issues/21161. I don't think the link helps any.
