### ISSUE TITLE
Rangepicker: Calendar jumps back to current date after selecting a start date beyond the current month

### ISSUE THREAD

**Issue by TheLeafiest** [ant-design/ant-design#21084]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/date-picker/](https://next.ant.design/components/date-picker/)

### Steps to reproduce
1. Click rangpicker input field
2. Skip ahead a couple months or years
3. Select a start date

### What is expected?
It should stay on the month that you selected the start date on

### What is actually happening?
It jumps back to the current calendar month

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.12.0 |
| Browser | Chrome 79.0.3945.117 |

**Comment by morenyang** [comment]
Try to fix in https://github.com/react-component/picker/pull/21

**Comment by hannaofsweden** [comment]
Fixing this would be great! :) Our customers find this very annoying.

**Comment by TheLeafiest** [comment]
@morenyang Any progress on this issue? Appreciate you looking at this, thanks again!
