### ISSUE TITLE
4.0.0-rc.1 TypeError: window.matchMedia is not a function in Jest

### ISSUE THREAD

**Issue by Jfelix61** [ant-design/ant-design#21096]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://not/required/see/description](http://not/required/see/description)

### Steps to reproduce
Using react-testing-tools along with an antd form, will result in this error: 
````
TypeError: window.matchMedia is not a function

      53 | 
      54 | const customRender = (ui: ReactElement<any>, options?: any) =>
    > 55 |   render(ui, { wrapper: providers(), ...options });
         |   ^
      56 | 
      57 | const loggedInRender = (ui: ReactElement<any>, options?: any) =>
      58 |   render(ui, { wrapper: providers(loggedInStore), ...options });

      at matchMedia (node_modules/antd/lib/_util/_util/responsiveObserve.js:58:32)
          at Array.forEach (<anonymous>)
      at Object.forEach [as register] (node_modules/antd/lib/_util/_util/responsiveObserve.js:53:36)
      at Object.register [as subscribe] (node_modules/antd/lib/_util/_util/responsiveObserve.js:27:18)
      at Row.subscribe [as componentDidMount] (node_modules/antd/lib/grid/grid/row.jsx:63:40)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:22101:22)
      at commitLayoutEffects (node_modules/react-dom/cjs/react-dom.development.js:25344:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:336:14)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:385:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:440:31)
      at commitRootImpl (node_modules/react-dom/cjs/react-dom.development.js:25082:9)
      at unstable_runWithPriority (node_modules/scheduler/cjs/scheduler.development.js:697:12)
      at runWithPriority$2 (node_modules/react-dom/cjs/react-dom.development.js:12149:10)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:24922:3)
      at finishSyncRender (node_modules/react-dom/cjs/react-dom.development.js:24329:3)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:24307:9)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23698:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:27103:3)
      at node_modules/react-dom/cjs/react-dom.development.js:27528:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:24433:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:27527:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:27608:10)
      at node_modules/@testing-library/react/dist/pure.js:86:25
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:24386:12)
      at act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1092:14)
      at render (node_modules/@testing-library/react/dist/pure.js:82:26)
      at customRender (src/utils/test-utils.tsx:55:3)
      at Object.<anonymous> (src/components/__tests__/SignUpForm.test.tsx:61:45)
````

### What is expected?
No error to be returned. 

### What is actually happening?
Forms break jest and react-testing-tool tests. 

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.12.0 |
| System | Manjaro Linux 5.4.12 |
| Browser | 79.0.3945.117 |

**Comment by Thanaen** [comment]
You can fix this by mocking the window.matchMedia in the setupTests.js file or before your tests.
Here's the mock I use:
```js
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn(),
  })),
});
```
[source](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)

**Comment by Gfast2** [comment]
```TypeError: Cannot read property 'addListener' of undefined```
Is what I got after Add the mocked matchMedia object

**Comment by iaurg** [comment]
Hi,

I solved this by doing:

Added in `jest.config.js` file:
```js
...
setupFilesAfterEnv: ['./jest.setup.js']
```

Created a file `jest.setup.js` in root folder with:
```js
Object.defineProperty(window, 'matchMedia', {
  writable: true,
  value: jest.fn().mockImplementation(query => ({
    matches: false,
    media: query,
    onchange: null,
    addListener: jest.fn(), // deprecated
    removeListener: jest.fn(), // deprecated
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    dispatchEvent: jest.fn()
  }))
})
```

ps: setupFilesAfterEnv is the "new" [deprecated setupTestFrameworkScriptFile](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array).

**Comment by pt-bayramali** [comment]
> You can fix this by mocking the window.matchMedia method in the setupTests.js file or before your tests.
> Here's the mock I use:
> 
> ```js
> Object.defineProperty(window, 'matchMedia', {
>   writable: true,
>   value: jest.fn().mockImplementation(query => ({
>     matches: false,
>     media: query,
>     onchange: null,
>     addListener: jest.fn(), // deprecated
>     removeListener: jest.fn(), // deprecated
>     addEventListener: jest.fn(),
>     removeEventListener: jest.fn(),
>     dispatchEvent: jest.fn(),
>   })),
> });
> ```
> 
> [source](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)

Receiving the following error after using this mock object:

```
TypeError: mql.addListener is not a function

```

**Comment by marsky911** [comment]
> > You can fix this by mocking the window.matchMedia method in the setupTests.js file or before your tests.
> > Here's the mock I use:
> > ```js
> > Object.defineProperty(window, 'matchMedia', {
> >   writable: true,
> >   value: jest.fn().mockImplementation(query => ({
> >     matches: false,
> >     media: query,
> >     onchange: null,
> >     addListener: jest.fn(), // deprecated
> >     removeListener: jest.fn(), // deprecated
> >     addEventListener: jest.fn(),
> >     removeEventListener: jest.fn(),
> >     dispatchEvent: jest.fn(),
> >   })),
> > });
> > ```
> > 
> > 
> > [source](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)
> 
> Receiving the following error after using this mock object:
> 
> ```
> TypeError: mql.addListener is not a function
> ```

I have the same probelm. have you solved it?

**Comment by janarvaez** [comment]
> > > You can fix this by mocking the window.matchMedia method in the setupTests.js file or before your tests.
> > > Here's the mock I use:
> > > ```js
> > > Object.defineProperty(window, 'matchMedia', {
> > >   writable: true,
> > >   value: jest.fn().mockImplementation(query => ({
> > >     matches: false,
> > >     media: query,
> > >     onchange: null,
> > >     addListener: jest.fn(), // deprecated
> > >     removeListener: jest.fn(), // deprecated
> > >     addEventListener: jest.fn(),
> > >     removeEventListener: jest.fn(),
> > >     dispatchEvent: jest.fn(),
> > >   })),
> > > });
> > > ```
> > > 
> > > 
> > > [source](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)
> > 
> > 
> > Receiving the following error after using this mock object:
> > ```
> > TypeError: mql.addListener is not a function
> > ```
> 
> I have the same probelm. have you solved it?

I fixed it by removing `jest.resetAllMocks()` in my `afterEach()`

**Comment by AO19** [comment]
I'm now getting `TypeError: Cannot read property 'addListener' of undefined`.

**Comment by bouncydragon** [comment]
still no solution??

`"react": "17.0.1",`
`"@types/react": "16.9.56",`
`"react-test-renderer": "16.13.0",`
`"@types/react-test-renderer": "16.9.2",`
`"antd": "4.8.2",`
`"typescript": "4.0.5",`
`"@types/jest": "25.1.4",`


> `import { render as rtlRender } from '@testing-library/react';`
> `import { Provider } from 'react-redux';`
> 
> `const TestProvider = ({ store, children }) => (`
>  `<Provider store={store}>{children}</Provider>`
> `);`
> 
> `const renderWithState = (ui, { store, ...opt }) =>`
>  `rtlRender(<TestProvider store={store}>{ui}</TestProvider>, 
> );`


<img width="876" alt="Screen Shot 2020-11-11 at 5 45 38 AM" src="https://user-images.githubusercontent.com/9712523/98737467-30e72300-23e1-11eb-9e3e-673f84231beb.png">

**Comment by AO19** [comment]
This worked for me:

```js
global.matchMedia = global.matchMedia || function () {
  return {
    matches: false,
    addListener: jest.fn(),
    removeListener: jest.fn(),
  };
};
```

More here #27658

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/27658#issuecomment-723954128

**Comment by tambaqui** [comment]
This also works for `Error: Uncaught [TypeError: Cannot read property 'addListener' of undefined]`:

```javascript
Object.defineProperty(window, 'matchMedia', {
    value: () => {
      return {
        matches: false,
        addListener: () => {},
        removeListener: () => {}
      };
    }
})
```

**Comment by cn-80** [comment]
@tambaqui thank you it fixed my problem, it should be part of antd docs :100:

**Comment by seong7** [comment]
@tambaqui  Thank you so much. You saved me.

**Comment by skaunov** [comment]
totally,
quite similar solutions didn't work out for the project I'm busy with
and this one helped
> @tambaqui thank you it fixed my problem, it should be part of antd docs 100

**Comment by Abhishek-K-Forcebolt** [comment]
> You can fix this by mocking the window.matchMedia method in the setupTests.js file or before your tests. Here's the mock I use:
> 
> ```js
> Object.defineProperty(window, 'matchMedia', {
>   writable: true,
>   value: jest.fn().mockImplementation(query => ({
>     matches: false,
>     media: query,
>     onchange: null,
>     addListener: jest.fn(), // deprecated
>     removeListener: jest.fn(), // deprecated
>     addEventListener: jest.fn(),
>     removeEventListener: jest.fn(),
>     dispatchEvent: jest.fn(),
>   })),
> });
> ```
> 
> [source](https://jestjs.io/docs/en/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom)

Why this error came, and how this code works?

**Comment by huynhkimtri** [comment]
Thank you so much. You saved me.

**Comment by yanlimabarbosa** [comment]
this was what worked for me, since vi.fn() wasn't working, i mocked the browser behavior for the respective functions:

```typescript
const createMatchMediaMock = (matches: boolean) => {
  const listeners: Array<(e: { matches: boolean }) => void> = []

  return {
    matches,
    media: '',
    onchange: null,
    addListener: (callback: (e: { matches: boolean }) => void) => {
      listeners.push(callback)
      callback({ matches })
    },
    removeListener: (callback: (e: { matches: boolean }) => void) => {
      const index = listeners.indexOf(callback)
      if (index > -1) {
        listeners.splice(index, 1)
      }
    },
    addEventListener: (
      type: string,
      callback: (e: { matches: boolean }) => void,
    ) => {
      if (type === 'change') {
        listeners.push(callback)
        callback({ matches })
      }
    },
    removeEventListener: (
      type: string,
      callback: (e: { matches: boolean }) => void,
    ) => {
      if (type === 'change') {
        const index = listeners.indexOf(callback)
        if (index > -1) {
          listeners.splice(index, 1)
        }
      }
    },
    dispatchEvent: vi.fn(),
  }
}

Object.defineProperty(window, 'matchMedia', {
  writable: true,
  enumerable: true,
  value: () => createMatchMediaMock(false),
})
``` 

after that almost all of the tests got fixed, and the ones who didn't, it was cz of timeout, setting `testTimeout: 10000` on vite.config.js fixed it
