### ISSUE TITLE
Using Switch doesn't trigger change event

### ISSUE THREAD

**Issue by Belgian93** [ant-design/ant-design#21090]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rough-silence-upzij)

### Steps to reproduce
Use the switch or the slider, no changes logged in console.
Using Input will update the changes

### What is expected?
For the boolean change to be logged in console

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.8.6 |
| System | Ubuntu 18.04 |
| Browser | Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
`onChange` => `onValuesChange`: https://codesandbox.io/s/charming-waterfall-cw3zt
