### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by wangytangy** [ant-design/ant-design#21094]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://spectrum.chat/next-js/general/the-problem-in-integrating-next-js-with-ant-ui-when-customizing-ant-themes~bdc65d8d-ad92-4ec0-8469-f31269b85bc6](https://spectrum.chat/next-js/general/the-problem-in-integrating-next-js-with-ant-ui-when-customizing-ant-themes~bdc65d8d-ad92-4ec0-8469-f31269b85bc6)

### Steps to reproduce
```
import Button from 'antd/es/button';

render () {
  return (<Button />);
}
```

### What is expected?
The button should render correctly.

### What is actually happening?
The webpage cannot load because of a Javascript syntax error: "Uncaught SyntaxError: Cannot use import statement outside a module"

The webpack bundle shows the error here:

/***/ (function(module, exports) {

	import Button from './button'; // <----- ERROR
	import ButtonGroup from './button-group';
	Button.Group = ButtonGroup;
	export default Button;
	//# sourceMappingURL=index.js.map

/***/ }),

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.8.4 |
| System | macOS High Sierra v0.13.6 |
| Browser | Chrome Version 79.0.3945.88 |

**Comment by arvinsim** [comment]
I have the same problem as above. Thought that for CRA + Ant Design, component testing should work out of the box.

**Comment by arvinsim** [comment]
@wangytangy [This](https://www.jianshu.com/p/02ac46867815) is a solution that worked for me.

**Comment by patelrikin** [comment]
@arvinsim are you able to post any snippet here since the link that you shared is 404'ing and possibly external links may not be counted on in terms of availability in future.

**Comment by irux** [comment]
@arvinsim could you post your solution again? I can't see the link you posted.

**Comment by Jplus2** [comment]
How to solve this for cases not using babel? using ts-jest.
