### ISSUE TITLE
Input suffix / prefix doesn't work in conjunction with addonBefore / addonAfter

### ISSUE THREAD

**Issue by chillyistkult** [ant-design/ant-design#21099]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-buck-xytok)

### Steps to reproduce
Add suffix / prefix together with addonBefore / addonAfter prop to Input

### What is expected?
Suffix / Prefix renders correctly

### What is actually happening?
Suffix / Prefix renders above the actual input

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.12.0 |
| System | OS X Catalina 10.15.2 |
| Browser | Chrome 79.0.3945.130 |

---
Worked in antd 3.X.X

**Comment by bijeshp** [comment]
Do we have a solution for this?
Doesn't seems to be working in `4.9.3`
