### ISSUE TITLE
Discussion about getFieldDecorator function in Form Component

### ISSUE THREAD

**Issue by kushalmahajan** [ant-design/ant-design#21098]
| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.8.x |
| System | MacOS |
| Browser | Chrome |

---
This is not a bug or feature request rather a general question about the usage of API of Form component. 

Okay, If you notice below snippet from https://ant.design/components/form/#Form-Component

```
{getFieldDecorator('username', {
    rules: [{ required: true, message: 'Please input your username!' }],
    })(
    <Input
        prefix={<Icon type="user" style={{ color: 'rgba(0,0,0,.25)' }} />}
        placeholder="Username"
    />
)}
```

It uses a `getFieldDecorator`, I'm assuming it decorates the underlying component ( field ) with name and makes use of rules array somewhere or somehow. 
Now, the same thing can be done with just passing rules array as a prop to Form Item i.e. ` <Form.Item rules={[]}>`.  

Assuming that I'm considering my fieldErrorState to be in Form component itself. On every change of field, it will update that same state via callbacks ( supporting unidirectional flow ). 

So, just curious to know what is the thought process for doing this the way it is done for Ant Design engineers?

**Comment by zombieJ** [comment]
You can get with #20661 about Form part. `Form.create` & `getFieldDecorator` is  a slightly redundant API. Form.Item handle the error display which is strongly coupling with `getFieldDecorator`. Developer have to wrapper their own code with both Form.Item & `getFieldDecorator` which can be simplify.
