### ISSUE TITLE
Differentiate between onCancel and onClose events in modal

### ISSUE THREAD

**Issue by thimovss** [ant-design/ant-design#21097]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently there is no proper way to differentiate between whether the close button ( x ) is clicked, or the cancel button is clicked in the `onCancel` event.

For our use case we use the modal to notify the user that they have unsaved changes and provide them the options: 'discard changes', our cancel button, and 'save changes' which is our Ok button.

When the user presses the close ( x ) button, we would like to close the modal so the user can continue editing the form without saving or discarding their changes.

To realize this we have to be able to differentiate between a click on the cancel button and the close button.

### What does the proposed API look like?
Already existing `onCancel` event will not happen when the user clicks the close button ( X ).
Additional `onClose` event is added to the Modal, which happens when the user clicks the close button ( X )

Optional: Also separate the event for when the user has clicked the mask

**Comment by thimovss** [comment]
Temporary work-around until this feature is implemented,
Add `id` prop to the `cancelButtonProps`,  
```jsx
cancelButtonProps={{ id: 'discardButton' }}
```
And check for the id in the `onCancel` to differentiate between the events.
```jsx
onCancel={(e) => {
  if(e.currentTarget.id === 'discardButton') {
    ...
  } else {
    ...
  }
}
```

**Comment by zombieJ** [comment]
`x`, `cancel` & `backdrop` should be the same logic in work progress. In your design system, you should  both trigger double confirm with `x` & `cancel` button.

We may not provide source type. But your solution is OK.

**Comment by netojose** [comment]
> Temporary work-around until this feature is implemented, Add `id` prop to the `cancelButtonProps`,
> 
> ```js
> cancelButtonProps={{ id: 'discardButton' }}
> ```
> 
> And check for the id in the `onCancel` to differentiate between the events.
> 
> ```js
> onCancel={(e) => {
>   if(e.currentTarget.id === 'discardButton') {
>     ...
>   } else {
>     ...
>   }
> }
> ```

I don't know about the time when this was proposed, but today (v 5.17.2), this doesn't work anymore

**Comment by SevakKhnkoyan** [comment]
I have the same case with unsaved changes.
Here is how I differentiated
`const leave = () => {
    ...
    setIsOpenModal(false);
  };
  
const handleXClick = (e) => {
    e.stopPropagation();
    setIsOpenModal(false);
  };
 <Modal
 ...
        onCancel={leave}
        closeIcon={<i onClick={handleXClick} ,,, />}
      >`
