### ISSUE TITLE
How disable multi rows with getCheckboxProps (from rowSelection)

### ISSUE THREAD

**Issue by by-cgonzalez** [ant-design/ant-design#21091]
Hi Guys,

I am trying to disable rows from my table, but for now just can disable just one with `getCheckboxProps: (record) => 
    ({      
      disabled: record.name === 'Disable'    
    }),`. This is from rowSelection: 
```js
const rowSelection = {
    onChange: (selectedRowKeys, selectedRows) => {   
      setSelectedRowKeys(selectedRowKeys);      
    },
    getCheckboxProps: (record) => 
    ({      
      disabled: record.name === 'Disable' , // Column configuration not to be checked    
    }),
  };
```

So, I need to disable this from a array or somthing that contain the values to disable.

Thank you in advance!

**Comment by rishad-spenmo** [comment]
For anyone looking for a solution for this particular issue,

```
const rowSelection = {
     getCheckboxProps: (selectedRowKeys) => {
            return {
                disabled: selectedRowKeys.name === "John" // This disables the checkboxes of row with name "John" 
            };
  }
```
