### ISSUE TITLE
Select.option not setting key, getting value as key

### ISSUE THREAD

**Issue by paulohpf** [ant-design/ant-design#21092]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/paulohpf/pen/WNbPmEr?editors=0010](https://codepen.io/paulohpf/pen/WNbPmEr?editors=0010)

### Steps to reproduce
Just open the console and click on select

### What is expected?
When the key is setted in option it overrides the value as key

### What is actually happening?
When the key is setted it actualy ignored in render

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome 79.0.3945.117 |

---
I think it's a bug

**Comment by zombieJ** [comment]
Your options have multiple same `value` like `7` which should be unique in Select.
