### ISSUE TITLE
typescript-antd-react-redux-starter

### ISSUE THREAD

**Issue by bang88** [ant-design/ant-design#2109]
Hello,This is an example use antd with typescript.

[repo](https://github.com/bang88/typescript-react-redux-starter)

[demo](https://bang88.github.io/typescript-react-redux-starter)

By the way,I use VSCode editor ,it works very well.  :smiley:

**Comment by benjycui** [comment]
It will be better to open a pull request to update antd's documentation.

**Comment by benjycui** [comment]
How about this? @afc163 

http://ant.design/docs/react/getting-started#1. 安装脚手架工具

![image](https://cloud.githubusercontent.com/assets/3580607/16215387/5f676ae8-3794-11e6-91e9-f8128c1eecbe.png)

**Comment by afc163** [comment]
可以有，找几个最好的，然后把 https://github.com/ant-design/ant-design/issues/129 链接贴到最后。

**Comment by bang88** [comment]
@afc163 你的邮件收不到吗？
能不能先发布个版本 解决一下这个问题。 https://github.com/ant-design/ant-design/commit/56a2e2d9842e41e7bf54615a635855d156de185f

**Comment by afc163** [comment]
发了一个 1.5.1

**Comment by bang88** [comment]
谢谢。
