### ISSUE TITLE
Modal.info、Modal.success、Modal.xxx 可以添加关闭接口嘛？

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#2110]
在 SPA 应用里考虑这样的一个场景：
在当前页面做了某个操作后，触发了 `Modal.info`，用来提示一些信息，然后一个不小心点了后退按钮，跳转到另外一页，此时这个 Modal.info 还是存在页面上的，没有被关闭掉。

如果 `Modal.info` 有返回 `close` 接口，那么就可以在触发 `Modal.info`的组件被销毁时，也将`Modal.info` 也给关闭掉。

另外，看来下源码，如果在[/components/modal/confirm.jsx L132](https://github.com/ant-design/ant-design/blob/master/components/modal/confirm.jsx#L132)前稍微修改，应该就可以满足需求了，如下：

- 法1）将内部的 `close` 函数返回
- 法2）在渲染后的组件实例上，添加 `close`方法，并且返回改组件实例

**Comment by leejaen** [comment]
同样需要

**Comment by afc163** [comment]
类似 message 和 notification 加上 destory 方法好了。

**Comment by RaoHai** [comment]
`Modal.destroy()` 一次销毁全部？

还是 

```jsx
var modal = Modal.info({});
modal.destroy();
```

**Comment by afc163** [comment]
后者好一点。

**Comment by ystarlongzi** [comment]
期待

**Comment by codering** [comment]
这种场景下，组件自身没法自动销毁吗？
