### ISSUE TITLE
Export Number component for wider use

### ISSUE THREAD

**Issue by freethejazz** [ant-design/ant-design#21104]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The `StatisticNumber` component used within `Statistic` component has nice features around displaying numbers, but currently can only be used via a `Statistic` component. This simple `StatisticNumber` component, if exported for wider use, could allow for uniform number formatting for display purposes throughout applications whether they need labels or not. In order to have the same number formatting API regardless of whether the number exists within a `Statistic` or other elements, I'd have to copy-paste the internals of the `StatisticNumber` component and keep my custom component up to date with the library across version updates.

**The end user experience is that all numbers, whether they're in statistics or tables or paragraphs can be viewed in a uniform and consistent format.**

### What does the proposed API look like?
This could be as simple as adding the following code to `components/statistic/index.tsx` and updating documentation:
```
import StatisticNumber from './Number';

Statistic.FormattedNumber = StatisticNumber;
```

However, it's possible the classes assigned in the `StatisticNumber` component may have some meaning that only makes sense to Statistics. If that were the case, it may be worth extracting the full formatting logic into a utility function that's imported both into `statistics/Number.tsx` and a separate, net-new `FormattedNumber` component (name up for debate), that can be used anywhere a `span` can be used.

**Comment by keithort** [comment]
Number is a native JavaScript object so this would have to go by another name.

**Comment by freethejazz** [comment]
Updated the description to account for clashes with built-ins and fix incorrect references to the `Number` component, which is actually named `StatisticsNumber` within the `Number.tsx` file.

**Comment by zombieJ** [comment]
Hi, you can use `className` to [customize style](https://codesandbox.io/s/lively-firefly-n10oz) or import from `antd/lib/statistic/Number`.

We may not export this component since it's a raw component if refactor need to adjust this. And not willing to export this as an official component yet.
