### ISSUE TITLE
InputNumber should have thousand separator 

### ISSUE THREAD

**Issue by ranjanach1983** [ant-design/ant-design#21100]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi,
Please include thousand separator into InputNumber it will help us to use thousand separator according to different locale. Currently facing issues to use different DecimalSeparator for different locale after inclusion of Thousand separator. Please help so that can have thousand separator. 
Thanking you
Ranjan

### What does the proposed API look like?
currency should look like if I use decimalSeparator as ',' 234.556,44 here dot as thousand separator and comma as decimalSeparator

**Comment by zombieJ** [comment]
https://ant.design/components/input-number/#components-input-number-demo-formatter
