### ISSUE TITLE
DatePicker / Calendar UX improvement

### ISSUE THREAD

**Issue by JesusTheHun** [ant-design/ant-design#21117]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Selecting a date that is not within the default month requires to intellectually leave the focus on the calendar to select a month or a year, before refocusing again.

### What does the proposed API look like?
Adopting a lateral scrollable months & year would be tremendous leap forward in term of UX.

Look this component for example : https://www.telerik.com/kendo-react-ui/components/dateinputs/calendar/
This calendar allow you to scroll to visit others months. Super intuitive and amazing UX.

**Comment by zombieJ** [comment]
Thanks for feedback. antd Calender, DatePicker, RangePicker is at same base of design and may not follow other design system. You can use component in your example directly.
