### ISSUE TITLE
Jumpy TimePicker dropdown

### ISSUE THREAD

**Issue by paulmorar** [ant-design/ant-design#21115]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/time-picker/](https://next.ant.design/components/time-picker/)

### Steps to reproduce
1. Click on a TimePicker
2. Hover around on the elements displayed in the dropdown

### What is expected?
The UI should be consistent and not jump around.

### What is actually happening?
Whenever you hover an element from the dropdown, the scrollbar appears and pushes the text. This is bad from a UX perspective.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | React |
| System | Any, but in my case Windows 10(10.0.17134) |
| Browser | Chrome Version 79.0.3945.130 |

---
I don't see this as a critical bug, but a bug nonetheless.

**Comment by zombieJ** [comment]
This design is for that customize style with narrow width column number covered by scrollbar, so we use align center instead. We have the plan to optimize this when css for customize scroll bar to be a standard.

Close since currently may have no action on this.

**Comment by paulmorar** [comment]
I think it is weird that you leverage future optimizations in detriment of UX.
But that is fine ... I guess. Thanks for the reply.
