### ISSUE TITLE
Useless displaynames for base Layout components

### ISSUE THREAD

**Issue by nathanrpage97** [ant-design/ant-design#21120]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently the display names for Layout components: Header, Content, Footer render as Adapter instead of a readable name. This becomes an issue when looking through react-devtools to find these components.

### What does the proposed API look like?
Setting the displayname of Header, Content, and Footer to make it more obvious to find these layout components.

**Comment by zombieJ** [comment]
PR is welcomed.

**Comment by morenyang** [comment]
I can take a look on this issue.
