### ISSUE TITLE
穿梭框Transfer在数据量几千（还可以更大，此处只给个下限）卡顿（死）的情况

### ISSUE THREAD

**Issue by dreamcatcher081210** [ant-design/ant-design#2112]
如题，在数据量比较大时几千条会出现卡顿情况，不是一般的卡，有没有什么优化的方案吗？用户体验太不友好了，严重影响了客户的使用，我自己测试用的是6000的量

**Comment by warmhug** [comment]
看来只要是可能涉及到大量数据的组件、都需要进行下压测。。

**Comment by bang88** [comment]
别全部列出来，异步加载。 再加个搜索框。。

**Comment by dreamcatcher081210** [comment]
大数据量会不可避免的出现类似的问题，

**Comment by afc163** [comment]
优化了渲染过程中的部分性能。

**Comment by afc163** [comment]
这里还有个重复 render 的问题，改完快了很多。
