### ISSUE TITLE
如何使用ssr服务端渲染方式

### ISSUE THREAD

**Issue by ClearSeve** [ant-design/ant-design#21122]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我想用ant Design 做博客系统,要处理seo相关的问题, 经过查阅后发现, 用服务端渲染的方式, 但是在互联网上查阅很多资料也没能找到可用的办法. 在ant design 文档中发现这个框架也支持服务端渲染, 包括dva的文档也去查阅过,但是还是没有找到答案

### What does the proposed API look like?
希望能找到解决方案

**Comment by yoyo837** [comment]
antd只需要支持ssr即可，项目里如何实现ssr和antd无关。

**Comment by ClearSeve** [comment]
> antd只需要支持ssr即可，项目里如何实现ssr和antd无关。

antd不是支持dva,  dva文档中也没有相关服务端渲染的文档，我在antd文档中看到使用dva ssr

**Comment by yoyo837** [comment]
你应该去看React的文档，比如https://reactjs.org/docs/react-dom-server.html，但通常正如你UI使用antd一样，为了快速开发，一般都基于一些封装好的、开箱即用的库来做，比如next.js

**Comment by zhangyuang** [comment]
https://github.com/ykfe/ssr/blob/dev/packages/plugin-react/src/config/server.ts#L62
https://github.com/ykfe/ssr#%E4%BD%BF%E7%94%A8-ui-%E6%A1%86%E6%9E%B6

不知道怎么配置的，参考这个配置。或者给该框架提issue

 
![image](https://user-images.githubusercontent.com/17424434/109802819-3f409f80-7c5b-11eb-94ee-3bff15ab216c.png)
