### ISSUE TITLE
Checkbox group not working inside collapse and panel components

### ISSUE THREAD

**Issue by manashemrajani** [ant-design/ant-design#21134]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ecrzxl](https://stackblitz.com/edit/react-ecrzxl)

### Steps to reproduce
* Please open https://stackblitz.com/edit/react-ecrzxl.
* Expand any of the collapsed panels
* Check any of the checkboxes
* The checkbox will not show a check even though the console shows it in checkedValues 

### What is expected?
The Checkbox should show a tick or check mark in the checkbox when clicked.

### What is actually happening?
The Checkbox remains blank when clicked as if it didn't become checked.

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.o |
| System | macOS 10.12 |
| Browser | Chrome 79.0.3945.130 |

**Comment by afc163** [comment]
```diff
-    <Checkbox.Group style={{ width: '100%' }} onChange={this.onChange}>
+    <Checkbox.Group style={{ width: '100%' }} onChange={onChange}>
```

**Comment by afc163** [comment]
Reproduce demo: https://stackblitz.com/edit/react-ecrzxl-a2d79n?file=index.js

**Comment by morenyang** [comment]
I can take a look on this issue.

**Comment by morenyang** [comment]
For PR https://github.com/ant-design/ant-design/pull/21155, 
for React context API polyfill, the most direct way is to wrap the `Checkbox` component by `Context.Consumer` and passing the context throw props:

```tsx
// Group
export const GroupContext = createContext<{ checkboxGroup: any }>({
  checkboxGroup: undefined,
});

// Checkbox
const WrappedCheckbox = (props: CheckboxProps) => (
  <GroupContext.Consumer>
    {context => <Checkbox {...props} groupContext={context} />}
  </GroupContext.Consumer>
);

export default WrappedCheckbox;
```

But it's not a good way in terms of code style and structure. 
So... is there any other good solution for this case?
