### ISSUE TITLE
There should be "二" instead of "三"

### ISSUE THREAD

**Issue by juzhiyuan** [ant-design/ant-design#21130]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/upload-cn/](https://next.ant.design/components/upload-cn/)

### Steps to reproduce
完全控制的上传列表
使用 fileList 对列表进行完全控制，可以实现各种自定义功能，以下演示三种情况：

上传列表数量的限制。

读取远程路径并显示链接。

### What is expected?
二

### What is actually happening?
三

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | Any |
| System | Chrome |
| Browser | Chrome |

**Comment by yoyo837** [comment]
ref: #16390
