### ISSUE TITLE
The ValidationRule for Antd Form is not consistent with async-validator

### ISSUE THREAD

**Issue by hansololai** [ant-design/ant-design#21143]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-stjc0)

### Steps to reproduce
This is a demo of the code one could import from async-validator's rules and try to use them in antd form. 

### What is expected?
The RuleItem Type defined in async-validator should be compatible with Antd's ValidationRule, after all, the async validator is the validation package used by antd. 

### What is actually happening?
The RuleItem and ValidationRule are not assignable. RuleItem's enum definition is different from Antd's ValidationRule. 

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.9 |
| System | Mac OSX |
| Browser | Chrome |

**Comment by hansololai** [comment]
I was going to make a PR for this, but then I found out the feature branch of Antd is on 4.0-rc. Which have already fixed this problem.  So this problem only exists on Antd 3, which I guess there is no need to make a PR for it.

**Comment by yoyo837** [comment]
`master` = 4.0
`3.x-stable` = 3.x

**Comment by hansololai** [comment]
@yoyo837 Thanks, so do I just make PR to 3.x-stable? The bot ask me to PR to feature branch, which is 4.0-rc.

**Comment by yoyo837** [comment]
If it is not a feature request, the fix PR can be sent individually to each branch to be modified.

**Comment by yoyo837** [comment]
If it is a feature request, `3.x-stable` will not accept it.

**Comment by hansololai** [comment]
After some investigation, I found out the `rc-form` package that Antd uses still depends on an old version of `async-validator` (1.11.5), the validation rules that I used now were based on `async-validator` 3.1.0, no wonder they cannot be assigned. I think the problem here is that rc-form needs to be updated with newer async-validator.

**Comment by yoyo837** [comment]
#21250 was reverted by #21391, so reopen this.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/21250#issuecomment-586468957

4.0 already handled this issue
