### ISSUE TITLE
checkbox的disabled状态样式显示不太友好

### ISSUE THREAD

**Issue by leejaen** [ant-design/ant-design#2114]
disabled是可不可以将其后跟着的span也置灰，这样可以一眼让人看出不可点，现在的状态只有前面的选框是灰色，后面span是黑色，下意识的点击span期望勾选到checkbox但是无效果，等鼠标移动到checkbox会出现不可点样式，改进下是否更好？

![image](https://cloud.githubusercontent.com/assets/1638970/16214676/61eefe5e-378d-11e6-8983-fde6cd55c7ad.png)

```
.ant-checkbox-disabled+span {
    color: #aaa;
    cursor: not-allowed;
}
```

**Comment by afc163** [comment]
`#ccc` @ddcat1115
