### ISSUE TITLE
DatePicker calendar icon is not clickable

### ISSUE THREAD

**Issue by hugomn** [ant-design/ant-design#21149]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd400-datepicker-1xxbe)

### Steps to reproduce
1. Click the calendar icon in the DatePicker component

### What is expected?
The picker input should open

### What is actually happening?
The pick input is not opening

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.8.6 |
| System | OSx |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`+ rc-picker@0.0.1-rc.3`

**Comment by afc163** [comment]
Current behavior is still not same as 3.x, which should open DatePicker.

**Comment by afc163** [comment]
Cursor pointer is not same too.

**Comment by afc163** [comment]
<img width="190" alt="image" src="https://user-images.githubusercontent.com/507615/73834001-e5965780-4845-11ea-8e86-fc42a08a179a.png">

Clicking the padding area does not open picker either, which should.

**Comment by afc163** [comment]
> Clicking the padding area does not open picker either, which should.

Input.Password has same issue: https://next.ant.design/components/input-cn/#components-input-demo-password-input

**Comment by afc163** [comment]
@zombieJ You can check this one

**Comment by zombieJ** [comment]
Will create a new issue for Input

**Comment by achillescs** [comment]
Range picker still has the same issue. RangePicker calendar icon is not clickable.
It is working fine in DatePicker but still calendar icon is not clickable in **RangePicker**

antD version - 4.1.4
https://ant.design/components/date-picker

**Comment by achillescs** [comment]
> Will create a new issue for Input

Range picker still has the same issue. RangePicker calendar icon is not clickable.
It is working fine in DatePicker but still calendar icon is not clickable in RangePicker

antD version - 4.1.4
https://ant.design/components/date-picker
