### ISSUE TITLE
TimePicker's onChange receives incorrect Moment instance

### ISSUE THREAD

**Issue by vyacheslav-pushkin** [ant-design/ant-design#21140]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ibg9k)

### Steps to reproduce
Select time (different from the current time) in TimePicker.

### What is expected?
Both arguments of TimePicker's onChange callback represent the selected time

### What is actually happening?
The second (string) argument represents the selected time. However, the first (Moment) argument represents a different time which is always the same and apparently is the time when the component was mounted.

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | Ubuntu 18.04 |
| Browser | Google Chrome Version 79.0.3945.88 (Official Build) (64-bit) |

**Comment by Far3t** [comment]
In your CodeSandbox, do you still have your "issue" if you 
`console.log(time.format())`
Working for me to just format it.
Don't know what you're talking about the time not changing, if you can add some details about it

**Comment by vyacheslav-pushkin** [comment]
@Far3t 
You are right, there is no issue, I seem to have misinterpreted the output. 
Thank you for you feedback and your great library.
