### ISSUE TITLE
Collapse Panel scrollbar with extra prop

### ISSUE THREAD

**Issue by rever96** [ant-design/ant-design#21148]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-bh26q?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Create a Collapse with Panels that have extra prop, style the content or the panel with overflow to get the scrolling function

### What is expected?
I expect that the content fill the parent width

### What is actually happening?
the content is wrapped into a margin-right with the same width of the extra

| Environment | Info |
|---|---|
| antd | 3.25.3 |
| React | react 16.12.0 |
| System | linux |
| Browser | chrome |

**Comment by rever96** [comment]
What is the version where I should update to get the clearfix?

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/74223835-84153380-4cf2-11ea-8d75-cc50f6412afb.png)

**Comment by rever96** [comment]
Sry for going out-topic, but....
`Attempted import error: 'Icon' is not exported from 'antd'.`
Did you move the Icon? Where I can find what I should change to update from 3.26.9 to 4.0.0-rc.4?

**Comment by yoyo837** [comment]
Move to "@ant-design/icons": "4.0.0-rc.0",

**Comment by yoyo837** [comment]
See #12011  #20661
