### ISSUE TITLE
expandIcon not rendering without children key for Table component

### ISSUE THREAD

**Issue by vatsal-noovosoft** [ant-design/ant-design#21154]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-murdock-r2x2x)

### Steps to reproduce
I am trying to move to ant design v4 but it seems that Table component expandIcon behaviour is changed. It is not rendering without specifying children key attribute in the dataSource of Table Component to display Tree data. whereas in the stable version it works without specifying children key.

Here is the comparison:

1) **Antd next v4 beta**
Antd Next  (Not working without specifying children key in the dataSource)
https://codesandbox.io/s/eloquent-murdock-r2x2x

2) **Antd next v4 beta**
Antd Next  (Working when specifying children key in the dataSource)
https://codesandbox.io/s/dazzling-chaum-pdu7k

3) **Stable version v3**
Antd latest (Working without specifying children key in the dataSource)
https://codesandbox.io/s/icy-bird-kqivz

### What is expected?
Expected to render expandIcon using antd next latest version without specifying children key in the dataSource

### What is actually happening?
Not rendering  expandIcon using antd next latest version without children key in the dataSource

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | latest |
| System | Mac OS 10.15 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Hmmm... v4 optimize the check logic to speed up perf but it will not provides icon when all the element don't have `children` yet.
We may need rollback the optimization.
