### ISSUE TITLE
Button component should have success or Green colour button

### ISSUE THREAD

**Issue by krishangoelmt** [ant-design/ant-design#21157]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
want to introduce success button and the user will pass type="success" and colour of that turns into green

### What does the proposed API look like?
pass props called "success" on the basis of that turns into green

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/4770#issuecomment-278217817
