### ISSUE TITLE
Word wrap in Menu.Item

### ISSUE THREAD

**Issue by tiagowippel** [ant-design/ant-design#21151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

Hi, it is possible to apply word-wrap in a Menu.Item component ?

### Reproduction link
[https://codepen.io/tiagowippel/pen/LYEKYbb?editable=true&editors=001](https://codepen.io/tiagowippel/pen/LYEKYbb?editable=true&editors=001)

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | Windows 10 PRO x64 |
| Browser | Chrome 79.0.3945.130 |

**Comment by afc163** [comment]
It cannot now, menu item is designed to be this way.
