### ISSUE TITLE
DatePicker (with showTime= true and showToday=false) should hide Now like Today

### ISSUE THREAD

**Issue by gitter-me** [ant-design/ant-design#21159]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-tdd-ecw9t)

### Steps to reproduce
Use a DatePicker with showTime.
Set showToday to false, and open the picker.

### What is expected?
The now button should be gone

### What is actually happening?
The now button is still visible

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | independent |
| System | independent |
| Browser | independent |

---
Alternatively there could be a property named showNow
But since both props would do the same

**Comment by zombieJ** [comment]
`showNow` seems better since TimePicker should also add this prop for control.

**Comment by gitter-me** [comment]
@zombieJ A bit off-topic but is there a way to have the picker accept the value without clicking on the ok button (if time is visible)?

**Comment by zombieJ** [comment]
OK button is must have in DataPicker with showTime since diff with DatePicker only there is no way to know what's the final value user select.

**Comment by hbarcelos** [comment]
Are there any updates here? Will this `showNow` option be included any time soon?

I have a use case where dates MUST be in the future.
I use `disabledDate`, so the dates which are not in the future are not selectable, but the `now` button still works and inputs the current date, even though it's invalid.

What I did was to add a custom validation rule to ensure the user cannot submit a wrong date.

Any other possible workarounds for now?

**Comment by JackLLLLL** [comment]
any updates? @afc163
I also ran into this issue but couldn't find any solution.

**Comment by OmkoBass** [comment]
showNow prop for TimePicker and DatePicker would be a good addition. I also have this problem.

**Comment by balmacefa** [comment]
I disable the button via css 😫

less:

Use :global to prevent webpack change the class name
`.datePickerStyle {
  :global {
    .ant-picker-now{
      display: none;
    }
  }
}`

tsx:
`<DatePicker
                dropdownClassName={styles.datePickerStyle}
              />`

**Comment by OmkoBass** [comment]
.ant-picker-now-btn {
    display: none;
}

This will fix the problem.

**Comment by balmacefa** [comment]
I'm using the showTime-options object ( https://github.com/react-component/picker#showTime-options ), I don't see and option to disable the now button. When `showTime=false` seens to be work ok.
