### ISSUE TITLE
能否手动设置form校验的结果？

### ISSUE THREAD

**Issue by sgdba** [ant-design/ant-design#2115]
有些校验放到rules里不太好做，所以想手动校验，校验的结果能否象内置的校验那样自动设置元素的反馈效果？主要是不想手动设置每一个item的validateStatus。其实就是想有个类似setFieldError之类的函数，传入field名称和错误信息，form自动反馈出相应的效果。看文档的话好象有个setFields，不过一直没试成功

**Comment by benjycui** [comment]
使用场景？

**Comment by sgdba** [comment]
密码和确认密码两个输入框，先输入密码，再输入确认密码，如果两者不一致能检查到，这时候没问题。此时如果我修改密码输入框中的内容，这时候密码输入框中的内容与密码确认框中的内容就不一致了，可是validator检查不到。这时候我就要手动校验

**Comment by benjycui** [comment]
参考下这个例子吧 http://ant.design/components/form#components-form-demo-validate-customized

**Comment by lixiaoyang1992** [comment]
给你个栗子：

有个Input {...getFieldProps('verify'}

手动校验后加提示：
this.props.form.setFields({
                verify: {
                  errors: [{
                    field: "verify",
                    message: "验证码错误"
                  }]
                }
              });
