### ISSUE TITLE
InputNumber does not explicitly define the input type as number

### ISSUE THREAD

**Issue by specialorange** [ant-design/ant-design#21158]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-no-input-type-for-input-number-oduyv)

### Steps to reproduce
you must include `type=number` explicitly, which is an antipattern to having an InputNumber component

### What is expected?
the component should declare itself as `type='number'` input itself

### What is actually happening?
the component does not have a type of `number`

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | react |
| System | all |
| Browser | All |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17344#issuecomment-506376039

**Comment by specialorange** [comment]
This is not related.   #17344 was the case because the value included the % sign.    This case is about clearly including the `type="number" directly into the input as there are two distinct Components: [Input and InputNumber]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9421
