### ISSUE TITLE
Clear antd 4.x Selection programmatically

### ISSUE THREAD

**Issue by kaikun213** [ant-design/ant-design#21161]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-40-select-clear-bug-qjpv3)

### Steps to reproduce
1. Select a value in the selection field
2. Clear the value of the Selection field by setting it to null programmatically (e.g. via Button).
3. The value will be set to null but the Selection field will still display the most recent selected value.
4. Clearing the field is only possible via the allow clear user interaction button.

### What is expected?
It is expected that the Selection field (value that is shown) is also cleared when the value is set to null. This was the case in antd 3.x.

### What is actually happening?
The shown value is not cleared.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by morenyang** [comment]
try to fix in https://github.com/react-component/select/pull/453

**Comment by yoyo837** [comment]
ref: #20979 react-component/select#443

**Comment by morenyang** [comment]
Here's the scene of antd 3.x
https://codesandbox.io/s/antd-select-clear-0yurp

![image](https://user-images.githubusercontent.com/15653996/73595151-1a599480-4550-11ea-801f-7ac9f9a47774.png)

**Comment by zombieJ** [comment]
Yes. https://github.com/react-component/select/pull/443 missing the `null` value. Let me patch.

**Comment by Babyshalini1995** [comment]
Hi,
This issue still exists in 4.x version. Please help us in fixing the same.

Thanks,
Shalini

**Comment by FradaL** [comment]
> Hi,
> This issue still exists in 4.x version. Please help us in fixing the same.
> 
> Thanks,
> Shalini

this is working for me
you should look it https://stackoverflow.com/questions/55863880/ant-design-reset-select/64077769#64077769

**Comment by MironV** [comment]
I'm still having this issue where you cannot clear `Select` using `value`.

**Comment by PigTom-c** [comment]
Is this problem solved now?

**Comment by yujo11** [comment]
Is it on going issue?

**Comment by Gaeun-Kwon** [comment]
Hi, I solved this issue by force re-rendering `Select` component using key.

[dropdown](https://github.dev/ant-design/ant-design/blob/master/components/select/style/dropdown.tsx) with Select component:

1. created when first clicked 
2. display: none when onBlur
3. display: block when clicked again
4. repeat above 2,3 steps

and still have hover context (couldnt find the reason) & it's not destroyed by giving `null` value to `Select`.

So I gave key to `Select` and increased key when I clear selected value.
then dropdown in `Select` is newly created each time. 

(not sure it is the best way to solve this problem. it just works for now.)

**Comment by persunde** [comment]
>I'm still having this issue where you cannot clear Select using value.
Me to, but I was able to solve it by forcing a re-render by changing the "key" prop value when the value was cleared aka set to null or undefined.

**Comment by vonKaster** [comment]
This keeps happening, any solution working?

**Comment by jcgato93** [comment]
Still happening

**Comment by monolithed** [comment]
Leaving this comment so I don’t forget it myself.
If the issue occurs with `react-hook-form` — just use the `Controller` component. Here’s an example:

```ts
import {Controller, useForm} from 'react-hook-form';

... 

const {control, reset} = useForm<FormPayload>();

...

 <Controller name="example"
                control={control}
                render={({field}) => (
                    <Select {...field}
                           allowClear={true}
                           defaultActiveFirstOption={true}
                           placeholder={placeholder}
                           options={[
                               {
                                   value: 'topic',
                                   label: '1',
                                   disabled: true
                               },
                               {
                                   value: '2',
                                   label: '2'
                               }
                           ]}
                    />
                )}

...

reset()

```
