### ISSUE TITLE
Don't want to show any icon in info modal or icon should be optional

### ISSUE THREAD

**Issue by krishangoelmt** [ant-design/ant-design#21162]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The icon in info modal should be optional

### What does the proposed API look like?
need to pass prop hideIcon="true" defaultProps = false

**Comment by afc163** [comment]
```
Modal.confirm({
  icon: null,
})
```
