### ISSUE TITLE
Antd Form Issue

### ISSUE THREAD

**Issue by h36ahmed** [ant-design/ant-design#21166]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/h36ahmed/antd-form-issue](https://github.com/h36ahmed/antd-form-issue)

### Steps to reproduce
There is TypeScript issue. Please pull the repo and use VSCode to open the project. Simply go to App.tsx file and you will red underline on Form and Form.Item

### What is expected?
Form & Form.Item is causing type issues. 

### What is actually happening?
Type '{ children: Element[]; style: { marginTop: number; }; }' is not assignable to type 'IntrinsicAttributes & FormProps & RefAttributes<FormInstance>'.
  Property 'children' does not exist on type 'IntrinsicAttributes & FormProps & RefAttributes<FormInstance>'.ts(2322)
Property 'Item' does not exist on type 'ForwardRefExoticComponent<FormProps & RefAttributes<FormInstance>>'

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | mac OS Mojave |
| Browser | Chrome Version 79.0.3945.117  |

**Comment by zombieJ** [comment]
Not get any error:
<img width="1095" alt="截屏2020-02-01下午11 48 24" src="https://user-images.githubusercontent.com/5378891/73594882-7242cc00-454d-11ea-8e47-537422548946.png">

**Comment by h36ahmed** [comment]
@zombieJ Are you sure you are using `4.0.0-rc.3` antd because 3.26.7 has no issues. Its the latest one that is giving errors?
![image](https://user-images.githubusercontent.com/13081913/73600300-0887e980-4570-11ea-9b59-73a41eeebec0.png)

**Comment by zombieJ** [comment]
Typescript of your vscode is out of data:
<img width="138" alt="截屏2020-02-02上午10 59 08" src="https://user-images.githubusercontent.com/5378891/73602216-1a3ab280-45ab-11ea-889c-a656d474b349.png">

Your package:
![Uploading 截屏2020-02-02上午11.00.26.png…]()
