### ISSUE TITLE
[4.x] Different default Table expand icon between 3.x and 4.x

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#21164]
~3.x: https://codesandbox.io/s/divine-leftpad-1qjdk ✅~
3.x: https://codesandbox.io/s/pedantic-oskar-dvd9t ✅
4.x: https://codesandbox.io/s/falling-glade-66vzo ❌

**Comment by afc163** [comment]
#21154

**Comment by zombieJ** [comment]
Should not use `ant-table-row-expand-icon` as customize `className`.
