### ISSUE TITLE
[4.0] Add more sizes to the Input component (xs, xl, xxl)

### ISSUE THREAD

**Issue by mgcrea** [ant-design/ant-design#21173]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Would be great to have more input sizes right out of the box as it's not straightforward to override them.

### What does the proposed API look like?

Would love to have [bootstrap-like breakpoints](https://getbootstrap.com/docs/4.0/layout/overview/):

`xs`, `sm`, `md`, `lg`, `xl`, `xxl`

We could alias existing sizes to these acronyms to prevent any breaking change.

Could work on it if you want.

**Comment by afc163** [comment]
Sorry, our design specification does not contain more sizes.
