### ISSUE TITLE
Antd icons aren't working: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by furrycatherder** [ant-design/ant-design#21171]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-knxvi)

### Steps to reproduce
Use new icons in a React component

### What is expected?
Icons should be displayed

### What is actually happening?
Error
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | latest |
| System | codesandbox |
| Browser | Firefox |

**Comment by zombieJ** [comment]
1. `LockOutline` => `LockOutlined`
2. Version of `@ant-design/icons` should be `4.0.0.rc.x`

**Comment by gevhambarzumyan93** [comment]
I have the same issue. ant 4.0.4, react 16.13.1

after I import { BulbOutlined } from "@ant-design/icons"

Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it’s defined in, or you might have mixed up default and named imports. Check the render method of `COMPONENT_NAME`.
