### ISSUE TITLE
Render issue with <Typography><Comment><Badge></Badge></Comment></Typography>

### ISSUE THREAD

**Issue by sugia** [ant-design/ant-design#21172]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-ganguly-ik9nu?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Puts `<Badge>` with in `<Typography> <Comment>`

### What is expected?
A correct number should be rendered within Badge.

### What is actually happening?
A wroing number is rendered within Badge.

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | Mac 10.14.6 |
| Browser | Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

**Comment by sugia** [comment]
Another experimental result shows that <Badge> renders incorrectly within tag <Typography>
https://codesandbox.io/s/pedantic-ganguly-ik9nu?fontsize=14&hidenavigation=1&theme=dark

**Comment by zombieJ** [comment]
Could you describe more about your issue? Not get the point of Badge issue.

<img width="541" alt="截屏2020-02-02上午10 44 36" src="https://user-images.githubusercontent.com/5378891/73602111-055d1f80-45a9-11ea-913b-6f897721bd2b.png">

**Comment by sugia** [comment]
@zombieJ Thanks for your following up.
Here is a sandbox for the rendering issue:
https://codesandbox.io/s/pedantic-ganguly-ik9nu?fontsize=14&hidenavigation=1&theme=dark

Here is a screenshot:
<img width="1062" alt="Screen Shot 2020-02-01 at 6 47 50 PM" src="https://user-images.githubusercontent.com/2340878/73602132-81148900-4523-11ea-939f-64c5afb44764.png">

**Comment by zombieJ** [comment]
Update demo: https://codesandbox.io/s/muddy-cherry-zrgb1
