### ISSUE TITLE
Table - Save and restore state

### ISSUE THREAD

**Issue by nsksaisaravana** [ant-design/ant-design#21182]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The save state feature allows you to save the current look of the grid and restore it upon returning to the grid.

For example, you may have an application where your user can reorder the columns, adjust column widths, apply sorts and filters, and select a specific cell. The user might adjust their grid to look as they wish, and then navigate to another page. When the user returns to the page with the grid, they might expect it to look like it did when they left. The save state feature permits this.

### What does the proposed API look like?
There are two core methods:

save, which packages the current grid state into an object which the calling application then stores somewhere (a cookie, session state, a database)
restore, which takes a grid state object, and returns the grid to the state that is stored in that object

**Comment by nsksaisaravana** [comment]
For the reference please check the below path of UI- GRID

http://ui-grid.info/docs/#!/tutorial/Tutorial:%20208%20Save%20and%20restore%20state

**Comment by zombieJ** [comment]
You can get all table state from `onChange` event.

ref: https://next.ant.design/components/table/#components-table-demo-reset-filter

**Comment by FishManHell** [comment]
@zombieJ 
Can you help with some warning ?
I got this  -> `Warning: [antd: Table] Columns should all contain `filteredValue` or not contain `filteredValue`.`
how to fix it ?
