### ISSUE TITLE
Table - Filter requires more user clicks.

### ISSUE THREAD

**Issue by nsksaisaravana** [ant-design/ant-design#21183]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Once the filter flag is enabled, text box or dropdown will be shown below the column name and the user should able to filter straight away.

### What does the proposed API look like?
Just set the enableFiltering flag in the table options, please check the screenshot below.

![image](https://user-images.githubusercontent.com/17681573/73620283-3f9bef00-4685-11ea-8e32-8ca7a0903b85.png)

**Comment by zombieJ** [comment]
Thanks for feedback. Flatten filter content into table is not recommend by ant design. Filter content outside should list out of table (ref: https://preview.pro.ant.design/list/table-list). We may not provide this feature in official api. But you can still realize it by set of `column.title`.
