### ISSUE TITLE
The FormInstance's setFieldsValue method doesn't tirgger the Input Type Component's onChange event

### ISSUE THREAD

**Issue by ago008** [ant-design/ant-design#21190]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-lc4r6?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1、click the button to set username's value
2、But the username Input Component 's onChange event didn't fire

### What is expected?
The FormInstance's setFieldsValue method should tirgger the Input Type Component's onChange event

### What is actually happening?
The FormInstance's setFieldsValue method doesn't tirgger the Input Type Component's onChange event

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | MAC OS |
| Browser | Chrome 69.0.3945.130 |

**Comment by afc163** [comment]
It is what it is, React `setState` don't trigger input `onChange` either.

**Comment by ygmgbg** [comment]
@afc163 if component A depends on B, and B depends on C, how to automatically update A when C is updated? I notice there is Dependencies api in Form.Item, there is an example how to trigger validation (password and confirm password), but no example on how to update the value, can you provide an example on how to use it to update value? Thank you.
