### ISSUE TITLE
动态加载数据的分页表格中，跨页选择行时，selectedRowKeys 和 selectedRows 表现不一致

### ISSUE THREAD

**Issue by zhumengyue** [ant-design/ant-design#21197]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/trusting-firefly-zoxuf)

### Steps to reproduce
打开 console， 第一页选择一行数据，切到第二页，再选择一行数据，此时打印出的结果中 selectedRowKeys 为两个数据，selectedRows 只有一个

### What is expected?
selectedRowKeys 和  selectedRows 都包含别的页面中选中的数据

### What is actually happening?
selectedRowKeys 和  selectedRows 不一致

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | macOS 10.14.6 |
| Browser | Chrome 79.0.3945.88 |

---
不清楚这是个 bug 还是 feature。

我的使用场景是，整个 table 用数据的 id  字段做 rowKey，选中后收集到的 idList 会用来执行一些逻辑，同时在前端会用到数据的其他字段来做别的显示，所以 onChange 中的两个参数都用到了。但是当跨页时，selectedRowKeys 正常， selectedRows 不正常。

如果这是一个 feature，请问有什么好的实践可以解决这个场景吗？

**Comment by zhumengyue** [comment]
https://github.com/ant-design/ant-design/issues/2764

**Comment by yoyo837** [comment]
我感觉是个bug，目前好像没有做跨页的行选择。

**Comment by zhumengyue** [comment]
@yoyo837 嗯，我也翻到这个 issues 了，目前来看只能自己处理了

**Comment by yoyo837** [comment]
做成受控的rowSection就可以了。
