### ISSUE TITLE
Issue regarding AutoComplete component onSelect

### ISSUE THREAD

**Issue by krishnabardoliya** [ant-design/ant-design#21192]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-76dkl)

### Steps to reproduce
- Select any option from AutoComplete component
- There is no event or any way to stop option getting select. 

### What is expected?
- Need any event or way to stop option getting selected.
- Need any function or event that will execute before selection of any option.

### What is actually happening?
- Currently Autocomplete selecting option onSelect and then executing the function inside.
- Option must be selected at last onSelect execution.
- It should be based on onSelect true or false response. 

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome - Version 79.0.3945.130 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Please try controlled mode of React component: https://reactjs.org/docs/forms.html#controlled-components
