### ISSUE TITLE
Adds a new parameter "processing" in tag Badge

### ISSUE THREAD

**Issue by sugia** [ant-design/ant-design#21191]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The tag <Badge status="processing" /> has a blue wave animation while Badge with other statuses have not. The new feature will enable Badge with other statuses to show animations.

### What does the proposed API look like?
<Badge status="error" processing={true} />

**Comment by zombieJ** [comment]
Thanks for feedback. Our design only provides `processing` status with animation. If you want to use animation with other status. You can customize this with additional className: https://codesandbox.io/s/upbeat-payne-fqrxf

**Comment by sugia** [comment]
@zombieJ Thanks for the example. That's exactly what I need.
BTW, would you like to write those cases into [document](https://ant.design/components/badge/) so that other users can see it as well?

**Comment by zombieJ** [comment]
This is not hard to implement. I think it's fine to let user just search issue if needed.
