### ISSUE TITLE
UseForm API needs to add a generic as  form data’s type

### ISSUE THREAD

**Issue by WinmezzZ** [ant-design/ant-design#21195]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Calling values in the callback to the validateFields method using the form instance returned by useForm() does not require a double assertion or simply forces as to be any type to override its default type Store {[x: string]: any}

### What does the proposed API look like?
```javascript
interface Values {
  name: string
  age: number
}

const DemoForm: FC = () => {
  // before
  // const [form] = Form.useForm()
  // after
  const [form] = Form.useForm<Values>()
  // ...
}
```

**Comment by zombieJ** [comment]
ref https://github.com/react-component/field-form/issues/70

**Comment by Kamahl19** [comment]
This should also be able without the use of `Form.useForm`. It would look like 
```
<Form<FormValues> onFinish={}>
</Form>
```

This works since TypeScript 2.9 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#generic-type-arguments-in-jsx-elements

**Comment by maasencioh** [comment]
There's any way to work on this?

**Comment by macari-dev** [comment]
> This should also be able without the use of `Form.useForm`. It would look like
> 
> ```
> <Form<FormValues> onFinish={}>
> </Form>
> ```
> 
> This works since TypeScript 2.9 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#generic-type-arguments-in-jsx-elements

This is not working and is not a proper solutions for the issue

**Comment by saostad** [comment]
> 
> 
> > This should also be able without the use of `Form.useForm`. It would look like
> > ```
> > <Form<FormValues> onFinish={}>
> > </Form>
> > ```
> > 
> > 
> > This works since TypeScript 2.9 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#generic-type-arguments-in-jsx-elements
> 
> This is not working and is not a proper solutions for the issue

that was a suggestion for solution not an actual solution!

**Comment by suncunhu** [comment]
Have a deadline for solving this problem?

**Comment by zombieJ** [comment]
@suncunhu, currently typescript do not support generic with HOC that means we can not provide this ability since Form component use `forwardRef` which block the generic.

Pls feel free to contribute if you have the solution.

**Comment by Jens1998D** [comment]
Is this ready to be used somehow? Ant Design 4.5.2 still seems to be using the 1.8.0 rc-field-form version.

**Comment by JensD98** [comment]
Is this ready to be used somehow? Ant Design 4.5.2 still seems to be using the 1.8.0 rc-field-form version.

**Comment by zombieJ** [comment]
@JensD98  antd release minor version each end of month

**Comment by acfasj** [comment]
> @JensD98 antd release minor version each end of month

why `form.validateFields();` not work, still get the type `Store` not the generic type I defined. [see codesandbox](https://codesandbox.io/s/awesome-sea-5irp6?file=/src/App.tsx)
