### ISSUE TITLE
Form.Item help text causing jumpy content height

### ISSUE THREAD

**Issue by samit4me** [ant-design/ant-design#21206]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/long-star-td4ir)

### Steps to reproduce
- Click "Open Form" button.
- Enter some text into "Username" field.

### What is expected?
The help/error message to disappear.

### What is actually happening?
The help/error message does disappear but due to the animation and class "ant-form-item-with-help" the page changes in height which is jumpy when inside modals.

Please note that normal error messages (e.g. not using help) appear to work as expected, see the "Password" field.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 79 |

---
In v3 this seems to work as expected https://codesandbox.io/s/tender-kare-qznfs

In v4 this causes the jumpy content height https://codesandbox.io/s/long-star-td4ir

**Comment by zombieJ** [comment]
ref #20836

**Comment by kangkang12** [comment]
![image](https://user-images.githubusercontent.com/34826299/98911651-e6a89380-24ff-11eb-9e62-9a2c9343eaca.png)
这个问题仍然存在，上图是antd官网的截图。

**Comment by zombieJ** [comment]
能开个新的 issue 不？

**Comment by olegmdev** [comment]
+1
