### ISSUE TITLE
v4 菜单展开时 会产生抖动

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design#21209]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.mii.red](http://www.mii.red)

### Steps to reproduce
当菜单有二级时

### What is expected?
不会抖动

### What is actually happening?
产生抖动

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 最新 |
| System | mac ios |
| Browser | 谷歌 |

![image](https://user-images.githubusercontent.com/24733229/73716618-7be95100-4752-11ea-8669-a43f73674f5c.png)

**Comment by admiao** [comment]
https://github.com/ant-design/ant-design/issues/21196

**Comment by zombieJ** [comment]
Hi @admiao ,请给一个在线的代码重现：https://u.ant.design/codesandbox

**Comment by admiao** [comment]
> Hi @admiao ,请给一个在线的代码重现：https://u.ant.design/codesandbox

https://next.ant.design/components/menu-cn/  产生的原因是 https://github.com/ant-design/ant-design/issues/21196

**Comment by dpyzo0o** [comment]
我这里也复现了

**Comment by dpyzo0o** [comment]
> Hi @admiao ,请给一个在线的代码重现：https://u.ant.design/codesandbox

https://next.ant.design/components/menu-cn/#components-menu-demo-inline, 官网的 demo 就能复现这个问题，点击展开子菜单时会出现抖动

**Comment by dpyzo0o** [comment]
@zombieJ 请问这个issue有人跟进一下吗

**Comment by TianEnPang** [comment]
> @zombieJ 请问这个issue有人跟进一下吗

官方已经跟进了 [21109](https://github.com/ant-design/ant-design/pull/21109)

**Comment by dpyzo0o** [comment]
> > @zombieJ 请问这个issue有人跟进一下吗
> 
> 官方已经跟进了 [21109](https://github.com/ant-design/ant-design/pull/21109)
> 
> 目前看已经解决此问题。

谢谢，是不是这个修复还没有发布？ 等到 rc5 就可以了吗

**Comment by TianEnPang** [comment]
> > > @zombieJ 请问这个issue有人跟进一下吗
> > 
> > 
> > 官方已经跟进了 [21109](https://github.com/ant-design/ant-design/pull/21109)
> > 目前看已经解决此问题。
> 
> 谢谢，是不是这个修复还没有发布？ 等到 rc5 就可以了吗

目前官方Demo中已经没有抖动了，但是我刚更新了rc4依然存在，可能要等到rc5了

**Comment by afc163** [comment]
fixed in #21314
