### ISSUE TITLE
(4.0Form) getFieldValue获取不到值. (3.x这样使用没有问题, 官方也没有相关的迁移参考)

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#21214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-morning-h4t7d)

### Steps to reproduce
打开Modal, 显示单选切换为是, 并不能显示组件(在例子为Input).

### What is expected?
显示单选切换为是, 能显示例子里的Input组件.

### What is actually happening?
显示单选切换为是, 不能显示例子里的Input组件. 而在关闭窗口的时候显示了.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome 79 |

---
3.x这样的写法是正常的. 4.0不行, 而4.0的fields又是FieldData[]类型, 难道要用fileds[0].value来判断吗?  万一中途加了个组件, 索引是不是错乱了. 或者自己写个查找方法?
4.0暂时处理这样的方法就是自己管理一个useState. 变化交由自己管理. (4.0的想法是这样的吗? 3.x的getFieldsValue太方便)

**Comment by zombieJ** [comment]
https://next.ant.design/components/form-cn/#components-form-demo-control-hooks

**Comment by crawler-django** [comment]
没有一个是我想要的.
demo例子不能像3.x一样正常显示.

**Comment by crawler-django** [comment]
3.x可以支持getFieldValue写在dom判断里, 在radio切换的时候能正常运行.
4.0不行.

**Comment by zombieJ** [comment]
v4 的表单修改值不会渲染整个 Component，请参考我给的例子。

完整迁移文档请参考：https://next.ant.design/components/form/v3-cn/

**Comment by wenlittleoil** [comment]
> 3.x可以支持getFieldValue写在dom判断里, 在radio切换的时候能正常运行.
> 4.0不行.

我也遇到这个问题了，在jsx里面书写的form.getFieldValue('myField')值没有完成dom动态渲染，实际上form表单数据已经更新。

**Comment by cyw0626** [comment]
+1

**Comment by hcxmj** [comment]
所以最终这个问题是怎么解决的呢

**Comment by imloren** [comment]
所以最终这个问题是怎么解决的呢

**Comment by dangdng** [comment]
所以最终这个问题是怎么解决的呢

**Comment by gengengengengen** [comment]
所以最终这个问题是怎么解决的呢
