### ISSUE TITLE
Drop element to Cascader #support

### ISSUE THREAD

**Issue by CarlosAmaral** [ant-design/ant-design#21228]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/delicate-field-hy4tv)

### Steps to reproduce
Drag and drop file tree element to input or cascader

### What is expected?
Looking for support on how can I successfully drag and drop to a Cascader like I can for an Input

### What is actually happening?
Not triggering a drop event for the Cascader

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | 16.12 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
Cascader don't supprt drag and drop behavior now.

**Comment by CarlosAmaral** [comment]
In case anyone wonders the same, I made this work like this:

I wrapped the Cascader around a div with a onDrop and onDragOver event listeners and it works. You get the name of the field you dropped into in the onDrop listener by navigating into the following structure: `event.currentTarget.id`
