### ISSUE TITLE
Tooltip Line breaks not working

### ISSUE THREAD

**Issue by Sparkenstein** [ant-design/ant-design#21224]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-g4uev)

### Steps to reproduce
Hover on input box

### What is expected?
The tooltip should show linebreaks. Other ways are not mentioned in docs

### What is actually happening?
Everything is one line

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | Ubuntu |
| Browser | Chrome  latest |

**Comment by zombieJ** [comment]
Tooltip max-width is `250px`:
<img width="403" alt="截屏2020-02-04下午6 55 11" src="https://user-images.githubusercontent.com/5378891/73738684-e06ed500-477f-11ea-8272-6788a5b1b022.png">

**Comment by Sparkenstein** [comment]
I understand you want to close as many issues as possible but this is not expected behavior.  The tooltip should show "at least 8 characters" and "1 Uppercase" on different lines. Total message is:
```
At least 8 characters
One Uppercase
One Lowercase
One Number
```

I have solved it as of now with `white-space: pre` css hack. Hope there's better solution exists

**Comment by keithort** [comment]
This is the default behavior of HTML. If you want a line break, you'll need to use JSX and add the `<br />` where you want the line break.

**Comment by MuhammadHasham23** [comment]
Title can take ReactNode as well, maybe you can render a component such as:

```
const renderTooltip = (firstName,lastName) => {
 return (
   <>
      <p>{firstName}</p>
      <br/>
      <p>{lastName}</p>
 </>
)
```
}

**Comment by aleris** [comment]
Works perfectly well with:

```
<Form.Item
        label="Field A"
        tooltip={
          <>
            <div>abc</div>
            <div>123</div>
          </>
        }
        >
        <Input />
</Form.Item>
```

**Comment by justanotheranonymoususer** [comment]
Had the same issue. All you need to do is to add `white-space: pre-line;` to the tooltip contents.
See https://stackoverflow.com/q/9492249/2604492
@zombieJ it should be set out of the box.

**Comment by ArturArakelyan0411** [comment]
If `whiteSpace: 'pre-line'` doesn't work as well

Try this

```js
<Tooltip overlayStyle={{ lineBreak: 'anywhere' }} title={`...`}>
...
</Tooltip>
```

**Comment by NijatInHIT** [comment]
> Had the same issue. All you need to do is to add `white-space: pre-line;` to the tooltip contents. See https://stackoverflow.com/q/9492249/2604492 @zombieJ it should be set out of the box.
> 
> Meanwhile, you just can use:
> 
> ```
> <Tooltip overlayStyle={{ whiteSpace: 'pre-line' }} title={`...`}>
> ...
> </Tooltip>
> ```

life saver!  no one would use <br />!
