### ISSUE TITLE
Popover 弹出窗 若content 里面包含弹出 的组件， 点击 content弹出的内容后， popover会隐藏

### ISSUE THREAD

**Issue by LeoZeda** [ant-design/ant-design#2122]
Popover 弹出窗 若content 里面包含弹出类型的组件（如select， datepicker）， 点击 content弹出的内容后， popover会隐藏. 
不知道可否做到点击Popover弹出的内容时， Popover不会受影响

//代码如下
[http://codepen.io/LeoZeda/pen/gMwVBp?editors=001](http://codepen.io/LeoZeda/pen/gMwVBp?editors=001)

**Comment by afc163** [comment]
注意 issue 格式。

**Comment by LeoZeda** [comment]
更新了代码

**Comment by afc163** [comment]
可以指定 A 浮层内的 B 浮层的渲染节点为 A 浮层（默认为 body）来解决。其他组件 Select、Tooltip 等都可以类似处理。

http://codepen.io/anon/pen/dXpxwE?editors=001

**Comment by LeoZeda** [comment]
可以了，但有个疑问， 这个getCalendarContainer函数，按我理解应该是设置浮层的渲染节点，看了官网API好多组件都类似函数，为什么不取名为setXXX函数？这样比较好理解

**Comment by afc163** [comment]
类似 getInitailState 和 getDefaultProps 的声明式命名方式，不是调用式的。

**Comment by miaojiuchen** [comment]
@afc163  请问，TimePicker没有getCalendarContainer这样的api，我要怎么设置它的浮层的anchor呢？

**Comment by miaojiuchen** [comment]
@afc163  我看了下rc-time-picker 发现是叫 getPopupContainer，希望加到文档里 
PR: 
https://github.com/ant-design/ant-design/pull/2390
