### ISSUE TITLE
TypeScript Antd Badge status throws error: No overload matches this call.

### ISSUE THREAD

**Issue by AO19** [ant-design/ant-design#21223]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/badge-antd-issue-reprod-4f92p)

### Steps to reproduce
Import Badge in TypeScript file and use Badge status attribute.

### What is expected?
Badge should render a status dot, when given a supported string.

### What is actually happening?
Error thrown, even though the string is correct.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | React @latest and TypeScript 3.7.3 |
| System | Windows 10 |
| Browser | Chrome/ Firefox |

---

```bash
No overload matches this call.
  Overload 1 of 2, '(props: Readonly<BadgeProps>): Badge', gave the following error.
    Type 'string' is not assignable to type '"error" | "processing" | "success" | "default" | "warning" | undefined'.        
  Overload 2 of 2, '(props: BadgeProps, context?: any): Badge', gave the following error.
    Type 'string' is not assignable to type '"error" | "processing" | "success" | "default" | "warning" | undefined'.  TS2769

    78 |                   <a href='_blank'>{item.title}</a>
    79 |                   <p>
  > 80 |                     <Badge status='error' />
       |                            ^
    81 |                     {`${item.coverage} 21h ago`}
    82 |                   </p>
    83 |                 </List.Item>
```

**Comment by zombieJ** [comment]
https://codesandbox.io/s/badge-antd-issue-reprod-4f92p
