### ISSUE TITLE
Move column headers to side of table

### ISSUE THREAD

**Issue by scottmay2020** [ant-design/ant-design#21231]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This allows the columns to be rendered on the side of the table for easier side by side comparison.

### What does the proposed API look like?
<Table columns={columns} dataSource={data} horizontal />

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9155#issuecomment-498622824
