### ISSUE TITLE
[v4] How to set custom value to form

### ISSUE THREAD

**Issue by mbm-code** [ant-design/ant-design#21238]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ulhv7)

### Steps to reproduce
https://codesandbox.io/s/antd-reproduction-template-ulhv7

### What is actually happening?
Cannot set value to form field

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.11.0 |
| System | Windows 10 |
| Browser | Google Chrome 79.0.3945.130 (Official Build) (64-bit) |

---
I'm upgrading from v3 to v4-rc.3. I facing issue getFieldDecorator label type. Please find the codesandbox.

I'm getting following data:
```
mydata: Array[2]
0: Array[2]
	0: undefined
	1: undefined
1: Array[2]
	0: undefined
	1: undefined
```

I want to following data:
```
mydata: Array[2]
0: Array[2]
	0: "Label 1"
	1: "Input value"
1: Array[2]
	0: "Label 2"
	1: ""
```

v3 code
```
(item.type) === "label" &&
          getFieldDecorator(
            `${data.name}[${key}][${itemkey}]`,
            {
              initialValue: item.value
            }
          )(
        <div>{item.value}</div>
)}
```

**Comment by wanjas** [comment]
`Form` has property `initialValues` now. 
Here is the migration guide https://next.ant.design/components/form/v3/

**Comment by zombieJ** [comment]
* For first render: use `initialValues` on Form
* For async set: use `form. setFieldsValue`
* Form Form.List add: use `add(initValue)`

**Comment by osamasayed** [comment]
> * For first render: use `initialValues` on Form
> * For async set: use `form.setFieldsValue`
> * for Form.List add: use `add(initValue)`

@zombieJ can you provide an example of using `add(initValue)`?  I am trying to dynamically field to Form.List for editing. for example, I have 3 names I want to pre-load so that I can edit them. I would appreciate your help on how to do that?

**Comment by OleksandrFomin** [comment]
> * For first render: use `initialValues` on Form
> * For async set: use `form.setFieldsValue`
> * for Form.List add: use `add(initValue)`

How do I do async set if my inputs are in collapsed menus (not rendered and therefore not registered with getFieldDecorator) 
I'm getting an error message telling me that I cannot set a value for a field that hasn't been rendered. Is there a workaround for that in antd v3

Here is my codesandbox https://codesandbox.io/s/unruffled-snowflake-0k0gl?file=/src/App.js

**Comment by youbek** [comment]
I really like the library you made. But why you prevent creating a fully controlled form?

**Comment by IonelLupu** [comment]
@zombieJ `form.setFieldsValue` doesn't set anything in my form if we don't have HTML elements for inputs. We had to add the inputs and make them hidden 😞
