### ISSUE TITLE
Input autocomplete does not work in Firefox.

### ISSUE THREAD

**Issue by thisissami** [ant-design/ant-design#21232]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-o5g1u)

### Steps to reproduce
1) Input text in text field.
2) Hit submit or hit enter.
3) Delete text in text field, then click in the input.

### What is expected?
It is expected that the browser autocomplete will show the previously entered value.

### What is actually happening?
In Chrome, it works as expected.

In Firefox, there is no autocomplete.

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | react 16.11 |
| System | Linux (Ubuntu 18.04) |
| Browser | Firefox 71.0 |

---
I believe this is the issue: https://github.com/facebook/react/issues/17022#issuecomment-544222838

`antd` seems to pass a `value` prop to the `input`, which according to the above link/thread/GitHub issue, stops autocomplete on Firefox from working. They provide a workaround in the thread using `ref`s.

**Comment by zombieJ** [comment]
We can do nothing about this since we need to set `value` prop in React for internal control (for clear value usage) or it will fire a warning by React said value miss set in control mode. You can fire a new issue to React instead.
