### ISSUE TITLE
让菜单分割线可以用于Menu中，而不只能用在弹出菜单内。

### ISSUE THREAD

**Issue by videni** [ant-design/ant-design#21233]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
让菜单可以作用于Menu控件的第一层，我们可以在视觉上给用户一个分开逻辑，表明被分开的菜单有一定的差异。比如，左侧作为菜单的区域，上部分，我们可以提取一些非常常用的链接，作为快捷菜单，下部分区域为其它链接。但这两部分在一个菜单内。

### What does the proposed API look like?
```
<Menu>
     <Divider/>
</Menu>
```

上面的使用方法会有很多警告，因为Divider接收的props跟Menu.Item, Menu.SubMenu是不一样的。

**Comment by afc163** [comment]
https://codesandbox.io/s/goofy-clarke-ykzh4

是这样么。

**Comment by videni** [comment]
@afc163,  我做了一点修改，是这个样子。https://codesandbox.io/s/holy-violet-wccrk?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/507615/73809609-bc0e0980-480e-11ea-9cb3-b5d9de271492.png">

现在的有什么问题，没太理解。

**Comment by videni** [comment]
@afc163 ,  功能上可用，但有很多警告。

> 上面的使用方法会有很多警告，因为Divider接收的props跟Menu.Item, Menu.SubMenu是不一样的。

**Comment by afc163** [comment]
codesandbox 里好像没看到警告。

**Comment by videni** [comment]
可能只在开发环境可见。
![image](https://user-images.githubusercontent.com/4058341/73811294-12317b80-4814-11ea-8c4d-a03c1b450909.png)
