### ISSUE TITLE
   table taking more time to load data

### ISSUE THREAD

**Issue by sunithakk** [ant-design/ant-design#21230]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-glitter-livi0)

### Steps to reproduce
https://codesandbox.io/s/gracious-glitter-livi0

### What is expected?
speed

### What is actually happening?
taking more time

| Environment | Info |
|---|---|
| antd | undefined |
| React | "react": "^16.12.0", |
| System | widwos 10 |
| Browser | chrome |

**Comment by keithort** [comment]
@sunithakk The reproduction doesn't utilize the Table component. Did you attach the correct link to this issue?
