### ISSUE TITLE
English

### ISSUE THREAD

**Issue by nuptaxin** [ant-design/ant-design#21248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nuptaxin/antd-demo/tree/dev_rowSelectionTable](https://github.com/nuptaxin/antd-demo/tree/dev_rowSelectionTable)

### Steps to reproduce
update excel file which has multiRow(>10) and width row  data。when use rowSelection, table right is out border.

### What is expected?
whether use rowSelection, table will self-adaptive

### What is actually happening?
table right is out border.

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome 79.0.3945.130 （64 位） |

**Comment by afc163** [comment]
```diff
columns={[
  {
    title: 'xxx',
+   ellipsis: true,
  }
]}
```

or

```diff
columns={[
  {
    title: 'xxx',
+   className: 'text-break',
  }
]}
```

```css
// css
.text-break {
  word-wrap: break-word;
  word-break: break-word;
}
```

or

```diff
<Table
+ scroll={{ x: true }}
/>
```
