### ISSUE TITLE
Keep the original node data when dragging on Tree component

### ISSUE THREAD

**Issue by CarlosAmaral** [ant-design/ant-design#21249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-field-9hf7v)

### Steps to reproduce
Drag an item vertically.

### What is expected?
I'd like to have the original node data that I'm dragging always present. 

### What is actually happening?
The original node data being dragged is lost when dragging on top of other nodes.

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | 16.12 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
I don't realy understand what your problem is.

**Comment by zombieJ** [comment]
Close since not more feedback.
