### ISSUE TITLE
手动调用validateFields校验某个表单项时，是否可以设置每次都执行 validator 函数？

### ISSUE THREAD

**Issue by zhumengyue** [ant-design/ant-design#21240]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/falling-https-16xn6)

### Steps to reproduce
首次点击 login 按钮，console 可以看到 validateFn 函数被执行了，之后再次点击 login，validateFn 不会执行

### What is expected?
每次都会执行

### What is actually happening?
只有首次执行

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.12.0 |
| System | macOS 10.14.6 |
| Browser | Chrome 79.0.3945.88 |

---
我感觉这应该是“预期内”效果，是否和 `validateTrigger` 有关？

我的使用场景是：点击按钮时，会根据 input 的内容和其他表单项来发一个请求，根据请求结果决定这个 input 是否校验通过。所以在逻辑上我在点击按钮时会把请求的返回结果存起来，然后手动调用 `validateFields(['xxx'])` 来单独校验这个 input 组件，最后在 validateFn 中会做判断保存的结果，来决定是否校验成功。

现在就如果第一次请求没成功，会正常校验不通过，但是当之后请求成功时，不会执行 validateFn 的逻辑，就永远是不通过。

如果改动了 input 的值，就会重新执行 validateFn，所以我觉得可能和 `validateTrigger` 有关。

请问有没有比较好的解决办法？

**Comment by afc163** [comment]
@zombieJ 看看是不是和 3.x 的逻辑不一致。

**Comment by zombieJ** [comment]
`validateFields` 有个 `force` 属性。 

ref: https://ant.design/components/form-cn/#validateFields/validateFieldsAndScroll

**Comment by America-first-melon** [comment]
这个属性4.x没了阿??
