### ISSUE TITLE
Enhance optionFilterProp to take an array (optionFilterProps).

### ISSUE THREAD

**Issue by J9th** [ant-design/ant-design#21251]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. Prevent users from needing to create a custom filterOption function for filtering based on multiple select option properties
2. When using Option Groups (OptGroup) to categorize select options, while needing to filter based on multiple select option properties, and using a custom filterOption function the select component only filters down to the OptGroup and not to the specific select option. The select component still shows all the options in the option group (which can be big) making the filter/search function useless.

For a code example please check [**here**](https://codesandbox.io/s/agitated-bush-z4lxr)
Also opened an enhancement issue for the rc-select component previously [**here**](https://github.com/react-component/select/issues/373)

### What does the proposed API look like?
```
  <Select
    showSearch
    style={{ width: 200 }}
    placeholder="Select a person"
    optionFilterProps=["children", "nickname", "age"]
    onChange={onChange}
    onFocus={onFocus}
    onBlur={onBlur}
    onSearch={onSearch}
  >
    <Option value="johnny" nickname="johnson" age="1">Johnny</Option>
    <Option value="madeline" nickname="mattie" age="2">Madeline</Option>
    <Option value="thomas" nickname="tom" age="3">Thomas</Option>
  </Select>
```

**Comment by afc163** [comment]
You can try `filterOption` for custom searching need.

**Comment by J9th** [comment]
filterOption does not solve the second problem, where the select options are not filtered down to a single options when using option groups

**Comment by afc163** [comment]
It looks like a bug.

**Comment by afc163** [comment]
https://codesandbox.io/s/charming-robinson-fwdwv
