### ISSUE TITLE
Nested Form.Item (with `noStyle`) does not show red asterisk for required rule

### ISSUE THREAD

**Issue by tennisgent** [ant-design/ant-design#21255]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-water-nji2y)

### Steps to reproduce
Create any nested set of Form.Item components using an Input.Group within a Form and set one (or all) of them to be required. You will see that the red asterisk that should appear next to the label does not appear. 

### What is expected?
Field is required so a red asterisk should appear to the left of the field label

### What is actually happening?
Field is being internally marked as required and will fail validation if it is left blank, but the user doesn't know that the field is required because no asterisk appears next to the label, as it does with all other required fields

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | MacOS |
| Browser | Chrome: Version 79.0.3945.117 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
`rules` only work when `name` is set. And for nest Form.Item, top level Form.Item can not decide it will mark as required or not automatically. Your should use `required` intead.

Additionally, `rc.3` has a bug that `required` prop not work as expect. It fixed in  #21168

**Comment by baurine** [comment]
> `rules` only work when `name` is set. And for nest Form.Item, top level Form.Item can not decide it will mark as required or not automatically. Your should use `required` intead.
> 
> Additionally, `rc.3` has a bug that `required` prop not work as expect. It fixed in #21168

Adding `required` props to the top Form.Item resolved my problem, thanks!
