### ISSUE TITLE
Form onSubmit回车提交表单事件，被控件按回车触发的交互覆盖

### ISSUE THREAD

**Issue by milobluebell** [ant-design/ant-design#21254]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
原生控件，比如select控件，在获得焦点时点击enter回车会正常触发表单submit提交事件，select本身的交互监听在space空格键。 但比如在antd的Form中，使用antd.Select组件时，点击回车会触发本身的显示/隐藏交互，而不是正确地提交了表单。且在文档中没有搜到能使我和原生达成一致交互的方法。我应该怎么办？ 

### What does the proposed API look like?
我期望是和原生form提交同样的交互逻辑

**Comment by yoyo837** [comment]
原生控件是仅有一个显示的input 表单项时，enter才是直接出发提交吧？来个demo？
