### ISSUE TITLE
关于Upload.Dragger拖拽上传压缩包里的文件

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#21259]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/g653p)

### Steps to reproduce
1、本地使用压缩软件打开压缩包
2、从压缩包里选中一个文件拖拽到组件上

### What is expected?
拖拽成功

### What is actually happening?
提示上传失败

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | 16.8 |
| System | Windows 10 |
| Browser | QQ浏览器10.4.2 |

**Comment by afc163** [comment]
。。。这种 antd 也支持不了的。

**Comment by phoema** [comment]
这也是客户反映的，我在这儿之前从来没想到能这么干。。。

**Comment by larants** [comment]
> 。。。这种场景 antd 也支持不了的。

文件夹上传也是不支持的，虽然上传组件提供了一个directory参数，但实际上还是一个一个上传的，啥时候支持一下真正的文件夹上传？？
