### ISSUE TITLE
getFieldDecorator doesn't allow one field name be part of another.

### ISSUE THREAD

**Issue by chenxd1996** [ant-design/ant-design#21252]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes we need one field name be part of another.
For example, we have a field which is array type, and its items are object type, and we need to add validator to not only the child fields but also the array field, such as the length and the order of the array.
So I think maybe getFieldDecorator should allow one field name be part of another.

### What does the proposed API look like?
No changes.

**Comment by chenxd1996** [comment]
有没有大佬来解释一下为啥这样设计？

**Comment by zombieJ** [comment]
v4 已经支持了。

ref：https://zhuanlan.zhihu.com/p/102057196  （查阅 `小淘气二号：getFieldDecorator` 部分）
