### ISSUE TITLE
`Icon` 增加 `size` 属性如何？

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#2125]
`Icon[size="small | default | large"]`

虽然可以用 `font-size` 设置 Icon 大小，但是这样不同的人写出来的 icon 大小可能不一致，或者可以规范下？

cc @Chinglik

**Comment by liekkas** [comment]
+1

**Comment by afc163** [comment]
设计师认为大小无明显规律，暂不支持。

**Comment by alex86w** [comment]
😢   在 fontSize 里面设置呀，找死我了， google和 度娘都美有

**Comment by afc163** [comment]
@alex86w 我在文档里补充下。
