### ISSUE TITLE
关于Upload组件如何自定义上传附件列表样式？

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#21260]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
期望能够在附件列表左侧增加一个下拉列表表单
不知道从哪里修改，只看到支持3种内置样式

### What does the proposed API look like?
不知道从哪里修改，只看到支持3种内置样式
期望能够自定义附件列表
比如我想在附件列表左侧增加一个下拉列表表单
我目前重写了一套附件列表显示组件，将showUploadList设置为了false
但是我发现缺失了不少功能，比如上传失败变红，提示失败，删除图标等，都需要重写，工作量较大，
是否能够开发附件列表，便于增加一些属性？提供自定义

**Comment by afc163** [comment]
Duplicate of #16047

**Comment by ZhaoXinNian** [comment]
附议
