### ISSUE TITLE
Dropdown Click Menu Bug in mobile

### ISSUE THREAD

**Issue by diw1** [ant-design/ant-design#21267]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown/#](https://ant.design/components/dropdown/#)

### Steps to reproduce
在移动端浏览器上，点击Click Event的Dropdown menu

### What is expected?
应该正常弹出菜单

### What is actually happening?
跳回到页首

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | Latest |
| System | Android |
| Browser | Mobile Chrome 79 |

---
桌面端没有此问题。

**Comment by afc163** [comment]
大概率是手机浏览器里 js 没加载完。

**Comment by diw1** [comment]
> 大概率是手机浏览器里 js 没加载完。

换了同机器的华为浏览器，同样。
换了个iPhone 用chrome，同样。
