### ISSUE TITLE
目前tree只有checkable属性,显示checkbox,有没有显示radio的属性

### ISSUE THREAD

**Issue by sy13277072001** [ant-design/ant-design#21269]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以在tree下建radio子节点,也可以建checkbox,可以对进行单选操作,也可以多选操作,混合使用.

### What does the proposed API look like?
           <TreeNode title="年龄" key="0" radioable>
                <TreeNode title={1}></TreeNode>
                <TreeNode title={2}></TreeNode>
                <TreeNode title={3}></TreeNode>
            </TreeNode>

**Comment by afc163** [comment]
多层级的单选建议用 TreeSelect 或者开启 Tree 的 selectable 属性。

**Comment by sy13277072001** [comment]
> 多层级的单选建议用 TreeSelect 或者开启 Tree 的 selectable 属性。

还需要搜索对应标签,  我目前把 radioGroup整体放入 treenode的title中,不过不能进行本地搜索了
![73812721-c92ff600-4818-11ea-88aa-833043c5e4fe (1)](https://user-images.githubusercontent.com/25413638/74006077-94a57100-49b5-11ea-9d65-ceea21e10613.png)

**Comment by afc163** [comment]
请使用 `filterTreeNode` 自行设定搜索的逻辑。

**Comment by afc163** [comment]
这里不应该使用 Tree 自带的 Checkbox，建议用 title 自定义节点内容。
