### ISSUE TITLE
Typography "editable" focus cursor at the beginning of the text instead of at the end

### ISSUE THREAD

**Issue by sanusart** [ant-design/ant-design#21261]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crimson-grass-t0ork)

### Steps to reproduce
Click on edit icon

### What is expected?
Cursor should be at the end of the text upon focus

### What is actually happening?
Cursor is at the beginning of the text upon focus

| Environment | Info |
|---|---|
| antd | 3.26.8 |
| React | 16.8.0 |
| System | MacOs |
| Browser | Google chrome |

---
It is also seem to happen in v4 and not only Macos and chrome based browsers.

**Comment by sanusart** [comment]
:+1: thank you!

**Comment by SamadhanShende** [comment]
cursor automatically shifts to the end of the name  in Typography.when i am change middle charater
