### ISSUE TITLE
Dropdown和Modal同时使用时无法更新Modal状态

### ISSUE THREAD

**Issue by h025** [ant-design/ant-design#21263]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-8divr?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
鼠标移至Dropdown ---> 点击ModalShow ----> 点击Add（或者点击cancel或Ok按钮）

### What is expected?
点击Add时count计数增加 点击cancel或Ok关闭Modal

### What is actually happening?
无任何反应

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.11.0 |
| System | win10 |
| Browser | chrome 79.0.3945.130 (正式版本64 位) |

---
更改组件state 无法更新Modal

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-odccs

**Comment by h025** [comment]
> https://codesandbox.io/s/antd-reproduction-template-odccs
> 
> Modal 不要放 Menu.Item 里面。

感谢您的回复。 我知道Modal不放在Menu.Item 里面没问题，但是我觉得放在里面好像也不违反react规则，好奇什么原因导致了状态更新失败！

**Comment by xjfan81** [comment]
@h025 放在里面，state是更新了，但Modal组件没有刷新。

**Comment by h025** [comment]
> @h025 放在里面，state是更新了，但Modal组件没有刷新。

是的，我发现Modal没有刷新，问题就是为什么不能更新，不懂！

**Comment by xjfan81** [comment]
@h025 这跟Menu的实现有关系。Menu（https://github.com/react-component/menu/blob/master/src/Menu.tsx）中套了一层SubPopupMenu，而在SubPopupMenu的实现（https://github.com/react-component/menu/blob/master/src/SubPopupMenu.tsx），有一个shouldComponentUpdate函数。这个条件要满足，setState()才会刷新。
