### ISSUE TITLE
father 打包 antd V4 Input 的问题

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#21262]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/father-antd-demo-26yid)

这个是包的链接 https://github.com/crazyair/father-demo

打包后的代码

```js
import 'antd/es/form/style';
import _Form from 'antd/es/form';
import 'antd/es/input/style';
import _Input from 'antd/es/input';
import React from 'react';

var DInput = function DInput(props) {
  return React.createElement(_Input, Object.assign({}, props));
};

var DForm = function DForm() {
  return React.createElement(_Form, null);
};

export { DForm, DInput };

```

### Steps to reproduce
进来页面就会报 `getInputClassName is not a function`，如果 删掉 `suffix` 就不会报错。

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | V4 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
还有个问题  
father-demo 项目 `yarn dev` 启动没问题，但是 `yarn doc:build`  ` serve -s .doc` 启动后的本地，文本框改变值的时候报错 ` regeneratorRuntime is not defined` 。
这些问题我也不知道是 antd 问题还是 father 问题 还是 docz 的。

**Comment by yoyo837** [comment]
#20842

**Comment by crazyair** [comment]
> #20842

嗯 2个问题，还有那个打包要不要加按需加载

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/field-form/commit/1f164ac989baba61db567f2d9ffdad19788ddaea

**Comment by crazyair** [comment]
@afc163  https://codesandbox.io/s/father-antd-demo-n194g  用了刚发版的 4 ，可是还有问题

**Comment by PeachScript** [comment]
@crazyair 这个问题是 father-antd-demo 这个库 module 配置导致的，`index.esm.min.js` 不应配置到 `package.json` 的 `main` 中

**Comment by PeachScript** [comment]
@crazyair  上面我说的不对，这个问题看起来和 codesandbox.io 有关，这个 demo 没有使用 npm 的包也会报同样的错误，而且使用的是 antd v3 ：https://codesandbox.io/s/epic-tdd-k62cb

issue 先重新打开了

**Comment by crazyair** [comment]
> @crazyair 上面我说的不对，这个问题看起来和 codesandbox.io 有关，这个 demo 没有使用 npm 的包也会报同样的错误，而且使用的是 antd v3 ：https://codesandbox.io/s/epic-tdd-k62cb
> 
> issue 先重新打开了

我也觉得可能是在线的问题，下载到本地再启动不报错。

**Comment by afc163** [comment]
确实和 codesandbox 有关，而且和 DInput 也没没什么关系。不是我们的问题就关闭了。

https://codesandbox.io/s/keen-glade-ycd83
