### ISSUE TITLE
Button.Group documentation is missing for 4.0 RC

### ISSUE THREAD

**Issue by chemicalkosek** [ant-design/ant-design#21278]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The part about Button.Group is missing in 4.0 RC documentation even though it works as it should after migration from v3

### What does the proposed API look like?
Add Button.Group documentation.

**Comment by zombieJ** [comment]
Yes. We removed this content in v4 doc on purpose.

**Comment by zombieJ** [comment]
PS: style is still compatible support to avoid breaking change.

**Comment by afc163** [comment]
Button.Group 从文档中移除的原因是？

**Comment by shughes-uk** [comment]
is there any alternative for grouping buttons together?

**Comment by chillyistkult** [comment]
Button.Group is broken in 4.1.4. Alignment issues when buttons have an icon and size is `small`.

**Comment by zombieJ** [comment]
@chillyistkult , do you have interested to help to fix this?

**Comment by klgd** [comment]
那 Button.Group 是计划废弃吗？

**Comment by milobluebell** [comment]
现在有人在开发这个东西吗？

**Comment by topsoft-support** [comment]
@zombieJ  有意为之  @afc163  不明原因  
啊。。。这个让我们吃瓜群众咋个搞

到底是能用还是不能用，建议用还是建议不用？
请给个准话？

**Comment by afc163** [comment]
简单的说就是 Ant Design 设计规范中移除了这种用法，所以相应的文档和演示我们都下掉了。设计上不再推荐使用 Button.Group，而是直接使用 Button。

在开发上我们为了保持向下兼容，所有的代码都保留，老代码不会挂。

**Comment by topsoft-support** [comment]
> 简单的说就是 Ant Design 设计规范中移除了这种用法，所以相应的文档和演示我们都下掉了。设计上不再推荐使用 Button.Group，而是直接使用 Button。
> 
> 在开发上我们为了保持向下兼容，所有的代码都保留，老代码不会挂。

也就是说 以后别用了Button.Group这样的组件了，要实现group的功能自己去实现类似`ant-btn-group`这样的样式及其`child`样式
```html
<div className="ant-btn-group">
    <Button>启用</Button>
    <Button>禁用</Button>
    <Button>删除</Button>
</div>

<div className="ant-btn-group" style={{marginLeft: "5px"}}>
    <Button>查看</Button>
    <Button>编辑</Button>
</div>
```

**Comment by hosseinmd** [comment]
> > 简单的说就是 Ant Design 设计规范中移除了这种用法，所以相应的文档和演示我们都下掉了。设计上不再推荐使用 Button.Group，而是直接使用 Button。
> > 在开发上我们为了保持向下兼容，所有的代码都保留，老代码不会挂。
> 
> 也就是说 以后别用了Button.Group这样的组件了，要实现group的功能自己去实现类似`ant-btn-group`这样的样式及其`child`样式
> 
> ```

Please speak English. A unit language can help to communicate with all of world.

**Comment by Enigama** [comment]
So what is the solution? We should avoid to use Button.Group ?

**Comment by xXm5aXx** [comment]
you can use <[Space](https://ant.design/components/space#space-demo-compact-buttons)> component with compact mode

**Comment by kvfi** [comment]
I would recommend doing this:

```
<Flex justify="flex-end" align="flex-end">
        <Space.Compact>
          <Button type="primary">
            Button 1
          </Button>
          <Button type="primary">Button 2</Button>
          <Button type="primary">Button 3</Button>
        </Space.Compact>
      </Flex>
```
