### ISSUE TITLE
Table - ColumnProps onFilter not working

### ISSUE THREAD

**Issue by frsc** [ant-design/ant-design#21277]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
(sorry, didn't have time to fix)

### Steps to reproduce
```
  const columns: ColumnProps<Tenant>[] = [
    {
      title: 'Name',
      dataIndex: 'name',
      key: 'name',
      filteredValue: [filterByName],
      onFilter: (value, tenant) => {
        return tenant.name.toLowerCase().includes(value.toLowerCase());
      },
      defaultSortOrder: 'ascend',
      sorter: (a: Tenant, b: Tenant) => stringSort(a.name, b.name),
      render: (text: string, company: Tenant) => (
        <Link to={`/company/${company.id}`}>{text}</Link>
      ),
    },
  ];

```
This code is no longer working after upgrading to v4. 
The filteredValue is connected to our state, and our filter function "onFilter" is no longer trigged after the upgrade at all. 

### What is expected?
Filtering

### What is actually happening?
No Filtering, the onFilter callback is not even triggered 

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | React 16.12 |
| System | Mac OS Mojave 10.14.6 |
| Browser | Chrome Version 79.0.3945.130  |

**Comment by devuxer** [comment]
@afc163,

I just ran into this myself.

Here's a repro:
https://codesandbox.io/s/throbbing-morning-jpse9

**Comment by rgilmutdinov** [comment]
Hello, @afc163,

I use external component to manage `filteredValue` of a table column. But `onFilter` function is not triggered after value update.

Here is an example:
https://codesandbox.io/s/recursing-galois-soigv

Such filtering works in **v3**, but doesn't work in **v4**.

The only way I found in **v4** to get such a filter work is to set an empty array for the `filters` property. But in this case the filter icon becomes visible, which I would like to avoid.

**Comment by zombieJ** [comment]
Ah ha. Interesting usage. Let me fix.

**Comment by zombieJ** [comment]
Patch v3 demo: https://codesandbox.io/s/priceless-cookies-v3o6e

**Comment by myasul** [comment]
@zombieJ thank you! Been looking for the difference why it's not working on v4. Your sandbox saved me :)
