### ISSUE TITLE
建议可编辑Tabs的关闭标签在PC浏览状态下是默认隐藏，鼠标移上去时才显示

### ISSUE THREAD

**Issue by yruson** [ant-design/ant-design#21274]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
提供更良好的用户体验

### What does the proposed API look like?
建议可编辑Tabs的关闭标签在PC浏览状态下是默认隐藏，鼠标移上去时才显示
参考VS Code

**Comment by zombieJ** [comment]
Tabs 是可以设置单个标签禁止关闭的，hover 显示就不知道哪个是可以关系哪个不可以了。此外，你可以通过样式覆盖： https://codesandbox.io/s/lucid-star-6xn7o
