### ISSUE TITLE
table rowSelection问题

### ISSUE THREAD

**Issue by lifeneedspassion** [ant-design/ant-design#2127]
### 现在table要选中项必须添加rowSelection属性，之前版本rowSelection设为null是有用的，现在设为null会报错
主要考虑到如果表格没有数据，然而又需要显示一些自己的提示信息，把rowSelection设为{}，checkbox依然会和提示信息一起渲染

**Comment by afc163** [comment]
rowSelection 可以设为 null，我测试不会报错。最好给出重现。

**Comment by lifeneedspassion** [comment]
http://codepen.io/lifeneedspassion/pen/LZbEYm?editors=001

从
`null`
变为
`const rowSelection = {
  onChange: record => {},
  selectedRowKeys: []
}`
的时候会报错

**Comment by afc163** [comment]
感谢帮忙重现。
