### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by samit4me** [ant-design/ant-design#21271]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/samit4me/antd-testing-regenerator](https://github.com/samit4me/antd-testing-regenerator)

### Steps to reproduce
- git clone
- yarn
- yarn test

### What is expected?
All tests to pass

### What is actually happening?
`AntForm.test.js` is failing with `ReferenceError: regeneratorRuntime is not defined`

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 80 |

---
It appears that `<Input />` has some dependency on `rc-field-form` which is making use of the regenerator-runtime.

If you uncomment line 4 of `/src/setupTests.js` this error will go away as the react-app-polyfill package makes the regenerator-runtime available. Without this tests would be much faster.

This seems like it might be related to #20842

**Comment by afc163** [comment]
#21262
#20842
#21271

看上去是一个问题，@zombieJ 看看能不能无缝修复掉。

**Comment by zombieJ** [comment]
await father build 完会生成一个 regeneratorRuntime。我看看有没有办法配置掉。

**Comment by afc163** [comment]
@PeachScript 也可以关注一下。

**Comment by sorrycc** [comment]
regeneratorRuntime 得项目依赖，如果每个组件都有 regeneratorRuntime 可能会产生多份 regeneratorRuntime 。

**Comment by sorrycc** [comment]
https://github.com/umijs/father#runtimehelpers
试试开这个。

**Comment by zombieJ** [comment]
`+ rc-field-form@0.0.0-rc.3`

**Comment by samit4me** [comment]
For anyone else having this issue, to get the latest version of `rc-field-form` I needed to:
- `yarn remove antd`
- `yarn add antd@next`

**Comment by B1anker** [comment]
> `+ rc-field-form@0.0.0-rc.3`

这个要在自己的package.json里加？

**Comment by zombieJ** [comment]
不用，重新安装依赖即可

**Comment by hugobarragon** [comment]
> 不用，重新安装依赖即可

@zombieJ  not working for me :/, i removed antd and installed @next , removed pacakge-lock.json and installed again to update rc-field-form ,and it updated to rc.3 but its not working same error, am i doing something wrong?

**Comment by zombieJ** [comment]
@hugobarragon , could you patch the error log for more info? `rc-field-form@rc.3` not use `regeneratorRuntime`:

ref: https://unpkg.com/browse/rc-field-form@0.0.0-rc.4/lib/utils/validateUtil.js

**Comment by hugobarragon** [comment]
my error is not that one, from validateUtil is this one:
its the typescript defenition... i have placed the error log on the issue
from #20842
https://github.com/ant-design/ant-design/issues/20842#issuecomment-583059026
https://github.com/ant-design/ant-design/issues/20842#issuecomment-583309590
