### ISSUE TITLE
Clicking form submit button not triggering onFinish in unit test

### ISSUE THREAD

**Issue by samit4me** [ant-design/ant-design#21272]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/samit4me/antd-testing-form](https://github.com/samit4me/antd-testing-form)

### Steps to reproduce
- git clone
- yarn
- yarn test

### What is expected?
All tests to pass

### What is actually happening?
`AntForm.test.js` is failing as `onFinish` is never being triggered.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 80 |

---
You will see `Form.js` and `AntForm.js` which are both the same, one written with Ant components and the other with native DOM elements.

`Form.test.js` appears to be working fine.
`AntForm.test.js` is failing as clicking the submit button is not triggering `onFinish`.

If you do a `yarn start` you'll see that both forms work in a browser and if you run these tests in a codesandbox they also work, which I think is the case because Jest is running them tests in a browser.

At a guess it might have something to do with the `matchMedia` mocking inside `/src/setupTests.js`, but I'm unsure what else to try. At the moment it doesn't seem possible to use `antd`   `create-react-app`   `testing-library` together which is a real shame as these are 3 excellent libraries.

**Comment by zombieJ** [comment]
https://github.com/testing-library/react-testing-library/issues/54

**Comment by samit4me** [comment]
❌ `fireEvent.click(getByText("Submit"));`
✅ `fireEvent.submit(getByText("Submit"));`

I also tried `fireEvent.click` with [`jest-environment-jsdom-sixteen`](https://github.com/SimenB/jest-environment-jsdom-sixteen) and still did not work 😞

Strange how `fireEvent.click` works with native elements such as `<form>`  and `<button>` but not the antd components `<Form>` and `<Input>`.

Thanks for the help 👍

**Comment by VienNguyen113** [comment]
@zombieJ I'm having the same problem as @samit4me and I think using fireEvent.submit is just a workaround. This issue should be re-open

**Comment by VienNguyen113** [comment]
@zombieJ  Can you explain why testing submitting by clicking doesn't work with the Antd button

**Comment by sean-macfarlane** [comment]
@samit4me can you share your working code? I still cannot get this to work,  `expect(submitSpy).toHaveBeenCalled();` is always 0 for me even using `fireEvent.submit(getByText("Submit"));`

**Comment by samit4me** [comment]
@sean-macfarlane if you take a look at the **_[Reproduction link](https://github.com/samit4me/antd-testing-form)_** there is a file `AntForm.test.js`, which fails the test. To get it working, I had to change `fireEvent.click(getByText("Submit"));` to `fireEvent.submit(getByText("Submit"));` on lines 7 and 16. Hope that helps!

https://github.com/samit4me/antd-testing-form/blob/master/src/AntForm.test.js#L16

**Comment by Mikodin** [comment]
This is still an issue for me - even with using `fireEvent.submit(...)`

**Comment by ildarnm** [comment]
Same bug. I use Jest with Enzyme.
`    wrapper.find('button#login-button').simulate('click');`

**Comment by ildarnm** [comment]
**Updated:** 
After changing the 'click' to 'submit' and transferring the expect functions to setTimeout, it works.

```
  it('should call loginFetch on submit button click', (done) => {
    wrapper.find('button#login-button').simulate('submit');
    setTimeout(() => {
      expect(fetchLoginMocked).toHaveBeenCalledTimes(1);
      expect(fetchLoginMocked).toHaveBeenCalledWith(credential);
      done();
    }, 0);
  });
```

**Comment by Mikodin** [comment]
That is almost comedic!  Thank you @ildarnm that did the trick

**Comment by Mikodin** [comment]
You can also use the `waitFor` function in `react-testing-library` which is a little better imo
```typescript
await waitFor(() =>
  expect(fetchSignInSpy).toHaveBeenCalledWith(seedEmail, seedPassword)
);
```

**Comment by amitpatil321** [comment]
I am [retty new to jest and enzyme, I have spent the half day trying different solution, I thought something is wrong with my code or my understanding, But seems like its problem with others too. At least I can get sound sleep now.  


Did anyone get the solution? 
Below is what I think should work
```

    mockFunc = jest.fn();

    // set up Input, with mockFunc as a prop
    wrapper = shallow(<LoginContainerUnconnected onSubmit={mockFunc} />).dive();
    const submit = wrapper.find("Button[htmlType='submit']");
    submit.simulate("click", { preventDefault() {} });
    const clickFunc = mockFunc.mock.calls.length;
    expect(clickFunc).toBe(1);
```

**Comment by daemswibowo** [comment]
> **Updated:**
> After changing the 'click' to 'submit' and transferring the expect functions to setTimeout, it works.
> 
> ```
>   it('should call loginFetch on submit button click', (done) => {
>     wrapper.find('button#login-button').simulate('submit');
>     setTimeout(() => {
>       expect(fetchLoginMocked).toHaveBeenCalledTimes(1);
>       done();
>     }, 0);
>   });
> ```

This is not a solution actually. The expect not fired, when I change `.toHaveBeenCalledTimes` to 100 it didn't fail 😀

**Comment by Chevindu** [comment]
> > **Updated:**
> > After changing the 'click' to 'submit' and transferring the expect functions to setTimeout, it works.
> > ```
> >   it('should call loginFetch on submit button click', (done) => {
> >     wrapper.find('button#login-button').simulate('submit');
> >     setTimeout(() => {
> >       expect(fetchLoginMocked).toHaveBeenCalledTimes(1);
> >       done();
> >     }, 0);
> >   });
> > ```
> 
> This is not a solution actually. The expect not fired, when I change `.toHaveBeenCalledTimes` to 100 it didn't fail grinning

You might want to [mock the timers](https://jestjs.io/docs/en/timer-mocks) for that code block to execute.
```
jest.useFakeTimers();

// your test assertions with timeouts

jest.runOnlyPendingTimers();
```

**Comment by atanasov-deyan** [comment]
I also spent some good time trying to figure out why the test is failing. Switching to fireEvent.submit also did not help. wrapping the expect in a waitFor did the trick. Anyone found something more elegant?

**Comment by ldwonday** [comment]
`modal.find('form') .at(1).instance() .submit()` is worked for me!~

**Comment by stevula** [comment]
In our case there were some validations appearing that we didn't notice. I would recommend anyone with this problem try removing any validations (`<Form.Item rules={...}>`) from your form to see if that allows your `onFinish` handler to be called.

If your `onFinish` handler is called when you remove the validations, then you just have to figure out how to get your validations to play nice with your tests. For example you might have to enter some valid input and then wait for the validation to disappear using `awaitFor` since validations can be async.
