### ISSUE TITLE
onPanelChange is never be triggled

### ISSUE THREAD

**Issue by aqnaruto** [ant-design/ant-design#21287]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-meadow-jol3d)

### Steps to reproduce
https://codesandbox.io/s/condescending-meadow-jol3d

### What is expected?
work normally

### What is actually happening?
when i change the panel ,onPanelChange did not triggle

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12 |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
same as #20592

**Comment by afc163** [comment]
@zombieJ Any chance to fix it?

**Comment by aqnaruto** [comment]
> @zombieJ Any chance to fix it?

commit ed1872fe0812f57840685ba6d2c2d97da45c3f9f (HEAD -> master)
Author: zombieJ <smith3816@gmail.com>
Date:   Tue Feb 26 19:56:55 2019 +0800
------------------
切到了他提交的commit，还是没有改对。  应该改 rc-picker调用那里 ，两个箭头前饭后翻那儿加个事件。如果有更好的改进方法欢迎指正。我先改完自己用了。

**Comment by zombieJ** [comment]
<img width="453" alt="截屏2020-02-09上午11 19 33" src="https://user-images.githubusercontent.com/5378891/74095581-0f919780-4b2e-11ea-9963-6394624a3be7.png">

What's mean of can not trigger?

patch v3 demo: https://codesandbox.io/s/still-shape-8pbnx

**Comment by zombieJ** [comment]
Update:
`onPanelChange` is only trigger when panel change(like 'date' -> 'month', 'date' -> 'year'). It's expected not to trigger when month change.

We should add additional api like `onPickerValueChange` to handle this requirement.

**Comment by aqnaruto** [comment]
> Update:
> `onPanelChange` is only trigger when panel change(like 'date' -> 'month', 'date' -> 'year'). It's expected not to trigger when month change.
> 
> We should add additional api like `onPickerValueChange` to handle this requirement.

#6844 can you understand chinese .  if just change mode(like 'date' -> 'month', 'date' -> 'year') , call it onModeChange will be more appropriate

**Comment by zombieJ** [comment]
It's a breaking change to modify exist api behavior. #6844 is not correct since `onPanelChange` also not trigger in v3 as https://github.com/ant-design/ant-design/issues/21287#issuecomment-583800395 mentioned.

**Comment by aqnaruto** [comment]
@zombieJ   这个不算breaking change 吧，@afc163 在别的issue下提的，前后月份切换的时候 要支持，这些你都视而不见吗。
我找到了rc-picker的源码，也是你维护的。
在onInternalPanelChange 方法里判断解开限制 在到 onPrevMonth onNextMonth 里调用一下 不就ok了吗。前后改动才三四行代码。

**Comment by zombieJ** [comment]
嗯，复用了。

**Comment by zombieJ** [comment]
ref https://github.com/react-component/picker/pull/26
