### ISSUE TITLE
Input: form item Input size error with prefix and suffix

### ISSUE THREAD

**Issue by yoyo837** [ant-design/ant-design#21288]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/withered-mountain-tjnhj)

### Steps to reproduce
switch the form size,

### What is expected?
Input size works fine with prefix and suffix

### What is actually happening?
not works

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | latest |
| System | MacOS latest |
| Browser | Chrome latest |

**Comment by afc163** [comment]
Input.Password is not working either.
