### ISSUE TITLE
[4.0] Feature: Align Radio and Checkbox APIs

### ISSUE THREAD

**Issue by mgcrea** [ant-design/ant-design#21280]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

Design-wise, we lack direct equivalents like the `<Radio.Button />` elements for checkboxes.

Usually you tend to use radios and checkboxes in a very similar manner, but currently it's a pain to redesign a component from scratch to align designs.

### What does the proposed API look like?

Add `<Checkbox.Button />` to mirror the radio API.

Could work on it if you want.

**Comment by afc163** [comment]
Sorry, there is not checkbox button in our design language.
