### ISSUE TITLE
Modal does not close with default behavior of maskClosable or keyboard

### ISSUE THREAD

**Issue by specialorange** [ant-design/ant-design#21283]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-napier-fmcry)

### Steps to reproduce
Include the parameters                 keyboard={true} or maskClosable={true} in the Modal declaration

### What is expected?
the Modal should close with by pressing the `esc` key or clicking outside the modal

### What is actually happening?
the modal is not closing in either case

| Environment | Info |
|---|---|
| antd | undefined |
| React | latest |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
https://codesandbox.io/s/k9oplll2k5

https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by specialorange** [comment]
Please review this, as I specified the use case exactly, by NOT using the `onCancel` callback/event handler.   I specifically documented the `maskClosable` and the `keyboard` attributes not functioning.    The docs do not say that the `onCancel` attribute is required.   The link previously provided, ( https://codesandbox.io/s/frosty-napier-fmcry ) clearly shows the issue.

I am trying to be as specific as possible, but this is the third ticket you have closed without addressing the root problem.   If you need additional documentation please ask before closing the issue.   It makes it more difficult to justify growing contributions to a particular open source if the issues are closed by the same person quickly without asking for clarification.

**Comment by afc163** [comment]
You have to use `onCancel` to control value, or visible is always `false` in your state.
