### ISSUE TITLE
[4.0 RC3] Form initialValues 无法加载对象形式的value

### ISSUE THREAD

**Issue by MingRock** [ant-design/ant-design#21286]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-almeida-zyp62)

### Steps to reproduce
-

### What is expected?
-

### What is actually happening?
check1无法加载对象形式的value,check2可以加载

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | LinuxMint |
| Browser | Chrome 79.0.3945.130 |

---
有没有其他方法获取checkbox的label值

**Comment by afc163** [comment]
和 Form 没关系，Check.Group 不能这么用，因为 `{ label: "a", value: "1" } === { label: "a", value: "1" }` 是 `false`。

https://codesandbox.io/s/cool-darkness-1gu0r
