### ISSUE TITLE
Input buttons hides behind suggestions in the mobile devices.

### ISSUE THREAD

**Issue by bhavikji** [ant-design/ant-design#21285]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7oypm)

### Steps to reproduce
Open the demo of Antd Autocomplete in codesandbox to reproduce the issue the screen size should be 5.2 inches or below, I tested the link from 5.2 inches to 6.5 inches it is working fine in the bigger device. I have faced this issue in my project where I am using ant design for designing so for verification I tested the demo given in sandbox and facing the same issue there as well.

### What is expected?
It should not hide the input field as user is unable to see what he is typing because of the list overlapping it

### What is actually happening?
As the user clicks to type in autocomplete component, it is overlapping the input which causes the input to hide and thus the user cannot see what he is typing.

| Environment | Info |
|---|---|
| antd | 3.19.5 |
| React | 16.8.6 |
| System | Android Marshmallow  |
| Browser | 80 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/15688#issuecomment-477065182

**Comment by bhavikji** [comment]
@afc163 : then is there anything link Autocomplete in mobile how can we create a component like autocomplete in antd mobile?
