### ISSUE TITLE
移动端进入官网很卡

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#2129]
iPhone6

**Comment by afc163** [comment]
@jljsj33 在移动端把动画替换或干掉如何？

**Comment by dyf2015** [comment]
是不是显示组件太多，是否可以做懒加载处理？

发自我的 iPhone

在 2016年6月21日，21:58，偏右 <notifications@github.com<mailto:notifications@github.com>> 写道：


@jljsj33<https://github.com/jljsj33> 在移动端把动画替换或干掉如何？

―

**Comment by zhaoqize** [comment]
PC端都很卡

**Comment by afc163** [comment]
这里有个动画不停地动，改掉后应该会好一点。

**Comment by jljsj33** [comment]
哪个啊？

**Comment by jljsj33** [comment]
首页不是移动端的没做嘛。。。
