### ISSUE TITLE
button group large size under antd 4.0 style error

### ISSUE THREAD

**Issue by vthinkxie** [ant-design/ant-design#21295]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-kvezaa?file=index.js](https://stackblitz.com/edit/react-kvezaa?file=index.js)

### Steps to reproduce
size error

### What is expected?
size ok

### What is actually happening?
size error

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | all |
| System | macos |
| Browser | chrome lastest |

**Comment by yoyo837** [comment]
It seems all work fine.

**Comment by yoyo837** [comment]
Your reproduction `antd` version is 3.26.9.

**Comment by zombieJ** [comment]
Patch reproduce: https://codesandbox.io/s/sharp-lake-rbcb2
