### ISSUE TITLE
RangePicker 选择周范围

### ISSUE THREAD

**Issue by jiayuu** [ant-design/ant-design#21308]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以选择周的范围 就像月一样 选择第一周到第三周

### What does the proposed API look like?
mode={['week', 'week']}

**Comment by afc163** [comment]
https://next.ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker

Try 4.x
