### ISSUE TITLE
table设置了scroll和fixed之后第一列显示不出来。

### ISSUE THREAD

**Issue by ranzhu123** [ant-design/ant-design#2130]
可以看一下官方例子，我的本地和官方一样。
![image](https://cloud.githubusercontent.com/assets/12227617/16253450/3d7d1290-3869-11e6-9039-11d8572bef18.png)

**Comment by afc163** [comment]
感谢反馈。

1. 在 Chrome 下，`td` 的 `white-space: nowrap;` 会影响单元格的宽度。
2. 这里去掉了 `white-space: nowrap;`，也优化了固定列时内容不能换行的问题。
3. 另外在 rc-table 里修复了固定表头垂直滚动时 `scrollTop is undefined` 的错误。

**Comment by ranzhu123** [comment]
把scroll设置好之后问题就解决了，设置为true不管用，得计算，现在没问题了，多谢
