### ISSUE TITLE
Menu导航菜单在切换Item时出现延迟和卡顿以及展开和收缩时出现抖动。

### ISSUE THREAD

**Issue by TianEnPang** [ant-design/ant-design#21301]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/menu-cn/#components-menu-demo-inline-collapsed](https://next.ant.design/components/menu-cn/#components-menu-demo-inline-collapsed)

### Steps to reproduce
1，使用 `create umi` 新建包含 antd 4.x.x 版本的 Ant design pro 项目，运行后会发现左侧 Menu 组件 

     * 在切换 Item 时出现点击后 "选中背景颜色" 延迟。

     * "选中背景颜色"在移动时的动画卡顿的情况。

     * 在有二级菜单情况下展开和收缩时会出现抖动。

2，"重现链接" 中也有相同问题。

### What is expected?
期望下次更新时修复此问题。

### What is actually happening?
同上"重现步骤"中的问题。

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | ^16.8.6 |
| System | Windows 10 Pro version 1909 |
| Browser | 【Chrome 80.0.3987.87】 & 【Edge 80.0.361.48】 |

---
左侧 Menu 为经常使用的组件，出现此问题大大降低体验感。

**Comment by TianEnPang** [comment]
1，以下为延迟和卡顿的效果 

![demo](https://user-images.githubusercontent.com/32772271/74100449-f1e22380-4b69-11ea-89c6-ab6bdc81c054.gif)

2，展开和收缩时抖动的效果可以查看 [重现链接](https://next.ant.design/components/menu-cn/#components-menu-demo-inline-collapsed)

**Comment by afc163** [comment]
> 在有二级菜单情况下展开和收缩时会出现抖动

这个确实有。

**Comment by afc163** [comment]
Broken by https://github.com/ant-design/ant-design/pull/21109

**Comment by qiangguyidi** [comment]
Menu导航菜单在切换Item时出现延迟和卡顿

**Comment by okwen5566** [comment]
请问这个卡顿问题有解决吗？当item数量多了后，50,60的时候，切换item要5、6秒后才会切到新的页面

**Comment by yoyo837** [comment]
请带复现开一个新问题。
