### ISSUE TITLE
validateFirst option prevents form submit

### ISSUE THREAD

**Issue by samit4me** [ant-design/ant-design#21305]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-wave-nwmwc)

### Steps to reproduce
- Enter "test" into username
- Enter some text into password
- Click Submit

### What is expected?
The form to submit and the Success message to be output in the console.

### What is actually happening?
There is two issues:
- onFinish is not getting triggered, so nothing is output to the console.
- Warning: React does not recognize the `validateFirst` prop on a DOM element.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.12.0 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Chrome 80 |

---
If you remove the `validateFirst` prop from the username `Form.Item` then the form works and the error message goes away, but then the issue of duplicate error messages exists.

See #21178

**Comment by zombieJ** [comment]
Your reproduce work as expect:
![Kapture 2020-02-10 at 10 37 51](https://user-images.githubusercontent.com/5378891/74117109-762bb980-4bf1-11ea-8cdb-f8b245212b17.gif)

**Comment by samit4me** [comment]
This is what I see when visiting https://codesandbox.io/s/youthful-wave-nwmwc

![example](https://user-images.githubusercontent.com/3248531/74118125-d62c5b00-4c05-11ea-84f8-165b316697c2.gif)

**Comment by samit4me** [comment]
To eliminate any weirdness with codesandbox I created a small repo to demonstrate the problems.
https://github.com/samit4me/antd-validatefirst

Issues with `validateFirst`:

1. `Warning: React does not recognize the `validateFirst` prop on a DOM element`
1. `onFinish` is NOT called when rules and validator both pass validation.
1. `onFinish` is called when rules pass, but validator fails (e.g. `Promise.reject`).

Steps to reproduce:

- `yarn`
- `yarn start`

React warning:
- Open console in browser to see Warning.

`onFinish` not called:
- Enter username "test" for both forms.
- Click Submit on "form 1" - "Success" output to console.
- Click Submit on "form 2" - no output to console (it should).

`onFinish` called:
- Enter username "ant" for both forms.
- Click Submit on "form 1" - "Failed" output to console.
- Click Submit on "form 2" - "Success" output to console (should be Failed).
