### ISSUE TITLE
nested field errors handling

### ISSUE THREAD

**Issue by akaguny** [ant-design/ant-design#21313]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-lehmann-tntk8-tntk8)

### case 1
1. open sandbox
2. check the console

expected:
```
FormFieldUsername errors ["Please input your username!"]
```
actual:
```
FormFieldUsername errors []
```

### case 2
1. open sandbox
2. see username field

expected:
username not red
actual:
username red

### What is expected?
see steps

### What is actually happening?
see steps

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google chrome Version 79.0.3945.130 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
### case 1

You call `form.getFieldError` before Field render, thus there are no error fetch.

### case 2

`help=''` is also a error message. So it turns read. You can control `validateStatus` to modify its status.

**Comment by shifraHolzer** [comment]
This was my exact problem. Thanks @zombieJ, saved me lots of code trawling....
