### ISSUE TITLE
Tree组件样式错误

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#21318]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-elgamal-6wq9n?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1、所有TreeNode 设置属性为 disabled=true
2、设置Tree的checkedKeys为{checked,halfCheckedKeys}

### What is expected?
TreeNode在disabled下halfCheckedKeys样式正确，为方框半选状态

### What is actually happening?
TreeNode在disabled下halfCheckedKeys样式错误，方框无勾选

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | latest |
| System | win10 |
| Browser | chrome80 |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/competent-albattani-i9ucv

**Comment by XianZhengquan** [comment]
但是这个应该算是bug啊，在不禁用的情况下，设置halfCheckedKeys能正常的渲染半选状态，但是在禁用的情况下就不能渲染

**Comment by zombieJ** [comment]
没懂，禁用不能渲染指的是？

<img width="156" alt="截屏2020-02-11下午3 38 49" src="https://user-images.githubusercontent.com/5378891/74218247-9d16e800-4ce4-11ea-8b23-73a3d5bdeb5d.png">

**Comment by XianZhengquan** [comment]
@zombieJ  就是这个节点前面的勾选框应为 半选状态

**Comment by XianZhengquan** [comment]
![image](https://user-images.githubusercontent.com/46179450/74218412-0139ac00-4ce5-11ea-9167-dd56c345af18.png)
这里应该是半选状态

**Comment by XianZhengquan** [comment]
但是在disabled的状态下，没有渲染成 半选的状态，也就是 `indeterminate` 为true的状态

**Comment by zombieJ** [comment]
用 `checkStrictly`

**Comment by XianZhengquan** [comment]
解决了，是我一直把 ` checkedKeys` 里面的 `halfChecked` 打错了
