### ISSUE TITLE
Online coding website Icon issue

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#21317]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/button-cn/#components-button-demo-icon](https://next.ant.design/components/button-cn/#components-button-demo-icon)

> 其他组件涉及 Icon 组件均存在该问题

#### 点击 ”在 CodePen 中打开”
- 由于 4.0 中改用 '@ant-design/icons' 方式
- CodePen Setting 中是使用 unpkg 引入 css js

#### 点击 ”在 CodeSandbox 中打开”
- package.json 中使用 `@ant-design`，而不是`@ant-design/icons`

#### 点击 ”在 Stackblitz 中打开”
- package.json 中 `dependencies`为空，未定义`react` `react-dom` `antd` `@ant-design/icos`

### What is expected?
打开 online coding 网站，可以直接进行编辑，而不需要额外调整配置

### What is actually happening?
打开 online coding 网站，控制台报错，需要额外调整配置

> PS. 感觉应该是要去相应的coding网站中去调整配置。

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
Stackblitz has bug can not handle correct deps tag like `next`. Seems we need remove it in web site tmply.

**Comment by zombieJ** [comment]
Create an issue to stackblitz: https://github.com/stackblitz/core/issues/1179
