### ISSUE TITLE
Input.Group 下的Input校验的时候不提示校验信息。

### ISSUE THREAD

**Issue by wangdao** [ant-design/ant-design#2131]
![_20160622113033](https://cloud.githubusercontent.com/assets/3746762/16253933/a82d8a80-386d-11e6-95ca-f800f2f0dd11.png)
![_20160622113053](https://cloud.githubusercontent.com/assets/3746762/16253934/a82f4d16-386d-11e6-8dfc-1a07b834d09d.png)

**Comment by heyi** [comment]
同样遇到这个问题，
![image](https://cloud.githubusercontent.com/assets/1179505/16257997/430276fe-388e-11e6-9a69-32fff9612ef6.png)

**Comment by heyi** [comment]
未升级到1.5之前是可以的。。我采取是比较hack的写法。
![image](https://cloud.githubusercontent.com/assets/1179505/16258050/871f79b8-388e-11e6-8cd8-d616c4a1981a.png)

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by wangdao** [comment]
@afc163 
http://codepen.io/wangdao/pen/dXNMjP?editors=001

能给 InputGroup 整体加上验证，我觉得更好。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/jAwVAE?editors=0010

**Comment by wangdao** [comment]
@afc163 谢谢
要显示校验信息，输入控件上级必须是Form.Item吧？

**Comment by afc163** [comment]
貌似是的。

**Comment by taditang** [comment]
因为getFieldProps的上层必须为FormItem, 所有可以使用多重FormItem来解决, 代码样式不会编辑，见谅．
如：
<FormItem>
<InputGroup>
<FormItem>
<Input {...getFieldProps(`${linkman_prefix}_phone_${index}_phone_number`, getFieldOption('phone'))} type="text" autoComplete="off"/>
<div className="ant-input-group-wrap">
            <Button icon="search" className={btnCls} size={size} onClick={this.handleSearch} />
</div>
</FormItem>
</InputGroup>
</FormItem>

**Comment by benjycui** [comment]
其实校验样式和文案自动生成只是为了减少模板代码。。。

**Comment by benjycui** [comment]
也可以手动设置，见：https://ant.design/components/form/#Form.Item
