### ISSUE TITLE
input suffix & addon border radius error

### ISSUE THREAD

**Issue by vthinkxie** [ant-design/ant-design#21311]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-diffie-guwc2)

### Steps to reproduce
visit the page

### What is expected?
border radius style correct

### What is actually happening?
border radius style error

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | lastest |
| System | macos |
| Browser | chrome lastest |

**Comment by afc163** [comment]
https://next.ant.design/components/input-cn/#components-input-demo-size

Broken style in firefox too.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/507615/74121614-2d7cfc00-4c03-11ea-8c3f-9e805a630e5c.png">

**Comment by afc163** [comment]
https://next.ant.design/components/input-cn/#components-input-demo-allowClear

<img width="617" alt="image" src="https://user-images.githubusercontent.com/507615/74121662-6e751080-4c03-11ea-87a2-f1c37879e0d4.png">

Different padding with 3.x

<img width="635" alt="image" src="https://user-images.githubusercontent.com/507615/74121676-7d5bc300-4c03-11ea-9b6a-8c5786b7c124.png">

**Comment by zombieJ** [comment]
> https://next.ant.design/components/input-cn/#components-input-demo-allowClear
> 
> <img alt="image" width="617" src="https://user-images.githubusercontent.com/507615/74121662-6e751080-4c03-11ea-87a2-f1c37879e0d4.png">
> 
> Different padding with 3.x
> 
> <img alt="image" width="635" src="https://user-images.githubusercontent.com/507615/74121676-7d5bc300-4c03-11ea-9b6a-8c5786b7c124.png">

TextArea reuse suffix style seems a bug should be fix.

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/pull/19310/files#diff-24058e4203928f9583925171815fe25dR62

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/74129384-670d3180-4c1a-11ea-8cd1-0adf0d53e45f.png)

这里还有个。
