### ISSUE TITLE
Table 搜索与重写展示是否有冲突

### ISSUE THREAD

**Issue by JoyNop** [ant-design/ant-design#21339]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exciting-sky-bg1n1?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
这里有一个表格Table ，也是官方文档中的例子，在name,age两列，通过column的render重写展示的内容，提供高亮和搜索

`<Paragraph ellipsis={{ rows: 1, expandable: true }}>{text}</Paragraph>`

因为他提供了一个`expland`功能

并为这两列添加搜索功能

```
 const columns = [
      {
        title: "Name",
        dataIndex: "name",
        key: "name",
        width: "30%",
        ...this.getColumnSearchProps("name"),
        render: (text: any) => (
          <Paragraph ellipsis={{ rows: 1, expandable: true }}>{text}</Paragraph>
        )
      },
      {
        title: "Age",
        dataIndex: "age",
        key: "age",
        width: "20%",
        render: (text: any) => (
          <Paragraph ellipsis={{ rows: 1, expandable: true }}>{text}</Paragraph>
        ),
        ...this.getColumnSearchProps("age")
      },
      {
        title: "Address",
        dataIndex: "address",
        key: "address",
        ...this.getColumnSearchProps("address")
      }
    ];
```

### What is expected?
如何 既能正常使用`Paragraph`的`expland`功能，又能继续使用搜索高亮

### What is actually happening?
- 在`name`列中，`this.getColumnSearchProps("name"),`先于  render，`Paragraph`的`expland`可以正常展示，但是搜索并没有显示高亮
- 在`age`中，` render`先于 `this.getColumnSearchProps("name")`，`Paragraph`的`expland`功能失效，将展示完整数据而不折叠，显然render并没有生效，但是搜索有高亮

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | react16.12 |
| System | windows 10  |
| Browser | 80.0.3987.87 |

**Comment by afc163** [comment]
高亮的例子建议自行排查改造，这只是个例子，没办法满足各种特殊情况下的配合使用。

**Comment by JoyNop** [comment]
> 高亮的例子建议自行排查改造，这只是个例子，没办法满足各种特殊情况下的配合使用。

事实上并不只是高亮，搜索`getColumnSearchProps`中的render貌似与`column`中render()有冲突，

**Comment by afc163** [comment]
这不是 antd 本身的问题，注意写的时候不要把前面的 render 覆盖了。
