### ISSUE TITLE
Table is not rerendered

### ISSUE THREAD

**Issue by scythargon** [ant-design/ant-design#21335]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-hopper-wly0x)

### Steps to reproduce
Click to any "Reload" action in the table, see that nothing happens. You can see the logging if open the browser console window.

### What is expected?
When "Reload" action is pressed I expect to see a spinner for 2 seconds on it's place and the "Reload" word again.

### What is actually happening?
Event handlers are fired but the component is not rerendered. 

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.12.0 |
| System | Ubuntu 19.10 |
| Browser | Chromium 73.0.3683.103 |

---
Locally I have the same issue but with Mobx as a data layer - there I need to move my cursor away from the table row or back for it to be rendered again, which is also not the behavior I expect. Thank you.

**Comment by SiHao24** [comment]
从哪个版本把current.target里面的selectionStart这个属性去掉了？
