### ISSUE TITLE
How to adjust the distance of the tooltip from the content

### ISSUE THREAD

**Issue by wangdanting** [ant-design/ant-design#21337]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tooltip can adjust the distance from the content

### What does the proposed API look like?
distance

**Comment by zombieJ** [comment]
You can use align:
```jsx
<Tooltip align={{ offset: [100, 200]  }} />
```

PS: This is a internal api which not list in doc but you can safe to use it.

**Comment by LeMorlalala** [comment]
how to adjust "align={{ offset: [100, 200]  }}" by its real placement?
