### ISSUE TITLE
Could we have an optional accordion prop on <Table/> much like <Collapse/> has, if the Table has the expandedRowRender prop?

### ISSUE THREAD

**Issue by yvzakn** [ant-design/ant-design#21330]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It will provide the ability to have an accordion type Collapse on Tables.

### What does the proposed API look like?
Prop name: accordion
Type: boolean
Default: false

**Comment by afc163** [comment]
We may not add `accordion` prop to Table, you can do it by control `expandedRowKeys`.
