### ISSUE TITLE
Collapse Panel with extra prop

### ISSUE THREAD

**Issue by rever96** [ant-design/ant-design#21346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rjznr)

### Steps to reproduce
Create a Collapse with Panels that have extra prop with high height and move it at the header line-height. Thats create a big vertical empty space in the panel header.

### What is expected?
I would have an access to modify the header dimension or that the panel header doesn't get resized when extra is relative

### What is actually happening?
The extra's container space is taken in the header panel even if it is not occuping that space.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | react 16.12.0 |
| System | linux |
| Browser | chrome |

**Comment by afc163** [comment]
It is not a antd issue, please handle your custom css well.

**Comment by rever96** [comment]
oh, you are right, thanks for the advice.
I've solved using `absolute` instead of `relative` as extra styling position.
