### ISSUE TITLE
Typography.Paragraph 上移了一点

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#21340]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/pro-table/issues/129](https://github.com/ant-design/pro-table/issues/129)

### Steps to reproduce
https://github.com/ant-design/pro-table/issues/129

![image](https://user-images.githubusercontent.com/18542211/74240491-10d0e900-4d15-11ea-8749-e9e7d72bb98d.png)

### What is expected?
保持一条线上对齐

### What is actually happening?
上移了一点，在table是就将row变大了

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by kaoding** [comment]
https://codesandbox.io/s/antd-reproduction-template-wp0r1

**Comment by afc163** [comment]
Paragraph 的语义是段落，和原生 p 标签一样会带一个 margin-bottom。单元格内的文本场景应该使用 Typography.Text。

**Comment by kaoding** [comment]
> Paragraph 的语义是段落，和原生 p 标签一样会带一个 margin-bottom。单元格内的文本场景应该使用 Typography.Text。

那 pro-table 里就不应用用 Typography.Paragraph ，而应用使用 Typography.Text 才正确。

**Comment by afc163** [comment]
对的，用错了。
