### ISSUE TITLE
v4 Select value in Form onFinish undefined

### ISSUE THREAD

**Issue by matthewlein** [ant-design/ant-design#21349]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-sound-r0mnv)

### Steps to reproduce
1. Type in a search in the Select input
2. Choose a result
3. Submit form
4. See console logged values undefined.

### What is expected?
I would expect the form value to match the Select element's value.

### What is actually happening?
The form value is undefined.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.12.0 |
| System | MacOSX  |
| Browser | All/Chrome |

**Comment by afc163** [comment]
https://next.ant.design/components/form/#components-form-demo-customized-form-controls

You forgot `onChange` of `SearchInput`.

**Comment by matthewlein** [comment]
I understand now, thanks. This worked previously in v3 without `onChange`
