### ISSUE TITLE
Select with showSearch enabled ALWAYS clears input

### ISSUE THREAD

**Issue by JayCodist** [ant-design/ant-design#21347]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-sorqk)

### Steps to reproduce
1. Open drop-down and type in part of intended input
2. Close drop-down.
3. Reopen drop-down to continue typing in the input

### What is expected?
It is expected that when you reopen the drop-down, you would be able to continue entering the input from where you left off

### What is actually happening?
The drop-down simply displays the previous input as some kind of placeholder and starts afresh upon further input, discarding the previous input

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.7.0 |
| System | Windows 8.0 |
| Browser | Google Chrome version 79 |

---
I understand that most of the time, this default behavior is desirable. But I was hoping there was a way of turning off this behavior, so the user could continue from where he left off, when he reopened the drop-down, as it is what my current app requires.

I can't seem to find a workaround as it appears that while I can set the "value" property of the Select component, I cannot directly change the search input value while the user is typing into the component

**Comment by afc163** [comment]
It is intended behavior that we won't change it probabily.

Could you try AutoComplete?

**Comment by JayCodist** [comment]
Yes. That works fine. Thank you!
