### ISSUE TITLE
能否照顾一下我们中国用户？Ant Design 系列的预览和文档 查看已经是灾难性操作，长等待或不响应

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design#21353]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
浏览速度正常

### What does the proposed API look like?
浏览速度正常

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19244#issuecomment-542561291

**Comment by admiao** [comment]
> [#19244 (comment)](https://github.com/ant-design/ant-design/issues/19244#issuecomment-542561291)

V4的呢

**Comment by afc163** [comment]
v4 要等一下正式发布。

或者等十分钟我用 gitee 同步一个网站出来。

**Comment by afc163** [comment]
可以了 https://antd-v4.gitee.io/index-cn

**Comment by admiao** [comment]
谢谢
