### ISSUE TITLE
Dropdown is not accessible (via keyboard)

### ISSUE THREAD

**Issue by manzoorwanijk** [ant-design/ant-design#21357]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown/#](https://ant.design/components/dropdown/#)

### Steps to reproduce
- Click on the dropdown trigger
- Try navigating with keyboard (Arrow/Tab)

### What is expected?
It should navigate through the items.

### What is actually happening?
It instead scrolls the whole page

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | 16 |
| System | Win 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Use `getPopupContainer` to set popup inline of the container that you can use tab for active element switch.

**Comment by manzoorwanijk** [comment]
It doesn't work. Here is the demo with `getPopupContainer`
[https://codesandbox.io/s/kdkcq](https://codesandbox.io/s/kdkcq)

**Comment by zombieJ** [comment]
Highlight the a element when focus:
![Kapture 2020-02-22 at 20 37 47](https://user-images.githubusercontent.com/5378891/75092524-54e4a900-55b3-11ea-8748-37fd6498a579.gif)


ref: https://codesandbox.io/s/nervous-visvesvaraya-cee18
