### ISSUE TITLE
Carousel 组件的 slidesToShow 和 slidesToScroll 一起使用会导致最后一页的有些 slide pointer-event 为 none

### ISSUE THREAD

**Issue by Jiang-Xuan** [ant-design/ant-design#21359]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-shape-b2gul)

### Steps to reproduce
1. 将轮播图滚动到最后一页
2. 将鼠标分别 hover 第 4 和 第 5

### What is expected?
第 4 个轮播图响应鼠标 hover, 文字颜色变为红色

### What is actually happening?
文字没有变色

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | 16.8.6 |
| System | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 |

---
看起来是 react-slide 造成的 bug, 第 4 个轮播图的 pointer-event 是 none, 没有变成 auto

**Comment by Jiang-Xuan** [comment]
@afc163 @zombieJ

**Comment by zombieJ** [comment]
`slidesToShow` 和 `slidesToScroll` 不是我们文档里的方法，如果使用了建议直接给 `react-slick` 开 issue。
