### ISSUE TITLE
form表单可以收集对象数组

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#21366]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
表单需要收集一个对象数组：
```
fileds:[{
  name:'a',
  age:14
},{
  name:'b',
  age:15
},{
  name:'c',
  age:16
}]
```

### What does the proposed API look like?
form.item的name可以做如下设置
```
name={['fileds[0]','name']}
name={['fileds[0]','age']}
name={['fileds[1]','name']}
name={['fileds[1]','age']}
```

**Comment by zombieJ** [comment]
`name={['fileds', 0, 'name']}`

**Comment by jianghai** [comment]
> `name={['fileds', 0, 'name']}`

拿到的还是一个对象：fileds: {0: {name: 'xx'}}
