### ISSUE TITLE
Modal prop iconClassName not working

### ISSUE THREAD

**Issue by JoeCMorgan** [ant-design/ant-design#21367]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-oniyd?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Create a confirm modal
Add the iconClassName prop
Inspect element to check if class has been applied to icon

### What is expected?
Class to be applied to icon

### What is actually happening?
The class specified is not being added to the icon

| Environment | Info |
|---|---|
| antd | 3.19.2 |
| React | 16.8.1 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
Modal.confirm do not support `iconClassName`, the TypeScript prop definition is a mistake and I will remove it.
