### ISSUE TITLE
Horizontal Steps switches to vertical with small size screen

### ISSUE THREAD

**Issue by rufusnguyen** [ant-design/ant-design#21371]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zd9td)

### Steps to reproduce
- Render any Steps components with default direction (horizontal)
- Resize screen to small (i.e: width 320px) 

### What is expected?
Steps is switched to vertical direction 

### What is actually happening?
Steps is in still horizontal 

| Environment | Info |
|---|---|
| antd | 3.22.2 |
| React | 16.8.4 |
| System | Windows |
| Browser | Chrome |

---
Do we have to force that auto-responsive-correct to display fixed direction?

**Comment by afc163** [comment]
It is by designed.

**Comment by yoyo837** [comment]
Duplicated of #21294
