### ISSUE TITLE
provide v4 component documentation on https://ant.design/

### ISSUE THREAD

**Issue by SamMaxwell** [ant-design/ant-design#21372]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
allows developers to start using antd v4

### What does the proposed API look like?
the version selector at the top of the page would allow the user to select 4.0-rc

**Comment by afc163** [comment]
https://next.ant.design

**Comment by yoyo837** [comment]
After the official release of 4.0.0, it will be migrated to ant.design, it's RC at the moment.

**Comment by SamMaxwell** [comment]
thanks. I am sorry for my confusion.
