### ISSUE TITLE
v4 app bundle size bigger than v3

### ISSUE THREAD

**Issue by matthewlein** [ant-design/ant-design#21374]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://example.com/reproduction-not-needed](http://example.com/reproduction-not-needed)

### Steps to reproduce
Update an app from v3 to v4

### What is expected?
Based on bundlephobia and the documentation, I expected bundle size to go down.

### What is actually happening?
Bundle size is up.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.12.0 |
| System | MacOSX  |
| Browser | all |

---
The only updates in this build are:

```
"@ant-design/icons": "4.0.0-rc.0",
"antd": "3.26.8", -> "antd": "4.0.0-rc.4",
```

Webpack verison: `"webpack": "4.41.5"`

I tried using babel-plugin-import as well but got the same build size

V3
<img width="417" alt="Screen Shot 2020-02-13 at 1 58 48 PM" src="https://user-images.githubusercontent.com/454758/74477257-90bf9600-4e70-11ea-93ef-6d93d3b5fbd5.png">
V4
<img width="419" alt="Screen Shot 2020-02-13 at 2 09 26 PM" src="https://user-images.githubusercontent.com/454758/74477275-9b7a2b00-4e70-11ea-80ee-57cc155c9e15.png">

Parsed sizes are up ~300k, gzipped ~60k

**Comment by matthewlein** [comment]
I should clarity—I use have been using babel-plugin-import successfully for v3 builds, I added another section for @ant-design/icons to see if that would help, since that was showing up as larger parsed size in the v4 builds.
```
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es"
        // "style": true
      },
      "import-antd"
    ],
    [
      "import",
      {
        "libraryName": "@ant-design/icons",
        "libraryDirectory": "es/icons",
        "camel2DashComponentName": false
      },
      "import-antd-icons"
    ],
```

**Comment by faradaytrs** [comment]
> I should clarity—I use have been using babel-plugin-import successfully for v3 builds, I added another section for @ant-design/icons to see if that would help, since that was showing up as larger parsed size in the v4 builds.
> 
> ```
>     [
>       "import",
>       {
>         "libraryName": "antd",
>         "libraryDirectory": "es"
>         // "style": true
>       },
>       "import-antd"
>     ],
>     [
>       "import",
>       {
>         "libraryName": "@ant-design/icons",
>         "libraryDirectory": "es/icons",
>         "camel2DashComponentName": false
>       },
>       "import-antd-icons"
>     ],
> ```

you need to remove icons from babel-plugin-import and it will do everything automatically. It worked for me

**Comment by faradaytrs** [comment]
> > I should clarity—I use have been using babel-plugin-import successfully for v3 builds, I added another section for @ant-design/icons to see if that would help, since that was showing up as larger parsed size in the v4 builds.
> > ```
> >     [
> >       "import",
> >       {
> >         "libraryName": "antd",
> >         "libraryDirectory": "es"
> >         // "style": true
> >       },
> >       "import-antd"
> >     ],
> >     [
> >       "import",
> >       {
> >         "libraryName": "@ant-design/icons",
> >         "libraryDirectory": "es/icons",
> >         "camel2DashComponentName": false
> >       },
> >       "import-antd-icons"
> >     ],
> > ```
> 
> you need to remove icons from babel-plugin-import and it will do everything automatically. It worked for me

What's result of source-map-explorer build/static/js/*.js?

**Comment by matthewlein** [comment]
@faradaytrs I tried all ways with babel-plugin-import, same as v3, adding icons, removing all. Nothing came out smaller than v3.

Here is a v4 build with no babel-plugin-import at all:

<img width="1698" alt="Screen Shot 2020-02-14 at 9 42 31 AM" src="https://user-images.githubusercontent.com/454758/74545990-738dd480-4f0f-11ea-9445-5ae21a374752.png">

It looks to me like something in the antd library is importing all the icons and not working with tree shaking. The large icon import comes from antd/node_modules
./node_modules/antd/node_modules/@ant-design/icons/es/index.js + 1483 modules (concatenated) (721.82 KB)

v3 icons were 490k

All my icon imports were done by the codemod, all in the format `import { CopyOutlined } from '@ant-design/icons'`

**Comment by faradaytrs** [comment]
I use CRA and my config looks like that, it works properly as i expected. I did no add config for icons.

```
const {override, fixBabelImports, addLessLoader} = require("customize-cra");

module.exports = override(
    fixBabelImports("antd", {
        libraryName: "antd",
        libraryDirectory: "es",
        style: true,
    }),
    addLessLoader({
        javascriptEnabled: true,
        modifyVars: {},
    }),
);
```

**Comment by matthewlein** [comment]
rc5 changed an import of `AntdIconProps` coming from antd's node_modules (and my accidental import from there), and now they bundle differently—how I would have expected, `@ant-design/icons` is not part of `antd` any more. 40k smaller, but still large.

<img width="1403" alt="Screen Shot 2020-02-17 at 10 27 04 AM" src="https://user-images.githubusercontent.com/454758/74671104-18a6e800-5170-11ea-885a-ac71e188a4ae.png">

**Comment by zachguo** [comment]
Try my solution: https://github.com/ant-design/ant-design/issues/12011#issuecomment-577513378

**Comment by zachguo** [comment]
@matthewlein TBH Your bundle report looks like you are not doing any tree-shaking at all.

**Comment by matthewlein** [comment]
@zachguo Thanks for taking a look. I already had `"libraryDirectory": "es"` in my .babelrc, didn't seem to help.

In the past, I have verified that unused parts of antd, like slick were not included. It's possible though, the whole TS -> esnext JS -> Babel + webpack is pretty tough to debug...

**Comment by matthewlein** [comment]
@zachguo Fixed via another comment in that issue thread. It turned out to be a couple of default imports that didn't come in right

```
import { Button, Col, DatePicker, Input, Row, Form } from 'antd';
import Checkbox, { CheckboxOptionType } from 'antd/lib/checkbox';
```
Should have been

```
import { Button, Col, DatePicker, Input, Row, Form, Checkbox } from 'antd';
import { CheckboxOptionType } from 'antd/lib/checkbox';
```

2.68mb -> 1.9mb.

Wow, what an amazing difference a few import statements can make.
