### ISSUE TITLE
样式问题：RangePicker 选择日期时间， 秒被分隔符遮挡

### ISSUE THREAD

**Issue by beMySun** [ant-design/ant-design#21377]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/woqpz)

### Steps to reproduce
选择日期， 时分秒即可

### What is expected?
数据完整呈现， 不被遮挡

### What is actually happening?
部分被遮挡了

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | react |
| System | macOS 10.14.4 |
| Browser | Chrome 79.0.3945.130 |

**Comment by beMySun** [comment]
![image](https://user-images.githubusercontent.com/12824205/74499423-92479780-4f1e-11ea-8516-4d8d343aa4a4.png)

**Comment by beMySun** [comment]
PS： 通过手动加宽， 比如加到400px, 是可以解决的。

![image](https://user-images.githubusercontent.com/12824205/74499733-a2ac4200-4f1f-11ea-96be-5e98a326c74f.png)

组件的默认宽度需要antd 加大一些。

**Comment by afc163** [comment]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/507615/74500212-329ebb80-4f21-11ea-8368-39979c2a2b97.png">

我这里是这样的。

**Comment by beMySun** [comment]
> <img alt="image" width="421" src="https://user-images.githubusercontent.com/507615/74500212-329ebb80-4f21-11ea-8368-39979c2a2b97.png">
> 
> 我这里是这样的。

这么奇怪 = =， 下面是我在文档中的截图：

![image](https://user-images.githubusercontent.com/12824205/74500673-94abf080-4f22-11ea-9a68-718d2a606126.png)

![image](https://user-images.githubusercontent.com/12824205/74500691-a7262a00-4f22-11ea-93c3-2a41fd7ada81.png)

**Comment by beMySun** [comment]
看起来是
format="YYYY-MM-DD HH:mm:ss"
和  
format="YYYY/MM/DD HH:mm:ss"

分隔符 - 和 / ， 占用的宽度不同导致的。 

如果手动指定分隔符为 /， 就没有问题了

**Comment by afc163** [comment]
试试按下 <kbd>cmd</kbd> + <kbd>0</kbd>？

**Comment by beMySun** [comment]
> 试试按下 cmd + 0？

试了， 还是一样：

![image](https://user-images.githubusercontent.com/12824205/74501145-2a944b00-4f24-11ea-9e29-05a051381763.png)

我找一些群里的朋友帮忙看看吧

**Comment by afc163** [comment]
先关了，有进一步信息或者别的重现再 reopen。
