### ISSUE TITLE
table组件在dataIndex属性使用多层JSON无效

### ISSUE THREAD

**Issue by WinterWoods** [ant-design/ant-design#21373]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/exciting-glade-2pzk0?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
性别这一列期望能正常显示

### What is expected?
性别这一列根据数据显示

### What is actually happening?
不显示

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.12 |
| System | win10 |
| Browser | chrome 80 |

---
antd3.x版本可以

**Comment by zombieJ** [comment]
https://codesandbox.io/s/zen-allen-3kw3e

> 此外，比较重大的改动为 dataIndex 从支持路径嵌套如 `user.age` 改成了数组路径如 `['user', 'age']`。以解决过去属性名带 . 需要额外的数据转化问题。

ref: https://next.ant.design/components/table-cn/#%E4%BB%8E-v3-%E5%8D%87%E7%BA%A7%E5%88%B0-v4

**Comment by VoliBearCat** [comment]
4.0开始是这样使用的吧  
dataIndex: ['test', 'sex']

**Comment by afc163** [comment]
@zombieJ 这个在 https://next.ant.design/docs/react/migration-v4-cn 里没有提到。

**Comment by AlexChilamLo** [comment]
此外，比较重大的改动为 dataIndex 从支持路径嵌套如 user.age 改成了数组路径如 ['user', 'age']

但是 在table搜索的時候 getColumnSearchProps 就失效了 
 ['user', 'age'] ERROR是tostring 就是沒找到對應的dataindex
用'user', 'age'的時候沒有ERROR但是 結果是有問題的

**Comment by zombieJ** [comment]
示例里 `getColumnSearchProps` 只是个例子，自己根据代码调整即可。

**Comment by gebilaoman** [comment]
> https://codesandbox.io/s/zen-allen-3kw3e
> 
> > 此外，比较重大的改动为 dataIndex 从支持路径嵌套如 `user.age` 改成了数组路径如 `['user', 'age']`。以解决过去属性名带 . 需要额外的数据转化问题。
> 
> ref: https://next.ant.design/components/table-cn/#%E4%BB%8E-v3-%E5%8D%87%E7%BA%A7%E5%88%B0-v4

一个很差的更新，不能因为个别的属性名带.就把之前的全不兼容了，之前的做法都是依赖于路径嵌套的特性做的，现在改动这么大，牵扯到的租户不是一般的多，太坑了。带.的就让他们自己写render转换啊，真不知道是怎么评估的需求改动

**Comment by huangtaoSyn** [comment]
> https://codesandbox.io/s/zen-allen-3kw3e
> 
> > 此外，比较重大的改动为 dataIndex 从支持路径嵌套如 `user.age` 改成了数组路径如 `['user', 'age']`。以解决过去属性名带 . 需要额外的数据转化问题。
> 
> ref: https://next.ant.design/components/table-cn/#%E4%BB%8E-v3-%E5%8D%87%E7%BA%A7%E5%88%B0-v4

请问一下 我也遇到了这样的问题  现在我想用table 树形数据展示 但是后端的json数据格式 需要显示的不一样
demo:第一层
           sysTopCataId: 1
          sysTopCataName: "产品中心"
          sysTopCataRecomand: "0"
          sysTopCataSort: 50
          sysSubCataEn:[    第二层
                      sysSubCataId: 6
                      sysSubCataName: "产品中心-软件"
                     sysSubCataRecomand: "0"
                      sysSubCataSort: 50
          ]  
现在想在树形数据结构显示 如何处理dataindex

**Comment by kke2017** [comment]
> > https://codesandbox.io/s/zen-allen-3kw3e
> > > 此外，比较重大的改动为 dataIndex 从支持路径嵌套如 `user.age` 改成了数组路径如 `['user', 'age']`。以解决过去属性名带 . 需要额外的数据转化问题。
> > 
> > 
> > ref: https://next.ant.design/components/table-cn/#%E4%BB%8E-v3-%E5%8D%87%E7%BA%A7%E5%88%B0-v4
> 
> 请问一下 我也遇到了这样的问题 现在我想用table 树形数据展示 但是后端的json数据格式 需要显示的不一样 demo:第一层 sysTopCataId: 1 sysTopCataName: "产品中心" sysTopCataRecomand: "0" sysTopCataSort: 50 sysSubCataEn:[ 第二层 { sysSubCataId: 6 sysSubCataName: "产品中心-软件" sysSubCataRecomand: "0" sysSubCataSort: 50 } ] 现在想在树形数据结构显示 如何处理dataindex

访问sysSubCataId的例子：dataIndex: [ 'sysSubCataEn', [ 0 ], 'sysSubCataId' ]
