### ISSUE TITLE
TimePicker 时间选择框 能否增加一个双面板选择

### ISSUE THREAD

**Issue by listcvc** [ant-design/ant-design#21381]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TimePicker 时间选择框 能否增加一个双面板选择？

用途1：营业时间 /开放购物时间
例1：08:00 - 17:30
例2：18:00 - 03:00
例3：12:00:00 - 12:05:00

### What does the proposed API look like?
参考 DatePicker 日期选择框

**Comment by afc163** [comment]
https://next.ant.design/components/time-picker-cn/#components-time-picker-demo-range-picker

**Comment by listcvc** [comment]
这个我看到了，是否可以改成，可以跨日期的？
就是例：19：00-03：00 因为有些商家的营业时间是跨天的，比如宵夜店，酒吧等



在 2020-02-14 15:59:07，"偏右" <notifications@github.com> 写道：

Closed #21381.

**Comment by afc163** [comment]
@listcvc 这个应该可以有，单独再提一个 issue 吧。
