### ISSUE TITLE
单纯的表单Form组件怎样与Modal.confirm()合体？

### ISSUE THREAD

**Issue by mervynchung** [ant-design/ant-design#2138]
一个单纯的表单组件
```
import React from 'react'
import {Button, Form, Input, Modal} from 'antd'

const FormItem = Form.Item;

let dialog = React.createClass({
    handleSubmit(){
        this.props.onSubmit(this.props.form.getFieldsValue())
    },
    render(){
        const { getFieldProps } = this.props.form;
        const formItemLayout = {
            labelCol: {span: 6},
            wrapperCol: {span: 18}
        };
        return <div>
            <Form horizontal onSubmit={this.handleSubmit}>
                <FormItem {...formItemLayout} label="名称">
                    <Input  {...getFieldProps('name')}  />
                </FormItem>
                <FormItem {...formItemLayout} label="描述">
                    <Input  {...getFieldProps('description')}  />
                </FormItem>
            </Form>
        </div>

    }
});
dialog = Form.create({
    mapPropsToFields(props) {
        let result = {};
        for (let prop in props.data) {
            result[prop] = {value: props.data[prop]}
        }
        return result;
    }
})(dialog);

module.exports = dialog;
```
表单里不含submit、button类型等带提交事件的元素。
提交动作由其他组件提供，例如一个Modal.confirm()，content是该dialog组件，用confirm的onOk实现提交。但不知道怎样使onOk的回调函数能访问到form里的getFieldsValue()。
请问这种情况有什么好的做法吗？

**Comment by lyuehh** [comment]
我目前的做法是 modal 里的 form 自己写 ok，cancel 按钮，设置 modal 的 footer是false，这样， ok 的回调里可以访问到 getFieldsValue

**Comment by benjycui** [comment]
把 `Form` 里面的值 `onChange` 到上层，提交时从上层读取数据再 POST 即可。

**Comment by mervynchung** [comment]
主要是因为用单纯Modal的话，我需要在上层state里多设置一个属性管理该modal的显示/隐藏，若用Modal.confirm的话我就不需要在state里另外维护这个状态了

**Comment by williamkhshea** [comment]
@benjycui 你是指透过onChange去setState传到上层吗? 

还是有其他不用setState的方法？请问你可以写一个简单的例子吗？

**Comment by tvrcgo** [comment]
@mervynchung  看到你说把 dialog 赋给 content，我也尝试赋值 React element，如下：

![image](https://cloud.githubusercontent.com/assets/237062/18268993/d538c55e-7458-11e6-9f35-535afba58310.png)

但是不显示，这种用法不行？

**Comment by navono** [comment]
`Modal`中放表单，`Modal`点击取消，怎么重置表单内容？`resetFields`好像无效。

**Comment by LJJCherry** [comment]
遇到同样的问题，最后还是放弃了在Model.confirm里面写Form，转而在Model里面写的Form

**Comment by Ortonzhang** [comment]
找了半天也没有好的解决方案。。。

**Comment by chenxiaochun** [comment]
官方有demo：https://ant.design/components/form/?locale=en-US#components-form-demo-form-in-modal

**Comment by somychfudewe** [comment]
<a href="https://codesandbox.io/s/antd-reproduction-template-1reil" rel="nofollow"><img src="https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667" alt="Edit on CodeSandbox" data-canonical-src="https://codesandbox.io/static/img/play-codesandbox.svg" style="max-width:100%;"></a>

Can try this:

```js
state = {
    remark: ""
  };

  componentDidMount() {
    const modal = Modal.confirm();
    modal.update({
      title: "Do you Want to delete these items?",
      content: (
        <Input.TextArea
          placeholder="remark"
          onChange={e => {
            this.setState({ remark: e.target.value });
            modal.update({ onOk: this.handleOk });
          }}
        />
      ),
      onOk: this.handleOk
    });
  }

  handleOk = () => {
    // Post request
    alert(JSON.stringify(this.state));
  };
```

**Comment by wowlusitong** [comment]
还是尝试在modal里写form吧，搞了个 [react-use-modal](https://github.com/wowlusitong/react-use-modal) 管理`显示/隐藏`的state，使用方式是
```js
handleXXX = () => {
  const { showModal, closeModal } = this.props;
  showModal(({show}) => <CustomModal show={show} closeModal={closeModal} />)
}
```

**Comment by CNMathon** [comment]
挖个坟，2021年了，有解决方案了吗？ @afc163

**Comment by chaosJS** [comment]
https://juejin.cn/post/7047330943228444685
关于这个问题我写了一篇文章
