### ISSUE TITLE
Card type Tabs - jump when activated

### ISSUE THREAD

**Issue by kosticfilip** [ant-design/ant-design#21385]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5vl0f)

### Steps to reproduce
Click any tab, notice how tab changes width.

### What is expected?
Smooth transition to active tab, without width of tab changing

### What is actually happening?
Tab changes width. Feels clunky/jerky.

| Environment | Info |
|---|---|
| antd | 3.26.9 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome |

---
I'm using both variants of tabs for current project, just noticed it doesn't feels smooth for card type. Probably related to font-weight changing to bold.

**Comment by afc163** [comment]
> Probably related to font-weight changing to bold.

You are right, we don't have proper solution for Chrome default behevior now.
