### ISSUE TITLE
table固定表头时，能否开放一个api，可以重写.ant-table-body，类似components

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#21383]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
滚动加载现在需要手动获取这个元素，实现方式不太好

### What does the proposed API look like?
```
components:{
  bodyWrapper:any
}
```

**Comment by zombieJ** [comment]
有 wrapper：
https://github.com/react-component/table/blob/master/src/interface.ts#L136

**Comment by zhangzhi93** [comment]
> 有 wrapper：
> https://github.com/react-component/table/blob/master/src/interface.ts#L136

![image](https://user-images.githubusercontent.com/16435301/74631064-fd030800-5196-11ea-92b6-2204f869cddb.png)
这个重写的是.ant-table-tbody，我想要重写.ant-table-body，是wrapper所在table的父级

**Comment by zombieJ** [comment]
这样你直接在外层监听就行了，不需要到里面去：https://codesandbox.io/s/hidden-wildflower-nwm21

**Comment by zhangzhi93** [comment]
> 这样你直接在外层监听就行了，不需要到里面去：https://codesandbox.io/s/hidden-wildflower-nwm21

好的👍
