### ISSUE TITLE
slider收起时，inline的menu会自动切换到垂直的menu， 希望还能保持inline的模式

### ISSUE THREAD

**Issue by cieldon32** [ant-design/ant-design#21399]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
collapsedWidth的大小很小的话，自动切换到垂直模式是合理的；
如果collapsedWidth的大小不是很小的话，而且希望能继续保持inline

### What does the proposed API look like?
希望能加个开关， 控制收起时menu的mode

**Comment by afc163** [comment]
如果用 collapsedWidth，意味收起的逻辑就是从 inline 变成 vertical。如果不希望变化模式，可以直接切换 Menu 的宽度就行了。
