### ISSUE TITLE
刷新时 menu 展示不符合预期，常常自动折叠

### ISSUE THREAD

**Issue by i-tengfei** [ant-design/ant-design#21398]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://creatorsdaily.com/questions](https://creatorsdaily.com/questions)

### Steps to reproduce
刷新即可重现

![示例](https://user-images.githubusercontent.com/1763168/74608111-56c4ed00-5119-11ea-93cb-dd268c8d9a12.gif)

### What is expected?
菜单不应该被自动折叠

### What is actually happening?
菜单会时常自动折叠起来

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.12.0 |
| System | macOS |
| Browser | chrome 80.0.3987.106 |

---
在 next.js 环境下使用的

**Comment by afc163** [comment]
可以帮忙排查一下给个 PR

**Comment by i-tengfei** [comment]
好奇怪，问题重现不了了，先关掉了，之后再有问题的时候排查吧
