### ISSUE TITLE
引入单个Alert组件,改变了全局字体

### ISSUE THREAD

**Issue by buhe** [ant-design/ant-design#214]
hi,
项目做的很赞,相见恨晚,我们之前大量使用了bootstrap-react的组件,就不打算全部替换了,试用了alert组件,发现一个小问题,会改变全局字体,随即反馈.

Good life!
harebu

**Comment by buhe** [comment]
感觉这样带来了一些侵入性.

**Comment by afc163** [comment]
alert 组件并没有修改全局样式。

如果是引入了 antd.css 导致改变的。antd 还是希望在新项目中独立使用，不建议和其他大型 UI 框架配合使用。

**Comment by buhe** [comment]
字号和字体都有改变
font-family: "Helvetica Neue", Helvetica, "Hiragino Sans GB", "STHeitiSC-Light", "Microsoft YaHei", "微软雅黑", Arial, sans-serif;
    font-size: 12px;

React 的思路就是只解决View的问题，让各个JS 框架共存,百花齐放,较低的侵入性.

**Comment by buhe** [comment]
body {
  font-family: "Helvetica Neue", Helvetica, "Hiragino Sans GB", "STHeitiSC-Light", "Microsoft YaHei", "微软雅黑", Arial, sans-serif;
  font-size: 12px;
  line-height: 1.5;
  color: #666666;
  background-color: #ffffff;
}

这是在 index.css 中搜索到的。基本确定应该是他的问题

**Comment by afc163** [comment]
```
import { Alert } from 'antd/lib/Alert';
```

样式再单独引用。

**Comment by buhe** [comment]
@afc163  不行的,直接报错了,而且样式本身好像是只有一个 index.css ,怎么单独引用呢?

**Comment by ecafe8** [comment]
改一下style里的less文件, 编译新的index.css;
