### ISSUE TITLE
select组件支持类似element组件库select组件的autocomplate功能

### ISSUE THREAD

**Issue by gitbu** [ant-design/ant-design#21409]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在select组件只支持远程搜索，但是实际需求中经常有两种要求，不光要远程搜索来选择内容，还要用户自定义输入内容

### What does the proposed API look like?
增加一个autocomplate的属性，值为布尔类型

**Comment by gitbu** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 现在select组件只支持远程搜索，但是实际需求中经常有两种要求，不光要远程搜索来选择内容，还要用户自定义输入内容
> 
> ### What does the proposed API look like?
> 增加一个autocomplate的属性，值为布尔类型

**Comment by yoyo837** [comment]
https://next.ant.design/components/select-cn/#components-select-demo-tags 这个满足中吗？

**Comment by zombieJ** [comment]
使用 AutoComplete 组件。

**Comment by gitbu** [comment]
@zombieJ 非常感谢，AutoComplate组件确实可以的，那我需要把Atnd升级到4.0，现在4.0是稳定版的吗，我还一直不知道antd出了4.0版本

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/20661
