### ISSUE TITLE
Form's onFinish argument type doesn't allow real data type

### ISSUE THREAD

**Issue by Kamahl19** [ant-design/ant-design#21401]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/create-react-app-with-typescript-wkgtz?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
```onFinish={(values: {email: string}) => { console.log(values) }} ```

### What is expected?
onFinish callback should accept real value's type

### What is actually happening?
onFinish callback says "Property 'email' is missing in type 'Store' but required in type 'Values'."

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | all |
| System | all |
| Browser | all |

**Comment by zombieJ** [comment]
merge into #21195
