### ISSUE TITLE
如何在Upload提交数据之前，加入请求权限？

### ISSUE THREAD

**Issue by lawrsp** [ant-design/ant-design#2140]
用的某云存储，上传文件需要token支持
因此问题来了，
如何在Upload之前的某个点，加入一个token请求的操作？

设想的流程如下：

`Upload获取文件 － 与服务器交互取得token － 设定token － 启动上传`

**Comment by afc163** [comment]
beforeUpload

**Comment by lawrsp** [comment]
@afc163 能不能看清楚问题再关啊

beforeUpload 得到的权数据，如何设定到上传请求里去？ 

`pload获取文件 － 与服务器交互取得token － ““设定token”” － 启动上传`

**Comment by afc163** [comment]
看下这个是否有帮助：https://github.com/ant-design/ant-design/issues/2022

**Comment by lawrsp** [comment]
明白了，data可以传入一个function

**Comment by guoxiangwen** [comment]
@lawrsp 你怎么解决的
