### ISSUE TITLE
Tooltip 关于在 Button disabled 时，将 Button 组件上的 classname 设置为 null 引发的样式问题

### ISSUE THREAD

**Issue by Yangfan2016** [ant-design/ant-design#21404]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/prod-bird-8ek1f?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
     <Tooltip title="prompt text">
        <Button disabled type="primary" className="btn">
          Hover me
        </Button>
      </Tooltip>

### What is expected?
Button 的 classname 不要设置为 null ，需要 Button 的 classname

### What is actually happening?
Button 的 classname 设置成了 null ，

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.4 |
| React | 16.8.3 |
| System | Macintosh; Intel Mac OS X 10_14_5 |
| Browser | Chrome/79.0.3945.130 |

---
bug 代码所在行 ：https://github.com/ant-design/ant-design/blob/master/components/tooltip/index.tsx#L126

**Comment by afc163** [comment]
这是预期的，Tooltip 下的 disabled Button 会 dom 结构会变化。className 会移到最外层，就是 span 上。

**Comment by Yangfan2016** [comment]
那我 想设置  Button disabled 时的classname ，怎么办 @afc163

**Comment by afc163** [comment]
可以

```css
.your-class.ant-btn,
.your-class .ant-btn {

}
```

**Comment by setobox** [comment]
可以在 Button 外包裹一层 `span` 标签
