### ISSUE TITLE
dataIndex with dot notation doesn't work in Table component

### ISSUE THREAD

**Issue by omniteq** [ant-design/ant-design#21416]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-smcl7)

### Steps to reproduce
1. Add a Table component
2. Define data array with nested object
3. Define indexData with dot notation e.g. 'node.person.name'

### What is expected?
Nested data are displayed in a table

### What is actually happening?
Table is displayed with empty cell

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.8.6 |
| System | MacOS 10.13.6 (17G7024) |
| Browser | Chrome 80.0.3987.100 |

---
This bug is not present in the latest version 3 of antd.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21373#issuecomment-586839740

https://next.ant.design/components/table/#Migrate-to-v4
