### ISSUE TITLE
v4 Search with enterButton does not apply className

### ISSUE THREAD

**Issue by matthewlein** [ant-design/ant-design#21419]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-sea-5jv71)

### Steps to reproduce
Create a search with enterButton prop and className prop.
Inspect the element to see className not applied.

### What is expected?
className should be applied to the input.

### What is actually happening?
className is not applied

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.12.0 |
| System | MacOSX  |
| Browser | All/Chrome |

---
I think the addOn check prevents this https://github.com/ant-design/ant-design/blob/e27589552386dc8ac2ca4fdeb9e6f48b6cc346d5/components/input/Input.tsx#L221.

You can apply a class to a parent as a workaround.

**Comment by afc163** [comment]
`className` will always be applied to outside wrapper, so that custom css selector could be working on every element inside.
