### ISSUE TITLE
Error on rendering Query component children: TypeError: _form.default.useForm is not a function

### ISSUE THREAD

**Issue by adamtamics** [ant-design/ant-design#21417]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/75871)

### Steps to reproduce
Open the provided sandbox link, it's from ant.design page.

### What is expected?
useForm isn't throw error.

### What is actually happening?
Error on rendering Query component children: TypeError: _form.default.useForm is not a function

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.9.0 |
| System | Mac OS Catalina 10.15.3 |
| Browser | Chrome 80.0.3987.10 |

**Comment by afc163** [comment]
```diff
{
  "dependencies": {
    "react-dom": "latest",
    "react": "latest",
-   "antd": "latest"
+   "antd": "next"
  }
}
```

https://codesandbox.io/s/sparkling-fast-1do44

**Comment by Feather130** [comment]
![image](https://user-images.githubusercontent.com/10240614/79035441-62043880-7bf1-11ea-93a4-95211b35108c.png)
antd4.1.1 依旧_form.default.useForm is not a function

**Comment by yoyo837** [comment]
提供复现
