### ISSUE TITLE
Open the ability of async-validator to register validators

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#21420]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
First, the `async-validator` callback validator cannot carry parameters. The injection method can solve this problem, and the scalability is greatly improved.

### What does the proposed API look like?
```
Form.create({
   ....
  validators: {
    notRegex: (rule: any, value: any, callback: any, source?: any, options?: any)  => any
  }    
})
```

**Use**
```
{getFieldDecorator('token', {
  rules: [
    { required: true, message: '%s is required' },
    { notRegex: /^\d $/, message: '%s value %s does not match pattern %s' }
  ],    
})(<Input />)
```

**Comment by kaysonwu** [comment]
@afc163  How to contribute this function to 3. X branch?

**Comment by yoyo837** [comment]
Send some pull request at `3.x-stable` branch.

**Comment by afc163** [comment]
3.x won't accept new feature now.

**Comment by kaysonwu** [comment]
How to make this feature work on version 3. X?

**Comment by kaysonwu** [comment]
@afc163  Complete this work, mainly update `rc-form`. antd is only responsible for updating the `ts` statement. Have you considered accepting the request?

**Comment by afc163** [comment]
You can send PR to https://github.com/react-component/field-form and antd master branch for 4.x, 3.x won't accept new feature now.

**Comment by kaysonwu** [comment]
@afc163  `3.x` depends on [rc-form](https://github.com/react-component/form). But the PR repository you provided confuses me

**Comment by afc163** [comment]
3.x won't accept new feature now.

**Comment by kaysonwu** [comment]
I know what you want to say, antd 3.x has stopped accepting new features, but the [rc-form](https://github.com/kaysonwu/ant-design/blob/3.x-stable/package.json#L119) it depends on hasn't stopped accepting new features? Update `rc-from` to benefit antd.

**Comment by afc163** [comment]
rc-form is also deprecated now, we recommand to use rc-field-form instead.

**Comment by kaysonwu** [comment]
Please allow me to love antd 3. X for a while.  I am going to submit a PR to `rc-form`, I hope to get more help from you, thank you!

**Comment by zombieJ** [comment]
Hi @kaysonwu , v3 is in maintains and will not accept new feature.
