### ISSUE TITLE
v4 Table size="small"时，固定列的表头因为颜色为透明，造成文字重叠

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design#21430]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/maxmeng93/pen/YzXWGZR](https://codepen.io/maxmeng93/pen/YzXWGZR)

### Steps to reproduce
打开重现链接（此为官方提供的demo），最后一行替换为 `ReactDOM.render(<Table size="small" columns={columns} dataSource={data} scroll={{ x: 1300 }} />, mountNode);`

![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/ant-design-bug.bi1rs4owtjs.gif)

### What is expected?
表头文字不重叠

### What is actually happening?
表头文字重叠

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.12.0 |
| System | windows 10 |
| Browser | chrome |

---
表头应该设置为白色，而不是透明色

**Comment by afc163** [comment]
你给的例子是空的，应该是忘记保存了。

**Comment by maxmeng93** [comment]
> 你给的例子是空的，应该是忘记保存了。

链接重新提供了
