### ISSUE TITLE
Breaking issues with getFieldsValue

### ISSUE THREAD

**Issue by sitepodmatt** [ant-design/ant-design#21435]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/field-form/commit/87ba282c9a6a12bdfdd7856584eaf2d8d75cae9a](https://github.com/react-component/field-form/commit/87ba282c9a6a12bdfdd7856584eaf2d8d75cae9a)

### Steps to reproduce
form.getFieldsValue() now returns just the first k/v entry in of an object, where as getFieldsValue(true) returns the full object. https://next.ant.design/components/form/ example with <pre>{JSON.stringify(form.getFieldsValue(), null, 2)}</pre> overlooks this, it misses the true argument.

### What is expected?
No dependency version jumping in tagged releases. rc-field-form is technically breaking semver principles here but still. 

### What is actually happening?
rc-field-form made a big behavioural change without incrementing semver, antd rc5 has semver loose on the dependency. 

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | latest |
| System | dos |
| Browser | chrome |

---
package.json should be locking dependencies as bill who used rc5 last week might not run into the issue of fred doing a fresh install today. Drop the ^ from dependencies of volatile stuff like rc-field-form

**Comment by zombieJ** [comment]
Sorry about this. It's our bad for the mistake update. Currently may hardly rollback since it will break other user again. We will release `1.x` for future update if needed.

For current to get fully value, you can use `getFieldsValue(true)` instead.

Very very sorry again for the bad experience. It shouldn't have happened.

**Comment by afc163** [comment]
We should revert rc-field-form@0.0.0-rc.6 and release a new 0.1.0 or 1.0.0 version.

**Comment by afc163** [comment]
Then publish a new antd@4.0.0-rc.6 which deps rc-field-form@0.1.0. This version will carry`getFieldsValue()` and `getFieldsValue(true)` changes.

**Comment by afc163** [comment]
After further digging, revert `rc-field-form@0.0.0-rc.6` will breaks `antd@4.0.0-rc.5`. Discussed with @zombieJ , we believe `antd@4.0.0-rc.5` has correct behavior and we will stick to it. Sorry for break changing in `<antd@4.0.0-rc.5`, which could be considered as a bug like https://github.com/ant-design/ant-design/issues/21320

**Comment by zombieJ** [comment]
Hmmm... After check rollback will break `4.0.0-rc.5` since it use same version define.  Sorry again for breaking change before `rc.5`. We will much follow the rule of semver define.
