### ISSUE TITLE
The second option parameter in the Select component via onSelect does not point to the correct result

### ISSUE THREAD

**Issue by cbbfcd** [ant-design/ant-design#21445]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-onselect-uzbqo)

### Steps to reproduce
1. Expand the drop down and click on 'Jack' in 'Recent Clicks'
2. check the console message 

### What is expected?
it should print 'selected jack, option.props {"value":"jack","tag":"jessic","children":"Jack"} '

### What is actually happening?
print 'selected jack, option.props {"value":"jack","tag":"rose","children":"Jack"} '

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | 16.8.x |
| System | mac os 10.15.2 |
| Browser | chrome  80.0.3987.87 |

---
There is such a requirement, you need to display the "history" and "all records" in the drop-down, click the history, but the option parameters obtained through onSelect are in the "all records", obviously they are not in an OptGroup?

**Comment by zombieJ** [comment]
Select 里不允许存在相同的 `value`，你的最近点击里需要把 value 重新映射一下以区分开来。
