### ISSUE TITLE
Dropdown left click mouse position

### ISSUE THREAD

**Issue by lexlexa** [ant-design/ant-design#21444]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Opening a menu for one item among many.

### What does the proposed API look like?
```html
<Dropdown placement="mouse" trigger={['click']}>
```

**Comment by zombieJ** [comment]
What's the background of this requirement?  Popup menu follow muse position is usually on the right click: https://ant.design/components/dropdown-cn/#components-dropdown-demo-context-menu

**Comment by lexlexa** [comment]
@zombieJ. In my case
![2020-02-19_08-59](https://user-images.githubusercontent.com/35931860/74806215-68afb700-52f6-11ea-9d19-348a89bf4c0d.png)

Context not recomended in web

**Comment by afc163** [comment]
My suggestion is adding a ellipsis trigger for dropdown menu.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/507615/74806456-f2747a00-5320-11ea-9e32-dcc5b32d5d3e.png">

**Comment by lexlexa** [comment]
@afc163  More detailed example
![2020-02-19_09-18](https://user-images.githubusercontent.com/35931860/74807234-00160980-52f9-11ea-80e4-9b3b2769b392.png)

**Comment by afc163** [comment]
We probably won't support this feature, it is against our design spec.
