### ISSUE TITLE
When using onBlur to close popover. Clicking button inside Popover does not trigger button.

### ISSUE THREAD

**Issue by jengjob** [ant-design/ant-design#21449]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-1s5p8?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Click 'Click me'.
2. Click 'Then click here'.

### What is expected?
click should propagate through button.

Console should log:
1. onClick in Popover 
2. DIV LOSING FOCUS
3. onClick in Content. 

### What is actually happening?
Console does not log "onClick in Content."

Console log:
1. onClick in Popover 
2. DIV LOSING FOCUS

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.2 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 79.0.3945.130  |

---
This is not reproduced in the minimal reproduction but clicking outside of the popover will trigger other things as expected like other buttons or links.

In my own project I have a popover that contains a list of links and they do not trigger when clicked. The motivation behind this is I want popover to disappear when you click inside popover, not just when you click outside of it. If anyone has another way to achieve that, please do tell.

**Comment by zombieJ** [comment]
It's browser default behavior.  Button is a focusable element that when you mouse down on it, `activeElement` changes from div to Button and trigger div lose focus.

You can add `preventDefault` on Button mouse down event to prevent it get focus: https://codesandbox.io/s/antd-reproduction-template-zl46d

**Comment by leejojosepj** [comment]
hoe to blur the background in popover like modal, i need to use popover but when click the button popover should come and all other in the view must be blur like modal opening

**Comment by leejojosepj** [comment]
how to blur the background in popover like modal, i need to use popover but when click the button popover should come and all other in the view must be blur like modal opening

**Comment by saileshkotha** [comment]
@leejojosepj I need the same feature, could you please share your approach if you've solved it. Thanks.
