### ISSUE TITLE
TimePicker should not require pressing OK to trigger onChange once a value has been selected

### ISSUE THREAD

**Issue by mgcrea** [ant-design/ant-design#21448]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yd40i)

### Steps to reproduce
Open Timepicker, select value, click outside to blur

### What is expected?
TimePicker should work like a DatePicker, selecting values then bluring the input should trigger the onChange event. Currently usage is very clumsy and I end up miss-selecting half the time.

### What is actually happening?
TimePicker does not persist selected values if you don't press OK

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.12.0 |
| System | macOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/issues/21189#issuecomment-581271007

**Comment by spectersegun** [comment]
please has this issue been fix?

or should i contribute?
