### ISSUE TITLE
Anchor on Modal

### ISSUE THREAD

**Issue by SwapnilMWaman** [ant-design/ant-design#21443]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stoic-http-y3jjs?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Clicking on Show Modal should work like https://ant.design/components/anchor/#Link-Props where we need to keep menus static and other content should scroll as per id of the div with #

### What is expected?
Clicking on Show Modal should work like https://ant.design/components/anchor/#Link-Props where we need to keep menus static and other content should scroll as per id of the div with #

### What is actually happening?
Clicking on show modal is just rendering normal page and its not adding ant-affix class after scrolling and so inline style attributes as well.

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | 16.10 |
| System | Windos |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/stoic-http-y3jjs?fontsize=14&hidenavigation=1&theme=dark

Try `getContainer`.

**Comment by SwapnilMWaman** [comment]
Thank you very much for your help. 

One more query here is if we are on Modal and using Anchor, the links on the left are having Links with HASH keys, and clicking on those, it changes the URL's hash part and so it closes modal, rather it should only scroll to the HASH which is default behavior of HTML.
