### ISSUE TITLE
官网的色彩描述有误

### ISSUE THREAD

**Issue by zhkzyth** [ant-design/ant-design#2145]
具体地址是，http://010x.ant.design/spec/colors， 关于 “Purple #5E30B5”的描述，如下这段：

> 介于红色和黄色之间，传达愉悦，创造力，热情，吸引力。但橙色又不如红色那样具侵略性，同时又能够很好的引起视觉的注意力。可以作为设计的主色也可以用于辅助色。但大面积使用时需要慎重。

应该不是“橙色”，而是“紫色”吧？

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/662

旧版文档就不予修复了。:smile:
