### ISSUE TITLE
optionLabelProp doesn't work in Autocomplete component

### ISSUE THREAD

**Issue by PeerlagudemKoushik** [ant-design/ant-design#21458]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-kepler-p4rhu)

### Steps to reproduce
1. set OptionLabelProp in autocomplete as title and add title to the option component as a prop.
2. select any option from the dropdown

### What is expected?
1. The prop value of OptionLabelProp should be rendered to the autocomplete select.

### What is actually happening?
1. It doesn't work as expected it renders value prop to the select box.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.12.0 |
| System | independent |
| Browser | independent |

---
1. since autocomplete is a wrapper upon select, the OptionPropLabel works fine in select but not in autocomplete
2. Link for the Autocomplete component https://next.ant.design/components/auto-complete/

**Comment by zombieJ** [comment]
`optionLabelProp` is a Select api since AutoComplete do not have a `label`. In v3 we wrapper Select to AutoComplete and mistake export this prop and use in demo. Which should clean up in v4 doc.

**Comment by PeerlagudemKoushik** [comment]
So in Autocomplete it renders the value when anything from dropdown is selected. This is wrong right ? It should render whatever between the Option tags right?

**Comment by 3dw1np** [comment]
How to modify the display of rendering of the autocomplete on select with optionLabelProp ?
For example the attribute 'name' in my options ?
```
const renderItem = item => ({
  name: item.name,
  value: item.id,
  label: (
    <div
      style={{
        display: 'flex',
        justifyContent: 'space-between',
      }}
    >
      <FontAwesomeIcon icon={ICONS_MAPPING[item.icon]} />
      {item.name}
    </div>
  ),
});
```

**Comment by 3dw1np** [comment]
I was able to do what I want with handleSelect(val, option) API.

**Comment by alessiocancian** [comment]
> `optionLabelProp` is a Select api since AutoComplete do not have a `label`. In v3 we wrapper Select to AutoComplete and mistake export this prop and use in demo. Which should clean up in v4 doc.

@zombieJ  well in v3 `optionLabelProp` DID work somehow.
I have a component which worked great using that prop in v3 and after upgrading to v4 it shows the value (numeric id) when selecting an item. I can't use the label as value because it isn't unique.

**Comment by zombieJ** [comment]
`optionLabelProp` is buggy with AutoComplete. When some option's `value` is same as another's `label`, component can not tell what is user typing for. If you have the `optionLabelProp` requirement, you can use Select to dynamic create a option mapping with user input instead.
