### ISSUE TITLE
form表单label错位

### ISSUE THREAD

**Issue by i7guokui** [ant-design/ant-design#21468]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/i7guokui/form-bug](https://github.com/i7guokui/form-bug)

### Steps to reproduce
直接点击'确定'按钮，显示校验不通过的提示信息，"类型"的label位置会跳动

### What is expected?
label位置不变

### What is actually happening?
label位置跳动

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | react |
| System | win10 |
| Browser | chrome 78 |

**Comment by afc163** [comment]
4.0 ❌：https://codesandbox.io/s/n84nu
3.x ✅：https://codesandbox.io/s/focused-meninsky-snvp3

**Comment by afc163** [comment]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/507615/74824863-e221c680-5343-11ea-82e0-0f7c7b8ec430.png">

**Comment by zombieJ** [comment]
为了兼容 `<Form.Item style={{ marginBottom: 0 }} />` 真是心累……
