### ISSUE TITLE
Input等组件存在内存泄漏

### ISSUE THREAD

**Issue by applezyp** [ant-design/ant-design#21461]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-ii980](https://codesandbox.io/s/antd-reproduction-template-ii980)

### Steps to reproduce
前提：利用chrome memory工具辅助观察
**案例1：（antd官网）**
1. 进入https://ant.design/components/input-number-cn/  dump一个当时的内存快照 （22.7M，HTMLInputElement 43个）
2. 在InputNumber页面的第一个输入框输入数字1
3. 任意点击一个其他Tab
4. 再切换到InputBumber Tab，点击memory工具的垃圾桶，然后再点击dump按键获取一个内存快照(27.5，HTMLInputElement 50个）

**案例2：（sandbox sample应用）**
1.进入页面https://ii980.csb.app/     dump当时内存，InputNumber显示数量为2
![image](https://user-images.githubusercontent.com/11324361/74824491-34aeb300-5343-11ea-8aaa-5c41c7652c37.png)
2.在输入框中输入数字1
3.点击click隐藏输入框
4.点击click显示输入框
5.dump此时内存，InputNumber显示数量为4
![image](https://user-images.githubusercontent.com/11324361/74824603-6162ca80-5343-11ea-9c27-5b2dedad37e1.png)

如果观察内存涨幅，可以多操作几次，只操作一次看不出效果，单次操作的话可以看HtmlInputElement的个数

### What is expected?
无论经过什么操作，回到同一个页面时，HTMLInputElement的个数应该是不变的

### What is actually happening?
按照重现步骤进行操作，HTMLInputElement的数量会不断变多，内存会不断累积，操作足够多，页面会崩溃

| Environment | Info |
|---|---|
| antd | 3.17.0 |
| React | 16.8.6 |
| System | mac os 10.13.6 |
| Browser | chrome 79.0.3945.130 |

---
我们的业务中对antd组件依赖比较多，有些场景需要用到antd的组件来填写一些内容，类似上面的操作步骤，打开弹框=>填写内容=>关闭弹框再打开这种场景，由于内存泄漏的问题不断积累，会让用户的界面崩溃，体验极差，无法正常使用

**Comment by zombieJ** [comment]
试了一下，没发现增长。方便给个 repo 代码不？

**Comment by applezyp** [comment]
> 试了一下，没发现增长。方便给个 repo 代码不？

repo: https://codesandbox.io/s/antd-reproduction-template-ii980
对应的页面应用页面：https://ii980.csb.app/
在这个页面中可以更方便的操作：
1、初始界面，dump内存
2、在输入框中输入数字1
3、点击click隐藏按钮
4、然后再点击click显示按钮
5、dump此时内存，会发现inputNumber个数变多了

**Comment by afc163** [comment]
我试了一下，什么 Input 都没有搜到。

<img width="647" alt="image" src="https://user-images.githubusercontent.com/507615/74825939-b0a9fa80-5345-11ea-93e1-f4271728b452.png">

**Comment by applezyp** [comment]
> 我试了一下，什么 Input 都没有搜到。
> 
> <img alt="image" width="647" src="https://user-images.githubusercontent.com/507615/74825939-b0a9fa80-5345-11ea-93e1-f4271728b452.png">

![image](https://user-images.githubusercontent.com/11324361/74826129-0a122980-5346-11ea-9034-450ea2afa0ad.png)
选择这个app的内存

**Comment by afc163** [comment]
我试了一下原生 input 也会是这样表现：https://mews0.csb.app/

https://codesandbox.io/s/antd-reproduction-template-mews0

可能确实有内存泄漏的问题，但是这样的检测方式是否无法暴露问题？

**Comment by afc163** [comment]
发了一个 rc-input-number@4.5.5 ，你可以在本地重新安装 node_modules 确保依赖升级后测试一下。看看内存问题有没有缓解。

**Comment by applezyp** [comment]
> 发了一个 rc-input-number@4.5.5 ，你可以在本地重新安装 node_modules 确保依赖升级后测试一下。看看内存问题有没有缓解。

我试一下

**Comment by zombieJ** [comment]
@applezyp ，这里先关了。如果还有问题，会重开一下。
