### ISSUE TITLE
Passing a React FC to the `getFieldDecorator` api will not receive the initial value.

### ISSUE THREAD

**Issue by jimmy-e** [ant-design/ant-design#21479]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-working-template-input-9dfez)

### Steps to reproduce
Go to the linked code sandbox.

### What is expected?
The second input in the form should receive the initial value from the `getFieldDecorator` api. It does not, however.

### What is actually happening?
The first input in the form is an ant input. The second input in the form is a React functional component that returns the ant input. For some reason, when the `getFieldDecorator` api receives this functional component, it does not pass the initial value to the child functional component.

```js
import React from "react";
import { Form, Input } from "antd";

const SampleInput = () => <Input placeholder="Input 2" />;

const SampleFormContent = ({ form }) => (
  <Form layout="inline" onSubmit={() => {}}>
    <h4>Input with an initial value:</h4>
    <Form.Item>
      {form.getFieldDecorator("input-1", {
        initialValue: "Sample Initial Value"
      })(<Input placeholder="Input 1" />)} // initialValue is displayed
    </Form.Item>
    <h4>Abstacted Input without an initial value:</h4>
    <Form.Item>
      {form.getFieldDecorator("input-2", {
        initialValue: "Sample Initial Value"
      })(<SampleInput />)} // initialValue is not displayed
    </Form.Item>
  </Form>
);

export default Form.create({ name: "sample_form" })(SampleFormContent);
```

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.12 |
| System | mac OSX |
| Browser | Chrome |

**Comment by zombieJ** [comment]
```diff
- const SampleInput = () => <Input placeholder="Input 2" />;
+ const SampleInput = (props) => <Input placeholder="Input 2" {...props} />;
```
