### ISSUE TITLE
Detail: alignment of first example in docs

### ISSUE THREAD

**Issue by luukdv** [ant-design/ant-design#21475]
Feel free to close this if it's not regarded as important. It's the very first example you come in contact with when checking out Ant, and it being a design system, I felt these small details are relevant.

### Reproduction link
[https://next.ant.design/docs/react/getting-started](https://next.ant.design/docs/react/getting-started)

### Steps to reproduce
Look at "First Example" on https://next.ant.design/docs/react/getting-started.

### What is expected?
Datepicker and button to be vertically aligned.

### What is actually happening?
Datepicker and button are not vertically aligned.

![1](https://user-images.githubusercontent.com/5585947/74831710-12527080-5316-11ea-85eb-b5f8661c3b71.jpg)
![2](https://user-images.githubusercontent.com/5585947/74831704-11b9da00-5316-11ea-9a2b-09ac731bfe08.jpg)

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | Latest |
| System | Any |
| Browser | Any |

**Comment by afc163** [comment]
Try antd@4.0.0-rc.5

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-z2zjb

**Comment by afc163** [comment]
It is a Mac Chrome issue which related to the fix of https://github.com/ant-design/ant-design/issues/19972 and we are not able to resolve it in 3.x.

It is been perfectly fixed in 4.x, try it.
