### ISSUE TITLE
DatePicker 能否也提供一个像RangePicker中的ranges属性，来预设日期，DatePicker只有今天根本不够用（如当月第一天，当月最后一天等）

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#21472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能够更加方便快捷选中想要的日期。
目前我项目中的解决方案是用renderExtraFooter来实现，但是有个小问题就是，点击了对应的预设日期，并不会自动关闭DatePicker的面板，用户体验不太好。

### What does the proposed API look like?
像RangePicker中的ranges属性即可，如：
 ranges={{
            '今天': [moment(), moment()],
            '当周': [moment().startOf('week'), moment().endOf('week')],
            '当月': [moment().startOf('month'), moment().endOf('month')],
            '上月': [moment().month(0 - 1).date(1), moment().month(0 - 1).date(31)],
            '近半年': [moment().month(0 - 6).date(1), moment().month(0 - 1).date(31)],
            '去年': [moment().month(0 - 12).date(1), moment().month(0 - 1).date(31)],
        }}

**Comment by afc163** [comment]
DatePicker 有一个 Footer，可以自行定义。

**Comment by afc163** [comment]
> 自动关闭DatePicker的面板

可以通过受控模式控制 open 来关闭面板。

对于日期单选，直接给快键方式不是通用需求，我们现在应该不会提供类似 ranges 的属性。

**Comment by wengsj11** [comment]
> DatePicker 有一个 Footer，可以自行定义。

但是这个footer好像没法覆盖原有的今天，只会多一个footer区域内容，这样就很冗余
![image](https://user-images.githubusercontent.com/25152128/100197906-01cec680-2f36-11eb-93f3-6ac2edbbd4ec.png)

**Comment by yeliex** [comment]
@afc163 不提供针对datepicker的快捷方式属性是出于哪方面的考虑 是否可以针对这个功能点提pr

**Comment by afc163** [comment]
基于 renderExtraFooter + open 受控模式封装成本不高。
