### ISSUE TITLE
Select.Option className does not appear in rendered DOM

### ISSUE THREAD

**Issue by jugglingcats** [ant-design/ant-design#21477]
I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-58312)

### Steps to reproduce
Given the following code the `className` provided to Option does not appear in the DOM (when inspected).
```
<Select placeholder="Select frame...">
        <Option value={"1"}>First menu</Option>
        <Option value={"2"}>Second menu</Option>
        <Option value={"3"} className="foo-bar" style={{background: "red"}}>Third menu</Option>
        <Option value={"4"}>Fourth menu</Option>
    </Select>
```
See also the reproduction.

### What is expected?
The class name should be rendered.

### What is actually happening?
No class name.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.9.20 |
| System | Windows 10 |
| Browser | Chrome 80.0.3987.106 |

---
Notice also that `style` is not included either. It can be useful to add classes or direct styles to an option. Also `className` is documented on `Select.Option`, so it should be working.

One partial workaround is to insert a `div` and put `className` or `style` there, but then this style is also used when the option is selected (in the trigger button), which in my case is not desirable.

**Comment by afc163** [comment]
3.x works: https://codesandbox.io/s/antd-reproduction-template-4xdtg

**Comment by valdo99** [comment]
^4.15.1
not working with scss
