### ISSUE TITLE
Input.Search can clear input in read-only mode

### ISSUE THREAD

**Issue by mmiocevic** [ant-design/ant-design#21488]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jolly-mountain-7381q)

### Steps to reproduce
Click clear icon when using Search component in read-only mode.

### What is expected?
Input should not be cleared when clear icon is pressed in read-only input mode.

### What is actually happening?
Input is cleared when clear icon is pressed in read-only input mode.

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | 16.12.0 |
| System | Windows 10 Pro |
| Browser | Google Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

---
HTML input type search element has no clear icon in read-only mode
<input type="search" value="abc" readonly>
so I do not know if this is by your design or not

**Comment by andyyxw** [comment]
Unfortunately, I need `allowClear` when `input` with `readOnly` ... Like this:

![Snipaste_2020-04-10_17-22-04](https://user-images.githubusercontent.com/41931722/78984829-d2f81180-7b59-11ea-9738-b0436cb40ea7.png)

So can I only add a button in `Suffix` to manually clear?
