### ISSUE TITLE
[v4] 表单组件使用 shouldUpdate 渲染额外字段并结合 Row ，Col 的布局问题

### ISSUE THREAD

**Issue by theprimone** [ant-design/ant-design#21480]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

按照这样的场景，`shouldUpdate` 返回 `null` 时，`Col` 组件仍然会占位。参考 https://codesandbox.io/s/formitem-with-col-ozngu

当前的解决方案是先直接调用**动态生成的函数**来判断返回值不为 `null` 则用 `Col` 组件包裹，否则直接返回，这样就不会占位了。但是这样会有警告：

```
Warning: Instance created by `useForm` is not connect to any Form element. Forget to pass `form` prop?
```

不优雅。

### What does the proposed API look like?

为 form 实例新增一个判断是否已经初始化完成的方法？抑或是在当前版本有没有其他的方法可以优雅实现？

**Comment by zombieJ** [comment]
你的例子看来完全没有必要用 `shouldUpdate`，直接在外层判断就行了：https://codesandbox.io/s/formitem-with-col-8ilog

**Comment by theprimone** [comment]
@zombieJ 我的例子可能过于简单了，现在更新了。第一个元素是动态元素，是会根据别的字段的值出现的 \_(:3J∠)\_

**Comment by zombieJ** [comment]
你这个更新还是把 Col 渲染了呀……，你如果想要的是根据里面的值判断是否需要渲染，可以参考这个例子：https://next.ant.design/components/form-cn/#components-form-demo-control-hooks

**Comment by theprimone** [comment]
又更新了一版，是将 Col 组件直接放到里边啊，之前没想到。那就是 Form.Item -> Col -> Form.Item 的结构了，得看看怎么封装一下了 :sweat_smile:
