### ISSUE TITLE
Cascader defaultValue is not working if setting it in useEffect with useState

### ISSUE THREAD

**Issue by jjzjx118** [ant-design/ant-design#21484]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-antd-cascader](https://stackblitz.com/edit/react-antd-cascader)

### Steps to reproduce
1. implement basic cascader component
2. setDefaultValue in useEffect

### What is expected?
the default value should shown

### What is actually happening?
defaultValue not working

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.12.0 |
| System | 3.26.11 |
| Browser | Chrome 78.0.3904.70 |

**Comment by mborysenko** [comment]
More over if you use `value` property and you use 'multiple mode' there are two more issues.

1. When you select value from the list the tag is added twice and then one disappears.
2. Selected item stays unselected.

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically

**Comment by mborysenko** [comment]
> https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically

Guys case that is described in FAQ, does not solve the issue, that case causes the issue.

Think of case when you use `'multiple'` mode and onChange causes some action outside the component that contain Select and new props(new list of items) are pushed inside and passed down to select component.

In that case using `value` prop works with issues:

1. It add two tags with the same value/name and then replaces them with the same but one;
2. Selected values are not selected
3. You can select more then one tag with the same value
4. When you update list values select component behaves unexpectedly
