### ISSUE TITLE
tree最里面一级是否可以修改样式

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#21489]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
只有树状图 竖着  其他位置会空余很多。
![image](https://user-images.githubusercontent.com/48147837/74925853-eca99200-540f-11ea-945d-47c0587cfdd5.png) 

### What does the proposed API look like?
如果能横着的话就能增加横向的空间， 或者有没有办法做到，求

**Comment by zombieJ** [comment]
可以自定义主题，替换掉变量。也可以给 TreeNode 加 className 来处理样式。

ref: https://ant.design/docs/react/customize-theme-cn

**Comment by GreatAuk** [comment]
@zombieJ 请问 TreeNode 如何设置 className ？

如果按之前 V3 版本来使用 Tree, 会有 warning
![image](https://user-images.githubusercontent.com/20253809/100717893-a5681d00-33f5-11eb-9cc7-a23ff551a457.png)
![image](https://user-images.githubusercontent.com/20253809/100718035-d1839e00-33f5-11eb-8d20-346221ed34a3.png)

**Comment by zombieJ** [comment]
按照提示换用 `treeData`，支持 `className` 的

**Comment by GreatAuk** [comment]
> 按照提示换用 `treeData`，支持 `className` 的

看了好几遍文档，没找到怎么定义 `treeNode` 的，只有自定义 `title`😢

**Comment by GreatAuk** [comment]
知道了，从这里添加 `className` 是万万没想到的😢
![image](https://user-images.githubusercontent.com/20253809/101135907-7648ea00-3647-11eb-99a0-3a1b6e60be16.png)
