### ISSUE TITLE
升级到4.0后,table size="small" 边框样式丢失

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#21493]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/table-cn/#components-table-demo-dynamic-settings](https://next.ant.design/components/table-cn/#components-table-demo-dynamic-settings)

### Steps to reproduce
size=small

### What is expected?
同3.x表格一样,显示边框

### What is actually happening?
边框没了,ui很丑

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16 |
| System | win 10 |
| Browser | chrome |

**Comment by l745230** [comment]
![image](https://user-images.githubusercontent.com/15940920/74929900-70b34800-5417-11ea-80d6-13418cf65fc2.png)

希望能回到此边框

**Comment by zombieJ** [comment]
v4 设计里 Table 的 `small` 和其他几种 `size` 保持一致。不再额外添加边框。

**Comment by l745230** [comment]
@zombieJ 旧版本使用small,有边框,用了很久了. 现在升级到4.0突然没了边框 整个UI发生了很大改变.
麻烦指导一下,要如何手动设置样式,把边框加上.

**Comment by zombieJ** [comment]
加个 `className` or `style` 设置 `border` 样式。

**Comment by afc163** [comment]
https://codesandbox.io/s/zs0sl

```
<Table size="small" bordered />
```
