### ISSUE TITLE
Console error on enter keypress for input fields

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#21497]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-validate-static](https://ant.design/components/form/#components-form-demo-validate-static)

### Steps to reproduce
- Have React Developer tools enabled in browser.
- Open console and press enter on an input field.

### What is expected?
No console log entry.

### What is actually happening?
Console log entry showing: 

onloadwff.js:71 Uncaught TypeError: Cannot read property 'type' of undefined
    at setFieldValue (onloadwff.js:71)
    at HTMLFormElement.formKeydownListener (onloadwff.js:71)

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | React |
| System | Windows 10 |
| Browser | Version 1.3.118 Chromium: 80.0.3987.116 (Official Build) (64-bit) |

**Comment by mjfwebb** [comment]
Just found out that this error is only present when React Developer Tools extension is enabled.

**Comment by afc163** [comment]
It is not a antd issue, please check your lastpass plugin: https://github.com/lastpass/lastpass-cli/issues/428
