### ISSUE TITLE
Select & TreeSelect support `onClear`

### ISSUE THREAD

**Issue by David1Socha** [ant-design/ant-design#21498]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In our application, we're triggering an API call after a user closes a `TreeSelect` based on what values they have selected. To reduce the number of calls made, we'd prefer to wait until the user has made all of their selections in the `TreeSelect` before we initiate the API call, which means using `onChange` wouldn't be ideal.

In [Issue 6290](https://github.com/ant-design/ant-design/issues/6290) , I see that `onDropdownVisibleChange` is suggested for this use case, and this nearly works; however, `onDropdownVisibleChange` is (understandably) not triggered when a user unselects one or more nodes by clicking the "X" icon without expanding the entire dropdown menu, then unfocuses the `TreeSelect` component. For our scenario, this means that a user could change values in the TreeSelect and unfocus it without any API call being triggered.

I believe exposing a separate `onBlur` prop that triggers in this situation and any other situation where the `TreeSelect` component goes from focused to unfocused would allow developers to better support the use-case of API calls triggered by `TreeSelect` selections.

### What does the proposed API look like?
The `onBlur` API I propose would be similar to `onDropdownVisibleChange`, except that it would trigger on any blur of the `TreeSelect` field. I believe the conditions under which this `onBlur` method would be triggered are essentially the same conditions that currently cause the `TreeSelect` element to lose its focused status (and the "ant-select-focused" class).

**Comment by zombieJ** [comment]
https://codesandbox.io/s/wonderful-allen-i5yld

**Comment by David1Socha** [comment]
Hey @zombieJ , thanks for the response. I definitely missed that an `onBlur` prop already exists here. In the demo you linked, if I change the `multiple` prop to true, I am able to reproduce the issue I raised, where removing nodes via "X" icons does not trigger `onBlur`. This can be observed at https://codesandbox.io/s/crimson-glade-wmcks .

It appears that this may be a regression, since I actually do get the behavior I'd expect on 3.X versions (see https://codesandbox.io/s/tender-sun-1w61x). When removing a node via "X", this version does send `focus` and `blur` events which I think is the expected behavior.

Does this concern make sense to you? I can re-file this issue as a bug if you'd prefer.

**Comment by zombieJ** [comment]
V4 refactor the Select & TreeSelect component and these Component will only has one input element to get focus which is aim for accessibility improvement prepare. That means clear btn will not get focus any more. So for v4 usage, I think it should add `onClear` event to handle this requirement.

**Comment by piyushk96** [comment]
Any update when does `onClear` will be supported

**Comment by habeebahmed** [comment]
@afc163 onBlur is not working as expected 
can you please check ?
https://codesandbox.io/s/condescending-night-lfn2v?file=/index.js:722-912

**Comment by afc163** [comment]
@07akioni rc-select 版本没有升级上来。

**Comment by 07akioni** [comment]
> @07akioni rc-select 版本没有升级上来。

feature 分支上没错吧
```
"rc-select": "~11.1.0",
```

**Comment by afc163** [comment]
👌，我看漏了，可以关了。

**Comment by fabripeco** [comment]
Please add documentation for onClear also on TreeSelect component (https://ant.design/components/tree-select/).

Thank you very much!

**Comment by kahummer** [comment]
onClear is not being fired on select/tree select either When removing a node via "X". Any solutions ???
