### ISSUE TITLE
table组件是否可以提供隔行换色功能

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2149]
提个需求，希望官方为ANTD提供一个隔行换色功能

**Comment by afc163** [comment]
我们的设计规范里没有隔行换色，还是不加了。

**Comment by CoderChow1994** [comment]
@wuhaih 后来你怎么实现的

**Comment by paranoidjk** [comment]
`rowClassName `

https://ant.design/components/table-cn/#Table
