### ISSUE TITLE
Proposal: form items dependencies reset and show/hide

### ISSUE THREAD

**Issue by csandanov** [ant-design/ant-design#21490]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. Now if you have, let's say, a select element with a dependent select and you change the first select value, you'll have to manually reset dependent elements via `form.setFieldsValue({...})` otherwise you will see the invalid value being selected in the second select. It's especially a problem when you have many dependent elements and cascading dependencies. 

2. Another related potential problem is when you need to optionally show/hide dependent elements based on the selected option in the dependee

### What does the proposed API look like?
1. State and city selects with options populated dynamically. If you select a city and then change a state, you will have an invalid value in your repopulated city select. By providing `dependsOn` you will automatically fix this.

```javascript
<Form.Item name="state" label="State">
  <Select>
    // populated dynamically.
  <Select>
</Form.Item>
<Form.Item name="city" label="City" dependsOn="state">
  <Select>
    // populated dynamically.
  </Select>
</Form.Item>
```

2. Additionally, if you already have two elements linked via `dependsOn` you can optionally provider `dependsOption` to show/hide the dependent element when a dependee's value set to the option. Mostly used for selects and radios. 

```javascript
<Form.Item name="git-ref-type" label="Git reference type">
  <Select>
    <Option value="branch">Branch</Option>
    <Option value="hash">Hash commit</Option>
  <Select>
</Form.Item>
<Form.Item name="branch" label="Git branch" dependsOn="git-ref-type" dependsOption="branch">
  <Select>
    // populated dynamically.  
  </Select>
</Form.Item>
<Form.Item name="hash" label="Commit hash" dependsOn="git-ref-type" dependsOption="hash">
  <Input type="text" />
</Form.Item>
```

**Comment by zombieJ** [comment]
Thanks for feedback. We've though of this ability and do research of schema configable auto fill values. Auto handle values can not fully cover use case, thus provides `shouldUpdate` for hidden requirement and `dependencies` only handle validation relation update.

We may not add these api in antd side but you can still HOC Form.Item in your own code logic. Thanks.
