### ISSUE TITLE
好像不支持服务端渲染

### ISSUE THREAD

**Issue by cheft** [ant-design/ant-design#215]
好像不支持服务端渲染，代码中含有 window 对象

**Comment by afc163** [comment]
欢迎探索和 PR ~

**Comment by cheft** [comment]
这要解决恐怕比较麻烦。

**Comment by thewei** [comment]
服务端渲染应该要支持呀，在部署上有好处，是否纳入计划中呢

**Comment by shepherdwind** [comment]
+1

**Comment by benjycui** [comment]
grep 了下，用到 `window` 之类的地方不少，如果在这些地方都用对象检测，会略复杂。

有个想法，写一个 `window-shiv`，类似 [window-shim](https://github.com/websecurify/node-window-shim)，但会比这个要完善。

在服务端则使用 mock 出来的 window，大概如下：

```js
{
  document: {
    ...
  },
  setTimeout() {},
  ...
}
```

这样只要在开头加个:

```js
import window from 'window-shiv';
```

**Comment by cheft** [comment]
嗯，这样实现要简单很多

**Comment by morer** [comment]
请提供一个服务端渲染的例子，我用express，但是不知道如何做，万分感谢。

**Comment by benjycui** [comment]
@morer antd 还没完全支持服务端渲染

**Comment by wuzhao** [comment]
+1

**Comment by shawon1220** [comment]
+1，react服务器端渲染，高压测试cpu密集运算，性能略差啊。
react同构实例：https://github.com/kriasoft/react-starter-kit

**Comment by afc163** [comment]
服务端渲染目前位置修复了很多问题，目前看来已经有很多人用到了。由于我们自己没有应用，所以不敢声称完全支持，希望使用了服务端渲染的用户继续帮忙测试和 PR ~

**Comment by MarshallChen** [comment]
服务器端渲染如果使用 Mock window 的话 `fbjs/lib/ExecutionEnviroment.canUseDOM` 在服务器端就会为 `true` 会导致什么问题目前倒是没有遇到，唯一觉得不痛快的是服务器端渲染出来的 DOM 里的 `data-reactid`，即 `react/lib/ReactDefaultInjection.js` 里会通过 `canUseDOM` 来生成不同形式的 `data-reactid`。

```javascript
// 不同的 data-reactid
ReactInjection.RootIndex.injectCreateReactRootIndex(ExecutionEnvironment.canUseDOM ? ClientReactRootIndex.createReactRootIndex : ServerReactRootIndex.createReactRootIndex);
```

 `react@15.0.0` 里即将去掉 `data-reactid`，但是服务器端渲染的 DOM 里 `data-reactid` 还是会保留的，不知道这样会不会有什么问题。

btw 我们现在就是在服务器端用的 mock window 的方式。

**Comment by dreambo8563** [comment]
今天尝试在start kit里引入 carousel 报了server和client有区别的错误,而且style没有引入

**Comment by afc163** [comment]
@dreambo8563 https://github.com/akiran/react-slick/pull/288/files

**Comment by dreambo8563** [comment]
@afc163 我不能确定是RSK的问题还是antd的.引入button也是一样的问题
RSK里用了一个isomorphic-style-loader/lib/withStyles 不知道是不是这个造成的问题

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/2993

有测试方案才能方便的排查问题。

**Comment by mgrush** [comment]
可以尝试 browser-env 来模拟window环境， 我目前使用的antd实现的服务器端渲染，已经在线上运行，不过browser-env一般来说是用于测试react代码的， 可能放在server rendering中 有点不是特别的合适

**Comment by yesmeck** [comment]
@mgrush 已经支持在 node  环境下渲染了。
