### ISSUE TITLE
怎样实现Tree最里面一级横排

### ISSUE THREAD

**Issue by panHuaCheng** [ant-design/ant-design#21507]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
让Tree的某一级横排

### What does the proposed API look like?
有一个属性可以让Tree的某一级横排或者竖排

**Comment by afc163** [comment]
不支持，但是 TreeNode 的 title 支持 ReactNode，你可以写你想写的任何东西。
