### ISSUE TITLE
onExpandedRowsChange return not correctly when rowKey is set

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#21504]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/boring-cori-9rwu9)

Table

### Steps to reproduce
1, set `rowKey`
2, bind `expandedRowKeys` to state
3, get `expandedRowKeys` from `onExpandedRowsChange`
4, load `dataSource` and set new `expandedRowKeys` state

### What is expected?
`onExpandedRowsChange` not trigger / return fresh `expandedRows`

### What is actually happening?
`onExpandedRowsChange` return `[]`

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome |

![20200221114722](https://user-images.githubusercontent.com/29817353/75002608-fb3f8a00-549f-11ea-9db7-afb959c4bdc7.jpg)

**Comment by zombieJ** [comment]
Hmm... I agree `onExpandedRowsChange` should not trigger.

**Comment by chiaweilee** [comment]
![image](https://user-images.githubusercontent.com/29817353/158523993-38c40c16-cd6e-4629-86de-5415691d23e6.png)

fixed
