### ISSUE TITLE
v4 表单如何回显CheckBox的值

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#21505]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
升级v4版本后,
找不到相关进行更改
        <FormItem label="管理员权限" name="remark" rules={[{ valuePropName: 'checked' }]}>
            <Checkbox/>
          </FormItem>

### What does the proposed API look like?
 <FormItem {...formItemLayout} label="权限">
            {getFieldDecorator('isAdmin', {
              valuePropName: 'checked',
              initialValue: record.isAdmin,
            })(<Checkbox />)}
          </FormItem>

**Comment by afc163** [comment]
https://next.ant.design/components/form-cn/#components-form-demo-basic

看第一个例子。
