### ISSUE TITLE
Select的Option从后台动态获取，setFieldsValue同步表单的时候，4.0版本下如何绑定？

### ISSUE THREAD

**Issue by heyepeng** [ant-design/ant-design#21509]
Select组件的Option是从后台取数据动态生成的，目前用的这个方式
`{companyData.map(d => (
              <Option key={d.id}>{d.companyName}</Option>
))}`

然后使用setFieldsValue同步表单数据。
表单上Select组件会直接显示表单数据的value，而不会根据value展示Option的文本。
初步判断是由于setFieldsValue的行为先于Option项的生成，但是在4.0版本，不知从何下手解决这个问题。

**Comment by zlyyyy** [comment]
你好，我也遇到了同样的问题，请问你是怎么解决这个问题的。

**Comment by heyepeng** [comment]
> 你好，我也遇到了同样的问题，请问你是怎么解决这个问题的。

Option加上key和value属性，并且在动态数据加载成功后再生成Select
