### ISSUE TITLE
Error on ExpandableTable.componentDidUpdate when expandedRowKeys is undefined

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#21502]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

4.0.0-rc.5

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-diffie-r4fvx)

3.26.11

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/confident-wood-62xzv)

### Steps to reproduce
1, set `expandedRowKeys` to `undefined`
2, trigger `componentDidUpdate`

### What is expected?
No error report

### What is actually happening?
```
TypeError
Cannot read property 'includes' of undefined
eval
https://ptfsc.csb.app/node_modules/rc-table/lib/ExpandableRow.js:191:31
Array.Connect._this.handleChange
https://ptfsc.csb.app/node_modules/mini-store/lib/connect.js:80:27
Object.setState
https://ptfsc.csb.app/node_modules/mini-store/lib/create.js:17:19
ExpandableTable.componentDidUpdate
https://ptfsc.csb.app/node_modules/rc-table/lib/ExpandableTable.js:200:20
```

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 & 3.26.11 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome |

---
```js
exports.default = mini_store_1.connect(function (_ref, _ref2) {
  var expandedRowKeys = _ref.expandedRowKeys;
  var rowKey = _ref2.rowKey;
  return {
    expanded: expandedRowKeys.includes(rowKey) // 👈 expandedRowKeys is not an array
  };
})(ExpandableRow);
```

This possible happened when trying:

```jsx
<Table expandedRowKeys={this.props.expandedRowKeys} />
```

**Comment by afc163** [comment]
你提供的这两个例子都是 3.x 的。

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/table/releases/tag/v6.10.12，重新安装 node_modules 即可。
