### ISSUE TITLE
是否可以加入，方法回调控制呢。目前使用非常不方便，可以参考 elementUI Tree 的一些方法和功能，虽然element tree 不支持 大数据虚拟滚动，但提供的一些方法还是很方便的

### ISSUE THREAD

**Issue by xiaogaofudao** [ant-design/ant-design#21519]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
是否可以加入，方法回调控制呢。目前使用非常不方便，可以参考 elementUI Tree 的一些方法和功能，虽然element tree 不支持 大数据虚拟滚动，但提供的一些方法还是很方便的

### What does the proposed API look like?
是否可以加入，方法回调控制呢。目前使用非常不方便，可以参考 elementUI Tree 的一些方法和功能，虽然element tree 不支持 大数据虚拟滚动，但提供的一些方法还是很方便的

**Comment by xiaogaofudao** [comment]
现在遇到了一个问题，我是在 vue 项目引用了 ant design tree react 组件。现在有个需求，想在输入框输入，自己前端遍历数据搜索，下拉显示匹配项。当用户点击下拉的某一项时候，我想定位到树形菜单的某一项，发现 rc-tree 并没有相关接口和方法。我自己想到的就是，找到这一项的父级 key。如果没有展开就展开，js dom 遍历到元素，通过 scrollIntoView 定位到匹配项。发现很难控制 元素节点 展开。有什么好的方法或是建议吗

**Comment by afc163** [comment]
> 发现很难控制 元素节点 展开

请使用 `expandedKeys` 控制节点展开。
