### ISSUE TITLE
Tree 组件是否可以提供类似 elementUI tree 组件的 expand-on-click-node

### ISSUE THREAD

**Issue by xiaogaofudao** [ant-design/ant-design#21517]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
expand-on-click-node 
是否在点击节点的时候展开或者收缩节点， 默认值为 true，如果为 false，则只有点箭头图标的时候才会展开或者收缩节点。

### What does the proposed API look like?
expand-on-click-node 
是否在点击节点的时候展开或者收缩节点， 默认值为 true，如果为 false，则只有点箭头图标的时候才会展开或者收缩节点。

**Comment by afc163** [comment]
https://ant.design/components/tree/#components-tree-demo-directory

看看这个。
