### ISSUE TITLE
[3.x Table] rowSelection的getCheckboxProps的问题, 参数record并不是所有的record都遍历了, 导致个别的自定义设置失效. 但在4.0Table是没有问题的.

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#21523]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-dan-wysti)

### Steps to reproduce
一级树出现了disable, 不能选中的现象.

### What is expected?
给二级树添加的ifDisable, 只有二级树不能被选中.

### What is actually happening?
一级树有个别不能选中.

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome 80 |

---
发现record不是遍历所有的record, 也就是有遗漏. 
4.0没发现问题, 4.0Demo: https://codesandbox.io/s/romantic-driscoll-bo650
4.0可能也有问题也说不准, 但在此demo并无问题.

**Comment by zombieJ** [comment]
`key` 每个都要设置：https://codesandbox.io/s/lucid-chebyshev-7t7gk
