### ISSUE TITLE
🐛[BUG]Pro Table 在树形结构下，选择多选框报错

### ISSUE THREAD

**Issue by Lanboo** [ant-design/ant-design#21526]
### 🐛 bug 描述

在树形结构下，选择多选框报错

### 📷 复现步骤
我在浏览器中Debug，原因如下：
``` js
// http://localhost:8000/node_modules/antd/es/table/hooks/useLazyKVMap.js
var dig = function dig(records) {
    records.forEach(function (record, index) {  //1
        var rowKey = getRowKey(record, index);
        kvMap.set(rowKey, record);

        if (childrenColumnName in record) {
            dig(record[childrenColumnName]);   //2
        }
    });
};
```
当列表中某个数据存在childrenColumnName字段时，不论是否为空，都会dig回调，从而在1处报错

### 🏞 期望结果
选择多选框不会报错

### © 版本信息

- Ant Design Pro 版本: [4.0.0]
- umi 版本
- 浏览器环境 Chrome 66.0.3359.139（正式版本） （64 位）
- 开发环境 Windows64
- ant-design/pro-table: "1.0.34"

### 🚑 其他信息

**Comment by chenshuai2144** [comment]
https://github.com/ant-design/ant-design/pull/21528
