### ISSUE TITLE
tree控件中，如何在空白处实现右键菜单

### ISSUE THREAD

**Issue by lwfwind** [ant-design/ant-design#21521]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前tree控件中，右键节点(node)会有对应的事件(onRightClick), 但右键点击空白处没有对应的事件

### What does the proposed API look like?
类似onRightClick，或者其它方案也可以

**Comment by afc163** [comment]
不太理解空白处点击的意义是什么。

**Comment by lwfwind** [comment]
已经实现

**Comment by jhoneybee** [comment]
可采用onBlur事件作为一种解决方案。

https://github.com/Kotomi-Team/kotomi-ui/blob/master/components/tree/Tree.tsx#L122-L132
