### ISSUE TITLE
[RangePicker] button text 

### ISSUE THREAD

**Issue by imhele** [ant-design/ant-design#21525]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

When inputting the start time of `<RangePicker showTime />`, the button text at the bottom of the panel is "Ok". In fact, after clicking the button, it will automatically switch to the panel for entering the end time. Using "Ok" to describe the function of the button is not very suitable.

![image](https://user-images.githubusercontent.com/32428655/75092957-303f0000-55b8-11ea-9bbe-4a60dd5988a9.png)

### What does the proposed API look like?

"Next" / "Previous" is better.

**Comment by afc163** [comment]
From mk-nickyang

---

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/u8d72)

### Steps to reproduce
v4 RangePicker user flow when `showTime={true}`:
- Select **start date**
- Select **start time** (optionally)
- Click **Ok**
- Select **end date**
- Select **end time** (optionally)
- Click **Ok**
- Done

### What is expected?
A better one

### What is actually happening?
The **Ok** button user has to click after selecting start date/time doesn't actually mean okay or finish.

Generally, the v4 RangePicker UX is much more complicated and confusing than the v3 one.

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.5 |
| Browser | Chrome 84.0.4147.105 |

---
#WeWantV3RangePicker

---

But what if user edits the **end date** first, click `Next`/`Ok` will then open the **start date** panel, which is also bit confusing

[![Image from Gyazo](https://i.gyazo.com/a9579856734b5be4d45ef99f3397410c.gif)](https://gyazo.com/a9579856734b5be4d45ef99f3397410c)

---

In my humble opinion, even when user sets `showTime={true}`, RangePicker should still make date range select work the same, time select should be optional and not breaking date range select workflow.

**Comment by nbhaohao** [comment]
Is there any progress now?

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)

**Comment by zombieJ** [comment]
Use `components.xxx` for customize.
