### ISSUE TITLE
RangePicker 表单校验问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2152]
我对表单的日期选择控件加上如下校验
const activeTimeV = getFieldProps('activeTime', {
      rules: [
        {
          required: true,
          type: 'date',
          message: '请输入有效时间？',
        },
      ],
    });

浏览器会报t.getTime is not function错，估计是因为值是个数组而不是时间类型吧

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
> 估计是因为值是个数组而不是时间类型吧

你已经总结出原因了。。。。。

`type: 'array'`

**Comment by aw6658913** [comment]
恩~刚想在线演示，我就是想问type要写什么，因为文档没有写什么type对应的值有哪些~感觉文档还是不够完善，很多没有体现出来，一出现文档没有的属性就蒙了

**Comment by afc163** [comment]
https://github.com/yiminghe/async-validator#type

文档里只放了一个 async-validator 链接，确实有点单薄。
