### ISSUE TITLE
form field is not a valid undefined

### ISSUE THREAD

**Issue by sequarius** [ant-design/ant-design#21537]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gist.github.com/sequarius/6d36b03ff5509b7afc8f36cf9c1d4e32](https://gist.github.com/sequarius/6d36b03ff5509b7afc8f36cf9c1d4e32)

### Steps to reproduce
click the button set age when model create, then click submit button

### What is expected?
form check pass through.

### What is actually happening?
async-validator: ["'age' is not a valid undefined"]

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.5 |
| React | 16.8.6 |
| System | Windows |
| Browser | Chrome 79.0.3945.130 |

**Comment by zombieJ** [comment]
`max` validate depends on the `type` which should be defined: https://codesandbox.io/s/kind-wright-205l0

**Comment by christian-sanches** [comment]
On my code, I used to return an empty rule (`{}`) conditionally. When the condition is met, this error was thrown.

There were two possible fixes:
1. do not return any rule at all
2. return a dummy validator
```ts
return {
  validator: (_, _val, callback) => callback(),
}
```

Hope it helps someone in the future!
