### ISSUE TITLE
被Form.create包裹的组件无法在父组件中使用ref获取然后调用方法

### ISSUE THREAD

**Issue by Yuliang-Lee** [ant-design/ant-design#2153]
Demo：http://codepen.io/Yuliang-Lee/pen/rLWQQe?editors=0011
相关的问题：https://github.com/ant-design/ant-design/issues/1158  ，但是没看懂里面的回答

antd：1.4.1
react：15.1.0

**Comment by benjycui** [comment]
如果只是为了获取里面那层 Form 的数据，建议在里面的 Form 提供 `onChange` 事件，在 Owner 中监听 `onChange` 事件即可，这样也比较符合 React 的风格。

**Comment by Yuliang-Lee** [comment]
@benjycui 场景是类似这样的：App内需要有不定个数的‘WrapComponent’，这个是可以增删的，而‘WrapComponent’有不同类型所以内部会有不同类型的表单控件，而内部的表单控件也是不定个数的，最后需要的数据需要组装成某个格式，我不想把所有组装的的代码都放到Owner上，而是在WrapComponent 里面处理然后返回对象。我现在暂时的解决方法是在Owner中调用Form.getFieldsValue来获取值然后处理，和onChange差不多。但是还是希望能直接调用子组件的静态方法。。

**Comment by benjycui** [comment]
`WrapComponent` 在把数据传给 Owner 的 `onChange` 之前处理成所需的数据格式不可以么？

**Comment by slertness** [comment]
也碰到这个问题 看了一下form包裹后的对象结构 貌似是能找到原组件 但是很深 路径很不友好
能不能写个更方便获取的方法呢

**Comment by Yuliang-Lee** [comment]
@benjycui 解决方案有很多，从结果来看是有办法获取到数据，但是各有优缺点嘛，比如你上面说的两种方法，都是把子组件的数据保存在了父组件state中，这样子组件数据非常多的时候就感觉父组件的state就很大了。

**Comment by benjycui** [comment]
主要是 Owner 主动去调用 Ownee 的方法，并不符合 React 的风格。。

@Yuliang-Lee Redux 其实就是这样。

**Comment by Yuliang-Lee** [comment]
@benjycui 哈哈，可能是我还没有习惯react的开发风格。Redux还没机会去用过。这个issue我close了。
