### ISSUE TITLE
timeline 样式建议

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#21545]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的组件都是就一个内容Timeline.Item 包裹， 能否价格属性，可以管理时间，在时间轴左侧或者右侧？而不是只能和内容绑在一起，在内容的左右侧， 

### What does the proposed API look like?
时间和内容分离，时间轴左右侧都可放

**Comment by shaodahong** [comment]
Duplicate of #17966

**Comment by k983551019** [comment]
> Duplicate of #17966

你们这文档上也没写啊。

**Comment by shaodahong** [comment]
写什么？

**Comment by k983551019** [comment]
> 写什么？

你们新加了label属性，可是文档上却找不到，别人会以为没这个东西

**Comment by shaodahong** [comment]
嗯，还没实现，欢迎 PR

**Comment by yoyo837** [comment]
存在的API没有加入文档的有两种情况，一种是漏了，一种是刻意不对外公开、不打算推广使用的！

**Comment by afc163** [comment]
看下 #17966，还没实现呢。
