### ISSUE TITLE
升级到4.0后,class table setState(editable,columns)  失效

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#21541]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
无

### What is expected?
修改editable后,columns会重新渲染

### What is actually happening?
升级后,columns只会以第一次editable的值,进行渲染. 后续修改editable ,columns不会更新

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | win 10 |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/15940920/75103148-df6bed80-5631-11ea-89c1-cd0b5db84029.png)

**Comment by l745230** [comment]
import React from 'react';

import { Table, Input, Button } from 'antd';

class OutStock extends React.Component {
  state = {
    editable: false,
    columns: [
      {
        title: '编号',
        dataIndex: 'id',
        width: 100,
        render: (text: any, record: any) => {
          const { editable } = this.state;

          return <div>{editable ? <Input allowClear autoFocus value={text} /> : text}</div>;
        },
      },
    ],
    data: [],
  };
  componentDidMount() {
    const data = [];
    for (let i = 0; i < 20; i += 1) {
      data.push({
        id: Math.floor(Math.random() * 100) + 10,
      });
    }

    this.setState({
      data: data,
    });
  }

  render() {
    const { columns, data } = this.state;

    return (
      <>
        <Button
          onClick={() => {
            const { editable } = this.state;

            this.setState({
              editable: !editable,
            });
          }}
        />
        <Table columns={columns} dataSource={data} rowKey="id" pagination={false} />
      </>
    );
  }
}

export default OutStock;

**Comment by l745230** [comment]
`
import React from 'react';

import { Table, Input, Button } from 'antd';

class OutStock extends React.Component {
  state = {
    editable: false,
    columns: [
      {
        title: '编号',
        dataIndex: 'id',
        width: 100,
        render: (text: any, record: any) => {
          const { editable } = this.state;

          return <div>{editable ? <Input allowClear autoFocus value={text} /> : text}</div>;
        },
      },
    ],
    data: [],
  };
  componentDidMount() {
    const data = [];
    for (let i = 0; i < 20; i += 1) {
      data.push({
        id: Math.floor(Math.random() * 100) + 10,
      });
    }

    this.setState({
      data: data,
    });
  }

  render() {
    const { columns, data, editable } = this.state;
    console.log(editable);
    return (
      <>
        <Button
          onClick={() => {
            const { editable } = this.state;

            this.setState({
              editable: !editable,
            });
          }}
        />
        <Table columns={columns} dataSource={data} rowKey="id" pagination={false} />
      </>
    );
  }
}

export default OutStock;

`

**Comment by l745230** [comment]
@afc163 大佬看看~~ 点按钮切换editable ,表格始终不会发生改变.

**Comment by l745230** [comment]
https://codesandbox.io/s/antd-reproduction-template-357w6?fontsize=14&hidenavigation=1&theme=dark

特地到codesandbox中试了下.   "antd": "^4.0.0-rc.5" 这个版本点切换editable,表格不会变

**Comment by l745230** [comment]
"antd": "latest" 则是正常的

**Comment by l745230** [comment]
@zombieJ 咨询一下,这个bug能在rc.7 版本修复吗?
现在升级4.0 有个编辑表格的功能被卡住了.
想问下官方的安排,如果要等比较长时间的话, 只能把想办法改成hooks写法了.(代码量有点大-.-)

**Comment by afc163** [comment]
same as #21573

**Comment by OhYee** [comment]
@l745230 
可以先把这一行的id存储setState成别的值，然后在setState的回调里再setState成原值，Table就会因为行id修改而重新渲染这一行
（起码能在较小的代码量保证能用，等修复后可以再该回去）

**Comment by l745230** [comment]
@OhYee 好评,按提供的思路试了下, 发现只需要将data重新在赋值一下,就能切换了.
最少代码改动的能用了 ^_^ 

![image](https://user-images.githubusercontent.com/15940920/75637226-0775d500-5c60-11ea-8a6e-b6289d0e9384.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21573#issuecomment-594310546

**Comment by zombieJ** [comment]
这个场景和 #21573 有点不太一样，需要修一下。
