### ISSUE TITLE
Modal 的 destroyOnClose不起效果

### ISSUE THREAD

**Issue by panHuaCheng** [ant-design/ant-design#21544]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
关闭时销毁 Modal 里的子元素

### What does the proposed API look like?
关闭时销毁 Modal 里的子元素

**Comment by yoyo837** [comment]
这个我好像遇到了，我看看能不能提供个复现。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21740#issuecomment-593105570
