### ISSUE TITLE
[4.0 Select & Form] [有Demo] 当Form的setFieldsValue 赋值给 Select组件的时候(Select组件拥有'labelInValue'和'multiple'), 点开select组件, 不再有高亮和选中.

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#21551]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fast-wood-553t2)

### Steps to reproduce
点击查看demo 点击select组件.

### What is expected?
点开select, 有高亮和选中.

### What is actually happening?
点开select, 没有任何高亮和选中.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc5 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome 80 |

---
如果没有labelInValue, setFieldsValue赋值给select组件都能正常显示高亮和选中.
添加了labelInValue就不行了.

**Comment by Xxxxxxxxxxn** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/97cbe82b1619b42e1f78fce9db09104b932a9da1fd37751f4d9c41f4fe350241/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/fast-wood-553t2)
> 
> ### Steps to reproduce
> 点击查看demo 点击select组件.
> 
> ### What is expected?
> 点开select, 有高亮和选中.
> 
> ### What is actually happening?
> 点开select, 没有任何高亮和选中.
> 
> Environment	Info
> antd	4.0.0-rc5
> React	16.12.0
> System	mac
> Browser	chrome 80
> 如果没有labelInValue, setFieldsValue赋值给select组件都能正常显示高亮和选中. 添加了labelInValue就不行了.
这个问题最后怎么解决了呢

**Comment by Xxxxxxxxxxn** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/97cbe82b1619b42e1f78fce9db09104b932a9da1fd37751f4d9c41f4fe350241/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/fast-wood-553t2)
> 
> ### Steps to reproduce
> 点击查看demo 点击select组件.
> 
> ### What is expected?
> 点开select, 有高亮和选中.
> 
> ### What is actually happening?
> 点开select, 没有任何高亮和选中.
> 
> Environment	Info
> antd	4.0.0-rc5
> React	16.12.0
> System	mac
> Browser	chrome 80
> 如果没有labelInValue, setFieldsValue赋值给select组件都能正常显示高亮和选中. 添加了labelInValue就不行了.

请问这个问题最后怎么解决了呢。我也遇到这个问题
