### ISSUE TITLE
请问下Upload组件的defaultFileList属性需要怎么接受state参数呢?

### ISSUE THREAD

**Issue by laolu87** [ant-design/ant-design#2155]
我想每次访问网页的时候在componentdidmount里面通过get请求获取图片然后再传递给state参数,然后再通过defaultFileList获取this.state.xxx参数渲染出来,可是我测试后不能成功,请问大神是什么原因呢?this.state.xxx控制台打印出来的数据格式是这样的:
[Object, Object, Object, Object, Object, Object, Object]
0: Object
thumbUrl: "https://os.alipayobjects.com/rmsportal/NDbkJhpzmLxtPhB.png"
uid: -1
url: "https://os.alipayobjects.com/rmsportal/NDbkJhpzmLxtPhB.png"
__proto__: Object
1: Object
2: Object
3: Object
4: Object
5: Object
6: Object

**Comment by afc163** [comment]
defaultFileList 不是受控属性，只有第一次生效，请认真研读 http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by laolu87** [comment]
恩恩,仔细看了一下Upload的api,还有一个fileList可以使用.
