### ISSUE TITLE
should Progress Component support to config background color

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#21550]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
progress support to config background-color, 如果可以的话，我这边可以提个pr,类似这种
![image](https://user-images.githubusercontent.com/22393991/75130378-0c3f0400-5709-11ea-8a51-9d9a746b5bc2.png)

### What does the proposed API look like?
backgroundColor = {color}

**Comment by afc163** [comment]
Is it `strokeColor` what you ask for?

**Comment by AshoneA** [comment]
@afc163 是没有完成的背景色，比如Percent是80%， 然后剩下的20%的颜色现在是不可配置的

**Comment by afc163** [comment]
现在有个 trailColor 只对 circle 类型生效，可以来个 PR 修复一下 line 类型。

https://codesandbox.io/s/exciting-hypatia-n3v62
