### ISSUE TITLE
Table组件实现第一行内容居中显示，从第二行开始内容居右显示

### ISSUE THREAD

**Issue by pushingmyway** [ant-design/ant-design#2156]
const renderContent = function (value, row, index) {
	  let obj = {
	    children: value,
	    props: {},
	  };
	  if (index == 0) {
	  	obj.props.textAlign = 'center';
	  	obj.className = 'digit-middle';
	  } else {
	  	obj.props.textAlign = 'right';
	  }
	  return obj;
	};

const manager_columns = [{
		title : '认证用户昵称',
		dataIndex: 'nick_name',
		render: renderContent,
	},{.....

代码这样写，if条件里的赋值应该是不成功

**Comment by afc163** [comment]
可以参考这个例子的对齐：http://ant.design/components/table/#components-table-demo-bordered
