### ISSUE TITLE
Dropdown doesn't scroll when using arrows to select item when use dropdownRender

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#21562]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mraiguo/pen/OJVWppZ?editors=0110](https://codepen.io/mraiguo/pen/OJVWppZ?editors=0110)

### Steps to reproduce
请在ie11下测试, 而且不同于这个 https://github.com/ant-design/ant-design/issues/7934，此问题是使用了dropdownRender，在外层div出现滚动条导致的
1. 点击Select 输入框
2. 拖动滚动条
https://i.loli.net/2020/02/24/pxvBKeEGyb1uXj3.gif
### What is expected?
能够拖动滚动条滚动

### What is actually happening?
一点击到滚动条，下拉框立即闪退

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | react16 |
| System | win10 |
| Browser | ie11 |

**Comment by afc163** [comment]
试试 https://ant.design/components/select-cn/#components-select-demo-custom-dropdown-menu 的解决方案。
