### ISSUE TITLE
Descriptions Span does not always span to the desired value

### ISSUE THREAD

**Issue by m-weeks** [ant-design/ant-design#21565]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blue-feather-zb6wj)

### Steps to reproduce
Add `span` to a description item that is not the first item in a row to span an entire row.

### What is expected?
Using the codesandbox example, the Address field should span onto a new line. The state field should also take up 2 columns, like it would if Address were not there.

### What is actually happening?
When a description item is set to span, it will only span if the previous items add up to be the correct number of columns.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome 79.0.3945.130 |

---
This is problematic for dynamically generated `Description` components, as you would need to calculate the number of columns for each item specifically to allow the spanning field to actually span.

**Comment by zombieJ** [comment]
You should add `span={2}` with second last item. Description always fill last item to the rest span within a row. So you set:
```
[1][1][1]
[1][1][3]
```

It will be:
```
[1][1][1]
[1][1][1]
```

**Comment by LiHaoGit** [comment]
@zombieJ  https://codesandbox.io/s/gracious-mayer-ro7um 这里依然有`Each child in a list should have a unique "key" prop.`的警告

**Comment by yoyo837** [comment]
我还没留意到已经支持响应式写法了。😂

**Comment by m-weeks** [comment]
@zombieJ The problem with that though is it becomes difficult to use a `Descriptions` component when you want to conditionally show items.

In my given example, if "occupation" was conditionally shown, I would need to then add `span={3}` on the second last item. Now this isn't the worst, but what if you have multiple conditionally shown items? Then you would need to calculate the spanned columns for each item.

See the following example:
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-sunset-0uy7y)

**Comment by bobsquito** [comment]
> [@zombieJ](https://github.com/zombieJ) The problem with that though is it becomes difficult to use a `Descriptions` component when you want to conditionally show items.
> 
> In my given example, if "occupation" was conditionally shown, I would need to then add `span={3}` on the second last item. Now this isn't the worst, but what if you have multiple conditionally shown items? Then you would need to calculate the spanned columns for each item.
> 
> See the following example: [![Edit on CodeSandbox](https://camo.githubusercontent.com/ecd139ba9847d0c77607c86339eb8ee6939ca85143a92ae16ebf20f58325e1b6/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/new-sunset-0uy7y)

Here is a function in case anyone else finds this and doesn't want the default behaviour.

This takes in the number of columns and the items and if any row is going to exceed the number of columns, instead of reducing the span of the final item in the row (default behaviour), this will increase the span of the second last item so that it takes up the full row, and the final item will be on a new row.

```
function balanceCollapseSpans(numColumns, items) {
  items.reduce((current, item, index) => {
    if (Number(item.span || 0) > numColumns) item.span = numColumns; // span cannot be more than numColumns
    let next = current + Number(item.span || 1); // what the span sum will be with this item
    // if the span sum is over the number of columns
    if (next > numColumns) {
      const remainder = numColumns - current; // the spaces remaining on the previous row
      // if it is not the first one, add the remainder to the previous item span
      if (index > 0) {
        const previousItem = items[index - 1];
        previousItem.span = Number(previousItem.span || 1) + remainder;
      }
      next = 0;
    }
    if (numColumns === next) next = 0;
    return next;
  }, 0);
  return items;
}
```
