### ISSUE TITLE
Table - Column render not working on state changing.

### ISSUE THREAD

**Issue by ichemidov** [ant-design/ant-design#21573]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-zhukovsky-qi41o)

### Steps to reproduce
1) Press 'Edit' button

### What is expected?
Input rendered at Math Score column

### What is actually happening?
Input isn't rendered. Only text.

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 16.12.0 |
| System | win 10 |
| Browser | Chrome 80.0.3987.122 |

---
It works fine with antd 3.x version (for example example with 3.26.12), but not with 4.x

**Comment by zombieJ** [comment]
Do not change `data` directly. It should be immutable: https://codesandbox.io/s/spring-dew-5uhzy

**Comment by waylandc** [comment]
> Do not change `data` directly. It should be immutable: https://codesandbox.io/s/spring-dew-5uhzy

So we cannot have a table containing data that is being auto-refreshed in background??

**Comment by waylandc** [comment]
> > Do not change `data` directly. It should be immutable: https://codesandbox.io/s/spring-dew-5uhzy
> 
> So we cannot have a table containing data that is being auto-refreshed in background??

Nevermind, I was able to figure it out. Here is a sandbox where I change state using setInterval and the table gets autorefreshed

[https://codesandbox.io/s/antd-reproduction-template-bls9f?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-bls9f?file=/index.js)

**Comment by jailsonpaca** [comment]
I solve this problem with this tool: https://stackoverflow.com/questions/46240647/react-how-to-force-a-function-component-to-render
