### ISSUE TITLE
层级表格子节点数据异步加载后拼装速度越来越慢

### ISSUE THREAD

**Issue by jaredleechn** [ant-design/ant-design#2157]
#1454 

需求场景是，一个树形表格，每一行数据都可能有自己的儿子节点，并且子节点也需要分页，数据量非常大，需要异步加载

目前采取根数据作为 Array root，所有的子节点存储为 Object patch （key 为父节点的 id），onExpandedRowsChange 的时候，执行 `loadChild(record.id)`，将数据先加到 patch 上，然后递归遍历 root，将 patch 拼接上去

导致的问题是随着展开次数增多，层级数据越来越多，拼装速度越来越慢，有好办法解决这个问题么？

**Comment by afc163** [comment]
给个调试的例子，估计有优化的空间。
