### ISSUE TITLE
onCancel cannot be triggered when click outside of Popconfirm

### ISSUE THREAD

**Issue by LuuuFan** [ant-design/ant-design#21570]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-z49r5)

### Steps to reproduce
1. Create a RadioGroup with Popconfirm, passing onConfirm and onCancel to it.
2. Click Radio to trigger Popconfirm
3. Click outside of Popconfirm

### What is expected?
onCancel can be triggered, selected radio goes back to previous selection.

### What is actually happening?
onCancel cannot be triggered, selected radio has been updated to new one.

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | 16.8.4 |
| System | macOS 10.15.3 |
| Browser | Chrome |

**Comment by afc163** [comment]
1. Try `onVisibleChange`
2. Change another interaction: https://codesandbox.io/s/antd-reproduction-template-f8ud1
