### ISSUE TITLE
Can not import Icon from antd v4 ("antd": "^4.0.0-rc.1")

### ISSUE THREAD

**Issue by luxuze** [ant-design/ant-design#21574]
![image](https://user-images.githubusercontent.com/35137889/75221562-1d594500-57dd-11ea-87f8-939a46691665.png)

**Comment by yoyo837** [comment]
https://next.ant.design/docs/react/migration-v4-cn#%E5%9B%BE%E6%A0%87%E5%8D%87%E7%BA%A7
