### ISSUE TITLE
bug: Slider RTL style 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#21585]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://ant.design/components/slider-cn/#components-slider-demo-mark

### Steps to reproduce
- 选择 RTL 模式
- 观察滑块下表 文字

### What is expected?
- 文字位置正常

### What is actually happening?
- 文字位置错误

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | The latest |
| System | mac |
| Browser | chrome 80 |

---
LTR 模式下，style  为 `translateX(-50%)`
RTL 模式下，style 应该调整为 `translateX(50%)`

**Comment by xrkffgg** [comment]
https://github.com/react-component/slider/blob/aa11444ff1c5d45f709a637921e877834dae4643/src/common/Marks.jsx#L42

这个模块没有 RTL 的判断

**Comment by yoyo837** [comment]
@saeedrahimi  Can you help to have a look?

**Comment by saeedrahimi** [comment]
> @saeedrahimi Can you help to have a look?

Yeah, I will fix this.

**Comment by saeedrahimi** [comment]
sorry for late, this bug was fixed by someone else [here](https://github.com/react-component/slider/pull/630), and it wasn't just for RTL style, it was happening in `reverse` mode of `rc-slider` component.
Thanks @zuochenxue for fixing this bug.
