### ISSUE TITLE
Select label ellipsis not working with Form.Item in 4.0.0-rc.6 

### ISSUE THREAD

**Issue by sntptrck** [ant-design/ant-design#21586]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rj2cm?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Put Select with Form.Item in Column
2. Open select value with long label.
3. see how overflow ellepsis not working

### What is expected?
Overflow ellepsis works

### What is actually happening?
Overflow ellepsis not works

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 16.12 |
| System | Windows 10 |
| Browser | Chrome |

---
Works in 4.0.0 rc-5

**Comment by afc163** [comment]
broken by https://github.com/ant-design/ant-design/pull/21476/files#diff-51de536edf29809d26f0ccfab96f81fcR146
