### ISSUE TITLE
Expanded row in scrollable table does not break into lines (commit break)

### ISSUE THREAD

**Issue by filipjnc** [ant-design/ant-design#21596]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-edison-uf8tx)

### Steps to reproduce
1. Open the reproduction env in a tablet-size window
2. Expand a row

### What is expected?
The contents in the expanded row break into lines (like in 3.24.1 or better yet in 3.23.2)

### What is actually happening?
The contents in the expanded row display in one line and enlarge the scrollable area to thousands of pixels.

| Environment | Info |
|---|---|
| antd | 3.24.2 |
| React | Irrespectively |
| System | Irrespectively |
| Browser | Irrespectively |

---
This has been introduced with this commit: https://github.com/ant-design/ant-design/pull/19284
Best behavior was achievable in 3.23.2.

**Comment by afc163** [comment]
If you turn on `scroll.x` to any value, scroll bar should be shown in small screen, I believe it is a expected behavior. The behavior of `3.23.2` is not different to table without `scroll` prop.

**Comment by filipjnc** [comment]
@afc163 I agree with the first sentence only partly. If the table has say is 500px wide unexpanded and the screen is 320px, yes it should show be scrollable. However, if the expanded row is shown, I expect the table to stay 500px wide and not 3000px with a long one line text. Some word-break must be implemented, otherwise the UX is bad and most use cases for expanded rows are useless now.

In 3.23.2 I could still scroll left and right and the expanded row remained 500px wide on opening.

**Comment by afc163** [comment]
I think you have the point, I tweak it in https://github.com/react-component/table/commit/9d6f5be68a96be68925f86cfabc50c0fd030bfc9 and released rc-table@6.10.13

Try remove node_modules/yarn.lock/package-lock.json and reinstall it.

**Comment by filipjnc** [comment]
@afc163 now it's perfect! Hope it stays like it is. Congrats on release of 4.0.0, looking forward to migrate.
