### ISSUE TITLE
RTL pagination for table

### ISSUE THREAD

**Issue by andriyklym** [ant-design/ant-design#21591]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5rpfd)

### Steps to reproduce
Add table with min data and config for RTL

### What is expected?
Pagination on left side

### What is actually happening?
Pagination on right side with arrows bugs

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | 79 |

---
In sandbox in shows as expected, but on my env, all components apply RTL rules without table pagination

**Comment by andriyklym** [comment]
![image](https://user-images.githubusercontent.com/22375996/75245612-b9cc1900-57d6-11ea-8aeb-ea28afafd6e0.png)
This is screen from my env. I checked classes from HTML, and on sandbox antd use ant-table-rtl and ant-pagination-rtl, but in my env this is not added.

**Comment by saeedrahimi** [comment]
I think the problem is with your environment setup, because reproduction in sandbox works as you expected.

**Comment by andriyklym** [comment]
ant-pagination-rtl
