### ISSUE TITLE
如何扩充icon字体

### ISSUE THREAD

**Issue by hhhyaaon** [ant-design/ant-design#2159]
## 场景
antd已提供部分iconfont，项目中还存在一些antd未提供的图标，如何把这些新的字体图标扩充到antd字体图标中？

**Comment by afc163** [comment]
通用图标给我们提需求，非通用图标自行使用 iconfont.cn 。

**Comment by hhhyaaon** [comment]
## 场景
目前有两份iconfont文件：
1、原antd字体文件
2、通过iconfont.cn可以导出的自定义字体文件antd_user

通过覆盖font-family可以扩充项目使用的图标
![image](https://cloud.githubusercontent.com/assets/17123400/16331195/216d5920-3a21-11e6-9399-f62cea14e193.png)


但是由于两份字体文件中，存在重复的Unicode，故当想使用antd_user中的某个图标，antd中有同unicode的不同图标，故导致无法取到antd_user中的图标

## 问题
是否可以将两份字体文件进行合并，而不是简单的覆盖？

**Comment by chenfengyanyu** [comment]
遇到了同样的问题，不知道题主解决了没？@hhhyaaon

**Comment by lijinlone** [comment]
antd自带的icon Unicode是e6开始的，可以通过修改Unicode的方式，
![antd](https://user-images.githubusercontent.com/1265291/29158009-d1d3188c-7ddb-11e7-855b-cc3554350ae4.JPG)

**Comment by xianghongai** [comment]
时至今日，有解决方案？
如果只是普通用直接 import iconfont下载的样式表就好；
如果要整合到 Menu 这类组件中，官方目前 `Icon.createFromIconfontCN()` 提供的方案，引用本地的有问题，即使是放根目录、开静态服务器。
