### ISSUE TITLE
Type '"404"' is not assignable to type '404 | 500 | 403 | "success" | "error" | "info" | "warning" | undefined'.

### ISSUE THREAD

**Issue by MingRock** [ant-design/ant-design#21592]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-shamir-btc0t)

### Steps to reproduce
Result status类型定义错误

### What is expected?
应该是字符串403 404

### What is actually happening?
定义成了数字类型

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 16.12.0 |
| System | LinuxMint |
| Browser | Chrome 79.0.3945.130 |

**Comment by wendellhu95** [comment]
According to the [RFC 2616](https://tools.ietf.org/html/rfc2616#section-6.1.1), the status code should be a 3-digit integer.

**Comment by yoyo837** [comment]
d.ts:
![image](https://user-images.githubusercontent.com/6134547/75311011-628a7f00-5890-11ea-9b03-e42c811bdab8.png)

source: 
![image](https://user-images.githubusercontent.com/6134547/75311018-69b18d00-5890-11ea-8ac8-a2ececbe1620.png)

**Comment by afc163** [comment]
Reproduce link: https://codesandbox.io/s/charming-cherry-ubw3y

**Comment by zhang6223284** [comment]
这个在 3.x 的版本不修了吗，现在不想升级4.0，但是 3.26.12的版本也有这个问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/a473770836a6b72ee7815056a41b850e4c4f77aa
