### ISSUE TITLE
update antd version when openning in riddle/codesandbox/stackblitz

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#21605]
After 4.0 release:

- [x] 3x.ant.design: antd version should be 3.x
- [x] ant.design: antd version should be 4.x
- [x] https://next.ant.design should redirect to https://ant.design after released.

**Comment by afc163** [comment]
- [ ] next badge in README should be removed too.

**Comment by zombieJ** [comment]
前三个可以提前搞掉 #21642
