### ISSUE TITLE
form.getFieldsValue 方法获取嵌套的字段值是个对象

### ISSUE THREAD

**Issue by wangzongming** [ant-design/ant-design#21601]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://next.ant.design/components/form-cn/#components-form-demo-validate-other](https://next.ant.design/components/form-cn/#components-form-demo-validate-other)

### Steps to reproduce

    const { Form, Input, Button } = antd;  
    const Demo = () => { 
       const [form] = Form.useForm(); 
      const onFinish = _ => {
          //实际上想获得user.name的值
          console.log(form.getFieldsValue( [ ['user', 'name'] ] ))
       }; 
      return (
        <Form form={form} name="nest-messages" onFinish={onFinish}> 
          <Form.Item
            name={['user', 'name']}
            label="Name" 
          >
            <Input /> 
          </Form.Item> 
          <Form.Item>
            <Button type="primary" htmlType="submit">
              Submit
            </Button>
          </Form.Item>
        </Form>
      );
    };

    ReactDOM.render(<Demo />, mountNode); 

![微信图片_20200226141335](https://user-images.githubusercontent.com/27466569/75317199-51e30480-58a2-11ea-87bf-0afaeb7ec1ca.png)

### What is expected?
返回一个字段的实际值

### What is actually happening?
一个对象

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 16.8 |
| System | window10 |
| Browser | Chrome 75.0.3770.80（正式版本） （64 位） |

**Comment by yoyo837** [comment]
当你取全部表单值时，并不是返回每个值，而是一个对象，为什么取部分的时候又要求只返回部分值呢？

例如，你的表单有三个字段，`['user', 'name']`, `['user', 'age']`, `['other', 'xxz']`
```json
{
  "user": {
    "name": "xxx",
    "age": 16,
  },
  "other": {
    "xxx": "yyy"
  }
}
```

**Comment by wangzongming** [comment]
确实，想错了

> 当你取全部表单值时，并不是返回每个值，而是一个对象，为什么取部分的时候又要求按具体值返回部分呢？
> 
> 例如，你的表单有三个字段，`['user', 'name']`, `['user', 'age']`, `['other', 'xxz']`
> 
> ```json
> {
>   "user": {
>     "name": "xxx",
>     "age": 16,
>   },
>   "other": {
>     "xxx": "yyy"
>   }
> }
> ```

**Comment by yoyo837** [comment]
还有个`getFieldValue` 你试试

**Comment by wangzongming** [comment]
> 还有个`getFieldValue` 你试试

嗯，我就是用了getFieldValu突然想起来的，然后发现我思路不对！哈哈。
