### ISSUE TITLE
当两个column的sorter为true时，第二个不能显示当前的状态

### ISSUE THREAD

**Issue by wukong1995** [ant-design/ant-design#21600]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/wukong1995/pen/abOJpGX](https://codepen.io/wukong1995/pen/abOJpGX)

### Steps to reproduce
直接运行即可

### What is expected?
第一个和第二个column的排序状态可正常显示

### What is actually happening?
第一个可正常显示，第二个column不能显示当前的排序状态

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.12.0 |
| System | macos |
| Browser | 最新chrome |

**Comment by afc163** [comment]
3.x 不支持多列排序，请尝试 4.x：https://github.com/ant-design/ant-design/issues/20661
