### ISSUE TITLE
级联下拉菜单，是否支持异步请求

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2161]
点击下拉菜单，选中项是否能支持异步从后台获取数据

提个需求，类似国家地点配置的，下拉想做成异步请求，请问官方有没有更好的实现方式

**Comment by afc163** [comment]
上层文档暂时没有放。

http://react-component.github.io/cascader/examples/dynamic-options.html

**Comment by wuhaih** [comment]
ANTD的级联菜单什么时候把上层实现集成进去
