### ISSUE TITLE
ant.design group cells with row selection

### ISSUE THREAD

**Issue by zxzzxxzx** [ant-design/ant-design#21629]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using tables with row selection to display data. Row selection feature allows adding checkboxes to each row for selection, but I need the same feature for grouped rows/cells (pls see the screen here: https://i.stack.imgur.com/BkAdD.png )
So right now there are 1 separate row selection checkbox for each row. Is it possible to show 1 checkbox for such cases instead of 2 (also group cells with checkboxes). If it has already been implemented, a link would be welcome. Thank you.

### What does the proposed API look like?
Not sure about this, maybe this has already been implemented somehow.

**Comment by zxzzxxzx** [comment]
I guess this issue may be related to the question:

https://github.com/ant-design/ant-design/issues/3505

If this has already been resolved is there any example btw?

**Comment by zombieJ** [comment]
Thanks for feedback. Let me handle this. Merge into #3505 firstly.
