### ISSUE TITLE
npm create umi 无法安装

### ISSUE THREAD

**Issue by huberystyle** [ant-design/ant-design#21637]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://dddd.ddd](https://dddd.ddd)

### Steps to reproduce
npm create umi 无法安装

ps. 没有网址，网址还搞个表填....

### What is expected?
安装成功

### What is actually happening?
? Select the boilerplate type ant-design-pro
? 🤓 Which language do you want to use? JavaScript
? 🦄 Time to use better, faster and latest antd@4! No
events.js:298
      throw er; // Unhandled 'error' event
      ^

TypeError: self.env.emit is not a function
    at /Users/hu_yicheng/.npm/_npx/3200/lib/node_modules/create-umi/node_modules/yeoman-generator/lib/index.js:653:22
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Emitted 'error' event on AntDesignProGenerator instance at:
    at Immediate.<anonymous> (/Users/hu_yicheng/.npm/_npx/3200/lib/node_modules/create-umi/node_modules/yeoman-generator/lib/index.js:668:20)
    at processImmediate (internal/timers.js:456:21)

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 最新 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design-pro/issues/6020
