### ISSUE TITLE
Resize does not work in group column

### ISSUE THREAD

**Issue by finas** [ant-design/ant-design#21638]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-black-ezi8o)

### Steps to reproduce
Drag the first column named Date

### What is expected?
It can resize the column width

### What is actually happening?
The resize in first columns seems unavailable.

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | lastest |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
We have no plan to cover it.
