### ISSUE TITLE
Modify dropdown placement for TreeSelect

### ISSUE THREAD

**Issue by tennox** [ant-design/ant-design#21630]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate. (possibly #8326 :stuck_out_tongue_winking_eye: )

### What problem does this feature solve?
We have a TreeSelect in the top right of the screen. When the dropdown tree is bigger than the width of the select field, the dropdown is expanding to the right - outside of the screen.

I can't set `dropdownPlacement` prop on the TreeSelect.

I think the same is valid for a regular Select component.

### What does the proposed API look like?
```jsx
<TreeSelect
  dropdownPlacement="bottomRight" />
```

Which just passes to the Dropdown component: https://ant.design/components/dropdown/#components-dropdown-demo-placement

**Comment by atirudom** [comment]
+1 confirm problem, this needs to be fixed.

This issue happens not only with width but also with height.

When the TreeSelect dropdown height is larger than the screen, it expands to the top of the input - outside of the screen.

**Comment by Youthink** [comment]
+1

**Comment by Youthink** [comment]
https://github.com/react-component/tree-select/issues/12

**Comment by afc163** [comment]
Merge into #31753
