### ISSUE TITLE
在 customize-cra 中的 fixBabelImports 配置 babel-plugin-import，不够好，会导致无法配置多个按需加载

### ISSUE THREAD

**Issue by dyb881** [ant-design/ant-design#21639]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前文档上的说明只能用到 antd，无法用到多个包

### What does the proposed API look like?
const { override, fixBabelImports } = require('customize-cra');

// 这样配置可以用到多个包
module.exports = override(
  fixBabelImports('antd', { libraryDirectory: 'es', style: true }),
  fixBabelImports('lodash', { libraryDirectory: '', camel2DashComponentName: false }),
);

**Comment by yoyo837** [comment]
请在 https://github.com/arackaf/customize-cra 中提交issue.

**Comment by afc163** [comment]
对的，有多个包的需求自行修改就行了，官网文档只是示例。
