### ISSUE TITLE
TreeSelect 下拉树中如果树结点的value值重复

### ISSUE THREAD

**Issue by tipsxBase** [ant-design/ant-design#21636]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://react-ahxmrj.stackblitz.io](https://react-ahxmrj.stackblitz.io)

### Steps to reproduce
点击下拉树跟树进行操作，对比

### What is expected?
1、是否可以做到像Tree组件一样，可以让树结点的value重复，
2、勾选一个树结点，其它value相同的结点可以同时选中

### What is actually happening?
TreeSelect如果树结点的value重复，控制台会报警告，并且勾选树结点会出现问题

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.12.0 |
| System | Mac Pro |
| Browser | Chrome 80.0.3987.122 |

**Comment by zombieJ** [comment]
设计如此。另外Tree 的 `key` 也不能相同，否则也会有问题。
