### ISSUE TITLE
why form-field children of render props only work with shouldupdate?

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#21645]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Mostly, if field-B depend on field-A, field-B need to know about field-A value, so field-B should be a render props as Field's children. Maybe I write `denpendencies={['field-A']}` then It should be work. But now Field children of render props only work with `shouldupdate`, then I need to write a function to compare the pre-value and current value, maybe dependencies should do more work for convenience。Is it designed on purpose? I read field-form code it should be fine. Like `dependencies={['gender']}` replace  `shouldUpdate={(prevValues, currentValues) => prevValues.gender !== currentValues.gender} `in https://next.ant.design/components/form-cn/#components-form-demo-control-hooks. 

### What does the proposed API look like?
render props should work with dependencies props

**Comment by zombieJ** [comment]
`dependencies` is an option but we didn't export to support render props yet is wish more user feedback since API is hard to remove if added. So we provides most flex way api `shouldUpdate` at the beginning.

But yes, it will come if more developer want this : )

**Comment by AshoneA** [comment]
Thanks for your answer. Maybe I'm the first guy that wants this  : ).  
btw, the new form performance is awesome, I like it!
