### ISSUE TITLE
Popover width is not properly re-calculated after adding  contents dynamicaly inside it

### ISSUE THREAD

**Issue by nijeesh4all** [ant-design/ant-design#21641]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/nijeesh4all/reactShopping/tree/master/?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Scenario #1
1. refresh the browser
2. Open the popover by clicking the cart button on the top right corner
3. then add items to the cart by clicking add to cart button
4. open the popover again

Scenario #2

1. refresh the browser
2. add items to the cart by clicking add to cart button ( do not click the cart icon before this )
3. open the popover

### What is expected?
in Scenario #1 you can see that popover didn't resize to accomadate the newly added contents to it.

### What is actually happening?
Popover should re-calculate its width after adding contets dynamicaly to it.

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | 16.12 |
| System | MacOS:Latest , Linux:Ubuntu:18 |
| Browser | Chrome:latest , Firefox:latest |

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/14977#issuecomment-467486171
