### ISSUE TITLE
bug: Date Picker disabled style 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#21644]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled](https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled)

### Steps to reproduce
- 打开链接
- 鼠标移到 禁用控件的尾部 图标上

### What is expected?
鼠标 禁用 状态

### What is actually happening?
鼠标为输入状态

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
@xrkffgg 再明示一下具体指的哪里？

**Comment by xrkffgg** [comment]
@yoyo837 
https://3x.ant.design/components/date-picker/#components-date-picker-demo-disabled

现在官网更新了，这是3.x 的 bug

鼠标移动到 disabled 的图标上，图标的 鼠标样式不对

**Comment by xrkffgg** [comment]
不过也不碍事

**Comment by yoyo837** [comment]
噢，我还以为4.0， 最近我人都恍惚了，看什么都不仔细细心！😅

**Comment by shaodahong** [comment]
Closed by #21655
