### ISSUE TITLE
TreeNode: Function components cannot be given refs.

### ISSUE THREAD

**Issue by fpsqdb** [ant-design/ant-design#21640]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-sound-hv0kr)

### Steps to reproduce
1. Create a Tree
2. Add TreeNode
3. Add ref on TreeNode

### What is expected?
Should receive the ref callback normally

### What is actually happening?
Get warning `Function components cannot be given refs` from console.

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.13.0 |
| System | windows 10 1909 |
| Browser | 80.0.3987.122 |

**Comment by zombieJ** [comment]
TreeNode is a syntactic sugar.  It will not really render in the view which is meaningless to give refs.
