### ISSUE TITLE
Collapse arrow doesn't respect padding changes

### ISSUE THREAD

**Issue by mtjn** [ant-design/ant-design#21648]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mtjn/antd-issue-21648-minimal-repro](https://github.com/mtjn/antd-issue-21648-minimal-repro)

### Steps to reproduce
Customize @collapse-header-padding-extra

### What is expected?
The collapse arrow should move in accordance with the updated padding value, so that correct spacing is maintained between the arrow and header

### What is actually happening?
The collapse arrow doesn't move, so that the header and collapse arrow overlap

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.11.0 |
| System | Ubuntu 19.10 |
| Browser | Chromium Version 80.0.3987.122 (Official Build) snap (64-bit) |

**Comment by zombieJ** [comment]
Arrow position is controlled by `@padding-md`. You should adjust this also.
