### ISSUE TITLE
Examples cannot open

### ISSUE THREAD

**Issue by glitchboyl** [ant-design/ant-design#21657]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://react-component.github.io/table/examples/expandIcon.html](http://react-component.github.io/table/examples/expandIcon.html)

### Steps to reproduce
pls open the link.

### What is expected?
can view examples normally.

### What is actually happening?
pls open the link.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8  |
| System | Manjaro KDE |
| Browser | Chrome |

**Comment by afc163** [comment]
Please report this to https://github.com/react-component/table/issues
