### ISSUE TITLE
[4.0] auto complete trigger bug

### ISSUE THREAD

**Issue by zkwolf** [ant-design/ant-design#21662]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/auto-complete-cn/](https://ant.design/components/auto-complete-cn/)

### Steps to reproduce
![GIF](https://user-images.githubusercontent.com/8555127/75506988-ab6e3f00-5a1a-11ea-9f8b-03d9bf66d8f9.gif)

### What is expected?
只触发一个

### What is actually happening?
触发了两个下拉菜单

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | x |
| System | win10 |
| Browser | chrome 80 |

**Comment by zombieJ** [comment]
Nice catch!

**Comment by afc163** [comment]
还有一个问题是 AutoComplete 现在在 input 里双击选中文字（或者连续点击）的时候，弹层会不断收起再弹出。3.x 里是 focus 的逻辑，弹层很稳定（这样体验好一点）。

**Comment by zombieJ** [comment]
ok，顺道一起改了
