### ISSUE TITLE
Menu 组件 “只展开当前父级菜单”时，展开收缩动画诡异

### ISSUE THREAD

**Issue by llyp618** [ant-design/ant-design#21666]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/menu](https://3x.ant.design/components/menu)

### Steps to reproduce
官网 - Menu组件 - “只展开当前父级菜单” 。 展开菜单最后一项，然后点击前一项展开，

### What is expected?
展开项正常过渡展开，收缩项正常收缩

### What is actually happening?
展开项动画过渡几乎没有，并且最后一项收缩动画也非常奇怪。

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.12.0 |
| System | OS X |
| Browser | chrome latest |

---
4.0 版本一样存在这个问题，3.23 以前版本没有这个问题的，官网2.x版本也没有问题，可以对比下两者的差别

**Comment by afc163** [comment]
- ✅ 3.23.6: https://codesandbox.io/s/optimistic-forest-v1obl
- ❌ 3.24.0: https://codesandbox.io/s/brave-tdd-wrh0o

**Comment by afc163** [comment]
Broken by #19205

**Comment by afc163** [comment]
还发现一个问题

https://github.com/ant-design/ant-design/blob/3ee0e4a58e0f93aaf3cec89dad1488c7a060ef02/components/style/core/motion.less#L18

这里改成

```diff
- transition: height 0.15s @ease-in-out, opacity 0.15s @ease-in-out !important;
+ transition: height 3s @ease-in-out, opacity 0.15s @ease-in-out !important;
```

预期是菜单伸缩是 3s，但是 0.15s 就走完了。

**Comment by zombieJ** [comment]
有点神奇。 。 。我看看

**Comment by zombieJ** [comment]
1. 预期是菜单高度伸缩是 3s，但是 0.15s 就走完了。

这个是因为设置了 deadline 是 `500`，改掉就行了。

2. 收缩动画

初步 debug 下来是动画跳帧了，具体原因还在看。单独抽出来就重现不了了，推测和 menu 渲染有关。

**Comment by afc163** [comment]
> 这个是因为设置了 deadline 是 500，改掉就行了。

不是，deadline 也改成 3s，动画还是 0.15s 就走完了。

**Comment by zombieJ** [comment]
`opacity 0.15s` 这个触发了 motionEnd，CSSMotion 支持判断 prop 类型结束动画，Menu 里时间是一样的所以没有加。调试都改成 3s 就行了。
