### ISSUE TITLE
时间轴能否提供参数设置，控制横向及纵向

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2166]
提个需求，时间轴能否提供参数设置，控制横向及纵向，如果是横向，是否能增加上下标题设置

**Comment by afc163** [comment]
没有设计稿，前端很难直接支持的，你可以把你的具体需求（描述和图）列出来。

**Comment by wuhaih** [comment]
好的，公司网络部运行上传附件，回家画个图给你们，谢谢，最近解决了蛮多问题

**Comment by wuhaih** [comment]
不允许上传附件，回头我回家上传

**Comment by afc163** [comment]
没反馈先关了。
