### ISSUE TITLE
[Badge] Weird rolling animation between 9 to 11

### ISSUE THREAD

**Issue by AlbertLucianto** [ant-design/ant-design#21674]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/badge/#components-badge-demo-change](https://ant.design/components/badge/#components-badge-demo-change)

### Steps to reproduce
Change up and down between 9 to 11

### What is expected?
It should only roll a little

### What is actually happening?
Rolls one (or more) full cycle

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13 |
| System | macOS 10.14.5 |
| Browser | Chrome |

**Comment by wendellhu95** [comment]
🙋‍♂️

**Comment by afc163** [comment]
3.x has same problem.

**Comment by wendellhu95** [comment]
> 3.x has same problem.

I will fix that in 3.x as well.

**Comment by wendellhu95** [comment]
<img width="500" alt="截屏2020-03-0317 02 11" src="https://user-images.githubusercontent.com/12122021/75759957-5f503100-5d71-11ea-825f-29de758e299d.png">

似乎之前的动画机制有问题。逻辑上是想让 0-9 或者 9-0 滚动时，先回到 10-19 内的位置（**复位**），然后再进行滚动（**滚动**），以达成平滑的效果，但实际上复位和滚动两步是同步的，浏览器直接当作一个动画效果来处理。
