### ISSUE TITLE
[dark mode] incorrect global style of <h1>

### ISSUE THREAD

**Issue by imhele** [ant-design/ant-design#21670]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button/](https://ant.design/components/button/)

### Steps to reproduce
open link and enable the dark mode.

### What is expected?
enabling dark mode should not change the layout

### What is actually happening?
the `margin-bottom` style of `h1, h2, h3, h4, h5, h6` got changed.

![image](https://user-images.githubusercontent.com/32428655/75514716-19266500-5a33-11ea-8906-598d0761839d.png)

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | * |
| System | macOS 10.14.6 |
| Browser | Google Chrome 80.0.3987.122 |

**Comment by ycjcl868** [comment]
@chenshuai2144 maybe the `antd-pro-merge-less` library bug, it modified the order of Less files.

**Comment by afc163** [comment]
Fixed in https://github.com/chenshuai2144/merge-cssMoudle-less/pull/11
