### ISSUE TITLE
FormItem triggerType属性没有被过滤

### ISSUE THREAD

**Issue by janryWang** [ant-design/ant-design#21677]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-swirles-mm1bk)

### Steps to reproduce
直接看报错

### What is expected?
无报错

### What is actually happening?
Warning: React does not recognize the `triggerType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, 

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.x |
| System | osx |
| Browser | chrome |

**Comment by afc163** [comment]
There is no `triggerType` prop in Form.Item, did you mean `trigger` or `validateTrigger`?
