### ISSUE TITLE
4.0 Codesandbox icon

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#21672]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/#components-button-demo-icon](https://ant.design/components/button-cn/#components-button-demo-icon)

### Steps to reproduce
- 打开链接
- 选择使用自定义图标的例子
- 点击 “在 CodeSandbox 中打开”

### What is expected?
- 图标正常显示
- 控制台不报错

### What is actually happening?
- 图标显示空白
- 控制台报错

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | The latest |
| System | mac |
| Browser | chrome 80  |

**Comment by xrkffgg** [comment]
@zombieJ

**Comment by shaodahong** [comment]
Codesandbox 的缓存吧，看到的是 4.0 版本，实际上还是 3.0 版本，强刷一下就可以

**Comment by zombieJ** [comment]
确认了一下，的确是 codesandbox 缓存问题。

**Comment by afc163** [comment]
确实是缓存，我干脆固定一下 codesandbox 里的 antd 版本。
