### ISSUE TITLE
need to config Descriptions label width 需要配置描述列表的宽度

### ISSUE THREAD

**Issue by neo20** [ant-design/ant-design#21673]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
problem demo: 
[https://codesandbox.io/s/recursing-star-fsrc0?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/recursing-star-fsrc0?fontsize=14&hidenavigation=1&theme=dark)

The label is too width when column set to 1 and description value is short

### What does the proposed API look like?
a `labelWidth` property

**Comment by yoyo837** [comment]
不为1的时候`labelWidth ` 应该如何表现？

**Comment by neo20** [comment]
> 不为1的时候`labelWidth ` 应该如何表现？

    <Descriptions title="Note: The label is too wide!" bordered column={1} labelWidth={'20%'}>
        <Descriptions.Item label="Name">John</Descriptions.Item>
        <Descriptions.Item label="Introduction">not set</Descriptions.Item>
    </Descriptions>

有时展示的值很短时，label列和value列是等分的，即各50%，看起来很蠢。加上`labelWidth='20%'`，让label占20%的宽度，或者是像素。不管column设为几，都可以这样处理。

类似于

    <style>
     dt {display: inline-block;
     float: left;
     width: 20%;
     }
    </style>
    <dl>
     <dt>Name</dt>
     <dd>John</dd>
     <dt>Introduction</dt>
     <dd>not set</dd>
    </dl>

**Comment by yoyo837** [comment]
`className` 是不是就可以了？

**Comment by yoyo837** [comment]
外加
```less
${className} .ant-descriptions-item-label {
}
```

**Comment by neo20** [comment]
> 外加
> 
> ```css-less
> ${className} .ant-descriptions-item-label {
> }
> ```

谢谢提示，可行。抱歉对less和样式这块不太掌握，我再去补补。
你写的不太懂，我这样写的，可能不太规范

    import styles from './index.less';

    <Descriptions className={styles.setlabelwidth} title="..." column={1} >
        <Descriptions.Item label="Name">John</Descriptions.Item>
        <Descriptions.Item label="Introduction">not set</Descriptions.Item>
    </Descriptions>

在index.less里

    .setlabelwidth {
      th {
        width: 20%;
      }
    }
