### ISSUE TITLE
图片上传控件需求

### ISSUE THREAD

**Issue by zxyzxyzxyzxyzxy** [ant-design/ant-design#2168]
1、需要保持上传的图片比例保持不变，当前无法获取图片尺寸信息
2、在仅允许用户上传1张图片的场景下，当前交互设计和允许上传多张图片隐喻上相同，会在成用户误解。
3、上传多张图片时，在图片数量达到最大值时，当前方案：仍显示上传按钮，上传后默认替换最老的图片不太合理。因为在数量达到最大值的时候，用户不知道不可以上传了，所以会继续上传，结果发现图片被替换了，这个操作是超出预期的。
建议：当达到最大值时，上传按钮隐藏，小于最大值才出现。

**Comment by afc163** [comment]
这个自行控制就行了，demo 只是举个简单的例子，你可以用任何方式提示用户（弹出，disabled，hide）。

**Comment by zxyzxyzxyzxyzxy** [comment]
3点没问题
2点可否在已上传图片上有个上传的按钮，上传后替换当前图片
1点如何？

**Comment by afc163** [comment]
1) 获取图片大小网上一搜一大把，Upload 提供了 FileObject 对象的。http://stackoverflow.com/questions/12570834/how-to-preview-image-get-file-size-image-height-and-width-before-upload

2) 你可以上传开始后把上传控件隐藏：http://ant.design/components/upload#components-upload-demo-picture-card
