### ISSUE TITLE
Descriptions 提示Sum of column `span` in a line not match `column` of Descriptions.

### ISSUE THREAD

**Issue by LiHaoGit** [ant-design/ant-design#21686]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-hooks-indtj)

### Steps to reproduce
直接打开页面，即可看到问题

### What is expected?
无警告输出且 `<Descriptions.Item label="工作经验" span={3}> `独占一行

### What is actually happening?
有两个警告：  
1.Warning: [antd: Descriptions] Sum of column `span` in a line not match `column` of Descriptions.  
2.Warning: Each child in a list should have a unique "key" prop. Check the render method of `Descriptions`.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | Window 10 |
| Browser | Microsoft Edge 80.0.361.62 |

**Comment by yoyo837** [comment]
ref: #20786 @zombieJ 他这样用好像也合情理，像Grid 那种。

**Comment by LiHaoGit** [comment]
#21565 也是同样的问题

**Comment by yoyo837** [comment]
那就关掉这个在那边跟踪哈。

Duplicated of #21565

**Comment by zombieJ** [comment]
Description 总是会检查每行中 Item 的 span 总是是否占满一行。如果没有，就把最后一个 Item 拉伸填满这一行。如果超了，则缩小填满这行并且报错。

从 Description 组件角度它不知道这个 `3` 是故意的还是不小心的。和 Grid 处理逻辑是不同的。

另外 `key` 报错我需要看看是不是个 bug。

**Comment by zombieJ** [comment]
官网可复现 key 错误，重开了。

**Comment by zombieJ** [comment]
官网可复现 key 错误，重开了。

**Comment by wangmaidong** [comment]
我让我很牛的同事，帮我写了一个自动调整的方法
`
function doProcess(baseValue, sourceList, finalList) {
    let sum = 0;
    console.log("===");
    // 记录分组
    let result = [];
    // 记录剩余的元素
    let newSourceList = [...sourceList];

    // 如果只有一个元素，直接将其设为最大值（baseValue）
    if (sourceList.length === 1) {
        sourceList[0] = baseValue;
    }

    for (let i = 0; i < sourceList.length; i++) {
        let integer = sourceList[i];
        result.push(integer);
        newSourceList.shift(); // 从newSourceList中移除第一个元素
        sum = result.reduce((acc, curr) => acc + curr, 0);

        // 如果sum等于baseValue，记录下来并继续处理
        if (sum === baseValue) {
            finalList.push(...result);
            console.log(result);
            break;
        } else if (sum > baseValue) {
            // 如果sum大于baseValue，调整最后一个加的值
            let remove = result.pop();
            newSourceList.unshift(remove); // 将其重新添加到newSourceList的开头

            let beforeSum = result.reduce((acc, curr) => acc + curr, 0);
            let lastValue = result.pop();
            result.push(lastValue + (baseValue - beforeSum));
            finalList.push(...result);
            console.log(result);
            break;
        }
    }

    // 如果遍历完成后result中的和不够baseValue
    if (sum > 0 && sum < baseValue) {
        let lastValue = result.pop();
        result.push(lastValue + baseValue - sum);
        finalList.push(...result);
        console.log(result);
    }

    // 递归调用
    if (newSourceList.length > 0) {
        doProcess(baseValue, newSourceList, finalList);
    }
}
function main() {
    let valueList = [1, 1, 2, 3, 2, 1, 2, 2, 1, 2, 2, 3, 1];
    // let valueList = [1, 1, 1, 1, 1];
    let sourceList = [...valueList];
    let finalList = [];
    // baseValue可以配置，当前设为3
    doProcess(3, sourceList, finalList);
    console.log("Final list: " + finalList);
    console.log("------"); // 能够调整为 1,2,3,3,2,1,3,2,1,3,3,3,3
}

main();
`
使用效果：
![微信图片_20240826153613](https://github.com/user-attachments/assets/bf54f174-6914-4989-b530-f407fae542d3)
