### ISSUE TITLE
FormItem needs extra element to make it work with react-hook-form Controller

### ISSUE THREAD

**Issue by JeromeDeLeon** [ant-design/ant-design#21681]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-m0buf?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Create a Form with antd
2. Use react-hook-form validation (This doesn't have to be this one)
3. Use react-hook-form Controller
5. Try inserting value to username
6. Submit form

### What is expected?
The form is expected to get the form values even without extra element inside `Form.Item`.

### What is actually happening?
Form doesn't work correctly inside `Form.Item` when used with `Controller` component. It doesn't save any values inside `react-hook-form` and not validated correctly because it doesn't have any values.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | Linux |
| Browser | 80.0.3987.122 |

---
I read inside `Form.Item` and found out that if I inserted extra elements inside `Form.Item`, I was running to this [line 252 inside FormItem](https://github.com/ant-design/ant-design/blob/796b5d2e10de740923fd98a44c22acaee99db65f/components/form/FormItem.tsx#L252). I also noticed that maybe I was running inside [line 272](https://github.com/ant-design/ant-design/blob/796b5d2e10de740923fd98a44c22acaee99db65f/components/form/FormItem.tsx#L272).

**Comment by zombieJ** [comment]
Remove `name` prop on Form.Item if you are using third part form lib.
