### ISSUE TITLE
TextArea mix shorthand and non-shorthand properties for the same value.

### ISSUE THREAD

**Issue by callmemb** [ant-design/ant-design#21697]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6n7oo)

### Steps to reproduce
Use `Input.TextArea` with `autoSize` prop.

### What is expected?
do not throw warning/error.

### What is actually happening?
throw warning/error: 
```
Removing a style property during rerender (overflow) when a conflicting property is set (overflowY) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.
```

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react 16.13.0 |
| System | linux fedora 31 |
| Browser | ff v.73, chrome v.80 |

**Comment by afc163** [comment]
I cannot reproduce any warning in my brower console, could you provide some gif or video?

**Comment by zombieJ** [comment]
@afc163 , reinstall `node_modules`. Seems new come from react 16.13.

**Comment by gotjoshua** [comment]
will this fix also make it to the 3.x branch or only 4.x ?

**Comment by lgf196** [comment]
我想问一下，我也报了这个错，你最终是怎么解决的

**Comment by haohaitao** [comment]
I have this problem, too

**Comment by Noa-p** [comment]
I met this problem too

**Comment by 91he** [comment]
Waiting for solution.

**Comment by 91he** [comment]
> I have this problem, too

I found this problem was resolved 12 days ago, but the newest 3.x version was release 14 days ago. 
Maybe we should wait another few days.

**Comment by ecstAsy** [comment]
I have the same problem. Is there any solution?

**Comment by spirit-drive** [comment]
I upgraded antd to 3.26.14. It fixed this problem fo me

**Comment by bianzhe1995** [comment]
> I upgraded antd to 3.26.14. It fixed this problem fo me

this worked for me

**Comment by crazyair** [comment]
me too

**Comment by rost21** [comment]
+1

**Comment by UnicornXU** [comment]
me too

**Comment by jhlym** [comment]
I have no choice.
I remove autoSize property in Input.TextArea.

ps. i use antd 3.x

**Comment by shermanrxie** [comment]
I have same problem with antd 3.X. What's the next step?
