### ISSUE TITLE
非受控模式一个问题

### ISSUE THREAD

**Issue by warmhug** [ant-design/ant-design#2169]
例如原生表单的 input 在非受控模式下、它的 value 随着用户输入自己变化，但外部能通过类似 `this.refs.input.value` 方式获取到即时的值；我们组件的非受控模式、似乎做不到？应该算是功能缺失，这样子非受控模式几乎是没什么用的。

**Comment by afc163** [comment]
是可以的，嵌套一层，麻烦一点。

https://github.com/ant-design/ant-design/issues/1357

**Comment by warmhug** [comment]
不光是指 input 组件，所有区分受控和非受控的组件都应该考虑下、提供统一的类似 getValue 的 API

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/388
