### ISSUE TITLE
Responsive sider with special trigger should be floating when open

### ISSUE THREAD

**Issue by D0m3-** [ant-design/ant-design#21690]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When opening the collapsed Sider from the special trigger, it pushes the content to the side. 
When the Sider is collapsed it means there is no available space on the screen. 
So the Sider should open above the content.

My workaround is to change the position to absolute and add a z-index

### What does the proposed API look like?
No API change

**Comment by afc163** [comment]
You can try Drawer in this situation, like lAnt Design documentation menu in small screen.

**Comment by marian2js** [comment]
@afc163 I don't think that was the correct answer. Using a drawer for small screens and a sider for large ones means 2 different implementations. Ant Design Pro uses the proposed approach in this issue and the usability is great.

**Comment by Bassadin** [comment]
Is adding a conditional drawer still the only option here? Seems like the behavior described above should be the default one.
