### ISSUE TITLE
cannot override `autoInsertSpaceInButton` for Modal.method() dialogs

### ISSUE THREAD

**Issue by xmcp** [ant-design/ant-design#21692]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6v1uw?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Click on the "trigger" button to trigger a `Modal.confirm()` dialog

### What is expected?
The button in the dialog should look like "测试"

### What is actually happening?
it actually looks like "测 试"

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.12.0 |
| System | Windows NT 10.0; Win64; x64 |
| Browser | Chrome/80.0.3987.122 |

---
`<ConfigProvider autoInsertSpaceInButton={false}>` is the only way to disable auto space insertion for buttons.

However, this does not work for buttons in `Modal.method()` dialogs, making the behavior inconsistent.

**Comment by afc163** [comment]
https://ant.design/components/modal/#components-modal-demo-hooks

https://ant.design/components/modal/#Why-I-can-not-access-context,-redux-in-Modal.xxx

**Comment by nmsn** [comment]
https://codesandbox.io/s/wizardly-edison-2ijv0j?file=/src/App.js

The button in the dialog doesn`t look like "测试"

**Comment by yuyanan58** [comment]
I have the same problem. 

I check the code and find `ConfirmDialog` only pass `direction`, `rootPrefixCls` and `iconPrefixCls` to `ConfigProvider`, so `autoInsertSpaceInButton ` is  `undefined`.

![image](https://user-images.githubusercontent.com/18694564/182516943-f3913e42-f0c2-4267-a16c-51d76b59610b.png)

**Comment by xukaike** [comment]
use `        Modal.confirm({  
            okText: "测试",
        });`

**Comment by vin-mfvhn** [comment]
Can we re-open this issue.
I think we did not resolved it.

**Comment by jacksonplus** [comment]
你可以使用 `okText:` '确定 '` 这样的方式，也就是 文字后面加个 空格
