### ISSUE TITLE
This project has been added to the react-ui-roundup

### ISSUE THREAD

**Issue by dimitropoulos** [ant-design/ant-design#21696]
Hi!

I am making this issue just to let you know that I've included your amazing project in the [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup).

For more information see https://github.com/dimitropoulos/react-ui-roundup/issues/2.

Please feel free to close this issue at will - I just wanted to let you know :smile:.

Thanks!

**Comment by afc163** [comment]
Thx! @dimitropoulos I like your project.

Alrough we have dark mode, theme and rtl support.

<img width="903" alt="image" src="https://user-images.githubusercontent.com/507615/75601586-88658d00-5af7-11ea-8c4f-60b2e5202343.png">

**Comment by zombieJ** [comment]
Thanks @dimitropoulos. I'm glad to be included : )

**Comment by dimitropoulos** [comment]
And let me just take a quick moment to thank you for your hard work on this project.  I used AntD for a very complex project right after 3.0 came out and it was a real boon for productivity!  The only thing we had trouble with was that we wanted to do 100% css-in-js but some of the components required writing css selectors to target children for theming.  Aside from that, we had a fantastic experience with the huge variety of offered components!

I just want you to know how much I appreciate your efforts @afc163 @zombieJ et. al.

Thank you!

p.s. The christmas snow on the button thing wasn't _that_ bad.  Please keep the creative ideas coming!  Not every idea works out, but I appreciate your willingness to take risks while innovating.
