### ISSUE TITLE
Slider: Allow user to disable default hotkeys

### ISSUE THREAD

**Issue by Jianyi-Ren** [ant-design/ant-design#21695]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We'd like to add customized hotkeys, and find the slider default hotkey (ArrowUp, ArrowDown, ArrowLeft, ArrowLeft) interferes our mapping
There should be an option to disable the default hotkeys for slider

### What does the proposed API look like?
  disabledHotkey={true}

**Comment by wendellhu95** [comment]
I could implement this feature.

**Comment by afc163** [comment]
@hullis Any progress?

**Comment by hullis** [comment]
> @hullis Any progress?

Will do this on the weekend. ;-p
