### ISSUE TITLE
[4.0] Form Instance in Class Component

### ISSUE THREAD

**Issue by CarolineBoyer** [ant-design/ant-design#21693]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
None possible - just following Migration guide

### Steps to reproduce
As required per https://ant.design/components/form/v3/#Form-control,
```javascript
For class component, you can use ref to access instance:

// antd v4
class Demo extends React.Component {
  formRef = React.createRef();
```

So I did
```javascript
export class SettingsMasterbot extends React.Component<ISettingsMasterbotProps, ISettingsMasterbotState> {
    // formRef = Form.useForm()[0]; //even tried this... out of desperation
    formRef = React.createRef();

    constructor(props: ISettingsMasterbotProps) {
        super(props);
    }

    componentDidMount() {
        this.props.getMasterbotParameters(this.props.systemSettings.documentLanguage);
        this.formRef.getFieldValue('name'); //Throw Error SettingsMasterbot.tsx:98 Uncaught TypeError: this.formRef.getFieldValue is not a function
        this.formRef.setFieldsValue({ //Same here
            name: 'Test',
        });
    }

```

### What is expected?
I expected the migration guide to be true.... So I guess something is wrong here... 

### What is actually happening?
/Throw Error SettingsMasterbot.tsx:98 Uncaught TypeError: this.formRef.getFieldValue is not a function

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react 16 |
| System | Windows 10 |
| Browser | Chrome |

---
There is also a typescript error Property 'getFieldValue' doesn't exist on type `React.createRef<unknown>()`

Changing `formRef = React.createRef();` to `formRef = React.createRef<FormInstance>();` doesn't change anything.

------------
Other question related : 
I needed to set a dynamic field hidden, in a sub component where I pass the form as props.
It doesn't have a Form.Item associated.
`getFieldDecorator(`${this.props.formItemName}Keys`, {initialValue: []});`
`getFieldDecorator(`${this.props.formItemName}id`, {initialValue: -1});`

What is the good practice here ?

**Comment by zombieJ** [comment]
Thanks for feedback. That doc mistake. It should be: `this.formRef.current`.

Let me update the doc.

**Comment by Code-Crash** [comment]
Hi,

I tried to look where I can find the doc to use **`formRef`** into the **class component**, can anyone share any link for the same?


@CarolineBoyer  Any luck with the class component and **`formRef`**? I have to use the following functions:
```
formRef.setFieldsValue
formRef.getFieldsValue
```
Thanks

**Comment by Vin-1991** [comment]
Any luck on this issue? As i'm getting the same upon using the 
`formRef = React.createRef<FormInstance>();
this.formRef.current.setFieldsValue` -> `Property 'setFieldsValue' does not exist on type 'Form'.`
