### ISSUE TITLE
[4.0] 在 Form.Item 里使用自定义表单组件的时候 TS 会报类型错误

### ISSUE THREAD

**Issue by patrickmao93** [ant-design/ant-design#21709]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-2dqi5?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
见例子

### What is expected?
可能可以用 render function 来解决
```
<Form.Item>
    {(value, onChange) => <MyCustomInput value={value} onChange={onChange} />}
</Form.Item>
```

### What is actually happening?
IDE 无法得知<Form.Item>会给children 传入 value 和 onChange 的 props, 所以 TS 会报错. 目前的 workaround 我是把自定义组件的 FC<Props> 定义拿掉了.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8 |
| System | mac osx 10.15.3 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
```tsx
interface MyCustomInputProps {
  value: any;
  onChange: React.ChangeEventHandler<any>;
}

const MyCustomInput: React.FC<MyCustomInputProps> = (props) => {
  return <input placeholder="My Custom Input" value={props.value} onChange={props.onChange} />;
};
```
