### ISSUE TITLE
The value of hidden form item in formlist will not be verified but will be obtained.FormList内隐藏表单项的值不会被校验但会被获取

### ISSUE THREAD

**Issue by jjwong1991** [ant-design/ant-design#21701]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-formlist-reproduction-gd4y2)

### 单层Form

1. 外部选择【显示】
2. 在xxx中输入非法值123
3. 外部选择【隐藏】
4. 点击【提交】
5. 规则校验不会校验xxx字段的值，getFieldsValue()也不包含xxx字段的值，但是onFinish提交的值仍旧包含
```
{
  ...,
  xxx: "123",
}
```

方法 | 是否读取到隐藏表单项
---|---
getFieldsValue() | 否
getFieldsValue(true) | 是
onFinish() | 是

### FormList

1. 外部选择【隐藏】
2. 点击【 添加】增加一组FormList的子元素
3. 列表选择【显示】
4. 在列表xxx中输入非法值123
5. 列表选择【隐藏】
6. 点击【提交】
7. 规则校验不会校验列表xxx字段的值，但是getFieldsValue()和onFinish的值仍旧包含
```
{
  ...,
  list: [
    ...,
    xxx: "123",
  ],
}
```

方法 | 是否读取到FormList隐藏表单项
---|---
getFieldsValue() | 是
getFieldsValue(true) | 是
onFinish() | 是

### What is expected?
1.在onFinish方法添加参数，控制是否获取隐藏表单项的值，在不获取隐藏表单项的值时，可参考保持与validate时或getFieldsValue()一致的表现

2.在FormList内的表单项隐藏时，onFinish()或getFieldsValue()可以有方法不获取隐藏表单项的值，可参考保持与validate时一致的表现

### What is actually happening?
1.getFieldsValue()不传递true参数时，不会获取隐藏表单项的值，但是onFinish()无论如何都会获取隐藏表单项的值

2.FormList中隐藏表单项产生的数组类型的值的子元素，无论使用哪种取值方法，虽然不会被校验，都会被读取到

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.6 |
| React | 16.13.0 |
| System | Windows10 |
| Browser | Chrome80 |

---
在表单中，有很多通过表单字段控制其他字段显隐的需求，目前FormList中的隐藏字段不会被校验但是会被提交，提交不可控的表单项目的值会产生许多问题，如果都在onFinish中做过滤不太现实

**Comment by jjwong1991** [comment]
@zombieJ 感谢，我已更新复现demo的引用为rc-field-form@1.0.1。目前单层Form的onFinish可以得到正常的结果，但是Form.List中的隐藏表单项的值还是会被读取，问题依旧存在

**Comment by zombieJ** [comment]
@jjwong1991，能新开一个关于 Form.List 的 issue 吗？谢谢。

**Comment by jjwong1991** [comment]
> @jjwong1991，能新开一个关于 Form.List 的 issue 吗？谢谢。

@zombieJ 好的，已提交 #21713
