### ISSUE TITLE
[4.0.0] Form.Item input feedback position regression

### ISSUE THREAD

**Issue by crudo** [ant-design/ant-design#21717]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

Related to https://github.com/ant-design/ant-design/issues/18984

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ms6ty)

### Steps to reproduce
Look at the position of feedback in inputs

<img width="396" alt="Screenshot 2020-02-29 at 17 59 32" src="https://user-images.githubusercontent.com/67999/75611948-67189700-5b1f-11ea-8c28-c0b7965cc826.png">

### What is expected?
To behave the same way as in v3

<img width="367" alt="Screenshot 2020-02-29 at 17 59 17" src="https://user-images.githubusercontent.com/67999/75611955-6ed83b80-5b1f-11ea-8070-3a5ed2e6af2f.png">

### What is actually happening?
The Icon is not aligned in input when input has custom width.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | MacOS 10.15.3 |
| Browser | Google Chrome 80.0.3987.122 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
Hmmmm... not find good way to resolve this with flex layout...

**Comment by AshoneA** [comment]
@zombieJ 
How about this?
https://github.com/ant-design/ant-design/pull/21785

![image](https://user-images.githubusercontent.com/22393991/75678082-c4e7e300-5cc7-11ea-853a-100ea6b51a19.png)

**Comment by zombieJ** [comment]
close since not an issue in latest version: https://codesandbox.io/s/antd-reproduction-template-forked-jg9vqg?file=/package.json
