### ISSUE TITLE
@ant-design/icons not installed in Stackblitz

### ISSUE THREAD

**Issue by int64ago** [ant-design/ant-design#21718]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://zumdre.run.stackblitz.io](https://zumdre.run.stackblitz.io)

### Steps to reproduce
https://zumdre.run.stackblitz.io

### What is expected?
NULL

### What is actually happening?
NULL

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8 |
| System | Linux |
| Browser | Chrome |

![image](https://user-images.githubusercontent.com/2230882/75619372-fb353d80-5bb5-11ea-9d73-b6ebf923b889.png)

**Comment by afc163** [comment]
这个链接是从哪个 demo 里打开的？

**Comment by int64ago** [comment]
![image](https://user-images.githubusercontent.com/2230882/75620750-9e428300-5bc7-11ea-9797-be566d809218.png)

不过应该是通用问题

**Comment by afc163** [comment]
正则判断有问题，我改成 @ant-design/icons 始终有吧。
