### ISSUE TITLE
Select/TreeSelect suffixIcon prop is gone, but still available in docs

### ISSUE THREAD

**Issue by zzt1224** [ant-design/ant-design#21710]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
1. search for suffixIcon, still there,
2. Ts file suffixIcon is no longer there 

### What is expected?
still need suffixIcon to work

### What is actually happening?
is gone

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | MacOs Sierra 10.12.6 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Patch reproduce: https://codesandbox.io/s/react-typescript-6bdvj
