### ISSUE TITLE
ant-design 4.0 Icon图标显示问题？

### ISSUE THREAD

**Issue by benson-singapore** [ant-design/ant-design#21727]
简单说一下，项目中做菜单管理时，设置图标回显的时候，是根据数据库里存的字符串回显的。
3.x 的时候回显是   <Icon type="setting" /> 我只需要传一个 setting字符串就可以。
升级4.x 之后，需要引入
 import {SettingOutlined} from '@ant-design/icons';
 <SettingOutlined />

请问，有没有别的回显方式，怎么通过 “SettingOutlined” 去回显图标

**Comment by yoyo837** [comment]
#20668
