### ISSUE TITLE
Issue 4.0  Icon 问题

### ISSUE THREAD

**Issue by benson-singapore** [ant-design/ant-design#21729]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
简单说一下，项目中做菜单管理时，设置图标回显的时候，是根据数据库里存的字符串回显的。
3.x 的时候回显是 我只需要传一个 setting字符串就可以。
升级4.x 之后，需要引入
import {SettingOutlined} from '@ant-design/icons';
`<SettingOutlined />`
请问，有没有别的回显方式，怎么通过 “SettingOutlined” 去回显图标

### What does the proposed API look like?
我期望 ` <Icon type="SettingOutlined" />`

**Comment by yoyo837** [comment]
思路的问题，有类似的提问，一个笨办法，所有页面路由的icon是已知的，全部import，用数据结构整理起来，比如key map对象，从后台拿到key后去数据结构里换实际icon，否则必然出现全部引入导致3.0的svg过大的问题

**Comment by zhuguangyue** [comment]
兄弟，请问有没有找到解决方法了啊，我目前项目升级ant4也遇到同样的问题，感觉把所有的icon统一import这方案不太理想

**Comment by yoyo837** [comment]
没有，这就是最理想的

**Comment by yoyo837** [comment]
在3.x中，虽然你的代码里没有import icon，但实际antd import 了全部，不管你用不用到，导致bundle过大，而上面这种方法，虽然需要自己import全部但是仅限自己需要的全部，而不是整个icon列表的所有。

**Comment by zhuguangyue** [comment]
如何import自己需要的全部，在每个需要图片的路由页面都需要import，如何把他封装成一个全局的，兄弟有没有具体例子参考一下吗

**Comment by yoyo837** [comment]
```js
import {SettingOutlined, xxx} from '@ant-design/icons';

const map = {}

map['SettingOutlined'] = <SettingOutlined />
map['xxx'] = <xxx />
```

**Comment by Zerounary** [comment]
省事的，这样写：
```js
import * as icons from '@ant-design/icons';
let DynamicIcon = icons['FastBackwardOutlined'];
return (
  <DynamicIcon />
)
```
直接通过名称来动态选用

**Comment by carmel** [comment]
下面是vue3的例子（动态引入icon-import icon by name string）：
```vue
<template>
  <component
    :is="name"
    :style="style"
    :class="className"
  />
</template>

<script>
import { defineComponent } from 'vue'
import {
  AntDesignOutlined,
  UserOutlined,
  PoweroffOutlined,
  InfoCircleOutlined,
  SafetyCertificateOutlined,
  FolderOutlined,
  MenuUnfoldOutlined,
  MenuFoldOutlined
} from '@ant-design/icons-vue'

export default defineComponent({
  name: 'DynamicIcon',
  components: {
    AntDesignOutlined,
    UserOutlined,
    PoweroffOutlined,
    InfoCircleOutlined,
    SafetyCertificateOutlined,
    FolderOutlined,
    MenuUnfoldOutlined,
    MenuFoldOutlined
  },
  props: {
    name: {
      type: String,
      default: 'AntDesignOutlined'
    },
    className: {
      type: String,
      default: ''
    },
    style: {
      type: Object,
      default: () => {}
    }
  }
})
</script>

```
