### ISSUE TITLE
4.0的select能否支持选择是否开启虚拟化滚动，不启用时采用3.x的渲染方式

### ISSUE THREAD

**Issue by sunyum** [ant-design/ant-design#21722]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
3.x升级4.0后，可能由于默认支持虚拟化滚动，4.0的 select 不能很好的定制 item 的样式
比如，要做一个 IconSelect , 让 item横向排列，但是由于支持了虚拟化，没办法灵活修改item的宽高，布局等。
![image](https://user-images.githubusercontent.com/20025971/75623863-8aa81400-5be9-11ea-85dc-e4b3f9a70675.png)
如图，每个item是一个图标，让图标横向排列，会导致滚动问题
![image](https://user-images.githubusercontent.com/20025971/75623886-da86db00-5be9-11ea-83ab-cf0f3e242590.png)

### What does the proposed API look like?
IsVirtualList

**Comment by yoyo837** [comment]
虚拟化为什么不能修改宽高？

**Comment by sunyum** [comment]
> 虚拟化为什么不能修改宽高？

可以修改宽高，但是如何定制 item 的排列布局？

**Comment by zombieJ** [comment]
有具体案例不，没明白为什么 option 要横向排列。那剩下的空间是放什么的。

**Comment by yoyo837** [comment]
设计师的稿子拿来看看 😄

**Comment by sunyum** [comment]
> 设计师的稿子拿来看看 😄
这是3.X实现的
![image](https://user-images.githubusercontent.com/20025971/75649508-44f15700-5c8e-11ea-9495-d1040b463988.png)

**Comment by zombieJ** [comment]
Get 了。可以用 `dropdownRender` 把原生的虚拟滚动组件替换掉。options 可以从原来的组件里取出来：https://codesandbox.io/s/fervent-kalam-9bnry

**Comment by zombieJ** [comment]
Reopen for #21754

**Comment by MrSuperLi** [comment]
> Get 了。可以用 `dropdownRender` 把原生的虚拟滚动组件替换掉。options 可以从原来的组件里取出来：https://codesandbox.io/s/fervent-kalam-9bnry
你好，我也遇到这样的需求。
你上面的例子还是使用虚拟滚动的，只是选项不够多。
