### ISSUE TITLE
Custom field validator is not triggering with dependencies

### ISSUE THREAD

**Issue by syamfullstack** [ant-design/ant-design#21738]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/syamfullstack/antd-form-field-dependencies-issue](https://github.com/syamfullstack/antd-form-field-dependencies-issue)

### Steps to reproduce
1. Change Password as "Syam"
2. Change confirm password as "Syam1", it will throw an error like "The two passwords that you entered do not match!"
3. Change password to "Syam1"
4. It won't trigger the form validator

### What is expected?
I have two dependant textboxes, whenever a change occurs in the first form field(password) should trigger the custom validator in the second one(confirm) and should clear the error if it is valid.
In the second form field, I have added the first form filed as dependencies

### What is actually happening?
It's not triggering the custom validator

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.3 |
| React | 16.12.0 |
| System | Mac |
| Browser | Chrome |

---

**Comment by vibhanshuc** [comment]
@syamfullstack  Any particular reason you are using arrays for form item's name: https://github.com/syamfullstack/antd-form-field-dependencies-issue/blob/master/src/App.js#L31

It seems to work fine for string names https://codesandbox.io/s/festive-northcutt-2f1ux

**Comment by syamfullstack** [comment]
> @syamfullstack Any particular reason you are using arrays for form item's name: https://github.com/syamfullstack/antd-form-field-dependencies-issue/blob/master/src/App.js#L31
> 
> It seems to work fine for string names https://codesandbox.io/s/festive-northcutt-2f1ux

**Comment by syamfullstack** [comment]
Its works fine with string names, but it doesn't work with nested form fields
for example

         {
                address: {
                       city: 'abc',
                       state: 'qwerty'
                       country: 'India',
                },
                amount: '100'
           }

Based on the county value, I want to validate the amount. If the country is 'India', the amount should be less than or equals to 100, greater than for any other country.

How can I write a custom validator function for the above scenario?

**Comment by zombieJ** [comment]
```diff
- dependencies={['security', 'password']}
+ dependencies={[['security', 'password']]}
```

**Comment by syamfullstack** [comment]
Thank you, its working fine
