### ISSUE TITLE
使用grid栅格布局时，Row组件中不显式指定align属性展现的效果与默认值top的展现效果不一致

### ISSUE THREAD

**Issue by TeibbyZhang** [ant-design/ant-design#21737]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-ob4yj?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1.使用两个Row组件，分别指定align属性为top和不指定align属性；
2.在Row组件下分别使用两个或两个的Col组件，并设置背景色展示Col组件高度；
3.在每个Col组件下设置高度综合不同的元素若干

### What is expected?
当未显式指定align属性时，展示效果与显示指定该属性的效果一致

### What is actually happening?
新增参数以区分两者或者在未设置align属性时隐式添加属性值为top

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react |
| System | win10 |
| Browser | chrome 80.0 |

**Comment by shaodahong** [comment]
codeSandbox 有缓存，你这个例子还是 3.x 版本，换到 4.0 就好了

**Comment by afc163** [comment]
https://codesandbox.io/embed/antd-reproduction-template-ob4yj?fontsize=14&hidenavigation=1&theme=dark
