### ISSUE TITLE
RC Field Form prevents compiling when upgrading from v3 to v4

### ISSUE THREAD

**Issue by specialorange** [ant-design/ant-design#21731]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.idonthaveone.com](http://www.idonthaveone.com)

### Steps to reproduce
./node_modules/antd/es/config-provider/index.js
Module not found: Can't resolve 'rc-field-form' in '/Users/username/dev/server/frontend/node_modules/antd/es/config-provider'

### What is expected?
it should compile

### What is actually happening?
it is not compiling, even with trying to upgrade the node module directly

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.12 |
| System | osx |
| Browser | all |

**Comment by zombieJ** [comment]
Clean up your `node_modules` and reinstall.
