### ISSUE TITLE
V4  message.open not working

### ISSUE THREAD

**Issue by arashkay** [ant-design/ant-design#21745]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-httzae?file=index.js](https://stackblitz.com/edit/react-httzae?file=index.js)

### Steps to reproduce
Press the "Display message" button to see the error. Or simply call
`message.open({ content: 'This is a normal message'})`

### What is expected?
Open the message toast similar to v3 or message.success({ content: 'This is a normal message'}).

### What is actually happening?
Error in /turbo_modules/react-dom@16.13.0/cjs/react-dom.development.js (23999:21)
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | Mac Catalina 10.15.2 |
| Browser | chrome Version 80.0.3987.122  |

---
All other methods are working fine, just "message.open" is not working.

**Comment by AshoneA** [comment]
You can try `message.open({ content: 'This is a normal message', icon: ' '});`, i will fix it in morning.

**Comment by yoyo837** [comment]
> You can try `message.open({ content: 'This is a normal message', icon: ' '});`, i will fix it .

No, `open` must provide `type`

**Comment by yoyo837** [comment]
Close by #21747
