### ISSUE TITLE
DestroyOnClose is not working

### ISSUE THREAD

**Issue by Elliottssu** [ant-design/ant-design#21740]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-stonebraker-cz5tf)

### Steps to reproduce
官网上的一个弹框 form的例子，加了一个 destroyOnClose

### What is expected?
输入内容后，点击取消，下次再打开，内容清空

### What is actually happening?
输入内容后，点击取消，下次再打开，内容没有清空

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | macOS |
| Browser | chrome 80.0.3987.122 |

**Comment by afc163** [comment]
form 的状态是在 useForm 里面的，自然不会跟着 Modal 一起被销毁，这个和 useState 是一样的道理。

**Comment by BugHiding** [comment]
@afc163 `destroyOnClose` 的描述是`关闭时销毁 Modal 里的子元素`,我们的心理预期是可以直接销毁`form` 包括 `useForm` 里的数据。但是实际和我们的预期就有了一点冲突，虽然我们可以通过`resetFields` 去做。所以这里是不是有一点小小的问题。

**Comment by Kermit-Xuan** [comment]
`destroyOnClose` 只是 `Modal` 的API，所以只会处理 `Modal` 相关的逻辑，和表单的逻辑是解耦的，两者没有关系。

`destroyOnClose` is only the API of `Modal`, so it will only deal with the logic related to `Modal`, and it is decoupled from the logic of the form, there is no relationship between the two.

**Comment by afc163** [comment]
@BugHiding 类比 `useState` 就很好理解。

```
const [value, setValue] = useState('');

return (
  <Modal destroyOnClose>
    <input value={value} />
  </Modal>
);
```

Modal 关闭时会销毁 input 节点，但是 `useState` 的 `value` 不会被销毁。

**Comment by BugHiding** [comment]
@afc163 嗯，非常感谢清晰的解释。实现确实如您所说，应该是我的理解上产生了偏差所以会提出这样的问题。我觉得应该还会有类似这样的问题被提出。

**Comment by xcgs123** [comment]
但为什么有时候是可以清空内容，有时候会缓存内容，感觉有个同步的问题

**Comment by xgj1988** [comment]
@afc163  我知道可以通过form的resetValues来处理，，但是我觉得这种语义上面给人比较混乱的感觉。。还是以前那种感觉比较切合实际 @BugHiding 你说对了，还有人提这个问题。

**Comment by afc163** [comment]
有希望在 https://github.com/ant-design/ant-design/issues/24729#issuecomment-646490076 里解决。

**Comment by DarwinniwraD** [comment]
it's working for the components declared with class

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/25186

**Comment by afc163** [comment]
4.5.0 之后，可以给 Form 加上 `preserve={false}` 属性来清除跟随 Modal 销毁的字段数据：https://codesandbox.io/s/mystifying-sound-lkin8

**Comment by alexkaduk** [comment]
Still, modal `destroyOnClose` does not work (((
