### ISSUE TITLE
TreeNodeNormal interface should have icon property

### ISSUE THREAD

**Issue by gavinxgu** [ant-design/ant-design#21742]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/treenodenormal-interface-should-have-icon-property?embed=1&file=index.tsx](https://stackblitz.com/edit/treenodenormal-interface-should-have-icon-property?embed=1&file=index.tsx)

### Steps to reproduce
Just happened.

### What is expected?
TreeNodeNormal interface should have icon property

### What is actually happening?
Icon prop in treeData item is mentioned in antd document, and it indeed works in js. But the typescript interface has no icon prop.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | MacOS |
| Browser | Chrome 80.0.3987.122 |

**Comment by PaulPCIO** [comment]
Agree
