### ISSUE TITLE
4.0 正式版 渲染 Result 组件必定导致页面 Crash

### ISSUE THREAD

**Issue by whinc** [ant-design/ant-design#21741]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

按照官网示例使用`<Result>`组件会导致页面 Crash，在 4.0.0 RC 5 版本中未出现该问题，升级到 4.0.0 正式版后出现该问题。

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-ardinghelli-pnrq0)

### Steps to reproduce
按照官网示例使用`<Result>`组件，demo 代码：
```tsx
function App() {
  return (
    <div className="App">
      <Result
        status={404}
        title="404"
        subTitle="Sorry, the page you visited does not exist."
        extra={<Button type="primary">Back Home</Button>}
      />
    </div>
  );
}

render(<App />, rootElement);
```

### What is expected?
正确渲染，不 Crash

### What is actually happening?

页面 Crash，报错如下：
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Context.Consumer`.
```

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | macOS 10.12.6 |
| Browser | Chrome 80 |

---

**Comment by blackraindrop** [comment]
这个是类型定义的问题，status=“404” 就不会报错了

**Comment by whinc** [comment]
> 这个是类型定义的问题，status=“404” 就不会报错了

不是这个问题原因

**Comment by whinc** [comment]
> 这个是类型定义的问题，status=“404” 就不会报错了

按照你说的修改后就好了，谢谢。

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/21691
