### ISSUE TITLE
官网点击无反应

### ISSUE THREAD

**Issue by omgEn** [ant-design/ant-design#21746]
v4 更新后 官网代码复制不了，所有的点击按钮都无效。

**Comment by yoyo837** [comment]
缓存吧？刷新一下

**Comment by omgEn** [comment]
清过缓存，无效。这两天一直都是这样子。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 上午10:05
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "1127263614"<1127263614@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 官网点击无反应 (#21746)




缓存吧？刷新一下

**Comment by yoyo837** [comment]
没遇到过，页面加载完成没？

**Comment by omgEn** [comment]
完成了，但是加载用了几分钟。
下面这些按钮都是点了没有反应。








------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 上午10:20
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "1127263614"<1127263614@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 官网点击无反应 (#21746)




没遇到过，页面加载完成没？

**Comment by yoyo837** [comment]
你试试 https://ant-design.gitee.io/

**Comment by yoyo837** [comment]
应该是没完成，浏览器请求某些资源超时了。你用国内站点 https://ant-design.gitee.io/

**Comment by omgEn** [comment]
完美解决。谢谢你。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;; 
发送时间: 2020年3月2日(星期一) 上午10:28
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "1127263614"<1127263614@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 官网点击无反应 (#21746)




应该是没完成，浏览器请求某些资源超时了。你用国内站点 https://ant-design.gitee.io/
