### ISSUE TITLE
[4.0.0] Form.Item key string is not translated to path (regression)

### ISSUE THREAD

**Issue by crudo** [ant-design/ant-design#21743]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-wildflower-9wrmw)

### Steps to reproduce
Click _Fill form_, then _Submit_ and look at the _result_.

### What is expected?
If item key is path (eg. 'az[0][name]', I get array in the form value in Ant v3.

```json
{
  "note": "Hello world!",
  "az": [
    {
      "name": "az-o-name"
    }
  ]
}
```

### What is actually happening?
If item key is path (eg. 'az[0][name]', I get string in the form value in Ant v4.

```json
{
  "note": "Hello world!",
  "az[0][name]": "az-0-name"
}
```

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | MacOS 10.15.3 |
| Browser | Google Chrome 80.0.3987.122 (Official Build) (64-bit) |

---
Compare with Antd v3 version here https://codesandbox.io/s/eager-morning-fxe8g

**Comment by afc163** [comment]
https://ant.design/docs/react/migration-v4

<img width="828" alt="image" src="https://user-images.githubusercontent.com/507615/75642656-33e91b80-5c77-11ea-9dc3-f47df0ce5522.png">

**Comment by crudo** [comment]
Thanks @afc163

Sorry, I did not know I was dealing with nested definition.
I believe It requires a better documentation. 
Will try to create PR.
