### ISSUE TITLE
Input.Search 支持 prefix 和 addonAfter

### ISSUE THREAD

**Issue by faremax** [ant-design/ant-design#21749]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
对于定制化的设计需求，希望可以支持 Input.Search 支持 prefix 和 addonAfter。

### What does the proposed API look like?
API 不变，将 Input.Search 现有的 prefix 和 addonAfter 属性值作为可以被覆盖的默认值即可

**Comment by yoyo837** [comment]
Input.Search 好像是特例封装，看看AutoComplate 和 Select 能否满足你的要求？

**Comment by faremax** [comment]
> Input.Search 好像是特例封装，看看AutoComplate 和 Select 能否满足你的要求？

单纯满足功能甚至 Input 本身也可以，我遇到的是个强设计需求，考虑 antd 能不能支持这样的改动，根本解决这个问题

**Comment by afc163** [comment]
现在的效果是这样的。

https://codesandbox.io/s/exciting-cache-hvipk

<img width="660" alt="image" src="https://user-images.githubusercontent.com/507615/75642042-1dda5b80-5c75-11ea-9414-23ef6f4ada57.png">

你希望实现什么样的效果？

**Comment by faremax** [comment]
> 你希望实现什么样的效果？
很抱歉，是我写错了，我想说的是 suffix 后缀，替换那个搜索图标。希望这个作为默认值提供。

**Comment by faremax** [comment]
> 现在的效果是这样的。
> 
> https://codesandbox.io/s/exciting-cache-hvipk
> 
> <img alt="image" width="660" src="https://user-images.githubusercontent.com/507615/75642042-1dda5b80-5c75-11ea-9414-23ef6f4ada57.png">
> 
> 你希望实现什么样的效果？

很抱歉，是我写错了，希望 suffix 后缀可以作为默认值提供，替换那个搜索图标。

**Comment by faremax** [comment]
示例如下：
https://codesandbox.io/s/morning-currying-e96tx

**Comment by afc163** [comment]
Input.Search 就是默认含有了 suffix 和 addonAfter 的 Input 语法糖，确实直接替换成 Input 就可以了。

```
    <Input
      placeholder="input search text"
      style={{ width: 200 }}
      suffix="newIcon"
    />
```

暂时看不到这个需求的必要性。而且如果 suffix 可以被替换成任意 Icon，Search 的搜索语义可能就不存在了。
