### ISSUE TITLE
升级 rc-form 到 0.17，支持 getFieldProps('xx.yy') 的写法

### ISSUE THREAD

**Issue by xuydn** [ant-design/ant-design#2175]
<Input {...getFieldProps("data.province", {initialValue: 'ppppp'})}/>
          <Input {...getFieldProps("data,city", {initialValue: 'cccccc'})}/>

使用this.props.form.getFieldsValue() 返回的是对象

```
{ 
  "data.province":"ppppp",
  "data,city":"ccccc"
}
```

并非预期的
```
{
   data:{
    province:"ppppp",
    city:"ccccc",
   }
}
```

之前的项目需要提交Json数据，实现过支持解析 getFieldProps('xx.yy') 的函数magic
magic(getFieldsValue()) ，能达到上面的预期结果
代码
[magic.html.zip](https://github.com/ant-design/ant-design/files/333190/magic.html.zip)

希望ant-design能支持这种情况，thanks

**Comment by yiminghe** [comment]
不支持的，这个只对 checkbox 做支持，请自行处理后再提交数据

**Comment by afc163** [comment]
http://codepen.io/anon/pen/dXvNGY?editors=001

我试了一下是支持的，你升级 antd 了么？

**Comment by xuydn** [comment]
给出的链接试了下确实可以哈，我本地升级的了，好奇怪
