### ISSUE TITLE
4.0选择器 下拉菜单与选择器同宽dropdownMatchSelectWidth设置false不生效。

### ISSUE THREAD

**Issue by haolic** [ant-design/ant-design#21754]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-efdcqd?file=index.js](https://stackblitz.com/edit/react-efdcqd?file=index.js)

### Steps to reproduce
设置了宽度，然后设置dropdownMatchSelectWidth为false，然后其中一个option字数改为很多，下拉框里的宽度还是和选择器一致。

### What is expected?
设置dropdownMatchSelectWidth为false后下拉框为适应子元素宽度。

### What is actually happening?
设置dropdownMatchSelectWidth为false后下拉框与选择器还是同宽的。

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react 16.13.0 |
| System | macOS 10.15.3  |
| Browser | 80.0.3987.122 |

**Comment by zombieJ** [comment]
> `dropdownMatchSelectWidth` 不再自动适应内容宽度，请用数字设置下拉宽度。

https://ant.design/docs/react/migration-v4-cn#%E7%BB%84%E4%BB%B6%E9%87%8D%E6%9E%84

**Comment by haolic** [comment]
> > `dropdownMatchSelectWidth` 不再自动适应内容宽度，请用数字设置下拉宽度。
> 
> https://ant.design/docs/react/migration-v4-cn#%E7%BB%84%E4%BB%B6%E9%87%8D%E6%9E%84

那实现同样的功能如何操作一波？

**Comment by harunurhan** [comment]
This was a nice feature which was removed, it's even used by you, in the some examples which are also broken, for instance the position select in https://ant.design/components/tabs/#components-tabs-demo-position


@zombieJ

**Comment by zombieJ** [comment]
Another also talk about this. We can consider to provide the ability to close virtual scroll to let the `dropdownMatchSelectWidth` back.

ref: #21722
