### ISSUE TITLE
下拉组件(Select) 右侧的下拉箭头，建议将尖下巴，改成宽下巴。

### ISSUE THREAD

**Issue by maorui2014** [ant-design/ant-design#21757]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
它看起来非一般性的“尖”，影响美观度，两条边之间的夹角应该更大一些，高度矮一些，建议参考一下 element 或其他更多组件。

### What does the proposed API look like?
无

**Comment by zombieJ** [comment]
It's by design. You can use `suffixIcon` to replace the icon.

**Comment by AntDesigners** [comment]
这个是整体全套图标考虑的，官网上有我们的相关文章[https://ant.design/docs/spec/icon-cn](url)
如果你项目中需要替换，建议先用 @zombieJ 的方式
