### ISSUE TITLE
v4 table的locale无用

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design#21760]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-fruse)

### Steps to reproduce
直接看

### What is expected?
显示中文

### What is actually happening?
还是英文

| Environment | Info |
|---|---|
| antd | undefined |
| React | ^16.8.6 |
| System | macOS |
| Browser | chrom最新 |

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/75654431-afa88f80-5c9a-11ea-9ffb-9609ac0c57ae.png)

啥问题？

**Comment by afc163** [comment]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/507615/75654541-e9799600-5c9a-11ea-9ea4-d009e384e31f.png">

确实有问题，codesandbox 这个缓存还在。

**Comment by zombieJ** [comment]
嗯，漏了。
