### ISSUE TITLE
bug: dropdown menu width style 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#21767]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/dropdown-cn/#components-dropdown-demo-sub-menu](https://ant.design/components/dropdown-cn/#components-dropdown-demo-sub-menu)

### Steps to reproduce
- 打开链接
- 点击多级菜单
- 观察最后一项

### What is expected?
- 文字和图标 位置 恰当

### What is actually happening?
- 文字和图标 有重叠

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | The latest |
| System | mac |
| Browser | chrome |

---
https://github.com/ant-design/ant-design/blob/27e48d325759f6a79151c5c8628b3ed023a3ddab/components/dropdown/style/index.less#L206

- 留给图标的总位置为 26px

https://github.com/ant-design/ant-design/blob/27e48d325759f6a79151c5c8628b3ed023a3ddab/components/dropdown/style/index.less#L121
- 图标大小加上 margin-right右边 8px，总为 20 px

https://github.com/ant-design/ant-design/blob/27e48d325759f6a79151c5c8628b3ed023a3ddab/components/dropdown/style/index.less#L184

- 图标位置 right 8px  (@padding-xs  这个 是 8px)
--- 
总的是 28px  大于  26px  ，所以会有 2px 的重叠

**Comment by yoyo837** [comment]
那也应该改成6吧？

**Comment by xrkffgg** [comment]
这就看 你们想 让文字和 图标 中间间隔有多少了，如果是 6px ，那 right 为 0

**Comment by yoyo837** [comment]
那还是加大`padding-right`.

**Comment by xrkffgg** [comment]
那图标 距离 right 有 16 px 会不会 太多了。。。

你认为 后缀图标 和文字 间隔 应该多少 px 合适？

**Comment by yoyo837** [comment]
其实应该和图标 与 右边一致，对称吧

**Comment by yoyo837** [comment]
至于图标内容在图标上布局中 就是图标的问题

**Comment by xrkffgg** [comment]
左侧 使用 icon 的 样式为

距离边距 5px

距离 文字内容  8px  

那我按照这个改？
