### ISSUE TITLE
Table 无法进行固定列，指定 column 的 width 属性，没有作用

### ISSUE THREAD

**Issue by zuizuihao** [ant-design/ant-design#2176]
使用方法如下：
```
const columns = [
  {
    title: '发货人',
    dataIndex: 'realName',
    width: 100,
  }, {
    title: '发货地',
    dataIndex: 'origin',
    width: 100,
  }, {
    title: '收货地',
    dataIndex: 'destination',
    width: 100,
  }, {
    title: '车辆描述',
    dataIndex: 'vehicleDescription',
    width: 200,
  }, {
    title: '状态',
    dataIndex: 'statusName',
    width: 50,
  }, {
    title: '定金（元）',
    dataIndex: 'frstPartMoney',
    width: 50,
  }, {
    title: '参考价格（元）',
    dataIndex: 'referencePrice',
    width: 50,
  }, {
    title: '实际价格（元）',
    dataIndex: 'realTotalPrice',
    width: 50,
  }]
<Table
        columns={columns}
        dataSource={list}
        className="table"
        pagination={pagination}
        onRowClick={this.onRowClick} />
```
渲染结果如下：
`<table class=""><colgroup><col style="width: 100px; min-width: 100px;"><col style="width: 100px; min-width: 100px;"><col style="width: 100px; min-width: 100px;"><col style="width: 200px; min-width: 200px;"><col style="width: 50px; min-width: 50px;"><col style="width: 50px; min-width: 50px;"><col style="width: 50px; min-width: 50px;"><col style="width: 50px; min-width: 50px;"></colgroup><thead class="ant-table-thead"><tr><th class=""><span><!-- react-text: 106 -->发货人<!-- /react-text --></span></th><th class=""><span><!-- react-text: 109 -->发货地<!-- /react-text --></span></th><th class=""><span><!-- react-text: 112 -->收货地<!-- /react-text --></span></th><th class=""><span><!-- react-text: 115 -->车辆描述<!-- /react-text --></span></th><th class=""><span><!-- react-text: 118 -->状态<!-- /react-text --></span></th><th class=""><span><!-- react-text: 121 -->定金（元）<!-- /react-text --></span></th><th class=""><span><!-- react-text: 124 -->参考价格（元）<!-- /react-text --></span></th><th class=""><span><!-- react-text: 127 -->实际价格（元）<!-- /react-text --></span></th></tr></thead><tbody class="ant-table-tbody"></tbody></table>`

但是没有按照规则渲染出想要的结果，chrome和safari都不行。

**Comment by dyf2015** [comment]
遇到同样问题

发自我的 iPhone

在 2016年6月26日，15:33，zuizuihao <notifications@github.com<mailto:notifications@github.com>> 写道：


使用方法如下：
const columns = [
{
title: '发货人',
dataIndex: 'realName',
width: 100,
}, {
title: '发货地',
dataIndex: 'origin',
width: 100,
}, {
title: '收货地',
dataIndex: 'destination',
width: 100,
}, {
title: '车辆描述',
dataIndex: 'vehicleDescription',
width: 200,
}, {
title: '状态',
dataIndex: 'statusName',
width: 50,
}, {
title: '定金（元）',
dataIndex: 'frstPartMoney',
width: 50,
}, {
title: '参考价格（元）',
dataIndex: 'referencePrice',
width: 50,
}, {
title: '实际价格（元）',
dataIndex: 'realTotalPrice',
width: 50,
}]

columns={columns}
dataSource={list}
className="table"
pagination={pagination}
onRowClick={this.onRowClick} />
渲染结果如下：

发货人     发货地     收货地     车辆描述    状态      定金（元）   参考价格（元） 实际价格（元）

但是没有按照规则渲染出想要的结果，chrome和safari都不行。

―

**Comment by zuizuihao** [comment]
原因已经找到，.ant-table-fixed-left td,.ant-table-fixed-left th,.ant-table-fixed-right td,.ant-table-fixed-right th,.ant-table-scroll td,.ant-table-scroll th{white-space:nowrap}.，样式中没有自动换行，建议改成white-space: normal。

**Comment by zuizuihao** [comment]
更新 https://npmcdn.com/antd/dist/antd.css 之后，问题解决了。
