### ISSUE TITLE
新设计阴影效果

### ISSUE THREAD

**Issue by jinan5694** [ant-design/ant-design#21775]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
新增的阴影设计无法清晰表达元素的高度。

### What does the proposed API look like?
加深二级和三级阴影的深度。
![image](https://user-images.githubusercontent.com/3690120/75662571-4761aa00-5caa-11ea-87b5-c8f421dbd985.png)

![image](https://user-images.githubusercontent.com/3690120/75662429-0cf80d00-5caa-11ea-9b96-b6e794e03480.png)

**Comment by AntDesigners** [comment]
这个问题我们会关注，后续有调整会及时同步出来

**Comment by yingxirz** [comment]
这个问题已经在考虑中了，准备将阴影和色板关联起来，以后阴影就可以不只是黑色啦（自然里可没有纯黑色的阴影）；
另外你说的对，我们还少了一个 2dp 的高度，这块我还没想好算法。
