### ISSUE TITLE
DatePicker in Popover

### ISSUE THREAD

**Issue by la99er** [ant-design/ant-design#21778]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-q8ouw?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
* Click on the Button
* Set a Date in the DatePicker.
* Clear the DatePicker

### What is expected?
The DatePicker should be cleared and the popover should still be open.

### What is actually happening?
The DatePicker is getting cleared, but the popover does close itself.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | Arch Linux |
| Browser | Firefox 73.0 (64-bit) & Chrome 80.0.3987.106 |

---
This issue seems to be related, but was closed: https://github.com/ant-design/ant-design/issues/20649  
Thus I was not sure if creating a new ticket is the right way to report this issue. I hope the way I did it is okay!  
Many thanks in advance!

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-disappears-when-I-click-another-popup-component-inside-it.-How-do-I-resolve-this

**Comment by la99er** [comment]
That does not solve my problem. The popover still closes itself when I clear the date time. If it is an easy fix, could you please adjust my example, so that the popover does not close itself by clearing the date?

**Comment by la99er** [comment]
My issue is fixed in v4.0.2 
Thanks for your support! :)

**Comment by wangcherry** [comment]
> My issue is fixed in v4.0.2
> Thanks for your support! :)

antd v4.0.4

![image](https://user-images.githubusercontent.com/11580793/77728941-84665580-7038-11ea-92b7-1b803af96ad9.png)

**Comment by wangcherry** [comment]
> My issue is fixed in v4.0.2
> Thanks for your support! :)

antd v4.0.4
select是可以生效的，但是RangePicker不生效

![image](https://user-images.githubusercontent.com/11580793/77729086-cbece180-7038-11ea-93ee-703cec42dcb6.png)
![image](https://user-images.githubusercontent.com/11580793/77729116-dc04c100-7038-11ea-868d-40a3a7393a41.png)

**Comment by dpyzo0o** [comment]
> > My issue is fixed in v4.0.2
> > Thanks for your support! :)
> 
> antd v4.0.4
> select是可以生效的，但是RangePicker不生效
> 
> ![image](https://user-images.githubusercontent.com/11580793/77729086-cbece180-7038-11ea-93ee-703cec42dcb6.png)
> ![image](https://user-images.githubusercontent.com/11580793/77729116-dc04c100-7038-11ea-868d-40a3a7393a41.png)

同样的问题，select 生效，rangepicker不生效

**Comment by 07akioni** [comment]
没理解，能贴个复现链接么？

**Comment by kennylbj** [comment]
```getPopupContainer={(trigger: any) => trigger.parentNode}```  用TimePicker时也不生效

**Comment by br-matt** [comment]
> `getPopupContainer={(trigger: any) => trigger.parentNode}` 用TimePicker时也不生效，必须要将Popover设置为trigger="click"才行

Bless you, don't know why this isnt in the docs

**Comment by lehaiquantb** [comment]
> `getPopupContainer={(trigger: any) => trigger.parentNode}` 用TimePicker时也不生效，必须要将Popover设置为trigger="click"才行

this should be in docs
