### ISSUE TITLE
v4 Dropdown的overlayStyle无用【v3是OK的】

### ISSUE THREAD

**Issue by rendongsc** [ant-design/ant-design#21770]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6w0zp)

### Steps to reproduce
检查页面元素查看。

### What is expected?
z-index: 1001;

### What is actually happening?
z-index: 1050;

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | ^16.8.6 |
| System | macOS |
| Browser | chrom最新 |

---
通过Dropdown封装的组件里还有弹窗，需要更改z轴大小，v3都是正常的，升级到v4出现这个问题。

**Comment by afc163** [comment]
reproduce: https://codesandbox.io/s/antd-reproduction-template-tc9e9
