### ISSUE TITLE
4.0官方文档form表单实例validator 返回错误使用Promise.reject("错误")，没有遵循eslint/prefer-promise-reject-errors

### ISSUE THREAD

**Issue by exvu** [ant-design/ant-design#21779]
4.0官方文档form表单实例validator 返回错误使用Promise.reject("错误")，没有遵循eslint/prefer-promise-reject-errors
此建议不是钻牛角尖，只是希望antd更规范的举例。同时感谢antd团队为我们提供开源项目。

**Comment by yoyo837** [comment]
我还打算让它支持这个 https://github.com/react-component/field-form/pull/88 😂

**Comment by afc163** [comment]
@exvu 来个 PR
