### ISSUE TITLE
antd4 一个数据更新不同步的问题

### ISSUE THREAD

**Issue by beMySun** [ant-design/ant-design#21786]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/scaukk/pen/ZEGyVWr?editors=0011](https://codepen.io/scaukk/pen/ZEGyVWr?editors=0011)

### Steps to reproduce
点击查看， 然后换一条再点击查看， 发现数据没有更新。

### What is expected?
数据更新

### What is actually happening?
数据没更新

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | macOS 10.14.4 |
| Browser | Chrome 79.0.3945.130 |

**Comment by beMySun** [comment]
![Kapture 2020-03-02 at 21 01 50](https://user-images.githubusercontent.com/12824205/75678696-2c526280-5cc9-11ea-8fb2-568b9f042974.gif)

**Comment by beMySun** [comment]
第一次点击Jim,  显示的是JIm

 第二次点击的是Joe, 显示的还是Jim

**Comment by LuckyWinty** [comment]
+1，我也遇到了这个问题，顶上去

**Comment by beMySun** [comment]
点击提交的一瞬间， 好像更新了，闪了一下。

**Comment by afc163** [comment]
resetFields 是重置回 initialValues 的值，并且 initialValues 只用于第一次初始化，不响应后续的变化，你需要转换一下思路：https://codepen.io/afc163-1472555193/pen/LYVjNWN?editors=0011

**Comment by syaivin** [comment]
> resetFields 是重置回 initialValues 的值，并且 initialValues 只用于第一次初始化，不响应后续的变化，你需要转换一下思路：https://codepen.io/afc163-1472555193/pen/LYVjNWN?editors=0011

@afc163 看你这例子弹框放在一个文件里，我的是单独用一个 js 文件引用的，form 要怎么拿，请教

**Comment by qihui1223** [comment]
`    {visible ? (
        <MyModal
          record={record}
          visible={visible}
          onOK={() => {
            setRecord({})
            setVisible(false)
          }}
        />
      ) : null}`

我也碰见了类似问题,找了一下午,记录一下,在modal没有点开时候不要挂载上去,否则始终会出现数据不更新的情况
