### ISSUE TITLE
Table defaultExpandAllRows doesn't always expand all rows

### ISSUE THREAD

**Issue by andykent** [ant-design/ant-design#21788]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-uy7qn)

### Steps to reproduce
- Create a table
- set `childrenColumnName` to something other than the default value
- set `expandable={{ defaultExpandAllRows: true }}`

### What is expected?
All rows are expanded, like when using `children` as the `childrenColumnName`

### What is actually happening?
Only the first level of rows is expanded

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | Mac |
| Browser | Chrome |

**Comment by andykent** [comment]
Additionally, whilst testing this I just noticed the expand icon positioning is wrong in Safari 13.0.5...

<img width="291" alt="Screenshot 2020-03-02 at 14 59 41" src="https://user-images.githubusercontent.com/614/75687937-7ec65b80-5c96-11ea-9c9e-d92c6205cb40.png">

**Comment by fw-amgaa** [comment]
not working even after fix. 
I did <Table
            childrenColumnName="children"
            expandable={{ defaultExpandAllRows: true }}
          />
but all rows are not expanded at all.

**Comment by mdapper** [comment]
This comment helped me solve the problem https://github.com/ant-design/ant-design/issues/11615#issuecomment-722747602

**Comment by AnhNH512** [comment]
> not working even after fix. I did <Table childrenColumnName="children" expandable={{ defaultExpandAllRows: true }} /> but all rows are not expanded at all.
I was try it and I was success you can pass childrenColumn name to expandable 
expandable = {{
   childrenColumnName : "something else",
   defaultExpandAllRows  : true
}}

**Comment by sherali-1** [comment]
working 2 solution here: https://stackoverflow.com/a/70765648/18734565

**Comment by jaweii** [comment]
I solved the problem by adding key to Table:

`<Table key={dataSource.length} {...props} />`

**Comment by KhanhBatLuc** [comment]
> https://stackoverflow.com/a/70765648/18734565

I followed but with version antd 5.4.0 it not working

**Comment by KhanhBatLuc** [comment]
> > not working even after fix. I did <Table childrenColumnName="children" expandable={{ defaultExpandAllRows: true }} /> but all rows are not expanded at all.
> > I tried it and I succeeded, you can pass childrenColumn name to expandable
> > expandable = {{
> > childrenColumnName : "something else",
> > defaultExpandAllRows  : true
> > }}

I followed but with version antd 5.4.0 it not working

**Comment by yogithesymbian** [comment]
> I solved the problem by adding key to Table:
> 
> `<Table key={dataSource.length} {...props} />`

thankyou , u saved my life ...

**Comment by kursadaltan** [comment]
> I solved the problem by adding key to Table:
> 
> `<Table key={dataSource.length} {...props} />`

Thank you for support. I pass problem.
