### ISSUE TITLE
自定义theme

### ISSUE THREAD

**Issue by xueqingxiao** [ant-design/ant-design#2178]
我想自定义theme，因为所有的component都引用了theme/default.less, 导致我自定义的theme不起作用。能否将 theme/default.less 从所有的component移除? 如果不能有没有一种是方式去自定义theme？

**Comment by yesmeck** [comment]
https://github.com/ant-design/antd-init/tree/master/examples/customize-antd-theme

**Comment by xueqingxiao** [comment]
@yesmeck 多谢了， 者正是我需要的。
