### ISSUE TITLE
table设置展开属性，指定展开图标在某一列显示时，表格复选框会错位

### ISSUE THREAD

**Issue by insistenceZHUO** [ant-design/ant-design#21781]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-worker-z7kow )

### Steps to reproduce
无需任何步骤

### What is expected?
复选框在最前面展示

### What is actually happening?
colunms的第一列显示在复选框的前面

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8 |
| System | win7 |
| Browser | google 版本 73.0.3642.0（正式版本） （32 位） |

**Comment by zombieJ** [comment]
Seems order logic should adjust.
