### ISSUE TITLE
Form.Item 的 validateFirst 属性, 对于自定义的 validator 验证无效!

### ISSUE THREAD

**Issue by dotcoo** [ant-design/ant-design#21793]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-2e6n7?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
在用户名中输入 a

### What is expected?
因为在 Form.Item 上设置了 validateFirst, 应该是第二条 rule 验证失败, 提示错误信息 'username' must be between 5 and 16 characters, 第三和第四条 rule 不执行.

### What is actually happening?
第二条 rule 验证失败, 后续 rule 不执行. 但是在控制台中可以看到第四条 rule 的 ajax 还是发送出去了.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react |
| System | win10 |
| Browser | Chrome 80.0.3987.122 |

**Comment by zombieJ** [comment]
`validateFirst` 指的是：
> 当某一规则校验不通过时，是否停止剩下的规则的校验

开启 `validateFirst` 后，任意一条规则验证失败就返回错误，而非等待所有验证失败后才返回。

**Comment by yoyo837** [comment]
意思是验证还是会执行，但是不等待结果？

**Comment by yoyo837** [comment]
我个人的理解是，逐条执行，遇到错误则停止并返回。

**Comment by zombieJ** [comment]
真实业务中有些异步校验会很久，逐条执行会明显加长等待时间。

**Comment by yoyo837** [comment]
那 @dotcoo 你这个就支持不了。

**Comment by yoyo837** [comment]
@zombieJ 能接受改为用户配置不？

**Comment by dotcoo** [comment]
> 那 @dotcoo 你这个就支持不了。

好的

**Comment by zombieJ** [comment]
> @zombieJ 能接受改为用户配置不？

没什么必要，做成有序的，即便是全部规则通过，用户也需要等更长的时间。

**Comment by JLoveI** [comment]
必填和异步校验，结果老是同步进行，没有还要进行异步校验，这个能否设置成有序的

**Comment by kpaxqin** [comment]
> 真实业务中有些异步校验会很久，逐条执行会明显加长等待时间。

个人觉得这个理由不成立，validator函数async化后，想要并行只要Promise.all 就可以了，用户是可以控制避免逐条执行的。

更何况真实业务中很难有多个异步校验（为什么不合成一个接口？），更多的场景是先同步校验必填、格式，通过后再做异步校验，现在同时执行的设计就完全支持不了，需要在所有异步校验函数里再重复写一遍同步前置校验。如果我同步校验是 type: 'email'，就那要确保自己重复写的，和type: 'email' 用的正则是一模一样的。

一边是少数场景且有轻松解，另一边是多数场景且解起来非常恶心。
validateFirst做成阻塞式既更实用，也和antd@3.x 保持兼容。
现在3.x迁过来的应用，很多异步校验现在变成了频繁且无意义的执行。

**Comment by zombieJ** [comment]
👌 合理

**Comment by zombieJ** [comment]
调整成默认顺序，并提供开启同时异步的选项让需要提速的用户用。
```
<Form.Item validateFirst="parallel" />
```

**Comment by MiniWei-boop** [comment]
请问一下这个解决了吗？上一条不能超过50个字的规则没通过，我自定义的validator里面的异步请求还是会发出去
