### ISSUE TITLE
日历组件 手机屏幕下错位，未自动换行

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#21794]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar-cn/](https://ant.design/components/calendar-cn/)

### Steps to reproduce
在小屏幕手机上测试

### What is expected?
图标不错位，月年自动换行

### What is actually happening?
图标错位，月年不自动换行

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.10 |
| System | iphone |
| Browser | chrome |

![捕获](https://user-images.githubusercontent.com/3166799/75733314-ec729600-5d2f-11ea-88d7-7d2bd6d6d2d0.PNG)

**Comment by yoyo837** [comment]
最小兼容 320px 吗？
