### ISSUE TITLE
RangePicker 4.X 如何设置选择范围

### ISSUE THREAD

**Issue by soulcm** [ant-design/ant-design#21795]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如只准选两个月的范围，start选了3月1号，那end只准选5月1号之前的值。
4.x之前的版本自己通过 onCalendarChange 和 disabledDate 可以实现，因为只选择一个start的时候 onCalendarChange 的值length为1，然后去控制disableDate的值，但现在4.x，start和end可以分开选择了，不知该如何实现了

### What does the proposed API look like?
依照4.X目前的方式，是否只能加个范围属性，其他由RangePicker去实现了

**Comment by yoyo837** [comment]
https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date

**Comment by willluck** [comment]
同样遇到了这个问题，要根据第一个选择的时间来决定第二个的禁用范围，感觉新版的没有老版的好用

**Comment by soulcm** [comment]
> https://ant.design/components/date-picker-cn/#components-date-picker-demo-disabled-date

麻烦看清我的需求，不是要固定禁用某些日期，是要根据start或end的选择，再禁用相应的日期

**Comment by soulcm** [comment]
> 同样遇到了这个问题，要根据第一个选择的时间来决定第二个的禁用范围，感觉新版的没有老版的好用

嗯，最起码老版本我有办法实现，新版本按新的交互方式，start和end可以分开选择，我没办法实现了，只能看antd能否提供API了

**Comment by willluck** [comment]
同样遇到了这个问题，要根据第一个选择的时间来决定第二个的禁用范围，感觉新版的没有老版的好用

> > 同样遇到了这个问题，要根据第一个选择的时间来决定第二个的禁用范围，感觉新版的没有老版的好用
> 
> 嗯，最起码老版本我有办法实现，新版本按新的交互方式，start和end可以分开选择，我没办法实现了，只能看antd能否提供API了

我正好就在用新版的RangePicker，我的需求是选了第一个，然后结束时间只能是在第一个选的时间的前一天或后一天，如果我第二个时间选了第一个时间的前一天，那么老组件能自动把第二个时间当成开始时间，第一个选的时间当成结束时间，现在这个分开选的就不行，如果现在我选了开始时间，那么禁用逻辑就只对开始时间的下拉框生效。。。

**Comment by zombieJ** [comment]
https://codesandbox.io/s/divine-moon-61y08

**Comment by afc163** [comment]
可以放到 demo 里去

**Comment by soulcm** [comment]
就这样关了吗，demo我看了，真的算勉强是实现了，先不说代码为了这么个功能加这么多逻辑，但现在start和end分开设置，导致这种情况下的交互真的很不友好了

**Comment by afc163** [comment]
@soulcm 你能写一个 codesandbox 演示一下 3.x 中是怎么做的？我们看看 4.x 里能不能跑的起来，是不是可以兼容性修复。

**Comment by willluck** [comment]
> @soulcm 你能写一个 codesandbox 演示一下 3.x 中是怎么做的？我们看看 4.x 里能不能跑的起来，是不是可以兼容性修复。

https://codesandbox.io/s/patient-fire-n6tdp
这里是我们项目中3.x的原代码，升到4.x的表现就很奇怪

**Comment by willluck** [comment]
> > @soulcm 你能写一个 codesandbox 演示一下 3.x 中是怎么做的？我们看看 4.x 里能不能跑的起来，是不是可以兼容性修复。
> 
> https://codesandbox.io/s/patient-fire-n6tdp
> 这里是我们项目中3.x的原代码，升到4.x的表现就很奇怪

需求就是选了开始时间，结束时间只能选开始时间的前一天或者后一天，用4.x的组件，感觉交互更复杂了，很重要一点就是结束时间不能选开始时间的前面了，3.x的组件会自行判断，小的时间就是开始时间，大的时间就是结束时间

**Comment by afc163** [comment]
@zombieJ 有空可以看看，暂时先 reopen 在这里。

**Comment by soulcm** [comment]
https://codesandbox.io/s/compassionate-shamir-f63np

**Comment by xue1206** [comment]
v4中start和end可以分开选择，确实没法做到起始时间互相限制了，希望官方能提供解决方案

**Comment by xzf123456** [comment]
v4中start和end可以分开选择，某些场景下很方便但某些场景下确实不方便，能否用一个属性让开发者自主选择是分开选还是一起选

**Comment by Alexerx** [comment]
确实给👴整傻了

**Comment by afc163** [comment]
trace #31643
