### ISSUE TITLE
message里warn方法与warning方法的问题？

### ISSUE THREAD

**Issue by Flourad** [ant-design/ant-design#2180]
- antd 版本:  "0.12.7",
- 浏览器及其版本: chrome
发现我现在用的antd的message并没有官网文档中写的message.warning(...)方法，只有message.warn()，下面是我在console里打印出来的message，我现在使用的antd版本是0.12.7

![image](https://cloud.githubusercontent.com/assets/1535874/16368038/7197a774-3c5c-11e6-88f1-adaeb401c4fd.png)

看了最新版本的message源码，只有message.warning(...)，是不是现在用warning替代了warn，如果这样的话，建议更新一下官网的文档，不然会引起误解~
官网API文档是酱紫，没有版本说明：
![image](https://cloud.githubusercontent.com/assets/1535874/16368176/d5bae7e2-3c5d-11e6-9a2c-b35b680a222d.png)

**Comment by afc163** [comment]
http://012x.ant.design/

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/fc55cf69194057cb452e13119697cdffd40f6793

It is a sad argument, you can use them both now.
