### ISSUE TITLE
升级到4.0后，找不到@ant-design/compatible

### ISSUE THREAD

**Issue by linguisx** [ant-design/ant-design#21808]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.meiyou.com](http://www.meiyou.com)

### Steps to reproduce
antd的3.26版本，使用@ant-design/codemod-v4升级后，找不到@ant-design/compatible

### What is expected?
正常使用

### What is actually happening?
不能编译通过

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12 |
| System | Windows10 |
| Browser | Chrome |

**Comment by yoyo837** [comment]
自行安装 @ant-design/compatible

**Comment by afc163** [comment]
注意命令行最后的提示信息。
