### ISSUE TITLE
expand related props don't works in 4.0

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#21803]
- [ ] defaultExpandAllRows
- [ ] defaultExpandedRowKeys
- [ ] expandedRowKeys
- [ ] expandedRowRender  
- [ ] expandIcon
- [ ] expandRowByClick
- [ ] expandIconColumnIndex
- [ ] childrenColumnName
- [ ] rowExpandable
- [ ] indentSize
- [ ] onExpand
- [ ] onExpandedRowsChange

**Comment by afc163** [comment]
`expandIconColumnIndex` 简单测了一下是文档确实，其他属性需要排查一下。

**Comment by Bojianye** [comment]
啥时候能修复呢？

**Comment by afc163** [comment]
@Bojianye 你遇到了什么问题？能麻烦提供一个重现吗？

**Comment by Bojianye** [comment]
expandedRowRender  don't work in antd V4.

**Comment by afc163** [comment]
@Bojianye https://codesandbox.io/s/billowing-leftpad-n64w7 我测试是可以的。

**Comment by Bojianye** [comment]
我是用的antd pro table, v1.0.43

**Comment by Bojianye** [comment]
@afc163 是不是antd pro table 也要使用v2？

**Comment by zombieJ** [comment]
@chenshuai2144

**Comment by chenshuai2144** [comment]
@Bojianye  是跟着你的项目走的。

**Comment by zombieJ** [comment]
看了一圈，应该就是 `expandIconColumnIndex` 文档里没有。改标签了。

**Comment by angusun** [comment]
expandedRowKeys 这个属性貌似还是不能用哦

**Comment by xiaochouyu2663** [comment]
rowExpandable don't work in antd V4.

**Comment by es3154** [comment]
rowExpandable  这个属性不可用，v4.4.0

**Comment by zombieJ** [comment]
@es3154 给个重现看看

**Comment by es3154** [comment]
@zombieJ https://github.com/es3154/antd_test/blob/master/src/index.js
`expandable={{
                       rowExpandable: d => d.id > 1
                   }}`
这行不起作用，可展开行要手动设置 行数据的children吗？

**Comment by zombieJ** [comment]
> @zombieJ https://github.com/es3154/antd_test/blob/master/src/index.js
> `expandable={{ rowExpandable: d => d.id > 1 }}`
> 这行不起作用，可展开行要手动设置 行数据的children吗？

https://codesandbox.io/s/ecstatic-wiles-wtxox?file=/index.js

没有配置展开内容，配置了就有了

**Comment by es3154** [comment]
原来这个是配合expandRender使用的，我想要的是树形表格，我们节点是动态加载的，有子节点的行有个标记属性，按照目前的用法，只能拿到表格数据后再遍历一遍，符合标记属性的行手动加childern属性了


 
---Original---
