### ISSUE TITLE
Table with fixed column in RTL direction

### ISSUE THREAD

**Issue by saeedrahimi** [ant-design/ant-design#21815]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/small-bush-k7zgg)

### Steps to reproduce
A table with fixed column config in Rtl direction

### What is expected?
Expected to show fixed columns correctly in Rtl direction
[expected demo](https://codesandbox.io/s/fervent-wilbur-xg3r9)

### What is actually happening?
No fixed columns and misplaced shadow

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react latest |
| System | Windows 10 |
| Browser | Chrome Version 80.0.3987.122 (Official Build) (64-bit) |

---
The original bug was reported by @mehdiraized in #21814

**Comment by zombieJ** [comment]
@saeedrahimi , what should table like when in RTL?

**Comment by saeedrahimi** [comment]
> @saeedrahimi , what should table like when in RTL?

fixed column should be displayed correctly in horizontal scrolling.
https://codesandbox.io/s/fervent-wilbur-xg3r9

**Comment by zombieJ** [comment]
Wow. I saw your patch the css in the codesandbox. Could you help move it in antd also?

**Comment by saeedrahimi** [comment]
> Wow. I saw your patch the css in the codesandbox. Could you help move it in antd also?

Of course.

**Comment by saeedrahimi** [comment]
I tried to handle this bug with just css patch but some sizes in fixed columns like `left: 100px` is defined by `rc-table` component.
So i decided to apply rtl to rc-table to support fixed column, and now a [pull request is opened ](https://github.com/react-component/table/pull/426)

**Comment by ahmedrowaihi** [comment]
@saeedrahimi is this fix applicable to virtual mode as well ? it seems not working in virtual
