### ISSUE TITLE
antd v4 add initialValue support on Form.Item like v3

### ISSUE THREAD

**Issue by davy-gan** [ant-design/ant-design#21816]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决复杂表单，循环渲染表单列表时赋值 

### What does the proposed API look like?
目前from 是将默认值挂载到form 上 ，期望还是和v3一样挂载在每个具体的item上

-----

@zombieJ  Update:
# Hi all. This issue is welcomed for feedback collection. If you like add `initialValue` on Form.Item, pls add 👍 on the topic directly. Or 👎 if not agree. Add feel free for other suggestion.

**Comment by davy-gan** [comment]
![image](https://user-images.githubusercontent.com/21240946/75752785-5b69e200-5d64-11ea-861c-84168d18b179.png)
 如这种情况下的 复杂表单复制 ，全部将默认值写在 form 上到后期没更没法维护，或者不好处理 从服务拿到数据循环渲染，复制循环渲染后的 复制局部表单，将复制后的局部表单设置成之前的复制时的值

**Comment by yoyo837** [comment]
我的情况和你类似，不过如果现在更改就是break change了

**Comment by lich-yoo** [comment]
针对每个 formitem 的 value 有具体格式化处理的，确实处理比之前复杂些。
比如之前可以在 datarange item 中把 '1583193600000,1583193600000' 格式化为 [moment, moment]。等等... 每个 item 的 value format 是由自己负责，比较清晰且隔离。
现在只能在 initialValues 前处理，而且是 object 数据，针对 type 的 format 比较麻烦。

@zombieJ  @afc163  后续是否考虑在 form 或 formitem 中加入 format 功能？

**Comment by shaodahong** [comment]
@lich-yoo 你的这个想法我们之前有讨论过 #19727

**Comment by supnate** [comment]
允许 Form Item 上设置 initialValue 可以更好的增加封装性，比如有一个通用的 Remember Me 组件：
```
const RememberMe = () => (
  <Form.Item name="rememberMe" initialValue={Cookie.get('remember-me')}>
    <CheckBox>RememberMe</CheckBox>
  </Form.Item>
);
```
能够让组件自己内部处理 initialValue。

**Comment by yoyo837** [comment]
So, 如果有打算accept这个的话，我就晚点升级自己项目 😂.

**Comment by LinkToWorld** [comment]
我也碰到了类似的问题，进行循环渲染的时候，以前只需要写一个生成FormItem数组的循环逻辑即可，现在还需要再写一个逻辑专门来生成Form组件的initialvalue属性。另外，针对FormItem组件的封装也变得不够优雅。

**Comment by soulcm** [comment]
> 我也碰到了类似的问题，进行循环渲染的时候，以前只需要写一个生成FormItem数组的循环逻辑即可，现在还需要再写一个逻辑专门来生成Form组件的initialvalue属性。另外，针对FormItem组件的封装也变得不够优雅。

+1

**Comment by qiqiboy** [comment]
还是要支持Field设置默认值，这样可以避免有默认值的field和form强耦合，增强可复用性。但是form的initialValues优先级应当大于field，前者设置了的话，覆盖同名field的默认值

**Comment by yoyo837** [comment]
@qiqiboy 我觉得优先级应该和你说的相反

**Comment by qiqiboy** [comment]
> @qiqiboy 我觉得优先级应该和你说的相反

举例场景：

```typescript
// FieldTelcode.tsx
<Form.Item initialValue="86">
     <Select />
</Form.Item>

// FormA.tsx
<Form initialValues={{ telcode: '1' }}>
    <FieldTelcode />
</FormA>

// FormB.tsx
<Form initialValues={{ telcode: '2' }}>
    <FieldTelcode />
</FormA>
```

我认为实际业务中，封装独立的Field或者FieldFragment，然后在不同Form中复用是基础场景。如果都能设置Form的初始值了，干嘛还要单独再设置Field的初始值去覆盖Form？

**Comment by zombieJ** [comment]
Form 上的 `initialValues` 优先级应该更高，以避免动态创建 Form.Item 还带有 `initialValue` 的覆盖问题。此外，如果多个 Form.Item 都注册了 `initialValue` 或者和 Form 的 `initialValues` 冲突，都应该 warning 并且以 Form 的 `initialValues` 为准，如果没有 `initialValues` 则不保证 `initialValue` 的值是哪个（这就回到了 v3 的问题）。

**Comment by yoyo837** [comment]
> 如果没有 `initialValues` 则不保证 `initialValue` 的值是哪个（这就回到了 v3 的问题）

这个指的是？有讨论相关的链接吗？

**Comment by qiqiboy** [comment]
warning不必了吧，循环创建Form.Item带默认值是个使用场景，但是我个人经验中，创建出可复用的带默认值的Field/Form.Item是个更高频需求，例如Telcode、RegionSelect等，都会带比如+86、CHN等默认值。

表单应当聚焦于Field，基于Field能完成默认值设置、校验、model-view值得相互转换），才能编写出可复用的Field或者若干Field组成的FormFragment。如果像设置默认值、值得转换处理都能在Form层做，那么这就导致Field必然深度耦合Form，不利于复用

**Comment by LinkToWorld** [comment]
@qiqiboy  关于Form属性initialValues和Form.Item属性initialValue两者优先级的问题，我倾向于后者优先级更高。理由很简单：其他共有属性如：labelAlign、labelCol、wrapperCol，他们的规则都是Form.Item覆盖Form，突然initialValue属性反了过来，会造成理解上的混乱。另外，如果Form.item支持initialValue属性，感觉Form的initialValues属性就不怎么需要了。

**Comment by qiqiboy** [comment]
> @qiqiboy 关于Form属性initialValues和Form.Item属性initialValue两者优先级的问题，我倾向于后者优先级更高。理由很简单：其他共有属性如：labelAlign、labelCol、wrapperCol，他们的规则都是Form.Item覆盖Form，突然initialValue属性反了过来，会造成理解上的混乱。另外，如果Form.item支持initialValue属性，感觉Form的initialValues属性就不怎么需要了。

理解。antd里的Form带了UI属性，这么做确实保证理解上的一致性。

但是我还是保留我的意见，觉得UI相关的属性与value分属不同维度（value虽然也会影响UI，但是更重要的是要被上层获取。最后是要拿到Form上层使用的，理论上Form上的初始值也应该更优先，保证输入输出的预期一致），是可以分开的，并且是可以利于Field复用性的。

**Comment by zombieJ** [comment]
冲突指的是这种情况：
```jsx
<Form>
  <Form.Item name="test" initialValue="123" />
  <Form.Item name="test" initialValue="233" />
</Form>
```

这种时候，直观的看或许选第一个 `123` 更好。接着，通过 shouldUpdate 动态的删除 Form.Item:
```jsx
<Form>
  <Form.Item shouldUpdate>
     anytingButFalse && <Form.Item name="test" initialValue="233" />
  </Form.Item>
  <Form.Item name="test" initialValue="233" />
</Form>
```

于是 resetFields 直观的应该是 `233`。

这时候，渲染又恢复成两者都展示的情况：
```jsx
<Form>
  <Form.Item name="test" initialValue="123" />
  <Form.Item name="test" initialValue="233" />
</Form>
```

看起来应该是 `123` 了，但是其实不然。内部的 Fields 管理其实是如下变化：

1. Field:123 , Field: 233
2. Field: 233
3. Field: 233, Field:123 （删除后重新添加回列表）

这个时候，代码初始化的值就会有出入。这只是个简单的例子。其实在任何场景下只要会发生 Field 动态增减的都可能会引起注册字段的顺序变化。这就是为什么我建议如果冲突就应该 warning，同时如果有 Form 的 `initialValues` 总是以 Form 的为准。

**Comment by yoyo837** [comment]
对于name重复的field如果直接给警告然后忽略呢？

**Comment by albert-cai** [comment]
希望添加这个支持，然后以form 的 initialValues 为准即可

**Comment by supnate** [comment]
Form.Item 优先 +1
因为在使用 Form.Item 的地方总有机会/办法拿到上层的 intialValues，从而可以自己决定用哪个。而上层 Form 上的 initialValues 如果优先了，下层实现会有和不支持 initialValue 同样的 limitation，只是程度稍微轻了一点而已。

从封装角度看，initialValue 是 Form.Item 的属性，设置就该生效，不该被全局变量影响。

**Comment by zombieJ** [comment]
如果 Field B 的上层渲染是根据 Field A 的值来，而 Field A 是异步添加。由于不知道哪些 renderProps 依赖了这个 Field 的 init value 就需要全局 re-render 一遍。

**Comment by yoyo837** [comment]
那就是做取舍了，功能优先性能，除非性能无法满足基本要求。

**Comment by subzero274** [comment]
使用antd v4无法给给动态创建的组件赋值，就像这样，如果使用V3 Form.Item initialValue就很容易实
`
import React, { Component } from 'react';
import { Form,Input } from 'antd';

class Test extends Component {
  state = {
    list: [1],
  };

  constructor(props) {
    super(props);
    this.addList = this.addList.bind(this);
  }

  addList(){
    const { list } = this.state;
    this.setState({
      list: [ ...list,parseInt(Math.random() * 100)]
    })
  }

  render() {
    const { list } = this.state;
    const initialValues = {};
    list.map((i,index) => {
      initialValues[`test-${index}`] = i;
    })
    return (
      <>
        <Form initialValues={initialValues} onSubmit={this.reciveTask}>
          {list.map((value,index) => (<Form.Item label="ContentType" name={`test-${index}`}>
            <Input />
          </Form.Item>))}
        </Form>
        <div onClick={this.addList}>添加新表单项</div>
      </>
    );
  }
}
export default Test;
`

**Comment by subzero274** [comment]
使用antd v4无法给给动态创建的组件赋值，就像这样，如果使用V3 Form.Item initialValue就很容易实现
这个问题V4有解吗？
```javascript
import React, { Component } from 'react';
import { Form,Input } from 'antd';

class Test extends Component {
  state = {
    list: [1],
  };

  constructor(props) {
    super(props);
    this.addList = this.addList.bind(this);
  }

  addList(){
    const { list } = this.state;
    this.setState({
      list: [ ...list,parseInt(Math.random() * 100)]
    })
  }

  render() {
    const { list } = this.state;
    const initialValues = {};
    list.map((i,index) => {
      initialValues[`test-${index}`] = i;
    })
    return (
      <>
        <Form initialValues={initialValues} onSubmit={this.reciveTask}>
          {list.map((value,index) => (<Form.Item label="ContentType" name={`test-${index}`}>
            <Input />
          </Form.Item>))}
        </Form>
        <div onClick={this.addList}>添加新表单项</div>
      </>
    );
  }
}
export default Test;
```

**Comment by ZhaoXinNian** [comment]
+1

**Comment by supnate** [comment]
If you want initialValue on form item, you may take a look at: https://github.com/rekit/antd-form-builder

**Comment by yoyo837** [comment]
It would be better if `antd` support this directly.
