### ISSUE TITLE
Form组件版本逻辑不一致

### ISSUE THREAD

**Issue by yikyo** [ant-design/ant-design#21812]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-matsumoto-utwth)

### Steps to reproduce
  当选择antd版本为（4.0.0）       ，点击按钮（Fill form)，查看console打印值
  当选择antd版本为（4.0.0-rc.0），点击按钮（Fill form)，查看console打印值

### What is expected?
打印结果一致

### What is actually happening?
  打印结果不一致，在4.0.0-rc.0输出      {note: "Hello world!", gender: "male", a: "b"}
  打印结果不一致，在4.0.0       输出      {note: "Hello world!", gender: "male"}

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | latest |
| System | mac 10.15 |
| Browser | chrome 80 |

**Comment by afc163** [comment]
这个 `4.0.0-rc.0` 的一个 bug，导致 form 和 3.x 的逻辑不一致，我们不得已进行了修复：https://github.com/ant-design/ant-design/issues/21320

更多相关讨论可见：https://github.com/ant-design/ant-design/issues/21435

**Comment by yikyo** [comment]
@afc163 假如我需要这个功能，我如何解决，比如我有个用户场景，购买产品时，需要选择多个配件，再计算最终的价格。

**Comment by afc163** [comment]
建议选择后把临时的控件保存到一个 UI 的稳定区。

或者无脑 `getFieldsValue(true)`

**Comment by afc163** [comment]
换句话说，你在 3.x 里怎么解决的？

**Comment by yikyo** [comment]
我最近在一直用4.0版，今天更新了一下，突然发现无法使用了，所以提issue，以为是bug
