### ISSUE TITLE
useForm > getFieldValue does not work

### ISSUE THREAD

**Issue by mxschmitt** [ant-design/ant-design#21829]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-d756r)

### Steps to reproduce
1. Open the link
2. Type something into field 2, both log point 1 and log point will show undefined

### What is expected?
The value of field1 will be logged

### What is actually happening?
undefined will be returned

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13 |
| System | macOS 10.15.3 |
| Browser | Chrome Version 80.0.3987.122 |

**Comment by mxschmitt** [comment]
Could be fixed by rewriting it like that:
https://codesandbox.io/s/antd-reproduction-template-993jp

The issue was in my mind that in the new Ant Design version the Form won't re-render if values are changing. Before it was like that. so if I pass now the `getFieldValue` function into the underlying component it works.

**Comment by josipbrcina** [comment]
@mxschmitt I am wondering why do you have console warning in your reproduction codesandbox
```Warning: Instance created by `useForm` is not connect to any Form element. Forget to pass `form` prop?``` when you did pass prop form?

**Comment by mxschmitt** [comment]
@josipbrcina I still face into that issue with the warning even by passing it as a Form prop. Strange.

**Comment by josipbrcina** [comment]
> @josipbrcina I still face into that issue with the warning on our application even by passing it as a Form prop. Strange.

I am gonna search one more time through the issues and potentially open a new one.

**Comment by josipbrcina** [comment]
#22130

**Comment by josipbrcina** [comment]
> > @josipbrcina I still face into that issue with the warning on our application even by passing it as a Form prop. Strange.
> 
> I am gonna search one more time through the issues and potentially open a new one.

#22130

**Comment by PeiTianHuang** [comment]
我也遇到了一样的问题，同样的代码在3.16版本上运行正常，在4.01上则会报错

**Comment by edbella** [comment]
In addition to this, I also noticed that `getFieldValue` which is supposed to listen to field value change doesn't work until I submit the form. Has anyone noticed this or I'm getting it wrong.

I'm simply calling `const clientName = form.getFieldValue('companyName');` but nothing returns for this particular field till I submit which isn't the way it worked in v3.

**Comment by mustafaIhssan** [comment]
Have you solved the issue ?

**Comment by adirrapidapi** [comment]
same issue. any solution?

**Comment by adred** [comment]
@edbella experiencing it too which doesn't make sense!

**Comment by adred** [comment]
I'm forced to re-render form by 
```javascript 
const forceUpdate = useReducer(() => ({}), {})[1] as () => void;
``` 
Just pass `forceUpdate` to your child component where you're calling `setFieldsValue`.
Basically the issue is `setFieldsValue` isn't triggering a re-render of the parent component. I hope it gets resolved!

**Comment by JohnDevitt** [comment]
Also experiencing the same issue: form.getFieldValue doesn't always update on a field change. Weirdly though, onValuesChange gets called reliably, so I can work around the issue with some state:

´´´
const [form] = useForm();
const [fieldUpdated, setFieldUpdated]<boolean>(false)

const onValuesChange = ({fieldName}) => {
    if(!fieldUpdated && fieldName) {
        setFieldUpdated(fieldName)
     }
}

return (
    <Form
        form={form}
        onValuesChange={onValuesChange}
    >
        ....
```

Less than ideal though, would be great to open the issue back up.

**Comment by andreiher** [comment]
Hello,

So i was facing an issue, in which i wasn't able to retrieve the values, using form.getFieldsValue. Tried a bunch of combinations and finally i stumbled upon a way that it works pretty much ok. 
Here is how 

```
const [form] = useForm();
console.log("form values", form.getFieldsValue());
return (
    <Form
        form={form}
    >
         {() => (<div>....</div>)}
    </Form>
)
```

**Comment by raualvron** [comment]
> Also experiencing the same issue: **form.getFieldValue doesn't always updated on a field change**. Weirdly though, onValuesChange gets called reliably, so I can work around the issue with some state:
> 
> ```
> const [form] = useForm();
> const [fieldValue, setFieldvalue](undefined)
> 
> const onValuesChange = ({fieldName}) => {
>     if(!fieldValue && fieldName) {
>         setFieldvalue(fieldName)
>      }
> }
> 
> return (
>     <Form
>         form={form}
>         onValuesChange={onValuesChange}
>     >
>         ....
>     </Form>
> )
> ```
> 
> Less than ideal though, would be great to open the issue back up.

That is the workaround what we have applied too. Even doing the following:

```
const [valuesForm, setValuesForm] = useState({});

 <Form
        form={form}
         onValuesChange={(v) => setValuesForm(v)}
    >

```
getFieldValue is updated on any field change.

**Comment by acomito** [comment]
Having the same issue still

**Comment by zjb19970804** [comment]
The same problem
dependencies and shouldupdate can only be used in JSX Form.Item It works,
we need to use it in functions form.getFieldValue

**Comment by experimatt** [comment]
It took a bit of refactoring but I was able to work around this using `dependencies` and also `shouldUpdate`. `dependencies` seemed like a slightly more elegant solution, but not only by a little bit.

```
          <Form.Item
            dependencies={['hourly']}
            noStyle
          >
            {({ getFieldValue }) => {
              return getFieldValue('hourly') ? (
                <Form.Item>
                  <div className='heading-small grey pb-2'>
                    What is your desired hourly rate?
                  </div>
                  <Form.Item
                    name='hourly_rate'
                    noStyle
                  >
                    <InputNumber
                      step={5}
                      formatter={value =>
                        `$ ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')
                      }
                      parser={value => value.replace(/\$\s?|(,*)/g, '')}
                      min={0}
                      max={500}
                    />
                  </Form.Item>
                </Form.Item>
              ) : null
            }}
          </Form.Item>
```

**Comment by moms-spaghetti** [comment]
I got this work by doing this 

Created a simple form. This is from a project I'm working on so I've remove most of the irrelevant code. 

```
<Form
        name="cms"
        form={form}
      >
        <Form.Item label="Video URL" name="video_url">
          <Input />
        </Form.Item>
</Form>
```

When grabbing the field contents I used getFieldValue like this. 
```
let videoUrlValue = form.getFieldValue("video_url")
console.log(videoUrlValue )
```

Hope that helps

**Comment by N1ck0lay** [comment]
I faced the same issue, code below will solve it

`const [formValues, setFormValues] = useState({});
const [form] = Form.useForm();

<Form
    form={form}
    onValuesChange={(values) => setValuesForm(values)}
>`

**Comment by Alice-Rez** [comment]
Same issue still present, thanks to all who offered solution here!

**Comment by Hemistone** [comment]
@N1ck0lay  In my case, I had to add`_` on `onValuesChange` function inputs like this, 
since it has definition as `onValuesChange?: ((changedValues: any, values: TimeFields) => void) | undefined`
and to get the whole `formValues` correctly, you should use the latter one.

```javascript
const [formValues, setFormValues] = useState({});
const [form] = Form.useForm();

<Form
  form={form}
  onValuesChange={(_, values) => setValuesForm(values)}
>

```

**Comment by carefreeav09** [comment]
@Hemistone's solution works perfectly! @N1ck0lay's solution doesn't work properly for dynamic fields.

**Comment by altschuler** [comment]
If anyone else stumbles upon this, there's a new `useWatch` hook (since 4.20) that helps with exactly this: https://ant.design/components/form/#Form.useWatch

**Comment by zakrogogolidze** [comment]
**Advanced:**

```
const [formValues, setFormValues] = useState({});
const [form] = Form.useForm();

<Form
  form={form}
  onValuesChange={(_, values) => setFormValues(prevState => ({...prevState, ...values}))}
>
```

**Comment by deathemperor** [comment]
> If anyone else stumbles upon this, there's a new `useWatch` hook (since 4.20) that helps with exactly this: [ant.design/components/form/#Form.useWatch](https://ant.design/components/form/#Form.useWatch)

This should be marked as "best answer". need more votes!

**Comment by fuadbaskara** [comment]
> > If anyone else stumbles upon this, there's a new `useWatch` hook (since 4.20) that helps with exactly this: [ant.design/components/form/#Form.useWatch](https://ant.design/components/form/#Form.useWatch)
> 
> This should be marked as "best answer". need more votes!

This the the best answer, hope ppl read the thread until here

**Comment by long-kr** [comment]
> > > If anyone else stumbles upon this, there's a new `useWatch` hook (since 4.20) that helps with exactly this: [ant.design/components/form/#Form.useWatch](https://ant.design/components/form/#Form.useWatch)
> > 
> > 
> > This should be marked as "best answer". need more votes!
> 
> This the the best answer, hope ppl read the thread until here

I did miss this answer, haha
