### ISSUE TITLE
Setting defaultValue on TextArea produces no effect

### ISSUE THREAD

**Issue by giordy** [ant-design/ant-design#21820]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ts-xkh5f8](https://stackblitz.com/edit/react-ts-xkh5f8)

### Steps to reproduce
Create a TextArea and set a defaultValue, it doesn't appear

### What is expected?
the default value should be set in the TextArea and appear

### What is actually happening?
I only see the place holder

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | MacOS 10.15.3 |
| Browser | Firefox 73.0.1 |

**Comment by afc163** [comment]
@zombieJ Should we allow user specify `defaultValue` in form control? It is not conflict with `initialValues`.

**Comment by zombieJ** [comment]
No. Never ever use `defaultValue` when using form control. When user set `defaultValue`, the form store actually is empty about this field even it display on the input box. If user not modify this field and submit the form, form get empty value.

@giordy , When you use form control, you should always set default value by `initialValues` in Form.

**Comment by hikmatbishokarma** [comment]
Hshbssbzb

**Comment by eschizo** [comment]
same problem for me!
:(

**Comment by eschizo** [comment]
> same problem for me!
> :(

Solved: 
If have userForm, it's necessary to use the `form.setFieldsValue` property:

ex:
form.setFieldsValue({
       'textareafield' : "TheValueYouWant"
})

**Comment by webberwang** [comment]
Why was this closed with any resolution?

**Comment by emanuelvsz** [comment]
> Why was this closed without any resolution?

Yeah, it make no sense.

But anyways, I'm having the same problem with this component 3 years a front of you guys 😆
