### ISSUE TITLE
antd@4.0.0 Result Component TypeDefinition Error

### ISSUE THREAD

**Issue by LPegasus** [ant-design/ant-design#21822]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-driscoll-ypwkh)

### Steps to reproduce
- Just see codesandbox link

### What is expected?
`props.status` should work.

### What is actually happening?
`props.status` type is an enum include 403 404 etc. which type is number.
But when status mapto image, Object.keys is used to reflect the keys. Thus, all number type keys will transform to string type. And an undefined error occurred.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | macOS |
| Browser | edge 80.0.361.48 |

**Comment by yoyo837** [comment]
Duplicated of #21741 #21592
