### ISSUE TITLE
v3->v4 Icon报错问题

### ISSUE THREAD

**Issue by nic329** [ant-design/ant-design#21833]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用v3的《Icon /》（由于markdown会解析，所以用全角符号）在v4的框架下会报一些莫名奇妙的错误，在升级时不好定位到原因，希望可以报错可以温馨化，告诉用户是因为使用了《Icon /》标签。

### What does the proposed API look like?
当用户在v4下使用了《Icon /》，能够提醒用户是因为Icon的问题。

**Comment by yoyo837** [comment]
有问题请提供复现按bug issue提交，这里描述的大串文字对解决问题提供的有用信息几乎为0。
