### ISSUE TITLE
Add displayName for each Components in order to identification?

### ISSUE THREAD

**Issue by Jibacat** [ant-design/ant-design#21830]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to identify the type of different components while added to `props.children`.

### What does the proposed API look like?
type: {
    ...,
    displayName: 'Input'
}

**Comment by afc163** [comment]
`Component.type`

**Comment by Jibacat** [comment]
> `Component.type`

component.type.name is not stable. It will be mangled to a simple name like `t` in production when i use babel & webpack

**Comment by Jibacat** [comment]
I cannot find a useful way to disable the mangling in webpack4 & babel.
![image](https://user-images.githubusercontent.com/28664253/75781328-f203c680-5d97-11ea-9266-9280396e906e.png)

**Comment by afc163** [comment]
```
import { Input } from 'antd';

console.log(component.type === Input);
```

**Comment by Jibacat** [comment]
> ```
> import { Input } from 'antd';
> 
> console.log(component.type === Input);
> ```

It works, thx👍
