### ISSUE TITLE
DatePicker input readonly mode.

### ISSUE THREAD

**Issue by moonjoungyoung** [ant-design/ant-design#21831]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
(duplicate but it is 2 years ago.)

### What problem does this feature solve?
I would like to forbid my users use Input in datepicker. Could you please provide some solution?

### What does the proposed API look like?
prop inputReadonly: boolean

**Comment by zombieJ** [comment]
Could you describe why disable user to input?

**Comment by afc163** [comment]
- https://github.com/ant-design/ant-design/issues/20442
- https://github.com/ant-design/ant-design/issues/20816

**Comment by afc163** [comment]
Merge into #20442
