### ISSUE TITLE
Setting undefined as value does not keep select clear in antd 4.0.0

### ISSUE THREAD

**Issue by locl95** [ant-design/ant-design#21839]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-wind-m3505-m3504)

### Steps to reproduce
Select any option

### What is expected?
To not show any option

### What is actually happening?
It's showing the selected optiom

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | mac OSX |
| Browser | Firefox |

---
It was working in 3.26.12: https://codesandbox.io/s/cool-pond-pz6sg

**Comment by zombieJ** [comment]
Select will tread as uncontrolled mode when `value` is keep `undefined` in v4. You it will auto reset if value change from some value to `undefined`: https://github.com/react-component/select/pull/443

ref https://github.com/react-component/select/pull/443

**Comment by zombieJ** [comment]
PS: `null` should make as control mode but not work, let me check why.
