### ISSUE TITLE
添加“高级搜索”表单区块后，页面出错

### ISSUE THREAD

**Issue by lazyfish88** [ant-design/ant-design#21837]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:8000/activity/list](http://localhost:8000/activity/list)

### Steps to reproduce
使用UI图形化编辑功能，新建一个空白页面，然后在这页面上加添一个“高级搜索”表单区块

### What is expected?
添加成功 

### What is actually happening?
提示异常

| Environment | Info |
|---|---|
| antd | 4.0.0-rc.1 |
| React | 16.8.6 |
| System | window10 |
| Browser | Google Chrome 80.0.3987.122 |

`×
Unhandled Rejection (TypeError): _form.default.create(...) is not a function
./src/pages/activity/list/AdvancedSearch/index.tsx
src/pages/activity/list/AdvancedSearch/index.tsx:72
  69 |   }
  70 | }
  71 | 
> 72 | const WrappedAdvancedSearchForm = Form.create({ name: "advanced_search" })(
  73 |   AdvancedSearchForm
  74 | );
  75 | export default () => (
View compiled
__webpack_require__
webpack/bootstrap:774
  771 | };
  772 | 
  773 | // Execute the module function
> 774 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  775 | 
  776 | // Flag the module as loaded
  777 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
./src/pages/activity/list/index.tsx
src/pages/activity/list/index.tsx:6
  3 | import { Spin } from 'antd';
  4 | import styles from './index.less';
  5 | import ActivityList from './ActivityList';
> 6 | import AdvancedSearch from './AdvancedSearch';
  7 | export default () => {
  8 |   const [loading, setLoading] = useState<boolean>(true);
  9 |   useEffect(() => {
View compiled
__webpack_require__
webpack/bootstrap:774
  771 | };
  772 | 
  773 | // Execute the module function
> 774 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  775 | 
  776 | // Flag the module as loaded
  777 | module.l = true;
View compiled
fn
webpack/bootstrap:129
  126 | 		);
  127 | 		hotCurrentParents = [];
  128 | 	}
> 129 | 	return __webpack_require__(request);
      | ^  130 | };
  131 | var ObjectFactory = function ObjectFactory(name) {
  132 | 	return {
View compiled
fn.t
webpack/bootstrap:173
  170 | 	}
  171 | };
  172 | fn.t = function(value, mode) {
> 173 | 	if (mode & 1) value = fn(value);
      | ^  174 | 	return __webpack_require__.t(value, mode & ~1);
  175 | };
  176 | return fn;
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.`

**Comment by zombieJ** [comment]
v4 版本 Form 不再需要 `Form.create`。请参考迁移文档进行迁移：https://ant.design/docs/react/migration-v4-cn
