### ISSUE TITLE
对于TreeSelect组件，使用异步加载数据的方式，怎么处理默认选中的节点还没有加载进来的情况。

### ISSUE THREAD

**Issue by zhulichao** [ant-design/ant-design#2183]

**Comment by warmhug** [comment]
`默认选中的节点` 怎么不是已经加载好的数据里的某些项？不然不是逻辑有问题？

**Comment by zhulichao** [comment]
是这样一种场景：要选择所在地区，默认是当前操作人的所在地区，在不同地方操作默认显示不同地区，如北京市的西城区，选项中默认加载的就是中国及以下的省份，其他数据使用异步加载方式，点击了才加载。能处理这种情况吗？

**Comment by warmhug** [comment]
更新到 rc-tree-select@1.7.5 ，使用`labelInValue `，参考这里 http://react-component.github.io/tree-select/examples/dynamic.html
