### ISSUE TITLE
 antd table 有可展开子集的时候固定表头出现大量空白 When there are expandable subsets in the ant table, a large number of blanks appear in the fixed header

### ISSUE THREAD

**Issue by gxf0201** [ant-design/ant-design#21845]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
添加进去子行的时候，会出现子行滑动
When a child row is added, it will slide

### What is expected?
1-2 working days

### What is actually happening?
When a child row is added, it will slide

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | react |
| System | 3.26.12 |
| Browser | 3.26.12 |

**Comment by zombieJ** [comment]
你的例子是空的

**Comment by capdiem** [comment]
我也存在这样的问题，不过我本地(windows)开发和部署就不会出现这个问题，发布到线上(linux)后就出现header空白（当table宽度小于`scroll.x`时）的情况。解决办法是不要设置 `scoll.x` 的值。 @gxf0201 

是个BUG吧。
