### ISSUE TITLE
@ant-design/compatible should not show warnings for upgrading

### ISSUE THREAD

**Issue by zmayor** [ant-design/ant-design#21843]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Using `@ant-design/compatible` means I had upgrading the antd from v3 to v4 already. The reason why I add the package is to compatible with the old code I won't rewrite. However, there are to many annoying waring in the console.

### What does the proposed API look like?
No more upgrading warings  for `@ant-design/compatible`

**Comment by zombieJ** [comment]
It's by design. `compatible` is design for transitional phase that developer can replace legacy component step by step following with the warning info. It will not warning in prop mode.
