### ISSUE TITLE
The "autoSize" property cannot be set in Input.TextArea

### ISSUE THREAD

**Issue by wanzhuxuan** [ant-design/ant-design#21841]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/u1x4z)

### Steps to reproduce
点击重现连接->看沙盒的控制台
这里的报错信息和我项目中出现的报错信息是一致的。

### What is expected?
在 Input.TextArea 中正常使用 autoSize 属性；

### What is actually happening?
Input.TextArea 无法设置 autoSize 属性，
无论赋值 对象 还是 布尔值 均会出现报错i信息；

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | latest |
| System | win10 |
| Browser | Chrome latest |

---
我的项目中需要使用 Input.TextArea组件 的 autoSize 属性，
但是运行后发现控制台报错，调了好久无果，就上官网看看，
结果发现官网也报同样的错误。

Warning: Removing a style property during rerender (overflow) when a conflicting property is set (overflowY) can lead to styling bugs. To avoid this, don't mix shorthand and non-shorthand properties for the same value; instead, replace the shorthand with separate values.

第一次提交Issue，希望可以得到解决。
(感谢antd，希望antd变得更好。)

**Comment by zombieJ** [comment]
Duplicate of #21697

**Comment by dongyuwhz** [comment]
解决了么，怎么解决？

**Comment by wangtongbo** [comment]
都2022年了还没解决吗
