### ISSUE TITLE
我想通过tranfer和tree 组件实现下图效果，现在实现遇到问题了

### ISSUE THREAD

**Issue by dreamDX** [ant-design/ant-design#2184]
http://h5cspm.miyapay.com/h5/images/transfer.png  要实现 这个图片链接的效果，看到transfer只有一级的，没有多级展开的demo，请问这个如何实现

**Comment by afc163** [comment]
目前不支持这种用法。

**Comment by dreamDX** [comment]
那如果要实现这个效果，请问我需要自定义tree，还是自定义transfer，还是全部自定义？！

**Comment by warmhug** [comment]
自定义tree 吧，像这样 http://www.ztree.me/v3/demo.php#_308 。若做好了、期待能在 rc-tree 的 [examples](https://github.com/react-component/tree/tree/master/examples) 里提 pr 、增加进去。:)
