### ISSUE TITLE
umi ui not work (run command failed, command ui does not exists.)

### ISSUE THREAD

**Issue by xx-li** [ant-design/ant-design#21842]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/practical-projects-cn](https://ant.design/docs/react/practical-projects-cn)

### Steps to reproduce
$ yarn global add umi
$ umi -v
$ umi ui

### What is expected?
According to the document can start Umi UI。 (umi version is 3.0.2)

### What is actually happening?
run command failed, command ui does not exists.
AssertionError [ERR_ASSERTION]: run command failed, command ui does not exists.
    at /Users/stellar/.config/yarn/global/node_modules/@umijs/core/lib/Service/Service.js:625:29
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/stellar/.config/yarn/global/node_modules/@umijs/core/lib/Service/Service.js:100:103)
    at _next (/Users/stellar/.config/yarn/global/node_modules/@umijs/core/lib/Service/Service.js:102:194)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | mac os 10.15.3 |
| Browser | chrome 80.0.3987.122 |

**Comment by ycjcl868** [comment]
Umi 3 no built-in UI, you could use via [@umijs/preset-ui](https://github.com/umijs/umi-ui#-%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B).

**Comment by afc163** [comment]
@ycjcl868 We need to update our document.

**Comment by ycjcl868** [comment]
OK
