### ISSUE TITLE
UXCore? Join forces?

### ISSUE THREAD

**Issue by kvetoslavnovak** [ant-design/ant-design#2185]
Hi, excelent job. 
Do you know about UXCore project? UXCore is a set of React Components that is designed for enterprise-class pc backend application. It seems to compete with you project, they have got some cool features.
http://uxco.re/components/alert/
https://github.com/uxcore/uxcore

It would be great if you can join your forces and work together. Combination of AntD and UXCore would be great.

**Comment by afc163** [comment]
https://gitter.im/ant-design/ant-design?at=56e54fae0055f8f35a82b8fa
