### ISSUE TITLE
Form.Item组件  labelCol和wrapperCol配置在移动端无效，label和输入框会各占一行

### ISSUE THREAD

**Issue by wangzongming** [ant-design/ant-design#21858]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#API](https://ant.design/components/form-cn/#API)

### Steps to reproduce
                <Form name="dynamic_rule">
                    <Form.Item
                        {...{
                            labelCol: { span: 4 },
                            wrapperCol: { span: 20 },
                        }}
                        name="nickname"
                        label="Nickname" 
                    >
                        <Input placeholder="Please input your nickname" />
                    </Form.Item>

                </Form>

### What is expected?
在小屏幕下这个布局配置也能用

### What is actually happening?
.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8 |
| System | window10 |
| Browser | Chrome 75.0.3770.80（正式版本） （64 位） |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10591

**Comment by zombieJ** [comment]
It's by design. #20836

cc @shaodahong

**Comment by shaodahong** [comment]
Yep, we made label and input item width 100% when screen width less than 575px

**Comment by wangzongming** [comment]
Oh, how sad I am!The Form my component USES is encapsulated, and sometimes a line needs to display two input fields or something like that.The rc version is fine, the official version is broken, you are making the components too inflexible.But I've changed my style.

**Comment by shaodahong** [comment]
I'm sorry about this. If we change display style, It's a breaking change, we need to be consistent with v3

**Comment by wangzongming** [comment]
no. i like v4

**Comment by FelicityGao** [comment]
你这样让我怎么在一行即显示标签又显示输入框？

**Comment by whx76** [comment]
最好有设置可自己决定是否在575以下这样处理,有时是需要同行显示
