### ISSUE TITLE
Calendar这个组件如何根据后台数据自定义日期单元格背景色

### ISSUE THREAD

**Issue by coderhn** [ant-design/ant-design#21852]
业务需求是这样的，需要做一个待办任务工作清单，于是我采用了Calendar这个组件，这个组件的日期单元格默认的背景色是白色的，现在需要根据后台传来的日期以及那天是否存在未完成的任务进行日期单元格背景色设置为红色。具体要求如下图

![问题1](https://user-images.githubusercontent.com/47112336/75853175-83bb1480-5e28-11ea-90aa-05c22889fa3e.png)

**Comment by yumindeckard** [comment]
@coderhn 

你可以用`dateRender`这个prop来传入一个自定义的date cell

具体请看rc-calendar这个库的文档，我猜测antd的文档应该也写了

**Comment by LilyEvans123** [comment]
> 业务需求是这样的，需要做一个待办任务工作清单，于是我采用了Calendar这个组件，这个组件的日期单元格默认的背景色是白色的，现在需要根据后台传来的日期以及那天是否存在未完成的任务进行日期单元格背景色设置为红色。具体要求如下图
> 
> ![问题描述图](https://user-images.githubusercontent.com/47112336/75853877-e52fb300-5e29-11ea-881e-037fe291e328.png)

怎么解决的啊

**Comment by LilyEvans123** [comment]
> rc-calendar

能给个具体链接啥的吗，真不会
