### ISSUE TITLE
active props required  in TreeNodeProps（typescript）

### ISSUE THREAD

**Issue by Dcatfly** [ant-design/ant-design#21853]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-dhawan-2p3rg)

### Steps to reproduce
When I use TreeNode in tsx, it prompts me for the active props, but this is not stated in the documentation.

### What is expected?
No type detection errors here.

### What is actually happening?
```
const TreeNode: React.FunctionComponent<TreeNodeProps>
Property 'active' is missing in type '{ title: string; }' but required in type 'TreeNodeProps'.ts(2741)
TreeNode.d.ts(26, 5): 'active' is declared here.
```

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | mac@10.14.6 |
| Browser | chrome@80 |

---
https://github.com/react-component/tree/pull/298

**Comment by prcdpr** [comment]
I also have this

**Comment by localSummer** [comment]
+1

**Comment by zombieJ** [comment]
Close for https://github.com/react-component/tree/pull/298
