### ISSUE TITLE
antd 4.0 components show page right-Anchor click highlighting is not as expected

### ISSUE THREAD

**Issue by LiDopamine** [ant-design/ant-design#21865]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-multiple-sorter](https://ant.design/components/table-cn/#components-table-demo-multiple-sorter)

### Steps to reproduce
click Anchor , the highlighting always not take effect 
点击右侧锚点，页面发生跳转。但是锚点不高亮，推测原因，锚点定位高于锚点元素不能触发锚点高亮。

### What is expected?
锚点不高亮
Anchor not take effect highlighting

### What is actually happening?
锚点如期高亮
Anchor take effect highlighting

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | -- |
| System | win 10 1909 |
| Browser | chrome 80.0 |

**Comment by afc163** [comment]
没懂，我测试了一下好像没问题。

**Comment by zombieJ** [comment]
<img width="108" alt="截屏2020-03-05下午5 24 56" src="https://user-images.githubusercontent.com/5378891/75967082-3d3be780-5f06-11ea-964b-677fef231460.png">

点击上面那个，再点击下面那个会不高亮。推测是精度有小数的问题。

**Comment by afc163** [comment]
Duplicate of #23929
