### ISSUE TITLE
Select 组件placeholder展示问题

### ISSUE THREAD

**Issue by jiayuu** [ant-design/ant-design#21861]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当Select为受控组件时如何显示出placeholder

### What does the proposed API look like?
value 为null时 显示placeholder

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2367
