### ISSUE TITLE
Table columns align property not working in typescript

### ISSUE THREAD

**Issue by squeaker33** [ant-design/ant-design#21869]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-sea-ivis7)

### Steps to reproduce
In Typescript, use property align in table.columns declaration and pass "center" | "right" | "left" to it

### What is expected?
No error from typescript because "center" | "right" | "left" are strings

### What is actually happening?
typescript error: type 'string' not type of  "center" | "right" | "left" | undefined

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | win7 |
| Browser | google chrome |

---
This is working in js but not in ts so it's a type issue only
In CodeSandbox it display correctly but when all is done loading an error appear on columns attribute of Table component

**Comment by squeaker33** [comment]
The problem seems to be from your use of '_RcColumnType_' from '_rc-table/lib/interface_' in the '_ant-design/components/table/Column.tsx_' file, because the type of align property is define there.

**Comment by zombieJ** [comment]
You should define your `columns` type: https://codesandbox.io/s/frosty-grass-t0g8w

**Comment by squeaker33** [comment]
Yep it works thanks
