### ISSUE TITLE
Print text with italics causes wrong characters in Chrome

### ISSUE THREAD

**Issue by Gervwyk** [ant-design/ant-design#21868]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-print-bug-x50ft)

### Steps to reproduce
Open the sandbox preview in full screen mode then try (cmd p) print in Chrome browser and weird characters show up.

### What is expected?
Just normally print the typography text.

### What is actually happening?
Chrome browser shows weird symbols. Safari prints fine.

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | latest |
| System | macOs 10.15.3 |
| Browser | Chrome 80.0.3987.122 |

---
If the <em> tags is removed from the page, it prints with no-issue.
If the BlinkMacSystemFont is removed from the font-family, it prints with no issue.

See: https://github.com/tailwindcss/tailwindcss/issues/1243

**Comment by zombieJ** [comment]
Seems it's a bug from Chrome. Typography do not have any magic on it. Pls feel free to fire issue to Chromium instead.

Before Chrome fix. Let's quota your research here in case other developer meet this:

> If the tags is removed from the page, it prints with no-issue.
If the BlinkMacSystemFont is removed from the font-family, it prints with no issue.

**Comment by ReDrUm** [comment]
It's definitely a Chrome bug. It's impacting various websites. Did you raise a ticket in the Chromium bug base? I couldn't find one related, so I made this [one](https://bugs.chromium.org/p/chromium/issues/detail?id=1091628). I've used your codesandbox example since it's a perfect test case for reproduction. I hope that's ok :)
