### ISSUE TITLE
Support swapping moment.js with date-fns

### ISSUE THREAD

**Issue by chemicalkosek** [ant-design/ant-design#21866]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Will you be providing support for date-fns the same way you made it for dayjs [https://ant.design/docs/react/replace-moment](https://ant.design/docs/react/replace-moment)

### What does the proposed API look like?
Provide 
```import dateFnsGenerateConfig from 'rc-picker/lib/generate/date-fns';``` 
the same way as dayjs.

**Comment by afc163** [comment]
@zombieJ can we release https://ant.design/docs/react/replace-moment as a npm package (like `@ant-design/antd-dayjs-wrapper`) to simplify the whole process.

**Comment by afc163** [comment]
```jsx
import { TimePicker, DatePicker, Calendar } from 'antd';
import convertor from `@ant-design/antd-date-convertor/dayjs`;

cosnt NewTimePicker = convertor(TimePicker);
cosnt NewDatePicker = convertor(DatePicker);
cosnt NewCalendar = convertor(Calendar);
```

or other API format.

**Comment by zombieJ** [comment]
Current step is simple enough just:
```tsx
const DatePicker = generatePicker<Dayjs>(dayjsGenerateConfig);
const Calendar = generateCalendar<Dayjs>(dayjsGenerateConfig);
```

No need to wrapper another package to handle this wrap. User should always pass an `generate` to covert into their date Component.

**Comment by zombieJ** [comment]
@chemicalkosek, do you have interested to contribute this feature to `rc-picker`?

**Comment by chemicalkosek** [comment]
@zombieJ Sorry, I don't think I'm the best one to do it. I have already look yesterday at the code [here](https://github.com/react-component/picker/blob/master/src/generate/dayjs.ts). 
While I could take a shot on swapping the corresponding dayjs functions with date-fns ones (even though I don't know date-fns yet), I don't really know what's going on there with the 'wo' 'Wo' thing (?) and parseNoMatchNotice. Plus you use TypeScript which I don't know.

### Why Date-Fns and not dayjs?
I have an already in production app which uses a lot of moment.js in loops for the main view (a big gaant like calendar view). It's quite slow on some weaker machines when changing the date range since it has to compute everything allover for the rerender. While I need to refactor the whole app to not use moment.js (moment is slow), I did some digging and it seems like date-fns is faster then dayjs when doing Math on dates. Source: [https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js](https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js).
Although I'm still considering dayjs since there's a lot of parsing too where dayjs is faster than date-fns. 

Some people may want date-fns since it has timezone support. Dayjs doesn't.

**Comment by wendellhu95** [comment]
@wenqi73

**Comment by zombieJ** [comment]
Move to #22732
