### ISSUE TITLE
form表单校验有多个规则情况下能否在第一个校验失败的时候不进行后面的校验，错误信息不显示

### ISSUE THREAD

**Issue by longhuasishen** [ant-design/ant-design#2186]
form表单校验有多个规则情况下能否在第一个校验失败的时候不进行后面的校验，只显示第一个规则的错误信息提示

**Comment by afc163** [comment]
https://github.com/yiminghe/async-validator#options

**Comment by longhuasishen** [comment]
![image](https://cloud.githubusercontent.com/assets/5009662/16380292/c6228466-3ca8-11e6-841f-667ac8cbd388.png)
