### ISSUE TITLE
Firefox - Autosized textarea doesn't scroll as you type

### ISSUE THREAD

**Issue by ElliotAshby** [ant-design/ant-design#21870]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-r25xe?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
-type into the textarea until the scrollbar appears
-continue to type so that new lines should appear

### What is expected?
textarea scrolls down as you type onto new lines

### What is actually happening?
no scrolling occurs

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Firefox 73.0.1 |

**Comment by koechkevin** [comment]
I am facing this warning on the console with autoSized textarea on chrome
<img width="474" alt="Screenshot 2020-03-07 at 13 29 39" src="https://user-images.githubusercontent.com/39160236/76141705-efdf8780-6077-11ea-81ed-56fb47f9a15d.png">

**Comment by afc163** [comment]
broken by https://github.com/ant-design/ant-design/pull/20737/
