### ISSUE TITLE
dropdown doesn't render in expected position if it's rendered in a table and uses getPopupContainer

### ISSUE THREAD

**Issue by RwwL** [ant-design/ant-design#21879]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dropdown-getpopupcontainer-in-table-8yc4g)

### Steps to reproduce
1) Create an Ant Dropdown component using the bottomRight placement prop and the getPopupContainer prop to render the popup in a specified div (in the repro link, this is done in a simple container component called OverflowMenu)
2) Render the Dropdown in each row of a table

### What is expected?
All dropdowns in the table render with the bottom right placement (unless, maybe there isn't room in the browser viewport, if that's a feature of the Dropdown).

### What is actually happening?
Dropdowns in the last three rows of the table render above their trigger button instead of below it, even when there's plenty of room in the browser viewport below the table for the dropdown to render.

Most importantly, this does not happen if you remove the getPopupContainer prop on the dropdown. When that one prop is removed, all dropdowns in the table render according to the placement prop.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | macOS 10.14.6 (18G3020) |
| Browser | Chrome, Firefox, Safari (any) |

---
I strongly prefer to use the getPopupContainer prop for Ant Dropdowns whenever possible because the default implementation of the Dropdown has accessibility issues with keyboard navigation, and using a popup container next to the triggering element improves that.

**Comment by afc163** [comment]
caused by https://github.com/ant-design/ant-design/pull/20705
