### ISSUE TITLE
select component has a css error when its value set to empty string

### ISSUE THREAD

**Issue by sujingclg** [ant-design/ant-design#21871]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/charming-lumiere-l8qvm)

### Steps to reproduce
set select component's value to "", and delete all of option under it.

### What is expected?
align(元素对齐)

### What is actually happening?
not align(元素不能对齐)

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.12.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Aha... 终于知道之前有些样式是干啥的了，重构需要带上。谢谢！

ref: https://github.com/ant-design/ant-design/pull/20538#issuecomment-569695326

**Comment by afc163** [comment]
我也忘了，果然要写注释。
