### ISSUE TITLE
treeNodeLabelProp breaks TreeSelect rendering

### ISSUE THREAD

**Issue by davidlougheed** [ant-design/ant-design#21878]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8przt)

### Steps to reproduce
Set a treeNodeLabelProp to a value other than the default

### What is expected?
Select should show 'title' prop in dropdown, value specified by treeNodeLabelProp in select after selection

### What is actually happening?
Value specified by treeNodeLabelProp is always used

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Ubuntu 18.04 |
| Browser | Firefox 73.0.1 |

**Comment by zombieJ** [comment]
`treeNodeLabelProp` default is `title`. When you change it, TreeSelect will show label as your configured one.

**Comment by davidlougheed** [comment]
@zombieJ in ant 3, title would be used for the content in the drop down and treeNodeLabelProp would be used when the selection was made - is there no way to accomplish that functionality anymore?

**Comment by davidlougheed** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/1823 Here’s a documented example of what it used to do (in this case someone asking for a port of the functionality in the react version to angular)

**Comment by markusmoglich** [comment]
Is there a way to achive the behavior described by @davidlougheed?
I mean something like **selectionLabelProp** or a function to customize it.

**Comment by davidlougheed** [comment]
@markusmoglich yes as far as i know this is still an issue; I'm pretty sure they misinterpreted what I originally said and/or didn't believe me about the regression, which is pretty disappointing
