### ISSUE TITLE
menu 报错

### ISSUE THREAD

**Issue by shenke119** [ant-design/ant-design#2188]
```javascript
import { Menu, Icon } from 'antd';
const SubMenu = Menu.SubMenu;
const MenuItemGroup = Menu.ItemGroup;

const Nav = class Nav extends React.Component {
	constructor(props) {
	    super(props);
	    this.state = {
	    		current:1
	    };
	}
  	render() {
	    return (
	    		<Menu>
	    		</Menu>
	    )
	}
}
```
报错 
warning.js:45Warning: getInitialState was defined on AntMenu, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?
warning.js:45Warning: getInitialState was defined on Menu, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001
