### ISSUE TITLE
分页在小屏幕下增加可自动转为简洁分页api

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#21885]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
分页过长，影响用户体验

### What does the proposed API look like?
可以设置开启或关闭
![Screenshot_2020-03-05-06-58-48-279_com android browser](https://user-images.githubusercontent.com/3166799/75931244-75fca200-5eaf-11ea-95f7-a632f6f8039d.jpg)
![Screenshot_2020-03-05-06-57-07-010_com android chrome](https://user-images.githubusercontent.com/3166799/75931248-77c66580-5eaf-11ea-9da5-7d1fdcc1dcd8.jpg)

**Comment by wendellhu95** [comment]
🙋‍♂️

**Comment by zombieJ** [comment]
@wendellhu95 , sure. Welcome!~
