### ISSUE TITLE
Autocomplete shows value (number) instead of label on selecting an option

### ISSUE THREAD

**Issue by aelkoussy** [ant-design/ant-design#21882]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/why-shown-value-is-number-not-string-3lq2e)

### Steps to reproduce
click on the autocomplete and choose an option

### What is expected?
the selected option should show as label

### What is actually happening?
it shows the numeric value instead of the label 

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | react 16.13.0 |
| System | Mac OS |
| Browser | Chrome |

---
This wasn't happening in Antd v4 , if passing to the autocomplete a datasource with (text, value) pair, like this:
https://codesandbox.io/s/antd-v3-autocomplete-works-well-swtkg

**Comment by zombieJ** [comment]
AutoComplete is an Input component with option list. It shows label in input is a bad design in v3 which makes value not align. In v4, it does work as an Input.

ref #21458

**Comment by 3dw1np** [comment]
Even if it was a bad design in v3, any way to display the text we want instead of the option value?

**Comment by 3dw1np** [comment]
I was able to do what I want with handleSelect(val, option) API.

**Comment by asimnazir** [comment]
> I was able to do what I want with handleSelect(val, option) API.

Can you share the code snippet ?

**Comment by PaulPCIO** [comment]
would be nice if we hard a third property within the options, that could be used as the "value" prop eg a key or id;
```jsx
{
  label:<span>Rich option - {option.name}</span>,  // label used as rich text for the dropdown
  value:option.name, // value used as the selected value within the input
  key:option.uniqueID // key used as the unique identifier (ex value)
}
```

**Comment by EugeneSnihovsky** [comment]
For anyone else faced this problem.
Just use [select component](https://ant.design/components/select) with `showSearch={ true }` attribute.
As I understand after read couple of issues, `Autocomplete` component works as expected and never be fixed.

**Comment by nhanhaloli** [comment]
> For anyone else faced this problem.
> Just use [select component](https://ant.design/components/select) with `showSearch={ true }` attribute.
> As I understand after read couple of issues, `Autocomplete` component works as expected and never be fixed.

Dropdown of select not re-render when data change. I mean when i click to select -> its open dropdown -> i text something and call api -> data change -> dropdown of select not re-render until i close it and open again. Any help with this issue. Thanks

**Comment by tomjohnneill** [comment]
> > For anyone else faced this problem.
> > Just use [select component](https://ant.design/components/select) with `showSearch={ true }` attribute.
> > As I understand after read couple of issues, `Autocomplete` component works as expected and never be fixed.
> 
> Dropdown of select not re-render when data change. I mean when i click to select -> its open dropdown -> i text something and call api -> data change -> dropdown of select not re-render until i close it and open again. Any help with this issue. Thanks


I just had the same issue as you. I fixed it by setting `filterOption={false}`:

```
<Select
  onSelect={handleSelect}
  filterOption={false}
  notFoundContent={null}
  showSearch
  onSearch={handleSearch}
>
  {options}
</Select>

```

**Comment by xseman** [comment]
Use `<Select />` with prop `labelInValue={true}`

**Comment by Zhangyao719** [comment]
// * 可选择、可手动输入的输入框
// * 支持 Form 表单
// * 相比 Antd 的 AutoComplete ，在选中选项时，支持输入框中显示 label 而不是 value。
// * 由 Antd 的 Select + showSearch 搜索框改编而来，重写 input 逻辑，当输入内容不匹配时，不会清空输入框。
// * @see https://4x-ant-design.antgroup.com/components/select-cn/#components-select-demo-search-box

import React, { useState } from 'react';
import { Select } from 'antd';
import debounce from 'lodash/debounce';

/**
 * @typedef {Object} Props
 * @property {string} value 受控的value
 * @property {Function} onChange 提供的 onChange 事件
 * @property {string} placeholder
 * @property {Object} style
 * @property {{ label: string; value: string | number }} options 下拉框选项
 * @param {Props} props
 */
const AutoComplete = ({
    value = '',
    onChange = () => {}, // form 表单接收的值
    placeholder = '',
    options = [],
    style = {},
}) => {
    const [input, setInput] = useState(value);

    // 重写输入逻辑：如果从 options 中匹配到，则返回 value，否则返回输入的值
    const handleInput = debounce(e => {
        const value = e.target.value;
        const selected = options.find(
            item => item.label.toLocaleLowerCase() === value.toLocaleLowerCase()
        );
        if (selected) {
            setInput(selected.label);
            onChange(selected.value);
        } else {
            setInput(value);
            onChange(value);
        }
    }, 500);

    const handleSelect = (value, option) => {
        // 避免重复的 form onChange 事件
        // 场景：输入框手动输入相匹配的值，又在下拉框中选择了该项，此时无需再重复触发
        if (input !== option.label) {
            setInput(option.label);
            onChange(value);
        }
    };

    return (
        <Select
            value={input}
            showSearch
            placeholder={placeholder}
            style={style}
            defaultActiveFirstOption={false}
            showArrow={false}
            notFoundContent={null}
            options={options}
            filterOption={(inputValue, option) => {
                const label = option.label.toLocaleLowerCase();
                const input = inputValue.toLocaleLowerCase();
                return label.indexOf(input) !== -1;
            }}
            onSelect={handleSelect}
            onInput={handleInput}
        />
    );
};

export default AutoComplete;
```js

**Comment by yogithesymbian** [comment]
i use `autocomplete` is for select. data from database or ignore to use the data on typing .
where `Select` doesnt have. this feature . when we typing and didnt select anything . its auto clear the form . not set the value what i typing.

hope you update and fix 
currently i tricky with bad logic . when its on change , i use additional useState to set the id.

**Comment by yogithesymbian** [comment]
> i use `autocomplete` is for select. data from database or ignore to use the data on typing . where `Select` doesnt have. this feature . when we typing and didnt select anything . its auto clear the form . not set the value what i typing.
> 
> hope you update and fix currently i tricky with bad logic . when its on change , i use additional useState to set the id.

engine:
```
"antd": "^5.15.3",
```

**Comment by xXAvoraXx** [comment]
+1
