### ISSUE TITLE
Antd.less is not being overridden when bundling with ParcelJS 

### ISSUE THREAD

**Issue by fredwin-o** [ant-design/ant-design#21884]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/parcel-antd-1z054?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Bundle Antd with ParcelJS.
Create Index.less file
Link to Index.html head

### What is expected?
Default Antd.less should be override by the Index.less file

### What is actually happening?
Index.less is not being adopted.

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Windows |
| Browser | Version 79.0.3945.88 |

**Comment by zombieJ** [comment]
Pls fire issue to ParcelJS instead. It's not an antd issue.
