### ISSUE TITLE
form 表单校验规则的type，设置为any报错

### ISSUE THREAD

**Issue by cc616** [ant-design/ant-design#21881]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blue-water-fri9c)

### Steps to reproduce
直接打开链接，点击submit，可以看见控制台报错

### What is expected?
要么能够正常submit，或者更新文档不支持any

### What is actually happening?
文档中rules规则的type一栏写的是内建校验类型，可选项，后面有个链接点进去是另外一个校验库，上面有个any的类型 ，当我设置type: 'any'时，页面报错

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | 16.13.0 |
| System | macOS |
| Browser | Google Chrome 80.0.3987.87 |

![image](https://user-images.githubusercontent.com/9332135/75899754-e76c2e80-5e76-11ea-91ce-3cfd37aaa0bb.png)
![image](https://user-images.githubusercontent.com/9332135/75899799-f652e100-5e76-11ea-8624-0c5c330c5686.png)
![image](https://user-images.githubusercontent.com/9332135/75899832-01a60c80-5e77-11ea-9279-bcae58a015fd.png)

**Comment by AshoneA** [comment]
Seems field-form should upgrade async-validator package.

**Comment by zombieJ** [comment]
@AshoneA , it's v3 issue which not use `rc-field-form` yet : )

**Comment by zombieJ** [comment]
Hi @cc616 , v3 use `async-validator` v1 which do not support any type. If you want to use any type. Welcome to upgrade antd to  v4 which do support any type.

**Comment by AshoneA** [comment]
> @AshoneA , it's v3 issue which not use `rc-field-form` yet : )

Ignore me...
