### ISSUE TITLE
Table 设置footer,新增行autoFocus,交互有点问题

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#21890]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-eqz50?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
输入框中按回车,会新增一行,当新增行超过窗口高度时,会导致footer不会始终显示.

### What is expected?
footer部分一直显示

### What is actually happening?
footer部分 每次新增行会 先显示, 再次新增行 "隐藏" 反复循环.

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16 |
| System | win10 |
| Browser | chrome |

**Comment by l745230** [comment]
这个使用场景下,footer与summary 都无法固定显示.
但是在codesandbox中,偶尔操作的时候,新增行footer与summary会始终显示. 多按一会回车后才会被挤掉.

**Comment by zombieJ** [comment]
`autoFocus` 属性只是保证元素创建后获得焦点。游览器在元素获取焦点后会让获取焦点的元素显示在页面上。这和 footer 没有关系。如果你需要添加一行后同时还要显示其他元素，需要自己实现滚动逻辑来滚动到对应位置。
