### ISSUE TITLE
发现表单校验的一个问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2189]
我校验长度结果发现只输入空格也是可以的，比如以下对输入框的校验代码
const nameProps = getFieldProps('name', {
      rules: [
        { required: true, min: 5, message: '用户名至少为 5 个字符' },
      ],
    });

我在输入框直接打5个空格也可以校验通过

**Comment by wengcd** [comment]
试试这个
`{ required: true, min: 5 , whitespace: true, message: '用户名至少为 5 个字符' }`
