### ISSUE TITLE
Table columns中dateIndex无法指向二级属性

### ISSUE THREAD

**Issue by vVvlife** [ant-design/ant-design#21891]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-kirch-gg3uf)

### Steps to reproduce
1.在columns中加入一个属性
{
    title: "UserName",
    dataIndex: "info.username",
    key: "name",
    render: text => <a>{text}</a>
  }
2.在data中每一个属性都加上info
    info: {
      username: "Jack"
    }

### What is expected?
希望UserName那一列出现数据

### What is actually happening?
结果为空

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Linux Ubuntu 18.04 （64 位） |
| Browser | Chromium 80.0.3987.87（正式版本）Built on Ubuntu , running on Ubuntu 18.04 （64 位） |

---
在3.26.12版本是可以实现的,但是在4.0.x版本以上就无法获取数据

**Comment by AshoneA** [comment]
用 `dataIndex: ["info" , "username"]` 代替

**Comment by vVvlife** [comment]
> 用 `dataIndex: ["info" , "username"]` 代替

谢谢!翻了一些更新日志看到

**Comment by gebilaoman** [comment]
感觉是一个很坑的更新，为什么这次的更新不兼容之前的路径法，差评～

**Comment by yoyo837** [comment]
> 感觉是一个很坑的更新，为什么这次的更新不兼容之前的路径法，差评～

好像是因为兼容无法解决一些其他场景，具体啥忘记了。

**Comment by AshoneA** [comment]
@gebilaoman @yoyo837 是之前如果 field 里面包含了 `.` 的情况，在 v3 上面无法兼容。
