### ISSUE TITLE
Warning raised by ant design icon wrapper into a tooltip component[4.0.0]

### ISSUE THREAD

**Issue by xuzhaogit** [ant-design/ant-design#21892]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
```
import React from "react";
import ReactDOM from "react-dom";
import { Tooltip } from "antd";
import "antd/dist/antd.css";
import "./index.css";
import { createFromIconfontCN } from '@ant-design/icons';

const IconFont = createFromIconfontCN({
  scriptUrl: '//at.alicdn.com/t/font_853185_ie2se111k1.js',
});

ReactDOM.render( <div className="App">
    <span>test</span>
    <div>
    <Tooltip title="test"><IconFont  type="lab-icon-baocun" /></Tooltip>
    </div>
  </div>,
  document.getElementById("root")
);

```

### What is expected?
no error

### What is actually happening?
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react 16.13.0 |
| System | macOs 10.14.6 |
| Browser |  chrome 80.0.3987.122 |

**Comment by devuxer** [comment]
I'm seeing the exact same error when I wrap a radio button with a tooltip. Didn't cause an error with 3.x.

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Trigger`.
    in RadioButton (at ScheduleTable.tsx:294)
    in Trigger (created by ForwardRef(Tooltip))
    in ForwardRef(Tooltip) (created by Context.Consumer)
    in Tooltip (at ScheduleTable.tsx:293)
    in div (created by Context.Consumer)
    in RadioGroup (at ScheduleTable.tsx:289)
    // etc...

**Comment by amiram** [comment]
It happened to me with title and icon
```
<Tooltip title={'some title'}
                placement={'bottomLeft'}>
                <Title level={4}>
                    {this.props.name}&nbsp;
                    <CloseCircleOutlined title="Disconnect"
                        onClick={() => this.props.onDiconnect()}/>
                </Title>
            </Tooltip>
```

**Comment by zombieJ** [comment]
Merge into #21921

**Comment by StallionV** [comment]
Can you confirm when will this fix be available. Still see the warning in latest Ant build V4.1.1

**Comment by yoyo837** [comment]
@StallionV  If you still have problems, please use https://new-issue.ant.design/ to open a new issue for tracking.

**Comment by StallionV** [comment]
@yoyo837 I will raise it but I am trying to first find out if this issue was fixed and if so in what version.
I am still seeing it in 4.1.1 so want to be sure.

**Comment by gino8080** [comment]
I got the same warning on 4.1.5

**Comment by StallionV** [comment]
Yes the problem is still there. I am not sure how the tooltip code has been fixed, but we seem to get it if we use `Ref` or any icons consisting of `SVGs` inside `tooltip`
e.g.
```
<Tooltip ...>
 <Element with SVG or ref >
</Tooltip>
```

The only way to avoid this currently is to wrap it in empty tags
```
<Tooltip ...>
 <><Element with SVG or ref ></>
</Tooltip>
```

So `Tooltip` surely still needs a fix

**Comment by espallargas** [comment]
Still having the same issue on `4.2.0` . And even adding a `Fragment` as suggested by @StallionV does not suppress the warning for me.

Here is my code:
```tsx
<Tooltip
  placement="top"
  title="xxx"
>
  <>
    <Icon
      onClick={onClick}
      data-testid={testId}
    />
  </>
</Tooltip>
```
I don't know if this could affect it, but I am using a `<ConfigProvider getPopupContainer={myExternalContainerFunction}>` wrapping this code.

**Comment by StallionV** [comment]
> Still having the same issue on `4.2.0` . And even adding a `Fragment` as suggested by @StallionV does not suppress the warning for me.
> 
> Here is my code:
> 
> ```tsx
> <Tooltip
>   placement="top"
>   title="xxx"
> >
>   <>
>     <Icon
>       onClick={onClick}
>       data-testid={testId}
>     />
>   </>
> </Tooltip>
> ```
> 
> I don't know if this could affect it, but I am using a `<ConfigProvider getPopupContainer={myExternalContainerFunction}>` wrapping this code.

@espallargas use `<span>` instead of fragment `<>` it should work

**Comment by espallargas** [comment]
> > Still having the same issue on `4.2.0` . And even adding a `Fragment` as suggested by @StallionV does not suppress the warning for me.
> > Here is my code:
> > ```tsx
> > <Tooltip
> >   placement="top"
> >   title="xxx"
> > >
> >   <>
> >     <Icon
> >       onClick={onClick}
> >       data-testid={testId}
> >     />
> >   </>
> > </Tooltip>
> > ```
> > 
> > 
> > I don't know if this could affect it, but I am using a `<ConfigProvider getPopupContainer={myExternalContainerFunction}>` wrapping this code.
> 
> @espallargas use `<span>` instead of fragment `<>` it should work

Unfortunately, it didn't.

**Comment by StallionV** [comment]
@espallargas can you create a reproduction link in code sandbox may be can take a peak

**Comment by mackonen-netigate** [comment]
> Yes the problem is still there. I am not sure how the tooltip code has been fixed, but we seem to get it if we use `Ref` or any icons consisting of `SVGs` inside `tooltip`
> e.g.
> 
> ```
> <Tooltip ...>
>  <Element with SVG or ref >
> </Tooltip>
> ```
> 
> The only way to avoid this currently is to wrap it in empty tags
> 
> ```
> <Tooltip ...>
>  <span><Element with SVG or ref ></span >
> </Tooltip>
> ```
> 
> So `Tooltip` surely still needs a fix

I believe <Popover> SVG Element </Popover> also behaves similar but seems to work with wrapping a span as you suggested!
