### ISSUE TITLE
Opening the drawer and then opening a modal.When the modal is closed,the scroll bar disappears.先开一个drawer再开一个modal，modal关闭时，页面滚动条消失

### ISSUE THREAD

**Issue by racargx** [ant-design/ant-design#21894]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7bh8l)

### Steps to reproduce
1.click ‘Open’
2.click ‘Open Modal’
3. close modal
4. scroll bar disappears

### What is expected?
scroll bar exists

### What is actually happening?
scroll bar disappears

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.4.1 |
| System | windows |
| Browser | chrome 73.0.3683.75 |

---
现在的业务需求没法升级到antd4.0，希望能在3.X版本上解决这个问题

**Comment by afc163** [comment]
@shaodahong 

Similar issues:

- https://github.com/ant-design/ant-design/issues/20022
- https://github.com/ant-design/ant-design/issues/21539

**Comment by epx-nathan** [comment]
I'm also experiencing this issue in our code base, which uses a lot of drawers + nested modals. I've attempted various workarounds but the various settings of `overflow: hidden` are very persistent. Happy to provide screenshots / videos of the behavior, if that would be helpful! Would love to have this resolved.

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/issues/24821

**Comment by jljsj33** [comment]
我日，不要把问题搞混了，，这是两个问题....

**Comment by jljsj33** [comment]
https://github.com/ant-design/ant-design/issues/21539
