### ISSUE TITLE
Table.Column component can not  render correctly when dataSource were updated

### ISSUE THREAD

**Issue by xuzhaogit** [ant-design/ant-design#21893]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-p3sp2)

### Steps to reproduce
```
import React from "react";
import ReactDOM from "react-dom";
import { Table,Button } from "antd";
import "antd/dist/antd.css";
import "./index.css";


class Demo extends React.PureComponent{
  constructor() {
    super();
    this.state = {
      tableData: [
        {
          name: 'Tom',
          age: 12,
        },
        {
          name: 'Alice',
          age: 13,
        },
      ],
    }
  }

  callbackMode = (text,record)=>{
    return record.age
  }
  edit = ()=>{
    let newData = this.state.tableData.slice()
    newData[0].age =1
    this.setState({tableData:newData})
  }

  render(){
    return (
      <div>
      <Button onClick={this.edit}>editData</Button>
      <Table dataSource={this.state.tableData}>
        <Table.Column title="名字" dataIndex="name" render={(text,record)=>{
          return text
        }}/>
        
              
        <Table.Column title="年龄" dataIndex="age" render={(text,record)=>{
          return text
        }}/>
              
        <Table.Column title="action"  render={this.callbackMode}/>
        <Table.Column title="action2"  render={(text,record)=>{
    return record.age
  }}/>
      </Table>
    </div>
    );
  }
}





ReactDOM.render(
  <Demo/>,
  document.getElementById("root")
);
```

1.click "editData" button

### What is expected?
render correctly

### What is actually happening?
action column can not render

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | react 16.13.0 |
| System | macOs 10.14.6 |
| Browser |  chrome 80.0.3987.122 |

**Comment by afc163** [comment]
```diff
- newData[0.age += 1;
+ newData[0] = {
+   ...newData[0],
+   age: 1,
+ };
```

https://codesandbox.io/s/antd-reproduction-template-ywpz1

**Comment by xuzhaogit** [comment]
> ```diff
> - newData[0.age += 1;
> + newData[0] = {
> +   ...newData[0],
> +   age: 1,
> + };
> ```
> 
> https://codesandbox.io/s/antd-reproduction-template-ywpz1

It works, but why action2 column can works, and the same code works fine with antd 3.x.

**Comment by afc163** [comment]
@zombieJ Should we be compitable with 3.x?

**Comment by afc163** [comment]
same as https://github.com/ant-design/ant-design/issues/21573#issuecomment-594310546

**Comment by zombieJ** [comment]
Noop. Origin Table has render perf issue that parent update cause Table fully update even data is same. We should not fallback to the low perf to compitable with un-standard usage case.

**Comment by afc163** [comment]
Then we should record it as a breaking change in changelog and migrate manual.

**Comment by jeft224** [comment]
@xuzhaogit  问题解决了吗？

**Comment by jailsonpaca** [comment]
I solve this problem with this tool: https://stackoverflow.com/questions/46240647/react-how-to-force-a-function-component-to-render
