### ISSUE TITLE
markdown编辑器

### ISSUE THREAD

**Issue by transtone** [ant-design/ant-design#219]
可以把markdown编辑器加入后期计划吗？
editor.md，github的编辑器，codding.net的编辑器，知乎的编辑器都不错，好歹也参考一个吧。

**Comment by transtone** [comment]
好吧，又被无视了。哪怕把这个：http://jrm2k6.github.io/react-markdown-editor/
功能改强大一点也好呀。

**Comment by afc163** [comment]
我们目前暂时没有这个需求，可以自行封装或直接使用业界的优秀组件。

**Comment by transtone** [comment]
蚂蚁金服难道不用在线编辑器的吗？你们用的是开源的吗，推荐一个？
