### ISSUE TITLE
antd v3->v4 升级后表单异常

### ISSUE THREAD

**Issue by lovekonakona** [ant-design/ant-design#21903]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-nvszm)

## 使用codemod-v4升级了业务代码之后，所有表单样式异常

我使用codesandbox创建了相同的业务代码，使用不同版本的antd中的Form

其中使用@ant-design/compatible的表单样式存在异常

（请拉宽页面，不要触发@media中的样式）

### What is expected?
升级后的表单样式正常

### What is actually happening?
升级后的表单样式异常

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Mac OS Mojave |
| Browser | Chrome 80 |

**Comment by zombieJ** [comment]
@shaodahong , Could you pls help to take a look?

**Comment by xuzhaogit** [comment]
同样遇到这个问题  @ant-design/compatible 引入的form 样式与3.x版本样式不同，并且如果用户重写过某些antd的样式同样会导致失效，怀疑是className变化？

**Comment by shaodahong** [comment]
> 同样遇到这个问题 @ant-design/compatible 引入的form 样式与3.x版本样式不同，并且如果用户重写过某些antd的样式同样会导致失效，怀疑是className变化？

如果重写确实可能会导致失效，`@ant-design/compatible` 中的 form 统一加上了 `legacy-*` 前缀

**Comment by wufeng87** [comment]
> > 同样遇到这个问题 @ant-design/compatible 引入的form 样式与3.x版本样式不同，并且如果用户重写过某些antd的样式同样会导致失效，怀疑是className变化？
> 
> 如果重写确实可能会导致失效，`@ant-design/compatible` 中的 form 统一加上了 `legacy-*` 前缀

@shaodahong 请问下，这个是需要改重写过form的样式吗？也统一加上legacy？

**Comment by shaodahong** [comment]
> 请问下，这个是需要改重写过form的样式吗？也统一加上legacy？

@wufeng87 是的，可以通过 Devtool 观察下 *Element*
