### ISSUE TITLE
Component Select dropdownMatchSelectWidth prop not working properly 

### ISSUE THREAD

**Issue by guilhermevdm** [ant-design/ant-design#21908]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-dropdownmatchselectwidth-not-working-0vsln)

### Steps to reproduce
set Select prop dropdownMatchSelectWidth to false

### What is expected?
dropdown's width not match with select.

### What is actually happening?
dropdown's width still matches with select

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13 |
| System | Windows 10 Home Single Language version 1903 build 18362.657 |
| Browser | Versão 80.0.3987.122 (Versão oficial) 64 bits |

---
dropdownMatchSelectWidth type is supposed to be boolean but is showing "number | true"

**Comment by guilhermevdm** [comment]
Sorry, did not give proper attention to the migration guide.
> Tree, Select, TreeSelect, AutoComplete rewrite
> 
> - use virtual scrolling.
> - 
> - onBlur no longer trigger value change.
> - 
> - dropdownMatchSelectWidth no longer automatically adapts to the content width, please set the dropdown width with numbers.
> - 
> - AutoComplete no longer support optionLabelProp. Please set Option value directly.

**Comment by subrato-pattanaik** [comment]
@demoraesgui I am not able to find the [migration guide](https://ant.design/docs/react/migration-v4#Component-refactoring) for `dropdownMatchSelectWidth` prop.

**Comment by xcatliu** [comment]
Set `virtual={false}` may solve this problem.
