### ISSUE TITLE
Disabled button does not go back to clickable when field values are erased

### ISSUE THREAD

**Issue by Bradly-kunthrope** [ant-design/ant-design#21904]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-gjmjp?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Fill up both username and password fields.
2. Click Next button.
3. Empty up either username or password field completely by deleting them.
4. Clicking the next button again will disable the button (since both fields should be required)
5. Type anything on the empty field. The disabled button will not go back to clickable again

### What is expected?
After filling up all the fields again, the disabled button should go back to its clickable state.

### What is actually happening?
The button is forever disabled once the field is empty after clicking,

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Google Chrome |

---
I'm updating my multi-step form's code to accommodate the latest version of ant design.

**Comment by Bradly-kunthrope** [comment]
Any update on this? Thanks.

**Comment by zombieJ** [comment]
close for https://github.com/react-component/field-form/commit/6ab530fdafada18d8e1505af8ecbc16800f142d0
