### ISSUE TITLE
DatePicker - Wrong dates when changing the first day of week 

### ISSUE THREAD

**Issue by leclercb** [ant-design/ant-design#21906]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-sjuv0)

### Steps to reproduce
Change the first day of week in moment:

    moment.updateLocale('en', {
        week: {
            dow: settings.firstDayOfWeek || 0
        }
    });

Then open a date picker, the dates are incorrect (wrong day of week).
Look at: http://torsten.bplaced.net/taskunifier/first-day-of-the-week.png

### What is expected?
The dates to be correct when changing the first day of week.

### What is actually happening?
The dates are incorrect (wrong day of week).
Look at: http://torsten.bplaced.net/taskunifier/first-day-of-the-week.png
(with ant design v3 it works)

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | Linux |
| Browser | Firefox 68.4.1esr (64-bit) |

**Comment by fwtcumt** [comment]
插楼提一个建议，像日期选择这样的控件，当有清除图标时，点击清除按钮，把值清除就行了，别再把下拉框打开吧。我大可能是想清除不再选择了，这样没有预料的打开，老是吓我一跳，还让我多了一步在其他地方点击一下才关闭。

**Comment by wendellhu95** [comment]
> 插楼提一个建议，像日期选择这样的控件，当有清除图标时，点击清除按钮，把值清除就行了，别再把下拉框打开吧。我大可能是想清除不再选择了，这样没有预料的打开，老是吓我一跳，还让我多了一步在其他地方点击一下才关闭。

这个建议单独开一个 issue 进行讨论和追踪。

**Comment by wendellhu95** [comment]
这个 issue 我可以帮忙，Angular 那边要上修改周首日的功能。 @zombieJ

**Comment by afc163** [comment]
@fwtcumt 确实和 3.x 的表现不一致了，单独开一个 issue 吧。

**Comment by ebru** [comment]
I'm having the same issue with v4, is there any chance to fix it in 4.0.3?

**Comment by leclercb** [comment]
Thanks thnt for making the changes.

Can this be merged ?
The problem is annoying and having the incorrect date/day is very error prone for users.

Thanks in advance !

**Comment by chemicalkosek** [comment]
Is this also fixed for days generate config?
