### ISSUE TITLE
Table如何进行cell编辑？

### ISSUE THREAD

**Issue by JZHculver** [ant-design/ant-design#2191]
RT
有么有现成的例子之类的
可以根据Column的某项属性动态的去向cell中添加组件

如：双击cell的时候cell变为input组件

**Comment by benjycui** [comment]
研究下下面的例子？

https://github.com/ant-design/ant-design/tree/design-pattern/docs/pattern/table/demo

**Comment by JZHculver** [comment]
@benjycui  学习了  十分感谢
