### ISSUE TITLE
表格expandable启用以后  expandIconAsCell失效

### ISSUE THREAD

**Issue by codeManage** [ant-design/ant-design#21913]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
1

### What is expected?
恢复expandIconAsCell

### What is actually happening?
expandIconAsCell失效

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.9 |
| System | mac |
| Browser |  80.0.3987.122（正式版本） （64 位） |

**Comment by zombieJ** [comment]
`expandIconAsCell` 不是官网文档提供的属性，在 v4 版本中没有透出。需要在迁移文档里提一下。

https://github.com/react-component/table/blob/9b0f79059c3d27546e7eaaf56ecb4eacccea2c31/src/Table.tsx#L12

**Comment by delyanr** [comment]
@zombieJ Is there a way to mimic the `expandIconAsCell={false}` functionality in ant-design v4? I have tables that use that in various cases and I'm trying to migrate to the new version. Thanks!

**Comment by EthanOrange** [comment]
是否考虑拉回这个属性💭
尝试升级到4.x的过程中
这个问题好难搞
![image](https://user-images.githubusercontent.com/7098719/78639097-f3b53280-78df-11ea-9e8f-6676c40ba018.png)

**Comment by delyanr** [comment]
I fixed it temporarily using css/less:

```css
.ant-table-row-expand-icon-cell {
  display: none;
}
```

However, I do believe bringing back the `expandIconAsCell` prop is the better option here.

**Comment by afc163** [comment]
Duplicate of #26021
