### ISSUE TITLE
How can I [stopPropagation] the click event of the modal/如何阻止点击modal或modal的遮罩导致的事件传播

### ISSUE THREAD

**Issue by sunyum** [ant-design/ant-design#21910]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/modelevent?embed=1&file=index.js](https://stackblitz.com/edit/modelevent?embed=1&file=index.js)

### Steps to reproduce
1. 点击按钮弹出modal
2. 点击modal或其阴影遮罩
3. 会触发外层div的点击事件且无法阻止

### What is expected?
可以让 modal 阻止事件冒泡

### What is actually happening?
点击modal获阴影遮罩，无法阻止触发外层div的点击事件

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13 |
| System | win10 |
| Browser | chrome最新版 |

**Comment by sunyum** [comment]
解决了，脑子有点短路，给Modal外再包个div，然后在此div中阻止事件冒泡就行了

**Comment by zombieJ** [comment]
哈哈，刚想说你的例子不是阻止了嘛。 。 。
