### ISSUE TITLE
Popover如果浮层渲染在父节点，当有滚动条时，点击打开在文档中间位置的popover时滚动条会滚动到顶部

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#21918]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/broken-mountain-lp0nv)

### Steps to reproduce
打开modal，点击Click me，滚动条会滚到顶部

### What is expected?
滚动条不动

### What is actually happening?
点击popover，滚动条会自动滚到顶部

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.12 |
| System | windows10 |
| Browser | chrome80 |

---
当查看popover的信息时，因为滚动到顶部，就看不到了

**Comment by AshoneA** [comment]
去掉 popover props 中的 `getPopupContainer={trigger => trigger.parentNode}` 试试

**Comment by zhangzhi93** [comment]
> 去掉 popover props 中的 `getPopupContainer={trigger => trigger.parentNode}` 试试

但是我还需要popover滚动跟随

**Comment by AshoneA** [comment]
Use `getPopupContainer={trigger => trigger}`.

**Comment by zhangzhi93** [comment]
> Use `getPopupContainer={trigger => trigger}`.

popover可以了！但是popover里面的select展示不开了，并且select我也想跟随滚动

**Comment by AshoneA** [comment]
对 Select 也用 `getPopupContainer={trigger => trigger}`.

**Comment by zhangzhi93** [comment]
> 对 Select 也用 `getPopupContainer={trigger => trigger}`.

![image](https://user-images.githubusercontent.com/16435301/76045415-f26ab000-5f97-11ea-9a3a-f4d587a1dbda.png)
也是显示不开

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F

#3487 #3438

**Comment by zhangzhi93** [comment]
> https://ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F
> 
> #3487 #3438

我这个demo，用trigger.parentNode会使滚动条自动滚到顶部，不是trigger.parentNode的原因~

**Comment by AshoneA** [comment]
@zhangzhi93 把 Modal 内容区域高度调高一点。

**Comment by zhangzhi93** [comment]
> @zhangzhi93 把 Modal 内容区域高度调高一点。

和modal高度没关系吧，我找找合适的节点放select吧，popover用```getPopupContainer={trigger => trigger}```是可以了
