### ISSUE TITLE
Icon not centered in horizontal menu item

### ISSUE THREAD

**Issue by AlephOfosev** [ant-design/ant-design#21917]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/AlephOfosev/live/abOLQdN](https://codepen.io/AlephOfosev/live/abOLQdN)

### Steps to reproduce
In a horizontal menu, create a menu item containing only an icon.

The code provided in CodePen is simply the first example provided for Menu component on Ant Design site: https://ant.design/components/menu/
where the text of the first menu item was removed (line 27 removed).

### What is expected?
Icon centered relatively to menu item, notably relatively to bar underlining active menu item when selected.

### What is actually happening?
The icon is not centered, as it has a 10 px margin to its right (see first "mail" icon in the CodePen example).

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 79 |

---
The 10px margin-right seems to come from ".ant-menu-item .anticon" selector in css/less.

This makes sense when there is text to its right, but not when there is nothing to the right of the icon.

**Comment by zombieJ** [comment]
Nice catch. Thanks for feedback.

**Comment by Terkea** [comment]
For the current time to solve that I added 10px marginLeft

**Comment by anjanvb** [comment]
Looks like this is still an issue.

<img width="284" alt="Screen Shot 2022-04-10 at 1 42 39 AM" src="https://user-images.githubusercontent.com/84933469/162610130-376d9b4b-44cb-42c3-b3f8-a7f056b99ee2.png">
.
