### ISSUE TITLE
Seems use Tooltip  in every function component without forwardRef report error

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#21921]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/21892](https://github.com/ant-design/ant-design/issues/21892)

### Steps to reproduce
Should we add `forwardRef` in exposing to the user function component? Or more attention this in the code review?

### What is expected?
No error need.

### What is actually happening?
Error always in Tooltip.

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16 |
| System | macos |
| Browser | chrome |

**Comment by zombieJ** [comment]
可以优化一下 `rc-trigger`，不是所有场景都需要用到子元素的 ref：https://github.com/react-component/trigger/blob/9913515e8468669ed673e736de26f3d5568fda3c/src/index.tsx#L784

**Comment by AshoneA** [comment]
嗯，这样感觉比较好。不然对用户来说非 antd 的 function component 也需要实现 forwardRef， 我先去看下 `rc-trigger` ~

**Comment by atzcl** [comment]
这是修复了还是？我在 v4.0.2 中依然存在这个问题

**Comment by yoyo837** [comment]
我看了下，v4.0.2应该包含了 react-component/trigger#174 ， 如果你还有问题，提供个复现。

**Comment by Bonnie8ni** [comment]
我在 v4.2.5 中依然存在这个问题

```
<Popconfirm>
   <TooltipButton>
     <Button icon={<DeleteOutlined />} />
   </TooltipButton>
</Popconfirm>
```

**Comment by yuxuan** [comment]
v4.3.3 依然有这个问题
