### ISSUE TITLE
upload上传框隐藏

### ISSUE THREAD

**Issue by yayamommy** [ant-design/ant-design#2192]
https://github.com/ant-design/ant-design/issues/1610

这个issue里面提供了隐藏上传按钮的方法，能把那个灰色的框也隐藏掉吗？

**Comment by ddcat1115** [comment]
每太明白，具体指哪个灰色的框？用 #1610 里提到的方法也不行？

麻烦提供下demo   http://codepen.io/anon/pen/wGOWGW?editors=001 
或截图说明下

**Comment by afc163** [comment]
#1610 应该足够解决问题了，没进一步反馈先关了。
