### ISSUE TITLE
EditableTable Component Table TS type mismatch

### ISSUE THREAD

**Issue by LbhFront-end** [ant-design/ant-design#21929]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/table-component-ts-cr0cb)

### Steps to reproduce
1.copy doc demo from https://ant.design/components/table-cn/#components-table-demo-edit-row

2.App.tsx
```tsx
    <Form form={form} component={false}>
      <Table
        components={components}
        bordered
        dataSource={data}
        columns={mergedColumns}
        rowClassName="editable-row"
        pagination={{
          onChange: cancel
        }}
      />
    </Form>
```

### What is expected?
eslint error 0

### What is actually happening?
(JSX attribute) components?: TableComponents<any> | undefined
不能将类型“{ body: { cell: ({ editing, dataIndex, title, inputType, record, index, children, ...restProps }: { [x: string]: any; editing: any; dataIndex: any; title: any; inputType: any; record: any; index: any; children: any; }) => Element; }; }”分配给类型“TableComponents<any>”。
  属性“body”的类型不兼容。
    不能将类型“{ cell: ({ editing, dataIndex, title, inputType, record, index, children, ...restProps }: { [x: string]: any; editing: any; dataIndex: any; title: any; inputType: any; record: any; index: any; children: any; }) => Element; }”分配给类型“{ wrapper?: "object" | "title" | "form" | "data" | "address" | "a" | "abbr" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | ... 100 more ... | undefined; row?: "object" | ... 117 more ... | undefined; cell?: "object" | ... 117 more ... | undefined; } | Custom...”。
      不能将类型“{ cell: ({ editing, dataIndex, title, inputType, record, index, children, ...restProps }: { [x: string]: any; editing: any; dataIndex: any; title: any; inputType: any; record: any; index: any; children: any; }) => Element; }”分配给类型“{ wrapper?: "object" | "title" | "form" | "data" | "address" | "a" | "abbr" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | ... 99 more ... | undefined; row?: "object" | ... 117 more ... | undefined; cell?: "object" | ... 117 more ... | undefined; }”。
        属性“cell”的类型不兼容。
          不能将类型“({ editing, dataIndex, title, inputType, record, index, children, ...restProps }: { [x: string]: any; editing: any; dataIndex: any; title: any; inputType: any; record: any; index: any; children: any; }) => Element”分配给类型“"object" | "title" | "form" | "data" | "address" | "a" | "abbr" | "area" | "article" | "aside" | "audio" | "b" | "base" | "bdi" | "bdo" | "big" | "blockquote" | "body" | "br" | "button" | ... 98 more ... | undefined”。
            不能将类型“({ editing, dataIndex, title, inputType, record, index, children, ...restProps }: { [x: string]: any; editing: any; dataIndex: any; title: any; inputType: any; record: any; index: any; children: any; }) => Element”分配给类型“FunctionComponent<HTMLAttributes<HTMLElement>>”。
              参数“__0”和“props” 的类型不兼容。
                Type 'HTMLAttributes<HTMLElement> & { children?: ReactNode; }' is missing the following properties from type '{ [x: string]: any; editing: any; dataIndex: any; title: any; inputType: any; record: any; index: any; children: any; }': editing, dataIndex, inputType, record, indexts(2322)
Table.d.ts(51, 5): The expected type comes from property 'components' which is declared here on type 'IntrinsicAttributes & Pick<TableProps<any>, "title" | "children" | "footer" | "style" | "summary" | "onChange" | "size" | "className" | "id" | "prefixCls" | "columns" | "scroll" | ... 27 more ... | "sortDirections"> & Partial<...> & Partial<...>'

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | react |
| System | window7 |
| Browser | Google Chrome 79.0.3945.130（64 位） |

---
I first found this eslint error in my own code,but it happend when i copy doc code in codesandbox.How can i fix it?

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/21931#issuecomment-595619197

**Comment by LbhFront-end** [comment]
> [#21931 (comment)](https://github.com/ant-design/ant-design/pull/21931#issuecomment-595619197)

thank you.And the address is the same address.

https://codesandbox.io/s/table-component-ts-cr0cb

i follow pr change my code,and still show eslint error.i don't kown where i miss change cause the error

**Comment by zombieJ** [comment]
移除了 components 的 Props 定义要求，避免用户还需要额外填 generic。
