### ISSUE TITLE
Form.useForm 能否返回同一个实例

### ISSUE THREAD

**Issue by soulcm** [ant-design/ant-design#21924]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codesandbox.io/s/silly-sun-mq7ir  

在demo中，如果不返回相同的实例，effect在每次setState时都会执行，因为依赖中加了form（按React要求，也应该加上）。这样导致其他state更新，都会进入到effect中

### What does the proposed API look like?
Form.useForm能返回相同的实例

**Comment by xwg2015** [comment]
@soulcm 你好 请教个问题 4.0更新后 使用form第一次正常 第二次再打开modal中的form就提示Warning: Instance created by `useForm` is not connect to any Form element. Forget to pass `form` prop?  请问是为什么？
