### ISSUE TITLE
Form组件onFieldsChange 和 fields结合使用时，输入时候会出现卡顿

### ISSUE THREAD

**Issue by jclegendary** [ant-design/ant-design#21923]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://rc-field-form.react-component.now.sh/?path=/story/rc-field-form--redux](https://rc-field-form.react-component.now.sh/?path=/story/rc-field-form--redux)

### Steps to reproduce
快速输入required表单

### What is expected?
快速输入时不应该出现流畅

### What is actually happening?
快速输入时input框的内容出现了卡顿

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | react16.3 |
| System | window |
| Browser | chrome |

**Comment by zombieJ** [comment]
ref #21904

**Comment by l745230** [comment]
我也遇到类似的情况,某些时候操作突然输入非常卡顿,
但是在codesandbox中始终无法重现出来.

**Comment by zombieJ** [comment]
Storybook 是 iframe 展示，点击去看单页是好的：
https://rc-field-form.react-component.now.sh/iframe.html?id=rc-field-form--redux
