### ISSUE TITLE
Form组件onFieldsChange 和 fields结合使用时，errors属性始终为空数组。

### ISSUE THREAD

**Issue by jclegendary** [ant-design/ant-design#21922]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-global-state](https://ant.design/components/form-cn/#components-form-demo-global-state)

### Steps to reproduce
删除Username表单所有内容

### What is expected?
应该出现必填提示

### What is actually happening?
但没有出现必填提示

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | react16 |
| System | window |
| Browser | chorm |

**Comment by zombieJ** [comment]
ref #21904
