### ISSUE TITLE
formitem设置多个校验规则，如何设置为顺序校验，出错中断？

### ISSUE THREAD

**Issue by SilentTiger** [ant-design/ant-design#2193]
`
const positionNameProps = getFieldProps('positionName', {

    rules: [
        { required: true, message: '职位名称不可以留空哦' },
        { max: 9, message: '你写的职位名称太长咯' },
        {
            validator: function (rule, value, callback) {
                superagent.get(config.apiHost + '/data/position/getpositionbyname?name=' + value).end(function (err, res) {
                    commonAjaxCallback(err, res, function (err, res) {
                        if (!err && res.body.Status === 200) {
                            callback([new Error('该职位名称已被占用')]);
                            return;
                        }
                        callback(null);
                    });
                });
            }
        }
    ]
});
`

如上所示，我给一个表单栏位设置了多种校验，我系统如果排在前面的校验没有通过，则不用执行后面的校验，直接给出提示，那么我需要如何修改我的代码？

另外，表单校验这块的文档能否写全面一点，感觉不太好理解，很多地方靠猜，谢谢。

**Comment by afc163** [comment]
#2186
