### ISSUE TITLE
Pagination use showSizeChanger with pageSize or defaultPageSize，get broken view

### ISSUE THREAD

**Issue by chenpeng1102** [ant-design/ant-design#21939]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/carlenPeng/pen/PoqJMMN](https://codepen.io/carlenPeng/pen/PoqJMMN)

### Steps to reproduce
change page size

### What is expected?
1. SizeChanger show `5 / page`
2. Option to display complete information

### What is actually happening?
1. SizeChanger show only `5`
2. Option shows ellipsis

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | macOS 10.15.2 |
| Browser | Chrome 81.0.4044.34 |

**Comment by zombieJ** [comment]
Your `defaultPageSize` is not list in the `pageSizeOptions`.
