### ISSUE TITLE
Small尺寸的Select组件在多选模式下tag文字不居中，向上偏移了一像素

### ISSUE THREAD

**Issue by w91** [ant-design/ant-design#21934]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cb85l)

### Steps to reproduce
打开页面点击 small 按钮

### What is expected?
tag文字居中

### What is actually happening?
tag文字向上偏移了一像素，看代码是这个
```css
transform: translateY(-1px);
```
造成的，不知道加这个偏移量的原因是什么

 ![image](https://user-images.githubusercontent.com/2599455/76060360-0c1dee80-5fbc-11ea-9474-a7a887305e05.png)

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.12.0 |
| System | mac os 10.14.6 |
| Browser | 80.0.3987.122 |

**Comment by xrkffgg** [comment]
这 `1px` 应该是 `border` 的
这里的 `line-height` 已经减去 `2px`了，感觉 这个应该是不用了
