### ISSUE TITLE
📊 📈 Introduce AntV: a new player of data visualization

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#21932]
In modern web development, data visualization could a significant job for front-end developers, such as charts, maps, graph and data analytics. In this field, there are plents of great players like [D3.js](https://d3js.org/), [highcharts](https://www.highcharts.com), [Chart.js](https://www.chartjs.org/) and [Vega](https://vega.github.io/vega/). Let me introduce a new player which born in China: [AntV](https://antv.vision/), which is a powerful solution you don't want to miss. Here are some reasons I want to recommend it to your guys.

![image.png](https://gw.alipayobjects.com/zos/antfincdn/w5CUa5soZP/9bda5048-eea9-47c8-9144-567e1f31fe0c.png)

You can visit it's home page for more information: https://antv.vision

### Visualization in all fields

As a data visualization , AntV team provide various of specific solutions for multiple scenarios which includes charts, graph and maps. The deeper you dig in AntV, the more it will surprise you.

- [G2](https://g2.antv.vision/): it is a library based on visual encoding for manipulating [The Grammar of Graphics](https://www.amazon.com/Grammar-Graphics-Statistics-Computing/dp/0387245448). [Leland Wilkinson](https://en.wikipedia.org/wiki/Leland_Wilkinson), the author of this book, came and replied in [GitHub issue](https://github.com/antvis/G2/issues/221#issuecomment-348279298) specially. It is data-driven, highly user-friendly and extensible. Users can easily build a variety of interactive statistical graphics without struggling with various complicated details of implementation.
   ![](https://user-images.githubusercontent.com/6628666/68994104-1061b700-08ba-11ea-8017-3534fc85bc2f.jpeg)
   ![image.png](https://gw.alipayobjects.com/zos/antfincdn/VNNkrOL0AG/a14a3f69-0e03-41ea-8c23-53843c06afe2.png)
- [G2Plot](https://g2plot.antv.vision): G2Plot is an interactive and responsive charting library based on g2, provided all kinds of charts with simply API which could satisfy common needs for charts.
   ![](https://camo.githubusercontent.com/a6ac7b3fdfff3b4cbda91b26659a1b813440b7b7/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f6d646e2f726d735f6433313464642f616674732f696d672f412a73587172527245774652514141414141414141414141426b4152516e4151)
- [G6](https://g6.antv.vision): High-perfermance graph library, dozens of built-in layouts and algorithms. You can create a powerful and extrmely customized graph analystic application in a few code.
   ![](https://gw.alipayobjects.com/zos/rmsportal/HQxYguinFOMIXrGQOABY.gif)
- [F2](https://f2.antv.vision): specific charting library for mobile devices in many aspects like memory, CPU, bundle size and interaction. Most of charts in Alipay App (800 million users in China) are made of it.
- [L7](https://l7.antv.vision/)： The altertive map solution of  [deck.gl](https://github.com/uber/deck.gl) based on WebGL, supports Google Maps and Mapbox.
   ![](https://gw.alipayobjects.com/mdn/antv_site/afts/img/A*-gtxQbUPoGQAAAAAAAAAAABkARQnAQ)

Beside above, AntV contains [g (Canvas and SVG render)](https://github.com/antvis/g), [x6 (diagramming)](https://github.com/antvis/x6), [Graphin (graph analysis react app)](https://github.com/antvis/graphin) which cover all fields of front end data visualization. All libraries are designed and maintianed by the team with unified design specification, similar API and usage. You don't have to seek libraries in communication, AntV has the whole package to finish your visualization work.

### Battle-tested

AntV is running in 10,000 applications of Alibaba Group, the biggest e-commerce company in China, from enterprise background applications, mobile web apps, miniapp to large BI systems. For instance,  [DeepInsight](https://deepinsight.alipay.com) of Ant Financial (biggest BI application in Alibaba, like like Microsoft Power BI) apply AntV solution as it's charts/graph/maps solution very deeply, in which the perfermance, theme and other features of AntV are fully battle-tested. Polished by rich business scenarios for several years, AntV has the ability to support the products with million user visits.

![](https://static001.infoq.cn/resource/image/b0/d8/b0d2b0045e72ab9560497a0f0330b3d8.gif)

AntV are also one of the most popular data visualization solution in China, thousands of companies are using it. It is a common choice in China that using AntV and [Ant Design](https://github.com/ant-design/ant-design/) (the second most popular React UI library in the world, maintained by same team of AntV) together.

### Open Source under MIT

Like Ant Design, AntV libraries are all open-source in [GitHub organization](https://github.com/antvis/) under MIT licence that makes developers use their for free. AntV team are very acitve in GitHub, willing to reply English question alrough there is lots of Chinese issues out there. They also built beautiful home pages with English and Chinese versions, language will not be an obstacle to use it.

![image.png](https://gw.alipayobjects.com/zos/antfincdn/%26kYhzH29iH/a5f28c95-6b33-4c7c-802b-02536ef7b43d.png)

These all are open source:

- G2: https://github.com/antvis/g2
- G2Plot: https://github.com/antvis/g2plot
- G6: https://github.com/antvis/g6
- F2: https://github.com/antvis/f2
- L7: https://github.com/antvis/l7
- gatsby-theme-antv: https://github.com/antvis/gatsby-theme-antv

### For Designers

AntV are frendly to not only developers, but designers too. There are the useful design resouces and tools to help designer and other roles finishing their jobs. [Chartcube](https://chartcube.alipay.com) is one of these tools,  people can create a chart without writing code, and export as svg/png/code.

![image.png](https://gw.alipayobjects.com/zos/antfincdn/E%24dpYMzgOa/159ad2a4-5574-4fc9-8c5f-086190495ef6.png)

AntV design teams provide complete [Sketch template](https://antv.vision/en/docs/specification/resources). You can also create a chart magiclly in a an awosome Skecth plugin ([kitchen](https://kitchen.alipay.com/))!

![](https://gw.alipayobjects.com/zos/antfincdn/ZJUyxsH2JF/1.gif)

### What's coming?

AntV team are dedicating to [G2@4.0 and G2Plot@1.0](https://github.com/antvis/G2/tree/4.x) development, it is a complete refactor with tons of improvements in perfermance, interaction and design details, the new version will be published in next month.

Except to build existed charts, AntV team think more. A new project AVA show the potential of automaticly create charts from data, in power of Chart Knowledge Base and rule-based analytics.

```jsx
import { autoCharts } from '@antv/chart-advisor';

const data = [{
   date: '2020-01',
   value: 100,
}, {
   date: '2020-02',
   value: 200,
}];

autoChart(data, container);
```

![](https://camo.githubusercontent.com/d46ac2d59da5132df320852fd6b22420d90d584d/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f51544a5059584a706a572f61766164656d6f2e676966)

AVA will be open-source in GitHub soon: https://github.com/antvis/AVA

### Conclusion

![11.png](https://gw.alipayobjects.com/zos/antfincdn/AC41sZzJda/11.png)

AntV is a fun, multiple usage scenarios, battle-tested data visualizaton solution which supported by a professional team from China, you might want to try it in your next project.

**Comment by israelKusayev** [comment]
Looks awesome!!
I looked in the documentation of antv, and I saw a lot of pages are still in Chinese,
Are you going to translate them to English?

**Comment by afc163** [comment]
It is in progress and hopefully community could help us in translation by sending us PR~
