### ISSUE TITLE
Where is preserve option in v4 form?

### ISSUE THREAD

**Issue by supnate** [ant-design/ant-design#21944]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#API](https://ant.design/components/form-cn/#API)

### Steps to reproduce
Search "preserve", no result.

### What is expected?
preserve property should exist

### What is actually happening?
No preserve property found on the doc

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`preserve` is removed. You can use `getFieldsValue(true)` to get fully values.

**Comment by supnate** [comment]
It's not only about get all values. In the past, if a dynamic form item is removed and added back again, the value is not persisted by default(unless preserve is true). Now the value is always there, there should be some API equivalent with `preserve`.

**Comment by xyj404** [comment]
I need it, too.

**Comment by shamseerahammedm** [comment]
only rendered fields are prasent on submit, other values are lost even if ```preserve``` is ```true``` set on ```Form```, is this a bug ? even if included in initial value its missing any work around for this ?
