### ISSUE TITLE
Form 中 DatePicker 的返回值格式无法自定义

### ISSUE THREAD

**Issue by wengcd** [ant-design/ant-design#2194]
### 版本
1.62（目前最新及以下）

### 问题
`DatePick` 的 `onChange` 事件新增了返回值 `dateString` 的选项
但是在 `Form` 表单中，比如设置参数 `getFieldProps('datetime')` 后,  `getFieldValue` 依旧是 Javascript 原生日期
自己每次提交表单前需要将 日期的 value 格式化后覆盖再 post 到服务器

### 期望
`Form` 中也能对 `DatePicker` 返回值增加`dateString`

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/1831

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
