### ISSUE TITLE
能不能把表单的Context.Cousmer封装成高阶组件提供给使用者

### ISSUE THREAD

**Issue by yushicheng** [ant-design/ant-design#21945]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
针对class组件 分离式的表项 可以不需要透传form

### What does the proposed API look like?
```react
import React from "react";
import {Form,Input} from "antd";


@Form.withForm
class NameItem extends React.Component {
    
    handleChange=({target})=>{
        const {form}=this.props
        form.setFieldsValue({age:4})
    };
    
    render(){
        return (
        <Form.Item name="name">
         	<Input onChange={this.handleChange}/>
         </Form.Item>)
    }
}

export default NameItem;
```

**Comment by zombieJ** [comment]
官方推荐通过 `ref` 调用：https://ant.design/components/form-cn/#components-form-demo-control-ref

v4 中，Form 的字段更新只会渲染相关字段组件。`withForm` 比较容易让人误解和 v3 的 `Form.create` 一样会全部刷新。因而不会提供该方法。

但是你可以根据业务自行封装。
