### ISSUE TITLE
Keyboard shortcuts for pagination

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#21949]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
What do you think about adding keyboard shortcuts (right and left arrow) for "previous page" and "next page"?

(To be clear, the keycodes for right arrow is 39, and for left arrow is 37.)

Or maybe we can give the user the option to choose a key code..

### What does the proposed API look like?
```javascript
<Pagination defaultCurrent={1} total={50} rightClickKeyCode={39} leftClickKeyCode={37}  />
```

**Comment by zombieJ** [comment]
Thanks for feedback. But we do not have plan to modify key code. You can wrap an div to customize this instead.
