### ISSUE TITLE
Incorrect warning on Tree loadData method

### ISSUE THREAD

**Issue by ascendedguard** [ant-design/ant-design#21956]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/s1ie2)

### Steps to reproduce
1. Expand "Expand to load" node.
2. View console at bottom for warning.

### What is expected?
No warning

### What is actually happening?
Warning: Second param return from event is node data instead of TreeNode instance. Please read value directly instead of reading from `props`.

This is also happening in our production app after upgrading.

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | React 16.13.0 |
| System | Windows 10, Node 10.16 |
| Browser | Chrome 80 |

---
The "minimal reproduction" link above is straight from the documentation for 4.0.1 for the Tree control.

We need to retrieve node.props.data (for children and other data), and there is no second return param like the warning is indicating. I also see no way to retrieve this data without using props, so the warning just seems incorrectly in this context.

**Comment by zombieJ** [comment]
That's correct warning. Site demo should update for correct way.

**Comment by noszone** [comment]
Still receiving this warning message, I took demo from website. Even on Stackblitz it gives warning. 

Is this affect functionality?
