### ISSUE TITLE
The Form.Item rules required not Re render ,after change other Form.Item value ,even the Form.Item shouldUpdate is true or set dependecies

### ISSUE THREAD

**Issue by davidcun** [ant-design/ant-design#21952]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-4x4p7)

### Steps to reproduce
Set a Form.Item rules required and style dispay dependency a nother Form.Item value，but it not useful.

### What is expected?
The Form.Item rules required  and display can change 

### What is actually happening?
The Form.Item rules required and display not change

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | mac os |
| Browser | chrome  |

---
const optType = useState("optType1")  can success

**Comment by davidcun** [comment]
if a class component, invoke forceUpdate in Select onChange function ,it will success

**Comment by AshoneA** [comment]
Looks Form.Item props can't dynamic update, I figure out in myslef form by all props support function likes `className = { storeValue => storeValue.A ? 'has-a': 'not-a' }`, but it's looks too ugly. do you have good ideas? @zombieJ

**Comment by AshoneA** [comment]
or this way...
https://codesandbox.io/s/antd-reproduction-template-6ys7k

**Comment by davidcun** [comment]
> or this way...
> https://codesandbox.io/s/antd-reproduction-template-6ys7k

yes，it is worked ,thanks
