### ISSUE TITLE
v4 版本 form 在 class 模式下，无法立即获得 formRef.current

### ISSUE THREAD

**Issue by kavience** [ant-design/ant-design#21963]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/v3-cn/](https://ant.design/components/form/v3-cn/)

### Steps to reproduce

```jsx
// antd v4
class Demo extends React.Component {
  formRef = React.createRef();

  componentDidMount() {
    this.formRef.current.setFieldsValue({
      username: 'Bamboo',
    });
  }

  render() {
    return (
      <Form ref={this.formRef}>
        <Form.Item name="username" rules={[{ required: true }]}>
          <Input />
        </Form.Item>
      </Form>
    );
  }
}
```

### What is expected?
this.formRef.current 为正确值

### What is actually happening?
this.formRef.current 为 null

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | ^16.8.6 |
| System | macOS |
| Browser | chrome |

---
this.formRef.current.setFieldsValue 会报错，提示 current 为 null，只有
 setTimeout(() => {
      this.formRef.current.setFieldsValue({
        username: 'Bamboo'
      });
    }, 100);
通过延时操作才可以。

**Comment by yoyo837** [comment]
因为通过ref需要先渲染一次，对自定义表单项可能不太友好！你可以外面包装个函数组建使用useForm得到后传进去，不使用ref的方式

**Comment by kavience** [comment]
@yoyo837  但是还是觉得 class 模式更好用

**Comment by zombieJ** [comment]
参考 @yoyo837  的建议。另外，例子中用的是 `componentDidMount`，这个时候 form 已经初始化好了。

**Comment by dreamcog** [comment]
我也遇到了同样的问题，测试在componentDidMount时候并没有初始化好form

**Comment by diemus** [comment]
4.2.5也遇到这个问题，componentDidMount里面调用this.formRef.current=null。暂时使用initialValues做替代了，看来对class支持的不太好，算是bug吗

**Comment by zombieJ** [comment]
@diemus 提供一下重现，我这边看是好的：https://codesandbox.io/s/biaodanfangfadiaoyongclass-component-ant-design-demo-i8qeh

**Comment by diemus** [comment]
@zombieJ 我创建了一个，打开就会报错”Cannot read property 'validateFields' of null“，

https://codesandbox.io/s/biaodanfangfadiaoyongclass-component-ant-design-demo-we66g?file=/index.js

**Comment by zombieJ** [comment]
那是 Modal 渲染没有 Form 实例化，和 Form 本身没什么关系。另外，你可以通过外层包 Form，里面放 Modal 实现 Form 默认便初始化完成的效果。

**Comment by tigertany** [comment]
如果modal上不加forceRender属性，componentDidMount、componentDidUpdate里current都是null

**Comment by wave1998** [comment]
modal加上了forceRender也不行，还是null，目前是在componentDidMont中加了个定时器暂时解决了

**Comment by fqucuo** [comment]
类组件下问题依旧

**Comment by Bulala-liu** [comment]
同样的问题

**Comment by wulinjie122** [comment]
> 如果modal上不加forceRender属性，componentDidMount、componentDidUpdate里current都是null

我用了这种方法解决了，强制Modal渲染，之后form就能拿到refs了，看来是form 没有真正的渲染导致current为null的。

`
formRef = React.createRef<FormInstance>();

 componentDidMount() {
    console.log(this.formRef.current)
  }
`

`
<Modal
        destroyOnClose
        title="编辑作品"
        visible={modalVisible}
        onCancel={() => {handleModalVisible(false)}}
        footer={null}
        forceRender={true}>
`

**Comment by JunlinZhu-Tommy** [comment]
加了定时器还是null.

**Comment by nqsjd178559344** [comment]
我也遇见了这个问题....上面的方法都没有解决我的问题

**Comment by qq253673732** [comment]
我也遇见了...上面的方法都没有解决我的问题

**Comment by hbliyafei** [comment]
我在 Modal 中添加了一个  forceRender  解决了这个问题
https://ant-design.gitee.io/components/form-cn/#%E4%B8%BA%E4%BD%95%E5%9C%A8-Modal-%E4%B8%AD%E8%B0%83%E7%94%A8-form-%E6%8E%A7%E5%88%B6%E5%8F%B0%E4%BC%9A%E6%8A%A5%E9%94%99%EF%BC%9F
https://codesandbox.io/s/antd-reproduction-template-ibu5c
