### ISSUE TITLE
antd v3 to v4 report error

### ISSUE THREAD

**Issue by zhonggithub** [ant-design/ant-design#21968]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
z-react next 分支
https://github.com/zhonggithub/z-react

### Steps to reproduce
npm run start

### What is expected?
正常显示

### What is actually happening?
升级到v4，报错，应该hook 那个地方有问题？不知道是否是我配置的问题？
如图
![image](https://user-images.githubusercontent.com/17545551/76140774-aeab9f80-6098-11ea-9262-2b4be75dd5e6.png)

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12 |
| System | mac os |
| Browser | chrome 最新版本 |

**Comment by afc163** [comment]
Please follow https://ant.design/docs/react/migration-v4-cn to upgrade antd v4.

**Comment by zhonggithub** [comment]
> Please follow https://ant.design/docs/react/migration-v4-cn to upgrade antd v4.

是按官网步骤更新的，依然报错

**Comment by afc163** [comment]
@zhonggithub 给重现的 repo，你给的例子里依然是 3.x。

**Comment by zhonggithub** [comment]
https://github.com/zhonggithub/z-react-4

**Comment by afc163** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/507615/76156952-ebc96d80-613c-11ea-918e-fa460b30b0a7.png">

```
npm install 
npm run dev
```

本地无法启动你的项目。

**Comment by zhonggithub** [comment]
npm run build:dll
npm run start

**Comment by afc163** [comment]
https://github.com/zhonggithub/z-react-4/pull/1

**Comment by zhonggithub** [comment]
谢谢， 我看看
