### ISSUE TITLE
4.0.1 message 和 empty 组件都用不了，报错了。搞了两小时，我将版本切换至3.26.9解决问题

### ISSUE THREAD

**Issue by katherinelo** [ant-design/ant-design#21973]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/](https://github.com/ant-design/)

### Steps to reproduce
message.success('cccccc');

### What is expected?
出现提示

### What is actually happening?
查看控制台发现报错

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | "react": "^16.6.0", |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
官网没有问题，请检查一下自己的依赖的版本。

**Comment by liuzhaowei55** [comment]
官网内外访问都不流畅

**Comment by shaodahong** [comment]
> 官网内外访问都不流畅

确实慢，上海家用出口电信

Request: https://script.hotjar.com/modules.4ad5fd5dd561559ff499.js
![image](https://user-images.githubusercontent.com/14831261/76161262-a91f8980-616c-11ea-9168-00f5c3d8e909.png)

Request: https://ant.design/index-2692247e.js
![image](https://user-images.githubusercontent.com/14831261/76161273-d2401a00-616c-11ea-8258-dfdb4ceaa0ae.png)

**Comment by shaodahong** [comment]
@liuzhaowei55 试试 https://ant-design.gitee.io
