### ISSUE TITLE
Property `showTime` does not exist on type `PickerProps<Moment>`

### ISSUE THREAD

**Issue by JeromeDeLeon** [ant-design/ant-design#21972]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/focused-kirch-qynoo?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
access `showTime` prop in `DatePickerProps`

### What is expected?
Property `showTime` should exists on type `PickerProps<Moment>` or `DatePickerProps` for short.

### What is actually happening?
Property `showTime` does not exist on type `PickerProps<Moment>`

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Linux |
| Browser | 80.0.3987.122 |

**Comment by JeromeDeLeon** [comment]
@afc163  I was able to track down the culprit with [this line](https://github.com/ant-design/ant-design/blob/0c92b8e0cccb0ac8e14ce0f7f375fc92716fb6b8/components/date-picker/generatePicker.tsx#L91); however, I can't seem to resolve the issue.

In my app, I used `node_modules` to test things out.

```ts
export declare type PickerProps<DateType> = PickerBaseProps<DateType> |  PickerDateProps<DateType> | PickerTimeProps<DateType>;
export declare type Sample<DateType> = Pick<PickerProps<DateType>, 'showTime'>;
```

The `Sample` type was having an `unknown` type, but `PickerDateProps` type has `showTime` type because I tried doing this

```ts
export declare type Sample<DateType> = Pick<PickerDateProps<DateType>, 'showTime'>;
```

and it worked. Sorry :disappointed: , I will not be able to solve this problem that much as I don't know why it didn't work.

**Comment by zombieJ** [comment]
It's not a bug. `showTime` only exist on `picker='date'`. You need to use `Extract` to get `picker='date'` typescript define:

https://codesandbox.io/s/practical-snowflake-nn4yf

**Comment by lirunwin** [comment]
How to get _showTime_'s type out? i need to give _showTime_ a default value, when i was trying to wrap _DatePicker.RangePicker_

**Comment by dramoturg** [comment]
Do you have any update about this issue? I have same problem when i use RangePicker component. If I try to pass the showTime property, I get the typescript error.
`  Property 'showTime' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<RangePickerProps<Moment>, any, any>> & Readonly<...> & Readonly<...>'.
TS2322`

example code 
`const CustomDatePicker: FC<RangePickerProps> = props => {
	return (
		<RangePicker
			showTime={{ format: 'HH:mm' }}
			{...props}
		/>
	);
};`
