### ISSUE TITLE
TextArea组件disabled状态在IE浏览器下滚动条无法通过鼠标滚动的问题？

### ISSUE THREAD

**Issue by wo-de-ping-er** [ant-design/ant-design#21986]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/input-cn/](https://3x.ant.design/components/input-cn/)

### Steps to reproduce
TextArea内容超出，出现滚动条，然后在禁用状态下，无法通过鼠标上下滚动，diabled状态下只能通过点击上下箭头进行切换。

### What is expected?
能够出现完整滚动条，鼠标滑轮可以上下滚动查看内容

### What is actually happening?
无法通过鼠标滑轮查看隐藏内容

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.8 |
| System | win0 |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
游览器原生行为组件层做不了什么。
