### ISSUE TITLE
4.0 Form.Item中rules中设置required，导致控件每次修改多次rerender

### ISSUE THREAD

**Issue by Cavendichun** [ant-design/ant-design#21987]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-buck-0iu4o)

### Steps to reproduce
rules中是要使用required就会出现此问题

### What is expected?
相应控件只rerender一次

### What is actually happening?
相应控件rerender了多次

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.8.0 |
| System | win10 |
| Browser | 74 |

**Comment by Cavendichun** [comment]
并且发现rules中指定type的话，也会出现此问题

**Comment by zombieJ** [comment]
有 Rule 的 Item 输入时有额外的状态更新，我看看怎么优化一下。

**Comment by shaodahong** [comment]
> 有 Rule 的 Item 输入时有额外的状态更新，我看看怎么优化一下：
> 
> 1. value change
> 2. meta: validating
> 3. meta: validated

required 本身也是受控的
