### ISSUE TITLE
input输入框能否有类似于length属性，超过某个值不能输入

### ISSUE THREAD

**Issue by longhuasishen** [ant-design/ant-design#2198]
input输入框能否有类似于length属性，超过某个值不能输入

**Comment by juneryo** [comment]
直接使用属性 maxLength 就行了

**Comment by afc163** [comment]
maxlength

https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input

好好学习 html 规范啊，这个和 antd 没关系。

**Comment by longhuasishen** [comment]
我的天。。。。。。

**Comment by yuhaocan** [comment]
直接使用属性 maxLength并不可以 
"antd": "^2.13.6"

**Comment by afc163** [comment]
@yubozhao https://codepen.io/afc163/pen/ZayVOQ?&editors=001 It is working.
