### ISSUE TITLE
Avatar in horizontal menu will be displayed wrong

### ISSUE THREAD

**Issue by ireznik** [ant-design/ant-design#21984]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-wind-cuvxn)

### Steps to reproduce
Create horizontal menu
add Avatar Component to one menu item

### What is expected?
margin-right is not applied to the avatar icon

### What is actually happening?
margin-right from menu is applied to the avatar icon

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | MacOS |
| Browser | Chrome 80 |

**Comment by afc163** [comment]
Fixed in #21925

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/22021#issuecomment-596408648

**Comment by NechamaKremer** [comment]
adding the following style solved the issue:

```
span.anticon.anticon-user {
    display: contents;
}
```
