### ISSUE TITLE
日期选择类组件交互问题和周选择组件故障

### ISSUE THREAD

**Issue by fwtcumt** [ant-design/ant-design#21995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/fwtcumt/system-antd4.0](https://github.com/fwtcumt/system-antd4.0)

### Steps to reproduce
1. clone链接仓库，然后执行 `yarn` `yarn start` 后就能看见里面有一组组件示例。
2. 日期组件除了RangePicker外其他都是点击清除按钮后自动打开下拉框。
3. 周选择控件在我的window下和macbookpro下都出现问题。
4. 对于Select宽度的决定有些不解。

### What is expected?
1. 支持清除功能的控件，点击清除按钮统一去掉值就行。
2. 给Select一个默认的宽度，就像Input一样。

### What is actually happening?
1. 日期组件除了RangePicker外其他都是点击清除按钮后自动打开下拉框。
2. 周选择控件在我的window下和macbookpro下都出现问题。
3. Select组件的宽度表现不一致。

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | windows10、macOS10.14.6 |
| Browser | 谷歌浏览器80.0.3987.132 |

---
没有在Form表单中使用，就是单独使用时。

**Comment by zombieJ** [comment]
Picker 清除弹窗是个 bug 会修一下， Select 提供默认宽度是一个 breaking change，暂时不会加上。
