### ISSUE TITLE
DirectoryTree 在 nextjs 的 dev 模式下报错

### ISSUE THREAD

**Issue by meltifa** [ant-design/ant-design#21997]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-rain-c7p5n)

### Steps to reproduce
1. 新建控制台，输入 npm run dev
2. 界面显示后点击树标题控制台报错

### What is expected?
无报错

### What is actually happening?
Warning: Second param return from event is node data instead of TreeNode instance. Please read value directly instead of reading from `props`.

多次点击还有额外的报错信息

Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the property `nativeEvent` on a released/nullified synthetic event. This is set to null. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | mac osx |
| Browser | chrome 80 |

---
production模式下没有以上报错信息

**Comment by zombieJ** [comment]
event 中的 node 为了兼容 v3 的 `props` 使用方式通过 `Object.defineProperty` 提供兼容，但是会提示用户直接调用数据。

你的框架劫持了 `console.log` ，来遍历 event 参数，导致触发了 warning。

**Comment by zombieJ** [comment]
看了一圈似乎没什么可以特别做的。
