### ISSUE TITLE
yarn antd 4.0.0 升级到 4.0.1  ， 怪异现象 ，

### ISSUE THREAD

**Issue by ayi0z** [ant-design/ant-design#21994]
- [√] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-s7fu2我试图重现问题，但并没有成功)

### Steps to reproduce
刚才，yarn升级Antd4.0.0到antd4.0.1后，
发现了许多@ant-design/icons名称变了，比如众多的以lined结尾的icon全部变成了以line结尾，
```
export { default as LinkedinOutline } from './outline/LinkedinOutline';
export { default as LikeOutline } from './outline/LikeOutline';
export { default as LockOutline } from './outline/LockOutline';
export { default as MedicineBoxOutline } from './outline/MedicineBoxOutline';
export { default as MailOutline } from './outline/MailOutline';
export { default as MehOutline } from './outline/MehOutline';
...
```

另外：出现了很多“Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.”类型的错误，而这些在4.0.0中并未出现。
```
// 原写法，出现Warning
<Input prefix={<UserOutline style={{ color: 'rgba(0,0,0,.25)' }} />} placeholder="Username" />

// 修改后写法,  不出现Warning， 但是icon并未正确显示
<Input prefix={() =><UserOutline style={{ color: 'rgba(0,0,0,.25)' }} />} placeholder="Username" />
     
```

而我试图在https://codesandbox.io/s/antd-reproduction-template-s7fu2重现的时候，却并没有出现这些问题. 

这其中应该是发生了什么我不知道的事情，能否有什么建议提供，谢谢。

### What is expected?
我希望获得建议

### What is actually happening?
意料之外的情况发生了

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.8.6 |
| System | macos 10.15.3 (19D76) |
| Browser | chrome 80.0.3987.132 |

**Comment by zombieJ** [comment]
删除 `yarn.lock` 和 `node_modules` 重新安装一下，推测是 yarn 锁定回了旧版本的 `@ant-design/icons`。

另外，`package.json` 里也可以手工同步一下 `@ant-design/icons` 的版本到最新：https://www.npmjs.com/package/@ant-design/icons

**Comment by ayi0z** [comment]
重新安装无效， 手动安装@ant-design/icons4.0.0后解决
