### ISSUE TITLE
Ant tabs animation 

### ISSUE THREAD

**Issue by GraceChiamaka** [ant-design/ant-design#21992]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-puxq5)

### Steps to reproduce
Install the latest version of antd
Import antd into the component you want to use it in
Add the code for basic tab

### What is expected?
I expect to see a  tab with some content displayed

### What is actually happening?
When navigating between the tabs
a margin-left property of -100% is added to the subsequent tabs making the contents of the tabs render out of view

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.11.0 |
| System | HP ENVY 13 |
| Browser | 80.0 |

---
Here's a link to a video demo --->
https://drive.google.com/file/d/1wmR-D9G9ZvSIvMozh-4leieiLqFguSmt/view

**Comment by afc163** [comment]
Tabs animation is broken in 3.x and 4.x, 2.x works fine:

- ❌：https://ant.design/components/tabs/
- ❌：https://3x.ant.design/components/tabs/
- ✅：https://2x.ant.design/components/tabs/

**Comment by afc163** [comment]
I can reproduce your problem, please provide one and I will reopen this issue.
