### ISSUE TITLE
Switch inside form gives value undefined if not touched/changed

### ISSUE THREAD

**Issue by vin0010** [ant-design/ant-design#21999]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-turing-5h7wg)

### Steps to reproduce
Click on submit button to submit form value of switch will be undefined

### What is expected?
Click on submit button to submit form value of switch will be true

### What is actually happening?
value of switch will be undefined

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | react |
| System | Mac |
| Browser | Chrome 80.0.3987.132 |

**Comment by vin0010** [comment]
This one solved when I set type as boolean.

**Comment by afc163** [comment]
You missed `<Form.Item valuePropName="checked" />`

**Comment by vin0010** [comment]
@afc163 Its not happening, please check the codesandbox link attached to this ticket.

**Comment by afc163** [comment]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/507615/76204544-899f6400-6233-11ea-853c-f97457b827c5.png">

**Comment by vin0010** [comment]
![image](https://user-images.githubusercontent.com/10086767/76204941-9d2dd900-61f9-11ea-9072-ffbe25216056.png)

**Comment by vin0010** [comment]
Please check the image above, Without clicking the switch if you submit, value is undefined.

**Comment by afc163** [comment]
Try `initialValues`: https://codesandbox.io/s/nervous-turing-5h7wg

**Comment by vin0010** [comment]
I thought `initialValues` is the workaround, thats why created this issue. Thank you for suggesting.

**Comment by afc163** [comment]
The value of fields without `initialValues` would be `undefined`.

**Comment by phishy** [comment]
I agree with @DavidWhit (thanks for the solution BTW!). Ashamed at how long I spent on this.

**Comment by pguardiario** [comment]
FormItem checkboxes are not working for me (always undefined in values). As a workaround:
```
const onFinish = function (values) {
  values.my_cb = document.querySelector('.ant-checkbox-checked #basic_my_cb') ? "checked" : ""
  ...
}
  
```

**Comment by mykola-element** [comment]
Not working if Form.Item contains more than just Switch

`<Form.Item valuePropName="checked" name="test">
    <Switch disabled={i.disabled} /> <span>hello it is custom text</span>
  </Form.Item>`

**Comment by DMF-Abed** [comment]
I created a helper component, for now:

`import { Switch, SwitchProps } from "antd";
import { FC, ReactNode } from "react";

interface SwitchInputProps extends SwitchProps {
  label: ReactNode;
}

const SwitchInput: FC<SwitchInputProps> = ({ label, ...rest }) => {
  return (
    <>
      <Switch {...rest} /> {label}
    </>
  );
};

export default SwitchInput;
`

**Comment by jbobd** [comment]
> This was an ordeal to understand how to default the value of a switch for a form.
> I had to reread the options on Form/Item because defaultChecked on switch doesn't work (for initial submit without toggling; meaning it will be undefined on submit)
> It doesn't make sense either to separately maintain state for checked state when form hook is being used.
> 
> ` <Form.Item name="status" valuePropName="checked" initialValue={true}> <Switch /> </Form.Item>`

Unfortunately for me, using this solutions throws this error:

`Warning: Multiple Field with path 'admin' set 'initialValue'. Can not decide which one to pick.`

Investigating still.

**Comment by lobigm** [comment]
Its 2022, i feel the same way as you @phishy, Thanks you @DavidWhit  you help me to understand what was wrong in my understanding.
