### ISSUE TITLE
AutoComplete选中显示的为什么是value值而不是label值

### ISSUE THREAD

**Issue by helen123456** [ant-design/ant-design#22004]
![image](https://user-images.githubusercontent.com/29134290/76181639-bedc8f80-61fc-11ea-91e1-e96e1e898639.png)

**Comment by wsh085** [comment]
请问这个问题后面是怎么解决的

**Comment by NARUTOyuyang** [comment]
请问怎么解决呢？不了了之？

**Comment by chen2938** [comment]
我也有这个疑问，为什么没有修复呢？

**Comment by yoyo837** [comment]
因为对应不到label时会显示value.

**Comment by sishen654** [comment]
2024年bug还在

**Comment by sishen654** [comment]
![Uploading image.png…]()

**Comment by sishen654** [comment]
解决方法，给 AutoComplete 设置 value 绑定状态值，给内部 Input 设置 change 方法修改状态值

**Comment by afc163** [comment]
@sishen654 这不是 bug，AutoComplete 的特性如此，你可能需要的是 Select + showSearch。

**Comment by Zhangyao719** [comment]
// * 可选择、可手动输入的输入框
// * 支持 Form 表单
// * 相比 Antd 的 AutoComplete ，在选中选项时，支持输入框中显示 label 而不是 value。
// * 由 Antd 的 Select + showSearch 搜索框改编而来，重写 input 逻辑，当输入内容不匹配时，不会清空输入框。
// * @see https://4x-ant-design.antgroup.com/components/select-cn/#components-select-demo-search-box

import React, { useState } from 'react';
import { Select } from 'antd';
import debounce from 'lodash/debounce';

/**
 * @typedef {Object} Props
 * @property {string} value 受控的value
 * @property {Function} onChange 提供的 onChange 事件
 * @property {string} placeholder
 * @property {Object} style
 * @property {{ label: string; value: string | number }} options 下拉框选项
 * @param {Props} props
 */
const AutoComplete = ({
    value = '',
    onChange = () => {}, // form 表单接收的值
    placeholder = '',
    options = [],
    style = {},
}) => {
    const [input, setInput] = useState(value);

    // 重写输入逻辑：如果从 options 中匹配到，则返回 value，否则返回输入的值
    const handleInput = debounce(e => {
        const value = e.target.value;
        const selected = options.find(
            item => item.label.toLocaleLowerCase() === value.toLocaleLowerCase()
        );
        if (selected) {
            setInput(selected.label);
            onChange(selected.value);
        } else {
            setInput(value);
            onChange(value);
        }
    }, 500);

    const handleSelect = (value, option) => {
        // 避免重复的 form onChange 事件
        // 场景：输入框手动输入相匹配的值，又在下拉框中选择了该项，此时无需再重复触发
        if (input !== option.label) {
            setInput(option.label);
            onChange(value);
        }
    };

    return (
        <Select
            value={input}
            showSearch
            placeholder={placeholder}
            style={style}
            defaultActiveFirstOption={false}
            showArrow={false}
            notFoundContent={null}
            options={options}
            filterOption={(inputValue, option) => {
                const label = option.label.toLocaleLowerCase();
                const input = inputValue.toLocaleLowerCase();
                return label.indexOf(input) !== -1;
            }}
            onSelect={handleSelect}
            onInput={handleInput}
        />
    );
};

export default AutoComplete;
