### ISSUE TITLE
The `<Icon>` in `<Menu.Item>` with `<Link>` wrapped has `margin-right: 0`

### ISSUE THREAD

**Issue by dickeylth** [ant-design/ant-design#22008]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/dickeylth/antd-icon-issue](https://github.com/dickeylth/antd-icon-issue)

### Steps to reproduce
1. npm install;
2. npm run start

### What is expected?
The `<Icon>` should have `margin-right: 10px` instead of the overridden style:

```
.ant-menu-item.ant-menu-item-only-child .anticon, .ant-menu-submenu-title.ant-menu-item-only-child .anticon {
    margin-right: 0;
}
```

### What is actually happening?
The `<Icon>`'s `margin-right: 0`.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | macOS 10.15.3 (19D76) |
| Browser | Chrome 80.0.3987.132 |

---
This is a brand new project initialized by `npm create umi` with `ant-design-pro` boilerplate.

**Comment by dickeylth** [comment]
![image](https://user-images.githubusercontent.com/2196373/76184905-9eb2cd80-6208-11ea-95fc-5163e76fe931.png)

**Comment by shaodahong** [comment]
I check it's broke in 4.0.2 version, you can try in this [Demo](https://codesandbox.io/s/currying-dream-n8xo1)

**Comment by shaodahong** [comment]
Cause by https://github.com/ant-design/ant-design/pull/21925

```less
.ant-menu-item.ant-menu-item-only-child .anticon, .ant-menu-submenu-title.ant-menu-item-only-child .anticon {
    margin-right: 0;
}
```

**Comment by zombieJ** [comment]
一层就够了，的确不用多。
