### ISSUE TITLE
4.X Icon组件承接元素能否自定义

### ISSUE THREAD

**Issue by soulcm** [ant-design/ant-design#22002]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
3.x时，Icon渲染出来为 ```<i xxx><svg xxx></i>```这种形式，4.X渲染出来为 ```<span><svg></span> ```这种形式，我们老的项目中样式上有些地方对span有覆盖（现在改动起来会有些麻烦），会造成span上的样式冲突，能否增加渲染的根元素自定义为span或i这种

### What does the proposed API look like?
增加Icon组件渲染的根元素类型，可自定义

**Comment by zombieJ** [comment]
可以基于 `@ant-design/icons-svg` 自行封装：https://unpkg.com/browse/@ant-design/icons-svg@4.0.0/lib/asn/AccountBookFilled.js
