### ISSUE TITLE
当有横向滚动条时，DirectoryTree组件选中时有问题

### ISSUE THREAD

**Issue by baizn** [ant-design/ant-design#22005]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
![image](https://gw.alipayobjects.com/mdn/rms_3ff49c/afts/img/A*3VsdQKHQzgAAAAAAAAAAAABkARQnAQ)

### Steps to reproduce
如图

### What is expected?
有滚动条时，选中时高亮背景也能够覆盖整个行。

### What is actually happening?
如图

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 0.16.x |
| System | mac |
| Browser | chorme最新 |

**Comment by afc163** [comment]
https://codesandbox.io/s/keen-hodgkin-8p6mr

**Comment by zombieJ** [comment]
Close since v3 is not in maintain.
