### ISSUE TITLE
越更新打开越慢

### ISSUE THREAD

**Issue by luneice** [ant-design/ant-design#22006]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd 越来越成熟，也越来越深受开发者的喜爱。但似乎作者们似乎对待国内开发者不太友好，国外的开源项目优先服务于他本国的开发者。以前的 antd 官方文档打开的速度还算快的，现在打开官方文档要等几分钟才能加载完成，于是发现服务器ip(104.27.157.218美国 cloudflare公司cdn节点)不是国内的。自家的阿里云不香？

### What does the proposed API look like?
无

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19244#issuecomment-542561291

**Comment by duanzheng** [comment]
> [#19244 (comment)](https://github.com/ant-design/ant-design/issues/19244#issuecomment-542561291)

有 3 版本的国内镜像吗

**Comment by xrkffgg** [comment]
ant-design 国内镜像地址：https://github.com/ant-design/ant-design/issues/25661
