### ISSUE TITLE
升级到4.0.1后,表格横向滚动很卡

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#22000]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1mtzd)

### Steps to reproduce
特别是滚动到第一列与最后一列时,明显感觉到卡顿

### What is expected?
3.26.13版本,丝般顺滑.

### What is actually happening?
卡顿

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16 |
| System | win10 |
| Browser | chrome |

---

**Comment by l745230** [comment]
表格内容为文本时,列数15+ 也能明显感觉到卡顿,内容本文越长,越卡

**Comment by zombieJ** [comment]
触发了 ResizeObserver，需要看看为什么。
