### ISSUE TITLE
升级antd4.0后webstorm中部分组件的属性类型提示不正常

### ISSUE THREAD

**Issue by PeiTianHuang** [ant-design/ant-design#22001]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
<Select getPopupContainer\={triggerNode => triggerNode.parentNode as HTMLElement} placeholder\="请选择" mode\="multiple"\>

项目A用的是antd 3.26.12，鼠标悬浮在上面三个属性后按住ctrl并点击左键即可跳转到类型定义的位置。

项目B用的是antd 4.0.1，鼠标悬浮在上面三个属性后按住ctrl并点击左键，只有mode属性可以跳转到类型定义的位置。

搜索antd4.0.1目录下的select组件目录，未能搜索到getPopupContainer的定义，但官网文档中依旧能查询到该属性。

table组件也有一样的问题。

### What is expected?
能够跟3.26.12一样可跳转到类型定义的位置。

### What is actually happening?
只有mode属性可以跳转到类型定义的位置。

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome69 |

**Comment by zmayor** [comment]
只能提示还是有的, 但是点属性不能跳转, 不过ctrl+左键点击Select或者Table本身还是可以跳转的.
确实很别扭..

**Comment by PeiTianHuang** [comment]
> 智能提示还是有的, 但是点属性不能跳转, 不过ctrl+左键点击Select或者Table本身还是可以跳转的.
> 确实很别扭..

点击Select跳转后，也看不到getPopupContainer、placeholder之类的属性定义哦，点table则看不到components那些。

**Comment by zmayor** [comment]
![image](https://user-images.githubusercontent.com/18019463/76177671-f264ed00-61ef-11ea-967b-0ba2f9afcf55.png)
要去rc-select的定义里面找, 很麻烦

**Comment by zombieJ** [comment]
v4 里 rc-select 组件自带 ts 定义，antd 里直接继承了 rc 的自定不在额外编写。手头没有 webstorm，试了一下 vscode 能够点到定义：
<img width="710" alt="截屏2020-03-09上午10 34 29" src="https://user-images.githubusercontent.com/5378891/76178254-b468c880-61f1-11ea-9d4c-d2a2b34a56d9.png">

建议给 webstorm 发个 bug，这个是标准的写法，没什么黑科技。

**Comment by zmayor** [comment]
https://youtrack.jetbrains.com/issue/WEB-44281

**Comment by CangJL** [comment]
antd | 4.8.4
React | 17.0.1
System | macOS
IDE ｜webstorm
完全没有属性的智能提示，请问是antd的问题还是webstorm的问题呢
