### ISSUE TITLE
表单验证数字类型以及URL类型

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2201]
### 你做了什么？

const stdPriceV = getFieldProps('stdPrice', {
        rules: [
          { required: false, type: 'number', message: '请输入数字' },
        ],
      });

const serviceURLV = getFieldProps('serviceURL', {
        rules: [
          {type: 'url', message: '输入格式错误'},
        ],
        validateFirst: true
      });

### 你期待的结果是：
验证数字我的我输入非数字提示‘请输入数字’
验证URL我输入非URL提示‘格式错误’

## 实际上的结果：
我在验证数字的输入框输入不管输入什么都报‘请输入数字’
验证URL我输入http://www.baidu.com,但是输入http://114.55.69.451却报错，实际上应该也是要通过才对，因为IP也是地址的一种

**Comment by afc163** [comment]
上了 Github 也蛮久了，不能学习一下 Markdown 格式么。https://guides.github.com/features/mastering-markdown/

**Comment by aw6658913** [comment]
这不每天都在忙着做项目没时间专门去看下这个~~虽然没特意去研究不过没看出我提交问题比以前都有改进吗~~还有，麻烦亲回答下我的问题哈，一切以工作为主

**Comment by aw6658913** [comment]
其实我想直接提供在线演示~fork账号用不了，注册验证码也出不来还提示我要去反馈~真没这美国时间去搞这个~~

**Comment by afc163** [comment]
> 我在验证数字的输入框输入不管输入什么都报‘请输入数字’

如果是使用了 Input 或者 input 组件，请保持校验规则为 `type: 'string'`。或者使用 `InputNumber` 来配合 `type: 'number'`。

> 验证URL我输入http://www.baidu.com ,但是输入 http://114.55.69.451 却报错，实际上应该也是要通过才对，因为IP也是地址的一种

IPv4 的数字最大只能是 254。
