### ISSUE TITLE
Select Input text overflows to ellipsis too early (antd 4.0.2 - Firefox only)

### ISSUE THREAD

**Issue by edant92** [ant-design/ant-design#22017]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-wfwum)

### Steps to reproduce
Create a Select element using antd 4.0.2 (note: this issue only occurs in Firefox using antd 4.0.2)

### What is expected?
Text should only be ellipsised when it reaches the end of the Select Input

### What is actually happening?
Text inside the Select Element/input is being ellipsised at a very small width.

## Additional Notes
I have tested this with Chrome as well as 4.0.1 in both Firefox and Chrome. It works correctly in these 3 cases.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | Ubuntu 18.04.4 |
| Browser | Firefox |

Screenshots:
Sandbox Firefox:
![sandbox_firefox](https://user-images.githubusercontent.com/6187226/76199822-dca3f780-61f0-11ea-8109-158c9ff07420.png)

Sandbox Chrome:
![image](https://user-images.githubusercontent.com/6187226/76200537-1a555000-61f2-11ea-93cd-a824554f118c.png)

**Comment by afc163** [comment]
Your codesandbox is empty.

**Comment by edant92** [comment]
@afc163 Thanks for pointing that out :laughing: I'd added the code but not pressed save. Please check again, apologies!

**Comment by zombieJ** [comment]
Your codesandbox still not reproduce the issue.

**Comment by edant92** [comment]
@zombieJ It does. I've attached images to the issue to make it clearer.

**Comment by afc163** [comment]
In my Firefox:

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/507615/76202912-9cfd0000-6230-11ea-8baa-e86a868fc906.png">

**Comment by edant92** [comment]
@afc163 That's because you're using antd 4.0.0 (according to your screenshot). The issue is only in 4.0.2.

**Comment by afc163** [comment]
Right, here is reproduce:

https://codesandbox.io/s/antd-reproduction-template-6z55h

> 😁 Next time you can provide a reproduce demo directly, don't let us dig..

**Comment by edant92** [comment]
@afc163 Thanks for clarifying it! Apologies, I thought I'd reproduced it correctly. I'll be more careful doing it next time.

**Comment by afc163** [comment]
Not only placeholder, it happen to selected value too: https://codesandbox.io/s/antd-reproduction-template-6z55h

<img width="665" alt="image" src="https://user-images.githubusercontent.com/507615/76207549-fbc67780-6238-11ea-8de4-e2b61aeb1c65.png">

**Comment by zombieJ** [comment]
Seems it's firefox bug.

**Comment by zombieJ** [comment]
Dig for workaround.
