### ISSUE TITLE
AutoComplete: Multiple options selected

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#22019]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-tree-84782)

### Steps to reproduce
Summary: 
We have an address lookup in our project, with fields - address, city and state. 

Link for antd v3, where feature is working fine:
https://codesandbox.io/s/nervous-lumiere-1cors

Steps:
Start typing into the autocomplete, there are three options with '158 Pelican Ln' as street but different city and state names. The street value need not be unique. The entire address value is unique i.e. value property is set as combination of street, city and state. Upon selecting an option, with antd v3 optionLabelProp, we could populate street value returned by the lookup into address field, city value into city field and state value into state field. 

### What is expected?
With antd4, the above feature cannot be achieved. 

### What is actually happening?
With antd v4, once we select '158 Pelican Ln Novato' and then click on the autocomplete second time, we see that all three options with '158 Pelican Ln' get selected and there is no way to select '158 Pelican Ln Greeneville'

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | Win 10 |
| Browser | Chrome 80 |

**Comment by zombieJ** [comment]
It's a bug, do not tread it as a feature. `value` of options in AutoComplete/Select should always be unique. **⚠️ We can not promise that whether it will be fixed in v3 in feature. ⚠️**

In your case, you should use Select instead of AutoComplete. AutoComplete is an input with additional popup suggestion. And also, option value should be unique.

**Comment by AnirudhaGohokar** [comment]
The whole issue is because value attribute is being used to show both selected text as well as for matching criteria. Another attribute similar to `optionLabelProp` could fix this issue

**Comment by umerfarooq112** [comment]
I have solved this form instace of ANTD. If you are using Form.item what you need to do is call form.setFieldsValue(); function to set the autocomplete value. Here look at my Code

>         <Form.Item label={<p className="label-input">Customer Name</p>} name="customerName"
                      rules={[
                        {
                          required: true,
                          message: "Please input Customer Name",
                        },
                      ]}
                    >
                      <AutoComplete
                        onSearch={handleSearchQuery}
                        onSelect={handleCustomerData}
                        placeholder="input here"
                      >
                        {data?.customers?.nodes.map((item) => (
                          <Option
                            key={item?.id}
              
                          >
                      
                            {item?.nameEnglish}
                          </Option>
                        ))}
                      </AutoComplete>
                    </Form.Item>

  
            

On onSelect Function set the form.item value by calling Form.setFieldValues()

> const handleCustomerData = (value, option) => {
  
    form.setFieldsValue({
    customerName: getCustomerObj[0].nameEnglish,

    });
  };
