### ISSUE TITLE
Icon margin is broken in AntD 4.0.2 when using NavLink from React Router

### ISSUE THREAD

**Issue by jaworek** [ant-design/ant-design#22028]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-wwqomp?file=index.js](https://stackblitz.com/edit/react-wwqomp?file=index.js)

### Steps to reproduce
Add <NavLink> around content in each <Menu.Item>.

### What is expected?
In prior versions spacing was not affected and icons had their margin applied properly.

![Menu with icons properly aligned](https://user-images.githubusercontent.com/22678765/76201378-740a4a00-61f3-11ea-8156-95d8548db6d5.png)

### What is actually happening?
Icons are missing right margin.

![Menu with icons missing margin right](https://user-images.githubusercontent.com/22678765/76201385-779dd100-61f3-11ea-8600-31bd3661b021.png)

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | MacOS 10.15 |
| Browser | Chrome, Firefox |

**Comment by afc163** [comment]
Fixed in #22021
