### ISSUE TITLE
`onChange` on Form.Item is not working with Select

### ISSUE THREAD

**Issue by nanaSun** [ant-design/ant-design#22026]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-65cde)

### Steps to reproduce
trigger the Select

### What is expected?
The first onChange is working

### What is actually happening?
The first onChange is not working

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13 |
| System | mac 10.14 |
| Browser | chrome  80.0.3987.132 |

**Comment by zombieJ** [comment]
`Form.Item` do not have `onChange` prop. You should use `onFieldsChange` on Form or `onChange` on Select instead.

**Comment by ravneet-core** [comment]
@zombieJ I think @nanaSun was trying to say that `onChange` on `Select` does not show the selected option when enclosed within a `Form.Item` I can replicate this error on my end and not sure how to fix it.
