### ISSUE TITLE
4.X 与 3.X 的Form.Item上设置help和rules时表现不一致

### ISSUE THREAD

**Issue by soulcm** [ant-design/ant-design#22023]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
4.X demo: https://codesandbox.io/s/determined-mclaren-p0tpl
3.X demo:  https://codesandbox.io/s/sleepy-banzai-fn76m

![image](https://user-images.githubusercontent.com/5706155/76197311-de88ad80-6226-11ea-9fa1-0f3b3a850d35.png)
![image](https://user-images.githubusercontent.com/5706155/76197343-ee07f680-6226-11ea-8fc5-f5a337bd2fbc.png)

当触发校验后，3.X的help状态会跟着变成红色，但4.X不会

### What does the proposed API look like?
4.X与3.X保持一致，触发校验未通过时，help的状态也变成红色

**Comment by zombieJ** [comment]
颜色是跟着 `status` 走的，设置了 `help` 不设置 `status` 应该就是默认的颜色。v3 是 bug，v4 不会特地跟着 v3 走。
