### ISSUE TITLE
从Select的notFoundContent打开的Modal，无法focus弹窗内元素

### ISSUE THREAD

**Issue by Heshiyu1996** [ant-design/ant-design#22031]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-4bcdz)

### Steps to reproduce
1、在Select框随意输入无法匹配结果的关键字；
2、出现notFoundContent内容时，点击“添加”；
3、打开的新建弹框里的Input无法focus

### What is expected?
在notFoundContent情况下，新建弹框里的Input能够被focus

### What is actually happening?
在notFoundContent情况下，新建弹框里的Input不能够被focus

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | macOS 10.14.4 |
| Browser | Chrome 80.0 |

---
因业务要求，需要在模糊搜索不到情况下，进行弹窗新建

**Comment by Heshiyu1996** [comment]
看到这个相似的问题，通过notFoundContent并没有解决（是否我方式不对？）
https://github.com/ant-design/ant-design/issues/18453

**Comment by afc163** [comment]
可以这么解：https://codesandbox.io/s/antd-reproduction-template-qe1lp

**Comment by afc163** [comment]
或者按 https://github.com/ant-design/ant-design/issues/18453#issuecomment-524602507 的说法把 Modal 挂载到 Select 外去。

**Comment by zombieJ** [comment]
Select 元素只有一个 Input 可以获取焦点，以防止失去焦点让 popup 关闭。你的 Modal 应该放到外面来调用。

**Comment by Heshiyu1996** [comment]
> 可以这么解：https://codesandbox.io/s/antd-reproduction-template-qe1lp

你好，受到启发。如果要修改onMouseDown事件，应该在Form位置可以生效。
demo：
https://codesandbox.io/s/antd-reproduction-template-lvxks

**Comment by Heshiyu1996** [comment]
> 或者按 [#18453 (comment)](https://github.com/ant-design/ant-design/issues/18453#issuecomment-524602507) 的说法把 Modal 渲染节点挂载到 Select 外去。

我分别通过Modal的getContainer属性在Select的同级、根节点的同级进行尝试，无法解决。（是否我的方式不对？）
demo：
https://codesandbox.io/s/antd-reproduction-template-ewfmj

**Comment by afc163** [comment]
getContainer 估计不好使。还是得把 Modal 定义到外面。

**Comment by Heshiyu1996** [comment]
> getContainer 估计不好使。还是得把 Modal 定义到外面。

感谢回复，的确没有达到预期效果。我稍后研究下getContainer好了~
目前做法是放到外面，通过ref来手动触发click，可实现 :D
demo：
https://codesandbox.io/s/antd-reproduction-template-4bcdz
