### ISSUE TITLE
Table设置scroll: true无效

### ISSUE THREAD

**Issue by byenow** [ant-design/ant-design#2203]
- antd 版本: 1.6.2
- 操作系统及其版本: macOS@10.11.3
- 浏览器及其版本: Chrome@51.0.2704.103 (64-bit)
- node: 4.4.5

低版本@1.3.2中显示正常，最新版本@1.6.2中`scroll: true`设置无效

http://codepen.io/byenow/pen/XKMMOg?editors=0010

**Comment by afc163** [comment]
对，尽量指定固定宽度 `scroll: 1200`。

如果一定要使用 `scroll: true`，需要配合样式 `.ant-table td { white-space: nowrap; }`。因为这个代码会带来其他问题，而且也不应该默认不换行，所以 1.6 里去掉了。

**Comment by yesmeck** [comment]
@afc163 要不 `scroll.x` 为 `true` 的时候自动加个 `.ant-table td { white-space: nowrap; }`？

**Comment by afc163** [comment]
想换行的时候怎么办？

**Comment by afc163** [comment]
不过如果只针对 `scroll={{ x: true }}`，好像也没问题。

**Comment by yesmeck** [comment]
我还是在文档里说明下吧。
