### ISSUE TITLE
Try esbuild

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#22035]
https://github.com/evanw/esbuild

https://github.com/sorrycc/esbuild-webpack-plugin

**Comment by mritd** [comment]
Is esbuild available?

**Comment by afc163** [comment]
两个都跑不通，先加个 `process.env.ESBUILD` 开启，本地可测：

- [ ] `ESBUILD=1 npm run site`：`TypeError: ssr is not a function`
- [ ] `ESBUILD=1 npm run dist`：可以构建成功，但是不会自动结束，长久的卡住
