### ISSUE TITLE
[3.26.13] 'is-validating' status is always on when removing field content

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#22042]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://google.com](https://google.com)

### Steps to reproduce
I'm using the base Form and Input components from `antd` 3.26.13 and only setting `rules: [{ required: true, message: 'my message here' }]`. It validated properly if I enter something into the field (`has-success` class appears on `Form.Item`), but the deleting the whole field content it gets stuck at `is-validating` class and shows no help text below the field at all.

What's even weirder is that the `async-validator` warn message appears properly in the console, saying that the field is required.

**Edit**
I've researched this issue and noticed that `validateFieldsInternal` function is stuck on line `fieldErrors.push(e);` as the `fieldErrors` is `undefined`. Not sure why this happens as `async-validator` clearly logged that the field I was testing was required.

This is kind of weird as I've not experienced this issue in any other project of mine, just the one I started recently based on a boillerplate from other projects (where it works correctly...)

### What is expected?
Help message should appear

### What is actually happening?
It is not appearing

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.12.0 |
| System | macOS 10.15.3 |
| Browser | Firefox 73.0.1 (64-bit) |

**Comment by QuanHuang** [comment]
Did you use "lodash-webpack-plugin" in your project? I have the same problem, form always keep "is-validating" when trigger validateFields function, then I find it works after removing "lodash-webpack-plugin" from webpack config file.  Env:  antd: 3.26.15, react:16.12.0, lodash-webpack-plugin: 0.11.5
