### ISSUE TITLE
Form.Item > initialValues broken if code comments exist

### ISSUE THREAD

**Issue by michaelpeterlee** [ant-design/ant-design#22046]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-s0egz)

### Steps to reproduce
 <Input  /> {/* <Input prefix={<Icon type="folder" style={{ color: 'rgba(0,0,0,.25)' }} />}  /> */}

### What is expected?
Form.initialValues to apply 'grr' value to the Note input; Ignore the commented out code.

### What is actually happening?
Causes Form.initialValues does not apply 'grr' value to the Note input.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | OSX 10.15 |
| Browser | Chrome 16.13.0 |

---
Took a while to debug this as did not manifest in v3, so this may help others implement v4 and/or upgrade form v3.

**Comment by afc163** [comment]
```diff
        <Form.Item
          name="note"
          label="Note"
          rules={[
            {
              required: true
            }
          ]}
        >
-         <Input />{" "}
+         <Input />
          {/* <Input prefix={<Icon type="folder" style={{ color: 'rgba(0,0,0,.25)' }} />} placeholder="Name" /> */}
        </Form.Item>
```

https://codesandbox.io/s/antd-reproduction-template-9ouyv
