### ISSUE TITLE
Bad type of AntTreeNodeProps interface

### ISSUE THREAD

**Issue by incNick** [ant-design/ant-design#22040]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/3.x-stable/components/tree/Tree.tsx](https://github.com/ant-design/ant-design/blob/3.x-stable/components/tree/Tree.tsx)

### Steps to reproduce
```
const props: AntTreeNodeProps;
props.children.length 
```
will return length not an attribute of props

### What is expected?
line 44 should be `children?: React.ReactNode[];`

### What is actually happening?
`children?: React.ReactNode;`

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | Chrome |

---
see https://3x.ant.design/components/tree/#components-tree-demo-draggable and 
search content like ##(info.node.props.children || []).length > 0##
IDE report the error like info.node.props.children hadn't attribute length

**Comment by fireairforce** [comment]
solved at https://github.com/ant-design/ant-design/pull/24429
