### ISSUE TITLE
[4.0] onFinish - values

### ISSUE THREAD

**Issue by CarolineBoyer** [ant-design/ant-design#22041]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
None - following Doc

### Steps to reproduce
Since migrating from 3 to 4, logging values don't show the 
```javascript
   onFinish = (values) => {
        console.log(values);
}
[...]

    <Form
        // ref={this.form}
        name="naviCreationForm"
        onFinish={this.onFinish}
        onFinishFailed={this.onFinishFailed}
        style={{
            margin: '30px'
        }}
        initialValues={initialValues}
    >
        <Form.Item
            key={'chosenNavi-name'}
            label={<IntlMessage id={'CONNECTINGHUB_CREATE_STEP_TWO_FIELD_NAME'}/>}
            name='name'
            rules={[
                {
                    required: true,
                    message: <IntlMessage
                        id={'CONNECTINGHUB_CREATE_STEP_TWO_FIELD_NAME_ERROR'}
                        valuesGiven={{typeOfNavi: this.state.chosenNavi.type}}/>
                },
            ]}
        >
            <Input/>
        </Form.Item>
[...]

```

### What is expected?
I expected the console.log to give me { name: 'contentOfInput', ... }

### What is actually happening?
It gives me this : Class {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: MouseEvent, _dispatchListeners: ƒ, …}
Therefore I don't have access to the values... 

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | react 16.13.0 |
| System | Windows 10 |
| Browser | Chrome |

---
Might be a similar issue to a chinease one, I am afraid I don't understand chinease :(

**Comment by mjfwebb** [comment]
Refer to https://ant.design/components/form/v3/#replace-onSubmit-with-onFinish, specifically the line mentioning: 

> You need to listen `onSubmit `and call `validateFields `to handle validation in old Form. New Form provides onFinish which only trigger when validation is passed

**Comment by mjfwebb** [comment]
I had to ensure validation was passed before I was returned the values:

`  const onFinish = () => {
    form.validateFields().then(async (values) => {
      // Use values here
    });
  };`

**Comment by CarolineBoyer** [comment]
Docs didn't feel like validateFields was mandatory.... I'll try this.
https://ant.design/components/form/v3/#replace-onSubmit-with-onFinish

**Comment by zombieJ** [comment]
Test your code. Can get value from `onFinish`: https://codesandbox.io/s/affectionate-yonath-nixky

**Comment by CarolineBoyer** [comment]
Hard to give you a codepen of this as the form is automatically created according to what first-step-wizard user input is.
The output of the console is what was given here :
```javascript
Class {dispatchConfig: {…}, _targetInst: FiberNode, _dispatchInstances: FiberNode, nativeEvent: MouseEvent, _dispatchListeners: ƒ, …}
nativeEvent: (...)
type: (...)
target: (...)
currentTarget: (...)
eventPhase: (...)
bubbles: (...)
cancelable: (...)
timeStamp: (...)
defaultPrevented: (...)
isTrusted: (...)
view: (...)
detail: (...)
screenX: (...)
screenY: (...)
clientX: (...)
clientY: (...)
pageX: (...)
pageY: (...)
ctrlKey: (...)
shiftKey: (...)
altKey: (...)
metaKey: (...)
getModifierState: (...)
button: (...)
buttons: (...)
relatedTarget: (...)
movementX: (...)
movementY: (...)
isDefaultPrevented: (...)
isPropagationStopped: (...)
preventDefault: (...)
stopPropagation: (...)
dispatchConfig: null
_targetInst: null
_dispatchListeners: null
_dispatchInstances: null
get nativeEvent: ƒ ()
set nativeEvent: ƒ (val)
get type: ƒ ()
set type: ƒ (val)
get target: ƒ ()
set target: ƒ (val)
get currentTarget: ƒ ()
set currentTarget: ƒ (val)
get eventPhase: ƒ ()
set eventPhase: ƒ (val)
get bubbles: ƒ ()
set bubbles: ƒ (val)
get cancelable: ƒ ()
set cancelable: ƒ (val)
get timeStamp: ƒ ()
set timeStamp: ƒ (val)
get defaultPrevented: ƒ ()
set defaultPrevented: ƒ (val)
get isTrusted: ƒ ()
set isTrusted: ƒ (val)
get view: ƒ ()
set view: ƒ (val)
get detail: ƒ ()
set detail: ƒ (val)
get screenX: ƒ ()
set screenX: ƒ (val)
get screenY: ƒ ()
set screenY: ƒ (val)
get clientX: ƒ ()
set clientX: ƒ (val)
get clientY: ƒ ()
set clientY: ƒ (val)
get pageX: ƒ ()
set pageX: ƒ (val)
get pageY: ƒ ()
set pageY: ƒ (val)
get ctrlKey: ƒ ()
set ctrlKey: ƒ (val)
get shiftKey: ƒ ()
set shiftKey: ƒ (val)
get altKey: ƒ ()
set altKey: ƒ (val)
get metaKey: ƒ ()
set metaKey: ƒ (val)
get getModifierState: ƒ ()
set getModifierState: ƒ (val)
get button: ƒ ()
set button: ƒ (val)
get buttons: ƒ ()
set buttons: ƒ (val)
get relatedTarget: ƒ ()
set relatedTarget: ƒ (val)
get movementX: ƒ ()
set movementX: ƒ (val)
get movementY: ƒ ()
set movementY: ƒ (val)
get isDefaultPrevented: ƒ ()
set isDefaultPrevented: ƒ (val)
get isPropagationStopped: ƒ ()
set isPropagationStopped: ƒ (val)
get preventDefault: ƒ ()
set preventDefault: ƒ (val)
get stopPropagation: ƒ ()
set stopPropagation: ƒ (val)
__proto__: Class
```


when code is :
export class NaviCreationWizard extends React.Component<INaviCreationWizardProps, INaviCreationWizardState> {
    form = React.createRef<FormInstance>();

    constructor(props: INaviCreationWizardProps) {
        super(props);
        this.state = {
            hasErrors: false,
            currentStepShown: 0,
            selectedType: '',
            chosenNavi: new Navi()
        }
    }
    onFinish = (values:any) => {
        console.log(values);
    };
    onFinishFailed = ({errorFields}: any) => {
        this.form.current!.scrollToField(errorFields[0].name);
    };

   render() {
... 
                            case 1:
                                let initialValues: { [key: string]: string } = {
                                    name: this.state.chosenNavi.name,
                                    description: this.state.chosenNavi.description['default']
                                };
                                Object.keys(this.state.chosenNavi.credentials).forEach(oneKey => {
                                    initialValues[oneKey] = this.state.chosenNavi.credentials[oneKey];
                                });
                                return (
                                    <div>
                                        <Form
                                            ref={this.form}
                                            layout={'vertical'}
                                            name="naviCreationForm"
                                            onFinish={this.onFinish}
                                            onFinishFailed={this.onFinishFailed}
                                            style={{
                                                margin: '30px'
                                            }}
                                            initialValues={initialValues}
                                        >
                                            <Form.Item
                                                key={'chosenNavi-name'}
                                                label={<IntlMessage id={'CONNECTINGHUB_CREATE_STEP_TWO_FIELD_NAME'}/>}
                                                name='name'
                                                rules={[
                                                    {
                                                        required: true,
                                                        message: <IntlMessage
                                                            id={'CONNECTINGHUB_CREATE_STEP_TWO_FIELD_NAME_ERROR'}
                                                            valuesGiven={{typeOfNavi: this.state.chosenNavi.type}}/>
                                                    },
                                                ]}
                                            >
                                                <Input/>
                                            </Form.Item>
                                            <Text strong>
                                                <IntlMessage
                                                    id={'CONNECTINGHUB_CREATE_STEP_TWO_FIELD_DESCRIPTION'}/>
                                            </Text>
                                            <Form.Item
                                                key={'chosenNavi-description'}
                                                name={'description'}
                                            >
                                                <Input/>
                                            </Form.Item>
                                            <Text strong>
                                                <IntlMessage
                                                    id={'CONNECTINGHUB_CREATE_STEP_TWO_FIELD_CREDENTIALS'}/>
                                            </Text>
                                            {Object.keys(this.state.chosenNavi.credentials).map((keyCorrespondingToChangingField: string) => {
                                                return <Form.Item
                                                    key={keyCorrespondingToChangingField}
                                                    label={keyCorrespondingToChangingField[0].toUpperCase() + keyCorrespondingToChangingField.slice(1)}
                                                    name={keyCorrespondingToChangingField}
                                                    rules={[
                                                        {
                                                            required: true,
                                                            message: <IntlMessage
                                                                id={'CONNECTINGHUB_CREATE_STEP_TWO_FIELD_CREDENTIALS_ERROR'}
                                                                valuesGiven={{
                                                                    typeOfNavi: this.state.chosenNavi.type,
                                                                    credential_field: keyCorrespondingToChangingField
                                                                }}
                                                            />,
                                                        }
                                                    ]}
                                                >
                                                    {
                                                        keyCorrespondingToChangingField === 'password' ?
                                                            <Input.Password/>
                                                            :
                                                            <Input/>
                                                    }
                                                </Form.Item>
                                            })}
                                        </Form>
                                    </div>
                                );
...
               <div className="steps-action" style={{
                    paddingBottom: '20px',
                    textAlign: 'center'
                }}>
                   {currentStepShown === 1 && (
                        <Button type="primary" onClick={this.onFinish} htmlType="submit">
                            <IntlMessage id={'CONNECTINGHUB_CREATE_NEXT'}/>
                        </Button>
                    )}
                </div>
```

However, doing like @mjfwebb suggested, makes it work. Why that much difference with what Docs are suggesting ? ( that onFinish = onSubmit + validate )

**Comment by zombieJ** [comment]
You add another `onFinish` on the Button `onClick` porp which makes you get SyntheticEvent object. 
```tsx
<Button type="primary" onClick={this.onFinish} htmlType="submit">
  <IntlMessage id={'CONNECTINGHUB_CREATE_NEXT'}/>
</Button>
```

**Comment by barrycarr** [comment]
I'm experiencing a similar issue, I think this issue needs to be re-opened. 

This error doesn't happen on all of my forms, but it does occur on two dynamic forms where the user can add multiple items of the same type/format. My forms follow the dynamic form example in your documentation. In my case, the data from each dynamic part of the form is being mix-up with what looks like an event object, similar to @CarolineBoyer example.

I'm also getting random  warnings about a SyntheticEvent being re-used. Both of my dynamic forms use a Select component and, occasionally, this warning appears when a value is selected from the drop-down. It doesn't happen every time and I haven't managed to figure out if there's a pattern to this warning occurring.

**Comment by linrf** [comment]
soma here

> I'm experiencing a similar issue, I think this issue needs to be re-opened.
> 
> This error doesn't happen on all of my forms, but it does occur on two dynamic forms where the user can add multiple items of the same type/format. My forms follow the dynamic form example in your documentation. In my case, the data from each dynamic part of the form is being mix-up with what looks like an event object, similar to @CarolineBoyer 's example.
> 
> I'm also getting random warnings about a SyntheticEvent being re-used. Both of my dynamic forms use a Select component and, occasionally, this warning appears when a value is selected from the drop-down. It doesn't happen every time and I haven't managed to figure out if there's a pattern to this warning occurring.

**Comment by mleister97** [comment]
Same issue for me, using normal Inputs

**Comment by mleister97** [comment]
@linrf @barrycarr 

For me the issue was:

Using
```js
<Form.Item style={{justifyContent: "center"}}><Button type="dashed" onClick={add} block>Add</Button></Form.Item>
```
instead of the correct solution:
```js
 <Form.Item style={{justifyContent: "center"}}><Button type="dashed" onClick={() => add()} block>Add</Button></Form.Item>
```

**Comment by MR-AMDEV** [comment]
@mleister97 Thank you the provided solution worked fine and the form starts to give normal values.

What could be the issue?
