### ISSUE TITLE
DatePicker的RangePicker不支持同时选择

### ISSUE THREAD

**Issue by Henri-Zhang** [ant-design/ant-design#22047]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
升级antd4之后，RangePicker支持单独选择开始时间或结束时间。但是我的需求还是希望像旧版那样可以一次性选择。

### What does the proposed API look like?
类似旧版同时选择开始结束。

**Comment by afc163** [comment]
It is by designed. You can lock antd version to 3.x if you prefer old `RangePicker[showTime]`.
