### ISSUE TITLE
Menu.Item not referentially transparent

### ISSUE THREAD

**Issue by dbousamra** [ant-design/ant-design#22048]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-faraday-co2on)

### Steps to reproduce
Extract a Menu.Item into its own component

### What is expected?
For it to work without errors

### What is actually happening?
The styling is broken. It also throws an
```
Uncaught TypeError: onItemHover is not a function
    at MenuItem._this.onMouseLeave (MenuItem.js?c3c0:61)
```
error on hover

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.12.0 |
| System | OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/lingering-wood-r6ee7

**Comment by dbousamra** [comment]
@afc163 Thank you!

**Comment by zhongyongbin1** [comment]
@afc163 我按照你说的：[https://codesandbox.io/s/lingering-wood-r6ee7]()没有解决问题，   
![image](https://user-images.githubusercontent.com/53078314/99934736-c5666380-2d99-11eb-8237-862a7ca727d3.png)
代码如下：   
![image](https://user-images.githubusercontent.com/53078314/99934756-d8793380-2d99-11eb-8fce-6bea869a6f3e.png)
