### ISSUE TITLE
上传图片如何得到图片的长宽？

### ISSUE THREAD

**Issue by guotie** [ant-design/ant-design#2204]
### 本地环境

- antd 版本: 当前版本
- 操作系统及其版本：所有操作系统
- 浏览器及其版本: 所有浏览器

### 你做了什么？

无

### 你期待的结果是：

希望得到图片的长宽尺寸信息

## 实际上的结果：

目前上传图片只有图片的size和图片的类型

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2168
