### ISSUE TITLE
Antd 4.0 ，unable to get to Form.Item default values

### ISSUE THREAD

**Issue by timothywei** [ant-design/ant-design#22049]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-tlon2)

### Steps to reproduce
https://codesandbox.io/s/antd-reproduction-template-tlon2

### What is expected?
get  Form.Item default values

### What is actually happening?
 Unable to get to Form.Item default values

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.* |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/issues/21820#issuecomment-593867570
