### ISSUE TITLE
[4.0.2] Error – not importing icons correctly?

### ISSUE THREAD

**Issue by Ancinek** [ant-design/ant-design#22045]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://not.required](https://not.required)

### Steps to reproduce
I've upgraded from latest 3.x to 4.0.2 and trying to go through the required migration changes. I'm stuck right away as it says `Module not found: Can't resolve '@ant-design/icons/CheckCircleFilled'` (and all of the other icons). I've installed `@ant-design/icons` and still nothing.

I'm using ejected `create-react-app` with this in `babel-loader` options plugin (worked with 3.26.13):
```
                  [
                    'import',
                    {
                      libraryName: 'antd',
                      libraryDirectory: 'es',
                      style: true,
                    },
                  ],
```

### What is expected?
No error when upgrading 

### What is actually happening?
Error after the upgrade

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.12.0 |
| System | 10.15.3 |
| Browser | Firefox 73.0.1 (64-bit) |

**Comment by afc163** [comment]
Please upgrade @ant-design/icons to 4.x

**Comment by Ancinek** [comment]
@afc163 the @ant-design/ucina package was at the same version as antd (so 4.0.2) when the error happened.

**Comment by afc163** [comment]
Remove yarn.lock and reinstall node_modules.

**Comment by Ancinek** [comment]
@afc163 Coming back after performing those steps. I'm using `npm` and removing `package-lock.json` along with `node_modules` did not help, unfortunately. Is there anything special I should do besides simply installing `antd@4.0.2` and `@ant-design/icons@4.0.2`?
