### ISSUE TITLE
希望增加一个点击行就能展开或收起树节点的功能

### ISSUE THREAD

**Issue by weidapao** [ant-design/ant-design#22057]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前展开或收起树节点只能点击最前方的小三角实现

### What does the proposed API look like?
增加一个配置项，点击行是否自动展开/收起

**Comment by jhoneybee** [comment]
可以用 Tree的`onSelect`事件来判断是否可以展开

**Comment by afc163** [comment]
Try https://ant.design/components/tree-cn/#components-tree-demo-directory
