### ISSUE TITLE
感觉v4版本的Button按钮样式没以前好看了，border-radius由4px变成了2px

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design#22050]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
样式

### What does the proposed API look like?
样式好看

**Comment by yoyo837** [comment]
这是刻意为之的修改，你可以覆盖`@border-radius-base`

**Comment by afc163** [comment]
可以自行覆盖变量：https://ant.design/docs/react/customize-theme-cn
