### ISSUE TITLE
`Select` selected value text is being truncated

### ISSUE THREAD

**Issue by pvinis** [ant-design/ant-design#22054]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-native-community/upgrade-helper](https://github.com/react-native-community/upgrade-helper)

### Steps to reproduce
- yarn install
- yarn start
- look at the `Select`s, they are correct, the text is for example `0.61.0`
- change `antd` to `4.0.2`
- yarn install
- yarn start
- look at the `Select`s, they are wrong, the text is for example `0.61 ...`

### What is expected?
The text to appear full, like `0.61.0`

### What is actually happening?
The text appears truncated, like `0.61 ...`

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | wat |
| Browser | firefox |

---

**Comment by afc163** [comment]
Fixed in #22033
