### ISSUE TITLE
AutoComplete组件的options遍历有问题

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#22064]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-5yhpsl](https://stackblitz.com/edit/react-5yhpsl)

### Steps to reproduce
输入框里输入 岳 就会报 Cannot use 'in' operator to search for 'options' in 岳*   错误

### What is expected?
希望不报错

### What is actually happening?
希望不报错

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.12.0 |
| System | mac |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
```diff
- ["岳*","yu78897"]
+ [{ value: "岳*" }, { value: "yu78897" }]
```

**Comment by ISBN9527** [comment]
哈哈😃没仔细看文档，谢谢大哥

**Comment by yoyo837** [comment]
@ISBN9527 你的github profile location 的`BeiJin` 少个`g` 😃

**Comment by ISBN9527** [comment]
@yoyo837 i follow u👍
