### ISSUE TITLE
[v4] How to disable input dynamically

### ISSUE THREAD

**Issue by mbm-code** [ant-design/ant-design#22060]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-qz9pd)

### Steps to reproduce
Click button

### What is expected?
Input will disable without use state.

### What is actually happening?
setFields not working

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.11.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
You should use `React.useState`, `setFields` only works on field value.

**Comment by Educity1237** [comment]
@afc163 is there other way out if we don't wants to use react useState. I mean I want it to be handle by form instance.
Is is possible?

**Comment by yicrotkd** [comment]
You can use `dependencies`.

https://4x.ant.design/components/form/#dependencies

This demo uses dependencies and handles `disabled` property by `getFieldValue`.

https://codesandbox.io/s/form-disabled-antd-4-24-4-forked-t7czo7?file=/demo.tsx
