### ISSUE TITLE
Table组件url远程数据需求，远程模式提高了简单table页面的开发效率。0.11版本远程模式被移除，文档概述了结论，我想知道移除的原因。

### ISSUE THREAD

**Issue by walk-liuyan** [ant-design/ant-design#22063]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 antd0.11版本后Table 的 dataSource 远程模式被移除，用户需要自行实现数据获取方式。以上是官方给出的结论，我想知道移除远程模式的原因

### What does the proposed API look like?
<Table url="/users" size="small" key="id" />

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/413#issuecomment-158333466
