### ISSUE TITLE
Directorytree with Virtual Scroll collapses sometimes when I change the tree render after scrolling

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#22062]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rough-tdd-gltnl)

### Steps to reproduce
1. Render a Directorytree with big data
2. TriggerSearch and change the tree render
3. Scroll the search result (still big data)
4. TriggerSearch based on current tree
5. The tree collapse with an uncaught error：   TypeError: Cannot read property 'data' of undefined, in List (created by NodeList) in NodeList (created by Tree) in div (created by Tree)
![uncaught error](https://user-images.githubusercontent.com/37827411/76292191-b7df7b00-62e9-11ea-9860-9cdc657b1e30.png)
6. Console says I should report this bug:   
Not find index item. Please report this since it is a bug.		
console.<computed>	@	index.js:1
List._this.getIndexKey	@	List.js?623a:151
getItemRelativeTop	@	itemUtil.js?cd2c:106
getItemAbsoluteTop	@	itemUtil.js?cd2c:119
componentDidUpdate	@	List.js?623a:463
![console.error1](https://user-images.githubusercontent.com/37827411/76292144-9d0d0680-62e9-11ea-9cc9-16aa9bb067f6.png)
![console.error2](https://user-images.githubusercontent.com/37827411/76292301-e9f0dd00-62e9-11ea-93cf-d4216b567674.png)
### What is expected?
No uncaught error

### What is actually happening?
an uncaught error

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | Google Chrome  version79.0.3945.88 |

---
The bug, which has a higher occurrence rate in my customized component SearchTree, only occurs once in the codesandbox and I cannot reproduce it. The bug occurs seems because the virtual list cannot find the right index sometime when I change the dataSource of the Tree after I scroll it.

**Comment by zombieJ** [comment]
Hi @sdhr27 ,

I can not get the error. Could you help provide more info like what you typed in the input.
If gif provide, that helps a lot.

**Comment by sdhr27** [comment]
I use hook to render my Component. The bug disappears when I use useCallback to package my funcition.
from:
`function renderDirectoryTree() {
    const treeProps = {
      ...props,
      motion: height ? null : undefined, // bug?
      selectedKeys,
      onExpand: onTreeExpand,
      onSelect: onTreeSelect,
      expandedKeys: myExpandedKeys,
    };
    if (children) {
      treeProps.children = newChildren;
    }
    if (dataSource) {
      treeProps.treeData = myDataSource;
    }
    return <DirectoryTree {...treeProps} />;
  }`
to:
`const renderDirectoryTree = useCallback(() => {
    const treeProps = {
      ...props,
      motion: height ? null : undefined, // bug?
      selectedKeys,
      onExpand: onTreeExpand,
      onSelect: onTreeSelect,
      expandedKeys: myExpandedKeys,
    };
    if (children) {
      treeProps.children = newChildren;
    }
    if (dataSource) {
      treeProps.treeData = myDataSource;
    }
    return <DirectoryTree {...treeProps} />;
  }, [myDataSource, newChildren]);`
Gif of the bug in my Component:
![1](https://user-images.githubusercontent.com/37827411/76374385-06d6f000-637e-11ea-8874-5a7124df5384.gif)

**Comment by sdhr27** [comment]
Also, if I don't pass `motion: height ? null : undefined`to the Tree. Virtul scroll will disappear when I change the expandedKeys, and white block show during scroll. Also I can't reproduce it in sandbox but in my Component. I am wondering what `motion` do in antd Tree?

**Comment by zombieJ** [comment]
Could you help to update your reproduce? I can not find `renderDirectoryTree` in your reproduce. Thanks.

**Comment by sdhr27** [comment]
I update the reproduce. To reproduce the bug:
![1](https://user-images.githubusercontent.com/37827411/76720430-c4475600-6777-11ea-8a18-65bf4b48623d.gif)
1. Expand a treenode.
2. Shrink the browser window
3. Enlarge the browser window

**Comment by sdhr27** [comment]
Does that mean the  tree height has to be determined once the tree is rendered?
