### ISSUE TITLE
Provides narrow theme

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#22068]
ref: https://www.yuque.com/docs/share/046f0665-5cbd-4614-ad4f-43798d06f27b

- [x] Official website preview support (theme switch) 
- [ ] Umi and Bigfish support @afc163 https://github.com/umijs/plugins/pull/120
- [x] Document for using it @afc163 #21668
- [ ] Narrow with dark theme
- [x] Global padding
- [x] Button
- [x] Dropdown
- [x] Pagination
- [x] PageHeader
- [x] Steps
- [x] Cascader
- [x] DatePicker
- [x] Form
- [x] InputNumber
- [x] Input
- [x] Mentions
- [x] Slider
- [x] Select
- [x] TreeSelect
- [x] Transfer
- [x] TimePicker
- [x] Uploader
- [x] Comment
- [x] Collapse
- [x] Card 
- [x] Descriptions 
- [x] List  
- [x] Popover  
- [x] Timeline  
- [x] Tabs  
- [x] Table 
- [x] Drawer 
- [x] Modal  
- [x] Tooltip 

Review Date: `4-2`
Release Date: `4-15`

**Comment by AshoneA** [comment]
Let me do it!

**Comment by zombieJ** [comment]
Hi @AshoneA ,
Thanks for your volunteer. Updated assigner in issue comment.

**Comment by afc163** [comment]
Assign myself to some components and umi support.

**Comment by AshoneA** [comment]
Here: https://github.com/ant-design/ant-design/pull/22126
