### ISSUE TITLE
Table表头的纵向滚动条宽度修改不了

### ISSUE THREAD

**Issue by panHuaCheng** [ant-design/ant-design#22076]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-monad-c4v9s)

### Steps to reproduce
修改滚动条的宽度
     &::-webkit-scrollbar {
        width: 5px;
         height: 5px;
      }
代码写了，但是滚动条没有变化。不会用codesandbox，麻烦你们改一下。
表头会占有原来滚动条的宽度
而不是修改过后的
![image](https://user-images.githubusercontent.com/50853087/76304987-4b6f7680-62ff-11ea-8de8-49104f8b26f3.png)

### What is expected?
表头和内容滚动条宽度一致

### What is actually happening?
表头和内容滚动条宽度不一致

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | 谷歌 74.0.3729.131 |

**Comment by zombieJ** [comment]
不建议修改滚动条样式，这不是 css 标准。Table 会模拟创建一个 div 来测量一下滚动条支持。可以试试看全局替换滚动条样式，如果不行的话。那就没办法了。

<img width="680" alt="截屏2020-03-10下午9 19 13" src="https://user-images.githubusercontent.com/5378891/76316027-cd1dcf00-6314-11ea-9c2f-a31890fa219d.png">

https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar
