### ISSUE TITLE
Multiple Form.Item in dynamic Form.List

### ISSUE THREAD

**Issue by giacomoronconiobda** [ant-design/ant-design#22078]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-mplkp?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Click on add choose one value on left column, then one on right.

### What is expected?
 The values in console after submit should be two arrays with same length: includedColumns and includingColumns

### What is actually happening?
The the two Form.Item are seen as the same while i would like to stay indipendent in terms of values in them.

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.13.0 |
| System | Ubuntu 18.04.4 LTS |
| Browser | Chrome 80.0.3987.122 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
Your 2 Form.Item is using same `name` which make one override another one. And also, you should extend `field` form Form.List instead of just using `index`.

https://codesandbox.io/s/antd-reproduction-template-uhu2v

**Comment by giacomoronconiobda** [comment]
Thank you for the very rapid answer
