### ISSUE TITLE
Impossible to expand Select component dropdown programatically

### ISSUE THREAD

**Issue by martis347** [ant-design/ant-design#22074]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/martis347/pen/XWbVPap?editors=0010](https://codepen.io/martis347/pen/XWbVPap?editors=0010)

### Steps to reproduce
Try to programatically expand element, to see the dropdown in one of these ways:
```javascript
document.querySelector('.ant-select').click()
document.querySelector('.ant-select-selector').click()
document.querySelector('.ant-select-selection-search').click()
document.querySelector('input').click()
```

### What is expected?
Select would expand and show dropdown values.

### What is actually happening?
Select is not expanding. The only possible way to expand it that I found is by using your mouse.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Google Chrome 80.0.3987.132 (Official Build) (64-bit) |

---
This used to work in Ant design 3.x.x but seems to be broken now after updating to ant design 4.0.2.

**Comment by afc163** [comment]
Try controlled mode by using `open` and `onDropdownVisibleChange`.

**Comment by martis347** [comment]
Thanks, @afc163, but by using controlled mode I could expand/collapse the component from within the React context. That still does not solve the problem of external click events not triggering the dropdown.

**Comment by Meshour** [comment]
@afc163 
I have the same issue. I am not able to write unit tests that includes the `Select` component cause I can't figure out how to open the dropdown with a click. In `v3` I could simply put a `test-id` on both the `Select` and the `Option` component and then I could find those properties and click on them.

In `v4` however, the `Option` component doesn't pass the `test-id` prop anymore, althought I was able make a work around here to look for the text itself. But I cannot find a way to open the `Select` dropdown using `react-testing-library`. I checked out the `onDropdownVisibleChange` method but that's called after the dropdown has opened. Any suggestions?

**Comment by mrdannael** [comment]
Propably it's `mousedown` event now instead of `click`.

I was able to open antd v4 select with the code below (tested in chrome console):

```javascript
let select = document.querySelector('.ant-select-selector');
let clickEvent = document.createEvent('MouseEvents');
clickEvent.initEvent('mousedown', true, true);
select.dispatchEvent(clickEvent)
```

**Comment by Meshour** [comment]
Thanks @mrdannael it works! It would be nice if it would work without the custom `querySelector` though :)

**Comment by klugjo** [comment]
Thanks @mrdannael, I have lost so much time with this. Here are some more details:

You can select your component like so to avoid the querySelector all

```
const elt = getByTestId('your-test-id').firstElementChild;
fireEvent.mouseDown(elt);
```

Now at this point you probably want to select an option from the list but there is an animation going on so the following code (that used to work in v3) will fail. 

```
expect(getByText('Option from Select')).toBeVisible(); // FAILS !
```

You have 2 options, use `toBeInTheDocument()` or wait for the animation to be over by using `waitFor(...)`

Option 1: Faster but not totally accurate, I prefer to use this for simple use cases as it makes the tests faster and synchronous

```
expect(getByText('Option from Select')).toBeInTheDocument(); // WORKS !
```

Option 2: Slower as you need to wait for the animation to finish but more accurate for complex cases

```
waitFor(() => expect(getByText('Option from Select')).toBeVisible()); // WORKS !
```

**Comment by famoraes** [comment]
Thank you all very much for this! I lost many hours trying to figure out why my tests weren't passing.
Just another thing:
If you want to select an option to test the document after it, you need to use `.click` and not `mousedown`.

`fireEvent.click(getByText('Option from Select'));`

In my case I didn't need to `waitFor` any change.

**Comment by Nodewarrior** [comment]
> Thanks @mrdannael, I have lost so much time with this. Here are some more details:
> 
> You can select your component like so to avoid the querySelector all
> 
> ```
> const elt = getByTestId('your-test-id').firstElementChild;
> fireEvent.mouseDown(elt);
> ```
> 
> Now at this point you probably want to select an option from the list but there is an animation going on so the following code (that used to work in v3) will fail.
> 
> ```
> expect(getByText('Option from Select')).toBeVisible(); // FAILS !
> ```
> 
> You have 2 options, use `toBeInTheDocument()` or wait for the animation to be over by using `waitFor(...)`
> 
> Option 1: Faster but not totally accurate, I prefer to use this for simple use cases as it makes the tests faster and synchronous
> 
> ```
> expect(getByText('Option from Select')).toBeInTheDocument(); // WORKS !
> ```
> 
> Option 2: Slower as you need to wait for the animation to finish but more accurate for complex cases
> 
> ```
> await waitFor(() => expect(getByText('Option from Select')).toBeVisible()); // WORKS !
> ```

This doesn't work for me. Tried many ways.

**Comment by sadsa** [comment]
I managed to test clicking and selecting multiple options and then expect the page results to change. 

```ts
      const { findAllByText } = setup();

      const select= document.querySelector(
        `[data-testid="<test_id>"] > .ant-select-selector`
      ) as HTMLElement;

      // click on the select input 
      fireEvent.mouseDown(select);

      // wait for the ant dropdown element to appear
      await waitFor(() => {
        return expect(
          document.querySelector(".ant-select-dropdown")
        ).toBeInTheDocument();
      });

      // select a single dropdown option
      fireEvent.click(document.querySelector(`[label="1"]`) as Element)

      const records = await findAllByText(/record/);
      expect(records).toHaveLength(1);
      
      // select another dropdown option
      fireEvent.click(document.querySelector(`[label="2"]`) as Element)

      const records2 = await findAllByText(/record/);
      expect(records2).toHaveLength(2);
````

I spent hours on this, so I hope it helps someone :)

**Comment by 07akioni** [comment]
> to test clicking and selecting multiple options and then expect the p

You should find out which step goes error exactly.

**Comment by thiagobutignon** [comment]
Hi guys, its impossible to test Select and Autocompletes components.

Here it's my unit test using jest and testing library.

```ts

const makeSut = (fieldName: string): RenderResult => {
  return render(
    <FormContext.Provider value={{ state: {} }}>
      <Form>
        <BankAutocompleteInput
          name={fieldName}
        />
      </Form>
    </FormContext.Provider>
  )
}

describe('BankAutocompleteInput Component', () => {
  beforeAll(() => {
    Object.defineProperty(window, 'matchMedia', {
      writable: true,
      value: jest.fn().mockImplementation(query => ({
        matches: false,
        media: query,
        onchange: null,
        addListener: jest.fn(), // Deprecated
        removeListener: jest.fn(), // Deprecated
        addEventListener: jest.fn(),
        removeEventListener: jest.fn(),
        dispatchEvent: jest.fn(),
        setState: jest.fn()
      }))
    })
  })

  test('Should set value on combobox click', async () => {
    const field = faker.database.column()
    makeSut(field)

    const input = screen.getByTestId(field).firstElementChild
    fireEvent.mouseDown(input)
    await waitFor(() => fireEvent.change(screen.getByRole('combobox'), { target: { value: 'Banco do Brasil S.A.' } }))

    await waitFor(() => fireEvent.click(document.querySelectorAll('.ant-select-item-option-content')[0]))

    expect(screen.getByRole('combobox')).toHaveValue('001')
  })
})

```

I'm receiving this error on terminal, but the unit tests is passing on green.

```
  ● Console

    console.error
      Warning: An update to List inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in List (created by OptionList)
          in OptionList (created by ForwardRef(Select))
          in div (created by SelectTrigger)
          in div (created by Align)
          in Align (created by CSSMotion)
          in DomWrapper (created by CSSMotion)
          in CSSMotion (created by PopupInner)
          in PopupInner (created by Popup)
          in div (created by Popup)
          in Popup (created by Trigger)
          in ForwardRef (created by Trigger)
          in Trigger (created by SelectTrigger)
          in SelectTrigger (created by ForwardRef(Select))
          in div (created by ForwardRef(Select))
          in ForwardRef(Select) (created by Select)
          in Select (created by ForwardRef(InternalSelect))
          in ForwardRef(InternalSelect) (created by Context.Consumer)
          in ForwardRef(AutoComplete) (created by Field)
          in Unknown
          in Unknown (created by Field)
          in div (created by FormItemInput)
          in div (created by FormItemInput)
          in div (created by Col)
          in Col (created by FormItemInput)
          in FormItemInput (created by Field)
          in div (created by Row)
          in Row (created by Field)
          in Field (created by WrapperField)
          in WrapperField (created by FormItem)
          in FormItem (created by BankAutoCompleteInput)
          in BankAutoCompleteInput
          in form (created by ForwardRef(Form))
          in ForwardRef(Form) (created by ForwardRef(InternalForm))
          in SizeContextProvider (created by ForwardRef(InternalForm))
          in ForwardRef(InternalForm)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at node_modules/rc-virtual-list/lib/hooks/useHeights.js:61:7
```

How i can test this without warnings?

Thanks forwards.

**Comment by cha0wg** [comment]
@thiagobutignon I got this error when test too, my test passed locally but failed on circleCI, the snapshot got unexpected `ForwardRef(InternalSelect)`
```
    -         <Select
    -           bordered={true}
    -           choiceTransitionName="zoom"
    +         </ForwardRef(InternalSelect)>
    +         <ForwardRef(InternalSelect)
                onChange={[Function]}
                placeholder="Max"
    -           transitionName="slide-up"
              >`

**Comment by bulletbrand** [comment]
Has anyone found a solution to this problem, how can you select an element in a select?

**Comment by loongluangkhot** [comment]
@thiagobutignon  I got the same error, and not sure how to solve. Have you figured anything out?

**Comment by michaelpeterlee** [comment]
@sadsa your contribution enabled my solution, below.

```
render(<MockComponent />, { wrapper: TestProviders });

const modal = await screen.findByRole(/dialog/i, { name: "My Modal",}); // Wait for modal to appear
expect(modal).toBeVisible();

const selectCompanyId = document.querySelector(".ant-select-selector") as HTMLElement;
fireEvent.mouseDown(selectCompanyId);

await waitFor(() => {
  return expect(document.querySelector(".ant-select-dropdown")).toBeInTheDocument();
}); // Wait for the ant dropdown virtual-list element to appear

expect(
  document.querySelector(".rc-virtual-list-holder-inner")?.children.length
).toBe(1); // <MockComponent /> specifies 1x Company item only

const domSelectListItem = screen.getByTitle('MyDropdownListItemLabel'); // AntD decorates item elements with title=""
fireEvent.click(domSelectListItem);
```

**Comment by xonium** [comment]
Thanks to this thread I managed to finally have a test that works and does not produce the warning `Warning: An update to List inside a test was not wrapped in act(...).`.

the select for the test
```
export const SelectView = () => {
return (<Select data-testid="select-name">
        <Select.Option value="Peter">Peter</Select.Option>
        <Select.Option value="Mats">Mats</Select.Option>
        <Select.Option value="Nicklas">Nicklas</Select.Option>
      </Select>)
}
```

the test
```
it("a test with select", async () => {
    var name = "Nicklas";
    
    const { container } = render(
      <SelectView />
    );

    let select = container.querySelector("[data-testid='select-name'] > .ant-select-selector");
    expect(select).not.toBeNull();
    
    let selectElement = select as Element;
    act(() => {
      fireEvent.mouseDown(selectElement);
    })

    expect(await screen.findByText(name)).toBeInTheDocument();

    act(() => {
      fireEvent.click(screen.getByText(name));
    });

    // do other expects on the changed value ...
  });
```

**Comment by craigmiller160** [comment]
Ok, following the steps in this thread I was just barely able to get the clicks to work, but it doesn't update the AntD form. I want to be able to submit it with the value set by the select.

**Comment by kaichii** [comment]
> 



> @martis347 Propably it's `mousedown` event now instead of `click`.
> 
> I was able to open antd v4 select with the code below (tested in chrome console):
> 
> ```js
> let select = document.querySelector('.ant-select-selector');
> let clickEvent = document.createEvent('MouseEvents');
> clickEvent.initEvent('mousedown', true, true);
> select.dispatchEvent(clickEvent)
> ```
> 
> Edit: Tested with RTL, works like a charm. Calling `fireEvent.mouseDown` on `.ant-select-selector` should open antd select in unit tests @Meshour :)
> 
> Tested with:
> 
> ```js
> const select = container.querySelector(
>     '[data-testid=mcc-select] > .ant-select-selector'
> );
> fireEvent.mouseDown(select); // this should open select in unit tests
> ```

`Event.initEvent()` is **Deprecated**, [see more](https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent).

Update:

 ```js
 const select = document.querySelector('.ant-select-selector');
 const clickEvent = new Event('mousedown', { bubbles: true, cancelble: true });
 select.dispatchEvent(clickEvent);
 ```

**Comment by benliu723** [comment]
@mrdannael @kaichii Frankly, i already gave up for writing ut for antd selector/dropdown until i found your reply. Thanks a lot!

**Comment by upesic** [comment]
@mrdannael @kaichii 
Thank you for the suggested solution, but unfortunately, it didn't work in my case.

These are the versions of the dependencies I use in my project
antd: 5.4.5,
react-hook-form: 7.43.7,
testing-library/react: 14.0.0,
testing-library/user-event: 14.4.3,

The Select component from antd is used as controlled component wrapped in Controller from react-hook-form.

Do you maybe know what could be the problem? Thanks in advance for any help!

**Comment by robertmirro** [comment]
@upesic I was able to choose a `Select.Option` like this:

```js
<Form.Item name="entity" label="I am a..." rules={[{ required: true, message: 'Please select' }]}>
  <Select placeholder="I am a...">
    <Select.Option value="Patient">Patient</Select.Option>
    <Select.Option value="Health System">Health System</Select.Option>
    <Select.Option value="Clinical Practice">Private Practice</Select.Option>
    <Select.Option value="Employer">Employer</Select.Option>
    <Select.Option value="Payer">Payer</Select.Option>
  </Select>
</Form.Item>
```
```js
act(() => {
  fireEvent.mouseDown(getByRole('combobox', { name: 'I am a...' }));
});
await user.click(getByText('Private Practice'));
```

**Comment by mrdannael** [comment]
@upesic My solution worked from specific 4.x version. I don't remember which one to be honest.
I have no idea if this still works for 5.x version. Maybe they changed the implemenation of the Select component again and are using another event for calling the select to open, or another part of select is listening for `mousedown` event.

**Comment by ozayats** [comment]
@mrdannael, @kaichii solution works fine with v5.14.0
Thanks a lot!

**Comment by Luqman-Q** [comment]
I have tried the solution of v5.6 and v5.14 but it doesnt work with both of them.  Whats your jest and rtl version?
