### ISSUE TITLE
上传控件中 页面文件列表的文件名该怎么更改

### ISSUE THREAD

**Issue by ZhaoXinNian** [ant-design/ant-design#22070]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
上传文件中希望在上传响应后有自定义显示文件的方法

比如文件列表样式
比如可以更换名称
因为后端会重新定义文件名

### What does the proposed API look like?
文件在上传到服务器器收到响应后再执行渲染，可根据用户要求自定义渲染

**Comment by afc163** [comment]
在返回的 fileList 里修改 `file.name` 即可：https://ant.design/components/upload-cn/#onChange
