### ISSUE TITLE
Cascader级联选择能否提供一个接口，以逗号,或者| 符号来多关键词搜索 ，比如：图书|文艺|文学

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#22071]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
图书|文艺|文学 以多关键词来定位搜索，能够解决大数据下，快速搜索到想要的层级数据

### What does the proposed API look like?
默认以逗号或者以| 来搜索数据

**Comment by afc163** [comment]
Try custom showSearch.filter: https://ant.design/components/cascader-cn/#components-cascader-demo-search
