### ISSUE TITLE
定制主题颜色和border-radius未起作用

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design#22088]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
-----config/config.ts-----
theme: {
    'primary-color': '#ee8222',
    'border-radius-base': '4px',
  },

### What does the proposed API look like?
在config/config.ts中修改border-radius-base大小和主题颜色，但是页面并未更新

**Comment by yoyo837** [comment]
https://ant.design/docs/react/customize-theme-cn

**Comment by lishaoh** [comment]
@yoyo837 就是通过【定制主题】来更改主题颜色的，直接修改config.ts文件里面的theme

**Comment by lishaoh** [comment]
是css文件覆盖less文件了
