### ISSUE TITLE
Webpack 4: CSS Module removes styling when applied to component.modules.less

### ISSUE THREAD

**Issue by fredwin-o** [ant-design/ant-design#22084]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-tdd-6fg4m?fontsize=14&hidenavigation=1&theme=dark)

Visualisation
https://stackoverflow.com/questions/60614595/bundle-antd-with-webpack-less-css-modules-what-am-i-missing

### Steps to reproduce
- Update .less rule to:
          {
            loader: "css-loader",
            options: {
              sourceMap: true,
              modules: true
            }
          }
- Create test.module.less
- Apply className={styles.header} to heading

### What is expected?
Default.less theme and less CSS module styles should apply to all elements

### What is actually happening?
Upon applying test.module.less it overrides the default theme and removing any default styling. In this case, no default styling is applied to the button.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | ^16.13.0 |
| System | Windows |
| Browser | Chrome Version 77.0.3865.120 |

---
Adding extra rule to support .css

{
        test: /\.css$/,
        use: [
          {
            loader: "style-loader"
          },
          {
            loader: "css-loader",
            options: {
              sourceMap: true,
              modules: true
            }
          },
          {
            loader: "less-loader"
          }
        ]
      }

Allows both to work however ideally would like to stick with .less extension? If it's possible.

**Comment by zombieJ** [comment]
Maybe you can check side effect if it's tree shaking by webpack.

ref: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

Close since it's not a antd bug.
