### ISSUE TITLE
Table header and cell do not align properly

### ISSUE THREAD

**Issue by wang12124468** [ant-design/ant-design#22082]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
1. Click the demo into codepen
2. Then add scroll.y = 50 in table props
3. Check the element of header cell, such as Column 1, it is width of 124 .
4. However, check the element of it's body cell, it is width of 125 .

### What is expected?
There are same width.

### What is actually happening?
Table header and cell do not align properly

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | * |
| System | * |
| Browser | * |

**Comment by zombieJ** [comment]
<img width="344" alt="截屏2020-03-10下午9 40 24" src="https://user-images.githubusercontent.com/5378891/76317826-c17fd780-6317-11ea-8c0b-adb476fd4ffa.png">

I get the same of 125. Could you provide more info like borswer & system info?

**Comment by wang12124468** [comment]
@zombieJ But I was only set the scroll.y=50. 
![image](https://user-images.githubusercontent.com/17714343/76395607-ba59d780-63b2-11ea-9e73-cdb4c165866f.png)
![image](https://user-images.githubusercontent.com/17714343/76395510-6f3fc480-63b2-11ea-8c48-6fe20c15772d.png)
![image](https://user-images.githubusercontent.com/17714343/76395540-841c5800-63b2-11ea-84cc-94484bc24cd4.png)
![image](https://user-images.githubusercontent.com/17714343/76395813-1290d980-63b3-11ea-851a-6aef581f130e.png)

**Comment by wang12124468** [comment]
And I have another question.

Why your width of elements had no decimals？

And why you table had no vertical scrollbar？
![image](https://user-images.githubusercontent.com/17714343/76396244-c7c39180-63b3-11ea-8341-2e8d3e321a34.png)

**Comment by wang12124468** [comment]
@zombieJ I guess the cause of it is that I had set zoom ratio on my computer. So the elements have decimals. 

![image](https://user-images.githubusercontent.com/17714343/76406035-111bdd00-63c4-11ea-92a6-2a62dcfd5927.png)


But how can i solve it?

**Comment by wang12124468** [comment]
@afc163 这个确实存在问题呀，为什么不回我呢？
- 当电脑设置了自定义缩放，dom元素就会存在小数
![image](https://user-images.githubusercontent.com/17714343/76720110-d4ab0100-6776-11ea-817a-9ef4668aa67e.png)

- 而rc-table底层rc-resize-observer中使用的Math.floor，就会造成header单元格总是小1px。
[antd 官网示例](https://ant.design/components/table/#components-table-demo-fixed-columns-header)就有这个问题

![image](https://user-images.githubusercontent.com/17714343/76720241-37040180-6777-11ea-8807-0ef13a1212ea.png)
![image](https://user-images.githubusercontent.com/17714343/76720258-42572d00-6777-11ea-8e2b-ff1410ff3e98.png)

**Comment by zombieJ** [comment]
手头没有 windows，试了一下 mac 缩放也是对齐的。推测是 window 缩放测量问题， @wang12124468 ，来个 PR 修一下？
