### ISSUE TITLE
How can I use createFormField after migrate from v3 to v4

### ISSUE THREAD

**Issue by sweelemk** [ant-design/ant-design#22089]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/form/#Form.createFormField](https://3x.ant.design/components/form/#Form.createFormField)

### Steps to reproduce
-

### What is expected?
Could you give me an example how I can do it in a new version?

### What is actually happening?
I want to understand it

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.12.0 |
| System | MacOS |
| Browser | Chrome Version 80.0.3987.132 |

**Comment by CarolineBoyer** [comment]
I am not sure I understand your issue, doesn't 
https://ant.design/components/form/#components-form-demo-global-state
answer to your question ?

**Comment by sweelemk** [comment]
In version 3 that creates a new field we use 
`mapPropsToFields(props) {
    return {
      username: Form.createFormField({
        ...props.username,
        value: props.username.value,
      }),
    };
  },`

How can I do it in a new version?

**Comment by afc163** [comment]
Don't need `mapPropsToFields` anymore, we can pass props to fields by `setFields` now.

**Comment by sweelemk** [comment]
> Don't need `mapPropsToFields` anymore, we can pass props to fields by `setFields` now.

Thank you!
