### ISSUE TITLE
Form: Unable to fetch form methods

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#22081]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-pine-nuixt)

### Steps to reproduce
Open the console

### What is expected?
this.formRef.current returns null inside render() method.

### What is actually happening?
this.formRef returns current property with all form methods listed, but this.formRef.current is null. Due to this, we are unable to set validateStatus property to form item

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | Win 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`ref` can not use before it first render.

ref https://reactjs.org/docs/refs-and-the-dom.html

**Comment by mendoncanorma** [comment]
@zombieJ , i have updated the code, despite of that we are unable to access form methods inside render method.

**Comment by CarlosAmaral** [comment]
@zombieJ so then how can you validate a form on a componentDidMount for example?
