### ISSUE TITLE
3.x 升级到4.0后如何将table的数据传递给components

### ISSUE THREAD

**Issue by lhyzxc** [ant-design/ant-design#22099]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`components={{ body: { row: TableBodyRow } }}`
在使用components时希望在TableBodyRow 中能获取当前行的数据信息

### What does the proposed API look like?
`onRow={record => {
            return {
              record,
} }}`
在3.x中 通过在onRow中返回record能达到这一目的，但是在4.0后这种写法就报错了。

**Comment by YaoKaiLun** [comment]
"TableBodyRow" is loaded before "record" props on "onRow" and I also I found that "record" parameter of "onRow"  is not be updated when dataSource is updated.

**Comment by YaoKaiLun** [comment]
I solved this problem by the below method :
```
{
          (!value || value.length === 0) ? (
            <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} />
          ) : (
            <Table
              components={components}
              dataSource={value}
              columns={newColumns}
              onRow={row}
            />
          )
        }
```

**Comment by lhyzxc** [comment]
> "TableBodyRow" is loaded before "record" props on "onRow" and I also I found that "record" parameter of "onRow" is not be updated when dataSource is updated.

确实这样 加层判断就行了 感谢
