### ISSUE TITLE
Autocomplete shows "null" instead of nothing, when the value is null

### ISSUE THREAD

**Issue by dbousamra** [ant-design/ant-design#22093]
- [] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/async-sun-x0cfy)

### Steps to reproduce
Change version from 4.0.2 back to 4.0.0 and you will see this issue disappears.

### What is expected?
When the value is null, i expect the control to show nothing.

### What is actually happening?
It is rendering the string 'null' in the input box.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | OSX |
| Browser | Chrome |

**Comment by hamzakaya** [comment]
[![](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/eloquent-bas-o4hjn) 
You can send the current data from value, you must send the options you want to be completed via 'options'

**Comment by dbousamra** [comment]
@hamzakaya This doesn't change anything. The value still reads as null.

**Comment by dbousamra** [comment]
Is this fixed? It appears to still be an issue in 4.0.4
