### ISSUE TITLE
`Menu.Item` renders with class name as `undefined-item` if put inside a fragment node

### ISSUE THREAD

**Issue by shackra** [ant-design/ant-design#22097]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-clb4t?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
put Menu.Item node inside a React.Fragment

### What is expected?
Menu.Item should look and behave as normal when put inside a React.Fragment node

### What is actually happening?
you will see that it lose format and breaks the app if you hover

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.12.0 |
| System | GNU/Linux |
| Browser | Firefox 73 |

---
the use case here is when using @casl/react, given that I would like to hide some menu options if the user does not have the right permissions to access some locations of the app

**Comment by afc163** [comment]
Duplicate of #18022

**Comment by dangngoctam00** [comment]
I have same problem when wrap menu item inside another component to check permission and returned as fragment. I've read many issues but none of them is solved. :/
