### ISSUE TITLE
input、Checkbox组件等..设置了defaultValue以后，rerender无效。

### ISSUE THREAD

**Issue by ReadingSteiner** [ant-design/ant-design#221]
我给input，Checkbox组件等设置了defaultValue以后，通过setState触发rerender（state里已经改变），但是组件UI上却仍然停留在defaultValue再也不变化了。

**Comment by afc163** [comment]
外界控制状态用 value 。

https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by ReadingSteiner** [comment]
那defaultValue设置了以后不可以改的话，那我为啥不直接设value，反正都不可以改

**Comment by afc163** [comment]
请阅读官方文档，里面讲的挺清楚了。
