### ISSUE TITLE
4.0版本中的Form.Item组件属性name,为什么这样写 name={`a[${index}].des`}不能自动转成一个数组对象，3.0是可以的

### ISSUE THREAD

**Issue by lgf196** [ant-design/ant-design#22107]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by yoyo837** [comment]
迁移需要在意哪些API有变化，留心看迁移文档  
https://ant.design/docs/react/migration-v4-cn
https://ant.design/components/form/v3-cn/

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/76393442-84b2ef80-63ae-11ea-87a5-ac6a03140c4f.png)

**Comment by lgf196** [comment]
@yoyo837 谢谢！
