### ISSUE TITLE
Panel selected DatePicker value is different from onInput value

### ISSUE THREAD

**Issue by pnorbi-bp-grape** [ant-design/ant-design#22106]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/elijah1/pen/poJabeO](https://codepen.io/elijah1/pen/poJabeO)

### Steps to reproduce
1. Chose a date from the panel by mouse click,  etc. 2020-03-11 then submit
2. Check the console output, date has a time value (Wed Mar 11 2020 07:45:37 GMT 0100)
3. Change the DatePicker value by keyboard, etc. 2020-03-12 then submit
4. Check the console output, date has no time value (Thu Mar 12 2020 00:00:00 GMT 0100)

### What is expected?
There is no difference between keyboard and panel selected date.

### What is actually happening?
Date values are different.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 80.0.3987.132  |

---
I use DatePicker with dayjs config, but it works as the same way I wrote above.

**Comment by zombieJ** [comment]
DatePicker do not care the time part value. If you need full datetime, you should use `showTime` for time pick part.
