### ISSUE TITLE
Table组件滚动条问题

### ISSUE THREAD

**Issue by ndqbaby** [ant-design/ant-design#22109]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
滚动条样式重定义过情况下， Table组件设置scroll:{y:400}, columns中设置最后一个列fixed:right，在浏览器宽度足够情况下。会有错位

### What is expected?
列表滚动的时候固定列和非固定列每一行没有错位

### What is actually happening?
列表滚动到底部到时候，设置了fixed:right的列较其他列还能多向上滚动横向滚动条高度的像素高度，导致固定列和非固定列每行数据高度之间错位

| Environment | Info |
|---|---|
| antd | 3.26.11 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome最新版 |

---
个人所查到的原因为:滚动条样式 .ant-table-fixed-header .ant-table-body-inner{
                                               overflow: scroll;
                                              }
在上面的样式中，默认了overflow-x:scroll 但是整个Table组件设置的scroll属性没有设置x。
通过查看dom节点，类ant-table-fixed-left下的ant-table-body-inner和 类ant-table-scroll下的ant-table-body 都没有设置样式overflow, 但是唯独ant-table-fixed-right下ant-table-body-inner设置了样式 overflow: scroll; 这才导致高度差

**Comment by ndqbaby** [comment]
https://codesandbox.io/s/antd-reproduction-template-bnzz8
@ant-design-bot

**Comment by ndqbaby** [comment]
![1583912945867](https://user-images.githubusercontent.com/43486949/76394102-ec1d6f00-63af-11ea-8ca9-a906ffad7131.jpg)

**Comment by afc163** [comment]
@ndbroadbent 你给的例子看上去没有问题。

**Comment by ndqbaby** [comment]
我的例子在我macmini上有问题，你看上面的截图 的确有错位，可以试试用鼠标滑动滚动条看。
我在我同事window系统上没问题。 但是我macmini就会这样。

**Comment by ndqbaby** [comment]
我查看css 是因为 .ant-table-fixed-header .ant-table-body-inner{
overflow: scroll;
}   这个问题，把它注释了就没问题,不会错位
chrome版本：版本 80.0.3987.132（正式版本） （64 位）
