### ISSUE TITLE
Table column render method that returns a colSpan / rowSpan config object is not accepting data-* attributes

### ISSUE THREAD

**Issue by mcmxc** [ant-design/ant-design#22116]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-rgb-2pce7)

### Steps to reproduce
Use render method in Column component (or a column object in columns array) that returns a config object as described in docs:
```
render: age => ({
        children: age,
        props: { "data-column": "Age", style: { color: "red" } }
      })
```

### What is expected?
<td> element should have `data-column="Age"` attribute in the html

### What is actually happening?
no `data-column` attribute present in html

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.12 |
| System | Mac OS Mojave |
| Browser | Latest Chrome |

---
This was working in 3.x version. This behavior is required for plenty of cases which custom data attributes are being used for. (different testid's, css attr() rules etc.)

**Comment by afc163** [comment]
similar issue: #22125
