### ISSUE TITLE
[3.26.12] RangePicker手动修改开始日期大于结束日期时会清空结束日期

### ISSUE THREAD

**Issue by qianyiyang** [ant-design/ant-design#22118]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-hill-xmq8t)

### Steps to reproduce
选择日期,然后手动修改开始日期大于结束日期,结束日期会被清空,这时点击提交,会报format错误,也没有必填的提示.

### What is expected?
结束日期不清空

### What is actually happening?
结束日期被清空

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.7 |
| System | windows 10 |
| Browser | chrome 79 |

---
之前的版本不会清空结束日期,现在这版本清空之后影响了很多以前的页面,暂时也不能升4.0,所以希望能修复一下

**Comment by Jennychen66** [comment]
Does this issue already fixed  ? I checked the code it the CodeSandBox , the endtime will not be cleared and it always larger than the startTime

**Comment by qianyiyang** [comment]
没有
![123](https://user-images.githubusercontent.com/22905113/79095661-8e54bc00-7d8d-11ea-893a-09d63a8c6c77.gif)

**Comment by qianyiyang** [comment]
> Does this issue already fixed ? I checked the code it the CodeSandBox , the endtime will not be cleared and it always larger than the startTime

![image](https://user-images.githubusercontent.com/22905113/79319027-635b9b00-7f3a-11ea-8bb8-16bb7732285c.png)

**Comment by qianyiyang** [comment]
> Does this issue already fixed ? I checked the code it the CodeSandBox , the endtime will not be cleared and it always larger than the startTime

![123](https://user-images.githubusercontent.com/22905113/79319175-8f771c00-7f3a-11ea-8d37-607f1eebc418.gif)

**Comment by afc163** [comment]
@zombieJ 有空看看 #23604，手动输入的时候，输入到第二个前面就被清空了，还是很影响体验的。
