### ISSUE TITLE
componentWillReceiveProps 里面使用 formRef.current 报null

### ISSUE THREAD

**Issue by google88888888** [ant-design/ant-design#22120]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
componentWillReceiveProps 里面使用 formRef.current 报null

### What is expected?
正常使用 formRef.current

### What is actually happening?
componentWillReceiveProps 里面使用 formRef.current 报null

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | "react": "^16.12.0", |
| System | windows |
| Browser | chrome 版本 80.0.3987.132（正式版本） （64 位） |

**Comment by google88888888** [comment]
> Hello @google88888888. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @google88888888, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

父组件打开子组件里面，子组件是modal，但是子组件的状态都来自公共redux，也就是没有父组件传子组件值。在子组件里面的componentWillReceiveProps使用formRef.current会报空

**Comment by yoyo837** [comment]
你好 @google88888888, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。https://u.ant.design/codesandbox-repro

**Comment by zombieJ** [comment]
`componentWillReceiveProps` 已经是 `UNSAFE` 的了，转用 `componentDidMount` 和 ``componentDidUpdate` 代替。
