### ISSUE TITLE
Input.search calls onChange after onSearch if the Clear Icon clicked

### ISSUE THREAD

**Issue by ostrich-g** [ant-design/ant-design#22121]
- [ X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5qtfb)

### Steps to reproduce
1. input something
2. click clear Icon

### What is expected?
fire onChange before onSearch

### What is actually happening?
fire onChange after onSearch

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.12.0 |
| System | macOS 10.13.3 |
| Browser | Chrome 80.0.3987.132 |

---
Input.search fire onChange before onSearch if input something and search.   
It should be consistent if the clear Icon clicked

**Comment by zombieJ** [comment]
What's the issue with current order?

**Comment by eternalphane** [comment]
@zombieJ I'm using `Input.Search` as controlled component, and firing `onChange` after `onSearch` force me to read the `value` parameter instead of omitting it and use the value in `state`, which is unintuitive.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18729#issuecomment-529502936
