### ISSUE TITLE
Month and year select options are abbreviated with an ellipsis which makes them unreadable

### ISSUE THREAD

**Issue by KevinHurts** [ant-design/ant-design#22123]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/calendar/](https://ant.design/components/calendar/)

### Steps to reproduce
When selecting year or month selection all options are abbreviated with an ellipsis. 

### What is expected?
Values should not be abbreviated

### What is actually happening?
Values are abbreviated

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.12.0 |
| System | macOS Catalina v10.15.3 |
| Browser | Google Chrome Version 80.0.3987.132 |

---
The issue also occurs in the examples for ant design

**Comment by KevinHurts** [comment]
Image of issue:
![image](https://user-images.githubusercontent.com/1827410/76407259-5cfe6000-638b-11ea-9cfc-d68ccbfdfac7.png)

Additional comments:
The issue also occurs on Safari and Firefox.
In Firefox even the label gets abbreviated.

**Comment by yoyo837** [comment]
Duplicated of #22017

**Comment by KevinHurts** [comment]
Not really duplicate since this issues is about the Calendar and not about regular selects. My issue also occurs on other browsers than Firefox. They are probably related though.
