### ISSUE TITLE
Table onRow does not support data-xxx html5 attributes in antd-4.0.2

### ISSUE THREAD

**Issue by SebastianKG** [ant-design/ant-design#22125]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
```
<Table
  [...]
  //this onRow won't work
  onRow={(rowObject) => {'data-whatever': 'does not work'}}
/>
```

### What is expected?
onRow to allow developers to include arbitrary attributes for the row element as the docs state

### What is actually happening?
only events seem to be supported

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | react 16.9.23 |
| System | macOS 10.14.6 |
| Browser | Chrome latest |

**Comment by afc163** [comment]
similar with #22116, merge into it.
