### ISSUE TITLE
Slider - the  value of slider are inconsistent before/after mouse up in vertical mode

### ISSUE THREAD

**Issue by MickeyMiao7** [ant-design/ant-design#22128]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-d0wzb)

### Steps to reproduce
1. Set `vertical` for Slider  
2. Click somewhere on the rail and hold the mouse, then check the value shown on tooltip (make sure you "click" the point, not dragging)
3. Release the mouse and then check the value on tooltip again. 
4. The two values are inconsistent.

### What is expected?
The values of slider should remain the same before/after mouse up.

### What is actually happening?
The values are in consistent.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Chrome 80.0 |

**Comment by MickeyMiao7** [comment]
![GIF](https://user-images.githubusercontent.com/13026247/76417379-bd1af380-63d7-11ea-9103-6f2bb3580681.gif)

**Comment by wendellhu95** [comment]
When you drag the handle to an end, you can see that it's not perfectly centered with  the track. I will try to fix this.

**Comment by afc163** [comment]
same as #19682

**Comment by wendellhu95** [comment]
Could be closed.

**Comment by yoyo837** [comment]
Fixed in #22135
