### ISSUE TITLE
table设置了固定列之后。滚动条显示问题

### ISSUE THREAD

**Issue by ranzhu123** [ant-design/ant-design#2212]
设置了左侧固定之后，因为固定的那个div的层叠在table上面，导致滚动条往左侧滚的时候看不到。是否可以设置左侧固定的div给滚动条留出点空间？
![image](https://cloud.githubusercontent.com/assets/12227617/16438040/9e865202-3dde-11e6-990f-d89c8472e804.png)
而且有个别时候拖动横向滚动条的时候，标题栏不跟着滚动，必须点击一下table才能跟着滚动。

**Comment by ranzhu123** [comment]
之前提到的滚动滚动条固定栏不跟着动，挺严重的，滚动的时候，fix列不动。
![image](https://cloud.githubusercontent.com/assets/12227617/16444657/b689de5e-3e11-11e6-91b0-c114131a93bc.png)
@afc163

**Comment by ranzhu123** [comment]
解决了，在ant-table-body上触发一下mouseenter事件就可以了

**Comment by afc163** [comment]
是组件问题么？组件可有需要改造的地方？

**Comment by ranzhu123** [comment]
我不知道我这个问题普遍吗，因为我的场景是点击table的一个单元格，然后进入另一个table所以造成了没有触发mouseenter的现象（因为鼠标还在table上面，但是我已经进入了另一个组件，另一个组件也是用的table），就导致了没有设置好scrollTarget，后面表头和左侧就不跟着scroll滚动，如果执行一下mouseenter就好了。如果这种场景多的话，可能需要改，是否能在table刚初始化数据的时候讲target设置好，现在还需要执行一次mouseenter。不知描述清楚了吗？

**Comment by afc163** [comment]
大概明白了，组件直接切换导致 mouseenter 没有机会触发。

我晚点看看怎么修复。

**Comment by ranzhu123** [comment]
好的
