### ISSUE TITLE
3.x 版本的 Table 组件导致 Hot Reload 失败

### ISSUE THREAD

**Issue by jas0ncn** [ant-design/ant-design#22136]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jas0ncn/ant-design-table-issue-demo](https://github.com/jas0ncn/ant-design-table-issue-demo)

### 准备最小化复现项目仓库

```bash
git clone https://github.com/jas0ncn/ant-design-table-issue-demo.git && cd ant-design-table-issue-demo

# 安装依赖
npm ci

# 启动项目
npm start
```

### 复现步骤

待 `npm start` 启动成功，页面成功渲染之后，注释 `src/App.js` 中第 6 行的 `console.log`，可发现页面 hot reload 失败并报错。

![2020-03-12 01 38 44](https://user-images.githubusercontent.com/3380894/76446764-7c849f80-6402-11ea-9afe-4d2f73ed2870.gif)

### What is expected?
hot reload 不报错

### What is actually happening?
hot reload 报错导致只能刷新页面

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.13.0 |
| System | macOS |
| Browser | Edge 80.0.361.62 |

---
我项目里用的 `3.25.1` 和最小复现 demo 用到的最新的 `3.26.13` 都有问题，`4.x` 经测试不受影响。

**Comment by jas0ncn** [comment]
疑似和 `https://github.com/react-component/table/blob/6.2.x/src/Table.js#L371` 有关

**Comment by jas0ncn** [comment]
@zombieJ 问题不严重，我来瞧瞧，可以打个 ` Someone working on it`

**Comment by jas0ncn** [comment]
@zombieJ 已向 `rc-table` 提交 PR：https://github.com/react-component/table/pull/431

**Comment by RwwL** [comment]
I just created a test case for a similar hot-reload issue I noticed with the `Collapse` component: https://github.com/RwwL/antd-collapse-issue

Do you think this is a closely related issue, @jas0ncn? Any chance it can be addressed in your PR, or should I open a separate issue for it?
