### ISSUE TITLE
Modal: option not to close with cancel key

### ISSUE THREAD

**Issue by AriLFrankel** [ant-design/ant-design#22137]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am wanting to use a modal that does not close...ever. I do not want users to be able to close the modal by pressing the escape key. I have passed in props `closable:false` and `mask-closable:false`

I see that a similar issue was opened and closed without resolution, https://github.com/ant-design/ant-design/issues/8818

### What does the proposed API look like?
`cancel-closable: boolean`
if true, modal closes when the cancel key is pressed
if false, modal does not close when the cancel key is pressed

**Comment by zombieJ** [comment]
`keyboard={false}`

**Comment by anztrax** [comment]
thanks bro @zombieJ  👍
