### ISSUE TITLE
Tree Component Async loadData Type problem

### ISSUE THREAD

**Issue by francisl** [ant-design/ant-design#22138]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-bush-fwiqu)

### Steps to reproduce
try to use the example for async tree on the main documentation : https://ant.design/components/tree/
Then use typescript type system.

### What is expected?
Be able to fully use typescript with the example to get up and running.
`onLoadData = (treeNode: EventDataNode) => { ` should let me use treeNode.children

### What is actually happening?
onLoad require a function signature of `(treeNode: EventDataNode) => Promise<void>) | undefined`

But EventDataNode don't have any children as used in the documentation.

Here is the Tree props https://github.com/ant-design/ant-design/blob/master/components/tree/Tree.tsx#L94

Then it inherit the loadData from RcTreeProps

Then the 'loadData' Props require the EventDataNode https://github.com/react-component/tree/blob/master/src/Tree.tsx#L115

The EventDataNode extend DataNode but with an explicit Omit of 'children' https://github.com/react-component/tree/blob/master/src/interface.tsx#L21

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | new-issue.ant.design |
| Browser | Latest Firefox, Chrome |

---
loading typescript error on codesandbox is a bit slow, need to wait for it

**Comment by hengkx** [comment]
@zombieJ See if there is any problem with this PR?

**Comment by jinqingxu** [comment]
Hi, is this issue solved? I met the same issue today. It would be super helpful if it can be solved.
