### ISSUE TITLE
Menu菜单项选中后，鼠标hover时没有高亮，设计如此？

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2213]
MenuItem选中后，鼠标hover时没有高亮
MenuItem包含 <a> 字体颜色不对

### 本地环境

- antd 版本: 1.6.2
- 操作系统及其版本：ubuntu 16.04
- 浏览器及其版本: 50.0.2661.102 Ubuntu 16.04 (64-bit)

### 可重现的在线演示
http://codepen.io/anon/pen/dXyQYG?editors=0110

官网也可以重现, dark主题比较明显
http://ant.design/components/menu#components-menu-demo-theme
http://ant.design/docs/spec/layout#docs-spec-layout-demo-aside

**Comment by afc163** [comment]
> MenuItem选中后，鼠标hover时没有高亮

上面修复了。

>  MenuItem包含 字体颜色不对

不太明白这个指的是啥？

**Comment by codering** [comment]
MenuItem包含``` <a />``` 字体颜色不对
