### ISSUE TITLE
Form.List：类型“typeof Form”上不存在属性“List”

### ISSUE THREAD

**Issue by Lanboo** [ant-design/ant-design#22134]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Lanboo/bookkeeping-web/commit/3532fa39fb837863ada10d9edd4d071b9b152fe9](https://github.com/Lanboo/bookkeeping-web/commit/3532fa39fb837863ada10d9edd4d071b9b152fe9)

### Steps to reproduce
```
<Form {...formLayout}>
  <Row>
    <Col span={12}>
      <FormItem/>
    </Col>
  </Row>
  <Form.List>
          {fields => (
            <div>
              {fields.map(field => (
                <Form.Item {...field}>
                  <Input />
                </Form.Item>
              ))}
            </div>
          )}
  </Form.List>
</Form>
```

### What is expected?
应该Form.List的吧

### What is actually happening?
报错：类型“typeof Form”上不存在属性“List”。
![image](https://user-images.githubusercontent.com/19277171/76435888-8acabf80-63f2-11ea-922e-05becf429d8b.png)

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | Windows |
| Browser | Chrome 79.0.3945.117（正式版本） （64 位） |

**Comment by zombieJ** [comment]
```diff
- import { Form } from '@ant-design/compatible';
+ import { Form } from 'antd';
```

**Comment by Lanboo** [comment]
> ```diff
> - import { Form } from '@ant-design/compatible';
> + import { Form } from 'antd';
> ```


```
import { Form } from '@ant-design/compatible';
const FormItem = Form.Item;

// return 部分代码
<FormItem label="业务场景">
    {form.getFieldDecorator('busiType', {
    rules: [{ required: true, message: '不能为空！' }],
    })(
    <Select<string>
        allowClear
        placeholder="业务场景"
        style={{ width: '100%' }}
        onChange={value => setBusiType(value)}
    >
        {DicSupport.dataEnum.selectTypeData['busiType']?.map((record: Dic) => (
        <Select.Option value={record.dicKey}>{record.dicValue}</Select.Option>
        ))}
    </Select>,
    )}
</FormItem>
```
`form.getFieldDecorator`这种获取空间的方式，在`Form from 'antd'`里并不支持的

**Comment by yoyo837** [comment]
直接迁移到新Form API 上来吧，不要长期停留在`@ant-design/compatible`上

**Comment by Lanboo** [comment]
那在新From API上，修改界面设置已有值，是通过控件的value属性直接赋值吗？

在`@ant-design/compatible`里：通过`initialValue`赋值的
```
<FormItem key="userCode" {...this.formLayout} label="用户代码">
    {form.getFieldDecorator('userCode', {
    initialValue: formVals.userCode,
    })(<Input placeholder="用户代码" disabled />)}
</FormItem>
```

**Comment by yoyo837** [comment]
https://ant.design/docs/react/migration-v4-cn
https://ant.design/components/form/v3-cn/

文档有写

**Comment by Lanboo** [comment]
感谢~
