### ISSUE TITLE
Tweak Select default width

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#22149]
@zombieJ 对于这种不设宽度的 Select 上面能展示，下拉框内展示不完整的情况，是不是可以调整调整下默认宽度，尽量让用户不用操心。

https://codesandbox.io/s/quirky-dewdney-3vfl3

<img width="123" alt="image" src="https://user-images.githubusercontent.com/507615/76491292-51349b80-6468-11ea-9047-702642b03851.png">

_Originally posted by @afc163 in https://github.com/ant-design/ant-design/pull/22148#issuecomment-598018557_

**Comment by zombieJ** [comment]
原本是有个默认 `100px` 宽度，后来不记得为啥又改成和 v3 一样按照内容宽度了。

**Comment by zombieJ** [comment]
找到了：https://github.com/ant-design/ant-design/pull/20538

**Comment by zombieJ** [comment]
设置不设置都会有影响，还是应该让用户用 `dropdownMatchWidth` 来展示全部。
