### ISSUE TITLE
SubMenu not disappear always

### ISSUE THREAD

**Issue by Flourad** [ant-design/ant-design#2214]
"ant-version": "1.6.2",  using ''babel-plugin-ant" which is recommended~

![image](https://cloud.githubusercontent.com/assets/1535874/16441182/d95ac32e-3dfa-11e6-9fa6-2528d8f4ff3c.png)

the error in console：
![image](https://cloud.githubusercontent.com/assets/1535874/16441255/7f2f6cfa-3dfb-11e6-8792-29fbbc9390c8.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001
