### ISSUE TITLE
新版本是否支持tab组件的多开，强烈需求

### ISSUE THREAD

**Issue by zengyunchun** [ant-design/ant-design#22141]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
是否支持tab组件的多开

### What does the proposed API look like?
是否支持tab组件的多开

**Comment by zombieJ** [comment]
多开指的是？

**Comment by zengyunchun** [comment]
就是可以同时打开多个tab，在之间进行切换呢，每一个互不影响


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"二货机器人"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午10:36
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"灵动穿越梦想"<595724205@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 新版本是否支持tab组件的多开，强烈需求 (#22141)





 
多开指的是？

**Comment by yoyo837** [comment]
非唯一active的？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/5812

**Comment by zengyunchun** [comment]
就是4.0还是得自己实现吧，官方不支持是吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"偏右"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午10:41
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"灵动穿越梦想"<595724205@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 新版本是否支持tab组件的多开，强烈需求 (#22141)





 
ant-design/ant-design-pro#5812

**Comment by afc163** [comment]
这是 pro 相关的讨论，和 antd 无关。

**Comment by zengyunchun** [comment]
好的，那 pro 也不考虑官方支持吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"偏右"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午10:46
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"灵动穿越梦想"<595724205@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 新版本是否支持tab组件的多开，强烈需求 (#22141)





 
这是 pro 相关的讨论，和 antd 无关。

**Comment by afc163** [comment]
对，详情见 https://github.com/ant-design/ant-design-pro/issues/220

**Comment by zengyunchun** [comment]
好的，那多谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"偏右"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月12日(星期四) 上午10:52
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"灵动穿越梦想"<595724205@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 新版本是否支持tab组件的多开，强烈需求 (#22141)





 
对，详情见 ant-design/ant-design-pro#220
