### ISSUE TITLE
组件 RangePicker 的属性 `activePickerIndex` 希望是受控的

### ISSUE THREAD

**Issue by yutingzhao1991** [ant-design/ant-design#22158]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
open 用受控方式自己控制后会导致第二次打开后首先让选择结束日期，这会让人很疑惑。

### What does the proposed API look like?
https://github.com/react-component/picker/blob/649ec52eca7c8d484cc7945d9477c9d50036ba7d/src/RangePicker.tsx#L196 支持 `activePickerIndex` 这个属性实现 activePickerIndex 的受控模式。

**Comment by zombieJ** [comment]
突然想到这个不能 export 出来，`activePickerIndex` 是用户点击的，不应该受控。用处特殊，加上 `@private` 标记好了。

**Comment by 99Arrzel** [comment]
This feature is no longer working for 5.14.0 and above
