### ISSUE TITLE
Divider是否用padding更好一些？

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#22156]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-btsw1)

### Steps to reproduce
直接看

### What is expected?
不出现滚动条

### What is actually happening?
出现滚动条

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by afc163** [comment]
这个和直接 div 或者 hr 表现一样，不是 Divider 特有的问题。

- div: https://codesandbox.io/s/antd-reproduction-template-0dgtu
- hr: https://codesandbox.io/s/antd-reproduction-template-0dgtu

用 margin 的原因是保持和 hr 的行为一致，可以利用 margin 的边距合并排版特性。
