### ISSUE TITLE
table问题

### ISSUE THREAD

**Issue by ndqbaby** [ant-design/ant-design#22152]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lbrp7)

### Steps to reproduce
1.设置table的属性scroll={{y:200}}
2.拉伸浏览器宽度，在一定宽度下，table的tbody会出现滚动条

### What is expected?
table不出现横向滚动条，因为我scroll没有设置x的值

### What is actually happening?
table的tbody区域快会出现滚动条

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.12.0 |
| System | window |
| Browser | chrome最新版 |

**Comment by ndqbaby** [comment]
设置table scroll属性为{y:200}
![999EC0BA79DE62FD75E3EC046C412E6F](https://user-images.githubusercontent.com/43486949/76493662-1cc3de00-646e-11ea-99d1-980c6bbcc3c6.png)

**Comment by ndqbaby** [comment]
如下图：div里面默认的overflow-x为auto，需要强制设置为overflow-x:hidden
![B2F1F87EB9AAEA39C47A3E99187CE42A](https://user-images.githubusercontent.com/43486949/76493867-9c51ad00-646e-11ea-9a7c-ea5daaa34f15.png)

**Comment by yoyo837** [comment]
文档有说只要不设置x就一定没有横向滚动条吗？如果你的表格压缩到很窄根本放不下列宽也不许滚动？

**Comment by afc163** [comment]
加了 overflowX 确实看上去符合预期一点，但是我测了一下内容就被隐藏了。考虑了一下，极端情况下出现滚动条对于用户还能够看到内容会是比较好的，这个问题不修了。

**Comment by ndqbaby** [comment]
@yoyo837 不是说不允许滚动，只是目前滚动了的只有tbody,header那块是没有滚动的, 而且这块有时候不只是出现在压缩很窄的情况下， 我这里还有一种情况是columns每一项都设置了width ，然后浏览器在宽度缩放在500px样子，也会出现类型情况，只有tbody滚动，theader不动，我只是以官方例子修改了下，提出了为什么会出现这样都原因。其实这个原因在某写情况下也会发生

**Comment by ndqbaby** [comment]
@afc163 目前在column多个都情况下，并且每个设置了width，也会有类似情况出现。而且不是上述极端情况在宽度500px的时候 也会有
![2539D46E-2C5F-475E-9296-E7FFC80C7172](https://user-images.githubusercontent.com/43486949/76507055-12faa480-6487-11ea-90e3-d17b9e70c903.png)

**Comment by afc163** [comment]
我考虑是如果不出现滚动条，在你这个场景内右侧的内容用户是不是就看不见了。
