### ISSUE TITLE
Tree组件 全选 或 上级菜单 被勾选后，动态添加菜单 新增的菜单会自动被勾选 

### ISSUE THREAD

**Issue by MysteriousRookie** [ant-design/ant-design#2215]
Tree组件中菜单被全选后保存数据库，全选 状态 所有的  key 都会被保存，在程序中增加一个菜单，由于之前全选 上级菜单的key 已经被保存，所以 新增菜单 也会为选中状态，但是数据库中 是没有这条菜单的key的。

**Comment by warmhug** [comment]
试试 `checkStrictly`

**Comment by MysteriousRookie** [comment]
使用 checkStrictly 用户勾选上级菜单 那么下级就不能自动选中了，这样太不友好了  还有就是  程序初始的默认值 也不能显示了
这是我Tree 组件所有使用的属性，
showLine multiple={true} 
checkable={true} 
checkStrictly={true} 
autoExpandParent={autoExpandParent}
expandedKeys={expandedKeys}     
onExpand = {this.onExpand} 
checkedKeys={Codes} 
onCheck={this.onCheck}

**Comment by warmhug** [comment]
初始值是能设置的、包括半选的值。选中关系的控制是比较麻烦点。
