### ISSUE TITLE
4.0 中 Button 组件缺失 ButtonGroup 文档说明

### ISSUE THREAD

**Issue by geekrainy** [ant-design/ant-design#22151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在 3.x 中，有关于 Button.Group 的使用示例及说明，在 4.0 中缺少。

### What does the proposed API look like?
补充相关文档说明。

**Comment by shaodahong** [comment]
Duplicate of #21278
