### ISSUE TITLE
Extends Picker to support quick pick

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#22150]
![1581678213553-b1612ef1-873e-48ec-bff4-ce780ae15384](https://user-images.githubusercontent.com/5378891/76492304-d8830e80-646a-11ea-943d-fde5f1bd084d.png)

**Comment by rashmimh** [comment]
Any update on this? It will be nice to have this fantastic feature. I am following it.

**Comment by zombieJ** [comment]
理解有误，快速选择器不是最终需求。合入 tech ui 开发，Quarter Picker 保留不删了。
