### ISSUE TITLE
 关于resizeable 在table中的应用问题

### ISSUE THREAD

**Issue by LauraPig** [ant-design/ant-design#22163]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-ptolemy-t2txu)

### Steps to reproduce
在对包含排序（sort）列的宽度调整时候，会触发列的排序行为。

### What is expected?
期望能够在调整列宽时候，不要触发或者可以控制是否触发sort行为。

### What is actually happening?
目前同时触发了sort排序

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13 |
| System | mac Os |
| Browser | chrome  77.0.3865.90 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14647

要更新一下 demo，问的人有点多。

**Comment by LauraPig** [comment]
有解决方案了吗？大概什么时候更新demo？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14647#issuecomment-467865540
