### ISSUE TITLE
Table 锁定列后 错误隐藏列

### ISSUE THREAD

**Issue by ShaofeiZi** [ant-design/ant-design#22160]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/753f5ae5?mode=jsx](https://riddle.alibaba-inc.com/riddles/753f5ae5?mode=jsx)

### Steps to reproduce
UV PV 等列 屏幕缩小后 被隐藏 且 下方 滚动条无法直接滚动过去

### What is expected?
下方 滚动条可直接滚动过去

### What is actually happening?
下方 滚动条不可直接滚动过去

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.13.0 |
| System | "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36" |
| Browser | Chrome/80.0.3987.132 |

**Comment by afc163** [comment]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/507615/76506786-b13a3a80-6486-11ea-8d5c-3e901cd756ef.png">

**Comment by ShaofeiZi** [comment]
https://riddle.alibaba-inc.com/riddles/753f5ae5?mode=jsx
riddle 已更新
指定宽度 且 生效 
未能解决

**Comment by ShaofeiZi** [comment]
关键在 scroll={{ x: 大于表格宽度 }}

**Comment by afc163** [comment]
```diff
- scroll={{ x: true }}
+ scroll={{ x: 'max-content' }}
```

先这样改，把表格宽度用内容撑开。

**Comment by afc163** [comment]
修改 https://github.com/ant-design/ant-design/issues/21596 时有点边界没考虑到，我晚点一起修复一下。

**Comment by afc163** [comment]
已修复 `rc-table@6.10.14`，请重新安装 `node_modules`。
