### ISSUE TITLE
有没有人像我一样觉得 Form.item 其实也是可以简化掉得？

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design#22164]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://nanxiaobei.github.io/ant-plus/

比如这个项目对 form 得简化 用起来十分之清爽 几乎跟写html时代得体验一样

### What does the proposed API look like?
像写H5一样写form

**Comment by zombieJ** [comment]
antd 的 Form 尽可能提供拓展能力，用户于之上可以自定义喜爱的封装形式哈。antd 本身尽可能避免过多注入。
