### ISSUE TITLE
[4.0.2] Not passing data attributes in <Select.Options />

### ISSUE THREAD

**Issue by remo1** [ant-design/ant-design#22162]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-allen-82p2h)

### Steps to reproduce
Pass custom attribute to select option

### What is expected?
To pass down custom attribute to select option 

### What is actually happening?
Not passing the custom attributes

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | latest |
| System | Mac Os |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Hi, what's the requirement of padding `data-*` prop?

**Comment by remo1** [comment]
It's blocking our upgrade to 4.0 and makes us need to add an extra span inside the select option to just pass the data-qa to a select item. 

Also, because the data-qa is not passed down it breaks our tests

**Comment by zombieJ** [comment]
Got it. Thanks for feedback.
