### ISSUE TITLE
TreeSelect 增加自定义回显内容

### ISSUE THREAD

**Issue by cnzsb** [ant-design/ant-design#22177]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
已选中内容默认显示为子节点的 title，能不能自定义回填的内容。比如有如下 2 个节点：

```
- 男性
  - 0-3 岁
  - 3-18 岁
  - 18 岁以上
  - 60 岁以上
- 女性
  - 0-3 岁
  - 3-18 岁
  - 18 岁以上
  - 60 岁以上
```

现在两个都选中 “18 岁以上” 则在选中位置展示的 2 个标签都为 “18 岁以上”，如果可以自定义为 “男性 - 18 岁以上”、“女性 - 18 岁以上”，则可以清晰表现所选中节点

### What does the proposed API look like?
```
<TreeSelect
  ...
  selectedRender={
    (nodeProps) => `${getParentProps(nodeProps.id).title} - ${nodeProps.title}`
  }
/>
```

**Comment by afc163** [comment]
`treeNodeLabelProp`

**Comment by cnzsb** [comment]
`treeNodeLabelProp` 设置为 `title` 也只不过是展示了子节点的文字信息罢了，除非在一开始就设置这个 `title`，那就太冗余了，看起来如下: 

```
- 男性
  - 男性 - 0-3 岁
  - 男性 - 3-18 岁
  - 男性 - 18 岁以上
  - 男性 - 60 岁以上
- 女性
  - 女性 - 0-3 岁
  - 女性 - 3-18 岁
  - 女性 - 18 岁以上
  - 女性 - 60 岁以上
```

除非可以在 TreeNode props 中增加自定义 `props`，比如可以传入自定义 `selectedTitle: 'customTitle'`，这样在格式化 `treeData` 的时候就可以插入自己想要的格式，然后配合 `treeNodeLabelProp="selectedTitle"` 才可以正常工作

**Comment by afc163** [comment]
treeNodeLabelProp 需要你提前处理数据，比如搞一个 `completeTitle` 属性，把父节点的信息递归加起来。

**Comment by cnzsb** [comment]
感谢，确实可以使用

**Comment by kyo4311** [comment]
> treeNodeLabelProp 需要你提前处理数据，比如搞一个 `completeTitle` 属性，把父节点的信息递归加起来。

需求应该是，下面选择的树简单显示，上方input框，选中的值需要显示全，看了半天文档，还没有找到解决方法。

**Comment by cnzsb** [comment]
@kyo4311 没法解决。凑合用吧。

**Comment by wuyandefeixue** [comment]
@cnzsb 解决了么？同样有这样的需求 ^-^

**Comment by WanAn0902** [comment]
> treeNodeLabelProp 需要你提前处理数据，比如搞一个 `completeTitle` 属性，把父节点的信息递归加起来。

V3版本就只处理了回显，树结构内容就很简单，升级V4后树结构显示的太冗余了；
如果在树结构就要全部显示，只用title都可以满足了，可是现在想树结构简单点，回显的时候才显示treeNodeLabelProp的内容，
这个可以优化吗？

**Comment by redochenzhen** [comment]
如果回显的内容不是简单文本，而是react组件(比如<span>ok?<span>)，可以做到吗？

**Comment by qq1975843200** [comment]
将TreeSelect的labelInValue属性设置为true，然后v-mod绑定treeValue:{label:"自定义回显内容",value:"选中节点Value"}，然后可以通过在@change事件里面修改treeValue.label来实现自定义回显内容。

**Comment by UnicornXU** [comment]
https://codesandbox.io/s/ke-gou-xuan-antd-4-21-2-forked-jpxm9l?file=/demo.js
可以实现 V4的fieldNames结合 treeNodeLabelProp实现

**Comment by lmsccc** [comment]
找到一个兼容V3 V4的办法，可以使用treeNodeLabelProp渲染两个div，一个渲染回显内容，一个渲染树节点内容，然后通过CSS控制在回显时回显的内容，在树节点时显示的内容

**Comment by zhangzhuang15** [comment]
我找到了一个实现TreeSelect回填的方法，主要借鉴了 @qq1975843200 的思路，给出React的实现方式：
```typescript
import React  from 'react';

const treeData = [
  {
     title: "男性",
     value: '0',
     children: [
        { title: '1', value: '0-1', longTitle: '男性-1'  },
        { title: '2', value: '0-2', longTitle: '男性-2' }
     ],
  },
  {
    title: '女性',
    value: '1',
    children: [
        { title: '1', value: '1-1', longTitle: '女性-1' },
       { title: '2', value: '1-2', longTitle: '女性-2' },
    ]
  },
];
const App: React.FC = () => {

    const changeFunc = (value, labelNode, extra) {
             const v = extra.triggerNode.props.longTitle;
             value.label =  v
    };

   return (
     <TreeSelect 
          treeData={treeData}
          labelInValue={true}
          onChange={changeFunc}
    />);
};
```
这样你会看到下拉框展示为：

男性
     1
     2
女性
     1
     2

选中男性的1后，输入框展示为 ‘男性-1’.

**Comment by denshicheng** [comment]
> > 我找到了一个实现TreeSelect回填的方法，主要借鉴了 @qq1975843200 的思路，给出React的实现方式：
> > ```ts
> > import React  from 'react';
> > 
> > const treeData = [
> >   {
> >      title: "男性",
> >      value: '0',
> >      children: [
> >         { title: '1', value: '0-1', longTitle: '男性-1'  },
> >         { title: '2', value: '0-2', longTitle: '男性-2' }
> >      ],
> >   },
> >   {
> >     title: '女性',
> >     value: '1',
> >     children: [
> >         { title: '1', value: '1-1', longTitle: '女性-1' },
> >        { title: '2', value: '1-2', longTitle: '女性-2' },
> >     ]
> >   },
> > ];
> > const App: React.FC = () => {
> > 
> >     const changeFunc = (value, labelNode, extra) {
> >              const v = extra.triggerNode.props.longTitle;
> >              value.label =  v
> >     };
> > 
> >    return (
> >      <TreeSelect 
> >           treeData={treeData}
> >           labelInValue={true}
> >           onChange={changeFunc}
> >     />);
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样你会看到下拉框展示为：
> > 男性 1 2 女性 1 2
> > 选中男性的1后，输入框展示为 ‘男性-1’.
> 
> 这个方法有用

如果 多选状态下，点击tag 中的×会报错的，需要自定义下tagrender 方法

**Comment by zwmmm** [comment]
能否给一个 labelRender 字段，参考 Select 组件
