### ISSUE TITLE
Select component 'dropdownMatchSelectWidth' prop set to false triggers same behaviour as if set to true

### ISSUE THREAD

**Issue by ryanhliu** [ant-design/ant-design#22173]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-hooks-tme0g)

### Steps to reproduce
`<Select dropdownMatchSelectWidth={false}>...</Select>` and if select options are long, the dropdown width still matches with the select width.

### What is expected?
The dropdown from the Select should fit the select options and not be restricted to the width of the Select box.

### What is actually happening?
The dropdown from the Select width is equal to the Select box width

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | react |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
`dropdownMatchSelectWidth={false}` is not supported in v4: https://ant.design/docs/react/migration-v4

Please set to a percise number value.

**Comment by AleksandrHovhannisyan** [comment]
@afc163 Why is it no longer supported? It worked perfectly fine before.

Now we'll have to calculate the maximum option's length ourselves and translate that into a responsive pixel width.

**Comment by ausrussell** [comment]
I was frustrated by the documentation on this which still has dropdownMatchSelectWidth in the API, a feature which I would very much like. 
Does anyone know any workaround for having a dropdown with a different sized content from the button controlling it?
