### ISSUE TITLE
目前组件不经过编译直接浏览器运行的模式 是否支持到IE8了？

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2217]

**Comment by benjycui** [comment]
没有这个模式吧。

请提供更多的信息。

**Comment by aw6658913** [comment]
有啊 我以前有发过你还有评论呢[https://github.com/ant-design/ant-design/issues/1804#issuecomment-221174422](url)

**Comment by aw6658913** [comment]
以前有发过，你还有评论呢#1804

**Comment by benjycui** [comment]
组件是用 TypeScript 写的，不经过编译是不可能在浏览器运行的。

之前已经讨论过的问题，如果想继续讨论，建议直接在之前的 issue 回复，直接开个新的 issue，没有上下文，表示看不懂。
