### ISSUE TITLE
From.initialValues not destroyed with Modal.destroyOnClose

### ISSUE THREAD

**Issue by SpringsTea** [ant-design/ant-design#22171]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-bohr-1gdpz)

### Steps to reproduce
Following the documentation to create a form within a modal, populate the form defaults with `initialValues`. Then close the modal with `destroyOnClose` set to true and re open while passing different initial values.

### What is expected?
Initial values should be updated if the modal has been destroyed. Opening between collection1 and collection2 in my example should update the Title each time.

### What is actually happening?
The title of the form will not change from the first modal that is open.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13 |
| System | Window 10 |
| Browser | Chrome |

---
If I set the initial values of the form items them selves, this behavior does not happen. However, doing this seems to mess up validation.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21740#issuecomment-593105570

**Comment by Jarvie8176** [comment]
Came up with a solution myself to reload mutable initialValues:

[![Edit dank-sea-ni5ug](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dank-sea-ni5ug?fontsize=14&hidenavigation=1&theme=dark)

The idea is to add a `loaded` flag which allows modal (form wrapper) to call `form.resetFields()` before showing a modal form.

**Comment by shanben7** [comment]
> Came up with a solution myself to reload mutable initialValues:
> 
> [![Edit dank-sea-ni5ug](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/dank-sea-ni5ug?fontsize=14&hidenavigation=1&theme=dark)
> 
> The idea is to add a `loaded` flag which allows modal (form wrapper) to call `form.resetFields()` before showing a modal form.

Would you mind sharing your solution with the `loaded` flag? The one you linked is the standard Ant demo.

**Comment by Jarvie8176** [comment]
> > Came up with a solution myself to reload mutable initialValues:
> > [![Edit dank-sea-ni5ug](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/dank-sea-ni5ug?fontsize=14&hidenavigation=1&theme=dark)
> > The idea is to add a `loaded` flag which allows modal (form wrapper) to call `form.resetFields()` before showing a modal form.
> 
> Would you mind sharing your solution with the `loaded` flag? The one you linked is the standard Ant demo.

updated.

the flag `loaded` is to reduce unnecessary calls to `form.resetFields()` when there is no data update. If that is not a concern you could simply reset the form every time the modal becomes visible.

**Comment by N00nDay** [comment]
use the `afterClose` attribute and reset the Form. `afterClose={() => form.resetFields()}` works for my use case, may work for yours too.

**Comment by elvisiraguha** [comment]
You can also use `form.setFieldsValue` to force update

**Comment by killbond007** [comment]
> I solved this by using `form.setFieldsValue` in useEffect to force update
me too :) 
useEffect(() => {
		if (initialValues) {
			form.setFieldsValue(initialValues)
		}
	}, [initialValues])

**Comment by lfpose** [comment]
I can confirm this issue as well. Solved it with useEffect but this doesn't seem to be intended behavior. Hoping for a fix eventually? Or is this supposed to work like this?
