### ISSUE TITLE
How can I get the global classnames, moment, etc. when antd is loaded by CDN?

### ISSUE THREAD

**Issue by ilovedesert001** [ant-design/ant-design#22181]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
How can I get the global classnames, moment, etc. when antd is loaded by CDN?
i wanna get all depends from antd , don'timport repeatedly

### What does the proposed API look like?
antd.deps.moment
antd.deps.classnames
etc

**Comment by afc163** [comment]
You can't, we don't export other libs in antd dist file.
