### ISSUE TITLE
Table Filter 支持根据不同字段类型

### ISSUE THREAD

**Issue by Justin-lu** [ant-design/ant-design#2218]
目前的Table只支持枚举类型的 `Filter`， 在使用的过程中，可能会需要

1. 根据选定时间段（datetime）
2. 根据选定数字区间（integer）
3. 更具字符串匹配（string）
...

等等不同字段类型进行筛选。比较类似 extjs 的 filter grid

![cursor_and_ext_js_4_0_7_-_sencha_docs](https://cloud.githubusercontent.com/assets/1632249/16445652/3f592240-3e16-11e6-87b0-930dabf45759.jpg)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1736

**Comment by Justin-lu** [comment]
最终通过继承`Table`，并用 `context` 解决了。
