### ISSUE TITLE
[4.0.2] Table fixed column display not properly when fixed some column index.

### ISSUE THREAD

**Issue by AonTJ** [ant-design/ant-design#22184]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ymk6e?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Try to change fixed props of age or action column from right to left.
2. Warning message show: Index 2 of `columns` missing `fixed='right'` prop.
3. See the result of column display not properly. 

### What is expected?
Fixed column left or right should display properly on any column index.

### What is actually happening?
Fixed column left or right display not properly when fixed some column index that not on the far left or right index.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | MacOS |
| Browser | Chrome Version 80.0.3987.132 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Columns that fixed to left should be head of `columns` array, right fixed columns should be the end.

**Comment by ReyoungLee** [comment]
> Columns that fixed to left should be head of `columns` array, right fixed columns should be the end.
遇到同样的问题。我猜是这个原因，看到你这么说才确定。但是Table API的fixed属性没有提及这一点。
