### ISSUE TITLE
DatePicker mode 为year的时候 选择无效，

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#22189]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-shamir-brznq)

### Steps to reproduce
这个时候有人会说，可以用什么onPanelChange和onOpenChange 但是不不行，你是可以选择了。但是请点击上面的左右箭头，会发现关闭了时期panel。。参考：https://codesandbox.io/s/antd-reproduction-template-lntg7

### What is expected?
DatePicker mode 为year的时候  可以选择 年

### What is actually happening?
DatePicker mode 为year的时候  可以选择 不能选择年

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | latest |
| System | windows 10  |
| Browser | chrome  78.0.3904.108 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-xztmt
