### ISSUE TITLE
表格 columns filters 传入颜色无效，重置筛选条件，外部有暴露方法？

### ISSUE THREAD

**Issue by zheng1013757145** [ant-design/ant-design#22194]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-leaf-qgcb2)

### Steps to reproduce
https://codesandbox.io/s/unruffled-leaf-qgcb2

### What is expected?
解决用户自定义配色，外部重置表格已选中状态

### What is actually happening?
实际传入颜色无效，外部没找见可以清楚filters状态的方法

| Environment | Info |
|---|---|
| antd | 3.16.1 |
| React | latest |
| System | windows 10 |
| Browser | Google Chrome |

---
filters: [{ text: '预约成功', value: '2', color: 'red' }, { text: '预约失败', value: '3', color: 'yellow' }, { text: '预约中', value: '1' , color: 'blue'}],
外部重置表格项修改 this.resetTableReset() 可以清空filters已经选择的状态
![image](https://user-images.githubusercontent.com/23191825/76606526-59b2d200-654d-11ea-8f88-28c700a80d57.png)

**Comment by zheng1013757145** [comment]
增加下面两种
filters: [{ text: '预约成功', value: '2', color: 'red' }, { text: '预约失败', value: '3', color: 'yellow' }, { text: '预约中', value: '1' , color: 'blue'}],

外部重置表格项修改 this.resetTableReset() 可以清空filters已经选择的状态

**Comment by zheng1013757145** [comment]
增加下面两种
filters: [{ text: '预约成功', value: '2', color: 'red' }, { text: '预约失败', value: '3', color: 'yellow' }, { text: '预约中', value: '1' , color: 'blue'}],

外部重置表格项修改 this.resetTableReset() 可以清空filters已经选择的状态

**Comment by afc163** [comment]
`filteredValue`

https://ant.design/components/table-cn/#components-table-demo-reset-filter
