### ISSUE TITLE
Input.Search组件中如果添加allowClear属性 点击删除图标会触发 onSearch 事件

### ISSUE THREAD

**Issue by DawnL6** [ant-design/ant-design#22195]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-austin-u9fx9)

### Steps to reproduce
1、input中随意输入内容
2、点击删除图标

### What is expected?
不触发onSearch事件

### What is actually happening?
触发了onSearch事件

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | latest |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
It is a intented behavior, check #18729
