### ISSUE TITLE
你们这个怎么下载运行的 nodejs安装方法不行 不成功 有其他方式吗

### ISSUE THREAD

**Issue by a6965921** [ant-design/ant-design#222]
你们这个怎么下载运行的 nodejs安装方法不行 不成功 有其他方式吗      网上我找了好多框架 不管从用户体验性还是从交互上 都比不上你们  真心想用你们的做后台前端框架

**Comment by sorrycc** [comment]
怎么不成功?

**Comment by afc163** [comment]
怎么不成功?
