### ISSUE TITLE
docs page code box does not work

### ISSUE THREAD

**Issue by inovramadani** [ant-design/ant-design#22203]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://sorry-not-about-the-library-but-the-docs-page.com](https://sorry-not-about-the-library-but-the-docs-page.com)

### Steps to reproduce
Go to any docs page e.g. https://ant.design/components/button/, try to open code box
[image](https://files.gitter.im/ant-design/ant-design-english/hI8b/image.png)

### What is expected?
when clicked to code box should show the code for displayed components

### What is actually happening?
does not open, not responding on click

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.0.8 |
| System | windows 10 |
| Browser | chrome 80.0.3987.132 |

**Comment by afc163** [comment]
It works on my machine, please check your network situation.
