### ISSUE TITLE
antd4.*中如何使用动态Icon

### ISSUE THREAD

**Issue by chenwenqin** [ant-design/ant-design#22210]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
3.*版本中，可以通过type来动态设置动态的Icon，使用场景如，首页菜单权限控制。但是现在的版本，没有Icon组件，取而代之的是各个独立的Icon组件，无法动态设置Icon的类型了。

### What does the proposed API look like?
Icon独立出来，但是使用type形式可目前的使用独立的Icon兼容，即   <CloseOutlined />  ===  <Icon type='close'>

**Comment by afc163** [comment]
两种方式：

1. https://github.com/ant-design/compatible
2. 预先引入需要用的 Icons，用约定的 string 做 key。

```jsx
import { Xxx, Yyy } from '@ant-design/icons';

const Icons = {
  'Xxx': Xxx,
  'Yyy': Yyy,
};

const MyIcon = Icons[key]; // key 是传入的 string
```

**Comment by weiq** [comment]
@chenwenqin 现在可以这么写
```
const Icon = require('@ant-design/icons')[type];
return <Icon {...otherProps} />;
```

**Comment by wtzeng1** [comment]
如果在 `umijs` 生态下，可以使用这个插件实现有限的动态渲染：[umi-plugin-antd-type-icon](https://www.npmjs.com/package/umi-plugin-antd-type-icon)
