### ISSUE TITLE
Table header in modal is not displayed  after set rowSelection

### ISSUE THREAD

**Issue by davidcun** [ant-design/ant-design#22215]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-r13tf)

### Steps to reproduce
after Add rowSellection then the header displayed , in my project

### What is expected?
The Table Normally

### What is actually happening?
Table header in modal is not displayed，in my project

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | mac os |
| Browser | chrome  lastest |

---
same code ,the codesandbox is normal ,why?

**Comment by davidcun** [comment]
Maybe it's like  #22198  https://github.com/ant-design/ant-design/issues/22198

**Comment by zombieJ** [comment]
Your reproduce works well:
<img width="743" alt="截屏2020-03-16上午11 36 02" src="https://user-images.githubusercontent.com/5378891/76721241-53ee0400-677a-11ea-913a-75903c1f7e41.png">

**Comment by zombieJ** [comment]
Merge into #22256

**Comment by davidcun** [comment]
@zombieJ 
It’s  not work

![image](https://user-images.githubusercontent.com/5778930/76813693-b9ea9200-6833-11ea-9324-c66ff5ba701f.png)

when I upgrade antd to 4.0.3 , compile error ,

./node_modules/antd/es/cascader/style/css.js
Module not found: Can't resolve './rtl.css' in  '~/node_modules/antd/es/cascader/style'

![image](https://user-images.githubusercontent.com/5778930/76813902-557c0280-6834-11ea-88b2-161cb9ef88c3.png)

**Comment by zombieJ** [comment]
Reinstall node_modules, codesandbox has cache for packages.
