### ISSUE TITLE
可否在4.x的树形组件的TreeNode上加上dataRef属性（3.x中原本是有的）？

### ISSUE THREAD

**Issue by ppmmwozuiai** [ant-design/ant-design#22225]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在从3.x迁移到4.0的过程中，原本在TreeNode上使用dataRef属性用来实现TreeNode和data条目的映射，因为后台的data可能并不只是｛key,title，chidren｝的形式，可能有其他属性或者属性是其他名称,这时在构造TreeNode的时候使用dataRef属性用于node<=>data之间的映射关系。但是在4.0中dataRef属性不在接口属性列表里，所以会报错，如何解决这个问题？

3.x的demo:https://3x.ant.design/components/tree/#components-tree-demo-dynamic
其中可以看到是可以用dataRef的

### What does the proposed API look like?
恢复dataRef属性

**Comment by zombieJ** [comment]
v3 版本的 Demo 里通过 `dataRef` 属性来直接修改数据实现 Tree 的动态节点，但是这会导致数据变成 mutable。在 hooks 中，这会导致 setState 被跳过更新。也可以预见未来 concurrent 模式会出现的渲染问题。

因而在 v4 中移除了 `dataRef` 并且更新了 Demo 通过 immutable 方式来更新：https://ant.design/components/tree-cn/#components-tree-demo-dynamic

此外，如果你只想获取额外信息。现在的回调参数中 node 会把所有的信息都返回出来：https://codesandbox.io/s/happy-engelbart-9mxk3

**Comment by ppmmwozuiai** [comment]
但仍有一个问题，就是这样的话在迁移至4.x过程中会有大量代码改动，因为在项目中已经在几十处基于renderTreeNode和dataRef的树形界面逻辑，这样的话只能一处处地进行修改。

**Comment by zombieJ** [comment]
建议自己包一个 HOC 来做兼容，这个是特意舍弃的，如果加回来就没有意义了。
