### ISSUE TITLE
建议增加表格筛选滚动条，太长了

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#22228]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design](https://ant.design)

### What is expected?
可以api设置超过n条有滚动条

### What is actually happening?
超长无滚动条
![QQ浏览器截图20200315173640](https://user-images.githubusercontent.com/3166799/76699034-2a829900-66e4-11ea-884b-f8927f48e14d.png)

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13.0 |
| System | Windows |
| Browser | chrome 80 |

**Comment by xrkffgg** [comment]
可以先在自己项目中自定义 这个
```
.ant-table-filter-dropdown .ant-dropdown-menu {
    max-height: calc(100vh - 130px);
}
```

**Comment by afc163** [comment]
similar to #19542
