### ISSUE TITLE
react组件添加JsMind的js和css依赖，请问怎么添加？

### ISSUE THREAD

**Issue by harrykate** [ant-design/ant-design#2222]
如何在react组件中添加外部的js和css依赖以达到个性化展示的目的？

### mac 本地环境如下
tnpm@4.5.0 (/usr/local/lib/node_modules/tnpm/bin/tnpm)
npm@3.10.2 (/usr/local/lib/node_modules/tnpm/node_modules/npm/lib/npm.js)
node@5.12.0 (/usr/local/Cellar/node5/5.12.0/bin/node)
npminstall@1.12.0 (/usr/local/lib/node_modules/tnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local (load prefix from: $ npm config get prefix)
darwin x64 15.0.0

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

### 你做了什么？
在自己写的组件里想引入jsmind的jss和css文件，从而让这个组件在index页面中按照jsmind的风格进行渲染展示。

### 你期待的结果是：
类似于下图的展示效果，这个是在html中引入jsmind的js和css，然后在html文件的script中按下列语法写好，直接打开html文件即可展示了，但是在react组件里不知道怎么写。

以下是html直接引入的方式的代码：
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>jsMind</title>
    <link type="text/css" rel="stylesheet" href="../style/jsmind.css" />
    <style type="text/css">
        #jsmind_container{
            width:800px;
            height:500px;
            border:solid 1px #ccc;
            /*background:#f4f4f4;*/
            background:#f4f4f4;
        }
    </style>
</head>
<body>
<div id="jsmind_container"></div>
<script type="text/javascript" src="../js/jsmind.js"></script>
<script type="text/javascript" src="../js/jsmind.draggable.js"></script>
<script type="text/javascript">
    function load_jsmind(){
        var mind = {
            "meta": {
                "name": "UI Travel Tree",
                "author": "Yufeng",
                "version": "V0.1"
            },
            "format": "node_tree",
            "data": {
                "id": "root",
                "topic": "理财小工具",
                "children": [{
                    "id": "1-0",
                    "topic": "unNamed Element",
                    "clicked": "true",
                    "children": [{
                        "id": "1-0-0",
                        "topic": "unNamed Element",
                        "clicked": "true",
                        "expanded": false,
                        "children": [{
                            "id": "1-0-0-0",
                            "topic": "人民币",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-1",
                            "topic": "美元",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-2",
                            "topic": "港币",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-3",
                            "topic": "欧元",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-4",
                            "topic": "韩元",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-5",
                            "topic": "日元",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-6",
                            "topic": "英镑",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-7",
                            "topic": "新加坡元",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-8",
                            "topic": "泰铢",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-9",
                            "topic": "俄罗斯卢布",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-10",
                            "topic": "澳大利亚元",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-11",
                            "topic": "加拿大元",
                            "clicked": "true"
                        }, {
                            "id": "1-0-0-12",
                            "topic": "挪威克朗",
                            "clicked": "true"
                        }]
                    }, {
                        "id": "1-0-1",
                        "topic": "请输入金额",
                        "clicked": "true"
                    }, {
                        "id": "1-0-2",
                        "topic": "unNamed Element",
                        "clicked": "true"
                    }, {
                        "id": "1-0-3",
                        "topic": "0",
                        "clicked": "true"
                    }]
                }, {
                    "id": "1-1",
                    "topic": "unNamed Element",
                    "clicked": "true",
                    "children": [{
                        "id": "1-1-0",
                        "topic": "利率表",
                        "clicked": "true"
                    }, {
                        "id": "1-1-1",
                        "topic": "活期",
                        "clicked": "true",
                        "children": [{
                            "id": "1-1-1-0",
                            "topic": "利率表",
                            "clicked": "true"
                        }, {
                            "id": "1-1-1-1",
                            "topic": "活期",
                            "clicked": "true"
                        }, {
                            "id": "1-1-1-2",
                            "topic": "定期",
                            "clicked": "false"
                        }, {
                            "id": "1-1-1-3",
                            "topic": "输入存款金额",
                            "clicked": "true"
                        }, {
                            "id": "1-1-1-4",
                            "topic": "存款期限",
                            "clicked": "true",
                            "children": [{
                                "id": "1-1-1-4-0",
                                "topic": "3个月定期",
                                "clicked": "true"
                            }, {
                                "id": "1-1-1-4-1",
                                "topic": "6个月定期",
                                "clicked": "true"
                            }, {
                                "id": "1-1-1-4-2",
                                "topic": "1年定期",
                                "clicked": "true"
                            }, {
                                "id": "1-1-1-4-3",
                                "topic": "2年定期",
                                "clicked": "false"
                            }, {
                                "id": "1-1-1-4-4",
                                "topic": "3年定期",
                                "clicked": "false"
                            }, {
                                "id": "1-1-1-4-5",
                                "topic": "5年定期",
                                "clicked": "false"
                            }]
                        }, {
                            "id": "1-1-1-5",
                            "topic": "年利率(%)",
                            "clicked": "true"
                        }]
                    }, {
                        "id": "1-1-2",
                        "topic": "定期",
                        "clicked": "true"
                    }, {
                        "id": "1-1-3",
                        "topic": "输入存款金额",
                        "clicked": "true"
                    }, {
                        "id": "1-1-4",
                        "topic": "存款期限(天)",
                        "clicked": "true"
                    }, {
                        "id": "1-1-5",
                        "topic": "输入存款天数",
                        "clicked": "true"
                    }, {
                        "id": "1-1-6",
                        "topic": "年利率(%)",
                        "clicked": "true",
                        "children": [{
                            "id": "1-1-6-0",
                            "topic": "0.35%央行基准利率",
                            "clicked": "true"
                        }, {
                            "id": "1-1-6-1",
                            "topic": "2.44%余额宝7日年化收益率",
                            "clicked": "true"
                        }]
                    }]
                }, {
                    "id": "1-2",
                    "topic": "房贷计算",
                    "clicked": "true",
                    "children": [{
                        "id": "1-2-0",
                        "topic": "利率表",
                        "clicked": "true"
                    }, {
                        "id": "1-2-1",
                        "topic": "等额本息",
                        "clicked": "true"
                    }, {
                        "id": "1-2-2",
                        "topic": "等额本金",
                        "clicked": "true"
                    }, {
                        "id": "1-2-3",
                        "topic": "等额本息还款详情",
                        "clicked": "true"
                    }, {
                        "id": "1-2-4",
                        "topic": "贷款类型",
                        "clicked": "true",
                        "children": [{
                            "id": "1-2-4-0",
                            "topic": "商业贷款",
                            "clicked": "true"
                        }, {
                            "id": "1-2-4-1",
                            "topic": "公积金贷款",
                            "clicked": "true"
                        }, {
                            "id": "1-2-4-2",
                            "topic": "组合贷款",
                            "clicked": "false"
                        }]
                    }, {
                        "id": "1-2-5",
                        "topic": "请输入金额",
                        "clicked": "true"
                    }, {
                        "id": "1-2-6",
                        "topic": "期限(年)",
                        "clicked": "true"
                    }, {
                        "id": "1-2-7",
                        "topic": "利率(%)",
                        "clicked": "true"
                    }]
                }]
            }
        };
        var options = {
            container:'jsmind_container',
            editable:true,
            theme:'primary'
        }
        var jm = jsMind.show(options,mind);
    }

    load_jsmind();
</script>
</body>
</html>

## 实际上的结果：

不知道怎么引入jss和css文件，让自己的组件个性化展示

### 可重现的在线演示

还没有引入成功    不知道怎么配置，现在我的antd工程目录如下：
![Uploading 屏幕快照 2016-06-30 10.22.10.png…]()

折腾好久了，麻烦答疑解惑一下，谢谢

**Comment by benjycui** [comment]
非 antd 的问题，建议去 JsMind 的 issue 提问。

**Comment by harrykate** [comment]
请问下JsMind的issue链接是什么？
