### ISSUE TITLE
Warning: `children` of Tree is deprecated. Please use `treeData` instead

### ISSUE THREAD

**Issue by jin-benben** [ant-design/ant-design#22220]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/k8nrd)

### Steps to reproduce
打开链接，看控制台

### What is expected?
没有waring

### What is actually happening?
Warning: `children` of Tree is deprecated. Please use `treeData` instead

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | latest |
| System | win10 |
| Browser | chrome版本 80.0.3987.132 |

**Comment by yoyo837** [comment]
这个警告的目的是让使用treeData的方式代替children，后续会删除children的用法

**Comment by lucasleelz** [comment]
@afc163 @yoyo837 自定义TreeNode怎么办~ 也没有提供一个自定义渲染的属性出来。以后Tree的灵活度就降低了。

**Comment by my101du** [comment]
> @afc163 @yoyo837 自定义TreeNode怎么办~ 也没有提供一个自定义渲染的属性出来。以后Tree的灵活度就降低了。

是的，我现在写了一个可编辑的 treeNode,  用 title = {<EditableItem />} 实现的，总是会报这个错误。
如果以后废弃 children 的话，怎么在 treeNode 上使用自定义组件恩？

**Comment by codingbycat** [comment]
> @afc163 @yoyo837 自定义TreeNode怎么办~ 也没有提供一个自定义渲染的属性出来。以后Tree的灵活度就降低了。

同意

**Comment by wjm117** [comment]
是的，不能使用children，太不灵活了

**Comment by NNNaix** [comment]
I think we need the TreeNode or a render function or some other way to use custom tree node, for example editable tree node.

**Comment by msotnikov** [comment]
> 是的，我现在写了一个可编辑的 treeNode, 用 title = {} 实现的，总是会报这个错误。
> 如果以后废弃 children 的话，怎么在 treeNode 上使用自定义组件恩？

I use this way. 
```
    const gg = users.map(el => ({
      ...el,
      title: <UsersTreeNode item={el}/>,
      key: el.id
    }))

    return arrayToTree(gg, { id: 'key', parentId: 'parent_id', childrenField: 'children', dataField: null })
```

But it is very slow with 1k components, because rendering perform before parent node render.
We definitely need the render prop.

**Comment by postgetme** [comment]
need custom render function

**Comment by postgetme** [comment]
need custom node render function too

**Comment by Ionito** [comment]
so, what is the solution to this?

**Comment by huya666** [comment]
我也遇到相同的问题，这个问题需要怎和以解决呢？

**Comment by yanlee26** [comment]
这个问题怎么被关闭的呢？？？

**Comment by msotnikov** [comment]
Use the antd@4.5.0. There new titleRender function.

>  🆕 Tree support titleRender to customize all nodes' content. #25624

**Comment by JoeVanGundy** [comment]
@msotnikov From what I can tell, this only change the internal contents of the row.
We need to be able to customize the entire row. Is this possible?

**Comment by 1119879311** [comment]
tree  的生成dom结构 都是同级的div 的了，没有以前ul,li 这种嵌套显示了，这警告怎么去掉啊

**Comment by Toge66** [comment]
如果如果后台返回的树节点数据结构是这样的{id: "xxxxx", name:"name"}，但是treeData的结构是{key:"xxxxx",title:"name"}，这样的话我就需要遍历后台返回的数据浪费性能，没有对应的api去映射吗？

**Comment by leiyangs** [comment]
so, what is the solution to this?

**Comment by aaronmichaelacosta** [comment]
It would be great to support custom children again, since it would provide much more flexibility than only allowing for 'treeData' to specify tree node configs.

For instance, if a a node's title AND its children need to be fetched asynchronously, this may be difficult to use the current interface with some libraries that don't support it. For example, Apollo Client is one such library that relies on declarative queries and hooks to load asynchronous data instead of manual promises, which antd's component docs seem to suggest is the only solution: https://ant.design/components/tree/#components-tree-demo-dynamic.

It would be great to re-enable custom children to support the following use case, for example:

```
import * as React from "react";
import { Tree } from " ";
import { useQuery } from "@apollo/react-hooks";
import { gql } from "graphql-tag";

const GET_ENTITY = gql`
  query getEntity($id: ID!) {
    entity(id: $id) {
      id
      children {
        id
        name
      }
    }
  }
`;

function MyCustomTreeNode({ id: string, name: string }) {
  const { data, loading } = useQuery(GET_ENTITY, {
    variables: { id }
  });
  if (loading || !data) {
    return null;
  }

  return (
    <Tree.TreeNode
      key={id}
      title={name}
    >
      {(loading || !data) ? null : data?.entity?.children?.map(child => (
        // this would be great, if only it worked
        <MyCustomTreeNode id={child.id} name={child.name} />
      ))}
    </Tree.TreeNode>
  );
}
```

**Comment by Ragzzy-R** [comment]
curious if there is an alternative solution for this? There is a real need for using children. We have a tree with node having multiple action buttons and each node is highly customizable. TreeNode provides means to provide custom components as children. Removing it is reducing flexibility. Is there a real reason this was removed?

**Comment by katdivyareddy10** [comment]
There's a prop called `titleRender` that you can use to render customized tree nodes.
```
const renderTreeNode = (nodeData) => {
    console.log(nodeData); // This should have all data regarding the node.

    return (
      <div>
        {nodeData.title}
        <Button text="Custom Action Button" onClick={} />
      </div>
    );
  };
  ```
  and use it like
```
<Tree 
  treeData={customTreeData}
  titleRender={renderTreeNode}
/>
```
I hope this helps!

**Comment by sunjiesama** [comment]
> 如果后台返回的树例程数据结构是这样的{id：“ xxxxx”，name：“ name”}，但是treeData的结构是{key：“ xxxxx”，title：“ name”}，这样的话我就需要遍历后台返回的数据浪费性能，没有对应的api去映射吗？

你好，请你这个问题你后来解决了吗

**Comment by YHS2017** [comment]
> There's a prop called `titleRender` that you can use to render customized tree nodes.
> 
> ```
> const renderTreeNode = (nodeData) => {
>     console.log(nodeData); // This should have all data regarding the node.
> 
>     return (
>       <div>
>         {nodeData.title}
>         <Button text="Custom Action Button" onClick={} />
>       </div>
>     );
>   };
> ```
> 
> and use it like
> 
> ```
> <Tree 
>   treeData={customTreeData}
>   titleRender={renderTreeNode}
> />
> ```
> 
> I hope this helps!

However, NodeData will lose part of the customer data, and there is no way to get the customer data of the current node during rendering customized tree nodes。

**Comment by v1talii-dev** [comment]
I can customize title via `titleRender` property but how customize `key` property?

**Comment by Bulala-liu** [comment]
谁能告诉我，可以忽略这个warning吗？？我需要自定义tree node啊。

**Comment by APIS-X** [comment]
@Bulala-liu 不要使用TreeNode, 通过Tree的treeData属性注入Tree的数据，使用TreeNode无非是用想用自定义节点，但是自定义节点的属性全部可以通过treeData满足，ant的Tree 是对组件rc-tree的二次封装，如果ant的API不明了的，可具体查看rc-tree的API
