### ISSUE TITLE
Tabs 组件 使用可控模式下，循环遍历出来TabPane  每次点击title TabPane都会重复渲染多次，次数随累计点击的tab增加累加

### ISSUE THREAD

**Issue by Gzbox** [ant-design/ant-design#22237]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-allen-gs9g8)

### Steps to reproduce
在受控模式下直接点击切换Tab   在遍历出的 TabPane中 console.log('渲染')  就能看到该tab下面的子TabPane会渲染多次次数随累计点击的tab增加累加

### What is expected?
点击某一个Tab 该tab下面的子TabPane只渲染一次 

### What is actually happening?
在受控模式下直接点击切换Tab   在遍历出的 TabPane中 console.log('渲染')  就能看到该tab下面的子TabPane会渲染多次，次数随累计点击的tab增加累加

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13 |
| System | macOS  10.13.4 |
| Browser | Chrome  版本 80.0.3987.132（正式版本） （64 位） |

**Comment by Gzbox** [comment]
是我哪里用错了吗？我再每个遍历出来的TabPane中加载不同的表格 在tabPane中获取数据，现在这种情况将导致渲染多次 还会触发多次请求

**Comment by zombieJ** [comment]
受控模式下，setState 让当前组件 re-render 导致子组件也 re-render （包括所有的 TabPane）。这是预期行为。

你不应该在 render 中调用 ajax 请求。应该改成根据 onChange 事件来调用对应的 ajax 请求。

**Comment by Gzbox** [comment]
即便是我不在 render 中调用 ajax 请求。改成根据 onChange 事件来调用对应的 ajax 请求。将获取对应的值props传给 子组件 ，这种方式 我通过在子组件中打印 仍然发现它  render了多次   render次数随累计点击的tab增加累加 @zombieJ    这符合预期吗？

**Comment by Gzbox** [comment]
即便是我不在 render 中调用 ajax 请求。改成根据 onChange 事件来调用对应的 ajax 请求。将获取对应的值props传给 子组件 ，这种方式 我通过在子组件中打印 仍然发现它 render了多次 render次数随累计点击的tab增加累加 @zombieJ 这符合预期吗？

**Comment by Gzbox** [comment]
我不能理解的是   render次数随累计点击的tab增加累加

**Comment by Gzbox** [comment]
@zombieJ [https://codesandbox.io/s/atlaskittabs-10-controlled-rt4g5](url)  这个组件符合我说的那种预期
演示codesandbox [https://codesandbox.io/s/atlaskittabs-10-controlled-rt4g5](url)

**Comment by Gzbox** [comment]
@chenshuai2144

**Comment by zombieJ** [comment]
`@atlaskit/tabs` 只渲染当前 active 的 TabPane，它没有动画切换的过程。所以每次只有一个 dom 在页面上。

antd 的策略是，只渲染当前的。当用户切换过后，不删除之前渲染过的节点。所以点击切换会逐渐增多。为的是防止用户在 mount 阶段调用异步请求导致切换时反复渲染。所以 render 数量随着上层刷新而整体刷新并增加是预期行为。

**Comment by Gzbox** [comment]
好的  我知道了  
非常感谢
