### ISSUE TITLE
form表单验证数字类型有问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2223]
我验证给输入框加上以下验证
const stdPriceV = getFieldProps('stdPrice', {
        rules: [
          { required: false, type: 'number', message: '请输入数字' },
        ],
      });

结果不论输入什么都提示’请输入数字‘

**Comment by afc163** [comment]
duplicated #2201

**Comment by aw6658913** [comment]
额，那个也是我提问的，因为一直没有人回复所以我开了一个新的issues @afc163

**Comment by afc163** [comment]
没人回复一般要么是问题不好回复，要么是资源不够，无法响应。重复开 issue 也解决不了。
