### ISSUE TITLE
Functional component Select onChange produces Warning: Cannot update a component from inside the function body of a different component.

### ISSUE THREAD

**Issue by erdemkeren** [ant-design/ant-design#22233]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/antd-3cannot-update-a-component-from-inside-the-function-body](https://stackblitz.com/edit/antd-3cannot-update-a-component-from-inside-the-function-body)

### Steps to reproduce
- Open browser console to see output.
- Create a new search-enabled Select component instance within a functional component
- Implement the `onSearch` handler and trigger setState hook call inside the function.
- See browser console warning.

### What is expected?
No console warning

### What is actually happening?
Warning: Cannot update a component from inside the function body of a different component.

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.13.0 |
| System | macOS Catalina 10.15.3 |
| Browser | Google Chrome Version 80.0.3987.132 (Official Build) (64-bit) |

---
I saw a similar bug report for v4 which was closed. But couldn't find one for v3 Select.

**Comment by dlcognite** [comment]
+1
commenting to follow this :)

**Comment by alexrdguez91** [comment]
+1

**Comment by afc163** [comment]
This issue had been resolved in antd v4: https://stackblitz.com/edit/antd-3cannot-update-a-component-from-inside-the-function-gece6k?file=package.json
