### ISSUE TITLE
select的文本出现省略号，没人发现吗？

### ISSUE THREAD

**Issue by sunyum** [ant-design/ant-design#22235]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/magical-sara-3g76r)

### Steps to reproduce
官网随便找个select的例子打开就可以看到

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13 |
| System | win10 |
| Browser | chrome最新版 |

**Comment by shaodahong** [comment]
![image](https://user-images.githubusercontent.com/14831261/76702768-6d099d00-6707-11ea-9f17-5df3aa5f6933.png)

截个图看下？

**Comment by sunyum** [comment]
> ![image](https://user-images.githubusercontent.com/14831261/76702768-6d099d00-6707-11ea-9f17-5df3aa5f6933.png)
> 
> 截个图看下？

![image](https://user-images.githubusercontent.com/20025971/76702893-63346980-6708-11ea-9402-1c4bdcef3a4d.png)

![image](https://user-images.githubusercontent.com/20025971/76702862-3da76000-6708-11ea-9cd4-324cfb1de575.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/22196#issuecomment-598631941
