### ISSUE TITLE
TreeSelect value 需要支持number类型

### ISSUE THREAD

**Issue by iwangx** [ant-design/ant-design#22241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为不是所有的id都是string，如果限制死为string对于业务的拓展性不是很好

### What does the proposed API look like?
```
<TreeSelect value={0} />
```

**Comment by zombieJ** [comment]
<img width="470" alt="截屏2020-03-16上午10 31 38" src="https://user-images.githubusercontent.com/5378891/76718314-5304a480-6771-11ea-8dd5-d0a4b06ba0d2.png">
