### ISSUE TITLE
@ant-design/compatible中的index.css样式缺失

### ISSUE THREAD

**Issue by soulcm** [ant-design/ant-design#22246]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sweet-pine-1zk4f)

### Steps to reproduce
打开devtool，选到对应元素，可以发现ant-row、ant-col的样式都未引入

### What is expected?
@ant-design/compatible/assets/index.css 包含所会用到的完整样式

### What is actually happening?
未包含需要的样式，如ant-row的样式就没有

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | macOS |
| Browser | chrome最新版本 |

---
本身组件通过babel-plugin-import按需引入，样式也自动引入，但兼容性的form使用推荐方式引入后，发现样式缺失，想改为直接引入到es下面的form时，只有less文件，无css文件，且less中代码为 @import 'antd/xxx/yyy'这种，无'~'符号，导致webpack的less-loader也无法找到

**Comment by shaodahong** [comment]
建议自己单独引入

1. compatible 引入后 `compatible/assets/index.css` 会多大约 3400 行的 Grid 的样式
2.  `~antd/xxx/yyy` 这种是 `less-loader` 的模块加载，compatible 使用的是 less 直接编译

**Comment by zombieJ** [comment]
@shaodahong 是不是应该和 antd 主包一样做一个额外的引入？https://github.com/ant-design/ant-design/blob/master/components/form/style/index.tsx

compatible： https://github.com/ant-design/compatible/tree/master/src/form/style

**Comment by shaodahong** [comment]
感觉不好，额外的引入也要区分 `less` 或者 `css`，让用户理解太麻烦了，还需要配置 `babel-plugin-import`，直接在 compatible 中搞个 FAQ 说明一下比较好

**Comment by zombieJ** [comment]
用户用 codemod 升级后，应该不会参考文档。这个如果要自行引入还需要有 console 提示最好。

**Comment by SOCHINGYEE** [comment]
之前项目做过antd的v3升级到v4的版本，我clone项目就会这个报错。后来去npm去搜antdesign-compatible发现以下内容：
Helps you to compatible different components between v4 and v5.
-- import { Button, Select, Dropdown } from 'antd';
++ import { Button, Select, Dropdown } from '@ant-design/compatible';

然后我就去ant-design/compatible的github去查看历史的版本，最后安装了以下版本解决了问题
yarn add @ant-design/compatible@v4-compatible-v3
