### ISSUE TITLE
Horizontal/Vertical nested submenu show scrollbars when clicked

### ISSUE THREAD

**Issue by weiguozhu** [ant-design/ant-design#22244]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sgmnt)

### Steps to reproduce
Click "Navigation Two" - "Submenu" - "Option 7" or "Option 8"
(This is an official example@Antd Doc)

### What is expected?
No scrollbar

### What is actually happening?
Show scrollbar

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 80.0.3987.132 |

---
Executed as expected in Ver 4.0.1

**Comment by afc163** [comment]
ref https://github.com/ant-design/ant-design/issues/21928

**Comment by oyalhi** [comment]
This is still present on Chrome Version 80.0.3987.149, Windows 10, antd 4.1.0
