### ISSUE TITLE
upload图片上传是否有做压缩功能？单单对上传大小做限制不大合理

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2224]

**Comment by afc163** [comment]
UI 不涉及这些业务功能，只是单纯的上传。

**Comment by aw6658913** [comment]
通过测试在没有与后台对接就是纯UI上测试生成缩略图多大都没有问题，到了有跟后端交互的环境上一旦上传过大缩略图会一直显示上传中，最终导致超时，另外action是否可以不需要必填呢？我发现不管有没设置action，只要上传必定执行action，浏览器network会发现请求报一个error.html错误，应该是执行了action报的错，因为我还要对上传图片信息进行筛选所以不通过action去提交给后台，action并没有设置
