### ISSUE TITLE
Antd Table rowSelection is not working in Antd 4.0.3

### ISSUE THREAD

**Issue by sb-lee** [ant-design/ant-design#22256]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-buck-wl12v)

### Steps to reproduce
I only added  rowSelection={{}} props in antd table    on  antd example( https://codesandbox.io/s/ozr5v )

### What is expected?
`rowSelectIon` column is normally shown  in table header  

### What is actually happening?
When horizontal scroll is shown, Table table header is not shown.
When horizontal scroll is not shown, Table table header is broken.

but  It is normally working in Antd 4.0.2

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13 |
| System | window 10  (1909) |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
试了一下，本地已经好了。应该是和 #22232 一个问题。
