### ISSUE TITLE
当getFieldProps和checkbox结合使用时，initialValue无法生效

### ISSUE THREAD

**Issue by taikongfeizhu** [ant-design/ant-design#2225]
### 本地环境

- antd 版本: 1.3.2
- 操作系统及其版本：mac
- 浏览器及其版本: chrome50

### 你做了什么？

引入 antd 了 Form, Input, Checkbox

### 你期待的结果是：

通过getFieldProps可以给checkbox正常做initialValue赋值

## 实际上的结果：

```js
<Checkbox
      {...getFieldProps('firstSocialSecurity', {
                initialValue: true
    })}>第一次在北京缴纳社保
</Checkbox>
```
当getFieldProps和checkbox结合使用时，initialValue无法生效；

**Comment by benjycui** [comment]
http://ant.design/components/form#getFieldProps options

![image](https://cloud.githubusercontent.com/assets/3580607/16482412/345fc7fa-3ee2-11e6-82fe-35918710b186.png)

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by Rosa0418** [comment]
@benjycui  How can i set the initialValue for checkbox ??

**Comment by Rosa0418** [comment]
<Checkbox
      {...getFieldProps('firstSocialSecurity', {
                valuePropName: 'checked',
                initialValue: true
    })}>第一次在北京缴纳社保
</Checkbox>
