### ISSUE TITLE
npm run build 后，放到其他环境中应该如何配置路由

### ISSUE THREAD

**Issue by yukiyuki1900** [ant-design/ant-design#2226]
npm run build 后，将dist目录放到服务器中，并配置路由指向dist/index.html，打开页面依然是显示404

之前问过部署后直接打开dist/index.html显示404，@benjycui  同学回答说本地路径没有匹配的路由，自然就 404 了，部署之后就正常了。

请问是因为我路由没有配置好吗？还是其他原因？

**Comment by yukiyuki1900** [comment]
这是package.json的配置项
{
  "private": true,
  "dependencies": {
    "antd": "^1.1.0",
    "babel-plugin-antd": "0.4.x",
    "babel-plugin-transform-runtime": "^6.8.0",
    "babel-runtime": "^6.6.1",
    "classnames": "^2.2.3",
    "js-cookie": "^2.1.1",
    "moment": "^2.13.0",
    "react": "^15.0.2",
    "react-dom": "^15.0.2",
    "react-router": "^2.0.1",
    "superagent": "^1.8.3",
    "superagent-jsonp": "^0.0.7"
  },
  "devDependencies": {
    "dora": "0.3.x",
    "dora-plugin-browser-history": "^0.1.1",
    "dora-plugin-hmr": "0.6.x",
    "dora-plugin-livereload": "0.3.x",
    "dora-plugin-proxy": "0.6.x",
    "dora-plugin-webpack": "0.6.x",
    "expect": "^1.20.1",
    "glob": "^7.0.3",
    "pre-commit": "1.x"
  },
  "entry": {
      "index": "./entries/index.html"
  },
  "pre-commit": [
    "lint"
  ],
  "scripts": {
    "build": "atool-build",
    "lint": "eslint --ext .js,.jsx src",
    "start": "killall -9 node ; ./node_modules/.bin/dora -p 8087 --plugins 'webpack,proxy,browser-history?index=/src/entries/index.html'",
    "test": "atool-test-mocha ./src/**/__tests__/*-test.js"
  }
}

**Comment by yukiyuki1900** [comment]
直接用服务器打开index.js的url，浏览器上显示报语法错误了。可是本地8989端口访问正常，编译命令是按照文档里的npm run build~

![aa](https://cloud.githubusercontent.com/assets/8652560/16481125/2ba05c0c-3edc-11e6-8bda-e072b6bb35d5.png)

**Comment by benjycui** [comment]
1. 之前已经提过的问题，可以 reopen issue 继续讨论，不然没上下文不好理解。
2. 这个问题不是 package.json 的配置问题。

确认你访问的路径，在 react-router 中配置了。

这样的问题，真心不好回复。。。

**Comment by yukiyuki1900** [comment]
好的~~

我在src/routes/index.js里配置了路由，具体代码如下：

![aa](https://cloud.githubusercontent.com/assets/8652560/16482990/f5b21820-3ee4-11e6-97c9-97245c50e637.png)

因为本地端口8989的路径访问时没问题的，所以一直做了很多尝试都没法解决。

我的做法是这样的，将dist目录放到服务器上，再修改php的路由，将路由指向dist/index.html~~

**Comment by benjycui** [comment]
话说，你用的是 `browserHistory`？

如果是，那么服务器也需要相应的配置，详见 react-router 的文档。

**Comment by yukiyuki1900** [comment]
查了一下react-router的关于browserHistory的文档：https://github.com/reactjs/react-router/blob/master/docs/guides/Histories.md#browserhistory

![aa](https://cloud.githubusercontent.com/assets/8652560/16515621/a16d6096-3fa5-11e6-90d8-3d7275eda878.png)

我是这样配的：

![aa](https://cloud.githubusercontent.com/assets/8652560/16515702/20ddbc18-3fa6-11e6-8846-c6aecef684ce.jpg)

这样有什么不对吗~？

**Comment by yuzhouisme** [comment]
提供一个apache2的解决方案，启用重定向，希望能解决大部分人的问题
<VirtualHost *:80>
    ServerAdmin yuzhouisme
    ServerName dev.yuzhouisme.com
    ServerAlias dev.yuzhouisme.com
    DocumentRoot /var/www/dev
    <Directory /var/www/dev/>
  	RewriteEngine On  
  	RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
  	RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
  	RewriteRule ^ - [L]

  	RewriteRule ^ /index.html [L]
    </Directory>
</VirtualHost>

**Comment by yukiyuki1900** [comment]
感觉不是服务器配置的问题而是部署的问题，因为之前有一次部署过一次放到服务器上访问正常，再到现在又访问404了，就再也没有访问正常过了~~一直找不出原因，十分诡异~~

但访问正常的部署后代码目前还保留，但是看不懂呀~~

**Comment by yukiyuki1900** [comment]
感觉应该不是服务器部署的问题，因为我发现之前项目有一次部署后的代码放服务器上展示正常了，但是现在代码部署出来放到服务器上都会404，也一直定位不出来到底是哪里的问题，找不出来当时展示正常的时候的源码~

目前状态是，我这边只保留了一份曾经部署后可访问正常的dist目录，可惜现在部署后得代码就从未成功过了。

**Comment by yukiyuki1900** [comment]
环境版本：
npm@2.14.7
node  v4.2.1
atool-build  0.7.13

**Comment by wuhaih** [comment]
你可以build之后在本地试下，看看访问的路由是否正确，最好是配置异步加载路由，可以很清楚看到访问的路由路径

**Comment by yukiyuki1900** [comment]
找到问题了，因为服务器上配的是/gring，所以react路由配置也得改成/gring/保持一致才可以。

**Comment by yukiyuki1900** [comment]
找到问题了，因为服务器上配的是/gring，所以react路由配置也得改成/gring/保持一致才可以。非常感谢各位的耐心解答~~

**Comment by Aijunwei** [comment]
请问要把dist文件夹当做静态资源，直接部署到tomcat服务器该怎么做

**Comment by sym900728** [comment]
在 tomcat 上面简单的做法，在 web.xml 中加入
...
<error-page>
    <error-code>404</error-code>
    <location>/index.html</location>
</error-page>
...
