### ISSUE TITLE
 Doesn't work blur to TreeSelect on Ipad

### ISSUE THREAD

**Issue by lexlexa** [ant-design/ant-design#22267]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select/#components-tree-select-demo-basic](https://ant.design/components/tree-select/#components-tree-select-demo-basic)

### Steps to reproduce
1. Click on TreeSelect
2. Click on an empty place

### What is expected?
TreeSelect blur

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.8.6 |
| System | any IpadOS |
| Browser | any |

**Comment by zacksinclair** [comment]
I also have this issue. It appears to happen for Select and TreeSelect fields on any IOS device, iphones included. If you programmatically call blur, nothing happens.

**Comment by zombieJ** [comment]
Close since not receive feedback any more.
