### ISSUE TITLE
Hiding search text on click Select, TreeSelect

### ISSUE THREAD

**Issue by lexlexa** [ant-design/ant-design#22266]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select/#components-select-demo-multiple](https://ant.design/components/select/#components-select-demo-multiple)

### Steps to reproduce
1. Click select
2. Type any text
3. Click text

### What is expected?
The cursor moves to the click position

### What is actually happening?
Search text is hiding

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.8.6 |
| System | any |
| Browser | any |

**Comment by UsamaMahboob** [comment]
I can do this!

**Comment by zombieJ** [comment]
Close since not an issue in latest version.
