### ISSUE TITLE
 Column is broken due to the width of the div wrapped the table

### ISSUE THREAD

**Issue by sb-lee** [ant-design/ant-design#22262]
- [X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-moon-7qzg2)

### Steps to reproduce
1. use fixed left columns and horizontal Scroll in antd Table.
2. Adjust the length of the div surrounding the table to be greater or less than the table's original length.
3. If the length of the div is less than the original length of the table, check that the fixed left column is drawn normally.

### What is expected?
table is drawn normally

### What is actually happening?
fixed columns are broken

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13 |
| System | window 10  (1909) |
| Browser | chrome latest |

**Comment by sb-lee** [comment]
This is error case capture in  my example
![image](https://user-images.githubusercontent.com/14502051/76747169-0f835800-67bc-11ea-8a69-65b494806e41.png)

**Comment by zombieJ** [comment]
Could you help to reinstall and test again? this should be fixed with latest rc-table.

**Comment by sb-lee** [comment]
And  

When All Columns has `ellipsis : true`  ,  It works like this:
![image](https://user-images.githubusercontent.com/14502051/76749622-2035cd00-67c0-11ea-8c81-7edafeb8196e.png)

**Comment by sb-lee** [comment]
And  when Table has 'rowSelection:{{}}` and  all Columns have `ellipsis : true`  ,  It works like this:   each row are broken

![image](https://user-images.githubusercontent.com/14502051/76750021-dd282980-67c0-11ea-8a67-2d507d30247d.png)


![image](https://user-images.githubusercontent.com/14502051/76749622-2035cd00-67c0-11ea-8c81-7edafeb8196e.png)
