### ISSUE TITLE
`ant-prefix`变量无法应用在message组件中

### ISSUE THREAD

**Issue by henryzp** [ant-design/ant-design#22269]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://ant.design](http://ant.design)

### Steps to reproduce
直接上源码：https://github.com/ant-design/ant-design/blob/master/components/message/index.tsx

第十三行：let prefixCls = 'ant-message';正确的应该像其他组件那样：拿到`getPrefixCls`去做字符串拼接

### What is expected?
现在无法生效，我传了`ant-v4`，期望得到`ant-v4-message`。

### What is actually happening?
实际得到`ant-message`

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.8.6 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
Try ` message.config({ prefixCls: "ex-ant-message" });`

**Comment by henryzp** [comment]
@afc163 ，这样是ok的，但是`message`本身什么时候能改造成和其他组件那样的？

另外，是不是还会有其他组件有类似的问题，得要通过调用`config`方法来处理呢？[捂脸]

**Comment by afc163** [comment]
message 目前的实现方式写法比较难改造成其他组件使用 `getPrefixCls` 的方式。
