### ISSUE TITLE
设置了scroll.y高度后导致横向滚动条拉到最后列和内容无法对齐

### ISSUE THREAD

**Issue by PeteLuo** [ant-design/ant-design#2227]
### 本地环境

- antd 版本:1.6.2
- 操作系统及其版本：win7旗舰64位
- 浏览器及其版本: 目前使用的是chrome 49.0.2623.110，其余浏览器如Safari等也存在该问题

### 你做了什么？
使用一个Table组件

### 你期待的结果是：
在设置了scroll.y的情况下表格正常显示

## 实际上的结果：
直接看v1.6.2官方文档Table组件最后一个“适合同时展示有大量数据和数据列”的demo。
##### 一开始未拖动横向滚动条效果：
![default](https://cloud.githubusercontent.com/assets/18900661/16477944/cc27a284-3ec8-11e6-8b9a-44332860d1da.jpg)
##### 滚动条拖动到最后的效果：
![default](https://cloud.githubusercontent.com/assets/18900661/16478019/755ae5aa-3ec9-11e6-9b87-d3368c195602.jpg)

### 可重现的在线演示
http://ant.design/components/table/ 适合同时展示有大量数据和数据列 Demo

**Comment by ranzhu123** [comment]
估计是scroll的x没有设置好 ，你的每列都设置宽度了吗？

**Comment by PeteLuo** [comment]
@ranzhu123 为了让例子更明显，我给表格加上了边框。
demo位置[http://codepen.io/PeteLuo/pen/XKgVaW](url)
可以看到所有列都设置的宽度，但是滚动条拉到最右边依然是未对齐的，相差一个滚动条的宽度
###### 图示：
![table](https://cloud.githubusercontent.com/assets/18900661/16572071/05856eb8-4297-11e6-9bd8-f8c05af54808.jpg)

**Comment by ranzhu123** [comment]
建议先通过修改右侧的paddingright 来解决吧？
