### ISSUE TITLE
Icon styles in Dropdown Menu Items are not applied if inside an anchor tag

### ISSUE THREAD

**Issue by palaumarc** [ant-design/ant-design#22274]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-dropdown-menu-icon-styles-bug-9dqv7)

### Steps to reproduce
Open the CodeSandbox link, you should see a Dropdown component with two options. The children of the first Menu.Item is wrapped into a link (anchor tag) while the other one is directly the text.

### What is expected?
All the icons children of a Menu.Item should have the same styles even if they are wrapped into an anchor tag

### What is actually happening?
Icons have different styles. It seems like the styles generally applied to icons inside a Menu.Item component do not apply to the icon of the one wrapped into a link.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13 |
| System | MacOS Mojave 10.14.6  |
| Browser | Chrome v80 |

**Comment by lich-yoo** [comment]
@afc163  @zombieJ  诶，这个问题最新版是不是又被改出来了？升完 antd 样式有差异了

![image](https://user-images.githubusercontent.com/18572962/123609481-460aa800-d832-11eb-82b4-2e4f29ef1d54.png)

![image](https://user-images.githubusercontent.com/18572962/123609622-689cc100-d832-11eb-9a92-31bdcd740ad8.png)
