### ISSUE TITLE
 Display cursor in field without search. Select

### ISSUE THREAD

**Issue by lexlexa** [ant-design/ant-design#22272]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select/#components-select-demo-basic](https://ant.design/components/select/#components-select-demo-basic)

### Steps to reproduce
1. Click on select

### What is expected?
Input cursor not visible

### What is actually happening?
Input cursor visible

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.8.6 |
| System | Ios, ipados |
| Browser | any |

**Comment by zombieJ** [comment]
Use `showSearch` to enable search function.

**Comment by lexlexa** [comment]
But no search needed

**Comment by lexlexa** [comment]
@zombieJ  up

**Comment by afc163** [comment]
Any screenshot in iOS?

**Comment by lexlexa** [comment]
@afc163 

IPhone 8/ IOS 11/Safari
![image](https://user-images.githubusercontent.com/35931860/76826241-02eb1800-682d-11ea-8321-64814dddad3a.png)

**Comment by afc163** [comment]
Fixed in #24631
