### ISSUE TITLE
TreeSelect search level limit. TreeSelect搜索时限制搜索层数。

### ISSUE THREAD

**Issue by ladyrick** [ant-design/ant-design#22276]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在TreeSelect中搜索时，它会自动展开所有的层次。

在动态加载数据时，搜索后，用户不得不先把左边的箭头收起，再展开，以触发数据获取。

代码示例：[https://codesandbox.io/s/antd-reproduction-template-g5zhm](https://codesandbox.io/s/antd-reproduction-template-g5zhm)

在以上示例中，搜索react时，会自动展开react和react-dom左边的箭头（虽然并没有子结点）。我不得不先把它收起来，再展开，以触发获取数据。

希望可以增加一个搜索层次限制，比如只搜索第一层的结点，这样就只在第一层中搜索，同时不需要展开所有的二级结点。

### What does the proposed API look like?
```
<TreeSelect showSearch searchLevel={1} >
    <TreeSelect.TreeNode />
</TreeSelect>
```

**Comment by zombieJ** [comment]
用 `treeExpandedKeys` 来将展开做成受控的进行管理。
