### ISSUE TITLE
Add a prop to the Table to prevent onHover functionality to the rows

### ISSUE THREAD

**Issue by nora-white** [ant-design/ant-design#22279]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently using 3.26.8.

In my application, I have many tables which significantly vary in size. Results could be as large as 350 million, and the number of columns could be as great as ~700. Each time a user hovers over a row in the Table, the className `ant-table-row-hover` is applied, forcing a re-render, and then running the column `render` function for each cell (so for ~700 cells in the worst case). Each cell needs to go through a check to determine how it should be rendered:
- If date, format as date.
- If numeric, format to a given precision.
- If link, extract data and format as link.
- If paragraph, slice the text and add a tooltip on hover to show the remaining text.
- etc.

Hovering on a table that has only a few columns is not that bad, but on a table that has ~700 columns on it, this is a significant performance decrease with a noticeable delay when mousing over a row.

It would be great to have a prop to turn off the hover className, and then on our end we could potentially apply some :hover CSS to the row, rather than applying a className.

### What does the proposed API look like?
```
<Table
   applyHoverClassName={false}
/>
```

**Comment by zombieJ** [comment]
v3 is in maintaining and will not apply new feature.
