### ISSUE TITLE
webpack编译DatePicker，页面报require is not defined

### ISSUE THREAD

**Issue by littleRice** [ant-design/ant-design#22283]
使用webpack3.8.1编译时，引用DatePicker，发现页面会报错，require is not defined

**Comment by rostislav-simonik** [comment]
@littleRice have you resolved your issue ? i'm facing the same.

**Comment by littleRice** [comment]
> @littleRice have you resolved your issue ? i'm facing the same.
you can try to  update it.   4.0.3

**Comment by littleRice** [comment]
try to update it. 4.0.3




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上6:35
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"紫沁雨星"<792819829@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] webpack编译DatePicker，页面报require is not defined (#22283)





 
@littleRice have you resolved your issue ? i'm facing the same.
