### ISSUE TITLE
Form component Upload UI render error

### ISSUE THREAD

**Issue by EthanOrange** [ant-design/ant-design#22281]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-kfqm5)

### Steps to reproduce
依次上传就行

### What is expected?
正确展示上传状态

### What is actually happening?
上传完成，UI显示上传中

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.8.6 |
| System | macOs Mojave |
| Browser | Chrome 版本 80.0.3987.132（正式版本） （64 位） |

**Comment by EthanOrange** [comment]
![image](https://user-images.githubusercontent.com/7098719/76813834-25346400-6834-11ea-843c-e37ed3204c2b.png)
附上gif 比较直观
可能需要梯子才能看到

**Comment by coderyyx** [comment]
也遇到这个问题

**Comment by zombieJ** [comment]
List 不是 immutable 的，先 slice 顶一下：https://codesandbox.io/s/antd-reproduction-template-7o42p
