### ISSUE TITLE
Input allowClear bug

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design#22286]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/xiexingen/pen/NWqMJPx](https://codepen.io/xiexingen/pen/NWqMJPx)

### Steps to reproduce
1.将Input的allowClear 设置为true
2.输入内容
3.鼠标离开输入框

### What is expected?
输入框上的清空按钮不应该一直显示

### What is actually happening?
输入框上的清空图标按钮一直在

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | ^16.13.0 |
| System | windows 10 |
| Browser |  80.0.3987.132（正式版本） （64 位） |

---
之前是鼠标hover到输入框而且输入框有内容才会显示 清空的图标
现在只要有内容 那个清空图标会一直显示

**Comment by afc163** [comment]
3.x 版本之前也是这样：https://3x.ant.design/components/input/#components-input-demo-allowClear

**Comment by vision-ken** [comment]
清空图标一直显示实在太丑了。整个表单一眼看过去都是密密麻麻的清空图标。建议改为获得焦点后才显示清空图标。

**Comment by caihai123** [comment]
其他的组件都是鼠标移入之后才显示，就input是一直显示的
