### ISSUE TITLE
Table filterDropdown 问题。。。

### ISSUE THREAD

**Issue by flicker85** [ant-design/ant-design#2228]
filterDropdown：可以自定义筛选菜单，此函数只负责渲染图层，需要自行编写各种交互

这个有没有具体的demo代码？找了一圈儿没找到。。。。

比如我要在筛选菜单里添加全选、清空之类的按钮，该怎么扩展？

还有一个问题，当我点击筛选图标，弹出筛选菜单，这是我不点任何筛选条件和按钮， 直接点页面空白处，筛选菜单会关闭，但是仍然会触发Table onChange函数。
http://ant.design/components/table#components-table-demo-ajax

**Comment by Justin-lu** [comment]
这是我的demo代码

```js
{
  title: "xxxx",
  dataIndex: "x",
  key: "x",
  filterDropdown: <DateTimeFilterDropdown
                              handleTableChange={this.props.handleTableChange}
                           />
}

```

**Comment by afc163** [comment]
> 还有一个问题，当我点击筛选图标，弹出筛选菜单，这是我不点任何筛选条件和按钮， 直接点页面空白处，筛选菜单会关闭，但是仍然会触发Table onChange函数。

现在没改变时不再触发 onChange 。

**Comment by badplum** [comment]
@Justin-lu  你好，请教下，这里我应该怎么写filter？能不能贴一下具体实现？谢谢

**Comment by Justin-lu** [comment]
https://github.com/Justin-lu/react-redux-antd/blob/master/src/components/CustomTable.js
https://github.com/Justin-lu/react-redux-antd/blob/master/src/components/DateTimeFilterDropdown.js

可以参考一下这里的demo

**Comment by badplum** [comment]
@Justin-lu 谢谢，我看一下。

**Comment by elearic** [comment]
@afc163 前辈您好,我也遇到类似问题，我使用filterDropDown自定义组件，如果在menu的item中添加了button按钮，想通过button去控制自定义filter列表的显示该如何操作呢，谢谢

**Comment by DJ0312** [comment]
这个自定义的组件的显示位置怎么调节，默认是把自定义的弹出框的left 对齐，能不能调到中间
