### ISSUE TITLE
bug: Rate RTL allowHalf 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#22296]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/rate-cn/#components-rate-demo-half](https://ant.design/components/rate-cn/#components-rate-demo-half)

### Steps to reproduce
- Open links
- Select RTL mode
- Mouse select half star
### What is expected?
- Mouse over the right part to indicate half star

### What is actually happening?
- Mouse over the left part to indicate a half star

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | The latest |
| System | mac |
| Browser | chrome |

---
In LTR mode, mouse over the left part to indicate a half star

**Comment by saeedrahimi** [comment]
https://github.com/react-component/rate/pull/54 ,  on Dec 3, 2019
