### ISSUE TITLE
FormItem 的 name 字段不在支持数组？

### ISSUE THREAD

**Issue by Sean-Snow** [ant-design/ant-design#22297]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd4-form-name-buzhichishuzu-1mxzy)

### Steps to reproduce
1. FormItem 设置 name 为 ['users','0','name']
2. 提交表单

### What is expected?
期望提交得到的表单值中users 为数组

### What is actually happening?
实际结果是对象

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | MacOS 10.15.3 |
| Browser | Google Chrome 80.0.3987.132 |

**Comment by Sean-Snow** [comment]
@afc163 大哥救命，影响的地方太多了

**Comment by MinJieLiu** [comment]
@Sean-Snow 你可以先试试 Form.List ?

**Comment by Sean-Snow** [comment]
@MinJieLiu  改动太多了

**Comment by zombieJ** [comment]
```diff
- ["users", "0", "name"]
+ ["users", 0, "name"]
```

**Comment by zombieJ** [comment]
```diff
- ["users", "0", "name"]
+ ["users", 0, "name"]
```

**Comment by kurarpikt** [comment]
> ```diff
> - ["users", "0", "name"]
> + ["users", 0, "name"]
> ```

找了整整一夜，直到看到这句才解决，老哥是怎么发现的？NB啊

**Comment by huseyingoztok** [comment]
@zombieJ  how to set value users.3.name with setFieldsValue. I can not find it. Your document give example for only users.1.name (Version 4.1.5)

**Comment by huseyingoztok** [comment]
@zombieJ  how to set value users.3.name with setFieldsValue. I can not find it. Your document give example for only users.0.name (Version 4.1.5) How can I dynamically change the value of the index I want?

**Comment by yoyo837** [comment]
@huseyingoztok https://codesandbox.io/s/antd-reproduction-template-erxq7?file=/index.js

**Comment by yoyo837** [comment]
@zombieJ 除了这样写还有更好的方法不？我也在学习。

**Comment by zombieJ** [comment]
@yoyo837 , `setFields` 可以单独按照路径设置。

**Comment by huseyingoztok** [comment]
@yoyo837 thank you very much for your reply. @zombieJ can you sample what you mean?

**Comment by yoyo837** [comment]
@huseyingoztok The example given to you at first did not use `setFields` until he provided me some help.

**Comment by huseyingoztok** [comment]
@yoyo837  I'm sorry. I saw your example as if you did with setFieldsValue. You used setFields, but that worked for me. It would be great if there is an example for setFieldsValue. Thank you very much.

**Comment by yoyo837** [comment]
@huseyingoztok In the example, I used setFieldsValue at first, but later changed to setFields. Wait a minute, I will provide you another example.

**Comment by huseyingoztok** [comment]
@yoyo837  thank you so much.

**Comment by yoyo837** [comment]
@huseyingoztok 
 https://codesandbox.io/s/antd-reproduction-template-iccz5 It is significantly more complicated.

**Comment by huseyingoztok** [comment]
@yoyo837  Thank you so much for taking the time to answer.

**Comment by huseyingoztok** [comment]
@yoyo837 How can we set errors to form elements like this with setFields? I tried a method similar to the method (https://codesandbox.io/s/antd-reproduction-template-erxq7?file=/index.js) set value, but it didn't.

**Comment by yoyo837** [comment]
@huseyingoztok Is this what you need? https://codesandbox.io/s/antd-reproduction-template-o305l?file=/index.js

https://github.com/react-component/field-form#fielddata

**Comment by huseyingoztok** [comment]
thank you so much. Yes it is @yoyo837 .

**Comment by huseyingoztok** [comment]
@yoyo837  You know why get TypeError: date.clone is not a function error when setting value to DatePicker? Sorry if it is wrong to ask the question from here.

**Comment by yoyo837** [comment]
@huseyingoztok Wrapper it with `moment` just like `moment(Date.now())`

**Comment by huseyingoztok** [comment]
@yoyo837  how to set globally localization for DatePicker format. I want to set tr o en locales by cookie value. I try set moment.locale in my index.js, but format does not changed.

**Comment by yoyo837** [comment]
@huseyingoztok You need https://ant.design/components/config-provider/


```jsx
import zhCN from 'antd/lib/locale/zh_CN';

ReactDom.render(
  <ConfigProvider locale={zhCN}>
    <App />
  </ConfigProvider>;
  ,
  // eslint-disable-next-line unicorn/prefer-query-selector
  document.getElementById('root')
);
```

**Comment by huseyingoztok** [comment]
Actually, how do I change the format globally in the datepickers I want to ask. I tried the method you said but my problem was not solved. Thank you.

**Comment by yoyo837** [comment]
@huseyingoztok That is the answer, if there are other questions, please provide a reproduction.

**Comment by dkfiresky** [comment]
@yoyo837 @huseyingoztok 

Here is a reproduction: https://codesandbox.io/s/locale-ant-design-demo-wbuzl

The date field placeholder is translated, but the actual value does not get formatted accordingly.

**Comment by yoyo837** [comment]
> @yoyo837 @huseyingoztok
> 
> Here is a reproduction: https://codesandbox.io/s/locale-ant-design-demo-wbuzl
> 
> The date field placeholder is translated, but the actual value does not get formatted accordingly.

ref: #22810 @zombieJ

**Comment by huseyingoztok** [comment]
@yoyo837  How can I prevent the decimal value from entering the number input?

**Comment by huseyingoztok** [comment]
Is there an example of using Form.List in Form.List? I made a few attempts but failed.

**Comment by huseyingoztok** [comment]
@zombieJ  @yoyo837  please help.

**Comment by yoyo837** [comment]
FYI：https://github.com/ant-design/ant-design/issues/22611#issuecomment-604192080

I don't know more information for the time being, I'm still learning v4.
