### ISSUE TITLE
Form表单中多列栅格式的表单排列方式，增加了校验规则，在27英寸屏幕下，会有高度问题

### ISSUE THREAD

**Issue by wooxyz** [ant-design/ant-design#22291]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-yuj0l?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
- 27英寸屏幕

### What is expected?
14英寸屏幕下，高度都是64，没有问题，如下图。不管是14英寸，还是27英寸，高度应该一样吧
![14英寸](https://user-images.githubusercontent.com/33221294/76814524-f1f2d480-6835-11ea-94e2-9e97e9470b72.png)

### What is actually happening?
在27英寸的屏幕下运行效果，校验不通过的feild4和feild5高度略有差异，如下图：
![27英寸](https://user-images.githubusercontent.com/33221294/76821819-093bbd00-684a-11ea-9c50-8bfd62358751.png)
尝试固定高度可以解决该问题，但觉的不好

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.8.6 |
| System | win10 |
| Browser | Chrome80.0.3987.132 |

---
奇怪的是：在codesandbox中始终无法重现出来，但真的会有这样的情况

**Comment by shaodahong** [comment]
看下浏览器是不是缩放了

**Comment by wooxyz** [comment]
@shaodahong 是的，非常之感谢，厉害，厉害！
