### ISSUE TITLE
table组件1个表格内怎么实现两个小计

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#22292]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在一个table里只能有一个小计，如果分组的话有好几个小计，最后一个总计，该如何做

### What does the proposed API look like?
表格分组，能有几个小计，最后一行一个总计

**Comment by yoyo837** [comment]
把小记做成数据行

**Comment by afc163** [comment]
Duplicate of #15630
