### ISSUE TITLE
Form.List 中 remove 方法可否支持数组以批量删除

### ISSUE THREAD

**Issue by MinJieLiu** [ant-design/ant-design#22298]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前 `Form.List` 参数 `remove` 不支持 批量删除，在全选了一组数据后，`fields.forEach` 调用 `remove`，被删除的数据会错乱，总会留下一半。

FormList.d.ts
```ts
interface FieldData {
  name: number;
  key: number;
  fieldKey: number;
}

interface Operation {
  add: () => void;
  remove: (index: number) => void;
  move: (from: number, to: number) => void;
}
```

原因可能是 `name` 值是连续的数值，删除一个后，后面的 `name` 都变了。在调用下一个`remove` 的时候，`name` 就出现错位的情况。

### What does the proposed API look like?

```ts
remove: (index: number| number[]) => void;
```

**Comment by zombieJ** [comment]
批量操作直接通过 setFieldsValue 改掉列表即可

**Comment by MinJieLiu** [comment]
一般用到 Form.List，那就代表着这样的结构比较深，setFieldsValue 参数貌似不支持 namePath。改深层的数据特别绕，FieldData.name 也不好映射到具体的 field 中。

**Comment by MinJieLiu** [comment]
主要是 Form.Item 上缺少 initialValues 这样的参数， normalize 参数也不支持加载的时候就转换。

**Comment by MinJieLiu** [comment]
暂时用很副作用的方式
为了能用 setFieldsValue

```jsx
<Form.Item noStyle shouldUpdate>
  {form => {
    const customField = form.getFieldValue('customField');
    customField[field.name] = {
      name: field.name,
      ...customField[field.name],
    };
    return <Input type="hidden" />;
  }}
</Form.Item>
```

**Comment by zombieJ** [comment]
能举个例子吗？我看看是什么结构

**Comment by MinJieLiu** [comment]
结构类似于这样，但初始状态 `exampleList` 为 `[]`

```jsx
const initialValues = {
  exampleList: [
    {
      name: 0,
      title: 'hello',
      description: 'world',
    },
    {
      name: 1,
      title: 'hello1',
      description: 'world1',
    },
  ],
};
```

使用了 `Form.List`

```jsx
<Form.List name="exampleList">
  {(fields, operation) => (
    <CustomComponent
      form={form}
      fields={fields}
      operation={operation}
    />
  )}
</Form.List>

```

后面按照 https://ant.design/components/form-cn/#components-form-demo-dynamic-form-item 做的，但是多了几个字段，增加了批量删除的功能

```jsx
{fields.map(field => {
  return (
    <>
      <Form.Item noStyle shouldUpdate>
        {() => {
          // 需要将 name 合并到 field 中
          const fieldArr = form.getFieldValue('exampleList');
          fieldArr[field.name] = {
            name: field.name,
            ...fieldArr[field.name],
          };
          return <Input type="hidden" />;
        }}
      </Form.Item>
      <Checkbox checked={isSelected(field.name)} onChange={() => toggle(field.name)} />
      <Form.Item name={[field.name, 'title']}>
        <Input  />
      </Form.Item>
      <Form.Item name={[field.name, 'description']}>
        <Input  />
      </Form.Item>
    </>
  );
})}
```

批量删除

```jsx
function handleBatchDelete() {
  const values = form.getFieldValue('exampleList');
  form.setFieldsValue({
    exampleList: values.filter(item => selected.every(n => item.name !== n)),
  });
}
```

**Comment by hanxinimm** [comment]
Form.List 能支持 initialValues 这样的参数最好
我也有这样的需求
![image](https://user-images.githubusercontent.com/13499426/79684663-d7ad7b80-8265-11ea-8484-24f0213eb4b2.png)
用户根据规格动态生成规格项目列表
![image](https://user-images.githubusercontent.com/13499426/79684704-04fa2980-8266-11ea-8505-0fa267d816bb.png)
目前组件包含嵌套，导致初始化值处理起来太复杂。

**Comment by alextrastero** [comment]
Sorry I don't read Chinese and google translator doesn't seem to work.

I'm also trying to render a `Form.List` in typescript, and when using `fieldKey` I get the error:
`Type ReactText[] is not assignable to type 'number'`

I expect it's because of:
```
interface FieldData {
  name: number;
  key: number;
  fieldKey: number;
}
```

**Comment by hanxinimm** [comment]
@alextrastero 

  /**
               * `fields` internal fill with `name`, `key`, `fieldKey` props.
               * You can extends this into sub field to support multiple dynamic fields.
               */

demo link

https://codesandbox.io/s/wonderful-lichterman-br63z

**Comment by alextrastero** [comment]
Thanks @hanxinimm, also just noticed this:
![image](https://user-images.githubusercontent.com/4152819/80598584-e21c0200-8a29-11ea-877e-403b5fdd7776.png)

**Comment by Ruto8** [comment]
@alextrastero I stumbled upon the same issue just minutes ago. 
For now overwriting the types with 
```ts
  const { Item }: any = Form
```
until this issue hopefully gets resolved

**Comment by yoyo837** [comment]
> @alextrastero
> 
> /**
> * `fields` internal fill with `name`, `key`, `fieldKey` props.
> * You can extends this into sub field to support multiple dynamic fields.
> */
> 
> demo link
> 
> https://codesandbox.io/s/wonderful-lichterman-br63z

ref: #22810 @zombieJ

**Comment by ZhuoYaZhao** [comment]
一个Form中有多个Form.List，可以支持给Form.List中的字段设置初始值吗？

**Comment by fireairforce** [comment]
I will work on this~

**Comment by fireairforce** [comment]
solve at: https://github.com/ant-design/ant-design/pull/25638
