### ISSUE TITLE
表格同时有树形结构和可展开，可以使用两个不同的按钮分别控制吗

### ISSUE THREAD

**Issue by liuxuhong109** [ant-design/ant-design#22295]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
同时兼容树形结构和可展开，分开控制

### What does the proposed API look like?
同时兼容树形结构和可展开，分开控制

**Comment by afc163** [comment]
建议不要用这样的交互，会混淆。

**Comment by mayu888** [comment]
> 建议不要用这样的交互，会混淆。

如果业务就要这么做，可以实现吗？
