### ISSUE TITLE
table组件可编辑能否一个单元格内是上下两个单元格的计算之和

### ISSUE THREAD

**Issue by wangxingxing123654** [ant-design/ant-design#22293]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table组件可编辑中。一个单元格内是上下两个单元格的计算之和

### What does the proposed API look like?
table组件可编辑中。一个单元格内是上下两个单元格的计算之和

**Comment by yoyo837** [comment]
https://ant.design/components/table-cn/#components-table-demo-summary

这个能做你想要的

**Comment by yoyo837** [comment]
3.x 也能变相做到

![image](https://user-images.githubusercontent.com/6134547/76827505-eb765400-6859-11ea-8a6a-eef1a0962087.png)

**Comment by wangxingxing123654** [comment]
> https://ant.design/components/table-cn/#components-table-demo-summary
> 
> 这个能做你想要的

不是这种。
是table内有两个输入框。两个输入框可以编辑，两个输入框之和等于table内第三行数据

**Comment by yoyo837** [comment]
> > https://ant.design/components/table-cn/#components-table-demo-summary
> > 这个能做你想要的
> 
> 不是这种。
> 是table内有两个输入框。两个输入框可以编辑，两个输入框之和等于table内第三行数据

那你完全可以编程处理，和表格没有关系。
