### ISSUE TITLE
Form input 使用了getFieldProps后怎样再监听onchange

### ISSUE THREAD

**Issue by ranchoX** [ant-design/ant-design#2230]
问题如下
代码：` <input type="text" style={{height:28}} {...getFieldProps('appid')}
                                   class="ant-input ant-input-lg"/>` 我想监听它onchange 事件。
但是这样会影响`  const {getFieldsValue} =form;
        var data = getFieldsValue()` 
所以我想请教下这样的功能需求，应该怎样处理
比如说我自己的onchange事件中可以调用form的 类似 setValue 方法。或者Form有提供像事件监听一个冒泡的机制

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/1286

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by ranchoX** [comment]
http://ant.design/components/form/#getFieldProps options

**Comment by WHX777** [comment]
请问一下你是怎么解决的呢，我也遇到了这个问题呢

**Comment by zhongjie-chen** [comment]
Ant Design Form的解读 了解一下 http://tech.dianwoda.com/2018/03/22/ant-form/
