### ISSUE TITLE
antd 4.0.3 input的样式bug

### ISSUE THREAD

**Issue by mankeheaven** [ant-design/ant-design#22300]
![image](https://user-images.githubusercontent.com/17426397/76835554-457f1580-686a-11ea-93f1-eb3577c3255c.png)

.ant-input-affix-wrapper {
  position: relative;
  display: inline-block;
  width: 100%;
  min-width: 0;
  padding: 4px 11px;
  color: rgba(0, 0, 0, 0.65);
  font-size: 14px;
  line-height: 1.5715;
  background-color: #fff;
  background-image: none;
  border: 1px solid #d9d9d9;
  border-radius: 2px;
  -webkit-transition: all 0.3s;
  transition: all 0.3s;
  display: -webkit-inline-box;
  display: -ms-inline-flexbox;
  display: inline-flex;
}

这个display : inline-flex 和inline-block同时存在

**Comment by mankeheaven** [comment]
拜拜

**Comment by xrkffgg** [comment]
这个 `index.css` 是你软件自动生成的。

非 https://new-issue.ant.design/?repo=ant-design 创建的 issues，系统会自动关闭

**Comment by afc163** [comment]
来个 PR 删掉前面那个。

**Comment by mankeheaven** [comment]
我没这么无聊软件生成这个，这是npm install 之后node_modules里面的。

**Comment by mankeheaven** [comment]
我不确定直接删除这个display:inline-block是否会影响其他的。因为目前来看这次4版本的input的布局和class都是重写了（我升级后项目中input变形对比先前的代码发现的）。这个不知道是否有测试用例

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/eea959b2e92a0685410466527921f874e47c7e31/components/input/style/affix.less#L9

看了一下确实不太好改，这里是对原来的 `display:inline-block` 进行了覆盖，代码确实会重复写。

**Comment by mankeheaven** [comment]
了解了
