### ISSUE TITLE
我一直觉得这个导航菜单组件展开效果很别扭

### ISSUE THREAD

**Issue by jthinking** [ant-design/ant-design#22314]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
视觉效果更好，体验更舒服

### What does the proposed API look like?
无

**Comment by afc163** [comment]
你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？

**Comment by jthinking** [comment]
> 你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？

对比一下ElementUI的相同组件https://element.eleme.cn/#/zh-CN/component/menu，不觉得咱这个动画有些卡顿的感觉吗

**Comment by admiao** [comment]
> > 你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？
> 
> 对比一下ElementUI的相同组件https://element.eleme.cn/#/zh-CN/component/menu，不觉得咱这个动画有些卡顿的感觉吗

vue 本身就更流畅

**Comment by afc163** [comment]
> 对比一下ElementUI的相同组件https://element.eleme.cn/#/zh-CN/component/menu，不觉得咱这个动画有些卡顿的感觉吗

目前我没有找到有效的执行方式，有任何性能和动画方面的改进方式，欢迎给我们 PR，这里不再跟踪。

**Comment by jthinking** [comment]
MATERIAL-UI官网（[https://material-ui.com/zh/](https://material-ui.com/zh/)）的左侧菜单栏效果就挺好的

**Comment by afc163** [comment]
他们的缓动函数不错，我们可以参考一下。

**Comment by jthinking** [comment]
> 他们的缓动函数不错，我们可以参考一下。

期待。Ant Design万岁！

**Comment by XSmarter** [comment]
展开二级菜单在macos下挺流畅的，但是同事windows下展开菜单，好像挺卡顿的不知道为什么？ @afc163

**Comment by admiao** [comment]
> 你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？

即使去掉动画 antd-react 和 antd-vue 都摆在那 肉眼都能辨别的 你没眼睛吗

**Comment by yoyo837** [comment]
> > 你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？
> 
> 即使去掉动画 antd-react 和 antd-vue 都摆在那 肉眼都能辨别的 你没眼睛吗

你没有手不知道自己实现吗？

**Comment by admiao** [comment]
> > > 你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？
> > 
> > 
> > 即使去掉动画 antd-react 和 antd-vue 都摆在那 肉眼都能辨别的 你没眼睛吗
> 
> 你没有手不知道自己实现吗？

我只是说Vue和react 某一领域的性能比较 ，给出不佳回应的是你们 成员某人 ，自己翻楼 ，  我也并不否认ant 贡献 ，你们否认我的说法你们没手实现？

**Comment by yoyo837** [comment]
> > > > 你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？
> > > 
> > > 
> > > 即使去掉动画 antd-react 和 antd-vue 都摆在那 肉眼都能辨别的 你没眼睛吗
> > 
> > 
> > 你没有手不知道自己实现吗？
> 
> 我只是说Vue和react 某一领域的性能比较 ，给出不佳回应的是你们 成员某人 ，自己翻楼 ， 我也并不否认ant 贡献 ，你们否认我的说法你们没手实现？

我翻楼也没看见谁否认你说的别人更流畅！

**Comment by admiao** [comment]
> > > > > 你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？
> > > > 
> > > > 
> > > > 即使去掉动画 antd-react 和 antd-vue 都摆在那 肉眼都能辨别的 你没眼睛吗
> > > 
> > > 
> > > 你没有手不知道自己实现吗？
> > 
> > 
> > 我只是说Vue和react 某一领域的性能比较 ，给出不佳回应的是你们 成员某人 ，自己翻楼 ， 我也并不否认ant 贡献 ，你们否认我的说法你们没手实现？
> 
> 我翻楼也没看见谁否认你说的别人更流畅！

![image](https://user-images.githubusercontent.com/24733229/77847406-70188900-71ef-11ea-8316-bd1afe311a90.png)
antd-vue是别人的啊？ 我也没有比较两个框架吧 我只是说某个领域vue 的性能  ，请问你是ant团队的吗？你没有手也没有眼睛?

**Comment by yoyo837** [comment]
> > > > > > 你这个反馈没有可操作性啊，要怎么做才能视觉效果更好，体验更舒服呢？
> > > > > 
> > > > > 
> > > > > 即使去掉动画 antd-react 和 antd-vue 都摆在那 肉眼都能辨别的 你没眼睛吗
> > > > 
> > > > 
> > > > 你没有手不知道自己实现吗？
> > > 
> > > 
> > > 我只是说Vue和react 某一领域的性能比较 ，给出不佳回应的是你们 成员某人 ，自己翻楼 ， 我也并不否认ant 贡献 ，你们否认我的说法你们没手实现？
> > 
> > 
> > 我翻楼也没看见谁否认你说的别人更流畅！
> 
> ![image](https://user-images.githubusercontent.com/24733229/77847406-70188900-71ef-11ea-8316-bd1afe311a90.png)
> antd-vue是别人的啊？ 我也没有比较两个框架吧 我只是说某个领域vue 的性能 ，请问你是ant团队的吗？你没有手也没有眼睛?

我问你谁在否认你的说法？你莫名其妙发哪门子鬼火？

**Comment by yoyo837** [comment]
别人的回复在前，antd-vue链接建议在后，问人家有没有眼睛，你怎么不先问问自己？

**Comment by yoyo837** [comment]
那个手势 是对

> vue 更流畅 

的回复，和antd-vue或者element-ui的实现更流畅毫无关系。

**Comment by afc163** [comment]
偏离讨论了。
