### ISSUE TITLE
feature request：select组件性能优化

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design#22311]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 可以解决多选模式下，选项超过30个后组件出现卡顿的问题，卡顿demo：官方的[demo](https://codesandbox.io/s/zzuj7)

### What does the proposed API look like?
期望是多选模式下，选项多了也不会卡顿的问题

**Comment by afc163** [comment]
你提供的例子看上去 10000 个也一点不卡。

**Comment by afc163** [comment]
你看上去反馈问题而不是 feature request，请使用 bug report 的模板来报告问题。
