### ISSUE TITLE
table的column定义中的title的入参没有当前表格的任何数据，希望获取到当前表格的data

### ISSUE THREAD

**Issue by Ghostliming** [ant-design/ant-design#22319]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
由于有多个table，需要在每一个table上的header上有一个批量操作表格数据的功能，目前由于header中只返回了filters，sortOrder，sortColumn，这个和数据无任何关系，我就无法在此做处理。

### What does the proposed API look like?
```js
interface ColumnProps<T> {
    title?: React.ReactNode | ((options: {
        data?: T[];
        filters: TableStateFilters;
        .......
    }) => React.ReactNode);
    .........
}
```

**Comment by zombieJ** [comment]
用受控模式获取 onChange 里的 `data`。
