### ISSUE TITLE
Dynamically assign Title value to PageHeader through state

### ISSUE THREAD

**Issue by PeterHassaballah** [ant-design/ant-design#22324]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-329u0)

### Steps to reproduce
add a state to the sand box and try to replace it with the title and observe the result 

### What is expected?
Dynamically assign 'Title' prop value of PageHeader using react state.

### What is actually happening?
Title does not show when the value is the this.state.title instead of a "string "

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.9.0 |
| System | Win 10 |
| Browser | Chrome Version 80.0.3987.132 (Official Build) (64-bit) |

**Comment by afc163** [comment]
```diff
    <PageHeader
      ghost={true}
      backIcon={false}
-     Title={t}
+     title={t}
      subTitle="subtitle"
      style={{ background: "#F4F7FC" }}
```
