### ISSUE TITLE
TreeSelect 可以在选中某元素后展示path么

### ISSUE THREAD

**Issue by light564** [ant-design/ant-design#2232]
### 本地环境

- antd 版本: 1.6.2
- 操作系统及其版本：Mac
- 浏览器及其版本: chrome  51

### 你期待的结果是：

选择"子节点一" 后显示"节点一>子节点一"

**Comment by warmhug** [comment]
#1709

**Comment by light564** [comment]
在form里面怎么做呢？
确实有办法获取这个path，但获取后怎么填进去？

**Comment by warmhug** [comment]
使用`labelInValue`，参考这里的demo，http://react-component.github.io/tree-select/examples/basic.html
![image](https://cloud.githubusercontent.com/assets/2011119/16488581/d0281ff4-3f03-11e6-8cef-0184f8cdcc4a.png)

**Comment by light564** [comment]
```
onChange(value) {
    console.log(value);
    this.setState({ value });
}
<TreeSelect style={{ width: 300 }}
    value={this.state.value}
    dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
    placeholder="请选择"
    allowClear
    treeDefaultExpandAll
    labelInValue
    onChange={this.onChange}
    >
    <TreeNode value="parent 1" title="parent 1" key="0-1">
        <TreeNode value="parent 1-0" title="parent 1-0" key="0-1-1">
            <TreeNode value="leaf1" title="my leaf" key="random" />
            <TreeNode value="leaf2" title="your leaf" key="random1" />
        </TreeNode>
        <TreeNode value="parent 1-1" title="parent 1-1" key="random2">
            <TreeNode value="sss" title={<b style={{ color: '#08c' }}>sss</b>} key="random3" />
        </TreeNode>
    </TreeNode>
</TreeSelect>
```

选择的时候  Uncaught TypeError: Cannot read property 'length' of undefined
(anonymous function)	@	VM66285:45031
fireChange	@	VM66285:45046
onSelect	@	VM66285:44629
onSelect	@	VM66285:45979
onSelect	@	VM66285:46427
domProps.onClick	@	VM66285:46665

**Comment by warmhug** [comment]
使用`treeData`，不要用`TreeNode`自己拼接了。注意 value 的格式。

**Comment by light564** [comment]
```
const treeData = [{
          label: '节点一',
          value: '0-0',
          key: '0-0',
          children: [{
            label: '子节点一',
            value: '0-0-1',
            key: '0-0-1'
          }, {
            label: '子节点二',
            value: '0-0-2',
            key: '0-0-2'
          }]
        }, {
          label: '节点二',
          value: '0-1',
          key: '0-1'
        }];
<TreeSelect style={{ width: 300 }}
                value={this.state.value}
                dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
                treeData={treeData}
                placeholder="请选择"
                treeDefaultExpandAll
                labelInValue
                onChange={this.onChange}/>
```
选择的时候有同样的问题。

**Comment by warmhug** [comment]
我上边demo没问题吧？有问题给出可运行demo

**Comment by light564** [comment]
http://codepen.io/light564/pen/WxjXpk?editors=001

**Comment by warmhug** [comment]
升级到 rc-tree-select@1.7.5

**Comment by light564** [comment]
1.6.2的 antd 用的rc-tree-select是1.7.2，升级到1.7.5后还是有同样的问题。
但直接用rc-tree-select 1.7.5就是正常的。
你们是推荐使用rc-tree-select的 TreeSelect么

**Comment by warmhug** [comment]
不是推荐。antd 依赖组件的末尾小版本号，要保持最新。

**Comment by light564** [comment]
http://codepen.io/light564/pen/VjWBXw?editors=001
升级到1.6.3就好了，Form里面做的话有点麻烦，以上是我的做法

**Comment by light564** [comment]
@warmhug  追问一下，假设我将TreeSelect封装了一层成了另外一个组件，我如何在setFieldsValue的时候不传入{treeSelect: {value:123, label: 'path'}}，而是用  {treeSelect: 123} ?

**Comment by warmhug** [comment]
既然封装了一层，在封装的组件里、处理下输入值、不就可以了吗？先自己尝试下看看、有问题可以贴出demo讨论。

**Comment by light564** [comment]
@warmhug   这种方式虽然可以实现，但getFieldsValue的时候，取到的值依然是   {value:123, label: 'path'} 这种格式的。如何让  getFieldsValue 的时候也只获得  treeSelect: 123  ？

**Comment by warmhug** [comment]
试试 http://react-component.github.io/form/examples/normalize.html  normalize 配置

**Comment by light564** [comment]
@warmhug   功能实现了 但是有个小问题
[丢失了表单校验的样式](http://codepen.io/light564/pen/oLZOpb?editors=001)

**Comment by warmhug** [comment]
再参考下这里 http://react-component.github.io/tree-select/examples/form.html  
![image](https://cloud.githubusercontent.com/assets/2011119/16679776/bc48d162-451c-11e6-85ec-314eddcf8358.png)
