### ISSUE TITLE
dismiss tooltip after some amount of time

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#22327]
- [ yes] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have an icon on my table, and when I'm clicking on it, it copies some text to the clipboard.  and after that, I'm showing tooltip with the text "Copied".

I want to dismiss the tooltip after one second 

### What does the proposed API look like?
``` <Tooltip placement='bottom' trigger='click' title="Copied" dismiss={1000}>```

**Comment by mzndako** [comment]
Let me do it

**Comment by afc163** [comment]
You can control it by `visible` or use `mouseLeaveDelay`.
