### ISSUE TITLE
Input placeholder permitting string | ReactNode

### ISSUE THREAD

**Issue by CarolineBoyer** [ant-design/ant-design#22323]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For now as featured in the doc, basic usage of Input is as followed:
```javascript
import { Input } from 'antd';
ReactDOM.render(<Input placeholder="Basic usage" />, mountNode);
```

When you want to internationalized it using react-intl, you can't pass a ReactNode such as 
```<FormattedMessage id={anId} values={someValues} />```
to the placeholder.
Doing so right now triggers a Typescript error and just show an [Object object] inside the placeholder.

### What does the proposed API look like?
Similar to what has been done for Select entry that allows placeholder to be a string or a ReactNode.

**Comment by afc163** [comment]
https://www.google.com/search?client=firefox-b-d&q=Input+placeholder+FormattedMessage

**Comment by CarolineBoyer** [comment]
I know the workaround for FormattedMessage, but what if you have another library or something...
Why would placeholder for Select and for Input be considered differently ?

**Comment by afc163** [comment]
Input `placeholder` is `placeholder` attribute of native input, you can set a custom react node placeholder to native input.
