### ISSUE TITLE
[4.x Table] [Bug!!!] [有demo!] 官方demo可伸缩列, 加上scroll.y值, 拉伸就开始错乱了.

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#22333]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-tdd-79igg)

### Steps to reproduce
拉伸表头.

### What is expected?
拉伸表头, 表头列和内容列保持一致.

### What is actually happening?
拉伸表头后, 表头列和内容列开始错乱.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome 80 |

---
[严重严重]

**Comment by crawler-django** [comment]
table scroll不能设置y值啊, 设置了y值, 拉伸列就错乱了.

**Comment by yoyo837** [comment]
Each child in a list should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.

跟这个可能有关

**Comment by yoyo837** [comment]
dataIndex 也是重复的

**Comment by crawler-django** [comment]
我已经更新了demo: https://codesandbox.io/s/determined-tdd-79igg
不是dataIndex重复的问题. 我dataIndex逐个换了, 只要表头横向有滚动, 设置scrolly, 就会错乱。
如果表头横向没有滚动, 好像没有什么太大问题, 虽然会稍微抖动, 但是有横向滚动后, 就不行了.

**Comment by yoyo837** [comment]
和滚动没关系。我有一样的场景，一切正常。

**Comment by yoyo837** [comment]
单独拿一个数据来记录width , 如果有优先使用

**Comment by crawler-django** [comment]
我更新后的demo您显示是正常的吗? 我自己测试这个demo是有问题的, 例子是官方拉来 多改了几个数据测试的.
我自己去掉scrolly值就正常了.

**Comment by yoyo837** [comment]
嗷，我的是3.x的。

**Comment by crawler-django** [comment]
哈哈😃 3.x确实是正常的.  最近项目升4 今天才发现 不然我也不知道.

**Comment by crawler-django** [comment]
据发现, 设置了scrolly的时候, 一拉伸, colgroup下的col们的宽度只有变化的那个有值.
而没有设置scrolly, 一拉伸, colgroup下的col们的宽度都有值.

**Comment by crawler-django** [comment]
我在rc-table测试是没有问题的. 有没有scrolly值, 都不会错乱.
但是在antd4.x就有这个问题. 
是不是某个样式冲突了?

**Comment by davidcun** [comment]
从3.x升级到4.x之后，就算Reinstall之后，我以前的表格也出现了这个问题，把表格放在Modal里面，设置了scroll.y，表头就错乱，删除scroll.y就没问题，还有第一次打开是有问题的，第二次打开Modal又没问题了，但是单纯的写个例子，又重现不了

**Comment by crawler-django** [comment]
我刚下载了现在master的代码, 发现没有问题了

**Comment by davidcun** [comment]
那估计这周发布之后就没问题了

**Comment by zombieJ** [comment]
`rc-table` 被 codesandbox 缓存了，最新版本修过了。https://codesandbox.io/s/determined-hypatia-52c4o

**Comment by tylerrrkd** [comment]
多了这一行导致的，`ant-table-measure-row`

**Comment by QianDingwei** [comment]
> 多了这一行导致的，`ant-table-measure-row`

同遇到表格多了ant-table-measure-row这么一行，是什么原因尼，请问如何解决

**Comment by QianDingwei** [comment]
ant-table-measure-row多了一条空白行
![image](https://user-images.githubusercontent.com/47747920/79308432-2805a000-7f2b-11ea-9926-8575c18786d2.png)

**Comment by yoyo837** [comment]
删除 node_modules lock文件重装 不行吗？

**Comment by QianDingwei** [comment]
是package.lock.json嘛？我今天才升级的ant4，不理解，麻烦指教



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;; 
发送时间: 2020年4月15日(星期三) 下午3:13
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "1370336125"<1370336125@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] [4.x Table] [Bug!!!] [有demo!] 官方demo可伸缩列, 加上scroll.y值, 拉伸就开始错乱了. (#22333)





 
删除 node_modules lock文件重装 不行吗？

**Comment by xrkffgg** [comment]
对， package.lock.json   yarn.lock  node_modules  都删，再重新 install

**Comment by QianDingwei** [comment]
好的，我一会试试，谢谢，麻烦了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2020年4月15日(星期三) 下午4:20
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "1370336125"<1370336125@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] [4.x Table] [Bug!!!] [有demo!] 官方demo可伸缩列, 加上scroll.y值, 拉伸就开始错乱了. (#22333)





 
对， package.lock.json   yarn.lock  node_modules  都删，再重新 install

**Comment by QianDingwei** [comment]
大佬，昨天试了你的方法，发现好像还是不行，table前面多一个空白行，就像下面这个图所示

麻烦问一下，还有其他解决办法嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2020年4月15日(星期三) 下午4:20
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "1370336125"<1370336125@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] [4.x Table] [Bug!!!] [有demo!] 官方demo可伸缩列, 加上scroll.y值, 拉伸就开始错乱了. (#22333)





 
对， package.lock.json   yarn.lock  node_modules  都删，再重新 install

**Comment by yoyo837** [comment]
@QianDingwei 提供复现

**Comment by tylerrrkd** [comment]
@QianDingwei 我现在暂时的解决方法是给 `.ant-table-measure-row` 设置样式，样式如下：

```
.ant-table-body .ant-table-measure-row {
  visibility: collapse;
}
```

**Comment by lovexiaobai222** [comment]
> 多了这一行导致的，`ant-table-measure-row`

对呀，这个ant-table-measure-row是起什么作用呢？

**Comment by carreylife** [comment]
同问， ant-table-measure-row是做啥用的

**Comment by JounQin** [comment]
同问，现在导致 css `> tr:first-child` 无法正确匹配。。。

@zombieJ

**Comment by JounQin** [comment]
找到了一个 workaround 同时支持 `ant-table-measure-row` 存在或者不存在的情况：

```less
.@{table-prefix} {
  &:first-child,
  &.@{table-prefix}-measure-row + tr {
  }
}
```

**Comment by vectorx5** [comment]
this worked for me

```
.ant-table-tbody .ant-table-measure-row {
  visibility: collapse !important;
}
```
