### ISSUE TITLE
table columns render this 绑定

### ISSUE THREAD

**Issue by flicker85** [ant-design/ant-design#2233]
```js
const columns = [{
  title: '姓名',
  dataIndex: 'name',
  render: name => {return <a href="#">{name}</a>},
  width: '20%',
}, {
  title: '操作',
  key: 'operation',
  //render(text, record) { console.log(this.openEditModal) }
  render: (text, record) => {  return <a href="#" onClick={this.openEditModal.bind(this, 'edit')}>编辑</a> }
}];

export default class extends React.Component {
  openEditModal(mode) {
    this.setState({ editModal: { open: true, mode } });
  }

  render() {
    return (
      <div>
        <Button type="primary" onClick={this.openEditModal.bind(this, 'add')}>testBtn</Button>
        <Table columns={columns} />
      </div>
    );
  };
}
```

大概就是这个意思, 怎么样才能让编辑按钮能调用到Component中的openEditModal函数?
是必须把columns的定义写到Component的render函数肿么?

**Comment by benjycui** [comment]
不一定是在 `render` 内，但是一定要放在组件内部。

https://github.com/ant-design/ant-design/issues/1762

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by wxhm1120** [comment]
同问。。。。

**Comment by hu-ke** [comment]
It would be more clear:

export function getColumns() {
            return [
                {
                  title: '编号' ,
                  dataIndex: 'id' ,
                  key: 'id' ,
                } ,
                {
                  title: '操作' ,
                  key: 'operator' ,
                  render: ( text , record) => {
                    return <a href="javascript:void 0;" onClick={this.handlePick.bind(null,record)}>删除</a>
                  }
                }
            ] ;
        }

import { getColumns } from './columns'

export default class MyTasks extends Component {
    constructor( props ){
        super( props ) ;
        this.columns = getColumns.call( this ) ;
    }
    render(){
        return <Table columns={ this.columns } dataSource={ [ {} , {} , ... ] } />
    }
}

**Comment by hu-ke** [comment]
It would be more clear:

export function getColumns() {
  return [
    {
      title: '编号' ,
      dataIndex: 'id' ,
      key: 'id' ,
    } ,
    {
      title: '操作' ,
      key: 'operator' ,
      render: ( text , record) => {
        return <a href="javascript:void 0;" onClick={this.handlePick.bind(null,record)}>删除</a>
      }
    }
  ];
}

import { getColumns } from './columns'

export default class MyTasks extends Component {
  constructor( props ){
    super( props ) ;
    this.columns = getColumns.call( this ) ;
  }
  render(){
    return <Table columns={ this.columns } dataSource={ [ {} , {} , ... ] } />
  }
}

**Comment by hu-ke** [comment]
It would be more clear:
```
export function getColumns() {
  return [
    {
      title: '编号' ,
      dataIndex: 'id' ,
      key: 'id' ,
    } ,
    {
      title: '操作' ,
      key: 'operator' ,
      render: ( text , record) => {
        return <a href="javascript:void 0;" onClick={this.handlePick.bind(null,record)}>删除</a>
      }
    }
  ];
}

import { getColumns } from './columns'

export default class MyTasks extends Component {
  constructor( props ){
    super( props ) ;
    this.columns = getColumns.call( this ) ;
  }
  render(){
    return <Table columns={ this.columns } dataSource={ [ {} , {} , ... ] } />
  }
}
```

**Comment by chenyu1990** [comment]
```
{
      title: '状态',
      dataIndex: 'status',

      render: (val, record) => {
        return <Fragment>
          <Badge status={statusMap[val]}/>
          <Switch checkedChildren="正常" unCheckedChildren="禁用" onChange={() => this.handleSwitchUserStatus(record)} defaultChecked/>
        </Fragment>;
      },
    },
```
