### ISSUE TITLE
doc: is Tabs in official website normal ？ 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#22337]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
- 打开官网链接
- 如果没出现，刷新一下

### What is expected?
- 显示正常

### What is actually happening?
- 焦点会自动聚焦在 自定义页签头的 tab 1

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | The latest |
| System | mac |
| Browser | chrome  火狐 |

---
- 本地开发环境没有这个现象
- 也没有发现 `Tabs` 最近有代码更新
- 不知道你们点开有没有这个现象

**Comment by xrkffgg** [comment]
@yoyo837 你看下你点开会这种情况吗？

**Comment by afc163** [comment]
有。

**Comment by yoyo837** [comment]
有。

**Comment by shaodahong** [comment]
Maybe cause by https://github.com/react-component/tabs/pull/218

**Comment by xrkffgg** [comment]
是多了 `tabindex`

**Comment by afc163** [comment]
好了，部署错了分支。

**Comment by xrkffgg** [comment]
还有这个 https://ant.design/components/list-cn/#components-list-demo-infinite-load

滚动加载  和   滚动加载无线长列表

这两个 Demo 是不是 有点问题？

**Comment by afc163** [comment]
> https://randomuser.me/api/?results=5&inc=name,gender,email,nat&noinfo

mock 接口挂了。
