### ISSUE TITLE
Form inline, size=small 情况下，水平对齐问题

### ISSUE THREAD

**Issue by LPegasus** [ant-design/ant-design#2234]
### 

- antd 版本:
├─┬ antd@1.5.1
├─┬ antd-tools@0.9.3
│ ├─┬ antd-md-loader@0.7.7
├── babel-plugin-antd@0.4.0
- 操作系统及其版本：OSX 10.11.5 
- 浏览器及其版本: Chrome 51.0.2704.106

### 你做了什么？
引入了antd的Form、FormItem、Input、Cascader

### 你期待的结果是：
像官网一样正常显示

## 实际上的结果：
当Input的和Cascader的size设置为small时，
```javascript
<FormItem><Input size="small" /></FormItem>
<FormItem><Cascader size="small" /></FormItem>
```
不在同一个水平面上。Cascader相对于Input下沉了1px

### 可重现的在线演示
http://codepen.io/anon/pen/vKmLva

**Comment by afc163** [comment]
![](https://zos.alipayobjects.com/rmsportal/wJxeKJIGZuPcMls.png)

左右高亮也被截断了。

**Comment by ddcat1115** [comment]
网站上上下左右都没有，我一并看下

**Comment by ddcat1115** [comment]
本周发布会fix掉，close了
