### ISSUE TITLE
DatePicker set Value 的一个问题

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#22342]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-tnrul)

### Steps to reproduce
需求随手写了个例子，发现个奇怪的问题
例如：
1. 开始时间选个 2020/3/5
2. 结束时间选个 2020/3/6
3. 开始时间选个 2020/3/7

### What is expected?
时间是正确的

### What is actually happening?
log打印与时间组件不一致

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.4.1 |
| System | win10 |
| Browser | 谷歌浏览器 |

**Comment by zombieJ** [comment]
```diff
- vlue={endTime ? moment(endTime, "YYYY-MM-DD") : undefined}
+ value={endTime ? moment(endTime, "YYYY-MM-DD") : undefined}
```
