### ISSUE TITLE
Descriptions 组件 layout 属性值为vertical 时 label 不应该有冒号

### ISSUE THREAD

**Issue by baizn** [ant-design/ant-design#22340]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
不需要

### Steps to reproduce
```
<Descriptions title='未生效变更' layout="vertical" column={4}>
     <Descriptions.Item label="类型">type</Descriptions.Item>
</Descriptions>
```

### What is expected?
layout 属性值为 vertical 时， label 中不应该有冒号

### What is actually happening?
![image](https://user-images.githubusercontent.com/9443867/76932022-e92cfc00-6924-11ea-9fcb-95e07acfdb74.png)

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 0.16.x |
| System | mac |
| Browser | chorme最新 |

**Comment by neo20** [comment]
这个问题加一个 `colon={false}` 不就可以了吗

像这样

    <Descriptions colon={false} title='未生效变更' layout="vertical" column={4}>
             <Descriptions.Item label="类型" >type</Descriptions.Item>
             <Descriptions.Item label="类型1" >type1</Descriptions.Item>
             <Descriptions.Item label="类型2" >type2</Descriptions.Item>
             <Descriptions.Item label="类型3" >type3</Descriptions.Item>
    </Descriptions>

**Comment by youngjuning** [comment]
```less
:global {
  .ant-descriptions-item-label::after {
    content: ''
  }
}
```
