### ISSUE TITLE
RangePicker: can disabledDate distinguish 'start' and 'end' partial

### ISSUE THREAD

**Issue by zuolei828** [ant-design/ant-design#22345]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to make the rangepicker 'start' partial and 'end' partial the different disabledDates.
eg: I can select the 'start' partial to any date, but i want the 'end' partial's valid date is not 14days longer after the 'start' partial's selected date 

### What does the proposed API look like?
```javascript
disabledDate(current, type) {
   if (type === 'start') {
     return .......
   }
   if (type === 'end') {
     return .......
   }
}


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment]
https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date

**Comment by zuolei828** [comment]
> https://ant.design/components/date-picker/#components-date-picker-demo-disabled-date

Not the disabledTime, I mean the disabledDate

**Comment by afc163** [comment]
https://codesandbox.io/s/disabled-date-time-ant-design-demo-5k3yr

**Comment by afc163** [comment]
上面这个 demo 还发现了一个 RangePicker 的底层 bug：#22351

**Comment by zuolei828** [comment]
> 上面这个 demo 还发现了一个 RangePicker 的底层 bug：#22351

感谢demo！我也直接用中文啦。您这个demo第一次是可以的，如果已经选择了3月1号到3月8号，再次打开picker组件就无法达到效果了，这时候start和end都已经被限制了。
如果有可能地话，还是希望分别动态针对start和end来分别disableDate。这样我打开start，就可以不限制，随意更改。打开end，针对start的选值去设置disableDate。和disableTime那个api是类似的。这个问题的关键还是一个disableDate，我无法在start和end都有值的时候，区分彼此的限制范围

**Comment by afc163** [comment]
> 这时候start和end都已经被限制了

1. 可以用的，你可以选一个中间的值，另一个值可选范围会往前/往后推 7 天。
2. 也可以直接清除了重选。
3. 也可以修改一下交互。如果两个值都选上了，那么 `disableDate` 都返回 `true`。此时修改了一个日期时判断另一个日期是否超出范围，超出就清空重选。（这里要用到完整受控模式）

**Comment by zuolei828** [comment]
> * 可以用的，你可以选一个中间的值，另一个值可选范围会往前/往后推 7 天。
> * 也可以直接清除了重选。
> * 也可以修改一下交互。如果两个值都选上了，那么 `disableDate` 都返回 `true`。此时修改了一个日期时判断另一个日期是否超出范围，超出就清空重选。（这里要用到完整受控模式）

您好，再次感谢回复！是这样的，我描述下我这边的需求，产品要求的是查看任意180天范围内的报表数据。这块的逻辑在之前ant3时候是写好的了，但是这次升级到4，这里就不好用了，因为日期组件分成了开始和结束日期单独选择。
您这里的第一点和第二点不满足产品的交互。第三点的话，我再看看怎么去写~
另外提一点，ant3版本的日期组件，有可能地话，能不能和Form表单一样，给出一个3的兼容版本，好让我们平滑升级~
