### ISSUE TITLE
Scroll-x is visible while it useless

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#22346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1ez7l)

### Steps to reproduce
用ie浏览器打开，即可重现

### What is expected?
无论column总宽度小于或等于屏幕宽度时，横向滚动条消失

### What is actually happening?
在ie11下，table设置 scroll={{x:'max-content'}}，无论column总宽度为多少，总会导致横向滚动条出现

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.8.4 |
| System | win 10 |
| Browser | Chrome 78.0.3904.70 |

![image](https://user-images.githubusercontent.com/4223563/78004594-fdb8bd80-7342-11ea-9309-7c373a79b97e.png)
![image](https://user-images.githubusercontent.com/4223563/78004635-0ad5ac80-7343-11ea-95f9-1a2d7083fdfe.png)

**Comment by l745230** [comment]
很久以前我也问过这个问题,然后官方回复让我自己写样式调...overflow-x:auto.
最终不了了之. 客户没揪着不放,我也懒得改了-.-

**Comment by wufeng87** [comment]
ie11 那你应该也有这个问题：https://github.com/ant-design/ant-design/issues/22341

**Comment by devuxer** [comment]
I'm unable to even override this via less. I tried:

```css
.ant-table-wrapper div.ant-table-content {
    overflow-x: auto;
}
```

But the scroll style appears to be set directly on the div, so it takes precedence.

Hope this can be fixed soon.

**Comment by afc163** [comment]
Duplicate of #25124
