### ISSUE TITLE
Packaging error in cascader/style/css.js

### ISSUE THREAD

**Issue by opatut** [ant-design/ant-design#22357]
### Reproduction link

Build error, cannot show with build from CDN.

### Steps to reproduce

* use webpack and babel-plugin-import
* `import {Cascader} from 'antd'`
* try to run webpack build

### What is expected?
The build works.

### What is actually happening?
Error 

```
node_modules/antd/es/cascader/style/css.js:
Module not found: Error: Can't resolve './rtl.css' in '.../node_modules/antd/es/cascader/style'
```

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | Arch Linux |
| Browser | N/A |

---
See also #22328 and https://github.com/ant-design/ant-design/issues/21656#issuecomment-600376753

**Comment by kothing** [comment]
这个是如何解决的？

**Comment by yoyo837** [comment]
等发布

**Comment by muhaimincs** [comment]
hello

**Comment by yoyo837** [comment]
@muhaimincs  try v4.0.4
