### ISSUE TITLE
列设置中固定列的内容区显示高度异常

### ISSUE THREAD

**Issue by avv1996** [ant-design/ant-design#22358]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7xluu)

### Steps to reproduce
上面的链接打开，看右侧效果就知道了。

### What is expected?
固定列高度正常

### What is actually happening?
部分固定列高度小于实际高度

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.9.0 |
| System | macOS Catalina 10.15.1 |
| Browser | Chrome 80.0.3987.132 |

**Comment by afc163** [comment]
chrome 里有问题。

**Comment by zombieJ** [comment]
td 用的 flex 布局导致的问题。

**Comment by zombieJ** [comment]
ref #22131

**Comment by avv1996** [comment]
其实还有个问题，就是 columns 如果 `fixed: 'right'` 的列定义写在 `fixed: 'left'` 的列定义前面，横向滚动时会出现空白列（不过因为这个可以手动排序，故不是很迫切，没有提出来）

**Comment by zombieJ** [comment]
@avv1996 开新的一个 issue 吧。我先处理这个。

**Comment by avv1996** [comment]
> @avv1996 开新的一个 issue 吧。我先处理这个。

https://github.com/ant-design/ant-design/issues/22366
