### ISSUE TITLE
ImageUploadList 如何限制上传图片的张数

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-design#2235]
### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by benjycui** [comment]
用 `beforeUpload` 限制，https://github.com/ant-design/ant-design/issues/2140

**Comment by hqwlkj** [comment]
beforeUpload 只能限制上传的文件格式，而不能限制上传文件的数量。
