### ISSUE TITLE
Descriptions在Col中无法自适应显示

### ISSUE THREAD

**Issue by GQMai** [ant-design/ant-design#22350]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daibiankuangde-ant-design-demo-trxny)

### Steps to reproduce
在Row/Col 中创建Descriptions

### What is expected?
Descriptions自适应显示

### What is actually happening?
Descriptions部分内容被遮挡
![image](https://user-images.githubusercontent.com/5309276/76943465-5e56fc00-693a-11ea-8dc4-7267bd924699.png)

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | Win10 |
| Browser | Chrome |

**Comment by GQMai** [comment]
vertical模式显示正常，horizontal模式会有问题

**Comment by yuanzicheng** [comment]
using this css to cover the default one of Descriptions:
```
.ant-descriptions-view > table {
    table-layout: fixed !important;
}
```

**Comment by GQMai** [comment]
@yuanzicheng Thanks. It works with the following settings.

 ```
    .ant-descriptions-item-label {
      white-space: unset;
      word-wrap: break-word;
    }

    .ant-descriptions-item-content {
      word-wrap: break-word;
    }

    .ant-descriptions-view > table {
      table-layout: fixed !important;
    }
```
