### ISSUE TITLE
列设置中固定列部分情况下异常显示且横向滚动时出现空白

### ISSUE THREAD

**Issue by avv1996** [ant-design/ant-design#22366]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-98qzt)

### Steps to reproduce
还有一种情况：https://codesandbox.io/s/antd-reproduction-template-n4257

### What is expected?
looks good

### What is actually happening?
looks bad

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.9.0 |
| System | macOS Catalina 10.15.1 |
| Browser | Chrome 80.0.3987.132 |

**Comment by zombieJ** [comment]
这两种配置都是不对的，console 有提示：
<img width="503" alt="截屏2020-03-18下午10 16 13" src="https://user-images.githubusercontent.com/5378891/76969971-1d74dc80-6966-11ea-893d-fb8d1d433e90.png">

<img width="510" alt="截屏2020-03-18下午10 17 08" src="https://user-images.githubusercontent.com/5378891/76970070-46956d00-6966-11ea-8f13-2b540c1ed000.png">
