### ISSUE TITLE
Layout component examples broken in the docs

### ISSUE THREAD

**Issue by affanshahid** [ant-design/ant-design#22369]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v1nbl)

### Steps to reproduce
Go to an example in the Layout component  docs. For example Header Sider. It looks perfect in the embedded version. If you click on one of the codepen/codesandbox links it doesn't display as it does in the docs.

Example: https://codesandbox.io/s/v1nbl

### What is expected?
A view that matches what is shown in the docs

### What is actually happening?
There is extra space underneath the Menu Items

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 80 |

---
It seems the docs version has the following style: 
```css
.ant-layout-header .ant-menu { line-height: inherit; }
``` 
which results in the correct display. The sandbox versions doesn't seem to have this. This is just a hunch I might be totally wrong

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16142 will be released in next patch, until then you can stick to old usage by adding `line-height` in demo: https://github.com/ant-design/ant-design/pull/16142/files#diff-b90e62d1b36c4c54ca9753741a8501e5L30

**Comment by afc163** [comment]
I redeploy documentation now.
