### ISSUE TITLE
Select能否提供设置dropdownMatchSelectWidth: false的行为和3.x保持一致

### ISSUE THREAD

**Issue by gonenoob** [ant-design/ant-design#22379]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
项目中下拉框内的选项长度是不确定的，需要显示完整。但是4.0只支持具体的数值，无法解决这个问题。能否dropdownMatchSelectWidth也支持false且和3.x行为保持一致。查看了多个关于dropdownMatchSelectWidth的issue，但是没找到解决这个问题的办法。

### What does the proposed API look like?
dropdownMatchSelectWidth: false

**Comment by afc163** [comment]
https://ant.design/docs/react/migration-v4-cn#%E7%BB%84%E4%BB%B6%E9%87%8D%E6%9E%84

v4 之后由于默认开启了虚拟滚动，`dropdownMatchSelectWidth={false}` 已经不再支持了，需要设置成数字。

**Comment by gonenoob** [comment]
> https://ant.design/docs/react/migration-v4-cn#%E7%BB%84%E4%BB%B6%E9%87%8D%E6%9E%84
> 
> v4 之后由于默认开启了虚拟滚动，`dropdownMatchSelectWidth={false}` 已经不再支持了，需要设置成数字。

那能否支持可以设置关闭虚拟滚动来支持这个功能呢？这个需求很常见啊。下拉框的数据很多都是需要看完整的信息的，而且这个长度是不固定的

**Comment by afc163** [comment]
很快就可以关闭虚拟滚动了：#21722

但是 `dropdownMatchSelectWidth={false}` 是否能加回来，我帮你 @zombieJ 。

**Comment by gonenoob** [comment]
> #21722

谢谢考虑这个问题！
很多 实际的需求都是要显示完整的数据信息的。很多项目的数据量并不是大到需要去考虑滚动的性能问题的。希望可以考虑这个问题，之前的很多issue也都是关于这个问题的。说明这是个常见的需求

**Comment by zombieJ** [comment]
> 很快就可以关闭虚拟滚动了：#21722
> 
> 但是 `dropdownMatchSelectWidth={false}` 是否能加回来，我帮你 @zombieJ 。

有的。
<img width="695" alt="截屏2020-03-20下午3 17 26" src="https://user-images.githubusercontent.com/5378891/77143321-ea456100-6abd-11ea-94a0-02175db2f7e1.png">

**Comment by afc163** [comment]
迁移文档里关于 `dropdownMatchSelectWidth` 的描述可以修改一下了。
