### ISSUE TITLE
TreeSelect in 4.0.3 cannot set customized treenode icon

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#22376]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-ant-design-demo-dh97z)

### Steps to reproduce
1. set treeIcon true.
2. set customized icon for treeNode.
3. Treenode does not have icon.

### What is expected?
Treenode has icon.

### What is actually happening?
Treenode does not have customized icon.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | win10 |
| Browser | Google Chrome  version79.0.3945.88 |

**Comment by afc163** [comment]
It is a bug, works on 3.x: https://codesandbox.io/s/jiben-ant-design-demo-xbf7x

Thx for reporting.
