### ISSUE TITLE
Time Range Slider must be adding on antd

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/ant-design#22370]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I required to use that time range slider on my app, People should be able to choose the time intervals during the day.

### What does the proposed API look like?
For example, like this https://www.npmjs.com/package/react-time-range-slider

**Comment by zombieJ** [comment]
Hi @xXAvoraXx , why not use Slider with range mode?

**Comment by xXAvoraXx** [comment]
@zombieJ but you couldn't do that like react time range slider, antd slider just only takes number values, of course I solved it this issue with antd slider by looking at the example react time range slider. but that doesn't mean that the problem is solved becouse this feature should have been added before.
