### ISSUE TITLE
Table fixed column get wrong display in ant4.0 with browser safari 12.

### ISSUE THREAD

**Issue by JerryLyu93** [ant-design/ant-design#22377]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
use safari 12 and open [fixed columns doc](https://ant.design/components/table-cn/#components-table-demo-fixed-columns), you can see that.

### What is expected?
display normally and fixed column would not scroll with table.

### What is actually happening?
Table got a blank column, and fixed columns covered the normal columns. When table scrolling, fixed column can not fixed.

[issue gif](https://s31.aconvert.com/convert/p3r68-cdx67/u12n1-rhj5k.gif)

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | macOS 10.14.6 |
| Browser | Safari 12.1.2 |

**Comment by dpyzo0o** [comment]
I have exactly the same issue

![demo](https://user-images.githubusercontent.com/24768249/78096075-48057180-740b-11ea-9801-ff565f90fc37.gif)

MacOS: 10.13.6
Safari: 12.1.2

**Comment by yoyo837** [comment]
version 13.1 (15609.1.20.111.8) can not reproduce this.

**Comment by dpyzo0o** [comment]
> macOS 10.15.4
> version 13.1 (15609.1.20.111.8) can not reproduce this.
> 
> May be related to macOS version.

So do you plan to look into this version issue or recommend user to just upgrade safari?

**Comment by yoyo837** [comment]
They should be checked first. Let's find some older mac...

**Comment by xrkffgg** [comment]
10.15.2 express OK

**Comment by yoyo837** [comment]
ref: 
https://github.com/ant-design/ant-design/issues/22773#issuecomment-606996936
https://github.com/ant-design/ant-design/issues/22773#issuecomment-610717472
https://github.com/ant-design/ant-design/issues/22773#issuecomment-610725224

**Comment by dpyzo0o** [comment]
Update

Issue gone when I upgrade safari to 13.1 (13609.1.20.111.8). The bug seems to only appear on safari 12.x

**Comment by zombieJ** [comment]
@dpyzo0o,
Thanks your feedback. Seems it's a render bug of old Safari with `sticky` precent.

**Comment by afc163** [comment]
@dpyzo0o Could you help to check whether https://preview-23161-ant-design.surge.sh/components/table/ works?

**Comment by dpyzo0o** [comment]
> @dpyzo0o Could you help to check whether https://preview-23161-ant-design.surge.sh/components/table/ works?

Sorry, I have already upgraded safari to 13.x...

**Comment by afc163** [comment]
@JerryLyu93 Could you help to check whether https://preview-23161-ant-design.surge.sh/components/table/ works?

**Comment by JerryLyu93** [comment]
我正在测试。但这个网址几乎无法访问，正在尝试在旧电脑上搭梯子。

**Comment by JerryLyu93** [comment]
The bug still exists.

The position setting (relative) in `.antd-table-thead > tr > the, .ant-table > tr > td`  cover the sticky position. If I remove the relative setting, it will look great.
