### ISSUE TITLE
Typescript errors when Select component has any props

### ISSUE THREAD

**Issue by nbhargava** [ant-design/ant-design#22373]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/nbhargava/ant-ts-select-repro](https://github.com/nbhargava/ant-ts-select-repro)

### Steps to reproduce
Run `docker-compose up` and visit http://localhost:3000. It fails to load (because Typescript fails to compile)

Remove `defaultValue` and typescript compiles everything properly. This was demonstrated with just `defaultValue` but seems to be a problem with virtually all props passed to Select.

### What is expected?
It should compile properly and let me use the allowed props for Select.

### What is actually happening?
It fails to load (because Typescript fails to compile)

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | react 16.13 |
| System | macOS |
| Browser | Chrome |

---
This bug was not present in 3.20.x

**Comment by afc163** [comment]
https://github.com/nbhargava/ant-ts-select-repro/pull/1

ts version is too old.
