### ISSUE TITLE
Unable to enter multiple characters into a text input in a form when it is a wrapped component.

### ISSUE THREAD

**Issue by jimmy-e** [ant-design/ant-design#22371]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-working-template-input-1x07q)

### Steps to reproduce
Go to the code sandbox. You will be able to type in as many characters as you want into 'Input 1', however, when you try to type in multiple characters into 'Input 2', the cursor escapes 'Input 2' after entering only one character.

### What is expected?
You are able to enter as many characters as needed into 'Input 2', a wrapped react component.

### Sample Code
```js
import React from "react";
import { Form, Input } from "antd";

const SampleComponent = ({ form }) => {
  const SampleInput = props => <Input placeholder="Input 2" {...props} />;

  return (
    <div>
      <Form.Item>
        {form.getFieldDecorator("input-1")(<Input placeholder="Input 1" />)}
      </Form.Item>
      <Form.Item>
        {form.getFieldDecorator("input-2")(<SampleInput />)}
      </Form.Item>
    </div>
  );
};

export default Form.create({ name: "sample_form" })(SampleComponent);
```

### What is actually happening?
The cursor escapes after entering only one character into 'Input 2'.

| Environment | Info |
|---|---|
| antd | 3.26.6 |
| React | 16.13 |
| System | mac OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-working-template-input-m3e6o
