### ISSUE TITLE
Can't set form initialValues from state

### ISSUE THREAD

**Issue by PillowSkyscraper** [ant-design/ant-design#22372]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vbffp)

### Steps to reproduce
Note the initial value for username is not shown in the form. It is shown in the div above the form just fine. It seems only static values work for initial values.

### What is expected?
initialValues should accept values from state as 3.x.x did. Or else we need better documentation on how to set initialValues from fetched data.

### What is actually happening?
initialValues only works if set to a static value

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome 80.0.3987.132 |

---
I am new to hooks, so maybe I don't know the proper way to do this, but couldn't find an example in the docs.

**Comment by yoyo837** [comment]
It is because your initialValue has no value when the form is initializing.

**Comment by afc163** [comment]
https://ant.design/components/form/v3/

> In v3, modifying the initialValue of un-operated field will update the field value synchronously, which is a bug. However, since it has been used as a feature for a long time, we have not fixed it. In v4, the bug has been fixed. initialValues only takes effect when initializing and resetting the form.

**Comment by israelKusayev** [comment]
I had the same problem, sometimes the `initialValues` are empty, and I need to fetch the `initialValues` form a remote server.

I've fixed it in this way

```javascript
useEffect(() => form.resetFields(), [props.initialValues]);
```

if the `initialValues` are different just reset the form.

**Comment by PillowSkyscraper** [comment]
I ended up just calling

```
form.setFieldsValue({
      username: data.username
});
```

in the useEffect after fetching the data.

I think it would be better practice to create a new useEffect that depends on the fetched data that sets the form fields. It would be nice if there was an example edit form that fetched the form data that we could use as an example.

**Comment by pkaq** [comment]
我也遇到这种问题了, initialValues是顶层组件传进来的 但这个值是需要在点击表单后通过获取id请求后台来更新的, 但使用这种解决方式 为什么怎么看都感觉很猥琐??? 正常的预期就应该是我传进来啥就渲染啥呀

```
useEffect(() => form.resetFields(), [props.initialValues]);
```

**Comment by Lactem** [comment]
> It would be nice if there was an example edit form that fetched the form data that we could use as an example.

Agreed. It would be very helpful if the docs added @israelKusayev 's solution. Very simple and effective.

**Comment by BilalurRehman-27** [comment]
> I ended up just calling
> 
> ```
> form.setFieldsValue({
>       username: data.username
> });
> ```
> 
> in the useEffect after fetching the data.
> 
> I think it would be better practice to create a new useEffect that depends on the fetched data that sets the form fields. It would be nice if there was an example edit form that fetched the form data that we could use as an example.

Saves my day (Y)

**Comment by yougikou** [comment]
I think a better way is to render the whole form when initial values loaded.

` 
  componentDidMount(){
    const data = <loadData>;
    this.setState({
      data : data,
      isLoading: false
    })
  }

  render() {
    const { data, isLoading } = this.state;

    if (isLoading) {
      return <div>isLoading</div>
    } else {
      return(
        <Form 
          size={"small"} 
          onValuesChange={this.onValuesChange.bind(this)} 
          initialValues={data}>

`

**Comment by BilalurRehman-27** [comment]
Thank you for the response. It helped me alot ❤️
________________________________

**Comment by Lukiya** [comment]
> I think a better way is to render the whole form when initial values loaded.
> 
> `
> componentDidMount(){
> const settings = getSettings();
> this.setState({
> settings: settings,
> isLoading: false
> })
> }
> 
> render() {
> const { settings, isLoading } = this.state;
> 
> ```
> if (isLoading) {
>   return <div></div>
> } else {
>   return(
>     <Form 
>       size={"small"} 
>       onValuesChange={this.onValuesChange.bind(this)} 
>       initialValues={settings}>
> ```
> 
> `

Great , this fixed my issue.

**Comment by ChhenglinHor** [comment]
When I tried to use `initialValues` the onChange event is not triggered? Any solution?

**Comment by gyx8899** [comment]
Use other parameters of ProForm to params, request

**Comment by josh231101** [comment]
> I had the same problem, sometimes the `initialValues` are empty, and I need to fetch the `initialValues` form a remote server.
> 
> I've fixed it in this way
> 
> ```js
> useEffect(() => form.resetFields(), [props.initialValues]);
> ```
> 
> if the `initialValues` are different just reset the form.

If you have no idea how what form is create a ref to the Form you are using
```
const EditUserForm = () => {
  const [user, dispatch] = useReducer(reducer, initialState)
  const form = useRef(null)

  useEffect(() => {
    form.current.resetFields()
  }, [user])
  return (
      <Form ref={form}>
      </Form>
  )
}

```

**Comment by osumoclement** [comment]
I wish there was a way of doing this from inside the form itself. As it is, I have to use ComponentDidMount and set the value with `this.formRef.current.setFieldsValue`. Looks hacky

**Comment by qiangxinglin** [comment]
I use `ModalForm` in procomponent and face the same issue, the simplest way is just add
```
modalProps={{
  destroyOnClose: true,
}}
```
to the props.

**Comment by SalisKhizarKhan** [comment]
Problem #. How to set Initial Values Using State in antd , Can't set form initialValues from state
Solution #.    
   Step 1. Declare State  : const [getReportFiltersInitialValues, setReportFiltersInitialValues] = React.useState({});
   Step 2. Reset Fields :   React.useEffect(() => form.resetFields(), [getReportFiltersInitialValues]);
   Step 3. Set State :   let reportInitalValue = { ReportType: "1", ReportMeasure: "1" };  
                          setReportFiltersInitialValues(reportInitalValue);
   Step 4 : Form Initializing  :  
           <Form
        form={form}
        name={"SearchForm"}
        initialValues={getReportFiltersInitialValues}
      >
        <Form.Item className="ant-form-item-label-custom" name={"ReportType"}>
          <Select size="large">
            <Select.Option value={"1"}>ABC</Select.Option>
          </Select>
        </Form.Item>

        <Form.Item
          className="ant-form-item-label-custom"
          name={"ReportMeasure"}
        >
          <Select size="large">
            <Select.Option value={"1"}>ABC</Select.Option>
          </Select>
        </Form.Item>
      </Form>

**Comment by EvgenyArtemov** [comment]
> I had the same problem, sometimes the `initialValues` are empty, and I need to fetch the `initialValues` form a remote server.
> 
> I've fixed it in this way
> 
> ```js
> useEffect(() => form.resetFields(), [props.initialValues]);
> ```
> 
> if the `initialValues` are different just reset the form.

Honestly, unexpected behavior. Before fetching values it's undefined, then once it's available (even with re-render) initial values aren't updating... counter intuitive :(

**Comment by kwantdev** [comment]
It's 2022 but I'm still experiencing this problem. Shouldn't it be resolved?

**Comment by dryhurst** [comment]
11/29/2022 same issue persists.

**Comment by NatalieButr** [comment]
it's 2023 and I have same problem:(

**Comment by TillMac** [comment]
02/01/2022 the same issue still persists in version 5.0.0.

**Comment by ap705** [comment]
Same issue

**Comment by manzaloros** [comment]
If this issue hasn't been fixed by now, I wonder what the AntD team would suggest for updating a form after it has been submitted.

Is it to manually reset fields like `form.setFieldValue('prop that was POSTED', newValueReceivedFromResponse)`?

**Comment by Ferid612** [comment]
I also had the same problem. My previous code:
 ```
 <Form
              onFinish={onFinish}
              initialValues={{name: "TEST" }}
            >
              <Form.Item name={['user', 'name']} rules={[{ required: true }]}>
                <Input 
                  onChange={setFormInputs}
                placeholder="*Name"
                name='name'
                
                />
              </Form.Item>
```
              
This is how I fixed it: I just changed the initial Values to:
initialValues={{user: { name: "TEST" }}}

**Comment by QuangHD-GearInc** [comment]
If you're using Form with Modal, add `destroyOnClose` props in the modal. It's working with my case.

**Comment by cincodenada** [comment]
> If this issue hasn't been fixed by now, I wonder what the AntD team would suggest for updating a form after it has been submitted.
> 
> Is it to manually reset fields like `form.setFieldValue('prop that was POSTED', newValueReceivedFromResponse)`?

I believe so, yes. From what I can tell this isn't "fixed" because `initialValues` isn't intended to be used for "edit" type forms, a better term in English would probably be defaultValues - they are static values that should be used for uninitialized fields. They are in fact called "default values" in the `Form.Item` description for `initialValues`.

If you are loading actual data values, the intended usage seems to be to call `setFieldValue` or `setFieldsValue` to load the data into the form.

**Comment by windgaucho** [comment]
In our case, we resolve using:
```
form.resetFields([]);
```

**Comment by ykazarinov** [comment]
> I ended up just calling
> 
> ```
> form.setFieldsValue({
>       username: data.username
> });
> ```
> 
> in the useEffect after fetching the data.
> 
> I think it would be better practice to create a new useEffect that depends on the fetched data that sets the form fields. It would be nice if there was an example edit form that fetched the form data that we could use as an example.

This actually worked in my case. Thank you.

**Comment by yogithesymbian** [comment]
should `defaultValue` automatic set to `const [formYogi] = Form.useForm();` 

```
<Form.Item
... ...
 ... ... >
<InputNumber<number>
  defaultValue={0}
/>
```

**Comment by yogithesymbian** [comment]
> should `defaultValue` automatic set to `const [formYogi] = Form.useForm();`
> 
> ```
> <Form.Item
> ... ...
>  ... ... >
> <InputNumber<number>
>   defaultValue={0}
> />
> ```
> 
> instead using useEffect but its still not automatic set

for example the json output just like 
```
{}
```
when typing `00`
```
{
  "yogi_number": 3
}
```
the first mount we need more action like initValue if render JSX is done by `setFieldsValue` 
more concise if `defaultValue` is work
