### ISSUE TITLE
Form.create的问题

### ISSUE THREAD

**Issue by cuisuichuan** [ant-design/ant-design#2238]
`export default Form.create()(RoleAdd);`
通过Form.create 包装后的控件 设置ref属性 调用不了包装前的拥有的函数
`<Modal visible={this.state.visible} 
 onOk={this.handleOk.bind(this)}
 okText="添 加">
<RoleAdd ref='roleAdd' />
</Modal>
`
`this.refs.roleAdd.mySubmit();`
我想通过Modal的按钮去提交表单,该如何做?

**Comment by benjycui** [comment]
其实是可以用 `ref` 的。。。

不过还是建议在 Owner 中收集表单的数据， `Modal` click 后向服务器发 Ajax 请求就好。
