### ISSUE TITLE
是否有对modal宽度的统一的全局设置

### ISSUE THREAD

**Issue by hellenhellen** [ant-design/ant-design#22385]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果通过全局的.ant-modal设置，并不生效，如果使用  !importtant 控制将会使modal中使用style特殊控制的样式失效。期望能开放全局统一样式设置的API

### What does the proposed API look like?
通过全局指令，控制modal宽度，或者当前modal的宽度设置不可变更行不那么强,通过控制样式即可生效

**Comment by afc163** [comment]
目前没有这个设置，建议封装一个自定义的 Modal 来统一宽度设置。
