### ISSUE TITLE
所有方法渲染出来的组件对prefixCls前缀都不支持

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design#22387]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.mii.red](https://www.mii.red)

### Steps to reproduce
比如 message  Modal.confirm 等  都是半支持，这种半工程 你们直接可以直接说不支持就可以了

### What is expected?
全面支持prefixcls 

### What is actually happening?
半支持

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 最新 |
| System | mac ios |
| Browser | 谷歌 |

![image](https://user-images.githubusercontent.com/24733229/77032961-e68fdc80-69e0-11ea-8fbe-1a353b3de349.png)

**Comment by afc163** [comment]
https://ant.design/components/modal-cn/#components-modal-demo-hooks
https://github.com/ant-design/ant-design/pull/20949
https://ant.design/components/modal-cn/#FAQ

**Comment by admiao** [comment]
> https://ant.design/components/modal-cn/#components-modal-demo-hooks
> #20949
> https://ant.design/components/modal-cn/#FAQ

button根本无法更改prefixcls 看见了么
