### ISSUE TITLE
How to remove Table  background of stripe 

### ISSUE THREAD

**Issue by wangdanting** [ant-design/ant-design#22383]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
How to remove Table  background of stripe. I want the table background to be white.

![image](https://user-images.githubusercontent.com/16220538/77029500-d4a93c00-69d6-11ea-9d09-808a015bca8c.png)

### What does the proposed API look like?
removeStripe = true

**Comment by wangdanting** [comment]
![89B547F1A8FA8213B7FDAD70655C9FE4](https://user-images.githubusercontent.com/16220538/77029605-1cc85e80-69d7-11ea-851d-604311a798d8.jpg)

**Comment by afc163** [comment]
Our Table don't have any styles of stripe row: https://ant.design/components/table-cn/

I think it is not a antd problem.
