### ISSUE TITLE
autosize textarea无法输入中文

### ISSUE THREAD

**Issue by light564** [ant-design/ant-design#2239]
### 本地环境

- antd 版本: 1.6.2
- 操作系统及其版本：Mac
- 浏览器及其版本: chrome 51

### 你做了什么？

使用中文输入法

### 可重现的在线演示

http://codepen.io/light564/pen/qNmVmZ?editors=001

**Comment by benjycui** [comment]
如果你说的是这种情况

![image](https://cloud.githubusercontent.com/assets/3580607/16514611/6e99dc2c-3f9f-11e6-80ce-c452f3a855c3.png)

那么应该是 chrome 的问题，chrome 的输入框在处理中文时也是有问题的。

![image](https://cloud.githubusercontent.com/assets/3580607/16514618/7db044bc-3f9f-11e6-9f3e-e8e04c1358a8.png)

**Comment by light564** [comment]
不是这种情况。
使用中文输入法，正常的情况应该是这样:


但在上面的demo中，中文输入法的面板闪退。导致输入的都是英文。

**Comment by benjycui** [comment]
要不你找多几台机器试下？看下是操作系统还是输入法导致的。

**Comment by light564** [comment]
另外，把modal去掉正常了

**Comment by light564** [comment]
mac 搜狗输入法  输入 nih
输入框显示  nnini'h  ，输入法面板存在

mac 使用自带的中文输入法  输入nih
输入框显示 nih，输入法面板消失

**Comment by benjycui** [comment]
Mac 自带的输入法，在 Chrome 中输入也有同样的问题。

![image](https://cloud.githubusercontent.com/assets/3580607/16548816/9c70ae92-41c9-11e6-9434-f07d7f3428d5.png)

**Comment by benjycui** [comment]
所以应该不是组件的问题，试着向 Chrome 或者 Mac 报 Bug，如何。

**Comment by RaoHai** [comment]
应该不是 Chrome 或者输入法的的 bug。把 modal 去掉就正常。

把代码里 `{...getFieldProps('content')} ` 这句删掉，也正常。

assgin 给我吧，我研究看看……

**Comment by lovesmilesha** [comment]
@RaoHai @benjycui 我把react升级到15.2.1解决了中文问题。但是会出现select  Unknown props的提醒。

**Comment by afc163** [comment]
try 1.6.4

**Comment by afc163** [comment]
看来是 react 和 chrome 配合的问题。@light564 可以帮忙验证下 @lovesmilesha 的说法。

**Comment by afc163** [comment]
不只是 chrome，所有浏览器都输入不了。

确实和 #2666 触发的条件一致。
