### ISSUE TITLE
Question: upload组件的previewImage

### ISSUE THREAD

**Issue by ZWkang** [ant-design/ant-design#22390]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://github.com/ant-design/ant-design/blame/20ddb402786b959e276315f9a38c4ffa16ab01e1/components/upload/UploadList.tsx#L91

### What does the proposed API look like?
请问为什么这里不做成await?
现在出现的问题是当我需要手动操作onChange的时候，例如使用upload上传后的返回值需要再走一次我自己的压缩操作。
这样子如果当压缩请求回来前就改变了uploadlist 的值，但是这个didupdate 获取预览图像 是异步的，这样子就很容易造成我及时拿到这个返回值也渲染不上去。
因为我上一步处理file object的时候thumbUrl还是为空字符串。

目前我想完成这种操作，只能通过手动再调一次previewImage。但是这样子 那组件原本的forceUpdate就浪费了。

**Comment by zombieJ** [comment]
没太看懂，有没有代码例子？

**Comment by ZWkang** [comment]
```
// 一个压缩的异步任务
async function CompressionFucntion(item: any) {
  // 因为获取预览是一个异步操作。当fileList change 触发这个异步任务
  // 此时的fileList内的元素thumbUrl有可能为空。
  const res = { ...item };
  return res;
}

// set Original FileList
function setFileList(res: any) {}

function R({
  onChange = (res: any) => {
    setFileList(res);
  },
  preview,
}) {
  const onFileListChangeHanler = async (args: any) => {
    const resultList = await Promise.all(
      args.fileList.map(async (item: any) => {
        const res = await CompressionFucntion(item);
        return res;
      }),
    );
    const res = Object.assign({}, args, {
      fileList: resultList,
    });
    if (onChange) {
      onChange(res);
    }
  };

  const uploadProps = {
    onChange: onFileListChangeHanler,
  };

  const previewProps = preview
    ? {
        listType: 'picture-card',
      }
    : {};
  return <Upload {...uploadProps} {...previewProps}></Upload>;
}

```

伪代码

**Comment by Kermit-Xuan** [comment]
@ZWkang 
https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx#L51
这里就是返回的`Promise`
