### ISSUE TITLE
more upload api

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#224]
`onRemove`  `urlResolver` `limit` 被 fileList 替代

```js
// onStart onSuccess onError onRemove 调用
function onChange(fileList){
 // [{file,status, serverResponse}]
}

<Upload onChange={onChange} fileList={[
{
 uid:'-1',
status:'complete',
 name:'x.gif',
 url:'http://x.com/x.gif',
},
{
 uid:'-2',
status:'complete',
 name:'y.gif'
 url:'http://y.com/y.gif'
}
]}>
```

<table>
<tr>
<td>fileList</td>
<td>当前的文件列表，内部 uid 设置个负数开头吧</td>
</tr>
<tr>
<td>defaultFileList</td>
<td>初始文件列表</td>
</tr>
<tr>
<td>onChange</td>
<td>列表发生变化调用</td>
</tr>
</table>

**Comment by afc163** [comment]
不兼容的改动，版本直接改到 0.9.0 好了。

**Comment by yiminghe** [comment]
嗯，你看下吧，现在的 api 不好用

**Comment by afc163** [comment]
为啥 uid 要用负数？

**Comment by yiminghe** [comment]
防止和 组件自己产生的 uid 冲突

**Comment by HeeTing** [comment]
fileList为空时，上传居然不会出发onchange...
