### ISSUE TITLE
[3.26.13] Table scroll mismatch header and body after filter reset

### ISSUE THREAD

**Issue by zxzzxxzx** [ant-design/ant-design#22408]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-sea-3n1gw)

### Steps to reproduce
1) Filter age to 32
2) Filter days to some unexistent (say 111)
3) reset days filter (see the result)
https://imgur.com/a/VTScBwF
4) When scroller is moved, table becomes OK

### What is expected?
Table header and body do match

### What is actually happening?
Table header and body mismatch

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | latest |
| System | Windows 10 |
| Browser | Chrome latest |

**Comment by afc163** [comment]
It had been fixed in antd 4.x now.
