### ISSUE TITLE
use custom Component will couse initialValue fail to transmit defaultValue to the component

### ISSUE THREAD

**Issue by LastStranger** [ant-design/ant-design#22403]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[demo site](https://codesandbox.io/s/antd-reproduction-template-o56ys)

### Steps to reproduce
```
                   <FormItem label="文档名称">
                      {getFieldDecorator('name', {
                        rules: [
                          {
                            required: true,
                            message: '请输入文档名称',
                          },
                          {
                            max: 40,
                            message: '超过40个字符最大限制',
                          },
                        ],
                        initialValue: data && data.name,
                      })(<Input placeholder="请输入文档名称, 限定40个汉字内" />)}
                    </FormItem>
```
`
const Big = (props) => <Input placeholder="请输入文档名称, 限定40个汉字内" {...props} />
`

I have a Table, and when I click an item on the table, then a Modal pops up, I use this form to show the item's values, and I have `destroyOnClose` attribute on my Modal Component, when I close the modal and click a new Item, the value seems still the last one, it doesn't change at all,

if I change the`<Input placeholder="请输入文档名称, 限定40个汉字内" />`to `<Big/>`,  the value is normal, why? what's the difference between those two?

### What is expected?
update the initalValue

### What is actually happening?
the formItem's value doesn't change

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.7 |
| System | macos |
| Browser | 76 |

---
I can't give you guys a link about my code right now, if you guys really need one, I will post a link later

**Comment by LastStranger** [comment]
@afc163 @ant-design-bot   I create a demo on sandbox,  if you click "haha" button, the drawer pops up from the right , and the input shows "haha", then you close the drawer, and click "nothing" button, the "nothing" show up, for now , nothing weird. But if you change the <Input/>'s content, and close the drawer, and click another button, then the value is the last one, it doesn't change at all.

For example, I click "haha" button ,then the "haha" show up, I change the value to be "hehe", and I close the drawer, then I click "nothing "button, it should be "nothing", but the value is"hehe",

and if I doesn't use <Dd/>, just use normal <Input/>, everything is fine. 
so I wonder what's the difference between 
```
<Dd />
const Dd = (props) => <Input placeholder="请输入文档名称, 限定40个汉字内" {...props} />;
```
```
<Input placeholder="请输入文档名称, 限定40个汉字内" />
```

**Comment by afc163** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/507615/77139375-bf084500-6ab0-11ea-8c2c-442f6ed2d51a.png">

**Comment by LastStranger** [comment]
@afc163 it's normal in my mac and my android device, maybe refresh it again? [https://codesandbox.io/s/antd-reproduction-template-o56ys](https://codesandbox.io/s/antd-reproduction-template-o56ys)

**Comment by LastStranger** [comment]
@afc163 it's been a while, any result?

**Comment by afc163** [comment]
不太理解，例子有啥问题？

![Kapture 2020-03-24 at 14 04 04](https://user-images.githubusercontent.com/507615/77393622-600c3e00-6dd8-11ea-9691-90879765a58f.gif)

**Comment by LastStranger** [comment]
@afc163  你点haha按钮开启这个抽屉后,修改被Dd组件封装的Input的内容,然后关闭抽屉,点击下一个按钮开启抽屉,然后就发现内容不是nothing而是你上一个修改的内容,
这种情况如果把Dd组件换成Input,就没有这个问题,无论怎么修改input内容,从新打开抽屉所展示的input内容都是和按钮对应的

**Comment by afc163** [comment]
https://3x.ant.design/components/form-cn/#components-form-demo-customized-form-controls

https://codesandbox.io/s/antd-reproduction-template-qi1zs

你需要 `React.forwardRef`。

**Comment by LastStranger** [comment]
升级到antd4以后不再需要`React.forwardRef`了,只需要保证value和onChange
