### ISSUE TITLE
第一次打开modal内table表头错位

### ISSUE THREAD

**Issue by starhu521** [ant-design/ant-design#22409]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/goofy-http-sn3v4)

### Steps to reproduce
每次刷新页面，第一次打开modal会错乱，之后都没问题。

### What is expected?
表头始终排列正常。

### What is actually happening?
表头第一次加载排列错乱。
设置了scroll为250，同时列宽度全设置，列宽度全不设置，最后一个不设置其余设置，都已试过，不能解决。
![image](https://user-images.githubusercontent.com/23275495/77069375-460edc00-6a23-11ea-8259-ea6f27bb2f4e.png)

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | macos10.15.2 |
| Browser | 80.0.3987.149（正式版本） （64 位） |

**Comment by zombieJ** [comment]
你的重现是好的

**Comment by starhu521** [comment]
> 你的重现是好的

![image](https://user-images.githubusercontent.com/23275495/77130164-cff58e00-6a91-11ea-8e49-4c0001831fef.png)
不行啊，我打开连接就是错掉的

**Comment by zombieJ** [comment]
清空游览器缓存试一下，这个 resize 逻辑有修过。可能是你这边/本地用的旧的版本的 rc-table。

**Comment by starhu521** [comment]
> 清空游览器缓存试一下，这个 resize 逻辑有修过。可能是你这边/本地用的旧的版本的 rc-table。

应该不是这个原因，我之前已经试过清楚浏览器缓存，删除antd依赖重装等。我看了下4.0.3版本antd的rc-table是7.3.0

**Comment by afc163** [comment]
最新的 rc-table 已经是 7.3.8 了，请检查 node_modules 里的 rc-table 的版本。

**Comment by yoyo837** [comment]
复现里面也是`colgroup` 多一个`col`。

**Comment by 13588936722** [comment]
解决了嘛

**Comment by starhu521** [comment]
> 最新的 rc-table 已经是 7.3.8 了，请检查 node_modules 里的 rc-table 的版本。

全是最新的，我这边复现概率90%。

**Comment by starhu521** [comment]
> 解决了嘛

没有呢

**Comment by starhu521** [comment]
> 最新的 rc-table 已经是 7.3.8 了，请检查 node_modules 里的 rc-table 的版本。

我这边问题的核心应该是出在异步加载数据

**Comment by 13588936722** [comment]
我就厉害了，版本问题

**Comment by afc163** [comment]
合并到 #22592 里跟踪，这里提供了可重现链接。
