### ISSUE TITLE
Table 显示筛选后的数据总数

### ISSUE THREAD

**Issue by nazhenhuiyi** [ant-design/ant-design#2240]
现在我在使用 ant design做一些开发,节省了不少的劳动力.

使用了table组件中filter功能,其会动态的改变数据的数量,但是我却没法获取到经过过滤后的数据总量.

![image](https://cloud.githubusercontent.com/assets/11942909/16513732/8365f150-3f99-11e6-96c8-acb7c34e8088.png)

这里代码是不是应该 把本地的total暴露在state中

**Comment by afc163** [comment]
可以描述一下具体需求是什么，方便整体考虑接口。

**Comment by lyuehh** [comment]
同样有这个需求，比如 根据某个条件过滤，想知道过滤后的条数

**Comment by williamkhshea** [comment]
如果可以的话，我建议再加上现在显示第一行跟最后一行数据的index，像这样

![screen shot 2016-07-24 at 5 11 30 pm](https://cloud.githubusercontent.com/assets/4775489/17082947/e0ed3a60-51c1-11e6-8008-2a8134e166bf.png)

**Comment by afc163** [comment]
@williamkhshea https://github.com/react-component/pagination/pull/42

**Comment by afc163** [comment]
发现这里已经改掉了：https://github.com/ant-design/ant-design/commit/1029419e95801a0f23bd144e13529d271270799e#diff-560531bf0c35a767c92341e7e9183ea0L642

现在已经支持显示筛选后的数据：http://codepen.io/afc163/pen/oYLMjL?editors=001

---

@williamkhshea 提到的需求等待 react-component/pagination#42 合并和发布即可。
