### ISSUE TITLE
The Form ref is none in render 

### ISSUE THREAD

**Issue by davidcun** [ant-design/ant-design#22415]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-og06y)

### Steps to reproduce
1、click button
2、the Form input display none 

### What is expected?
first click the input display

### What is actually happening?
input no show 

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | mac os |
| Browser | chrome  lastest |

---
//能不能在通过props初始化表单的时候就可以采用此form的引用
    //否则通过编辑数据的时候，只能把关联字段必填与否通过state来实现，
    //当Form字段关联比较多的时候就比较麻烦，需要搞很多state和onChange

**Comment by zombieJ** [comment]
与表单有关的操作都需要在 Form 的控制范围内。

https://codesandbox.io/s/antd-reproduction-template-l0bq9
