### ISSUE TITLE
Does not re-render on state's change

### ISSUE THREAD

**Issue by kefimochi** [ant-design/ant-design#22419]
## Does not re-render on state's change
I noticed that whenever I need initial values of a form to be derived from some external api call or external object, that antd does not re-render to match the changed data.

Here's a CodeSandbox showing what I mean. You can see in the terminal that as component mounts the `state.name` is changed from the default `Kate` to `JK`. And `state.switch` changes it's value from false to true. And yet the antd's form does not visually reflect the new changes, despite component being updated.
https://codesandbox.io/s/other-form-controls-ant-design-demo-s6g3k

It is a bug? 🤔Otherwise, how can I make the form to re-render to reflect new changes?

**Comment by braian125** [comment]
same problem, @kefimochi could you solve it?

**Comment by braian125** [comment]
> ## Does not re-render on state's change
> I noticed that whenever I need initial values of a form to be derived from some external api call or external object, that antd does not re-render to match the changed data.
> 
> Here's a CodeSandbox showing what I mean. You can see in the terminal that as component mounts the `state.name` is changed from the default `Kate` to `JK`. And `state.switch` changes it's value from false to true. And yet the antd's form does not visually reflect the new changes, despite component being updated.
> https://codesandbox.io/s/other-form-controls-ant-design-demo-s6g3k
> 
> It is a bug? 🤔Otherwise, how can I make the form to re-render to reflect new changes?

can be easily solved, see this comment https://github.com/ant-design/ant-design/issues/22372#issuecomment-602102164
