### ISSUE TITLE
input number RTL issues

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#22420]
- [yes ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-t7qkn)

### Steps to reproduce
see the attached codesandbox

### What is expected?
* tooltip for input number should be in the right 
* when input number isn't 100% width, the feedback is should be inside the input

### What is actually happening?
* tooltip for input number should be in the left
* when input number isn't 100% width, the feedback is broken

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | windows 10 |
| Browser | chrome 80 |

---
and also ..
why input number isn't 100% width by default? (like regular input) (not only in RTL mode)

**Comment by yoyo837** [comment]
There are two problems in `InputNumber`, RTL is one and hasFeedback is the other.

**Comment by yoyo837** [comment]
![Mar-20-2020 09-41-07](https://user-images.githubusercontent.com/6134547/77129442-fb2aae00-6a8e-11ea-868d-f2403badd6e1.gif)

Is this a bug that should be fixed? @zombieJ

**Comment by xrkffgg** [comment]
is InputNumber need 100% width in form by default? 
@afc163  @yoyo837

**Comment by afc163** [comment]
No, InputNumber have default width fit for numberic value.

**Comment by xrkffgg** [comment]
If you need 100% width, you can use

`<InputNumber style={{ width: '100%' }} />`

RTL has added https://github.com/ant-design/ant-design/pull/22434

**Comment by israelKusayev** [comment]
Is there a way I can use this fix, instead of waiting to version 4.0.4 ?

**Comment by yoyo837** [comment]
Waiting for the next release.

**Comment by yoyo837** [comment]
As planned it should be today.
