### ISSUE TITLE
Does not re-render on state's change

### ISSUE THREAD

**Issue by kefimochi** [ant-design/ant-design#22421]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/other-form-controls-ant-design-demo-s6g3k)

### Steps to reproduce
Open the sandbox and look at the terminal.

### What is expected?
Antd updates its form fields as the component updates. Otherwise, how can one do api calls to get the data & put it in the form if antd doesnt support it?

### What is actually happening?
I linked to a CodeSandbox showing what I mean. You can see in the terminal that as component mounts the `state.name` is changed from the default `Kate` to `JK`. And `state.switch` changes it's value from false to true. And yet the antd's form does not visually reflect the new changes, despite component being updated.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | Mac 10.14.05 |
| Browser | Chrome 80.0.3987.122 |

---
It is a bug? 🤔Otherwise, how can I make the form to re-render to reflect new changes in state?

**Comment by afc163** [comment]
`initialValues` is like `defaultValue` of input, it will only works on first render. Please use `setFieldValue` to set new value.

**Comment by kefimochi** [comment]
Thank you so much! 🙌

**Comment by huyhoangsz** [comment]
setFieldsValue does not re-render form items. This is a silly example. Let's say I have 2 items in the form (gender and age). If age > 18 then gender should be boy else gender should be girl. 

https://codesandbox.io/s/upbeat-montalcini-wlt61?file=/src/App.js

If I change the age by inputting new value to the number input, everything works as expected. However, if I change the age by clicking on the button, my app does not work.

Bug reproduce:
Step 1: Click on button 
Expect: Age is changed to 25, gender is changed to Boy
Reality: Age is changed to 25, gender is not changed

**Comment by jerome-nelson** [comment]
@huyhoangsz Try using `useForm()` and passing the prop form instance into that. That fixes your example :-)

**Comment by fgblomqvist** [comment]
Doing a `form.setFields(...)` on a nested form does not yield a re-render 😕  (the `form` is gotten from useForm)

**Comment by bibi9768** [comment]
> `initialValues` is like `defaultValue` of input, it will only works on first render. Please use `setFieldValue` or `setFieldsValue` to set new value.

thanks u

**Comment by Rupal-Malik-au9** [comment]
Rendering the drawer only when we have input values(in case of form in Drawer) and value of showDrawer is true.
 {(inputValues) && showDrawer && <Drawer/>}
