### ISSUE TITLE
menu太长时，需要scoll

### ISSUE THREAD

**Issue by kylezhang** [ant-design/ant-design#2242]
如下图，我的menu是内容都是一级的，所以当我很多时，一个屏幕就显示不下了，但是不会出现scoll，所以，能给menu加个scoll属性吗？
![Uploading menu.png…]()

**Comment by ddcat1115** [comment]
看不到图，另外，外层限高应该就可以了，如果还不行请提供 demo

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
@ddcat1115 你给的 demo 没 fork 成功。

**Comment by afc163** [comment]
```jsx
<div style={{ overflow: 'auto' }}>
  <Menu />
</div>
```
