### ISSUE TITLE
How can I set default selected value?

### ISSUE THREAD

**Issue by miyunim** [ant-design/ant-design#22426]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-tzcnh)

### Steps to reproduce
Click submit

### What is expected?
If I submit a form, I want to get a value on the selector.

### What is actually happening?
it returns just 'undefined'

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | lastest |
| System | Mac ios |
| Browser | Chrome |

---
How can I get a defaultValue if there is a selector?

**Comment by afc163** [comment]
https://codesandbox.io/s/select-uo674

You forgot to assign `name`.

**Comment by miyunim** [comment]
@afc163 
I assigned name but it doesn't work

https://codesandbox.io/s/select-mfg8n

<img width="964" alt="스크린샷 2020-03-20 오전 11 59 35" src="https://user-images.githubusercontent.com/447006/77132380-8cefe680-6aa2-11ea-85e4-3f5241735283.png">

**Comment by afc163** [comment]
https://codesandbox.io/s/select-qm5je

**Comment by miyunim** [comment]
🤔I would like to create a dynamic form.
If I add a form Item it is selected a default value.
Could I use the form without initialValue?
