### ISSUE TITLE
antd@4.0.3 cascader Cannot find module './rtl.css'

### ISSUE THREAD

**Issue by guchengjie** [ant-design/ant-design#22428]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
install antd@4.0.3，npm start 时出现Cannot find module './rtl.css'

### What is expected?
项目启动成功

### What is actually happening?
启动失败，提示Cannot find module './rtl.css'

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | window10 |
| Browser | 79.0.3945.130 |

---
import '../../style/index.less';
import './index.less';
import './rtl.css'; // style dependencies

import '../../empty/style';
import '../../input/style';

4.0.3版本的rtl.css文件没有生成，所以导致无法引用

**Comment by afc163** [comment]
Fixed in #22360
