### ISSUE TITLE
表格Column 是否可以提供一个统一的默认配置，可以对Column一些属性进行统一配置

### ISSUE THREAD

**Issue by davidcun** [ant-design/ant-design#22425]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在指定表格Column的时候，通常都需要对width，align，等这样的属性设置。aling默认是left，如果我想居中，就得每个Column都去指定align，如果提供给一个Column默认配置修改的入口，这样就对需要统一配置的Column会非常方便

### What does the proposed API look like?
Table 属性添加 columnDefaultProp = {align:'center',width:100}，当Column里面没有指定align或者width的时候就采用此配置。

**Comment by afc163** [comment]
建议封装一个上层的自定义 Table 统一收掉这类配置。
