### ISSUE TITLE
Fixed 的列在Edge浏览器下边框 消失

### ISSUE THREAD

**Issue by jakdosen** [ant-design/ant-design#22439]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### What is actually happening?
 

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | Window 10 |
| Browser | Edge |

**Comment by afc163** [comment]
Could you take some screenshot?

**Comment by kangkang12** [comment]
这个问题啥时候处理啊。edge固定列没有分割线

**Comment by afc163** [comment]
@lzqtxwd @Labriko Edge 版本是啥？

**Comment by afc163** [comment]
@jakdosen 这个问题现在还存在么

**Comment by afc163** [comment]
Closing for no response.

**Comment by LazyChun** [comment]
The problem reoccurs on the new version chrome
