### ISSUE TITLE
antd的4.0.3版本table在设置了scroll下header与body错位了

### ISSUE THREAD

**Issue by 13588936722** [ant-design/ant-design#22432]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://dev.mhealth100.com/patient/cstmr-demo/error.png](https://dev.mhealth100.com/patient/cstmr-demo/error.png)

### Steps to reproduce
设置一个scroll就可以看到

### What is expected?
不错位

### What is actually happening?
错位了

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | ^16.12.0 |
| System | window10 |
| Browser | Google Chrome 80.0.3987.149 |

---
是因为头部的table下的<colgroup>标签多生成了一个<col style="width: 0px; min-width: 0px;">导致的。

**Comment by 13588936722** [comment]
还需要添加一个滚动条隐藏的样式

::-webkit-scrollbar {
  display: none;
}

**Comment by 13588936722** [comment]
代码地址： https://codesandbox.io/s/sharp-hofstadter-du3ie?fontsize=14&hidenavigation=1&theme=dark

**Comment by zombieJ** [comment]
@13588936722 ，试试这个。看看会不会有同样的 BUG：
https://codesandbox.io/s/zealous-bartik-n4jg6

**Comment by 13588936722** [comment]
还是会出现这个bug，问题的原因就是你们生成的table的时候，在其header中的colgroup中多生成了一个col导致的。这个col是<col style="width: 0px; min-width: 0px;">。
You can check it in Browser DOM element！

**Comment by zombieJ** [comment]
你给个 gif 吧，我们这边没有 windows，看不到你的这个 bug。

**Comment by 13588936722** [comment]
![image](https://user-images.githubusercontent.com/33176701/77146884-14e7e780-6ac7-11ea-8648-75c06a06a442.png)
![image](https://user-images.githubusercontent.com/33176701/77146907-1e714f80-6ac7-11ea-9a90-0830356a5c2e.png)

当table的columns的长度与col的长度不一致的时候，就会出现这个问题。

**Comment by yoyo837** [comment]
ref: #22409

**Comment by 13588936722** [comment]
哪个他也没有解决啊，我也借鉴了他的，去看了rc-table版本，是7.3.0最新版了，我也删除node_moudles，重新install了。

**Comment by crawler-django** [comment]
等antd 弄上依赖 rc-table 7.3.8把.
好像是7.3.0有问题啊

**Comment by afc163** [comment]
@crawler-django 

重装依赖即可安装到 rc-table@7.3.8

**Comment by crawler-django** [comment]
为什么我重装的依赖是7.3.6?
![image](https://user-images.githubusercontent.com/37062307/77151874-d4419b80-6ad1-11ea-9013-4ba098ce3751.png)

**Comment by yoyo837** [comment]
有没有使用自建npm镜像

**Comment by afc163** [comment]
移除 package-lock.json 或者 yarn.lock 再装。

**Comment by 13588936722** [comment]
别移除，万一出事就尴尬了。

**Comment by crawler-django** [comment]
移除 package-lock.json 或者 yarn.lock 再装 就可以解决问题了.(目前)

**Comment by 13588936722** [comment]
晓得了

**Comment by 13588936722** [comment]
还没有好，还是错位

**Comment by crawler-django** [comment]
我的拉伸问题已经解决了.  你看看你的npm包 rc-table的版本是不是7.3.8?

**Comment by zombieJ** [comment]
@13588936722 , 帮忙跑一下 `npm ls rc-table` 看看。

**Comment by 13588936722** [comment]
@zombieJ 运行npm ls rc-table还是一样的结果。我看到rc-table的版本是最新的了（7.3.8），但是页面效果还是一样。

**Comment by lucasleelz** [comment]
安装最新版本`rc-table@7.3.13`可以解决。@13588936722

**Comment by zombieJ** [comment]
手头没有 windows，直接去掉这个 0 column 算了。

**Comment by yoyo837** [comment]
我现在手边有Windows，需要我测一下吗？

**Comment by zombieJ** [comment]
@yoyo837 ，不用了。直接去掉 0 宽度的 column 了。

**Comment by lemovel** [comment]
我这是有的浏览器有ant-table-cell ant-table-cell-scrollbar 这个样式，有的浏览器又没有，导致滚动条占了内部的位置，从而导致头部和Body步对齐

**Comment by lemovel** [comment]
我这是有的浏览器有ant-table-cell ant-table-cell-scrollbar 这个样式，有的浏览器又没有，导致滚动条占了内部的位置，从而导致头部和Body步对齐

**Comment by EyreGe** [comment]
> 

请问你这个问题解决了吗
