### ISSUE TITLE
table展开折叠图标有些行需要隐藏，有些行要显示，如果重写expandIcon，好像必须要返回一个自定义图标，怎么在保留原图标的同时，隐藏某些行的图标？

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#22443]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些行的展开行有数据，某些行没有，有展开行数据的不能折叠，没有展开行数据的可以折叠

### What does the proposed API look like?
Function(props,ReactNode):ReactNode   返回原ReactNode？

**Comment by zombieJ** [comment]
自己覆盖，再写一个一样的图标就行了。

**Comment by zhangzhi93** [comment]
> 自己覆盖，再写一个一样的图标就行了。

自己重写实现了，但是没有原来的动画效果
