### ISSUE TITLE
Table grouping header, when multiple sorting, controlled failure(Table分组表头,multiple排序时,受控失败)

### ISSUE THREAD

**Issue by zhshch9527** [ant-design/ant-design#22448]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-morning-7eceb)

### Steps to reproduce
Two columns, one grouped and one not grouped, both set multiple sort , and set sortOrder to be controlled, and update sortOrder through onChange method
两个column,一个分组，一个不分组，都设置multiple sort,并且设置sortOrder受控,通过onChange方法更新sortOrder

### What is expected?
All column sort icons can be highlighted normally
所有column的排序图标都能正常高亮选中

### What is actually happening?
The sorting icon of the grouped column is always gray and will not be highlighted according to sortOrder
分组的column的排序图标永远是灰色的，不会根据sortOrder而高亮

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.1 |
| System | windows8.1 |
| Browser | 72.0.3626.119 (official version) (64-bit) |

---
The test in other cases is correct:
1. Two columns, one grouped, one not grouped, multiple sort set, sortOrder not set
Result: the sort icon is displayed correctly
2.Two columns, set group at the same time, set multiple sort at the same time, set sortOrder at the same time
Result: the sort icon is displayed correctly
In the above connection, under the last field, also add the children group, then it is OK
其他情况的测试是正确的:
1.两个column,一个分组，一个不分组，同时设置multiple sort,不设置sortOrder
结果：排序图标正确显示
2.两个column,同时设置分组，同时设置multiple sort,同时设置sortOrder受控
结果：排序图标正确显示
在上述连接里，在最后一个字段下，也添加children分组，就可以了

**Comment by zombieJ** [comment]
Group 本身是没有 Column 概念的，不应该有 `dataIndex` 和 `sorter` 属性。TS 定义有问题，我改一下。
