### ISSUE TITLE
Tree in 4.0.3 cannot get right DOM Element after Expand action

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#22442]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyizhankaizhedietubiao-ant-design-demo-evcty)

### Steps to reproduce
1. add className '.katavorio-draggable-item' to every TreeNode leaf.
2. notify current '.katavorio-draggable-item' treenode amount after expandedKeys change.
3. cannot get the right '.katavorio-draggable-item' treenode amount real-time in 4.0.3, which is not a problem in tree of 3.x

### What is expected?
get the right amount of '.katavorio-draggable-item' treenode after expandedKeys change.

### What is actually happening?
cannot get the right amount of '.katavorio-draggable-item' treenode after expandedKeys change.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | win10 |
| Browser | Google Chrome  version79.0.3945.88 |

**Comment by zombieJ** [comment]
You should not use `document.querySelector` in render. It's not a React way.

**Comment by sdhr27** [comment]
I use `document.querySelector` in useEffect hook, and React Document says that `useEffect run after every render` and `React guarantees the DOM has been updated by the time it runs the effects`. I have to get all draggable DOM Element after expand for JsPlumb in our project.  
If you can't change the current sequence between tree render and expandKeys change, at least please provides a new API for operations after expand. @zombieJ

**Comment by sdhr27** [comment]
Wait, it's actually a little strange. If useEffect gurantees the DOM has been updated by the time it runs the effects, why can't I get the right DOM element in useEffect hook?

**Comment by sdhr27** [comment]
Also, 3.x does not have such problem. I can perfectly get the right DOM in useEffect hook.
