### ISSUE TITLE
disabled Button with Tooltip has a span wrapper, which affects css selector

### ISSUE THREAD

**Issue by rinick** [ant-design/ant-design#22453]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/weathered-night-6z6x2)

### Steps to reproduce
buttons are not aligned

### What is expected?
.group > .ant-btn {
  margin-top: 4px;
}

### What is actually happening?
the disabled button is wrapped by a span, which makes it hard to apply css selector

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome 80 |

**Comment by rinick** [comment]
change selector to `.group .ant-btn` would work, but it means developers need to be aware of this behavior when writing css.  Also there might be some use case people really need to use `>` selector

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21404#issuecomment-586800984

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/18842#issuecomment-532036147

**Comment by rinick** [comment]
@afc163  can we give that wrapper span a css className so when I really need to use the `>` selector, there is still a way to select it
```
.group > .ant-btn, .group > .ant-btn-tooltip-wrapper {
 ....
}
```

**Comment by afc163** [comment]
We should fix the align issue.

**Comment by afc163** [comment]
>  can we give that wrapper span a css className

sure, how about `.ant-tooltip-wrapper-for-disabled`?

**Comment by rinick** [comment]
> > can we give that wrapper span a css className
> 
> sure, how about `.ant-tooltip-wrapper-for-disabled`?

yep, that works for me
