### ISSUE TITLE
Replace X icons with a cross

### ISSUE THREAD

**Issue by rumkin** [ant-design/ant-design#22454]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently closing icons on modals are letters `x` and not a crosses. It looks incorrect for me because cross has exact 90 degree angles while letter `x` doesn't and this difference is significant in this case. Usually the times (`&times;`) HTML-entity is used for this.

Here is the example to see the difference.
```
× x 
```
### What does the proposed API look like?
New icon with perpendicularly crossing bars.

**Comment by shangguanhongzhou** [comment]
Triangle: the angle in the new version of icons is inspired by the American Fighter F-14 tomcat, like 76 degrees. Usually, most of the icons in applications and systems could apply 76 degrees as the start and adjust flexibly according to the actual situation.
![image](https://user-images.githubusercontent.com/8383020/81889006-23d5ac80-95d5-11ea-91ca-82fa39311817.png)

**Comment by rumkin** [comment]
@shangguanhongzhou As we all know design shouldn't prevail over function in cases where the goal is utility. In the case of cross sign angles are part of semantics (and thus function) not design, so I think it would be correct to make an exclusion for this icon or just move it to some extended iconset for the Ant's UI.

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design-icons/commit/824500349894a87562f033dbdc5e3c5d301a2f5c
