### ISSUE TITLE
Column onCell 'GetComponentProps<unknown>' error 

### ISSUE THREAD

**Issue by henryk1229** [ant-design/ant-design#22451]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/henryk1229/antd-onCell-error](https://github.com/henryk1229/antd-onCell-error)

### Steps to reproduce
Fork the repo, start dev environment and view typescript error warning at line 40:

Type '(record: unknown) => { record: unknown; }' is not assignable to type 'GetComponentProps<unknown>'.
  Type '{ record: unknown; }' has no properties in common with type 'HTMLAttributes<HTMLElement>'.ts(2322)
interface.d.ts(60, 5): The expected type comes from property 'onCell' which is declared here on type 'IntrinsicAttributes & ColumnProps<unknown>'

### What is expected?
onCell method for Column component behaves as in previous versions of ant design

### What is actually happening?
When trying to render a record onto a Column using the onCell method, this typescript error is encountered:

Type '(record: unknown) => { record: unknown; }' is not assignable to type 'GetComponentProps<unknown>'.
  Type '{ record: unknown; }' has no properties in common with type 'HTMLAttributes<HTMLElement>'.ts(2322)
interface.d.ts(60, 5): The expected type comes from property 'onCell' which is declared here on type 'IntrinsicAttributes & ColumnProps<unknown>'

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.1 |
| System | Mac  |
| Browser | Chrome Version 80.0.3987.132 (Official Build) (64-bit) |

**Comment by 757566833** [comment]
+1
I had the same problem

**Comment by kissthom** [comment]
I have the same problem. I tried to find an other way to pass the record to the cell but did not find any.
And actually there is an example in the docs itself what has to have the same issue:
https://ant.design/components/table/#components-table-demo-edit-row

**Comment by cckz** [comment]
I had the same problem, `rc-table/lib/interface.d.ts`

```tsx
export interface ColumnType<RecordType> extends ColumnSharedType<RecordType> {
    colSpan?: number;
    dataIndex?: DataIndex;
    render?: (value: any, record: RecordType, index: number) => React.ReactNode | RenderedCell<RecordType>;
    shouldCellUpdate?: (record: RecordType, prevRecord: RecordType) => boolean;
    rowSpan?: number;
    width?: number | string;
    onCell?: GetComponentProps<RecordType>;
    /** @deprecated Please use `onCell` instead */
    onCellClick?: (record: RecordType, e: React.MouseEvent<HTMLElement>) => void;
}
```

```tsx
export declare type GetComponentProps<DataType> = (data: DataType, index?: number) => React.HTMLAttributes<HTMLElement>;
```

**Comment by wocaatm** [comment]
the reason is onCell need return to React.HTMLAttributes<HTMLElement> without any customer props. The docs [](https://ant.design/components/table/#components-table-demo-edit-row) has the same problmes

**Comment by kliments** [comment]
Hello,
are there any updates? I am having the same issue here.

**Comment by takka** [comment]
Related to this issue, indeed onCell don't return any custom props and that makes this example from docs https://github.com/ant-design/ant-design/blob/master/components/table/demo/edit-cell.md having type errors if it would be in TS

**Comment by fgblomqvist** [comment]
This still seems to be an issue 😕

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/28817#issuecomment-758352026
