### ISSUE TITLE
InitialValues not passed correctly to Form.List

### ISSUE THREAD

**Issue by robbedec** [ant-design/ant-design#22452]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-williams-0gcjd)

### Steps to reproduce
https://codesandbox.io/s/hopeful-williams-0gcjd and compare the printed JSON vs the JSON in the console.

### What is expected?
The created JSON is passed to Form.List

### What is actually happening?
The input field is filled with __[object Object]__

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.3 |
| Browser | Chromium to 80.0.3987.137. |

---
I'm trying to create a form that can contain previously entered information and that can be extended with new textboxes.

**Comment by zombieJ** [comment]
`initialValues` format is not correct.

https://codesandbox.io/s/green-leftpad-33slm
