### ISSUE TITLE
Custom form component is not triggered based on dependencies

### ISSUE THREAD

**Issue by noticeMaker** [ant-design/ant-design#22458]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/withered-feather-tv9wu)

### Steps to reproduce
1. Change text to any value
2. It won't trigger the custome componet to update

### What is expected?
Whenever text changes. 
Custom form componet  will update 

### What is actually happening?
It's not triggering the custom update ，
By the way, it works in version 4.0.1

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome 79 |

**Comment by zombieJ** [comment]
`dependencies` start to work after Form.Item touched.

![Kapture 2020-03-21 at 13 04 53](https://user-images.githubusercontent.com/5378891/77219877-df99d300-6b74-11ea-8025-c56a7ba506a7.gif)
