### ISSUE TITLE
safari 中，row 组件嵌套会导致布局不对齐，内容错位

### ISSUE THREAD

**Issue by kyriejoshua** [ant-design/ant-design#22469]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-lamarr-m03z6)

### Steps to reproduce
Row 中嵌套了 Row，除此之外给 css 设置了属性。注意是只在 safari 中出现。下面 id 重复是复制的效果，请忽略……

```javascript
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Form, Input, Row, Col } from "antd";

class PureForm extends React.Component {
  render() {
    return (
      <Form>
        <Row gutter={24}>
          <Col span={8} align="center">
            <Form.Item label="E-mail" id="test">
              <Input id="test" />
            </Form.Item>
          </Col>
          <Col span={8} align="center">
            <Form.Item label="E-mail" id="test">
              <Input id="test" />
            </Form.Item>
          </Col>
          <Col span={8} align="center">
            <Form.Item label="E-mail" id="test">
              <Input id="test" />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={24}>
          <Col span={8}>
            <Form.Item label="E-mail" id="test">
              <Input id="test" />
            </Form.Item>
          </Col>
          <Col span={8}>
            <Form.Item label="E-mail" id="test">
              <Input id="test" />
            </Form.Item>
          </Col>
          <Col span={8}>
            <Form.Item label="E-mail" id="test">
              <Input id="test" />
            </Form.Item>
          </Col>
        </Row>
      </Form>
    );
  }
}

ReactDOM.render(<PureForm />, document.getElementById("container"));
```

```css
.ant-form-item {
  display: flex;
}
.ant-form-item-control-wrapper {
  flex: 1;
}
```

### What is expected?
正常对齐展示，如第二行

### What is actually happening?
第二行正常展示，第一行内容偏移

| Environment | Info |
|---|---|
| antd | 3.26.2 |
| React | react@16.12.0 |
| System | macos 10.15.3 |
| Browser | safari version 13.0.5 (15608.5.11) |

---
当我修改其中的 display 属性或者修改其中的 div 的 align 属性都能解决问题，但我想知道这个具体的原因。

解决方案 1
```css
.ant-row:after, .ant-row:before {
      display: initial; // 关键代码可以解决
      content: "";
} 
```

解决方案 2
`<div align="center" class="ant-col ant-col-8" style="text-align: center;padding-left: 12px; padding-right: 12px;">`
设置 `text-align: center`.

晚点我试着翻译成英文[捂脸]

**Comment by afc163** [comment]
我也不了解，一般这种是 safari 的样式 bug。自定义样式和 antd 样式结合使用的兼容性问题可能需要楼主自行探索一下了。

**Comment by kyriejoshua** [comment]
好吧。。以后在 safari 再遇到再关注一下。

**Comment by zombieJ** [comment]
https://codesandbox.io/s/wispy-feather-hk2vx

flex 后把 float 清除的伪类去掉。
