### ISSUE TITLE
Switch to dark theme, css order mess up

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#22460]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

![image](https://user-images.githubusercontent.com/22393991/77220217-c430c700-6b78-11ea-9171-f78609451a68.png)

### Steps to reproduce
Site switch to dark mode, CSS orders are not correct.

### What is expected?
Order like default mode. Site's CSS should override antd.less.

### What is actually happening?
Order mess up.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16 |
| System | macos |
| Browser | chrome |

**Comment by AshoneA** [comment]
https://github.com/chenshuai2144/merge-cssMoudle-less/pull/11

**Comment by AshoneA** [comment]
也会对网站上之后的 compact 模式造成一定的影响。

**Comment by afc163** [comment]
看上去也能解决 #21670 ？

**Comment by AshoneA** [comment]
@afc163 是的，应该可以，主要就是 CSS 导入的顺序不一样导致覆盖了网站的一些样式（比如 reset ）。

**Comment by afc163** [comment]
Fixed in https://github.com/chenshuai2144/merge-cssMoudle-less/pull/11
