### ISSUE TITLE
Search with remote data Example is broken due to offline Endpoint

### ISSUE THREAD

**Issue by ireznik** [ant-design/ant-design#22472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select/#components-select-demo-search-box](https://ant.design/components/select/#components-select-demo-search-box)

### Steps to reproduce
Type something into search box
open https://suggest.taobao.com

### What is expected?
Results after typing should be shown

### What is actually happening?
Nothing because endpoint responds with HTTP 404 code

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | latest |
| System | MacOS 10.15 |
| Browser | Chrome 80 |

**Comment by afc163** [comment]
<img width="344" alt="image" src="https://user-images.githubusercontent.com/507615/77247300-a93e7f80-6c6a-11ea-939f-f52b4dd7232b.png">

It works.
