### ISSUE TITLE
treeselect的树节点能更换switchicon吗？

### ISSUE THREAD

**Issue by aojiaodemeng** [ant-design/ant-design#22487]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
符合项目整体样式规范

### What does the proposed API look like?
增加api-switchIcon

**Comment by afc163** [comment]
支持的：https://codesandbox.io/s/long-shadow-60dwg
