### ISSUE TITLE
Submit form using a specific keyboard shortcut

### ISSUE THREAD

**Issue by kncs** [ant-design/ant-design#22481]
- [X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would like to be able to submit a form using  specific keyboard shortcut. it will allow end user to submit the form without using the mouse. I created a table with an editable row with multiple fields and some fields are optional. The aim is to display a message to the end user when the form is valid in order to allow him to save it with a shortcut like ctrl Enter .
See below components used into the form :
  Input 
  Select
  Text Area
  Datepicker

For now, there is not a simple way to bind the onKeyDown for all this components, Moreover, some key already have a specific and different behavior depending on components. 

### What does the proposed API look like?
For me the API should be simple, it would be perfect to have a new props "submitShortcut".

**Comment by zombieJ** [comment]
You can use `form.submit` to trigger submit with any customize keyboard shortcut.

**Comment by kncs** [comment]
Thank you for your response. 

I tried to use the onKeyPress on Form into [basic usage](https://codesandbox.io/s/7qdb9) and it works well

I tried exaclty the same thing into [Editable row](https://codesandbox.io/s/dwsn2) and it didn't work as I expected, can you advice me on why this was not working as I expect ?
