### ISSUE TITLE
Update the Ant design documentation for Table component

### ISSUE THREAD

**Issue by skyorion427** [ant-design/ant-design#22497]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It is required to set the `rowKey` prop in the Table component and the Table data should have the unique key.
If the Array of dataSource for the table has too many elements (Table has lots of rows) and there is no unique key, we should be able to set the key prop as their linear index which will be unique per row data.

### What does the proposed API look like?
It would be great if we update the documentation.  
  
- Currently, there are just 2 methods in the doc.  
....  
rowKey	Row's unique key, could be a string or function that returns a string	string|Function(record):string	key.  
...  

`// primary key is uid   
return <Table rowKey="uid" />  
// or  
return <Table rowKey={record => record.uid} />;`  
  
- In the antd lib, the rowKey prop is defined like this:  
...  
      `var recordKey = typeof rowKey === 'function' ? rowKey(record, index) : record[rowKey];`  
...  
  
- I suggest writing the detailed callback.  
...  
rowKey	Row's unique key, could be a string or function that returns a string	string|Function(record, index):string	key.  
  
`// primary key is uid  
return <Table rowKey="uid" />  
// or  
return <Table rowKey={record => record.uid} />;  
//or  
return <Table rowKey={(record, index) => index} />;`

**Comment by afc163** [comment]
Table `data` must have a primary key for features which deps on it(expand, selection, eg..), you can create one if original data does not.
