### ISSUE TITLE
建议新增Modal与Tabs完美组合

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#22492]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
建议新增Modal与Tabs完美组合，未手动调整，无法达到如何效果，tabs上方空太多

![QQ浏览器截图20200322202521](https://user-images.githubusercontent.com/3166799/77249408-d9424e80-6c7b-11ea-935b-1f3c02d86a04.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/cool-surf-ocidc
