### ISSUE TITLE
Ant v4 breaks the ability to open dropdown of Select and TreeSelect programmatically

### ISSUE THREAD

**Issue by pierre-borckmans** [ant-design/ant-design#22491]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-o9t2b)

### Steps to reproduce
In Ant v3, it was possible to programmatically open the dropdown and give focus to the search box of Select and TreeSelect components, 
using a workaround described in https://github.com/ant-design/ant-design/issues/3790#issuecomment-412281417

```
antdSelectRef.rcSelect.setOpenState(true, true);
```
Using this allowed to programmatically open the Select/TreeSelect dropdown, and to give focus to search input.
(working example using ant v3 here: https://codesandbox.io/s/antd-reproduction-template-8l0ey)

In Ant v4, the `rcSelect` and `rcSelectTree` are not available anymore, and I could not find any alternative to open the dropdown and focus the search input box.

### What is expected?
A programmatic way to open the Select dropdown and to focus the search box.
Maybe the `focus` method of Select and TreeSelect should do this by default?
Or Select and TreeSelect should expose 

### What is actually happening?
No programmatic way seem to be available to open the Select dropdown and to focus the search box

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.3.1 |
| System | MacOS 10.15.3 |
| Browser | Chrome 80 |

---
Here is a working example using ant v3:
https://codesandbox.io/s/antd-reproduction-template-8l0ey

**Comment by afc163** [comment]
You should depend on inner method of React instance, it is not React way.

We provide `open` and `onDropdownVisibleChange` props that you can control dropdown visible.

**Comment by pierre-borckmans** [comment]
Thanks @afc163. Using the `open` props also gives focus the search input box?

**Comment by afc163** [comment]
We also provide `focus` and `blur` methods for Select, you can call it  like using native input.

**Comment by pierre-borckmans** [comment]
Yes, but it does not focus the search box of the Select component.

**Comment by pierre-borckmans** [comment]
Nevermind, it seems to work now. Thanks!
