### ISSUE TITLE
DatePicker component doesn't support HTML autocomplete attribute

### ISSUE THREAD

**Issue by sagar7993** [ant-design/ant-design#22499]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-22ktp)

### Steps to reproduce
DatePicker component doesn't support HTML autocomplete attribute. I'm trying to create a checkout form where the user has to enter his credit card details and I'd like to use HTML autocomplete attributes to improve accessibility.

I'm trying to make use of the following autocomplete attribute values

* `cc-name`
* `cc-number`
* `cc-expiry`
* `cc-csc`

I'm also facing similar issue trying to implement a DatePicker for birthday field with the following autocomplete values

* `bday`
* `bday-day`
* `bday-month`
* `bday-year`

### What is expected?
When a user clicks on the DatePicker element, if there are any saved cards in the browser, and if user clicks on the autocomplete suggested value then the DatePicker component should take the correct value. This is an annoying accessibility related problem.

### What is actually happening?
When a user clicks on the DatePicker element, if there are any saved cards in the browser, or if the user's birthday is stored in the browser, it shows the cards but nothing happens when you click on it.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.1 |
| System | Mac OS X |
| Browser | Chrome |

**Comment by miguelgrc** [comment]
I'm also having problems with this. In my case I need to set `autoComplete="off"`, but this is not propagated by `DatePicker`.

**Comment by harunurhan** [comment]
seems like, this needs to be fixed on https://github.com/react-component/picker first.. I can have a look at it, if there is an interest to get it merged.

**Comment by sagar7993** [comment]
@harunurhan It would be great if you could work on this.

**Comment by Codyooo** [comment]
Same issue with TimePicker. All Components using <input /> element inside should expose autoComplete prop.😳
![image](https://user-images.githubusercontent.com/18410763/79436813-f0b6f200-8003-11ea-8c78-6a0020c3edb7.png)

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/picker/pull/46
