### ISSUE TITLE
想了解下大家使用Table组件时如何做增删改查的动效

### ISSUE THREAD

**Issue by djorkaeff** [ant-design/ant-design#2249]
如这里所描述的效果
http://motion.ant.design/#/language/interact?_k=80x79i

**Comment by afc163** [comment]
目前的实现确实有困难。

**Comment by djorkaeff** [comment]
😢

**Comment by afc163** [comment]
@jljsj33 看看能否由 rc-table 底层直接支持动画。

**Comment by jljsj33** [comment]
恩。。好像很早就有人提出了吧。。看下底层能不能加上进出场效果。。。

**Comment by jljsj33** [comment]
看了结构，，好像在 https://github.com/react-component/table/blob/master/src/Table.jsx#L389 这里改成 <QueueAnim component="tbody" type={['right', 'left']}> 就可以。。。。删除增加是有效果，，但移动的效果是没的。。。

**Comment by djorkaeff** [comment]
@jljsj33 能否在 https://github.com/react-component/table/blob/master/src/TableRow.jsx 里加个行级的单元素动画，做修改时的高亮淡出效果。目前要做的话每个column 都要写一次。

**Comment by afc163** [comment]
尝试 `<Table rowWrapper={(row) => <Animate>{row}</Animate>} />`

**Comment by jljsj33** [comment]
额。。。按你这需求，可以用 <TweenOneGroup enter={[{ duration: 0, x: '100%',  backgroundColor: '#fff000'}, { height: 0, type: 'from' , opacity: 0}, { x: 0 }, { delay: 3000, backgroundColor: 'transparent'}]} leave={{ x: '-100%', opacity: 0 }} />。。。

**Comment by jljsj33** [comment]
https://github.com/react-component/table/pull/57
