### ISSUE TITLE
Table onRow事件处理函数中，通过useState创建的hook变量不能刷新

### ISSUE THREAD

**Issue by bahborben** [ant-design/ant-design#22496]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/bahborben/antd-issue-demo](https://github.com/bahborben/antd-issue-demo)

### Steps to reproduce
* yarn start，在界面上显示一个表格，其中有两行数据，均处于未选中状态
* 按住ctrl键，鼠标点击第一行，该行变更为选中状态
* 按住ctrl键，鼠标再次点击第一行，该行仍然为选中状态
* 按住ctrl键，鼠标点击第二行，该行变更为选中状态，同时，第一行变更为未选中状态

在BaseTable中的Table组件上，将dataSource设置为从props中引入，则发生上述问题，但如果直接配置为常量数据，则可正常运行，如下：

```html
<Table
...
dataSource={[
        { id: 1, code: "P-01", name: "Panda" },
        { id: 2, code: "T-01", name: "Tiger" }
      ]}
/>
```

### What is expected?
在初始两条记录均未选中的状态下：
* 按住ctrl键，鼠标点击第一行，该行变更为选中状态
* 按住ctrl键，鼠标点击第二行，该行变更为选中状态，此时，两行均应为选中状态
* 按住ctrl键，鼠标再次点击第一行，该行应变更为未选中状态

### What is actually happening?
onRow下onClick的事件处理函数中，通过useState创建的hook变量不能刷新，永远是调用useState时赋予的初始状态

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.1 |
| System | fedora 31 |
| Browser | Chromium 80.0.3987.132 (Developer Build) Fedora Project (64-bit) |

**Comment by snoopy1412** [comment]
same question ,what can i do ?

**Comment by lucasleelz** [comment]
同~，看起来是rc-table内部没有做同步~ 导致`selectedRowKeys`异常。

**Comment by bahborben** [comment]
又尝试了一下通过 Class 方式实现Table的外部组件， 这种情况下，在onRow的onClick方法中， this 变量是 undefined

**Comment by snoopy1412** [comment]
> 又尝试了一下通过 Class 方式实现Table的外部组件， 这种情况下，在onRow的onClick方法中， this 变量是 undefined

发现可以用useRef 过度一下

**Comment by bahborben** [comment]
> > 又尝试了一下通过 Class 方式实现Table的外部组件， 这种情况下，在onRow的onClick方法中， this 变量是 undefined
> 
> 发现可以用useRef 过度一下

之前是把onRow作为component class的成员函数，无法在其中引用到this，现在把onRow及其内部调用的切换选择状态的函数都放在了render方法里，state和rowSelection状态正常了，但是显示选中状态的checkbox没有响应......

**Comment by zombieJ** [comment]
测了一下，最新的 Table 已经没有这个问题。可以删除 `yarn.lock` 重新安装一下。

**Comment by bahborben** [comment]
> 测了一下，最新的 Table 已经没有这个问题。可以删除 `yarn.lock` 重新安装一下。

用测试项目验证了，删除node_module目录, yarn.lock文件，确认package.json中ant-design版本为最新的4.1.1； 执行yarn install，而后yarn start启动。
问题仍然可以重现。

**Comment by StallionV** [comment]
English please

**Comment by crazyll** [comment]
用4.2.2版本同样遇到了这个问题，太坑了！

**Comment by zombieJ** [comment]
@crazyll  开个 issue 提供一下重现看看

**Comment by crazyll** [comment]
> @crazyll 开个 issue 提供一下重现看看

心累，本来用useRef避免了这个问题。但是遇到的两个页面不同步更新的变量不一样，也很纠结。结果写了个demo准备提issue发现我用的竟然不是最新版本，vscode versionlens 插件检测到的最新的是4.1.2，issue上最新的是4.2.5，发现之后升级了一下就没有这个问题了。

**Comment by yoyo837** [comment]
versionlens 延迟大 卸载了吧，直接npm 查询不更好？还有outdated 指令可以使用

**Comment by ZhouChilly** [comment]
4.9.4 版本这个问题又出现了
