### ISSUE TITLE
表单验证 validator  在obBlur 调取接口自定义验证  在点击提交时会重复验证两次  ，每次点提交都会验证两次调两次接口

### ISSUE THREAD

**Issue by i-jump** [ant-design/ant-design#22500]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
rule 自定义validator  异步调接口验证通过后  点击提交  无法提交 也不报错
`
 rules: [
        {
          required: true,
          message: '店铺为必填项',
        },
        {
          validator: async (rule, value) => {
            const res = await validatorName({name: value}); //调接口验证唯一
            if (res.result) {
              return Promise.resolve();
            }
            return Promise.reject("店铺名称已存在");
          },
        },
      ],
`

### What is expected?
1. 可以提交表单
2.提交表单验证一次即可 （现在是点击提交验证两次 调取两次接口）

### What is actually happening?
validator异步验证通过后，点击提交 验证两次，并且无法提交表单

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | react |
| System | 4.0.3 |
| Browser | google |

---
在pro-table中 操作表单自定义验证， 点击提交验证两次并且停留在提交业务 无报错反应

**Comment by xieyezi** [comment]
@i-jump  

你好，请问你解决这个问题了吗？我也遇到同样的问题了。`Form.Item `设置了自定义校验（调接口校验），触发时机为`OnBlur`,但是现在有一个bug:当我第一次在输入框输入值之后，直接点击提交按钮，会触发两次校验，调两次接口

**Comment by 07akioni** [comment]
https://github.com/ant-design/pro-components 可以去 protable 提一下 issue。
或者给一个发复现的 codesandbox 链接
