### ISSUE TITLE
pagination can not highlight current page,can not use next and previous button

### ISSUE THREAD

**Issue by justnull** [ant-design/ant-design#2250]
"antd": "^0.12.x",win7 x64,node:v6.2.1.chrome 51.

我期待的结果是：像官网一样正常显示 .http://codepen.io/youthterm/pen/KrqPaV?editors=1111

## 实际上的结果：
![qq 20160701175116](https://cloud.githubusercontent.com/assets/724861/16543494/3255da92-410a-11e6-8c30-cbaf1e930a45.png)
can not highlight current page,and can not use next and previous button.these two button can not work.
I can use other Function.
### 可重现的在线演示

http://codepen.io/youthterm/pen/KrqPaV?editors=1111.
我在codepen上的行为是正确的。
 a re-producible demo ： http://codepen.io/youthterm/pen/kXwXQQ

**Comment by benjycui** [comment]
<del>多喝热水，重启试试</del>

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
0.12.x 的例子：http://codepen.io/anon/pen/jAwArL?editors=1111

也是没有问题的哦~

**Comment by justnull** [comment]
@afc163 当第一次初始化pagination，total为0,current为1.第二次设置total为n,current为1(n>0).可以重现这个问题。

**Comment by afc163** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by justnull** [comment]
@afc163 http://codepen.io/youthterm/pen/akwmPB?editors=1111
input 2,and press Enter buttion.you can see a pagination without highlight current page.

**Comment by afc163** [comment]
http://codepen.io/anon/pen/xOAEZq?editors=1111

And press Enter won't trigger `onPageChange`.

**Comment by justnull** [comment]
@afc163 I not means `<button>`.I means Enter button on keyboard.

**Comment by afc163** [comment]
It is reasonable that when Pagination total is `0` (which make max page count is 0), the `page` of `onChange(page)` will be `0` too, which is always smaller than max page count.

**Comment by justnull** [comment]
yes,it was right in this example.but it still can't work in real project.
```
<Pagination showQuickJumper onChange={this.onCurChange}  total={110} current={this.state.cur} />
<Pagination showQuickJumper onChange={this.onPageChange}  total={this.state.total} current={this.state.current} />
```
`onCurChange` direct call `setState`. and  `onPageChange` use flux Framework(ajax) to call `setState`. `onCurChange` can work well. `onPageChange`  can not work.

**Comment by justnull** [comment]
@afc163  I understand the reason.maybe the typeof this.state.current it string.so it can't work.
