### ISSUE TITLE
table组件能否自定义row的内容

### ISSUE THREAD

**Issue by yesuanzao** [ant-design/ant-design#2251]
我现在有一些数据想要分组显示（隔几行显示一个特殊行），之前用到了table组件，但是只能定义columns，能否直接在row层级上做判断？

**Comment by benjycui** [comment]
`columns.render(text, record, index)` 提供的 3 个参数，足以判断现在是哪行了。

**Comment by yesuanzao** [comment]
@benjycui 这样虽可以，但要在每一列都判断一次，不是很方便

**Comment by djorkaeff** [comment]
@yesuanzao 估计你要的是这种组件的提供方式
http://www.material-ui.com/#/components/table

**Comment by yesuanzao** [comment]
@djorkaeff 是的，能够自定义tableRow非常灵活

**Comment by benjycui** [comment]
因为 material-ui 的 Table 比 antd 的裸。。。

**Comment by djorkaeff** [comment]
@benjycui 简洁性和开发效率上antd的table都要好些，但是细节控制以及与外部库的组合确实就非常依赖于你们提供的api了。可否考虑提供两套table的实现。一套快速开发，一套允许打磨细节和性能。

**Comment by djorkaeff** [comment]
#2249 和 ant motion的组合也会方便点

**Comment by afc163** [comment]
Usage 层面不做大的改造了，否则文档和维护成本会不可控，动画的问题到 #2249 继续讨论。
