### ISSUE TITLE
Form中使用Upload组件，上传完成后不更新状态

### ISSUE THREAD

**Issue by suunryo** [ant-design/ant-design#22515]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8ct82)

### Steps to reproduce
见代码
Form.Item中使用Upload，上传完成后Upload组件未更新状态
注释掉Form.Item的valuePropName和getValueFromEvent属性后，可以正常展示
使用了shouldUpdate，似乎没有效果（不知道这个api是不是这个作用）

### What is expected?
正确展示状态

### What is actually happening?
展示Uploading

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome 80 |

---
PS: Form.Item为什么不能嵌套自定义组件，尽管这个组件就是一个antd的表单

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/22322, please upgrade to `antd@4.0.4`.

https://codesandbox.io/s/antd-reproduction-template-orz2m
