### ISSUE TITLE
商用ant-图标（icon）是否有版权问题？

### ISSUE THREAD

**Issue by 7Charlotte** [ant-design/ant-design#22510]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我需要明确知道商用ant-图标（icon），即这个链接里提供的图标是否有侵权风险？（非iconfont） https://ant.design/components/icon-cn/

### What does the proposed API look like?
希望在demo里明确版权问题

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-icons/blob/master/LICENSE
