### ISSUE TITLE
能不能提供一个类似 Element-UI 的可视化主题配置工具？

### ISSUE THREAD

**Issue by ibufu** [ant-design/ant-design#22522]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的主题定制比较麻烦，要一个个得去试对应的变量。
这是 Element-UI 的[可视化工具](https://element.eleme.cn/#/zh-CN/theme/preview)，可以让设计师直接操作。

### What does the proposed API look like?
-

**Comment by afc163** [comment]
可以试试 https://antdtheme.com/ 需求可以提给 https://github.com/gzgogo/antd-theme/issues
