### ISSUE TITLE
Form中包含InputNumber

### ISSUE THREAD

**Issue by reiken** [ant-design/ant-design#22528]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
1.Form 嵌套InputNumber
2.在InputNumber随意输入数字
3.删除数字
4.按住InputNumber的增加按钮不松手

### What is expected?
数字累加

### What is actually happening?
数字并未累加

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16 |
| System | MAC OS |
| Browser | chrome 80.0.3987.149 |

**Comment by reiken** [comment]
直接在ant design官网form demo中有例子可以直接复现

**Comment by afc163** [comment]
![2020-03-23 22-34-40 2020-03-23 22_36_49](https://user-images.githubusercontent.com/507615/77327913-cd778a80-6d56-11ea-8996-db30e069a9e5.gif)

https://codesandbox.io/s/biaodanfangfadiaoyong-ant-design-demo-u6tcy

It works on form demo.

**Comment by reiken** [comment]
> ![2020-03-23 22-34-40 2020-03-23 22_36_49](https://user-images.githubusercontent.com/507615/77327913-cd778a80-6d56-11ea-8996-db30e069a9e5.gif)
> 
> https://codesandbox.io/s/biaodanfangfadiaoyong-ant-design-demo-u6tcy
> 
> It works on form demo.

先把inputNumber里的数字删除再随便输入一个数字，然后按住增加或缩小不要松手

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by Kermit-Xuan** [comment]
在`rc-input-number`发了个PR，[#248](https://github.com/react-component/input-number/pull/248)

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/input-number/pull/248
