### ISSUE TITLE
Force Update Content of Table

### ISSUE THREAD

**Issue by forwardref** [ant-design/ant-design#22520]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
E.g. you have a **`dataSource` with 20.000 items**. You **change the value of one item**=row in the `dataSource`. Since the array reference still equals, the **table does not rerender**. You would have to copy/create another array to force rerender, which can be costly for 20k rows.

Also tried setting `ref` and wanted to call `forceUpdate` on it, but it fails with "Function components cannot be given refs".

### What does the proposed API look like?
Maybe implement `forwardRef` in Table and make `tableRef.forceUpdate()` work?

**Comment by zombieJ** [comment]
You can add a `context` to make it happen. Data should be immutable.

**Comment by sevi221** [comment]
@zombieJ Could you give us an example, please?

**Comment by uguraktas** [comment]
> You can add a `context` to make it happen. Data should be immutable.

sorry, what exactly do you mean? Could you explain pls?

**Comment by dzekodev** [comment]
i need an example to get my hand arround it
