### ISSUE TITLE
[Component Upload]Make 'data' param can return a promise

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#22529]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At now, the `data` param we provide must be a **sync** function, so if I want to add some data asynchronously, the only way is doing something in `componentDidMount` and then call `setState` and then use that state as the data in the render function.

In #1840, the suggested way is to use `beforeUpload`, but from my test(maybe wrong), we can't do this too, here is my code:

```
function beforeUpload(file) {
  return new Promise(r => {
    file.data = { foo: 'bar' };

    r(file);
  });
}
```

The reason is that the Upload component will not use the `file.data` as the upload data param. In other words, the data param passed into Upload must be from the props(https://github.com/react-component/upload/blob/2bc60f4b576c9c5108c483f70ca43cae08aeadad/src/AjaxUploader.jsx#L116), so, whatever we do, we can't use an async way to change/pass the data(like `beforeUpload`), except the date param itself allows us to return a promise. If I'm wrong, please let me know, thanks.

### What does the proposed API look like?
Make `data` param can return a promise

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by Kermit-Xuan** [comment]
[#253](https://github.com/react-component/upload/pull/253) in `rc-upload`
