### ISSUE TITLE
Add & close tab poorly documented

### ISSUE THREAD

**Issue by JoeCMorgan** [ant-design/ant-design#22530]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001](https://codepen.io/pen/?&editable=true&editors=001)

### Steps to reproduce
There is no explanation of how to use the plus button, the 'add' function does not appear to be called from anywhere. Please update your documentation to explain this more clearly.

### What is expected?
Better documentation.

### What is actually happening?
Poor documentation.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.0 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://ant.design/components/tabs/#components-tabs-demo-editable-card

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/77326988-9359b900-6d55-11ea-95b5-6235aebb1c40.png">

Please reference source code of demo.
