### ISSUE TITLE
Ant Design Chat Component

### ISSUE THREAD

**Issue by a3596287** [ant-design/ant-design#22537]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Apart from the message component, would you support chat component? 

### What does the proposed API look like?
chat box

**Comment by afc163** [comment]
We may not have plan for a chat or conversation component, it would be a complicated component and hard to satisfy real situations.

You can try https://github.com/Wolox/react-chat-widget and https://github.com/Detaysoft/react-chat-elements

**Comment by hamzan32** [comment]
sdsdsdasd

**Comment by hamzan32** [comment]
> sdsdsdasd

cdf

**Comment by alexbadoi** [comment]
in the era of AI chat component is ++
