### ISSUE TITLE
npm latest version is incorrect

### ISSUE THREAD

**Issue by lc-leoniefarmer** [ant-design/ant-design#22539]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
navigate to react file in terminal. Run npm outdated command

### What is expected?
latest version should show 4.0.4

### What is actually happening?
latest version shows as 3.26.14

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | react |
| System | mac |
| Browser | not applicable |

**Comment by zombieJ** [comment]
Thanks for feedback. Updated.
