### ISSUE TITLE
Improve performance in Search Tree

### ISSUE THREAD

**Issue by giacomoronconiobda** [ant-design/ant-design#22534]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Filtering a Tree component with a lot of data (say thousand of nodes) freeze the browser

### What does the proposed API look like?
Same API different implementation

**Comment by afc163** [comment]
https://ant.design/components/tree/#components-tree-demo-virtual-scroll

**Comment by giacomoronconiobda** [comment]
The poor performance is rather on the searching than visualizing.

Il mar 24 mar 2020, 03:42 偏右 <notifications@github.com> ha scritto:

**Comment by iloveip** [comment]
I have the same problem. I have around 3000 nodes in the tree and the search becomes really slow. Virtual scroll doesn't help too much.
