### ISSUE TITLE
Cannot assign `align` to a v4 Table column  using TypeScript

### ISSUE THREAD

**Issue by zomars** [ant-design/ant-design#22535]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-v4-table-columns-issue-reproduction-template-3enh5)

### Steps to reproduce
Try to assign a `align` property to a column.

### What is expected?
No type errors.

### What is actually happening?
A type error:
```
Types of property 'align' are incompatible.
Type 'string' is not assignable to type 'AlignType'.
```

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.8.4 |
| System | macos 10.15.3 |
| Browser | Firefox 75 |

**Comment by afc163** [comment]
#21869

**Comment by zomars** [comment]
@afc163 thank you! A note on the docs would be useful.

**Comment by afc163** [comment]
https://ant.design/components/table/#Using-in-TypeScript

**Comment by zomars** [comment]
I totally missed that, thank you!

**Comment by afc163** [comment]
Another trick way is

```diff
- align: 'left',
+ align: 'left' as 'left',
```

**Comment by zomars** [comment]
Good to know! Thanks again! 🙏

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17281#issuecomment-505262460
