### ISSUE TITLE
 ant4图标问题，请问现在如何动态渲染图标啊？

### ISSUE THREAD

**Issue by zhuguangyue** [ant-design/ant-design#22542]
### 🐛 ant4图标问题，请问现在如何动态渲染图标啊？
ant3时图标不需要直接icon=“图标标签”，ant4后icon={图标组件}，而且需要import，那么当我需要后端获取图标值，前端渲染，import怎么解决？系统菜单图标等等
**ant3:**
` <Button type="primary" icon="search" htmlType="submit">查询</Button>`

**ant4**
`import {SearchOutlined } from '@ant-design/icons';
 <Button type="primary" icon={<SearchOutlined />} htmlType="submit">查询</Button>`

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/21729#issuecomment-593078457
#20668
