### ISSUE TITLE
Menu navigation menu suggest adding menu hover event

### ISSUE THREAD

**Issue by a88053443** [ant-design/ant-design#22543]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
例如鼠标放到菜单上展示收藏五角星，移出隐藏

For example, hover the mouse over the menu to display the collection of five-pointed stars, move out of hiding

### What does the proposed API look like?
```javascript
onHover: () => {}
```

**Comment by afc163** [comment]
Try `onMouseEnter` and `onMouseLeave`.
