### ISSUE TITLE
table中的filterDropdown属性能否提供下点击触发的事件

### ISSUE THREAD

**Issue by XUGAOBO** [ant-design/ant-design#2254]

**Comment by XUGAOBO** [comment]
我通过改变一个状态属性来控制显示和隐藏,个人认为得有个触发事件把,还是有更好的方法

**Comment by benjycui** [comment]
不清楚你的问题，`filterDropdown` 的显示和隐藏应该在 Table 内就处理掉了 https://github.com/ant-design/ant-design/blob/1.x-stable/components/table/filterDropdown.jsx#L150

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/3003
