### ISSUE TITLE
Cascader long-option-text style issue

### ISSUE THREAD

**Issue by woshiqiang1** [ant-design/ant-design#22549]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
make long text options display better

### What does the proposed API look like?
I add some css in the origin code
![_1BDFFC58-70F1-4449-894D-49D6FEF097A7__20200324125747.jpg](https://i.loli.net/2020/03/24/Yyb7GTvtVqsPpHg.jpg)

**Comment by afc163** [comment]
It is browser native tooltip, nothing we can do about it.
