### ISSUE TITLE
React state update on an unmounted component (Modal Form)

### ISSUE THREAD

**Issue by hjiawei** [ant-design/ant-design#22544]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/priceless-moon-lmyhm)

### Steps to reproduce
1. Start the codesandbox example
2. Click "Show Modal" button

### What is expected?
No warning message in the console.

### What is actually happening?
Console Warning: Can't perform a React state update on an unmounted component.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | codesandbox.io |
| Browser | Google Chrome 80.0.3987.149 (Official Build) (64-bit) |

---
I switched back to antd 4.0.3 and I didn't see the warning. I guess this is introduced in antd 4.0.4?

**Comment by afc163** [comment]
similar to #22531

**Comment by zelin-zx** [comment]
我也是这个问题,,请问解决了吗
