### ISSUE TITLE
404 page of ant-design's website https://ant.design/docs/react/introduce-cn1231 cover on Header Component?

### ISSUE THREAD

**Issue by HancockY** [ant-design/ant-design#22545]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce-cn1231](https://ant.design/docs/react/introduce-cn1231)

### Steps to reproduce
Get into 404 page above, then F12 and resize browser, zoom out browser the Header component will show up. 
进入404页面, 然后缩放浏览器, 选择一下组件, Header 部分就显示出来了. 我就是想知道如何在单页应用中显示全屏的404页, 并且不显示Header部分.
需要如何配置路由? 我看ant-design的官网好像是通过position: fixed做的, 覆盖Header? 
或者说拆分路由, 分成Home   404的外层路由, Home 里面是 Header   Content 部分.

### What is expected?
Do not show Header

### What is actually happening?
Header show up.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 4.0.4 |
| System | windows10 |
| Browser | chrome |

---
I just wonder how I can show 404 page full screen in a single page application with the Header disapear.

**Comment by HancockY** [comment]
![Uploading 微信截图_20200324105057.png…]()

**Comment by HancockY** [comment]
![微信截图_20200324105057](https://user-images.githubusercontent.com/19997073/77384984-d05b9500-6dc1-11ea-8ee9-b6bfe61799b6.png)

**Comment by afc163** [comment]
antd 官网是取巧的手段，不是好的方式，不要参考，正确的做法是在 404 页面设定独立的 layout。

**Comment by HancockY** [comment]
> antd 官网是取巧的手段，不是好的方式，不要参考，正确的做法是给 404 页面设定独立的 layout。

Thx
