### ISSUE TITLE
RangePicker使用open后希望第二次打开首先选择开始时间

### ISSUE THREAD

**Issue by xhw0714** [ant-design/ant-design#22550]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
隐藏选择框后使用open控制RangePicker无法选择开始时间。

### What does the proposed API look like?
RangePicker使用open后首先选择开始时间。

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by xhw0714** [comment]
https://codesandbox.io/s/antd-reproduction-template-w4u88?fontsize=14&hidenavigation=1&theme=dark

**Comment by xhw0714** [comment]
https://codesandbox.io/s/antd-reproduction-template-w4u88?fontsize=14&hidenavigation=1&theme=dark

**Comment by xhw0714** [comment]
https://codesandbox.io/s/antd-reproduction-template-w4u88?fontsize=14&hidenavigation=1&theme=dark
3.x就可以

**Comment by afc163** [comment]
不太理解你说的。

**Comment by xhw0714** [comment]
行吧。。那关闭吧

**Comment by xrkffgg** [comment]
4.0 的 `RangePicker` 把 开始时间和 结束时间分开了，如果你不隐藏，你就会看到。

- 当你选择完开始的时间后，焦点会自动滑到 结束时间
- 当你再次 open 的时候，焦点还是结束的
- 如果要选择开始的世界，就需要点击开始的框才行

**Comment by xhw0714** [comment]
> 4.0 的 `RangePicker` 把 开始时间和 结束时间分开了，如果你不隐藏，你就会看到。
> 
> * 当你选择完开始的时间后，焦点会自动滑到 结束时间
> * 当你再次 open 的时候，焦点还是结束的
> * 如果要选择开始的时间，就需要点击开始的框才行

那有没有方法可以隐藏的时候滑到开始时间？

**Comment by xrkffgg** [comment]
可以试试 在你点击的时候，清空 value 的值

**Comment by xhw0714** [comment]
> 可以试试 在你点击的时候，清空 value 的值

还是不行

**Comment by xrkffgg** [comment]
有没有可能在你点击的时候，New一个RangePicker
