### ISSUE TITLE
TreeSelect doesn't show the title.

### ISSUE THREAD

**Issue by itellboy** [ant-design/ant-design#22553]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rough-monad-v6kpq)

### Steps to reproduce
Delay set the treeData value

### What is expected?
It can show the title related with the value. And it could work at 3.x.

[https://codesandbox.io/s/eloquent-thunder-0tpdu](https://codesandbox.io/s/eloquent-thunder-0tpdu)

### What is actually happening?
It shows the value directly.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | latest |
| System | macOS 10.15.2 |
| Browser | Chrome latest |

**Comment by zlyyyy** [comment]
我也遇到了。。。我还以为我写的有问题

**Comment by ZhaoXinNian** [comment]
好巧我也遇到了， 我的情况是这样

**Comment by WinterWoods** [comment]
什么时候能修复
