### ISSUE TITLE
Badge: Rtl issue with two digit 

### ISSUE THREAD

**Issue by saeedrahimi** [ant-design/ant-design#22555]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdesign-badge-rtl-issue-two-digit-cz980)

### Steps to reproduce
go to this badge demo: https://ant.design/components/badge/#components-badge-demo-change
switch to rtl direction.
try to increase badge counter above 9.

### What is expected?
expected to show `10`.

### What is actually happening?
shows `01`

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | latest |
| System | latest |
| Browser | Brave 1.4 |

**Comment by xrkffgg** [comment]
Hi, if you're not going to fix it yet, let me do it, OK?
