### ISSUE TITLE
Unknown event handler property `onFinish`

### ISSUE THREAD

**Issue by a3596287** [ant-design/ant-design#22556]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-06hdf)

### Steps to reproduce
Render the above code from App.js or Index.js

### What is expected?
expecting the error appears

### What is actually happening?
no error message comes up, in the console, I can see onFinish is unknow event.

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
If you are using antd 3.x, please check https://3x.ant.design/

**Comment by momenfc** [comment]
remove "validateTrigger" form prop
