### ISSUE TITLE
form组件中 validateFieldsAndScroll函数没有让校验失败的元素滚动到屏幕中间，而是滚动到底部

### ISSUE THREAD

**Issue by lianpen** [ant-design/ant-design#2255]
### 本地环境

- antd 版本:1.6.3
- 操作系统及其版本：win7
- 浏览器及其版本:chrome

### 你期待的结果是：

让校验失败的元素滚动到屏幕中间

## 实际上的结果：

校验失败的元素位置在屏幕底部

**Comment by ddcat1115** [comment]
`validateFieldsAndScroll` 会将不在可见区域的校验失败的表单项滚进可见区，位置不一定，一般是在顶部或底部。

**Comment by lianpen** [comment]
我想让它出现在中间最显眼的位置，我应该怎么做？

**Comment by ddcat1115** [comment]
可以设置 offset，参照 http://react-component.github.io/form/examples/radio-group.html

**Comment by lianpen** [comment]
thank you
我用offsetBottom可以解决问题
