### ISSUE TITLE
Failed to provide children property to ColumnProps in TypeScript

### ISSUE THREAD

**Issue by ZekeLu** [ant-design/ant-design#22554]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-frog-6j2yd)

### Steps to reproduce
check the file `src/App.tsx`, there is a compiler error on line 14:

```
Type '{ title: string; dataIndex: string; }[]' is not assignable to type 'null | undefined'.
  Type '{ title: string; dataIndex: string; }[]' is not assignable to type 'null'
```

### What is expected?
the `children` property should be supported.

### What is actually happening?
Failed to provide `children` property to `ColumnProps` in TypeScript

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.0 |
| System | Win 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
It may be related to #21414

@zombieJ come and check it.

**Comment by zombieJ** [comment]
Use `ColumnsType` instead of `ColumnProps`. `ColumnProps` is just for Column component usage.

**Comment by ZekeLu** [comment]
Thank you very much!

In my case, I use `ColumnGroupType` and it works!
