### ISSUE TITLE
Freeze browser on big search trees

### ISSUE THREAD

**Issue by giacomoronconiobda** [ant-design/ant-design#22559]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-mplkp?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Search for a number in the Input Search

### What is expected?
Filter tree

### What is actually happening?
Very slow, freezeing

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.0 |
| System | Ubuntu 18.04.4 LTS |
| Browser | Chrome 80.0.3987.122 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
It's a demo for search tree. You should additional work on the `onChange` of demo to optimize `expandedKeys` logic.
