### ISSUE TITLE
height of block with <Text ellipsis /> inside

### ISSUE THREAD

**Issue by slavakam** [ant-design/ant-design#22565]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/text-component-ant-design-demo-z9wxe)

### Steps to reproduce
add <Text ellipsis /> element to any block items

### What is expected?
in the example, we expected that the second block(with Text.ellipsis) will be with the same height as the first block(with Text without ellipsis inside div)

### What is actually happening?
the second block(with Text.ellipsis) has more height than the first block(with Text without ellipsis inside div)

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | your current version |
| System | all |
| Browser | all |

**Comment by zombieJ** [comment]
`Text` is a `inline-block` element. It means you should set width of it if you need `ellipsis` work:
https://codesandbox.io/s/text-component-ant-design-demo-gbfds

**Comment by slavakam** [comment]
> `Text` is a `inline-block` element. It means you should set width of it if you need `ellipsis` work:
> https://codesandbox.io/s/text-component-ant-design-demo-gbfds
this issue not about 3dots this issue about the height of gray block

**Comment by slavakam** [comment]
> `Text` is a `inline-block` element. It means you should set width of it if you need `ellipsis` work:
> https://codesandbox.io/s/text-component-ant-design-demo-gbfds

this issue not about 3dots this issue about the height of gray block
