### ISSUE TITLE
建议 TimePicker 不显示秒时显示成 14:11:--

### ISSUE THREAD

**Issue by wuzhao** [ant-design/ant-design#2256]
现在 TimePicker 可以选择显示的 format，比如 format 为 HH:mm 时，秒直接不显示，标示为 14:11。

这种情况下，如果没有日期，看起来更像是 14分11秒，建议显示为 14:11:--，用 -- 代替缺失的时间维度。

![image](https://cloud.githubusercontent.com/assets/712075/16552559/9719c552-41f4-11e6-9c83-05ea571309b1.png)

**Comment by afc163** [comment]
format 可以自行设置的吧？

**Comment by wuzhao** [comment]
format 如果设置成 14:11:-- 不行的，因为这个属性最重会用来处理事件，除非增加一个 custom 相关字段。

```
import 'antd/dist/antd.css';
import { TimePicker } from 'antd';

ReactDOM.render(
  <TimePicker defaultValue="12:08:23" format="HH:mm:--" />
, mountNode);
```

**Comment by afc163** [comment]
http://codepen.io/anon/pen/bZRwvm?editors=0010

这样可以么？

**Comment by wuzhao** [comment]
可以！
