### ISSUE TITLE
Form inline模式 Input allowClear 宽度闪烁

### ISSUE THREAD

**Issue by zlab** [ant-design/ant-design#22562]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daiyichutubiao-ant-design-demo-0q1us)

### Steps to reproduce
输入任意字符

### What is expected?
宽度不变

### What is actually happening?
input宽度会增加清除小图标的宽度

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.13 |
| System | mac13 |
| Browser | chrome 80 |

**Comment by shaodahong** [comment]
不是 Form 的问题，4.0 Input 的 suffix 不是 `absolute` 了，所以造成图标出现宽度增加

https://codesandbox.io/s/daiyichutubiao-ant-design-demo-0ohnm

@zombieJ 帮忙看下这个

**Comment by zombieJ** [comment]
嗯，感觉应该固定一下 suffix 。

**Comment by zlab** [comment]
这什么图。。。
