### ISSUE TITLE
move @form-item-label-height to global variables

### ISSUE THREAD

**Issue by slavakam** [ant-design/ant-design#22568]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
we don’t need to reassign styles every time using Form.Item component

### What does the proposed API look like?
@form-item-label-height: @input-height-base;

**Comment by zombieJ** [comment]
Could you provides usage case about this? Since form item label height should follow input height base.

**Comment by slavakam** [comment]
https://codesandbox.io/s/basic-usage-ant-design-demo-xbq9t

I opened the issue https://github.com/ant-design/ant-design/issues/21874. It would be better if you will move @form-item-label-height to global ant variables

**Comment by afc163** [comment]
PR welcome
