### ISSUE TITLE
InputNumber in Form.item with name is not showing default value

### ISSUE THREAD

**Issue by JumpAttacker** [ant-design/ant-design#22570]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-j5hp1q?file=index.js](https://stackblitz.com/edit/react-j5hp1q?file=index.js)

### Steps to reproduce
with name prop in Form.Item def value is not showing, without all working fine

### What is expected?
want to see default value

### What is actually happening?
cant see default value

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | react@16.13.1 |
| System | win10 |
| Browser | 80.0.3987.132 |

**Comment by zombieJ** [comment]
too many issue for `defaultValue`. We should add warning if user set `defaultValue` for Form.Item, it's controlled mode accurately.
