### ISSUE TITLE
安装Ant之后，运行自己配置的webpack非常慢

### ISSUE THREAD

**Issue by llh520xw** [ant-design/ant-design#2257]
### 本地环境
var path = require('path'),
    node_modules = path.resolve(__dirname, 'node_modules'),
    pathReact = path.resolve(node_modules, 'react/dist/react.min.js'),
    pathReactDom = path.resolve(node_modules, 'react-dom/dist/react-dom.min.js');

var config = {
    devtool: 'inline-source-map',
    entry: ['webpack/hot/dev-server', path.resolve(__dirname, 'Learn/examples/main.jsx')],
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'bundle.js'
    },
    module: {
        loaders: [{
            test: /\.jsx?$/, // 用正则来匹配文件路径，这段意思是匹配 js 或者 jsx
            loader: 'babel',
            query: {
                presets: ['react', 'es2015'],
                plugins: ["transform-class-properties"]
            }
        }, {
            test: /\.less$/,
            loader: 'style!css!less'
        }, {
            test: /\.(jpg|png)$/,
            loader: 'url?limit=25000'
        }],
        noParse: [pathReact, pathReactDom],
        plugins: ['antd', {
            style: 'css'
        }]
    }
};

module.exports = config;

{
  "name": "leilihuang",
  "version": "1.0.0",
  "description": "",
  "main": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build": "wepack",
    "dev": "webpack-dev-server --devtool eval --progress --colors --hot --content-base build",
    "kaifa": "webpack-dev-server --devtool cheap-module-eval-source-map --progress --colors --hot --content-base build"
  },
  "author": "leilihuang",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.9.1",
    "babel-loader": "^6.2.4",
    "babel-plugin-antd": "^0.4.0",
    "babel-plugin-transform-class-properties": "^6.9.1",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "file-loader": "^0.8.5",
    "react": "^15.1.0",
    "react-dom": "^15.1.0",
    "react-router": "^2.4.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.13.1"
  },
  "dependencies": {
    "antd": "^1.0.0-beta.10",
    "css-loader": "^0.23.1",
    "less": "^2.7.1",
    "less-loader": "^2.2.3",
    "npm": "^3.9.5",
    "style-loader": "^0.13.1",
    "webpack-dev-server": "^1.14.1"
  }
}
- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

### 你做了什么？
npm run dev热启动项目

### 你期待的结果是：
正常运行

## 实际上的结果：
运行很慢

**Comment by afc163** [comment]
http://eternalsky.me/ru-he-10-bei-ti-gao-ni-de-webpack-gou-jian-xiao-lu/

**Comment by jzlxiaohei** [comment]
上面的文章涵盖了很多内容，非常全

按照我的实验，简单的设置两个地方，开发时的速度就会快很多（当然启动的时间还是一样的慢...

`babel-loader` 的`cacheDirectory`设为`true`,
`config.cache`设为`true`

**Comment by llh520xw** [comment]
谢谢，我试试
