### ISSUE TITLE
Select multi-step option

### ISSUE THREAD

**Issue by philcon93** [ant-design/ant-design#22585]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We wish to have a multi-step select input where the select options helps start the user off, and then they finish it off with some custom text.

We use the select options for the 'key' of a query, and have the user fill out the 'value'. As an example, we have an option 'id:', which the user then needs to fill in the 'key', e.g 'id:n1002'. This key/value pair is needed so we can later figure out which filter needs to be added to the API query, e.g order id, customer name, order status etc. A very good example of this working is the Stripe dashboard - https://dashboard.stripe.com/dashboard.

Here is an example of the flow:

- https://codesandbox.io/s/select-multi-step-ant-design-demo-8ibr6

We can't use the AutoComplete component because it is a single value component, while the Select component allows multiple values, and the tags mode is best suited.

If we could have a way to make it when the user selects the option, it updates the text input value (Not the select components value, which are the tags), then on the enter key or some programmable way, it adds its to the selects value. Or even a programmable way to update the text input value, so we could update its value instead of updating the selects value which are already uneditable tags.

### What does the proposed API look like?
Could have a queryValue and onSubmit for the text input:

```
<Select
    queryValue='status:'
    onSubmit=(value => {
        setSelectedItems(value);
        clearQuery();
    })
    value={selectedItems}
    mode='tags'/>
```

**Comment by zombieJ** [comment]
It's too specific that may not apply to antd side. You should extends `onSearch` to customize this requirement:
https://codesandbox.io/s/duoxuan-ant-design-demo-06fuq

**Comment by zombieJ** [comment]
It's too specific that may not apply to antd side. You should extends `onSearch` to customize this requirement:
https://codesandbox.io/s/duoxuan-ant-design-demo-06fuq

**Comment by philcon93** [comment]
Thanks for the reply :), can confirm this isn't an adequate component for us. Time to try the actual component behind this, it looks like you can edit it's text input component:

- https://react-select.com/components
