### ISSUE TITLE
Select in RTL drop-down location

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#22580]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fangxiang-ant-design-demo-jhqkk)

### Steps to reproduce
- Open link
- Select LTR, click, the drop-down is close to the left
- Select RTL, click, the drop-down is still close to the left

### What is expected?
- In RTL, the drop-down is close to the right

### What is actually happening?
- In RTL, the drop-down is close to the left

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by xrkffgg** [comment]
- https://ant.design/components/cascader-cn/
Like the drop down in Cascader.

**Comment by saeedrahimi** [comment]
It could be handled with a simple gird.
https://codesandbox.io/s/fangxiang-ant-design-demo-dyd5k

**Comment by xrkffgg** [comment]
<img width="538" alt="WeChat5c2cf11b98a4c007cb84caab62e739d4" src="https://user-images.githubusercontent.com/29775873/77518286-7ab5e400-6eb8-11ea-858a-4d543aa87860.png">

I mean, the position of the drop-down should not be in red box, but in blue box.

**Comment by xrkffgg** [comment]
https://github.com/react-component/select/pull/471
