### ISSUE TITLE
4.0版本Grid不支持ie11

### ISSUE THREAD

**Issue by chjish28461** [ant-design/ant-design#22587]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://172.16.225.174/index.html](http://172.16.225.174/index.html)

### Steps to reproduce
Grid使用默认flex布局，但是不支持ie11

### What is expected?
支持ie11

### What is actually happening?
不支持

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.2.1 |
| System | windows7 |
| Browser | ie11 |

**Comment by afc163** [comment]
https://caniuse.com/#feat=flexbox
