### ISSUE TITLE
组件在 react@15.2.0 下报  Unknown props 警告

### ISSUE THREAD

**Issue by jzlxiaohei** [ant-design/ant-design#2258]
### 本地环境

- antd 版本: ^1.6.3
- 操作系统及其版本：mac os
- 浏览器及其版本: chrome

### 你做了什么？

按照官网例子，使用了导航栏 `Menu`
### 你期待的结果是：

console上没有`waring`
## 实际上的结果：

```
vendor.dll.js:3141Warning: Unknown props `tag`, `hiddenClassName`, `visible` on <ul> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in ul (created by DOMWrap)
    in DOMWrap (created by Menu)
    in Menu (created by Menu)
    in Menu (created by Layout)
    in nav (created by Layout)
    in div (created by Layout)
    in Layout (created by RouterContext)
    in RouterContext (created by Router)
    in Router
```

### 原因
DOMWrap 中，直接通过{...props}把属性全赋值到了`Tag`,`Tag`是`ul`时，tag`, `hiddenClassName`, `visible`是非法的属性。 [源码地址](https://github.com/react-component/menu/blob/master/src/DOMWrap.jsx#L22)

不过production环境，不报警告（ `   new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('production')
    })`+  `uglify`  ）

**Comment by RaoHai** [comment]
https://github.com/ant-design/ant-design/issues/2253

React 15.2.x 之后蹦出来的。已经发现了。。

**Comment by jzlxiaohei** [comment]
@RaoHai
恩，我自己写的一些东西，也有报错。基本同意处理下面这样
```
  const others = _.omit(this.props, 'option', 'notMerge', 'notRefreshImmediately'');
  return <div {others}/>
```
全fix掉，还是很烦的

**Comment by jzlxiaohei** [comment]
看了相关issue的修复，是浅层clone props(`var newProps  = {...this.props}`)，然后delete掉不应该传入的属性名。
感觉_.omit会更好些

**Comment by afc163** [comment]
这个需要 antd 和底层 rc 组件统一改一遍，在此之前，可以先保持 `react@15.1.0`。

**Comment by uinika** [comment]
请问，你们计划在哪个版本对该bug进行修复？

**Comment by Yhaojing** [comment]
具体是怎么操作的，比如说我使用<Spin/>报错warning.js?3efc:44Warning: Unknown prop `spinning` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Spin)
    in Spin (created by LoadingPage)
    in LoadingPage (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App) (created by RouterContext)
    in div (created by TodoApp)
    in TodoApp (created by RouterContext)
    in RouterContext (created by Router)
    in Router
    in Provider

我应该怎么改？？还是明白呀

**Comment by afc163** [comment]
- [ ] Form
- [ ] Menu
- [ ] InputNumber
- [ ] Select
- [ ] Transfer
- [ ] TreeSelect
- [ ] Badge
- [ ] Spin
- [ ] Tag
- [ ] Tree
- [ ] Steps
- [ ] Tabs
- [ ] BackTop
- [ ] QueueAnim

**Comment by ubuntugx** [comment]
@ddcat1115 Popover 里放 div 会报 warning。
代码：
```html
<Popover content={content} placement="bottomRight" trigger="click">
    <div className={style.navItem}><a className={style.navLink}>三个点</a></div>
</Popover>
```
warning：
```
warning.js?85a7:44 Warning: Unknown prop `visible` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by LazyRenderBox)
    in LazyRenderBox (created by PopupInner)
    in div (created by PopupInner)
    in PopupInner (created by Popup)
    in Align (created by Popup)
    in AnimateChild (created by Animate)
    in Animate (created by Popup)
    in div (created by Popup)
    in Popup
```
antd 版本： 1.6.3
React 版本：15.0.1
浏览器：Chrome  51.0.2704.103

**Comment by ddcat1115** [comment]
@ubuntugx 更新到 1.6.4 试试，应该没有问题了

**Comment by clarkhan** [comment]
今天尝试升级了一下，仍有提示。暂时还没细究，先回滚了，难道和使用有关？

+-- antd@1.6.4
| +-- array-tree-filter@1.0.0
| +-- classnames@2.2.5
| +-- css-animation@1.2.5
| | `-- component-classes@1.2.6
| |   `-- component-indexof@0.0.3
| +-- gregorian-calendar@4.1.4
| +-- gregorian-calendar-format@4.1.3
| | `-- warning@2.1.0
| +-- object.omit@2.0.0
| | +-- for-own@0.1.4
| | | `-- for-in@0.1.5
| | `-- is-extendable@0.1.1
| +-- rc-animate@2.3.0
| +-- rc-calendar@5.6.2
| +-- rc-cascader@0.9.11
| +-- rc-checkbox@1.4.0
| +-- rc-collapse@1.6.3
| | `-- rc-animate@2.1.0
| +-- rc-dialog@6.1.1
| +-- rc-dropdown@1.4.8
| +-- rc-form@0.17.1
| | `-- dom-scroll-into-view@1.2.0
| +-- rc-input-number@2.5.13
| +-- rc-menu@4.12.4
| +-- rc-notification@1.3.4
| +-- rc-pagination@1.5.3
| +-- rc-progress@1.0.4
| +-- rc-queue-anim@0.11.12
| | `-- velocity-animate@1.2.3
| |   `-- jquery@3.1.0
| +-- rc-radio@2.0.0
| +-- rc-rate@1.1.2
| +-- rc-select@6.4.6
| | `-- warning@2.1.0
| +-- rc-slider@3.7.3
| | `-- warning@2.1.0
| +-- rc-steps@2.1.5
| +-- rc-switch@1.4.2
| +-- rc-table@4.3.5
| | `-- object-path@0.9.2
| +-- rc-tabs@5.9.2
| +-- rc-time-picker@1.1.5
| +-- rc-tooltip@3.4.2
| +-- rc-tree@1.3.6
| +-- rc-tree-select@1.7.6
| +-- rc-upload@1.13.3
| | `-- warning@2.1.0
| +-- rc-util@3.1.3
| | +-- add-dom-event-listener@1.0.1
| | +-- shallowequal@0.2.2
| | | `-- lodash.keys@3.1.2
| | |   +-- lodash._getnative@3.9.1
| | |   +-- lodash.isarguments@3.0.8
| | |   `-- lodash.isarray@3.0.4
| | `-- util-deprecate@1.0.2
| +-- react-addons-pure-render-mixin@15.2.1
| +-- react-slick@0.12.2
| | +-- json2mq@0.2.0
| | | `-- string-convert@0.2.1
| | +-- object-assign@2.1.1
| | +-- react-responsive-mixin@0.3.5
| | | +-- can-use-dom@0.1.0
| | | `-- enquire.js@2.1.1
| | `-- slick-carousel@1.6.0
| `-- warning@3.0.0
+-- react@15.2.1
| `-- fbjs@0.8.3
|   +-- core-js@1.2.6
|   `-- ua-parser-js@0.7.10
+-- react-dom@15.2.1


![2016-07-09_170217](https://cloud.githubusercontent.com/assets/3722265/16707166/59cf8288-45f8-11e6-995b-e004e046201a.png)
![2016-07-09_170256](https://cloud.githubusercontent.com/assets/3722265/16707173/5f7e7202-45f8-11e6-9f8d-58c23a000a18.png)
![2016-07-09_170339](https://cloud.githubusercontent.com/assets/3722265/16707175/62e3dc84-45f8-11e6-8d29-dfe22c735288.png)

**Comment by afc163** [comment]
没有重现，确保本地安装 rc-animation 是 2.3.0+ 版本的。

**Comment by clarkhan** [comment]
果然，之前 rc-collapse 依赖的 rc-animate@2.1.0，指定版本升级之后就 OK 了。谢谢！

**Comment by cagen** [comment]
请问一下，我在Cascader中使用了getPopupContainer属性，还是会产生这个Warning
`Warning: Unknown prop `getPopupContainer` on <input> tag.`

是我这边版本的问题么？我的rc-cascader版本 `rc-cascader@0.9.11 (rc-trigger@1.6.3)`

**Comment by cagen** [comment]
好像Select组件上的tags属性也会报错：
`Warning: Unknown prop `tags` on <input> tag.`

antd版本 `antd@1.6.4`
rc-select版本 `rc-select@6.4.6`

**Comment by jc920699638** [comment]
Unknown prop `xl` on <div> tag. Remove this prop from the element. For details 这是个什么情况 栅格的xl报错 其他md lg sm 都不会出现这个问题??

**Comment by bnerDY** [comment]
在react ^15.6.1 版本上的Spin 还有这个问题

**Comment by benjycui** [comment]
> 在react ^15.6.1 版本上的Spin 还有这个问题

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
