### ISSUE TITLE
子节点全部取消后，oncheck的halfCheckedKeys里返回的值为未删除

### ISSUE THREAD

**Issue by yuanweisuannai** [ant-design/ant-design#22589]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
勾选子节点，然后取消子节点

### What is expected?
如果子节点全部取消之后，半选的数组里应该不返回数据

### What is actually happening?
子节点全部取消之后，半选的数组里还是返回父节点的数据

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome80.0.3987.149 |

**Comment by xushengs** [comment]
这个可以看到，子节点全部取消后，父节点状态并未改变：[https://codesandbox.io/s/jiben-ant-design-demo-ryx6n]()

**Comment by xushengs** [comment]
> Hello @yuanweisuannai. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @yuanweisuannai, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

已更新

**Comment by zombieJ** [comment]
设置 `halfCheckedKeys` 空数组会 block checkedKeys 更新，比较神奇。
```jsx
halfCheckedKeys={[]}
```
要看看为什么。

**Comment by zombieJ** [comment]
找到原因了，`halfCheckedKeys` 不是 Tree 的属性。但是被更新逻辑命中了。
