### ISSUE TITLE
把Table通过一个Class 封装放到Modal中之后表头错乱

### ISSUE THREAD

**Issue by davidcun** [ant-design/ant-design#22592]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-69zzo)

### Steps to reproduce
1、点击展示
2、表头是错乱的
3、注意，只有第一次点击会出现问题，Modal退出再打开就没有问题

备注（以下方式是没有问题的）：
1、第一种：通过forceUpdate可以解决，但是不太想用此方式
2、第二种：去掉中间的Modal，把ModalDemo中的Modal直接放在TableDemo里面，DemoController直接引用TableModal，也没问题
3、第三种：在TableModal里面的延迟加载数据时间为500，也没有问题

### What is expected?
表头展示正确

### What is actually happening?
表头展示错误

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.0 |
| System | mac os |
| Browser | chrome  lastest |

---
备注（一下方式是没有问题的）：
1、第一种：通过forceUpdate可以解决，但是不太想用此方式
2、第二种：去掉中间的Modal，把ModalDemo中的Modal直接放在TableDemo里面，DemoController直接引用TableModal，也没问题
3、第三种：在TableModal里面的延迟加载数据时间为500，也没有问题

**Comment by zombieJ** [comment]
`rc-resize-observer` 用的 getBoundingClientRect，动画的时候还在缩放。需要拓展一下 `rc-resize-observer`。
