### ISSUE TITLE
horizontal menu 情况下，submenu-pop 不消失问题

### ISSUE THREAD

**Issue by changegt** [ant-design/ant-design#22598]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7h8ry)

### Steps to reproduce
配置 defaultOpenKeys

### What is expected?
一段时间后关闭

### What is actually happening?
pop不关闭

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | 16.8.6 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
> 一段时间后关闭

不可能一段时间后关闭的，你配置了默认打开那就是打开的状态，除非用户介入进行交互。
