### ISSUE TITLE
Problems to insert image in the table.

### ISSUE THREAD

**Issue by lucassdr** [ant-design/ant-design#22608]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/lucassdr/covid19-dashboard](https://github.com/lucassdr/covid19-dashboard)

### Steps to reproduce
Not applicable.

### What is expected?
Display each image for each data node.

### What is actually happening?
No image information is displayed.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 4.0.3 |
| System | MacOS |
| Browser | Chrome |

---
I have a list with several cities and each city has a unique flag. I would like to know how I can place each unique image to be displayed in the table. I can't find that use anywhere and I hope to find it in that space.

**Comment by lucassdr** [comment]
I found the solution, walking with my own legs, that is, alone. haha ha.

Below the solution. Yes, it was easy, but the documentation does not show any example that would easily fit. (Ohh ... no!).

`{
        title: '',
        dataIndex: 'flag',
        key: 'flag',
        render: flag => (
            <img src={`${flag}`} style={{ height: '10%' }} />
        ),
        width: '15%',
},`

Keep going always!

**Comment by muhriddin-x** [comment]
thanks, your answer helped me
