### ISSUE TITLE
[4.0] onFieldsChange incorrect validation error

### ISSUE THREAD

**Issue by mikeyshing88** [ant-design/ant-design#22605]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-sky-8313f)

### Steps to reproduce
Decrease the input field counter to below 10 and check the console.

You will see the following 3 console logs:

1) field data with no errors
2) an empty value
3) field data with expected error

### What is expected?
The validation rule error should be present on the first render.

### What is actually happening?
The validation rule error should be is not in the first render, but appears on the following render.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | Latest |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
InputNumber `onChange` returns string in some situation due to `formatter` usage or `-10` input duration, please drop `type: 'number'` in rules and using `min` and `max` props in InputNumber.

https://codesandbox.io/s/silly-bartik-z8iv3

**Comment by mikeyshing88** [comment]
Doing that would then not generate the error message if a user inputs an invalid value.

The same issue appears with simply using `Input` and setting the form item as `required` - https://codesandbox.io/s/recursing-ishizaka-osty0 (just delete the initial value in the input field)
