### ISSUE TITLE
Double click also executes the single click event

### ISSUE THREAD

**Issue by oasmat83** [ant-design/ant-design#22602]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost](http://localhost)

### Steps to reproduce
I'm using your Table component I've set an onRow attribute with a "onDoubleClick" and "onClick" event. When I execute a "onDoubleClick" the event fires both the "onClick" and the "onDoubleClick" functions. Shouldn't it just execute the "onDoubleClick" function?

### What is expected?
"onDoubleClick" should just fire up the "onDoubleClick" function.

### What is actually happening?
Both functions are executed

| Environment | Info |
|---|---|
| antd | 3.24.0 |
| React | 16.13 |
| System | Windows 10 |
| Browser | Chrome Version 80.0.3987.132 (Official Build) (64-bit) |

---
no external url is available.

**Comment by zombieJ** [comment]
It's React behavior. We can do nothing about this.

https://codesandbox.io/s/agitated-glade-0cddm

**Comment by hungryzzz** [comment]
I also encountered the same problem, how did you solve it?

**Comment by JuanFLZ** [comment]
I had the same problem and found a solution using a timeout:

` let singleClickTimer: any;
  let firstClickEvent = false;

 const oneClickHandler = (item: any) => {
    if (!firstClickEvent) {
      firstClickEvent = true;
      singleClickTimer = setTimeout(() => {
        // some stuff
        firstClickEvent = false;
      }, 300);
    }
  };

  const doubleClickHandler = (item: any) => {
    clearTimeout(singleClickTimer);
    // some stuff
    firstClickEvent = false;
  };

return (
<Table
                dataSource={dataSource}
                columns={columns}
                onRow={(record, rowIndex) => {
                  return {
                    onClick: (event) => {
                      oneClickHandler(record);
                    }, // click row
                    onDoubleClick: (event) => {
                      doubleClickHandler(record);
                    }, // double click row
                  };
                }}
              />
)`
