### ISSUE TITLE
不懂这么多警告是啥意思。。。

### ISSUE THREAD

**Issue by helloCheng09** [ant-design/ant-design#22604]
![image](https://user-images.githubusercontent.com/41097785/77564491-c76fde00-6efd-11ea-8362-0dbe781f4e0b.png)

**Comment by afc163** [comment]
https://github.com/facebook/create-react-app/releases/tag/v3.4.1 开始默认开启 `React.StrictMode`，这种反馈会越来越多。

#22493
#9870

**Comment by helloCheng09** [comment]
Thank you bro!At first I thought you wanted me to open the strict mode, the original is to let me delete the strict mode!Haha, there is no warning after deleting this tag, you can happily use antd~ thank you for your hard development!

![image](https://user-images.githubusercontent.com/41097785/77608113-3decfa00-6f57-11ea-9dae-bdc0f14d2ad2.png)

**Comment by helloCheng09** [comment]
> https://github.com/facebook/create-react-app/releases/tag/v3.4.1 开始默认开启 `React.StrictMode`，这种反馈会越来越多。
> 
> #22493
> #9870
Thank you bro!At first I thought you wanted me to open the strict mode, the original is to let me delete the strict mode!Haha, there is no warning after deleting this tag, you can happily use antd~ thank you for your hard development!
![image](https://user-images.githubusercontent.com/41097785/77608123-46ddcb80-6f57-11ea-9e9a-73077d1abecb.png)

**Comment by ok2fly** [comment]
请问 楼主是怎么 解决 开发者模式下 按需加载 组件 控制台报错的

**Comment by helloCheng09** [comment]
> 请问 楼主是怎么 解决 开发者模式下 按需加载 组件 控制台报错的

是一样的报错吗？一样的报错删除index.js的React.StrictMode标签就可以了
https://blog.csdn.net/weixin_44544388/article/details/105115366

**Comment by ok2fly** [comment]
> https://blog.csdn.net/weixin_44544388/article/details/105115366

是一样的报错， 
谢谢 @helloCheng09  你给出的链接解决了我的问题，这个问题让我郁闷4天，
