### ISSUE TITLE
transfer搜索时没对特殊字符做处理

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2260]
### 本地环境

- antd 版本: 1.6.2
- 操作系统及其版本：Ubuntu 16.04 (64-bit)
- 浏览器及其版本: 51.0.2704.79 Ubuntu 16.04 (64-bit)

### 你做了什么？

transfer 列表内容搜索

### 你期待的结果是：

能正常过滤

## 实际上的结果：

输入 ( , * 等报错

### 可重现的在线演示

官网demo可以重现

**Comment by codering** [comment]
另外，能否自定义过滤？

**Comment by afc163** [comment]
关于自定义过滤，欢迎 PR
