### ISSUE TITLE
Long Submenu Title Being Overlayed By Arrow Icon

### ISSUE THREAD

**Issue by johnkmzhou** [ant-design/ant-design#22609]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/johnzhou/pen/NWqENOY](https://codepen.io/johnzhou/pen/NWqENOY)

### Steps to reproduce
Create a SubMenu with a long title.

### What is expected?
The SubMenu title and arrow icon should be clearly separated.

### What is actually happening?
The submenu arrow icon is being overlayed over the title.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | Microsoft Windows 10 Pro Version	10.0.17763 Build 17763 |
| Browser | Chrome 80.0.3987.132 |

---
I know that this can fixed in multiple ways, either adding a fixed width to the SubMenu component or removing the width property from the icon but I would prefer a fix in ant.design because I don't think having a long title is out of the ordinary.

**Comment by wwyx778** [comment]
I will fix this :-)
