### ISSUE TITLE
最新版本的 antd 按需加载后使用Button组件会报警告

### ISSUE THREAD

**Issue by xkmy** [ant-design/ant-design#22601]
antd版本:4.0.4
react版本:16.13.1
![image](https://user-images.githubusercontent.com/44152845/77544049-78b54a80-6ee3-11ea-98cb-825b96ca2f35.png)
![image](https://user-images.githubusercontent.com/44152845/77544012-6b985b80-6ee3-11ea-82c4-91c27ddfb57d.png)

**Comment by afc163** [comment]
https://github.com/facebook/create-react-app/releases/tag/v3.4.1 开始默认开启 `React.StrictMode`，这种反馈会越来越多。

#22493
#9870

**Comment by ok2fly** [comment]
> 这种反馈会越来越多。

这种问题应该如何解决 ？求大神指点

**Comment by ok2fly** [comment]
删除index.js的React.StrictMode标签就可以了
