### ISSUE TITLE
Publish source code to npm and enable declarationMap config of typescript

### ISSUE THREAD

**Issue by claneo** [ant-design/ant-design#22617]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometime I want to view source code of ant design, with this config we can view source code using `Go to definition` command directly.

### What does the proposed API look like?
Publish source code to npm and enable declarationMap config of typescript

**Comment by afc163** [comment]
I strongly suggest you could read source code in GitHub (or clone it in your machine) rather than in node_modules.
