### ISSUE TITLE
Ant Design Customize Icon error The tag name provided ('/static/media/delete.0ba2d6ed.svg') is not a valid name

### ISSUE THREAD

**Issue by a3596287** [ant-design/ant-design#22612]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-xdmt7)

### Steps to reproduce
I did not find the place to modify the webpack.configuration.js.

When I render this svg, I got this error : The tag name provided ('/static/media/delete.0ba2d6ed.svg') is not a valid name

### What is expected?
expecting to render the icon 

### What is actually happening?
The tag name provided ('/static/media/delete.0ba2d6ed.svg') is not a valid name

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
It should be related to the `codeandbox` compilation configuration. If you use webpack in your project, you should need a loader that can handle `svg` files.

**Comment by afc163** [comment]
https://ant.design/components/icon/#Custom-SVG-Icon

**Comment by a3596287** [comment]
I followed exactly on https://ant.design/components/icon/#Custom-SVG-Icon, added the code into webpack.config.js.
