### ISSUE TITLE
Select 关闭虚拟滚动什么时候可以用，项目使用现在Select window系统下一直卡顿明显，我看react-component已经支持了

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design#22614]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Select虚拟滚动window系统下一直卡顿明显

### What does the proposed API look like?
Select手动控制开启关闭虚拟滚动，关闭虚拟滚动打开select不会明显卡顿

**Comment by yoyo837** [comment]
#21955 试试最新版本

**Comment by afc163** [comment]
> Select虚拟滚动window系统下一直卡顿明显

我更关心这个是怎么回事，能帮助重现和排查一下么。

**Comment by XSmarter** [comment]
@yoyo837 怎么使用最新版本

**Comment by XSmarter** [comment]
@afc163 我这边mac也没有复现，但是同事一直在说卡顿明显，客户使用也是这样的，就是用antd4 Select 添加了一些options，代码如下，您用window系统试试呢
![image](https://user-images.githubusercontent.com/33716687/77608066-1bf37780-6f57-11ea-9b77-01c13dae1841.png)

**Comment by XSmarter** [comment]
![image](https://user-images.githubusercontent.com/33716687/77608105-39284600-6f57-11ea-8dac-008feb364d47.png)

**Comment by XSmarter** [comment]
展开选择层时动画卡顿

**Comment by XSmarter** [comment]
@afc163 问一下，我应该怎么使用最新版本呢？现在客户反馈体验不太好，让改成原来antd3的方式，我试试最新版本virtual:false

**Comment by yoyo837** [comment]
`dropdownMatchSelectWidth={false}`

**Comment by XSmarter** [comment]
@yoyo837 不需要升级antd 版本吗？ 我现在是antd 4.0.4

**Comment by XSmarter** [comment]
@yoyo837 antd 4.0.4 现在并不支持这样吧

**Comment by yoyo837** [comment]
嗷，好像还没发布

**Comment by yoyo837** [comment]
看样子是需要4.1.0

**Comment by zombieJ** [comment]
@XSmarter ，能否直接贴代码？贴截图复制不下来啊。

**Comment by XSmarter** [comment]
Select 关闭虚拟滚动什么时候会发布？ @zombieJ @afc163 目前项目比较着急需要修复这个问题。这个就是普通的select组件，好像就是用户第一次进入软件时卡顿比较严重，后面再进脚本缓存下来就好了，基本每个windows系统的新用户都是

**Comment by hengkx** [comment]
@XSmarter 能否提供个demo看下为什么卡顿？

**Comment by yoyo837** [comment]
Try v4.1.0, If any questions please feel free to open a new issue for that.
