### ISSUE TITLE
steps 步骤条如果只有2步的话，步骤条可否均等分，也就是后面的横线能否一样长 

### ISSUE THREAD

**Issue by chenggege** [ant-design/ant-design#2261]

**Comment by ddcat1115** [comment]
两步不是只有一根线？麻烦提供下 demo，不太理解

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by chenggege** [comment]
我在你贴的那个连接里面写了如下的代码：step步骤只有2个的话会有两条线，一条长一条短，如何使这两条线一样长呢?



const { Steps } = antd;
const Step = Steps.Step;

const steps = [{
  title: '已完成',
  description: '这里是多信息的描述啊',
}, {
  title: '进行中',
  description: '这里是多信息的耶哦耶哦哦耶哦耶',
}].map((s, i) => <Step key={i} title={s.title} description={s.description} />);

ReactDOM.render(<Steps current={1}>{steps}</Steps>,document.getElementById('container'));

**Comment by afc163** [comment]
Fork 一份 codepen 啊。
