### ISSUE TITLE
[DatePicker/TimePicker] Possibility to disable hours based on the selected date

### ISSUE THREAD

**Issue by hbarcelos** [ant-design/ant-design#22610]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If I need to enforce a date-time to be in the future, currently I can't prevent the user from selecting the wrong hour.

Let's imagine it's 6 PM of 2020-01-01.

I can set the `disabledDate` prop in `DatePicker` as:

```js
function isBeforeToday(current) {
  return !!current && dayjs(current) < dayjs().startOf('day');
}
```

However, there is currently no way of disabling hours before 6 PM if the selected date is today. The `disabledHours` prop that I pass to `showTime` currently does not pass the selected date as a parameter:

| Prop              | Description                                    | Type                                   |
| :---              | :-----------                                   | :---                                   |
| `disabledHours`   | to specify the hours that cannot be selected   | function()                             |
| `disabledMinutes` | to specify the minutes that cannot be selected | function(selectedHour)                 |
| `disabledSeconds` | to specify the seconds that cannot be selected | function(selectedHour, selectedMinute) |

---

Also, if I try to use this as `disabledDate`:

```js
function isBeforeNow(current) {
  return !!current && dayjs(current) < dayjs();
}
```
The current day will be disabled in the calendar, preventing the user from selecting it.

### What does the proposed API look like?
To not have breaking changes, the `selectedDate` parameter could be added at the end of each related function prop.

| Prop              | Type                                                 |
| :---              | :---                                                 |
| `disabledHours`   | function(selectedDate)                               |
| `disabledMinutes` | function(selectedHour, selectedDate)                 |
| `disabledSeconds` | function(selectedHour, selectedMinute, selectedDate) |

**Comment by Mathijs003** [comment]
Having same issue, this is breaking functionality. Severe issue

**Comment by thakkarpanth** [comment]
Having the same issue. Is there any way ?

**Comment by ravneet-core** [comment]
Having the same issue, did anyone figure out how to solve this?

**Comment by phandd** [comment]
I solved this by using state with `onSelect` to track the selected date:
```js
const [selectedDate, setSelectedDate] = useState()

<DatePicker
  onSelect={setSelectedDate}
  showTime={{
    disableHours: () => {
      // use selectedDate here
    }
  }}
/>
```

hope this helps.

**Comment by ashu17706** [comment]
> I solved this by using state with `onSelect` to track the selected date:
> 
> ```js
> const [selectedDate, setSelectedDate] = useState()
> 
> <DatePicker
>   onSelect={setSelectedDate}
>   showTime={{
>     disableHours: () => {
>       // use selectedDate here
>     }
>   }}
> />
> ```
> 
> hope this helps.

Thanks. This is what I was looking for. :)

**Comment by HelpMe-Pls** [comment]
Again, props to @phandd for his much needed solution. I wasn't able to find the `onSelect` prop in the [`<DatePicker/>` component](https://ant.design/components/date-picker/#DatePicker), and also had no idea that `onSelect` prop [from the `<TimePicker/>`](https://ant.design/components/time-picker/#API) somehow works for `<DatePicker/>` (Obviously it triggers TS complain).
Anyway, [here's my sample](https://codesandbox.io/s/disabled-past-date-time-y1nrmm?file=/demo.tsx) for a quick view in case you also had the same problem.

Cheers.

**Comment by zombieJ** [comment]
Close since `disabledTime` already support passing date.

**Comment by korkt-kim** [comment]
@zombieJ I think `disabledTime` does not support passing date yet. because the return type of `disabledTime` is still 
`
{
    disabledHours?: () => number[];
    disabledMinutes?: (hour: number) => number[];
    disabledSeconds?: (hour: number, minute: number) => number[];
}
`
