### ISSUE TITLE
select在rule规则下验证存在问题

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/ant-design#22613]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-ant-design-demo-in8vx?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
初始化值是5
```
  useEffect(() => {
    form.setFieldsValue({
      username: 5
    });
  }, []);
```
设置规则最小是1，最大是10
```
        rules={[
          {
            min: 1,
            max: 10,
            message: "username error!"
          }
        ]}
```

### What is expected?
验证结果应该是正确的

### What is actually happening?
提示错误

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/jibenshiyong-ant-design-demo-of62j

**Comment by afc163** [comment]
<img width="875" alt="image" src="https://user-images.githubusercontent.com/507615/77607184-7a6b2680-6f54-11ea-80b9-020b31f8da86.png">

**Comment by afc163** [comment]
https://codesandbox.io/s/jibenshiyong-ant-design-demo-61o8q
