### ISSUE TITLE
Selection keys and rows  are not initialized  at  data source changed  on ant table

### ISSUE THREAD

**Issue by sb-lee** [ant-design/ant-design#22623]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/selection-and-operation-ant-design-demo-2424g)

### Steps to reproduce
0. Please, open reproduction
1. Select some check boxes.
2. Next, delete  selected rows  on data source
3. Finally, check current selected rows and keys.
3-1 Or else,  check table selected rows and key when another additional rows are selected

### What is expected?
Initialize selection or  remove  selected rows and keys  when Its are deleted on data source.

### What is actually happening?
The selection of deleted data remains.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | window 10  (1909) |
| Browser | chrome latest |

**Comment by afc163** [comment]
`state.xxx` will keep in it's value util you change it manually or select item in Table, `dataSource` change won't affect it.
