### ISSUE TITLE
<BackTop> don't work with antd <Table> or how to make it work?

### ISSUE THREAD

**Issue by TRUEJASONFANS** [ant-design/ant-design#22628]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8cwp7)

### Steps to reproduce
just direct run

### What is expected?
When scroll bar scroll into the bottom, the BackTop should be visible

### What is actually happening?
No BackTop existed

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | 16.8.6 |
| System | windows |
| Browser | chrome |

**Comment by xrkffgg** [comment]
<img width="1221" alt="WeChat39556da1c5c017b26c030ea9e70c33d4" src="https://user-images.githubusercontent.com/29775873/77622481-4bb37700-6f79-11ea-8013-b69ef8912ff5.png">

这样？

**Comment by TRUEJASONFANS** [comment]
@xrkffgg ,
之前我试过这样， 我补充了下sandbox的代码。当我把content的高度设置style={{ height: "calc(100vh - 50px)" }}, BackTop就一直show不出来了。 我把去掉了就shows 出来了。 Anyway, 谢谢的你的帮助

**Comment by xrkffgg** [comment]
设置了 table 的高度之后，滚动是在 table 内部，外部的高度是达不到 默认 BackTop 的触发条件（400px）。
<img width="1244" alt="WeChatf77086a31d8998608d50fc8a43a90e06" src="https://user-images.githubusercontent.com/29775873/77630409-ec0f9880-6f85-11ea-9fde-3378e0c633aa.png">

你试试这个 `target`
https://ant.design/components/back-top-cn/#API

**Comment by TRUEJASONFANS** [comment]
@xrkffgg , 嗯嗯 我也注意到了这个属性， 但是不太明白怎么写一个对table的target。

**Comment by xrkffgg** [comment]
试试设个 id ，然后用 `document.getelementbyid` 

其实我也没用过，我是猜的

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-wrmgr

**Comment by TRUEJASONFANS** [comment]
> https://codesandbox.io/s/antd-reproduction-template-wrmgr

@afc163  谢谢你解答

**Comment by wang3620** [comment]
请问如何在table内部实现一个BackTop呢？我尝试了这个
```
          <Table
            id="my-special-table"
            onChange={this.handleTableOnChange}
            className={styles.mainTable}
            columns={columns}
            dataSource={testData}
            pagination={{ pageSize: 100 }} scroll={{ y: 240 }}
          />
          <BackTop target={() => document.getElementById("my-special-table")} />
```
但是没反应，画到table最低下了还是没有backtop的按钮. @afc163 谢谢！

**Comment by wang3620** [comment]
> 请问如何在fixed header的table内部实现一个BackTop呢？我尝试了这个
> 
> ```
>           <Table
>             id="my-special-table"
>             onChange={this.handleTableOnChange}
>             className={styles.mainTable}
>             columns={columns}
>             dataSource={testData}
>             pagination={{ pageSize: 100 }} scroll={{ y: 240 }}
>           />
>           <BackTop target={() => document.getElementById("my-special-table")} />
> ```
> 
> 但是没反应，画到table最低下了还是没有backtop的按钮. @afc163 谢谢！

Never mind. I figure it out by this :) 
```
<Table
            onChange={this.handleTableOnChange}
            className={styles.mainTable}
            columns={columns}
            dataSource={testData}
            pagination={{ pageSize: 100 }} scroll={{ y: 240 }}
          />
<BackTop target={() => document.getElementsByClassName("ant-table-body")[0]} />
```
