### ISSUE TITLE
Calendar组件在非全屏模式时，建议增加日期区间选择功能，同时建议增加周(week)的选择功能。

### ISSUE THREAD

**Issue by qingxs** [ant-design/ant-design#22622]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当Calendar组件在mini模式下时，我经常把它作为页面上快速切换日期搜索条件来使用，比如员工考勤统计，左边是日历选择，右边是考勤统计的列表。目前的情况只能单选，无法做到多天的考勤统计。类似的应用场景很常见，希望开发者们能考虑一下。
为什么我要用Calendar组件而不用DatePicker?
1，用DatePicker选择日期，不能直观的看到当前的日历。
2，使用DatePicker选择日期比Calendar更麻烦。
3，Calendar在页面上直接显示，会使页面显得更美观大气。

### What does the proposed API look like?
**增加rangeSelect开关，当rangeSelect=true时，onSelect回调为function([moment,moment])，为rangeSelect=false时保持原API不变。**

####代码片断####
```jsx
const onSelect=(selected)=>{
	console.log(selected);
	//rangeSelect=true时: [moment,moment]
	//rangeSelect=false时: moment
}
...
<Calendar
	rangeSelect
	fullscreen={false}
	onSelect={onSelect}
/>
```

**Comment by qingxs** [comment]
有人看到吗？能不能给个回复？

**Comment by hengkx** [comment]
看了下组件太复杂了 涉及的东西比较多 暂时没有太多时间一点点的看还是让别人处理把 
:joy:

**Comment by jzhao62** [comment]
这个issue 现在是inactive， 还接受MR吗

**Comment by ianzone** [comment]
希望能做成这种 https://www.telerik.com/kendo-react-ui/components/scheduler/

**Comment by afc163** [comment]
Trace #40051
