### ISSUE TITLE
codesandbox cannot jump directly

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#22636]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
friendly experience
![image](https://user-images.githubusercontent.com/8358236/77643811-f9834d80-6f9a-11ea-8644-2aa9eadff9a9.png)
![image](https://user-images.githubusercontent.com/8358236/77643863-0e5fe100-6f9b-11ea-8173-970d11f1018a.png)

### What does the proposed API look like?
not

**Comment by afc163** [comment]
好像这周起突然这样了，帮忙一起看看。

**Comment by hengkx** [comment]
好像是`referer`导致的
![image](https://user-images.githubusercontent.com/8358236/77650581-add6a100-6fa6-11ea-9f75-6ef84271f334.png)
![image](https://user-images.githubusercontent.com/8358236/77650612-b4fdaf00-6fa6-11ea-9df7-e7f7159b535b.png)
