### ISSUE TITLE
Card Tabs do not support small size

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#22637]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daxiao-ant-design-demo-s2k93)

### Steps to reproduce
view reproduce

### What is expected?
support small

### What is actually happening?
not support small

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | latest |
| System | https://codesandbox.io/s/daxiao-ant-design-demo-s2k93 |
| Browser | chrome |

**Comment by MrHeer** [comment]
it's by design?
https://github.com/ant-design/ant-design/blob/c6fc5030e508eca57207258d62b7913e2df6fe0e/components/tabs/index.tsx#L118-L122

**Comment by afc163** [comment]
We can remove the warning too.

**Comment by MrHeer** [comment]
Ok, I'll PR.
