### ISSUE TITLE
点击 <Table /> 的某一行，如何对该行追加 class，实现高亮

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#2263]
如题。

看到`rowClassName`可以配置表格行的类名，但它只会在渲染数据时，触发一次，在点击时，并不会执行。

**Comment by afc163** [comment]
`onRowClick` 后动态设定 `rowClassName`。

**Comment by ystarlongzi** [comment]
我知道为什么点击后不会执行了，因为我没更改组件的 state，所以就不会执行 render 函数了。。。傻了

**Comment by zhangolve** [comment]
感谢楼上的提问和解答，对我也有很大帮助。

**Comment by wnSmile** [comment]
请问是怎么解决的 ，有代码可以查看吗

**Comment by lvybriage** [comment]
请问 可以paste代码吗 感激不尽
