### ISSUE TITLE
DefaultValue doesn't work for vertical Slider

### ISSUE THREAD

**Issue by kpavlov7** [ant-design/ant-design#22645]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-1e8rw)

### Steps to reproduce
Slider component with properties vertical={true} min={0} max={100} and defaultValue={11}

### What is expected?
It is expected that the position of the slider head is at the default value.

### What is actually happening?
The position of the slider head is at 0.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.9.0 |
| System | Windows 10 x64 |
| Browser | Chrome  Version 80.0.3987.149 (Official Build) (64-bit) |

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/77701547-8d800400-6ff1-11ea-9239-8023e03a8c29.png)
spell check
