### ISSUE TITLE
0.12版本的Select在showSearch状态下搜索结果为空时点键盘向下按钮时整个页面无响应

### ISSUE THREAD

**Issue by abyssBx** [ant-design/ant-design#2264]
### 本地环境

- antd 版本: 0.12.17
- 操作系统及其版本：OS X 10.11.3
- 浏览器及其版本: Google Chrome 51.0.2704.106

### 你做了什么？

引入 antd 的Select, 并且设置 showSearch
在搜索框输入值，使搜索结果为空
点击键盘向下方向键

## 实际上的结果：

整个网页无响应

### 可重现的在线演示

官网0.12.17的带搜索框的select即可重现
1.6.x的文档带搜索框的select无搜索框，所以不知道问题是不是存在

**Comment by afc163** [comment]
1.6.x 搜索框就在选择器上。https://github.com/ant-design/ant-design/issues/1390

**Comment by ddcat1115** [comment]
1.6.x 带搜索框的 select 没有该问题，尽量更新下吧
