### ISSUE TITLE
Tooltip in form.item is not working with validate rules

### ISSUE THREAD

**Issue by JumpAttacker** [ant-design/ant-design#22640]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-pyqnb2?file=index.js](https://stackblitz.com/edit/react-pyqnb2?file=index.js)

### Steps to reproduce
type in all inputs, then try to submit

### What is expected?
it validate me

### What is actually happening?
it always talking to me, that my input(with Tooltip inside) is null

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | react@16.13.1 |
| System | win10 |
| Browser | 80.0.3987.132 |

**Comment by zombieJ** [comment]
Form.Item inject value & event on sub component directly. You should customize component with Tooltip support.
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by JumpAttacker** [comment]
do u mean i should create a new component, which will contain tooltip and input inside?

**Comment by vinceplayer** [comment]
@JumpAttacker have you resolved?

**Comment by JumpAttacker** [comment]
> @JumpAttacker have you resolved?

dont remember already ;d, not using this package right now
