### ISSUE TITLE
Select without width will shake when placeholder provided

### ISSUE THREAD

**Issue by kaiyoma** [ant-design/ant-design#22649]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-with-search-field-ant-design-demo-0gsfx)

### Steps to reproduce
For a Select component, set `dropdownMatchSelectWidth` to true and set `showSearch` to true. Enter some text to search the options.

### What is expected?
The component should expand automatically to show the search term.

### What is actually happening?
The entire component collapses in on itself.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 80, Firefox 74, Edge 18 |

**Comment by zombieJ** [comment]
It's not related with `dropdownMatchSelectWidth`. Default Select do not have length but `placeholder` extends the length: https://codesandbox.io/s/select-with-search-field-ant-design-demo-qbc6g

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/32988
