### ISSUE TITLE
TextArea autoSize prevents the manual resize on Firefox 

### ISSUE THREAD

**Issue by DidiBear** [ant-design/ant-design#22648]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mec8m)

### Steps to reproduce
Manually resize the TextArea with the drag at the bottom-right.

### What is expected?
The manual resize should work as when there is no autoSize => https://codesandbox.io/s/yc7ci

### What is actually happening?
The manual resize is directly blocked, making it impossible to resize the text area as we want.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12 |
| System | Ubuntu 19.04 |
| Browser | Firefox 74.0 |

---
Those codepen links are the one [from the `Input` demo](https://ant.design/components/input/#components-input-demo-autosize-textarea).

**Comment by afc163** [comment]
Duplicate of #19652

**Comment by DidiBear** [comment]
@afc163 This is not a duplicate of #19652:
- In #19652 the resize cannot reduce the size, this is only related with Chrome.
- Here the issue is that the resize is blocked, this is only related with Firefox.

**Comment by zombieJ** [comment]
Manually adjust height of TextArea is against with `autoSize` prop. We should add `resize: none` when `autoSize` is enabled.
