### ISSUE TITLE
Icons-svg 这个包怎么去掉， 体积太大

### ISSUE THREAD

**Issue by shen1986** [ant-design/ant-design#22650]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://extraimage.net/image/LwrM](https://extraimage.net/image/LwrM)

### Steps to reproduce
把现有的项目从V3版本升级到v4版本然后通过 react-app-rewired build 时候 ，发现这个包体积太大了，Icon的导入方式全部用最新的方法import { ReloadOutlined } from '@ant-design/icons';

### What is expected?
Icons-svg 能够不导入么

### What is actually happening?
Icons-svg 体积太大

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | React 16.4.1 |
| System | win10 |
| Browser | chrome 80.0.3987.132 |

**Comment by XSmarter** [comment]
看了下自己的icons 确实大啊，不是说antd4新版本按需加载吗？代码里已经把原来老版本的icon引入方式全部替换成新的了
![image](https://user-images.githubusercontent.com/33716687/77714292-9da8db00-7013-11ea-9262-a0eaaadd0401.png)

**Comment by yoyo837** [comment]
你的tree shaking没生效，出了antd支持，你的bundle工具也要配置正确

**Comment by XSmarter** [comment]
![image](https://user-images.githubusercontent.com/33716687/77714569-4820fe00-7014-11ea-9554-2e709ad2de8e.png)
package.json 是这样的

**Comment by yoyo837** [comment]
提供复现repo吧

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design-pro/issues/6173#issuecomment-602983469

**Comment by afc163** [comment]
@shen1986 怎么解决的

**Comment by shen1986** [comment]
做最小化仓库时候，某些配置组件更新到新版本后，有些配置文件和新版本不兼容，导致ree shaking没生效，谢谢yoyo837的提醒

**Comment by dyyliao123** [comment]
> 做最小化仓库时候，某些配置组件更新到新版本后，有些配置文件和新版本不兼容，导致ree shaking没生效，谢谢yoyo837的提醒

怎么解决的啊
