### ISSUE TITLE
Cannot get right DOM Elements of 4.x Tree in useEffect hook when expandedKeys change

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#22651]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyizhankaizhedietubiao-ant-design-demo-1kyx5)

### Steps to reproduce
1. Get DOM in useEffect hook when expandedKeys change.
2. Expand treeNode.
3. Cannot get the right DOM, which WORKS in 3.x.

### What is expected?
Can get the right DOM, just like 3.x

### What is actually happening?
Cannot get the right DOM in 4.x without setTimeOut.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.12.0 |
| System | win10 |
| Browser | Google Chrome  version79.0.3945.88 |

---
I believe that `React guarantees the DOM has been updated by the time it runs the effects`. It's abnormal that I can't get right DOM in useEffect hook. Also, 3.x Tree doesn't have this bug.

**Comment by sdhr27** [comment]
Can get the right DOM in 3.x Tree but not 4.x

**Comment by sdhr27** [comment]
I believe that React guarantees the DOM has been updated by the time it runs the effects. It's abnormal that I can't get right DOM in useEffect hook.

**Comment by zombieJ** [comment]
v4 use virtual scroll which append node async. You can add `setTimeout` as workaround: https://codesandbox.io/s/zidingyizhankaizhedietubiao-ant-design-demo-1r9x0

PS: Use `querySelectorAll` is not a React way. You'd better to consider refactor your code for this.
