### ISSUE TITLE
表单使用this.props.form.resetFields()无法清除设置的initialValue 

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2265]

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2173

---

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
