### ISSUE TITLE
table-resizable-column in RTL is broken

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#22659]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-resizable-column](https://ant.design/components/table-cn/#components-table-demo-resizable-column)

### Steps to reproduce
- Open link
- Select RTL
- Try resizable column

### What is expected?
- It is work

### What is actually happening?
- It's not work

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by xrkffgg** [comment]
这个我看了一下，`react-resizable` 已经支持了设置 RTL https://github.com/STRML/react-resizable/issues/95

怎么在 Demo 判断 direction 再研究一下

**Comment by xrkffgg** [comment]
@afc163 
我看那个 [STRML/react-resizable](https://github.com/STRML/react-resizable) 维护性不是很好，有一个可以支持的 PR 一年了都没处理😂 。

你要不要在 ant-design 或者 react-component fork 一份，我看看能修改一下 提交到这边来

**Comment by xrkffgg** [comment]
感觉 https://github.com/bokuweb/react-rnd 比 https://github.com/STRML/react-resizable 功能好一些

**Comment by afc163** [comment]
@xrkffgg 可换。

**Comment by huangweirong** [comment]
> 感觉 https://github.com/bokuweb/react-rnd 比 https://github.com/STRML/react-resizable 功能好一些

react-rnd在antd中用不起来，报错元素类型无效，想问下是引用完直接使用就行嘛？

**Comment by xrkffgg** [comment]
@huangweirong 应该是可以的，但和表格结合起来还有点难。我记得 react-rnd 是要求有一个盒子的，和 react-resizable 的结构是不一样的

**Comment by xrkffgg** [comment]
There is a solution in RTL

Modify in css

```diff
#components-table-demo-resizable-column .react-resizable-handle {
  position: absolute;
--right: -5px;
++left: -5px;
  bottom: 0;
  z-index: 1;
  width: 10px;
  height: 100%;
  cursor: col-resize;
}
```

Add in jsx

```diff
<Resizable
  width={width}
  height={0}
  handle={
    <span
      className="react-resizable-handle"
      onClick={e => {
        e.stopPropagation();
      }}
    />
  }
  onResize={onResize}
++resizeHandles={['w']}
  draggableOpts={{ enableUserSelectHack: false }}
>
  <th {...restProps} />
</Resizable>
```
