### ISSUE TITLE
树选择组件 是否支持节点只能下拉不能选中

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2266]

**Comment by ddcat1115** [comment]
可以在 `onChange` 里控制，参考 http://react-component.github.io/tree-select/examples/basic.html  中 just select children 一例

**Comment by aw6658913** [comment]
我这个是在表单里面的，在表单里是onChange控制的，难不成我要表单触发设置成onSelect吗？

**Comment by warmhug** [comment]
表单验证，参考这里： http://react-component.github.io/tree-select/examples/form.html

**Comment by aw6658913** [comment]
另外请教下，除了旁段是否为父节点用onChange设置value之外，有那种直接父节点就显示为不可选中状态然后子节点可以选中吗？disabled是直接整个节点包括子节点都禁用掉了
