### ISSUE TITLE
Input的type为number时，对 “0.”失去焦点的处理前后不一致

### ISSUE THREAD

**Issue by n313893254** [ant-design/ant-design#22668]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-ant-design-demo-jpuw0)

### Steps to reproduce
1. 输入 `0.`，鼠标点击空白处使其失去焦点， 此时输入框为 `0`
2. 在原来的0后面增加`.`, 鼠标点击空白处使其失去焦点， 此时输入框为 `0.`

### What is expected?
输入框应该显示为 `0`

### What is actually happening?
输入框显示为 `0.`

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | MacOS 10.14.2 |
| Browser | Chrome 80.0.3987.149 |

**Comment by zombieJ** [comment]
这个是原生行为，antd 这边做不了什么：https://codesandbox.io/s/jibenshiyong-ant-design-demo-4xvw9
