### ISSUE TITLE
Typescript definitions update for Form, Form.Item

### ISSUE THREAD

**Issue by Faisal-Manzer** [ant-design/ant-design#22661]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
Copied and pasted "Login Form"

### What is expected?
There should be no error in types

## Typescript error in "Form"
*"TS2339: Property 'className' does not exist on type 'IntrinsicAttributes & FormProps & RefAttributes<FormInstance>'."*
```
<Form
                name="normal_login"
                className="login-form"
                initialValues={{remember: true}}
                onFinish={this.onFinish}
            >
```

## Typescript error in "Form.Item"
*TS2339: Property 'name' does not exist on type 'IntrinsicAttributes & FormItemProps'.*
```
<Form.Item
                    name="username"
                    rules={[{required: true, message: 'Please input your Username!'}]}
                >
                    <Input prefix={<UserOutlined className="site-form-item-icon"/>} placeholder="Username"/>
                </Form.Item>
```

## Typescript error in "Form.Item"
*TS2322: Type '{ children: (string | Element)[]; }' is not assignable to type 'IntrinsicAttributes & FormItemProps'.   Type '{ children: (string | Element)[]; }' is not assignable to type 'FormItemProps'.     Types of property 'children' are incompatible.       Type '(string | Element)[]' is not assignable to type 'ChildrenType'.         Type '(string | Element)[]' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | any | (new (props: any) =>...'.
TS2322: Type '{ children: (string | Element)[]; }' is not assignable to type 'IntrinsicAttributes & FormItemProps'.   Type '{ children: (string | Element)[]; }' is not assignable to type 'FormItemProps'.     Types of property 'children' are incompatible.       Type '(string | Element)[]' is not assignable to type 'ChildrenType'.         Type '(string | Element)[]' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | any | (new (props: any) =>...'.           Type 'string | Element' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | any | (new (props: any) =>...'.             Type 'string' is not assignable to type 'ReactElement<any, string | ((props: any) => ReactElement<any, string | any | (new (props: any) =>...'.*
```
<Form.Item>
                    <Button type="primary" htmlType="submit" className="login-form-button">
                        Log in
                    </Button>
                    Or <a href="#!">register now!</a>
                </Form.Item>
```

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | MacOS (issue is platform independent) |
| Browser | not a browser issue |

**Comment by Faisal-Manzer** [comment]
Sorry it was some of my fault

**Comment by aureliusm** [comment]
@Faisal-Manzer Can you please explain the fault - having the same issue. Thanks!

**Comment by peelin** [comment]
@aureliusm  Me too! Please post here if you figure it out.

**Comment by ayegnb** [comment]
@peelin @aureliusm @Faisal-Manzer have you figured out what caused this error? Would appreciate your explanation

**Comment by LoicUV** [comment]
@peelin @aureliusm @Faisal-Manzer @ayegnb I had the issue after migrating from antd 3 to 4 with dev server running. Restarting it + reloading vscode view fixed it (stale types from v3).

**Comment by meltemgursoy** [comment]
Same problem ! What is the exact solution?

**Comment by cup0ra** [comment]
Same problem ! What is the exact solution?

**Comment by imCorfitz** [comment]
I kept having this issue, because the `Form` component was imported from the wrong path. TypeScript auto imported here: `import Form from 'antd/lib/form/Form';`. This `Form` component does not have the `<Form.Item>`... 

Initially I found the `FormItem` component here: `import FormItem from 'antd/lib/form/FormItem';` until I realised, that in the documentation, `Form` was imported directly from `antd`. import { Form } from 'antd';`. Now everything works as intended.

**Comment by IskraAtanasova** [comment]
Could you please explain how to make it work if the import is:
import { Form } from "@ant-design/compatible"

I am using <Form.Item
          name="inputField"
             rules={[
               {
                type: "email",
                  message: "Please enter a valid email address."
              },
                ]}
> 
<Input></Input>
</Form.Item> 

***I need the Form to be imported from compatible

**Comment by tiborsaas-tw** [comment]
I also ran into this and I was very puzzled until I realized that my `<Title>` component was imported from `antd/lib/skeleton/Title` instead of `antd/lib/typography/Title`
