### ISSUE TITLE
[4.0.4] Locale `lang` types are not up-to-date.

### ISSUE THREAD

**Issue by PaulJln** [ant-design/ant-design#22674]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/PaulJln/antd-4.0.4-date-picker-local-fr-FR](https://github.com/PaulJln/antd-4.0.4-date-picker-local-fr-FR)

### Steps to reproduce
Open antd/lib/date-picker/locale/fr_FR.d.ts and antd/lib/date-picker/locale/en_US.d.ts, type lang looks different. The type `rangePlaceholder: string[]` is missing.

### What is expected?
Related to : https://github.com/ant-design/ant-design/pull/22122

The field `rangePlaceholder: string[];` is missing.

### What is actually happening?
```
Types of property 'timePickerLocale' are incompatible.
    Property 'rangePlaceholder' is missing in type '{ placeholder: string; }' but required in type '{ placeholder: string; rangePlaceholder: string[]; }'.ts(2719)
en_US.d.ts(44, 9): 'rangePlaceholder' is declared here.
```

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12 |
| System | MacOS 10.15.3 |
| Browser | Firefox Developer Edition v74 |

**Comment by afc163** [comment]
@PaulJln Could you send a PR?

**Comment by PaulJln** [comment]
@afc163 Yes, I'll do it later this day, sorry for the delay !
