### ISSUE TITLE
UploadFile组件，onChange事件`不起作用`

### ISSUE THREAD

**Issue by openwings** [ant-design/ant-design#2267]
### 本地环境

- antd 版本:1,6,3
- 操作系统及其版本：MacOS
- 浏览器及其版本:Chrome50.2

### 你做了什么？

使用FileUpload组件，action指定为上传接口。绑定onChange监听器，做状态更新

### 你期待的结果是：

onChange被正确调用，从而可以控制过程

## 实际上的结果：

onChange事件`不起作用`

### 可重现的在线演示
无

**Comment by ddcat1115** [comment]
请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001
