### ISSUE TITLE
Spin no vertical center

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#22684]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyimiaoshuwenan-ant-design-demo-80jyc)

### Steps to reproduce
demo

### What is expected?
vertical center

### What is actually happening?
 no vertical center
![image](https://user-images.githubusercontent.com/8358236/77799682-4278f600-70b0-11ea-9fe0-b92d6221fb0a.png)

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | latest |
| System | windows  |
| Browser | chrome |

**Comment by zombieJ** [comment]
It's by design.

ref: https://github.com/ant-design/ant-design/commit/e008214f566c7855d7c0d4b940ce5a972a232ca3
