### ISSUE TITLE
Antd Affix: Memory leak error

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#22683]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-shamir-tn0fu)

### Steps to reproduce
1. Scroll a little till the Affix becomes sticky.
2. Click on Toggle button.
3. First Affix is removed and second Affix gets mounted.
4. Warning seen on console - Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
5. Note: This is particularly observed in Chrome - Emulation Mode (Responsive Viewport Mode)

### What is expected?
Warning should not appear

### What is actually happening?
Memory leak warning is seen

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.3 |
| System | Windows 10 |
| Browser | Chrome - Emulation Mode (Responsive Viewport Mode) |

**Comment by mendoncanorma** [comment]
@afc163 ,
Do you need any more information for this bug. Were you able to replicate it.

**Comment by afc163** [comment]
I can't reproduce any warning.

**Comment by mendoncanorma** [comment]
@afc163 ,

You need to be on Chrome - Responsive View Port Mode. We are able to consistently replicate this issue. I have attached recording and screenshot of the issue.

![22683-1](https://user-images.githubusercontent.com/5765207/77822594-46d9f900-711a-11ea-8d3e-7c11e75f9e3b.png)


[22683-1.zip](https://github.com/ant-design/ant-design/files/4397096/22683-1.zip)

**Comment by afc163** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/77823173-05eede00-7134-11ea-8599-9d3c58f9ed9d.png">

**Comment by mendoncanorma** [comment]
@afc163 ,
That's right. We consistently see this warning.

**Comment by mendoncanorma** [comment]
@afc163 , 
Thank you for fixing. Which version of antd will this be available?

**Comment by afc163** [comment]
Next patch: https://ant.design/changelog#Release-Schedule

**Comment by mendoncanorma** [comment]
Will it be available in 3.x.? As I mentioned above, we can't upgrade to 4.x at this point.

**Comment by afc163** [comment]
I cherry-picked to 3.x-stable branch now, it will be released in next 3.x patch version which may be at next weekend.

**Comment by mendoncanorma** [comment]
Thank you @afc163.

**Comment by hydiamond** [comment]
This situation also happens with Table :'((

**Comment by Virgil-N** [comment]
It occurs now and then.

**Comment by KaseyaCat** [comment]
It occurs with unpounted Menu comptonent too

**Comment by Chilingaryan** [comment]
I am facing with the same memory leakage warning when Menu component gets unmounted with `items` props
` "antd": "^5.5.1"`. It seems the problem is not resolved yet

**Comment by romulorod** [comment]
I also face this for the Select components, using antd 4.x
![image](https://github.com/ant-design/ant-design/assets/80011318/dfe4d753-324a-4e90-a138-eb1e73257230)

**Comment by bacardi-rum** [comment]
@romulorod same problem here, using TreeSelect from antd 4.x

**Comment by bamtheboozle** [comment]
any updates? seems like this still happens with dropdown menus

**Comment by yoyo837** [comment]
ref: #42674

**Comment by akuzko** [comment]
@romulorod @bacardi-rum faced the same issue with ant'd `Select` with `mode="multiple"` on 4.x. Got rid of it by fixing `rc-overflow` package on version 1.2.8
