### ISSUE TITLE
ant 表格分页，不能主动设置当前的页数 ，只能通过鼠标事件

### ISSUE THREAD

**Issue by float90** [ant-design/ant-design#2268]
### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by RaoHai** [comment]
```
const pagination = {
  defaultCurrent: 2,
 ...
}
```

**Comment by cike8899** [comment]
我也遇到了相同的问题，及时设置了defaultCurrent:2 蓝的背景色还是在1上面！

**Comment by afc163** [comment]
`current`

https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by zhiqiang21** [comment]
问题怎么解决的 @RaoHai

**Comment by YagamiLight126** [comment]
解决这个问题应该由默认的state来控制，
const paginationSetting = {
      total: total_count, // 数据总数
      defaultCurrent: 1, // 默认的当前页数
      current: currentPage, // 当前页数
      onChange,// 页码改变的回调
}
const onChange = (page, pageSize) => {
      this.setState({currentPage: page});
      this.apiRequest({ page: page, per_page: pageSize });
    };
