### ISSUE TITLE
<Select/> always validation error

### ISSUE THREAD

**Issue by SiriMhM** [ant-design/ant-design#22685]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)

### Steps to reproduce

- Add a < Select/ > with selectMode "multiple" or "tags" as < Form.Item/ >

- Add to the Form.Item the following: `rules={[{ type: 'any', required: true, message: 'Please fill out the select' }]}`

### What is expected?
The field is required and after providing correct data, it won't show that the validation has an error.

### What is actually happening?
The validation always shows an error, although there have been added correct values in the select.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | Windows 10 Pro, x64 |
| Browser | Google Chrome 80.0.3987.149 |

**Comment by hengkx** [comment]
No problem with the test https://codesandbox.io/s/xiaoyanqitazujian-ant-design-demo-0hple

**Comment by SiriMhM** [comment]
Hi, sorry it's because I use it in a functional component. Is is possible to use a < Select /> in a functional component (useRef or useCallback) ?
Or is it definitely necessary to use a class-component ?
