### ISSUE TITLE
Pre populate API data in FORM

### ISSUE THREAD

**Issue by Nilanth** [ant-design/ant-design#22692]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As in Form, the data stored in redux is not recommended as mentioned in AntD docs, Then how we can prepopulate API data to form?
https://ant.design/components/form/#components-form-demo-global-state

### What does the proposed API look like?
There should be a prop to prepopulate the data to FORM from API response

**Comment by zombieJ** [comment]
You can reset fields when initial value is ready.

```tsx
useEffect(() => {
  form.resetFields();
}, [props.initialValues]);

return <Form initialValues={props.initialValues} />;
```
