### ISSUE TITLE
Table组件scroll在x,y都设置的情况下,列的内容重叠，行错位

### ISSUE THREAD

**Issue by fantaishao** [ant-design/ant-design#22700]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/LiLu2020/pen/vYOvjoP](https://codepen.io/LiLu2020/pen/vYOvjoP)

### Steps to reproduce
设置table的scroll.x = true，scroll.y = 200，列的第一列和最后一列固定

### What is expected?
表格有横向和纵向滚动条，表头和内容能完整展示，并且不换行

### What is actually happening?
横向滚动条未出现，列的内容换行，设置’white-space: nowarp'属性无效，行错位

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | 16.8.5 |
| System | maxos |
| Browser | Google Chrome Version 80.0.3987.149 |

**Comment by afc163** [comment]
<img width="462" alt="image" src="https://user-images.githubusercontent.com/507615/77828886-28472280-7159-11ea-872e-ff3b2b11af30.png">

https://3x.ant.design/components/table-cn/#components-table-demo-fixed-header

**Comment by fantaishao** [comment]
> <img alt="image" width="462" src="https://user-images.githubusercontent.com/507615/77828886-28472280-7159-11ea-872e-ff3b2b11af30.png">
> 
> https://3x.ant.design/components/table-cn/#components-table-demo-fixed-header

最后一列和第一列需要固定，我设置了宽度。
其他列希望是内容来撑开，不换行，出现横向滚动条。
但是现在设置scroll.x = true，scroll.y = 200没有出现横向滚动，内容也换行了。
我是参照这个例子来的
https://3x.ant.design/components/table-cn/#components-table-demo-fixed-columns-header

**Comment by afc163** [comment]
固定列头的时候，最好每一列都给宽度（可以留一列不设宽度适应流式布局），否则都有可能对不齐。

**Comment by fantaishao** [comment]
> 固定列头的时候，最好每一列都给宽度（可以留一列不设宽度适应流式布局），否则都有可能对不齐。

定宽，内容多的话，会换行。 现在预期效果是不换行。如果给省略号，设置横向滚动好像没有意义。
感觉x轴和y轴的设置只能二选一
