### ISSUE TITLE
使用form标签 出错

### ISSUE THREAD

**Issue by wwlweihai** [ant-design/ant-design#2270]
### 本地环境

- antd 版本: 1.6.3
- 操作系统及其版本：mac 
- 浏览器及其版本: chrome

## 实际上的结果： 

Warning: Unknown prop `prefixCls` on <form> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in form (created by Form)
    in Form (created by SignIn)
    in div (created by SignIn)
    in div (created by SignIn)
    in SignIn (created by Form(SignIn))
    in Form(SignIn)

**Comment by afc163** [comment]
trace on #2258

**Comment by wwlweihai** [comment]
感谢
