### ISSUE TITLE
Please include use of new dependency 'ant-design/icons" in Icons page (https://ant.design/components/icon/)

### ISSUE THREAD

**Issue by natashavg** [ant-design/ant-design#22707]
- [ X ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
People will all run into issue of copied icon code on (https://ant.design/components/icon/) not working because it is failing to import from 'antd'. Because this is unique to these components it would be nice if the dependency was listed at the top of the page.

### What does the proposed API look like?
no api, just update the docs at https://ant.design/components/icon/

**Comment by hengkx** [comment]
I also encountered the same problem when using it for the first time
