### ISSUE TITLE
allowClear fires form validation

### ISSUE THREAD

**Issue by shindig** [ant-design/ant-design#22706]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-d8zqd)

### Steps to reproduce
1) Select the one option available in the Select
2) Click the "allowClear" icon in the Select

### What is expected?
Validation should not be performed until the form is submitted

### What is actually happening?
Form validation is fired off and the "required" error message is showing as soon as you click the "allowClear" icon.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | React 16.13.1 |
| System | OS X Mojave 10.14.6 |
| Browser | Chrome 80.0.3987.149 |

**Comment by zombieJ** [comment]
Use `validateTrigger` to config validate trigger event.
