### ISSUE TITLE
新版 Table 在手机端 ios10 版本的Safari下无法横向滚动

### ISSUE THREAD

**Issue by Cedcn** [ant-design/ant-design#22702]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yijsk)
https://codesandbox.io/s/yijsk

### Steps to reproduce
https://ant.design/components/table/ ios10及以下版本的手机访问Demo

https://github.com/ant-design/ant-design/blob/2cb516b5b7f1705a13631386d6b297e0caec8ca3/components/table/Table.tsx#L417-L419
猜测可能是上面这个绑定事件导致的

### What is expected?
可以滚动

### What is actually happening?
在手机端低版本的ios下无法滚动.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.0 |
| System | ios 10.3.1 |
| Browser | Safari |

**Comment by afc163** [comment]
antd 是面向桌面端的组件库，低版本的移动端设备不会再专门兼容了。
