### ISSUE TITLE
AutoComplete does not use value prop correctly.

### ISSUE THREAD

**Issue by yifengd** [ant-design/ant-design#22704]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autocomplete-issue-reproduction-d8ep1)

### Steps to reproduce
Attempting to use the value prop as an object or array of objects as described in the API (https://ant.design/components/auto-complete/#API).

### What is expected?
The input field is rendered as a series of react elements, e.g. tags, or a mix of string and tags.

### What is actually happening?
The value prop is coerced into a string '[Object object]'

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.8.6 |
| System | MacOS 10.15.4 |
| Browser | Chrome 80.0.3987.149 |

**Comment by zombieJ** [comment]
Thanks for feedback. AutoComplete copy the doc from Select. Docs is not correct which should be fixed.

**Comment by yifengd** [comment]
Why is this a documentation problem? Clearly it is possible to render inline React elements in the input field (i.e tags). The logic behind this should be exposed. What I want to do is to automatically tokenize parts of the input string as tags and leave the rest as strings:

<img width="561" alt="Screenshot 2020-03-29 at 15 27 32" src="https://user-images.githubusercontent.com/34337420/77850308-e3130700-71d1-11ea-8b18-0be67223e7f2.png">

I can achieve this for example, by abusing the tagRender prop in Select to render custom content. But this is very hacky, since the entire input is now one tag. I cannot arbitrarily customize how Select tokenizes the input, for example.

My suggestion is that we can use the value prop as an array like it is described in the original docs, so we can both customize the tokenization and the rendering.
