### ISSUE TITLE
could we export ConfigConsumer with ConfigProvider like ConfigProvider.ConfigConsumer?

### ISSUE THREAD

**Issue by ginobilee** [ant-design/ant-design#22701]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use ConfigConsumer directly, now the only way is like `import { ConfigConsumer } from 'antd/es/config-provider'` or `import { ConfigConsumer } from 'antd/lib/config-provider'`. 

my scene is, I'm developing a form engine which could use antd.Form antd other elements. I need to extend some logic in Form and FormItem class, without this api, I must split it to 'es' and 'lib' version, since I can't make sure which version users use, and different dir's ConfigProvider/ConfigConsumer does not support each other.

### What does the proposed API look like?
```js
import { ConfigProvider } from 'antd';

const { ConfigConsumer } = ConfigProvider;
```

**Comment by zombieJ** [comment]
It may not export directly since we do not want user to access this internal component. But you can still import ConfigConsumer by `antd/lib/config-provider/...`.

**Comment by ginobilee** [comment]
> It may not export directly since we do not want user to access this internal component. But you can still import ConfigConsumer by `antd/lib/config-provider/...`.

yes, but this way I must confirm which dir user uses, meaning `lib` or `es`. Anyway thanks
