### ISSUE TITLE
treeSelect在表单中未正常显示title

### ISSUE THREAD

**Issue by WinterWoods** [ant-design/ant-design#22716]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/congshujuzhijieshengcheng-ant-design-demo-u0dql)

### Steps to reproduce
对表单setFieldsValue后,TreeSelect未显示title值

### What is expected?
期望设置setFieldsValue后,TreeSelect组件显示title值

### What is actually happening?
现在显示的是value

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12 |
| System | win10 |
| Browser | chrome 80 |

**Comment by hengkx** [comment]
Duplicate #22553
