### ISSUE TITLE
Table的批量选择50条以上就很卡了

### ISSUE THREAD

**Issue by zdxxxxxx** [ant-design/ant-design#2271]
### 本地环境

- "antd": "^1.1.0":
- “windows”:10
- chrome:51.0.2704.106 

### 你做了什么？

使用antd的Table组件,批量选框，分页，pagesize

### 你期待的结果是：

批量选择速度要快

## 实际上的结果：

每页50条，批量选择明显有延迟

### 可重现的在线演示

暂无线上代码

**Comment by dyf2015** [comment]
确实有点卡

**Comment by afc163** [comment]
rc-table 做了一点优化，有性能问题直接看看代码有没有问题，帮忙 PR 吧。
