### ISSUE TITLE
Typography.Text 在 Form 中样式问题

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#22728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dumi-demo-8ev85)

### Steps to reproduce
1、打开 demo.tsx
2、点击表单第一个字段 文本 后面的编辑 Icon

### What is expected?
样式正常

### What is actually happening?
样式异常

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | latest |
| System | mac |
| Browser | mac edge |

---
text 类型源码在 https://github.com/crazyair/father-doc-yform/blob/master/packages/yform/src/YForm/component/Typography.tsx

**Comment by zombieJ** [comment]
Text 是一个轻量级内联组件，本意不是用来放到 Form.Item 里做控制校验。虽然感觉是可以优化一下。

**Comment by xrkffgg** [comment]
```
div.ant-typography-edit-content {
  left: -12px;
  margin-top: -5px;
  margin-bottom: calc(1em - 4px - 2px);
}
```

这是默认样式，你可以在你项目中，引入自定义 css 

通过修改这几个值，来让你的样式正常

**Comment by crazyair** [comment]
> ```
> div.ant-typography-edit-content {
>   left: -12px;
>   margin-top: -5px;
>   margin-bottom: calc(1em - 4px - 2px);
> }
> ```
> 
> 这是默认样式，你可以在你项目中，引入自定义 css
> 
> 通过修改这几个值，来让你的样式正常

要改默认？这样好吗

**Comment by xrkffgg** [comment]
https://ant.design/components/typography-cn/#components-typography-demo-interactive

官网中，可交互的 Demo  中，为了保持点击前后的统一，做了这个样式，在你项目中，你可以自己根据自己需要调整

**Comment by xrkffgg** [comment]
改默认多正常啊

**Comment by xrkffgg** [comment]
当然 如果要改，最好是加个 ID ，这样只改你需要的地方，其他地方还是默认的

**Comment by crazyair** [comment]
> 当然 如果要改，最好是加个 ID ，这样只改你需要的地方，其他地方还是默认的

恩 先这样弄吧
