### ISSUE TITLE
treeselect when click select， show error

### ISSUE THREAD

**Issue by liuhongmeichirstina** [ant-design/ant-design#22724]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce
1 代码使用方式
<TreeSelect
         key={index}
          showSearch
          style={{ width: '100%' }}
          value={(dcResourceUris && dcResourceUris[0]) || ''}
          dropdownStyle={{ maxHeight: 220, overflow: 'auto' }}
          placeholder="选择一个文件夹或者文件"
          treeIcon
          allowClear
          treeNodeLabelProp={'value'}
          loadData={this.onLoadData}
         onChange={value => this.changeProps('dcResourceUris', [value])}
>
      {this.renderTreeNodes(resoureDataInfo)}
</TreeSelect>

renderTreeNodes的返回：

return (
            <TreeNode
                 icon={<MyIcon type={isOpen ? 'filedir-open' : 'filedir-close'} />}
                 title={item.title}
                 value={item.key}
                 key={key}
         {this.renderTreeNodes(item.children, searchTreeValue, flag)}
            </TreeNode>

叶子节点返回：
return <TreeNode icon={<MyIcon type="file" />} key={key} value={item.key} title={item.title} isLeaf={true} />;
         

### What is expected?
点击下拉能正常展示树结构，但是现在报错，尝试过antd 3.6.6版本，是没问题的，之后的版本都有这个问题

### What is actually happening?
TreeNode.js?96be:454 Uncaught TypeError: Cannot read property 'prefixCls' of null
     at TreeNode.render (TreeNode.js?96be:454)
     at finishClassComponent (VM85236 react-dom.development.js:14400)
     at updateClassComponent (VM85236 react-dom.development.js:14355)
      at beginWork (VM85236 react-dom.development.js:15222)
    at performUnitOfWork (VM85236 react-dom.development.js:18789)
    at workLoop (VM85236 react-dom.development.js:18829)
    at HTMLUnknownElement.callCallback (VM85236 react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (VM85236 react-dom.development.js:199)
     at invokeGuardedCallback (VM85236 react-dom.development.js:256)
    at replayUnitOfWork (VM85236 react-dom.development.js:18061)
 
 

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | 16.8.1 |
| System | windows |
| Browser | chrome 75.0.3770.80 |

---
链接在内网 无法外部访问

**Comment by chinabaijunjie** [comment]
我也是同样遇到了这个问题
![image](https://user-images.githubusercontent.com/33617869/78015239-bbf83900-737b-11ea-8280-f8d4cf63312f.png)
![image](https://user-images.githubusercontent.com/33617869/78015396-efd35e80-737b-11ea-9518-ef06763aff94.png)
