### ISSUE TITLE
Instructions on removing Momentjs from DatePicker, dont show how to create new one like LuxonJS

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#22725]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/replace-moment#DatePicker](https://ant.design/docs/react/replace-moment#DatePicker)

### Steps to reproduce
Currently if one wants to use a lib like LuxonJS for DatePicker, there is no guide/instructions for it.
The guide in [current documentation](https://ant.design/docs/react/replace-moment#DatePicker) simply shows how to use the prebuilt integration for DayJS. It doesn't show how to create a custom integration.

### What is expected?
1. Provide prebuilt integration for LuxonJS (like the one for DayJS)
2. Provide instructions on how to create custom integrations (not just switching to prebuilt one)

### What is actually happening?
Currently instructions only show how to *switch* between momentjs and dayjs. they dont show how to create one from scratch

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | firefox 74 |

**Comment by zombieJ** [comment]
Remove moment is a breaking change that we may not do that.

Merge into #22732

**Comment by pdeva** [comment]
this bug is *not* about removing moving mometjs.

It is about providing instructions for how to use other datetime libs with DatePicker. Your current docs only show how to use DayJS but dont provide instructions on how to integrate any other library

**Comment by afc163** [comment]
@pdeva see ##22732
