### ISSUE TITLE
当table的expandedRowRender是input，并且重写了components->body->row，input只能输入一个字符。

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#22722]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table扩展行是input，并且需要重写行拖拽排序时遇到此问题；复现此问题：https://codesandbox.io/s/exciting-fog-pcrq8

### What does the proposed API look like?
感觉是，每次一输入就会触发render，导致input失去焦点。

**Comment by hengkx** [comment]
```js
expandedRowRender: (record, index) => (
            <Input
              autoFocus
              value={record.name}
              onChange={({ target: { value } }) => this.onChange(value, index)}
            />
          ),
```
你给input设置了`autoFocus`所以焦点 会聚焦到最后一个input 正常在最后输入是没有问题的

**Comment by zhangzhi93** [comment]
> ```js
> expandedRowRender: (record, index) => (
>             <Input
>               autoFocus
>               value={record.name}
>               onChange={({ target: { value } }) => this.onChange(value, index)}
>             />
>           ),
> ```
> 
> 你给input设置了`autoFocus`所以焦点 会聚焦到最后一个input 正常在最后输入是没有问题的

额，现在情况是这样的，加上autoFocus虽然可以一直输入了，但是不能输入中文，你可以试一下。如果不加autoFocus每次只能输入一个字符。有链接的https://codesandbox.io/s/exciting-fog-pcrq8，你可以打开先看一下

**Comment by zhangzhi93** [comment]
```
body: {
      row: props=>this.tableBodyRow(props)
 }
```
找到问题所在了，这里用错了，导致每次都重新渲染了~
