### ISSUE TITLE
table文档页报错好多天了，什么时候能修复下

### ISSUE THREAD

**Issue by yunuo-tech** [ant-design/ant-design#22729]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
打开控制台即可看到

### What is expected?
修复

### What is actually happening?
修复

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 18 |
| System | macos |
| Browser | chrome |

**Comment by yoyo837** [comment]
没有看到报错，你截个图看看？

**Comment by yunuo-tech** [comment]
> 没有看到报错，你截个图看看？

![image](https://user-images.githubusercontent.com/5960864/77871718-879b5480-7277-11ea-915b-50912900e61a.png)
应该不是网络的事，挂不挂代理都报这个加载错误，清空缓存也是，别的页面没事。

**Comment by yoyo837** [comment]
我个人这边确实白白净净的没问题，看不太懂是为什么！

**Comment by hengkx** [comment]
@yunuo-tech 我这边没有加载 你报错的哪些文件 ，一切正常
![image](https://user-images.githubusercontent.com/8358236/77874853-e2857980-7280-11ea-9b60-87af5f11905b.png)

**Comment by xrkffgg** [comment]
同没有看到。。。。

![image](https://user-images.githubusercontent.com/29775873/77896146-66a02700-72aa-11ea-8902-e4e66d145006.png)

**Comment by zombieJ** [comment]
看起来像是你的网络问题。开个代理看看。
