### ISSUE TITLE
Select 自定义输入内容调用form.resetForm清空不了

### ISSUE THREAD

**Issue by lycandjava** [ant-design/ant-design#2273]
### windows

- antd 版本: 1.5.0
- 操作系统及其版本：Win10 
- 浏览器及其版本: chrome

### 你做了什么？
```jsx 
 <FormItem label="xxx：" labelCol={{ span: 8 }} wrapperCol={{ span: 16 }}>
   <Select multiple size="default" placeholder="xxx"  {...getFieldProps('xxxx')}  notFoundContent="未检索到数据">
              {this.state.dict_101.map(d=><Option key={d.name}>{d.name}</Option>)}
    </Select>
 </FormItem>  
this.props.form.resetFields();
```

问题类似官网：http://ant.design/components/form
校验部分喜欢的颜色

### 你期待的结果是：
自定义输入的内容在调用this.props.form.resetFields();时候可以清空

**Comment by ddcat1115** [comment]
如果需要随意输入内容，请用 `tags `，而非 `multiple`

**Comment by lycandjava** [comment]
3Q

**Comment by lycandjava** [comment]
@ddcat1115 但是用户输入之后，如果不选择，直接让他失去焦点，还是情况不了呢，怎么办？

**Comment by ddcat1115** [comment]
好像多选模式下（包括 `multiple` 和 `tags`）对于自己输入 但未选中的内容确实没法控制，有点误导， @yiminghe  看下这里rc-select能优化下吗？

**Comment by yiminghe** [comment]
需要 demo

**Comment by ddcat1115** [comment]
http://codepen.io/ddcat1115/pen/YWxrdk?editors=0011  输入一些内容但不选中选项，也不回车，直接离焦，这部分内容会保留在 select 框中，看起来是value的一部分，但实际不是，也不能通过 setState 的方式去掉

**Comment by afc163** [comment]
按照 http://select2.github.io/examples.html#tags，输入未选中直接 blur，应该清空。

**Comment by ljy-xian** [comment]
想问一下随意输入可以设置为单选吗？ 使用tags默认会转为多选
