### ISSUE TITLE
Volunteer for DatePicker date lib generate support

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#22732]
- [x] date-fns #21866
- [ ] luxon #22725

**Comment by fireairforce** [comment]
I will work on this~

**Comment by hihuz** [comment]
Hello :wave: 

We are using antd and luxon in our project and have recently written our own integration (generate config) for it.

I can see there was some interest for it in this issue, If you are still interested, we could open a pull request and try to work from there.

One thing to keep in mind is that luxon has no notion of localized weeks, it only uses and handles ISO weeks, so there would be some differences with the other integrations for that (start of week is Monday for all locales). Although I suspect luxon users working with weeks are already aware of that, and we could document a way to override this default with a locale <> start of week mapping.

Let me know what you think when you get the chance.

Thank you for all your great work on antd!
