### ISSUE TITLE
antd中Tab选中状态有一条蓝线，这个怎么去掉

### ISSUE THREAD

**Issue by wb-lbl360107** [ant-design/ant-design#22747]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://miygz.csb.app/](https://miygz.csb.app/)

### Steps to reproduce
点击tab下方，会出现一条蓝线

### What is expected?
想把蓝线去掉

### What is actually happening?
蓝线一直存在，点击的时候总会出现，目前没办法解决

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.1 |
| System | mac10.14.6  |
| Browser | 谷歌80.0.3987.149 |

**Comment by wb-lbl360107** [comment]
tab点击出现蓝线问题

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/77893005-f5f70b80-72a5-11ea-9495-857a33100fed.png)

你是说这个？`.ant-tabs-ink-bar`

**Comment by xrkffgg** [comment]
😂😂😂 正常样式啊，表示当前选择嘛

**Comment by xrkffgg** [comment]
如果你要隐藏的话，可以在项目中加入 自定义样式\
```
.ant-tabs-ink-bar {
    visibility: hidden;
}
```

**Comment by wb-lbl360107** [comment]
![image](https://user-images.githubusercontent.com/62874767/77899214-f8119800-72ae-11ea-80cf-2e85d7ebdaaf.png)
zhe这条蓝线

**Comment by wb-lbl360107** [comment]
> ![image](https://user-images.githubusercontent.com/6134547/77893005-f5f70b80-72a5-11ea-9495-857a33100fed.png)
> 
> 你是说这个？`.ant-tabs-ink-bar`

![image](https://user-images.githubusercontent.com/62874767/77899274-0eb7ef00-72af-11ea-836e-2efdcfe0df6e.png)
这条蓝线

**Comment by yoyo837** [comment]
没有这条蓝线，检查下你自己的代码 或者提供复现！

**Comment by wb-lbl360107** [comment]
> 你的复现里没有这条蓝线，检查下你自己的代码 或者提供可复现链接！

![img](https://user-images.githubusercontent.com/62874767/77899878-cbaa4b80-72af-11ea-9dc5-77c44e9bf33e.gif)
这是antd官网的

**Comment by jimtang9527** [comment]
这是个明显的bug，很容易重现的

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/22337

@afc163  

![image](https://user-images.githubusercontent.com/29775873/77900113-23e14d80-72b0-11ea-91aa-c46eeaf1aa4b.png)

**Comment by wb-lbl360107** [comment]
> #22337
> 
> @afc163
> 
> ![image](https://user-images.githubusercontent.com/29775873/77900113-23e14d80-72b0-11ea-91aa-c46eeaf1aa4b.png)

这个怎么修复

**Comment by yoyo837** [comment]
原来是点内容区域噢

**Comment by yoyo837** [comment]
需要 css outline 去掉

**Comment by yoyo837** [comment]
@xrkffgg 不是同一个问题吧？

**Comment by MrHeer** [comment]
outline？

**Comment by wb-lbl360107** [comment]
> 需要 css outline 去掉

谢谢，解决了

**Comment by MrHeer** [comment]
I want to fix it.

**Comment by lovelyJason** [comment]
蓝线不是本来就应该的吗,点击不给蓝线,那用户体验那么差

**Comment by yoyo837** [comment]
你可能也理解我前面一开始理解的线了，不是那个！

**Comment by a1473838623** [comment]
.ant-menu-light.ant-menu-horizontal>.ant-menu-item-selected::after {
    border-bottom-color: white !important;
}

.ant-menu-light.ant-menu-horizontal>.ant-menu-item-active::after {
    border-bottom-color: white !important;
}

**Comment by ghost613bb** [comment]
ant-tabs-nav::before {
  border-bottom: none !important;
}
