### ISSUE TITLE
[4.0] table使用fixed header和Dropdown一起getPopupContainer无效

### ISSUE THREAD

**Issue by lich-yoo** [ant-design/ant-design#22744]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudingbiaotou-ant-design-demo-4yrix)

### Steps to reproduce
点击 action 列 More (Dropdown)，然后滚动 table，发现 getPopupContainer 无效

### What is expected?
Dropdown 正确滚动

### What is actually happening?
Dropdown 即使设置 getPopupContainer 也无效

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | lastest |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/gudingbiaotou-ant-design-demo-gjsty
