### ISSUE TITLE
listType为picture-card的Upload组件，在win10的chrome浏览器中，多次上传，会导致浏览器卡死

### ISSUE THREAD

**Issue by chenhebing** [ant-design/ant-design#22741]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhaopianqiang-ant-design-demo-46pgp)

### Steps to reproduce
windows下，多次上传，删除操作后

### What is expected?
浏览器不会卡死

### What is actually happening?
chrome浏览器会出现卡死的情况，只能选择关机重启

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
你能找别的电脑也测试一下吗，排除是你本地环境的问题。

**Comment by ZeroJsus** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### Reproduction link
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/zhaopianqiang-ant-design-demo-46pgp)
> 
> ### Steps to reproduce
> windows下，多次上传，删除操作后
> 
> ### What is expected?
> 浏览器不会卡死
> 
> ### What is actually happening?
> chrome浏览器会出现卡死的情况，只能选择关机重启
> 
> Environment	Info
> antd	4.1.0
> React	16.13.0
> System	win10
> Browser	chrome

大佬问题 你解决了么 我这里客户也遇到了 相同的问题

**Comment by chenhebing** [comment]
> 你能找别的电脑也测试一下吗，排除是你本地环境的问题。

我这边是mac，是我们的测试同学反馈的问题，并且是多个同学，稳定复现。卡死后任务管理器都打不开

**Comment by chenhebing** [comment]
卡死前的状态是唤起系统文件选择器的步骤卡死了

**Comment by yoyo837** [comment]
稳定复现的话几次上传几次删除会出现？

**Comment by yoyo837** [comment]
考虑下是否和`<input accept="image/*" />` 这个 `accept`的范围在某些电脑上文件过多可能也会。

**Comment by chenhebing** [comment]
> 稳定复现的话几次上传几次删除会出现？

不等 之前反馈的是10+次 后面我给他那个sandbox的地址 他三次就挂了

但是并不是所有的windows能稳定复现

**Comment by chenhebing** [comment]
> 考虑下是否和`<input accept="image/*" />` 这个 `accept`的范围在某些电脑上文件过多可能也会有关系。

我自己的项目里面accept 只有 image/jpg, image/png, image/jpeg

目前的问题是 listType 为 picture-card会出现这个问题，为默认的text不会

**Comment by yoyo837** [comment]
@chenhebing 再找一下稳定复现的电脑环境，把他一直测试默认打开的文件夹内的符合accept的文件删除到只剩一个，再多次尝试看看能不能复现？

**Comment by chenhebing** [comment]
> @chenhebing 再找一下稳定复现的电脑环境，把他一直测试默认打开的文件夹内的符合accept的文件删除到只剩一个，再多次尝试看看能不能复现？

好的 感谢

**Comment by chenhebing** [comment]
> @chenhebing 再找一下稳定复现的电脑环境，把他一直测试默认打开的文件夹内的符合accept的文件删除到只剩一个，再多次尝试看看能不能复现？

找我们测试同学，使用codeSandbox的测试，发现没有再出现卡死的情况。现在已经不能稳定复现了，我先关了，后面如果还会有类似的问题，再打开吧。
