### ISSUE TITLE
请添加功能 - 将选项列固定在表格最右边列的API在antd-design里面Table组件中

### ISSUE THREAD

**Issue by Taiguofen** [ant-design/ant-design#22749]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 将选项列固定在表格最右边列的API在antd-design里面Table组件中 ,由于在table组件中的选择功能的配置 rowSelection 中所提供的fixed无法正确地将选项列固定在右边。

### What does the proposed API look like?
在table组件中的选择功能的配置 rowSelection 中添加 fixed："right"

**Comment by afc163** [comment]
目前不支持选择列放在右边，你可以尝试构造一个自定义列来做选择。

**Comment by luoyifanff** [comment]
不能将rowSelection作为一个普通列吗

**Comment by luoyifanff** [comment]
> 目前不支持选择列放在右边，你可以尝试构造一个自定义列来做选择。
不能将rowSelection作为一个普通列吗
