### ISSUE TITLE
有支持react-native的计划吗

### ISSUE THREAD

**Issue by walter211** [ant-design/ant-design#2275]
看了文档不错，想用

**Comment by yuzhouisme** [comment]
我觉得没必要...

**Comment by yiminghe** [comment]
请期待 ant design mobile，两个月后开源

**Comment by Feit** [comment]
@yiminghe 现在能参与内测吗？

**Comment by benjycui** [comment]
Published: http://mobile.ant.design/

**Comment by feit** [comment]
awesome！

**Comment by yuzhouisme** [comment]
awesome! 
but 如果写移动端，我习惯用react-native，如果写响应式，我好像挺接受在antd上使用xs={x},sm={x}这种...
最后，awesome!
