### ISSUE TITLE
升级的antd4.1.0 table组件表头样式没了

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design#22750]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
显示table组件表头样式

### What does the proposed API look like?
添加table组件表头样式

**Comment by XSmarter** [comment]
重新删除node_modules 重新下载后就有样式了

**Comment by y-takey** [comment]
I have same issue. (maybe #22737 too)
but i cloudn't reproduce it on codesandbox. the issue happens on my project.

a output html is below. i guess the cause is because `thead` is not given a `ant-table-thead` class.

```html
<div class="ant-table-header" style="overflow: hidden;">
  <table style="table-layout: fixed;">
    <colgroup>
      <col style="width: 317px; min-width: 317px;">
      <col style="width: 318px; min-width: 318px;">
      <col style="width: 0px; min-width: 0px;">
    </colgroup>
    <thead>
      <tr>
        <th class="ant-table-cell">Key</th>
        <th class="ant-table-cell">Name</th>
      </tr>
    </thead>
  </table>
</div>
```

**Comment by wygkzqa** [comment]
I have same issue

**Comment by wleven** [comment]
删除node_modules 没有用哦

**Comment by wygkzqa** [comment]
> 删除node_modules 没有用哦

看你下你的 rc-table version，最新版本修复了这个样式问题

**Comment by y-takey** [comment]
@wygkzqa Thank you very much!

remove `node_modules` and `yarn.lock`, then exec `yarn install`, so the issue is fixed. (`rc-table` version is 7.3.8 -> 7.3.14)

**Comment by greatghoul** [comment]
I have same issue ⬆️
