### ISSUE TITLE
Form.Item and Select with multiple: Cannot read max rules correctly

### ISSUE THREAD

**Issue by luxurya111** [ant-design/ant-design#22763]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ig9p2)

### Steps to reproduce
Just used Form.Item with Multiple Select and max rules but not work correctly..

### What is expected?
This work correctly..

### What is actually happening?
If the max rule is applied, an error occurs even if you select any items.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.12.0 |
| System | CentOS 7 |
| Browser | Chrome 80.0.3987.149 (64bit) |

**Comment by afc163** [comment]
`max` will validate string length in your case, or max numberic value when `type: 'number'`, it cannot works for selected item count in that way.

**Comment by luxurya111** [comment]
![image](https://user-images.githubusercontent.com/61316679/77924838-29a25780-72df-11ea-897d-98e6f4863c36.png)
according to documents, max will read Max length of string, number, array. am I misreading this?

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-4jfp1

You have to define `type: 'array'`.

**Comment by luxurya111** [comment]
oh I see, thank you for commented!
