### ISSUE TITLE
点击Tabs里面的内容，边框会出现蓝色选中样式

### ISSUE THREAD

**Issue by davidcun** [ant-design/ant-design#22760]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ocje0)

### Steps to reproduce
1、点击第一个TabPane里面的表格内容，或者第二个的TabPane按钮的右边
2、出现蓝色边框选中样式

### What is expected?
不应该出现此样式

### What is actually happening?
出现了蓝色边框

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.0 |
| System | mac os |
| Browser | chrome  lastest |

**Comment by afc163** [comment]
Fixed in #22752, will be released in this weekend.
