### ISSUE TITLE
升级到最新的React 15.20时，浏览器打印日志提示react-unknown-prop的error

### ISSUE THREAD

**Issue by uinika** [ant-design/ant-design#2276]
### Webpack + Babel + React + Redux

- antd 版本: 1.6.3
- 操作系统及其版本：Ubuntu 16.04
- 浏览器及其版本: Chrome 50

**Comment by afc163** [comment]
#2276

麻烦先看下有没有重复的问题。

**Comment by uinika** [comment]
我想了解一下，这个问题，你们计划在哪个版本里进行修复？
