### ISSUE TITLE
如何通过后端的字符串直接渲染一个组件？

### ISSUE THREAD

**Issue by Imagine-Tom** [ant-design/ant-design#22766]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比方说后端过来的字段为 item.type = Form
我想直接拿这个 <item.type></item.type>
渲染出一个 From组件。
而不是if(item.type === Form){
return <Form></Form>

}
请问有人有这样尝试过吗？
因为是动态的数据。可配置的。
所以我想直接这样做。
不知道怎么样才可以不用判断字段如return 组件。

### What does the proposed API look like?
可以直接使用后端的字符串渲染组件。

**Comment by Imagine-Tom** [comment]
@afc163 
你好 请问这个问题怎么了  呜呜呜

**Comment by yoyo837** [comment]
个人感觉你跨度有点大，先学好基础噢！

**Comment by Imagine-Tom** [comment]
> 个人感觉你跨度有点大，先学好基础噢！

const Component = { Select, Card, Form, Button };
const  = 'Button';
const Com = Component[name];
大概这样- -
