### ISSUE TITLE
更新antd 4之后，TreeSelect报错，IntrinsicAttributes & IntrinsicClassAttributes<TreeSelect<{}>

### ISSUE THREAD

**Issue by PandaJJ5286** [ant-design/ant-design#22776]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
升级antd 4.1.0 后出现如下报错
                                        <TreeSelect
                                            value={this.state.currentCatalog}
                                            placeholder="Please select"
                                            treeData={data.options}
                                            onChange={(e, label) => this.setCatalog(e, label, data.paramsKey)}
                                        />
Type '{ value: any; placeholder: string; treeData: any; onChange: (e: any, label: any) => void; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<TreeSelect<{}>> & Readonly<{ children?: ReactNode;...'.

### What is expected?
不报错

### What is actually happening?
报错Type '{ value: any; placeholder: string; treeData: any; onChange: (e: any, label: any) => void; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<TreeSelect<{}>> & Readonly<{ children?: ReactNode;...'.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | macOS Mojave 10.14.4 (18E224) |
| Browser | chrome 80.0.3987.149 |

**Comment by PandaJJ5286** [comment]
这是ts下报的类型错误，而且需要依赖的东西太多了，报错的信息就是TreeSelect传任何一个属性都会报错，这种错误应该不需要复现吧，报错已经很清晰了。


原始邮件
发件人:Ant Design GitHub Botnotifications@github.com
收件人:ant-design/ant-designant-design@noreply.github.com
抄送:Panda Zhanghjzhang89@126.com; Mentionmention@noreply.github.com
发送时间:2020年3月31日(周二) 21:49
主题:Re: [ant-design/ant-design] 更新antd 4之后，TreeSelect报错，IntrinsicAttributes  IntrinsicClassAttributesTreeSelect{} (#22776)


Hello @PandaJJ5286. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
你好 @PandaJJ5286, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by yoyo837** [comment]
应该不是所有的人不行，不然会出现很多报告者。所以应该是你的情况下不行，请提供复现方便快速解决。

**Comment by PandaJJ5286** [comment]
您好，我将typescript版本改成了3.7.5，修复了该问题，建议在官方升级文档上，写明所需最低的ts版本，我这边之前的版本是2.9.2，谢谢帮助


原始邮件
发件人:Amumunotifications@github.com
收件人:ant-design/ant-designant-design@noreply.github.com
抄送:Panda Zhanghjzhang89@126.com; Mentionmention@noreply.github.com
发送时间:2020年4月1日(周三) 09:19
主题:Re: [ant-design/ant-design] 更新antd 4之后，TreeSelect报错，IntrinsicAttributes  IntrinsicClassAttributesTreeSelect{} (#22776)


应该不是所有的人不行，不然会出现很多报告者。所以应该是你的情况下不行，请提供复现方便快速解决。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/22845

**Comment by xinkule** [comment]
> #22845

这个问题应该很多用老版本的 typescript 都会用到，Form 组件里尤其明显，没大量爆出的原因我猜测是大部分人都没用 ts 写 antd，关于 ts 的版本问题是否写在 v3 到 v4 的迁移文档里比较好？BTW，最新的 CRA 里 ts 的依赖版本也没达到文档上标注的 3.8.4，而是 3.7.5，不知道会不会有额外问题

**Comment by Lizhooh** [comment]
@afc163 
同样的情况，用 antd 4，typescript 更新到 3.9.5，也报错，服了。用  3.x 没有问题，升级到 4.x 一堆问题。

![微信截图_20200625101624](https://user-images.githubusercontent.com/19299088/85645728-272c7f80-b6cd-11ea-929a-20745db8f474.png)

**Comment by Lizhooh** [comment]
类型“IntrinsicAttributes & IntrinsicClassAttributes<Select<SelectValue>> & Pick<Readonly<SelectProps<SelectValue>> & Readonly<{ children?: ReactNode; }>, "children" | "mode"> & Partial<...> & Partial<...>”上不存在属性“style”。
