### ISSUE TITLE
Can't reference HTML element of TextArea in v4

### ISSUE THREAD

**Issue by omniphx** [ant-design/ant-design#22770]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-dfvp3)

### Steps to reproduce
1. Create a ref of a TextArea component
2. Try to run the following piece of code: `window.getComputedStyles(textAreaReference.current)`
3. You should get the error: `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

### What is expected?
In version 3, the following code worked fine:
`window.getComputedStyles(textAreaReference.current.textAreaRef)`

In version 4, it appears that `textAreaRef`is no longer a property on the `<Input.TextArea/>` component. Is there another way to find the HTML element reference?

### What is actually happening?
Receiving the error: `Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.`

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | OSX 10.14.6 |
| Browser | Chrome Version 80.0.3987.149 |

**Comment by zombieJ** [comment]
`textAreaRef` also not work in latest v3. Do not rely on internal instance prop since we do not guarantee this.

If you need access internal dom directly, you can add id for `querySelector` or `findDOMNode` instead.

**Comment by Lizhooh** [comment]
@zombieJ findDOMNode is deprecated

**Comment by zombieJ** [comment]
Before React provide official fully functional replacement, you can safe to use `findDOMNode`.
