### ISSUE TITLE
codesandbox links not redirecting in antd v3 DOCS

### ISSUE THREAD

**Issue by rahuls360** [ant-design/ant-design#22774]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/grid/#header](https://3x.ant.design/components/grid/#header)

### Steps to reproduce
Open https://3x.ant.design/components/grid/#header (Antd 3x)
Click on any codesandbox link
Stuck on you are being redirected

### What is expected?
New codesandbox link to test the code

### What is actually happening?
stuck on redirecting page

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | NA |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
#22688 @Rustin-Liu

**Comment by Rustin-Liu** [comment]
I will fix it tonight.

**Comment by zombieJ** [comment]
Seems codesandbox fixed this issue.

@rahuls360 , could you try again?

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/3x.ant.design/commit/d6ff243e90fc86fa6283a02485dee58da00fd508
