### ISSUE TITLE
Table columns 大小变化

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#22777]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jincouxing-ant-design-demo-32z9i)

### Steps to reproduce
在 columns 表头内包含 sorter: true，设置 Table 的 size="middle" or size="small" 时，表头反而**变大**了

### What is expected?
https://codesandbox.io/s/jincouxing-ant-design-demo-32z9i

### What is actually happening?
https://codesandbox.io/s/jincouxing-ant-design-demo-32z9i

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by kaoding** [comment]
在 columns 里加了 filters:[]后，设置 Table 的 size="middle" or size="small" 时，表头不**变小**了

**Comment by kaoding** [comment]
https://codesandbox.io/s/jincouxing-ant-design-demo-zg6pe

**Comment by AshoneA** [comment]
@afc163  这个 4.0 中表头中带有搜索的话 Table size 调整感觉没有变化的应该算是 bug 吧？如果是的话我一起修掉了。
https://codesandbox.io/s/jincouxing-ant-design-demo-mhjq4

**Comment by kaoding** [comment]
> @afc163 这个 4.0 中表头中带有搜索的话 Table size 调整感觉没有变化的应该算是 bug 吧？如果是的话我一起修掉了。
> https://codesandbox.io/s/jincouxing-ant-design-demo-mhjq4

这个是 v4.1.0 引入的bug，v4.0.4没有这个bug

https://codesandbox.io/s/jincouxing-ant-design-demo-zg6pe

**Comment by AshoneA** [comment]
@kaoding  嗯，带 `sorter: true` 有 bug 是 4.1 的，4.0 是带 filter 之后 size 会不起作用。

**Comment by afc163** [comment]
> @afc163 这个 4.0 中表头中带有搜索的话 Table size 调整感觉没有变化的应该算是 bug 吧？如果是的话我一起修掉了。

是 bug。
