### ISSUE TITLE
修改state数据后是刷新了整个页面并不是局部刷新？

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design#22775]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
例如一个页面中有一表格1000行数据未做分页，绑定model修改其中一条数据后整个界面的表格被重新刷新了一次？这是不是太消耗资源了，还不如我直接写jquery修改表格中的某列数据

### What does the proposed API look like?
期望能实现局部刷新，或者框架有这个功能我没找到？

**Comment by yoyo837** [comment]
局部刷新具体哪一部分完全是由组件封装的情况来说的。
可以提比如哪里性能不够好，渲染次数过多或者不高效。和jquery对比是没必要的，jquery 和 React 完全是不同思维的两种方式，jquery 是按过程来的，React 按申明式的结果。

**Comment by laolaolulu** [comment]
> 可以重新放置局部
> 性能完全好，渲染次数过多或者不高效。和jquery比较是没必要的，jquery和React完全是不同思维的两种方式，jquery是按过程来的，根据申明式的结果进行反应。

好吧，我还活在操作dom时代，不知道react是如何渲染的

**Comment by yoyo837** [comment]
内存维护虚拟DOM，对比实际DOM，差异更新。

先close了。

**Comment by laolaolulu** [comment]
那比如我一个界面有10个折线图是绑定到的同一个state，而每个折线图有1000条数据；而我新增了state中某个折线图的数据，那重新渲染时并没有我想象中第一次那样消耗资源？
