### ISSUE TITLE
Input 光标聚焦问题 在input 1聚焦，鼠标左键按下，然后滑动到input2，放开鼠标左键，光标自动聚焦到input2

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#22779]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
1、在代码演示的基本使用那个控件聚焦，鼠标左键按下
2、滑动到右侧的第一个Large Size Input输入框，放开鼠标左键，光标就聚焦到了这里

### What is expected?
鼠标左键聚焦，不会随着鼠标滑动而聚焦

### What is actually happening?
鼠标左键聚焦现在随着鼠标滑动而聚焦

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | Win7 64位 |
| Browser | 版本 81.0.4044.69（正式版本）beta （64 位） |

---
在上述情况下，我在表格里面使用Input后，发现，同一行，如果两个Input靠在一起，input1和input2，如果鼠标左键全部选中input2后，不小心滑倒input1，就会修改到input1的值。用户体验较差（但是如果只引入Input，并排放一起，又不会重现）

**Comment by zombieJ** [comment]
看了一下，当 Input 使用了前后缀，防止点击失去焦点的情况，加了 `onMouseUp` 设置焦点。如果要精确判断焦点元素是不是在 Input 内来恢复焦点性价比非常低。
