### ISSUE TITLE
Table组件在列宽很大的情况下在火狐下无法进行自适应，谷歌可以

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#22780]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/phoema/pen/RwPvXjM?editors=0010](https://codepen.io/phoema/pen/RwPvXjM?editors=0010)

### Steps to reproduce
参见链接，使用火狐和谷歌分别打开
将column的width设置的很宽
谷歌浏览器能够自适应，火狐不能自适应

### What is expected?
火狐浏览器的table组件自适应问题

### What is actually happening?
谷歌浏览器能够自适应，火狐不能自适应

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12 |
| System | Windows 10 |
| Browser | 火狐浏览器 |

**Comment by afc163** [comment]
这是浏览器对 table 渲染机制的问题，antd 貌似做不了什么，建议不要这么设置，列宽度很宽时可以设置 `scroll.x` 出横向滚动条。
