### ISSUE TITLE
官网Tree组件的loanData演示代码4.1版本无效果

### ISSUE THREAD

**Issue by playedclass** [ant-design/ant-design#22786]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/](https://ant.design/components/tree-cn/)

### Steps to reproduce
loadData方法执行无效果

### What is expected?
正常显示下级

### What is actually happening?
无反应

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.0 |
| System | macos catalina |
| Browser | chrome |

**Comment by afc163** [comment]
实测没问题。

<img width="343" alt="image" src="https://user-images.githubusercontent.com/507615/78019548-81de6580-7382-11ea-8126-e94d4eade49f.png">

**Comment by playedclass** [comment]
![image](https://user-images.githubusercontent.com/3337266/78031568-4c437780-7396-11ea-8a00-b641172c118c.png)

用class的方法测试，会报这个错，
const { props } = treeNode 这句没用，应该去掉

**Comment by playedclass** [comment]
复现地址
https://codesandbox.io/s/antd-reproduction-template-re4y8

**Comment by playedclass** [comment]
顺便补充一下，原来loadData方法是用return dispatch({})，现在也是报错的，有推荐的写法吗
![image](https://user-images.githubusercontent.com/3337266/78086941-01574d80-73f2-11ea-8079-a096a7296c83.png)

**Comment by zombieJ** [comment]
v3 的异步加载是通过直接修改 treeData 实现，到了 v4 版本不在推荐使用 mutable 的操作，因而 demo 已经改过了。你可以看一下新版的 demo，实现已经变成 immutable 了。

**Comment by playedclass** [comment]
> v3 的异步加载是通过直接修改 treeData 实现，到了 v4 版本不在推荐使用 mutable 的操作，因而 demo 已经改过了。你可以看一下新版的 demo，实现已经变成 immutable 了。

现在官网的也没有变，试过这个例子吗，是不支持class了？
https://codesandbox.io/s/tree-loandata-zbgmu
