### ISSUE TITLE
Input Component inside form element  not updating 

### ISSUE THREAD

**Issue by ac4medeveloper** [ant-design/ant-design#22789]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
I am trying to get value from backend and append in Input Field but value is not updating in React. Currently I am using Ant design Forms and if input field is moved out of Form it works

### What is expected?
The expected result is that the input element should have value

### What is actually happening?
No value is seen on input field

| Environment | Info |
|---|---|
| antd | undefined |
| React | Version 16.12.0 |
| System | Win 10 |
| Browser | Chrome |

**Comment by ac4medeveloper** [comment]
Please find the Code here
https://codesandbox.io/s/antd-reproduction-template-byu74

**Comment by a3596287** [comment]
You need to edit on the top Sir.

**Comment by a3596287** [comment]
Can you see there's a reproduce link button?

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-hocbq

When you add `Input` into the `Form` and `Form.Item` and set a name for `Form.Item`, the `Input` is completely controlled by the `Form`. You need to use the Form's api to control the `Input`
