### ISSUE TITLE
select在搜索时，点击input后，无法再次点击展开下拉，除非重新获取焦点

### ISSUE THREAD

**Issue by carvinlo** [ant-design/ant-design#22783]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/5zldn)

### Steps to reproduce
select在搜索时，重置data为空，在等待搜索服务返回前，鼠标点击input，搜索结果返回后设置data重新渲染后，下拉无法再点开，除非重新让input失去焦点，再重新点击

### What is expected?
点击input后无法展开下拉

### What is actually happening?
若不重新失去焦点，再重新获取，无法点击展开下拉

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.8 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
Merge into #22736
