### ISSUE TITLE
Ability to show only next and prev buttons in pagination

### ISSUE THREAD

**Issue by keshikashviligio** [ant-design/ant-design#22791]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I'd like to hide pagination page numbers and show only next and previous buttons and pageSize swither

### What does the proposed API look like?
I try simple mode but it has input and I don't need input also, I think if there will be an option like showPageNumers (boolean default true) and we can control rendering page numbers or not

**Comment by zombieJ** [comment]
You can use css to hide `.ant-pagination-item` page element.

**Comment by keshikashviligio** [comment]
Yes, but it is not a good solution to hide and show something in react app : ))

**Comment by jadhavmanoj** [comment]
Do you have any workaround for this? 💭

**Comment by Douglasacost** [comment]
You can always use the ** itemRender** so overide the default componentes there

**Comment by icy1xtee** [comment]
what if i need more than 5 items? should i use css to add items as well?
