### ISSUE TITLE
antd 4.0 table columns 字段中 children 不能为 undefined 或者 空数组

### ISSUE THREAD

**Issue by zzswang** [ant-design/ant-design#22804]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/zzswang/pen/gOpEvgy](https://codepen.io/zzswang/pen/gOpEvgy)

### Steps to reproduce
1. 打开重现链接
2. 点击 右上方 run，观察运行结果
3. table columns 中的 姓名一列 没有显示，原因是因为 里面放了一个 undefined 的children

### What is expected?
当 column.children == undefined 时候，column 可以正确展示

### What is actually happening?
当 column.children == undefined 时候，column 无法展示

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.7 |
| System | macOS catalina 10.15.4 |
| Browser | chrome 80.0.3987.149 |

---
children 为 undefined 是有必要的，尤其是在动态计算 columns 的时候，可以减少代码

**Comment by yoyo837** [comment]
这个好像改过了，让我找找，另外你的React 16.7 太低了要求16.9以上。

**Comment by yoyo837** [comment]
ref: react-component/table/pull/430

**Comment by afc163** [comment]
应该是 bug：https://github.com/ant-design/ant-design/issues/1365#issuecomment-211206941

无论 children 是什么值，姓名这列都不应该消失。

**Comment by zzswang** [comment]
playground 里面用的是 react 16.13 版本

https://unpkg.com/react@16/umd/react.development.js
