### ISSUE TITLE
关于@ant-design/icons的尺寸在前端逻辑与设计端逻辑不一致的问题

### ISSUE THREAD

**Issue by neko0623** [ant-design/ant-design#22808]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://tva1.sinaimg.cn/large/00831rSTly1gde569feabj32xo0mgjwb.jpg](https://tva1.sinaimg.cn/large/00831rSTly1gde569feabj32xo0mgjwb.jpg)

### Steps to reproduce
我是一个设计师，一直对antdesign的icon尺寸设置问题感到很疑惑，“为什么前端程序员做出来的尺寸总是和设计稿有差距”，具体问题如下：
**前端实现**：icon尺寸使用fontsize的方式来设置（尺寸由svg坐标决定）
**设计端设计**：icon尺寸使用官方提供的icon组件来设置（尺寸由画板大小决定）
**分歧**：icon的设计画板带有出血，前端使用的svg图标则是svg实际最小像素（无出血）
**场景**：设计师使用了一个44px的icon，开发查看标注时显示icon为30*36px，于是将fontsize设置为36，等设计师验收时发现尺寸有差距，于是问“为什么不按设计稿来？…”
**配图说明**：https://tva1.sinaimg.cn/large/00831rSTly1gde569feabj32xo0mgjwb.jpg

### What is expected?
页面效果与设计稿一致。

### What is actually happening?
设计逻辑与前端实现逻辑不一致，导致验收时尺寸和位置可能有误差。

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | / |
| System | macOS Mojave 10.14.6 |
| Browser | Google Chrome 78.0.3904.108（正式版本）64位 |

---
意见和建议：是否能实现设计端与前端尺寸设置逻辑的一致性？避免不必要的误差，如设计端的icon不使用出血，或前端的svg图标字体包含出血？（不太懂前端，不清楚svg能不能这么做）

**Comment by afc163** [comment]
Ant Design 的图标规则是图标大小和文字字体大小始终保持一致，这样大多数场景不需要额外调整图标大小就能用，要做到这一点，svg 里不能留出血位，否则在同一个 font-size 下两个元素横向排版时，图标会小一号。

设计端的图标尺寸目前留了出血位（iconfont 里的图标），确实会导致图标 size 在设计稿中需要比文字大一号（比如 14px 文字配 16px 的带出血图标），**这是目前的一个设计潜规则**。我反馈给设计师看看怎么调整比较好。

**Comment by shangguanhongzhou** [comment]
1.  设计上：Ant Design 的 图标设计规范中，是需要出血位的 https://ant.design/docs/spec/icon-cn
2. 前端：可以直接引用 Ant Design 中 图标库，宽高比是1：1，https://ant.design/components/icon-cn/
3.官方图标库中的图标，设计和前端是一一对应的，都可以找的到。

**Comment by mslovy** [comment]
1）如果设计图标不留 出血位，会有什么弊端么？
2）如果遵循你说的“潜规则”，是否有统一的标准？上述例子中写到 14px 问题配 16px 出血位图标；那如果是  20px 文字是否是使用 22px 出血位的图标呢？
3）如果文字使用了 bold 加粗，则图标线条并没有被加粗，是否方法可以解决，让图标线条与加粗后的字体线条看上去一致呢？
@afc163

**Comment by Johnny-young** [comment]
> 1. 设计上：Ant Design 的 图标设计规范中，是需要出血位的 https://ant.design/docs/spec/icon-cn
> 2. 前端：可以直接引用 Ant Design 中 图标库，宽高比是1：1，https://ant.design/components/icon-cn/
>    3.官方图标库中的图标，设计和前端是一一对应的，都可以找的到。

我在antd的官网查看图标svg，为啥圆形类的图标没有空白出血位，方形类的图标会有空白出血位 呢？？？？官方的设计规范是有出血位空白的，为啥会这样？？
