### ISSUE TITLE
Any click within a Modal defined in an Input suffix will always focus the Input

### ISSUE THREAD

**Issue by DidiBear** [ant-design/ant-design#22801]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-ant-design-demo-ybdwl)

### Steps to reproduce
- Click on the Modal
- Try to edit the input in the Modal
- It will focus the outside Input instead

### What is expected?
The actions in the Modal should be considered as if it was in an unrelated component.

### What is actually happening?
Any click in the Modal will focus the Input outside.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.12 |
| System | Ubuntu 19.04 |
| Browser | Firefox 74.0, Chrome 80.0 |

---
This Input behavior works as expected in Antd 3. \
The new Input behavior is semantically fine, I am mostly seeking a turnaround, like stopping the event propagation or tweaking working component tree.

**Comment by DidiBear** [comment]
After looking [at the source here](https://github.com/ant-design/ant-design/blob/master/components/input/ClearableLabeledInput.tsx#L109), there is a `onMouseUp` hook around the input.

So this can be prevented using by wrapping the `suffix` and stopping the propagation of the event:
```tsx
<Input
  suffix={
    <span onMouseUp={e => e.stopPropagation()}>
      <Suffix />
    </span>
  }
/>
```
Cf. the forked sandbox with the fix => https://codesandbox.io/s/basic-ant-design-demo-5hmcp

**Comment by xessam** [comment]
Thanks, its working 


> After looking [at the source here](https://github.com/ant-design/ant-design/blob/master/components/input/ClearableLabeledInput.tsx#L109), there is a `onMouseUp` hook around the input.
> So this can be prevented by wrapping the `suffix` and stopping the propagation of the event:
> 
> ```tsx
> <Input
>   suffix={
>     <span onMouseUp={e => e.stopPropagation()}>
>       <Suffix />
>     </span>
>   }
> />
> ```
> 
> Cf. the forked sandbox with the fix => https://codesandbox.io/s/basic-ant-design-demo-5hmcp
