### ISSUE TITLE
Tree组件，如何设置选中

### ISSUE THREAD

**Issue by yuzhouisme** [ant-design/ant-design#2280]
### 本地环境

- antd 版本:1.1.0
- 操作系统及其版本：Safari
- 浏览器及其版本:Mac 10.11.5

### 你做了什么？

使用Tree组件，并期望通过属性改变选中项；
（我有几条数据，当我点击条目1时，树可以根据条目1的已设置的内容，来设置Tree的选中项）

我看到了补充：#638 的描述，具体如下：
补充：手动重置功能指在周期刷新的时候设置参数，而不仅仅是通过defaultCheckedKeys；defaultCheckedKeys这个接口仅能在Mount时设置参数，并不能够实时刷新

### 你期待的结果是：
可以选中某些项

## 实际上的结果：

无法更改...

期望该如何解决这个问题，谢谢！

**Comment by ddcat1115** [comment]
看下 API，可以设置 `checkedKeys`

http://codepen.io/ddcat1115/pen/rLzNzp?editors=0011

**Comment by yuzhouisme** [comment]
@ddcat1115 对哦，我的错，我关闭了这个问题，谢谢
