### ISSUE TITLE
Followed steps of "Use modularized antd" and  got a error

### ISSUE THREAD

**Issue by lucasbastianik** [ant-design/ant-design#22802]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/next-with-antd-error-sp13g)

### Steps to reproduce
- Started a new project with Next.js
- Followed the steps in the site of antd: [here](https://ant.design/docs/react/introduce).
 - Use babel-plugin-import
 - Config of .babelrc
- Got a error of module.

### What is expected?
Import components from antd without having to manually import the corresponding stylesheet. The antd babel plugin will need automatically import stylesheets.

#### Codesandbox
```
import { Row } from '../grid';
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.antd/es/row (/sandbox/.next/server/static/development/pages/index.js:225:18)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at Module../pages/index.js (/sandbox/.next/server/static/development/pages/index.js:140:69)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at Object.3 (/sandbox/.next/server/static/development/pages/index.js:191:18)
    at __webpack_require__ (/sandbox/.next/server/static/development/pages/index.js:23:31)
    at module.exports../node_modules/antd/es/button/style/index.js (/sandbox/.next/server/static/development/pages/index.js:91:18)
    at Object.<anonymous> (/sandbox/.next/server/static/development/pages/index.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

#### Localhost
```
import { Row } from '../grid';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | Mac OS |
| Browser | Chrome |

**Comment by lucasbastianik** [comment]
Maybe this https://github.com/ant-design/ant-design/issues/21094 is the next of this but I didn't see a fix or anything there.

**Comment by ThalesAvila** [comment]
I had the same problem, the antd documentation doesn't seens to help

**Comment by afc163** [comment]
https://github.com/zeit/next.js/issues/5180#issuecomment-500704225

**Comment by lucasbastianik** [comment]
About https://github.com/zeit/next.js/issues/5180#issuecomment-500704225:
- This comment is so old that lib `@zeit/next-typescript` is not even needed anymore because it is already built-in from next.

About the [Medium link](https://medium.com/anna-coding/how-to-config-ant-design-in-next-js-with-custom-theme-b704022591af) and https://github.com/hanpama/next-with-antd:
- Tried to integrate what @annacoding2020 did with @hanpama repo got the same error and I pushed to this repo: https://github.com/lucasbastianik/next-with-antd-modularized-error

I have already invested hours trying to solve this problem and tried several approaches.

**Comment by afc163** [comment]
https://github.com/zeit/next.js/tree/canary/examples/with-ant-design

**Comment by annacoding2020** [comment]
> About [zeit/next.js#5180 (comment)](https://github.com/zeit/next.js/issues/5180#issuecomment-500704225):
> 
> * This comment is so old that lib `@zeit/next-typescript` is not even needed anymore because it is already built-in from next.
> 
> About the [Medium link](https://medium.com/anna-coding/how-to-config-ant-design-in-next-js-with-custom-theme-b704022591af) and https://github.com/hanpama/next-with-antd:
> 
> * Tried to integrate what @annacoding2020 did with @hanpama repo got the same error and I pushed to this repo: https://github.com/lucasbastianik/next-with-antd-modularized-error
> 
> I have already invested hours trying to solve this problem and tried several approaches.

@lucasbastianik 

In babelrc file

[
      "import", {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": true
      }
    ]


Remove         "libraryDirectory": "es",

**Comment by annacoding2020** [comment]
@lucasbastianik 

You can try the latest update in the article below

https://annacoding.com/article/2cU5baQMXG8SV2pbxh7kO8/How-to-config-Ant-Design--in-Next.js-with-custom-theme?

**Comment by lucasbastianik** [comment]
> https://github.com/zeit/next.js/tree/canary/examples/with-ant-design

This example doesn't use modularized antd and modifyVars of less variables like a mine. The error occurs precisely on these occasions.

**Comment by EduardoLopes** [comment]
@annacoding2020's article works for me.

.babelrc should be:
```
{
  "presets": ["next/babel"],
  "plugins": [
    ["import", { "libraryName": "antd", "style": true }]
  ]
}
```

I would like to add typescript to this mix and still use [babel-plugin-import](https://ant.design/docs/react/use-in-typescript#Use-babel-plugin-import) as shown in the antd guide,  there's a way to do that using next?

**Comment by annacoding2020** [comment]
> @annacoding2020's article works for me.
> 
> .babelrc should be:
> 
> ```
> {
>   "presets": ["next/babel"],
>   "plugins": [
>     ["import", { "libraryName": "antd", "style": true }]
>   ]
> }
> ```
> 
> I would like to add typescript to this mix and still use [babel-plugin-import](https://ant.design/docs/react/use-in-typescript#Use-babel-plugin-import) as shown in the antd guide, there's a way to do that using next?
> 
> --
> Update:
> to use typescript, i just changed the file extension to .tsx and it just work, with no adicional configuration.

Ture, not other configuration with typescript

**Comment by smddzcy** [comment]
@annacoding2020 thanks for the article, it works for antd with less + custom variables.
it doesn't work if you have a 3rd-party that depends on in the project though, e.g. `@ant-design/pro-table`. I think because `@ant-design/pro-table` also requires some Antd styles itself. do you have any workaround for that?

**Comment by annacoding2020** [comment]
I can spend some time to check this

**Comment by annacoding2020** [comment]
> @annacoding2020 thanks for the article, it works perfectly for antd with less + custom variables 👍
> it doesn't work if you have another library that depends on antd though, e.g. `@ant-design/pro-table` (idk if the issue is only with this library), probably because `@ant-design/pro-table` also requires some antd styles itself. do you have any workaround for that?
> 
> for reference, here's the error and its stack trace:
> 
> ```
> @import './themes/index';
> ^
> 
> SyntaxError: Invalid or unexpected token
>     at compileFunction (<anonymous>)
>     at Module._compile (internal/modules/cjs/loader.js:895:18)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/Users/.../node_modules/antd/lib/badge/style/index.js:3:1)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>     at Module.require (internal/modules/cjs/loader.js:852:19)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at Object.<anonymous> (/Users/.../node_modules/@ant-design/pro-table/lib/component/status/index.js:8:1)
>     at Module._compile (internal/modules/cjs/loader.js:959:30)
> ```

@smddzcy   I can check this

**Comment by duan602728596** [comment]
According to the webpack configuration information `config.externals[0]` I printed, in the SSR environment, nextjs is to load the modules in node_modules in the way of commonjs.

By rewriting `config.externals[0]` method, related components of `antd` can be packaged with webpack.

This is the configuration of my project, you can refer to rewrite this configuration of `config.externals[0]`.

```javascript
const process = require('process');
const withSass = require('@zeit/next-sass');

const isDev = process.env.NODE_ENV === 'development';

module.exports = withSass({
  cssModules: true,
  cssLoaderOptions: {
    localIdentName: isDev ? '[path][name]__[local]___[hash:base64:6]' : '_[hash:base64:6]'
  },
  webpack(config, options) {
    const { rules } = config.module;
    const { use } = rules[rules.length - 1];
    const loaders = options.isServer
      ? ['css-loader/locals']
      : use.slice(0, isDev ? 2 : 1).concat(['css-loader']);

    config.module.rules.push({
      test: /.*\.less$/,
      use: [
        ...loaders,
        {
          loader: 'less-loader',
          options: {
            lessOptions: {
              javascriptEnabled: true
            },
            sourceMap: isDev
          }
        }
      ]
    });

    if (options.isServer) {
      const externalsFunc = config.externals[0];

      config.externals[0] = function(context, request, callback) {
        if (/(antd|rc-|css-animation|@ant-design)/.test(request)) {
          return callback();
        }

        return externalsFunc(context, request, callback);
      };
    }

    return config;
  }
});
```

**Comment by annacoding2020** [comment]
> ```js
> css-loader
> ```

Quickly test this solution, at least I have some errors

- // https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?

- Can't resolve 'css-loader/locals' 

My dev env:

webpack 4

less-loader > 3

**Comment by ahmetcetin** [comment]
@annacoding2020 I have upgraded less to 3.11.1 but kept less-loader @5.0.0, and left javascriptEnabled: true in webpack config, now it compiles

**Comment by codewaseem** [comment]
@ahmetcetin Can you show the config?

**Comment by codewaseem** [comment]
Hi @annacoding2020, How can I css modules with this?
