### ISSUE TITLE
Dependency clarification when using babel-import-plugin, webpack, and less imports

### ISSUE THREAD

**Issue by FoxxMD** [ant-design/ant-design#22800]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
N/A

### Steps to reproduce
Use babel-import-plugin with webpack and set `style:true` so that less files are imported modularly like so:
```
{
                libraryName: 'antd',
                libraryDirectory: 'es',
                style: true,
              }
```
With less related dependencies like:
```
less @ < 3.0.1
```

### What is expected?
Upgrading from 4.0.4 to 4.1.0 should not break anything related to loading less files for components.

### What is actually happening?
```
ERROR in ./node_modules/antd/es/drawer/style/index.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ref--11-2!./node_modules/antd/es/drawer/style/index.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):


      /* stylelint-disable-next-line function-calc-no-invalid */
      padding-right: calc(@drawer-header-close-padding - var(--scroll-bar));
    ^
Cannot read property 'numerator' of undefined
      in C:\Users\example\code\node_modules\antd\es\drawer\style\drawer.less (line 189, column 6)
 @ ./node_modules/antd/es/drawer/style/index.less 2:14-121 21:1-42:3 22:19-126
 @ ./node_modules/antd/es/drawer/style/index.js
 @ ./app/containers/Authenticated/component.js
 @ ./app/containers/App/index.js
 @ ./app/app.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./app/app.js
```

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

---
I finally solved this by upgrading my less-related dependencies to match what was in create-react-app after ejecting:
```
    "less": "^3.11.1",
```
but since I did not initially use CRA for my project I had no way of knowing this would be an issue and it was not mentioned in the docs. I had previously been at `less@^2.7.3` and found that at least `less@3.0.1` was required to solve the error. I would update the babel-import-plugin docs for antd to note that at least less 3.x is required to use `style:true`

**Comment by afc163** [comment]
Please upgrade to latest version of less, our less code are built on it and will not be compatible with old version of less.

**Comment by FoxxMD** [comment]
Yes I am aware now 😅 The point of my issue was to suggest that a minimum version of `less` is specified in the [babel-plugin-import](https://ant.design/docs/react/use-with-create-react-app#Use-babel-plugin-import) section of the docs to help others.
