### ISSUE TITLE
DatePicker format doesn't behave correctly for `L` and `l`

### ISSUE THREAD

**Issue by patrickomeara** [ant-design/ant-design#22810]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-48p7o)

### Steps to reproduce
set browser locale to `en_AU` or anything non US. Refresh codesandbox. 

### What is expected?
format should be dd/mm/YYYY

### What is actually happening?
always US format

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

---
this was working fine in v3

**Comment by patrickomeara** [comment]
Sorry, I just hadn't saved the codesandbox. Thought it would autosave.

https://codesandbox.io/s/antd-reproduction-template-48p7o

**Comment by yoyo837** [comment]
FYI https://codesandbox.io/s/antd-reproduction-template-9jocq

**Comment by zombieJ** [comment]
![Kapture 2020-04-02 at 16 24 56](https://user-images.githubusercontent.com/5378891/78226605-86c82400-74fe-11ea-8a94-f4a0eacb2687.gif)

Seems `L` does work.

**Comment by yoyo837** [comment]
他说en_au 应该是 dd/mm/YYYY

**Comment by zombieJ** [comment]
It's a bug for v3 not correct handle locale info. In v4, all `locale` is controlled by ConfigProvider. So if need get `L` format. You should config ConfigProvider `locale` prop to set the locale.

https://codesandbox.io/s/antd-reproduction-template-9kkg9

**Comment by zombieJ** [comment]
Additionally, `en_AU` is not in `antd/lib/locale/`. It's welcomed for PR to add locale file.

**Comment by patrickomeara** [comment]
Hi @zombieJ 

Here I have used ConfigProvider to provide `en_GB` however it still shows in US format

https://codesandbox.io/s/antd-reproduction-template-igdhd

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/78236424-8c2c6b00-750c-11ea-9ff8-79b31fec7d8d.png)

I tried this but it also doesn't work:
https://codesandbox.io/s/antd-reproduction-template-9ff3e

**Comment by zombieJ** [comment]
@patrickomeara  @yoyo837, moment do not include its locale by default. You should import it when use it: https://codesandbox.io/s/antd-reproduction-template-z3ss2?file=/index.js
