### ISSUE TITLE
Filter icon visible when no filter items

### ISSUE THREAD

**Issue by PaulPCIO** [ant-design/ant-design#22816]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-table-column-filter-icon-ovxof)

### Steps to reproduce
1. Create Table Data
2. Create Table Columns
3. Add either an empty filter array to a column or undefined filter to a column
```jsx
  {
    title: "Age",
    dataIndex: "age",
    key: "age",
    filters: [] // this causes the filter icon to be visible
  }
```
or
```jsx
  {
    title: "Age",
    dataIndex: "age",
    key: "age",
    filters: undefined // this causes the filter icon to be visible
  }
```

### What is expected?
The filter icon should not be visible as there are no dropdown icons

### What is actually happening?
The filter icon is visible and the dropdown filter menu is empty

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | react 16.13.1 |
| System | windows 10 / macOS Catalina |
| Browser | Chrome 80.0.3987.149 |

---
If you ask why there would be an empty filter or undefined filter, It is because we build our filter list dynamically based on the available data, so if there is either no data or only 1 filterable item in our current dataSource, then we do not want to display the column filter.

**Comment by yoyo837** [comment]
Caused by the `in` operator at https://github.com/ant-design/ant-design/blob/master/components/table/hooks/useFilter/index.tsx

**Comment by zombieJ** [comment]
We can remove filter icon when is `undefined` but should keep when it's a empty array.
