### ISSUE TITLE
RangePicker设置defaultValue不生效

### ISSUE THREAD

**Issue by PresByter2015** [ant-design/ant-design#22813]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-meninsky-wfj65)

### Steps to reproduce
usecontext 获取的值，放到defaultValue里面；RangePicker在Modal组件内部。
1. const { state, dispatch } = useContext(MyContext)

2.
<RangePicker
                        defaultValue={[moment(state.startTime, "YYYY-MM-DD HH:mm"), moment(state.endTime, "YYYY-MM-DD HH:mm")]}
                        showTime={{ format: 'HH:mm' }}
                        format="YYYY-MM-DD HH:mm"
                        onChange={onChange}
                        onOk={onOk}
                    />
3. 结果始终是 0000-01-01 00:00

### What is expected?
获取到传到的值。如2020-03-26 19:59

### What is actually happening?
0000-01-01 00:00

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | windows10 |
| Browser | 谷歌浏览器 版本 80.0.3987.149（正式版本） （64 位） |

**Comment by yoyo837** [comment]
复现是空的

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

**Comment by PresByter2015** [comment]
写作 component 文件内

**Comment by PresByter2015** [comment]
获得的数据是对的，只要一使用 moment[] 就为 0000-01-01 00:00

**Comment by yoyo837** [comment]
请先更新你的复现。

**Comment by PresByter2015** [comment]
本地 跑得起来，复现跑步起来，codeopen antd引入失败

**Comment by yoyo837** [comment]
你的复现，就算你写在component里，入口文件什么都没引用当然跑不起来

![image](https://user-images.githubusercontent.com/6134547/78119526-2ae89700-743b-11ea-9240-e33c975881f4.png)

**Comment by PresByter2015** [comment]
打算 回退了 问题太多了。
