### ISSUE TITLE
table的filters筛选为何会触发分页呢，我的数据是希望后台交互筛选的啊，

### ISSUE THREAD

**Issue by imeime** [ant-design/ant-design#22819]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在table数据翻页的基础上，再进行表头filters筛选时可以控制与后台交互数据，而不是也触发分页又取一次数据~~~

### What does the proposed API look like?
在table数据翻页的基础上，再进行表头filters筛选时可以控制与后台交互数据，而不是也触发分页又取一次数据~~~

**Comment by yoyo837** [comment]
table的filters是前端过滤，而前端过滤比如存在行数变化，分页自然变化。

**Comment by imeime** [comment]
由于涉及数据量较大问题，一次性不会取所有，执行的是后端交互取数，希望filters可以支持后端取数，，，，

**Comment by yoyo837** [comment]
你应该给你的表格套上搜索表单，来达到你的目的。
例如：
![image](https://user-images.githubusercontent.com/6134547/78120697-f70e7100-743c-11ea-84bf-08a1aae411c2.png)

**Comment by imeime** [comment]
![image](https://user-images.githubusercontent.com/14157324/78120783-19a08a00-743d-11ea-938c-8c139baf34f7.png)
产品说了算~~~

**Comment by yoyo837** [comment]
我没弄错的话，应该是不支持后端filters的。还有个方法就是叫产品下班别走...

**Comment by afc163** [comment]
可以支持的，你可以在 onChange 里面手动控制  `pagination.current` 保持不变。

**Comment by imeime** [comment]
刚才产品来找我了，，哈哈

**Comment by imeime** [comment]
试了下，貌似不对呢，我用的是pagination的onChange和table的onChange控制的，表头触发筛选：
首先触发分页，pagination里的onChange(cur)事件，随后触发才是table的onChange（pagination, filters, sorter），这里区分不了这个触发是哪来的，，求大佬指点

**Comment by afc163** [comment]
可以这样：https://codesandbox.io/s/yuanchengjiazaishuju-ant-design-demo-7y2uf

不过 还有一个问题，filters 没变化的时候会触发 onChange，我得修一下。

**Comment by xiaozhaoying** [comment]
解决办法
可以移除pagination的onChange事件，改用Table组件的onChange事件，该事件会在表格组件分页、排序、筛选变化时触发，并接收以下参数：
https://github.com/ant-design/ant-design/issues/13509
