### ISSUE TITLE
antd table `scroll.x` 搭配 `column.ellipsis` 在 `Firefox浏览器 `下会导致单元格内容根据宽度自动省略不生效

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#22812]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/fengyun2/pen/ExjMLzZ?editable=true&editors=001](https://codepen.io/fengyun2/pen/ExjMLzZ?editable=true&editors=001)

### Steps to reproduce
用火狐浏览器打开页面即可重现

![image](https://user-images.githubusercontent.com/8147202/78109720-54e68d00-742c-11ea-9a8a-001342f40b9a.png)

### What is expected?
antd table `scroll.x` 搭配 `column.ellipsis` 在 `Firefox浏览器 `下单元格内容根据宽度可以自动省略，跟Chrome和IE11下的表现效果一致

![image](https://user-images.githubusercontent.com/8147202/78110116-0d143580-742d-11ea-9d12-82c085c67612.png)

### What is actually happening?
antd table `scroll.x` 搭配 `column.ellipsis` 在 `Firefox浏览器 `下会导致单元格内容根据宽度自动省略不生效

![image](https://user-images.githubusercontent.com/8147202/78109720-54e68d00-742c-11ea-9a8a-001342f40b9a.png)

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | 16.13.1 |
| System | win 10 |
| Browser | Firefox Quantuan 68.0.1(32位) |

**Comment by zombieJ** [comment]
`max-content` 就是让表格宽度撑满来展示内容。如果需要省略，设置一个固定的宽度。

**Comment by afc163** [comment]
改成 `x: '100%'` 就 ok 了。

https://codepen.io/afc163-1472555193/pen/YzXgBKL?editors=0010

**Comment by fengyun2** [comment]
> 改成 `x: '100%'` 就 ok 了。
> 
> https://codepen.io/afc163-1472555193/pen/YzXgBKL?editors=0010

设置 scroll.x = '100%' 后，无论内容多少，都会出现横向滚动条

**Comment by afc163** [comment]
@zombieJ `overflow: auto` 在新版 Table 下是不是可以考虑起来了，最近反馈挺多。

https://github.com/ant-design/ant-design/issues/22827
https://github.com/ant-design/ant-design/issues/22346
https://github.com/ant-design/ant-design/issues/21304

**Comment by zyrepo** [comment]
@afc163  设置了scrollx的情况下， 动态减少column 会导致，每一个td都变为设置好的width, 不会自动撑满table。

**Comment by zyrepo** [comment]
columns 动态改变的时候， 
![image](https://user-images.githubusercontent.com/22114645/82432496-b806ae80-9ac2-11ea-8102-864a6e063832.png)
这个东西并不会去动态改变
