### ISSUE TITLE
style: Menu backgroud error in compact

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#22815]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/#components-menu-demo-theme](https://ant.design/components/menu-cn/#components-menu-demo-theme)

### Steps to reproduce
- Open link
- Select compact mode

### What is expected?
- backgroud right

### What is actually happening?
- backgroud error

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by xrkffgg** [comment]
选择 紧凑模式默认的 background 把 dark 的 background 给覆盖了

**Comment by xrkffgg** [comment]
以此类推，感觉其他的类似，这种的 也会有问题，我找找看

**Comment by AshoneA** [comment]
@xrkffgg 多谢多谢。

**Comment by xrkffgg** [comment]
粗略看了一圈，其他的暂时没发现

**Comment by AshoneA** [comment]
我大致都检查过一遍了，就是有些组件在某些配置组合下会出问题的情况没 catch 到。

**Comment by xrkffgg** [comment]
发现了一个~

**Comment by xrkffgg** [comment]
https://ant.design/components/spin-cn/#components-spin-demo-size

![image](https://user-images.githubusercontent.com/29775873/78117480-4e5e1280-7438-11ea-85fd-7a63703de710.png)

margin-right  给覆盖了

**Comment by xrkffgg** [comment]
Dark.theme 同样被覆盖

**Comment by xrkffgg** [comment]
发现了的再解决吧，这玩意太细节了，专门去找，不一定能找到

**Comment by AshoneA** [comment]
@xrkffgg 反正你找到了 assign 给我就行了。

**Comment by xrkffgg** [comment]
@AshoneA @afc163 
https://ant.design/components/radio-cn/#components-radio-demo-radiobutton

发现大问题了。。。。。compact 会把 rtl 的样式覆盖。。。

必须在 compact 后面 再引 一次 rtl 才行，而且感觉需要对 compact + rtl 再处理

**Comment by xrkffgg** [comment]
编译出的 _site/compact.css 文件中，关于 rtl 的 在 默认的前面，应该再后面就好了

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/fangxiang-ant-design-demo-1lqi5

不过暂时不用担心，这个情况只存在官网

在实际工程中，应该 compact/ dark 不会覆盖 rtl

**Comment by xrkffgg** [comment]
同时使用的时候，以后一个 引入的 css 为准，前面的不生效了

**Comment by xrkffgg** [comment]
我用的方式二  https://ant.design/docs/react/customize-theme-cn#%E5%AE%98%E6%96%B9%E4%B8%BB%E9%A2%98-%F0%9F%8C%88

难道方式 一 和方式三，同时开启能同时生效吗？

@AshoneA

**Comment by xrkffgg** [comment]
官网我觉得还是 site 生成的 css 的问题，build 出的 dist 中的 css 就没问题

**Comment by AshoneA** [comment]
> 同时使用的时候，以 后一个 引入的 css 为准，前面的不生效了

这个我过两天放假的时候看下，这两天有点忙...

> 难道方式 一 和方式三，同时开启能同时生效吗？

https://github.com/umijs/umi/issues/4315

https://github.com/umijs/plugins/pull/131

现在主题实现上支持混合的话有点麻烦，所以只能选择其一，等之后会用其他方式实现支持混合模式。

**Comment by xrkffgg** [comment]
我记得刚开始也是说的 只有一种，但是看官网的教程 变成了 两种都可以 😂😂，我以为你实现了

**Comment by AshoneA** [comment]
> 我记得刚开始也是说的 只有一种，但是看官网的教程 变成了 两种都可以 😂😂，我以为你实现了

单纯的用 less 变量覆盖是可以实现混合的，但是昨天看了 umi 那边主题配置方式不太一样。

**Comment by afc163** [comment]
> 单纯的用 less 变量覆盖是可以实现混合的，但是昨天看了 umi 那边主题配置方式不太一样。

给 umi 来个 PR？

**Comment by AshoneA** [comment]
> 给 umi 来个 PR？

过两天放假我研究下可不可行

**Comment by AshoneA** [comment]
> dark 也会把 rtl 的 给覆盖了

@xrkffgg 如果在 rtl 样式前面加个 `[data-direction='rtl']` 是可以通过权重方式覆盖掉，不过我不太清楚这种做法在 rtl 中是否标准，rtl 模式的网站都会在 header 中加 `[data-direction='rtl']` 吗？
![image](https://user-images.githubusercontent.com/22393991/78379489-08a27500-7605-11ea-8c70-586552a102c1.png)
