### ISSUE TITLE
Set valuePropName Error when Use Tree In Form

### ISSUE THREAD

**Issue by Evanna51** [ant-design/ant-design#22818]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/evanna51/pen/mdJojRe?editable=true&editors=001](https://codepen.io/evanna51/pen/mdJojRe?editable=true&editors=001)

### Steps to reproduce
Just Check

### What is expected?
Can Check, and Form can get right `checkedKeys`

### What is actually happening?
Can't check

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16  |
| Browser | Chrome 80 |

**Comment by Evanna51** [comment]
It may be rc-form's bug, but I think Antd Team should also solve

**Comment by afc163** [comment]
`valuePropName="checkedKeys" trigger="onCheck"`

**Comment by Evanna51** [comment]
> `valuePropName="checkedKeys" trigger="onCheck"`

Thank you！

there's no clear demo in Official website
