### ISSUE TITLE
select组件多选模式下的性能问题

### ISSUE THREAD

**Issue by ivc369** [ant-design/ant-design#22822]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-wescoff-w729p)

### Steps to reproduce
搜索、删除、选择一项Select Option

### What is expected?
期望onChange（选择或删掉一项option）的时候流畅一点。

### What is actually happening?
onChange（选择或删掉一项option）的时候很卡（在我的Mac上等待10秒左右看到结果）

在生产环境中的select options数据量会更大、数据结构更复杂，操作更卡（在我的Mac上等待50秒以上看到结果）。

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | v16.13.0 |
| System | MacOS Catalina Version 10.15.3 (19D76) |
| Browser | Chrome Version 80.0.3987.149 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
多选还需要想办法优化一下增减的流程。

**Comment by YYL1999** [comment]
select数据很多时不建议直接使用select组件 可以在antd的基础上进行封装 实现无限滚动

**Comment by ivc369** [comment]
> select数据很多时不建议直接使用select组件 可以在antd的基础上进行封装 实现无限滚动

无限滚动是指 [virtual scroll](https://github.com/react-component/virtual-list) 么?

**Comment by YYL1999** [comment]
> > select数据很多时不建议直接使用select组件 可以在antd的基础上进行封装 实现无限滚动
> 
> 无限滚动是指 [virtual scroll](https://github.com/react-component/virtual-list) 么?

你说的这个没用过 要是不着急 可以自己实现一个  看看网上教程啥的

**Comment by ivc369** [comment]
> > > select数据很多时不建议直接使用select组件 可以在antd的基础上进行封装 实现无限滚动
> > 
> > 
> > 无限滚动是指 [virtual scroll](https://github.com/react-component/virtual-list) 么?
> 
> 你说的这个没用过 要是不着急 可以自己实现一个 看看网上教程啥的

？？感觉你可能没理解我的意思，zombieJ好像是知道的

**Comment by YYL1999** [comment]
> > > > select数据很多时不建议直接使用select组件 可以在antd的基础上进行封装 实现无限滚动
> > > 
> > > 
> > > 无限滚动是指 [virtual scroll](https://github.com/react-component/virtual-list) 么?
> > 
> > 
> > 你说的这个没用过 要是不着急 可以自己实现一个 看看网上教程啥的
> 
> ？？感觉你可能没理解我的意思，zombieJ好像是知道的

根本原因就是数据量大 渲染卡顿  解决掉渲染问题就OK了呗

**Comment by Kermit-Xuan** [comment]
select 现在已经使用虚拟列表实现了，大数据渲染列表不是问题。

**Comment by YYL1999** [comment]
> select 现在已经使用虚拟列表实现了，大数据渲染列表不是问题。

v4确实支持了  上周还发现个bug

**Comment by ivc369** [comment]
> > > > > select数据很多时不建议直接使用select组件 可以在antd的基础上进行封装 实现无限滚动
> > > > 
> > > > 
> > > > 无限滚动是指 [virtual scroll](https://github.com/react-component/virtual-list) 么?
> > > 
> > > 
> > > 你说的这个没用过 要是不着急 可以自己实现一个 看看网上教程啥的
> > 
> > 
> > ？？感觉你可能没理解我的意思，zombieJ好像是知道的
> 
> 根本原因就是数据量大 渲染卡顿 解决掉渲染问题就OK了呗

不全是， v4确实是支持虚拟列表这个我知道（数据量大的渲染没问题），我的问题是比如 “搜索、删除、选择一项Select Option”的交互会卡顿

**Comment by Kermit-Xuan** [comment]
这个我已经知道啥问题了，明天尝试进行修复

**Comment by ivc369** [comment]
> 这个我已经知道啥问题了，明天尝试进行修复

嗯嗯 🙏

**Comment by Kermit-Xuan** [comment]
原因是 `rc-select` 里面的这个方法导致:
``` js
export function findValueOption(
  values: RawValueType[],
  options: FlattenOptionData[],
): OptionData[] {
  const optionMap: Map<RawValueType, OptionData> = new Map();

  options.forEach(flattenItem => {
    if (!flattenItem.group) {
      const data = flattenItem.data as OptionData;
      // Check if match
      optionMap.set(data.value, data);
    }
  });

  return values.map(val => injectPropsWithOption(optionMap.get(val)));
}
```

在显示选中值的时候会遍历每个值去找值对应的`label`、`disabled`等属性:
``` js
let displayValues = React.useMemo<DisplayLabelValueType[]>(
      () =>
        mergedRawValue.map((val: RawValueType) => {
          const displayValue = getLabeledValue(val, {
            options: mergedFlattenOptions,
            prevValue: baseValue,
            labelInValue: mergedLabelInValue,
            optionLabelProp: mergedOptionLabelProp,
          });

          return {
            ...displayValue,
            disabled: isValueDisabled(val, mergedFlattenOptions),
          };
        }),
      [baseValue, mergedOptions],
    );
```
其中 `isValueDisabled` 和 `getLabeledValue` 方法都会调用 `findValueOption` 这个, 当选中的值和选项非常大的时候，计算量就会非常大，我针对 `findValueOption` 做了优化，当不传入选项时就会使用缓存的options，不用每次都对options进行遍历，这样在调用上面那个方法时只需要最开始调用一次 `findValueOption` 后续值的遍历都使用缓存，我试了试选中和删除的性能没有问题，都是立刻得到反馈

优化后的 `findValueOption`:
``` js
let optionMap: Map<RawValueType, OptionData> = new Map();
export function findValueOption(
  values: RawValueType[],
  options?: FlattenOptionData[],
): OptionData[] {
  // it will use cached optionMap when no options.
  if (options) {
    optionMap = new Map();
    options.forEach(flattenItem => {
      if (!flattenItem.group) {
        const data = flattenItem.data as OptionData;
        // Check if match
        optionMap.set(data.value, data);
      }
    });
  }

  return values.map(val => injectPropsWithOption(optionMap.get(val)));
}
```

调用优化:
``` js
let displayValues = React.useMemo<DisplayLabelValueType[]>(() => {
      // cache options
      findValueOption([], mergedFlattenOptions);

      return mergedRawValue.map((val: RawValueType) => {
        const displayValue = getLabeledValue(val, {
          options: null,
          prevValue: baseValue,
          labelInValue: mergedLabelInValue,
          optionLabelProp: mergedOptionLabelProp,
        });

        return {
          ...displayValue,
          disabled: isValueDisabled(val, null),
        };
      });
    }, [baseValue, mergedOptions]);
```

[#499](https://github.com/react-component/select/pull/499)

@zombieJ

**Comment by ivc369** [comment]
> findValueOption

感谢 ❤

**Comment by Kermit-Xuan** [comment]
@zombieJ 麻烦看看这个有没有问题
