### ISSUE TITLE
Buggy table display on mobile

### ISSUE THREAD

**Issue by ixowuif** [ant-design/ant-design#22827]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
Is also buggy in the Ant Design Docs.

### What is expected?
The table should become scrollable if the content is too long (workes if there is a fixed column). (https://imgur.com/MOvYPq9)

### What is actually happening?
the table is floating over the container and outside of the screen.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.12.0 |
| System | iOS |
| Browser | Safari |

---
also the gradient seams to be buggy. (https://imgur.com/bRl3hHS)

**Comment by zombieJ** [comment]
Use `scroll` prop to make it responsive. But we will do nothing on demo case each demo should be pure for usage case.

**Comment by ixowuif** [comment]
adding "scroll" doesn't fix the problem, and it is not only the demo, i have the same problem in my project. it is just strange behavior, if i add a fixed colum it will work. and it is just ios/safari, on mac/chrome it is working like expected.

also the display problem with the black line is stille there. @zombieJ
