### ISSUE TITLE
Unknown prop `spinning` on <div> tag. Remove this prop from the element.

### ISSUE THREAD

**Issue by Yhaojing** [ant-design/ant-design#2282]
### 本地环境

- antd 版本:1.6.2
- 操作系统及其版本：mac
- 浏览器及其版本:chrome

### 你做了什么？
引入and<Spin/>

## 实际上的结果：
报错Unknown prop `spinning` on <div> tag. Remove this prop from the element.
看到网上相关问题，但是我本地代码怎么解决我还是不知道，以我一小段程序为例请告诉我怎么修改：
`import React, { Component } from 'react'
import { Spin } from 'antd'

class LoadingPage extends Component {

    render () {
        return (
            <div className='page'>
                <Spin/>
            </div>
        )
    }
}

export default LoadingPage`

**Comment by afc163** [comment]
#2258
