### ISSUE TITLE
Form.List remove之后再重置生成的fields的key值不从0递增

### ISSUE THREAD

**Issue by Caoqingda** [ant-design/ant-design#22826]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#Form.List](https://ant.design/components/form-cn/#Form.List)

### Steps to reproduce
Form.List 
新加三个：
![image](https://user-images.githubusercontent.com/41361873/78128378-63db3880-7448-11ea-97e9-27b048e1baf3.png)
全部删除并**重置**之后在新加三个
![image](https://user-images.githubusercontent.com/41361873/78128544-b3216900-7448-11ea-9916-f6ade324ffee.png)
重置之后的key为什么会没有删除过的key

### What is expected?
重置之后  应该是key从0开始递增

### What is actually happening?
重置之后 key过滤掉key删除过的ke

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | win10 |
| Browser | Google Chrome  版本 80.0.3987.149（正式版本） |

**Comment by zombieJ** [comment]
`key` 当然不能重置，重置了就让 React 对应到不同 Node 去了。只有 `name` 才应该重置。
