### ISSUE TITLE
如果Menu是激活状态，父级的SubMenu应该默认激活

### ISSUE THREAD

**Issue by winter-ice** [ant-design/ant-design#22835]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
用户只需要判断菜单项即可，例如通过location.path判断菜单项变成激活状态，但是父级菜单默认没有展开

### What does the proposed API look like?
无需提供API

**Comment by afc163** [comment]
存在子菜单激活但是父级菜单收起的情况，比如当前子菜单高亮，用户手动收起父级菜单，所以组件不能简单的一刀切。你可以根据子菜单状态去自行按需控制父级菜单的展开收起状态。

**Comment by winter-ice** [comment]
@afc163 我说的是`defaultOpenKeys`的情况，是否可以这样？

**Comment by afc163** [comment]
defaultOpenKeys 和 defaultSelectedKeys 保持分离吧，有自定义需求上层封装就好。

**Comment by winter-ice** [comment]
感觉`defaultOpenKeys`应该默认是自动展开的，如果有需求自定义可以自己传值。因为大部分场景默认情况下菜单项选中·SubMenu·就应该展开，所以应该覆盖这种默认情况。90%的情况下是这样的话，作为默认情况，不是可以增加开发者易用性么

**Comment by afc163** [comment]
defaultOpenKeys 默认值目前为空，如果增加就会是破坏性修改，组件层面不建议做太多假设。

> 大部分场景默认情况下菜单项选中·SubMenu·就应该展开

这个也不是对的，比如 horionzontal Menu 和 vertical Menu，以及 Dropdown 里的 menu，默认选中也不应该展开。inline Menu 也保持一致性会比较简单。

**Comment by winter-ice** [comment]
好吧，考虑的不是很周到，感谢回复 😄

**Comment by Hardenthirteen** [comment]
请问怎样设置可以让 跳转到没有name属性的页面时，菜单栏不收起？
