### ISSUE TITLE
Space 自动屏宽组件被压缩了

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#22837]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-ant-design-demo-n2rlf)

### Steps to reproduce
通过刷新页面来重现

direction=“vertical” 时

### What is expected?
不要被压缩

### What is actually happening?
补压缩了

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by shaodahong** [comment]
不管是垂直还是水平都是 inline

**Comment by zombieJ** [comment]
见 @shaodahong 的说明，如果要撑满设置一个宽度即可：https://codesandbox.io/s/jibenyongfa-ant-design-demo-41plo

**Comment by kaoding** [comment]
@zombieJ 这个可以在 Space 文档中补充说明一下，让其他开发也好知道。这个是未告知的改变、还以为是bug。

**Comment by shaodahong** [comment]
@kaoding https://ant.design/components/space-cn/#components-space-demo-vertical 文档有写的
