### ISSUE TITLE
Tree rendering performance issue

### ISSUE THREAD

**Issue by cmark** [ant-design/ant-design#22839]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/tree/issues/305](https://github.com/react-component/tree/issues/305)

### Steps to reproduce
1. Create a tree component with around 200 items (the number of items depends on your computer's resources)
2. Scroll and navigate the tree while your mouse pointer is constantly moving up and down on the tree components
3. Chrome tries to handle the increasing amount of re-renders, but fails to render without performance drops

Especially noticable in the tree node highlighting, that it is unable to render due to the too many events.

### What is expected?
When scrolling and navigating a tree component with around 200 items I don't get occasional performance drop in Ant Design v4 Tree component.

### What is actually happening?
Occasional performance drops due to a potentially malfunctioning rc-tree `onMouseMove` event handler.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | N/A |
| Browser | Any browser (tested in Chrome) |

---
This is not related to the virtualized flag or any tree/list virtualization features. This is a bug in rc-tree and it has been already reported in the relevant repository.
See here: https://github.com/react-component/tree/issues/305

This is just an issue to track the integration progress of the bugfix in rc-tree with the latest antd v4.

**Comment by zombieJ** [comment]
It's a bug to repeat trigger active change.

**Comment by cmark** [comment]
Thank you! 👍
