### ISSUE TITLE
antd v4: tabs出现莫名其妙的边框样式 

### ISSUE THREAD

**Issue by TataQin** [ant-design/ant-design#22831]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

---
[这个样式是什么东东啊？可以去掉么](http://fdfs.test.ximalaya.com/group1/M01/37/B0/wKgD3l6EhsuAagPUAABbSsDY3s4083.png)
注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by yoyo837** [comment]
Duplicate of #22760
