### ISSUE TITLE
Prop option to use earlier version of DateRangePicker

### ISSUE THREAD

**Issue by ebru** [ant-design/ant-design#22830]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
**Current version:** https://ant.design/components/date-picker/

**Earlier version:** https://3x.ant.design/components/date-picker/

Please look for the example of Range Picker.

In the newest version of RangePicker, we need to click to start or end date to choose range. With that it restricts you to pick a range freely, you need to click both start/end date to complete range selection in some cases.

It is getting a bit more complex especially when you have disabled dates since the new version is not flexible as much as the earlier in my opinion.

I believe it might have strong reasons to do it like this and this is why I am not asking for a total change, but it would also be nice to have an option to use it like in the earlier version as well. It was really nice to click anywhere and choose a range while going forward/backward freely.

### What does the proposed API look like?
I don't have a clear naming on this one but maybe it can be like this, any prop option would work.

`<RangePicker isFlexibleRange  />`

**Comment by afc163** [comment]
We probably won't return to old interaction of RangePicker.

**Comment by eugenest** [comment]
@ebru 

we also faced this problem
our users are used to pick dates by 3 clicks: open date picker, pick start date, pick end date (changing time is a relatively rare scenario in our use cases)
so we just "rebuilt" date range picker version with separate controls

basic solution is here https://codesandbox.io/s/quizzical-cartwright-7xqik

**Comment by iShawnWang** [comment]
Same issue here !
