### ISSUE TITLE
通过`dva`异步加载数据，组件`Pagination`的`defaultCurrent`失效

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/ant-design#22849]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhucexinyonghu-ant-design-demo-7vqm3?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
先从model加载本地的分页数据，之后通过effects加载异步分页数据

### What is expected?
defaultCurrent应该正常展示

### What is actually happening?
defaultCurrent无效

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | codesandbox |
| Browser | chrome |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
