### ISSUE TITLE
即使使用了 getPopupContainer ，浮层位置仍不正确

### ISSUE THREAD

**Issue by fix777** [ant-design/ant-design#22848]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-voice-oqhfw)

### Steps to reproduce
1. 点击 `click me` 按钮
2. 滚动红框内的滚动条

### What is expected?
浮层位置跟随按钮

### What is actually happening?
浮层位置未发生变化

| Environment | Info |
|---|---|
| antd | 3.26.14 |
| React | 16.13.1 |
| System | macOS 10.15.3 (19D76) |
| Browser | Chrome Version 80.0.3987.149 (Official Build) (64-bit) |

---
搜索了issue，没有找到解决办法

**Comment by afc163** [comment]
https://codesandbox.io/s/naughty-merkle-jdjvg

浮层需要相对滚动区域元素定位。

**Comment by fix777** [comment]
> https://codesandbox.io/s/naughty-merkle-jdjvg
> 
> 浮层需要相对滚动区域元素定位。

感谢回复。关于这点可以在 [FAQ](https://3x.ant.design/docs/react/faq-cn#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E4%BC%9A%E8%B7%9F%E9%9A%8F%E6%BB%9A%E5%8A%A8%E6%9D%A1%E4%B8%8A%E4%B8%8B%E7%A7%BB%E5%8A%A8%EF%BC%9F) 中提醒下开发者

**Comment by afc163** [comment]
@fix777 👍 确实，来个 PR 如何？

**Comment by aiingstan** [comment]
貌似 `Modal.info` 之类使用 `ConfirmDialog` 进行渲染的元素，没法从全局配置中获取 `getPopupContainer` 设定
https://github.com/ant-design/ant-design/blob/8256b3cb8961460493091f34cc6feacf3554d0a0/components/modal/confirm.tsx#L18
