### ISSUE TITLE
表单验证initialValue 问题

### ISSUE THREAD

**Issue by ChenQiWen** [ant-design/ant-design#2285]
### 本地环境

- antd 版本:1.6.3
- 操作系统及其版本：win10
- 浏览器及其版本: chrome 50.0.2661.94 m

### 你做了什么？

表单验证 是编辑页面 一开始进入页面控件用initialValue 给个初始值 删除了初始值在提交的时候 验证非空就没用了

### 你期待的结果是：

把initialValue 给的初始值删掉后 依然能正确验证

## 实际上的结果：

控件只要有了initialValue 哪怕给一个空值 也能通过验证

**Comment by ddcat1115** [comment]
试了一下没有重现

请提供下可重现的demo   http://codepen.io/anon/pen/wGOWGW?editors=001
