### ISSUE TITLE
现在的项目是用的antd，请问如何升级成antd-pro来做权限管理

### ISSUE THREAD

**Issue by w809694546** [ant-design/ant-design#22859]
如题

**Comment by yoyo837** [comment]
现在是antd 做好了，升级pro的必要性不大。你的项目已经是一个类pro的东西了，pro只是个模版。

**Comment by w809694546** [comment]
> 现在是antd 做好了，升级pro的必要性不大。你的项目已经是一个类pro的东西了，pro只是个模版。

请问如果想用pro的权限管理Authorized应该怎么操作一下呢

**Comment by yoyo837** [comment]
搬运你需要的那部分代码就可以了
