### ISSUE TITLE
Table column set sorter cause align invalid

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#22855]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-ant-design-demo-v3kw1)

### Steps to reproduce
see name column

### What is expected?
align valid

### What is actually happening?
align invalid

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.0 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by zombieJ** [comment]
ref: https://github.com/ant-design/ant-design/commit/e262d14c2bd5705c30013b9f7012ba41ff616cf9#diff-e2a536684ed8b2684e0ae68f0ef1ffe9R214
