### ISSUE TITLE
[Menu] Selected submenu doesn't appear selected

### ISSUE THREAD

**Issue by JesusTheHun** [ant-design/ant-design#22852]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/JesusTheHun/pen/MWwRmRm?editors=0010](https://codepen.io/JesusTheHun/pen/MWwRmRm?editors=0010)

### Steps to reproduce
Set the selectedKey of the menu to a submenu key. The submenu is not selected.

### What is expected?
Since the tile is clickable it is expected to be selectable.

### What is actually happening?
The submenu tile does not appear as selected.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.0 |
| System | macOS 10.15.4 |
| Browser | all |

**Comment by zombieJ** [comment]
SubMenu do not have selected status. Only MenuItem has.
```
defaultSelectedKeys={['3']}
defaultOpenKeys={['sub1', 'sub2']}
```

**Comment by JesusTheHun** [comment]
I this true. Hence this issue. There is no reason it has none, it's inconsistent.
A SubMenu can be clicked, therefore you can be on a page that matches the SubMenu tile.

This refer to https://ant.design/docs/spec/values, natural user cognition and behavior.
