### ISSUE TITLE
Menu 支持更多类型的openKeys

### ISSUE THREAD

**Issue by winter-ice** [ant-design/ant-design#22851]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用者无需进行二次转换

### What does the proposed API look like?
涉及api：`defaultOpenKeys`,`defaultSelectedKeys`,`openKeys`,`selectedKeys`
希望支持`number`,`string`,`number[]`,`string[]`类型传入

**Comment by afc163** [comment]
建议转成 string，多支持一个类型有时候会造成 string 和 number 的混用。
