### ISSUE TITLE
4.0 Dropdown触发事件设置为click，自定义overlay，点击overlay导致下拉框被关闭

### ISSUE THREAD

**Issue by Cavendichun** [ant-design/ant-design#22853]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hongfafangshi-ant-design-demo-bxd2n)

### Steps to reproduce
自定义overlay，点击overlay导致下拉框被关闭

### What is expected?
点击overlay不关闭下拉框

### What is actually happening?
点击overlay导致下拉框被关闭

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.8.0 |
| System | win10 |
| Browser | 74 |

**Comment by zombieJ** [comment]
用 Popover
