### ISSUE TITLE
Checkbox in form with default value. Got error: Failed prop type: Invalid prop `checked` supplied to `Checkbox`

### ISSUE THREAD

**Issue by JumpAttacker** [ant-design/ant-design#22854]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-j5hp1q-5ak3g2](https://stackblitz.com/edit/react-j5hp1q-5ak3g2)

### Steps to reproduce
try to change defaultChecked in code and you will see, that it is ignoring dat setting

### What is expected?
want to manipulate default values in checkbox

### What is actually happening?
checkbox ignoring 
initialValues={{
                    Checkbox: {
                        defaultChecked: false,
                    },
                }}

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | react@16.13.1 |
| System | win10 |
| Browser | 80.0.3987.132 |

---
also trying 
checked instead of defaultChecked

**Comment by yoyo837** [comment]
```
initialValues={{
            Checkbox: false,
        }}
```

**Comment by zsl1549** [comment]
![image](https://user-images.githubusercontent.com/32888522/91814028-187ebd80-ec66-11ea-8424-e72998e06759.png)
@yoyo837   3.26.18版本就没有解决的办法吗

**Comment by yoyo837** [comment]
什么问题，给个复现
