### ISSUE TITLE
【Bug】模态确认框Modal.confirm方法创建的弹出确认框中的”确定“按钮可以点击多次

### ISSUE THREAD

**Issue by Feixu2015** [ant-design/ant-design#22861]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/querenduihuakuang-ant-design-demo-c19nw)

### Steps to reproduce
1.  点击confirm，弹出确认框
2. 靠近"Ok"按钮右侧右键，然后再迅速多次左键点击“Ok”按钮的空白处
3. console中会出现“我被点击了2次”，说明按钮可以被多次点击

### What is expected?
确认框的“OK"按钮只允许点击一次

### What is actually happening?
确认框的“OK"按钮可以被点击多次

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16.8.6 |
| System | macos Catalina 10.15 |
| Browser | Chrome 80.0.3987.149 |

---
确认框：只需确认一次即可，不应该被多次点击“确认”按钮

**Comment by yoyo837** [comment]
试不出来。上个gif?

**Comment by yoyo837** [comment]
复现里是4.1.0, 你的描述是3.19.3

**Comment by Feixu2015** [comment]
@yoyo837 sanbox没有antd的3.19.3版本。
![Bug](https://user-images.githubusercontent.com/11504549/78265904-a3cd1900-7537-11ea-8d74-bb22b9ff76e9.gif)

**Comment by yoyo837** [comment]
看gif，在动画过程中确实连续点击了两次，我感觉这个不算问题。你可以在点击后给按钮设置禁用状态。

**Comment by Feixu2015** [comment]
> 看gif，在动画过程中确实连续点击了两次，我感觉这个不算问题。你可以在点击后给按钮设置禁用状态，控制权完全在个人，antd不应该干涉这个。

个人理解：从业务层面来讲，既然是“确认模态框”，组件层面应确保按钮只被允许点击了一次。按钮可以点击多次本身就和确认模态框的业务场景相悖。
