### ISSUE TITLE
Input type="textarea" 设置autosize无法自适应行数且报错

### ISSUE THREAD

**Issue by Jinan11jinan** [ant-design/ant-design#22865]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/1.x-stable/components/input/demo/autosize-textarea.md](https://github.com/ant-design/ant-design/blob/1.x-stable/components/input/demo/autosize-textarea.md)

### Steps to reproduce
复制代码后运行浏览器控制台报错

### What is expected?
不报错且能自适应行高

### What is actually happening?
控制台报：Warning: Received `true` for a non-boolean attribute `autosize`.
无法自适应行高

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.13.0 |
| System | window7 |
| Browser | chrome 75.0.3770.100 |

**Comment by zombieJ** [comment]
`1.x` 已经不再维护，请升级你的 antd 版本。
