### ISSUE TITLE
Padding of column title is broken on small sized table when filter is enabled

### ISSUE THREAD

**Issue by ebru** [ant-design/ant-design#22866]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-ant-design-demo-01isv)

### Steps to reproduce
1. Inspect column header, 

`padding: 16px 2.3em 16px 16px` (.ant-table-filter-column-title)

2. Inspect a cell under that column, 

`padding: 8px 8px;` (.ant-table.ant-table-small .ant-table-tbody > tr > td)

### What is expected?
Padding-left and padding-right values should be relevant to have column title and cell content aligned correctly

### What is actually happening?
Column title is not aligned with its cell content when filter is enabled, it is 8px ahead

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | React 16.13.1 |
| System | MacOS Catalina Version 10.15.3  |
| Browser | Chrome Version 80.0.3987.162 |

**Comment by afc163** [comment]
same as #22777

**Comment by zombieJ** [comment]
ref #21631
