### ISSUE TITLE
Cascader TS类型声明少字段fieldnames

### ISSUE THREAD

**Issue by PandaJJ5286** [ant-design/ant-design#22862]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
饮用Cascader组件，传入filedNames属性，即报错，搜索cascader文件，没有该字段的声明，删除该字段后不再报错。

### What is expected?
不报错

### What is actually happening?
Type '{ filedNames: { label: string; }; options: any[]; onChange: (value: any, selectedOptions: any) => void; placeholder: string; value: any; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Cascader> & Pick<Readonly<{ children?: ReactNode; }> & Readonly<...>, "style" | ... 21 more ... | "fieldNames"> & Partial<...> & Partial<...>'.
[0]   Property 'filedNames' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Cascader> & Pick<Readonly<{ children?: ReactNode; }> & Readonly<...>, "style" | ... 21 more ... | "fieldNames"> & Partial<...> & Partial<...>'.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | macOS Mojave 10.14.4 (18E224) |
| Browser | chrome 80.0.3987.149 |

**Comment by PandaJJ5286** [comment]
https://codesandbox.io/s/antd-reproduction-template-5e5j8

**Comment by yoyo837** [comment]
`fieldNames`

**Comment by PandaJJ5286** [comment]
> `filedNames` => `fieldNames`

收到，谢谢，不好意思，自己拼错了
