### ISSUE TITLE
使用Form表单时,如果Form.Item中写入其他非antd组件,在提交表单时会出错

### ISSUE THREAD

**Issue by hitime888** [ant-design/ant-design#22874]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-mccb3)

### Steps to reproduce
1. 点击"提交"按钮, 会发现"测试一"为必填项, "测试二"为必填项, 但是没有给出默认提示.
2. 分别填写"测试一"和"测试二".
3. 点击"提交"按钮, 会发现现象同上面序号1.

### What is expected?
在Form.Item中, 加入其他元素(非antd组件)时, 能够正确的通过表单的必填校验.

### What is actually happening?
在Form.Item中, 加入其他元素(非antd组件)时, 提交表单时不能通过表单的必填校验.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.3 |
| Browser | chrome 80.0.3987.149 |

---
1. 当Form.Item设置 rules={[{ required: true, message: "此题必填" }]} 时, 提交表单不能通过校验.
2. 当Form.Item设置 required={true} 时, 提交表单无反应, 获取不到表单的值.
3. 此现象在其他antd组件中也存在, 希望能够解决.

**Comment by yoyo837** [comment]
自定义组件要从prop接收来自form的value和onchange 并实现相关逻辑，


给你改了一个 没改全： https://codesandbox.io/s/antd-reproduction-template-vlto8

**Comment by yoyo837** [comment]
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by zombieJ** [comment]
请参考 @yoyo837  的留言，官网有自定义组件的例子。
