### ISSUE TITLE
@ant-prefix和ConfigProvider prefixCls配置后， Modal.confirm 样式前缀未修改 还是ant

### ISSUE THREAD

**Issue by leidenglai** [ant-design/ant-design#22873]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-t22bk)

### Steps to reproduce
如题

### What is expected?
能提供更好的方案配置 prefixCls

### What is actually happening?
 Modal.confirm className前缀未修改，包括内部的button组件

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | latest |
| System | Mac os |
| Browser | Chrome |

---
现在只有暂时这样弄了。
Modal.confirm({
      prefixCls: 'cbet-modal',
      cancelButtonProps: {
        prefixCls: 'cbet-btn'
      },
      okButtonProps: {
        prefixCls: 'cbet-btn'
      }
})

**Comment by afc163** [comment]
需要使用这种方式调用才能获得 prefixCls 和 context 数据：https://ant.design/components/modal-cn/#components-modal-demo-hooks

https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux-%E7%9A%84%E5%86%85%E5%AE%B9%EF%BC%9F

**Comment by vero-jasper** [comment]
这是

> 需要使用这种方式调用才能获得 prefixCls 和 context 数据：https://ant.design/components/modal-cn/#components-modal-demo-hooks
> 
> https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux-%E7%9A%84%E5%86%85%E5%AE%B9%EF%BC%9F

这是用hooks的情况，如果在class组件里，这个问题就没法解决了，改前缀只能改modal，如果content使用了组件则组件样式丢失

**Comment by vkiller178** [comment]
any update?

**Comment by Lcj-space** [comment]
> 需要使用这种方式调用才能获得 prefixCls 和 context 数据：https://ant.design/components/modal-cn/#components-modal-demo-hooks
> 
> https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux-%E7%9A%84%E5%86%85%E5%AE%B9%EF%BC%9F

就算这样也不方便啊。遇到业务复杂的地方都得加复杂的一匹。
