### ISSUE TITLE
Tab组件点击内容区域会出现蓝色边框

### ISSUE THREAD

**Issue by Codyooo** [ant-design/ant-design#22877]
antd版本：4.1.0
![image](https://user-images.githubusercontent.com/18410763/78327694-1aa5f880-75b0-11ea-8a7c-950d59a5e7f5.png)

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by xrkffgg** [comment]
It will be fix in next version.
