### ISSUE TITLE
Allow configuration of Modal animation origin point

### ISSUE THREAD

**Issue by mtjn** [ant-design/ant-design#22889]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In certain situations, Modals can appear with entry/exit animations using a page element as the origin point. The Modal appears at the origin point, and moves to the final position (top of screen or center if `centered: true`) during the entry/exit animations. Otherwise, Modals appear in their final destination, with no x/y movement.

It would be good to have the option to disable this behavior. This would solve the following problems:

1. Some people may find this x/y translation animations overly visually distracting.
2. This leads to Modals appearing in different ways, which can appear random/unpredictable and be confusing.
2. In some cases the same Modal can be triggered in both manners (e.g. a cancel editing confirmation which can be triggered by clicking a close icon, or pressing escape), which can be semantically confusing.

I have observed this behavior occurring when a Modal is created by an onClick handler, and also during testing when a Modal is created during a react-router route change (the Modal used the react-router <Link> element as the origin point).

### What does the proposed API look like?
For Modal API:

### String property example:

- Property: `animationOrigin`
- Description: `Controls the origin point for entry/exit animations`
- Type: `element | page`
- Default: `element`

### Boolean property example:

- Property: `animateOriginFromElement`
- Description: `Controls whether page elements should be used as origin points for entry/exit animations`
- Type: `boolean`
- Default: `true`

**Comment by afc163** [comment]
`<Modal transitionName="zoom" />`

https://github.com/ant-design/ant-design/issues/16435

https://github.com/ant-design/ant-design/pull/14052#discussion_r244902906

**Comment by mtjn** [comment]
Thanks. But zoom is the default behaviour, the origin point is still based on the trigger event target position.

Also where is the transitionName prop and its possible values documented?

**Comment by sauldeleon** [comment]
Any update on this? I would love to see all my modals starting from the center of the screen, instead of the clicking point.

How can we achieve this?

Thanks!

**Comment by markoorn** [comment]
Has anyone come right with this or is this a feature the team is not interested in supporting?

**Comment by GiovannaMonti** [comment]
Any updates? It would be a nice feature

**Comment by YongzeYao** [comment]
any updates?

**Comment by nodkrot** [comment]
Why so quite on this?

**Comment by trungkiengrxer** [comment]
anyone come up with a solution?
