### ISSUE TITLE
Allow global configuration of Modal option defaults

### ISSUE THREAD

**Issue by mtjn** [ant-design/ant-design#22886]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I prefer to have all Modals in my app centered. It would be good to be able to globally configure this behavior, instead of having to remember to add the `centered: true` prop to every `Modal.method()` call.

It would also be good to allow other configuring global defaults of other Modal options, e.g. okText, cancelText, closeIcon etc.

Thank you!

### What does the proposed API look like?
Similar to `message.config(options)`

`Modal.config({ centered: bool, ...options })`

**Comment by hengkx** [comment]
@zombieJ @afc163 
Is it necessary to add more global configuration? example:
```
Table.config({ bordered: bool, ...options })
```

**Comment by afc163** [comment]
Noop, Comtom Component is recommended to using React component with preset config.

**Comment by afc163** [comment]
I afraid this will be applied to `<Modal />` too which breaks rule about React component reuse method.
