### ISSUE TITLE
Calendar组件为何不能选中？

### ISSUE THREAD

**Issue by yesuanzao** [ant-design/ant-design#2288]
选中之后样式未改变。我看rc-fullCalendar有个Select属性，但是ant给禁用了，是否和这个有关？

**Comment by ddcat1115** [comment]
`Calendar` 只是按照日期形式展示数据，不提供选中等功能，如果需要，可以使用 Form Controls 类别下的 `DatePicker`

**Comment by yesuanzao** [comment]
@ddcat1115 我看onSelect是有效的，但是日历默认选中的还是当天，'ant-fullcalendar-selected-day'这个样式没有应用到选中的日期

**Comment by yesuanzao** [comment]
是版本的问题，升级就好了

**Comment by yesuanzao** [comment]
升级也不能解决。。。

**Comment by afc163** [comment]
@ddcat1115 的说法是对的，Calendar 类似电脑的日历，只是个展示容器，没有选中的交互，是有意这么做的。

**Comment by ningyanbo** [comment]
@afc163 why disabled rc-fullCalendar  Select={Select} ？
