### ISSUE TITLE
Form表单validateFields事件会导致useEffect触发两次

### ISSUE THREAD

**Issue by CarlXu94** [ant-design/ant-design#22882]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/CarlXu94/CarlXu94.git](https://github.com/CarlXu94/CarlXu94.git)

### Steps to reproduce
点击到第三页，点击查询会触发两次useEffect，如果把query组件里面的validateFields注释掉，就不会出现这个问题

### What is expected?
期望useEffect只触发一次

### What is actually happening?
期望useEffect只触发两次

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
`await` 使得 React 的 state update 会变成同步：
```jsx
const handleSearch = async () => {
  const values = await form.validateFields();
  if (props.onFormInput) {
    props.onFormInput({});
  }
};
```

所以你的 `setSearchData` 和 `setPagination` 会分别触发两次
```jsx
const onSearch=(values)=>{
  console.error('onSearch!', values);
  setSearchData(values)
  setPagination({
    ...pagination,
    current:1
  })
}
```

这和 Form 没有关系，你直接 await 任何东西都是多次触发 `useEffect`：
```jsx
const handleSearch = async () => {
  await Promise.resolve();
  if (props.onFormInput) {
    props.onFormInput({});
  }
};
```

**Comment by CarlXu94** [comment]
> `await` 进行React的状态更新会变成同步：
> 
> ```js-jsx
> const  handleSearch  =  async（）=> {
>    const  values  =  等待 表单。validateFields（）;
>   如果（道具。onFormInput）{
>      道具。onFormInput（{}）;
>   }
> };
> ```
> 
> 所以你的`setSearchData`和`setPagination`会分别触发两次
> 
> ```js-jsx
> const  onSearch =（值）=> {
>    控制台。错误（' onSearch！'，values）;
>   setSearchData（values）
>    setPagination（{
>      ... pagination，
>      current：1
>   }）
> }
> ```
> 
> 这和表单没有关系，你直接等待任何东西都是多次触发`useEffect`：
> 
> ```js-jsx
> const  handleSearch  =  async（）=> {
>    等待 Promise 。解决（）;
>   如果（道具。onFormInput）{
>      道具。onFormInput（{}）;
>   }
> };
> ```

我改成了.then()也会触发两次，之前用的是3.x的，当时以回调函数的形式没有出现这个问题，要怎么改还请大佬指教

**Comment by TianQianTQ** [comment]
请问这个问题如何解决呢
