### ISSUE TITLE
官方 transfer 动态数据例子中，右边显示条目错误

### ISSUE THREAD

**Issue by MinJieLiu** [ant-design/ant-design#22890]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/93xeb)

### Steps to reproduce
全选 transfer，转入到右边，然后分页
![image](https://user-images.githubusercontent.com/6167727/78342395-cc9eee00-75cb-11ea-9702-b6ec9f06d5ac.png)

![image](https://user-images.githubusercontent.com/6167727/78342430-d88ab000-75cb-11ea-94cc-5b4f17c6bd39.png)

### What is expected?
右边结果能和全选条目保持一致

### What is actually happening?
不一致

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.12 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
没懂，你的重现步骤具体点。

**Comment by MinJieLiu** [comment]
1. 左边列全选，全部转到 右边的框（右边的框能显示10条数据）
![image](https://user-images.githubusercontent.com/6167727/78354787-180ec780-75df-11ea-9b8e-1692f5b92d0b.png)

2. 左边点到第二页

![image](https://user-images.githubusercontent.com/6167727/78354815-24932000-75df-11ea-882b-4d391f383759.png)

右边的全选框选不了任何值了

**Comment by MinJieLiu** [comment]
表格上全选框可以，主要是 右边的框是由 `targetKeys` 来控制的，由什么办法能自定义顶部的全选框？

**Comment by zombieJ** [comment]
你分页把 `dataSource` 替换了，`targetKeys` 找不到对应的 key 就全选不了了。

**Comment by MinJieLiu** [comment]
这是官方文档中的 demo
