### ISSUE TITLE
How to control Select input value in tags mode?

### ISSUE THREAD

**Issue by toastyboost** [ant-design/ant-design#22898]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to add phone mask in select input

<img width="475" alt="Screenshot 2020-04-03 at 16 05 53" src="https://user-images.githubusercontent.com/51236614/78363840-24862680-75c5-11ea-9b09-805f77253f41.png">

### What does the proposed API look like?
Add render method or props

**Comment by afc163** [comment]
It should use `searchValue` to control, but it has problem in tags mode, trace #22907 for further bug fix.
