### ISSUE TITLE
Upload中action的地址设为'http://xxx.com/xxx'外链时，点击上传会报跨域错误

### ISSUE THREAD

**Issue by CXHtml** [ant-design/ant-design#2289]
### 本地环境

- antd 版本:1.6.3
- 操作系统及其版本：OS X EI Caption 10.11.5
- 浏览器及其版本: Chrome 51.0.2704.103 (64-bit)

### 你做了什么？

当action设为：

```
{
  action: 'http://v0.api.upyun.com/sscc-test'
}
```
点击上传会报：

`Request header field X-Requested-With is not allowed by Access-Control-Allow-Headers in preflight response`

### 你期待的结果是：

正常上传

**Comment by afc163** [comment]
https://github.com/react-component/upload/issues/33
