### ISSUE TITLE
Modal style breaks if html has no declaration of "<!DOCTYPE html>"

### ISSUE THREAD

**Issue by freewind** [ant-design/ant-design#22892]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/freewind-demos/typescript-react-antd-modal-style-issue-demo](https://github.com/freewind-demos/typescript-react-antd-modal-style-issue-demo)

### Steps to reproduce
1. Clone the repo
2. npm install
3. npm run demo
4. Click on the button on page to open the modal
You will see the modal styling issue

If you fix 'index.html' by uncomment the first line about "<!DOCTYPE html>", the refresh the browser, you will see the styling is corrected.

### What is expected?
The style is still correct without "<!DOCTYPE html>"

### What is actually happening?
The position of "x" on the right top of modal is not correct, higher than normal

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | not related |
| System | osx |
| Browser | chrome |

**Comment by freewind** [comment]
![image](https://user-images.githubusercontent.com/333781/78343133-f86ea380-75cc-11ea-8bcd-38aa885e97b5.png)

**Comment by yoyo837** [comment]
Why your HTML have no declaration, it is not standard.

**Comment by afc163** [comment]
Please add `<!DOCTYPE html>`, it is important.

**Comment by freewind** [comment]
What if you're writing some plugins or extensions for some legacy systems, which has no "<!DOCTYPE html>", and you can't add that?
