### ISSUE TITLE
[Menu] Submenu should be selectable

### ISSUE THREAD

**Issue by JesusTheHun** [ant-design/ant-design#22894]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

Following https://ant.design/docs/spec/values, natural user cognition and behaviour, a SubMenu tile can be clicked, therefore you can be on a page that matches the SubMenu tile, so it should be selectable. The user expect it and it's confusing for him to not see a visual feedback.

### Reproduction link
[https://codepen.io/JesusTheHun/pen/MWwRmRm?editors=0010](https://codepen.io/JesusTheHun/pen/MWwRmRm?editors=0010)

### Steps to reproduce
Set the selectedKey of the menu to a submenu key. The submenu is not selected.

### What is expected?
Since the tile is clickable it is expected to be selectable.

### What is actually happening?
The submenu tile does not appear as selected.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.0 |
| System | macOS 10.15.4 |
| Browser | all |

**Comment by afc163** [comment]
Submenu is designed to be not selectable but collapsible, Adding selected style will confuse user.

**Comment by dohoangtung** [comment]
It should be selectable because it can be clicked with onTitleClick event

**Comment by jerryjoy06** [comment]
In the above example, is there anyway to close the menu when I click on the **Navigation Three** - **Submenu**?

**Comment by dohoangtung** [comment]
Trigger onTitleClick then remove class .ant-menu-hidden 
![image](https://user-images.githubusercontent.com/40049759/81384112-67df3200-913b-11ea-8691-149674ef2ba9.png)
