### ISSUE TITLE
table组件点击了展开行后expandedRowRender函数会多次执行

### ISSUE THREAD

**Issue by y805939188** [ant-design/ant-design#22901]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-dzjjd)

### Steps to reproduce
给expandedRowRender函数中随便加个log，点击展开后控制台中会发现多次触发expandedRowRender。

### What is expected?
点击展开只执行一次expandedRowRender

### What is actually happening?
执行多次

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.x |
| System | mac |
| Browser | chrome |

---
不影响render，但是如果有异步请求的话会重复执行ajax

**Comment by afc163** [comment]
副作用操作不能放在 render 流里，这是 React 的规范，建议遵循。

**Comment by y805939188** [comment]
> 副作用操作不能放在 render 流里，这是 React 的规范，建议遵循。

上面我没有表述清楚，我说的那个render不是class的render，指的是expandedRowRender。
就是expandedRowRender这个方法return了一个ReactNode，这个ReactNode是个组件，组件里获取了远程数据。expandedRowRender多次触发，导致组件中的异步操作多次执行，虽然我可以在组件内部优化，但我个人觉得expandedRowRender这个方法应该在展开和收起时各只执行一次是正常的。

**Comment by Patrick-Ren** [comment]
这个应该和你render的组件获不获取远程数据没关系，检查下table的rowKey属性，确保table每行的key都唯一。之前我也遇到这个问题，后端告诉我taskId是唯一标识符，我就rowKey="taskId", 结果他们taskId全重复了

**Comment by Patrick-Ren** [comment]
老哥，我想你应该用onExpand函数：https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx

**Comment by Patrick-Ren** [comment]
可以把数据从子组件提升到父组件，https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx 不过略显麻烦  感觉这个东西是无解的，父组件虽然可以控制子组件何时加载，但如果子组件在componentDidMount后立马调API，那么最终的结果只能是加载多少次就call多少次API

**Comment by afc163** [comment]
expandedRowRender 本身也是在 React render 流程中。

**Comment by afc163** [comment]
Table 扩展行的展开按钮是否展现，现在依赖 expandedRowRender 的返回值，所以需要执行一下才知道需不需要展现。XxxxRender 中只应该有组件的渲染逻辑，不应该放其他副作用逻辑。

**Comment by y805939188** [comment]
> expandedRowRender 本身也是在 React render 流程中。

可能还是我没表述清楚。我没把异步放在render里。https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-dzjjd
比如这个example把异步放在componentdidupdate中，当点击想展开行的时候，会把其他行的expand也rerender。我觉得更理想的情况应该是点击某行，只执行该行的expand的rerender。

**Comment by y805939188** [comment]
> 可以把数据从子组件提升到父组件，https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx 不过略显麻烦 感觉这个东西是无解的，父组件虽然可以控制子组件何时加载，但如果子组件在componentDidMount后立马调API，那么最终的结果只能是加载多少次就call多少次API

我觉得有些场景是依赖点击了expand后获取到record才能知道怎么处理的。所以提升到父组件有时候可能做不到

**Comment by laolaolulu** [comment]
> > 可以把数据从子组件提升到父组件，[https:](https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx) //codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx不过略显麻烦感觉这个东西是无解的，父组件虽然可以控制子组件何时加载，但如果如果子组件在componentDidMount后立马调API，那么最终的结果只能是加载多少次就调用多少次API
> 
> 我觉得有些场景是依赖点击了expand后获取到记录才能知道怎么处理的。所以提升到父组件有时候可能做不到

我也遇到你这个情况,expandedRowRender被执行了很多次,请问你是如何解决的呢

**Comment by y805939188** [comment]
> > > 可以把数据从子组件提升到父组件，[https:](https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx) //codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx不过略显麻烦感觉这个东西是无解的，父组件虽然可以控制子组件何时加载，但如果如果子组件在componentDidMount后立马调API，那么最终的结果只能是加载多少次就调用多少次API
> > 
> > 
> > 我觉得有些场景是依赖点击了expand后获取到记录才能知道怎么处理的。所以提升到父组件有时候可能做不到
> 
> 我也遇到你这个情况,expandedRowRender被执行了很多次,请问你是如何解决的呢

😂😂😂我的解决方式是睁一只眼闭一只眼~因为项目甩给别人了哈哈

**Comment by laolaolulu** [comment]
> > > > 可以把数据从子组件提升到父组件，[https:](https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx) //codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx不过略显麻烦感觉这个东西是无解的，父组件虽然可以控制子组件何时加载，但如果如果子组件在componentDidMount后立马调API，那么最终的结果只能是加载多少次就调用多少次API
> > > 
> > > 
> > > 我觉得有些场景是依赖点击了expand后获取到记录才能知道怎么处理的。所以提升到父组件有时候可能做不到
> > 
> > 
> > 我也遇到你这个情况,expandedRowRender被执行了很多次,请问你是如何解决的呢
> 
> 😂😂😂我的解决方式是睁一只眼闭一只眼~因为项目甩给别人了哈哈

哎,我也想直接放了,可是我的expandedRowRender里面还有个map遍历,点击时浏览器明显卡顿

**Comment by y805939188** [comment]
> > > > > 可以把数据从子组件提升到父组件，[https:](https://codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx) //codesandbox.io/s/qiantaozibiaoge-ant-design-demo-550vx不过略显麻烦感觉这个东西是无解的，父组件虽然可以控制子组件何时加载，但如果如果子组件在componentDidMount后立马调API，那么最终的结果只能是加载多少次就调用多少次API
> > > > 
> > > > 
> > > > 我觉得有些场景是依赖点击了expand后获取到记录才能知道怎么处理的。所以提升到父组件有时候可能做不到
> > > 
> > > 
> > > 我也遇到你这个情况,expandedRowRender被执行了很多次,请问你是如何解决的呢
> > 
> > 
> > 😂😂😂我的解决方式是睁一只眼闭一只眼~因为项目甩给别人了哈哈
> 
> 哎,我也想直接放了,可是我的expandedRowRender里面还有个map遍历,点击时浏览器明显卡顿

map里没啥副作用的话，扔进webworker里头试试呗~

**Comment by bigmgreen** [comment]
这个问题目前是无解了吗？

**Comment by yoyo837** [comment]
render 里面返回的组件自行memo?

**Comment by bigmgreen** [comment]
想要的是点击某行，就执行那行的 expandedRowRender

**Comment by dsherret** [comment]
I got it to work by following the example here: https://github.com/ant-design/ant-design/issues/20027#issuecomment-560209258 (basically, trigger a fetch in `onExpand` and then store the data in some parent state keyed by row)

It's unfortunate that so much complexity is required to achieve this.
