### ISSUE TITLE
Select cursor position is different

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#22906]
<img width="241" alt="image" src="https://user-images.githubusercontent.com/507615/78375897-13a6d680-7600-11ea-890e-948602eb312d.png">

<img width="240" alt="image" src="https://user-images.githubusercontent.com/507615/78375913-1b667b00-7600-11ea-91c1-42db6cf57ef6.png">

<img width="293" alt="image" src="https://user-images.githubusercontent.com/507615/78376189-8912a700-7600-11ea-91fb-b5c3cd7e03c3.png">

**Comment by zombieJ** [comment]
多选有 Selector，所以左上下 padding 是等值的，否则会略丑。和单选不太一样：
<img width="411" alt="截屏2020-04-06 上午11 35 04" src="https://user-images.githubusercontent.com/5378891/78520886-aad77e00-77fa-11ea-9369-75b121e2e350.png">

单选和 Input 的 padding 是相等的。

**Comment by afc163** [comment]
我觉得还是可以优化一下的，保持光标位置统一，但是 padding 和现在一样区别。

**Comment by zombieJ** [comment]
👌 `rc-select` 加个 `has-value` 的 `className` hack 一下好了。
