### ISSUE TITLE
Form add typescript type Store

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#22905]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/8358236/78374797-82833000-75fe-11ea-999a-a69d4e08cab5.png)
![image](https://user-images.githubusercontent.com/8358236/78374820-8911a780-75fe-11ea-8e39-fa064f54c2de.png)

### What is expected?
```js
import { Store } from 'antd/lib/form';
```

### What is actually happening?
```js
import { Store } from 'rc-field-form/lib/interface';
```

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | latest |
| System | windows  |
| Browser | chrome |

**Comment by yoyo837** [comment]
ref: #22755
