### ISSUE TITLE
Transfer的容错能否增强下

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2290]
### 本地环境

- antd 版本: 1.6.3
- 操作系统及其版本：ubuntu 16.04 x64
- 浏览器及其版本:  51.0.2704.79 Ubuntu 16.04 (64-bit)

### 你做了什么？

使用Transfer组件，targetKeys的初始值中有一个key不在左侧列表中

### 你期待的结果是：

Transfer功能正常

## 实际上的结果：

renderItem时报错， Uncaught TypeError: Cannot read property 'title' of undefined

### 可重现的在线演示

http://codepen.io/coderingz/pen/EymAPX

**Comment by afc163** [comment]
感觉这种容错没有必要，不过还是欢迎 PR ~

**Comment by codering** [comment]
@afc163 再问个体验的问题
我在选中了几项，然后再在搜索框中输入搜索项，原有的选中项就丢失了， 保留原有选中状态是否更好些？

搜索前

![image](https://cloud.githubusercontent.com/assets/2271825/16648573/5e1e5248-4467-11e6-9a4d-97884be2a677.png)


搜索后

![image](https://cloud.githubusercontent.com/assets/2271825/16648616/86bb055c-4467-11e6-8428-5cbf323f2432.png)

**Comment by afc163** [comment]
搜索后不再清除选中。

**Comment by codering** [comment]
列表项近1000条的时候，会有卡顿， 这个数据该如何处理比较好些？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2112
