### ISSUE TITLE
filterOption not working with OptGroup

### ISSUE THREAD

**Issue by joaorsfonseca** [ant-design/ant-design#22918]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-user-select-renderer-ddda1e?file=UsersGrouped.js](https://stackblitz.com/edit/react-user-select-renderer-ddda1e?file=UsersGrouped.js)

### Steps to reproduce
filterOption in version 3.10.10 will iterate over all Options.. in version 3.11.0 it only iterates over OptGroup

### What is expected?
i was expecting the same behaviour in version 3.11.0

### What is actually happening?
why this change from version 3.10.10 to 3.11.0?

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome |

---
why? how can i filter the Options inside each OptGroup?
the same occurs with the latest version (3.26.15)

**Comment by kderbalah** [comment]
👍

**Comment by lc-stevenzhang** [comment]
This bug still there, in version 4.1.4.
Reproduce link:
https://codepen.io/ChaoZhang/pen/ExVWdWe?editors=0010

**Comment by jextrevor** [comment]
Having the issue as well.

**Comment by zombieJ** [comment]
Close since v3 ended the maintenance cycle.

**Comment by ericleb010** [comment]
I'm on `3.26.18` with a similar issue. I had to change my `filterOption` function to account for `OptGroup` components:

```javascript
(input, option) => {
  const { children } = option.props;

  if (option.type.isSelectOptGroup) {
    return children.includes(child => child.props.children.toLowerCase().indexOf(input.toLowerCase()) >= 0);
  }
  return children.toLowerCase().indexOf(input.toLowerCase()) >= 0;
}
```

**Comment by katrinanova** [comment]
the bug is present in v4, please reopen

**Comment by zombieJ** [comment]
@katrinanova pls fire new issue instead.

**Comment by munloong** [comment]
is it resolved?

**Comment by cundejo** [comment]
With antd@3.26.18 this works for me:
```
const filterOption = (value, option) => {
  const { children } = option.props;

  if (option.type.isSelectOptGroup) {
    return children.includes((child) => child.props.children.toLowerCase().indexOf(value.toLowerCase()) >= 0);
  }
  return children.toLowerCase().indexOf(value.toLowerCase()) >= 0;
};
```

**Comment by saravanan0701** [comment]
filterOption={(input, option) =>{
                        if(option.children){
                            return option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0 ? true : false;
                        }else if(option.label){
                            return option.label.toLowerCase().indexOf(input.toLowerCase()) >= 0 ? true : false;
                        }
                    }}

**Comment by zhangsenhua** [comment]
the bug is present in v4, please reopen

**Comment by canberkakartuna** [comment]
<Select
              showSearch
              filterOption={(input, option) => {
                if (option.children) {
                  return option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0
                    ? true
                    : false;
                } else if (option.label) {
                  return option.label.toLowerCase().indexOf(input.toLowerCase()) >= 0
                    ? true
                    : false;
                }
              }}
            >
Passing 'showSearch' props along with 'filterOption' works for me.

**Comment by zhangsenhua** [comment]
```js
<Select
    showSearch
    options={[
        {
            label: 'A',
            value: 'A',
            options: [
                {
                    label: 'a',
                    value: 'a',
                },
                {
                    label: 'b',
                    value: 'b',
                }
            ]
        },
        {
            label: 'B',
            value: 'B',
            options: [
                {
                    label: 'aa',
                    value: 'aa',
                },
                {
                    label: 'bb',
                    value: 'bb',
                }
            ]
        },
    ]}
    optionLabelProp="label"
    // children? options? label?
    optionFilterProp="children"
    filterOption={(input, option) => {
        console.log(input, option)
        // return what?
        return true
    }}
/>
```

**Comment by ruskakimov** [comment]
With this `filterOption` it matches both group and children labels (not case sensitive).

```TSX
filterOption={(input, option) => {
  return (
    option?.label.toLowerCase().includes(input.toLowerCase()) ??
    false
  );
}}
```

**Comment by GrayFrost** [comment]
> ```js
> <Select
>     showSearch
>     options={[
>         {
>             label: 'A',
>             value: 'A',
>             options: [
>                 { label: 'a', value: 'a' },
>                 { label: 'b', value: 'b' },
>             ],
>         },
>         {
>             label: 'B',
>             value: 'B',
>             options: [
>                 { label: 'aa', value: 'aa' },
>                 { label: 'bb', value: 'bb' },
>             ],
>         },
>     ]}
>     optionLabelProp="label"
>     // children? options? label?
>     optionFilterProp="children"
>     filterOption={(input, option) => {
>         console.log(input, option)
>         // return what?
>         return true
>     }}
> />
> ```

try this:
```
const filterOption = (input: string, option?: any) => {
  if (option && option.options) {
    return false;
  }
  return option?.label.includes(input);
};
```

**Comment by wuhanjun** [comment]
> With antd@3.26.18 this works for me:
> 
> ```
> const filterOption = (value, option) => {
>   const { children } = option.props;
> 
>   if (option.type.isSelectOptGroup) {
>     return children.includes((child) => child.props.children.toLowerCase().indexOf(value.toLowerCase()) >= 0);
>   }
>   return children.toLowerCase().indexOf(value.toLowerCase()) >= 0;
> };
> ```

return children.includes((child) => child.props.children.toLowerCase().indexOf(value.toLowerCase()) >= 0);

Is this useless? The 'includes' parameter cannot be a function, it will only return false forever
