### ISSUE TITLE
npm registry says "latest" is 3.26.15

### ISSUE THREAD

**Issue by sirlantis** [ant-design/ant-design#22919]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.npmjs.com/package/antd](https://www.npmjs.com/package/antd)

### Steps to reproduce
- Just look at the tag list 

### What is expected?
Latest is 4.1.0

### What is actually happening?
Latest is 3.26.15

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | any |
| System | MacOS |
| Browser | Chrome |

---
Also see https://github.com/ant-design/ant-design/issues/22910 - documentation of v4 also disappeared.

**Comment by rsispal** [comment]
I'm seeing this too, looks like an accidental release has overtaken - https://github.com/ant-design/ant-design/commit/b30832cda17d4b675c6fac3813f7783290e89361

**Comment by Emp2612** [comment]
文档也找不到4.1的文档了，请问发生了什么

**Comment by Patrick-Ren** [comment]
今天npm install antd@latest, 直接从4.0.3来到了3.26.15, 到官网看V4的文档也找不见，心慌慌

**Comment by xrkffgg** [comment]
由于昨晚发布了3.x 的版本发布了 release ，4.1.1 还在待发布中，所以最新的 被 3.26.15 给占据了。待 4.1.1 发布后，就会正常啦

**Comment by xrkffgg** [comment]
你可以先下载 npm install antd@4.1.0。
国内镜像的文档还可以查看。   https://ant-design.gitee.io/components/button/

**Comment by rsispal** [comment]
> 由于昨晚发布了3.x 的版本发布了 release ，4.1.1 还在待发布中，所以最新的 被 3.26.15 给占据了。待 4.1.1 发布后，就会正常啦

It’s a shame that this has completely removed the v4 documentation in the interim.

**Comment by xrkffgg** [comment]
> > 由于昨晚发布了3.x 的版本发布了 release ，4.1.1 还在待发布中，所以最新的 被 3.26.15 给占据了。待 4.1.1 发布后，就会正常啦
> 
> It’s a shame that this has completely removed the v4 documentation in the interim.

You can also interview : https://ant-design.gitee.io/components/button/

**Comment by ycjcl868** [comment]
- npm latest tag had been fixed.
- the official website is being deployed

**Comment by ycjcl868** [comment]
done
