### ISSUE TITLE
Where is the ant.design v4 documentation?

### ISSUE THREAD

**Issue by penalosa** [ant-design/ant-design#22910]
### Reproduction link
[https://ant.design/docs/react/migration-v4](https://ant.design/docs/react/migration-v4)

### Steps to reproduce
As of about an hour ago, the link (https://ant.design/docs/react/migration-v4) pointed to the migration docs from v4 to v4, but now it 404s. There's no mention of Ant Design v4 on ant.design - the latest version is 3.26.15.

**Comment by Qiuhang817385** [comment]
same condition with you

**Comment by Qiuhang817385** [comment]
same condition with me

**Comment by xrkffgg** [comment]
The new version is being upgraded, please wait a moment.

**Comment by Qiuhang817385** [comment]
太勤奋了叭  大早上开始更新了

**Comment by appuntos** [comment]
Same here... really weird. All the component docs for v4 are mssing.

**Comment by xrkffgg** [comment]
You can also use this site: use this site: https://ant-design.gitee.io/components/button/

**Comment by StallionV** [comment]
> The new version is being upgraded, please wait a moment.

If you are upgrading, it would be good if the documentation and upgrade links are still available.
Pulling it out from the everywhere including npm gives a very bad feeling that something is dramatically wrong with the new version.
You should instead keep V4.0 on the current site and show upgrade message instead of 404s

**Comment by NaveenDA** [comment]
It still upgrading?

**Comment by julianklumpers** [comment]
Also when installing antd via `npm` or `yarn`, it installs version 3....

**Comment by caihongxu** [comment]
I also just found out that Ant Design 4 has disappear everywhere. Is there something wrong with it? Should we downgrade to Ant Design 3.x instead?

**Comment by floatrx** [comment]
still waiting for upgrade! :)

**Comment by hengkx** [comment]
Repaired

**Comment by mayormario** [comment]
Thanks, is working now

**Comment by NaveenDA** [comment]
Now Version 4 is available. 😍
