### ISSUE TITLE
Table fixed header without Y-Scroll

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#22914]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently you can only have fixed headers in Ant Table using Yscroll. This means you need to specify the height of the table.
There are cases where we will not know what the height is since it will be based on the records being sent, there may be cases where in you want the height to be dynamic and change based on the height of the rendering element and there are cases where you want the height to just be 100%.

### What does the proposed API look like?
*header: fixed or default*

Remove need to specify y-scroll when using fixed headers.

**Comment by lich-yoo** [comment]
#21066

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12088#issuecomment-475128031
https://github.com/ant-design/ant-design/issues/15340#issuecomment-471927481

`y: 'calc(100vh - 200px)'`

**Comment by StallionV** [comment]
> `y: 'calc(100vh - 200px)'`
Let me try this @afc163, can you also tell how to do that for the footer as well.
So both table header and footer are fixed and the records inside scroll.
Currently the footer as well only shows up at the end of records.
So when picking up flex height, footer and header should both be fixed

**Comment by zombieJ** [comment]
@StallionV,
`calc(100vh - 200px)` is just a css value which is nothing magic on antd side:
https://developer.mozilla.org/en-US/docs/Web/CSS/calc

**Comment by StallionV** [comment]
> @StallionV,
> `calc(100vh - 200px)` is just a css value which is nothing magic on antd side:
> https://developer.mozilla.org/en-US/docs/Web/CSS/calc

Thanks I do understand that, what I meant was add it also as one of the examples since this trick may not be very obvious.
Also do share if there is a similar trick for the footer

**Comment by Yukimotochern** [comment]
'vh' is not a good unit, since it changes all the time in the mobile browser. If only 100 '%' or other css unit can be supported.
[https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser](url)

**Comment by afc163** [comment]
see #21066
