### ISSUE TITLE
Custom Form.Item and Validator value

### ISSUE THREAD

**Issue by PaulPCIO** [ant-design/ant-design#22924]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/custom-form-item-yw40v)

### Steps to reproduce
1. Create a custom <Form.Item> component passing down all the props and forward the ref.
2. Use a custom validator

### What is expected?
The validator to run as normal using the stock <Form.Item>

### What is actually happening?
It does not seem like the props are being passed correctly or maybe a referencing issue? the validator is not triggering, otherwise, when it triggers it uses the `event.target.value` instead of the `onChange value`

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | mac os x  |
| Browser | chrome |

**Comment by zombieJ** [comment]
```diff
const CustomFormItem = React.forwardRef(
  ({ label, children, ...props }, ref) => {
    // you would expect this to function the same as any Form.Item but as you can see stuff like the validator etc are not passed correctly
    return (
      <Form.Item ref={ref} {...props}>
-        {label} {children}
+        {children}
      </Form.Item>
    );
  }
);
```
