### ISSUE TITLE
Modal里面再打开Modal，遮照层不起作用

### ISSUE THREAD

**Issue by wo23wo32** [ant-design/ant-design#2292]
Modal里面打开Modal，遮照层不起作用。看了下遮照层ant-modal-mask的z-index是990。ant-modal-wrap的z-index是1000。后面打开的Modal遮照层z-index还是990，导致遮照层不起作用。现在Modal给的style貌似只能修改ant-modal-wrap的样式，像这样打开两个Modal的情况，不知道有什么好的方法没有
![127_0_0_1_8989_taskmanager_html_taskid_89_](https://cloud.githubusercontent.com/assets/6779656/16645468/bbac5e66-4456-11e6-9734-7fb76a56a825.jpg)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2009
