### ISSUE TITLE
Steps with labelPlacement on vertical not responsively changing to vertical direction

### ISSUE THREAD

**Issue by diw1** [ant-design/ant-design#22922]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-ant-design-demo-7vmtb)

### Steps to reproduce
make view width<480px

### What is expected?
steps should responsively changing to vertical direction

### What is actually happening?
steps with labelPlacement on vertical not change.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | latest |
| System | Windows10 |
| Browser | Chrome lastest |

---
Similar to the issue https://github.com/ant-design/ant-design/issues/14463

顺便，3.26.14的changelog中英文搞反了

**Comment by diw1** [comment]
顺便，3.26.14的changelog中英文搞反了

**Comment by afc163** [comment]
Fixed in antd 4.9.x https://codesandbox.io/s/basic-ant-design-demo-forked-bw296
