### ISSUE TITLE
antd从3.x升级到4.1后报错了

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design#22931]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.暂时没有.com](https://www.暂时没有.com)

### Steps to reproduce
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

### What is expected?
没有报错。在antd3.x时是没有这个错误的。

### What is actually happening?
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 最新版 |
| System | windows10 |
| Browser | chrome 版本 73.0.3683.103（正式版本） （32 位） |

**Comment by effapp** [comment]
![image](https://user-images.githubusercontent.com/51013754/78467376-bebdaa00-773e-11ea-8f9c-affa82cfc17e.png)
![image](https://user-images.githubusercontent.com/51013754/78467380-d137e380-773e-11ea-83c5-46f77d8b3b54.png)

**Comment by AshoneA** [comment]
1. 你可能有多个 React 版本在你项目中。
2. 你可能打破了 Hooks 规格。

**Comment by effapp** [comment]
> 1. 你可能有多个 React 版本在你项目中。
> 2. 你可能打破了 Hooks 规则。

“有多个 React 版本在你项目中”这种情况应该怎么处理？
我在网上搜索了一下，要在配置文件中增加如下语句，请问是哪一个文件夹下的配置文件里增加？
alias: {
        react: path.resolve('./node_modules/react')
      }

**Comment by AshoneA** [comment]
React 强烈不推荐使用多个不同版本的方式。

https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

**Comment by effapp** [comment]
> React 强烈不推荐使用多个不同版本的方式。
> 
> https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

我怎样查看有哪些React版本？怎样消除重复的版本呢？

**Comment by kuku** [comment]
我也碰到类似的问题，我的解决办法是: 把 ./node_modules 这个目录里面的内容全部删掉，然后用 yarn install (如果你用的是 npm ,应该就是 npm install  ) 重新安装一下依赖就好了。

**Comment by Vsion** [comment]
@effapp 后来解决了吗 有什么解决思路么 分享一下 感谢
