### ISSUE TITLE
Table 设置 scroll={{ x: "100%" }} 时，展开多行后展开按钮失效

### ISSUE THREAD

**Issue by BugHiding** [ant-design/ant-design#22938]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kezhankai-ant-design-demo-3g2c1)

### Steps to reproduce
1.  将browser宽度拉大使滚动条滑块不显示。
2.  点击任意展开按钮，使内容超过可视窗口。
3.  再点击任意展开按钮，此时失效。
![5](https://user-images.githubusercontent.com/6602889/78471150-af038d00-7761-11ea-89da-1bdda5a2fede.gif)

### What is expected?
展开按钮一直可用

### What is actually happening?
展开按钮失效

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.12.0 |
| System | macOS 10.15.4 |
| Browser | chrome 80.0.3987.163 |

---
如果有选择框，点击选择框会更新展开状态。
![6](https://user-images.githubusercontent.com/6602889/78471301-ce4eea00-7762-11ea-80cb-fbbb1c0ba0f8.gif)

**Comment by zombieJ** [comment]
奇怪，我重现不出来……还有什么技巧不？

**Comment by BugHiding** [comment]
@zombieJ 
1.  保证宽度足够滑块不要出现。
2.  展开足够多的行使内容超过可视窗口。

**Comment by BugHiding** [comment]
@zombieJ 如果重现不了可以试试火狐浏览器

**Comment by BugHiding** [comment]
3.  打开的时候要没有竖向滚动条，然后一直展开到滚动条出现。

**Comment by BugHiding** [comment]
`chrome 80.0.3987.163`

有竖向滚动条时，展开按钮行为正常。

![8](https://user-images.githubusercontent.com/6602889/78520531-87600380-77f9-11ea-8c75-da4ebab664f9.gif)

竖向滚动条从无到有，展开按钮行为错误。

![9](https://user-images.githubusercontent.com/6602889/78520578-aeb6d080-77f9-11ea-958f-dc19c2a13596.gif)


`safari 13.1`

有竖向滚动条时，展开按钮行为正常。

![10](https://user-images.githubusercontent.com/6602889/78520632-dad25180-77f9-11ea-97be-8e128ac5b208.gif)

竖向滚动条从无到有，展开按钮行为错误。

![11](https://user-images.githubusercontent.com/6602889/78520658-f2a9d580-77f9-11ea-9ce4-2d7887ab553b.gif)

`firefox 74.0.1`

有竖向滚动条时，展开按钮行为正常。

![12](https://user-images.githubusercontent.com/6602889/78520716-179e4880-77fa-11ea-8551-502122feaf98.gif)

竖向滚动条从无到有，展开按钮行为错误。

![13](https://user-images.githubusercontent.com/6602889/78520737-2422a100-77fa-11ea-96d3-a42d0588a5f8.gif)

**Comment by BugHiding** [comment]
@zombieJ  非常抱歉之前的描述非常混乱，我用了几台不同的机器测了一下。

1.  保证宽度足够下方滚动条滑块不显示。（这个条件不确定）
2.  保证高度足够竖向滚动条不显示。
3.  点击足够多个展开按钮使竖向滚动条出现。
4.  再点击展开按钮，这时展开按钮失效。

**Comment by BugHiding** [comment]
@zombieJ  `antd 4.1.1` 这个版本再测就没有这个问题了，虽然不知道发生了什么，感谢！！！
