### ISSUE TITLE
更新antd后 出现的错误

### ISSUE THREAD

**Issue by zhibimohai** [ant-design/ant-design#2293]
### 本地环境

- antd 版本:1.6.3
- 操作系统及其版本：win10
- 浏览器及其版本:chrom 最新版

### 你做了什么？

npm更新antd pack

### 你期待的结果是：

 像官网一样正常显示

## 实际上的结果：

报很多错：
Warning: Unknown props `lg`, `md`, `xs` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

Warning: Unknown props `tag`, `hiddenClassName`, `visible` on <ul> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

Warning: Unknown props `horizontal`, `prefixCls` on <form> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

**Comment by afc163** [comment]
#2258 

遇到问题，先搜索。

#2253  #2276 #2279 #2282
