### ISSUE TITLE
Clicking Button with href prop causes app to reload

### ISSUE THREAD

**Issue by RealDyllon** [ant-design/ant-design#22936]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-button-href-reload-67e0x)

### Steps to reproduce
Clicking the antd <Button/> with href prop causes Entire React app to reload (Unexpected). 
Cliking react-router-dom's <Link/> wrapped around antd-button does not cause reload (Expected).

Click the different buttons in the reproduction to view the different behavior.

### What is expected?
No reload is expected when antd-button with href prop is clicked.

### What is actually happening?
React app reloads when the antd-button with href prop is clicked

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | Windows 10 v1909 |
| Browser | Firefox 74.0.1; Chrome 80.0;  |

**Comment by afc163** [comment]
`<Button href="/" />` is same as `<a href="/" />`: https://codesandbox.io/s/antd-button-href-reload-6ru6m

Please try

```
<Link href="/">
  <Button type="primary">xx</Button>
</Link>
```

**Comment by extempl** [comment]
@afc163 Even so, it shouldn't reload when used as a <Link to={} component={Button}>. And it does because Button href is not a Link (for some reason, like why?)

**Comment by Lyumih** [comment]
Поддерживаю, наблюдаю на анте 5

**Comment by joaolfern** [comment]
HTML standards do not approve wrapping a button with an anchor tag.

Instead I have achieved the react-router-dom V5 navigate effect with with this little wrapper around Button's onClick

```tsx
function AntdButton({ children, href, onClick, ...rest }: ISquareButtonProps) {
  const history = useHistory()

  function handleClick(e: React.MouseEvent<HTMLButtonElement>) {
    if (href) {
      e.preventDefault()
      history.push(href)
      return
    }

    if (onClick) {
      onClick(e)
    }
  }

  return (
    <AntdButton href={href} onClick={handleClick} {...rest}>
      {children}
    </AntdButton>
  )
}

```
