### ISSUE TITLE
RadioGroup使用options配置时可以选择Radio或者Radio.Button

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#22930]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用更方便

### What does the proposed API look like?
```
type='radio'|'button'
```

**Comment by zombieJ** [comment]
#12852

**Comment by DivXPro** [comment]
的确这样更方便。而且适合做适合做二次封装
