### ISSUE TITLE
gtag是什么文件

### ISSUE THREAD

**Issue by liujiaqiang1** [ant-design/ant-design#22940]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/docs/react/introduce-cn](https://3x.ant.design/docs/react/introduce-cn)

### Steps to reproduce
查看network
可以看到发了这样一个请求，https://www.googletagmanager.com/gtag/js?id=UA-72788897-1

### What is expected?
不引用外部文件

### What is actually happening?
引用了外部文件

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | mac |
| Browser | chrome |

---
内网使用的项目，加载不到这个文件，console会报错，有些客户会在意，有什么解决办法吗

**Comment by yoyo837** [comment]
我猜你用了pro吧，搜索GA 相关的删除之

**Comment by yoyo837** [comment]
antd本身没有引用GA

**Comment by yoyo837** [comment]
文档网站引用了是网站用途。
