### ISSUE TITLE
一个页面是否能有两个表单并且是互不影响的

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2294]

**Comment by benjycui** [comment]
可以。

空泛的问题不可能得到具体的回复，麻烦详细描述你的诉求。

**Comment by aw6658913** [comment]
我要做一个带步骤条的页面，第一步跟第二步都有表单，第一步提交后跳转到第二步，但实际第一步跟第二步都在同一个页面，只是我在第一步提交的时候隐藏了第一步的内容然后显示出第二步的内容，这时候问题就来了，我表单是有验证不为空的，然而第一步跟第二步的表单都在一个js的return里，这样的话在第一步表单会不会把没显示的第二步的表单一起验证进去了？（不好意思，我电脑没翻墙注册不了账号没办法提供在线演示，望理解）

**Comment by afc163** [comment]
codepen 不需要注册账号也能使用。

**Comment by dreamcatcher081210** [comment]
一个页面、N个表单组件可以实现。。。

**Comment by dreamcatcher081210** [comment]
官网的Form - demo不就是那样的么。。。

**Comment by aw6658913** [comment]
我的意思是 两个像这样<Form></Form>闭合的表单组件，官网都是一个Form组件闭合

**Comment by aw6658913** [comment]
@afc163 我要FORK的时候就会提示我登录了，登录就要注册了

**Comment by afc163** [comment]
![](https://zos.alipayobjects.com/rmsportal/UygKwQLwPvcngIL.png)

**Comment by aw6658913** [comment]
在线演示如下，有两个确定按钮，我想点击确定获取是各自表单的内容，而不是全部的，http://codepen.io/anon/pen/wWqkxy?editors=1010

**Comment by aw6658913** [comment]
没办法实现吗？

**Comment by afc163** [comment]
```jsx
const BasicDemoForm1 = createForm()(BasicDemo1);

const BasicDemoForm2 = createForm()(BasicDemo2);

const BasicDemoForm3 = createForm()(BasicDemo3);
```

几个表单就建立几个高阶组件，应该是可行的。

**Comment by aw6658913** [comment]
`createForm()(BasicDemo1) 这个中的BasicDemo1 应该是对应一个React.createClass吧？我在线演示的都在同一个里面没办法分开定义吧？`

**Comment by aw6658913** [comment]
@benjycui 能看下我那个在线演示，要怎么点击确认按钮获取的是各自`<form></form>`标签内的表单数据吗#2383

**Comment by benjycui** [comment]
重构，把表单拆分成两个。

既然这两部分表单的数据是独立的，那么把它们拆分成两个组件，也是合理的。

**Comment by whiteblueblack** [comment]
抱歉，感觉没有解决问题。请问同页面两个表单，如何验证数据呢？例如官方案例：
[https://codepen.io/whiteblueya/pen/GMEgXx?&editors=001](url)
一个表单的确定事件为：
`handleCreate = () => {
    const form = this.form;
    form.validateFields((err, values) => {
      if (err) {
        return;
      }
      console.log('Received values of form: ', values);
      form.resetFields();
      this.setState({ visible: false });
    });
  }`
那么另一个表单的确认事件该怎么写呢？`this.form`只能获取当前的form的引用吧？两个就冲突了。

**Comment by belief-cyf** [comment]
所以最终解决方案多个表单还是不能放到一个组件里面 必须独立封装为不同的小组件咯？

**Comment by fly-sheep** [comment]
> ```js-jsx
> const BasicDemoForm1 = Form.create()(BasicDemo1);
> 
> const BasicDemoForm2 = Form.create()(BasicDemo2);
> 
> const BasicDemoForm3 = Form.create()(BasicDemo3);
> 
> render(
>   <div>
>     <BasicDemoForm1 />
>     <BasicDemoForm2 />
>     <BasicDemoForm3 />
>   </div>
> )
> ```
> 
> 几个表单就建立几个高阶组件，应该是可行的。

如果

**Comment by lbyupup** [comment]
请问如果一个页面有两个表单 通过一个状态来切换，首次渲染的表单 form实例使用正常，可是切换后的表单form实例始终拿不到字段数据是为什么呢？
