### ISSUE TITLE
Dark mode vertical menu submenu items have incorrect color styles

### ISSUE THREAD

**Issue by deoxxa** [ant-design/ant-design#22949]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu/#components-menu-demo-switch-mode](https://ant.design/components/menu/#components-menu-demo-switch-mode)

### Steps to reproduce
Check both the "change mode" and "change style" toggles, then hover over the submenu.

### What is expected?
The text should be dark on a light background.

### What is actually happening?
The text is light on a light background.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12 |
| System | Ubuntu Linux |
| Browser | Chrome Version 80.0.3987.132 (Official Build) (64-bit) |

**Comment by delyanr** [comment]
FYI, I'm currently migrating from v3 to v4, and I'm almost certain there was NO issue with v4.1.0, but it appeared in v4.1.1.

**Comment by SteffeyDev** [comment]
I'm seeing the same issue since upgrading from 4.1.0 to 4.1.1, appears to be a regression
