### ISSUE TITLE
Ant Table in minified production deployment crashes

### ISSUE THREAD

**Issue by samuelhalff** [ant-design/ant-design#22943]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://csb-hq5y0-87mvlx2us.now.sh/
Link to source: https://codesandbox.io/live/O78yyg

### Steps to reproduce
Build react, antd 4.1, using parcel-bundler 1.12.4, deployed in production and minified.
Not minified does not crash.

### What is expected?
Basic Table, from antd documentation, rendering, with no issue.

### What is actually happening?
Rendering Table crashes with error:
```
h is not  a function.
```
Error seems to arise within a usememo. Difficult to determine the origin. 

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.3.1 |
| parcel-bundler | 1.12.4 |
| System | Debian 10.3 |
| Browser | Chrome latest  |

**Comment by samuelhalff** [comment]
This cannot be reproduced on a sandbox.

**Comment by samuelhalff** [comment]
Reproduction with web pack actually works. We use parcel. 
The issue might be with parcel, looking into it now.

**Comment by FocusCare** [comment]
![11](https://user-images.githubusercontent.com/3634726/79136658-f0d8a700-7de3-11ea-97c3-1724fe8e63cf.png)
3Provider : 
1. BodyContext
2. ResizeContext
3. TableContext
hase same code like:
```
import * as React from 'react';
export default React.createContext(null);
```
when use parcel bundler has the same hash;

**Comment by samuelhalff** [comment]
@FocusCare Thank you but is there a fix we can apply? This is kind of urgent for us.
Thanks a lot.

**Comment by FocusCare** [comment]
https://github.com/react-component/table/pull/457
@samuelhalff create pl, after rc-table merge code and push new npm version

**Comment by FocusCare** [comment]
write a script to change code before build.
i fix now like this:
1.  fix-rc-table-source-code.js
```
const path = require('path');
const fs = require('fs');

const fileList = ['BodyContext.js', 'ResizeContext.js', 'TableContext.js'];
const folder = path.resolve(__dirname, '../node_modules/rc-table/es/context');

fileList.forEach(item => {
  const file = path.resolve(folder, item);
  const context = fs.readFileSync(file).toString();
  if (!/console/mg.test(context)) {
    fs.writeFileSync(file, `${context}console.log('${item}')`)
  }
})

```
2. build cmd like this:
```
node scripts/fix-rc-table-source-code.js && parcel build ./src/index.html
```

**Comment by zombieJ** [comment]
Hi all.
This is parcel bug. Please fire bug to parcel instead of patching to `rc-table`. It's not a `rc-table` bug.

**Comment by KunalBonage** [comment]
> write a script to change code before build.
> i fix now like this:
> 
> 1. fix-rc-table-source-code.js
> 
> ```
> const path = require('path');
> const fs = require('fs');
> 
> const fileList = ['BodyContext.js', 'ResizeContext.js', 'TableContext.js'];
> const folder = path.resolve(__dirname, '../node_modules/rc-table/es/context');
> 
> fileList.forEach(item => {
>   const file = path.resolve(folder, item);
>   const context = fs.readFileSync(file).toString();
>   if (!/console/mg.test(context)) {
>     fs.writeFileSync(file, `${context}console.log('${item}')`)
>   }
> })
> ```
> 
> 1. build cmd like this:
> 
> ```
> node scripts/fix-rc-table-source-code.js && parcel build ./src/index.html
> ```

I am trying to apply this patch, but still not getting expected output. Can you please let me know if anything other changes needs to be done.

**Comment by pratik-github** [comment]
It would be really gr8 to have a workaround till the time parcel fix this

**Comment by pratik-github** [comment]
> write a script to change code before build.
> i fix now like this:
> 
> 1. fix-rc-table-source-code.js
> 
> ```
> const path = require('path');
> const fs = require('fs');
> 
> const fileList = ['BodyContext.js', 'ResizeContext.js', 'TableContext.js'];
> const folder = path.resolve(__dirname, '../node_modules/rc-table/es/context');
> 
> fileList.forEach(item => {
>   const file = path.resolve(folder, item);
>   const context = fs.readFileSync(file).toString();
>   if (!/console/mg.test(context)) {
>     fs.writeFileSync(file, `${context}console.log('${item}')`)
>   }
> })
> ```
> 
> 1. build cmd like this:
> 
> ```
> node scripts/fix-rc-table-source-code.js && parcel build ./src/index.html
> ```

seems this is not working.. can you help

**Comment by vincelwt** [comment]
> write a script to change code before build.
> i fix now like this:
> 
> 1. fix-rc-table-source-code.js
> 
> ```
> const path = require('path');
> const fs = require('fs');
> 
> const fileList = ['BodyContext.js', 'ResizeContext.js', 'TableContext.js'];
> const folder = path.resolve(__dirname, '../node_modules/rc-table/es/context');
> 
> fileList.forEach(item => {
>   const file = path.resolve(folder, item);
>   const context = fs.readFileSync(file).toString();
>   if (!/console/mg.test(context)) {
>     fs.writeFileSync(file, `${context}console.log('${item}')`)
>   }
> })
> ```
> 
> 1. build cmd like this:
> 
> ```
> node scripts/fix-rc-table-source-code.js && parcel build ./src/index.html
> ```

Worked for me, thanks a lot

**Comment by chico-malo** [comment]
我也遇到了同样的问题，非常感谢。

> write a script to change code before build.
> i fix now like this:
> 
> 1. fix-rc-table-source-code.js
> 
> ```
> const path = require('path');
> const fs = require('fs');
> 
> const fileList = ['BodyContext.js', 'ResizeContext.js', 'TableContext.js'];
> const folder = path.resolve(__dirname, '../node_modules/rc-table/es/context');
> 
> fileList.forEach(item => {
>   const file = path.resolve(folder, item);
>   const context = fs.readFileSync(file).toString();
>   if (!/console/mg.test(context)) {
>     fs.writeFileSync(file, `${context}console.log('${item}')`)
>   }
> })
> ```
> 
> 1. build cmd like this:
> 
> ```
> node scripts/fix-rc-table-source-code.js && parcel build ./src/index.html
> ```

I have  the same problem. Thank you very much.

**Comment by samuelhalff** [comment]
Any progress in solving this? Nothing on parcel, can't antd push a quick fix in the meantime? This is very problematic for our project.
Thanks a lot.

**Comment by Hexagonale** [comment]
If anyone looking for solution parcel seems to sort it out. I need to test it tomorrow.

https://github.com/parcel-bundler/parcel/issues/3368#issuecomment-520908190
