### ISSUE TITLE
Default value property of TreeSelect doesn't work with Form Item when declared name for it

### ISSUE THREAD

**Issue by minhluan96** [ant-design/ant-design#22944]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-methods-class-component-ant-design-demo-kkwyz?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1. Create a Form
2. Create a TreeSelect with defaultValue property in the Form.Item
3. Assign name for that Form.Item

### What is expected?
The defaultValue of TreeSelect should be shown as normal when they weren't assigned name to the Form.Item

### What is actually happening?
Unable to assign default value for TreeSelect if they were in the Form.Item has name property

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.9.0 |
| System | MacOS Catalina 10.15.4 |
| Browser | Brave browser Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit) |

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/commit/6fc0ca089e672d11fc5a7858b21e6b8ee4e47a7f
