### ISSUE TITLE
table 固定前后列数据过多时样式会歪掉

### ISSUE THREAD

**Issue by yukiyuki1900** [ant-design/ant-design#2295]
使用了固定前2列和后2列，中间列可滚动

目前样式歪掉：
![aaa](https://cloud.githubusercontent.com/assets/8652560/16647688/fe077a5a-4462-11e6-9ea6-eddad838b9e0.png)

因为之前是没有歪掉的，所以查了下./node_modules/antd/antd.css的代码，发现之前有段样式没有了

![aaa](https://cloud.githubusercontent.com/assets/8652560/16647776/6918ea04-4463-11e6-8e4f-8a5b273f2faf.png)

加上这段代码就没问题了，请问什么要去掉这段样式呢？

我的antd版本是最新1.6.2的

**Comment by afc163** [comment]
这段样式会造成其他错位问题，而且单元格就无法换行了。

你需要给 `scroll={{ x: 1000 }}` 加上具体的宽度。

**Comment by yukiyuki1900** [comment]
好的没问题了，谢谢

**Comment by afc163** [comment]
解决了建议自己关掉。
