### ISSUE TITLE
RangePicker 的类型丢失

### ISSUE THREAD

**Issue by free-D** [ant-design/ant-design#22955]
The issue which is not created via http://new-issue.ant.design will be closed immediately.

(property) RangePicker: React.ForwardRefExoticComponent<TimeRangePickerProps & React.RefAttributes<any>>
Property 'picker' is missing in type '{}' but required in type 'TimeRangePickerProps'.ts(2741)

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by Lizhooh** [comment]
同样的情况，用 antd 4，typescript 更新到 3.9.5，也报错，服了。

![微信截图_20200625101624](https://user-images.githubusercontent.com/19299088/85645688-08c68400-b6cd-11ea-94b3-77b600e2d7a4.png)
