### ISSUE TITLE
Upload组件无法识别带有压缩参数的图片路径

### ISSUE THREAD

**Issue by lincolon** [ant-design/ant-design#22958]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
调用Upload组件，参数fileList=[{uid: 1, status: 'done', name: 'name', url: 'https://xxx.jpg!compress'}]，【!compress】是通过阿里云图片压缩服务得到的压缩后缀，按照这种调用方式，图片无法渲染，同样的图片路径，在Avatar组件里面可以渲染。

### What is expected?
图片正常渲染

### What is actually happening?
图片未显示

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | react@16.12.0 |
| System | MacOS10.15 |
| Browser | chrome80 |

**Comment by afc163** [comment]
阿里云图片压缩服务的文档能提供一个链接么？

**Comment by lincolon** [comment]
> 阿里云图片压缩服务的文档能提供一个链接么？

https://test-file.smart-store.2bao.org/2020/04/02/VpaCn3O3pb4dRKKP.jpg!thumb

**Comment by lincolon** [comment]
> 阿里云图片压缩服务的文档能提供一个链接么？

问题已解决，换了一个分隔符就可以了，自定义规则里支持【-，_，!，/】四种分隔符，只有采用【 / 】时，Upload组件可以正常渲染出图片。

使用的是阿里云OSS图片处理https://help.aliyun.com/document_detail/48884.html?spm=5176.8466010.0.0.3cdd1450aVOz87；
图片处理域名规则
默认规则：域名/sample.jpg?x-oss-process=style/stylename
自定义规则：域名/sample.jpg自定义分隔符stylename
我们采用的是自定义规则
