### ISSUE TITLE
Hack code in dark theme

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#22959]
```diff
+     options: {
+       modifyVars: {
+          'hack': `true;@import "${require.resolve('antd/lib/style/color/colorPalette.less')}";`,
+          ...darkTheme,
+          ...compactTheme,
+       },
+       javascriptEnabled: true,
+     },
```

https://ant.design/docs/react/customize-theme-cn

```
'hack': `true;@import "${require.resolve('antd/lib/style/color/colorPalette.less')}";`,
```

这一行很丑陋，是否有办法去掉。

**Comment by AshoneA** [comment]
我有点不明白 `hack` 这个 key 是个啥意思... 找遍了 less-loader 和 less 文档也没找到这个关键字。还是说只是个 magic string 吗，实际上没有意义。

**Comment by zombieJ** [comment]
less 的变量修改是直接将变量值添加到最后：
```js
'primary-color': '#1DA57A'
```
变成：
```less
// 原本的 less 内容

@primary-color: #1DA57A;
````

它本身不支持动态 `@import`，所以这段代码其实就是直接注入了代码：
```less
@hack: true;@import "antd/lib/style/color/colorPalette.less";
```

**Comment by vipcxj** [comment]
我写了个样式模板框架，基本就是解决less笨重的变量注入问题。不同于市面上那些着眼于style属性的，我这个是运行时根据模板生成css注入到网页的`<style>`标签里。并且支持运行时修改注入的变量。antd的css变量都是靠less搞定，但这个less编译太慢了，而且运行时也没法修改，所以我就搞了这个东西。目前处于alpha版本，就我自己在用。虽然功能一大堆，配置项很多，但其实只测试了主要功能。文档都没写~
我这[工程](https://github.com/vipcxj/themed-styles)分三部分
[themed-styles](https://github.com/vipcxj/themed-styles/tree/master/packages/themed-styles)是主体，本质上是一个postcss插件和一个webpack插件。所以我这东西必须配合webpack使用。配置时只需要用到webpack插件，它会自动调用postcss插件来生成运行时的模板编译代码。
[themed-styles-runtime](https://github.com/vipcxj/themed-styles/tree/master/packages/themed-styles-runtime)是运行时组件，类似`@babel/runtime`。
[themed-styles-react](https://github.com/vipcxj/themed-styles/tree/master/packages/themed-styles-react)不是必须的，甚至其实和其他两个组件没啥关系，就是个context。
虽然这套框架是支持运行时修改任何注入的css变量的，但使用起来还是主题的方式。将变量方案整合为一个主体，导入样式时
```javascript
import styles from 'style.tcss';
const [defaultClass, classes] = styles.useTheme('theme name');
```
`defaultClass`只有当样式不包含类名时，才有意义，框架会自动生成一个类来修饰那些不包含类名的样式，来保证它们的局部性。类似于css-loader，webpack插件的设置里可以改成默认全局，这样就没有这个逻辑了。
`classes`就是和传统import的东西一样了，键为编写时的类名，值为运行时真正的类名。
这个框架应该可以和其他任何样式工具混用。换句话说可以同时import这个框架支持的模板文件和一般css和less文件。这样可以仅仅将动态的那部分样式分离出来弄成模板。

**Comment by AshoneA** [comment]
这个貌似也好关了？

**Comment by afc163** [comment]
所以是不是更应该都用 `globalVars` 而不是 `modifyVars`？

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/91161459-5bd4ab80-e6fd-11ea-87b2-e3eee652ce44.png)

'hack': `true;@import "${require.resolve('antd/lib/style/color/colorPalette.less')}";

这句用在 `dark` theme 作为 js 主题变量的场景，不加则会报错
