### ISSUE TITLE
AutoComplete.Option not possible with custom input in V4

### ISSUE THREAD

**Issue by Mainachtsmann** [ant-design/ant-design#22965]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-xy6l3)

### Steps to reproduce
Use AutoComplete and set an OptionsArray [AutoComplete.Option, ...] into new options property

### What is expected?
Normal Options dropdown will be shown

### What is actually happening?
=> Warning: Invalid values for props `$$typeof`, `type` on <div> tag ........
white Options open up

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Firefox 75.0b12 |

---
OptionsArray should be set into children but this is not possible if you have a customized Input
See my CodeSandbox

**Comment by zombieJ** [comment]
https://ant.design/components/auto-complete-cn/#components-auto-complete-demo-custom

**Comment by baqihg** [comment]
如果我想自定义下拉选项，又想自定义输入框，V4是不是就实现不了了？

V3 可以把自定义下拉选项可以设置到 dataSource 上，然后输入框设置到 children 来实现这个需求。

**Comment by zombieJ** [comment]
`options` 属性
