### ISSUE TITLE
The project's antd3 overwrites the third-party component's antd4

### ISSUE THREAD

**Issue by wangdanting** [ant-design/ant-design#22961]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
The dependency version of antd used in the project is 3.24.3.
The antd dependency version of the third-party component is antd4.1.1. And Local run is correct.
After the project introduces third-party components, antd4.1.1 in the third-party components becomes invalid, and the third-party components become version 3.

### What is expected?
Third-party components use antd4

### What is actually happening?
The project's antd3 overwrites the third-party component's antd4

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome |

---
Third-party component configuration
package.json
```
"peerDependencies": {
    "react": ">=16.12.0",
    "react-dom": ">=16.12.0",
    "typescript": ">=3.8.4",
    "antd": ">=4.0.0"
  },
  "dependencies": {
    "@ant-design/icons": "^4.0.5",
    "antd": "^4.1.1"
  },
"devDependencies": {
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "typescript": "3.8.4"
  },
```

My Project configuration
package.json
```
"dependencies": {
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
   "antd": "^3.24.3",
  },
```

**Comment by afc163** [comment]
I don't think it is our problem, don't use mixed version of antd in one project.

**Comment by wangdanting** [comment]
> I don't think it is our problem, don't use mixed version of antd in one project.

What should I do, the third-party library uses the latest antd4, and my project uses ant3.

**Comment by yoyo837** [comment]
Upgrade your `antd`  to same version, or get some supports from third-party library.
