### ISSUE TITLE
在使用Tree树形组件->拖动示例（draggable）在mobx下使用错误

### ISSUE THREAD

**Issue by xiaofine1122** [ant-design/ant-design#22964]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
组件示例代码中在forEach中修改了数组的信息，在标准js环境中没问题。
但是如果使用 mobx 就会出现下面错误
“mobx.module.js:3138 Uncaught Error: [mobx] Modification exception: the internal structure of an observable array was changed”

之后询问了mobx社区，在数组中应该尽量避免在forEach循环中修改数组
原文链接 https://github.com/mobxjs/mobx/issues/2326

### What does the proposed API look like?
建议将Tree组件拖动示例中的forEach 替换成其他的循环方式
```
  const loop = (data, key, callback) => {
      data.forEach((item, index, arr) => {
        if (item.key === key) {
          return callback(item, index, arr);
        }
        if (item.children) {
          return loop(item.children, key, callback);
        }
      });
    };
```

**Comment by zombieJ** [comment]
@xiaofine1122，直接来个 PR 改掉例子吧~
