### ISSUE TITLE
Icon in button not horizontally aligned in compact input group

### ISSUE THREAD

**Issue by florianMo** [ant-design/ant-design#22967]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/size-ant-design-demo-cms3v?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Setup an Input.Group with "compact" attribute, add an Input and a icon-only button.

### What is expected?
Icon in button should be horizontally centered

### What is actually happening?
Icon in button is left aligned.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13 |
| System | Linux Mint 19 |
| Browser | Chrome 80 |

---
This seems to be caused by a display:inline-flex on .ant-input-group.ant-input-group-compact > *, overriding the display:inline-block from .ant-btn.

**Comment by zombieJ** [comment]
This patch breaks the align: https://github.com/ant-design/ant-design/pull/22197/files#diff-6d9cc1a7ae7831e12b8dd36d676c99ffR342
