### ISSUE TITLE
AntD Table - Search textbox to filter/search in all columns

### ISSUE THREAD

**Issue by mbv401920150** [ant-design/ant-design#22969]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I previously used Material Table, and the only thing that I miss is the option to search/filter this table because the filter performs in all columns.
https://material-table.com/#/docs/features/search

### What does the proposed API look like?
Have the option to enable or disable the search option based on the API (Like the Material UI Table)

**Comment by afc163** [comment]
You can create your table by composing Table and Input component, or you can try https://github.com/ant-design/pro-table/

**Comment by mbv401920150** [comment]
Well, the Pro-table doesn't work... but, I created a quick and easy example of how it should work...


If somebody else required inspiration... check out this code:
`https://codesandbox.io/s/basic-usage-ant-design-demo-2swep?file=/index.js`

I will need to include more code to validate when the column is a picklist/Combobox/select option instead of plain text... but I will work on that!

**Comment by Vishnu-Das** [comment]
@mbv401920150 codeSandBox link is not active any more can you send it once more. Thanks

**Comment by mbv401920150** [comment]
> @mbv401920150 codeSandBox link is not active any more can you send it once more. Thanks

Seems that still working, please check again... FYI, this is the link:
https://codesandbox.io/s/basic-usage-ant-design-demo-2swep?file=/index.js

**Comment by deep-link** [comment]
This would be help you,

`<Table
                    loading={loading || dataTableLoading}
                    pagination={{
                        onChange: (page, recordsPerPage) => this.paginate(page, recordsPerPage),
                        total,
                        defaultPageSize: 10
                    }}
                    onChange={(pagination,unknown,sortedColumn,action)=>{
                        /*Do your remort search*/
                    }}
                    filterMultiple={true}
                    rowSelection={rowSelection}
                    dataSource={data}>`

**Comment by GokulVertex** [comment]
how to ant design table search in function components

**Comment by duanduan321** [comment]
> > @mbv401920150 codeSandBox link is not active any more can you send it once more. Thanks
> 
> Seems that still working, please check again... FYI, this is the link:
> https://codesandbox.io/s/basic-usage-ant-design-demo-2swep?file=/index.js

this works partially, because if you have other values in the object and one of them is not in any column of your table, that is, it is not being used for some reason, and if you search for it, the filter will return true exemple. How to solve this?
![image](https://user-images.githubusercontent.com/86322662/123484900-79092d80-d5df-11eb-8042-87f0ca2eaff6.png)

**Comment by MrUsmanDev** [comment]
you can add TextBoxes in each columns like this 

 const columns = [
    {
      
      title:<span className="dragHandler">Name</span>,
      dataIndex: 'name',
      key: '1',
      sorter: (a, b) => a.name.length - b.name.length,
      sortDirections: ['ascend', 'descend'],
      sortIcon: (sortDir) => {
        if (sortDir.sortOrder === 'ascend') return <CaretUpOutlined />;
        if (sortDir.sortOrder === 'descend') return <CaretDownOutlined />;
        return  <CaretUpOutlined />; // Return null if no sorting direction is set
      },
      render: ()=> <Input />,
      children:[
        {
          title: <Input />,
          dataIndex: 'name',
          key: 'name',
        }
      ],
      ...getColumnSearchProps('name'),
      
      
    }],

**Comment by BhushanChandak** [comment]
> > > @mbv401920150 codeSandBox link is not active any more can you send it once more. Thanks
> > 
> > 
> > Seems that still working, please check again... FYI, this is the link:
> > https://codesandbox.io/s/basic-usage-ant-design-demo-2swep?file=/index.js
> 
> this works partially, because if you have other values in the object and one of them is not in any column of your table, that is, it is not being used for some reason, and if you search for it, the filter will return true exemple. How to solve this? ![image](https://user-images.githubusercontent.com/86322662/123484900-79092d80-d5df-11eb-8042-87f0ca2eaff6.png)

I have made some changes in search method 
![Uploading 20240718_142629.jpg…]()
