### ISSUE TITLE
Passing onOK to a DatePicker should consistently enable the OK button in the calendar

### ISSUE THREAD

**Issue by SpringsTea** [ant-design/ant-design#22966]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently the only way to enable the OK button and use the `onOK` callback is to pass a `showTime` format.
This means you can't display the OK button for dates without time.

Iin the case of a `RangePicker` I cannot require the user enter both ends of the range at a time when modifying an existing range, so they have to either open the calendar twice to put in each date (triggering `onChange` twice) or clear the date before re-entering.

### What does the proposed API look like?
```
<DatePicker
onOk={handleOK}
...
/>
```
If `onOK` is a prop, enable the ok button to display in the calendar.

**Comment by zombieJ** [comment]
> Iin the case of a RangePicker I cannot require the user enter both ends of the range at a time when modifying an existing range, so they have to either open the calendar twice to put in each date (triggering onChange twice) or clear the date before re-entering.

Could you describe more about this? I can not get the point of relation with ok button.

**Comment by SpringsTea** [comment]
When a date range picker has two dates, you can only set one date at a time. Selecting a date triggers `onChange` and closes the calendar. 

For example, the picker is currently on a range from this week, and you want a one month range from 6 months ago. You open the calendar and select a start date of 6 months ago. The calendar closes, and `onChange` triggers, filtering the whole 6 month period (because the second half of the range is still on a current date). Then they open the calendar again and repeat the process.

This behavior can only be avoided by either:
- Clearing the picker before choosing a new range, because an empty picker will wait for the user to fill both dates
- Passing `showTime` which keeps the calendar open so the user can set the time, and utilizes the `onOk` prop.

For pickers that don't need time, I think forcing this behavior when `onOK` is passed makes sense.

**Comment by DeepAnchor** [comment]
It would be very helpful if the RangePicker could have an 'ok' option to confirm, just like DatePicker time option! This will allow the user to select a range without the popup automatically closing each time.

[Example](https://i.imgur.com/YdH6O9B.png)

Want:
[Allow 'ok' button to confirm on RangePicker](https://i.imgur.com/b7rVBDO.png)

Thank you!

**Comment by itamardavidyan** [comment]
> It would be very helpful if the RangePicker could have an 'ok' option to confirm, just like DatePicker time option! This will allow the user to select a range without the popup automatically closing each time.
> 
> [Example](https://i.imgur.com/YdH6O9B.png)
> 
> Want:
> [Allow 'ok' button to confirm on RangePicker](https://i.imgur.com/b7rVBDO.png)
> 
> Thank you!

Join for @DeepAnchor  request

**Comment by softshape** [comment]
We've found that Range Picker works best with OK button enabled (in our UX scenario). Unfortunately, the button won't work with weeks, months. and years mode. It's displayed only in date+time mode.

Any way to enable it permanently would be really useful.

**Comment by rohit-sourcefuse** [comment]
We are also facing a similar issue, can you please share any alternative.

**Comment by kennybecerra** [comment]
Are there any updates on this issue or a work around for adding enabling Ok button in RangePicker ?

**Comment by victoray** [comment]
any update on this feature

**Comment by dineshadhikari** [comment]
looking for  update on this feature

**Comment by imsid1996** [comment]
I found one work around for this issue.

for range picker, set showTimer to yes and in css hide timer panel by overriding class(ant-picker-time-panel).
.ant-picker-time-panel {
		display: none;
	}
**Note:** to handle side effect where time panel get hide for other elements as well, try to override class with parent class.

now in selected values it shows current time, to handle time in values pass props format="yyyy-mm-dd" which will hide time in values,

<RangePicker
					onChange={onChange}
					format="YYYY-MM-DD"
					showTime
				/>

now you will get dates with okay button,

to style ok button, override class .ant-btn-primary by selecting parent class(i.e. .ant-picker-range-wrapper) through which btn will not get override globally.

.ant-picker-range-wrapper .ant-btn-primary{
/* your styling goes here */

To replace OK button text.
just put below css 

.ant-btn-primary {
font-size: 0 !important;
}

.ant-btn-primary:after {
		content: "Apply" !important; /* Text whatever you want */
		font-size: 16px; /* original font size */
	}

**Comment by ishehov** [comment]
I wholeheartedly support the speakers above (and keeping github-actions bot busy), any updates on this?

**Comment by niklaaa** [comment]
to show OK button set showTime....why why

**Comment by Megatey** [comment]
Please anyone with an idea on how i can change the background color of ok button to blue when selecting date

**Comment by LimhorngSok** [comment]
Any update on this issue?

**Comment by tuantruong625** [comment]
Bump, any updates?

**Comment by noblenihal** [comment]
@SpringsTea Any updates ?

**Comment by chidera-ugo** [comment]
any updates?

**Comment by 0x-s13i** [comment]
Any updates?

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
