### ISSUE TITLE
官网更新日志下拉框出现省略号

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#22974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
查看官网

### What is expected?
自适应内容宽度,或设置下拉框宽度

### What is actually happening?
出现省略号

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16 |
| System | win10 |
| Browser | chrome |

![0F40FA8E-7EE5-4B3E-85CA-1CE79901D90A](https://user-images.githubusercontent.com/15940920/78624675-c905b280-78bc-11ea-9480-85eb29d18e12.png)

**Comment by l745230** [comment]
已经好几个4.x版本都是这样,没看到有修复.. 就我的电脑会这样么-,-

**Comment by afc163** [comment]
<img width="702" alt="image" src="https://user-images.githubusercontent.com/507615/78625168-ee46f080-78bd-11ea-87cc-b6ee46a14fa0.png">

我这里是这样的。

**Comment by zombieJ** [comment]
<img width="286" alt="截屏2020-04-07 上午11 18 43" src="https://user-images.githubusercontent.com/5378891/78626511-8befef00-78c1-11ea-830b-a7830504a3ec.png">
模拟器里跑也是好的。

@l745230 能帮忙看看不？

**Comment by kaoding** [comment]
IE11  出现省略号

**Comment by l745230** [comment]
看了下版本.
Mac 下
Chromium 69.0.3497.81 出现省略号
80.0.3987.149（正式版本） （64 位） 正常.

**Comment by l745230** [comment]
![image](https://user-images.githubusercontent.com/15940920/78628421-a4aed380-78c6-11ea-82ab-6f4687cd4213.png)

Chromium 69.0.3497.81 版本,查看官网有省略号,查看gitee的镜像版本,显示正常.

**Comment by afc163** [comment]
请访问：https://ant-design.gitee.io/index-cn

**Comment by afc163** [comment]
你这个网站没意义了，我下掉了。

**Comment by afc163** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/507615/78628871-20f5e680-78c8-11ea-94fe-eb6e9afe8b9f.png">

另外，你 chrome 的版本是不是太老了，升级上来试试。
