### ISSUE TITLE
Popover which triggered by context-menu couldn't handle first click event

### ISSUE THREAD

**Issue by uni-zheng** [ant-design/ant-design#22985]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/unizheng/pen/eYNqryK?editable=true&editors=001](https://codepen.io/unizheng/pen/eYNqryK?editable=true&editors=001)

### Steps to reproduce
1. right click button
2. click content in popover

### What is expected?
show an alert

### What is actually happening?
not show an alert

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | latest |
| System | mac |
| Browser | chrome |

---
the alert will show on second click

**Comment by afc163** [comment]
It works well in your codepen, alert shows as expected. Am I miss something?

**Comment by RealDyllon** [comment]
> It works well in your codepen, alert shows as expected. Am I miss something?

@afc163 The alert doesn't display when clicking the first time. The user has to click a second time to display the alert .

**Comment by afc163** [comment]
![2020-04-07 17-43-25 2020-04-07 17_44_00](https://user-images.githubusercontent.com/507615/78654629-62ea5100-78f7-11ea-8796-83e8fb6cc1de.gif)

`alert` display at first click here, you can see it in gif.

**Comment by RealDyllon** [comment]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/25902208/78656050-68489b00-78f9-11ea-98db-0b2c462737d2.gif)

I'm experiencing this issue on Chrome 80 (see attached gif)

**Comment by RealDyllon** [comment]
Just to clarify: It's only on the first click after app load.

**Comment by afc163** [comment]
<img width="294" alt="image" src="https://user-images.githubusercontent.com/507615/78658586-e78b9e00-78fc-11ea-90b8-9fb510aa4469.png">

Same chrome version.

**Comment by RealDyllon** [comment]
I also have this issue on Firefox 74.0.1
I'm running Windows 10 v1909

**Comment by uni-zheng** [comment]
See attached gif captured on Chrome 80.0.3987.149（正式版本） （64 位）

![demo](https://user-images.githubusercontent.com/9986421/78739274-7f819a00-7986-11ea-9f9e-f8e5e53581f1.gif)

Also has same issue on Safari.

But there is no problem that in Antd 4.x I tested.

**Comment by uni-zheng** [comment]
@afc163 Is there has any progress?

**Comment by afc163** [comment]
@uni-zheng I can't reproduce in my machine, could you help to dig in?

**Comment by uni-zheng** [comment]
@afc163 I can reproduce this that use rc-tooltip@3.7.3.

Maybe you should test it use rc-tooltip@3.7.3 directly

**Comment by mjfwebb** [comment]
I can reproduce the issue as the described in my browser: Version 1.5.123 Chromium: 80.0.3987.163 (Official Build) (64-bit).

**Comment by uni-zheng** [comment]
@afc163 I couldn't test rc-trigger@2.6.2 or rc-trigger@2.2.2. There throw error when I run `npm install`. Some dependence maybe too old to use.

**Comment by uni-zheng** [comment]
reopen

**Comment by uni-zheng** [comment]
@afc163 please reopen this issue thx.

**Comment by asimkt** [comment]
@afc163 this is reproducible in the codepen provided in _Google Chrome Version 83.0.4103.61 (Official Build) (64-bit)_

Please re-open
