### ISSUE TITLE
文档里没写明远程加载部分和普通加载全部的区别

### ISSUE THREAD

**Issue by vipcxj** [ant-design/ant-design#22989]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/table-cn/#components-table-demo-ajax](https://3x.ant.design/components/table-cn/#components-table-demo-ajax)

### Steps to reproduce
直接看官网文档中远程加载的例子

### What is expected?
说清远程加载部分，和直接传整个数据参数的区别

### What is actually happening?
貌似对于Table本身来说没任何区别

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8.3 |
| System | all |
| Browser | all |

---
其实Table我已经用了很久了。不过过去服务器加载的我都是一律分页，并且每次只取那一页所需要的数据。也就是说dataSource属性最终传入的只有一页数据，其他数据在本地都是不存在的。并且用起来也没有任何毛病。但最近希望服务端不分页，直接传回所有数据，在客户端进行筛选过滤后，在传给Table，这是我就意识到一个问题，Table组件是如何区分传入的dataSource数据是完整的还是分页后的？因为根据官方的例子，对于Table来说根本分不清dataSource属于哪一种情形啊。既然如此，我只传入一页数据，Table是如何正确显示页码的呢？因为我可控地设置了current？那是不是意味着我dataSource传入完整数据，就不能再控制当前页了？

**Comment by zombieJ** [comment]
`dataSource` 长度小于 `pagination` 的 `total` 即为异步数据。

**Comment by vipcxj** [comment]
> `dataSource` 长度小于 `pagination` 的 `total` 即为异步数据。

那`pagination`的`total`没指定的情况呢？文档中大多数例子不要说`total`，`pagination`本身就没指定

**Comment by zombieJ** [comment]
没有写 `total` 时总是同步的。
