### ISSUE TITLE
select key值重复时，filterOption触发列表选项叠加

### ISSUE THREAD

**Issue by sanityou** [ant-design/ant-design#22986]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daisousuokuang-ant-design-demo-96dsd)

### Steps to reproduce
输入框搜索s，删除再搜索s，可以看到sam选项不断增加

### What is expected?
搜索不会导致选项变化

### What is actually happening?
选项叠加重复

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | react |
| System | macOS Catalina |
| Browser | Chrome 80.0.3987.149 |

**Comment by zombieJ** [comment]
`key` 需要唯一，这是 React 的规范：https://reactjs.org/docs/lists-and-keys.html#keys
