### ISSUE TITLE
Display DatePicker inline

### ISSUE THREAD

**Issue by philcon93** [ant-design/ant-design#22987]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We display the RangePicker in a modal, and because the calendar section is `position: absolute`, it displays incorrectly.

We would like to display the calendar section `position: relative` so that it fills out the body of the modal.

A clear example of how this currently function can be seen here:

- https://codesandbox.io/s/range-picker-ant-design-demo-n6boe?file=/index.js

There is a wrapper div around the calendar which adds `{ position: absolute;top: 0px;left: 0px;width: 100%; }`. We would just like to adjust these styles please. Adding a style `position: relative;` here, plus ensuring prop `popupStyle` has a style `position: relative;` would achieve this inline DatePicker.

### What does the proposed API look like?
Like how there is a prop `popupStyle`, it could also have a prop `wrapperStyle` (PropType.object) which adds to this wrapper.

This would make it the responsibility of the developer to ensure their new styles work correctly, and wouldn't affect the component in its default state.

Would love to know your thoughts on this, or even if it's actually possible already with the current API :)

**Comment by zombieJ** [comment]
> We display the RangePicker in a modal, and because the calendar section is position: absolute, it displays incorrectly.

Could you provide a reproduce about this? What's the `incorrectly` look like?

**Comment by philcon93** [comment]
I have updated that example above to be in a modal now so it's easier for you to see the situation:

- https://codesandbox.io/s/range-picker-ant-design-demo-n6boe?file=/index.js

To outline the problem, the calendar has an absolute position which makes its parent element not have a correct relative height. This is an issue because the calendar will display outside the modal, making the close button unreachable.

![Screen Shot 2020-04-08 at 9 15 08 am](https://user-images.githubusercontent.com/13529653/78727972-776f2d80-7979-11ea-9eb9-56c03c7519ff.png)

We would like to display the calendar relative to its parent element, so the modal will have a correct height.

**Comment by zombieJ** [comment]
Why keep `open` on DatePicker? What's the background to force render of it?

**Comment by philcon93** [comment]
It's okay mate don't worry, we will work around it. Thank you for replying :)

**Comment by AgoloFatmaAkram** [comment]
Any ideas on how to get rid of the parent wrapper or override these values?
`{ position: absolute; top: 0px; left: 0px; width: 100%; }`

**Comment by kamranblueeast** [comment]
HI @philcon93, did this work for you?

**Comment by IonelLupu** [comment]
@kamranblueeast I think he is referring to this inline mode, which is implemented already in NgZorro: https://ng.ant.design/components/date-picker/en#components-date-picker-demo-inline 
![image](https://user-images.githubusercontent.com/4083652/210844027-a0ee0d95-22fe-4bc6-b252-99783e9c485d.png)
