### ISSUE TITLE
自定义样式没有生效

### ISSUE THREAD

**Issue by grayShi** [ant-design/ant-design#22994]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
v4.1.4，自定义设置tabs行高无效，默认40px也没有生效

### What is expected?
@tabs-card-height: 40px;  从4.0.2升级到4.1.4，自定义设置tabs行高无效，默认40px也没有生效

### What is actually happening?
@tabs-card-height: 40px;  从4.0.2升级到4.1.4，自定义设置tabs行高无效，默认40px也没有生效

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | react |
| System | windows，mac |
| Browser | chrome,ie |

**Comment by afc163** [comment]
@MrHeer 

https://github.com/ant-design/ant-design/pull/22666

**Comment by yoyo837** [comment]
Why close this?

**Comment by grayShi** [comment]
> Why close this?

1. “默认40px没有生效“，应该是我搞错了。
2. @tabs-card-height样式在v4.0.2上是生效的，但是从v.4.0.2升到v4.1.1，就不起作用了。然后刚才我回到v4.0.2也没有生效，所以我准备再看一看。
