### ISSUE TITLE
The Browser blocked when input chinese in Safari.

### ISSUE THREAD

**Issue by gb-6k-house** [ant-design/ant-design#22997]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://preview.pro.ant.design/user/login?redirect=https%3A%2F%2Fpreview.pro.ant.design%2Fdashboard%2Fanalysis](https://preview.pro.ant.design/user/login?redirect=https%3A%2F%2Fpreview.pro.ant.design%2Fdashboard%2Fanalysis)

### Steps to reproduce
enter chinese (  用户名输入框，直接输入中文)

### What is expected?
Can input chinese

### What is actually happening?
cannot input chinese

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.12.0  |
| System | Mac |
| Browser | Safari |

**Comment by afc163** [comment]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/78678763-fa619b00-791b-11ea-8a31-6d5b8d4a701b.png">

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/507615/78678813-09e0e400-791c-11ea-9901-bdcefccd29c6.png">

可以输入。
