### ISSUE TITLE
InputNumber:The onchange event only provides a value. When the component value is under control, 0.0 and 0 cannot be distinguished——InputNumber：onChange事件只提供了值，在组件值受控时无法区分0.0和0的情况

### ISSUE THREAD

**Issue by thding** [ant-design/ant-design#22990]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I use the inputnumber component, I need to control the user's input, such as calculation. However, when the user enters 0.0, the value returned from the component is 0 of the numerical type, which cannot be distinguished for processing. I hope to provide a second string parameter or tell me how to solve this situation. Thanks——当我使用InputNumber组件时我需要对用户的输入做一些控制比如计算操作，但是当用户输入0.0时从组件返回的值还是数值类型的0，无法区分进行处理，希望可以提供第二个字符串参数或者告知我如何解决这种情况，谢谢

### What does the proposed API look like?
I want to add a second string parameter such as' strValue 'to the onchange event so that I can receive' 0.0 'instead of 0 (numeric type) when the user enters 0.0——我希望在onChange事件中增加第二个字符串参数如'strValue',这样在用户输入0.0时我可以接收到'0.0'而不是0（数值类型）

**Comment by vipcxj** [comment]
改用Input？既然是InputNumber，内部肯定把值当数值处理，0和0.0肯定是同一个东西~

**Comment by thding** [comment]
> 改用Input？既然是InputNumber，内部肯定把值当数值处理，0和0.0肯定是同一个东西~

改用input涉及面太广，做了二次封装，很多地方大量使用，组件的变更怕带来一些不可预支的不符合预期的表现所以问问有没有好的解决方式。

**Comment by vipcxj** [comment]
> > 改用Input？既然是InputNumber，内部肯定把值当数值处理，0和0.0肯定是同一个东西~
> 
> 改用input涉及面太广，做了二次封装，很多地方大量使用，组件的变更怕带来一些不可预支的不符合预期的表现所以问问有没有好的解决方式。

这个问题不大，你外面在套一层，做下输入的检查，其他逻辑交给原来的组件就行了~

**Comment by zombieJ** [comment]
满足数字格式的时候 `onChange` 返回的一定是 number 类型，这个是组件的特性决定的。我也是倾向于这个需求基于 Input 封装。
