### ISSUE TITLE
使用Form.create(options)，设置validateMessages出错

### ISSUE THREAD

**Issue by huanhuan129129** [ant-design/ant-design#2299]
### 本地环境

- antd 版本: 1.1.0
- 操作系统及其版本：os x
- 浏览器及其版本: chrome 51

### 你做了什么？
使用
```jsx
Form.create({
  validateMessages: {
    required() {
      return '此处必填';
    },
  },
})
```
在输入框未填写时，提交表单，页面提示了组件默认的错误提示 ‘showStoreNum is not a number’

### 你期待的结果是：
在输入框未填写时，提交表单，页面提示‘此处必填’

## 实际上的结果：
在输入框未填写时，提交表单，页面提示了组件默认的错误提示 ‘showStoreNum is not a number’

### 可重现的在线演示

http://codepen.io/anon/pen/zBdEpN?editors=001#anon-login

**Comment by benjycui** [comment]
```jsx
const NewForm = Form.create({
  validateMessages: {
    types: { number: '%s Hello' }
  },
})(App);
```

`validateMessages` 的配置方式见 https://github.com/yiminghe/async-validator/blob/master/src/messages.js

**Comment by kasinooya** [comment]
我们的问题不光是校验type类型的默认报错文案修改。

InputNumber组件存在不合适，如果空内容，则typeof value === 'string‘，而当有内容的时候，typeof value === 'number'，这让我们在写rule时候很难处理rule的tpye，因为存在两种可能的类型。

例子详见：http://codepen.io/kasinooya/pen/YWxBQZ?editors=001#anon-login

p.s. 之前没有出问题的原因我怀疑是 validator 的校验逻辑没有 && ，required 和 type 并存就校验了 required。在开发理解上，如原issue的例子，报错文案应该命中required的默认报错'此处必填'，而不是命中 type != number的文案

**Comment by benjycui** [comment]
那么这个就要改 `InputNumber` 了 @afc163 

现在先给 `InputNumber` 设置 `initialValue` 绕过去。

**Comment by kasinooya** [comment]
表单选填项不适合设置 `initialValue` ，会把错误值带给后端

目前只能手动写rule了，期望后期尽快修复！

**Comment by benjycui** [comment]
https://github.com/react-component/input-number/blob/master/src/InputNumber.js#L137

或者可以改为：

```js
isNaN(v) || v === '' ? undefined : v
```

这样 POST 到服务器时是不会有这个字段的：

```js
JSON.stringify({ value: undefined }) => "{}"
```

@afc163

**Comment by afc163** [comment]
呃，https://github.com/react-component/input-number/commit/fefd900d5e1742af5476de5fd04a73f55d265b8a
