### ISSUE TITLE
建议Table添加align属性

### ISSUE THREAD

**Issue by WanAn0902** [ant-design/ant-design#22995]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前要统一设置表格列的对齐方式只能在每一个Column上设置align，建议可以在Table上添加一个align属性用于统一设置表格所有列的对齐方式

### What does the proposed API look like?
align = "left" | "right" | "center"，可以默认"left"或者"center"

**Comment by zombieJ** [comment]
直接用 css 设置一下：https://codesandbox.io/s/jibenyongfa-ant-design-demo-yxkpz?file=/index.css
