### ISSUE TITLE
Tooltip overlayStyle color options not working

### ISSUE THREAD

**Issue by JESii** [ant-design/ant-design#23002]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/jesii/pen/ExjqOrb?editable=true&editors=001](https://codepen.io/jesii/pen/ExjqOrb?editable=true&editors=001)

### Steps to reproduce
1) Create Tooltip
2) Add overlayStyle with color settings

### What is expected?
Color settings should be added to the tooltip

### What is actually happening?
No color settings are seen -- only the default

| Environment | Info |
|---|---|
| antd | 3.20.3 |
| React | 16.12.0 |
| System | 10.15.3 (19D76) |
| Browser | Version 80.0.3987.149 (Official Build) (64-bit) |

**Comment by afc163** [comment]
https://codepen.io/afc163-1472555193/pen/ExjqJYQ?editors=0010

**Comment by JESii** [comment]
Nice to have that workaround, but why doesn't `overlayStyle` function as documented?

**Comment by punit-naik** [comment]
@afc163 Why was this closed?

**Comment by yoyo837** [comment]
feel free to open a new issue for any problems.

**Comment by manikandanraji** [comment]
I am still facing the issue. overlayStyle object styles are not applying.

**Comment by sklinov** [comment]
@afc163 That workaround doesn't solve the problem that the background color of the tooltip is not changing.
