### ISSUE TITLE
Cannot test Select with react testing library after upgrading to v4

### ISSUE THREAD

**Issue by klugjo** [ant-design/ant-design#23009]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-qoi8e)

### Steps to reproduce
Given the following component

```
<Select
  defaultValue="Value 1"
  onChange={handleChange}
>
  <Option value="jack">Value 1</Option>
  <Option value="jack">Value 2</Option>
  <Option value="jack">Value 3</Option>
</Select>
```

In v3 is it possible to test a Select component like this:
```
// Opens the Drop down
fireEvent.click(getByText("Value 1"));
// Select a value from the dropdown <- THIS FAILS in v4 but work in v3
fireEvent.click(getByText("Value 2"));
```

When printing out the full DOM, the dropdown content is not present in the DOM. This means I can't select an option.

This is a blocker to migrate my app to v4

### What is expected?
I would expect the dropdown content to be inside the DOM at the bottom of the body.

### What is actually happening?
The content of the dropdown is not appearing anywhere

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12.0 |
| System | All |
| Browser | Chrome |

**Comment by afc163** [comment]
Try `<Select virtual={false} />`

**Comment by klugjo** [comment]
This is not working.

I gave an example with Select, but AutoComplete, DatePicker and a lot of other components have the same issue

**Comment by afc163** [comment]
@klugjo Could you share a minimal reproduce repo?

**Comment by klugjo** [comment]
https://github.com/ant-design/ant-design/issues/22074#issuecomment-597061052

This fixed it.

Basically `.click()` does not work anymore. `mouseDown()` needs to be used instead

Thanks !

**Comment by afc163** [comment]
Don't depend on dom manipulation to control component, it is not reliable.

**Comment by klugjo** [comment]
I am only using this for UI testing, not in my app

**Comment by rucah** [comment]
I had a very similar problem testing a component with a antd Select wrapped in. I found my solution in this post https://stackoverflow.com/questions/61080116/ant-design-v4-breaks-react-testing-library-tests-for-select-and-autocomplete by using the `mouseDown` event and an expectation inside a `waitFor`

**Comment by rcbevans** [comment]
@rucah That suggestion works for showing the options dropdown, do you happen to know how to hide it again?

I have behavior I'm trying to test which is invoked by `onBlur`, but I can't figure out how to get the Select component to invoke it.

I have tried
```ts
      fireEvent.mouseUp(screen.getByText('select text'));
      fireEvent.mouseOut(screen.getByText('select text');
      fireEvent.mouseLeave(screen.getByText('select text'));
      fireEvent.click(screen.getByTestId('outer-container'));
      fireEvent.click(document);
      fireEvent.click(container);
```
None of which are coaxing the onBlur into running

**Comment by rcbevans** [comment]
For anyone who finds this, the following is working for me

```ts
// Show the dropdown
userEvent.click(screen.getByText('select text'));

// Hide the dropdown
userEvent.click(container);
```

**Comment by th3n3rd** [comment]
@rcbevans could you elaborate on what do you refer as `container`? Could you share a working example?

**Comment by rcbevans** [comment]
> @rcbevans could you elaborate on what do you refer as `container`? Could you share a working example?

Sure.  Container is a property on the object returned by the RTL `render` function.

```
import { render } from '@testing-library/react';

const renderOptions = {...}

const { container } = render(<Component />, renderOptions);

// Will cause the dropdown to show
userEvent.click(screen.getByText('my select text placeholder'));

...

// Will hide the dropdown
userEvent.click(container);
```

**Comment by th3n3rd** [comment]
Thanks for the clarification, I thought you meant something else. That being your solution only works if the "placeholder" you have is unique, if you have multiple dropdown with the same placeholder than unfortunately it doesn't work as expected.

**Comment by xyy94813** [comment]
```js
test('Tree select', async () => {
  // open dropdown of tree select
  await act(async () => {
      fireEvent.mouseDown(
        container.querySelector('.ant-select-selection-search-input'),
      );
      jest.runAllTimers();
  });
})
```

**Comment by donysukardi** [comment]
@xyy94813 does your dropdown look like this? I'm unable to use `@testing-library/user-event` to simulate click when there's `pointer-events: none`. it seems like the animation hasn't been performed yet, even with `jest.runAllTimers()`

```
<div
  class="ant-select-dropdown"
  style="opacity: 0; pointer-events: none; min-width: 0; width: 0px;"
> 
```

**Comment by ekeijl** [comment]
I did not succeed selecting a value using Cypress either using `click()` or `trigger('mouseDown')`.

If you use `<Select showSearch={true}>` you may be able to type a value in the search box. In case of Cypress + Testing Library:
```
cy.findByRole('combobox', { name: /your label here/i}).type("some value{enter}");
```
