### ISSUE TITLE
Cascader

### ISSUE THREAD

**Issue by nodeman777** [ant-design/ant-design#2300]
### 本地环境

- antd 版本:1.1.0
- 操作系统及其版本：ubuntu 16.4
- 浏览器及其版本:chrome 51.0.2704.106

### 可重现的在线演示
https://codepen.io/ea7son/pen/dXzdYz

**Comment by afc163** [comment]
404

**Comment by nodeman777** [comment]
@afc163 再试下？刚引用有问题在修改

**Comment by afc163** [comment]
有了。

**Comment by afc163** [comment]
是这个改动影响了，我明天再看看：https://github.com/react-component/cascader/commit/026e03be8a563d3066e9b41a9532bae0ded7eeee

**Comment by niss2000** [comment]
楼主，你注册了codepen么？为啥我注册的时候不显示验证码框？没法注册啊

**Comment by nodeman777** [comment]
@niss2000 估计是google的验证码吧，得翻墙，我之前注册的帐号。

**Comment by afc163** [comment]
reinstall

**Comment by nodeman777** [comment]
@afc163 好像还是得双击才刷新（codepen的代码按照官网更新了），还有例子里的this.setState({options:[...this.state.options]}) 有必要么？

**Comment by afc163** [comment]
codepen 里的 antd.js 没更新的，你的本地项目里可以这么用。
