### ISSUE TITLE
Menu使用inline mode，dark theme在inlineCollapsed时，子菜单弹层背景色为白色

### ISSUE THREAD

**Issue by CoffeeWorm** [ant-design/ant-design#23003]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suoqineiqiancaidan-ant-design-demo-nq101)

### Steps to reproduce
安装4.1.1版本antd，使用Menu组件，设置mode="inline" theme="dark" inlineCollapsed={true}。

### What is expected?
子菜单弹层背景色与一级菜单颜色一致，且为深色

### What is actually happening?
子菜单弹层背景色为白色，文字为白色

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | MacOS、Windows10 |
| Browser | Chrome 80.0.3987.106 |

---
https://codesandbox.io/s/7zw4g  官网demo也是如此

**Comment by afc163** [comment]
Should be fixed in #22981
