### ISSUE TITLE
SubMenu dark theme

### ISSUE THREAD

**Issue by Dricc** [ant-design/ant-design#23008]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sider-ant-design-demo-652fj)

### Steps to reproduce
Add Menu with subMenu and set theme to dark

### What is expected?
Submenu background is same as menu

### What is actually happening?
Submenu background is white

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12.0 |
| System | macOs Catalina 10.15.4 |
| Browser | Firefox 74 |

**Comment by afc163** [comment]
Fixed in #22981
