### ISSUE TITLE
用了ConfigProvider locale={zhCN}之后 datePicker 仍然显示英文

### ISSUE THREAD

**Issue by shen1986** [ant-design/ant-design#23001]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/shen1986/antdDatePickerTest](https://github.com/shen1986/antdDatePickerTest)

### Steps to reproduce
      <DatePicker
          picker="month"
      />

### What is expected?
显示中文的1月，2月等

### What is actually happening?
都是英文

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | react  16.13.1 |
| System | Mac |
| Browser | chrome 80.0.3987.149 |

**Comment by afc163** [comment]
https://ant.design/components/config-provider-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86-ConfigProvider-locale%EF%BC%8C%E6%97%B6%E9%97%B4%E7%B1%BB%E7%BB%84%E4%BB%B6%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%9F
