### ISSUE TITLE
Form.Item中的DatePicker获取到的是moment对象,能否给个格式化的props自动将moment转换成string

### ISSUE THREAD

**Issue by MingRock** [ant-design/ant-design#23007]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在大型表单中提交时,需要每个进行moment.format().toString转换,有点繁琐

### What does the proposed API look like?
在Form.Item或DatePicker中增加个valueFormat的props

**Comment by zombieJ** [comment]
`4.2.0` 会加 `getValueProps`: https://github.com/ant-design/ant-design/issues/19727#issuecomment-610203180
