### ISSUE TITLE
Drop Down for Changing Page Size on Paginated Table Cuts off Numbers in IE 11

### ISSUE THREAD

**Issue by martymcfly1985** [ant-design/ant-design#23010]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/pagination/](https://ant.design/components/pagination/)

### Steps to reproduce
Open the above link to your web page on pagination in IE 11 and look at one of the examples where you can choose the page size.

### What is expected?
The drop down will show the number without cutting it off.

### What is actually happening?
The box is too small and it cutting off the number within the drop down.

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | 16.13.0 |
| System | 10.0.17763 |
| Browser | 11.1098.17763.0 |

---
This was working in previous 3.0 versions. I switched your site back to 3.26.14 and it worked as expected.

![image](https://user-images.githubusercontent.com/48028793/78720258-59f78080-78f3-11ea-8d31-5ef14ce130db.png)

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/pull/22033
