### ISSUE TITLE
Enhancement of compact theme

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#23015]
ref: https://www.yuque.com/docs/share/1f9849ba-f80a-4a9a-a960-ba48a6d4027d

Should update in `feature` branch at `4.2.0`.

- [ ] Font size
- [ ] Component padding
- [ ] Button
- [ ] Breadcrumb
- [ ] Dropdown
- [ ] Layout
- [ ] Pagination
- [ ] PageHeader
- [ ] Steps
- [ ] AutoComplete
- [ ] Checkbox
- [ ] Cascadar
- [ ] DatePicker
- [ ] Form
- [ ] InputNumber
- [ ] Input
- [ ] Mentions
- [ ] Rate
- [ ] Radio
- [ ] Switch
- [ ] Slider
- [ ] Select
- [ ] TreeSelect
- [ ] Transfer
- [ ] TimePicker
- [ ] Upload
- [ ] Avatar
- [ ] Badge
- [ ] Comment
- [ ] Collapse
- [ ] Card
- [ ] Calendar
- [ ] Descriptions
- [ ] Empty
- [ ] List
- [ ] Popover
- [ ] Statistic
- [ ] Tree
- [ ] Tooltip
- [ ] Timeline
- [ ] Tag
- [ ] Tabs
- [ ] Table
- [ ] Alert
- [ ] Drawer
- [ ] Modal
- [ ] Message
- [ ] Notification
- [ ] Progress
- [ ] Popconfirm
- [ ] Result
- [ ] Spin
- [ ] Skeleton
- [ ] Anchor

**Comment by AshoneA** [comment]
Closes: #23135
