### ISSUE TITLE
Upload component list size

### ISSUE THREAD

**Issue by thomaslc66** [ant-design/ant-design#23012]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gary-shen.github.io/ant-design/components/upload/](https://gary-shen.github.io/ant-design/components/upload/)

### Steps to reproduce
Take an upload component that accept multiple or single file and upload 50 files at once.

### What is expected?
It should be possible to limit the size of the list that is displayed at the bottom, because if I upload 50   files then all my UI is messed up. It should be possible to display only the last 5-10 upload or at least have a method to delete programmatically this list.

### What is actually happening?
The list goes bigger and bigger extending and messing with the UI of the app. Then the user needs to refresh or delete the files one by one

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 0.60 |
| System | Windows |
| Browser | Firefox, Chome, Opera, Safari |

**Comment by thomaslc66** [comment]
Find my answer

**Comment by jaddoescad** [comment]
Hi, How can You limit upload to a single file?
