### ISSUE TITLE
表格总结栏竖直方向跟随滚动，且当表格设置列固定后，总结栏对应的列没有固定

### ISSUE THREAD

**Issue by PeiTianHuang** [ant-design/ant-design#23017]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zongjielan-ant-design-demo-2twdp?file=/index.js)

### Steps to reproduce
官方示例中设置scroll和列固定后即可重现。

### What is expected?
1、当表格的第一列是fixed时，总结栏的第一列也应是fixed；
2、总结栏在竖直方向应该不参与滚动（类似footer，因为需要参与滚动的话直接加多一行数据即可）

### What is actually happening?
1、表格水平滚动时由于总结栏的固定列发生了滚动，导致跟上方内容错位；
2、竖直方向需滚动后才能看到总结栏，使得它更接近一行普通的数据

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome69 |

**Comment by PeiTianHuang** [comment]
第一点的表现类似酱紫
![image](https://user-images.githubusercontent.com/17986764/78741139-2ec07000-798b-11ea-98bb-418e8d3d11ce.png)
![image](https://user-images.githubusercontent.com/17986764/78741181-44ce3080-798b-11ea-9336-a7e59c7a9237.png)

**Comment by PeiTianHuang** [comment]
第二点的期望类型酱紫
![image](https://user-images.githubusercontent.com/17986764/78741305-91b20700-798b-11ea-8e35-3924cf0fc4b2.png)

**Comment by zombieJ** [comment]
merge into #19769
