### ISSUE TITLE
Table header disappear in production!

### ISSUE THREAD

**Issue by luanphungba** [ant-design/ant-design#23021]
hi everyone, i have some problems when using ant table. I render 300 rows, choose fixed header, when i build my app, the header disappears. Can anyone help me?
![image](https://user-images.githubusercontent.com/43276516/78743577-341cbb00-7989-11ea-8fd7-54a83a6caccf.png)

**Comment by dohoangtung** [comment]
. This is really an issue! I've faced the problem too. @luanphungba , do you have solution for this?
