### ISSUE TITLE
建议Cascader级联选择组件默认值不在option里存在时可以显示默认值【请看清楚内容，不是问如何使用，是需求】

### ISSUE THREAD

**Issue by piscdong** [ant-design/ant-design#23027]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
前面发了一个，被官方不认真审题关了，好吧，我重发一遍，同时 @zombieJ 麻烦看清别人的话好吧

我的意思就是默认值不在option里存在的情况下时候能和Select一样直接显示，而不是显示个空白

说一个实际的应用场景：一个项目有网页端管理后台和小程序，网页端用Cascader做省市区级联选择，小程序有原生的省市区选择，但是如果两边数据源不一样的情况下，导致Cascader的默认值不在option里存在的情况下，为了更好的用户体验，可以直接显示默认值，而不是显示空白。
Select就是这么处理的，我建议Cascader也能同样处理

这不是代码wo不work的问题

### What does the proposed API look like?
建议Cascader级联选择组件默认值不在option里存在时可以显示默认值

**Comment by zombieJ** [comment]
merge into #23019
