### ISSUE TITLE
希望createFromIconfontCN支持同时引入多个scriptUrl

### ISSUE THREAD

**Issue by 303394539** [ant-design/ant-design#23022]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1、当出现多个项目产生了多组iconfont资源，并且新的项目需要同时使用这些资源的时候。
2、按道理，一个项目里面创建多个createFromIconfontCN可以解决这个需求问题，但是这对于项目的统一化开发体验不友好，多个开发者需要同时知道哪个type属于哪一个Icon实例，也可能会出现为了解决问题，相同资源多次创建的情况，影响设计资源规划体验和开发体验。

### What does the proposed API look like?
const MyIcon = createFromIconfontCN({
  scriptUrls: ['//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js','//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js'], //多个资源合并到同一个Icon实例中
});

**Comment by fjc0k** [comment]
使用 iconfont.cn + React 推荐使用这个浏览器插件，根据项目生成 React SVG 图标组件，与 Ant Design Icons 类似：

https://github.com/fjc0k/Iconfonter

![image](https://user-images.githubusercontent.com/13151189/78750974-e82b3f80-79a3-11ea-85fd-07e0f20316a5.png)

生成的组件代码是这样的：

```ts
import React from 'react'

interface IconWrapperComponentProps extends React.ComponentProps<'span'> {
  iconName: string
  svgViewBox: string
  svgPaths: React.ReactNode
}

const IconWrapperComponent = React.forwardRef<
  HTMLSpanElement,
  IconWrapperComponentProps
>((props, ref) => {
  const { iconName, svgViewBox, svgPaths, className, ...restProps } = props
  return (
    <span
      role='img'
      aria-label={iconName}
      {...restProps}
      ref={ref}
      className={`anticon${className ? ` ${className}` : ''}`}>
      <svg
        viewBox={svgViewBox}
        width='1em'
        height='1em'
        fill='currentColor'
        data-icon={iconName}
        aria-hidden='true'>
        {svgPaths}
      </svg>
    </span>
  )
})
IconWrapperComponent.displayName = 'IconWrapperComponent'

export interface IconProps extends React.ComponentProps<'span'> {}

// pause
export const IconPause = React.forwardRef<HTMLSpanElement, IconProps>(
  (props, ref) => {
    return (
      <IconWrapperComponent
        {...props}
        ref={ref}
        iconName={`pause`}
        svgViewBox={`0 0 1024 1024`}
        svgPaths={
          <React.Fragment>
            <path d='M750.82666667 35.09333333c-54.61333333 0-102.4 47.68-102.4 102.18666667v749.44c0 54.50666667 47.78666667 102.18666667 102.4 102.18666667s102.4-47.68 102.4-102.18666667V137.28c0-54.50666667-47.78666667-102.18666667-102.4-102.18666667z m-477.65333334 0c-54.61333333 0-102.4 47.68-102.4 102.18666667v749.44c0 54.50666667 47.78666667 102.18666667 102.4 102.18666667s102.4-47.68 102.4-102.18666667V137.28c-0.10666667-54.50666667-47.89333333-102.18666667-102.4-102.18666667z' />
          </React.Fragment>
        }
      />
    )
  }
)
IconPause.displayName = 'IconPause'

// play
export const IconPlay = React.forwardRef<HTMLSpanElement, IconProps>(
  (props, ref) => {
    return (
      <IconWrapperComponent
        {...props}
        ref={ref}
        iconName={`play`}
        svgViewBox={`0 0 1024 1024`}
        svgPaths={
          <React.Fragment>
            <path d='M286.24658623 957.35303049C211.40076538 1004.00420652 112.43908945 952.50946636 112.43908945 866.85484771V155.10575611c0-85.60363326 98.96167463-137.14935878 173.80749678-90.44719738l595.91141735 356.89424259a105.5387265 105.5387265 0 0 1 0 180.89439736l-595.91141735 354.85484771z' />
          </React.Fragment>
        }
      />
    )
  }
)
IconPlay.displayName = 'IconPlay'
```

**Comment by 303394539** [comment]
> 使用 iconfont.cn + React 推荐使用这个浏览器插件，根据项目生成 React SVG 图标组件，与 Ant Design Icons 类似：
> 
> https://github.com/fjc0k/Iconfonter
> 
> ![image](https://user-images.githubusercontent.com/13151189/78750974-e82b3f80-79a3-11ea-85fd-07e0f20316a5.png)
> 
> 生成的组件代码是这样的：
> 
> ```ts
> import React from 'react'
> 
> interface IconWrapperComponentProps extends React.ComponentProps<'span'> {
>   iconName: string
>   svgViewBox: string
>   svgPaths: React.ReactNode
> }
> 
> const IconWrapperComponent = React.forwardRef<
>   HTMLSpanElement,
>   IconWrapperComponentProps
> >((props, ref) => {
>   const { iconName, svgViewBox, svgPaths, className, ...restProps } = props
>   return (
>     <span
>       role='img'
>       aria-label={iconName}
>       {...restProps}
>       ref={ref}
>       className={`anticon${className ? ` ${className}` : ''}`}>
>       <svg
>         viewBox={svgViewBox}
>         width='1em'
>         height='1em'
>         fill='currentColor'
>         data-icon={iconName}
>         aria-hidden='true'>
>         {svgPaths}
>       </svg>
>     </span>
>   )
> })
> IconWrapperComponent.displayName = 'IconWrapperComponent'
> 
> export interface IconProps extends React.ComponentProps<'span'> {}
> 
> // pause
> export const IconPause = React.forwardRef<HTMLSpanElement, IconProps>(
>   (props, ref) => {
>     return (
>       <IconWrapperComponent
>         {...props}
>         ref={ref}
>         iconName={`pause`}
>         svgViewBox={`0 0 1024 1024`}
>         svgPaths={
>           <React.Fragment>
>             <path d='M750.82666667 35.09333333c-54.61333333 0-102.4 47.68-102.4 102.18666667v749.44c0 54.50666667 47.78666667 102.18666667 102.4 102.18666667s102.4-47.68 102.4-102.18666667V137.28c0-54.50666667-47.78666667-102.18666667-102.4-102.18666667z m-477.65333334 0c-54.61333333 0-102.4 47.68-102.4 102.18666667v749.44c0 54.50666667 47.78666667 102.18666667 102.4 102.18666667s102.4-47.68 102.4-102.18666667V137.28c-0.10666667-54.50666667-47.89333333-102.18666667-102.4-102.18666667z' />
>           </React.Fragment>
>         }
>       />
>     )
>   }
> )
> IconPause.displayName = 'IconPause'
> 
> // play
> export const IconPlay = React.forwardRef<HTMLSpanElement, IconProps>(
>   (props, ref) => {
>     return (
>       <IconWrapperComponent
>         {...props}
>         ref={ref}
>         iconName={`play`}
>         svgViewBox={`0 0 1024 1024`}
>         svgPaths={
>           <React.Fragment>
>             <path d='M286.24658623 957.35303049C211.40076538 1004.00420652 112.43908945 952.50946636 112.43908945 866.85484771V155.10575611c0-85.60363326 98.96167463-137.14935878 173.80749678-90.44719738l595.91141735 356.89424259a105.5387265 105.5387265 0 0 1 0 180.89439736l-595.91141735 354.85484771z' />
>           </React.Fragment>
>         }
>       />
>     )
>   }
> )
> IconPlay.displayName = 'IconPlay'
> ```

现在要解决的场景是项目只定义一个Icon组件，其他开发人员直接使用同一个Icon就可以使用不同资源的type，而不是一个资源建一个Icon，这样的话就可以同一个Icon使用不同资源的type，再加上如果设计需要把其中一个资源的svg跟换到另一个资源中，从AIcon的资源到BIcon的资源，那岂不是要去改业务代码？所以这些插件解决不了项目统一管理资源的需求

**Comment by fjc0k** [comment]
@303394539 个人觉得，对于阿里系外的网站，依靠阿里 cdn 本来就是不太好的方案，谁都不能保证一直可用，最好是本地化，之前本地化很麻烦，所以我搞了这个插件，无论是小程序 css 还是 React 组件，都生成相应的跟阿里 cdn 无关的代码。至于体积，minify + gzip 后，我觉得要不是图标达到一定量级，并不会有特别的影响。

**Comment by 303394539** [comment]
> @303394539 个人觉得，对于阿里系外的网站，依靠阿里 cdn 本来就是不太好的方案，谁都不能保证一直可用，最好是本地化，之前本地化很麻烦，所以我搞了这个插件，无论是小程序 css 还是 React 组件，都生成相应的跟阿里 cdn 无关的代码。至于体积，minify + gzip 后，我觉得要不是图标达到一定量级，并不会有特别的影响。

十分感谢大哥的解答，这个插件使我眼前一亮，对我很有启发，我也很认同大哥对于外部CDN与压缩缓存作用的看法。
从资源上来说iconfont是阿里的一个正式产品，图标资源也相当于托管在上面，所以相对也是可以信任的，应该和BootCDN之类的不一样，当然大哥点醒了我，我后期会考虑这种资源自己管理起来。
如果撇开本地代码流量的考虑外，合并资源为同一个Icon组件来开放到业务开发对于我现在构建的开发模式很有意义。当然，4.0以后其实antd对于Icon是偏向推荐使用按需加载的，只是我这边希望开发模式统一化，模式化。所以更多的是希望使用一致，拿来即用。
生成本地资源固然是有用的，不过这也相当于资源脱离了设计的控制，设计如果修改了资源库，并不是告知一声开发就可以完事的，开发还得去删除不需要的图标本地代码，这也会引起连锁报错，与只需要type区分的轻量级不太一样。

**Comment by 303394539** [comment]
@fjc0k 
十分感谢大哥的解答，这个插件使我眼前一亮，对我很有启发，我也很认同大哥对于外部CDN与压缩缓存作用的看法。
从资源上来说iconfont是阿里的一个正式产品，图标资源也相当于托管在上面，所以相对也是可以信任的，应该和BootCDN之类的不一样，当然大哥点醒了我，我后期会考虑这种资源自己管理起来。
如果撇开本地代码流量的考虑外，合并资源为同一个Icon组件来开放到业务开发对于我现在构建的开发模式很有意义。当然，4.0以后其实antd对于Icon是偏向推荐使用按需加载的，只是我这边希望开发模式统一化，模式化。所以更多的是希望使用一致，拿来即用。
生成本地资源固然是有用的，不过这也相当于资源脱离了设计的控制，设计如果修改了资源库，并不是告知一声开发就可以完事的，开发还得去删除不需要的图标本地代码，这也会引起连锁报错，与只需要type区分的轻量级不太一样。

**Comment by fjc0k** [comment]
@303394539 哈哈，阿里系的东西是要开放点的，发展顺利应该不会砍这些公益项目。

另外这个无论哪种方案 iconfont.cn 上的资源有变动，前端都必须手动更新，不过是更新链接还是更新组件而已，不过你的需求其实用组件也可以实现的，就是多生成一个统一的图标组件，通过图标名称属性决定返回哪个具体的图标组件，就是将入口统一即可，顺便还能做图标不存在时的 fallback，不过这会导致无法 tree shake。

**Comment by 303394539** [comment]
@fjc0k 早期使用antd的时候，主要是从iconfont下载css或者js资源直接引入，如果设计修改了，重新下直接覆盖目录就更新了。算起来iconfont把图标资源项目化管理还是不错的，后期因为支持了createFromIconfontCN这种形式，突然覆盖目录变成修改个url就可以完成了，开发体验直接飙升。总的来说url引入的方式还是很舒服的。毕竟提交git的时候，如果文件改了要看很多位置，url换了看个字符串变化就看出来了，突出了方便，当时增加createFromIconfontCN方式的idea还是很赞的

**Comment by afc163** [comment]
你们俩聊了这么多，这个需求来帮忙搞定如何，多个文件合并成一个 Icon 看上去还是很有用的。

**Comment by 303394539** [comment]
@afc163 好的大哥，正准备周末搞一下，只是麻烦问下，4.*是提交到feature分支，还能一起做在3.*不？是哪个分支？

**Comment by afc163** [comment]
feature 分支吧，3.x 不接受新特性了。

**Comment by 303394539** [comment]
@afc163 4.*是ant-design-icons，没有feature分支，是不是直接提供给master？被合并发布以后再去ant-design提交feature 分支？

**Comment by afc163** [comment]
直接给 ant-design-icons 的 master 提交就好了。

Ant Design 这边也是 master 就好了，本身功能不依赖 `ant-design-icons`。

**Comment by 303394539** [comment]
@afc163 老哥，我在ant-design-icons提交了push requests，我看前后的request都有处理了，我这个只是过了验证还没合并处理，是你们的合并流程还没走到，还是request不得行，我😅住了

**Comment by xiaoYuanDun** [comment]
你好，最近整合代码库有用到这个特性，把多个库的Icon整合在一起，但是每次使用都加载全量的 icon-svg，比如 只用到 Icon-A 里的 type，但是却在头部添加了所有 Icon-A，Icon-B，Icon-C 的 type，打包后体积非常大，我试过分别写两个 createFromIconfontCN，比如：
const IconA = createFromIconfontCN({ scriptUrls: ['//at.alicdn.com/t/font_icon-a'] })
const IconB= createFromIconfontCN({ scriptUrls: ['//at.alicdn.com/t/font_icon-b'] })
然后在整合的 Icon-font 组件库中分别导出他们：
export {
  IconA,
  IconB
} ,
但是这样并没有解决问题，貌似 createFromIconfontCN 返回的是同一个对象，现在的想法是想做成 @ant-design/icons 的按需加载的形式，即每个图标有单独的 SVG 和对应的 JS 文件，但是从 Iconfont 下载下来的图标文件是一个整体，想请问一下有什么工具可以帮助我把整体的下载文件拆分成单独的一个个的 SVG 和 JS 吗？

**Comment by yoyo837** [comment]
createFromIconfontCN 使用iconfont加载的图标不应该是应用里都会用到的吗？是希望单个页面再支持局部引入？

**Comment by xiaoYuanDun** [comment]
如 IconA 包含 dog, cat, cow, duck 这四个图标，IconB 包含 time, clock, desk 这三个图标
我在组件库中默认导出一个 IconFont 是包含了所有整合图标的，如下：
`const IconFont = createFromIconfontCN({ scriptUrls: ['**icon-a**', '**icon-b**'] })`
`const IconApp = createFromIconfontCN({ scriptUrls: ['**icon-b**'] })`
`export default IconFont `
`export { IconApp  }`
本意是需要使用全量图标的时候，直接使用 IconFont，如果只需使用 IconB 就使用 IconApp，从而减少打包大小(因为部分库的图标打包后太大，而项目里并没有用到)
但是我发现，我在其他项目中引用 IconApp 时，icon-a 的 svg 也被加载到 head 中(但是我在创建 IconApp 时，只用了 icon-b)，看了下代码，可能是 createFromIconfontCN 只会通过 ref 返回一个实例的原因，所以这里我就想把每个图标 拆分成各自对应的 SVG 和 JS 文件，从而达到按需加载的效果

**Comment by xiaoYuanDun** [comment]
https://github.com/ant-design/ant-design/issues/23022#issuecomment-699581923
对，这种想法可行吗？

**Comment by xiaoYuanDun** [comment]
> createFromIconfontCN 使用iconfont加载的图标不应该是应用里都会用到的吗？（不需要的iconfont里删除的那种）是希望单个页面再支持局部引入？

对，这种思路可行吗？
