### ISSUE TITLE
table组件在android6.0任意浏览器和webview内不能滑动

### ISSUE THREAD

**Issue by fairplay01** [ant-design/ant-design#23024]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

ref: #22702

### Steps to reproduce
可以用mumu模拟器自带浏览器测试，任意table区域内，不能滑动

### What is expected?
table区域内可以滑动，支持touchmove事件

### What is actually happening?
table区域内不可以滑动

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.7.0 |
| System | android 6.0 |
| Browser | 任意浏览器或webview |

---
着急，希望官方给个回复

**Comment by zombieJ** [comment]
我们不为旧版安卓系统提供支持

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/9c72b346715ef27b96ded59109ef39e25dc110eb/components/table/Table.tsx#L427

这行能去掉么，记得有个老板 iOS 的问题也是这个。

**Comment by zombieJ** [comment]
我看看为啥当时这么写：https://github.com/ant-design/ant-design/commit/9165b5ee7a5c67f7232d8a32a4b332ead99a9f5d

**Comment by fairplay01** [comment]
多谢，android 7.x也不能用，  麻烦zombieJ看下。

**Comment by fairplay01** [comment]
hi,我测试了下https://preview-23036-ant-design.surge.sh/components/table/，是可以滑动了， 但是scroll.x的例子好像有点问题，也或许是我测试的不对？

**Comment by qiutian00** [comment]
> 我们不为旧版安卓系统提供支持

table组件支持安卓版本至少是？ @zombieJ
