### ISSUE TITLE
Layout收起来的状态时，侧边栏Menu有SubMenu时，鼠标移到SubMenu上展示的内容不对

### ISSUE THREAD

**Issue by zhangchao828** [ant-design/ant-design#23029]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6ep5o)

### Steps to reproduce
Layout的Sidebar收缩状态，鼠标移到SubMenu上展示的内容不对

### What is expected?
鼠标移到SubMenu上展示的内容正常

### What is actually happening?
鼠标移到SubMenu上展示的内容不对

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
需要写一个图标收起状态才能正确展示：https://codesandbox.io/s/antd-reproduction-template-6kpq2?file=/index.js

**Comment by zhangchao828** [comment]
@afc163 不对呀，说的是鼠标移到SubMenu，，官网的例子里都是这样展示不对的https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed

**Comment by zhangchao828** [comment]
![微信图片_20200409094310](https://user-images.githubusercontent.com/15683846/78849311-bb7c3400-7a46-11ea-8af3-ff11545d15e4.png)

**Comment by afc163** [comment]
Fixed in #22981 and #23054
