### ISSUE TITLE
组件是否能分包发布?

### ISSUE THREAD

**Issue by mqliutie** [ant-design/ant-design#23038]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决版本升级问题

### What does the proposed API look like?
组件分包发布, 比如`Table`组件
`import Table from 'antd.table';`
对于老系统, 还在使用3.x的版本, 直接升级不现实, 但是可以通过这种方式在新代码中使用4.x的特性
比如现在我的一个工程中, Table的性能很差, 我特别想用4的版本, 但是整个工程升级会带来更大的问题, 我需要改动非常多的点

**Comment by mqliutie** [comment]
分包的发布应该可以用`lerna`管理

**Comment by yoyo837** [comment]
个人认为UI库还是不同于lodash这种util库的，你可以等到合适的机会再升级，毕竟还有多版本global css和函数方法的冲突

**Comment by zombieJ** [comment]
见 @yoyo837  的留言，另外 v4 提供了 codemod 可以将 v3 的项目转 v4。你可以试试。

**Comment by lxsunbin** [comment]
我也遇到了同样的问题，希望能在v3版本中使用v4的Table，请问有什么方案吗？

**Comment by yoyo837** [comment]
添加rc-table引用自行封装一个

**Comment by lxsunbin** [comment]
> 添加rc-table新版本引用自行封装一个

谢谢，我尝试一下

**Comment by zxdvd** [comment]
我们目前使用npm包alias的方式导入新版本的antd，两个版本并存，目前global css确实是一个很大的问题，除此之外都还好。

对于大项目完全的升级成本和风险都比较高，如果各个版本css互不影响就好了。
