### ISSUE TITLE
ant-modal在弹出和关闭时出现卡顿的现象

### ISSUE THREAD

**Issue by dreamcatcher081210** [ant-design/ant-design#2303]
### 本地环境

- antd 版本:1.6.2
- 操作系统及其版本：win7
- 浏览器及其版本:chrome 51.0.2704.84

### 你做了什么？

引入 antd 了 modal 进行打开弹出和取消关闭动作

### 你期待的结果是：

 打开和关闭的流畅度能进一步提高

## 实际上的结果：

卡顿、给人感觉这个modal的动作有些愣头愣脑的

### 可重现的在线演示

 无

**Comment by niss2000** [comment]
这个Modal是通过操作DOM来实现的，每次的弹出和取消都会对DOM进行节点的插入和删除

**Comment by benjycui** [comment]
> 卡顿的现象

是点击按钮后先卡一下再出现 `Modal` 还是说动画卡顿。

**Comment by benjycui** [comment]
> 卡顿、给人感觉这个modal的动作有些愣头愣脑的

`Modal`：你们程序员才愣头愣脑的 😑

**Comment by jljsj33** [comment]
时间过快的原因，，你可以设成0.45,，我自个用前台的motion全是搞成0.45的，，默认的是0.3

**Comment by dreamcatcher081210** [comment]
其实就是在点击弹出时卡顿，然后动画过程中也出现过卡顿。同意楼上的说法，或者是否可以优化下动画逻辑。。。

**Comment by dreamcatcher081210** [comment]
用的多了便会发现，demo永远都是美好的，项目永远都是残酷的。

**Comment by dyf2015** [comment]
屏幕大的时候，更明显。

发自我的 iPhone

在 2016年7月8日，10:45，Benjy Cui <notifications@github.com<mailto:notifications@github.com>> 写道：


卡顿、给人感觉这个modal的动作有些愣头愣脑的

Modal：你们程序员才愣头愣脑的 ??

―

**Comment by benjycui** [comment]
@dyf2015 屏幕大是得有多大。。。24寸表示没感觉。

@jljsj33 所以是建议修改动画时间解决这个问题？

**Comment by afc163** [comment]
动画流程度与机器性能和显卡性能有比较大的关系，和时长关系不大。如有卡顿，可以自行覆盖样式去掉动画。https://github.com/ant-design/ant-design/issues/951

**Comment by afc163** [comment]
> 同时两组动画在同时进行

发现在原生的 input （无 transition 动画）里 blur 也有类似情况，怀疑是 chrome 的 bug。

**Comment by Kaijun** [comment]
@afc163 非常有可能，Safari 和 Firefox 都无法重现

**Comment by stevenluoxiaohua** [comment]
建议参考下arco的modal，很丝滑，就是这个项目现在没维护了
