### ISSUE TITLE
官网-暗黑模式 色卡设置z-index调整

### ISSUE THREAD

**Issue by macc6579** [ant-design/ant-design#23033]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/spec/dark-cn](https://ant.design/docs/spec/dark-cn)

### Steps to reproduce
1.进入官网-设计-全局样式-暗黑模式，下拉至 色板生成工具#
2.尝试设置颜色，点击color-bar，展示色卡选项

### What is expected?
希望色卡选项完整展示

### What is actually happening?
色卡选项被页脚遮盖了一部分

![image](https://user-images.githubusercontent.com/11343720/78761923-d8b4f200-79b5-11ea-940b-15dcfb159b6e.png)

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.10.2 |
| System | macOS Catalina 10.15.2 |
| Browser | Chrome  79.0.3945.88（正式版本） （64 位） |

---

**Comment by yoyo837** [comment]
下面的框框 提交 comment 可以上传或者粘贴文件

**Comment by macc6579** [comment]
> 下面的框框 提交 comment 可以上传或者粘贴文件

好的， 贴了个在线文档的链接，里面放了截图www
【喜欢新版的AntDesign!  ヾ(◍°∇°◍)ﾉﾞ加油鸭！

**Comment by yoyo837** [comment]
重新用这个发一下

![image](https://user-images.githubusercontent.com/6134547/78760322-912d6680-79b3-11ea-845c-1179c528e2e6.png)

不然还得挂梯子

**Comment by macc6579** [comment]
> 重新用这个发一下
> 
> ![image](https://user-images.githubusercontent.com/6134547/78760322-912d6680-79b3-11ea-845c-1179c528e2e6.png)
> 
> 不然还得挂梯子
更新了

**Comment by afc163** [comment]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/507615/78800161-b63ecb00-79ed-11ea-869c-0e9b9da1540c.png">

为啥我这看到是这样的。

**Comment by macc6579** [comment]
> <img alt="image" width="1209" src="https://user-images.githubusercontent.com/507615/78800161-b63ecb00-79ed-11ea-869c-0e9b9da1540c.png">
> 
> 为啥我这看到是这样的。

升级了Chrome版本之后就正常了www~  感谢 Thanks♪(･ω･)ﾉ
