### ISSUE TITLE
通过import { createFromIconfontCN } from '@ant-design/icons';发生错误

### ISSUE THREAD

**Issue by QianDingwei** [ant-design/ant-design#23042]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://qiandingwei.dev.brvdev.huxiang.pro/mailprocess/workspace](http://qiandingwei.dev.brvdev.huxiang.pro/mailprocess/workspace)

### Steps to reproduce
升级出现的问题，不知道怎么重现
报的问题就是：Unhandled Rejection (TypeError): (0 , _icons.createFromIconfontCN) is not a function

### What is expected?
const IconFont = createFromIconfontCN({
    scriptUrl: '//at.alicdn.com/t/font_1393104_dw1yvp6zcgd.js',
});可以通过createFromIconfontCN创建icon的

### What is actually happening?
目前是报错

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13 |
| System | Mac |
| Browser | Chrome |

**Comment by Summer-andy** [comment]
@FrontDream  hello, I also encountered the same problem,  have you solved it now?
