### ISSUE TITLE
Table 表格汇总能不能显示在第一行而不是最后一行

### ISSUE THREAD

**Issue by luffyZh** [ant-design/ant-design#23040]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
很多表格类需求汇总数据显示在第一条要比最后一条更直观

### What does the proposed API look like?
增加个 summaryPlacement 或者 summaryPosition 即可，'top' or 'bottom'

**Comment by zhangchao828** [comment]
可以使用Table的components属性来模拟，参考这个https://codesandbox.io/s/xo4j1qk044
需要判断一下index=0的时候

**Comment by luffyZh** [comment]
好的，感谢
