### ISSUE TITLE
Select cannot be open programmatically with .click()

### ISSUE THREAD

**Issue by klugjo** [ant-design/ant-design#23044]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-kmwvi)

### Steps to reproduce
Given the following component

```
<Select
  defaultValue="Value 1"
  onChange={handleChange}
>
  <Option value="value1">Value 1</Option>
  <Option value="value2">Value 2</Option>
</Select>
```

In v3 is it possible to open the dropdown programmatically by doing

```
document.querySelector(".ant-select").click()
```

In v4 this does not work. This has a lot of implications, most importantly, **I am not able to open the Select Dropdown in JSDOM** which makes it impossible to test components that use a Select.

And all the tests that used to work in v3 are now broken.

I have described the issue with `Select` but it also happens with `AutoComplete` and `DatePicker` for example.

Thanks a lot for your help !

### What is expected?
Here is the exact same code with v3

https://codesandbox.io/s/antd-reproduction-template-7s0jc

Clicking on the button calls `.click()` on the DOM Element for the `Select` and opens the dropdown

### What is actually happening?
I believe something is broken in the way the Select listens to click events but I am not able to pinpoint the exact place in the code

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12.0 |
| System | All |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/22491#issuecomment-602180659
