### ISSUE TITLE
省市区选择控件的格式自定义 

### ISSUE THREAD

**Issue by zjsxfly** [ant-design/ant-design#2304]
现在省市区选择控件不支持选择省后取数据库市数据再显示，请问最佳实践应该如何处理，是否有支持antd省市区选择控件数据格式的前端json数据

**Comment by benjycui** [comment]
用 `changeOnSelect` http://ant.design/components/cascader#components-cascader-demo-change-on-select

实时监听选项变化，把新的数据追加到 `options` 中。
