### ISSUE TITLE
Select does not show text caret when in Collapse with forceRender

### ISSUE THREAD

**Issue by yifengd** [ant-design/ant-design#23059]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vslm5)

### Steps to reproduce
Place select in Collapse.Panel with forceRender on. Click on the select field.

### What is expected?
The text cursor (caret) appears.

### What is actually happening?
There is no text cursor (the width of the select search is set to 0px instead of 3px) until a symbol is entered.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | macOS 10.15 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
multiple Select default do not show the arrow. Use `showArrow` prop to enable it.

**Comment by yifengd** [comment]
I think you misunderstood me. I don't mean the arrow. I mean the text cursor when you type.
<img width="78" alt="Screenshot 2020-04-13 at 22 48 47" src="https://user-images.githubusercontent.com/34337420/79159791-ff6d9100-7dd8-11ea-8055-ee241c858c0a.png">
