### ISSUE TITLE
Expose Option interfaces from rc-select

### ISSUE THREAD

**Issue by MarcServat** [ant-design/ant-design#23056]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-antd-typescript-kn4wi?file=/src/App.tsx)

### Steps to reproduce
1. Export Select component
2. Use onChange callback
3. Check the type of the second parameter

### What is expected?
Interfaces from rc-select are expose to provide type safety.

### What is actually happening?
The interfaces cannot be exported from antd, so typescript compilation will fail.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Firefox 75.0b11 |

**Comment by zombieJ** [comment]
TS support picker type definition:
```tsx
import { SelectProps } from 'antd/lib/select';

type onChange = Required<SelectProps<string>>['onChange'];

// Filled with type definition
const myOnChange: onChange = () => {};

// Get param of function
type optionType = Parameters<onChange>[1];
```

**Comment by afc163** [comment]
Seems `<Select<string> />` not working
