### ISSUE TITLE
Text组件和Dropdown共用时报Maximum call stack size exceeded

### ISSUE THREAD

**Issue by areyouse7en** [ant-design/ant-design#23058]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-leavitt-htwde)

### Steps to reproduce
当Text里ellipsis和copyable同时设置时，会报RangeError: Maximum call stack size exceeded

### What is expected?
不报错

### What is actually happening?
RangeError: Maximum call stack size exceeded
measureText
https://htwde.csb.app/node_modules/antd/lib/typography/util.js:135:23

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.8.6 |
| System | Windows |
| Browser | Chrome 78.0.3904.108 |

**Comment by Go7hic** [comment]
应该是你的版本有问题，  4.0 版本代码改过了 可以升级一下。如果升级影响很麻烦，可以先不用这个组件。复制用的  https://github.com/sudodoki/copy-to-clipboard 这个库

**Comment by areyouse7en** [comment]
好的，谢谢。升级4影响略大，暂不考虑。

**Comment by afc163** [comment]
You need to import css: https://codesandbox.io/s/awesome-wood-rl1ch?file=/src/App.tsx
