### ISSUE TITLE
Tabs - In Safari, the tab content which is not the first disappears

### ISSUE THREAD

**Issue by SevenUMR** [ant-design/ant-design#23050]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/sevenumr/pen/NWGKMwr?editable=true&editors=001](https://codepen.io/sevenumr/pen/NWGKMwr?editable=true&editors=001)

### Steps to reproduce
Switch to the tab which is not the first

### What is expected?
The Tab Content shows correctly

### What is actually happening?
The Tab Content flashed and then disappear

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16 |
| System | macOS Mojave 10.14.1 |
| Browser | Safari 13.1 |

**Comment by afc163** [comment]
I can't reproduce any flash in your codepen.

**Comment by SevenUMR** [comment]
![safari13 1](https://user-images.githubusercontent.com/15668756/78994492-d055e600-7b72-11ea-804b-b9a35991d911.gif)

Maybe Safari’s bug?

**Comment by imhxc** [comment]
This is indeed a bug under Safair.
You can temporarily solve it in any of the following ways:

1. Close the animation;
2. Increase the transition time of the animation slightly;
3. Add the `-webkit-backface-visibility: hidden` CSS property to the animation execution element.

**Comment by tawfek** [comment]
Same here in Chrome/80.0.3
useragent (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36)

The problem fixed by turn of the animation (animated={false})

**Comment by knowankit** [comment]
https://github.com/bangthetable/blue-haven/pull/3660
