### ISSUE TITLE
Form onFieldsChange is executing while validating the Form Value

### ISSUE THREAD

**Issue by viranmalaka** [ant-design/ant-design#23060]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-7i62tz](https://stackblitz.com/edit/react-7i62tz)

### Steps to reproduce
```
class Demo extends React.Component {
  formRef = React.createRef();

  render() {
    return (
      <Form 
        ref={this.formRef} 
        name="control-ref" 
        onFieldsChange={(e) => console.log('form on change', e)}
      >
        <Button 
          onClick={() => this.formRef.current.validateFields().then(console.log)}
          >
          Run Validation
        </Button>
        <Form.Item
          name="note"
          label="Note"
        >
          <Input />
        </Form.Item>
      </Form>
    );
  }
}
```

### What is expected?
Form onFieldChange function should not execute while validating the form.

### What is actually happening?
Form onFieldChange function is executing while validating the form.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | Ubuntu |
| Browser | Chrome |

---
I am loading some sets of data into a form and it has a submit button that is being enabled when the form is touched. I am simply triggering a modal with data from the form. But before that, I just execute the `validateFields` method to check whether the data in the form is valid or not. In that scenario, as a side effect, I can see my submit button is being enabled because the form fields are getting touched.

**Comment by zombieJ** [comment]
`onFieldChange` will trigger 3 times when rule is provided:
1. User input to trigger `onFieldChange`
2. Rule validating
3. Rule validated

`form.isFieldValidating` changes `false` -> `true` -> `false` by steps. `onFieldsChange` is design for out data control like redux. User can not input anything since fields value is not set since `onFieldsChange` not trigger.

In your case, you can this demo to dynamic control button disabled status: https://ant.design/components/form-cn/#components-form-demo-inline-login

**Comment by DenysVuika** [comment]
The behavior is absolutely insane! (sorry).
I'm subscribing to the `onFieldsChange` and there is no way to find out whether all the checks are finished and the handler deals with the final value/field!

**Comment by fyodorovandrei** [comment]
@DenysVuika Ant Form have `onValuesChange` method
