### ISSUE TITLE
Form.List 嵌套 Form.List 应该如何使用啊？

### ISSUE THREAD

**Issue by oyhk** [ant-design/ant-design#23065]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
      <Form.List name='users'>
        <Form.Item name='id'>
        <Input/>
        </Form.Item>
        <Form.List name='comments'>
          <Form.Item name='content'>
            <Input />
          </Form.Item>
        </Form.List>
      </Form.List> 

我想解决嵌套Json的需求，麻烦支持一下！谢谢了

### What does the proposed API look like?
"users":[
  {
    "id":1,
    "comments":[
      "id":10,
      "content":"这里是评论"
     ]
  }
]

**Comment by hengkx** [comment]
https://github.com/react-component/field-form/blob/master/examples/list.tsx

**Comment by oyhk** [comment]
上面的例子只是单层Form.List的使用，我想要嵌套的
`  <Form.List name='users'>
    <Form.Item name='id'>
    <Input/>
    </Form.Item>
    <Form.List name='comments'>
      <Form.Item name='content'>
        <Input />
      </Form.Item>
    </Form.List>
  </Form.List> `

**Comment by guilhermemiua** [comment]
Hi, I'm actually facing the same problem. I can use the Form.List, but using another Form.list inside does not work.

@oyhk did you found a way to do this?

@hengkx I think you have misunderstood our problem. Can you revisit this issue?

Thank you guys.

**Comment by oyhk** [comment]
> Hi, I'm actually facing the same problem. I can use the Form.List, but using another Form.list inside does not work.
> 
> @oyhk did you found a way to do this?
> 
> @hengkx I think you have misunderstood our problem. Can you revisit this issue?
> 
> Thank you guys.

I have solved this problem.

**Comment by afc163** [comment]
Should I close this issue?

**Comment by yoyo837** [comment]
> > Hi, I'm actually facing the same problem. I can use the Form.List, but using another Form.list inside does not work.
> > @oyhk did you found a way to do this?
> > @hengkx I think you have misunderstood our problem. Can you revisit this issue?
> > Thank you guys.
> 
> I have solved this problem.

How did you solve it?

**Comment by oyhk** [comment]
https://gitee.com/oyhk/mkfree-deploy/blob/release/1.1.0/frontend/src/pages/project/components/ProjectFrom.tsx

**Comment by xizheng** [comment]
> https://gitee.com/oyhk/mkfree-deploy/blob/release/1.1.0/frontend/src/pages/project/components/ProjectFrom.tsx

same problem
I think now, the only way to fix is wrap it to your custom Component

**Comment by bruceeewong** [comment]
after test, Form.List can work with embeded data like below:
`{
  "level1List": [
    {
      "level2List": [
        {"key": ""}
      ]
    }
  ]
}
`
write the form like below:
`
<Form.List name="level1List">
  {(level1Fields) => (
    <div>
      {level1Fields.map((level1Field, level1Index) => (
        <Form.List name={[level1Field.name, 'level2List']}    // notice here, using name path
        {(level2Fields) => (
          <div>
            {level2Fields.map((level2Field, level2Index) => (
              <Form.Item
                name={[level2Field.name, 'key']}  // notice the field name should be level2Field.name
              >
                <Input />
              </Form.Item>
            )}
          </div>
        )}
        </Form.List>
      )}
    </div>
  )}
</Form.List>
`
hope this helps.

**Comment by seriousFace-Ian** [comment]
> https://github.com/react-component/field-form/blob/master/examples/list.tsx

@hengkx The link has expired, can you provide another one?

**Comment by hengkx** [comment]
@seriousFace-Ian https://field-form-react-component.vercel.app/demo/list

**Comment by wangweiwg** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> ```
>   <Form.List name='users'>
>     <Form.Item name='id'>
>     <Input/>
>     </Form.Item>
>     <Form.List name='comments'>
>       <Form.Item name='content'>
>         <Input />
>       </Form.Item>
>     </Form.List>
>   </Form.List> 
> ```
> 
> 我想解决嵌套Json的需求，麻烦支持一下！谢谢了
> 
> ### What does the proposed API look like?
> "users":[ { "id":1, "comments":[ "id":10, "content":"这里是评论" ] } ]

hi, have you resolve that problem ？

**Comment by itart-top** [comment]
> after test, Form.List can work with embeded data like below:
> 
> ```
> {
>   "level1List": [
>     {
>       "level2List": [
>         {"key": ""}
>       ]
>     }
>   ]
> }
> ```
> 
> write the form like below:
> 
> ```
> <Form.List name="level1List">
>   {(level1Fields) => (
>     <div>
>       {level1Fields.map((level1Field, level1Index) => (
>         <Form.List name={[level1Field.name, 'level2List']}    // notice here, using name path
>         {(level2Fields) => (
>           <div>
>             {level2Fields.map((level2Field, level2Index) => (
>               <Form.Item
>                 name={[level2Field.name, 'key']}  // notice the field name should be level2Field.name
>               >
>                 <Input />
>               </Form.Item>
>             )}
>           </div>
>         )}
>         </Form.List>
>       )}
>     </div>
>   )}
> </Form.List>
> ```
> 
> hope this helps.

it works, thanks!
