### ISSUE TITLE
table 可伸缩列，当数据量较大，单元格渲染内容复杂时，可伸缩明显卡顿

### ISSUE THREAD

**Issue by kxcy001123** [ant-design/ant-design#23066]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keshensuolie-ant-design-demo-t671q?file=/index.js)

### Steps to reproduce
1. 打开链接
2. 拖拽可伸缩列

### What is expected?
1. 可流畅拖拽

### What is actually happening?
1. 拖拽明显卡顿

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.8.4 |
| System | mac |
| Browser | chrome 75.0.3770.100 |

**Comment by zombieJ** [comment]
Demo 是举例，如果有性能调优的话。你可以使用分页 or 参考虚拟滚动的例子：https://ant.design/components/table-cn/#components-table-demo-virtual-list

**Comment by JhonXY** [comment]
@zombieJ 将拖拽和虚拟滚动的Demo结合了下，但是发现虚拟滚动失效了，实在是找不到原因：
https://codesandbox.io/s/zealous-cookies-hvfbb?file=/index.js

**Comment by Xiaoqiang-Du** [comment]
> Demo 是举例，如果有性能调优的话。你可以使用分页 or 参考虚拟滚动的例子：https://ant.design/components/table-cn/#components-table-demo-virtual-list

拖拽会错位
