### ISSUE TITLE
Ability to set Select 'No Data'

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#23064]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8kfc9?file=/index.js)

### Steps to reproduce
```js
import React from "react";
import ReactDOM from "react-dom";
import { Select, Table } from "antd";
import "antd/dist/antd.css";
import "./index.css";

ReactDOM.render(
  <div>
    <Table 
      locale={{emptyText: 'Custom data'}}
      columns={[
          {
              title: 'Name',
              dataIndex: 'name'
          }
        ]}
      />

    <Select 
      locale={{emptyText: 'Custom data'}} 
      style={{width: 200}} 
    />

  </div>,
  document.getElementById("root")
);
```
### What is expected?
Ability to set Select 'No Data'

### What is actually happening?
Disability to set Select 'No Data'

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.11.0 |
| System | macOS |
| Browser | Safari |

**Comment by zombieJ** [comment]
Select use `notFoundContent` to set empty content.

**Comment by monolithed** [comment]
@zombieJ, are there any plans to combine these properties?
It's strange to have different names of the same functionality....

```ts
notFoundContent?: React.ReactNode;
emptyText?: React.ReactNode | string;
```

**Comment by zombieJ** [comment]
We recommend to use `renderEmpty` on ConfigProvider to config global empty style. `emptyText` & `notFoundContent` is legacy prop but still support.

**Comment by lgants** [comment]
@zombieJ unless I'm mistaken, a big issue with renderEmpty is inability to dynamically set text and use custom component. For example, if I wanted to dynamically display 'No Messages' in only one list in the app

**Comment by zombieJ** [comment]
HOC of Select which wrapped with ConfigProvider.
