### ISSUE TITLE
需要一个有后缀的数字输入框，Input还是InputNumber？

### ISSUE THREAD

**Issue by WanAn0902** [ant-design/ant-design#23069]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我需要在数字输入框的最后加一个后缀，使用InputNumber的formatter属性，后缀就只能在输入内容后面，而不是固定在输入框的最后；
使用Input，设置type="number"，但是又不能限制输入数字的最大小值了

### What does the proposed API look like?
希望让InputNumber可以像Input一样添加前缀prefix和后缀suffix

**Comment by zombieJ** [comment]
Duplicate of #14284

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-qy8jn?file=/index.js

原生 input 支持 max 和 min 。

**Comment by WanAn0902** [comment]
> https://codesandbox.io/s/antd-reproduction-template-qy8jn?file=/index.js
> 
> 原生 input 支持 max 和 min 。

支持max和min属性，但并没有antd的InputNumber的效果，使用InputNumber时当输入值不在范围内失去焦点后会自动变为限制值，而Input没有
