### ISSUE TITLE
Hover and Select CSS variables - Ant design V4.0 Select and Hover colors are swapped

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#23061]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Can someone explain why the colors of Selected and Hover were swapped.
Official release says: 

> Exchanged Selected and Hovered color.  The color of selected components is changed to `@blue-1: #E6F7FF`, and the corresponding hover color is changed to `@gray-2: #FAFAFA`.

This is not a minor color change but a complete swap. 

 1. What were the reasons driving it: 

If you are using a lot of tables, drop downs etc this will completely change the way your hovers and select look, its a significant change for users who have been used to the original design.
I think it is great that there is a plan to have consistency, but ***Gray for hover is more close to indicating something that is disabled***. 

 2. Is there a universal place where this can be changed using a variable to be like a lighter version of light blue  instead?

And looks like it is not universally applied. Here are a few examples
`Select V3`: 
Selected tags in the input box - Gray. 
Tags in the dropdown on hover -  Blue
Tags in the dropdown Selected -  Gray

`Select V4`: 
Selected tags in the input box - Gray. 
Tags in the dropdown on hover -  Gray
Tags in the dropdown Selected -  Blue

Selected tags in input box (gray) and in dropdown (blue) no longer match in color

`Tree V3`: 
Hover: Light Blue background
Selected: Dark background

`Tree V4`: 
Hover: Gray background
Selected: Blue background

Same principal how ever is not applied to `Menus`, `buttons`, `pagination` etc. Which are generally following the rule of Blue-Blue combination for hover-select instead of a gray variation

`Menu V3 and V4`:
Item Hover: Blue Text
Item Selected: Blue Text, Blue Background
No Gray here for V4?

`Date Picker V3`: 
Hover: Blue background
Selected: Blue background

`Date Picker V4`: 
Hover: Blue Dotted border
Selected: Blue background

Again no Gray here.

I think most components have a blue-blue hover and select combination, but there are some exceptions which and have gray-blue instead. I would instead want to know a way to override this universally.
But before that trying to understand the driving principal behind it since the design docs don't say anything.

### What does the proposed API look like?
@background-hover
@background-select

OR
**Do away with the Blue-Gray combinations for select, Tree etc and instead use a Blue-Blue approach similar to Menus.
On Hover the text turns blue instead of background turning gray.**

**Comment by StallionV** [comment]
Hello Ant designers can you confirm if someone is looking at this ?

**Comment by afc163** [comment]
@AntDesigners

**Comment by StallionV** [comment]
@AntDesigners please can you update us on this?

**Comment by yingxirz** [comment]
Hover state is less importance than selected state.
Hover state means that an object should provide visual feedback to express the interactivity and pointing accuracy (affordance) when the cursor is pointing to an object. Although the feedback should be perceived , it's no need to be too strong. But highlight selected is because  as long as user selected the object , means it is higher priority than others.
We are sorting palettes and its usage systematically. Soon there will be some conclusions.
