### ISSUE TITLE
其他组件里面嵌套菜单组件渲染报错

### ISSUE THREAD

**Issue by llh520xw** [ant-design/ant-design#2306]
[

### 本地环境

使用的组件
![image](https://cloud.githubusercontent.com/assets/13639327/16677214/12e12b08-4506-11e6-8e65-d028001a7abe.png)
![image](https://cloud.githubusercontent.com/assets/13639327/16677225/2a435032-4506-11e6-8b02-82822cc69438.png)

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

### 你做了什么？
在main.jsx里面嵌套菜单组件

### 你期待的结果是：
正常的渲染出菜单组件

## 实际上的结果：
渲染报错
![image](https://cloud.githubusercontent.com/assets/13639327/16677264/836098d2-4506-11e6-8621-4dc7abe90d72.png)

**Comment by afc163** [comment]
subMenu => SubMenu

**Comment by llh520xw** [comment]
....真的是这个原因，十分感谢
