### ISSUE TITLE
Cascader组件expandTrigger为hover，悬浮到无次级菜单时，次级显示了上一次的次级菜单，造成误解

### ISSUE THREAD

**Issue by zhuchuanlei** [ant-design/ant-design#23075]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-mbc0q?file=/index.js)

### Steps to reproduce
悬浮到有次级的选项，再悬浮到无次级的选项

### What is expected?
悬浮到无次级的选项时，次级框不显示

### What is actually happening?
悬浮到无次级的选项时，次级框显示的是上一次的次级

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 17 |
| System | mac |
| Browser | google |

**Comment by zombieJ** [comment]
`expandTrigger` 的 `click` 和 `hover` 是一致的，激活后展示下一层。hover 选项是有明确的背景色来区分的。

**Comment by afc163** [comment]
Duplicate of #28774
