### ISSUE TITLE
请问一下，Menu菜单onClick事件，如何拿到菜单的title?

### ISSUE THREAD

**Issue by niss2000** [ant-design/ant-design#2307]
主要是菜单点击后会生成一个tab，tab的title要和菜单的title一致，谢谢

**Comment by yuzhouisme** [comment]
点击菜单时，可以取到menu的key值，即（e.key）
那么，我想有几种方法，
1. 使用title设置menu的key的值（可能存在效率问题）；
2. 使用数组／字典，构建key/value这种键值对，那么你的问题迎刃而解；

**Comment by niss2000** [comment]
谢谢，已经解决了，通过event.item.props.children可以拿到菜单的title
