### ISSUE TITLE
Button icon with loading animation weird

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#23070]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-grucr?file=/index.js)

### Steps to reproduce

![Kapture 2020-04-09 at 10 36 21](https://user-images.githubusercontent.com/14831261/78852065-fafa4e80-7a4d-11ea-92e4-67a48cadc824.gif)

![Kapture 2020-04-09 at 10 37 11](https://user-images.githubusercontent.com/14831261/78852111-16655980-7a4e-11ea-81ff-34dbbc8a6054.gif)

### What is expected?
animation normal

### What is actually happening?
animation weird

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.0 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by zombieJ** [comment]
猫兄自给自足一下搞个 fix 😄？

**Comment by afc163** [comment]
正确的动画应该是这样的：https://3x.ant.design/components/button-cn/#components-button-demo-loading

**Comment by shaodahong** [comment]
嗯，4.0 的点起来很奇怪，我大概知道什么原因了， `flex` 的问题
