### ISSUE TITLE
TreeSelect的title与treeNodeLabelProp

### ISSUE THREAD

**Issue by WanAn0902** [ant-design/ant-design#23079]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
想要自定义回显内容，升级V4后树结构显示的太冗余了，但V3版本的TreeSelect的treeNodeLabelProp属性只处理了回显，树结构内容就比较简单；
毕竟如果在树结构中就要全部显示，只用title都可以满足了

### What does the proposed API look like?
树结构内容展示的title只显示每一层自己的内容，回显的时候才显示treeNodeLabelProp的内容，这个可以优化吗？

**Comment by zombieJ** [comment]
不太明白你说的内容……能说的更详细一些不？

**Comment by WanAn0902** [comment]
> 不太明白你说的内容……能说的更详细一些不？

额....首先我很抱歉，我没描述清楚我的问题🤩。。。。

我引用[#22177](https://github.com/ant-design/ant-design/issues/22177)的例子，比如有2个节点

```
- 男性
  - 0-3 岁
  - 3-18 岁
  - 18 岁以上
  - 60 岁以上
- 女性
  - 0-3 岁
  - 3-18 岁
  - 18 岁以上
  - 60 岁以上
```
我想选中  女性 -> 18岁以上  后输入框回显为  

> 女性-18岁

此时如果使用treeNodeLabelProp，则树结构会显示为
```
- 男性
  - 男性 - 0-3 岁
  - 男性 - 3-18 岁
  - 男性 - 18 岁以上
  - 男性 - 60 岁以上
- 女性
  - 女性 - 0-3 岁
  - 女性 - 3-18 岁
  - 女性 - 18 岁以上
  - 女性 - 60 岁以上
```

> 简单来说就是我想下面选择的树简单显示，上方input框，选中的值需要显示全，

类似的issue在[#22177](https://github.com/ant-design/ant-design/issues/22177)中有人提过，但一直没有找到更合适的解决方案

**Comment by zombieJ** [comment]
懂了，是弹出框里显示的和输入框显示的不同是吧？

**Comment by WanAn0902** [comment]
> 懂了，是弹出框里显示的和输入框显示的不同是吧？

对对对🤩就是要不同，可是目前不支持，我觉得v4的title属性和treeNodeLabelProp属性的功能是差不多的

**Comment by zombieJ** [comment]
我和设计师对一对，看看选项和展示不同是不是一种好的设计。

**Comment by leezng** [comment]
同样的需求，在v3上可以实现，v4这个属性改了就不行了
tree-select作为目录选择器，每一层只显示当前层级目录名，选完后显示完整路径/xxx/xxxxxx

**Comment by debuggerccai** [comment]
这个问题有推进吗？我在最近的迭代过程中有这种场景的需求

**Comment by stxwd46** [comment]
> 我和设计师对一对，看看选项和展示不同是不是一种好的设计。

这个问题目前有新进展吗？业务场景还是需要用到自定义回显的。而且 antd3.x 是支持的。为什么 4 反而不支持呢？可以提供个开关让用户自己选择要不要自定义回显吧

**Comment by azx1985** [comment]
这次我们也有这样的需求，选择的时候有icon，回显的时候想去掉icon

**Comment by azx1985** [comment]
treeSelect里面有个value，用onChange修改state里面的value，修改是成功的，但是treeSelect里面的value值没有生效

**Comment by afc163** [comment]
@stxwd46 给一个 v3 生效 v4 不生效的 codesandbox 看看吧。

**Comment by WanAn0902** [comment]
> codesandbox

v3生效   https://codesandbox.io/s/elegant-hill-6k1wn?file=/index.js
v4不生效  https://codesandbox.io/s/focused-bassi-8zji8?file=/index.js
![image](https://user-images.githubusercontent.com/38753567/88136413-c5076180-cc1b-11ea-984d-a251f5bc3739.png)

**Comment by Latiest** [comment]
解决了吗
