### ISSUE TITLE
Progress 设置steps 分段进度条 strokeColor 无法使用渐变色

### ISSUE THREAD

**Issue by andyhuai** [ant-design/ant-design#23072]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
渐变色的分段进度条
<Progress percent={30} strokeWidth={15} steps={20} strokeColor={{
          '0%': '#108ee9',
          '100%': '#87d068',
        }}/>

### What does the proposed API look like?
能够设置渐变色

**Comment by yoyo837** [comment]
https://ant.design/components/progress-cn/#type=%22line%22 只有line支持渐变

**Comment by afc163** [comment]
试了下目前的 dom 结构只能做成这样的：

<img width="146" alt="image" src="https://user-images.githubusercontent.com/507615/78858309-9e535f80-7a5e-11ea-9231-de6b76b5103c.png">

😅 肯定不是想要的。

改造起来会很麻烦，暂时不予支持了。
