### ISSUE TITLE
v4 <Form> 自定义校验validator，如何做防抖？

### ISSUE THREAD

**Issue by maxmeng93** [ant-design/ant-design#23077]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rkzno)

### Steps to reproduce
antd v4 自定义校验绑定防抖会报错。因为必须返回一个Promise。我应该怎么处理？
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-form-%E9%98%B2%E6%8A%96.2pzkuczn3wt.gif)

### What is expected?
自定义校验可以使用防抖

### What is actually happening?
自定义校验不可以使用防抖

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome |

**Comment by zombieJ** [comment]
直接延迟就行了，每次触发新的校验，过去的校验无论是否进行中都会被舍弃：

https://codesandbox.io/s/antd-reproduction-template-3jz2i?file=/index.js

**Comment by maxmeng93** [comment]
谢谢

**Comment by maxmeng93** [comment]
好像并没有达到节流的效果。如果这里需要请求后台接口做验证，还是会频繁请求。

```diff
  checkName = async (rule, value) => {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (value) {
+          console.log('true')
          resolve();
        }
        reject("不能为空");
      }, 500);
    });
  };
```
![image](https://raw.githubusercontent.com/maxmeng93/picee/master/bug/antd-form-%E9%98%B2%E6%8A%96-1.s9y864s593n.gif)

**Comment by yoyo837** [comment]
封装一下，如果在执行前有新的任务发起，setTimeout给clear一下

**Comment by maxmeng93** [comment]
```jsx
class App extends React.Component {
  timer = null;

  checkName = (rule, value) => {
    if (this.timer) {
      clearTimeout(this.timer);
    }

    return new Promise((resolve, reject) => {
      this.timer = setTimeout(() => {
        if (value) {
          console.log(true)
          return resolve();
        }
        return reject("不能为空");
      }, 800);
    });
  };

  render() {
    return (
      <Form>
        <Form.Item
          name="name"
          label="名字"
          rules={[{ validator: this.checkName }]}
        >
          <Input />
        </Form.Item>
      </Form>
    );
  }
}
```

**Comment by dadazhouRenee** [comment]
接口校验的时候 validateStatus 好像没有改变成 "validating"

**Comment by MINGLIANG98** [comment]
靠一个变量维护 怎么复用呢 这样搞太麻烦了
