### ISSUE TITLE
在Modal组件里面的表单，第一次点击提交按钮，页面刷新，在路由地址上加了个问号

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design#23073]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/form-cn/#header](https://3x.ant.design/components/form-cn/#header)

### Steps to reproduce
无

### What is expected?
第一次点击不会刷新页面

### What is actually happening?
第一次点击刷新了页面

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | mac |
| Browser | 谷歌 |

**Comment by z-lionel** [comment]
点击之后刷新页面，地址多加了个问号，如下
http://localhost:8000/?#/

**Comment by zombieJ** [comment]
这是 html 里 form 的默认行为和 antd 无关，你需要在 onSubmit 时间里调用 `preventDefault` 阻止游览器行为。

**Comment by vimcaw** [comment]
@zombieJ 现在最新版本(4.6.2)的 Form 没有 `onSubmit` 事件了，只有个 `onSubmitCapture` ，在里面调用 `preventDefault` 后还是会刷新页面，\`onFinish\` 之类的事件也没有提供 `event` 对象，想问下最新版本下应该如何阻止浏览器默认行为呢？

**Comment by zombieJ** [comment]
给个重现看看，Form 默认 preventDefault 的

**Comment by vimcaw** [comment]
@zombieJ 搞错了，经过排查是别的地方导致的，确实已经 `preventDefault` 过了，不好意思。 😓
