### ISSUE TITLE
Add a text color prop for the tag

### ISSUE THREAD

**Issue by romu70** [ant-design/ant-design#23082]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, we can specify custom color for the tag component. But as soon as a color is specified, the text is white, and this can't be easily changed. This change would allow Ant users to specify color combinations more legible or more "brand oriented" (for instance a light background color with a dark text).

### What does the proposed API look like?
```textColor``` as a string to specify the...text color

**Comment by afc163** [comment]
https://codesandbox.io/s/basic-ant-design-demo-3iyuj

**Comment by romu70** [comment]
Ok thanks for the workaround. But honestly, there is no documentation, and no way to find this feature for a non coder. I suggest to revise your judgement about this issue.

**Comment by PeterMain** [comment]
If you have a color tag:
<Tag color="#D9A54F"> there's seemingly no way to have a text color other than white. The proposed workaround doesn't address this.

**Comment by amaxalov** [comment]
@romu70 I agree with you, this is not the answer to the question. Why does antd have a color library for designers? To add them inline manually?

**Comment by romu70** [comment]
@amaxalov that's why I gave up with Ant for my new projects.
