### ISSUE TITLE
Table组件filter点击时错误 Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2308]
### 本地环境

- antd 版本: 1.6.4
- 操作系统及其版本：ubuntu 16.04
- 浏览器及其版本:  51.0.2704.79 Ubuntu 16.04 (64-bit)

### 你做了什么？

使用antd 了 Table filter功能 

### 你期待的结果是：

filter点击时功能正常

## 实际上的结果：

报错Cannot read property 'offsetWidth' of null

### 可重现的在线演示

官网可重现

**Comment by yiminghe** [comment]
重装
