### ISSUE TITLE
Modal.method()是否支持getContainer？

### ISSUE THREAD

**Issue by Codevers** [ant-design/ant-design#23085]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在业务组件开启全屏后，使用Modal.method()形式的弹窗，需设置getContainer才可正常工作（不使用<Modal>组件的原因是为了减少繁琐程度）

### What does the proposed API look like?
```js
 Modal.confirm({
            title: '确认要删除此数据吗？',
            icon: <ExclamationCircleOutlined/>,
            content: '',
            okText: '确认',
            getContainer :true,
            okType: 'danger',
            cancelText: '取消',
            onOk: () => {
            }
 })
```

**Comment by afc163** [comment]
支持：https://github.com/ant-design/ant-design/commit/877f9fd7d64b2e41fb7a6312398b7c1bcc3f6cc3

**Comment by afc163** [comment]
@Codevers 可以来个 PR 补充一下文档。

**Comment by afc163** [comment]
@Codevers Could you help us improve document?

**Comment by wangxiaogang94** [comment]
message的和这个不一样吧
