### ISSUE TITLE
umi3工程开启中文设置后antd时间控件RangePicker月份不显示中文

### ISSUE THREAD

**Issue by adongroom** [ant-design/ant-design#23088]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

https://codesandbox.io/s/jiben-ant-design-demo-fs0bg?file=/index.js

### Steps to reproduce
npm run serve后  首页的时间控件点开是半汉化状态

### What is expected?
月份显示中文

### What is actually happening?
月份是英文

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | umi3集成 |
| System | mac os |
| Browser | chrome 最新版 |

**Comment by ycjcl868** [comment]
抽取一个 codesandbox， @zombieJ  可以跟进下

**Comment by juxiaowei** [comment]
ant pro 集成的 antd 4.0.1 同样存在汉化问题

**Comment by zombieJ** [comment]
看了一下，需要 `import "moment/locale/zh-cn";` :https://codesandbox.io/s/jiben-ant-design-demo-fs0bg?file=/index.js

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/78899161-8fdd6600-7aa7-11ea-9fb0-2e478b6c3c4f.png)

插件里已经加了

**Comment by ycjcl868** [comment]
看了下，是项目里 external 了 moment，去掉后，ok 了。

![image](https://user-images.githubusercontent.com/13595509/78901055-59edb100-7aaa-11ea-95f1-9e9f0229cbd2.png)

**Comment by afc163** [comment]
external moment 的话需要把 moment locale 的 cdn 也引入才行。
