### ISSUE TITLE
<Form layout="inline">模式下，行与行间没有间距，也没法调整

### ISSUE THREAD

**Issue by chinple** [ant-design/ant-design#23084]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wonderful-lichterman-br63z?file=/index.js:0-1549)

### Steps to reproduce
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Form, Input, Button, Col, Row } from "antd";
import { MinusCircleOutlined, PlusOutlined } from "@ant-design/icons";

const layout = {
  labelCol: { span: 8 },
  wrapperCol: { span: 12 },
};
const tailLayout = {
  wrapperCol: {  span: 16112 },
};

const Demo = () => {
  const onFinish = values => {
    console.log('Success:', values);
  };

  const onFinishFailed = errorInfo => {
    console.log('Failed:', errorInfo);
  };

  return (
    <Form layout="inline" 
      {...layout}
      name="basic"
      initialValues={{ remember: true }}
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
    >
      <Form.Item
        label="Username"
        name="username"
        rules={[{ required: true, message: 'Please input your username!' }]}
      >
        <Input />
      </Form.Item>

      <Form.Item
        label="Password"
        name="password"
        rules={[{ required: true, message: 'Please input your password!' }]}
      >
        <Input.Password />
      </Form.Item>
      <br/>
      <Form.Item
        label="1212"
        name="121212"
        rules={[{ required: true, message: 'Please input your password!' }]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item {...tailLayout}>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
    </Form>
  );
};

ReactDOM.render(<Demo />, document.getElementById("container"));

### What is expected?
行与行间的间距不能调整

### What is actually happening?
行与行间的间距有默认的间距，或者可以调整

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.9.0 |
| System | chrome |
| Browser | chrome |

**Comment by chinple** [comment]
https://codesandbox.io/s/silly-tdd-3evlf?file=/index.js 这个地址

**Comment by afc163** [comment]
`layout="inline"` 意味着整个 Form 就是一行，不存在行与行之间的概念。

**Comment by chinple** [comment]
![image](https://user-images.githubusercontent.com/6138875/78874336-d4084080-7a7e-11ea-884d-9c853d49142f.png)
挤一块了，行与行间能否搞个间隔。3.*系列是默认有间隔的比较好看

**Comment by chinple** [comment]
这个导致我3.*系列不能升级到4.*

**Comment by zombieJ** [comment]
v3 的间距是因为为了兼容旧版 IE 实现的问题导致的，没有间距才是 inline 正确的表现。你可以给 Form.Item 添加 `margin` 来实现自定义的间距。

**Comment by afc163** [comment]
可以自行添加 margin：https://codesandbox.io/s/eager-sutherland-mzcnb

**Comment by chinple** [comment]
感谢
