### ISSUE TITLE
(关于DatePicker) DatePicker现在支持了可以选择季度, 有没有考虑跨季度选择的打算?

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#23092]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
虽然说可以跨月份来查询, 但是得一个个选月份还得考虑是否选错, 比如第一季度到第三季度, 选了1月到9月, 少了10月.
不知道有没有支持跨季度选择的打算呢? (没有就只能自己实现了hha).

### What does the proposed API look like?
希望支持跨季度选择.

**Comment by afc163** [comment]
https://codesandbox.io/s/range-picker-ant-design-demo-hdx2l?file=/index.js

好像已经是支持了的。

**Comment by crawler-django** [comment]
nice~
