### ISSUE TITLE
Select component tries to perform state update after unmounting

### ISSUE THREAD

**Issue by pmwmedia** [ant-design/ant-design#23093]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/pmwmedia/antd-select-unmount-issue](https://github.com/pmwmedia/antd-select-unmount-issue)

### Steps to reproduce
1. npm install
2. npm run test

### What is expected?
Select component won't perform any React state update after being unmounted

### What is actually happening?
Select component tries to perform a React state update after being unmounted, if the menu was just opened

```
 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
        in ForwardRef(Select) (created by Select)
        in Select (created by Context.Consumer)
        in Select (at MyComponent.js:7)
        in div (at MyComponent.js:6)
        in MyComponent (at MyComponent.test.js:6)
```

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | Windows 10 Pro Version 1903 |
| Browser | Node.js with Jest |

---
I can reproduce the issue on my local Windows computer as well as on Travis: https://travis-ci.com/github/pmwmedia/antd-select-unmount-issue/jobs/317561927

**Comment by afc163** [comment]
- https://github.com/react-component/select/blob/b9a0bcdce6d618293bbc66ed5c76098e8773afef/src/OptionList.tsx#L138
- https://github.com/react-component/select/blob/d795e2e076d64482c3c949fff268f8ec5ff721e3/src/generate.tsx#L790

@zombieJ We should reset this effects.
