### ISSUE TITLE
什么时候model可以支持拖动呀?

### ISSUE THREAD

**Issue by jave-joe** [ant-design/ant-design#23091]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
大大们,model弹出框不支持点着标题部位进行拖动,这个会考虑后期支持吗?

### What does the proposed API look like?
希望能有支持modal可拖动的解决方案

**Comment by afc163** [comment]
#3012
