### ISSUE TITLE
Transfer的自定义footer时，props中position属性怎么没了？

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2309]
### 本地环境

- antd 版本: 1.6.4
- 操作系统及其版本：
- 浏览器及其版本:

### 你做了什么？

Transfer自定义footer， 根据position的值(left, right) 来判定footer呈现不同的内容

1.6.3有这个属性，1.6.4去掉了，可以加回来吗？

**Comment by ddcat1115** [comment]
可以用 `titleText` 判断，两边标题肯定也是不一样的吧

**Comment by codering** [comment]
好吧，现在只能这样了，希望后面会改进

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/47230e4a329f7460213139163e41acd0cc6621c0#diff-406f50bdb6bcf15915388a8bd29fa69fL241

最好加回来，保持向下兼容。@ddcat1115
