### ISSUE TITLE
In Antd V4 Icons are duplicated in the webpack bundle

### ISSUE THREAD

**Issue by YannPl** [ant-design/ant-design#23096]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://i.imgur.com/6dLFw7p.png](https://i.imgur.com/6dLFw7p.png)

### Steps to reproduce
Require icons using the recomended method in the documentation and the upgrade guide.
For example:  `import { ArrowRightOutlined } from '@ant-design/icons';`

### What is expected?
Icons in the final bundle should be only imported once

### What is actually happening?
The generated bundles contains all icons duplicated:
![Bundle analyzer](https://i.imgur.com/6dLFw7p.png)
As we can see in the image above, both `icons/es/icons` AND `icons-svg/es/asn` are imported in the bundle.
For this example, I've highlighted in red all the icons containing "home" and we can see the 3 possible icons are duplicated.
This causes the icons bundle to be 2.51Mo (not compressed)

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13 |
| System | Linux |
| Browser | Chrome |

---
I use already Babel import plugin with the following config:
```
[
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": true
      }
    ],
```

**Comment by MarvinDurot** [comment]
I had the same issue on my client project. 
It's very annoying during development because my webpack watch task is longer.
Unfortunately I can't find any workaround solution..

**Comment by pmwmedia** [comment]
I use e.g. `import FileSearchOutlined from "@ant-design/icons/FileSearchOutlined";` to avoid bundling all icons in my project.

**Comment by YannPl** [comment]
> I use e.g. `import FileSearchOutlined from "@ant-design/icons/FileSearchOutlined";` to avoid bundling all icons in my project.

I get it but why are all icons duplicated in the bundle ?
What is different between `icons/es/icons` and `icons-svg/es/asn`
Why do we need both ?
