### ISSUE TITLE
Form V4 form.setFields doesn't work

### ISSUE THREAD

**Issue by sylhero** [ant-design/ant-design#23099]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-demo-k36ms?file=/index.js)

### Steps to reproduce
enter an invalid email

### What is expected?
it should show error message as "this is another error message"

### What is actually happening?
it's still using the default error message

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12.0 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
You should not `setFields` in validator. But message not sync with validator does a bug that I will check.

**Comment by zombieJ** [comment]
Checked. It's follow the behavior of v3: https://codesandbox.io/s/throbbing-butterfly-6m4vu?file=/index.js

**Comment by zombieJ** [comment]
ref https://github.com/yiminghe/async-validator/issues/234

**Comment by sylhero** [comment]
actually I just made it work so basically if you remove the message from the rules and use your customized validator just `throw new Error('whatever message you want')` it works

**Comment by reznord** [comment]
I am getting the following error message while doing `form.setFields`

```
Uncaught Error: Objects are not valid as a React child (found: Error: User with username 'asdas' not found.). If you meant to render a collection of children, use an array instead.
```

@sylhero can you update your sandbox with the fix if possible?

(thanks in advance)

**Comment by sylhero** [comment]
@reznord you can check again `form.setFields` is not needed

**Comment by reznord** [comment]
Great, thanks. :)
