### ISSUE TITLE
Select dropdown no longer triggered by onChange event

### ISSUE THREAD

**Issue by AceNorth** [ant-design/ant-design#23103]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-m6ub5?file=/index.js)

### Steps to reproduce
In the repro sandbox, open the console.

Type ```document.querySelector('.code-box-demo .ant-select-selector').click()```.

Note that the dropdown menu does not open.

Change the antd dependency to 3.26.15.

Type ```document.querySelector('.ant-select-selection__rendered').click()```.

Note that the dropdown menu opens.

You can see this behavior in the docs as well, go here: https://3x.ant.design/components/select/ and type ```document.querySelector('.code-box-demo .ant-select-selection__rendered').click()``` in the console.

Then go here: https://ant.design/components/select/ and type ```document.querySelector('.code-box-demo .ant-select-selector').click()```.

In v3 the menu opens, in v4 it does not.

### What is expected?
When a click event is called on the select component, the dropdown menu should render.

### What is actually happening?
When a click event is called on the select component, the dropdown menu does not render.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.3 |
| Browser | Chrome 80.0.3987.149 |

---
This is making it impossible for us to write integration tests in jest for modules that use the antd select component, because we have no way of triggering the dropdown menu to render. If someone has a workaround please let me know.

**Comment by pmwmedia** [comment]
I use a mouse down event in my Jest tests to open select menus: https://github.com/pmwmedia/antd-select-unmount-issue/blob/master/src/MyComponent.test.js

However, you will run in issue #23093 after your test, if you aren't lucky about timing and test order.

**Comment by afc163** [comment]
#23044
https://github.com/ant-design/ant-design/issues/22491#issuecomment-602180659
https://github.com/ant-design/ant-design/issues/22074#issuecomment-597061052
