### ISSUE TITLE
年选择器

### ISSUE THREAD

**Issue by xiamidong** [ant-design/ant-design#2310]
### 本地环境

- antd 版本:1.3.2
- 操作系统及其版本: mac 
- 浏览器及其版本:google

### 我的需求

 > 引入 antd 的DatePicker组件
>  DatePicker里面有月的选择，我想要用年选择器，有什么解决方法吗？

**Comment by afc163** [comment]
直接用 Select 。

**Comment by xiamidong** [comment]
不想用Select选择器，想要的效果如同日历选择器中点击年后的效果
