### ISSUE TITLE
mac系统下select滚动条被遮挡

### ISSUE THREAD

**Issue by Chastrlove** [ant-design/ant-design#23107]
![WX20200410-100746](https://user-images.githubusercontent.com/17813559/78955871-28f59680-7b13-11ea-8548-0e5478a7caa3.png)
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oqrrc)

### Steps to reproduce
输入1，出现滚动条，hover在任意一个option上，会使滚动条被遮挡

### What is expected?
滚动条不被option遮挡

### What is actually happening?
滚动条被option遮挡

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | macOS Catalina |
| Browser | chrome 81.0.4044.92 |

---
可以在虚拟滚动的父节点上加入z-index解决该问题

**Comment by yoyo837** [comment]
同版本浏览器，这边重现不了。另外你系统设置的滚动条不隐藏吗？

**Comment by zombieJ** [comment]
这个应该是修过的，重装一下依赖试试。 ref #20792 

如果还是无效，审查元素看看有没有什么地方设置了 will change 样式。

**Comment by Chastrlove** [comment]
> 同版本浏览器，这边重现不了。另外你系统设置的滚动条不隐藏吗？

没有，隐藏的，只是滑动的时候我截的图，我发现我这个问题，safari和firefox都是好的，就是chrome不行

**Comment by Chastrlove** [comment]
> 这个应该是修过的，重装一下依赖试试。 ref #20792
> 
> 如果还是无效，审查元素看看有没有什么地方设置了 will change 样式。

我看了下https://ant-design.gitee.io/components/select-cn/上面的例子也是这样，我重装了下浏览器发现没有变化，是不是和我Catalina系统10.15.4版本有关系

**Comment by zombieJ** [comment]
我的系统版本和你一样，但是没有看到这个现象。神奇。你能找个相同的机器也试试不？

**Comment by Chastrlove** [comment]
> 我的系统版本和你一样，但是没有看到这个现象。神奇。你能找个相同的机器也试试不？

额，应该是我的问题，我把chrome配置删干净了，然后重装就好了

**Comment by zombieJ** [comment]
👌thx，估计是什么插件搞的。
