### ISSUE TITLE
Warning: Prop `multiple` did not match. Server: "undefined" Client: "true"

### ISSUE THREAD

**Issue by silinchen** [ant-design/ant-design#23109]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-rfjys?file=/index.js)

### Steps to reproduce
use with next.js，when ssr the TreeSelect component will warning..

### What is expected?
treeselect component support ssr

### What is actually happening?
not support ssr. when use multiple prop

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.11.0 |
| System | mac os 10.12 |
| Browser | Google Chrome 80 |

**Comment by zombieJ** [comment]
Could you provides a git repo for reproduce? Your codesandbox can not reproduce it.
