### ISSUE TITLE
On selecting a row on table the hover color is retained until you hover away 

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#23106]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-3klvr?file=/index.js)

### Steps to reproduce
Create a table which allow row selection

### What is expected?
When you click on the select checkbox the row color should change from Gray to Blue
When you unselect it, it should change from Blue to Gray

### What is actually happening?
The row maintains its hover color Gray even when you select/unselect it

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13 |
| System | Mac OSX |
| Browser | Safari 13.1, Chrome 80.0 |

---
In Ant version 3.x this was not the case

**Comment by yoyo837** [comment]
Hover color is takes priority over row selected color.

**Comment by yoyo837** [comment]
When you select / deselect it on the row it is still in hover state until you leave this row.

**Comment by StallionV** [comment]
@yoyo837 that was not how it was in Ant v3.x please check the demos.
Previously when you hover you see the hover color and the moment you select the select color takes priority over hover and you are immediately able to see the change, if you now unselect you can see back the hover color so the instant feedback actually makes sense.

Currently even when you select you still see gray and you actually have to move away to confirm your change that’s not a good user experience.

**Comment by zombieJ** [comment]
> @yoyo837 that was not how it was in Ant v3.x please check the demos.
> Previously when you hover you see the hover color and the moment you select the select color takes priority over hover and you are immediately able to see the change, if you now unselect you can see back the hover color so the instant feedback actually makes sense.
> 
> Currently even when you select you still see gray and you actually have to move away to confirm your change that’s not a good user experience.

Thanks for reply. Let me check.

**Comment by yoyo837** [comment]
> @yoyo837 that was not how it was in Ant v3.x please check the demos.
> Previously when you hover you see the hover color and the moment you select the select color takes priority over hover and you are immediately able to see the change, if you now unselect you can see back the hover color so the instant feedback actually makes sense.
> 
> Currently even when you select you still see gray and you actually have to move away to confirm your change that’s not a good user experience.

Aha, after you reminded, I just noticed this difference.
