### ISSUE TITLE
Select and other components do not align when not using default size

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#23105]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-miwqt)

### Steps to reproduce
Place a Select and Search component or Button next to each other (in-line).
Ensure they are of same size e.g. Small, Default or Large

### What is expected?
They should all align completely

### What is actually happening?
Only the components with default size align, the small and large do not.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13 |
| System | Mac OSX |
| Browser | Safari 13.1, Chrome 80.0 |

---
This seems to be more of a problem for Select component. When other components are aligned e.g. Search and Button they seem to work well

**Comment by zombieJ** [comment]
Will patch for this. Align style recommend to use Space component since Browser render logic usually affect the align: https://codesandbox.io/s/antd-reproduction-template-miwqt?file=/index.js

**Comment by StallionV** [comment]
Thank you you guys are pretty fast 👍👌
