### ISSUE TITLE
Normalize is not been called when using form.setFieldsValue

### ISSUE THREAD

**Issue by lopesrichard** [ant-design/ant-design#23104]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/richardbranvo/pen/PoPoxdd](https://codepen.io/richardbranvo/pen/PoPoxdd)

### Steps to reproduce
1. Create a form with an input
2. Insert a normalize function on that input
3. Type on input
4. Create a form variable using the hook Form.useForm();
5. Change the value of the input programatically using form.setFieldsValue()

### What is expected?
It's expect the normalize function been called when changing values using setFieldsValue function

### What is actually happening?
The normalize function is not been called.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by zombieJ** [comment]
`normalize` only trigger when form get value from component trigger event. It do not replace `setFields` value. In next minor version. Field will provide `getValueProps`. It give the ability to set Component value before render.

Let me update doc for more description.

**Comment by lopesrichard** [comment]
Is there already a way to achieve that?
