### ISSUE TITLE
Horizontal top navigation menu dark theme problem

### ISSUE THREAD

**Issue by huangshuwei** [ant-design/ant-design#23119]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/top-navigation-ant-design-demo-n2znu?file=/index.js)

### Steps to reproduce
official menu component,change the theme to dark

### What is expected?
dropdown menu item is visible

### What is actually happening?
dropdown menu item is not visible

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | react |
| System | win10 |
| Browser | chrome 81.0.4044.92 |

**Comment by afc163** [comment]
Fixed in #23054
