### ISSUE TITLE
Ability to switch themes live

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#23116]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Give a component that makes it easier to which themes live from light to dark or compact.
Currently there does not seems to be an easy or straight forward documentation or example that shows this, although AntD site has this implemented.
Please update documentation to show a live example if you can on how the AntD site is doing it

### What does the proposed API look like?
```
<Theme type="dark">
Wrap your application in this or any component in this.
</Theme>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/10384
https://github.com/ant-design/ant-design/issues/4837#issuecomment-380583445

**Comment by StallionV** [comment]
You guys keep closing this without actually telling us or adding any documentation that shows how to get this done?
