### ISSUE TITLE
升级antd4后运行构建命令报错less问题

### ISSUE THREAD

**Issue by sujiangyin** [ant-design/ant-design#23125]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/docs/react/migration-v4-cn#%E5%BC%80%E5%A7%8B%E5%8D%87%E7%BA%A7](https://ant-design.gitee.io/docs/react/migration-v4-cn#%E5%BC%80%E5%A7%8B%E5%8D%87%E7%BA%A7)

### Steps to reproduce
npm start

### What is expected?
构建无报错

### What is actually happening?
$ npm start

> work_loan_open@0.1.0 start F:\dev\dev open\work_loan_open\htdocs
> node scripts/start.js

Starting the development server...

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
Failed to compile.

./src/assets/less/manage/base.less (./node_modules/css-loader??ref--5-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/less-loader/dist/cjs.js??ref--5-oneOf-3-3!./src/assets/less/manage/base.less)

      /* stylelint-disable-next-line function-calc-no-invalid */
      padding-right: calc(@drawer-header-close-padding - var(--scroll-bar));
    ^
Cannot read property 'numerator' of undefined
      in F:\dev\dev open\work_loan_open\htdocs\node_modules\antd\lib\drawer\style\drawer.less (line 189, column 6)

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome |

**Comment by Limbo2333** [comment]
我也出现了这个问题，把less，和less-loader升级到最新就可以了

**Comment by afc163** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/507615/78983411-be664a00-7b56-11ea-97d2-f17a43766061.png">

#22800

**Comment by sujiangyin** [comment]
我升级了这两个npm包，再运行还是一样哦------------------ 原始邮件 ------------------
发件人: "Limbo2333"<notifications@github.com>
发送时间: 2020年4月10日(星期五) 晚上6:09
收件人: "ant-design/ant-design"<ant-design@noreply.github.com>;
抄送: "suosuo"<1605324281@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [ant-design/ant-design] 升级antd4后运行构建命令报错less问题 (#23125)




 
我也出现了这个问题，把less，和less-loader升级到最新就可以了
 
&mdash;

**Comment by qiwang97** [comment]
@afc163 [parcel-antd](https://github.com/ant-design/parcel-antd/blob/master/package.json) uses antd v3 and less v2.7. When I upgrade antd v4,I get the warning `Cannot read property 'numerator' of undefined`. When I upgrade less ,i get `Inline JavaScript is not enabled. Is it set in your options?`.

Anything to do with parcel + antd v4 + less values?

**Comment by woowalker** [comment]
解决了吗？我这边也出现了

**Comment by sujiangyin** [comment]
this is the  answer：
detele old packages then install，use the cmd with 管理员权限
`rm -rf ./node_modules && npm install`

**Comment by sujiangyin** [comment]
要删除旧的npm包，再用cmd以管理员权限重新安装一次。rm -rf ./node_modules &amp;&amp; npm install



---原始邮件---
发件人: "woowalker"<notifications@github.com&gt;
发送时间: 2020年7月13日(周一) 下午2:15
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"suosuo"<1605324281@qq.com&gt;;
主题: Re: [ant-design/ant-design] 升级antd4后运行构建命令报错less问题 (#23125)




 
解决了吗？我这边也出现了
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
 
---原始邮件---
发件人: "woowalker"<notifications@github.com&gt;
发送时间: 2020年7月13日(周一) 下午2:15
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"suosuo"<1605324281@qq.com&gt;;
主题: Re: [ant-design/ant-design] 升级antd4后运行构建命令报错less问题 (#23125)




 
解决了吗？我这边也出现了

**Comment by Chengma999** [comment]
I also have the same problem. I have less and less-loader at  /node_modules. But they are not in my package.json. How can I upgrade less and less-loader?

less less-loader 存在node_modules 目录下，但他们不在我的package.json文件里， 该如何更新他们至最新版本。？

**Comment by sujiangyin** [comment]
可以重新安装一下



---原始邮件---
发件人: "Chengma999"<notifications@github.com&gt;
发送时间: 2020年7月20日(周一) 晚上7:51
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"suosuo"<1605324281@qq.com&gt;;
主题: Re: [ant-design/ant-design] 升级antd4后运行构建命令报错less问题 (#23125)




 
I also have the same problem. I have less and less-loader at  /node_modules. But they are not in my package.json. How can I upgrade less and less-loader?
 
less less-loader 存在node_modules 目录下，但他们不在我的package.json文件里， 该如何更新他们至最新版本。？

**Comment by zjscy666** [comment]
![image](https://user-images.githubusercontent.com/22449281/89514672-bcf91580-d808-11ea-9e6e-6f091e3b66e5.png)
我用了dva 按照上述方式，还是报错，大佬们用的less和less-loader版本可以提供下不

**Comment by zxkws** [comment]
> Hello @sujiangyin. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @sujiangyin, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

大佬,可以留一下你的邮箱吗,我也遇到了这个问题,没有好的解决办法.

**Comment by sujiangyin** [comment]
要删除旧的npm包，再用cmd以管理员权限重新安装一次。rm -rf ./node_modules && npm install

**Comment by Mh2336393** [comment]
> 我升级了这两个npm包，再运行还是一样哦------------------ 原始邮件 ------------------ 发件人: "Limbo2333"<notifications@github.com> 发送时间: 2020年4月10日(星期五) 晚上6:09 收件人: "ant-design/ant-design"<ant-design@noreply.github.com>; 抄送: "suosuo"<1605324281@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [ant-design/ant-design] 升级antd4后运行构建命令报错less问题 (#23125) 我也出现了这个问题，把less，和less-loader升级到最新就可以了 &mdash; You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
我也遇到这样的问题 升级了也不管用

**Comment by yoyo837** [comment]
来个复现repo

**Comment by Mh2336393** [comment]
正在压缩 client 马上

> 来个复现repo

**Comment by Mh2336393** [comment]
> 来个复现repo

**Comment by Mh2336393** [comment]
> 正在压缩 client 马上
> 
> > 来个复现repo

**Comment by yuxuan** [comment]
如果 `padding-right: calc(@drawer-header-close-padding - var(--scroll-bar));`

**Comment by hanzhixing** [comment]
Please fix this!!!

**Comment by yoyo837** [comment]
没有遇到这个问题，请提供复现。

**Comment by well-monkey** [comment]
我直接用的 create-react-app安装的最新版本  然后安装的
"less": "^4.0.0",
"less-loader": "5.0.0",
然后引入antd复现了 这个问题

**Comment by weiyuan0609** [comment]
antd: 4.9.4
webpack: 5.11.0
less-loader: 7.2.0
less: 4.0.0

遇到这个问题
![image](https://user-images.githubusercontent.com/25721693/103123831-9442c100-46c0-11eb-9480-e40a4d79850f.png)

**Comment by yoyo837** [comment]
已发布的版本暂不支持less 4.0

**Comment by whinc** [comment]
我也遇到了同样的问题，我的项目使用的是最新的依赖版本，配置如下
```
    "react-scripts": "4.0.1",
    "customize-cra": "^1.0.0",
    "less": "^4.1.0",
    "less-loader": "^7.2.1",
```

在 less 的配置项中指定 math 为 "always" 即可：
```
  addLessLoader({
    lessOptions: {
      modifyVars: {
        '@primary-color': '#1DA57A',
        '@link-color': '#1DA57A',
      },
      javascriptEnabled: true,
      math: 'always'   // 此处指定为兼容 less-loader 3.x 的默认选项
    },
  }),
```

具体原因是 less-loader 从 3.x 升级到 4.x 后对于数学计算的默认配置发生了变化（详情参考[这里[(http://lesscss.org/usage/#less-options-math)，估计 antd4 还没有升级，暂时先配置到 3.x 的默认配置即可。

![image](https://user-images.githubusercontent.com/5096493/104155931-21a54580-5423-11eb-8933-f8582d37c518.png)

**Comment by afc163** [comment]
antd 最新版本已修复。

**Comment by whinc** [comment]
> antd 最新版本已修复。

棒！我升级下~

**Comment by cyt68** [comment]
> 我也遇到了同样的问题，已解决了。
> 
> 我的项目使用的是最新的依赖版本，配置如下
> 
> ```
>     "react-scripts": "4.0.1",
>     "customize-cra": "^1.0.0",
>     "less": "^4.1.0",
>     "less-loader": "^7.2.1",
> ```
> 
> 在 less 的配置项中指定 math 为 "always" 即可：
> 
> ```
>   addLessLoader({
>     lessOptions: {
>       modifyVars: {
>         '@primary-color': '#1DA57A',
>         '@link-color': '#1DA57A',
>       },
>       javascriptEnabled: true,
>       math: 'always'   // 此处指定为兼容 less-loader 3.x 的默认选项
>     },
>   }),
> ```
> 
> 具体原因是 less-loader 从 3.x 升级到 4.x 后对于数学计算的默认配置发生了变化（详情参考[这里](http://lesscss.org/usage/#less-options-math))，估计 antd4 还没有升级，暂时先配置到 3.x 的默认配置即可。
> 
> ![image](https://user-images.githubusercontent.com/5096493/104155931-21a54580-5423-11eb-8933-f8582d37c518.png)

隔壁antdv来的，大兄弟的方法亲测有效，升级那些根本不得行，可能跟不同环境有关系，但是这种从兼容角度处理问题的一看就是靠谱的。

**Comment by KitaniIslam** [comment]
> 我也遇到了同样的问题，已解决了。
> 
> 我的项目使用的是最新的依赖版本，配置如下
> 
> ```
>     "react-scripts": "4.0.1",
>     "customize-cra": "^1.0.0",
>     "less": "^4.1.0",
>     "less-loader": "^7.2.1",
> ```
> 
> 在 less 的配置项中指定 math 为 "always" 即可：
> 
> ```
>   addLessLoader({
>     lessOptions: {
>       modifyVars: {
>         '@primary-color': '#1DA57A',
>         '@link-color': '#1DA57A',
>       },
>       javascriptEnabled: true,
>       math: 'always'   // 此处指定为兼容 less-loader 3.x 的默认选项
>     },
>   }),
> ```
> 
> 具体原因是 less-loader 从 3.x 升级到 4.x 后对于数学计算的默认配置发生了变化（详情参考[这里](http://lesscss.org/usage/#less-options-math))，估计 antd4 还没有升级，暂时先配置到 3.x 的默认配置即可。
> 
> ![image](https://user-images.githubusercontent.com/5096493/104155931-21a54580-5423-11eb-8933-f8582d37c518.png)

thank you !! its all  about the ( math: 'always' ) in my case !
