### ISSUE TITLE
Menu组件在 dark 模式下使用二级菜单 SubMenu，SubMenu 的 chirdren 字体颜色是白色，导致二级菜单栏都是白的。

### ISSUE THREAD

**Issue by lz-lee** [ant-design/ant-design#23129]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhuti-ant-design-demo-2fhy1)

### Steps to reproduce
hover 一级菜单展示二级菜单

### What is expected?
二级菜单字体颜色适配 dark 模式

### What is actually happening?
二级菜单字体颜色未适配 dark 模式

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | macOS 10.13.4 |
| Browser | 80.0.3987.163 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/22981 and [4.1.2](https://github.com/ant-design/ant-design/releases/tag/4.1.2)
