### ISSUE TITLE
Colorful Tooltip

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#23127]
<img width="263" alt="image" src="https://user-images.githubusercontent.com/507615/78976196-44c75f80-7b48-11ea-86a5-47d6b03ad76d.png">

```jsx
<Tooltip color="magenta" />
```

https://ant.design/components/tag/#components-tag-demo-colorful

**Comment by AshoneA** [comment]
Cool~

**Comment by AshoneA** [comment]
我来做下，不过应该也要支持配置文字颜色吧？否则白色背景的话就看不到字了。

**Comment by afc163** [comment]
直接按 Tag 预设颜色的 API 来操作就行了。

**Comment by ztplz** [comment]
Sounds good to me.
