### ISSUE TITLE
Menu dark background 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#23124]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed](https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/29775873/78972131-9fa88900-7b3f-11ea-8ac1-c5db6c6a2372.png)

### What is expected?
背景颜色 为 黑色
### What is actually happening?
背景颜色 白色，与字体颜色重合

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
#22981
