### ISSUE TITLE
Menu如何设置菜单的inlineIndent（也就是左侧边距）

### ISSUE THREAD

**Issue by niss2000** [ant-design/ant-design#2312]
Menu菜单（inline模式）的左侧边距被固定为24px,48px,72px...(按层级加倍，看源码是由inlineIndent设定的)，现在想改成15px，30px, 45px...这样子的，请问有没有什么好办法？

- antd 版本:1.6.3

**Comment by afc163** [comment]
undocumented prop `inlineIndent`：https://github.com/react-component/menu/blob/66b2e8073d30aab712cd434274e44d3bccf3d860/src/MenuMixin.js#L77
