### ISSUE TITLE
SizeChanger of Pagination does not work when pageSize is set

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#23121]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mhh8k?file=/index.js)

### Steps to reproduce
1. Set pageSize.
2. Set total to reveal sizeChanger.
3. Cannot change page size with sizeChanger.

### What is expected?
Can change page size with the sizeChanger OR simply not reveal the sizeChanger when pageSize is set.

### What is actually happening?
Cannot change page size with SizeChanger when pageSize is set.

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12.0 |
| System | win10 |
| Browser | Google Chrome  version79.0.3945.88 |

**Comment by afc163** [comment]
https://codesandbox.io/s/zongshu-ant-design-demo-dbkn3?file=/index.js

You forgot `onShowSizeChange`.
