### ISSUE TITLE
每次form.resetFields会导致组件重构触发componentDidMount

### ISSUE THREAD

**Issue by razr001** [ant-design/ant-design#23137]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-jj409)

### Steps to reproduce
新建一个form，插入一个自定义表单组件，输入表单值，调用form.resetFields

### What is expected?
不要触发componentDidMount

### What is actually happening?
每次resetFields都会触发componentDidMount

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.8 |
| System | windows |
| Browser | chrome 80 |

**Comment by zombieJ** [comment]
`resetFields` 会重置整个组件，这个是预期行为。我加个 FAQ 说明一下。

**Comment by razr001** [comment]
> `resetFields` 会重置整个组件，这个是预期行为。我加个FAQ说明一下。

这不合理啊，如果我的组件数据从后端取的比如一些下拉的字典，每次reset都要调接口，严重影响体现

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/23138/files#diff-b440ab587c7d2033e16fdb0c3539a67fR318  这个也是 `resetFields` 要处理的副作用之一。数据请求应该和字段组件解耦。
