### ISSUE TITLE
form rule for check macthing in two field  

### ISSUE THREAD

**Issue by nejos97** [ant-design/ant-design#23136]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
it's impossible now for me to check if two field have the same value. for example when user want to reset his password

### What does the proposed API look like?
i want to propos the new built in rule that allow developer to check if two field in form have the same value

**Comment by zombieJ** [comment]
ref the Confirm Password sample:
https://ant.design/components/form/#components-form-demo-register
