### ISSUE TITLE
Form的默认文案是英文?

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design#23148]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
默认文案是英文?
config中配置了中文无效
```
locale: {
    default: 'zh-CN',
    antd: true,
    baseNavigator: true,
  },
```

在basiclayout中使用也无效
```
import zhCN from 'antd/es/locale/zh_CN';
 <ConfigProvider locale={zhCN}>
        {children}
      </ConfigProvider>
```

### What is expected?
可有内置中文文案?

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome |

**Comment by zombieJ** [comment]
嗯，是可以优化一下。

**Comment by lemovel** [comment]
要下载最新版本？还是直接重新下载依赖就可以了？

**Comment by yoyo837** [comment]
还没合并PR

**Comment by lemovel** [comment]
请问什么时候会合并呢？

**Comment by yoyo837** [comment]
Review 后。

> 什么时候Review呢？

这个没答案，每个人有自己的时间分配！

**Comment by hengkx** [comment]
#23369
