### ISSUE TITLE
select组件为输入搜索组件时没有限制输入长度的API

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#23143]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以限制输入的文字长度

### What does the proposed API look like?
提供这样的API或者属性

**Comment by zombieJ** [comment]
https://codesandbox.io/s/daisousuokuang-ant-design-demo-z0x5o?file=/index.js

**Comment by aw6658913** [comment]
我的是3.0版本的，不是4.0的，我试了下你的demo，在3.0版本是控制不了的

**Comment by senlinkey** [comment]
你可以通过 ref 找到 input, 修改 input的 maxLength

**Comment by sautePhoProgrammer** [comment]
https://github.com/ant-design/ant-design/issues/27954

**Comment by Lynne42** [comment]
> https://codesandbox.io/s/daisousuokuang-ant-design-demo-z0x5o?file=/index.js

使用这个中文输入法就失效了
