### ISSUE TITLE
Tree组件点击节点获取Key问题.

### ISSUE THREAD

**Issue by flicker85** [ant-design/ant-design#2314]
当我点击Tree中的某个节点，我想要获取到这个节点的key，通过这个key做其它处理，

使用API中的onSelect函数，只能在选中时获取到该节点的key，
当我再次点击该节点，该节点变为未选中状态，此时无法公国onSelect函数获得节点的key，

请问有什么办法能在我每次点击节点时都能获得该节点绑定的key值么？

**Comment by ddcat1115** [comment]
看下API, `onSelect` 参数有两个，第二个 object.node 下包含节点相关所有信息

**Comment by flicker85** [comment]
onSelect	点击树节点触发	
function(selectedKeys, e:{selected: bool, selectedNodes, node, event})

e.node里确实有一堆信息，可是没找到当前所点击的Tree节点所对应的key的值 @@

**Comment by ddcat1115** [comment]
node.props.eventKey 或者node.props.pos

**Comment by flicker85** [comment]
ok, 可以啦, 3q~

**Comment by afc163** [comment]
@flicker85 没问题请关闭 issue。
