### ISSUE TITLE
关于table中数组数据变化渲染的问题

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design#23147]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
升级到最新版本后发现table中的数组数据 进行push操作后 不会触发重新渲染 升级之前是没有问题的

### What is expected?
- 

### What is actually happening?
-

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21573#issuecomment-594310546

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21893#issuecomment-595110678

**Comment by dahaideyu** [comment]
我实现一个树状结构的table 。带checkbox，选中之后子元素值选中却没有显示选中状态。
