### ISSUE TITLE
Form 的 setFieldsValue 和 resetFields 为什么不触发 Form 的 onValuesChange

### ISSUE THREAD

**Issue by C-zhui** [ant-design/ant-design#23156]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这是表单联动的常见需求，不然每次 resetFields 之后都要 setTimeout 手动调用 onValuesChange callback

### What does the proposed API look like?
setFieldsValue 、resetFields 能 触发 Form 的onValuesChange

### What is actually happening?
| Environment | Info|
| -- | --|
| antd | 4.1.2|
| React | 16.13.1|
| System | macos | 
| Browser | chrome |

**Comment by zombieJ** [comment]
API 设计设置值不应该触发事件，这样容易让用户出现死循环。例如 `onValuesChange` 如果调用了 `setFields`。开发者又会需要额外参数来判断代码是来自用户操作还是自己的 `setFields` 调用来防止死循环。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19449#issuecomment-546814164

**Comment by ETRick** [comment]
我也遇到了这个问题，两个 Form 联动，同一个FormItem 有多种修改方式，被卡了一会儿，看了一下源码。如果手动修改 form 触发 form 的 onValuesChange，有两种方法：

1. 通过模拟输入组件的输入事件来触发：拿到 FormItem 包裹的输入组件的 ref， 调用 ref.current.handleChange 来模拟输入, 如： `inputRef.current.handleChange({ target: { value: exampleValue } })`

2. 拿到 rcForm 的 dispatch 方法，通过发送 updateValue 的消息来触发 form 的更新 ：`const formDispatch = (form as any).getInternalHooks('RC_FORM_INTERNAL_HOOKS').dispatch；formDispatch.dispatch({ type: 'updateValue', namePath: examplePath, value: exampleValue })`

第二种方式比较通用。由于用了比较 hack 的方式，建议封装一个 hooks 来做这件事情。

**Comment by wlx0077** [comment]
典型的因噎废食，基于数据驱动视图的模型，其本身就会存在更新数据时产生视图循环更新的风险，这是固有的现象。如果出现死循环问题，更多的是个人使用的问题，解决方案可以提供类似react中shouldUpdate或者类似useEffect deps参数浅层对比的方法，要么提示操作不当自己找方式解决，而不是取消原有的数据更新。setFieldsValue是控件联动的主要方法，如果没法通过统一入口onValuesChange去更新外部state，那么就存在外部state与form内部维护的state不一致的问题，意味着在setFieldsValue时需要独立处理外部state。setFieldsValue其API名称的意义就是去修改数据的，既然数据产生了变化，又为何不触发onValuesChange？

**Comment by youngluo** [comment]
是否考虑提供一个实例方法，手动触发 onValuesChange
