### ISSUE TITLE
【BUG】4.1.2版本使用主题启动错误：Variable @input-height-base is undefined

### ISSUE THREAD

**Issue by hanguihe** [ant-design/ant-design#23154]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/hanguihe/antd-4.1.2](https://github.com/hanguihe/antd-4.1.2)

### Steps to reproduce
新建一个Umi3项目，在项目中显式安装 antd 依赖，配置紧凑主题

### What is expected?
正常启动

### What is actually happening?
无法正常启动

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.12.0 |
| System | Mac OS 10.15.4 |
| Browser | 80.0.3987.163 |

---
使用create-react-app，用react-app-rewired配置主题也是同样问题。

**Comment by hanguihe** [comment]
![](https://user-images.githubusercontent.com/29910482/79060103-c687cc00-7cb3-11ea-9432-04a661c644d6.png)

**Comment by AshoneA** [comment]
ref: https://github.com/umijs/plugins/pull/153

**Comment by hanguihe** [comment]
> 参考：[umijs / plugins＃153](https://github.com/umijs/plugins/pull/153)


感觉问题应该不是umi那边，用create-react-app配置主题也是同样的报错
<img width="928" alt="截屏2020-04-12 下午2 00 36" src="https://user-images.githubusercontent.com/29910482/79061817-5cc4ed80-7cc6-11ea-9066-b44a3896b7ac.png">

<img width="438" alt="截屏2020-04-12 下午2 01 27" src="https://user-images.githubusercontent.com/29910482/79061789-1e2f3300-7cc6-11ea-9889-bfc297140c2b.png">

**Comment by AshoneA** [comment]
@hanguihe 
你试试这样可不可行
```js
const defaultTheme = require('antd/dist/default-theme');
// ...
     options: {
       modifyVars: {
          'hack': `true;@import "${require.resolve('antd/lib/style/color/colorPalette.less')}";`,
          ...defaultTheme,
          ...compactTheme,
       },
       javascriptEnabled: true,
     },

```

**Comment by hanguihe** [comment]
@AshoneA 你这样写是可以的！周末还要帮忙解答问题，真是太感谢大佬啦☺️
