### ISSUE TITLE
关于复杂表单得布局困难

### ISSUE THREAD

**Issue by pkaq** [ant-design/ant-design#23164]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
![MBWZNS}{6K310(4GYLKG7GA](https://user-images.githubusercontent.com/4537450/79064562-7f620100-7cdc-11ea-97a7-13a0c8fe007a.png)
如图，目前实现图中得复杂表单布局感觉非常困难
假如采用<row> <col>来实现得话
那么分割方式是
12 12
24 
8 8 8

那么问题来了， 由于form得labelcol和wrapcol是以所在col得宽度来计算得，就会导致三行计算出来的 label和wrap的宽度不一样 从而导致无法精准的对齐, 这种需求在大众业务系统中应该还是很普遍的 不知道有没有什么好的解决方案 

### What does the proposed API look like?
类似于extjs中得column布局模式 或者 可以支持设置 labelwidth 和 wrapwith?

**Comment by zombieJ** [comment]
Gird 布局支持 `flex` 属性，可以直接定义宽度：https://codesandbox.io/s/jibenshiyong-ant-design-demo-2t7i9?file=/index.js
