### ISSUE TITLE
Got compile failed error when importing a .less file from a .tsx file with babel-plugin-import,react-app-rewired and customize-cra

### ISSUE THREAD

**Issue by iamgian-web** [ant-design/ant-design#23163]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/github/iamgian-web/customize-antd-theme)

[Reproduce repository](https://github.com/iamgian-web/customize-antd-theme)
> the master branch got compiled error and the dev branch works ok,the only difference between them is src/App.less(.css)

### Steps to reproduce
1. create a project with typescript enabled by `npx create-react-app customize-antd-theme --template typescript`
2. npm i babel-plugin-import  react-app-wired customize-cra  less  less-loader
3. add a config-overrides.js in project root dir, and add some code ` 
const { override, fixBabelImports, addLessLoader } = require("customize-cra");

const darkThemeVars = require("antd/dist/dark-theme");

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
    style: true,
  }),
  addLessLoader({
    modifyVars: {
      hack: `true; @import "${require.resolve(
        "antd/lib/style/color/colorPalette.less"
      )}";`,
      ...darkThemeVars,
      "primary-color": "#00f",
      localIdentName: "[local]--[hash:base64:5]",
    },
    javascriptEnabled: true,
  })
);
`
4. change src/App.css to src/App.less ,then update import statement in src/App.tsx  to `import './App.less';`
5.yarn run start

### What is expected?
Dark theme applied and primary-color changed

### What is actually happening?
Failed to compile.

```
@hack: true; @import "\path\to\my\project\antd-theme-customation\node_modules\antd\lib\style\color\colorPalette.less";@theme: dark;@blue-1: mix(color(~`colorPalette('@{blue-base}', 8) `), @component-background, 15%);@blue-2: mix(color(~`colorPalette('@{blue-base}', 7) `), etc...
Variable @blue-base is undefined
      in \path\to\my\project\antd-theme-customation\src\App.less (line 5, column 153)
```

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | win10x64 |
| Browser | chrome81 |

**Comment by AshoneA** [comment]
I'm sorry for that, how about add `defaultTheme` and try it again?
```js
const defaultTheme = require('antd/dist/default-theme');
// ...
     options: {
       modifyVars: {
          'hack': `true;@import "${require.resolve('antd/lib/style/color/colorPalette.less')}";`,
          ...defaultTheme,
          ...darkThemeVars,
       },
       javascriptEnabled: true,
     },
```

**Comment by iamgian-web** [comment]
Ok,thanks 💯 ,problem solved.

**Comment by AshoneA** [comment]
@iamgian-web It's my pleasure.
