### ISSUE TITLE
Locally developed, you don't see the options with the filtering capabilities of the table, but once you've packaged it, it's fine

### ISSUE THREAD

**Issue by jokingzhang** [ant-design/ant-design#23166]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://jokingzhang.github.io/antd-theme-demo/#/comp/table](https://jokingzhang.github.io/antd-theme-demo/#/comp/table)

### Steps to reproduce
- 1, go to https://github.com/jokingzhang/antd-theme-demo
- 2, npm install & npm start
- 3. Open http://localhost:3067/#/comp/table and click the filter function of the table

### What is expected?
You can see the filtering options in Table normally

![image](https://user-images.githubusercontent.com/10766546/79068531-3e78e500-7cfa-11ea-9b97-6ae915dedbc5.png)

### What is actually happening?
No filtering options

![image](https://user-images.githubusercontent.com/10766546/79068553-61a39480-7cfa-11ea-8d0f-708bcfeee7f2.png)

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.13.1 |
| System | mac OS 10.14.6 |
| Browser | Chrom 版本 81.0.4044.92（正式版本） |

---
You don't see the options for local development, but when you package it, it's fine

**Comment by zombieJ** [comment]
Pls provide a mini reproduce instead.

**Comment by jokingzhang** [comment]
https://github.com/jokingzhang/antd-theme-demo

**Comment by jokingzhang** [comment]
antd 3.26.11 is fine.

**Comment by afc163** [comment]
我们的一处写法没有兼容 less 2，你可以升级到 less 3：https://github.com/jokingzhang/antd-theme-demo/pull/1

我再修复一下 3.x。

**Comment by jokingzhang** [comment]
明白了，我回头试一下，谢谢大佬~
