### ISSUE TITLE
antd 有没有兼容ie8以下的插件

### ISSUE THREAD

**Issue by dreamDX** [ant-design/ant-design#2317]
antd 有没有兼容ie8以下的插件，貌似运行到ie8就报错

**Comment by ddcat1115** [comment]
目前还是提供有限度的支持的。http://ant.design/docs/react/getting-started#%E5%85%BC%E5%AE%B9%E6%80%A7  （需用现代浏览器打开）

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init#dont-work-in-ie8-
