### ISSUE TITLE
Enable master branch protect ?

### ISSUE THREAD

**Issue by AshoneA** [ant-design/ant-design#23179]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Yesterday, I check out master branch then rebase upstream/master, I forget to check out a new branch so push a commit to ant-design master directly. It's my mistake.
How about enable master branch protect, not allow anyone to push master branch only pr.
@afc163 @zombieJ

### What does the proposed API look like?
Enable master branch protect ?

**Comment by afc163** [comment]
<img width="750" alt="image" src="https://user-images.githubusercontent.com/507615/79090106-28f7cf80-7d7b-11ea-9fe0-f11cfc52a6b8.png">

done
