### ISSUE TITLE
Table组件固定列在Safari浏览器存在兼容问题

### ISSUE THREAD

**Issue by sharesin** [ant-design/ant-design#23177]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
打开即可重现

### What is expected?
尽快修复，3.xx版本无此问题

### What is actually happening?
显示问题

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | React 16.12.0 以上 |
| System | mac |
| Browser | Safari |

**Comment by afc163** [comment]
Safari 版本是？

**Comment by sharesin** [comment]
版本 12.1.2 (14607.3.9)

**Comment by afc163** [comment]
看看 https://preview-23161-ant-design.surge.sh/components/table/ 这里是不是好的。

**Comment by yoyo837** [comment]
可能需要重装一下

**Comment by sharesin** [comment]
> 看看 https://preview-23161-ant-design.surge.sh/components/table/ 这里是不是好的。

这个显示也是有问题

**Comment by sharesin** [comment]
<img width="1665" alt="WX20200413-110905@2x" src="https://user-images.githubusercontent.com/5266021/79089053-3ca13700-7d77-11ea-9ba4-32c1909ae258.png">

**Comment by sharesin** [comment]
> 可能需要重装一下

是官网的文档需要重新发布吗？

**Comment by imhxc** [comment]
这个问题应该是没有彻底修复，class 样式被 style 样式覆盖了

**Comment by sharesin** [comment]
> 这个问题应该是没有彻底修复，class 样式被 style 样式覆盖了

嗯，太希望在后续版本修复完善，谢谢！

**Comment by imhxc** [comment]
@sharesin 
你可以采用下面的方法来临时解决这个问题：
 ````
.ant-table-cell-fix-left,
 ant-table-cell-fix-right: {
  position: position: -webkit-sticky !important;
  position: sticky !important;
} 
````

**Comment by sharesin** [comment]
> @sharesin
> 你可以采用下面的方法来临时解决这个问题：
> 
> ```
> .ant-table-cell-fix-left,
> ant-table-cell-fix-right: {
>  position: position: -webkit-sticky !important;
>  position: sticky !important;
> } 
> ```
谢谢

**Comment by yoyo837** [comment]
fixed的列都会加style的sticky样式再加个-webkit-sticky应该就可以了

**Comment by sharesin** [comment]
> fixed的列都会加style的sticky样式再加个-webkit-sticky应该就可以了

解决了

**Comment by yoyo837** [comment]
我去给rc-table加个PR

**Comment by sharesin** [comment]
> ~我去给rc-table加个PR~
> 
> style 咋写俩position，写不了吧 😂

不同的内核分别渲染各自的😂

**Comment by imhxc** [comment]
> ~我去给rc-table加个PR~
> 
> style 咋写俩position，写不了吧 😂

所以说很蛋疼，要么用 JS 来判断是否加前缀，要么就写在 class 中
