### ISSUE TITLE
Typography.Text 的省略号 连同 复制按钮也一同省略了

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#23174]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望 省略的时候 复制按钮还在

### What does the proposed API look like?
无

**Comment by linxianxi** [comment]
Typography.Paragraph 可以设置后缀 但是只能是string 不能是图标

**Comment by zkwolf** [comment]
给个复现？
