### ISSUE TITLE
v4.0 的 setFieldsValue 没有 callbackFn 了，请问如何实现这个功能

### ISSUE THREAD

**Issue by asyura** [ant-design/ant-design#23176]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
需要在 setFieldsValue 成功后进行一些操作

### What does the proposed API look like?
setFieldsValue with callback or setFieldsValue return promise

**Comment by k-yle** [comment]
This is a significant issue. In the following code snippet, you would expect `x` to be `1`. However, `form.setFieldsValue` takes time to set the value, yet it doesn't have a callback or return a promise. So `x` is undefined. 

```js
form.setFieldsValue({ a: 1 });
const x = form.getFieldValue("a");
// BUG: x === undefined
```

If you add a setTimeout, it works fine. But we shouldn't have to do this!

```js
form.setFieldsValue({ a: 1 });

setTimeout(() => {
	const x = form.getFieldValue("a");
	// x === 1
}, 100);
```

**Comment by zombieJ** [comment]
Could you help to provide a reproduce about this. Seems recently version of form is a sync already.
