### ISSUE TITLE
table summary position (top / bottom)

### ISSUE THREAD

**Issue by pierre-b** [ant-design/ant-design#23170]
Hello guys,

### What problem does this feature solve?
In data reports we often have a lot of table rows, and the summary won't be visible right away. We need to put the summary line at the top of the table. 

**You can find an example in Google Analytics: the first line is always the totals.**

### What does the proposed API look like?
`<Table summaryPosition="top">...</Table>`

Thank you for considering this feature request!

**Comment by pierre-b** [comment]
Any news regarding this feature please?

**Comment by pierre-b** [comment]
Hi guys, do you have an idea when this feature will be added in the roadmap please?

Here is an example of what it looks like on Google Analytics:
![top-table-summary](https://user-images.githubusercontent.com/1058531/103276839-e557fb00-49c7-11eb-9221-0635a0a5f69e.png)

Thanks for considering this and happy 2021!

**Comment by chillyistkult** [comment]
This issue should not be labeled as inactive. Having summary at the top is the most common thing and a very basic feature in my opinion.

**Comment by afc163** [comment]
Supported in https://github.com/react-component/table/pull/618

**Comment by pierre-b** [comment]
Hi @afc163 sorry but I requested to put the Table Summary a the top. Could you please reopen this feature request?

**Comment by yoyo837** [comment]
> Hi @afc163 sorry but I requested to put the Table Summary a the top. Could you please reopen this feature request?

https://github.com/react-component/table/pull/624

**Comment by pierre-b** [comment]
Thanks @yoyo837 for the link, it would be great to add `<Table.Summary fixed="top">` in the docs. I couldn't guess it.

**Comment by yoyo837** [comment]
It will be.

**Comment by Stacey1018** [comment]
想问问什么时候发布到稳定版本呢

**Comment by balboFK** [comment]
Hello guys! 
When will this be on the main branch? I want to fix my Summary to the top of the table, but now, the only accepted value for "fixed" is a boolean.

Im running on : "antd": "^4.16.13"

Example:

![image](https://user-images.githubusercontent.com/87539237/136435181-b7feb845-2f23-443d-82b9-c72cdd7cb693.png)
