### ISSUE TITLE
TreeSelect 组件  dropdownStyle 配置高度 无法自适应

### ISSUE THREAD

**Issue by doudou003** [ant-design/ant-design#23187]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-bassi-feogj?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/eloquent-bassi-feogj?file=/index.js

### What is expected?
期望：可以根据 dropdownStyle 配置高度 适应

### What is actually happening?
使用 dropdownStyle 属性配置高度后产生大量空白

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | ^16.13.1 |
| System | windows |
| Browser | chrome |

**Comment by imhxc** [comment]
你应该传递 `maxHeight ` 属性，而不是 `height`。

**Comment by afc163** [comment]
用 `listHeight`：https://codesandbox.io/s/cold-frog-r5ccg?file=/index.js

@zombieJ 3.x 里配置弹层高度的方式失效了：https://3x.ant.design/components/tree-select-cn/#components-tree-select-demo-basic 看看要不要加个 FAQ 和升级说明。

**Comment by afc163** [comment]
以及补充 listHeight 的文档说明。
