### ISSUE TITLE
Showing a Tooltip conditionally when the content has ellipsis is not possible

### ISSUE THREAD

**Issue by OscarGimenez** [ant-design/ant-design#23188]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-and-ellipsis-fjbrw?file=/index.js)

### Steps to reproduce
Try to assign a Tooltip to a Paragraph only with ellipsis is true and shown.

So:
If the ellipsis dinamically appears -> Tooltip should be shown.
If the ellipsis doesn't appear -> Tooltip should be hidden.

### What is expected?
Tooltip is shown only when ellipsis appears.

### What is actually happening?
Tooltip is always shown.

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | react |
| System | Windows 10 Pro 18363.720 x64 |
| Browser | Chrome 80.0.3987.163 (64 bits) |

---
I'm not sure if this is a bug, or a new feature...
I'm trying some [workarounds](https://stackoverflow.com/questions/61124992/is-it-possible-to-show-an-ant-design-tooltip-conditionally-only-when-the-content), but I think that this behaviour should be on the API.

**Comment by zombieJ** [comment]
In our design. Should always to show `collapse` if need fully content. But I think we can add `onEllipsis` event to help this.

**Comment by OscarGimenez** [comment]
`collapse` is nice, but it doesn't cover the necessities of the app I'm developing now.

If the Ant Design team could add `onEllipsis ` event, it would be great and it will solve the issue I'm facing.

Thanks!
