### ISSUE TITLE
多个输入框的组合验证

### ISSUE THREAD

**Issue by ChenQiWen** [ant-design/ant-design#2318]
### 本地环境

- antd 版本:1.63
- 操作系统及其版本：win10
- 浏览器及其版本:最新chrome

### 你做了什么？

多个Input 框组合在一起  用 一个FormItem 包裹起来 怎么验证每个input 

### 你期待的结果是：

可以验证每一个input 给出单独的提示

## 实际上的结果：

如果FormItem 里面在嵌套FormItem  会报错

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2131#issuecomment-230231698

**Comment by afc163** [comment]
FormItem 里嵌套应该不会报错的。可见演示：http://ant.design/components/form/#components-form-demo-validate-static

如果有报错，麻烦提供下重现。
