### ISSUE TITLE
4.0版本Form中 setFieldsValue() 后为什么调用 isFieldsTouched() 改为true了？这个问题怎么解决

### ISSUE THREAD

**Issue by liu-jin-cheng** [ant-design/ant-design#23196]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/?repo=ant-design](https://new-issue.ant.design/?repo=ant-design)

### Steps to reproduce
先进行setFieldsValue(),然后进行isFieldsTouched()取值，取到true

### What is expected?
先进行setFieldsValue(),然后进行isFieldsTouched()取值，取到false

### What is actually happening?
先进行setFieldsValue(),然后进行isFieldsTouched()取值，取到true

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | windows |
| Browser | google |

**Comment by liu-jin-cheng** [comment]
> Hello @liu-jin-cheng. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @liu-jin-cheng, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

建好了，类似于这么简单的https://codesandbox.io/s/antd-reproduction-template-5upte?file=/index.js

**Comment by yoyo837** [comment]
setFieldsValue调用也表示用户操作过呀。因为没办法知道你这个API是不是由用户触发的行为调用的。

**Comment by yoyo837** [comment]
比如你把他放到一个按钮的onClick里。

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-log0e?file=/index.js

**Comment by liu-jin-cheng** [comment]
> 比如你把他放到一个按钮的onClick里。

那之前3.0就没有这么奇怪的问题，其实项目中好多这种问题，列入左边树，右边表单用来编辑这个树的信息，我点到树的节点时setFieldsValue（），然后不进行任何操作，切换节点调用isFieldsTouched() 的就变成true了，3.0版本就不是这个样子的

**Comment by liu-jin-cheng** [comment]
> https://codesandbox.io/s/antd-reproduction-template-log0e?file=/index.js

这个我知道，但是我们项目就是先setFieldsValue的，和我们的设计有关系

**Comment by yoyo837** [comment]
“例如左边树”等其他问题你可以提供复现新建issue。

3.x能用的话我暂时不太清楚，先给你开着。

**Comment by hengkx** [comment]
我 暂时也有这样的的需求一个页面上多个tab切换，要判断用户没有操作过 就`setFieldsValue()`

**Comment by zombieJ** [comment]
v4 的 Form 规范了状态管理，代码和用户的设置都认为是 `touched`，如果你不需要 `touched` 可以通过 `setFields` 来只做值设置：
https://codesandbox.io/s/antd-reproduction-template-1w82g?file=/index.js

另外，如果是异步的初始化，推荐通过 `resetFields` 来处理。

**Comment by hushuang-pangpang** [comment]
请问一下这个问题解决了吗，我现在也是遇到了这个问题，需要先请求接口数据，然后setFieldsValue()，但是再进行isFieldsTouched()校验就会返回true，即使我没有手动修改过表单的数据

**Comment by wulisensen** [comment]
请问这个问题 解决了吗，只想知道 用户本身 的操作行为 有没有改过表单？
