### ISSUE TITLE
offset in FormItem's labelCol isn't work if layout is vertical

### ISSUE THREAD

**Issue by kidandcat** [ant-design/ant-design#23193]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-sreh5?file=/index.js)

### Steps to reproduce
Use Form with layout 'vertical' and try to add offset to labels with Form's labelCol

### What is expected?
The label should have the offset applied

### What is actually happening?
The label ignores the offset

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Edge 80.0.361.111 |

**Comment by afc163** [comment]
It is by designed, vertical form means label and field take place the whole line each.

**Comment by kidandcat** [comment]
It may be by design, but then why do you allow to set labelCol offset if it's not gonna work?

**Comment by se7en00** [comment]
+1
当vertical布局时，在labelCol中设置offset无效
