### ISSUE TITLE
changed expandable.childrenColumnName lead to undefined selectedRows

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#23197]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shuxingshujuzhanshi-ant-design-demo-mpzcr)

### Steps to reproduce
1. change data.children to sons 
2. change expandable.childrenColumnName to sons
3. select a data that gets undefined selectedRow

### What is expected?
not undefined

### What is actually happening?
[undefined]

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome 79.0.3945.88 |

**Comment by satanYuTeng** [comment]
childrenColumnName 和 checkStrictly: false 一起用的时候 checkStrictly 失效
用 codeSandBox 里的例子就可以复现

**Comment by zombieJ** [comment]
@satanYuTeng 开个新的 issue 吧~~
