### ISSUE TITLE
Need help with my calculator program.

### ISSUE THREAD

**Issue by crossEvan** [ant-design/ant-design#23208]
I'm a high school teacher for computer programming, and I'm trying to make an assignment for my students to make a calculator. I seem to have a bit of issue with making it myself though, and I was wondering if someone could help me make it.  I just want someone to try to do this code, so I can see your thought process

 because mine is not working at the moment.

My steps are:

1. You are provided with an HTML, and CSS files. Look at these files to understand how
to use them and modify them if needed based on your code. (Note: You can add
different selector (id, class) in HTML ONLY and cannot make any changes to CSS.)
All your work will be done in JS file.

2. Connect files and this is what you should see. You are ready to start.

3. Apply these changes :
a. Change the background colour of operation buttons (*, /, +, -), make each
button a different colour ( your choice).
b. Change the font colour for all number buttons (include decimal “.” button, to
blue.
c. Change the background colour of clear “C” button, to black. Also the font colour
to white.

4. Add three Buttons before “C” (clear) button as follow:
a. MS -- Memory Store
b. MC – Memory Clear
c. MR – Memory Restore
All three buttons must have grey background and white font.
After you apply the changes(with your own colour selection), you should see
something like this:
 

5. Record any clicking of buttons and display its value on the screen.
Suggested steps: (Note: You can come up with your own solution)
a. Create variables that will store targeted DOM elements, input/outputs
b. Add an event listener to retrieve data from all buttons when they are clicked.
The handler, function(event) can be used to display the value of the button
(number or operation) on the screen. You can use event.target.dataset.num
to return the value and it should be stored as a new variable added to screen
value.

6. Perform calculations (*, /, +, -) when clicking on the equal “=” button,
Suggested steps:
a. Add an event listener for the equal button. When you click the button, the
handler function(event) can be used to calculate the expression using
eval(screen.value) method. Assign the answer that you obtain to the screen
value. (Note: eval() is a function/method that evaluates expressions. Like:
eval(“2+7”).)

7. Display a message such as “Please Enter a Value”, when clicking the equal “=” button
and nothing is displayed on the screen.

8. Make the memory functional; storing, clearing and retrieving data.
Suggested steps:
a. Add event listeners for:
i. MS→ Store the data from screen to memory;
ii. MC → clear the data in the memory;
iii. MR → Recall the memory value to screen.

9. Clear data in screen by clicking on “C” button.

10.Text appearing on the calculator screen must be aligned to the right.

11.When the mouse hovers over a button, change the background colour of the button.
(your choice of colour). Ensure the colour changes back when the mouse cursor is
removed.

And here's the the CODE:

My started JavaScript:

```
//3.
//Changing colors of opertion colors 

//Multiply Color
const colorMultiply = document.getElementById('multiply')
colorMultiply.style.backgroundColor = "green"

//Divide Color
const colorDivide = document.getElementById('divide')
colorDivide.style.backgroundColor = "red"

//subtract color
const colorSubtract = document.getElementById('subtract')
colorSubtract.style.backgroundColor="blue"

//add color
const colorAdd = document.getElementById('add')
colorAdd.style.backgroundColor="yellow"


//change font of numbers to blue (I did it like this incase anyone wants to color of a single number)
//Makes it easier
const number1 = document.getElementById('number1')
number1.style.color="blue"
const number2 = document.getElementById('number2')
number2.style.color="blue"
const number3 = document.getElementById('number3')
number3.style.color="blue"
const number4 = document.getElementById('number4')
number4.style.color="blue"
const number5 = document.getElementById('number5')
number5.style.color="blue"
const number6 = document.getElementById('number6')
number6.style.color="blue"
const number7 = document.getElementById('number7')
number7.style.color="blue"
const number8 = document.getElementById('number8')
number8.style.color="blue"
const number9 = document.getElementById('number9')
number9.style.color="blue"
const number0 = document.getElementById('number0')
number0.style.color="blue"
const decimal = document.getElementById('decimal')
decimal.style.color="blue"

//Changing color of the clear button
const clear = document.getElementById('clear')
clear.style.color="white"
clear.style.backgroundColor="black"

///////////////////////////////////////////////////////////////////////////////////////////////////////
// Then we want to insert `memoryStoreButton` before the `clear` button:
var memoryStoreButton = document.createElement("BUTTON");
memoryStoreButton.innerHTML = "MS";
clear.before(memoryStoreButton); //puts button before clear

// Then we want the `memoryClearButton` before `memoryStoreButton`
var memoryClearButton = document.createElement("BUTTON");
memoryClearButton.innerHTML = "MC";
memoryStoreButton.before(memoryClearButton);//puts button before clear

// and finally, the `memoryRestoreButton` before `memoryClearButton`
var memoryRestoreButton = document.createElement("BUTTON");
memoryRestoreButton.innerHTML = "MR";
memoryClearButton.before(memoryRestoreButton);//puts button before clear
```

HTML:
```
<!DOCTYPE html>
<html lang="en">

<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <meta http-equiv="X-UA-Compatible" content="ie=edge">
 
<title> Calculator 8 </title>
 <script src="fp.js" defer></script>
 <link rel="stylesheet" href="fp.css">



</head>

<body>
 <section class="calculator8">
	<h1> Calculator 8 </h1>
  <form>
   <input type="text" name="" id="numberBox" class="screen8">
  </form>
  <div class="buttons8"> 
   <!-- operation buttons -->
   <button id="multiply" type="button" class="btn8 btn-mul" data-num="*">*</button>
   <button id="divide" type="button" class="btn8 btn-div" data-num="/">/</button>
   <button id="subtract" type="button" class="btn8 btn-sub" data-num="-">-</button>
   <button id="add" type="button" class="btn8 btn-add" data-num="+">+</button>
   <!-- number buttons -->
   <button id="decimal" type="button" class="btn8 btn-grey" data-num=".">.</button>
   <button id="number9" type="button" class="btn8 btn-grey" data-num="9">9</button>
   <button id="number8" type="button" class="btn8 btn-grey" data-num="8">8</button>
   <button id="number7" type="button" class="btn8 btn-grey" data-num="7">7</button>
   <button id="number6" type="button" class="btn8 btn-grey" data-num="6">6</button>
   <button id="number5" type="button" class="btn8 btn-grey" data-num="5">5</button>
   <button id="number4" type="button" class="btn8 btn-grey" data-num="4">4</button>
   <button id="number3" type="button" class="btn8 btn-grey" data-num="3">3</button>
   <button id="number2" type="button" class="btn8 btn-grey" data-num="2">2</button>
   <button id="number1" type="button" class="btn8 btn-grey" data-num="1">1</button>
   <button id="number0" type="button" class="btn8 btn-grey" data-num="0">0</button>
   <button id="equals" type="button" class="btn8 btn-grey">=</button>
   <button id="clear" type="button" class="btn8 btn-grey">C</button>


  </div>



 </section>

 
</body>

</html>
```

CSS:
```

*{
 margin: 0;
 padding: 0;
 box-sizing: border-box;
}

body{
 min-height: 100vh;
 display: flex;
 align-items: center;
 justify-content: center;

}

.calculator8{
 flex: 0 0 40%;
}
.screen8{
 width: 100%;
 font-size: 7rem;
 padding: 0.5rem;
 background: rgb(41,41,56);
 color: white;
 border:none;
}

.buttons8{
 display: flex;
 flex-wrap: wrap;
 transition: all 0.5s linear;
}

button{
 flex:0 0 25%;
 border: 1px solid black;
 padding: 0.25rem 0;
 transition: all 2s ease;
}

.btn-grey{
 background: rgb(224,224,224);
}

.btn8{
 font-size: 4rem;
}
```

**Comment by keithort** [comment]
@crossEvan You should post your question on StackOverflow.
