### ISSUE TITLE
Checkbox group support virtualized rendering

### ISSUE THREAD

**Issue by Mohamed-Ghanem** [ant-design/ant-design#23204]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If the list passed to Checkbox.Group as options array or using the children rendering is big it will take huge time to load and will be laggy.

### What does the proposed API look like?
It should implement the virtualized rendering with the same API.

**Comment by afc163** [comment]
You can try https://github.com/react-component/virtual-list/ or https://github.com/bvaughn/react-window
