### ISSUE TITLE
Usage questions of `antd` should be asked in StackOverflow?

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#2320]
`antd` 的 issues 中，有相当一部分是 usage questions。虽然通过文档的迭代和整理 FAQ 可以减少 usage questions，但随着 `antd` 的用户越来越多，usage questions 数量还是在增加中，而这些问题极大的消耗了 maintainers 的精力。

所以希望可以把这些 usage questions 迁移到 StackOverflow 中，让社区更多的人参与到其中，以减少 maintainers 答疑的时间。

提出这个建议，有两个依据：

1. 现在 `antd` 社区中已经出现了不少热心人帮忙回答问题。而个人认为，为了让社区保持这股热情，甚至吸引更多的人加入到其中，应该有一个正反馈机制，让 contributors 可以明确感知自己对社区的贡献。但在 issue 中回答问题，缺乏对这些贡献的记录。

  而 StackOverflow 有完善的激励机制，并会记录答题者的 reputation，所以答题者除了可以在回答问题的过程中加深自己对 `antd` React 的认识（教学相长），也会不断地得到社区的认可。
2. 部份用户，认为自己在使用 `antd`  中遇到的所有问题，都应该由 `antd` 的 maintainers 来解答，但其中有不少都是 React Webpack 之类的问题，在 `antd` 的 issue 中提问，不一定能得到专业的回复。

  如果用户是在 StackOverflow 中提问，贴上包括 antd 在内的标签，如 React Webpack 之类，能吸引熟悉相关的领域的人来回答，反而有更好的效果。

**Comment by RaoHai** [comment]
如果迁到爆栈上，使用中文提问和回答会不会对国外友人造成困扰……

**Comment by benjycui** [comment]
需要做的事有两点：

1. 把 usage questions 都引导到 StackOverflow 上。
1. 在有足够多的人来回答 `antd` 的问题之前，maintainers 还是需要关心 StackOverflow 上面的问题。即使在后面有足够多的 contributors，maintainers 也需要扮演兜底的角色。

**Comment by benjycui** [comment]
> 如果迁到爆栈上，使用中文提问和回答会不会对国外友人造成困扰……

建议使用英文提问，因为这样才能有更多的人来回答问题，答案也会惠及更多的人。但实在英文不行的，用中文也是可以，毕竟现在 `antd` 的社区主要也是中文。

**Comment by afc163** [comment]
中英文是个大问题，StackOverflow 基本上没有中文问题。vuejs 的做法是是自建论坛。

**Comment by ddcat1115** [comment]
有几个顾虑：

1. maintainers 还是要先识别是usage类，还是组件本身的问题，感觉这个才是最花时间的
2. 感觉会在StackOverflow上帮忙回答的人也会在github上回答？

就是比较担心『仅仅是多了一个需要维护的地方』

**Comment by nodeman777** [comment]
需要大家一起来回答，大部分的问题不需要maintainers吧。可能大家都比较忙，只关注自己的问题。搞其他的形式都是没用的。

**Comment by benjycui** [comment]
> 中英文是个大问题

或者同时考虑 SegmentFault 和 StackOverflow？

> maintainers 还是要先识别是usage类，还是组件本身的问题，感觉这个才是最花时间的

一开始要这样，但是当用户已经培养成习惯后，就会主动去论坛提问了。另外现在这么多 usage question，也是因为我们在官网就直接邀请他们来 issue 提问了，可以修改文档，引导到论坛。

![image](https://cloud.githubusercontent.com/assets/3580607/16685728/9fd69bc2-453f-11e6-9298-3120d9bb3082.png)

> 感觉会在StackOverflow上帮忙回答的人也会在github上回答？

有人专门在 SO 和 SF 上面刷问题，但没发现有人专门来 GitHub 刷 issue。

> 需要大家一起来回答，大部分的问题不需要maintainers吧。可能大家都比较忙，只关注自己的问题。搞其他的形式都是没用的。

是的，所以希望 SO 能激励更多的人来提问，类似 zhihu.com 的激励机制。

**Comment by michshat** [comment]
Just came across `antd`and it's by far the best `react` component implementation out there. Would be awesome to reach out to non-Chinese speaking community also. Stackoverflow would be a  great place to start for sure :)

**Comment by benjycui** [comment]
@michshat we are working on documentation translation.

**Comment by michshat** [comment]
@benjycui  that's really awesome - thanks!. I'll continue using `google translate` for now :)

**Comment by benjycui** [comment]
@michshat I am not sure whether you can help us to review our translation now.

**Comment by michshat** [comment]
@benjycui I would be glad to help, let me know where the translations accessible from.

**Comment by icukaegbu** [comment]
Would love to help, using Google Translate like @michshat, but creating them into markdown files complete with the images and source codes. Started last night, hope to do it for all the components. 
<img width="1280" alt="screen shot 2016-07-13 at 9 06 33 am" src="https://cloud.githubusercontent.com/assets/8110590/16796195/3f345b5e-48d9-11e6-8ba2-c2dcdb6a439e.png">
<img width="1280" alt="screen shot 2016-07-13 at 9 06 44 am" src="https://cloud.githubusercontent.com/assets/8110590/16796196/3f346162-48d9-11e6-8b44-6bc31ed2eaa1.png">
<img width="1280" alt="screen shot 2016-07-13 at 9 07 09 am" src="https://cloud.githubusercontent.com/assets/8110590/16796197/3f34da02-48d9-11e6-8054-b707a172af6d.png">


See attached screenshots. Let me know if this can help

**Comment by icukaegbu** [comment]
Each component has a folder and included images

<img width="1003" alt="screen shot 2016-07-13 at 9 05 38 am" src="https://cloud.githubusercontent.com/assets/8110590/16796238/7b720526-48d9-11e6-99e2-203cdfc1ab76.png">

**Comment by benjycui** [comment]
@icukaegbu it's cool thanks, but it's better to put translation in to ant.design, trace: https://github.com/ant-design/ant-design/issues/1471

**Comment by ryannealmes** [comment]
Kudos to you guys, this is an epic repo with lots of amazing components. The datepicker functionality alone is crazy. I am busy checking if we can use it in our production apps. A little worrying about the language barrier, but you guys seem to have a solid plan to help out other language speaking people. Thanks again really awesome of you guys.

**Comment by benjycui** [comment]
Refer https://macacajs.com/macaca/support.html

I will update site this afternoon.
