### ISSUE TITLE
pagination number per page RTL

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#23207]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ssunm)

### Steps to reproduce
click on the dropdown

### What is expected?
page / 10

### What is actually happening?
10 / page

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.0 |
| System | windows 10 |
| Browser | chrome 80 |

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/79143283-8ded0d00-7def-11ea-9f91-cea412e4d815.png)

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/79144949-66e40a80-7df2-11ea-8551-8f69789d715e.png)

**Comment by xrkffgg** [comment]
😂😂 这有点无解啊，有的想要 ltr 有的想要 rtl

**Comment by xrkffgg** [comment]
@yoyo837 你有什么想法吗？

**Comment by xrkffgg** [comment]
我还是改回默认吧，然后把给官网的 dropdown 插样式

**Comment by yoyo837** [comment]
加个pagination 下的select 加个覆盖。

**Comment by xrkffgg** [comment]
我还是改成默认的吧，然后在需要的地方加样式，单在 pagination ，也不知道其他组件有没有地方用到

**Comment by israelKusayev** [comment]
♡
