### ISSUE TITLE
OTP input box

### ISSUE THREAD

**Issue by ng-parth** [ant-design/ant-design#23201]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now a days, many authentication takes places using OTPs either via mobile or email or both.   
An OTP input can have various UIs *simplest* being a *single input box* with required character limit.    
But most common UI is having **#n independent boxes** where user input's the OTP.    
More crucial things here to tackle are the functionalities which are expected. 
Some functionalities are: 
- Cursor should keep moving to next box as user types the OTP
- Cursor should move to previous box when user deletes character/digit from current box. 
- Cursor should move using arrow keys.
- Paste from clipboard should work fine and populate the OTP boxes correctly. 

### What does the proposed API look like?
The above feature can be introduced using the current <Input /> component and some additional wrapper on top of it. 
A sample component would have most APIs from <Input /> component. 
Example: 
```HTML
<OTPInput 
    length={4} 
    masked={false}
    numeric={true} 
    autoValidate={true} 
    onValidate={validateCallback} 
    onChange={changeCallback}  
/>
```
APIs: 
- **length**: *integer*: number of individual boxed needed based on OTP length expected.
- **masked**: *boolean*: do this want to mask the input like passwords are masked with * or discs?
- **numeric**: *boolean*: do this component accepts only numeric input or alphamumeric is also allowed?
- **autoValidate**: *boolean* : do you want to auto-validate the OTP when last digit/character is enter. 
- **onValidate**: *function* : callback function to validate the OTP when last digit/character is enter.
- **onChange**: *function*: standard onChange callback.

**Comment by vunderkind** [comment]
Good feature request, actually.

What happened to this? Feels weird to have to write a custom component for this.

**Comment by mbushpilot2b** [comment]
This would be very helpful.

**Comment by thousifive** [comment]
This is actually a good feature, hope this is will be included in next release

**Comment by dikshan-justin** [comment]
this would be very useful rather than a custom written component

**Comment by LahiruJayasekara** [comment]
This is nice to have a component

**Comment by FurkanSelvi** [comment]
This would be very helpful

**Comment by Ralfarios** [comment]
Since I'm tired of waiting antd to make this component, I made one.
Please check it https://www.npmjs.com/package/antd-input-otp

**Comment by FurkanSelvi** [comment]
> Since I'm tired of waiting antd to make this component, I made one. Please check it https://www.npmjs.com/package/antd-input-otp demo: https://codesandbox.io/s/antd-input-otp-demo-1jmypp

Thank you

**Comment by leshalv** [comment]
+1

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/48076
