### ISSUE TITLE
UploadList组件，当传入的fileList的url为感叹号进行传参时，组件会将url识别为非图片，导致无法正确显示图片

### ISSUE THREAD

**Issue by onjuju** [ant-design/ant-design#23203]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx](https://github.com/ant-design/ant-design/blob/master/components/upload/UploadList.tsx)

### Steps to reproduce
<Upload fileList=[{thumbUrl: "http://xxx/xxx.img!w_200,h_300"}] />

### What is expected?
渲染出对应fileList的预览图

### What is actually happening?
无图片显示，没有渲染img标签，而是thumbnail icon

| Environment | Info |
|---|---|
| antd | 3.24.3 |
| React | 16.11.0 |
| System | Windows10 |
| Browser | Chrome |

---
UploadList.tsx文件的第145行，使用isImageUrl(file)方法时，会判断文件类型。如果传入图片url，并带上!后面的参数，extname方法不会获取到准确的文件后缀，因为在extname方法中只对“？”或者“#”进行了识别，而“！”没有。建议这里可以自定义判断是否为图片的方法。
可能也由于我们用的cdn传参方式较为少见，如果认为没必要麻烦关闭就好，辛苦了！

**Comment by afc163** [comment]
可以看看 https://github.com/ant-design/ant-design/issues/22958

不过我觉得如果是 oss 默认参数，可以来个 PR 改进。

**Comment by yoyo837** [comment]
oss 的连接符不是`@!`吗？

**Comment by onjuju** [comment]
我们不是用阿里云的oss

**Comment by afc163** [comment]
Fixed in #23248
