### ISSUE TITLE
Unexpected Rotate 90 degrees when view a image in Upload component

### ISSUE THREAD

**Issue by Jibacat** [ant-design/ant-design#23200]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#components-upload-demo-picture-card](https://ant.design/components/upload-cn/#components-upload-demo-picture-card)

### Steps to reproduce
Upload this image http://havi-1254389369.picgz.myqcloud.com/havidriverpic/343723d8f763249e9534fa826229d48b.jpeg and then click thie view button.

### What is expected?
Image do not rotate

### What is actually happening?
Image rotate 90 degrees

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.x |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
I don't think it is antd's bug.

**Comment by afc163** [comment]
https://www.google.com/search?newwindow=1&client=firefox-b-d&sxsrf=ALeKk00HUY_1UZ0W7Jl4HPuwEaXvfH--KQ%3A1586777674627&ei=Sk6UXr7jJZWNoATi8YOQCw&q=upload+image+rotate+90+degrees&oq=upload+image+rotate+90+degrees&gs_lcp=CgZwc3ktYWIQAzIECCMQJzoHCCMQsAIQJ0oKCBcSBjEyLTEwN0oICBgSBDEyLTRQ2QVYmAlglAxoAHAAeAGAAY8BiAGvBJIBAzEuNJgBAKABAaoBB2d3cy13aXo&sclient=psy-ab&ved=0ahUKEwi-sIi9p-XoAhWVBogKHeL4ALIQ4dUDCAs&uact=5

**Comment by Jibacat** [comment]
> I don't think it is antd's bug.

https://exif.tuchong.com/view/9086337/
Get `Rotate 90 CW` in IFD0，Thx.
I will be more cautious to publish a issue next time.
--

**Comment by Jibacat** [comment]
I have told to the ios engineer and they will fix it. XD
