### ISSUE TITLE
4.1.3  Form.Item required属性没有校验

### ISSUE THREAD

**Issue by duwei54** [ant-design/ant-design#23216]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/issues23216-r1gez)
### Steps to reproduce
            <Form.Item name="text" label="名称" required>
              <Input />
            </Form.Item>
提交没有触发校验

### What is expected?
表单必填项校验

### What is actually happening?
没有触发校验

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.0 |
| System | win10 64bit |
| Browser | chrome |

**Comment by duwei54** [comment]
[最小化例子](https://codesandbox.io/s/issues23216-r1gez)已补

**Comment by yoyo837** [comment]
[react-component/field-form](https://github.com/react-component/field-form) 没有处理 `required` prop，看是自动转换成`rule`配置传进去还是修改它支持一下。

**Comment by imhxc** [comment]
@yoyo837 
 `required` props 的设计初衷是否只是展示必填样式？
如果是的的话，我觉得没必要修改。

**Comment by yoyo837** [comment]
> @yoyo837
> `required` props 的设计初衷是否只是展示必填样式？
> 如果是的的话，我觉得没必要修改。

其实好多地方我也不太熟悉，代码渗透不足，好尴尬！等team的人来看看吧。

**Comment by yoyo837** [comment]
如果如你所说，那`required `的文档描述就需要修改了。

**Comment by imhxc** [comment]
> 如果如你所说，那`required `的文档描述就需要修改了。

嗯嗯，的确；那就等 team 的人来看吧。

**Comment by aw6658913** [comment]
required 应该只是作为展示必填项用，不作为表单校验，我经常这么用，因为很多地方会用到要显示必填，但是实际不需要通过表单去校验，而是通过别的方式

**Comment by duwei54** [comment]
@aw6658913 那估计的改改文档吧，这么写有点迷:joy:

**Comment by hengkx** [comment]
觉得很奇怪啊 既然不做必填校验为什么要必填的样式

**Comment by zombieJ** [comment]
`required` 只是个样式配置，v4 合并了 `getFieldDecorator`  后的确会有点懵。文档更新一下。

**Comment by imhxc** [comment]
> 觉得很奇怪啊 既然不做必填校验为什么要必填的样式

业务需求是千变万化的，所以总会有看起来不那么合理的地方。

**Comment by aw6658913** [comment]
有些不是通过表单去校验必填的，并不是说不需要必填，只是校验方式不一样，所以我个人认为这个是required只是个样式设置是没错的，需要必填校验应该通过getFieldDecorator去设置规则
