### ISSUE TITLE
Why Notification and Message are not regular (pure/functional) components?

### ISSUE THREAD

**Issue by oleg-brizy** [ant-design/ant-design#23212]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The possibility to write components that display notifications and messages without side effects, and to hide notification/message by not rendering it as component.

### What does the proposed API look like?
`<Notification type="info" />` instead of `notification.info()`

**Comment by oleg-brizy** [comment]
I store notifications in redux then I need to render them.
With current api it's not possible to do it properly

```ts
export const GlobalNotifications: React.FC<IGlobalNotificationsProps> = ({ notifications, onClose }) => {
  notifications.forEach(({ key, type, message }) => {
    const config: ArgsProps = { key, message, placement: "bottomRight", onClose: onClose.bind(null, key) };

    switch (type) {
      case "success":
        notification.success(config);
        break;
      case "info":
        notification.info(config);
        break;
      case "warning":
        notification.warning(config);
        break;
      case "error":
        notification.error(config);
        break;
      default:
        notification.open(config);
    }
  });

  return <></>; // Weird component
};
```

and I get warning in browser console

```
react-dom.development.js:88 Warning: Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate.
```

**Comment by oleg-brizy** [comment]
I store notifications in redux then I need to render them.
With current api it's not possible to do it properly

```ts
export const GlobalNotifications: React.FC<IGlobalNotificationsProps> = ({ notifications, onClose }) => {
  notifications.forEach(({ key, type, message }) => {
    const config: ArgsProps = { key, message, placement: "bottomRight", onClose: onClose.bind(null, key) };

    switch (type) {
      case "success":
        notification.success(config);
        break;
      case "info":
        notification.info(config);
        break;
      case "warning":
        notification.warning(config);
        break;
      case "error":
        notification.error(config);
        break;
      default:
        notification.open(config);
    }
  });

  return <></>; // Weird component
};
```

and I get warning in browser console

```
react-dom.development.js:88 Warning: Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate.
```

----

I would like to render notifications like this

```ts
export const GlobalNotifications: React.FC<IGlobalNotificationsProps> = ({
  notifications, onClose
}) => {
  return <>{notifications.map(({ key, type, message }) => (
    <Notification
      key={key}
      type={type}
      message={message}
      placement="bottomRight"
      onClose={onClose.bind(null, key)}
    />
  ))}</>;
};
```

**Comment by afc163** [comment]
Check https://ant.design/components/notification/#components-notification-demo-hooks
#17343

**Comment by oleg-brizy** [comment]
It doesn't not fix my issue at all:
1. There is no way to close/destroy an opened notification (with `<Notification />` component it would disappear when the component is unmounted).
2. When I try to open a notification with a `key` that was closed before, nothing happens. This is unacceptable because my app has hardcoded notifications keys (one key for ajax errors, another key for form errors, etc.)
3. Notifications are still rendered outside app container, in `<body>`.

I need notifications to be strictly tied to my `notifications` array - if I change the array, the notifications should change.

```ts
export const GlobalNotifications: React.FC<IGlobalNotificationsProps> = ({
  notifications, onClose
}) => {
  const [notificationApi, notificationContext] = notification.useNotification();

  useEffect(() => {
    notifications.forEach(({ key, type, message }) => {
      const config: ArgsProps = {
        key,
        message,
        placement: "bottomRight",
        duration: 10000,
        onClose: onClose.bind(null, key),
      };

      switch (type) {
        case "success":
          notificationApi.success(config);
          break;
        case "info":
          notificationApi.info(config);
          break;
        case "warning":
          notificationApi.warning(config);
          break;
        case "error":
          notificationApi.error(config);
          break;
        default:
          notificationApi.open(config);
      }
    });
  }, [notifications]);

  return <div className="notifications-container">{notificationContext}</div>;
};
```

![StaticShot_14-04-2020_19-25-01](https://user-images.githubusercontent.com/59368968/79249287-b58eb480-7e85-11ea-8012-6b4799b81db5.png)

**Comment by nielsonlien** [comment]
Hi sir, i have a problem when using antd notification, i am getting "reactRender is not a function" error when running this on my micro frontend app, but it works fine on single react app. Do you have any idea what is the problem?

![image](https://user-images.githubusercontent.com/57793426/183306228-18bafc8c-ef3f-4938-844a-7dbcb570306e.png)
