### ISSUE TITLE
https://ant.design/ 地址打开真特么慢

### ISSUE THREAD

**Issue by iwen-pengh** [ant-design/ant-design#23215]
域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，域名打开太慢了，

**Comment by yoyo837** [comment]
https://ant-design.gitee.io/
