### ISSUE TITLE
TreeSelect breaks when enclosed in a Form.Item that has a name attribute

### ISSUE THREAD

**Issue by codemang** [ant-design/ant-design#23213]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tree-select-error-8lic9)

### Steps to reproduce
1. Find the browser preview on the right-hand side.
1. Select a value from the TreeSelect.
1. Close the TreeSelect modal.
1. Click the clear button.
1. **Notice that the TreeSelect value IS NOT cleared.**
1. Now, in `tree_select_form.jsx`, comment out the `Form.Item` name attribute.
1. Repeat steps #2 - #4.
1. **Notice that the TreeSelect value IS cleared.**

### What is expected?
I expect the selected values in the TreeSelect to be cleared.

### What is actually happening?
An empty array is passed as the `value` to the `TreeSelect`, but it still shows options as being selected.

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | OSX 10.15.3 (Catalina) |
| Browser | Chrome, Version 80.0.3987.16 |

**Comment by DongchengWang** [comment]
Quoted from the docs:

After wrapped by `Form.Item` with `name` property, `value`(or other property defined by `valuePropName`) `onChange`(or other property defined by `trigger`) props will be added to form controls, the flow of form data will be handled by Form which will cause:

1. You shouldn't use `onChange` on each form control to **collect data**(use `onValuesChange` of Form), but you can still listen to `onChange`.
2. You cannot set value for each form control via `value` or `defaultValue` prop, you should set default value with `initialValues` of Form. Note that `initialValues` cannot be updated by `setState` dynamiclly, you should use `setFieldsValue` in that situation.
3. You shouldn't call `setState` manually, please use `form.setFieldsValue` to change value programmatically.

See [https://ant.design/components/form/](https://ant.design/components/form/).

**Comment by afc163** [comment]
#22944

**Comment by codemang** [comment]
@DongchengWang thanks for the detailed reply! 

What you're saying makes sense, but I have a further question. In my case, I have multiple form components, each of which lives in their own file. They have their own redux containers that pass the data  directly to them (in the TreeSelect case, it passes the possible options and the select values).

The only reason I'm wrapping these components in a `<Form.Item>` is because I want to utilize the validation warnings. If a user presses submit on the form but some of the inputs are not filled out, I want to show a warning.

Having the `Form` control all the data is problematic for me, since I'd prefer to keep the current architecture where each input is given it's data from it's container. Is there any way to have the best of both worlds? Again, my goal is to have each input component own it's own data, but also have "field required" validation warnings that are triggered when the user presses submit.

**Comment by DongchengWang** [comment]
@codemang 

You could keep the `name` attribute and try `onValuesChange` and `setFieldsValue`.
Check more Form APIs to see if they meet your requirements.

**Comment by codemang** [comment]
@DongchengWang unfortunately that won't work for me. Again, my goal is explicitly not have the parent form control the state, but have individual input components control the state. I ended up removing the name attribute from each `Form.Item`, and manually passing the `validateStatus` and `help` attributes to `FormItem`
