### ISSUE TITLE
React Strict Mode Warning keeps showing up and keeps producing numerous error logs

### ISSUE THREAD

**Issue by ericsonpadol** [ant-design/ant-design#23217]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://notfound.com](http://notfound.com)

### Steps to reproduce
1. import antd web component i.e. Buttons
2.  render to web browser

### What is expected?
remove strict mode warnings and findDOMNode is deprecated in StrictMode. error

### What is actually happening?
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: LocaleReceiver

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Wave which is inside StrictMode.

| Environment | Info |
|---|---|
| antd | undefined |
| React | react 16.13.0 |
| System | MacOS 10.14.6 |
| Browser | Chrome Version 81.0.4044.92 |

**Comment by yoyo837** [comment]
Duplicated of #9870 and #22493
