### ISSUE TITLE
input number RTL

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#23210]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-tgori?file=/index.js)

### Steps to reproduce

first input - type something, see the feedback, it is in the wrong place, outside of the input...

second input - see the length, type something, the length is growing a little

### What is expected?
* consistent length.
* feedback in the right place

### What is actually happening?
* length is changing when typing or just incrementing the number
* feedback is far away from the input

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.0 |
| System | windows 10 |
| Browser | chrome 80 |

**Comment by yoyo837** [comment]
ref: https://github.com/ant-design/ant-design/issues/22420#issuecomment-601490529

**Comment by yoyo837** [comment]
LTR has the same problem.

**Comment by israelKusayev** [comment]
@yoyo837 it is correct for the "feedback in the wrong place, but not for the second problem that length is changing when typing (this happens only in rtl)

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/79410618-85edc280-7fd3-11ea-886b-c577f7820f62.png)

Because of this, if you take it out, you'll see it's normal.

**Comment by xrkffgg** [comment]
You can ues in this way  https://codesandbox.io/s/antd-reproduction-template-drdyx?file=/index.js
