### ISSUE TITLE
timePicker组件选择错乱

### ISSUE THREAD

**Issue by guxinyan** [ant-design/ant-design#23227]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/time-picker-cn/#components-time-picker-demo-hide-column   官方示例用户也能复现](https://ant-design.gitee.io/components/time-picker-cn/#components-time-picker-demo-hide-column   官方示例用户也能复现)

### Steps to reproduce
点时间选择 2：00

### What is expected?
选中2：00

### What is actually happening?
选中3：00

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.8.4 |
| System | Windows 7 |
| Browser | chrome 80.0.3987 |

---
官方demo在用户电脑上表现是，选时间会自动加一个小时。但是在业务场景页面下，选时间会自动加2个小时 or 3个小时

**Comment by yoyo837** [comment]
不能复现，能否录制一个gif？

**Comment by guxinyan** [comment]
> 不能复现，能否录制一个gif？避免理解错误。

https://s17.aconvert.com/convert/p3r68-cdx67/pums8-338h3.gif
