### ISSUE TITLE
在Form中的Upload组件中使用getFieldValue报错

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#23220]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-go60f?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
在Upload中根据form数据渲染报错

### What is expected?
获取formvalue正常显示数据

### What is actually happening?
Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Microsoft Edge  81.0.416.53 |

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-w83z1?file=/form.js

**Comment by Liu-Ya** [comment]
> https://codesandbox.io/s/antd-reproduction-template-w83z1?file=/form.js

我也知道这里用这种方案是可以的，但这里的代码是简化的，在我实际业务中一个Upload有几十行代码，此处要用到三个Upload，如果全照这么写就是二三百行代码了，实在是太麻烦

**Comment by yoyo837** [comment]
你的具体业务不太清楚，但是你的复现所呈现的问题是：Form.Item支持children传入函数，而不是具体的表单项控件，其他的就是自己逻辑相关东西了。

**Comment by Liu-Ya** [comment]
> 你的具体业务不太清楚，但是你的复现所呈现的问题是：Form.Item支持children传入函数，而不是具体的表单项控件，其他的就是自己逻辑相关东西了。

```jsx
({getFieldValue}) => {return <a />}
```
这个必须直接放在Form.Item下，不然都会报错😂

**Comment by yoyo837** [comment]
> > 你的具体业务不太清楚，但是你的复现所呈现的问题是：Form.Item支持children传入函数，而不是具体的表单项控件，其他的就是自己逻辑相关东西了。
> 
> ```js-jsx
> ({getFieldValue}) => {return <a />}
> ```
> 
> 这个必须直接放在Form.Item下，不然都会报错😂

对呀，API设计本身如此，我修改的复现就是纠正你这个问题。

**Comment by yoyo837** [comment]
你可以抽取一个自定义的`Upload` 在这里返回给`Form.Item`。

**Comment by Liu-Ya** [comment]
> 你可以抽取一个自定义的`Upload` 在这里返回给`Form.Item`。

是的  已经在做了   谢谢
