### ISSUE TITLE
更新日志【文档】从 4.1.1后就少了【更新日期】

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#23228]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/changelog-cn](https://ant.design/changelog-cn)

### Steps to reproduce
https://ant.design/changelog-cn

### What is expected?
https://ant.design/changelog-cn

### What is actually happening?
https://ant.design/changelog-cn

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | react |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
My bad.
