### ISSUE TITLE
动态切换时长度不一致的button按钮，会出现动画

### ISSUE THREAD

**Issue by hzyhbk** [ant-design/ant-design#23226]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/anniuleixing-ant-design-demo-lznxl)

### Steps to reproduce
点击 有动画 下的按钮

### What is expected?
按钮切换时无动画

### What is actually happening?
按钮切换时会出现动画

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | macOS Mojave 10.14.6 |
| Browser | Chrome 版本 80.0.3987.163（正式版本） （64 位） |

**Comment by yoyo837** [comment]
App1 中  `添加规则` 按钮与 `取消` 被React识别为更新了。 
https://codesandbox.io/s/anniuleixing-ant-design-demo-ibu4z?file=/App.jsx

给 `添加规则` 添加一个key或者不要让App1 和App2到按钮的Dom结构完全相同也可以。
