### ISSUE TITLE
style/core/base.less 是否需要更新了？

### ISSUE THREAD

**Issue by huangbinjie** [ant-design/ant-design#23232]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less#L231](https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less#L231)

### Steps to reproduce
https://github.com/ant-design/ant-design/blob/master/components/style/core/base.less#L231

### What is expected?
参考最新版本的 [normalize.css](https://github.com/necolas/normalize.css/blob/master/normalize.css#L76) a 标签没有 transition

### What is actually happening?
全局样式给 a 标签加了 `transition`

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8.4 |
| System | macOS High Sierra |
| Browser | Chrome |

---
想知道这是否符合预期。我看每个组件有给 a 加上 `transition` 的习惯，那么全局的是否可以去掉呢？

**Comment by afc163** [comment]
这是 antd 自己提供的全局设置，如果需要去掉，可以全局样式覆盖。
