### ISSUE TITLE
Antd Modal 弹窗关闭以后会自动聚焦到弹窗前最后一次聚焦的Input，希望能够提供一个属性来屏蔽改方法

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#23239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-9eu5f)

### Steps to reproduce
在input输入框随便输入，然后回车，点击弹窗里面的按钮关闭弹窗，可以看到input获取到了焦点

### What is expected?
希望modal能够提供一个属性来屏蔽该方法

### What is actually happening?
在input输入框随便输入，然后回车，点击弹窗里面的按钮关闭弹窗，可以看到input获取到了焦点

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | Win7 64位 |
| Browser | 版本 81.0.4044.69（正式版本）beta （64 位） |

---
我看过源码，是源码的rc-dialog有写this.lastOutSideFocusNode.focus(); 。希望加个属性屏蔽改方法即可，这个目前对我们系统里有写操作造成了一定的影响

**Comment by shaodahong** [comment]
It's resolved by https://github.com/react-component/dialog/pull/169

you can do this

```jsx
<Modal focusTriggerAfterClose={false}>
...
</Modal>
```

**Comment by necessityOVO** [comment]
> It's resolved by [react-component/dialog#169](https://github.com/react-component/dialog/pull/169)
> 
> you can do this
> 
> ```js
> <Modal focusTriggerAfterClose={false}>
> ...
> </Modal>
> ```
focusTriggerAfterClose的antd 4. 才有的，请问用antd 3.的话有什么绕过的方式么？
