### ISSUE TITLE
1.6.4版本似乎会给表单控件添加ant-row样式

### ISSUE THREAD

**Issue by wuzeru** [ant-design/ant-design#2323]
ant-row具备样式，会影响页面原有样式
这样的操作似乎不应该升级小版本

**Comment by afc163** [comment]
如何影响的，能否详细一些。方便我们综合考虑。

https://github.com/ant-design/ant-design/commit/d9b4eb4aa330e5e87501e4a3f1a803af107d6bb7 @benjycui

**Comment by benjycui** [comment]
那个已经重构了 https://github.com/ant-design/ant-design/pull/2313/files

之前加上这个，是因为没有 `.ant-row` 的话，在 `Collapse` 和 `Modal` 内时，表格样式会乱。
