### ISSUE TITLE
`antd/dist/dark-theme` 编译有误？

### ISSUE THREAD

**Issue by zpr1g** [ant-design/ant-design#23237]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link

![Gz4lse.png](https://s1.ax1x.com/2020/04/14/Gz4lse.png)

### Steps to reproduce

在 pro 中使用暗黑主题的方式

```
import darkTheme from 'antd/dist/dark-theme';

theme: {
  ...darkTheme,
  '@primary-color': '#0057a2',
}
```
从 4.0.1 -> 4.1.3 突然暗色主题的功能就挂了，找了半天发现是如上图的编译后的代码有问题。

期间也看了官网对使用暗色主题的说明，结果安装 `@umijs/plugin-antd` 后就报错

```
plugin @umijs/plugin-antd is already registered by /home/my/path/node_modules/_@umijs_plugin-antd@0.5.0@@umijs/plugin-antd/lib/index.js, plugin from /home/my/path/node_modules/@umijs/plugin-antd/lib/index.js register failed.
```

故无法使用 `{ dark: true }` 的功能。

### What is expected?

至少保证 `antd/dist/dark-theme`  这个没问题吧？

### What is actually happening?

```
import darkTheme from 'antd/dist/dark-theme';

theme: {
  ...darkTheme,
  '@primary-color': '#0057a2',
}
```

此前暗色主题的使用方式无效！

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.8.6 |
| System | Deepin 15.11 |
| Browser | Chrome 80.0.3987.132 |

**Comment by zpr1g** [comment]
另外，暂时先这样凑合用吧

```
import defaultTheme  from 'antd/dist/default-theme';
import { darkThemeSingle }  from 'antd/dist/theme';

theme: {
  ...defaultTheme,
  ...darkThemeSingle,
  'primary-color': '#0057a2',,
},
```

**Comment by ycjcl868** [comment]
使用 umi，直接配置 `antd: { dark: true }` 即可 https://umijs.org/zh-CN/plugins/plugin-antd#dark

**Comment by zpr1g** [comment]
@ycjcl868 试过了，安装 `@umijs/plugin-antd` 后就编译报错了，我的 config.ts 文件也没有 `plugins` 字段。

**Comment by zombieJ** [comment]
@zpr1g  给个最小重现吧。 @ycjcl868  帮忙看看。

**Comment by ycjcl868** [comment]
> @ycjcl868 试过了，安装 `@umijs/plugin-antd` 后就编译报错了，上面我也说了。而且我的 config.ts 文件也没有 `plugins` 字段。

给一个最小复现吧，我这能用的

**Comment by AshoneA** [comment]
@zpr1g 
```js
const { getThemeVariables } = require('antd/dist/theme');
// ...
  theme: {
    ...getThemeVariables({ dark: true }),
  },
```
这种方式 OK 的吗？

**Comment by zpr1g** [comment]
OK 的，看了代码也不会覆盖样式的。

**Comment by AshoneA** [comment]
> OK 的，看了代码也不会覆盖样式的。

不过你要是可以的话，还是希望你能提供一份最小复现，我们继续排查下。

**Comment by zpr1g** [comment]
额，有个问题是哪儿能找到 umi 的一个在线可用 demo 。这个用不了 https://codesandbox.io/s/jlp78xo63v?file=/pages/index.js

**Comment by AshoneA** [comment]
可以把最小复现项目传到 github 上或者 @ycjcl868 帮忙看下有其他办法吗？

**Comment by zpr1g** [comment]
https://github.com/zpr1g/umi-demo/tree/master

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/79218481-136dcd00-7e83-11ea-96d6-7f1ee0cdd55c.png)

`@umijs/preset-react` 中包括 `@umijs/plugin-antd`

**Comment by zpr1g** [comment]
@ycjcl868 问题是我把这个删了，再配置 `antd: { dark: true }` 也无效啊？

**Comment by zombieJ** [comment]
应该就是 https://github.com/ant-design/ant-design/pull/23243 的问题了，对吗？@AshoneA

**Comment by AshoneA** [comment]
@zombieJ @zpr1g  我用这个 github 仓库删了`@umijs/plugin-antd`试了是可以的，删除 node_modules ， package-lock 之后重新安装是可以的！

**Comment by zpr1g** [comment]
@AshoneA 你确定？我删除重装两次了，暗色主题都没生效 [・_・?]

**Comment by AshoneA** [comment]
> @AshoneA 你确定？我删除重装两次了，暗色主题都没生效 [・_・?]

啊，暗色主题没生效可能得等下 https://github.com/umijs/plugins/pull/159 或者 https://github.com/ant-design/ant-design/pull/23243 合进去。
不过删除重装之后应该启动的时候没有报错了吧？

**Comment by zpr1g** [comment]
重点不是没报错啊，删了就不报了。暗色主题才是我想要的

**Comment by AshoneA** [comment]
> 重点不是没报错啊，删了就不报了。暗色主题才是我想要的

嗯，先用 `getThemeVariables` 的方式来解决吧！非常不好意思...

**Comment by AshoneA** [comment]
> 看了 #23243 应该就是之前神级手滑导致的？

是的，我该剁手了...

**Comment by zpr1g** [comment]
总结一下，之前我是这样使用暗色主题的：

```
import darkTheme from 'antd/dist/dark-theme';

theme: {
  ...darkTheme,
  '@primary-color': '#0057a2',
}
```

然后从 4.0.1 -> 4.1.3 突然部署后暗色主题没了（本地可能由于缓存的原因导致显示没问题），给我吓呆了 😂 那应该下个版本就能愉快的 `antd: { dark: true }` 使用暗色主题了？

**Comment by afc163** [comment]
我明天再发个 patch。

**Comment by AshoneA** [comment]
> 那应该下个版本就能愉快的 antd: { dark: true } 使用暗色主题了？

总结的很好！我就是幕后黑手，下版本也可以试试紧凑模式😆

**Comment by AshoneA** [comment]
> #23243 合并后，我明天再发个 patch。

辛苦了！

**Comment by zpr1g** [comment]
> 总结的很好！我就是幕后黑手，下版本也可以试试紧凑模式😆

到时候可以试一下，之前也有这种感觉，明明页面挺大的，显示的内容感觉没多少 😂

**Comment by ycjcl868** [comment]
> > 那应该下个版本就能愉快的 antd: { dark: true } 使用暗色主题了？
> 
> 总结的很好！我就是幕后黑手，下版本也可以试试紧凑模式😆

主题可以组合，比如暗色+紧凑：

```js
{
   antd: {
     dark: true,
     compact: true,
   }
}
```

**Comment by zpr1g** [comment]
> 同时开启暗黑和紧凑模式会导致 css 的加载体积增加一倍，这暂时受限于我们目前的主题实现方式，请知晓。

这个光说了一个请知晓，那下一步不该精简一下吗？

**Comment by AshoneA** [comment]
@afc163 以 `modifyVars` 或者 umi 的方式配置应该是不会使体积增加一倍的。

**Comment by afc163** [comment]
@AshoneA 在 PR 里把文档顺手更新了吧。

**Comment by Chenghui-web** [comment]
> 总结一下，之前我是这样使用暗色主题的：
> 
> ```
> import darkTheme from 'antd/dist/dark-theme';
> 
> theme: {
>   ...darkTheme,
>   '@primary-color': '#0057a2',
> }
> ```
> 
> 然后从 4.0.1 -> 4.1.3 突然部署后暗色主题没了（本地可能由于缓存的原因导致显示没问题），给我吓呆了 😂 那应该下个版本就能愉快的 `antd: { dark: true }` 使用暗色主题了？

antd@4.3.4 版本没有找到 antd/dist/dark-theme 这个文件路径要怎么办哦 ~

**Comment by zpr1g** [comment]
怎么可能

![R5(@5CFW@BG 4(JB@}0R2$C](https://user-images.githubusercontent.com/18096089/84991021-88f26400-b178-11ea-8af1-666a628f050e.png)

**Comment by Chenghui-web** [comment]
> 怎么可能
> 
> ![R5(@5CFW@BG 4(JB@}0R2$C](https://user-images.githubusercontent.com/18096089/84991021-88f26400-b178-11ea-8af1-666a628f050e.png)

![image](https://user-images.githubusercontent.com/23331593/84992129-15e9ed00-b17a-11ea-9bb9-fb475ba436ca.png)

**Comment by zpr1g** [comment]
你这依赖不是 antd@^3.24.0 哪儿就 antd@4 了？

**Comment by yoyo837** [comment]
info 命令是查仓库的
