### ISSUE TITLE
Slider component does not accept number[] as value or default value

### ISSUE THREAD

**Issue by Ellinn** [ant-design/ant-design#23244]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider/#API](https://ant.design/components/slider/#API)

### Steps to reproduce
1. Create a slider in a typescript env
2. Pass [1, 2, 3] as value 
3. Typescript won't accept

### What is expected?
Slider should accept number[] instead of [number, number]

### What is actually happening?
Documentation for value prop is confusing saying
```javascript
number|number[]
```

But the actual SliderValue type is 
```javascript
export declare type SliderValue = number | [number, number]
```

That is not the same but working if you disable typescript

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.4 |
| Browser | All  |

**Comment by DongchengWang** [comment]
I believe we should fix the docs.

Slider is designed to accept a number or a `[number, number]` tuple. 
If you pass values like [1, 2, 3] and disable type check, it won't behave as we expect during runtime.

The same works for `defaultValue`, too.

**Comment by Ellinn** [comment]
I can make a PR about that 🙂

**Comment by DongchengWang** [comment]
@Ellinn I have already done it.

**Comment by Ellinn** [comment]
Oh okay ! Thanks to you 🙂
