### ISSUE TITLE
Transfer搜索时可以忽略大小写吗？

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2324]
因为存在英文的情况，希望搜索时能忽略大小写

**Comment by benjycui** [comment]
增加 `filterOption(inputValue, option) => Boolean`

与 Select 的 API 一致。

![image](https://cloud.githubusercontent.com/assets/3580607/17397922/da648230-5a6c-11e6-9222-2bca922f1f76.png)

**Comment by codering** [comment]
今天会发布一个小版本吗？

**Comment by benjycui** [comment]
小手一拌，直接 push 了。。。。麻烦 review 一下哈。。。 @RaoHai @dqaria

**Comment by afc163** [comment]
放到 master 上吧，1.x 不发新功能了。

**Comment by benjycui** [comment]
这个已经有人需要的样子 。。 https://github.com/ant-design/ant-design/issues/2622

**Comment by afc163** [comment]
没关系，1.x 开发该收了。

**Comment by wuhaih** [comment]
什么时候更新？
