### ISSUE TITLE
Select component add possibility to not let the user search even if Select has type multiple

### ISSUE THREAD

**Issue by NitroBAY** [ant-design/ant-design#23247]
- [V] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a Select which show multiple options to the user and the user may select one or more of these options therefore I use mode="multiple" but ant design always allow the user to search among the Options when you have a Select with type="multiple". It is useless to have a search feature in my case (few options) and it ruins the experience on the mobile phone because when you click on select the keyboards pops up and hide half of the UI. And as I have multiple selects it is incredibly tedious and frustrating to use these selects as you constantly have to close your keyboard.

### What does the proposed API look like?
Same API than now, just take into consideration "showSearch" attribute when set to false in mode="multiple". Should be easy to implement.

**Comment by afc163** [comment]
https://codesandbox.io/s/multiple-selection-ant-design-demo-j0jyg

`showSearch={false}` works.

**Comment by NitroBAY** [comment]
Not on version 3 https://codesandbox.io/s/multiple-selection-ant-design-demo-ccq7m?fontsize=14&hidenavigation=1&theme=dark
I'm not sure about your policy on supporting ant design 3 but I hope you still support it because you made the switch from 3 to 4 not long ago and it is not possible to switch for us to update the app to use ant design v4 now because we have other priorities and I guess for so many other people it is the same they won't update their antd version as soon as you release a new breaking update.

**Comment by afc163** [comment]
We may not change it in v3 now.

**Comment by NitroBAY** [comment]
If I make a PR it will be refused ?
You updated ant design during the development of my product I didn't expect the framework of my website to not be supported anymore before I even release my app.
