### ISSUE TITLE
How to set to show only one month in range picker selection antd

### ISSUE THREAD

**Issue by dilshan89** [ant-design/ant-design#23245]
I'm using antd calendar RangePicker for my react app.i want to show only one month of calendar dropdown upon selection, instead of two months default.

```
<div className="DatePickerBar">
   <RangePicker format="YYYY-MM-DD"
     className="DateInput"
     value={[moment(dateRange.from), moment(dateRange.to)]}
     onChange={this.onRangeChange}
     allowClear={false}
    />
</div>
```

codesandbox: [wvt2t.csb.app](url)

**Comment by woohoou** [comment]
If anyone has the same problem, I solve it with this:

  ```
.ant-picker-panels > *:first-child button.ant-picker-header-next-btn {
    visibility: visible !important;
  }

  .ant-picker-panels > *:first-child button.ant-picker-header-super-next-btn {
    visibility: visible !important;
  }

  .ant-picker-panels > *:last-child {
    display: none;
  }

  .ant-picker-panel-container, .ant-picker-footer {
    width: 280px !important;
  }

  .ant-picker-footer-extra > div {
    flex-wrap: wrap !important; 
  }
```

**Comment by imsid1996** [comment]
> If anyone has the same problem, I solve it with this:
> 
> ```
> .ant-picker-panels > *:first-child button.ant-picker-header-next-btn {
>   visibility: visible !important;
> }
> 
> .ant-picker-panels > *:first-child button.ant-picker-header-super-next-btn {
>   visibility: visible !important;
> }
> 
> .ant-picker-panels > *:last-child {
>   display: none;
> }
> 
> .ant-picker-panel-container, .ant-picker-footer {
>   width: 280px !important;
> }
> 
> .ant-picker-footer-extra > div {
>   flex-wrap: wrap !important; 
> }
> ```

@woohoou 

Looks like Mentioned issue for one month calendar is getting solved with this css but its creating one side effect where **showTime** is also get affected and time panel getting hide,
to to solve this issue we can right parent element class i.e. class for parent div which will be range picker(.ant-picker-range-wrapper).
we can find the class through inspect element*

**Comment by samridhi-J** [comment]
using the above solution, on clicking month and year button in the header shows nothing .How to fix that issue?

**Comment by KiraBurova** [comment]
@samridhi-J 
> using the above solution, on clicking month and year button in the header shows nothing .How to fix that issue? @imsid1996 , @woohoou

I think you can fix it by doing

```
.ant-picker-panels > *:nth-child(2) {
      display: none;
    }
```

instead of 

```
.ant-picker-panels > *:last-child {
  display: none;
}
```

**Comment by sazedur-strativ** [comment]
This does not allow me to select a range . Only select a date range as i hide the upcoming month view. How can i resolve this having just one month view and also can select the range?

`
import styled from '@emotion/styled';

export const DateRangeWrapper = styled.div`
  margin-top: -48px;

  .date-range-header {
    padding: 13px 16px;
    border-bottom: 1px solid #eaecf0;
    display: flex;
    gap: 8px;

    h3 {
      margin: 0;
      font-size: 16px;
      font-weight: 600;
      color: #1e1b39;
    }
  }

  .ant-picker-dropdown .ant-picker-panels > div:last-child {
    display: none !important;
  }

  .ant-picker-panels {
    display: flex;
  }

  .ant-picker-input {
    display: none !important;
  }

  .ant-picker-dropdown .ant-picker-panel-container {
    overflow: visible !important;
    width: 480px !important;
    height: 512px !important;
  }

  /* Increase width of the calendar panel */
  .ant-picker-panel {
    width: 100% !important;
  }

  /* Increase width of calendar header and body */
  .ant-picker-date-panel,
  .ant-picker-body {
    width: 100% !important;
  }

  /* Make calendar cells fill the available space */
  .ant-picker-content {
    width: 100% !important;
  }

  .ant-picker-content thead th,
  .ant-picker-content tbody td {
    width: 14.28% !important; /* 100% / 7 days */
  }

  /* Increase height of date cells */
  .ant-picker-cell {
    height: 40px !important;
  }

  .ant-picker-cell-inner {
    height: 40px !important;
    width: 40px !important;
    line-height: 40px !important;
    border-radius: 9999px !important;
  }

  /* Adjust week header height */
  .ant-picker-content thead th {
    height: 40px !important;
  }

  /* Adjust header spacing */
  .ant-picker-header {
    padding: 0 16px !important;
  }

  /* Show all navigation arrows */
  .ant-picker-header-super-prev-btn,
  .ant-picker-header-prev-btn,
  .ant-picker-header-next-btn,
  .ant-picker-header-super-next-btn {
    display: inline-flex !important;
    visibility: visible !important;
  }
`;

`
