### ISSUE TITLE
the Table component set attribute scroll x  error:ResizeObserver loop limit exceeded 

### ISSUE THREAD

**Issue by caowenhai888** [ant-design/ant-design#23246]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-lumiere-ucutv?file=/src/index.js)

### Steps to reproduce
初始化控制台会打印error信息

### What is expected?
window.onerror 不会异常

### What is actually happening?
window.onerror异常  ：ResizeObserver loop limit exceeded 

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.8.6 |
| System | Mac OS X Version: 10.14.4 |
| Browser | Chrome Version: 80.0.3987 |

**Comment by yoyo837** [comment]
怎么操作可以重现？直接打开没错误。

**Comment by zombieJ** [comment]
@yoyo837 ，例子里用的是 log 打印的 error：
<img width="260" alt="截屏2020-04-14 下午7 27 43" src="https://user-images.githubusercontent.com/5378891/79220118-056d7b80-7e86-11ea-9ea8-9f3f5135b661.png">

**Comment by zombieJ** [comment]
这个错误是可以无视的，ResizeObserver 注册的时候也正是组件第一次渲染的时候，它不一定能在同一帧里完成，所以有这个信息。未来 React 上 concurrent 后，就 OK 了。

ref：https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded

**Comment by caowenhai888** [comment]
@zombieJ  我在antd 3.x的版本发现这个问题是不存在的~

**Comment by zombieJ** [comment]
因为 v3 是通过渲染时获取元素对齐，对于动态元素对齐有 bug 同时性能也差一些：https://zhuanlan.zhihu.com/p/102037418

**Comment by caowenhai888** [comment]
@zombieJ 非常感觉，持续关注此问题~

**Comment by LHYSS** [comment]
> 怎么操作可以重现？直接打开没错误。

直接打开当前页没有问题，从其他页跳到该页会打印error信息

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/align/pull/72#event-3660686845

**Comment by EmmaLuo2** [comment]
大家有试着升级react 18吗？我升级后发现还有这个问题

**Comment by GrayYoung** [comment]
> 大家有试着升级react 18吗？我升级后发现还有这个问题

我也是升级到react 18，遇到了这个同样的问题。

**Comment by GrayYoung** [comment]
> 大家有试着升级react 18吗？我升级后发现还有这个问题


> 



> > 大家有试着升级react 18吗？我升级后发现还有这个问题
> 
> 我也是升级到react 18，遇到了这个同样的问题。


https://stackoverflow.com/questions/71668256/deprecation-notice-reactdom-render-is-no-longer-supported-in-react-18

我按照这个把 render 修改后，这个问题消失了。

**Comment by TomLamhku** [comment]
"react": "^17.0.2",
  "antd": "^5.3.2",
 The problem happen again

**Comment by zxq08** [comment]
> "react": "^17.0.2", "antd": "^5.3.2", The problem happen again

"react": "^17",
"antd": "5.12.0", 
The problem still exist

**Comment by mcshaman** [comment]
I encounter this issue with a few components. [The issue seems to be with re-resize-observer.](https://github.com/react-component/resize-observer/issues/236)
