### ISSUE TITLE
AutoComplete 能够可配 Input props 或继承;

### ISSUE THREAD

**Issue by jljsj33** [ant-design/ant-design#23257]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
auto complete 也可以有 input 相关的 api, 如 onPressEnter。

### What does the proposed API look like?
平辅 input 的 api 到 autoComplete 里，或恢复 options 可用 `<Option />`，AutoComplete 的 children 留给自定义 <Input />， 如:
```jsx
<AutoComplete>
  <Input onPressEnter={(e) => {}} />
</AutoComplete>
```

**Comment by afc163** [comment]
https://ant.design/components/auto-complete/#components-auto-complete-demo-custom

这样就可以了，统一用 `options`。

**Comment by jljsj33** [comment]
我要用这个`<Options key={value} value={value}>{value}</Options>`。。改这个量有点大，，做兼容。。。

**Comment by jljsj33** [comment]
以前 dataSource 里是可以用 `<Options key={value} value={value}>{value}</Options>` 这样的，，然后 children 用 input，可以满足需求，，现在不能了。。。如果能把 input 的 api 平辅动 auto-complete 里是最好的。。。

**Comment by afc163** [comment]
`<Options key={value} value={value}>{value}</Options>` 这和个 `options` 有啥区别？

**Comment by jljsj33** [comment]
options 里不支持 react.element ，，，如果复用 slelect 的下拉菜单和自定义 input 就有问题了，，

**Comment by afc163** [comment]
看看你的需求长什么样，截个图啥的。

**Comment by jljsj33** [comment]
我是只个例子，，好了不跟你扯了，，把 onPressEnter 带到 autoComplete 上，，我就没啥事了。。。

**Comment by afc163** [comment]
options 里支持 React Node 的，https://ant.design/components/auto-complete/#components-auto-complete-demo-uncertain-category

**Comment by jljsj33** [comment]
你这是忽悠啊，，我要的是支持数组的 Option，可跟 select 共用或加下 onPressEnter
