### ISSUE TITLE
文档增加编辑按钮

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#2325]
在文档头部：

![image](https://cloud.githubusercontent.com/assets/3580607/16685535/590a557c-453e-11e6-82d7-6f482f531806.png)

和 demo 预览：

![image](https://cloud.githubusercontent.com/assets/3580607/16685541/6545724a-453e-11e6-9a51-8a370874c494.png)

增加编辑按钮如何？点击后直接跳转到 GitHub 对应的页面。

其实就是一个邀请 http://ant.design/docs/spec/invitation

**Comment by afc163** [comment]
可以有。:+1:

**Comment by benjycui** [comment]
Demo 的编辑按钮应该放在介绍文字内，不然用户可能会误认为是 demo 支持在线编辑。

cc @Chinglik

**Comment by afc163** [comment]
:+1:

**Comment by afc163** [comment]
![](https://zos.alipayobjects.com/rmsportal/WFhdWUVYQAIIkRL.png)

有点歪，margin 给的元素有点不对。
