### ISSUE TITLE
Menu,Tabs不兼容React 15.2.0

### ISSUE THREAD

**Issue by niss2000** [ant-design/ant-design#2326]
从React 15.1.0升级到15.2.0，发现使用Menu和Tabs时会出现警告

`react.js:20110 Warning: Unknown props `tag`, `hiddenClassName`, `visible` on <ul> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in ul (created by DOMWrap)
    in DOMWrap (created by Menu)
    in Menu (created by t)
    in t (created by Index)
    in div (created by Index)
    in div (created by Index)
    in div (created by Index)
    in Index`

`react.js:20110 Warning: Unknown props `showProp`, `exclusive`, `component`, `transitionName`, `animation`, `transitionEnter`, `transitionLeave`, `transitionAppear`, `onEnd`, `onEnter`, `onLeave`, `onAppear` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Animate)
    in Animate (created by Tabs)
    in div (created by Tabs)
    in div (created by Tabs)
    in Tabs (created by t)
    in t (created by exports)
    in div (created by exports)
    in div (created by exports)
    in div (created by exports)
    in exports (created by Loader)`

- antd 版本:1.6.3

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2258

不关注 issue，也不关注版本更新么...
