### ISSUE TITLE
Modal.confirm上的疑惑

### ISSUE THREAD

**Issue by vocoWone** [ant-design/ant-design#23269]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-villani-v05sx?file=/index.js:416-451)

### Steps to reproduce
第一次点击【Confirm】按钮， ok button的loading状态没更改

### What is expected?
第一次点击【Confirm】按钮， ok button的loading状态会更改

### What is actually happening?
第一次点击【Confirm】按钮， ok button的loading状态没更改

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | react 16.13 |
| System | mac |
| Browser | 谷歌 |

**Comment by afc163** [comment]
建议参考这个例子：https://ant.design/components/modal-cn/#components-modal-demo-confirm-promise
