### ISSUE TITLE
Tree component - hide file icon when use showLine

### ISSUE THREAD

**Issue by larsmogren** [ant-design/ant-design#23261]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/883vo47xp8)

### Steps to reproduce
go to https://codesandbox.io/s/883vo47xp8

### What is expected?
File icon should be hidden and replaced with line.

### What is actually happening?
File icon is still visible.

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome  80.0.3987.163 |

---
Got the link to https://codesandbox.io/s/883vo47xp8 from https://ant.design/components/tree/
The example in https://codesandbox.io/s/883vo47xp8 works for antd 3.26.15

**Comment by afc163** [comment]
We need a `showline={{ hideLeafIcon }}` prop for convenience.

**Comment by abhishekahuja87** [comment]
Any plans to fix this? Thanks

**Comment by fireairforce** [comment]
I will fix this.

**Comment by fireairforce** [comment]
solved at： https://github.com/ant-design/ant-design/pull/25067

**Comment by abhishekahuja87** [comment]
Hi, I still see this issue; its not fixed I guess

**Comment by CezarCobuz** [comment]
This issue is still present please reopen this issue
