### ISSUE TITLE
Select suffixIcon behavior issue

### ISSUE THREAD

**Issue by hejaziak** [ant-design/ant-design#23263]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tags-ant-design-demo-yl5nd?file=/index.js)

### Steps to reproduce
Hover or click on the copy icon

### What is expected?
The tooltip should appear when hover and onCopy function should be called when clicking

### What is actually happening?
no tooltip appears and the icon is not clickable

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.12 |
| System | mac OSX 10.15.3 |
| Browser | Chrome version 80 |

**Comment by suman7063** [comment]
I found solution 
  const [isActive, setActive] = useState(true);
  const toggleClass = () => {
    setActive(!isActive);
  };
 suffixIcon={<CaretDownOutlined className={isActive ? 'ant-select-suffix' : ''} onClick={toggleClass} />}

**Comment by phuong-eoh** [comment]
> I found solution const [isActive, setActive] = useState(true); const toggleClass = () => { setActive(!isActive); }; suffixIcon={<CaretDownOutlined className={isActive ? 'ant-select-suffix' : ''} onClick={toggleClass} />}

It works, thank you! 🚀

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/29996#issuecomment-1089747530

**Comment by toannh-nalvn** [comment]
My solution: :global(.ant-picker-suffix) {
      :global(.anticon) {
        border-radius: var(--br-full);
        background-color: var(--blue-1);
      }
    }

**Comment by Minhnd3** [comment]
add **style={{ pointerEvents: 'none' }}** in suffixIcon component
