### ISSUE TITLE
TS2741: Property 'translate' is missing in type '{}'

### ISSUE THREAD

**Issue by monolithed** [ant-design/ant-design#23266]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-chebyshev-d81vs?file=/src/App.tsx)

### Steps to reproduce
```ts
import React from "react";
import { HomeOutlined} from '@ant-design/icons';

export const Example = () => {
  return (
      <HomeOutlined />
  );
};
```

### What is expected?
No errors

### What is actually happening?
```
TS2741: Property 'translate' is missing in type '{}' but required in type 'Pick<AntdIconProps, "cite" | "data" | "form" | "label" | "span" | "style" | "summary" | "title" | "pattern" | "slot" | "children" | "max" | "required" | "high" | "low" | ... 347 more ... | "twoToneColor">'.
```

<img width="822" alt="Screenshot 2020-04-14 at 23 58 17" src="https://user-images.githubusercontent.com/803674/79277270-25b32f80-7eb2-11ea-8a0a-8c36d8672590.png">

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.11.0 |
| System | macOS 10  |
| Browser | Safari |

---
I got that error after replacing antd@4.0.0-rc.6 with antd@4.1.1
The main reason of the error is using @ant-design/icons as an internal dependency with a prefix ^(caret) symbol. 

```
antd@4.0.0-rc.6
    -- @ant-design/icons@4.0.0 // good

antd@4.1.1
    -- @ant-design/icons@4.0.6  // bad
```

As I know the translate property shouldn't be required by default without a backward compatibility.

PS: please, don't use the ^(caret) symbol at all.

**Comment by chenshuai2144** [comment]
@monolithed  you need update @type/react

**Comment by afc163** [comment]
Your codesandbox works well: https://codesandbox.io/s/gracious-bassi-mep2m?file=/src/App.tsx

**Comment by PandaJJ5286** [comment]
> @monolithed you need update @type/react

@type/react升级到什么版本，16.9.1依然不生效

**Comment by jonathan-chancetop** [comment]
@PandaJJ5286 @types/react-dom also need to upgrade

**Comment by wumiangithub** [comment]
@type/react    16.9.49
@types/react-dom    16.9.8
react-dom   16.13.1 
react    16.13.1
"@ant-design/icons": "^4.2.2",
也报这个错

**Comment by dwb1994** [comment]
> @monolithed you need update @type/react

@type[s]/react

**Comment by lty-work** [comment]
> > @monolithed you need update @types/react
> 
> @types/react升级到什么版本，16.9.1依然不生效

^16.9.23

**Comment by Rynxiao** [comment]
Use `npm dist-tags` command to determine which types version you need to upgrade.

for example, use `npm dist-tags @types/react` to match your `typescript` version

```shell
$ npm dist-tags @types/react                                                                                                                        ⬡ 12.13.0 [±master ●]
latest: 16.9.56
ts2.0: 15.0.1
ts2.1: 15.0.20
ts2.2: 15.0.30
ts2.3: 16.0.36
ts2.4: 16.0.36
ts2.5: 16.0.36
ts2.6: 16.4.7
ts2.7: 16.4.7
ts2.8: 16.9.34
ts2.9: 16.9.35
ts3.0: 16.9.46
ts3.1: 16.9.49
ts3.2: 16.9.56
ts3.3: 16.9.56
ts3.4: 16.9.56
ts3.5: 16.9.56
ts3.6: 16.9.56
ts3.7: 16.9.56
ts3.8: 16.9.56
ts3.9: 16.9.56
ts4.0: 16.9.56
ts4.1: 16.9.56
ts4.2: 16.9.56
```

**Comment by dotnetpower** [comment]
It's working as well after run "npm install @ant-design/icons@4.0.0".
thanks,

**Comment by g770728y** [comment]
> It's working as well after run "npm install @ant-design/icons@4.0.0".
> thanks,

Yes, It works after install @ant-design/icons@4.0.
BTW: upgrade @type/react did not help.

**Comment by zawie** [comment]
I still have this issues: install @ant-design/icons@4.0 or upgrade @type/react did not help.

**Comment by fatelei** [comment]
I still have this issues: install @ant-design/icons@4.0 or upgrade @type/react did not help.

**Comment by fatelei** [comment]
I fix it, @zawie you should upgrade typescript >= 3.8.0 https://stackoverflow.com/questions/62939139/declaration-or-statement-expected-with-react-bootstrap

**Comment by Juned-H2** [comment]
Had a similar issue, updated @types/react and problem resolved.

`yarn remove @types/react`
then
`yarn add @types/react@latest --dev`
