### ISSUE TITLE
如何只引入ant layout?

### ISSUE THREAD

**Issue by PhilipDing** [ant-design/ant-design#2327]
只想用ant layout，应该怎么用？import 'antd/dist/antd.css' 之后会帮一些其他的样式override掉了，例如我现在用的material-ui

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#i-just-want-to-use-menubuttonetc-but-it-seems-that-i-have-to-import-the-whole-antd-and-its-style

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
