### ISSUE TITLE
DatePicker - API to customize rendering of the input

### ISSUE THREAD

**Issue by travikk** [ant-design/ant-design#23276]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
DatePicker (and RangePicker more specifically) takes up a lot of UI real estate. Currently there is no way to not show input as it acts as the trigger for displaying the panels.

I would like to request a feature, whereby developers will be allowed to specify custom rendering of the input. Currently I have a use-case, where I'd like to display 1 simple button with calendar icon (instead of inputs and separator), which would show a range picker. The idea is that my real estate is limited and I can't fit 2 inputs just to display user's selection.

I can somewhat achieve that by hacking around and setting display: none to inputs and separators, but it's not a solution I'm happy with. Ideally there's API that will allow customizing that part of the component.

### What does the proposed API look like?
There's 2 choices:

- allow a specific prop like inputRender
- if props.children is defined, use that instead of rendering content of the container div (which contains inputs and separators)

**Comment by afc163** [comment]
see #18376

**Comment by travikk** [comment]
@afc163 thanks. While I know of the workaround (hiding the inputs) that's not ideal, as it messes up tab order, not to mention rendering of extra elements which are unnecessary.

It would be great to provide API that would allow solving this is a less hacky way.

**Comment by hardmanhong** [comment]
`RangePicker` 也可以支持 `inputRender` 吗，看了 `rc` 库的代码，并不支持呢

**Comment by hardmanhong** [comment]
> see #18376 and #18743

`RangePicker` 也可以支持 `inputRender` 吗，看了 `rc` 库的代码，并不支持呢

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
