### ISSUE TITLE
当DatePicker的showTime为false返回时间戳有误

### ISSUE THREAD

**Issue by chendanlin** [ant-design/ant-design#23273]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-8fsbf?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/antd-reproduction-template-8fsbf?file=/index.js

### What is expected?
普通DatePicker返回的时间戳是日期的0时0分0秒0毫秒的时间戳,在RangePicker的结束时间是日期的23时99分99秒999毫秒的时间戳

### What is actually happening?
返回的是当前时间的时间戳

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | react 16.12.0 |
| System | window10 |
| Browser | edge 81.0.416.53 |

---
这导致了如果在查询时使用了RangePicker，有一条记录时间是2020-01-01 09:00:00 我在选择2020-01-01时的当天时间晚于09:00:00，返回的时间戳会大于2020-01-01 09:00:00，这条记录将不会存在。当showTime为false时，我只是想查找在此日期内的记录,并不希望带上当前时间

**Comment by chendanlin** [comment]
https://codesandbox.io/s/antd-reproduction-template-8fsbf?file=/index.js
已经更新，在9点过后当选择4月15号时记录被过滤掉了，原因是日期的时间戳会带上当前时间，所以查询的时间会大于2020-04-15 09:00:00

**Comment by afc163** [comment]
建议比较前根据具体需求加上 `.startOf('day')`。

**Comment by chendanlin** [comment]
@afc163 这只是简化了的实例，使用moment只是为了方便展示效果，真实情况是请求后端，当然我可以在传参时修改，但是是否可以在组件中就完成这个操作

**Comment by afc163** [comment]
默认日期是会带上当前时间的，建议获得信息后自行二次处理后再提交后端。
