### ISSUE TITLE
ant design的select的mode=multiple, value初始化值数组key时，只显示key，不显示对应的名字，而onChange赋值数组key，显示对应的名字 ant4.0 

### ISSUE THREAD

**Issue by RomaYang** [ant-design/ant-design#23285]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/?repo=ant-design](https://new-issue.ant.design/?repo=ant-design)

### Steps to reproduce
无

### What is expected?
select的mode=multiple, value初始化值数组key时，应该默认显示对应的名字，而不是直接显示key

### What is actually happening?
初始化，直接显示了key

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome |

**Comment by admiao** [comment]
我也出现了，数据是异步的 ，同步数据出现的话建议你对比一下key的类型
