### ISSUE TITLE
使用reducers删除state一条数据后界面不更新

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design#23287]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
使用reducers删除state一条数据后界面不更新

### What is expected?
界面更新

### What is actually happening?
未跟新

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | window10 |
| Browser | 谷歌 |

---
import { Effect, Reducer } from 'umi';
import { queryList, addParameter, editParameter, delParameter } from './service';
import { Parameter } from "./data.d";
import { message } from 'antd';

export interface ModelType {
  namespace: string;
  state: ParStateType;
  effects: {
    delete: Effect;
  };
  reducers: {
    delPar: Reducer<ParStateType>;
  };
}

export interface ParStateType {
  list: Parameter[],
}

const Model: ModelType = {
  namespace: 'parameter',
  state: {
    list: [],
  },

  effects: {
    *delete({ payload }, { call, put }) {
      const response = yield call(delParameter, payload);
      yield put({
        type: 'delPar',
        payload: response,
      });
    },

  },
  reducers: {
    delPar(state = { list: [] }, { payload }) {
      if (payload.success) {
        message.success("参数删除完成！");
        let lists = state.list;
        var ind = lists.findIndex(item => item.id === payload.data.id);
        if (ind > -1) {
          lists.splice(ind, 1);
          return {
            ...state,
            list: lists,
          };
        }
      } else {
        message.error("参数删除失败！");
      }
      return {
        ...state,
        list: state.list,
      };
    },

  }

};

export default Model;

{
      title: '操作',
      width: 125,
      align: 'center',
      render: (_, record) => {
        return (<>
          <Popconfirm title='确定删除?' onConfirm={() => {
            dispatch({
              type: 'parameter/delete',
              payload: record.id,
            });
          }}>
            <a>删除</a>
          </Popconfirm>
          <Divider type="vertical" />
          <a onClick={() => {
            setFormValues(record);
            openUpdateModal(true);
          }}>修改</a>
        </>
        )
      }

**Comment by afc163** [comment]
看描述和 antd 没关系，关闭。
