### ISSUE TITLE
antd Tabs切换在IE浏览器下非常慢如何优化？

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#23288]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在ie浏览器下切换严重卡顿，好几秒才切换过来，不知道为什么，动画功能我都关闭了，还是很卡，有点严重影响用户使用体验了

### What does the proposed API look like?
在ie浏览器上切换正常，无卡顿现象

**Comment by yoyo837** [comment]
先看一下Chome性能采集是哪里卡，发个图

**Comment by Mathround** [comment]
> 先看一下Chome性能采集是哪里卡，发个图

![image](https://user-images.githubusercontent.com/25702871/79324456-3e6b2600-7f42-11ea-897a-84533ac88c85.png)

**Comment by yoyo837** [comment]
录gif吧，需要选中一片区域查看（一次tab切换的开始和截止）

**Comment by Mathround** [comment]
> 录gif吧，需要选中一片区域查看（一次tab切换的开始和截止）

没试过录gif的，晚点我研究研究怎么录制gif的，你看看这张有参考意义吗？我只切换一个tabs标签录下来的结果数据
![image](https://user-images.githubusercontent.com/25702871/79326614-b71fb180-7f45-11ea-8de3-33b3011689c1.png)

**Comment by yoyo837** [comment]
要不给复现仓库吧。这样效率太低。

**Comment by Mathround** [comment]
> 要不给复现仓库吧。这样效率太低。

好，我先研究一下，我不知道是不是我代码写的有问题

**Comment by hengkx** [comment]
windows下 可以用这个录制 gif https://github.com/NickeManarin/ScreenToGif
