### ISSUE TITLE
antd没有颜色选择器组件吗

### ISSUE THREAD

**Issue by eveningwater** [ant-design/ant-design#23280]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
更改颜色

### What does the proposed API look like?
就是像element ui那样的颜色选择器组件

**Comment by afc163** [comment]
现在可以使用 https://github.com/casesandberg/react-color

**Comment by afc163** [comment]
https://ant.design/docs/react/recommendation-cn
