### ISSUE TITLE
[Table] sorter.columnKey is undefined

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#23289]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keshensuolie-ant-design-demo-h3kes?file=/index.js)

### Steps to reproduce
- click column which can be sort by.
- check `sorter` argument from `onChange`, `sorter.columnKey` is `undefined`.

### What is expected?
`sorter.columnKey` is not `undefined`.

### What is actually happening?
`sorter.columnKey` is `undefined`.

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome |

**Comment by zombieJ** [comment]
You need config `key` on column to get the `columnKey` or just use `field` to get mapping `dataIndex`: https://codesandbox.io/s/keshensuolie-ant-design-demo-1w30h

**Comment by afc163** [comment]
This line don't use `getColumnKey` like other places: https://github.com/ant-design/ant-design/blob/0716d1498f63fb2d6c9af39a2ad11d2d028e0fa2/components/table/hooks/useSorter.tsx#L223

- https://github.com/ant-design/ant-design/blob/0716d1498f63fb2d6c9af39a2ad11d2d028e0fa2/components/table/hooks/useSorter.tsx#L125
- https://github.com/ant-design/ant-design/blob/0716d1498f63fb2d6c9af39a2ad11d2d028e0fa2/components/table/hooks/useSorter.tsx#L68

**Comment by zombieJ** [comment]
table generate internal key for sort mapping, but it's meaningless for user. since user many have multiple column with same `dataIndex`:
```tsx
const columns = [
  { dataIndex: 'user', render: (_, user) => user.name },
  { dataIndex: 'user', render: (_, user) => user.age },
];
```

Not export internal `getColumnKey` to sort param is by design.

ref: https://github.com/ant-design/ant-design/blob/0716d1498f63fb2d6c9af39a2ad11d2d028e0fa2/components/table/util.ts#L4
