### ISSUE TITLE
按照‘快速上手’文档，修改源码文件不自动刷新

### ISSUE THREAD

**Issue by hellobbq** [ant-design/ant-design#2329]
#### 本地环境

- antd 版本: 1.1.2
- 操作系统及其版本：windows10
- 浏览器及其版本: chrome

#### 你做了什么？
1、npm install antd-init -g
2、mkdir antd && cd antd
3、antd-init --type plain-react
4、跑起来后，随意修改了一个less和jsx文件，打开的页面不能自动刷新，console如实际结果阐述

#### 你期待的结果是：

修改src下的文件后页面自动刷新

#### 实际上的结果：

`[HMR] connected
client.js:127 [HMR] bundle rebuilding
client.js:130 [HMR] bundle rebuilt in 499ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:81[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.
process-update.js:89[HMR]  - ./src/layouts/MainLayout/MainLayout.jsx
client.js:127 [HMR] bundle rebuilding
client.js:130 [HMR] bundle rebuilt in 224ms
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:81[HMR] The following modules couldn't be hot updated: (Full reload needed)
This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

process-update.js:89[HMR]  - ./src/entries/index.less`

#### 可重现的在线演示

无

**Comment by GrayChoi** [comment]
安装chrome插件live reload

**Comment by hellobbq** [comment]
@GrayChoi 谢谢
