### ISSUE TITLE
Usability: Tabbing through radio buttons inside carousel breaks

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#23294]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/long-forest-ylg6b)

### Steps to reproduce
1. Tab through the radio buttons inside the carousel. (Do not use mouse)
2. After tabbing through the last radio button in a slide, the next slide is partially shown

### What is expected?
The slide should not break.

### What is actually happening?
After tabbing through the last radio button in a slide, the next slide is partially shown

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 81 |

**Comment by mendoncanorma** [comment]
Attaching recording for reference: 
[Bug_Carousel.zip](https://github.com/ant-design/ant-design/files/4481805/Bug_Carousel.zip)

**Comment by mendoncanorma** [comment]
@ant-design-bot 
Do you need more inputs here?

**Comment by mendoncanorma** [comment]
@afc163 ,
Can you please cherry pick this bug fix to antd 3.x.

**Comment by afc163** [comment]
Sure~

**Comment by mendoncanorma** [comment]
Thank you @afc163  

~Norma

**Comment by StefanoSega** [comment]
@afc163 get the same issue if v4.6.1 having a Form with Input fields inside a Carousel and tabbing through the fields
