### ISSUE TITLE
Draggable items in multi mode Select component

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#23299]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In a case where the order of choices in the Select component is important: It would provide the user the ability to re-order selections in the multi-mode Select component without having to de-select and re-select multiple times.

### What does the proposed API look like?
`<Select mode="multiple" draggable />`

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9459#issuecomment-369830297
https://github.com/ant-design/ant-design/issues/5799
https://github.com/ant-design/ant-design/issues/9847
