### ISSUE TITLE
关于Select组件的自动分词功能，是否支持回车换行等转义字符

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#23304]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tokenSeparators属性都支持什么字符规格，纯字符串吗，是否支持回车换行等转义字符，我希望能够实现从excel里粘贴一列到Select组件能够自动分词。

### What does the proposed API look like?
支持回车换行等转义字符，能够实现从excel里粘贴一列到Select组件能够自动分词

**Comment by afc163** [comment]
`tokenSeparators={[' ']}`

不过这样一行内的空格识别不出来。

**Comment by afc163** [comment]
https://codesandbox.io/s/automatic-tokenization-ant-design-demo-2q1xy?file=/index.js

@zombieJ `onPaste` 可以拿到换行信息。

**Comment by phoema** [comment]
感谢，原来空格就能分换行的词
目前编号组基本不会出现空格，一般情况能满足需求
当然，有了真正的换行支持更好，加油。

**Comment by lhd-1727865856** [comment]
Mac输入法使用 tokenSeparators={[' ']} 分词 会乱掉
