### ISSUE TITLE
Table scroll.y 动态更变，会导致表格列错位

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#23308]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quiet-bush-7k2d2?file=/index.js)

### Steps to reproduce
先向右拖曳滚动条一段距离后，再切换分页（切换多次分页，大约3到5次或更多）后，会看到列出现很明显的错位显示

> 这个时候如果随意拖曳一下滚动条，表格就能正常展示

![image](https://user-images.githubusercontent.com/8147202/79411087-8f2b5f00-7fd4-11ea-8f83-38a4d0b13f89.png)

### What is expected?
Table `scroll.y` 动态更变，先向右拖曳滚动条一段距离后，再切换分页（切换多次分页，大约3到5次或更多）后，列能正常展示，不错位

![image](https://user-images.githubusercontent.com/8147202/79411132-a10d0200-7fd4-11ea-98ad-3315eebfaa61.png)

![image](https://user-images.githubusercontent.com/8147202/79411153-b08c4b00-7fd4-11ea-8ead-01616e7ce0b9.png)

### What is actually happening?
列错位

![image](https://user-images.githubusercontent.com/8147202/79411099-93577c80-7fd4-11ea-839e-f0f6b1af1e17.png)

| Environment | Info |
|---|---|
| antd | 3.26.12 |
| React | 16.13.1 |
| System | win 10 |
| Browser | Chrome 78.0.3904.70 |

**Comment by zombieJ** [comment]
Duplicate of #9900

**Comment by fengyun2** [comment]
@zombieJ @afc163 这个不是 【表格 固定列 子表格】引起的bug，我这个都没有固定列，是 scroll 动态计算导致出现的bug

**Comment by zombieJ** [comment]
底层是同一个原因，表头和表格是两个表格实现，也是表格对齐的实现问题。

**Comment by fengyun2** [comment]
3.x 版本没计划修复吗？或者有什么解决办法？例如切换分页时，表格滚动条滚动一段距离触发表格重新渲染一次

**Comment by zombieJ** [comment]
v3 版本的 table 设计修不了了。 ref：https://zhuanlan.zhihu.com/p/102037418
