### ISSUE TITLE
[DatePicker] 范围日期选择器闪回问题

### ISSUE THREAD

**Issue by fjc0k** [ant-design/ant-design#23305]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker](https://ant.design/components/date-picker-cn/#components-date-picker-demo-range-picker)

### Steps to reproduce
1. 点击第一个演示打开选择器
2. 将月份拉至2021年5月
3. 点击选择2021年5月21日
4. 明显可见，选择区域闪回了2020年4月，而不是停留在2021年5月

![chrome-capture](https://user-images.githubusercontent.com/13151189/79407867-95b5d880-7fcc-11ea-812f-8df5ee3ddb87.gif)

### What is expected?
选择区域停留在2021年5月

### What is actually happening?
选择区域闪回了2020年4月

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.x |
| System | macos |
| Browser | chrome 83 |

**Comment by afc163** [comment]
最新版本应该已经修复了， @fjc0k 可以到官网确认一下。
