### ISSUE TITLE
Antd V4 antd.less doesn't work?

### ISSUE THREAD

**Issue by thenylify** [ant-design/ant-design#23301]
I get the following issue when I include antd.less file in my React App.js file..

Module build failed (from ../node_modules/less-loader/dist/cjs.js):
      /* stylelint-disable-next-line function-calc-no-invalid */
      padding-right: calc(@drawer-header-close-padding - var(--scroll-bar));
    ^
Cannot read property 'numerator' of undefined

The issue which is not created via http://new-issue.ant.design will be closed immediately.

---

注意：不是用 http://new-issue.ant.design 创建的 issue 会被立即关闭。

**Comment by thenylify** [comment]
Any help would be much appreciated!

**Comment by afc163** [comment]
upgrade your less version to latest

**Comment by thenylify** [comment]
> upgrade your less version to latest

Awesome! Thanks
