### ISSUE TITLE
Select支持label或value搜索

### ISSUE THREAD

**Issue by qwer5454554** [ant-design/ant-design#23316]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在form表单中使用Select时
Select如果是通过后台接口渲染  
在form提交时我们期望能拿到当前Select选择的值 antd也是这么做的(因为我们给每一个option都添加了value值)
但如果Select如果需要支持搜索 按照常规的给每一个options赋value值 组件会根据Select.option的value值去过滤  而我们期望的是通过过滤label
如果不给每个option赋value值是可以通过label搜索  但在form提交时获取到的是当前选项的label文字 而我们期望获取到的是value值

### What does the proposed API look like?
Select支持根据value还是label来搜索

**Comment by afc163** [comment]
你需要研究一下 `optionFilterProp`。

**Comment by qwer5454554** [comment]
sorry 我好像铁憨憨

**Comment by yyqxjwxy** [comment]
> sorry 我好像铁憨憨

哈哈我也遇到了这个问题

**Comment by stefango** [comment]
https://github.com/react-component/select/blob/master/src/hooks/useFilterOptions.ts#L33
