### ISSUE TITLE
Form.Item 的多个验证规则，validateFirst=true有错误时希望终止验证

### ISSUE THREAD

**Issue by kettyy** [ant-design/ant-design#23327]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如下，希望验证到输入字符不满足第一个规则时，不发送ajax请求，现在情况是不符合第一个规则也会执行第二条规则

```
<Form.Item
  name="name"
  validateFirst={true}
  validateTrigger="onBlur"
  rules={[
    {
      required: true,
      max: 20,
      min: 2,
    },
    ({ getFieldValue, isFieldTouched, getFieldError }) => ({
      validator: (rule, value) => {
        return Axios.get(`xxxxxx`, {
          params: {
            name: value,
          },
        }).then(({ status }) => {
          // 
        });
      },
    }),
  ]}
>
  <Input />
</Form.Item>
```

### What does the proposed API look like?
期望校验是异步，但是能捕获错误，及时终止

**Comment by yoyo837** [comment]
Maybe duplicated of #21793

**Comment by kettyy** [comment]
> Hello @kettyy. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @kettyy, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/antd-reproduction-template-4vty1?file=/index.js

**Comment by yoyo837** [comment]
就是和#21793说的一回事，你看看。

**Comment by kettyy** [comment]
> 就是和 #21793 说的一回事，你看看。

由于https://github.com/ant-design/ant-design/issues/21793已被关闭，所以新开了一个issue，这个问题希望能得到解决

**Comment by kettyy** [comment]
> 就是和 #21793 说的一回事，你看看。

由于https://github.com/ant-design/ant-design/issues/21793  已被关闭，所以新开了一个issue，这个问题希望能得到解决

**Comment by yoyo837** [comment]
豆酱在那个问题里有回复，多个validator都是并行的，任何一个错误即返回，但是已经开始执行的不会停下来。

除非串行才能满足。

可能不太容易接受这个改变。
