### ISSUE TITLE
FormItem间联动无效，即使设置了shouldUpdate

### ISSUE THREAD

**Issue by xiaofengz** [ant-design/ant-design#23320]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/beautiful-mendeleev-jxovl?file=/src/index.js)

### Steps to reproduce
点击add field,左边输入lastname，右边无显示，需再点击add field才触发更新

### What is expected?
点击add field,左边输入lastname，右边应该显示lastname input框

### What is actually happening?
点击add field,左边输入lastname，右边无显示，需再点击add field才触发更新

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
`shouldUpdate` 是 `renderProps` 用的。不是和 `name` 配合的：https://codesandbox.io/s/inspiring-fast-llxp0?file=/src/index.js:1284-1296
