### ISSUE TITLE
antd 的 css 类名，是否支持自己增加前缀？

### ISSUE THREAD

**Issue by ubuntugx** [ant-design/ant-design#23324]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
主项目里（antd 2.x）需要引入一个npm包，npm包里的antd版本是3.x，出现了样式覆盖的情况，所以想在 npm 包中，把antd的类名统一加前缀，避免覆盖的情况

### What does the proposed API look like?
可以统一修改 antd css 类名的前缀

**Comment by afc163** [comment]
https://ant.design/components/config-provider-cn/

**Comment by MinL-DN** [comment]
你好，可以给个思路么，我也遇到了同样的问题

**Comment by yoyo837** [comment]
支持的，上面这个链接里是文档

**Comment by shijunwen** [comment]
你好，我组件库用了antd4.0，项目里面用的antd3.0。在项目里面引用组件库的组件导致样式污染了，请问你是怎么处理的，能给个思路吗？
