### ISSUE TITLE
表格列名称部分点击事件

### ISSUE THREAD

**Issue by Minfee** [ant-design/ant-design#23322]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在table组件用作比对数据，希望点击列名之后另一表格可以进行数据同步，所以需要表格 列名部分的点击事件

### What does the proposed API look like?
加入可以控制列名render部分的api

**Comment by afc163** [comment]
`onHeaderRow`
