### ISSUE TITLE
Cascasder ：Warning: value prop on input should not be null. 

### ISSUE THREAD

**Issue by klniu** [ant-design/ant-design#2333]
#### 本地环境
- antd 版本: 1.6.4
- 操作系统及其版本：archlinux x86_64
- 浏览器及其版本: google-chrome 51.0.2704.106
- react: 15.1.0

在1.6.4版本之前，Cascader的源码在处理Input value prop的时候，使用的空字符串，如下图：
![screenshot_20160710_142750](https://cloud.githubusercontent.com/assets/1018698/16712059/90bde59c-46ab-11e6-9716-b534ce725376.png)
1.6.4版本中，此prop改为null，如下图：
![screenshot_20160710_143158](https://cloud.githubusercontent.com/assets/1018698/16712060/90ebd312-46ab-11e6-9b10-e38375ba9aa0.png)
因此，react（15.1.0以上的版本均是，以下未测试）为在控制台显示一个错误：

> Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

并且cascader无法选中选项。

**Comment by afc163** [comment]
ref #2335
