### ISSUE TITLE
RangePicker with component style not working correctly

### ISSUE THREAD

**Issue by HsnImam** [ant-design/ant-design#23337]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-bhaskara-km1ku)

### Steps to reproduce
1- Click in the input box of RangePicker
2 - Observe the date popup

### What is expected?
On selecting the input box, date popup should be visible. On selecting outside, it should hide.

### What is actually happening?
When I click inside the RangePicker input box, date popup is not visible but when focus is lost, date popup panel is visible.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.0 |
| System | UNIX |
| Browser | Chrome Version 80.0.3987.163  |

---
I am using antd RangePicker, when I am using `import 'antd/es/date-picker/style/index.css';` or `import 'antd/es/date-picker/style/index.less';`, styles are not getting polluted but the component is not working as expected.

**Comment by jsalis** [comment]
Looks like you need to also import the core styles which include animations for the popup.

**Comment by afc163** [comment]
https://codesandbox.io/s/stoic-waterfall-koqrz?file=/src/App.js

**Comment by HsnImam** [comment]
Thanks for looking into this solution, but when I import like this `import "antd/es/date-picker/style/css";`, it affects my global style. `antd` pollutes my other style. To avoid this, I was loading the specific css. I had followed the instruction on [this thread](https://github.com/ant-design/ant-design/issues/9363)

**Comment by jjsub** [comment]
@HsnImam To only import the style of the RangePicker without affecting the global style, this worked out for me:

```
import {DatePicker} from 'antd';
import 'antd/es/date-picker/style/index.css';
import 'antd/es/input/style/index.css';
```
