### ISSUE TITLE
Upload inside Form.Item with label has a large blank space below it

### ISSUE THREAD

**Issue by m-weeks** [ant-design/ant-design#23339]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pictures-wall-ant-design-demo-04y94?file=/index.js)

### Steps to reproduce
Putting an upload with `showUploadList={true}` inside a form item with a label inside a form with `layout="true"`. Once uploading an image to this input, the issue is caused.

### What is expected?
The uploaded images and upload button should appear properly inline without a large space below

### What is actually happening?
The images and button appear next to each other, but there is a space below them the size of the upload button.

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 80.0.3987.163 |

**Comment by JMarkoski** [comment]
Is someone working on this? I would like to take it.

**Comment by afc163** [comment]
@JMarkoski PR welcome~

**Comment by komagic** [comment]
这个是什么情况
