### ISSUE TITLE
Tree组件定义错误

### ISSUE THREAD

**Issue by sunguoxing0628** [ant-design/ant-design#23335]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-mop2q)

### Steps to reproduce
1、使用`Tree`组件的`selectedKeys`和`onSelect`

2、获取事件`onSelect`的参数`selectedKeys`，处理过后，对`Tree`的`selectedKeys`属性赋值

3、提示错误TS2322: Type 'ReactText[]' is not assignable to type 'string[]'，`selectedKeys`类型为`string[]`，而`onSelect`的第一个参数`selectedKeys`为`React.ReactText[]`

### What is expected?
```
onSelect: (selectedKeys: string[]) => void
或者
selectedKeys: ReactText[]
```

### What is actually happening?
TS2322: Type 'ReactText[]' is not assignable to type 'string[]'. 

Type 'ReactText' is not assignable to type 'string'. 

Type 'number' is not assignable to type 'string'.

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.8.6 |
| System | macOS 10.15.4 |
| Browser | Chrome 80.0.3987.163 |

---
重现链接是js版本的，无法实现重现，我把主要代码写在这里

我发现`Tree`的`selectedKeys`类型为`string[]`，而`onSelect`的第一个参数`selectedKeys`为`React.ReactText[]`，直接赋值会提示错误

```
TS2322: Type 'ReactText[]' is not assignable to type 'string[]'. 

Type 'ReactText' is not assignable to type 'string'. 

Type 'number' is not assignable to type 'string'.
```

函数
```
onSelect = (selectedKeys: React.ReactText[]) => {
    if (selectedKeys && selectedKeys.length > 0) {
      // 其他业务
      this.setState({ selectedKeys });
    }
  };
```

代码
```

                <Tree
                    defaultExpandParent
                    onSelect={this.onSelect}
                    selectedKeys={selectedKeys}
                  >
                    {this.renderTreeNodes(treeData)}
                  </Tree>
```

**Comment by yoyo837** [comment]
你的复现与Tree无关，请更新。

**Comment by sunguoxing0628** [comment]
> 你的复现与Tree无关，请更新。

@yoyo837 已经更新了新的链接，增加了一个information.tsx文件

![image](https://user-images.githubusercontent.com/27573161/79528573-edbc1000-809c-11ea-8337-87c199f8b6f6.png)

**Comment by afc163** [comment]
确实不一致，可以来个 PR 修正一下。

另外你暂时可以这么写：https://codesandbox.io/s/antd-reproduction-template-f0cr3?file=/information.tsx:362-405

**Comment by sunguoxing0628** [comment]
> 确实不一致，可以来个 PR 修正一下。
> 
> 另外你暂时可以这么写：https://codesandbox.io/s/antd-reproduction-template-f0cr3?file=/information.tsx:362-405

按照你这么改的话(`onSelect = (selectedKeys: React.ReactText[]) =>void` 改为 `onSelect = (selectedKeys: string[]) => void` )，运行没有什么问题，但是IDE会在组件那个提示检查错误`TS2769: No overload matches this call.`，不能将类型“(selectedKeys: string[]) => void”分配给类型“(selectedKeys: ReactText[], info: { event: "select"; selected: boolean; node: EventDataNode; selectedNodes: DataNode[]; nativeEvent: MouseEvent; }) => void”，不知为何在线IDE没有提示，会不会有其他影。
