### ISSUE TITLE
ConfigProvider doc syntax highlighting

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#23332]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://ant.design/components/config-provider-cn/

### Steps to reproduce
强迫症看着难受:sweat_smile:

### What is expected?
![image](https://user-images.githubusercontent.com/8358236/79484729-adca3e00-8046-11ea-9e9e-c18a3dc54bf9.png)

### What is actually happening?
![image](https://user-images.githubusercontent.com/8358236/79484623-8b382500-8046-11ea-9613-97a0d99a3af8.png)

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | latest |
| System | windows  |
| Browser | chrome |

**Comment by yoyo837** [comment]
没看明白啥意思这是？

**Comment by hengkx** [comment]
> 没看明白啥意思这是？

语法没识别出来 一对标签颜色不一样

**Comment by yoyo837** [comment]
这和编辑器有关吧，在哪看见的？

**Comment by hengkx** [comment]
官网 那个组件的文档
昨天提pr的时候看见的 越看越难受😣

**Comment by afc163** [comment]
去 bisheng 看看能不能修复~
