### ISSUE TITLE
Table 的分页如何做有缓存的？例如之后往前翻的时候不用请求了，我做了个demo，但是有两个问题

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#23349]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
切换页码不用反复请求

### What does the proposed API look like?
无

### 我的codesandbox demo
https://codesandbox.io/s/yuanchengjiazaishuju-ant-design-demo-kbc1v?file=/index.js

### 问题一： （虽然报错但是却能用）
![image](https://user-images.githubusercontent.com/47104575/79540341-94fb7000-80ba-11ea-934d-94cb14c85352.png)

### 问题二：
从第一页分到第二页的时候 loading显示当前页的数据没有问题，但是继续往后翻 loading 显示的是空数据，而不是当前页的数据，等数据请求到了才显示

**Comment by yoyo837** [comment]
自行控制pagination

**Comment by yoyo837** [comment]
修改数据的时候 immutable, 不要push，直接修改成新对象

**Comment by linxianxi** [comment]
> 修改数据的时候 immutable, 不要push，直接修改成新对象

麻烦看一下我发的链接的做法 还有我的问题 你回复的太快了 我刚才还没编辑好。。。

**Comment by linxianxi** [comment]
看了文档 和 issues，都没有找到类似的

**Comment by linxianxi** [comment]
> 修改数据的时候 immutable, 不要push，直接修改成新对象

我现在是的做法是  用一个state存全部的数据  再用slice 取数据放到dataSource上 这样可以

**Comment by zombieJ** [comment]
SWR 库了解一下：https://swr.now.sh/

另外这不是 antd 的问题，先关了
