### ISSUE TITLE
table的state数据更新后带render列的数据不更新

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design#23346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
table的state数据更新后带render列的数据不更新

### What does the proposed API look like?
table的state数据更新后带render列的数据不更新

![TIM截图20200417132330](https://user-images.githubusercontent.com/33310261/79535097-06352600-80af-11ea-9bb5-80d71a706ee5.png)

**Comment by wenguangji** [comment]
可以在拿到state的值后做一次浅拷贝，暂时可以解决这个问题
