### ISSUE TITLE
Tree(树形)控件设置了checkedKeys属性后，点击复选框时事件执行但视图不更新,

### ISSUE THREAD

**Issue by CharleySc** [ant-design/ant-design#2334]
#### 本地环境

- antd 版本:1.6.4
- 操作系统及其版本：MAC OS X  10.11.5
- 浏览器及其版本:  所有浏览器

#### 你做了什么？
使用Tree（树形控件）前提设置了multiple checkable 当再设置checkedKeys属性后，点击复选框时onCheck事件可以执行，但是视图不更新(就是点击复选框了但复选框里的勾没有勾上，但onCheck事件可以触发)，项目紧急。。。希望ant团队能够尽快修复帮帮妹纸我早日脱离苦海。。泪目中。。

#### 你期待的结果是：
前提设置了multiple checkable 当再设置checkedKeys属性。。点击复选框视图可以再更新。。

#### 实际上的结果：
点击其他复选框后那个勾勾并不勾上。。我哭了。。

**Comment by afc163** [comment]
checkedKeys 是受控组件，建议自行研习 React 受控组件概念。http://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by CharleySc** [comment]
那我想问一下。。。。设置了checkedKeys checkedKeys受控的概念是只能通过设置的key来选中，后面的操作是再也不能通过鼠标来点击选中其他复选框了吗？ @afc163
