### ISSUE TITLE
[关于4.x Form的疑问和建议] 在表单里有很多元素且拥有initialValue的时候, 如何简单的清空表单?   

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#23341]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在表单里有很多元素且拥有initialValue的时候, 我发现我并不能简单的清空表单.  resetFields会重置到initialValue的时候, 如果用setFieldsValue那些, 则要写好多好多代码. 
可能会有个目前的相对简单的方法:  先resetFields再setFieldsValue将那些初始值清空.
但是如果initialValue设置的初始值不止3个呢?  或者更多. 或者后面需求增加, 又加了几个初始值, 则相应的也要改很多.
不知道Form后面有没考虑出个api 为清空表单的功能,  而不是重置到initialValues.

这样子能解决一键清空表单的问题, 且代码使用简单.

### What does the proposed API look like?
能一键清空表单数据, 而不是重置.

**Comment by yoyo837** [comment]
没太看明白需求是什么

**Comment by crawler-django** [comment]
需求是 简单的清空表单数据. 在有InitialValues的情况 和 表单里面的FormItem很多的情况.

**Comment by hengkx** [comment]
reset 不满足需求？

**Comment by crawler-django** [comment]
> reset 不满足需求？

reset 只是重置到initialValue. 是重置到设置的初始值, 不是清空

**Comment by hengkx** [comment]
完全清空 还初始化干嘛 用的时候设置值不就好了

**Comment by yoyo837** [comment]
全部清空的功能？无任何默认值的？

**Comment by crawler-django** [comment]
> 完全清空 还初始化干嘛 用的时候设置值不就好了

不一样, 有些搜索是要初始值的.  但是不要值就搜索全部数据, 客户就不想一个个删, 需要一键清空.

**Comment by yoyo837** [comment]
> reset 只是重置到initialValue. 是重置到设置的初始值, 不是清空

initialValue不就是初始值吗？到底啥意思。

**Comment by crawler-django** [comment]
> 全部清空的功能？无任何默认值的？

是的. 数据全部清空.

**Comment by yoyo837** [comment]
> > 全部清空的功能？无任何默认值的？
> 
> 是的. 数据全部清空.

你前面又否认不是要全部清空，整懵了。 结论就是要“全部清空”吧！？

**Comment by crawler-django** [comment]
> > > 全部清空的功能？无任何默认值的？
> > 
> > 
> > 是的. 数据全部清空.
> 
> 你前面又否认不是要全部清空，整懵了。 结论就是要“全部清空”吧！？

抱歉.. 我说的reset是重置到初始值, 不是清空值 的意思

**Comment by yoyo837** [comment]
> 抱歉.. 我说的reset是重置到初始值, 不是清空值 的意思. 是要全部清空.

更懵了。

resetFields 不就是重置到默认值吗？

> 不是清空值 的意思. 是要全部清空.

这句话能不能重新组织下？ 😭

**Comment by crawler-django** [comment]
> > 抱歉.. 我说的reset是重置到初始值, 不是清空值 的意思. 是要全部清空.
> 
> 更懵了。
> 
> resetFields 不就是重置到默认值吗？
> 
> > 不是清空值 的意思. 是要全部清空.
> 
> 这句话能不能重新组织下？ 😭

resetFields 官方的意思是重置到初始值. 不是我所想要的清空.  这句话是回 @hengkx 的.
我需要的是全部清空. 需要一个新的api来全部清空表单数据.

**Comment by hengkx** [comment]
建议不使用初始值 用的时候去设置

**Comment by yoyo837** [comment]
> 建议不使用初始值 用的时候去设置

这个怕是只能业务决定，开发没话语权。

应该就是要个 form.clearAll() 这样的API。 主要是他那句

> 不是清空值 的意思.

太难懂了。

**Comment by hengkx** [comment]
> > 建议不使用初始值 用的时候去设置
> 
> 
> 
> 这个怕是只能业务决定，开发没话语权。
> 
> 
> 
> 应该就是要个 form.clearAll() 这样的API。 主要是他那句
> 
> 
> 
> > 不是清空值 的意思.
> 
> 
> 
> 太难懂了。

完全可以满足实际业务 开发做处理就好了 没必要增加api

**Comment by yoyo837** [comment]
> 完全可以满足实际业务 开发做处理就好了 没必要增加api


我明白你的意思了

@crawler-django 表单不使用initialValue而使用setFieldsValue来初始化，然后resetFields就是清空了。如果要恢复业务层面的默认值，在setFieldsValue一遍

**Comment by crawler-django** [comment]
> > 完全可以满足实际业务 开发做处理就好了 没必要增加api
> 
> 我明白你的意思了
> 
> @crawler-django 表单不使用initialValue而使用setFieldsValue来初始化，然后resetFields就是清空了。如果要恢复业务层面的默认值，再setFieldsValue一遍

是个好方法。 以前我习惯把初始值放initialValues里, 清空会比较麻烦, 却没想到这种😆。

**Comment by zhaoqiqang199** [comment]
你们理解都有毛病吧，联系上下文很好理解
