### ISSUE TITLE
Icon组件在TypeScrpt中使用报类型错误

### ISSUE THREAD

**Issue by mxt142114** [ant-design/ant-design#23342]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:4000/无连接](http://localhost:4000/无连接)

### Steps to reproduce
无

### What is expected?
引用：import { QuestionCircleOutlined } from '@ant-design/icons';
使用：<QuestionCircleOutlined className="ml10" />
错误：Property 'translate' is missing in type '{ className: string; }' but required in type 'Pick '
但是import { QuestionCircleOutlined } from '@ant-design/icons/es/icons';这种引用方式就可以，请问我的使用方式有问题吗

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome |

**Comment by sanriqing** [comment]
解决了吗？
