### ISSUE TITLE
There is a long word paragraph in the header of Collapse.Panel, it will make panel-extra dislocation。

### ISSUE THREAD

**Issue by owiki** [ant-design/ant-design#23340]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://nvneq.csb.app/](https://nvneq.csb.app/)

### Steps to reproduce
just open it

### What is expected?
could you make the extra icon in the right position of the panel header?

### What is actually happening?
the panel-extra icon dislocation

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | latest |
| System | windows 10  |
| Browser | chrome 80 |

**Comment by afc163** [comment]
We can refactor layout by flex now.

**Comment by owiki** [comment]
thanks! use `flex-grow:3` in 'header' props can solve this problem.
