### ISSUE TITLE
官网的demo里ts没有泛型

### ISSUE THREAD

**Issue by titianqx** [ant-design/ant-design#23345]
- [ x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
官网的demo里 区分了ts 和  js

但是实际代码两者只是换行不太一样....  其他都一样 

没有泛型  对ts新手不友好....

希望可以完善一下..

感谢

### What does the proposed API look like?
N/A

**Comment by afc163** [comment]
直接来 PR 吧，TypeScript 例子现在也少的可怜，希望社区长期帮忙更新。
