### ISSUE TITLE
在Form.Item中使用Upload（官网代码演示第二个：用户头像），上传会报错：fileList.filter is not a function 导致图片上传失败

### ISSUE THREAD

**Issue by lichangchao15442** [ant-design/ant-design#23350]
相关Form.Item代码：
```
<FormItem
          {...formItemLayout}
          label='机构封面'
          name='coverImage'
          valuePropName='fileList'
          rules={[
            {
              required: true,
              message: '请上传机构封面！'
            }
          ]}
        >
          <Upload
            {...UploadProps}
          >
            {coverImageUrl ? <img src={coverImageUrl} alt="avatar" style={{ width: '100%' }} /> : uploadButton}
          </Upload>
        </FormItem>
```
（PS：关于Upload的代码是copy的官网代码演示）
自己定位的原因：在注释掉valuePropName='fileList'后，可以正常上传图片，但是会报一个⚠️：devScripts.js:5035 Warning: [antd: Upload] `value` is not validate prop, do you mean `fileList`?

**Comment by yoyo837** [comment]
我这边试用正常

**Comment by lichangchao15442** [comment]
我知道原因了，是因为没有给Form.Item添加getValueFromEvent={normFile}，加上之后就正常了。（不断踩坑的小白😂）

**Comment by CBCzed** [comment]
@lichangchao15442 遇到同样的问题，normFile具体写什么，方便告知一下吗？

**Comment by lichangchao15442** [comment]
> @lichangchao15442 遇到同样的问题，normFile具体写什么，方便告知一下吗？

这个
const normFile = (e: any) => {
    if (Array.isArray(e)) {
      return e;
    }
    return e && e.fileList;
  };

**Comment by nameJw** [comment]
`
<Form.Item label='头像' name='avatar' valuePropName='fileList'>
    <Upload />
</Form.Item>
`
我的这样写了valuePropName='fileList' 还是报那个警告：
Warning: [antd: Upload] `value` is not a valid prop, do you mean `fileList`?

**Comment by s464446877** [comment]
遇到同样问题，不加valuepropname就报value is not a valid prop, do you mean fileList?，加上之后就报fileList.filter is not a functio，怎么解决

**Comment by relines** [comment]
遇到同样问题，不加valuepropname就报value is not a valid prop, do you mean fileList?，加上之后就报fileList.filter is not a functio，怎么解决？

**Comment by relines** [comment]
遇到同样问题，不加valuepropname就报value is not a valid prop, do you mean fileList?，加上之后就报fileList.filter is not a functio，怎么解决？
antd 3.0

**Comment by relines** [comment]
antd 3.0 遇到同样问题，不加valuepropname就报value is not a valid prop, do you mean fileList?，加上之后就报fileList.filter is not a functio，怎么解决？
