### ISSUE TITLE
用typescript开发，引入Select 组件 没有找到  firstActiveValue？（rc-select 去掉了firstActiveValue的声明）

### ISSUE THREAD

**Issue by huihongzhou** [ant-design/ant-design#23353]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | chrome |
| Browser | 最新 |

**Comment by yoyo837** [comment]
`firstActiveValue`好像弃用删除了。文档没改。
