### ISSUE TITLE
Can not reset Input and value` prop on `input` should not be null

### ISSUE THREAD

**Issue by williamkhshea** [ant-design/ant-design#2335]
#### Mac OS X 10.11.5

- antd 版本: 1.6.4
- 操作系统及其版本：Mac OS X 10.11.5
- 浏览器及其版本: Chrome 51.0.2704.106 (64-bit)

#### 你做了什么？
![screen shot 2016-07-10 at 4 43 24 pm](https://cloud.githubusercontent.com/assets/4775489/16712583/35ef1c54-46be-11e6-84ed-449d84f7860c.png)

http://ant.design/components/form/

按重置

#### 你期待的结果是：

清空值与状态

#### 实际上的结果：
![screen shot 2016-07-10 at 4 51 28 pm](https://cloud.githubusercontent.com/assets/4775489/16712595/9d9d77c4-46be-11e6-8cbb-1a7dbdecb3b9.png)

只清空状态，没有清空值

#### 可重现的在线演示

http://ant.design/components/form/

**Comment by afc163** [comment]
fixed in 8ec15e4ad39446189bd0982a34e0141b62cbfa51

**Comment by afc163** [comment]
Keep this open util new version published, avoiding more duplicated issue.
