### ISSUE TITLE
dva创建的项目，引入antd 定制主题时 把 style:true了， 然后menu收起后，二级菜单消失不见

### ISSUE THREAD

**Issue by jiashicheng** [ant-design/ant-design#23357]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jiashicheng/dva-antd-bug/#/](https://github.com/jiashicheng/dva-antd-bug/#/)

### Steps to reproduce
dva创建的项目，引入antd 定制主题时 把 style:true了，使用官网menu可收起demo的代码复制到项目中，  然后menu收起后，二级菜单消失不见

### What is expected?
显示二级菜单

### What is actually happening?
只显示了一个阴影

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13 |
| System | windows |
| Browser | chrome |

**Comment by jiashicheng** [comment]
https://github.com/jiashicheng/dva-antd-bug   项目demo 地址

**Comment by afc163** [comment]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/507615/80355900-3fd61000-88ab-11ea-9707-c23a3d3b062b.png">

没发现有啥问题。

**Comment by afc163** [comment]
关闭了，能重现了再打开。

**Comment by jiashicheng** [comment]
> 关闭了，能重现了再打开。

不好意思，我的demo项目上  把webpackrc里面的  style:true 改回去css了，  

["import", { "libraryName": "antd", "libraryDirectory": "es", "style": "css" }]   //  改为true

请改为  style:true   即可重现，  谢谢了

**Comment by afc163** [comment]
需要把依赖的 less 版本升级到3，roadhog 已经很久不维护了，建议用 umi 吧。

**Comment by afc163** [comment]
和 #23166 是一个问题。
