### ISSUE TITLE
Select Component

### ISSUE THREAD

**Issue by xr0master** [ant-design/ant-design#23352]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a few features request for same component.
1. Many times we need to use multi-line for Option. For example, to select city: the first line is name of city and the second line is country of this city. Or for shops: the name of shop and its address and etc. If we use the multi-line, then the selection-item looks broken.
2. allowClear doesn't allow to change its behavior. It will be nice to have the configuration to reset the value to defaultValue instead of clear at all on clear click button.

### What does the proposed API look like?
1. Probably something like this:
```js
onSelectRender = (itemInstance) => `cool text: ${itemInstance.title} : ${itemInstance.value}`
```
2. onClearMode: 'reset' | 'clear'
where 'reset' is to reset to defaultValue and 'clear' to clean up.

**Comment by zombieJ** [comment]
What's the ui look like?

**Comment by afc163** [comment]
```
<Option>
  <div>
    <div>content</div>
    <div>content</div>
    <div>content</div>
    <div>content</div>
  <div>
</Option>
```

You can try to add custom react node inside Option.

**Comment by xr0master** [comment]
I don’t have to try, I did it and it breaks selection-item. But you know, it doesn’t matter to me, I opened this feedback for you. If you no need this, just close it.

**Comment by afc163** [comment]
@xr0master Please check https://ant.design/components/select/#components-select-demo-option-label-prop

**Comment by afc163** [comment]
https://codesandbox.io/s/custom-selection-render-ant-design-demo-48s4m?file=/index.js

**Comment by xr0master** [comment]
Oh, it indeed works! Thank you for your time and I apologize.
It may be worth adding such an example to the documentation? I mean with multi-line options.

**Comment by afc163** [comment]
I believe you can learn it form https://ant.design/components/select/#components-select-demo-option-label-prop
