### ISSUE TITLE
onBlur prop of Select return empty string 

### ISSUE THREAD

**Issue by slavakam** [ant-design/ant-design#23361]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/option-group-ant-design-demo-db7n6)

### Steps to reproduce
use onBlur prop in Select

### What is expected?
we expected that e.target.value returns the this.state.value

### What is actually happening?
e.targer.value returned empty string

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | macos Catalina 10.15.3 |
| Browser | chrome |

**Comment by zombieJ** [comment]
Select is not a native html component which mean you can not get value from `onBlur`. It only promise value by `onChange` event.

**Comment by vitaliymaz** [comment]
@zombieJ, please look a little more on this issue.

onBlur gives us an event as an argument. And that is correct. But the event structure itself looks incomplete. Getting **event.target.value** returns an empty string which is not expected. It is natural to expect real value there.

Is it expected **event.target.value** to return an empty string?

Try it here
https://codesandbox.io/s/basic-usage-ant-design-demo-0rh6u?file=/index.js

**Comment by zombieJ** [comment]
Pls see my comment above. Select support `labelInValue` which means value can be `{ label: ReactNode, value: string | number }` that is not supported by natural html input component. So we do not fill the value with `target.value`. Select should always get the correct value by `onChange` event.
