### ISSUE TITLE
drawer中使用modal导致body无法滚动

### ISSUE THREAD

**Issue by KaiEi1020** [ant-design/ant-design#23362]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drawerzhongshiyongmodalzaidianjilingyigemodalguanbihou-body-wufagundong-7o023?file=/index.js)

### Steps to reproduce
 1. 点击open drawer按钮
 2. 点击抽屉中的open modal1按钮，
 3. 关闭modal1
 4. 关闭抽屉
 5. 点击open modal2按钮
 6. 关闭modal2
 7. body无法滚动

### What is expected?
body可正常滚动

### What is actually happening?
如上操作后body无法滚动

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome |

**Comment by KaiEi1020** [comment]
drawer打开时，rc-drawer下的DrawerChild的toggleScrollingToDrawerAndBody方法会将body的overflow设置为“hidden”，在modal1关闭时，switchScrollingEffect中的条件if (openCount === 1 && !Object.keys(cacheOverflow).length)成立，cacheOverflow被赋值。modal2关闭时执行了switchScrollingEffect中else if中的内容。body被设置为"overflow: hidden"。个人见解，需要修改DrawerChild的toggleScrollingToDrawerAndBody方法

**Comment by afc163** [comment]
Duplicate of #21894

**Comment by KaiEi1020** [comment]
not duplicate of #21894

**Comment by katteXu** [comment]
为什么关了 还没解决 怎么给关了呢

**Comment by swustzzh** [comment]
> 为什么关了 还没解决 怎么给关了呢

我用4.15.0也遇到了，感觉没修复，然后问题都关了

**Comment by xiaohei456** [comment]
我也遇到了 添加下面样式就解决了
html,
body {
  width: 100%;
  height: 100%;
  overflow-y: auto !important;
}
 遇到的可以试试
"antd": "^4.2.0"

**Comment by xiaohei456** [comment]
我加了下面样式解决的
html,
body {
width: 100%;
height: 100%;
overflow-y: auto !important;
}
你可以试试
"antd": "^4.2.0"

**Comment by g17628381307** [comment]
> 我加了下面样式解决的 html, body { width: 100%; height: 100%; overflow-y: auto !important; } 你可以试试 "antd": "^4.2.0"

这样会造成Drawer和Body 滚动条都会出现的呀

**Comment by LOWINC** [comment]
```js
function removeStyle() {
  const styleTags = document.getElementsByTagName('style');
  for (let i = 0; i < styleTags.length; i++) {
    const rcUtilKey = styleTags[i].getAttribute('rc-util-key');
    if (rcUtilKey?.indexOf('rc-util-locker') === 0) {
      styleTags[i].remove();
    }
  }
}

window.addEventListener('popstate', () => {
  removeStyle();
});

window.addEventListener('load', () => {
  removeStyle();
});

```

**Comment by swustzzh** [comment]
您的邮件已收到。----------------------张智慧----------------------
