### ISSUE TITLE
using generatePicker, the test fails

### ISSUE THREAD

**Issue by pnorbi-bp-grape** [ant-design/ant-design#23365]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/xiaohuoni/antd4-generate-picker/tree/master/antd-demo](https://github.com/xiaohuoni/antd4-generate-picker/tree/master/antd-demo)

### Steps to reproduce
I followed your instructions to replace moment with dayjs on the following way:
https://github.com/xiaohuoni/antd4-generate-picker/tree/master/antd-demo
1. fresh clone
2. yarn install
3. yarn test

### What is expected?
Test is successful.

### What is actually happening?
Test fails with the following error:
C:\app\test\frontend\node_modules\antd\es\date-picker\generatePicker\index.js:3
    import PickerButton from '../PickerButton';
    ^^^^^^
    SyntaxError: Cannot use import statement outside a module

      1 | import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs'
    > 2 | import generatePicker from 'antd/es/date-picker/generatePicker'
          | ^
      3 | import 'antd/es/date-picker/style/index'

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (src/components/widgets/DatePicker/DatePickerWidget.js:5:1)

Test Suites: 1 failed, 1 total

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | 80.0.3987.163 |

---
I tried several way to fix this, but no result. All other modules work normally.

**Comment by zombieJ** [comment]
@xiaohuoni

**Comment by xiaohuoni** [comment]
The main purpose of this demo is to show how to replace `moment` with `dayjs`, so the test cases brought in the new project have not been modified.
I fixed it in this [commit](https://github.com/xiaohuoni/antd4-generate-picker/commit/d223d8d522c33864cce2f660f94e96474943f373).

**Comment by pnorbi-bp-grape** [comment]
@xiaohuoni thanks for your help. It was also a problem in my application. (broken tests)
So the solution was to replace `antd/es` with `antd/lib` in the import staments like you did.
@zombieJ fyki: antd docs is still reference to the previous import statements:
https://ant.design/docs/react/replace-moment#DatePicker

**Comment by afc163** [comment]
Could changing `lib` to `es` resolve this issue too?

```diff
- import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
+ import dayjsGenerateConfig from 'rc-picker/es/generate/dayjs';
```

**Comment by pnorbi-bp-grape** [comment]
@afc163 No, only lib version works with test.

**Comment by qiwang97** [comment]
so any difference between  antd/es and antd/lib?  which one should i use for production?

**Comment by jymsy** [comment]
I use antd/lib, but date picker doesn't have customize @ant-prefix.

**Comment by nirajmchauhan** [comment]
For me as well `antd/lib` works

**Comment by AidanTu** [comment]
If you need to import from `antd/es` in your project (such as due to this problem importing from `antd/lib`: https://github.com/ant-design/ant-design/issues/29907) but still want to test the component you can workaround this error by using jest's moduleNameMapper to substitute `antd/lib` in for your jest tests by adding the following in your jest config:
```
moduleNameMapper : {
    '^antd/es/(.*)$': 'antd/lib/$1',
}
```

Obviously it would be ideal if the problem with `antd/lib` locale could be fixed so we could just use `antd/lib` and not worry about this issue but if you want multiple locales it seems you need to use `antd/es` for production currently, so the above workaround can work in the meantime. 
I thought I'd leave it here in case any others come to this issue with the same problem that I experienced where we need both multi-locale support (currently only possible by importing from `antd/es`) and unit tests.

**Comment by Kainatn** [comment]
I was also facing this issue and I resolved this issue by replacing the url
```
- import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
+  import  dayjsGenerateConfig from 'antd/node_modules/rc-picker/lib/generate/dayjs'
```

**Comment by Rohit-Alex** [comment]
> moduleNameMapper : {
>     '^antd/es/(.*)$': 'antd/lib/$1',
> }

Can you tell me where to add these lines? It would really help.

**Comment by Kainatn** [comment]
@Rohit-Alex inside **node_modules** folder  ./node_modules/@rjsf/antd/dist/es/components/DatePicker/index.js
 https://stackoverflow.com/questions/69970486/datepicker-in-antd-throwing-error-import-dayjsgenerateconfig-from-rc-picker-lib
