### ISSUE TITLE
期望 initialValues 能实时更新数据

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design#23363]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
应该大家都常常的把create 和edit 是同一个页面 ， 频繁切换create 和 edit 页面就不能很直接的更换form 的数据 ， 还有常常在modal里用用 当 频繁的编辑不同列表的数据 ， 都会得不到及时响应的编辑数据 ， 也不明白在什么时机能够优雅的实现 initialValues实时更新的效果，虽然有setFieldsValue这种辅助函数,会有警告 ，不知道在react hooks中什么时机为最佳。

### What does the proposed API look like?
提供Form实时更新Api

**Comment by yoyo837** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82

https://reactjs.org/docs/forms.html#controlled-components

在受控模式下，初始值只会在首次渲染生效，如果实时更新则表单无法编辑，被默认值锁死。

create和edit组件复用确实很常见，只需要在切换时先销毁再重新挂载同时提供新的默认值即可。

**Comment by afc163** [comment]
Modal 中可以开启 `destroyOnClose`。

**Comment by x1nGoo** [comment]
> Modal 中可以开启 `destroyOnClose`。

如果不是modal, 是页面要怎么处理? 打开页面先调用接口获取数据, 然后再用hooks setData,
initialValues要怎么赋值?

**Comment by yoyo837** [comment]
你可以 initialValues 拿到值之后 才渲染form
{initialValues && <Form }

**Comment by x1nGoo** [comment]
> 你可以 initialValues 拿到值之后 才渲染form
> {initialValues && <Form }

如果不这样, 是不是只能用setFieldsValue 操作来赋值?  
哪一种方式会比较好?

**Comment by yoyo837** [comment]
initialValues 控制form渲染 会在延迟出现UI，但 重置可以恢复到initialValues。

setFieldsValue 控制 可以及时显示UI，重置不能恢复initialValues  因为initialValues  没值。

**Comment by yoyo837** [comment]
你看配合Card loading 等控制

**Comment by x1nGoo** [comment]
> 你可以配合Card loading 等控制

明白了, 谢谢, 
我还有遇到个问题 就是用protable, 查询时 
columns 里 valueType 选择 dateTimeRange, 
{
title: '发布时间',
dataIndex: 'addTime',
valueType: 'dateTimeRange'
}
然后F12查看请求参数, 时间段的2个字段都是addTime, 这种要怎么把字段名分开?
current: 1
pageSize: 10
addTime: 2020-05-26 18:07:58
addTime: 2020-05-27 18:07:58

**Comment by yoyo837** [comment]
没明白 ，上个demo

**Comment by x1nGoo** [comment]
> 没明白 ，上个demo

https://codesandbox.io/s/antd-reproduction-template-ukpd0?file=/myList.js
把创建时间选上值, 然后点查询, 看F12 header里的参数 会有2个since字段

**Comment by follow-zy** [comment]
刚学    小白还是没看懂各位大佬说的     table 表格edit 弹出框操作  弹出框内容始终是第一点开的值   怎么实现频繁edit不同数据  form表单初始值显示正确啊？？？？

**Comment by yoyo837** [comment]
@x1nGoo 你的复现报错。

**Comment by follow-zy** [comment]
@yoyo837    
edit(row,reword){
  this.setState({
      flag:true,
      obj:{key:row.key,name:row.name},
  },()=>{
      if(this.formRef.current){
         this.formRef.current.resetFields();
      }
  })
}       大佬看看这个呐  一般情况是我这样写的嘛？  我这样写 频繁点击edit  弹框里每条数据   初始化数据显示就是对的

**Comment by yoyo837** [comment]
@follow-zy 不了解你业务本身，可以围绕antd的功能讨论。

**Comment by x1nGoo** [comment]
@yoyo837 
https://codesandbox.io/s/dumi-demo-wew39?file=/demo.tsx
