### ISSUE TITLE
table可以针对单元格增加hove或点击属性，并把单元格标红处理么？最好能对某个单元格增加回调方法。

### ISSUE THREAD

**Issue by SlimJason** [ant-design/ant-design#2336]
#### 本地环境

- antd 版本:1.1.0
- 操作系统及其版本：mac 10.6
- 浏览器及其版本:chrome 最新

#### 你做了什么？

使用table

#### 你期待的结果是：

对单元格增加特殊处理，比如标红，然后点击事件回调，把td里面内容，换成input，进行修改。

#### 实际上的结果：

无法对单元格处理

**Comment by SlimJason** [comment]
本地调试时候，有时候重新启动，npm start，css样式会加载不到，重新antd-init又好了。。。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1710
