### ISSUE TITLE
TimePicker : renderExtraFooter not working

### ISSUE THREAD

**Issue by exlame** [ant-design/ant-design#23366]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/x6sjc?file=/index.js)

### Steps to reproduce
Open on field
Click on First Ok

### What is expected?
See only one Footer
This official example should set the selected time on click

### What is actually happening?
We can see two footers
Custom Ok isn't setting the value (In official example)
![image](https://user-images.githubusercontent.com/2616347/79603472-69788580-80ba-11ea-9d60-64ca094c29fe.png)

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | 16.12.0 |
| System | CodeSandbox |
| Browser | Chrome |

**Comment by afc163** [comment]
It is render**Extra**Footer, there is no way to customize original footer now.
