### ISSUE TITLE
npm start  失败

### ISSUE THREAD

**Issue by lanxingshou** [ant-design/ant-design#2337]
#### 本地环境

- antd 版本:

- 操作系统及其版本：
win7
- 浏览器及其版本:

#### 你做了什么？
http://ant.design/docs/react/getting-started 的步骤来的，启动失败，参考https://github.com/ant-design/antd-init/issues/87

**Comment by afc163** [comment]
trace on https://github.com/ant-design/antd-init/issues/87

**Comment by Veitor** [comment]
好蛋疼，这类问题不帮我们小白解决啊？难道非要在mac下才能用？
