### ISSUE TITLE
Select Component input type

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#23375]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Can you add attribute to Select component to set the type of textbox? We have a use case where select component renders only numbers. We are using select with showSearch option. On mobile, user sees regular keyboard. We would like to restrict the user to see numeric keyboard.

### What does the proposed API look like?
<Select inputType='tel' />
Default value of input should be 'text'

**Comment by afc163** [comment]
You can try `getInputElement` to customize input element.

https://github.com/react-component/select

**Comment by mendoncanorma** [comment]
Thank you @afc163
