### ISSUE TITLE
onBlur prop of Select return empty string 

### ISSUE THREAD

**Issue by slavakam** [ant-design/ant-design#23372]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-demo-rgsez?file=/index.js )

### Steps to reproduce
https://codesandbox.io/s/vibrant-silence-b95zu?file=/index.js:0-1079 (this is antd with 3.26.15 version)
https://codesandbox.io/s/basic-usage-ant-design-demo-rgsez?file=/index.js (this is antd with 4.1.3 version)

antd with redux-form

### What is expected?
we expect that in example with 4.1.3 on Blur does not reset select value

### What is actually happening?
in the first example, onBlur does not clean select value
in second - does clean

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | your current version |
| System | ios |
| Browser | chrome |

**Comment by slavakam** [comment]
https://codesandbox.io/s/headless-sea-h2i8b?file=/src/App.js

**Comment by zombieJ** [comment]
`onBlur` in v3 return value is a bad design since user can not prevent event bubble like `preventDefault` or `stopPropagation`. In v4, it returns the origin event instead.

Let me update this in migration document.

**Comment by slavakam** [comment]
I understood that what you mean. in this example
https://codesandbox.io/s/headless-sea-h2i8b?file=/src/App.js
onBlur return event with e.target.value which we selected before, but ant component return empty string

**Comment by zombieJ** [comment]
`e.target` is the html `input` native element. It's used for accessibility usage to enable Select component has a unique focusable component and it's also used as search input box. Which value is not the Select component value.

**Comment by alexaung** [comment]
@slavakam how do you solve this issue. I am also using antd V4 with redux-form. When select dropdown is close, all selected items are gone.

**Comment by slavakam** [comment]
@alexaung we pass onBlur={() => { input.onBlur(input.value); }} prop to Select component for now

**Comment by alexaung** [comment]
> @alexaung we pass onBlur={() => { input.onBlur(input.value); }} prop to Select component for now
Hi slavakan,
I am thinking to downgrade to V3 but you saved me. Thanks

**Comment by ramavilli** [comment]
onBlur={() => { input.onBlur(input.value); }}  Not working in Antd^4.11.1 and redux form ^8.2.5
