### ISSUE TITLE
如何在4.X中关闭多列排序

### ISSUE THREAD

**Issue by aixiaobenaixiaoben** [ant-design/ant-design#23378]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
场景：服务端接口只支持单列排序，前端列表中有多个字段可排序，希望点击某个字段触发排序后，其他可排序字段都取消排序状态

### What does the proposed API look like?
在table的配置参数中增加一个multiSortable:boolean参数，当该参数为true时，column的sorter-> multiple属性失效

**Comment by afc163** [comment]
建议自行控制状态就行，开启一列排序的同时把其他列的排序状态取消。
