### ISSUE TITLE
When a non-existing Option is set as defaultValue under the Select of ant.d, the key will be shown

### ISSUE THREAD

**Issue by ishan-nibaya** [ant-design/ant-design#23374]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackoverflow.com/questions/61167919/when-a-non-existing-option-is-set-as-defaultvalue-under-the-select-of-ant-d-the](https://stackoverflow.com/questions/61167919/when-a-non-existing-option-is-set-as-defaultvalue-under-the-select-of-ant-d-the)

### Steps to reproduce
I have ant.design Select like
```
<Form.Item
 name="select_list_group"
 label="Select Group">
  <Select
   showSearch
   optionLabelProp="children"
   allowClear={true}
   notFoundContent={null}
 >
  <Option key="1" value="5e91e5add5fecf076ce7fe56" >Group One</Option>
  <Option key="2" value="5e91e563d5fecf076ce7fe55" >Group Two</Option>
  <Option key="3" value="5e91e563d5fecf076ce7fe54" >Group Four</Option>
 </Select>
</Form.Item>
```

Then I set initialValues to non-existing value like "5e91e563d5fecf076ce7fe53".
```
<Form
 ref={this.formFourFormRef}
 onFinish={onFinish}
 initialValues={{select_list_group: "5e91e563d5fecf076ce7fe53"}}
>
```

### What is expected?
I want it to be emptied.

### What is actually happening?
It shows "5e91e563d5fecf076ce7fe53".

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8.6 |
| System | Windows |
| Browser | Chrome |

**Comment by zombieJ** [comment]
It's by design. Select shows the value when option not exist. You can use `labelInValue` to customize the `label` when data is not ready.

**Comment by ishan-nibaya** [comment]
I tried with `labelInValue` but I couldn't stop appearing the value.

Will it be possible to stop showing this in an upcoming version?
![image](https://user-images.githubusercontent.com/36402202/79641094-f0108e00-81b2-11ea-9f70-f69947444133.png)

**Comment by zombieJ** [comment]
https://ant.design/components/select/#components-select-demo-label-in-value

**Comment by ishan-nibaya** [comment]
> https://ant.design/components/select/#components-select-demo-label-in-value

I did like this but this showing the ID. can you help me to fix this.

![image](https://user-images.githubusercontent.com/36402202/79679267-14578380-8222-11ea-8eeb-1789f5c6534a.png)

**Comment by ishan-nibaya** [comment]
May I put a feature request for this?

**Comment by haivx** [comment]
> > https://ant.design/components/select/#components-select-demo-label-in-value
> 
> I did like this but this showing the ID. can you help me to fix this.
> 
> ![image](https://user-images.githubusercontent.com/36402202/79679267-14578380-8222-11ea-8eeb-1789f5c6534a.png)

you need to add default label like this: `defaultValue={{ key: '4h243df8234' , label: 'Group three'}}`
