### ISSUE TITLE
Show empty when a non-existing Option is set as defaultValue.

### ISSUE THREAD

**Issue by ishan-nibaya** [ant-design/ant-design#23383]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I set a non-existing value as defaultValue, it shows the value.

![image](https://user-images.githubusercontent.com/36402202/79683174-bccb0f00-8245-11ea-9a57-1daead5a1899.png)

### What does the proposed API look like?
I want it to be emptied.

![image](https://user-images.githubusercontent.com/36402202/79683228-3e22a180-8246-11ea-9b1d-900f05a25fe7.png)

**Comment by afc163** [comment]
You can set defaultValue to `undefined` by yourself if it is not existed in options.

**Comment by ishan-nibaya** [comment]
There is another question.

I have two selects. eg: First one "Groups" and the second one "Users". 
(Second select options dynamically change.)

1. When I select a group, then the second select shows users relevant to that group.
2. Then I select a user from the second Select.
3. Afterward, I change the name of the group.
4. Then the user id will be shown automatically.

![image](https://user-images.githubusercontent.com/36402202/79685983-5a303e00-825a-11ea-92b0-782360905225.png)

**Comment by yoyo837** [comment]
You should use `SetFieldsValue` of` Form` or make it into controlled mode to reset the value of the second select.

**Comment by ishan-nibaya** [comment]
> You should use `SetFieldsValue` of` Form` or make it into controlled mode to reset the value of the second select.

My options are dynamically changing.

Can you check my code?

https://codesandbox.io/s/currying-sky-c8r5t?file=/src/App.js

**Comment by yoyo837** [comment]
How about this way? https://codesandbox.io/s/cranky-margulis-6mm77?file=/src/App.js

**Comment by ishan-nibaya** [comment]
> How about this way? https://codesandbox.io/s/cranky-margulis-6mm77?file=/src/App.js

Thank you for your kind attention. The problem in this is, for every change in the first select, the valid users are removed.

I want only non-existing option to be removed.

**Comment by yoyo837** [comment]
@ishan-nibaya I updated it, pls check it again.

**Comment by ishan-nibaya** [comment]
> @ishan-nibaya I updated it, pls check it again.

It works. Thanks.
