### ISSUE TITLE
Modal.info等静态方法支持通过config方法指定渲染容器

### ISSUE THREAD

**Issue by zetay** [ant-design/ant-design#23384]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在ShadowDOM中使用Modal.info等静态方法时可以将DOM渲染到ShadowRoot中

### What does the proposed API look like?
参照Notification或者message，提供config方法，可以指定getContainer。或者可以接收ConfigProvider传入的getPopupContainer

**Comment by afc163** [comment]
Duplicate of #23085
