### ISSUE TITLE
当父容器宽度不足时treeNode title会自动换行

### ISSUE THREAD

**Issue by johnnylc** [ant-design/ant-design#23385]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-wildflower-r6dbx?file=/index.js)

### Steps to reproduce
在示例中，父容器已经设置 overflow: auto, 但是测试节点超长仍然被自动换行。

### What is expected?
与antd 3.X版本保持一致，不需要换行，超长treeNode通过scrollbar滚动查看

### What is actually happening?
超长treeNode自动换行了

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | mac |
| Browser | Chrome 76.0.3809.132 |

---
        <TreeNode
          key={item.key}
          {...item}
          title={<span style={{whiteSpace: 'nowrap'}}>{item.title}</span>}
        />
通过使用span样式包裹title可以达到不换行且可滚动的效果：
<span style={{whiteSpace: 'nowrap'}}>{item.title}</span>
但是这样解决比较tricky。

**Comment by afc163** [comment]
> 与antd 3.X版本保持一致，不需要换行，超长treeNode通过scrollbar滚动查看

出现滚动条是 bug：#22005，换行是预期的改动。
