### ISSUE TITLE
Transfer component not clearing search text and selected values on form reset

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#23391]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-fog-6gvhd)

### Steps to reproduce
Added transfer component inside the form with reset button.

1. Enter search text inside transfer component
2. select some value and move to target
3. click on reset button

### What is expected?
1. search text should be cleared
2. Items in target section should be cleared

### What is actually happening?
1. search text not getting cleared
2. Items in target section not getting  cleared

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16 |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
Please read https://3x.ant.design/components/form/#components-form-demo-customized-form-controls and https://3x.ant.design/components/form/#this.props.form.getFieldDecorator(id,-options) for form usage.

**Comment by yakkantiraja** [comment]
Updated as per the guide line but still same issue. Able to read values when submitting but reset not clearing the selected list inside transfer component.

**Comment by yakkantiraja** [comment]
https://codesandbox.io/s/nervous-fog-6gvhd?file=/src/index.js

**Comment by yakkantiraja** [comment]
searchtext never cleared

**Comment by saresh-krish** [comment]
Hi @yakkantiraja 
How to use the required field in Transfer component in ANTD form
https://codesandbox.io/s/nervous-fog-6gvhd?file=/src/index.js
