### ISSUE TITLE
When I select an Option in Select and change Option dynamically it shows value.

### ISSUE THREAD

**Issue by ishan-nibaya** [ant-design/ant-design#23398]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-demo-gbxqx?file=/index.js)

### Steps to reproduce
I have two selects. eg: First one "Report Users" and the second one "Select User".
(Second select options dynamically change.)

1. When I select Report Users, then the second select shows users.
2. Then I select a user from the second Select.
3. Afterward, I remove the user from the first one.
4. Then the user value will be shown automatically.

![image](https://user-images.githubusercontent.com/36402202/79723938-480ada00-8304-11ea-89e8-219b904ddb02.png)

### What is expected?
I don't want to see the value.

### What is actually happening?
It shows value.

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.8.6 |
| System | Windows |
| Browser | Chrome |

**Comment by xiaobindebingo** [comment]
![image](https://user-images.githubusercontent.com/33923136/79739004-26274c80-8330-11ea-95f5-55f31f8d0324.png)
i Reproduct your link， but i cannot repeat your error，is there something wrong?

**Comment by yoyo837** [comment]
ref: #23383

**Comment by yoyo837** [comment]
Duplicated of #23383

**Comment by yoyo837** [comment]
Duplicated of #23383

**Comment by yoyo837** [comment]
Duplicated of #23383

**Comment by ishan-nibaya** [comment]
I would like ant.d team can give a good solution to this for eg jquery select2.b
