### ISSUE TITLE
table with custom component cell render empty data in one cell

### ISSUE THREAD

**Issue by yan130** [ant-design/ant-design#23396]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-77f6z?file=/index.js)

### Steps to reproduce
render the table with custom cell component but without any data 

### What is expected?
the Empty data svg should be under the table header

### What is actually happening?
the Empty data svg is in the first cell

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.12.0 |
| System | MacOS  |
| Browser | Chrome 80.0.3987.163 |

---
3.26 doesn't have this issue. We need this feature to have a more complexed cell than the one in the example

**Comment by zombieJ** [comment]
You should pass `this.props` to td component: https://codesandbox.io/s/antd-reproduction-template-77f6z?file=/index.js

**Comment by yan130** [comment]
Thanks, just add 
`colSpan={restProps.colSpan}`
in the `td` tab
