### ISSUE TITLE
DatePicker 增加校验和使用onChange回调后出现的问题

### ISSUE THREAD

**Issue by dreamcatcher081210** [ant-design/ant-design#2339]
#### 本地环境

- antd 版本:1.6.2
- 操作系统及其版本：win7 
- 浏览器及其版本:chrome : 51.0.2704.84 m

#### 你做了什么？
       ` const endDate = getFieldProps('endDate',{
            rules: [
                {required: true, message: 'end is required', type: 'date'}
            ],
            trigger:'onSelect',
            validateTrigger:'onSelect'
        });`

在Form表单里如下：
`       <DatePicker
                 {...endDate }
                 format="yyyy/MM/dd"
                 disabledDate={this.disabledStartDate}
                 onChange={this.onStartChange}
          />`

#### 你期待的结果是：

选中日期后能够在输入框显示出来

#### 实际上的结果：

相反

#### 可重现的在线演示
http://codepen.io/wytheliang/pen/OXxaAV?editors=001#anon-login

**Comment by dreamcatcher081210** [comment]
设定为onSelect事件后为什么导致整个组件都不好用了。。。

**Comment by benjycui** [comment]
http://ant.design/components/form#特别注意

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by dreamcatcher081210** [comment]
@benjycui THX The same to you!
