### ISSUE TITLE
跟着antd项目实战创建的项目，在实际开发过程中总是会把.umi下的路由文件恢复到初始

### ISSUE THREAD

**Issue by wo4558771** [ant-design/ant-design#23390]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/practical-projects-cn](https://ant.design/docs/react/practical-projects-cn)

### Steps to reproduce
例如我在添加了新的路由页面之后，或者把index.tsx文件更改为jsx文件并且在路由文件里把索引更改为index.jsx，保存完之后可以，但是其他地方一修改就会恢复成初始的状态，下面有附加图片

### What is expected?
保存实际修改的代码

### What is actually happening?
实际结果是会恢复到创建初始状态

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome73.0.3683.86（正式版本） |

![1](https://user-images.githubusercontent.com/24221012/79711903-db8bdd00-82fb-11ea-95db-54bb1ad3b1bf.jpg)
![2](https://user-images.githubusercontent.com/24221012/79711912-e0e92780-82fb-11ea-8862-82794e366104.jpg)
![3](https://user-images.githubusercontent.com/24221012/79711916-e5154500-82fb-11ea-8bc2-5e1702d3e3ac.jpg)

**Comment by yoyo837** [comment]
你试试把index写成文件夹里面再放个index.jsx？

**Comment by afc163** [comment]
不要修改 tsx 为 jsx，如果需要 js 项目，在创建的时候直接选 js 项目即可。

另外，umi 相关问题建议反馈到 umi 的 issues 区。

**Comment by wo4558771** [comment]
不好意思，以为是antd这边的问题，谢谢
