### ISSUE TITLE
Transfer component not clearing search text after reset

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#23393]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nervous-fog-6gvhd)

### Steps to reproduce
Added transfer component inside the form with Submit and reset button.

1) Enter search text inside transfer component
2) Data got filtered
3) click on reset button

### What is expected?
1) Search text should be cleared

### What is actually happening?
Search text still appears but selections got reset.

| Environment | Info |
|---|---|
| antd | 3.19.3 |
| React | 16 |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
Transfer search value cannot be controlled now, please trace #17240 for further progress.
