### ISSUE TITLE
table组件Ajax读取json数据按照文档写filter无效，官方文档其实也是无效的

### ISSUE THREAD

**Issue by Tinker404** [ant-design/ant-design#234]
看看是不是BUG

**Comment by afc163** [comment]
看网络请求，ajax 模式下的筛选排序是向后台去请求数据的。

**Comment by Tinker404** [comment]
@afc163 网络请求正常，请问一下怎么在table ajax上写筛选和排序，看官方文档有点迷惑

**Comment by afc163** [comment]
请求到后台，后台根据参数返回筛选和排序的数据，前台进行展示。

**Comment by Tinker404** [comment]
@afc163 没法像其他例子一样写吗，写不来后台的数据处理，有例子吗
