### ISSUE TITLE
CheckboxGroup getFieldProps属性问题

### ISSUE THREAD

**Issue by ChenQiWen** [ant-design/ant-design#2340]
#### 本地环境

- antd 版本:1.6.4
- 操作系统及其版本：win10
- 浏览器及其版本:chrome最新

#### 你做了什么？

给CheckboxGroup  添加了getFieldProps 绑定了onchange事件

#### 你期待的结果是：

可以正常选中 像官网一样

#### 实际上的结果：

无法正常选中 点击无法应

**Comment by dreamcatcher081210** [comment]
由于 getFieldProps 会占用 onChange 等事件（即你所设置的 trigger validateTrigger），所以如果仍需绑定事件，请更改trigger validateTrigger事件

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1353
