### ISSUE TITLE
Multiple Cascaders

### ISSUE THREAD

**Issue by codingwithswapnil** [ant-design/ant-design#23410]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/cascader/](https://ant.design/components/cascader/)

### Steps to reproduce
If I select on cascader, I need to append the selected one on top and keep one for other selection.

### What is expected?
on click on CROSS, there should be event to handle and name of cascader should be allowed to be ARRAY.

### What is actually happening?
I am adding cascaders using state but not able to delete from the state after removal of any value nor able to receive the event of that cascader.

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | react 16.10 |
| System | Windows |
| Browser | Chrome |

---
Is there any way to handle input name to be array?

**Comment by afc163** [comment]
#6674
#5026

You can try TreeSelect.

**Comment by SwapnilMWaman** [comment]
Tree select wont use Cascader. I need to use Cascader with multiple on selection of one. I am able to do that with react, but the issue is with clear / deselect. Clearing does not have any method and deselecting treats as onChange and so its binding another cascader.
![Capture](https://user-images.githubusercontent.com/20841729/79966976-d8cfea00-84ab-11ea-94e1-e077c5d6a3c6.PNG)

**Comment by ToNewDay** [comment]
同样希望支持多选。请问这个特性是在开发中吗，我是否可以提交 PR 支持该功能。

**Comment by afc163** [comment]
@ToNewDay welcome

**Comment by ToNewDay** [comment]
@afc163 work 中

**Comment by ToNewDay** [comment]
@afc163 烦请帮审阅思路： [地址](https://github.com/ToNewDay/ant-design/commits/cascader-support-multiple)

**Comment by afc163** [comment]
可以发个 PR 让 @zombieJ 跟踪 review。

**Comment by zombieJ** [comment]
@ToNewDay，可以使用 `rc-select` 的 [generate](https://github.com/react-component/select/blob/master/src/generate.tsx) 重构一下 `rc-cascader`，输入框 + 多单选 + 下拉是配套的。新版的 `rc-tree-select` 也是使用的 generate 实现的。

**Comment by ToNewDay** [comment]
> @ToNewDay，可以使用 `rc-select` 的 [generate](https://github.com/react-component/select/blob/master/src/generate.tsx) 重构一下 `rc-cascader`，输入框 + 多单选 + 下拉是配套的。新版的 `rc-tree-select` 也是使用的 generate 实现的。

好的，我研究下

**Comment by drizzlesconsin** [comment]
可以考虑支持下 [`inline`](https://rsuitejs.com/components/multi-cascader/#Inline)

**Comment by drizzlesconsin** [comment]
是否可以下考虑支持 [`inline`](https://rsuitejs.com/components/multi-cascader/#Inline)
![image](https://user-images.githubusercontent.com/69514654/132172748-68b032cc-0fa2-487f-adb3-d6c7e6a80221.png)

现在是可以设置 `open` 始终显示
```diff
<Cascader
+  open
    style={{ width: 400, height: 600 }}
    options={options}
    onChange={onChange}
    multiple
    maxTagCount="responsive"
  />
```
![image](https://user-images.githubusercontent.com/69514654/132173073-ba5210f1-d675-45c3-865d-ca6b11569a2e.png)

https://github.com/ant-design/ant-design/pull/31936

**Comment by afc163** [comment]
https://ant.design/components/cascader-cn/#components-cascader-demo-multiple
