### ISSUE TITLE
typescript antd4.0 Form 组件 ref断言

### ISSUE THREAD

**Issue by world56** [ant-design/ant-design#23415]
`class ItemsEdit extends React.Component {

    formRef = React.createRef<FormInstance>();

    render() {
        return (
            <Modal
                title='物品'
                getContainer={false}
                visible>

                <Form ref={this.formRef}>

                </Form>

            </Modal>
        );
    };

};`

不能将类型“RefObject<FormInstance>”分配给类型“((instance: FormInstance | null) => void) | RefObject<FormInstance> | null | undefined”。
  不能将类型“React.RefObject<import("d:/Web Product/Demo/arenaofvalor/arenaofvalor-admin/node_modules/rc-field-form/lib/interface").FormInstance>”分配给类型“React.RefObject<import("d:/Web Product/Demo/arenaofvalor/arenaofvalor-admin/node_modules/antd/lib/form/util").FormInstance>”。
    Type 'FormInstance' is missing the following properties from type 'FormInstance': scrollToField, __INTERNAL__ts(2322)
index.d.ts(142, 9): The expected type comes from property 'ref' which is declared here on type 'IntrinsicAttributes & FormProps & RefAttributes<FormInstance>'

我应该怎样在class组件对ref进行断言？

**Comment by world56** [comment]
react版本号： 16.13.1
antd版本号 ：  antd 4.1.4

**Comment by lyxverycool** [comment]
import { FormInstance } from 'antd/lib/form';

**Comment by nvmnghia** [comment]
My fix: 

```ts
import { FormInstance } from 'rc-field-form';
```

`FormInstance` exported by AntD extends over this, but ```rules``` props only need rc's `FormInstace`.
