### ISSUE TITLE
antd 4.0 Form  createRef 方法  断言失败

### ISSUE THREAD

**Issue by world56** [ant-design/ant-design#23417]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-dcqwv?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
class 组件 formRef = React.createRef<FormInstance>();    则提示 “不能将类型“RefObject<FormInstance>”分配给类型“((instance: FormInstance | null) => void) | RefObject<FormInstance> | null | undefined”。”

hooks 组件是不会存在这样的问题，我看了hooks的Form组件源码  function useForm(form?: FormInstance): [FormInstance]; 但是不适用calss组件。

### What is expected?
如何解决这个问题？我觉得不应该用any去代替吧？

### What is actually happening?
暂时无法解决

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | window10 |
| Browser | 谷歌浏览器 chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/unruffled-euclid-klrbr?file=/src/App.tsx

```
import { FormInstance } from "antd/lib/form/Form";
```

**Comment by aaa123123999** [comment]
formRef:any = React.createRef() 就可以了
