### ISSUE TITLE
Using filterOption with Select throws warning. Migration document needs update

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#23418]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-y588h)

### Steps to reproduce
- Add a Select component to the page
- Add filterOption that can help filter values from dropdown as you type it.
The way of using filterOption in version 3.X was to use `props` before children.
Looks like that is no more the case

```
filterOption={(input, option) =>
        option.props.children.toLowerCase().indexOf(input.toLowerCase()) >= 0
}
```

### What is expected?
No Warning should appear 

### What is actually happening?
`Warning: Return type is option instead of Option instance. Please read value directly instead of reading from `props`.`

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13 |
| System | Mac OSX |
| Browser | Safari 13,1, Chrome 80.0 |

---
This is happening because previously in version 3.X it was 
 `option.props.children.toLowerCase().indexOf(input.toLowerCase()) >= 0 `
in version 4.x we need to use
` option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0`

This is a breaking change and migration document should mention this.

**Comment by zombieJ** [comment]
This warning is by design. To avoid breaking change, we use `Object.defineProperty` to add `props` to polyfill. But I agree to mention this on the doc.
