### ISSUE TITLE
Import locale dynamically on state change

### ISSUE THREAD

**Issue by adred** [ant-design/ant-design#23413]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The language of the app I'm working on depends on the user object received from an API so I don't know in advance what locale to import. This feature request would like to add support to dynamically set the locale for `ConfigProvider` as it doesn't work currently.   

### What does the proposed API look like?
This how I wish to set locale via `useEffect` react hook. The `require` statement is just for brevity.

    const [locale, setLocale] = useState()
  
    useEffect(() => {
        const locale = require(`antd/es/locale/${language}`)
        setLocale(locale)
    }, [language])

And in the return statement

    return <ConfigProvider locale={locale}><div>Hellor World!</div></ConfigProvider>

**Comment by afc163** [comment]
Check https://ant.design/components/config-provider/#components-config-provider-demo-locale

**Comment by adred** [comment]
Hi @afc163 , I already look into the example you provided before I created the issue. The example only works if you import the locale(s) in advance, not when you dynamically import like in my example.

**Comment by adred** [comment]
Hi @afc163 if you could take a look at my codesandbox example you'll see what I mean. It's not the same as the demo provided in the documentation.

**Comment by adred** [comment]
In case someone stumbles into this, what I did was import languages that we support in a separate file like so:

    import enUS from 'antd/es/locale/en_US'
    import zhCN from 'antd/es/locale/zh_CN'
    import esES from 'antd/es/locale/es_ES'

    export const languages: {[key: string]: any} = {
        en: enUS,
        es: esES,
        zh: zhCN,
   }

**Comment by tewarig** [comment]
thanks @adred  this really helped

**Comment by EvgenBabenko** [comment]
@adred i recently faced with this question too, after investigation, i've found that import a bit not correct, correct import should looks like

`import('antd/lib/locale/en_US').then((res) => res.default)`
