### ISSUE TITLE
Automatically switch button loading state when onClick passes an asynchronous function

### ISSUE THREAD

**Issue by vimcaw** [ant-design/ant-design#23421]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When the button performs some asynchronous operations, displaying the loading animation is a good user experience, but doing so everywhere is very troublesome, which produces some boilerplate code. So we encapsulated Ant Design's `Button` component, which automatically switched the loading state according to the execution state of the `async function` when passing an `async function` to the `onClick` prop, but in a non-Typescript project, this lost the `auto-complete` of Ant Design's attribute and type. So I still hope to support this feature natively, so that more people can benefit from it.

This is a sample of my implementation:

```js
import {Button} from "antd";

export default function AsyncButton({ type, size, icon, onClick, children, ...rest }) {
  const [loading, setLoading] = useState(false);

  return (
    <Button
      type={type}
      size={size}
      icon={icon}
      loading={loading}
      onClick={e => {
        if (typeof onClick === 'function' && !loading && !rest.loading) {
          const isAsyncFunc = onClick && Object.prototype.toString.call(onClick) === '[object AsyncFunction]';
          if (isAsyncFunc) {
            (async () => {
              setLoading(true);
              try {
                await onClick(e);
                setLoading(false);
              } catch (e) {
                setLoading(false);
                throw e;
              }
            })();
          } else {
            onClick(e);
          }
        }
      }}
      {...rest}
    >{children}</Button>
  )
}
```

### What does the proposed API look like?

```js
<Button
  onClick={async () => {
    await axios.post('/posts');
  }}
>
  Auto switch Loading
</Button>
```

In the above code, an `async function` is passed to the `onClick` property, the Button will switch to the loading state when clicked, and cancel the loading state after the execution of the onClick `async function` is completed.

And provide a props `disableAsyncOnClickLoadingInfering` to disable this feature.

**Comment by afc163** [comment]
We won't add this feature, it is too much complicated.

**Comment by buhichan** [comment]
This AsyncButton is too common for all kinds of applications, why not implement it in antd?
What about an opt-in prop instead of an opt-out prop, like 'async?: boolean' ?
What about a separated component, so that we don't add complexity of Button?

**Comment by vimcaw** [comment]
I think too, its implementation is just simple.

Btw, in our team, I will always create a new Button component to replace the primitive `button` of `ant-design`, like this:

https://gist.github.com/vimcaw/32745d0ac1342fbcb53bc453be3e36cd
