### ISSUE TITLE
Table calculated wrong scroll width  when set `scroll: { x: true }`

### ISSUE THREAD

**Issue by uni-zheng** [ant-design/ant-design#23429]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/unizheng/pen/eYpdbvV](https://codepen.io/unizheng/pen/eYpdbvV)

### Steps to reproduce
Set `scroll={{ x: true, y: 300 }}` on `Table`.
Set some columns that total width is larger than table width

### What is expected?
The columns display correct width base on they set.

### What is actually happening?
The columns was shrunk.

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | latest |
| System | max os |
| Browser | chrome 80 |

---
I found the `col` element has wrong style in table header `colgroup`.

![image](https://user-images.githubusercontent.com/9986421/79822171-20c71200-83c3-11ea-942e-1f529761d63f.png)

It has correct style in table body `colgroup`

![image](https://user-images.githubusercontent.com/9986421/79822218-3805ff80-83c3-11ea-97ad-c8f557568ae7.png)

**Comment by afc163** [comment]
Try `x: 'max-content'`: https://codepen.io/unizheng/pen/eYpdbvV
