### ISSUE TITLE
SizeChanger of Pagination should hide when PageSize is set

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#23422]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/s/1zyts)

### Steps to reproduce
1. Set `pageSize` of a Pagination.
2. When total number gets large, the SizeChanger shows.
3. I don't need that SizeChanger when I already have a pageSize, not speaking that SizeChanger doesn't work if I don't set `onShowSizeChange`.

### What is expected?
Don't automatically show the SizeChanger when I already have a pageSize. 

### What is actually happening?
SizeChanger automatically shows  when I already have a pageSize, which can't work if I don't set `onShowSizeChange`.

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.12.0 |
| System | win10 |
| Browser | Google Chrome  version79.0.3945.88 |

---
The original default value `false` of `showSizeChanger` is just fine in the old version. The new default value is OK but it will be much more userfirendly if you hide the SizeChanger when pageSize is already set. So I don't have to manually set `showSizeChanger` to `false` every time I use it.

**Comment by sdhr27** [comment]
The original default value false of showSizeChanger is just fine in the old version. The new default value is OK but it will be much more userfirendly if you hide the SizeChanger when pageSize is already set. So I don't have to manually set showSizeChanger to false every time I use it.

**Comment by dengfuping** [comment]
- `pageSize` is controlled prop and variable, it's unreasonable that `pageSize` is immutable when `pageSize` is set already.

**Comment by sdhr27** [comment]
> * `pageSize` is controlled prop and variable, it's unreasonable that `pageSize` is immutable when `pageSize` is set already.

good point! That's what I am trying to express.

**Comment by afc163** [comment]
Your codesandbox is empty.

**Comment by sdhr27** [comment]
> desandbox is emp

It's a demo in your website named `Total number`：https://codesandbox.io/s/1zyts

**Comment by afc163** [comment]
It is not a bug, check https://github.com/ant-design/ant-design/pull/22711 and https://ant.design/components/table/#API

You can turn off size changer by setting `showSizeChanger={fasle}` manually.

**Comment by sajinsha9595** [comment]
Even though i set an  onSizeChange function while filtering pagination based on 10/20/50 its not working. idk why its not working.. This is the Code 

  const [pageSize, setPageSize] = useState(20);
 const [currentPage, setCurrentPage] = useState(0);

 const handlePageNumSizeClick = (current, size) => {
    setPageSize(size);
    setCurrentPage(current - 1);
  };


 <Pagination
         hideOnSinglePage={true}
        size="small"
        total={bannerCount}
        current={currentPage + 1}
        defaultPageSize={DEFAULT_PAGE_SIZE}
        onChange={handlePageNumClick}
        showSizeChanger
        onShowSizeChange={handlePageNumSizeClick}
        />
