### ISSUE TITLE
dependencies 支持正则匹配

### ISSUE THREAD

**Issue by guaijie** [ant-design/ant-design#23439]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决依赖多个其他表单项时，触发自动校验 例如： dependencies={['field','*']} 满足namePath的所有表单项变化都将触发改表单项重新校验

### What does the proposed API look like?
dependencies={['field',new RegExp()]}

**Comment by yoyo837** [comment]
一般情况下，表单互相有关联的字段都是个别，支持正则的必要性感觉没那么大。

**Comment by guaijie** [comment]
但不可否人在某些情况需要他，比如处理表格中的表单字段，每一列字段名都是一样的但为了区分，需要给表单 name 拼接成唯一一个标识name=[id, filedName]

**Comment by yoyo837** [comment]
表单项的name 本身就必须唯一，否则功能会有问题。

**Comment by guaijie** [comment]
所以正则在这里就有意义了
