### ISSUE TITLE
Table 使用Tag标签，导致fixed列样式乱了

### ISSUE THREAD

**Issue by imxiongying** [ant-design/ant-design#2343]
#### 本地环境

- antd 版本:16.4
- 操作系统及其版本：mac 10.11.5
- 浏览器及其版本: 50.0.2661.102

#### 你做了什么？

 ```
{
                title: '状态',
                dataIndex: 'status',
                width: 100,
                fixed: 'left',
                render: function (text, record, index) {
                    if ("1" === text) {
                        return  <Tag color="blue">未受理</Tag>;
                    } else if ("2" === text) {
                        return <Tag color="green">受理中</Tag>;
                    } else if ("3" === text) {
                        return <Tag color="yellow">等待回复</Tag>;
                    } else if ("4" === text) {
                        return <Tag>受理完成</Tag>;
                    } else {
                        return "";
                    }
                }.bind(this)
}

```
#### 实际上的结果：
![aaa](https://cloud.githubusercontent.com/assets/15927621/16723581/6dd58d02-4780-11e6-9630-dfe97d1554ed.png)

**Comment by benjycui** [comment]
如果你每行的行高是固定的话，可以先设定一个固定的高度来解决这个问题。

**Comment by afc163** [comment]
给个重现吧，这个问题之前修复过的。

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by imxiongying** [comment]
@afc163 
重现地址：
http://codepen.io/xiongying/pen/jAGRvx?editors=0010

**Comment by afc163** [comment]
貌似你给的演示里没有问题。

**Comment by imxiongying** [comment]
<img width="1280" alt="2016-07-12 12 06 09" src="https://cloud.githubusercontent.com/assets/15927621/16754905/0c4fce58-482a-11e6-8731-75f3916c8f00.png">

**Comment by imxiongying** [comment]
fix 列和滚动列队不齐

**Comment by afc163** [comment]
你的 x 值有点小，挤压了表头，尝试调大 x 。

**Comment by imxiongying** [comment]
调大x值确实没问题了，但开发的项目中确实有这个问题，而且项目内部也没有会影响该部分的css
<img width="709" alt="2016-07-12 3 00 26" src="https://cloud.githubusercontent.com/assets/15927621/16758118/6b437d66-4842-11e6-80e0-34265567aa7a.png">
<img width="714" alt="2016-07-12 3 00 34" src="https://cloud.githubusercontent.com/assets/15927621/16758119/6b737214-4842-11e6-8e32-0ebd44549204.png">

**Comment by afc163** [comment]
最好给出上述场景的重现。

**Comment by afc163** [comment]
对表头挤压错位的问题做了优化。

**Comment by tindytian** [comment]
我也遇到了，我把右边的的固定列的链接变成Button就对齐了
