### ISSUE TITLE
antd use rc-picker and this needs dayjs as peerDependency

### ISSUE THREAD

**Issue by deleonio** [ant-design/ant-design#23435]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
npm install antd@4.1.4

### What is expected?
dayjs as peerDependency missing

### What is actually happening?
add dayjs to antd deps

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16 |
| System | Windows |
| Browser | Chrome |

**Comment by yoyo837** [comment]
https://ant.design/docs/react/replace-moment#How-to-use-DatePicker-with-customize-date-library-like-dayjs%EF%BC%9F

**Comment by yoyo837** [comment]
@iamkun

**Comment by iamkun** [comment]
Cause dayjs is an alternative. You may have to install it manually before using it.

**Comment by afc163** [comment]
Could we drop `peerDependenecies`, it is meaningless for people don't replace moment.

**Comment by Classic-Paterson** [comment]
I don't think that this should be closed. 
We are using a [pnpm ](https://pnpm.js.org/en/3.0.0/pnpm-install#strict-peer-dependencies)with a strict peer dependency flag. Antd has a dependency on rc-picker, which requires a peer dependency on dayjs, therefore this will fail when installing Antd with the flag set:
 ```
ERROR  @rush-temp/core-ui > antd: rc-picker@1.6.1 requires a peer of dayjs@^1.8.18 but none was installed.
```

**Comment by zombieJ** [comment]
Since dayjs is singleton. Seems still need move to `peerDeps`
ref https://github.com/react-component/picker/pull/214
