### ISSUE TITLE
Tabs 组件的 nav 栏可否动态改变样式

### ISSUE THREAD

**Issue by nitta-honoka** [ant-design/ant-design#2344]
#### 本地环境

- antd 版本: 0.12.5
- 浏览器及其版本: Chrome 51.0

#### 你做了什么？

- 使用场景：使用了 Tabs 组件，现在希望能够在页面滚动一段距离后将 nav 动态切换为固定定位，并改变其 UI 样式
- 遇见的问题：API 文档中没有发现对应的变为固定定位的接口，也没找到为 nav 添加 className 的接口，所以请问一下，是否有什么途径可动态改变 nav 的样式。

**Comment by afc163** [comment]
- Affix `onChange`
- Tabs `className`
