### ISSUE TITLE
Cascader级联选择给value之后在有loadData的情况下第一次下拉选项不展开

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#23441]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-ant-design-demo-t4ccy?file=/index.js)

### Steps to reproduce
在有loadData时，第一次点击只显示第一级选项，第二次点才会正确显示三级

### What is expected?
第一次点击选项就能正确选中

### What is actually happening?
在有loadData是第一次点击不选中

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome81 |

**Comment by zhangzhi93** [comment]
有人看这个问题吗？

**Comment by afc163** [comment]
Duplicate of #16968
