### ISSUE TITLE
Modal中放Formitem，手动控制help与validateStatus参数，modal关闭时，error不消失，重新打开modal时，error一闪而过。

### ISSUE THREAD

**Issue by Chastrlove** [ant-design/ant-design#23443]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-2jxuvq?file=index.js](https://stackblitz.com/edit/react-2jxuvq?file=index.js)

### Steps to reproduce
清空输入框，触发error。点击cancel按钮，将help置为null，validateStatus置为success（antd3的版本是会将error的dom清除），modal关闭，在chrome devtool中可以看到error并没有被清除，点击open按钮，红色的error样式一闪而过。

### What is expected?
error变为不可见，或者不要一闪而过

### What is actually happening?
error没被清除，modal打开时error一闪而过

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | macOS Catalina |
| Browser | chrome 81.0.4044.92 |

**Comment by Chastrlove** [comment]
![2020-04-21 17 21 03](https://user-images.githubusercontent.com/17813559/79849157-b0d17f80-83f4-11ea-8fc0-62ca5b631c1f.gif)

**Comment by zombieJ** [comment]
窗体关闭速度比错误信息快，导致关闭信息动画来不及关闭就关闭所以触发不了 onAnimateEnd。得想想办法。

**Comment by Chastrlove** [comment]
any progress
