### ISSUE TITLE
脚手架提供了HtmlWebpackPlugin这个插件麽？

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2345]
我需要对这个插件做覆盖，或者webpark引入次插件

**Comment by benjycui** [comment]
See: https://github.com/ant-tool/atool-build/blob/master/src/getWebpackCommonConfig.js

也可以在把最终的 config 打印出来查看。

**Comment by wuhaih** [comment]
我看了，没有啊，我怎么在webpark增加一个这样的插件，会不会对内置的配置造成影响

**Comment by benjycui** [comment]
See: https://github.com/ant-tool/atool-build

最终配置以你修改之后的为准。
