### ISSUE TITLE
Add Pinterest icon

### ISSUE THREAD

**Issue by redapollos** [ant-design/ant-design#23458]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We need a Pinterest icon for several of our applications and it has not yet been added to the icon brand library.

### What does the proposed API look like?
<PinterestOutlined />

**Comment by afc163** [comment]
trace in https://github.com/ant-design/ant-design-icons/issues/71#issuecomment-617505222
