### ISSUE TITLE
Select component: Push current typed in value to the bottom of dropdown

### ISSUE THREAD

**Issue by philmetzger** [ant-design/ant-design#23459]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently when I use the Select the current input value is always on top of the dropdown. You can see an example here: https://codesandbox.io/s/dgcwn

Is there any way to push the input value to the bottom of the dropdown?

### What does the proposed API look like?
Something like inputValue="bottom" or so.

![image](https://user-images.githubusercontent.com/4325631/79913302-ab3f5e00-8423-11ea-8e85-772f666ce0c4.png)

**Comment by afc163** [comment]
We may not provide this feature but I believe you can use `onSearch` and daynamic options to make it.

**Comment by philmetzger** [comment]
No that wont work, I forced set Options to something, but somehow always what is as my input param is at the top of that list.
