### ISSUE TITLE
滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条

### ISSUE THREAD

**Issue by LTBLwhz** [ant-design/ant-design#23450]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
超长表格不分页，在windows上想要左右滑动时，需要滚动到最下面，鼠标拖动滚动条，有了辅助按钮可以在当前行 点击按钮 左右滚动

### What does the proposed API look like?
table-> scroll -> axu : [ {render:fn},{} ] //axu 辅助按钮，传入一个数组，第一个为左，第二个为右
我已在antd@3.9.4  3个 fixed table 上实现了 想要的效果
主要改动在rc-table 需要antd 新增prop校验
目前 想要在 4.0上实现同样效果
![image](https://user-images.githubusercontent.com/22017926/79863602-9efad700-840a-11ea-809a-f19234ba7937.png)

**Comment by afc163** [comment]
建议自行尝试实现，官方暂时不会提供这个交互。

**Comment by LTBLwhz** [comment]
我是想实现 实现了以后 antd会考虑合分支么

发自我的iPhone

在 2020年4月21日，下午8:29，偏右 <notifications@github.com> 写道：

﻿

建议自行尝试实现，官方暂时不会提供这个交互。

**Comment by afc163** [comment]
应该不会，交互会尽可能只保持推荐的一种。

**Comment by LTBLwhz** [comment]
OK 我了解了

谢谢

在 2020年4月21日，下午8:33，偏右 <notifications@github.com> 写道：

﻿

应该不会，交互会尽可能只保持推荐的一种。

**Comment by QianDingwei** [comment]
想请教一下，超长表格不分页，在windows上想要左右滑动时，需要滚动到最下面才能出现横向滚动条，有可能在表格一出先，就有横向滚动条嘛，而不是等到滚动到最下面才出现

**Comment by yoyo837** [comment]
@QianDingwei 表格有没有横向滚动条 和纵向滚动到什么位置没关系吧？

**Comment by QianDingwei** [comment]
主要是现在的横向滚动条，只有在table拉到最下面，横向滚动条才会展现。当横向数据比较多，纵向数据也比较多，就得先拉到最下面，然后再拉横向。以下面这个例子为例：https://codesandbox.io/s/antd-reproduction-template-go4p4
你需拉倒最下面，才能显示横向滚动条，有办法解决吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;; 
发送时间: 2020年4月24日(星期五) 中午11:34
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "1370336125"<1370336125@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)





 
@QianDingwei 表格有没有横向滚动条 和纵向滚动到什么位置没关系吧？

**Comment by yoyo837** [comment]
动态 max-height #21584

**Comment by yoyo837** [comment]
也就是 动态 y

**Comment by LTBLwhz** [comment]
我的这个交互正是为了解决这个问题

谢谢

在 2020年4月24日，上午11:40，Charles <notifications@github.com> 写道：

﻿

主要是现在的横向滚动条，只有在table拉到最下面，横向滚动条才会展现。当横向数据比较多，纵向数据也比较多，就得先拉到最下面，然后再拉横向。以下面这个例子为例：https://codesandbox.io/s/antd-reproduction-template-go4p4
你需拉倒最下面，才能显示横向滚动条，有办法解决吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;;
发送时间: 2020年4月24日(星期五) 中午11:34
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "1370336125"<1370336125@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;;
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)






@QianDingwei 表格有没有横向滚动条 和纵向滚动到什么位置没关系吧？

**Comment by LTBLwhz** [comment]
而且 我已经在4.0的基础上实现了我提出的效果，
相对于之前  rc-table 7.0使用了hooks 和其他sticky实现 添加这个功能 犹如探囊取物，还不会影响之前的dom结构和性能

谢谢

在 2020年4月24日，上午11:40，Charles <notifications@github.com> 写道：

﻿

主要是现在的横向滚动条，只有在table拉到最下面，横向滚动条才会展现。当横向数据比较多，纵向数据也比较多，就得先拉到最下面，然后再拉横向。以下面这个例子为例：https://codesandbox.io/s/antd-reproduction-template-go4p4
你需拉倒最下面，才能显示横向滚动条，有办法解决吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Amumu"<notifications@github.com&gt;;
发送时间: 2020年4月24日(星期五) 中午11:34
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "1370336125"<1370336125@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;;
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)






@QianDingwei 表格有没有横向滚动条 和纵向滚动到什么位置没关系吧？

**Comment by QianDingwei** [comment]
想问一下如何解决的(详细一点的，最好有源码啦)，或者有没有更好的解决办法



---原始邮件---
发件人: "light"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 中午11:44
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Charles"<1370336125@qq.com&gt;;
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)




 而且 我已经在4.0的基础上实现了我提出的效果， 
 相对于之前  rc-table 7.0使用了hooks 和其他sticky实现 添加这个功能 犹如探囊取物，还不会影响之前的dom结构和性能 
 
 谢谢 
 
 在 2020年4月24日，上午11:40，Charles <notifications@github.com&gt; 写道： 
 
 ﻿ 
 
 主要是现在的横向滚动条，只有在table拉到最下面，横向滚动条才会展现。当横向数据比较多，纵向数据也比较多，就得先拉到最下面，然后再拉横向。以下面这个例子为例：https://codesandbox.io/s/antd-reproduction-template-go4p4 
 你需拉倒最下面，才能显示横向滚动条，有办法解决吗 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Amumu"<notifications@github.com&amp;gt;; 
 发送时间: 2020年4月24日(星期五) 中午11:34 
 收件人: "ant-design/ant-design"<ant-design@noreply.github.com&amp;gt;; 
 抄送: "1370336125"<1370336125@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;; 
 主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450) 
 
 
 
 
 
 
 @QianDingwei 表格有没有横向滚动条 和纵向滚动到什么位置没关系吧？

**Comment by LTBLwhz** [comment]
就是我提的这个feture

谢谢

在 2020年4月24日，上午11:47，Charles <notifications@github.com> 写道：

﻿

想问一下如何解决的(详细一点的，最好有源码啦)，或者有没有更好的解决办法



---原始邮件---
发件人: "light"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 中午11:44
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Charles"<1370336125@qq.com&gt;;
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)




而且 我已经在4.0的基础上实现了我提出的效果，
相对于之前 rc-table 7.0使用了hooks 和其他sticky实现 添加这个功能 犹如探囊取物，还不会影响之前的dom结构和性能

谢谢

在 2020年4月24日，上午11:40，Charles <notifications@github.com&gt; 写道：

﻿

主要是现在的横向滚动条，只有在table拉到最下面，横向滚动条才会展现。当横向数据比较多，纵向数据也比较多，就得先拉到最下面，然后再拉横向。以下面这个例子为例：https://codesandbox.io/s/antd-reproduction-template-go4p4
你需拉倒最下面，才能显示横向滚动条，有办法解决吗




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人: "Amumu"<notifications@github.com&amp;gt;;
发送时间: 2020年4月24日(星期五) 中午11:34
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&amp;gt;;
抄送: "1370336125"<1370336125@qq.com&amp;gt;; "Mention"<mention@noreply.github.com&amp;gt;;
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)






@QianDingwei 表格有没有横向滚动条 和纵向滚动到什么位置没关系吧？

**Comment by yoyo837** [comment]
动态y值就是方案。源码肯定你自己写，监控windows.resize， 计算表格剩余可滚动空间，y值响应变化就可以了。上面那个PR 就是完成这个事，但是还在确认中，未合并，你可以自己实现。

**Comment by QianDingwei** [comment]
好的，谢谢



---原始邮件---
发件人: "Amumu"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 中午11:49
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Charles"<1370336125@qq.com&gt;;
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)




 
动态y值就是方案。源码肯定你自己写，监控windows.resize， 计算表格剩余可滚动空间，y值响应变化就可以了。上面那个PR 就是完成这个事，但是还在确认中，未合并，你可以自己实现。

**Comment by QianDingwei** [comment]
好的谢谢



---原始邮件---
发件人: "light"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 中午11:49
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Charles"<1370336125@qq.com&gt;;
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)




 就是我提的这个feture 
 
 谢谢 
 
 在 2020年4月24日，上午11:47，Charles <notifications@github.com&gt; 写道： 
 
 ﻿ 
 
 想问一下如何解决的(详细一点的，最好有源码啦)，或者有没有更好的解决办法 
 
 
 
 ---原始邮件--- 
 发件人: "light"<notifications@github.com&amp;gt; 
 发送时间: 2020年4月24日(周五) 中午11:44 
 收件人: "ant-design/ant-design"<ant-design@noreply.github.com&amp;gt;; 
 抄送: "Mention"<mention@noreply.github.com&amp;gt;;"Charles"<1370336125@qq.com&amp;gt;; 
 主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450) 
 
 
 
 
 而且 我已经在4.0的基础上实现了我提出的效果， 
 相对于之前 rc-table 7.0使用了hooks 和其他sticky实现 添加这个功能 犹如探囊取物，还不会影响之前的dom结构和性能 
 
 谢谢 
 
 在 2020年4月24日，上午11:40，Charles <notifications@github.com&amp;gt; 写道： 
 
 ﻿ 
 
 主要是现在的横向滚动条，只有在table拉到最下面，横向滚动条才会展现。当横向数据比较多，纵向数据也比较多，就得先拉到最下面，然后再拉横向。以下面这个例子为例：https://codesandbox.io/s/antd-reproduction-template-go4p4 
 你需拉倒最下面，才能显示横向滚动条，有办法解决吗 
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 
 发件人: "Amumu"<notifications@github.com&amp;amp;gt;; 
 发送时间: 2020年4月24日(星期五) 中午11:34 
 收件人: "ant-design/ant-design"<ant-design@noreply.github.com&amp;amp;gt;; 
 抄送: "1370336125"<1370336125@qq.com&amp;amp;gt;; "Mention"<mention@noreply.github.com&amp;amp;gt;; 
 主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450) 
 
 
 
 
 
 
 @QianDingwei 表格有没有横向滚动条 和纵向滚动到什么位置没关系吧？

**Comment by QianDingwei** [comment]
想问一下该如何解决呢



---原始邮件---
发件人: "Amumu"<notifications@github.com&gt;
发送时间: 2020年4月24日(周五) 中午11:42
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"Charles"<1370336125@qq.com&gt;;
主题: Re: [ant-design/ant-design] 滑动表格新交互(windows):hover行新增左右辅助按钮，可以供使用者绑定新交互，如点击控制横向滚动条 (#23450)




 
也就是 动态 y

**Comment by LTBLwhz** [comment]
![image](https://user-images.githubusercontent.com/22017926/80174887-967ee800-8626-11ea-8a64-0b86889e1d07.png)

**Comment by NookyPOP** [comment]
@ThenMorning 您好，出现左右箭头的是antd 那个版本的，目前我看到的4.13.1版本没有

**Comment by ThenMorning** [comment]
> @ThenMorning 您好，出现左右箭头的是antd 那个版本的，目前我看到的4.13.1版本没有

是我自己的实现，可以参考这2个分支
![image](https://user-images.githubusercontent.com/22017926/112795942-d6064d80-909b-11eb-976a-245b8562ab2c.png)
