### ISSUE TITLE
官网在IE11下卡顿

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#23463]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/steps/#components-steps-demo-vertical-small](https://ant.design/components/steps/#components-steps-demo-vertical-small)

### Steps to reproduce
浏览

### What is expected?
normal

### What is actually happening?
卡顿

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | latest |
| System | windows 10 |
| Browser | IE11 |

---
把浏览器弄崩溃

**Comment by hengkx** [comment]
![bug](https://user-images.githubusercontent.com/8358236/79931442-9db6c200-847d-11ea-8688-61a8144b8dc6.gif)
鼠标滚轮一直在动，浏览器cpu占用很高

**Comment by afc163** [comment]
官网暂时不会对 IE 做优化，如果具体组件有问题，欢迎提 issue。
