### ISSUE TITLE
用Form.List的时候，想初始化时，显示两条数据

### ISSUE THREAD

**Issue by woaiwuchihan** [ant-design/ant-design#23460]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在用Form.List组件的时候，我想初始化的时候，默认显示多条数据并赋值。请问该如何实现，是通过

### What does the proposed API look like?
能够提供一个配置项，来配置初始化显示条目的。

**Comment by yoyo837** [comment]
给个例子 帮你改改？

**Comment by woaiwuchihan** [comment]
Form.List一开始默认是没有数据，只能通过添加按钮一条条添加。但我想实现一个页面，初始的时候会有几条数据，这几条数据要显示出来。并且可以删除。我试着在FORM中添加fields并赋值，但Form.List中遍历的fields还是空

**Comment by woaiwuchihan** [comment]
> 给个例子 帮你改改？
Form.List一开始默认是没有数据，只能通过添加按钮一条条添加。但我想实现一个页面，初始的时候会有几条数据，这几条数据要显示出来。并且可以删除。我试着在FORM中添加fields并赋值，但Form.List中遍历的fields还是空

**Comment by yoyo837** [comment]
用 https://codesandbox.io/s/antd-reproduction-template-6e93z 做个demo

**Comment by woaiwuchihan** [comment]
> 用 https://codesandbox.io/s/antd-reproduction-template-6e93z 做个demo
找到了，在FORM里面用initialValues={{tags: fetchedFields}}，可以给Form.List中的fields设置初始值

**Comment by gametheworld** [comment]
> 用https://codesandbox.io/s/antd-reproduction-template-6e93z做个演示

你TM看明白他问的问题了么？

**Comment by yoyo837** [comment]
> > 用[https://codesandbox.io/s/antd-reproduction-template-6e93z做个演示](https://codesandbox.io/s/antd-reproduction-template-6e93z%E5%81%9A%E4%B8%AA%E6%BC%94%E7%A4%BA)
> 
> 你TM看明白他问的问题了么？

那请问你TM看明白我说的什么了么？我让他用初始案例做个demo我好给他改，他自己找到方法了，管你TM什么事？

**Comment by blackcatpolice** [comment]
哈哈哈哈哈，楼上俩大哥，解决问题还上头了呢

**Comment by zhaoqiqang199** [comment]
> 哈哈哈哈哈，楼上俩大哥，解决问题还上头了呢

这个黄头像的看了几个issues他一直很上头
