### ISSUE TITLE
为什么当前需要验证的文本框在获取光标的时候报错？

### ISSUE THREAD

**Issue by cnv587** [ant-design/ant-design#2347]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

#### 可重现的在线演示
![qq 20160711200225](https://cloud.githubusercontent.com/assets/13713580/16729954/8fc06d52-47a2-11e6-9610-c79487185f99.jpg)

**Comment by cnv587** [comment]
这是我从官方复制的代码

**Comment by codering** [comment]
这个是因为你用了最新的react造成了，已经在修复了 https://github.com/ant-design/ant-design/issues/2332

**Comment by afc163** [comment]
ref #2335
