### ISSUE TITLE
ant-design 所有产品的文档站点能不能搭建一下国内镜像，这已经不是第一次出现了，照顾一下翻墙困难的开发者。

### ISSUE THREAD

**Issue by admiao** [ant-design/ant-design#23472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
正常浏览文档

### What does the proposed API look like?
能正常浏览文档

**Comment by joyshion** [comment]
@admiao https://ant-design.gitee.io/

**Comment by admiao** [comment]
> @admiao https://ant-design.gitee.io/

谢谢

**Comment by afc163** [comment]
Duplicate of #21353

**Comment by xhwgood** [comment]
> @admiao https://ant-design.gitee.io/

404，地址迁移了？

**Comment by yoyo837** [comment]
能访问啊

**Comment by xhwgood** [comment]
> 能访问啊

这地址神了，之前我真不能访问，但现在居然又可以了

**Comment by afc163** [comment]
gitee 不是很稳定，刚才我手动触发了重新部署。

**Comment by xrkffgg** [comment]
ant-design 国内镜像地址：https://github.com/ant-design/ant-design/issues/25661
