### ISSUE TITLE
[v4] Upload - fileList undefined error when beforeUpload return false

### ISSUE THREAD

**Issue by CarolineBoyer** [ant-design/ant-design#23487]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload/#components-upload-demo-avatar](https://ant.design/components/upload/#components-upload-demo-avatar)

### Steps to reproduce
Since upgrading to 4.0, Upload implemented as following doesn't work when having already an avatar, and wishing to change.
I followed this demo tutorial : https://ant.design/components/upload/#components-upload-demo-avatar with little change as I don't upload here but latter on.

```javascript
export class Uploader extends React.Component<IUploaderProps, IUploaderState> {

    constructor(props: IUploaderProps) {
        super(props);
        this.state = {
            isLoading: false,
            imgUrlInBase64: ''
        }
    }

    getBase64(img: Blob | File): void {
        const reader = new FileReader();
        reader.readAsDataURL(img);
        const that = this;
        reader.addEventListener("load", function () {
            that.setState({
                imgUrlInBase64: (this.result != null) ? this.result.toString() : ''
            })
        }, false);

    }

    normalizingFileUpload = (event: any) => {
        if (Array.isArray(event)) {
            return event;
        }
        return event && event.fileList;
    };

    render() {
        const {imgUrlInBase64, isLoading} = this.state;
        let avatarSrc;
        if (imgUrlInBase64 != '') {
            avatarSrc = imgUrlInBase64
        } else if (this.props.preLoadedImg != '') {
            avatarSrc = this.props.preLoadedImg
        } else {
            avatarSrc = undefined
        }

        const uploaderProps: UploadProps = {
            name: 'avatar',
            listType: "picture-card",
            showUploadList: false,
            accept: "image/*",
            beforeUpload: (file: (File | Blob)) => {
                const checkingSizeIsLessThan2M = file.size / 1024 / 1024 < 2;
                if (!checkingSizeIsLessThan2M) {
                    message.error('This file is too heavy.')
                } else {
                    this.getBase64(file);
                }
                return false;
            }
        };
        return (
            <Row>
                <Col span={24}>
                    <Form.Item
                        wrapperCol={{offset: 9}}
                        name='avatar'
                        valuePropName='fileList'
                        getValueFromEvent={this.normalizingFileUpload}
                        rules={[
                            {
                                required: true,
                                message: 'This cannot be empty'
                            },
                        ]}
                    >
                        <Upload {...uploaderProps}>
                            <Avatar
                                size={84}
                                icon={ imgUrlInBase64 != '' ? null : isLoading ? <LoadingOutlined/> : <UploadOutlined />}
                                src={avatarSrc}
                            />
                        </Upload>
                    </Form.Item>
                    <Text type="secondary"><BulbOutlined/>I only accept images smaller than 2Mb.</Text>
                </Col>
            </Row>
        );
    }
}
```

### What is expected?
in 3.0, this scenario would work:
1> Clicking on the upload opens  the file dialog
2> Choosing a file (image less than 2MB) triggers the preview of it ( upload is done later through form) (by parsing to base64 and putting it in the src param of Avatar entity)
3> If there is already an image that had been uploaded before, clicking will reopen the file dialog.
4> Choosing a second file will replace the preview of it
5> Submitting form will upload avatar-base-64-string

### What is actually happening?
in 4.0, step 4> isn't working any more. I feel something has changed in the way Upload.js is writter as this error shows up in console :

```bash
Upload.js:234 Uncaught TypeError: stateFileList.concat(...).forEach is not a function
    at Object.Upload._this.beforeUpload (Upload.js:234)
    at AjaxUploader.upload (AjaxUploader.js:122)
    at AjaxUploader.js:90
    at Array.forEach (<anonymous>)
    at AjaxUploader._this.uploadFiles (AjaxUploader.js:89)
    at AjaxUploader._this.onChange (AjaxUploader.js:41)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:306)
```

When looking at said code, fileList is a state variable of the Upload component. In my case, it should only be [] or [one single file]. Should I give this as a props to my Upload component like API says (did it become mandatory to have a fileList)  ? How would that work in my case?

What would be the fix here ?

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | react 16 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by CarolineBoyer** [comment]
For those who will come here after, issue was coming from the fact that my redux action was giving me back from DB a string and not a file.
Therefore this piece of code :
```javascript
valuePropName='fileList'
                        getValueFromEvent={this.normalizingFileUpload}
```
from the Form.Item was triggering the issue shown in first message.

Removing the getValueFromEvent and changing the valuePropName to 'file' seem to have done the deed.

I am not sure I understand why though....

**Comment by IslaMurtazaev** [comment]
@CarolineBoyer Thanks a lot, bumped into the same issue

**Comment by olustrrax** [comment]
@CarolineBoyer When I changed valuePropName to 'file' it seem work for me. Thank you!

**Comment by kodie** [comment]
This fixed my issue but now the only problem is that setting the initial value of the upload component isn't working.

```
defaultFileList: [
    {
      uid: '1',
      name: 'xxx.png',
      status: 'uploading',
      url: 'http://www.baidu.com/xxx.png',
      percent: 33,
    }
  ]
```

That doesn't work with valuePropName set to `file`. I've also tried removing the encapsulating array to just make it a single object but that doesn't work either.
