### ISSUE TITLE
请教一下，form表单中使用Slider组件，如何在onAfterChange事件才触发表单值的改变

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design#23481]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/form-cn/#header](https://3x.ant.design/components/form-cn/#header)

### Steps to reproduce
请教一下，form表单中使用Slider组件，如何在onAfterChange事件才触发表单值的改变，
在表单的onValuesChange回调事件监听值并触发事件。
在getFieldDecorator里面添加了trigger: 'onAfterChange'就无法改变表单里面的值

### What is expected?
表单里的Slider组件在onAfterChange事件之后，才改变表单的值，
而不是在拖动的时候实时改变

### What is actually happening?
拖动的时候实时改变

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | mac |
| Browser | 谷歌 |

---
希望表单里的Slider组件，在拖动停止之后，才触发onValuesChange的事件

**Comment by hengkx** [comment]
Form Item trigger

https://ant.design/components/form/#API

**Comment by afc163** [comment]
你可以封装一个 XxxxSlider，内部逻辑自行改成 onAfterChange 时才触发 onChange，然后把这个 XxxxSlider 放在 Form 里，可以参考自定义表单组件：https://3x.ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by z-lionel** [comment]
> 你可以封装一个 XxxxSlider，内部逻辑自行改成 onAfterChange 时才触发 onChange，然后把这个 XxxxSlider 放在 Form 里，可以参考自定义表单组件：https://3x.ant.design/components/form-cn/#components-form-demo-customized-form-controls

好的，谢谢！
