### ISSUE TITLE
JavaScript evaluation error: 'ReferenceError: colorPalette is not defined

### ISSUE THREAD

**Issue by baldarian** [ant-design/ant-design#23480]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/baldarian/antd-issue-demonstration](https://github.com/baldarian/antd-issue-demonstration)

### Steps to reproduce
Run `npm run get-vars`

### What is expected?
Basically I'm trying to get the values of less variables and put them into a javascript. I found a snippet of code somewhere that allows to do that, but it seems doesn't work with the current version of antd. Can you please checkout the codebase and see how can I fix it ?

### What is actually happening?
I'm getting the following error when running `npm run get-vars`

JavaScript evaluation error: 'ReferenceError: colorPalette is not defined

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | MacOS 10.15.03 |
| Browser | Chrome 81 |

**Comment by afc163** [comment]
I know little about less vars extract functions, you have to dig yourself or seek help in less community.

**Comment by afc163** [comment]
Hopfully you can resolve it and share here.
