### ISSUE TITLE
Please let me know how to make the basic example of tree select(https://3x.ant.design/components/tree-select/#header) to incorporate search box in input box same like multiple select

### ISSUE THREAD

**Issue by habeebahmed** [ant-design/ant-design#23486]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Please let me know how to make the basic example of tree select(https://3x.ant.design/components/tree-select/#header) to incorporate search box in input box same like multiple select
This feature is there in v4 but lacks in version 3 
I want to know whether search box can be inline for basic single select usage
![image](https://user-images.githubusercontent.com/36078669/79958969-285ce880-84a1-11ea-843f-489c9f21de49.png)

### What does the proposed API look like?
I think adding an option to toggle search box inline or in dropdown can work

**Comment by afc163** [comment]
TreeSelect search box is same as Select search box in v4. We won't support search input in dropdown now.

**Comment by habeebahmed** [comment]
@afc163 I was talking about v3 where I can get searchbox inline just as like tree select in v4
I can't upgrade to v4 due to dependency 
So I think v3 won't have that feature

V4 tree select 
![image](https://user-images.githubusercontent.com/36078669/79962094-43c9f280-84a5-11ea-8056-5b191216bf95.png)

V3 tree select
![image](https://user-images.githubusercontent.com/36078669/79962171-5d6b3a00-84a5-11ea-9fe9-24ab2ee4034f.png)

my requirement is to make searchbox similar to V4 in V3

**Comment by afc163** [comment]
@habeebahmed It is hard to make same search input as TreeSelect in v4 without upgrading, I don't know how either.

**Comment by afc163** [comment]
That is why we change it in a major version.

**Comment by habeebahmed** [comment]
@afc163 okay thanks for your time
