### ISSUE TITLE
【Tree】Customize collapse/expand icon

### ISSUE THREAD

**Issue by hankaibo** [ant-design/ant-design#23491]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Expand and collapse are two states. Using one icon is not good enough.

### What does the proposed API look like?
collapseIcon(ReactNode)
expandIcon(ReactNode)

**Comment by afc163** [comment]
`switcherIcon`

**Comment by WisestCoder** [comment]
Why close this issue?
How should i use different icon on expand and collapse?
