### ISSUE TITLE
TreeSelect的showCheckedStrategy属性设置TreeSelect.SHOW_ALL还是不显示父节点？

### ISSUE THREAD

**Issue by liangchaofei** [ant-design/ant-design#23493]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kegouxuan-ant-design-demo-jggul)

### Steps to reproduce
选择子节点，value不显示父节点

### What is expected?
选择子节点，value显示父节点

### What is actually happening?
选择子节点，value不显示父节点

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | MAC |
| Browser | Chrome |

**Comment by CraiGZero** [comment]
I also encountered the same problem。

**Comment by CraiGZero** [comment]
如果你紧急的话，我可以提供一个临时的解决办法：
给TreeSelect指定一个新属性（例如name）,使name=你想要展示的值，
然后在TreeSelect使用treeNodeLabelProp=‘name’

https://stackblitz.com/edit/react-2kcpmz

**Comment by liangchaofei** [comment]
> https://stackblitz.com/edit/react-2kcpmz

这个没有解决吧？

**Comment by zombieJ** [comment]
`showCheckedStrategy` 对应的是 `treeCheckable`，开启了就行了：
<img width="529" alt="截屏2020-05-18 下午5 56 08" src="https://user-images.githubusercontent.com/5378891/82199866-dc328600-9930-11ea-9223-8614c60bda0e.png">

**Comment by Terry-cjgu** [comment]
这个问题没解决啊也，怎么closed 了呢？

**Comment by LiuYnag** [comment]
SHOW_PARENT和SHOW_ALL两个参数填写完没效果啊，treeCheckable这个属性开启页不行呀，为啥会关了这个bug

**Comment by williamwang2013** [comment]
我的问题类似，我已通过后台方式处理解决。
我的环境是react+ ant design 3.26.7，要实现给菜单树赋权的效果，用treeselect ,
  <TreeSelect
              style={{ width: '100%' }}
              dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
              treeData={roleTreeList}
              treeCheckable="true"
              showCheckedStrategy={SHOW_ALL}
              placeholder="请设置菜单权限"
              onChange={onTreeChange}
            />,
假设某个1级菜单目录-系统管理下，有3个子菜单，用户管理、角色管理、菜单管理，用treeselect赋权时，我只选了用户管理和角色管理2个子菜单，实际上的treeselect values中应该要包含父级菜单系统管理的id的，但是因为系统管理下的3个子菜单没有全部选中，即使 showCheckedStrategy={SHOW_ALL}，在获取treeselect value时是拿不到系统管理的key值的。
我通过后台来解决的，我的解决方式如下：
    1.前台没办法通过组件来拿到系统管理的key值，前台传值不变
    2.后台拿到前台传过来的所有key值，递归查找所有父节点后，跟前台传值做并集后做唯一值筛选。这样保证可以拿到所有前台漏掉的父节点值。入库时的数据不会有问题
    3.这样会导致一个新问题出现，就是由于系统管理父节点的值入库了，在treeselect上明明应该是只显示系统管理和用户管理、角色管理两个子菜单的，但是如果从库里面拿数据的话，系统管理的key默认也是选中的，会变成了系统管理下的3个子菜单都是选中的状态
    4. 第3步中的问题我是这么处理的，数据库中存入了系统管理的节点id,但是在treeselect绑定values值时，过滤掉这些父节点的key值，具体sql类似如下，我这里是角色赋权，在角色创建时指定角色有权限操作的菜单树。角色表上加一个字段menuCheckStrictly，默认为true。然后入库时父节点key值即使入库，再取数据库值绑定到treeselect时，由于角色menuCheckStrictly为true，会过滤掉这些父节点key值。
    
        select m.menu_id
		from sys_menu m
            left join sys_role_menu rm on m.menu_id = rm.menu_id
        where rm.role_id = #{roleId}
            <if test="menuCheckStrictly">
              and m.menu_id not in (select m.parent_id from sys_menu m inner join sys_role_menu rm on m.menu_id = rm.menu_id and rm.role_id = #{roleId})
            </if>
		order by m.parent_id, m.order_num
     整个操作，已经测试成功，基本达到我的要求。
