### ISSUE TITLE
Table组件固定列、表头后CSS样式问题

### ISSUE THREAD

**Issue by siminture** [ant-design/ant-design#23492]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns](https://ant.design/components/table-cn/#components-table-demo-fixed-columns)

### Steps to reproduce
1、打开官网Table组件
2、滚动页面到内容【固定头和列】，找到对应的Table组件演示
3、把浏览器窗口宽度调整窄方便横向滚动，建议900px左右
4、用鼠标横向滚动表格，注意观察表头“Action”右边，竖向滚动条上方位置，会有1个px宽度、1个字体行高左右的透明区域，导致表头的文字、等有颜色的内容在滚动时会穿过这块。

### What is expected?
修复样式问题

### What is actually happening?
修复样式问题

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | react |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
我这里无法重现。

**Comment by siminture** [comment]
![antd-table-scrolling-issue](https://user-images.githubusercontent.com/1584380/80207620-0ca04080-8661-11ea-815b-8f2134b837c6.gif)

![antd-table-issue](https://user-images.githubusercontent.com/1584380/80207716-3fe2cf80-8661-11ea-9e18-d503d409f90f.png)

补上图片

**Comment by siminture** [comment]
不知为啥GITHUB上图片显示不出来，我上传到其它地方：

http://56xyy.com/files/antd-table-scrolling-issue.gif

http://56xyy.com/files/antd-table-issue.png

**Comment by imhxc** [comment]
这是 chromium 的一个 BUG，但是至今都没有被解决。
我能想到的办法就是 `left: 0` 修改为 `left: -1px`，但我不认为这是一个好的办法。

**Comment by afc163** [comment]
Chrome 的渲染问题，antd 这边没什么好办法。
