### ISSUE TITLE
导航菜单收缩时，默认不能显示全部

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#23500]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
导航菜单收缩时，默认不能显示全部，需要滚动鼠标，才能显示，用户体验不好
![QQ浏览器截图20200422204818](https://user-images.githubusercontent.com/3166799/79983917-05e7c100-84db-11ea-9d96-15d0a2732471.png)
![QQ浏览器截图20200422204848](https://user-images.githubusercontent.com/3166799/79983922-07b18480-84db-11ea-8d2f-4489a7d089d9.png)

**Comment by Kermit-Xuan** [comment]
你的第二张图里面，如果再多几个菜单项，还是展示不下，居中的方法，指标不治本，先保持现状。
