### ISSUE TITLE
Table expandIcon used together with onRow-onClick causes side-effects

### ISSUE THREAD

**Issue by icaroponce** [ant-design/ant-design#23502]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/intelligent-chandrasekhar-1yhtj?file=/index.js)

### Steps to reproduce
click on the expand icon and see in the logs that `onClick` is also being triggered, which doesn't happen when `expandIcon` isn't set.

### What is expected?
`onClick` shouldn't be triggered in the case of clicking in the expand icon, because if `onClick` triggers an action like showing a modal, that will happen even if the user only wants to expand the row.

### What is actually happening?
when using `expandIcon`, `onClick` shouldn't be triggered if the user only clicks the icon. As it happens using the default icon, (not setting a custom `expandIcon`)

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13 |
| System | Archlinux 5.5.13-arch1-1 |
| Browser | Chromium Version 80.0.3987.149 |

**Comment by afc163** [comment]
You need to add `e.stopPropagation();` manually: https://codesandbox.io/s/sharp-cohen-s7exu
