### ISSUE TITLE
RangePicker calendar icon is not clickable.

### ISSUE THREAD

**Issue by achillescs** [ant-design/ant-design#23503]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/3kwvm)

### Steps to reproduce
1. Click the calendar icon in the RangePicker component.

### What is expected?
Date range window should open.

### What is actually happening?
Date range window is not opening.

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.11.0 |
| System | Ubuntu |
| Browser | Chrome 80.0.3987.122  |

---
Calendar icon is clickable in DatePicker but is not working in RangePicker.

**Comment by zombieJ** [comment]
Rule of RangePicker icon:
* Do nothing if already open
* Open first if first enabled
* Open second

**Comment by MakarovAV** [comment]
Unfortunately, the suggested solution does not work for me, cause neither the rangepicker itself nor the suffixIcon does not seem to react on onClick event.

Am I missing something here?
