### ISSUE TITLE
Select tokenSeparators 设置无效

### ISSUE THREAD

**Issue by coy9** [ant-design/ant-design#23514]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidongfenci-ant-design-demo-r6tci?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/zidongfenci-ant-design-demo-r6tci?file=/index.js

### What is expected?
正常 数据分割 a@b

### What is actually happening?
a,b

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | ^16.8.6 |
| System | mac |
| Browser |  81.0.4044.122 |

**Comment by afc163** [comment]
出现了什么问题？

**Comment by coy9** [comment]
![image](https://user-images.githubusercontent.com/23191825/80061002-93babf00-8562-11ea-9bb5-888208b8fc56.png)
![image](https://user-images.githubusercontent.com/23191825/80061043-aa611600-8562-11ea-9e37-272be7cb824c.png)
期望数据 a@b@c@d 实际是a,b,c,d

**Comment by afc163** [comment]
还是不理解，你最好写一个手把手的操作步骤。

**Comment by coy9** [comment]
https://codesandbox.io/s/zidongfenci-ant-design-demo-r6tci?file=/index.js
![image](https://user-images.githubusercontent.com/23191825/80064000-b3a1b100-8569-11ea-839b-e16f850f4a2c.png)

**Comment by afc163** [comment]
`tokenSeparators` 只是接受输入的，对实际的 value 数组无影响，你可以拷贝 `aa@bb@cc` 到 Select 里试试。
