### ISSUE TITLE
ie11下报错，缺少标识符 script1010 非常紧急，因为你们使用了.default字段

### ISSUE THREAD

**Issue by JinJieTan** [ant-design/ant-design#23510]
这里应该是引用了antd的组件 然后
![image](https://user-images.githubusercontent.com/47209029/80054707-9dd4c180-8552-11ea-874a-8dee2fe7f841.png)
![image](https://user-images.githubusercontent.com/47209029/80054712-a4633900-8552-11ea-8f05-43e7edc289fa.png)

**Comment by JinJieTan** [comment]
我是4.0.0的antd版本

**Comment by yoyo837** [comment]
不是这个问题

**Comment by JinJieTan** [comment]
我取消引入antd，这个问题就消失了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Amumu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 中午11:19
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"Peter"<453089136@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] ie11下报错，缺少标识符 script1010 非常紧急，因为你们使用了.default字段 (#23510)





 
不是这个问题

**Comment by yoyo837** [comment]
我说的是“不是default”的问题，问题由antd引入，去掉当然消失。

**Comment by hengkx** [comment]
try `react-app-polyfill`

**Comment by JinJieTan** [comment]
好的~&nbsp;谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tom Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 中午11:26
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"Peter"<453089136@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] ie11下报错，缺少标识符 script1010 非常紧急，因为你们使用了.default字段 (#23510)





 
try react-app-polyfill

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/80056054-dfb33700-8555-11ea-9fc3-00a4d8063fea.png)

https://ant.design/docs/react/getting-started-cn#%E5%85%BC%E5%AE%B9%E6%80%A7

**Comment by JinJieTan** [comment]
嗯，这里引入是没有配置按需加载，然后直接手动按需引入的&nbsp;


//&nbsp;import&nbsp;Spin&nbsp;from&nbsp;'antd/es/spin'
//&nbsp;import&nbsp;'antd/es/spin/style/index.css'


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Amumu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 中午11:24
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"Peter"<453089136@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] ie11下报错，缺少标识符 script1010 非常紧急，因为你们使用了.default字段 (#23510)





 
我说的是“不是default”的问题，问题由antd引入，去掉当然消失。
