### ISSUE TITLE
Cannot stopPropagation keypress event inside dropdown overlay

### ISSUE THREAD

**Issue by thnt** [ant-design/ant-design#23518]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/type-ant-design-demo-bkmfy)

### Steps to reproduce
1. Click Button to show Input
2. Type a space in the Input

### What is expected?
Input (dropdown overlay) keep showing

### What is actually happening?
Dropdown overlay was hidden because of onClick event of Button was triggered

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.x |
| System | Any |
| Browser | Any |

**Comment by afc163** [comment]
Try https://codesandbox.io/s/type-ant-design-demo-c55w9?file=/index.js

**Comment by thnt** [comment]
You put my overlay outside of button, that is not what i want.
