### ISSUE TITLE
v4自定义validator怎么使用debounce

### ISSUE THREAD

**Issue by Clago** [ant-design/ant-design#23517]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-d9y64?file=/index.js)

### Steps to reproduce
如何使用lodash的debounce防止抖动

### What is expected?
如何去写debounce

### What is actually happening?
Warning: `callback` is deprecated. Please return a promise instead.
_.debounce包裹成promise直接运行不了。

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome |

---
不是什么错误报告，发上来请教下，不知道如何去写。

**Comment by afc163** [comment]
这样写代码应该是工作的：https://codesandbox.io/s/antd-reproduction-template-yold0?file=/index.js

1. warning 的问题不太好处理，现在做了[一些判断](https://github.com/react-component/field-form/blob/09b570a75c529aa514dc256f67b36ece6bca9264/src/utils/validateUtil.ts#L156)，被 debounce 过就不准确了。
2. codesandbox 里遇到 `new Error()` 界面直接弹出报错了，应该是 codesandbox 的问题，本地看完全正常。

**Comment by Clago** [comment]
不行，测试直接异常报错。目前我还是尽量不用ajax远程验证吧。希望后续表单验证能考虑远程验证。

**Comment by afc163** [comment]
> 不行，测试直接异常报错。

我本地测试时没问题的。

**Comment by lilywang711** [comment]
> > 不行，测试直接异常报错。
> 
> 我本地测试时没问题的。

我点击 codesandbox 也是不行的，输入后，直接页面抛出异常，没有友好的显示异常。如图
![image](https://user-images.githubusercontent.com/17040010/91680591-4983c300-eb7e-11ea-887d-3e36e9bab761.png)

**Comment by ourfeel** [comment]
debounce 过后， 验证步频和 debounce的result 不对应。 
如果在async func 里调用 callback。 由于后期返回的promise 都是fulfilled状态， 又不会触发callback
