### ISSUE TITLE
树下拉选择控件触发事件问题

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2351]
当设置了多选属性时，是否支持全部勾选完成下拉弹出层消失后再触发事件，onChange跟onSelect都是勾选了就马上触发回调函数了

**Comment by warmhug** [comment]
可以考虑增加`onDropdownVisibleChange` api

**Comment by warmhug** [comment]
升级 rc-tree-select 到最新

**Comment by aw6658913** [comment]
我更新到最近的 是在rc-tree-select的js里是有看到onDropdownVisibleChange这个属性，这个属性好像是一个方法，那参数嘞，open？我看官网的API还没更新出来

**Comment by warmhug** [comment]
使用示例：http://react-component.github.io/tree-select/examples/basic.html
![image](https://cloud.githubusercontent.com/assets/2011119/17127931/bf431d3c-533b-11e6-801f-5f5a75aaea0b.png)
