### ISSUE TITLE
How can I remove highlighting/box shadow when focused/active of select box

### ISSUE THREAD

**Issue by habeebahmed** [ant-design/ant-design#23521]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/condescending-night-lfn2v?file=/index.css)

### Steps to reproduce
- click on drop down 
- It shows highlight on box

### What is expected?
- I want to remove the highlight from the box
- the only way I see is by removing classes 'ant-select-open ant-select-focused' but I guess that's not possible
- I added outline none and box-shadow none still no difference

### What is actually happening?
- It displays box shadow

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.0.0 |
| System | latest |
| Browser | latest |

**Comment by afc163** [comment]
There is a `box-shadow` to override.

**Comment by habeebahmed** [comment]
@afc163 can you please check the code sandbox and let me know exactly where....?
and is it supposed to be on :focus or :active ?

**Comment by afc163** [comment]
<img width="765" alt="image" src="https://user-images.githubusercontent.com/507615/80070615-cc17c880-8575-11ea-97c2-474aad61af17.png">

**Comment by habeebahmed** [comment]
@afc163 thanks
