### ISSUE TITLE
Input.Password点击显示密码input焦点问题

### ISSUE THREAD

**Issue by yaeSakuras** [ant-design/ant-design#23524]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-otgjo)

### Steps to reproduce
输入密码，然后点击显示密码

### What is expected?
焦点保持不变

### What is actually happening?
焦点跑到input框最前面去了

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | mac os  |
| Browser | chrome 81 |

**Comment by huntdream** [comment]
Is anyone working on this issue? I'd like to have a try
