### ISSUE TITLE
树下拉选择控件去掉勾选能触发onSelect事件，但直接点击“x”删除已勾选选项无法触发onSelect事件

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2352]

**Comment by warmhug** [comment]
请尽量使用`onChange`事件代替 onSelect。  
select 事件是 tree-select 中 tree 的事件，点x删除是选择框里的事件，不是一回事，也做不到一致。

**Comment by aw6658913** [comment]
那这样的话我是要如何知道点了‘x’删除操作和删除了哪个选项呢？

**Comment by warmhug** [comment]
根据点击的 value ，查找数据。

**Comment by aw6658913** [comment]
onChange事件获取到的value是当前已选择的value，当去掉勾选时value是剩下勾选的选项而非当前我删除的value，难道我要定义一个参数去记录上次的value然后触发onChange的时候再去进行对比查找吗？这样好像不大合理

**Comment by warmhug** [comment]
onChange 回调里的第三个参数里的`triggerValue`，是你需要的。

**Comment by aw6658913** [comment]
我看API文档只有一个value属性，请问你这个是哪里看的？

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/16828884/81f42aa8-49c6-11e6-8ea8-55a964ad938f.png)
API上写的是三个参数

**Comment by encorehe** [comment]
最新的 没有onChange事件啊
