### ISSUE TITLE
dropdown menu is fixed to the screen while scrolling the table which is having virtual list

### ISSUE THREAD

**Issue by sai78** [ant-design/ant-design#23534]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/virtual-list-ant-design-demo-60rtb?file=/index.js)

### Steps to reproduce
Give height to the Table.Use virtual list to scroll the elements of the Table. Add filters to any column.

### What is expected?
Ideally drop-down menu should not be fixed to screen while scrolling the Table

### What is actually happening?
drop-down menu is fixed to the screen while scrolling

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.8 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by afc163** [comment]
trace https://github.com/ant-design/ant-design/issues/29366
