### ISSUE TITLE
Clicking select icon doesn't trigger open

### ISSUE THREAD

**Issue by c316** [ant-design/ant-design#23537]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select/](https://ant.design/components/select/)

### Steps to reproduce
Go to the Select component example on the ant.design page. Try to open the select dropdown by pressing the "^" icon. 

### What is expected?
The dropdown should open when pressing the "^" icon. 

### What is actually happening?
The select component isn't opened. 

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | MacOS 10.15.4 |
| Browser | Version 1.7.98 Chromium: 81.0.4044.113 (Official Build) (64-bit) |

---
Issue gif https://www.dropbox.com/s/ob4kxi1eerkfgyg/Select%20issue.gif

**Comment by QianDingwei** [comment]
same as you .you ant update 4.1.4 when you are build, reset to 4.1.3 is find

**Comment by yoyo837** [comment]
Duplicated of #23546
