### ISSUE TITLE
Cascader slow performance on opening after selected path

### ISSUE THREAD

**Issue by ivaylopetrovdev** [ant-design/ant-design#23530]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-mwng3)

### Steps to reproduce
1. get at least 6-7 levels deep (check the console to have at least something like: ["item1", "item10", "item100", "item1000", "item10000", "item100000", "item1000000"]). 
2. click outside of the Cascader (so it can close)
3. click on the input of the Cascader (to get it open again)

### What is expected?
As ALL options are already there (not created on the fly), Cascader to open IMMEDIATELY with selected options (ones from Step 1) 

### What is actually happening?
It takes 4-5 seconds to see the Cascader opened with selected options. 

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | macOS Mojave 10.14.6 |
| Browser | Chrome 80.0.3987.163 |

---
I hit this issue by using large set of lazy loaded data in my project (each level has between 5 and 500 options). I was unpleasantly surprised by this issue, after I had read the Cascader's documentation (https://ant.design/components/cascader/), that says:

When To Use#
- When you need to select from a set of associated data set. Such as province/city/district, company level, things classification.
- When selecting from a large data set, with multi-stage classification separated for easy selection.
- Chooses cascade items in one float layer for better user experience.

I need a solution to resolve this performance issue as the Cascader component will be used with a heavy and fast usage. Please help/fix that performance issue so UX can be the best!

**Comment by ivaylopetrovdev** [comment]
来自保加利亚的问候
你能帮助我吗？

---
ブルガリアからのご挨拶
手伝って頂けますか？

**Comment by ivaylopetrovdev** [comment]
Still not even 1 response? What a community!

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by Kermit-Xuan** [comment]
I find the reason may be `monitorResize` in `rc-align`, and the default value of `monitorBufferTime` is `0`.

So i want to add `popupAlignMonitorBufferTime` prop in `rc-trigger` to control `monitorResize` of `rc-align`, it's OK?


![1](https://user-images.githubusercontent.com/33770367/82239018-be821280-996a-11ea-8771-18c6659d7a47.png)

**Comment by Kermit-Xuan** [comment]
After tracing, I found that the biggest reason for consuming performance is that too much option data leads to a very large number of dom. In your example, I expanded the level of 5 to 6 and found that the number of dom node in the menu reached about 8,000, and because of the in `cascader` we used `rc-align`, it will observe child elements in the menu to align the menu with the target element, so when the dom node is more, this will also consume a lot of performance

@afc163, Do we consider using virtual lists to implement `rc-cascader`  to improve performance?

**Comment by afc163** [comment]
YES, Cascader is one of visual list component we planed to do.

**Comment by afc163** [comment]
搞了个夏令营活动：#24353

**Comment by afc163** [comment]
trace in #24353

**Comment by ivaylopetrovdev** [comment]
Hello, any progress on this issue? I can see that all relevant tickets are closed. Does it means that this bug wont be fixed? My project needs this fix as we are on production at the moment and it's is causing serious issues!

**Comment by kliuj** [comment]
请问已经好了吗，用的最新版4.18.9，还是非常卡。

**Comment by ROTGP** [comment]
Asking again in 2022, is there any progress on this issue? It seems that TreeSelect is performant and uses virtual scrolling, whereas the Cascader (which is very similar) does not use virtual scrolling, and freezes when using many elements. This is a real shame as the Cascader is a fantastic component, however the performance issue means I can't use it.

**Comment by pinocchio126** [comment]
Cascader doesn't help me with performance issues right now，When will virtual scrolling be added，I take this very seriously.

**Comment by tyn1998** [comment]
Hello guys, it seems the [Cascader](https://ant-design.antgroup.com/components/cascader-cn) component still does not support virtual scrolling to decrease the amount of DOM nodes to be rendered. I also kindly ask you to improve the performance, thank you ❤️
