### ISSUE TITLE
The tree table also displays expand icons when children are empty arrays

### ISSUE THREAD

**Issue by Codevers** [ant-design/ant-design#23544]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
An empty array is a common scenario, no need to convert to null

### What does the proposed API look like?
```js
{
name:'1',
children:[]
}
```
Expand icon is not displayed

**Comment by afc163** [comment]
Duplicate of #1365
