### ISSUE TITLE
Fatal exception thrown when tooltip is shown after upgrading to antd 4.1.4

### ISSUE THREAD

**Issue by whenmoon** [ant-design/ant-design#23541]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/basic-ant-design-demo-jk4qn?file=/index.js

### Steps to reproduce
https://ant.design/components/tooltip/

### What is expected?
Tooltip to be shown. This was working in ant design version 3.x

### What is actually happening?
This exception is thrown:
```
Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Tooltip._this.onPopupAlign (index.js:149)
    at Popup._this.onAlign (Popup.js:87)
    at Align.js:77
    at trigger (useBuffer.js:12)
    at Object.forceAlign (Align.js:152)
    at Popup.<anonymous> (Popup.js:79)
    at callCallback (react-dom.development.js:12490)
    at commitUpdateQueue (react-dom.development.js:12511)
    at commitLifeCycles (react-dom.development.js:19858)
    at commitLayoutEffects (react-dom.development.js:22803)

react-dom.development.js:19527 The above error occurred in the <Popup> component:
    in Popup (created by Trigger)
    in Portal (created by Trigger)
    in Trigger (created by ForwardRef(Tooltip))
    in ForwardRef(Tooltip) (created by Context.Consumer)
    in Tooltip (created by HCTooltip)
    in div (created by storyFn)
    in div (created by storyFn)
    in storyFn
    in ErrorBoundary

```

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | OSX 10.14.5 |
| Browser | Chrome Version 81.0.4044.113  |

**Comment by whenmoon** [comment]
Here is a reproducible demo of the bug: https://codesandbox.io/s/basic-ant-design-demo-jk4qn?file=/index.js

**Comment by whenmoon** [comment]
> Hello @whenmoon. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @whenmoon, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

Here is a reproducible demo of the bug: https://codesandbox.io/s/basic-ant-design-demo-jk4qn?file=/index.js

**Comment by whenmoon** [comment]
This function on line 141 of antd > lib > tooltip > index.js always returns `undefined:
```
var placement = Object.keys(placements).filter(function (key) {  
return placements[key].points[0] === align.points[0] && placements[key].points[1] === align.points[1];
      })[0]; // 根据当前坐标设置动画点

**Comment by LuJiaNan** [comment]
少了个容错处理。`if(placement){ return; }`

**Comment by LuJiaNan** [comment]
少了个容错处理
![2DRV DR0 WPSPB_%7(IRK)S](https://user-images.githubusercontent.com/16320772/80552710-11b31600-89fa-11ea-8bde-7aabb5ddc09b.png)

**Comment by LuJiaNan** [comment]
好像少了个容错处理。`if(!placement){ return; }`
