### ISSUE TITLE
DatePicker控件单独使用时size="small"是ok的，但是与form一起使用时会出现样式冲突，导致显示有误

### ISSUE THREAD

**Issue by lanll** [ant-design/ant-design#2354]
运行下面代码就可以看到了：
```
const { DatePicker, Form } = antd;
const RangePicker = DatePicker.RangePicker;
const FormItem = Form.Item;

const App = React.createClass({
  render() {
    return (
      <div style={{margin: 10}}>
        <RangePicker size="small"/><br>
        <DatePicker size="small"/>
        <Form horizontal className="ant-advanced-search-form">
          <FormItem>
             <RangePicker size="small"/>
          </FormItem>
          <FormItem>
             <DatePicker size="small"/>
          </FormItem>
        </Form>
      </div>
    );
  }
});

ReactDOM.render(<App />, document.getElementById('container'));
```

应该是以下的样式影响到了（className="ant-advanced-search-form"）：
.ant-advanced-search-form .ant-input, .ant-advanced-search-form .ant-input-group .ant-input, .ant-advanced-search-form .ant-input-group .ant-input-group-addon
 {
    height: 28px;
}

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by lanll** [comment]
我不知道要怎么添加链接进来
麻烦你们运行下一下代码：就可以看到效果了
const { DatePicker, Form } = antd;
const RangePicker = DatePicker.RangePicker;
const FormItem = Form.Item;

const App = React.createClass({
  render() {
    return (
      <div style={{margin: 10}}>
        <RangePicker size="small"/><br>
        <DatePicker size="small"/>
        <Form horizontal className="ant-advanced-search-form">
          <FormItem>
             <RangePicker size="small"/>
          </FormItem>
          <FormItem>
             <DatePicker size="small"/>
          </FormItem>
        </Form>
      </div>
    );
  }
});

ReactDOM.render(<App />, document.getElementById('container'));

**Comment by RaoHai** [comment]
看了下是 `ant-advanced-search-form` 吧 .ant-input 的高度统一设置成 28px 了。 

高级搜索的表单控件是不支持 size=small 的。

你可可以尝试去掉 `ant-advanced-search-form` 的 className 

如果一定要使用高级搜索的表单，也不要设置 size 。
