### ISSUE TITLE
Select component at 4.1.4 cant't be opened when user directly clicks the Arrow.

### ISSUE THREAD

**Issue by IcebearDL** [ant-design/ant-design#23546]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/select-cn/](https://ant-design.gitee.io/components/select-cn/)

### Steps to reproduce
1. Enter the ant official website. Choose the select component.
2. Select component cant't be opened when user directly clicks the little Arrow.

### What is expected?
Wherever user click at the select, the select component can be opened.

### What is actually happening?
Select component cant't be opened when user directly clicks the little Arrow.

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.12.10 |
| System | window 10 |
| Browser | Chrome 版本 75.0.3770.100（正式版本） （64 位） |

---
When the select is short, the problem becomes more obvious which looks like a bug.

**Comment by afc163** [comment]
Fixed in #23448, will be released in this week.
