### ISSUE TITLE
第一次调用Form.resetFields()不会生效，第二次调用才会生效。

### ISSUE THREAD

**Issue by huxiany** [ant-design/ant-design#23551]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaodanfangfadiaoyongclass-component-ant-design-demo-cg5hk?file=/index.tsx)

### Steps to reproduce
1.进入界面后点击Reset按钮，结果是只清除了this.state.note的值，但未清除form中note的值；
2.再次点击Reset按钮，即可清除form中note的值。

备注：在form中设置了initialValues={{ note: s.note }}，在我们的应用场景中需要把note保存在this.state中，之前使用andt3.x版本也是同样的方式，本次升级至4.x版本，修改了默认值设置方式后就出现了这个问题。

目前找到一个解决方案，但觉得不太合适：
使用this.formRef.current.setFieldsValue({ note: undefined }); 替代  this.formRef.current.resetFields(); 

### What is expected?
请帮忙确认是4.x的bug还是不支持这种用法？ 

### What is actually happening?
急需答案~等待您的回复！

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | win10 |
| Browser | Google Chrome |

**Comment by afc163** [comment]
不是 bug，`resetFields` 是重置回 `initialValues`，而 `initialValues` 只有第一次 render 会生效，你可以参考理解一下现在的行为。

**Comment by RianMan** [comment]
我也遇到这个问题了，怎么解决呢？？
```
this.formRef.current.resetFields()
this.setState({pageNum: 1, pageSize: 10})
this.handleSetData({
  pageNum: 1,
  pageSize: 10
})
```
列表重新渲染了，但是搜索框内的值还是在哪，再点击下才可以

**Comment by komorebi-cqd** [comment]
直接用formRef身上的setFieldsValue设置一下就行
