### ISSUE TITLE
Table组件pageSize由大到小选择后报`dataSource` length is less than `pagination.total` but large than `pagination.pageSize`

### ISSUE THREAD

**Issue by xlieee** [ant-design/ant-design#23554]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wf4im)

### Steps to reproduce
1、选择20/page
2、选择10/page

### What is expected?
没有warning

### What is actually happening?
不影响结果，但产生了warning

| Environment | Info |
|---|---|
| antd | 4.1.3 |
| React | react |
| System | windows |
| Browser | 谷歌81.0.4044.92 |

**Comment by afc163** [comment]
官方例子需要再优化优化。

**Comment by fenglijunnb** [comment]
@xlieee 请问一下，那你这个问题最后是怎么解决的呢

**Comment by joi-joe-joy** [comment]
I have the same problem

**Comment by shaodushu** [comment]
I have the same problem too

**Comment by xlieee** [comment]
> @xlieee 请问一下，那你这个问题最后是怎么解决的呢

可以时使用unstable_batchUpdate,或者不要分开更新Table的属性

**Comment by xlieee** [comment]
@fenglijunnb 
可以时使用unstable_batchUpdate,或者不要分开更新Table的属性

**Comment by fenglijunnb** [comment]
@xlieee 那具体是怎么使用的呢，我这个不太清楚，大佬

**Comment by jibenziliao** [comment]
![image](https://user-images.githubusercontent.com/12134347/97654299-95c78280-1a9d-11eb-879d-9b0b096cddab.png)

**Comment by ccloveak** [comment]
I have the same problem too
![image](https://user-images.githubusercontent.com/38686314/99487743-5f00d000-29aa-11eb-853d-187b2ca19990.png)

**Comment by mixj93** [comment]
Same problem

**Comment by xgqfrms** [comment]
Haiyaaaa! 坑

**Comment by UnicornXU** [comment]
最后解决了么

**Comment by RosApr** [comment]
how to fix it

**Comment by twoheartliu** [comment]
same problem

**Comment by Leioy** [comment]
still exists

**Comment by chengshaohui** [comment]
"antd": "^4.17.0" still exists

**Comment by LBH1314** [comment]
"antd": "^4.17.0-alpha.0" still exists

**Comment by chengshaohui** [comment]
"antd": "^4.17.2" still exists

**Comment by SilentFlute** [comment]
#https://github.com/ant-design/pro-components/issues/3436#issuecomment-984439793

**Comment by SilentFlute** [comment]
贴一个我自己的解决方法供大家参考: #https://github.com/ant-design/pro-components/issues/3436#issuecomment-984439793

**Comment by Bian2017** [comment]
"antd": "^4.17.2" still exists

**Comment by MCZhanHong** [comment]
same problem

**Comment by mac-boss** [comment]
目前仍然存在

**Comment by lhbDesign** [comment]
现在还有啊，有没有解决办法呢？
