### ISSUE TITLE
antd RangePicker value属性为undefined时候 不受控，与3.x行为不一致

### ISSUE THREAD

**Issue by Chastrlove** [ant-design/ant-design#23553]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-zm2umc-53jndf?file=package.json](https://stackblitz.com/edit/react-zm2umc-53jndf?file=package.json)

### Steps to reproduce
选择任意一个时间段

### What is expected?
当传入undefined时，组件受控，无法更改value

### What is actually happening?
当传入undefined时，并不是受控组件

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | macOS Catalina |
| Browser | chrome 81.0.4044.92 |

---
antd 3x并没有这个问题

**Comment by zombieJ** [comment]
v3 部分组件设置 `undefined` 受控是实现问题。v4 组件都按照原生组件规范，如果是 `undefined` 就是非受控。

ref #21839

**Comment by Chastrlove** [comment]
> v3 部分组件设置 `undefined` 受控是实现问题。v4 组件都按照原生组件规范，如果是 `undefined` 就是非受控。
> 
> ref #21839

https://codesandbox.io/s/frosty-wind-m3505-pdgxv  即便setState设为undefined也无法将rangePicker重置。只有设置为[]才会被重置

**Comment by Chastrlove** [comment]
@zombieJ

**Comment by zombieJ** [comment]
👌 我修一下~
