### ISSUE TITLE
在treeselect中使用input(不带前后缀)，无法聚焦

### ISSUE THREAD

**Issue by njmqd** [ant-design/ant-design#23559]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-ant-design-demo-fye5p?file=/index.js)

### Steps to reproduce
(1) 打开treeselect下拉框
(2)点击input

### What is expected?
input获得焦点

### What is actually happening?
下拉框关闭

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | mac 10.14.5 |
| Browser | Chrome 81.0.4044.122 |

**Comment by njmqd** [comment]
之前修过带前后缀的类似bughttps://github.com/ant-design/ant-design/issues/22881

**Comment by zombieJ** [comment]
TreeSelect 点击 Item 会触发选中逻辑，如果不需要它触发包一层阻止掉即可：
https://codesandbox.io/s/jibenshiyong-ant-design-demo-g1ntc?file=/index.js

PS：建议调整一下交互，TreeSelect or Select 本身就是一个输入组件，输入组件选项嵌套输入是很怪异的交互。
