### ISSUE TITLE
TreeNode blink when draggable switch

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#23558]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/white-monad-4g91o?file=/index.js)

### Steps to reproduce
Click switch button

### What is expected?
No blink

### What is actually happening?
Blink

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | latest |
| System | IOS |
| Browser | chrome |

**Comment by afc163** [comment]
Closing it because 3.x is not maintianed any more.
