### ISSUE TITLE
开源精神难能可贵，ant cool什么时候开放给外部使用

### ISSUE THREAD

**Issue by and80506** [ant-design/ant-design#2355]
#### 期望的结果是：

ant cool可下载使用

#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/1769410/16758709/e56c4480-4845-11e6-8506-6e5f9285d6ba.png)

**Comment by afc163** [comment]
暂时没有时间表，服务对外开放是一件比较麻烦的事，后续可能会考虑开放 sketch 文件，欢迎持续关注。
