### ISSUE TITLE
Modal can't open when 'forceRender' is true

### ISSUE THREAD

**Issue by Rain-1214** [ant-design/ant-design#23563]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/guojihua-ant-design-demo-k788g?file=/index.js)

### Steps to reproduce
click button.

### What is expected?
show the modal.

### What is actually happening?
only show mask,

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | deepin 15.11 |
| Browser | 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 |

---
I don't know it's a bug or a feature.I want to update some state when modal is hidden and 'forceRender' is 'true'.I also want to lazy to render modal by myself. and then it can't open.... if this question is a bug,i think the issue maybe at [this line](https://github.com/react-component/dialog/blob/65214b9696936879d2ea446d7ae8c4ea34c5b00f/src/Dialog.tsx#L87)
--------------------------
英语实在不怎么样，抱歉。大概场景就是需要在Modal关闭或者还未打开的时候更新一些Modal中的组件或子组件，但是我也希望他有一个lazyload的过程，所以我自己希望自己维护它的load行为。但是就打不开了...

**Comment by afc163** [comment]
直接去掉 `forceRender={true}` 会有什么问题？

**Comment by Rain-1214** [comment]
因为在我们的场景里面用户打开了Modal填写完了表单并点击确定之后，会打开另外一个Modal来预览本次操作的变更项，这个时候用户可以确认提交，也可以取消返回。如果用户确认提交并请求成功，这个时候我需要重置表单以及一些其他操作，但是这个时候那个表单的Modal的visible为false，forceRender也没有传,以Modal中的(lazy行为)[https://github.com/react-component/dialog/blob/65214b9696936879d2ea446d7ae8c4ea34c5b00f/src/LazyRenderBox.tsx#L15]这个时候他的 shouldComponentUpdate 会返回 false,Modal的children的所有的useEffect 就都不会执行。。

**Comment by afc163** [comment]
`forceRender={!lazy}` ?

**Comment by Rain-1214** [comment]
感觉可行。感谢大佬。但是总觉得跟forceRender这个语义渐行渐远。。那这个问题我就关了。
