### ISSUE TITLE
Tree loadData 异步加载数据 虚拟滚动的高度计算错误导致目录树一部分被隐藏

### ISSUE THREAD

**Issue by wangdanting** [ant-design/ant-design#23569]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yibushujujiazai-ant-design-demo-ml5p7?file=/index.js:987-997)

### Steps to reproduce
1. 我把setTimeout的1000 换成了100 后
2. 你把这些目录都展开，你会发现后面的节点被遮挡了。

### What is expected?
1. 虚拟滚动的loadData异步加载后高度计算正确

### What is actually happening?
Tree loadData 异步加载数据 虚拟滚动的高度计算错误导致目录树一部分被隐藏
![image](https://user-images.githubusercontent.com/16220538/80206631-407a6680-865f-11ea-8348-54caae2ec185.png)
![image](https://user-images.githubusercontent.com/16220538/80206660-4ff9af80-865f-11ea-9373-dfc7028a2a29.png)

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome |

**Comment by zombieJ** [comment]
虚拟滚动的 bug。

**Comment by zombieJ** [comment]
Update: 
发现不是虚拟滚动的 bug。
Tree 展开元素在用户可视的范围外被 Chrome 优化跳过了动画阶段，从而它不会触发 `onAnimateEnd` 事件，导致 Tree 永远在等待动画而无法解除虚拟滚动的同步锁。
需要改进 `rc-animate` 让它即便不触发真实动画也能强制刷新结束事件。
