### ISSUE TITLE
steps style in compact theme

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#23565]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/steps-cn/#components-steps-demo-vertical](https://ant.design/components/steps-cn/#components-steps-demo-vertical)

### Steps to reproduce
- 垂直方向上，紧凑模式使用了 small
- ant-steps-item-tail 距离边界 12px了
- RTL 模式下 未处理
### What is expected?
- 12px

### What is actually happening?
- 16px

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | The latest |
| System | mac |
| Browser | chrome |

---

你在 compact 中处理了 ant-steps-item-tail 

![image](https://user-images.githubusercontent.com/29775873/80199948-8120b280-8654-11ea-8784-17fa170717af.png)

我不太清楚你这个加在哪了，你直接 处理下吧 😂😂，我就不找了

**Comment by AshoneA** [comment]
我来看看
