### ISSUE TITLE
Edge浏览器中，table的固定列（如nzLeft）边框消失

### ISSUE THREAD

**Issue by ai977313677** [ant-design/ant-design#23576]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header](https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header)

### Steps to reproduce
使用edge打开官方文档，查看虚拟滚动demo，可以看到边框消失的现象

### What is expected?
边框与chrome和Firefox中的表现一致，可以正常显示

### What is actually happening?
边框消失

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.9 |
| System | win10 x64 家庭版 |
| Browser | "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18362" |

---
应该是sticky导致的这个问题，edge支持 `position: sticky`，但表现结果与chrome等浏览器不一致

**Comment by afc163** [comment]
`nzLeft` 看上去是 angular 的属性名，你提错地方了。

**Comment by ai977313677** [comment]
> 
> 
> `nzLeft` 看上去是 angular 的属性名，你提错地方了。

不是，我用angular的时候发现的，这个问题在react和angular里都有，在angular那边提了一个issue，让我在react这边也提一个，issue标题没仔细检查直接复制过来的。
