### ISSUE TITLE
Custom icon is shown in expanded rows

### ISSUE THREAD

**Issue by MarcServat** [ant-design/ant-design#23573]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-2shpzk](https://stackblitz.com/edit/react-2shpzk)

### Steps to reproduce
* Click one of the table's row
* see the arrow in the expandable row

### What is expected?
Children rows shouldn't have custom icon, if they are not expandable

### What is actually happening?
All expandable rows have the same custom icon, however when a non custom Icon is set, the expanded rows haven't got any Icon

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Firefox 76 |

**Comment by afc163** [comment]
The reproduction link you provided cannot be open.

**Comment by MarcServat** [comment]
> The reproduction link you provided cannot be open.
Sorry, I've updated.

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-mkwkwh?file=index.js

`expandIcon` props provide `expandable`.
