### ISSUE TITLE
Transfer component - titles property only accepts string[]

### ISSUE THREAD

**Issue by adipaul1981** [ant-design/ant-design#23578]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/transfer/](https://ant.design/components/transfer/)

### Steps to reproduce
In documentation of Transfer component: 
titles property accepts `ReactNode[]`, but only seems to accept `string[]`

### What is expected?
Transfer component - property: titles -  to accept `ReactNode[]` (as per Doc)

### What is actually happening?
Transfer component - property: titles -  to accept `string[]`

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | Linux |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/basic-ant-design-demo-7g8de?file=/index.js

It support ReactNode.
