### ISSUE TITLE
Anchor href 属性包含2个 "#" 时功能异常

### ISSUE THREAD

**Issue by wuzekang** [ant-design/ant-design#23577]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-kstdma](https://stackblitz.com/edit/react-kstdma)

### Steps to reproduce
点击左侧Anchor.Link无法平滑滚动, 无选中标记

右侧功能正常

### What is expected?
点击左侧Anchor.Link平滑滚动, 有选中标记

### What is actually happening?
点击左侧Anchor.Link无法平滑滚动, 无选中标记

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.12.0 |
| System | elementary OS Juno |
| Browser | Version 76.0.3809.132 (Official Build) (64-bit) |

---
HashRouter Link 生成的链接时, 如果有hash属性会产生这种 /#/faq?locale=en#Q1 链接, Anchor 内部的正则会剔除 [/#/faq?locale=en] 只保留 #Q1 导致功能异常

我把

```js
var sharpMatcherRegx = /#([^#] )$/;
```
修改为

```js
var sharpMatcherRegx = /#([\S] )$/;
```
功能恢复正常

**Comment by yoyo837** [comment]
href 不规范，不应该是BUG

**Comment by wuzekang** [comment]
RFC 中 fragmentid 的确不应该包含 "#", 但是我测试了firefox 和 chrome, <a href="#a#b"> 都可以定位到对应的元素. 我提出这个问题主要是 HashRouter 的实现目前就是这样的, 而且这个正则修改也不会增加很高的成本

**Comment by wuzekang** [comment]
https://github.com/ant-design/ant-design/pull/23595
