### ISSUE TITLE
下拉选择器在MAC系统下点击下箭头区域没有反应

### ISSUE THREAD

**Issue by WhatIsGhost** [ant-design/ant-design#23593]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/#components-select-demo-tags](https://ant.design/components/select-cn/#components-select-demo-tags)

### Steps to reproduce
点击任意一个下拉框的下箭头均无反应

### What is expected?
点击下拉框任意位置都能正确显示下拉

### What is actually happening?
点击下拉框的下箭头无反应

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | react |
| System | MAC OS最新 |
| Browser | Chrome最新 Safari最新 |

**Comment by yoyo837** [comment]
Duplicated of #23546
