### ISSUE TITLE
antd formItem中input text配合getFieldProps无法输入中文

### ISSUE THREAD

**Issue by lovesmilesha** [ant-design/ant-design#2359]
#### 本地环境
webpack+react+redux+react-router

- antd 版本:1.6.3
- 操作系统及其版本：win7企业版
- 浏览器及其版本:chrome 51.0.2704.106 m

#### 你做了什么？
```
<FormItem  label="客户姓名:">
       <Input type="text" placeholder="请输入客户姓名"  name="OwnerName" {...getFieldProps('OwnerName')}/>
                            </FormItem>
```

#### 你期待的结果是：
可以正常输入中文
#### 实际上的结果：
*加入了getFieldProps会无法输入中文
#### 可重现的在线演示
暂无

**Comment by benjycui** [comment]
Duplicate: https://github.com/ant-design/ant-design/issues/2239

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by lovesmilesha** [comment]
但是并没有解决问题那个issues,被close掉了。并不是chrome的问题；无法输入中文

**Comment by lovesmilesha** [comment]
ok
