### ISSUE TITLE
Form.item required rules true and datepicker defaultvalue set but error when submit without changing

### ISSUE THREAD

**Issue by okaradayi93** [ant-design/ant-design#23592]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/#DatePicker](https://ant.design/components/date-picker/#DatePicker)

### Steps to reproduce
 <Form.Item 
          name="birth_date" 
          label="Birtdate" 
          rules={[
              {
                required: true,
                message: 'Please input the title of collection!',
              },
            ]}>
          <DatePicker format="DD/MM/YYYY" defaultValue={props.editingrow.birth_date ? moment(props.editingrow.birth_date) : null } style={{width:470}}/>

### What is expected?
if datepicker has default value pass rule

### What is actually happening?
Form.item required rules true and datepicker defaultvalue set but error when submit without changing

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.13.1 |
| System | react |
| Browser | google chrome |

**Comment by vbogutskii-sh** [comment]
```javascript
const config = {
  rules: [{ type: 'object' as const, required: true, message: 'Please select time!' }],
};

<Form.Item label="Date Start" name="dateStart"  {...config}>
    <DatePicker />
</Form.Item>
```

**Comment by gcrmusadul** [comment]
**For Ant Form:**

<Form.Item
        name="dateOfBirth"
        label={t('date_of_birth')}
        rules={[{ type: 'object', required: true, message: t('this_field_is_required') }]}
        defaultValue={moment(user.dateOfBirth)}
        getValueProps={(i) => ({ value: moment(i) })}
    >
        <DatePicker
            format='DD/MM/YYYY'
            placeholder='DD/MM/YYYY'
            allowClear={false}
        />
</Form.Item>
