### ISSUE TITLE
Render Table 出错

### ISSUE THREAD

**Issue by lanstonpeng** [ant-design/ant-design#236]
React.render(
     \<div>\</div>
      \<Table columns={columns} dataSource={dataSource} pagination={pagination} />
    ,node)

只要在Table前加任意tag就会
报错：Adjacent JSX elements must be wrapped in an enclosing tag

**Comment by zhujun24** [comment]
React.render(
<div>
<Table columns={columns} dataSource={dataSource} pagination={pagination} />
</div>, node)
这样试试看

**Comment by afc163** [comment]
http://stackoverflow.com/questions/25034994/how-to-correctly-wrap-few-td-tags-for-jsxtransformer
