### ISSUE TITLE
先打开一个drawer，再打开drawer中的modal，关闭modal，关闭drawer，再打开另一个modal，关闭后body无法滚动

### ISSUE THREAD

**Issue by KaiEi1020** [ant-design/ant-design#23609]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drawerzhongshiyongmodalzaidianjilingyigemodalguanbihou-body-wufagundong-7o023?file=/index.js)

### Steps to reproduce
*  复现步骤：
 * 1. 点击open drawer按钮
 * 2. 点击抽屉中的open modal1按钮，
 * 3. 关闭modal1
 * 4. 关闭抽屉
 * 5. 点击open modal2按钮
 * 6. 关闭modal2
 * 7. body无法滚动

### What is expected?
如上操作后能正常滚动

### What is actually happening?
不能滚动

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome |

---
请认真阅读操作步骤，该问题与其他问题未重复

**Comment by afc163** [comment]
本质上和 #21894 是相同的原因导致，可以到 #21894 下面补充信息和跟进，当然欢迎直接 PR。
