### ISSUE TITLE
Pagination 组件的pageSize切换器可以定义显示位置

### ISSUE THREAD

**Issue by li5tun** [ant-design/ant-design#23601]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望Pagination 组件的pageSize切换器可以定义显示位置

### What does the proposed API look like?
pageSizeChangerPosition

**Comment by li5tun** [comment]
目前下拉菜单只能向下显示。

**Comment by yoyo837** [comment]
pagination用的select，select是支持方向自动的，

![image](https://user-images.githubusercontent.com/6134547/80295287-47f75800-87a4-11ea-825d-0bcce632065f.png)

**Comment by yoyo837** [comment]
select的自动方向是下方没空间了就向上，你是要强制手动指定？

**Comment by li5tun** [comment]
不会自动向上的，始终都是向下的。https://ant.design/components/pagination-cn/，比如在这个示例页中，选项无论在什么情况下都是向下的。

**Comment by yoyo837** [comment]
> 不会自动向上的，始终都是向下的。比如在这个示例页中，选项无论在什么情况下都是向下的。

说过了，因为下面有空间，我给你的截图是F12删除了下方一些DOM结构给你看的。

**Comment by yoyo837** [comment]
当你的select弹出位置下方不够空间就会自动向上。

**Comment by jxccc1998** [comment]
> 当你的select弹出位置下方不够空间就会自动向上。

请问使用position:fixed固定底部的时候分页器会向上弹出，使用position: sticky吸底时依然朝下弹出，这个是因为内部的select还没兼容sticky吗

**Comment by Luooojunnn** [comment]
可以强制控制弹出方向吗

**Comment by cms120** [comment]
## 通过源码中的一个prop解决

也遇到这个问题了，placement错误又不能指定，看源码看到一个api解决了这个问题

看`antd`的源码可以看到，`props` 继承自 `rc pagination`

```tsx
export interface PaginationProps extends RcPaginationProps {
```

继续看 `rc pagination`

```tsx
export interface PaginationProps extends Partial<PaginationData> {
...
}
export interface PaginationData {
  ...
  selectComponentClass: React.ComponentType; // 下拉框组件
}
```

`rc pagination`本身没有 select 组件，需要prop传递

再看 `antd` 的render函数

```tsx
return wrapSSR(
    <RcPagination
      ...
      selectComponentClass={selectComponentClass || (isSmall ? MiniSelect : MiddleSelect)} // 可以自定义 select 否则 用 MiniSelect 或者 MiddleSelect
    />,
  );
```

向前看 `MiniSelect` ，也是 `antd` 的 `select` 组件

```tsx
import type { SelectProps } from '../select';
import Select from '../select';

type CompoundedComponent = React.FC<SelectProps> & {
  Option: typeof Select.Option;
};

const MiniSelect: CompoundedComponent = (props) => <Select {...props} showSearch size="small" />;
const MiddleSelect: CompoundedComponent = (props) => <Select {...props} showSearch size="middle" />;

MiniSelect.Option = Select.Option;
MiddleSelect.Option = Select.Option;

export { MiniSelect, MiddleSelect };
```

到这就可以解决我们的问题了

```tsx
import { Select, SelectProps } from 'antd';

type CompoundedComponent = React.FC<SelectProps> & {
  Option: typeof Select.Option;
};
// 原生的 pagination 组件 的 select 不能自动变更位置 在这替换为 始终在右上角
const SelectTopRight: CompoundedComponent = (props) => <Select {...props} placement="topRight" />;
SelectTopRight.Option = Select.Option;

export { SelectTopRight };
```



```tsx
<Pagination
  ...
  selectComponentClass={SelectTopRight} // 替换掉默认的下拉框
  />
```
