### ISSUE TITLE
<Table /> 复选框选中后，再次更新列表数据后，发现还是选中状态

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#2361]
antd 版本为 1.5.1。

如题，正常情况下更新数据后，之前选中的状态应该也会被取消掉。

在 [#793](https://github.com/ant-design/ant-design/issues/793) 有同学遇到类似的场景，但那个解决方案是针对 0.10.5 的，而在我使用的版本和最新版本这种解决方案应该是无效的，[查看 demo](http://codepen.io/ystarlongzi/pen/mEqXNK)。

**Comment by afc163** [comment]
http://ant.design/changelog#0.12.0 

https://github.com/ant-design/ant-design/commit/3ed9ce3cb5fbeab3936e844575bec63e551b2b24

使用受控模式手动清除 selectedRowKeys，[demo](http://ant.design/components/table/#components-table-demo-row-selection-and-operation)。

**Comment by ystarlongzi** [comment]
谢谢，原来文档里有，没看清楚！

ps，文档的锚点定位貌似有问题，比如你给的 demo 地址就无法定位到对应的位置

**Comment by afc163** [comment]
Firefox 下是可以的。。。我看看。

**Comment by afc163** [comment]
先勉强修复了锚点。

**Comment by chenbin92** [comment]
@afc163  

## 交互: 
每个 TAB 下面均是一个表格，均有过滤，排序，分页功能；

## 问题：
当点击不同的 TAB 切换时，会从后台请求数据；但是在 TAB 切换时，会默认记住上一个 TAB 选中的 `filter`，`sorter`， `pagination`，因为默认状态是不会被清除重置的；

这样问题就来了：数据是动态更新的，但是对应的 `filter`，`sorter`， `pagination` 状态是上一个 TAB 的，能否在切换 TAB 时清除重置对应的 `filter`，`sorter`， `pagination` ?  

## 现有解决方案： 
使用 table 提供的 `filteredValue` 筛选的受控属性可以清除，但是有 `filter`，`sorter`， `pagination` 的地方都需要去配置，工作量太重复了。 


<img width="1031" alt="_" src="https://cloud.githubusercontent.com/assets/3995814/16797293/7609ada6-4919-11e6-90f1-ccc50f980872.png">
