### ISSUE TITLE
form.item表单的name属性

### ISSUE THREAD

**Issue by chengmings** [ant-design/ant-design#23619]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ant@3 的form.getFieldDecorator的id支持这样子嵌套
{getFieldDecorator('member[0].name.firstname', {})(<input/>)}
{getFieldDecorator('member[1].name.firstname', {})(<input/>)}

那么ant@4的name如何做到这样子的嵌套

### What does the proposed API look like?
无

**Comment by yoyo837** [comment]
`member[0].name.firstname` => `['member', 0, 'name', 'firstname']`

https://ant.design/components/form/v3-cn/#%E5%B5%8C%E5%A5%97%E5%AD%97%E6%AE%B5%E8%B7%AF%E5%BE%84%E4%BD%BF%E7%94%A8%E6%95%B0%E7%BB%84

**Comment by chengmings** [comment]
谢谢

**Comment by chengmings** [comment]
这种生成的数组格式，如何能够让它能够在initialValues中使用？ antd@3的时候 我是遍历这个数组 然后在每一个Form.Item下面都有initialValue 出来的

**Comment by yoyo837** [comment]
```js
initialValues={{
  member:[{
    name: {
      firstname: '张山'
    }
  }]
}}
```

也可以等 #22993 发布（预计是4.2.0），恢复原来每一项的`initialValue`的支持。

**Comment by chengmings** [comment]
好的 谢谢
