### ISSUE TITLE
live theme switch between Default, Dark themes in create-react-app

### ISSUE THREAD

**Issue by vreddy448** [ant-design/ant-design#23622]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/23621](https://github.com/ant-design/ant-design/issues/23621)

### Steps to reproduce
 addLessLoader({
        javascriptEnabled: true,
        modifyVars: {
            '@primary-color': '#007AFF'
        },
    }),

### What is expected?
 live theme switch between Default, Dark themes in create-react-app

### What is actually happening?
not able to achieve live theme switch between Default, Dark themes in create-react-app

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | 16.2 |
| System | Mac OS |
| Browser | Chrome |

**Comment by afc163** [comment]
Try https://github.com/mzohaibqc/antd-theme-webpack-plugin

**Comment by vreddy448** [comment]
> Try https://github.com/mzohaibqc/antd-theme-webpack-plugin

its not working and also mentioned repo dependencies are very old.

**Comment by zcmgyu** [comment]
> Try https://github.com/mzohaibqc/antd-theme-webpack-plugin

Switch between dark and light must customize a lot. Otherwise, color doesn't match to current Ant Design's style.
