### ISSUE TITLE
table可选择性展开需求

### ISSUE THREAD

**Issue by sweetolive** [ant-design/ant-design#2362]
rc-table源码是根据expandable来判断是否展开
```
<TableRow
  ...
  expandable={childrenColumn || expandedRowRender}
  ...
/>
```
能否根据expandedRowRender的返回值来实现table可选择性的展开需求呢？
```
<TableRow
  ...
  expandable={childrenColumn || expandedRowRender(record, i)}
  ...
/>
```

效果图如下：
<img width="418" alt="screen shot 2016-07-13 at 11 07 37" src="https://cloud.githubusercontent.com/assets/2638302/16790668/532c8288-48ea-11e6-92e9-9a4de988e515.png">

**Comment by afc163** [comment]
代码你也贴了，目前确实是根据返回值来判断的。

**Comment by afc163** [comment]
感觉可以，来个 PR ~

**Comment by sweetolive** [comment]
好～～

**Comment by sweetolive** [comment]
@afc163 已经在rc-table提了pr，有空merge一下～～

**Comment by afc163** [comment]
后来想了一下，之前修改过性能问题 #764 ，这样可能又会回去，即每行的 render 都要重复运行。

**Comment by benjycui** [comment]
或者这样？

```js
expandable={childrenColumn || (expandedRowRender && shouldExpandRow(record, i))}
```

**Comment by sweetolive** [comment]
@afc163 暂时没有想到其他简单的方法， @benjycui shouldExpandRow也一样会重复运行呀
```
...
if (expandedRowRender && isRowExpanded) {
  expandedRowContent = expandedRowRender(record, i);
}
// 这个是否也会影响性能呢？
let className = rowClassName(record, i);
...
```

**Comment by benjycui** [comment]
计算量不一样。

**Comment by sweetolive** [comment]
rowClassName还是shouldExpandRow？为什么不一样～～

**Comment by ywzhaiqi** [comment]
我暂时用 `rowClassName` 解决，但是有着同样的性能问题。

按照官方的示例

    render() {
        const { selectedRowKeys } = this.state;
        const rowSelection = {
          selectedRowKeys,
          onChange: this.onSelectChange,
        };
        return (
          <div>
            <Table rowSelection={rowSelection} columns={columns} dataSource={data} />
          </div>
        );
    }

只要 render 了，table 的每一行都会运行 `rowClassName`，因为 `rowSelection` 每次都是一个新对象。同样，table 中每次点击选中或取消，每一行都会运行 `rowClassName`
