### ISSUE TITLE
ConfigProvider add getScrollTarget

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design#23626]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- onex is based on [qiankun](http://github.com/umijs/qiankun): , which has a common layout header, and always scroll on content, not window
- antd [affix](https://ant.design/components/affix-cn/)  default is listen window scroll, and expose a props `target: () => HTMLElement`

So any page integrated in onex, should have to set all it's affix `target` props, i guess there may be more component need to do this just like affix.

### What does the proposed API look like?
I suggest  [`ConfigProvider`](https://ant.design/components/config-provider-cn/) add a api `getScrollTarget` just like  `getPopupContainer`

cc/ @kuitos

**Comment by WellerQu** [comment]
+1
