### ISSUE TITLE
多选日期不能重复点击

### ISSUE THREAD

**Issue by yj6232779** [ant-design/ant-design#23620]
[-](url) [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/faq-cn](https://ant.design/docs/react/faq-cn)

### Steps to reproduce
我需做一个多选日期，但是没有点击事件，想要的结果是 我点了4月26日，4月28日，我再点击4月28日是应该取消。没有点击事件只能做到选择4月26日，选择4月28日，需要再选择4月26日后再点击4月28日才能取消2朋28日，然后还得把4月26日选上。才能实现这样的效果

### What is expected?
多选日期，如果得复选择该日期就应该是选中或取消选中

### What is actually happening?
要重复步骤

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | mac |
| Browser | 谷 |

**Comment by afc163** [comment]
Duplicate of #4447

**Comment by afc163** [comment]
There is `onSelect` in calendar https://ant.design/components/calendar/
