### ISSUE TITLE
[v4] Select can't input with mode="tags" and open="false"

### ISSUE THREAD

**Issue by NoyChan** [ant-design/ant-design#23639]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-s1y2f)

### Steps to reproduce
Select组件同时加上mode="tags"和open="false"

### What is expected?
可以正常输入

### What is actually happening?
无法正常输入

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.1 |
| System | window |
| Browser | Chrome/79.0.3945.88 |

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-y6gko?file=/index.js

你的受控模式不完整

**Comment by NoyChan** [comment]
期望可以在始终不显示下拉面板的情况下进行输入（open="false")，3.x版本是支持的 @yoyo837

**Comment by afc163** [comment]
3.x 确实是支持的，需要看看：https://codesandbox.io/s/antd-reproduction-template-np35q?file=/index.js

**Comment by yoyo837** [comment]
3.x 咋不支持回车确认！

**Comment by NoyChan** [comment]
回车确认有workaround  https://codesandbox.io/s/antd-reproduction-template-nkvpu
只是在v4上用不了

**Comment by zombieJ** [comment]
ref https://github.com/react-component/select/blob/12a0859a036781666151f042afa6f5e2b6e44851/src/Selector/MultipleSelector.tsx#L72
