### ISSUE TITLE
Dragger组件，在directory条件下，通过click和drag，beforeUpload的入参中fileList数据表现不一致

### ISSUE THREAD

**Issue by chenhebing** [ant-design/ant-design#23637]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drag-and-drop-ant-design-demo-2meeg?file=/index.js:436-448)

### Steps to reproduce
通过click选择文件夹或拖拽的方式选择文件夹，console中打出的结果不一样

### What is expected?
click和drag，获取到的fileLIst一致

### What is actually happening?
click和drag，获取到的fileLIst不一致

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.0 |
| System | mac 10.15.4 |
| Browser | chrome |

**Comment by chenhebing** [comment]
看了下实现，[在rc-upload中有对directory迭代的过程，isFile的时候 callback了[file]](https://github.com/react-component/upload/blob/master/src/traverseFileTree.js#L44)

是否可以先将file存起来，等迭代处理完了以后，再统一callback？

**Comment by chenhebing** [comment]
并且在directory下，拖拽文件也可以上传，这个可以做下限制不？

**Comment by afc163** [comment]
see https://github.com/ant-design/ant-design/issues/19068 ?

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/30403#issuecomment-857326292

**Comment by pisyell** [comment]
> Fixed in [#30403 (comment)](https://github.com/ant-design/ant-design/issues/30403#issuecomment-857326292)
我看了你的这两条回复，antd@4.24.12 版本中还是没解决楼主这个问题呢？
点击打开文件系统选中文件夹，进入beforeUpload和onChange方法的时候，fileList是多个。
但是拖拽一个文件夹上传的时候，fileList每次都是1个，请问这个解决了吗？


这是我拖拽文件夹上传触发的日志
<img width="348" alt="image" src="https://github.com/ant-design/ant-design/assets/37040920/b53c46b8-91dc-4ea5-a600-be8aa059b7b6">

**Comment by F-loat** [comment]
最新版还是有这个问题，上面两条回复和这个问题也没什么关系 @afc163
