### ISSUE TITLE
3.x的Form动态增减表单项异常

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design#23635]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/withered-bush-jws7y?file=/index.js)

### Steps to reproduce
1. 在代码75行修改为：names[${index}]
2. 增加4项空的表单项
3. 在第一行输入1，在第二行输入2，如此类推
4. 删除第一行

### What is expected?
第一行的1被正确删掉，并且form的values应该是含有一个names数组

### What is actually happening?
第四行的4被删掉了

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.13 |
| System | win 10 |
| Browser | chrome 80 |

---
大佬们可以补充说明一下到底是代码里面的哪个地方写法有问题吗，是antd的还是demo的，如果是antd的能否说明一下原因，学习一下

**Comment by yoyo837** [comment]
多简单的道理，你删除的确实是第一项，但是表单值是根据`getFieldDecorator(key)` 来绑定的，第一个删除了，后面的顶位，不就是这个现象咯。

知道是这个原因后，你完全可以使用编程方法规避这个问题。

**Comment by Rhuaer** [comment]
@yoyo837 
1. 如果按照顶位的说法的话，删了第一项，后面顶上，那最终的结果应该是2/3/4，而不是删了第一项后还是1/2/3吧？
2. 如果按照表单项是按照`getFieldDecorator(key)`来获取输入框的值，那么这种现象可以解释得通。但从另外一方面来说，这种key采用路径写法来生成一个数组表单数据的功能，容易让人入坑，是不是完善文档说明？
3. 如果在78行，增加`initialValue: k,`，则表现正常。按照第1点的顶位逻辑，这样看起来就是ok的，但又没有办法解释第1种的异常；如果按照第2点的说法，其实应该表现异常的，但现在加了initialValue后却一切正常了

**Comment by yoyo837** [comment]
顶上，顶的是你数组的index, 你数组长度4，index是0, 1, 2, 3删除第一个，index是0，1，2，而你看到的是原index 1，2，3的值，明白否？这和antd没关系。

你可以维护一个value, 每次使用的时候value++，删除的不受影响，最终把所有值按顺序取index即可。

**Comment by Rhuaer** [comment]
> 而你看到的是原index 1，2，3的值

这里看到的并不是原index1, 2, 3的值，而是原index0, 1, 2的值。所以才觉得有问题

**Comment by yoyo837** [comment]
都是错觉误导了你。
