### ISSUE TITLE
4.x的Form动态增减表单项异常

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design#23634]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dongtaizengjianbiaodanxiang-ant-design-demo-c37n7?file=/index.js)

### Steps to reproduce
1. 在代码61行增加了这个语句：`name={["name", index]}`
2. 增加4项空的表单项
3. 在第一行输入1，然后在第二行输入2
4. 出现显示异常，1不见了
5. 继续在最后一行输入3，然后删除第一行

### What is expected?
都能正确输入，并且能够正常准确删除项

### What is actually happening?
1. 出现显示异常，1不见了
2. 删除的时候最后一行的3被删掉了

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13 |
| System | win 10 |
| Browser | chrome 80 |

大佬们可以补充说明一下到底是代码里面的哪个地方写法有问题吗，是antd的还是demo的，如果是antd的能否说明一下原因，学习一下

**Comment by huntdream** [comment]
`name={["name", index]}`这里应该写的不对，需要把`field.name`传递下去，`name={[field.name, index]}`这样是可行的

**Comment by Rhuaer** [comment]
> `name={["name", index]}`这里应该写的不对，需要把`field.name`传递下去，`name={[field.name, index]}`这样是可行的

感谢大佬，4.0手生，不知道对于 https://github.com/ant-design/ant-design/issues/23635 这个问题有没有什么指导
