### ISSUE TITLE
Select return undefined when submit

### ISSUE THREAD

**Issue by Mouerr** [ant-design/ant-design#23636]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-component-inside-component-0uk6v?file=/index.js)

### Steps to reproduce
fill the form and submit

### What is expected?
expected select value to be filled

### What is actually happening?
all inputs values are filled when submit except select is undefined

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | react 16.3.1 |
| System | windows 7 64bit |
| Browser | Version 81.0.4044.122 (Official Build) (64-bit) |

---
i think that's happened because i put select inside another component, not directly inside <form.item>

**Comment by yoyo837** [comment]
https://codesandbox.io/s/select-component-inside-component-uwdyc

**Comment by milkyu** [comment]
同样的问题。。。

**Comment by yoyo837** [comment]
https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

**Comment by milkyu** [comment]
解决了 form item里面只能有一个元素
