### ISSUE TITLE
使用create-react-app配置 config-overrides 后 ConfigProvider 组件 在ie11 中报错

### ISSUE THREAD

**Issue by JinTaoOO** [ant-design/ant-design#23646]
react 版本： 16.13.1
antDesign版本：  4.1.5
react-app-rewired 版本： 2.1.5
config-overrides配置如下：
`
const {
  override,
  fixBabelImports,
  addLessLoader,
} = require("customize-cra");
 
 
module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd", libraryDirectory: "es", style: 'css' // change importing css to less
  }),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { "@primary-color": "#1DA57A" }
  })
)`
无 ConfigProvider 时ie 使用正常

**Comment by WeijianXu** [comment]
I have same problem!
