### ISSUE TITLE
upload上传图片限制只能上传一张的方法，是需要哪些事件配合使用才行？ 还有哦了onpreview 事件貌似会失效

### ISSUE THREAD

**Issue by dreamDX** [ant-design/ant-design#2365]
upload上传图片限制只能上传一张的方法，是需要哪些事件配合使用才行？ 还有哦了onpreview 事件貌似会失效，做了事件显示，但是点击无反应

    onPreview: (file) => {
        console.log("const-onPreview:"+file);
        this.setState({
          priviewImage: file.url,
          priviewVisible: true,
        });
      },

**Comment by afc163** [comment]
1. http://ant.design/components/upload/#components-upload-demo-fileList 这里演示了限制的一种方式，具体交互可以自行选择。
2. onPreview 是可用的：http://ant.design/components/upload/#components-upload-demo-picture-card 。如果有问题，最好提供重现，否则难以定位。

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by Robin-front** [comment]
我按照 [http://ant.design/components/upload/#components-upload-demo-picture-card ](http://ant.design/components/upload/#components-upload-demo-picture-card ) ，遇到新上传的图片onPreview不调用的问题，defaultFileList可以正常预览。不过新上传的图片却可以调用 remove

**Comment by Robin-front** [comment]
找到问题了，还是要设置url才行，之前有个 issue说不用url也能预览，我还以为修复了。
添加以下代码正常预览
```js
// 2. 读取远程路径并显示链接
        fileList = fileList.map((file) => {
          if (file.response) {
            // 组件会将 file.url 作为链接进行展示
            file.url = file.response.imgUrl
          }
          return file
        })
```

**Comment by aw6658913** [comment]
@Robin-front 请问你这段代码是加在哪里的
