### ISSUE TITLE
modal的底部的按钮文字默认为cancel,ok而不是取消,确定,与文档所示有出入

### ISSUE THREAD

**Issue by LastStranger** [ant-design/ant-design#23650]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4g6nm?file=/index.js)

### Steps to reproduce
点击modal

### What is expected?
底部文字为取消和确认

### What is actually happening?
底部样式为cancel 和OK

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13 |
| System | macos |
| Browser | 76 |

**Comment by afc163** [comment]
https://ant.design/docs/react/i18n-cn
