### ISSUE TITLE
Antd table pagination position props is not working

### ISSUE THREAD

**Issue by sb-lee** [ant-design/ant-design#23656]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/selection-and-operation-ant-design-demo-nlulq)

### Steps to reproduce
pagination props option is 
```html
<Table
            pagination={{
            position: "bottomCenter",
            showSizeChanger: true,
            pageSizeOptions: ["10", "20", "50", "100", "200"]
          }}
          columns={columns}
          dataSource={data}
 />
```
### What is expected?
pagination position is in bottom-centner

### What is actually happening?
not working. Also, any other position option is not working  with 'bottomLeft', 'topLeft', 'topCenter'

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.1 |
| System | window 10  (1909) |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
```diff
- position: "bottomCenter",
+ position: ["bottomCenter"],
```

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-dynamic-settings

这里设置是无效的，还有 ts 定义是

<img width="639" alt="image" src="https://user-images.githubusercontent.com/507615/80348761-dc46e500-88a0-11ea-888f-f866fd0f1161.png">

是否需要修一下。

**Comment by hengkx** [comment]
#22647  这个是后面改成这样了，我记得当时有讨论是否需要兼容之前的 说不需要我就去掉了，我找不到记录了
![image](https://user-images.githubusercontent.com/8358236/80349395-c554c280-88a1-11ea-8b00-d38ba43d7a65.png)

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/22739/files#r399982279

需要恢复一下

**Comment by zombieJ** [comment]
> #22647 这个是后面改成这样了，我记得当时有讨论是否需要兼容之前的 说不需要我就去掉了，我找不到记录了
> ![image](https://user-images.githubusercontent.com/8358236/80349395-c554c280-88a1-11ea-8b00-d38ba43d7a65.png)

嗯，看起来还是需要兼容的

**Comment by afc163** [comment]
不用兼容了，应该是 ts 定义和演示代码改漏了。

**Comment by hengkx** [comment]
change demo and doc？ @afc163

**Comment by afc163** [comment]
API 其实没写错，不过看上去有歧义。

**Comment by hengkx** [comment]
https://ant.design/components/table-cn/#components-table-demo-pagination
这里面有分页的设置
https://ant.design/components/table-cn/#components-table-demo-dynamic-settings
这个里面直接删掉怎么样？

**Comment by afc163** [comment]
@hengkx 下面这个例子可以看和他配置配合的效果，先别删好了，修复下。

**Comment by hengkx** [comment]
> @hengkx 下面这个例子可以看和他配置配合的效果，先别删好了，修复下。

好 我想想看 怎么实现好 是个数组 同方向还互斥，分页里面那种风格 放里面 好像不太搭

**Comment by LbhFront-end** [comment]
你好，我想问一下，
['bottomCenter '] 类型错误
![image](https://user-images.githubusercontent.com/30042334/83218577-c7f84f80-a1a0-11ea-849c-c0682b3ce17d.png)
![image](https://user-images.githubusercontent.com/30042334/83218600-d2b2e480-a1a0-11ea-87ea-4c0a35c5c203.png)

是会修复吗 ，还是我所引用的TS类型错了
`import { PaginationConfig } from 'antd/es/pagination';`
