### ISSUE TITLE
`form.getFieldInstance()` like v3

### ISSUE THREAD

**Issue by Airkro** [ant-design/ant-design#23659]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
```js
form.getFieldInstance(...).focus()
```

### What does the proposed API look like?
```js
const [form] = Form.useForm();

form.getFieldInstance(['abc','efg']).focus()
```

**Comment by flashprogram** [comment]
Any update on this matter?

**Comment by yakkantiraja** [comment]
@yoyo837  any ETA for this ? Our migration to V4 is blocked due to this bug.

**Comment by chrisque5** [comment]
We too have a dependency on this

**Comment by bplemon** [comment]
Any updates on a fix for this? focus is fundamental in forms so this is a major blocker for my migration to v4!

**Comment by zombieJ** [comment]
Since function component do not support ref before component author wrapper with `forwardRef`. `Form.Item` will add `referable` prop to let form know if this field component should be add ref.

**Comment by yakkantiraja** [comment]
When this fix will be available to use?

**Comment by yoyo837** [comment]
> When this fix will be available to use?

v4.4.0 in future
