### ISSUE TITLE
Fixed columns hide one another

### ISSUE THREAD

**Issue by Maliglood** [ant-design/ant-design#23651]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ts-qslsec](https://stackblitz.com/edit/react-ts-qslsec)

### Steps to reproduce
Scroll to right.

### What is expected?
"Full Name" column is fixed to leftward and "Age" column is fixed to "Full Name" column. Other columns are scrollable.

### What is actually happening?
"Age" column	overlaps "Full Name" column because they have CSS-attribute "left: 0".

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google Chrome |

---
"Full Name" and "Age" columns have CSS-attribute "left: 0" but "left"-attribute of "Age" column must be equal width of "Full Name" column.

**Comment by afc163** [comment]
You need `scroll={{ x: true }}`: https://stackblitz.com/edit/react-ts-np9pn1?file=Hello.tsx

**Comment by Maliglood** [comment]
> You need `scroll={{ x: true }}`: https://stackblitz.com/edit/react-ts-np9pn1?file=Hello.tsx

And then I have with scrolling beacause horisontal scroll inside scrollable container.
