### ISSUE TITLE
Upload action 属性动态修改

### ISSUE THREAD

**Issue by nodeman777** [ant-design/ant-design#2366]
现在的upload组件不接收props的更新，有个使用场景就是后台的上传接口会因为上传的文件类型不同而不同

**Comment by ddcat1115** [comment]
Upload可以接受props更新，猜测你是在 beforeUpload 里修改action不成功？试下返回一个promise

http://codepen.io/ddcat1115/pen/EyEOzy?editors=0011

**Comment by afc163** [comment]
@nodeman777 最好简单总结下，以便后续可以帮助到遇到类似问题的人。

**Comment by nodeman777** [comment]
[upload组件源码](https://github.com/react-component/upload/blob/master/src/AjaxUploader.jsx)
由于我的action是基于setState方法更新的，而setState方法又是异步的。
源码第96行` if (before && before.then)`
所以当需要异步检查或者更新组件props的时候beforeUpload函数需要返回一个thenable对象
