### ISSUE TITLE
DatePicker能否提供扩展支持非正常的日期值

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design#23689]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
某些情况下这个日期接受的值为正常日期或者保密(NA)之类的，期望可以提供这种扩展 比如日期:2010-02-02 或者 NA NA表示这个日期是保密的，类似这种的

### What does the proposed API look like?
<DatePicker externalValues=['NA'] />;

**Comment by yoyo837** [comment]
format就可以了吧

**Comment by xiexingen** [comment]
format一个是吧一个日期对象转成字符串，这种相当于是一个特殊值"NA"这种 他压根就不是一个日期值

**Comment by yoyo837** [comment]
format 只处理显示值，持有的value仍然是日期对象。

**Comment by xiexingen** [comment]
> format 只处理显示值，持有的value仍然是日期对象。

所以咯，实际情况这个时候日期控件的值已经不是一个日期了；而是一个特殊值 表示不适用或者未知的这种场景，

**Comment by afc163** [comment]
试试 https://stackoverflow.com/questions/38953566/override-the-moment-js-default-invalid-date-text

**Comment by xiexingen** [comment]
> 试试 https://stackoverflow.com/questions/38953566/override-the-moment-js-default-invalid-date-text

https://github.com/ant-design/ant-design/issues/23689#issuecomment-620348780

**Comment by xiexingen** [comment]
> 试试 https://stackoverflow.com/questions/38953566/override-the-moment-js-default-invalid-date-text
shile试了下 值是可以进去了，但是面板里面全变成了NaN
![image](https://user-images.githubusercontent.com/7939085/80469229-db7e8380-8972-11ea-864e-f414b3bb2aba.png)

**Comment by afc163** [comment]
supported in https://github.com/ant-design/ant-design/issues/17222
