### ISSUE TITLE
Form.Item上添加initialValue支持 依赖 rc-field-form 1.2.0 版本,这个版本何时可以更新

### ISSUE THREAD

**Issue by hanxinimm** [ant-design/ant-design#23685]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Form.Item上添加initialValue支持 
更好的可以动态控制表单

### What does the proposed API look like?
五一之前可以更新吗？马上五一啊，想着更新了，五一可以把功能完善了~

#21816

**Comment by yoyo837** [comment]
等待4.2.0，应该是五一前
