### ISSUE TITLE
Custom Override Less for ant design is not working.

### ISSUE THREAD

**Issue by ericsonpadol** [ant-design/ant-design#23684]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://notfound.com](http://notfound.com)

### Steps to reproduce
@import '~antd/es/style/themes/default.less';
@import '~antd/dist/antd.less'; // Import Ant Design styles by less entry
@import 'your-theme-file.less'; // variables to override above

run lessc --j override.less src/override.css

### What is expected?
Color palette should change

### What is actually happening?
Color palette not changing

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.1 |
| System | MacOS 10.14.6 |
| Browser | Chrome Version 81.0.4044.92 |

**Comment by ericsonpadol** [comment]
![image](https://user-images.githubusercontent.com/25553631/80397035-27381b00-88e8-11ea-9ff6-8709bf5e4a35.png)

This is the actual result

**Comment by yoyo837** [comment]
https://ant.design/docs/react/customize-theme
