### ISSUE TITLE
Table 的 dataSource 数组 一定要 是 object[] 吗 文档上 是 any[]

### ISSUE THREAD

**Issue by suyunlongsy** [ant-design/ant-design#23697]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new](https://github.com/ant-design/ant-design/issues/new)

### Steps to reproduce
用 string[] 作为 dataSource 时 报错 ,上面网址没办法填的

### What is expected?
为什么 string[] 不支持呢 ，文档上 写的 是 any[] 被骗了

### What is actually happening?
TypeError: Cannot use 'in' operator to search for 'children' in price

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | react 16.13.1 |
| System | mac |
| Browser | chorme |

---
吐槽 提issue 好麻烦

**Comment by afc163** [comment]
应该是 `Object[]`，来个 PR 修正一下文档。

**Comment by hengkx** [comment]
ts也要改

**Comment by hengkx** [comment]
看错了

**Comment by afc163** [comment]
ts 改了就有兼容问题，暂时别动。

**Comment by afc163** [comment]
3.x 的表格这个例子是能跑的：https://codesandbox.io/s/eager-surf-ruied?file=/index.js

@zombieJ 我们需要修复一下。
