### ISSUE TITLE
关于Antd组件属性配置ReactElement的疑问

### ISSUE THREAD

**Issue by zhbhun** [ant-design/ant-design#237]
[Ant Design设计规范-标签嵌套](https://github.com/react-component/react-component.github.io/blob/master/docs/zh-cn/component-design.md#使用标签嵌套)提到尽量使用标签嵌套而不是属性配置，但现在很多Antd组件明明是可以通过标签嵌套实现的，但却用了属性配置。例如，Antd Modal的标题和页脚都是在Modal组件属性上配置的。

**Comment by warmhug** [comment]
是想要这样子？
```html
<Modal>
<Title>title</Title>
<Content>content</Content>
<Footer>
  <button /><button />
</Footer>
</Modal>
```
跟现在的貌似也差别不大

**Comment by yiminghe** [comment]
只用 children，其他不要用

**Comment by zhbhun** [comment]
一些代码格式化工具（如webstorm）对属性这种大括号{}里的标签没法格式化，这样在属性里写ReactElement看起来很不舒服。如果提前在临时变量里写好，这样代码也会很乱。之前开发了个页面，很Antd组件多属性里都要写ReactElement，结果整个代码看下来很晕！
