### ISSUE TITLE
Official website style

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#23702]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

![image](https://user-images.githubusercontent.com/8358236/80454770-29888c80-895d-11ea-9ebb-715c47667f13.png)

### What does the proposed API look like?
not

**Comment by afc163** [comment]
怎么又错了，这个我记得改过。

**Comment by hengkx** [comment]
... 不知道什么时候有改， 刚看的时候 感觉 有点奇怪就提了一个

**Comment by afc163** [comment]
知道了，改 https://github.com/ant-design/ant-design/issues/22392 的时候改挂了。
