### ISSUE TITLE
Button  Type="danger" typescript 不会提示报错

### ISSUE THREAD

**Issue by huihongzhou** [ant-design/ant-design#23708]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://baidu.com](http://baidu.com)

### Steps to reproduce
button.d.ts 里面 declare const ButtonTypes: ["default", "primary", "ghost", "dashed", "danger", "link"]; 是包含 danger 的，但是 4.1.5最新的Button 文档 里是去掉里 type=“danger”， 这。。。。。

### What is expected?
xx

### What is actually happening?
xx

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.1 |
| System | chrome |
| Browser | 最新 |

**Comment by dgomez-orangeloops** [comment]
@afc163 "danger" type not included on ts definition for 4.2.0 :(
