### ISSUE TITLE
Page-header property tags type issue

### ISSUE THREAD

**Issue by Hongvyo** [ant-design/ant-design#23701]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-pageheader-tags-for-typescript-3zk8v?file=/index.tsx)

### Steps to reproduce
on ts compile

### What is expected?
no type error - Type 'Element' is not assignable to type 'TagType | TagType[]'

### What is actually happening?
<PageHeader title="title" tags={<Tag color="blue">service</Tag>} />
tags would throw an error: Type 'Element' is not assignable to type 'TagType | TagType[]' on compile

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.1 |
| System | macOS 10.15.4 |
| Browser | chrome 81.0.4044.122 |

---
related issue? -> https://github.com/ant-design/ant-design/issues/16092 (this has been merged.)
on recent release 4.1.5. typing for tags has changed from ReactElement<Tag> to TagType
please help.

**Comment by alextrastero** [comment]
I'm having the same issue with `4.1.5`, error:
![image](https://user-images.githubusercontent.com/4152819/80462152-95a3ca00-8936-11ea-8520-ebdaa9facc3a.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/cf3d611f59de96f921a88b08997dffb98c664d03#diff-0c0a946fe11565a9475bee873340e3d1R20

@hengkx

**Comment by alextrastero** [comment]
Thanks for the quick response 👍
