### ISSUE TITLE
自定义表单控件 使用 useState 初始值失败【求帮助】

### ISSUE THREAD

**Issue by myzhoulang** [ant-design/ant-design#23707]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaodanchicun-ant-design-demo-2my23?file=/index.js)

### Steps to reproduce
1. 自定义表单控件
2. 表单控件中使用 `useState` 初始化值，无效

### What is expected?
能正常获取到 `useState` 的初始化值

### What is actually happening?
获取不到 `useState` 的初始化值

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.12.0 |
| System | 全部 |
| Browser | 全部 |

**Comment by afc163** [comment]
FileUpload 的 `value` 不是一个真正的受控属性（你的例子是只有第一次渲染时才生效），这不是 antd 的问题，你需要自己研究 React 组件的实现逻辑。
