### ISSUE TITLE
TreeSelect 搜索后产生一系列逻辑问题

### ISSUE THREAD

**Issue by zjuasmn** [ant-design/ant-design#2370]
#### 本地环境

- antd 版本: 1.6.3
- 操作系统及其版本：Mac OSX 10.11.5
- 浏览器及其版本: chrome

#### 你做了什么？

使用官网的treeselect控件，多选例子：

我的操作步骤：

1. 搜索框输入"1-1"
2. 选择“子节点四”
3. 删除搜索框中的“1-1”
4. 搜索框选择“子节点一”

#### 你期待的结果是：

步骤2之后“节点二”半选中，原先选中的“子节点一”依然存在

步骤4之后“子节点一”重新选中

#### 实际上的结果：
步骤2之后节点二全选中，原先选中的“子节点一”不被选中
步骤4之后“子节点一”无法选中，浏览器报错`index.js:101 Uncaught TypeError: Cannot set property 'checked' of undefined`

#### 可重现的在线演示

http://ant.design/components/tree-select/
代码演示的第三个

**Comment by warmhug** [comment]
同 #2393
