### ISSUE TITLE
关于表单校验中trigger的问题，多数是关于InputNumber。

### ISSUE THREAD

**Issue by slertness** [ant-design/ant-design#2371]
#### 本地环境

- antd 版本: 1.6.3
- react 版本: 0.14.8
- 操作系统及其版本：win 10
- 浏览器及其版本: chrome 51

#### 你做了什么？

首先有点疑惑的是文档里写trigger是“收集子节点的值的时机”，另有一个validateTrigger是“校验子节点值的时机”，但是从官方文档里代码的使用来看trigger好像才是“校验子节点值的时机”？而validateTrigger好像没在代码里看到。

然后姑且把trigger当作校验时机来用的话，也是发现几个问题，下面具体说明。

#### 你期待的结果是：

1. Input不写trigger，期待默认onChange（文档中的默认值）校验。
2. InputNumber的rules type写number，trigger写onChange。期待onChange校验。
3. InputNumber的rules type写number，trigger写onBlur。期待onBlur校验。

#### 实际上的结果：

1. 默认不校验。
2. 实际表现为onBlur校验，并且报的是xxx is not a number。
3. 填的是数字但是在onBlur时报xxx is not a number。

#### 可重现的在线演示

http://codepen.io/slert/pen/PzOBaA?editors=0011

**Comment by afc163** [comment]
1. validate 里 的 onChange 需要指定，类似 test2 的用法。

```js
{
  validate: [{
    rules: [
      { required: true },
    ],
    trigger: 'onChange',  // validate 里 的 onChange 需要指定，类似 test2 的用法
  }],
}
```

或者简写为：

```
{
  rules: [
     { required: true },
  ],
}
```

**Comment by afc163** [comment]
2. InputNumber 组件的 onChange 是在 blur 时触发的，所以这个表现是正常的。

**Comment by afc163** [comment]
3) 按照 2 的写法就好，InputNumber 统一使用 onChange 做 trigger 和 validateTrigger 。

**Comment by afc163** [comment]
感谢详细的反馈信息。

**Comment by whx76** [comment]
并且设置如下规则   rules: [{ type: 'number', required: true, message: '必须有值' },
            {  max: 2147483647, message: '最大2147483647' }], 输入任何数字都会提示最大2147483647
