### ISSUE TITLE
Form表单数据接管Tag组件为什么接管不上

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#23711]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-ant-design-demo-c1gfc)

### Steps to reproduce
提交表单，数据没接管

### What is expected?
希望数据接管

### What is actually happening?
实际没接管

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.0 |
| System | mac |
| Browser | 谷歌 |

**Comment by ISBN9527** [comment]
![image](https://user-images.githubusercontent.com/30942709/80463843-74a99c00-896b-11ea-9ec5-5217114e73b3.png)

**Comment by afc163** [comment]
Cannot understand what is your expected result.

**Comment by afc163** [comment]
你需要研究一下：https://ant.design/components/form-cn/#components-form-demo-customized-form-controls

这不是 antd 的问题，关闭了。

**Comment by ISBN9527** [comment]
谢谢大哥指点 @afc163 
以前没好好看示例😁
