### ISSUE TITLE
Import individual Menu with styles, SubMenu do not disappear.

### ISSUE THREAD

**Issue by goldEli** [ant-design/ant-design#23723]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdmenubug-umb0h?file=/src/App.js)

### Steps to reproduce
Mouse in and out the menu.

### What is expected?
Mouse in the menu, a submenu appears, mouse out the menu, submenu disappears

### What is actually happening?
Mouse in and out menus, submenu do not disappear

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.12 |
| System | macos |
| Browser | chrome(Version 81.0.4044.122 (Official Build) (64-bit)) |

---
I manually copied the zoom related class from index.css into my CSS file and the bug was fixed.

**Comment by afc163** [comment]
https://codesandbox.io/s/antdmenubug-xjkm2?file=/src/App.js
