### ISSUE TITLE
extend ConfigProvider class to override its instance member method `getPrefixCls`,but it doesn't work

### ISSUE THREAD

**Issue by doudounannan** [ant-design/ant-design#23720]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/naughty-tree-j943e?file=/src/App.js)

### Steps to reproduce
just run

### What is expected?
override `getPrefixCls` function to add other className on ant component for modify some style

### What is actually happening?
override `getPrefixCls` function doesn't work

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.12 |
| System | osx 10.13.4 |
| Browser | chrome |

**Comment by afc163** [comment]
Just don't extends ConfigProvider.

**Comment by doudounannan** [comment]
> Just don't extends ConfigProvider.

I want to know the reason,can u tell me why?

**Comment by doudounannan** [comment]
> Just don't extends ConfigProvider.

@afc163 I want to know the reason,can u tell me why?

**Comment by afc163** [comment]
It is not a expected way to use React Component.

**Comment by doudounannan** [comment]
> It is not a expected way to use React Component.

I know it isn't a valid solution to custom own style. But  it should work in principle analyze. It works by overriding `render` function in extended class, but `getPrefixCls` function doesn't work, I'm confused.

**Comment by doudounannan** [comment]
> It is not a expected way to use React Component.

@afc163 
I know it isn't a valid solution to custom own style. But it should work in principle analyze. It works by overriding render function in extended class, but getPrefixCls function doesn't work, I'm confused.
