### ISSUE TITLE
Tooltip 在 requestFullscreen 全屏下不显示

### ISSUE THREAD

**Issue by lattemj** [ant-design/ant-design#23738]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/embed/antd-reproduction-template-wzizc?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
dom 中使用 Tooltip 组件，dom全屏（requestFullscreen）后Tooltip组件无法显示

### What is expected?
Tooltip在dom(requestFullscreen全屏)后能正确显示

### What is actually happening?
Tooltip在dom(requestFullscreen全屏)后没有正确显示

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | react |
| System | windows 10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
请使用`getPopupContainer `
