### ISSUE TITLE
loading direction in rtl

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#23735]
### What is expected?
LTR 下 loading 是顺时针，RTL 模式下调整为 逆时针

**Comment by hengkx** [comment]
你这issues 怎么建的为什么没有自动关闭

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/80661440-48079880-8ac1-11ea-8d40-0ad3585fc253.png)

最后一行 不删就 OK

**Comment by xrkffgg** [comment]
我看有提示，还以为 你给这个 解决了呢 😂😂

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design-icons/pull/290 @afc163 @zombieJ

**Comment by zombieJ** [comment]
RTL 下顺时针也是顺时针的，不需要调换方向。

**Comment by zombieJ** [comment]
ref: https://material-ui.com/components/progress/

**Comment by zombieJ** [comment]
另外图标类的大部分都不需要调换方向，它已经是最小单元了。
