### ISSUE TITLE
Upload onDownload works only when clicked on downloadIcon

### ISSUE THREAD

**Issue by kbzowski** [ant-design/ant-design#23737]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-mendeleev-mxwgs?file=/src/App.js)

### Steps to reproduce
1. Click on files list - new tab is opened with given URL
2. Click on download button - onDownload is called

### What is expected?
If onDownload is defined it should be called for both cases - clicking on the files list and download button

### What is actually happening?
onDownload is called only when showDownloadIcon: true and user clicks on that icon. 

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 81 |

---
To not brake anything, onDownload should be called when url in filelist is not defined. Currently, the missing url field results in the link not being created at all.

**Comment by afc163** [comment]
It is designed to bind `download` icon in first place.

**Comment by kbzowski** [comment]
I believe, if url field is not provided in the fileList, clicking on the list item should be handle by onDownload too. Otherwise, it's very inconsistent.

**Comment by huseyingoztok** [comment]
The onDownload method is not triggered at the time of download.

**Comment by huseyingoztok** [comment]
@yoyo837 @afc163 please help.

**Comment by ptflp** [comment]
how to solve this?

**Comment by huseyingoztok** [comment]
I solved it by making a service request in the onPreview method.

`async onPreview(file) {
      if (file.key) {
        const url = await fileService.downloadFile(file.url);
        window.open(url, '_self');
      }
    }`
