### ISSUE TITLE
Ant Table: On data hover does not show for numeric data with Ellipsis on

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#23739]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-4y0dh?file=/index.js)

### Steps to reproduce
Add a `Table`
Create a few columns with data as string and few as numbers
Set `ellipsis` prop to `true`

### What is expected?
When you hover over the content the in built html tooltip(because of title attribute)  should be shown for any generic content irrespective of `String` or `Number`, unless it is specially rendered content

### What is actually happening?
Hover info does not show for numeric data
<img width="517" alt="Screen Shot 2020-05-02 at 10 03 12 AM" src="https://user-images.githubusercontent.com/4985350/80870623-7bcaf580-8c5c-11ea-9539-36b160073ed2.png">

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.13 |
| System | Mac OSX |
| Browser | Safari 13.1, Chrome 80.0 |

**Comment by zombieJ** [comment]
Your demo do not contains Tooltip component.

**Comment by StallionV** [comment]
Hello @zombieJ , 
My bad I did not mean Ant Design Tooltip I meant standard html hover info.
When you over over columns having string data you can see the additional info show up as standard html tooltip (title) but the same does not when the data is numeric.

Hope this clarifies. The reproduction link is still the same
