### ISSUE TITLE
Upload 报跨域上传错误问题

### ISSUE THREAD

**Issue by CharleySc** [ant-design/ant-design#2373]
#### 本地环境

- antd 版本:1.64
- 操作系统及其版本：Mac 10.11.5
- 浏览器及其版本: Safari 谷歌 火狐 Opera

#### 你做了什么？
我使用upload上传组件，。。后端是java 可是 可是上传时报跨域问题。。。不知道是什么情况，upload不是已经帮我们解决的跨域问题了吗？怎么还会报。。是我忽略设置什么了还是
以下是错误信息：
XMLHttpRequest cannot load http://**.**.**:8080/KBBrand**/act**/***.do. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Uncaught ReferenceError: message is not defined

**Comment by afc163** [comment]
https://github.com/react-component/upload/issues/33

**Comment by afc163** [comment]
服务端需要支持跨域接口，upload 作为前端组件，服务端不支持也没有办法。

**Comment by CharleySc** [comment]
你贴给我的那个是后端里面的东西吗。。表示看不懂。。那我这个问题，是服务端没设置好跨域吗还是@ 
@afc163

**Comment by afc163** [comment]
http://stackoverflow.com/questions/10636611/how-does-access-control-allow-origin-header-work

**Comment by CharleySc** [comment]
我在服务端已经设置了如下：
response.setHeader("Access-Control-Allow-Origin,"*");  //支付跨域Access-Control-Allow-Origin
可是还是报那个错。。。我想请教一下Upload组件API中的  ‘headers’参数 或者'data'参数是需要配合设置的吗？怎么设置。。。有点疑惑 真心请教！ @afc163 @

**Comment by vincentshow** [comment]
@afc163 延续一贯的犀利风格
我本地也遇到这个问题，app里数据请求都是跨域，可以正常返回数据，唯独这个Upload控件不知道怎么处理，按照issue里说的方法我做了如下设置
const props = {
            action: this.props.fileUploadUrl,
            listType: 'picture-card' as UploadFileListType,
            headers:{
                "X-Requested-With": null
            },
            withCredentials:true,
            onChange: (info: any) => {
                console.log(info.file.status);
            }
        };
不知道这个header这样设置合不合适，为了测试，我把 this.props.fileUploadUrl换成登录用的url也一样报跨域错误。登录的url原本的功能是OK的，只不过使用的是antinit初始化项目里改造后的Fetch完成请求，达人求破啊
附下我改造的Fetch设置，就是在原来的基础上加了跨域支持
options.mode = "cors";
options.credentials = "include";

**Comment by vincentshow** [comment]
tm自己的问题，服务端在preflight时返回的数据有问题，如果哪位也是用的aspnet core webapi，可以参考下面的方案https://github.com/aspnet/CORS/issues/19

**Comment by Robot-L** [comment]
不知道楼主问题解决了没,同时也为后来的小伙伴们解惑:

当使用XMLHttpRequest发送请求时，浏览器发现该请求不符合同源策略(跨域)，会给该请求加一个请求头：Origin，后台进行一系列处理，如果确定接受请求则在返回结果中加入一个响应头：Access-Control-Allow-Origin;浏览器判断该相应头中是否包含Origin的值，如果有则浏览器会处理响应，我们就可以拿到响应数据，如果不包含浏览器直接驳回，这时我们无法拿到响应数据。

请求头部中会包含以下头部：
```js
Origin:'http://localhost'(请求域名)
Access-Control-Request-Method:'post'(请求方式)
Access-Control-Request-Headers:'X-Requested-With'(请求Header)
```
接收到页面这个请求后，服务器可以设置如下头部与浏览器沟通来判断是否允许这个请求。不设置的话浏览器会拒绝接收数据...
```js
'Access-Control-Allow-Origin':'http://localhost',(允许请求的域名)
'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',(允许请求的方式)
'Access-Control-Allow-Headers': 'X-Requested-With, Content-Type'(允许请求的Headers)
```
@CharleySc 楼主我猜你是不是服务器没有设置完整

**Comment by shengliangli** [comment]
关于服务器设置问题
