### ISSUE TITLE
DatePicker can not choose time

### ISSUE THREAD

**Issue by Niefee** [ant-design/ant-design#23754]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/niefee/pen/YzyxXBg?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fdate-picker-cn%2F](https://codepen.io/niefee/pen/YzyxXBg?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fdate-picker-cn%2F)

### Steps to reproduce
[https://ant.design/](https://ant.design/components/date-picker-cn/#components-date-picker-demo-mode)
官网例子也不能选择时间，没能点击确认按钮。
DatePicker 的mode属性为time，没能正常选择。

### What is expected?
正常选择

### What is actually happening?
按钮一直置灰

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16 |
| System | macos |
| Browser | chrome 64 |

**Comment by afc163** [comment]
You may need https://ant.design/components/time-picker-cn/
