### ISSUE TITLE
Can not use showTime[defaultValue] in RangePicker

### ISSUE THREAD

**Issue by abbish** [ant-design/ant-design#2375]
使用 showTime 设置 TimePicker 的 defaultValue 后 console 报错

```
<RangePicker style={widthStyle}
                         locale={enUS}
                         showTime={{
                           format: 'HH:mm',
                           defaultValue: '00:00:00'
                         }}
                         format="yyyy/MM/dd HH:mm"
                         onChange={this.changeDateRange}
            />
```

![screen shot 2016-07-14 at 2 00 05 pm](https://cloud.githubusercontent.com/assets/138192/16829756/21aea8ec-49cd-11e6-92c3-5726f421d8b4.png)

antd 版本 1.6.2

**Comment by RaoHai** [comment]
@afc163 上次改进后的 showTime 的 datePicker 不支持设置里边 TimePicker 的 defaultValue 了，这个要兼容掉么？

**Comment by afc163** [comment]
能兼容就兼容掉吧，感觉 defaultValue 还是有用的。

**Comment by RaoHai** [comment]
但是好像旧版本 showTime 的 datePicker 也不支持这么设置里边 TimePicker 的 defaultValue 啊。。这个是用在什么场景呢？为什么要单独设置内部 TimePicker 的默认值，而不是整个 datePicker 的日期和时间都一起给一个默认值呢？

**Comment by abbish** [comment]
现象是这样，当选择一个日期后，时间也会被默认生成，而这个时间看上去是随机的，需求是这样，没有选择时间时，时间放空，或者手动设置一个默认值，比如 开始时间 是 00:00 结束时间 是 23:59:59，用户有需求调整时间范围时候在自行调整

![screen shot 2016-07-27 at 2 33 08 pm](https://cloud.githubusercontent.com/assets/138192/17166058/36505fd6-5407-11e6-965c-ae70d52aac26.png)

![screen shot 2016-07-27 at 2 33 08 pm](https://cloud.githubusercontent.com/assets/138192/17166150/c27bc068-5407-11e6-840a-6fa05c2e0f4e.png)

**Comment by RaoHai** [comment]
我们最近对可选时间的 DatePicker 做了优化。选择日期的时候，时间会默认选择当下时刻。

![](https://camo.githubusercontent.com/5ad9cd2df7803d6a121f1dae5508ce204917878b/68747470733a2f2f7a6f732e616c697061796f626a656374732e636f6d2f726d73706f7274616c2f696c576877657664746c4c4c6c7a732e706e67)

如果要配置默认时刻，只能把逻辑调整为：选择日期的时候，时间会默认选择当下时刻或指定的默认时间。时间放空是不合理的。

**Comment by abbish** [comment]
OK，比如用户想看某一天的数据，那么开始和结束都是一天 ，默认选择当前时间为默认时间的做法就不太合适，用户需要额外操作时间，我想最好的办法就是可以定制显示的时间。

还有另一个用起来困惑的地方，当前的功能中的 locale 和时区绑定紧密，在某些情况下我的需求只是希望从 locale 中使用语言翻译元素，而时区保持当前浏览器时区，比如在中国使用的英文界面，目前我的做法也就只能使用 en_US locale  clone 出来的数据中再去改变时区，这个做法虽然可以工作但感觉不妥，也可能是我没有翻查到更好的做法，国际化问题包含语言，格式化，时区等等本身也较复杂，目前的实现略显简单粗暴，造成了一些疑惑

**Comment by abbish** [comment]
OK，比如用户想看某一天的数据，那么开始和结束都是一天 ，默认选择当前时间为默认时间的做法就不太合适，用户需要额外操作，我想比较好的办法就是可以定制默认显示的时间。

还有另一个用起来困惑的地方，当前的功能中的 locale 和时区绑定紧密，在某些情况下我的需求只是希望从 locale 中使用语言翻译元素，而时区保持当前浏览器时区，比如在中国使用的英文界面，目前我的做法也就只能使用 en_US locale clone 出来的数据中再去改变时区，这个做法虽然可以工作但感觉不妥，也可能是我没有翻查到更好的做法，国际化问题包含语言，格式化，时区等等本身也较复杂，目前的实现略显简单粗暴，造成了一些疑惑

**Comment by infeng** [comment]
不知道选择日期的时候时间可以指定这个改进什么时候加上去？

**Comment by jingxiawl** [comment]
这个会调整么，现在也是遇到相同需求需要设置默认开始时间00:00:00,结束时间23:59:59,遇到相同问题报错，

**Comment by benjycui** [comment]
如果是 PropTypes 报错的问题，2.0.0 之后应该就不存在了，因为已经与底层统一了类型。

**Comment by zzzzxiao** [comment]
我现在的需求是RangePicker要设置起始时间和结束时间的showTime，比如起始时间分钟只能选30，结束时间分钟只能选择29分或者59分，showTime怎么配置？

**Comment by benjycui** [comment]
@zzzzxiao 参考 TimePicker 的 API https://ant.design/components/time-picker/#API

**Comment by zzzzxiao** [comment]
showTime={{ defaultValue: '09:29:59', disabledMinutes: this.disabledEndMinutes, disabledSeconds: this.disabledEndSeconds, hideDisabledOptions: true }}
这样设置了，没有什么用。。。@benjycui
报错如下：warning.js?69f9:36 Warning: Failed prop type: Invalid prop `defaultValue` of type `string` supplied to `Picker`, expected `object`.

**Comment by benjycui** [comment]
时间累组件的值需要是 `moment` 类型，请查阅文档。

**Comment by infeng** [comment]
@zzzzxiao 可以暂时通过DatePicker的defaultPickerValue属性来设置起始时间和结束时间

**Comment by ningyanbo** [comment]
DatePicker一个onChange事件，不够用

**Comment by benjycui** [comment]
ping~

**Comment by afc163** [comment]
ping~

**Comment by piotrwitek** [comment]
Could someone translate issue description to english please?
I think I have the same issue which is: 

**Scenario**: I want to set `defaultValue` property in `showTime` prop (accepting `TimePicker Options`) 
for `RangePicker` component to set a default time when choosing value for the first time.

**Expected**: I expect the same behaviour as when setting up a `defaultValue` for `TimePicker` component.

**Current**: `defaultValue` on `TimePicker Options` object passed to `showTime`, doesn't have any effect on `RangePicker` Behaviour

This is very common scenario in creating UI, would be greatly appreciated if this functionality is provided. Maybe I could help?

**Comment by Ben07** [comment]
@benjycui 在1.9.1的antd中，设置DatePicker的时间
`showTime={{defaultValue:moment('00:00:00','HH:mm:ss')}}`
报
`calendar must be type of GregorianCalendar`
请问在不改变antd版本的情况下，有解决办法吗？

**Comment by benjycui** [comment]
@Ben07 请看对应版本的文档。

**Comment by benjycui** [comment]
`2.10.2`
