### ISSUE TITLE
在From中使用DatePicker.RangePicker，其宽度与其它输入框宽度不一致，相对较短

### ISSUE THREAD

**Issue by huxiany** [ant-design/ant-design#23752]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gaojisousuo-ant-design-demo-hzrvf?file=/index.js:262-273)

### Steps to reproduce
说明：其中有使用row 和 col ，并设置了响应式栅格参数；

重现步骤：
1.点开codesandbox链接，然后拉大Browser窗口的宽度，即可看到现象。

### What is expected?
请帮忙确认是否是bug? 

### What is actually happening?
在V3升级至V4中发现此问题

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.12.0 |
| System | win10 |
| Browser | google Chrome |

**Comment by afc163** [comment]
```diff
- <RangePicker />
+ <RangePicker style={{ width: '100%' />`
```

**Comment by binbinah** [comment]
> ```diff
> - <RangePicker />
> + <RangePicker style={{ width: '100%' />`
> ```

看起来应该是：

- <RangePicker />
+ <RangePicker style={{ width: '100%' }} />

漏了俩花括号
