### ISSUE TITLE
官网演示的组件库中栅格配置器tips与下面数值不符

### ISSUE THREAD

**Issue by Sawyer02** [ant-design/ant-design#23768]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/grid-cn/](https://ant.design/components/grid-cn/)

### Steps to reproduce
组件-栅格-栅格配置器

### What is expected?
tips数值应该和下面数值对应。

### What is actually happening?
tips的数值是1、2、3、4，底下的数值是16、24....

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 不懂。 |
| System | windows10 |
| Browser | Google Chrome  81.0.4044.129 |

**Comment by yoyo837** [comment]
这个demo的重点是演示动态设置栏栅格切换成不同的形态供预览，`Slider` 只是个配合工具，不过可以优化一下.
