### ISSUE TITLE
tag demo in site

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#23777]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tag-cn/#components-tag-demo-checkable](https://ant.design/components/tag-cn/#components-tag-demo-checkable)

### Steps to reproduce
这个 可选择的 Demo 想要展示的是不是 热门标签展示的东西？

“可选择” 的 Demo 点击无法选中

是不是可以把 2 个 Demo 合成一个？

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
被我改挂了，原来这个组件没有非受控模式。

**Comment by afc163** [comment]
可以合并。名称改为 `可选择标签`。
