### ISSUE TITLE
Select组件的下拉框，随鼠标浮动到不同选项，选项宽度会不断变化

### ISSUE THREAD

**Issue by blksky** [ant-design/ant-design#23786]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-fsckq?file=/index.js)

### Steps to reproduce
点击Select组件，打开选项列表，鼠标在上面来回滑动

### What is expected?
Select组件的选项，随选项内容确定，且最小宽度为Select组件宽度，且所有选项宽度相同，不随鼠标移动而变化

### What is actually happening?
Select组件的下拉框，随鼠标浮动到不同选项，选项宽度会不断变化

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 6.13.1 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Weird problem.

**Comment by zombieJ** [comment]
accessibility util dom node affect the calculation. Let me fix this.
