### ISSUE TITLE
Switch text display not correct

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#23784]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/switch-cn/#components-switch-demo-text](https://ant.design/components/switch-cn/#components-switch-demo-text)

### Steps to reproduce

![Kapture 2020-04-30 at 17 02 46](https://user-images.githubusercontent.com/5378891/80692654-76f32e00-8b04-11ea-9b4b-c9ac5418aeae.gif)

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | latest |
| System | IOS |
| Browser | chrome |

**Comment by zombieJ** [comment]
@xrkffgg

**Comment by afc163** [comment]
修了可以速度发个 patch

**Comment by beeef** [comment]
> 修了可以速度发个 patch

Sorry I cannot read that. Is there a new patch available that fixes this bug?

**Comment by xrkffgg** [comment]
I am looking it
