### ISSUE TITLE
input serarch in rtl

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#23794]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/#components-input-demo-search-input](https://ant.design/components/input-cn/#components-input-demo-search-input)

![image](https://user-images.githubusercontent.com/29775873/80715021-56d56600-8b28-11ea-8f52-3de54180901d.png)

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | The latest |
| System | win10 |
| Browser | chrome |

**Comment by xrkffgg** [comment]
@afc163 大佬，你新加了一个例子，测出来 BUG 啦~ https://github.com/ant-design/ant-design/pull/23527

下次 加 Demo  @ 我一下，我看看 RTL 有没有影响

**Comment by afc163** [comment]
👌
