### ISSUE TITLE
Form - onFieldsChange is fired three times instead of 1

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#23798]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-demo-houm6)

### Steps to reproduce
type one letter in repro input

### What is expected?
123 logged to console once

### What is actually happening?
123 logged to console thrice

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | latest |
| System | any |
| Browser | chrome 81 |

**Comment by yoyo837** [comment]
Did you forget to save `codesandbox`?

**Comment by avalanche1** [comment]
Yep. Fixed, thx.

**Comment by yoyo837** [comment]
`onFieldsChange` fired by `field` change like `value` or `error`. Maybe `onValuesChange` is what you want.

**Comment by avalanche1** [comment]
Do you mean typing a char is causing three props to change?

**Comment by asumaran** [comment]
Probably related to my issue https://github.com/ant-design/ant-design/issues/23803 @avalanche1  are you using `React.StrictMode` by any chance?

**Comment by zombieJ** [comment]
It's by design: https://github.com/ant-design/ant-design/issues/23060#issuecomment-611295060

Let me add this in FAQ since asked many times.

**Comment by afc163** [comment]
Try `onValuesChange`
