### ISSUE TITLE
form表单的validator，不能使用节流阀吗？

### ISSUE THREAD

**Issue by dlrandy** [ant-design/ant-design#2379]
现在就是想要在用户输入用户名的时候，不要连续的向后台发送请求？
 const  nameProps = getFieldProps('userName', {
          trigger: 'onBlur',
          rules: [
            {required: true, whitespace: true, message: "用户名不能为空"},
            {validator: lodash.debounce(this.checkName(this.checkNameOnServer))}

这样使用还是会连续的发送请求，写法不对吗？还是别的问题啊

**Comment by afc163** [comment]
http://codepen.io/anon/pen/GqyPAV?editors=001
