### ISSUE TITLE
文档中组件默认尺寸为中，在Form.Item下默认组件尺寸为大

### ISSUE THREAD

**Issue by gafish** [ant-design/ant-design#2380]
#### 本地环境

- antd 版本:1.6.4
- 操作系统及其版本：mac os x 10.11.5 (15F34)
- 浏览器及其版本: chrome 版本 51.0.2704.103 (64-bit)

#### 你做了什么？

引入 antd 的 Button

Form.Item>

Button type="primary" size="large">按钮1</Button

Button type="primary">按钮2</Button

/Form.Item>

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

在Form.Item组件下按钮2未添加size属性的时候也被加上了 ant-btn-lg 类，导致尺寸默认状态下是大尺寸

#### 可重现的在线演示

const { Button,Form } = antd;

const App = React.createClass({
  render() {
    return (
      div style={{margin: 10}}>
        Form.Item>
  Button type="primary" size="large">Large</Button>
  Button type="primary">Default</Button>
          /Form.Item>
      /div>
    );
  }
});

ReactDOM.render(<App />, document.getElementById('container'));

**Comment by ddcat1115** [comment]
`Form` 表单文档中有说明：『标准表单中一律使用大号控件』

写在 `Form.Item` 中的组件，若没有指定尺寸，会默认加上大号样式

**Comment by hbrls** [comment]
@ddcat1115 然而 ButtonGroup 不能设置 size="default" 怎么办

**Comment by afc163** [comment]
有问题请单独提 issue。
