### ISSUE TITLE
Add maxLength to Editable Typography

### ISSUE THREAD

**Issue by siyavash4812** [ant-design/ant-design#23801]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using the editable typography in my code in a notes app and I need to have a maximum number of characters allowed set. This is not possible right now. The way I do it right now is I check the length of the new string when onChange is fired but that is too late as I cannot give users live feedback. Someone might right 1000 characters and when try to save it, it will say max characters is 500. 

### What does the proposed API look like?
Editable uses Textarea therefore we can easily pass a prop inside the editable object to the Base component and then Base component can pass it down to Editable.

**Comment by Ezhvsalate** [comment]
Also waiting for this feature! Thank you in advance.
