### ISSUE TITLE
Error: Cannot find module './locale'

### ISSUE THREAD

**Issue by Trenki** [ant-design/ant-design#23817]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/23814无网址](https://github.com/ant-design/ant-design/issues/23814无网址)

### Steps to reproduce
1.使用create-react-app react-admin生成react
2.yarn add antd
3.在app.js引入 Botton
4.npm start
浏览器报错，Cannot find module './locale'

### What is expected?
正常使用antd

### What is actually happening?
浏览器报错Cannot find module './locale'

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | win10 |
| Browser | 谷歌  81.0.4044.122 |

**Comment by mohapakram** [comment]
Same problem here.

**Comment by zombieJ** [comment]
Lock moment version temporary. ref:https://github.com/moment/moment/issues/5484
