### ISSUE TITLE
Tooltip 和 Button(disabled) 混用BUG

### ISSUE THREAD

**Issue by raygu0101** [ant-design/ant-design#2381]
#### 本地环境
- antd 版本: https://npmcdn.com/antd/dist/antd.js
- 操作系统及其版本：windows10
- 浏览器及其版本: chrome 51.0.2704.106

#### 你做了什么？

对 disabled 的 Button 使用 Tooltip 进行提示，提示不会隐藏

#### 你期待的结果是：

Tooltip 能正常使用，hover 显示，out 隐藏

#### 实际上的结果：

hover 显示，out 仍然显示

#### 可重现的在线演示

http://codepen.io/raygu/pen/akEzGP?editors=001

**Comment by afc163** [comment]
已知问题。https://github.com/react-component/tooltip/issues/18

Chrome 的 bug。
