### ISSUE TITLE
when activeKey is supplied to Collapse it disables other Panels 

### ISSUE THREAD

**Issue by SamMaxwell** [ant-design/ant-design#23812]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5j6x0?file=/index.js)

### Steps to reproduce
provide activeKey prop to Collapse
observe how its Panels behave as if they are disabled

### What is expected?
Collapse activeKey prop should not cause Panels to behave as if they are disabled

### What is actually happening?
Collapse activeKey prop causes Panels to behave as if they are disabled

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows 10 Pro 10.0.18363 Build 18363 |
| Browser | Version 81.0.4044.122 (Official Build) (64-bit) |

---
I am using Collapse as navigation menu for an application that has many URIs

the Panels allow information hiding and simplifying the menu structure

if I use defaultActiveKeys, then the Panels behave properly, but defaultActiveKeys only work the first time

I need it to react to the user when the navigate from within the content

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#I-set-the-value-of-Input/Select(etc.),-and-then-it-cannot-be-changed-by-user's-action

Please learn React controlled component.

**Comment by SamMaxwell** [comment]
Thanks, but I do not think it is necessary to prevent the user from opening/closing Panels when the app opens/closes Panels in a cooperative way. [Antd allows the programmatic control of Menu selectedKeys and Breadcrumbs while still allowing the user to interact with the components. Programmatically setting the value of an input does not make the input disabled].

The Collapse/Panel/Menu/Item works wonderfully and exactly meets the requirements when the user is interacting directly with the app navigator. But when the user clicks on a link within the content, the app needs to assist the user by setting the activeKey on the Collapse and setting the selectedKey on the Menu so that the navigator accurately reflects the state of the app.

Please reconsider my request.

At least update the documentation to explain that if activeKey is specified then all Panels become disabled and them add an onClick to the Panel so the developer can set the activeKey programmatically when the user clicks a Panel.

**Comment by EChatzidakis** [comment]
I know it's been years but since Google brought me here and this topic still comes up, my solution to this was to make an `onChange` handler for the `Collapse` that updates the state with the new `activeKey`.
