### ISSUE TITLE
RangePicker mechanism

### ISSUE THREAD

**Issue by jonathanroze** [ant-design/ant-design#23810]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ti7vw?file=/index.js)

### Steps to reproduce
Select a date range, like 2020-4-04 to 2020-4-05 and after that click on the left side and select a previous date 

### What is expected?
Selecting a previous date for the left side and skip to right side for selecting another date

### What is actually happening?
The overlay close and the right side stay like before

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.12 |
| System | Macos |
| Browser | Chrome |

**Comment by zombieJ** [comment]
RangePicker input is individual when both start & end filled.

**Comment by jonathanroze** [comment]
So there aren't no way to open the second datepicker after the first one was filled ?
