### ISSUE TITLE
Ellipsis menu item should ping on the right instead of follow of last visible menu item

### ISSUE THREAD

**Issue by thomaslc66** [ant-design/ant-design#23828]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antdmenubug-qcd8k?file=/src/App.js)

### Steps to reproduce
Create a Menu with a submenu

### What is expected?
Get the possibility to select or change the value of top css param on the submenu class.

### What is actually happening?
With the white theme we don't see it very well but the space between the menu and the submenu display is wide. With the dark theme it's really ugly and it would be good if we have the possibility to access or change this css proprety {top: 71px} that define the space between menu and submenu

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | react last version |
| System | all |
| Browser | all |

**Comment by afc163** [comment]
I don't get your point, could you take some screenshot to decribe your demands with more details?

**Comment by afc163** [comment]
Closing for no response.
