### ISSUE TITLE
When select date from datepicker, table x-axis scrolls to left

### ISSUE THREAD

**Issue by furkanilhan** [ant-design/ant-design#23820]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-tukxso?embed=1&file=app/main.jsx](https://stackblitz.com/edit/react-tukxso?embed=1&file=app/main.jsx)

### Steps to reproduce
There is a "First Date" column on my table at the end of right side.
1. Click the 3 dots next to "First Date" header, you will see the filter popup.
2. Click the "Select Date" input and a DatePicker will be pops up.
3. Choose a date from DatePicker.
When you follow these steps, you will see the table suddenly scrolls to left and DatePicker closes.

### What is expected?
Table must not scroll when I select date from DatePicker in the table filter popup.

### What is actually happening?
Selecting date from table filter popup causes to scroll the table to left. If you realize my DatePicker has a time picker. When I select a day from calender, time picker scrolls to current time. I think it triggers the table scroll.

![datepicker](https://user-images.githubusercontent.com/21006973/80865453-49d48600-8c92-11ea-8fbf-71a168a49e26.gif)

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows 10 Enterprise 1809 |
| Browser | 81.0.4044.129 |

---
I use kendo react grid version: 3.13.0
https://github.com/ant-design/ant-design/issues/23813

**Comment by zombieJ** [comment]
Seems `@progress/kendo-react-data-tools` is not open source that can not get what it handle inside.

Please fire issue to `@progress/kendo-react-data-tools` instead.
