### ISSUE TITLE
antd dynamic form input dependency

### ISSUE THREAD

**Issue by AramRafeq** [ant-design/ant-design#23829]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Form.Item Provides dependencies prop but i cannot get it to work with Form items inside a Form.List this will solve the issue that i want to dynamically add details row with multiple controls some of them depend on values of each other 
<img width="1276" alt="Screenshot 2020-05-02 at 13 50 31" src="https://user-images.githubusercontent.com/6641251/80872741-959c2500-8cbc-11ea-93f0-ba48aaebba90.png">

### What does the proposed API look like?
just like dependencies prop on form.item it could take an object to indicate to which dynamic control should we bind

**Comment by zombieJ** [comment]
Could you provide a reproduce about this not working?
