### ISSUE TITLE
table组件，能否提供默认选中属性设置？

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2382]

**Comment by ddcat1115** [comment]
可以配置 `rowSelection` 下的 `getCheckboxProps`

http://codepen.io/ddcat1115/pen/pbpjJz?editors=001

**Comment by afc163** [comment]
建议用 selectedRowKeys + 受控模式，默认给 selectedRowKeys 指定一个值就能实现。

**Comment by wuhaih** [comment]
其实我想实现的效果是，点击行，但不是点击radio checkbox那列，点击行的其他单元格，默认选中radio或者checkbox，不知道行点击事件，能否做处理

**Comment by wuhaih** [comment]
formProps.tableProps.rowSelection = {
      type: "radio",
       selectedRowKeys:"",
      onChange(selectedRowKeys, selectedRows) {
        _this._selectedRows = selectedRows;
      },
      onSelect(record, selected, selectedRows) {
        _this._selectedRows = selectedRows;
      },
      onSelectAll(selected, selectedRows, changeRows) {
        _this._selectedRows = selectedRows;
      }
    };

为什么行点击事件，onchange不触发，一定要点击radiao列才触发？
