### ISSUE TITLE
 Can't resolve './locale' in 'node_modules\moment\src\lib\locale'

### ISSUE THREAD

**Issue by Poline** [ant-design/ant-design#23823]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Poline/antd](https://github.com/Poline/antd)

### Steps to reproduce
1. create create-react-app with typescript
2. Install 4.2.0. ant library version
3. npm run start
4. add input component to some react component

import { Input } from 'antd';

render() {
    return <Input />;
}

5. See the error after compiling 

./node_modules/moment/src/lib/locale/locales.js
Module not found: Can't resolve './locale' in 'node_modules\moment\src\lib\locale'

### What is expected?
Project will be work properly

### What is actually happening?
I have an error while project compiling

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google Chrome 81.0.4044.129 |

---
I have found some issues from 2018 or 2017 years, but for me solutions did not work

**Comment by hengkx** [comment]
duplicate #23817

**Comment by Poline** [comment]
> duplicate #23817

@hengkx I think no. Because I don't use <LocaleProvider> on smt else which should use moment
Also I use create react app and I have not webpack config, it is not a minute to add it. Also I think that If I install package it should work without any manipulations from my side

**Comment by sowka1995** [comment]
Moment version 2.25.1 still not works. How to force 2.24.0 version using npm not yarn and resolutions block?

**Comment by albertli354** [comment]
> Moment version 2.25.1 still not works. How to force 2.24.0 version using npm not yarn and resolutions block?
> 
> Edit: my temporary workound
> 
> 1. `npm install --save-dev npm-force-resolutions`
> 2. add in package.json
> 
> ```
>  "resolutions": {
>     "moment": "2.24.0"
>  }
> ```
> 
> 1. Add to "scripts" node in package.json
>    ` "preinstall": "npx npm-force-resolutions"`
> 2. Type `npm install`

you can do `npm install moment@2.24.0` to revert to a specific version. But it doesn't work for me.

**Comment by domezi** [comment]
Same problem here...

**Comment by zombieJ** [comment]
@domezi , `2.24.0` not includes `getISOWeeksInISOWeekYear`. Please re-check your `moment` version.

ref: https://unpkg.com/browse/moment@2.24.0/src/lib/moment/prototype.js

**Comment by 1096642300** [comment]
> Moment version 2.25.1 still not works. How to force 2.24.0 version using npm not yarn and resolutions block?
> 
> Edit: my temporary workound
> 
> 1. `npm install --save-dev npm-force-resolutions`
> 2. add in package.json
> 
> ```
>  "resolutions": {
>     "moment": "2.24.0"
>  }
> ```
> 
> 1. Add to "scripts" node in package.json
>    ` "preinstall": "npx npm-force-resolutions"`
> 2. Type `npm install`

**Comment by zombieJ** [comment]
Please move to https://github.com/moment/moment/issues/5472. We may can do nothing in antd side.

**Comment by rudymarca** [comment]
> 2\. npm install

Me ayudo mucho

**Comment by rudymarca** [comment]
> Moment version 2.25.1 still not works. How to force 2.24.0 version using npm not yarn and resolutions block?
> 
> Edit: my temporary workound
> 
> 1. `npm install --save-dev npm-force-resolutions`
> 2. add in package.json
> 
> ```
>  "resolutions": {
>     "moment": "2.24.0"
>  }
> ```
> 
> 1. Add to "scripts" node in package.json
>    ` "preinstall": "npx npm-force-resolutions"`
> 2. Type `npm install`

Falto eliminar node_modules, antes que todo.
