### ISSUE TITLE
File icons

### ISSUE THREAD

**Issue by LucaFilitz** [ant-design/ant-design#23838]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be cool if there were audio/video file icons because there are icons for stuff like image, word, powerpoint etc. 

### What does the proposed API look like?
Like the great existing icons :)

**Comment by afc163** [comment]
Trace in https://github.com/ant-design/ant-design-icons/issues/71#issuecomment-624425505
