### ISSUE TITLE
一个return里有两个form闭合标签会报错

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2383]
#### 可重现的在线演示
http://codepen.io/anon/pen/xOpGVK?editors=001

**Comment by ddcat1115** [comment]
看下报错的原因：Adjacent JSX elements must be wrapped in an enclosing tag

render 内容一定要包在一个标签内

**Comment by afc163** [comment]
error:

```
<Form></Form>
<Form></Form>
```

ok:

```jsx
<div>
  <Form></Form>
  <Form></Form>
</div>
```

**Comment by aw6658913** [comment]
那我要如何让两个<Form></Form>里面的内容不关联呢？如论我点那个确定按钮获取的都是两个表单的值，我希望的效果是只获取到确定按钮所在<Form></Form>标签内的表单值
在线演示地址：http://codepen.io/anon/pen/xOpGVK?editors=001

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2294#issuecomment-232370445
