### ISSUE TITLE
Menu Items that contain an <a> anchor tag and also a custom icon have a blue highlight instead of the normal grey color

### ISSUE THREAD

**Issue by e-compton** [ant-design/ant-design#23830]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-ud8djc](https://stackblitz.com/edit/react-ud8djc)

### Steps to reproduce
Create a menu that has a menu item with both a custom icon and an <a> tag.

```
      <Menu onClick={this.handleClick} selectedKeys={[this.state.current]} mode="inline">
        <Menu.Item key="alipay">
          <a href="https://ant.design" target="_blank" rel="noopener noreferrer">
            Highlighted Correctly
          </a>
        </Menu.Item>
        <Menu.Item key="alipay" icon={<LayoutOutlined />}>
          <a href="https://ant.design" target="_blank" rel="noopener noreferrer">
            Highlighted Weirdly
          </a>
        </Menu.Item>
      </Menu>
```

### What is expected?
Expected the menu item to be grey instead of blue when rendered.

### What is actually happening?
The menu item is blue.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Mac OS |
| Browser | Chrome 81.0.4044.122 |

---
I believe the a tag color should be changed by this css block:
```
.ant-menu-item > a {
    color: rgba(0, 0, 0, 0.65);
}
```

However, when the item is rendered with an icon the "a" is not an immediate child of the ".ant-menu-item":
```
<li class="ant-menu-item" role="menuitem" style="padding-left: 24px;">
  <span role="img" aria-label="layout" class="anticon anticon-layout">
    <svg viewBox="64 64 896 896" focusable="false" class="" data-icon="layout" width="1em" height="1em" fill="currentColor" aria-hidden="true">...</svg>
  </span>
  <span>
    <a href="https://ant.design" target="_blank" rel="noopener noreferrer">
      Highlighted Weirdly
    </a>
  </span>
</li>
```
It could probably be fixed by changing the rule to:
```
.ant-menu-item  a {
    color: rgba(0, 0, 0, 0.65);
}
```

**Comment by jimmykane** [comment]
Hi @afc163  this still applies with Link elements from the react router 

![Image](https://github.com/user-attachments/assets/c6c13755-2946-4d0a-a2c3-8c0ef8d1fb27)
