### ISSUE TITLE
[V4] Table re-rendering even though all props are the same.

### ISSUE THREAD

**Issue by zcmgyu** [ant-design/ant-design#23834]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tracking-ant-design-table-re-renders-cdz5k?file=/src/index.js)

### Steps to reproduce
I've been using https://github.com/welldone-software/why-did-you-render to tracking why a certain component re-renders.
I released after upgrading to AntD V4, the table component render a lot.

Open the console and notice how the heavy list re-renders on every click on "Increase!" even though its props are the same.

### What is expected?
Prevent re-render in the Table component

### What is actually happening?
Components had the name `Body`, `undefined` re-render every sibling component render.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.3.1 |
| System | MacOS |
| Browser | Chrome 80.0.3987.122  |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/23833/files

**Comment by zcmgyu** [comment]
Oh, thanks. I got it.
