### ISSUE TITLE
Warning: React does not recognize the `initialValue` prop on a DOM element.

### ISSUE THREAD

**Issue by Mouerr** [ant-design/ant-design#23839]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-initialvalue-unreconized-m4q9y?file=/index.js)

### Steps to reproduce
just open the console

### What is expected?
expected to set initialValue without throwing warning.

### What is actually happening?
it works as expected but a warning occured in console:
Warning: React does not recognize the `initialValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | windows 7 64bit |
| Browser | chrome Version 81.0.4044.129 (Official Build) (64-bit) |

**Comment by trannhai1998** [comment]
Hi Guys. what is the solution to this problem?

**Comment by denisapelnikov** [comment]
> Hi Guys. what is the solution to this problem?
Just update your Ant Design version. It was fixed.
`npm update antd`

**Comment by Bonnie8ni** [comment]
目前還是有這個問題 + 1

**Comment by Arrow66** [comment]
still getting this error

**Comment by zhonggithub** [comment]
react: 17.0.1
antd: 4.8.5
chrome: 最新版本

same error
![image](https://user-images.githubusercontent.com/17545551/100492031-9702d280-3163-11eb-8918-a3022a4f1aac.png)

**Comment by yoyo837** [comment]
New Reproduction link Pls.
