### ISSUE TITLE
antd4 Tree虚拟滚动 目录多次重复点击展开收起后，就会卡住，例如图标已经显示收起，但子树还是显示的。

### ISSUE THREAD

**Issue by wangdanting** [ant-design/ant-design#23848]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/oe97q)

### Steps to reproduce
1. 重复点击一个目录展开收起。
2. 就会发现三角形图标收起了，但子树还在显示

### What is expected?
重复点击一个目录展开收起，效果能正确

### What is actually happening?
1. 重复点击一个目录展开收起。
2. 就会发现三角形图标收起了，但子树还在显示

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome |

---
应该是计算的性能问题，希望能够优化。
![image](https://user-images.githubusercontent.com/16220538/80936235-c7b79f00-8e02-11ea-818f-184da8612d9f.png)

**Comment by zombieJ** [comment]
Nice catch，在动画没有完成前点击会干扰计算。需要加个锁。
