### ISSUE TITLE
DropdownButton 里没有stopPropagation，导致放在表格里会触发选中

### ISSUE THREAD

**Issue by lifeneedspassion** [ant-design/ant-design#2384]
#### 本地环境

- antd 版本:1.6.2
- 操作系统及其版本：win7
- 浏览器及其版本:all

#### 问题
把 点击模式 的 DropdownButton 放到有勾选功能的表格里，点击DropdownButton会触发表格行选中，希望DropdownButton事件处理函数里加上 stopPropagation，感激不尽呀

**Comment by afc163** [comment]
自行加上可否？表格里的渲染元素的点击事件，靠框架是加不完的，默认都拦截下来也不太好。

```jsx
function handleButtonClick(e) {
  e.stopPropagation();
}

...

<DropdownButton onClick={handleButtonClick} overlay={menu} type="primary">
  某功能按钮
</DropdownButton>
```

**Comment by lifeneedspassion** [comment]
左边按钮是加了的，但是问题是功能按钮右边那个带向下箭头的按钮是没办法加的 @afc163

**Comment by afc163** [comment]
Ok，我晚点再看看。

**Comment by ddcat1115** [comment]
`DropdownButton` 外面包一层，自己加 onClick 事件并阻止吧

http://codepen.io/ddcat1115/pen/dXmkdv?editors=0011

**Comment by lifeneedspassion** [comment]
恩，这样是可以实现的，谢谢。
但是组件里还是没有修改是吗？

**Comment by ddcat1115** [comment]
对，组件内部没有修改。因为全部统一 stopPropagation 不太合适，本来想把event传出来自己在onVisibleChange里阻止冒泡，但有些事件有延时处理，不能有效stop，还不如像上面这样做简单有效~

**Comment by lifeneedspassion** [comment]
好的，确实不好统一处理 ლ(╹◡╹ლ)
那就这样吧，感谢回复❤❤❤

**Comment by ddcat1115** [comment]
😸
