### ISSUE TITLE
Switch 开关在4.2版本中，在关闭状态下无法显示全部文字

### ISSUE THREAD

**Issue by vVvlife** [ant-design/ant-design#23843]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/94fht)

### Steps to reproduce
点击switch按钮

### What is expected?
关闭状态能显示全部文字

### What is actually happening?
第一个文字会被隐藏

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.0 |
| System | Ubuntu 18.04 |
| Browser | Chrome 81.0.4044.122 |

**Comment by xrkffgg** [comment]
has fixed https://github.com/ant-design/ant-design/pull/23791

**Comment by xrkffgg** [comment]
下个版本 会修复
