### ISSUE TITLE
[bug] treeNode does not open with draggable spec

### ISSUE THREAD

**Issue by Jinkwon** [ant-design/ant-design#23851]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pf7xu)

![treeNode](https://user-images.githubusercontent.com/1798916/80938674-fc345680-8e14-11ea-8cf8-5bb8ace9b4bc.gif)

### Steps to reproduce
Drag 0-0-2 item to 0-0-1

### What is expected?
Should open tree node when dragging to treeNode.

### What is actually happening?
Left arrow icon has been changed, but not opened tree node.
When it try again, 0-0-1 treeNode open automatically. (It's bug)

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | latest |
| System | macos  |
| Browser | chrome latest |

**Comment by zombieJ** [comment]
https://github.com/react-component/tree/commit/1c56e48188b9e1a42cf1f6b9b9d1dc5cb40602f1
