### ISSUE TITLE
table fix列width失效

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#23858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-foxpw?file=/index.js)

### Steps to reproduce
resize broswer面板，当横向滚动条出现时，age列width失效

### What is expected?
宽度保持

### What is actually happening?
压缩至最小宽度

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12 |
| System | win |
| Browser | chrome |

**Comment by zombieJ** [comment]
设置 `scroll={{ x: true }}` 时，会使用 Table 原生宽度。当表格被挤压时，列会按比例被压缩。设置滚动宽度即可：

https://codesandbox.io/s/antd-reproduction-template-r3u5s?file=/index.js

**Comment by fred8617** [comment]
4.0.1版本的时候还可以结合layout auto实现单列带宽度固定，请问在当前版本下应该如何实现这样的杨过 @zombieJ 
[https://codesandbox.io/s/antd-reproduction-template-foxpw?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-foxpw?file=/index.js)
