### ISSUE TITLE
Visual inconsistency when using onMouseEnter/Leave to trigger Sider with inner Menu collapse/expansion

### ISSUE THREAD

**Issue by ChambreNoire** [ant-design/ant-design#23864]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/chambrenoire/pen/xxwpVeq](https://codepen.io/chambrenoire/pen/xxwpVeq)

### Steps to reproduce
Move the mouse over the collapsed Sider and then move it off slowly. Now do this fast in one quick flick of the wrist.   

### What is expected?
I expect the appearance of the selected menu item to always be the same when collapsed but this is not the case. it varies depending on how fast the mouse passes over the sider.

### What is actually happening?
If the movement is slow the selected menu item appears with a blue background. If the mouse movement is fast the selected menu item retains the left blue border which is has when the sider is not collapsed.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.11 |
| System | Windows 10 |
| Browser | Chrome 81.0.4044.129 |

---
depending on how (fast vs slow) the collapse is triggered it looks like an ul.ant-menu-vertical is changed to ul.ant-menu-inline and the selected li has a padding-left of 24px added...

**Comment by ChambreNoire** [comment]
![expanded](https://user-images.githubusercontent.com/2291230/81015452-08450600-8e5f-11ea-81b3-3904dd72728f.PNG)
![collapsed-bad](https://user-images.githubusercontent.com/2291230/81015461-0b3ff680-8e5f-11ea-837f-a8269dab2527.PNG)
![collapsed-good](https://user-images.githubusercontent.com/2291230/81015464-0c712380-8e5f-11ea-9cf0-5d4665ae970a.PNG)

**Comment by wenweicui** [comment]
got the same problem, any solutions?

**Comment by afc163** [comment]
I believe it has been resolved in latest antd, please reply if not.

**Comment by ChambreNoire** [comment]
It seems that this has not been resolved yet (yes I'm using the latest version of antd)
