### ISSUE TITLE
render prop in table columns not executed when Customized filter panel

### ISSUE THREAD

**Issue by Mouerr** [ant-design/ant-design#23866]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-filter-panel-ant-design-demo-2nsj9)

### Steps to reproduce
comment this.getColumnSearchProps and render will work good.

### What is expected?
expected the column to be rendered as configured in render prop and show the customized filter panel

### What is actually happening?
if customized filter panel exist in columns, the render prop is not working

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | win 7 64bit |
| Browser | chrome Version 81.0.4044.129 |

**Comment by zombieJ** [comment]
Your `getColumnSearchProps` contains `render` function which replace the origin one.
