### ISSUE TITLE
Checkbox未选中项disabled

### ISSUE THREAD

**Issue by ChenQiWen** [ant-design/ant-design#2387]
#### 本地环境

- antd 版本:1.6.4
- 操作系统及其版本：win10
- 浏览器及其版本:最新chrome

#### 你做了什么？

根据状态控制Checkbox 的disabled

#### 你期待的结果是：

使未选中的 选项 disabled掉

#### 实际上的结果：

所有选项都disabled掉了

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by airyland** [comment]
:sweat:  Are you insane?

**Comment by ChenQiWen** [comment]
就是给Checkbox 绑定了onchange事件  当选中个数大于指定个数时  剩下未选的全部disabled，说白了就是限制下最多选择几个。不是不想写demo   codepen 很多时候都不能反映出情况 我试了很多次都没有反应。

**Comment by ChenQiWen** [comment]
说白了就是给Checkbox 选中个数数量限制，等于选中个数时把未选择项全部disabled而不是把所有的项都disabled。不是不想给demo codepen很多时候都不能反馈出情况 一直无反应

**Comment by benjycui** [comment]
不是常见的场景，还是自行处理下？

**Comment by ChenQiWen** [comment]
Checkbox 选中个数限制  这个还不常见吗？ 很多都会加选择数量限制吧

**Comment by afc163** [comment]
```
<Checkbox disabled />
<Checkbox disabled={false} />
<Checkbox disabled />
<Checkbox disabled={false} />
```

Checkbox 的失效状态都是独立的，有什么问题么？
