### ISSUE TITLE
Calendar Month/Year selection triggers onSelect

### ISSUE THREAD

**Issue by LaurentDeMontBlanc** [ant-design/ant-design#23879]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-s3xfh?file=/index.js)

### Steps to reproduce
Change the month or year on the calendar.

### What is expected?
Nothing happens.

### What is actually happening?
The onSelect method is triggered.

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | ^16.13.1 |
| System | Ubuntu 19.04 |
| Browser | Firefox 75.0 |

---
The onSelect method should only be triggered if a specific date (i.e.: 05.05.2020) is selected.
Im not sure if this is intended as I tried this on older versions (2.x.x) where the onSelect method is only triggered on  cell selection.
If this is intended i would suggest a onCellSelect prop to seperate the concerns.

**Comment by afc163** [comment]
> The onSelect method should only be triggered if a specific date

`onSelect` should be triggered in Month/Year selection, it is a intended behavior.

**Comment by LaurentDeMontBlanc** [comment]
@afc163 should i open a feature request for onCellSelection then?

**Comment by hbl-anhnt1** [comment]
should i open a feature request for onCellSelection then?
