### ISSUE TITLE
When the loading prop of the button changes quickly, the loading icon element will not disappear

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#23888]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crimson-glade-7nlph?file=/src/App.js)

### Steps to reproduce
just click 'Click me!'

### What is expected?
loading icon element should be deleted

### What is actually happening?
loading icon element is still there

![image](https://user-images.githubusercontent.com/7843281/81082598-14e06180-8f26-11ea-870e-1e1c0180cbbc.png)

![image](https://user-images.githubusercontent.com/7843281/81082656-24f84100-8f26-11ea-8a92-6190838c2f6c.png)

![image](https://user-images.githubusercontent.com/7843281/81082856-6a1c7300-8f26-11ea-9fa3-386ec786df96.png)

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome 81 |

**Comment by afc163** [comment]
It seems to have fixed in #23783

**Comment by muzea** [comment]
I tried 4.2.1 and this problem has been fixed.
