### ISSUE TITLE
In multiple selection the 'X' mark is not well placed

### ISSUE THREAD

**Issue by sanadsa** [ant-design/ant-design#23886]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-gh82b?file=/index.js)

### Steps to reproduce
do a select like the example in the link above (codesandbox)

### What is expected?
The 'X' mark should be at the same height of the word

### What is actually happening?
The 'X' mark is a little bit above the word and not well placed

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows 10 pro 1903 |
| Browser | chrome 81 |

**Comment by afc163** [comment]
<img width="173" alt="image" src="https://user-images.githubusercontent.com/507615/81134366-13935100-8f87-11ea-9d36-2ab497b2c633.png">

It looks no problem.

**Comment by mjfwebb** [comment]
Current: `.anticon { vertical-align: -0.125em; }`
![image](https://user-images.githubusercontent.com/28074382/81167816-2cefc980-8f96-11ea-8e2c-3737f00e1493.png)

What could be a little better: `.anticon { vertical-align: -0.225em; }`
![image](https://user-images.githubusercontent.com/28074382/81167952-67596680-8f96-11ea-9e1a-c761dac86865.png)

**Comment by zombieJ** [comment]
<img width="430" alt="截屏2020-05-08 上午11 45 19" src="https://user-images.githubusercontent.com/5378891/81368045-66087500-9121-11ea-9e8b-549e82fc141f.png">
In my view, current x position is better since it's vertical center. Move x down to match text looks more stranger.

**Comment by mjfwebb** [comment]
Though this isn't exactly the same use case, I wanted to see what something similar does elsewhere and thought about browser tabs.

![image](https://user-images.githubusercontent.com/28074382/81372152-f03ce300-90f9-11ea-9772-449eb00589a0.png)

In the attached image, we see the `x` matching both the text *and* vertical center.

For this Antd component to do the same, the height of the tags would need to be increased, so perhaps it's not feasible.

Just some food for thought.

**Comment by Liu-Ya** [comment]
@afc163 @zombieJ 这样做之后在中文中的效果
![image](https://user-images.githubusercontent.com/23520283/82168899-71faf080-98f2-11ea-8d09-a53bd3807ad2.png)

给人感觉头轻脚重，非常不协调
在浏览器标签或VSCode中，'X'的尺寸接近于一个大写字母，而当前只有'x'小写的大小
建议调整`x`尺寸
