### ISSUE TITLE
Table组件加载大量数据时表头和表格内容的加载显示顺序

### ISSUE THREAD

**Issue by HollyHjj** [ant-design/ant-design#23899]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table组件加载大量数据时，表头总是最后加载显示，数据已经显示出来了，表头那一行还是空白，建议先加载显示表头再加载显示表格数据

### What does the proposed API look like?
无改变

**Comment by afc163** [comment]
trace in #24332
