### ISSUE TITLE
Tabs标签的默认样式height: 100%会导致撑满屏幕

### ISSUE THREAD

**Issue by yukilzw** [ant-design/ant-design#23890]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yukilzw/web_channel/blob/bug/antdTab/src/edit/index.js)

### Steps to reproduce
空页面下拖入一个Tabs
.ant-tabs-nav .ant-tabs-tab类名原有的height: 100%会造成撑满屏幕
必须重新在CSS中height设置为auto覆盖

### What is expected?
高度正常

### What is actually happening?
高度不正常

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | win10 |
| Browser | Chrome70.0.35 |

**Comment by yukilzw** [comment]
https://github.com/yukilzw/web_channel/tree/bug/antdTab
切到该仓库bug/antdTab分支上已经清空了所有多余代码，只有一个index.js打包入口文件，npm start就可以在9090端口看到了，这个html模版没有任何多余的内容，只有一个Tabs标签

**Comment by zombieJ** [comment]
`index.html` 里加一个 `<!DOCTYPE html>`

**Comment by yukilzw** [comment]
Oh.....I'm sry (T＿T)

**Comment by MrXianSen** [comment]
请问下这个issuse是怎么解决的？我在flink的原生页面上遇到了一样的问题？

**Comment by Anry** [comment]
> `index.html` 里加一个 `<!DOCTYPE html>`

我再本地调试的时候加了<!DOCTYPE html> 正常了，但是打包发布后，发布后的布甲又显示不正常，请教这是因为什么
