### ISSUE TITLE
table的expandable属性同时设置自定义expandIcon图标和expandRowByClick:true会导致展开无法收拢

### ISSUE THREAD

**Issue by KejieLiu** [ant-design/ant-design#23894]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/spring-shape-15nk4?file=/index.js)

### Steps to reproduce
展开后，点击自定义图标无法恢复成收拢状态，目测是图标点击和行点击事件都触发了，导致无法收拢

### What is expected?
展开后，点击自定义图标恢复成收拢状态

### What is actually happening?
展开后，点击自定义图标无法恢复成收拢状态

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.8 |
| System | mac |
| Browser | chrome81 |

**Comment by KejieLiu** [comment]
👍

**Comment by afc163** [comment]
https://github.com/react-component/table/releases/tag/v7.5.4
