### ISSUE TITLE
[Question] How to write a completely controlled form

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#23898]
### Reproduction link
[https://stackblitz.com/edit/react-avejvc?file=index.js](https://stackblitz.com/edit/react-avejvc?file=index.js)

I removed onChange, the content in the form is still updated.

### What is expected?
When fields are unchanged, the input in the form should not change.

### What is actually happening?
Even though the fields have not changed, the input in the form is still updated.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome 81 |

**Comment by muzea** [comment]
I found the reason for the uncontrollability here

https://github.com/react-component/field-form/blob/df028bfe7cb379dc35f281be988763719a58eef0/src/Form.tsx#L118-L123

This means that form does not provide controlled usage, does it?

**Comment by zombieJ** [comment]
Form do not support fully control. It only re-sync when `fields` change. For control should use `setFields` to control internal status.

**Comment by muzea** [comment]
If I want to discard a change, I can only save the previous value myself, and then call setFields?

**Comment by yoyo837** [comment]
I think, yes.

**Comment by muzea** [comment]
Okay, this design is a bit terrible.

**Comment by yoyo837** [comment]
close this, feel free to open a new issue if you have other questions.
