### ISSUE TITLE
table支持自动滚动

### ISSUE THREAD

**Issue by DreamPWJ** [ant-design/ant-design#23892]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在很多展示页面和大屏页面，需要信息滚动展示，因为数据比较多，同时大屏展示几乎不需要操作所以不适合分页等。antd应该针对可视化大屏做一定的组件，需求很多

### What does the proposed API look like?
AutoScroll="true"

**Comment by yoyo837** [comment]
滚动播出信息那种？

**Comment by afc163** [comment]
这个需求比较特殊，建议自行封装吧。

**Comment by DreamPWJ** [comment]
@afc163 哎 提啥需求基本就是被pass掉 只因为你们没有这个需求而已

**Comment by DreamPWJ** [comment]
@yoyo837  对

**Comment by yoyo837** [comment]
组件只考虑绝大部分常用场景，其他的都需要自行封装。没办法考虑到每个使用者。我自己的项目也是这样的。

**Comment by DreamPWJ** [comment]
这个需求其实也挺常见的

**Comment by DreamPWJ** [comment]
圣诞节彩蛋我们不需要，你们也悄悄加了，有些需求真的是不同人有不同需求，你们觉得不需要的反而是其他人很需要的，比如tabs多标签高效切换

**Comment by yoyo837** [comment]
本身表达的和交流都会带一些主观，做项目也是一样。做了的组件就需要精力和时间去维护，没做的，各自封装的就自行维护。

**Comment by mingdongtu** [comment]
> * [ ]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> 在很多展示页面和大屏页面，需要信息滚动展示，因为数据比较多，同时大屏展示几乎不需要操作所以不适合分页等。antd应该针对可视化大屏做一定的组件，需求很多
> 
> ### What does the proposed API look like?
> AutoScroll="true"
我们也有这个需求

**Comment by Veynee** [comment]
加个动态滚动 css，然后替换数据，再打磨打磨，基本上就 OK

**Comment by zhaoxiaozhang** [comment]
> 

我们也有这需求
