### ISSUE TITLE
DatePicker日期国际化错误 中英文都存在

### ISSUE THREAD

**Issue by DreamPWJ** [ant-design/ant-design#23891]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-i2ijq?file=/index.js)

### Steps to reproduce
  <ConfigProvider locale={zhCN}> 添加全局本地化

### What is expected?
显示应该是全部中文

### What is actually happening?
日期有中文有英文 

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | react 16.13 |
| System | window10 |
| Browser | chrome80 |

**Comment by DreamPWJ** [comment]
https://codesandbox.io/s/antd-reproduction-template-i2ijq?file=/index.js:262-294

**Comment by afc163** [comment]
https://ant.design/components/config-provider-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86-ConfigProvider-locale%EF%BC%8C%E6%97%B6%E9%97%B4%E7%B1%BB%E7%BB%84%E4%BB%B6%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%9F

**Comment by DreamPWJ** [comment]
设置了依然不行 复现地址https://codesandbox.io/s/antd-reproduction-template-zcqjf  @afc163

**Comment by afc163** [comment]
还需要引用 moment 的语言包：https://codesandbox.io/s/antd-reproduction-template-64gfh?file=/index.js:273-303

我补充一下文档。

**Comment by songyanzhen** [comment]
> 还需要引用 moment 的语言包：https://codesandbox.io/s/antd-reproduction-template-64gfh?file=/index.js:273-303
> 
> 我补充一下文档。

这个demo里面的选择框也不全是中文呀，，，按照这个设置了并不好使。。

**Comment by songyanzhen** [comment]
![image](https://user-images.githubusercontent.com/12579967/82668117-ad3b4d80-9c6b-11ea-94e6-bf15acf6e7b5.png)

**Comment by Delphier** [comment]
Same issue when version >= 4.2.1.
4.2.0 OK.

**Comment by JarVZhao** [comment]
奇怪,全配对了moment也不生效,仍然是一半英文,moment": "2.27.0","antd": "4.5.2",
import moment from "moment";
import "moment/locale/zh-cn";
moment.locale("zh-cn");

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/antd-reproduction-template-64gfh?file=/index.js:273-303

这个例子没问题啊

**Comment by JarVZhao** [comment]
我也感觉很奇怪，之前没有这个问题，升级后就出现了，却解决不了，很明显是moment的配置没有生效。试了查依赖发现rc picker用的moment与antd的不一样，不知道有没有影响


 
---原始邮件---
发件人: "xrkffgg"<notifications@github.com&gt;
发送时间: 2020年8月4日(星期二) 中午11:25
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"JarVZhao"<1365966868@qq.com&gt;;
主题: Re: [ant-design/ant-design] DatePicker日期国际化错误 中英文都存在 (#23891)




 
https://codesandbox.io/s/antd-reproduction-template-64gfh?file=/index.js:273-303
 
这个例子没问题啊

**Comment by JarVZhao** [comment]
![image](https://user-images.githubusercontent.com/39182231/89267798-49210680-d66a-11ea-81d9-3951d48d1a90.png)

**Comment by JarVZhao** [comment]
![image](https://user-images.githubusercontent.com/39182231/89268009-871e2a80-d66a-11ea-972e-63aed675fe52.png)

**Comment by afc163** [comment]
@JarVZhao 移除 yarn.lock 或者 package-lock.json 后重新安装。

**Comment by JarVZhao** [comment]
works,thanks

**Comment by wzwlhc** [comment]
把antd版本降为4.2.0， 在哪里看到了>=4.2.1周为英文，本人已试， 可用

**Comment by wzwlhc** [comment]
![image](https://user-images.githubusercontent.com/44838946/90471583-38d05780-e151-11ea-925d-302d06120362.png)

**Comment by wzwlhc** [comment]
@DreamPWJ 
![image](https://user-images.githubusercontent.com/44838946/90471677-6c12e680-e151-11ea-9c78-5e2adc07bb6e.png)

**Comment by FredZeng** [comment]
Bundlers might create multiple copies of moment when using moment@2.27.0, hence `moment.locale` might not work.
See [moment issue 5623](https://github.com/moment/moment/issues/5623#issuecomment-653688917)

**Comment by wumiangithub** [comment]
同样的问题， antd4.6.5   moment 2.29.0    moment恢复老版本2.24.0可展示中文，但是ts报错。。 moment升级最新的，ts是不报错了，但是中英文就都有了。一个时间组件而已这么依赖moment干嘛。。。

**Comment by into-piece** [comment]
我发现当设置umi的config=》ignoreMomentLocale为true后，
![image](https://user-images.githubusercontent.com/23183463/97834151-11316a00-1d12-11eb-9359-f4a4ec4eccbe.png)
会自动把中文在内的国际化去除，所以即使像上文配置后还是无法生效。当我关闭这个配置就修复了日期控件的中文问题显示了。大家可以做一下借鉴~

**Comment by andycao** [comment]
> 同样的问题， antd4.6.5 moment 2.29.0 moment恢复老版本2.24.0可展示中文，但是ts报错。。 moment升级最新的，ts是不报错了，但是中英文就都有了。一个时间组件而已这么依赖moment干嘛。。。

我也遇到同样问题，降级到2.24.0解决的，老项目没有ts
看了下依赖，应该是antd的moment更新了，但是里面的rc-search依赖的moment没有更新

**Comment by lou0820** [comment]
版本：
react: ^16.13.1
antd: ^4.6.5
moment：2.29.1
**antd RangePicker中英文混合显示解决方法：
package.json中手动改成 moment: latest
rm -rf node_modules
rm -rf package-lock.json
npm install**

**Comment by georgehpj** [comment]
moment的package.json里有个jsnext:main属性指向的是./dist/moment.js。也就是说如果外部打包工具设置了能够识别jsnext:main这个属性的话，import moment from 'moment' 对应的应该是 import 'moment/dist/locale/zh-cn'。
这点最好在官网上明说。

**Comment by zhangchao828** [comment]
+1 升级的时候容易出现这种情况，建议官方今早移除对moment的依赖

**Comment by ltbyce** [comment]
@wumiangithub 我也遇到了这个问题（rc-picker 依赖moment:v2.24.0）和我本地的版本v:2.27.0不一致，请问你是如何解决的呢？

**Comment by ltbyce** [comment]
> @wumiangithub 我也遇到了这个问题（rc-picker 依赖moment:v2.24.0）和我本地的版本v:2.27.0不一致，请问你是如何解决的呢？

我知道了，rc-picker 的package中引用的是^2.24.0,^实际取得是最近的大版本，所以实际版本应该看node_modules->moment>momentjs的version实际为2.29.1，那么本地版本修改为^2.24.0就可以了

**Comment by rainmanhhh** [comment]
还是没看懂要怎么解决，antd版本4.11.2，moment版本2.29.1，依然是中英文混合

**Comment by qhx0807** [comment]
将 `import 'moment/locale/zh-cn';`

修改为：

`import 'moment/dist/locale/zh-cn';`

版本：

```json
"antd": "^4.15.1",
"moment":  "^2.29.1"
```
测试可行。

**Comment by g770728y** [comment]
> 将 `import 'moment/locale/zh-cn';`
> 
> 修改为：
> 
> `import 'moment/dist/locale/zh-cn';`
> 
> 版本：
> 
> ```json
> "antd": "^4.15.1",
> "moment":  "^2.29.1"
> ```
> 
> 测试可行。

感谢, 确实, dist下面的文件是ejs格式的

**Comment by Jack-Lo** [comment]
moment版本不一致导致的，rc-calender指定moment为2.x，把自己项目的package.json里moment版本号对齐就可以解决了，先yarn remove moment，再手动添加"moment": "2.x"到package.json，然后yarn一下重新安装依赖

**Comment by endless-z** [comment]
本地运行是正常的，可是发布到测试环境就变中英混合，这是啥原因呢

**Comment by MICAHFANG** [comment]
antd@4.23.2
moment@2.29.4
手写moment语言包，已解决

```
└─┬ antd@4.23.2
  ├── moment@2.29.4
  └─┬ rc-picker@2.6.10
    └── moment@2.29.4 deduped
```
https://codesandbox.io/s/suspicious-banzai-iwpso4?file=/src/App.js


![image](https://user-images.githubusercontent.com/105974914/199633046-d366dc59-ba86-431b-acc3-b3d36572932c.png)

**Comment by lijie602** [comment]
> 将 `import 'moment/locale/zh-cn';`
> 
> 修改为：
> 
> `import 'moment/dist/locale/zh-cn';`
> 
> 版本：
> 
> ```json
> "antd": "^4.15.1",
> "moment":  "^2.29.1"
> ```
> 
> 测试可行。


> 解决了  感谢
>  "antd": "^4.24.6"
> "moment": "^2.29.2",

**Comment by Flcwl** [comment]
@zombieJ  请教下，现在 4.24.8 版本国际化中文的需求，是不是不需要在项目内 moment.locale('zh_cn') 了？

**Comment by taoxiaofeng** [comment]
> antd@4.23.2 moment@2.29.4 手写moment语言包，已解决
> 
> ```
> └─┬ antd@4.23.2
>   ├── moment@2.29.4
>   └─┬ rc-picker@2.6.10
>     └── moment@2.29.4 deduped
> ```
> 
> https://codesandbox.io/s/suspicious-banzai-iwpso4?file=/src/App.js
> 
> ![图像](https://user-images.githubusercontent.com/105974914/199633046-d366dc59-ba86-431b-acc3-b3d36572932c.png)

此方法管用，谢谢

**Comment by simplast** [comment]
yarn add moment@2.29.4 装了这个版本可以了

**Comment by visionChengc** [comment]
如果使用的是yarn   可以加上resolutions 字段固定moment版本   其他工具同理

**Comment by katoto** [comment]
> > @wumiangithub 我也遇到了这个问题（rc-picker 依赖moment:v2.24.0）和我本地的版本v:2.27.0不一致，请问你是如何解决的呢？
> 
> 我知道了，rc-picker 的package中引用的是^2.24.0,^实际取得是最近的大版本，所以实际版本应该看node_modules->moment>momentjs的version实际为2.29.1，那么本地版本修改为^2.24.0就可以了

有用

**Comment by wenda10086** [comment]
2026年，使用antd的4.0版本还是有这个问题。全新项目，但是是用的vite构建。
vite针对moment会有点问题，增加如下代码可强制moment使用同一版本

```ts
// vite.config.ts
resolve: {
    alias: [
      { find: /^moment$/, replacement: resolve(__dirname, 'node_modules/moment/moment') },
      { find: /^moment\//, replacement: `${resolve(__dirname, 'node_modules/moment')}/` },
    ]
  },
```

另有一个保底方案，在入口文件main.ts中
```ts
import moment from 'moment'

// 自己重新注册一下，保证在moment中注册到了zh-cn
moment.defineLocale('zh-cn', {
// 将moment/locale/zh-cn中的配置复制过来
months: '一月_二月_三月_四月_五月_六月_七月_八月_九月_十月_十一月_十二月'.split(
            '_'
        ),
        monthsShort: '1月_2月_3月_4月_5月_6月_7月_8月_9月_10月_11月_12月'.split(
            '_'
        ),
        weekdays: '星期日_星期一_星期二_星期三_星期四_星期五_星期六'.split('_'),
        weekdaysShort: '周日_周一_周二_周三_周四_周五_周六'.split('_'),
        weekdaysMin: '日_一_二_三_四_五_六'.split('_'),
        longDateFormat: {
            LT: 'HH:mm',
            LTS: 'HH:mm:ss',
            L: 'YYYY/MM/DD',
            LL: 'YYYY年M月D日',
            LLL: 'YYYY年M月D日Ah点mm分',
            LLLL: 'YYYY年M月D日ddddAh点mm分',
            l: 'YYYY/M/D',
            ll: 'YYYY年M月D日',
            lll: 'YYYY年M月D日 HH:mm',
            llll: 'YYYY年M月D日dddd HH:mm',
        },
        meridiemParse: /凌晨|早上|上午|中午|下午|晚上/,
        meridiemHour: function (hour, meridiem) {
            if (hour === 12) {
                hour = 0;
            }
            if (meridiem === '凌晨' || meridiem === '早上' || meridiem === '上午') {
                return hour;
            } else if (meridiem === '下午' || meridiem === '晚上') {
                return hour + 12;
            } else {
                // '中午'
                return hour >= 11 ? hour : hour + 12;
            }
        },
        meridiem: function (hour, minute, isLower) {
            var hm = hour * 100 + minute;
            if (hm < 600) {
                return '凌晨';
            } else if (hm < 900) {
                return '早上';
            } else if (hm < 1130) {
                return '上午';
            } else if (hm < 1230) {
                return '中午';
            } else if (hm < 1800) {
                return '下午';
            } else {
                return '晚上';
            }
        },
        calendar: {
            sameDay: '[今天]LT',
            nextDay: '[明天]LT',
            nextWeek: function (now) {
                if (now.week() !== this.week()) {
                    return '[下]dddLT';
                } else {
                    return '[本]dddLT';
                }
            },
            lastDay: '[昨天]LT',
            lastWeek: function (now) {
                if (this.week() !== now.week()) {
                    return '[上]dddLT';
                } else {
                    return '[本]dddLT';
                }
            },
            sameElse: 'L',
        },
        dayOfMonthOrdinalParse: /\d{1,2}(日|月|周)/,
        ordinal: function (number, period) {
            switch (period) {
                case 'd':
                case 'D':
                case 'DDD':
                    return number + '日';
                case 'M':
                    return number + '月';
                case 'w':
                case 'W':
                    return number + '周';
                default:
                    return number;
            }
        },
        relativeTime: {
            future: '%s后',
            past: '%s前',
            s: '几秒',
            ss: '%d 秒',
            m: '1 分钟',
            mm: '%d 分钟',
            h: '1 小时',
            hh: '%d 小时',
            d: '1 天',
            dd: '%d 天',
            w: '1 周',
            ww: '%d 周',
            M: '1 个月',
            MM: '%d 个月',
            y: '1 年',
            yy: '%d 年',
        },
        week: {
            // GB/T 7408-1994《数据元和交换格式·信息交换·日期和时间表示法》与ISO 8601:1988等效
            dow: 1, // Monday is the first day of the week.
            doy: 4, // The week that contains Jan 4th is the first week of the year.
        },
})
```
