### ISSUE TITLE
onFinish not called in test?

### ISSUE THREAD

**Issue by rkrupinski** [ant-design/ant-design#23909]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/upbeat-galois-uegfu

### Steps to reproduce
* Here's a basic antd@4.2.0 form: [https://awesome-jepsen-4fd6f6.netlify.app/](https://awesome-jepsen-4fd6f6.netlify.app/)
* Here's the repository [https://github.com/rkrupinski/antd-form-test](https://github.com/rkrupinski/antd-form-test)

1. Clone the repository
2. Install deps
3. Run tests (these include both: `testing-library` & `enzyme`)

### What is expected?
Tests are passing.

### What is actually happening?
Tests aren't passing.

I've tried a couple of different methods, yet can't make `antd` call the `onFinish` handler. Am I missing something?

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | all |
| Browser | test |

**Comment by zombieJ** [comment]
You can ref `rc-field-form` test case for `onFinish`: https://github.com/react-component/field-form/blob/28c0815d32c4907f1806f7c27651f451e709c52b/tests/index.test.js#L215

**Comment by vadimTestPlatform** [comment]
Found solution for me here: https://issuehunt.io/r/ant-design/ant-design/issues/21272
