### ISSUE TITLE
Table customerize sort is not working in TS functional component

### ISSUE THREAD

**Issue by a3596287** [ant-design/ant-design#23904]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-odj75?file=/antTable.tsx)

### Steps to reproduce
See reproduce linke above, unable to assign column types

### What is expected?
expecting the code would work as in normal JS, but in tax, it's not allow me to assign the type.

### What is actually happening?
expecting the code would work as in normal JS, but in tax, it's not allow me to assign the type.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome |

**Comment by a3596287** [comment]
Error on line 93

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-z6zle?file=/antTable.tsx
