### ISSUE TITLE
input内容溢出时, 内容没有正确滚动到最右侧

### ISSUE THREAD

**Issue by duhongjun** [ant-design/ant-design#23903]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
如gif图所示, 在antd官网复现
https://user-images.githubusercontent.com/18900868/81150089-edcf7180-8fb1-11ea-936a-a874e8fc7a2c.gif

### What is expected?
文本内容超过input宽度时, 最右侧的文字永远展示完整

### What is actually happening?
最右侧的文字被遮盖, 光标也被遮盖了.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.8 |
| System | macos10.15.1 |
| Browser | chrome 81.0 |

**Comment by afc163** [comment]
https://codesandbox.io/s/jibenshiyong-ant-design-demo-mzqr4?file=/index.js:136-160

测试了一下原生 input 也有一样的问题，并且在 Firefox 和 Safari 下没问题，猜测是输入法和 Chrome 浏览器的问题。
