### ISSUE TITLE
Locale can config DatePicker default format

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#23902]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Can config default format globally.

### What does the proposed API look like?
```tsx
<ConfigProvider locale={localeWithFormat} />
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/14656
https://github.com/ant-design/ant-design/issues/26977

**Comment by david-soyez** [comment]
Seriously you link old issues talking about LocalProvider which is deprecated a long time ago.

**Comment by leedorian** [comment]
Same issue, has it been fixed?

**Comment by LukaszGrela** [comment]
I can see the locale object on the `DatePicker` with correct format `dateFormat: "D/M/YYYY"`, but the selected date is formatted with some other format (Default?) `YYYY-M-D`. Are you planing on fixing this bug?

**Comment by LukaszGrela** [comment]
Any update on this issue?

**Comment by Quixit** [comment]
I'm having this issue too, the config provider doesn't affect date/time pickers, they always display the chinese date format YYYY-MM-DD instead of anything else. Like US MM\DD\YYYY

**Comment by lhrinaldi** [comment]
Just FYI if I use `format="L"` it solves my problem the `DatePicker` gets the format from the locale.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
