### ISSUE TITLE
Hope AutoComplete can be add one loading state

### ISSUE THREAD

**Issue by mxt142114** [ant-design/ant-design#23900]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It can let users directly feel the data is loading

### What does the proposed API look like?
AutoComplete can be add one loading state

**Comment by afc163** [comment]
Try `notFoundContent`: https://codesandbox.io/s/basic-usage-ant-design-demo-qbzzz?file=/index.js:356-371
