### ISSUE TITLE
v3 -> v4 升级之后 设定children为select的 Form.Item的validateTrigger为onBlur的话，会在onBlur的时候删除select的值。

### ISSUE THREAD

**Issue by Rain-1214** [ant-design/ant-design#23911]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-demo-xflul?file=/index.js)

### Steps to reproduce
* select选择一个option
* 触发其onBlur事件

### What is expected?
select保留我选中的值

### What is actually happening?
select 置空了我选中的值，并且提示我该字段必填

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | deepin 20.0 beta |
| Browser | 5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36 |

---
问题似乎是之前的 [v3 的](https://github.com/react-component/form/blob/32721598fb40be845105964004af87fe2a06fcd1/src/createBaseForm.js#L267) Form 组件 validate 行为和 trigger 行为都会收集一遍 value。[v4的](https://github.com/react-component/field-form/blob/df028bfe7cb379dc35f281be988763719a58eef0/src/Field.tsx#L400) 将 updateValue 和 validateValue 行为分开了，只在updateValue的时候收集value。

然后还有Select组件在普通模式下所提供的 Input 的 Value 只会保存 searchValue, 所以 [onBlur事件](https://github.com/react-component/select/blob/0ba4d3608afa0a2310568211dfb22d531e2946d2/src/Selector/SingleSelector.tsx#L40)抛出来的event并没有携带上 真实的activeValue,进而Form收集Value的时候 [getValueFromEvent](https://github.com/react-component/form/blob/32721598fb40be845105964004af87fe2a06fcd1/src/utils.js#L89) 这个函数并获取不到值。就出现了上述问题。如果用 Antdv4的 Form 组件(并且没有将trigger和validateTrigger同时设置为 onBlur)应该是没有问题，但是升级过程没有办法重写所有的class组件到hooks。所以有没有什么办法能绕过这个问题。我其实只想安安静静的升个级。升完好好落地一下hooks。

**Comment by zombieJ** [comment]
https://ant.design/docs/react/migration-v4-cn#%E7%BB%84%E4%BB%B6%E9%87%8D%E6%9E%84

> onBlur 时不再修改选中值，且返回 React 原生的 event 对象。

v3 的 Form 设计问题使得 `validateTrigger` 也会收集一次值，同时 Select 的 onBlur 事件返回值设计也有问题。它其实不是应该触发变更的时机，因而在 v4 中将 onBlur 返还给原生 event 事件。

对于兼容包中的 Form 可以包一下 Select，来实现。在 v4 里当前的设计是预期行为。

ref #23372

**Comment by Nicole1991** [comment]
> https://ant.design/docs/react/migration-v4-cn#%E7%BB%84%E4%BB%B6%E9%87%8D%E6%9E%84
> 
> > onBlur 时不再修改选中值，且返回 React 原生的 event 对象。
> 
> 嗯，v3 的 Form 设计问题使得 `validateTrigger` 也会收集一次值。同时 Select 的 onBlur 事件返回值设计也有问题。它其实不是应该触发变更的时机，因而在 v4 中将 onBlur 返还给原生 event 事件。
> 
> 对于兼容包中的 Form 可以包一下 Select，来实现。在 v4 里当前的设计是预期行为。
> 
> ref #23372

@zombieJ  你好，我目前用的是兼容包中的Form，Select用的是v4，想请问一下，你这里的包一下Select是什么意思？我碰到的问题也是把`validateTrigger`的时机设置成onBlur之后，每次onBlur时select中选中的值就被清空了。

**Comment by yoyo837** [comment]
包一下 应该是说 封装再二次处理

**Comment by Rain-1214** [comment]
@Nicole1991 就是你需要一个这样的组件。替换掉那些v3的Form使用着v4的Select的那些地方。。
```ts
import React from 'react';
import { Select } from 'antd';
import { ILegacySelectProps } from './index.d';

const LegacySelect: React.FC<ILegacySelectProps> = (props) => {

  const onBlur = React.useCallback((event: React.FocusEvent<HTMLInputElement>) => {
    if (props.onBlur) {
      props.onBlur(props.value ?? event);
    }
  }, [props.onBlur, props.value]);

  return (
    <Select {...props} onBlur={onBlur}>
      {props.children}
    </Select>
  );
};


export default LegacySelect;


```
