### ISSUE TITLE
Ant Table select all function, behavior is different

### ISSUE THREAD

**Issue by a3596287** [ant-design/ant-design#23913]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-row-selection-custom](https://ant.design/components/table/#components-table-demo-row-selection-custom)

### Steps to reproduce
as the link above

### What is expected?
I have noted, the select all function for the example above, they behave differently.

1. Select All from the header (checkbox), they only select the first page of data. (this is designed like this).

2. Select All from the selection, Table.SELECTION_ALL, is this by design as well?

const rowSelection = {
      selections: [
        Table.SELECTION_ALL]

3. If I want to create a button outside the Table, where can I find the example to achieve point 1 above, (only select the 1st-page data)?

### What is actually happening?
see above

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
> Select All from the selection, Table.SELECTION_ALL, is this by design as well?

It is by design.

> If I want to create a button outside the Table, where can I find the example to achieve point 1 above, (only select the 1st-page data)?

You can filter the dataSource by pageSize and current page, and controll `rowSelection.selectedKeys`.

**Comment by DavraYoung** [comment]
> > Select All from the selection, Table.SELECTION_ALL, is this by design as well?
> 
> It is by design.
> 
> > If I want to create a button outside the Table, where can I find the example to achieve point 1 above, (only select the 1st-page data)?
> 
> You can filter the dataSource by pageSize and current page, and controll `rowSelection.selectedKeys`.

What if user used shift + select to select all rows in the page? He will not expect to select other page rows.

**Comment by rashmimh** [comment]
+1
