### ISSUE TITLE
tabs标签页，选项卡占比宽度是否可以等分

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2391]
<Tabs type="card">
      <TabPane tab="选项卡一" key="1">选项卡一内容</TabPane>
      <TabPane tab="选项卡二" key="2">选项卡二内容</TabPane>
      <TabPane tab="选项卡三" key="3">选项卡三内容</TabPane>
</Tabs

目前选项卡都是居左的，我想要的效果这三个选项卡TAB 平分横向宽度，不知道官方是否能提供这样一个设置

**Comment by afc163** [comment]
抱歉，不提供，建议自行覆盖。
