### ISSUE TITLE
Tree : custom icon with <tag> overlapping with node's label

### ISSUE THREAD

**Issue by TheUncharted** [ant-design/ant-design#23919]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customize-icon-ant-design-demo-dm5dk?file=/index.js)

### Steps to reproduce
Set icon property with :  \<Tag color="purple">123\</Tag>

### What is expected?
The custon icon and the node's label should not overlap and must be separated by a space

### What is actually happening?
the node's label is overlapping with the custom icon

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Try this one: https://codesandbox.io/s/customize-icon-ant-design-demo-4xzvq?file=/index.js

**Comment by TheUncharted** [comment]
thanks !
