### ISSUE TITLE
select组件dropdownStyle 中的top left 属性不生效

### ISSUE THREAD

**Issue by zooeyking** [ant-design/ant-design#23927]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-christian-miwm4)

### Steps to reproduce
<Select
        defaultValue="lucy"
        style={{ width: 120 }}
        dropdownStyle={{top: 120, left: 20}}
        getPopupContainer={() => document.getElementById('area')}
      >    // dropdownStyle中的top left 属性不起作用

### What is expected?
下拉选项弹框按照dropdownStyle 中设置的top left值定位

### What is actually happening?
dropdownStyle 中设置的top left值无效

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.x |
| System | mac |
| Browser | 谷歌 Version 81.0.4044.122 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/6624#issuecomment-374851334

**Comment by zooeyking** [comment]
谢谢！

**Comment by zooeyking** [comment]
我试了dropdownAlign这个属性，但是还是不能解决我的问题。因为dropdownAlign={{offset: [x, y]}}中的x  y 是相对于你计算出来的top  left偏移的，由于你计算出来的top,left值是变化的 导致我无法确定偏移量x,y 要设为多少。
我的理解是 当我设置了dropdownStyle 后，当 dropdownStyle中有top,left属性的时候，你就不需要计算top，left值了，直接使用我dropdownStyle中设置的top,left值。现在是你用计算出来的top,left值 把我dropdownStyle中的top, left覆盖掉了。这显然是不合理的吧。
