### ISSUE TITLE
Switch使用多个标签的时候，样式出现错位

### ISSUE THREAD

**Issue by majinkai** [ant-design/ant-design#23920]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://w3gabj.run.stackblitz.io/](https://w3gabj.run.stackblitz.io/)

### Steps to reproduce
1. 切换到未选中状态
2. 停用字样被遮盖了

### What is expected?
无遮盖正常显示

### What is actually happening?
字样被遮盖了

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | Mac |
| Browser | Chrome |

**Comment by xrkffgg** [comment]
ref https://github.com/ant-design/ant-design/issues/23843
