### ISSUE TITLE
website Anchor highlight bug

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#23929]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/grid-cn/#API](https://ant.design/components/grid-cn/#API)

### Steps to reproduce
点击链接

### What is expected?
正常

### What is actually happening?

![image](https://user-images.githubusercontent.com/8358236/81260458-9e9a4700-906c-11ea-9b67-e76d660d0bd1.png)
应该在api才对
![image](https://user-images.githubusercontent.com/8358236/81260521-bd98d900-906c-11ea-8472-cd3738239c31.png)
`povide`这个对吗？

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | latest |
| System | windows  |
| Browser | chrome |

**Comment by yoyo837** [comment]
`provide`

**Comment by hengkx** [comment]
我实际 要反映的是第一个图片 问题

**Comment by xrkffgg** [comment]
这个例子 没生效？

**Comment by hengkx** [comment]
链接 和 锚点的 位置 对不上

**Comment by hengkx** [comment]
不对啊 最近是改了 什么 所有组件里面都有问题 点 api对应的上面一个

**Comment by afc163** [comment]
@hengkx 来排查一下。

**Comment by hengkx** [comment]
没有解决。
![image](https://user-images.githubusercontent.com/8358236/82824942-d9113a00-9edc-11ea-9ac7-1c93e56bbf66.png)
![bug](https://user-images.githubusercontent.com/8358236/82824957-df9fb180-9edc-11ea-90e2-9ce55299abea.gif)

**Comment by xrkffgg** [comment]
这个 一行 放了 2 个例子，水平方向上 没法区分吧

**Comment by hengkx** [comment]
第一个是我手动选中的 不选中 滚动 永远选不中，这个 感觉 没什么好办法 ，直接url进去 还是 有问题
