### ISSUE TITLE
TreeSelect多选模式下进行搜索会把已选项清掉

### ISSUE THREAD

**Issue by ljy-xian** [ant-design/ant-design#2393]
#### 本地环境
antd版本：0.12.13
操作系统：ubuntu14.04
浏览器：chrome50.0.2661.102

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

#### 你做了什么？
使用TreeSelect组件进行多选。部分属性如下：
            multiple: true,
            treeCheckable:true
            searchPlaceholder: '请选择',
            placeholder: '请选择',
            treeNodeFilterProp:'label',
例如选项中共有四项，label分别为 bb ab bc bd ac 。当前状态下已经选中bb，ac两项。此时输入关键字b进行联想，弹出联想框后再选一项‘bd’，发现此时已选项ac会被清掉。也就是说进行联想时，也会对已选项进行过滤。

#### 你期待的结果是：
输入关键字进行联想，不会对已选项再次过滤。

#### 实际上的结果：
输入关键字进行联想，同时会对已选项进行过滤。

#### 可重现的在线演示
麻烦看一下这个问题，谢谢～

**Comment by warmhug** [comment]
升级到 rc-tree-select@1.7.9
