### ISSUE TITLE
[Menu] 建议提供关闭 scrollIntoView 功能的 prop

### ISSUE THREAD

**Issue by oustn** [ant-design/ant-design#23936]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当菜单出现滚动条且页面缩放（scale）的时候，由于容器组件的尺寸计算使用的是 clientHeight，导致位置计算错误，scrollIntoView 的节点错误。

[Demo](https://codesandbox.io/s/elegant-bhaskara-7cvf1)

鼠标移动到 Option3 时可见现象，导致滚动位置错误。

### What does the proposed API look like?
Menu 上提供一个 prop， 可以关闭这个功能

**Comment by afc163** [comment]
可以直接去掉这个功能，给 https://github.com/react-component/menu 来个 PR 吧。
