### ISSUE TITLE
级联选择次级选项首次render了两遍

### ISSUE THREAD

**Issue by zhangzhi93** [ant-design/ant-design#23933]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
异步加载时，次级可能有一样的选项，导致切换的时候视觉上看不出切换了。想加一个动画，发现首次的时候动画会走两遍。示例：https://codesandbox.io/s/dongtaijiazaixuanxiang-ant-design-demo-52jk5?file=/index.js

### What does the proposed API look like?
无api期望，首次只render一遍

**Comment by EscapeB** [comment]
上面的example 收拢展开菜单项同样执行会执行两次动画。
应该是trigger 的display值none和block切换导致css动画重复绘制。

**Comment by Kermit-Xuan** [comment]
不是渲染两次的问题，其实是`transitionName`属性值导致的，此属性默认值为`slide-up`，就会在菜单整体添加一个`slide-up`的动画，又因为你在菜单子元素上也添加了动画，挂载的时候你的动画先执行了(第一次绘制), 然后菜单整体的`slide-up`动画执行了，完成后导致子元素的动画再次绘制(第二次绘制)。
可以将`transitionName`设为空，或者用JS去控制子元素动画，在动画结束后删除类名。

![1](https://user-images.githubusercontent.com/33770367/82112161-0cd1be80-977d-11ea-8d8c-7fc970c07e24.png)
![2](https://user-images.githubusercontent.com/33770367/82112168-1529f980-977d-11ea-8263-e4f73d233d1b.png)
![3](https://user-images.githubusercontent.com/33770367/82112175-1bb87100-977d-11ea-8605-12e79cab2d37.png)

**Comment by Kermit-Xuan** [comment]
@afc163 这个我看了是`transitionName`导致的子元素动画重复绘制问题，没什么问题的话是不是就可以先关了？

**Comment by afc163** [comment]
感谢 @Kermit-Xuan 细致的排查

**Comment by zhangzhi93** [comment]
> @afc163 这个我看了是`transitionName`导致的子元素动画重复绘制问题，没什么问题的话是不是可以先关了？

您好，请问下有什么解决方法吗？
> 将transitionName设为空

怎样把动画类名设为空？

> JS去控制子元素动画，在动画结束后删除类名

怎样监听动画结束？

**Comment by Kermit-Xuan** [comment]
@zhangzhi93 就是将`cascader`组件的`transitionName`属性名设为空字符串
``` html
<Cascader
  transitionName=''
  options={this.state.options}
  loadData={this.loadData}
  onChange={this.onChange}
  changeOnSelect
  popupClassName="animate-cascader"
/>
```

**Comment by zhangzhi93** [comment]
> @zhangzhi93 就是将`cascader`组件的`transitionName`属性名设为空字符串
> 
> ```
> <Cascader
>   transitionName=''
>   options={this.state.options}
>   loadData={this.loadData}
>   onChange={this.onChange}
>   changeOnSelect
>   popupClassName="animate-cascader"
> />
> ```

好的，谢谢
