### ISSUE TITLE
Table可能在Modal中超出边界

### ISSUE THREAD

**Issue by ppmmwozuiai** [ant-design/ant-design#23931]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/blissful-engelbart-wgdlb?file=/src/App.js)

### Steps to reproduce
采用官网实例https://ant.design/components/table-cn/#components-table-demo-nested-table 中的表格，并将其置于Modal中，

### What is expected?
表格在Modal边界内

### What is actually happening?
1）当表格size=default时，表格超出Modal边界，size=middle/small时不超出
2）当渲染子表格时，不论设置任何size，均超出Modal边界

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12 |
| System | Windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
Try `scroll.x`: https://codesandbox.io/s/dry-pine-cku3h

or `tableLayout="fixed"`: https://codesandbox.io/s/nice-bose-w9g4x?file=/src/App.js
