### ISSUE TITLE
RadioGroup组件属性之间有冲突

### ISSUE THREAD

**Issue by cnv587** [ant-design/ant-design#2394]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

#### 可重现的在线演示

设置“getFieldProps('isContainerChild')” 后"defaultValue=1"无效

**Comment by cnv587** [comment]
OK,我明白了，initialValue

**Comment by afc163** [comment]
麻烦自行关闭。。
