### ISSUE TITLE
[Table] internalRefs is a regenerated object every time, resulting in useless render

### ISSUE THREAD

**Issue by muzea** [ant-design/ant-design#23948]
https://github.com/ant-design/ant-design/blob/c4b602e8353e9ca926e29dda0e6ef7df7f265c70/components/table/Table.tsx#L163-L165

**Comment by zombieJ** [comment]
@muzea , could you provide the reproduce of useless render?

**Comment by muzea** [comment]
@zombieJ  https://stackblitz.com/edit/react-9mccwx?file=index.js
When the value of input changes, there will be a lot of useless rendering in the table.

![image](https://user-images.githubusercontent.com/7843281/81374984-0ca94180-9133-11ea-9ba7-f4d8df1bf163.png)

**Comment by zombieJ** [comment]
Table re-render is caused by App render. Table should always re-render when parent render in case parent state used in `column.render`.

It's not related with `internalRefs`.

**Comment by muzea** [comment]
I can understand that in the actual scenario, there will be users who refer to some variables in column.render that will not be passed to the table. antd table made some compromises for this usage. But I still want to point out that this compromise hurts users who will not refer to variables in table.render that will not be passed to table.

If the props we pass to the table have not changed, why do we need to re-render the entire table? If I want to guarantee my performance, should I use useMemo to wrap every table that needs to be rendered?

PS: I updated the example, the Memo component has the performance I expect, and we can compare the performance of the two writing methods in react devtool profiler.

**Comment by zombieJ** [comment]
Table support `shouldCellUpdate` in next minor version. 

In alpha version, there exists many of `useMemo` to reduce render times. It removed in released version since `column.render` is very flexible controlled by user. By default, we should keep sync re-render when parent changed. But yes, just use `shouldCellUpdate` in next version to control cell render logic.
