### ISSUE TITLE
Autocomplete with both custom options and custom input field

### ISSUE THREAD

**Issue by thomasstjerne** [ant-design/ant-design#23941]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/thomasstjerne/pen/pojaYgX](https://codepen.io/thomasstjerne/pen/pojaYgX)

### Steps to reproduce
Use both custom Input field and custom options as children of Autocomplete

### What is expected?
Custom render of Options and Input

### What is actually happening?
Custom input will not work and this error will be in the console:
Warning: `children` should be `Select.Option` or `Select.OptGroup` instead of `Search`.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.9 |
| System | OSX |
| Browser | Chrome Version 81.0.4044.122 (Official Build) (64-bit) |

---
The dataSource prop is now deprecated so custom rendering of Options is done with children, but if a custom input field is required, this is also done through children. And it seems that the options prop doesn´t work with custom rendered Options

**Comment by zombieJ** [comment]
https://ant.design/components/auto-complete-cn/#components-auto-complete-demo-custom

**Comment by thomasstjerne** [comment]
Thanks @zombieJ , but this will not work if you look at the example. Please reopen.
The issue is that BOTH custom Input AND custom Options should be possible. 
The code below will not work unless you change `options` prop to `dataSource` which is deprecated.
````
const options = result.map(email => (
    <Option key={email} value={email}>
      {email}
    </Option>
  ));

return (
    <AutoComplete
      options={options}
      style={{
        width: 200,
      }}
      onSearch={handleSearch}
      placeholder="input here"
    >
      <TextArea
        placeholder="input here"
        className="custom"
        style={{ height: 50 }}
        onKeyPress={handleKeyPress}
      />
    </AutoComplete>
  );
````

**Comment by zombieJ** [comment]
Internal antd is just covert `Option` nodes to `options`. `options` is same as Options. You don't need to create that.

**Comment by thomasstjerne** [comment]
But I need the children of the Option to be a ReactNode not plain text. How do I achieve that:
````
<Option>
 <MyCustomReactNode />
</Option>

````

**Comment by N00nDay** [comment]
I second this. This is one of the biggest headaches from switching from v3 to v4. I have wasted days on trying to get this to work.

**Comment by djpeach** [comment]
Really surprised this is not a thing, to be able to take a list of react nodes in the options array. We also have a need for this

**Comment by djpeach** [comment]
Solution! AntDesign bases their AutoComplete on rc-select: https://www.npmjs.com/package/rc-select, which has a `getInputElement()` prop. AntDesign just extends rc-selects props, so this is also a prop for AntDesign even though it is not listed in the AutoComplete api. So just feed in your custom input element via this prop, and provide your custom options through AutoComplete's customized children option.

```
const options = result.map(email => (
    <Option key={email} value={email}>
      {email}
    </Option>
  ));

return (
    <AutoComplete
      getInputElement={() => (
        <TextArea
          placeholder="input here"
          className="custom"
          style={{ height: 50 }}
          onKeyPress={handleKeyPress}
        />
      )}
      style={{
        width: 200,
      }}
      onSearch={handleSearch}
      placeholder="input here"
    >
    {options}
    </AutoComplete>
  );
```

**Comment by DevonPeroutky** [comment]
Huge +1 this is necessary

**Comment by akavato** [comment]
Strange it's closed without any labels, this won't be fixed? This is a real issue.

**Comment by k88manish** [comment]
Don't know if this is correct of not but i was able to customise list items by putting JSX element in label prop

```tsx
   const options = data.map(({ user }) => ({
      value: user.email,
      label: (
        <div style={{ display: 'flex', textAlign: 'right' }}>
          {user.email}
          { user.isMember && (
            <span style={{ fontSize: '14px', color: 'grey', flex: 1 }}>Already a member</span>
          )}
        </div>
      )
    }))
```

**Comment by thomasstjerne** [comment]
> Don't know if this is correct or not but i was able to customise list items by putting JSX element in label prop

This was how I solved it as well.

**Comment by akavato** [comment]
> > Don't know if this is correct or not but i was able to customise list items by putting JSX element in label prop
> 
> This was how I solved it as well.

This makes sense! May be this could be pushed to docs that we can write jsx in label? @afc163
