### ISSUE TITLE
使用dispatch更新界面刷新效率太低了?每秒更新3次浏览器就卡死了

### ISSUE THREAD

**Issue by laolaolulu** [ant-design/ant-design#23949]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我前端有个列表(G2仪表盘)集合,connect了个model,然后后端通过websocket发送数据到前端通过reducers去更新界面;但我发现效率太低了,每秒更新3次浏览器就卡死了,我不太明白是否是我写法有问题?

### What does the proposed API look like?
前端websocket代码:
 const hubConnect = new HubConnectionBuilder()
                .withUrl('../chathub')
                .build();
            try {
                hubConnect.on("update_parval", function (id: number, value: number) {
                    dispatch({
                        type: 'parameter/putVal',
                        payload: { id, value }
                    });
                });

model代码:
export interface ModelType {
  namespace: string;
  state: ParStateType;
  reducers: {
    putVal: Reducer<ParStateType>;
  };
}
export interface ParStateType {
  list: Parameter[],
}
const Model: ModelType = {
  namespace: 'parameter',
  state: {
    list: [],
  },
  reducers: {
     putVal(state = { list: [] }, { payload }) {
      const p = state.list.find(f => f.id == payload.id);
      if (p) {
        p.value = payload.value;
      }
      return { ...state };
    },
};
export default Model;

前端界面:
interface CardListProps {
    parameter: ParStateType;
    dispatch: Dispatch;
}
const Index: React.FC<CardListProps> = (props) => {
    const {
        parameter: { list: parlist },
    } = props;
    return (
        <List<Parameter>
            style={{ margin: 24 }}
            rowKey="id"
            grid={{ gutter: 24, xxl: 6, xl: 5, lg: 4, md: 3, sm: 2, xs: 1 }}
            dataSource={parlist}
            renderItem={(item) => {
                if (item.sort && item.sort > 0) {
                      return (
                        <List.Item key={item.id}>
                            <Card
                                hoverable                              
                            >
                                <Gauge values={item} />
                            </Card>
                        </List.Item>
                    );
                } else { return (<></>); }
            }}
        />
    );
}
export default connect(
    ({
        parameter,
    }: {
        parameter: ParStateType;
    }) => ({
        parameter,
    }),
)(Index);

**Comment by yoyo837** [comment]
应该和antd没关系
