### ISSUE TITLE
How to repair the position of the  select options  when it is expanded

### ISSUE THREAD

**Issue by zhangwudi886** [ant-design/ant-design#23954]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-wu-xd2vz?file=/index.js)

### Steps to reproduce
click select，then it's out of bounds,Scroll bar appears in area div。

### What is expected?
I hope it doesn't show up when select options expands，i do not want scrollbars，and hope  to offset right，，，What should I do to fix it

### What is actually happening?
area div find a scroll bar when options show

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.13 |
| System | mac os  |
| Browser |  chrome 81.0.4044.129（正式版本） （64 位） |

**Comment by afc163** [comment]
How about remove `dropdownMatchSelectWidth={false}` ?

**Comment by zhangwudi886** [comment]
> How about remove `dropdownMatchSelectWidth={false}` ?

, development scenarios need different lengths，so，i can't change this options，

**Comment by zhangwudi886** [comment]
I have solved this problem by checking the source code！it's work for me .
`			
<Select>	
dropdownAlign={{
	overflow: { adjustX: true, adjustY: true }, // auto adjust position when sourceNode is overflowed
}}
</Select>	
`
