### ISSUE TITLE
水平Menu在菜单比较多时，切换display属性有明显卡顿

### ISSUE THREAD

**Issue by wongfugui** [ant-design/ant-design#23956]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/wongfugui/pen/abvYwZd?editors=0010](https://codepen.io/wongfugui/pen/abvYwZd?editors=0010)

### Steps to reproduce
1、水平Menu菜单达到40个左右

2、隐藏Menu，设置display: none

3、设置display：block，将Menu显示出来，出现明显卡顿

4、从display：block 到 display：none则不存在该情况

5、仅在 mode 为 ‘horizontal’时存在该情况。 

### What is expected?
切换状态不卡顿

### What is actually happening?
切换时有明显卡顿

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.0 |
| System | windows |
| Browser | chrome |

**Comment by cszo** [comment]
我觉得应该是这个更新导致的[#22934](https://github.com/ant-design/ant-design/pull/22934)  用4.1.1以前的版本就没这个问题    希望大牛尽快处理下吧  这个子菜单渲染的问题太影响体验了  @  @AshoneA

**Comment by AshoneA** [comment]
@cszo 应该跟 #22934 没关系，那个 commit 对实际代码其实没什么影响，不过这个确实可以优化下。
你先试试这种方法呢？ https://codepen.io/AshoneA/pen/rNOKgvd?editors=1010

**Comment by wongfugui** [comment]
@AshoneA 你的这种方法试过，只能小幅优化，不能根本上解决问题，菜单再多一点点也还是会卡顿，而且在部分场景下没有办法按照这种方法来使用，比如整个Menu是由另一个包封装提供的

**Comment by cszo** [comment]
> @cszo 应该跟 #22934 没关系，那个 commit 对实际代码其实没什么影响，不过这个确实可以优化下。
> 你先试试这种方法呢？ https://codepen.io/AshoneA/pen/rNOKgvd?editors=1010

看错了 其实我想说的是这个问题......#24103

**Comment by Kermit-Xuan** [comment]
@afc163 我看了看是由于rc-menu里面的这个方法导致的:
``` js
// memorize rendered menuSize
  setChildrenWidthAndResize = () => {
    if (this.props.mode !== 'horizontal') {
      return;
    }
    const ul = ReactDOM.findDOMNode(this) as HTMLElement;

    if (!ul) {
      return;
    }

    const ulChildrenNodes = ul.children;

    if (!ulChildrenNodes || ulChildrenNodes.length === 0) {
      return;
    }

    const lastOverflowedIndicatorPlaceholder = ul.children[
      ulChildrenNodes.length - 1
    ] as HTMLElement;

    // need last overflowed indicator for calculating length;
    setStyle(lastOverflowedIndicatorPlaceholder, 'display', 'inline-block');

    const menuItemNodes = this.getMenuItemNodes();

    // reset display attribute for all hidden elements caused by overflow to calculate updated width
    // and then reset to original state after width calculation

    const overflowedItems = menuItemNodes.filter(
      c => c.className.split(' ').indexOf(MENUITEM_OVERFLOWED_CLASSNAME) >= 0,
    );

    overflowedItems.forEach(c => {
      setStyle(c, 'display', 'inline-block');
    });

    this.menuItemSizes = menuItemNodes.map(c => getWidth(c));

    overflowedItems.forEach(c => {
      setStyle(c, 'display', 'none');
    });
    this.overflowedIndicatorWidth = getWidth(ul.children[
      ul.children.length - 1
    ] as HTMLElement);
    this.originalTotalWidth = this.menuItemSizes.reduce(
      (acc, cur) => acc + cur,
      0,
    );
    this.handleResize();
    // prevent the overflowed indicator from taking space;
    setStyle(lastOverflowedIndicatorPlaceholder, 'display', 'none');
  };
```
当组件挂载后对每个菜单项加了这个监听器，而且这个方法里面的都是重新计算所有菜单项的大小，
因此当菜单项多了后，只要一隐藏再展示，所有菜单项的监听器都会触发，此方法又是直接操作DOM就非常消耗性能:

![WX20200513-212420](https://user-images.githubusercontent.com/33770367/81818560-c43db980-9560-11ea-82dd-cab9539469da.png)

因此可以给这个方法加上防抖，我在本地试了试加上后就好了，就是不知道会不会有其他问题？

**Comment by afc163** [comment]
可以的，来个 PR 吧~

**Comment by Kermit-Xuan** [comment]
是用`throttle-debounce`这个么？另外防抖时间怎么控制呢？

**Comment by Kermit-Xuan** [comment]
[#319](https://github.com/react-component/menu/pull/319)， 用`throttle-debounce`加了防抖时间100ms，但是现在从resize到重新计算完成会有100ms的时间差，不知道会不会有影响。

**Comment by afc163** [comment]
> 但是现在从resize到重新计算完成会有100ms的视觉时间差。

有明显的问题么？来个视频看看。

**Comment by Kermit-Xuan** [comment]
![u5ymy-1go10](https://user-images.githubusercontent.com/33770367/81900899-49bc7a80-95f0-11ea-8fa7-17a353ccc048.gif)

**Comment by afc163** [comment]
确实有点蛋疼。

1. 用 `lodash/throttle`，和其他依赖保持一致，可以省一点体积。
2. 打开 `leading: true`。

**Comment by Kermit-Xuan** [comment]
一个问题就是点toggle出现的时候先显示全部菜单然后过100ms才会换成`...`按钮，另一个就是resize触发后100ms后才会重新计算显示，不能立即看到。

**Comment by Kermit-Xuan** [comment]
> 确实有点蛋疼。
> 
> 1. 用 `lodash/throttle`，和其他依赖保持一致，可以省一点体积。
> 2. 打开 `leading: true`。

👌，我试试

**Comment by Kermit-Xuan** [comment]
`rc-menu` 8.2.0 版本中已解决此问题。
