### ISSUE TITLE
Input/Search maxLength not working with type number

### ISSUE THREAD

**Issue by vaibhavi3t** [ant-design/ant-design#23967]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-lamarr-58jo4?file=/src/App.js)

### Steps to reproduce
I have implemented search with maxLength. 
The issue is mostly with input type number. The maxLength property is not working 

### What is expected?
If Search/Input is configured with maxLength:10 (type="number")
Then user should not be able to enter more than 10 digits

### What is actually happening?
Currently user is able to enter digits more than maxLength

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | macOS Catalina version 10.15.3 |
| Browser | Chrome Version 81.0.4044.129 |

**Comment by afc163** [comment]
Native input behaves in same way: https://codesandbox.io/s/distracted-wind-96hfo

**Comment by vaibhavi3t** [comment]
@afc163 
Agreed not supported in native input but can't be provide support in antd input?

**Comment by hengkx** [comment]
Can you consider supporting it? @afc123
