### ISSUE TITLE
ConfigProvider & LocalProvider not work properly when import components from antd/lib

### ISSUE THREAD

**Issue by Renderz** [ant-design/ant-design#23966]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Renderz/reproduce](https://github.com/Renderz/reproduce)

### Steps to reproduce
```yarn start```

## 
1. locale works fine when import from antd or antd/es/table
2. locale not works when import from antd/lib/table

### What is expected?
locale works on import from 'antd/lib/table'

### What is actually happening?
locale works not properly after version 4.1.1

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | macOs Catalina |
| Browser | chrome |

**Comment by yoyo837** [comment]
https://ant.design/components/config-provider-cn/#FAQ

**Comment by afc163** [comment]
```diff
- import { ConfigProvider } from 'antd';
- import Table from 'antd/lib/table';
- import zh_CN from 'antd/es/locale/zh_CN'
+ import { ConfigProvider, Table } from 'antd';
+ import zh_CN from 'antd/es/locale/zh_CN'
```

Don't mix `es` and `lib` when using antd.
