### ISSUE TITLE
4版本以上 tree组件 多次点击会出现错误

### ISSUE THREAD

**Issue by sherryhhx** [ant-design/ant-design#23965]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/23964](https://github.com/ant-design/ant-design/issues/23964)

### Steps to reproduce
https://github.com/ant-design/ant-design/issues/23964

### What is expected?
保持与3一致

### What is actually happening?
出错

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.9 |
| System | mac |
| Browser | chrome 81.0.4044.138 |

**Comment by sherryhhx** [comment]
![image](https://user-images.githubusercontent.com/19605920/81396619-52c4cc00-9158-11ea-8334-d66b9eedba0a.png)

**Comment by zombieJ** [comment]
https://github.com/react-component/tree/commit/1a783fda3c411e1be75fb5c4edbb09792d479b6e 有修过，升级一下依赖试试？

**Comment by afc163** [comment]
@sherryhhx

**Comment by afc163** [comment]
close for no response
