### ISSUE TITLE
ToolTip component used with Button[disabled], Button className attribute inheritance error.

### ISSUE THREAD

**Issue by JinHe-PerkinElmer** [ant-design/ant-design#23961]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/empty-wood-pck8e?file=/index.js)

### Steps to reproduce
As this codesandbox demo, you can press f12 and find, Button's className 'tl-btn' is inherited by button's parent node 'span', not button itself.

### What is expected?
Normally, we expect Button's props like 'className' should be reflect to the props of button element, not other element.

### What is actually happening?
Because of this bug, it's hard to adjust this disabled button's style, which is terrible.

| Environment | Info |
|---|---|
| antd | 3.26.7 |
| React | "react": "16.9.0", |
| System | Win10 |
| Browser | Chrome Version 81.0.4044.129 (Official Build) (64-bit) |

---
There is no problem in earlier version of antd '3.7.2'.

**Comment by afc163** [comment]
#22453
#21404 
#17449 
#4865

**Comment by JinHe-PerkinElmer** [comment]
I think this is not reasonable. you can add a span element for disabled button, but should't remove the button's props.
