### ISSUE TITLE
button text not align center when default font-size-base is changed

### ISSUE THREAD

**Issue by rppig42** [ant-design/ant-design#23979]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-n22de?file=/index.js)

### Steps to reproduce
1. change the default @font-size-base to other values like 13px

### What is expected?
button text should be vertical align

### What is actually happening?
 the button text won't vertical align

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.9.21 |
| System | Mac OS 101.15 |
| Browser | Chrome latest |

**Comment by afc163** [comment]
It works well in my machine. Please provide reproduce and screenshot.

**Comment by rppig42** [comment]
@afc163 forgive me but after my double check, could you please try it agin in you local env with **small** button.

![image](https://user-images.githubusercontent.com/48581046/81500854-6f533680-9307-11ea-96c0-f9643553cb50.png)
