### ISSUE TITLE
Slider 的 onChange 和 onAfterChange 和预想的值不一样

### ISSUE THREAD

**Issue by codetker** [ant-design/ant-design#23970]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6uto1?file=/src/App.js:0-991)

### Steps to reproduce
The onChange functiion and onAfterChange function has diffrent appearance on user`s action on slider and text.[Slider 组件用户点击滑动条和点击文字两种情况下 onChange 和 onAfterChange 表现不一致]
here  is the code
```
import * as React from "react";
import { Slider } from "antd";

const { Component } = React;

const marks = {
    0: "0°C",
    26: "26°C",
    37: "37°C",
    100: {
        style: {
            color: "#f50"
        },
        label: <strong>100°C</strong>
    }
};

export default class keys extends Component {
    state = {
        value: 37
    };
    componentDidMount() {
        // todo
    }

    onChange = value => {
        console.log("222=>", value);
        if (value < 30) {
            return;
        }
        this.setState({
            value
        });
    };

    onAfterChange = (aa) => {
        console.log("111=>", aa);
    };

    render() {
        return (
            <Slider
                marks={marks}
                value={this.state.value}
                step={null}
                onChange={this.onChange}
                onAfterChange={this.onAfterChange}
                defaultValue={37}
            />
        );
    }
}
```
Result
![](https://i.ibb.co/ZJXVWY6/slider.png)

### What is expected?
The same console

### What is actually happening?
Different value

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.3.1 |
| System | mac |
| Browser | chrome |

---
工程中使用 antD 版本是 3.26.16，那个时候其实如果 onChange return 空值的情况下，点击文字 onAfterChange 会触发，而点击 sliderBar  onAfterChange 不会触发。所以有点好奇 antD  最新版本是否存在同样的问题，结果发现虽然都会触发，但是其实还是有不一致的地方。另外，页面失去焦点又获取焦点会重复触发 onAfterChange，很奇怪，不过已经看到有对应的 issue 了。

**Comment by afc163** [comment]
本地测试没看出来有啥区别。
