### ISSUE TITLE
"InputNumber" component bug for the zero value.

### ISSUE THREAD

**Issue by JulinPeng** [ant-design/ant-design#2397]
#### 本地环境

- antd 版本: 1.6.4
- 操作系统及其版本：Win10
- 浏览器及其版本: Chrome  51.0.2704.106 m

#### 你做了什么？

引入 antd 了 ` InputNumber`  :

`<InputNumber step={0.001} defaultValue={0}/>`

#### 你期待的结果是：

show "0" in the InputNumber

#### 实际上的结果：

show nothing

#### Analysis and Resolution:

` render() in InputNumber.js` :

```
        var inputDisplayValue = undefined;
        if (this.state.focused) {
           // original:
           // inputDisplayValue = this.state.inputValue || ''; 

           // fixed:
            var stateInputValue = this.state.inputValue;
            inputDisplayValue = isNaN(stateInputValue) ? '' : stateInputValue;
        } else {
            // original:
            // inputDisplayValue = this.state.value || '';

            // fixed:
            var stateValue = this.state.value;
            inputDisplayValue = isNaN(stateValue) ? '' : stateValue;
        }
```

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/input-number/commit/730073b7720398727b03db5ef20402a88b44d7a5

Reinstall.
