### ISSUE TITLE
Responsive height for Table

### ISSUE THREAD

**Issue by GeorgeCodeHub** [ant-design/ant-design#23974]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We have the following example:

https://stackblitz.com/edit/react-imocxq

We want the table height to fit the parent’s available height. Ideally, we want:
1.	the footer to always be docked at the bottom of the parent container. 
2.	If the table contains a few rows, the footer should remain docked at the bottom. 
3.	If the table contains more rows than fit the parent’s height and needs to overflow then the overflow should be visible only for the table body, and the footer should remain docked at the bottom and not be pushed downwards.
4.	A flexbox approach if possible (it seems to us that this is a flex scenario)

What we don’t want:
1.	A height: 100vh approach
2.	A calc (100vh - ***px) involved (because we want to use the methodology in arbitrary component hierarchies inside our solution)
3.	Fixed heights in the table
4.	To use absolute/fixed positioning
5.	No 3rd party solutions (if possible)
6.	To use. offsetHeight

### What does the proposed API look like?

<Table type="flex"/>

Example with a few items in Table:
![Web image few](https://user-images.githubusercontent.com/54906099/81415294-ed211180-9150-11ea-8f00-7211ddab179f.png)

Example with a lot of items in Table:
![Web image a lot](https://user-images.githubusercontent.com/54906099/81415305-f1e5c580-9150-11ea-83b5-5a26184ff16c.png)

**Comment by yoyo837** [comment]
Can #21584 meet your needs?

**Comment by afc163** [comment]
We probably won't implement this kind of feature, you can try to customize Table `components.row`.

**Comment by leecjson** [comment]
> We probably won't implement this kind of feature, you can try to customize Table `components.row`.

Why? To fit it's parent height has a lot of advantage.

```
.ant-table-wrapper {
  height: 100%;

  .ant-spin-nested-loading {
    height: 100%;

    .ant-spin-container {
      height: 100%;
      display: flex;
      flex-flow: column nowrap;

      .ant-table {
        flex: auto;
        overflow: hidden;

        .ant-table-container {
          height: 100%;
          display: flex;
          flex-flow: column nowrap;

          .ant-table-header {
            flex: none;
          }

          .ant-table-body {
            flex: auto;
            overflow: scroll;
          }
        }
      }

      .ant-table-pagination {
        flex: none;
      }
    }
  }
}
```

**Comment by nora-white** [comment]
This would be an amazing feature. This has plagued the application that I work on for several years, even after upgrading to v4. We have to manually handle the scroll, and it is extremely finicky and breaks easily. Quite disappointing to hear that Antd `won't do` this.

**Comment by jahshatta** [comment]
> > We probably won't implement this kind of feature, you can try to customize Table `components.row`.
> 
> Why? To fit it's parent height has a lot of advantage.
> 
> ```css
> .ant-table-wrapper {
>   height: 100%;
> 
>   .ant-spin-nested-loading {
>     height: 100%;
> 
>     .ant-spin-container {
>       height: 100%;
>       display: flex;
>       flex-flow: column nowrap;
> 
>       .ant-table {
>         flex: auto;
>         overflow: hidden;
> 
>         .ant-table-container {
>           height: 100%;
>           display: flex;
>           flex-flow: column nowrap;
> 
>           .ant-table-header {
>             flex: none;
>           }
> 
>           .ant-table-body {
>             flex: auto;
>             overflow: scroll;
>           }
>         }
>       }
> 
>       .ant-table-pagination {
>         flex: none;
>       }
>     }
>   }
> }
> ```

Hello. Are you still using this workarond or find new solution?
Can't get it work on last antd version.

**Comment by xinghul** [comment]
for anyone who wants a custom solution:
```typescript
const [tableHeight, setTableHeight] = useState(600);
// ref is the Table ref.
const ref = useRef<HTMLDivElement>(null);

useLayoutEffect(() => {
  const node = ref.current;
  const { top } = node.getBoundingClientRect();

  // normally TABLE_HEADER_HEIGHT would be 55.
  setTableHeight(window.innerHeight - top - TABLE_HEADER_HEIGHT);
}, [ref]);
```

and you can just set the scrollable height like this:
```typescript
<Table
  ...
  scroll={{ y: tableHeight }}
  ...
/>
```

**Comment by ahsansher** [comment]
You can adjust this as per your requirement.

`scroll={{ y: 'calc(100vh - 4em)' }}`

**Comment by bboure** [comment]
Here is my solution based on @xinghul's

```ts
export const useTableHeight = (ref: RefObject<Element>) => {
  // Keep the Table the height of the parent.
  const [tableHeight, setTableHeight] = useState(600);
  const resizeTable = useDebouncedCallback(
    () => {
      const node = ref.current;
      if (!node) {
        return;
      }
      const { height } = node.getBoundingClientRect();
      // height of the content minus the header and footer
      setTableHeight(height - 55 - 48);
    },
    100,
    {
      trailing: true,
      maxWait: 100,
    },
  );

  useLayoutEffect(() => {
    window.addEventListener('resize', resizeTable);

    return () => {
      window.removeEventListener('resize', resizeTable);
    };
  }, [resizeTable]);

  return tableHeight;
};

```

```jsx

const contentRef = useRef<HTMLDivElement>(null);
const tableHeight = useTableHeight(contentRef);

// ...
<div ref={contentRef}> 
  <Table
    ...
    scroll={{ y: tableHeight }}
    ...
  />
</div>
```

Also see https://www.npmjs.com/package/use-debounce#debounced-callbacks

**Comment by huynhttdev** [comment]
It's working! Thanks @bboure

**Comment by tnstjd120** [comment]
Thanks for the good source.

```setTableHeight(height - 55 - 48)```

What are the values ​​of 55 and 48 here?

@bboure

**Comment by bboure** [comment]
@tnstjd120 It's the height of the header and the footer. YMMV

**Comment by deepak-techprescient** [comment]
Adding to @bboure's solution, this is what I used for dynamic header and footer heights. This solved the problem for changing heights of the header and footer due to wrapping of text.

```
import { useState, useLayoutEffect } from 'react';
import { debounce } from 'lodash';
import $ from 'jquery';

export const useTableHeight = (ref: React.RefObject<Element>) => {
  const [tableHeight, setTableHeight] = useState<number | undefined>(undefined);

  const resizeTable = debounce(() => {
    const node = ref.current;

    if (node) {
      const tableContainerHeight = $(node).outerHeight(true);
      const tableHeaderHeight = $(node).find('.ant-table-thead')?.outerHeight(true);
      const tableFooterHeight = $(node).find('.ant-pagination')?.outerHeight(true);

      if (tableContainerHeight && tableHeaderHeight && tableFooterHeight) {
        setTableHeight(tableContainerHeight - tableHeaderHeight - tableFooterHeight);
      }
    }
  }, 100);

  useLayoutEffect(() => {
    resizeTable();
    window.addEventListener('resize', resizeTable);

    return () => {
      window.removeEventListener('resize', resizeTable);
    };
  }, [resizeTable]);

  return tableHeight;
};
```

**Comment by thoughtpalette** [comment]
Using some methods provide here, was able to come up with a suitable `react-jss` solution that seems to work so far:
```
		container: {
			height: '100%',
			overflowY: 'auto',
		},
	        table: {
			'& .ant-table-wrapper, & .ant-spin-nested-loading, & .ant-spin-container':
				{
					height: '100%',
				},

			'& .ant-table': {
				height: `calc(100% - ${ANTD_TABLE_FOOTER_HEIGHT_PX}px)`,
				overflowY: 'auto',
			},

			'& .ant-table-content': {
				overflow: 'inherit !important', // Required for sticky header
			},

			'& .ant-table-thead > tr > th': {
				position: 'sticky',
				top: 0,
				zIndex: 10,
			},
		},
```

**Comment by scrynaxx** [comment]
I also faced a problem with scroll height calculation.
I managed to make such a hook for height calculation. This is a hastily version, but it works great, no need to write crutches in styles. You can add more checks, extend it somehow.
I added an option to stretch by page height and calculate scroll height with pagination height. The effect for setting the table height is called separately, because this element is drawn after tbody (such a feature of ant table).
For debounce I used package [use-debounce](https://www.npmjs.com/package/use-debounce)

Just place the hook in a place convenient for you, for example:
<pre>
use-table-scroll/
    |-- use-table-scroll.hook.ts
    |-- use-table-scroll.types.ts
    |-- use-table-scroll-lib.ts
    |-- index.ts</pre>

_Hook types:_ 
```
type UseTableScroll = {
  tableRef: RefObject<TableRef>;
  scroll: TableProps["scroll"];
};

type ScrollX = string | number | true | undefined;
```

_Hook lib_
```
const getPaginationHeight = (tableWrapper: HTMLDivElement) => {
  let calculatedHeight = 0;

  const paginationElement = tableWrapper.getElementsByClassName("ant-table-pagination")[0];
  if (!paginationElement) return calculatedHeight;

  const { height } = paginationElement.getBoundingClientRect();
  const styles = window.getComputedStyle(paginationElement);
  const marginTop = +styles.marginTop.replace("px", "");
  const marginBottom = +styles.marginBottom.replace("px", "");

  calculatedHeight += height + marginTop + marginBottom;

  return calculatedHeight;
};
```

_Hook:_
```
export const useTableScroll = (
  scrollX: ScrollX = true,
  stretchByPage: boolean = true,
  delay: number = 50,
): UseTableScroll => {
  const [scrollY, setScrollY] = useState<number | undefined>();
  const tableRef = useRef<TableRef>(null);

  const calcScrollY = () => {
    const tableWrapper = tableRef.current?.nativeElement;
    if (!tableWrapper) return;

    const tBody = tableWrapper.getElementsByTagName("tbody")[0];
    if (!tBody) return;

    const { y: tBodyY } = tBody.getBoundingClientRect();
    const totalHeight = window.innerHeight - tBodyY - getPaginationHeight(tableWrapper);

    // if (stretchByPage) setTableHeight(tableWrapper, totalHeight);
    setScrollY(totalHeight);
  };

  const debounce = useDebouncedCallback(calcScrollY, delay);

  useEffect(() => {
    debounce();
    window.addEventListener("resize", calcScrollY);

    return () => {
      window.removeEventListener("resize", calcScrollY);
    };
  }, [tableRef]);

  useEffect(() => {
    if (!stretchByPage) return;

    const tableWrapper = tableRef.current?.nativeElement;
    if (!tableWrapper) return;

    const tableBody = tableWrapper.getElementsByClassName("ant-table-body")[0] as HTMLDivElement;
    if (!tableBody) return;

    tableBody.style.height = `${scrollY}px`;
  }, [!!scrollY]);

  return { tableRef, scroll: { x: scrollX, y: scrollY } };
};
```

### Usage
```
import { useTableScroll } from "./use-table-scroll";

const ExampleComponent = () => {
  const { tableRef, scroll } = useTableScroll();

  return (
    <Table
      ref={tableRef}
      rowKey={"itemId"}
      columns={SOME_COLUMNS}
      dataSource={SOME_ITEMS}
      scroll={scroll}
      pagination={SOME_PAGINATION_STATE}
    />
  );
};
```

**Comment by xavierPlainconcepts** [comment]
> I also faced a problem with scroll height calculation. I managed to make such a hook for height calculation. This is a hastily version, but it works great, no need to write crutches in styles. You can add more checks, extend it somehow. I added an option to stretch by page height and calculate scroll height with pagination height. The effect for setting the table height is called separately, because this element is drawn after tbody (such a feature of ant table). For debounce I used package [use-debounce](https://www.npmjs.com/package/use-debounce)
> 
> Just place the hook in a place convenient for you, for example:
> 
> use-table-scroll/
>     |-- use-table-scroll.hook.ts
>     |-- use-table-scroll.types.ts
>     |-- use-table-scroll-lib.ts
>     |-- index.ts
> _Hook types:_
> 
> ```
> type UseTableScroll = {
>   tableRef: RefObject<TableRef>;
>   scroll: TableProps["scroll"];
> };
> 
> type ScrollX = string | number | true | undefined;
> ```
> 
> _Hook lib_
> 
> ```
> const getPaginationHeight = (tableWrapper: HTMLDivElement) => {
>   let calculatedHeight = 0;
> 
>   const paginationElement = tableWrapper.getElementsByClassName("ant-table-pagination")[0];
>   if (!paginationElement) return calculatedHeight;
> 
>   const { height } = paginationElement.getBoundingClientRect();
>   const styles = window.getComputedStyle(paginationElement);
>   const marginTop = +styles.marginTop.replace("px", "");
>   const marginBottom = +styles.marginBottom.replace("px", "");
> 
>   calculatedHeight += height + marginTop + marginBottom;
> 
>   return calculatedHeight;
> };
> ```
> 
> _Hook:_
> 
> ```
> export const useTableScroll = (
>   scrollX: ScrollX = true,
>   stretchByPage: boolean = true,
>   delay: number = 50,
> ): UseTableScroll => {
>   const [scrollY, setScrollY] = useState<number | undefined>();
>   const tableRef = useRef<TableRef>(null);
> 
>   const calcScrollY = () => {
>     const tableWrapper = tableRef.current?.nativeElement;
>     if (!tableWrapper) return;
> 
>     const tBody = tableWrapper.getElementsByTagName("tbody")[0];
>     if (!tBody) return;
> 
>     const { y: tBodyY } = tBody.getBoundingClientRect();
>     const totalHeight = window.innerHeight - tBodyY - getPaginationHeight(tableWrapper);
> 
>     setScrollY(totalHeight);
>   };
> 
>   const debounce = useDebouncedCallback(calcScrollY, delay);
> 
>   useEffect(() => {
>     debounce();
>     window.addEventListener("resize", calcScrollY);
> 
>     return () => {
>       window.removeEventListener("resize", calcScrollY);
>     };
>   }, [tableRef.current?.nativeElement]);
> 
>   useEffect(() => {
>     if (!stretchByPage) return;
> 
>     const tableWrapper = tableRef.current?.nativeElement;
>     if (!tableWrapper) return;
> 
>     const tableBody = tableWrapper.getElementsByClassName("ant-table-body")[0] as HTMLDivElement;
>     if (!tableBody) return;
> 
>     tableBody.style.height = `${scrollY}px`;
>   }, [scrollY]);
> 
>   return { tableRef, scroll: { x: scrollX, y: scrollY } };
> };
> ```
> 
> ### Usage
> ```
> import { useTableScroll } from "./use-table-scroll";
> 
> const ExampleComponent = () => {
>   const { tableRef, scroll } = useTableScroll();
> 
>   return (
>     <Table
>       ref={tableRef}
>       rowKey={"itemId"}
>       columns={SOME_COLUMNS}
>       dataSource={SOME_ITEMS}
>       scroll={scroll}
>       pagination={SOME_PAGINATION_STATE}
>     />
>   );
> };
> ```

Works great, thanks!

**Comment by AsuraKev** [comment]
> Here is my solution based on @xinghul's
> 
> ```ts
> export const useTableHeight = (ref: RefObject<Element>) => {
>   // Keep the Table the height of the parent.
>   const [tableHeight, setTableHeight] = useState<number>();
>   const resizeTable = useDebouncedCallback(
>     () => {
>       const node = ref.current;
>       if (!node) {
>         return;
>       }
>       const { height } = node.getBoundingClientRect();
>       // height of the content minus the header and footer
>       setTableHeight(height - 55 - 48);
>     },
>     100,
>     {
>       trailing: true,
>       maxWait: 100,
>     },
>   );
> 
>   useLayoutEffect(() => {
>     resizeTable();
>     window.addEventListener('resize', resizeTable);
> 
>     return () => {
>       window.removeEventListener('resize', resizeTable);
>     };
>   }, [resizeTable]);
> 
>   return tableHeight;
> };
> ```
> 
> ```js
> const contentRef = useRef<HTMLDivElement>(null);
> const tableHeight = useTableHeight(contentRef);
> 
> // ...
> <div ref={contentRef}> 
>   <Table
>     ...
>     scroll={{ y: tableHeight }}
>     ...
>   />
> </div>
> ```
> 
> Also see https://www.npmjs.com/package/use-debounce#debounced-callbacks

I am trying this one out, but the flex box container height is always the height of the table so resizing is not working for me:/

**Comment by FilippTrigub** [comment]
It's 2 years later and people still have to build workarounds for such a basic feature. Bizarre...

**Comment by YuvalPeretz** [comment]
Honestly, one of the things that they need to add ASAP

**Comment by YuvalPeretz** [comment]
I just want to share a solution that works for a table with at least 1 row (altering the CSS could lead to 100% without values as well, I might share this later):

A few key notes:

1. I moved the pagination to the title, you can do the same by moving it to the footer, DONT USER THE BUILT IN as it really messes things up.
2. You need to pass the `parentRef` for reference to the hight which fills it.
3. ITS NOT PERFECT! so if you have changes to make to even make this better please do. 
4. It is responsive to both PC and Phones

```
//CustomTable.tsx - Need to pass the parent's ref
import { Table, TableProps } from "antd";
import React, { useEffect, useRef, useState } from "react";

type CustomTableProps = {
  parentRef?: React.RefObject<HTMLElement>;
} & TableProps<any>;

export default function CustomTable(props: CustomTableProps) {
  const { parentRef, ...tableProps } = props;
  const [tableHeight, setTableHeight] = useState<number | undefined>(parentRef?.current?.clientHeight);
  const tableRef = useRef<HTMLDivElement>(null);
  const [extraHeight, setExtraHeight] = useState(50);

  useEffect(() => {
    let newExtraHeight = 50;
    if (tableRef.current) {
      const title = tableRef.current.querySelector(".ant-table-title");
      if (title) newExtraHeight += title.clientHeight;
      const pagination = tableRef.current.querySelector(".ant-table-pagination");
      if (pagination) newExtraHeight += (pagination as HTMLElement).clientHeight;
      const footer = tableRef.current.querySelector(".ant-table-footer");
      if (footer) newExtraHeight += (footer as HTMLElement).clientHeight;
    }
    setExtraHeight(newExtraHeight);
  }, [props.title, props.pagination]);

  useEffect(() => {
    if (!parentRef?.current) return;
    let observeTarget = parentRef.current;
    let resizeObserver: ResizeObserver | undefined;
    setTimeout(() => {
      const handleResize = (entries: ResizeObserverEntry[]) => {
        for (let entry of entries) {
          const newHeight = entry.contentRect.height;
          setTableHeight(newHeight);
        }
      };

      resizeObserver = new ResizeObserver(handleResize);
      resizeObserver.observe(observeTarget);

      setTableHeight(observeTarget.clientHeight);
    }, 100);

    return () => {
      resizeObserver?.unobserve(observeTarget);
      resizeObserver?.disconnect();
    };
  }, [parentRef]);

  return (
    <div ref={tableRef} style={{ height: "100%", width: "100%" }}>
      <Table
        {...tableProps}
        scroll={{
          y: tableHeight ? tableHeight - extraHeight : undefined,
          ...tableProps.scroll,
        }}
      />
    </div>
  );
}
```

Use case (absolutely not perfect): 
```
<Card
      title={
        <Typography.Title>
          <AiOutlineAlert />
          Alerts
        </Typography.Title>
      }
      style={{ height: "100%", overflow: "hidden" }}
      styles={{ body: { height: "90%", padding: `1px 0px 50px 0px`, overflowY: "auto" } }}
    >
      <Flex ref={flexRef} style={{ height: "100%", width: "100%" }}>
        <CustomTable
          title={() => (
            <Space style={{ overflowX: "auto", overflowY: "hidden", width: "100%" }}>
              <Pagination
                style={{ width: "100%" }}
                simple
                defaultCurrent={1}
                pageSize={15}
                showSizeChanger={false}
                onChange={setPaginationCurrent}
                total={data.length}
              />
              <OpenAlerts />
              <Legend />
            </Space>
          )}
          parentRef={flexRef}
          columns={columns}
          dataSource={data}
          scroll={{ x: 500 }}
          pagination={{
            pageSize: 15,
            position: ["none"],
            current: paginationCurrent,
          }}
        />
      </Flex>
    </Card>
```

**Comment by balboFK** [comment]
Hello everyone, kicking back an old one here huh?
@afc163 @zombieJ @li-jia-nan  I read above that you guys don't plan on implementing this, but i dont know if you are still following this discussion but it seems to be a very heated case on this topic. Is it too dificult to implement or is it some other reason to not do so? I saw a lot of workarounds and I also have mine, but this seems to be a good oportunity to create an out of the box solution and a rewrite for the table component height and scroll controls. I am now trying to use the new Splitter component for example, and using two tables, one on the top split panel, and one on the bottom split panel, and to controls their heights to match the container is incredible awful and annoying. I honestly think this API should come from the table itself, since the height control is coming from it. If you need an example I'll file a new issue and we can discuss there and reference this one. I think we should provide an API that allows the height control to be done withouth having to do workarounds with scroll X and Y. I also would love to see any official examples from you guys where this is used correctly with container parenting and dynamic sizes, now that we have the Splitter component. I would be happy to help and hear from you guys.

**Comment by li-jia-nan** [comment]
> Hello everyone, kicking back an old one here huh? @afc163 @zombieJ @li-jia-nan I read above that you guys don't plan on implementing this, but i dont know if you are still following this discussion but it seems to be a very heated case on this topic. Is it too dificult to implement or is it some other reason to not do so? I saw a lot of workarounds and I also have mine, but this seems to be a good oportunity to create an out of the box solution and a rewrite for the table component height and scroll controls. I am now trying to use the new Splitter component for example, and using two tables, one on the top split panel, and one on the bottom split panel, and to controls their heights to match the container is incredible awful and annoying. I honestly think this API should come from the table itself, since the height control is coming from it. If you need an example I'll file a new issue and we can discuss there and reference this one. I think we should provide an API that allows the height control to be done withouth having to do workarounds with scroll X and Y. I also would love to see any official examples from you guys where this is used correctly with container parenting and dynamic sizes, now that we have the Splitter component. I would be happy to help and hear from you guys.

In fact, we plan to refactor the Table component in the future. I am not sure whether the current Table will add new features. This may needs to be discussed with the official team.

**Comment by balboFK** [comment]
I see! Thanks for the heads up @li-jia-nan ! So I guess we might see it on V6 of Antd or can we still hope for a V5 release window? Since the table is a core component from Antd, and as much as sometimes it cant be hard to implement some solutions with it, most of the common use cases it works very well out of the box. But as always, if we can make it even better and more customizable it most certainly would be for the best. If you get some insight from the team that can be shared with use, please do so. Thanks again for taking a look at this.

**Comment by balboFK** [comment]
Got it! Thanks for your time @li-jia-nan . I'll keep an eye out for this one. For now I'll use my "work around" to get it how I need.

**Comment by paramiman** [comment]
Would love to see this as an added feature.

**Comment by tuzixiangs** [comment]
Is there a good solution for antd5 now

**Comment by ChristianVega5421** [comment]
Still having issues with this. I used the solution on top and as long as the table does not change its content works. The moment it starts changing is broken. I even have an issue where it starts resizing in width when there are no elements. Trying this in Transfers' table. Also it is because I am not a Front End developer lol...

**Comment by trieu-hphuc96** [comment]
> > We probably won't implement this kind of feature, you can try to customize Table `components.row`.
> 
> Why? To fit it's parent height has a lot of advantage.
> 
>     .ant-table-wrapper {
>       height: 100%;
> 
>      .ant-spin-nested-loading {
>        height: 100%;
> 
>        .ant-spin-container {
>          height: 100%;
>          display: flex;
>          flex-flow: column nowrap;
> 
>          .ant-table {
>            flex: auto;
>            overflow: hidden;
> 
>            .ant-table-container {
>              height: 100%;
>              display: flex;
>              flex-flow: column nowrap;
> 
>              .ant-table-header {
>                flex: none;
>              }
> 
>              .ant-table-body {
>                flex: auto;
>                overflow: scroll;
>              }
>            }
>          }
> 
>          .ant-table-pagination {
>            flex: none;
>          }
>        }
>      }
>    }

Thank you, it's still working for me. Just have a little update to show the pagination footer


       .ant-table-wrapper {
             height: 100%;

            .ant-spin-nested-loading {
                height: 100%;

                .ant-spin-container {
                    height: 100%;
                    display: flex;
                    flex-flow: column nowrap;

                    .ant-table {
                        flex: auto;
                        overflow: hidden;
                        display: flex;
                        flex-direction: column;

                        .ant-table-container {
                            height: 100%;
                            display: flex;
                            flex-flow: column nowrap;
                            max-height: 100%;
                            overflow: hidden;

                            .ant-table-header {
                                flex: none;
                            }

                            .ant-table-body {
                                flex: auto;
                                overflow: scroll;
                            }
                        }

                        .ant-table-footer {
                            border-top: 1px solid var(--ant-table-border-color);
                        }
                    }

                    .ant-table-pagination {
                        flex: none;
                    }
                }
            }
        }
