### ISSUE TITLE
Allow setting border of Message popup

### ISSUE THREAD

**Issue by oleks12345** [ant-design/ant-design#23971]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When showing warning/error it isn't clear if its an error or normal message, only indication is icon.

Adding a red border in error, and orange in warning would help.

### What does the proposed API look like?
possible options
* just adding a border to warring, error would be great - but that would change existing applications. 
* Adding ability to add class to ant-message-notice-content/ant-message-notice would work great.
* Adding class near  ant-message-notice-content or ant-message-notice that would indicate type of message (error, warning, success..) so user can style it, using that class.

**Comment by afc163** [comment]
trace in #16659
