### ISSUE TITLE
Unable to clear range picker after date is selected

### ISSUE THREAD

**Issue by schoenbl** [ant-design/ant-design#23982]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wispy-rgb-xidbz?file=/src/App.js:0-754)

```
import React, { useState } from "react";
import { DatePicker } from "antd";
import moment from "moment";

const { RangePicker } = DatePicker;
import "antd/dist/antd.css";

const DataTable = props => {
  const [dateRange, changeDateRange] = useState(null);

  const onDateRangeChange = dateRange => {
    if (dateRange) {
      changeDateRange(returnMomentDateRange(dateRange[0], dateRange[1]));
    }
  };

  const returnMomentDateRange = (start, finish) => {
    return [moment(start, "YYYY-MM-DD"), moment(finish, "YYYY-MM-DD")];
  };

  return (
    <RangePicker
      allowClear={true}
      size="small"
      picker="date"
      value={dateRange !== "" ? dateRange : ""}
      onChange={onDateRangeChange}
    />
  );
};

export default DataTable;
```
### Steps to reproduce
Select a date, then try to clear the date with the 'x' logo.

### What is expected?
The dates to clear to have no dates for the start and finish.

### What is actually happening?
Nothing.

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
It works well in your codesandbox.
