### ISSUE TITLE
Antd 编译结果的疑问

### ISSUE THREAD

**Issue by GuichiZhao** [ant-design/ant-design#23988]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/introduce-cn](https://ant.design/docs/react/introduce-cn)

### Steps to reproduce
na

### What is expected?
na

### What is actually happening?
na

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | latest |
| System | na |
| Browser | latest |

---
首先 
首页上说： 注意：antd 默认支持基于 ES module 的 tree shaking，不使用以下插件也会有按需加载的效果。
如果只是js的话的确可以tree shaking，不过css怎么办呢？以es/affix/index.js 为例我没有找到相应的引入css的地方
解决方案：只要在编译的时候在index.js加上css的入口就可以了，不过这样的话import-plugin就会有问题，可以权衡一下

然后我在 es/affix/index.js看到了许多类似这样的代码
`function _extends() { _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i  ) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; }; return _extends.apply(this, arguments); }
`
这些都是babel编译出来的，而且在每个文件里反复出现，考虑一下babel-plugin-transform-runtime，可以减少用户的最终文件的size

最后，在很多个es文件夹下，index.js 都会引用很多些其他的文件，考虑用rollup进行打包，可以进一步减少size。

综上：
第一点是我的质疑
二三点是我的建议

如果是我考虑的不周到恳请指出，如果这些确实是问题，我愿意帮助修复

**Comment by afc163** [comment]
1. css 没办法 tree shaking，目前只能靠 `babel-plugin-import` 的 style 属性来做按需加载。
2. 不只是 runtime，还需要把 babel 6 和 7 统一掉，欢迎来 PR，具体可以到 https://github.com/ant-design/ant-design/issues/22698 里回复跟进。
3. rollup 的方案 @zombieJ 应该试过了，比 webpack 小了不到 1 kB。欢迎你来尝试。也到 https://github.com/ant-design/ant-design/issues/22698 里跟进。

**Comment by GuichiZhao** [comment]
@afc163 
我也觉得css没法tree shaking
不过官网
https://ant.design/docs/react/introduce-cn
上那句
注意：antd 默认支持基于 ES module 的 tree shaking，不使用以下插件也会有按需加载的效果。
放在那里什么意思？想表达什么呢？

**Comment by yoyo837** [comment]
js 可以tree shaking，不含css，css需要全量引入吧！

**Comment by GuichiZhao** [comment]
@yoyo837  这么说也没错，不过官网上那句话真的有点迷。。。。

**Comment by GuichiZhao** [comment]
@afc163 @yoyo837 而且说css不能tree shaking我觉得真未必

**Comment by GuichiZhao** [comment]
@afc163 @yoyo837   我们试过了， 用rollup 写一下renderChunk把css加一个入口就可以tree shaking css

**Comment by yoyo837** [comment]
> @afc163 @yoyo837 我们试过了， 用rollup 写一下renderChunk把css加一个入口就可以tree shaking css

有兴趣来个PR看看吗？是否能兼容babel-plugin-import 一起使用？

**Comment by GuichiZhao** [comment]
@yoyo837  `babel-plugin-import` 完全没有意义， 用tree shaking就足够

**Comment by GuichiZhao** [comment]
@yoyo837 @afc163   你有微信吗，我给你看一下我们的项目，和antd的结构有一点像，不过就做到了只用tree shaking就可以按需加载。antd应该也没差，只不过现在不是很有时间看antd的build process

**Comment by GuichiZhao** [comment]
@yoyo837 
有了tree shaking我真的想不明白为什么要搞一个`babel-plugin-import`

**Comment by afc163** [comment]
babel-plugin-import 搞的时候还没有 webpack 2。现在这个插件的意义很小，样式即使全量加载对性能的影响也比 JS 小很多，我准备把相关的 warning 和文档都删掉。

**Comment by GuichiZhao** [comment]
@afc163 
现在es的folder的基础上，每一个component分别这样配一下能做到css按需加载，我们就这样，没什么问题。可以参考一下，我如果时间多的话也会发pr
```
//rollup.config.js
const cssFileName = 'index.css'
module.exports = ({ dir = 'es/button' }) => {
    return {
        input: 'button/index.js',
        output: [{
            format: 'es',
            dir
        },
        ],
        plugins: [
            postcss({
                extract: path.resolve(__dirname, dir, cssFileName),
                modules: true,
                plugins: [copyAssets()],
                use: ['less'],
                //provide a hit to copyAssets
                to: path.resolve(__dirname, dir, 'plugin-hint')
            }),
            {
                name: 'antd',
                renderChunk(code) {
                    //加上css的入口
                    return `import './${cssFileName}' \n` + code
                },
                resolveId(source) {
                    //如果不再component文件夹，不要resolve
                    if (source.startWith('../')) {
                        return { id: source, external: true };
                    }
                    return null;
                }

            },
        ],
    }
}

```

**Comment by afc163** [comment]
这样不行的，用户如果要引入 less 就会有问题。默认引入 css 文件也会默认要求用户配置 css-loader，有侵入性。真正要实现完美按需加载要等未来的 css in js 了。

**Comment by GuichiZhao** [comment]
`babel-plugin-import` 用户也是需要配css-loader的吧
>import DatePicker from 'antd/es/date-picker'; // 加载 JS
>import 'antd/es/date-picker/style/css'; // 加载 CSS

至于用less主要目的就是定制主题的，想想别的办法呗。就算将来用css in js了，也不可能再让用户添加compile time的逻辑了吧？

所以我觉得现在的话除了让用户配一下node_module里的css-loader别的地方体验应该不会比css in js差

**Comment by Airkro** [comment]
我也有做过相关尝试，webpack 确实可以搞定包括 css 在内的树摇，只需要每个组件 import 自己的样式，并且做的简单的配置就行了，所以上述的方案完全是可行的，对于webpack为主流的生态没有什么使用成本。

```json
{ "sideEffects": [ "*.less", "*.css" ] }
```

加 css-loader 不是大问题，问题是原先的代码里没有 import 样式，如果加上就成了breaking change。

**Comment by Airkro** [comment]
至于 css 换成 less 的办法也是有的，就是做多种发布（不管是分目录还是分包），例如 `antd/es` => `less`， `antd/lib` => `css`。但如果想给用户最大的选择权，至少要满足多个排列组合：

| es   | es + css  | es + less  |
| ---- | --------- | ---------- |
| lib  | lib + css | lib + less |

官方应该不会想做那么多种发布

**Comment by Airkro** [comment]
如果官方不做，私人定制也是一种路子，就是用代码生成的方式，生成可自动树摇的文件（esmodules 语法导入样式，也就是上述的 `es + css`，`es + less`），导出到 antd 目录或者创建一个新包。

再用 webpack 的 alias 移花接木。实际项目就只需要修改 alias 就能实现自动导入样式和树摇两个目的

**Comment by yoyo837** [comment]
直接PR上来学习下。

**Comment by zombieJ** [comment]
这样其实还是回到了 `babel-plugin-import`，相对的 webpack 做 alias 其实也容易给人埋坑，统一收到一个插件里会更通用一些。

**Comment by Airkro** [comment]
除非直接搞一个大版本更新，不然任何方法都会埋坑的，除非开发者很清楚的知道自己 import 的是啥。

我现在倾向于做一个 `@ant-design/magic` 的包，只要安装就能自动树摇并自动导入样式，前提是架手架支持。

但如果想要替换某个 `antd` 组件或其他高级案例，`babel-plugin-import` 仍是最佳选择。

**Comment by Airkro** [comment]
@yoyo837

PR 我就不开了，因为这些都是花活，没有黄金性价比 ，官方的立场肯定是维稳，采纳的可能性不大。

私底下可能会自己做成第三方包，其实每个人都能弄，思路上面都有了

**Comment by Airkro** [comment]
@afc163 , @yoyo837 , @zombieJ 

有空做了上述的工具：https://www.npmjs.com/package/@shaking/antd-less

只要安装上就开箱即用，前提是脚手架是基于 webpack@4，配置事先就支持 tree-shaking 和 less。

手头的项目测试发现，这种做法虽然零配置，但因为 import map 不够扁平，编译速度却比 `babel-plugin-import` 要慢一些，如果用官方导出可能会好些。

**Comment by githoniel** [comment]
@Airkro your solution is good. But webpack4 may not shake static file imported by css when css itself is shake

see the issue below,  the demo in it is using your tree shake solution. It will work well in webpack5 use asset module.

https://github.com/webpack-contrib/url-loader/issues/228

But I think this is not a  problem for antd, because there is no static file imported by component style sheet

**Comment by nzhl** [comment]
> 这样不行的，用户如果要引入 less 就会有问题。默认引入 css 文件也会默认要求用户配置 css-loader，有侵入性。真正要实现完美按需加载要等未来的 css in js 了。

大概理了下, 所以现状是
1. js部分是完美支持 tree-shaking 的, 不需要 babel-plugin-import
2.样式部分如果在每个组件的入口文件中引入其实也可以完美支持, 但是这样搞得话会强制要求接入方配置 css-loader. 

所以目前的意思是保持现状, 要追求极致还是 babel-plugin-import , 一般糙一点的直接无脑全量样式+按需组件就行了.

这个结论没问题吧?

**Comment by Airkro** [comment]
https://github.com/ant-design/ant-design-mobile v5 已经选用了组件自行引入CSS的方案（没有less版本）。

仔细想想，分离JS和CSS的场景几乎不存在，只是以前的工具不够强大，现在直接“在一起”就行了。

[ant-design v5](https://github.com/ant-design/ant-design/issues/33862) 则打算用 `css in js`。

这个问题到今天真正算是尘埃落定了。

**Comment by LJJCherry** [comment]
> > 这样不行的，用户如果要引入 less 就会有问题。默认引入 css 文件也会默认要求用户配置 css-loader，有侵入性。真正要实现完美按需加载要等未来的 css in js 了。
> 
> 大概理了下, 所以现状是
> 
> 1. js部分是完美支持 tree-shaking 的, 不需要 babel-plugin-import
> 2. 样式部分如果在每个组件的入口文件中引入其实也可以完美支持, 但是这样搞得话会强制要求接入方配置 css-loader.
> 
> 所以目前的意思是保持现状, 要追求极致还是 babel-plugin-import , 一般糙一点的直接无脑全量样式+按需组件就行了.
> 
> 这个结论没问题吧?

我看下来应该是这样。。。

**Comment by LeiYao123** [comment]
@afc163 如果加载的是 antd main 入口的 cjs 版本的包，比如可能被 babel-loader 转换，或是 nextjs 这样的只支持 cjs 版本的，这样做了之后，tree shaking 还会生效吗，还有 按需加载的效果吗

**Comment by LeiYao123** [comment]
1. js部分是完美支持 tree-shaking 的, 不需要 babel-plugin-import
2. 样式部分如果在每个组件的入口文件中引入其实也可以完美支持, 但是这样搞得话会强制要求接入方配置 css-loader.
 所以目前的意思是保持现状, 要追求极致还是 babel-plugin-import , 一般糙一点的直接无脑全量样式+按需组件就行了.

> 我看下来是这样。。。但引入babel-plugin-import 算不算是追求极致。。。官方废弃了的话感觉不算了吧？剩下的只是css的按需引入问题，看下个版本要用css in js来解决了

---
@LJJCherry 如果使用者使用了 cjs 版本的包，就不会自动 tree shaking（比如 next.js） 这时候好像还是会需要 babel-plugin-import
