### ISSUE TITLE
spinning timeout 问题

### ISSUE THREAD

**Issue by raygu0101** [ant-design/ant-design#2398]
#### 你做了什么？

表格进行当前页数据刷新，使用 loading 属性进行 loading 提示

#### 你期待的结果是：

立即出现 loading 效果，现在为延迟 250 ms，接口在这个时间内返回，就没有 loading 效果

#### 实际上的结果：

延迟 250 ms，接口已返回，给用户的体验就是点击刷新没有任何反应

#### 建议
建议可以配置 spinning timeout 参数，麻烦看一下，感谢

**Comment by RaoHai** [comment]
这个当初是为了解决 Spin 加载过快会闪动的问题 #1273 

需要用 loading 效果告诉用户该区域已经刷新了么？

**Comment by afc163** [comment]
时间很短的情况下，用户也看不清的。

**Comment by afc163** [comment]
或者改成延迟消失，只要出现过，至少显示 5/600ms 这样？

**Comment by raygu0101** [comment]
恩，需要让用户感知这个操作执行了
另外，延迟的loading，有的时候会感觉操作的不流畅感

赞成将延迟出现改成延迟消失，时间也建议可配置
感谢答复~

**Comment by RaoHai** [comment]
像这样？ #2486

**Comment by zkboys** [comment]
setTimeout 能否改成，默认500ms，提供接口，可配置？
