### ISSUE TITLE
Tabs switching causes the value of the form form to change（tabs切换使得form表单的值进行改变）

### ISSUE THREAD

**Issue by fenglijunnb** [ant-design/ant-design#23983]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
What this feature needs is to address the user experience, and then I want you to look at how do you design it（这个功能需要的是解决用户的使用体验，然后希望大家看一下如何进行设计）
Now, the one I designed will have tabs switch to the second page, and the form form doesn't have a value（现在我设计的这个会出现tabs切换第二个页面时，form表单赋不上值）

### What does the proposed API look like?
就是能简便就简便

![image](https://user-images.githubusercontent.com/48191768/81461420-38cdcc80-91de-11ea-8e01-c494ef344806.png)
![image](https://user-images.githubusercontent.com/48191768/81461425-3cf9ea00-91de-11ea-87f5-c8883a194bcf.png)

这是完整的代码

import { Line } from '@antv/g2plot';
import {Button, Card, DatePicker, Input, Form, Radio, Select, Tabs} from 'antd';
import {connect} from 'dva'
import React, { useState, useRef } from 'react';
import { PageHeaderWrapper } from '@ant-design/pro-layout';
import styles from './style.less';

const { TabPane } = Tabs;
const FormItem = Form.Item;
const { Option } = Select;
const { RangePicker } = DatePicker;
const { TextArea } = Input;
let linePlot;

@connect(({auth_user, loading}) => ({
    // auth_user,
    // loading: loading.effects['auth_user/handleListData'],
    // listData: auth_user.listData,
    // pagination: auth_user.pagination,
    // // msg: auth_user.msg,
    // // searchAdvanceStatus: auth_user.searchAdvanceStatus,
    // // searchStatus: auth_user.searchStatus,
    // // dealStatus: auth_user.dealStatus,
    // searchParams: auth_user.searchParams,
}))

export default class UpdateForm extends React.Component {

    data = [
        { year: '1991', value: 3 },
        { year: '1992', value: 4 },
        { year: '1993', value: 3.5 },
        { year: '1994', value: 5 },
        { year: '1995', value: 4.9 },
        { year: '1996', value: 6 },
        { year: '1997', value: 7 },
        { year: '1998', value: 9 },
        { year: '1999', value: 13 },
    ];

    constructor(props) {
        super(props);
        this.formRef = React.createRef();
        this.newTabIndex = 0;
        const panes = [
            { title: 'Tab 1', content: 'Content of Tab Pane 1', key: '1',  closable: false},
            { title: 'Tab 2', content: 'Content of Tab Pane 2', key: '2',  closable: false},
        ];
        this.state = {
            activeKey: panes[0].key,
            panes,
        };
    }

    componentDidMount(){
        this.formData();
        this.drawRangeMapCharts(this.data);
    }
    formData = () => {
        this.formRef.current.setFieldsValue({
            title: this.props.location.query.channelId,
            subject: 'china',
            categories: 'usa',
            publicType: '1',
            categoriesw: 'second',
            test: '2',
            categoriesw4: 'third',
        });
        console.log(this.props.location.query.channelId)
    }
    //绘制血缘关系图
    drawRangeMapCharts(data){
        linePlot = new Line(document.getElementById('container'), {
            title: {
                visible: true,
                text: '带数据点的折线图',
            },
            description: {
                visible: true,
                text: '将折线图上的每一个数据点显示出来，作为辅助阅读。',
            },
            width: 700,
            height: 463,
            forceFit: false,
            padding: 'auto',
            data,
            xField: 'year',
            yField: 'value',
            point: {
                visible: true,
            },
            label: {
                visible: true,
                type: 'point',
            },
        });
        linePlot.render();
    }
    //重置表单
    handleReSetForm = () => {
       this.formRef.current.resetFields();
    };
    onFinish = values => {
       // console.log(values);
    }
    handleDifficulty = () => {
            const data2 = [
              { year: '2016', value: '重要' },
              { year: '2017', value: '一般' },
              { year: '2018', value: '容易' },
              { year: '2019', value: '容易' },
              { year: '2020', value: '一般' },
            ];
            linePlot.destroy();
            this.drawRangeMapCharts(data2)
    }
    handleChange = () => {
        const data3 = [
          { year: '2016', value: '一星' },
          { year: '2017', value: '二星' },
          { year: '2018', value: '一星' },
          { year: '2019', value: '三星' },
          { year: '2020', value: '三星' },
        ];
        linePlot.destroy();
        this.drawRangeMapCharts(data3)
    }

    onChange = activeKey => {
        this.formRef.current.setFieldsValue({
            title: this.props.location.query.channelId,
            subject: 'china',
            categories: 'usa',
            publicType: '1',
            categoriesw: 'second',
            test: '2',
            categoriesw4: 'third',
        });
        this.setState({ activeKey });
    };

    add = () => {
        const { panes } = this.state;
        const activeKey = `newTab${this.newTabIndex++}`;
        panes.push({ title: 'New Tab', content: 'New Tab Pane', key: activeKey,  closable: false  });
        this.setState({ panes, activeKey });
    };

    onEdit = (targetKey, action) => {
        this[action](targetKey);
    };

    render(){
      const { submitting,resetting } = this.props;
      const {activeKey} = this.state;
      const formItemLayout = {
        labelCol: {
          xs: {
            span: 8,
          },
          sm: {
            span: 5,
          },
        },
        wrapperCol: {
          xs: {
            span: 24,
          },
          sm: {
            span: 12,
          },
          md: {
            span: 10,
          },
        },
      };
      const submitFormLayout = {
        wrapperCol: {
          xs: {
            span: 0,
            offset: 0,
          },
          sm: {
            span: 0,
            offset: 5,
          },
        },
      };
      console.log(this.formRef)
      //2、创建dom
        return(
            <PageHeaderWrapper>
                <div className={styles.divAll}>
                    <Tabs
                        onChange={this.onChange}
                        activeKey={this.state.activeKey}
                        type="editable-card"
                        onEdit={this.onEdit}
                        className={styles.flex}
                    >
                        {this.state.panes.map(pane => (
                            <TabPane tab={pane.title} key={pane.key} closable={pane.closable} className={styles.margin}>

                                {pane.content}
                                <Form
                                    style={{
                                        marginTop: 8,
                                    }}
                                    ref={this.formRef}
                                    name="basic"
                                    onFinish={this.onFinish}
                                    // onFinishFailed={onFinishFailed}
                                >
                                    <FormItem
                                        {...formItemLayout}
                                        label='知识点名称'
                                        name="title"
                                        rules={[
                                            {
                                                required: true,
                                                message: "请输入知识点",
                                            },
                                        ]}
                                    >
                                        <Input placeholder='给知识点起个名字'/>
                                    </FormItem>
                                </Form>
                                {/*{ activeKey == this.state.activeKey ?     :<div> </div>}*/}
                            </TabPane>
                        ))}
                    </Tabs>
                    <div id='container' className={styles.lineChart} />
                </div>
            </PageHeaderWrapper>
        );
    }
}

**Comment by fenglijunnb** [comment]
codesandbox 我没用过，我给你一个线上的GitHub仓库吧 
https://github.com/fenglijunnb/ant-pro-test.git 
目录是在那个/src/pages/basic/knowlege/components/UpdateForm

**Comment by afc163** [comment]
放在 Tabs 里实际上有三个表单，建议分成三个 form 实例来调用，你现在复用了一个会有很多问题。

**Comment by fenglijunnb** [comment]
我想问一下那个tabs是我循环出来的，form表单的实例怎么能循环出来呢

**Comment by dazyzsy** [comment]
Tab2 里的Form渲染时，数据还是空的，你需要数据更新后，重新渲染它，如果是hooks就很简单
```
useEffect(() => {
    setTabData(data)
  }, [data])
```
data 更新时，重新 setTabData，让组件渲染

**Comment by fenglijunnb** [comment]
好的，我在看看
