### ISSUE TITLE
Setting both Badge.color and Badge.style.color sets background color accidentally

### ISSUE THREAD

**Issue by panlina** [ant-design/ant-design#23991]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-badge-style-color-issue-10xd7)

### Steps to reproduce
Open the demo.

### What is expected?
The 2 `Badge`s both render a red dot and gray text.

### What is actually happening?
The `color="#f00"` one renders a red background color for the whole badge.

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16 |
| System | any |
| Browser | any |

**Comment by panlina** [comment]
@zombieJ Will anyone look at this?

**Comment by zombieJ** [comment]
Close since v3 ended the maintenance cycle.
