### ISSUE TITLE
DatePicker onOk callback无效

### ISSUE THREAD

**Issue by miaojiuchen** [ant-design/ant-design#2399]
#### 本地环境

 Node v5.3.0

- antd 版本: V1.6.4
- 操作系统及其版本：Windows 10 Build 10586
- 浏览器及其版本: Chrome 最新

#### 你做了什么？

DatePicker showTime 情况下 onOk 回调无效

#### 你期待的结果是：

文档无相关demo

#### 实际上的结果：
onOk 回调无效

#### 可重现的在线演示

http://codepen.io/infinitymiaojiuchen/pen/ZOvXRd?editors=001

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/a05b4e67477d6d965e17d3fc5394fc42f55ffceb

把逻辑改坏了。正确的逻辑如下：

需要显示时间时，点击面板上的日期，不触发 onChange，点击 ok 时触发 onChange。

直接使用 onChange 就好。

**Comment by miaojiuchen** [comment]
THX！
