### ISSUE TITLE
to support a customized the row render in table component.

### ISSUE THREAD

**Issue by glossary95** [ant-design/ant-design#24008]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
the function support that the user can add a button on a row in the table component, and float to right in a row. if the user drag the horizontal scroll bar, the button float on the right of the row still.

### What does the proposed API look like?
row render just like column render. and there are some parameters , such as record and so on.

Example UI.
![image](https://user-images.githubusercontent.com/10994884/81475117-aad4fe80-923c-11ea-9c3e-244e6df80a20.png)

**Comment by zombieJ** [comment]
Use `components` to customize row.

**Comment by glossary95** [comment]
thanks
