### ISSUE TITLE
引入 antd.css 和 antd.less 效果不一致的问题

### ISSUE THREAD

**Issue by akecn** [ant-design/ant-design#2400]
#### 本地环境

- antd 版本: 1.6.3
- 操作系统及其版本：osx 10.11.5
- 浏览器及其版本: chrome  51.0.2704.106 (64-bit)

#### 你做了什么？

不使用antd-init 等工具。

创建 `use_css.less` 和 `use_less.less`，内容分别为
```
@import '~antd/dist/antd.css';
```
和
```
@import '~antd/dist/antd.less';
```

页面分别引入这两个文件，查看效果。

#### 你期待的结果是：

样式定义应该是一致的。

#### 实际上的结果：

部分样式的顺序不同。比如 Cascader 组件中的 Input 组件样式。

如果引入 `use_css.less`，则 `.ant-cascader-input` 类的定义会覆盖 `ant-input` 类的定义。
如果引入 `use_less.less`，则 `ant-input` 类的定义会覆盖 `.ant-cascader-input` 类的定义；并且存在重复定义的情况，所有的 antd 类 都定义了好多次。

#### 可重现的在线演示

![use antd.css](https://cloud.githubusercontent.com/assets/352465/16868789/31d050c4-4aac-11e6-8645-35ad73d83642.png)

![use antd.less](https://cloud.githubusercontent.com/assets/352465/16868817/4d14cbda-4aac-11e6-8a1a-52643e85664b.png)

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/commit/a535238d68173a6ddb1912d0d18a3c288c54bf6a

**Comment by akecn** [comment]
呃。。根本的原因似乎是less 加载顺序的问题，虽然不清楚为什么css文件的结果是正确的。只是直接这么改cascader组件的问题是不是会有遗漏呀～～
