### ISSUE TITLE
error ant-table-cell-scrollbar style in table with (scroll table and rowSelection and hide the checkbox of row selection)

### ISSUE THREAD

**Issue by glossary95** [ant-design/ant-design#24007]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-p3y3w?file=/index.js)

### Steps to reproduce

1. set scroll={{ y: 240 }} in the Table
2. set rowSelection={rowSelection} in the Table
3. set the css in global 
.ant-table-selection-column {
  display: none;
}

### What is expected?
the position of the element th.ant-table-cell-scrollbar is OK.

### What is actually happening?
the position of the element th.ant-table-cell-scrollbar is error.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome |

---
<thead class="ant-table-thead">
<th class="ant-table-cell ant-table-selection-column"><div class="ant-table-selection"><label class="ant-checkbox-wrapper"><span class="ant-checkbox"><input type="checkbox" class="ant-checkbox-input" value=""><span class="ant-checkbox-inner"></span></span></label></div></th>
<th class="ant-table-cell">Name</th>
<th class="ant-table-cell">Age</th>
<th class="ant-table-cell">Address</th>
<th class="ant-table-cell ant-table-cell-scrollbar"></th> 
</thead>

Error Screen
![image](https://user-images.githubusercontent.com/10994884/81474859-b9221b00-923a-11ea-90cc-434c291236c5.png)

**Comment by zombieJ** [comment]
When you replace default antd style. You should handle this yourself.

**Comment by RixBai** [comment]
![image](https://user-images.githubusercontent.com/43899212/83356922-38d17000-a337-11ea-8be8-061229a9898e.png)
Have the same problem

**Comment by RixBai** [comment]
Did you find the solution @glossary95

**Comment by RixBai** [comment]
Fixed the issue by updating antd version. :)

**Comment by jimmyrogue** [comment]
@glossary95 hi, i have the same issue. can you tell me how to fix it?
