### ISSUE TITLE
Let table and form support dot syntax

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#24002]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

**Keywords**

`dot`,`dataIndex`,`name`,`form`,`table`

### What problem does this feature solve?
Both the `dataIndex` attribute of the table column and the` name` attribute of the form item support passing arrays, hoping to add dot syntax recognition.

### What does the proposed API look like?
```
<Form.Item label="Name" name="user.name" />
```

And

```
<Column dataIndex="level.name" />
```

**Comment by kaysonwu** [comment]
For 4.x

**Comment by zombieJ** [comment]
dot syntax can not tell what's the `xxx.yyy` means:
```tsx
{
  'xxx.yyy': value,
}

{
  xxx: {
    yyy: value,
  }
}
```

So it replaced with array in v4.
