### ISSUE TITLE
Drawer glitch in docs

### ISSUE THREAD

**Issue by NishargShah** [ant-design/ant-design#24011]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer/](https://ant.design/components/drawer/)

### Steps to reproduce

1. Go to the drawer section of the component area
2. Click on the bottom/top radio in a custom placement area and open it using the right button.
3. Now close the drawer and click on top/bottom radio, you will see, the model will go to the top and same for the bottom.

### What is expected?
model not to be shown in UI

### What is actually happening?
Glitch comes

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16 |
| System | Windows 10 |
| Browser | Chrome 81 |

**Comment by yoyo837** [comment]
Nice catch!

**Comment by NishargShah** [comment]
> Nice catch!

Thanks
