### ISSUE TITLE
Checkbox Group creates multiple error in console

### ISSUE THREAD

**Issue by NishargShah** [ant-design/ant-design#24012]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

I searched that error in internet and I found many questions related to it but no answer can solve my issue.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-5um5g)

### Steps to reproduce
Click on the rating dropdown and see errors in the console.

### What is expected?
No Error in console

### What is actually happening?
The error comes in console, why I don't know

### Errors
Warning: React does not recognize the `inlineIndent` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inlineindent` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
So on.....

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16 |
| System | Windows 10 |
| Browser | Chrome 81 |

**Comment by zombieJ** [comment]
children of `SubMenu` should be Menu.Item.
