### ISSUE TITLE
Tree及TreeNode的selectable属性

### ISSUE THREAD

**Issue by jialeicui** [ant-design/ant-design#2401]
#### 本地环境

- antd 版本:v1.6.4

由于需要此功能, 查看源码看到[rc-tree](https://github.com/react-component/tree/blob/6e53520c3d461e0903cefb3782628a9ffac06764/src/TreeNode.jsx#L262)是支持`TreeNode`级`selectable`属性的.

在`rc-tree`的[README.md](https://github.com/react-component/tree/blob/master/README.md)中只提到了`Tree`级别的`selectable`
`antd`中这两个级别的都没有提到, 是否需要补充到说明中?

**Comment by warmhug** [comment]
可以先用着。我测试没问题会补充上去，和其他issue一次性改掉。
