### ISSUE TITLE
breadcrumb 点过去的链接，一定是#开头的吗？

### ISSUE THREAD

**Issue by lleng13** [ant-design/ant-design#2402]
我的页面是没有#的，用了react-router + antd breadcrumb之后，点击breadcrumb上面的链接都是带#的，导致route无法正确跳转，有其他的配置方法么，我看了一下，不知道怎么处理

**Comment by Yhaojing** [comment]
你解决这个问题了吗

**Comment by Yhaojing** [comment]
我也遇到这个问题，想问你是怎么解决的能给我个小demo吗

**Comment by lleng13** [comment]
routes:   
  {
            path: 'some/view',
            breadcrumbName: '我的页面',
            getComponents(nextState, callback) {
                require.ensure([], function (require) {
                    callback(null, require('./containers/some/view').default)
                })
            }
     }

相应的面包屑组件，其中linkRender来重写链接：
 <Breadcrumb {...this.props} linkRender={this._linkRender.bind(this)}/>  

例如这样：
    _linkRender(href, name, paths) {
        return <Link to={href}>{name.props.children}</Link>
    }
