### ISSUE TITLE
antd ConfigProvider locale change result in Children Component rerender

### ISSUE THREAD

**Issue by ruizhang-chowbus** [ant-design/ant-design#24029]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/ruizhang-chowbus/pen/OJyZdEb?editors=0112](https://codepen.io/ruizhang-chowbus/pen/OJyZdEb?editors=0112)

### Steps to reproduce
点击切换语言按钮

### What is expected?
切换语言时，useEffect里面的代码不执行

### What is actually happening?
每次切换语言，useEffect里面的代码都会执行

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome 81.0.4044.138 |

**Comment by ruizhang-chowbus** [comment]
if i don't use ConfigProvider，but only pass locale，the child component not trigger useEffect invoke
https://codepen.io/ruizhang-chowbus/pen/OJyZdEb?editors=1111

**Comment by ruizhang-chowbus** [comment]
Sorry, the following correct link is https://codepen.io/ruizhang-chowbus/pen/XWmqvGe?editors=0111

**Comment by Mosby-zhou** [comment]
antd 4.2.0 也有这个问题, 回退到 4.1.1就没问题了

**Comment by ruizhang-chowbus** [comment]
i have tried in codepen.io, then i found it happened since 4.1.4。It's necessary to fix it。

**Comment by echoLC** [comment]
发现新的版本一直有这个问题

**Comment by 1977474741** [comment]
> 我在codepen.io上试过，发现这个问题从4.1.4开始就出现了。必须修复。

现在有解决方案吗？
