### ISSUE TITLE
add option for 'Select' component to remove selected items from dropdown -- when mode is "tags"

### ISSUE THREAD

**Issue by mxye** [ant-design/ant-design#24021]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
With "tags" mode of the Select component, currently as you select multiple items from the DropDown list of 'Select', it does not remove those items, it just marks those items as 'selected'.

For a lot of UX use cases, it is better to have those selected items no longer show up in the list.

I'm aware a similar issue (https://github.com/ant-design/ant-design/issues/8050) was opened and successfully resolved with some sample code. However, the solution code only works in "multiple" mode. The dropdown still displays selected options when the mode is "tags". 

### What does the proposed API look like?
With the "tags" mode, add a property for the option like clearSelectedItems=true which will filter the dropdown list of the already selected items.

**Comment by zombieJ** [comment]
Use `dropdownRender` to customize selection options. It's by design to keep show the `option` listed with `tags` mode. We may not adjust this logic.

**Comment by mxye** [comment]
Thanks. I haven't seen an example of using dropdownRender in action -- don't know how to. Any pointers?

**Comment by yasuoyuhao** [comment]
Can you give me an example? 👍

**Comment by mxye** [comment]
hi there, do you not have an official example of using dropdownRender somewhere? Looks like both @yasuoyuhao and I would like to know.
