### ISSUE TITLE
the search input of the select will display cursor in ie11even through showSearch is false

### ISSUE THREAD

**Issue by zhuyuedlut** [ant-design/ant-design#24034]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2f1qx)

### Steps to reproduce
- Open link
- Click the Select
- You can see

### What is expected?
- the cursor do not show

### What is actually happening?
- the cursor is display even through set the showSearch is false

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | windows |
| Browser | ie11 |

---
I find the reason is the attribute readonly is failed for IE11,  I set unselectable="on" it works, but I cannot modify the source code

**Comment by Kermit-Xuan** [comment]
fix it on rc-select. [#487](https://github.com/react-component/select/pull/487)

**Comment by afc163** [comment]
fixed in https://github.com/react-component/select/pull/487
