### ISSUE TITLE
Tree 组件自定义样式

### ISSUE THREAD

**Issue by ES1993** [ant-design/ant-design#24036]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TreeNode 功能按钮图标

### What does the proposed API look like?
<TreeNode rightView={<Icon/>} />

**Comment by ES1993** [comment]
![image](https://user-images.githubusercontent.com/28608890/81534146-1e405280-939a-11ea-82db-20ab6dad7b13.png)

**Comment by ES1993** [comment]
![image](https://user-images.githubusercontent.com/28608890/81534198-357f4000-939a-11ea-8575-532d17e2a8d6.png)

**Comment by afc163** [comment]
title 支持传入 ReactNode。

**Comment by ES1993** [comment]
![image](https://user-images.githubusercontent.com/28608890/81538314-2ea7fb80-93a1-11ea-87a3-616486296dfe.png)
title 上的 ReactNode 会一起被选中

**Comment by ES1993** [comment]
> title 支持传入 ReactNode。

title 上的 ReactNode 会一起被选中

**Comment by afc163** [comment]
有额外操作的话，是不是应该用 checkbox 去选择。

**Comment by ES1993** [comment]
> 有额外操作的话，是不是应该用 checkbox 去选择。

我自己写了一个 组件 解决了 这个问题 谢谢 你的 帮助

**Comment by pxim** [comment]
> > title 支持传入 ReactNode。
> 
> title 上的 ReactNode 会一起被选中

请问怎么解决的，我也出现同样的问题了
![image](https://user-images.githubusercontent.com/5111701/119796056-9dec8100-bf0b-11eb-824a-fe70687ac0cf.png)
