### ISSUE TITLE
Modal.confirm 的 使用promise的延迟关闭，处理异步请求后，确认按钮只能点击一次

### ISSUE THREAD

**Issue by wendy0512** [ant-design/ant-design#24037]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/querenduihuakuang-ant-design-demo-s3kdz)

### Steps to reproduce
modal.confirm提示用户是否删除？点击确认，发起异步请求，异步请求 处理正确，关闭modal，处理错误 ，不关闭modal，可以重新点击确认发起请求

### What is expected?
promise中 使用 异步请求返回处理结果，如果处理结果是true，关闭modal，处理结果是false，不关闭modal，并且modal的确认按钮可以点击，再次发起请求

### What is actually happening?
modal的按钮只能被点击一次

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows 10 OS Version 1909 (Build 18363.778) |
| Browser | Chrome :81.0.4044.138 (正式版本) （64 位） (cohort: Stable) |

---
删除提示
提示用户是否删除？点击确认，发起异步请求，异步请求 处理正确，关闭modal，处理错误 ，不关闭modal，可以重新点击确认发起请求

**Comment by manman0512** [comment]
antd版本：4.2.0

**Comment by Suckson** [comment]
💯

**Comment by afc163** [comment]
既然用了 Promise，为啥不直接 reject：https://codesandbox.io/s/querenduihuakuang-ant-design-demo-2lctl?file=/index.js
