### ISSUE TITLE
More styling component inspired by Tailwind CSS

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#24033]
Something like Space.

https://tailwindcss.com

**Comment by afc163** [comment]
简单看了下：

- https://tailwindcss.com/docs/space 和 Space 一致。
- https://tailwindcss.com/docs/divide-width 和 Divider 一致。
- https://tailwindcss.com/docs/grid-template-columns 可以作为 #8042 的参考。
- https://tailwindcss.com/docs/breakpoints 可以考虑单独把 Breakpoints 拿出来做成独立组件。

**Comment by monolithed** [comment]
I think there is no any reason to extend the current styling with another library. Why is it needed?
it would be great to support [CSS Grids](https://github.com/ant-design/ant-design/issues/8042), but Tailwind CSS...

**Comment by mzohaibqc** [comment]
I can be totally wrong and don't know the consequences but IMHO, if we can use tailwind alongside Ant Design that would be awesome, at least for utility classes like flex, margins, padding, spacing, font styles etc.

I am working on a project and I've created a lot of utility classes which are not well though of as compare to tailwindcss

e.g.

```
.add-margin(@n, @direction, @base, @i: 0) when (@i =< @n) {
  &-@{base}-@{i} {
    margin-@{direction}: @i * @base !important;
  }
  .add-margin(@n, @direction, @base, (@i + 1));
}

.m {
  &t {
    .add-margin(10, top, 2px);
    .add-margin(10, top, 5px);
  }
  &l {
    .add-margin(10, left, 2px);
    .add-margin(10, left, 5px);
  }
  &b {
    .add-margin(10, bottom, 2px);
    .add-margin(10, bottom, 5px);
  }
  &r {
    .add-margin(10, right, 2px);
    .add-margin(10, right, 5px);
  }
}
```

this is one example and there are many more.
