### ISSUE TITLE
Select 能不能做到单独修改了suffixIcon向下的箭头。

### ISSUE THREAD

**Issue by k983551019** [ant-design/ant-design#24035]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 修改了suffixIcon的图标 会吧其他放大镜  loading效果的一起遮住。

### What does the proposed API look like?
 修改了suffixIcon图标。同时还不会覆盖掉loading的效果

**Comment by imhxc** [comment]
给个在线复现链接吧。

**Comment by k983551019** [comment]
> 给个在线复现链接吧。

https://github.com/ant-design/ant-design/issues/24035#issuecomment-626505333
select 的loading的被覆盖了

**Comment by yoyo837** [comment]
这个算不算bug还不好说，因为当提供suffixIcon 有两种解释，一是无论如何就是要显示自定义的suffixIcon，一种是你想要的那种效果。你可以在试试loading为true时去掉自定义suffixIcon。

**Comment by yoyo837** [comment]
https://codesandbox.io/s/sousuoyonghu-ant-design-demo-mhih2?file=/index.js

**Comment by imhxc** [comment]
楼上大佬已经给了解决方案了，这个应该不算bug

**Comment by k983551019** [comment]
> 楼上大佬已经给了解决方案了，这个应该不算bug

我也知道。就是能单独提出来icon最好

**Comment by zombieJ** [comment]
`suffixIcon` 用户属性拥有最高权限。因为 `search` 和 `loading` 状态都可以通过 HOC 来实现定制化的 `suffixIcon` 不同状态下的图标。

**Comment by hustcer** [comment]
“能单独提出来icon最好”
