### ISSUE TITLE
在ant design4.0.0-rc.1版本升级到最新4.2.0版本到时候，日期组件内部的文字变成英文的了

### ISSUE THREAD

**Issue by insistenceZHUO** [ant-design/ant-design#24030]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/uucue)

### Steps to reproduce
升级组件库

### What is expected?
内部的文字是中文

### What is actually happening?
变成英文

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.8.6 |
| System | mac os10.15.3 |
| Browser | 版本 81.0.4044.138（正式版本） （64 位） |

---
用的是ant design pro创建的项目，

**Comment by yoyo837** [comment]
https://codesandbox.io/s/jiben-ant-design-demo-u9tro?file=/index.js

**Comment by insistenceZHUO** [comment]
> https://codesandbox.io/s/jiben-ant-design-demo-u9tro?file=/index.js
我用的是ant design pro创建的项目，没有修改这个配置的地方

**Comment by yoyo837** [comment]
项目总有个入口。
