### ISSUE TITLE
input的maxLength是默认一个占位一个字符，是否有自定义校验规则计算maxLength

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#24031]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们想要实现1个汉字当成2个英文长度计算，做成受控组件代价太大，希望通过改变maxLength计算规则去实现

### What does the proposed API look like?
我们想要实现1个汉字当成2个英文长度计算，做成受控组件代价太大，希望通过改变maxLength计算规则去实现

**Comment by yoyo837** [comment]
Input 和 TextArea?

**Comment by aw6658913** [comment]
是的

**Comment by yoyo837** [comment]
看team是否接受这个请求，如果接受这个的话可能是加一个函数参数，供使用者自行计算。

**Comment by afc163** [comment]
maxLength 目前默认用的原生 input 的属性，不会做 hack，有需求可以自行封装逻辑。
