### ISSUE TITLE
为什么我给form表单的input组件设置value无效？如何初始化给他值？

### ISSUE THREAD

**Issue by cnv587** [ant-design/ant-design#2403]
#### 本地环境

- antd 版本:1.6.4
- 操作系统及其版本：
- 浏览器及其版本:

#### 实际上的结果：
![3](https://cloud.githubusercontent.com/assets/13713580/16875948/97ea8f96-4ad4-11e6-97a5-5582a3e6b720.jpg)

**Comment by GrayChoi** [comment]
defaultValue初始化赋值

**Comment by huyansheng3** [comment]
如果不是设置 initialValue呢？ 期望这个值是可以根据用户操作变化的

**Comment by yesmeck** [comment]
@huyansheng3 使用问题可以到 segmentfault 上提问。

**Comment by skydh** [comment]
thanks,this help me a lot
