### ISSUE TITLE
4.x 版本Form.validateFields&onFinsh无法获取验证后值

### ISSUE THREAD

**Issue by seiwhale** [ant-design/ant-design#24044]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wild-silence-1kiyu)

### Steps to reproduce
- 在 `Drawer` 中放置 `Form` 表单，触发 `submit` 后 `onFinsh`未触发，无法获取到对应的表单值。若通过 `Button` 手动触发点击事件后， `validateFields` 状态一直处于 `pending` 中，无法进入 `then` 和 `catch` 回调。
- `getFieldsValue` 可正常获取。

### What is expected?
期待可以触发 `onFinsh` 事件并获取到对应的值，或者可以手动通过 `validateFields` 获取到对应的值或错误状态。

### What is actually happening?
- 在 `Drawer` 中放置 `Form` 表单，触发 `submit` 后 `onFinsh`未触发，无法获取到对应的表单值。若通过 `Button` 手动触发点击事件后， `validateFields` 状态一直处于 `pending` 中，无法进入 `then` 和 `catch` 回调。
- `getFieldsValue` 可正常获取。

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12 |
| System | Win10专业版 120.2202.130.0 |
| Browser | Chrome 81.0.4044.138 |

**Comment by zombieJ** [comment]
你的 `validator` 没有返回：
```tsx
validator(rule: Rule, value: string) {
  validateFields([["receiver", "tel"]]);
  // 需要返回一个 Promise
}
```

https://codesandbox.io/s/vigilant-joliot-hhi9g?file=/src/App.tsx
