### ISSUE TITLE
CheckboxGroup 选中数量限制

### ISSUE THREAD

**Issue by ChenQiWen** [ant-design/ant-design#2404]
#### 本地环境

- antd 版本:1.6.4
- 操作系统及其版本：win10
- 浏览器及其版本:chrome

#### 你做了什么？

CheckboxGroup 选中数量限制

#### 你期待的结果是：

CheckboxGroup 选择数量满足条件时 能把未选择的选项disabled掉

#### 实际上的结果：

给CheckboxGroup  加上disabled 所有选项都disabled掉了

**Comment by afc163** [comment]
```jsx
<CheckboxGroup>
  <Checkbox disable={xxxx} />
  <Checkbox disable={xxxx} />
  <Checkbox disable={xxxx} />
</CheckboxGroup>
```

状态分开管理即可。

**Comment by ChenQiWen** [comment]
嗯 我知道 一开始初始值可以这样给。但Checkbox 触发onChange 时 满足条件时 怎么禁用未选择的
