### ISSUE TITLE
Checkbox Field is undefined in Form.List

### ISSUE THREAD

**Issue by StefanSelfTaught** [ant-design/ant-design#24049]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-checkbox-bug-1qfkp?file=/Bug.js)

### Steps to reproduce
My code is very similar to this one in the docs: https://ant.design/components/form/#components-form-demo-dynamic-form-item.

1. Add a course field.
2. Enter a value in all fields, leave the scholarship checkbox untouched.
3. Submit the form.
4. Check the console.

### What is expected?
When the form is submitted and the Checkbox is untouched, the Checkbox value should be false. ( if the Checkbox in checked and then unchecked, the value of the Checkbox is false ) 

### What is actually happening?
When the form is submitted and the Checkbox is untouched, the Checkbox value is undefined.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | React 16.13.0 |
| System | Windows 10 Pro, version 1909 |
| Browser | Chrome 81 |

**Comment by MuggleFighter** [comment]
https://codesandbox.io/s/antd-reproduction-template-checkbox-bug-c8nnb 
try to give 'scholarship' field a initialValue

**Comment by StefanSelfTaught** [comment]
Yeah, it works. I was trying to set `initialValues` on the form, didn't see the `initialValue` prop in the docs ... . Thanks!

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-checkbox-bug-7vfo0?file=/Bug.js

`initialValue={false}`.

**Comment by devspartan** [comment]
But if we want to check the box to true. It will still give the same value false. How to cope with that thing?

**Comment by josh231101** [comment]
Same problem here, thought it was the prop from parent element, until I active and deactivate I get the value, otherwise no interaction sends undefined
