### ISSUE TITLE
Different performances between 4.0.1 and 4.0.1 above when using dependencies (dependencies在4.0.1和4.0.1以上版本表现不一致)

### ISSUE THREAD

**Issue by MuggleFighter** [ant-design/ant-design#24043]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zhucexinyonghu-ant-design-demo-jipv4)

### Steps to reproduce
Switch antd version between 4.0.1 and above respectively. Input something in 'test1' field.
把antd版本分别切换为4.0.1和4.0.1以上, 在'test1'字段输入内容

### What is expected?
'Test' component should have same performances between different versions.
'Test' 组件在不同版本应有相同的表现

### What is actually happening?
'Test' component has different performances.
'Test' 组件表现不一致

| Environment | Info |
|---|---|
| antd | 4.0.1 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.4 |
| Browser | chrome 81.0.4044.138 |

**Comment by zombieJ** [comment]
没明白，你说的表现是什么？

**Comment by MuggleFighter** [comment]
> 能说说你需要重复渲染的场景是什么吗？
> 
> 4.0.1 https://codesandbox.io/s/zhucexinyonghu-ant-design-demo-ynp6f
> 4.2.0 https://codesandbox.io/s/zhucexinyonghu-ant-design-demo-gg7vb

场景是我在封装一个业务层面通用的表单, 当C字段依赖A, B字段时,希望A,B字段任何变更都可以触发C字段更新, 比如: A字段是价格,B字段是折扣, C字段是根据A, B立即计算出来的优惠价.

**Comment by zombieJ** [comment]
用 `shouldUpdate` 来控制：https://codesandbox.io/s/zhucexinyonghu-ant-design-demo-ukdr6?file=/index.js

`dependencies` 作用于依赖更新重新触发校验，重新触发字段渲染元素是个 bug。重新渲染是 renderProps 的职责范畴哈。
