### ISSUE TITLE
DatePicker/RangePicker: Not able to select date after making a production build with Parcel Bundler

### ISSUE THREAD

**Issue by KunalBonage** [ant-design/ant-design#24045]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/KunalBonage/antd-parcel-datepicker/tree/master](https://github.com/KunalBonage/antd-parcel-datepicker/tree/master)

### Steps to reproduce
1. Make a build.
2. we can see the DatePicker but we are not able to click/ select the date.

### What is expected?
We should be able to select the date.

### What is actually happening?
We can see the DatePicker/RangePicker but not able to select the date.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows |
| Browser | Google Chrome 81.0.4044.92 (Official Build) (64-bit) |

---
I have checked FAQ, there is similar kind of issue present but in our case we are using Parcel Bundler and after making production build date picker is not working. 
Note: It is working fine when we run it locally without production build.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/22943#issuecomment-614680162

**Comment by zombieJ** [comment]
https://github.com/parcel-bundler/parcel/issues/3523
