### ISSUE TITLE
Button组件loading动画问题

### ISSUE THREAD

**Issue by Hencky** [ant-design/ant-design#24054]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/butotn-loading-347oq?file=/index.js)

### Steps to reproduce
1. 点击第一个按钮，loading动画出现消失时卡顿明显；
2. 点击第二个按钮，按钮变宽（没变宽就多点几次）；

### What is expected?
按钮loading动画流畅

### What is actually happening?
按钮loading动画不流畅

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | Mac |
| Browser | 81.0 |

**Comment by afc163** [comment]
Fixed in #23783
