### ISSUE TITLE
Unable to install version 4.2.1

### ISSUE THREAD

**Issue by gudleik** [ant-design/ant-design#24057]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gist.github.com/gudleik/22b12ef62588d5914eba345e2b44dc81](https://gist.github.com/gudleik/22b12ef62588d5914eba345e2b44dc81)

### Steps to reproduce
yarn add antd@4.2.1

### What is expected?
antd 4.2.1 is installed

### What is actually happening?
yarn throws error during post-install about missing generate-version script. 
Source:

https://github.com/ant-design/ant-design/commit/d2214589391c8fc8646c3e8ef2c6aa86fcdd02a3#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R77

| Environment | Info |
|---|---|
| antd | 4.2.1 |
| React | not relevant |
| System | macOS |
| Browser | not relevant |

**Comment by achilles-kosun** [comment]
Do we have a hotfix release for this?
