### ISSUE TITLE
table里怎么实现行的手动排序

### ISSUE THREAD

**Issue by ggsddo** [ant-design/ant-design#2405]
比如说，我点击某一行，实现上移或者是下移一行的操作。或者是拖拽。

**Comment by yesmeck** [comment]
现在的 API 应该是做不到，等 #2029 实现后就可以用 [react-dnd](https://github.com/gaearon/react-dnd)之类的库做拖动排序了。

**Comment by afc163** [comment]
根据交互修改数据的顺序，动态设置 dataSource 。
