### ISSUE TITLE
Variable @modal-heading-color does not cover the modal close button

### ISSUE THREAD

**Issue by dysticus** [ant-design/ant-design#24050]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/dysticus/antdesign-theme-issue/tree/modal-problem](https://github.com/dysticus/antdesign-theme-issue/tree/modal-problem)

### Steps to reproduce
- Clone repo and run `npm install && npm start`
- Verify the overwriting of the variable @modal-heading-color in webpack-config.js
- Click on the button Open Modal
- Check the text colour of the header of the modal
- Verify the text is white (as expected due to modifyVars), yet the close button (which is part of the header) is not.

### What is expected?
When setting the less variable @modal-heading-color to white, I would expect the entire heading color would be white and not only the text.

### What is actually happening?
Currently only the text is styled with the variable @modal-heading-color, the close button colour is a 45% fade of black, like the variables @text-color-secondary and @modal-mask-bg.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.x |
| System | Win10 |
| Browser | Chrome |

**Comment by afc163** [comment]
close button don't belong to Modal header actually.
