### ISSUE TITLE
版本升级影响react-router的Link跳转到新页面

### ISSUE THREAD

**Issue by MingleJia** [ant-design/ant-design#24066]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/情景简单，不需要链接](https://ant.design/components/table-cn/情景简单，不需要链接)

### Steps to reproduce
升级到3.26.0版本，设置ConfigProvider为zhCN中文，跳转到_blank新窗口

### What is expected?
<Link className={styles.rightItem}
                    to="/infoLoadIn?type=student"
                    target="_blank"
                >导入学生</Link> 跳转到并打开/infoLoadIn?type=student页面

### What is actually happening?
跳转到了/infoLoadIn?type=student链接，但页面空白，控制台无报错

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16.8.2 |
| System | win10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
看不太懂

**Comment by fenglijunnb** [comment]
tabs切换form表单，然后得到所有表单的数据进行提交，改如何操作呢

**Comment by yoyo837** [comment]
> tabs切换form表单，然后得到所有表单的数据进行提交，改如何操作呢

上层管理数据就可以了

**Comment by fenglijunnb** [comment]
@yoyo837 你好，这个具体有没有例子呢，我这里确实不太明白

**Comment by yoyo837** [comment]
> @yoyo837 你好，这个具体有没有例子呢，我这里确实不太明白

你先提供你的demo，不然我也不容易理解你的意思。

**Comment by fenglijunnb** [comment]
好的，我给你发一份邮件吧，要不

**Comment by yoyo837** [comment]
> 好的，我给你发一份邮件吧，要不

online demo 更好，万一我弄不好，其他人也可以帮忙看看

**Comment by fenglijunnb** [comment]
这个 online demo我不会弄，你看如果可以的话你可以把它挂起来

**Comment by yoyo837** [comment]
> 这个 online demo我不会弄，你看如果可以的话你可以把它挂起来

用过就会了 https://u.ant.design/codesandbox-repro 改这个，记得保存

**Comment by fenglijunnb** [comment]
改这个确实我感觉有点困难，要不你先看一下邮件

**Comment by yoyo837** [comment]
online demo的作用就是快速解决问题，你发我俩问题我还得想办法让他跑起来，没那么多时间，大家都有自己工作的。

**Comment by fenglijunnb** [comment]
那我先试试在线上改，如果不行的话，正好在把整个项目给你，然后直接运行就行
