### ISSUE TITLE
v4 版本 Table组件不能随着expandedRowKeys属性手动更改而变化

### ISSUE THREAD

**Issue by Cedarkun** [ant-design/ant-design#24068]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kezhankai-ant-design-demo-gmzcr)

### Steps to reproduce
https://codesandbox.io/s/kezhankai-ant-design-demo-gmzcr

### What is expected?
Table组件随着expandedRowKeys属性手动更改而变化

### What is actually happening?
Table组件不能随着expandedRowKeys属性手动更改而变化

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | windows64 |
| Browser | Google Chrome74.0.3724.8 |

**Comment by afc163** [comment]
Your codesandbox works fine.

**Comment by Cedarkun** [comment]
我希望通过点击操作栏Expand字段可以实现表格展开，但是实际上并没有如愿

**Comment by zombieJ** [comment]
不要修改 `expandedRowKeys`，每次变更都传递新的 `expandedRowKeys`:
https://codesandbox.io/s/kezhankai-ant-design-demo-vh26j?file=/index.js
