### ISSUE TITLE
Drag from one Tree and drop to another Tree fails

### ISSUE THREAD

**Issue by thomasstjerne** [ant-design/ant-design#24062]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/drag-tree-to-tree-3vw9k)

### Steps to reproduce
Drag a node from the left tree to the right (or vice versa)

### What is expected?
onDrop callback called

### What is actually happening?
TypeError
Cannot read property 'props' of undefined

| Environment | Info |
|---|---|
| antd | 4.2.1 |
| React | 16.12 |
| System | OSX |
| Browser | Chrome Version 81.0.4044.122 (Official Build) (64-bit) |

**Comment by thomasstjerne** [comment]
I think this is because of broken functionality in [rc-tree](https://github.com/react-component/tree/)  v3.x
rc-tree used to have a working example of drag / dropping between trees

**Comment by thomasstjerne** [comment]
I have submitted a pull request for this here: https://github.com/react-component/tree/pull/327

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/tree/pull/327 Thx! @thomasstjerne

**Comment by sz-Oliver** [comment]
请问你修复并提交在哪个版本了呢？最近4.2.4版本还是有这个问题呀。

**Comment by abrostamian** [comment]
its not fixed yet i can't drag drop between two tree

**Comment by dyram-ivoyant-eng** [comment]
Not able to drag and drop between 2 different trees.
