### ISSUE TITLE
MonthPicker must input some typescript properties

### ISSUE THREAD

**Issue by jeessy2** [ant-design/ant-design#24071]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Error:(40, 22) TS2739: Type '{ format: string; placeholder: string; }' is missing the following properties from type 'Readonly<Pick<Pick<PickerDateProps<Moment>, "onChange" | "picker" | "prefixCls" | "className" | "style" | "mode" | "tabIndex" | "value" | "defaultValue" | "defaultPickerValue" | ... 87 more ... | "id"> & { ...; }, "locale" | ... 98 more ... | "bordered">>': autoComplete, id

### What is expected?
不需要autoComplete,id

### What is actually happening?
必须要

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16 |
| System | all |
| Browser | chrome |

**Comment by jeessy2** [comment]
创建一个新的项目没有这个错。从4.1升级到4.2就有错，有可能和项目有关？

**Comment by yoyo837** [comment]
请提供下复现，否则不知道什么问题，无从解决。

**Comment by jeessy2** [comment]
可能和antd无关。不知道升级了啥包引起的。我先关了
