### ISSUE TITLE
Input组件onChange事件打印event对象，里面的target为null

### ISSUE THREAD

**Issue by lansebingqilin** [ant-design/ant-design#24079]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-cache-cimoq)

### Steps to reproduce
打印event

### What is expected?
在Antd官方网站Input进行提示下onChange事件的event.persist()

### What is actually happening?
打印event对象，里面的target的值为null,是react的事件机制导致的相关问题，需要使用event.persist()异步获取

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.8.6 |
| System | mac OS 10.15.3 |
| Browser | 81.0.4044.138 |

**Comment by yoyo837** [comment]
这个好像是React内部行为，除非persist，否则都是包装对象，为了性能。

**Comment by afc163** [comment]
antd 不会对 event 做特殊操作，保持和原生 input 逻辑一致，你可以在使用的时候调用 `event.persist()`。
