### ISSUE TITLE
Got wrong active tab position in Tabs when append  a new tab with title fetched from remote server 

### ISSUE THREAD

**Issue by dilidili** [ant-design/ant-design#24075]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyixinzengyeqianhongfaqi-ant-design-demo-02mvz?file=/index.js)

### Steps to reproduce
Repeatedly click the "ADD" button to add a new tab.

### What is expected?
When  "long length description" append to the tab name asynchronously, Tabs should navigate to the active tab automatically.

### What is actually happening?
Tab ink bar scroll once but ignored the latter "long length description" label change.

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | ^16.12.0 |
| System | macOS 10.13.2 |
| Browser | Chrome 80.0.3987.163 |

**Comment by zombieJ** [comment]
close since it seems work as expect in new Tab: https://codesandbox.io/s/zidingyixinzengyeqianhongfaqi-ant-design-demo-forked-x0hce?file=/index.js
