### ISSUE TITLE
InputNumer 上下增加按钮错位

### ISSUE THREAD

**Issue by nuintun** [ant-design/ant-design#24076]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/api/v1/sandboxes/define)

### Steps to reproduce
鼠标移动到 InputNumer 上

### What is expected?
上下增加按钮不错位

### What is actually happening?
上下增加按钮错位

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | React 16 |
| System | WIN10 |
| Browser | 81 |

![企业微信截图_20200512144934](https://user-images.githubusercontent.com/1730277/81649923-a63e5f00-9463-11ea-92d3-2146906b03e7.png)

**Comment by fireairforce** [comment]
CodeSanbox的链接好像挂掉了？

**Comment by afc163** [comment]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/507615/82174639-decab680-9903-11ea-8d37-7ca2443c838e.png">

mac 上无法重现。

**Comment by nuintun** [comment]
@afc163 WIN10 chrome 81

**Comment by yoyo837** [comment]
复现咋点不开

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/82225711-1ebb8900-9958-11ea-9bde-28983a1c3ba8.png)

win10 上确实有问题
