### ISSUE TITLE
当日历组件open参数手动控制时，点击空白区域无法关闭浮层

### ISSUE THREAD

**Issue by kyo4311** [ant-design/ant-design#24083]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8ltmc?file=/index.js)

### Steps to reproduce
当日历组件open参数手动控制时，点击空白区域可以关闭浮层

### What is expected?
给个一个实例，可以调用实例对象上的方法，进行关闭

### What is actually happening?
暂时不知道用什么方法关闭浮层

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-Input/Select-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86%E3%80%82

你需要学习 React 受控模式。

**Comment by kyo4311** [comment]
> https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E8%AE%BE%E7%BD%AE%E4%BA%86-Input/Select-%E7%AD%89%E7%9A%84-value-%E6%97%B6%E5%AE%83%E5%B0%B1%E6%97%A0%E6%B3%95%E4%BF%AE%E6%94%B9%E4%BA%86%E3%80%82
> 
> 你需要学习 React 受控模式。
> 
> RangePicker 有个 `onOpenChange` 属性。

浮内点击和层外点击，返回的open值都是false，所以不好区分。

**Comment by afc163** [comment]
Try https://codesandbox.io/s/antd-reproduction-template-zvyzj?file=/index.js

**Comment by kyo4311** [comment]
> Try https://codesandbox.io/s/antd-reproduction-template-zvyzj?file=/index.js

谢谢，选了两个时间的时候关闭正确了。

但是如果点开，不选时间，直接点空白区域还是关闭不了。

另外，如果footer有很多按钮，最近7天，15天之类的，选了两个时间，不想关闭，需要自己点击下面的按钮手动关闭。

**Comment by afc163** [comment]
试试：https://codesandbox.io/s/antd-reproduction-template-dck29

**Comment by kyo4311** [comment]
> 试试：https://codesandbox.io/s/antd-reproduction-template-dck29

到处乱点点，很快就不行了。

**Comment by afc163** [comment]
看看这种需求怎么满足：@zombieJ

**Comment by kyo4311** [comment]
如果日历选择，也可以不绑定Input，可以自己在想要的地方弹出来就好了

**Comment by yoyo837** [comment]
> 如果日历选择，也可以不绑定Input，可以自己在想要的地方弹出来就好了

自己稍微包装一下逻辑可以的，我自己就做了一个类似的，

![image](https://user-images.githubusercontent.com/6134547/81768790-78622480-950e-11ea-9b0d-1b2a8662320e.png)

**Comment by yoyo837** [comment]
把自带的input隐藏掉，再加`dropdownClassName` 处理一下定位

**Comment by kyo4311** [comment]
> > 如果日历选择，也可以不绑定Input，可以自己在想要的地方弹出来就好了
> 
> 自己稍微包装一下逻辑可以的，我自己就做了一个类似的，
> 
> ![image](https://user-images.githubusercontent.com/6134547/81768790-78622480-950e-11ea-9b0d-1b2a8662320e.png)

求教！可以在codesandbox写个例子吗？

**Comment by yoyo837** [comment]
```jsx
          <DatePicker
            className="hidden"
            dropdownClassName={classNames(styles.dropdown, {
              [styles.dropdownMobile]: isMobile,
            })}
            onOpenChange={this.handleCalendarOpenChange}
            onChange={this.handleCalendarChange}
            value={slide}
            open={calendarOpen}
          />
```

就这个。没别的黑魔法

**Comment by kyo4311** [comment]
> ```js-jsx
>           <DatePicker
>             className="hidden"
>             dropdownClassName={classNames(styles.dropdown, {
>               [styles.dropdownMobile]: isMobile,
>             })}
>             onOpenChange={this.handleCalendarOpenChange}
>             onChange={this.handleCalendarChange}
>             value={slide}
>             open={calendarOpen}
>           />
> ```
> 
> 就这个。没别的黑魔法

那这个点空白区域，可以关闭吗？

**Comment by yoyo837** [comment]
`  open={calendarOpen}` 自己用受控的方式。

**Comment by kyo4311** [comment]
> calendarOpen

同样的方法，我昨天就试了，怎么就是不行。
我的需求还可能更复杂一些，点时日历图标，先弹窗一个快捷时间，如7天，15天，自定义，点自定义再弹日历组件。

**Comment by yoyo837** [comment]
> > calendarOpen
> 
> 同样的方法，我昨天就试了，怎么就是不行。
> 我的需求还可能更复杂一些，点时日历图标，先弹窗一个快捷时间，如7天，15天，自定义，点自定义再弹日历组件。

问题不大吧同样的套路。

**Comment by yoyo837** [comment]
你把你的demo 发出来看看

**Comment by kyo4311** [comment]
> 你把你的demo 发出来看看

https://codesandbox.io/s/antd-reproduction-template-5b4cd

**Comment by yoyo837** [comment]
你要受控不得
```jsx
        open={open}
        onOpenChange={setOpen}
```

一对儿吗？
https://codesandbox.io/s/antd-reproduction-template-e1wd8?file=/index.js:676-726

**Comment by kyo4311** [comment]
> 你要受控不得
> 
> ```js-jsx
>         open={open}
>         onOpenChange={setOpen}
> ```
> 
> 一对儿吗？
> https://codesandbox.io/s/antd-reproduction-template-e1wd8?file=/index.js:676-726

最关键的一点，选了第二个时间不想关闭浮层。希望自己点击关闭，或是确定再关闭

**Comment by yoyo837** [comment]
都受控了，当然可以自己处理。

https://codesandbox.io/s/antd-reproduction-template-e1wd8?file=/index.js 再看看

**Comment by kyo4311** [comment]
> 都受控了，当然可以自己处理。
> 
> https://codesandbox.io/s/antd-reproduction-template-e1wd8?file=/index.js 再看看

比较接近了，只是点空白区域关不掉，这块处理也是挺麻烦的。

**Comment by yoyo837** [comment]
提供的只是思路，你看看我注释那个地方。

**Comment by yoyo837** [comment]
反正我认为是能改成你想要的样子，麻烦不麻烦是另外一回事，组件里也不会接受太复杂的逻辑。

**Comment by yoyo837** [comment]
因为每个实际使用场景和业务都不尽相同。

**Comment by kyo4311** [comment]
> 提供的只是思路，你看看我注释那个地方。

嗯！感谢，我再回去理理

**Comment by kyo4311** [comment]
已经找到解决方案：
外层用rc-trigger控制弹窗，里面放两个弹窗层。

<PopUp
        ref={(ref: any) => {
          triggerRef.current = ref;
        }}
        popupVisible={visible}
        onPopupVisibleChange={(val) => {
          setVisible(val);

          if (open) {
            setOpen(false);
          }
        }}
        popup={
          <div id="date_popup">
            {open ? (
              <DatePicker.RangePicker
                className={styles.picker}
                ref={ref}
                open={open}
                getCalendarContainer={() => document.getElementById('date_popup')}
                renderExtraFooter={() => footer}
              />
            ) : (
              <QuickTimeSelect onChange={onDateChange} />
            )}
          </div>
        }
        popupPlacement="bottomRight"
        destroyPopupOnHide
      >

**Comment by afc163** [comment]
辛苦了，我们可以考虑在 onOpenChange 第二个参数里加点东西，方便区分关闭的来源。cc @zombieJ

**Comment by kyo4311** [comment]
> onOpenChange
1. 考虑区分onBlur, 一个是input的失去焦点，一个是整个弹窗的失去焦点。
2. 考虑在 onOpenChange 第二个参数里加点东西，方便区分关闭的来源。
3. 考虑不绑定input和弹窗使用  (把原始的rc-picker暴露给使用者)。

**Comment by huahmj** [comment]
另一种方案，可以通过几个props组合来处理

**Comment by chienweiluo** [comment]
I face this situation,too when using RangePicker. Any solution for now ?

**Comment by Void1315** [comment]
是否能考虑将控制弹层打开的`setOpen`方法暴露出来，类似于`ref.focus()`方法？

**Comment by afc163** [comment]
看上去最新版本已经修复了：https://codesandbox.io/s/antd-reproduction-template-forked-cftxmj?file=/index.js

**Comment by Dragon-Rider** [comment]
@afc163 LGTM
