### ISSUE TITLE
Breadcrumb rtl show discuss

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24085]
- In LTR a default breadcrumb is this

![image](https://user-images.githubusercontent.com/29775873/81669123-4f8f5000-9478-11ea-9a11-4fccecd156e7.png)

- Now in RTL it is 

![image](https://user-images.githubusercontent.com/29775873/81669130-561dc780-9478-11ea-9ab2-06544e2b796b.png)

- if this actually right in RTL?

`An Application \ Application List \ Application Center \ Home`

- what's better in RTL ?
  - `\`
  - `/`

**Comment by yoyo837** [comment]
We should ask RTL language users @saeedrahimi

**Comment by AshoneA** [comment]
https://material-ui.com/components/breadcrumbs/
Seems material-ui use `/ `

**Comment by xrkffgg** [comment]
@israelKusayev Can you help answer it?

**Comment by israelKusayev** [comment]
I asked a few friends about this example 
![image](https://user-images.githubusercontent.com/42112796/81701531-d3463e00-9472-11ea-99d4-173092237b6d.png)
and they said the correct option is option 1 (in line 1)

**but**
I took a look in few Israelis sites, and they do it in a much safer way
![image](https://user-images.githubusercontent.com/42112796/81689326-d802f600-9462-11ea-8e4b-081c58e49cb4.png)
https://www.zap.co.il/models.aspx?sog=e-cellwatch


![image](https://user-images.githubusercontent.com/42112796/81689381-e6511200-9462-11ea-8950-9f50de02cb8f.png)
https://www.rest.co.il/recommended-restaurants/hasharon-area/

![image](https://user-images.githubusercontent.com/42112796/81702215-a7778800-9473-11ea-8aff-f2dc1bbf5eb4.png)

https://www.ynet.co.il/articles/0,7340,L-5729533,00.html

**Comment by saeedrahimi** [comment]
In Persian language that is RTL, most of breadcrumbs uses `/`
![screenshot-ant design-2020 05 12-18_48_48](https://user-images.githubusercontent.com/12451743/81703101-65554300-9481-11ea-9de7-47c81d6e22eb.png)

**Comment by yoyo837** [comment]
So, the standard usage is `/`? Or that the standard usage is `\`, but peoples are already accustomed to `/`?

**Comment by israelKusayev** [comment]
The standard is /

**Comment by xrkffgg** [comment]
thx all
