### ISSUE TITLE
use Grid props like flex inside one of xxl,xl,...

### ISSUE THREAD

**Issue by JavaScripti** [ant-design/ant-design#24080]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-j7jj5)

### Steps to reproduce
-

### What is expected?
in docs:
```
xxl	≥1600px, could be a span value or an object containing above props
```

so this should be work:
```javascript
<Row justify="center">
  <Col xxl={{ flex: "1140px" }} lg={{ flex: "992px" }}>
    Header
  </Col>
</Row>
```

but it's not working!

### What is actually happening?
nothing!

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by JavaScripti** [comment]
is this a bug?

**Comment by yoyo837** [comment]
```ts
export interface ColSize {
  span?: ColSpanType;
  order?: ColSpanType;
  offset?: ColSpanType;
  push?: ColSpanType;
  pull?: ColSpanType;
}
```

Does not support the `flex` prop.

**Comment by JavaScripti** [comment]
@yoyo837 Oops, that's so bad. thank you

**Comment by lilbumblebear** [comment]
I see that this looks like it "should" have been implemented already, but I am unable to get flex to work as a property inside of a size prop. 

https://codepen.io/lilbumblebear/pen/xxdqzZJ
