### ISSUE TITLE
form   initialValue问题

### ISSUE THREAD

**Issue by ChenQiWen** [ant-design/ant-design#2408]
#### 本地环境

- antd 版本:1.6.4
- 操作系统及其版本：win10
- 浏览器及其版本: chrome

#### 你做了什么？

给input加了getFieldProps  initialValue属性，rules验证就是失效

#### 你期待的结果是：

可以正常验证里面的值

#### 实际上的结果：

只要有initialValue 这个属性  表单都可以正常提交 验证失效了

#### 可重现的在线演示

http://codepen.io/anon/pen/GqQKRk?editors=001

**Comment by afc163** [comment]
1. 你给的重现例子直接报错，都不能运行起来，你自己没有试过？
2. 我修正你给的例子，发现你说的情况不存在？

报告问题时，请确保问题是可重现的，这是起码的负责任态度吧。

**Comment by ChenQiWen** [comment]
哦哦 我看了一下 是我语法写错了 不好意思 以后我会注意的
