### ISSUE TITLE
button组件内用tooltip组件，导致tooltip失效

### ISSUE THREAD

**Issue by jihanting** [ant-design/ant-design#24090]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-gwcds?file=/index.js:0-542)

### Steps to reproduce
hover到按钮图标上，不会显示提示文案

### What is expected?
显示提示文案

### What is actually happening?
不会显示提示文案

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.12.0 |
| System | macOS 10.13.6 |
| Browser | chrome |

**Comment by afc163** [comment]
https://stackoverflow.com/a/14690527/3040605

HTML 规范内，button 内的元素没有办法做独立的交互。

**Comment by jihanting** [comment]
> https://stackoverflow.com/a/14690527/3040605
> 
> HTML 规范里 button 内的元素没有办法做独立的交互。

你指的规范文档在哪里？有链接吗？

**Comment by jihanting** [comment]
> https://stackoverflow.com/a/14690527/3040605
> 
> HTML 规范里 button 内的元素没有办法做独立的交互。

![image](https://user-images.githubusercontent.com/16217129/81695330-0bf70f00-9495-11ea-9605-82a536e8a91b.png)
 
我看了一下好像你们把btn样式里面的pointer-events设置为none了，这个就是基于你所说的html规范来设置的吗

**Comment by afc163** [comment]
看了下是 https://github.com/ant-design/ant-design/issues/7034

**Comment by afc163** [comment]
过了两年再看，感觉没什么道理，我发个 PR 改掉。
