### ISSUE TITLE
BackTop has a div with empty class

### ISSUE THREAD

**Issue by varundey** [ant-design/ant-design#24098]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-testing-library-demo-8rg7s)

### Steps to reproduce
From the given codesandbox, inspect element on `Back to Top` button and notice div with class `ant-back-top`

### What is expected?
the first child div of `<div class="ant-back-top">` should have a valid class name like so:
```
<div class="ant-back-top">
  <div class="some-class">
    ....
  </div>
</div>
```

### What is actually happening?
The first child has an empty class name
```
<div class="ant-back-top">
  <div class="">
    ....
  </div>
</div>
```
 

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | MacOS 10.15.4 |
| Browser | Chrome 81/Firefox 76 |

---
This hampers the testing of the component as the react-testing-library is not able to find this node. This can be verified in the test tab of the above codesandbox as well. However if I try to render a similar div node with empty class, I am able to render and test it in react-testing-library

**Comment by afc163** [comment]
I don't think we should change dom structure just for a test library unless it have actually user experience problem.
