### ISSUE TITLE
subMenu disappear flicker  （version >= 4.1.2）

### ISSUE THREAD

**Issue by cszo** [ant-design/ant-design#24103]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/cszo/pen/yLYEQxZ](https://codepen.io/cszo/pen/yLYEQxZ)

### Steps to reproduce
当我将菜单项悬停在一个菜单项  并快速切换悬停至同一级别的另一个菜单项时，上一个子菜单消失闪烁        
when i hover the menu-item and quickly hover another menu-item at the same level, the previous subMenu  disappear flicker

### What is expected?
不闪烁 跟4.1.1及之前版本一样

### What is actually happening?
当我将菜单项悬停在一个菜单项  并快速切换悬停至同一级别的另一个菜单项时，上一个子菜单消失闪烁     
when i hover the menu-item and quickly hover another menu-item at the same level, the previous subMenu  disappear flicker

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1  |
| System | macOS |
| Browser | chrome 81.0.4044.138（正式版本） （64 位） |

---
antd4.1.1正常：[https://codepen.io/cszo/pen/ZEbjpaG](https://codepen.io/cszo/pen/ZEbjpaG)
antd4.1.2异常：[https://codepen.io/cszo/pen/yLYEQxZ](https://codepen.io/cszo/pen/yLYEQxZ)

**Comment by shaodahong** [comment]
Resolved by https://github.com/ant-design/ant-design/pull/23664, Upgrade version >= 4.2.0

**Comment by cszo** [comment]
> Resolved by #23664, Upgrade version >= 4.2.0

4.2.0依然有这个问题啊。。。当鼠标在menu-item上面上下快速移动 子菜单的渲染还会有重叠的感觉。。[https://codepen.io/cszo/pen/yLYEQxZ](https://codepen.io/cszo/pen/yLYEQxZ)

**Comment by mjfwebb** [comment]
Probably could be improved by using z-index. I.e the submenu which is closing would have a lower index than the one which is opening.

**Comment by afc163** [comment]
Resolved by #23664, try 4.2.2
