### ISSUE TITLE
如何在使用form.create时可以导出泛型组件

### ISSUE THREAD

**Issue by HoorayHY** [ant-design/ant-design#24104]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-monad-opqn1?file=/src/App.tsx)

### Steps to reproduce
1、export default Form.create<propType<T,A>>()(component)，无法导出泛型类型组件，且T,A值不能传入
2、export default <T,A>() => Form.create<propType<T,A>>()(component)，可以导出泛型类型组件，但是页面渲染时报错“无效子组件”，且component组件内容未渲染出来

### What is expected?
使用form.create可以正确导出泛型组件

### What is actually happening?
使用form.create后导出泛型组件报错

| Environment | Info |
|---|---|
| antd | 3.23.6 |
| React | 16.8.6 |
| System | mac |
| Browser | 谷歌 |

**Comment by afc163** [comment]
https://3x.ant.design/components/form-cn/#%E5%9C%A8-TypeScript-%E4%B8%AD%E4%BD%BF%E7%94%A8

**Comment by zombieJ** [comment]
只有 function 支持泛型，强转可以：
```tsx
function MyForm<T>(...) {
  return Form.create(...) as ...;
}
```

本身和 antd 无关，issue 关了。

**Comment by JSjump** [comment]
@HoorayHY 兄弟怎么解决的
