### ISSUE TITLE
upload组件disabled状态样式问题

### ISSUE THREAD

**Issue by jihanting** [ant-design/ant-design#24100]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-dtb35?file=/index.js)

### Steps to reproduce
1.点击clickable upload,能够正常上传文件没有问题；
2.点击disabled upload,样式上与clickable upload没有差别，用户区分不出这个按钮是处于不可点击的状态；

### What is expected?
设置了disabled的上传按钮样式应该显示不可点击状态

### What is actually happening?
设置了disabled的上传按钮样式显示了可点击状态

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.12.0 |
| System | macOS 10.13.6 |
| Browser | chrome  81.0.4044.138 |

**Comment by yoyo837** [comment]
按钮 也是自行控制 https://codesandbox.io/s/antd-reproduction-template-bfg8d
