### ISSUE TITLE
使用script标签全局引入antd报错

### ISSUE THREAD

**Issue by fred8617** [ant-design/ant-design#24116]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://kk4e3.csb.app/](https://kk4e3.csb.app/)

### Steps to reproduce
查看控制台即可

### What is expected?
正常写入window对象

### What is actually happening?
未写入window对象

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.8  |
| System | win |
| Browser | chrome |

**Comment by yoyo837** [comment]
把codesandbox的链接发出来，不然看不见代码

**Comment by yoyo837** [comment]
全局引用不是这么用的 `import s from 'https://unpkg.com/antd'`

**Comment by fred8617** [comment]
@yoyo837 没代码，script标签引的
![image](https://user-images.githubusercontent.com/35049517/81788787-a870ee00-9535-11ea-93de-f9928dc57bff.png)

**Comment by fred8617** [comment]
![image](https://user-images.githubusercontent.com/35049517/81788865-c1799f00-9535-11ea-8c02-b8602d3af7af.png)

**Comment by afc163** [comment]
> 把codesandbox的链接发出来，不然看不见代码

**Comment by fred8617** [comment]
[https://codesandbox.io/s/antd-reproduction-template-inrm9?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-inrm9?file=/index.js)
沙盒看不见报错，点开预览一下，f12就能看见控制台了

**Comment by afc163** [comment]
https://ant.design/docs/react/introduce-cn#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5

<img width="623" alt="image" src="https://user-images.githubusercontent.com/507615/81790068-6ba5f680-9537-11ea-89f2-b86c4a6a1fdf.png">

**Comment by fred8617** [comment]
@afc163 失误，忘记引依赖了，引入依赖还是报错，这个问题只存在于min.js中，antd.js没这个问题
[https://codesandbox.io/s/antd-reproduction-template-inrm9?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-inrm9?file=/index.js)

**Comment by afc163** [comment]
```
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/moment/min/moment.min.js" id="external-js"></script>
  <script src="https://unpkg.com/react/umd/react.production.min.js" id="external-js"></script>
  <script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js" id="external-js"></script>
  <script src="https://unpkg.com/moment/min/moment.min.js" id="external-js"></script>
  <script src="https://unpkg.com/antd@4.2.2/dist/antd.min.js" id="external-js"></script>
</head>
<body>
  <script>console.log(antd);</script>
</body>
</html>
```

确实有问题，4.2.0 没有问题，我排查一下。

**Comment by afc163** [comment]
没有找到原因，干脆整体重构了 rc-progress，本地测试已修复。

https://github.com/ant-design/ant-design/pull/24127

**Comment by hellorayza** [comment]
@afc163 
hi，官网FAQ：[antd 会像 React 那样提供单文件引入吗？](https://ant.design/docs/react/faq-cn#antd-%E4%BC%9A%E5%83%8F-React-%E9%82%A3%E6%A0%B7%E6%8F%90%E4%BE%9B%E5%8D%95%E6%96%87%E4%BB%B6%E5%BC%95%E5%85%A5%E5%90%97%EF%BC%9F) 下面的链接已经失效，麻烦更新，谢谢^_^。
