### ISSUE TITLE
在componentDidMount中使用ReactDOM.render渲染一个antd组件,校验失效问题

### ISSUE THREAD

**Issue by hitime888** [ant-design/ant-design#24115]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-chaum-w11co)

### Steps to reproduce
点击"提交"按钮

### What is expected?
点击"提交"按钮, 第一个Input组件和后面几个Input组件都可以校验

### What is actually happening?
不能校验

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.3 |
| Browser | chrome 80.0.3987.149 |

---
1. 我现在的需求就是将富文本中的下划线变为Input框
2. 使用antd 3.x Form的getFieldDecorator没有问题, 能够得到校验.

**Comment by afc163** [comment]
不要在 componentDidMount 里调用 ReactDOM.render ，破坏了 React 自有的生命周期。

**Comment by hitime888** [comment]
> 不要在 componentDidMount 里调用 ReactDOM.render ，破坏了 React 自有的生命周期。

但是我不这样做, 实现不了我这个需求呀. 在antd 3.x的时候, 用getFieldDecorator是可以的

**Comment by hitime888** [comment]
> 不要在 componentDidMount 里调用 ReactDOM.render ，破坏了 React 自有的生命周期。

不在componentDidMount中渲染Input的话, 我不知道我要把Input渲染到那个位置, 以及要渲染几个Input. 在render中我只知道富文本长啥样.

**Comment by yoyo837** [comment]
你另外render的 不要和 本身已经被现有React 组件生命周期所管理，即他们不冲突， 应该可以用，但是你得自行手动维护管理你render的root（被现有React 组件生命周期所管理）

**Comment by zombieJ** [comment]
感觉你的场景可以通过 `$(YourRickText)` 获取 jquery 转译过的 html 结构，然后在翻成 React 组件。

**Comment by hitime888** [comment]
> 感觉你的场景可以通过 `$(YourRickText)` 获取 jquery 转译过的 html 结构，然后在翻成 React 组件。

没太听懂呢. 获取 jquery 转译过的 html 结构, 然后在翻成 React 组件, 怎么渲染到 ${YourRichText}这个位置呢

> 

>

**Comment by hitime888** [comment]
> render的 不要和 本身已经被现有React 组件

没太懂呀.
