### ISSUE TITLE
Table-pagination-showTotal 进行本地筛选后，total的数值是后端返回的总数

### ISSUE THREAD

**Issue by macc6579** [ant-design/ant-design#24119]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyishaixuancaidan-ant-design-demo-9iw50)

### Steps to reproduce
1. 对任意一列数据进行筛选
2. 点击确认

### What is expected?
页脚的统计数据与筛选前后的数据一致。
希望与showSizeChanger的表现相同

### What is actually happening?
total的数值是后端返回的总数

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.10.2 |
| System | macOS Catalina 10.15.2 |
| Browser | 版本 81.0.4044.138（正式版本） （64 位） |

---
或者是我使用的姿势不正确？
因为目前showTotal的值是通过state传入的，
传入的state确实未发生改变，需要自己进行手动更新？
如何获取当前展示的  列表数据的实际长度呢？

因为SizeChanger的数据  会随着表格数据的变化  进行更新，
猜测会有某个参数可提供计算？

**Comment by imhxc** [comment]
这个不是bug，是你使用方式有误。
`pagination={{ showTotal: () => `共${data.length}条` }}` 这里的 data.lengt 始终取的是你最开始定义的 data.

**Comment by macc6579** [comment]
> 这个不是bug，是你使用方式有误。
> `pagination={{ showTotal: () => `共${data.length}条` }}` 这里的 data.lengt 始终取的是你最开始定义的 data.

想请教下，如何 可以拿到  与当前table数据  一致的参数呢www感激不尽

**Comment by afc163** [comment]
Duplicate of #24022

**Comment by imhxc** [comment]
https://codesandbox.io/s/zidingyishaixuancaidan-ant-design-demo-pagination-k4m4f?file=/index.js

看这个例子，`showTotal` 这个属性会有两个参数，第一个即为当前列表的数量。

除此之外，你也可以将数据长度设置为 state，然后 配合 Table 的 `onChange` ，在 `onChange` 回调中去修改 state 即可。

**Comment by macc6579** [comment]
> https://codesandbox.io/s/zidingyishaixuancaidan-ant-design-demo-pagination-k4m4f?file=/index.js
> 
> 看这个例子，`showTotal` 这个属性会有两个参数，第一个即为当前列表的数量。
> 
> 除此之外，你也可以将数据长度设置为 state，然后 配合 Table 的 `onChange` ，在 `onChange` 回调中去修改 state 即可。

多谢~
