### ISSUE TITLE
Option to hide ExpandIcon column

### ISSUE THREAD

**Issue by EBruchet** [ant-design/ant-design#24129]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using `expandRowByClick`, the ExpandIcon can be considered redundant, and hiding it allows the user to gain a bit of extra horizontal space if needed.

Using `expandIconColumnIndex: x` where x < 0 doesn't seem to hide the column completely.

### What does the proposed API look like?
```
    <Table
         columns={columns}
         expandable={{
            ...expandablePropsHere
            expandIcon: () => null,
            expandRowByClick: true,
          }}
    />
```

**Comment by taizhengfs** [comment]
真是有意思，这个问题搞了三四年了一个icon还是隐藏不掉 - -

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-z4z4o

**Comment by h1nson** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-z4z4o

this worked for me.
