### ISSUE TITLE
关于#2030 issue的疑问

### ISSUE THREAD

**Issue by noonnightstorm** [ant-design/ant-design#2412]
### 环境：
"antd": "~1.6.5",
"react": "~15.1.0"

npm: 3.x

### 问题：
我项目里面为了使用一个稳定的react版本，所以只接受15.1.x的bugfix版本。但是antd里面的依赖包有"react-addons-pure-render-mixin": "^15.0.0"。当react有更新的时候，我们的同事的机器安装环境或者线上打包的时候就会打出2个react版本，会抛错：

Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's render method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

#2030

请问有什么好的方法解决？

**Comment by afc163** [comment]
npm3 安装 react-addons-pure-render-mixin 应该是不会安装 react 的。

确认你同事的机器安装环境是 npm3？或者给个能重现的 repository 看看。

**Comment by noonnightstorm** [comment]
@afc163 我项目里面的package里面是："react": "~15.1.0"，版本肯定是15.1.x；而react-addons-pure-render-mixin的依赖包里面是："react": "^15.2.1"，版本肯定高于15.1.x。这两个不是同一个依赖包，npm3按道理来说也应该会安装2个的。

![test](https://cloud.githubusercontent.com/assets/1336049/16942598/7f426872-4dc9-11e6-889c-8d22b2c67de2.jpg)

**Comment by afc163** [comment]
react-addons-pure-render-mixin 里是 peerDependencies ，npm@3 不会安装 peerDependencies 。

**Comment by RaoHai** [comment]
tnpm 是 2.x 吧……升级一下？。。。

**Comment by noonnightstorm** [comment]
@RaoHai @afc163 果然。好吧，果然是tnpm的问题。sorry，问了一个低级问题。哈哈
