### ISSUE TITLE
3.9之前的Icon组件和3.9版本之后的Icon组件 怎样共存

### ISSUE THREAD

**Issue by betterHX** [ant-design/ant-design#24120]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们做了一个插件  依赖于3.16版本的antd， 但是我们业务系统有3.9版本之前的antd，在加载了插件之后 3.9版本的Icon组件的部分样式及伪类会呗覆盖，导致了业务系统中的Icon 不生效；

### What does the proposed API look like?
这个有什么解决方案吗？

**Comment by afc163** [comment]
建议不同版本不要混用，目前没有好的办法。
