### ISSUE TITLE
Tree组件中TreeNode里title属性设置为ReactNode的时候ReactNode点击事件频繁失效

### ISSUE THREAD

**Issue by MI-Class** [ant-design/ant-design#24123]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mi-class/pen/bGVjrrO?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Ftree-cn%2F](https://codepen.io/mi-class/pen/bGVjrrO?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Ftree-cn%2F)

### Steps to reproduce
不停的选中取消同一个Checkbox
Keep checking and unchecking the same Checkbox

### What is expected?
希望如果从TreeNode里title属性里传入ReactNode的时候里面的点击事件还可以用
Hopefully, the click event inside the TreeNode will still be available if you pass in the ReactNode from the title property inside the TreeNode

### What is actually happening?
如果TreeNode里title属性里传入的ReactNode中有点击时间的话大部分会被Tree中的onSelect属性拦截到而ReactNode中的点击时间无法触发
If there is a click time in the ReactNode passed in from the title property in TreeNode, most of it will be intercepted by the onSelect property in Tree and the click time in ReactNode will not be triggered

| Environment | Info |
|---|---|
| antd | 4.0.0|
| React | 16.8.6 |
| System | win10 |
| Browser | firefox76.0.1 |

---
树形结构里面title部分需要Checkbox,做一个权限管理方面的功能,给菜单赋予权限,每个菜单都具有不同的功能可供选择,而菜单又是树形的结构
The title part of the tree structure needs a Checkbox, which is a function of permission management, and gives permissions to the menus. Each menu has different functions to choose from, and the menus are tree structure

**Comment by afc163** [comment]
https://codepen.io/afc163-1472555193/pen/XWmBeMe?editors=0011

**Comment by MI-Class** [comment]
我那个例子可能没表达清楚,Tree里打开checkable属性的,参考这个例子https://codepen.io/mi-class/pen/eYpjoaZ?editors=0011&__cf_chl_jschl_tk__=b55d8a06babd98c7da215c936e49c7ca46accfb6-1589417025-0-AW2x5KkYIfoWiN9TSy7he7xjUWUbsoWbEF0usiEHwajt6IaWdvERmwq-2tYPv8EJAvkMhrplhEcYVETwPdqB5zCpXxqTwiI_uQbQiGiyI9TEzdrcPswb8bOZ5NtlwgolSpZaMMjzkWXf6iTPB_TXDXZ1q5TORcw3oEjLNBq1qkR_QX6XeDKGKVpMfsdnFsCrbXGORKPh2y7n1ov4qpbloy34hLplLXKvv2PjhU9GTt368IwrhGuhc7P7IoyYxluCDdzO7_97_4dC9qH6XwzeQuntUIoBT9vWC8vxwxU9wzo11-qCzMaigoQnliZlsjQfy3Hmjta11qtOv4I1Io7PQbE7WVK1cfX2_lBEFUGEZloXgmg4dPMeDL8zQgvUEw-vdrmugygd-WQAVSK-ROnyAIk

**Comment by afc163** [comment]
注意看：

```
selectable={false}
```

**Comment by MI-Class** [comment]
> 注意看：
> 
> ```
> selectable={false}
> ```

非常感谢.
加上这个之后点击title传入的组件会影响到tree组件的选中状态,不过我已经知道怎么处理了,再title传入的组件中阻止事件冒泡就可以了[#24140](https://github.com/ant-design/ant-design/issues/24140),非常感谢

**Comment by afc163** [comment]
title 上如果有 checkbox 里交互上不应该重复的，节点选择操作最好交给 checkable 来做。
