### ISSUE TITLE
table支持表头浮动、横向滚动条浮动

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design#24131]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
![image](https://user-images.githubusercontent.com/7939085/81813878-96ee0d00-955a-11ea-8e81-0ccf58374fe7.png)

![image](https://user-images.githubusercontent.com/7939085/81814041-d0267d00-955a-11ea-9d26-694a0372f199.png)

效果如这两个图所示

当表格内容比较多的时候、或者列比较多的时候，往下滚动的时候 如果表头可以像excel固定在顶部会大大增加体验
https://rsuitejs.com/components/table#%E8%99%9A%E6%8B%9F%E5%8C%96%E7%9A%84%E5%A4%A7%E8%A1%A8%E6%A0%BC

同样，当表格内容比较多，列也比较多的时候 如果每次还需要滚动到底部才能拖动横向滚动条，体验非常查
https://rsuitejs.com/components/table#%E5%9B%BA%E5%AE%9A%E6%A8%AA%E5%90%91%E6%BB%9A%E5%8A%A8%E6%9D%A1%E5%9C%A8%E9%A1%B5%E5%B0%BE

发现这这两个地址的实现效果就比较不错，强烈建议支持一下

### What does the proposed API look like?
table上配置属性
affixHeader=true 往下滚动的时候 表头像excel冻结行一样的效果
affixHorizontalScrollbar=true  当表格行数比较多的时候，虚拟的横向滚动条会浮动在最下方

**Comment by yoyo837** [comment]
scroll.y？

**Comment by xiexingen** [comment]
> scroll.y？ https://ant.design/components/table-cn/#components-table-demo-fixed-header
仔细看看案例中的那个，那个体验真比scroll.y好多了

**Comment by yoyo837** [comment]
可能我没理解你的意思。

**Comment by imhxc** [comment]
的确，在实际业务中会出现该场景需求，可以考虑添加该功能。

**Comment by yoyo837** [comment]
> 的确，在实际业务中会出现该场景需求，可以考虑添加该功能。

能说明一下你理解到的意思吗？

**Comment by imhxc** [comment]
> > 的确，在实际业务中会出现该场景需求，可以考虑添加该功能。
> 
> 能说明一下你理解到的意思吗？

可以理解为 Table 高度大于窗口的时候，表头和横向滚动条可以分别固定在窗口顶部和底部；

当前 Ant Design Table 组件的固定表头无法固定到窗口上，只能固定到 Table 自身。

**Comment by yoyo837** [comment]
#21584 这个能达到效果吧？

**Comment by imhxc** [comment]
> #21584 这个能达到效果吧？

好像不可以，这个 PR 目的是为了让表格的滚动区域撑满页面（也可能是我理解有误）。

这个 issue 的意思可以理解就是一个简单的吸顶效果；
就是在页面滚动的过程中，当 Table 的表头触碰到了窗口底部，就自定吸附到浏览器顶部。

**Comment by yoyo837** [comment]
并不滚动区域撑满页面，是撑满除了表头尾/分页组件的区域，不就刚好你说的那种效果么？

**Comment by imhxc** [comment]
> 并不滚动区域撑满页面，是撑满除了表头尾/分页组件的区域，不就刚好你说的那种效果么？

不需要撑满呀，即使我 Table 总高度为 100px，当页面滚动过程中，如果表头碰到了窗口顶部，就立即吸附到顶部。

或者你发个 #21584  的 Demo 看下？

**Comment by afc163** [comment]
这个特性很有用，@imhxc 有没有兴趣来个 PR。

**Comment by imhxc** [comment]
> 这个特性很有用，@imhxc 有没有兴趣来个 PR。

我之前有看过，Antd Design 和 React Suite 他俩的 Table 实现方式不一样；Ant Design 是用的原生 table（好像也可以用自定义标签渲染，不过没尝试过），React Suite 是用 div 模拟的 table。

所以实现起来可能会比较蛮烦，可以抽时间先研究下 。

**Comment by yoyo837** [comment]
@imhxc 那就不是同一种需求。

**Comment by yoyo837** [comment]
@imhxc 如果表格很高，表头触顶了吸附上去，此时底部怎么办？

**Comment by imhxc** [comment]
> @imhxc 如果表格很高，表头触顶了吸附上去，此时底部怎么办？如何满足题主的需求？

没太明白。
表格很高应该不影响底部固定呀；反正不管啥情况，只要表头触顶就固定到顶部，横向滚动下触地就固定到底部。

**Comment by yoyo837** [comment]
就是触顶固定顶部，触底固定底部？

**Comment by imhxc** [comment]
> 就是触顶固定顶部，触底固定底部？

对

**Comment by clanaid** [comment]
触顶固定顶部那跟吸顶功能有什么区别？

**Comment by xiexingen** [comment]
吸顶应该是指一直在顶部，触顶固定顶部应该是指当往下滚动的时候那个在浏览器视窗y轴的0即以上的时候

**Comment by WangJM001** [comment]
+1，底部除了滚动条我觉得分页器也需要吸底

**Comment by afc163** [comment]
supported in https://github.com/ant-design/ant-design/pull/25939

**Comment by darkfiredarkhalo** [comment]
`sticky`只是表头吸顶, 横向滚动条和分页器并不会浮动在可见区域底部, 已经是很费劲的操作

**Comment by vaynevayne** [comment]
这也没支持啊 怎么就关闭了
