### ISSUE TITLE
table的虚拟window 能不能支持react-window-infinite-loader，实现大数据延迟加载

### ISSUE THREAD

**Issue by aiyuchen** [ant-design/ant-design#24133]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一般需要用到大的数据，比如几千几万条的时候，不会一次加载下来，需要延迟分配下载，能否将`table`组件的`components`支持`react-window-infinite-loader`，实现延迟加载虚拟window

> 我传入`react-window-infinite-loader`组件，目前好像不支持
> https://codesandbox.io/s/xuniliebiao-ant-design-demo-k1fsm?file=/index.js:154-170

### What does the proposed API look like?
```
<Table
    {...props}
    components={{
        body: (
            <InfiniteLoader>
                <VariableSizeGrid>....</VariableSizeGrid>
            </InfiniteLoader>
        )
    }}
/>
````

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-virtual-list

**Comment by aiyuchen** [comment]
@afc163 我说的是不支持虚拟dom延迟加载，不是不支持虚拟dom，你发的文档我肯定是看过的，才能再次基础之上提供一个演示文档的，提这个问题前也是自己反复测试好几个小时的，感觉管理员瞄一眼还没看内容就随便关了问题，要这样以后都不敢提建议

**Comment by yoyo837** [comment]
交互相关了！这种交互好像移动端用对方比较多，后台仍然使用分页接口！

**Comment by afc163** [comment]
已经有相关 issue 了，可以在 #22928 里讨论，当然欢迎贡献代码。

**Comment by aiyuchen** [comment]
@afc163 技术不高。。。我想了一下，逾期纠结怎么让table组件支持按需加载，干脆去掉table组件就好了。。。。
我把table组件剥离后自己写了一个虚拟dom，这样就可以实现延迟加载数据了
https://codesandbox.io/s/magical-borg-vzqn4?fontsize=14&hidenavigation=1&theme=dark

因为考虑到加载的数据要本地用JS做比较处理的，没有用分页，而是滚动后持续加载的方式

**Comment by WangYang-Rex** [comment]
table的虚拟window 能否支持固定列的功能，期望某几列可以固定在左侧

**Comment by zzwar2009** [comment]
这种需求还是有场景的，比如大数据部门，做一个报表报表，数据可能是实时查的，一般数据都是成千上万条的，这种情况是不知道有多少页的，这种就即需要虚拟滚动解决页面卡的问题，也需要延迟加载服务端数据，希望后期有规划支持吧

**Comment by MrHuang123** [comment]
有好的实现方案吗
