### ISSUE TITLE
Table的Column的title无法自定义

### ISSUE THREAD

**Issue by chj-damon** [ant-design/ant-design#24132]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
定义Table的Columns，把Column的title属性写成函数式写法

### What is expected?
可以在函数式写法里面拿到title的原始值，这样才能实现自定义的效果。比如原来title是个字符串，现在想要把它包在一个div里面。
设想的api应该是：
`title: props => <div>{props.title}</div>`
现在的props是一个对象，包含：`sortColumn`/`sortColumns`/`sortOrder`这三个属性，但是我不知道这三个属性对我自定义title有什么用。

### What is actually happening?
函数式写法里面拿不到title的原始值

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13 |
| System | MacOS Majave |
| Browser | Chrome 81.0.4044.113 |

**Comment by afc163** [comment]
这个 title 本来就是你定义的，哪里有什么原始值可以传，鸡生蛋蛋生鸡。

**Comment by chj-damon** [comment]
是的，我自己相差了
