### ISSUE TITLE
为什么InputNumber的onChange事件不是输入就立即触发的？

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#2413]
- antd 版本:1.6.5
- 操作系统及其版本：win10
- 浏览器及其版本: chrome51

查看了inputNumber的例子
http://ant.design/components/input-number/
发现onChange事件并不是像Input组件一样输入后就立即触发的，而是当焦点离开才触发，不知道为什么设计成这样？
我这边的需求是，当inputNumber的value变化的时候，动态的给另一个inputNuber赋上同样的值。
当然希望是能inputNumberA输入数字后，inputNumberB立即会跟着变化。
或者我能通过其他input事件来实现？
谢谢

**Comment by afc163** [comment]
InputNumber 在交互上限制了非法数字的录入，在 blur 的时候会检查并触发 onChange 。

如果需要输入同步，可以使用 `<input />` 或 `<input type="number" />`。

**Comment by ystarlongzi** [comment]
@afc163 

现在 `<InputNumber />` 组件在触发 onChange 事件时表现不一致，导致在 onBlur 事件里可能无法获取到最新的状态。

如下图，[查看demo](http://codepen.io/ystarlongzi/pen/XNyeKx?editors=001)

![111](https://cloud.githubusercontent.com/assets/2840462/21218483/cbea5f1c-c2eb-11e6-81d9-4d986abdcca4.gif)

是否可以考虑在[mixin.js#L76](https://github.com/react-component/input-number/blob/master/src/mixin.js#L76)加个定时器，避免这种现象？

**Comment by benjycui** [comment]
非受控模式就没问题 https://ant.design/components/input-number/#components-input-number-demo-basic

**Comment by benjycui** [comment]
@ystarlongzi 你的问题再单独开个 issue

**Comment by ystarlongzi** [comment]
好的
