### ISSUE TITLE
Form.Item is missing initialValue prop in the type definition

### ISSUE THREAD

**Issue by rvinzent** [ant-design/ant-design#24138]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-in2f0)

### Steps to reproduce
try to use `initialValue` prop in a `Form.Item` as described in the docs using Typescript

### What is expected?
I expect the TS compiler to not complain because this prop exists and is usable in plain JavaScript.

### What is actually happening?
Typescript complains the prop does not exist on the `Form.Item` component

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | macOS 10.15.4 (19E287) |
| Browser | Chrome Version 81.0.4044.138 (Official Build) (64-bit) |

**Comment by zombieJ** [comment]
检查了一下有的，本地重装一下依赖试试。

**Comment by yoyo837** [comment]
> 检查了一下有的，本地重装一下依赖试试。

好像不是懂中文的。

**Comment by afc163** [comment]
It works: https://codesandbox.io/s/antd-reproduction-template-r0400?file=/index.tsx:303-315

**Comment by rvinzent** [comment]
> 检查了一下有的，本地重装一下依赖试试。

That worked 🤦. I don't know how it can be broken in the CodeSandbox I made and working in the same exact one you made. Some dependency probably got patched or something.

Thanks!
