### ISSUE TITLE
有时候请求返回速度太快了, Button的loading状态还没反应过来就没有了.

### ISSUE THREAD

**Issue by lirunwin** [ant-design/ant-design#24134]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Button的loading状态改变太快造成Button闪动. 当loading状态从true变为false之前,希望有个delay

### What does the proposed API look like?
```<Button loading={loading} delay={500}>Submit</Button>```

**Comment by afc163** [comment]
https://ant.design/components/button-cn/#API

仔细看文档。
