### ISSUE TITLE
Tree组件中TreeNode里title属性设置为ReactNode的时候

### ISSUE THREAD

**Issue by MI-Class** [ant-design/ant-design#24140]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mi-class/pen/eYpjoaZ?editors=0011&__cf_chl_jschl_tk__=b55d8a06babd98c7da215c936e49c7ca46accfb6-1589417025-0-AW2x5KkYIfoWiN9TSy7he7xjUWUbsoWbEF0usiEHwajt6IaWdvERmwq-2tYPv8EJAvkMhrplhEcYVETwPdqB5zCpXxqTwiI_uQbQiGiyI9TEzdrcPswb8bOZ5NtlwgolSpZaMMjzkWXf6iTPB_TXDXZ1q5TORcw3oEjLNBq1qkR_QX6XeDKGKVpMfsdnFsCrbXGORKPh2y7n1ov4qpbloy34hLplLXKvv2PjhU9GTt368IwrhGuhc7P7IoyYxluCDdzO7_97_4dC9qH6XwzeQuntUIoBT9vWC8vxwxU9wzo11-qCzMaigoQnliZlsjQfy3Hmjta11qtOv4I1Io7PQbE7WVK1cfX2_lBEFUGEZloXgmg4dPMeDL8zQgvUEw-vdrmugygd-WQAVSK-ROnyAIk](https://codepen.io/mi-class/pen/eYpjoaZ?editors=0011&__cf_chl_jschl_tk__=b55d8a06babd98c7da215c936e49c7ca46accfb6-1589417025-0-AW2x5KkYIfoWiN9TSy7he7xjUWUbsoWbEF0usiEHwajt6IaWdvERmwq-2tYPv8EJAvkMhrplhEcYVETwPdqB5zCpXxqTwiI_uQbQiGiyI9TEzdrcPswb8bOZ5NtlwgolSpZaMMjzkWXf6iTPB_TXDXZ1q5TORcw3oEjLNBq1qkR_QX6XeDKGKVpMfsdnFsCrbXGORKPh2y7n1ov4qpbloy34hLplLXKvv2PjhU9GTt368IwrhGuhc7P7IoyYxluCDdzO7_97_4dC9qH6XwzeQuntUIoBT9vWC8vxwxU9wzo11-qCzMaigoQnliZlsjQfy3Hmjta11qtOv4I1Io7PQbE7WVK1cfX2_lBEFUGEZloXgmg4dPMeDL8zQgvUEw-vdrmugygd-WQAVSK-ROnyAIk)

### Steps to reproduce
不停的选中取消同一个Checkbox(比如删除的Checkbox)
Keep checking and unchecking the same Checkbox

### What is expected?
希望如果从TreeNode里title属性里传入ReactNode的时候里面的点击事件还可以用
Hopefully, the click event inside the TreeNode will still be available if you pass in the ReactNode from the title property inside the TreeNode

### What is actually happening?
如果TreeNode里title属性里传入的ReactNode中有点击时间的话大部分会被Tree中的onSelect属性拦截到而ReactNode中的点击时间无法触发,
If there is a click time in the ReactNode passed in from the title property in TreeNode, most of it will be intercepted by the onSelect property in Tree and the click time in ReactNode will not be triggered

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.8.6 |
| System | win10 |
| Browser | firefox76.0.1 |

---
上次提了issue,因为我例子设置的不恰当,没表达好我想要的被关了,这次我又重开了一下,例子修改了,树形结构里面title部分需要Checkbox,做一个权限管理方面的功能,给菜单赋予权限,每个菜单都具有不同的功能可供选择,而菜单又是树形的结构,既需要选择这个菜单是否展示,又需要选择菜单中有什么权限.相当于Tree组件中的checkable属性是打开的,另外TreeNode的title中也传入的有Checkbox,两个都需要能点击选中却不互相干扰
Example raised issue last time, because I set the inappropriate, not express what I want is closed, this time I reopened, example, modify the Tree structure inside the title part needs the Checkbox, do a permission management function, given access to menus, each menu has different function to choose from, the menu is the structure of the Tree, whether need to choose the menu display, and what is the need to choose the menu permissions. Equivalent to a Tree in the component checkable property is on, the other TreeNode title also have incomingCheckbox. Both need to be able to click and select without interfering with each other

**Comment by MI-Class** [comment]
上次提了issue,但是我例子设置的不恰当,没表达出我的意思,我又重开了一个,修改了例子,我实际意思是Tree组件中的checkable属性是打开的,另外TreeNode的title中也传入的有Checkbox,两个都需要能点击选中却不互相干扰

**Comment by zombieJ** [comment]
用 `stopPropagation` 阻止 Checkbox 传递给 TreeNode 来处理：
https://codesandbox.io/s/jiben-ant-design-demo-cscrr?file=/index.js

**Comment by MI-Class** [comment]
> 用 `stopPropagation` 阻止 Checkbox 传递给 TreeNode 来处理：
> https://codesandbox.io/s/jiben-ant-design-demo-cscrr?file=/index.js

非常感谢,一直在看antd组件本身怎么阻止冒泡,没想到可以自己在组件外层套一个标签来阻止冒泡
