### ISSUE TITLE
china-division中没有香港、澳门和台湾的数据

### ISSUE THREAD

**Issue by Lifuzhen** [ant-design/ant-design#24147]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/cascader-cn/](https://ant-design.gitee.io/components/cascader-cn/)

### Steps to reproduce
页面最后有一句“注意，如果需要获得中国省市区数据，可以参考 china-division。”。使用的时候发现没有香港、澳门 和台湾。

### What is expected?
中国省市区数据要齐全

### What is actually happening?
中国省市区数据不齐全。

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.0 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
最好反馈给 china-division，我们解决不了这个问题。

**Comment by yoyo837** [comment]
https://github.com/modood/Administrative-divisions-of-China/issues/27

**Comment by Lifuzhen** [comment]
> 最好反馈给 china-division，我们解决不了这个问题。

好滴

**Comment by wangxingkang** [comment]
@Lifuzhen https://github.com/pansyjs/china-division  最近整理的可以看下
