### ISSUE TITLE
table支持在多列排序之后，某列的表头不相应鼠标的排序事件

### ISSUE THREAD

**Issue by zhuyuedlut** [ant-design/ant-design#24149]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一个table配置了多列排序，想针对某列固定其优先级最高的列的排序的顺序（用户点击表头不会改变排序的顺序），其他列正常响应

### What does the proposed API look like?
columns中可以有属性配置不响应鼠标的点击事件

**Comment by afc163** [comment]
用 sortOrder 做受控就行了。

**Comment by zhuyuedlut** [comment]
@afc163 好的，我尝试一下，多谢~

**Comment by zhuyuedlut** [comment]
@afc163 这里有个问题，我使用sortOrder对表格的特定的列设置了sortOrder之后，其他列也进行点击的排序了，请问如何解决~

**Comment by afc163** [comment]
来个重现 http://u.ant.design/codesandbox-repro 看看，可能是 bug。

**Comment by zhuyuedlut** [comment]
@afc163 https://codesandbox.io/s/antd-reproduction-template-jrjtz?file=/index.js，仅仅是官网提供的多级排序的示例增加了sortOrder，麻烦看看是不是bug

**Comment by zombieJ** [comment]
这不是 bug，有一列配置 `sortOrder` 后，整个 `columns` 的 sorter 都认为是受控状态。

想一下如果 `sortOrder` 支持半受控。那么当有一列 A 设置了 sortOrder，另一列 B 不设置。你就不知道这个是：
* 故意锁定了 A 排序，B 不排序
* A 排序，B 按用户操作排序
* AB 排序，然后 B 取消排序

更糟糕的是，如果 B 本来设置了 `sortOrder` 然后又设置成了 `undefined`。这是应该非受控，还是被重置了？

排序是 `columns` 级别的，不会存在半受控状态的。

**Comment by afc163** [comment]
如何实现多列排序，某一列固定不能操作呢。

**Comment by zombieJ** [comment]
> 如何实现多列排序，某一列固定不能操作呢。

https://codesandbox.io/s/antd-reproduction-template-s1xl4?file=/index.js
