### ISSUE TITLE
menu子菜单选中状态

### ISSUE THREAD

**Issue by kele5240** [ant-design/ant-design#2414]
#### 本地环境

- antd 版本:  1.6.5
- 操作系统及其版本： mac os  10.11.4
- 浏览器及其版本: chrome 版本 51.0.2704.103 (64-bit)

#### 你做了什么？

官网列子里查看效果，没有本地部署等

#### 你期待的结果是：

正常显示逻辑

#### 实际上的结果：

子菜单选中之后，其父菜单并没有选中样式。外层看起来并不知道处于哪个大的menu下

#### 可重现的在线演示

![bug](https://img.alicdn.com/tps/TB1QyvUKVXXXXajXVXXXXXXXXXX-1105-364.gif)

**Comment by kele5240** [comment]
不知是否交互有意而为之？

**Comment by afc163** [comment]
应该是没做，可以加上。

**Comment by guicode** [comment]
设置Menu.Item.isMenuItem = true
[https://github.com/react-component/menu/blob/master/src/util.js#L36](url)
