### ISSUE TITLE
为什么要给className加后缀处理？

### ISSUE THREAD

**Issue by tkvern** [ant-design/ant-design#2415]
#### 本地环境

- antd 版本: 1.1.0
- 操作系统及其版本： MacOS 10.11.5
- 浏览器及其版本: Chrome 51.0.2704.103 (64-bit)

#### 你做了什么？
将[可收起展开的侧边导航](http://ant.design/docs/spec/layout)导入到项目

#### 你期待的结果是：
像官网一样正常显示

#### 实际上的结果：
缺少样式，由于编译代码时，自动为`className`加了后缀，相应的样式文件不生效。
尝试使用下面的方式导入样式，非常之麻烦。
```js
import styles from './filename.less';
```

#### 可重现的在线演示
![image](https://cloud.githubusercontent.com/assets/10667077/16909796/6db7d41a-4d07-11e6-93af-b13227acb067.png)

![image](https://cloud.githubusercontent.com/assets/10667077/16909741/17af244c-4d07-11e6-8c81-58852b5765c6.png)

#### 需求
1. 是否有去除这种加后缀的方法
2. 如果不能去除，怎么处理className更好

**Comment by afc163** [comment]
https://github.com/css-modules/css-modules

与组件库无关。

**Comment by tkvern** [comment]
在哪去除？。。。。使用antd-init默认就有了

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/blob/1.1.0/boilerplates/plain-react/webpack.config.js#L21-L29

**Comment by chengmu** [comment]
这默认就带了啊 还要自己手动去除才能用官方例子？  看起来不手动去除默认的Menu里面的都不会处理啊。这个启动脚手架是不是也太不友好了

**Comment by afc163** [comment]
脚手架已经更新了。https://github.com/ant-design/babel-plugin-antd/issues/46#issuecomment-238139185
