### ISSUE TITLE
select: 当遇到选中超长文本时无法鼠标悬停无法显示 title

### ISSUE THREAD

**Issue by cipchk** [ant-design/ant-design#24157]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-demo-dlldr)

### Steps to reproduce
见重现

### What is expected?
- 已完成选中，列表不可见时：
- 鼠标悬停时无法利用 `title` 呈现完成的文本内容

### What is actually happening?
鼠标悬停能正常显示 `title`

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | All |
| Browser | All |

**Comment by zombieJ** [comment]
应该直接给 Select 设置 `title` 属性，而不是用 Option 套 `div` 套 `title` 的形式。后者 hover 显示 title 的范围也是残的：
https://codesandbox.io/s/basic-usage-ant-design-demo-hi2bi?file=/index.js

**Comment by DrunkenDreeze** [comment]
.ant-select-single .ant-select-selector .ant-select-selection-item, .ant-select-single .ant-select-selector .ant-select-selection-placeholder{
    pointer-events: auto;
    z-index: 2;
}
