### ISSUE TITLE
Menu.ItemGroup title style

### ISSUE THREAD

**Issue by kesskalli** [ant-design/ant-design#24159]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/kesskalli/pen/ExVejML](https://codepen.io/kesskalli/pen/ExVejML)

### Steps to reproduce
Add a style attribute or className attribute to a Menu.ItemGroup to change the color.
It's not applied to the Menu.ItemGroup title, but the Menu.Item inner text. 

### What is expected?
The title must have the color as defined in the style attribute

### What is actually happening?
The color is inherited from "ant-menu-item-group-title" class.

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | JS |
| System | Windows 10 |
| Browser | Chrome 81 |

**Comment by afc163** [comment]
```diff
- <Menu.ItemGroup title="Item 1" style={customStyle}>
+ <Menu.ItemGroup title={<div style={customStyle}>Item 1</div>}>
```
