### ISSUE TITLE
Want to InputNumber Support 'addonAfter/addonBefore/prefix/suffix' Attribute

### ISSUE THREAD

**Issue by houkunlin** [ant-design/ant-design#24155]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Compatible with input properties。兼容 Input 的 addonAfter/addonBefore/prefix/suffix 这个几个属性。

### What does the proposed API look like?
Consistent with the properties of Input。与 Input 组件的使用方式一致

**Comment by afc163** [comment]
Duplicate of #14284

**Comment by afc163** [comment]
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
