### ISSUE TITLE
Problem with List and List.Item when using inside docz

### ISSUE THREAD

**Issue by jquintozamora** [ant-design/ant-design#24153]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react)

### Steps to reproduce
add List component and List.Item inside

### What is expected?
To work

### What is actually happening?
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons: 1. You might have mismatching versions of React and the renderer (such as React DOM) 2. You might be breaking the Rules of Hooks 3. You might have more than one copy of React in the same app See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | latest |
| System | MacOS |
| Browser | Chrome latest |

**Comment by ghostjzf** [comment]
You don't use the latest version. You can use version 4.1.3 first.

**Comment by huihongzhou** [comment]
4.1.3 is ok

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24176#issuecomment-630607366

**Comment by jquintozamora** [comment]
It looks like it was an issue with antd combined with docz. It looks like it is solved using antd 4.2.5
