### ISSUE TITLE
Transfer 组件能否默认设置一个有返回值的 defaultRender

### ISSUE THREAD

**Issue by hzyhbk** [ant-design/ant-design#24156]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在使用 Formily 做**纯 JSONSchema 表示表单**的时候，我的 JSONSchema 数据是从后台过来的一份 josn字符串，因为 josn 字符串里面又放不了函数，所以 Transfer 组件默认就无法显示选项的标题的
比如我有如下的 JSONSchema (下面是解析之后的 json 对象，原始的是 json 字符串) 
```js
const schema = {
  type: 'object',
  properties: {
  transfer: {
      type: 'number',
      enum: [
        { key: 1, title: '选项1', },
        { key: 2, title: '选项2', },
      ],
      // 'x-component-props': {
      //   render: data => data.title,
      // }
      'x-component': 'Transfer',
      title: '穿梭框',
    },
  }
}
```
现阶段就用这份 jsonSchema 是无法展示出选项的，还需要提供 render 函数

### What does the proposed API look like?
`TransferItem` 类型里有 `title` 字段，所以 Transfer 内部能否将默认的 `defaultRender` 函数设置成 
```js
const defaultRender = data => data.title || null;
```
或者提供一个类似 `defaultRenderKey` 的 props
```jsx
// 外部使用的时候
<Transfer  defaultRenderKey="title" />

// Transfer 内部
const getDefaultRender = defaultRenderKey => data => data[defaultRenderKey] || null
```

**Comment by zombieJ** [comment]
HOC 自己包一下 Transfer 来支持即可。除非完全无法实现，不会特地去做 API 支持。
