### ISSUE TITLE
现在Form组件layout="inline"布局变成了flex，但是其中一个表单项需要强制换行该怎么做呢？

### ISSUE THREAD

**Issue by XSmarter** [ant-design/ant-design#24168]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Form组件layout="inline"，可以自由的换行布局

### What does the proposed API look like?
Form组件layout="inline"，可以自由的换行布局

**Comment by zombieJ** [comment]
用 Row Col 分行。

**Comment by XSmarter** [comment]
@zombieJ 如果不想用这种Row Col布局呢，这种自适应的并不适用于全部用户的需求

**Comment by XSmarter** [comment]
最后如果想换行的form.item 包裹这个div来进行换行。<div style={{ display: 'flex', flexWrap: 'wrap' }}></div>

**Comment by yoyo837** [comment]
总之就是自行包装一下排版

**Comment by crazyair** [comment]
ref: https://github.com/ant-design/ant-design/issues/31044
