### ISSUE TITLE
Search Bar in the doc is not User friendly

### ISSUE THREAD

**Issue by Lahirutech** [ant-design/ant-design#24165]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/switch/](https://ant.design/components/switch/)

### Steps to reproduce
Go to https://ant.design/components/switch/

### What is expected?
Make Search Bar big and the icon black 

### What is actually happening?
actually I spent  10 minutes to find where the hell is your search

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.0 |
| System | windows10 |
| Browser | Chrom |

---
Do it immediately

**Comment by afc163** [comment]
Seems you find it~, it won't be a problem now. :tada:
