### ISSUE TITLE
Popover and Popover arrow position, width and direction issues  inside a table 

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#24172]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-jotce?file=/index.js)

### Steps to reproduce
1. Create a table
2. Ensure have a column which has a link or a button which can show a pop over
3. Add a `ConfigProvider` to ensure popover scrolls with the rows
4. Toggle the `Ellipsis` prop for column and see how the pop over width and position is affected. The popover is actually getting rendered inside the column.
5. In some cases when there is not enough space to render pop over in its present direction, the direction changes but the popover arrow still points to the original direction not the new one
6. Toggle the `placement` prop for popover, if you don't add it we notice the popover width is correct. Adding it somehow limits the width and sometimes also changes the popover direction
7. Popover randomly changes direction showing a flick affect on screen. If first shows at one position and then switches quickly and shows at another making it appear like a glitch

### What is expected?
1. Playing with `ellipsis` prop in table or `placement` in popover, should not affected the popover so dramatically. 
2. Pop over arrow direction should show correctly in accordance with popover direction
3. Before rendering pop over, if it is determined that the space may not be enough and the popover has to instead show up in a new place, do not render it twice. It shows popover at one place and then flicking to another.
4. Pop over width should not change if placement prop is provided

### What is actually happening?
1. Playing with `ellipsis` prop in table or `placement` in popover, affects the popover. `Ellipsis` prop for table makes popover render inside the column, specially when it has a `ConfigProvider`
2. Pop over arrow direction changes randomly sometimes, if popover direction changes
3. When changes direction, pop over seems to render twice in some cases and so makes it appear like a glitch or flicker affect
4. Pop over should width change in some cases if placement prop is provided

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13 |
| System | Mac OSX |
| Browser | Safari 13.1, Chrome 80.0 |

**Comment by zombieJ** [comment]
For `expect.1`, it's by design. Table ellipsis use html native ability which makes container as `overflow:hidden`. So if config `getPopupContainer` to parentNode, it cut as expect.

For placement dynamic change arrow not switch is a bug. I will take a look.

**Comment by StallionV** [comment]
Thanks @zombieJ how about points 3 and 4.
Why does the width of pop over change and why does it render twice. I believe those are also bugs

**Comment by afc163** [comment]
Close in https://github.com/yiminghe/dom-align/pull/53
