### ISSUE TITLE
升级antd4的时候List.Item组件使用时会报Invalid Hook

### ISSUE THREAD

**Issue by ghostjzf** [ant-design/ant-design#24176]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
渲染阶段就报错

### What is expected?
不报错

### What is actually happening?
The above error occurred in the <Item> component:

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.12 |
| System | MacOS |
| Browser | chrome |

---
 The above error occurred in the <Item> component:
in Item (at Catalog/index.tsx:68)
    in ul (created by List)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Spin (created by List)
    in div (created by List)
    in List (at Catalog/index.tsx:64)
    in div (at Catalog/index.tsx:63)
    in div (created by Context.Consumer)
    in div (created by Context.Consumer)
    in Spin (at Catalog/index.tsx:62)
    in Catalog (at AccountOpen/index.tsx:58)
    in div (created by Context.Consumer)
    in Col (at AccountOpen/index.tsx:57)
    in div (created by Context.Consumer)
    in Row (at AccountOpen/index.tsx:56)
    in div (at AccountOpen/index.tsx:55)
    in AccountOpen (at withPermission/index.js:61)
    in WithPermission-AccountOpen (at withLogin/index.js:14)
    in WithLogin (at withTitle/index.tsx:16)
    in WithTitle-WithLogin (created by Context.Consumer)
    in div (at TabBody.tsx:16)
    in Route (at TabBody.tsx:13)
    in TabBody (at App.tsx:112)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Content (at App.tsx:134)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (at App.tsx:120)
    in App (created by Context.Consumer)
    in withRouter(App) (at App/index.tsx:41)
    in Router (created by BrowserRouter)
    in BrowserRouter (at App/index.tsx:40)
    in FormProvider (created by Context.Consumer)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (at App/index.tsx:39)
    in MobXProvider (at App/index.tsx:38)
    in ErrorBoundary (at App/index.tsx:37)
    in Root (created by HotExportedRoot)
    in AppContainer (created by HotExportedRoot)
    in HotExportedRoot (at app/index.tsx:9)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.

**Comment by ghostjzf** [comment]
把List.Item换成div标签就不会报错

**Comment by ghostjzf** [comment]
@observer
class Catalog extends Component<IProps, IState> {
    state = {
        loading: true
    };

    timer;

    componentDidMount() {
        this.getMenuStats();
        this.autoUpdateMenuStats(30);
    }

    componentWillUnmount() {
        clearInterval(this.timer);
    }

    autoUpdateMenuStats = (duration: number) => {
        // duration值单位为秒
        this.timer = setInterval(() => {
            this.getMenuStats();
        }, duration * 1000);
    };

    getMenuStats = async () => {
        try {
            await menuStore.getMenuStats();
        } catch (error) {
            console.log(error.error_msg);
        }

        this.setState({
            loading: false
        });
    };

    render() {
        const { width, menus } = this.props;
        const { loading } = this.state;
        const menuStats = toJS(menuStore.menuStats);

        return (
            <Spin spinning={loading} tip="loading...">
                <div className="us-open-catalog" style={{ width }}>
                    <List
                        bordered
                        dataSource={menus}
                        renderItem={(item: any) => (
                            <List.Item className="list-item">
                                <NavLink
                                    className={`list-item-link ${item.disabled && 'list-item-disabled'}`}
                                    activeClassName="list-item-active"
                                    to={item.path}
                                    onClick={e => {
                                        if (!item.disabled) {
                                            this.getMenuStats();
                                        } else {
                                            e.preventDefault();
                                        }
                                    }}>
                                    <Row justify="space-between">
                                        <Col>{item.name}</Col>
                                        <Col>
                                            <Badge
                                                style={{ ...badgeColor[item.badgeColor || 'blue'] }}
                                                count={(menuStats && menuStats![item.dataIndex]) || 0}
                                                showZero
                                            />
                                        </Col>
                                    </Row>
                                </NavLink>
                            </List.Item>
                        )}
                    />
                </div>
            </Spin>
        );
    }
}

export default Catalog;

**Comment by ghostjzf** [comment]
看下这个代码有问题吗，就是这段报错的

**Comment by yoyo837** [comment]
没办法调试，请提供在线demo

**Comment by ghostjzf** [comment]
暂时没找到原因，我选择了4.1.3的版本就不会报错了

**Comment by ghostjzf** [comment]
> 没办法调试，请提供在线demo

react-hot-loader没有配置支持hooks版本会导致这个组件报错，可以关掉这个问题了

**Comment by afc163** [comment]
@ghostjzf ❤️，可以自行关闭。
