### ISSUE TITLE
select  multiple  could support  repeat input?

### ISSUE THREAD

**Issue by ranqiqiang** [ant-design/ant-design#24179]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.I want to do support calculation formula ,like this  [  num * num    num/total    ]   .but now just support input one  [ num ]

### What does the proposed API look like?
repeat=true

**Comment by zombieJ** [comment]
Select is not design for this usage. If you want to show the same item. You can dynamic generate options like:
```tsx
<Option value="num_1">num</Option>
<Option value="num_2">num</Option>
```
