### ISSUE TITLE
document error of custom icon with svg file

### ISSUE THREAD

**Issue by shengliangli** [ant-design/ant-design#24175]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/icon-cn/](https://ant.design/components/icon-cn/)

### Steps to reproduce
the document said:
```
import MessageSvg from 'path/to/message.svg'; // path to your '*.svg' file.
```
It does not work.

Must be writen:
```
import {ReactComponent as MessageSvg} from 'path/to/message.svg'; // path to your '*.svg' file.
```

### What is expected?
right document

### What is actually happening?
--

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrom 81 |

---
@svr/webpack v5.4.0, webpack v4

**Comment by yoyo837** [comment]
文档没错吧，为何还需要 `{ReactComponent as MessageSvg} `?

**Comment by yoyo837** [comment]
ts definition ref: #20142

**Comment by darksheepgod** [comment]
@afc163  Please update the v3.x document as well.
