### ISSUE TITLE
Drawer 组件在 mask 属性为 false 的情况下，抽屉从开到关时没有动画效果

### ISSUE THREAD

**Issue by elowes** [ant-design/ant-design#24188]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/duocengchouti-ant-design-demo-l3i2g?file=/index.js)

### Steps to reproduce
点击 Toggle drawer 按钮，抽屉立刻消失，没有动画效果

### What is expected?
和打开时一样有动画效果

### What is actually happening?
无动画效果

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.12.0 |
| System | macOS |
| Browser | Chrome 81 |

---
[https://github.com/ant-design/ant-design/blob/8497e54e39e781fd748659344a3b7489b6264f8d/components/drawer/style/drawer.less#L14](https://github.com/ant-design/ant-design/blob/8497e54e39e781fd748659344a3b7489b6264f8d/components/drawer/style/drawer.less#L14)

上面这里 height 属性有动画延迟。

[https://github.com/ant-design/ant-design/blob/8497e54e39e781fd748659344a3b7489b6264f8d/components/drawer/style/drawer.less#L37](https://github.com/ant-design/ant-design/blob/8497e54e39e781fd748659344a3b7489b6264f8d/components/drawer/style/drawer.less#L37)

然后关闭时，子组件采用了 height: 100%; 但是由于上面父组件的 height 有动画延迟，所以此时的子组件的高度为 0。导致界面上面看起来没有动画，实际上是元素没有高度。

**Comment by afc163** [comment]
Fixed in #24082
