### ISSUE TITLE
可以禁用 tab scrollToActiveTab 行为

### ISSUE THREAD

**Issue by concefly** [ant-design/ant-design#24181]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当页面 dom 复杂之后，rc-tab 默认的 tab 滚动到激活项的行为会导致比较严重的 reflow 消耗。

https://github.com/react-component/tabs/blob/a3150988c5f8819f88a4d7bb7f438047aafeba5d/src/ScrollableTabBarNode.js#L104

![image](https://user-images.githubusercontent.com/6647656/82027013-2ebc3a00-96c6-11ea-9c25-e0c9952745ec.png)

希望可以提供一个配置开关，业务上可以禁用这个行为

### What does the proposed API look like?
`TabsProps['disableAutoScrollToActiveTab']?: boolean`

**Comment by concefly** [comment]
相关 issue：https://github.com/ant-design/ant-design/issues/20003#issuecomment-629093212

**Comment by afc163** [comment]
可以用 https://github.com/react-component/resize-observer 重构来解决性能问题。

**Comment by afc163** [comment]
Trace in #24284

**Comment by afc163** [comment]
Fixed in #24284
