### ISSUE TITLE
Form的initialValues对于select的mode为select时，需要初始化数组，但是无法实现初始化数组，想让其显示name，id为value

### ISSUE THREAD

**Issue by FrontDream** [ant-design/ant-design#24193]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-18f3s?file=/index.js:388-396)

### Steps to reproduce
查看重现链接就可以查看

### What is expected?
期望的是，传入一个数组，name为显示值，id为最终选择传出来的value

### What is actually happening?
报错，无法实现

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13 |
| System | Mac |
| Browser | Chrome |

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-0h5ln?file=/index.js

**Comment by yoyo837** [comment]
文档都有写噢，请仔细阅读一下
