### ISSUE TITLE
form.setFieldsValue does not work for Select with multiple mode

### ISSUE THREAD

**Issue by csandanov** [ant-design/ant-design#24196]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-mfrxb?file=/index.js)

### Steps to reproduce
- Create form with select with mode multiple and a few values
- Call `form.setFieldsValue` on the form item to set some of the values

### What is expected?
Specified values must be selected

### What is actually happening?
No values selected

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.12.0 |
| System | macOS |
| Browser | Chrome 81.0.4044.138 |

---
- I tried to use labels and values, both did not work
- I found a bunch of similar issues but most of them closed as invalid, There's issue https://github.com/ant-design/ant-design/issues/19375 with the comment saying you should use `normalize` but this was for v3 and code examples do not work

**Comment by csandanov** [comment]
Ok, it actually works.

**Comment by qduld** [comment]
> Ok, it actually works. 🤦‍♂️

I have the same issue,but it not work!

**Comment by qduld** [comment]
> Ok, it actually works. 🤦‍♂️

![捕获](https://user-images.githubusercontent.com/23184084/85118515-09859300-b253-11ea-8785-3ff497a006e8.PNG)
