### ISSUE TITLE
经form包裹的Upload，disabled后依然可以通过点击label调起上传窗口

### ISSUE THREAD

**Issue by 7inFen** [ant-design/ant-design#24197]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-lovelace-p47w1?file=/src/App.js)

### Steps to reproduce
Upload组件已禁用，点击Upload组件无法调起上传窗口，但是通过点击label可以调起。

### What is expected?
Upload组件禁用的情况下点击label也不能调起上传窗口

### What is actually happening?
调起了

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.12.0 |
| System | Windows 10 1909 |
| Browser | chrome  |

---
点击 demo `上传` 文字

**Comment by afc163** [comment]
这个应该修过了：https://github.com/ant-design/ant-design/pull/16483 要再检查一下。

**Comment by FAKER-A** [comment]
https://codesandbox.io/s/brave-poincare-b0r87?file=/src/App.js:246-489  @7inFen 这样可以让点击label不触发，刚刚看了一下这个触发的操作好像是 label 标签中 for 属性的特性。
