### ISSUE TITLE
BackTop 无效

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#24192]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/back-top-cn/#components-back-top-demo-custom](https://ant.design/components/back-top-cn/#components-back-top-demo-custom)

### Steps to reproduce
滚动后点击up 并没有返回到顶部 同时，up消失了

### What is expected?
滚动到顶部，同时再次滚动到底部后出现up

### What is actually happening?
没有任何效果

| Environment | Info |
|---|---|
| antd | 4.2.2|
| React | latest |
| System | windows  |
| Browser |  chrome latest |

**Comment by afc163** [comment]
Firefox 是好的。

**Comment by 43374166** [comment]
不起作用啊  滑动到底部不出现这玩意
