### ISSUE TITLE
引入的js太大，首页0.chunk.js有1mb，求正确使用的姿势

### ISSUE THREAD

**Issue by bethinner** [ant-design/ant-design#2420]
使用了挺多antd 的组件，并使用了web'pack的分块打包，但是首页加载了antd的js，有1MB

 我期待的结果是：打包的时候可以按需要打包js

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design#use-modularized-antd

http://ant.design/docs/react/getting-started#%E6%8C%89%E9%9C%80%E5%8A%A0%E8%BD%BD
