### ISSUE TITLE
When the InputNumber step is clicked, the decimal number over 6 decimal becomes scientific notation

### ISSUE THREAD

**Issue by wing1003** [ant-design/ant-design#24206]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-sypo3)

### Steps to reproduce
Click the step button of the third InputNumber.

### What is expected?
The decimal over six decimal in InputNumber don't become scientific notation.

### What is actually happening?
The decimal over six decimal in InputNumber has become scientific notation.

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | React 16 |
| System | Mac |
| Browser | chrome |

---
I seems that there are something problem on the dependency rc-input-number. The source code in line 135-145 of src/index.js. 

貌似是InputNumber的依赖rc-input-number有问题。在源码的src/index.js的135-145行这段代码的逻辑有问题

**Comment by fireairforce** [comment]
尝试修复了一下～

**Comment by mattfixme** [comment]
4.18.3 version still has this problem. this link [https://codesandbox.io/s/polished-river-ohly2?file=/src/App.js](codesandbox) can reproduce, when i input, InputNumber will show scientific notation, when input lose focus, become normal
