### ISSUE TITLE
ant的less文件的变量替换不够彻底

### ISSUE THREAD

**Issue by davedavehong** [ant-design/ant-design#24205]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/davedavehong/ant4-diag](https://github.com/davedavehong/ant4-diag)

### Steps to reproduce
yarn，yarn build

### What is expected?
打包的css文件中不存在ant开头的样式名，全被替换为byMainApp开头

### What is actually happening?
打包的css文件中既有ant开头，也有byMainApp开头的样式名

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 没装 |
| System | mac |
| Browser | Chrome 版本 81.0.4044.138（正式版本） （64 位） |

**Comment by morenyang** [comment]
I can take this
