### ISSUE TITLE
Card activeTabKey or tabActiveKey

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#24208]
Are `tabActiveKey` and `defaultTabActiveKey` better prop name?

In [pro-layout](https://github.com/ant-design/ant-design-pro-layout) it named to `tabActiveKey`.

**Comment by AshoneA** [comment]
我觉得改了会造成 breaking change 的...

**Comment by afc163** [comment]
如果要改肯定要兼容，然后加 warning。

**Comment by xrkffgg** [comment]
Can it be simplified to `active` and `default`

**Comment by shaodahong** [comment]
In my see, Card had many tab props, we can remove it(waring), and use it

```jsx
<Card
  tabProps={{
    activeKey: 1,
    defaultActiveKey: 1
  }}
</>
```

**Comment by yoyo837** [comment]
tab前缀的属性在Card tab相关功能中有明确指向性意图是tab相关功能使用的。个人建议保留。

**Comment by zombieJ** [comment]
没有特别的倾向性，感觉两者都差不多。原本的把  `TabKey` 作为一个标识，这个提议是把整个 `tabActiveKey` 作为标识。可改可不改的情况下建议不改。

PS： 定完了可以更新一下：https://github.com/ant-design/ant-design/wiki/API-Naming-rules

**Comment by afc163** [comment]
贴一下出处：
<img width="680" alt="image" src="https://user-images.githubusercontent.com/507615/82205351-0ab45f00-9939-11ea-9b07-607cdf6578b8.png">

**Comment by zombieJ** [comment]
按照 naming standard，属性名都要先过一下已有的名称表。个人感觉 pro layout 才是 typo = =

**Comment by shaodahong** [comment]
这种属于 compose 组件，心智上来说我觉得都放到 `tabProps` 更好，换个名字治标不治本

**Comment by hengkx** [comment]
个人觉得不管是什么 最好是一种统一的风格，对于我这种有些强迫症的人来说，就好比 文档中的有的默认值用‘ 包裹 有的没有，我一直都想把所有的给他统一😭
