### ISSUE TITLE
PageHeader component support transmission Breadcrumb component

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#24217]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
More flexible data structure support. By transferring props, these steps can become cumbersome when you encounter custom data structures and switch whether to display breadcrumbs or not.

### What does the proposed API look like?

```jsx
import React from 'react';
import  { PageHeader, Breadcrumb }  from 'antd';

const breadcrumb = (
   <Breadcrumb>
       {['Home', 'user'].map(val => <Breadcrumb.Item>{val }</Breadcrumb.Item>)}
   </Breadcrumb>
);

<PageHeader
    className="site-page-header"
    title="Title"
    breadcrumb={breadcrumb}
    subTitle="This is a subtitle"
  />
```

**Comment by afc163** [comment]
Is there any usage scenario that can't be implemented by current breadcrumb API?

**Comment by kaysonwu** [comment]
**Now**
```ts
const routes = [{ id: 1,name: 'Home' }, {id: 2, name: 'user'}];

 function itemRender(route: any) {
    return <span key={route.name}>{route.name}</span>;
  }

 <PageHeader title="User" breadcrumb={{ routes, itemRender }} />
```

1. I have to follow the breadcrumb [route](https://ant.design/components/breadcrumb-cn/#routes) type
2. Sometimes I don't want to display `Breadcrumb`, but when it comes to custom data types, I have to always provide `itemRender`
3. When customizing data types, it is not friendly enough to `TS`


**After**
```ts
const breadcrumb = showBreadcrumb  && (
   <Breadcrumb>
       {['Home', 'user'].map(val => <Breadcrumb.Item>{val }</Breadcrumb.Item>)}
   </Breadcrumb>
);

<PageHeader
    className="site-page-header"
    title="Title"
    breadcrumb={breadcrumb}
    subTitle="This is a subtitle"
  />
```
In this way, I can freely render the `Breadcrumb` while still using the `PageHeader` component

**Comment by afc163** [comment]
```jsx
const routes = [{ id: 1,name: 'Home' }, {id: 2, name: 'user'}];

function itemRender(route: any) {
  return <span key={route.name}>{route.name}</span>;
}

<PageHeader title="User" breadcrumb={showBreadcrumb && { routes, itemRender }} />
```

What is the different between this and component usage?

**Comment by kaysonwu** [comment]
It looks good, but `typescript` will give you a type warning.  In fact, I want to find a clearer way to write,  Instead of discussing whether it can be achieved by existing methods.

**Comment by afc163** [comment]
What is the type warning? We should fix it.

**Comment by kaysonwu** [comment]
My routes type is customized. It does not follow the [route](https://ant.design/components/breadcrumb/#routes) type of breadcrumb, so it is not an error

**Comment by afc163** [comment]
I think there is no harm that support `breadcrumb={<Breadcrumb />}` if this would bring declarative clarity for you, PR is welcome~

**Comment by kaysonwu** [comment]
ok！

**Comment by kaysonwu** [comment]
I think this issue should be reopen because it is currently impossible to implement breadcrumb with icon.

**Comment by kaysonwu** [comment]
@afc163

**Comment by kaysonwu** [comment]
I can't come up with a new PR right now. It should be possible to pass a `routes` object or breadcrumb component.

**Comment by iloveip** [comment]
Hi @kaysonwu,

Did you manage to make a custom component for `breadcrumb` in `PageHeader`? I have the same problem.
