### ISSUE TITLE
Menu not displaying the correct submenu arrow icon when right positioned

### ISSUE THREAD

**Issue by minotaurrr** [ant-design/ant-design#24218]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sider-ant-design-demo-4plqq?fontsize=14&hidenavigation=1&theme=dark&file=/index.js)

### Steps to reproduce
Place menu on the right hand side of the screen with submenus in it.

### What is expected?
Submenu arrow icon to be pointing towards left and the icon to be placed to the right of the arrow.

### What is actually happening?
The arrow icon on the submenu is pointing towards right when the popup appears on the left. The menu icon is also displayed on the left of the arrow.

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | macOS |
| Browser | Chrome 81 |

**Comment by afc163** [comment]
Maybe what you need is RTL mode: https://ant.design/components/config-provider/#components-config-provider-demo-direction

**Comment by minotaurrr** [comment]
@afc163 Thanks that worked. For anyone with the same issue, you can wrap an individual component around configprovider
