### ISSUE TITLE
upload组件的fileList上传进度条的样式支持定制

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#24213]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
upload组件的fileList上传进度条的样式支持定制，例如支持设置【进度条线的宽度，单位 px】(strokeWidth)和显示【进度数值或状态图标】(showInfo)等属性

### What does the proposed API look like?
接受一个props属性：progressAttr，具体API属性参考：https://ant.design/components/progress-cn/

**Comment by afc163** [comment]
```diff
- progressAttr
+ progress={{ ... }}
````

可以就叫 progress，欢迎 PR。

**Comment by afc163** [comment]
close in #24319
