### ISSUE TITLE
Table - please add an option to control sorting logic through props

### ISSUE THREAD

**Issue by yonatanlozinsky** [ant-design/ant-design#24224]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am currently working on a feature which displays an array of objects in two ways: antd table and a custom card layout.
I was asked to share the sorting state between displays, meaning that if for instance I sorted by date of birth ascending on the table, and then switch display modes, the sorting will stay. Could not find a way in the docs or questions regarding this, if it exists already - sorry and please point me there :)

Thanks, amazing work by the way!

### What does the proposed API look like?
Props on the table component:
sortBy: {column: String, order: String},

or maybe separate these into two, but I think that it should go together.
,

**Comment by afc163** [comment]
We provider `column.sorter` and `column.sortOrder`, I believe those props can make any kind of sort function.

**Comment by yonatanlozinsky** [comment]
It's specific per column,
If I change the current column to another one in the card layout, how does the table listen to it?
