### ISSUE TITLE
Small switch with icon render incorrect offset on check

### ISSUE THREAD

**Issue by Gervwyk** [ant-design/ant-design#24226]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-qm3k2?file=/index.js)

### Steps to reproduce
Switch with checkedChildren, small and checked
```
<Switch
   size="small"
   checkedChildren={<ExclamationCircleOutlined />}
   checked={true}
 />
```

### What is expected?
Padding on switch right is consistent when switched.

### What is actually happening?
Padding on switch right is inconsistent when switched.

| Environment | Info |
|---|---|
| antd | 4.2.3 |
| React | latest |
| System | macOs 10.15.3 |
| Browser | Chrome 80.0.3987.122 |

---
The error was introduced in v4.2.3 with:

https://github.com/ant-design/ant-design/commit/fd7c94240315bece6556b3362e2db7e0cc8abbf5#diff-127f550453f2759d7ec11151b1bcdb86R123

Works for Switch small and checked but not taking into account checkedChildren width.

**Comment by afc163** [comment]
@lexlexa
