### ISSUE TITLE
form's api that setFields is not work,console error :TypeError: fields.forEach is not a function     at Object.FormStore.setFields 

### ISSUE THREAD

**Issue by sujiangyin** [ant-design/ant-design#24225]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#API](https://ant.design/components/form-cn/#API)

### Steps to reproduce
1、formRef.setFields({
            [ipsKey]: {
                value: item,
                errors: [errorMsg]
            }
        });

### What is expected?
set the fields info ，include value and error

### What is actually happening?
console:
index.js:1437 TypeError: fields.forEach is not a function
at Object.FormStore.setFields (useForm.js:440)

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | ^16.12.0 |
| System | win10 |
| Browser | chrome |

**Comment by huseyingoztok** [comment]
@sujiangyin  can you try this?

formRef.setFields([
  {
    name: ipsKey,
    value: item,
    errors: [errorMsg]
    }
]);

**Comment by sujiangyin** [comment]
yes,this is the new usage，thank you very much



---Original---
