### ISSUE TITLE
菜单menu组件没有对齐

### ISSUE THREAD

**Issue by junhwong** [ant-design/ant-design#24228]
如题, 效果如下

![image](https://user-images.githubusercontent.com/8044424/82153241-db4e1580-9898-11ea-9226-ed67df38f7ec.png)

PS: 组件样式表里边没看到有对齐的css

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.3.1 |
| System | win10 |
| Browser | chrome/edge |

**Comment by imhxc** [comment]
给个复现链接吧

**Comment by junhwong** [comment]
@afc163 @imhxc https://codesandbox.io/s/antd-reproduction-template-hjwj9

**Comment by imhxc** [comment]
@junhwong 是被你设置的 CSS 样式影响了。
你在 index.css 文件中对 `.App` 设置了 `text-align: center`，把该属性去掉就可以了。

**Comment by junhwong** [comment]
@imhxc 组件样式不应该受外部影响吧

**Comment by junhwong** [comment]
除非显示覆盖或重写

**Comment by imhxc** [comment]
CSS 属性会继承呀。

**Comment by xrkffgg** [comment]
ant-menu 中 没有定义 text-align，就会 继承上层的啊

**Comment by junhwong** [comment]
但不统一阿，如果统一那么其它组件也应该是这样 如 button

**Comment by junhwong** [comment]
> menu

这也是我提这个issue的原因

**Comment by yoyo837** [comment]
你意思menu顶层加个默认对齐？

**Comment by junhwong** [comment]
menu组件我觉得也应该设置一个属性 左对齐(默认)，右对齐，居中对齐

**Comment by junhwong** [comment]
并且 menu组件还有有个是否平铺的控制属性

**Comment by junhwong** [comment]
`mode="horizontal"`

**Comment by xrkffgg** [comment]
> `mode="horizontal"`

http://localhost:8001/components/menu-cn/#components-menu-demo-horizontal

**Comment by xrkffgg** [comment]
> menu组件我觉得也应该设置一个属性 左对齐(默认)，右对齐，居中对齐

Menu 中包含多个 元素，不建议统一设置 `text-align`

**Comment by imhxc** [comment]
你提到的 Button 组件居中是因为 Ant Design 主动加了 `text-align: center`，因为大多数场景下，按钮文案都是要居中的；

> menu组件我觉得也应该设置一个属性 左对齐(默认)，右对齐，居中对齐

你这个需求可以直接 `className` 来实现。

**Comment by yoyo837** [comment]
我理解他的意思是，组件内应该默认含有自己的文本对齐方式不直接依赖css的默认值，现在的组件有的有如button,有的没有如menu。

> Menu 中包含多个 元素，不建议统一设置 text-align

如果按上面的说法做，不同的元素内部再覆盖自己需要的对齐方式即可。

**Comment by junhwong** [comment]
我的意思是 menu 组件在增加一个 align的属性来控制，像flex一样，这样默认情况也是统一的，而现在一个上层 text-align就影响了，

**Comment by junhwong** [comment]
@yoyo837 是的

**Comment by xrkffgg** [comment]
align  center 的样子，感觉 很奇怪

![image](https://user-images.githubusercontent.com/29775873/82191751-94f2c800-9925-11ea-8dc6-f8132fa2a4ed.png)


---
可以加上一个默认的 text-align

**Comment by imhxc** [comment]
你这个不太合理，组件要考虑普适性，大多数场景下 Menu 组件都是默认对齐，跟随文档或父组件走。（除非像 Button 组件这种比较特殊）。
另外 CSS 可继承的属性很多，不只 `text-align` 一个，`text-align` 支持配置，那其他的是不是也要支持。

**Comment by junhwong** [comment]
我的理解 `组件`应该是相对独立的如(web components规范)一样，不显示覆盖或重写都应该是默认的样式，不受其它的影响

**Comment by imhxc** [comment]
> web components

你提到的这个应该是  Shadow DOM，但是目前 Ant Design 好像不支持。

而且有时候用户就是需要做些覆盖，用来调试一些细节。

**Comment by junhwong** [comment]
默认样式也是允许显示覆盖和重写的，开闭原则

**Comment by junhwong** [comment]
并且 大多数人默认也是不做调整的，这也是选择UI库的基本思路

**Comment by junhwong** [comment]
相信大多的调整最多的就是风格(颜色)和尺寸

**Comment by yoyo837** [comment]
如果前面的意思没理解错，现在的状态没那么理想，team可能不一定改，即使改也会拉得很长，那么多组件。 另外，如果你要覆盖全局的，顺手再加样式帮menu的再覆盖回去一遍吧。

**Comment by imhxc** [comment]
1. 你的 issue 中的需求可以通过 `className` 覆盖样式来实现;
 2. 你在 `.App` 类中设置了 `text-align: center` 这本身也是样式覆盖，所以你要为你的覆盖操作带来的问题做额外的处理；
 3. 大多数组件不能显示的设置对齐方式，因为要跟随文档或父组件走，不然会破坏 CSS 的继承关系；

**Comment by junhwong** [comment]
我的本意是帮助更加完善antd，我如果有特别的需求，就是默认有很多样式我也会覆盖重写。
并不是要解决或不知道怎么解决。

作为用户我希望antd完善强大、方便，就是这样
