### ISSUE TITLE
Error after following the 'Use in Typescript' instruction

### ISSUE THREAD

**Issue by mpiorowski** [ant-design/ant-design#24230]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mpiorowski/energy-portal/tree/develop](https://github.com/mpiorowski/energy-portal/tree/develop)

### Steps to reproduce
1. Follow the antd instruction https://ant.design/docs/react/use-in-typescript
2. Run the application using 'yarn start'
3. Get error

### What is expected?
Running applciation

### What is actually happening?
Got following error:

./node_modules/antd/lib/notification/style/index.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/antd/lib/notification/style/index.less)
Syntax error: Unknown word (10:4)

   8 | @notification-margin-bottom: 16px;
   9 | 
> 10 | .@{notification-prefix-cls} {
     |    ^
  11 |   .reset-component;
  12 | 

| Environment | Info |
|---|---|
| antd | 4.2.3 |
| React | React 16.13.1 |
| System | Ubuntu 20 |
| Browser | Mozzilla Firefox |

**Comment by atkinson** [comment]
I get this too. react@16.13.1; antd@4.2.3; OSX / Chrome

**Comment by afc163** [comment]
Fixed in #24227
