### ISSUE TITLE
Card Extras are not responsive

### ISSUE THREAD

**Issue by csufeardir** [ant-design/ant-design#24232]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/s/antd-reproduction-template-forked-zqhych?file=/index.js)

### Steps to reproduce
Create Antd Cards inside Antd Row and Column. Add Extras to card, then decrease the column size. 

### What is expected?
Extras of the card to get smaller responsively, as its contents do.

### What is actually happening?
Extras stay the same size, overflowing the card, while contents get smaller as expected.

| Environment | Info |
|---|---|
| antd | 4.2.3 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome 81.0.4044.138 |

**Comment by theappbangla** [comment]
I'm also facing the same issue.
Did you find any solution?

**Comment by csufeardir** [comment]
> I'm also facing the same issue.
> Did you find any solution?

Unfortunately I did not work on a solution, but I believe it can be solved via overriding the CSS for card elements.

**Comment by zombieJ** [comment]
You can override it by media selector self: https://codesandbox.io/s/antd-reproduction-template-forked-jvv4vk?file=/index.css
