### ISSUE TITLE
在 create-react-app 中使用,文档是不是有误？

### ISSUE THREAD

**Issue by renleiabc** [ant-design/ant-design#24241]
![image](https://user-images.githubusercontent.com/24283195/82172700-81336b80-98fd-11ea-95a5-556012f8c2bb.png)
这是在raco.config.js 用于修改默认配置；
但是这里
![image](https://user-images.githubusercontent.com/24283195/82172737-9f996700-98fd-11ea-8188-be0cbf051af4.png)
又变成修改 config-overrides.js 文件如下。
难道没有问题吗？

**Comment by miaojinxing** [comment]
> 最新文档上说是在craco.config.js中进行了修改配置；
> 但是下边又变成了config-overrides.js中配置。
> 难道没有问题吗？

他有dome  个人觉得不是什么好方案，建议网上谷歌百度
