### ISSUE TITLE
Modal中的Form被销毁后没有重新初始化表单值

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#24248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-et4qj?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
`destroyOnClose`已经开启
点击`打开`，修改`Input`的内容，关闭Modal后重新打开仍然为编辑后的值

### What is expected?
重新打开Modal后Input值为初始化的`1`

### What is actually happening?
Form没有重新初始化

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Microsoft Edge  81.0.416.53 |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21740#issuecomment-593105570
