### ISSUE TITLE
【CheckBox】 wrap in 【react-sortable-hoc】 items , can not check , after drag item to another place. 

### ISSUE THREAD

**Issue by woshiqiang1** [ant-design/ant-design#24249]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/pensive-galileo-8o8lh?file=/src/Table.jsx](https://codesandbox.io/s/pensive-galileo-8o8lh?file=/src/Table.jsx)

### Steps to reproduce
1. wrap a checkbox in each 【react-sortable-hoc】item
2. uncheck a checkbox 
3. drag the uncheck item to another place
4. check the checkbox // you will find it can't be check angin 

### What is expected?
checkbox can be checked, after drag

### What is actually happening?
checkbox can't be checked, after drag

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.13.0 |
| System | windows |
| Browser | chrome |

---
This bug is found in antd@3.17.0, before this version is ok, but version after @3.17.0 seems has this bug.

**Comment by woshiqiang1** [comment]
sorry，yesterday is very busy. here is the reproduce link :
https://codesandbox.io/s/pensive-galileo-8o8lh?file=/src/Table.jsx

**Comment by woshiqiang1** [comment]
click the right-top corner icon in the table, you well see the checkbox group.

**Comment by afc163** [comment]
Don't use `index` as React key.

**Comment by woshiqiang1** [comment]
> Don't use `index` as React key.

Thaks，I change the key of sortItem to `item.title`, the bug is fixed. I don't understant why antd@3.16.x don't have this bug。
