### ISSUE TITLE
Tabs components 高度定死导致不能自适应高度

### ISSUE THREAD

**Issue by wenshan** [ant-design/ant-design#2425]
#### 本地环境

- antd 版本:0.12.13
- 操作系统及其版本：mac
- 浏览器及其版本:chrome

#### 你期待的结果是：

    .card-container > .ant-tabs-card > .ant-tabs-content {
    background: #fff;
    padding: 16px;
    height: auto;
    margin-top: -16px;
}

#### 实际上的结果：

    .card-container > .ant-tabs-card > .ant-tabs-content {
    background: #fff;
    padding: 16px;
    height: 120px; 
    margin-top: -16px;
}

**Comment by afc163** [comment]
组件没有内置这段代码，你可以在业务中自行修改。
