### ISSUE TITLE
file Uplaod Dragger inside component return undefined

### ISSUE THREAD

**Issue by Mouerr** [ant-design/ant-design#24257]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/file-uplaod-dragger-inside-component-itcnf?file=/index.js)

### Steps to reproduce
fill the input, upload file and submit

### What is expected?
expected dragger FileList value to be in submit values

### What is actually happening?
all inputs values are filled when submit except file dragger value is undefined

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | react 16.3.1 |
| System | windows 7 64bit |
| Browser | chrome 81.0.4044.122 (Official Build) (64-bit) |

---
the fileList state inside fileUpload.js is filled but it seems form.item is not taking it as a value

**Comment by afc163** [comment]
You need to learn how to customize a form control: https://ant.design/components/form/#components-form-demo-customized-form-controls
