### ISSUE TITLE
select 扩展元素我不想联动上面已经选中的

### ISSUE THREAD

**Issue by jinrichardJIN** [ant-design/ant-design#24251]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/qkc4d?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/qkc4d?file=/index.js

### What is expected?
在扩展的菜单里面回车或者删除，不要操作我上面已经选中的项

### What is actually happening?
在扩展的菜单里面回车或者删除，上面跟着一起联动

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | react |
| System | 000 |
| Browser | chrome |

**Comment by yoyo837** [comment]
https://codesandbox.io/s/kuozhancaidan-ant-design-demo-mmzlr?file=/index.js 这样试试

**Comment by yoyo837** [comment]
有问题再打开。
