### ISSUE TITLE
Callback for date rage

### ISSUE THREAD

**Issue by ZKMN** [ant-design/ant-design#24255]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
For example at now i need to call some callback when i click on X in date rage picker when dates was filled
https://ant.design/components/date-picker/#components-date-picker-demo-select-in-range.
And now the dates are cleared and there is no way to call some function after / during this.

### What does the proposed API look like?
I don't have example

**Comment by afc163** [comment]
`onChange`
