### ISSUE TITLE
Table中radio状态改变的问题

### ISSUE THREAD

**Issue by kunkkaliu** [ant-design/ant-design#2426]
Ant: 1.6.5
浏览器：Chrome
操作系统：Mac
render () {
const { selectedRows } = this.state;
        const rowSelection = {
            type: 'radio',
            selectedRows,
            onChange: this.onSelectChange,
        };
<Table columns={columns} rowSelection={rowSelection} dataSource={this.props.roles}  bordered></Table>
}

问题描述：table做了单选，选择一行，然后改变selectedRows为空数组，但是table中的radio还是处于选中状态。

**Comment by afc163** [comment]
selectedRowsKey 

没有 selectedRows 这个受控属性。

**Comment by kunkkaliu** [comment]
多谢。。回复的好及时 👍
