### ISSUE TITLE
Switch wrapped in tooltip causes error "cannot find property blur"

### ISSUE THREAD

**Issue by mtjn** [ant-design/ant-design#24262]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-ant-design-demo-fg7ik)

### Steps to reproduce
Click switch

### What is expected?
Switch toggles normally

### What is actually happening?
Clicking triggers "cannot read property blur of 'undefined'" error

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.12.0 |
| System | Ubuntu 20.04 |
| Browser | Chromium Version 81.0.4044.138 (Official Build) snap (64-bit) |

---
In my production app, this causes a console error and the page lags. JS heap increases to 180MB. In the minimal reproduction, the page crashes.

Perhaps related to https://github.com/ant-design/ant-design/issues/4853 ?

**Comment by hengkx** [comment]
ref #24254

**Comment by afc163** [comment]
可以发个 rc-switch@3.0.2 hot fix，不然要等周末。

**Comment by afc163** [comment]
It works well in my local envoironment, I think it is a codesandbox issue.

**Comment by mtjn** [comment]
The error also occurs for me in my production app on my local environment.

> In my production app, this causes a console error and the page lags. JS heap increases to 180MB. In the minimal reproduction, the page crashes.

**Comment by afc163** [comment]
@mtjn Could you provider a minimal git repo to reproduce?

**Comment by yoyo837** [comment]
https://codesandbox.io/s/basic-ant-design-demo-frqbx?file=/index.js

**Comment by yoyo837** [comment]
@afc163 Need a patch release for 3.0.1.

**Comment by yoyo837** [comment]
Please help to creating v.3.0.x branch in https://github.com/react-component/switch.

**Comment by afc163** [comment]
done: https://github.com/react-component/switch/tree/3.0.x

**Comment by yoyo837** [comment]
Pls remove `node_modules` and `package-lock.json or yarn.lock` file than reinstall it.

**Comment by mtjn** [comment]
> Pls remove `node_modules` and `package-lock.json or yarn.lock` file than reinstall it.

this fixed it, thank you.
