### ISSUE TITLE
RangePicker在某些默认时间设置下，start_time 和end_time选取同一个时间 onChange 事件第一个参数数组的第二个参数为undefined

### ISSUE THREAD

**Issue by facingcheer** [ant-design/ant-design#24265]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-surf-6w4et?file=/index.js)

### Steps to reproduce
在2个Rangepicker 中选择时间（start和end为同一时间）
查看控制台打印的onchange事件参数

### What is expected?
onChange 事件第一个参数数组2个值都为moment

### What is actually happening?
在某些默认时间设置下, onChange 事件第一个参数数组第二个为undefined

| Environment | Info |
|---|---|
| antd | 3.26.0 |
| React | 16 |
| System | mac |
| Browser | chrome 80 |

**Comment by yoyo837** [comment]
如何操作？哪些时机会出现这个问题？

**Comment by facingcheer** [comment]
> 如何操作？哪些时机会出现这个问题？

codesandbox的链接里面有2个RangePicker
这两个RangePicker在选择时间的时候都选择开始和结束相同的时间（比如第一个picker 开始结束都设置为2020-05-20 第二个picker开始结束都设置为2020-04-20
然后查看sandbox中控制台里打印的参数信息
![image](https://user-images.githubusercontent.com/5510657/82278830-ab4c6280-99bd-11ea-939e-1fe7164bc927.png)

**Comment by yoyo837** [comment]
奇怪噢，就第二个会，我看看...

**Comment by yoyo837** [comment]
ref: #17135 #17694

**Comment by yoyo837** [comment]
初始值 开始时间的时分秒小于结束时间的时分秒
（如1970-01-01 02:22:22 and 1970-01-02 01:11:11），
1.  通过交互选择为同一天时时分秒纠正为结束时间吗？
2. 还是当不是`showTime`时忽略比较大小？
3· `value`在不是`showTime`时直接抹掉时分秒再使用？

**Comment by yoyo837** [comment]
@mraiguo

**Comment by xiaoxiaoting** [comment]
和楼主遇到同一个问题

**Comment by Homingciu** [comment]
遇到同样问题！
![image](https://user-images.githubusercontent.com/26406656/89031171-951b3500-d364-11ea-89f4-7ea76578d23b.png)
我觉得就是抛出来的value的end < start然后被置为undefined

**Comment by xiaoxiaoting** [comment]
你可以做一个判断,我就是这样解决的，你可以试试，目前没发现有啥问题，已经很久了，忘记啥判断，好像是undefined情况就把数组重设一下，两个值都是第一个值。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Homingciu <notifications@github.com&gt;
发送时间: 2020年7月31日 19:34
收件人: ant-design/ant-design <ant-design@noreply.github.com&gt;
抄送: Crystal <1062764645@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design] RangePicker在某些默认时间设置下，start_time 和end_time选取同一个时间 onChange 事件第一个参数数组的第二个参数为undefined (#24265)





 
遇到同样问题！
 
 我觉得就是抛出来的value的end < start然后被置为undefined

**Comment by yoyo837** [comment]
@afc163  @zombieJ  这个问题我之前定位了，但是不知道应该采用什么方式修复，以至于一直搁置在这里。现在还改吗？

**Comment by Homingciu** [comment]
@xiaoxiaoting 我就是这样修复的，只不过我想让antd官方也修复

**Comment by zombieJ** [comment]
@yoyo837，v3 已经过了维护期了。比较担心修改会引发新的 bug，不过你可以试试，如果不 break 的话可以给 rc 发个 patch。

**Comment by yoyo837** [comment]
那我应该考虑使用 https://github.com/ant-design/ant-design/issues/24265#issuecomment-630555710 中的哪个方案来修改呢？

**Comment by zombieJ** [comment]
个人倾向于第一个

**Comment by Homingciu** [comment]
说实话，假如先选7月5号，再选7月4号，你们不是会将时间排序成[4号，5号]，这样子吗？为什么选同一天的时候不排序，然后再统一时间呢， 或者不排序直接统一好时间。根本就不应该触发value[0].diff(value[1]) > 0，这个条件，根据这个判断在正确情况下都是多余的

**Comment by yoyo837** [comment]
> 说实话，假如先选7月5号，再选7月4号，你们不是会将时间排序成[4号，5号]，这样子吗？为什么选同一天的时候不排序，然后再统一时间呢， 或者不排序直接统一好时间。根本就不应该触发value[0].diff(value[1]) > 0，这个条件，感觉这个判断在正确情况下都是多余的

并不存在你说的能先选5号再选4号然后自动调换吧

**Comment by Homingciu** [comment]
那好吧，那我觉得你还是加一下根据showTime来判断吧

**Comment by Homingciu** [comment]
> > 说实话，假如先选7月5号，再选7月4号，你们不是会将时间排序成[4号，5号]，这样子吗？为什么选同一天的时候不排序，然后再统一时间呢， 或者不排序直接统一好时间。根本就不应该触发value[0].diff(value[1]) > 0，这个条件，感觉这个判断在正确情况下都是多余的
> 
> 并不存在你说的能先选5号再选4号然后自动调换吧

那好吧，那我觉得你还是加一下根据showTime来判断吧

**Comment by yoyo837** [comment]
不修了吗？我那个PR下午提交了test case
