### ISSUE TITLE
antd form 自定义组件 Input 组件，用 1password 自动填充后失去焦点后丢失 value

### ISSUE THREAD

**Issue by elevensky** [ant-design/ant-design#24261]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-darwin-gyexe?file=/index.js)

### Steps to reproduce
使用 1password 自动填充后，鼠标点击页面空白处。

### What is expected?
密码保留

### What is actually happening?
密码自动清空

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | latest |
| System | macos |
| Browser | chrome |

---
正常键盘输入无问题。
自定义表单组件InputPassword中，document.addEventListener("keyup", this.handleKeyEvent);去掉监听事件改变state的情况是好的。
怎么避免这种情况？

**Comment by zombieJ** [comment]
全局添加事件非常的不 React，推测是相互作用的问题。本身和 antd 无关，建议去掉全局事件在尝试。如果还有问题，可以给 1password 提 issue。

**Comment by elevensky** [comment]
@zombieJ 
React.Component 自定义组件时，1password自动填充触发的事件打印流如下图：
![image](https://user-images.githubusercontent.com/6904834/82400432-def4be80-9a89-11ea-90ea-801ec45696cd.png)
感觉是，document EventListener里的setState造成了组件的重渲，不断丢弃原Input实例造成的问题。和1password也没啥关系。
