### ISSUE TITLE
Inside Automatic tokenization, hovering on tags doesn't show tooltip showing the full text when the text of tag is too long a

### ISSUE THREAD

**Issue by deepseafishing** [ant-design/ant-design#24268]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-cfoyj?file=/index.js)

### Steps to reproduce
Write a long text that's overflow the width of the select bar

### What is expected?
When I hover over a tag generated in that select bar, it should give me a tooltip that shows the whole text just as same as any tags in ant design.

### What is actually happening?
It doesn't show you anything.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12.0 |
| System | Mac OS Catalina |
| Browser | Chrome |

---
I don't know this was bug report or feature recommendation.

**Comment by zombieJ** [comment]
Select support `tagRender` to customize the selector item. You can wrap with additional tooltip: https://codesandbox.io/s/antd-reproduction-template-2q67v?file=/index.js

**Comment by deepseafishing** [comment]
works perfectly thanks!

**Comment by afc163** [comment]
We should add default `title` to select tag.
