### ISSUE TITLE
Empty in components are not identical

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24276]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/empty-cn/#components-empty-demo-config-provider](https://ant.design/components/empty-cn/#components-empty-demo-config-provider)

### What place?
- Cascader class is `ant-cascader-menu-item-disabled`, not other `ant-xx-empty`, so the cursor show different.
- When customize. 
  - Color in **(Select、TreeSelect、Table)** is `rgba(0,0,0,.65)`
  - Color in **(Cascader、Transfer、List)** is `rgba(0,0,0,.25)`

**Comment by afc163** [comment]
看上去颜色没问题，我这里看到的都是 `.25`。

<img width="478" alt="image" src="https://user-images.githubusercontent.com/507615/82291537-bdd59480-99db-11ea-8cb3-0ff107c5d3bc.png">

<img width="278" alt="image" src="https://user-images.githubusercontent.com/507615/82291544-c1691b80-99db-11ea-867e-5b52ef6f989a.png">

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/82293137-a8ae3500-99de-11ea-9fc1-44db8ad2dc38.png)
