### ISSUE TITLE
How to make the fixed column height  fit the extended row?

### ISSUE THREAD

**Issue by ChenYCL** [ant-design/ant-design#24277]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### preview
![image](https://user-images.githubusercontent.com/25706676/82283531-d5535400-99c0-11ea-8400-4a97d205e498.png)

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-leakey-g6x7m?file=/index.js)

### Steps to reproduce
click the expand icon ,the fixed column not auto fit the table

### What is expected?
auto fit the expand row's height

### What is actually happening?
fixed column not fit height  when expanded content show, the content is Multi-row

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | 16.13 |
| System | window10 |
| Browser | Chrome Version 81.0.4044.138 |

**Comment by afc163** [comment]
It is been resolved in antd v4, try it.

There is nothing we can do in v3 now.
