### ISSUE TITLE
Select下拉框可输入，加上font-size后下拉框抖动

### ISSUE THREAD

**Issue by wananle** [ant-design/ant-design#24270]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sousuokuang-ant-design-demo-4frxt?file=/index.js)

### Steps to reproduce
给下拉框设置font-size下拉框输入就会抖动

### What is expected?
设置font-size下拉框不会抖动

### What is actually happening?
下拉框会抖动

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.12.0 |
| System | win10 |
| Browser | Google |

**Comment by xrkffgg** [comment]
在你的 font-size 下面 加一个

`position: absolute` 看看

**Comment by wananle** [comment]
> 在你的 font-size 下面 加一个
> 
> `position: absolute` 看看

加上我界面上的样式就变了

**Comment by xrkffgg** [comment]
`line-height: 30px`

**Comment by zombieJ** [comment]
有输入和非输入用的不同方式对齐，我看看有木有办法优化一下。

**Comment by zombieJ** [comment]
看了一下没啥可以额外做的，参考 @xrkffgg 的建议给元素设置固定 `line-height`。

**Comment by wananle** [comment]
> 看了一下没啥可以额外做的，参考 @xrkffgg 的建议给元素设置固定 `line-height`。

好的

**Comment by wananle** [comment]
> `line-height: 30px`

可以了，谢谢
