### ISSUE TITLE
formRef.current.setFieldsValue异常问题

### ISSUE THREAD

**Issue by Loren-Wang** [ant-design/ant-design#24288]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com   未上线项目，暂时无法重现](http://www.baidu.com   未上线项目，暂时无法重现)

### Steps to reproduce
通过formRef.current.setFieldsValue设置一个数据
{
  "data":{
     "zh":"xxxxxxxx",
     "en":"zzzzzzzz"
  },
  "rank":1,
  "status":1
}

 在初始情况下是ok的，但是在后续调用该方法设置数据为
{
  "data":{
     "zh":"aaaaaa",
     "en":"zzzzzzzz"
  }}
时，实际的结果数据变成了
{
  "data":"aaaaaa",
  "rank":1,
  "status":1
}

### What is expected?
{
  "data":{
     "zh":"aaaaaa",
     "en":"zzzzzzzz"
  },
  "rank":1,
  "status":1
}

### What is actually happening?
{
  "data":"aaaaaa",
  "rank":1,
  "status":1
}

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | mac 10.15.4 |
| Browser | Chrome 81.0.4044.138 |

---
在form表单内部的其中一个item是多个输入框进行输入数据，多个输入框中有联动输入变更也有独立的输入框，所有的输入框都使用的state进行数据管理，在输入框内容变更后使用formRef.current.setFieldsValue更新form内的数据

**Comment by yoyo837** [comment]
请使用 https://u.ant.design/codesandbox-repro 复现

**Comment by Loren-Wang** [comment]
https://codesandbox.io/s/antd-reproduction-template-4en73?file=/index.js

**Comment by yoyo837** [comment]
操作步骤是怎样的？

**Comment by yoyo837** [comment]
你这写的太复杂了，而且是你自己的逻辑造成的data / title 复写掉了

**Comment by yoyo837** [comment]
你的title只和当前 zh 或者 en 中的一个直接绑定就好了，zh 或者 en本身处理自己的rules校验，不用专门为title当作一个字段处理

**Comment by yoyo837** [comment]
你的demo需要精简，且修正表单设置值的错误逻辑，这里是一个参考代码：

https://codesandbox.io/s/antd-reproduction-template-xt0jj?file=/LanguageText.js

**Comment by Loren-Wang** [comment]
你的逻辑并不是我想要的，我这边的业务场景是一个接口返回title、childTitle等多语言对象，每个对象内部都是包含了zh、en等语言对象，然后是要同时编辑，所以这就需要有多个form-item标签内部再包含多个form-item标签然后再处理，而不是通过states判断去输入哪个语言，不过最后问题我也确定了，是最外层form-item标签的name导致了title的重写，因为setfields先于setstate执行，所以在修改title之后又被form-item内部的input标签修改后再赋值导致异常，就是你说的被复写是吧！

在这里先谢谢你之前的解释、说明，不过想给你们提一个小小的建议，希望你们后面能加上这种多层级数据的输入以及修改功能，谢谢！！！

**Comment by yoyo837** [comment]
使用`setFieldsValue`修改数据时记得保持原有的结构就没问题。

```js
{
  title: {
    zh: 123,
    en: 456
  }
  status: 1
}
```

要修改zh的时候不要错误的修改title就可以了。_

**Comment by xiaoyc-9364** [comment]
> 使用`setFieldsValue`修改数据时记得保持原有的结构就没问题。
> 
> ```js
> {
>   title: {
>     zh: 123,
>     en: 456
>   }
>   status: 1
> }
> ```
> 
> 要修改zh的时候不要错误的修改title就可以了。_

现在是不支持setFieldsValue({xxx.xxx.xxx: xxx}这种格式了吗

**Comment by yoyo837** [comment]
有任何问题请随时提供复现打开一个issue.
