### ISSUE TITLE
This relative module was not found: ../plugin-dva/connect in ./src/.umi/core/umiExports.ts

### ISSUE THREAD

**Issue by sunshinev** [ant-design/ant-design#24289]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pro.ant.design/docs/getting-started-cn](https://pro.ant.design/docs/getting-started-cn)

### Steps to reproduce

yarn create umi ant
npm install
npm start

### What is expected?
run successful

### What is actually happening?

```
➜  ant-design-pro npm start

> ant-design-pro@4.0.0 start /www/jaysun/test/ant-design-pro
> umi dev

🚀 Starting Umi UI using umi@3.2.0...
🌈 Umi UI mini Ready on port 3000.
Starting the development server...

✖ Webpack
  Compiled with some errors in 40.33s

 ERROR  Failed to compile with 1 errors                                                                       下午4:50:16

This relative module was not found:

* ../plugin-dva/connect in ./src/.umi/core/umiExports.ts
```

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | osx |
| Browser | chrome |

**Comment by afc163** [comment]
It is not a antd issue.
