### ISSUE TITLE
New Tabs design

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#24284]
![1585303746817-bc60e582-0ef6-45ea-8d23-42b2c44ec5e8](https://user-images.githubusercontent.com/5378891/82293827-c203b100-99df-11ea-8ac9-0db5baf6c4e8.png)

Do not modify `rc-tabs` since this will rewrite with new design and update for accessibility control.

**Comment by zombieJ** [comment]
cc @hengkx，`rc-tabs` 不用重写成 hooks 哈~

**Comment by hengkx** [comment]
ok

**Comment by afc163** [comment]
不滚动了么。

**Comment by zombieJ** [comment]
嗯，没有滚动了。

**Comment by yoyo837** [comment]
移动端就不那么友好了，是否可以参数控制一下能任然滚动的方式？成本应该不大。

**Comment by zombieJ** [comment]
> 移动端就不那么友好了，是否可以参数控制一下能任然滚动的方式？成本应该不大。

两者布局方式完全不同，我看看有没有简单的方式来实现。

**Comment by afc163** [comment]
现在的移动端也不好，最好改造完移动端能适配成 [TabBarSwipeableTabs](https://github.com/react-component/tabs/blob/master/src/TabBarSwipeableTabs.js) 支持用手指左右拖动。

**Comment by zombieJ** [comment]
感谢反馈，我和设计师同步一下。

**Comment by zombieJ** [comment]
汗，Dropdown 没有 Accessibility…… 我去跟一下

ref https://github.com/ant-design/ant-design/issues/24173

**Comment by zombieJ** [comment]
汗 v2，Menu 也没有 Accessibility…… 改造链路略长……

**Comment by afc163** [comment]
#19015

**Comment by afc163** [comment]
#24181

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/18940

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/8576

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19961

**Comment by chenxichaodb** [comment]
Hi, 请问现在antd有对menu的无障碍改造的计划吗？或者只需要让cascader元素，在用键盘操作的同时让被选中的选项一直显示这个特性。这个特性改动只需要在[menu这里](https://github.com/react-component/cascader/blob/8dc3510c8b6427d2bc2960895441f97818fdd51c/src/Menus.tsx#L47) 加入 `|| prevProps.activeValue !== this.props.activeValue` 的判断，同时提供一个选项是否开关这个功能。

**Comment by afc163** [comment]
@chenxichaodb 欢迎来 PR
