### ISSUE TITLE
Drawer在在底部无遮罩时关闭问题

### ISSUE THREAD

**Issue by ShangTX** [ant-design/ant-design#24287]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)]

https://codesandbox.io/s/clever-waterfall-7o3m6?file=/src/App.js

### Steps to reproduce
关闭Drawer可见

### What is expected?
关闭后Drawer不再占据开启时的空间

### What is actually happening?
关闭后仅视觉上消失了，仍然遮盖原来的位置，无法操作

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome 78.0.3904.108 |

**Comment by CHU295** [comment]
同样的问题，希望早点fix

**Comment by yoyo837** [comment]
已修复，下个发布可用
