### ISSUE TITLE
全局配置中文后，RangePicker的月份和星期依旧是中文

### ISSUE THREAD

**Issue by MaZhengA** [ant-design/ant-design#24286]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pics.images.ac.cn/image/5ec38ecb1234a.html](https://pics.images.ac.cn/image/5ec38ecb1234a.html)

### Steps to reproduce
按照官网设置完之后，RangePicker不起作用

### What is expected?
期望月和星期也变成中文

### What is actually happening?
依旧是英文

| Environment | Info |
|---|---|
| antd | 3.16.4 |
| React | ^16.12.0 |
| System | 10.15.3 |
| Browser | Google Chrome81.0.4044.138 |

**Comment by yoyo837** [comment]
https://ant.design/components/config-provider-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%88%91%E4%BD%BF%E7%94%A8%E4%BA%86-ConfigProvider-locale%EF%BC%8C%E6%97%B6%E9%97%B4%E7%B1%BB%E7%BB%84%E4%BB%B6%E7%9A%84%E5%9B%BD%E9%99%85%E5%8C%96%E8%BF%98%E6%9C%89%E9%97%AE%E9%A2%98%EF%BC%9F

**Comment by sporteveryday** [comment]
我今天升级到最新也出现了同样的问题

**Comment by yoyo837** [comment]
请提供一个在线demo 复现

**Comment by sporteveryday** [comment]
> 请提供一个在线demo 复现

已解决，回溯到旧版本再更新到4.2.4，全局设置中文，解决问题，没有复现中英文混合的情况

**Comment by xue1206** [comment]
antd依赖moment@~2.25.3
rc-picker依赖moment@^2.24.0
是不是这个原因导致的， 我也出现了这个情况

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/82630948-d2f23380-9c26-11ea-8e5c-ed41411b2c3e.png)

npm 用的 `^`

**Comment by afc163** [comment]
antd 已经改了，本周会发布版本。#24322
