### ISSUE TITLE
table scroll y 是否可以考虑从height改为max-height？

### ISSUE THREAD

**Issue by yexingxia** [ant-design/ant-design#2428]
#### 本地环境

- antd 版本: 1.6.4
- 操作系统及其版本：windows7 x64
- 浏览器及其版本:  chrome

#### 你做了什么？

引入table组件，设置了scroll={y: xxx}

#### 你期待的结果是：

table的max-height是y值，当数据比较少高度不足y值时，table能够自适应高度

#### 实际上的结果：

table的height是y值，当数据比较少高度不足y值时，table下面出现空白

#### 可重现的在线演示

http://codepen.io/wmf/pen/jAkzXN?editors=001

**Comment by afc163** [comment]
https://github.com/react-component/table/issues/65

**Comment by yexingxia** [comment]
是否可以更新下antd的package.json里面rc-table的版本号呢？现在的版本号设置我没法更新到4.4.0

**Comment by afc163** [comment]
等下个版本，别着急。:santa:

https://github.com/ant-design/ant-design/wiki/%E8%BD%AE%E5%80%BC%E8%A7%84%E5%88%99%E5%92%8C%E7%89%88%E6%9C%AC%E5%8F%91%E5%B8%83%E6%B5%81%E7%A8%8B#%E5%8F%91%E5%B8%83%E8%BD%AE%E5%80%BC%E8%A7%84%E5%88%99
