### ISSUE TITLE
TreeSelect 与 Form 结合使用的问题

### ISSUE THREAD

**Issue by MinJieLiu** [ant-design/ant-design#24294]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TreeSelect 与 Form 结合使用方便取值

### What does the proposed API look like?
TreeSelect 中 TreeNode 的 value 是全局唯一，若与 Form 结合使用，假设取值为 title（title 不全局唯一）该如何优雅实现？
本身 TreeNode 中已经包含了 id，id 应不唯一。若我把 title 放在 value 字段上就会 warning

**Comment by zombieJ** [comment]
没明白，给个重现看看。

**Comment by MinJieLiu** [comment]
https://ant.design/components/tree-select-cn/#TreeNode-props

![image](https://user-images.githubusercontent.com/6167727/82329265-9c909a80-9a13-11ea-9e99-6d25e6c31352.png)

我的意思是 结合 Form.Item 使用，这里的 value 我可以设置成不唯一的值吗（因为 key 已经唯一了）

或者有什么办法在 Form 上不取 value。valuePropName 若设置成 title ？

**Comment by zombieJ** [comment]
不行，必须唯一。这个是 TreeSelect 的基本规定。

**Comment by MinJieLiu** [comment]
Form 表单所获取的值不就是 value 吗

**Comment by zombieJ** [comment]
1. Form.Item 可以配置从事件获取值的逻辑，默认是 event.target.value or value。
2. TreeSelect 的选项 value 必须唯一，这和 Form 本身没有关系。你设置成 title 就不是 TreeSelect 的 value，就需要自己通过自定义组件形式封装 TreeSelect。

**Comment by MinJieLiu** [comment]
理解，自己封装一下。
