### ISSUE TITLE
什么时候支持React 0.14.x 来着？

### ISSUE THREAD

**Issue by okoala** [ant-design/ant-design#243]
rt~

**Comment by afc163** [comment]
等正式发布了再说吧。

**Comment by demohi** [comment]
react@0.14.0-rc1以及发布  可以开始支持了~

**Comment by afc163** [comment]
https://github.com/facebook/react/pull/4797

**Comment by benjycui** [comment]
react@0.14.0 已经发布 https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by afc163** [comment]
可以列下修改点和需要修改的 react-component 组件。

**Comment by kazaff** [comment]
同问

**Comment by benjycui** [comment]
要不先把 https://github.com/ant-design/ant-design/pull/369 pick 到 master?  ping @afc163

**Comment by afc163** [comment]
先把 develop 搞成 0.14 吧，目前接入 https://github.com/react-component/queue-anim 会报错。

**Comment by afc163** [comment]
已经把 #369 放到 master 上了。

**Comment by afc163** [comment]
wait: https://github.com/react-component/dialog/pull/12

**Comment by afc163** [comment]
https://github.com/react-component/menu 还没升。

**Comment by benjycui** [comment]
@afc163 等 merge

https://github.com/react-component/notification/pull/5

https://github.com/react-component/menu/pull/16

另外，略好奇，怎么我 `grep` 不出来。在 ant-design 目录下运行这行命令 `grep -r 'deprecated API' $(ls node_modules/rc-* | grep 'rc-' | cut -d ':' -f 1) | grep -v '/node_modules/'` 应该可以把依赖的 rc 中使用到 deprecated API 的代码到 `grep` 出来的。

**Comment by afc163** [comment]
`React.findDOMNode` 会编译为类似于 `_react2['default'].findDOMNode`。

**Comment by benjycui** [comment]
试过了，也是不行。。。
