### ISSUE TITLE
希望Avatar组件支持draggable属性

### ISSUE THREAD

**Issue by zhangyu1818** [ant-design/ant-design#24305]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Avatar组件放在一个可在页面拖动的div里，但是图片默认在html中是draggable的，所以导致本想拖动div，结果把图片给拖出来了

如果支持给Avatar组件中的img标签添加draggable属性，就可以解决这个问题

### What does the proposed API look like?
```jsx
<Avatar draggable="false" src={user.avatar} />
```

**Comment by afc163** [comment]
这个属性透传到 img 标签上就行，来个 PR 吧。

**Comment by zhangyu1818** [comment]
> 这个属性透传到 img 标签上就行，来个 PR 吧。

我提了一个PR，不是很搞得懂流程Orz……
