### ISSUE TITLE
findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Menu which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

### ISSUE THREAD

**Issue by jiankafei** [ant-design/ant-design#24307]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](http://www.example.com?des=无法提供链接因为无法打开codesandbox.io创建示例)

### Steps to reproduce
开启严格模式，使用 Menu 组件

### What is expected?
移除 findDOMNode，改用 ref

### What is actually happening?
严格模式下 Menu 使用 findDOMNode 报错

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
Duplicated of #22493
