### ISSUE TITLE
Can't set less variable from webpack 

### ISSUE THREAD

**Issue by Seresigo** [ant-design/ant-design#24300]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/webpack-config-l2l4g?file=/src/app.jsx)

### Steps to reproduce
```
// webpack.config.js
module.exports = {
  rules: [{
    test: /\.less$/,
    use: [{
      loader: 'style-loader',
    }, {
      loader: 'css-loader', // translates CSS into CommonJS
    }, {
      loader: 'less-loader', // compiles Less to CSS
     options: {
       lessOptions: { // If you are using less-loader@5 please spread the lessOptions to options directly
         modifyVars: {
           'grid-gutter-width':'12px'
         },
         javascriptEnabled: true,
       },
     },
    }],
    // ...other rules
  }],
  // ...other config
}
```

### What is expected?
Grid column padding will be 6px

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | Mac OS Latest |
| Browser | 81.0.4044.138 |

**Comment by yoyo837** [comment]
It looks like an unused variable, we should remove it.

**Comment by Seresigo** [comment]
@yoyo837 And how to set default gutter for whole project now?
In version 3 it's work fine

**Comment by yoyo837** [comment]
Yes, it works in v3. It was removed in 4.0. There seems to be no way to set it to global. 

@afc163 @zombieJ Need to implement it again?

**Comment by Statfine** [comment]
"less": "3.10.3",
 "less-loader": "5.0.0",
is OK?

**Comment by Seresigo** [comment]
This link is template from web, it doesn't depend on less version)

**Comment by Seresigo** [comment]
Same problem with setting custom breakpoints such as `@screen-xs` and others
Need to reopen this issue 🤔
@afc163 any help?

**Comment by ovidius72** [comment]
I need to set custom breakpoints. Is there any update on this. ?
