### ISSUE TITLE
DatePicker.RangePicker jumps like crazy when selecting dates

### ISSUE THREAD

**Issue by rpmonteiro** [ant-design/ant-design#24309]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-go87h)

### Steps to reproduce
Try to select a date range a few months in the future.
If you select a date on the right side of the picker, the whole thing jumps back to today, and the user is completely lost.

### What is expected?
Keep the picker in the same position like in antd 3.x

### What is actually happening?
If you select a date on the right side of the picker, the whole thing jumps back to today, and the user is completely lost.
As it stands, this component is completely unusable.

![gif1](https://user-images.githubusercontent.com/7824615/82409081-3fc1ce00-9a6d-11ea-95a9-4e6cad8a7932.gif)
![gif2](https://user-images.githubusercontent.com/7824615/82409085-40f2fb00-9a6d-11ea-8554-ffd4471c726a.gif)

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | Mac |
| Browser | Chrome latest |

**Comment by morenyang** [comment]
fixed in https://github.com/react-component/picker/pull/21

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15653996/82719345-4013d080-9cdc-11ea-91c4-4dae598caaaa.gif)

**Comment by afc163** [comment]
Wait for `4.3.0` to close.

**Comment by boi87** [comment]
This is happening for me now, on a `<DatePicker>` and not RangePicker.

"antd": `"^5.3.3"`,
"react": "^18.2.0", 

Clicking on the date picker would make the date jump like crazy till year 3000+.

Before click:

<img width="179" alt="image" src="https://user-images.githubusercontent.com/25410752/236246309-00380e20-d426-463c-90fe-60b45b0f7e9b.png">

After a couple of clicks:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/25410752/236246638-6b78a16f-950b-4706-b974-92d6cbedf537.png">


I've noticed that if I delete the date (via X button in the date picker), the dates will no longer appear as all selected. But still, moving your mouse inside the calendar will make dates go crazy.

![date picker 1](https://user-images.githubusercontent.com/25410752/236250371-ce0e1d97-75ca-4f81-9a43-6d0dbe33b385.gif)

**Comment by yoyo837** [comment]
@boi87 Please open a new issue for that.

**Comment by TrungLeThanh** [comment]
@boi87 Using dayjs instead of moment will help resolve the issue.

**Comment by Adharsraj** [comment]
@TrungLeThanh lifesaver
