### ISSUE TITLE
getValueProps 获取值慢一步吗？

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#24306]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dumi-demo-bwc38?file=/demo.tsx)

### Steps to reproduce
点击 获取提交前数据 按钮

### What is expected?
打印出 2020-05-20 日期

### What is actually happening?
打印出 1970-01-19

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | latest |
| System | mac |
| Browser | chrome |

---
不应该是接口返回时间戳，在 datePicker 获取的时候格式化成 moment 吗？

**Comment by yoyo837** [comment]
把 `yforms` 去掉做一个复现吧，yforms的逻辑看不见也和antd无关。

**Comment by crazyair** [comment]
> 把 `yforms` 去掉做一个复现吧，yforms的逻辑看不见也和antd无关。

https://codesandbox.io/s/jibenshiyong-ant-design-demo-hxe2q?file=/index.js

**Comment by yoyo837** [comment]
供参考 ：https://codesandbox.io/s/jibenshiyong-ant-design-demo-5edcz?file=/index.js

应该是moment用法有关。

**Comment by crazyair** [comment]
> 供参考 ：https://codesandbox.io/s/jibenshiyong-ant-design-demo-5edcz?file=/index.js
> 
> 应该是moment用法有关。

哎呀，我这是举个例子，input 等其他的都是一样效果。。。。。。。

**Comment by crazyair** [comment]
例子中时间戳是少了3位，但说的不是这个问题啊。

**Comment by crazyair** [comment]
更新了 demo
![image](https://user-images.githubusercontent.com/7971419/82403776-3d259f80-9a92-11ea-9360-a0118a0737b9.png)

初始化为 `a` 表单显示为 `b` 但是提交的值还是 'a'

**Comment by yoyo837** [comment]
被谁重置了吧？重新给个没有`yforms `的demo?

**Comment by crazyair** [comment]
> 被谁重置了吧？重新给个没有`yforms `的demo?

https://codesandbox.io/s/jibenshiyong-ant-design-demo-hxe2q?file=/index.js

**Comment by yoyo837** [comment]
https://codesandbox.io/s/jibenshiyong-ant-design-demo-b2nyb?file=/index.js 啥问题呢？

**Comment by crazyair** [comment]
> https://codesandbox.io/s/jibenshiyong-ant-design-demo-b2nyb?file=/index.js 啥问题呢？

初始化为 a 表单显示为 b 但是提交的值还是 'a'

**Comment by yoyo837** [comment]
你看错了吧, moment对象里展开有个_i 是初始值的引用吧，那个不是实际值！

**Comment by crazyair** [comment]
忽略 date 字段看 demo 字段

**Comment by yoyo837** [comment]
你的demo里的b 是你自己写死的，你看看我demo里`Success`的输出

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/82404412-d2756380-9a93-11ea-968e-12d5d801c58e.png)

**Comment by crazyair** [comment]
这里写死 `b`，应该 success 输出也为 `b` 的

**Comment by yoyo837** [comment]
看懂了

**Comment by crazyair** [comment]
我发现我真的不会沟通。

**Comment by yoyo837** [comment]
复现： https://codesandbox.io/s/jibenshiyong-ant-design-demo-pf72u?file=/index.js

**Comment by yoyo837** [comment]
@zombieJ 初始时`getValueProps`不起作用是预期行为吗？用户交互后Input和DatePicker还不一样的效果Input始终输出修改值，DatePicker保留`getValueProps`的值。

**Comment by zombieJ** [comment]
`getValueProps` 就是把表单的值转换成 Form.Item 的属性，例子中相当于无视 Form instance 的任何值直接给 Form.Item 设置了 value：
```tsx
getValueProps={v => ({ value: "b" })}

// 等同于：
<Input value="b" />
```

从组件 `onChange` 获取值是 `getValueFromEvent`。


<img width="678" alt="截屏2020-05-20 下午3 30 58" src="https://user-images.githubusercontent.com/5378891/82417945-e8dce880-9aae-11ea-853a-691f4d0c5051.png">

**Comment by crazyair** [comment]
还是没理解。哎。。。。

**Comment by crazyair** [comment]
如果 getValueProps 只是为了拿到 value 给 Input 添加比如 value 、addonAfter 等属性，那确实看错了这个 api 了。
这个 issue 要讨论的是，initialValues 中 date 是时间戳，那 DatePicker 拿到前需要转换为 moment。一开始以为 getValueProps 是干这个事的，想多了。

**Comment by yoyo837** [comment]
那意思就是即使`<Input value="b" />` 直接放到Form、Form.Item里，也和当前现象一样，显示不变但表单值变。是不是这个时候表单值也一起锁定合理一些 ， 很好奇这功能啥时候会用到。“影子值”？

**Comment by zombieJ** [comment]
> 如果 getValueProps 只是为了拿到 value 给 Input 添加比如 value 、addonAfter 等属性，那确实看错了这个 api 了。
> 这个 issue 要讨论的是，initialValues 中 date 是时间戳，那 DatePicker 拿到前需要转换为 moment。一开始以为 getValueProps 是干这个事的，想多了。

`getValueProps` 可以用的，你的重现里转的时间就是这个值：
https://codesandbox.io/s/jibenshiyong-ant-design-demo-hxe2q?file=/index.js

<img width="281" alt="截屏2020-05-20 下午4 05 28" src="https://user-images.githubusercontent.com/5378891/82421591-ce593e00-9ab3-11ea-9116-52e27e0f8060.png">

**Comment by zombieJ** [comment]
另外，转过去给 Form.Item 还需要用 getValueFromEvent 转回来交个 Form instance。

**Comment by crazyair** [comment]
`getValueProps ` 这个 api 有什么意义？
- value 可以直接用 valuePropName 
- 其它可以直接写到 children dom 中

**Comment by zombieJ** [comment]
你的场景就是例子，form instance 只保留 timestamp 而不用 moment 对象。组件的 value 是一个 moment 对象，通过 `getValueProps` 和 `getValueFromEvent` 做中间转换。

**Comment by crazyair** [comment]
但是第一次没转，差距大了。

**Comment by zombieJ** [comment]
没转指的是？这个 issue 里的例子有点多了。
直接贴个新的 codesandbox 重新描述一下输入，和预期输出吧~

**Comment by yoyo837** [comment]
上面我发的最新的那个

**Comment by crazyair** [comment]
不管 codesendbox 了，我理下需求吧！
1. 比方表单 date 字段，接口返回的是时间戳。
2. 不希望在 initialValues 中把 date 改成 moment 格式。（有时候字段嵌套深、拆分文件等，在 initialValues 统一处理有点不好维护）
3. 那就需要在 Form.Item 中添加一个参数，可以控制 initialValues.date 在到达 DatePicker 时候已经是 moment 格式了。当 date onChange 可以不用再执行该方法。
4. 表单提交时候可以在 Form.Item 中再添加一个参数，可以控制 submit 时候再转成时间戳（当然这个是 plus 功能，可以考虑是否支持，反正我的 yforms 已经支持了。）

**Comment by zombieJ** [comment]
这不就是 `getValueProps` 和 `getValueFromEvent` 做的事情吗？

另外，我最早的说明就是解释你的 reproduce 的 @yoyo837

**Comment by crazyair** [comment]
你确定能实现？

**Comment by zombieJ** [comment]
所以才说给一个最新的 reproduce 让我看看是我哪里理解有问题哈~

**Comment by crazyair** [comment]
https://codesandbox.io/s/jibenshiyong-ant-design-demo-hxe2q?file=/index.js
![image](https://user-images.githubusercontent.com/7971419/82429383-5fcdad80-9abe-11ea-8dbe-0a7397df771c.png)
点击提交想要得到`{demo: "b", date: Moment}`

**Comment by zombieJ** [comment]
知道 gap 在哪儿了，数据是双向的：
`Form instance`  <-> `Form.Item > Component`

* 设置 `getValueProps` 是 `Form instance`  -> `Form.Item > Component`
* 设置 `getValueFromEvent` 是 `Form.Item > Component`  -> `Form instance`

你的 reproduce 里通过 `getValueProps` 修改了展示的值，但是对于 Form instance 而言，它存的还是 `initialValues`。你应该修改 `initialValues` 而不是只是改掉传递给元素的值。

**Comment by crazyair** [comment]
![image](https://user-images.githubusercontent.com/7971419/82430350-c99a8700-9abf-11ea-8883-245eb0c1a3ab.png)

**Comment by crazyair** [comment]
要的是多一次`渲染`

**Comment by zombieJ** [comment]
Form.Item 本身也有 `initialValue`……

**Comment by zombieJ** [comment]
另外一点，`initialValues` 不用改 moment 格式，你写 timestamp 然 Form.Item 通过 `getValueProps` 转成 moment 给 Form.Item 下的 Component。就是你的例子呀。

**Comment by crazyair** [comment]
你这跑题了啊，这个`initIalValue` 能拿到 date 的值吗？API 要做成方法才合理把？
`(values)=> moment`

**Comment by yoyo837** [comment]
> 另外一点，`initialValues` 不用改 moment 格式，你写 timestamp 然 Form.Item 通过 `getValueProps` 转成 moment 给 Form.Item 下的 Component。就是你的例子呀。

实际情况是不操作表单项直接提交得不到moment。

**Comment by zombieJ** [comment]
我写一下例子，看看是不是你的意思。稍等。

**Comment by yoyo837** [comment]
@crazyair 你这个有点接近完全受控表单的样子了，但是实际并不支持受控的表单。

**Comment by crazyair** [comment]
> 另外一点，`initialValues` 不用改 moment 格式，你写 timestamp 然 Form.Item 通过 `getValueProps` 转成 moment 给 Form.Item 下的 Component。就是你的例子呀。

要的是绝对的修改，你这个不太好，就上面写死的例子表单中看的是 b 提交确是 a 不太好。

**Comment by crazyair** [comment]
> @crazyair 你这个有点接近完全受控表单的样子了，但是实际并不支持受控的表单。

知道 getValueProps 的定义了，现在讨论的是另外的问题了，不用 getValueProps 这个 API ！

**Comment by zombieJ** [comment]
Update：https://codesandbox.io/s/jibenshiyong-ant-design-demo-2z01g?file=/index.js

**Comment by crazyair** [comment]
> Update：https://codesandbox.io/s/jibenshiyong-ant-design-demo-2z01g?file=/index.js

你这个就是刚才说的不太好，我想要第一次提交的结果是 date: Moment 是没法办到的，现在问题就在这。

**Comment by zombieJ** [comment]
> 要的是绝对的修改，你这个不太好，就上面写死的例子表单中看的是 b 提交确是 a 不太好。

双向绑定通过 `getValueProps` 修改了单向数据，另一边也需要配合的做。

**Comment by yoyo837** [comment]
如果 getValueProps 写死一个值，目前的表现算bug吗？https://codesandbox.io/s/jibenshiyong-ant-design-demo-rylpx?file=/index.js:804-817

**Comment by zombieJ** [comment]
> > Update：https://codesandbox.io/s/jibenshiyong-ant-design-demo-2z01g?file=/index.js
> 
> 你这个就是刚才说的不太好，我想要第一次提交的结果是 date: Moment 是没法办到的，现在问题就在这。

意思是你初始化给的是 timestamp，但是希望之后拿到的都是 moment？

**Comment by zombieJ** [comment]
> 如果 getValueProps 写死一个值，目前的表现算bug吗？
> https://codesandbox.io/s/jibenshiyong-ant-design-demo-rylpx?file=/index.js:804-817

不是 bug，Form.Item 忠实的接收你提供的 value 传递给了 Component。这是预期行为。

**Comment by crazyair** [comment]
> > > Update：https://codesandbox.io/s/jibenshiyong-ant-design-demo-2z01g?file=/index.js
> 
> > 
> 
> > 你这个就是刚才说的不太好，我想要第一次提交的结果是 date: Moment 是没法办到的，现在问题就在这。
> 
> 
> 
> 意思是你初始化给的是 timestamp，但是希望之后拿到的都是 moment？

对，就是要绝对的修改。只需要一次setFieldValue 就可以

**Comment by yoyo837** [comment]
那其实我一直错误的理解 getValueProps 是双向的效果等于 getValueProps + getValueFromEvent。

**Comment by zombieJ** [comment]
> 对，就是要绝对的修改。只需要一次setFieldValue 就可以

Get 了，`get * 2` 是用于 Form.Item 和 Form instance 数据之间的转化，的确不是用于 Form instance 的数据转化。

**Comment by crazyair** [comment]
我的预期是

`getFormatValue` 格式化获取值。
`setFormatValue` 格式化提交值。

**Comment by zombieJ** [comment]
Form 的数据管理类型本身是稳定的，初始化数据转换不是 Form 的 scope。还是需要业务上自行转换。

**Comment by crazyair** [comment]
就是来找解决方案的，对于表单层级比较多的那种，格式化字段是个异常麻烦和不好维护的事情。

```
{
"a": {
"b": {
"c": [
{
"d": 1589968926
}
]
}
}
}
```

**Comment by yoyo837** [comment]
@crazyair 你再加上getValueFromEvent能不能满足需求？

**Comment by crazyair** [comment]
`get * 2` 能勉强满足，但是不完美。

**Comment by crazyair** [comment]
还有如果用 deps 获取 date 值，会是时间戳，当 date 改变一次又变成 Moment，这里 deps 还要加格式判断。

**Comment by crazyair** [comment]
现在做了提交格式化，但是获取格式化是个难题，我没想到怎么解决
![image](https://user-images.githubusercontent.com/7971419/82435767-5d238600-9ac7-11ea-9637-a0751b87c41e.png)

**Comment by zombieJ** [comment]
还是建议在入口做 initialValues 的处理，可以用 json schema 来预转换一下数据。当把未转化的数据传进去后，到处都需要判断类型了。
简单来一点就直接递归判断是否是合法的 timestamp。

**Comment by crazyair** [comment]
一个字段被多个 Form 复用，每个 initIalValues 都要转换一次，比较麻烦。
