### ISSUE TITLE
Select component de-selection does not work by passing `undefined` as value

### ISSUE THREAD

**Issue by nikhilem** [ant-design/ant-design#24310]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-with-search-field-ant-design-demo-g0fz6?file=/App.js)

### Steps to reproduce
1. Click on any option of Select
2. Clicking on the `None` option should deselect the value & show only the placeholder
<img width="231" alt="Screenshot 2020-05-20 at 1 01 15 PM" src="https://user-images.githubusercontent.com/8972095/82418023-10758600-9a9a-11ea-88f1-1e65aad600cf.png">

3. Clicking on the `None` option again, also should the placeholder, but it shows `None` as the selected option
<img width="231" alt="Screenshot 2020-05-20 at 1 01 26 PM" src="https://user-images.githubusercontent.com/8972095/82418041-15d2d080-9a9a-11ea-9a34-1e2a8c2ff130.png">

### What is expected?
When clicking on the `None` option, it should deselect the value & show only the placeholder.

### What is actually happening?
It displays `None` as the selected option even though the value prop for Select is `undefined`

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | macOS 10.15.4 |
| Browser | Chrome 81 |

---
Providing a `None` option for the user to de-select any selected option, by setting the `value` prop of the `Select` component as undefined, should deselect the option and show only the placeholder.

This works as expected in Ant v3 ([Reproduction](https://codesandbox.io/s/select-with-search-field-ant-design-demo-qhqmo?file=/App.js)) i.e clicking on the `None` option any number of times shows only the placeholder
But, works inconsistently in Ant v4 ([Reproduction](https://codesandbox.io/s/select-with-search-field-ant-design-demo-g0fz6?file=/App.js)) i.e clicking on the `None` option more than once, selects the `None` as an option instead of deselecting all options.

**Comment by nikhilem** [comment]
De-selection in Ant v4 works by setting value as `[]`(Empty array) instead of `undefined` 🤔

**Comment by KamilNiewiadomski** [comment]
Hi @nikhilem, how to de-select single option in multiple mode?

**Comment by afc163** [comment]
Don't use `undefined` as any field value.
