### ISSUE TITLE
table 组件 设置scroll 之后 动态减少columns 会导致 单元格不撑满屏幕

### ISSUE THREAD

**Issue by zyrepo** [ant-design/ant-design#24316]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-n9t6w?file=/index.js)

### Steps to reproduce
一直点减  即可重现 

### What is expected?
期望，表格撑满屏幕

### What is actually happening?
减少表格的columns的时候，没有自动撑满屏幕

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.0 |
| System | window10 |
| Browser | chrome  80.0.3987.163 |

**Comment by zyrepo** [comment]
页面resize的时候会重新撑满

**Comment by zombieJ** [comment]
诡异……

**Comment by zyrepo** [comment]
@zombieJ  下次发版在什么时候呢

**Comment by yoyo837** [comment]
大概是周五、六、日、一。

**Comment by yoyo837** [comment]
react-component/table#479 应该重装依赖就可以用了

**Comment by zyrepo** [comment]
@yoyo837 
antd的依赖是~7.5.3
![image](https://user-images.githubusercontent.com/22114645/82517954-d3b89600-9b50-11ea-980d-c05f1196642e.png)
更改是改到了 7.7.1 上
![image](https://user-images.githubusercontent.com/22114645/82518041-0498cb00-9b51-11ea-95a8-67ec569fb2eb.png)
应该需要更新版本之后，才可以用吧

**Comment by yoyo837** [comment]
嗷 没注意看， 那要等4.3.0了

**Comment by zyrepo** [comment]
ok

**Comment by zombieJ** [comment]
<img width="758" alt="截屏2020-05-21 下午9 46 22" src="https://user-images.githubusercontent.com/5378891/82565151-84a04e80-9bac-11ea-84d3-b80903f3400a.png">

7.5.x 也发了 patch
