### ISSUE TITLE
Menu inlineCollapsed without icon display Error

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24311]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suoqineiqiancaidan-ant-design-demo-3v5s3?file=/index.js)

### What is actually happening?

![image](https://user-images.githubusercontent.com/29775873/82423926-0e6df000-9ab7-11ea-969d-4f312e26f35f.png)

**Comment by xrkffgg** [comment]
虽然可以把这个文字居中，但是文字过多，也显示不全。

是不是 可以 在收起的时候 加一个默认 按钮

**Comment by xrkffgg** [comment]
大家有什么方案？

**Comment by yoyo837** [comment]
省略号吧，要么保持现状，没啥好办法。

**Comment by afc163** [comment]
用 `<Avatar>{title[0]}</Avatar>`
