### ISSUE TITLE
setFieldsValue in dynamic form

### ISSUE THREAD

**Issue by Firetuy** [ant-design/ant-design#24317]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This feature solve the doubt about how to setFieldsValue in a dynamic form

### What does the proposed API look like?
https://codesandbox.io/s/form-methods-ant-design-demo-c1yvv?file=/index.js

Please look at the console and commented lines at function handleCidade

**Comment by zombieJ** [comment]
`setFieldsValue` is to set a group of values. For array index value, you can use `setFields` to config it.

ref: https://ant.design/components/form-cn/#FieldData
