### ISSUE TITLE
Table缺少下边框

### ISSUE THREAD

**Issue by ILiuDongHui** [ant-design/ant-design#24312]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-bordered](https://ant.design/components/table-cn/#components-table-demo-bordered)

### Steps to reproduce
添加一个带边框的表格组件： <Table borderd />

### What is expected?
具有正常的四条边框

### What is actually happening?
缺少下边框

| Environment | Info |
|---|---|
| antd | 4.2.3 |
| React | react |
| System | Windows10 1903 |
| Browser | Chrome 81.0.4044.138（正式版本） （64 位） |

---
如果传递了 footer ，那么下边框有的，但我并不需要一个 footer

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/82475348-f3bf6980-9afe-11ea-8347-51ebbfef0734.png)

去掉 footer 后，下边框仍然在显示

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/daibiankuang-ant-design-demo-e1zx4
