### ISSUE TITLE
表格悬浮编辑的 Case 在哪里？

### ISSUE THREAD

**Issue by abbish** [ant-design/ant-design#2432]
请问，

表格悬浮编辑的 Case 在哪里？

![qhiyxenxazealjt](https://cloud.githubusercontent.com/assets/138192/16945468/cc9d048e-4dd7-11e6-940a-e4b1e634facc.png)

**Comment by RaoHai** [comment]
column 的 render 里加个 popover，编辑之后把数据改掉。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/blob/design-pattern/docs/pattern/table/demo/edit-hover.md

**Comment by abbish** [comment]
OK，如果我想做双击内容变表单输入，也是要在 render 中自己做控件实现吧 ？

**Comment by abbish** [comment]
OK，多谢
