### ISSUE TITLE
Button loading windows环境下依旧卡顿

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#24323]
windows环境下依旧卡顿，loading时icon是突然弹出来的，和上面gif中的效果不一样。[官网Demo](https://ant.design/components/button-cn/#components-button-demo-loading)可以复现。

![button](https://user-images.githubusercontent.com/36978364/82443342-ea6cd780-9ad3-11ea-8dba-ff3ea68a6f29.gif)

Environment | Info 
-----|-----
Windows | 10
Chrome | 81.0
antd| 4.2.4

_Originally posted by @Loving-Vincent in https://github.com/ant-design/ant-design/pull/23783#issuecomment-631428000_

**Comment by shaodahong** [comment]
Cause by https://github.com/ant-design/ant-design/pull/24095/files  `inline-block` remove, but relate to `rc-animate/lib/CSSMotion`

**Comment by afc163** [comment]
We can add inline-block back.
