### ISSUE TITLE
Cascader displays values of previously picked option after re-render

### ISSUE THREAD

**Issue by FlyingUnicornSF** [ant-design/ant-design#24333]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://4lzr9.csb.app/](https://4lzr9.csb.app/)

### Steps to reproduce
1: select an option from the left selector. 2: select an option from right Cascader 3: select another option on the left selector. 4: cascader shows values of the options from the last selected.

### What is expected?
cascader clears field 

### What is actually happening?
cascader showing values of last options that were selected. 

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | macOS Catalina |
| Browser | Chrome  81.0.4044.138  |

**Comment by afc163** [comment]
It is not a bug, you should clear Cascader value when select option.

**Comment by FlyingUnicornSF** [comment]
with which command? can you explain this a little bit more? it's clearly not explained in the documentation.

**Comment by FlyingUnicornSF** [comment]
@afc163  if it's not a bug, then explain why it doesn't happen in version 4.1.2
[https://ylb8b.csb.app/](https://ylb8b.csb.app/)
