### ISSUE TITLE
v4 Table with Fixed Header flickers on initial load

### ISSUE THREAD

**Issue by NickDubelman** [ant-design/ant-design#24332]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
You can use the documentation tables to reproduce this. If you open the v3 Table "Fixed Header" example, there is no flickering. If you do the same for v4 Table "Fixed Header" example (open it in Stackblitz and hit the refresh button), you will see a flicker when the table initially loads.

### What is expected?
Fixed header should not flicker in on initial load. It looks very clunky because the data loads in and then the column headers flicker in afterwards. This is even for small amounts of data like 3 rows!

### What is actually happening?
Fixed header flickers in after ~0.5 seconds (meanwhile the table data is already rendered)

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13 |
| System | Mac |
| Browser | Firefox, Chrome, Safari |

**Comment by zombieJ** [comment]
could you help to provide a gif for this?

**Comment by NickDubelman** [comment]
it is subtle but the column headers render after the data. this seems to only be the case when using fixed header ![antd4-table-bug](https://user-images.githubusercontent.com/16615307/95614670-bb6fe780-0a1b-11eb-8ec6-2d1f97b67d22.gif)

**Comment by zombieJ** [comment]
v4 use `requestAnimationFrame` to sync Table header to avoid column init render trigger multiple time resize observer. Let me check how to improve this.
