### ISSUE TITLE
关于 Breadcrumb 设计方面的两个问题。

### ISSUE THREAD

**Issue by any-hn** [ant-design/ant-design#2434]
关于 Breadcrumb 设计方面的两个问题。

1. 鼠标悬停的时候 breadcrumb item 字体没有什么变化。仅有的 indicator 是 cursor/pointer 变成手指样式。

2. breadcrumb 里面的字体照理来说都是 link text，使用 link text 的样式感觉会比现有的灰色更加显眼让用户更容易轻松的意识到向上导航链接的存在。不知为何设计中没有使用。

希望能跟大家友好讨论学习一下。谢谢。

**Comment by Chinglik** [comment]
感谢你的反馈哦，这里确实有些问题

这里面包屑采用的是弱链接的方式，因为从功能上看，他所在的位置和常规样式，已经能够看出它的作用；不直接用『链接蓝』也是从视觉上跟灰色底不太融合，也不想再不需要引导的时候面包屑一直这么明显，所以做了让步，改成默认灰，需要时再点亮的方式；

所以这里 hover 的时候，不光鼠标会变成手型，字也应该变成蓝色的 link text 的。设计稿如下图：

![image](https://cloud.githubusercontent.com/assets/14192159/17009385/9b52cc64-4f2c-11e6-9765-f2a0275390a6.png)


这个我们会和工程师尽快修改，谢谢你的细心指出哈~~^_^
