### ISSUE TITLE
希望message的getContainer可以多次配置

### ISSUE THREAD

**Issue by wangxiaogang94** [ant-design/ant-design#24349]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
全屏Fullscreen某一个dom节点以后,比如ReactDOM.findDOMNode(ref.current).webkitRequestFullscreen()，message需要挂载在这个dom节点上。但是路由跳转或者该dom节点销毁后，message就无法挂载了。

### What does the proposed API look like?
希望message.config可以多次调用配置。或者message[level]可以配置getContainer

**Comment by afc163** [comment]
支持：https://github.com/ant-design/ant-design/issues/23085

@wangxiaogang94 可以来个 PR 补充一下文档。

**Comment by afc163** [comment]
message.config 应该是可以多次调用的：https://github.com/ant-design/ant-design/blob/35a6a887a34626e5c097411b3e5dd6c7e6776699/components/message/index.tsx#L152

**Comment by rt-zhangxuefei** [comment]
希望能在message.info(config) 里面也支持下，使用时按需修改 getContainer

**Comment by Yiniau** [comment]
目前需要手动调用 message.destroy
否则 config 之后生成的 instance 不会被销毁，getContainer 一直指向旧的内存中的函数
https://github.com/ant-design/ant-design/blob/35a6a887a34626e5c097411b3e5dd6c7e6776699/components/message/index.tsx#L12
https://github.com/ant-design/ant-design/blob/35a6a887a34626e5c097411b3e5dd6c7e6776699/components/message/index.tsx#L21
