### ISSUE TITLE
[SoC2020] Add feature for components

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#24352]
ref: #24351

#### 项目名称/Project Title
为组件新增 feature<br />Add feature for components<br />

<a name="FuJDg"></a>
#### 项目描述/Project Description
在 antd 日常维护中，存在大量新增需求。在经过评估后会接纳一些合理需求，从而进行落地。<br />In the daily maintenance of antd, there are a lot of new feature request. After an assessment, some reasonable needs will be accepted to land.<br />

<a name="8OMx6"></a>
#### 预期成果/Expected Outcomes

- [https://github.com/ant-design/ant-design/issues/17975](https://github.com/ant-design/ant-design/issues/17975)
  - Typography.Paragraph 自动溢出省略修改展开按钮
  - Typography.Paragraph support customize ellipsis button
-  [https://github.com/ant-design/ant-design/issues/19514](https://github.com/ant-design/ant-design/issues/19514)
  - Col 支持响应式排序
  - Col support responsive ordere
- [https://github.com/ant-design/ant-design/issues/20574](https://github.com/ant-design/ant-design/issues/20574)
  - Skeleton 提供对应组件样式
  - Skeleton support more component style
- [https://github.com/ant-design/ant-design/issues/22732](https://github.com/ant-design/ant-design/issues/22732)
  - DatePicker 支持更多日期库
  - DatePicker support more date lib
- [https://github.com/ant-design/ant-design/issues/22298](https://github.com/ant-design/ant-design/issues/22298)
  - Form.List 支持批量删除
  - Form.List support batch deletion

<a name="XTscC"></a>
#### 需要的技能/Required Skills

- React
- Typescript
- Jest
- HTML
- CSS

**Comment by fireairforce** [comment]
I am a junior student  and now am an intern in BeiJing, I want to take part in this.

**Comment by zombieJ** [comment]
> I am a junior student and now am an intern in BeiJing, I want to take part in this.

https://github.com/ant-design/ant-design/issues/24351#issuecomment-632441183 Welcome : )

**Comment by saphal1998** [comment]
Hey @zombieJ. I'd love to work on this issue, can you help me get started on this?

**Comment by arteevraina** [comment]
Hello @zombieJ I am really looking forward to work on this idea. Can you guide me to get started on this idea and if there is a gitter channel or any other irc or mailing list so that I can discuss the project idea with you?

**Comment by maze-runnar** [comment]
@zombieJ can you please help me in getting started with this idea for ASoC.

**Comment by zombieJ** [comment]
Hi all , pls leave comment on #24351 instead. Lock issue for more comments.
