### ISSUE TITLE
缺少工具类

### ISSUE THREAD

**Issue by aliyoung** [ant-design/ant-design#24358]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
内容的居中，padding，margin等等工具类没有，还需要手动写样式，造成风格不统一

### What does the proposed API look like?
.text-center，p-sm-1，.m-sm-1

**Comment by yoyo837** [comment]
antd 跟 bootstrap这种定位还是有区别的，容易冗余，大家也不会都异口同声来使用这些工具类，反而会增大bundle。建议按照自己的需求自行定义。
