### ISSUE TITLE
[SoC2020] 2020 Alibaba Summer of Code for students

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#24351]
# 2020 Alibaba Summer of Code

Welcome to the open source world! If you haven't planned how to spend this summer, come to the Alibaba Summer of Code and coding with us! 💻

Alibaba Summer of Code is a global program focused on engaging students directly into open source software development. Under the guidance of the mentor in the Alibaba open source project, students experience the software development in the real world.Alibaba Summer of code will begin between May 25th and September 5th. Students can use the summer time to participate in the open source project and work with the core members of the project.

## What you can get?
On this exclusive developer journey, students will have the opportunity to:

- Participate in the top projects of the International Open Source Foundation;
- Get a scholarship from Alibaba;
- Obtain an open source contributor certificate;
- Get a fast pass of Alibaba Internship/recruitment;
- Get your code adopted and used by the open source project！

## Our Mentor
@zombieJ 

## Apply Now!
Step 1. You can click on this link to apply directly:

* [Add feature for components](https://github.com/ant-design/ant-design/issues/24352)
* [Rewrite Cascader](https://github.com/ant-design/ant-design/issues/24353)

Step 2. Full list of Alibaba Summer of Code Projects:

(Online after 5-25)

- 中文：[https://developer.aliyun.com/topic/summerofcode2020](https://developer.aliyun.com/topic/summerofcode2020)
- English:[https://www.alibabacloud.com/campaign/summerofcode2020](https://www.alibabacloud.com/campaign/summerofcode2020)

![image](https://user-images.githubusercontent.com/5378891/82538449-599f0600-9b7e-11ea-9042-5724e6200b4c.png)

## Timeline⏳

![image](https://user-images.githubusercontent.com/5378891/82538572-86531d80-9b7e-11ea-917f-d634f5084dc4.png)

## Contact us!
Email Address: aliopensource@alibabacloud.com

**Comment by morenyang** [comment]
sounds cool, but I am not a student anymore 😭

**Comment by fireairforce** [comment]
it's cool, i will take part in this.

**Comment by zombieJ** [comment]
Hi @fireairforce , register page will open on 5-25. Welcome to participate in : )

**Comment by fireairforce** [comment]
@zombieJ ok

**Comment by ycjcl868** [comment]
It's cool, could I take part in this?

**Comment by zombieJ** [comment]
Hi all, please feel free to register if you want to join.

**Comment by xrkffgg** [comment]
I am no longer a student. 

If you are still in school, do not miss it, trust yourself.

**Comment by fireairforce** [comment]
ok, i will apply right now.

**Comment by fireairforce** [comment]
@zombieJ I want to konw that in our idealist,we just need to write one of the choice in our Implementation plan or we should finish the both?
![image](https://user-images.githubusercontent.com/32598811/82888280-b5e99780-9f7b-11ea-802b-8e84a2ad40df.png)

**Comment by maze-runnar** [comment]
@fireairforce I think only one.

**Comment by zombieJ** [comment]
> @zombieJ I want to konw that in our idealist,we just need to write one of the choice in our Implementation plan or we should finish the both?
> ![image](https://user-images.githubusercontent.com/32598811/82888280-b5e99780-9f7b-11ea-802b-8e84a2ad40df.png)

Pick one

**Comment by ali4heydari** [comment]
Cool, but I'm a student from Iran 😭

**Comment by crazyair** [comment]
Form.List 问题还很多，对适应复杂场景还有很多不足。

**Comment by HarshMehta2468** [comment]
@zombieJ  Is there any channel/mailing list where we can discuss the project idea? I realy want to be a part of this through ASOC 2020

**Comment by zombieJ** [comment]
hi @HarshMehta2468 ,

We use a unified registration entrance for students participate in. System will choose the match resume to enjoy the SoC2020. If you have a good idea, pls feel free to register:
* 中文：https://developer.aliyun.com/topic/summerofcode2020
* English:https://www.alibabacloud.com/campaign/summerofcode2020

**Comment by tsaffi** [comment]
Greetings. I am new to open-source. I have been using ant-design for a while now and I love it. So, I decided to contribute to making it better. Since I am new to open-source, I would like to know if there is a forum where contributors can request for help anytime they get stuck while working on a new feature, fixing a bug or to have a better understanding of the codebase.
I read this https://ant.design/docs/react/contributing and have set up my environment already.

**Comment by zombieJ** [comment]
Hi @tsaffi,
After reading https://ant.design/docs/react/contributing, you can start PR as you wish. For PR, there need to fill some additional info in PR template. You will see it when open PR : )

**Comment by zombieJ** [comment]
报名通道关闭，锁定 issue。
Lock issue since register time up.
