### ISSUE TITLE
component   collapse ， serial click on panel content， it will report ‘Error handling response: TypeError: Cannot read property 'left' of undefined’

### ISSUE THREAD

**Issue by xiaoYuanDun** [ant-design/ant-design#24356]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-8t8pk?file=/index.js)

### Steps to reproduce
serial click on panel content zone,  

### What is expected?
no error console

### What is actually happening?
it will report 'Error handling response: TypeError: Cannot read property 'left' of undefined'

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.9.35 |
| System | window 10 pro |
| Browser | chrome 83.0.4103.61  |

---
at first, i think is the problem of my environment or context , then i code it on codesandbox, however it happen the same problem, and i try some other edition, like 4.2.3 , 4.2.2 ,it also happen, and i can not find the trigger of the problem

**Comment by xiaoYuanDun** [comment]
and, the example on https://ant.design/components/collapse-cn/#header have this porblem too

**Comment by yoyo837** [comment]
Can not reproduce

**Comment by afc163** [comment]
May cause by your browser extension.

**Comment by xiaoYuanDun** [comment]
thank U, i will check out and try to find a way to provide a online reproduction，close this issue for the moment
