### ISSUE TITLE
[SoC2020] Rewrite Cascader

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#24353]
ref: #24351

#### 项目名称/Project Title
重写 Cascader<br />Rewrite Cascader<br />

<a name="USt04"></a>
#### 项目描述/Project Description
部分 antd 组件可以通过重构复用现有组件统一提升其性能以及改进包尺寸。在 v4 中，Select 组件底层已经为全键盘以及无障碍做了技术支持。因而类似的 Cascader 组件也可以借此获得相关能力。<br />Some antd components can be refactored and reused to improve their performance and package size. In v4, the base of the Select component has provided technical support for the full keyboard and accessibility. Therefore, similar Cascader components can also be used to obtain related capabilities.<br />

<a name="q1Jg1"></a>
#### 预期成果/Expected Outcomes

- 使用 `rc-select` 的 generate 函数重写 Cascader 组件。
- 需要提供全键盘支持。
- 需要提供无障碍支持。
- 跑通原本的测试用例。
- #23530 提供的例子的性能得到大幅提升。

---

- Use `rc-select`  generate to rewrite Cascader component.
- Need fully keyboard support.
- Provides accessibility.
- pass all exist test case.
- #23530 perfermance issue could be resolved.

<a name="7mdTp"></a>
#### 需要的技能/Required Skills

- React
- Typescript
- Jest
- HTML
- CSS

**Comment by arteevraina** [comment]
@zombieJ I am interested in this idea for ASoC 2020.

**Comment by zombieJ** [comment]
Hi @arteevraina  pls feel free to go to the link on #24351 for registry. Lock issue for more comments.
