### ISSUE TITLE
Small rounded buttons have a wrong font-size applied

### ISSUE THREAD

**Issue by DiegoBM-DB** [ant-design/ant-design#24367]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/button/style/mixin.less#L366](https://github.com/ant-design/ant-design/blob/master/components/button/style/mixin.less#L366)

### Steps to reproduce
Following the link you can see how the @font-size-base is applied instead of @btn-font-size-sm for small rounded buttons

### What is expected?
All buttons should have @btn-font-size-sm applied regardless of their shape type

### What is actually happening?
The wrong @font-size-base is applied to rounded small buttons

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | React |
| System | All Systems |
| Browser | All Browsers |

**Comment by zombieJ** [comment]
It's by design. Not a bug.

**Comment by DiegoBM-DB** [comment]
Is there any logical, valid explanation or reasoning that justifies why it was decided to make it look like that by design? Because it certainly looks disconnected and inconsistent. And it doesn't make sense to allow the user to configure the font size for the small size if it's not going to be respected afterwards.

This is how it looks like as it is right now:
![wrong](https://user-images.githubusercontent.com/13576899/82567876-49872680-9b7e-11ea-92e4-1ce6034ff5c0.png)


And this is how it would look like with the right setting applied:
![right](https://user-images.githubusercontent.com/13576899/82567889-4c821700-9b7e-11ea-8e71-fa0fc2e04c5c.png)
