### ISSUE TITLE
TreeSelect 搜索异步返回不展开

### ISSUE THREAD

**Issue by duwei54** [ant-design/ant-design#24361]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/search-not-expand-b55b8?file=/src/App.js:554-574)

### Steps to reproduce
使用搜索,异步返回来的data树节点无法全部展开

### What is expected?
搜索返回数据  节点可以全部展开

### What is actually happening?
没有展开

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | win10 64bit |
| Browser | chrome |

---
3.X版本没有此问题

**Comment by afc163** [comment]
这是符合预期的，`treeDefaultExpandAll`  只有第一次 render 会生效。你需要手动控制展开的 keys。

> 如果 3.x 能工作，那么应该是 3.x 的 bug。

**Comment by duwei54** [comment]
想不到我钟意的功能,竟然是一个bug 😂   真是一个伤心的事情
