### ISSUE TITLE
1.6.5版本 upload 上传没有反应

### ISSUE THREAD

**Issue by afeidonler** [ant-design/ant-design#2436]
刚刚升级到1.6.5版本 发现uploader 点击上传没有反应，但是图片已经上传了，只是没有显示，希望可以修复

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by leejaen** [comment]
今天发现有同样的问题

**Comment by yesdgn** [comment]
就是onChange只会触发一次了uploading ， 以后的done什么的就不会触发了。  我也是相同的问题。希望修复。

**Comment by afc163** [comment]
是否这个问题：https://github.com/ant-design/ant-design/issues/2423

**Comment by yesdgn** [comment]
是的，按#2423里的修改下就好了。
