### ISSUE TITLE
Radio Group 触发onChange时的问题

### ISSUE THREAD

**Issue by seraphimrose** [ant-design/ant-design#2437]
radio group 的 onChange触发时，查看e.target，发现其checked属性不是预期的值？（true和false相反）

似乎给radio group设置value时会出现该问题

代码：http://codepen.io/seraphimRose/pen/YWZmoo

**Comment by afc163** [comment]
http://ant.design/components/radio/ 这里也有问题。

反复点击 Radio，会出现类似 Checkbox 的切换行为。

原因是这里 https://github.com/react-component/checkbox/blob/ce54ab62363315d235c3498a6ef222349b42bc2f/src/Checkbox.jsx#L68 和 https://github.com/react-component/checkbox/blob/ce54ab62363315d235c3498a6ef222349b42bc2f/src/Checkbox.jsx#L74 ，不应该进行切换。应该始终取 `e.target.checked` 的值。

@yiminghe
