### ISSUE TITLE
table columns render 中添加的click事件函数， 监测不到state的变化

### ISSUE THREAD

**Issue by zyrepo** [ant-design/ant-design#24370]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-l7wnz?file=/index.js)

### Steps to reproduce
点击加或减， 然后点击a链接查看控制台变化

### What is expected?
默认columnsState  length为2
期望， 点减的时候， columnsState length 变为1  
此时 点击表格中的text 控制台打印的columnsState length 为1

### What is actually happening?
当前 点击表格中的text 控制台打印的columnsState length 为2

| Environment | Info |
|---|---|
| antd | 4.2.4|
| React | 16.13.1 |
| System | windows |
| Browser | chrome  |

**Comment by afc163** [comment]
期望是什么，实际是什么，建议写清除，`state的改变` 是一个很模糊的描述。

**Comment by zyrepo** [comment]
@abc163 期望是可以检测到columnsState 的变化， 实际是检测不到

**Comment by yoyo837** [comment]
issue里10个以上的相关问题，主要围绕render引用不到新state值，作用相关，动态返回新的columns就好了

**Comment by zyrepo** [comment]
@yoyo837 可以在上面的demo里举个例子吗，非常感谢

**Comment by afc163** [comment]
> 可以检测到 案例中 columnsState 的变化

怎么算检测到变化。

你可以按这种思路写：期望 console.log 打印 AAAA？实际上是 BBBB。

**Comment by yoyo837** [comment]
你这个columnsState 到底啥作用 没意义

**Comment by zyrepo** [comment]
@afc163  更新了一下描述

**Comment by zyrepo** [comment]
@yoyo837  这个只是个例子， 比如表格column中render了一个dom，绑定了一个click事件， 点击的时候，需要把当前行（record）的数据和 当前组件 state中的数据结合起来，传给另一个组件。

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-zmtdx?file=/index.js 
仅供参考。

虽然改掉了你demo 对 column 的存储，但我想说明的是，render没有引用到最新值并不和antd有关。

**Comment by zyrepo** [comment]
@yoyo837  可以帮忙看一下这个例子吗   https://codesandbox.io/s/antd-reproduction-template-qlej5?file=/index.js

**Comment by zyrepo** [comment]
@yoyo837 谢谢

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-1yyny?file=/index.js

**Comment by afc163** [comment]
看上去是有点奇怪：https://codesandbox.io/s/antd-reproduction-template-61ory?file=/index.js

**Comment by zyrepo** [comment]
@yoyo837  你没发现我写的那个demo, 不用useMemo 也可以正常打印吗

**Comment by zyrepo** [comment]
@afc163  我是指这个
![image](https://user-images.githubusercontent.com/22114645/82634387-274de100-9c30-11ea-9fda-f99e9e07b835.png)

**Comment by zyrepo** [comment]
@afc163  Table组件 现在 onRow 中可以获得 当前组件更新后的state  columns中的 onCell 和  render 中绑定的事件 取不到最新的state值

**Comment by afc163** [comment]
为啥关掉了。

**Comment by zyrepo** [comment]
> 为啥关掉了。

使用onRow可以满足需求了，不确定 框架层面 在onCell 中是否可以解决  取不到最新state的问题

**Comment by afc163** [comment]
先开着等 @zombieJ 有空排查，也欢迎帮忙排查。

**Comment by zyrepo** [comment]
ok

**Comment by zombieJ** [comment]
<img width="1153" alt="截屏2020-05-24 上午11 20 28" src="https://user-images.githubusercontent.com/5378891/82744860-95b9ad00-9db0-11ea-89ec-a3d500f2c4ba.png">

内部 column 是更新的了，主要问题是你 `column[0]` 中的 `columnState` 在初始化时就已经固定是最初那个 `columnState`。之后更新 `columnState` 都和 `columns` 无关。你可以看看这个每次更新都重新初始化 `columns[0]` 的效果：
https://codesandbox.io/s/antd-reproduction-template-u2hkp?file=/index.js

当然这个改动也同样有延迟，不解决更新问题。最好的方式是把循环依赖解耦或者退而求其次用 `useRef` 来获取 `columnState` 更新：
https://codesandbox.io/s/antd-reproduction-template-kqov7?file=/index.js
