### ISSUE TITLE
the Option list Quickly withdraw from select Component  

### ISSUE THREAD

**Issue by xinyanxing** [ant-design/ant-design#24384]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/danxuanzuhe-ant-design-demo-7wm80?file=/index.js)

### Steps to reproduce
1.Add Select into Radio.Grop

### What is expected?
 Option list show 

### What is actually happening?
Can't selected because Option list Quickly withdraw 

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.10.2 |
| System | mac os 10.15 |
| Browser | 81.0.4044.138（正式版本） |

**Comment by afc163** [comment]
https://codesandbox.io/s/danxuanzuhe-ant-design-demo-398tb?file=/index.js

**Comment by afc163** [comment]
https://codesandbox.io/s/danxuanzuhe-ant-design-demo-z2rfg?file=/index.js

**Comment by zcmgyu** [comment]
Thanks. Set `onClick={e => e.preventDefault()}` on <Select> help a lot.
