### ISSUE TITLE
Modal ok button size not recover after confirmingLoad switch

### ISSUE THREAD

**Issue by zhouyuan1990** [ant-design/ant-design#24382]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/t9su2)

### Steps to reproduce
1. click the button, open the modal, click the ok button
2. after the modal close, reopen the modal again.

the ok button size is not correct

### What is expected?
the ok button size should recover

### What is actually happening?
the ok button size is not recovered

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.12.0 |
| System | Mac OS 10.15.4 |
| Browser | Chrome |

**Comment by afc163** [comment]
Fixed in #24238

**Comment by afc163** [comment]
> Fixed in #24238

No, fixed in https://github.com/ant-design/ant-design/pull/24328

**Comment by zhouyuan1990** [comment]
thanks
