### ISSUE TITLE
快速拖动树节点释放后，会在释放的节点上残留类名drag-over drag-over-gap-top drag-over-gap-bottom

### ISSUE THREAD

**Issue by sz-Oliver** [ant-design/ant-design#24380]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#components-tree-demo-draggable](https://ant.design/components/tree-cn/#components-tree-demo-draggable)

### Steps to reproduce
none

### What is expected?
拖动完成之后，清除拖动位置的类名导致的样式问题

### What is actually happening?
快速拖动才会出现

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | windows ios |
| Browser | chrome |

**Comment by zhangwudi886** [comment]
no solution？

**Comment by sz-Oliver** [comment]
> no solution？

you can manually remove the node className when you dropped

**Comment by zhangwudi886** [comment]
> > no solution？
> 
> you can manually remove the node className when you dropped

other goodways to fix this problem without removing className？

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/tree/pull/355
