### ISSUE TITLE
存在自定义setInterval逻辑时，Carousel组件的autoplay失效了

### ISSUE THREAD

**Issue by chenhebing** [ant-design/ant-design#24388]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidongqiehuan-ant-design-demo-q10c2)

### Steps to reproduce
点击查看重现链接，在100s内，autoplay是无效的，超过100s后，开始启动轮播

### What is expected?
存在自定义setInterval逻辑时，autoplay依然可用

### What is actually happening?
存在自定义setInterval逻辑时，autoplay无效

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.0 |
| System | mac 10.15.4 |
| Browser | chrome |

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by Kermit-Xuan** [comment]
根本原因不是使用自定义`setInterval`，而是你的`setInterval`里面的逻辑会每隔一秒重新`setState`导致视图整体重新渲染，轮播组件也会重新渲染。但是`autoplay`是在每次视图更新的时候重启，又因为`autoplaySpeed`默认值是`3000`,你的`setInterval`间隔是`1000`,每次`autoplay`重启后还没切换时，你的视图又更新了，所以直到`setInterval`结束后才会开始`autoplay`。

解决方案：将`autoplaySpeed`的值设置的比你的`setInterval`时间短。

**Comment by morenyang** [comment]
consider using `React.Memo` or `useMemo` for your carousel

https://zh-hans.reactjs.org/docs/react-api.html#reactmemo
https://zh-hans.reactjs.org/docs/hooks-reference.html#usememo

**Comment by yoyo837** [comment]
state更新不应该重置 Carousel，这才是根本问题

**Comment by Kermit-Xuan** [comment]
这个是不是可以关了？

**Comment by yoyo837** [comment]
为什么关？个人认为是bug，我打算抽空看看

**Comment by Kermit-Xuan** [comment]
我是觉得自己可以规避这种问题，比如像 @morenyang 说的用`useMemo`, 当然如果在组件内部针对`autoplay`做优化更好。

**Comment by yoyo837** [comment]
@Kermit-Xuan 你之前看过这里，帮忙review下

**Comment by yoyo837** [comment]
<img width="913" alt="QQ20200527-131530@2x" src="https://user-images.githubusercontent.com/6134547/83504849-96141f80-a4f7-11ea-93c7-9cf1ff5bb3c4.png">
