### ISSUE TITLE
在使用 dropdownRender 对Select(mode="multiple")进行扩展时。 如果dropdownRender里有Input时，在input中进行删除操作会触发Select的删除。

### ISSUE THREAD

**Issue by 23cicada** [ant-design/ant-design#24387]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fragrant-grass-cngu8?file=/index.js)

### Steps to reproduce
1.选择Select框中的条目
2.对dropdownRender中的Input中进行删除操作
3.触发Select的删除

### What is expected?
dropdownRender中的Input中进行删除操作，不会影响Select

### What is actually happening?
dropdownRender中的Input中进行删除操作，也触发了Select的删除操作

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | react |
| System | macOs 10.15.4 |
| Browser | Chrome 81.0.4044.138 |

---
我尝试打开Select的下拉菜单时，对Select进行取消焦点操作，但对dropdownRender中的Input进行删除操作时，问题依旧出现。

**Comment by afc163** [comment]
Try `stopProgapagtion`

https://codesandbox.io/s/priceless-golick-7voim

**Comment by 23cicada** [comment]
非常感谢！
