### ISSUE TITLE
Table在使用虚拟列表时，点击某一列的排序会报错

### ISSUE THREAD

**Issue by XiaoMing6** [ant-design/ant-design#24383]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuniliebiao-ant-design-demo-bke6h?file=/index.js)

### Steps to reproduce
在使用虚拟列表的表格中，点击某一列排序

### What is expected?
正常触发onChange

### What is actually happening?
报错：Cannot read property 'scrollTop' of undefined

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.0 |
| System | win10 |
| Browser | Chrome 75.0.3770.80 |

**Comment by SevenLiu-code** [comment]
你可以把sorter换成一个函数，dataSource有多少个，就执行了多少次，我这边测了是这样的情况...

**Comment by XiaoMing6** [comment]
好的，那这个问题会在后续版本修复吗？

**Comment by yoyo837** [comment]
这个看上去是demo的问题，没兼容访问`documentElement[method]`

```tsx
  const [connectObject] = useState<any>(() => {
    const obj = {};
    Object.defineProperty(obj, 'scrollLeft', {
      get: () => null,
      set: (scrollLeft: number) => {
        if (gridRef.current) {
          gridRef.current.scrollTo({ scrollLeft });
        }
      },
    });

    return obj;
  });
```

**Comment by XiaoMing6** [comment]
但4.0.0没有这个问题

**Comment by yoyo837** [comment]
4.0.0 不报错，能正常排序吗？

https://codesandbox.io/s/xuniliebiao-ant-design-demo-rudtx?file=/index.js 这个demo里不能

**Comment by XiaoMing6** [comment]
我没有用到组件自行排序的功能，只用了点击排序能触发onChange的功能，除了4.0.0，其他版本都不能实现我的需求。对于这个问题，能给个解决方案么？更新demo或者更新Table？

**Comment by yoyo837** [comment]
那你用这个 https://codesandbox.io/s/xuniliebiao-ant-design-demo-2dt0n

**Comment by edant92** [comment]
I also had this issue when filtering and adding:

```
    Object.defineProperty(obj, "ownerDocument", {
      get: () => document.body.ownerDocument
    });
```

also fixed it for me :)

**Comment by zombieJ** [comment]
Merge into #20339
