### ISSUE TITLE
Table组件的表头动态添加列后出现异常

### ISSUE THREAD

**Issue by PeiTianHuang** [ant-design/ant-design#24389]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/6nsim)

### Steps to reproduce
表格渲染后添加一个有指定width的列即可，此时内容区渲染正常，但表格头部中新增的col并没有正常设置width和minWidth（table > colgroup > col）

若把表格销毁掉后重新渲染，则显示正常

该问题在4.0.1版本中不存在，升级到4.2.4后出现，目前回撤版本后表现正常

### What is expected?
表格头部应正常渲染新增的列

### What is actually happening?
目前渲染出来的列没有正常设置宽度

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome80 |

**Comment by afc163** [comment]
你给的例子好像和这个 issue 无关。

**Comment by fenglijunnb** [comment]
请问一下子奥。这是什么导致的呢    tryApplyUpdates is not defined

**Comment by PeiTianHuang** [comment]
更新到4.2.5后解决了

**Comment by fenglijunnb** [comment]
ok，我先试一下更新，直接改变package.json就行了吧

**Comment by yoyo837** [comment]
修改后，最好删除node_modules 和 lock 文件 重装

**Comment by fenglijunnb** [comment]
好的，谢谢

**Comment by fenglijunnb** [comment]
对了，再问你一下，lock文件我没找到，它在哪呢

**Comment by yoyo837** [comment]
packeg-lock.json 或者 yarn.lock

**Comment by fenglijunnb** [comment]
![image](https://user-images.githubusercontent.com/48191768/83117290-7946a900-a0ff-11ea-9d27-68c502b7860c.png)

**Comment by yoyo837** [comment]
并不会，自动生成的

**Comment by fenglijunnb** [comment]
好的，谢谢，麻烦你了
