### ISSUE TITLE
Input Component wrong value type

### ISSUE THREAD

**Issue by quantum-noise** [ant-design/ant-design#24403]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-spence-8zbcg?file=/index.ts)

### Steps to reproduce
Actual "value" type is `string | number | string[]`.
```JavaScript
// No type errors
export const A = () => <Input value={["test"]} />;
// No type errors
export const B = () => <Input value={1000} />;
```

### What is expected?
Expected value type is `string`.

### What is actually happening?
Actual value type is `string | number | string[]` (see https://ant.design/components/input/#Input).

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 81 |

**Comment by morenyang** [comment]
In the types definition of react, the `value` attribute of the native `input` element can be `string | string[] | number`. I think the `input` component in antd should also follow this rule.

![image](https://user-images.githubusercontent.com/15653996/82677351-73257800-9c7a-11ea-8462-84efcac0839b.png)

**Comment by quantum-noise** [comment]
For the `<input type="text">` the only correct value type is `string`: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text
The react type definitions is too general, it covers all possible `<input type=[text | number | ... ]>` cases.

**Comment by morenyang** [comment]
check the `type` attribute in the `input` component, it supports many types:
https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L19-L43

In addition, I think many projects use `number` as the value type in the `input` component, change to strict `string` may have some big impact...

**Comment by afc163** [comment]
@quantum-noise You are right. In antd, Input basicly equals to `<input type="text" />`, alrough we don't restrict `type` of input for some edge cases, but follow native input element's `type` tsd. Still, we don't encourage our users to change type and get confused, I perfer keep this `string` in documentation.
