### ISSUE TITLE
requestFullscreen()全屏下, Dropdown组件弹出部分不显示

### ISSUE THREAD

**Issue by CaicoLeung** [ant-design/ant-design#24400]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/CaicoLeung/React-TS-Hooks](https://github.com/CaicoLeung/React-TS-Hooks)

### Steps to reproduce
侧边栏菜单[商品管理], 右侧Table的[操作]列Dropdown下拉组件

### What is expected?
进入全屏下下拉组件弹出层显示

### What is actually happening?
进入全屏下下拉组件弹出层不显示

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | Mac 10.15.5 Beta |
| Browser | Edge 84.0.516.1 |

**Comment by yoyo837** [comment]
Duplicated of #24250

**Comment by CaicoLeung** [comment]
> Duplicated of #24250

谢谢, 已解决
