### ISSUE TITLE
IE11 bug in one of dependencies: Access is denied (scroll-into-view-if-needed => compute-scroll-into-view)

### ISSUE THREAD

**Issue by ichuyko** [ant-design/ant-design#24408]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/stipsan/compute-scroll-into-view/issues/676](https://github.com/stipsan/compute-scroll-into-view/issues/676)

### Steps to reproduce
Steps to reproduce:

1. You need App1 with iFrame
2. set document.domain of app1 to domain.com
3. You need App2 that load into App1 iframe
4. set document.domain of app2 to sub.domain.com
5. Try to scroll some pages with Menu items (Usage of function getFrameElement with a crash with error: Access is denied)

### What is expected?
No crashes

### What is actually happening?
Application crash

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | Windows |
| Browser | IE11 |

---
PullRequest with the fix: https://github.com/stipsan/compute-scroll-into-view/pull/680

**Comment by ichuyko** [comment]
Error in console: 
Access is denied

**Comment by afc163** [comment]
Fixed in https://github.com/stipsan/compute-scroll-into-view/pull/680

**Comment by ichuyko** [comment]
> 不用升，能安装到 2.2.25

In case a new installation or first usage yes, you are right, the latest version will be installed. But in case you have cached or already installed the old version ... your build could use the old version.  Also you can commit -lock file...

Probably it's better to put the correct version to dependency.

In any case, you guys will make the best decision...
