### ISSUE TITLE
feature branch test covarge

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#24401]
- master `85`: https://codecov.io/gh/ant-design/ant-design/tree/master/components/
- feature `96`: https://codecov.io/gh/ant-design/ant-design/tree/feature/components/

---

- [x] Transfer https://github.com/ant-design/ant-design/pull/24041#issuecomment-632601390 @zombieJ 
- [x] ConfigProvider https://github.com/ant-design/ant-design/pull/23759#issuecomment-632600645 @xrkffgg

**Comment by afc163** [comment]
Transfer 用例还得补补。

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/24414  这个已经把之前漏的补上了
