### ISSUE TITLE
table pagination position typescript type is wrong, document is Array, such as ['bottomRight']

### ISSUE THREAD

**Issue by vmwell** [ant-design/ant-design#24409]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
const pagination = {
            position: ['bottomLeft']
}

let locale = getTableLocale(fetchStatus)

return (
            <Table loading={loading} columns={columns} dataSource={dataSources.content}
                pagination={pagination} rowKey={record => record.id} size="middle" bordered locale={locale} />
)

### What is expected?
typescript project does not report the error

### What is actually happening?
error : 不能将类型“string[]”分配给类型“TablePaginationPosition[]”。

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome 83 |

**Comment by vmwell** [comment]
@ant-design-bot I know, but open the webpage too slow, no vpn

**Comment by afc163** [comment]
You can choose to provide a minimal GitHub repository.

**Comment by vmwell** [comment]
@afc163 GitHub repository: https://github.com/vmwell/antd-demo

Table define in App.tsx file

**Comment by afc163** [comment]
```diff
- position: ["bottomLeft"]
+ position: ["bottomLeft" as "bottomLeft"]
```

You can try this as workaround now.

**Comment by vmwell** [comment]
it is ok, thanks.

**Comment by zombieJ** [comment]
It's not a antd bug.  Typescript will tread as `string[]` when not define its type. So any const will make TS covert:
```ts
position: ["bottomLeft" as const]
```

ref https://www.typescriptlang.org/play?#code/C4TwDgpgBACg9gZwDIEsHCgXigCgOQA2EAZsHlAD5R4BOKA5gBZkCUA2gLoDcAUDwMZwAduigBDLFDaESZcQiiCRwbnyWiARgC54yNBmxjeA4QjhEAdATj0cGllyA

Or you can just reuse pagination define:
```tsx
const pagination: TableProps<any>['pagination'] = {
  position: ['bottomLeft'],
};

const table = <Table pagination={pagination} />;
```
