### ISSUE TITLE
Tree树形控件希望可以添加修改功能

### ISSUE THREAD

**Issue by YushengWang98** [ant-design/ant-design#24412]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在一些后台管理系统中,为了更方便的展示公司和分公司,部门及其下属部门的关系,我们会选择使用Tree树形控件,现在只能做到数据展示的功能,并没有实现对当前选中的数据进行修改的功能,如果用只是想单纯的修改一个部门或者分公司的名字的话可以直接在Tree上进行操作就不必跳转到另一个页面进行操作,可以大大的提高员工的效率

### What does the proposed API look like?
使用Boolean控制当前Tree组件是否为可编辑状态 ,当点击该item的编辑按钮时,替换为input进行可编辑的操作,点击确认按钮返回输入的值,点击取消按钮返回到原始值

**Comment by afc163** [comment]
Duplicate of #5782
