### ISSUE TITLE
关于 ant-design 组件库 3.x版本中table组件中boolean类型的列值无法被渲染的问题

### ISSUE THREAD

**Issue by JunZhou2016** [ant-design/ant-design#24427]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/table-cn/#components-table-demo-bordered](https://3x.ant.design/components/table-cn/#components-table-demo-bordered)

### Steps to reproduce
1、使用table组件新建一个table；
2、将某列设置为boolean类型，赋值为true/false;

### What is expected?
正确展示true/false

### What is actually happening?
boolean类型的列不显示

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 15.4.1 |
| System | windows |
| Browser | 74.0.3729.157（正式版本） |

**Comment by yoyo837** [comment]
没有render的情况下，个人感觉可以支持一下！

**Comment by yoyo837** [comment]
https://github.com/react-component/table/pull/480#issuecomment-633442852
