### ISSUE TITLE
Use <List.Item> component will broken by React Hook problem

### ISSUE THREAD

**Issue by EuphoriaCHN** [ant-design/ant-design#24422]
- ✅ I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/EuphoriaCHN/KCSoft-Test-Online/blob/master/src/component/QuestionList/QuestionList.tsx#L20](https://github.com/EuphoriaCHN/KCSoft-Test-Online/blob/master/src/component/QuestionList/QuestionList.tsx#L20)

### Steps to reproduce
1. open '/' or '/question' path
2. find **Change View** button on content top right, select "List Views" and click it
3. then React will mount `/src/component/QuestionList/QuestionList.tsx`
4. In Line #20, I used <List> and <List.Item> component, but if i just use <List.Item> by any way (Explicitly as a child element of <List> or use `renderItem` API), browser will warn that "Invalid hook call" and "The above error occurred in the <Item> component"
5. then, page was broken

### What is expected?
It will render right things on browser

### What is actually happening?
At first I thought it was my personal problem that was incorrect, but then I removed all Component (include react-hot-loader) and it still not work. [Like this](https://files.gitter.im/ant-design/ant-design/1T83/image.png)

But it not work, finally i simply use <List> component in ReactDom.render() to mount it to root DOM-Element, [like this](https://files.gitter.im/EuphoriaCHN/ot9q/image.png)

Then, [page still broken by same error](https://files.gitter.im/ant-design/ant-design/SsdO/image.png)

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | React: 16.13.1 |
| System | MacOS 10.15.4 (19E266) |
| Browser | Google Chrome  78.0.3904.108 |

### 补充说明
好叭我英语确实不好，辛苦你们了。

在使用 AntD高于 4.2.2 版本时，只要在 `<List>` 里面使用 `<List.Item>` 会报 Hook 相关的错误。我在 [这个 ISSUE](https://github.com/ant-design/ant-design/issues/24153) 和 [这个 ISSUE](https://github.com/ant-design/ant-design/issues/24176) 中找到了相关问题，但答案是降级到 4.1.3 版本。

我尝试过降级，确实能解决问题，但同时我使用了 `<Menu.Item>` 里面的 icon prop，看起来 4.1.3 对这个并不支持。

所以那两个 ISSUE 我认为并不是一个很好的解决问题的方法，有时间麻烦相关 RD 可以看看。感谢

（最近大学要期末考试了hhh实在腾不出时间 clone 仓库阅读大佬们的源码，下次一定

**Comment by EuphoriaCHN** [comment]
然后我康了康 4.2.4，也会出现同样的问题。

After now, I installed AntD@^4.2.4, there still be broken.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24176#issuecomment-630607366

**Comment by EuphoriaCHN** [comment]
THX, 谢谢
