### ISSUE TITLE
Buttons of InputNumber do not work anymore when trigger changed on form item

### ISSUE THREAD

**Issue by medihack** [ant-design/ant-design#24421]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/medihack/pen/VwvRbpL](https://codepen.io/medihack/pen/VwvRbpL)

### Steps to reproduce
1. Put `InputNumber` inside a `Form.Item`
2. Change the `trigger` of the form item to `onPressEnter`
3. Try to click the buttons of the `InputNumber` on the rendered site

### What is expected?
The up and down buttons should still work on an InputNumber regardless of the trigger type (there are a lot of cases where it makes sense to change the trigger an InputNumber).

### What is actually happening?
The up and down buttons of the InputNumber are still shown but without any functionality when changing the trigger on a form item.

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16 |
| System | Windows 10 Pro |
| Browser | Chrome 83.0.4103.61 |

**Comment by afc163** [comment]
`trigger` is used to collect data, InputNumber can't get it's value when change `trigger` to `onPressEnter`

**Comment by medihack** [comment]
Sorry, I don't fully understand. When changing the `trigger` to `onPressEnter`, the data is collected when entering some number and pressing the enter key. So this works (see reproduction link). But the buttons of the input do not work anymore.
I am looking for a way so that the data is collected from the `InputNumber` only if the user presses the enter key or the user changes the value using the buttons. I thought this is what `trigger` is for.
