### ISSUE TITLE
Affix: Method to unstick

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#24423]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Is there a method to unstick or remove Affix and then add it back when required?

### What does the proposed API look like?
refAffix.current.sticky(true|false)

**Comment by afc163** [comment]
Method is not a good way to use React, just try `<Affix />`.
