### ISSUE TITLE
Typography title not working

### ISSUE THREAD

**Issue by NoyChan** [ant-design/ant-design#24435]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/title-y17pg?file=/index.js)

### Steps to reproduce
添加title属性

### What is expected?
hover时显示title内容

### What is actually happening?
title不显示

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | window |
| Browser | Chrome/79.0.3945.88 |

---
3.x版本可显示title

**Comment by Kermit-Xuan** [comment]
I will work it.
