### ISSUE TITLE
能否增加图片异步加载组件Img

### ISSUE THREAD

**Issue by freepander** [ant-design/ant-design#2443]
如题。
组件中包含img标签，react貌似要等到图片加载完成后才会渲染整个组件。
能否增加异步加载图片的组件，只有在图片在可见的范围内才加载图片内容，提高render效率？

**Comment by benjycui** [comment]
antd 只是个 UI 库，这类功能建议 Google https://www.google.com.hk/?ion=1&espv=2#q=react%20lazy%20load
