### ISSUE TITLE
Many weird onChange events for Input.TextArea when triggered from smartphone

### ISSUE THREAD

**Issue by boiacchi** [ant-design/ant-design#24433]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ueijd.csb.app/](https://ueijd.csb.app/)

### Steps to reproduce
Using Firefox from Android 6 mobile phone:
1) Type a letter (example: x)
2) Type a comma or type space

### What is expected?
1) A message slides down from the top of the screen with the typed letter inside (example: "x")
2) A message slides down from the top of the screen with the 2 typed chars inside (example: "x,")

### What is actually happening?
1) A message slides down from the top of the screen with the typed letter nside (example: "x")
2) 4 messages slide down from the top of the screen with some chars inside (example: "", "x", "x,", "x, ")

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | react 16.13.1 |
| System | Android 6 |
| Browser | Firefox 68.8.1 |

---
My virtual keyboard adds a space after the comma automatically (Microsoft SwiftKey)

**Comment by afc163** [comment]
antd don't provide offcial support for Firefox Android, but any PR is welcome~
