### ISSUE TITLE
DatePicker localization: moment.locale('zh-cn') not work

### ISSUE THREAD

**Issue by Delphier** [ant-design/ant-design#24443]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-64gfh?file=/index.js)

### Steps to reproduce
Click DatePicker, see week title.

### What is expected?
The week of DatePicker is chinese.

### What is actually happening?
The week of DatePicker is english.

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 83 |

---
v4.2.0 is OK, when version >=4.2.1 occurs this issue.
After install v4.2.5, local moment auto update to v2.26.0 not v2.25.3.

**Comment by afc163** [comment]
Upgrade to antd@4.2.5, it works fine: https://codesandbox.io/s/antd-reproduction-template-w64f7?file=/package.json
