### ISSUE TITLE
FormItem 嵌套 FormItem 必填红星不显示

### ISSUE THREAD

**Issue by lz-lee** [ant-design/ant-design#24444]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cp0b6?file=/index.js)

### Steps to reproduce
官方文档里的示例就是不显示的。
https://ant.design/components/form-cn/#components-form-demo-complex-form-control

### What is expected?
required 红星显示

### What is actually happening?
required 红星不显示

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.12.0 |
| System | macOS 10.14.5 |
| Browser | Chrome  81.0.4044.138 |

**Comment by afc163** [comment]
```diff
- <Form.Item label="Username">
+ <Form.Item label="Username" required>
```

需要主动在外面声明。
