### ISSUE TITLE
es6 写法中Form的使用，getFieldProps undefined????

### ISSUE THREAD

**Issue by Yhaojing** [ant-design/ant-design#2444]
#### 本地环境

node 6.2.1
npm 3.9.3

- antd 版本:^1.6.3
- 操作系统及其版本：ios
- 浏览器及其版本:

#### 你做了什么？

使用and的Form表单
`import React, { Component, PropTypes } from 'react';
import { Input, Button, Form } from 'antd';
const FormItem = Form.Item;

class Login extends Component {
    constructor(props) {
        super(props);
        this.handleSubmit = this.handleSubmit.bind(this);
    }
    handleSubmit(e) {
        e.preventDefault();
        this.props.onLoginClick(this.props.form.getFieldsValue());
    }
    render() {
        const { errorMessage, form } = this.props;
        console.log('form:', form);
        const { getFieldProps } = form;
        return (
          <Form horizontal onSubmit={this.handleSubmit} >
            <FormItem
              label="用户名："
              labelCol={{ span: 6 }}
              wrapperCol={{ span: 14 }}
            >
              <Input
                ref="username" placeholder="Username"
                {...getFieldProps('username')}
              />
            </FormItem>
            <FormItem
              label="密码："
              labelCol={{ span: 6 }}
              wrapperCol={{ span: 14 }}
            >
              <Input
                type="password" ref="password" placeholder="Password"
                {...getFieldProps('password')}
              />
            </FormItem>
            <FormItem wrapperCol={{ span: 14, offset: 6 }} style={{ marginTop: 24 }}>
              <Button type="primary" htmlType="submit" className="col-24">Login</Button>
            </FormItem>
              {errorMessage &&
                <p style={{ color: 'red' }}>{errorMessage}</p>
              }
          </Form>
        );
    }
}

Login.propTypes = {
    form: PropTypes.func,
    onLoginClick: PropTypes.func.isRequired,
    errorMessage: PropTypes.string,
};

export default Login;
`

#### 你期待的结果是：

不能正常使用
#### 实际上的结果：

TypeError: Cannot read property 'getFieldProps' of undefined

**Comment by afc163** [comment]
按文档来，你漏代码了。

`Form.createForm`

**Comment by Yhaojing** [comment]
我知道有这句代码，以前写成let Demo = React.createClass({})形式时是Demo = Form.create()(Demo);
但是现在 class Demo extends Component {} Demo是类了，那句代码应该怎么写

**Comment by shenke119** [comment]
```javascript
constructor(props) {
        super(props);
        this.state = {
            
        };
        this.getFieldProps = props.form.getFieldProps;
        this.getFieldError = props.form.getFieldError;
        this.isFieldValidating = props.form.isFieldValidating;
        this.validateFields = props.form.validateFields;
        this.getFieldValue = props.form.getFieldValue;
 }
```
下面的this.props.form.getFieldsValue()  之类 改成this.getFieldsValue()
