### ISSUE TITLE
可搜索的Tree和DatePicker日期选择框的范围选择器IE浏览器中文字下沉问题

### ISSUE THREAD

**Issue by HollyHjj** [ant-design/ant-design#24449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/HollyHjj/Image/blob/master/DataPicker%20pic1.png](https://github.com/HollyHjj/Image/blob/master/DataPicker%20pic1.png)

### Steps to reproduce
在antd 的Table控件的列配置中，用日期选择框<RangePicker>实现数据筛选
//<Table>中startTime列的配置描述
  const getStartTimeColumnRangeSearchProps = (dataIndex) => ({
    //filterDropdown:可以自定义筛选菜单，此函数只负责渲染图层，需要自行编写各种交互
    filterDropdown: ({
      setSelectedKeys,
      selectedKeys,
      confirm,
      clearFilters,
    }) => (
      <div >
        <Space>
          <RangePicker
            showTime
            onChange={(dates, dateStrings) => {
              //设置<Table>中startTime列的<RangePicker>的状态
              setStartTimeRange((prev) => ({
                start: dateStrings[0],
                end: dateStrings[1],
              }));
              //更新onFilter的处理逻辑（必须setSelectedKeys，否则还是原来的onFilter逻辑）
              setSelectedKeys(
                dateStrings[0] && dateStrings[1]
                  ? [dateStrings[0], dateStrings[1]]
                  : []
              );
            }}
          />
          <Button
            type="primary"
            onClick={() => handleColumnSearch(selectedKeys, confirm, dataIndex)}
            icon={<SearchOutlined />}
            size="small"
          >
            筛选
          </Button>
          <Button
            onClick={() => handleColumnReset(clearFilters, dataIndex)}
            size="small"    
          >
            重置
          </Button>
        </Space>
      </div>
    ),
    //filterIcon:自定义 filter 图标
    filterIcon: (filtered) => (
      <Tooltip title="按时间范围筛选">
        <FilterFilled style={{ color: filtered ? "#1890ff" : undefined }} />
      </Tooltip>
    ),
    //onFilter:本地模式下，确定筛选的运行函数
    onFilter: (value, record) => {
      return (
        record[dataIndex] &&
        timeDeformat(record[dataIndex]) >= timeDeformat(startTimeRange.start) &&
        timeDeformat(record[dataIndex]) <= timeDeformat(startTimeRange.end)
      );
    },
  });

### What is expected?
文字正常显示，不要下沉

### What is actually happening?
文字下沉，文字下半部分被输入框挡住，显示不全

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | react@16.13.1 |
| System | win10 |
| Browser | IE 11.1217.17763.0 |

---
实际的结果图 https://github.com/HollyHjj/Image/blob/master/DataPicker%20pic1.png
https://github.com/HollyHjj/Image/blob/master/TreeSearch%20pic2.png

**Comment by zombieJ** [comment]
Closed since IE is out of latest support version. Sorry for delay.
