### ISSUE TITLE
按需引入css时，Popover不能正常工作

### ISSUE THREAD

**Issue by mrbook1122** [ant-design/ant-design#24452]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hl1wh?fontsize=14&hidenavigation=1&theme=dark&file=/index.js)
 

### What is expected?
popover正常工作

### What is actually happening?
当设置popover的触发事件为点击时，点击不能弹出窗口，鼠标移开再次点击才弹出窗口

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | windows10 18363.836 |
| Browser | chrome 81.0.4044.138 |

**Comment by afc163** [comment]
```diff
- import "antd/lib/button/style/index.css";
+ import "antd/lib/button/style";
```

or 

```diff
- import "antd/lib/button/style/index.css";
+ import "antd/dist/antd.css";
```
