### ISSUE TITLE
es6 写法中Form的使用, class Demo extends Component {} 形式，Demo = Form.create()(Demo);这句该怎么修改

### ISSUE THREAD

**Issue by Yhaojing** [ant-design/ant-design#2445]
node 6.2.1
npm 3.9.3

- antd 版本:1.6.5
- 操作系统及其版本：ios
- 浏览器及其版本:

#### 你做了什么？

以前写成let Demo = React.createClass({})形式时是Demo = Form.create()(Demo);
但是现在 class Demo extends Component {} Demo是类了，那句代码应该怎么写
#### 实际上的结果：
TypeError: Cannot read property 'getFieldProps' of undefined

**Comment by GrayChoi** [comment]
export default Form.create()(Demo);
或者
const DemoForm = Form.create()(Demo);
export default DemoForm;

只要名字和class名字不重复就行了

**Comment by jerson** [comment]
onSubmit={this.handleSubmit}

to 

onSubmit={this.handleSubmit.bind(this)}
with 
export default Form.create()(Demo);
