### ISSUE TITLE
[Upload] There is an area of blank below the <Upload listType="picture-card" /> in the <Form layout="vertical" /> when upload some pictures

### ISSUE THREAD

**Issue by HeskeyBaozi** [ant-design/ant-design#24455]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

在表单vertical布局下上传组件（照片墙模式）添加多张图片时下方会出现很大一片空白

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xiaoyanqitazujian-ant-design-demo-z64no)

### Steps to reproduce
添加三张以上的图片，表单布局vertical，上传组件是照片墙模式

### What is expected?
照片墙下没有很大一片空白

### What is actually happening?
照片墙下有很大一片空白

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | macOS |
| Browser | Chrome 81.0.4044.138 |

---
怀疑是换行样式有问题

**Comment by HeskeyBaozi** [comment]
复现操作录制视频 https://youtu.be/Ya5BD3gLOKs

**Comment by xrkffgg** [comment]
https://ant.design/components/upload-cn/#components-upload-demo-picture-card

测试了下这个 还好，没有出现你视频的情况。估计和你 Form 的定义有关吧。

**Comment by xrkffgg** [comment]
Sandboxes 发下就行，还整油管 🤣

**Comment by xrkffgg** [comment]
- 用你的例子 测不出

![2020-05-26 14 42 08](https://user-images.githubusercontent.com/29775873/82870890-44055400-9f63-11ea-8266-916bde9e9f83.gif)

**Comment by HeskeyBaozi** [comment]
> * 用你的例子 测不出
> 
> ![2020-05-26 14 42 08](https://user-images.githubusercontent.com/29775873/82870890-44055400-9f63-11ea-8266-916bde9e9f83.gif)

你可以试试传三张图片后，把中间的分栏线左拉使得两行变成一行试试：）

**Comment by HeskeyBaozi** [comment]
![drag](https://user-images.githubusercontent.com/15819224/83002997-49849c00-a040-11ea-9ea7-f17717fecb82.gif)

**Comment by xrkffgg** [comment]
😂😂😂  这不是人为的原因么
