### ISSUE TITLE
Upload组件 accept 设置问题

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2446]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：win7
- 浏览器及其版本: chrome 51

#### 你做了什么？

使用Upload上传excel, 设置accept的值为"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel"

#### 你期待的结果是：

upload弹出框中文件类为 xlsx, xls

#### 实际上的结果：

upload弹出框中文件类为 所有文件

#### 可重现的在线演示

无

是我accept设置错误吗？

**Comment by GrayChoi** [comment]
http://codepen.io/anon/pen/RRrgWp?editors=001
没有再现你这个问题

**Comment by codering** [comment]
我在ubuntu, 虚拟机win7下都没正常显示，也许是因为没装 windows office的原因
然后在同时的win10（装了office）上试了下，也不行.....

最后无奈只能设置 ` accept: '.xlsx' ` ，识别office2007以上版本

**Comment by lixuejiang** [comment]
要用后缀来限制
