### ISSUE TITLE
umi dva的项目升级4.2.5后全部变成英文

### ISSUE THREAD

**Issue by victorWuxz** [ant-design/ant-design#24464]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-tqhxo?file=/index.js:0-628)

### Steps to reproduce
更改umilocal配置，设置成中文，项目中所有的日期组件和无数据提示都是英文

### What is expected?
通过umi的local配置可以设置成中文

### What is actually happening?
local配置成中文后还是英文

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.12 |
| System | mac |
| Browser | chrome80 |

---
使用ConfigProvider也不可以

**Comment by afc163** [comment]
请提交到 umijs 下。

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-mvgl7?file=/index.js
