### ISSUE TITLE
Menu.Item onClick not closing Menu properly

### ISSUE THREAD

**Issue by dbousamra** [ant-design/ant-design#24462]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-cartwright-8ej4o?file=/index.js)

### Steps to reproduce
Menu.Item that is not a child of a Menu directly (but instead has it's props passed in), with an onClick handler opening a modal.

### What is expected?
When you open a modal, the menu item should disappear.

### What is actually happening?
It does not disappear

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
Don't put Modal inside Menu.

**Comment by dbousamra** [comment]
Okay. What should I do instead here?
