### ISSUE TITLE
动态增加Table固定列会出现列遮盖或空白间隙

### ISSUE THREAD

**Issue by wes0310** [ant-design/ant-design#24466]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/flamboyant-rain-lvd0i)

### Steps to reproduce
点击addAfter按钮添加固定列,会有遮盖现象
点击addBefor按钮添加固定列,正常

### What is expected?
固定列顺序不影响表格显示

### What is actually happening?
固定列顺序必须放在数组最前面，才能不出现遮盖错位或空白间隙

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.12.0 |
| System | Windows 10 专业版 |
| Browser | chrome 72.0.3626.96 |

**Comment by afc163** [comment]
按照目前的设计，`fix: 'left'` 的列确实需要放在前面。
