### ISSUE TITLE
Rewrite [Real project with umi and dva]

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#24474]
Drop `dva` and use https://github.com/ant-design/ant-design-pro/issues/6023

- [ ] mocks
- [ ] services
- [ ] `useModel`
- [ ] `useRequest`

https://ant.design/docs/react/practical-projects
https://ant.design/docs/react/practical-projects-cn

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/82893744-14b30f00-9f84-11ea-8e23-eb2c00f83cd4.png)

竟然没有我

**Comment by gautamsingal** [comment]
@afc163 is this still open and can you please elaborate a bit on the issue?
