### ISSUE TITLE
Form min validate error

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#24472]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/biaodanfangfadiaoyong-ant-design-demo-666gd?file=/index.js)

### Steps to reproduce
input `-1`

### What is expected?
'note' cannot be less than 0

### What is actually happening?

'note' is not a valid undefined
'note' cannot be less than 0

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | latest |
| System | windows  |
| Browser | chrome |

**Comment by hengkx** [comment]
@afc163 在邀请下，过期了，在垃圾箱 今天才看到
![image](https://user-images.githubusercontent.com/8358236/82891557-8721f000-9f80-11ea-9253-da35392b6a66.png)

**Comment by afc163** [comment]
done

**Comment by hengkx** [comment]
这两天眼睛不太好 要休息休息了 看一会电脑就眼睛疼

**Comment by hengkx** [comment]
https://codesandbox.io/s/biaodanfangfadiaoyong-ant-design-demo-07uqc?file=/index.js

是我用错了吗？要加上`type=number`
