### ISSUE TITLE
Checkbox.Group在Form中defaultValue失效

### ISSUE THREAD

**Issue by distance321** [ant-design/ant-design#24470]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
```
const options = [
  { label: 'Apple', value: 'Apple' },
  { label: 'Pear', value: 'Pear' },
  { label: 'Orange', value: 'Orange' },
]
  const layout = {
    labelCol: { span: 0 },
    wrapperCol: { span: 24 },
  };
const [form] = Form.useForm();

      <Form
        name="basic"
        {...layout}
        onFinish={onFinish}
      >
        <Form.Item label="" name="fruit">
          <Checkbox.Group options={options} defaultValue={['Apple']} />
        </Form.Item>
      </Form>
```

### What is expected?
Checkbox默认选中Apple

### What is actually happening?
无法默认选中

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.8.6 |
| System | macOs 10.15.4 |
| Browser | Google Chrome  83.0.4103.61 |

---
如果将Form.Item的name至空，Checkbox就可以默认选中，但是不满足表单需求

**Comment by afc163** [comment]
Try `initailValues`
