### ISSUE TITLE
FormItem is not defined

### ISSUE THREAD

**Issue by gwuhaolin** [ant-design/ant-design#2448]
#### 本地环境

- antd 版本:1.6.5
- 操作系统及其版本：macOS
- 浏览器及其版本: chrome canary

#### 你做了什么？
我使用typescript来写react应用，在引入FormItem时是这样的
```
import {Form, Input, Button, FormItem} from "antd";
```
结果报错：FormItem is not defined
在ant-design的index.d.ts文件里有这样的声明：
```
export class FormItem extends React.Component<FormItemProps, {}> {
}
```
实际上antd是没有直接export出FormItem。

所以导致使用typescript时报错，解决方案可以是：
- 修改index.d.ts 文件 去掉`export class FormItem`
- 让antd直接导出 FormItem

**Comment by afc163** [comment]
我们正在用 ts 重写，旧的 index.d.ts 未来会废弃：https://github.com/ant-design/ant-design/issues/1846

这个问题欢迎直接给我们 PR：

1. 修改 1.x-stable 分支上的：index.d.ts
2. 或修改 master 上的 FormItem.tsx

**Comment by gwuhaolin** [comment]
我发现master所有组件已经用typescript重写，为什么不直接用tsc为每个组件生成d.ts文件发布到npm而是手写一份index.d.ts呢？

**Comment by afc163** [comment]
index.d.ts 是改造前社区提供的，typescript 的重写还没有完成，完成后会生成这个文件。

#1846 里应该已经说得很清楚了。
