### ISSUE TITLE
Select Tag Mode "Create New Label"

### ISSUE THREAD

**Issue by roeljohn** [ant-design/ant-design#24488]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Hi,

Is this possible https://prnt.sc/sogqbj
So when create a new tag mode instead of the same test appear in below I will replace that current text with "Create New Label"

Create New Label/Tag: Tag/Label Name

### What does the proposed API look like?
Right now I have notFoundContent={'Create New Label'} but the problem is that when I typing it replace the text I current typing

**Comment by afc163** [comment]
It is hard to implement https://prnt.sc/sogqbj now.

**Comment by roeljohn** [comment]
@afc163 how about this. I having trouble implemeting create tag in api because the onSelect need to trigger first before the onChange but it sometimes onChange trigger having an error because onSelect not trigger.
`<Select
                    showSearch
                    mode="tags"
                    style={{ width: 200 }}
                    defaultValue={this.props.label}
                    onSearch={(data) => console.log('onSearch', data)}
                    placeholder="Select Label"
                    optionFilterProp="children"
                    filterOption={(input, option) =>
                        option.props.children.toString().toLowerCase().indexOf(input.toString().toLowerCase()) >= 0
                    }
                    notFoundContent={'Create New Label'}
                    onSelect={(id) => this.props.createLabel(id)}
                    onChange={(id) => {
                        this.props.assignLabel(id);
                    }}
                >
                    {label`
![image](https://user-images.githubusercontent.com/8347743/83255176-8a1c1b00-a1e2-11ea-8ce5-f83d0f5a596e.png)
