### ISSUE TITLE
Custom attributes on Select are added to inner input element

### ISSUE THREAD

**Issue by florianMo** [ant-design/ant-design#24481]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/custom-attribute-forwarded-to-input-fx5ok?file=/src/App.js)

### Steps to reproduce
Setup a Select with a custom attribute (data-*) and some options, allowing search.

### What is expected?
Custom attribute should not be given to inner input element since it could be supposed to be unique in page.

### What is actually happening?
The input element used to perform search also have the custom attribute.

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.3.1 |
| System | Linux Mint 19.3 |
| Browser | Chrome 83 |

---
There might be a good reason for this behaviour, but I think this is mostly unwanted. I only tried with data-testid attribute. It might also happen to other form elements.

**Comment by AceNorth** [comment]
+1 to this. Makes testing more complicated than it needs to be, because you'll render multiple components with the same `data-testid` attribute when you should only be rendering one.

**Comment by florianMo** [comment]
Exactly. As a workaround for react-testing-library, where possible, I put `data-testid` attribute on parent element, so my tests are not impacted. Otherwise replacing `getByTestId` by `getAllByTestId(...)[0]` works fine.

**Comment by zombieJ** [comment]
It should only patch for `aria-*` props.

**Comment by jarretmoses** [comment]
I have the same issue. I believe it is related to https://github.com/react-component/select/commit/7d228321c043d1549e1922b3710eaee8ec380b7c
