### ISSUE TITLE
Steps break if the text-align is not left

### ISSUE THREAD

**Issue by spluxx** [ant-design/ant-design#24484]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://26dnu.csb.app/](https://26dnu.csb.app/)

### Steps to reproduce
Set text-align to anything other than left anywhere above the dom tree.

### What is expected?
It should look OK - maybe shifting horizontally.

### What is actually happening?
The alignment between the steps and lines break.

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.0 |
| System | macOS 10.15.2 |
| Browser | Chrome 81.0.4044.138 (Official Build) (64-bit) |

---
It's easy to work around by having an immediate parent with text-align set to left. However, I think it would make more sense to have this built-in to the Steps component itself, if it depends heavily on the fact that text-align set to left to work as expected.

**Comment by coskunuyar** [comment]
https://github.com/ant-design/ant-design/pull/24486/commits/0d0da2141df171955efc1138e763bd326884c3c8

I hope thats will fix the issue.

**Comment by yoyo837** [comment]
Similar to the discussion of #24228
