### ISSUE TITLE
codesandbox can't open

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#24493]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
click codesandbox 

### What is expected?
open

### What is actually happening?
```
{
"errors": {
"detail": [
"Internal server error"
]
}
}
```

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | latest |
| System | windows  |
| Browser | chrome |

**Comment by afc163** [comment]
貌似好了。
