### ISSUE TITLE
DatePicker(Today ) text not localizing 

### ISSUE THREAD

**Issue by AbhijeetGaware** [ant-design/ant-design#24497]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

### Steps to reproduce
We are trying to localize DatePicker based on browser locale

<DatePicker locale={window.navigator.language}/> 

It will be good if can override today text with parameter

Eg.,  <DatePicker todayText={"Manual Today}/> // We can take care of localizing using react-intil if this parameter exist

We tried below work-around based on antd recommended localization. It is not working for all countries (Eg., Ireland - ga)

import zh_CN from 'antd/lib/date-picker/locale/zh_CN';
<DatePicker locale={zh_CN}/>  Date Picker Calender localizing perfectly.  // 

### What is expected?
DatePicker should have todayText attribute to override/localize the value

### What is actually happening?
Unable to localize Today text for all required countries part of our requirement

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.13.0 |
| System | MacBookPro |
| Browser | Chrome 81.0.4044.138  |

**Comment by lilifan1598** [comment]
![image](https://user-images.githubusercontent.com/39824392/82993192-cdd02280-a032-11ea-8e41-4e3a6fd30246.png)

so am i

**Comment by AbhijeetGaware** [comment]
@ant-design-bot 
 i provided sample code  
https://codesandbox.io/embed/antd-reproduction-template-x294g?fontsize=14&hidenavigation=1&theme=dark

**Comment by yoyo837** [comment]
Your link is not version 3.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-foi4j?file=/index.js

**Comment by AbhijeetGaware** [comment]
> Your link is not version 3.

i am using antd version 3.26.17

**Comment by AbhijeetGaware** [comment]
> https://codesandbox.io/s/antd-reproduction-template-foi4j?file=/index.js

https://codesandbox.io/embed/antd-reproduction-template-46ilm?fontsize=14&hidenavigation=1&theme=dark

**Comment by yoyo837** [comment]
A set of localization is indecomposable.

**Comment by AbhijeetGaware** [comment]
> indecomposable.

i need to change today text for few countries (eg.Ireland) rest of few countries working fine

**Comment by yoyo837** [comment]
Maybe your should add `en_IE` locale for antd

**Comment by AbhijeetGaware** [comment]
> Maybe you should add `en_IE` locale for `antd`

i have tried that its shows error antd cant find module
<img width="604" alt="Screenshot 2020-05-27 at 4 48 05 PM" src="https://user-images.githubusercontent.com/56472463/83013005-e5f77000-a039-11ea-9f36-2576685e07ac.png">

**Comment by yoyo837** [comment]
There is no i18n of en_IE currently, need you to help add it.

**Comment by AbhijeetGaware** [comment]
> There is no i18n of `en_IE` currently, need you to help add it.

how to change  (Today) text will you provide any parameter for (irish),(ireland)

**Comment by AbhijeetGaware** [comment]
> > There is no i18n of `en_IE` currently, need you to help add it.
> 
> how to change (Today) text will you provide any parameter for (irish),(ireland)

i need to locale for irish (ga_IE) and need to work for antd

**Comment by yoyo837** [comment]
There is no internationalization of these areas yet, welcome to send us PR to add them.

**Comment by AbhijeetGaware** [comment]
@yoyo837  i need to translate Today text when it will be added will you let me know 
or you can provide me how to override today text manually for DatePicker

**Comment by AbhijeetGaware** [comment]
https://codesandbox.io/embed/antd-reproduction-template-46ilm?fontsize=14&hidenavigation=1&theme=dark

i was trying to do what you said please see the once Thank You

**Comment by yoyo837** [comment]
Do you mean that you don't know how to contribute an i18n locale？

**Comment by AbhijeetGaware** [comment]
> Do you mean that you don't know how to contribute an i18n locale？

yes i know it and i tried it but still its not taking locale in DatePicker

**Comment by AbhijeetGaware** [comment]
<img width="449" alt="Screenshot 2020-05-27 at 5 34 35 PM" src="https://user-images.githubusercontent.com/56472463/83016969-6de07880-a040-11ea-86c8-824cbcb6d9d2.png">

**Comment by yoyo837** [comment]
What is the output of navigator.language on your computer?

**Comment by AbhijeetGaware** [comment]
> What is the output of navigator.language on your computer?

what i selected languages on browser locale its properly working fine only i am stuck with irish

**Comment by yoyo837** [comment]
https://ant.design/docs/react/i18n#Adding-newplanguage 
If your language is not in above list, feel free to create a locale package based on [en_US](https://github.com/ant-design/ant-design/blob/master/components/locale/en_US.tsx) and send us a pull request. This [Azerbaijani](https://github.com/ant-design/ant-design/pull/21387) language PR could be a sample.

**Comment by yoyo837** [comment]
You need to send PR to [rc-picker](https://github.com/react-component/picker) like react-component/picker#24 and [rc-pagination](https://github.com/react-component/pagination) like react-component/pagination#249 at first.

**Comment by AbhijeetGaware** [comment]
> You need to send PR to [rc-picker](https://github.com/react-component/picker) like [react-component/picker#24](https://github.com/react-component/picker/pull/24) and [rc-pagination](https://github.com/react-component/pagination) like [react-component/pagination#249](https://github.com/react-component/pagination/pull/249) at first.

@yoyo837 okay Thank you

**Comment by AbhijeetGaware** [comment]
@yoyo837 https://github.com/react-component/picker/pull/79

**Comment by AbhijeetGaware** [comment]
https://github.com/ant-design/ant-design/pull/24586

**Comment by AbhijeetGaware** [comment]
@yoyo837 https://github.com/react-component/pagination/pull/273

**Comment by AbhijeetGaware** [comment]
> https://ant.design/docs/react/i18n#Adding-newplanguage
> If your language is not in above list, feel free to create a locale package based on [en_US](https://github.com/ant-design/ant-design/blob/master/components/locale/en_US.tsx) and send us a pull request. This [Azerbaijani](https://github.com/ant-design/ant-design/pull/21387) language PR could be a sample.

@yoyo837  Some checks were not succesfull . i have added 2 file from rc-picker in ant-design component so should i have to delete those file or i have to raise pr again for ant-design

**Comment by yoyo837** [comment]
Wait for the PR of the Picker and Pagination to merge and release a new version.
