### ISSUE TITLE
antd3.x的表格使用scroll={{x:1900}}时，如果列表内容行很宽，在WIndow里左右滚动需要滚动在列表底部才能进行左右滚动

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-design#24500]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js:0-2696)

### Steps to reproduce
搞一个列表数据多的，加上scroll={{x:1900}}属性，在Windows下左右操作

### What is expected?
windows下不用滚动到列表底部也可以左右操作（例如：窗口底部加滚动条左右操作控制表格左右操作）

### What is actually happening?
windows下需要滚动到列表底部才可以左右操作

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | Windows |
| Browser | 版本 83.0.4103.61（正式版本） （64 位) |

---
import React from "react";
import ReactDOM from "react-dom";
import { Table, version } from "antd";
import "antd/dist/antd.css";
import "./index.css";
const columns = [
  {
    title: 'Full Name',
    width: 100,
    dataIndex: 'name',
    key: 'name',
    fixed: 'left',
  },
  {
    title: 'Age',
    width: 100,
    dataIndex: 'age',
    key: 'age',
    fixed: 'left',
  },
  { title: 'Column 1', dataIndex: 'address', key: '1' },
  { title: 'Column 2', dataIndex: 'address', key: '2' },
  { title: 'Column 3', dataIndex: 'address', key: '3' },
  { title: 'Column 4', dataIndex: 'address', key: '4' },
  { title: 'Column 5', dataIndex: 'address', key: '5' },
  { title: 'Column 6', dataIndex: 'address', key: '6' },
  { title: 'Column 7', dataIndex: 'address', key: '7' },
  { title: 'Column 8', dataIndex: 'address', key: '8' },
  {
    title: 'Action',
    key: 'operation',
    fixed: 'right',
    width: 100,
    render: () => <a>action</a>,
  },
];

const data = [
  {
    key: '1',
    name: 'John Brown',
    age: 32,
    address: <div style={{height:40}}>asdasd</div>,
  },
  {
    key: '2',
    name: 'Jim Green',
    age: 40,
    address: 'London Park',
  },
  {
    key: '3',
    name: 'John Brown',
    age: 32,
    address: 'New York Park',
  },
  {
    key: '4',
    name: 'Jim Green',
    age: 40,
    address: 'London Park',
  },
  {
    key: '11',
    name: 'John Brown',
    age: 32,
    address: 'New York Park',
  },
  {
    key: '22',
    name: 'Jim Green',
    age: 40,
    address: 'London Park',
  },
  {
    key: '33',
    name: 'John Brown',
    age: 32,
    address: 'New York Park',
  },
  {
    key: '441',
    name: 'Jim Green',
    age: 40,
    address: 'London Park',
  },
  {
    key: '111',
    name: 'John Brown',
    age: 32,
    address: 'New York Park',
  },
  {
    key: '221',
    name: 'Jim Green',
    age: 40,
    address: 'London Park',
  },
  {
    key: '331',
    name: 'John Brown',
    age: 32,
    address: 'New York Park',
  },
  {
    key: '441',
    name: 'Jim Green',
    age: 40,
    address: 'London Park',
  },
  {
    key: '112',
    name: 'John Brown',
    age: 32,
    address: 'New York Park',
  },
  {
    key: '222',
    name: 'Jim Green',
    age: 40,
    address: 'London Park',
  },
  {
    key: '323',
    name: 'John Brown',
    age: 32,
    address: 'New York Park',
  },
  {
    key: '424',
    name: 'Jim Green',
    age: 40,
    address: <div style={{height:40}}>asdasd</div>,
  },
];
ReactDOM.render(
  <div className="App">
    <h1>antd version: {version}</h1>
   <Table 
   columns={columns}
    dataSource={data} 
   scroll={{ x: 1300 }}
   pagination={{pageSize:20}} />
  </div>,
  document.getElementById("root")
);

**Comment by yoyo837** [comment]
See #21584 and #24131
