### ISSUE TITLE
在List.Item中Col生效，但是在Col中使用Typography.Text ellipsis>不能正确的省略文字

### ISSUE THREAD

**Issue by HunterHeroHan** [ant-design/ant-design#24503]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-meadow-slkm8)

### Steps to reproduce
在List.Item中Co栅格l生效，但是在Col中使用Typography.Text ellipsis>不能正确的省略文字。

### What is expected?
可以正常使用ellipsis

### What is actually happening?
不能正常使用ellipsis

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.12.0 |
| System | contos 7.2 |
| Browser | Google Chrome 81.0.4044.138 |

**Comment by xilihuasi** [comment]
I'll handle this and add a demo in ellipsis block.Should I change the `Multiple line ellipsis support` description into `ellipsis support` in the ellipsis demo block ,since the scene is not just multiple line?

**Comment by HunterHeroHan** [comment]
.ant-list-item-meta {
      width: -webkit-fill-available;
    }

    .ant-list-item-meta-content {
      width: -webkit-fill-available;
    }

    .ant-typography-ellipsis {
      width: -webkit-fill-available;
    }

我目前是在less里面加了这些，使它能够正常显示

**Comment by afc163** [comment]
Sure. @xilihuasi

**Comment by zombieJ** [comment]
It's not a bug. `Typography.Text` is a `inline-block` component which should set width for ellipsis. We should update doc for this.
