### ISSUE TITLE
pagination onChange not called when the page size changed

### ISSUE THREAD

**Issue by dubiao** [ant-design/ant-design#24501]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://5olx3.csb.app/](https://5olx3.csb.app/)

### Steps to reproduce
import React from "react";
import ReactDOM from "react-dom";
import { List, Card, version } from "antd";
import "antd/dist/antd.css";
import "./index.css";

ReactDOM.render(
  <div className="App">
    <h1>antd version: {version}</h1>
    <List
      dataSource={new Array(100).fill(100)}
      pagination={{
        position: "both",
        pageSize: 20,
        showSizeChanger: true,
        onChange: (page, pageSize) => {
          console.warn("onChange", page, pageSize);
        }
      }}
      renderItem={(item, i) => {
        return (
          <List.Item>
            <Card>
              <h2>[{i   1}]</h2>
            </Card>
          </List.Item>
        );
      }}
    />
  </div>,
  document.getElementById("root")
);

Chagne the page size with sizeChanger

### What is expected?
onChange called and console warns two number.

### What is actually happening?
Nothing. onChange of pagination not called.

| Environment | Info |
|---|---|
| antd | 4.0.2 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome any |

---
If I change the page, onChange calls. But if I change page size, onChange not called.

**Comment by fireairforce** [comment]
I will work on it~
