### ISSUE TITLE
Select Tag 模式没有显示光标

### ISSUE THREAD

**Issue by FrancisKong** [ant-design/ant-design#24505]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vtur7)

### Steps to reproduce
点击 Select 输入框

### What is expected?
应该出现光标，这是 Antd 文档上的截图，但在 CodeSandBox 打开后就没有光标了
<img width="334" alt="Screen Shot 2020-05-27 at 18 50 16" src="https://user-images.githubusercontent.com/7656698/83010562-05e35f80-a04b-11ea-922e-1f26538f419c.png">

### What is actually happening?
没有出现光标

<img width="648" alt="Screen Shot 2020-05-27 at 18 49 50" src="https://user-images.githubusercontent.com/7656698/83010515-f49a5300-a04a-11ea-87bc-f9a3d65e125c.png">

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | macOS |
| Browser | Chrome 83 |

**Comment by afc163** [comment]
<img width="297" alt="image" src="https://user-images.githubusercontent.com/507615/83020338-ea805080-a05a-11ea-931f-be992974a042.png">

有光标。

**Comment by mattcarlotta** [comment]
I just ran into the same issue. To help narrow this down... 

This issue only appears to impact Chrome, as both Firefox (latest) and Safari (latest) correctly display the cursor when initially focused. The cursor is present in v3.26.17 and v4.0.0-alpha.0, but in v4.0.0-alpha.10+ it becomes invisible. Typing something into the field reveals the cursor, however, if you delete the text, then it becomes invisible again. It also appears that typing 2-3 characters in Chrome results in some slightly overflowed text.

Chrome:
https://youtu.be/JkFyiTv3fFM

Firefox:
https://youtu.be/9c7X9-H2Was

**Comment by afc163** [comment]
Fixed in #24631
