### ISSUE TITLE
Select中加入全选按钮

### ISSUE THREAD

**Issue by xiamidong** [ant-design/ant-design#2451]
### 本地环境

- antd 版本:1.3.2
- 操作系统及其版本: mac 
- 浏览器及其版本:google

### 我的需求

 >  我想在Select中加入全选按钮，应该怎么做？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2320

Try to ask Usage problems in StackOverflow.

**Comment by afc163** [comment]
Try use controlled prop `value`
