### ISSUE TITLE
antd spin spinning={false} causes the icon to disappear

### ISSUE THREAD

**Issue by mx2323** [ant-design/ant-design#24517]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/mx2323/pen/bGVyJYJ?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fspin%2F](https://codepen.io/mx2323/pen/bGVyJYJ?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fspin%2F)

### Steps to reproduce
add spinning={false} to the props of Antd.Spin

### What is expected?
should show the spin icon but not spin. 

### What is actually happening?
the icon disappears

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.0 |
| System | mac os x  |
| Browser | chrome  |

---
i like how the colors on the antd spin animates. please keep that when its not spinning. just dont rotate it!

**Comment by afc163** [comment]
It is expected behavior, there is not spinner don't rotate in antd now.
