### ISSUE TITLE
DataPicker locale name months and dateweeks not working

### ISSUE THREAD

**Issue by matteoabbruzzo** [ant-design/ant-design#24515]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/date-format-ant-design-demo-fz0tj?file=/index.js)

### Steps to reproduce
Antd 4.2.5 depends of rc-picker with a wrong dependecy of moment 2.2.4

### What is expected?
To see months and days in the correct language

### What is actually happening?
Months and days are in the default language

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Please upgrade to moment 2.26.0: https://codesandbox.io/s/date-format-ant-design-demo-i7cqq?file=/package.json

**Comment by neo20** [comment]
> Please upgrade to moment 2.26.0: https://codesandbox.io/s/date-format-ant-design-demo-i7cqq?file=/package.json

the problem still exists. weekday and month are showed in English, rather than Chinese

Reproduction link
https://codesandbox.io/s/date-format-ant-design-demo-swjck?file=/index.js

**Comment by afc163** [comment]
@neo20 https://codesandbox.io/s/date-format-ant-design-demo-pkpom?file=/index.js
