### ISSUE TITLE
Table selectedRowKeys 数据无缓存

### ISSUE THREAD

**Issue by tdida** [ant-design/ant-design#24527]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xuanzehecaozuo-ant-design-demo-8t1wt?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
选中表格 row，切换页码，选中表格 row，selectedRowKeys 数据没有缓存上次页码的选中项

### What is expected?
切换页码，selectedRowKeys 数据缓存上次页码的选中项

### What is actually happening?
切换页码，selectedRowKeys 数据没有缓存上次页码的选中项

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | macOS 10.15.5 |
| Browser | chrome 84.0.4147.21 |

**Comment by afc163** [comment]
Duplicate of #7942

**Comment by tdida** [comment]
@afc163 是 selectedRowKeys 不是 selectedRow

**Comment by afc163** [comment]
后端分页的话是选择列数据留不住的，前端分页可以，更换 dataSource 都会把不在当前数据里面的 selectedRowKeys 清掉（因为 Table 区别不了换页还是重新刷新了数据）。

你需要把一个 selectedRowKeys 放在 state 里面存起来。

**Comment by tdida** [comment]
👌

**Comment by WanAn0902** [comment]
> 👌

请问您是这么解决的？如果把每次选择的数据放在state里，可是要怎么区分是选中还是取消呢，只能不停的往state里push新的选中数据

**Comment by ChengYiFan** [comment]
> 👌



> > 👌
> 
> 请问您是这么解决的？如果把每次选择的数据放在state里，可是要怎么区分是选中还是取消呢，只能不停的往state里push新的选中数据

同问

**Comment by afc163** [comment]
> 请问您是这么解决的？如果把每次选择的数据放在state里，可是要怎么区分是选中还是取消呢，只能不停的往state里push新的选中数据

rowSelection 里面有个 onSelect，可以区分。

**Comment by tdida** [comment]
@WanAn0902 通过 onSelect 和 onSelectAll 处理

**Comment by baozouai** [comment]
以下是我的解决方案
这里是自定义hooks => useTableSelect.js
``` javascript
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { message } from 'antd';

export default function useTableSelect(props) {
  const {
    // 数据的key
    rowKey,
    // 是否多选
    isSelectMore,
    // 最大可选多少条
    maxSelected,
  } = props;

  const {
    // 复选框配置
    getCheckboxProps,
    // 选择回调
    selectCallback,
  } = props;

  // 选择数据
  const [select, setSelect] = useState({
    selectedRowKeys: [],
    selectedRows: [],
  });

  // 行选择
  function onSelect(record) {
    // 判断是否有选择框配置
    if (getCheckboxProps) {
      const { disabled } = getCheckboxProps(record);
      // disabled为true则禁止选择
      if (disabled) {
        return;
      }
    }
    let selectedRowKeysTemp;
    let selectedRowsTemp;
    // 这里不能用 const { selectedRowKeys, selectedRows } = state; 否则点击该行页面不render
    if (isSelectMore) {
      selectedRowKeysTemp = [...select.selectedRowKeys];
      selectedRowsTemp = [...select.selectedRows];
      const selectedKey = record[rowKey];
      const index = selectedRowKeysTemp.indexOf(selectedKey);
      // 如果已存在 则去掉
      if (index >= 0) {
        selectedRowKeysTemp.splice(index, 1);
        selectedRowsTemp.splice(index, 1);
      } else {
        // 否则加入
        selectedRowKeysTemp.push(selectedKey);
        selectedRowsTemp.push(record);
      }
      if (!checkMaxLength(selectedRowKeysTemp)) {
        // 判断是否超过最大可选数
        return false;
      }
    } else {
      selectedRowKeysTemp = [record[rowKey]];
      selectedRowsTemp = [record];
    }
    selectCallbacks(selectedRowKeysTemp, selectedRowsTemp);
  }
  // 全选回调
  function onSelectAll(selected, selectedRows, changeRows) {
    let selectedRowKeysTemp = [...select.selectedRowKeys];
    let selectedRowsTemp = [...select.selectedRows];
    const changedKeys = changeRows.map(row => row[rowKey]);
    // 全选
    if (selected) {
      // 过滤掉已选的
      selectedRowKeysTemp = selectedRowKeysTemp.concat(
        changedKeys.filter(key => !selectedRowKeysTemp.includes(key)),
      );
      selectedRowsTemp = selectedRowsTemp.concat(
        changeRows.filter(row => !select.selectedRowKeys.includes(row[rowKey])),
      );
      if (!checkMaxLength(selectedRowKeysTemp)) {
        // 判断是否超过最大可选数
        return false;
      }
    } else {
      // 全不选
      // 去掉已选的
      selectedRowKeysTemp = selectedRowKeysTemp.filter(key => !changedKeys.includes(key));
      selectedRowsTemp = selectedRowsTemp.filter(row => !changedKeys.includes(row[rowKey]));
    }
    selectCallbacks(selectedRowKeysTemp, selectedRowsTemp);
  }
  // 检查是否超过最大可选数量
  function checkMaxLength(selectedRowsKeys) {
    if (maxSelected && selectedRowsKeys.length > maxSelected) {
      message.warning(`最多只能选择${maxSelected}条数据`, 1.5);
      return false;
    }
    return true;
  }
  // 选择回调
  function selectCallbacks(selectedRowKeys = [], selectedRows = []) {
    setSelect({ selectedRowKeys, selectedRows });
    selectCallback(isSelectMore ? selectedRowKeys : selectedRowKeys[0], selectedRows);
  }
  // 清空选择
  function clearSelect() {
    selectCallbacks([], []);
  }
  return {
    ...select,
    onSelect,
    onSelectAll,
    clearSelect,
    selectCallbacks,
  };
}

useTableSelect.defaultProps = {
  rowKey: 'id',
  isSelectMore: true,
  getCheckboxProps: () => {},
  selectCallback: () => {},
};

useTableSelect.propTypes = {
  rowKey: PropTypes.string,
  isSelectMore: PropTypes.bool,
  getCheckboxProps: PropTypes.func,
  selectCallback: PropTypes.func,
};
```

然后在你的列表中引入

```javascript
import useTableSelect from '@/hooks/useTableSelect';
.....
const {
    selectedRowKeys,
    selectedRows,
    onSelect,
    onSelectAll,
    clearSelect,
    selectCallbacks,
  } = useTableSelect({
    rowKey,
    isSelectMore,
    maxSelected,
    getCheckboxProps,
    selectCallback,
  });

...
tableProps.rowSelection = {
      selectedRowKeys,
      onSelect,
      onSelectAll,
      type: isSelectMore ? 'checkbox' : 'radio',
      columnWidth: 30,
      getCheckboxProps,
    };
...
.....


```

**Comment by damaohub** [comment]
> 以下是我的解决方案
> 这里是自定义hooks => useTableSelect.js
> 
> ```js
> import React, { useState } from 'react';
> import PropTypes from 'prop-types';
> import { message } from 'antd';
> 
> export default function useTableSelect(props) {
>   const {
>     // 数据的key
>     rowKey,
>     // 是否多选
>     isSelectMore,
>     // 最大可选多少条
>     maxSelected,
>   } = props;
> 
>   const {
>     // 复选框配置
>     getCheckboxProps,
>     // 选择回调
>     selectCallback,
>   } = props;
> 
>   // 选择数据
>   const [select, setSelect] = useState({
>     selectedRowKeys: [],
>     selectedRows: [],
>   });
> 
>   // 行选择
>   function onSelect(record) {
>     // 判断是否有选择框配置
>     if (getCheckboxProps) {
>       const { disabled } = getCheckboxProps(record);
>       // disabled为true则禁止选择
>       if (disabled) {
>         return;
>       }
>     }
>     let selectedRowKeysTemp;
>     let selectedRowsTemp;
>     // 这里不能用 const { selectedRowKeys, selectedRows } = state; 否则点击该行页面不render
>     if (isSelectMore) {
>       selectedRowKeysTemp = [...select.selectedRowKeys];
>       selectedRowsTemp = [...select.selectedRows];
>       const selectedKey = record[rowKey];
>       const index = selectedRowKeysTemp.indexOf(selectedKey);
>       // 如果已存在 则去掉
>       if (index >= 0) {
>         selectedRowKeysTemp.splice(index, 1);
>         selectedRowsTemp.splice(index, 1);
>       } else {
>         // 否则加入
>         selectedRowKeysTemp.push(selectedKey);
>         selectedRowsTemp.push(record);
>       }
>       if (!checkMaxLength(selectedRowKeysTemp)) {
>         // 判断是否超过最大可选数
>         return false;
>       }
>     } else {
>       selectedRowKeysTemp = [record[rowKey]];
>       selectedRowsTemp = [record];
>     }
>     selectCallbacks(selectedRowKeysTemp, selectedRowsTemp);
>   }
>   // 全选回调
>   function onSelectAll(selected, selectedRows, changeRows) {
>     let selectedRowKeysTemp = [...select.selectedRowKeys];
>     let selectedRowsTemp = [...select.selectedRows];
>     const changedKeys = changeRows.map(row => row[rowKey]);
>     // 全选
>     if (selected) {
>       // 过滤掉已选的
>       selectedRowKeysTemp = selectedRowKeysTemp.concat(
>         changedKeys.filter(key => !selectedRowKeysTemp.includes(key)),
>       );
>       selectedRowsTemp = selectedRowsTemp.concat(
>         changeRows.filter(row => !select.selectedRowKeys.includes(row[rowKey])),
>       );
>       if (!checkMaxLength(selectedRowKeysTemp)) {
>         // 判断是否超过最大可选数
>         return false;
>       }
>     } else {
>       // 全不选
>       // 去掉已选的
>       selectedRowKeysTemp = selectedRowKeysTemp.filter(key => !changedKeys.includes(key));
>       selectedRowsTemp = selectedRowsTemp.filter(row => !changedKeys.includes(row[rowKey]));
>     }
>     selectCallbacks(selectedRowKeysTemp, selectedRowsTemp);
>   }
>   // 检查是否超过最大可选数量
>   function checkMaxLength(selectedRowsKeys) {
>     if (maxSelected && selectedRowsKeys.length > maxSelected) {
>       message.warning(`最多只能选择${maxSelected}条数据`, 1.5);
>       return false;
>     }
>     return true;
>   }
>   // 选择回调
>   function selectCallbacks(selectedRowKeys = [], selectedRows = []) {
>     setSelect({ selectedRowKeys, selectedRows });
>     selectCallback(isSelectMore ? selectedRowKeys : selectedRowKeys[0], selectedRows);
>   }
>   // 清空选择
>   function clearSelect() {
>     selectCallbacks([], []);
>   }
>   return {
>     ...select,
>     onSelect,
>     onSelectAll,
>     clearSelect,
>     selectCallbacks,
>   };
> }
> 
> useTableSelect.defaultProps = {
>   rowKey: 'id',
>   isSelectMore: true,
>   getCheckboxProps: () => {},
>   selectCallback: () => {},
> };
> 
> useTableSelect.propTypes = {
>   rowKey: PropTypes.string,
>   isSelectMore: PropTypes.bool,
>   getCheckboxProps: PropTypes.func,
>   selectCallback: PropTypes.func,
> };
> ```
> 
> 然后在你的列表中引入
> 
> ```js
> import useTableSelect from '@/hooks/useTableSelect';
> .....
> const {
>     selectedRowKeys,
>     selectedRows,
>     onSelect,
>     onSelectAll,
>     clearSelect,
>     selectCallbacks,
>   } = useTableSelect({
>     rowKey,
>     isSelectMore,
>     maxSelected,
>     getCheckboxProps,
>     selectCallback,
>   });
> 
> ...
> tableProps.rowSelection = {
>       selectedRowKeys,
>       onSelect,
>       onSelectAll,
>       type: isSelectMore ? 'checkbox' : 'radio',
>       columnWidth: 30,
>       getCheckboxProps,
>     };
> ...
> .....
> ```
还是不行啊

**Comment by damaohub** [comment]
@baozouai 你这个远程请求数据换页后还是不行吧

**Comment by baozouai** [comment]
> @baozouai 你这个远程请求数据换页后还是不行吧

可以的，请问你有什么问题，用的是版本是多少

**Comment by damaohub** [comment]
> > @baozouai 你这个远程请求数据换页后还是不行吧
> 
> @damaohub 可以的，请问你有什么问题，用的是版本是多少

我的版本比较高的，已经用preserveSelectedRowKeys解决了

**Comment by baozouai** [comment]
> > > @baozouai 你这个远程请求数据换页后还是不行吧
> > 
> > 
> > @damaohub 可以的，请问你有什么问题，用的是版本是多少
> 
> 我的版本比较高的，已经用preserveSelectedRowKeys解决了

我的是4.3.1

**Comment by WilliamFocus** [comment]
> > > @baozouai 你这个远程请求数据换页后还是不行吧
> > 
> > 
> > @damaohub 可以的，请问你有什么问题，用的是版本是多少
> 
> 我的版本比较高的，已经用preserveSelectedRowKeys解决了

看到你的答案终于找到可以用的了，原来文档有这属性可以用
