### ISSUE TITLE
有没有代替mapPropsToFields的示例

### ISSUE THREAD

**Issue by Shen-Shuyi** [ant-design/ant-design#24533]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我的项目里有很多场景是点击Table的一行然后弹出一个含有Form的Modal进行编辑, 之前的做法是将那一行的数据放进props然后用mapPropsToFields映射到Form的field, 在编辑完成上传服务器后自动关闭Modal.  

看了官网的示例貌似只有 [https://ant.design/components/form-cn/#components-form-demo-global-state](url) 和我需求符合一些, 但这个示例的说明却是"将表单数据存储于外部容器并非好的实践，如无必要请避免使用", 我的需求并不是要把数据存到上级Component, 有没有推荐的示例?

**Comment by shaodahong** [comment]
https://preview.pro.ant.design/list/basic-list
