### ISSUE TITLE
form.getFieldinstance() has been missing/removed

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#24538]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-7nrcwn?file=index.js](https://stackblitz.com/edit/react-7nrcwn?file=index.js)

### Steps to reproduce
In AntD 3 , there is an option to access the form field by calling form.getFieldInstance(). This is very useful to access the dom events like focus.
But in AntD 4 this method not available.

We can create ref and use access the DOM.
However when there nested structure like parent -> Child -> GrandChild -> GreateGrandChild its very annoying to create too many ref's there by violating Encapsulation.

### What is expected?
form should have exposed method like form.getFieldInstance()

### What is actually happening?
form.getFieldInstance is not a function

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | any |
| System | any |
| Browser | any |

**Comment by yoyo837** [comment]
Duplicated of #23659
