### ISSUE TITLE
button-group中嵌入一个dropdown,当dropdown旁边的按钮是disable状态时,从disable按钮方向划进dropdown包裹的标签,不触发下拉

### ISSUE THREAD

**Issue by duhongjun** [ant-design/ant-design#24547]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-qlvfp?file=/index.js)

### Steps to reproduce
//  从Dropdown左侧(也就是禁用状态的按钮)划到Dropdown上, 无法触发下拉,
// 从其他方向(上,右,下)不受影响,正常触发下拉.

### What is expected?
disabled按钮不会影响dropdown

### What is actually happening?
disabled按钮会影响dropdown

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.8 |
| System | macos10.15.1 |
| Browser | chrome 81.0 |

---
不知道是否描述清楚了,如果没看懂的话, 我可以补一张gif图.

**Comment by afc163** [comment]
Chrome 的专属"问题"，不太好修。

**Comment by duhongjun** [comment]
兼容问题啊 那就算了  可以靠改变按钮位置来绕过这个问题
