### ISSUE TITLE
table 组件没有 ref 属性可选，ts过程会报错

### ISSUE THREAD

**Issue by zozopen** [ant-design/ant-design#24543]
![image](https://user-images.githubusercontent.com/23204297/83128911-a3539780-a10e-11ea-904e-ad4b3adb2e5f.png)

**Comment by yoyo837** [comment]
我在想 #22015 里加，但是没写好！欢迎PR

**Comment by aNewLearnerHere** [comment]
> 我想在 #22015 里加，但是没写好！欢迎PR

大佬，大概啥时候加呀，之前的3.x业务里需要用到ref，升级之后这个跟ref相关的功能就要gg了～

**Comment by raualvron** [comment]
> I want to add in #22015 , but I didn’t write it! Welcome to PR

Hi yoyo837, Is going the table component to support ref?. Thanks

**Comment by yoyo837** [comment]
> > I want to add in #22015 , but I didn’t write it! Welcome to PR
> 
> Hi yoyo837, Is going the table component to support ref?. Thanks

It is not supported currently, I have not been able to do this very well, PR welcome.
