### ISSUE TITLE
Add `-readonly` marker to the class name of the input wrapper `ant-input-affix-wrapper` when 'readOnly' property is set.

### ISSUE THREAD

**Issue by Frontmaster** [ant-design/ant-design#24544]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently if you use input with prefix/suffix the component creates additional wrapper around it with a class name `ant-input-affix-wrapper`. When you set property `disabled` this wrapper receives an extra class `ant-input-affix-wrapper-disabled`. Which unfortunately is not the case when you set 'readOnly'.
This looks like a missing feature. This feature is crucial in order to provide a consistent look of a readonly inputs with and without `prefix/suffix`

### What does the proposed API look like?
When property `readOnly` is set on input which uses `prefix/suffix` an extra class `ant-input-affix-wrapper-readonly` should be assigned. Basically the same API as with `disabled` state.

**Comment by morenyang** [comment]
I can take this
