### ISSUE TITLE
表格固定列性能问题？

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#2454]
使用固定列后，鼠标悬浮到表格行上就会有setState调用，触发表格的重新render。
好像还和表格横向滚动条有关，拖动横向滚动条也会调用setState，会触发表格列的render方法。
`scroll={{ x: 1500, y: 300 }}`

antd版本 1.6.5

试了下官网固定列的例子，这个貌似会有性能问题？该怎么处理好？
谢谢。

**Comment by afc163** [comment]
对，这个是为了实现滚动交互必要的渲染，有任何性能优化的建议，欢迎直接给 rc-table PR ~

**Comment by afc163** [comment]
fixed in #2540
