### ISSUE TITLE
modal.confirm方法. 属性okType为danger的弹窗.   初始确定按钮显示为hover状态的淡红色. 

### ISSUE THREAD

**Issue by guiyu1230** [ant-design/ant-design#24542]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/beautiful-tdd-iwhf8?file=/index.js)

### Steps to reproduce
1. 设置modal.confirm方法. okType="danger"
2. 打开弹窗. 发现初始状态 "确认"按钮为 淡红色(hover状态下的颜色. 但不是hover状态)
3. 点击空白处. "确认"按钮恢复为红色

### What is expected?
初始状态 "确认"按钮为红色. 

### What is actually happening?
初始状态 "确认"按钮为淡红色(hover状态下的颜色. 但不是hover状态). 

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome  79.0.3945.88 |

---
3.x和4.x版本都有此问题.    4.2.5 最新的danger 按钮样式也有此问题.  边框色偏淡. 点空白处可恢复

**Comment by guiyu1230** [comment]
confirm方法.   okType=   'default' | 'primary' | 'ghost' | 'dashed' | 'danger'   所有类型都有此问题

**Comment by yoyo837** [comment]
这是autoFocus功能吧？

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/83130719-532a0480-a111-11ea-82f3-38ce55bfa573.png)

https://codesandbox.io/s/stoic-chaum-wiee6?file=/index.js
