### ISSUE TITLE
Checkbox button

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24540]
类似于 Radio.Group 中的 Radio.Button。

做了一个 Checkbox button 的 Demo，看看效果，讨论下，是否有 **实用性** 和 **可行性**

![2020-05-28 17 02 48](https://user-images.githubusercontent.com/29775873/83121863-7353c680-a105-11ea-949a-57ac82122220.gif)

- gif 第一次加载卡顿，加载完成一次后，可正常查看。

**Comment by zombieJ** [comment]
v4 版本下掉了 Button.Group 是因为它和 Radio.Button 不好区分。目前为止设计上还不准备提供 Button 的其他功能样式。 我和设计师对一对。

**Comment by shangguanhongzhou** [comment]
![image](https://user-images.githubusercontent.com/8383020/83124478-d85ceb80-a108-11ea-9f69-fa040f93b981.png)
这个样式在交互设计上是不存在的，但还是感谢你的意见输入。

**Comment by afc163** [comment]
有个 CheckCard 可以试着拿出来做掉。

**Comment by fmaximus** [comment]
Why is this closed, it seems the PR was never merged.
