### ISSUE TITLE
badge 数字不居中

### ISSUE THREAD

**Issue by waveheart** [ant-design/ant-design#24548]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/badge-cn/](https://ant.design/components/badge-cn/)

### Steps to reproduce
https://ant.design/components/badge-cn/

### What is expected?
徽标数字居中

### What is actually happening?
徽标数字居中

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | react |
| System | ALL |
| Browser | ALL  |

---
设计师反馈所有数字不居中
![微信图片_20200528200715](https://user-images.githubusercontent.com/25602259/83139396-e0278a80-a11e-11ea-9651-49e01c008cdb.png)
![微信图片_20200528200742](https://user-images.githubusercontent.com/25602259/83139407-e7e72f00-a11e-11ea-9046-21be73b0c42c.png)

**Comment by waveheart** [comment]
官方组件的页面直接看就行
我们的设计师牛逼比你们小阿狸的设计师牛逼1W倍， 我也没办法

**Comment by waveheart** [comment]
![image](https://user-images.githubusercontent.com/25602259/83170958-ec740d80-a147-11ea-8e38-9a77c5122fd7.png)

**Comment by xrkffgg** [comment]
这个我觉得你可以在自己项目中 改改 css ，把数字 挪到 你们设计师认为中间的位置。

**Comment by yoyo837** [comment]
你的截图 视觉上有一丢丢沉底，是什么浏览器？我的Chrome和Safari没有这个现象。

是否确认过是不是项目内样式影响了？

**Comment by waveheart** [comment]
> 这个我觉得你可以在自己项目中 改改 css ，把数字 挪到 你们设计师认为中间的位置。

我调这个当然没问题。

所以提issue ， 我给我们设计师看了官方组件库的样式，人家说居中，放大500%看的。
不信你试试。 放大了以后明显靠底部。

**Comment by xrkffgg** [comment]
元素的设计并不一定是要居中的，还要考虑视觉上的效果。

你应该了解，有些东西，在视觉上，居中的反而是不居中，相等的反而是不相等。

**Comment by waveheart** [comment]
> 元素的设计并不一定是要居中的，还要考虑视觉上的效果。
> 
> 你应该了解，有些东西，在视觉上，居中的反而是不居中，相等的反而是不相等。


我知道，我就是甩锅， 被我们设计师给气的。
哈哈。

**Comment by afc163** [comment]
你截图产品里的 Badge 确实不居中，截图里 antd 里的是居中的。看看是什么影响了。

**Comment by AshoneA** [comment]
我看着感觉也像是没居中，是有被缩放之类的吗。
