### ISSUE TITLE
React does not recognize the `colStyle` prop on a DOM element.

### ISSUE THREAD

**Issue by Renderz** [ant-design/ant-design#24557]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/76w69?file=/index.js)

### Steps to reproduce
directly open

### What is expected?
no error

### What is actually happening?
Warning: React does not recognize the `colStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `colstyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.12.0 |
| System | macOS |
| Browser | chorme |

**Comment by yoyo837** [comment]
List 里面 是搭配 List.Item的

**Comment by yoyo837** [comment]
除非team原则上不反对List里直接放非 List.Item的其他内容，再打开。

**Comment by Renderz** [comment]
> 除非team原则上不反对List里直接放非 List.Item的其他内容，再打开。

这个是官方例子的引用, 如果修改是不是在官网部分也改掉.

**Comment by yoyo837** [comment]
由 #23630 引起， @afc163 是否克隆的时候判断一下emit掉`colStyle`?
```jsx
      cloneElement(child, {
        key: keys[index],
        colStyle,
      }),
```

**Comment by yoyo837** [comment]
Looks similar to #24553
