### ISSUE TITLE
table表格. defaultExpandAllRows属性使用问题

### ISSUE THREAD

**Issue by guiyu1230** [ant-design/ant-design#24559]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/little-silence-w6lm7?file=/index.js)

### Steps to reproduce
1. table表格使用defaultExpandAllRows=true属性
2. dataSource数据是使用了接口请求. (dataSource数据有children属性)
3. 数据展现后. 子数据未展开(defaultExpandAllRows未生效)

### What is expected?
数据展现后. 子数据展开

### What is actually happening?
数据展现后. 子数据未展开

| Environment | Info |
|---|---|
| antd | 3.26.10 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | chrome  79.0.3945.88 |

---
做了测试.  发现defaultExpandAllRows属性只会在 Table表格第一次render生效.  后面再次render不会生效(接口请求拿到数据会再赋值一次).

**Comment by afc163** [comment]
>  发现defaultExpandAllRows属性只会在 Table表格第一次render生效

这是预期的，这个属性就是这样工作的。

**Comment by guiyu1230** [comment]
那对于业务层面.  请求接口拿到dataSource. 后展示想让数据全展开. 有什么好办法吗

**Comment by afc163** [comment]
1. 可以拿到数据再渲染 Table：`dataSource && <Table dataSource={dataSource} defaultExpandAllRows />`.
2. 或者使用 expandable.expandKeys 手动控制需要展开的列。（推荐）

**Comment by dotexe0** [comment]
@afc163 is it correct to say that `expandable` props and `loading` prop do not work together?
It means we need to do:
```
{loading ? (
        <Table key="loading-table" loading={loading} />
      ) : (
        <Table
          key="unique-key"
          columns={columns}
          dataSource={dataSource}
          expandable={{
            childrenColumnName: 'someColumnThatContainsChildren',
            defaultExpandAllRows: true
          }}
        />
      )}
```

instead of just:
```
<Table
     key="unique-key"
     loading={loading}
     columns={columns}
     dataSource={dataSource}
     expandable={{
       childrenColumnName: 'someColumnThatContainsChildren',
       defaultExpandAllRows: true
    }}
 />
```

**Comment by Guwengo** [comment]
```
{loading ? (
        <Table key="loading-table" loading={loading} />
      ) : (
        <Table
          key="unique-key"
          columns={columns}
          dataSource={dataSource}
          expandable={{
            childrenColumnName: 'someColumnThatContainsChildren',
            defaultExpandAllRows: true
          }}
        />
)}
```
正解,这个办法清测
