### ISSUE TITLE
V4.2.4 Cascader in child component doesn't clear input filed as V4.2.1 does when new options passed as props

### ISSUE THREAD

**Issue by FlyingUnicornSF** [ant-design/ant-design#24554]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://4lzr9.csb.app/](https://4lzr9.csb.app/)

#### Vid showing the steps to reproduce & shows difference between V4.2.1 and V4.2.4:
[https://youtu.be/QpyOhlJwyvQ](https://youtu.be/QpyOhlJwyvQ)

#### V4.2.1:
 [https://ylb8b.csb.app/](https://ylb8b.csb.app/)

#### Architecture: 
- Parent component (App.js) contains a selector.   Child component (bugMaybe.js) contains a cascader. Parent component propagates a set of options to child component and cascader loads the passed options. 
- Upon selecting an option with a selector in App.js, it propagates a different cascader options to its child component accordingly.

ex: Key 1 in a selector in App.js propergates option1 to bugMaybe.js cascader.   
ex: Key 2 in a selector in App.js propergates option2 to bugMaybe.js cascader. 
#### Steps: 
- Select an option in the parent component. 
- Select an option from a cascader, and cascader displays options.
- Select another option in the parent component. 

### What is expected?
cascader clears input display. See the vid from 11sec mark.

### What is actually happening?
cascader displays VALUES of previously picked in input field. See the vid from 0sec. 

| Environment | Info |
|---|---|
| antd | 4.2.4 |
| React | 16.13.1 |
| System | macOS Catalina |
| Browser | Chrome  81.0.4044.138  |

---
V4.2.1 and V4.2.4 behaves differently.  I tired with V.4.2.5 in sandbox, it was not fixed.

**Comment by afc163** [comment]
It is expected behavior implemented in https://github.com/ant-design/ant-design/pull/24058

Like what I said in https://github.com/ant-design/ant-design/issues/24333#issuecomment-631858845, you should alway clear Cascader value after select changed: https://codesandbox.io/s/antd-cascaderbug-q4gg6?file=/app.js
