### ISSUE TITLE
Broken Grid List styles when adding a component between List and List.Item

### ISSUE THREAD

**Issue by ostrebler** [ant-design/ant-design#24553]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wild-hooks-95i3s?file=/src/App.tsx)

### Steps to reproduce
Use `List` in grid mode, and wrap `List.Item` in a component.

I have a large UI codebase which uses a lot of wrapper components around `List.Item` (to use item-level hooks for example...). This used to work fine in AntDesign 3. Using the grid mode, the new version 4 breaks the styles because [they are directly injected into `List.Item` using `cloneElement`](https://github.com/ant-design/ant-design/blob/master/components/list/index.tsx#L248).

### What is expected?
Styles should be applied via style sheets, not by element cloning which is not only an unlisted breaking change from v3 but also prohibits an easy use of component wrapper around `List.Item` (without forwarding props).

### What is actually happening?
Styles are broken. The grid layout doesn't render correctly.

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | react 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 81.0.4044.138 |

**Comment by zombieJ** [comment]
If codesandbox can not reproduce. Please provide a github mini repo for reproduce instead.

**Comment by afc163** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/507615/83330769-0dfa0400-a2c4-11ea-9f4e-d64b337d06eb.png">

**Comment by xiaosongxiaosong** [comment]
4.x 版本将 `List.Item` 包装成组件会导致响应式栅格列表无法正常显示，之前 3.x 版本的时候这样使用没有问题的

#### 4.x 版本
[![Edit admiring-cerf-kiw7j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-cerf-kiw7j?fontsize=14&hidenavigation=1&theme=dark)

显示效果:
![4 x](https://user-images.githubusercontent.com/2703455/83837073-fee1de80-a727-11ea-8878-d267ff4fbe47.gif)

#### 3.x 版本
[![Edit upbeat-goldberg-ueme0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-goldberg-ueme0?fontsize=14&hidenavigation=1&theme=dark)

显示效果:
![3 x](https://user-images.githubusercontent.com/2703455/83837072-fe494800-a727-11ea-910c-a2eaf732d236.gif)

**Comment by lgants** [comment]
I recently noticed this behavior after updating to 4.3.1 - I've been using 4.x for a while without this issue. Might be related to this: https://github.com/ant-design/ant-design/pull/24280
