### ISSUE TITLE
Form 大表单输入情况，如果打开控制台，输入内容非常卡。

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#24558]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dumi-demo-p9zw6?file=/demo.tsx)

### Steps to reproduce
正常输入是不卡的，但是打开控制台再输入变的奇卡无比。

### What is expected?
不卡

### What is actually happening?
卡

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
复现不是大表单，且打开后输入内容不卡。

**Comment by crazyair** [comment]
> 复现不是大表单，且打开后输入内容不卡。

![image](https://user-images.githubusercontent.com/7971419/83211787-924b6a80-a190-11ea-92fa-cee8d41a66aa.png)

**Comment by crazyair** [comment]
> 复现不是大表单，且打开后输入内容不卡。

不好意思，链接贴错了，更新了

**Comment by yoyo837** [comment]
截个图先放着 
![image](https://user-images.githubusercontent.com/6134547/83213288-60d49e00-a194-11ea-82d3-35151385c839.png)

**Comment by crazyair** [comment]
@zombieJ

**Comment by yoyo837** [comment]
这个的优先级应该不会太高，这么多表单项太少见了。

**Comment by crazyair** [comment]
> 这个的优先级应该不会太高，这么多表单项太少见了。

那劳烦看我又发了一个

**Comment by zombieJ** [comment]
性能消耗来自于 Input 的 `resolveOnChange`，我看看里面做了啥。

**Comment by zombieJ** [comment]
看了一下，每个字段通知耗费 `0.1 ~ 0.2 ms`，1000 字段后会显得时间很久。我看看怎么优化字段通知的代码逻辑。

**Comment by zombieJ** [comment]
发现原来的例子也变卡了，试了一下 Firefox 比 Chrome 顺畅。推测最近 Chrome 上了啥负优化。。。

**Comment by crazyair** [comment]
暂时先过吧

**Comment by zombieJ** [comment]
挖了一下，有 2 点可以优化：
* 开发模式下，未使用 Form 的检测逻辑做 dedup
* Chrome 下获取 store 值的 function 速度变慢了，推测是 inlineCaches 命中出了问题。提炼到上层统一传入。

ref https://github.com/react-component/field-form/pull/143
