### ISSUE TITLE
官网一个设计图中的组件难以工程化，建议去除

### ISSUE THREAD

**Issue by leeching** [ant-design/ant-design#2455]
在官网文档中出现了一幅设计图，具体位置在【语言】》【三大特性】》【微小】》【第三幅设计图】。

链接：http://ant.design/docs/spec/feature#微小

图片：
![jxzqirfmctmjuah](https://cloud.githubusercontent.com/assets/8462120/17018782/f8e7ddd0-4f6b-11e6-8853-7955eeaebe13.png)

这个组件并没有被antd实现，而且，在中文输入的情景下这个组件几乎是无法实现的，原因是：

1. 这样的组件只能使用div[contenteditable]实现，input[type="text"]无法折行，textarea中是纯文本，效果图中的尾部高亮和下划线效果是做不出来的。
2. 要想实现图中的效果，div[contenteditable]上必须监听`input`或`keyup`, `keydown`之类的事件。每次事件触发时，分析文本长度。div[contenteditable]上并没有`change`事件。
3. 如果只输入西文，根据第二点的思路，可以实现。但是，如果是在输入中文，比如说，某一个用户正在输入拼音但还没有按空格键确认文字输入的时候，div[contenteditable]上的`input`, `keydown`等事件也会被触发，见下图

![image](https://cloud.githubusercontent.com/assets/8462120/17019630/db38dd4e-4f6f-11e6-8b24-cac373c7780e.png)

还有其他的解决方案，比如分两层，上一层放一个隐形的textarea，下一层放div实时渲染textarea的内容，但是如果文本很长，触发了textarea的滚动事件，或者在textarea中做了选中一段文字的操作，很难在下一层的div中模拟选中效果。

总而言之，在中文的使用环境下，这个组件的实现几乎是不可能的，所以建议把网站上这张设计图去除，以免有工程师被强行要求开发这个效果浪费时间。

**Comment by RaoHai** [comment]
这个可以用 draft-js 做的。

**Comment by leeching** [comment]
感觉一个input级别的组件，要用到富文本编辑器，从开发成本和功能收益来看，并不是很优化。但可以尝试一下，感谢回复。

**Comment by RaoHai** [comment]
不需要全功能的富文本。只需要一个基本的框框，在 onChange 和 onCompositionUpdate（用于输入法）的时候算一下总长， 给个提示什么的就行了。

**Comment by afc163** [comment]
1. 是可以实现的，按 @RaoHai 的说法，这种属于富文本编辑器的范畴。实际上，twitter 的发布输入框就是这样的。https://twitter.com/
2. 我们目前也还未这个功能，会放到后续 Editor 的实现里。https://github.com/ant-design/ant-design/issues/1083 
3. 这是一个比较复杂的功能，如果自行开发确实需要比较多的精力，如果你在使用 Ant Design 及其技术栈，建议把我这个回复给你的 PD 或设计师看，让他们了解到这个功能的投入产出比。

欢迎持续关注。

**Comment by afc163** [comment]
另外，你可以试试 https://github.com/lovasoa/react-contenteditable。我试过，onChange 在大部分情况还是可用的。

**Comment by zhujun24** [comment]
题主说的第三点原因，对于中文输入等非直接输入会触发 `keydown` 事件，可以监听 [CompositionEvent](https://developer.mozilla.org/en-US/docs/Web/API/CompositionEvent) 事件，比如分别监听 [compositionstart](https://developer.mozilla.org/en-US/docs/Web/Events/compositionstart) 和 [compositionend](https://developer.mozilla.org/en-US/docs/Web/Events/compositionend) 事件，这些事件会在 `keydown` 事件之前触发，因此可以在 `compositionstart` 事件触发的时候添加一个属性，然后在 `compositionend` 事件触发的时候修改这个属性，就可以在 `keydown` 事件触发的时候判断这个属性来处理逻辑，如果是非直接输入触发的 `keydown` 事件，则可以不做处理，否则就可以随意玩耍了
