### ISSUE TITLE
1.6.5版本的antd,form组件默认状态下不管列表占了几栅格都会自动霸占一行

### ISSUE THREAD

**Issue by laolu87** [ant-design/ant-design#2456]
例如我 一个输入框是\<FormItem key = '1' wrapperCol = {{span:'5'}}>,然后下一个输入框也是\<FormItem key = '2' wrapperCol = {{span:'5'}}>时,总共还不到24栅格,但他却强制换行,我的目的是不想他换行!而form改成inline样式时,他们却没有栅格全都缩成一堆了!只有1.6.5这个版本有这个bug,降级后就不会了!不知道什么原因?

**Comment by afc163** [comment]
Need demo.

**Comment by laolu87** [comment]
演示代码:
`const { Form, Select, InputNumber, DatePicker, TimePicker, Switch, Radio,
         Cascader, Slider, Button, Col, Upload, Icon } = antd;
const FormItem = Form.Item;
const Option = Select.Option;
const RadioButton = Radio.Button;
const RadioGroup = Radio.Group;

const areaData = [{
  value: 'shanghai',
  label: '上海',
  children: [{
    value: 'shanghaishi',
    label: '上海市',
    children: [{
      value: 'pudongxinqu',
      label: '浦东新区',
    }],
  }],
}];

let Demo = React.createClass({
  handleSubmit(e) {
    e.preventDefault();
    console.log('收到表单值：', this.props.form.getFieldsValue());
  },

  normFile(e) {
    if (Array.isArray(e)) {
      return e;
    }
    return e && e.fileList;
  },

  render() {
    const { getFieldProps } = this.props.form;
    return (
      <Form onSubmit={this.handleSubmit} horizontal>
            <FormItem
              key = '1'
              wrapperCol = {{span:'5'}}>
              <Select
                placeholder='请选择类型'
                {...getFieldProps('super_category_id',)}>
                <Option key = '1'>111</Option>
              </Select>
            </FormItem>
            <FormItem
              key = '2'
              wrapperCol = {{span:'5'}}>
              <Select
                placeholder='请选择类型'
                {...getFieldProps('super_category_id',)}>
                <Option key = '1'>111</Option>
              </Select>
            </FormItem>
      </Form>
    );
  },
});

Demo = Form.create()(Demo);

ReactDOM.render(<Demo />, document.getElementById('container'));`

**Comment by laolu87** [comment]
复制你们例子搞的演示代码,自行忽略多余的东西!

**Comment by laolu87** [comment]
行内样式问题就更大了!
```
const { Form, Select, InputNumber, DatePicker, TimePicker, Switch, Radio,
         Cascader, Slider, Button, Col, Upload, Icon } = antd;
const FormItem = Form.Item;
const Option = Select.Option;
const RadioButton = Radio.Button;
const RadioGroup = Radio.Group;

const areaData = [{
  value: 'shanghai',
  label: '上海',
  children: [{
    value: 'shanghaishi',
    label: '上海市',
    children: [{
      value: 'pudongxinqu',
      label: '浦东新区',
    }],
  }],
}];

let Demo = React.createClass({
  handleSubmit(e) {
    e.preventDefault();
    console.log('收到表单值：', this.props.form.getFieldsValue());
  },

  normFile(e) {
    if (Array.isArray(e)) {
      return e;
    }
    return e && e.fileList;
  },

  render() {
    const { getFieldProps } = this.props.form;
    return (
      <Form onSubmit={this.handleSubmit} inline>
            <FormItem
              key = '1' wrapperCol = {{span:'24'}}>
              <Select
                placeholder='请选择类型'
                {...getFieldProps('super_category_id',)}>
                <Option key = '1'>111</Option>
              </Select>
            </FormItem>
            <FormItem
              key = '2'  wrapperCol = {{span:'24'}}>
              <Select
                placeholder='请选择类型'
                {...getFieldProps('super_category_id',)}>
                <Option key = '1'>111</Option>
              </Select>
            </FormItem>
      </Form>
    );
  },
});

Demo = Form.create()(Demo);

ReactDOM.render(<Demo />, document.getElementById('container'));
```

**Comment by yeliex** [comment]
貌似一直有这个问题 手动加个flex: 1试试

另外1.6.5中更新了formitem label.
原先是 
```html
<div class="ant-form-item">
    <label>...</label>
</div>
```
更新后变成了
```html
<div class="ant-form-item">
    <div class="ant-form-item-label">
        <label>...</label>
    </div>
</div>
```

**Comment by laolu87** [comment]
@yeliex 恩恩,我需要的效果已经实现了,就是提交一下问题而已!

**Comment by afc163** [comment]
horizontal 模式 FormItem 会占据一行。

inline 模式，尝试给 select 加上固定宽度吧。

**Comment by laolu87** [comment]
@afc163 那默认是什么模式呢?1.6.5版本默认状态下也会占据一行,之前的版本不会,感觉是这个版本的问题.之前版本那么设计挺好的,默认模式下不会自动占据一行也不会像行内样式那样需要固定宽度,可以直接使用栅格系统!

**Comment by benjycui** [comment]
可能是这个原因导致的 https://github.com/ant-design/ant-design/commit/4a6ff6f05324d9df9a727a583356f7dfc54b1683

可以提供可重现 demo 么。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001
