### ISSUE TITLE
antd4 form表单给 form.item 设置initialValue不生效

### ISSUE THREAD

**Issue by littleBelle** [ant-design/ant-design#24564]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://e.coding.net/napinshop/napinAdmin.git](https://e.coding.net/napinshop/napinAdmin.git)

### Steps to reproduce
在components/pageList/search.js的192行
给循环出来的form.item的input加上initialValue初始值，控制台报错
input: (item, index) => {
      let { input, label } = item;
      input = Object.assign(
        {
          field: null,
          placeholder: null,
          onChange: value => {},
          initialValue: null,
        },
        input,
      );
      this.values[input.field] = input.initialValue;
      return (
        <FormItem label={label} key={index} name={input.field} initialValue={'1111111'}>
          <Input
            placeholder={input.placeholder}
            onChange={e => {
              input.onChange(e);
            }}
          />
        </FormItem>
      );
    },
报错内容如下：devScripts.js:5035 Warning: React does not recognize the `initialValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

### What is expected?
希望能给form.item的input设置初始值

### What is actually happening?
给form.item的input设置初始值时控制台报错

| Environment | Info |
|---|---|
| antd | undefined |
| React | 4.2.5 |
| System | window10 |
| Browser | google |

---
如果是给Form设置initialValues可以实现，但是目前想要的是给form.item设置初始值

**Comment by zhangtang1** [comment]
生效了，但是console上报了warning的警告，就是上面那个

**Comment by zhangtang1** [comment]
https://codesandbox.io/s/antd-reproduction-template-ts00g?file=/index.js

生产环境没问题，但开发环境会报：Warning: React does not recognize the `initialValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `initialvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element

是Form.Item的initialValue没过滤传给了dom？
还是我的用法有问题？

**Comment by dumbbell0720** [comment]
同问

**Comment by 07akioni** [comment]
给一个 codesandbox 复现链接
