### ISSUE TITLE
List 类型无法使用 initialValue 设置值

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#24561]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dumi-demo-p9zw6?file=/demo.tsx)

### Steps to reproduce
List 传了 initialValue 没有显示出来数据
### What is expected?
可以和其它类型一样可以用 initialValue

### What is actually happening?
无法使用 initialValue

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by 569202812** [comment]
我是直接在Form里面处理的

**Comment by crazyair** [comment]
#24562 移步
