### ISSUE TITLE
statistic demo

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24565]
### Link
https://ant.design/components/statistic-cn/#components-statistic-demo-basic

![image](https://user-images.githubusercontent.com/29775873/83217541-97afb180-a19e-11ea-85b3-155475adcd15.png)

这个 Button  是不是想 随机数字来展示的？

现在 Demo 中没有任何操作。。。。

**Comment by afc163** [comment]
> 这个 Button 是不是想 随机数字来展示的？

不是，纯展示的 Button。

**Comment by xrkffgg** [comment]
- https://ant.design/components/modal-cn/#components-modal-demo-confirm
- https://ant.design/components/modal-cn/#components-modal-demo-confirm-promise

我感觉这 2 个 Demo 可以合并一下，而且名字还重复了。

功能上，第二个 的 promise 可以加到 第一个上。

@afc163

**Comment by afc163** [comment]
@xrkffgg 可以的。
