### ISSUE TITLE
Modal style in RTL

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24566]
### Reproduction link
[https://ant.design/components/modal-cn/#components-modal-demo-confirm](https://ant.design/components/modal-cn/#components-modal-demo-confirm)

RTL 样式异常

![image](https://user-images.githubusercontent.com/29775873/83218076-cf6b2900-a19f-11ea-8c5a-ac71e5c8bacc.png)

**Comment by xrkffgg** [comment]
之前看过一下，不是那么容易解决，先记录着。

**Comment by afc163** [comment]
截一个内部周报。

<img width="719" alt="image" src="https://user-images.githubusercontent.com/507615/83333973-fb88c600-a2d5-11ea-980a-c6dcf43553d9.png">

**Comment by xrkffgg** [comment]
ok

**Comment by xrkffgg** [comment]
- iv 

默认的 Spin RTL 是逆时针的。
LoadingOutlined 自定义 Spin 

这个是不是可以重启了。

https://github.com/ant-design/ant-design/issues/23735 

https://github.com/ant-design/ant-design-icons/pull/290

**Comment by xrkffgg** [comment]
- i

---
一般的组件中，如 Menu、PageHeader 等，在 RTL 模式下 **方向性按钮** 都进行了对应的调整，如下图：

![image](https://user-images.githubusercontent.com/29775873/83367834-1c8e0b80-a3e9-11ea-945d-9e11283e1d7f.png)

![image](https://user-images.githubusercontent.com/29775873/83367846-2748a080-a3e9-11ea-94a5-6f97992aa5ff.png)

---
官网中的按钮，我也进行过相应的调整

![image](https://user-images.githubusercontent.com/29775873/83367979-bb1a6c80-a3e9-11ea-865a-4e7966bdee52.png)

---

而 Icon 使用 如 `<LeftOutlined />`，RTL 模式下系统不应该去主动改变，而应遵循开发者的代码，若需调整开发者可使用 `<RightOutlined />`。

RTL 并不是把 左右 都改变了，只是方向变了。

**Comment by xrkffgg** [comment]
- iii

我来改一下。

**Comment by hengkx** [comment]
`rtl` 模式 是不是 直接改成 `<RightOutlined />` 要好些

**Comment by xrkffgg** [comment]
😂😂😂  不是啊，某个开发者，用了 <LeftOutlined /> ，RTL 下，我们不能给变的啊。

RTL 下， 左还是左，右还是右。

**Comment by hengkx** [comment]
开发者用了 肯定 不能变，这个 不是有默认值吗？

**Comment by xrkffgg** [comment]
其他组件中 用到的方向性的 按钮 都变过了。

**Comment by xrkffgg** [comment]
@afc163 

1 2 3 都 OK 了。

4 打算怎么弄？

---
默认的 Spin RTL 是逆时针的。
LoadingOutlined 自定义 Spin 是需要修改 Icon 的

是不是可以用之前的这个呢？

#23735

ant-design/ant-design-icons#290
