### ISSUE TITLE
使用ts-import-plugin按需加载antd变异的时候有warning

### ISSUE THREAD

**Issue by WebEngineerLi** [ant-design/ant-design#24567]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/index-cn](https://ant-design.gitee.io/index-cn)

### Steps to reproduce

![image](https://user-images.githubusercontent.com/30517805/83220836-ac904300-a1a6-11ea-9a00-4b80383df0a3.png)
webpack配置
```js
{
  loader: "ts-loader",
  options: {
    transpileOnly: true,
    getCustomTransformers: () => ({
      before: [ tsImportPluginFactory( [{
        libraryName:"antd",
        libraryDirectory:"lib",
        style:true
      }]) ]
    }),
    compilerOptions: {
      module: "es2015"
    }
  },
},
```

### What is expected?
编译时不报warning

### What is actually happening?
编译时报warning

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | Mac 10.15.4  |
| Browser | Chrome 83.0.4103.61 |

**Comment by afc163** [comment]
建议提到 https://github.com/Brooooooklyn/ts-import-plugin
