### ISSUE TITLE
Form.List 类型无法使用 initialValue 设置值

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#24562]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dongtaizengjianbiaodanxiang-ant-design-demo-7ot8n?file=/index.js)

### Steps to reproduce
List 传了 initialValue 没有显示出来数据
### What is expected?
可以和其它类型一样可以用 initialValue

### What is actually happening?
无法使用 initialValue

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
复现连接呢？List 没 `initialValue`参数吧？

**Comment by crazyair** [comment]
https://codesandbox.io/s/dongtaizengjianbiaodanxiang-ant-design-demo-7ot8n?file=/index.js

![image](https://user-images.githubusercontent.com/7971419/83215129-c9be1500-a198-11ea-9e14-ab53b763621b.png)

**Comment by crazyair** [comment]
> 复现连接呢？List 没 `initialValue`参数吧？

既然做了 initIalValue 参数，其实 List 也可以支持的，要不怎么给他设置默认值啊。

**Comment by yoyo837** [comment]
我以为你说的List, 原来是Form.List

**Comment by yoyo837** [comment]
Form.List里一般最终都返回Form.Item，它接受initialValue

**Comment by crazyair** [comment]
![image](https://user-images.githubusercontent.com/7971419/83215643-0cccb800-a19a-11ea-9bbb-7731492612c8.png)
这个好支持，只要这样加上就行了

**Comment by yoyo837** [comment]
Form.List一般都是自行控制渲染，初始值也一并自行处理比较合理

**Comment by crazyair** [comment]
我觉得 Form.List 设置 initialValue 只管长度，不管值是 ok 的。

**Comment by yoyo837** [comment]
> 我觉得 Form.List 设置 initialValue 只管长度，不管值是 ok 的。
> 或者嵌套 Field，以最后一层设置的 initialValue 为准。

这个没明白什么意思，细说一下？

**Comment by crazyair** [comment]
> 这个没明白什么意思，细说一下？

你再自己仔细看下 https://github.com/ant-design/ant-design/issues/24562#issuecomment-635726003 这个 comment，不行你就本地启动试下，就会发现问题的。

**Comment by crazyair** [comment]
@zombieJ 帮忙看下这个。

**Comment by zombieJ** [comment]
`Form.List` 是特地没有 `initialValues` 的。因为它本身其实不 hold 值，值是依赖于内嵌的 Form.Item。对添加此特性个人感觉比较谨慎，里面的 Form.Item 写错了容易被坑到。

**Comment by crazyair** [comment]
我打算放弃用  initialValues 了，所以 List 不支持的话，我没法给默认值了。

**Comment by zombieJ** [comment]
可以自行包一个 Form.List 在 mount 的时候更新一下。antd 这边暂时不会加上。

**Comment by crazyair** [comment]
这个要怎么改？ https://github.com/crazyair/yforms/blob/add-view/packages/yforms/src/YForm/component/List.tsx

**Comment by crazyair** [comment]
> `Form.List` 是特地没有 `initialValues` 的。因为它本身其实不 hold 值，值是依赖于内嵌的 Form.Item。对添加此特性个人感觉比较谨慎，里面的 Form.Item 写错了容易被坑到。

如果使用 initialValues 设置默认值，那就自然设置到 List 的 Field 上面了，其实是一个道理。

**Comment by zombieJ** [comment]
https://codesandbox.io/s/dongtaizengjianbiaodanxiang-ant-design-demo-301e1?file=/index.js

**Comment by crazyair** [comment]
动态增减表单项

**Comment by crazyair** [comment]
> https://codesandbox.io/s/dongtaizengjianbiaodanxiang-ant-design-demo-301e1?file=/index.js

还能这样搞，牛牛牛。

**Comment by zombieJ** [comment]
话说你封装的话，最好换个名字比如 `initialListValue`，让用户知道这个是不太一样的。

**Comment by crazyair** [comment]
YForm 传 initialValues，然后我在下面把他拆分到每个 Item 上。我才能做 formFormat toFormat 。

**Comment by crazyair** [comment]
就比如 wrapperCol，也是设置到每个 Item 上面，才好做每个 Item 的 noCol（去掉 Col 布局） 和 offset（缩进）。

**Comment by crazyair** [comment]
> 话说你封装的话，最好换个名字比如 `initialListValue`，让用户知道这个是不太一样的。不是直接作用到 List 而是到 children Item。

上面也有说明，这里设置 value 的话，不能真的设置值，只需要设置 List 渲染长度就行 [{},{}] 。下面的自然有 initialValue。

**Comment by crazyair** [comment]
我感觉把 Form.List 当成一个字段就好了，因为本来就用了 Field，还有就算下面有没有 Form.Item，提交的时候也有 List 的值的。

**Comment by crazyair** [comment]
看到发的新版，更新了保持报错状态，我这嵌套使用报错都乱套了。不知道要怎么搞了。

![image](https://user-images.githubusercontent.com/7971419/83353160-23823300-a383-11ea-9bd0-ecd7c3b9593d.png)

**Comment by zombieJ** [comment]
能搞个最小重现不？

**Comment by crazyair** [comment]
> 能搞个最小重现不？

得好好跟你讨论下 fieldKey isListField 。好多事情要讨论，钉钉？

**Comment by zombieJ** [comment]
antd 钉钉群 : 11722346
加群找我

**Comment by crazyair** [comment]
搜不到，二维码呢？

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/83368963-506b3000-a3ed-11ea-97cd-dbae10a0686e.png)

**Comment by crazyair** [comment]
3ky，刚才打开方式不对。

**Comment by lichangchao15442** [comment]
如果想要给每项动态添加的表单项设置初始值，可以自己使用setFieldsValue代替List提供的add方法（亲测有效！）

**Comment by damaohub** [comment]
> 如果想要给每项动态添加的表单项设置初始值，可以自己使用setFieldsValue代替List提供的add方法（亲测有效！）
我觉得可能是因为用setFieldsValue设置的是(value不是initialValue)值，所以List提供的add方法会有问题，导致数量不能增加

**Comment by HiiragiMatu** [comment]
想請問如果用Form.List包Form.List initialValues設置還會成功嗎?
