### ISSUE TITLE
Colorful Radio

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24571]
![2020-05-29 14 20 49](https://user-images.githubusercontent.com/29775873/83227942-dd2ca880-a1b7-11ea-9748-26f64124a673.gif)

> PS. gif 第一次加载卡顿，加载完成一次后，可正常观看。

**Comment by xrkffgg** [comment]
#### Tooltip

![image](https://user-images.githubusercontent.com/29775873/83228752-6a243180-a1b9-11ea-9b95-b6dfba8a0da7.png)


#### Tag

![image](https://user-images.githubusercontent.com/29775873/83228783-73ad9980-a1b9-11ea-8e85-9c4d240caa78.png)

**Comment by AshoneA** [comment]
那感觉好多组件都能加了， Switch、Checkbox 之类的，

**Comment by yoyo837** [comment]
实际上应该存在使用不同颜色的场景，但可能不会对同时支持多颜色有太大需求。那样的话，通过定制css就能做到。

**Comment by afc163** [comment]
这个还是不加了。

**Comment by afc163** [comment]
Tooltip 加色彩是因为语雀已经用了类似的样式，需要给用户高亮的强提示。

Checkbox 五颜六色目前看没什么用。

**Comment by xrkffgg** [comment]
我也没想好哪里用，好看就完事了。

**Comment by AshoneA** [comment]
> 我也没想好哪里用，好看就完事了。

克制一点。😃

**Comment by xrkffgg** [comment]
https://ant-design-colorful.github.io/ant-design-colorful/  😎
