### ISSUE TITLE
modal.confirm会导致页面宽度发生变化

### ISSUE THREAD

**Issue by CHU295** [ant-design/ant-design#24572]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/holy-lake-9o7o2?file=/index.js)

### Steps to reproduce
进去连接，打开控制台，点击页面confirm执行modal.comfirm方法，可以看见右侧滚动条消失，这时body被添加了overflow: hidden属性。

而在官网执行上述方法会添加如下三个属性
position: relative; width: calc(100% - 17px); overflow: hidden;

### What is expected?
完整添加三个属性

### What is actually happening?
只添加了overflow: hidden

导致页面宽度发生变化，视觉bug

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome 83.0.4103.61 |

---
modal打开的时候会在body上面加overflow: hidden;这样导致右边滚动条消失，续而引起页面宽度产生变化，页面视觉上也会产生宽度变化的效果，体验极差

**Comment by afc163** [comment]
这是预期的，不然 Modal 会因为滚动条消失而跳动一个滚动条的宽度。详情见：https://github.com/twbs/bootstrap/blob/407b4c3606cb6cf871c3ec2a2662f10d3a5d399b/js/src/modal.js#L450

**Comment by CHU295** [comment]
> 这是预期的，不然 Modal 会因为滚动条消失而跳动一个滚动条的宽度。详情见：https://github.com/twbs/bootstrap/blob/407b4c3606cb6cf871c3ec2a2662f10d3a5d399b/js/src/modal.js#L450

哈？现在就是有bug，会消失一个滚动条的宽度，预期的确实是不会消失的

**Comment by afc163** [comment]
@CHU295 录个屏或者发个 GIF 看看

**Comment by CHU295** [comment]
> @CHU295 录个屏或者发个 GIF 看看

![image](https://user-images.githubusercontent.com/23656516/83389621-16b51c00-a423-11ea-880c-99b39d92edee.png)
![image](https://user-images.githubusercontent.com/23656516/83389649-23d20b00-a423-11ea-9af9-c87f6f1ed349.png)
你看，这里只添加了一个ovh属性，我问题里面的demo也是这样的

**Comment by CHU295** [comment]
> @CHU295 录个屏或者发个 GIF 看看

视频发钉钉讨论群了，不知道你在不在

**Comment by afc163** [comment]
无法重现：https://stackblitz.com/edit/react-1th3zj?file=index.js

看看是不是你本地有什么样式影响了？

**Comment by CHU295** [comment]
> 无法重现：https://stackblitz.com/edit/react-1th3zj?file=index.js
> 
> 看看是不是你本地有什么样式影响了？

https://codesandbox.io/s/holy-lake-9o7o2?file=/index.js
我上面发的这个你打开没问题吗？我这边打开也有这个问题，我试了三个在线编辑器，有两个正常的，这个是异常的。都是只添加了ovh一个属性然后宽度变化

![image](https://user-images.githubusercontent.com/23656516/83470194-3183a100-a4b4-11ea-962e-22376b6a7443.png)
![image](https://user-images.githubusercontent.com/23656516/83470215-3e07f980-a4b4-11ea-83b2-1e3b95c78cf6.png)
你看，就这样的，这个编辑器不会添加，其他的编辑器我试过有些是正常的。
我自己的项目里面目前只引入了antd，刚搭建

**Comment by afc163** [comment]
这个例子不加 width 是对的，因为页面本身没有出现滚动条，视觉上打开对话框也不会抖。

**Comment by CHU295** [comment]
> 这个例子不加 width 是对的，因为页面本身没有出现滚动条，视觉上打开对话框也不会抖。

我突然发现抽屉组件也有这个bug了。。之前好的，我昨天升级了4.3，无法定位问题了、、

**Comment by CHU295** [comment]
> 这个例子不加 width 是对的，因为页面本身没有出现滚动条，视觉上打开对话框也不会抖。

我现在抽屉组件也有这个问题了。
我看了下具体情况是，body没有滚动条，是下面的标签具有滚动条，然后现在这样会导致宽度变化

**Comment by afc163** [comment]
建议给个重现。

**Comment by CHU295** [comment]
> 建议给个重现。

大佬在钉钉交流群吗？我昨天发过视频

**Comment by CHU295** [comment]
> 建议给个重现。

定位到问题了，是因为项目里面有fixed定位，比如header。
这种情况下就会导致上面的滚动条消失页面宽度变化。
我刚才试了下吧官网的头部改成fixed，然后也出现了这种问题。

在项目中用fixed定位应该是很常见的情况吧，这种问题后面会当成优化点去解决吗

**Comment by afc163** [comment]
有重现能确定是 bug 就会修复。

**Comment by CHU295** [comment]
> 有重现能确定是 bug 就会修复。

好的辛苦了

**Comment by AboyL** [comment]
> > 有重现能确定是 bug 就会修复。
> 
> 好的辛苦了

这个问题解决了吗？

**Comment by JimmyDrive** [comment]
找到了一个解决方法 在挂载的容器上添加width:100vw   一个取巧的方法

**Comment by ShaoClean** [comment]
> 找到了一个解决方法 在挂载的容器上添加width:100vw 一个取巧的方法

牛逼！

**Comment by tclxtommy-hu** [comment]
> width:100vw

这个思路可以，挂载在body上，我就在body上添加了 <body style="width: calc(100% - 17px);">
