### ISSUE TITLE
menu-multiple

### ISSUE THREAD

**Issue by guoguoorange** [ant-design/ant-design#24579]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/menu/index.tsx](https://github.com/ant-design/ant-design/blob/master/components/menu/index.tsx)

### Steps to reproduce
not multiple

### What is expected?
menu compont support multiple

### What is actually happening?
only has props name multiple，but not use。

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 4.2.5 |
| System | windows |
| Browser | Google  |

---
菜单组件文档里面有多选的入参，但是源码里面只是接受了该参数，并没有应用，多选无效。

**Comment by afc163** [comment]
<img width="627" alt="image" src="https://user-images.githubusercontent.com/507615/83244440-f3476280-a1d1-11ea-8745-c7ff1634f8f4.png">

https://codesandbox.io/s/neiqiancaidan-ant-design-demo-uqpom?file=/index.js 有效。
