### ISSUE TITLE
table组件是否可以增加鼠标拖动批量选择功能？

### ISSUE THREAD

**Issue by AboyL** [ant-design/ant-design#24575]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
减少用户的操作

在现在大部分的桌面系统中 都支持通过鼠标来批量选择的功能，例如文件、文件夹操作等

例如用户需要选择3-7行的表格数据

不使用该功能需要5次点击

而增加该功能则只需要一次点击

### What does the proposed API look like?
按住列表的某行的chooseBox

然后进行上下拖动可以对内容进行select

可以在拖动的时候进行select或者在最后松开鼠标的时候进行select操作，而在拖动的时候只进行操作反馈

可以提供一个dragChoose来进行开启或者关闭(或者内置)

如果认为该功能不好，希望可以给一个说明。

**Comment by afc163** [comment]
是可以试试按住 <kdb>shift</kdb> 点击第一行，再按住 <kdb>shift</kdb> 点击最后一行，可以批量选择中间所有行。

**Comment by wteam-xq** [comment]
> 你可以试试按住 shift 点击第一行，再按住 shift 点击最后一行，可以批量选择中间所有行。

实际上， 数据分析经常需要 选择部分列，这样shift就无法满足。 例如： 复制 第2~3行， 4~5列数据， 现在就无法支持。
