### ISSUE TITLE
Steps mismatch in color transitions on hover

### ISSUE THREAD

**Issue by delyanr** [ant-design/ant-design#24576]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2tbmd)

### Steps to reproduce
Hover over the top right navigation step ("Step 3 waiting for longlong time"). Notice the mismatch in color transitions between (1) the title and the description, and (2) the subtitle.

### What is expected?
All elements transition to the primary color at the same time.

### What is actually happening?
The subtitle transitions instantaneously, while the rest take 0.3 seconds.

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome latest |

---
This should be a super quick fix - basically the .less style does not include the subtitle in the :hover rule with the color transitions.

**Comment by coolstuff-michael** [comment]
https://github.com/ant-design/ant-design/blob/master/components/steps/style/index.less#L157
