### ISSUE TITLE
modal实现需要优化

### ISSUE THREAD

**Issue by CHU295** [ant-design/ant-design#24570]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
modal.confirm的时候回发生

modal打开的时候会在body上面加overflow: hidden;这样导致右边滚动条消失，续而引起页面宽度产生变化，页面视觉上也会产生宽度变化的效果，体验极差

### What does the proposed API look like?
期望打开modal的时候body不会因此改变属性，滚动条依然存在，页面宽度不会被改变

**Comment by yoyo837** [comment]
trace in #24572
