### ISSUE TITLE
Table 的列中 column 的render 不支持添加祖先事件

### ISSUE THREAD

**Issue by zhangwilling** [ant-design/ant-design#2457]
当然也可以用局部的 pubsub的模式去解决，但是我绝得antdesign可以解决这个问题。
如下是某个column的数据，见render

```
 {
  title: '操作',
  key: 'operation',
  render: (text, record) => {
       return (
           <span>
	     <a href="#">操作一{record.name}</a>
	      <span className="ant-divider"></span>
	      <a href="#">操作二</a>
	      <span className="ant-divider"></span>
	      <a href="#" className="ant-dropdown-link" onClick＝｛this.xxxx｝> //例如这里, console.log(this); 是undefiend。那如果我将事件写在组件内，我该如何获取
	        更多 <Icon type="down" />
	      </a>
	    </span>
	)
}
```

**Comment by afc163** [comment]
你最好给出完整的例子，this 问题一般和 antd 没什么关系。

**Comment by afc163** [comment]
> 例如这里, console.log(this); 是undefiend。那如果我将事件写在组件内，我该如何获取 ...

另外，话最好说完，讲一半让人闹心。

**Comment by afc163** [comment]
你可以参考 https://github.com/ant-design/ant-design/blob/design-pattern/docs/pattern/table/demo/ 这里的例子。

**Comment by zhangwilling** [comment]
哈哈。是我自己的问题，官网的例子，使用的const定义的局部变量。把column写成this.xx就没问题了，我以为必须使用这种局部变量的方式定义，真是不好意思。对了，希望antd能支持表头的行合并，表头有需要分组归类的场景。虽然title支持jsx，也不能达到很好的效果。
