### ISSUE TITLE
Upgrade to rc-util@5.x

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#24582]
See https://github.com/ant-design/ant-design/pull/24584

- [x] antd
- [x] @ant-design/icons
- [x] rc-animate
- [x] rc-cascader
- [x] rc-dialog
- [x] rc-drawer
- [x] rc-field-form
- [x] rc-input-number
- [x] rc-mentions
- [x] rc-notification
- [x] rc-rate
- [x] rc-resize-observer
- [x] rc-select
- [x] rc-slider
- [x] rc-switch
- [x] rc-tree
- [x] rc-tree-select
- [x] rc-trigger
- [x] rc-align
- [x] rc-virtual-list
- [x] rc-picker
- [x] rc-menu
- [x] rc-table

---

1. 升级 minor 版本
2. `rc-resize-observer` `rc-virtual-list` `rc-align` `rc-trigger` `rc-animate` `rc-select` 等升级后，其他组件需要相应更新依赖版本。

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/83256625-5393cf80-a1e5-11ea-870c-7d8a6a35147f.png)
可以带链接 点过去 最好 哈哈

**Comment by zombieJ** [comment]
我从下往上做免得冲突

**Comment by afc163** [comment]
rc-resize-observer 和  rc-field-form 我没有权限。
