### ISSUE TITLE
Menu组件可以禁用键盘事件（keydown）么？

### ISSUE THREAD

**Issue by Garyismonster** [ant-design/ant-design#2458]
文档中没有找到，禁用是click和keydown一起禁用

Thx

**Comment by benjycui** [comment]
目前无法单独禁用 Menu 的按键行为（如果你指的是通过方向键之类选择菜单项）。

不知道你禁用的理由是？

**Comment by afc163** [comment]
http://github.com/react-component/menu 里不支持，欢迎去 PR ~
