### ISSUE TITLE
DatePicker with dayjs cannot get correct locale from ConfigProvider

### ISSUE THREAD

**Issue by promer94** [ant-design/ant-design#24596]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wrong-locale-5m8hs?file=/index.tsx:201-215)

### Steps to reproduce
Open DatePicker

### What is expected?
DatePickers should show Chinese locale
![4ULiYwyevgztNFk](https://vip1.loli.net/2020/05/30/4ULiYwyevgztNFk.jpg)

### What is actually happening?
DatePicker with dayjs still shows the default locale
![IR51l4kOFDSs67C](https://vip1.loli.net/2020/05/30/IR51l4kOFDSs67C.png)

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | macos 10.15.3 |
| Browser | Edge Version 83.0.478.37 |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/wrong-locale-7f192?file=/index.tsx
