### ISSUE TITLE
Checkbox and Radio error styles don't match other form elements

### ISSUE THREAD

**Issue by keithort** [ant-design/ant-design#24590]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-surf-di8sp?file=/index.js)

### Steps to reproduce
1. Create a form with the Checkbox and/or Radio component.
1. Submit the form without marking either component

### What is expected?
The border color for the components should match that of the Input, InputNumber, and Select components, . 

### What is actually happening?
The border color stays the standard grey color of the non-error component

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | latest |
| System | any |
| Browser | any |

**Comment by swarajpure** [comment]
Which border color are you talking about?

I didn't understand the exact problem.

**Comment by keithort** [comment]
@swarajpure The HTML elements are visually hidden by Ant. The border is used to actually draw the checkbox and radio buttons. 
See [checkbox css](https://github.com/ant-design/ant-design/blob/3.26.17/components/checkbox/style/mixin.less#L51) and [radio css](https://github.com/ant-design/ant-design/blob/3.26.17/components/radio/style/index.less#L54)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/26849
