### ISSUE TITLE
Table selectedRowKeys 数据无缓存，state存储如何区分取消还是选中

### ISSUE THREAD

**Issue by WanAn0902** [ant-design/ant-design#24595]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vbltc?file=/index.js:873-887)

### Steps to reproduce
第一页选中一条数据，第二页再选一条数据，此时打印的selectedKeys没有缓存

### What is expected?
如果设计selectedKeys是有缓存的，请解决目前我们使用v4.2.5版本中没有缓存的问题，
如果设计selectedKeys没有缓存，我们自己将selectedRowKeys放在state里，那如何区别当前操作是选中还是取消选中？可否出一个正确的官方例子

### What is actually happening?
文档上的例子，第一页选中一条数据，第二页再选一条数据，此时打印的selectedKeys是有缓存的。但实际我们用的v4.2.5版本代码中selectedKeys并没有缓存。

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.1 |
| System | macOS 10.15.5 |
| Browser | chrome 84.0.4147.21 |

**Comment by Kermit-Xuan** [comment]
可以用 `onSelect` 中的参数来区分选中还是未选中:

https://codesandbox.io/s/xuanzehecaozuo-ant-design-demo-f1y8r?file=/index.js
