### ISSUE TITLE
使用antd pro v5，更新到 antd 4.3.0 登录报错

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#24613]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design-pro/tree/v5](https://github.com/ant-design/ant-design-pro/tree/v5)

### Steps to reproduce
看 console.log

### What is expected?
能登录进去
删除测试性能代码

### What is actually happening?
登录不进去
console.log有一大堆性能测试的 log

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | react |
| System | windows |
| Browser | chrome |

**Comment by kaoding** [comment]
@afc163

**Comment by kaoding** [comment]
v4.3.0：Tab居"左"了
![image](https://user-images.githubusercontent.com/18542211/83346647-09c7f800-a351-11ea-8faf-608c1760f8b5.png)

以上的版本：Tab居"中"了
![image](https://user-images.githubusercontent.com/18542211/83346672-3f6ce100-a351-11ea-9d38-6a96ed232ad1.png)

**Comment by kaoding** [comment]
v 4.3.0 不是每次都登录不进去，在切换 tab 后（如：账户密码登录、手机号登录），有一个登录了，后面就登录不进去了，是不是修改了以前 tab 的用法了？

**Comment by kaoding** [comment]
![image](https://user-images.githubusercontent.com/18542211/83347101-020a5280-a355-11ea-8498-0ce01dfb9c0c.png)

**Comment by wang1212** [comment]
This framework is not easy to use and not worth using

- No API is provided to override the internal style of the component

It can only be achieved by the parent element and the class name, but the class name in the component has changed too much between minor version updates, which is very bad.

- bundle size is too large

Ironically, few advanced components are provided.

- Color theme is not supported

Not consistent with its so-called corporate framework.

---

Other alternatives are recommended, such as：

[material-ui](https://material-ui.com/)
[React Bootstrap](https://react-bootstrap.github.io/)
[reactstrap](https://reactstrap.github.io/)
...

**Comment by zombieJ** [comment]
@kaoding `rc-field-form` 失误把 debug 信息发包了，已去除。 登录问题 @chenshuai2144 看一下。

**Comment by afc163** [comment]
Tabs 居左的问题呢

**Comment by chenshuai2144** [comment]
试了一下，登录是 ok 的。
@zombieJ  要关注一下云凤蝶了，他们不知道会不会乱掉布局

**Comment by zombieJ** [comment]
> @zombieJ 要关注一下云凤蝶了，他们不知道会不会乱掉布局

不魔改样式是不会影响的

**Comment by zombieJ** [comment]
> Tabs 居左的问题呢

换成 flex 布局后要通过 margin 设置居中：https://codesandbox.io/s/hl5hk?file=/index.css

**Comment by kaoding** [comment]
> 试了一下，登录是 ok 的。
> @zombieJ 要关注一下云凤蝶了，他们不知道会不会乱掉布局

登录是在特定情况下不行的：
切换到手机登录模式，不输入手机号和认证码（空的情况下），再切换回用户名密码模式，这时候填了正确的用户名和密码也登录不了。

**Comment by afc163** [comment]
> 换成 flex 布局后要通过 margin 设置居中：https://codesandbox.io/s/jiben-ant-design-demo-0tvi6

我们应该给一个属性了。

**Comment by zombieJ** [comment]
align right 比较诡异，感觉 tabBarCentered 就够了

**Comment by kaoding** [comment]
已测试，全部修复！
