### ISSUE TITLE
Table x: 'max-content' and x: '1200' not working on google chrome

### ISSUE THREAD

**Issue by surenkhorloo** [ant-design/ant-design#24618]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
React project antdesign table x: 'max-content' not working google chrome browser. But working on firefox

### What is expected?
React project antdesign table x: 'max-content' not working google chrome browser. But working on firefox

### What is actually happening?
React project antdesign table x: 'max-content' not working google chrome browser. But working on firefox

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.12.0 |
| System | 1.1.0 |
| Browser | 83.0.410003.61 |

**Comment by afc163** [comment]
```diff
- x: '1200'
+ x: 1200
```
