### ISSUE TITLE
Antd 4.x Tree with virtual scroll; there could other way to enable virtual scroll as currently, its not possible to style the scroll bar

### ISSUE THREAD

**Issue by abhishekahuja87** [ant-design/ant-design#24626]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/06z85)

### Steps to reproduce
The virtual scroll is enabled by setting "height" prop and with this way the user cannot control the styling of the scroll bar.

### What is expected?
Some other prop to enable virtual scroll so that user can manage the scrollbar styling example: enable on hover etc.

### What is actually happening?
Currently the overflow-y: "auto is set as inline style to the Tree

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Firefox 76.0.1 |

---
I would like to use Tree in a container with scrollbar(X and Y) which get enabled only onhover. I also saw the scrollbar-X get enabled only when the height of Tree is till a certain height but for a very long Tree along overflow-Y, the scrollbar-X is hidden/not available.

**Comment by afc163** [comment]
Try `<Tree virtual={false} />`

**Comment by abhishekahuja87** [comment]
Thanks for reply, I would like to use the virtual functionality i.e. not make it false as the Tree is large. And with the virtual set to true I would like to style the scrollbar as mentioned.

Related defect: https://github.com/ant-design/ant-design/issues/24625

**Comment by abhishekahuja87** [comment]
hi, reason to mark inactive?

**Comment by zombieJ** [comment]
Since new virtual scroll use fake scrollbar with className `ant-tree-list-scrollbar` & `ant-tree-list-scrollbar-thumb`. You can adjust style now.

**Comment by abhishekahuja87** [comment]
Hi, 1 que pls: How can I ensure that the scrollbar is visible only onhover? I am unable to control this behaviour

**Comment by zombieJ** [comment]
Pls feel free to PR for `rc-virtual-list` if want to keep it all the time : )

**Comment by ftoyoshima** [comment]
Is it possible to set `scroll-behavior: smooth` to the virtual scroll? Tried to edit the `.ant-tree` class, but the scroll behavior didn't seem to change
