### ISSUE TITLE
Overview in site

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24629]
缩略图中使用的 组件样式非现有样式。

- border-radius 为 4px

---

如果不碍事，直接关了吧。

**Comment by zombieJ** [comment]
> 如果不碍事，直接关了吧。

看了一下有的是抽象的有的是具象的，看来的确是要统一一下会更好些。

PS：Tabs 组件更新了样式，我做了一下 RTL，帮忙再确认一下哈~

**Comment by zombieJ** [comment]
<img width="446" alt="截屏2020-06-01 上午9 51 17" src="https://user-images.githubusercontent.com/5378891/83369023-7a245700-a3ed-11ea-95e5-d842fc559e5f.png">

**Comment by xrkffgg** [comment]
组件中的语言也可以统一一下
如果用两套图片，就一套全中、一套全英
如果一套，就全英好了

**Comment by xrkffgg** [comment]
> PS：Tabs 组件更新了样式，我做了一下 RTL，帮忙再确认一下哈~

https://ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar

这个样式有问题。以前用的是 `.ant-tabs-bar` 加的 border-bottom

现在这种方式 border-bottom 没加上，active 的 height 也没加上。同样这个的 RTL 也有点小问题。

**Comment by xrkffgg** [comment]
@zombieJ

**Comment by xrkffgg** [comment]
样式里 `>` 影响不少

**Comment by zombieJ** [comment]
> 组件中的语言也可以统一一下
> 如果用两套图片，就一套全中、一套全英
> 如果一套，就全英好了

规范的组件示例里是不使用问题，通过竖线表示。这个的确需要改一改。

**Comment by arvinxx** [comment]
本周我先统一处理下图片文字的样式的问题，用占位符替换。

暗色模式需要额外添加一下暗色模式的图，这个往后排吧
