### ISSUE TITLE
antd源代码编译出错

### ISSUE THREAD

**Issue by ninemilli-song** [ant-design/ant-design#2462]
#### 本地环境
Mac OS

- antd 版本:1.6.5

#### 你期待的结果是：
正确编译结果：
```
dist
├── antd.css
├── antd.css.map
├── antd.js
├── antd.js.map
├── antd.min.css
├── antd.min.css.map
├── antd.min.js
└── antd.min.js.map
```

##### npm install 之后报错：
```
npm ERR! peerinvalid The package eslint@3.1.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-plugin-babel@3.3.0 wants eslint@>=1.0.0
npm ERR! peerinvalid Peer eslint-plugin-jsx-a11y@1.5.5 wants eslint@^2.10.2 || 3.x
npm ERR! peerinvalid Peer eslint-plugin-import@1.11.1 wants eslint@2.x - 3.x
npm ERR! peerinvalid Peer eslint-config-airbnb@9.0.1 wants eslint@^2.9.0
```

**修改package.json 中eslint版本为"eslint": "^2.9.0", 修复上面问题**

##### 运行**npm run compile** 一坨报错类似如下，找不到依赖：

```
components/_util/openAnimation.tsx(1,26): error TS2307: Cannot find module 'css-animation'.
```

但是node_modules中已经存在这些依赖包

##### 运行**npm run dist** 报错如下：

```
ERROR in multi antd.min
    Module not found: Error: Cannot resolve module 'es3ify-loader' in /Users/l/workspace/ReactJs/ant-design
     @ multi antd.min
```

我需要在内网使用ant design，有可能会改动一些代码，所以希望能够使用源码进行编译，但是遇到好多问题，能够帮忙解决么？I need help!!!

**Comment by GrayChoi** [comment]
你最好给个可以重现问题的repository， 你这样提问实在帮不到你。

**Comment by ninemilli-song** [comment]
@GrayChoi <https://github.com/ant-design/ant-design.git> 将代码clone到本地，然后按照我说的方式编译就会出现问题，或者你可以告诉我正确的编译方法，不胜感激！

**Comment by ninemilli-song** [comment]
@GrayChoi 或者您可以告诉我您那里可以正常编译，我就考虑是不是我本地环境的问题了

**Comment by afc163** [comment]
1. peerDependencies 的问题，用 npm@3。
2. master 在正在做 typescript 的改造：https://github.com/ant-design/ant-design/issues/1846 ，未完成，所以会有很多问题，你可以先使用 1.x-stable 分支上的代码。

**Comment by ninemilli-song** [comment]
@afc163 Thanks for your help, I will try! :)

**Comment by ninemilli-song** [comment]
@afc163 Thank you! My question has solved. But, Can you tell me what the difference between the  `"npm run compile"` and `"npm run dist"`. Thank you a lot! 👍
