### ISSUE TITLE
Dynamic hide and display steps not working

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#24627]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-cipnh?file=/steps.jsx)

### Steps to reproduce
Click on the button

### What is expected?
extra steps should appear 

### What is actually happening?
extra steps don't appear 

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome 83 |

**Comment by zombieJ** [comment]
Steps not support Fragment.

**Comment by israelKusayev** [comment]
@zombieJ  thank you it is working good, but when I'm using React.Fragment I get an error about the keys in browser console

![image](https://user-images.githubusercontent.com/42112796/84688602-48140880-af48-11ea-8b24-3a7f3086e74a.png)

**Comment by zombieJ** [comment]
Hi @israelKusayev , pls check `key` if duplicated. If not, could you help to create a new issue about this?
