### ISSUE TITLE
4.3版本tab的hideAdd不生效

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design#24634]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-almeida-3khdh)

### Steps to reproduce
无

### What is expected?
hideAdd可用

### What is actually happening?
hideAdd不可用

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome 84 |

**Comment by xrkffgg** [comment]
本地测试是正常的。
官网和 CodeSandbox 属性无效。是不是 rc-tabs 没更新？

**Comment by afc163** [comment]
Duplicate of #24617

**Comment by xrkffgg** [comment]
没看到 已经修复了啊 😂

**Comment by YinRenjie1993** [comment]
@afc163 
![image](https://user-images.githubusercontent.com/11569655/83379377-f3cc3d00-a40d-11ea-9b67-0dfcad2b3987.png)

**Comment by xrkffgg** [comment]
已经修复了，但是还没发布。

**Comment by YinRenjie1993** [comment]
@xrkffgg 你没问题吗   这个链接 https://codesandbox.io/s/fancy-bash-3dt9g?file=/index.js
![image](https://user-images.githubusercontent.com/11569655/83379506-49084e80-a40e-11ea-88a9-7c4575765004.png)

**Comment by xrkffgg** [comment]
等下一个版本。

**Comment by jonnywang** [comment]
赶紧发布新版本啊

**Comment by chzng** [comment]
antd 4.16.2 中Tabs 的hideAdd也不生效

**Comment by yoyo837** [comment]
> antd 4.16.2 中Tabs 的hideAdd也不生效

上个复现，开个新issue.

**Comment by chzng** [comment]
> > antd 4.16.2 中Tabs 的hideAdd也不生效
> 
> 上个复现，开个新issue.

单单写个demo复现不了了，项目中使用就不行了，试试排除法，看看哪些安装包有冲突导致
