### ISSUE TITLE
andt@1.6.5 使用 webpack 在 production 环境打包后， FormItem 的 onChange 报错

### ISSUE THREAD

**Issue by jerrybendy** [ant-design/ant-design#2463]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本： OS X 10.11.5
- 浏览器及其版本: Chrome 51.0.2704.103

#### 你做了什么？

使用 antd 中的 Form 和 Input 组件， webpack 打包运行一切正常。一旦把环境变量 NODE_ENV 设为 production 再打包后， Input 的 onChange 就会报错 （看起来是 rc-form）的问题

#### 你期待的结果是：

打包生产环境和开发环境的代码行为一致

#### 实际上的结果：

打包成生产环境代码后 onChange 会报错

```
Uncaught TypeError: Cannot read property 'validate' of undefined
```

错误指向的是 ./node_modules/rc-form/lib/createBaseForm.js 的第 69 行，也就是 antd/dist/antd.js 的第 9024 行。 所以应该是 rc-form 中的一个错误

#### 可重现的在线演示

https://github.com/jerrybendy/ant-design-form-bug

因为涉及到 webpack 等，所以就不用 codePen 的演示了。上面的仓库是我重现的一个基本上最小的集合。

 `npm install` 后，如果注释掉 `webpack.config.js` 中第26行设置环境变量的代码，打包后运行，在输入框里输入任意文字或者修改 select 框的选项都是正常的。

添加第26行的设置环境变量的代码后重新打包运行，无论是输入框中输入内容还是修改 select 框的选项，第一次都是正常的，第二次往后都会报错。

**Comment by codering** [comment]
这问题是由于rc-form不能用于纯函数组件。
rc-form的`Note`有说明 http://react-component.github.io/form/
antd Form组件里也有`特别注意` http://ant.design/components/form

感觉都提示的不够明显， 应该字体加大变红！

**Comment by jerrybendy** [comment]
@codering 我试了一下，果然是这样。。改成 class 定义的组件就 OK 了。又翻了下 ant 的文档，找了好久，终于找到了你所说的”特别注意“。。。。谢谢你的帮助  😁

**Comment by jerrybendy** [comment]
@codering  我把 Issue 关啦
