### ISSUE TITLE
New Tabs 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24638]
> PS：Tabs 组件更新了样式，我做了一下 RTL，帮忙再确认一下哈~

https://ant.design/components/tabs-cn/#components-tabs-demo-custom-tab-bar

这个样式有问题。以前用的是 `.ant-tabs-bar` 加的 border-bottom

现在这种方式 border-bottom 没加上，active 的 height 也没加上。同样这个的 RTL 也有点小问题。

**Comment by afc163** [comment]
Duplicate of #24616
