### ISSUE TITLE
Card的api使用extra会显示title的框

### ISSUE THREAD

**Issue by HunterHeroHan** [ant-design/ant-design#24646]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
只想显示一个关闭按钮，不想card上面额外切分出一个块。

### What does the proposed API look like?
可以通过配置把title的框框隐藏掉。

**Comment by yoyo837** [comment]
antd的card本身没有关闭（x）这个设计，你可以二次封装一下，自行提供一个关闭的交互，里面放Card
