### ISSUE TITLE
[Table AJAX] Row selection has been reset when changing pagination

### ISSUE THREAD

**Issue by nghiepit** [ant-design/ant-design#24640]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bug-table-ajax-selection-pagination-ant-design-demo-gw7cl?file=/index.js)

### Steps to reproduce
1. Select a row
2. Next page
3. Select  another a row
4. Check console.log

### What is expected?
The row selected keys should keep when changing the page

### What is actually happening?
The row selected keys have been reset

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.13.1 |
| System | OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
It is intented behavior, Table cannot tell it is a pagiantion change or data complete replacement in remote mode.

**Comment by mikeyshing88** [comment]
@afc163 do you know of any workaround for this? We currently use graphql for our table pagination and we allow users to select rows (from different pages) to export the data to an CSV file. This is currently no longer possible due to this change (as the selections are reset when changing pages)

**Comment by damiangreen** [comment]
This is a breaking change for us

**Comment by clintmilner** [comment]
I don't think this should be closed as I am seeing this issue as well. Keeping selected table rows in state while going from page-to-page is common practice and many of my tables require this functionality.

**Comment by zombieJ** [comment]
This is conflict with #24336. Maybe we should support `selection.dirty` to enable cache the keys which not exist in the list.

**Comment by baozouai** [comment]
以下是我的解决方案
my solution:
这里是自定义hooks => useTableSelect.js
``` javascript
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { message } from 'antd';

export default function useTableSelect(props) {
  const {
    // 数据的key
    rowKey,
    // 是否多选
    isSelectMore,
    // 最大可选多少条
    maxSelected,
  } = props;

  const {
    // 复选框配置
    getCheckboxProps,
    // 选择回调
    selectCallback,
  } = props;

  // 选择数据
  const [select, setSelect] = useState({
    selectedRowKeys: [],
    selectedRows: [],
  });

  // 行选择
  function onSelect(record) {
    // 判断是否有选择框配置
    if (getCheckboxProps) {
      const { disabled } = getCheckboxProps(record);
      // disabled为true则禁止选择
      if (disabled) {
        return;
      }
    }
    let selectedRowKeysTemp;
    let selectedRowsTemp;
    // 这里不能用 const { selectedRowKeys, selectedRows } = state; 否则点击该行页面不render
    if (isSelectMore) {
      selectedRowKeysTemp = [...select.selectedRowKeys];
      selectedRowsTemp = [...select.selectedRows];
      const selectedKey = record[rowKey];
      const index = selectedRowKeysTemp.indexOf(selectedKey);
      // 如果已存在 则去掉
      if (index >= 0) {
        selectedRowKeysTemp.splice(index, 1);
        selectedRowsTemp.splice(index, 1);
      } else {
        // 否则加入
        selectedRowKeysTemp.push(selectedKey);
        selectedRowsTemp.push(record);
      }
      if (!checkMaxLength(selectedRowKeysTemp)) {
        // 判断是否超过最大可选数
        return false;
      }
    } else {
      selectedRowKeysTemp = [record[rowKey]];
      selectedRowsTemp = [record];
    }
    selectCallbacks(selectedRowKeysTemp, selectedRowsTemp);
  }
  // 全选回调
  function onSelectAll(selected, selectedRows, changeRows) {
    let selectedRowKeysTemp = [...select.selectedRowKeys];
    let selectedRowsTemp = [...select.selectedRows];
    const changedKeys = changeRows.map(row => row[rowKey]);
    // 全选
    if (selected) {
      // 过滤掉已选的
      selectedRowKeysTemp = selectedRowKeysTemp.concat(
        changedKeys.filter(key => !selectedRowKeysTemp.includes(key)),
      );
      selectedRowsTemp = selectedRowsTemp.concat(
        changeRows.filter(row => !select.selectedRowKeys.includes(row[rowKey])),
      );
      if (!checkMaxLength(selectedRowKeysTemp)) {
        // 判断是否超过最大可选数
        return false;
      }
    } else {
      // 全不选
      // 去掉已选的
      selectedRowKeysTemp = selectedRowKeysTemp.filter(key => !changedKeys.includes(key));
      selectedRowsTemp = selectedRowsTemp.filter(row => !changedKeys.includes(row[rowKey]));
    }
    selectCallbacks(selectedRowKeysTemp, selectedRowsTemp);
  }
  // 检查是否超过最大可选数量
  function checkMaxLength(selectedRowsKeys) {
    if (maxSelected && selectedRowsKeys.length > maxSelected) {
      message.warning(`最多只能选择${maxSelected}条数据`, 1.5);
      return false;
    }
    return true;
  }
  // 选择回调
  function selectCallbacks(selectedRowKeys = [], selectedRows = []) {
    setSelect({ selectedRowKeys, selectedRows });
    selectCallback(isSelectMore ? selectedRowKeys : selectedRowKeys[0], selectedRows);
  }
  // 清空选择
  function clearSelect() {
    selectCallbacks([], []);
  }
  return {
    ...select,
    onSelect,
    onSelectAll,
    clearSelect,
    selectCallbacks,
  };
}

useTableSelect.defaultProps = {
  rowKey: 'id',
  isSelectMore: true,
  getCheckboxProps: () => {},
  selectCallback: () => {},
};

useTableSelect.propTypes = {
  rowKey: PropTypes.string,
  isSelectMore: PropTypes.bool,
  getCheckboxProps: PropTypes.func,
  selectCallback: PropTypes.func,
};
```

然后在你的列表中引入

```javascript
import useTableSelect from '@/hooks/useTableSelect';
.....
const {
    selectedRowKeys,
    selectedRows,
    onSelect,
    onSelectAll,
    clearSelect,
    selectCallbacks,
  } = useTableSelect({
    rowKey,
    isSelectMore,
    maxSelected,
    getCheckboxProps,
    selectCallback,
  });

...
tableProps.rowSelection = {
      selectedRowKeys,
      onSelect,
      onSelectAll,
      type: isSelectMore ? 'checkbox' : 'radio',
      columnWidth: 30,
      getCheckboxProps,
    };
...
.....


```

**Comment by nghiepit** [comment]
Tks @baozouai,

But, there are too many unnecessary custom code.
Currently, I downgraded to `antd@2.4.2`

**Comment by QuyetAQ** [comment]
@baozouai Thank you.

**Comment by nicholasgriffintn** [comment]
I was just Googling and found this issue first, but in the docs, it looks like there's an option for this in rowSelection now that sorts the issue called preserveSelectedRowKeys.

It's here in the docs:

https://ant.design/components/table/#components-table-demo-ajax

I just tried it and it did the trick for me.

**Comment by Thaianh34** [comment]
> I was just Googling and found this issue first, but in the docs, it looks like there's an option for this in rowSelection now that sorts the issue called preserveSelectedRowKeys.
> 
> It's here in the docs:
> 
> https://ant.design/components/table/#components-table-demo-ajax
> 
> I just tried it and it did the trick for me.

I tried "preserveSelectedRowKeys" and it works for me.

**Comment by ndtan** [comment]
> > I was just Googling and found this issue first, but in the docs, it looks like there's an option for this in rowSelection now that sorts the issue called preserveSelectedRowKeys.
> > It's here in the docs:
> > https://ant.design/components/table/#components-table-demo-ajax
> > I just tried it and it did the trick for me.
> 
> I tried "preserveSelectedRowKeys" and it works for me. Thank you, @nicholasgriffintn

Thank you. You save my day.

**Comment by BaronSmile** [comment]
https://codesandbox.io/s/ajax-antd-5-2-2-forked-jrxbdc?file=/demo.tsx:2774-3150
does not help to save the state check when navigating through pages
