### ISSUE TITLE
Is there a way to put an affixed button on a modal?

### ISSUE THREAD

**Issue by avalladaresm** [ant-design/ant-design#24642]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-fdmt9?file=/Demo.js)

### Steps to reproduce
Reproduction is in link provided; Use a Button component inside an Affix component inside a Modal component with a lot of info to be able to scroll and see the affixed button behavior.

### What is expected?
When modal is open and there's a lot info inside it that scrolling is necessary, I need an affixed button so that the user doesn't have to scroll again all the way up or down to press the X button or the cancel button, so what is expected is that the affixed button shows on top of the modal while scrolling.

### What is actually happening?
The affixed button is staying behind, in a fixed position on top of the modal.

| Environment | Info |
|---|---|
| antd | 4.1.0 |
| React | 16.13.1 |
| System | Ubuntu 20.04 LTS 64-bit |
| Browser | Google Chrome Version 81.0.4044.138 (Official Build) (64-bit) |

**Comment by mjfwebb** [comment]
You could add some CSS to the `ant-modal-body`. Something like:

```.ant-modal-body {
  overflow-y: scroll;
  height: 60vh;
}```

Check this out: https://codesandbox.io/s/antd-reproduction-template-q4xen?file=/index.css:27-84

**Comment by avalladaresm** [comment]
Looks good. I will use it that way, thanks!
Would be cool that it could work the way I explained, though. Is it possible to submit a feature request?
