### ISSUE TITLE
4.3版本  upload组件 内部获取的data不是transformFile 的方法执行之后的data值

### ISSUE THREAD

**Issue by nelling** [ant-design/ant-design#24653]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-dlick)

### Steps to reproduce
上传一个文件，看方式调用顺序

### What is expected?
transformFile方法执行在内部获取data之前

### What is actually happening?
组件内部获取的data 在transformFile方法 之后

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.9.25 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
Did you forget save your codesandbox?

**Comment by nelling** [comment]
> Did you forget save your codesandbox?

https://codesandbox.io/s/antd-reproduction-template-u6jjw

**Comment by zombieJ** [comment]
ref https://github.com/react-component/upload/pull/253

**Comment by zombieJ** [comment]
@Kermit-Xuan

**Comment by Kermit-Xuan** [comment]
OK, 我来修复
