### ISSUE TITLE
表格组件的表头提供位置设置属性

### ISSUE THREAD

**Issue by qiannianv** [ant-design/ant-design#2465]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by afc163** [comment]
`column.className`

http://ant.design/components/table/#components-table-demo-bordered

**Comment by qiannianv** [comment]
这个试过了，但改变的只有表格内的数据居中了，但表头仍然是居左的，我是想让表头也跟着居中
编辑器没法截图吗，很想截图跟你表达一下

**Comment by afc163** [comment]
http://codepen.io/anon/pen/pbLQmr?editors=0110

**Comment by qiannianv** [comment]
谢谢~~  实现了~~

**Comment by afc163** [comment]
:+1:

**Comment by zhonggithub** [comment]
哥们 是怎么做到 列头 居中的？？

**Comment by feilongOnMoudu** [comment]
@qiannianv 你怎么实现让表格组件的表头居中的 我试了 并没有什么用啊？
能附上你写的代码吗？

**Comment by zhonggithub** [comment]
要重写 columns  的className  这样可以实现

.table-column-center-important {
  text-align: center !important;
  font-size: 14px;
}

**Comment by henryzp** [comment]
@afc163 ，为什么不直接提供align参数呢？？

一般来说，可能其他的css很少有操作，align的场景会比较多一些。。

**Comment by afc163** [comment]
@henryzp 可以考虑来个 PR ~

**Comment by henryzp** [comment]
@afc163 https://github.com/react-component/table/pull/137，那个test用例（即tests/__snapshots__)下的文件模板要改一下，我现在的没有修改，导致结果通不过

**Comment by zhongshun89** [comment]
表头居然不能居中,怎么越用这个组件越觉得坑,虽然这个东西是开源的,我并没有资格去抱怨,但觉得这样的坑实在是太不应该了.

**Comment by coryisbest0728** [comment]
@zhongshun89 可以用column的className来设置表头的样式。默认是居左的。

**Comment by zhonggithub** [comment]
@zhongshun89 你用熟悉了就会了。他的官方文档其实是有介绍过的。我以前做c++ 的，没做过web .我刚刚开始用的时候也是到处碰壁，觉得在使用ant 的时候，更应该先了解的他的设计原则和设计哲学。

**Comment by zhongshun89** [comment]
@zhonggithub  我以前也做过c++ ^_^

**Comment by zhongshun89** [comment]
@coryisbest0728 试过了没卵用,算了,我改全局的吧,浪费很多时间,算了.

**Comment by zhongshun89** [comment]
解决办法
在column里面设置<el-table-column  className="column_center">....</el-table-column>   
colume_center 的样式为
  .column_center {
    text-align: center !important;
  }
在vue单文件组件中的<style>模块属性里不能加 scoped 属性,否则依然居中不了.

**Comment by afc163** [comment]
@zhongshun89 别回复错仓库了。

**Comment by afc163** [comment]
trace https://github.com/react-component/table/pull/137

**Comment by afc163** [comment]
@yesmeck 这个在 3.0 里做掉吧。

**Comment by yesmeck** [comment]
https://github.com/react-component/table/commit/f4ff62a36a3ee5d61a9e4d7385bc106f8c4146ac
