### ISSUE TITLE
Error using Radio.Group options: Element type is invalid:

### ISSUE THREAD

**Issue by dcshernandez** [ant-design/ant-design#24656]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/radiogroup-group-optional-ant-design-demo-pipy7?file=/index.js)

### Steps to reproduce
Use an array of options in the Radio.Group component instead of multiple `<Radio></Radio>`
```
     <Radio.Group onChange={this.onChange} value={this.state.value}>
          <Radio value={1}>A</Radio>
          <Radio value={2}>B</Radio>
          <Radio value={3}>C</Radio>
          <Radio value={4}>D</Radio>
        </Radio.Group>

        <Radio.Group
          options={plainOptions}
          onChange={this.onChange1}
          value={value1}
        />
```

### What is expected?
Show radio button options

### What is actually happening?
the app crashes and displays error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.13.1 |
| System | ubuntu 18.04 |
| Browser | Google Chrome Version 81.0.4044.129  |

---
It does not happen with antd 4.2

**Comment by hengkx** [comment]
Strange. Can't restore locally
