### ISSUE TITLE
row组件嵌套table组件后，scroll不生效，没有滚动条

### ISSUE THREAD

**Issue by zt123123** [ant-design/ant-design#24659]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/optimistic-frog-1lx0f)

### Steps to reproduce
just see the result

### What is expected?
the table should have scrollbar

### What is actually happening?
the table no scrollbar

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.13.1 |
| System | macOS |
| Browser | chrome83 |

**Comment by afc163** [comment]
Row has `display: flex` defaultly which will stretch it with children's width, you can try `<Row style={{ display: 'block}} />`
