### ISSUE TITLE
Input component update unexpected when using controlled component

### ISSUE THREAD

**Issue by Kol96** [ant-design/ant-design#24663]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenshiyong-ant-design-demo-f6ur7?file=/index.js)

### Steps to reproduce
Input 0

### What is expected?
Expect nothing happen

### What is actually happening?
Display 0

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.0 |
| System | mac |
| Browser | Chrome81 |

**Comment by Kol96** [comment]
when props.value is undefined, it directly set the inner value

https://github.com/ant-design/ant-design/blob/master/components/input/Input.tsx#L208

**Comment by afc163** [comment]
Your codesandbox works as your expectation:

1. Input 0
2. Nothing happen

**Comment by Kol96** [comment]
switch antd to 4.3

**Comment by afc163** [comment]
We tweak Input controlled behavior in v4 to make sure it works in the same way with native input: https://codesandbox.io/s/jibenshiyong-ant-design-demo-m1xgo?file=/index.js

<img width="733" alt="image" src="https://user-images.githubusercontent.com/507615/83418819-c5268480-a456-11ea-8ddd-0a345926a427.png">

In which React will print warning: `A component is changing an uncontrolled input of type undefined to be controlled.`

```
<input value={undefined}> === <input />
```
