### ISSUE TITLE
Antd build tools append copywrite to all files (including files we wrote)

### ISSUE THREAD

**Issue by jonborchardt** [ant-design/ant-design#24667]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The build tools put the following text in all source code files, including those we wrote or modified substantially:
```
Copyright 2015-present, Alipay, Inc.
All rights reserved.
```

Please consider making this configurable.

### What does the proposed API look like?
This could be a build parameter or a file exclude list in config.

**Comment by zombieJ** [comment]
`@ant-design/tools` is used for antd build only. You can fork to modify for customize usage.

**Comment by jonborchardt** [comment]
Can we modify the copywrite, or is that against your terms and services?

**Comment by zombieJ** [comment]
Noop. `@ant-design/tools` is design for antd build only. We have no plan to extends more ability on it. Pls fork to modify if you have own usage.
