### ISSUE TITLE
Dropdown 组件的 overlay 属性的根组件必须是 Menu ，否则报错

### ISSUE THREAD

**Issue by jiankafei** [ant-design/ant-design#24660]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](http://www.example.com?des=无法提供链接因为无法打开codesandbox.io创建示例)

### Steps to reproduce
Dropdown 组件的 overlay 属性的根组件使用非 Menu 组件

### What is expected?
Dropdown 应该可以使用任何组件和元素作为展示元素

### What is actually happening?
只能使用 Menu

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
这是预期行为，Dropdown 的语义是下拉菜单，必须配合 Menu 才能使用。

**Comment by zombieJ** [comment]
你需要的是 popover： https://ant.design/components/popover-cn/#header

**Comment by xianghongai** [comment]
![Dropdown Menu](https://user-images.githubusercontent.com/2075006/89630356-d74af600-d8d1-11ea-8b55-a1150f253015.png)
@afc163 @zombieJ 

您好，这样的问题如何解决？

**Comment by 07akioni** [comment]
给一个复现链接，看起来不应该

**Comment by xianghongai** [comment]
> 
> 
> 给一个复现链接，看起来不应该

[https://codesandbox.io/s/unruffled-spence-41yxd](https://codesandbox.io/s/unruffled-spence-41yxd?fontsize=14&hidenavigation=1&theme=dark)

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/unruffled-spence-41yxd

看起来内部是判断了节点类型，建议直接用右边的写法，如果有动态需求的话可以写一个函数返回 Menu。

**Comment by afc163** [comment]
https://codesandbox.io/s/charming-drake-7zyug

**Comment by xianghongai** [comment]
> 
> 
> https://codesandbox.io/s/charming-drake-7zyug

机智，github reaction 三连。

**Comment by jiankafei** [comment]
我这边为什么访问不了 codesandbox， 是被墙了吗？

**Comment by 07akioni** [comment]
> 我这边为什么访问不了 codesandbox， 是被墙了吗？

可能就会是网不好

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/charming-drake-7zyug

原来如此hhh
