### ISSUE TITLE
React does not recognize the `dropdownMatchSelectWidth` prop on a DOM element.

### ISSUE THREAD

**Issue by deligent-ant** [ant-design/ant-design#24662]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
tabs 下写 drawer  直接复现

### What is expected?
没报错

### What is actually happening?
React does not recognize the `dropdownMatchSelectWidth` prop on a DOM element.

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.8  |
| System | mac |
| Browser | chrome |

---
tabs 下写 drawer  直接复现

**Comment by yoyo837** [comment]
fixed in #24651

**Comment by deligent-ant** [comment]
no. the warning still exist in v4.3.0

**Comment by yoyo837** [comment]
等待发布

**Comment by yoyo837** [comment]
已发布新版本
