### ISSUE TITLE
DatePicker 在选时间范围时，选择“此刻”时，无法显示时间

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#2467]
#### 本地环境

- antd 版本: 1.6.4
- 操作系统及其版本：win10
- 浏览器及其版本: chrome

#### 你做了什么？

使用DatePicker组件做时间范围选择时，单击“此刻”，当前的时间无法显示在页面上。
如下图：
![1](https://cloud.githubusercontent.com/assets/4525647/17049522/5eb582f2-5020-11e6-9fe7-a476b6331722.png)
![2](https://cloud.githubusercontent.com/assets/4525647/17049530/64f82cd2-5020-11e6-8330-83c7d34a0f02.png)

#### 你期待的结果是：

单击“此刻”能将当前时间正常显示在页面上。

#### 实际上的结果：

单击“此刻”页面上没有显示当前时间。

#### 可重现的在线演示

http://ant.design/components/date-picker#components-date-picker-demo-start-end
官方实例就可复现。

**Comment by afc163** [comment]
duplicate #1902

**Comment by Jimberton-js** [comment]
我更新了版本 datePicker的点击此刻时间 输入框内 还是 无法显示

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1902#issuecomment-234475070

修复版本还未发布。

**Comment by afc163** [comment]
Keep it open until release
