### ISSUE TITLE
Add a less default variables that allows to control the table-font-size

### ISSUE THREAD

**Issue by emil-unimaze** [ant-design/ant-design#24670]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The variables allow changing table font size depending on ConfigProvider's componentSize.

### What does the proposed API look like?
```
@table-font-size-base: 14px;
@table-font-size-lg: @table-font-size-base + 2px;
@table-font-size-sm: 12px;
```

**Comment by morenyang** [comment]
I can take this
