### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by djmisterjon** [ant-design/ant-design#24671]
I see some your demo not work.
Here one !
https://codesandbox.io/s/r1klr?file=/index.js

inside **Context Menu**
https://ant.design/components/dropdown/

**Comment by xrkffgg** [comment]
现在好几个组件的 CodeSandbox Demo 都有问题。
- Dropdown
- Menu
- Checkbox
- Form
- Transfer
- ConfigProvider

**Comment by djmisterjon** [comment]
@xrkffgg 
谢谢你确认我的朋友
并感谢您所做的所有出色工作。
