### ISSUE TITLE
Tabs bug

### ISSUE THREAD

**Issue by lijiehan72** [ant-design/ant-design#24675]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4kjxz)

### Steps to reproduce
<Tabs
          hideAdd
          onChange={this.onChange}
          activeKey={this.state.activeKey}
          type="editable-card"
          onEdit={this.onEdit}
        >
          {this.state.panes.map(pane => (
            <TabPane tab={pane.title} key={pane.key}>
              {pane.content}
            </TabPane>
          ))}
        </Tabs>

### What is expected?
隐藏tabPane ➕ 加号

### What is actually happening?
升级4.0 以后 hideAdd功能失效。

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.8 |
| System | mac |
| Browser | Chrome |

---
希望官方大大 尽快支持下，从2.0陪伴到4.3 了， 忠实铁粉

**Comment by yoyo837** [comment]
Fixed in #24621
