### ISSUE TITLE
The collaborator wiki link out of date

### ISSUE THREAD

**Issue by Rustin-Liu** [ant-design/ant-design#24676]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/wiki/Collaborators](https://github.com/ant-design/ant-design/wiki/Collaborators)

### Steps to reproduce
Open [a list of features](https://github.com/ant-design/ant-design/projects/2)

### What is expected?
Open the project.

### What is actually happening?
Got a 404, it seems the project deleted.

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | None |
| System | None |
| Browser | None |

---
Maybe we can use [issue Feature Request](https://github.com/ant-design/ant-design/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%92%A1+Feature+Request%22)

**Comment by afc163** [comment]
Updated to https://github.com/ant-design/ant-design/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22
