### ISSUE TITLE
[tabs] 4.3.0 tabs 样式问题

### ISSUE THREAD

**Issue by JackLLLLL** [ant-design/ant-design#24679]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-flower-0833f?file=/src/App.js)

### Steps to reproduce
https://codesandbox.io/s/new-flower-0833f

### What is expected?
https://codesandbox.io/s/funny-sunset-xfubr

### What is actually happening?
https://codesandbox.io/s/new-flower-0833f

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.12.0 |
| System | macos |
| Browser | chrome latest |

**Comment by afc163** [comment]
antd 4.3.0 重构了 Tabs，使用 flex 样式重写了，和你在 tabs 上加的自定义的 flex 样式会有冲突，建议删掉或换用其他样式覆盖方案。

**Comment by zombieJ** [comment]
`align-items` 作用于 Flex 和 Grid。在旧版本里 Tabs 是 block，写 `align-items` 是无效的，新版 Tabs 直接去掉即可。

**Comment by JackLLLLL** [comment]
嗯 不好意思 因为之前试着加了个width100%就变正常了 被自己误导了...

**Comment by wendy2017** [comment]
![image](https://user-images.githubusercontent.com/22806386/84997192-d1ae1b00-b180-11ea-8178-89a230838156.png)

**Comment by wendy2017** [comment]
加了 editable-card ，4.3.0 之后的版本，在纯函数组件中报错

**Comment by zombieJ** [comment]
@wendy2017  开个新 issue 给个重现看看哈~
