### ISSUE TITLE
Affix scrolls out of the container

### ISSUE THREAD

**Issue by yandiro** [ant-design/ant-design#24681]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/affix/](https://ant.design/components/affix/)

### Steps to reproduce
Scroll down ultill it is fixed to the top of the container, then scroll down the page (not the container)

### What is expected?
The affix to be inside the container

### What is actually happening?
It gets stuck on the viewport, does not move with the container

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | Your website |
| System | Linux Mint |
| Browser | Firefox, Brave, Chrome |

---
https://imgur.com/BEyCnL2
https://imgur.com/Lyot8nf

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/16125

**Comment by afc163** [comment]
https://ant.design/components/affix/#FAQ
