### ISSUE TITLE
TS写法设置Table ColumnType 的children 属性时，类型检查报错

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design#24680]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-wave-z6qkc)

### Steps to reproduce
使用tsx/ts的写法给Table写多级表头时，ColumnProps的children属性会报错，对应的d.ts的属性为null

--
When writing a multi-level header to the Table using tsx/ts, the children property of ColumnProps will report an error and the corresponding d.ts property is null

### What is expected?
ColumnProps设置children不会报类型检查的错误
--
ColumnProps setting children will not report errors for type checking

### What is actually happening?
ColumnProps设置children会报类型检查的错误
--
ColumnProps setting children will report type check errors

| Environment | Info |
|---|---|
| antd | 4.3.0 |
| React | 16.12.0 |
| System | MacOs |
| Browser |  chrome 83.0.4103.61 |

---
场景：使用ts写多级表头时会出现类型检查的报错
ps：重现链接需要等codesandbox加载完成才可以看到类型检查报警，或者可以再自己本地的编辑器里复现
--
Scenario: When using ts to write a multi-level header, an error of type checking will occur
PS：The reproduction link needs to wait until the codesandbox is loaded before you can see the type check alarm, or you can reproduce it in your local editor

**Comment by zombieJ** [comment]
`ColumnProps` 是 Column 组件，不是 `columns` 属性。`columns` 属性是 `ColumnsType`

**Comment by XiaoJiuDYS** [comment]
类型改成ColumnsType与ColumnGroupType确实不会报类型检查的错误.
是不是API文档上写错了？
![image](https://user-images.githubusercontent.com/36301924/83483901-3c4f2d80-a4d6-11ea-98f4-066e7f4a6076.png)
![image](https://user-images.githubusercontent.com/36301924/83483976-728cad00-a4d6-11ea-87d9-1bb7157bb426.png)

**Comment by zombieJ** [comment]
感谢提醒，我改一下文档
