### ISSUE TITLE
Site code tabs lose padding

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#24694]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-basic](https://ant.design/components/form/#components-form-demo-basic)

### Steps to reproduce
click **Show Code**

### What is expected?
has padding

![image](https://user-images.githubusercontent.com/14831261/83521962-8eae3f80-a512-11ea-8798-8dd4dca4ad93.png)

### What is actually happening?
no padding

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.0 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by afc163** [comment]
这里应该是居中的。

@zombieJ

**Comment by zombieJ** [comment]
嗯

**Comment by zombieJ** [comment]
先用样式改一下，我之后 feature 里把 centered 上了。
