### ISSUE TITLE
Form List returning unecessary data to field value

### ISSUE THREAD

**Issue by ghmendonca** [ant-design/ant-design#24698]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-zcgly?file=/index.js)

### Steps to reproduce
Click to add a new field
Fill the fields
Click the submit button

### What is expected?
Return an array with the objects containing the fields values only

### What is actually happening?
Returning an array with objects which contains the fields values and a lot of other fields

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.8.6 |
| System | Windows 10 |
| Browser | Google Chrome |

---
Probably the values are being filled with some synthetic event, since when you start filling the fields with values you get a lot of this message:

```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `isDefaultPrevented` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
```

**Comment by zombieJ** [comment]
```diff
--- <Button onClick={add} />
+++ <Button onClick={() => { add(); }} />
```

**Comment by Elendiar** [comment]
> +++ <Button onClick={() => { add(); }} />

Omg, I was racking my brains why I have html component object in my list. Because i shortened this to `onClick={add}` and this ruined all.
