### ISSUE TITLE
Menu导航菜单更新defaultSelectedKeys视图没有更新

### ISSUE THREAD

**Issue by Chris-wei** [ant-design/ant-design#24690]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-qksy6?file=/index.js)

### Steps to reproduce
设置defaultSelectedKeys，初始化更改的时候，视图不刷新（上述案例引入Menu会报错）

### What is expected?
视图选中更新的 key 

### What is actually happening?
视图不更新，没有选中目标menu

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.8.0 |
| System | window7 |
| Browser | chrome  83.0.4103.61 |

**Comment by afc163** [comment]
#17638
