### ISSUE TITLE
如何实现案例里 complex table 里的例子？

### ISSUE THREAD

**Issue by fomenyesu** [ant-design/ant-design#2469]
#### 本地环境

- antd 版本:1.1.0
- 操作系统及其版本：windows7 32位
- 浏览器及其版本: chrome

#### 你做了什么？

使用antd的表格组件。

#### 你期待的结果是：

像官网里面的complex table 实现复杂表头的案例

#### 实际上的结果：

无法实现，也对应的源码实例

#### 可重现的在线演示
无

我想问的是，antd通过什么方法实现复杂表头的表格？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1430

不是所有的规范都已经实现了的。
