### ISSUE TITLE
Radio.Button typescript - can't find onClick attribute

### ISSUE THREAD

**Issue by FBenaziz** [ant-design/ant-design#24692]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-0sw2i?file=/index.js)

### Steps to reproduce
I can't reproduce it on the sandbox, there is no typescript check.

You just need to add an onClick on the Radio.Button

### What is expected?
onClick should be in the props of Radio.Button in the typescript

### What is actually happening?
I have a typescript error on the onClick.

```tsx
/// <reference types="react" />
import Group from './group';
import Button from './radioButton';
import { RadioProps } from './interface';
export * from './interface';
interface CompoundedComponent extends React.ForwardRefExoticComponent<RadioProps & React.RefAttributes<HTMLElement>> {
    Group: typeof Group;
    Button: typeof Group;
}
declare const Radio: CompoundedComponent;
export { Button, Group };
export default Radio;
```

Group and Button have both "typeof Group"
I think Button should be "typeof Button" 

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | react 16.13.1 |
| System | Ubuntu 18.04 |
| Browser | Chromium |

**Comment by abenhamdine** [comment]
ok ! le fix est là https://github.com/ant-design/ant-design/pull/24693

**Comment by FBenaziz** [comment]
Thank you for your work, you are amazing ! :)
