### ISSUE TITLE
紧凑模式能否调整字体大小为14px

### ISSUE THREAD

**Issue by jeessy2** [ant-design/ant-design#24705]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
12px看见有点小
### What does the proposed API look like?
能自由调整最好

**Comment by afc163** [comment]
在紧凑模式基础上修改 @font-size-base 主题变量就行了。

**Comment by jeessy2** [comment]
使用的以下那模式， 加了@font-size-base没有用。
```
modifyVars: getThemeVariables({
     compact: true, // 紧凑模式
}),
```

**Comment by yoyo837** [comment]
```js
modifyVars: {
... getThemeVariables({
     compact: true, // 紧凑模式
}),
覆盖key：value
}
```

这样呢？

**Comment by jeessy2** [comment]
> ```js
> modifyVars: {
>   ...getThemeVariables({
>      compact: true, // 紧凑模式
>   }),
>   '@font-size-base'：'14px'
> }
> ```
> 
> 这样呢？
看了代码，这样可以。
