### ISSUE TITLE
Multiple times rendered Button hangs in loading state if loading prop is set back to false quicker than set 'delay'

### ISSUE THREAD

**Issue by alesn** [ant-design/ant-design#24708]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hogrp?file=/index.js)

### Steps to reproduce
This is a follow-up bug report to https://github.com/ant-design/ant-design/issues/24669 which was resolved for a simple case but the problem remains even in 4.3.1 if the Button is rendered multiple times with 'loading' prop set to {delay: <number>}. There are more details in the linked issue. 

To reproduce the still unresolved problem use the provided minimal reproduction link. "Double click" 'Start loading with delay' button (click it quickly twice) and then quickly click 'Finish loading'. Watch the Primary button as it hangs in never ending 'loading' state.
When this gets resolved, test it again with multiple quick clicks on 'Start loading with delay' and then quickly clicking 'Finish loading'

### What is expected?
After loading finishes ('loading' prop of Button is set to false), Button stops being in 'loading' state (stops spinning the loading icon)

### What is actually happening?
Button hangs in 'loading' state with spinning 'loading icon' forever

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | latest |
| System | Windows 10 |
| Browser | Chrome-latest; independent of browser |

**Comment by zombieJ** [comment]
@alesn,
Nice catch! Thanks for report.
