### ISSUE TITLE
Space 有推荐写法占满整行吗？

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#24717]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-austin-b4fls?file=/index.js)

### Steps to reproduce
无

### What is expected?
![image](https://user-images.githubusercontent.com/7971419/83703047-fb275c80-a640-11ea-89cd-c4b40f0c2133.png)
占满整行

### What is actually happening?
没有

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/demo-snap-xxx-7nvv8?file=/index.js

**Comment by crazyair** [comment]
其实不是想要这个

**Comment by zombieJ** [comment]
你这个应该用 Row & Col。Space 是内联的，不作子元素拉伸。
