### ISSUE TITLE
Table 中展开功能需要key从1开始

### ISSUE THREAD

**Issue by Witee** [ant-design/ant-design#2471]
import { Table } from 'antd';

const columns = [
  { title: '姓名', dataIndex: 'name', key: 'name' },
  { title: '年龄', dataIndex: 'age', key: 'age' },
  { title: '住址', dataIndex: 'address', key: 'address' },
  { title: '操作', dataIndex: '', key: 'x', render: () => <a href="#">删除</a> },
];

const data = [
  { key: 1, name: '胡彦斌', age: 32, address: '西湖区湖底公园1号', description: '我是胡彦斌，今年32岁，住在西湖区湖底公园1号。' },
  { key: 2, name: '吴彦祖', age: 42, address: '西湖区湖底公园2号', description: '我是吴彦祖，今年42岁，住在西湖区湖底公园2号。' },
  { key: 3, name: '李大嘴', age: 32, address: '西湖区湖底公园3号', description: '我是李大嘴，今年32岁，住在西湖区湖底公园3号。' },
];

ReactDOM.render(
  <Table columns={columns}
    expandedRowRender={record => <p>{record.description}</p>}
    dataSource={data}
    className="table"
  />
, mountNode);

以上是官方的例子，发现data的key从0开始写的话，0的那列点+号就无法展开，key+1就可以了，不影响使用，算不算个小的bug

**Comment by Witee** [comment]
Fixed ?

**Comment by benjycui** [comment]
试下 1.7.0

**Comment by Witee** [comment]
从1.6.4升级到1.8.0了，这个问题解决了。感谢
