### ISSUE TITLE
NavLinks not working inside notification method

### ISSUE THREAD

**Issue by rahuls360** [ant-design/ant-design#24712]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/navlink-not-working-inside-notification-antd-3-q1gpc)

### Steps to reproduce
1) Click on Button
2) Get error message [Invariant failed: You should not use <NavLink> outside a <Router>]

### What is expected?
1) Show the notification toaster
2) Clicking on Go to Page 2, must route the user to page 2.

### What is actually happening?
Showing error message
My entire application is wrapped around <BrowserRouter />, so I don't know why it wants to to wrap it again.

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
Try https://ant.design/components/notification/#components-notification-demo-hooks
