### ISSUE TITLE
建议Button组件的focus状态使用outline实现，而非background-color高亮

### ISSUE THREAD

**Issue by cw1997** [ant-design/ant-design#24710]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前Button进入focus状态后的行为是：若type为primary，则background-color亮度降低颜色等级（例如从primary-6降低到primary-4），若type为default或者其他，则将border-color修改为primary-6。link则几乎看不出任何差别。我认为这样的表现没有一致性。并且有视觉上的缺陷，例如primary的focus状态，在对比度或亮度较低的LCD屏幕上显示反查非常小。
同时在设计上也会有冲突，例如很多场合下需要一个border-color为primary-6，background-color为#fff的按钮（参考知乎问题页面的【写回答】按钮），但是目前type为default的Button的focus状态样式占据了这个设计空间。
antd其他一些组件也存在类似问题，例如checkbox在checked状态下，getfocus行为和lostfocus行为几乎看不出任何差别。这样违反了无障碍设计的原则，对于无鼠标，纯键盘tab操作的页面来说会有很大问题。

本人看到Chrome新版本修改了默认表单控件的focus状态在dark mode和light mode下的不同表现（为亮白色或者深黑色的outline-color，而非之前的暗蓝色），有所启发，若各位有其他的设计想法也欢迎讨论！

### What does the proposed API look like?
border-color, outline

**Comment by afc163** [comment]
加了 outline 之后会被设计师认为是 bug...

**Comment by zombieJ** [comment]
v4 有积累一些鼠标聚焦和键盘聚焦的区分经验，不过 `:focus-visible` 也快了。所以还会再等等。

**Comment by cw1997** [comment]
> 加了 outline 之后会被设计师认为是 bug...

为什么会被认为是BUG呢？:-o
我观察过从Chrome默认样式，到Bootstrap，Material-ui等css框架，一直都是沿用outline作为focus状态的样式，Microsoft Windows上的focus状态样式实际上也是一个offset为负数，style为dash-dot的outline。通过outline作为focus状态样式应该已经形成了一种共识吧。

**Comment by yingxirz** [comment]
其实是有道理的，antd 的交互反馈很多不太一致：
我理解 focus 和 hover 是两个样式，应该分离，所以这里存在两个问题：
1）hover 状态下 @blue-4 的颜色不符合无障碍要求；
2）focus 状态样式反馈不统一；

🙆‍♂️ 这个两个问题记下来了

**Comment by afc163** [comment]
<img width="582" alt="图片" src="https://github.com/ant-design/ant-design/assets/507615/7ad3eeb1-2750-4b56-953a-4f5dfca6414d">

5.x 已经改成 outline 了。
