### ISSUE TITLE
Focus height of textarea in edge

### ISSUE THREAD

**Issue by zhengyangkang** [ant-design/ant-design#24728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
Open the antd official website in edge, select the input component, adjust the browser width, make the textarea's placeholder text greater than or equal to 2 lines, and click textarea to get the focus

用edge打开antd官网，选择Input组件，调整浏览器宽度使textarea的placeholder文本大于等于2行，点击textarea获得焦点

### What is expected?
Focus on the first line

焦点定位在第一行

### What is actually happening?
Focus on the last line of the placeholder

焦点定位在placeholder的最后一行

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.1 |
| System | win10 |
| Browser | Edge/44.18362.449.0 |

**Comment by zhengyangkang** [comment]
![image](https://user-images.githubusercontent.com/15917367/83738303-b6261900-a686-11ea-83fa-7e2decedb033.png)

**Comment by zombieJ** [comment]
这么神奇？输入文字后光标是什么位置？

**Comment by zhengyangkang** [comment]
@zombieJ 比如placeholder一共2行，value为空的时候焦点就在第二行，输入内容后会自动回到第一行

**Comment by zombieJ** [comment]
感觉像是 Edge bug，`placeholder` 用的是原生的属性，没有黑魔法……

**Comment by zhengyangkang** [comment]
额  好像还真的是。。。
