### ISSUE TITLE
datepicker日历不显示中文

### ISSUE THREAD

**Issue by MingRock** [ant-design/ant-design#24721]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-tw8qz)

### Steps to reproduce
-

### What is expected?
显示中文

### What is actually happening?
英文显示

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-hfc84?file=/index.js
