### ISSUE TITLE
Lots of Errors when using Material UI Component in Antd Menu Item

### ISSUE THREAD

**Issue by awarmfastbear** [ant-design/ant-design#24723]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate. 

This is as close as I can find to be related but the conclusion was that it shouldn't happen with components, only vanilla html elements: https://github.com/ant-design/ant-design/issues/8708

### Reproduction link

You'll need to click on the refresh button in the virtual browser to trigger the component mounting.

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/withered-firefly-xf3jr?file=/src/App.js)

### Steps to reproduce
In a new app, add an Antd menu component then add a Material UI List component inside of the menu and you'll get errors.

I am using this MaterialUI List component because I want my Nav buttons to have ripple effects. In my app this renders fine but it throws a bunch of errors as seen in the Repro link.

### What is expected?
No errors

### What is actually happening?
Not sure.

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.3.1 |
| System | Windows 10 x64 |
| Browser | Firefox 77 |

**Comment by zombieJ** [comment]
Menu only accept `Menu.Item` or `Menu. SubMenu` as children.
