### ISSUE TITLE
如何清空Table sorter 多列排序的状态？

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#24722]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-multiple-sorter](https://ant.design/components/table-cn/#components-table-demo-multiple-sorter)

### Steps to reproduce
提供多列排序, 但是无法统一清空全部列的排序状态
```
   sorter: {
      compare: (a, b) => a.chinese - b.chinese,
      multiple: 3,
    },
```

### What is expected?
统一清空多列排序状态

### What is actually happening?
找不到办法清空

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.12.0 |
| System | macOs |
| Browser | chrome |

**Comment by zombieJ** [comment]
参考 https://ant.design/components/table-cn/#components-table-demo-reset-filter 坐成受控的

**Comment by shuozhang2016** [comment]
@zombieJ 您所提供的这个例子里面sortOrder 是单列排序有效无法运用到多列排序场景，如果加上了这个属性再次点击排序，多列排序功能就失效了

**Comment by zombieJ** [comment]
给个重现看看

**Comment by shuozhang2016** [comment]
https://codesandbox.io/s/recursing-jones-wzlu1?file=/src/App.js

加上了sortOrder属性，多列排序的效果就失效了 @zombieJ

**Comment by zombieJ** [comment]
触发多列排序的时候，`sorter` 返回的是一个数组。
