### ISSUE TITLE
Jest Tests Fails

### ISSUE THREAD

**Issue by helabenkhalfallah** [ant-design/ant-design#24739]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Run jest test

### What is expected?
Test is successful.

### What is actually happening?
```
xxx\front-js\node_modules\our-checkbox\node_modules\antd\es\checkbox\index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Checkbox from './Checkbox';
                                                                                                    ^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (node_modules/our-checkbox/lib/lib/our-checkbox/OurCheckBoxStyled.js:10:40) 
```

The same issue with all antd components.

I tried many Jest configuration but always in fail  :

```
 // An array of regexp pattern strings that
  // are matched against all test paths, matched tests are skipped
  testPathIgnorePatterns: [
    "<rootDir>/node_modules/(?!antd|rc-|css-)",
  ],

  // This option sets the URL for the jsdom environment. It is reflected in properties such as location.href
  testURL: 'http://localhost',

  // An array of regexp pattern strings that are matched against all source file paths, matched files will skip transformation
  transformIgnorePatterns: [
    "<rootDir>/node_modules/(?!antd|rc-|css-)",
  ],
```

I tried also to mock but same issue.

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | React 16.12.0 |
| System | Windows 10 |
| Browser | all |

---
We aren't permitted to share code outside nor share our applications links, have you please an idea ? We have this issue since 4 days :( :( We can't omit unit tests otherwise we will be forced to change antd (we use antd for our design system with styled components). Thank you for your help :)

**Comment by hongthong2** [comment]
good

**Comment by helabenkhalfallah** [comment]
Seriously ? I said that we aren't allowed to share neither code nor application links. If I can do it I do it without reminding me, if it's hard for you to help, I close the issue and I remove antd to use more helpful api. 
Thank you.

**Comment by callumnewlands** [comment]
I know this issue is old, but as it was never resolved, I'll add my thoughts in case anyone else comes across this with the same issue

I had a similar issue (may be the same, or may be different it's difficult to tell from the original error log provided in the issue) with antd 4.24.5 and resolved the issue by changing `import Checkbox from "antd/es/checkbox/Checkbox";` to `import { Checkbox } from "antd";`

My error was:
```[INFO]     Details:
[INFO] 
[INFO]     /home/runner/work/.../node_modules/antd/es/checkbox/Checkbox.js:1
[INFO]     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";
[INFO]                                                                                       ^^^^^^
[INFO] 
[INFO]     SyntaxError: Cannot use import statement outside a module
[INFO] 
[INFO]       18 |     renderCascader
[INFO]       19 | } from "helpers/questionHelpers";
[INFO]     > 20 | import Checkbox from "antd/es/checkbox/Checkbox";
[INFO]          | ^
[INFO]       21 | import { ListForm } from "./ListForm";```

**Comment by mMarcos208** [comment]
Same Issue.

    /home/marconi/Documentos/AgroHUB.UI.Web/node_modules/antd/es/form/style/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import '../../style/index.less';
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

**Comment by hshoja** [comment]
> I know this issue is old, but as it was never resolved, I'll add my thoughts in case anyone else comes across this with the same issue
> 
> I had a similar issue (may be the same, or may be different it's difficult to tell from the original error log provided in the issue) with antd 4.24.5 and resolved the issue by changing `import Checkbox from "antd/es/checkbox/Checkbox";` to `import { Checkbox } from "antd";`
> 
> My error was:
> 
> ```
> [INFO] 
> [INFO]     /home/runner/work/.../node_modules/antd/es/checkbox/Checkbox.js:1
> [INFO]     ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import _defineProperty from "@babel/runtime/helpers/esm/defineProperty";
> [INFO]                                                                                       ^^^^^^
> [INFO] 
> [INFO]     SyntaxError: Cannot use import statement outside a module
> [INFO] 
> [INFO]       18 |     renderCascader
> [INFO]       19 | } from "helpers/questionHelpers";
> [INFO]     > 20 | import Checkbox from "antd/es/checkbox/Checkbox";
> [INFO]          | ^
> [INFO]       21 | import { ListForm } from "./ListForm";```
> ```

I fixed my problem by changing import from  from `antd/lib` instead of `antd/es` 

 https://stackoverflow.com/questions/61781271/jest-wont-transform-the-module-syntaxerror-cannot-use-import-statement-outsi
