### ISSUE TITLE
Impossible to stop propagation on CheckableTag

### ISSUE THREAD

**Issue by faradaytrs** [ant-design/ant-design#24733]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6vph4)

### Steps to reproduce
Click on checkable tag and see that onClick event on parent is being fired

### What is expected?
Expecting onClick to fire and ability to stop propagation

### What is actually happening?
onClick of parent element is fired

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.1 |
| System | Mac Os Catalina |
| Browser | Latest Chrome |

---
Maybe it's worth to provide event object in onChange function

**Comment by zombieJ** [comment]
Your reproduce is not same as your description. Did you forget to save it?

**Comment by faradaytrs** [comment]
It is right now, when you click on Click me Checkable Tag parent click event will be fired

**Comment by zombieJ** [comment]
Still the same as before: 

<img width="473" alt="截屏2020-06-04 下午8 37 44" src="https://user-images.githubusercontent.com/5378891/83757573-3fe3df80-a6a3-11ea-9f89-6df6d0f9e964.png">

**Comment by faradaytrs** [comment]
Okay it seems I forgot to save it yesterday… Please check again. 
https://codesandbox.io/s/antd-reproduction-template-6vph4
