### ISSUE TITLE
form.create配合forwardRef使用时ts提示错误。

### ISSUE THREAD

**Issue by gaoyiniy** [ant-design/ant-design#24736]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inspiring-nightingale-m5fci?file=/src/App.tsx)

### Steps to reproduce
使用form传递ref

### What is expected?
不报错

### What is actually happening?
ts check报错

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | 16.8 |
| System | mac |
| Browser | chrome |

**Comment by yoyo837** [comment]
> #22015

It’s base on v4, not v3.

**Comment by holynewbie** [comment]
how about [wrappedComponentRef](https://github.com/react-component/form#note-use-wrappedcomponentref-instead-of-withref-after-rc-form140) ?

**Comment by gaoyiniy** [comment]
> how about [wrappedComponentRef](https://github.com/react-component/form#note-use-wrappedcomponentref-instead-of-withref-after-rc-form140) ?

yes it works, thx!
