### ISSUE TITLE
Allow form label not to be displayed

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#24735]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes, I don't want to display a label, just as a variable for form validation

### What does the proposed API look like?
[https://codesandbox.io/s/without-label-for-form-grxmv?file=/index.js](https://codesandbox.io/s/without-label-for-form-grxmv?file=/index.js)

**Comment by kaysonwu** [comment]
[https://github.com/ant-design/ant-design/blob/master/components/form/style/index.less#L79](https://github.com/ant-design/ant-design/blob/master/components/form/style/index.less#L79)

```less
&.@{ant-prefix}-col-0 {
    display: none;
}
```

**Comment by afc163** [comment]
你可以用中文，不太能理解你的意思。

**Comment by kaysonwu** [comment]
`label` 有时候我不想显示它，只是单纯的想把它用于表单验证的关键字替换

**Comment by afc163** [comment]
那就不设置 label 就行了。

**Comment by kaysonwu** [comment]
做表单验证的时候，统一设置验证消息，label 可以作为国际化的名称方案，如果不设置就会导致验证消息显示 undefined

**Comment by hengkx** [comment]
`noStyle`属性是干啥的 之前用过 有点忘了 好像有点类似

**Comment by afc163** [comment]
你能给个重现么。

**Comment by kaysonwu** [comment]
`noStyle` 会破坏整体结构，不太适合。 重现： [https://codesandbox.io/s/without-label-for-form-crf4x?file=/index.js](https://codesandbox.io/s/without-label-for-form-crf4x?file=/index.js)

**Comment by kaysonwu** [comment]
将表单  `labelCol`  属性设置为 `{{ span: 0 }}`  目前是无法隐藏的，这只是一个样式 BUG，我并非要报告这个，我要报告的内容就是允许控制 `label` 不去渲染，把它仅当做一个替换表单验证信息的文案

**Comment by kaysonwu** [comment]
![QQ截图20200605163420](https://user-images.githubusercontent.com/14865584/83855285-6f015c00-a74a-11ea-848f-175470de0327.png)

这个是我要的最终呈现结果

**Comment by afc163** [comment]
我建议不设置 label，然后自定义 rule message。

**Comment by kaysonwu** [comment]
我就是觉得每次还要在 规则后面设置  message 好显得多余，虽然个性了，但是对于需要统一文案需求的确实是额外的代码。[https://laravel.com/docs/7.x/validation](https://laravel.com/docs/7.x/validation) 这是我用过最好的表单验证，它的灵活度特别高，让表单验证的关注点在规则验证，而不是在文案

**Comment by afc163** [comment]
可以在 Form 上加个 `hideLabel`，类似 `hideRequiredMark`，来个 PR 如何？

**Comment by kaysonwu** [comment]
我的 PR 被那个 stylelint 插件卡住了。

**Comment by zombieJ** [comment]
不建议加 `hideLabel`，这里的需求是因为不设置 `label` 让模板使用 `${label}` 的显示 `undefined`。应该直接改 locale 的 `validateMessages`。没必要额外加一个 `hideLabel` 属性。

**Comment by kaysonwu** [comment]
@zombieJ  改 `validateMessages`  ？统一文案时是需要提供字段名的

**Comment by zombieJ** [comment]
中文里 `validateMessages` 用的是 `${label}`，你直接改成 `${name}` 就行了。

**Comment by kaysonwu** [comment]
`name` 的本意是字段名，不适合做国际化验证信息的文案。如果非要这样做，必须升级验证插件，可以参考 [https://laravel.com/docs/7.x/validation#custom-error-messages](https://laravel.com/docs/7.x/validation#custom-error-messages)

**Comment by zombieJ** [comment]
可以考虑把 [`messageVariables `](https://github.com/react-component/field-form/blob/3457cc0cd821000d90c3b3fde7b4aa4de96ddf8d/src/Field.tsx#L72) 放出来

**Comment by kaysonwu** [comment]
还是想来吐槽下 `async-validator`，我发现用它来注册一个全局可用的验证规则异常的困难，比如实现下面的需求：

```tsx
<Form.Item
  name="phone"
  rules={[{ required: true, type: 'phone' }]}
>
  <Input
    allowClear
    autoComplete="off" 
  />
</Form.Item>
```

为什么说实现起来困难，主要还是因为 `async-validator`  设计方案存在缺陷，**无法通过组合进行合成一个新的规则**

对于中后台业务，表单验证尤为重要，个人感觉 `async-validator` 已经很难满足需求。扩展性强的验证规则不仅可以提供更好的语义，还能很好的复用，从而减少一些重复的代码

目前虽然可以通过验证器函数实现复用，但是要支持国际化的时候 又显得十分繁琐，如果可以参考 [Laravel](https://github.com/laravel/framework/tree/7.x/src/Illuminate/Validation) 的表单验证器设计，我想将会非常舒适，它的写法将变成如下：

```tsx
<Form.Item
  name="phone"
  rules={['required', 'phone']}
>
  <Input
    allowClear
    autoComplete="off" 
  />
</Form.Item>
````

**Comment by zombieJ** [comment]
> 无法通过组合进行合成一个新的规则

这个能详细描述一下吗？

**Comment by kaysonwu** [comment]
[https://github.com/yiminghe/async-validator/blob/master/src/index.js#L288](https://github.com/yiminghe/async-validator/blob/master/src/index.js#L288) `async-validator` 允许你自己注册一个类型验证器，你注册后，如果要复用它的一些规则比如： `required` 你会有什么感觉？

其次，**一个高级的规则，应该可以由低级的规则组合而成**。目前，表单组件唯一允许扩展自定义规则的方式是：函数。 这个函数存在 **国际化**  验证消息的不足。 

做中后台表单是最常用的，但是我发现规则复用变得异常困难！

**Comment by kaysonwu** [comment]
[https://github.com/laravel/framework/blob/7.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php](https://github.com/laravel/framework/blob/7.x/src/Illuminate/Validation/Concerns/ValidatesAttributes.php)  Laravel 的验证器设计的非常好。

1. 全局性规则注册，使用时可以携带参数
2. 验证器、规则、提示信息分离

但是 `async-validator` 设计是：规则、验证器(实际由多个规则组合而成的)，当你定义一个类型验证规则时，你还必须自己处理 `required` 逻辑

**Comment by zombieJ** [comment]
由于我没有用过 laravel 的 validation，还是不太理解现在遇到的问题是什么。比如这个：
```
rules={['required', 'phone']}
```

和
```
rules={[{ required: true, type: 'phone' }]}
```

区别是什么，什么问题现在会卡住。能多描述一些吗，谢谢~

**Comment by kaysonwu** [comment]
上面的只是写法，我主要想表达的还是：自定义规则扩展性不强的问题

**Comment by kaysonwu** [comment]
我重写写 `FormItem` 试试，看看最终出来的效果是不是要比现在的好用

**Comment by kaysonwu** [comment]
自 `antd@4.7.0` 支持  `messageVariables` 完全可以实现本需求
