### ISSUE TITLE
PlusOutlined 图标 使用浏览器缩放时候会有条线消失

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design#24749]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/summer-brook-egwir?file=/index.js)

### Steps to reproduce
点击浏览器缩放功能 缩小

### What is expected?
正常

### What is actually happening?
不正常

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome 84 |

**Comment by YinRenjie1993** [comment]
![image](https://user-images.githubusercontent.com/11569655/83842028-a6fda480-a734-11ea-90aa-bc41f3c4b360.png)

**Comment by afc163** [comment]
暂时不会对浏览器缩放做特别优化，在 windows 下基本没有办法避免。
