### ISSUE TITLE
Table expandable 去除默认的td标签，允许自定义标签

### ISSUE THREAD

**Issue by 960590968** [ant-design/ant-design#24740]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://s1.ax1x.com/2020/06/05/tDyL8J.png

### What does the proposed API look like?
https://s1.ax1x.com/2020/06/05/tDyL8J.png
解决方式
expandedRowRender:() => {
  rerturn (
<tr>
 <td colSpan={3}></td>
<td></td>
<tr>
)
}

**Comment by afc163** [comment]
暂不支持，可以用 expandIcon 去自定义展开符号。

**Comment by 960590968** [comment]
> 暂不支持，可以用 expandIcon 去自定义展开符号。

需要的是可以合并展开列的单元格：
看一下图片：https://s1.ax1x.com/2020/06/05/tDyL8J.png 
目前Table做不了这样的功能
