### ISSUE TITLE
键盘tab键在form表单里切换到treeSelect时，第一次不被选中

### ISSUE THREAD

**Issue by yyxe** [ant-design/ant-design#24747]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
使用键盘上的tab键切换到treeSelect上，鼠标操作的时候第一次不能选中

### What is expected?
希望第一次操作能触发onchange事件

### What is actually happening?
跟鼠标操作一样。不管第几次操作都能被选中

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | react |
| System | windows |
| Browser | google |

**Comment by afc163** [comment]
> https://u27lec.run.stackblitz.io

I can't open this link.

**Comment by yyxe** [comment]
https://ant-design.gitee.io/components/form-cn/#components-form-demo-nest-messages

**Comment by yyxe** [comment]
https://ant-design.gitee.io/components/form-cn/#components-form-demo-size

**Comment by yyxe** [comment]
wait a moment

**Comment by yyxe** [comment]
https://ant-design.gitee.io/components/form-cn/#components-form-demo-size

**Comment by yyxe** [comment]
如果不能复现。刷新页面再去操作，用tab键切换到treeSelect组件，鼠标操作去选择。

**Comment by afc163** [comment]
我测试几次都是可以 tab 到 TreeSelect 上进行选择的。

**Comment by yyxe** [comment]
@afc163  视频可以看吗？发送一个帮忙看下。。。刷新页面再去操作，用tab键切换到treeSelect组件，鼠标操作去选择。第一次不会被选中，第二次就没问题了。还有就是，如果只用键盘操作或则只用鼠标都没问题。

**Comment by yyxe** [comment]
第一次不可以






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"偏右"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月5日(星期五) 下午4:42
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"zhangxiaolong"<amour1117@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 键盘tab键在form表单里切换到treeSelect时，第一次不被选中 (#24747)





 
我测试几次都是可以 tab 到 TreeSelect 上进行选择的。

**Comment by afc163** [comment]
![1](https://user-images.githubusercontent.com/507615/83862824-0bc8f700-a755-11ea-981f-7174121a97c8.gif)

**Comment by yyxe** [comment]
****刷新页面再去操作（第一次），用tab键切换到treeSelect组件，直接鼠标操作去选择treeSelect（第一次）。

**Comment by afc163** [comment]
我是这么操作的。

**Comment by yyxe** [comment]
![yllhp-vco21](https://user-images.githubusercontent.com/26535795/83866469-6fa1ee80-a75a-11ea-86a9-aec4e6a7b118.gif)

**Comment by yyxe** [comment]
1.每次都是第一次进入页面操作
2.tab键切换的时候不要操作鼠标
3.切换到TreeSelect组件的时候用鼠标操作去选择
4.第一次不被选中

**Comment by afc163** [comment]
看看有没有什么浏览器插件影响了。

**Comment by yyxe** [comment]
没有呢。我测了几个浏览器都不可以。貌似只有TreeSelect组件第一次不会被选中。刚好用户有操作复现这个问题。

**Comment by afc163** [comment]
可以帮忙排查一下，我这里重现不出来。

**Comment by yyxe** [comment]
好的，谢谢了。我们这边测试都有复现过。你可以照着我们操作的步骤去尝试能不能重现或者多找几个人尝试。

**Comment by Kermit-Xuan** [comment]
我这边也复现了

![Jun-05-2020 19-04-45](https://user-images.githubusercontent.com/33770367/83870044-22288000-a760-11ea-8572-b531c05925d4.gif)

**Comment by oceandrama** [comment]
Can confirm it too
