### ISSUE TITLE
将Card.Grid封装成组件后，Card 的bodyStyle中padding:0将失效

### ISSUE THREAD

**Issue by ppmmwozuiai** [ant-design/ant-design#24745]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-banach-1mv6l?file=/src/App.js)

### Steps to reproduce
直接在Card中使用Card.Grid和将Card.Grid封装到其他组件中，bodyStyle会有不同的padding

### What is expected?
padding=0

### What is actually happening?
padding=24px

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.12 |
| System | windows |
| Browser | chrome latest |

**Comment by afc163** [comment]
目前的实现方式很难避免这个问题。

**Comment by afc163** [comment]
看了一下目前的 API 不好解决，建议直接设置 `<Card bodyStyle={{ padding: 0 }} />`
