### ISSUE TITLE
form中的select组件如果添加showSearch={true}属性，出现页面上id重复问题

### ISSUE THREAD

**Issue by haolic** [ant-design/ant-design#24748]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/immutable-grass-3vn8z?file=/index.js)

### Steps to reproduce
Form中绘制一个Form.Item，里边写一个Select并添加showSearch={true}属性, 检查元素会出现重复id问题。

![截图](https://img.alicdn.com/tfs/TB1uKmeJbY1gK0jSZTEXXXDQVXa-1036-1396.png)

### What is expected?
期望只有一个id。（id不重复，从html及js运行角度来讲，页面上出现两个同样id的元素是不正确的。）

### What is actually happening?
出现两个相同id的元素，div 和 input

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | latest |
| System | macOS 10.15.2 |
| Browser | chrome 83.0.4103.61 |

**Comment by Rustin-Liu** [comment]
I am working on this.

**Comment by Rustin-Liu** [comment]
Sorry, I have no time to fix this issue recently because I am looking for a job.

**Comment by haolic** [comment]
I'll follow up on that.

**Comment by haolic** [comment]
> Sorry, I have no time to fix this issue recently because I am looking for a job.


Because I am looking for a job now, I have time to fix this problem.🤣🤣🤣

**Comment by haolic** [comment]
Sorry, I can't find the cause of the problem, please ask someone to fix it.

**Comment by 07akioni** [comment]
not reproduced in `4.x`. `3.x` is no longer maintained. Please migrate to `4.x` instead.
