### ISSUE TITLE
RowKey worked strange when use Google Translate

### ISSUE THREAD

**Issue by sosohime** [ant-design/ant-design#24751]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-kapitsa-5p8y8?file=/index.js)

### Steps to reproduce
```javascript
<Table
       ...
       rowKey={(v, i) => String(i)} // bad code, but it can make rows refresh every time
/>
```
![](https://github.com/sosohime/interview/blob/master/images/tablerowkey.gif?raw=true)

### What is expected?
不确定哪种结果结果才是正确的，见实际结果描述

### What is actually happening?
正常来说按照预期，rowKey如果按照正常key的工作方式，应该导致dataSource变化时，前几列仍维持上次的结果。
目前实际表现是：
    不使用翻译的情况下，整个列表每次都会获得刷新（不符合正常使用key的预期）
    使用翻译的情况下，前几列不会变化（符合正常使用key的预期）

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.12.0 |
| System | macos 10.15.4 |
| Browser | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 |

**Comment by zombieJ** [comment]
谷歌翻译和 React 元素映射会起冲突，antd 这边做不了什么。

**Comment by sosohime** [comment]
（大概是哪里导致key的运行有差异，可以提点一下么

**Comment by afc163** [comment]
https://github.com/facebook/react/issues/11538#issuecomment-417504600
