### ISSUE TITLE
Form 表单组件里面的InputNumber组件输入很长的数字报错TypeError: l.toFixed is not a function

### ISSUE THREAD

**Issue by GKLL** [ant-design/ant-design#24752]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
在动态增减嵌套字段中的数字输入框输入很长的数字出现错误 TypeError: l.toFixed is not a function

### What is expected?
不报错， 在3.x版本不会报错， 在4.x Form表单中会出现

### What is actually happening?
TypeError: l.toFixed is not a function

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | react |
| System | win10 |
| Browser | chrome  84.0.4128.3（正式版本） （32 位） |

---
在3.x版本不会报错

**Comment by fireairforce** [comment]
这个bug不是是我上次改出来的吧。。。。

**Comment by yoyo837** [comment]
> 这个bug不会是我上次改出来的吧。。。。

Yes, https://github.com/react-component/input-number/pull/246

**Comment by fireairforce** [comment]
我来处理一下吧，抱歉~
