### ISSUE TITLE
[v4.3.1] Table scrollx失效.

### ISSUE THREAD

**Issue by crawler-django** [ant-design/ant-design#24755]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-bhaskara-vix6l?file=/index.js)

### Steps to reproduce
例子是官方拿的, 在table组件上添加scroll={{ x: 200 }}  // 一个指定的数值

### What is expected?
表格的总体宽度限制到200.

### What is actually happening?
表格的总体宽度为100%

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome 83 |

**Comment by afc163** [comment]
表单整体宽度建议在 Table 外层进行控制。`scroll.x` 只是针对可能有的滚动区域的。
