### ISSUE TITLE
DatePicker 交互重做，面板和输入框分离，范围选择现可单独选择开始和结束时间。

### ISSUE THREAD

**Issue by PandaJJ5286** [ant-design/ant-design#24750]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wk04r016q8)

### Steps to reproduce
RangePicker可否保留原版本交互，业务场景中，仍然需要原先框选时间范围的交互，可否提供一个选择，或者向下的兼容包。

### What is expected?
可否提供一个选择，或者向下的兼容包，让用户可以自由选择使用哪种交互。

### What is actually happening?
目前只有分离选择的交互，业务反应交互不便

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.1 |
| System | macOS Mojave 10.14.4 (18E224) |
| Browser | chrome 80.0.3987.149 |

**Comment by shuozhang2016** [comment]
同意，确实使用不如以前方便了，已经把表现形式限制住了。比如拿可选7天的需求来说。如果需求是 当点击开始日期，希望用户看到前后7天是可选的。那这个组件就完全没有办法实现了 。用ANTD3就可以轻松实现

**Comment by hellosean1025** [comment]
新的交互被业务疯狂吐槽了

**Comment by hellosean1025** [comment]
@shuozhang2016 @PandaJJ5286 

优化了重新选择时间每次选择都会关闭弹框：
示例：https://codesandbox.io/s/intelligent-mendel-pk2n4?file=/index.js

原理：修改了 rc-picker 部分逻辑
https://github.com/hellosean1025/picker

**Comment by zombieJ** [comment]
Close since `4.4.0` adjust open logic.
