### ISSUE TITLE
Get First Date and Last Date on Panel at Calendar Component

### ISSUE THREAD

**Issue by iyansr** [ant-design/ant-design#24759]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to get first date and last date on panel at calendar component, because in my current project i want to display data from API that need start date and endData, the endpoint of my API is like : `/some/endpoint?startDate=2020-06-05&endDate=2020-06-30` , then the API return list of date with data in range of date (in this case from 2020-06-05 to 2020-06-30). i need to display that data in `dateCellRender` props.

### What does the proposed API look like?
in dateCellRender props, i think it's good to provide some parameters like 

```
dateCellRender=(date: moment, startDate: moment, endDate: moment)

```

**Comment by zombieJ** [comment]
Hi, what's it look like in UI?

**Comment by iyansr** [comment]
> Hi, what's it look like in UI?

i want to display data from API in `dateCellRender` props, it will be similar from [documentation](https://ant.design/components/calendar/#components-calendar-demo-notice-calendar) about `dateCellRender`, but my API provide start date and end date query

**Comment by iyansr** [comment]
> Hi, what's it look like in UI?

url endpoit look like this `/some/endpoint?startDate=2020-06-01&endDate=2020-06-30`

and the response look like this 

```json
{
    "requestAs": null,
    "message": "Success",
    "status": true,
    "code": 200,
    "data": {
        "2020-06-01": {
            "count": 0
        },
        "2020-06-02": {
            "count": 0
        },
        "2020-06-03": {
            "count": 0
        },
        "2020-06-04": {
            "count": 1
        },
        "2020-06-05": {
            "count": 1
        },
        "2020-06-06": {
            "count": 0
        },
        "2020-06-07": {
            "count": 0
        },
        "2020-06-08": {
            "count": 0
        },
        "2020-06-09": {
            "count": 0
        },
        "2020-06-10": {
            "count": 0
        },
        "2020-06-11": {
            "count": 0
        },
        "2020-06-12": {
            "count": 0
        },
        "2020-06-13": {
            "count": 0
        },
        "2020-06-14": {
            "count": 0
        },
        "2020-06-15": {
            "count": 0
        },
        "2020-06-16": {
            "count": 0
        },
        "2020-06-17": {
            "count": 0
        },
        "2020-06-18": {
            "count": 0
        },
        "2020-06-19": {
            "count": 0
        },
        "2020-06-20": {
            "count": 0
        },
        "2020-06-21": {
            "count": 0
        },
        "2020-06-22": {
            "count": 0
        },
        "2020-06-23": {
            "count": 0
        },
        "2020-06-24": {
            "count": 0
        },
        "2020-06-25": {
            "count": 0
        },
        "2020-06-26": {
            "count": 0
        },
        "2020-06-27": {
            "count": 0
        },
        "2020-06-28": {
            "count": 0
        },
        "2020-06-29": {
            "count": 0
        },
        "2020-06-30": {
            "count": 0
        }
    },
    "errors": []
}
```

**Comment by zombieJ** [comment]
Sorry, I still not get the point of first date & last date. Could you describe more about this?

**Comment by iyansr** [comment]
> Sorry, I still not get the point of first date & last date. Could you describe more about this?

Maybe this snippet give you and idea what i mean, sorry.

```javascript
const DetailActivity = () => { 
const [parameters, setParameters] = useState({startDate: '', endDate: ''})

const fetchData = async () => {
		const response =  Axios.get(`/endpoint?${queryString.stringify(parameters)}`)
		console.log(response.data)
	}


  return (
   <Calendar
	getStartDate={(date) => setParameters({ ...parameters, startDate: date.format('YYYY-MM-DD') })}
	getEndDate={(date) => setParameters({ ...parameters, endDate: date.format('YYYY-MM-DD') })}
	dateCellRender={(value) => {
		return <div>
				{/* display data from fetchData() */}
		         </div>
		}}
	/>
 )

}
```

start date and end date that i mean is, 31 May, and 11 July like image bellow,
so, every panel changed, i want to get different start, and end date

![image](https://user-images.githubusercontent.com/42711013/83989307-98073400-a978-11ea-83ea-e7fc73552736.png)

sorry for my bad english

**Comment by zombieJ** [comment]
`getStartDate` or `getEndDate` should not be the api within Calendar since it's not a real event. You can copy `rc-picker` util to get the month first date instead:  https://github.com/react-component/picker/blob/48647028069faf3bfc9fda0b3d2886824b2ca192/src/utils/dateUtil.ts#L158
