### ISSUE TITLE
TabPane's tab rendering as button is very limiting

### ISSUE THREAD

**Issue by mihai-dinculescu** [ant-design/ant-design#24763]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-volhard-ohqzb?file=/index.js)

### Steps to reproduce
Try adding a button inside a TabPane's tab

### What is expected?
It works like it used to in Antd 3.2 or prior.

### What is actually happening?
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | - |
| System | - |
| Browser | - |

---
Caused by https://github.com/ant-design/ant-design/pull/24552

**Comment by zombieJ** [comment]
New Tabs follow accessibility design which use button as TabNode to support keyboard & screen reader with button native ability.

For nest interactive you can follow the [editable Tabs example](https://ant.design/components/tabs/#components-tabs-demo-editable-card) to use `role='button'` instead.


ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role

**Comment by mihai-iotic** [comment]
> 
> 
> New Tabs follow accessibility design which use button as TabNode to support keyboard & screen reader with button native ability.
> 
> For nest interactive you can follow the [editable Tabs example](https://ant.design/components/tabs/#components-tabs-demo-editable-card) to use `role='button'` instead.
> 
> ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role

I'm sorry, I fail to understand how is that supposed to help.

It's all good if `tab="Tab 1"` gets wrapped inside a button.

However, `tab={<Component />}` should not, imho. What if the component contains two buttons?

**Comment by mihai-dinculescu** [comment]
> 
> 
> New Tabs follow accessibility design which use button as TabNode to support keyboard & screen reader with button native ability.
> 
> For nest interactive you can follow the [editable Tabs example](https://ant.design/components/tabs/#components-tabs-demo-editable-card) to use `role='button'` instead.
> 
> ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role

I'm sorry, I fail to understand how is that supposed to help.

It's all good if `tab="Tab 1"` gets wrapped inside a button.

However, `tab={<Component />}` should not, imho. What if the component contains two buttons?

**Comment by mihai-dinculescu** [comment]
@zombieJ

**Comment by zombieJ** [comment]
It's not a good design with nest interactive button for a11y. But you can still ignore this with create a `role='button'` to skip the check:
```diff
<button>
   - <button />
   + <div role="button" />
</button>
```

**Comment by mihai-dinculescu** [comment]
> 
> 
> It's not a good design with nest interactive button for a11y. But you can still ignore this with create a `role='button'` to skip the check:
> 
> ```diff
> <button>
> --  <button />
> ++  <div role="button" />
> </button>
> ```

That is exactly my point. The Ant Tab shouldn't force the user into nesting buttons.

If a string is provided, it should be wrapped in a button. ARIA compliant, just like it works now.
If a React component is provided, it should be wrapped in a div. In this case, it should be the user's responsibility to make the tab ARIA compliant.
