### ISSUE TITLE
Select shifts vertically when searching

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#24760]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-meadow-60ich)

### Steps to reproduce
Focus first Select with showSearch prop and type something in its search input

### What is expected?
Select position doesn't shift when searching

### What is actually happening?
Select element shifts vertically when search input is not empty if there are more inline elements beside it

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16 |
| System | any |
| Browser | any |

---
Setting vertical-align to inline elements would fix it.

**Comment by zombieJ** [comment]
`:after` missing `line-height`
