### ISSUE TITLE
TagProps is missing afterClose property.

### ISSUE THREAD

**Issue by pumanitro** [ant-design/ant-design#24770]
### Reproduction link
[https://github.com/ant-design/ant-design/blob/fd9846a145e19215fe857b74990772e7700422dc/components/tag/index.tsx#L19](https://github.com/ant-design/ant-design/blob/fd9846a145e19215fe857b74990772e7700422dc/components/tag/index.tsx#L19)

### Steps to reproduce
Use <Tag/> component with afterClose property and the newest antd.

### What is expected?
<Tag/> component to have afterClose  property definition type as in documentation:
https://ant.design/components/tag/#header

### What is actually happening?
afterClose property is missing.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.11.0 |
| System | Windows 10 |
| Browser | Chrome 83.0.4103.61 |

**Comment by afc163** [comment]
`afterClose` has removed in v4, we forget to update document.
