### ISSUE TITLE
官方文档修改主题后日期控件出现线框 

### ISSUE THREAD

**Issue by xietongjian** [ant-design/ant-design#24777]
https://ant.design/components/date-picker/  
官方文档修改主题后日期控件出现线框   
重现步骤：  
1、在右下角修改主题色  
![image](https://user-images.githubusercontent.com/16096832/83934078-7f641600-a7e0-11ea-9807-2a1d515bda13.png)
2、访问日期控件出现线框
![image](https://user-images.githubusercontent.com/16096832/83934128-ee416f00-a7e0-11ea-9752-9d368faac4ed.png)

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/955fa520f1ef5e2eed0dfb6c45cb20449a8cc65c/site/theme/template/Layout/Footer.tsx#L362-L398

### 1.开发环境`changeColor()`不起作用。

![image](https://user-images.githubusercontent.com/29775873/83937010-a714a780-a7fb-11ea-922d-3c34eea207c9.png)

分析：开发环境中，由于组件样式放到了 color.less 下方，原有会覆盖 color.less 。

### 2.官网的变更样式。
我看结果类似于 theme 的覆盖。这样有些处理的样式会被覆盖回来。类似于这个 Issue 的情况。
如果通过定制主题覆盖变量的话，应该不会出现这种情况的。

### 3.非直接primary没变

![image](https://user-images.githubusercontent.com/29775873/83937112-741ee380-a7fc-11ea-8508-8891fd6d27ea.png)

https://github.com/ant-design/ant-design/blob/955fa520f1ef5e2eed0dfb6c45cb20449a8cc65c/components/style/themes/default.less#L520

primary 变了，这个没有变。

- 感觉 2、3 的都是由于 变更 的方式 引起的。

**Comment by afc163** [comment]
cc @mzohaibqc

**Comment by mzohaibqc** [comment]
@afc163 looking into this

**Comment by mzohaibqc** [comment]
@afc163 I've fixed the issue and published a new version of `antd-theme-generator@1.2.4`

Kindly update the package and it will be fixed
