### ISSUE TITLE
有一个问题，怎么用refs调用form中的自定义方法呢？

### ISSUE THREAD

**Issue by oz9876** [ant-design/ant-design#2477]
这样一个场景，
表单中有一个按钮，点击后弹出一个弹窗，
选择数据后，弹窗关闭，
需要在表单的一个位置显示刚刚选择的数据，
我的思路是在其父组件用refs调用form中的一个方法，但调不到，
看过大家的提问，但还是毫无头绪。
急急急！！

**Comment by benjycui** [comment]
> 需要在表单的一个位置显示刚刚选择的数据

这个显示出来的数据可编辑么？

**Comment by oz9876** [comment]
不可编辑，随弹窗的选择来改变，提交时当做表单的其中一个值。如果不能使用子父组件传值的方式，改如何实现呢？

**Comment by benjycui** [comment]
在 `Modal` 中收集数据，可以直接在 `Form` 里面使用。

```jsx
<div>
  <Form>
    ...
    <p>{getFieldValue('sth')}</p>
    ...
  </Form>

  <Modal>
    <Select {...getFieldProps('sth', {...})} />
  </Modal>
</div>
```
