### ISSUE TITLE
Not able to create OptGroup in AutoComplete function

### ISSUE THREAD

**Issue by kj96** [ant-design/ant-design#24776]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autocomplete-optgroup-2-06ok0?file=/index.js:1207-1244)

### Steps to reproduce
Try to create OptGroup in AutoComplete function and pass it in dataSource

### What is expected?
Should show OptGroup options in AutoComplete

### What is actually happening?
Doesn't render OptGroup options

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.3.1 |
| System | Arch Linux |
| Browser | Firefox |

---
Works in version 3.26.1

**Comment by zombieJ** [comment]
`dataSource` is an api from v3. v4 use `options` instead. Please refer v4 doc instead.

**Comment by freezing2616** [comment]
where is the optgroup in autocomplete v4

**Comment by swillis12** [comment]
@zombieJ How do you create an OptGroup in AntD v4 Autocomplete:

This is what I had in v3, options are grouped. I can't seem to do this in V4:
![image](https://user-images.githubusercontent.com/35236833/104072162-806a8500-51bf-11eb-8f7c-ec5003001a64.png)
