### ISSUE TITLE
Issue - Upload Control - Press Enter Key - File Select Dialog is opened twice

### ISSUE THREAD

**Issue by santoshmact** [ant-design/ant-design#24771]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://zprnp.csb.app/](https://zprnp.csb.app/)

### Steps to reproduce
1. Navigate to mentioned Sandbox URL.
2. Click Tab Key and navigate to 'Click to Upload' button.
3. Press Enter key
4. File Dialog is opened
5. Click Esc Key. File Dialog will be closed.
6. Automatically another File Dialog will be opened.

### What is expected?
On Enter key press, File Select Dialog/Window should be opened only once.

### What is actually happening?
On Enter key press, File Select Dialog/Window is opening two times.

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.12.0 |
| System | window |
| Browser | Goggle Chrome 83.0 |

**Comment by morenyang** [comment]
I can take this

**Comment by afc163** [comment]
Any progress?
