### ISSUE TITLE
select  suffixIcon does not work

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design#24784]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-roentgen-vvelk?file=/index.js:0-764)

### Steps to reproduce
https://codesandbox.io/s/nice-roentgen-vvelk?file=/index.js:0-764

### What is expected?
work

### What is actually happening?
not work

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome 84 |

**Comment by xrkffgg** [comment]
只适用于单选模式。

**Comment by YinRenjie1993** [comment]
考虑支持下吧。。文档也没说只支持单选

**Comment by zombieJ** [comment]
多选默认没有后缀图标，用 `showArrow` 开启一下。

**Comment by crimson968** [comment]
我使用单选select出现了同样的问题
