### ISSUE TITLE
It is invalid  when dynamically switch the picker property of the DatePicker component

### ISSUE THREAD

**Issue by becarchal** [ant-design/ant-design#24780]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-mestorf-ng6sr?file=/index.js)

### Steps to reproduce
Try to change the picker property by choice, and U will see that nearby DatePicker component is invalid.

### What is expected?
Correctly display the components of the day, month, quarter and year

### What is actually happening?
Doesn't render Correctly

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.12.0 |
| System | macOS Catalina |
| Browser | chrome |

---
We need to dynamically switch from date to year

**Comment by becarchal** [comment]
By debugging this file 'node_modules/rc-picker/es/PickerPanel.js'
`  var _useMergedState5 = useMergedState(function () {
    if (picker === 'time') {
      return 'time';
    }

    return getInternalNextMode('date');
  }, {
    value: mode
  }),`
try to change mode, I have solved this problem。So，when I change the picker, I need to change the mode at the same time。Hope to help others。

**Comment by AuglyXu** [comment]
I've got the same problem. Try to use the following way to render the different instance to achieve the goal temporarily.
`
      {
        picker === "date"  && <DatePicker onChange={onChange} picker="date" />
      }
      {
        picker === "week"  && <DatePicker onChange={onChange} picker="week" />
      }
      {
        picker === "month"  && <DatePicker onChange={onChange} picker="month" />
      }
      {
        picker === "quarter"  && <DatePicker onChange={onChange} picker="quarter" />
      }
      {
        picker === "year"  && <DatePicker onChange={onChange} picker="year" />
      }
`
I have forked the codesandbox and modified it.
https://codesandbox.io/s/priceless-mclaren-m1okx
