### ISSUE TITLE
provide the name of the select component on change handler

### ISSUE THREAD

**Issue by mossa-Sammer** [ant-design/ant-design#24791]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
provide the ability to access the select component name
I want to access the select component name because I have a list of selects

### What does the proposed API look like?
onSelect={(value,option,select)=>{}}

**Comment by yoyo837** [comment]
Do you think What is the difference between `onSelect` and `onChange`?

**Comment by mossa-Sammer** [comment]
@yoyo837  No

**Comment by yoyo837** [comment]
Sorry i can't get the point.

**Comment by mossa-Sammer** [comment]
@yoyo837 just I want to access the select component name in the function ```onSelect```

**Comment by afc163** [comment]
You should learn React first before using antd.

**Comment by mossa-Sammer** [comment]
https://codesandbox.io/s/react-example-8ttk2?file=/index.js
@afc163 
I can't do this in antd why?

**Comment by mossa-Sammer** [comment]
@afc163 seems Antdesign team  have an impolite Children as maintainers
