### ISSUE TITLE
antd not rendering properly in codesandbox 

### ISSUE THREAD

**Issue by hazee007** [ant-design/ant-design#24795]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mutable-rgb-cfy96?file=/src/App.js)

### Steps to reproduce
just click on the link to minimal reproduction

### What is expected?
to render like form-in-modal from https://ant.design/components/form/#components-form-demo-form-in-modal

### What is actually happening?
app not rendering with styles from antd

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google Chrome Version 83.0.4103.61 (Official Build) (64-bit) |

---
this is my first time setting a minimal reproduction with codesandbox i believe that's my issue here, this is not the actual problem i'm trying to get help for, but i have to fix this one first as it's not rendering properly..

**Comment by mjfwebb** [comment]
Add `import "antd/dist/antd.css";` to your imports.

**Comment by hazee007** [comment]
> Add `import "antd/dist/antd.css";` to your imports.

thank you
