### ISSUE TITLE
Timeline 不支持自定义颜色

### ISSUE THREAD

**Issue by yukrain** [ant-design/ant-design#2479]
- antd 版本:1.6.5

 <Timeline.Item color="green">创建服务现场 2015-09-01</Timeline.Item>
color 参数貌似不支持自定义色值

源代码这里好像也只支持三种颜色
https://github.com/ant-design/ant-design/blob/master/components/timeline/TimelineItem.tsx#L43

` <div className={dotClassName} style={{ color: /blue|red|green/.test(color) ? null : color }}>{dot}  </div>
`

**Comment by yeliex** [comment]
`color : 指定圆圈颜色 blue, red, green，或自定义的色值`
