### ISSUE TITLE
Overview some suggest

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24799]
>  For better.

### Button

正常的 Button 有 padding，文字会居中。建议 左右两侧空隙相同。

### Dropdown

下拉按钮不建议和文字重叠。应在后方。

### Select

下拉按钮不建议和文字重叠。

### Calendar

日期不居中。Demo 的例子都是正常的。截个图应该就行。
https://ant.design/components/calendar-cn/

### Popover

Button 左右 padding 问题，同 Button

### Tooptip

提示框中 文字 padding 不一致。

### Tabs

仔细看，截图上半部分是缺失的，还有略微感觉字体和其他的不太一样。

### Alert

第二个的 关闭 按钮位置 异常。

### Message

提示框中文字 padding 异常。应为和图标距离边界相同。

**Comment by xrkffgg** [comment]
神奇了。。。。

Mac 上看到的 这个是正常的。
![image](https://user-images.githubusercontent.com/29775873/83984165-40f86380-a966-11ea-9429-4014889fa69f.png)


Win 上面就是不正常。

![image](https://user-images.githubusercontent.com/29775873/83984190-5a99ab00-a966-11ea-9051-9b308c46dea8.png)

**Comment by arvinxx** [comment]
> 神奇了。。。。
> 
> Mac 上看到的 这个是正常的。
> ![image](https://user-images.githubusercontent.com/29775873/83984165-40f86380-a966-11ea-9429-4014889fa69f.png)
> 
> Win 上面就是不正常。
> 
> ![image](https://user-images.githubusercontent.com/29775873/83984190-5a99ab00-a966-11ea-9051-9b308c46dea8.png)

图用的全部是 SVG，难道 SVG 在 win 和 mac 下的渲染方式不一致？

**Comment by zombieJ** [comment]
@xrkffgg windows 下所有游览器都是这样的吗？

**Comment by xrkffgg** [comment]
win 试了 谷歌、opera、edge 都这样

**Comment by xrkffgg** [comment]
要不直接用 图片 或者 Base64

**Comment by morenyang** [comment]
刚想说这个问题
还以为出什么乱码了
WIndows 10 1909 (我系统是英文)
Chrome 83.0

![image](https://user-images.githubusercontent.com/15653996/83988707-a81e1400-a976-11ea-885b-d8995b3c2583.png)

**Comment by afc163** [comment]
最好用矢量图形画竖线，不要用字符。
