### ISSUE TITLE
Drawer is broken with Release 4.3.2

### ISSUE THREAD

**Issue by dbrrt** [ant-design/ant-design#24797]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/drawer/](https://ant.design/components/drawer/)

### Steps to reproduce
Click on First Open Button in a browser

### What is expected?
No Drawer will appear

### What is actually happening?
Investigation in progress

| Environment | Info |
|---|---|
| antd | 4.3.2 |
| React | 16.10.1 |
| System | Manjaro |
| Browser | Chrome 83.0.4103.61 |

**Comment by jsteenkamp** [comment]
Seeing same issue - Drawer seems to have width/height = NaN.

**Comment by dbrrt** [comment]
Thanks!
