### ISSUE TITLE
Radio.Group 组件 使用 options 选项时 buttonStyle="solid" 不生效

### ISSUE THREAD

**Issue by index-swf** [ant-design/ant-design#24798]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-radio-group-bug-demo-jky90)

### Steps to reproduce
使用 Radio.Groups 组件，并指定 options 和 buttonStyle='solid'

### What is expected?
props.buttonStyle: 'solid' 生效

### What is actually happening?
props.buttonStyle: 'solid' 不生效

| Environment | Info |
|---|---|
| antd | 4.3.2 |
| React | 16.12.0 |
| System | Mac OSX |
| Browser | Chrome 83.0.4103.61 (Official Build) (64-bit) |

**Comment by xrkffgg** [comment]
看了一下，这 2 种样式都需要用 Radio.Button 的。在你的基础上换了种写法。你试试看。

![image](https://user-images.githubusercontent.com/29775873/83960472-ca069080-a8bb-11ea-852e-73d050cffdc1.png)

**Comment by afc163** [comment]
`buttonStyle` 只针对 Radio.Button 生效。`<Radio.Group options={options} />` 本身没有 button 样式，所以无法匹配。

**Comment by xrkffgg** [comment]
我在想是不是可以这样。
如果设置了 buttonStyle，并且使用 options 的方式，我们就 自动启用 Radio.Button，
你觉得呢？
@afc163

**Comment by afc163** [comment]
先支持 `<Radio.Group options={options} component={Radio.Button} />`

再支持 `<Radio.Group options={options} component={Radio.Button} buttonStyle="solid" />`

**Comment by index-swf** [comment]
@xrkffgg 感谢回复，我知道那样写可以，就是懒得再写一个map了，如果能支持指定component应该会方便一点

**Comment by lucasdiaas** [comment]
> 先支持 `<Radio.Group options={options} component={Radio.Button} />`
> 
> 再支持 `<Radio.Group options={options} component={Radio.Button} buttonStyle="solid" />`

I've tried this but apparently the RadioGroup do not have the prop `component`. I got the following typescript error
![typescript-error](https://user-images.githubusercontent.com/22860001/84039931-57a7b600-a978-11ea-9c82-f9cd66b41ca4.png)
