### ISSUE TITLE
Divider misaligned inside Row

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#24794]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/divider-with-title-ant-design-demo-m7omy?file=/index.js)

### Steps to reproduce
Check reproduction link

### What is expected?
Divider properly vertically center aligned to text

### What is actually happening?
Divider appears above below text

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | React |
| System | Windows 10 |
| Browser | Version 1.9.76 Chromium: 81.0.4044.138 (Official Build) (64-bit) |

**Comment by xrkffgg** [comment]
看了下，由于设计的原因，不建议这两个一起使用。
如果你要用的话，可以加上这个
```
.ant-row > .ant-divider-horizontal.ant-divider-with-text::before, 
.ant-row > .ant-divider-horizontal.ant-divider-with-text::after {
  top: 0;
}
```
觉得不太通用，不改代码了。

**Comment by xrkffgg** [comment]
加个ID的话，就更好了。不影响其他。

**Comment by zombieJ** [comment]
<img width="597" alt="截屏2020-06-07 下午1 28 20" src="https://user-images.githubusercontent.com/5378891/83961133-cf1b0e00-a8c2-11ea-8c98-aa74557693d1.png">

**Comment by mjfwebb** [comment]
@zombieJ I can't read the text in your screenshot.

**Comment by xrkffgg** [comment]
### Outline
In the grid system, we define the frame outside the information area based on row and column, to ensure that every area can have stable arrangement.

Following is a brief look at how it works:

- Establish a set of column in the horizontal space defined by row (abbreviated col)

- Your content elements should be placed directly in the col, and only col should be placed directly in row

- The column grid system is a value of 1-24 to represent its range spans. For example, three columns of equal width can be created by <Col span={8} />.

- If the sum of col spans in a row are more than 24, then the overflowing col as a whole will start a new line arrangement.

Our grid systems base on Flex layout to allow the elements within the parent to be aligned horizontally - left, center, right, wide arrangement, and decentralized arrangement. The Grid system also supports vertical alignment - top aligned, vertically centered, bottom-aligned. You can also define the order of elements by using order.

Layout uses a 24 grid layout to define the width of each "box", but does not rigidly adhere to the grid layout.

**Comment by xrkffgg** [comment]
https://ant.design/components/grid/

**Comment by zombieJ** [comment]
> @zombieJ I can't read the text in your screenshot.

OPS. For the reply lines I though both are Chinese and patch the Chinese doc screenshot. Sorry for that.
