### ISSUE TITLE
Updating with form-in-modal

### ISSUE THREAD

**Issue by hazee007** [ant-design/ant-design#24796]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mutable-rgb-cfy96?file=/src/MyModal.js)

### Steps to reproduce
Click on the edit button

### What is expected?
When i click on the edit button i should get the form modal popup with data i want to update in it

### What is actually happening?
model not showing with the initial value i want to update

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google Chrome Version 83.0.4103.61 (Official Build) (64-bit) |

---
i'm using a useEffect to check for the task id and base on that id populate the form modal with the values corresponding to that id.
i'm getting the id but modal is not getting populated

**Comment by zombieJ** [comment]
Your `name` with Form.Item is not align with any of your data set to form.
