### ISSUE TITLE
多列排序在ipad上首次触碰屏幕只会出现排序的tooltip，但是排序并没有被触发，点击第二下才能触发排序, 与PC浏览器不一致

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#24804]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-multiple-sorter](https://ant.design/components/table-cn/#components-table-demo-multiple-sorter)

### Steps to reproduce
用ipad打开浏览器进行多列排序，首次点击并不能激活排序，第二次点击才能进行排序

### What is expected?
首次点击进行排序

### What is actually happening?
与pc端浏览器表现不一致

| Environment | Info |
|---|---|
| antd | 4.3.2 |
| React | 16.12.0 |
| System | ipados |
| Browser | safari |

**Comment by afc163** [comment]
这个是移动设备的特性，我们不好做什么。
