### ISSUE TITLE
Don't treat redundant 'initialValue' at Form.Item level as warning

### ISSUE THREAD

**Issue by dobrynin** [ant-design/ant-design#24818]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, if a field is set w/ initialValues prop on the Form component, and again set at the Form.Item level w/ the `initialValue` prop, Antd logs a verbose warning in the console: `Warning: Form already set 'initialValues' with path 'my_list.0.my_field'. Field can not overwrite it. `

This can be especially obtrusive if you have the same component rendered multiple times, thus causing a big wall of red text.

In my view, I think that setting initialValue at both levels should be viewed as okay usage, and the behavior should stay as is but w/o a warning (i.e. the value at the top level is used instead of the value at the Form.Item) This is the case if you initialize the form state w/ existing data when the Form component is first rendered, but would like a default value at the component level if the field is not initially set. In some places we use `form.getFieldValue` to check whether the field has been initialized, but in other places this would be quite tedious, and generally I think it is not necessary to have to write out this logic.

Please let me know your thoughts, thank you!

### What does the proposed API look like?
No API change. Just stop logging a warning.

**Comment by dobrynin** [comment]
https://codesandbox.io/s/antd-reproduction-template-36s23

**Comment by zombieJ** [comment]
It's by design.

ref https://github.com/react-component/field-form/pull/111

**Comment by dobrynin** [comment]
@zombieJ thanks for the reply. I recognize that it is by design. My request is to change the design because I think what I am suggesting has a valid use case.

**Comment by zombieJ** [comment]
When same field configured initialValue on both Form & Field side. We can not tell what's the best initialValue it should be. Thus it must warning on component side. And warning only trigger once when it's same text. If you get lots of warning, you may to check if it's not need to config `initialValue` on Form or on Field side.
And as above, it's by design. Form component can not tell if it's a miss configured.

**Comment by piyushk96** [comment]
@zombieJ I also have same opinion as @dobrynin. Form's initialValues should override Form.Item's initialValue there is no problem in that but there should not be any warning in this case.

**Comment by zombieJ** [comment]
Since in component side, we can not tell it's a miss setting. You can just ignore this warning since it's dev only.

**Comment by dobrynin** [comment]
My opinion is that the value of this warning does not outweigh the annoyance of this log cluttering the console (or the extra custom logic needed to avoid passing initialValue if the field is already set in initialValues).

**Comment by lb-aivision** [comment]
I also approve @dobrynin use-case.

Furthermore, Antd documentation (https://ant.design/components/form/#Form.Item) states that:

`initialValue | Config sub default value. Form initialValues get higher priority when conflict`

When reading this documentation I assume that current behavior (upper level priority) is expected and totally normal.
Why the warning if the docs tells you exactly what you can expect? It's not like it's a surprise...

If you really want to go for this design, please at least update the documentation.
Maybe there is some side-effects we should know about?

**Comment by luoye-fe** [comment]
遇到同样问题，虽然 `production` 会去掉错误提示，但是开发中 `Form` 复杂后会有一长串 `error`，其实可以把 `error` 改为 `warn` 也能够起到提示开发者的作用。

**Comment by deepakbhattmits** [comment]
Try 
useEffect (()=>setFieldvalues(defalultvalues[0],[defaultValues])
It will initiate your values

**Comment by mleister97** [comment]
same as @NightFox7

**Comment by abechoe** [comment]
Also having this issue. Not sure why this is closed; I also have the use case that @dobrynin mentions and there doesn't seem to be a resolution.

**Comment by lavelee** [comment]
I agree with the comments above. I use this code to suppress log on dev

`console.lib.mjs`
```js
let orgConsoleError = console.error;

export function suppressAntDesignLog() {
  console.error = (...args) => {
    // https://github.com/ant-design/ant-design/issues/24818
    if (String(args[0]).startsWith(`Warning: Form already set 'initialValues' with path`)) return;
    orgConsoleError(...args);
  };
}
```

`app.mjs`
```js
import { suppressAntDesignLog } from '../lib/console.lib.mjs';
if (NODE_ENV !== 'production') suppressAntDesignLog();
... initialization ...

```

**Comment by mathieu-dufour** [comment]
> I also approve @dobrynin use-case.
> 
> Furthermore, Antd documentation (https://ant.design/components/form/#Form.Item) states that:
> 
> `initialValue | Config sub default value. Form initialValues get higher priority when conflict`
> 
> When reading this documentation I assume that current behavior (upper level priority) is expected and totally normal. Why the warning if the docs tells you exactly what you can expect? It's not like it's a surprise...
> 
> If you really want to go for this design, please at least update the documentation. Maybe there is some side-effects we should know about?

+ 1

**Comment by mathieu-dufour** [comment]
> I also approve @dobrynin use-case.
> 
> Furthermore, Antd documentation (https://ant.design/components/form/#Form.Item) states that:
> 
> `initialValue | Config sub default value. Form initialValues get higher priority when conflict`
> 
> When reading this documentation I assume that current behavior (upper level priority) is expected and totally normal. Why the warning if the docs tells you exactly what you can expect? It's not like it's a surprise...
> 
> If you really want to go for this design, please at least update the documentation. Maybe there is some side-effects we should know about?

\+1

**Comment by floatrx** [comment]
Same problem! Everything works fine, but on the first render (with initial values & Form.List), it throws console errors. Muted by console.error monkey patching too! 🙈
