### ISSUE TITLE
官网示例报错

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#24816]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
1. 进入官网，选择 Components。
1. 点击左边菜单 Tabs 进入 Tabs 的示例页。
1. 再点击左边菜单 Table 进入 Table 的示例页。
1. 然后右边的导航菜单直接选择 Drag sorting。

此示例报错：
![2020-06-08_11-56](https://user-images.githubusercontent.com/10294977/83991381-2b436800-a97f-11ea-83fa-2ff93b590958.png)

### What is expected?
不报错？

### What is actually happening?
报错了。

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | latest |
| System | Linux kernel 5.4.38 |
| Browser | Chrome Dev 85.0.4158.4 |

---
目前仅发现从 Tabs 跳过去，然后通过右侧的导航跳转时会触发。如果是手动滚动下去的则不触发，但是点击右边的导航后会立即报错。

**Comment by xrkffgg** [comment]
应该是两个拖拽的互相影响

**Comment by xrkffgg** [comment]
https://github.com/react-dnd/react-dnd/issues/186
