### ISSUE TITLE
一个页面中有多个Table，selectRowKeys怎么区分

### ISSUE THREAD

**Issue by zengze** [ant-design/ant-design#2481]
#### 本地环境

- antd 版本: antd v1.6.4
- 操作系统及其版本：win7 64位
- 浏览器及其版本: Google 51.0.2704.106 m

**Comment by afc163** [comment]
```jsx
<Table selectRowKeys={this.state.selectRowKeysOne} />
<Table selectRowKeys={this.state.selectRowKeysAnother} />
<Table selectRowKeys={this.state.selectRowKeysWhatever} />
```

**Comment by zengze** [comment]
@afc163 
![1](https://cloud.githubusercontent.com/assets/20620151/17082535/a6c95d76-51b4-11e6-8777-d959cb2b03f8.png)
![2](https://cloud.githubusercontent.com/assets/20620151/17082536/a6d452ee-51b4-11e6-83eb-c78a0ad2f217.png)
![3](https://cloud.githubusercontent.com/assets/20620151/17082537/a6dbee28-51b4-11e6-9997-2b0b0d595380.png)
改了之后，各表不影响，但是删除一条记录后Checkbox依然被选中，而selectedRowKeysOne已经被清空。此前使用selectedRowKeys则不会出现这种情况。

**Comment by afc163** [comment]
提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by zengze** [comment]
http://codepen.io/anon/pen/bZrWdV?editors=0010#anon-login

地表水用的selectRowKeysOne，修改或删除后，Checkbox为选中状态
其他特殊用的selectRowKeys，修改或删除后，Checkbox状态正常

**Comment by benjycui** [comment]
```jsx
    for(let i = 0; i < dbsCode.length; i ++){
      dbsData.push({
        key: i, // !!!!
        dbscode: dbsCode[i],
        dbsname: dbsName[i],
      });
    }
```

`key` 应该稳定且唯一，在你的业务中应该是用 dbscode 当作 key。

**Comment by zengze** [comment]
@afc163 
http://codepen.io/anon/pen/bZrWdV?editors=0010#anon-login

**Comment by afc163** [comment]
```diff
    const dbsrowSelection = {
-     selectedRowKeysOne,
+     selectedRowKeys: selectedRowKeysOne,
      onChange: this.onSelectDbskeyChange,
      onSelect: this.onSelectDbsChange,
      onSelectAll: this.onSelectDbsAllChange
    };
```

注意根本没有 `rowSelection.selectedRowKeysOne` 这个 API。
