### ISSUE TITLE
Cascader new style

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#24813]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/507615/83989186-32b34300-a978-11ea-8002-28b3f416a5c9.png">

https://www.heyui.top/component/other/categorypicker

**Comment by xrkffgg** [comment]
感觉应用场景好像只有 地区的选择

**Comment by 07akioni** [comment]
Pros
- 实现起来比较简单
Cons
- `全部`看起来有点困扰
- 菜单的 UI 和键盘操作应该不太好对应
