### ISSUE TITLE
4.x 版本将 List.Item 包装成组件会导致响应式栅格列表无法正常显示， 3.x 版本没有问题

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ant-design/ant-design#24828]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-cerf-kiw7j?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
4.x 版本将 `List.Item` 包装成组件会导致响应式栅格列表无法正常显示，之前 3.x 版本的时候这样使用没有问题的

#### 4.x 版本
[![Edit admiring-cerf-kiw7j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/admiring-cerf-kiw7j?fontsize=14&hidenavigation=1&theme=dark)

显示效果:
![4 x](https://user-images.githubusercontent.com/2703455/83837073-fee1de80-a727-11ea-8878-d267ff4fbe47.gif)

#### 3.x 版本
[![Edit upbeat-goldberg-ueme0](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-goldberg-ueme0?fontsize=14&hidenavigation=1&theme=dark)

显示效果:
![3 x](https://user-images.githubusercontent.com/2703455/83837072-fe494800-a727-11ea-910c-a2eaf732d236.gif)

### What is expected?
ant-col 自动根据浏览器宽度自动加上 width 和 max-width 属性

### What is actually happening?
ant-col  width 和 max-width 属性缺失

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.12 |
| System | win10 |
| Browser | chrome |

本来在这个 [issue](https://github.com/ant-design/ant-design/issues/24553) 里面增加了说明，几天没有看到答复所以单独提了 issue

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/objective-hill-onj6m

**Comment by xiaosongxiaosong** [comment]
issue 已被修复，非常感谢
