### ISSUE TITLE
Upload.Dragger component's drag&drop does not work when "accept" prop is defined

### ISSUE THREAD

**Issue by accnops** [ant-design/ant-design#24826]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ziyf6)

### Steps to reproduce
Once the "accept" prop is added to the Upload.Dragger component, dragging a file to the upload does not work. I did a quick test will all newest libraries (antd 4), it does not work either.

### What is expected?
Only files that fit the accept filter are accepted when drag&dropping.

### What is actually happening?
Now it does not accept any files when the accept prop is added.

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.12.0 |
| System | MacOS 10.15.4 |
| Browser | Google Chrome 81.0.4044.138 |

**Comment by afc163** [comment]
Try `accept="audio/mpeg"`.

https://stackoverflow.com/questions/10688588/which-mime-type-should-i-use-for-mp3

https://codesandbox.io/s/antd-reproduction-template-ziyf6?file=/index.js
