### ISSUE TITLE
Table.columns.fixed 的列中Table.Summary.Row的同列没有跟着浮动

### ISSUE THREAD

**Issue by kamu1** [ant-design/ant-design#24822]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-summary](https://ant.design/components/table-cn/#components-table-demo-summary)

### Steps to reproduce
在示例中代码含 pageData.forEach(...的第一个表格；
1、设置columns[0].fixed = 'left'；
2、设置列头的宽度和Table.scroll.y值呈现出横向滚动条；

在示例中第二个表格
summary相关fixed的列可以浮动，但是颜色没有保持与本行一致

### What is expected?
然后在拖动时，summary相关的列没有跟着dataSource相关数据的列同时固定。

### What is actually happening?
1、summary相关的列与dataSource保持一致的浮动效果；
2、summary相关浮动的列与当前行的背景颜色保持一致；

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16 |
| System | mac |
| Browser | chrome |

---
通过summary.cell来做合计数据行时遇到的问题。

**Comment by kamu1** [comment]
<img width="500" alt="WeChatee1388e2414262f41e52cbfa199fe373" src="https://user-images.githubusercontent.com/13414302/84000366-1246b100-a997-11ea-8450-4d077514e819.png">

**Comment by afc163** [comment]
>  summary相关fixed的列可以浮动，但是颜色没有保持与本行一致

<img width="609" alt="image" src="https://user-images.githubusercontent.com/507615/84004960-efb89600-a99e-11ea-9048-ccf16dfc9882.png">

看上去颜色没有问题。

**Comment by kamu1** [comment]
1、summary相关的列与dataSource保持一致的浮动效果；
复现示例：
https://codesandbox.io/s/quizzical-margulis-gqelj?file=/index.js
2、...第二个关于背景颜色的没有问题，样式是业务自己来写的，是我没注意搞错了，报歉。

**Comment by afc163** [comment]
参照第二个例子写就行了：https://codesandbox.io/s/reverent-dew-voskd?file=/index.css
