### ISSUE TITLE
1.x版本怎样设置语言为中文

### ISSUE THREAD

**Issue by 1870390731** [ant-design/ant-design#24825]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
低版本的antd（1.x）没有ConfigProvider 组件，怎么解决语言的问题，我想设置成中文

### What does the proposed API look like?
提供类似ConfigProvider的组件

**Comment by afc163** [comment]
Please try upgrade to higher version of antd, 1.x is not mantainted any more.
