### ISSUE TITLE
Tabs components nodes change after build

### ISSUE THREAD

**Issue by fightingSunnyGirl** [ant-design/ant-design#24823]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
development to production after build
development nodes :
<div role="tab" aria-disabled="true" aria-selected="false" tabindex="-1" class=" ant-tabs-tab ant-tabs-tab-disabled" id="tab-cg" aria-controls="tabpane-cg">qweqwe</div>

production nodes:
<button type="button" role="tab" aria-selected="false" tabindex="0" disabled="" class="ant-tabs-tab ant-tabs-tab-disabled" id="rc-tabs-0-tab-cg" aria-controls="rc-tabs-0-panel-cg">qweqwe</button>

### What is expected?
same nodes

### What is actually happening?
different

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | react |
| System | mac |
| Browser | all |

**Comment by fightingSunnyGirl** [comment]
development : `<div role="tab" aria-disabled="true" aria-selected="false" tabindex="-1" class=" ant-tabs-tab ant-tabs-tab-disabled" id="tab-cg" aria-controls="tabpane-cg">12323:</div>` 
production:`<button type="button" role="tab" aria-selected="false" tabindex="0" disabled="" class="ant-tabs-tab ant-tabs-tab-disabled" id="rc-tabs-0-tab-cg" aria-controls="rc-tabs-0-panel-cg">123</button>`

**Comment by afc163** [comment]
We refactor Tabs in antd 4.3.0, please upgrade your local node_modules.
