### ISSUE TITLE
InputNumber为0时候就被清空了

### ISSUE THREAD

**Issue by yukrain** [ant-design/ant-design#2483]
版本 antd 1.6.5

`     <InputNumber  size="small"    />`
为0的时候文字会不显示， 其他数字都显示

![2016-07-25 02 30 13](https://cloud.githubusercontent.com/assets/5093226/17085648/08517596-5210-11e6-9229-346072c36831.jpg)

**Comment by benjycui** [comment]
本地测试正常。

![image](https://cloud.githubusercontent.com/assets/3580607/17088752/0fc567aa-5252-11e6-9160-bd4e75bc9621.png)

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2397
