### ISSUE TITLE
antd 默认支持基于 ES modules 的 tree shaking，对于 js 部分，直接引入 import { Button } from 'antd' 就会有按需加载的效果。`未生效`

### ISSUE THREAD

**Issue by ghostjzf** [ant-design/ant-design#24837]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://new-issue.ant.design/](https://new-issue.ant.design/)

### Steps to reproduce
import {Button} from "antd" 

### What is expected?
自动加载样式

### What is actually happening?
并没有自动加载，antd 默认支持基于 ES modules 的 tree shaking，对于 js 部分，直接引入 import { Button } from 'antd' 就会有按需加载的效果，文档上说这句话难道不是不需要babel-plugin-import 的意思吗

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.13 |
| System | MacOS |
| Browser | chrome |

**Comment by afc163** [comment]
对，我们不推荐用 babel-plugin-import 了。

详情见：

https://github.com/ant-design/ant-design/pull/24184 
https://github.com/ant-design/ant-design/issues/23988

**Comment by ghostjzf** [comment]
那现在样式全量引入吗




| |
jiangzhifeng666
|
|
邮箱：jiangzhifeng666@163.com
|

Signature is customized by Netease Mail Master

在2020年06月08日 17:39，偏右 写道：

对，我们不推荐用 babel-plugin-import 了。

详情见：

#24184
#23988

**Comment by afc163** [comment]
对，建议全量引入。

**Comment by feishi20** [comment]
Don't use 'postcss-icss-keyframes' plugin with antd@v4, which may have conflict with some components like Select. https://github.com/ant-design/ant-design/issues/26252

**Comment by zerrol** [comment]
> 对，建议全量引入。

请问样式为什么建议全量引入，不会有影响加载速度的问题吗？

**Comment by yoyo837** [comment]
可能是，css全量zip后也没多大，且一般能利用http缓存，花力气去支持部分引入成本不划算吧，不然你就用babel-plugin-import
