### ISSUE TITLE
手机端标签页 tabPosition="bottom" 无法正常工作

### ISSUE THREAD

**Issue by xiaosongxiaosong** [ant-design/ant-design#24831]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/p4kg3)

### Steps to reproduce
1. 使用单独窗口打开演示夜魔 https://p4kg3.csb.app/
2. F12 打开调试工具，切换成模拟手机后刷新页面
3. 将 tab position 切换成 bottom

### What is expected?
标签在内容下方

### What is actually happening?
切换成 bottom 与 top 显示一致

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.12 |
| System | win10 |
| Browser | chrome |

**Comment by yoyo837** [comment]
当下方位置不够时，会自动往上

**Comment by yoyo837** [comment]
手机下样式切换未成功导致

**Comment by xrkffgg** [comment]
我这里正常阿。

![2020-06-08 17 06 37](https://user-images.githubusercontent.com/29775873/84012675-82126700-a9aa-11ea-8063-f56a1dc4bee7.gif)

**Comment by yoyo837** [comment]
手机 viewport 响应式

**Comment by xrkffgg** [comment]
刷新一下 不行了。。。

**Comment by zombieJ** [comment]
移动端下为了体验考虑，`tabPosition` 自动会变成 `top`。不过似乎 `bottom` 也可以？我调整一下。
