### ISSUE TITLE
Table Column 中如何使用 shouldComponentUpdate 干预重新 Render

### ISSUE THREAD

**Issue by abbish** [ant-design/ant-design#2484]
目前发现在有自定义 Render 方法的 Column 中，每次表格变化都会触发所有 Column Row 重新渲染，导致性能很慢，Issues 中也有类似提问，请问如何使用 shouldComponentUpdate 干预渲染？

Column 定义如下
![screen shot 2016-07-25 at 11 45 43 am](https://cloud.githubusercontent.com/assets/138192/17089966/6c2db8f6-525e-11e6-9fa2-1cb5e788852c.png)

勾选两行，会导致批量重新渲染 （全部数据38行）
![screen shot 2016-07-25 at 11 46 37 am](https://cloud.githubusercontent.com/assets/138192/17089979/8cf007f6-525e-11e6-846c-bc544577306b.png)

![screen shot 2016-07-25 at 11 46 49 am](https://cloud.githubusercontent.com/assets/138192/17089970/758043b0-525e-11e6-9ae5-fabd16c5a303.png)

**Comment by afc163** [comment]
```jsx
render: {
  return <YourCell />;
}
```

```jsx
const YourCell = React.createClass({
  shouldComponentUpdate() {
    ...
  },
  render() {
    ...
  }
})
```
