### ISSUE TITLE
how can i change <Tag/> close icon 

### ISSUE THREAD

**Issue by Niefee** [ant-design/ant-design#24848]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
想修改标签<Tag/>的关闭icon

### What does the proposed API look like?
<Tag closeIcon=<span>X<span/>>

**Comment by afc163** [comment]
What make you need to customize Tag close icon?

**Comment by Niefee** [comment]
@afc163 In order to unify the overall UI design
