### ISSUE TITLE
Drawer style not clean after mask false in developer mode

### ISSUE THREAD

**Issue by hmz22** [ant-design/ant-design#24844]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ibb.co/7NF3pLG](https://ibb.co/7NF3pLG)

### Steps to reproduce
Drawer

### What is expected?
when mask is false and toggle visible false styled most be clear in developer mode

### What is actually happening?
when mask is false and toggle visible false style width still and cant remove it in developer mode but when build the project fixed this issue

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Please remove `yarn.lock` and `package-lock.json` and `node_modules`, then reinstall in development mode.
