### ISSUE TITLE
OptionProps should be exported in Select component

### ISSUE THREAD

**Issue by neemski** [ant-design/ant-design#24854]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/friendly-mendel-gbkml?file=/src/App.tsx)

### Steps to reproduce
(The following assumes this is a TypeScript project):
1. Create a custom component that wraps the antd Select component
2. Define a prop that proxies the Select.Option props
3. Try to import OptionProps from antd/lib/select when defining its type

### What is expected?
4. It is expected that OptionProps is exported in the Select component and available to be used to define types

### What is actually happening?
4. OptionProps is not exported and can't be used to define types

| Environment | Info |
|---|---|
| antd | 4.0.0-alpha.4 |
| React | 16.13.1 |
| System | macOS 10.15.4 |
| Browser | Chrome 83.0.4103.97 |

---
It was removed in this PR: https://github.com/ant-design/ant-design/pull/18658/files#diff-146763d630216d32434b0a462d81ddf7L87

**Comment by nitinknolder** [comment]
I have resolved this issue, please issue: https://github.com/ant-design/ant-design/pull/24870

**Comment by afc163** [comment]
Fixed in #24870

**Comment by nitinknolder** [comment]
> Thanks @nitinknolder, @afc163!

Your welcome @neemski
