### ISSUE TITLE
TreeSelect在宽度较小或者层级较多,并且开启虚拟滚动下 怎么让下面的选择框有横向滚动条呢

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design#24851]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
TreeSelect 不开启虚拟滚动时 可以修改样式 实现横向滚动条

### What does the proposed API look like?
希望有办法可以设置滚动条

**Comment by yoyo837** [comment]
试试  `dropdownRender`

**Comment by YinRenjie1993** [comment]
虚拟滚动的时候  下面的div没有宽度  会根据当前渲染的项的宽度来 所以不行

**Comment by afc163** [comment]
https://codesandbox.io/s/sparkling-snowflake-mzr1s?file=/index.js

这样是你想要的效果么？

**Comment by YinRenjie1993** [comment]
@afc163 开启虚拟滚动时候不行

**Comment by afc163** [comment]
目前应该是不支持的。
