### ISSUE TITLE
Modal本地正常发到测试服上Cannot read property 'getParent' of undefined，请问能看出什么问题吗

### ISSUE THREAD

**Issue by MangGoDio** [ant-design/ant-design#24858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-z7w0e?file=/TestComp.js)

### Steps to reproduce
昨晚发布以后所有打开Modal的事件都挂掉了，但是本地antd的包更新到最新的4.3.3是好的，试了下codebox也正常，来求助一下

### What is expected?
Modal正常打开

### What is actually happening?
https://yunhu-stage.oss-cn-hangzhou.aliyuncs.com/mehealth/2020-06-09/6fcdfc0db84441d1bd43ef2fc5d8b1ca.png

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | 79.0 |

**Comment by jljsj33** [comment]
重新 build

**Comment by a1178013314** [comment]
我跟了跟代码 this: undefined

**Comment by jljsj33** [comment]
重装依赖，，` rm -rf node_modules & npm i`

**Comment by icodinglee** [comment]
重装依赖也不行

**Comment by zero2603** [comment]
Same issue

**Comment by WangShuanPeng** [comment]
+1

**Comment by waiwaiku** [comment]
Same issue

**Comment by waiwaiku** [comment]
官方其实已经修复了，在rc-util  5.0.4版本修复的，如果重新安装依赖不行，检查下私有仓库是否有同步更新

**Comment by ronnyfv** [comment]
+1

**Comment by gitshrl** [comment]
+1

**Comment by junjie-lean** [comment]
把antd降级到4.3.2能暂时解决此问题，这应该是antd自身的bug

**Comment by joycode1** [comment]
Is the issue resolved?

**Comment by vmwell** [comment]
+1

**Comment by 969319036** [comment]
重新安装 rc-dialog 和 rc-util
报错就npm install
亲测有效

**Comment by yoyo837** [comment]
remove `node_modules`, `package-lock.json` or `yarn.lock`

reinstall

**Comment by zif002** [comment]
Hi, I have a similar problem, ```rm -rf node_modules package-lock.json & npm i``` does not work, 
maybe because the version in package.json in node_modules / ant is "rc-util": "^ 5.0.1", but current version 5.0.5 I updated antd to the latest version 4.4.0, but the problem remains, can you please fix it on 5.0.5 I think it should fix
