### ISSUE TITLE
在required为true的input中输入中文出现怪异的拼音

### ISSUE THREAD

**Issue by kylezhang** [ant-design/ant-design#2485]
### React， antd.的版本如下
"react": "^15.0.0",
 "react-dom": "^15.2.1",
"antd": "^1.6.5",

![a3ed6800-531f-4329-9800-da4c2716aa56](https://cloud.githubusercontent.com/assets/3679798/17089983/9589a296-525e-11e6-9906-5a287063c96c.png)
![274aefad-fbcb-4b35-96bd-13eb50ff1566](https://cloud.githubusercontent.com/assets/3679798/17089986/9a351122-525e-11e6-86c2-8e19d156de82.png)

**Comment by RaoHai** [comment]
#2239 同一个问题。。

**Comment by kylezhang** [comment]
@RaoHai #2239也没有具体的把问题解决了；
#### 我把React版本升级到了`"react": "^15.2.1"`,这个问题是解决了。

### 但是出现了新的问题，如下图：
![image](https://cloud.githubusercontent.com/assets/3679798/17092568/2c38fe8c-5276-11e6-8498-409dc6aff4e4.png)

**Comment by kylezhang** [comment]
#2258 看到了这个，真的能理解到“提问的智慧”了。。。。。
有时间问题提过，但是没法找，找不到😓
