### ISSUE TITLE
when I use search in TreeSelect, the result array cannot render dynamically

### ISSUE THREAD

**Issue by qianyx21** [ant-design/ant-design#24868]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lucid-cartwright-ol16p)

### Steps to reproduce
1. click 'please select' expand TreeSelect
2. type 'qq' in search input

### What is expected?
list of TreeSelect show the Node which contains text 'qq'

### What is actually happening?
TreeSelect show noting

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.12.0 |
| System | window10 |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/zealous-golick-om8bw

or

https://codesandbox.io/s/boring-albattani-7us9f
