### ISSUE TITLE
border不显示（颜色不显示）

### ISSUE THREAD

**Issue by liangmengli** [ant-design/ant-design#24863]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://cdn-public.littleoakcn.com/antd.png](https://cdn-public.littleoakcn.com/antd.png)

### Steps to reproduce
网站所有的边框都不显示，颜色太淡
显示器型号：https://cdn-public.littleoakcn.com/screen.jpg
网站截图：https://cdn-public.littleoakcn.com/antd.png

### What is expected?
是否可以调整边框颜色

### What is actually happening?
边框颜色太浅，有些电脑屏幕会显示不出来

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.13.1 |
| System | window |
| Browser | 版本 83.0.4103.97（正式版本） （64 位） |

**Comment by afc163** [comment]
Try https://ant.design/docs/react/customize-theme-cn
