### ISSUE TITLE
Search in Docs don't work

### ISSUE THREAD

**Issue by trulyronak** [ant-design/ant-design#24860]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/overview/](https://ant.design/components/overview/)

### Steps to reproduce
go to components search
type in 's'

### What is expected?
being able to search

### What is actually happening?
the screen turns white, and upon inspection of the debug console, I see this
TypeError: "Wa.subtitle is undefined" in the terminal

| Environment | Info |
|---|---|
| antd | undefined |
| React | n/a |
| System | MacOS |
| Browser | Firefox 77.0.1 |

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/84108245-577be900-aa52-11ea-8de1-3c1856a64f21.png)

**Comment by trulyronak** [comment]
yeah it got fixed via https://github.com/ant-design/ant-design/commit/84381e3e6c51bf4bc01487f1b27c47c2070b7302
