### ISSUE TITLE
The value of the onChange prop of InputNumber should not include the string type

### ISSUE THREAD

**Issue by 1123612483** [ant-design/ant-design#24862]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://muffinyu.github.io/antd-online](https://muffinyu.github.io/antd-online)

### Steps to reproduce
Click the reproduction link to open a new tab, paste the following code into the code area and run.(打开重现链接，并将以下代码粘贴至代码区并运行)

```javascript
import { InputNumber } from 'antd';
class Demo extends React.Component {
  btnClick = () => {
    console.log('button clicked');
  }
  render() {
    return (
      <div>
        <div>
          <InputNumber onChange={value => console.log(value)} />
        </div>
        <div>
          <input type="number" onChange={e => console.log(e.target.value)} />
        </div>
      </div>
    )
  }
}
ReactDOM.render(
  <Demo />
, mountNode);
```

### What is expected?
1. According to the typescript definition of InputNumber, when the input box has no value, the value should be undefined after losing focus.(根据InputNumber的typescript定义，当输入框没有值时，失去焦点后value应该为undefined)
2. When the original InputNumber inputs non-numeric characters, the input box will not be displayed, and the InputNumber of antd should also be like this..(原生的InputNumber输入非数字字符时，输入框不会显示，antd的InputNumber也应该是这样的).
3. After the original InputNumber input box is cleared, the value of onChange displays an empty string, and so is the InputNumber of antd. I think that the empty string is converted to undefined.(原生的InputNumber输入框清空后，onChange的value显示空字符串，而antd的InputNumber也是如此，我认为应该把空字符串转为undefined)

### What is actually happening?
1. value is null.(value为null).
2. InputNumber of antd cannot display non-numeric characters.(antd的InputNumber不能显示非数字字符).
3. The value of InputNumber becomes a string after being cleared, and becomes null after losing focus.(InputNumber的值清空后变为字符串，失去焦点后变成null)

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.13.0 |
| System | Win10 |
| Browser | Google v83.0.4103.97 |

---
1. If the above bug is fixed, the type corresponding to onChange can be changed to "(value: number | undefined) => void".(如果将以上bug修复，那么onChange对应的类型就可以改为“(value: number | undefined) => void”)

**Comment by 1123612483** [comment]
If the antd in the project is upgraded to version 4.3.3, hundreds of InputNumber are waiting for me to fix the type.  :-(
(如果把项目中的antd升级到4.3.3版本，几百个InputNumber组件等着我修复类型。)

**Comment by yoyo837** [comment]
Your want to revert #23871?

**Comment by mjfwebb** [comment]
If I understand it correctly, the PR you referenced @yoyo837 is only solving a Types problem, where the real problem is that the returned value should never being a string.

**Comment by 1123612483** [comment]
> Your want to revert #23871?

yep, the implementation layer should be modified instead of the interface layer.

**Comment by 1123612483** [comment]
> If I understand it correctly, the PR you referenced @yoyo837 is only solving a Types problem, where the real problem is that the returned value should never being a string.

You are so right.

**Comment by zombieJ** [comment]
`onChange` return `string` is when the text can not pass to number. It's design for controlled mode to avoid block typing.

**Comment by 1123612483** [comment]
> `onChange` return `string` is when the text can not pass to number. It's design for controlled mode to avoid block typing.

In this case, isn't it better to use the input box with type number? What is the role of InputNumber?

**Comment by 1123612483** [comment]
> `onChange` return `string` is when the text can not pass to number. It's design for controlled mode to avoid block typing.

The type of onChange is undoubtedly increasing the mental burden of the user.

**Comment by zombieJ** [comment]
`1` -> `1.` -> `1.1` with controlled if skip `1.` string will user never input success.

**Comment by 1123612483** [comment]
> `1` -> `1.` -> `1.1` with controlled if skip `1.` string will user never input success.


You can use the regular expression of numbers to verify the legality of the value.

**Comment by 1123612483** [comment]
> `1` -> `1.` -> `1.1` with controlled if skip `1.` string will user never input success.

When value is not a number, onChange is not called.

**Comment by yoyo837** [comment]
Any changes are changes, it need to reflect input value to the onchange.

**Comment by zombieJ** [comment]
When you return `1` as `1.`. It's not in controlled. For example, InputNumber support format:
1. 壹元
2. 贰
3. 贰元

Since convert logic is by user. `贰` is not the validate value. If not trigger `onChange`, `贰` will be force convert to `零元`

**Comment by 1123612483** [comment]
> When you return `1` as `1.`. It's not in controlled. For example, InputNumber support format:
> 
> 1. 壹元
> 2. 贰
> 3. 贰元
> 
> Since convert logic is by user. `贰` is not the validate value. If not trigger `onChange`, `贰` will be force convert to `零元`

OK. So why is the type of value `number | undefined` instead of `number | string | undefined`? Because `壹元` can be assigned to the value.

**Comment by 1123612483** [comment]
> Any changes are changes, it need to reflect input value to the onchange.

In the controlled mode, you can judge the value before passing it to onChange.

**Comment by zombieJ** [comment]
Yes. It pass `number` when input text is a validate number and `string` when convert failed.

**Comment by 1123612483** [comment]
> Any changes are changes, it need to reflect input value to the onchange.

In the controlled mode, you can judge the value before passing it to onChange.

> Yes. It pass `number` when input text is a validate number and `string` when convert failed.

But why is it a number when the value conversion fails and when it loses focus? Shouldn't it be a string?

**Comment by 1123612483** [comment]
I think the logic of value in onBlur and value in onChange should be consistent.

**Comment by afc163** [comment]
InputNumber is designed to return string when inputing text: https://github.com/ant-design/ant-design/issues/12795#issuecomment-432185737, it allows user input none-digit characters.

> If the antd in the project is upgraded to version 4.3.3, hundreds of InputNumber are waiting for me to fix the type

Why this makes TS incompatibility? Could you provide online reproduce?

**Comment by 1123612483** [comment]
> Why this makes TS incompatibility? Could you provide online reproduce?

The reason for TS incompatibility depends on the business scenario of our project. The usage scenario of our project is very simple, no need to process logic in onChange, just setState, only when the InputNumber loses focus to get the value of onChange, then the value is number | undefined.

TS不兼容的原因取决于我们项目的业务场景，我们项目的使用场景很简单，不需要在onChange处理逻辑，仅仅做setState处理，当InputNumber失去焦点时才去获取onChange的value，此时value为number | undefined。
``` typescript
class Demo extends React.Component<{}, { qty: number }> { 
    state = { qty: 0 };

    handleChange = (value: number | undefined) => {
        this.setState({ qty: value ?? 0 });
    }

    handleClick = () => {
        const { qty } = this.state;

        if (qty >= 0) {
           
        }
    }

    render() {
        return (
            <>
                <InputNumber
                    value={this.state.qty}
                    onChange={this.handleChange}
                />
                <Button onClick={this.handleClick}>Save</Button>
            </>
        );
    }
}

There are hundreds of references to InputNumber components in our project. After version 4.3.3, I need to fix these references.

我们项目引用InputNumber组件有上百处，4.3.3版本之后，我需要对这些引用进行修复。
```
class Demo extends React.Component<{}, { qty: number }> {
    state = { qty: 0 };

    handleChange = (value: number | string | undefined) => {
        if (typeof value == 'string') {
            return;
        }

        this.setState({ qty: value ?? 0 });
    }

    handleClick = () => {
        const { qty } = this.state;

        if (qty >= 0) {

        }
    }

    render() {
        return (
            <>
                <InputNumber
                    value={this.state.qty}
                    onChange={this.handleChange}
                />
                <Button onClick={this.handleClick}>Save</Button>
            </>
        );
    }
}
```
For this issue #12795. I think that when the value is an empty string, the InputNumber component should return undefined instead of "". This conversion should be handled internally by the InputNumber component, not the user.

对于这个问题#12795，我认为当value为空字符串时，InputNumber组件应该返回undefined而不是“”。这个转换应当由InputNumber组件内部作处理，而不应该是使用者。

**Comment by 1123612483** [comment]
> InputNumber is designed to return string when inputing text: [#12795 (comment)](https://github.com/ant-design/ant-design/issues/12795#issuecomment-432185737), it allows user input none-digit characters.
> 
> > If the antd in the project is upgraded to version 4.3.3, hundreds of InputNumber are waiting for me to fix the type
> 
> Why this makes TS incompatibility? Could you provide online reproduce?

**Comment by 1123612483** [comment]
https://github.com/react-component/input-number/blob/master/src/index.js

**Comment by 1123612483** [comment]
Or the component provides an event to handle the value after losing focus.
`afterBlur: (value: number | undefined) => void;`

``` typescript
class Demo extends React.Component<{}, { qty: number }> {
    state = { qty: 0 };

    handleChange = (value: number | undefined) => {
        this.setState({ qty: value ?? 0 });
    }

    handleClick = () => {
        const { qty } = this.state;

        if (qty >= 0) {

        }
    }

    render() {
        return (
            <>
                <InputNumber
                    value={this.state.qty}
                    afterBlur={this.handleChange}
                />
                <Button onClick={this.handleClick}>Save</Button>
            </>
        );
    }
}
```

**Comment by zombieJ** [comment]
v3 也是包含的 string，但是定义有问题所以没有报错：https://unpkg.com/browse/antd@3.26.18/es/input-number/index.d.ts

现在的定义是正确的。

对于你的场景，直接自己 HOC InputNumber 加个 afterBlur 就行了。

**Comment by 1123612483** [comment]
> v3 也是包含的 string，但是定义有问题所以没有报错：https://unpkg.com/browse/antd@3.26.18/es/input-number/index.d.ts
> 
> 现在的定义是正确的。
> 
> 对于你的场景，直接自己 HOC InputNumber 加个 afterBlur 就行了。

这个定义被正确修复之后，对我们项目反而造成副作用，一升级到4.3.3就各种报错，现在还没升级上。唉，当初没想到对InputNumber HOC，看来这个锅得自己背了。😂
