### ISSUE TITLE
React app with Typescript failes to find the CardInterface

### ISSUE THREAD

**Issue by THPubs** [ant-design/ant-design#24864]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-cherry-i0ryj?file=/src/StyledComponents.tsx)

### Steps to reproduce
Wait till the link loads the typescript runner. It might take a minute. Hover over the StyledCard and you'll get the error: 

    Exported variable 'StyledCard' has or is using name 'CardInterface' from external module ".../node_modules/antd/lib/card/index" but cannot be named.

This happens when we try to export a Card component wrapped inside a styled-component.

### What is expected?
No errors. The `CardInterface` should be exported.

### What is actually happening?
The `CardInterface` is not exported from the `Card` so Typescript cannot determine the shape of `CardInterface`.

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.13.1 |
| System | OSX Catalina |
| Browser | Firefox Developer Edition 78 |
| TypeScript | 3.9.5 |

**Comment by THPubs** [comment]
I'm going to work on this now. It'll be a simply `export` I think 🙂

**Comment by SunStupic** [comment]
This is happening again. 

```

Error during bundle: Error: /Users/stupic/Documents/workstream-frontend/libs/workstream-ui/src/lib/Checkbox/styled.Checkbox.ts(22,14): semantic error TS4023: Exported variable 'Checkbox' has or is using name 'CompoundedComponent' from external module "/Users/stupic/Documents/workstream-frontend/node_modules/antd/lib/checkbox/index" but cannot be named.
Error during bundle: Error: /Users/stupic/Documents/workstream-frontend/libs/workstream-ui/src/lib/Checkbox/styled.Checkbox.ts(22,14): semantic error TS4023: Exported variable 'Checkbox' has or is using name 'CompoundedComponent' from external module "/Users/stupic/Documents/workstream-frontend/node_modules/antd/lib/checkbox/index" but cannot be named.
Bundle failed: workstream-ui
```
