### ISSUE TITLE
Tabs组件在ie11浏览器中切换不了

### ISSUE THREAD

**Issue by fyxwanan** [ant-design/ant-design#24871]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/](https://ant.design/components/tabs-cn/)

### Steps to reproduce
ie 11 浏览器
1. 打开你们家官网
2. 然后点击代码演示，切换Tabs
3. 必然重现

### What is expected?
期望能够正常切换，
能不能加急解决。

### What is actually happening?
目前并不能正常切换。

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | react |
| System | windows |
| Browser | ie11 |

**Comment by zombieJ** [comment]
官网不做 IE 适配，项目里如果有问题给个重现：

![Kapture 2020-06-09 at 19 56 46](https://user-images.githubusercontent.com/5378891/84144758-67fc8580-aa8b-11ea-9ea1-1a819634d717.gif)

**Comment by fyxwanan** [comment]
> 官网不做 IE 适配，项目里如果有问题给个重现：
> 
> ![Kapture 2020-06-09 at 19 56 46](https://user-images.githubusercontent.com/5378891/84144758-67fc8580-aa8b-11ea-9ea1-1a819634d717.gif)

emm  你这个有github地址吗  我拉个你的代码试试~

**Comment by zombieJ** [comment]
直接 umi 建了一个项目复制了 antd 的例子，配置了一下游览器版本：
```
  targets: {
    ie: 11,
  },
```
