### ISSUE TITLE
有可编辑表格组件么？

### ISSUE THREAD

**Issue by ninemilli-song** [ant-design/ant-design#2487]

**Comment by afc163** [comment]
Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).

**Comment by ninemilli-song** [comment]
@afc163 After reading the [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and the [issues](https://github.com/ant-design/ant-design/issues), i can't find the table which can be edit, so i must admit how a fool man i am! But i still want to know where is the editable table. if it not existed in antd or in your plan then i will extend it by myself. Please forgive a foolish man! Thank you a lot!

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/2432

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/search?q=%E8%A1%A8%E6%A0%BC+%E7%BC%96%E8%BE%91&type=Issues&utf8=%E2%9C%93
