### ISSUE TITLE
V4版本AutoComplete组件移除optionLabelProp属性后用什么替代了呢

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design#24874]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在后台给的数据格式[{id:1, name: '张三'}, {id:2, name: '李四'}]，而AutoComplete要求的option格式是[{id:1, value: '张三'}, {id:2, value: '李四'}]，我该怎么处理

### What does the proposed API look like?
期望可以定义参数

**Comment by zombieJ** [comment]
`optionLabelProp` 做的是 `label` 映射，AutoComplete 里实际上没有 `label` 的概念所以去除。  你的场景直接自己转换一下格式就行了。

**Comment by theDoinb** [comment]
没了么，难怪把3.x的代码拷过来，点完不是label而是value值，
其实感觉 label可还行，毕竟有时候奇奇怪怪的 name 会重复，ID不会，
