### ISSUE TITLE
Provide Statistic.Countdown as standalone component

### ISSUE THREAD

**Issue by HenningCash** [ant-design/ant-design#24876]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, the Countdown component is always wrapped/rendered by `<Statistic />`. This adds a lot of surrounding divs and some undesired large style defaults. There should be a standalone variant of `<Countdown />` that can be used in inline text or other components like `<Tag />` outside of a statistics dashboard.

### What does the proposed API look like?
Same API (without `<Statistic />` props) as `<Statistic.Countdown />`.

**Comment by afc163** [comment]
```
<Countdown value={deadline}
```

https://codesandbox.io/s/nameless-resonance-v528p?file=/index.js

**Comment by HenningCash** [comment]
Sorry, that is not what I meant. There is no way to render countdown to a custom HTML element.
I want e.g. `<Tag><Countdown ... /></Tag>` to render to something like
```html
<span class="ant-tag">
  <span>47:59:22</span>
</span>
```

Currently this will always render 2x wrapping divs and 1x span (+ default statistic classes/styles)..
```html
<span class="ant-tag">
  <div class="ant-statistic">
    <div class="ant-statistic-content">
      <span class="ant-statistic-content-value">47:59:22</span>
    </div>
   </div>
</span>
```

`<Countdown />` is unnecessarily coupled to the `<Statistic />` component. It is useful on its own.
