### ISSUE TITLE
Select 在showSearch的情况下输入文字，当点击任意处blur导致文字不能够继续输入。只能重新输入

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#24872]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
是否有属性支持输入任意字符blur在次输入字符不需要重新输入

### What does the proposed API look like?
是否有属性支持输入任意字符blur在次输入字符不需要重新输入

**Comment by afc163** [comment]
`autoClearSearchValue`

**Comment by zombieJ** [comment]
用 `searchValue` 做成受控的

**Comment by shuozhang2016** [comment]
1. 不好意思，可能我没有描述清楚，我的述求是在非tags,非multiple情况下如果在blur的时候search value 不被清掉的方法。@afc163 
2. autoClearSearchValue好像在multiple下也有问题，当选中选项的时候不会清掉search value, 当blur的时候还是会清掉search value
3.  @zombieJ 我指的是select， 好像没有searchValue 这个属性

**Comment by zombieJ** [comment]
`searchValue` 和 `onSearch` 配合一下，没有的话估计是文档里漏了，你先试试

**Comment by shuozhang2016** [comment]
@zombieJ 经测试 searchValue 无法生效
