### ISSUE TITLE
Button type=`text` should not support `ghost`

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#24875]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/#components-button-demo-ghost](https://ant.design/components/button-cn/#components-button-demo-ghost)

<img width="378" alt="截屏2020-06-09 下午9 00 34" src="https://user-images.githubusercontent.com/5378891/84150312-448a0880-aa94-11ea-858c-dd3f1b54c9e8.png">

**Comment by Delphier** [comment]
ghost link 和 text 按钮，其实挺有用的，比如在深色背景上，取消比较遗憾，应该保留。
