### ISSUE TITLE
Drawer with "destroyOnClose" prop unmounts children too early when closing

### ISSUE THREAD

**Issue by lscheibel** [ant-design/ant-design#24889]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-wyusu?file=/index.js)

### Steps to reproduce
Use https://ant.design/components/drawer/ "Submit form in drawer" demo and add the "destroyOnClose" prop. When closing the drawer using the "cancel" button, the form inside disappears without a transition and then the drawer slides away. When clicking outside the drawer to close it, the form inside the drawer correctly fades out while the drawer retracts.

### What is expected?
The drawers contents should fade out, while the drawer retracts.

### What is actually happening?
When triggering the closing of the drawer with the cancel button the contents disappear immediately without any transition. When clicking outside the drawer the contents correctly fade out.

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | react@16.x |
| System | MacOS 10.14.6 (Mojave) |
| Browser | Google Chrome 83.0.4103.61 (Official Build) (64-bit) |

---
Setting animation playback speed to 10% in the dev-tools helps to illustrate the issue. This issue is already visible in the antd docs when adding the "destroyOnClose" prop to the "Submit form in drawer" demo

**Comment by toweave** [comment]
The sam

https://user-images.githubusercontent.com/12064408/141097519-40dedec5-51bd-493d-8557-faeb6e63029b.mp4

e.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-wyusu?file=/index.js

It is fixed now.
