### ISSUE TITLE
TreeSelect在过滤选择的场景下，view与state不一致

### ISSUE THREAD

**Issue by pixystone** [ant-design/ant-design#2488]
#### 本地环境

- antd 版本:  1.6.5
- 操作系统及其版本：osx 10.11.5
- 浏览器及其版本: chrome

#### 你做了什么？

1. 勾选子节点一
1. 勾选子节点二
1. 离开焦点
1. 再打开选择框

#### 你期待的结果是：

- 再次打开选择框时子节点二不是选中状态，期望与`this.state.value`保持一致

> 因为`handleChange`中已经过滤了选中1个以上结果时，不更新state

#### 实际上的结果：

- 离开焦点前，子节点二确实不是选中的
- 重新打开选择框时，子节点二居然是被**选中的**，此时`this.state.value = ['0-0-1']`并没有两个选中值

#### 可重现的在线演示

http://codepen.io/anon/pen/LkmdyV?editors=0011

**Comment by pixystone** [comment]
#### 更多的现象：

之后取消子节点二的（假）选中状态，并不会触发handleChange

**Comment by warmhug** [comment]
rc-tree-select@1.7.10

**Comment by pixystone** [comment]
https://github.com/react-component/tree-select/commit/46e955abdc5d001e9752e0a17657135d5bf4c434

**Comment by pixystone** [comment]
还是原来的demo地址：

http://codepen.io/anon/pen/LkmdyV?editors=0011

操作：

- 勾选子节点一
- 勾选子节点二
- 反选子节点一

期望：

没有节点被勾选

实际情况：

子节点二被勾选了


第一次子节点二没有被勾选，因为没有更新state，但是在组件内部实际上是勾选的状态吗？
