### ISSUE TITLE
使用websocket.subscribe后，message组件无法使用，没有效果

### ISSUE THREAD

**Issue by fantaishao** [ant-design/ant-design#24890]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/message/](https://3x.ant.design/components/message/)

### Steps to reproduce
在项目中添加了websocket后，调用websocket.subscribe方法后，message组件无效，没有效果

### What is expected?
message能正常使用

### What is actually happening?
message组件无效，没有效果

| Environment | Info |
|---|---|
| antd | 3.21.4 |
| React | 16.8.5 |
| System | window10 |
| Browser | Chrome 83.0.4103.97 |

---
websocket版本

"socket.io": "^2.2.0",

 "sockjs-client": "1.3.0",

"webstomp-client": "1.2.6"

**Comment by yoyo837** [comment]
UI怎么会和你的webscoket有关系呢，先检查下调用代码看看，提供复现。
