### ISSUE TITLE
<Switch> 样式问题 划出去了

### ISSUE THREAD

**Issue by fragilehan** [ant-design/ant-design#24891]
升级到4.3.3以后 划出去了
之前 4.2.0 正常
![image](https://user-images.githubusercontent.com/32543010/84257649-3d243700-ab48-11ea-8709-099175659c57.png)

**Comment by yoyo837** [comment]
你有没有覆盖样式，先删除看看

**Comment by xiaoguiking** [comment]
> > 你有没有覆盖样式，先删除看看
> 
> 我发现了是因为 这个滑块的样式变成了 calc(100% - 16px - 2px);
> less loader 对calc 解析不好 会打包成 calc(80%); 所以出去了
> 升级了 less less loader 版本以后解决了问题

我也遇到了这个问题，目前是最新版本的antd，检查switch给出的css是这样，
.ant-switch-checked .ant-switch-handle {
    left: calc(80%);
}， 我现在less版本是2.7.3，因为当初做了降级处理为了兼容antd，我先尝试下升级，看效果

**Comment by fragilehan** [comment]
> > > 你有没有覆盖样式，先删除看看
> > 
> > 
> > 我发现了是因为 这个滑块的样式变成了 calc(100% - 16px - 2px);
> > less loader 对calc 解析不好 会打包成 calc(80%); 所以出去了
> > 升级了 less less loader 版本以后解决了问题
> 
> 我也遇到了这个问题，目前是最新版本的antd，检查switch给出的css是这样，
> .ant-switch-checked .ant-switch-handle {
> left: calc(80%);
> }， 我现在less版本是2.7.3，因为当初做了降级处理为了兼容antd，我先尝试下升级，看效果

我之前是 2.7.3  loader 版本是5 昨天全直接升到最新了。。。 不多loader 的配置 变了 配自定义主题的时候 那你要看一下那个option

**Comment by fragilehan** [comment]
> > > 你有没有覆盖样式，先删除看看
> > 
> > 
> > 我发现了是因为 这个滑块的样式变成了 calc(100% - 16px - 2px);
> > less loader 对calc 解析不好 会打包成 calc(80%); 所以出去了
> > 升级了 less less loader 版本以后解决了问题
> 
> 我也遇到了这个问题，目前是最新版本的antd，检查switch给出的css是这样，
> .ant-switch-checked .ant-switch-handle {
> left: calc(80%);
> }， 我现在less版本是2.7.3，因为当初做了降级处理为了兼容antd，我先尝试下升级，看效果

你只升级 less loader 就行了 我刚试了一下

**Comment by ittce** [comment]
你们升级到那个版本了。

**Comment by ittce** [comment]
升级到less-loader 未解决，改成引入方式，通过css引入了。

**Comment by ittce** [comment]
升级到7.0.0未解决。

**Comment by ittce** [comment]
升级到7.0.0未解决。

**Comment by yoyo837** [comment]
提供下复现

**Comment by fragilehan** [comment]
> 升级到7.0.0未解决。
我现在是
"less": "^3.11.3",
"less-loader": "^6.1.0",
"antd": "4.5.3",
