### ISSUE TITLE
Icon 图表-代码演示-点击"展开全部代码"滚动条会回到顶部

### ISSUE THREAD

**Issue by xiaodun** [ant-design/ant-design#24911]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/icon-cn/](https://ant.design/components/icon-cn/)

### Steps to reproduce
ant.design官网 - 组件 - 图表 - 代码演示 - 点击"展开全部代码"

### What is expected?
点击"展开全部代码"滚动条不回到顶部

### What is actually happening?
点击"展开全部代码"滚动条回到了顶部

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.9.0 |
| System | mac |
| Browser | 83.0.4103.97 |

---
搜索图标功能,IconDisplay/index.tsx 中  117行的autoFocus 属性导致的

**Comment by xrkffgg** [comment]
PR welcome

**Comment by xiaodun** [comment]
> PR welcome

PR?

**Comment by xrkffgg** [comment]
Pull Request

**Comment by xiaodun** [comment]
> Pull Request
今天已经完成了第一次提issues,明天再试试第一次PR

**Comment by xrkffgg** [comment]
很简单的，时不我待。Come on

**Comment by nitinknolder** [comment]
I have raised the PR for this issue: https://github.com/ant-design/ant-design/pull/24932

**Comment by xrkffgg** [comment]
I have some ideas. I prefire not to remove this, but to initialize the page to `true`, and then become false.

**Comment by nitinknolder** [comment]
@xrkffgg Didn't get your point could you please elaborate.

**Comment by xrkffgg** [comment]
I think the original intention is remind users to search here.

So we should keep `autoFocus` presence.

like
```js
autoFocus={this.state.isAutoFocus}
```

First, `isAutoFocus` is `true`, then turn `false`.

**Comment by nitinknolder** [comment]
Ok, like what I suppose to do is take one local state to initialize it with **true** initially, then set its state to false in render method and assign it to the autofocus property right?

**Comment by xrkffgg** [comment]
Can give it a try

**Comment by xiaodun** [comment]
> I have raised the PR for this issue: #24932

Can you read Chinese?

**Comment by nitinknolder** [comment]
> > I have raised the PR for this issue: #24932
> 
> Can you read Chinese?

NO

**Comment by xiaodun** [comment]
> > > I have raised the PR for this issue: #24932
> > 
> > 
> > Can you read Chinese?
> 
> NO

So you used Google Translate?

**Comment by nitinknolder** [comment]
> > > > I have raised the PR for this issue: #24932
> > > 
> > > 
> > > Can you read Chinese?
> > 
> > 
> > NO
> 
> So you used Google Translate?

Yeah right!
