### ISSUE TITLE
这是bug还是feature？ Pagination 组件total大于50时showSizeChanger默认为true，pageSize修改时onChange不会触发，需要添加onShowSizeChange方法

### ISSUE THREAD

**Issue by without-yy** [ant-design/ant-design#24913]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/little-flower-vwvvl?file=/index.js)

### Steps to reproduce
1

### What is expected?
showSizeChange 默认值不跟随total变化，或 pageSize修改时触发onChange, 移除onShowSizeChange

### What is actually happening?
pageSize修改时onChange不会触发，需要添加onShowSizeChange方法

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.12 |
| System | MacOS 10.15 |
| Browser | Chrome 83.0.4103.97 |

**Comment by yoyo837** [comment]
目前实现是这样，onShowSizeChange 没触发onChange.

**Comment by yoyo837** [comment]
https://github.com/react-component/pagination/pull/272

**Comment by without-yy** [comment]
> 目前实现是这样，onShowSizeChange 没触发onChange.

当前的实现方式showSizeChange参数的默认值不太合理，没有添加onShowSizeChange事件时即使为true，也没有任何意义，还会对调用者造成迷惑

**Comment by yoyo837** [comment]
没太明白，什么`即使为true`?

**Comment by without-yy** [comment]
showSizeChanger： 是否展示 pageSize 切换器，当 total 大于 50 时默认为 true

我在开发过程中完全没有在意到这个参数，当数据多的时候才意识到，这才发现了onChange没有触发，需要再增加onShowSizeChange事件

**Comment by afc163** [comment]
看上去确实需要触发一下 onChange。

**Comment by yoyo837** [comment]
> 看上去确实需要触发一下 onChange。

然后就回到了 https://github.com/react-component/pagination/pull/272#issuecomment-635794830 的讨论 

@fireairforce 重启修改？

**Comment by fireairforce** [comment]
ok~改了

**Comment by afc163** [comment]
Fixed in #24964

**Comment by 20021004cb** [comment]
数据超过50，设置showSizeChanger为true，页面直接崩掉了，请问有人遇到这种问题吗？
