### ISSUE TITLE
ant-deasign-pro打包后体积umi.js太大

### ISSUE THREAD

**Issue by fightingSunnyGirl** [ant-design/ant-design#24914]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
npm run build

### What is expected?
小一些啊 越小越好 

### What is actually happening?
mac 打包出来的是1.5兆 linux打包出来的2.3兆

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | mac |
| Browser | all |

**Comment by fightingSunnyGirl** [comment]
![image](https://user-images.githubusercontent.com/24716684/84359552-6225b200-abfb-11ea-90b6-b51588880890.png)
![image](https://user-images.githubusercontent.com/24716684/84359594-6eaa0a80-abfb-11ea-8ee6-ea6fa87fa571.png)

**Comment by xrkffgg** [comment]
Pro 在这里提问：https://github.com/ant-design/ant-design-pro/issues
