### ISSUE TITLE
antd4.3.3中 List组件的grid属性失效

### ISSUE THREAD

**Issue by chenwenqin** [ant-design/ant-design#24916]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-lbc4b?file=/index.js)

复现链接可能失效，以下是代码段
```typescript
<List grid={{ gutter: 16, column: 6 }}>
    {[1, 2, 3, 4, 5, 6].map(it => <List.Item>{it}</List.Item>)}
</List>
```

### Steps to reproduce
直接打开

### What is expected?
grid属性下，List.Item组件横向排列

### What is actually happening?
加了grid属性(基数偶数都一样)，List.Item组件纵向排列

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.9.0 |
| System | win 10 |
| Browser | chrome |

**Comment by dopt** [comment]
如果换个方式写代码就可以把List.Item组件横向排列，以下是代码段：
> <List
      grid={{ gutter: 16, column: 4 }}
      dataSource={[1, 2, 3, 4, 5, 6]}
      renderItem={item => <List.Item>{item}</List.Item>}
    />

[https://codesandbox.io/s/antd-reproduction-template-h6s81?file=/index.js](url)

参考資源：
https://ant.design/components/list/#components-list-demo-grid

**Comment by chenwenqin** [comment]
谢谢，我试过了，确实可以。

但是这种方式灵活性降低了很多，数据源并不是完全同结构的。

**Comment by chenwenqin** [comment]
> 如果换个方式写代码就可以把List.Item组件横向排列，以下是代码段：
> 
> > <List
> > grid={{ gutter: 16, column: 4 }}
> > dataSource={[1, 2, 3, 4, 5, 6]}
> > renderItem={item => <List.Item>{item}</List.Item>}
> > />
> 
> https://codesandbox.io/s/antd-reproduction-template-h6s81?file=/index.js
> 
> 参考資源：
> https://ant.design/components/list/#components-list-demo-grid

谢谢，我试过了，确实可以。

但是这种方式灵活性降低了很多，数据源并不是完全同结构的。

**Comment by chenwenqin** [comment]
已经找到解决方案，放弃 `List`组件的`grid`支持，改用`Row`和`Col`配合可以实现完全等效的效果，而且很灵活。
