### ISSUE TITLE
New tabs hidden menu does not work with long tab names inside JSX elements.

### ISSUE THREAD

**Issue by nickmask** [ant-design/ant-design#24924]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-0dq1q?file=/index.js)

### Steps to reproduce
Reduce screen size until the tab side menu comes up. Click the ... and the tab links will not have an ellipsis, they will just go off the side.

### What is expected?
Either to not be able to provide a JSX element or for it to ellipsis the text even when nested inside of a JSX element.

### What is actually happening?
The text is being cut off.

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 83.0.4103.97  |

**Comment by afc163** [comment]
<img width="183" alt="image" src="https://user-images.githubusercontent.com/507615/84390396-1b02e580-ac2a-11ea-9d68-a3d031d4529e.png">
