### ISSUE TITLE
tabs-demo-card-top 样式紧凑模式下异常

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24920]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/#components-tabs-demo-card-top](https://ant.design/components/tabs-cn/#components-tabs-demo-card-top)

### 正常模式下

![image](https://user-images.githubusercontent.com/29775873/84371500-52fb3000-ac0c-11ea-8947-1d29fbdf9770.png)

### 紧凑模式下

![image](https://user-images.githubusercontent.com/29775873/84371661-935aae00-ac0c-11ea-81a8-2d782546d97b.png)

---

应该是需要修改 Demo 中自定义 css

**Comment by AshoneA** [comment]
仔细！
