### ISSUE TITLE
Radio.Group layout vertical ?

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24939]
#### Radio.Group 的 垂直布局， 看下效果：

![2020-06-12 10 24 40](https://user-images.githubusercontent.com/29775873/84458205-07da2f00-ac97-11ea-95cd-aa5d3cbd0c52.gif)

- 拿官网的例子改了个简单的效果，略粗糙，大家看看有没有可行性？

**Comment by AshoneA** [comment]
用户自己加个 style 属性也能实现类似效果吧~
https://codesandbox.io/s/blissful-darkness-q5m86?file=/index.js

**Comment by hengkx** [comment]
觉得怪怪的

**Comment by xrkffgg** [comment]
这个是粗糙的，水平上没对齐，而且两个连接处 多了一行。

**Comment by xrkffgg** [comment]
用户 自己要改样式的话，改动样式的地方还挺多的。

**Comment by zombieJ** [comment]
这样子空间利用率很低，感觉垂直用户还是习惯用小圆点
