### ISSUE TITLE
prev and next button icons are too small in month and quarter picker

### ISSUE THREAD

**Issue by Elinia** [ant-design/ant-design#24937]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w1smm)

### Steps to reproduce
check each picker and compare the prev and next button size

### What is expected?
prev and next button icons should have the same size in date picker.

### What is actually happening?
prev and next button icons in month and quarter picker is smaller than others.

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 83 |

---
prev and next buttons are using character instead of css border effect.

**Comment by yoyo837** [comment]
这个圈一下设计师吧

**Comment by xrkffgg** [comment]
感觉 尺寸 统一一下也好。刚才看了一下，确实有点小，我不记得以前啥样子，感觉以前好像是一样的啊。

**Comment by xrkffgg** [comment]
可能是 rc 那边的变动引起的

**Comment by zombieJ** [comment]
这个是用伪类画的，可以直接调一调。

**Comment by fireairforce** [comment]
我来改一下吧

**Comment by fireairforce** [comment]
具体讨论可以去 pr 那边看

**Comment by xrkffgg** [comment]
`rc-picker: 1.7.1`  注意 合到 feature 分支。

**Comment by fireairforce** [comment]
那我开个pr？

**Comment by xrkffgg** [comment]
> 那我开个pr？

👌

**Comment by yoyo837** [comment]
不是minor？

**Comment by xrkffgg** [comment]
rc-picker 1.7.0 已经更新到 feature 了，现在 master 还是 1.6 的

**Comment by fireairforce** [comment]
feature已pr

**Comment by zombieJ** [comment]
下下周就发 minor 了，可以等等。

**Comment by fireairforce** [comment]
好的，到时候上车。
