### ISSUE TITLE
Option to re-order the display of elements (InputNumber)

### ISSUE THREAD

**Issue by decimoseptimo** [ant-design/ant-design#24935]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be nice if there was a way to re-order the display of the elements (input, up, down), to allow for other visual configurations like: https://polaris.shopify.com/components/forms/stepper#navigation

### What does the proposed API look like?
```<RcInputNumber
      layout={({input, up, down})=>(
        <><up/><input/><down/></>
      )}
    />
```

**Comment by zombieJ** [comment]
Which component?

**Comment by decimoseptimo** [comment]
Sorry, I copied this over from another repo.
I'm talking about InputNumber.

**Comment by decimoseptimo** [comment]
This is related to https://github.com/react-component/input-number/issues/206
Since that is easier to fix, may be assign to that instead?

**Comment by afc163** [comment]
Sorry, we have no plan to do this now.
