### ISSUE TITLE
rangePicker清除日期后，获得一个长度为2的数组[null, null]

### ISSUE THREAD

**Issue by huanhuan129129** [ant-design/ant-design#2493]
#### 本地环境

- antd 版本: 最新1.6.0
- 操作系统及其版本：
- 浏览器及其版本:

#### 你做了什么？

在rangePicker中先选日期，然后再用清除annual清除掉
#### 你期待的结果是：
获取的value为undefined
#### 实际上的结果：
返回一个长度为2的数组[null, null]
#### 可重现的在线演示
http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
对，这个是对的，返回值始终是数组。
