### ISSUE TITLE
antd4.0  Modal组件

### ISSUE THREAD

**Issue by katteXu** [ant-design/ant-design#24947]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.antd-design.com](http://www.antd-design.com)

### Steps to reproduce
12312321

### What is expected?
Modal.confirm 需要一个默认icon

### What is actually happening?
Modal confirm 没有默认icon

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | react 16 |
| System | macos |
| Browser | Chrome  |

---
之前的版本一致都有默认icon

**Comment by afc163** [comment]
It has default icon: https://ant.design/components/modal/#components-modal-demo-confirm

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/84483560-15f67280-accc-11ea-998a-af6ff56e6fce.png)

我想他的意思是 没有 设置 icon 的时候，有一个默认的。

**Comment by afc163** [comment]
可以有一个。

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/84485417-b3eb3c80-acce-11ea-97a0-517fd4ae3cbb.png)

这个地方加一个 icon 就行，但是用哪个当默认啊？

**Comment by afc163** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/507615/84485780-0b89a800-accf-11ea-928b-e5d52ec07299.png">

**Comment by whinc** [comment]
> ![image](https://user-images.githubusercontent.com/29775873/84485417-b3eb3c80-acce-11ea-97a0-517fd4ae3cbb.png)
> 
> 这个地方加一个 icon 就行，但是用哪个当默认啊？

在 antd 中的 Modal 加默认图标，意味着必须需要引入 @antd-design/icons 包，这个是怎么解决的？

**Comment by yoyo837** [comment]
在支持tree shaking的情况下引入@antd-design/icons 使用其一个icon，没什么问题。

**Comment by whinc** [comment]
> 在支持tree shaking的情况下引入@antd-design/icons 使用其一个icon，没什么问题。

和猜想的一样，感谢
