### ISSUE TITLE
Pagination Component Move Right?

### ISSUE THREAD

**Issue by roeljohn** [ant-design/ant-design#24943]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I having an issue about the position the whole pagination item including the previous and right div to right. Is there a way I can edit or put a div container inside a previous 1,2,3,4 next section so I can put a class in that div so I can move it to the right?

https://prnt.sc/syaola - screenshot
![image](https://user-images.githubusercontent.com/8347743/84464967-7673b880-aca8-11ea-87c5-041945f27536.png)

### What does the proposed API look like?

`<Pagination item="right" />`
 or 
`<Pagination itemRenderer={(previous, items, next) => <div className="container">{previous} {items} {next}</div>} />`

**Comment by afc163** [comment]
```
<Pagination style={{ float: 'right' }} />
```

**Comment by roeljohn** [comment]
> style={{ float: 'right' }}

this will work but my issue is that it's include the 
![image](https://user-images.githubusercontent.com/8347743/84465174-ed10b600-aca8-11ea-8a6a-bbc3e5e9439e.png)

**Comment by roeljohn** [comment]
ah no worries I just use this. thanks @afc163

**Comment by afc163** [comment]
https://codepen.io/afc163/pen/gOProwd?editors=0110

**Comment by roeljohn** [comment]
Thanks! =)
