### ISSUE TITLE
Display character counter for input component optionally

### ISSUE THREAD

**Issue by ashkan-pm** [ant-design/ant-design#24940]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I think having a character counter when there is a limit on the input field would be very important for UX and useful for projects using ant. It's a very common practice and material design promotes it too. Of course you can use the suffix or addon props with a bit of custom logic to achieve this, but that would create some problems. It would not be possible for the TextArea component, it wouldn't have the option of showing the counter outside of the input, and most importantly I find it sub-optimal to have to create custom components that wrap ant inputs in the projects that need this and have to use those instead.
I'd be more than happy to do this and create a PR for it if you think it's a good idea.

### What does the proposed API look like?
Perhaps we can have a showCounter boolean prop to the input which would show the number of characters entered if there is no maxLength prop, and show the ratio of characters used and the total character limit if a maxLength was specified. I attached a design for how the counter might look like.

<img width="291" alt="Screen Shot 2020-06-12 at 6 20 04 AM" src="https://user-images.githubusercontent.com/64011067/84458315-cd13cf00-ac75-11ea-89c8-0e6976d218f3.png">

**Comment by mxye** [comment]
So "showCount" doesn't display for standard Input, just TextArea, right? Is that intentionally omitted? May I make another feature request to add it to the standard Input?
