### ISSUE TITLE
how tag click 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#24942]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/silly-hodgkin-uc5bm?file=/index.js)

- 为啥 初始化的时候会弹出 1 ?
- 为啥 点击 Home 不触发 click 事件 ？

> a 标签支持了 click，但木有继承 tag 的颜色啊。

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by katteXu** [comment]
onClick={()=>alert(1)}
