### ISSUE TITLE
Tabs centered

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#24941]
```
<Tabs centered />
```

<img width="681" alt="image" src="https://user-images.githubusercontent.com/507615/84459715-b338b300-ac9a-11ea-9394-7465c97f9ac2.png">

**Comment by ashkan-pm** [comment]
I think I can try to implement this. Can I give it a shot?

**Comment by afc163** [comment]
@ashkan-pm sure~

**Comment by ashkan-pm** [comment]
@afc163 Alright I'm on it 👍
