### ISSUE TITLE
pagination组件切换分页时添加beforeChange方法

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#24949]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
切换分页时需要提醒用户保持正在编辑的数据

### What does the proposed API look like?
beforeChange

**Comment by afc163** [comment]
建议做 current 受控就行了，onChange 的时候做拦截。
