### ISSUE TITLE
table数据为空时，提示文字支持html标签

### ISSUE THREAD

**Issue by forthedamn** [ant-design/ant-design#2494]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：mac os x 10.10.5
- 浏览器及其版本: chrome 51.0.2704.103

#### 你做了什么？

设置table 的 emptyText

#### 你期待的结果是：

空白提示支持html标签

#### 实际上的结果：

只能是字符串

**Comment by afc163** [comment]
支持的。
