### ISSUE TITLE
Form表单提交时提示“无效的参数”

### ISSUE THREAD

**Issue by aiyudeleng** [ant-design/ant-design#24951]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[localhost:3001](localhost:3001)

### Steps to reproduce
编辑信息后提交

### What is expected?
正常提交表单数据

### What is actually happening?
表单数据正常，但是提交时提示“无效的参数”

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12.0 |
| System | win10 |
| Browser | Edge浏览器（chromium内核） 84.0.516.1 (官方内部版本) dev (64 位) |

**Comment by aiyudeleng** [comment]
> Hello @aiyudeleng. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @aiyudeleng, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

项目是部署在本地的，并且涉及到两个页面之间传值，可能无法构建仓库或codesandbox实例。
![image](https://user-images.githubusercontent.com/31436484/84482791-e5fa9f80-acca-11ea-8988-b1544ff80026.png)

**Comment by jinxin0112** [comment]
看上去不是 form 的 bug ，而是 request 抛出的一个后端错误

**Comment by aiyudeleng** [comment]
> 看上去不是 form 的 bug ，而是 request 抛出的一个后端错误

确实是！一直在调更新后的Form，还以为是对Form的使用有问题，一直在找Form的原因。还很奇怪为什么没抓到错误。没往后台判断的返回考虑。非常非常感谢！
