### ISSUE TITLE
After the table is refreshed, the selected data is incorrect.

### ISSUE THREAD

**Issue by xiaofsu** [ant-design/ant-design#24954]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
I use: https://www.cnblogs.com/cristina-guan/p/9556274.html
To ensure that after deletion, you can keep the table refreshed on the current page.

When I deleted it for the first time, the data was deleted normally,
However, when I select the sorted data of the current page, the deletion is incorrect, and the selected data is not deleted correctly.

Please watch the zip。

---

我使用：https://www.cnblogs.com/cristina-guan/p/9556274.html  
来确保在删除之后，可以让表格保持在当前页面进行刷新。

在我删除第一次时，数据是正常被删除的，
但我再选择当前页面的排序较后的数据时，删除不正确，选择的数据没有被正确删除。

我提供了视频。

---

[QQ录屏20200612164428.zip](https://github.com/ant-design/ant-design/files/4769733/QQ.20200612164428.zip)

### What is expected?
数据被正确删除。

### What is actually happening?
数据未被正常删除。

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | ^16.8.6 |
| System | windows 10 |
| Browser | Google Chrome 已是最新版本 版本 83.0.4103.97（正式版本） （64 位） |

**Comment by cjmafei** [comment]
看一下控制台有没有报 key 相关的warning
