### ISSUE TITLE
InputNumber - Max/Min value validation - Is not the same on blur

### ISSUE THREAD

**Issue by bolanos-m** [ant-design/ant-design#24968]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/inputnumber-issue-on-blur-vfwm7)

### Steps to reproduce
- Open the console
- Put number grater than max validation (Default = 90 / Max = 100)
- If number is greater to 100 (Example: 150), and we move the focus, the onBlur event catches the value equal to 150... after, the value return to 100.

### What is expected?
Be able to catch the max value in onBlur event if the current value is overpassing the validation.

### What is actually happening?
The value in the onBlur event could overpass the max (Or min) value

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | react |
| System | any |
| Browser | any |

---
Example of the issue: https://imgur.com/a/N1aloBQ

**Comment by cjmafei** [comment]
I don't think it's a right way to use onChange and onBlur at the same time.It makes no sense that using value from onChange in onBlur.

**Comment by afc163** [comment]
It is by designed, please use onChange to catch valid number.
