### ISSUE TITLE
antd 1.6.5后，upload组件上传文件后，file的状态一直处于uploading状态

### ISSUE THREAD

**Issue by LeungManwei** [ant-design/ant-design#2496]
#### 本地环境

- antd 版本:1.6.5
- 操作系统及其版本：win10
- 浏览器及其版本:chrome 53

#### 你做了什么？

upload组件上传文件后，upload的onChange事件中的file的状态一直处于uploading状态
该问题发生在更新到1.6.5（因为1.6.4Form重置表单值有问题所以更新），在1.6.4upload组件正常
#### 你期待的结果是：

上传成功后file.status === done
#### 实际上的结果：
file.status ===uploading

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2423

**Comment by LeungManwei** [comment]
thx

**Comment by afc163** [comment]
有问题，先搜索。
