### ISSUE TITLE
menu的性能问题

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design#24975]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/42ecz)

### Steps to reproduce
1. 打开react devTools中的组件变更高亮选项
2. 点击任意菜单项

### What is expected?
1. 叶子节点的菜单项只更新自己
2. 父级节点的菜单项只更新自己和子菜单

### What is actually happening?
任意的点击都更新了整个菜单

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.12.0 |
| System | win 10 |
| Browser | chrome 83 |

![参考图片](https://user-images.githubusercontent.com/13702561/83349552-43582d80-a368-11ea-9ac9-616802a7e76d.gif)

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by Kermit-Xuan** [comment]
这个之前已经有优化了，https://github.com/react-component/menu/pull/123

而且你给的例子里面，其实就是优化后的，https://42ecz.csb.app/

**Comment by Rhuaer** [comment]
> 这个之前已经有优化了，[react-component/menu#123](https://github.com/react-component/menu/pull/123)
> 
> 而且你给的例子里面，其实就是优化后的，[42ecz.csb.app](https://42ecz.csb.app/)

无论是从官方demo还是我那个动图，其实都没有达到react-component/menu#123 的效果，反而变成了优化前的，变成了渲染整个菜单，而不是fix里面的只更新当前菜单

**Comment by Kermit-Xuan** [comment]
http://react-component.github.io/menu/examples/antd.html 你看看这个例子应该是优化后的吧？我觉得可能是 `antd` 里面menu的问题。

**Comment by Rhuaer** [comment]
> http://react-component.github.io/menu/examples/antd.html

恩，这个例子的效果感人，确实是优化后的，但 https://42ecz.csb.app/ 中antd官方的示例就不行，随便点击哪里都会导致整个menu重新渲染

**Comment by Kermit-Xuan** [comment]
我看了目前 `antd` 自己管理 `menu` 的 展开状态，然后将其传递给 `rc-menu`，这样以来 每次渲染后 `and` 的 `menu` 都会重新渲染，导致 `rc-menu` 中的优化失效，想搞的话，就需要把 `antd` 的状态管理全部迁移到 `rc-menu` 中，由其做统一管理。 @afc163

**Comment by afc163** [comment]
可以的，最好 antd 这边只留个壳。
