### ISSUE TITLE
RangePicker设置defaultValue不生效

### ISSUE THREAD

**Issue by yulrosy** [ant-design/ant-design#2497]
#### 本地环境

- antd 版本: 1.6.4
- 操作系统及其版本：windows10
- 浏览器及其版本: chrome 51.0.2704.106 m

#### 你做了什么？

    <RangePicker defaultValue={this.porps.dateRange} showTime={{format:"HH:mm"}} format="yyyy.MM.dd HH:mm" {...getFieldProps('time')}/>

#### 你期待的结果是：

展示给定的默认时间

#### 实际上的结果：
没有展示默认时间

**Comment by afc163** [comment]
http://ant.design/components/form/#this.props.form.getFieldProps(id,-options)

**Comment by yulrosy** [comment]
<RangePicker initialValue={this.props.dateRange} showTime={{format:"HH:mm"}}
                       format="yyyy.MM.dd HH:mm" {...getFieldProps('time')}/>

改成 initialValue还是不行，dateRange是一个数组，有2个Date类型的数据，哪姿势不对了

**Comment by afc163** [comment]
你看看自行文档吧。。。。

**Comment by yulrosy** [comment]
好吧，我再研究一下

**Comment by yulrosy** [comment]
componentDidMount(){
      const props = this.props;
      props.form.setFieldsValue({time:props.dateRange});
    }
我觉得我这种办法有点low，但想不到更好的了

**Comment by afc163** [comment]
{...getFieldProps('time', {
  initialValue: ...
})}

**Comment by yulrosy** [comment]
囧，在这设置啊，thanks
