### ISSUE TITLE
datePicker calendar  unstable when updating version 4.3.3 

### ISSUE THREAD

**Issue by AbhijeetGaware** [ant-design/ant-design#24973]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/](https://ant.design/components/date-picker/)

### Steps to reproduce
DatePicker

### What is expected?
i am using version 3.26.17 but when i updated 4.3.3 all UI is changed datePicker calendar i need to stable datepicker calendar 

### What is actually happening?
1.when importing (import 'antd/dist/antd.css')  working fine .
but all entire project when i import those css file the calendar its unstable 
(import '../node_modules/antd/lib/date-picker/style/index.css'
import '../node_modules/antd/lib/input/style/index.css';) 

<img width="1152" alt="Screenshot 2020-06-13 at 5 23 02 PM" src="https://user-images.githubusercontent.com/56472463/84568270-cd0def00-ad9b-11ea-90a5-6cd3972e61fb.png">

2. when i Import  index.css instead of only css its working fine 
  (import '../node_modules/antd/lib/date-picker/style/css'
import '../node_modules/antd/lib/input/style/css';) 

now its stable

result:-
<img width="591" alt="Screenshot 2020-06-13 at 5 45 19 PM" src="https://user-images.githubusercontent.com/56472463/84568542-b799c480-ad9d-11ea-9f9c-64a0d0a605d1.png">

//code//
import React from 'react';
import logo from './logo.svg';
// import 'antd/dist/antd.css'; 
import DatePicker from "antd/lib/date-picker";
import './App.css';
import '../node_modules/antd/lib/date-picker/style/index.css'
import '../node_modules/antd/lib/input/style/index.css';
const { RangePicker } = DatePicker;

function App() {
  return (
    <div className="App">
      <div>
      <h3>DatePicker</h3>
        <DatePicker/>  
      </div>
      <div>
        <h3>RangePicker</h3>
        <RangePicker/>
      </div>
    </div>
  );
}

export default App;
result:-
<img width="585" alt="Screenshot 2020-06-13 at 5 42 08 PM" src="https://user-images.githubusercontent.com/56472463/84568486-6f7aa200-ad9d-11ea-8226-b1ba9e0bb45c.png">

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.13.0 |
| System | MacBookPro |
| Browser | Chrome 81.0.4044.138  |

---
-

**Comment by yoyo837** [comment]
These components have been rewritten according to the new design in 4.x

**Comment by AbhijeetGaware** [comment]
> These components have been rewritten according to the new design in 4.x

@yoyo837  so what should i have to change ??

**Comment by afc163** [comment]
Please import css by following offcial documentation.

```diff
import 'antd/dist/antd.css';
```

**Comment by yoyo837** [comment]
https://ant.design/docs/react/migration-v4

**Comment by AbhijeetGaware** [comment]
> Please import css by following offcial documentation.
> 
> ```diff
> import 'antd/dist/antd.css';
> ```

@yoyo837  i tried this its working fine but the problem is its working only one applications and one application nested too many applications nested applications cant't work 
so in my main application i used this files and 3.26.17 its working fine but when i update new version  4.3.3 all datePicker ui can’t stable 
(import '../node_modules/antd/lib/date-picker/style/index.css'
import '../node_modules/antd/lib/input/style/index.css';)

**Comment by AbhijeetGaware** [comment]
> https://ant.design/docs/react/migration-v4

okay i will  look at Thanks.
