### ISSUE TITLE
table可否支持单行数据更新

### ISSUE THREAD

**Issue by yruson** [ant-design/ant-design#24974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
场景：对某行执行一一个操作，根据这个操作的结果，手动更新对应行的数据。而不需要整个table重新加载数据。

### What does the proposed API look like?
像element UI为table提供了setRowi可以事后手动更新某一行的数据，翻遍一antd好像没有实现。

**Comment by afc163** [comment]
更新数据即可，使用 antd 前建议先学习一下 React。
