### ISSUE TITLE
RangePicker 设置样式异常

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#24972]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-bush-jz4mr?file=/index.js)

### Steps to reproduce
无

### What is expected?
正常

### What is actually happening?
不正常

![image](https://user-images.githubusercontent.com/7971419/84565493-18c09880-ad9c-11ea-9853-1566c534a0e0.png)
```jsx
const Demo = () => {
  const style = { display: "inline-block", width: "400px" };
  return (
    <>
      <Input style={style} />
      <hr />
      <RangePicker style={style} />
      <hr />
      <DatePicker style={style} />
    </>
  );
};
```

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by cjmafei** [comment]
DatePicker相关的组件都用的inline-flex,你写的display: "inline-block"覆盖了原样式

**Comment by crazyair** [comment]
> DatePicker相关的组件都用的inline-flex,你写的display: "inline-block"覆盖了原样式

有没有办法兼容呢？或者包裹一下。

**Comment by cjmafei** [comment]
> > DatePicker相关的组件都用的inline-flex,你写的display: "inline-block"覆盖了原样式
> 
> 有没有办法兼容呢？或者包裹一下。

你使用inline-block的场景是什么，或者说原因是什么

**Comment by crazyair** [comment]
就是为了一行展示多个元素，demo 已经更新了，改用了 inline-flex 现在看来没问题了

**Comment by cjmafei** [comment]
> 就是为了一行展示多个元素，demo 已经更新了，改用了 inline-flex 现在看来没问题了

不需要加inline-flex，pick组件本身用的就是inline-flex，除非你在外面包裹了一层

**Comment by crazyair** [comment]
就是外面包裹了一层，那怎么写

**Comment by cjmafei** [comment]
> 就是外面包裹了一层，那怎么写

去掉display: "inline-block"

**Comment by crazyair** [comment]
日期的不用扩展到 100%
![image](https://user-images.githubusercontent.com/7971419/84566087-10b72780-ada1-11ea-8ca8-ebb5b1813383.png)
其他的扩展到 100% 
![image](https://user-images.githubusercontent.com/7971419/84566101-2593bb00-ada1-11ea-850c-c2309bdd590e.png)

这样也挺好看的。

**Comment by zombieJ** [comment]
看来你们已经讨论完了，关了哈~
