### ISSUE TITLE
Form validateTrigger prop not working with onBlur

### ISSUE THREAD

**Issue by gcoxdev** [ant-design/ant-design#24970]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-heisenberg-j0tis)

### Steps to reproduce
* Set validateTrigger prop to "onBlur" on Form component
* Add Form.Item with Input to Form with required rule
* Focus on Input
* Blur from Input (no error)
* Focus on Input and type text
* Remove text
* Blur from Input (no error)

### What is expected?
Apply validation for all fields on the form when setting validateTrigger prop to "onBlur" on Form component instead of individually setting validateTrigger on each form item

### What is actually happening?
onBlur validation not triggering on form items when form-level validateTrigger is set to "onBlur". Instead, validation trigger is still only validating on change event.

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | react 16.13.1 |
| System | Windows 10 |
| Browser | Firefox/Chrome latest |

---
See reproduction link

**Comment by zombieJ** [comment]
`validateTrigger` is a Form.Item prop not Form prop.

**Comment by gcoxdev** [comment]
Why is it listed as a Form prop then? https://ant.design/components/form/#Form

**Comment by HkOri** [comment]
> For someone comes to this issue, you have to use `rules` props in your form.item in order to make the `validateTrigger` works.

still useless
