### ISSUE TITLE
[4.3.x] pageheader 中 tabs 样式丢失

### ISSUE THREAD

**Issue by lich-yoo** [ant-design/ant-design#24989]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/page-header-cn/#components-page-header-demo-responsive](https://ant.design/components/page-header-cn/#components-page-header-demo-responsive)

### Steps to reproduce
在 antd v4.3.x 中 tabs 进行了重做，样式 class 大幅修改，pageheader 中 tabs 样式还是旧的没有更换，导致样式丢失。

### What is expected?
样式恢复 v4.3.x 之前

### What is actually happening?
样式丢失
![image](https://user-images.githubusercontent.com/18572962/84614163-df04a480-aef7-11ea-8c59-1c42739432c4.png)

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | lastest |
| System | win10 |
| Browser | chrome |

**Comment by lich-yoo** [comment]
不确定是否有其他组件中设置的 tabs 样式，建议搜索排查下，更新旧样式的引用

**Comment by afc163** [comment]
- 4.2.x ✅：https://codesandbox.io/s/elegant-bohr-x92mh?file=/package.json
- 4.3.x ❌：https://codesandbox.io/s/nervous-hugle-0ntzj?file=/package.json

**Comment by lebron112** [comment]
遇到了同样的问题 
![image](https://user-images.githubusercontent.com/20268396/84640559-6f5cdc80-af2c-11ea-883e-d44740a7311f.png) 4.3.4
![image](https://user-images.githubusercontent.com/20268396/84640636-87ccf700-af2c-11ea-971f-08e5350da783.png)4.2.4
