### ISSUE TITLE
Search onChange change typescript type

### ISSUE THREAD

**Issue by rparac** [ant-design/ant-design#24987]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have been trying to print the value of the search field every time a new character is typed. This is my solution:

          <Search placeholder={'search'}
                  onChange={(e: FormEvent<HTMLElement>) => {
                    let elem: HTMLInputElement = e.currentTarget as HTMLInputElement;
                    console.log(elem.value);
                  }}/>

If e is of type FormEvent\<HTMLInputElement\> this could be solved without any casting. It would be nice if this could be changed.

### What does the proposed API look like?
The type of onChange would become onChange: (e: FormEvent\<HTMLInputElement\>) => void.

**Comment by zombieJ** [comment]
Why use `currentTarget`? Seems current `onChange` is correct define:

<img width="878" alt="截屏2020-06-15 下午9 57 00" src="https://user-images.githubusercontent.com/5378891/84666022-25d3b800-af53-11ea-9e6a-1ad867557974.png">

**Comment by rparac** [comment]
I have been using `Search` component from `'antd/lib/transfer/search'`. I apologize for not mentioning that so far. The type does indeed seem to be correctly defined in the component from `'antd/lib/input/Search'`. 
The `Search` component that I have been using has the following type:
 `onChange?: (e: React.FormEvent<HTMLElement>) => void;`
That is also the reason why I have been using currentTarget instead of target since target of a `FormEvent` has `EventTarget` as its type. That is unlike currentTarget whose type is `EventTarget & HTMLElement`.

**Comment by afc163** [comment]
Don't use `antd/lib/transfer/search`, it is not offically exported to users.

**Comment by zombieJ** [comment]
We do not support internal component and you should avoid to use that since it maybe removed on refactorting.
