### ISSUE TITLE
CheckBoxGroup defaultValue

### ISSUE THREAD

**Issue by gitbu** [ant-design/ant-design#2498]
#### 本地环境

- antd 版本:1.6.5
- 操作系统及其版本：mac pro 10.11.3
- 浏览器及其版本:chrome  51.0.2704.106 (64-bit)

**Comment by benjycui** [comment]
http://ant.design/components/checkbox#components-checkbox-demo-group

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2497
