### ISSUE TITLE
Cascader组件使用loadData并且浮层受控时无法清空数据

### ISSUE THREAD

**Issue by zhangyu1818** [ant-design/ant-design#24988]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-hodgkin-8v2kl?file=/index.js)

### Steps to reproduce
随意选中一项后，点小叉叉清空数据

### What is expected?
浮层内容选中项清空

### What is actually happening?
浮层选中项没有被清空

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | Ubuntu 20.04LTS |
| Browser | Chrome 83 |

如果浮层不受控不会有这个问题，但是场景需要失焦的时候才关闭浮层

**Comment by afc163** [comment]
虽然交互看上去很奇怪，但是清空数据时确实应该把浮层状态也清理一下。
