### ISSUE TITLE
建议团队开发一个滚动条样式的兼容组件

### ISSUE THREAD

**Issue by sugermy** [ant-design/ant-design#24998]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
ant的功能非常丰富，UI也很好看 但是美中不足的一点就滚动条样式还是原生的样式有点影响美观

### What does the proposed API look like?
可以参考Element UI的滚动条样式，最好可以实现自定义颜色 宽度等常规内容

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19036

可以用 -webkit-scrollbar 做自定义滚动条样式。

**Comment by sugermy** [comment]
> [＃19036](https://github.com/ant-design/ant-design/issues/19036)
> 
> 可以用-webkit-scrollbar做自定义滚动条样式。

那只能局限于webkit的浏览器了
