### ISSUE TITLE
Switch does not re-render on paginated Tables

### ISSUE THREAD

**Issue by vickOnRails** [ant-design/ant-design#24994]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-sound-kusj3?file=/index.js)

### Steps to reproduce
1. Visit the above minimal reproduction
2. Click on another page of the table data (Like 1,2,3)

### What is expected?
The switches are supposed to change or rerender based on the values of the specific cell

### What is actually happening?
The switches do not rerender and configuration for the first rendered table page persist

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Chrome 83 |

---
I ran into this bug because I passed in an array of objects each containing 0 and 1 values. I wanted to render numerous switch widgets based on the truthy value of every cell. Everything worked as expected, but when I navigate to another page of the table, nothing rerenders.

Maybe there's something I'm doing wrong?

**Comment by cjmafei** [comment]
![image](https://user-images.githubusercontent.com/23433659/84627387-6a426200-af19-11ea-8424-5e22cbe500fa.png)
Please notice the warning on the console. Table data is missing the key.

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically

**Comment by afc163** [comment]
@cjmafei is right, you should have primary key for your data and set it by `rowKey`.

**Comment by vickOnRails** [comment]
Wow.

100% my bad.

I solved the issue by adding a key to the incoming data.

Thanks a lot, @cjmafei & @afc163
