### ISSUE TITLE
徽标数不支持链接和导航

### ISSUE THREAD

**Issue by zhbhun** [ant-design/ant-design#250]
目前Antd徽标数的用法只提到：
> 一般出现在通知图标或头像的右上角，用于显示需要处理的消息条数，通过醒目视觉形式吸引用户处：理。

除了这个外，在链接、导航菜单、页签选项和按钮等组件上有时候也需要添加徽标组件。

另外， 徽标组件必须作为父组件来包装需要添加徽标的内容，如果我需要给某个组件加两个徽标，这样就实现不了了。

**Comment by afc163** [comment]
可以帮忙改改然后 PR 如何？目前刚写完还没实践过。

**Comment by zhbhun** [comment]
看了下手机APP上按钮的徽标，感觉也没什么问题，然后测了一遍各个组件上添加徽标的效果，效果也还可以。
![tmp](https://cloud.githubusercontent.com/assets/1996891/9731936/b6a5a2c6-5652-11e5-9786-97a991d30209.jpg)

之前是我遇到需求，要做类似于React-Bootstrap的徽章：
![tmp](https://cloud.githubusercontent.com/assets/1996891/9732066/78d53d5c-5653-11e5-9d07-cb79f48e9ed3.jpg)

**Comment by yiminghe** [comment]
clean
