### ISSUE TITLE
No way to determine AM/PM when using disabledHours with use12Hours

### ISSUE THREAD

**Issue by AceNorth** [ant-design/ant-design#25009]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The prop disabledHours takes a function that returns an array of hours to be disabled. So if you want to disable all the hours before 6 P.M., you would provide an array of values from 1-18. However, when use12Hours = true, this will disable all the hour values (even when the user selects "PM") because it is apparently only checking the integers themselves and not their place on the 24-hour clock. In the example here, I'm trying to prevent the user from selecting an end time for their appointment that would be earlier than the start time, but that's impossible with the current API:

<img width="365" alt="Screen Shot 2020-06-15 at 12 57 46 PM" src="https://user-images.githubusercontent.com/20522677/84686369-ce5d2a00-af09-11ea-9f5d-b1c27ecb1cf1.png">

### What does the proposed API look like?
When use12Hours=true, disabledHours should still accept an array of integers from 1-23, but it should be aware of whether AM or PM is selected in the overlay and adjust the disabling of values accordingly (so 1:00 PM should be disabled if "13" is provided).

**Comment by ChenCodes** [comment]
I have the same issue as above - any thoughts on if this bug will be resolved?

**Comment by tonyisblind** [comment]
same issue here, any updates? Thanks!

**Comment by vandercloak** [comment]
@zombieJ Why did this get closed? Is there a antd version where this is now fixed?

**Comment by vandercloak** [comment]
@zombieJ Happy new year! Hope your doing well. 

Is there any updates/plans for this issue?

**Comment by vandercloak** [comment]
@zombieJ I decided to fork and check it out. I have a PR to address the issue noted above ^.

This is my first ant-design PR. What are the next steps for review/deployment and integration into the ant design repo?
