### ISSUE TITLE
Add a choice to remove step icon for InputNumber (again)

### ISSUE THREAD

**Issue by taha-moghaddam** [ant-design/ant-design#25002]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
As @luyunfei suggested sometimes ago I suggest again to Please add a choice to remove step icon for InputNumber.
Because InputNumber is alone solution for input-number validation which is not supported by Input-component.

### What does the proposed API look like?
`<InputNumber stepsStyle={"display": "none"}/>`

**Comment by xrkffgg** [comment]
In my opinion, it can be has.

**Comment by afc163** [comment]
#18809 
#6552

**Comment by xrkffgg** [comment]
你可以在你需要的项目中加上这个。
```css
.ant-input-number-handler-wrap { 
    visibility: hidden;
}
```

**Comment by Pszz** [comment]
> 你可以在你需要的项目中加上这个。
> 
> ```css
> .ant-input-number-handler-wrap { 
>     visibility: hidden;
> }
> ```

我认为不合理，按照这样说，我可以破坏组件任何内部结构。
已经第N次遇到想要使用InputNumber，但是因为up/down 按钮不合理，导致放弃该组件。
我认为该属性是很常规的一个API
```js
{
controller: false
}
```
