### ISSUE TITLE
form with redux become slow

### ISSUE THREAD

**Issue by ChengYiWu** [ant-design/ant-design#25000]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/romantic-wescoff-bghs1?file=/index.js)

### Steps to reproduce
输入资料

### What is expected?
正常速度显示输入的资料

### What is actually happening?
页面卡卡的

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.9 |
| System | Windows 10 Home |
| Browser | chrome 83.0.4103.97 |

**Comment by zombieJ** [comment]
v4 不再推荐使用外部存储管理表单内部数据：

> 注意： 将表单数据存储于外部容器[并非好的实践](https://github.com/reduxjs/redux/issues/1287#issuecomment-175351978)，如无必要请避免使用。

https://ant.design/components/form-cn/#components-form-demo-global-state

如有需求，欢迎 PR 优化。

**Comment by Kermit-Xuan** [comment]
先关闭了，有需要再开启。
