### ISSUE TITLE
Moving slider is triggering highlights of all other elements

### ISSUE THREAD

**Issue by skyorion427** [ant-design/ant-design#25010]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider/](https://ant.design/components/slider/)

### Steps to reproduce
Drag slider

### What is expected?
The only slider should be updated

### What is actually happening?
All other elements are highlighted

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | latest version |
| System | Mac OS 10.15.2 |
| Browser | Safari |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/slider/commit/b0873ea93881c40271a4c7bde5735c655fc7f345
