### ISSUE TITLE
Tooltip TS版本使用自定义背景颜色，代码检查报错

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design#25015]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-shamir-qp057)

### Steps to reproduce
在TypeScript版本中使用Tooltip 自定义color属性（如#099999），代码检查报错

### What is expected?
代码检查不报错，背景颜色可以正常更改

### What is actually happening?
背景颜色更改看起来成功了，但是代码检查报错

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.12.0 |
| System | MacOs |
| Browser |  chrome 83.0.4103.61 |

---
跟进去发现ts定义的把颜色范围给定死了

![image](https://user-images.githubusercontent.com/36301924/84728313-87cc0600-afc3-11ea-825f-51b87933f802.png)

**Comment by linbudu599** [comment]
I'd like to give a try on fixing it, which requires a proper way to handle type definitions in Hex & RGB & RGBA.

**Comment by XiaoJiuDYS** [comment]
> I'd like to give a try on fixing it, which requires a proper way to handle type definitions in Hex & RGB & RGBA.

Maybe just like Tag?Of course, it’s great to do better.

**Comment by linbudu599** [comment]
> > I'd like to give a try on fixing it, which requires a proper way to handle type definitions in Hex & RGB & RGBA.
> 
> Maybe just like Tag?Of course, it’s great to do better.

哈哈哈哈俺也是中国人! 但是看起来我没有找到很好的办法解决它, 如果需要精确的类型定义而不是直接"string", 需要对Hex类型限制每一位0~f(#000000 -> #ffffff), RGB则需要每一位在0~255, RGBA的最后一位则需要在0~1, 我的想法是开放string类型, 在<ToolTip />里用正则来判断是否是正确的格式. @afc163

**Comment by xrkffgg** [comment]
不用那么麻烦，直接加个类型就行。

**Comment by XiaoJiuDYS** [comment]
简单的改成这样就行了
color?:   LiteralUnion<PresetColorType, string>;

**Comment by xrkffgg** [comment]
我觉得这样就行
```js
color?: PresetColorType | string;
```

**Comment by XiaoJiuDYS** [comment]
> 我觉得这样就行
> 
> ```js
> color?: PresetColorType | string;
> ```
这样写没问题，不过用LiteralUnion 在IDE里提示更友好一点🤔
