### ISSUE TITLE
table组件会给传给dataSource的数组里的每一项增加indexForSort属性

### ISSUE THREAD

**Issue by vxzhong** [ant-design/ant-design#2501]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：osx 1.11.6
- 浏览器及其版本: chrome

#### 你做了什么？

创建了一个table:
```js
<Table
      loading={loading}
      columns={columns}
      dataSource={data}
    />
```

#### 你期待的结果是：
table组件不改变dataSource的值，即data不变。

#### 实际上的结果：

data数组里的每一项多了一个indexForSort的属性。

看了一下table的代码，做了数组本身的拷贝，但直接修改了每一项，能不能用{ ...data[i], indexForSort: i }代替?
```js
var data = this.props.dataSource || [];
    // 优化本地排序
    data = data.slice(0);
    for (var i = 0; i < data.length; i++) {
      data[i].indexForSort = i;
    }
```

**Comment by afc163** [comment]
👍  来个 PR 吧 ~

发到 1.x-stable 分支。

**Comment by Ben07** [comment]
1.9.1版本中依然存在此indexForSort的属性。

**Comment by benjycui** [comment]
存在是对的，原来的问题是修改了数据源。

**Comment by Ben07** [comment]
@benjycui 我原本通过record拿到一条数据，修改后直接提交就是了，现在得手动delete这个indexForSort属性。觉得别扭
