### ISSUE TITLE
form.onValuesChange或是form.onFieldsChange应该提供机制，使用户知道输入值是否满足校验

### ISSUE THREAD

**Issue by sunchey11** [ant-design/ant-design#25025]
### What problem does this feature solve?
当表单控件值改变时，且此值符合校验规则时，需要编写代码处理一些业务逻辑。
但是目前，form.onValuesChange会响应校验非法的值，所以无法将业务逻辑写到这里。
而onFieldsChange会进入3次，第一次（校验之前）的信息没有校验错误，且validating=false，所以在这里写业务逻辑也会处理校验未通过的情况。

### What does the proposed API look like?
1.像antd3.0一样，onFieldsChange只进入2次，或者第一次进入onFieldsChange时，提供信息，说明是校验前的状态
2.onValuesChange提供信息，描述值的检验信息

**Comment by afc163** [comment]
What does the proposed API look like?

**Comment by sunchey11** [comment]
I think maybe you can set FieldData.validating as true or undefined when onFieldsChange first triggers.

**Comment by zombieJ** [comment]
> 当表单控件值改变时，且此值符合校验规则时，需要编写代码处理一些业务逻辑。

举个例子？

**Comment by sunchey11** [comment]
例如，form表单中有3个字段：单价、数量、金额。其中金额为自动计算，金额=单价*数量。
     字段单价上有配置校验，现在希望用户在输入单价时，如果输入的单价满足校验规则，则自动计算金额。如果输入的单价不满足校验，则不触发金额的计算。
     想通过响应onValuesChange和onFieldsChange来完成这个逻辑，但是都不合适。
     之前在antd3 的时候，onFieldsChange进两次，第一次validating=true, 第二次validating=false,
所以就判断validating=false，并且errors为空就可以了。
     但是antd4，onFieldsChange会进3次，第一次的时候，valating=false,且errors为空，其实这时还没开始校验。
    不知道有没有其他办法能做到这一点，谢谢

**Comment by mlf75** [comment]
可以在onValuesChange里这样判断

    const errors = this.formRef.current.getFieldsError()
    const target = errors.find(item => item.errors.length)
    if (target) {
      return 
    }

**Comment by Julia95Qian** [comment]
通过onValuesChange中getFieldsError判断错误信息的方法不可行。
表单触发onValuesChange时，未经过验证validateFields，此时form.getFieldsError(namePaths)为空数组，在下次onValuesChange时才会有上次的错误信息。
![image](https://user-images.githubusercontent.com/51627103/230817467-714bac86-a514-4190-b34c-160bf143601c.png)
