### ISSUE TITLE
Tree将children修改为treeData后，只显示“---”

### ISSUE THREAD

**Issue by aiyudeleng** [ant-design/ant-design#25021]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[localhost:3001](localhost:3001)

### Steps to reproduce
每次加载时

### What is expected?
修改为treeData后能正常加载tree

### What is actually happening?
实际tree各个节点显示“---”

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12.0 |
| System | win10 |
| Browser | Edge浏览器（chromium内核） 84.0.516.1 (官方内部版本) dev (64 位) |

---
 <Tree
                                showLine={false}
                                onExpand={this.onExpand}
                                expandedKeys={expandedKeys} 
                                autoExpandParent={autoExpandParent}
                                scroll={{ y: this.state.tableHeight }}
                                onSelect={this.onSelect}
                               treeData={this.state.treeData}
                            >
                              -  {this.state.treeData}//3.X写法正常显示
                            </Tree>}

**Comment by L-Hknu** [comment]
等有数据的时候再渲染组件就好了

**Comment by aiyudeleng** [comment]
> 等有数据的时候再渲染组件就好了

数据是有的。只是换成V4.0的写法后数据没出来。不知道是不是写法上还有哪里不对

**Comment by L-Hknu** [comment]
> > 等有数据的时候再渲染组件就好了
> 
> 数据是有的。只是换成V4.0的写法后数据没出来。不知道是不是写法上还有哪里不对

条件判断数据没有的情况下不渲染组件,有数据后再渲染就可以了

**Comment by L-Hknu** [comment]
> > 等有数据的时候再渲染组件就好了
> 
> 数据是有的。只是换成V4.0的写法后数据没出来。不知道是不是写法上还有哪里不对

this.state.treeData.length>0&&<Tree
showLine = {false}
onExpand = {this.onExpand} expandKeys
= {expandedKeys}
autoExpandParent = {autoExpandParent}
scroll = {{y：this.state.tableHeight}}
onSelect = {this.onSelect}
treeData = {this.state .treeData}
>
-{this.state.treeData} // 3.X写法正常显示
}

**Comment by aiyudeleng** [comment]
> > > 等有数据的时候再渲染组件就好了
> > 
> > 
> > 数据是有的。只是换成V4.0的写法后数据没出来。不知道是不是写法上还有哪里不对
> 
> this.state.treeData.length>0&&<Tree
> showLine = {false}
> onExpand = {this.onExpand} expandKeys
> = {expandedKeys}
> autoExpandParent = {autoExpandParent}
> scroll = {{y：this.state.tableHeight}}
> onSelect = {this.onSelect}
> treeData = {this.state .treeData}
> 
> > 
> 
> -{this.state.treeData} // 3.X写法正常显示
> }

解决了。还是数据的问题。3.X的写法用的是message，4.0用的是title！

**Comment by L-Hknu** [comment]
> > > > 等有数据的时候再渲染组件就好了
> > > 
> > > 
> > > 数据是有的。只是换成V4.0的写法后数据没出来。不知道是不是写法上还有哪里不对
> > 
> > 
> > this.state.treeData.length>0&&<Tree
> > showLine = {false}
> > onExpand = {this.onExpand} expandKeys
> > = {expandedKeys}
> > autoExpandParent = {autoExpandParent}
> > scroll = {{y：this.state.tableHeight}}
> > onSelect = {this.onSelect}
> > treeData = {this.state .treeData}
> > > 
> > 
> > 
> > -{this.state.treeData} // 3.X写法正常显示
> > }
> 
> 解决了。还是数据的问题。3.X的写法用的是message，4.0用的是title！

嗯,异步数据的问题
