### ISSUE TITLE
RangePicker 使用 allowClear 值为 null？

### ISSUE THREAD

**Issue by crazyair** [ant-design/ant-design#25027]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/recursing-wilson-4mdbr?file=/index.js)

### Steps to reproduce
1、点击 range 右边的清空按钮
2、点击提交

### What is expected?
无报错

### What is actually happening?
有报错

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | latest |
| System | mac |
| Browser | chrome |

**Comment by crazyair** [comment]
如果值为  `null` 这样设置默认值是没有效果的 `const { range = [] } = values;`

**Comment by zombieJ** [comment]
和 Input 的 `allowClear` 重置给的是 `''` 一样，RangePicker 清除给的也是值，而不是 `undefined`

**Comment by zombieJ** [comment]
Select 清空也应该是 `null`，防止 breaking change 先不动了。

**Comment by crazyair** [comment]
解构设置默认值不支持 null 蛋疼啊。range 能设置清空值值 [null,null] ？要不可以配置清空值。

**Comment by afc163** [comment]
清空是不是应该是 `[null, null]`?

**Comment by zombieJ** [comment]
> 清空是不是应该是 `[null, null]`?

`allowEmpty` 才允许 start or end 存在 `null`
