### ISSUE TITLE
form.resetFields() 后 focus 操作失效

### ISSUE THREAD

**Issue by BugHiding** [ant-design/ant-design#25028]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-booth-ktt94?file=/index.js)

### Steps to reproduce
1. 点击 reset  按钮

### What is expected?
focus 到对应输入框

### What is actually happening?
未 focus 到对应输入框

### remark
`inputEl.current.input.focus();` 和 `inputEl.current.focus();` 都可以聚焦，顺便想问一下应该使用哪一个，谢谢。

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | macOS 10.15.5 |
| Browser | Chrome 83.0.4103.97 |

**Comment by zombieJ** [comment]
1. reset 会重置组件，后面立刻跟 focus 是聚焦不到的。感觉可以 reset 返回一个 Promise 让用户知道什么时候 reset 重置完成了。

2. `.current.focus()`

**Comment by crazyair** [comment]
> 1. reset 会重置组件，后面立刻跟 focus 是聚焦不到的。感觉可以 reset 返回一个 Promise 让用户知道什么时候 reset 重置完成了。
> 2. `.current.focus()`

Promise
