### ISSUE TITLE
Table Component crashes with a column with key "children"

### ISSUE THREAD

**Issue by jonathancai11** [ant-design/ant-design#25024]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-https-iy24n?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Just open sandbox

### What is expected?
Table should render

### What is actually happening?
Table cannot render, app crashes with 
"TypeError
(data || []).forEach is not a function
"

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | react |
| System | MacOS |
| Browser | Chrome |

---
Thanks for the wonderful library!

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/13002

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12029#issuecomment-418054873
