### ISSUE TITLE
Setting the open value of Select to undefined prevents opening.

### ISSUE THREAD

**Issue by Jab0rnal** [ant-design/ant-design#25030]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-4tzcw?file=/index.js)

### Steps to reproduce
Click the select and nothing will happen.

### What is expected?
If the open value is set to defined I would expect default behavior. I.e the select list would open when clicked.

### What is actually happening?
Nothing. The select list is not opening.

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13 |
| System | Windows 10 |
| Browser | Chrome / all |

---
There is a scenario i have come up against where i want the select list to be open if certain conditions are met. However, if these conditions are not met then i want default behaviour. So my open value of select would be something like:

open={condition || undefined}

However, if it sets undefined the select is then broken as described above.

**Comment by afc163** [comment]
Fixed in 4.6.x: https://codesandbox.io/s/antd-reproduction-template-forked-usu2u?file=/index.js
