### ISSUE TITLE
TreeSelect component first selection failure

### ISSUE THREAD

**Issue by muliawanw** [ant-design/ant-design#25040]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-tzuql?file=/index.js)

### Steps to reproduce
https://codesandbox.io/s/antd-reproduction-template-tzuql?file=/index.js

On the link provided above,
* Click down arrow to expand and select "my leaf" item.
* Observe no item selected and onChange not triggered. (NOK)
* Select the "my leaf" again
* Observe all is good now, item selected and onChange triggered (OK)

Rather random and if fail to reproduce, reload page and/or make some changes to the script (modify the console.log text and save) and try steps above again.

Can also be reproduced on official antd components page https://ant.design/components/tree-select/
on the "Basic" section

Also potentially same issue as https://github.com/ant-design/ant-design/issues/24747
This issue was talking about usage in the form but you dont need form to reproduce issue. Feel free to duplicate if same issue,.

### What is expected?
Expecting the TreeSelect to select the selected item and trigger onChange event

### What is actually happening?
TreeSelect is not selecting the selected item from drop down on first selection

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome Version 83.0.4103.106 (Official Build) (64-bit) |

---
The console print out this message. Not sure if it is related
Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by React and is not a top-level container. Instead, have the parent component update its state and rerender in order to remove this component.

**Comment by afc163** [comment]
I can't reproduce it. Could you try other browsers or Chrome without extensions which may be the cause.

**Comment by afc163** [comment]
merge with #24747
