### ISSUE TITLE
How to split form item into multiple components?

### ISSUE THREAD

**Issue by Wenfengcheng** [ant-design/ant-design#25046]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a relatively large form that contains user information, address information, contact information, etc. I want to split them into three small forms and put them into a large form. And all the information of the three small forms can be submitted when I submit large form.

我有一个比较大的表单，里面包含用户信息，地址信息，联系信息等等，我想把他们拆分为三个小表单然后放到一个大表单.然后我提交时三个小表单的所有信息都可以被提交.

### What does the proposed API look like?
```
<Container>
    <UserInfoForm />
    <AddressInfoForm />
    <ContactInfoForm />
    <SubmitButtonGroup />
<Container/>
```
Can you share some demo about this scene? 

能分享一些关于这种场景的demo?

**Comment by Wenfengcheng** [comment]
@afc163 I'm sorry to ask usage questions here, but I can not find any solution abount the above question.

**Comment by fireairforce** [comment]
> @afc163 I'm sorry to ask usage questions here, but I can not find any solution abount the above question.

try  https://gitter.im/ant-design/ant-design
