### ISSUE TITLE
Add option for keeping MenuPopup open when click it

### ISSUE THREAD

**Issue by hydRAnger** [ant-design/ant-design#25041]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
 in source: https://github.com/ant-design/ant-design/blob/8dc16037d054a6dc83caeefe5093d40ebf6e4a05/components/menu/index.tsx#L312-L315

Can we add option let user define whether the MenuPopup will be closed after click item in it? (if so, I can make a PR)

### What does the proposed API look like?
add option like 'closePopupAutomatically: boolean (defalut: true)'?

**Comment by afc163** [comment]
https://codesandbox.io/s/modern-wood-l9vb0?file=/index.js
