### ISSUE TITLE
Indirect reference instead of direct reference

### ISSUE THREAD

**Issue by lpgph** [ant-design/ant-design#25047]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I use "ts" to use antd, but when I refer to the "tree" component, I need to refer to the type "DataNode" of "tree", and I find that I need to reference from "rc-tree" instead of "antd", which means I need to install "rc-tree"

### What does the proposed API look like?
import { DataNode } from 'antd/es/tree;

**Comment by KumaCool** [comment]
`TreeSelect`中的`treeData: DataNode` 与 `Tree`组件的`DataNode` 不是一个类型.
我在导出类型时只能导出`Tree`组件的类型...是否可以统一标准?
