### ISSUE TITLE
Light Theme Not Working in Menu component

### ISSUE THREAD

**Issue by awarmfastbear** [ant-design/ant-design#25048]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-qg3sth?file=index.js](https://stackblitz.com/edit/react-qg3sth?file=index.js)

### Steps to reproduce
Use the Menu examples from the docs and try setting the theme to light. Certain parts of the page will be dark.

### What is expected?
The whole page should be light.

### What is actually happening?
Certain components are dark and some are light

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12 |
| System | Windows 10 |
| Browser | Firefox 77 |

---
Why is it that the 'light' theme does not make everything light?

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-qg3sth-qcasuh?file=index.js

**Comment by awarmfastbear** [comment]
@afc163  how do you get the Header to follow the same theme color?

**Comment by Camble** [comment]
> https://stackblitz.com/edit/react-qg3sth-qcasuh?file=index.js

This works for the Sider component, but not Header

**Comment by monolithed** [comment]
The Header component looks very specific. What is the reason of using a dark background by default?

**Comment by Baileymnm1999** [comment]
What a contributer @afc163. I bet you contribute so much! You are such a good contributer. In fact, I bet, if you didn't spend so much time contributing quality content such as your comment above... you might have stopped to notice that the header does NOT work. [https://stackblitz.com/edit/react-qg3sth-z57nww?file=index.js](https://stackblitz.com/edit/react-qg3sth-z57nww?file=index.js)

**Comment by afc163** [comment]
@Baileymnm1999 In antd demo, we use custom className in Header to make it white, check https://ant.design/components/layout/#components-layout-demo-side

**Comment by ReturnMeVoid** [comment]
Finally what do to with that issue?

**Comment by gurungsandesh** [comment]
we can inherit the background color. @ReturnMeVoid

**Comment by djtriptych** [comment]
Still seeing this issue =/
