### ISSUE TITLE
关于Sider Menu二级菜单

### ISSUE THREAD

**Issue by hydRAnger** [ant-design/ant-design#25042]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
请问现在的Sider Menu，可以或如何实现类似下图所示的横向二级菜单功能呢？_

现有实现里(https://github.com/ant-design/ant-design/blob/master/components/menu/demo/vertical.md)
SubMenu是通过popup来展现的，如何实现更‘持久化’的二级菜单呢？即带有占位或者说地位更接近于Menu呢？

### What does the proposed API look like?

![image](https://user-images.githubusercontent.com/1228449/84841301-e3a69580-b07c-11ea-9941-27127aebf47b.png)

**Comment by afc163** [comment]
用两个 Menu 联动实现。
