### ISSUE TITLE
cnpm i的时候报错

### ISSUE THREAD

**Issue by yuu2lee4** [ant-design/ant-design#2505]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：win10 64bit
- 浏览器及其版本: chrome 53

#### 你做了什么？
cnpm install

#### 你期待的结果是：
正常

#### 实际上的结果：
![1](https://cloud.githubusercontent.com/assets/8046366/17129053/549b63f6-5343-11e6-91d6-678637f606d2.png)

**Comment by afc163** [comment]
你为什么需要 `cnpm install`。

另外，本项目开发不支持 tnpm@4。

**Comment by yuu2lee4** [comment]
安装依赖啊。。。npm 4  不支持？

**Comment by afc163** [comment]
没有 npm@4，只有 tnpm@4 ，请使用 npm 的官方版本。
