### ISSUE TITLE
Form.List中的Form.Item添加校验规则required: true，字段没有必填标识*

### ISSUE THREAD

**Issue by yaeSakuras** [ant-design/ant-design#25052]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-10iof?file=/index.js)

### Steps to reproduce
Form.List中添加一个Form.Item并加上rules={[{ required: true, message: "Please input!" }]}没有必填标识*

### What is expected?
希望Form.Item加上rules={[{ required: true, message: "Please input!" }]}有必填标识*

### What is actually happening?
没有必填标志

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | mac os  |
| Browser | chrome 83 |

**Comment by Ceilon** [comment]
为什么没人回答呢

**Comment by yoyo837** [comment]
复现不可用，且自行关闭了issue.
