### ISSUE TITLE
Form.List 里的 Select 组件，手动设置 Select 的值为 undefined 无效，值还是被渲染到了页面上

### ISSUE THREAD

**Issue by dreamqyq** [ant-design/ant-design#25057]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sharp-paper-u7dlz?file=/index.js)

### Steps to reproduce
1. 点击 Add Field
2. 选择第一个Select，选 1
3. 如果提示“ 不能选1” ，再次选 1
4. 设置了 value 为 undefined，但是 Select 还是展示了 1，而不是 placeholder 效果

### What is expected?
如果 select 选1，绑定的 fieldValues 对应的 value 为 undefined，页面上应当展示 select 的 placeholder 效果，这个值不应该被渲染到页面上

### What is actually happening?
select 选择 1，页面上展示的是 1，而不是 placeholder 效果

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.12.0 |
| System | Mac OS |
| Browser | Chrome |

---
- 先选 0，再选 1，是可以设置成 undefined 的，页面上也正确设置成了 undefined；
- 选 1失败，再次 选1，虽然绑定的 value 的值是 undefined，但是页面上还是展示为 1。

**Comment by afc163** [comment]
```diff
- setFieldValues([...fieldValues, { value: undefined }]);
+ setFieldValues([...fieldValues, { value: null }]);
```

用 `null` 而不是 `undefined` 作为空值，`undefined` 等同于没有 value。

**Comment by dreamqyq** [comment]
@afc163 十分感谢你的回复

但是 设置为 null，Select的 **placeholder** 就没了啊。
另外，value绑定的值如果是null，ts会报错。value的类型只有这几种：`string | number | RawValue[] | LabeledValue | LabeledValue[] | undefined`

请问有办法解决吗，再次感谢🙏

**Comment by afc163** [comment]
@zombieJ 看看。

**Comment by zombieJ** [comment]
`null` 设置了没有 `placeholder` 是 bug。

**Comment by zombieJ** [comment]
看了一下，为了支持 Option 值为 `null` 的情况它也会转成一个 displayValue，特殊处理一下，遇到没有 label 的 null 也当没值。

**Comment by afc163** [comment]
undefined 也应该处理吧，https://ant.design/components/form-cn/#components-form-demo-control-hooks 这个例子 Select reset 的时候接收的就是 undefined。

**Comment by zombieJ** [comment]
看了一下 undefined 本来就是处理的，这里是因为 value 原本是 `undefined` 受控改掉的值还是 `undefined` ，所以对 Select 来说 `value` 一直都是 `undefined` 也就非受控了。

**Comment by dreamqyq** [comment]
@zombieJ 首先十分感谢你的回复。

但是按照你的说法，从 undefined 改为 undefined，Select 就非受控了。那么下面这个例子：

1. https://codesandbox.io/s/antd-select-clear-l4n69
   为什么我怎么选择 1 ，无论怎么操作，1 都不会回写到 select 上，

2. 而本 issue 最上面的那个例子里，https://codesandbox.io/s/sharp-paper-u7dlz?file=/index.js
  2.1 先选择了 0，再选择 1，select受控了，页面显示为 placeholder 状态，正常
  2.2 如果这么操作：选 0 ，然后选 1，继续选 1，select就被回填了 1。

请问：为什么都是从undefined 变为 undefined，情况 1受控了，而情况2却非受控了？

期待您的回复，谢谢🙏

**Comment by zombieJ** [comment]
```diff
--- "antd": "3.26.7",
+++ "antd": "4.x",
```
