### ISSUE TITLE
Unite api(boolean) in site

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#25056]
![image](https://user-images.githubusercontent.com/29775873/84878650-b37ee700-b0bc-11ea-8e46-3ea41568bfd1.png)

官网 API 中 boolean 出现 2 种表达方式。计划统一一下。

- [x] 1. true

- [ ] 2. `true`

用哪一种？

**Comment by afc163** [comment]
true 吧。

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/25058#issuecomment-645405077
