### ISSUE TITLE
Theme property for the Layout header component?

### ISSUE THREAD

**Issue by awarmfastbear** [ant-design/ant-design#25051]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-bxmvf8?file=index.js](https://stackblitz.com/edit/react-bxmvf8?file=index.js)

### Steps to reproduce
Change the theme of the layout's menu and sider to light and the header defaults to dark.

### What is expected?
The header's color should follow the color of the menu or siders color. Instead it defaults to dark without a clear way to dynamically change it besides overriding the CSS

### What is actually happening?
The header defaults to dark

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | Windows |
| Browser | Firefox 77 |

---
How can the Header component be dynamically themed without needing to adjust css?

Ideally the layout component could have a theme property as it is the parent for Header, Sider, Menu, etc, which would effect those components.

**Comment by xrkffgg** [comment]
Menu `theme="dark"`

Also, can use a variable to control theme.

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-bxmvf8?file=index.js

```diff
- <Header className="header">
+ <Header className="header" style={{ background: '#fff' }}>
```
