### ISSUE TITLE
issue connected to setFieldsValue for Avatar

### ISSUE THREAD

**Issue by HarutSargsyan** [ant-design/ant-design#25060]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vd1v7?file=/App.js:351-352)

### Steps to reproduce
I think you should add that ability for Avatar, and in my code, there are also other components for choosing an image and changing it.

### What is expected?
I expect that it should enable the save button too because I update remaining fields and it works, but for Avatar field it doesn't work.

### What is actually happening?
It doesn't work for Avatar when we change it, it doesn't enable save button, so it means onValueChange doesn't work for my Avatar form item.

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | Mac OS X 10.14.16 |
| Browser | Google Chrome |

---
The situation is like this, I have a form and lots of Input Fields, only for this we are using antd Upload component when we change all remaining fields it makes Save button enable, only when we are changing picture it doesn't.

**Comment by afc163** [comment]
First of all, Avatar is not a typical form control.

You can check https://ant.design/components/form/#components-form-demo-customized-form-controls for custom form component.

**Comment by HarutSargsyan** [comment]
which names are equal to the value of trigger
<https://ant.design/components/form/?locale=en-US#getFieldDecorator's-parameters>

**Comment by HarutSargsyan** [comment]
I have just can't find other names besides onChange
