### ISSUE TITLE
Module not found: Error: Cannot resolve module 'css'

### ISSUE THREAD

**Issue by willcj** [ant-design/ant-design#2506]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：mac mini 10.9.5
- 浏览器及其版本:浏览器及其版本:chrome 51.0.2704.106 (64-bit) 

#### 你做了什么？
npm start 后打开chrome访问localhost:3002 ,页面空白

报错信息如下

ERROR in ../~/antd/lib/button/style/index.js
Module not found: Error: Cannot resolve module 'css' in /Users/projects/node_modules/antd/lib/button/style
 @ ../~/antd/lib/button/style/index.js 3:0-33

ERROR in ../~/antd/lib/button/style/index.js
Module not found: Error: Cannot resolve module 'css' in /Users/projects/node_modules/antd/lib/button/style
 @ ../~/antd/lib/button/style/index.js 5:0-23

ERROR in ../~/antd/lib/input/style/index.js
Module not found: Error: Cannot resolve module 'css' in /Users/projects/node_modules/antd/lib/input/style
 @ ../~/antd/lib/input/style/index.js 3:0-33

ERROR in ../~/antd/lib/input/style/index.js
Module not found: Error: Cannot resolve module 'css' in /Users/projects/node_modules/antd/lib/input/style
 @ ../~/antd/lib/input/style/index.js 5:0-23

ERROR in ../~/antd/lib/form/style/index.js
Module not found: Error: Cannot resolve module 'css' in /Users/projects/node_modules/antd/lib/form/style
 @ ../~/antd/lib/form/style/index.js 3:0-33

ERROR in ../~/antd/lib/form/style/index.js
Module not found: Error: Cannot resolve module 'css' in /Users/projects/node_modules/antd/lib/form/style
 @ ../~/antd/lib/form/style/index.js 5:0-23

**Comment by benjycui** [comment]
依赖没安装好吧，删除重装，建议使用 cnpm

**Comment by willcj** [comment]
@benjycui 试了好久，删了node 用brew 装的，之后还是有这个问题

**Comment by afc163** [comment]
Try `rm -rf node_modules && cnpm install`

https://cnpmjs.org/

**Comment by willcj** [comment]
@afc163  Thanks 

我的解决办法如下

1 删除所有 node 相关联内容

参照：http://benznext.com/2015/04/completely-uninstall-node-js-from-mac-os-x/

The following is the best way to completely uninstall node + npm:
1 	go to /usr/local/lib and delete any node and node_modules
2 	go to /usr/local/include and delete any node and node_modules directory
3 	if you installed with brew install node, then run brew uninstall node in your terminal
4 	check your Home directory for any local or lib or include folders, and delete any node or node_modules from there
5 	go to /usr/local/bin and delete any node executable
You may need to do the additional instructions as well:
1 	sudo rm /usr/local/bin/npm
2 	sudo rm /usr/local/share/man/man1/node.1
3 	sudo rm /usr/local/lib/dtrace/node.d
4 	sudo rm -rf ~/.npm
5 	sudo rm -rf ~/.node-gyp
6 	sudo rm /opt/local/bin/node
7 	sudo rm /opt/local/include/node
8 	sudo rm -rf /opt/local/lib/node_modules
9 	sudo rm -rf /usr/local/include/node/

2 重新安装Node

参照：https://github.com/npm/npm/issues/3125

sudo brew uninstall node
brew update
brew upgrade
brew cleanup
brew install node
sudo chown -R $(whoami) /usr/local
brew link --overwrite node
sudo brew postinstall node


3 安装cnpm

参照：https://cnpmjs.org/

npm install -g cnpm --registry=https://registry.npm.taobao.org

4 删除原项目中node_modules 执行 cnpm install

rm -rf node_modules && cnpm install

5 npm start 
   
    OK
