### ISSUE TITLE
Doc API standard 

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#25066]
### 背景
为保证文档中 API 描述信息的一致规范，拟按照现有书写规范，及 #25056、#20907 中对 string 和 boolean 的讨论结果，将 API 中各类型和书写方式进行统一。并写入 Wiki 中。
- [x] Wiki

### 链接
https://ant.design/components/button-cn/#API

### 目标
https://github.com/ant-design/ant-design/wiki/API-Naming-rules

### 举例

| 参数      | 说明                   | 类型                           | 默认值 |
| --------- | ---------------------- | ------------------------------ | ------ |
| htmlType | xxx        | string                               | `button `      |
| type          | xxx           | `horizontal ` \| `vertical ` | `horizontal` |
| disabled  | xxx           | boolean                            | false  |
| minLength      | xxx                         | number                           | 0      |
|  style      | xxx                    | CSSProperties                  | -   |
| character | xxx | (props) => ReactNode | - |
| offset       | xxx  | \[number, number] | \[0, 0] | 
| value     | xxx         | string \| number | `small`     | 

### 约定
- string 类型时，**默认值**使用  ` `` `。
- 也可在类型中列举 string 可选值。
- boolean 类型时，**默认值**使用 true 或 false。
- number 类型时，**默认值**直接使用数字。
- function 类型时，在**类型**中使用箭头函数表达式。
- 无**默认值**使用 - 。
- **说明**末尾无句号。

---

### Examples

| Property      | Description                   | Type                           | Default |
| --------- | ---------------------- | ------------------------------ | ------ |
| htmlType | xxx        | string                               | `button `      |
| type          | xxx           | `horizontal ` \| `vertical `  | `horizontal` | 
| disabled  | xxx           | boolean                            | false  |
| minLength      | xxx                         | number                           | 0      |
|  style      | xxx                    | CSSProperties                  | -   |
| character | xxx | (props) => ReactNode | - |
| offset | xxx| \[number, number] | \[0, 0] |
| value     | xxx         | string \| number | `small`      | 

### Promise
- When string type, the **Default** use ` `` `.
- Can also list string optional values ​​in **Type**.
- When boolean type, the **Default** value is true or false.
- When number type, the **Default** value use numbers directly.
- When function type, use an arrow function expression in **Type**.
- No default value use - .
- Capitalize the first letter in **Description** apart from `someProp`.
- No period at the end of the **Description**.

**Comment by xrkffgg** [comment]
欢迎补充

相关 Issues :

- https://github.com/ant-design/ant-design/issues/25056

- https://github.com/ant-design/ant-design/issues/20907

相关 PR :

- https://github.com/ant-design/ant-design/pull/25058

- https://github.com/ant-design/ant-design/pull/20970

间接：

https://github.com/ant-design/ant-design/issues/16048

**Comment by hengkx** [comment]
无默认值可使用 -
会不会有点多余

**Comment by xrkffgg** [comment]
> 无默认值可使用 -
> 会不会有点多余

因为出现各种写法，有的是 - ，有的写 无 ，有的 空白

**Comment by hengkx** [comment]
这个问题 之前 提过一次 太多了 有心无力

**Comment by xrkffgg** [comment]
这里也可以讨论下，无的情况用什么表示

- [ ] -
- [ ] 无
- [ ] (空)

**Comment by xrkffgg** [comment]
> 这个问题 之前 提过一次 太多了 有心无力

我觉得文档是对外的，没有一个稍微统一的写法，别人就会觉得很乱。尤其还是面向国际。

**Comment by Kermit-Xuan** [comment]
我倾向于1

**Comment by afc163** [comment]
Wike => Wiki

**Comment by xrkffgg** [comment]
@afc163 @zombieJ 看一下，哪里还需要改动、补充。准备加 Wiki 。

**Comment by xrkffgg** [comment]
还发现了一个地方。Description  说明的地方。

英文首字母 是否需要大写？

结尾是否需要加标点？

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/85094649-e7275180-b221-11ea-9745-68eab949809b.png)

**Comment by fireairforce** [comment]
首字母小写，无标点吧

**Comment by Rustin-Liu** [comment]
大写，有标点。

**Comment by zombieJ** [comment]
表格每个类型的 defaultValue 都写一下，然后最后加一行没有默认值的情况。

**Comment by zombieJ** [comment]
印象里中文末尾是没有标点的，省一点空间。

**Comment by zombieJ** [comment]
> 印象里中文末尾是没有标点的，省一点空间。感觉可以商榷，不是很重要。定下就行。

这个感觉可以做一个 lint 来检查一下。

**Comment by xrkffgg** [comment]
@zombieJ @afc163 看一下

**Comment by xrkffgg** [comment]
已更新 Wiki，计划 4.4.0 上线后，再逐步统一。

**Comment by xrkffgg** [comment]
Done.
