### ISSUE TITLE
Show Empty component when table filter has no data

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#25068]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
https://codesandbox.io/s/antd-reproduction-template-o4q18?file=/index.js

enter this codesandbox and click on the table filter
currently this is what the user will see when there is no filters
![image](https://user-images.githubusercontent.com/42112796/84933184-2e0c2e80-b0de-11ea-98b1-55a15f54bc2a.png)

I think it would be better if he will see something like
![image](https://user-images.githubusercontent.com/42112796/84933087-04530780-b0de-11ea-846b-26b535d2d225.png)

### What does the proposed API look like?
it should be the default beaviour

**Comment by afc163** [comment]
Please upgrade your less version to `3.x`.
