### ISSUE TITLE
RuleType "type" doesn't include "array"

### ISSUE THREAD

**Issue by gwuah** [ant-design/ant-design#25078]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z?file=/index.js)

### Steps to reproduce
Project Too Large to isolate

### What is expected?
Setting rule of type "array" for tag select component should work successfully. (Typescript project)

### What is actually happening?
Setting property rule with value "array" for tag select components fails because it's not declared in the `RuleType` type.

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | MacOS Mojave 10.14.6  |
| Browser | Chrome |

Possible values of rule as defined by `async-validator` includes the "array" prop as expected.
<img width="614" alt="Screen Shot 2020-06-18 at 4 30 25 AM" src="https://user-images.githubusercontent.com/24861123/84978744-3899e880-b11d-11ea-83fb-bf469613875c.png">

But in` rc-field-form/lib/interface.d.ts`, RuleType doesn't include "array"
![Screen Shot 2020-06-18 at 4 30 09 AM](https://user-images.githubusercontent.com/24861123/84978819-6717c380-b11d-11ea-80cc-1ea82594c4c4.png)

**Comment by gwuah** [comment]
@afc163 Hey so I was just wanted to be sure, this isn't an issue from antd right?
The pull request has to go against https://github.com/react-component/field-form/blob/master/src/interface.ts rather.

**Comment by afc163** [comment]
We include `array` in here: https://github.com/react-component/field-form/blob/3457cc0cd821000d90c3b3fde7b4aa4de96ddf8d/src/interface.ts#L70

**Comment by afc163** [comment]
Right, you can send PR to https://github.com/react-component/field-form

**Comment by NuoHui** [comment]
sorry, @gwuah 。 https://github.com/react-component/field-form/blob/master/src/interface.ts#L70。 You can provide a demo？

**Comment by zj9495** [comment]
array type is already defined here https://github.com/react-component/field-form/blob/master/src/interface.ts#L81
should we close this issue?@afc163
