### ISSUE TITLE
Error on calling setState inside onValuesChange method if any of the Form.Item is inside Form.List

### ISSUE THREAD

**Issue by arptg** [ant-design/ant-design#25071]
- [ * ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-volhard-lif8f?file=/index.js)

### Steps to reproduce
1. Render Some Form.Item inside Form.List
2. Put setState call inside onValuesChange method
3. Change value inside the nested Form.Item

### What is expected?
The state should be updated

### What is actually happening?
throws an error - value.map is not a function

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.3.1 |
| System | All |
| Browser | All |

---
I am not sure if this was the intended behaviour, if it is , why ?

**Comment by zombieJ** [comment]
Close since codesandbox is gone.
