### ISSUE TITLE
Use some css-in-js solution?

### ISSUE THREAD

**Issue by zhaoyao91** [ant-design/ant-design#25079]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
- easy for development
- easy for integration
- easy for use
- dynamic

### What does the proposed API look like?
refer to [material-ui](https://material-ui.com/), [evergreen](https://evergreen.segment.com/)

**Comment by afc163** [comment]
see #5656

**Comment by zhaoyao91** [comment]
@afc163 this issue is not about theming, theming is just another thing which has related to the styling mechanism.

Using css-in-js or traditionon less is much a low level decision which deserve a deep disscusion.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/5570#issuecomment-332551645
https://github.com/ant-design/ant-design/issues/5656#issuecomment-339271633

**Comment by zhaoyao91** [comment]
well, fine.

**Comment by zhaoyao91** [comment]
@afc163 If there is a chance to create a new generation of antd, will you choose css-in-js solution or stick to less?
