### ISSUE TITLE
table filter过滤条件交互问题？

### ISSUE THREAD

**Issue by marchFantasy** [ant-design/ant-design#2507]
#### 本地环境
- antd 版本:1.6.5
- 操作系统及其版本：Mac 10.11.6
- 浏览器及其版本:chrome 51

#### 你做了什么？

table的列选项添加过滤功能时，交互是有问题的？
http://ant.design/components/table/#components-table-demo-reset-filter
官网也有问题

#### 实际上的结果：

![image](https://cloud.githubusercontent.com/assets/3906826/17130366/c2bb079a-534a-11e6-8e1b-8f3f40337d02.png)
点击“姓李的”，实际并没有立即响应，下拉框也自动关闭；接着，点击“姓胡的”，这时候数据过滤成姓李的，“姓胡的”选项竟然没被选中；每次点击下拉菜单都自动关闭，很不方便，过滤条件也不是立即生效。

正常交互，我觉得是：
1，点击“姓李的”，立即响应过滤数据都是“姓李的”；这样［确定］按钮就不需要了
2，如果保留［确定］按钮，在勾选checkbox时，下来框不要总是关闭，这样才能点击确定

#### 可重现的在线演示
http://ant.design/components/table/#components-table-demo-reset-filter

**Comment by afc163** [comment]
嗯，正确的交互不是这样的，搞坏了。

**Comment by afc163** [comment]
Broken here: https://github.com/react-component/dropdown/commit/f6ff40373c5d7c412768f800c9271d712a7a9abd

**Comment by afc163** [comment]
重安 antd 即可。

**Comment by marchFantasy** [comment]
@afc163 ，谢谢，辛苦了！
