### ISSUE TITLE
Can't work when Upload in Popover

### ISSUE THREAD

**Issue by wygkzqa** [ant-design/ant-design#25077]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/objective-solomon-1hfwe?file=/index.js)

### Steps to reproduce
Please see the demo

### What is expected?
Popover is working

### What is actually happening?
Popover doesn't work

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | macOS 10.15.5 |
| Browser | Chrome 83 |

**Comment by xrkffgg** [comment]
你的 Demo 第一个例子不是正常的嘛

**Comment by xrkffgg** [comment]
```
<Upload {...props}>
  <Popover title="Title" content="test content">
    <Button>
      <UploadOutlined /> Upload
    </Button>
  </Popover>
</Upload>
```

**Comment by wygkzqa** [comment]
> ```
> <Upload {...props}>
>   <Popover title="Title" content="test content">
>     <Button>
>       <UploadOutlined /> Upload
>     </Button>
>   </Popover>
> </Upload>
> ```

This will trigger Upload click event?

**Comment by xrkffgg** [comment]
You can try in your CodeSandbox.

**Comment by wygkzqa** [comment]
Yes, i mean this will trigger Upload click event. That's not what i want, i don't want Popover.content trigger click event.
