### ISSUE TITLE
table设置过滤列，过滤列中使用select的问题

### ISSUE THREAD

**Issue by ranzhu123** [ant-design/ant-design#2508]
#### 本地环境
windows

- antd 版本:1.6.4
- 操作系统及其版本：window8
- 浏览器及其版本:chrome51.0.2704.103

#### 你做了什么？
使用table添加过滤列，过滤列中添加了TreeSelect，希望可以使用TreeSelect获取过滤的数据。

#### 你期待的结果是：

在过滤框（dropdown）中使用treeSelect的时候能够和其他情况下正常使用

#### 实际上的结果：

第一次打开的时候，点击其他区域，应该关闭treeSelect会出现treeselect关不掉的现象，点击过滤按钮才可以关闭，（考虑是不是阻止了冒泡？）第二次打开的时候选择treeselect的checkbox的时候会触发dropdown的关闭事件。导致treeselect的框自动关闭，再次点击treeselect的时候会移动到最上边去。

#### 可重现的在线演示
![default](https://cloud.githubusercontent.com/assets/12227617/17132590/0568762c-5355-11e6-8478-5bcfa98309e9.gif)

http://codepen.io/anon/pen/yJjmdJ?editors=001#anon-login 这只是filterDropdown的代码，需要放到table的filterDropdown里

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1736

**Comment by ranzhu123** [comment]
这个我看过了，但是并没有解决的方法？

**Comment by afc163** [comment]
用这个 filterDropdown 自定义浮层的内容，filters 目前不支持自定义组件。
