### ISSUE TITLE
Control between forms doesn't work as intended

### ISSUE THREAD

**Issue by stefan-unimaze** [ant-design/ant-design#25087]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-form-context](https://ant.design/components/form/#components-form-demo-form-context)

### Steps to reproduce
You can reproduce this in the example "Control between forms" on the ant.design components documentation

Add a user through the form in the modal.
The user appears in the list in the basicForm.
Submit the form

### What is expected?
'values' in onFinish is expected to have 'group' and 'users' values

### What is actually happening?
'values' in onFinish only have 'group'

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 83.0.4103.97 |

**Comment by domino14** [comment]
Shouldn't this be removed from the documentation? It doesn't work.. is there a workaround?
