### ISSUE TITLE
form表单的 initialValue 对switch无效。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#25091]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/awesome-feynman-vr4b4?file=/index.js)

### Steps to reproduce
1:运行重现链接的程序。
2:查看console，明明academyFlag是true，为什么我的switch没有选中呢？

### What is expected?
应该Switch应该被选中。

### What is actually happening?
Switch初始的时候没被选中。

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | react |
| System | win10  |
| Browser | chrome |

**Comment by defpis** [comment]
同求解决方法，switch状态无法同步

**Comment by xrkffgg** [comment]
Switch  加个这个如何
```js
defaultChecked={academyFlag}
```

**Comment by defpis** [comment]
找到解决方法了添加在Form.Item 上添加树形valuePropName="checked"

```typescript
<Form.Item label="启动状态" name="enabled" valuePropName="checked">
    <Switch />
</Form.Item>
```

**Comment by defpis** [comment]
valuePropName | 子节点的值的属性，如 Switch 的是 'checked'。该属性为 getValueProps 的封装，自定义 getValueProps 后会失效
-- | --

**Comment by xrkffgg** [comment]
他例子上加了 `valuePropName`，但是没加 `name`

**Comment by xgj1988** [comment]
@xrkffgg   居然和有没有name有关系。，，我丢。。

**Comment by lspeer** [comment]
> @xrkffgg 居然和有没有name有关系。，，我丢。。
如果1是开启，2是关闭，这种怎么处理呢
