### ISSUE TITLE
Modal的destroyOnClose对form表单没用？太坑了。。Modal基本上都是和Form联用。

### ISSUE THREAD

**Issue by xgj1988** [ant-design/ant-design#25092]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-shadow-ji3hp?file=/index.js:565-579)

### Steps to reproduce
1:点击打开Modal按钮，Modal打开，然后看到输入框是张三丰。
2：关闭的时候其实已经把currentItem设置为{｝,已经没有username了。
3：在点击打开Modal2，会发现还有username。

### What is expected?
应该没有username

### What is actually happening?
有username

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | react |
| System | win10 |
| Browser | chrome |

---
我知道应该是把状态放在了form这里面，但是我觉得就是坑爹。。我感觉有很多莫名的问题会出现。。从api语义上来说，也容易产生歧义。

**Comment by afc163** [comment]
Duplicate of #21740
