### ISSUE TITLE
Tooltip ref error if React.memo is child

### ISSUE THREAD

**Issue by IndProgo** [ant-design/ant-design#25094]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tooltip-react-memo-sv0ko?file=/index.js)

### Steps to reproduce
Open Codesandbox console. Refresh preview if needed.

### What is expected?
No error

### What is actually happening?
If Tooltip child is functional component with React.memo() hoc, it causes error: Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13 |
| System | windows |
| Browser | any |

**Comment by mjfwebb** [comment]
This will fix it:

`const Custom = React.memo(React.forwardRef((props, ref) => <span ref={ref} {...props} />));`
