### ISSUE TITLE
RangePicker的ranges建议可配置text以满足国际化

### ISSUE THREAD

**Issue by heyepeng** [ant-design/ant-design#25095]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前:
ranges: {
          '今天': [moment(), moment()],
          '本周': [moment().startOf('week'), moment().endOf('week')],
          '本月': [moment().startOf('month'), moment().endOf('month')],
        }
这种以Object的key作为text的方式不便于对按钮text进行国际化。

### What does the proposed API look like?
ranges: [
	{text:'本周'，range:[moment().startOf('week'), moment().endOf('week')]},
	{text:'本月'，range:[moment().startOf('month'), moment().endOf('month')],}
]

**Comment by hicrystal** [comment]
看了一下这个需要改rc-picker，亲 要不然你试试在那边提交另一个issue？

**Comment by hicrystal** [comment]
看了一下是`rc-picker` 规定的ranges，不太确定能不能在这个库里面来做

**Comment by afc163** [comment]
可以。

**Comment by hicrystal** [comment]
好的 那我这两天会试着提一个PR

**Comment by guji-david** [comment]
现在这个国际化可以用了不？

**Comment by promotion-xu** [comment]
同问，这个国际化提交pr了吗 @afc163

**Comment by promotion-xu** [comment]
@heyepeng 这个问题解决了吗

**Comment by kerm1it** [comment]
@promotion-xu  用动态 key 的方式应该可以满足吧？

``` js
ranges: {
 [i18n.get('today')]: [moment(), moment()],
 [i18n.get('currentWeek')]: [moment().startOf('week'), moment().endOf('week')],
 [i18n.get('currentMonth')]: [moment().startOf('month'), moment().endOf('month')],
}
```

**Comment by promotion-xu** [comment]
@kerm1it 谢谢你，可以了
