### ISSUE TITLE
selectTree 能也也加个fieldNames

### ISSUE THREAD

**Issue by zhans1099** [ant-design/ant-design#25098]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
数据结构不总是 label、value和children
最好和Cascader级联选择一样加个fieldNames

### What does the proposed API look like?
{ label: 'label', value: 'value', children: 'children' }

**Comment by afc163** [comment]
#24282
