### ISSUE TITLE
Search in Tooltip doesn't work

### ISSUE THREAD

**Issue by michele-b** [ant-design/ant-design#25099]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-jjvp8)

### Steps to reproduce
Press search, you get the error "Could not consume error: Error {stack: "r/e.inject/p</</<@https://codesandbox.io/static/js/sandbox.30aba3f91.js:1:63616 "}"

### What is expected?
Value must be searched value

### What is actually happening?
You get the error "Could not consume error: Error {stack: "r/e.inject/p</</<@https://codesandbox.io/static/js/sandbox.30aba3f91.js:1:63616 "}" on press search

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | React 16 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
Seems to have been fixed in https://github.com/ant-design/ant-design/pull/25049

**Comment by xrkffgg** [comment]
I did a test, it has fixed.
