### ISSUE TITLE
在Form中使用Cascader时，怎么把selectedOptions添加为最终输出值，现在默认是把value添加到Form中

### ISSUE THREAD

**Issue by 23cicada** [ant-design/ant-design#25093]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
默认输出为选中后的数组，但实际中每个值往往需要对应的键值。

### What does the proposed API look like?
可以设置其他值添加到Form中

**Comment by coldice945** [comment]
在 Form 中使用 Cascader，又想把 label 传递过去。可以通过 `getValueFromEvent` 和 `getValueProps` 的组合达到 Cascader 组件 labelInValue 的目的。代码如下。

```
<Form
  initialValues={{
    region: [
      { value: "110000", label: '北京市' },
      { value: "110100", label: '北京市' },
      { value: "110101", label: '东城区' },
    ],
  }}
>
  <Form.Item
    name="region"
    label="城市"
    getValueFromEvent={(value, selectedOptions) => selectedOptions}
    getValueProps={val => ({ value: val.map(i => i.value) })}
  >
    <Cascader options={regionOptions} />
  </Form.Item>
</Form>
```
