### ISSUE TITLE
Table 第一页初始化时不显示数据

### ISSUE THREAD

**Issue by carr123** [ant-design/ant-design#251]
我用Ajax 从服务器获取数据，然后setState 让 Table 去显示。
代码形如:   < Table columns={columns}   dataSource={data}  / >
data 就是我根据服务器返回的数据组成的数组。

当Table的数据低于10个时，第一页正常显示没问题。
当Table的数据超过10个时，分多页显示，带Pagination.  
但是刚开始刷新时第一页不显示数据，点击第二页后就显示第二页数据，再点回第一页就能显示第一页数据了。

**Comment by afc163** [comment]
试试 beta 版本。

```
npm install antd@beta
```

**Comment by carr123** [comment]
beta 版本 可以了。 谢谢！
