### ISSUE TITLE
ResizableTextArea autoSize logic causes incorrect scroll position

### ISSUE THREAD

**Issue by SamKirkland** [ant-design/ant-design#25103]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-textarea-resize-reproduction-d9s44?file=/index.js)

### Steps to reproduce
Copy the textbox content and then paste multiple (20 ) times. Notice the scroll position is now out of sync.

This problem is 

### What is expected?
The textbox should scroll to the current position my cursor is at. My cursor should always be visible.

### What is actually happening?
The textbox attempts to scroll to the cursors position but instead scrolls to the cursors position without a scrollbar, instead of with a scrollbar.

When the scrollbar is re-added the width of the textbox is smaller which increases its height. Throwing off the scroll position.

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Tested on Chrome v83, FireFox v77 |

---
This is due to the [following code](https://github.com/ant-design/ant-design/blob/8dd8a19d6fffe24c7239f3f9d1fb7f35b767b157/components/input/ResizableTextArea.tsx#L140) which removes the scrollbar - throwing off the calculations.

I noticed [this note](https://github.com/ant-design/ant-design/blob/8dd8a19d6fffe24c7239f3f9d1fb7f35b767b157/components/input/ResizableTextArea.tsx#L20), but was unable to understand what this was trying to fix. I'm assuming this was to resolve the opposite issue, keeping a scrollbar around when none was needed.

```typescript
const RESIZE_STATUS_NONE = 0;
const RESIZE_STATUS_RESIZING = 1;
const RESIZE_STATUS_RESIZED = 2;
```

**Comment by afc163** [comment]
@Kermit-Xuan

**Comment by Kermit-Xuan** [comment]
@SamKirkland  To resolve [#20674](https://github.com/ant-design/ant-design/issues/20674)

**Comment by Kermit-Xuan** [comment]
@afc163 I don't know why setting `overflow` to `hidden` when resizeStatus is `RESIZE_STATUS_RESIZING`?

![image](https://user-images.githubusercontent.com/33770367/85102072-6b83cf80-b236-11ea-9f57-02cf0dbce73c.png)

**Comment by zombieJ** [comment]
It's caused that when text is just fill the width, `overflow-y: auto` will not show the scroll bar.

But when add text to make scroll bar appear, change text back to prev text will not make the scrollbar hidden.

So it need to make `overflow: hidden` to force browser re-calculate the overflow.

**Comment by Kermit-Xuan** [comment]
This is closed first, it will reopen when need.
