### ISSUE TITLE
Form on finish gives only the current values of from items in the DOM

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#25101]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-4j0sf?file=/index.js)

### Steps to reproduce
1. open codesandbox 
2. click on submit form
3. see the results in the alert
4. click on second step
5 repeat on 2. and 3.

### What is expected?
form should save all the data, even if some of Form.items currently not rendered

### What is actually happening?
form on finish only gives the data of currently form items in the DOM

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome 83 |

---
I want to be able to render long form of few steps, maybe there's a way I'm not aware of it, to achieve it

**Comment by afc163** [comment]
Try `<Form.Item hidden />`: https://codesandbox.io/s/antd-reproduction-template-981xj?file=/index.js

**Comment by afc163** [comment]
Or you can try `form.getFieldsValue(true)` to get all preserved values: https://codesandbox.io/s/antd-reproduction-template-fj1my?file=/index.js
