### ISSUE TITLE
Tooltip does not follow the position of fixed elements on scroll

### ISSUE THREAD

**Issue by micnic** [ant-design/ant-design#25117]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/micnic/pen/XWXpaGv](https://codepen.io/micnic/pen/XWXpaGv)

### Steps to reproduce
1. Put the cursor over the first text so that the tooltip appears
2. Start scrolling while keeping the cursor over the text with tooltip

### What is expected?
It is expected that the tooltip does not move while scrolling because the element has the css position fixed.

### What is actually happening?
While scrolling the tooltip follows the scroll position and is not displayed near the element that triggered the tooltip.

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | any |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-disappears-when-I-click-another-popup-component-inside-it.-How-do-I-resolve-this

related issue: #3487 #3438

**Comment by yaronya** [comment]
Hey @afc163 
I don't think this PR should be closed as:
1. The attached doc link doesn't include any reference that this is also an issue of the `Tooltip` component.
2. I've tried to fix this via the suggested solution (`getPopupContainer`) and it doesn't work.

**Comment by thangdev** [comment]
@yaronya , Hey you can add `getPopupContainer` inside Tooltip tag like this. It works for me :)
` <Tooltip getPopupContainer={triggerNode => triggerNode.parentNode} />`

**Comment by kaushik-asahi** [comment]
> @yaronya , Hey you can add `getPopupContainer` inside Tooltip tag like this. It works for me :)

But I tried getPopupContainer workaround, but i couldn't change the placement (i.e. even if i specify placement=top, it behaves like placement=bottom)

**Comment by DevRichter** [comment]
> > @yaronya , Hey you can add `getPopupContainer` inside Tooltip tag like this. It works for me :)
> 
> I tried getPopupContainer workaround, but i couldn't change the placement (i.e. even if i specify placement=top, it behaves like placement=bottom). But it does fix the popup moving along the scroll issue.

you can add a relative position to the .ant-tooltip-inner and move it with the left right top bottom props wherever you want to it be :)
