### ISSUE TITLE
可否增加复杂的条件查询

### ISSUE THREAD

**Issue by hardyfan** [ant-design/ant-design#25118]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这个功能可以将多个条件进行and和or的复杂组合条件的查询。

### What does the proposed API look like?
类似与kendoUI for react的功能。请参考！

**Comment by yoyo837** [comment]
你在说哪个组件？form？

**Comment by afc163** [comment]
表意不明，closing。
