### ISSUE TITLE
DatePicker 在使用Form.create方法自动创建onChange之后，“此刻”按钮失效

### ISSUE THREAD

**Issue by cagen** [ant-design/ant-design#2511]
当 DatePicker 通过 `this.props.form.getFieldProps` 生成onChange方法之后，如果打开showTime属性，则在使用日历中的 "此刻" 按钮，无法选中当前时间。去掉showTime属性，"今日"按钮是正常的。

- antd 版本: 1.6.5
- 浏览器及其版本: Chrome 51.0.2704.84

#### 可重现的在线演示
http://codepen.io/anon/pen/zBaGqP?editors=001

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2467

**Comment by cagen** [comment]
抱歉，失误了。一开始只搜索到了2399那个问题，以为不一样就提了
