### ISSUE TITLE
Ability to make Table Summary Fixed Row like Table Header

### ISSUE THREAD

**Issue by ralppppy** [ant-design/ant-design#25116]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have really long table data and somehow I need to calculate the data per row so I want to use the summary prop of Table. But I don't want a user to scroll down to the bottom just to see the summary, I want them to see it constantly even though they are scrolling up and down

### What does the proposed API look like?
Maybe an additional prop for
```
 <Table.Summary.Row fixedRow={true}>
    ...
</Table.Summary.Row>
```
or
```
 <Table.Summary.Row.Fixed>
    ...
</Table.Summary.Row.Fixed>
```

**Comment by afc163** [comment]
I prefer `fixed`

```
<Table.Summary.Row fixed>
    ...
</Table.Summary.Row>
```

**Comment by nemo02622** [comment]
any progress on this issue？

**Comment by alexchen1875** [comment]
> I prefer `fixed`
> 
> ```
> <Table.Summary.Row fixed>
>     ...
> </Table.Summary.Row>
> ```

what about  postion(top/bottom) ?  😃 


```
<Table.Summary.Row fixed postion='top/bottom'>    ...
</Table.Summary.Row>
```

**Comment by alexchen1875** [comment]
这个可以合并了么,都已经很久很久很久很久了,产品都要跳起来打我膝盖了

**Comment by SamWeichangyue** [comment]
any progress on this issue？

**Comment by declan94** [comment]
This feature has NOT been released?

**Comment by declan94** [comment]
> This feature has NOT been released?

Oh! My fault, released in `rc-table`, but not in the newest `antd` release
