### ISSUE TITLE
ant-Input Different from the input

### ISSUE THREAD

**Issue by Linbubin** [ant-design/ant-design#25112]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/input-ref-selection-tysp9?file=/index.js)

### Steps to reproduce
move cursor,and type value, observe the differences between the two input

### What is expected?
input and antd-Input cursor keep in place

### What is actually happening?
antd-input cursor to the back of content

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome 83.0.4103.106 |

---
I need to convert value to uppercase when I input it, but it will lead to the loss of cursor, so I modified it with selection.

**Comment by afc163** [comment]
Try this way: https://codesandbox.io/s/input-ref-selection-tysp9?file=/index.js

**Comment by Linbubin** [comment]
@afc163  
The code in the link is the same as my demo. Can I give a link again? Or paste the code directly.    
thanks!

**Comment by afc163** [comment]
Sorry: https://codesandbox.io/s/input-ref-selection-ogir7?file=/index.js
