### ISSUE TITLE
Input type=“number” 时，输入框可以输入字母e 

### ISSUE THREAD

**Issue by miaomiaoG** [ant-design/ant-design#25114]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/miaomiaog/pen/mdVRmOX?editable=true&editors=0010](https://codepen.io/miaomiaog/pen/mdVRmOX?editable=true&editors=0010)

### Steps to reproduce
代码：
<Input type="number" suffix="米" />

### What is expected?
只允许输入数字

### What is actually happening?
字母 e 还是可以被输入并且没有报错

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.12.0 |
| System | macos 10.15.4 |
| Browser | chrome  83.0.4103.106（正式版本）  |

**Comment by miaomiaoG** [comment]
![image](https://user-images.githubusercontent.com/29765893/85104482-480f5380-b23b-11ea-885a-e5dd9f5a34f2.png)

**Comment by afc163** [comment]
`<Input type="number" />` 和原生的 `<input type="number" />` 交互是一致的，我们没做其他特殊处理。
