### ISSUE TITLE
Drawer component set with mask={false} doesn't work with height attribute set via string

### ISSUE THREAD

**Issue by shifraHolzer** [ant-design/ant-design#25123]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-shadow-jvp0m?file=/index.js)

### Steps to reproduce
When the bottom Drawer component is rendered with `mask` attribute set to false, and `height` attribute set to a string value, it will not limit the height to 80, but rather fill the entire screen.
 ```
<Drawer placement="bottom" visible mask={false} height="80" key="key">
    <p>Some contents...</p>
</Drawer>
```

### What is expected?
Drawer height should be limited to the value set in the height attribute

### What is actually happening?
The drawer expands over the entire screen.

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.3.1 |
| System | mac |
| Browser | chrome |

---
This functionality works as expected when the `height` attribute is set as a number, or `mask` is set to `true`.

**Comment by afc163** [comment]
```diff
- height="80"
+ height="80px"
```
