### ISSUE TITLE
当Menu.SubMenu下面没有Menu.Item的时候，怎么去掉SubMenu右边的小箭头

### ISSUE THREAD

**Issue by peterchenhdu** [ant-design/ant-design#2512]
#### 本地环境
- antd 版本: antd v1.6.4
- 操作系统及其版本：Win7
- 浏览器及其版本: Firefox47.0

#### 实际上的结果：没有子菜单的时候，仍然显示下拉小箭头

[http://files.cnblogs.com/files/chenpi/img.7z](url)

如上图，红色圈出的部分不应该显示，或者说 有没有选项可以去掉~

**Comment by RaoHai** [comment]
传图可以直接把图拖到 github 的输入框里的……

**Comment by peterchenhdu** [comment]
@RaoHai 试了一下，传不上去，可能跟公司网络有关。。。

**Comment by benjycui** [comment]
这也是个交互上要考虑的问题，就是对于没有子菜单的 `SubMenu` 应该怎么处理。

* 显示出来，但 `disabled`。
* 直接不显示。

**Comment by Chinglik** [comment]
@peterchenhdu  你说的对，没有子菜单的时候，下拉小箭头确实不应该有。这个我们工程师会尽快处理的。谢谢你的反馈哈~~

下拉箭头 disable 的场景目前暂时没有遇到过，暂不考虑哈

ps.同学你的图片卡不开哦~

**Comment by pasturn** [comment]
@benjycui 这个问题我们项目也遇到了，导航权限管理的时候，有些人是没有`SubMenu`下面的权限的，之前试了靠判断是否渲染控制会报错，产品经理的想法是直接隐藏掉。所以希望能提供一个隐藏的api，类似`display:none`之类的，在样式上做隐藏就可以

**Comment by benjycui** [comment]
antd 和 rc-menu 都需要修改。

**Comment by benjycui** [comment]
@peterchenhdu @Chinglik  想了下，`Menu.SubMenu` 下面没有 `Menu.Item` 时，如果把 `>` 去掉，会很诡异，因为这样在用户看来就是一个普通的 `Menu.Item` 了，而点击却没有任何反应，还不如直接隐藏或者 disabled。

@pasturn `SubMenu[className]` 是支持的，自行判断是否有 children 再加上相应的 `className` 即可
