### ISSUE TITLE
Junk characters on << and >> buttons on pagination

### ISSUE THREAD

**Issue by vigyanhoon** [ant-design/ant-design#25128]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/vigyanhoon/the-list](https://github.com/vigyanhoon/the-list)

### Steps to reproduce
Pull the repo.
Do npm install
Do npm run build
Run html from dist folder

### What is expected?
<< and >> buttons on paginations should not show junk characters

### What is actually happening?
You will see junk characters in >> and << buttons on pagination. If I hover over these buttons, it displays properly.

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 83 |

![image](https://user-images.githubusercontent.com/8503526/85188611-b6005d00-b2c5-11ea-9f53-2b554a16edd1.png)

**Comment by fireairforce** [comment]
Can you provide a online code like codesandbox etc?

**Comment by vigyanhoon** [comment]
Wonder why it was closed despite providing the repo.

However I came to know of the solution, which was to add this webpack config:

'new TerserPlugin({
  terserOptions: { output: { ascii_only: true } }
}),'
