### ISSUE TITLE
[Form.Item] regex rule not working with simple input

### ISSUE THREAD

**Issue by HadiSDev** [ant-design/ant-design#25126]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-typescript-form-regex-validator-5pygy)

### Steps to reproduce
I want to check if the entered value matches the entered regex. Try to enter a number first. In the field

### What is expected?
Entering a number should fail
Accepted values e.g:
"123Hello",
"Hee"

### What is actually happening?
The regex rule is not being validated

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | React-typescript |
| System | Windows 10 Pro |
| Browser | Edge |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-typescript-form-regex-validator-yfhii

**Comment by HadiSDev** [comment]
Thank you @afc163 :)
