### ISSUE TITLE
horizontal scroll appear even when no need to scroll

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#25124]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7tksr?file=/index.js)

### Steps to reproduce
open link above

### What is expected?
horizontal scroll bar should appear only when we need to scroll

### What is actually happening?
horizontal scroll bar appear also when we don't need to scroll

![image](https://user-images.githubusercontent.com/42112796/85149114-97fd1300-b259-11ea-934a-2f61805901ab.png)

I don't know if it is wrong behavior, but I don't like it because it looks confusing, and taking extra space 
| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome 83 |

**Comment by HullQin** [comment]
有个临时的解决方案：
```css
.ant-table-content {
  overflow-x: auto!important;
}
```
但还是希望antd能默认解决这个问题，从三个月前就开始关注这个小需求了，好像到现在还没解决
