### ISSUE TITLE
rangepicker 建议参考 airbnb datepicker 交互

### ISSUE THREAD

**Issue by hellosean1025** [ant-design/ant-design#25120]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
升级了 ant4 后，rangepicker 在已选时间的情况下，每次选择会关闭筛选框

### What does the proposed API look like?
可参考： http://airbnb.io/react-dates/?path=/story/daterangepicker-drp--default
期望点两次才会关闭

**Comment by afc163** [comment]
react-dates 在两个都有值的情况下：

1. 选结束时间直接关闭浮层，完成选择。
2. 选开始时间会保持浮层，需要再点结束时间，这样和初始化的习惯保持一致。

我们也可以按这个来优化，正好能解决一部分目前业务遇到的旧版交互习惯的反馈。@zombieJ

**Comment by zombieJ** [comment]
嗯，点开始后选择点击外面关闭。可以

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/24750

**Comment by hellosean1025** [comment]
@zombieJ 这个交互的改进大概什么时间能支持?

**Comment by hellosean1025** [comment]
简单优化了一下：
示例：https://codesandbox.io/s/intelligent-mendel-pk2n4?file=/index.js

原理：修改了 rc-picker 部分逻辑
https://github.com/hellosean1025/picker

**Comment by afc163** [comment]
fixed in https://github.com/react-component/picker/pull/89 and https://github.com/ant-design/ant-design/pull/25135
