### ISSUE TITLE
Dayjs Datepicker with Spanish Locale Now Working

### ISSUE THREAD

**Issue by danilockthar** [ant-design/ant-design#25134]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wrong-locale-7f192?file=/index.tsx)

### Steps to reproduce
Change the Locale version of the codesandbox rep to es-es and run. It doesnt work. 

### What is expected?
Im expecting the datepicket translate the dates to spanish version

### What is actually happening?
Not recognizing es-Es or es_ES version of dayjs  locale

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | Next JS |
| System | Windows 10 |
| Browser | Chrome |

---
If you could provide an example with next js additional to the locale dayjs spanish would be great!

**Comment by afc163** [comment]
It works: https://codesandbox.io/s/wrong-locale-n7fyy?file=/index.tsx
