### ISSUE TITLE
Anchor组件加了getContainer属性，鼠标滚动页面时，锚点导航没有变化

### ISSUE THREAD

**Issue by vivianus-chan** [ant-design/ant-design#25130]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/vivianus/pen/RwrKdVv?editors=0110](https://codepen.io/vivianus/pen/RwrKdVv?editors=0110)

### Steps to reproduce
Anchor示例加getContainer={() => document.querySelector('#aaaa')}

### What is expected?
在编辑器编译通过，在codepen能正常显示

### What is actually happening?
1、在codepen运行此代码，鼠标滚动页面时，锚点导航没有变化；   
2、在vscode运行此代码，编译报错：
没有与此调用匹配的重载。
  第 1 个重载(共 2 个)，“(props: Readonly<AnchorProps>): Anchor”，出现以下错误。
    不能将类型“() => Element | null”分配给类型“() => AnchorContainer”。
      不能将类型“Element | null”分配给类型“AnchorContainer”。
        不能将类型“null”分配给类型“AnchorContainer”。
  第 2 个重载(共 2 个)，“(props: AnchorProps, context?: any): Anchor”，出现以下错误。
    不能将类型“() => Element | null”分配给类型“() => AnchorContainer”。ts(2769)
Anchor.d.ts(14, 5): 所需类型来自属性 "getContainer"，在此处的 "IntrinsicAttributes & IntrinsicClassAttributes<Anchor> & Pick<Readonly<AnchorProps> & Readonly<...>, "style" | ... 9 more ... | "targetOffset"> & Partial<...> & Partial<...>" 类型上声明该属性
Anchor.d.ts(14, 5): 所需类型来自属性 "getContainer"，在此处的 "IntrinsicAttributes & IntrinsicClassAttributes<Anchor> & Pick<Readonly<AnchorProps> & Readonly<...>, "style" | ... 9 more ... | "targetOffset"> & Partial<...> & Partial<...>" 类型上声明该属性

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | ^16.13.1 |
| System | win10 |
| Browser | google 83.0.4103.106 |

**Comment by zgoby** [comment]
你在codepen里写的内容不是bug，getContainer指定滚动监听的dom，无值监听在window，以下正确使用方式
https://codepen.io/zgoby/pen/QWymGyY?editors=0110
