### ISSUE TITLE
Select crashes if rendered inside another component.

### ISSUE THREAD

**Issue by jackowiak** [ant-design/ant-design#25131]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-waqq8e](https://stackblitz.com/edit/react-waqq8e)

### Steps to reproduce
1) Click on Menu button on the right side of the header
2) Now AntD's Select is rendered
3) Choose any Option.

### What is expected?
1) onChange event will be fired.
2) Option will be selected.

### What is actually happening?
1) onChange is not fired
2) Select that was rendered inside header is closed now.
3) Out of nowhere, the same Select immediately appears in the corner of an app. After selecting any value from new Select, onChange is fired and Option is selected.

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | Windows 10 Pro |
| Browser | Chrome, Firefox |

---
I don't know why the Select behaves like that. I've tried to add `getPopupContainer={t => t.parentNode}` props on Select, it works a bit better (onChange is fired correctly and there's no any surprise like out-of-nowhere Select rendered in the corner of an app). But it makes Options a bit invisible.

**Comment by afc163** [comment]
I believe you should ask for solution in https://www.ag-grid.com/
