### ISSUE TITLE
The background of Button in Modal confirm dialog is not correct when open

### ISSUE THREAD

**Issue by Babyfaceqian** [ant-design/ant-design#25149]
- [✓] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/modal/](https://3x.ant.design/components/modal/)

### Steps to reproduce
The issue is able to be reproduced on ant-design website.
1. Click Confirm Button, check the background color of the 'OK' button in the dialog. The color seems for hover state.
2. After clicked somewhere, the background of the 'OK' button will be changed to the basic color.
3. Same issue happens in danger button.

### What is expected?
The background color of 'OK' button should be the basic color not hover color when confirm dialog is opened.

### What is actually happening?
The background color of 'OK' button has hover color when confirm dialog is opened.

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.1 |
| System | mac os 10.15.4 |
| Browser | Chrome 83.0.4103.97 |

---
It didn't happen in version 3.11.2

**Comment by afc163** [comment]
#17193
https://github.com/ant-design/ant-design/issues/16857#issuecomment-496806000
https://github.com/ant-design/ant-design/issues/16297#issuecomment-486567040
