### ISSUE TITLE
InputNumber在focus和blur时都会触发onChagne ?

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2514]
#### 本地环境

- antd 版本:  1.6.5
- 操作系统及其版本：ubuntu 16.04
- 浏览器及其版本: chrome

#### 你做了什么？

```js

          <InputNumber 
            min={0}
            defaultValue={0} 
            onChange={value => this.handleChange({xxx: value})} 
         />

```

#### 你期待的结果是：

只有值真的改变了，才触发onChange

#### 实际上的结果：

值没变，但在focus和blur时都会触发onChagne

#### 可重现的在线演示

官网可重现

**Comment by codering** [comment]
或者把event回传给我，我自己判断下

**Comment by afc163** [comment]
fixed in rc-input-number@2.5.15

https://github.com/react-component/input-number/commit/2a78189254173587a757126cdac115b50c986a31

**Comment by L-x-C** [comment]
@afc163 这里还是有个bug，当InputNumber里面没有值时，每次blur还是会触发onChange,有值就不会

![1](https://cloud.githubusercontent.com/assets/4329120/24740915/1874e036-1ad6-11e7-99d7-fa78baec3fdc.gif)

**Comment by afc163** [comment]
@L-x-C You can create a new issue for that.
