### ISSUE TITLE
Warning: [antd: Form.Item] `children` is array of render props cannot have `name`.

### ISSUE THREAD

**Issue by zanjs** [ant-design/ant-design#25150]
```
<Form.Item
        name="agreement"
        valuePropName="checked"
        rules={[
          { validator:(_, value) => value ? Promise.resolve() : Promise.reject('Should accept agreement') },
        ]}
        {...tailFormItemLayout}
      >
        <Checkbox>
          I have read the <a href="">agreement</a>
        </Checkbox>
      </Form.Item>
```

**Comment by xyy7260** [comment]
@zanjs  请问你的这个问题解决了没

**Comment by samkahchiin** [comment]
@xyy7260 I guess this is related to this. Check the documentations.
https://ant.design/components/form/#components-form-demo-complex-form-control

**Comment by pavan-shipmnts** [comment]
I'm using a rich text editor with antd form. Would the custom control be two way binded to the Antd form?

**Comment by SulePostar** [comment]
Hello XXX, your issue has been closed because it does not conform to our issue requirements. 
It seems like a good answer for any issue you have no idea how to solve ???

**Comment by MrRobz** [comment]
My undesanding
While using `<Form.Item` it internally passes some props like value, onChange to the immediate child. But this won't happen and fails if there are multiple children.

Valid
```
<Form.Item>
 <Input>
</Form.Item>
```

Not Valid
```
<Form.Item>
 <Input>
 <Input>
</Form.Item>
```

The 2nd case cases this error in console.

**Comment by dyarfi** [comment]
Use `<Form.Item extra={<div>add extra tags in the bottom of the field below warning message</div>}>` if you want to add some stuff.
