### ISSUE TITLE
Tabs 在ie11下无法关闭

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design#25153]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/#components-tabs-demo-card-top](https://ant.design/components/tabs-cn/#components-tabs-demo-card-top)

### Steps to reproduce
https://ant.design/components/tabs-cn/#components-tabs-demo-card-top

### What is expected?
在ie下 能正常关闭

### What is actually happening?
无法关闭 onRemove不触发 触发了onChange

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | window |
| Browser | ie11 |

---
这个问题挺急的 能不能快速发个小版本解决下

**Comment by YinRenjie1993** [comment]
@afc163 正常模式下，直接在ie11下打开官网的tabs演示的新增和关闭页  点击关闭图标

**Comment by afc163** [comment]
你本地测试过么，官网本身不支持 IE11.

**Comment by YinRenjie1993** [comment]
https://codesandbox.io/s/tni88

**Comment by afc163** [comment]
codesandbox 本身也是不支持 IE11 的，你最好提供一个你本地测试过在 IE11 下有问题的最小化的 github repo。

**Comment by YinRenjie1993** [comment]
http://47.96.13.104:5000/ 这个是我部署的一个 在外网的  可以直接用ie11打开
这个是这个部署的代码 代码直接在官网复制的 没有改过
https://github.com/YinRenjie1993/antd_tabs

**Comment by YinRenjie1993** [comment]
@afc163

**Comment by zombieJ** [comment]
看起来 IE11 里 Button 不支持内嵌 active 元素， @afc163 被你说中了~

**Comment by YinRenjie1993** [comment]
@afc163 今天发版本不 等着修复呢

**Comment by yoyo837** [comment]
#25242
