### ISSUE TITLE
how can i generate the component's json schema ？such generate from typescript interface ?

### ISSUE THREAD

**Issue by banama** [ant-design/ant-design#25162]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
we want to get the antd-component's meta data, such as
```
{
    "title": "alert ",
    "description": "A simple form example.",
    "type": "object",
    "properties": {
        "type": {
            "type": "string",
            "title": "type",
            "desc": " Type of Alert styles, options:`success`, `info`, `warning`, `error`",
            "default": "success"
        },
        ......
    }
}
```
that can be used by json-schema-editor. 
Do you have any good suggestions ?

**Comment by afc163** [comment]
You have to dig by yourself.
