### ISSUE TITLE
Autocomplete not always cleaned with defaultActiveFirstOption={true} 

### ISSUE THREAD

**Issue by msotnikov** [ant-design/ant-design#25161]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-v0rcv?file=/index.js)

### Steps to reproduce
Try select one option then another, then another. 

### What is expected?
The input field must clear after each selection.

### What is actually happening?
The Input field not always cleaned.

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 83.0.4103.106 |

**Comment by afc163** [comment]
Remove `backfill={true}`.
