### ISSUE TITLE
Select dynamic option creation while not using tags mode

### ISSUE THREAD

**Issue by YikSanChan** [ant-design/ant-design#25178]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It allows creating an option by simply typing without having to "typing -> click 'Add Item' -> select the item".

### What does the proposed API look like?
[react-select Creatable](https://react-select.com/creatable) provides a good example. The same feature request has been discussed in https://github.com/ant-design/ant-design/issues/7876 however the suggestion of using https://ant.design/components/select/#components-select-demo-tags does not covering all the use cases - what if users don't want to use tags mode?

**Comment by zombieJ** [comment]
Why can not use `tags` mode?  What does `not covering all the use cases` mean?

**Comment by YikSanChan** [comment]
@zombieJ Cannot use tags mode because it allows selecting multiple tags in one Select while I only want to allow one value. Also, tags mode has special styling compared to non-tags mode.

Let me know if you have more questions regarding the feature request, thank you

**Comment by zombieJ** [comment]
Use AutoComplete instead.

**Comment by YikSanChan** [comment]
@zombieJ Thx! Will give it a shot

**Comment by afc163** [comment]
Closing now, feel free to comment if you meet problem of AutoComplete.

**Comment by YikSanChan** [comment]
@zombieJ @afc163 AutoComplete works great, thanks
