### ISSUE TITLE
When using Select component, selecting an OptGroup selects all children

### ISSUE THREAD

**Issue by rchavik** [ant-design/ant-design#25176]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

Although similar to #4823, what I propose is a bit different. We don't make the `OptGroup` selectable like an `Option`, but autoselects its children.

### What problem does this feature solve?
When used with an `OptGroup` that is more than a few children, clicking on one automatically selects all children.

For example, when using this component to render an address book, we could use `OptGroup` to group addresses and when a group is selected, one can add all of them to the receiver list.

### What does the proposed API look like?
How about the following below. When autoSelectChildren prop is present, clicking on it selects all children.  If the property is not specified, we use the current behavior.

```jsx
<Select>
  <Select.OptGroup autoSelectChildren label='Work'>
    <Select.Option value='foo@example.com'>Foo</Select.Option>
    <Select.Option value='bar@example.com'>Bar</Select.Option>
  </Select.OptGroup>
  <Select.OptGroup label='Family'>
    <Select.Option value='spam@example.com'>Spam</Select.Option>
    <Select.Option value='eggs@example.com'>Eggs</Select.Option>
  </Select.OptGroup>
</Select>
```

**Comment by afc163** [comment]
You should try TreeSelect in this situation, not Select.

**Comment by rchavik** [comment]
Thanks for the pointer.

**Comment by rchavik** [comment]
> You should try TreeSelect in this situation, not Select.

@afc163 i have just tried using `TreeSelect`.  It works as expected, but I couldn't find a way to dynamically add new entry. With `Select`, I achieved this by using `mode='tags`'.

Is there similar functionality for `TreeSelect`?
