### ISSUE TITLE
Rangepicker for Timepicker does not work with dayjs

### ISSUE THREAD

**Issue by amar-sharma** [ant-design/ant-design#25177]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-voice-jkxrh?file=/src/App.tsx)

### Steps to reproduce
* Follow [Replace MomentJS](https://ant.design/docs/react/replace-moment#DatePicker)
* try to use `RangePicker` for `TimePicker` with `const {RangePicker} = TimePicker;`

### What is expected?
RangePicker for Time is rendered

### What is actually happening?
Getting an error Property 'RangePicker' does not exist on type 'ForwardRefExoticComponent<TimePickerProps & RefAttributes<any>>'. 

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Firefox |

**Comment by FabienDeborde** [comment]
I am getting the same problem here.
I defined the DatePicker like this
```js
import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs'
import generatePicker from 'antd/es/date-picker/generatePicker'
import 'antd/es/date-picker/style/css'

const DatePicker = generatePicker(dayjsGenerateConfig)

export default DatePicker
```

The TimePicker like this:
```js
import React from 'react'
import DatePicker from '../DatePicker/CustomPicker.jsx'

const TimePicker = React.forwardRef((props, ref) => {
  return <DatePicker {...props} picker="time" mode={undefined} ref={ref} />
})

TimePicker.displayName = 'TimePicker'

export default TimePicker
```
But when I import the TimePicker component and try to get the RangePicker like I did for the DatePicker ( `const CustomTimeRangePicker = TimePicker.RangePicker` ), it seems there is no RangePicker in this TimePicker instance.

Is there an extra step to do to make this work with TimePickers?

I used to use the Webpack plugin but we switched to Rollup and now I'm stuck on this problem...
If anyone has any insight on this issue, it would help me a lot!

**Comment by FabienDeborde** [comment]
As usual it's after posting an issue that I get how to solve my problem...

I fixed it by dropping the use of a custom TimePicker, instead I use the custom DatePicker, extract the RangePicker (`const CustomTimeRangePicker = DatePicker.RangePicker`), and I pass the picker & mode props to this CustomTimeRangePicker component. Something like this:
```js
<CustomTimeRangePicker
          className="customTimePicker"
          dropdownClassName="customDropdown"
          name="myRangePicker"
          autocomplete="off"
          format={SERVER_TIME_FORMAT}
          value={[start, end]}
          onChange={handleInputChange}
          onBlur={handleBlur}
          picker="time"
          mode={undefined}
        />
```

Maybe it was obvious for some people, but took me a while to figure this out.
Hope it can help someone along the way!
