### ISSUE TITLE
antd upload组件上传过程浏览器卡死

### ISSUE THREAD

**Issue by sujiangyin** [ant-design/ant-design#25173]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd upload组件上传过程浏览器卡死

### What does the proposed API look like?
antd upload组件上传过程浏览器卡死，很长时间才能看到上传成功回显图片，网上查说是要把图片转base64所以要很长时间，请问有没有优化方案？目前耗时非常大

**Comment by afc163** [comment]
You can try customize Upload previewFile to replace default preview logic: https://github.com/ant-design/ant-design/pull/15984/files

ref #15885

**Comment by sujiangyin** [comment]
> You can try customize Upload previewFile to replace default preview logic: https://github.com/ant-design/ant-design/pull/15984/files
> 
> ref #15885

i read the code of this address,there is writed like that:
`
previewFile(file.originFileObj).then((previewDataUrl: string) => {
          // Need append '' to avoid dead loop
          file.thumbUrl = previewDataUrl || '';
          this.forceUpdate();
        });
`
,i am not understant how to use the props  `previewFile`,how about the usage of this api?

**Comment by sujiangyin** [comment]
> You can try customize Upload previewFile to replace default preview logic: https://github.com/ant-design/ant-design/pull/15984/files
> 
> ref #15885

this is my codes
`<Upload
                    {...this.uploadConfig}
                    accept={this.accept}
                    fileList={ fileList }
                    multiple={ multiple }
                    previewFile={this.previewFile}
                    beforeUpload = { this.beforeUpload }
                    onChange={ this.handleChangeUpload }
                  >
                    {fileList.length >= this.maxUpload ? null : 
                        <div className="upload-card-btn">
                            <div className="upload-btn-wrapper">
                                <div className="upload-btn">
                                <svg className="icon" aria-hidden="true">
                                    <use xlinkHref="#icon-upload"></use>
                                </svg>
                                <div className="ant-upload-text">{this.UploadBtnTitle}</div>
                                </div>
                            </div>
                            {/* 按钮底部文案，用于说明上传格式要求等 */}
                            {bottomText && 
                                <span className="upload-text">
                                    {bottomText}
                                </span>
                            }
                        </div>
                    }
                  </Upload>`
`previewFile(file, (previewDataUrl)=>{
    file.thumbUrl = previewDataUrl;
});`

the previewFile function may be wrong,what should i do?

**Comment by sujiangyin** [comment]
> You can try customize Upload previewFile to replace default preview logic: https://github.com/ant-design/ant-design/pull/15984/files
> 
> ref #15885

now my code is

`previewFile = ((file)=>{
    return new Promise((resolve) => {
    const reader = new FileReader();
    reader.readAsDataURL(file);
    reader.onload = function (e) {
        const dataUrl = e.target.result;
        resolve(dataUrl)
    }
})
}
)`
 above,this `dataUrl` is base64 img,how to replace the fileList to preview??

my all code is

`
<Form.Item label={this.label}
                name={fieldName}
                rules={this.rules}
                initialValue={initialValue}
            >
                <div  className="upload-outer-box">
                      {fileList.map((item,index) => (
                          <div className="upload-pic-box" key={index}>
                            <span className="upload-close" onClick={this.removeUpload.bind(this,index)}>
                                <svg className="icon" aria-hidden="true">
                                <use xlinkHref="#icon-close"></use>
                                </svg>
                            </span>
                            {/* 控制图片和其他文件上传后回显 */}
                            {this.type =='img' ? <img src={item.thumbUrl||item.long_url} alt=""/> :
                                <span>
                                    <span className="upload-logo">
                                    <svg className="icon" aria-hidden="true">
                                    <use xlinkHref="#icon-pdf"></use>
                                    </svg>
                                </span>
                                <span className="upload-name">{item.name}</span>
                                </span>
                            }
                        </div>
                      ))}
                  <Upload
                    {...this.uploadConfig}
                    accept={this.accept}
                    fileList={ fileList }
                    multiple={ multiple }
                    previewFile={this.previewFile}
                    beforeUpload = { this.beforeUpload }
                    onChange={ this.handleChangeUpload }
                  >
                    {fileList.length >= this.maxUpload ? null : 
                        <div className="upload-card-btn">
                            <div className="upload-btn-wrapper">
                                <div className="upload-btn">
                                <svg className="icon" aria-hidden="true">
                                    <use xlinkHref="#icon-upload"></use>
                                </svg>
                                <div className="ant-upload-text">{this.UploadBtnTitle}</div>
                                </div>
                            </div>
                            {/* 按钮底部文案，用于说明上传格式要求等 */}
                            {bottomText && 
                                <span className="upload-text">
                                    {bottomText}
                                </span>
                            }
                        </div>
                    }
                  </Upload>
                  </div>
              </Form.Item>
`

**Comment by sujiangyin** [comment]
> You can try customize Upload previewFile to replace default preview logic: https://github.com/ant-design/ant-design/pull/15984/files
> 
> ref #15885

i have try

`previewFile = ((file)=>{
    let _this = this;
    return new Promise((resolve) => {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = function (e) {
            const dataUrl = e.target.result;
            let previewList = _this.state.previewList;
            previewList.push({
                thumbUrl:dataUrl,
                name: file.name
            })
            _this.setState({
                previewList: previewList
            })
            resolve(dataUrl)
        }
    })
    }
)
`

回显部分的代码

`{previewList.map((item,index) => (
                            <div className="upload-pic-box" key={index}>
                                <span className="upload-close" onClick={this.removeUpload.bind(this,index)}>
                                    <svg className="icon" aria-hidden="true">
                                    <use xlinkHref="#icon-close"></use>
                                    </svg>
                                </span>
                                {/* 控制图片和其他文件上传后回显 */}
                                {this.type =='img' ? <img src={item.thumbUrl||item.long_url} alt=""/> :
                                    <span>
                                        <span className="upload-logo">
                                        <svg className="icon" aria-hidden="true">
                                        <use xlinkHref="#icon-pdf"></use>
                                        </svg>
                                    </span>
                                    <span className="upload-name">{item.name}</span>
                                    </span>
                                }
                            </div>
                      ))}`

但是上传前的浏览器还是卡比较久，速度没有改善，请问还可以怎么做

**Comment by afc163** [comment]
@sujiangyin 可以试试升级到最新版本，现在的实现没有用 FileReader 了。

**Comment by sujiangyin** [comment]
好的。thx…



---原始邮件---
发件人: "偏右"<notifications@github.com&gt;
发送时间: 2020年7月8日(周三) 下午5:03
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"suosuo"<1605324281@qq.com&gt;;
主题: Re: [ant-design/ant-design] antd upload组件上传过程浏览器卡死 (#25173)




 
@sujiangyin 可以试试升级到最新版本，现在的实现没有用 FileReader 了。
