### ISSUE TITLE
进度条 strokeLinecap='square' 属性无效

### ISSUE THREAD

**Issue by Q-Qplus1s** [ant-design/ant-design#25181]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/progress-cn/#API](https://ant.design/components/progress-cn/#API)

### Steps to reproduce
```tsx
import React, { FC } from 'react';
import { Progress } from 'antd';

interface Props {
  totalGB?: number;
  usedMB?: number;
}

const Index: FC<Props> = (props)  => {

  const percent = props.usedMB && props.totalGB ?
    (props.usedMB / (10.24*props.totalGB)) : 0;

  return (
    <div className='flc fl1 p16'>
      <div className='fc-df f13'>
        共 {props.totalGB} GB 已用 {props.usedMB} MB
      </div>
      <div className='flr fl1'>
        <Progress
          showInfo={false}
          percent={Number(percent.toFixed(2))}
          strokeLinecap='square'
        />
      </div>
    </div>
  );
};

Index.defaultProps = {
  totalGB: 15,
  usedMB: 535.4
};

export default Index;


```

### What is expected?
进度条边缘应该是直角的，但是显示效果为圆角

### What is actually happening?
显示进度条圆角

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.0 |
| System | Centos 7 |
| Browser | Chrome Version 83.0.4103.97 (Official Build) (64-bit) |

---
直接使用上述代码复现

![Screenshot from 2020-06-24 02-18-34](https://user-images.githubusercontent.com/50064165/85441689-f6135880-b5c1-11ea-9df6-68c724bd2558.png)

**Comment by afc163** [comment]
https://ant.design/components/progress-cn/#components-progress-demo-linecap

这个应该是预期的，右侧进度边缘会变成方形的，你可以和 https://github.com/ant-design/ant-design/pull/11547 的作者讨论一下。
