### ISSUE TITLE
Select的dropdownMatchSelectWidth在给Select设置了style宽度的时候无效

### ISSUE THREAD

**Issue by areyouse7en** [ant-design/ant-design#25180]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-with-search-field-ant-design-demo-sybvx?file=/index.js)

### Steps to reproduce
给Select设置style={{width:'100%'}}之后，下拉菜单的宽度就和输入框一样宽了

### What is expected?
下拉菜单的宽度和dropdownMatchSelectWidth设置的一样

### What is actually happening?
下拉菜单的宽度和设置的不一样，无效

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.12.0 |
| System | Windows |
| Browser | Chrome 80.0.3987.122 |

---
antd@4.0.4的时候还是好的

**Comment by zombieJ** [comment]
It's by design. We should update doc for this.

**Comment by xrkffgg** [comment]
你可以加上 `dropdownStyle={{ minWidth: 100 }}`

**Comment by xrkffgg** [comment]
`dropdownMatchSelectWidth` 和 `dropdownStyle` 一起使用

**Comment by areyouse7en** [comment]
ok
`dropdownMatchSelectWidth={200}
          dropdownStyle={{ minWidth: 200 }}`
起作用了
