### ISSUE TITLE
upload文档描述中method无法正常使用

### ISSUE THREAD

**Issue by 7King** [ant-design/ant-design#25187]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload/#API](https://ant.design/components/upload/#API)

### Steps to reproduce
使用默认上传方式之外的method无法生效  如method={'PUT'} 上传方式仍为POST

### What is expected?
浏览器发送请求为method中的请求方式

### What is actually happening?
请求方式无法更改，只能为POST

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.9.0 |
| System | windows10 |
| Browser | 谷歌浏览器版本 83.0.4103.97（正式版本） （64 位） |

**Comment by afc163** [comment]
实测有效：https://codesandbox.io/s/exciting-rgb-9pi75?file=/index.js
