### ISSUE TITLE
为什么只对外提供点击Menu.Item的事件处理，没有提供点击SubMenu的事件处理

### ISSUE THREAD

**Issue by peterchenhdu** [ant-design/ant-design#2519]
本地环境

    antd 版本: antd v1.6.4
    操作系统及其版本：Win7
    浏览器及其版本: Firefox47.0

你期待的结果是：对外提供点击Menu.Item的事件处理

**Comment by benjycui** [comment]
因为你没看文档 http://ant.design/components/menu#Menu.SubMenu-props

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
