### ISSUE TITLE
tabs组件内容太多时，左右滑动点击了最后一项后，回不到第一项，上下滑动时，只能通过鼠标滚动上下滚动，如果页面还有滚动条时，不方便操作

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#25195]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quizzical-austin-f82go?file=/index.js)

### Steps to reproduce
当TabPane项数目达到可滚动时即可复现

### What is expected?
tabs组件
1. 左右滑动，点击了最后一项后，可以通过箭头点击回到前一项和后一项
2. 上下滑动时，可以通过箭头点击回到前一项和后一项

![image](https://user-images.githubusercontent.com/8147202/85511007-b765b880-b62a-11ea-8fc1-c80b21b09354.png)

![image](https://user-images.githubusercontent.com/8147202/85511045-c187b700-b62a-11ea-8ba7-0988c0f240a0.png)

### What is actually happening?
tabs组件
1. 左右滑动，点击了最后一项后，没法向左或向右移动
2. 上下滑动时，只能通过鼠标滚动上下滚动，无法通过点击操作向上或向下滚动

![image](https://user-images.githubusercontent.com/8147202/85510956-a9179c80-b62a-11ea-8a86-b32080849ce8.png)

![image](https://user-images.githubusercontent.com/8147202/85510891-956c3600-b62a-11ea-8064-a5f9c3c349ab.png)

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.12.0 |
| System | win 10 |
| Browser | Chrome 83.0.4103.61 |

**Comment by zombieJ** [comment]
新的 Tabs 设计取消了箭头，鼠标 hover 到那个 `…` 就是剩余的所有 Tabs。

**Comment by fengyun2** [comment]
> 新的 Tabs 设计取消了箭头，鼠标 hover 到那个 `…` 就是剩余的所有 Tabs。

问题是，我如何回到第一项呢？

**Comment by zombieJ** [comment]
> 鼠标 hover 到那个 `…` 就是剩余的所有 Tabs。

hover 显示下拉框，点击回到第一项

**Comment by laixstx** [comment]
**1、垂直模式的时候，`...` 不见了。**
![image](https://user-images.githubusercontent.com/10735940/88892848-0f21c000-d278-11ea-8e75-756aac196578.png)

**2、垂直模式下，我选中的是“标签11”，但是根本没有标签选中的效果，这看着，让人一脸懵逼，实在有些搞笑...**

![image](https://user-images.githubusercontent.com/10735940/88893732-59f00780-d279-11ea-8edf-016cea48c564.png)


另外，忍不住吐槽一下这个新设计，你们自己用着都不觉得变扭吗？

先不说样式变丑了，体验上更是掉了不止一个档次。
**如果页面本身就有滚动条，这种“只依靠鼠标滚动来移动标签”的方式，滚着滚着页面就跑了，这操作体验上，简直难受得不能再让人抓狂了...**

这个对 Tabs         ########组件的更新，实在有些多余，越更新越难用...

**Comment by zombieJ** [comment]
@laixstx ，你的系统和游览器是什么版本的？ 我看一下

**Comment by laixstx** [comment]
> @laixstx ，你的系统和游览器是什么版本的？ 我看一下
系统：win10 家庭版 64位
浏览器：qq浏览器，10.5.2
![image](https://user-images.githubusercontent.com/10735940/88991575-996b3200-d313-11ea-915b-82cbe1bf226d.png)

**Comment by zombieJ** [comment]
@laixstx，你还有其他游览器没？试下也是相同的结果吗？谢谢~

**Comment by laixstx** [comment]
@zombieJ  Chrome 浏览器的效果是正常的：
![image](https://user-images.githubusercontent.com/10735940/89010225-bbc77480-d340-11ea-9955-eef31eb17e47.png)

**Comment by zombieJ** [comment]
QQ 游览器看来 Chrome 内核版本太旧，你看看能不能升级一下 QQ 游览器？

**Comment by xrkffgg** [comment]
竟然还有 QQ 浏览器

**Comment by afc163** [comment]
```diff
- 游览器
+ 浏览器
```

**Comment by laixstx** [comment]
> 竟然还有 QQ 浏览器

qq 用的人还是挺多的啊 - -||

**Comment by laixstx** [comment]
> QQ 游览器看来 Chrome 内核版本太旧，你看看能不能升级一下 QQ 游览器？

更新到最新版了，然后还是不行 [手动捂脸] 
难道 QQ 浏览器不配拥有 antd

![image](https://user-images.githubusercontent.com/10735940/89027509-30a8a780-d35d-11ea-931c-7f665a1d2e91.png)

**Comment by zombieJ** [comment]
看起来是 QQ 游览器锁定的 Chrome 内核版本是 bug 版本，只能发邮件让它们去更新一下了。

**Comment by keminu** [comment]
为啥不保留原来的左右滑动设计呢？加个选项就行
