### ISSUE TITLE
是否有在create react app通过引用不同的css文件，或者全局配置来修改颜色主题的方法？

### ISSUE THREAD

**Issue by pxim** [ant-design/ant-design#25193]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1.我的create react app因为项目需求，其webpack配置已经魔改了很多，和原本的相差很大，我看官网的修改主题的方法要在CRA的webpack配置里修改，我感觉太麻烦了，不太想继续修改webpack配置文件，
①有没有通过把 import 'antd/dist/antd.css'; 改成引入其他css的方式，修改主题？
②或者有没有 类似
 css.global('html, body',  {
    padding: 0,
    backgroundColor: '#000000',
    // background: this.props.pageStore.nWebsiteBg || '#ffffff',
    margin: '0px',
    overflow: 'hidden',
});
这种 方法，修改全局的主题样式？
③是否可以在使用的组件里添加个设置主题的api，类似这样？
![image](https://user-images.githubusercontent.com/5111701/85508724-3527c500-b627-11ea-8c1f-5ecb3f95cfd9.png)

### What does the proposed API look like?
简单，高效

**Comment by afc163** [comment]
You can try https://github.com/ycjcl868/theme-switcher

**Comment by pxim** [comment]
会了

`import 'antd/dist/antd.dark.css';`
