### ISSUE TITLE
table rowSelection 支持指定某一行的 checkbox 是否是 disabled

### ISSUE THREAD

**Issue by sliuqin** [ant-design/ant-design#252]
现在有一个需求，某种状态下某一行数据是不能被选中的，希望提供设置 checkbox 为 disabled 的方法。

**Comment by afc163** [comment]
有点复杂，等到下期再看看。

**Comment by afc163** [comment]
1. 支持单选。
2. 支持配置 props 。

**Comment by RaoHai** [comment]
某行默认选中、某行不能选中，如何配置为好？

**Comment by afc163** [comment]
之前试着按照实现过，感觉实现上异常麻烦（需要把 disabled 的属性剔除出 selectAll 的判断中），使用也有问题。

```js
rowSelection: {
  getCheckboxProps(value) {
    return {
      defaultValue: false,
      disabled: true
    };
  }
}
```

后来倾向于拆出来交给用户自行实现，把实现代码做到演示中。

@RaoHai 看看如何处理比较好。

**Comment by RaoHai** [comment]
https://github.com/ant-design/ant-design/pull/371

**Comment by afc163** [comment]
defaultValue 应为 defaultChecked ，我搞错了。

```js
rowSelection: {
  getCheckboxProps(value) {
    return {
      defaultChecked: false,
      disabled: true
    };
  }
}
```
