### ISSUE TITLE
Dark theme for collapsed horizontal menu

### ISSUE THREAD

**Issue by msotnikov** [ant-design/ant-design#25202]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-53elm?file=/index.js)

### Steps to reproduce
Horizontal menu with a lot of items with submenu and collapsed on narrow screen. Then hover the dots.

### What is expected?
Expanded submenu must be dark themed

### What is actually happening?
Expanded submenus has light theme. Items of sub menu has right dark theme.

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 83.0.4103.106 |

![image](https://user-images.githubusercontent.com/16710810/85527880-f2102680-b613-11ea-8cbb-288f5a6a0644.png)

**Comment by afc163** [comment]
broken by #24997
