### ISSUE TITLE
Form add typescript type ValidateErrorEntity

### ISSUE THREAD

**Issue by k0603156** [ant-design/ant-design#25209]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-williamson-h395t?file=/src/App.tsx)

### Steps to reproduce
```typescript
import React from "react";
import Form from "antd/lib/form";
import Input from "antd/lib/input";
import { Store, ValidateErrorEntity } from "antd/lib/form/interface";

const layout = {
	labelCol: { span: 8 },
	wrapperCol: { span: 16 },
};
export default function RegistForm() {
	const onFinish = (values: Store) => {
		console.log("Success:", values);
	};
	const onFinishFailed = (errorInfo: ValidateErrorEntity) => {
		console.log("Failed:", errorInfo);
	};
	return (
		<Form
			{...layout}
			name="basic"
			initialValues={{ remember: true }}
			onFinish={onFinish}
			onFinishFailed={onFinishFailed}
		>
			<Form.Item
				label="Username"
				name="username"
				rules={[
					{ required: true, message: "Please input your username!" },
				]}
			>
				<Input />
			</Form.Item>
		</Form>
	);
}

```

### What is expected?
import { ValidateErrorEntity } from "antd/lib/form/interface";

### What is actually happening?
import { ValidateErrorEntity } from "rc-field-form/lib/interface";

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | react@16.13.1 |
| System | windows10 |
| Browser | chrome |

**Comment by afc163** [comment]
I assume you had solution about it cause you closed all PRs, feel free to create PR if this is what you need. Closing now.
