### ISSUE TITLE
[Feature Request] Improve Typography copyable

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#25203]
Now we support a copy button with original text: https://codesandbox.io/s/interesting-river-vtoqf?file=/index.js

```jsx
<Paragraph copyable={{ text: 'Hello, Ant Design!' }} />
```

There is three problems to resolve:

1. Cannot customize copy icon.
2. The copy icon has extra `margin-left`.
3. There is no good way to change default `Copy` and `Copied` in Tooltip.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/507615/85527552-8c389480-b63d-11ea-97f6-16a8ef897e85.png">

The new API we are looking for should be:

```diff
<Paragraph
  copyable={{
    text: 'Hello, Ant Design!',
    onCopy: () => {},
+   icon: <Icon />,
+   tooltips: ['Copy', 'Copied'],
  }} 
/>
```

**Comment by zombieJ** [comment]
`tooltips` is no need. It's controlled by ConfigProvider `locale`.

**Comment by afc163** [comment]
It is a common need to customize tooltip for each copy button.
