### ISSUE TITLE
Menu的 icon 属性怎么传入组件呢?

### ISSUE THREAD

**Issue by xuoutput** [ant-design/ant-design#25208]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q8ccf?file=/index.js)

### Steps to reproduce

// 传入的值
```
export const menu: AppMenu = {
  title: 'MY-TS',
  items: [
    { route: '/', title: 'Home' },
    {
      route: '/users',
      title: 'Users',
      icon: UserOutlined,
      children: [
        {
          route: '/users/info',
          title: 'info'
        },
        {
          route: '/users/email',
          title: 'email'
        }
      ] },
    { route: '/about', title: 'About' },
    // 这里怎么设置啊
    { route: '/manager', title: 'Manger', icon: AppstoreOutlined }
  ]
}

// 渲染菜单
  renderMenu = (items: AppMenuItem[]): React.ReactNode => {
    return items.map((item) => {
      if (item.children) {
        return (
          <SubMenu title={item.title} key={item.route}>
            {this.renderMenu(item.children)}
          </SubMenu>
        )
      }
      return (
// 主要是这里 怎么设置 icon 属性, 让 Icon 组件显示 icon={item.icom} 肯定不行
        <Menu.Item title={item.title} key={item.route} icon={<UserOutlined/>}>
          <NavLink to={item.route}>{item.title}</NavLink>
        </Menu.Item>
      )
    })
  }
```

### What is expected?
带有图标的menu
![image](https://user-images.githubusercontent.com/16385443/85549982-16d7be80-b653-11ea-9c7e-70d195b8633b.png)

### What is actually happening?
报错, 不知道怎么传入 Icon 组件

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | macos 10.15.5 |
| Browser | chrome 83.0.4103.116 (Official Build) (64-bit) |

**Comment by yoyo837** [comment]
不就是`icon={<MyIcon />}`?

**Comment by yoyo837** [comment]
你demo里不就是有写吗？

**Comment by yoyo837** [comment]
`icon: AppstoreOutlined` 改为
`icon: <AppstoreOutlined />` 不就可以 icon={item.icon} 了吗

**Comment by xuoutput** [comment]
@yoyo837 那我在 menu 里直接这么写不对呀

```
export const menu: AppMenu = {
  title: 'MY-TS',
  items: [
    { route: '/manager', title: 'Manger', icon: AppstoreOutlined }
  ]
}

// 渲染菜单这里直接传入 icon={item.icon} 会报错, 变成传入 icon={ AppstoreOutlined} 不是 icon={ <AppstoreOutlined/>}, 但在 menu 中写  { route: '/manager', title: 'Manger', icon: <AppstoreOutlined/> } 这个也不对呀
        <Menu.Item title={item.title} key={item.route} icon={item.icon}>
          <NavLink to={item.route}>{item.title}</NavLink>
        </Menu.Item>
      
```

**Comment by yoyo837** [comment]
实例和类的区别，前面俄发给你了

**Comment by yoyo837** [comment]
看不见我发的？

**Comment by xuoutput** [comment]
![image](https://user-images.githubusercontent.com/16385443/85557744-a3d24600-b65a-11ea-86ea-0c686294fffd.png)

**Comment by yoyo837** [comment]
你这个文件.ts吧？改为.tsx看看

**Comment by xuoutput** [comment]
改成 .tsx 后变成
![image](https://user-images.githubusercontent.com/16385443/85558475-5904fe00-b65b-11ea-9c0e-7b418c48a7f8.png)

我在

**Comment by yoyo837** [comment]
那看不见图片！你只是绕过问题并没有解决问题

**Comment by xuoutput** [comment]
通过引入 `import React from  'react'` 把报错都清掉了, 图标显示出来了, 谢谢大佬 @yoyo837 
![image](https://user-images.githubusercontent.com/16385443/85561036-d0d42800-b65d-11ea-9ee1-af752592bef8.png)
![image](https://user-images.githubusercontent.com/16385443/85561086-dc275380-b65d-11ea-8a12-9d7bdfea2a4f.png)
