### ISSUE TITLE
Table header fixed is not aligned if display or browser uses zooming

### ISSUE THREAD

**Issue by antoniodesousa** [ant-design/ant-design#25207]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/ (Dynamic Settings example and change header to fixed)](https://ant.design/components/table/ (Dynamic Settings example and change header to fixed))

### Steps to reproduce
Set your display scale to any value other than 100% or change the zooming in the browser.

### What is expected?
Table header and body are perfectly aligned 

### What is actually happening?
Table header and body are not perfectly aligned 

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | react 16.13.1 |
| System | Windows 10 Enterprise 1809 |
| Browser | Google Chrome 83.0.4103.106 |

Here is a screenshot of this issue (I changed the border color to be more visible):

![Fixed Header not aligned](https://user-images.githubusercontent.com/10920974/85541850-c17ebb80-b618-11ea-9945-08b6f3259da0.png)

**Comment by afc163** [comment]
I think nothing we can do about it. ┓( ´∀` )┏

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17324#issuecomment-505938145

**Comment by afc163** [comment]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/507615/86312586-a550cf00-bc55-11ea-91ff-49798fe82f33.png">

<img width="402" alt="image" src="https://user-images.githubusercontent.com/507615/86312608-b13c9100-bc55-11ea-91a6-914cd40d9b5f.png">

列头和内容宽度在精度上确实会有一些差异。
