### ISSUE TITLE
No way to control AutoComplete dropdown width with dropdownMenuStyle

### ISSUE THREAD

**Issue by grkacy** [ant-design/ant-design#25216]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-eg96q?file=/index.js)

### Steps to reproduce
Setting a style via dropdownMenuStyle is applied to the menu but the dropdown remains in its original size.

### What is expected?
Was expecting the size of the autocomplete dropdown to assume the same size as the menu item.

### What is actually happening?
The dropdown size remained unchanged

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

---
I am working on a dropdown that will be dynamically positioned depending on the position of the cursor in the input field (hence you see there my experimentation with dropdownAlign)

**Comment by afc163** [comment]
Try `dropdownStyle`: https://codesandbox.io/s/antd-reproduction-template-vuo3l?file=/index.js

**Comment by afc163** [comment]
Or you may need https://ant.design/components/mentions/
