### ISSUE TITLE
Popover and tooltip are not displayed for custom components

### ISSUE THREAD

**Issue by awall** [ant-design/ant-design#25214]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pedantic-bird-bopvk)

### Steps to reproduce
Place a custom component as the child element of a Tooltip, the tooltip does not render. Wrap that child in a div, and then it renders fine.

### What is expected?
The tooltip should render, even if it is a custom component.

### What is actually happening?
The tooltip only renders if it is a "builtin" DOM element (like div, p, etc...), or an AntD component, but it won't render custom components.

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | All, tested on 16.13.1 |
| System | All, tested on Windows 10 |
| Browser | All, tested in Firefox and Chrome  |

---
This bug was reported last year in April, and mysteriously closed, even though it was never fixed! Please see https://github.com/ant-design/ant-design/issues/15909 for reference.

**Comment by afc163** [comment]
https://codesandbox.io/s/hopeful-elbakyan-vw0gv?file=/src/index.js

**Comment by Gibbo3771** [comment]
Same problem here. Entire component is pretty much useless if you want to combine it with iconography. Any ideas/work arounds?

**Comment by 07akioni** [comment]
> Same problem here. Entire component is pretty much useless if you want to combine it with iconography. Any ideas/work arounds?

You should make relevant event listener prop available on your component

**Comment by Mathijs003** [comment]
> https://codesandbox.io/s/hopeful-elbakyan-vw0gv?file=/src/index.js

This example is always working

**Comment by webcolor-in** [comment]
> Same problem here. Entire component is pretty much useless if you want to combine it with iconography. Any ideas/work arounds?

Simplest is to wrap with any other element like div/span.

**Comment by webcolor-in** [comment]
> > https://codesandbox.io/s/hopeful-elbakyan-vw0gv?file=/src/index.js
> 
> This example is always working

The reason why this is happening is, popover or tooltip element registers events on child element and when we have another custom component it is not able to. 

![image](https://user-images.githubusercontent.com/55145799/126588257-15c53d2a-8562-43ef-bc2b-6eae41ba5b5a.png)
