### ISSUE TITLE
Form `initialValues` is not working if Form.Item children has extra element

### ISSUE THREAD

**Issue by tonynguyenit18** [ant-design/ant-design#25217]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-hd3ln?file=/EditForm.js)

### Steps to reproduce
-  With label the `initialValues` is not working for userName
- Comment out the label it will work

### What is expected?
with or without extra element `initialValues` should be working

### What is actually happening?
with extra element `initialValues` is not working

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-8ooix?file=/EditForm.js

**Comment by amitpatil321** [comment]
Check documentation here https://4x.ant.design/components/form/#components-form-demo-complex-form-control
