### ISSUE TITLE
Table with scroll option wraps words instead of auto-sizing columns based on content

### ISSUE THREAD

**Issue by eparizzi** [ant-design/ant-design#25227]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-4x-table-scroll-issue-hsuuk)

### Steps to reproduce
Using Antd version 4.x, create a Table with `scroll={{ x: "max-content" }}`

### What is expected?
Columns should autosize based on content instead of wrapping to fix inside the Table container. I expect the same behaviour as Table from Antd 3.x (see the same example above working fine in 3.x [here](https://codesandbox.io/s/antd-3x-table-scroll-ok-fc8gg))

### What is actually happening?
Columns wrap words and doesn't autosize based on content.

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | Any system |
| Browser | Any modern browser |

**Comment by afc163** [comment]
That is weird because it works well in Firefox.
