### ISSUE TITLE
Table body row always rerender even set stable rowKey and return false from shouldCellUpdate

### ISSUE THREAD

**Issue by cncolder** [ant-design/ant-design#25224]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd4-table-move-cursor-y60ci?file=/index.js)

### Steps to reproduce
1. Expand `.ant-table-tbody` element in chrome dev tools.
2. Click `Move Cursor` button. It will move cursor one step and slice three lines from data.

### What is expected?
Only render the last line. Skip first two lines.

Here is antd 3 table demo show what's difference.
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](antd3-table-move-cursor-ivthu?file=/index.js)

### What is actually happening?
All three line rerender even the keys of row is same. 
columns config `shouldCellUpdate: () => false` not work.

| Antd 4 Table | Antd 3 Table |
|---|---|
| ![屏幕录制2020-06-25 20 06 52](https://user-images.githubusercontent.com/127009/85720178-c4fe6980-b722-11ea-9030-58c6836c961b.gif) | ![屏幕录制2020-06-25 20 14 03](https://user-images.githubusercontent.com/127009/85720475-0b53c880-b723-11ea-8cfe-e248d57fe5ec.gif) |

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | react 16.13.1 |
| System | macOS |
| Browser | Chrome 83 |

**Comment by coolcorexix** [comment]
I have this problem too and I have to end up using an extra state layer to make sure that the children does not get re-render so often
