### ISSUE TITLE
List of Ant Design resources

### ISSUE THREAD

**Issue by websemantics** [ant-design/ant-design#2522]
Hi all,

My apologies that this is not an issue. Just wanted to say how awesome Ant Design is, and I only discovered this yesterday. 

I created a list of the available resources here, 
https://github.com/websemantics/awesome-ant-design mainly for people who are interested to find related projects and or add their own. Also, I hope you like my Ascii Art :)

Keep up the great work,

**Comment by afc163** [comment]
Great job!

There is plenty of examples using antd here: https://github.com/ant-design/ant-design/issues/129 U might be interested.

**Comment by websemantics** [comment]
Will definitely add, thanks for the links @afc163 :-)

**Comment by websemantics** [comment]
All added, .. finally!

**Comment by benjycui** [comment]
Close now, and any useful resources of Ant Design could be PR to https://github.com/websemantics/awesome-ant-design
