### ISSUE TITLE
Ability to customize icon for Sider's zero width special trigger

### ISSUE THREAD

**Issue by allenylzhou** [ant-design/ant-design#25237]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using multiple Siders (one on left and one on right), having both zero width special triggers be BarsIcon means my users are not able to differentiate between what they do.

### What does the proposed API look like?
`<Sider zeroWidthSpecialTrigger={<SomeIcon />} />`

**Comment by afc163** [comment]
`trigger`

**Comment by allenylzhou** [comment]
The special zero-width trigger cannot be customized:
```
// special trigger when collapsedWidth == 0
    const zeroWidthTrigger =
      parseFloat(String(collapsedWidth || 0)) === 0 ? (
        <span
          onClick={this.toggle}
          className={`${prefixCls}-zero-width-trigger ${prefixCls}-zero-width-trigger-${
            reverseArrow ? 'right' : 'left'
          }`}
          style={zeroWidthTriggerStyle}
        >
          <BarsOutlined />
        </span>
      ) : null;
```
It is always BarsOutlined.
