### ISSUE TITLE
Enable legacy Rangepicker behavior 

### ISSUE THREAD

**Issue by Cenume** [ant-design/ant-design#25230]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
New rangepicker where the start and end time is selected separately is a nice update, but on some use case it is preferable to choose a range on every selection (such as this https://github.com/ant-design/ant-design/edit/master/components/date-picker/demo/select-in-range.md case, you cannot set start time earlier directly, have to clear up first etc)/

### What does the proposed API look like?
Choice to enable selecting both start and end time at once just like antd 3.x

<img width="603" alt="Screenshot 2020-06-26 at 3 13 56 PM" src="https://user-images.githubusercontent.com/18655810/85830739-aa2e0280-b7bf-11ea-84ca-441e92922ea1.png">

<img width="795" alt="Screenshot 2020-06-26 at 3 14 14 PM" src="https://user-images.githubusercontent.com/18655810/85830762-b619c480-b7bf-11ea-9c77-2c7731bd1982.png">

**Comment by zombieJ** [comment]
https://github.com/react-component/picker/pull/89
https://github.com/react-component/picker/pull/90
