### ISSUE TITLE
ConfigProvider 配置的 locale 对弹框中的元素不生效

### ISSUE THREAD

**Issue by jinliming2** [ant-design/ant-design#25239]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crimson-snowflake-8odje?file=/index.js)

### Steps to reproduce
已配置中文语言，鼠标移动到外层的 copyable 的复制按钮上可看到中文提示。

点开弹框，在弹框中的复制按钮则不能显示为中文。

### What is expected?
弹框中继承语言配置显示为中文

### What is actually happening?
弹框中没有继承语言配置

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | latest |
| System | Linux kernel 5.4.48 |
| Browser | Chrome Dev 85.0.4173.0 |

**Comment by zombieJ** [comment]
静态方法没有 context，用 hooks 获取上下文：https://ant.design/components/modal-cn/#components-modal-demo-hooks
