### ISSUE TITLE
有没有谁做了基于12px样式啊！

### ISSUE THREAD

**Issue by codedart2018** [ant-design/ant-design#25232]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
能更丰富的展现内容！

### What does the proposed API look like?
以14px拿来做中后台字体还是大了，呈现还是不舒服的！主要是后台展现的内容比较多！把body设置成12px 某些可以12px保持某些组件高度不变，但是如果基于padding的组件就会导致高度宽度不一致在页面更难看。想问下有谁人改造过！求一份样式！

**Comment by fireairforce** [comment]
try https://github.com/ant-design/ant-design/issues/25231#issuecomment-650104660 ?
