### ISSUE TITLE
When you delete a row of data, all rows below this row will be re-rendered. Even if rowKey is set.

### ISSUE THREAD

**Issue by accwill** [ant-design/ant-design#25234]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-edit-cell](https://ant.design/components/table-cn/#components-table-demo-edit-cell)

### Steps to reproduce
点击 2次 "Add a Row" ，向Table中添加2行数据。然后点击第二行右侧的"delete"按钮删除第二行数据，此时第二行下面的所有tr都会被重新渲染。

### What is expected?
删除当前行，当前行下面的行不会被重新渲染

### What is actually happening?
删除当前行，当前行下面的行会被重新渲染

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | windows |
| Browser | 78.0.3904.87 |

**Comment by afc163** [comment]
similar to #25224

**Comment by zombieJ** [comment]
https://ant.design/components/table-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-%E6%9B%B4%E6%96%B0-state-%E4%BC%9A%E5%AF%BC%E8%87%B4%E5%85%A8%E8%A1%A8%E6%B8%B2%E6%9F%93%EF%BC%9F
