### ISSUE TITLE
ant-design date picker

### ISSUE THREAD

**Issue by AteFeh-Gh** [ant-design/ant-design#25235]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.npmjs.com/package/antd-jalali-moment](https://www.npmjs.com/package/antd-jalali-moment)

### Steps to reproduce
I added Datepicker object in my component, then I localized it by  moment.locale("fa"),  in _app.js file of next js project
https://www.npmjs.com/package/antd-jalali-moment

### What is expected?
I expect the date picker format to be completely Persian

### What is actually happening?
I have used antd-jalali-moment as a datepicker, and i have a problem. The problem is ,at the first time, it shows the miladi year on year picker. but when i click on the year picker to change it, the year is in jallali format in the inner page and it is correct. but at the first time show, it is not ok. thank you so much for helping me to solve it.
"antd": "^4.3.1",
"antd-jalali-moment": "^3.3.2",
"next": "^9.2.1",

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | Next js 9.2.1 |
| System | Ubuntu |
| Browser | chrome |

**Comment by zombieJ** [comment]
Pls provide antd only reproduce instead.

**Comment by thakurujjwal** [comment]
date picker or range picker work fine but when click on cross icon onchange not work  but when select another date in datepicker  onchange work but click on cross icon onchange not  work .
