### ISSUE TITLE
Can message destroy the specified key?

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#25236]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
跨变量作用域使用 message 时，可以不用额外的全局存储实例对象。

### What does the proposed API look like?
```
message.loading({ content: '正在加载...', duration: 0, key: 'loading' });

message.destroy('loading');
```

**Comment by afc163** [comment]
supported in #26052
