### ISSUE TITLE
RangePicker open twice on Safari

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#25241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
click on RangePicker to open

### What is expected?
open normally

### What is actually happening?
opening twice

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.12.0 |
| System | macOs |
| Browser | Safari |

**Comment by saneksa** [comment]
In the same way, all the drop-down elements in IE 11 are opened

**Comment by afc163** [comment]
I can't reproduce it in Safari.

![2020-07-01 17-52-33 2020-07-01 17_54_04](https://user-images.githubusercontent.com/507615/86230609-e13b5400-bbc3-11ea-8bc6-8050c9d48bcb.gif)
