### ISSUE TITLE
Table Column Children using TypeScript

### ISSUE THREAD

**Issue by faizankhan1995** [ant-design/ant-design#25248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allows Table Column to have sub-columns using typescript 

### What does the proposed API look like?
<Table<Product>
<Table.Column <Discounts>>
<SubColumns>
</Table.Column>
</Table>

**Comment by zombieJ** [comment]
Use `Table.CulmnGroup`.
