### ISSUE TITLE
3.0 版本中表格拖拽demo的问题

### ISSUE THREAD

**Issue by xukaifengit** [ant-design/ant-design#25258]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/table-cn/#components-table-demo-drag-sorting](https://3x.ant.design/components/table-cn/#components-table-demo-drag-sorting)

### Steps to reproduce
打开重现链接 点击codesandbox 即可复现
报错位置：import HTML5Backend from 'react-dnd-html5-backend';

### What is expected?
import { HTML5Backend } from 'react-dnd-html5-backend';

### What is actually happening?
demo可以正常运行了

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | Not related |
| System | Not related |
| Browser | Not related |

---
辛苦更新下

**Comment by fireairforce** [comment]
https://github.com/ant-design/ant-design/pull/25151
更新了应该是还没发布。
