### ISSUE TITLE
Upload component 多点击几次上传就会崩溃，大概是内存占满了，谷歌浏览器

### ISSUE THREAD

**Issue by Pangnz** [ant-design/ant-design#25256]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jtqow)

### Steps to reproduce
点击上传，点击取消，这样反复操作几次，就会出现浏览器崩溃

### What is expected?
多操作几次不崩溃，能正常打开

### What is actually happening?
多操作几次崩溃，直接程序无响应，要关掉浏览器才可以再次使用

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | "react": "^16.12.0", |
| System | windows 10专业版 |
| Browser | Google Chrome 版本 83.0.4103.106（正式版本） （64 位） |

**Comment by fireairforce** [comment]
我这边貌似没有这个问题 
macos 10.15.5
Chrome版本: 83.0.4103.116（正式版本） （64 位）

**Comment by Pangnz** [comment]
> 我这边貌似没有这个问题
> macos 10.15.5 
> Chrome版本: 83.0.4103.116（正式版本） （64位）
是因为我是windows吗 我回去用mac试试=-=

**Comment by fireairforce** [comment]
我只是提供一个参照😂

**Comment by afc163** [comment]
Duplicate of #25206
