### ISSUE TITLE
Tree树形控件在叶子节点的内容比较长时会无法正常显示，怎么添加水平滚动条？

### ISSUE THREAD

**Issue by fengnex** [ant-design/ant-design#25268]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tree的典型用途是用来展示一个文件夹下面的子文件夹及其中的文件，文件夹、文件名都可能较长，目前在这种情况下tree组件会无法完整展示节点文件或文件夹的名字

### What does the proposed API look like?
可以设置tree组件的width，或通过其他方式，tree组件在需要时自动展示水平滚动条

**Comment by fengnex** [comment]
![image](https://user-images.githubusercontent.com/26297547/86197390-d82c9180-bb87-11ea-96ae-0fb8bda466cc.png)

上图是这个链接上运行你们自己的例子的xiaog效果：https://ant.design/components/tree-cn/
这个问题是非常显而易见的

**Comment by fengnex** [comment]
实际UI上不会给tree组件象上图那么宽的空间
tree空间非常常见，无法想象v4.4的ant design还有这样的问题

**Comment by yoyo837** [comment]
包一层设置overflow-x

**Comment by fengnex** [comment]
谢谢@yoyo837
不好意思，这不是bug！

**Comment by Fleeting198** [comment]
在 Tree 组件上设置样式 overflow-x: scroll; white-space: no-wrap; 能仅藉由水平滚动来显示超宽的节点。

**Comment by fengnex** [comment]
@Fleeting198 Thank you a lot for your so helping suggestion, and it's really useful!

**Comment by zhangzp0803** [comment]
问题解决了吗？我们也遇到了同样的问题，

**Comment by zhangzp0803** [comment]
> @Fleeting198 Thank you a lot for your so helping suggestion, and it's really useful!

问题解决了吗？我们也遇到了同样的问题

**Comment by Fleeting198** [comment]
> > @Fleeting198 Thank you a lot for your so helping suggestion, and it's really useful!
> 
> 问题解决了吗？我们也遇到了同样的问题

是的解决了，就像我之前说的这样加样式，这不能解决你的问题吗？

**Comment by Idletalk** [comment]
> > > @Fleeting198 Thank you a lot for your so helping suggestion, and it's really useful!
> > 
> > 
> > 问题解决了吗？我们也遇到了同样的问题
> 
> 是的解决了，就像我之前说的这样加样式，这不能解决你的问题吗？

如果是利用了treeSelect的异步加载，这种就没有效果了，有什么解决方案吗

**Comment by coopercoder** [comment]
是的，treeSelect有什么办法解决这个问题吗。

**Comment by xiaolifeipiao** [comment]
> ![image](https://user-images.githubusercontent.com/26297547/86197390-d82c9180-bb87-11ea-96ae-0fb8bda466cc.png)
> 
> 上图是这个链接上运行你们自己的例子的效果：[https://ant.design/components/tree-cn/，从中可以看到tree的组件在超出div的外框时的效果。如果节点更长，包含了更多个单词，那么一个节点会被显示为多行。](https://ant.design/components/tree-cn/%EF%BC%8C%E4%BB%8E%E4%B8%AD%E5%8F%AF%E4%BB%A5%E7%9C%8B%E5%88%B0tree%E7%9A%84%E7%BB%84%E4%BB%B6%E5%9C%A8%E8%B6%85%E5%87%BAdiv%E7%9A%84%E5%A4%96%E6%A1%86%E6%97%B6%E7%9A%84%E6%95%88%E6%9E%9C%E3%80%82%E5%A6%82%E6%9E%9C%E8%8A%82%E7%82%B9%E6%9B%B4%E9%95%BF%EF%BC%8C%E5%8C%85%E5%90%AB%E4%BA%86%E6%9B%B4%E5%A4%9A%E4%B8%AA%E5%8D%95%E8%AF%8D%EF%BC%8C%E9%82%A3%E4%B9%88%E4%B8%80%E4%B8%AA%E8%8A%82%E7%82%B9%E4%BC%9A%E8%A2%AB%E6%98%BE%E7%A4%BA%E4%B8%BA%E5%A4%9A%E8%A1%8C%E3%80%82) 这个问题是非常显而易见的

大佬找到解决方案了吗？
