### ISSUE TITLE
Updated to v4.3.5, Tabs animation didn't work

### ISSUE THREAD

**Issue by liuxinqiong** [ant-design/ant-design#25277]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lo5yh)

### Steps to reproduce
click tab bar to switch tabPane

### What is expected?
when switch to another tab, the tabPane switched with animation

### What is actually happening?
animation didn't work

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | react |
| System | macOS Mojave |
| Browser | Chrome  83.0.4103.61 |

**Comment by afc163** [comment]
Tabs `animated` default value change to `false` after `4.3.0` in https://github.com/ant-design/ant-design/issues/25061
