### ISSUE TITLE
Carousel Duplicating Items

### ISSUE THREAD

**Issue by JoaoP57** [ant-design/ant-design#25289]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kcuuw?file=/package.json)

### Steps to reproduce
Inspect Carousel items

### What is expected?
Correctly render the amount of items provided to the carousel

### What is actually happening?
Carousel is duplicating the elements.
If I provide 3 elements the data-index for the carousel will go up to 6 and duplicate the elements.

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | React.js |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
It is by designed, you can read source of https://github.com/akiran/react-slick

**Comment by izrobin** [comment]
Did you find a solution to this? @JoaoP57 ? I have the same problem, and @afc163 's link is completely useless.

**Comment by MuhammadAhmed1994** [comment]
Any update on this issue?

**Comment by vnghia187** [comment]
> Any update on this issue?

just set infinite prop to false if number of items is equal to slideToShow prop

**Comment by baig13** [comment]
> > Any update on this issue?
> 
> just set infinite prop to false if number of items is equal to slideToShow prop

Thanks for saving my life
