### ISSUE TITLE
Attempted import error: 'rc-textarea' does not contain a default export (imported as 'RcTextArea').

### ISSUE THREAD

**Issue by jonnywang** [ant-design/ant-design#25284]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
none

### Steps to reproduce
yarn start

Failed to compile.

./node_modules/antd/es/input/TextArea.js
Attempted import error: 'rc-textarea' does not contain a default export (imported as 'RcTextArea').

 

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.12.0 |
| System | mac os10.14.6 |
| Browser | none |
| Node |v12.18.1

**Comment by ycjcl868** [comment]
+1

**Comment by ycjcl868** [comment]
https://github.com/react-component/textarea/commit/92fd5e99339cec6da43fdff6c474928860daf4df

**Comment by eparizzi** [comment]
Same issue here when using Antd 4.4.0 in a Next project:
https://codesandbox.io/s/antd-440-with-next-issue-i0qb2

**Comment by kamil-ignac-ih21** [comment]
+1

**Comment by chaitan94** [comment]
This can be closed as a duplicate to https://github.com/ant-design/ant-design/issues/25285, as both were raised at same time, which https://github.com/ant-design/ant-design/issues/25285 has a codesandbox to reproduce the issue in addition
