### ISSUE TITLE
Can select start day and end day at same time in Range Picker

### ISSUE THREAD

**Issue by JackMei7709** [ant-design/ant-design#25282]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In previous version, we can select the start day and end day at the same time, thus we apply for the time range check when we select both of them. However, currently we can only select one by one, thus we need to select twice and remove the time range check.

### What does the proposed API look like?
Apply for both select at the same time.

**Comment by JackMei7709** [comment]
Or if we can solve at least when change date, can have date range check.. Otherwise we have to add search button to do the check.

**Comment by xrkffgg** [comment]
duplicate: https://github.com/ant-design/ant-design/issues/25291
