### ISSUE TITLE
broken encoding for arrows in datePicker

### ISSUE THREAD

**Issue by themafia98** [ant-design/ant-design#25288]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
P.S: Not reproduction in sandbox.

### Steps to reproduce
Encoding: UTF-8.
![Bug encoding](https://i.ibb.co/GMmvcGH/image-2020-06-29-10-40-36-478.png)

### What is expected?
Expected arrows icons

### What is actually happening?
Bad arrows icons

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.4 |
| System | Windows |
| Browser | Chrome 83 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/17480, please upgrade antd.
