### ISSUE TITLE
升级antd后,table通过getCheckboxProps配置disabled,数据更新后disabled不对新数据起作用

### ISSUE THREAD

**Issue by just-me-cy** [ant-design/ant-design#2528]
比如
 const data = [{
      key: '1',
      name: '胡彦斌',
      age: 32,
      address: '西湖区湖底公园1号',
    }, {
      key: '2',
      name: '胡彦祖',
      age: 42,
      address: '西湖区湖底公园1号',
    }, {
      key: '3',
      name: '李大嘴',
      age: 32,
      address: '西湖区湖底公园1号',
    }];

配置
 const rowSelection = {
      getCheckboxProps: record => ({
        disabled: record.name === '李大嘴',    // 配置无法勾选的列
      }),
    };

然后数据更新
 this.setState(() => {
      this.state.data[0].name = '李大嘴';
    });
**发现第一行还是可以勾选。**

**Comment by afc163** [comment]
`this.state.data[0].name = '李大嘴';`

认真学习下 react 吧，不能直接修改 state 对象。https://facebook.github.io/react/docs/component-api.html#setstate
