### ISSUE TITLE
InputNumber绑定Form表单后，手动修改一个值后，加减按住不放，不能正常的加减

### ISSUE THREAD

**Issue by ChaoshengZhang** [ant-design/ant-design#25298]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-water-1s4lk?file=/index.js)

### Steps to reproduce
1、Form表单项绑定InputNumber;
2、手动修改一个值；
3、直接鼠标按住不放加或者减；

### What is expected?
正常按照设置step加减

### What is actually happening?
来回跳动

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.5.2 |
| System | window10 |
| Browser | 谷歌浏览器 |

---
改变之后，失焦或者点击一下在按住不放，不会出现问题

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/issues/22528, please upgrade to antd v4.
