### ISSUE TITLE
Column Selection in the table

### ISSUE THREAD

**Issue by arpitmalik** [ant-design/ant-design#25290]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The idea is to make a column selection in the table just like we have in excel. So we can select a particular columns and alter the data in it.
For example: If it is a table named "scooter prices". And we want to select the scooter price for a particular year and add/subtract some amount from it.

https://stackoverflow.com/questions/52762533/react-ant-design-table-multiple-column-row-selection

### What does the proposed API look like?
Just like we have a rowSelection, we should have a colSelection to select particular rows.

**Comment by afc163** [comment]
Please use `column.render` for this feature.
