### ISSUE TITLE
Nothing is shown in Avatar when setting icon first and then children

### ISSUE THREAD

**Issue by hjiawei** [ant-design/ant-design#25294]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-tu-ycfmf)

### Steps to reproduce
Run the example in codesandbox.io and wait for 2 seconds

### What is expected?
When the `userInitial` isn't set, show the `UserOutlined` icon in `Avatar`. After the `userInitial` is fetched, unset the icon and show the `userInitial` string.

### What is actually happening?
The `UserOutlined` icon is showing fine initially. After the `userInitial` is fetched, nothing is shown in `Avatar`.

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | codesandbox.io |
| Browser | Google Chrome Version 83.0.4103.116 (Official Build) (64-bit) |

---
I am not sure if this is still a valid use case after the `Avatar` bugfix #24944 in 4.3.4 (guessing... not sure if this is really caused by it). It was working fine in 4.3.3 though.

If what I am doing is not right, please suggest a better way. What I want to do is the following:
* When the `userInitial` isn't yet fetched from the backend, show the `UserOutlined` icon.
* After the `userInitial` is fetched, show the `userInitial` string instead of the icon.

**Comment by afc163** [comment]
https://codesandbox.io/s/stoic-nightingale-q289j?file=/index.js

**Comment by hjiawei** [comment]
Thank you for your prompt reply. Works fine now after the change.
