### ISSUE TITLE
Table 分页错误显示错误

### ISSUE THREAD

**Issue by sliuqin** [ant-design/ant-design#253]
http://gitlab.alipay-inc.com/alipay-cd/emcooperate/commit/e8353e8c52785432ce52d6172c7134acd1669e8b

src/component/WarningDashboard/SearchResultTabPane.jsx 文件的代码变更。
单独使用 Pagination 是正常的。

**Comment by yiminghe** [comment]
公司内网地址不要贴出啊

**Comment by afc163** [comment]
实测没有问题，周一见面了看。
