### ISSUE TITLE
RangePicker选择一个时间区间后，点击日历外面关闭日历，会把input内的时间区间替换了，而不是通过点击确定按钮来替换

### ISSUE THREAD

**Issue by luosenhao** [ant-design/ant-design#25308]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/date-picker-cn/#RangePicker](https://3x.ant.design/components/date-picker-cn/#RangePicker)

### Steps to reproduce
点击RangePicker选择一个时间区间含时分秒，点击日历外面，关闭日历

### What is expected?
input继续保持原有的值不变

### What is actually happening?
该时间区间会被赋值到input上

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | win10 |
| Browser | firefox |

---
解决方案二：能否控制点击日历外关闭日历的事件

**Comment by zombieJ** [comment]
Close since v3 end maintains life cycle.
