### ISSUE TITLE
antd 4.x Table 不支持ref

### ISSUE THREAD

**Issue by aNewLearnerHere** [ant-design/ant-design#25306]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#API](https://ant.design/components/table-cn/#API)

### Steps to reproduce
/** @desc 类组件直接引用即可 */
import React from 'react';
import {Table} from 'antd';

type IProps = ReturnType<typeof mapStateToProps>;
const mapStateToProps = (rootState: IRootState) => ({
  global: rootState.Common_global,
});

Class TableAutoFixed extends Component<IProps,{}> {
   const tableRef:any = React.createRef();
   ...
   return <Table ref={this.tableRef}/>;
}
export default connect(mapStateToProps, null, null, { forwardRef: true })(TableAutoFixed);

### What is expected?
ref正常使用

### What is actually happening?
通过ref写的功能无法正常使用，ts检查的时候报错Table无ref属性，同时使用了react-redux的connect功能，虽然已经采用透传forwardRef方式:connect(mapStateToProps, null, null, { forwardRef: true })(TableAutoFixed)，但仍报错 Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8.6 |
| System | mac  |
| Browser | chrome |

---
TableAutoFixed 是实现表格依据可视窗口大小来判断是否对table固定列的功能

**Comment by raualvron** [comment]
Hi everyone.

Is going the Table component to support ref? 

We updated to Ants v4 and it looks like what it is not supported anymore.

Thanks

**Comment by ko22009** [comment]
Up

**Comment by berdyshev** [comment]
any updates here?

**Comment by delphin92** [comment]
If you need just ref to \<table> DOM element, you can use this WA:
```javascript
const tableRef = useRef<HTMLTableElement>(null);

const TableWrapper = (props: any) => (
  <table ref={tableRef} {...props}/>
);
...

<Table
  components={{
    table: TableWrapper
  }}
/>
```

**Comment by JounQin** [comment]
Is there any better solution natively? 😂

The above solution would work, but just sounds like a hack.

**Comment by JounQin** [comment]
```ts
/** based on @see https://developers.google.com/web/updates/2017/09/sticky-headers */
useEnhancedEffect(() => {
  if (!sticky) {
    return
  }

  const tableContainer = tableRef.current!.closest(
    `.ant-table-wrapper`,
  ) as HTMLDivElement // prefer using `tableRef.current` directly rather than DOM API

  return observeIntersectionOn(addStickySentinel(tableContainer), {
    threshold: 1,
  }).pipe(tap(ev => setStickyActive(ev.intersectionRatio < 1)))
}, [sticky])

/** @see https://github.com/ant-design/ant-design/issues/25306#issuecomment-852022326 */
const table = useCallback(
  (props: HTMLAttributes<HTMLTableElement>) => (
    <table ref={tableRef} {...props} />
  ),
  [],
)
```

**Comment by JounQin** [comment]
Sorry, I just found my use case is so simple, I finished up by wrapping a div container:

```ts
export const Table = ({ stikcy, ...props }) => {
  const ref = useRef()
  return (
    <div className="relative">
      {stikcy && <div ref="ref" className="sticky-sentinel"></div>}
      <Table {...props} />
    </div>
  )
}
```

But a `ref` or prop `prefix` should be preferred for no wrapping.
