### ISSUE TITLE
Table 表格组件  头部 fixed 之后 表格body与header列错误（mac下正常，window下错位）

### ISSUE THREAD

**Issue by howieyi** [ant-design/ant-design#25300]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/2bri0)

### Steps to reproduce
进入演示代码后，选择显示边框，选择固定头部，body 和 header 单元格会错位

### What is expected?
window下，单元格正常无错位

### What is actually happening?
window下单元格错位严重，甚至header引入单元格拖动宽度后，错位会更加严重，mac下正常

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
给个截图？

**Comment by howieyi** [comment]
![image](https://user-images.githubusercontent.com/8057227/86093247-37839680-bae1-11ea-93f2-f8841ac2a990.png)

**Comment by howieyi** [comment]
如果引入 resize-cell 之后错位会比较夸张

**Comment by zombieJ** [comment]
看你的按钮样式似乎缩放了屏幕？

**Comment by afc163** [comment]
#25207

**Comment by howieyi** [comment]
没有缩放屏幕，正常打开就这样的

**Comment by zombieJ** [comment]
应该也是 windows 下高清屏设置了显示百分比

**Comment by howieyi** [comment]
没有，我想说什么都没设置。。。就正常打开就这样了，你们试下window电脑都可以重现的，fixed header 之后就可以了。。。

**Comment by afc163** [comment]
@howieyi 试一下 <kbd>Ctrl</kbd> + <kbd>0</kbd>？

**Comment by howieyi** [comment]
额，已经说了浏览器没有做放大缩小。。。。别把别人当小白呀。。。我都说了几遍了，你们找一台window电脑试一下不就知道了，不要一直揣测。。。。

**Comment by afc163** [comment]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/507615/86312586-a550cf00-bc55-11ea-91ff-49798fe82f33.png">

<img width="402" alt="image" src="https://user-images.githubusercontent.com/507615/86312608-b13c9100-bc55-11ea-91a6-914cd40d9b5f.png">

不只是 windows，列头和内容宽度在精度上确实会有一些差异。

**Comment by afc163** [comment]
我们可能需要更精确的宽度监听：https://github.com/react-component/resize-observer/blob/000b8dead14be42540057ed6b23a71ce7a84bb66/src/index.tsx#L87-L93

cc @zombieJ

**Comment by zombieJ** [comment]
> 我们可能需要更精确的宽度监听 @zombieJ
> 
> https://github.com/react-component/resize-observer/blob/000b8dead14be42540057ed6b23a71ce7a84bb66/src/index.tsx#L87-L93

这端防抖代码，不参与计算。问题在于 `offsetWidth` 返回像素尺寸，而 `getBoundingClientRect` 会被外层的 `transform` 影响实际值。我试试用 `getComputedStyle` 来看看效果。

**Comment by zombieJ** [comment]
@howieyi @afc163  

它不仅仅是游览器的缩放，在 windows 的高清屏下分辨率还有一层缩放：
![mmexport1593694947156](https://user-images.githubusercontent.com/5378891/86362289-a1e63380-bca7-11ea-9b01-d01362bf426c.png)


这是我的 windows 下 100%：
![mmexport1593694661885](https://user-images.githubusercontent.com/5378891/86361841-fb019780-bca6-11ea-900f-936ed6b77566.png)

**Comment by zombieJ** [comment]
另外试了一下 `getComputedStyle` 能获取精确像素，但是设置上去后没有效果。

**Comment by afc163** [comment]
@howieyi 看看是不是上面说的操作系统里的缩放与布局打开了，如果也是这种情况我们可能没什么办法。

**Comment by howieyi** [comment]
@afc163 的确这种情况可以，不过window10人家推荐都125%显示了，难道还要让人家用户自己去设置这个吗，不合理呀

**Comment by afc163** [comment]
@howieyi 主要还是我们没有办法解决。

**Comment by howieyi** [comment]
我还发现一个问题，就是异步获取数据渲染的时候，你们头部是优先渲染的，body异步之后渲染的，第一次渲染会错乱的宽度会比较夸张，不是这种1像素的差别，这就导致我还非得在数据获取完成后才能渲染table了
第一次
![image](https://user-images.githubusercontent.com/8057227/86697036-98125680-c040-11ea-80b1-2e8f6cd4947f.png)
第二次
![image](https://user-images.githubusercontent.com/8057227/86696876-73b67a00-c040-11ea-98d7-5f4dcb3d4356.png)

**Comment by zombieJ** [comment]
window 是根据当前分辨率来推荐缩放比，不是所有都是 125%。
另外这个是 windows 和 Chrome 的兼容问题，上面提过，我在代码端获取到非整数值后设置回去后 Fixed Header 还是对不齐这个就没办法了。

**Comment by afc163** [comment]
关闭了，因为我们没好办法修复，有什么好的解决方案欢迎继续回复或给我们 PR。

**Comment by 77soul** [comment]
https://juejin.cn/post/7243796937199616037 好好学 好好看
