### ISSUE TITLE
tabs 拖拽排序显示错误

### ISSUE THREAD

**Issue by FEliuyg** [ant-design/ant-design#25302]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nrlc1)
该实例为官方demo

### Steps to reproduce
拖拽tab项，active状态显示异常，文字和线不在一个位置

### What is expected?
显示正常

### What is actually happening?
显示异常

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome |

**Comment by huntdream** [comment]
@afc163 pr发到rc-tabs了，大佬有空看下👀
