### ISSUE TITLE
table 从服务端读取数据时，rowSelection 的选中状态翻页无法记住

### ISSUE THREAD

**Issue by chenyuan208** [ant-design/ant-design#25312]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fast-currying-s607k?file=/index.js)

### Steps to reproduce
1，checkbox选中一条数据
2，点击第二页
3，第二页checkbox选中一条数据
4，点击第一页

### What is expected?
第一页的数据被选中

### What is actually happening?
第一页的数据没有被选中

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | mac os 10.15.2 |
| Browser | chorme 83.0.4103.116  |

**Comment by jsshizhan** [comment]
我也遇到了，这个是什么原因

**Comment by zXuff** [comment]
得把preserveSelectedRowKeys设置成true才行
