### ISSUE TITLE
select选择框， 下拉框option（生成的menuitem）的key值取的一直是value的值

### ISSUE THREAD

**Issue by flymoonspirit** [ant-design/ant-design#2531]
#- antd 版本: 1.6.5
- 操作系统及其版本：mac
- 浏览器及其版本: chrome

```jsx
<Option
          key={item.key}
          value={item.value}
        >
          {item.value}
</Option>
```

此处设置的key值无效，下拉生成的MenuItem的key总是".$item.value"，以前版本应该会取item.key+"/"+".$item.value"作为最终的key

**Comment by benjycui** [comment]
所以你碰到的问题是什么？

warning 提示重复的 key 还是说你想读取 key 值？

**Comment by flymoonspirit** [comment]
warning 提示重复的 key

**Comment by benjycui** [comment]
那就有点诡异了。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
无进一步反馈，先关了，有问题再开。
