### ISSUE TITLE
select 按label过滤bug

### ISSUE THREAD

**Issue by xiexingen** [ant-design/ant-design#25314]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lingering-flower-syq2x?file=/package.json)

### Steps to reproduce
输入张三

### What is expected?
匹配的列表里面应该只显示一条数据

### What is actually happening?
显示了两条张三的数据

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | Chrome |

再附上一张图

![image](https://user-images.githubusercontent.com/7939085/86130421-b515c980-bb16-11ea-9d22-f2f6250910d3.png)

**Comment by xrkffgg** [comment]
是因为两个 `key` 不同
`mode="tags"` 的时候，你输入什么，默认的 `key` `value` 就是什么
你把你例子中的 key 001 改成  张三，让 key 和 value 保持一样，你再搜索，就正常了。

**Comment by xiexingen** [comment]
> 是因为两个 `key` 不同
> `mode="tags"` 的时候，你输入什么，默认的 `key` `value` 就是什么
> 你把你例子中的 key 001 改成 张三，让 key 和 value 保持一样，你再搜索，就正常了。

但是这应该算bug吧，既然配置了搜索的属性是label了 不应该还是按key去算

**Comment by xrkffgg** [comment]
这个不是 搜索的问题，是 `mode="tags"` 会新增 选项
