### ISSUE TITLE
允许拖动改变列宽或者行高。Allow dragging to change column width or row height.

### ISSUE THREAD

**Issue by ILiuDongHui** [ant-design/ant-design#25316]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望实现与Excel中类似的效果，可以通过使用鼠标拖动列的边框来调整列的宽度或者行的高度。

EN:  
To achieve a similar effect to columns in Excel, you can adjust the width of the column or the height of the row by dragging the border of the column with the mouse.

### What does the proposed API look like?
```
<Table allowRowResize={true} allowColResize={true} ... />
```

**Comment by ILiuDongHui** [comment]
Table Component

**Comment by zombieJ** [comment]
https://ant.design/components/table-cn/#components-table-demo-resizable-column

**Comment by wuxianyuan** [comment]
table的width属性是百分比的，拖动这个其他的也跟着变化，这样子效果真的很差
