### ISSUE TITLE
RadioGroup 

### ISSUE THREAD

**Issue by zhuyankun** [ant-design/ant-design#25310]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/tree/4.4.0](https://github.com/ant-design/ant-design/tree/4.4.0)

### Steps to reproduce
Form使用 RadioGroup 就会报错

### What is expected?
无Warning

### What is actually happening?
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
    in RadioGroup

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | react 16.13.1 |
| System | win10 |
| Browser | Google Chrome 83.0.4103.116 |

---
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
    in RadioGroup

**Comment by undead25** [comment]
官方示例：https://codesandbox.io/s/nsp9f?file=/index.js

**Comment by JoyceLizhuo** [comment]
+1,同样遇到这个问题,Radio.Group的ref丢失导致form.getFieldInstance('具体的key')不预期，希望尽快修复

**Comment by songjoe** [comment]
遇到了同样的问题

**Comment by 224137748** [comment]
+1

**Comment by lucifer1004** [comment]
Why is this issue closed?

**Comment by yoyo837** [comment]
This weekend

**Comment by lucifer1004** [comment]
Thanks.


On 07/2/2020 22:09，Amumu<notifications@github.com> wrote：

This weekend

**Comment by flycj** [comment]
+1,  遇到同样的问题

**Comment by yybin** [comment]
+1遇到了同样的问题

**Comment by flycj** [comment]
> +1遇到了同样的问题

更新到最新版本就行了
