### ISSUE TITLE
文件太大上传失败

### ISSUE THREAD

**Issue by cjchnwscqwsbsy** [ant-design/ant-design#25325]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/upload-cn/](https://3x.ant.design/components/upload-cn/)

### Steps to reproduce
上传的文件超过300M失败

### What is expected?
如何上传500M文件

### What is actually happening?
error

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | win10 |
| Browser | 83 |

**Comment by yoyo837** [comment]
这应该是服务端相关吧？只要服务端支持，持续上传几天几夜都没问题。

**Comment by Kermit-Xuan** [comment]
服务端或者代理层应该有超时时间，超时后自动断开了

**Comment by yoyo837** [comment]
请先排除服务端的原因，还有问题再打开。
