### ISSUE TITLE
React Strict Mode prevents opened Modal from hiding the background scrollbar

### ISSUE THREAD

**Issue by Doesntmeananything** [ant-design/ant-design#25323]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-paper-x48kt?file=/src/index.js)

### Steps to reproduce
1. Click 'Open Modal' button and observe that it doesn't hide the background scrollbar.
2. Go to `index.js`.
2. Change mode from `strict` to `notStrict` for the App component.
3. Click 'Open Modal' button and observe that the background scrollbar is now being hidden.

### What is expected?
When opening a modal, the background scrollbar should be hidden even if React Strict Mode is on.

### What is actually happening?
When opening a modal, the background scrollbar is not hidden with React Strict Mode on.

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | Manjaro Linux 20.0.3 |
| Browser | Google Chrome 83.0.4103.116 |

---
With Strict Mode on, `body` doesn't have the necessary css properties to hide the scrollbar:
![not working](https://i.imgur.com/utGdx8h.jpg)

However, without Strict Mode, the correct css properties get attached:
![working](https://i.imgur.com/QTd4Ugq.jpg)

**Comment by afc163** [comment]
It may be related with facebook/react#15074

**Comment by afc163** [comment]
Duplicate of #28228
