### ISSUE TITLE
select support value type null/undefined

### ISSUE THREAD

**Issue by WenhanDo** [ant-design/ant-design#25327]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When chooseing query options, there is always an option with null/undefined value that means "all", but Select only accepts string/number value

### What does the proposed API look like?
should be accepting null/undefined

**Comment by yoyo837** [comment]
`<Option value="">All</Option>`

**Comment by WenhanDo** [comment]
> `<Option value="">All</Option>`

what about null, null means different with undefined

**Comment by yoyo837** [comment]
`null` values ​​are already available

`<Option value={null}>All</Option>`

**Comment by yoyo837** [comment]
`undefined` means it have not select yet.

**Comment by WenhanDo** [comment]
> `undefined` means it have not select yet.

`undefined` means 'do not filter' while `null` means 'filter for value null'

**Comment by afc163** [comment]
Like @yoyo837 said, `undefined` means not value selected, you can use `null` or `""`.

https://codesandbox.io/s/nervous-sun-k3nqn?file=/index.js

**Comment by chillyistkult** [comment]
@afc163 According to the typescript interface `null` is not supported:

`RawValue | RawValue[] | LabeledValue | LabeledValue[]`

`declare type RawValue = string | number;`

How to solve this `Select<string | null>` does not work?

**Comment by yfzhe** [comment]
Meet the same type problem today. Any progress on this issue?
