### ISSUE TITLE
【需求】官方支持dash docset

### ISSUE THREAD

**Issue by cookie314** [ant-design/ant-design#25332]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
虽然在线文档非常帮，还是希望团队有空是否能支持下dash的docset？离线文档无论是速度还是便捷性可能还是更高效一点。
之前有https://github.com/yesmeck/antd-dash民间的支持，到3.4的版本，目前4.4的已经不能正常生成文档了。
因为跟site的组织结构和代码关联毕竟大，所以个人觉得官方支持更靠谱点。

### What does the proposed API look like?
dash文档。https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/Ant_Design

**Comment by hengkx** [comment]
离线文档更新不及时吧，如果是速度问题的话 antd 有在国内部署一套官网

**Comment by jhoneybee** [comment]
离线文档。 

```
git clone https://github.com/ant-design/ant-design.git 
npm install  
npm run site
```

然后放在electronjs，或者nginx或者其他任何能够渲染html的里面。

**Comment by cookie314** [comment]
也不是网络或速度问题。本地serve或者官网的，如果要查找某个组件的文档，就要打开网页，查找组件。而dash docset基本就是键盘快捷键，效率方面更好一点。

**Comment by nailuoGG** [comment]
在 [/yesmeck/antd-dash](https://github.com/yesmeck/antd-dash) 基础上改改，构建出了docset，但是访问页面时提示404

bisheng的确是生成了多页面的文档，但是保留了路由判断逻辑，如果路由不匹配是会报错的。暂时还在找相关的代码

![image](https://user-images.githubusercontent.com/4554827/89094659-16240c00-d3f9-11ea-8770-c15b723843cb.png)

**Comment by nailuoGG** [comment]
效果是这样，中文英文都有

<img width="1095" alt="图片" src="https://user-images.githubusercontent.com/4554827/192182604-76e51404-3a66-44c4-aa6e-9697d4973644.png">

制作方法：

```bash
git clone https://github.com/ant-design/ant-design.git
brew install dashing
npm run site && cd _site && dashing init antd
```

会生成一个文件 _site/dashing.json， 修改他
```json
{
  "name": "Ant Design",
  "package": "antd",
  "index": "index.html",
  "selectors": {
    ".main-container .markdown h1": {
      "type": "Component",
      "matchpath": "components"
    },
    "#demo-toc > li": {
      "type": "Section",
      "matchpath": "components"
    }
  },
  "ignore": ["ABOUT", "#header", ".main-menu"],
  "icon32x32": "",
  "allowJS": true,
  "ExternalURL": "https://ant.design/"
}

```

最后在_site目录中执行：

 dashing build antd

**Comment by zombieJ** [comment]
官网暂无精力支持，这里就先关了哈。
