### ISSUE TITLE
Select crashed with key of undefined on virtual list

### ISSUE THREAD

**Issue by albert-cai** [ant-design/ant-design#25331]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-oave3a?embed=1&file=index.js](https://stackblitz.com/edit/react-oave3a?embed=1&file=index.js)

### Steps to reproduce
Type ru then select ru and click back into the select as to make another selection.
Keeps on selecting value and typings if first step did not trigger it.

### What is expected?
Not to crash on selected value

### What is actually happening?
Seems to be random. Happen after selection is made and we click back into the Select to make another selection. Seems to happen only for virtualized value (not initially shown when clicking on the dropdown)

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12.0 |
| System | Mac OS 10.15.5 |
| Browser | chrome OS 83.0.4103.106 |

---
This bug was fixed by rc-virtual-list@1.1.5. But the fixed version was not used by the latest rc-select. And naturally not used by the latest and. Please upgrade the version of rc-virtual-list to make sure bug fixing works in new and version.

**Comment by albert-cai** [comment]
[24329](https://github.com/ant-design/ant-design/issues/24329) has not been fixed in antd@4.2.5, this bug still exists.

**Comment by afc163** [comment]
https://stackblitz.com/edit/react-oave3a-tq8aqa?file=package.json

```diff
-   "antd": "4.2.4",
+   "antd": "4.2.5",
```

**Comment by albert-cai** [comment]
> https://stackblitz.com/edit/react-oave3a-tq8aqa?file=package.json
> 
> ```diff
> -   "antd": "4.2.4",
> +   "antd": "4.2.5",
> ```

Please check the dependency version. antd@4.2.5 is not working. 
This bug was fixed by rc-virtual-list@1.1.5. But the fixed version was not used by the latest rc-select. And naturally not used by the latest and. Please upgrade the version of rc-virtual-list to make sure bug fixing works in new and version.

**Comment by albert-cai** [comment]
> https://stackblitz.com/edit/react-oave3a-tq8aqa?file=package.json
> 
> ```diff
> -   "antd": "4.2.4",
> +   "antd": "4.2.5",
> ```

The Reproduction link is copied from [24329](https://github.com/ant-design/ant-design/issues/24329) because of this is a required field. This issue is for updating the dependency version of rc-virtual-list@1.1.5

**Comment by afc163** [comment]
![2020-07-01 11-26-18 2020-07-01 11_29_26](https://user-images.githubusercontent.com/507615/86200002-2b094780-bb8e-11ea-93bb-d3d745886b5b.gif)

Did I missing something?

**Comment by albert-cai** [comment]
@

> ![2020-07-01 11-26-18 2020-07-01 11_29_26](https://user-images.githubusercontent.com/507615/86200002-2b094780-bb8e-11ea-93bb-d3d745886b5b.gif)
> 
> Did I missing something?

As I said, this issue is not opened for this Reproduction link.

**Comment by albert-cai** [comment]
> @
> 
> > ![2020-07-01 11-26-18 2020-07-01 11_29_26](https://user-images.githubusercontent.com/507615/86200002-2b094780-bb8e-11ea-93bb-d3d745886b5b.gif)
> > Did I missing something?
> 
> As I said, this issue is not opened for this Reproduction link.

![image](https://user-images.githubusercontent.com/20965109/86200172-8dfade80-bb8e-11ea-98a8-76306049de91.png)

**Comment by albert-cai** [comment]
> > @
> > > ![2020-07-01 11-26-18 2020-07-01 11_29_26](https://user-images.githubusercontent.com/507615/86200002-2b094780-bb8e-11ea-93bb-d3d745886b5b.gif)
> > > Did I missing something?
> > 
> > 
> > As I said, this issue is not opened for this Reproduction link.
> 
> ![image](https://user-images.githubusercontent.com/20965109/86200172-8dfade80-bb8e-11ea-98a8-76306049de91.png)

![image](https://user-images.githubusercontent.com/20965109/86200232-b1be2480-bb8e-11ea-80b5-d58659a85850.png)
![image](https://user-images.githubusercontent.com/20965109/86200247-bc78b980-bb8e-11ea-8f0c-40a650cb90f2.png)

**Comment by afc163** [comment]
Please remove `yarn.lock` and `package-lock.json` then reinstall `node_modules`.
