### ISSUE TITLE
Input 组件报错 Attempted import error: 'rc-textarea' does not contain a default export (imported as 'RcTextArea').

### ISSUE THREAD

**Issue by mrsy3249** [ant-design/ant-design#25349]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/tree/4.4.0](https://github.com/ant-design/ant-design/tree/4.4.0)

### Steps to reproduce
import { Input } from 'antd';
<Form.Item><Input></Input></Form.Item>

### What is expected?
正常显示

### What is actually happening?
渲染报错

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | window10 |
| Browser | Chrome (83.0.4103.116) |

**Comment by afc163** [comment]
Fixed in #25284
