### ISSUE TITLE
Modal.confirm.content = <DatePicker />时，全局的语言包配置失效

### ISSUE THREAD

**Issue by lincolon** [ant-design/ant-design#25344]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/](https://ant.design/components/config-provider-cn/)

### Steps to reproduce
按钮点击事件，调用Modal.confirm({title: '导出配送单',content: <DatePicker/>})；DatePicker的语言包还是英文的

### What is expected?
DatePicker使用全局配置的语言包

### What is actually happening?
DatePicker使用默认的语言包

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | mac os 10.15.5 |
| Browser | chrome83 |

**Comment by yoyo837** [comment]
静态方法不支持全局国际化配置，改用hook形式

**Comment by yoyo837** [comment]
Duplicated of #22873
