### ISSUE TITLE
When set LabelInValue in Select，typeof Select  value exchange to {label: xxx, value:xxx} ;but has `value` property

### ISSUE THREAD

**Issue by jinglf000** [ant-design/ant-design#25355]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kind-agnesi-6ildg)

### Steps to reproduce
1、select options 
2、console will print result

### What is expected?
when Select set labelInValue，Select value don't have`value` property

### What is actually happening?
when Select set labelInValue，Select value  have`value` property

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | Mac 10.15.2 |
| Browser | Chrome 83 x64 |

**Comment by afc163** [comment]
I don't understand your problem.

**Comment by jinglf000** [comment]
real
![image](https://user-images.githubusercontent.com/14195057/86244015-e6a39900-bbd9-11ea-9c77-eac9109c605b.png)
docs
![image](https://user-images.githubusercontent.com/14195057/86244091-033fd100-bbda-11ea-95c7-ef0c919924e0.png)

**Comment by afc163** [comment]
Select option `key` could replace `value` in all situations, let me update documentation about it.
