### ISSUE TITLE
修改列表数据的时候多出来一个字段indexForSort，这个有什么用

### ISSUE THREAD

**Issue by llh520xw** [ant-design/ant-design#2535]
#### 本地环境

- antd 版本:最新版本
- 操作系统及其版本：windows
- 浏览器及其版本:google

#### 你做了什么？
修改应用列表数据

#### 你期待的结果是：

将原有的数据与修改后的数据进行合并，得到正常的数据

#### 实际上的结果：
![Uploading image.png…]()

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/2501

**Comment by llh520xw** [comment]
![qq 20160729122457](https://cloud.githubusercontent.com/assets/13639327/17237722/836ebfa2-5587-11e6-90cb-f545a75ca5a9.png)
修改数据，将原有的数据，与修改后的数据合并，提示说不能修改indexForSort字段，这个怎么解决

**Comment by llh520xw** [comment]
我将源码里面的table改了，还是报这样的错误
![qq 20160729123024](https://cloud.githubusercontent.com/assets/13639327/17237804/484f0836-5588-11e6-9db8-326bc2fbf6b7.png)

**Comment by afc163** [comment]
把你的代码贴一贴，最好提供重现。

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
你这么直接改源码会报错的吧，`...` 浏览器不支持的。

**Comment by llh520xw** [comment]
![1](https://cloud.githubusercontent.com/assets/13639327/17239845/c99ede96-5599-11e6-96e2-22b4acf568bb.png)
![2](https://cloud.githubusercontent.com/assets/13639327/17239846/c9c7e67e-5599-11e6-9525-af4408e4256f.png)
![3](https://cloud.githubusercontent.com/assets/13639327/17239848/c9e11f36-5599-11e6-9556-44ba450cb48e.png)
![4](https://cloud.githubusercontent.com/assets/13639327/17239847/c9e1029e-5599-11e6-81f4-547a2c1dba7d.png)
![5](https://cloud.githubusercontent.com/assets/13639327/17239850/c9ede7ca-5599-11e6-8d8c-93a9d6e9ed26.png)
![6](https://cloud.githubusercontent.com/assets/13639327/17239849/c9ea3300-5599-11e6-969b-6e7026192e0f.png)

**Comment by llh520xw** [comment]
http://codepen.io/anon/pen/wGOWGW?editors=001你发的这个不知道怎么创建文件。。。不会玩

**Comment by afc163** [comment]
感觉是你的 `this.state.todos` 里面有 undefined ，自己打印出来看看吧。

**Comment by llh520xw** [comment]
![7](https://cloud.githubusercontent.com/assets/13639327/17240123/ded52912-559b-11e6-92be-5e9fcac4e39f.png)
![8](https://cloud.githubusercontent.com/assets/13639327/17240124/ded9ff64-559b-11e6-8e94-70c16ad56f48.png)
有数据，新增的2条

**Comment by llh520xw** [comment]
问题在修改的时候提示我说不能修改 indexForSort 字段。
 Cannot set property 'indexForSort' of undefined

**Comment by llh520xw** [comment]
提交修改的数据，list列表里面打印this.props.todos里面有个undefined

**Comment by afc163** [comment]
dataSource 里不应该有 undefined 的，去掉即可。

**Comment by llh520xw** [comment]
我找到了
![image](https://cloud.githubusercontent.com/assets/13639327/17240354/9a379f2c-559d-11e6-8967-cd044fb20940.png)
这个位置原来只吧相同的数据返回了，修改下就好了，谢谢你
