### ISSUE TITLE
select 的mode 是多选的时候在ie11 上不能onFocus 不生效

### ISSUE THREAD

**Issue by ycshill** [ant-design/ant-design#25354]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-pond-9o10t)

### Steps to reproduce
在ie11 打开，然后鼠标聚焦到 多选的 select 框上

### What is expected?
onFocus 能生效

### What is actually happening?
onFocus 不能生效

| Environment | Info |
|---|---|
| antd | 3.26.16 |
| React | 16.8.6 |
| System | win 10 |
| Browser | ie11 |

**Comment by afc163** [comment]
3.x 修复过 https://github.com/react-component/select/commit/aa40e46c8105f1a349cdde74a3c50cd098fed3d9，4.x 改丢了。

**Comment by afc163** [comment]
发现还不是同一个问题，IE11 各种诡异。

**Comment by ycshill** [comment]
> 发现还不是同一个问题，IE11 各种诡异。

是呢，哪个版本修复了呢，我用的 3.26.16

**Comment by afc163** [comment]
3.x 不再维护了，请升级到 4.x 上。
