### ISSUE TITLE
progress 在4.4版本警告

### ISSUE THREAD

**Issue by HIPPOWUYUFAN** [ant-design/ant-design#25353]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[Warning: [antd: Progress] `successPercent` is deprecated. Please use `success` instead. ](Warning: [antd: Progress] `successPercent` is deprecated. Please use `success` instead. )

### Steps to reproduce
Warning: [antd: Progress] `successPercent` is deprecated. Please use `success` instead. 

### What is expected?
消除警告，或者更新文档说明

### What is actually happening?
Warning: [antd: Progress] `successPercent` is deprecated. Please use `success` instead. 

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | mac 10.15.4  |
| Browser | 83.0.4103.106 (正式版本) （64 位） |

**Comment by afc163** [comment]
文档已经没有 successPercent 了，请使用 `success={{ percent: xx }}`。

**Comment by fireairforce** [comment]
这个来源于：https://github.com/ant-design/ant-design/pull/24655，你可以使用 `success: { progress: number }` 替代原有的 `successPercent`,把进度条成功相关的配置都放在一个对象里面了～

**Comment by HIPPOWUYUFAN** [comment]
<Progress
          success={{ progress: this.state.result.levelPercent * 100 }}
        />


我是这样写的，依旧警告

**Comment by fireairforce** [comment]
![image](https://user-images.githubusercontent.com/32598811/86235336-d9cb7900-bbca-11ea-80a9-6ec5fe575ca1.png)
@afc163 这里的api设定是progress。

**Comment by HIPPOWUYUFAN** [comment]
<Progress
          success={{ progress: this.state.result.levelPercent * 100 }}
        />

我是这样写的，依旧警告

**Comment by fireairforce** [comment]
我修一下吧～抱歉，看见了

**Comment by afc163** [comment]
。。。感觉是个笔误，应该是 success.percent 的。

**Comment by HIPPOWUYUFAN** [comment]
thx

**Comment by FEliuyg** [comment]
官方demo也会报这个错误，而且没有配置success这个props

**Comment by JadeLiuYC** [comment]
使用upload组件时也会报这个警告，怎么解决？ @afc163

**Comment by fireairforce** [comment]
@JadeLiuYC 给个复现吧

**Comment by TwoNingMengTea** [comment]
使用 Upload 组件也会报这个警告。
官网的例子复制下来同样的问题。
antd 版本已经更新到 4.5.0

**Comment by 07akioni** [comment]
> 使用 Upload 组件也会报这个警告。
> 官网的例子复制下来同样的问题。
> antd 版本已经更新到 4.5.0

给个 codesandbox 的复现链接？
