### ISSUE TITLE
如何才能知道表单的字段是不是被编辑过

### ISSUE THREAD

**Issue by li5tun** [ant-design/ant-design#25350]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如果保存按钮默认是禁用的，直到有字段被编辑过后才可以点击

### What does the proposed API look like?
我试过onFieldsChange，onValuesChange，isFieldsTouched这些方法，但是如果在方法里调用setState去告诉render方法按钮当前的状态，值就修改不了了。有没有一个类似于isPristine的方法，可以用于这样的场景？

**Comment by zombieJ** [comment]
isFieldTouched

**Comment by Yangfan2016** [comment]
@zombieJ  请问像 直接粘贴内容 这种  好像 并没有触发  isFieldsTouched 这个方法
