### ISSUE TITLE
Expose internals of Table for better composability

### ISSUE THREAD

**Issue by utkuturunc** [ant-design/ant-design#25359]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Since the table component is opinionated, it's pretty hard to use it with other libraries. An example usa case would be to use https://github.com/tannerlinsley/react-table with ant table styles.

### What does the proposed API look like?
It would be useful to have components such as <Table><THead><TBody><Td><Tr> etc, containing only styling.

**Comment by afc163** [comment]
You can try `<Table componets={{ ... }} />` for more advanced usage, for examples:

-https://ant.design/components/table/#components-table-demo-resizable-column
- https://ant.design/components/table/#components-table-demo-drag-sorting-handler
