### ISSUE TITLE
Table component scroll bar rendering problem

### ISSUE THREAD

**Issue by luoJunGitHub** [ant-design/ant-design#25362]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If I set the scrollbar for the table component, it will always be there.For example, if I set scrolling by height, {y: 500}, the scroll bar will still appear when the component reaches 500px.The same goes for the horizontal scroll bar.I want the scroll bar to appear when the height or width is full of the set value or percentage.Percentage represents the height or width of the parent component of the table.

### What does the proposed API look like?
scroll:{x:"100%",y:"100%"}

**Comment by afc163** [comment]
It is by designed, trace in #25124
