### ISSUE TITLE
Table组件是否会在未来加强

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design#2536]
企业后台最复杂莫过于表格，希望未来会对表格组件进行增强， 比如表格内的编辑，设置显示列，拖动行排序等。

**Comment by dyf2015** [comment]
这些基于现有的自己实现都不难

发自我的 iPhone

在 2016年7月29日，11:54，dai875939260 <notifications@github.com<mailto:notifications@github.com>> 写道：


企业后台最复杂莫过于表格，希望未来会对表格组件进行增强， 比如表格内的编辑，设置显示列，拖动行排序等。

―

**Comment by Justin-lu** [comment]
@dai875939260 只需构造传入 columns 的顺序和列，即可实现列排序和隐藏/显示功能

**Comment by afc163** [comment]
后续会考虑逐步增强，目前这些功能确实都可以上层封装，当我们足够常用的时候，会逐步下沉到基础组件中，欢迎持续关注和贡献。
