### ISSUE TITLE
badge size (small)

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#25371]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
badge is to large right now (for an icon)
![image](https://user-images.githubusercontent.com/42112796/86280422-71899100-bbe4-11ea-90ed-f309c410c3db.png)
https://codesandbox.io/s/antd-reproduction-template-lo61v?file=/index.js
### What does the proposed API look like?
`<badge size='small' /> `

**Comment by xrkffgg** [comment]
Badge support `style`, you can customize it.

**Comment by yoyo837** [comment]
> Badge support `style`, you can customize it.

So, `Badge` does not support `size`?

**Comment by xrkffgg** [comment]
> So, `Badge` does not support `size`?

Yes

**Comment by 07akioni** [comment]
> > So, `Badge` does not support `size`?
> 
> Yes

Yes means No actually.

**Comment by xrkffgg** [comment]
@afc163 Do you think Badge needs to increase the `size`? Or just use `style`.

**Comment by 07akioni** [comment]
maybe we should provide a smaller edition of badge. the badge currently can't fill most reasonable use cases.

**Comment by afc163** [comment]
@07akioni Send it up!
