### ISSUE TITLE
Transfer组件是否考虑添加对右侧列表上下移动的功能

### ISSUE THREAD

**Issue by juneryo** [ant-design/ant-design#2538]
主要是想对右侧列表中的元素进行自定义的排序。
目前在当前Transfer组件基础上做相应功能扩展好像也不是很好弄的样子。。。

**Comment by benjycui** [comment]
通过 `render` 给每行增加上下移动按钮，移动数据后通过修改 `targetKeys` 调整右侧元素数据。

**Comment by juneryo** [comment]
哦哦，给每行都加上下移动的按钮啊，这倒是个办法，先去试试。
原来一直想直接在左移、右移的按钮的上方和下方加上按钮。

**Comment by juneryo** [comment]
试了下，能够满足需求，
只是在鼠标放上去的时候，会显示Object，不过问题也不大，暂时先这样好了=w=
![1](https://cloud.githubusercontent.com/assets/4101515/17240579/d2653c50-559e-11e6-9de2-3208661bd86f.png)

**Comment by afc163** [comment]
http://ant.design/components/transfer/#components-transfer-demo-custom-item

这里可以 return `{ label: xxx, value: xxx }` 这样的格式。

**Comment by juneryo** [comment]
发现问题了。。。
对targetKeys进行排序后，右侧列表并不会马上重新渲染，点击左移，触发onChange后才会。
http://codepen.io/juneryo/pen/BzNjzP?editors=0010
具体操作是：
点击右侧列表中的向上箭头，列表不变，这时点击左移箭头，右侧列表顺序变化。

**Comment by benjycui** [comment]
改为：

```js
targetKeys: this.state.targetKeys.reverse().concat(),
```

返回同一个引用会被认为是不变。

**Comment by yourenA** [comment]
请问一下我通过改变state.targetKeys的顺序，为什么视图没有改变

这是上移一个位置代码
`
        let selectedKeys=this.state.selectedKeys;
        let targetKeys=this.state.targetKeys
         const index=targetKeys.indexOf(selectedKeys[0]);//规定选择右边的一个
            const temp=targetKeys[index-1]
            targetKeys[index-1]=targetKeys[index]
            targetKeys[index]=temp;
            this.setState({
                targetKeys:targetKeys
            })
`
this.state.targetKeys已经改变了，但是试图却没有改变，请问一下为什么会这样？

**Comment by Xing-He** [comment]
```jsx
render={(item) => {
  const label = (
    <span>
      {
        targetKeys.includes(item.key) ? (
          <span>
            <Icon type="arrow-up" onClick={this.onMoveUp.bind(this, item)} />
            <Icon type="arrow-down" onClick={this.onMoveDown.bind(this, item)} style={{ paddingLeft: 4, paddingRight: 4 }} />
          </span>
        ) : null
      }
      {item.title}
    </span>
  );
  return { value: item.title, label };
}}
```

```js
onMoveUp = (item, e) => {
  e.stopPropagation();
  e.preventDefault();
  const { key } = item;
  const { targetKeys } = this.state;
  const index = targetKeys.indexOf(key);
  if (index > 0) {
    const upperKey = targetKeys[index - 1];
    targetKeys[index - 1] = key;
    targetKeys[index] = upperKey;
    this.setState({ targetKeys: [...targetKeys] });
  }
}
onMoveDown = (item, e) => {
  e.stopPropagation();
  e.preventDefault();
  const { key } = item;
  const { targetKeys } = this.state;
  const index = targetKeys.indexOf(key);
  if (index < targetKeys.length - 1) {
    const nextKey = targetKeys[index + 1];
    targetKeys[index + 1] = key;
    targetKeys[index] = nextKey;
    this.setState({ targetKeys: [...targetKeys] });
  }
}
```

**Comment by ktfj** [comment]
请求这个问题最后怎么解决的？

**Comment by agikoo** [comment]
![image](https://user-images.githubusercontent.com/696429/90100368-1c0ddb80-dd6f-11ea-9f31-8594daedc79a.png)
使用官方的表格Transfer，再加上表格的排序，可以完美实现

**Comment by Jiang1120** [comment]
> 用官方的表格传输，再加上表格的排序，可以完美实现如下图：
可以看一下具体代码嘛

**Comment by yybin** [comment]
> 使用官方的表格Transfer，再加上表格的排序，可以完美实现 如下图：
> ![image](https://user-images.githubusercontent.com/696429/90100368-1c0ddb80-dd6f-11ea-9f31-8594daedc79a.png)

可以贴一下代码具体如何实现的吗？

**Comment by femaimi9527** [comment]
请问各位大佬，有没点选项目能触发的事件？或者有事件函数能触发”移入 >“和”移出 <“按钮？感谢！
想着能实现勾选左边的某一项就能移动到右边，勾选右边同理。或者是勾选某一项就能触发一次”移入“和”移出“按钮。

**Comment by KevinChan168** [comment]
> 官方的表格Transfer

官方的表格Transfer是啥

**Comment by KevinChan168** [comment]
> 使用官方的表格Transfer，再加上表格的排序，可以完美实现 如下图：
> ![image](https://user-images.githubusercontent.com/696429/90100368-1c0ddb80-dd6f-11ea-9f31-8594daedc79a.png)

官方的表格Transfer是啥

**Comment by xu-hz** [comment]
> > 使用官方的表格Transfer，再加上表格的排序，可以完美实现 如下图：
> > ![image](https://user-images.githubusercontent.com/696429/90100368-1c0ddb80-dd6f-11ea-9f31-8594daedc79a.png)
> 
> 官方的表格Transfer是啥

请问这个具体实现思路是？

**Comment by laosandegudai** [comment]
> 试了下，能够满足需求， 只是在鼠标放上去的时候，会显示Object，不过问题也不大，暂时先这样好了=w= ![1](https://cloud.githubusercontent.com/assets/4101515/17240579/d2653c50-559e-11e6-9de2-3208661bd86f.png)

这是怎么实现只自定义右侧渲染框的？
