### ISSUE TITLE
how to hide expandIcon in antd table

### ISSUE THREAD

**Issue by preservance717** [ant-design/ant-design#25386]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tender-sanderson-w4dsn)

### Steps to reproduce
set expandIconAsCell and expandIconColumnIndex property. but icon still show.

- and version: v4.3

- `expandIconAsCell={false} expandIconColumnIndex={-1}`， but icon still show.  [demo](https://codesandbox.io/s/tender-sanderson-w4dsn)
![image](https://user-images.githubusercontent.com/18299850/86312502-6de22280-bc55-11ea-9f8e-116bed0800a5.png)

### What is expected?
provide property to hide expand icon

### What is actually happening?
set expandIconAsCell and expandIconColumnIndex property  but icon still show.

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.9.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
#24129

**Comment by afc163** [comment]
Duplicate of ##24129

**Comment by preservance717** [comment]
@afc163  is it fix in antv@4.3？can i use expandIconColumnIndex=-1 in antv@4.3
