### ISSUE TITLE
InputNumber 输入 999999999999.9999 自动格式化变成了 999999999999.9998

### ISSUE THREAD

**Issue by iblq** [ant-design/ant-design#25396]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/wtfname/pen/vYLpLjp?editable=true&editors=001%3Dhttps%3A%2F%2F3x.ant.design%2Fcomponents%2Finput-number-cn%2F](https://codepen.io/wtfname/pen/vYLpLjp?editable=true&editors=001%3Dhttps%3A%2F%2F3x.ant.design%2Fcomponents%2Finput-number-cn%2F)

### Steps to reproduce
输入 999999999999.9999

### What is expected?
999999999999.9999

### What is actually happening?
999999999999.9998

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.1 |
| System | OSX |
| Browser | chrome 83.0.4103.61 |

---
如 codepan 示例代码

**Comment by afc163** [comment]
InputNumber cannot handle big number issue: https://github.com/ant-design/ant-design/issues/5235#issuecomment-285665328
