### ISSUE TITLE
Popconfirm 点击空白处阻止弹出框关闭，只有在点击确定时才关闭

### ISSUE THREAD

**Issue by devin-huang** [ant-design/ant-design#25392]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2F3x.ant.design%2Fcomponents%2Fpopconfirm-cn%2F](https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2F3x.ant.design%2Fcomponents%2Fpopconfirm-cn%2F)

### Steps to reproduce
1.点击按钮
2.弹出气泡
3.空白关闭气泡

### What is expected?
点击空白处阻止弹出框关闭

### What is actually happening?
点击空白或者其他组件就会关闭

| Environment | Info |
|---|---|
| antd | undefined |
| React | 3.26.16 |
| System | window10 |
| Browser | Google Chrome 83.0.4103.116（正式版本） （64 位） |

**Comment by afc163** [comment]
这个组件的交互就是这么设计的。
