### ISSUE TITLE
how to use ConfigProvider to trim space in Input component？

### ISSUE THREAD

**Issue by unclepis** [ant-design/ant-design#25394]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i expect to use configProvider to make all the inputs trim the useless space in the beginning and the end ,does it make sense?

### What does the proposed API look like?
`
<ConfigProvider input={{trim:true}}>
</ConfigProvider>
`

**Comment by afc163** [comment]
Sorry, I don't think it is a common situation that ConfigProvider should handle.
