### ISSUE TITLE
Table组件的每列td怎么定义宽度？

### ISSUE THREAD

**Issue by Tinker404** [ant-design/ant-design#254]
react自动按照数据生成的表单，render里面都是td的子元素，设置宽度没意义，如何定义每个table列的宽度？

**Comment by zhujun24** [comment]
在 columns 设置 width

**Comment by zhechang520** [comment]
如何合并列？

**Comment by baizn** [comment]
在 columns 设置 width 貌似也不起作用，我是在外部添加了class，class中同时定义width和max-width属性才可以的。
