### ISSUE TITLE
table fixed hover 就会执行 render 方法

### ISSUE THREAD

**Issue by zinkey** [ant-design/ant-design#2540]
antd table 设置了 fixed，每次 hover 都会执行 columns 定义的 render 方法。

http://codepen.io/zinkey/pen/ZOjbXr?editors=0010

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2454

**Comment by afc163** [comment]
在 rc-table@4.4.2 修复了，重新安装即可。

另外，Table 的单元格渲染性能应该也有很大提升。

**Comment by MedusaLeee** [comment]
@afc163 您好，现在antd@2.9.1 依然存在这个问题 “每次 hover 都会执行 columns 定义的 render 方法” 
```javascript
{
      title: '#',
      dataIndex: 'number',
      key: 'number',
      width: 30,
      fixed: 'left',
      render: () => {
          // do something
     }
   },
```

**Comment by yesmeck** [comment]
@MedusaLeee 用 fixed  column 的情况下，hover 的那行会重新 render，这是正常行为。
