### ISSUE TITLE
Improvement to Date Picker

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#25404]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Makes it more intuitive and natural.

### What does the proposed API look like?
Expected Behavior:
=================

The purpose of allowing the users to type the dates in manually is to make it easier for them. The glitches and restrictions above doesn’t necessary make it easier.

`Issue 1`. Tab key should work to navigate from field to field, and it should not wipe out the date values.

`Issue 2`. Navigating with the mouse clicks also should not wipe out the date values.

`Issue  3`. The manual date entry to should work for format mm/dd/yyyy, when the user enters something like 1/1/2019 or 01/3/18

`Issue  4`. When using restricted formats like mm/dd/yyyy "/" slashes should be auto entered

These examples refer specifically when using Start and End Date together
`Issue 1`: Entry does not persist when navigating with the tab key
1. Enter Start Date by typing it
2. Press the tab key.  <— this is what users normally do when filling in forms to move from one field to another
3. It doesn’t do anything the first time. Press the tab key again.
4. Observe the cursor now moved to the End Date, and also Start Date entry gets wiped out.

`Issue 2`: Entry does not persist when using the mouse either
1. Enter Start Date by typing it, do not press enter or tab.
2. Instead use the mouse pointer to click on the End Date.
3. Type in the End Date manually also instead of selecting a date from the calendar popup.
4. Press enter
5. Observe how dates are wiped out

`Issue 3`: Entry persists when pressing the Enter key but the format is restricted
1. Ensure date formats are set to MM/DD/YYYY
2. Start typing in the Start Date manually: 3/3/2020
3. Press the Enter key, and observe that the entry gets wiped out.
4. Enter the Start Date again and this time use: 03/03/2020
5. Press the Enter key, and observe that everything works this time.

`Issue 4`: Entry persists when pressing the Enter key but the format is restricted
1. Ensure date formats are set to MM/DD/YYYY
2. Start typing in the Start Date manually: 03/03/2020
3. Notice how every time we need to input "/". This should be intuitive and auto inputted based on user typing

**Comment by Geczy** [comment]
Looks very similar to https://github.com/ant-design/ant-design/issues/25403

These issues would be great to have fixed, thank you for writing it up

**Comment by StallionV** [comment]
Thanks @Geczy I see [#25403](https://github.com/ant-design/ant-design/issues/25403#issue-650065414) and it seems to related to the arrow usage. I have tried to include a much wider scope to make the usage more intuitive, specially when using keyboard. Hopefully it can be looked into.

**Comment by StallionV** [comment]
Thank you for acknowledging it. I am tight on cycles and am extremely unlike to pick this up.
But I see you already have the help wanted tag and hopefully someone else can step in.
Fingers Crossed

**Comment by henk-mapli** [comment]
> Issue 2. Navigating with the mouse clicks also should not wipe out the date values.

This will be very useful. Our users often click outside the date picker to dismiss it, but then do not notice that the date they picked got reverted.

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
