### ISSUE TITLE
新版本更新下 Form.Item hidden 存在样式问题

### ISSUE THREAD

**Issue by xiaojun1314** [ant-design/ant-design#25409]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
无

### What is expected?
隐藏表单 高度也需要隐藏 

### What is actually happening?
目前的结果 隐藏字段 高度没有隐藏 留有空白

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | react |
| System | window 7  |
| Browser | 谷歌双核 |

**Comment by xiaojun1314** [comment]
https://codesandbox.io/s/antd-reproduction-template-fpyok?file=/index.js

**Comment by xiaojun1314** [comment]
看一下这个 一个小例子  表单隐藏空白处 还是存在的
https://codesandbox.io/s/antd-reproduction-template-fpyok?file=/index.js

**Comment by xrkffgg** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/25336
