### ISSUE TITLE
关于复杂form表单多层级组件验证的一些疑问

### ISSUE THREAD

**Issue by dmdoit** [ant-design/ant-design#25417]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
做了一个sku的form表单，目前涉及到父、子、孙 层级的组件，
sku组件属于孙组件，父组件定义了[form] = Form.useForm(),  sku这个组件已经与其他组件解耦
现在我想验证孙组件里的数据，因为form里不能嵌套form，我有什么好的方式处理吗？
![image](https://user-images.githubusercontent.com/19385704/86452875-88002b80-bd4f-11ea-9932-1e1b2eed9bb6.png)

### What does the proposed API look like?
期望大神给点方案

**Comment by hmilin** [comment]
孙组件中使用Form并设置component属性为false就不会渲染出dom节点了

**Comment by zpr1g** [comment]
https://ant.design/components/form-cn/#Rule 通过 validator 自定义校验规则就行了吧

**Comment by dmdoit** [comment]
@zpr1g  
![image](https://user-images.githubusercontent.com/19385704/86462297-f64bea80-bd5d-11ea-81be-389a457353f3.png)

**Comment by whateveryoudo** [comment]
你好，我是使用的ant-design-vue，和你有同样的问题，目前的解决办法：1. sku 放弃采用自定义组件的形式（会覆盖整个formitem下的表单控件)，在formitem下方设置一个无高度的formitem, useForm直接自定义校验。2.关于sku内部部分字段校验，其实也是采用useForm的方式，（将单条sku封装成组件，useForm传入当前行数据进行rule校验，PS:这里在内部校验是没有问题的，对外通信不了（因为你useForm的范围仅在当前行), 我目前采用的方法，监听最外部的操作，譬如submit操作，则手动调用一次当前行的validate,来触发样式显示)。
