### ISSUE TITLE
栅格布局nz-row与nz-col之间多了一层自定义的标签，栅格布局不生效

### ISSUE THREAD

**Issue by 007GitHu** [ant-design/ant-design#25416]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/angular-nmgbo1?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-nmgbo1?file=src/app/app.component.ts)

### Steps to reproduce
栅格布局nz-row与nz-col之间能加上自定义的标签，封装各个组件后，使用时会有一层标签，而9版本栅格布局中，多了一层自定义的标签，栅格布局失效

### What is expected?
可以加自定义标签，方便封装

### What is actually happening?
实际加了自定义标签后栅格布局不生效

| Environment | Info |
|---|---|
| antd | undefined |
| React | 9 |
| System | window10 |
| Browser | 谷歌 |

**Comment by yoyo837** [comment]
是不是提交错地方了？

**Comment by afc163** [comment]
反馈错地方了。
