### ISSUE TITLE
The selected style of the menu component submenu item is abnormal

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#25412]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shousuoshizicaidanxiangxuanzhongseyichang-b9ejd)

![QQ截图20200703151119](https://user-images.githubusercontent.com/14865584/86442848-fb4e7100-bd40-11ea-826e-48df65aaa1c1.png)

### Steps to reproduce
1. Open the reproduction link
2. Zoom out the preview view
3. View omitted submenu items

### What is expected?
Only the selected menu item is highlighted

### What is actually happening?
All submenu items containing the `a` label are highlighted

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.x |
| System | windows 10 |
| Browser | last |

**Comment by kaysonwu** [comment]
Caused by this line of code: [https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less#L327](https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less#L327)

**Comment by kaysonwu** [comment]
@zombieJ  [https://github.com/ant-design/ant-design/commit/e4a1a45b0928c1da600867da67085156841a7cdb](https://github.com/ant-design/ant-design/commit/e4a1a45b0928c1da600867da67085156841a7cdb)

**Comment by kaysonwu** [comment]
related: [https://github.com/ant-design/ant-design/issues/23830](https://github.com/ant-design/ant-design/issues/23830)

**Comment by zombieJ** [comment]
@kaysonwu  do you have interesting to create a PR for this?

**Comment by kaysonwu** [comment]
Modified to the following:

```less
  &-vertical &-submenu-selected,
  &-vertical-left &-submenu-selected,
  &-vertical-right &-submenu-selected {
    color: @menu-highlight-color;
    > a,
   > span > a {
      color: @menu-highlight-color;
    }
  }

```

国内 git 拉取太慢了

**Comment by zombieJ** [comment]
可以试试 chrome 的  `gitpod` 插件哈~

**Comment by yoyo837** [comment]
梯子，秒天秒地

**Comment by kaysonwu** [comment]
好的，这次你先修复吧 @zombieJ

**Comment by yoyo837** [comment]
也可以试试在线编辑，不拉取

**Comment by kaysonwu** [comment]
在线编辑入口发我下，我一下子找不到那个入口了

**Comment by kaysonwu** [comment]
我找到在线入口了，没有在贡献指南里面。我尝试下修复这个问题

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/blob/master/components/menu/style/index.less 

![image](https://user-images.githubusercontent.com/6134547/86445737-7fa2f300-bd45-11ea-8475-5ec429075f91.png)

**Comment by kaysonwu** [comment]
😂 图片我看不到，也不知道你发了什么

**Comment by yoyo837** [comment]
```shell
151.101.184.133    user-images.githubusercontent.com
```

**Comment by kaysonwu** [comment]
好了，我来解决这个问题吧
