### ISSUE TITLE
AutoComplete在使用官方查询模式 - 确定类目示例，加入filterOption属性不能区分大小写，报错了

### ISSUE THREAD

**Issue by tanforce** [ant-design/ant-design#25419]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?editors=0011](https://codepen.io/pen/?editors=0011)

### Steps to reproduce
AutoComplete使用官方查询模式 - 确定类目示例，加入filterOption属性不能区分大小写，会报错：Uncaught TypeError: option.props.children.toUpperCase is not a function

### What is expected?
能够区分大小写进行搜索

### What is actually happening?
不能区分大小写搜索

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | Google Chrome 71.0.3578.98 |

**Comment by tanforce** [comment]
https://codesandbox.io/s/antd-reproduction-template-nzyj3

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-huy45?file=/index.js
