### ISSUE TITLE
Upload组件，在Windows10上，拖拽上传出现“正在打开”提示框和打开一个空白标签页

### ISSUE THREAD

**Issue by gitshan** [ant-design/ant-design#2541]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：window10
- 浏览器及其版本: Firefox 47.0.1

#### 你做了什么？

- 打开 http://ant.design/components/upload/#components-upload-demo-drag
- 拖拽文件至上传区域

#### 你期待的结果是：

- 和chrome表现一致，无“正在打开该文件”的提示和新的空白标签页

#### 实际上的结果：

- 提示正在打开该文件，并打开一个空白标签页

#### 可重现的在线演示

- 可在官网直接复现 http://ant.design/components/upload/#components-upload-demo-drag

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2422

**Comment by ddcat1115** [comment]
这个应该是 ff 对 onDrop 的默认行为导致的，可以尝试在 `Upload` 外包一层并给该元素的 onDrop 事件函数 preventDefault & stopPropagation，我试了一下应该可以的
