### ISSUE TITLE
InputNumber 支持stringMode 模式

### ISSUE THREAD

**Issue by kpaxqin** [ant-design/ant-design#25418]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
|       | InputNumber(antd)   |  input[type="number"]  |
| --------    | -----  |  ----  |
| value类型  | number (触发多次时可能为null或string)  |   string  |
| value合法性 | 有保证 |  IE不保证，其它有保证  |
| 区分 0 与 0.00 |   不支持   |   支持   |
| big number  |   不支持    |  支持  |
|  comma 作为小数点 | 支持 |  视浏览器、用户区域行为不一致，Chrome强制不支持  |
| 跨平台一致性  |   优    |  差  |

如上表，阻碍目前在多币种涉金额场景下使用InputNumber的主要问题：
1. 大数支持与值类型问题，风险角度无法接受输入框会导致用户输入值发生变化，这也引申出期望像原生input[type='number']一样使用字符串表示value，前端将字符串交给后端消费，杜绝前端导致的值变形
2. 值类型问题，触发多次且类型不统一，下游校验、消费逻辑风险增加

使用原生 input[type=number] 的主要问题：
1. 跨平台体验不一致，对于使用 comma 表示小数点的地区，可能在firefox下能输入comma，在chrome就不行
2. IE下值合法性没有保障，比如IE下onchange会抛出 `"2abc,"`  这样的value，在firefox/chrome等现代浏览器下就直接被认为是空值了

从思路上，原生的input[type=number] 并不和JS的Number类型强绑定，只确保输入的是合法的数字字符串，和范围、精度解耦，这样的设计适用面是更广的。

### What does the proposed API look like?
```js
<InputNumber stringMode /> 
```
此时value类型始终为string

**Comment by kpaxqin** [comment]
https://github.com/ant-design/ant-design/issues/681

这个模式下InputNumber大数、精度相关的issue都是可解的

**Comment by zombieJ** [comment]
@07akioni  可以来调研一下

**Comment by 07akioni** [comment]
ok

**Comment by 07akioni** [comment]
头大，这里面很多逻辑等同于重写了，牵连的东西挺多。

如果用的是字符串，最后点 step 按钮翻回头计算的还是 double，精度问题还是存在，可能需要引入一个精确计算的库。

**Comment by 07akioni** [comment]
浏览器只负责保证 format 但是并不保证 step，如果引入 step 就会出现计算问题。我觉得如果出现会产生输入风险的场景下，用 InputNumber 并不是一个很好的选择（这种时候不适合再让用户点点点 +- 了），内置的格式化很难满足所有用户的需求。

**Comment by zombieJ** [comment]
特意引入数字库成本略大，看看能不能用 BigInt

**Comment by kpaxqin** [comment]
> 浏览器只负责保证 format 但是并不保证 step，如果引入 step 就会出现计算问题。我觉得如果出现会产生输入风险的场景下，用 InputNumber 并不是一个很好的选择（这种时候不适合再让用户点点点 +- 了），内置的格式化很难满足所有用户的需求。

作为使用者我希望输入框保障给出来的value是合法的number string，同时对用户的体验统一（比如可以像FF一样把用户输入的 , 在value中替换成. ），这是对开发和对用户两端的核心价值。+-操作在stringMode下可以接受拿掉

**Comment by 07akioni** [comment]
BigInt 是没问题的，在上面做一层简单的封装即可，不考虑兼容性的话绝对够用了。

我刚才看了最流行的几个大数运算库，他们的问题是全都写在了一个对象上，没法按需引入。其实 steps 自身只需要四则运算。

首要问题还是得明确什么状况下期望什么样的表现，如果还维持现在的 double 作为 value 的 api，新的功能都会很难完成。

**Comment by 07akioni** [comment]
我现在想了一个方案
  - 采用高精度运算
  - 只接受合法输入 `^\s*\d+(\.\d+)?\s*$`
    - 接受小数位数限制 `^\s*\d+(\.\d{位数})?\s*$`，用于金额
    - 任何状态下不允许不合法的值进入输入框
  - 任何不合法的输入不帮忙做值的转换
    - 例如 start = 0, step = 2, value = 1
  - 返回值是一个高精度对象，valueOf 可以转化为 double，toString()，转化为 string
    - 还包含一个 bigint 对象
    - 包含 10 的幂次作为指数
    - 用户如果在意值的话需要自己转化
  - 默认不区分 `0` 和 `0.00`
    - 不区分的情况下 value.toString() 会 trim 所有没必要的 0 和空格
    - 区分的情况下 value.toString() 会维持输入的值（切掉前后空格）

**Comment by zombieJ** [comment]
InputNumber 有一个 format 支持额外的格式转换。建议是输入 <-> string 的互转，免得 format 里有太多边界情况。

**Comment by Kermit-Xuan** [comment]
`bigint` 是原生的吗？会不会存在兼容问题呢？

**Comment by 07akioni** [comment]
> `bigint` 是原生的吗？会不会存在兼容问题呢？

会存在的，这个是面向未来考虑的，一旦不支持 IE，那 latest 2 version 没有不支持的

**Comment by Kermit-Xuan** [comment]
> > `bigint` 是原生的吗？会不会存在兼容问题呢？
> 
> 会存在的，这个是面向未来考虑的，一旦不支持 IE，那 latest 2 version 没有不支持的

![image](https://user-images.githubusercontent.com/33770367/88021623-6d57f000-cb60-11ea-85e0-bd5793a7a429.png)

目前来看 Safari 是还没有支持的呢

**Comment by 07akioni** [comment]
> > > `bigint` 是原生的吗？会不会存在兼容问题呢？
> > 
> > 
> > 会存在的，这个是面向未来考虑的，一旦不支持 IE，那 latest 2 version 没有不支持的
> 
> ![image](https://user-images.githubusercontent.com/33770367/88021623-6d57f000-cb60-11ea-85e0-bd5793a7a429.png)
> 
> 目前来看 Safari 是还没有支持的呢

是的，所以现在只是搞一个设想。离最后去实现还差很远。

https://github.com/tc39/proposals/blob/master/finished-proposals.md

Proposal 已经 finish 了，未来一定会有的。

**Comment by zombieJ** [comment]
建议是如果存在不合法的值在 onBlur 的时候恢复成之前合法的值，否则用户没办法输入值，比如  `.` -> `.1` -> `-.1` -> `-1.1`。

**Comment by zombieJ** [comment]
另外还需要考虑一下受控下是怎么状态

**Comment by 07akioni** [comment]
你说的好像是，那感觉就是在 blur 的时候跑一次流程，而不是 input change，允许中间状态出问题。

**Comment by Ash000es** [comment]
Hi All, Anyone used the input number and knows how to show the place holder value, right now the default value of 0 number is what the user gets to see. is there a way to override it with the string in place holder ? Thank you!! <InputNumber size='large' type='number' placeholder='adult' style={style} min={0} max={10} defaultValue={0} onChange={props.onChange} />

**Comment by Ash000es** [comment]
<InputNumber size='large' type='number' placeholder='adult' style={style} min={0} max={10} defaultValue={0} onChange={props.onChange} />

**Comment by Ash000es** [comment]
```
<InputNumber size='large' type='number' placeholder='adult' style={style} min={0} max={10} defaultValue={0} onChange={props.onChange} />
```

**Comment by 07akioni** [comment]
> ```
> <InputNumber size='large' type='number' placeholder='adult' style={style} min={0} max={10} defaultValue={0} onChange={props.onChange} />
> ```

As I can see there's no `placeholder` prop, you may open a new issue for feature request.
