### ISSUE TITLE
Form 表单组件如何设置为受控状态

### ISSUE THREAD

**Issue by imhxc** [ant-design/ant-design#25415]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tp0f2?file=/index.js)

### Steps to reproduce
在文档中，我仅找到了 fields 字段是和受控有关的，但是我官方示例中发现，即使将 fields 写死为一个空数组，表单中的输入框依旧可以输入值。

### What is expected?
受控

### What is actually happening?
不受控

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.12 |
| System | macOS |
| Browser | Chrome |

**Comment by yoyo837** [comment]
表单项一旦交给form就是如此，设计如此，你可以不注册给form，自行处理受控，仍然可以放到form的布局里。不给`name`即可。

**Comment by imhxc** [comment]
> 表单项一旦交给form就是如此，设计如此，你可以不注册给form，自行处理受控，仍然可以放到form的布局里。不给`name`即可。
那 `fields` 的作用是什么？

**Comment by yoyo837** [comment]
我理解错了，我以为你说的是抽象的fields，实际你说的API fields

**Comment by imhxc** [comment]
嗯嗯 。我表述的不准确。是 Form 组件 API 中的 `fields`。

**Comment by zombieJ** [comment]
`fields` 是惰性受控，当 `fields` 变化时会将数据同步给 Form。但是如果 `fields` 没有变化则会使用 Form 内置逻辑控制字段。在 v4 中，[不再推荐](https://ant.design/components/form-cn/#components-form-demo-global-state) 将表单内部状态在外部进行管理：

> 通过 `onFieldsChange` 和 `fields`，可以把表单的数据存储到上层组件或者 Redux、dva 中，更多可参考 `rc-field-form` 示例。
> 注意： 将表单数据存储于外部容器并[非好的实践](https://github.com/reduxjs/redux/issues/1287#issuecomment-175351978)，如无必要请避免使用。

ref: https://github.com/reduxjs/redux/issues/1287#issuecomment-175351978

**Comment by HankWang1999** [comment]
> `fields` 是惰性受控，当 `fields` 变化时会将数据同步给 Form。但是如果 `fields` 没有变化则会使用 Form 内置逻辑控制字段。在 v4 中，[不再推荐](https://ant.design/components/form-cn/#components-form-demo-global-state) 将表单内部状态在外部进行管理：
> 
> > 通过 `onFieldsChange` 和 `fields`，可以把表单的数据存储到上层组件或者 Redux、dva 中，更多可参考 `rc-field-form` 示例。
> > 注意： 将表单数据存储于外部容器并[非好的实践](https://github.com/reduxjs/redux/issues/1287#issuecomment-175351978)，如无必要请避免使用。
> 
> ref: [reduxjs/redux#1287 (comment)](https://github.com/reduxjs/redux/issues/1287#issuecomment-175351978)

想问一下，如果一定要实现Form受控，那么这样操作合适吗？
1.事件向上：分为用户输入表单（自然数据流）、修改表单值（举例：表单联动），前者使用Form的API onValuesChange触发onChange，后者处理好值后向上onChange。
2.值向下：useEffect(()=>{form.setFieldsValue(value)},[value])
