### ISSUE TITLE
v4 Progress successPercent is deprecated. Please use success instead

### ISSUE THREAD

**Issue by N00nDay** [ant-design/ant-design#25424]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-j3usv?file=/index.js)

### Steps to reproduce
Add Progress component and do not use successPercent prop

### What is expected?
I expect not to receive a warning when I am not using the prop I am being warned for using

### What is actually happening?
I am being warned for using a prop incorrectly that I am not using

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.12.0 |
| System | Mac Catalina 10.15.5 |
| Browser | Chrome 83.0.4103.116 |

**Comment by fireairforce** [comment]
solved at https://github.com/ant-design/ant-design/pull/25356

**Comment by Jeff909Dev** [comment]
I have the same issue, just using the demo code of `Progress` shows the warning.

**Comment by ApsarasX** [comment]
![image](https://user-images.githubusercontent.com/24390069/86576404-479ce980-bfab-11ea-9d5a-9bb82f166759.png)
我也有同样的问题

**Comment by fireairforce** [comment]
Please Update the antd to `v4.4.1`.
