### ISSUE TITLE
Feature Request: Table: Expandable Row Animation

### ISSUE THREAD

**Issue by bradyallen** [ant-design/ant-design#25427]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Expandable row currently is currently immediate, but a property for rowExpandableSmooth would be a nice polish point while implementing this in the field. If you need an idea for this, a fast expand from source row the background color shape from top to bottom, then fade in content on open could be nice.

### What does the proposed API look like?
property rowExpandableSmooth

**Comment by afc163** [comment]
We may not provide this feature currently.
