### ISSUE TITLE
New feature - Form.Item hidden prop in 4.4.0 release not working

### ISSUE THREAD

**Issue by anastasiap** [ant-design/ant-design#25425]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-ellis-q8jv5?file=/src/App.js)

### Steps to reproduce
Create Form. 
Add Form.Item with hidden prop set to true
Add Input
Field is still visible
No sign of 'hidden' style in console

### What is expected?
Field to be completely invisible and not taking any space.

### What is actually happening?
Field is visible. If you set Input to hidden, Form.Item still takes all the space.

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.12.0 |
| System | Win 7 |
| Browser | Chrome |

**Comment by yoyo837** [comment]
Fixed in #25336
