### ISSUE TITLE
Is there a chance to add tree select filterOption events 3.26.12 version

### ISSUE THREAD

**Issue by SercanBozkurt** [ant-design/ant-design#25421]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Do you have the chance to add tree select filterOption events in 3.26.12 version or how do I do this? There is an "İ" "i" problem in the filter

### What does the proposed API look like?
filterOption events can be added to the tree select component

**Comment by afc163** [comment]
3.x is not maintained any more since may, please upgrade to 4.x
