### ISSUE TITLE
api for handlign disabling dropdown.button independent of dropdown

### ISSUE THREAD

**Issue by mx2323** [ant-design/ant-design#25430]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
right now with the Dropdown.Button, you cannot disable the button and leave the dropdown enabled. you can only disable the entire dropdown and button. 

i would like to allow the user to switch states using the dropdown, and disable the button in certain states.

### What does the proposed API look like?
have an array of keys for 'disabling' the button, that uses the menu overlay keys

**Comment by afc163** [comment]
https://codesandbox.io/s/brave-bush-uimew?file=/index.js
