### ISSUE TITLE
Table 异步函数会被触发两次，当使用 size changer 的时候

### ISSUE THREAD

**Issue by brickspert** [ant-design/ant-design#25434]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/b1af792f](https://riddle.alibaba-inc.com/riddles/b1af792f)

### Steps to reproduce
官方示例：https://ant.design/components/table-cn/#components-table-demo-ajax

点击页码切换器，onChange 会被触发两次。

### What is expected?
只被触发一次

### What is actually happening?
被触发了两次

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.8  |
| System | mac |
| Browser | chrome |

**Comment by AlbertAZ1992** [comment]
前几天遇到同样的问题，antd 升到 4.4 之后会出现，追踪了下原因是： https://github.com/react-component/pagination/pull/272。
看起来 table 的修复需要一段时间，所以我们的解决方法是把 onChange 移到 pagination里，类似这样 https://riddle.alibaba-inc.com/riddles/c0418263，暂时避免法两次请求（官网Demo不大好）

**Comment by fireairforce** [comment]
这里用 pagination 的onChange 不合适，因为这两个 api 的使用场景不太一样，应该还是 table 的 onChange 的调用方法要调整一下吧。

**Comment by AlbertAZ1992** [comment]
@fireairforce 其实现在第一次发的是 current 没有置 1 的 onchange，第二次发的才是 current 置1 的 onShowSizeChange。点到第二页再且 pagesize就能看出来，之前的 test case 有点问题。
更新了两个 pr ，详见描述。
