### ISSUE TITLE
<Table /> 父组件为 <Row /> 时，当数据减少时，界面渲染有 bug

### ISSUE THREAD

**Issue by ystarlongzi** [ant-design/ant-design#2543]
如题，当有如下配置和结构时，并且数据有多变少时，界面渲染会出现 bug。

```
<Row>
  <Table
        // ..... 省略其它配置
        scroll={{y: 300}}/>
</Row>
```

如果 `<Table />` 父组件不是 `<Row />` 就没问题

[查看 demo](http://codepen.io/ystarlongzi/pen/akjvXZ?editors=0010)

**Comment by afc163** [comment]
没发现有什么 bug，是不是 Row 貌似都一样。

**Comment by ystarlongzi** [comment]
@afc163 擦，本地和 demo 都无法重现了

**Comment by afc163** [comment]
🎅

**Comment by benjycui** [comment]
目测是宇宙射线导致的 bug 😄
