### ISSUE TITLE
How to enable tab left & right arrows instead of moreIcon dropdown? 

### ISSUE THREAD

**Issue by zeeshanaligold** [ant-design/ant-design#25435]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It's a bit difficult for visitor to understand if there are more tabs. Even there is no prop to change the moreIcon. so i think it would be great to have arrows button as well.

### What does the proposed API look like?
I would say to keep arrow buttons as it is was in previous version. 
Second is to make moreIcon changeable via prop.

**Comment by afc163** [comment]
It can't, you have to stick in 4.2.x if you prefer left/right button to scroll.

**Comment by zeeshanaligold** [comment]
@afc163 yes, but i need tabs to be swipe able as well specially for mobile devices.

**Comment by 17forever** [comment]
If you want to change moreIcon, you can redefine in renderTabBar.  
For example:
```
<Tabs
    {...tabsProps}
    renderTabBar={(tabBarProps, DefaultTabBar) => {
        return <DefaultTabBar {...tabBarProps} moreIcon={<DoubleRightOutlined />} />
     }}
>
    content
</Tabs>
```

**Comment by eladonline** [comment]
> Member

this is a very bad choice you should keep both options
