### ISSUE TITLE
Modal.confirm没有获取ConfigProvider指定的prefixCls

### ISSUE THREAD

**Issue by MongooseSong** [ant-design/ant-design#25440]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/modal/ConfirmDialog.tsx](https://github.com/ant-design/ant-design/blob/master/components/modal/ConfirmDialog.tsx)

### Steps to reproduce
在外层包裹一层<ConfigProvider prefixCls="test-ant">的时候，内部使用了Modal.confirm的时候，没有应用此contextProps。查看源码证实了此推论。

### What is expected?
期望Modal.comfirm可以自动引用ConfigProvider定义的prefixCls

### What is actually happening?
仍然使用了ant自身的prefix

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | * |
| System | * |
| Browser | * |

---
只能通过强制指定prefixCls的props指定

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/22873#issuecomment-608223331
