### ISSUE TITLE
Table fixed column not working in IE due to position:sticky. Any polyfill or better substitution?

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#25446]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/](https://ant.design/components/table/)

### Steps to reproduce
Column could be fixed in IE

### What is expected?
Column could be fixed in IE

### What is actually happening?
Column could not be fixed in IE

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.12.0 |
| System | Windows |
| Browser | IE |

**Comment by 07akioni** [comment]
How can you use IE on macOS?

**Comment by shuozhang2016** [comment]
sry, its a type

**Comment by afc163** [comment]
You can try https://github.com/wilddeer/stickyfill
