### ISSUE TITLE
 [antd: Progress] `successPercent` is deprecated. Please use `success` instead. 

### ISSUE THREAD

**Issue by baobao12356** [ant-design/ant-design#25453]
![image](https://user-images.githubusercontent.com/22005273/86578262-1d98f680-bfae-11ea-986f-49e512508342.png)

**Comment by yoyo837** [comment]
Duplicated of #25424

**Comment by fireairforce** [comment]
https://github.com/ant-design/ant-design/issues/25424#issuecomment-654128810

**Comment by sauravkhdoolia** [comment]
@fireairforce @yoyo837 This error is still there even in 4.4.2 ... That is very weird. I saw some PRs and Doc changes by @fireairforce but It's weird that the error is still there for `<Progress percent={n} status="active" />`

**Comment by yoyo837** [comment]
Try remove node_modules, package-lock.json or yarn.lock and reinstall it
