### ISSUE TITLE
Table search with highlight

### ISSUE THREAD

**Issue by saresh-krish** [ant-design/ant-design#25455]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q-57471984-searchintable-y0n8h?fontsize=14&file=/src/App.react.js)

### Steps to reproduce
Global search for Antd table

### What is expected?
After search the value , the value will be highlight. 

### What is actually happening?
After search value we cannot what value is searched.

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Google Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

---
After search the global search value will be highlighter.
How  can i use this highlighter NPM - https://www.npmjs.com/package/react-highlight-words  in this global search- https://codesandbox.io/s/q-57471984-searchintable-y0n8h?fontsize=14&file=/src/App.react.js

**Comment by 07akioni** [comment]
Try `rowClassName` to make rows hit highlighted

**Comment by saresh-krish** [comment]
@07akioni 
I need value to highlight not row

**Comment by 07akioni** [comment]
> @07akioni
> I need value to highlight not row

selector can be applied to content

**Comment by saresh-krish** [comment]
@07

> selector can be applied to content

How to apply highlight(selector) in this https://codesandbox.io/s/q-57471984-searchintable-y0n8h?fontsize=14&file=/src/App.react.js table
