### ISSUE TITLE
能不能把样式 结构 和行为分开

### ISSUE THREAD

**Issue by yuu2lee4** [ant-design/ant-design#2545]
就是你们提供一个ant  design的 样式  和结构，最后 可以拿这个东西 和任何其他的比如react或者vue或者jq结合，做出来ant design react版或者vue版 或者jq版、、

**Comment by benjycui** [comment]
问题是没这个人力。。。

胡兴趣可以尝试 PR。

**Comment by wuhaih** [comment]
支持哈，我正想把antd和vue，jq结合，可以讨论下，我的QQ：503970039 黑丝带

**Comment by yuu2lee4** [comment]
@wuhaih  https://github.com/okoala/vue-antd/issues/31
