### ISSUE TITLE
Overflow for vertical menus

### ISSUE THREAD

**Issue by FoxxMD** [ant-design/ant-design#25461]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When a vertical menu is too large for the parent container it will get an overflow indicator menu. Basically the same behavior as when the menu is in `horizontal` mode.

### What does the proposed API look like?
The API would not change.

**Comment by afc163** [comment]
Vertical Menu should have enough space when scroll down in most situations, we may not implement an overflow indicator in that situation.
