### ISSUE TITLE
Table组件的pageSize由大到小选择后报`dataSource`的长度小于`pagination.total`但大于`pagination.pageSize`

### ISSUE THREAD

**Issue by fenglijunnb** [ant-design/ant-design#25466]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Table组件的pageSize由大到小选择后报`dataSource`的长度小于`pagination.total`但大于`pagination.pageSize`

### What does the proposed API look like?
Table组件的pageSize由大到小选择后报`dataSource`的长度小于`pagination.total`但大于`pagination.pageSize`

**Comment by afc163** [comment]
参考一下这个例子的改法：https://github.com/ant-design/ant-design/pull/23560

**Comment by fenglijunnb** [comment]
@afc163 这个例子是普通的table,如果我是protable 的呢

**Comment by afc163** [comment]
建议到 ProTable 的 issues 提问并提供重现。

**Comment by BluesVN** [comment]
> @afc163 这个例子是普通的table,如果我是protable 的呢

一毛一样的问题

**Comment by ycg520520** [comment]
我也遇到了这样的问题。不过只有页面刷新进入就选择pageSize数字最大后面马上选择数字较小的时候才出现

**Comment by hemengke1997** [comment]
+1 protable出现的这个问题
