### ISSUE TITLE
select组件当所选内容过长而显示缩略号时鼠标放上去无法显示完整内容

### ISSUE THREAD

**Issue by guixuefeng101** [ant-design/ant-design#25464]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当所选内容过长时用户可以看到完成内容

### What does the proposed API look like?
加一个showTitle属性，当所选内容过长而显示缩略号时鼠标放上去可以显示完整内容

**Comment by guixuefeng101** [comment]
https://codesandbox.io/s/antd-reproduction-template-nsscj?file=/index.js




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ant Design GitHub Bot"<notifications@github.com&gt;; 
发送时间: 2020年7月7日(星期二) 上午10:40
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "风一样的少年"<1073561754@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] select组件当所选内容过长而显示缩略号时鼠标放上去无法显示完整内容 (#25464)





 
Hello @guixuefeng101. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
你好 @guixuefeng101, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by afc163** [comment]
Fixed in rc-select@11.0.9

**Comment by afc163** [comment]
Fixed in rc-select@11.0.10
