### ISSUE TITLE
Export event parameter types for menu

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#25467]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction code

```tsx
import React, { FC } from 'react';
import { Menu } from 'antd';
// eslint-disable-next-line import/no-extraneous-dependencies
import { MenuInfo } from 'rc-menu/lib/interface';

const Component: FC = props => {
  const onClick = (e: MenuInfo) => {

  }

 return (
   <Menu onClick={onClick} />
 );
}
```

### Steps to reproduce
1. Using typescript
2. Declare an `onClick` event handler

### What is expected?
Has export of `SelectInfo` and `MenuInfo`

### What is actually happening?
No export of `SelectInfo` and `MenuInfo`

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.x |
| System | windows 10 |
| Browser | last |

**Comment by kaysonwu** [comment]
`ClickParam` was exported before, now it is gone.

**Comment by Kermit-Xuan** [comment]
Can you provide reproduce link of codesandbox?

I check the code of `rc-menu`

**Comment by nirvdrum** [comment]
@kerm1it I get the following when I try that:

```
Cannot use namespace 'MenuInfo' as a type.  TS2709
```

I'm not sure how I'm supposed to annotate this click parameter. I'm upgrading from Ant 4.3.4 to 4.12.3 and am running into the `ClickParam` export changing.

**Comment by nirvdrum** [comment]
To work around typing the actual parameter, I'm typing the entire function:

```ts
import { MenuClickEventHandler } from 'rc-menu/lib/interface'

const menuClick: MenuClickEventHandler = ({ key }) => {
  ...
}
```

It stands out a bit because that's not how most of our code is written, but it satisfies the type checker.

**Comment by insertmike** [comment]
Used `// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types` to skip adding the `rc-depenency` just for typescript to work. Can reconsider if it is needed in more places

**Comment by thawinwats** [comment]
import type { MenuProps } from 'antd'

const onClick: MenuProps['onClick'] = (e) => {

}

**Comment by GongT** [comment]
```typescript
import type { MenuProps } from 'antd';
type MenuInfo = Parameters<Exclude<MenuProps['onClick'], undefined>>[0];
```
