### ISSUE TITLE
Ability to render the Button component without the Wave component

### ISSUE THREAD

**Issue by DobrinGanev** [ant-design/ant-design#25462]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The button component is rendered as a child component of the `Wave` component by default. As a user, I want to have an option to `turn off` this wave effect. I can override the attribute `click-animating-without-extra-node='true'` but if you're inspecting the button you will not know why this attribute was added. A clean solution will be to add only attributes that are in use.

### What does the proposed API look like?

```javascript
return isNeedWave ? <Wave>{buttonNode}</Wave> : buttonNode;
```
the `isNeedWave` prop can be defaulted to `true`

**Comment by afc163** [comment]
Try to override less veriable: `@wave-animation-width: 0`

https://github.com/ant-design/ant-design/blob/93c294664a00ffd38eaa3e0e83959026cf4d13c6/components/style/themes/default.less#L862

**Comment by DobrinGanev** [comment]
@afc163 I am guessing this variable will apply to all the components rendered with the `Wave`

**Comment by afc163** [comment]
Yes, it can remove wave style of all components.
