### ISSUE TITLE
Table组件的pageSize由大到小选择后报`dataSource`的长度小于`pagination.total`但大于`pagination.pageSize` 

### ISSUE THREAD

**Issue by fenglijunnb** [ant-design/ant-design#25465]

**Comment by fenglijunnb** [comment]
Reproduction link
Edit on CodeSandbox

Steps to reproduce
1、选择20/page
2、选择10/page

**Comment by yoyo837** [comment]
请带复现连接新建一个issue.

**Comment by rocky-191** [comment]
> Reproduction link Edit on CodeSandbox
> 
> Steps to reproduce 1、选择20/page 2、选择10/page

我也出现类似问题了

**Comment by rocky-191** [comment]
react_devtools_backend.js:4026 Warning: [antd: Table] `dataSource` length is less than `pagination.total` but large than `pagination.pageSize`. Please make sure your config correct data with async mode. 
![image](https://user-images.githubusercontent.com/13551340/172326889-f2eaab7d-1503-44d7-b5c3-6ccc43db9167.png)

**Comment by rocky-191** [comment]
> Reproduction link Edit on CodeSandbox
> 
> Steps to reproduce 1、选择20/page 2、选择10/page

后来你解决了吗这个问题，目前我发现先切换成20条每页，等一会儿，在去切换成10条每页，不能切换的速度太快，就不会报这个错
