### ISSUE TITLE
Select support custom data type option

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#25477]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
自定义标签时， `value` 不应该被指定为 color，因为传递给后端时通常是一个 key

### What does the proposed API look like?
最终希望的效果 [https://codesandbox.io/s/yincangyixuanzexiangbingzidingyixuanzebiaoqian-suhu1?file=/index.js](https://codesandbox.io/s/yincangyixuanzexiangbingzidingyixuanzebiaoqian-suhu1?file=/index.js)

**Comment by kaysonwu** [comment]
`tagRender` 回调函数，就只有 `label` 和 `value` 可以用，对于多彩不是很友好。而且 label 就是 value。实际 label 有什么意义呢？

**Comment by afc163** [comment]
> 而且 label 就是 value

这应该是 Select 多选的 bug，label 没有生效。

https://codesandbox.io/s/yincangyixuanzexiangbingzidingyixuanzebiaoqian-di2h8

<img width="280" alt="image" src="https://user-images.githubusercontent.com/507615/87027002-1d4b6600-c20f-11ea-9f86-abf19c2e7da9.png">

**Comment by CornerSkyless** [comment]
> > 而且 label 就是 value
> 
> 这应该是 Select 多选的 bug，label 没有生效。
> 
 尝试提交了个 PR 修复这个 bug

**Comment by CornerSkyless** [comment]
label 就是 value 是因为每次选中的时候都动态改了下 options，把已经选中的项目从 options 中移除了。然后这个时候 select 组件就无法从 options 中找到每个选中项目的 value 对应的 label 值了。 

https://codesandbox.io/s/yincangyixuanzexiangbingzidingyixuanzebiaoqian-2i9xw?file=/index.js

**Comment by afc163** [comment]
`labelInValue` 就是为这种情况准备的。

**Comment by kaysonwu** [comment]
@afc163 那多彩标签呢？怎么实现？`tagRender` 给的参数还是太少了

**Comment by kaysonwu** [comment]
可以考虑新增个 `fieldNames` 属性，然后 `tagRender` 传递 `option`， 而不是就 `label` 和 `value`，不然多彩标签不够用
