### ISSUE TITLE
Form使用时可以指定数据模型，即目前的Store类型应变成泛型

### ISSUE THREAD

**Issue by leopen-hu** [ant-design/ant-design#25473]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate. #21180 提了相同的问题，但是因为格式问题已经被关闭了

### What problem does this feature solve?
在typescript开发时可以使用类型约束确保数据填充是正确的，比如 initialValues 类型的检查，setFiledsValue；
避免很多函数的强制类型装换，比如onFinish时可以直接指定自己定义好的数据类型而不需要强制转换为Store类型；

### What does the proposed API look like?
const form = Form.useForm<FormValuesType>();

**Comment by afc163** [comment]
Duplicate of #21195
