### ISSUE TITLE
antd 3.x Cascader can not display defaultValue

### ISSUE THREAD

**Issue by ASkyBig** [ant-design/ant-design#25478]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cascader-repaint-lw2b7?file=/index.js)

### Steps to reproduce
nothing need

### What is expected?
show defaultValue

### What is actually happening?
does show defaultValue

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.8.6 |
| System | MacOs Catalina 10.15.3 |
| Browser | 83.0.4103.116（正式版本） （64 位） |

---
4.x work fine

**Comment by afc163** [comment]
3.x is not maintianed anymore, please upgrade to v4.

**Comment by ASkyBig** [comment]
> 3.x is not maintianed anymore, please upgrade to v4.

got it. Tks
