### ISSUE TITLE
Cannot set value when ‘Form.Item name ’ is an array

### ISSUE THREAD

**Issue by lxf001** [ant-design/ant-design#25471]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-omni4)

### Steps to reproduce
https://codesandbox.io/s/antd-reproduction-template-omni4

### What is expected?
set 'name' value

### What is actually happening?
can't set

| Environment | Info |
|---|---|
| antd | undefined |
| React | latest |
| System | win |
| Browser | latest |

**Comment by tnduc** [comment]
try with `name={[i, "a"]}`

**Comment by N00nDay** [comment]
I have updated your codesandbox to show how it is done. https://codesandbox.io/s/antd-reproduction-template-teh8n?file=/index.js:255-310

In a nutshell, add this to your form and swap 'seven' and 'four' with the values you want. `initialValues={{ 0: { a: "seven" }, 1: { a: "four" } }}`

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-4q9h7?file=/index.js

**Comment by lxf001** [comment]
import React from "react";
import ReactDOM from "react-dom";
import { Form, Input, Checkbox } from "antd";
import "antd/dist/antd.css";
import "./index.css";

let arr = [
  {
    check: true,
    faArr: [{ fb: 1, fbArr: [{ fbb: 11 }] }, { fb: 2 }],
  },
  {
    check: false,
    faArr: [{ fb: 3 }, { fb: 4, fbArr: [{ fbb: 44 }, { fbb: 41 }] }],
  },
];

ReactDOM.render(
  <div className="App"&gt;
    {/* How set value */}
    <Form&gt;
      {arr.map((x, i) =&gt; (
        <div&gt;
          <Form.Item name={""}&gt;
            <Checkbox /&gt;
          </Form.Item&gt;
          {x.faArr.map((y, n) =&gt; (
            <div&gt;
              <Form.Item name={""}&gt;
                <Input /&gt;
              </Form.Item&gt;
              {y.fbArr &amp;&amp;
                y.fbArr.map((z, m) =&gt; (
                  <div&gt;
                    <Form.Item name={""}&gt;
                      <Input /&gt;
                    </Form.Item&gt;
                  </div&gt;
                ))}
            </div&gt;
          ))}
        </div&gt;
      ))}
    </Form&gt;
  </div&gt;,
  document.getElementById("root")
);








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 凌晨0:27
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"刘新风"<lxf_dream@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Cannot set value when ‘Form.Item name ’ is an array (#25471)





 
Closed #25471.
