### ISSUE TITLE
AutoComplete component should use name or id as key and not display value when a list of objects is passed in 

### ISSUE THREAD

**Issue by sarahob** [ant-design/ant-design#25479]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The AutoComplete component is using the display value as the key for the list which means that lists with duplicate display values don't get selected correctly even though they may be unique items based on the key. To solve this when the case is object the option key should be a unique identifier.  

### What does the proposed API look like?
For this we need to extend the DataSourceItemObject to to 
```javascript
export interface DataSourceItemObject {
  value: string;
  text: string;
  key: string;
}
```

In the switch statement, for the 'object' case, then we can set the key to the key property. This enables a unique identifier not dependent on the display value. 

```javascript
 case 'object': {
              const { value: optionValue, key: optionKey, text: optionDisplayText } = item as DataSourceItemObject;
              return (
                <Option key={optionKey} value={optionValue}>
                  {optionDisplayText}
                </Option>
              );
            }
```

**Comment by 07akioni** [comment]
When you want value not be identical with displayed value, you should use select.

AutoComplete should be viewed as a better Input. Its view & model should work like an Input.
