### ISSUE TITLE
Receiving a Warning Note when using Dayjs with DatePicker

### ISSUE THREAD

**Issue by N00nDay** [ant-design/ant-design#25489]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-87s2j?file=/DatePicker.js)

### Steps to reproduce
I followed the steps provided on antd website https://ant.design/docs/react/replace-moment#DatePicker but utilized the javascript version https://github.com/xiaohuoni/antd4-generate-picker/tree/master/antd-demo.

### What is expected?
I expect not to receive a warning.

### What is actually happening?
I am receiving the following Warning `Note: Not match any format. Please help to fire a issue about this.`

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.12.0 |
| System | Mac Catalina 10.15.5 |
| Browser | Chrome 83.0.4103.116 |

**Comment by zombieJ** [comment]
@iamkun  pls take a look.

**Comment by iamkun** [comment]
Thanks. Fixed in https://github.com/react-component/picker/pull/102
