### ISSUE TITLE
Provide form components with no logic

### ISSUE THREAD

**Issue by rvsia** [ant-design/ant-design#25485]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In Data Driven Forms (https://data-driven-forms.org/) we want to use Antd React library to build forms using our validation, state management, etc. 

However, form components are currently using https://github.com/react-component/field-form 

We don't want to use it - we just want to use form components without any additional form logic. It is possible to not use it right now - but, the components still import all unnecessary packages and logic, so it makes our applications slower and bundle sizes larger.

We propose to extract all internal form components to separate components, that will just provide styling. Please see the proposed API.

### What does the proposed API look like?
```jsx
import { Form, FormItem, FormItemLabel, FormItemInput } from 'antd';
...
<Form ...>
   <FormItem invalid={invalid} help={error || helperText}>
       <FormItemLabel title={title}/>
       <FormItemInput>
            <Input .... />
        </FormItemInput>
   </FormItem>
   <FormItem>
        ....
   </FormItem>
   ....
</Form>
```

**Comment by afc163** [comment]
Form.Item without `name` is what you want.

````
<Form.Item validateStatus="error" help="message">
```

**Comment by rvsia** [comment]
@afc163 thanks for the quick response but I don’t think this is what I want.

If I use `FormItem` without a name, there is still all this code and imports included:

https://github.com/ant-design/ant-design/blob/master/components/form/FormItem.tsx

Importing rc-field-form etc. just make the application bigger and slower. There are many hooks used. Too much overhead for a layout component.

**Comment by afc163** [comment]
It works in a same way as a static layout component.

It is not in our plan to provide a pure static form component without rc-field-form.
