### ISSUE TITLE
Not focused search input - multiple TreeSelect 

### ISSUE THREAD

**Issue by lexlexa** [ant-design/ant-design#25482]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-select/#components-tree-select-demo-checkable](https://ant.design/components/tree-select/#components-tree-select-demo-checkable)

### Steps to reproduce
1. Clear TreeSelect value
2. Blur
3. Click TreeSelect

### What is expected?
Keyboard is show

### What is actually happening?
Keyboard not show

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.8.6 |
| System | Ios |
| Browser | chrome |

**Comment by lexlexa** [comment]
Also relevant for Select

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/34238#issuecomment-1305018949
