### ISSUE TITLE
Upload组件在win10 Chrome/83.0.4103.116中上传文件，会导致浏览器卡死

### ISSUE THREAD

**Issue by songning0605** [ant-design/ant-design#25496]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-cloud-rub85?file=/src/index.js)

### Steps to reproduce
1、点击上传文件，浏览器即卡死

### What is expected?
上传文件时，浏览器不要卡死

### What is actually happening?
上传文件时，浏览器卡死

| Environment | Info |
|---|---|
| antd | 4.3.4 |
| React | 16.13.1 |
| System | win10 |
| Browser | Chrome/83.0.4103.116 |

**Comment by yoyo837** [comment]
你试试把能复现的目标文件夹内的文件只留一个

**Comment by afc163** [comment]
如何重现？

**Comment by songning0605** [comment]
> 如何重现？

我提供那个Demo仓库，随便选一个文件就会卡死的

**Comment by afc163** [comment]
我这里无法重现。
