### ISSUE TITLE
关于table组件中rowSelection中的fixed属性，控制选择框列固定方向问题？

### ISSUE THREAD

**Issue by yipanhuasheng** [ant-design/ant-design#25495]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pensive-pond-l8v4p?file=/index.js)

### Steps to reproduce
使用table组件时，配置rowSelection中的fixed属性，该属性作用一个布尔值控制“把选择框列固定在左边”，我理解true就是放左边，false放右边吧

### What is expected?
fixed为false时，第一列的选择框放置在table表格的最后一列

### What is actually happening?
不论fixed布尔值true或false，对选择框列没有影响

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 3.x |
| System | macOS 10.15.5 |
| Browser | google chrome 83.0.4103.116（正式版本） （64 位） |

---
没有具体的react版本，我是在官网提供codesandbox上试的，不知道是我没理解这个属性的作用吗？

**Comment by afc163** [comment]
要配合横向滚动：https://codesandbox.io/s/pensive-pond-l8v4p?file=/index.js

**Comment by yipanhuasheng** [comment]
可以详细解释一下吗，老哥，选择框列可以放在最右侧是吧？

**Comment by afc163** [comment]
false 就是不固定，现在不支持放在右边。

**Comment by yipanhuasheng** [comment]
咱们不考虑这个功能吗？选择框列只能放在最左侧有点僵硬啊。

**Comment by afc163** [comment]
目前的设计是这样的，放在右边很奇怪。
