### ISSUE TITLE
[form] Is there any official way to know if a form is pristine?

### ISSUE THREAD

**Issue by dbx834** [ant-design/ant-design#2549]
Hi,

Is there any official way to know if a form is pristine?
PS: 'pristine' means it has just been rendered and there have been no interactions.

Thanks

**Comment by benjycui** [comment]
Nope.

> 'pristine' means it has just been rendered and there have been no interactions.

And I think it's not easy for `antd.Form` to watch all the interactions(`onChange` `onFocus`?) of those form controls in it.

**Comment by benjycui** [comment]
Trace: https://github.com/ant-design/ant-design/issues/4374

It's seems that you can know whether form is touched after these feature are supported.

But I am not sure if it's what you want.
