### ISSUE TITLE
Date picker locale not picking from default value like antd3

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#25497]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-1ynv8b?file=index.js](https://stackblitz.com/edit/react-1ynv8b?file=index.js)

### Steps to reproduce
In AntD 3 version  if we set the global moment locale based on browser language and pass the as default value to DatePicker from moment() the browser locale was picking up as expected.
This was there in old docs

Note: Part of locale of DatePicker, MonthPicker, RangePicker, WeekPicker is read from value. So, please set the locale of moment correctly.

### What is expected?
Based on moment locale the date picker should show the format

The above not was missing and no info on locale from defaultvalue

### What is actually happening?
Browser local is not being picked and it always shows default local which is us.

But AntD4 docs says we have to pass the locale to configProvider to handle locale format. We can't pre import the locale because our locale depends on browser language. There is no option to import based on browser language or no option pass the locale as string to ConfigProvider instead of manually importing

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | any |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
Can you share a online example that works on 3.x but fail in 4.x? I don't realy understand your description.

**Comment by yakkantiraja** [comment]
Apologies for my confusing description. 

here is example for both V3 and V4

Set browser language to en-GB (English - United Kingdom)

V3 datepicker format shows - **07/09/2020** i.e DD/MM/YYYY  which is expected and correct

https://stackblitz.com/edit/react-bv6get?file=index.js

V4 datepicker format shows - **09/07/2020**  i.e MM/DD/YYYY  which is incorrect

https://stackblitz.com/edit/react-fgxm6x?file=index.js

**Comment by afc163** [comment]
> V3 datepicker format shows - 07/09/2020 i.e DD/MM/YYYY which is expected and correct

v3: https://stackblitz.com/edit/react-bv6get-fopc4n?file=index.js

<img width="382" alt="image" src="https://user-images.githubusercontent.com/507615/86991581-0aff0700-c1d2-11ea-9f45-fd6d57eb5b35.png">

> V4 datepicker format shows - 09/07/2020 i.e MM/DD/YYYY which is incorrect

v4: https://stackblitz.com/edit/react-fgxm6x-t4up3z?file=index.js

<img width="380" alt="image" src="https://user-images.githubusercontent.com/507615/86991575-05092600-c1d2-11ea-8605-8af324e73ce3.png">


---

V4 shows **07/09/2020** which I believe it is correct as you described.

**Comment by yakkantiraja** [comment]
Apologies for the typo. V3 is correct and V4 is wrong. 

It should show as V3  ie. 09/07/2020

**Comment by afc163** [comment]
So **DD/MM/YYYY** (v4) is correct? 

![](https://user-images.githubusercontent.com/507615/86991575-05092600-c1d2-11ea-8605-8af324e73ce3.png)

**Comment by yakkantiraja** [comment]
No. Today's date is 9'th July.

So it(V4) should show 09/07/2020. 

But V4 is showing month first which is wrong. 

V3 is correct which is showing Date first.

**Comment by yakkantiraja** [comment]
One more example V3  - correct

![image](https://user-images.githubusercontent.com/8353615/86995535-e314a100-c1db-11ea-892a-49484cb6958f.png)

V4 wrong

![image](https://user-images.githubusercontent.com/8353615/86995550-ef98f980-c1db-11ea-8a39-a42a6874e7df.png)

**Comment by bplemon** [comment]
I too am facing this issue.  I've done all my migration to v4 but this is holding me up from going live as my clients work directly with dates and are across different timezones/countries.

**Comment by chrisque5** [comment]
I am also having this issue of setting dynamic locale

**Comment by yakkantiraja** [comment]
Any update on this bug?

**Comment by pierre-H** [comment]
same problem ... :'(

**Comment by bplemon** [comment]
I'd like an update on this too, it's a breaking change and should be a high priority

**Comment by flyerH** [comment]
Maybe you can try this way before the problem fixd😂

```
const lang = (navigator.language || navigator.languages[0] || 'en-GB').replace('-', '_');
const locale = require(`antd/es/date-picker/locale/${lang}`).default;

const Test = () => {
  return (
    <div>
      version: {version}
      <br />
      <DatePicker defaultValue={moment()} locale={locale} />
    </div>
  );
}
```

**Comment by chrisque5** [comment]
@flyerH that's how we're doing it temporarily. But for a long run, this feature should come back.

**Comment by 07akioni** [comment]
ref https://github.com/ant-design/ant-design/issues/25893

**Comment by afc163** [comment]
@zombieJ Why can't we read locale from moment instance like v3?

**Comment by zombieJ** [comment]
In v4, all component always follow its internal locale config to avoid mixed issue. And this also give the ability to enable multiple locale in one page:
```tsx
moment.locale('zh-cn');

<>
  <ConfigProvider locale={en}>
    <DatePicker />
  </ConfigProvider>

  <ConfigProvider locale={fr}>
    <DatePicker />
  </ConfigProvider>
<>
```

**Comment by yakkantiraja** [comment]
Then we need to have some kind of wild card to import all locales.

In our application(ReactJs) we read the locale from browser and set it globally.

We need some kind of 
 import alllocales from 'antd/es/locales' ;

and then can use **navigator.language** and pass it to the component

 <ConfigProvider locale={alllocales[navigator.language ] }> 
    <DatePicker />
  </ConfigProvider>

@zombieJ  is there any way ?

**Comment by zombieJ** [comment]
You can do like this but need a little fallback when locales file not contain `navigator.language`

**Comment by yakkantiraja** [comment]
@zombieJ  i don't see any option to import "alllocales ".

Is there anything i'm missing in docs?

**Comment by zombieJ** [comment]
@yakkantiraja, you are right. Currently should only pick the locale you need as another module to export by usage. You can use scripts to generate a module file contains all the locale.

**Comment by yakkantiraja** [comment]
Thanks for the confirmation @zombieJ

**Comment by 0707236659** [comment]
> @yakkantiraja, you are right. Currently should only pick the locale you need as another module to export by usage. You can use scripts to generate a module file contains all the locale.

do you have any example :((
