### ISSUE TITLE
InputNumber component - validation check is showing up outside the field.

### ISSUE THREAD

**Issue by bharatn** [ant-design/ant-design#25494]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-river-p34k9?file=/index.js:553-564)

### Steps to reproduce
refer to code above.

### What is expected?
The validation icon should be inside the field

### What is actually happening?
The validation icon is outside the field

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | v16.13.0 |
| System | Mac |
| Browser | Chrome 83.0.4103.116 (didnt check others) |

**Comment by afc163** [comment]
Try https://codesandbox.io/s/confident-microservice-pq9gs?file=/index.js

**Comment by bharatn** [comment]
That doesnt fix the issue entirely. We want to use a reduced width for number fields (90px) and still have enough space to hold error messages. The style your applied limits the entire wrapper resulting in

<img width="120" alt="Screen Shot 2020-07-08 at 7 41 25 AM" src="https://user-images.githubusercontent.com/903589/86932622-753e7b80-c0ee-11ea-9d75-e09cf3e4fefc.png">

What we want is 

<img width="384" alt="Screen Shot 2020-07-08 at 7 42 09 AM" src="https://user-images.githubusercontent.com/903589/86932705-90a98680-c0ee-11ea-92d4-50bfe99241e4.png">

To achieve this, we need separate style props for field and error message area.
