### ISSUE TITLE
Form 表单字段name在使用数字NamePath时，返回结果异常

### ISSUE THREAD

**Issue by qhanw** [ant-design/ant-design#25508]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/bold-dream-qj1dr?file=/index.js)

### Steps to reproduce
1、打开控制台，切到 console
2、输入表单值后，点击提交
3、查看控制台输出，第一项为多项空值数组

### What is expected?
在表单名为数字NamePath 时，表单提交后仍为对象结构。如 {1:{3: 'xi'}, 2:{4: 'si'}}

### What is actually happening?
{1: [undefined, undefined, undefined, {3: 'xi'}], 2: {4: 'si'}}
如下图：
![image](https://user-images.githubusercontent.com/10607656/86914540-15c68700-c153-11ea-81c2-2daa946295ac.png)

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.13.1 |
| System | mac os mojave v10.14.6 |
| Browser | chrome v83.0.4103.116 |

---
antd 文档给出可以使用数字

**Comment by zombieJ** [comment]
数字在 store 中没有确定类型时优先转为数组，我文档更新一下。
