### ISSUE TITLE
TreeSelect- asynchronous loadData callback is triggering twice in strict mode

### ISSUE THREAD

**Issue by apdroid** [ant-design/ant-design#25504]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/throbbing-dust-b3dy8)

### Steps to reproduce
1. Use react in strict mode
2. Add tree select component
3. For async loading, loadData callback triggers twice

### What is expected?
loadData callback should trigger only once

### What is actually happening?
loadData callback is triggering twice

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | React v16.13.1 |
| System | Windows 10 |
| Browser | Chrome Version 83.0.4103.116 |

**Comment by zombieJ** [comment]
https://github.com/facebook/react/issues/15074

**Comment by apdroid** [comment]
I removed setState dependency from the code, now it's raw treeSelect component with simple loadData function. Still, the loadData is triggered twice.

[![Edit keen-sun-bvon9](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-sun-bvon9?fontsize=14&hidenavigation=1&theme=dark)
