### ISSUE TITLE
Select在下拉列表弹出的时候，下拉框右侧箭头图标没有了交互（默认向下，下拉框列表弹出图标向上）

### ISSUE THREAD

**Issue by overcastsky** [ant-design/ant-design#25506]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
点击下拉框

### What is expected?
下拉框右侧图标有交互效果

### What is actually happening?
无论下拉列表弹出还是收起，图标都是向下，没有任何交互

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | react |
| System | macOs |
| Browser | Chrome |

**Comment by afc163** [comment]
It is by designed: https://github.com/ant-design/ant-design/pull/23468
