### ISSUE TITLE
Carousel走马灯，以及react-slick的bug

### ISSUE THREAD

**Issue by chairui2001** [ant-design/ant-design#2550]
#### 本地环境

- antd 版本: 1.6.3
- 操作系统及其版本：win7 64位旗舰
- 浏览器及其版本:  chrome 版本 45.0.2454.99 (64-bit)

#### 你做了什么？

查看Carousel走马灯示例，进而观看react-slick的示例，发现bug

#### 你期待的结果是：

正常运行

#### 实际上的结果：

将浏览器窗口化并改变窗口宽度，来回几次，发现自动滚动播放的效果停止，而且也无法点击小按钮来切换

#### 可重现的在线演示

http://webrafter.com/opensource/react-slick

**Comment by benjycui** [comment]
react-slick 的 bug https://github.com/akiran/react-slick/issues/337 。

**Comment by benjycui** [comment]
其实基于 Ant Motion 重做一个 rc-carousel 可行么？ @afc163 @jljsj33 

react-slick 感觉基本不维护了，伤者的 GitHub 活跃度也很低。。。

**Comment by afc163** [comment]
其实 @jljsj33 已经搞了一个。https://github.com/react-component/banner-anim

**Comment by chairui2001** [comment]
谢谢回复，很有帮助

**Comment by zhangda47** [comment]
1.11.0 antd 已经更新react-slick至0.13，使用时在chrome 52上必须调整一次浏览器大小才能使轮播图适应宽度，其他浏览器好像没这个问题。https://github.com/akiran/react-slick/issues/370

**Comment by 727177817** [comment]
@zhangda47   我的也是这个问题，而且所有浏览器都是，slick版本试了好几个都不能解决，请问你的解决了吗

**Comment by zhangda47** [comment]
@727177817 我换成了ant的动画组件，[banner-anim](http://motion.ant.design/components/banner-anim)

**Comment by afc163** [comment]
https://github.com/akiran/react-slick/issues/543
