### ISSUE TITLE
Draggable Slider Range

### ISSUE THREAD

**Issue by OlivierKamers** [ant-design/ant-design#25517]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
A similar issue is this one: https://github.com/ant-design/ant-design/issues/12585 but the resolution is to use a charting library which is not relevant to our use case.

### What problem does this feature solve?
A range has been set on the Slider component that the user then wants to "move around" between the min and max values. 
Instead of changing the extent of the current range when clicking on the slider, it allows dragging it between the min and max.

This behaviour is also implemented by the (deprecated) react-input-range library: https://github.com/davidchin/react-input-range#draggabletrack-boolean

An example application is looking at thermal data. The photos have a certain temperature range. To improve the visibility of certain features the user should look at a temparature range of 20 degrees difference. However the position of this range changes between photos. The user should be able to easily move the range from `[10, 30]` to `[50, 70]` for example without having to change the min from 10 to 50 and the max from 30 to 70.

### What does the proposed API look like?
An additional property on the Slider component `draggableTrack`.

Example:
```
<Slider range draggableTrack defaultValue={[20, 50]}  />
```

**Comment by 07akioni** [comment]
Try the workaround

https://codesandbox.io/s/elated-ritchie-j4gkt

**Comment by OlivierKamers** [comment]
Thank you for proposing that workaround. 
It is however not the behaviour that we are looking for. It should still be possible to change the (size of the) range by dragging the handles at the end and the range should be draggable when clicking+holding the blue track bar between the handles.
It might be possible to implement this using a similar workaround, but I hope it's something that can be valuable as a supported behaviour in the component library.

**Comment by jljsj33** [comment]
标给我干嘛，，，我是来找用法的，，，又要我卖力？？

**Comment by jljsj33** [comment]
https://github.com/react-component/slider/pull/722
