### ISSUE TITLE
[Table/Pagination] An error occurs when the showTotal parameter is 0

### ISSUE THREAD

**Issue by leezng** [ant-design/ant-design#25526]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/young-waterfall-fzk1f?file=/index.js)

### Steps to reproduce
```
pagination={{
    showTotal: total => `共${total}条`,
    total: data.length - 1, // data.length = 1
}}
```

### What is expected?
total = 0

### What is actually happening?
total = 1

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | Latest |
| System | macOS Mojave |
| Browser | Google Chrome Latest |

**Comment by 07akioni** [comment]
Maybe it's a bug of pagination 

https://codesandbox.io/s/lucid-benz-7qtfi?file=/index.js

**Comment by 07akioni** [comment]
by the way, your antd version in codesandbox is 3.6.2, not 4.4.1

**Comment by leezng** [comment]
changed to antd4. the same on 3 and 4.

**Comment by Kermit-Xuan** [comment]
I will work it.

**Comment by Kermit-Xuan** [comment]
@leezng 

``` js
// ============ Basic Pagination Config ============
  const mergedPagination = extendsObject<Partial<TablePaginationConfig>>(
    innerPagination,
    paginationObj,
    {
      total: paginationTotal > 0 ? paginationTotal : total,
    },
  );
```

This is logic from the table component in `antd`.

It will read the length of `dataSource` if the `total` of pagination is less than 0.

**Comment by Kermit-Xuan** [comment]
This can be closed if it don't have to modify. @afc163

**Comment by Kermit-Xuan** [comment]
This is not a bug, it will reopen if need.

**Comment by arocki7** [comment]
@leezng, Since you are calling pagination as an object from Table, you will need to make it like the below.

```showTotal: (total) => `Total ${total} items` ```
