### ISSUE TITLE
npm install错误Can't find package omit.js

### ISSUE THREAD

**Issue by MangGoDio** [ant-design/ant-design#25524]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://yunhu-stage.oss-cn-hangzhou.aliyuncs.com/mehealth/2020-07-09/926fb9cf30bd4f6bb354df074daae214.png](https://yunhu-stage.oss-cn-hangzhou.aliyuncs.com/mehealth/2020-07-09/926fb9cf30bd4f6bb354df074daae214.png)

### Steps to reproduce
 npm run build

### What is expected?
打包成功

### What is actually happening?
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "cd /tmp/npm-build-cloud-clinic && cnpm install", "delta": "0:00:25.361368", "end": "2020-07-09 09:22:39.197452", "msg": "non-zero return code", "rc": 1, "start": "2020-07-09 09:22:13.836084", "stderr": "platform unsupported umi@2.13.13 › umi-ui@1.5.6 › react-dev-utils@9.0.1 › fork-ts-checker-webpack-plugin@1.1.1 › chokidar@2.1.8 › fsevents@^1.2.7 Package require os(darwin) not compatible with your platform(linux)\n[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(linux)\nplatform unsupported umi-plugin-react@1.15.8 › webpack@4.41.1 › watchpack@1.7.2 › chokidar@3.4.0 › fsevents@~2.1.2 Package require os(darwin) not compatible with your platform(linux)\n[fsevents@~2.1.2] optional install error: Package require os(darwin) not compatible with your platform(linux)\n\nWARN node unsupported \"node@v10.16.3\" is incompatible with umi-plugin-react@1.15.8 › webpack@4.41.1 › watchpack@1.7.2 › watchpack-chokidar2@^2.0.0, expected node@<8.10.0\n✖ Install fail! Error: [antd@4.4.1 › rc-mentions@1.3.0 › rc-menu@8.5.0 › omit.js@^2.0.0] Can't find package omit.js@^2.0.0\nError: [antd@4.4.1 › rc-mentions@1.3.0 › rc-menu@8.5.0 › omit.js@^2.0.0] Can't find package omit.js@^2.0.0\n    at resolve (/usr/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:80:11)\n    at resolve.next (<anonymous>)\n    at onFulfilled (/usr/lib/node_modules/cnpm/node_modules/co/index.js:65:19)\n    at /usr/lib/node_modules/cnpm/node_modules/co/index.js:54:5\n    at new Promise (<anonymous>)\n    at co (/usr/lib/node_modules/cnpm/node_modules/co/index.js:50:10)\n    at toPromise (/usr/lib/node_modules/cnpm/node_modules/co/index.js:118:63)\n    at next (/usr/lib/node_modules/cnpm/node_modules/co/index.js:99:29)\n    at onFulfilled (/usr/lib/node_modules/cnpm/node_modules/co/index.js:69:7)\n    at /usr/lib/node_modules/cnpm/node_modules/co/index.js:54:5\nnpminstall version: 3.27.0\nnpminstall args: /usr/bin/node /usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/var/lib/jenkins/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org", "stderr_lines": ["platform unsupported umi@2.13.13 › umi-ui@1.5.6 › react-dev-utils@9.0.1 › fork-ts-checker-webpack-plugin@1.1.1 › chokidar@2.1.8 › fsevents@^1.2.7 Package require os(darwin) not compatible with your platform(linux)", "[fsevents@^1.2.7] optional install error: Package require os(darwin) not compatible with your platform(linux)", "platform unsupported umi-plugin-react@1.15.8 › webpack@4.41.1 › watchpack@1.7.2 › chokidar@3.4.0 › fsevents@~2.1.2 Package require os(darwin) not compatible with your platform(linux)", "[fsevents@~2.1.2] optional install error: Package require os(darwin) not compatible with your platform(linux)", "", "WARN node unsupported \"node@v10.16.3\" is incompatible with umi-plugin-react@1.15.8 › webpack@4.41.1 › watchpack@1.7.2 › watchpack-chokidar2@^2.0.0, expected node@<8.10.0", "✖ Install fail! Error: [antd@4.4.1 › rc-mentions@1.3.0 › rc-menu@8.5.0 › omit.js@^2.0.0] Can't find package omit.js@^2.0.0", "Error: [antd@4.4.1 › rc-mentions@1.3.0 › rc-menu@8.5.0 › omit.js@^2.0.0] Can't find package omit.js@^2.0.0", "    at resolve (/usr/lib/node_modules/cnpm/node_modules/npminstall/lib/download/npm.js:80:11)", "    at resolve.next (<anonymous>)", "    at onFulfilled (/usr/lib/node_modules/cnpm/node_modules/co/index.js:65:19)", "    at /usr/lib/node_modules/cnpm/node_modules/co/index.js:54:5", "    at new Promise (<anonymous>)", "    at co (/usr/lib/node_modules/cnpm/node_modules/co/index.js:50:10)", "    at toPromise (/usr/lib/node_modules/cnpm/node_modules/co/index.js:118:63)", "    at next (/usr/lib/node_modules/cnpm/node_modules/co/index.js:99:29)", "    at onFulfilled (/usr/lib/node_modules/cnpm/node_modules/co/index.js:69:7)", "    at /usr/lib/node_modules/cnpm/node_modules/co/index.js:54:5", "npminstall version: 3.27.0", "npminstall args: /usr/bin/node /usr/lib/node_modules/cnpm/node_modules/npminstall/bin/install.js --fix-bug-versions --china --userconfig=/var/lib/jenkins/.cnpmrc --disturl=https://npm.taobao.org/mirrors/node --registry=https://r.npm.taobao.org"], "stdout": "", "stdout_lines": []}

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.8.6 |
| System | windows 10 |
| Browser | 79.0 |

**Comment by gopep9** [comment]
试下改用yarn吧，刚刚也遇到类似的错误

**Comment by afc163** [comment]
cnpm 没有同步 npm，不是 antd 的问题。

**Comment by yoyo837** [comment]
https://npm.taobao.org/sync/包名 

执行同步

**Comment by CrystalLiu123** [comment]
yarn解决，同步cnpm未解决
