### ISSUE TITLE
select加上showSearch属性后，输入完文字按回车会清空之前得内容

### ISSUE THREAD

**Issue by Wtianliang** [ant-design/ant-design#25535]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
直接在select输入框写完文字按回车

### What is expected?
按回车不要清空内容

### What is actually happening?
按回车会清空内容，并且选择了一个内容后按回车会回显上一个选择得内容

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.12.0 |
| System | macos |
| Browser | chrome最新版本 |

**Comment by afc163** [comment]
`autoClearSearchValue={false}`

**Comment by Wtianliang** [comment]
> `autoClearSearchValue={false}`

```
<Select
                            onClick={() => {
                                if (openSelectArea) {
                                    this.setState({openSelectArea: false});
                                }
                            }}
                            onSelect={this.handleChange}
                            showSearch
                            placeholder="请输入查询内容"
                            style={{width: 200}}
                            showArrow={false}
                            filterOption={false}
                            onSearch={this.handleSearch}
                            autoClearSearchValue={false}
                            notFoundContent={null}>
                            {options}
                        </Select>
```
- 这是代码，加上autoClearSearchValue=true了没有起效果
- 文档上  是否在选中项后清空搜索框，只在 mode 为 multiple 或 tags 时有效
- 我得mode没有设置为multiple 或 tags

**Comment by afc163** [comment]
你的需求是啥，感觉你需要的是 AutoComplete 而不是 Select。

**Comment by Wtianliang** [comment]
> 你的需求是啥，感觉你需要的是 AutoComplete 而不是 Select。

嗯，按业务需求确实AutoComplete更合适，这个项目已经迭代很久了这块一直用的Select组件
因为需求需要月份rangpicker选择时间能够禁用显示灰色   这几天刚升级到4.0其他组件就有问题了。。。

**Comment by Wtianliang** [comment]
感谢作者得建议，已经改成AutoComplete了

**Comment by lsh6372** [comment]
遇到了同样的问题，确实AutoComplete更合适~
