### ISSUE TITLE
Tooltip missing on Dropdown selected value on Mouse Over

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#25537]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-wpedz8?file=index.js](https://stackblitz.com/edit/react-wpedz8?file=index.js)

### Steps to reproduce
Mouseover on the the selected value on Dropdown. 

### What is expected?
It should show tooltip  with selected value

### What is actually happening?
Not showing the tooltip in V4. 

V3 is working fine

https://stackblitz.com/edit/react-fn2524?file=index.js

V4 not working 

https://stackblitz.com/edit/react-wpedz8?file=index.js

It seems html "title" property missed on selected text div/span in V4 

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | any |
| System | any |
| Browser | any |

---

**Comment by yakkantiraja** [comment]
V3 looks like this
![image](https://user-images.githubusercontent.com/8353615/87006313-0d258d80-c1f3-11ea-9cfc-ff16c6056e97.png)

But V4 looks like 
![image](https://user-images.githubusercontent.com/8353615/87006382-28909880-c1f3-11ea-9d29-dd2b524e314a.png)

**Comment by afc163** [comment]
Fixed in rc-select@11.0.10
