### ISSUE TITLE
Bug in Form.List  when using <Select />

### ISSUE THREAD

**Issue by eduilson** [ant-design/ant-design#25532]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-dynamic-form-items](https://ant.design/components/form/#components-form-demo-dynamic-form-items)

### Steps to reproduce
Insert a <Select /> into an list item

### What is expected?
Standard form behavior

### What is actually happening?
The Console displays the following Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `isPropagationStopped` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.

When clicking on the submission form, an error or bug occurs when trying to retrieve items from the list

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google Chrome |

![image](https://user-images.githubusercontent.com/23145787/86995170-abc3d700-c17e-11ea-9fc5-9694ba9dfb24.png)
![image](https://user-images.githubusercontent.com/23145787/86995225-ce55f000-c17e-11ea-8069-194fa39359ce.png)

**Comment by gsaidy** [comment]
I came across the same error in the console when using `Form.List`

I had the following code
```
<Form.List name={[parentName, 'options']}>
  {(fields, { add, remove }) => (
    <>
      {fields.map((field, index) => (
        <AttributeOption
          key={field.key}
          index={index}
          removeOption={() => remove(field.name)}
        />
      ))}
      <AddOptionButton addOption={add} />
    </>
  )}
</Form.List>
```

Replacing `addOption={add}` with `addOption={() => add()}` fixed the issue for anyone who has/will have this issue.

**Comment by fgblomqvist** [comment]
This is the same issue as #24698 (and yes, the solution is indeed to not pass the add function straight to a button). It has to do with the fact that onX event handlers get passed various parameters, and I guess the add function assumes that's data and therefore adds it to the form instance.
