### ISSUE TITLE
Select远程搜索功能在已有选中项时，再搜索，之后关闭下拉框，select文本会变成value值，不再是label或者optionLabelProp对应的值（options的value和label不同）

### ISSUE THREAD

**Issue by rocketsbigfan** [ant-design/ant-design#25549]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-meitner-r5iyu?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1.先随便搜索一个值，并选中
2.搜索其他值，jsonp返回结果中不包含之前选中的项
3.点击屏幕其他地方，收起下拉框

### What is expected?
在不重新选中的情况下，select展现的项目应该是value对应的label或者optionLabelProp对应的值

### What is actually happening?
select显示的是value值

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.8.6 |
| System | window10 |
| Browser | chrome最新版 |

---

**Comment by rocketsbigfan** [comment]
问题相应图片
![1594293239(1)](https://user-images.githubusercontent.com/20547894/87033538-f85bf080-c218-11ea-91e3-6f4ff2726e1e.jpg)


在没有查询到相应搜索内容后，sho收起下拉框，select显示的值，如图

![1594293428(1)](https://user-images.githubusercontent.com/20547894/87033576-0ad62a00-c219-11ea-81b9-521264039b32.jpg)

**Comment by rocketsbigfan** [comment]
还请帮忙解答一下

**Comment by zombieJ** [comment]
试了一下是好的，具体是什么步骤？

![Kapture 2020-07-09 at 22 20 12](https://user-images.githubusercontent.com/5378891/87051618-62cd5a80-c232-11ea-94bc-7f1b58b8e8c0.gif)

**Comment by rocketsbigfan** [comment]
> 试了一下是好的，具体是什么步骤？
> 
> ![Kapture 2020-07-09 at 22 20 12](https://user-images.githubusercontent.com/5378891/87051618-62cd5a80-c232-11ea-94bc-7f1b58b8e8c0.gif)

不好意思，您是通过我上面的链接操作的嘛，如果是的话，其中的圈出的value和label，是否是相同的值，如果是的话，麻烦你设置下value: r[1]，在相同的操作试试
![image](https://user-images.githubusercontent.com/20547894/87054691-0409e000-c236-11ea-80cb-ada62237fd19.png)

**Comment by rocketsbigfan** [comment]
> 试了一下是好的，具体是什么步骤？
> 
> ![Kapture 2020-07-09 at 22 20 12](https://user-images.githubusercontent.com/5378891/87051618-62cd5a80-c232-11ea-94bc-7f1b58b8e8c0.gif)

家里网不好，谅解一下，谢谢

**Comment by rocketsbigfan** [comment]
> 试了一下是好的，具体是什么步骤？
> 
> ![Kapture 2020-07-09 at 22 20 12](https://user-images.githubusercontent.com/5378891/87051618-62cd5a80-c232-11ea-94bc-7f1b58b8e8c0.gif)

![演示](https://user-images.githubusercontent.com/20547894/87102995-4f4bdf00-c286-11ea-81bc-f32cf61f1156.gif)
我将value: r[0] 修改成了value: r[1]得到的结果是这样的

**Comment by zombieJ** [comment]
升级一下 antd 版本：https://codesandbox.io/s/tender-dirac-p0577
