### ISSUE TITLE
Antd Form Input field validation

### ISSUE THREAD

**Issue by saresh-krish** [ant-design/ant-design#25547]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-validation-3yd07?file=/index.js)

### Steps to reproduce
form Input field length validation

### What is expected?
Input field minimum length without a required field

### What is actually happening?
Input field is not required , if i submit without entering the value i got this error 'Validation error on field 'username''

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Google Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

---
Form Input minimum length validation and the field is not required

**Comment by zombieJ** [comment]
Submit will trigger validate but `username` is `undefined` which crash on the `value.length`:

```diff
--- validator(rule) {
+++ validator(rule, value = '') {
```

**Comment by saresh-krish** [comment]
> Submit will trigger validate but `username` is `undefined` which crash on the `value.length`:
> 
> ```diff
> --- validator(rule) {
> +++ validator(rule, value = '') {
> ```

@zombieJ Thank you

**Comment by utkuegeerol** [comment]
@zombieJ Thank you,

you are the man  

:)
