### ISSUE TITLE
More customize support for size on TimeLine

### ISSUE THREAD

**Issue by hydRAnger** [ant-design/ant-design#25545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
if use a bigger customized dot in TimeLine.Item, will overlap with the content
![image](https://user-images.githubusercontent.com/1228449/87024106-a795c900-c213-11ea-8e9b-1a5555e87e97.png)
seems caused by calculation of content's margin(https://github.com/ant-design/ant-design/blob/master/components/timeline/style/index.less#L84).

### What does the proposed API look like?
Currently, it's difficult to style this(need some tricky hack)
If necessary, I can make a PR for this.

**Comment by 07akioni** [comment]
try

https://codesandbox.io/s/intelligent-paper-i4mxi?file=/index.css

**Comment by hydRAnger** [comment]
> try
> 
> https://codesandbox.io/s/intelligent-paper-i4mxi?file=/index.css

thanks~ Yes, I know hacking on style can fix it, just curious if it's necessary for supporting on API level (I mean don't touch things like `.ant-timeline-item-content`)

**Comment by 07akioni** [comment]
In my point of view it's not very necessary for support in API level. since the hack is not very tricky (for example, touch unstable element class name, or need many lines of css to override the style)

**Comment by hydRAnger** [comment]
> In my point of view it's not very necessary for support it in API level. since the hack is not very tricky (for example, touch unstable element class name, or need many lines of css to override the style)

Thanks~ for the API level, or just provide some 'className' or 'style' support for the 'item-content'? (because item-content was generated by antd/TimeLine, currently there is no interface to styling it), maybe `.ant-timeline-item-content` is a little too low-level?(just my thought, not very sure)

**Comment by 07akioni** [comment]
If you don't want to touch css, this could be a workaround.
```jsx
<Timeline.Item>
  <CustomWrapperWithMargin>content</CustomWrapperWithMargin>
</Timeline.Item>
```
`<Timeline.Item contentStyle={...} />` could be a new API for the case. However I'm not sure we will create a new API for this.

**Comment by hydRAnger** [comment]
emmm...sure...need to consider if a new API like contentStyle is necessary...~
