### ISSUE TITLE
Modal jumps out of screen

### ISSUE THREAD

**Issue by urrri** [ant-design/ant-design#25554]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modal-out-of-screen-6vv7l)

### Steps to reproduce
1.Create modal,
2.Add props: centered and width=1000 (should be more than 768)
3.Open modal and change browser width from > 1000 to <1000 and then <768

### What is expected?
Modal should remain in the middle of the screen

### What is actually happening?
when screen width becomes <1000 (defined modal width) it jumps down out of screen and scroll bar appears

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.12 |
| System | windows |
| Browser | chrome 83 |

---
- it happens also in version 3.*
- possible solution:
```less
.ant-modal-centered {
  white-space: nowrap; // prevent wrapping modal after :before element, that has screen height
  > .ant-modal {
    white-space: normal; // restore wrapping for internal elements
  }
}
```

**Comment by 07akioni** [comment]
`<modal><vertical-aligner><modal-body></modal>`

`<modal-body>` is line wrapped when screen has no space.
