### ISSUE TITLE
Sortable table demo not correct

### ISSUE THREAD

**Issue by shaodahong** [ant-design/ant-design#25556]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler](https://ant.design/components/table-cn/#components-table-demo-drag-sorting-handler)

### Steps to reproduce
try to drag twice

![Kapture 2020-07-10 at 10 29 36](https://user-images.githubusercontent.com/14831261/87110081-c2f6e780-c298-11ea-8a95-54775e0d8463.gif)

### What is expected?
correct

### What is actually happening?
not correct

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.13.0 |
| System | Mac OS X |
| Browser | chrome 75.0.3770.100  |

**Comment by xrkffgg** [comment]
我怎么感觉以前是好的呢 😂

**Comment by Yunfly** [comment]
我来改下这个吧

**Comment by Yunfly** [comment]
感觉是索引乱了，表现有点不正常

**Comment by shaodahong** [comment]
Awesome! Please feel free to reach out if you have any questions.

**Comment by souldjl** [comment]
这个能支持树形table拖拽吗，看了下move-array 好像不支持，文档中也没有写清楚的
