### ISSUE TITLE
想从3升级到4，但icon的break change实在绕不过

### ISSUE THREAD

**Issue by vipcxj** [ant-design/ant-design#25559]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
如题，在我们这有使用字符串动态引用icon的需求，但是4中不同icon变成独立的组件，没办法使用type属性来动态得到Icon了，这个该怎么解决？

### What does the proposed API look like?
提供一个兼容3的利用字符串动态引用Icon的方案

**Comment by yoyo837** [comment]
搜索相关issue，有，把所有需要的一次性引入map管理起来

**Comment by afc163** [comment]
https://pro.ant.design/blog/antd-4.0-cn

https://github.com/ant-design/ant-design/issues/20668

**Comment by darrenliuwei** [comment]
> https://pro.ant.design/blog/antd-4.0-cn
> 
> #20668

这个链接点开是空白的
![image](https://user-images.githubusercontent.com/10508248/217127916-67fdebe2-85f5-47c6-84d4-4617531e9eb8.png)
