### ISSUE TITLE
Carousel in Space has error

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#25552]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-tereshkova-02us3?file=/index.js:840-848)

### What is expected?
Carousel normal

### What is actually happening?
Carousel error

**Comment by zombieJ** [comment]
<img width="585" alt="截屏2020-07-09 下午10 28 40" src="https://user-images.githubusercontent.com/5378891/87052616-8ba21f80-c233-11ea-8361-de1ca500ad58.png">

**Comment by xrkffgg** [comment]
Year, I also found the `width` is abnormal

**Comment by zombieJ** [comment]
Space 原本就是 `inline-flex` 布局，内部元素不设置宽度感觉也不能算是 bug。

**Comment by xrkffgg** [comment]
我也没试出好的办法，先这样吧 😂😂
