### ISSUE TITLE
Cannot update Table Scrollbar style

### ISSUE THREAD

**Issue by taranlabana** [ant-design/ant-design#25555]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am trying to change the style of the scrollbar of antTable. 

I am using AntD Table in react application
and trying to apply style as:

```
[class*='ant-table-body'] {
        ::-webkit-scrollbar {
            height: 8px;
            width: 8px;
        }

        ::-webkit-scrollbar-track {
            background: transparent;
        }

        ::-webkit-scrollbar-thumb {
            background-color: rgba(#333, .2);
            border: 3px solid transparent;
            border-radius: 4px;
        }
}
```
Also tried with `.ant-table-body` but got no success.

Can someone suggest me how to implement it?

**Comment by 07akioni** [comment]
could you please add a reproduction link?

**Comment by taranlabana** [comment]
## Reproduction Link
https://codepen.io/taranlabana/pen/BajVRLm?editors=0100

**Comment by yoyo837** [comment]
Your code can not works.

![image](https://user-images.githubusercontent.com/6134547/87179055-b3b38080-c310-11ea-9715-244b35e5b428.png)

It's css not less/scss.

**Comment by giorgiveego** [comment]
Same, not updating styles

**Comment by YuvalPeretz** [comment]
The solution for me was to add this:
```
.ant-table-body {
  scrollbar-width: auto;
  scrollbar-color: auto;
}
```

Then you can add customizations
