### ISSUE TITLE
Menu组件onClick事件原本TS输入参数类型ClickParam不见了

### ISSUE THREAD

**Issue by sujingclg** [ant-design/ant-design#25569]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/commit/e4bbc8fcb3fdd1f8aee6c17c15f2b566f415287e#diff-b5d7ebd6926cbb3981c237f2e491be13](https://github.com/ant-design/ant-design/commit/e4bbc8fcb3fdd1f8aee6c17c15f2b566f415287e#diff-b5d7ebd6926cbb3981c237f2e491be13)

### Steps to reproduce
无

### What is expected?
有ClickParam类型参数方便引入

### What is actually happening?
ClickParam被删除了

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.13.1 |
| System | Mac |
| Browser | Chrome |

**Comment by yoyo837** [comment]
ref: #25467 #25468
