### ISSUE TITLE
Named import from json will be deprecated from webpack 5

### ISSUE THREAD

**Issue by otakustay** [ant-design/ant-design#25566]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/3.x-stable/components/version/index.tsx](https://github.com/ant-design/ant-design/blob/3.x-stable/components/version/index.tsx)

### Steps to reproduce
1. `import {Button} from 'antd'`;
2. build it with webpack@5

### What is expected?
No warning or error is produced

### What is actually happening?
Getting a warning message:

```
 warning  in ./node_modules/antd/es/version/index.js

Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)
```

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.1 |
| System | macOS |
| Browser | Chrome |

---
It seems webpack@5 is planning to depreacted named import from json files, we'd better change `import {version} from '../../package.json` to `import packageInfo from '../../package.json'

**Comment by afc163** [comment]
3.x is not maintianed any more, please upgrade to 4.x.

**Comment by vnguyen94** [comment]
@afc163 why can't this be backported to 3.x? it's a two-line change, and migrating to 4.x requires a lot more work than the proposed fix.
