### ISSUE TITLE
Select with custom Option is behaving not correctly

### ISSUE THREAD

**Issue by miyamirz** [ant-design/ant-design#25576]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-leakey-7qhx3?file=/index.js)

### Steps to reproduce
1.type 'b' in select input, and select first option (Bob). The tag (bob@gmail.com) is rendered.
2.now again type 'b', OBSERVE THE TAG behaviour..It changes from bob@gmail.com to Bob.

### What is expected?
the tag should be consistent and does not change

### What is actually happening?
the tag is changing 

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.12 |
| System | Mac |
| Browser | Chrome |

**Comment by Yunfly** [comment]
this is because default optionLabelProp is children. when prop.data changed it render option.children as default. 
to fix it, one can set optionLabelProp="value" 
like this: https://codesandbox.io/s/stupefied-bohr-r368h?file=/index.js

**Comment by miyamirz** [comment]
Cool. got it. Thanks @Yunfly

**Comment by miyamirz** [comment]
@Yunfly I have mode="tags" , Can i render the entire node in the Options for already selected values?
For example 
1. i type 'b' and select bob@gmail.com.
2.Now i type 'j' and the option should have user Name (Bob) with mail(bob@gmail.com).

https://codesandbox.io/s/amazing-forest-v521v?file=/index.js

help would be appreciated.
