### ISSUE TITLE
Provide width and minWidth to Antd Modal

### ISSUE THREAD

**Issue by aditya-padhi-kbl** [ant-design/ant-design#25570]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-leavitt-i6l2m?file=/package.json)

### Steps to reproduce
In index.js file in Line No. 38 please try to apply width and minWidth

### What is expected?
Width and minWidth should be applied to the Modal

### What is actually happening?
width and minWidth is not getting applied to the Modal

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.13.0 |
| System | Mac |
| Browser | Chrome v80 |

**Comment by afc163** [comment]
```
<Modal width={400} />
```

And providing `minWidth` is not in our plan.
