### ISSUE TITLE
An `id` must be provided to format a message.

### ISSUE THREAD

**Issue by fenglijunnb** [ant-design/ant-design#25572]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
这是一个bug 

### What does the proposed API look like?
An `id` must be provided to format a message.

**Comment by fenglijunnb** [comment]
@afc163 这个东西没办法写demo .就是我用了npm run lint:fix 命令然后项目就报错

**Comment by remind** [comment]
我刚刚也遇到了，什么都没有做，就create之后install，再start，浏览器打开就是这个错

**Comment by remind** [comment]
用的pro构建的

**Comment by remind** [comment]
![1](https://user-images.githubusercontent.com/3130675/87146013-e2afff00-c2dc-11ea-9a6e-147ef9414c38.jpg)

**Comment by fenglijunnb** [comment]
@remind 的确，这玩意我也不晓得是啥错

**Comment by fenglijunnb** [comment]
@remind 你如果解决了问题的话，可以发出来看看奥

**Comment by MRchao90s** [comment]
我也有这个问题

**Comment by remind** [comment]
@fenglijunnb @MRchao90s 我换了一个版本，create时选择V5，就没这个问题

**Comment by gehaijun** [comment]
ref: [route-utils](https://github.com/umijs/route-utils/pull/4)

**Comment by MRchao90s** [comment]
> @fenglijunnb @MRchao90s 我换了一个版本，create时选择V5，就没这个问题
我用V5已经解决这个问题

**Comment by fenglijunnb** [comment]
@MRchao90s @gehaijun @remind 还有一种是你的antd 版本过高，你弄到4.3版本就可以了
