### ISSUE TITLE
Form did't catch the errors when submit the form with  some of Form.Item's validateStatus is error. 当表单中Form.Item的validateStatus为error时，提交表单仍然会触发验证成功

### ISSUE THREAD

**Issue by weileiwilliam** [ant-design/ant-design#25580]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crimson-fast-07jjl?file=/index.js:1015-1029)

### Steps to reproduce
1.set the value of validateStatus of Form.Item to error

2.submit the form

3.the form didn't catch the errors

### What is expected?
when set the value of validateStatus of Form.Item to error and submit the form, the form should catch the error

当Form.Item的validateStatus的值为error时，提交表单应当数据验证失败

### What is actually happening?
when set the value of validateStatus of Form.Item to error and submit the form, the form didn't catch the error

当Form.Item的validateStatus的值为error时，提交表单应当数据验证成功

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | ^16.12.0 |
| System | macOS Catalina 10.15.5 |
| Browser | Google Chrome 83.0.4103.116 (Official Build) (64-bit) |

**Comment by afc163** [comment]
validateStatus 只是纯样式展示，校验逻辑是 rules 控制的。
