### ISSUE TITLE
Select with mode = "tags"  , already selected values are not nodes but value strings.

### ISSUE THREAD

**Issue by miyamirz** [ant-design/ant-design#25592]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/amazing-forest-v521v?file=/index.js)

### Steps to reproduce
I have mode="tags" , Can i render the entire node in the Options for already selected values?
For example

i type 'b' and select bob@gmail.com.
2.Now i type 'j' and the option should have user Name (Bob) with mail(bob@gmail.com).

### What is expected?
The already selected values should be nodes

### What is actually happening?
The already selected values are of type string in options and not nodes

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.12 |
| System | Mac |
| Browser | chrome |

---
Continuation of  - Select with custom Option is behaving not correctly #25576
https://github.com/ant-design/ant-design/issues/25576

**Comment by miyamirz** [comment]
@Yunfly  can you please help me here. 
Also the optionLabelProp is not supported in AutoComplete. How can i acheive the same in it

**Comment by Yunfly** [comment]
labelInValue may help, it save  label's ReactNode and render it. I haven't deeply use AutoComplete in this situation.

**Comment by miyamirz** [comment]
i have tried labelInValue.. its not working. I tried setting option instance to value in handleChange which is also not working
https://codesandbox.io/s/lucid-zhukovsky-5h7mu?file=/index.js

**Comment by Yunfly** [comment]
it render your option node, what if change CSS to show where u want.  https://codesandbox.io/s/quirky-sea-jh3ss?file=/index.js

**Comment by miyamirz** [comment]
looks good. I will try similar for AutoComplete and check if it works there also. Thanks @Yunfly
