### ISSUE TITLE
3.26.7升级4.4.2后,页面有大量input, 则Input绑定onchange事件,输入卡顿

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#25596]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7l2du?file=/index.js)

### Steps to reproduce
文本框连续输入,onchange明显感觉卡顿

### What is expected?
连续输入舒畅

### What is actually happening?
连续输入卡顿

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16 |
| System | MAC |
| Browser | chrome |

---
场景:表格批量输入后提交
在3.26.7版本功能已上线使用,输入十分顺畅.
现在打算升级到4.x 发现重装依赖后,此功能输入变的卡顿.
codesandbox中将antd版本退回到3.26.7也是卡顿的.

尝试将只保留一个input, 输入也不会卡
随着页面输入框的增多,体验上越来越卡

**Comment by Kermit-Xuan** [comment]
线上的 React 版本是多少？

**Comment by Kermit-Xuan** [comment]
希望能给一个不卡顿的复现demo，目前看来是因为，每次 `onChange`， 都会 `setState`，表格全部重新渲染，连续输入的话肯定就卡了，可以利用 `shouldComponentUpdate` 去优化表格渲染。

**Comment by l745230** [comment]
> 希望能给一个不卡顿的复现demo，目前看来是因为，每次 `onChange`， 都会 `setState`，表格全部重新渲染，连续输入的话肯定就卡了，可以利用 `shouldComponentUpdate` 去优化表格渲染。

不卡的demo重现不出来...
我把线上版本的代码,在本地重新安装依赖后,启动发现输入也卡顿了 这真的是醉了....

在代码没有改变的基础上,只做了2件事
1.电脑旧的node环境卸载,重装了v14.5.0版本.
2.删除旧依赖,重新安装

**Comment by Kermit-Xuan** [comment]
> > 希望能给一个不卡顿的复现demo，目前看来是因为，每次 `onChange`， 都会 `setState`，表格全部重新渲染，连续输入的话肯定就卡了，可以利用 `shouldComponentUpdate` 去优化表格渲染。
> 
> 不卡的demo重现不出来...
> 我把线上版本的代码,在本地重新安装依赖后,启动发现输入也卡顿了 这真的是醉了....
> 
> 在代码没有改变的基础上,只做了2件事
> 1.电脑旧的node环境卸载,重装了v14.5.0版本.
> 2.删除旧依赖,重新安装

看看会不会是 React 版本的问题呢？

**Comment by l745230** [comment]
如果先抛开antd升级的因素,就说说这个卡顿现象.

react不是虚拟Dom,只有差异的数据才更新吗?,为何会每次onchange,表格全部渲染..

**Comment by afc163** [comment]
试试 `shouldCellUpdate`：https://codesandbox.io/s/antd-reproduction-template-gfity?file=/index.js

**Comment by Kermit-Xuan** [comment]
> 如果先抛开antd升级的因素,就说说这个卡顿现象.
> 
> react不是虚拟Dom,只有差异的数据才更新吗?,为何会每次onchange,表格全部渲染..

重新渲染不是dom的重新加载，是组件的render方法重新执行，返回的虚拟DOM与之前的做diff，最后做dom的差异更新，但是table的节点非常多，执行render然后做diff的过程就很耗性能。

**Comment by l745230** [comment]
> 试试 `shouldCellUpdate`：https://codesandbox.io/s/antd-reproduction-template-gfity?file=/index.js

1.shouldCellUpdate 得4.3.0之后才支持的. 
2.配置了shouldCellUpdate之后,输入框的值,无论改成什么,离开输入框后就变回初始值了. 那这跟普通文本展示没什么区别了.  这种情况下,虽然onchange不卡,但是如果表格没配置输入框,也不卡. 没解决根本问题.

**Comment by l745230** [comment]
用create-my-app搭了个环境.
多次重装依赖,进行体验
antd: 3.25.3 react:16.7.0 输入框会卡,但是表现上比4.4.2好很多
antd: 4.4.2 react:16.8.0 明显感觉比3.25.3卡

**Comment by Kermit-Xuan** [comment]
@l745230 https://codesandbox.io/s/antd-reproduction-template-qb6zd?file=/index.js
看看是否满足你的需求？

**Comment by Kermit-Xuan** [comment]
> > 试试 `shouldCellUpdate`：[codesandbox.io/s/antd-reproduction-template-gfity?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-gfity?file=/index.js)
> 
> 1.shouldCellUpdate 得4.3.0之后才支持的.
> 2.配置了shouldCellUpdate之后,输入框的值,无论改成什么,离开输入框后就变回初始值了. 那这跟普通文本展示没什么区别了. 这种情况下,虽然onchange不卡,但是如果表格没配置输入框,也不卡. 没解决根本问题.

https://codesandbox.io/s/antd-reproduction-template-qb6zd?file=/index.js 看看是否满足你的需求？

**Comment by afc163** [comment]
> 配置了shouldCellUpdate之后,输入框的值,无论改成什么,离开输入框后就变回初始值了. 那这跟普通文本展示没什么区别了

更新数据需要严格的 immutable，避免将 prevRecord 的数据改掉：https://codesandbox.io/s/antd-reproduction-template-i0k8y?file=/index.js

更清晰的最小化例子：https://codesandbox.io/s/peaceful-newton-w386f?file=/index.js

**Comment by Kermit-Xuan** [comment]
@afc163 我写的那种用非受控模式实现可以么？

**Comment by afc163** [comment]
非受控模式大概不是 @l745230 想要的。

**Comment by l745230** [comment]
> 更清晰的最小化例子：https://codesandbox.io/s/peaceful-newton-w386f?file=/index.js
@afc163 大佬给的这个例子体验了下,非常流畅.每个输入框更改的值也能记录下来.
结合我这边业务,还有个疑问咨询一下,
例子中使用defaultValue, 那么每一行多个输入框联动,好像是无法实现
比如 key0=key1 * 10 + key2   三个输入框互相联动

**Comment by l745230** [comment]
呃 看错了.楼上回复的是@Kermit-Xuan 给的非受控模式..

**Comment by l745230** [comment]
https://codesandbox.io/s/antd-reproduction-template-i0k8y?file=/index.js:0-5346

@afc163 按大佬给的例子,改了下业务代码, shouldCellUpdate 效果很明显. 现在输入体验跟线上版本基本一样了~~ 

可以安心升级4.x了

**Comment by l745230** [comment]
-  shouldCellUpdate(record, prev)  => record !== prev; 
+ shouldCellUpdate: (record, prev) => record.deliveryQuantity !== prev.deliveryQuantity,

记录一下,使用的时候要具体到那个字段不做比较.
