### ISSUE TITLE
Select component is not compatible with autoComplete tags

### ISSUE THREAD

**Issue by cesarnml** [ant-design/ant-design#25595]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/antd-select-autocomplete-workaround](https://stackblitz.com/edit/antd-select-autocomplete-workaround)

### Steps to reproduce
Create a Select component with autoComplete attribute.

### What is expected?
I would expect the autocomplete behavior described in this google reference: https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

### What is actually happening?
Input components will respect browser autocomplete behavior. Select components do not.

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.12.0 |
| System | Mac Catalina 10.15.5 |
| Browser | Chrome 86.0.42 |

**Comment by afc163** [comment]
Select don't support `autoComplete`, you may need https://ant.design/components/auto-complete-cn/
