### ISSUE TITLE
Descriptions没有冒号对齐功能

### ISSUE THREAD

**Issue by YuShengSenior** [ant-design/ant-design#25597]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了实现样式与设计稿不符

### What does the proposed API look like?
可以有一个属性来设置是否启用冒号对齐,采用boolean控制或者是啥的....

**Comment by afc163** [comment]
目前我们的 Descriptions 在设计上没有冒号对齐，建议不要这么设计。

**Comment by YuShengSenior** [comment]
okk好的吧
