### ISSUE TITLE
安装完antd（本地）,antd-bin（全局）后使用webpack-dev-server启动时报reqwest错

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#256]
平台：win7,64位

npm install antd --save-dev
npm install antd-bin -g

系统能够正常启动，网上也说只有服务器端才用到，但在webpack-dev-server启动时一大片红色总觉得不好。

报错信息都是关于reqwest的。

ERROR in ./~/antd/~/reqwest/make/tests.js
Module not found: Error: Cannot resolve module 'fs' in D:\path\to\...\node_modules\antd\node_modules\reqwest\make
...

ERROR in ./~/antd/~/reqwest/make/tests.js
Module not found: Error: Cannot resolve module 'child_process' in D:\path\to\...\node_modules\antd\node_modules\reqwest\make
...

ERROR in ./~/antd/~/reqwest/make/tests.js
Module not found: Error: Cannot resolve module 'process-child' in D:\path\to\...\node_modules\antd\node_modules\reqwest\make
...

ERROR in ./~/antd/~/reqwest/make/tests.js
Module not found: Error: Cannot resolve module 'connect' in D:\path\to\...\node_modules\antd\node_modules\reqwest\make
...

ERROR in ./~/antd/~/reqwest/make/tests.js
Module not found: Error: Cannot resolve module 'dispatch' in D:\path\to\...\node_modules\antd\node_modules\reqwest\make
...

ERROR in ./~/antd/~/reqwest/make/tests.js
Module not found: Error: Cannot resolve module 'delayed-stream' in D:\path\to\...\node_modules\antd\node_modules\reqwest\make
...

ERROR in ./~/antd/~/reqwest/make/phantom.js
Module not found: Error: Cannot resolve module 'webpage' in D:\path\to\...\node_modules\antd\node_modules\reqwest
...

查到的解决办法有两种：
1，在package.json里
  "browser": {
    "fs": false,
    "child_process": false
  },
但是我试过了没效果

2，在webpack.config.js里
  node: {
    fs: "empty",
    child_process: 'empty'
  },
试过了，fs，child_process两个模块不报错了，但是其余仍然报错，还是没根本解决问题，请大神们看看，谢谢

**Comment by sorrycc** [comment]
antd-bin 和项目目录不在同一个盘符?

**Comment by zccst** [comment]
在同一个盘符。
项目在D盘
antd-bin作为全局安装，npm install antd-bin -g，也是安装在D盘的，目录是
D:\users\...\npm\node_modules\antd-bin
antd-bin我是本地安装的，在项目目录下，npm install antd --save-dev。

**Comment by ecafe8** [comment]
我也遇到了.  在antd目录下重新装一次reqwest的2.0.1版本解决;
npm install reqwest@2.0.1 --save

**Comment by afc163** [comment]
试试 beta 版本：`npm install antd@beta`

**Comment by zccst** [comment]
@ecafe8 给力，我重装以后不报错了，好开心。

**Comment by zccst** [comment]
@afc163 beta版本稳定吗？我想等你们下一个稳定版发布后再更新。

**Comment by afc163** [comment]
预计本周末发 0.9.0 。

**Comment by zccst** [comment]
@afc163 给力，这么快就发新版，能明显感觉到你们的坚持与付出，加油。

**Comment by baizn** [comment]
MAC 下，原来报的错和上面类似，npm install reqwest@2.0.1 --save 和 npm install antd@beta 后还报如下错误：
![image](https://cloud.githubusercontent.com/assets/9443867/9811866/6a5b1a66-58ac-11e5-986a-0a3dc5edfd2c.png)

![image](https://cloud.githubusercontent.com/assets/9443867/9811931/b590744a-58ac-11e5-87a7-aba5a85bb126.png)

怎么解决呢 ，感谢！

**Comment by zccst** [comment]
@baizn 看报错，是css相关的错误。所以应该看你webpack.config.js里是否配对了css loader的参数。

**Comment by baizn** [comment]
终于搞定了  原来是安装antd后，还需要在antd/node_modules目录下面安装style等好几个包才可以。node npm也重装了好几次。。。
