### ISSUE TITLE
Table组件 scroll 的scroll 属性没有作用

### ISSUE THREAD

**Issue by Aaronphy** [ant-design/ant-design#2560]
#### 本地环境

- antd 版本: 0.12.x
- 操作系统及其版本：mac os
- 浏览器及其版本:普通chrome

#### 你做了什么？
 
   引入 antd 了 Table 
   设置了scroll  ,没有作用

#### 你期待的结果是：

   像官网一样正常显示 

#### 实际上的结果：

  没有作用

**Comment by benjycui** [comment]
Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
0.12.x 没有这个功能，注意 changelog。
