### ISSUE TITLE
Change color of antd Divider component

### ISSUE THREAD

**Issue by aashayamballi** [ant-design/ant-design#25605]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If the Divider component used in the grey (#f0f2f5) background, then the divider component will not appear as it should be. So if we have an option to change the color of the divider component or if there is any CSS property that I could change the color of the divider, that would be great.

### What does the proposed API look like?

```
<Divider color="black"/>
<Divider style={{color: "black"}}/>
```

**Comment by xrkffgg** [comment]
https://ant.design/components/divider-cn/#components-divider-demo-customize-style

**Comment by aashayamballi** [comment]
Thank you @xrkffgg
