### ISSUE TITLE
Calendar validRange does not display data

### ISSUE THREAD

**Issue by jamalabo1** [ant-design/ant-design#25606]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-zmnew?file=/index.js)

### Steps to reproduce
set validRange

### What is expected?
To display data for the current month selected

### What is actually happening?
Does select month number 6 without displaying the month's name, and loads the month's data but does not render/display it

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.8.1 |
| System | Windows 10 |
| Browser | Chrome 78 |

**Comment by 07akioni** [comment]
I can't reproduce your issue. In you reproduction link, not data is given to calendar.

https://codesandbox.io/s/upbeat-hypatia-cjtbd?file=/index.js

**Comment by afc163** [comment]
@07akioni Using `Need Reproduce` label if issue cannot reproduce problem.

**Comment by jamalabo1** [comment]
Maybe the data loading problem is in my side, but the other problem you maybe didn't notice that the month is selected in numbers 
when you first load the link it selects 2020 6, not 2020 Jun
