### ISSUE TITLE
Select Custom dropdown can not prevent closed for using onMouseDown

### ISSUE THREAD

**Issue by zyycode** [ant-design/ant-design#25609]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-sun-nhmc3)

### Steps to reproduce
clicking CheckBox in Select dropdown, it will closed.

点击下拉框中的CheckBox 文字会自动收起

### What is expected?
**Hope can not closed by clicking Select dropdown.**

点击下拉框的内容不会自动收起

### What is actually happening?
** closed by clicking Select dropdown.**

点击下拉框的内容会自动收起

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.12 |
| System | macOS 10.15.2 |
| Browser | Chrome 83.0.4103.116 |

---
It can work in Firefox and Safari，but not working in **chrome** , by the way it also can work for antd ^4.0.0.

**Comment by afc163** [comment]
Try Popover, it is not good usage to use dropdownRender in this way.
