### ISSUE TITLE
Collapse折叠面板 能加个拖动改变排序功能吗

### ISSUE THREAD

**Issue by withwz** [ant-design/ant-design#25618]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用antdesignpro menu 做左边的菜单，使用Collapse折叠面板控制左边菜单的显示隐藏

![img](https://cdn.nlark.com/yuque/0/2020/png/432716/1594720484024-5d4e1ad6-d642-46b8-a2a4-b3953ceae155.png)

### What does the proposed API look like?
```jsx
  <Collapse dragableChange={(order)=>{}} defaultActiveKey={['1']} onChange={callback}> // dragableChange改变了顺序触发，返回现在Panel的顺序
    <Panel dragable={true} header="This is panel header 1" key="1">  // dragable 这个Panel可以拖动改变顺序
      <p>{text}</p>
    </Panel>
    <Panel dragable={false} header="This is panel header 2" key="2">
      <p>{text}</p>
    </Panel>
    <Panel dragable={true} header="This is panel header 3" key="3" disabled>
      <p>{text}</p>
    </Panel>
  </Collapse>,
```

**Comment by Kermit-Xuan** [comment]
这个没必要加，自己用个拖拽库就可以解决了。

**Comment by withwz** [comment]
> 这个没必要加，自己用个拖拽库就可以解决了。

我试了https://github.com/YGYOOO/react-draggable-tags这个库， 
也试了https://www.jianshu.com/p/a923add40767这个方案，
都不行
Collapse下边必须跟着Panel ，要不就不好使了。。

你试了用哪个拖动库好使吗

**Comment by Kermit-Xuan** [comment]
> > 这个没必要加，自己用个拖拽库就可以解决了。
> 
> 我试了[YGYOOO/react-draggable-tags](https://github.com/YGYOOO/react-draggable-tags) 这个库，
> 也试了[jianshu.com/p/a923add40767](https://www.jianshu.com/p/a923add40767) 这个方案，
> 都不行
> Collapse下边必须跟着Panel ，要不就不好使了。。
> 
> 你试了用哪个拖动库好使吗

https://github.com/SortableJS/react-sortablejs#custom-component

**Comment by wuranxu** [comment]
> > 这个没必要加，自己用个拖拽库就可以解决了。
> 
> 我试了https://github.com/YGYOOO/react-draggable-tags 这个库， 也试了https://www.jianshu.com/p/a923add40767 这个方案， 都不行 Collapse下边必须跟着Panel ，要不就不好使了。。
> 
> 你试了用哪个拖动库好使吗

后来解决了吗？我看Collapse后面只能跟Panel组件，导致拖拽不了。。
