### ISSUE TITLE
Tree component need a custom props node render function if children is deprecated.

### ISSUE THREAD

**Issue by NNNaix** [ant-design/ant-design#25615]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We can not use treeData to solve all the scenario. 
For example, if we need customize nodes that using treeData, we must render all the tree node in treeData one time, it slowly and expensive.
And in the term of design, the decoupling of model and view is also following to the best practice.
So I think if we should not obsolete 'children' until find a solution for customizing node.

### What does the proposed API look like?
Something like below. we can infer the type of CustomTreeNode to retrict the treeData node type.
```jsx
<Tree customNode={<CustomTreeNode/>} />
```

**Comment by lucasleelz** [comment]
some issue.

**Comment by zombieJ** [comment]
`title` support function to lazy render. But I think provide a `titleRender` is a better solution.

**Comment by eiva** [comment]
Any idea how to make titleRender make elements with a same width? (or better to fill all remaining space)
