### ISSUE TITLE
warning.js:44 Warning: Failed propType: Invalid prop `popup` supplied to `Trigger`, expected a ReactNode. Check the render method of `Tooltip`.

### ISSUE THREAD

**Issue by tianyacsdn** [ant-design/ant-design#2561]
warning.js:44 Warning: Failed propType: Invalid prop `popup` supplied to `Trigger`, expected a ReactNode. Check the render method of `Tooltip`.

- antd 版本:1.7.0
- 操作系统及其版本：win7
- 浏览器及其版本:chrome

**Comment by tianyacsdn** [comment]
使用<Popover>也是报一样的错误

**Comment by tianyacsdn** [comment]
使用<Popover>也是报一样的错误

**Comment by RaoHai** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by RaoHai** [comment]
并且这个是 warning……代码贴一下吧。

**Comment by benjycui** [comment]
无进一步反馈，先关了，有问题再开吧。

**Comment by ITJesse** [comment]
同样的问题，删掉 node_modules 后重新安装解决。可能是因为存在损坏的包。

**Comment by jinchaoxiang** [comment]
修改方式 this.getPopupElement => this.getPopupElement()
