### ISSUE TITLE
Inputnumber value getting changed after blur

### ISSUE THREAD

**Issue by yakkantiraja** [ant-design/ant-design#25616]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-myi5e3?file=index.js](https://stackblitz.com/edit/react-myi5e3?file=index.js)

### Steps to reproduce
Enter value as in Input number  44444444444444444444

### What is expected?
After input value click outside of the field.

### What is actually happening?
entered value showing as  9007199254740991

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | any |
| System | any |
| Browser | any |

---
It should show what i have entered which is 44444444444444444444

**Comment by fireairforce** [comment]
It will overflow.
![image](https://user-images.githubusercontent.com/32598811/87409394-747a7d80-c5f7-11ea-908b-7fcfad23fd2c.png)
