### ISSUE TITLE
希望Carousel增加箭头切换和可以设置自动播放时间

### ISSUE THREAD

**Issue by MaZhengA** [ant-design/ant-design#25619]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel-cn/](https://ant.design/components/carousel-cn/)

### Steps to reproduce
无

### What is expected?
无

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | undefined |
| React | ^16.12.0 |
| System | 10.15.3 |
| Browser | Google Chrome81.0.4044.138 |

**Comment by fireairforce** [comment]
https://github.com/ant-design/ant-design/issues/5458#issuecomment-288713585

**Comment by afc163** [comment]
There is `autoPlaySpeed`.
