### ISSUE TITLE
InputNumber组件 onBlur事件返回的e.target.value有误

### ISSUE THREAD

**Issue by FEliuyg** [ant-design/ant-design#25614]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hidden-fire-k231g?file=/index.js:291-302)

### Steps to reproduce
1.InputNumber输入框清空，然后点击失去焦点
2.onBlur返回的参数e，获取e.target.value的值为0
3.但如果原生input标签。onBlur获取的e.target的值为''

### What is expected?
e.target.value返回'' 或者null

### What is actually happening?
e.target.value为0

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.0 |
| System | mac |
| Browser | chrome |

**Comment by 07akioni** [comment]
If you rely on text value of the input, you'd better use <input type="number" />, not InputNumber

**Comment by afc163** [comment]
应该返回 undefined。

**Comment by fireairforce** [comment]
可以去 rc 里改一下

**Comment by 1123612483** [comment]
InputNumber的onBlur应当返回`''`，和input的onBlur保持一致，因为InputNumber的onBlur输出的`e`的来源还是在input

**Comment by fireairforce** [comment]
> 应该返回 undefined。

我看 onChange 的逻辑里面返回的是''

**Comment by yuzhihaoGitHub** [comment]
使用了formatter和parser属性，onBlur时间获取的e.target.value的值为NaN，如何解决呢？

**Comment by laoxubuer** [comment]
> 使用了formatter和parser属性，onBlur时间获取的e.target.value的值为NaN，如何解决呢？

onChange里，编辑的时候，value是string，onBlur或者点击加减按钮都是number，可以通过类型来判断
