### ISSUE TITLE
Google's lighthouse: Links are not crawlable (pagination)

### ISSUE THREAD

**Issue by decimoseptimo** [ant-design/ant-design#25627]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This issue negatively impacts the lighthouse test at around 10 points in the SEO measurement

### What does the proposed API look like?
Probably replacing <a> for <button> tags will do for the pagination component. Altough I can forsee similar issues present in other components.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/pagination/pull/288
