### ISSUE TITLE
Pagination无法默认高亮选中页码

### ISSUE THREAD

**Issue by tulies** [ant-design/ant-design#25625]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-night-nct6u?file=/src/App.js)

### Steps to reproduce
直接使用Pagination，动态传入total参数，会导致无法选中默认页码。直接将total写死数字则可以。

具体demo见：https://codesandbox.io/s/nostalgic-night-nct6u?file=/src/App.js。

### What is expected?
应该默认高亮选中第一页。

### What is actually happening?
没有高亮选中页码。

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome |

---
在Table组件中直接设置pagination属性是可以正常

**Comment by fireairforce** [comment]
看复现貌似是和 total 初始值设置为 0 有关系，不过这种情况下你可以使用 `current` 这个参数？

**Comment by tulies** [comment]
> 看复现貌似是和 total 初始值设置为 0 有关系，不过这种情况下你可以使用 `current` 这个参数？

呃，的确如此，必须要设置current，忘记设置了。

谢谢。
