### ISSUE TITLE
Form组件在antd 版本: 1.6.4 和react版本: 15.2.1下报错

### ISSUE THREAD

**Issue by and80506** [ant-design/ant-design#2562]
#### 本地环境

- antd 版本: 1.6.4
- react版本: 15.2.1
- 操作系统及其版本：os x 10.11.5
- 浏览器及其版本: chrome 51.0.2704.106 (64-bit)

#### 你做了什么？
运行例子[form组件](http://ant.design/components/form/)中的与modal配合使用的例子，react报错。
运行其他例子也是一样报同一个错误。
#### 你期待的结果是：

无报错，根据[Input组件](http://ant.design/components/input/)的这段描述“如果 Input 在 Form.Item 内，并且 Form.Item 设置了 id 和 options 属性，则 value defaultValue 和 id 属性会被自动设置。”， input应该被正确赋予value属性。

#### 实际上的结果：

warning.js:44 Warning: Input is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
![localhost 8001 pages example index html 2016-08-01 11-32-23](https://cloud.githubusercontent.com/assets/1769410/17282761/fb360710-57db-11e6-8358-1abbd8a78b29.png)

查看Element面板，发现input没有被正确赋予value属性。

![localhost 8001 pages example index html 2016-08-01 11-33-25](https://cloud.githubusercontent.com/assets/1769410/17282755/f19bf728-57db-11e6-8372-c058df939896.png)

**Comment by benjycui** [comment]
http://ant.design/components/form#this.props.form.getFieldProps(id,-options)

`initialValue`

**Comment by and80506** [comment]
多谢解答，但是表单校验的[例子](http://ant.design/components/form/#components-form-demo-validate-basic)里，如果加initialValue，页面初始化时立即进行了一次表单校验，而且校验结果为通过，正常结果应该是初始化页面不校验不显示反馈图标，请问如何解决？

![form - ant design 2016-08-01 12-42-08](https://cloud.githubusercontent.com/assets/1769410/17283645/69c0d27e-57e5-11e6-9958-21081e405b51.png)

```
...
const nameProps = getFieldProps('name', {
      rules: [
        { required: true, min: 5, message: '用户名至少为 5 个字符' },
        { validator: this.userExists },
      ],
      initialValue: '12334',
    });
...
<FormItem
          {...formItemLayout}
          label="用户名"
          hasFeedback
          help={isFieldValidating('name') ? '校验中...' : (getFieldError('name') || []).join(', ')}
        >
          <Input {...nameProps} placeholder="实时校验，输入 JasonWood 看看" />
 </FormItem>
```

**Comment by benjycui** [comment]
要不先把 antd 升到 1.7.0，react 升到 15.3.0 吧，这样把 initialValue 去掉也没有 warning。

**Comment by and80506** [comment]
好的，多谢了。
