### ISSUE TITLE
4.4.2 List 中 Switch未正确回显.

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#25639]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vibrant-allen-nr13x?file=/index.js)

### Steps to reproduce
访问连接

### What is expected?
获取请求数据后,List中Switch显示正确状态

### What is actually happening?
获取请求数据后,List中Switch未显示正确状态

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16 |
| System | MAC |
| Browser | chrome |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E5%8A%A8%E6%80%81%E6%94%B9%E5%8F%98-defaultValue-%E7%9A%84%E6%97%B6%E5%80%99%E5%AE%83%E5%B9%B6%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%E3%80%82
