### ISSUE TITLE
Tree: Support custom function as switcherIcon

### ISSUE THREAD

**Issue by SentretC** [ant-design/ant-design#25632]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, the Tree component can accept a `switcherIcon` property of type ReactNode. However, using it one can only specify the icon used in expanded state; when an tree node is collapsed the same icon is used, just rotated 90° ccw; and the one used for leaf nodes depends on the `showLine` property.
One can also specify a `switcherIcon` for each item in `treeData`, which can be a ReactNode or a function that returns different icons depending on node state. A great feature, but not documented (the doc just says `treeData` is of type `array<{key, title, children, [disabled, selectable]}>`, without even mentioning `icon`). And it's a little complicated for many use cases (why specify a rendering function for each node when the function can return different result depending on their data?).

It would be nice if the `switcherIcon` property of the component itself can also be assigned a custom function, like the `icon` prop and the one in `treeData` does.

By the way, the doc has an FAQ on [How to hide file icon when use showLine](https://ant.design/components/tree/#How-to-hide-file-icon-when-use-showLine). The demo provided doesn't work as the css in it don't apply to antd 4. Also, one can easily use `showLine={{ showLeafIcon: false }}` now thanks to PR #25271.

---

当前，树形控件 Tree 可以接受一个 ReactNode 类型的 `switcherIcon` 属性。但是通过该属性只能指定展开状态下的图标；节点折叠时仍为同一图标，只是逆时针旋转了 90°；而叶子节点的对应图标则受 `showLine` 属性控制。
而 `treeData` 中的每一项也可以指定 `switcherIcon`，这一属性既可以是 ReactNode 也可以是根据节点状态返回不同图标的自定义函数。很赞的功能，可惜文档里没写（文档只说 `treeData` 的类型是 `array<{key, title, children, [disabled, selectable]}>`，都没提 `icon`）。而且好像很多情况下没必要这么麻烦（既然是可以根据不同节点数据返回不同图标的渲染函数，为什么还一定要为每个节点分别指定呢？）。

希望控件本身的 `switcherIcon` 属性也像 `icon` 属性和 `treeData` 里的 `switcherIcon` 那样，可以设置为自定义函数。

顺带一提，文档中有一个关于[在 showLine 时，如何隐藏子节点图标](https://ant.design/components/tree-cn/#%E5%9C%A8-showLine-%E6%97%B6%EF%BC%8C%E5%A6%82%E4%BD%95%E9%9A%90%E8%97%8F%E5%AD%90%E8%8A%82%E7%82%B9%E5%9B%BE%E6%A0%87%EF%BC%9F)的 FAQ，其中给出的 demo 所含 css 不适用于 antd 4 所以并不能用。另外现在有了 PR #25271，直接指定 `showLine={{ showLeafIcon: false }}` 就可以。

### Proposal A
Same as `swicherIcon` in `treeData`, or the `icon` property:
`switcherIcon: ReactNode | (props) => ReactNode`
### Proposal B
Make the icon type more explicit, and allow user to only override the default one in some cases:
`switcherIcon: ReactNode | (props, type: 'open' | 'close' | 'noop') => （ReactNode | null)`

**Comment by tomasamado97** [comment]
any news on this? We are using the Tree component too and we need to be able to change the icon depending on if the tree is expanded or not.

**Comment by afc163** [comment]
> Proposal A

> Same as swicherIcon in treeData, or the icon property:
> switcherIcon: ReactNode | (props) => ReactNode

Supported in https://4x.ant.design/changelog-cn#4.20.0

https://github.com/ant-design/ant-design/pull/34470
