### ISSUE TITLE
antd 3.x 版本是否有国内镜像地址

### ISSUE THREAD

**Issue by WebEngineerLi** [ant-design/ant-design#25636]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/index-cn](https://ant-design.gitee.io/index-cn)

### Steps to reproduce
无

### What is expected?
https://3x.ant.design/index-cn antd3.x 有时进入会很耗时，期望有3.x的国内镜像

### What is actually happening?
无

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.13.1 |
| System | Mac 10.15.4  |
| Browser | Chrome 83.0.4103.61 |

**Comment by xrkffgg** [comment]
或许 clone 下 3.x 的代码，本地起一个服务是个不错的选择~ 

- https://github.com/ant-design/ant-design/tree/3.x-stable

**Comment by WebEngineerLi** [comment]
> 或许 clone 下 3.x 的代码，本地起一个服务是个不错的选择~
> 
> * https://github.com/ant-design/ant-design/tree/3.x-stable

What a great idea

**Comment by xrkffgg** [comment]
要是不看网站样式，直接撸源码API都行

**Comment by afc163** [comment]
有心的同学可以用 gitee 搞一个，最慢十分钟就搞出来了。

**Comment by xrkffgg** [comment]
ant-design 3.x 国内镜像地址：https://ant-design-3x.gitee.io/

**Comment by xrkffgg** [comment]
ant-design 国内镜像地址：https://github.com/ant-design/ant-design/issues/25661

**Comment by WebEngineerLi** [comment]
> ant-design 国内镜像地址：#25661

感谢大！！！
