### ISSUE TITLE
tab is hidden by left arrow when text in tab is too long

### ISSUE THREAD

**Issue by leviathan-n** [ant-design/ant-design#25631]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-wright-5w9d9?file=/index.js)

### Steps to reproduce
click open in new window button which is at top-right of the web, then click right arrow, finally click the leftmost tab, this tab will be hidden by the left arrow

### What is expected?
display complete context of the tab

### What is actually happening?
tab is hidden partly by left arrow

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.1 |
| System | windows10 2004 |
| Browser | Microsoft Edge 83 |

**Comment by afc163** [comment]
3.x is not maintianed now, please upgrade to 4.x for better behavior.
