### ISSUE TITLE
Select组件tokenSeparators属性自动回车分词失效

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#25642]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epwwo)

### Steps to reproduce
在4.4.0之前，支持了回车换行 #23304
<Select mode="tags"
            notFoundContent=''
            tokenSeparators={[',','\r\n']}
            />

### What is expected?
回车换行有效

### What is actually happening?
4.4.1回车换行失效了

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.12 |
| System | Windows 10 |
| Browser | 谷歌浏览器 |

**Comment by afc163** [comment]
@zombieJ 看看是不是 https://github.com/react-component/select/pull/517 改挂了。

**Comment by zombieJ** [comment]
你复制的文本是什么样子的？MAC 下试了 `\n` 是可以的，你试试直接 `\n` ？

https://codesandbox.io/s/dazzling-leaf-kdycl?file=/index.js

**Comment by phoema** [comment]
从excel里面粘贴的一列
\n也不行
您这个box可以是因为后面多了个tokenSeparators=空格
粘贴数据被转换为空格了。

**Comment by zombieJ** [comment]
> 从excel里面粘贴的一列
> \n也不行
> 您这个box可以是因为后面多了个tokenSeparators=空格
> 粘贴数据被转换为空格了。

意思是我给的重现里复制 Textare 是可以行的？但是 Excel 里不可行？

**Comment by afc163** [comment]
给个精确的重现方式吧。

**Comment by phoema** [comment]
您的这个测试地址
https://codesandbox.io/s/relaxed-davinci-6uknk?file=/index.js

我是windows
excel拷贝一列、或者记事本拷贝一列，均不分词，分词加上\r\n也不分词

**Comment by 07akioni** [comment]
It's a bug. Things copied from same column in excel will be treated as `row1\rrow2\rrow3`

**Comment by 07akioni** [comment]
> 您的这个测试地址
> https://codesandbox.io/s/relaxed-davinci-6uknk?file=/index.js
> 
> 我是windows
> excel拷贝一列、或者记事本拷贝一列，均不分词，分词加上\r\n也不分词

用 `' '` 可以，你试试。这确实是个 bug。

**Comment by phoema** [comment]
嗯，试过了，最早回车就被替换成空格了
#23304
后来afc163他们加上这个特性了，现在又没了
主要是这个特性我们用的多，很多地方需要从excel里粘贴过来
