### ISSUE TITLE
基于form item二次封装的FormItemComponent组件拿不到props.value值

### ISSUE THREAD

**Issue by guiyu1230** [ant-design/ant-design#25644]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-basic](https://ant.design/components/form-cn/#components-form-demo-basic)

### Steps to reproduce
1. 基于form item的二次封装.   将item下的标签封装成属性  <FormItemComponent name="item1"  component="input"  label="选择框" /> 
2.通过component="input"可以定义输入框类型表单  但是这个FormItemComponent组件内有缺陷.  拿不到props.value值

### What is expected?
希望这个FormItemComponent组件的props里可以拿到value.   或者有办法拿到value值

### What is actually happening?
希望这个FormItemComponent组件的props添加不了value;

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome  79.0.3945.88 |

---
Form的value值  都是通过initialValues和onValuesChange设置初始值.   但是Item组件没有办法拿到value值.  不知道有什么好办法

**Comment by guiyu1230** [comment]
基于Form Item二次封装的组件ItemComponent不知道可以拿到props.value值吗.   可以理解为Form Item能否有value权限管理

**Comment by yoyo837** [comment]
上demo看看
