### ISSUE TITLE
Custom label on option doesn't work when dropdownRender is used

### ISSUE THREAD

**Issue by vandesh** [ant-design/ant-design#25647]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/distracted-paper-ltl5x)

### Steps to reproduce
* Use dropdownRender method in Select
* Add a label prop with any value to the Option tag

### What is expected?
The value in the label prop should be rendered after selection

### What is actually happening?
The selected rendered value is still picked up from the contents of option tag rather than the label prop

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome v83.0.4103.116  |

---
Here is a link to how it works with the label prop without using dropdownrender - https://codesandbox.io/s/bold-dust-ii2cx

**Comment by yoyo837** [comment]
`Option` does not support `label` prop.

**Comment by yoyo837** [comment]
```
          <Option key={value} value={value}>
            show value
          </Option>
```

**Comment by vandesh** [comment]
@yoyo837 That's what I thought from the docs. But then I saw this example and it works fine with label - https://codesandbox.io/s/bold-dust-ii2cx

**Comment by yoyo837** [comment]
It uses `optionLabelProp`

**Comment by MilosJo** [comment]
@vandesh @yoyo837 
Hi guys, I need opposite of this.. is it possible?
Per design I have label inside input, so when I choose something from dropdown it should always have prefix.
So I have option1, option2 and when I choose any, value of input should be "test: option1" for eg.

Thanks
