### ISSUE TITLE
Setting indeterminate state on `rowSelection` with `getCheckboxProps` no longer works

### ISSUE THREAD

**Issue by NobleMule** [ant-design/ant-design#25646]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-m78qu)

### Steps to reproduce
Set a checkbox's indeterminate property via the `getCheckboxProps` property of the `rowSelection` object

### What is expected?
It is expected that the checkbox column has a checkbox in an indeterminate state

### What is actually happening?
The checkbox appears unchecked

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.13.1 |
| System | Ubuntu 20.04 |
| Browser | Chromium Version 83 |

---
This issue _was not_ present in 4.3.5 but is present in all versions from 4.4.0 up to the latest (4.4.2 at time of writing). This link shows the exact same code working when using 4.3.5: [https://codesandbox.io/s/antd-reproduction-template-g4t3z](https://codesandbox.io/s/antd-reproduction-template-g4t3z)

**Comment by 07akioni** [comment]
could you explain why you use indererminate state manually？what scene is it for？

**Comment by NobleMule** [comment]
We have a table where you can select some rows and add, remove or modify options associated with the data. The modify action opens a modal with another table representing the available options for selected data. Where an option applies to all selected data objects, the checkbox is checked. Where it applies to none of the selected data object, it's unchecked. Where it applies to some of them, it's indeterminate. The user can then check or uncheck these options to modify what options are associated with the selected data objects.

**Comment by NobleMule** [comment]
@07akioni Thanks for fixing that so fast :pray:

Is there any idea when it will be released? Or do you have a suggested workaround that is quick to implement? We rely on other features of the rowSelection such as `preserveSelectedRowKeys` so I'd like to avoid implementing a completely custom selection column if possible :smiley:

**Comment by 07akioni** [comment]
If possible I will finish the pr tomorrow and release it this week. It will be released no later than next weekend.
