### ISSUE TITLE
table组件中的Column项中的fixed是string或boolean类型，但是现在只规定了boolean类型，ts中使用报错

### ISSUE THREAD

**Issue by 944832260** [ant-design/ant-design#25658]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#API](https://ant.design/components/table-cn/#API)

### Steps to reproduce
11

### What is expected?
修复

### What is actually happening?
11

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | win |
| Browser | 谷歌 |

**Comment by 07akioni** [comment]
https://github.com/react-component/table/blob/master/src/interface.ts#L22

It seems that the string type exists in rc-table

**Comment by 944832260** [comment]
> https://github.com/react-component/table/blob/master/src/interface.ts#L22
> 
> 似乎字符串类型存在于rc-table中
咱们别似乎行吗 ?我是 不知道咋贴图，能贴图的话早就贴了

**Comment by yoyo837** [comment]
直接粘贴

**Comment by 944832260** [comment]
> 直接粘贴

http://chuantu.xyz/t6/739/1594882431x-1404755402.jpg
上传到网络上了，看图片报错吧

**Comment by yoyo837** [comment]
比较模糊，电脑上直接截图，粘贴会清晰一些。

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/87637428-c3015680-c774-11ea-9222-d3a41ddfc539.png)


看上去是可以的

**Comment by 944832260** [comment]
> ![image](https://user-images.githubusercontent.com/6134547/87637428-c3015680-c774-11ea-9222-d3a41ddfc539.png)
> 
> 看上去是可以的

![image](https://user-images.githubusercontent.com/37320855/87637581-0cea3c80-c775-11ea-8efc-6256ae8b08c7.png)

**Comment by 944832260** [comment]
> ![image](https://user-images.githubusercontent.com/6134547/87637428-c3015680-c774-11ea-9222-d3a41ddfc539.png)
> 
> 看上去是可以的

![image](https://user-images.githubusercontent.com/37320855/87637844-681c2f00-c775-11ea-8e07-d522b5c1c91e.png)

**Comment by yoyo837** [comment]
用复现发代码吧，这样效率太低

**Comment by 07akioni** [comment]
> > https://github.com/react-component/table/blob/master/src/interface.ts#L22
> > 似乎字符串类型存在于rc-table中
> 
> 咱们别似乎行吗 ?我是 不知道咋贴图，能贴图的话早就贴了

发这个是为了辅助之后看这个 issue 的人判断。

**Comment by 944832260** [comment]
> 用复现发代码吧，这样效率太低

https://github.com/944832260/webpack4-react-ts/blob/master/src/pages/warehousing/warehousing.tsx
仓库拉代码看项目吧

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/87662972-a88ba500-c795-11ea-8e68-991dfbeada90.png)

能提供在线的最好，还能改代码。

**Comment by Xing-He** [comment]
Same error, need fix !!!

**Comment by Kermit-Xuan** [comment]
这个应该是由于没有给 `state` 写类型声明导致的，TS进行类型推导时把 `fixed` 推导成了 `string` 类型

试试这个: 
https://codesandbox.io/s/infallible-chaplygin-vjp81?file=/src/App.tsx

**Comment by 944832260** [comment]
> Same error, need fix !!!
> 
> ```js-jsx
> const column = [
>     {
>          .....,
>          fixed: 'right'
>     }
> ]
> 
> <Table column={column} datasource={[....]}/>
> ```

现在的fiexd只能设置true或者false，string类型不行的

> 这个应该是由于没有给 `state` 写类型声明导致的，TS进行类型推导时把 `fixed` 推导成了 `string` 类型
> 
> 试试这个:
> https://codesandbox.io/s/infallible-chaplygin-vjp81?file=/src/App.tsx

这个可以 3Q
