### ISSUE TITLE
Form表单嵌套出现样式错误

### ISSUE THREAD

**Issue by javaxiu** [ant-design/ant-design#2565]
#### 本地环境

- antd 版本:0.12.4
- 操作系统及其版本：linux 
- 浏览器及其版本: chromium 

#### 你期待的结果是：
嵌套的Form表单，FormItem里有Form

#### 实际上的结果：
出现字表单内的表单没有中心对齐

**Comment by benjycui** [comment]
`0.12.x` 已经不维护了。

另外，这样嵌套的话，数据你准备怎么处理，感觉很奇怪。。

**Comment by javaxiu** [comment]
不维护了吗？那为什么我直接npm install antd得到的就是0.12.17……

**Comment by benjycui** [comment]
因为你 package.json 的 dependencies 的写法问题，建议认真学习 semver
