### ISSUE TITLE
ConfigProvider is broken with Select inside a Form component

### ISSUE THREAD

**Issue by sagar7993** [ant-design/ant-design#25650]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-z937v?file=/index.js:695-710)

### Steps to reproduce
1. Create a form component
2. Create a select component inside Form.Item
3. Wrap the Select component inside Config.Provider to provide a custom empty message for the select when no options are available

### What is expected?
The select component should have worked as expected, when an option is selected, it should have updated the form values

### What is actually happening?
The select options don't work. When an option is selected, it doesn't update the form values

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | Mac OS X |
| Browser | Chrome (Latest) |

**Comment by yoyo837** [comment]
https://codesandbox.io/s/antd-reproduction-template-umrxc?file=/index.js
