### ISSUE TITLE
there is no dropdown`s x overflow at ur select 

### ISSUE THREAD

**Issue by sekune** [ant-design/ant-design#25666]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
just enable overflow x = auto

### What does the proposed API look like?
select

**Comment by 07akioni** [comment]
what is "ur select"?

**Comment by sekune** [comment]
> Hello @sekune. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @sekune, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)
