### ISSUE TITLE
Intractable List

### ISSUE THREAD

**Issue by alex20465** [ant-design/ant-design#25669]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Interacting with List items.. select / active etc.

### What does the proposed API look like?
Its not a special API feature, List items aren't there just for representation. To be able to interact with the list we need features like active/selected item onSelectItem(key: string) etc. I think the idea is clear. Bootstrap / Material have the same implementation. AntDesign current list implementation is just representational.

**Comment by afc163** [comment]
You can try https://prolist.ant.design/
