### ISSUE TITLE
The value of Select cannot be reseted in the afterClose Method of Modal.(Modal中的Select组件不能重置)

### ISSUE THREAD

**Issue by lovehall** [ant-design/ant-design#25665]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-turing-c7pr9?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
1.Choose one option
2.Click Cancel
3.Click New Collection
4.The value of Select cannot be reseted 

### What is expected?
The value of Select can be reseted in the afterClose Method of Modal

### What is actually happening?
The value of Select cannot be reseted in the afterClose Method of Modal

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | macOS |
| Browser | chrome83 |

**Comment by 07akioni** [comment]
Try `destroyOnClose`

**Comment by lovehall** [comment]
> Try `destroyOnClose`

Thanks!
