### ISSUE TITLE
Different behavior on table filter popover with scroll y and without scroll y

### ISSUE THREAD

**Issue by Cenume** [ant-design/ant-design#25668]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-bartik-bjkuq?file=/index.js)

### Steps to reproduce
try the debounced search from the popover. type in some search query and the table will filter itself in 0.5 second

Try the same thing with  // scroll={{ y: 100 }} (line 139) enabled

### What is expected?
retain the search popover when the table lost all data or changed from no data -> have data

### What is actually happening?
search popover destroyed when the table lost all data or changed from no data -> have data (only when the scroll y is enabled)

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.12 |
| System | any |
| Browser | any |

**Comment by hoho2017** [comment]
search no data,table resize and refresh,so the data is cleaned

**Comment by hoho2017** [comment]
https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel  this demo is all right

**Comment by Cenume** [comment]
@hoho2017 yeah, that demo doesn't use debounced search, if you press enter it is expected to disappear, however with debounce search, it is expected to retain the popover.

in my demo, the table without scroll-y works but with scroll-y it doesn't work, I think the behavior shouldn't be different

**Comment by afc163** [comment]
Duplicate of #29366
