### ISSUE TITLE
[4.x] Input 组件 size="small" 与 allowClear 同时使用时，会存在边框粗细不一致情况

### ISSUE THREAD

**Issue by lich-yoo** [ant-design/ant-design#25667]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hopeful-shaw-hs0de?file=/index.js)

### Steps to reproduce
组件设置属性 Input size="small" allowClear ，缩放浏览器比例 (模拟 win10 笔记本显示)，观察输入框边框。
当输入框处于 focus 状态时，比较明显。边框粗细不一致。

![image](https://user-images.githubusercontent.com/18572962/87657117-f51eb280-c78c-11ea-9835-b91aeb50a919.png)
![image](https://user-images.githubusercontent.com/18572962/87657163-04056500-c78d-11ea-8470-9e70fcf51b11.png)

### What is expected?
边框正常

### What is actually happening?
部分边框被内部 input 挡住

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | lastest |
| System | win10 |
| Browser | chrome |

**Comment by fireairforce** [comment]
mbp 这边好像显示不出来，你这个确实有点明显

**Comment by lich-yoo** [comment]
> mbp 这边好像显示不出来，你这个确实有点明显

@fireairforce 刚才拿同事的 mbp 试了下，也有问题。把所有缩放比例都试下。好像在 150% 和 250% 时比较明显。

**Comment by Kermit-Xuan** [comment]
这应该是边框的1像素问题吧？

**Comment by lich-yoo** [comment]
> 这应该是边框的1像素问题吧？

缺掉的宽度，正好是input 的宽度，应该是 input 位置异常，把边框给覆盖了

![image](https://user-images.githubusercontent.com/18572962/87662364-af65e800-c794-11ea-87ea-0a0a40a5afcd.png)

**Comment by lich-yoo** [comment]
严格来说缩放的样式问题也不是很大。 但是大部分 win 10 笔记本，系统缩放恰好是 150%。
对这部分笔记本用户来说 是必现。

**Comment by 07akioni** [comment]
这个问题感觉不是很好解决，不知道有没有对应的 css 属性能搞定。

**Comment by Kermit-Xuan** [comment]
https://codesandbox.io/s/brave-pare-xkkq1?file=/index.js

试试这个怎么样？

**Comment by lich-yoo** [comment]
> https://codesandbox.io/s/brave-pare-xkkq1?file=/index.js
> 
> 试试这个怎么样？

👍 加上指定 css，效果上正常了。

**Comment by zombieJ** [comment]
windows 系统缩放特别蛋疼，Table 的固定列对齐也是同样的问题。

**Comment by 07akioni** [comment]
> https://codesandbox.io/s/brave-pare-xkkq1?file=/index.js
> 
> 试试这个怎么样？

可以，相当 hack

**Comment by yoyo837** [comment]
有必要提交到仓库不？

**Comment by Kermit-Xuan** [comment]
我感觉没有必要吧，缩放可能会导致各种问题，这样改感觉治标不治本，大家觉得呢？

**Comment by 07akioni** [comment]
我觉得没必要：
1. 用 border 的地方太多了，需要一视同仁
2. 对于分辨率更高的屏幕，能完整展现缩放的，这种 hack 其实是对显示效果的损害

以及，你们说的缩放是系统缩放还是浏览器缩放= =

**Comment by Kermit-Xuan** [comment]
> 我觉得没必要：
> 
> 1. 用 border 的地方太多了，需要一视同仁
> 
> 2. 对于分辨率更高的屏幕，能完整展现缩放的，这种 hack 其实是对显示效果的损害
> 
> 
> 
> 以及，你们说的缩放是系统缩放还是浏览器缩放= =

浏览器缩放

**Comment by 07akioni** [comment]
那就更不能管了，浏览器缩放带来的潜在问题太多了，不值得去专门处理

**Comment by lich-yoo** [comment]
是的，这种边缘问题，本身优先级不高。且当前背景没有完美解决方案。

不应该用特殊处理去参杂到主线代码中。反而容易造成其他问题。

大家都一致认为不应该提交到仓库，先 close 处理。后续如果有其他人出现类似问题，可以采用 @Kermit-Xuan 的方法解决。
