### ISSUE TITLE
ant-design 官网国内镜像地址

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#25661]
## 国内镜像

| 版本 | 地址 |
| --- | --- |
| 4.x  |  http://ant-design.gitee.io       |
| 3.x  |  http://ant-design-3x.gitee.io |
| 2.x  |  http://ant-design-2x.gitee.io |
| 1.x   |  http://ant-design-1x.gitee.io |

**Comment by afc163** [comment]
@xrkffgg 改一下 3.x 的站点重新部署一下，让它能切换到 https://ant-design-3x.gitee.io

**Comment by xrkffgg** [comment]
改 footer 里的，还是在像 4.x 在 header 加个选项？

**Comment by afc163** [comment]
改所有出现镜像站点链接的地方。

**Comment by afc163** [comment]
另外 4.x 文档里，FAQ 里可以补一个国内镜像的问题。

**Comment by thlovey** [comment]
<img width="766" height="430" alt="Image" src="https://github.com/user-attachments/assets/74584ec0-74cc-414c-a1fc-1d1d4c9fec56" />这里的5.x地址错误了
