### ISSUE TITLE
能否增加”横“向Tree组件

### ISSUE THREAD

**Issue by kaoding** [ant-design/ant-design#25677]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在的Tree组件是”竖“向，希望可以增强现有的Tree组件或者增加”横“向树组件

### What does the proposed API look like?
和Tree保持一致，在节点处增加”操作“（如：可以直接增加节点，删除节点，修改该节点title）功能，同时也希望现有的Tree也可以增加”操作“功能。

**Comment by kaoding** [comment]
类似这种：
![image](https://user-images.githubusercontent.com/18542211/87741469-2e036980-c817-11ea-88f2-ae2227adacde.png)

**Comment by kaoding** [comment]
类似这种：
![image](https://user-images.githubusercontent.com/18542211/87741543-58552700-c817-11ea-9a5b-ee0692b76853.png)

**Comment by yoyo837** [comment]
看上去较业务化，个人感觉不太可能会考虑在antd实现。

**Comment by kaoding** [comment]
> 看上去较业务化，个人感觉不太可能会考虑在antd实现。

主要是可以实现”横“向Tree组件。
上面业务化的组件是让用户来做，只是用一些实例来说明”横“向组件用这个需求。

**Comment by Kermit-Xuan** [comment]
感觉你这个类似与流程图的概念，现有的tree组件应该满足不了你的需求

**Comment by kaoding** [comment]
> 感觉你这个类似与流程图的概念，现有的tree组件应该满足不了你的需求

把现有的tree组件”横“过来就行，节点的内容让用户自己的业务来实现。

**Comment by 07akioni** [comment]
> > 感觉你这个类似与流程图的概念，现有的tree组件应该满足不了你的需求
> 
> 把现有的tree组件”横“过来就行，节点的内容让用户自己的业务来实现。

你可能对“横”的结果以及它和现有实现的区别没有明确的预期。

比如现有的 tree 宽度不可变，“横”过来高度也不可变，但是你给的图明显高度是可变的。还有文字排列问题，虚拟滚动定宽问题，很多问题累积起来其实就让它变成了一个完全不同的东西。

总的来说是个完全不同的东西，不会在 tree 中实现的。

去找一些具有节点编辑功能的库对你实现这个需求会有更大的帮助，比如 g6 之类的。

**Comment by Kermit-Xuan** [comment]
> > > 感觉你这个类似与流程图的概念，现有的tree组件应该满足不了你的需求
> 
> > 
> 
> > 把现有的tree组件”横“过来就行，节点的内容让用户自己的业务来实现。
> 
> 
> 
> 你可能对“横”的结果以及它和现有实现的区别没有明确的预期。
> 
> 
> 
> 比如现有的 tree 宽度不可变，“横”过来高度也不可变，但是你给的图明显高度是可变的。还有文字排列问题，虚拟滚动定宽问题，很多问题累积起来其实就让它变成了一个完全不同的东西。
> 
> 
> 
> 总的来说是个完全不同的东西，不会在 tree 中实现的。
> 
> 
> 
> 去找一些具有节点编辑功能的库对你实现这个需求会有更大的帮助，比如 g6 之类的。

我就是这个意思

**Comment by afc163** [comment]
这个更多是可视化的组件，可以参考一下 G6 https://g6.antv.vision/zh/examples/net/dagreFlow#basicDagre

**Comment by kaoding** [comment]
> 这个更多是可视化的组件，可以参考一下 G6 https://g6.antv.vision/zh/examples/net/dagreFlow#basicDagre

要的就是这种组件，多谢 @afc163
