### ISSUE TITLE
The title of Upload Item is not close to the item

### ISSUE THREAD

**Issue by kitety** [ant-design/ant-design#25679]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#header](https://ant.design/components/upload-cn/#header)

### Steps to reproduce
1.upload a file

2.hover the file

image detail:https://imgkr.cn-bj.ufileos.com/4cc2e131-38b7-4436-9502-8f6014a6fd8b.png

### What is expected?
The title of Upload Item is close to the item

### What is actually happening?
The title of Upload Item is not close to the item

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | Antd official website version |
| System | win10 |
| Browser | Chrome 84.0.4147.89 |

**Comment by afc163** [comment]
It is wired to close Item by closing it as default behavior of Upload, I suggest you can cutomize your own upload list.
