### ISSUE TITLE
Table组件，若所有column都设置width属性，反而列头和内容无法对齐

### ISSUE THREAD

**Issue by qiannianv** [ant-design/ant-design#2567]
#### 本地环境

- antd 版本:1.6.5
- 操作系统及其版本：
- 浏览器及其版本:谷歌

#### 可重现的在线演示
备注：看官网上的例子，最后一列是没有设置width的，一定要最后一列不设置才能对其吗？

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by qiannianv** [comment]
1.6.5版本是不正常的，更新到1.7.0就正常了
