### ISSUE TITLE
Ts疑问, shouldCellUpdate 使用this.state的值,如果columns不设置sorter,则ts会将this.state认定为any类型. 配置了sorter又正常了.百思不得其解

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#25684]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.baidu.com](https://www.baidu.com)

### Steps to reproduce
看图...

### What is expected?
没配置sorter的时候,shouldCellUpdate使用this.state中的值不报ts错误

### What is actually happening?
没配置sorter的时候,shouldCellUpdate使用this.state中的值报ts错误

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16 |
| System | win10 |
| Browser | chrome |

---
codesandbox.io 没弄出来ts环境... 随便放了url上去,见谅.. 看2张截图.... 虽然ts报了一大堆错误,但是实际上运行的时候功能是正常的.

![903C5221701F1AA3D432888061DB3163](https://user-images.githubusercontent.com/15940920/87766357-9ff5a600-c84b-11ea-8dcb-64591c0194f7.jpg)

![43FEFCC0632E5C21708A741FC4249521](https://user-images.githubusercontent.com/15940920/87766404-b1d74900-c84b-11ea-937b-08eb1705e9b6.jpg)

![0F1977A9CAB253853F276EA65A208F6A](https://user-images.githubusercontent.com/15940920/87766426-b7cd2a00-c84b-11ea-87af-052c643df899.jpg)

**Comment by 07akioni** [comment]
我遇到过类似的问题，但是其实能跑好像就说明没问题。不知道哪里配错了

**Comment by Kermit-Xuan** [comment]
我在codesandbox上按照你的写了一个，没有出现你的错误

https://codesandbox.io/s/affectionate-engelbart-mb38p?file=/src/App.tsx

**Comment by 07akioni** [comment]
如果你发现最终编译没有问题的话，还是先想办法检查一下 vscode 的配置

**Comment by l745230** [comment]
@Kermit-Xuan 重现出来了
https://codesandbox.io/s/amazing-merkle-tg5hl?file=/src/App.tsx

**Comment by Kermit-Xuan** [comment]
应该是在columns 数组的类型推导出现了错误，你给 `shouldCellUpdate` 标注上返回给类型，或者给 `state` 加上类型声明就好了

https://codesandbox.io/s/reverent-jang-t5mwj?file=/src/App.tsx

**Comment by l745230** [comment]
@Kermit-Xuan 
原来如此,学会了!
顺便问一句,像这样的情况,我是自己写声明呢,还是可以等官方未来修复此ts问题?

**Comment by Kermit-Xuan** [comment]
官方是没有问题的，是你没有写声明，导致TS根据你写的值进行类型推导的时候出现了错误，所以在写TS的时候尽量都写上类型声明。

**Comment by l745230** [comment]
@Kermit-Xuan 明白了~蟹蟹指导~
