### ISSUE TITLE
Prop `className` did not match. Server in Nextjs

### ISSUE THREAD

**Issue by mehdiraized** [ant-design/ant-design#25688]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/pull/19380](https://github.com/ant-design/ant-design/pull/19380)

### Steps to reproduce
i have issue on nextjs

Warning: Prop `className` did not match. Server: "ant-badge ant-badge-rtl" Client: "ant-badge"

### What is expected?
fixed this

### What is actually happening?
The server side and the client side are not the same

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | Mac os v11 Big sur |
| Browser | chrome, safari, firefox |

**Comment by xrkffgg** [comment]
Maybe the problem is because of nextjs, not ant-design.
