### ISSUE TITLE
Add isActive prop in CollapsePanelProps

### ISSUE THREAD

**Issue by DidiBear** [ant-design/ant-design#25686]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The `isActive` prop is used in [`Collapse.Panel` in `rc-collapse` here](https://github.com/react-component/collapse/blob/master/src/Panel.jsx#L36) to set if the panel is open or closed.
However, this prop is not define in [`CollapsePanelProps` defined in `ant-design` here](https://github.com/ant-design/ant-design/blob/5290421ac92387054a2a9d5a80b7f8b4de1b7d3a/components/collapse/CollapsePanel.tsx#L6-L17).

This makes it inconvenient when creating a custom component that wraps the `Collapse.Panel`.

### What does the proposed API look like?
Add `isActive?: boolean` to `CollapsePanelProps`.

**Comment by 07akioni** [comment]
I don't think it will make a great difference when making a custom collapse. Could you provide a convincing example?

**Comment by afc163** [comment]
It is a inner props generated by `activeKeys`, we shouldn't use it.
