### ISSUE TITLE
Table head flicker when dynamic updating dataSource

### ISSUE THREAD

**Issue by maxiaochuan** [ant-design/ant-design#25689]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/empty-voice-5uerv?file=/src/App.js)

### Steps to reproduce
* set props scroll.y
* dynamic updating dataSource

### What is expected?
table head do not flicker

### What is actually happening?
table head flicker when dynamic updating dataSource

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.10.2 |
| System | mac |
| Browser | chrome, safari |

**Comment by zombieJ** [comment]
https://github.com/react-component/table/pull/406
