### ISSUE TITLE
offset in FormItem's labelCol isn't work if layout is vertical

### ISSUE THREAD

**Issue by gaara4896** [ant-design/ant-design#25680]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-kwt6x)

### Steps to reproduce
1. Make a form that layout is 'vertical'.
2. Make a FormItem, and set offset for its labelCol.
3. Show the form in browser, the offset setting didn't work.

### What is expected?
offset did worked in v2.X.X

### What is actually happening?
Input offset working but label does not offset properly

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | nextjs |
| System | Linux Kernel: 5.7.8-arch1-1 |
| Browser | Chromium Version 84.0.4147.89 (Official Build) Arch Linux (64-bit) |

**Comment by gaara4896** [comment]
Also, the issue had existed since 2018,which had been shown in issue https://github.com/ant-design/ant-design/issues/9962. However, it had been closed due to lack of reproduction.

**Comment by 07akioni** [comment]
form-item's style overrides col's style
