### ISSUE TITLE
Tree组件关闭虚拟滚动，并且设置高度时，展开节点时，会跳动，点击展开的节点，可能不在可视区域

### ISSUE THREAD

**Issue by YinRenjie1993** [ant-design/ant-design#25682]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upbeat-snowflake-x70c9?file=/index.js:1474-1481)

### Steps to reproduce
1.virtual设置为false height设置有值
2.先展开几个上面的树节点 让界面出现滚动条
3.滚动到底部 点击最下面可以展开的节点

### What is expected?
点击展开后 点击的节点还在可视区域

### What is actually happening?
点击展开后 滚动条会跳动  点击展开的节点可能在可视区域外 体验不好

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome 84 |

**Comment by YinRenjie1993** [comment]
![Jul-17-2020 15-51-35](https://user-images.githubusercontent.com/11569655/87762342-92d5b880-c845-11ea-8c14-27e67b303d5a.gif)

**Comment by 07akioni** [comment]
（推测）我感觉这可能是浏览器的行为，当触底之后增加高度不会维持原来的 top，而一致维持 bottom = 0。

**Comment by YinRenjie1993** [comment]
不是 height设置成 undefined就不对了

**Comment by zombieJ** [comment]
感觉是个 bug

**Comment by atonesapple** [comment]
你好，滚动效果实现了没右，tree加高度没有出滚动效果，是什么问题
？
