### ISSUE TITLE
nested  expandable table example's style  is broken 

### ISSUE THREAD

**Issue by sb-lee** [ant-design/ant-design#25681]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/staging-worker-z32c)

### Steps to reproduce
https://codesandbox.io/s/staging-worker-z32c7

### What is expected?
The alignment of the first column in each table row should look normal.

### What is actually happening?
The alignment of the first column in each table row is broken in large screen  browsers, 

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.12.0 |
| System | mac os lastest |
| Browser | chrome. lastest |

Capture
---
small screen browser

![image](https://user-images.githubusercontent.com/14502051/87753308-4d14f200-c83d-11ea-8280-86712f126c9f.png)

large screen browser
![image](https://user-images.githubusercontent.com/14502051/87753399-79307300-c83d-11ea-97b7-b38dd29f5526.png)

**Comment by saikumarf9** [comment]
Any solution for this @sb-lee?
