### ISSUE TITLE
Styles not loaded during SSR

### ISSUE THREAD

**Issue by mayinghan** [ant-design/ant-design#25696]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mayinghan/cra-ssr-demo](https://github.com/mayinghan/cra-ssr-demo)

### Steps to reproduce
first run `npm run build`
then run `npm run start-server`
then open localhost:3000

### What is expected?
I included a antd Button in the middle of the page. I used SSR in this demo. The button should have the ant design style (like a large blue button)

### What is actually happening?
The style of the button is missing. Styling is not working in SSR mode

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | React 16.12 |
| System | Mac os |
| Browser | Chrome latest |

---
服务端渲染情况下样式加载不出来
not able to load style when using SSR

**Comment by afc163** [comment]
`webpack.server.js` works on `server/index.js` only, you need a babel config for `src`.

**Comment by afc163** [comment]
Or import `antd/dist/antd.css` in App.css.

**Comment by mayinghan** [comment]
@afc163 as for the client side (things inside src/), I've already built it using `npm run build` which is provided by CRA. Do I need to override any of the CRA default packing config to make it work?

**Comment by mayinghan** [comment]
@afc163 The second solution works. A lot of thanks. Could you elaborate on the first solution you mentioned a little bit when you are available? Thanks sir
