### ISSUE TITLE
BackTop 组件在 Safari 浏览器下失效

### ISSUE THREAD

**Issue by beMySun** [ant-design/ant-design#25694]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8dozr)

### Steps to reproduce
1. 打开 https://codesandbox.io/s/8dozr
2. 往下拉
3. 在Safari 中， Up 按钮始终不出现， 在Chrome中正常。

### What is expected?
在 Safari 中 正常工作

### What is actually happening?
在Safari 中 工作不正常， UP 按钮始终不出现。

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | react |
| System | macOS 10.14.4 |
| Browser | Safari 版本 12.1.2 (14607.3.9) |

**Comment by beMySun** [comment]
![image](https://user-images.githubusercontent.com/12824205/87897530-41643e00-ca7e-11ea-8078-8af8d469812d.png)

**Comment by beMySun** [comment]
![image](https://user-images.githubusercontent.com/12824205/87897567-5c36b280-ca7e-11ea-9e1b-28602b16434a.png)

**Comment by beMySun** [comment]
![image](https://user-images.githubusercontent.com/12824205/87897588-6ce72880-ca7e-11ea-8cee-1a50a8c6940d.png)

**Comment by xrkffgg** [comment]
我这里 `OS 10.15.5`  `Safari 13.1.1`  正常

**Comment by beMySun** [comment]
官网demo: https://ant.design/components/back-top-cn/#header

![image](https://user-images.githubusercontent.com/12824205/87897835-17f7e200-ca7f-11ea-9fe2-c551182a3410.png)

**Comment by beMySun** [comment]
> 我这里 `OS 10.15.5` `Safari 13.1.1` 正常

看来我要悄咪咪升级一波系统， 然后告诉测试： 在我电脑上是好的。 哈哈

**Comment by xrkffgg** [comment]
没问题就关了哈。
