### ISSUE TITLE
Cascader not work correctly when value not matched in options

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#25692]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gallant-burnell-81t0t)

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-clarke-mwupb)

### Steps to reproduce
set a `value` which is not matched with `options`, e.g:

```
value={["Mars", "China"]}
```

### What is expected?
- no selected value show, user must select value from options manually when options not matched.

### What is actually happening?
- in 4.4.2, `Mars / China` show.
- in 3.26.18, no value no placeholder show.

![2](https://user-images.githubusercontent.com/29817353/87875899-f1966000-ca06-11ea-874d-1c9be159d028.jpg)
![1](https://user-images.githubusercontent.com/29817353/87875964-49cd6200-ca07-11ea-8b1f-c0722ad28a44.jpg)

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | latest |
| System | Mac OS |
| Browser | Chrome |

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/24058

**Comment by xrkffgg** [comment]
这个 issues 提出需要显示默认值：https://github.com/ant-design/ant-design/issues/23019

**Comment by xrkffgg** [comment]
If need to add an attribute to control these two situations? 
@afc163 @zombieJ @Kermit-Xuan

**Comment by zombieJ** [comment]
Select TreeSelect Cascader should display the value even not exist in the options. When user submit a Form, if not display the value, user will think the input is empty but it actually submitted invisible value.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/25707#issuecomment-661669441
