### ISSUE TITLE
Layout 布局 两端对齐问题

### ISSUE THREAD

**Issue by netskyline** [ant-design/ant-design#257]
如果要实现两端对齐（左右贴边不留空白），根据官网文档，使用了 row-flex-space-between，左右两边还是有空白，这个样式的实现是不是和 row-flex-space-around 的实现混淆了？

如果是我理解错了，没用对方法，请教正确用法，谢谢。

**Comment by netskyline** [comment]
justify-content 属性的 space-between 和 space-around 应该是下面截图中的对齐才对吧

![c2d35408-bf51-4e87-8851-98e23ff0f8b9](https://cloud.githubusercontent.com/assets/2669032/9812292/ea6c1046-58ae-11e5-9e17-7cf5e4a13b77.png)

**Comment by zhujun24** [comment]
是的，bug 修复中

**Comment by netskyline** [comment]
好的，辛苦了。。

**Comment by afc163** [comment]
ping~

**Comment by netskyline** [comment]
time=180119.804 ms

**Comment by zhujun24** [comment]
[275](https://github.com/ant-design/ant-design/pull/275)
