### ISSUE TITLE
Input.Group incorrect width when using %

### ISSUE THREAD

**Issue by joshua-lehmann** [ant-design/ant-design#25702]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-oqy7l?file=/index.js)

### Steps to reproduce
Use an antd input.group and add multiple antd elements with % width (total of 100%) 

### What is expected?
All input groups should have the same width, no matter how many elements are in there, because they all have 100% width in total

### What is actually happening?
Depending on the amount of elements the input group has a different width 

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.13.1 |
| System | Windows 7 |
| Browser | Chrome |

---
Maybe it has something to to with the shared borders of the elements in the input groups

**Comment by 07akioni** [comment]
deal it with css.
https://codesandbox.io/s/antd-reproduction-template-38jc3
i think there's n oneed to solve the problem inside the framework. since whether to solve it, there will always be edge cases.

**Comment by joshua-lehmann** [comment]
Of course you can fix it with this manual css, however I think that is more of a workaround and not a solution. And also I do not agree that it should not be solved always, because everything should have the same width by default. The edge case would be if you do not want it to be the same (100%) width, then you could apply your own css for an edge case. But by default it should work like every other component and just be 100% width without manual css.

**Comment by 07akioni** [comment]
I can't figure out a solution work at most scenes. Could you please provide some ideas? Thanks a lot.
