### ISSUE TITLE
input、textarea组件在Safari浏览器下输入卡死

### ISSUE THREAD

**Issue by lishaoh** [ant-design/ant-design#25708]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-q3vz2?fontsize=14&hidenavigation=1&theme=dark&file=/index.js](https://codesandbox.io/s/antd-reproduction-template-q3vz2?fontsize=14&hidenavigation=1&theme=dark&file=/index.js)

### Steps to reproduce
官方链接也可以测试

### What is expected?
Safari浏览器中可以输入中文

### What is actually happening?
输入英文没问题，输入中文卡死

| Environment | Info |
|---|---|
| antd | 3.25.2 |
| React | v16.8.6 |
| System | Mac |
| Browser | Safari  v13.0.5 |

**Comment by afc163** [comment]
无法重现。

**Comment by lishaoh** [comment]
@afc163 https://codesandbox.io/s/antd-reproduction-template-q3vz2?fontsize=14&hidenavigation=1&theme=dark&file=/index.js

**Comment by afc163** [comment]
还是无法重现。

![2020-07-22 15-03-19 2020-07-22 15_05_22](https://user-images.githubusercontent.com/507615/88145278-c8571900-cc2c-11ea-83c8-44e2138ebe30.gif)

1. 你可以尝试升级到 antd@3.x 以及 React 的最新版本。
2. 可以尝试升级到 antd 4.x，3.x 本身也不维护了。
3. 或者尝试升级 safari 和中文输入法到最新版本。

**Comment by lishaoh** [comment]
Safari 浏览器13.1.x版本是OK的，只是在v13.0.4、v13.0.5版本（其他13.0.x版本没有测试过）会出现这个问题

**Comment by afc163** [comment]
@lishaoh React 版本升上去试试，大概率是 Safari 自己的问题。

**Comment by DDDrop** [comment]
Safari 打开 ant 的首页后，各种组件都很卡。

**Comment by 07akioni** [comment]
> Safari 打开 ant 的首页，各种组件都很卡。
> 
> `Safari Version 13.1.2 (15609.3.5.1.3)`

电脑的配置如何？

**Comment by 07akioni** [comment]
> Safari 打开 ant 的首页，各种组件都很卡。
> 
> `Safari Version 13.1.2 (15609.3.5.1.3)`

这个 issue 里面提到的是 3.x 版本，如果你感觉 4.0 版本的问题可以复现的话，可以开一个新的 issue
