### ISSUE TITLE
buy theme ant design pro for angular

### ISSUE THREAD

**Issue by trunghoang1991** [ant-design/ant-design#25703]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want buy theme ant design pro for angular, design basic include page table list, form, and dashboard

### What does the proposed API look like?
I not need api mock data, all only is HTML use component of ng zorro

**Comment by afc163** [comment]
wrong repo.
