### ISSUE TITLE
Make Select Use a Tray on Mobile devices instead of a dropdown menu,

### ISSUE THREAD

**Issue by Rocinante89** [ant-design/ant-design#25709]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using the select component, it would be great user experience if mobile users could see a tray instead of a dropdown menu.

Users expect web apps these days to function as well on mobile devices as on desktops, so the framework should enable functionality like above in order to facilitate that.

### What does the proposed API look like?
maybe add an isMobile prop to that would enable the functionality if it was set to true

**Comment by Rocinante89** [comment]
![Image](https://user-images.githubusercontent.com/8224386/87927972-f9dcb280-ca7b-11ea-8bcd-88f98dd6bd15.gif)

**Comment by afc163** [comment]
antd don't provide mobile support, please try other mobile UI library.
