### ISSUE TITLE
Upload组件上传状态一直处于uploading

### ISSUE THREAD

**Issue by ypwlal** [ant-design/ant-design#2570]
#### 本地环境

- antd 版本: 1.7.5
- 操作系统及其版本：window 10 
- 浏览器及其版本: chrome52.0.2743.82  firefox 47.0.1

#### 你做了什么？

引入antd，使用Upload组件，对照官方demo

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：

在onChange打印files对象，其中文件对象
     status一直为uploading
     event一直为undefined
     response一直为undefined

> 更换为antd 1.6.4后可以正常使用；

**Comment by benjycui** [comment]
现在最新版本是 1.7.0，先升级试试吧。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2423
