### ISSUE TITLE
ability to disable checkbox on ant design tree parents

### ISSUE THREAD

**Issue by mx2323** [ant-design/ant-design#25715]
- [ X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
i would like to be able to not show the checkboxes on parents in ant tree, and only show them for children

### What does the proposed API look like?
a single boolean prop on the Ant Tree Component to toggle parent checkboxes.

![image](https://user-images.githubusercontent.com/528124/87998905-81471780-cab6-11ea-80eb-9750c28330d6.png)
I would like to hide checkboxes on the two parents and only show checkboxes on the leaf nodes (CALL_CENTER, CATALOG_PAGE, CATALOG_RETURNS), etc.

**Comment by afc163** [comment]
https://codesandbox.io/s/peaceful-heisenberg-prv09
