### ISSUE TITLE
Ability to make Enable / Disable Affix

### ISSUE THREAD

**Issue by andypho** [ant-design/ant-design#25714]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The ability to the control when the affix will stick to the view port.
When Affix is disable the content inside will remain on the default location.
One of the example is I do not want affix to be disabled when its in mobile view, but enable in desktop view.

### What does the proposed API look like?
Adding `disabled` to Affix props

**Comment by afc163** [comment]
```
disabled ? <Node /> : (
  <Affix>
    <Node />
  </Affix>
)
```

Try this way.

**Comment by andypho** [comment]
> ```js-jsx
> disabled ? <Node /> : (
>   <Affix>
>     <Node />
>   </Affix>
> )
> ```
> 
> Try this way.

This is the way i currently using, but the thing is I will have 2 <node /> .
When i resize from desktop to mobile view, the node will in different state.

**Comment by afc163** [comment]
```jsx
const node = <Node />;

disabled ? node : (
  <Affix>
    {node}
  </Affix>
)
```

**Comment by monolithed** [comment]
The disabled property is already present in Slider, Switch, TimePicker and other components, so this issue should be reopened as a feature request for compliance and consistency as well.

**Comment by JesperWe** [comment]
For anyone else finding this:

There are rendering issues with @afc163 suggested approach, but I got things to work with this "poor mans" disable approach:

	<Affix offsetTop={ 12 } target={ disabled ? null : undefined }>

(The Affix does not work when target = null, so this is a disable. For target = undefined it defaults to window as target).
