### ISSUE TITLE
组件无法正常渲染，这是哪里出了问题？

### ISSUE THREAD

**Issue by yuyic** [ant-design/ant-design#25725]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yuyic/antdtest](https://github.com/yuyic/antdtest)

### Steps to reproduce
yarn dev

### What is expected?
正常渲染

### What is actually happening?
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | ^16.12.0 |
| System | window 10 |
| Browser | Chrome |

**Comment by yoyo837** [comment]
提示很清晰：Invalid hook call. Hooks can only be called inside of the body of a function component.

**Comment by yoyo837** [comment]
提供的repo不能复现

**Comment by yuyic** [comment]
删除node_modules重装后问题消失。
