### ISSUE TITLE
antd4.0无法使用less实时改变主题颜色

### ISSUE THREAD

**Issue by MrMeiyu** [ant-design/ant-design#25727]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://无](http://无)

### Steps to reproduce
```
onChangeComplete = (sketchColor) => {
    const changeColor = () => {
      window.less
      .modifyVars({
        '@primary-color': sketchColor,
      })
      .then(() => {
        localStorage.setItem('themeColor',sketchColor);
      });
    };
    window.less = {
      async: true,
      javascriptEnabled: true,
    };
    loadScript('/lib/less.min.js').then(() => {
      changeColor();
    });
  }
```

### What is expected?
能使用less在线修改主题颜色或者是其它更好的方法

### What is actually happening?
在antd4.0使用less.modifyVars不能更新当前主题

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.3.1 |
| System | mac |
| Browser | 73.0.3683.86 |

---
如果我在antd4.0中单独加载 "  @import '~antd/lib/index.less'  " 是可以实时修改颜色的，但是这样所有的组件的样式不全（除了颜色其它的样式没有） ；如果我按照官方使用 “   @import '~antd/dist/antd.less'   ” 这个less文件以后我就不能使用less实时修改颜色

**Comment by afc163** [comment]
我们没有官方提供这方面的功能，也不做相关的答疑，建议搜索 issues 看看。

**Comment by MrMeiyu** [comment]
@afc163 那请问一下，你们内部现在使用antd会有在线修改主题的需求嘛？如果有的话能方便说下是怎么做的嘛？

**Comment by afc163** [comment]
我们这类需求比较少，你可以看看

- https://github.com/mzohaibqc/antd-theme-generator 
- https://github.com/emeks-studio/antd-custom-theme-generator
- https://github.com/ycjcl868/theme-switcher
- https://github.com/chenshuai2144/umi-plugin-antd-theme

**Comment by MrMeiyu** [comment]
@afc163 欧克，谢谢大佬

**Comment by pengcui123** [comment]
请问下你们antd网站那个右下角更换主题是怎么实现的呀@afc163
