### ISSUE TITLE
Table组件中selection在树形表格中错位

### ISSUE THREAD

**Issue by codingbycat** [ant-design/ant-design#25736]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elated-diffie-rvg1k)

### Steps to reproduce
当children不设置，即没有children字段一切正常，但是当children设置为false 或者 null，selection会发生错位的情况

### What is expected?
selection不错位，与不设置children表现一直

### What is actually happening?
selection错位

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | "react": "^16.11.0" |
| System | macOS Catalina 10.15.2 |
| Browser | Chrome 84.0.4147.89（64-bit） |

**Comment by codingbycat** [comment]
暂时可以通过设置css进行粗暴的解决，不过不知道会影响什么其他功能上的使用
``` less
.ant-table-selection-column {
  > .ant-table-row-expand-icon {
    display: none;
  }
}
```

**Comment by afc163** [comment]
Current behavior is not same as 3.x which is correct.
