### ISSUE TITLE
autocomplete 下拉框没有被 Input suffix上的onClick事件阻止。

### ISSUE THREAD

**Issue by kairi1227** [ant-design/ant-design#25732]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-brattain-jgn9h)

### Steps to reproduce
`Input` 作为 `AutoComplete`的自定义组件。

设置  `Input` 的 `suffix`属性。

在`suffix`的组件上设置 `onClick`事件，事件内容：
```
e.stopPropagation(); 
e.preventDefault();
```

### What is expected?
单击 `Input` 的 `suffix` 时，阻止aucomplete的下拉框显示

### What is actually happening?
下拉框展开了

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | window 10 |
| Browser | chrome 84 |

**Comment by 07akioni** [comment]
```
onMouseDown={e => {
  e.stopPropagation();
  e.preventDefault();
}}
```

**Comment by kairi1227** [comment]
@07akioni  感谢，生效了。
