### ISSUE TITLE
checkbox.group 个数限制，当个数限制3个时，未选中的chekbox 禁止点击

### ISSUE THREAD

**Issue by WangXiaoXiaoG** [ant-design/ant-design#25745]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了当需求只能限定选择N个时，当超过N个时，其他不可点击，就像上传图片一样，可以限制个数。 

### What does the proposed API look like?
checkbox.group    limit：3

**Comment by afc163** [comment]
建议自行封装，不难。

**Comment by WangXiaoXiaoG** [comment]
嗯嗯，封装了
