### ISSUE TITLE
<Table /> - Table Body Scroll in Y-direction - unused and disabled.

### ISSUE THREAD

**Issue by sdenisen** [ant-design/ant-design#25749]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-hooks-3m9nx?file=/src/App.js)

### Steps to reproduce
I have an Ant Design table. By default table style attribute set to "table-layout: auto". To set the width of the table columns properly there is need to use the following ant-Table property: 
           scroll={{x:"max-content", y:"max-content"}}

So in that case, "table-layout" attribute of ant-Table control is set to "fixed" and the table with that attribute gets sturdier and predictable, but from the right side of the table, there is appeared disabled "Y-scrollbar".

### What is expected?

I expected that HTML table control will have an attribute: "table-layout: fixed" without any scrollbars for X and Y directions.
X or Y scrollbars should appear only when the height/width of the table is oversize. 

 

### What is actually happening?
In case of using property scroll={{x:"max-content", y:"max-content"}}.
There is appeared disabled "Y-scrollbar" from the right side of the HTML table. 

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.12.0 |
| System | macOS - 10.15.5 |
| Browser | Chrome,  version: 83.0.4103.116  |

---
The same situation was with the header of the ant-Table:
https://github.com/react-component/table/pull/219

**Comment by zombieJ** [comment]
Use `tableLayout` prop.
