### ISSUE TITLE
Cascader级联选择的 多选功能

### ISSUE THREAD

**Issue by KouSum** [ant-design/ant-design#25752]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Select选择器 和 Tree树形控件    如果选择项太多 需要滚动不是特别方便，横向的联级多选操作上会方便一点，至少在PC端 

### What does the proposed API look like?
.

**Comment by afc163** [comment]
Duplicate of #23410

**Comment by ZFtime** [comment]
弱弱的问一句，大佬们，你们用什么做的ant里面的级联多选？？？

**Comment by lm1073330969** [comment]
> 弱弱的问一句，大佬们，你们用什么做的ant里面的级联多选？？？

我也想问下 级联多选 ant里面的怎么实现

**Comment by HelKyle** [comment]
> 弱弱的问一句，大佬们，你们用什么做的ant里面的级联多选？？？

我也有同样的需求，尝试自己实现了一个简单版的级联多选，欢迎试用

代码在这 😃：https://github.com/HelKyle/antd-multi-cascader
这是如何实现的文章📝：https://juejin.cn/post/6914994241940750343
