### ISSUE TITLE
如何结合Form.List和Table

### ISSUE THREAD

**Issue by fatesq** [ant-design/ant-design#25750]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望通过Form.List创建一个Table形式的表单提交

**Comment by liweitao92** [comment]
https://github.com/ant-design/pro-list
你要的是这个？

**Comment by Aysnine** [comment]
https://codesandbox.io/s/antd-rich-list-demo-j5d14

https://codesandbox.io/s/antd-rich-list-demo-v2-z7wjf

**Comment by jws132** [comment]
有没有树形表单的例子
![image](https://user-images.githubusercontent.com/10203374/208356469-ee170003-4c61-4727-8ba4-8541a044e1a8.png)

**Comment by louhaojie99** [comment]
[这或许是 Form.List和Table最佳实践。](https://louhaojie99.github.io/pro-components/components/editable-table)
