### ISSUE TITLE
BackUp组件再Chrome 51.0.2704.166m下不渲染的问题

### ISSUE THREAD

**Issue by IIIThSoul** [ant-design/ant-design#25753]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://内部项目，无法提供](http://内部项目，无法提供)

### Steps to reproduce
调用BackUp组件，并在Chrome51.0.2074下预览

### What is expected?
下滑页面，可以看到 BackUp

### What is actually happening?
没有看到BackUp，查看页面元素，元素没有被渲染出来

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.12.0 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
Chrome 51 版本太低了，不再提供相关的支持。
