### ISSUE TITLE
treeSelect showSearch and onBlur behave improperly 

### ISSUE THREAD

**Issue by crowcc** [ant-design/ant-design#25751]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://hr1kw.csb.app/](https://hr1kw.csb.app/)

### Steps to reproduce
Input something in the TreeSelect Component, don't select any option, then blur it

### What is expected?
1. If I didn't select any option, TreeSelect should clear the input value when blur, just behave like the Select Component
2. The TreeSelect onBlur event should be triggered only when blur

### What is actually happening?
1. TreeSelect didn't clear the input value when blur 
2. The TreeSelect onBlur event was triggered  when focus and when blur

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.1 |
| System | windows; mac |
| Browser | chrome |

**Comment by afc163** [comment]
3.x is not maintianed anymore, please try 4.x.

**Comment by afc163** [comment]
4.x is ok: https://codesandbox.io/s/antd-reproduction-template-83hfc?file=/package.json
