### ISSUE TITLE
Remove formats from locales

### ISSUE THREAD

**Issue by andrestaht** [ant-design/ant-design#25756]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Removes confusion when looking/creating the locale files and required time to understand that they are not used and can be ignored.

### What does the proposed API look like?
Remove yearFormat, dateFormat, dayFormat and dateTimeFormat from locale files.

**Comment by afc163** [comment]
trace #23902
