### ISSUE TITLE
DatePicker没办法接受moment(null)无效的日期类型

### ISSUE THREAD

**Issue by tangtangtangtangtang** [ant-design/ant-design#25761]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-shtern-dvpuf?file=/index.js)

### Steps to reproduce
1. 使用renderExtraFooter创建一个footer
2. footer点击并设置value为moment(null)
3. 所有的日期都变为了NaN

### What is expected?
1. 期望能通过moment(null)无效日期的方式能够设置一个特殊的日期，这个特殊的日期不属于任何一天，比如一个无截止日期
2. 并且选择这个日期后日历的功能展示不受影响
3. 这在antd3.x是没有问题的

### What is actually happening?
1. 所有的日期都变为了NaN，即使清空value也没办法回去了
2. 我无法再重新选择别的日期

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | latest |
| System | macos |
| Browser | 83.0.4103.116 |

**Comment by yoyo837** [comment]
moment原则上不支持传递null，个人认为应该从业务层面处理，比如无值表示不限或者2999年这种特别大的值

**Comment by yoyo837** [comment]
3.x能这么干应该是利用了一个怪异行为，或者是bug

**Comment by tangtangtangtangtang** [comment]
> moment原则上不支持传递null，个人认为应该从业务层面处理，比如无值表示不限或者2999年这种特别大的值

给后端的数据上是用特殊值去代表的，只是我前端需要正常展示...想到的是用无效的moment值，并且moment可以去设置这个无效的时候显示啥。4.x不行了吗。。。那我咋办

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/15920

3.x 也没准备支持，可以把这个 warning 在 v4 里也加一下。

**Comment by tangtangtangtangtang** [comment]
> #15920
> 
> 3.x 也没准备支持，可以把这个 warning 在 v4 里也加一下。

那就是以后也不准备支持这种类似的是吗？我需要另辟蹊径了吗

**Comment by zombieJ** [comment]
嗯，暂无计划。

**Comment by zombieJ** [comment]
看了一下，v4 也是有 warning 的。 issue close.
