### ISSUE TITLE
ERROR in ./node_modules/antd/es/index.js

### ISSUE THREAD

**Issue by eBerdnA** [ant-design/ant-design#25762]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/eBerdnA/antdRepro](https://github.com/eBerdnA/antdRepro)

### Steps to reproduce
    npm install
    npx webpack

### What is expected?
No error

### What is actually happening?
    ERROR in ./node_modules/antd/es/index.js
    Module not found: Error: Can't resolve './affix' in 'C:\dev\antdRepro\node_modules\antd\es'
     @ ./node_modules/antd/es/index.js 3:0-43 3:0-43
     @ ./src/index.tsx

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Microsoft Edge (Chromium) |

**Comment by afc163** [comment]
```diff
  // webpack.config.js
  resolve: {
-   extensions: [".ts", ".tsx"]
+   extensions: [".js"]
  },
```
