### ISSUE TITLE
日期组件支持多选

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-design#25766]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决处理选择不连续的多个时间选项的问题
例如:选择 20200918 和20190822和20180917
现在仅支持时间范围和单个时间
在网上查询这类需求比较多,但是没有成型的解决方案

### What does the proposed API look like?
提供参数
[type]单选或者多选(类型下拉框的单选和多选)
[count]可设置选项个数
[value]返回参数为['20191020','20200809']数组

**Comment by afc163** [comment]
Duplicate of #4447
