### ISSUE TITLE
下拉框搜索拼音输入法光标位置错误

### ISSUE THREAD

**Issue by nextdoorUncleLiu** [ant-design/ant-design#25769]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
在上述版本的状态下
<Select
  mode="multiple"
  showSearch
  optionFilterProp="children"
>...</Select>
搜索 option 的内容，拼音输入，然后删除，在输入数字，这时候光标会往前跳一位

### What is expected?
期望光标位置正确

### What is actually happening?
实际不正确

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome 83.0.4103.116 |

**Comment by 07akioni** [comment]
给一个 CodeSandbox 的复现链接？
