### ISSUE TITLE
表头分组中间组合并样式错乱

### ISSUE THREAD

**Issue by lemovel** [ant-design/ant-design#25771]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/7xpx8?file=/index.js:159-1589

### Steps to reproduce
表头分组，合并行的children不能有分组，否则样式错乱

### What is expected?
支持这种分组

### What is actually happening?
将上面链接的columns 改成我自身的columns会有样式错乱

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.0 |
| System | 78 |
| Browser | chrome |

---
 const columns = [
      {
        title: 'Name',
        dataIndex: 'name',
        key: 'name',
        width: 100,
        fixed: 'left',
        rowSpan: 4,
        filters: [
          {
            text: 'Joe',
            value: 'Joe',
          },
          {
            text: 'John',
            value: 'John',
          },
        ],
        onFilter: (value, record) => record.name.indexOf(value) === 0,
      },
      {
        title: 'Other',
        rowSpan: 1,
        children: [
          {
            title: 'Age',
            dataIndex: 'age',
            key: 'age',
            width: 150,
            rowSpan: 2,
            sorter: (a, b) => a.age - b.age,
            children: [
              {
                title: '111',
                dataIndex: 'age',
                key: 'age',
                width: 150,
                rowSpan: 1,
                sorter: (a, b) => a.age - b.age,
              }
            ]
          },
          {
            title: 'Address',
            children: [
              {
                title: 'Street',
                dataIndex: 'street',
                key: 'street',
                width: 150,
              },
              {
                title: 'Block',
                children: [
                  {
                    title: 'Building',
                    dataIndex: 'building',
                    key: 'building',
                    width: 100,
                  },
                  {
                    title: 'Door No.',
                    dataIndex: 'number',
                    key: 'number',
                    width: 100,
                  },
                ],
              },
            ],
          },
        ],
      },
    ]

**Comment by lemovel** [comment]
已跟进

**Comment by yoyo837** [comment]
看上去正常的

**Comment by lemovel** [comment]
https://codesandbox.io/s/stupefied-williamson-df5j1

你拉到最后，看，表头有缺失，而且表头展现给代码逻辑不一致，感觉像右边的往左边移了呢

**Comment by yoyo837** [comment]
https://codesandbox.io/s/silent-sun-u27id?file=/index.js

这样吗？

**Comment by lemovel** [comment]
额，我是Age 那个表头，age要占2个rowspan，111占一个

**Comment by zombieJ** [comment]
@lemovel 你把你要的结构画出来看看
