### ISSUE TITLE
Cascader matchInputWidth not working as expected

### ISSUE THREAD

**Issue by chrisque5** [ant-design/ant-design#25779]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/chrisque5/pen/NWxoZPG](https://codepen.io/chrisque5/pen/NWxoZPG)

### Steps to reproduce
Set showSearch with matchInputWidth: true

### What is expected?
Expecting the dropdown width to match the input width.

### What is actually happening?
Dropdown width not working as expected. Or unable to set custom with for dropdown.

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.9.0 |
| System | All |
| Browser | All |

**Comment by afc163** [comment]
There is no `matchInputWidth` prop in Cascader.

**Comment by chrisque5** [comment]
![image](https://user-images.githubusercontent.com/2912399/88272201-f1e67200-cd0a-11ea-9119-b2b87c47e1a4.png)

As specified in the documentation for Cascader, https://ant.design/components/cascader/#API **matchInputWidth** isn't a field is showSearch property?

**Comment by afc163** [comment]
Sorry, it is. However it works in this way:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/507615/88272583-851fa780-cd0b-11ea-9246-0bcf9658656b.png">

<img width="638" alt="image" src="https://user-images.githubusercontent.com/507615/88272675-a54f6680-cd0b-11ea-98d0-3faa35dccc1e.png">

**Comment by chrisque5** [comment]
Thanks for the explanation. May be an example in the documentation would avoid such misunderstanding.

**Comment by afc163** [comment]
Link API doc to here: https://github.com/ant-design/ant-design/commit/c299f1c4204935767a3b7ff741ffb311421f6491
