### ISSUE TITLE
Table中启用排序(or 将title设为Tooltip组件)，点击悬浮框也会触发Table的排序

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design#25773]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/th9z4)

### Steps to reproduce
鼠标移入表头，显示出tooltip，点击tooltip

### What is expected?
点击tooltip，对排序无影响

### What is actually happening?
点击tooltip会触发该列的排序

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.12.0 |
| System | MacOs |
| Browser |  chrome 83.0.4103.61 |

---
禁用Table的Tooltip，重写title为Tooltip 结果是一样的

如果只是将Tooltip元素内的冒泡阻止掉，边框以及箭头的位置也可以触发排序，不能完全解决这个问题

**Comment by afc163** [comment]
为啥要阻止掉，点击 tooltip 触发应该也合理。

**Comment by XiaoJiuDYS** [comment]
tooltip中包含跳转链接（或者其他点击事件）的情况 就会显得很奇怪

**Comment by afc163** [comment]
这个不是 Table 自带的排序提示么，为啥会有链接？

**Comment by XiaoJiuDYS** [comment]
禁掉了自带的，重写title 为Tooltip （抱歉，demo没能完全体现）

**Comment by afc163** [comment]
来个重现看看。

**Comment by XiaoJiuDYS** [comment]
https://codesandbox.io/s/vigorous-cohen-99bc9

**Comment by afc163** [comment]
https://codesandbox.io/s/musing-sound-cccfs?file=/index.js

**Comment by XiaoJiuDYS** [comment]
这样带来的新问题是 点击表头的文字就不会触发排序了

**Comment by afc163** [comment]
https://codesandbox.io/s/gallant-carson-x310b?file=/index.js

**Comment by XiaoJiuDYS** [comment]
这种我也尝试过了
如果只是将Tooltip元素内的冒泡阻止掉，边框以及箭头的位置也可以触发排序

**Comment by afc163** [comment]
https://codesandbox.io/s/bold-fog-k3fjh?file=/index.js

**Comment by XiaoJiuDYS** [comment]
👍      可以了！
