### ISSUE TITLE
Upload in Mobile Firefox not support multiple image upload

### ISSUE THREAD

**Issue by zhuzhuyule** [ant-design/ant-design#25770]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/upload/#components-upload-demo-fileList](https://3x.ant.design/components/upload/#components-upload-demo-fileList)

### Steps to reproduce
1. open mobile Firefox and navigation to  'https://3x.ant.design/components/upload/#components-upload-demo-fileList'
2. click `upload` button
3. Slected two ore more than two images
4. confrim upload those images
5. just upload one image

### What is expected?
If i select three images, i expect to upload thress images.

### What is actually happening?
I select three images, just upload one images.

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.12.1 |
| System | Android 10 |
| Browser | Android Firefox 68.10.1 |

---
just in firefox for android

**Comment by afc163** [comment]
We don't provide offcial support for mobile devices, but feel free to give us PR if you find solution.

**Comment by zhuzhuyule** [comment]
Just like Firefox for android has this issue, because the Android Firefox 68.10.1 not support `<input type="file" multipul=true />`, it always called `onChange` event once however one or more images selected.
