### ISSUE TITLE
InputNumber value prop does not work nested inside Form.Item

### ISSUE THREAD

**Issue by qydchen** [ant-design/ant-design#25785]
- [ X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-j5hp1q-ifyk6e](https://stackblitz.com/edit/react-j5hp1q-ifyk6e)

### Steps to reproduce
1. Take a look at the NumberInput with the label `not-working`.

### What is expected?
Expect the value prop of NumberInput to be displayed in the input of `not-working`

### What is actually happening?
The value prop of NumberInput is not displayed even though the value prop was passed through. It looks like somehow the prop name in Form.Item is preventing the NumberInput to show its initial value. 

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome |

---
I attempted to remove the prop name to solve my issue and it worked, but that caused issues in my project because removing the prop name also disabled the rules prop in Form.Item

**Comment by afc163** [comment]
https://ant.design/components/form/#Why-is-component-defaultValue-not-working-when-inside-Form.Item
