### ISSUE TITLE
Select选择器多选后，input内是否支持图中这种效果

### ISSUE THREAD

**Issue by zlyyyy** [ant-design/ant-design#25787]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
![image](https://user-images.githubusercontent.com/22760932/88369947-b065cd80-cdc3-11ea-9ebc-bfec142c0419.png)

### What problem does this feature solve?
遇到个需求多选后再选择字段升降序

### What does the proposed API look like?
支持自定义多选后的dom

**Comment by afc163** [comment]
You can try `tagRender`.

**Comment by zlyyyy** [comment]
mode multiple | tags 模式下选中取消选中的动画是否支持移除，现在自定义tagRender的话，有明显的延迟 @afc163
