### ISSUE TITLE
setFields 属性如何设置？

### ISSUE THREAD

**Issue by sxlfzhy** [ant-design/ant-design#2578]
form  setFields 属性如何设置？如何设置error？

**Comment by iiitmahesh** [comment]
How set an object with fields for antd  form??

var data =  {};
this.props.form.setFields(data);

**Comment by iiitmahesh** [comment]
How to use this while form creating mapPropsToFields

```
class CustomizedForm extends React.Component {}
CustomizedForm = Form.create({})(CustomizedForm);
```

**Comment by iiitmahesh** [comment]
I got it .

const CreateLr = Form.create({

    mapPropsToFields(props) {
    return {
      username: {
        ...props.username,
        value: props.username.value.toUpperCase(),
      },
    };
  }

})(CreateLrForm);
