### ISSUE TITLE
请教一下：如果一个Form中有两个input，这两个input至少需要填写一个，rule需要怎么设置？

### ISSUE THREAD

**Issue by sxlfzhy** [ant-design/ant-design#2579]
请教一下：如果一个Form中有两个input，这两个input至少需要填写一个，rule需要怎么设置？求高手解答

**Comment by benjycui** [comment]
自定义校验规则 http://ant.design/components/form#components-form-demo-validate-customized

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
