### ISSUE TITLE
There is no way to change sorter tooltip text in Table component?

### ISSUE THREAD

**Issue by Frontovichok** [ant-design/ant-design#25791]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The ability to translate sorter tooltip text into different languages

### What does the proposed API look like?
add sorterTooltipText attribute to the columns object

**Comment by afc163** [comment]
``
<Table locale={{ triggerDesc: 'xxx' }} />
```

https://github.com/ant-design/ant-design/blob/4ad1ccac277782d7ed14f7e5d02d6346aae0db67/components/locale/default.tsx#L19

**Comment by Prerna-Gusain-PST** [comment]
> 

This will change the text for each and every column, what if I want to customize the text for only one key in column?
