### ISSUE TITLE
RangePicker onClick type definition differs from docs

### ISSUE THREAD

**Issue by albertms10** [ant-design/ant-design#25799]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
`DatePicker.RangePicker` `onClick` function is wrongly defined as `rc-picker`’s `onClick`, which differs from documentation:
```js
onClick: (values: RangeValue<DateType>, formatString: [string, string]) => void
```

<img width="679" alt="Captura de Pantalla 2020-07-24 a les 21 36 52" src="https://user-images.githubusercontent.com/26429103/88429126-63e7b580-cdf6-11ea-82a4-4aa754bcb7c6.png">

A reproduction sandbox can be found [here](https://codesandbox.io/s/antd-reproduction-template-ih8tm). If you `Ctrl/Cmd + click` on the `onChange` component prop, the reference leads to the wrong method definition. CodeSandbox does not complain about it, but WebStorm does (as seen in the screenshot).

### What does the proposed API look like?
`DatePicker.RangePicker` `onClick` function should be defined as in [documentation](https://ant.design/components/date-picker/#RangePicker):
```js
onClick: (dates: [moment, moment], dateStrings: [string, string]) => void
```

**Comment by albertms10** [comment]
Just updated the main issue with a reproduction link and further explanation.

**Comment by afc163** [comment]
I believe you have a wrong version of typescript codesandbox, please check https://codesandbox.io/s/festive-mestorf-2xy8q?file=/src/App.tsx

**Comment by albertms10** [comment]
I see that, as WebStorm suggested, you need `downlevelIteration` to be `true` in `tsconfig.json`. Thanks!
