### ISSUE TITLE
table多选框设置其宽度问题

### ISSUE THREAD

**Issue by reng99** [ant-design/ant-design#25803]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#API](https://ant.design/components/table-cn/#API)

### Steps to reproduce
.ant-table-row-level-0{
  .ant-table-selection-column{
    background-color: blue;
    margin: 0 !important;
      padding: 0 !important;
      width: 16px !important;
      min-width: 16px !important;
      max-width: 16px !important;
  }
}

### What is expected?
宽度变更为16px

### What is actually happening?
无变化

| Environment | Info |
|---|---|
| antd | undefined |
| React | ^16.8.6 |
| System | mac / window |
| Browser | google等 |

**Comment by afc163** [comment]
Try `rowSelection.columnWidth`.

https://ant.design/components/table-cn/#rowSelection

**Comment by reng99** [comment]
> columnWidth

It works. Thanks
