### ISSUE TITLE
Form中使用函数组件会报Function components cannot be given refs

### ISSUE THREAD

**Issue by lingjieee** [ant-design/ant-design#25802]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/lingjieee/antd-demo](https://github.com/lingjieee/antd-demo)

### Steps to reproduce
```
const Demo2 = ({value, onChange}) => {
  return(
    <input type="text" value={value} onChange={onChange}/>
  )
}
```

```
<Form.Item name="b" label="箭头函数组件">
  <Demo2/>
</Form.Item>
```

### What is expected?
正常使用

### What is actually happening?
控制台会报Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | mac os 10.15.5 |
| Browser | chrome 84 |

---
```
function Demo1({value, onChange}) {
  return(
    <input type="text" value={value} onChange={onChange}/>
  )
}
```
升级4.4.X之后出现这个问题
使用Demo1这种方式定义的函数组件可正常使用，但是使用Demo2箭头函数就会报错

**Comment by TranNgocKhoa** [comment]
AntD haven't update its dependency to fix this. So should add list line of code in package.json in dependencies field:
```
"rc-util": "^5.0.6",
```
This will tell npm use `rc-util` version 5.0.6.

**Comment by Kermit-Xuan** [comment]
`"rc-util": "^5.0.1"` is version of `package.json`

It will use the latest version when the version is `>= 5.0.1, < 6.0.0`.

**Comment by 07akioni** [comment]
> AntD haven't update its dependency to fix this. So should add list line of code in package.json in dependencies field:
> 
> ```
> "rc-util": "^5.0.6",
> ```
> 
> This will tell npm use `rc-util` version 5.0.6.

maybe you need to remove package-lock.json and then reinstall it.

**Comment by TranNgocKhoa** [comment]
> > AntD haven't update its dependency to fix this. So should add list line of code in package.json in dependencies field:
> > ```
> > "rc-util": "^5.0.6",
> > ```
> > 
> > 
> > This will tell npm use `rc-util` version 5.0.6.
> 
> maybe you need to remove package-lock.json and then reinstall it.

Thanks
