### ISSUE TITLE
Left/Right navigation was replaced by dropdown in Tabs component

### ISSUE THREAD

**Issue by rb-prashant** [ant-design/ant-design#25805]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In latest version of antd, the Left/Right navigation was replaced by dropdown in Tabs component. This could be good in functionality wise but the scroll navigation was prettier than this dropdown. It would be great if it can be reverted. 
Best.

### What does the proposed API look like?
https://ant.design/components/tabs/

**Comment by rb-prashant** [comment]
Please see below how ugly this is looking.

![image](https://user-images.githubusercontent.com/67176536/88454154-1cf7cf80-ce8b-11ea-9335-f68f5a521150.png)

Thank you

**Comment by afc163** [comment]
It won't revert, you have to stick to 4.2.x if you don't like new design of tabs.
