### ISSUE TITLE
InputNumber在移动端访问,默认拉起数字键盘

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#25813]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在IPad中访问时,希望数字输入框能默认弹出数字键盘.  

### What does the proposed API look like?

InputNumber默认实现.

**Comment by afc163** [comment]
You can try `<InputNumber type="number" />` or `<Input type="number" />`.

**Comment by l745230** [comment]
@afc163 
<InputNumber type="number" /> 可以实现,但是还是希望能默认配置.
<Input type="number" /> 配置后,PC端显示会多出一个原生的上下箭头. 移动端显示正常.  
![image](https://user-images.githubusercontent.com/15940920/88638213-c3dba600-d0ed-11ea-9287-57ea8ccc08ae.png)


还有个,input配置type="number" 只能输入数字了, 有什么方法能默认弹出数字键盘的情况下,还能切换键盘输入中文呢?

**Comment by 07akioni** [comment]
那可能需要你动态切换 type 了
