### ISSUE TITLE
Wrong API document at 'progress' component

### ISSUE THREAD

**Issue by mrtk0y** [ant-design/ant-design#25824]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/progress/#API](https://ant.design/components/progress/#API)

### Steps to reproduce
At 'success' api, it's should be
```
{ progess: number, strokeColor: string }
```
in docs is 
```
{ percent: number, strokeColor: string }
```

### What is expected?
progess in success, not percent 

### What is actually happening?
Write wrong document

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | react |
| System | All |
| Browser | All  |

**Comment by afc163** [comment]
It should be `success.percent`: https://github.com/ant-design/ant-design/pull/25356
