### ISSUE TITLE
Carousel change event when there is only one or no child & autoplay= true (子元素只有一个或者为空的时候，还是自动切换)

### ISSUE THREAD

**Issue by zhshch9527** [ant-design/ant-design#25837]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/frosty-tdd-2u31w?file=/index.js)

### Steps to reproduce
```
<Carousel
    autoplay
    beforeChange={(f, m) => console.info("before", f, m)}
    afterChange={c => console.info("after", c)}
  >
    <div>hello</div>
  </Carousel>
```
![7LQR1 YXR4ZQR1BTVJ5`A)U](https://user-images.githubusercontent.com/42881276/88530664-4a33b180-d034-11ea-966e-b20e70c7e615.png)
![IC_5DXIRIU404H%5X Q`DYC](https://user-images.githubusercontent.com/42881276/88530672-4bfd7500-d034-11ea-9f6b-9e5bca171b5a.png)

### What is expected?
When autoplay is true and there is only one or no child , don't switch automatically
当autoplay=true,并且子元素为空或者只有一个，不要自动切换

### What is actually happening?
switch automatically 

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | windows8.1 |
| Browser | 72.0.3626.119 (official version) (64-bit) |

---
Don't know if it is a bug ，If necessary, I have to set autoplay 
```
autoplay={children && children.length > 1}
```
不知道这个现象是否是一个bug

**Comment by afc163** [comment]
```
autoplay={children && children.length > 1}
```

这是正确的解决方式，我不太认为这是个 bug。
