### ISSUE TITLE
Form: Custom validator not working correctly when empty

### ISSUE THREAD

**Issue by joshua-lehmann** [ant-design/ant-design#25831]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-3zsuz?file=/index.js)

### Steps to reproduce
Working scenario:
1. Create a custom search validator for an input which only allows numbers or empty input
2. Type 1234 in the input
3. Use Backspace to delete all characters in the input
No validation error, because the numbers were valid or the input was empty

Second working scenario:
1. Create a custom search validator for an input which only allows numbers or empty input
2. Type 1abcd in the input
3. Use Backspace to delete all characters in the input
No validation error

Error scenario:
1. Create a custom search validator for an input which only allows numbers or empty input
2. Type abcd in the input
3. Use Backspace to delete all characters in the input
Validation error, however it should be valid because the input is empty and the promise should be resolved because of the  
```javascript
if (!value) {
      return Promise.resolve();
    }
```

### What is expected?
The validator should allow empty values no matter if the previous input was valid or invlid
Only the current input should matter and if that is valid the message should be valid

### What is actually happening?
The validator says it is invalid when the input is empty and the previous input was invalid, even when empty values should be valid

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | Windows 7 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
```diff
  if (!value) {
+   setSearchError('');
    return Promise.resolve();
  }
```
