### ISSUE TITLE
Divider color doesn't show when it's used in the layout footer with Row and Col.

### ISSUE THREAD

**Issue by aashayamballi** [ant-design/ant-design#25830]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-greider-kd9bq?file=/index.js)

### Steps to reproduce
* Create Row in the footer.
* Create 2 Col in the Row
  * Col with span = 1
  * Col with span = 6 and offset offset = 17
* Create a div inside Col = 6 and offset = 17
* Add the style float right to the div
* Add the vertical Divider component and give the color black
* Add few texts in between the Divider 

### What is expected?
The Divider component should be shown with the appropriate color.

### What is actually happening?
The Divider with the given color should be shown

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | Windows 10 Pro |
| Browser | Google Chrome Version 84.0.4147.89 (Official Build) (64-bit) |

**Comment by afc163** [comment]
Try `borderColor`: https://codesandbox.io/s/competent-framework-gwjly?file=/index.js

**Comment by aashayamballi** [comment]
Thank you 👍
