### ISSUE TITLE
Menu with dark theme: selected item's background should have padding around content

### ISSUE THREAD

**Issue by matulef** [ant-design/ant-design#25845]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-byjl1?file=/index.js)

### Steps to reproduce
Use `Menu` component with `theme="dark"` and select one of the menu items. 

### What is expected?
The background color of the selected navigation item should extend to the left and right of the item's content. 

Before 4.5.0:
![Screen Shot 2020-07-27 at 12 47 04 PM](https://user-images.githubusercontent.com/974305/88588143-ebf2d880-d00b-11ea-9d9a-676fd14b9901.png)

### What is actually happening?
The background color ends abruptly to the left and right of the selected item's content. 

After 4.5.0:
![Screen Shot 2020-07-27 at 12 47 23 PM](https://user-images.githubusercontent.com/974305/88588172-fb722180-d00b-11ea-914c-ae6712483ac6.png)

| Environment | Info |
|---|---|
| antd | 4.5.0 |
| React | 16.12.0 |
| System | any |
| Browser | any |

---
This is due to the following change: https://github.com/ant-design/ant-design/pull/25622

With the `light` theme, the padding is not needed, because it makes sense for the underline to end where the text ends. But with the `dark` theme, it looks very unnatural without the padding.

**Comment by hoho2017** [comment]
![image](https://user-images.githubusercontent.com/23206991/88613688-a217fa00-d0c0-11ea-9a7d-9707a104c563.png)
modify the code in red box like this will be fine

**Comment by hoho2017** [comment]
@afc163

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/88613827-e60aff00-d0c0-11ea-8d08-225cba208ed9.png)

**Comment by 07akioni** [comment]
= =，正在看

**Comment by hoho2017** [comment]
> = =，正在看

把那3行删掉就正常啦 但是我不知道哪里修改

**Comment by 07akioni** [comment]
> > = =，正在看
> 
> 把那3行删掉就正常啦 但是我不知道哪里修改

我引入新设计的时候应该没有发现这个样式的破坏

**Comment by afc163** [comment]
@xrkffgg https://github.com/ant-design/ant-design/commit/f0509f0bf96e47b31ee4616f7db5179bdc737f83
