### ISSUE TITLE
Drawer is not visible when rendered without mask

### ISSUE THREAD

**Issue by FateTestrossa** [ant-design/ant-design#25858]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2F3x.ant.design%2Fcomponents%2Fdrawer%2F](https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2F3x.ant.design%2Fcomponents%2Fdrawer%2F)

### Steps to reproduce
1.将抽屉的width设置为百分比（例如50%）  
Set the width of the drawer to a percentage (for example, 50%)  
2.将mask属性设置为false  
Set the mask property to false

### What is expected?
在没有遮罩的情况下，正常显示抽屉宽度为50%  
Without a mask, it normally shows a drawer width of 50%

### What is actually happening?
在没有遮罩的情况下，抽屉没有展示  
In the absence of a mask, the drawer is not displayed

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.9 |
| System | win10 |
| Browser | chrome 83 |

---
https://github.com/ant-design/ant-design/pull/23925  
antd 4.2.1版本已修复该问题，希望在3.x版本修复一下  
Antd 4.2.1 has fixed this issue and we hope to fix it in 3.x

**Comment by afc163** [comment]
3.x 不在维护了，请升级到 4.x。
