### ISSUE TITLE
走马灯infinite属性不设置的会导致渲染多个child的副本

### ISSUE THREAD

**Issue by EggTronic** [ant-design/ant-design#25854]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/akiran/react-slick/issues/1171](https://github.com/akiran/react-slick/issues/1171)

### Steps to reproduce
https://github.com/akiran/react-slick/issues/1171

### What is expected?
走马灯内的每个子组件应该只存在一个。

### What is actually happening?
走马灯infinite属性不设置的会导致存渲染多个child的副本

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | Win 10 |
| Browser | Chrome Latest |

**Comment by yoyo837** [comment]
当前antd使用的是fork版本 `@ant-design/react-slick`，请提供下复现。

**Comment by EggTronic** [comment]
@yoyo837 
![image](https://user-images.githubusercontent.com/22841829/88633971-17072600-d0f9-11ea-9b62-445c4dffaa09.png)

**Comment by xrkffgg** [comment]
代码设计就是这样。

**Comment by EggTronic** [comment]
这样如果子组件有数据请求的话就比较不方便，需要把请求提升出来，不然就会重复请求。

**Comment by afc163** [comment]
只能 `infinite={false}`，这种是 react-slick 的实现方式，没什么好办法。
