### ISSUE TITLE
包错误

### ISSUE THREAD

**Issue by lincolon** [ant-design/ant-design#25859]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/config-provider-cn/](https://ant.design/components/config-provider-cn/)

### Steps to reproduce
yarn add antd@4.5.0

### What is expected?
正常编译

### What is actually happening?
Failed to compile.

./node_modules/antd/es/badge/style/css.js
Module not found: Can't resolve './ribbon.css' in '/xx/node_modules/antd/es/badge/style'

| Environment | Info |
|---|---|
| antd | 4.5.0 |
| React | 16 |
| System | mac os 10.15.5 |
| Browser | chrome84 |

**Comment by yoyo837** [comment]
你的编译环境需要支持css文件处理，如使用webpack时css相关loader。

**Comment by afc163** [comment]
@07akioni https://github.com/ant-design/ant-design/blob/f498ae034412a7bd69c37e6d937e891f8763e0c4/components/badge/style/index.tsx#L2 ribbon 要在 index.less 里引用。
