### ISSUE TITLE
请问如何实现清除表头选中filters和sorter？

### ISSUE THREAD

**Issue by tulies** [ant-design/ant-design#25868]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
重置表格查询的时候，希望能够把在表头上选择的过滤条件和排序一起重置成默认状态。请问下有没有什么api可以调用呢。

### What does the proposed API look like?
重置表格查询的时候，希望能够把在表头上选择的过滤条件和排序一起重置成默认状态。

**Comment by tulies** [comment]
知道了。。。

**Comment by tulies** [comment]
i know

**Comment by gengxuelei** [comment]
How to solve, encountered the same problem...

**Comment by Edw1nkql** [comment]
how to solve, thanks
