### ISSUE TITLE
Menu inline模式下 同时收起多个SubMenu时有明显卡顿

### ISSUE THREAD

**Issue by lihqi** [ant-design/ant-design#25867]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-poitras-85qc0?file=/MyMenu.js)

### Steps to reproduce
点击全部收起

### What is expected?
~~希望能传入一个属性控制Motion的motionLeaveImmediately属性~~
在一些情况下展开/收起全部功能是合理的，可否提供一种方式控制动画是否执行，或者像[material-ui](https://material-ui.com/zh/api/collapse/#collapse-api)的timeout，控制动画的执行时间

### What is actually happening?
有明显卡顿

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome |

**Comment by 07akioni** [comment]
说实话我建议你用 Tree，这么做有点刁难浏览器了hhh。

**Comment by lihqi** [comment]
> 说实话我建议你用 Tree，这么做有点刁难浏览器了hhh。Tree 对搜索的体验也更好，这么多数据

- 在产品中的场景Menu更好

- demo中数据并不算多，不到100个SubMenu，用户的数据可能更多

**Comment by 07akioni** [comment]
> > 说实话我建议你用 Tree，这么做有点刁难浏览器了hhh。Tree 对搜索的体验也更好，这么多数据
> 
> * 在产品中的场景Menu更好
> * demo中数据并不算多，不到100个SubMenu，用户的数据可能更多

感觉其他组件没有暴露类似的功能，我不是很确定这个是否会被加上去。

如果你们的产品未来确保不会开发一个选中某一项的功能，那 Menu 凑活用一下应该也是可以的。

**Comment by afc163** [comment]
需要解决性能问题，看上去 https://github.com/ant-design/ant-design/issues/24975 没有解决这里的问题。@Kermit-Xuan

**Comment by Kermit-Xuan** [comment]
这是受控模式，优化都是基于非受控模式的。

**Comment by Kermit-Xuan** [comment]
晚上我看看怎么优化一下

**Comment by Kermit-Xuan** [comment]
我看了看，这种其实不是数据多渲染的性能问题，是菜单多了后，同时收起或展开的时候动画同时执行导致的卡顿

我想你要的其实就是能够控制菜单收起或展开时的动画的属性，这个属性其实是有的， `motion` 传入 `{ motionLeaveImmediately: true }`

现在你试试这个:

https://codesandbox.io/s/frosty-grass-5vjkd?file=/Sider.js

**Comment by lihqi** [comment]
> 我看了看，这种其实不是数据多渲染的性能问题，是菜单多了后，同时收起或展开的时候动画同时执行导致的卡顿
> 
> @lihqi 我想你要的其实就是能够控制菜单收起或展开时的动画的属性，这个属性其实是有的， `motion` 传入 `{ motionLeaveImmediately: true }`
> 
> 现在你试试这个:
> 
> https://codesandbox.io/s/frosty-grass-5vjkd?file=/Sider.js

原来是这么用的！感谢！

**Comment by asmallbottle** [comment]
> 我看了看，这种其实不是数据多渲染的性能问题，是菜单多了后，同时收起或展开的时候动画同时执行导致的卡顿
> 
> @lihqi 我想你要的其实就是能够控制菜单收起或展开时的动画的属性，这个属性其实是有的， `motion` 传入 `{ motionLeaveImmediately: true }`
> 
> 现在你试试这个:
> 
> https://codesandbox.io/s/frosty-grass-5vjkd?file=/Sider.js

你好，是我用的antd版本太低么？没找到这个属性？
![image](https://user-images.githubusercontent.com/39576794/105951307-cb830400-60aa-11eb-9945-b2493a6e98f2.png)

**Comment by kerm1it** [comment]
https://github.com/react-component/menu/blob/master/src/Menu.tsx#L49
