### ISSUE TITLE
Menu的字菜单a-menu-item 能否横向排列 个数可定义

### ISSUE THREAD

**Issue by huoshidehua** [ant-design/ant-design#25877]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
有时候子菜单很多再加上分组，整个菜单就变的很长

### What does the proposed API look like?
加一个 horizontal | vertical 属性，加一个 col 表示横向情况下需要几列 类似如下效果
![Image](https://raw.githubusercontent.com/huoshidehua/docfile/master/%E6%A8%AA%E5%90%91%E8%8F%9C%E5%8D%95.jpg)

**Comment by Veynee** [comment]
Like Dropdown

**Comment by huoshidehua** [comment]
> Like Dropdown

そうです

**Comment by afc163** [comment]
Not in our plan.
