### ISSUE TITLE
Carousel走马灯样式问题-轮播项比内容区高度多出两个像素

### ISSUE THREAD

**Issue by xietongjian** [ant-design/ant-design#25878]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/carousel-cn/#header](https://ant.design/components/carousel-cn/#header)

### Steps to reproduce
Carousel走马灯样式问题-内容区与轮播项高度不一样
![antdesign-bug](https://user-images.githubusercontent.com/16096832/88758701-a2d18e80-d19b-11ea-8d00-7d9e13fc4fad.jpg)

### What is expected?
Carousel走马灯-内容区与轮播项高度一样

### What is actually happening?
样式问题-内容区与轮播项高度不一样

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.8.6 |
| System | win10 |
| Browser | 谷歌-版本 84.0.4147.89（正式版本） （64 位） |

**Comment by afc163** [comment]
多了 2px，具体有什么影响么？

**Comment by xietongjian** [comment]
> 多了 2px，具体有什么影响么？

只是一点点样式问题，设计师要求比较高。

**Comment by afc163** [comment]
截图看看，antd 官网貌似看不出来问题。

**Comment by xietongjian** [comment]
> 截图看看，antd 官网貌似看不出来问题。

![image](https://user-images.githubusercontent.com/16096832/88765870-c3a0e080-d1a9-11ea-9a4c-88a59b161961.png)
只是页面背景色与内容区背景色不一样的情况才会出现明显的问题。
```javascript
:global {
    .ant-carousel .slick-slide {
      >div{
        >div{
          // 默认是inline-block，我强行改成block就没事了。
          // display:block!important;
          display:block!important;
        }
      }
}
```

**Comment by afc163** [comment]
能给我个 codesandbox 重现么？我在官网调了背景色也没看出来。

<img width="655" alt="image" src="https://user-images.githubusercontent.com/507615/88768192-4d05e200-d1ad-11ea-8220-d5377ef7134d.png">

**Comment by xietongjian** [comment]
看下这个，我把index.css里面的默认样式删除掉了。难道是这个原因导致的？
https://codesandbox.io/s/intelligent-leftpad-38zls?file=/index.css

**Comment by afc163** [comment]
很奇怪的问题，找到两个解决方式：

1. https://codesandbox.io/s/frosty-cookies-fn1ly?file=/index.css
2. https://codesandbox.io/s/cool-grothendieck-o57pg?file=/index.css

**Comment by afc163** [comment]
准备用第二种方式修复，侵入性小一点。

**Comment by xietongjian** [comment]
> 准备用第二种方式修复，侵入性小一点。

好的，希望越做越好，精益求精。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/25886/files#diff-618993db86dbd3c36a31c6225bcd36c3R51

**Comment by 07akioni** [comment]
这个不是 vertical-align 的问题吗？
```
.slick-slide > div > div  {
  vertical-align: bottom;
}
```
https://codesandbox.io/s/dawn-field-z630y?file=/index.css

**Comment by afc163** [comment]
看上去是的，可以再来个 PR。
