### ISSUE TITLE
http://library.ant.design/ can't open, please repair it! thanks

### ISSUE THREAD

**Issue by ieoo** [ant-design/ant-design#25875]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://library.ant.design/](http://library.ant.design/)

### Steps to reproduce
open the url

### What is expected?
do

### What is actually happening?
do

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | windows 10 |
| Browser | chrome |

**Comment by xrkffgg** [comment]
@ieoo You should open issue in https://github.com/ant-design/antd-library
