### ISSUE TITLE
Error when dragging slider on the last drawerChild in mobile screen - DrawerChild._this.removeMoveHandler

### ISSUE THREAD

**Issue by paulussimanjuntak** [ant-design/ant-design#25870]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-pine-js7yd)

### Steps to reproduce
- open reproduction link, open link in new tab.
- inspect the browser and choose a mobile device.
- reload the page.
- open the first drawer, open the childDrawer.
- Drag the slider.

### What is expected?
There are no errors when dragging the slider on childDrawer

### What is actually happening?
When on the mobile screen size and dragging the slider in childDrawer the error "Cannot read property 'x' of undefined, DrawerChild._this.removeMoveHandler" appears. This error will only appear when on the mobile screen size and only in the childDrawer or in the last Multi-level drawer.
*dragging only

| Environment | Info |
|---|---|
| antd | 2.3.2 |
| React | 16.13.1 |
| System | Mac |
| Browser | Chrome |

**Comment by Jeff909Dev** [comment]
I have the same problem by dragging the slider in mobile screen size 
<img width="749" alt="Captura de pantalla 2020-08-23 a las 22 48 17" src="https://user-images.githubusercontent.com/57524818/90988415-dd5bfa80-e592-11ea-972a-ff2ec7071599.png">
give the following error:
<img width="933" alt="Captura de pantalla 2020-08-23 a las 22 50 02" src="https://user-images.githubusercontent.com/57524818/90988431-ffee1380-e592-11ea-8d38-c546c0b29070.png">

**Comment by Dateezeon** [comment]
Was there a resolution to this issue?  I am getting an error here as well but a different one.
![Screenshot 2020-10-14 164705](https://user-images.githubusercontent.com/28759980/96048949-f4092a00-0e3c-11eb-961d-3f6b073c1c5c.png)

**Comment by paulussimanjuntak** [comment]
Hi @Dateezeon the issue is not resolved yet

**Comment by SolidZORO** [comment]
+1，`"antd": "^4.15.1"`

**Comment by arifszn** [comment]
Confirming on 4.15.0. Only happens in mobile screen,

![image](https://user-images.githubusercontent.com/45073703/115182436-c5298480-a0fb-11eb-8acc-93dc20a736ca.png)

**Comment by mortenmo** [comment]
same problem. only when using Chrome on responsive/mobile view. Drag and drop doesn't work in the view while in that view, but works fine when I turn off the "device toolbar" in the Chrome inspector:

react-dom.development.js:6202 Unable to preventDefault inside passive event listener invocation.
preventDefault @ react-dom.development.js:6202
DrawerChild._this.removeMoveHandler @ DrawerChild.js:57
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:646
dispatchUserBlockingUpdate @ react-dom.development.js:5894

**Comment by mortenmo** [comment]
Workaround: The code in question is only triggered when mask={true} which is default. A workaround to get rid of the error is to turn the mask off for mobile devices.

The issue is in rc-drawer on a touchMove event which is why it is only triggered on mobile (or in mobile/device mode on Chrome when you turn that on). If not touch or if mask is off, this code is not triggered.

**Comment by afc163** [comment]
Fixed in react-component/drawer#153
