### ISSUE TITLE
Tree 树形控件Demo中“ 自定义展开/折叠图标”，对于控制台的警告很不友好？

### ISSUE THREAD

**Issue by dajun1230** [ant-design/ant-design#25876]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/tree/demo/switcher-icon.md](https://github.com/ant-design/ant-design/blob/master/components/tree/demo/switcher-icon.md)

### Steps to reproduce
直接将“自定义展开/折叠图标”中的代码放到新搭建的一个React项目中，就会在控制台报错，虽然不影响使用，但是很奇怪。（警告如下：index.js:1 Warning: `children` of Tree is deprecated. Please use `treeData` instead.）对于antd 4.x版本来说，既然都已经弃用了children，那为什么TreeNode就很不友好的支持呢。一直提示红色警告。

### What is expected?
还是能够支持TreeNode，但是不要出现红色警告。（因为用户难免会有自定义树形结构每一行显示的内容。）

### What is actually happening?
支持TreeNode的同时，还不会出现红色警告

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | react 16.13.1 |
| System | Mac |
| Browser | 谷歌 最新版本 |

**Comment by 07akioni** [comment]
还能用是为了保持兼容性，用 titleRender 可以解决自定义的问题。

deprecated 的不建议使用，有可能下个大版本就见不到了。

换成 treeData 内部代码处理起来会简单，性能也会更好。

**Comment by dajun1230** [comment]
好的。谢谢，我尝试一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "07akioni"<notifications@github.com&gt;; 
发送时间: 2020年7月29日(星期三) 晚上9:47
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "杨朝军"<1123395547@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] Tree 树形控件Demo中“ 自定义展开/折叠图标”，对于控制台的警告很不友好？ (#25876)





 
还能用是为了保持兼容性，用 titleRender 可以解决自定义的问题。
 
deprecated 的不建议使用，有可能下个大版本就见不到了。
 
换成 treeData 内部代码处理起来会简单，性能也会更好。

**Comment by alinaleidada** [comment]
但是对于某些节点是自定义功能的，比如某一类可以点击，某一类需要禁用，用titleRender 会造成多次渲染，并且点击需要自定义的节点会 警告 “没有唯一值”
