### ISSUE TITLE
时间选择器和日期选择器导出的范围选择器命名一样

### ISSUE THREAD

**Issue by 134355** [ant-design/ant-design#25885]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
const { RangePicker } = DatePicker;
const { RangePicker } = TimePicker;
我需要同时使用这两选择器
const { RangePicker } = DatePicker;
const { RangePicker：RangeTimePicker } = TimePicker;
这样使用<RangeTimePicker
		style={{ width: '100%' }}
              format="HH:mm"
              placeholder={['开始时间', '结束时间']}
            />,没法通过编译

### What does the proposed API look like?
进行改进，或者有其他方式代替

**Comment by XiaoJiuDYS** [comment]
是不是冒号 用了中文输入法，没复现出来(https://codesandbox.io/s/broken-smoke-8yh4f)
```tsx
const { RangePicker：RangeTimePicker } = TimePicker;
```
