### ISSUE TITLE
date-fns generator get error

### ISSUE THREAD

**Issue by TianyiLi** [ant-design/ant-design#25881]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-biwo2?file=/index.js)

### Steps to reproduce
use date-fns generator

### What is expected?
should not get error

### What is actually happening?
get date-fns error

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.12.0 |
| System | Ubuntu 20.04 |
| Browser | Chrome |

---
The generator did not format string correctly

date-fns format spec is different from momentjs .

**Comment by fireairforce** [comment]
我看一下~

**Comment by StefanoMagrassi** [comment]
@fireairforce it seems there are two issues with [unsupported unicode tokens](https://date-fns.org/v2.15.0/docs/Unicode-Tokens):
1. in [`DatePanel/DateHeader.tsx`](https://github.com/react-component/picker/blob/master/src/panels/DatePanel/DateHeader.tsx#L60) the `format` function is called with a fixed `locale.yearFormat` which does not comply the `date-fns` spec (e.g. [`en_US`](https://github.com/react-component/picker/blob/master/src/locale/en_US.ts#L18))
2. in [`DatePanel/DateBody`](https://github.com/react-component/picker/blob/master/src/panels/DatePanel/DateBody.tsx#L89) the `format` function is called with a fixed `'YYYY-MM-DD'` which does not comply the `date-fns` spec

**Comment by fireairforce** [comment]
@StefanoMagrassi You can also submit a pull request to fix it~👍

**Comment by TianyiLi** [comment]
This is what I did in my project now.

```ts
import datefnsGenerateConfig from 'rc-picker/lib/generate/dateFns';
import generatePicker from 'antd/lib/date-picker/generatePicker';
import 'antd/es/date-picker/style/index';

function localParse(format: string) {
  return format
    .replace(/Y/g, 'y')
    .replace(/D/g, 'd')
    .replace(/gggg/, 'yyyy')
    .replace(/g/g, 'G')
    .replace(/([Ww])o/g, 'wo');
}
export const Picker = generatePicker<Date>({
  ...datefnsGenerateConfig,
  locale: {
    ...datefnsGenerateConfig.locale,
    format: (locale, date, format) => {
      return datefnsGenerateConfig.locale.format(locale, date, localParse(format));
    },
    parse: (locale, text, formats) => {
      formats = formats.map(localParse);
      return datefnsGenerateConfig.locale.parse(locale, text, formats);
    },
  },
});

```
