### ISSUE TITLE
dropdown 原版本 4.4.2 升级至4.5.1 报错 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sherryhhx** [ant-design/ant-design#25884]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)

### Steps to reproduce
dropdown 原版本 4.4.2 升级至4.5.1 报错 Maximum call stack size exceeded

### What is expected?
不报错

### What is actually happening?
报错 白屏

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.9 |
| System | mac |
| Browser | chrome 81.0.4044.138 |

**Comment by feibi** [comment]
+1

**Comment by timelessover** [comment]
+1

**Comment by mntnv** [comment]
+1

**Comment by nickzheng1994** [comment]
+1

**Comment by netfoxor** [comment]
+1

**Comment by hanlike** [comment]
+1

**Comment by mbektior** [comment]
+1

**Comment by netfoxor** [comment]
再重新安装下依赖（注意不要锁版本）解决了，我的猜测是ant design依赖的某个版本出了bug，已经修复了。

**Comment by qixm-burnish** [comment]
我的项目使用4.4.x重新安装依赖时，select的远程搜索同样存在这个问题，浏览器提示信息为：
```
Uncaught RangeError: Maximum call stack size exceeded
    at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:187)
```
删除node_module和lock文件，重新安装4.5.1才解决

**Comment by xrkffgg** [comment]
dependencies 有更新，更新版本，必删 lock ，重新安装

**Comment by xrkffgg** [comment]
You should remove `yarn.lock` or `pack-lock.json` and node_modules, next install again.

**Comment by yyd91521** [comment]
dropdown 原版本 4.3.4 升级至4.5.1
也是报错 Maximum call stack size exceeded  at Object.mergedMotion.<computed> [as onEnterStart] (Popup.js:190) 
 The above error occurred in the <CSSMotion> component: in CSSMotion (created by ForwardRef)
删除 pack-lock.json && node_modules  依然不行


React | 16.13.1
System | windows10
Browser | 83.0.4103.106

**Comment by 07akioni** [comment]
`git clean -fdx` 然后重新 `npm install` 试试？还是不行的话可以传一个复现的 repo

**Comment by shaozujie** [comment]
+1

**Comment by anastasia-adv** [comment]
+1
