### ISSUE TITLE
Tree option "autoExpandParent" is not working

### ISSUE THREAD

**Issue by cnLGMing** [ant-design/ant-design#25887]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/cnLGMing/pen/WNrBVww](https://codepen.io/cnLGMing/pen/WNrBVww)

### Steps to reproduce
Not applicable [defaultExpandedKeys] parameter, use [autoExpandParent]

### What is expected?
I think the effect is like this.

![expect](http://imge.19930827.xyz/ant-design-tree.png)

### What is actually happening?
but now

![now](http://imge.19930827.xyz/ant-design-tree-now.png)

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.12.0 |
| System | macOS 10.15.6 |
| Browser | Edge 83.0.478.56 |

**Comment by 07akioni** [comment]
说实话我也没高明白这个是干啥的= =

https://github.com/react-component/tree/blob/039fa5f4e87dc0be4e0d70ad3603e3a83249e540/tests/Tree.spec.js#L123

**Comment by zombieJ** [comment]
`autoExpandParent` is used for recursive expanded when some child node is expanded. So when you do not provide `defaultExpandedKeys` or `expandedKeys`. There are nothing to recursive expand.

**Comment by skczjun** [comment]
这个属性完全没用。只要你设置了expandedKeys就会自动展开所有父级节点，即使你把autoExpandParent给设为false

**Comment by JackLiR8** [comment]
Use `defaultExpandAll ` to expand all node!
