### ISSUE TITLE
如何优雅的重写 ant-design 组件的样式

### ISSUE THREAD

**Issue by chenbin92** [ant-design/ant-design#2588]
### 本地环境

- antd 版本: 1.7.0

### 遇到的问题

最近使用 antd 在写一个系统，但是整个系统的设计配色与 antd 的色调是完全不同的，官方提供的 [可配置的颜色](https://github.com/ant-design/ant-design/issues/193)太少， 该如何优雅的去重写 antd 组件的样式？

<img src="http://7xr387.com1.z0.glb.clouddn.com/calendar.png" width="200px" /> <img src="http://7xr387.com1.z0.glb.clouddn.com/select.png" width="200px" />
 
---

### 目前解决方法

在 `components/` 下新建一个文件夹 `Style/`，所有需要重写样式的组件按照 `${componentname}Overwrite.scss` 命名

```
src/
  |-components/
  |    |- DatePickerOverwrite.scss
  |    |- InputOverwrite.scss
  |    |- SelectOverwrite.scss
  |    |- etc...
```

##### 方式一：

如需要引用 `DatePicker` 组件，在相应的文件引入  `DatePicker`  的同时引用一份 `DatePickerOverwrite.scss`

```
// in homepage.js
import { DatePicker } from 'antd';
import './components/Style/DatePickerOverwrite.scss';
```

* 优点：可以配置 `"plugins": [["antd", { style: "css" }]]` 按需加载
* 缺点：需要在使用 `DatePicker` 的文件引用，如果有多个文件引用，需要引用多次
 
--- 

##### 方式二：

直接在项目的入口文件引入 

```
// in app.js
import  'antd/dist/antd.css'  // 一次引用所有的 antd style
import './components/DatePickerOverwrite.scss'; 
```

```
// in homepage.js
import { DatePicker } from 'antd';
```

* 优点 ：只需在入口文件引用一次，作为全局样式
* 缺点：不能按需加载 `antd.css`

@afc163  以上是在实际项目开发中遇到的疑点，请问有没有什么好的建议，还是我的姿势压根不对 ？

**Comment by dyf2015** [comment]
less不是更容易？

发自我的 iPhone

在 2016年8月2日，20:19，chenbin <notifications@github.com<mailto:notifications@github.com>> 写道：

本地环境

  *   antd 版本: 1.7.0

遇到的问题？

最近使用 antd 在写一个系统，但是整个系统的设计配色与 antd 的色调是完全不同的，官方提供的 可配置的颜色<https://github.com/ant-design/ant-design/issues/193>太少， 该如何优雅的去重写 antd 组件的样式？

[https://camo.githubusercontent.com/b999ffa6156c007a692a7d68681f08632d533efd/687474703a2f2f3778723338372e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f63616c656e6461722e706e67]<https://camo.githubusercontent.com/b999ffa6156c007a692a7d68681f08632d533efd/687474703a2f2f3778723338372e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f63616c656e6461722e706e67> [https://camo.githubusercontent.com/12d5f3d54cf81b61cc21bd427154b91e94265bbb/687474703a2f2f3778723338372e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f73656c6563742e706e67] <https://camo.githubusercontent.com/12d5f3d54cf81b61cc21bd427154b91e94265bbb/687474703a2f2f3778723338372e636f6d312e7a302e676c622e636c6f7564646e2e636f6d2f73656c6563742e706e67>

________________________________
目前解决方法

在 components/ 下新建一个文件夹 Style/，所有需要重写样式的组件按照 ${componentname}Overwrite.scss 命名

src/
  |-components/
  |    |- DatePickerOverwrite.scss
  |    |- InputOverwrite.scss
  |    |- SelectOverwrite.scss
  |    |- etc...


分别对应以下两种引用方式：
方式一：

如需要引用 DatePicker 组件，在相应的文件引入 DatePicker 的同时引用一份 DatePickerOverwrite.scss

// in homepage.js
import { DatePicker } from 'antd';
import './components/Style/DatePickerOverwrite.scss';


  *   优点：可以配置 "plugins": [["antd", { style: "css" }]] 按需加载
  *   缺点：需要在使用 DatePicker 的文件引用，如果有多个文件引用，需要引用多次

________________________________
方式二：

直接在项目的入口文件引入

// in app.js
import  'antd/dist/antd.css'  // 一次引用所有的 antd style
import './components/DatePickerOverwrite.scss';


// in homepage.js
import { DatePicker } from 'antd';


  *   优点 ：只需在入口文件引用一次，作为全局样式
  *   缺点：不能按需加载 antd.css

@afc163<https://github.com/afc163> 以上是在实际项目开发中遇到的疑点，请问有没有什么好的建议, 还是我的姿势压根不对 ？

―

**Comment by afc163** [comment]
一般来说 `***Overwrite.scss` 的文件大小不会很大。你可以：

```jsx
// in homepage.js
import { DatePicker } from 'antd';
```

```jsx
// in app.js
import './overwrite.scss';  // 一次引用所有的 overwrite style
```

**Comment by afc163** [comment]
另外，我们的变量覆盖的确实不是很全，也欢迎给我们提 PR。

**Comment by chenbin92** [comment]
@afc163 感谢！

**Comment by henryzp** [comment]
@afc163 

```
// in homepage.js
import { DatePicker } from 'antd';
// in app.js
import './overwrite.scss';  // 一次引用所有的 overwrite style
```

这种方式有问题吧？

因为上面的会生成

```
:root .xxx {}
```

而下面，如果写成：

```
.xxx {}
```

这样显然覆盖不了啊？

**Comment by xiaojingzhao** [comment]
并没有效果啊，over write的css一直被ant的覆盖

**Comment by henryzp** [comment]
@xiaojingzhao ，我新开了一个项目，也一直被ant的覆盖，活见鬼了。。

**Comment by henryzp** [comment]
@afc163 ，有一种情况是组件异步加载的时候，是覆盖不了的，比如：

```
const NotFound = (location, cb) => {
	require.ensure([], require => {
		cb(null, require('XXX').default)
	},'notfound')
}

 <Route path="*" getComponent={NotFound} />
```

Route中如果是component，即可以覆盖antd的，getComponent则不行，需要写!important才可以

**Comment by OuFeng** [comment]
antd与Styled-Components配合使用

1:安装Styled-Components
```javascript
    npm install --save-dev styled-components
```

2:引入并使用
```javascript
    import styled from 'styled-components';
    //面包屑控件
    import { Breadcrumb } from 'antd';

    const BreadcrumbStyled = styled(Breadcrumb)`
        font-size: 1.5em;
        text-align: center;
        color: palevioletred;
    `;

    ReactDOM.render(
        <Breadcrumb>
            <Breadcrumb.Item>首页</Breadcrumb.Item>
            <Breadcrumb.Item href="">应用中心</Breadcrumb.Item>
            <Breadcrumb.Item href="">应用列表</Breadcrumb.Item>
            <Breadcrumb.Item>某应用</Breadcrumb.Item>
        </Breadcrumb>
    , mountNode);
```

**Comment by TreeVie** [comment]
@OuFeng 这样写感觉跟直接在写style复杂度是一样的啊

**Comment by linonetwo** [comment]
@TreeVie 这样写可以在组件上 f12 直接跳转到样式，因为样式被存在一个变量里了，就能用跳转到定义功能了。方便维护。

**Comment by muzi131313** [comment]
https://pro.ant.design/docs/style-cn

**Comment by muzi131313** [comment]
https://pro.ant.design/docs/style-cn
![image](https://user-images.githubusercontent.com/2398149/90329205-25987d00-dfd5-11ea-93d6-b94726964a61.png)
