### ISSUE TITLE
Modal.confirm. using Form's Instance to validate Fields and not get Fields' values

### ISSUE THREAD

**Issue by ngd-b** [ant-design/ant-design#25882]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/questionmodal-of-form-qhtj1?file=/index.js)

### Steps to reproduce
1. 点击按钮 Button。
2. 弹出层，直接点击确定会进行表单校验，有提示校验信息。
3. 按照规则填写内容后提交，`form.validateFields().then(valus=>{})` , 

### What is expected?
点击“提交”按钮后，表单校验后在`then`方法返回表单的值。`resolve()`后关闭弹出层

### What is actually happening?
`then`方法没有执行，获取不到校验后的`values`。提交按钮一直处于加载状态

| Environment | Info |
|---|---|
| antd | 4.1.1 |
| React | 16.13.1 |
| System | window 10 |
| Browser | google chrom 83 |

---
我本地使用的antd版本是4.1.1  。 示例中使用了最新版本4.5.1 也有这个问题

**Comment by afc163** [comment]
用 useModal：https://ant.design/components/modal-cn/#components-modal-demo-hooks

直接用 Modal.xxx 拿不到 Context。

**Comment by ngd-b** [comment]
不是Modal传递context的问题。

```js
onOk:()=>{
    return new Promise((resolve,reject)=>{
        // 调用getFieldsValue 可以获取到值
        console.log(formPreset.getFieldsValue());
       // 通过触发form表单校验调用then方法取值，then 方法未执行
       // 如果触发校验，未通过，会执行catch
        formPreset.validateFields()
            .then(values=>{
                console.log(values);
                resolve();
            }).catch(err=>{
                reject(err);
            });
    });
}
```

我也按照useModal的方式测试了一下。还是一样的问题

**Comment by afc163** [comment]
你试试 `<Modal />`，Modal.xxx 尽量不要承载重交互。

**Comment by ngd-b** [comment]
问题还存在，`form.validateFields()` then方法未调用。

地址：https://codesandbox.io/s/questionmodal-of-form-qhtj1?file=/index.js

**Comment by ngd-b** [comment]
找到问题了，是自定义规则校验的问题，没有默认`resolve()`

```js
{
    validator(ruel, value) {
    return new Promise((resolve, reject) => {
        try {
        if (!value.match(/^[2-9]|1[0-2]$/)) {
            reject("请输入2-12之间的数字!");
        }
        // 其他未校验情况，直接resolve，我以为 除了reject() 其他情况默认执行
        resolve();
        } catch (e) {
           reject("请输入2-12之间的数字!");
        }
    });
    }
}
```
