### ISSUE TITLE
Showing a Tooltip conditionally, on Text component, when the content has ellipsis is not possible

### ISSUE THREAD

**Issue by AlberErre** [ant-design/ant-design#25891]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-82wuw?file=/index.js)

### Steps to reproduce
Try to assign a Tooltip to a Text only when ellipsis is applied and shown.

Therefore:
If the ellipsis dinamically appears -> Tooltip should be shown.
If the ellipsis doesn't appear -> Tooltip should be hidden.

### What is expected?
Tooltip is shown only when ellipsis appears.

A similar issue was found with the Paragraph component (https://github.com/ant-design/ant-design/issues/23188), an `onEllipsis` event was added by the Antd team.

### What is actually happening?
Tooltip is always shown.

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.3 (64Bits) |
| Browser | Chrome 80.0.3987.163 (64 bits) |

---
A similar issue was found with the Paragraph component (https://github.com/ant-design/ant-design/issues/23188), an `onEllipsis` event was added by the Antd team.

**Comment by Overcase** [comment]
我来认领这个功能把

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/28821
