### ISSUE TITLE
Let select support editable mode?

### ISSUE THREAD

**Issue by kaysonwu** [ant-design/ant-design#25896]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前 `Select` 不支持 可编辑的组合框，一个可编辑的组合框具有以下形态：

- 下拉按钮选择
- 直接自己输入内容

QQ 登录框中的 QQ 号输入框 就是一个可编辑的组合框。

### What does the proposed API look like?
```
<Combobox editable />
// or
<Select editable />
```

**Comment by afc163** [comment]
https://ant.design/components/auto-complete-cn/

**Comment by kaysonwu** [comment]
@afc163 自动完成不适用， 输入的时候会打开 下拉选项。这不像 可编辑的组合框。 我需要的是仅下拉的时候才出现下拉选项。 你可以看看 QQ 登录框的 QQ 号码输入框，输入的时候不会一直展示下拉选项。 这里的意思应该是，下拉选项作为备选，优先输入。 如果再加个 `prefix` 前缀图标更好了

**Comment by 07akioni** [comment]
> 输入的时候会打开 下拉选项。这不像 可编辑的组合框。 我需要的是仅下拉的时候才出现下拉选项。 你可以看看 QQ 登录框的 QQ 号码输入框，输入的时候不会一直展示下拉选项。 这里的意思应该是，下拉选项作为备选，优先输入。 如果再加个 `prefix` 前缀图标更好了

通过现有功能组合应该是能做到的，自定义 input + auto-complete

**Comment by kaysonwu** [comment]
是可以，变相向实现。

**Comment by kaysonwu** [comment]
出了个 Demo [https://codesandbox.io/s/qqlogin-wf4v9?file=/index.js](https://codesandbox.io/s/qqlogin-wf4v9?file=/index.js) 但不是最优的方式
