### ISSUE TITLE
DatePicker day of the week not working in Antd v4

### ISSUE THREAD

**Issue by roelvdboom** [ant-design/ant-design#25893]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/moment-day-of-week-not-working-inu1u?file=/index.js)

### Steps to reproduce
- Import moment
- Change locale to `nl`
- Use the DatePicker component

### What is expected?
First day of the week should start with monday in DatePicker component

### What is actually happening?
First day of the week is still sunday.

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.3.1 |
| System | Ubuntu 20.04 |
| Browser | Chrome: 83.0.4103.61 |

---
First day of the week on monday did work in version: 3.26.18
https://codesandbox.io/s/moment-day-of-week-working-l0zb0?file=/index.js

**Comment by 07akioni** [comment]
Would you like to send a PR to fix it?

**Comment by zombieJ** [comment]
antd v4 DatePicker locale no longer affect by global setting. It always follow the component locale: https://codesandbox.io/s/moment-day-of-week-not-working-j96p9?file=/index.js

Doc should update about moment part.
