### ISSUE TITLE
List.Item hoverable

### ISSUE THREAD

**Issue by goodoldneon** [ant-design/ant-design#25899]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Give clear visual feedback that a `List.Item` is clickable.

### What does the proposed API look like?
Same as the `Card` component's `hoverable` property.

**Comment by xrkffgg** [comment]
I think you can define it this way directly in your project

```css
.ant-list-item:hover {
    xxx
}
```

**Comment by zombieJ** [comment]
You can follow @xrkffgg to customize hover style currently. And let me sync with designer. thx

**Comment by goodoldneon** [comment]
Thank you @xrkffgg and @zombieJ for the fast feedback! I can get this functionality with CSS now, but I really like the `hoverable` prop on the `Card` component!

**Comment by zombieJ** [comment]
@goodoldneon , you can try https://procomponents.ant.design/list/table  first since before this.

**Comment by afc163** [comment]
https://procomponents.ant.design/components/list
