### ISSUE TITLE
Unfocus the input element

### ISSUE THREAD

**Issue by modimansi** [ant-design/ant-design#25897]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/interesting-chaum-lmvp9)

### Steps to reproduce
src folder contains demo-component which as 2 InputNumber elements. While changing value of 2nd element, 1st one gets in to focus

### What is expected?
InputNumber which is user interacting with should stay in focus

### What is actually happening?
The focus get shifted to the first InputNumber element when you change value of other InputNumber elements

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.13.1 |
| System | 1803 |
| Browser | 84.0.4147.105 |

---
I had so many elements in the code, which led to scrolling of page. So when I change value of lower elements, focus gets shifted to first element

**Comment by afc163** [comment]
```diff
-                     <label className="children">{props.children}</label><br/>
+                    <div className="children">{props.children}</div><br/>
```

https://codesandbox.io/s/clever-wing-bkmlg?file=/src/page-content/component.js

**Comment by modimansi** [comment]
thank you @afc163
