### ISSUE TITLE
组件源码编写

### ISSUE THREAD

**Issue by baijunpeng666** [ant-design/ant-design#25894]
请教一个问题，为什么不在组件tsx文件里面直接import引入这个组件的样式呢，而是在编译的时候把他们结合到一块？为什么要这么处理呢？

**Comment by yoyo837** [comment]
因为antd无法也不应该从源码角度控制你的打包和编译环境及其方式，css整合到一起是方便整体引入就像传统的`<style />`那样。

**Comment by 07akioni** [comment]
打包流程包的太深了，按照现有的打包方式写在里面会出问题，你自己写进去打包看看产物就知道了
