### ISSUE TITLE
Modal styles are broken when using `Modal.useModal` hook

### ISSUE THREAD

**Issue by Gautierrr** [ant-design/ant-design#25895]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-leaf-oste4)

### Steps to reproduce
Use `modal` provided by `Modal.useModal` hook without `rootPrefixCls` and `prefixCls` set.

```js
export default function App() {
  const [modal, contextHolder] = Modal.useModal();

  return (
    <div>
      {contextHolder}
      <Button
        onClick={() =>
          modal.confirm({
            title: "Are you sure?"
          })
        }
      >
        Open broken modal
      </Button>
    </div>
  );
}
```

### What is expected?
Default Ant styles are not supposed to be broken 😄

### What is actually happening?
Default Ant styles are not applied on the modal (and the modal buttons).

| Environment | Info |
|---|---|
| antd | 4.5.0 |
| React | 16.12.0 |
| System | MacOS v10.15.5 |
| Browser | Chrome v84.0.4147.89 |

---
Seems to be related to this PR: https://github.com/ant-design/ant-design/pull/25613
If `rootPrefixCls` and `prefixCls` are not set, modal class names look like this: `undefined-confirm-body-wrapper` on the DOM node.
As a workaround, we can set `rootPrefixCls` to `ant` and `prefixCls` to `ant-modal`.

**Comment by lukasluecke** [comment]
Also happens on the component docs page at https://ant.design/components/modal/ 🙈

Thanks for the workaround 🙂 TypeScript complains about setting `rootPrefixCls` this way, but it's the only thing that works - tried it with `Modal.config()` as well, but didn't seem to have any effect.

**Comment by zombieJ** [comment]
ref https://github.com/ant-design/ant-design/commit/f7ed77b52f7a66ded9905f1646e578ff2170712b

**Comment by zqjimlove** [comment]
> ref #25603

`Modal.config` can't fix this issue.

``` javascript
(getGlobalModal() || Modal).confirm({
    ...messageObj,
    onOk: () => fn(...args),
    prefixCls: 'ant-modal'
  });
```
and then `prefixCls` just work for modal, the buttons still missing the prefixCls, like:

![image](https://user-images.githubusercontent.com/3240259/89599066-0725d980-d891-11ea-9eae-d238826b0371.png)

**Comment by 07akioni** [comment]
> > ref #25603
> 
> `Modal.config` can't fix this issue.
> 
> ```js
> (getGlobalModal() || Modal).confirm({
>     ...messageObj,
>     onOk: () => fn(...args),
>     prefixCls: 'ant-modal'
>   });
> ```
> 
> and then `prefixCls` just work for modal, the buttons still missing the prefixCls, like:
> 
> ![image](https://user-images.githubusercontent.com/3240259/89599066-0725d980-d891-11ea-9eae-d238826b0371.png)

for temporal fix you still need to set `rootPrefixCls`.

the problem will be solved in next patch version.
