### ISSUE TITLE
Wrong table behaviour when it's width change with scroll y active 

### ISSUE THREAD

**Issue by SrAnthony** [ant-design/ant-design#25898]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-osi5i?file=/index.js)

### Steps to reproduce
In the example, click on "Increase width". The table will move to the right.
Click on "Scroll is enabled" and then again on "Increase width". The table will not move to the right.

### What is expected?
When the scroll y is enable and the table should resize, not move.

### What is actually happening?
The table is moving.

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | latest |
| System | MacOS |
| Browser | Chrome |

**Comment by SrAnthony** [comment]
If you open the inspector, find the `<table style="table-layout: fixed;">` and toggle off and on the width attribute inside `.ant-table table`, the table will fix.

![Screen Shot 2020-07-29 at 14 10 35](https://user-images.githubusercontent.com/14919996/88831413-b124a800-d1a5-11ea-8153-c25daefcef79.png)

**Comment by zombieJ** [comment]
flex layout should config content width to force calculate if you need make rest part auto width:
https://codesandbox.io/s/antd-reproduction-template-5dd9o
