### ISSUE TITLE
请问资源下载中的Axure部件库有更新计划吗？

### ISSUE THREAD

**Issue by iandukov** [ant-design/ant-design#2590]
如题

**Comment by benjycui** [comment]
最近更新过了。

**Comment by benjycui** [comment]
以后设计资源更新后，设计方面需要知会下码农，这样可以把设计资源更新同步到 Change log 中，同时也需要更新 http://ant.design/docs/resource/download 页面时的版本号。

@ant-design/ant-design-team

**Comment by iandukov** [comment]
Axure Components v1.3
Axure Box v1.3

已经有更高的版本了吗？
