### ISSUE TITLE
Button组件无法使用e.target.dataset

### ISSUE THREAD

**Issue by Mango525** [ant-design/ant-design#25904]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-7su26?file=/index.js)

### Steps to reproduce
重现链接中的代码， Button组件使用dataset属性，希望点击按钮在控制台打印出字符串test，但是在新版本的antd中打印为undefined，4.2.2版本同样的代码，控制台打印出test：
```jsx
import React from "react";
import ReactDOM from "react-dom";
import { Button, version } from "antd";
import "antd/dist/antd.css";
import "./index.css";

ReactDOM.render(
  <div className="App">
    <h1>antd version: {version}</h1>
    <Button
      onClick={e => {
        console.log(e.target.dataset.test);
      }}
      data-test="test"
      type="primary"
      style={{ marginLeft: 8 }}
    >
      Primary Button
    </Button>
  </div>,
  document.getElementById("root")
);
```

### What is expected?
Button组件可以获取传入的dataset属性值

### What is actually happening?
Button组件可以传入的dataset属性值打印出来为undefined

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.13.1 |
| System | mac os 10.15.4  |
| Browser | Microsoft Edge  83.0.478.61 |

---
4.2.2版本antd同样的代码可以打印出dataset的值

**Comment by 07akioni** [comment]
https://codesandbox.io/s/antd-reproduction-template-9wrz3?file=/index.js
use `e.currentTarget`.
