### ISSUE TITLE
InputNuber添加前缀后缀

### ISSUE THREAD

**Issue by guangming21** [ant-design/ant-design#25901]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
经常使用InputNumber场景下，需要带上单位

### What does the proposed API look like?
<InputNumber  addonAfter="单位" />

**Comment by afc163** [comment]
Duplicate of #14284

**Comment by guangming21** [comment]
我就服了，你的解决方法都不是大家想要的，好好做一个功能不行吗，InputNumber也是封装Input，为什么要逃避这个问题呢，很难吗？

You can try <Input type="number" prefix="$" /> instead of InputNumber.
你自己试一试这个，数字输入根本控不住，min={1}， 输入-1也可以

**Comment by guangming21** [comment]
大家都在提这个问题，就是一个小小的不方便，解决一下很费事吗

**Comment by 07akioni** [comment]
https://codesandbox.io/s/objective-stallman-ny6tb

**Comment by Scxw010516** [comment]
2024年了，还是没有suffix

**Comment by afc163** [comment]
suffix 会和 handlers 互相遮盖，不知道怎么处理。

**Comment by Scxw010516** [comment]
> suffix 会和 handlers 互相遮盖，不知道怎么处理。

可不可以给增减按钮和suffix增加优先级呢，比如controls=true的时候，suffix属性无效之类的。在我的开发过程中，很少用到增减按钮，但是suffix真的非常需要

**Comment by Scxw010516** [comment]
> > suffix 会和 handlers 互相遮盖，不知道怎么处理。
> 
> 可不可以给增减按钮和suffix增加优先级呢，比如controls=true的时候，suffix属性无效之类的。在我的开发过程中，很少用到增减按钮，但是suffix真的非常需要

虽然这样不太优雅

**Comment by afc163** [comment]
> 比如controls=true的时候，suffix属性无效之类的

这个会被当做 bug 的。

**Comment by afc163** [comment]
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
