### ISSUE TITLE
The `.anticon` style of `vertical-align` is `baseline`

### ISSUE THREAD

**Issue by WebSkiller** [ant-design/ant-design#25900]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
The `.anticon` style of `vertical-align` is `baseline`, i can see the button icon and the button font are not justified

### What does the proposed API look like?
Button icon and button font are proposed to be justified.

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/88873583-8bec7400-d24f-11ea-94a8-ad13f512ce0c.png)

As you can see the `vertical-align` is not `baseline` but `-.125em`.
