### ISSUE TITLE
走马灯内存泄漏

### ISSUE THREAD

**Issue by Xavier0818** [ant-design/ant-design#25905]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ec3b0?file=/index.js)

### Steps to reproduce
处理后的分页数据进行轮播，出现内存泄漏，在ant的modules包中react-slick版本为0.26.3

### What is expected?
内存正常

### What is actually happening?
内存增涨

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | react |
| System | win 10 |
| Browser | edge 84.0.522.44 |

**Comment by afc163** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/15062
