### ISSUE TITLE
NODE_ENV=production 编译后 Form.create 大量报错

### ISSUE THREAD

**Issue by yxqme** [ant-design/ant-design#2591]
版本：1.6.5  1.7.0
NODE_ENV=development 正常
NODE_ENV=production 报错

场景: 使用了 Form.create(options) onFieldsChange 和 mapPropsToFields

报错信息
> Uncaught TypeError: Cannot read property 'onChange' of undefined

定位到此
```js
if (fieldMeta[action]) {
   fieldMeta[action].apply(fieldMeta, args);
 }
```

> Uncaught TypeError: Cannot read property 'validate' of undefined

定位到
```js
var validate = fieldMeta.validate;
```

**Comment by codering** [comment]
@yxqme  https://github.com/ant-design/ant-design/issues/2463

**Comment by benjycui** [comment]
文档里面的 PR 已经合并，试下最新版的 React 怎样？

**Comment by yxqme** [comment]
@codering 🙏  确实如此 我关了

**Comment by codering** [comment]
@yxqme @benjycui  我刚测试了最新的15.3版本，没有这个问题。
http://codepen.io/coderingz/pen/AXQRkp
![image](https://cloud.githubusercontent.com/assets/2271825/17351454/3d5170ae-5961-11e6-9993-b8978b32010c.png)
