### ISSUE TITLE
InputNumber loses focus when onChange is called

### ISSUE THREAD

**Issue by eakl** [ant-design/ant-design#25919]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-bell-s6q0z?file=/index.js)

### Steps to reproduce
Focus on any row of Column 2 (<InputNumber />) with onChange prop, type a 2-digit number (e.g. '23') on it and then lose focus after the 1st digit (e.g. after '2')

### What is expected?
That the InputNumber don't lose focus after the 1st digit is entered (e.g. after '2'). Allowing for multi-digit input (e.g. '2345')

### What is actually happening?
After the 1st digit is entered, InputNumber loses focus

| Environment | Info |
|---|---|
| antd | 4.4.3 |
| React | 16.12.0 |
| System | MacOS High Sierra 10.13.6 |
| Browser | Chrome 83.0.4103.97 |

**Comment by eakl** [comment]
I have debugged my code and the issue is triggered at line 127 of my CodeSandbox when `setData([...newData])` is called. I still don't understand why as the code looks correct though.

**Comment by eakl** [comment]
Up on this issue.

**Comment by eakl** [comment]
Another source of the issue might come from the **InputNode** component on `L. 77-87`

To reproduce the issue:
1. `L. 103`: Replace Input**Node** by Input**Number**
2. `L. 127` : comment out **setData()**

It looks like the onChange props is not passed properly.

**Comment by vsosinga** [comment]
Moving your `InputNode` declaration ouside of the `EditableCell` component fixes this

**Comment by mileshobby** [comment]
Hello, I am having this issue as well. I cannot remove my InputNode from Editable Cell because my onChange is dynamic based on values passed to the cell

**Comment by vsosinga** [comment]
@mileshobby can you share a code example? Is the function itself dynamic or the parameters?

**Comment by StefanoSega** [comment]
same issue

**Comment by stcalica** [comment]
same issue as well. 
Lose focus everytime onChange is called.

**Comment by vsosinga** [comment]
@StefanoSega @stcalica have you tried the solution in my comment? Can you share a code example?

**Comment by stcalica** [comment]
@vsosinga  it's just a simple component, the updateComponent is a redux action. your solution with the InputNode and everything seems a bit wild to me as I'm just trying to use InputNumber on it's own and onChange doesn't seem to allow me to type past the first digit. 

If anything is the issue is me trying to use styling on the InputNumber. 

  ```
const Numeric = styled(InputNumber)`
  <color css styles> 
`;




cons ScoreComponent = ({
    label,
    weight,
    updateComponent,
   }) => {

  const editScore = e => {
    updateComponent({ weight: e });
  };
  .
 .
 .
 return(
   <Numeric defaultValue={weight} onChange={editRiskScore} />
 )

```

**Comment by vsosinga** [comment]
@stcalica the original problem is using an `InputNumber` in an `EditableCell`, so that's what my solution is for.
Since you're not using an `EditableCell` the problem is somewhere else. Can you try to recreate your case in a CodeSandbox?

**Comment by afc163** [comment]
Check https://codesandbox.io/s/gifted-mayer-3j4vs?file=/index.js
