### ISSUE TITLE
table文档与源代码不符合

### ISSUE THREAD

**Issue by AlexXiaoLiu** [ant-design/ant-design#25912]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#API](https://ant.design/components/table-cn/#API)

### Steps to reproduce
源代码里面interfect.d.ts中的TableRowSelection的fixed是boolean并非是文档中的boolean | string

### What is expected?
改成为boolean | string 能让我最后一列能够固定

### What is actually happening?
现在我不能完成最后一列的固定

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | win10 |
| Browser | Google Chrome 84 |

---
325警告

**Comment by afc163** [comment]
<img width="1026" alt="image" src="https://user-images.githubusercontent.com/507615/88891662-21026380-d276-11ea-90f2-2cfd38991f9c.png">

文档中是 boolean。

**Comment by AlexXiaoLiu** [comment]
> <img alt="图片" width="1026" src="https://user-images.githubusercontent.com/507615/88891662-21026380-d276-11ea-90f2-2cfd38991f9c.png">
> 
> 文档中是boolean。

如果像文档中columns固定列用fixed:'right'编译会出现报错。提示fixed为boolean  fixed:'right' as any才能够解决问题
