### ISSUE TITLE
Antd 4 的版本中表格当中使用onCell即设置单列样式中对于whitSpace不支持

### ISSUE THREAD

**Issue by dajun1230** [ant-design/ant-design#25915]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/table](https://github.com/ant-design/ant-design/blob/master/components/table)

### Steps to reproduce
columns = [
     { title: '描述', dataIndex: 'desc',key:"desc",
      onCell: () => {
        return {
          style: {
            maxWidth: 150,
            overflow: 'hidden',
            whiteSpace: 'nowrap',
            textOverflow:'ellipsis',
            cursor:'pointer'
          }
        }
      },
      render: (text) => <Tooltip placement="topLeft" title={text}>{text}</Tooltip>
    },       
]。
antd 3的版本对于设置whiteSpace： ‘no-warp'是支持的，但是4的版本中使用就不行，出现不兼容问题（The types of 'onCell(...).style.whiteSpace' are incompatible between these types.）

### What is expected?
期望是能够支持使用whiteSpace: 'nowrap',

### What is actually happening?
出现了不兼容，同时报错。（The types of 'onCell(...).style.whiteSpace' are incompatible between these types.
          Type 'string' is not assignable to type '"pre" | "nowrap" | "-moz-initial" | "inherit" | "initial" | "revert" | "unset" | "-moz-pre-wrap" | "break-spaces" | "normal" | "pre-line" | "pre-wrap" | undefined'.） 部分报错。

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | react 16.13.1 |
| System | Mac |
| Browser | 谷歌 最新版本 |

**Comment by dajun1230** [comment]
你看一下，大概就是这样子的，只是项目中用了ts。https://codesandbox.io/s/antd-reproduction-template-nmi4i?file=/index.js



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ant Design GitHub Bot"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 下午5:59
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "杨朝军"<1123395547@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] Antd 4 的版本中表格当中使用onCell即设置单列样式中对于whitSpace不支持 (#25915)





 
Hello @dajun1230. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
你好 @dajun1230, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by dajun1230** [comment]
我贴一下代码，害怕上面那个链接你看不到。import React from "react";
import ReactDOM from "react-dom";
import { Button, DatePicker, version, Tooltip, Table } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const tableData = [
  {
    id: 123,
    name: "js",
    describe:
      "JavaScript 是一种非常松散的面向对象语言，也是 Web 开发中极受欢迎的一门语言。JavaScript，尽 管它的语法和编程风格与 Java 都很相似，但它却不是 Java 的“轻量级”版本，甚至与 Java 没有任何关 系。JavaScript 是一种全新的动态语言，它植根于全球数亿网民都在使用的 Web 浏览器之中，致力于增 强网站和 Web 应用程序的交互性。",
    time: "2020-07-30"
  }
];
const columns = [
  {
    title: "课程名称",
    dataIndex: "name",
    key: "name"
  },
  {
    title: "课程描述",
    dataIndex: "describe",
    key: "describe",
    align: "center", // 用的是ts  这里就是用的是align: ‘center' as 'center'
    onCell: () =&gt; {
      return {
        style: {
          maxWidth: 50,
          overflow: "hidden",
          whiteSpace: "nowarp",
          textOverflow: "ellipsis",
          cursor: "pointer"
        }
      };
    },

    render: text =&gt; (
      <Tooltip placement="topLeft" title={text}&gt;
        {text}
      </Tooltip&gt;
    )
  },
  {
    title: "课程时间",
    dataIndex: "time",
    key: "time"
  }
];

ReactDOM.render(
  <div className="App"&gt;
    <h1&gt;antd version: {version}</h1&gt;
    <DatePicker /&gt;
    <Button type="primary" style={{ marginLeft: 8 }}&gt;
      Primary Button
    </Button&gt;
    <Table
      style={{ width: "100%" }}
      dataSource={tableData}
      columns={columns}
      rowKey={row =&gt; row.id}
    /&gt;
  </div&gt;,
  document.getElementById("root")
);





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月30日(星期四) 下午5:59
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"杨朝军"<1123395547@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] Antd 4 的版本中表格当中使用onCell即设置单列样式中对于whitSpace不支持 (#25915)





 
Hello @dajun1230. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
你好 @dajun1230, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by afc163** [comment]
codesandbox 有 TS 的脚手架，建议做一个重现出来。

**Comment by dajun1230** [comment]
zh：专门搭建了一个demo来复现这个问题，codesandbox不好用，用不习惯，可能是没有用熟导致的吧。复现地址：（https://github.com/dajun1230/antd-demo-ts）。（注意：只要取消App.tsx文件中的第21行代码，就会报错。）en:&nbsp;A demo has been specially built to reproduce this problem. Codes and box are not easy to use, and they are not used to it. It may be caused by not using it well. Duplicate address:（ https://github.com/dajun1230/antd-demo-ts ）。 (Note: just cancel App.tsx The 21st line in the file will report an error.)


那就麻烦你看一下这个问题了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "偏右"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 晚上8:58
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "杨朝军"<1123395547@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] Antd 4 的版本中表格当中使用onCell即设置单列样式中对于whitSpace不支持 (#25915)





 
你这个看不到错误，codesandbox 有 TS 的脚手架，建议做一个重现出来。

**Comment by dajun1230** [comment]
如果没有时间的话，上个问题可以不看，因为暂时可以用ellipsis来代替，虽然我不知道是哪里的兼容问题导致的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "偏右"<notifications@github.com&gt;; 
发送时间: 2020年7月30日(星期四) 晚上8:58
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "杨朝军"<1123395547@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] Antd 4 的版本中表格当中使用onCell即设置单列样式中对于whitSpace不支持 (#25915)





 
你这个看不到错误，codesandbox 有 TS 的脚手架，建议做一个重现出来。

**Comment by afc163** [comment]
```
const a = {
  whiteSpace: 'nowrap',
  maxWidth: 100,
  textOverflow: 'ellipsis',
  cursor: 'pointer',
};

const b: React.HTMLAttributes<HTMLElement> = {
  style: {},
};

b.style!.whiteSpace = a.whiteSpace;
b.style!.maxWidth = a.maxWidth;
b.style!.cursor = a.cursor;
b.style!.textOverflow = a.textOverflow;
```

<img width="565" alt="image" src="https://user-images.githubusercontent.com/507615/89003850-6c2e7c00-d333-11ea-83c9-25ef4308402a.png">

<img width="858" alt="image" src="https://user-images.githubusercontent.com/507615/89003856-705a9980-d333-11ea-90ac-e392544658bc.png">

`whiteSpace` 在 TypeScript 定义中不接收 string，只接受字面量枚举，而例子中其他属性都支持 string。

有两种解决方案你可以试试：

```diff
    onCell: () => {
      return {
        style: {
          maxWidth: 300,
          overflow: 'hidden',
          whiteSpace: 'nowrap', // 只要一取消注视就会报错。
          textOverflow:'ellipsis',
          cursor:'pointer'
-       }
+       } as React.CSSProperties,
      }
    },
```

```diff
    onCell: () => {
      return {
        style: {
          maxWidth: 300,
          overflow: 'hidden',
          whiteSpace: 'nowrap' as 'nowrap',
          textOverflow:'ellipsis',
          cursor:'pointer'
        }
      }
    },
```

**Comment by dajun1230** [comment]
好的，麻烦了。（备注一下总体感觉：去提了两个问题，都很热心的回答了，及时有效，谢谢你们）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "偏右"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 中午1:43
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "杨朝军"<1123395547@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] Antd 4 的版本中表格当中使用onCell即设置单列样式中对于whitSpace不支持 (#25915)





 const a = {   whiteSpace: 'nowrap',   maxWidth: 100,   textOverflow: 'ellipsis',   cursor: 'pointer', }; const b: React.HTMLAttributes<HTMLElement&gt; = {   style: {}, }; b.style!.whiteSpace = a.whiteSpace; b.style!.maxWidth = a.maxWidth; b.style!.cursor = a.cursor; b.style!.textOverflow = a.textOverflow;  

 

 
whiteSpace 在 TypeScript 定义中不接收 string，只接受字面量枚举，而例子中其他属性都支持 string。
 
有两种解决方案你可以试试：
     onCell: () =&gt; {       return {         style: {           maxWidth: 300,           overflow: 'hidden',           whiteSpace: 'nowrap', // 只要一取消注视就会报错。           textOverflow:'ellipsis',           cursor:'pointer' -       } +       } as React.CSSProperties,       }     },
     onCell: () =&gt; {       return {         style: {           maxWidth: 300,           overflow: 'hidden',           whiteSpace: 'nowrap' as 'nowrap',           textOverflow:'ellipsis',           cursor:'pointer'         }       }     },

**Comment by dajun1230** [comment]
我都试过了，这两种方式都不得行。没事，我也不研究了，用ellipsis暂时能达到我要的效果。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "偏右"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 中午1:43
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "杨朝军"<1123395547@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] Antd 4 的版本中表格当中使用onCell即设置单列样式中对于whitSpace不支持 (#25915)





 const a = {   whiteSpace: 'nowrap',   maxWidth: 100,   textOverflow: 'ellipsis',   cursor: 'pointer', }; const b: React.HTMLAttributes<HTMLElement&gt; = {   style: {}, }; b.style!.whiteSpace = a.whiteSpace; b.style!.maxWidth = a.maxWidth; b.style!.cursor = a.cursor; b.style!.textOverflow = a.textOverflow;  

 

 
whiteSpace 在 TypeScript 定义中不接收 string，只接受字面量枚举，而例子中其他属性都支持 string。
 
有两种解决方案你可以试试：
     onCell: () =&gt; {       return {         style: {           maxWidth: 300,           overflow: 'hidden',           whiteSpace: 'nowrap', // 只要一取消注视就会报错。           textOverflow:'ellipsis',           cursor:'pointer' -       } +       } as React.CSSProperties,       }     },
     onCell: () =&gt; {       return {         style: {           maxWidth: 300,           overflow: 'hidden',           whiteSpace: 'nowrap' as 'nowrap',           textOverflow:'ellipsis',           cursor:'pointer'         }       }     },

**Comment by afc163** [comment]
@dajun1230 你可以本地试试，我测试是好的：https://github.com/dajun1230/antd-demo-ts/pull/3

**Comment by dajun1230** [comment]
你好，我想借这个问题请教一下其他的问题，不知道方便不？&nbsp;

1. 现在antd 4.x中使用了craco.config.js，这个文件是不是与config-overrides.js只能存在一个，并且前者的优先级更高？
2. 在config-overrides.js中还可以配置从中引入全局的less变量，以及用@符号代表'src'作为根目录，还有配置px转rem的插件也是可以的，但是现在craco.config.js文件中，完全不知道怎么配置这三个插件，请问你知道吗？ （或者你可以提交一下文档，我去看，去尝试都行）我去github.com上面找了craco-less插件，上面也没有提到关于这三个的配置，如果你知道，可以告诉我怎么配置吗？（谢谢大佬）（备注使用carco.config.js就安装了craco-less）
