### ISSUE TITLE
Slider tooltip visible abnormal

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#25910]
![2020-07-30 14 30 07](https://user-images.githubusercontent.com/29775873/88888773-843dc700-d271-11ea-81e9-5352c2181fca.gif)

---
- 当我缓慢移动一个把手经过另一个把手时，会激活这个把手的 tooltip ，让它一直显示。
> When I slowly move one handle past another, it will activate the tooltip of this handle and keep it displayed.

**Comment by xrkffgg** [comment]
应该是 重构 hooks引起的， https://github.com/ant-design/ant-design/pull/23699
之前版本的 都 OK

**Comment by xrkffgg** [comment]
😂😂 看着都没问题，但确实有影响

**Comment by hoho2017** [comment]
> 😂😂 看着都没问题，但确实有影响

这是一个bug

**Comment by hoho2017** [comment]
> 😂😂 看着都没问题，但确实有影响

第一个栗子也有这问题鸭

**Comment by xrkffgg** [comment]
横竖都有问题

**Comment by hoho2017** [comment]
> 横竖都有问题

感觉像onMouseLeave失效了😂😂

**Comment by lihqi** [comment]
试试
  const toggleTooltipVisible = (index: number, visible: boolean) => {
    setVisibles(prev => {
      return { ...prev, [index]: visible }
    });
  };
