### ISSUE TITLE
在form表单中，Cascader选择后，始用getValueFromEvent获取选择项的对象字段放入form中，但无法回显

### ISSUE THREAD

**Issue by 23cicada** [ant-design/ant-design#25924]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-pascal-7mhe3?file=/index.js)

### Steps to reproduce
始用getValueFromEvent获取对象后放入form，但无法在Cascader中回显

### What is expected?
正常显示

### What is actually happening?
无法显示，因为form表达储存的值为对象，Cascader只能接收数字或字符串类型的数组

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | react |
| System | win10 |
| Browser | chrome |

**Comment by 07akioni** [comment]
https://codesandbox.io/s/hardcore-tharp-snrzo?file=/index.js

use first argument.

**Comment by 23cicada** [comment]
我期望的是获取选中项的对象，并不是直接拿值

**Comment by 23cicada** [comment]
默认就是取第一个参数，getValueFromEvent={v => v} 这样写又有什么意义呢？

**Comment by Kermit-Xuan** [comment]
`value` 肯定只能接受指定的格式, 你的这种需求，需要自己在提交后拿 `value` 去 options 里面自己查找。
