### ISSUE TITLE
I can't correct render @ant-design/icons

### ISSUE THREAD

**Issue by KInGATiLLa** [ant-design/ant-design#25934]
Specs: 
- Win 10 64bit
- Node 12.18.2
- React 16.13.1
- Antd 4.5.1

I think, I imported @ant-design/icons library correctly according to the documentation. And when i write <ImportedIcon /> this, it shows me this errors. I tried many times.

![Capture1](https://user-images.githubusercontent.com/17881842/89011865-bd466c00-d343-11ea-8ed6-1443c442446a.PNG)
![Capture2](https://user-images.githubusercontent.com/17881842/89011876-c20b2000-d343-11ea-91e9-d562cb735fd8.PNG)
![Capture3](https://user-images.githubusercontent.com/17881842/89012288-891f7b00-d344-11ea-9df2-91618fef3ae1.PNG)

**Comment by xrkffgg** [comment]
Check name  https://ant.design/components/icon/
