### ISSUE TITLE
在form表单中，Cascader选择后，使用getValueFromEvent获取选择项的对象字段放入form中，但无法回显

### ISSUE THREAD

**Issue by 23cicada** [ant-design/ant-design#25935]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-shape-zbk64?file=/index.js)

### Steps to reproduce
使用getValueFromEvent获取对象后放入form，但无法在Cascader中回显

### What is expected?
正常显示

### What is actually happening?
无法显示，因为form表达储存的值为对象，Cascader只能接收数字或字符串类型的数组

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | react |
| System | win10 |
| Browser | chrome |

---
我这是第二次提这个问题了，如果单纯把getValueFromEvent={v => v} 改成这样是多此一举的

**Comment by afc163** [comment]
目前不支持这种功能：https://github.com/ant-design/ant-design/issues/24040#issuecomment-626590546

建议到 onFinish 里面去二次处理：https://codesandbox.io/s/frosty-waterfall-54z1p?file=/index.js ，或者封装一个能接收 options 的 NewCascader 组件。
