### ISSUE TITLE
树选择控件搜索怎么是根据value搜索，而不是根据label搜索

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2593]
#### 你做了什么？
在选择框中输入“节点一”

#### 你期待的结果是：
可以搜索到“节点一”

#### 实际上的结果：
搜索到的是no found，只有搜索“0-0”才有结果

**Comment by aw6658913** [comment]
补充下在线演示地址[http://ant.design/components/tree-select](url) 多选案例

**Comment by aw6658913** [comment]
补充下在线演示地址：http://ant.design/components/tree-select  （多选案例）

**Comment by warmhug** [comment]
为什么默认是根据value搜索？因为 value 只能是字符串，但 label 可以是任意 react node 节点、无法确定搜索什么。

你想根据 label 搜索，设置 treeNodeFilterProp="label"
