### ISSUE TITLE
Form.Item hasFeedback should allow for 'error' value (only show on error)

### ISSUE THREAD

**Issue by fgblomqvist** [ant-design/ant-design#25946]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, using hasFeedback leads to having a ton of extra icons in a form, even if the values are correct. When an Input is incorrect, it is helpful and pretty to show the red icon as extra visual aid that the input is incorrect. However, I think in some/most situations, it is unnecessary to show the green checkmark once the value becomes correct. Not showing any icon at all at that point is fine and less cluttered in my opinion.

It is currently not possible to get this functionality in an easy/clean manner. You would have to duplicate the form error state yourself (e.g. store the error state for all fields in a state variable on every form change and then use that variable to decide whether to show feedback).

### What does the proposed API look like?
Allow `hasFeedback` to accept `true | false | 'error'`, where true/false is the same as before, and 'error' is to only show feedback when there's an error.

**Comment by afc163** [comment]
You can try this as workaround: https://codesandbox.io/s/blue-cherry-2se5f?file=/index.js

**Comment by fgblomqvist** [comment]
Yes that's pretty much the workaround I described. Quite cumbersome if you have 10+ fields.
