### ISSUE TITLE
antd表格写了expandedRowKeys点击加号就无法展开？

### ISSUE THREAD

**Issue by xidianhgh** [ant-design/ant-design#25944]
< a-table   ref = "TableInfo"
               : columns = " columns "
               : dataSource = " dataSource "
               : pagination = " pagination "
               : loading = " loading "
               : scroll = " {  x:   900  } "
               @ change = " handleTableChange "
                defaultExpandedRowKeys  = {[ 1 ]}
               : expandedRowKeys = " expandedRowKeys "
                >
网上很多网友反映这个问题

**Comment by 07akioni** [comment]
区分一下受控模式和非受控模式
