### ISSUE TITLE
Form input 使用了getFieldProps后输入文字变的很慢是为什么

### ISSUE THREAD

**Issue by Yhaojing** [ant-design/ant-design#2595]
#### 本地环境

- antd 版本:1.6.3
- 操作系统及其版本：ios
- 浏览器及其版本:chrome

#### 你做了什么？
	Form input 使用了getFieldProps后输入变得卡顿，很慢

**Comment by benjycui** [comment]
应该是因为你的表单太复杂了，拆开成几个小表单吧。 See: https://github.com/ant-design/ant-design/issues/1972
