### ISSUE TITLE
Tree组件，第一层子节点之间缺少连接线

### ISSUE THREAD

**Issue by tulies** [ant-design/ant-design#25950]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tree组件，第一层子节点之间缺少连接线。

### What does the proposed API look like?
Tree组件，第一层子节点之间是否也应该加上连接线啊。

![image](https://user-images.githubusercontent.com/8286897/89104399-c6226500-d44b-11ea-890a-54fb0c3219da.png)

**Comment by afc163** [comment]
应该是要的，来个 PR 如何？

**Comment by tulies** [comment]
> 应该是要的，来个 PR 如何？

😂  有空我看看源码。。。

**Comment by Er1cKwok** [comment]
pr还没合吗？

**Comment by tulies** [comment]
> pr还没合吗？
没有，一直出差没时间看。我用了showLine和showIcon，同时使用时候，叶子节点和非叶子混在一层的时候，连接线实在是不好看，而且无法去掉默认的icon。  也没办法设置展开和收起的图标不一致。最终我选择了不用连接线，直接用DirectoryTree了。
![image](https://user-images.githubusercontent.com/8286897/90338202-71214a00-e01a-11ea-81b1-3e39034d04f6.png)

最主要是无法去掉默认的文件icon，混在一层的问题，应该需要代码设置文件夹节店排在上面就可以了。

**Comment by tulies** [comment]
> pr还没合吗？

没有，一直出差没时间看。我用了showLine和showIcon，同时使用时候，叶子节点和非叶子混在一层的时候，连接线实在是不好看，而且无法去掉默认的icon。 也没办法设置展开和收起的图标不一致。最终我选择了不用连接线，直接用DirectoryTree了。
![image](https://user-images.githubusercontent.com/8286897/90338380-d590d900-e01b-11ea-86f3-40366929abd4.png)


最主要是无法去掉默认的文件icon，混在一层的问题，应该需要代码设置文件夹节店排在上面就可以了。

**Comment by tulies** [comment]
看到大哥们已经修复了连接线
