### ISSUE TITLE
select选择框，combobox模式下，labelInValue这个属性无效

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2596]
antd版本1.6.4  
我想得到value对象，但是现在只能拿到key

**Comment by RaoHai** [comment]
代码贴一下。。

至少在我这个示例里，这么用是有效的。

http://codepen.io/RaoHai/pen/RRYBvP?editors=001

**Comment by wuhaih** [comment]
handleChange(value) {
    //判断是否显示下拉列表,由于select组件，combox模式下，labelInValue属性不生效，故增加分支
    //value 是object 对象，对应的key value 值是一样的
        this.setState({
           value:value.key,
           text:value
        })
    }
  },

  render() {
    let {  value, ...others} = this.props;
    const options = this.state.data.map((d, idx) => {
      return <Option key={String(idx)} value={String(d.value)}>{d.text}</Option>
    }); 
   return (
      <Select {...others}
         key={others.Zoomkey}
         combobox
         onChange={this.handleChange.bind(this)}
         filterOption={false}
         value={this.state.text}
         defaultActiveFirstOption={false}
         labelInValue >
        {/*{ options }*/}
        <Option value="jack">jack-杰克</Option>
        <Option value="lucy">lucy-露西</Option>
        <Option value="tom1">汤姆1</Option>
        <Option value="tom2">汤姆2</Option>
      </Select>
    );

**Comment by RaoHai** [comment]
用一下 codepen 吧……

**Comment by wuhaih** [comment]
不好意思，我简单描述下吧，就是你拿的那个value object对象
value = Object {key: "lucy", label: "lucy"}  key label值变成一样的啦，而其实我的label是有中文名字的
value = Object {key: "lucy", label: "lucy-露西"}

**Comment by RaoHai** [comment]
好吧。明白了。

 设置一下 `<Select optionLabelProp=“children”>` 就可以取到了。

**Comment by wuhaih** [comment]
感谢，解决啦
