### ISSUE TITLE
npm run pub 过程 lint 和 jest 报错但没有退出

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#25965]
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/507615/89126763-e40acb00-d51a-11ea-823f-e4c035b74c1a.png">

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/507615/89126777-00a70300-d51b-11ea-99fa-4ccb81b9a07a.png">

最后发布成功了，实际上应该直接 exit 的。

**Comment by 07akioni** [comment]
这个有点神奇
