### ISSUE TITLE
InputNumber readOnly 交互

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#25974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rm1q3?file=/index.js)

### 交互点
1. 右侧是否需要显示操作栏？
2. 鼠标悬浮操作栏显示禁用样式，但是点击有阴影交互，移动有尺寸交互。

### Version
4.5.2

**Comment by xrkffgg** [comment]
禁用的 InputNumber 不显示右侧操作栏

**Comment by zombieJ** [comment]
看起来 readOnly 也是没有必要显示这个按钮的
