### ISSUE TITLE
Drawer 中使用 Modal.method 导致 overflow 的样式问题

### ISSUE THREAD

**Issue by lhzbxx** [ant-design/ant-design#25972]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-b9282)

### Steps to reproduce
打开 Drawer，然后点击 Drawer 中的按钮触发 Modal.confirm，再点击 Modal 中的确认按钮。

### What is expected?
Drawer 和 Modal 都关闭。且页面滚动正常。

### What is actually happening?
Drawer 和 Modal 都关闭。但页面无法滚动。发现 body 中多了 overflow-y: hidden 的样式。

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | Mac OS X 10_15_16 |
| Browser | Chrome/84.0.4147.105 |

**Comment by afc163** [comment]
你给的例子实测貌似是正常的。

**Comment by lhzbxx** [comment]
> 你给的例子实测貌似是正常的。

![image](https://user-images.githubusercontent.com/3831948/89157858-c469b600-d59f-11ea-930a-197806ba1f79.png)

您看一下截图，因为 body 中增加了 scroll-y: hidden 的样式，导致整个页面无法滚动了。
可能是我复现步骤没说清楚？一定要通过 Modal.confirm() 手动关闭 Drawer（也不要再次打开 Drawer）这时候应该就能复现了。

**Comment by afc163** [comment]
设置 Mac 系统滚动条为下图时重现成功了。

<img width="331" alt="image" src="https://user-images.githubusercontent.com/507615/89161193-dc900400-d5a4-11ea-83dd-cd12878c7314.png">

**Comment by lhzbxx** [comment]
Any update?

**Comment by shaodahong** [comment]
不知道操作的对不对，但是没复线 @lhzbxx 

![Kapture 2020-08-10 at 22 55 37](https://user-images.githubusercontent.com/14831261/89796787-a500f900-db5c-11ea-8640-4ef70c67a4df.gif)

**Comment by lhzbxx** [comment]
> 不知道操作的对不对，但是没复现 @lhzbxx
> 
> ![Kapture 2020-08-10 at 22 55 37](https://user-images.githubusercontent.com/14831261/89796787-a500f900-db5c-11ea-8640-4ef70c67a4df.gif)

你把显示滚动条设置为默认的「根据鼠标或触控板自动显示」，然后再按相同的步骤，结果会发现页面内部无法滚动，因为 body 多了 overflow-y: hidden; 的 style。

**Comment by shaodahong** [comment]
![image](https://user-images.githubusercontent.com/14831261/89848724-6fd6c400-dbb9-11ea-896c-83ed19a31577.png)

和这个没关系

**Comment by lhzbxx** [comment]
> ![image](https://user-images.githubusercontent.com/14831261/89848724-6fd6c400-dbb9-11ea-896c-83ed19a31577.png)
> 
> 和这个没关系

![5f32255a4dfc1_5f32255ab983f](https://user-images.githubusercontent.com/3831948/89859144-e46a2c80-dbd2-11ea-8b5f-651737770764.gif)

那您看一下这个呢。
我实测下来是有关系的。

**Comment by shaodahong** [comment]
嗯，设置成这样复现了

![image](https://user-images.githubusercontent.com/14831261/89860956-488eef80-dbd7-11ea-9530-911c94daba28.png)

**Comment by weiliang903** [comment]
@afc163 相似的 bug
当关闭 Drawer 组件时，body 会遗留一个 `overflow-y: hidden;` 样式，造成页面无滚动条，也就无法滚动。

**Comment by weiliang903** [comment]
> @afc163 相似的 bug 在 `antd@3.26.18`
> 当关闭 Drawer 组件时，body 会遗留一个 `overflow-y: hidden;` 样式，造成页面无滚动条，也就无法滚动。

已解决，同时关闭 Modal 和 Drawer 组件可能引起的冲突。一个 hack 方式是，关闭 modal 后 setTimtout 500ms 再关闭 drawer

**Comment by Zzy0706** [comment]
> > @afc163 相似的 bug 在 `antd@3.26.18`
> > 当关闭 Drawer 组件时，body 会遗留一个 `overflow-y: hidden;` 样式，造成页面无滚动条，也就无法滚动。
> 
> 已解决，同时关闭 Modal 和 Drawer 组件可能引起的冲突。一个 hack 方式是，关闭 modal 后 setTimtout 500ms 再关闭 drawer

确实得这样😂

**Comment by Youmoo** [comment]
在4.91版本中这个问题仍然存在，该问题的处理还有进度吗

**Comment by cdx111** [comment]
在4.22.1版本中这个问题仍然存在，该问题的处理还有进度吗
