### ISSUE TITLE
Breadcrumb.Item的重构出现了不兼容

### ISSUE THREAD

**Issue by Rhuaer** [ant-design/ant-design#25975]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/peaceful-taussig-zy0j3?file=/index.js)

### Steps to reproduce
1. 从页面上看到Mock Node后面少了一个分隔符/
2. 但如果切换到4.2.4版本的话是会有一个分隔符/

### What is expected?
期望在demo场景下仍然有分隔符

### What is actually happening?
demo场景下没有分隔符

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.11.0 |
| System | win 10 |
| Browser | chrome 83 |

---
这个现象是从4.3.0版本出现的，该版本对Breadcrumb使用hooks进行了重构，不兼容代码对比如下：

```js
//  4.2.4 BreadcrumbItem.tsx定义了默认值
  static defaultProps = {
    separator: '/',
  };

// 4.3.0 BreadcrumbItem.tsx中没有重新在BreadcrumbItem.defaultProps 定义separator
```

**Comment by lihqi** [comment]
https://github.com/ant-design/ant-design/blob/8c7f7b4295848cbefe0e16b59792c24e202030b5/components/breadcrumb/BreadcrumbItem.tsx#L20

`
  prefixCls: customizePrefixCls,
  separator = '/',
  children,
  overlay,
`

这样也没什么问题吧
