### ISSUE TITLE
对于/movie/:id这种路径，刷新后丢失，应该怎么才能解决，求方法

### ISSUE THREAD

**Issue by yuzhouisme** [ant-design/ant-design#2598]
#### 本地环境

- antd 版本: 1.1.0
- 操作系统及其版本：MacOS 10.11.5 
- 浏览器及其版本: Safari or Chrome

#### 你做了什么？

我写了下面这个路由，并将react-router从2.0.1升至最新2.6.1，以试图了解react-router最新的改动，并尝试解决“标题描述”的问题；

    <Route path="/" component={App}>
      <IndexRoute component={Index} />
      <Route path="courses" component={Index} />
      <Route path="about" component={About} />
      <Route path="movies" component={Movie}>
        <Route path="/movie/:movieId" component={Moovie}/>
      </Route>
      <Route path="movies/*" component={NotFound} />
      <Route path="books" component={Book} />
      <Route path="*" component={NotFound} />
    </Route>

当我跳转到/movie/1111路径时，这时候一旦刷新页面，就会报：

http://localhost:8989/movie/index.cssFailed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8989/movie/index.jsFailed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8989/movie/common.jsFailed to load resource: the server responded with a status of 404 (Not Found)

也不会匹配404页面，等等

#### 你期待的结果是：

正常打开

#### 追加描述

类似/movies页面，刷新页面之后，可以保持在原页面，方法是采用在Apache下做配置
但是对于这种/movie/xxx， 双斜线，求方法，谢谢！

**Comment by yuzhouisme** [comment]
是不是dora需要一些配置才能应对这种浏览器刷新？

**Comment by benjycui** [comment]
试下 https://github.com/dora-js/dora-plugin-browser-history ？

**Comment by yuzhouisme** [comment]
@benjycui 看了下，应该最新的antd工程，npm start 就应该是dora --plugins xxxx

具体如下：
"start": "dora --plugins \"proxy,webpack,webpack-hmr,livereload?enableJs=false&injectHost=127.0.0.1,browser-history?index=/src/entries/index.html\"",

**Comment by yuzhouisme** [comment]
@benjycui 把一个例子弄到线上了，可访问http://www.bestore.cc/movies，然后点击“跳转到”，这个时候路径会变成/movie/111，这个时候刷新。

**Comment by benjycui** [comment]
线上环境支持 browserHistory 的方式建议看 react-router 的文档。

**Comment by yuzhouisme** [comment]
好的，我找一下看看
