### ISSUE TITLE
<Form.List> with Autocomplete field

### ISSUE THREAD

**Issue by clemsos** [ant-design/ant-design#25981]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-0ui9m?file=/index.js)

### Steps to reproduce
1. Create an `Autocomplete` field within `<Form.List>` instance
2. Try to get the values from the `Form`

### What is expected?
`Form` should store value from the `Autocomplete` input field

### What is actually happening?
No value is returned by the `Form`

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | react |
| System | osx |
| Browser | Chrome |

---
I could not figure out how to use it properly so I opened this bug. I guess I should use the on Select or onChange to store the field state into the form but not sure how to achieve this

**Comment by bihongbin3027** [comment]
hi，You can replace it with：https://codesandbox.io/s/old-rain-cu8y7?file=/index.js

**Comment by clemsos** [comment]
@bihongbin3027 thank you for the answer. The `Select` only allow to pick a value that already exists.  I want user to also have the ability to write new input

**Comment by zombieJ** [comment]
You should wrap component with `value` & `onChange` prop directly:

https://codesandbox.io/s/antd-reproduction-template-05io6?file=/index.js

**Comment by clemsos** [comment]
That works, many thanks 🙏
