### ISSUE TITLE
rc-dialog 中 forceRender 导致 .ant-modal-wrap display: none

### ISSUE THREAD

**Issue by LiJiahaoCoder** [ant-design/ant-design#25999]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/naughty-nightingale-g0h32)

### Steps to reproduce
自定义 `Modal`:
```javascript
<Modal
  forceRender
  title={"修改初始密码"}
  visible={visible}
  closable={false}
  maskClosable={false}
  onCancel={onCancel}
>
  {/* children */}
</Modal>
```
`App.js` 使用：
```javascript
<Modal visible />
```

当 `visible` 设为 `true` 时，同时使用 `forceRender`，`rc-dialog` 中逻辑会将 `wrapper` 的 `style.display` 设为 `none`。

### What is expected?
在上述重现链接中，期望展示结果为：页面中展示 `Modal` 弹窗及 `children`

### What is actually happening?
在上述重现链接中，实际展示结果为：空白页面

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.3 |
| Browser | Chrome 84.0.4147.89 |

**Comment by LiJiahaoCoder** [comment]
`rc-tools` 中依赖已升级，是否考虑升级 `rc-test` 中的相关依赖，比如 `rc-tools` 中使用的最新 `gulp v4.0.0`，依赖版本不对称可能会引起一些问题。

**Comment by afc163** [comment]
统一升级到 father。

**Comment by LiJiahaoCoder** [comment]
已经提交pr，Travis构建失败，请检查Travis配置是否正确😁

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/dialog/pull/194
