### ISSUE TITLE
Tabs style follow design

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#2599]
http://ant.design/components/tabs/#components-tabs-demo-editable-card
## Expected

![](https://zos.alipayobjects.com/rmsportal/KNrbhxiISdlSoDV.png)

**Comment by benjycui** [comment]
对比了下，好像一样了，现在。

还是说我忽略了些细节？

**Comment by afc163** [comment]
+ 号紧贴页签右侧。

**Comment by benjycui** [comment]
Pending for: https://github.com/ant-design/ant-design/pull/3017

省的又要处理冲突。。

**Comment by benjycui** [comment]
有个疑问。

1. 如果页签数量较多，就会进入滑动模式。
1. 在滑动模式下，如果新增按钮紧贴右侧，那么用户左滑时，新增按钮就会被隐藏。

![image](https://user-images.githubusercontent.com/3580607/26963753-c58d5434-4d20-11e7-8188-f615683ce826.png)

**Comment by benjycui** [comment]
所以个人认为，现在把新增按钮固定在最右反而是兼容性更好的设计。

**Comment by afc163** [comment]
过长的时候，就固定在最右。不过长的时候，跟着最右的标签走。

**Comment by afc163** [comment]
trace #7206
