### ISSUE TITLE
![image](https://user-images.githubusercontent.com/12579967/82668117-ad3b4d80-9c6b-11ea-94e6-bf15acf6e7b5.png)

### ISSUE THREAD

**Issue by JarVZhao** [ant-design/ant-design#26003]
![image](https://user-images.githubusercontent.com/12579967/82668117-ad3b4d80-9c6b-11ea-94e6-bf15acf6e7b5.png)

_Originally posted by @songyanzhen in https://github.com/ant-design/ant-design/issues/23891#issuecomment-632668786_

奇怪,全配对了moment也不生效,仍然是一半英文,moment": "2.27.0","antd": "4.5.2",
import moment from "moment";
import "moment/locale/zh-cn";
moment.locale("zh-cn");

**Comment by pearone** [comment]
+1

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/issues/23891#issuecomment-624429227

**Comment by xrkffgg** [comment]
Duplicate of: https://github.com/ant-design/ant-design/issues/23891

**Comment by 0408jiahuicao** [comment]
+1

**Comment by Easyzhou** [comment]
+1，已经影响正常业务，怎么配置都不行

**Comment by xrkffgg** [comment]
> +1，已经影响正常业务，怎么配置都不行

#23891 看下这个
