### ISSUE TITLE
Select disappear without animation after select

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#26000]
- ✅ https://3x.ant.design/components/select/
- ❌ https://ant.design/components/select/

**Comment by afc163** [comment]
所有弹层组件（Tooltip/TreeSelect/Dropdown/Popover）的消失动画都没了。

**Comment by afc163** [comment]
可能是 https://github.com/react-component/animate/pull/108 的原因。

@yoyo837

**Comment by yoyo837** [comment]
我看看

**Comment by yoyo837** [comment]
react-component/animate#108 的修改还没有发布，应该是别的问题。

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/25852 ？

**Comment by afc163** [comment]
可能是 https://github.com/react-component/trigger/pull/191

**Comment by atom-shanghai** [comment]
360极速浏览器，select 失效

**Comment by zombieJ** [comment]
> 可能是 [react-component/trigger#191](https://github.com/react-component/trigger/pull/191)

嗯，这个的问题。
