### ISSUE TITLE
Menu.ItemGroup cannot be used as a JSX component.

### ISSUE THREAD

**Issue by patrickomeara** [ant-design/ant-design#26004]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
ts compile error only

### Steps to reproduce
```tsx
                <Dropdown
                    overlay={(
                        <Menu>
                            <Menu.Item>Option 0</Menu.Item>
                            <Menu.Divider />
                            <Menu.ItemGroup title="Options">
                                <Menu.Item>Option 1</Menu.Item>
                            </Menu.ItemGroup>
                        </Menu>
                    )}
                >
                    <a className="ant-dropdown-link" onClick={e => e.preventDefault()}>
                        Cascading menu <DownOutlined />
                    </a>
                </Dropdown>
```

### What is expected?
I expect the typescript compiler to finish without errors

### What is actually happening?
```
TS2607: JSX element class does not support attributes because it does not have a 'props' property.

TS2786: 'Menu.ItemGroup' cannot be used as a JSX component.
  Its instance type 'MenuItemGroup' is not a valid JSX element.
    Type 'MenuItemGroup' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.
```

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | macos  |
| Browser | firefox latest |

---
This is only happening for ItemGroup. Item and SubMenu work as expected.

The only difference I can find is the ItemGroup types comes directly from `rc-menu`. The others have types in antd

https://github.com/ant-design/ant-design/blob/87555eb5a9dda92af7fb7a4d6146c08cfb1f98c3/components/menu/index.tsx#L2-L6

```ts
// antd/lib/menu/index.d.ts

import SubMenu from './SubMenu';
import Item from './MenuItem';
import { MenuTheme } from './MenuContext';
export { MenuItemGroupProps } from 'rc-menu';
```

**Comment by Kermit-Xuan** [comment]
OK, i will handle it.

**Comment by Kermit-Xuan** [comment]
@patrickomeara what's the version of typescript?

It's normal in this case:
https://codesandbox.io/s/eager-moon-x7slt?file=/src/App.tsx

**Comment by patrickomeara** [comment]
Hi @Kermit-Xuan I am using Typescript 3.9.7 with the following tsconfig

```
{
  "compilerOptions": {
    "baseUrl": "./react",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": [
      "dom",
      "es7"
    ],
    "module": "esnext",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noUnusedLocals": true,
    "suppressImplicitAnyIndexErrors": true,
    "strictNullChecks": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "./react/**/*"
  ]
}
```

**Comment by Kermit-Xuan** [comment]
You can add `"esModuleInterop": true` to `compilerOptions`.

Because `MenuItemGroup` uses `import React from "react"`, `esModuleInterop` must be `true`.

**Comment by afc163** [comment]
https://github.com/react-component/menu/commit/9c2adc67ad630a2d3edf476b5176b6adc1ee3793

**Comment by Kermit-Xuan** [comment]
@patrickomeara 

You can remove `node_modules` and `package-lock.json`, then run `npm i`.

**Comment by patrickomeara** [comment]
Thanks, the update has worked.
