### ISSUE TITLE
Table selection doesn't work on IE11

### ISSUE THREAD

**Issue by fragsalat** [ant-design/ant-design#26016]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-row-selection](https://ant.design/components/table/#components-table-demo-row-selection)
PS: Seems like there is a general error on your documentation page in IE11 but I tried the tables also on local app in IE11

### Steps to reproduce
- Open the page
- Click on a select box
- Checkbox never get's checked

### What is expected?
- Open the page
- click on select box
- checkbox is checked and table select all is on state intermediate

### What is actually happening?
When clicking the checkbox the tables rowSelection.onChange callback is called but it is only passed an empty array

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | Win 10 |
| Browser | IE11 |

**Comment by zombieJ** [comment]
antd official site do not support IE11. You should add polyfill code with IE11 in you app.

**Comment by fragsalat** [comment]
I already use babel-env with ie 11 query. Also Checkboxes itself work but not within the table component

**Comment by zombieJ** [comment]
Could you provide an git repo?

**Comment by fragsalat** [comment]
While preparing the example repo I found out the issue was a broken polyfill. Sorry for disrubtion and have a nice day
