### ISSUE TITLE
Tree dynamic update Demo1(class Component) error

### ISSUE THREAD

**Issue by oosugi84** [ant-design/ant-design#26017]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-elion-lfz8t?file=/index.js)

### Steps to reproduce
run the link provided

### What is expected?
works as Demo

### What is actually happening?
cannot display the children

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.12.0 |
| System | codesandbox |
| Browser | chrome latest |

---
js: https://codesandbox.io/s/angry-elion-lfz8t
ts: https://codesandbox.io/s/charming-allen-n30xi

both have the same problem

**Comment by zombieJ** [comment]
It's no related with class component or function component. You code with Demo1 modify the treeData directly which make internal memo logic think tree is not change.

**Comment by zombieJ** [comment]
> It's no related with class component or function component. You code with Demo1 modify the treeData directly which make internal memo logic think tree is not change.

Pls follow the workable one to create a new tree data instead.
