### ISSUE TITLE
Unable to Get Binary HTTP Response After Uploading File Using Upload Component (multipart/form-data)

### ISSUE THREAD

**Issue by jcald1** [ant-design/ant-design#26013]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jcald1/datadeck.git  (installation instructions)](https://github.com/jcald1/datadeck.git  (installation instructions))

### Steps to reproduce
Deploy according to the Readme instructions
Go to http://localhost:3000
Click on upload CSV File (https://github.com/datadeckllc/ddpkg/blob/master/sosCa/test.csv is a good sample)

### What is expected?
The server returns a binary file in the response with the proper Content-Type and Content-Disposition.  The Chrome browser does not open the file.
I see that the Upload component info.file.response has the response as a string, but when I tried to save this file (commented out in datadeck/components/dragger.js), the file is corrupted.  I believe this is because you are holding on to response a string instead of a byte array.  Ideally we the whole response would not be stored in memory and the download would just happen, but at the very least I would change this value to be a byte array, which would allow users to be able to handle the binary data.

### What is actually happening?
The file does not open.
After manually adding code to download the file from Upload component info.file.response, the resulting file is corrupted.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | Linux Mint |
| Browser | Chrome |

**Comment by grip-service** [comment]
Please see https://github.com/jcald1/datadeck.git instead of https://github.com/datadeckllc/datadeck.

**Comment by zombieJ** [comment]
Your demo do not accept `csv` file. Seems it only accept excel file. Demo should be update. Or you can use sandbox to create a simple demo.
