### ISSUE TITLE
修改message全局提示的样式问题 

### ISSUE THREAD

**Issue by mingyangsama** [ant-design/ant-design#26029]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
修改message全局提示的样式问题 

### What does the proposed API look like?
修改message全局提示的样式问题

**Comment by yoyo837** [comment]
可以使用prefix

**Comment by afc163** [comment]
不知所云。
