### ISSUE TITLE
Tabs 组件的 onEdit 难以理解。

### ISSUE THREAD

**Issue by xiaorong61** [ant-design/ant-design#26023]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-ik1uy?file=/index.tsx)

### Steps to reproduce
书写 Tabs 组件 onEdit 属性时

### What is expected?
vscode 提示回调函数 (e: string, action: 'add' | 'remove') => void;

### What is actually happening?
vscode 提示回调函数 (e: React.MouseEvent | React.KeyboardEvent | string, action: 'add' | 'remove') => void;

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | OSX 10.15.6 |
| Browser | Edge 84.0.522.52 |

---
在 umijs 使用 antd

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/c72be7bdda2bb2f3f320e8350464428d40f07c46/components/tabs/index.tsx#L24

**Comment by xiaorong61** [comment]
> https://github.com/ant-design/ant-design/blob/c72be7bdda2bb2f3f320e8350464428d40f07c46/components/tabs/index.tsx#L24

我修改了一下，我现在的问题是为什么onEdit 第一个参数可以是字符串也可以是事件？从官网的文档来看第一个参数是当做字符串用的。

![image](https://user-images.githubusercontent.com/5251387/89384539-d169df00-d730-11ea-87ac-9dcc1c85d6d0.png)

**Comment by afc163** [comment]
点 `+` 新增 tab 的时候参数为 event：https://github.com/ant-design/ant-design/blob/c72be7bdda2bb2f3f320e8350464428d40f07c46/components/tabs/index.tsx#L36

**Comment by hengkx** [comment]
修改一下文档说明吧

**Comment by hengkx** [comment]
处于什么考虑 而 没有使用 如 `onAdd` `onRemove`

**Comment by afc163** [comment]
精简 API 数量。

**Comment by xiaorong61** [comment]
原来是根据 action 决定的，懂了。
