### ISSUE TITLE
气泡卡片结合Form提示用户输入在样式上出现了不相容

### ISSUE THREAD

**Issue by yctjb1** [ant-design/ant-design#26033]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-vnl7gd](https://stackblitz.com/edit/react-vnl7gd)

### Steps to reproduce
输入数字12因为小于3位所以触发rules效验使得Popover判断right居中的总高变高导致三角箭头下移

### What is expected?
Form.Item中能够接受Popover包裹Input

### What is actually happening?
如果在Form.Item中使用Popover包裹Input会导致无法触发rules，只得Popover包Form.Item包Input但是存在上述提到的rules验证开启时的气泡箭头定位误差

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.12.0 |
| System | windows10 |
| Browser | chrome84.0.4147.105 |

---
说严重也不严重，如果不在优化范围内，那我就索性为了Popover放弃Form好了

**Comment by xrkffgg** [comment]
Popover 包着 Item，显示的位置是 它的中间这没错。

你这个需求，感觉可以动态加个 align 设置 offset 来弄。
http://localhost:8001/components/tooltip-cn/#API
https://github.com/yiminghe/dom-align

**Comment by afc163** [comment]
Try this way: https://stackblitz.com/edit/react-jrj7va
