### ISSUE TITLE
fr_FR localization spelling error

### ISSUE THREAD

**Issue by Thanaen** [ant-design/ant-design#26031]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-frfr-spelling-error-etkej?file=/index.js)

### Steps to reproduce
Click two times on the column sorter, then keep your mouse hover the sorter

### What is expected?
There should be "Annuler le tri"

### What is actually happening?
There's "Annuler le trie"

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Firefox 79 |

**Comment by xrkffgg** [comment]
PR welcome
