### ISSUE TITLE
<Row></Row>组件在同一行闭合会报错？

### ISSUE THREAD

**Issue by xieyihao** [ant-design/ant-design#2603]
#### 本地环境
Node版本：v4.4.7
npm版本：3.10.5

- antd 版本:
v1.7.0
- 操作系统及其版本：
Microsoft Windows [版本 10.0.10586]
- 浏览器及其版本:
Chrome 版本 52.0.2743.82 m

#### 你做了什么？
引入了<Row>组件
 ```
<Row>  
   { this._renderThead()}  
 </Row>
 ```

想把</Row>合并到同一行
`<Row> { this._renderThead()}  </Row>`

#### 你期待的结果是：
正常运行

#### 实际上的结果：
报错了

> TypeError: Cannot read property 'style' of undefined

**Comment by xieyihao** [comment]
![image](https://cloud.githubusercontent.com/assets/12508868/17364778/d72059ae-59b4-11e6-88eb-5e50c2f3d0a5.png)

**Comment by xieyihao** [comment]
好奇怪的问题啊，也没找到是什么原因

**Comment by xieyihao** [comment]
刚刚删掉了空格测试了下，确实正常了。
但有空格也报错，太奇怪了，修复下？

**Comment by afc163** [comment]
Done 🎅

**Comment by xieyihao** [comment]
太有速度了吧 ！！
