### ISSUE TITLE
inputNumber handler background in dark

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#26037]
### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-hofstadter-hdrrx)

- 点开链接可发现。目前 background 是透明，会透出下方的图标。

![image](https://user-images.githubusercontent.com/29775873/89397260-3aa61e00-d742-11ea-9172-c6a219db3545.png)

### 该交互目前包含 4 种颜色。

![image](https://user-images.githubusercontent.com/29775873/89397165-12b6ba80-d742-11ea-9289-185081ad0b91.png)

现有色值：

1. 背景色 transparent 
2. 边框色 #434343
3. icon 色  rgb(255,255,255,0.45)
4. icon hover 色  #165996

**Comment by zombieJ** [comment]
印象里 @ycjcl868 有处理过，估计是坏了。

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/commit/208d954a1d6b2f5ed7008e0b10097a15e92002f7

找到之前的历史了。可能当时没有定位这种情况的。
