### ISSUE TITLE
table filterDropdown使用getPopupContainer进行绑定父元素时，如果同时有body滚动需要和scroll:x，scroll:y滚动需要，或者是表格为空的情况，会出现浮层位置错误的情况

### ISSUE THREAD

**Issue by hzura** [ant-design/ant-design#26038]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/spring-sky-p9ry9?file=/index.js)

### Steps to reproduce
当getPopupContainer绑定外层的scrollnode时，使用双指横向滑动表格浮层位置不变；
当getPopupContainer绑定parentNode时，与scroll:y 同时使用会出现浮层位置出错；另外，不设置scroll:x但是表格筛选出空表格时，一样会出现浮层错误。

### What is expected?
浮层位置正确

### What is actually happening?
浮层位置错误

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.13.1 |
| System | macos catalina 10.15.4 |
| Browser | chrome |

---
场景比较复杂，还是说明一下业务需求吧

实际中的场景是，有scroll：x需求（字段名过多），有body滚动需要（浏览器不是全屏），有scroll：y需求（子表格弹窗），可能筛选出空表格（不用多说），目前看起来最好的方案是绑定外层的scrollnode同时scroll：y设置得大一点，不过还是想反馈一下这个issue

感觉主要的问题在于绑定parentNode时定位函数的计算，要保证筛选框不能超出表头或者表格，所以就会出现浮层位置错误，有没有统一的解决方案呢？

**Comment by afc163** [comment]
你的例子我打开看没什么问题，怎样算是浮层位置错误呢，预期的浮层位置是什么？

<img width="712" alt="image" src="https://user-images.githubusercontent.com/507615/89399764-7b536680-d745-11ea-9414-afe763bae004.png">

**Comment by hzura** [comment]
> 你的例子我打开看没什么问题，怎样算是浮层位置错误呢，预期的浮层位置是什么？
> 
> <img alt="image" width="712" src="https://user-images.githubusercontent.com/507615/89399764-7b536680-d745-11ea-9414-afe763bae004.png">


忘记加scroll:y了（捂脸），我修改一下吧
另外现在的情况下（绑定的parentnode且不设置scroll:y），横纵向滚动没有问题，但是假如搜索结果为空时浮层位置会出现错误

**Comment by afc163** [comment]
确实比较蛋疼，我能想到的最好方式是这样的：https://codesandbox.io/s/lingering-smoke-5orqc?file=/index.js

**Comment by hzura** [comment]
这个方法筛选为空的时候就甚至不跳出来了(捂脸)

**Comment by afc163** [comment]
> 这个方法筛选为空的时候就甚至不跳出来了

来个重现。

**Comment by lirunwin** [comment]
不仅如此, 让切换getPopupContainer在body 和parent切换的时候也会出现问题. 全屏的时候的用parent  其余时候用body.

**Comment by hzura** [comment]
![image](https://user-images.githubusercontent.com/44900485/89408484-05ee9280-d753-11ea-890e-6e7a8df0e182.png)
这样的情况下点击自定义筛选按钮不会弹出filterdropdown

**Comment by afc163** [comment]
给重现。

**Comment by hzura** [comment]
https://codesandbox.io/s/lingering-smoke-5orqc?file=/index.js
问题：使用getPopupContainer属性将下拉框绑定到ant-table-body元素时，筛选结果为空时不会再次弹出自定义筛选框
重现步骤：点击自定义筛选按钮，输入sss搜索，搜索后表格为空，再点击筛选按钮不会再次弹出自定义筛选框
猜测原因：筛选结果为空时ant-table大小也为空，而浮层不能超出ant-table大小

**Comment by afc163** [comment]
3.x 不维护了，升级到 4.x 吧：https://codesandbox.io/s/twilight-wind-usy03?file=/index.css

上面的例子别忘了给 `.ant-table-body` 加上 `position: relative`。
