### ISSUE TITLE
Descriptions 组件，当column=3，只有两个Descriptions.Item时，其中一个Item设置span=2，这个Item还是没有占用2个位置

### ISSUE THREAD

**Issue by wangxiang1** [ant-design/ant-design#26036]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-isdv2?file=/index.js:0-473)

### Steps to reproduce
1、使用官网Descriptions组件-带边框的样例代码
2、只保留Order time和Usage Time这一行，删除其他Item
3、发现UsageTime不再占用2个位置，而是两个Item等分

### What is expected?
column为3时，Descriptions.Item设置的span小于3时，应该生效，当只有两个Item时，一个Item span=1，另一个item span=2，此时两个item应该是1：2的大小，而不是1：1

### What is actually happening?
两个Item是1：1

| Environment | Info |
|---|---|
| antd | 3.20.0 |
| React | 16.8.1 |
| System | window10 |
| Browser | Chrome78 |

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/89613379-adcfa180-d8b4-11ea-86cb-b92b0e7a95f3.png)
因为 table-layout 是 auto 导致的这个问题。

可以覆盖一下。
```css
table {
  table-layout: fixed !important;
}
```

以及似乎默认状态下 description 就是响应式的，可能文档没有更新，太窄的时候是两列的。

**Comment by wangxiang1** [comment]
谢谢 非常有帮助 能实现我的需求 @07akioni

**Comment by wangxiang1** [comment]
已经通过设置
`table {
  table-layout: fixed !important;
}`
覆盖了table样式，解决了这个问题。
