### ISSUE TITLE
Using date-fns the 'Month' don't appears in the Date Picker header

### ISSUE THREAD

**Issue by Tsuna-mi** [ant-design/ant-design#26045]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-biwo2?file=/index.js)

### Steps to reproduce
- use date-fns generator to load rc-picker
- Open the Datepicker loaded

### What is expected?
The 'shortMonth' appears before the year in the panel header of the component

### What is actually happening?
The string with the shortMonth seems not to be generated properly using date-fns generator.
```
<div class="ant-picker-header-view">
   <button type="button" tabindex="-1" class="ant-picker-month-btn"></button>
   <button type="button" tabindex="-1" class="ant-picker-year-btn">2020</button>
</div>
```

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | macOS mojave 10.14.6 |
| Browser | chrome 84.0.4147.105  |

**Comment by xindixu** [comment]
Also, weekdays aren't generated as well. 
```
<table class="ant-picker-content">
  <thead>
    <tr>
      ...
      <th></th>
      ...
    </tr>
  </thead>
</table>
```

**Comment by fireairforce** [comment]
ok, i will see it~

**Comment by fgblomqvist** [comment]
Is there an update on this @fireairforce? Is this is a bug in antd or in rc-picker you think?

**Comment by miaopeng** [comment]
@fgblomqvist A simple workaround is override Datepicker interface functions, rc-picker component did not provide these functions to generate date-fns Datepickers, here is a sample for zhCN locale:

```
const originFormat = config.locale.format;
Object.assign(config.locale, {
  getShortMonths: () => [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ],

  getShortWeekDays: () => ['日', '一', '二', '三', '四', '五', '六'],
  format: (local: string, date: Date, format: string) => {
    if (/\[.+\]/.test(format)) {
      const f = format.replace(/\[|\]/g, "'");
      return originFormat(local, date, f);
    }
    return originFormat(local, date, format);
  },
});

const DatePicker = generatePicker<Date>(config);
```
This can resolve shortMonth, weeekdays and Quarter format in data-fns Datepickers. And you should change the names with your locale names.

**Comment by fireairforce** [comment]
> Is there an update on this @fireairforce? Is this is a bug in antd or in rc-picker you think?

I think it may be a error on rc-picker, sorry i am busy on other things these days~

**Comment by fgblomqvist** [comment]
@fireairforce Yeah as @miaopeng pointed out above, this is indeed a "problem"/missing implementation in rc-picker.

**Comment by fgblomqvist** [comment]
I put together a more complete/dynamic solution that supports different locales over in the rc-picker thread:
https://github.com/react-component/picker/issues/128#issuecomment-675527252

It will still require you to explicitly list which locales you want to support, but that's just how it should be in order to keep bundle size down. Kudos to @miaopeng for the inspiration.

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/picker/pull/115
