### ISSUE TITLE
Badge color should be themable with out changing @highlight-color

### ISSUE THREAD

**Issue by sorahn** [ant-design/ant-design#26040]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will allow users to define a default background color for the badge component with out changing the @highlight-color for the entire theme.

### What does the proposed API look like?
Add `@badge-background-color: @highlight-color` here
https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less#L659

Change this line to `background: @badge-background-color`
https://github.com/ant-design/ant-design/blob/master/components/badge/style/index.less#L26

I would be happy to open a PR for this.

**Comment by afc163** [comment]
@badge-color is better.

**Comment by sorahn** [comment]
> @badge-color is better.

No problem!
