### ISSUE TITLE
Message Component Cannot be Closed

### ISSUE THREAD

**Issue by jcald1** [ant-design/ant-design#26054]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2x.ant.design/components/message/](https://2x.ant.design/components/message/)

### Steps to reproduce
Send a message (success or failure)

### What is expected?
The user should be able to close the pop up.  This is especially important when overriding the default duration.  For example, the failure message has an X, but when you click on it, it doesn't close.

### What is actually happening?
There's no way to close the message

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | Linux Mint |
| Browser | Chrome |

**Comment by Veynee** [comment]
2.x?

**Comment by afc163** [comment]
https://codesandbox.io/s/determined-hawking-v4fzl?file=/index.js

https://ant.design/components/message/#components-message-demo-loading

**Comment by afc163** [comment]
supported in #26052

**Comment by jcald1** [comment]
@afc163 , how do you tie the `message.destroy()` to a user click?  Is there a `onClick` property?  I don't see that in the documentation.

**Comment by gianpo86** [comment]
Thanks for including this feature in the v4.6.0. I have the 4.6.4 and I am still not able to destroy a specific message via key.

Here my code:

```
import { message } from "antd";
...
const msgKey = Math.random().toString();

const config = {
  key: msgKey,
  type: "info",
  content: "test message",
  duration: 0,
  className: "custom-ant-message-container",
};

message.open(config);
const closeMessage = () => message.destroy(msgKey); //Invalid number of arguments, expected 0
...
```
The message I get from the IDE is `Invalid number of arguments, expected 0`

Inspecting the imported `message`, the IDE redirects me to `/node_modules/antd/lib/message/index.d.ts` and there, at line 45 there is a: 

```
export interface MessageApi extends MessageInstance {
    warn(content: JointContent, duration?: ConfigDuration, onClose?: ConfigOnClose): MessageType;
    config(options: ConfigOptions): void;
    destroy(): void;
    useMessage(): [MessageInstance, React.ReactElement];
}
```
 Where `destroy` has indeed no input parameter......

However, in the neighbour file `/node_modules/antd/lib/message/index.js` at line 184 there is a 

```
var api = {
  open: notice,
  config: setMessageConfig,
  destroy: function destroy(messageKey) {
    if (messageInstance) {
      if (messageKey) {
        var _messageInstance = messageInstance,
            removeNotice = _messageInstance.removeNotice;
        removeNotice(messageKey);
      } else {
        var _messageInstance2 = messageInstance,
            destroy = _messageInstance2.destroy;
        destroy();
        messageInstance = null;
      }
    }
  }
};
```

Where the message has a key as optional input parameter.

So my question is: am I importing the message wrongly? or there is a Bug in the index.d.ts file?

Thanks

**Comment by gianpo86** [comment]
> @afc163 , how do you tie the `message.destroy()` to a user click? Is there a `onClick` property? I don't see that in the documentation.

Just bind it by yourself:

```
const config = {
  key: msgKey,
  ...
};
message.open(config);
const closeMessage = () => message.destroy(msgKey);
```

However, I actually have the issue that message.destroy( does not accept any key as input parameter - see my question above)

**Comment by gianpo86** [comment]
@afc163 just updated to antd 4.6.5 and the issue still persists

**Comment by lihqi** [comment]
@gianpo86 thanks for your report , I will PR as soon as possible

**Comment by lihqi** [comment]
> @afc163 , how do you tie the `message.destroy()` to a user click? Is there a `onClick` property? I don't see that in the documentation.

If you need it
[example](https://codesandbox.io/s/interesting-cherry-60z35?file=/index.js)

**Comment by EPEduardoPaixao** [comment]
I did it that way

 message.info(
      {
      key: 'msgKey',
      content: "Test message",
      duration:5,
      className: "custom-class",
      onClick:(() => message.destroy('msgKey'))
    }
    );

**Comment by EPEduardoPaixao** [comment]
that way when I click on the message it closes, I'm working to put an icon and only close when I click on it

**Comment by l443018** [comment]
> that way when I click on the message it closes, I'm working to put an icon and only close when I click on it

you could customise content and put a close icon on the right, and detect icon's class name in onClick handler

```js

export const customMessage = {
  error: (content: string, duration?: number) => {
    const key = `${new Date().getTime()}_${Math.random()}`;
    message.error({
      key,
      content: (
        <>
          {content}
          <div className="custom-message-close">
            <CloseOutlined className="pointer-events-none" />
          </div>
        </>
      ),
      duration: duration ?? 10,
      onClick: event => {
        if (event.target.classList?.contains('custom-message-close')) {
          message.destroy(key);
        }
      },
    });
  },
};
```

usage:

```
customMessage.error('some error message')
```

![image](https://github.com/ant-design/ant-design/assets/7532024/0a880c98-f74e-41db-bd1e-1cd5c04923f6)
