### ISSUE TITLE
Forcing Service Worker to update the new build

### ISSUE THREAD

**Issue by sunnixx** [ant-design/ant-design#26058]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently whenever a new build is deployed. The service worker waits to detect new hashes and then pops the Refresh bar. But this sometimes doesn't show until we refresh the site altogether or sometimes even hard refresh it. 
So I believe there should be a way to force the Service worker to show the "refresh" pop so that this problem doesn't occur and disrupt user experience. 

### What does the proposed API look like?
I would say something that can trigger the 'message' event that the service worker is listening.

**Comment by afc163** [comment]
I don't think there is any relevance with antd.

**Comment by sunnixx** [comment]
Thanks for the update. @afc163 but then can you guide me where I can sort this out ? Since we're looking for a way to force refresh on the SW.
