### ISSUE TITLE
添加分屏组件

### ISSUE THREAD

**Issue by axetroy** [ant-design/ant-design#26055]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在一些场景中需要进行分屏

例如 A | B | C

这三个屏可以通过鼠标拖拽改变宽高

### 为什么不用 Tab？

Tab 并不是分屏，只能看到一个 Tab，而不能同时看多个

### 为什么不用 row col？

Row Col 可以满足分屏效果，但是没有拖拽改变大小

### What does the proposed API look like?
```jsx
import { Screen } from "ant-design"

function main () {
  return <Screen>
    <Screen.Item>
      A Screen
    </Screen.Item>
    <Screen.Item>
      B Screen
    </Screen.Item>
    <Screen.Item>
      C Screen
    </Screen.Item>
  </Screen>
}
```

**Comment by afc163** [comment]
Try https://github.com/tomkp/react-split-pane

**Comment by afc163** [comment]
#12636
