### ISSUE TITLE
upload 是否支持先本地预览，再单独点击某个按钮触发上传请求

### ISSUE THREAD

**Issue by imxiongying** [ant-design/ant-design#2605]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

**Comment by benjycui** [comment]
应该说是浏览器不支持吧，毕竟 img 无法引用本地的文件，必须先上传。

**Comment by infeng** [comment]
可以通过beforeUpload属性先阻止上传来实现这个效果

**Comment by benjycui** [comment]
@infeng 不懂。。。阻止上传不是问题，问题是怎么预览。

**Comment by infeng** [comment]
beforeUpload的参数是File对象，然后通过file api获取base64不就可以实现预览了吗

**Comment by benjycui** [comment]
😅 犯二了，毕竟很久没用过 base64 了。。

**Comment by benjycui** [comment]
@infeng thanks, @imxiongying close now.
