### ISSUE TITLE
Setting indeterminate state on `rowSelection` with `getCheckboxProps` only partially works

### ISSUE THREAD

**Issue by NobleMule** [ant-design/ant-design#26053]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-vl8jo)

### Steps to reproduce
Table with row named "Indeterminate User" should be in an indeterminate state initially. Upon selecting this checkbox, the name changes to "NEW NAME" and no longer meets the criteria

### What is expected?
The checkbox should lose it's indeterminate state and now go back to toggling between checked and unchecked

### What is actually happening?
It appears to have updated the selected row list as the "check all" box toggles between indeterminate and unchecked but the row itself remains in an indeterminate state

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | Ubuntu 20.04 |
| Browser | Chromium 84.0.4147.105 |

---
This issue was not present in 4.3.5 but is present in all versions from 4.4.0 up to the latest (4.5.2 at time of writing). This link shows the exact same code working when using 4.3.5: https://codesandbox.io/s/antd-reproduction-template-r96oi

This was discovered because we have a table representing data that can have one or more options associated with it. The user can modify these options by selecting one or more table rows and launching a new modal that contains the currently selected options for the rows you've just selected. The options will be pre-selected where that option is already applied to the selected rows, clear if it applies to none of the selected rows and indeterminate when selected to some of the selected rows. The user can check or uncheck options which will then be added or removed from the previously selected rows. If an indeterminate row is unchanged then the option remains applied to the original subset of data. When it is checked, this association is lost and it should apply to all or be removed from all selected items. The continued appearance of being indeterminate will cause confusion for the end user.

**Comment by afc163** [comment]
`indeterminate` is always true in your codesandbox, it is controlled behavior that is expected.
