### ISSUE TITLE
date range picker , bug when type date from same month in startdate and enddate

### ISSUE THREAD

**Issue by nikhilsonavane** [ant-design/ant-design#26068]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-9hde3?file=/index.js)

### Steps to reproduce
date range picker date format: MM/DD/YYYY
type date manually in one shot:    08/05/2015 and  08/10/2015

### What is expected?
expected output for enddate is  08/10/2015

### What is actually happening?
it shows enddate   09/10/2015

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.13.0 |
| System | windows 10 |
| Browser | chrome |

---
when we type startdate and enddate  manually,   that time it add one month if we write date range in same month

**Comment by afc163** [comment]
3.x is not maintianed anymore, please try antd@4.x
