### ISSUE TITLE
目前UI主色调为蓝色，如果需要主题切换(只变更UI颜色)，该如何优雅实现？

### ISSUE THREAD

**Issue by imxiongying** [ant-design/ant-design#2606]
#### 本地环境

- antd 版本:1.6.5
- 操作系统及其版本：mac 10.11.5
- 浏览器及其版本:50.0.2661.102

#### 你做了什么？
如何优雅的实现自定义的css主题切换，仅针对UI的颜色？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/wiki/FAQ#how-to-modify-antds-colour-scheme

Please read [documentation](http://ant.design/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).
