### ISSUE TITLE
Pagination 组件输入跳转页码不清空问题

### ISSUE THREAD

**Issue by Felix-Prince** [ant-design/ant-design#26061]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/pagination/#components-pagination-demo-mini](https://ant.design/components/pagination/#components-pagination-demo-mini)

### Steps to reproduce
1. 在跳转页面的框中输入目标页
2. 不要用回车，在别的地方点击一下实现跳转
3. 手动点击页码或者修改切换每页数

### What is expected?
输入的页码可以清空

### What is actually happening?
通过回车的方式跳转的时候，页码框中输入的数字会自动清空，但是如果是失焦的方式，输入的页码会一直存在

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8.6 |
| System | MacBook Pro 2.3 GHz 四核Intel Core i7 |
| Browser | Google Chrome  84.0.4147.105 |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/pagination/pull/298
