### ISSUE TITLE
TreeSelect When `autoClearSearchValues` is set to `false`, there is a problem with checking after searching

### ISSUE THREAD

**Issue by AsakuraC** [ant-design/ant-design#26065]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wizardly-snowflake-ktj1t?file=/index.js)

### Steps to reproduce
1. open TreeSelect
2. search 2
3. check `Node 2`
4. close TreeSelect
5. open TreeSelect

### What is expected?
all checked

### What is actually happening?
not all

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.3.1 |
| System | macOS 10.15.5  |
| Browser | Chrome 最新版 |

**Comment by AsakuraC** [comment]
![如图](https://note.youdao.com/yws/api/personal/file/WEB96a3ff5b40a721d84406d1f4edd951d2?method=download&shareKey=c3951662664e1e60c15107edb23a56d4)

**Comment by AsakuraC** [comment]
![treeselect-error](https://user-images.githubusercontent.com/18549833/89529308-13714e80-d81f-11ea-861d-926277b9450d.gif)
错误如图

**Comment by flyerH** [comment]
Add props `treeNodeFilterProp: "title"` can work~

**Comment by AsakuraC** [comment]
> Add props `treeNodeFilterProp: "title"`, it can work~
> https://codesandbox.io/s/sad-platform-3p08o?file=/index.js

![image](https://user-images.githubusercontent.com/18549833/89635417-87702d00-d8d9-11ea-8241-510908d126f0.png)
Child Node1 is not checked

**Comment by AsakuraC** [comment]
？
