### ISSUE TITLE
Select component tagRender (mode *default*) not working.

### ISSUE THREAD

**Issue by caocuong2404** [ant-design/ant-design#26074]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hardcore-austin-q7ud5)

### Steps to reproduce
I added function and infused into **Select props**, but the value is shown in the **Input** incorrect.
.e.g:
```javascript
const _tagRender = (props) => `prefix: ${props.value} `;
...
<Select
    tagRender={_tagRender}
    // mode="multiple" (uncomment this, it's work)
    ...
  >
    ...
</Select>
```

### What is expected?
I want the feature tagRender working on mode default

### What is actually happening?
this a bug, because it does not go through the transformer function

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.12.6 |
| System | MacOS 10.15.6 |
| Browser | Firefox Developer 80 |

**Comment by caocuong2404** [comment]
>     * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> 
> ### Reproduction link
> 
> [![Edit on CodeSandbox](https://camo.githubusercontent.com/416c7a7433e9d81b4e430b561d92f22ac4f15988/68747470733a2f2f636f646573616e64626f782e696f2f7374617469632f696d672f706c61792d636f646573616e64626f782e737667)](https://codesandbox.io/s/hardcore-austin-q7ud5)
> ### Steps to reproduce
> 
> I added function and infused into **Select props**, but the value is shown in the **Input** incorrect.
> .e.g:
> 
> ```js
> const _tagRender = (props) => `prefix: ${props.value} `;
> ...
> <Select
>     tagRender={_tagRender}
>     // mode="multiple" (uncomment this, it's work)
>     ...
>   >
>     ...
> </Select>
> ```
> 
> ### What is expected?
> 
> I want the feature tagRender working on mode default
> ### What is actually happening?
> 
> this a bug, because it does not go through the transformer function
> Environment 	Info
> antd 	4.5.2
> React 	16.12.6
> System 	MacOS 10.15.6
> Browser 	Firefox Developer 80

**Comment by 07akioni** [comment]
https://codesandbox.io/s/thirsty-borg-zt8kf

you can use `optionLabelProp`

**Comment by caocuong2404** [comment]
> https://codesandbox.io/s/thirsty-borg-zt8kf
> 
> you can use `optionLabelProp`

@07akioni My problem:

options pattern: 
```typescript
{ value: item.member_id, label: <EntityUser userId={item.member_id} /> }
```  
but tagRender function i want shown in the ** Input Select** is: **EntityUserCompact** and value still the **item.member_id**
```typescript
const tagRenderUser = (props) => {
    return <span className="selected-tag-item">
        <EntityUserCompact userId={props.value} />
    </span>;
};
```
![image](https://user-images.githubusercontent.com/50004497/89608488-7276a800-d89f-11ea-93f0-aa9b1387824c.png)

**Comment by 07akioni** [comment]
> > https://codesandbox.io/s/thirsty-borg-zt8kf
> > you can use `optionLabelProp`
> 
> @07akioni My problem:
> 
> options pattern:
> 
> ```ts
> { value: item.member_id, label: <EntityUser userId={item.member_id} /> }
> ```
> 
> but tagRender function i want shown in the **Input Select** is: **EntityUserCompact** and value still the **item.member_id**
> 
> ```ts
> const tagRenderUser = (props) => {
>     return <span className="selected-tag-item">
>         <EntityUserCompact userId={props.value} />
>     </span>;
> };
> ```
> 
> ![image](https://user-images.githubusercontent.com/50004497/89608488-7276a800-d89f-11ea-93f0-aa9b1387824c.png)
> Like this:
> ![image](https://user-images.githubusercontent.com/50004497/89608672-fa5cb200-d89f-11ea-9aab-261b2a2b1f0b.png)

The ui may mislead user for it looks like a multiple select. If indeed you need a multiple select, tagRender works
 well.

If you do need to implement this. create a new prop for example `labelNode` for each select option and use `optionLabelProp="labelNode"`
