### ISSUE TITLE
I don't know how to set the array object

### ISSUE THREAD

**Issue by lxf001** [ant-design/ant-design#26077]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-4sz8b?file=/index.js)

### Steps to reproduce
Initialization and setup

### What is expected?
Initialization and setting values

### What is actually happening?
Cannot initialize and set values

| Environment | Info |
|---|---|
| antd | undefined |
| React | latest |
| System | win |
| Browser | latest |

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/89611829-bb832800-d8b0-11ea-861f-c57dfc81dbf4.png)

**Comment by zombieJ** [comment]
Pls follow official example: https://ant.design/components/form-cn/#components-form-demo-dynamic-form-item

You can use `initialValues` to set the Form field value and Form.List will auto fill the fields data.

**Comment by lxf001** [comment]
no no

**Comment by lxf001** [comment]
This number will change, through form.setFiledsValue () set value

**Comment by lxf001** [comment]
Not the initial setting value








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午2:27
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"刘新风"<lxf_dream@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] I don't know how to set the array object (#26077)





 
Closed #26077.

**Comment by zombieJ** [comment]
`setFieldsValue` is all the same.

**Comment by lxf001** [comment]
Take a simple example










------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午2:45
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"刘新风"<lxf_dream@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] I don't know how to set the array object (#26077)





 
setFieldsValue is all the same.

**Comment by lxf001** [comment]
Hey, please give me some advice







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "二货机器人"<notifications@github.com&gt;; 
发送时间: 2020年8月7日(星期五) 下午2:45
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "刘新风"<lxf_dream@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] I don&#39;t know how to set the array object (#26077)





 
setFieldsValue is all the same.
 
&mdash;

**Comment by 07akioni** [comment]
use `initialValues` to set initial values and use `setFieldsValue` to set new values.

**Comment by lxf001** [comment]
The key is how you set up this kind of array object multi-level nesting







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "07akioni"<notifications@github.com&gt;; 
发送时间: 2020年8月9日(星期天) 晚上10:39
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "刘新风"<lxf_dream@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] I don&#39;t know how to set the array object (#26077)





 
use initialValues to set initial values and use setFieldsValue to set new values.

**Comment by 07akioni** [comment]
follow xrkffgg's instruction

**Comment by lxf001** [comment]
Set a new value through 'setfieldsvalue'. The submitted value is still in this nested array object format.

**Comment by lxf001** [comment]
We all know how to set the initial value. I mean new values need to be set, and they need to be changed.

**Comment by lxf001** [comment]
Still need to keep array object format for submission

**Comment by 07akioni** [comment]
try set name path for field properly

**Comment by vedovato** [comment]
https://codesandbox.io/s/quirky-brook-ou9j9?file=/src/App.js

**Comment by lxf001** [comment]
forget it。 I don't know. You don't understand. In the recursive format, set the value through the form







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Andrei Vedovato"<notifications@github.com&gt;; 
发送时间: 2020年9月1日(星期二) 上午9:37
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "刘新风"<lxf_dream@qq.com&gt;; "Manual"<manual@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] I don&#39;t know how to set the array object (#26077)





 
https://codesandbox.io/s/quirky-brook-ou9j9?file=/src/App.js
 
&mdash;
