### ISSUE TITLE
Add formatter to DatePicker

### ISSUE THREAD

**Issue by fabientownsend** [ant-design/ant-design#26070]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Some users are writing numbers in the input like "12121999" expecting to have "12/12/1999" instead of click on the date picker, it could be interesting to have a props similar to [InputNumber](https://github.com/ant-design/ant-design/blob/master/components/input-number/index.tsx#L26) where the developer can format the input typed by the user. 

### What does the proposed API look like?
``` javascript 
function addSlashToDate(date: string): string {
   return date.replace(/yourRegex/, '/')
}
...
<DatePicker
  format="MM/DD/YYYY"
  formatter={addSlashToDate}
/>
````

**Comment by zombieJ** [comment]
Why not config format to `DDMMYYYY`?

**Comment by fabientownsend** [comment]
The `format` part only impact if the users click on the date but not if you type directly the date in the input as a result the UI display the date in two different formatting.

By clicking you would have the date display as `08/07/2020` if you set `format="MM/DD/YYYY"` but it would display `08072020` if a user type the date without the `/`, that's where it would be interesting to add a formatter option to automatically add the separators when the users don't do it.

**Comment by zombieJ** [comment]
Still not get it. When exist multiple format, display will alway use first one: https://codesandbox.io/s/sleepy-http-hldf6?file=/index.js

**Comment by fabientownsend** [comment]
Let me explain it differently. In a scenario where I don't use the mouse and only the keyboard and don't use the "pop up" of the DatePicker - when I type the following number in the input section with my keyboard "06062000" I would like it to appear like "06/06/2000".

A similar example with the InputNumber: https://codesandbox.io/s/ogrue
In the first input, if the user enters "2000" it appears as "2,000"

**Comment by zombieJ** [comment]
Date is different with InputNumber since InputNumber can always stop immediately since any number can be a validate number. But Date string must be a unique content when typed. That's why we offer format with array to be a post update instead.

**Comment by fabientownsend** [comment]
Right, that make all sense. I guess it could still be an option to have the option of also using an immediate formatting when the date is typed, but it may not worth the effort. The issue can be closed if it's the case

Thanks for your answer @zombieJ 👍
