### ISSUE TITLE
input number needs a place holder to override the default value 

### ISSUE THREAD

**Issue by Ash000es** [ant-design/ant-design#26080]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
information is clear to the user about the type of information he is selecting, for example two input components being used  to select the number of rooms and number of guests a person needs to book. at the moment you can't add a palce holder to distinguish which is which specially when other components along side the number selector have a place holder like dates selection  

### What does the proposed API look like?
same as it is now, just the default number doesn't have to be what is shown to the user, the placeholder value can switch to default number when the user hover over the component

**Comment by afc163** [comment]
There is placeholder prop like Input: https://codesandbox.io/s/6q4il?file=/index.js

**Comment by Ash000es** [comment]
no, there is default number prop and you can't take it away or replace it with a string

**Comment by afc163** [comment]
I cannot understand what you describe.

**Comment by Ash000es** [comment]
in the example you showed me in sand box. the value the user sees is 3 which is the default number prop. I am asking to have a place holder prop to be able to have a string that describes what is it I am selecting. so what the user should see is for example ''number of Adult'' not number 3. you could switch to default number on hovering or not but the user needs to understand what is he selecting ? number of what?

**Comment by afc163** [comment]
Could you take a image or alternative demo?

**Comment by Ash000es** [comment]
<img width="590" alt="Screenshot 2020-08-07 at 10 08 28" src="https://user-images.githubusercontent.com/57522888/89624040-f3c93d00-d895-11ea-82e7-d414d0334fe7.png">
This is how it should look like

**Comment by Ash000es** [comment]
<img width="590" alt="Screenshot 2020-08-07 at 10 09 20" src="https://user-images.githubusercontent.com/57522888/89624113-10fe0b80-d896-11ea-89eb-170cf83e8f38.png">
this is how it is now, no placeholder for text allowed

**Comment by afc163** [comment]
Did you mean https://github.com/ant-design/ant-design/issues/23201 or #14284 ?

**Comment by Ash000es** [comment]
yes like 14284, however wrapping the input into a span is not a solution  cause the prefix value is outside the input number on top while it should be allowed next to the number inside the box just like the screen shot above. 
<img width="126" alt="Screenshot 2020-08-07 at 11 23 38" src="https://user-images.githubusercontent.com/57522888/89631007-72c37300-d8a0-11ea-8687-0d6fb7928d72.png">

**Comment by afc163** [comment]
Trace in #14284, we will support `prefix` and `suffix` of InputNumber soon.

**Comment by afc163** [comment]
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
