### ISSUE TITLE
使用prefixCls="antmain"，less编译，结果出现menu组件样式问题，已经解决，希望写法上更加严谨

### ISSUE THREAD

**Issue by zjscy666** [ant-design/ant-design#26084]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
![企业微信截图_15967860522630](https://user-images.githubusercontent.com/22449281/89622672-f8a5e500-d8c5-11ea-95d1-5a378f374b12.png)

&-vertical-right&-sub {
    min-width: 160px;
    max-height: calc(100vh - 100px);
    padding: 0;
    overflow: hidden;
    border-right: 0;
    transform-origin: 0 0;
源码上 es/menu/index.less 下面的calc写法不够严谨，二次编译导致出问题，希望修改成max-height: ~'calc(100vh - 100px)';

### What does the proposed API look like?
不然用less编译修改ant前缀的时候，会出现计算问题

**Comment by afc163** [comment]
建议将 less 版本升级到 3.x，2.x 识别不了 calc。

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/23125#issuecomment-611971690
https://github.com/ant-design/ant-design/issues/24891
https://github.com/ant-design/ant-design/issues/23301
https://github.com/ant-design/ant-design/issues/23531

**Comment by zjscy666** [comment]
"less": "^3.11.3",
    "less-loader": "5.0.0",

**Comment by afc163** [comment]
@zjscy666 能提供一个最小重现看看么？
