### ISSUE TITLE
Content and border of sortable table row not visible when dragging inside modal.

### ISSUE THREAD

**Issue by christianandrei** [ant-design/ant-design#26096]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-bartik-ymion?file=/index.js)

### Steps to reproduce
try to drag

### What is expected?
content and border of row must be visible when dragging 

### What is actually happening?
content and border of row not visible when dragging

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | chrome 84.0.4147.105 |

---
this happens inside a modal

**Comment by 07akioni** [comment]
```
.row-dragging {
  background: #fafafa;
  border: 1px solid #ccc;
  add this line >>> z-index: 1000;
}
```

**Comment by MINGLIANG98** [comment]
真是醉了 999都不行 demo也不改一下
