### ISSUE TITLE
Mentions press Enter to report an error

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#26097]
### Reproduction link
[https://ant.design/components/mentions-cn/#components-mentions-demo-basic](https://ant.design/components/mentions-cn/#components-mentions-demo-basic)

### Steps to reproduce
1. Enter @ in the input box
2. Enter some other until the result is empty, showing no data
3. Press `Enter` key now
4. Console error
5. Press again, error again

### What is actually happening?

![image](https://user-images.githubusercontent.com/29775873/89711085-9549af00-d9ba-11ea-880d-032bd61f79ff.png)

```
Uncaught TypeError: Cannot read property 'value' of undefined
```

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | The latest |
| System | win10 |
| Browser | chrome |

**Comment by xrkffgg** [comment]
@Kermit-Xuan 有空瞅瞅？

**Comment by Kermit-Xuan** [comment]
> @Kermit-Xuan 有空瞅瞅？

好，分给我

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/mentions/pull/30
