### ISSUE TITLE
Incorrect DatePicker dropdown shown

### ISSUE THREAD

**Issue by rchavik** [ant-design/ant-design#26093]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker/#components-date-picker-demo-switchable](https://ant.design/components/date-picker/#components-date-picker-demo-switchable)

### Steps to reproduce
1. Choose Quarter from dropdown, select a quarter from the datepicker calendar.
2. Choose either "Date" or "Week" or "Month", then try to select a date from the datepicker calendar (It still shows the the old Quarter style calendar).

### What is expected?
After changing the picker type, the datepicker calendar should be automatically reflected correctly

### What is actually happening?
It is showing a previously selected picker type.

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | Ubuntu 20.04 Desktop |
| Browser | Firefox 79 |

**Comment by rchavik** [comment]
![image](https://user-images.githubusercontent.com/39490/89701088-1cb50500-d95e-11ea-952b-e15496a75839.png)

**Comment by 07akioni** [comment]
fixed in latest rc-picker

**Comment by afc163** [comment]
It is not fixed, antd don't dep on rc-picker@2.0.3 now.

**Comment by 07akioni** [comment]
> It is not fixed, none version of antd deps on rc-picker@2.0.3 now.

should we update rc-picker to 2.x?

**Comment by afc163** [comment]
Sure.

**Comment by afc163** [comment]
```
+ rc-picker@1.15.2
```
