### ISSUE TITLE
Antd instruction for form modal contain Typescript error

### ISSUE THREAD

**Issue by mpiorowski** [ant-design/ant-design#26091]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/mpiorowski/bills-management/blob/feature/bills/client/src/components/bills/BillForm.tsx](https://github.com/mpiorowski/bills-management/blob/feature/bills/client/src/components/bills/BillForm.tsx)

### Steps to reproduce
Follow the instuction for form modal on antd page and use typescript code.

### What is expected?
Working solution

### What is actually happening?
Inside modal onOk func the form.then returning values are of type Store ([name: string]: any). Two lines below it we try to pass it to a func that accept only Values type (Prop: string). This two types cannot match, so typescript throw error here.

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | Ubuntu 20 |
| Browser | Mozilla |

---
I've looked for a valid solution, maybe some type of casting params, but couldn't find anything :/ Maybe You guys know of a magic solution here.

**Comment by afc163** [comment]
I don't find any TypeScript error in your repo, please provide minimal reproduce (codesandbox for best).

**Comment by mpiorowski** [comment]
Sorry, i accidently changed my code and push it :). This is a copy paste code from Your page, and here we can see the issue :).

https://codesandbox.io/s/antd-reproduction-template-l4ijk?file=/index.tsx

Line 34, after everything loads.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-o15y5

https://github.com/ant-design/ant-design/pull/22755
