### ISSUE TITLE
Tabs destroyInactiveTabPane Documentation is missing

### ISSUE THREAD

**Issue by StallionV** [ant-design/ant-design#26092]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
[react-components/tabs](https://github.com/react-component/tabs#tabs) has a prop called `destroyInactiveTabPane` which ensures all the other tabs are destroyed when we select a different tab. This is a good feature to have and something that Ant Design already supports, but it is not documented.

Currently by default, once all tabs are rendered when you switch tabs they are not re-rendered.
Some of the tabs may have API calls and content that has to be refreshed and so `destroyInactiveTabPane` is a good option to have.

### What does the proposed API look like?
Update Documentation to mention about `destroyInactiveTabPane`.

**Comment by afc163** [comment]
<img width="450" alt="image" src="https://user-images.githubusercontent.com/507615/89707187-82c17c80-d99e-11ea-9faf-82f441804353.png">

**Comment by StallionV** [comment]
@afc163 wanting to know if the documentation was updated since this is already closed. I don’t see any related pull requests so.

**Comment by afc163** [comment]
PR welcome
