### ISSUE TITLE
Pagination的一些问题与建议

### ISSUE THREAD

**Issue by shenlm203** [ant-design/ant-design#261]
你好，我的想法有如下几点：

**一个优化建议**
Pagination的quick jumper输入input当输入的数值大于最大分页时，能够给出优化
如果输入页码大于最大页码，则默认跳到最后一页
其他用户输入错误值，则默认跳到第一页

** 增加事件**
如果用户在quick jumper 的input中输入的时候，能够给出事件回调，方便获取用户输入后，给出一些回调。比如如果输入错误，则input外层给个红色的border提示，当然这点可以组件内部后期完善。

**问题**
目前如果页码过多，则会隐藏页码，这是一个非常贴心的设计。
但当用户顺序从第一页点到第五页的时候，第6页是隐藏的,这对用户来说有些突兀，且用户要点击`>>`然后才能点击页码6， 增加了用户的操作成本。是否可以判断用户在第5页的时候后续页码就自动展开？

**Comment by ibigbug** [comment]
非常感谢反馈 :)

会结合提到的一些点进行优化。

**Comment by afc163** [comment]
感觉 1 和 3 可以先优化下。

**Comment by ibigbug** [comment]
1. 当用户输入大于最大分页时，默认跳到最后一页; 输入错误时，屏蔽错误输入，并保持当前页
2. 事件，再考虑下，红框就不需要了吧，因为这个 input 不在表单里面，只做页码输入
3. 这块体验需要重新优化一下，让翻页流程更加流畅

**Comment by shenlm203** [comment]
我们团队正在尝试使用ant，你们的组件很有意义，也很高效！看好你们，期待0.9.0，加油！

**Comment by ibigbug** [comment]
可以试用 `rc-pagination@1.1.13` 看看还有没有再需要继续改进的地方。
