### ISSUE TITLE
Table onShowSizeChange event is triggered three times

### ISSUE THREAD

**Issue by bibiehy** [ant-design/ant-design#26100]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-lederberg-tqqhv?file=/demo.tsx)

### Steps to reproduce
20 items per page are displayed by default, please open the console.

step1:  please turn to the third page, you will see the message 'is triggered'.

step2: click the event '50/page', you will see three messages again. this shows that three requests were made.

### What is expected?
when i click the event '50/page', i expect to trigger a request.

### What is actually happening?
it's three requests were triggered.

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | google - 83.0.4103.61 |

**Comment by zhangchen915** [comment]
onShowSizeChange triggered twice.
You should use table onChange to trigger a request.

**Comment by bibiehy** [comment]
> onShowSizeChange triggered twice.
> You should use table onChange to trigger a request.

I don't understand.
onChange is the changed page, onShowSizeChange is the changed pageSize, if the page number is three, now, I go to execute the onShowSizeChange event, not only 3 requests but the pageSize becomes 1.

**Comment by dennismorello** [comment]
I have the same issue, the `onShowSizeChange` callback is triggered twice.

**Comment by ISBN9527** [comment]
i have the same question.

**Comment by kliakos** [comment]
> > onShowSizeChange triggered twice.
> > You should use table onChange to trigger a request.
> 
> I don't understand.
> onChange is the changed page, onShowSizeChange is the changed pageSize, if the page number is three, now, I go to execute the onShowSizeChange event, not only 3 requests but the pageSize becomes 1.

I tested this and it turns out that `onChange` is also triggered by the pageSize change eventm in contrary to what the documentation says. So a workaround would be to set only the `onChange` instead of both `onChange` and `onShowSizeChange`. However this looks like a regression and will probably be fixed, so I am not sure if we should jump into doing the workaround, which will stop working after the issue is fixed.

**Comment by dennismorello** [comment]
> I tested this and it turns out that `onChange` is also triggered by the pageSize change eventm in contrary to what the documentation says. So a workaround would be to set only the `onChange` instead of both `onChange` and `onShowSizeChange`. However this looks like a regression and will probably be fixed, so I am not sure if we should jump into doing the workaround, which will stop working after the issue is fixed.

Yes, I observed the same. This is clearly a regression and so should be handled; we look forward for a fix 🤞🏻

**Comment by BaoXianPower** [comment]
I have the same question. what should I do?

**Comment by BaoXianPower** [comment]
That could be the reason
```javascript
// rc-pagination 
// https://github.com/react-component/pagination/blob/master/src/Pagination.jsx 

this.props.onShowSizeChange(current, size);

if ('onChange' in this.props && this.props.onChange) {
      this.props.onChange(current, size);
}
```

**Comment by rixcian** [comment]
I had the same issue. I used `onChange` event instead of the `onShowSizeChange`, because it's not executed twice but only once so (in my case) it was dispatching action twice with no reason (I'm using it with redux). 

In the `onChange` event I'm only checking if the pageSize is different from previous value (if it's true, then I'm dispatching redux action). 


```javascript
...

// I'm getting defaultPageSize from redux & then use it in Table component
const dispatch = useDispatch();
const { defaultPageSize: reduxPageSize } = useSelector((state: RootState) => state.settings);
const [pageSize, setPageSize] = useState(reduxPageSize);


// On `reduxPageSize` variable change, check if it's different from value saved in state
useEffect(() => {
  if (pageSize !== reduxPageSize) {
    setPageSize(reduxPageSize);
  }
}, [reduxPageSize]);

...

return (
<Table<DataTable>
  columns={tableColumns}
  dataSource={formattedOsVersionsList}
  pagination={{
    position: ['topRight', 'bottomRight'],
    defaultPageSize: pageSize,
    onChange: (_, size) =>
        size && size !== pageSize && dispatch(defaultPageSize(size))
  }}
/>
)
```

**Comment by kliakos** [comment]
Is this really fixed? I can see that changing the pageSize still triggers the onChange event, although it shoudn't.

Repro: https://codesandbox.io/s/changer-antd492-forked-itqh3

**Comment by jippy89** [comment]
This still happens in `antd@^5.17.0` with `react@^18.2.0`? Solved it by only using `onChange` events.
I was looking to get the `pageSize` to zero whenever the size change, but well if this is the only way it can work.

```js
onChange(pageNumber, pageSize) {
  // My logic
  onPaginationChange({
    page: pageNumber - 1,
    size: pageSize,
  });
}
```
