### ISSUE TITLE
use Modal method to fill responsive component in content prop without view update

### ISSUE THREAD

**Issue by Indomi** [ant-design/ant-design#26101]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-morning-9wubf?file=/src/App.js)

### Steps to reproduce
1. use Modal method to create a window
2. fill a componet like Input / Select which define value and onChange
3. input or select value, view with Input Changed, but can not changed in Select

### What is expected?
select any option with view rerender

### What is actually happening?
value of select changed, but view not

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.0 |
| System | macos10.15.5  |
| Browser | chrome84.0.4147.105 |

**Comment by afc163** [comment]
https://ant.design/components/modal/#Why-I-can-not-access-context,-redux-in-Modal.xxx

**Comment by Indomi** [comment]
> https://ant.design/components/modal/#Why-I-can-not-access-context,-redux-in-Modal.xxx

打扰啦，创建实例注入到组件中我也试过，但是依然没有解决问题，可以看下codesandbox的demo

**Comment by zombieJ** [comment]
`modal.info` 创建实例是一次性的，之后 setState 更新不会对弹出的 Modal 触发额外的渲染。如果希望 modal.info 被外层影响，创建一个 context 传递一下数据更新即可： https://codesandbox.io/s/eloquent-fermat-v132b?file=/src/App.js
