### ISSUE TITLE
Radio 点击事件捕获不到onclick事件

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2610]
antd版本1.6.4
<Radio value="Y" key="primaryInd" onClick={this.checkRadio} >主要</Radio> 
Radio点击的时候，捕获不到onclick事件

**Comment by RaoHai** [comment]
Radio 不支持 onClick 事件呀。。

单选框用 onChange 就好了。有什么需求是需要用到 onClick 的呢？

**Comment by wuhaih** [comment]
之前的版本支持的，现在升级了不支持了，刚测试用onChange是可以的 ，onClick 事件也是最基本的为什么不放开

**Comment by RaoHai** [comment]
https://github.com/react-component/checkbox/commit/e7d4cddc6724ff541581627a811600bddbe1ce1e#diff-07bc8878edb787bfd00405b74d0a7300L87

@shepherdwind 这个 commit 有什么深意么……

**Comment by afc163** [comment]
https://github.com/react-component/checkbox/pull/14

**Comment by RaoHai** [comment]
@afc163 那么 Radio 和 Checkbox 要不要支持 onClick 呢。

**Comment by afc163** [comment]
可以针对性加一下。

**Comment by wuhaih** [comment]
我觉得最好放开吧，升级了导致了很多用了onClick无效了

**Comment by afc163** [comment]
不过正常的值获取确实应该用 onChange ，onClick 应该只用于一些特殊的需求。

**Comment by wuhaih** [comment]
不冲突吧，它也能获取对象值
