### ISSUE TITLE
官网资源下载中提供的iconFont，下载解压后的iconfont.svg用Sketch和AI打开均无内容

### ISSUE THREAD

**Issue by iandukov** [ant-design/ant-design#2611]
![25906891-98db-40d4-abd6-10b3f3e26fb5](https://cloud.githubusercontent.com/assets/7217782/17389032/158e2c4c-5a33-11e6-9987-aadbc95c40b0.png)

**Comment by afc163** [comment]
这是 http://iconfont.cn/ 用于 icon font 生成的文件，并非正常的 svg。

你可以试试：http://leungwensen.github.io/svg-icon/#ant

**Comment by iandukov** [comment]
感谢
http://www.iconfont.cn/collections/show/790
iconfont上的图标和AntD官网的一些图标有一些差异，比如delete图标一胖一瘦

**Comment by afc163** [comment]
你居然发现了这个，我都不知道有这个。。。

这个应该是新版的图标，antd 里还未更新。
