### ISSUE TITLE
ESLint error react/display-name on Table's ColumnsType with custom render

### ISSUE THREAD

**Issue by gaara4896** [ant-design/ant-design#26111]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-k252y)

### Steps to reproduce
1. Set eslintrc to following configuration

```
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'plugin:jsx-a11y/recommended',
    // Prettier plugin and recommended rules
    'prettier/@typescript-eslint',
    'plugin:prettier/recommended',
  ],
```

2. Create a column objects for table
3. Run `eslint . --ext .ts,.tsx`

```
yarn run v1.17.3
$ eslint --fix . --ext .ts,.tsx,.js,.jsx

/home/user/my-project/components/ComponentTable.tsx
  32:13  error  Component definition is missing display name  react/display-name

✖ 1 problem (1 error, 0 warnings)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### What is expected?
ColumnsType should include displayName as optional props

### What is actually happening?
ColumnsType unable to set display name as props

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | next 9.4.4 |
| System | Linux 5.7.12-arch1-1 |
| Browser | Chromium Version 84.0.4147.105 (Official Build) Arch Linux (64-bit) |

**Comment by afc163** [comment]
It is not a antd issue.

**Comment by wapenshaw** [comment]
To anyone coming here with the same issue, just disable eslint for that line if you are writing a small render function for example 

```tsx
// eslint-disable-next-line react/display-name
render: (date) => moment(date).format('MMMM ddd yyy - HH mm ss'),
```

If you have  a bigger render function do something like 

```tsx
render: editColumnRender,

// and write a function called editColumnRender like so 

const editColumnRender = (value: any, record: RecordType) => {
// returns any jsx
}

```
