### ISSUE TITLE
Select下拉框显示空白

### ISSUE THREAD

**Issue by mayiliang** [ant-design/ant-design#26116]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ancient-snowflake-yiu6u)

### Steps to reproduce
点击下拉框选择最后一个选项，然后再点击下拉框

### What is expected?
下拉框正常显示
![image](https://user-images.githubusercontent.com/37889491/89771083-576f9680-db32-11ea-8e6e-1927f0473c9f.png)

### What is actually happening?
下拉框显示空白
![image](https://user-images.githubusercontent.com/37889491/89771129-69e9d000-db32-11ea-9a82-c45b4d33a02a.png)

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | window 10 |
| Browser | chrome (84.0.4147.105) |

**Comment by susiwen8** [comment]
好像和 virtual list 有关

**Comment by 07akioni** [comment]
you can use `virtual={false}` as a temporal workaround

**Comment by mayiliang** [comment]
> you can use `virtual={false}` as a temporal workaround

Thanks. It worked.

**Comment by afc163** [comment]
It is not resolved until rc-virtual-list@2.x: https://github.com/react-component/virtual-list/pull/41

cc @zombieJ

**Comment by zombieJ** [comment]
patch 在 `rc-select@11.1.x` 上，master 是 `11.0.x`，试了一下已经好了。cherry picker 发现还有 css-motion 相关内容不太好剥离。 @chenshuai2144 正好也想给 Descriptions 那个发 minor，要不然这周直接发 minor 吧。

**Comment by afc163** [comment]
rc-tree-select 还没升，master 有个 devDeps 也没升。

**Comment by zombieJ** [comment]
可以 feature 里都升一下

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/25907

**Comment by zXuff** [comment]
1

**Comment by zXuff** [comment]
4.6.1还是不好使

**Comment by zombieJ** [comment]
@zXuff 感谢反馈，已修复

**Comment by wingsico** [comment]
4.10.0 还是存在这个情况

**Comment by yoyo837** [comment]
开个新issue.

**Comment by wingsico** [comment]
> 开个新issue.

清了 .lock 重装一遍好了..

**Comment by shiwanjun1995** [comment]
select组件能不能加一个下拉展示的条数，现在是8条，这个如何修改，如果我想要5条、10条呢？貌似修改高度不行

**Comment by shiwanjun1995** [comment]
> select
@zombieJ

**Comment by shiwanjun1995** [comment]
> select组件能不能加一个下拉展示的条数，现在是8条，这个如何修改，如果我想要5条、10条呢？貌似修改高度不行

等了噶久，能不能实现这个功能，也木有人回复，还是自己补充下

`
方法一：限制是只能8条以内
dropdownStyle: { maxHeight: `${32*x+4*2}px` }
这里的x为条数，后面的值是上下的padding，但是经过测试，这里的x最多只能调整到8，
方法二：
  .rc-virtual-list-holder {
    max-height: 320px !important; // 32*x，这里是展示10条
    // max-height: fit-content !important;
  }
`
