### ISSUE TITLE
Table什么时候可以实现无限加载数据，目前只要table数据一多整个页面都会卡

### ISSUE THREAD

**Issue by Mathround** [ant-design/ant-design#26117]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在前端已经有做了分页情况下，后台一次性返回三四百条数据时只要整个页面有操作都会很卡

### What does the proposed API look like?
希望Table可以实现无限加载数据，比如就算出现几万条数据都不带卡的

**Comment by Kermit-Xuan** [comment]
参考一下虚拟列表 https://ant.design/components/table-cn/#components-table-demo-virtual-list

**Comment by Mathround** [comment]
> 参考一下虚拟列表 https://ant.design/components/table-cn/#components-table-demo-virtual-list

好吧，才发现最新版已经有这功能了，我一直用3.26版本的

**Comment by Mathround** [comment]
> 参考一下虚拟列表 https://ant.design/components/table-cn/#components-table-demo-virtual-list

这个虚拟列表的貌似只能纯粹展示大量的数据而没有其它的交互，也太鸡肋了吧，我想把rowSelection属性整合进去直接就给报错了，有其它方法可以整合进去吗？还是不支持呢

**Comment by azx1985** [comment]
用虚拟列表的话，嵌套子表格好像也不能一起使用吧
