### ISSUE TITLE
FormItem、Checkbox、Row/Col 同时使用时，布局会出现奇怪的问题

### ISSUE THREAD

**Issue by rxliuli** [ant-design/ant-design#26113]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-leftpad-o53xs?file=/index.js)

### Steps to reproduce
参考上面的链接

### What is expected?
Checkbox 不仅在水平方向上对其，还在垂直方向上对其。

### What is actually happening?
在垂直方向上有奇怪的空白

| Environment | Info |
|---|---|
| antd | 4.2.5 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome 84.0.4147.105 |

![image](https://user-images.githubusercontent.com/24560368/89757187-20d85280-db17-11ea-9dc1-d32c369c534d.png)

**Comment by afc163** [comment]
Form.Item 之间有默认 margin。
