### ISSUE TITLE
使用两个DatePicker不能选择同一天

### ISSUE THREAD

**Issue by jie-L** [ant-design/ant-design#26110]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/date-picker-cn/](https://3x.ant.design/components/date-picker-cn/)

### Steps to reproduce
两个DatePicker实现开始~结束时间选择     使用disabledDate控制选择范围         先选择开始时间为8月10号    结束时间可以选择8月10号         先选择结束时间为8月10号     开始时间不能选择8月10号只能9号

### What is expected?
先选择结束时间为某一天    选择开始时间是也可以选择同一天    需要使用disabledDate

### What is actually happening?
先选择结束时间为某一天    选择开始时间不能选择同一天

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 任何版本 |
| System | widows |
| Browser | google |

---
import { DatePicker } from 'antd';

class DateRange extends React.Component {
  state = {
    startValue: null,
    endValue: null,
    endOpen: false,
  };

  disabledStartDate = startValue => {
    const { endValue } = this.state;
    if (!startValue || !endValue) {
      return false;
    }
    return startValue.valueOf() > endValue.valueOf();
  };

  disabledEndDate = endValue => {
    const { startValue } = this.state;
    if (!endValue || !startValue) {
      return false;
    }
    return endValue.valueOf() <= startValue.valueOf();
  };

  onChange = (field, value) => {
    this.setState({
      [field]: value,
    });
  };

  onStartChange = value => {
    this.onChange('startValue', value);
  };

  onEndChange = value => {
    this.onChange('endValue', value);
  };

  handleStartOpenChange = open => {
    if (!open) {
      this.setState({ endOpen: true });
    }
  };

  handleEndOpenChange = open => {
    this.setState({ endOpen: open });
  };

  render() {
    const { startValue, endValue, endOpen } = this.state;
    return (
      <div>
        <DatePicker
          disabledDate={this.disabledStartDate}
          format="YYYY-MM-DD"
          value={startValue}
          placeholder="Start"
          onChange={this.onStartChange}
          onOpenChange={this.handleStartOpenChange}
        />
        <DatePicker
          disabledDate={this.disabledEndDate}
          format="YYYY-MM-DD"
          value={endValue}
          placeholder="End"
          onChange={this.onEndChange}
          open={endOpen}
          onOpenChange={this.handleEndOpenChange}
        />
      </div>
    );
  }
}

ReactDOM.render(<DateRange />, mountNode);

**Comment by xrkffgg** [comment]
3.x 已经不维护了，请更新 4.x 使用。

**Comment by jie-L** [comment]
决赛圈了    不希望更新

**Comment by jie-L** [comment]
> 3.x已经不维护了，请更新4.x使用。

谢谢     决赛圈了    不希望更新
