### ISSUE TITLE
Antd 4 Form and DatePicker Functional Component Error

### ISSUE THREAD

**Issue by christopher97** [ant-design/ant-design#26120]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/christopher97/pen/PoNqVVv?editors=0010](https://codepen.io/christopher97/pen/PoNqVVv?editors=0010)

### Steps to reproduce
Simply run the codepen, although it might show error "unexpected token <", but this is as close as it is to the actual code

### What is expected?
Datepicker will show up fine inside a functional component

### What is actually happening?
Every other input component shows up just fine, error happens when I used DatePicker.
React printed these to the console
```
Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.
The above error occurred in the <InnerPicker> component
```

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | Ubuntu 18.04.4 LTS |
| Browser | Google Chrome Version 84.0.4147.105 (Official Build) (64-bit) |

**Comment by christopher97** [comment]
Thanks for your reply, I tried creating a new repo to reproduce the error and copied the src folder from my old repo to the new repo, and it ran well. So I decided to delete the package-lock.json and node_modules folder, ran npm install again and it worked!

**Comment by ssdeniss** [comment]
Why i cant use defaultValue inside in DatePicker.RangePicker?

**Comment by ssdeniss** [comment]
@ant-design-bot
