### ISSUE TITLE
input number text alignment for InputNumber component

### ISSUE THREAD

**Issue by ruegenaschenbrenner** [ant-design/ant-design#26123]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
text alignment for number input to feature a prop that aligns the text to the right and perhaps moves the increment buttons to the left

### What does the proposed API look like?
I guess the prop could be something like

`align="right"`

then simply update the css class

Note: https://ant.design/docs/spec/alignment#Numbers-Alignment

**Comment by xrkffgg** [comment]
Like RTL?

**Comment by dengfuping** [comment]
- @ruegenaschenbrenner [RTL](https://ant.design/components/config-provider-cn/#components-config-provider-demo-direction) of `ConfigProvider` component maybe what you want.
![image](https://user-images.githubusercontent.com/14918822/89879224-302dcd80-dbf5-11ea-96b7-f566a59c86e4.png)
