### ISSUE TITLE
Provide Typography.Text type=success?

### ISSUE THREAD

**Issue by breeswish** [ant-design/ant-design#26127]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now `type` can be `secondary`, `warning` and `danger`. It would be nice to provide `success` as well, so that a colored icon can be easily implemented via `<Typography.Text type="success"><CheckCircleFilled /></Topography.Text>`, instead of defining a class for it every time.

### What does the proposed API look like?
Add `type=success` to `<Topography.Text>`

**Comment by llwslc** [comment]
title typo
Typograph.Text -> Typography.Text
