### ISSUE TITLE
Table pagination should not be hidden when the last record on the last page is deleted

### ISSUE THREAD

**Issue by QoVoQ** [ant-design/ant-design#26126]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-o7yd4?file=/index.js)

### Steps to reproduce
i) go to the last page (page 3)

ii) click "delete"

### What is expected?
Message of "No data" should be displayed, and pagination should be visible as well.

Since there is still 2 records left(3 records in total, 1 record is removed), users should be able to go to previous pages and check remaining records.

### What is actually happening?
Message of "No data" is displayed, but pagination is hidden

| Environment | Info |
|---|---|
| antd | 4.5.2 |
| React | 16.13.1 |
| System | macOS mojave 10.14.6  |
| Browser | Version 84.0.4147.105 (Official Build) (64-bit) |

**Comment by QoVoQ** [comment]
This bug only happens when using backend pagination, meaning manual manage property `pagination.total`

**Comment by zhangchen915** [comment]
Same with #25836
