### ISSUE TITLE
Allow Upload's beforeUpload prop to take an array of files when 'multiple' is set to true.

### ISSUE THREAD

**Issue by jonecole** [ant-design/ant-design#26121]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, when multiple files are added at the same time, beforeUpload fires once for each file. Since there is no way to control when the function fires, they often fire only a few milliseconds apart, making debouncing with setState for a custom request impossible. If beforeUpload could take an array of files instead, then multiple files uploaded at the same time would only cause beforeUpload to fire once. This would allow for operations to be done on multiple files at once, and allow for a function to be called at the end of beforeUpload without having to attempt to debounce.

### What does the proposed API look like?
Currently, beforeUpload looks like this:  
&nbsp;&nbsp;&nbsp;&nbsp;```beforeUpload: (file, fileList) => { . . . }```  
With the proposed change it could look like:  
&nbsp;&nbsp;&nbsp;&nbsp;```beforeUpload: ([file], fileList) => { . . . }```

**Comment by jonecole** [comment]
This may be a duplicate of #8579, although it doesn't look like that one was ever resolved.

**Comment by afc163** [comment]
We cannot change this because it will be a break change.

**Comment by sahilverma817** [comment]
Well, you can do it like below:

```
beforeUpload: (file, fileList) => {
			if (fileList.length > 0 && fileList[fileList.length - 1] === file) {
				Do something()
			}
			return false;
		},                 
```
