### ISSUE TITLE
https://avatars3.githubusercontent.com/u/35128?s=40&v=4 访问不了

### ISSUE THREAD

**Issue by jiangyanghe** [ant-design/ant-design#26131]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://avatars3.githubusercontent.com/u/35128?s=40&v=4 ](https://avatars3.githubusercontent.com/u/35128?s=40&v=4 )

### Steps to reproduce
随边打开页面，加载很慢 发现 是avatars1.githubusercontent.com avatars2.githubusercontent.com avatars3.githubusercontent.com访问不了

### What is expected?
可以快速访问

### What is actually happening?
avatars3.githubusercontent.com 加载不出

| Environment | Info |
|---|---|
| antd | undefined |
| React | react |
| System | mac |
| Browser | 谷歌 |

---
我链接了VPN 可以翻墙

**Comment by yoyo837** [comment]
这不是antd的问题，是大陆网络环境的问题。
