### ISSUE TITLE
Table组件rowSelection设置点击行无法选中

### ISSUE THREAD

**Issue by dumbbell0720** [ant-design/ant-design#26132]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-chatelet-o7bwf?file=/index.js)

### Steps to reproduce
只有点击复选框才能选中，点击行无法选中

### What is expected?
点击行也能选中

### What is actually happening?
只有点击复选框才能选中，点击行无法选中

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by afc163** [comment]
https://ant.design/components/table-cn/#components-table-demo-row-selection

<img width="724" alt="image" src="https://user-images.githubusercontent.com/507615/89874649-bb579500-dbee-11ea-8ca2-46af0d506f84.png">

**Comment by dumbbell0720** [comment]
用的正是demo给的代码，只不过把data中的key改成了id, 就不生效了

**Comment by afc163** [comment]
请设置 rowKey

**Comment by dumbbell0720** [comment]
@afc163  抱歉，是我点击事件里selectedRowKeys的处理逻辑不对。
![image](https://user-images.githubusercontent.com/30950222/89971873-045f2600-dc8f-11ea-8d6c-f82f069e4cb3.png)
