### ISSUE TITLE
Locale of RangePicker component only partially effective

### ISSUE THREAD

**Issue by LiJiahaoCoder** [ant-design/ant-design#26138]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-datepicker-issue-87zwq)

## RangePicker of antd

```tsx
import { DatePicker, ConfigProvider } from "antd";
import localeForAntPicker from "antd/es/locale/zh_CN";

import "antd/dist/antd.css";

const App = () => <ConfigProvider locale={localeForAntPicker}>
  <AntRangePicker />
</ConfigProvider>;
```

## RangePicker of rc-picker

```tsx
// copied from rc-picker/example

import { RangePicker as RcRangePicker } from "rc-picker";
import momentGenerateConfig from "rc-picker/lib/generate/moment";
import localeForRcPicker from "rc-picker/lib/locale/zh_CN";

const App = () => {
  // ...
  return <RcRangePicker<Moment>
    {...sharedProps}
    value={undefined}
    locale={localeForRcPicker}
/>
};
```

### What is expected?
Expect:

Show "2020年8月" and "一/二/三..." of week in panel.

### What is actually happening?
Actually:

Show "2020年 Aug" and "Mo/Tu/We..." of week in panel.

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.12.0 |
| System | MacOS v10.15.3 |
| Browser | Chrome v84.0.4147.89 |

---
Both of  antd and rc-picker have same behavior.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-datepicker-issue-forked-jvbom?file=/src/App.tsx
