### ISSUE TITLE
inputNumber 的onChange函数无法被调用

### ISSUE THREAD

**Issue by Yangzhedi** [ant-design/ant-design#2613]
#### 本地环境

- antd 版本:1.6.4
- 操作系统及其版本：win7
- 浏览器及其版本: chrome44

#### 你做了什么？
 引入 antd 了 inputNumber

#### 实际上的结果：
inputNumber 的onChange函数无法被调用

**Comment by benjycui** [comment]
实测可以 http://ant.design/components/input-number/#components-input-number-demo-basic

在点击按钮和 blur 时会触发 onChange 事件。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001
