### ISSUE TITLE
Select 下拉框，列表中是中文列表，是否支持下英文输入也筛选下

### ISSUE THREAD

**Issue by EagleWolf** [ant-design/ant-design#2614]
#### 本地环境

- antd 版本:1.4.0
- 操作系统及其版本：win7 64位
- 浏览器及其版本: Chrome 52.0.27

#### 你期待的结果是：

列表是汉字的，输入英文的时候也可以进行筛选。像输入汉字一样进行筛选。

**Comment by afc163** [comment]
filterOption 支持函数调用。

**Comment by EagleWolf** [comment]
如何使用filterOption函数，实现输入字母，进行筛选那？
