### ISSUE TITLE
TreeSelect 节点同时指定title和label的时候，会选择显示label，文档里面并没有提到这点，之前的版本里也不是这样的行为。

### ISSUE THREAD

**Issue by wangsenyuan** [ant-design/ant-design#26148]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/new-https-m1t3w?file=/index.js)

### Steps to reproduce
TreeSelect 节点同时指定title和label

### What is expected?
使用title来显示

### What is actually happening?
使用了label

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome, FF |

**Comment by 07akioni** [comment]
https://ant.design/docs/react/migration-v4-cn

应该是 v3 到 v4 的升级导致的，文档里确实没有提到

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/90090855-a6e2dc00-dd57-11ea-9100-67cd7a1535f5.png)

**Comment by wangsenyuan** [comment]
> https://ant.design/docs/react/migration-v4-cn
> 
> 应该是 v3 到 v4 的升级导致的，文档里确实没有提到

在4 版本里面应该是没有这个问题的。最近一次build，自动install 了 4.5.3 版本才发现的。

**Comment by 07akioni** [comment]
> > https://ant.design/docs/react/migration-v4-cn
> > 应该是 v3 到 v4 的升级导致的，文档里确实没有提到
> 
> 在4.2.* 版本里面应该是没有这个问题的。最近一次build，自动install 了 4.5.3 版本才发现的。

4.2.0 存在问题

**Comment by zombieJ** [comment]
嗯，这是为了 labelInValue 对齐调整的。文档需要提及一下。
