### ISSUE TITLE
Button with primary type and danger prop in Button.Group has a blue left border

### ISSUE THREAD

**Issue by cagen** [ant-design/ant-design#26142]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7eeit)

### Steps to reproduce
open the reproduction link

### What is expected?
no blue border

### What is actually happening?
blue border appear

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | macOS |
| Browser | Chrome Version 86.0.4229.0 (Official Build) canary (x86_64) |

---
I am upgrading antd from 3.x to 4.x. It was not a problem when using 3.x.
https://codesandbox.io/s/stupefied-rosalind-6dry6

**Comment by 07akioni** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-r3z36?file=/index.js

**Comment by cagen** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-r3z36?file=/index.js
> 
> use type instead

@07akioni Hi，Thx for the reply. Setting type to `danger` works. But the typescript will report an error.  
  
![image](https://user-images.githubusercontent.com/5174809/90479152-cebfae80-e160-11ea-8a5c-f36a2de5a38b.png)



And I think the [documents](https://ant.design/components/button/) have some confused information, which may need to be clarified:
* In the example of `Danger Buttons` it says `danger is a property of button after antd 4.0.`
* And in API section, `danger` is still one of the possible `type` value.

**Comment by 07akioni** [comment]
> > https://codesandbox.io/s/antd-reproduction-template-forked-r3z36?file=/index.js
> > use type instead
> 
> @07akioni Hi，Thx for the reply. Setting type to `danger` works. But the typescript will report an error.
> 
> ![image](https://user-images.githubusercontent.com/5174809/90479152-cebfae80-e160-11ea-8a5c-f36a2de5a38b.png)
> 
> And I think the [documents](https://ant.design/components/button/) have some confused information, which may need to be clarified:
> 
> * In the example of `Danger Buttons` it says `danger is a property of button after antd 4.0.`
> * And in API section, `danger` is still one of the possible `type` value.

you are right. this could be a bug.

**Comment by 07akioni** [comment]
however, button group is deprecated. it's not recommended to use it.

**Comment by zombieJ** [comment]
Since v3 is out of maintain that we have compatible the Buton.Group for a long time seems meaningless. Should upgrade the migration doc that we do not support button group any longer.

**Comment by cagen** [comment]
> however, button group is deprecated. it's not recommended to use it.



> Since v3 is out of maintain that we have compatible the Buton.Group for a long time seems meaningless. Should upgrade the migration doc that we do not support button group any longer.


Ah, got it.
I will change the way of grouping buttons, Thx!
