### ISSUE TITLE
List shows both Loading and No Data indicators

### ISSUE THREAD

**Issue by yuribit** [ant-design/ant-design#26146]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/yuribit/pen/NWNGzGO?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Flist%2F](https://codepen.io/yuribit/pen/NWNGzGO?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Flist%2F)

### Steps to reproduce
List with customized loading indicator and empty dataSource shows No Data and Spinner at the same time.

### What is expected?
No Data should be hidden and the loading indicator should be visible.

### What is actually happening?
Both No Data and Spinner are visible at the same time.

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.x |
| System | MacOS 10.15 |
| Browser | Chrome Version 84.0.4147.105 |

**Comment by afc163** [comment]
It is intented behavior, you can set empty text by `locale={{ emptyText: loading ? '' : <Empty> }}`.
