### ISSUE TITLE
Bug: This line of code doesn't work in this table case

### ISSUE THREAD

**Issue by alucard-ltd** [ant-design/ant-design#26151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8qgn1)

### Steps to reproduce
https://ant.design/components/table/#components-table-demo-edit-cell
In this case,  `this.state.dataSource.length >= 1 ? ( <Comp /> ) : null`, it not work.

### What is expected?
Delete btn should be display when this.state.dateSource.length is 1.

### What is actually happening?
But actually it still show.

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | chrome web page |
| Browser | chrome |

**Comment by afc163** [comment]
> Delete btn should be display when this.state.dateSource.length is 1.

> But actually it still show.

Should or should not the Delete btn be shown?

**Comment by afc163** [comment]
```diff
- this.state.dataSource.length >= 1
+ this.state.dataSource.length > 1
```
