### ISSUE TITLE
How to use QueueAnim with Table

### ISSUE THREAD

**Issue by EdenLiang** [ant-design/ant-design#2615]
#### 本地环境

- antd 版本:1.6.5
- 操作系统及其版本：wIn 10
- 浏览器及其版本:chrome 50.x
- react: 15.2.1
- rc-queue-anim: 0.12.4

#### 你做了什么？
引入了QueueAnim，以及Table
当然官方的demo是可以的，然而没有和Table联动的demo
尝试在Table上增加key，然而并没有“进场”和“出场”效果
是否无法联动呢？

**Comment by afc163** [comment]
http://react-component.github.io/table/examples/animation.html

**Comment by EdenLiang** [comment]
many thx
