### ISSUE TITLE
Using multiple ConfigProvider, when child ConfigProvider ummount, it should not changeConfirmLocale to default.

### ISSUE THREAD

**Issue by senwong** [ant-design/ant-design#26155]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/protable-bug-zkp4s?file=/src/App.js)

### Steps to reproduce
1. click 'open modal' button, modal footer button is '取消 确定'  
2.  click 'toggle table',  
3. click 'open modal' button, modal footer button change to 'cancel  ok'

### What is expected?
modal footer button is  '取消 确定'  

### What is actually happening?
modal footer button is 'cancel  ok'

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome 84 |

---
when LocalProvider component will unmount, it should not change confirm locale to default,  should change to legacyLocale.

**Comment by zombieJ** [comment]
Please use hooks instead: https://ant.design/components/modal-cn/#components-modal-demo-hooks
