### ISSUE TITLE
官网Tree树形控件拖拽demo有一系列bug

### ISSUE THREAD

**Issue by zjuasmn** [ant-design/ant-design#2616]
#### 本地环境

- antd 1.7.0:
- Mac OS X：
- Chrome 51

#### 你做了什么？

使用官网的树形控件拖拽

1. 将0-0-0-0 移出 0-0-0 至0-0下
2. 将0-0-0-1 0-0-0-2 移出0-0-0
3. 0-0往下移至0-2下方

#### 你期待的结果是：
1. 0-0-0-0移到在0-0下作为他的儿子
2. 0-0-0 左边指示箭头消失
3. 0-0在0-2下方成为最后一个节点
4. 0-0在移动时不会提示插入到自己的子孙节点
5. 移动完成后鼠标移开节点蓝色高亮消失

#### 实际上的结果：
1. 0-0-0-0移到了0-0上方
2. 0-0-0左侧仍有箭头
3. 0-0在0-2上方，成为倒数第二个元素
4. 0-0在移动时会提示插入到自己的子孙节点
5. 移动完成后鼠标移开不时会有部分节点仍然高亮

#### 可重现的在线演示
http://ant.design/components/tree/

**Comment by warmhug** [comment]
插入到自己的子孙节点，控制台有 warn 提示。箭头和部分节点高亮问题、我看下。其他问题我再测测

**Comment by zjuasmn** [comment]
插入自己子孙节点主要的问题是当0-0收起来，作为一个整体往下拖动时，子孙节点直接就展开了，如何能让他们在拖动过程中不展开呢？

**Comment by warmhug** [comment]
![image](https://cloud.githubusercontent.com/assets/2011119/17479493/63ef40b8-5da5-11e6-80a2-e0b9d30fa782.png)

可以自己控制是否展开

**Comment by warmhug** [comment]
ref #2660
