### ISSUE TITLE
umi更改ant的table的hover样式无法生效

### ISSUE THREAD

**Issue by LastStranger** [ant-design/ant-design#26164]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/customize-theme-cn#header](https://ant.design/docs/react/customize-theme-cn#header)

### Steps to reproduce
在项目根目录的 config/config.js（Umi）文件中 theme 字段进行主题配置.
```
  theme: {
    // 'primary-color': primaryColor,
    'border-radius-base': '2px',
    "primary-color": "#1DA57A",
    'table-selected-row-bg': '#7af',
    'item-active-bg': '#1DA57A',
    'item-hover-bg': '#1DA57A',
    'table-header-bg': '#1DA57A'
  },
```
`'item-active-bg': '#1DA57A',
    'item-hover-bg': '#1DA57A',`这两个属性无法生效

### What is expected?
table的hover颜色变为#1DA57A

### What is actually happening?
无变化

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | macos |
| Browser | 76 |

**Comment by LastStranger** [comment]
这怎么创建?公司项目无法提供,所以说按照目前的情况,我给的信息是正确的,只是没有更详细的信息?

**Comment by LastStranger** [comment]
我想了解我的写法有问题吗?

**Comment by LastStranger** [comment]
还是说item-active-bg和item-hover-bg这两个不是用来控制table的hover颜色的?

**Comment by afc163** [comment]
用 create-umi 搞一个重现 repo。

**Comment by afc163** [comment]
确实不是，两者颜色不一样：https://github.com/ant-design/ant-design/blob/0c1504cc8d0390774128720ef4a840d2cfdd323d/components/style/themes/default.less#L583
