### ISSUE TITLE
Unable to load initial values in Form when Modal opens

### ISSUE THREAD

**Issue by GeorgeCodeHub** [ant-design/ant-design#26169]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/antd-modalform?file=ContentModal.js](https://stackblitz.com/edit/antd-modalform?file=ContentModal.js)

### Steps to reproduce
- Set state as the initialValues in the Form.
- Have them load when the modal opens with componentDidMount which updates the current state.

### What is expected?
When opening the modal it should saw the values given in the componentDidMount.

### What is actually happening?
When modal opens no values are loaded as initial Values in the Form.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | react@16.12 |
| System | Windows 10 Pro Version	10.0.18362 Build 18362 |
| Browser | Mozilla Firefox@79.0 (64-bit) |

**Comment by afc163** [comment]
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/507615/90006767-1d39fc80-dccc-11ea-8dfb-4fe55a5fb1ee.png">

**Comment by GeorgeCodeHub** [comment]
I didn't think of looking below the Form.item settings. Thank you for the quick response!
