### ISSUE TITLE
日期或者时间需要格式化输出

### ISSUE THREAD

**Issue by 134355** [ant-design/ant-design#26167]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当和form一起使用时返回的值是（moment）这个值需要手动格式化后才能传给后端使用，返回这个（moment）真是太难用了
如果返回的值能设置格式化，就不需要手动去格式化这个（moment），在后台或者中台有着大量的表单或者查询表格数据， 都要手动去格式， 这步很多余，和form使用时能配置输出格式化后的日期或者时间，不需要手动去做这个操作，为什么了，因为这个操作重复性太高了，没法复用

### What does the proposed API look like?
建议参考elementui   iview

**Comment by 134355** [comment]
![image](https://user-images.githubusercontent.com/38032758/89996591-8ebe7e80-dcbd-11ea-8fa0-4233f1b44032.png)

**Comment by 134355** [comment]
![image](https://user-images.githubusercontent.com/38032758/89996803-d5ac7400-dcbd-11ea-9579-7ac737bbb732.png)

**Comment by yoyo837** [comment]
可是这强依赖后台，有的接口习惯long数字，有的又是别的格式，不太可能写死进去。

**Comment by 134355** [comment]
> 可是这强依赖后台，有的接口习惯long数字，有的又是别的格式，不太可能写死进去。

我之前使用的时element和iview的，可以配置这个时间格式化，但是antd这个真的很蛋疼，这些操作很多余，但又不得不做

**Comment by 134355** [comment]
希望大佬们可以参考，毕竟这样的设计很好
![QQ截图20200812171922](https://user-images.githubusercontent.com/38032758/89998514-405eaf00-dcc0-11ea-801f-c7240307fda8.png)

**Comment by afc163** [comment]
可以对 DatePicker 做一层上层封装就行，value 接收一个 format 后的字符串，onChange 返回同样的字符串。

**Comment by 134355** [comment]
> 可以对DatePicker做一个上层封装，值接收一个格式后的字符串，onChange返回相同的字符串。
> 
> ```js-jsx
> const  MyDatePicker  =（props）=> {
>    //这里做一层转换
>   return < DatePicker  { ... props } />
> };
> 
> < Form.Item  名称= “日期” >
>   < MyDatePicker />
> </ Form.Item >
> ```

怎么转换啊，

**Comment by afc163** [comment]
https://codesandbox.io/s/affectionate-kowalevski-5g8g6?file=/index.js

**Comment by 134355** [comment]
> https://codesandbox.io/s/affectionate-kowalevski-5g8g6?file=/index.js
感谢大佬

**Comment by gametheworld** [comment]
> 可以对 DatePicker 做一个上层封装，value 接收一个 format 后的字符串，onChange 返回同样的字符串。
> 
> ```js
> const MyDatePicker = (props) => {
>   // 这里做一层转换
>   return <DatePicker {...props} />
> };
> 
> <Form.Item name="date">
>   <MyDatePicker />
> </Form.Item>
> ```

如果是直接在FormData上设置值的怎么处理？

`form.setFieldsValue({
						...data
					});`


这种请求就很头大了啊兄弟
