### ISSUE TITLE
Popover content flickering when Checkbox is checked and wrapped by overflow: "auto"

### ISSUE THREAD

**Issue by NoyChan** [ant-design/ant-design#26161]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kpr5u?file=/index.js)

### Steps to reproduce
Popover组件的content内添加处于选中状态的Checkbox，Checkbox的父级设置样式overflow :“auto”

### What is expected?
Popover弹出内容不闪烁

### What is actually happening?
Popover弹出内容不断闪烁

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | latest |
| System | window |
| Browser | chrome 79 |

**Comment by 07akioni** [comment]
I can't reproduce it

**Comment by NoyChan** [comment]
![image](https://uploads.codesandbox.io/uploads/user/ea0a78d9-2a26-42be-9c57-9a4fa6b8ce4b/hNO5-reproduce.gif)
seem like just happened in Chrome browser , using the link provided above

**Comment by asaadam** [comment]
hey it seems working on me

![Antd](https://user-images.githubusercontent.com/1397612/90463258-ac17a080-e134-11ea-918a-a2883f35b8c9.gif)

can you provide what's your chrome version?

mine is 84.0.4147.125

**Comment by NoyChan** [comment]
it happens only if you keep the checkbox in checked status ,&nbsp;minie&nbsp;chrome version&nbsp;is 83.0.4103.116 and&nbsp;79.0.3945.88




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Adam Akbar"<notifications@github.com&gt;; 
发送时间: 2020年8月18日(星期二) 上午10:25
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "陈焕杰"<191925313@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] Popover content flickering when Checkbox is checked and wrapped by overflow: &quot;auto&quot; (#26161)





 
hey it seems working on me
 

 
can you provide what's your chrome version?
 
mine is 84.0.4147.125

**Comment by afc163** [comment]
You can try these workarounds:

```diff
    <Popover
      placement={"bottom"}
      content={
-       <div style={{ overflowY: "auto" }}>
+       <div>
          <Checkbox defaultChecked={true}>Some Text</Checkbox>
        </div>
      }
    >
      <span>antd version: {version}</span>
    </Popover>
```

or

```diff
    <Popover
      placement={"bottom"}
      content={
        <div style={{ overflowY: "auto" }}>
          <Checkbox defaultChecked={true}>Some Text</Checkbox>
        </div>
      }
+     overlayStyle={{ width: 160 }}
    >
      <span>antd version: {version}</span>
    </Popover>
```

**Comment by NoyChan** [comment]
```diff
<Popover
  placement={"bottom"}
  content={
    <div style={{ maxHeight: 300, overflowY: "auto" }}>
      {mockData.map(v => (
+      <div key={v.key} style={{ overflow: "hidden", lineHeight: "22px" }}>
        <Checkbox checked={v.checked}>{v.label}</Checkbox>
+      </div>
      ))}
    </div>
  }
>
  <span>some text</span>
</Popover>
```
I'd like to keep my outer overflow: "auto", so my workaroud is wrap the Checkbox with overflow: "hidden"

**Comment by 07akioni** [comment]
看起来 checkbox 的动画会不停的播放
