### ISSUE TITLE
table 使用fixed固定第一列时，如果第一列固定宽度同时包含的内容过长会导致表格行间错位

### ISSUE THREAD

**Issue by hzura** [ant-design/ant-design#26162]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fervent-chandrasekhar-uvgf0?file=/index.js)

### Steps to reproduce
打开即可现

### What is expected?
表格不出现错位

### What is actually happening?
表格错位

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.13.1 |
| System | macos catalina 10.15.4 |
| Browser | chrome |

**Comment by afc163** [comment]
This issue is handled well in v4, please upgrade to antd v4.

**Comment by ygnihao** [comment]
antd vue 版本的仍然没有更新
