### ISSUE TITLE
Error occurred when using treenode search (korean)

### ISSUE THREAD

**Issue by namiomiru** [ant-design/ant-design#26165]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/antd-reproduction-template-forked-trpky?file=/index.js:0-1214

### Steps to reproduce
treenode search in Korean ( ex: 자동차)

### What is expected?
search

### What is actually happening?
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in t (created by OptionList)
| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | mac 10.15.5 |
| Browser | 84 |

**Comment by afc163** [comment]
I can't reproduce in your stackblitz.

**Comment by namiomiru** [comment]
> I can't reproduce in your stackblitz.

I'm sorry, but you have to type in Korean one by one for errors to occur.

![image](https://user-images.githubusercontent.com/34525483/90488162-72678980-e176-11ea-96c4-fa4dbfaa82fd.png)
![image](https://user-images.githubusercontent.com/34525483/90488195-801d0f00-e176-11ea-9be0-eef2633d6442.png)

**Comment by afc163** [comment]
I can't reproduce it with Korean keyboard, please send us PR if you find solution.

**Comment by namiomiru** [comment]
> I can't reproduce it with Korean keyboard, please send us PR if you find solution.

okay
I'll PR it when I find it.
