### ISSUE TITLE
Tree控件设置了expandedKeys的值后，去除某些key，图标箭头变了，但节点并没有收缩起来

### ISSUE THREAD

**Issue by mu1004** [ant-design/ant-design#26166]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://adf.rnd.sfd.com/asdt](http://adf.rnd.sfd.com/asdt)

### Steps to reproduce
前置条件：
树的节点是异步加载
需要实现的功能：需要记录本次页面操作的展开节点，下次进入后直接打开
实现逻辑：在localstorage中存储每次展开的值，下次进入页面时，塞入该值到expandedKeys中

现象：
当节点多级时，选择展开的值是跨级选择，比如【0-0,0-0-1,0-1,0-2,0-2-0】,那么最终只会展开0-2-0，而其他的展开只是改变了图标（箭头方向），导致数据无法loaded

方案改进：让每次展开同一级有且仅能展开一个，其余都自动收缩；
但出现了问题：当前操作：图标箭头变了，但节点并没有收缩起来（依次展开：0-0 ---> 0-0-0 ---> 0-0-1）此时0-0-0的图标变了（箭头方向）但并未把子节点收起来

### What is expected?
现象：
当节点多级时，选择展开的值是跨级选择，比如【0-0,0-0-1,0-1,0-2,0-2-0】,那么最终只会展开0-2-0，而其他的展开只是改变了图标（箭头方向），导致数据无法loaded

方案改进：让每次展开同一级有且仅能展开一个，其余都自动收缩；
但出现了问题：当前操作：图标箭头变了，但节点并没有收缩起来（依次展开：0-0 ---> 0-0-0 ---> 0-0-1）此时0-0-0的图标变了（箭头方向）但并未把子节点收起来

### What is actually happening?
现象：
当节点多级时，选择展开的值是跨级选择，比如【0-0,0-0-1,0-1,0-2,0-2-0】,那么最终只会展开0-2-0，而其他的展开只是改变了图标（箭头方向），导致数据无法loaded

方案改进：让每次展开同一级有且仅能展开一个，其余都自动收缩；
但出现了问题：当前操作：图标箭头变了，但节点并没有收缩起来（依次展开：0-0 ---> 0-0-0 ---> 0-0-1）此时0-0-0的图标变了（箭头方向）但并未把子节点收起来

| Environment | Info |
|---|---|
| antd | 4.5.0 |
| React | 16.12.0 |
| System | windows 10  |
| Browser | chrome 81  |

**Comment by PeachScript** [comment]
重现链接无法打开；另外，最好在 codesandbox.io 之类的平台上提交重现**最小可复现** demo，便于查看代码

**Comment by 1eeing** [comment]
直接用官网的可搜索的tree就可以复现：https://ant.design/components/tree-cn/

复现步骤：先全部展开，然后快速输入1-1，就可以发现收缩是有问题的
