### ISSUE TITLE
Space组件中存在条件渲染，会重置内部表单组件的初值

### ISSUE THREAD

**Issue by sdhr27** [ant-design/ant-design#26177]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-cannon-h2e9h?file=/index.js)

### Steps to reproduce
1. 使用Space，其中包含表单元素
2. 表单元素之外的元素为条件渲染，表单元素表单域改变时触发条件渲染
3. 表单元素会被重置

### What is expected?
表单元素不会被重置

### What is actually happening?
表单元素被重置

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | windows10 |
| Browser | Google Chrome83.0.4103.97 |

**Comment by xrkffgg** [comment]
https://codesandbox.io/s/elastic-https-ljctb?file=/index.js  我这正常啊

**Comment by sdhr27** [comment]
如果用&&就会有问题，三元不会

**Comment by xrkffgg** [comment]
&& 更改了 children 的数量，重新渲染也没毛病啊。
实际上 select 的值变了，但是重新渲染，因为有 defaultValue，又显示默认值了。

**Comment by xrkffgg** [comment]
或者你把 defaultValue 改成变量，再 change 的时候，同时用 useState 把这个也更新了

**Comment by 07akioni** [comment]
> && 更改了 children 的数量，重新渲染也没毛病啊。
> 实际上 select 的值变了，但是重新渲染，因为有 defaultValue，又显示默认值了。

我试了试，为什么加 key 也没有用呢

**Comment by xrkffgg** [comment]
感觉最好是不动 children 的数量

**Comment by shaodahong** [comment]
> > && 更改了 children 的数量，重新渲染也没毛病啊。
> > 实际上 select 的值变了，但是重新渲染，因为有 defaultValue，又显示默认值了。
> 
> 我试了试，为什么加 key 也没有用呢，在原本的 demo

因为外层的 Key 已经变了，这块可以优化下，Demo 的对的，但是如果在传 key 的情况下确实可以优化下

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/blob/1c63268e6a4cd14ca8148b51cfc9306136b46375/components/space/index.tsx#L67

这样？
```
key={child.key || `${itemClassName}-${i}`}
```

**Comment by shaodahong** [comment]
倾向于 `${itemClassName}-${child.key || i}`}

**Comment by 07akioni** [comment]
> 倾向于 `${itemClassName}-${child.key || i}`}

感觉这个不好，有风险，数字很容易冲上，有 key 和无 key 要保证不会冲突：
`${itemClassName}-{child.key === undefined ? i :  'key-' + child.key }`

**Comment by xrkffgg** [comment]
😂  为用户 真是操碎了心

**Comment by afc163** [comment]
用 React.Children.map 替换 map 试试，把 key={index} 去掉。
