### ISSUE TITLE
bugs in 'Select' component: open and dropdown options updates

### ISSUE THREAD

**Issue by jiehan1029** [ant-design/ant-design#26179]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/happy-breeze-vh9y4)

### Steps to reproduce
1. click select, can see 4 dropdown options.
2. search
3. should render the predefined 1 option, but instead saw empty dropdown.
4. click on input to open dropdown again, this time see the 1 option.

### What is expected?
should see the dropdown options updated.

### What is actually happening?
dropdown options are not updated, even though the correct data has been passed into the `Select` component. (see console log before return)

| Environment | Info |
|---|---|
| antd | 4.0.3 |
| React | React 16.13.1 |
| System | Mac High Sierra 10.3.6 |
| Browser | Chrome 84.0.4147.105 |

---
I have another bug about Select component but unfortunately unable to create simplified version to demo. Main issue is that I passed an `dropdownOpen` as `open` props to `Select`, but dropdown didn't open as it should be. I'm sure the `dropdownOpen` is set correct, since I console log it in render, and it's true. What are the possible causes that stopped dropdown from open?

**Comment by 07akioni** [comment]
it is not a bug, if you search `5`, `O5` will be displayed.

if you search something not matching for example `blablabla`, `O5` shouldn't be displayed which is as expected.
