### ISSUE TITLE
How to hide a specific value when using Slider

### ISSUE THREAD

**Issue by jovanimal** [ant-design/ant-design#26180]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-v0zbb)

### Steps to reproduce
The step on the slider is 50k each, I want to skip the value 950k.

### What is expected?
Allow me to hide only the value 950,000 in the Slider, when I slide from 900k to 1 million.

Example:
<a href="https://imgflip.com/gif/3pi6t4"><img src="https://media.giphy.com/media/dZ3VceSTjbeL6Fj7s3/giphy.gif"/></a>

### What is actually happening?
It's showing 950k, as the step is 50k.

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/90088960-cb888500-dd52-11ea-8f93-e16c05c90f39.png)
reproduction link is irrelevant.

however I think you can use controlled mode to skip 95k. simply not apply value from onChange when value is 95k.
