### ISSUE TITLE
表单字段trigger设置为失去焦点（onBlur）收集时，再次得到焦点，Input的内容不能删除和增加，且失去焦点依然会触发表单onValuesChange事件

### ISSUE THREAD

**Issue by cqluohong** [ant-design/ant-design#26185]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-forked-n9pxd](https://codesandbox.io/s/antd-reproduction-template-forked-n9pxd)

### Steps to reproduce
1.表单两个字段，一个Input，一个Select，Input的trigger为‘OnBlur’，Form设置onValuesChange事件
2.填充Input字段，tab键失去焦点，触发onValuesChange事件，将焦点再次定位到Input上，无法修改和删除字段
3.再次按下tab键失去焦点，Input值未改变仍然触发onValuesChange事件

### What is expected?
我希望Input失去焦点时，收集字段值，请求后端，初始化表单Select的Option

### What is actually happening?
失去焦点的Input再次获得焦点，无法删除和添加内容

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | antd pro 使用的React版本 |
| System | window10企业版 |
| Browser | chrome 84.0.4147.125 |

---

**Comment by xrkffgg** [comment]
@07akioni @Kermit-Xuan  有空的话，来瞅一下~

**Comment by tianfeng65** [comment]
关注中，等修复！

**Comment by zombieJ** [comment]
这个不是 bug，需要 onBlur 收集值就自定义组件实现。Field 本身对子元素是受控的。
