### ISSUE TITLE
TreeSelect - Inconsistent look and behavior

### ISSUE THREAD

**Issue by visvadw** [ant-design/ant-design#2619]
Hello everybody,

`TreeSelect` needs a little improvement in order to have a consistent look and behavior.

When either empty or populated, the symbol on the right side suggests that you can use it for expanding the control and getting the values, just like `Select`.
![2016-08-04_142944](https://cloud.githubusercontent.com/assets/14140226/17400407/5b28d44c-5a50-11e6-906c-1913d896644c.png)
On the other hand, when you click on it it will do something else: clearing the entrie(s), without asking for a confirmation.
![2016-08-04_143122](https://cloud.githubusercontent.com/assets/14140226/17400419/696c0998-5a50-11e6-8dae-c0d82fce96bf.png)
Imagine that a user may want to provide additional entries to the existing ones. As we all know, you tend to click on the symbol to get the values. But this action clears the existing selected values. If you don't know/remember the entries, you may be lost or forced to cancel and reenter the form.

Issue [2557](https://github.com/ant-design/ant-design/issues/2557) suggests an improvement (the clear icon should be visible only when value is selected), but it still does not provide a consistent user experience.

Maybe a confirmation dialog can help by forcing the user to confirm that he really wants to clear it.

**Comment by GrayChoi** [comment]
Agree. 
Cascader has same problem.
I think we even don't need clear icon, just add a del key event listener to clear the value.

**Comment by visvadw** [comment]
Right! As everybody is used to click on the icon to expand it, it should behave like that.
If multiples entries exist, maybe an option to select it before pressing Backspace key would help.

**Comment by visvadw** [comment]
And with `Cascader` the inconsistency is bigger, as:
- when empty, clicking on the right symbol it looks and behave as it is used for expanding the control

![image](https://cloud.githubusercontent.com/assets/14140226/17413218/fbb72250-5a88-11e6-8740-f48a6b6b30cf.png)

- but when an entry exists, the right symbol role changes:

![image](https://cloud.githubusercontent.com/assets/14140226/17413299/54d29e64-5a89-11e6-9506-60b90c33df29.png)

**Comment by warmhug** [comment]
fixed ref #2557

**Comment by afc163** [comment]
@warmhug it is not about this.

**Comment by afc163** [comment]
Just keep original behavior, it is by designed.
