### ISSUE TITLE
form.setFieldsValue 之后再去选择日期  出错clone.weekday is not a function

### ISSUE THREAD

**Issue by KouSum** [ant-design/ant-design#26190]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/replace-moment-cn 按照此教程替换 Moment.js为dayjs ](https://ant.design/docs/react/replace-moment-cn 按照此教程替换 Moment.js为dayjs )

### Steps to reproduce
按照教程替换 Moment.js为dayjs     form中使用RangePicker     form.setFieldsValue 之后再去选择日期  出错clone.weekday is not a function
```javascript
import React, { useState, useEffect } from 'react';
import {
  Form,
  Button,
} from 'antd';
import { DatePicker, Calendar } from '../components';
import format from 'dayjs';


const dateFormat = 'YYYY-MM-DD';
const { RangePicker } = DatePicker;
function Demo(props) {
  const [form] = Form.useForm();
  useEffect(() => {
    form.setFieldsValue({
      dates: [format("2020-05-05",dateFormat), format("2020-05-06",dateFormat)],
    });
  }, []);



  const onFinish = values => {
    console.log('Finish:', values);
  };

  function dateChange(a,b,c){
    console.log(a,b,c)
  }

  return (

    <Form form={form} name="statis" layout="inline" onFinish={onFinish}>
      <Form.Item name="dates">
        <RangePicker initialValues={[format('2015-01-01', dateFormat), format('2015-01-01', dateFormat)]} onChange={dateChange} format={dateFormat} />
      </Form.Item>
      <Form.Item>
        <Button
          type="primary"
          htmlType="submit"
          onClick={() => {
            console.log(
              form.getFieldsValue(),
              format('2018-08-08').format('YYYY-MM-DD'),
            );
          }}
        >
          查询
        </Button>
      </Form.Item>
    </Form>
  );
}

export default Demo;

```

### What is expected?
 form.setFieldsValue之后可以正常选择日期

### What is actually happening?
出错clone.weekday is not a function

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.12.0 |
| System | win10  |
| Browser | 谷歌浏览器 |

---

部分错误提示
dayjs.js:73 

Uncaught TypeError: clone.weekday is not a function
    at Object.getWeekDay (dayjs.js:73)
    at getWeekStartDate (dateUtil.js:97)
    at DateBody (DateBody.js:21)
    at renderWithHooks (react-dom.development.js:14803)
    at mountIndeterminateComponent (react-dom.development.js:17482)
    at beginWork (react-dom.development.js:18596)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at beginWork$1 (react-dom.development.js:23203)
    at performUnitOfWork (react-dom.development.js:22154)
    at workLoopSync (react-dom.development.js:22130)
    at performSyncWorkOnRoot (react-dom.development.js:21756)
    at react-dom.development.js:11089
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11039)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11084)
    at flushSyncCallbackQueue (react-dom.development.js:11072)
    at discreteUpdates$1 (react-dom.development.js:21893)
    at discreteUpdates (react-dom.development.js:806)
    at dispatchDiscreteEvent (react-dom.development.js:4168)

**Comment by 07akioni** [comment]
please provide a codesandbox link

**Comment by KouSum** [comment]
重装依赖包后就好了

**Comment by crownclownwl** [comment]
我也遇到这个问题了，回显之后，在编辑就报错

**Comment by KouSum** [comment]
[https://codesandbox.io/s/antd-reproduction-template-forked-6qd12?fontsize=14&hidenavigation=1&theme=dark](url)
不知道重现的是否正确，这里是正常的。

**Comment by G-WangZH** [comment]
> 我也遇到这个问题了，回显之后，在编辑就报错

我yongdayjs时也遇到了，请问解决了吗

**Comment by victorWuxz** [comment]
我也遇到了同样的问题

**Comment by harshithmullapudi** [comment]
4.5.0版本更新打破了dayjs的实现。这似乎适用于4.4.3

**Comment by Deboracgs** [comment]
I have the same problem with datepicker, any update?

**Comment by crownclownwl** [comment]
把项目中的 day.js 改成 moment.js 完美解决，就是 moment.js 太大了

**Comment by FabienDeborde** [comment]
Having the same issue here.
I would be really great if dayjs was better supported and didn't need a "hacky" way to implement it.
(a props passed to the picker would be the easiest way to use it)

**Comment by hoangmeo** [comment]
update lastest version  dayjs

**Comment by Deboracgs** [comment]
@crownclownwl moment.js is not recommended to use now, dayjs is the recommended to use

**Comment by Deboracgs** [comment]
@hoangmeo I'm using the lastest version

**Comment by marian2js** [comment]
This is an issue with rc-picker: https://github.com/react-component/picker/issues/123

**Comment by JemarJones** [comment]
The required plugins should probably be listed on that "Replace Moment.js" page IMO

**Comment by afc163** [comment]
@iamkun Should we update documentation?

**Comment by iamkun** [comment]
> @iamkun Should we update documentation?

@afc163 This is because, after 4.5.0, Antd uses `moment().weekday` which needs an additional Day.js plugin.

I'll update `antd-dayjs-webpack-plugin` to add the relevant plugin to make it work.

**Comment by afc163** [comment]
https://ant.design/docs/react/replace-moment-cn should include these additional Day.js plugins.

**Comment by iamkun** [comment]
Correct, and I'll update `rc-picker/lib/generate/dayjs` as well

**Comment by iamkun** [comment]
After digging this issue, it is actually because there are **TWO** Day.js package installed in `node_modules`, one `node_modules/dayjs`, the other might in `node_modules/rc-picker/dayjs`, and this is the reason that caused this error.

SOLUTION: 

1. Add dayjs to the dependency to `package.json`
2. delete `node_modules` and` package-lock.json`
3. npm install 
4. check and make sure there are only **ONE** Day.js package installed in `node_modules`

ref: https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/36

**Comment by cjfff** [comment]
> After digging this issue, it is actually because there are **TWO** Day.js package installed in `node_modules`, one `node_modules/dayjs`, the other might in `node_modules/rc-picker/dayjs`, and this is the reason that caused this error.
> 
> SOLUTION:
> 
> 1. Add dayjs to the dependency to `package.json`
> 2. delete `node_modules` and` package-lock.json`
> 3. npm install
> 4. check and make sure there are only **ONE** Day.js package installed in `node_modules`
> 
> ref: [ant-design/antd-dayjs-webpack-plugin#36](https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/36)

this solution can resolute my project.

but the dayjs instance maybe not in your node_modules, it could build in another package that it would not the same dayjs and the rc-picker import

**Comment by PipBoy2000** [comment]
> 4\. check and make sure there are only **ONE** Day.js package installed in `node_modules`

Yeah, that isn't working no matter how many times I nuke my package-lock.json and node_modules.  The `rc-picker` always has that dependency:

```
  "dependencies": {
    "@babel/runtime": "^7.10.1",
    "classnames": "^2.2.1",
    "date-fns": "^2.15.0",
    "dayjs": "^1.8.30",
    "moment": "^2.24.0",
    "rc-trigger": "^5.0.4",
    "rc-util": "^5.4.0",
    "shallowequal": "^1.1.0"
  }
```

**Comment by iamkun** [comment]
@PipBoy2000 Thanks, fixed in https://github.com/react-component/picker/pull/214

**Comment by YemreAybey** [comment]
I believe we will wait until ant-design update rc-picker version right?

**Comment by Messiahhh** [comment]
> After digging this issue, it is actually because there are **TWO** Day.js package installed in `node_modules`, one `node_modules/dayjs`, the other might in `node_modules/rc-picker/dayjs`, and this is the reason that caused this error.
> 
> SOLUTION:
> 
> 1. Add dayjs to the dependency to `package.json`
> 2. delete `node_modules` and` package-lock.json`
> 3. npm install
> 4. check and make sure there are only **ONE** Day.js package installed in `node_modules`
> 
> ref: [ant-design/antd-dayjs-webpack-plugin#36](https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/36)

Solved my problem
