### ISSUE TITLE
Form custom component: Calling onChange with new value creates new reference for method

### ISSUE THREAD

**Issue by chris335** [ant-design/ant-design#26192]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-nash-ql8jl?file=/src/App.js)

### Steps to reproduce
Calling onChange in custom form component will create a new reference of the onChange method

### What is expected?
Same reference to the onChange function when called by a new value

### What is actually happening?
New reference to onChange function

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12.0 |
| System | Windows 7 |
| Browser | Chrome v84 |

**Comment by zombieJ** [comment]
Why should keep the onChange ref?

**Comment by chris335** [comment]
In some scenarios there are unnecessary renders.
For me, the question arises whether there is a reason to provide a new function when a value changes?

**Comment by zombieJ** [comment]
Field need a wrap function since user may provide a handler in the same trigger:

```tsx
<Form.Item>
  <Input onChange={myOnChangeFunc} />
</Form.Item>
```

**Comment by chris335** [comment]
Still dont get why the FormItem provides a new function every time a value changes?

**Comment by chris335** [comment]
I have now done a workaround with useRef.
I store the function which solves my reference problems.

`const updateFunction = useRef(onChange);

const updateSelection = useCallback((keys) => {
    updateFunction.current(keys);
  }, [updateFunction]
);`

**Comment by zombieJ** [comment]
@chris335 what's your use case that need keep the `onChange`?

**Comment by zombieJ** [comment]
Close since no more feedback.
