### ISSUE TITLE
Need support for masking in the Input

### ISSUE THREAD

**Issue by kubade-anup** [ant-design/ant-design#26193]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Masked input gives user a hint and guides him to provide the valid input. Like country specific phone number. Each country has it's own format to show the phone number.
My requirement is to use mask for the IP address. Where user will see placeholder "\_\_\_.\_\_\_.\_\_\_.\_\_\_" which will accept only digits. And each part could have one or at max 3 digits. I tried to use other libraries but they fail to show the value correctly in the mask.
Here is an example. Mask "ddd.ddd.ddd.ddd", placeholderChar is "_" and the value passed is "192.168.1.4". I was expecting input box to show "192.168.1__.4__" but it showed me "192.168.1_4.\_\_\_". 
Similarly if the value passed is "0.0.0.0", then I see "0_0.0_0.\_\_\_.\_\_\_"

### What does the proposed API look like?
<Input mask="ddd.ddd.ddd.ddd" value="192.168.1.4" placeholderChar="_" onChange={this.onChange} />

**Comment by 07akioni** [comment]
use controlled mode. set `value` manually when change changes.
