### ISSUE TITLE
如何将Menu跟React Router的Link结合起来？

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#262]
我想用Menu菜单和react router，Menu生成是li，点击，hover等都是以li为基准的。
但router的Link本质是a，所以只能嵌入到li中。
形成：
< li class="menu" >< a href="#/create">< / a >< / li >
Menu自己监听的onClick事件是操作li的。
而router的Link监听的onClick事件是操作a的。
矛盾，如何合二为一？

**Comment by yiminghe** [comment]
<Item><Link to={yy}>xx</Link></Item>

**Comment by zccst** [comment]
@yiminghe 没这么简单，我就是这么做的。但解析后就变成我说的
< li class="menu" >< a href="#/create">< / a >< / li >

该问题我自己已解决，就是点击li（但未点击a）时，模拟点击a事件。
if (e.domEvent.target.nodeName === "LI" ) {
      this.simulateClick(e.domEvent.target.firstChild);
    }

**Comment by Tinker404** [comment]
```
<Item><Link to={yy}>xx</Link></Item>
```

可行，router本身就是控制hash来渲染页面，你那个方法也是可行的

**Comment by yiminghe** [comment]
a style 为 block

**Comment by zccst** [comment]
@yiminghe 是的，我已经先改成display:block，但在menu中，li与a之间有padding值，还是会导致点击到li了，但没点击到a的情况（比如两边），此时menu菜单选中状态已切换，但link没生效。

所以就增加了一个判断，如果点击到a，则正常跳转和样式切换。如果点击不到a，就先切换样式，再模拟点a，完成页面跳转。总体表现变得一致。
