### ISSUE TITLE
Dynamic Form Item with default values

### ISSUE THREAD

**Issue by nagendragandla001** [ant-design/ant-design#26204]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/](https://ant.design/components/form/)

### Steps to reproduce
Dynamic form items can't be loaded with backend response

### What is expected?
Dynamic Form Items should have feature to render the existing data along with add button.

### What is actually happening?
Currently it's not loading the existing data.

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | react |
| System | v12.14.1 |
| Browser | chrome Version 84.0.4147.89  |

**Comment by vedovato** [comment]
does this count as a reproduction? Also want to know how to render the form with initialValues
https://codesandbox.io/s/quirky-brook-ou9j9?file=/src/App.js

**Comment by vedovato** [comment]
Think i got it https://codesandbox.io/s/quirky-brook-ou9j9?file=/src/App.js

**Comment by exlame** [comment]
When changing the initialValues, it doesn't change the current value of the form. Usually, when i'm dealing with an async call to populate the initialValues, I run a FormInstance.resetFields() after the reset to the current initialValues. Another way would be to use the FormInstance.setFieldsValue() qalongside with the change of initialValues.
