### ISSUE TITLE
table组件 行点击时如何设置指定行的高亮或比较明细的样式，以便标记

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#26207]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们有一个需求：客户查看列表，点击列表或列表中的某一个ID标识列查看详情（抽屉），希望能够记住是哪一行显示的抽屉，以便频繁阅读行数据、详情数据时能够较方便区分关联数据。我们的数据行的checkbox给了批量删除、导出及其他批量操作。

### What does the proposed API look like?
大佬们定。

**Comment by afc163** [comment]
`rowClassName`
