### ISSUE TITLE
require an API to change the selected part of input with type date

### ISSUE THREAD

**Issue by Morteza-Jenabzadeh** [ant-design/ant-design#26202]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When using antDesing input with type date there is no API that can change the selected part of the date.
for instance, when the current selection is the year there is no access to change selection&focus to month or day

### What does the proposed API look like?
it would be nice if there was an API that can change the selected part of the date.

**Comment by 07akioni** [comment]
![image](https://user-images.githubusercontent.com/18677354/90474909-f9a60480-e158-11ea-99f3-b6c13fddf25f.png)

Month and year can be changed by click header.

If you want to change the value, use it in controlled mode.

**Comment by Morteza-Jenabzadeh** [comment]
Thanks for your answer
There are two points
1-The question is not about date picker its about an input with date type
2-its about how we can change selected digit(not change) with the program (not by user interaction)

**Comment by afc163** [comment]
`about an input with date type`

It is native input component which is not a antd issue.
