### ISSUE TITLE
Input组件, 当设置readOnly=true时，如何展示allowClear图标

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#26215]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/broken-haze-boj6j?file=/index.js)

### Steps to reproduce
鼠标移入 <Input.Search> 组件， 当设置readOnly=true时，没有展示allowClear图标

### What is expected?
鼠标移入 <Input.Search> 组件， 当设置readOnly=true时，可以设置展示allowClear图标

### What is actually happening?
鼠标移入 <Input.Search> 组件， 当设置readOnly=true时，没法展示allowClear图标

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 17.0.0-rc.0 |
| System | win 10 |
| Browser | Chrome 83.0.4103.61 |

---
或者有什么方法可以达到不想用户手动输入内容，但是可以通过allowClear图标删除内容？

**Comment by xrkffgg** [comment]
Try `suffix`
