### ISSUE TITLE
Select onSearch bug

### ISSUE THREAD

**Issue by Timson020** [ant-design/ant-design#26216]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/serene-rhodes-zctzo?file=/src/App.js)

### Steps to reproduce
select框输入timson

### What is expected?
显示1个选项

### What is actually happening?
空白

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | ^16.13.1 |
| System | Mac |
| Browser | chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/strange-hawking-i2huw?file=/src/App.js

or

simply https://codesandbox.io/s/recursing-edison-li0m4?file=/src/App.js
