### ISSUE TITLE
antd tabs切换卡，没有立即跳转到被点击的tab上面

### ISSUE THREAD

**Issue by hoho2017** [ant-design/ant-design#26211]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
tab切换延迟

### What does the proposed API look like?
先切换tab，再加载tab里面的内容

**Comment by hoho2017** [comment]
有没有一个 API 可以在tabs change之前触发方法

**Comment by hoho2017** [comment]
> 有没有一个 API 可以在tabs change之前触发方法

这样我就可以先加载loading了，不然直接执行tab里面的方法无法加载loading（貌似）

**Comment by hoho2017** [comment]
特殊情况不方便使用forceRender提前加载

**Comment by zhangchao828** [comment]
你可以把loading包住整个Tabs组件，然后触发它

**Comment by ahxdg** [comment]
你可以先把数据备份一下，然后设置成空值。等tab切换获取后，再把备份的数据设置回来就行了。当然最好是加个延迟..
