### ISSUE TITLE
Which rich text editor do you recommend.

### ISSUE THREAD

**Issue by huseyingoztok** [ant-design/ant-design#26218]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.nolink.com](https://www.nolink.com)

### Steps to reproduce
  ***

### What is expected?
  ***

### What is actually happening?
  ****

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome |

---
How to set values ​​to rich text editors in the form. Can you give a detailed example. When the form is loaded, I want to give the editors their initial values. The example could be with BraftEditor or another editor you recommend.

**Comment by huseyingoztok** [comment]
How can I set a value in editore with the form's initialValues ​​props?

**Comment by afc163** [comment]
See https://ant.design/docs/react/recommendation

**Comment by huseyingoztok** [comment]
I saw it but could not see enough information for use. I cannot set a value in the editor when the page is loaded. I actually asked for help in this matter.

**Comment by afc163** [comment]
See https://braft.margox.cn/demos/antd-form

**Comment by huseyingoztok** [comment]
Thanks for the document. But in version 4.1.5 there is no getFieldDecorator. When I tried setting values ​​in 4.1.5, I could not give the initial value to the editor. As you mentioned above, I am trying to give the value of the form with the initialValues ​​props, but it doesn't work.

**Comment by afc163** [comment]
You can ask in https://github.com/margox/braft-editor/issues
