### ISSUE TITLE
Validation rules not working in InputNumber

### ISSUE THREAD

**Issue by debotos** [ant-design/ant-design#26228]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-bardeen-deh5j?file=/src/App.js)

### Steps to reproduce
I created a code sandbox to reproduce the issue please check it out.

### What is expected?
Range validation should trigger if it is not between 20 and 100

### What is actually happening?
Range validation triggering if there is value

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | ^16.13.1 |
| System | MacOS 10.15.6 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/clever-germain-2l1qx
