### ISSUE TITLE
Description.Item component doesn't support customize style

### ISSUE THREAD

**Issue by Kexin-Li** [ant-design/ant-design#26220]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/purple-platform-vgjyw?file=/index.js)

### Steps to reproduce
Take a look at `Description.Item` component

### What is expected?
I set style props to `Description.Item` component, which should override the color of the text.

### What is actually happening?
nothing happened.

| Environment | Info |
|---|---|
| antd | 4.2.2 |
| React | 17.0.0-rc |
| System | macOS 10.15.6 |
| Browser | Chrome 84.0.4147.125 |

---
I noticed `Description.Item` doesn't support style props yet, is there any way I can customize styles? Thanks!

**Comment by llwslc** [comment]
try this
```html
<Descriptions title="User Info">
  <Descriptions.Item label={<span style={{ color: "red" }}>UserName</span>}>
    <span style={{ color: "green" }}>Zhou Maomao</span>
  </Descriptions.Item>
</Descriptions>
```
