### ISSUE TITLE
基于rollup构建引入antd部分组件的react项目报错

### ISSUE THREAD

**Issue by Donaldgljh** [ant-design/ant-design#26221]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/tabs-cn/](https://ant-design.gitee.io/components/tabs-cn/)

### Steps to reproduce
引入antd的table或者tabs组件会报错，但是引入Button一些组件不会报错

### What is expected?
正常运行

### What is actually happening?
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Tabs$1`.
    at createFiberFromTypeAndProps (kgGraphApp.min.js:27386)
    at createFiberFromElement (kgGraphApp.min.js:27409)
    at reconcileSingleElement (kgGraphApp.min.js:17654)
    at reconcileChildFibers (kgGraphApp.min.js:17714)
    at reconcileChildren (kgGraphApp.min.js:20183)
    at updateHostComponent (kgGraphApp.min.js:20723)
    at beginWork (kgGraphApp.min.js:22048)
    at HTMLUnknownElement.callCallback (kgGraphApp.min.js:3609)
    at Object.invokeGuardedCallbackDev (kgGraphApp.min.js:3658)
    at invokeGuardedCallback (kgGraphApp.min.js:3713)

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | windows 10 x64 |
| Browser | Google Chrome 版本 84.0.4147.125（正式版本） （64 位） |

---
我的配置文件
package.json
{
  "name": "graph-app",
  "version": "1.0.0",
  "description": "graph-app with react and rollup",
  "main": "index.js",
  "author": "donaldlh",
  "license": "ISC",
  "scripts": {
    "start": "cross-env NODE_ENV=development && rollup -c -w",
    "build": "rimraf dist && cross-env NODE_ENV=production rollup -c",
    "product": "serve dist"
  },
  "dependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
  "devDependencies": {
    "@babel/core": "^7.11.1",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.11.0",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.11.0",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
    "@babel/runtime-corejs3": "^7.11.2",
    "@rollup/plugin-commonjs": "^14.0.0",
    "@rollup/plugin-html": "^0.2.0",
    "@rollup/plugin-node-resolve": "^8.4.0",
    "@rollup/plugin-replace": "^2.3.3",
    "antd": "4.5.1",
    "babel-eslint": "^10.1.0",
    "babel-plugin-import": "^1.13.0",
    "babel-plugin-react-require": "^3.1.3",
    "cross-env": "^7.0.2",
    "eslint-plugin-react": "^7.20.5",
    "rimraf": "^3.0.2",
    "rollup": "^2.23.1",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-css-porter": "^1.0.2",
    "rollup-plugin-eslint": "^7.0.0",
    "rollup-plugin-less": "^1.1.2",
    "rollup-plugin-livereload": "^1.3.0",
    "rollup-plugin-postcss": "^3.1.5",
    "rollup-plugin-scss": "^2.1.0",
    "rollup-plugin-serve": "^1.0.3",
    "rollup-plugin-terser": "^7.0.0",
    "serve": "^11.3.2"
  }
}

rollup配置文件
rollup.config.js
import resolve from "@rollup/plugin-node-resolve"; //编写的代码与依赖的第三方库进行合并
import babel from "rollup-plugin-babel"; //es6代码转换
import replace from "@rollup/plugin-replace";
import commonjs from "@rollup/plugin-commonjs"; //解决rollup.js无法识别CommonJS模块
import html from "@rollup/plugin-html";
import serve from "rollup-plugin-serve";
import livereload from "rollup-plugin-livereload";
import { eslint } from "rollup-plugin-eslint";
import { terser } from "rollup-plugin-terser";
import postcss from "rollup-plugin-postcss";

const isProd = process.env.NODE_ENV == "production"; // 环境 or 开发环境
const extensions = [".js", ".jsx"];

export default [
  {
    //入口文件
    input: "src/index.js",
    //输出文件
    output: [
      {
        file: "dist/kgGraphApp.min.js",
        format: "umd",
        name: "kgGraphApp",
      },
    ],
    //隐掉(!) this has been rewritten to undefined这个报错，自定义警告事件
    onwarn: function (warning) {
      if (warning.code === "THIS_IS_UNDEFINED") {
        return;
      }
    },
    plugins: [
      resolve({
        extensions,
      }),
      postcss({
        extensions: [".less", ".css"],
        use: [["less", { javascriptEnabled: true }]],
        extract: false,
      }),
      babel({
        babelrc: false,
        exclude: "node_modules/**",
        presets: ["@babel/preset-env", "@babel/preset-react"],
        plugins: [
          [
            "import",
            { libraryName: "antd", libraryDirectory: "es", style: true },
            "antd",
          ],
        ],
      }),
      html({
        fileName: "index.html",
        title: "kg-graph",
        template: ({ title }) => {
          return `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="utf-8">
        <title>${title}</title>
        <link rel="stylesheet" href="/index.css">
        </head>
        <body>
        <div id="root"></div>
        <script src="/kgGraphApp.min.js"></script>
      </body>
      </html>
      `;
        },
      }),
      commonjs({
        include: "node_modules/**",
      }),
      eslint({
        include: ["src/**"],
        exclude: ["node_modules/**"],
      }),
      replace({
        "process.env.NODE_ENV": JSON.stringify(
          isProd ? "production" : "development"
        ),
      }),
      isProd && terser(),
      !isProd &&
        serve({
          open: true, //打开浏览器
          host: "localhost",
          port: 3000,
          contentBase: ["dist"],
        }),
      !isProd &&
        livereload({
          watch: "dist",
        }),
    ],
  },
];

**Comment by Donaldgljh** [comment]
hello，repo:   https://github.com/Donaldgljh/rollup-app

**Comment by afc163** [comment]
I don't know how to resolve it, please help.

**Comment by Kermit-Xuan** [comment]
@Donaldgljh 可以给个最小复现的codesandbox 或 仓库链接么？

**Comment by afc163** [comment]
See https://github.com/Donaldgljh/rollup-app

**Comment by Donaldgljh** [comment]
> @Donaldgljh 可以给个最小复现的codesandbox 或 仓库链接么？

https://github.com/Donaldgljh/rollup-app 这个应该很小了吧，引入了antd的Tabs组件，当然Table组件也会出现这种情况

**Comment by Kermit-Xuan** [comment]
> > @Donaldgljh 可以给个最小复现的codesandbox 或 仓库链接么？
> 
> [Donaldgljh/rollup-app](https://github.com/Donaldgljh/rollup-app) 这个应该很小了吧，引入了antd的Tabs组件，当然Table组件也会出现这种情况

OK，不好意思，之前没看到

**Comment by Donaldgljh** [comment]
没事没事，麻烦您啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Kermit Xuan <notifications@github.com&gt;
发送时间: 2020年8月19日 11:02
收件人: ant-design/ant-design <ant-design@noreply.github.com&gt;
抄送: liang <1169194182@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[ant-design/ant-design] 基于rollup构建引入antd部分组件的react项目报错 (#26221)





   
@Donaldgljh 可以给个最小复现的codesandbox 或 仓库链接么？
  
Donaldgljh/rollup-app 这个应该很小了吧，引入了antd的Tabs组件，当然Table组件也会出现这种情况
  
OK，不好意思，之前没看到

**Comment by Kermit-Xuan** [comment]
昨晚上我调试了一下，好像是倒入icon组件的时候出错了，导入的是像 `{default: ..., esModule: true}` 这样的一个对象，而不是组件构造函数，感觉像是当成 `commonjs` 导入了，我对 rollup 不太熟，是不是需要什么插件？ @afc163

**Comment by megatunger** [comment]
@Donaldgljh  I also faced this issue too, since I upgraded to rollup 2. I downgraded and it worked again:

```
@rollup/plugin-commonjs": "^11.1.0",
"@rollup/plugin-node-resolve": "^7.1.3",
"rollup": "^1.27.4",
"rollup-plugin-copy": "^3.3.0",
"rollup-plugin-peer-deps-external": "^2.2.0",
"rollup-plugin-postcss": "^3.1.5",
"rollup-plugin-typescript2": "^0.27.0",
```

**Comment by Donaldgljh** [comment]
ok,thank you,it works. 

> @Donaldgljh I also faced this issue too, since I upgraded to rollup 2. I downgraded and it worked again:
> 
> ```
> "@rollup/plugin-commonjs": "^11.1.0",
> "@rollup/plugin-node-resolve": "^7.1.3",
> "rollup": "^1.27.4",
> "rollup-plugin-copy": "^3.3.0",
> "rollup-plugin-peer-deps-external": "^2.2.0",
> "rollup-plugin-postcss": "^3.1.5",
> "rollup-plugin-typescript2": "^0.27.0",
> ```

ok,thank you,it works.

**Comment by Donaldgljh** [comment]
> ok,thank you,it works.
> 
> > @Donaldgljh I also faced this issue too, since I upgraded to rollup 2. I downgraded and it worked again:
> > ```
> > "@rollup/plugin-commonjs": "^11.1.0",
> > "@rollup/plugin-node-resolve": "^7.1.3",
> > "rollup": "^1.27.4",
> > "rollup-plugin-copy": "^3.3.0",
> > "rollup-plugin-peer-deps-external": "^2.2.0",
> > "rollup-plugin-postcss": "^3.1.5",
> > "rollup-plugin-typescript2": "^0.27.0",
> > ```
> 
> ok,thank you,it works.

HI,I also try to upgrade to rollup 2.26.0 and rollup/plugin-commonjs 15.0.0  It works.
