### ISSUE TITLE
transefer穿梭框，显示搜索框，输入英文字母大小写无法匹配

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2622]
antd版本：0.12.X
是否新版组件解决了这个问题？

**Comment by benjycui** [comment]
duplicate: https://github.com/ant-design/ant-design/issues/2324

Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).
