### ISSUE TITLE
Npm package.json dependencies should be moved to peerDependencies

### ISSUE THREAD

**Issue by EugeneSnihovsky** [ant-design/ant-design#26227]
- [ x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
npm install antd

### What is expected?
When module is installed it should point out that it requires peer dependencies and usser should install it manually

### What is actually happening?
When module is installed it automatically install dependencies and if dependencies versions mismatch - it create node_modules subfolder in antd

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | MacOS 10.15.6 |
| Browser | Chrome |

---
Use dependencies instead of peerDependencies reduce flexibility and can break something. For example, I can't use antd in create-react-library development server because antd create its own node_modules with different react version and dev server failed with versions mismatch.

Sorry for missed minimal reproduction link. I think it will not help here

**Comment by afc163** [comment]
I don't think we should use `peerDependencies` instead of `dependencies`, feel free to fork antd and make your own pacakge.
