### ISSUE TITLE
React.createElement: type is invalid -- expected a string or a class/function but got: object

### ISSUE THREAD

**Issue by sam-chuang** [ant-design/ant-design#26226]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/sam-chuang/ant-design-snowpack-issue](https://github.com/sam-chuang/ant-design-snowpack-issue)

### Steps to reproduce
1. clone https://github.com/sam-chuang/ant-design-snowpack-issue
2. npm install & npm start
3. open http://localhost:8080/ on browser
4. open browser dev console

### What is expected?
Page console should not have any warning

Warning: React.createElement: type is invalid

### What is actually happening?
Page console shows multiple warning about React.createElement: type is invalid

Refer to screenshots here
https://sam-chuang.github.io/ant-design-snowpack-issue/
![issue](https://user-images.githubusercontent.com/33828310/90325335-e81ff980-dfac-11ea-9a43-637eaed25170.png)

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
snowpack problem trace in #26090
