### ISSUE TITLE
树形控件获取半选节点把我所有未选中的全选了这个Bug没人修复嘛吗？

### ISSUE THREAD

**Issue by GeorGeWzw** [ant-design/ant-design#26231]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/DestinyCore/destiny-admin-flow-umi](https://github.com/DestinyCore/destiny-admin-flow-umi)

### Steps to reproduce
const onCheck = (checkedKeys: any, e: { checked: boolean; checkedNodes: any; node: any; event: any; halfCheckedKeys: any }) => {
    let concat = checkedKeys.concat(e.halfCheckedKeys);
    console.log(concat)
    setTreeCheckedKeys(checkedKeys);
  };

使用concat  之后我未选中的子级也给我选中了

### What is expected?
我只要半选及全选的节点

### What is actually happening?
使用concat  之后我未选中的子级也给我选中了

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | windows |
| Browser | google  chrom 86  |

**Comment by afc163** [comment]
Please provide a minimal reproduce.
