### ISSUE TITLE
select 组件 

### ISSUE THREAD

**Issue by wangwangliu** [ant-design/ant-design#2623]
#### 本地环境

- antd 版本: antd 所有版本
- 操作系统及其版本：mac
- 浏览器及其版本: chrome 所有版本

#### 你做了什么？
 select 做筛选 
第一步: value值我已选取 弹出层已经消失 但我并没有点击页面其他地方 让select输入框处于blur态 ;
第二步：按快捷键enter 这个select 还会弹出来

#### 你期待的结果是：
select 不应和 快捷键 联系起来

#### 实际上的结果：
按快捷键enter 这个select 还会弹出来

**Comment by afc163** [comment]
这不算 bug 吧，focused 的组件响应快捷键还是合理的。

https://github.com/react-component/select/blob/59d1c8c3ae4f27977ccdbad62efad2047a5fe76b/src/Select.jsx#L178
