### ISSUE TITLE
when Modal.method's in pending status ,the Cancel button Should it be switched to a disabled state?

### ISSUE THREAD

**Issue by alexchen1875** [ant-design/ant-design#26236]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ez1k2)

### Steps to reproduce
when the ok button is pending stats,click cancle button

### What is expected?
when the ok button is pending stats,then cancel button should be disabled?or how can i  Achieve this effect?

### What is actually happening?
cancel button is work

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | latest |
| System | windows |
| Browser | chrome  latest |

---
then

**Comment by afc163** [comment]
No, cancel button should be always available to allow users exit current process.
