### ISSUE TITLE
如何阻止表单控件enter默认触发form的submit

### ISSUE THREAD

**Issue by victorykong** [ant-design/ant-design#26235]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
treeSelect 搜索功能开启后，回车将会触发 submit

### What does the proposed API look like?
Form 提供接口阻止或在 onFinish 时暴露 event 参数，允许判断异常提交情况

**Comment by victorykong** [comment]
目前 onFinish: (values)=> void，参数少了

**Comment by zombieJ** [comment]
form 中只要存在 submit 就会触发 form submit。如果不需要游览器原生的效果，直接不用原生的 submit 就行了：https://codesandbox.io/s/vibrant-leakey-d772e?file=/index.js
