### ISSUE TITLE
Table and Pagination errors when using snowpack

### ISSUE THREAD

**Issue by sam-chuang** [ant-design/ant-design#26237]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/sam-chuang/ant-design-table-pagination-snowpack-issue](https://github.com/sam-chuang/ant-design-table-pagination-snowpack-issue)

### Steps to reproduce
1. Clone https://github.com/sam-chuang/ant-design-table-pagination-snowpack-issue
2. npm install
3. npm start
4. open browser

### What is expected?
Show table and pagination correctly

### What is actually happening?
blank page, browser console shows errors

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
snowpack problem trace in #26090
