### ISSUE TITLE
The onDownload method is not triggered at the time of download.

### ISSUE THREAD

**Issue by huseyingoztok** [ant-design/ant-design#26238]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.nolink.com](https://www.nolink.com)

### Steps to reproduce
ss

### What is expected?
ss

### What is actually happening?
ss

| Environment | Info |
|---|---|
| antd | 4.1.5 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome |

---
Does the upload component have an event triggered at the moment the file is downloaded? I used the onDownloading method in your document, but this method was not triggered. If you can help or suggest a solution, I would be very happy.

**Comment by afc163** [comment]
Duplicate of #23737
