### ISSUE TITLE
Sider Menu icons don't link when sider is collapsed

### ISSUE THREAD

**Issue by jvrszk** [ant-design/ant-design#26239]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/l5y7l)

### Steps to reproduce
1- click expand/collapse trigger to collapse menu
2- (when menu is collapsed) click on icon of menu.item that has 1 level only (no sub-menu)

### What is expected?
Icon should behave as link to respective page

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 6.13.1 |
| System | Mac |
| Browser | Chrome |

**Comment by afc163** [comment]
I cannot understand  what`don't link` means.
