### ISSUE TITLE
TreeSelect TitleRender or title mapping in simpleMode

### ISSUE THREAD

**Issue by msotnikov** [ant-design/ant-design#26232]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Prevent redundant data preparing (like `array.map(el => ({...el, label: el.name}))` )

### What does the proposed API look like?
Expample here, please see the comments
https://codesandbox.io/s/reverent-dan-496hm?file=/index.js

**Comment by afc163** [comment]
see #24282
