### ISSUE TITLE
基于antd 4.x 封装组件库时报错 Invalid hook call.

### ISSUE THREAD

**Issue by yjzzcao** [ant-design/ant-design#26245]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
1. 利用lerna管理前端模块
```txt
root/
  ├── packages/
      ├── ui/
          ├── package.json
      ├── fe/
          ├── package.json
```
```json
// root/packages/ui/package.json
{
  ...
  "name": "my-ui",
  "version": "0.0.0",
  "peerDependencies": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
  ...
}
```
```json
// root/packages/fe/package.json
{
  ...
  "dependencies": {
    "my-ui": "^0.0.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
  ...
}
```
2. 运行项目时 报错 Invalid hook call.
3. 通过 npm ls react 发现 react 被 rc-picker 依赖进来
```bash
> root/packages/ui $ npm ls react
@gogoal/lts-probe-ui@0.0.0 /Users/caoyujian/workspace/lts-probe/packages/lts-probe-ui
└─┬ antd@4.5.4
  └─┬ rc-picker@1.15.3
    └── react@16.13.1 
```

### What is expected?
rc-picker 中的 react 依赖从 dependencies 移动至 devDependencies

### What is actually happening?
运行项目时 报错 Invalid hook call.

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | ^16.9.0 |
| System | Mac |
| Browser | Chrome latest |

**Comment by zombieJ** [comment]
你的库自行依赖一下 React。
ref: https://docs.npmjs.com/files/package.json#peerdependencies

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/picker/releases/tag/v1.15.4

**Comment by WenHua39** [comment]
这个问题我也遇到了，正常打包一个react17.0.2的npm包，发布之后 ，宿主引入没有问题，但是只要把antd4.x版本引入进来，不管是npm link 还是 publish  ，宿主引入这个包就会报错：
### Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

以下是我的package.json的依赖版本

"dependencies": {
        "@ant-design/icons": "^4.6.3",
        "@ant-design/pro-form": "^1.42.0",
        "@ant-design/pro-layout": "^6.5.0",
        "@ant-design/pro-table": "^2.49.0"
    },
    "devDependencies": {
        "@babel/core": "^7.2.2",
        "@babel/plugin-proposal-class-properties": "^7.0.0",
        "@babel/preset-env": "7.2.3",
        "@babel/preset-react": "7.0.0",
        "@types/react": "^17.0.0",
        "@types/react-dom": "^17.0.0",
        "antd": "^4.16.13",
        "babel-loader": "8.0.5",
        "babel-plugin-import": "^1.13.3",
        "clean-webpack-plugin": "^4.0.0",
        "css-loader": "0.28.9",
        "file-loader": "^6.2.0",
        "html-webpack-plugin": "^4.5.1",
        "less": "^3.11.1",
        "less-loader": "^5.0.0",
        "mini-css-extract-plugin": "^2.4.4",
        "react": "^17.0.2",
        "react-dom": "^17.0.2",
        "style-loader": "0.19.1",
        "typescript": "^4.4.4",
        "url-loader": "^4.1.1",
        "webpack": "^5.18.0",
        "webpack-cli": "^3.3.12",
        "webpack-dev-server": "^3.11.2",
        "webpack-node-externals": "1.6.0"
    },
    "peerDependencies": {
        "antd": "4.x",
        "react": ">=16.9.0",
        "react-dom": ">=16.9.0"
    }

**Comment by gaomAndximi** [comment]
> 这个问题我也遇到了，正常打包一个react17.0.2的npm包，发布之后 ，宿主引入没有问题，但是只要把antd4.x版本引入进来，不管是npm link 还是 publish ，宿主引入这个包就会报错：
> 
> ### Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> 
> 应该是打包姿势的问题，解决了

请问怎么解决的？
