### ISSUE TITLE
Loading spinner for Statistic while fetching data from async functions

### ISSUE THREAD

**Issue by FrozenIce0617** [ant-design/ant-design#26248]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If we get values from async functions, we have to show loading spinner while fetching data.

### What does the proposed API look like?
It would be great if the `value` props accept `ReactNode` or `loading` props for the `Statistic` component.

**Comment by zombieJ** [comment]
Why not wrapper Statistic with Spin instead of put value with Spin?

**Comment by FrozenIce0617** [comment]
I need to show skeleton for only `value`, not for the whole `Statistic` component.

**Comment by zombieJ** [comment]
PR is welcome

**Comment by appleshell** [comment]
I‘m trying to resolve it.
