### ISSUE TITLE
Ability to reset all Custom Filters within a Table component (Feature Request)

### ISSUE THREAD

**Issue by beckettkev** [ant-design/ant-design#26247]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-custom-filter-panel](https://ant.design/components/table/#components-table-demo-custom-filter-panel)

### Steps to reproduce
Implement the code shown on the table component custom filter panel.
Add a new global button outside the table object.
Try and get it to reset any active custom filters that are currently applied

### What is expected?
To be able to globally reset the custom filters from a button (not having to go into each one and click the reset button). This doesn't look possible due to the way the onReset methods are not callable externally and the state is encapsulated.

### What is actually happening?
You can reset each column filter, one by one, using the drop down panel, but there is no way to attach or add a global button that can reset all of the custom filters.

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | latest |
| System | Windows |
| Browser | Chrome |

---
Happy to build this myself if the relevant methods are exposed.

**Comment by zombieJ** [comment]
Use control mode.

https://ant.design/components/table-cn/#components-table-demo-reset-filter
