### ISSUE TITLE
Select Demo中的search box,去掉icon遇到难题

### ISSUE THREAD

**Issue by xieyihao** [ant-design/ant-design#2624]
#### 本地环境
Node版本：v4.4.7
npm版本：3.10.5

- antd 版本:v1.7.0
- 操作系统及其版本：Microsoft Windows [版本 10.0.10586]
- 浏览器及其版本:Chrome 版本 52.0.2743.82 m

#### 你做了什么？
根据Demo <a href="http://ant.design/components/select/#components-select-demo-search-box" >components-select-demo-search-box</a>
![image](https://cloud.githubusercontent.com/assets/12508868/17429918/f599d71e-5b23-11e6-92cd-3d9fecbe42ae.png)

我尝试去掉搜索icon，可以隐藏后直接样式乱了
```
render(){
  return(
    <div className="ant-search-input-wrapper" >
        <Input.Group className={searchCls}>
          <Select
            combobox
            value={this.state.value}
            placeholder={placeholder}
          >
            {optionItems}
          </Select>
-          <div className="ant-input-group-wrap">
-            <Button className={btnCls} onClick={this.handleSubmit}>
-              <Icon type="search" />
-            </Button>
-          </div>
        </Input.Group>
      </div>
 )  }
```

#### 你期待的结果是：
保持原来的样式，右边的icon去掉

#### 实际上的结果：
隐藏后直接样式乱了,后面的元素遮住了输入框。
![image](https://cloud.githubusercontent.com/assets/12508868/17429874/ba0cf33e-5b23-11e6-8da2-6cd4fb9a2c64.png)

**Comment by xieyihao** [comment]
使用了Input Group 的结构、样式好复杂，不清晰，能介绍下是怎么布局的吗？讲下思路

**Comment by afc163** [comment]
`Input.Group` 也去掉就行了。
