### ISSUE TITLE
RangePicker在未设置默认值的前提下，首次渲染后首次点击，为什么会出现默认值？再次点击又没有了？

### ISSUE THREAD

**Issue by liyswei** [ant-design/ant-design#26241]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jmfj1?file=/index.js)

### Steps to reproduce
在预览界面渲染后，点击RangePicker组件的开始时间（或者结束时间）

### What is expected?
开始时间输入框（结束时间输入框）不出现默认值

### What is actually happening?
开始时间输入框（结束时间输入框）出现默认值，而且该默认值不是当天日期，无法理解是怎么算出来的

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | macOS 10.15.5 |
| Browser | chrome 84.0.4147.125 |

---
这个问题还是偶发性的，多刷新页面操作几次发现，是大概3次出现2次的情况

**Comment by liyswei** [comment]
codesandbox ：https://codesandbox.io/s/antd-reproduction-template-forked-jmfj1?file=/index.js

**Comment by 07akioni** [comment]
> codesandbox ：https://codesandbox.io/s/antd-reproduction-template-forked-jmfj1?file=/index.js
链接内容不符

**Comment by liyswei** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-v14tp?file=/index.js

> > codesandbox ：https://codesandbox.io/s/antd-reproduction-template-forked-jmfj1?file=/index.js
> > 链接内容不符

https://codesandbox.io/s/antd-reproduction-template-forked-v14tp?file=/index.js

麻烦再看一下，我发现是RangePicker如果有一个兄弟节点在它前面就容易出现这个问题，如果是唯一节点，好像就不会出现问题

**Comment by flyerH** [comment]
> > > codesandbox ：https://codesandbox.io/s/antd-reproduction-template-forked-jmfj1?file=/index.js
> > > 链接内容不符
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-v14tp?file=/index.js
> 
> 麻烦再看一下，codesandbox原先的例子这个问题时有时无的，我改了一下，能看到这个问题。在点击日期输入框的时候，出现灰色的日期值，鼠标移动一点点，这个输入框又马上清空了

@afc163 麻烦再看看这个问题😉

**Comment by Kermit-Xuan** [comment]
我知道什么问题了？应该是 https://github.com/ant-design/ant-design/pull/25826 这里改动导致的

**Comment by Kermit-Xuan** [comment]
@zombieJ 看看这个问题，应该和 hover 时候设置 placeholder 有关。发现在首次打开面板的时候，面板还没打开完成就触发了 hover 事件，这是如果鼠标箭头如果正好经过面板，就会导致 placeholder 会设置错误。

**Comment by zombieJ** [comment]
> @zombieJ 看看这个问题，应该和 hover 时候设置 placeholder 有关。发现在首次打开面板的时候，面板还没打开完成就触发了 hover 事件，这是如果鼠标箭头如果正好经过面板，就会导致 placeholder 会设置错误。

有点怪异，它 hover 后应该还会触发一次 leave 事件？

**Comment by Kermit-Xuan** [comment]
触发 leave 事件的话用户也是有感知的，会闪一下，感觉正确的做法是面板打开后才开始监听hover事件

**Comment by zombieJ** [comment]
嗯，不过其实现在这个也是打开了面板遇到的问题。感觉一个 workaround 就是弄个 timeout 延迟一下。
