### ISSUE TITLE
Directory Tree  When scrolling is triggered in a child component, the parent component also scrolls

### ISSUE THREAD

**Issue by superw-123** [ant-design/ant-design#26246]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ougvk?file=/index.js)

### Steps to reproduce
在codesanbox中没有复现，在本地由4.4.0升级到4.5.4后（这个升级是为了解决DirectoryTree滚动时节点丢失的问题即#26129）
点击树节点，弹出popover，滚动popover中的内容，树上的节点跟着一起滚动
```
<DirectoryTree
    switcherIcon={<DownOutlined />}
    showIcon={false}
    onExpand={onExpand}
    expandedKeys={expandedKeys}
    autoExpandParent={autoExpandParent}
    height={treeHeight}
    treeData={renderTreeNodes(treeData)} />

const renderTreeNodes = data => (
    data.map(item => {
        const {title, titleCN, tree_id, is_table, children} = item;
        if (children) {
            return {title: title, key: tree_id, children: renderTreeNodes(children)};
        } else {
            return {title: onCustomLabel(item), key: tree_id};
        }
    })
);

const onCustomLabel = item => {
	 <span onClick={() => this.onSelect(item)}>
        <Popover content={<FieldMenu {...fieldProps} />}
            title={'test'}
            placement="rightTop"
            trigger="click"
            visible={visible}
            onVisibleChange={handleVisible}
            overlayClassName={Styles['drag-table-pop']}
        >
              
            <span>
                {item.title}
            </span>
        </Popover>
     </span>
}
```

### What is expected?
滚动时不要穿透

### What is actually happening?
滚动popover子组件里的内容，Directory tree父组件里的树节点也滚动

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12.0 |
| System | mac catalina 10.15.5 |
| Browser | 84.0.4147.125（正式版本） （64 位） |

**Comment by afc163** [comment]
You can provide a minimal GitHub repository if it cannot reproduce in codesandbox.

**Comment by superw-123** [comment]
复现的示例，下载后，npm i，点击【点我点我点我】的节点，滚动鼠标，即可复现
https://github.com/superw-123/super/blob/master/dva-quickstart.zip

**Comment by superw-123** [comment]
> You can provide a minimal GitHub repository if it cannot reproduce in codesandbox.



> Hello @superw-123. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @superw-123, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

复现的示例，下载后，npm i，点击【点我点我点我】的节点，滚动鼠标，即可复现
https://github.com/superw-123/super/blob/master/dva-quickstart.zip

**Comment by afc163** [comment]
Please provide a **minimal** reproduce instead of your whole project.

**Comment by superw-123** [comment]
> minimal

去掉codesanbox中的iframe就会复现
https://codesandbox.io/s/antd-reproduction-template-forked-f7buj?file=/index.js

**Comment by afc163** [comment]
没有重现你描述的问题。

![1](https://user-images.githubusercontent.com/507615/90497311-895bab00-e179-11ea-8c57-18b336994cfc.gif)

**Comment by flyaaaaaaaa** [comment]
对这棵进行什么操作会使带有这两个类名ant-tree-list-scrollbar，ant-tree-list-holder的元素丢失，我的项目中也出现了这个问题，这两个属性不存在，popover中出现滚动时候，就出现了滚动穿透的现象
