### ISSUE TITLE
Using FormList inside a FormList doesn't work as expected when having two list items in the child list

### ISSUE THREAD

**Issue by osamasayed** [ant-design/ant-design#26249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formlist-bug-reproduction-m7ry7)

### Steps to reproduce
1. Click on Add Performance Bonus button.
2. Input a type, value, and year.
3. Click on Add a year button.
4. Input Year 1's value e.g. 120
5. Click on Add a year button.
6. Input Year 2's value e.g. 430

### What is expected?
1. Year 1's value will be 120.
2. Year 2's value will be 430.
3. `vestingSchedule` should be there when submitting the form values.

### What is actually happening?
1. Year 1's value goes away.
2. Year 2's value is 430.
3. `vestingSchedule` is not there when submitting the form values at all.

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.12.0 |
| System | Mac Os |
| Browser | Google Chrome 84.0.4147.125 |

**Comment by zombieJ** [comment]
FormList is also a field that you should pass name also: https://codesandbox.io/s/formlist-bug-reproduction-forked-selrp?file=/src/App.js
