### ISSUE TITLE
[需求]Typography的复制文本功能,手动调用

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#26258]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前文字右边带图标的不够友好.
 
想在文本外套一个Dropdown右键菜单, 点击复制后,手动将选择的文字复制到剪切板中.

### What does the proposed API look like?
import { Typography, message } from 'antd';
const { Copyable ,clipboard} = Typography;

const copy = (text)=>{
  // do others ...
  clipboard(text);
}

<Copyable  
text="要复制的内容123' // text为空,默认为子元素内容
onClick={(text)=>{copy(text)}} 
onSuccess={()=>{message. success('复制成功')}}
onFail={()=>{message.fail('当前浏览器不支持,请手动复制')}}
>
点击复制
</Copyable>

**Comment by afc163** [comment]
这种需求可以直接使用 https://www.npmjs.com/package/copy-to-clipboard
