### ISSUE TITLE
table onSelect更改selectedRowKeys 无效

### ISSUE THREAD

**Issue by jayguojianhai** [ant-design/ant-design#26256]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/jayguojianhai/umi3](https://github.com/jayguojianhai/umi3)

### Steps to reproduce
直接点击对应的checkbox

### What is expected?
期望选中

### What is actually happening?
没有选中

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | macos Mojave 10.14.4  |
| Browser | Google Chrome 81.0.4044.138（正式版本） （64 位）） |

---
为什么不用onChange，是因为需要处理上下级逻辑，最小复现demo里面没有体现这块，比如我勾选了一个子节点就应该把他父节点勾上。所有不能用onchange

**Comment by zombieJ** [comment]
```diff
--- selectedRowKeys.push(record.id);
+++ selectedRowKeys = [...selectedRowKeys, record.id];
```

**Comment by jayguojianhai** [comment]
@zombieJ 我不明白为什么要这么写？

**Comment by yoyo837** [comment]
看一下react文档，immutable的问题

**Comment by jayguojianhai** [comment]
好吧尴尬，antd3的时候没有问题的，升级到4才遇到这个问题

**Comment by zombieJ** [comment]
v3 时期兼容旧版 React15 所以是全量刷新，到 Hooks 时代，mutable data React 是不会更新的。
