### ISSUE TITLE
Select下拉框组件加上disabled属性后不能自动失去焦点

### ISSUE THREAD

**Issue by yingxiaoqiang** [ant-design/ant-design#26253]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/restless-voice-6umzg?file=/index.js)

### Steps to reproduce
1. 点击下拉框，任选一个值，disabled属性值变为true，下拉框变为不可编辑
2. 5秒钟之后disabled属性值变为false，此时点击下拉框外的任何地方，下拉框不会自动失去焦点
3. 需要重新点击以下下拉框，然后再点击下拉框外的地方，下拉框才会失去焦点

### What is expected?
下拉框加上disabled属性不会影响自动失去焦点

### What is actually happening?
disabled属性从true变成false时，影响了下拉框自动失去焦点

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12.0 |
| System | macos  |
| Browser | chrome 84.0.4147.125 |

---
不使用disabled属性不会有以上问题

**Comment by xrkffgg** [comment]
@07akioni 你在改这个了吗？

**Comment by 07akioni** [comment]
> @07akioni 你在改这个了吗？

没有呢，改的话我会打个 working tag
