### ISSUE TITLE
form.setFields with Input tag inside div does not work

### ISSUE THREAD

**Issue by hejaziak** [ant-design/ant-design#26250]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-tnr7e?file=/index.js)

### Steps to reproduce
Just check the first form.setFields and the second one

### What is expected?
The first form.setFields should update the input value

### What is actually happening?
the first form.setFields does not change the input value

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12 |
| System | mac OSX 10.15.3 |
| Browser | Chrome version 80 |

**Comment by afc163** [comment]
`Form.Item` should always wrap Input directly.
