### ISSUE TITLE
table scroll:{x:...} 从数据为空=>非空状态时table-header和table-body会不对齐

### ISSUE THREAD

**Issue by yexingxia** [ant-design/ant-design#2625]
#### 本地环境

- antd 版本:  1.7.0
- 操作系统及其版本：mac
- 浏览器及其版本:  chrome 47

#### 你做了什么？
引入antd的Table放查询结果，使用了scroll:{x: ...}来显示横向滚动条
过程以下面的demo为例：用数据A渲染表格，将表格的横向滚动条拉到最右，然后点击RELOAD按钮触发一次数据为空的重绘（显示暂无数据），然后再点击RELOAD按钮用数据A触发一次重绘，表头和表体的数据会出现不对齐的现象，表头貌似还保留着上一次的scrollLeft

#### 你期待的结果是：
希望当表格为空时，表头和表体的scrollLeft都能重置为0

#### 实际上的结果：
当表格为空时，表头或表体的scrollLeft会保留之前的值

#### 可重现的在线演示
http://codepen.io/wmf/pen/rLqYrj?editors=001

**Comment by afc163** [comment]
感谢反馈

**Comment by yexingxia** [comment]
👍
