### ISSUE TITLE
有 autoSize 属性的 TextArea 会再 body 增加一个 textarea

### ISSUE THREAD

**Issue by tlessss** [ant-design/ant-design#26257]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/#Input.TextArea](https://ant.design/components/input-cn/#Input.TextArea)

### Steps to reproduce
...

### What is expected?
为啥要加这个textarea

### What is actually happening?
多了一个textarea

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | ^16.9.0 |
| System | mac |
| Browser | chrome 84.0.4147.125 |

**Comment by 07akioni** [comment]
我感觉可能是测量文字高度用的

**Comment by 07akioni** [comment]
https://github.com/react-component/textarea/blob/master/src/calculateNodeHeight.tsx
