### ISSUE TITLE
Select change the scroll bar style

### ISSUE THREAD

**Issue by cnLGMing** [ant-design/ant-design#26268]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/reverent-almeida-37h7f)

### Steps to reproduce
see link

### What is expected?
I need to override the style of the Select scroll bar. I have implemented Table and Cascader components, but the Select not

### What is actually happening?
I did not find the style name

| Environment | Info |
|---|---|
| antd | 4.5.1 |
| React | 16.12.0 |
| System | macOS 10.15.6 |
| Browser | Edge 83.0.478.56  |

**Comment by afc163** [comment]
https://codesandbox.io/s/clever-haze-ug5vg?file=/index.css

create-react-app don't support less defaultly.

**Comment by martingsix** [comment]
Have you come to a solution on this? Still struggling to find out how to do it :/
