### ISSUE TITLE
Table组件设置scroll.y无效

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#2626]
#### 本地环境

- antd 版本: 1.7.0
- 操作系统及其版本：window10
- 浏览器及其版本:  54.0.2816.0 dev-m

#### 你做了什么？

使用Table，设置了scroll={{y: 1000}}

#### 你期待的结果是：

Table滚动区域高度变为1000

#### 实际上的结果：
Table滚动区域的高度没有变化

#### 可重现的在线演示

http://codepen.io/infeng/pen/PzyOAk/?editors=001

**Comment by afc163** [comment]
数据量不够，scroll.y 实际上是 `max-height`。

https://github.com/react-component/table/issues/65

**Comment by infeng** [comment]
是我理解错了，我是想设置Table的高度，在之前的版本中，设置了scroll.y之后Table的高度是会变的，现在不行了。

**Comment by infeng** [comment]
我想达到的效果是，Table没有数据的时候，Table内容区域的高度可以自定义

**Comment by afc163** [comment]
直接设置 bodyStyle 就可以了。

**Comment by afc163** [comment]
诶？bodyStyle 这个属性在文档里丢了。

**Comment by infeng** [comment]
之前的版本scroll.y是设置height，我现在才看到改成了max-height，不怪得我更新到1.7.0之后就不行了，设置bodyState可以实现，感谢！（文档里确实是没了bodyStyle属性o(^▽^)o）
