### ISSUE TITLE
antd form rules add `validator` will Invalidation of `required`

### ISSUE THREAD

**Issue by victorykong** [ant-design/ant-design#26264]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If both required and validator ES2015 abbreviations exist, then required is invalid. The Validator is a custom validator so will it invalidate other restrictions like that? I finally rewrote it as `[ {required:true}, ()=> Promise ]` and it's in effect

### What does the proposed API look like?
This can be written directly as follows: `[ { required: true, validator: ()=> Promise } ]`

**Comment by victorykong** [comment]
Invalidation：
<img width="755" alt="image" src="https://user-images.githubusercontent.com/50655436/90492348-adb48900-e173-11ea-9ee6-36844e9e76f4.png">

**Comment by afc163** [comment]
有了 validator 以后，其他 rules 配置都会失效。
