### ISSUE TITLE
Write the Form in the tabBarExtraContent property of the Tabs component. Entering a Chinese symbol triggers the onChange event of the Tabs component.

### ISSUE THREAD

**Issue by sweetyangtian** [ant-design/ant-design#26261]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/8qu22)

### Steps to reproduce
点击【新建】按钮，出现弹框，输入中文符号，如 【】，可看到Tabs的onChange事件被触发。
Click the button, and the modal id show.  Enter Chinese symbols, such as "【】", and you will see the onChange event in Tabs being triggered.

### What is expected?
期望不触发Tabs的onChange事件。
The onChange event in Tabs is not expected to trigger.

### What is actually happening?
the onChange event in Tabs being triggered.

| Environment | Info |
|---|---|
| antd | 3.26.17 |
| React | 15 |
| System | windows10-18363 |
| Browser | Chrome79 |

**Comment by afc163** [comment]
I cannot reproduce.

**Comment by sweetyangtian** [comment]
> I cannot reproduce.

访问我提供的代码链接也不能复现吗？要使用Windows系统

**Comment by sweetyangtian** [comment]
> I cannot reproduce.

访问我提供的代码链接也不能复现吗？要使用Windows系统

**Comment by afc163** [comment]
3.x 不维护了，你可以试试 4.x，我这里暂时找不到 windows 系统。
