### ISSUE TITLE
Responsive Padding & Margin support

### ISSUE THREAD

**Issue by JChristopher9** [ant-design/ant-design#26276]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Support for responsive padding & margins like Bootstrap Or Tailwind

### What does the proposed API look like?
for example
<Content padding={{ md: '10px', lg:'20px' }}> </Content>

**Comment by afc163** [comment]
You can use Tailwind with antd.

This issue is merged to https://github.com/ant-design/ant-design/issues/24033
