### ISSUE TITLE
多个<>

### ISSUE THREAD

**Issue by yuchengx** [ant-design/ant-design#26273]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
多个<>

### What is expected?
正常

### What is actually happening?
没有<>

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | react |
| System | window |
| Browser | 谷歌 |

![image](https://user-images.githubusercontent.com/32560819/90533214-c42a0700-e1aa-11ea-8d2c-18af14514a59.png)
使用Tabs

**Comment by xrkffgg** [comment]
Check your code.

**Comment by yuchengx** [comment]
使用tabs 组件时候有<&gt;在上面




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2020年8月19日(星期三) 上午9:17
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "莫道"<281907117@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 多个<&gt; (#26273)





 
Check your code.

**Comment by xrkffgg** [comment]
请使用 codesandbox 提供复现。
