### ISSUE TITLE
Table's onChange not triggered when filters cleared 

### ISSUE THREAD

**Issue by zguillen** [ant-design/ant-design#26277]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/4mo9w?file=/index.js:678-684)

### Steps to reproduce
using the demo https://ant.design/components/table/#components-table-demo-reset-filter  in code sandbox. 
1. add a filter, click OK
2. note console prints out, "Various parameters..." from handleChange callback
3. click "Clear Filters" button and note nothing printed in console, handleChange callback was not called

### What is expected?
table's onChange callback should be called when filters are cleared outside from filter dropdown's reset button.

### What is actually happening?
table's onChange callback is not called when filters are cleared outside of the filter dropdown.  (i.e. "Clear Filters" button on https://ant.design/components/table/#components-table-demo-reset-filter 

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.9 |
| System | Windows 10 |
| Browser | Chrome 84 |

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/90581505-003a8780-e1fe-11ea-9487-3320bb017d20.png)

---
I use your Demo. And when I click reset button, it has console.

**Comment by flyerH** [comment]
![image](https://user-images.githubusercontent.com/17452527/90593495-a1373b80-e21a-11ea-80d8-936a35ac2b45.png)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/19415#issuecomment-546182503
