### ISSUE TITLE
Form/Select组件，当Option较多时，反复点击展开会导致渲染问题

### ISSUE THREAD

**Issue by 4tj** [ant-design/ant-design#26289]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/compassionate-sky-3qevq)

### Steps to reproduce
当Option较长时，选中末尾的Option后，反复点击触发展开收起Option就会发现渲染不出来。

步骤：
1. 点击 Select 组件展开 Option 列表，选择第 98 个 Option
2. 再次点击这个 Select 组件，发现 Option 渲染不出来（容器框有展开）

（如果再次点击时正常，反复多点几次展开收起这个操作就会复现。

### What is expected?
正常渲染，不管Option多长，再说100个也不长，实际生产复现30多个就会。

### What is actually happening?
渲染框白屏，触发scroll就好了

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12.0 |
| System | macOS |
| Browser | Chrome |

**Comment by Kermit-Xuan** [comment]
应该是这个： https://github.com/ant-design/ant-design/issues/26116

**Comment by 4tj** [comment]
![ezgif-2-5c3b958dc9c3](https://user-images.githubusercontent.com/1736244/90616803-7bbd2880-e240-11ea-896b-613b44fc39d1.gif)

**Comment by Kermit-Xuan** [comment]
就是和那个issue的原因一样，虚拟列表的问题，你把 `virtual` 设为 `false` 应该就好了

**Comment by 4tj** [comment]
> 就是和那个issue的原因一样，虚拟列表的问题，你把 `virtual` 设为 `false` 应该就好了

确实可以，列表超长又会很卡，不能关这个功能。等修复后release吧
