### ISSUE TITLE
当前ANTD版本是否提供单独构建文件

### ISSUE THREAD

**Issue by wuhaih** [ant-design/ant-design#2628]
antd版本：1.7
官方说明，单独构建版本在使用0.12版本，不知道1.0以上版本是否可行

**Comment by afc163** [comment]
...

http://ant.design/docs/react/install#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5

**Comment by wuhaih** [comment]
新版本怎么构建的，发现构建出来有问题，能否提供demo

**Comment by allenliu6** [comment]
所以链接打不开了？

**Comment by afc163** [comment]
https://ant.design/docs/react/introduce-cn#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%BC%95%E5%85%A5
