### ISSUE TITLE
 Failed to open the example of the official website in codesandbox

### ISSUE THREAD

**Issue by iwits** [ant-design/ant-design#26283]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eiuon?file=/package.json)

### Steps to reproduce
open a example which in the official website ，they are failed。

### What is expected?
Examples are available

### What is actually happening?
failed 

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12.0 |
| System | maxos |
| Browser | chrome |

**Comment by iwits** [comment]
![image](https://user-images.githubusercontent.com/15440081/90601444-ce8be580-e22a-11ea-94d2-486db6903396.png)

**Comment by afc163** [comment]
https://twitter.com/AntDesignUI/status/1295976505038663681

**Comment by afc163** [comment]
@CompuIves @siddharthkp @SaraVieira

**Comment by CompuIves** [comment]
Looking into this!

**Comment by CompuIves** [comment]
Fix should be live within 20 min!

**Comment by CompuIves** [comment]
Fix is live! Apologies for the regression here, our testing suite didn't catch this change since there was a server side component involved. I'll take a look today on how we can prevent this from happening again!

**Comment by afc163** [comment]
@CompuIves Thx for quick response and the fix, codesandbox is one of my favourite products~
