### ISSUE TITLE
Copy and Paste images to upload form

### ISSUE THREAD

**Issue by minhthien309** [ant-design/ant-design#26284]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to use both copy/paste images from clipboard and choosing images dialog to upload file. But i can only use choose images dialog (image below)

![image](https://user-images.githubusercontent.com/9354317/90606385-f595e780-e229-11ea-8cf6-4877c48edc45.png)

### What does the proposed API look like?
Copy and Paste images to upload form

**Comment by afc163** [comment]
See https://github.com/PaulaSham/docs/issues/2

**Comment by minhthien309** [comment]
Thank you
