### ISSUE TITLE
InputNumber incorrect step behavior

### ISSUE THREAD

**Issue by leanniby** [ant-design/ant-design#26285]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/numberinput-incorrect-step-behavior-fstgr?file=/index.js)

### Steps to reproduce
- Focus input element
- Enter any number (example "1")
- No changing focus, click up step button

### What is expected?
Increment value after click step button ("2", "3" ...)

### What is actually happening?
Show value is changed "2", "1",  "1", "2", "1", "1",...

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12  |
| System | any |
| Browser | any  |

---
The current behavior is reproduced when used redux and redux-saga

**Comment by xrkffgg** [comment]
PR welcome~

**Comment by prasanthLalapeta** [comment]
Any updates on this issue ?

**Comment by n0ruSh** [comment]
@xrkffgg It can be consistently reproduced in the code sample @leanniby provides. I took a quick look and It's related to the `setValue` is called in asynchronous way (i.e inside a `setTimeout`)

**Comment by xrkffgg** [comment]
> @xrkffgg It can be consistently reproduced in the code sample @leanniby provides. I took a quick look and It's related to the `setValue` is called in asynchronous way (i.e inside a `setTimeout`)

PR welcome ~

**Comment by chiptoe** [comment]
@netochaves any updates?

**Comment by zombieJ** [comment]
seems not a bug in v5. Closed: https://stackblitz.com/edit/react-4jfgfq?file=demo.tsx
