### ISSUE TITLE
Footer and Title slots for Drawer component

### ISSUE THREAD

**Issue by PavelEfimenko** [ant-design/ant-design#26288]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
My case

```
<Drawer title="here" footer={<Button loading={dataLoading}>Save</Button>}>
       <DrawerContent/>
</Drawer>
```

For example some data i get on my child component `<DrawerContent>`, and i cant ease put this data into `title` or `footer`, it could be dataLoading or username

### What does the proposed API look like?
```
<Drawer>
  <Drawer.Title>This is a drawer title</Drawer.Title>
  <Drawer.Footer>This is a drawer footer</Drawer.Footer>
</Drawer>
```
or
```
const { Title, Footer } = Drawer;

<Drawer>
  <Title>This is a drawer title</Title>
  <Footer>This is a drawer footer</Footer>
</Drawer>
```

**Comment by afc163** [comment]
I prefer `title` and `footer` props, which same as Modal.
