### ISSUE TITLE
JavaScript evaluation error: 'ReferenceError: colorPalette is not defined' after do getThemeVariables({ dark: true }) in craco.config.js

### ISSUE THREAD

**Issue by Y-lonelY** [ant-design/ant-design#26290]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/Y-lonelY/grow-fe](https://github.com/Y-lonelY/grow-fe)

### Steps to reproduce
1. yarn install
2. yarn start

### What is expected?
normal running

### What is actually happening?
Failed to compile.

./src/App.less (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-8-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-8-3!./node_modules/less-loader/dist/cjs.js??ref--6-oneOf-8-4!./src/App.less)

.antTreeFn(@tree-prefix-cls);
^
Error evaluating function `color`: JavaScript evaluation error: 'ReferenceError: colorPalette is not defined'
      Error in /Users/yango/react/grow-fe/node_modules/antd/lib/tree/style/index.less (line 12, column 0)

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | ^16.13.1 |
| System | Mac OS Catalina 10.15.6 |
| Browser | Google Chrome 84.0.4147.125 |

**Comment by afc163** [comment]
@AshoneA @ycjcl868 暗色主题的用法有点问题。

```diff
const CracoLessPlugin = require('craco-less');
const { getThemeVariables } = require('antd/dist/theme');

module.exports = {
  plugins: [
    {
      plugin: CracoLessPlugin,
      loader: "less-loader",
      options: {
        lessLoaderOptions: {
          lessOptions: {
-           modifyVars: getThemeVariables({ dark: true }), // 去掉这个就好了。
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
};
```

**Comment by Y-lonelY** [comment]
> @AshoneA @ycjcl868 暗色主题的用法有点问题。
> 
> ```diff
> const CracoLessPlugin = require('craco-less');
> const { getThemeVariables } = require('antd/dist/theme');
> 
> module.exports = {
>   plugins: [
>     {
>       plugin: CracoLessPlugin,
>       loader: "less-loader",
>       options: {
>         lessLoaderOptions: {
>           lessOptions: {
> -           modifyVars: getThemeVariables({ dark: true }), // 去掉这个就好了。
>             javascriptEnabled: true,
>           },
>         },
>       },
>     },
>   ],
> };
> ```

去掉之后 dark 模式就不生效了，貌似是因为解析 `.colorPaletteMixin()` at /node_modules/antd/lib/style/color/colorPalette.less 错误导致

**Comment by llwslc** [comment]
这个用法的例子有问题, 在 index.js 直接 `import 'antd/dist/antd.dark.less';` 就可以了

**Comment by Y-lonelY** [comment]
> 这个用法的例子有问题, 在 index.js 直接 `import 'antd/dist/antd.dark.less';` 就可以了

你说的方式我理解，但是这样存在问题就是全局引用之后，**通过此方式不能同时配置两种及以上主题**，[link](https://ant.design/docs/react/customize-theme-cn)，我希望达到的效果是通过 `webpack` 来按需加载😟

**Comment by llwslc** [comment]
这个接口 `getThemeVariables(options = {})`  是不是应该扩展成 `getThemeVariables(options = {}, extra = {})` 把以下这两种情况合并?

```js
modifyVars: getThemeVariables({
  dark: true, // 开启暗黑模式
  compact: true, // 开启紧凑模式
}),
```

```js
modifyVars: {
  'primary-color': '#1DA57A',
  'link-color': '#1DA57A',
  'border-radius-base': '2px',
},
```

**Comment by AshoneA** [comment]
> 这个接口 `getThemeVariables(options = {})` 是不是应该扩展成 `getThemeVariables(options = {}, extra = {})` 把以下这两种情况合并?
> 
> ```js
> modifyVars: getThemeVariables({
>   dark: true, // 开启暗黑模式
>   compact: true, // 开启紧凑模式
> }),
> ```
> 
> ```js
> modifyVars: {
>   'primary-color': '#1DA57A',
>   'link-color': '#1DA57A',
>   'border-radius-base': '2px',
> },
> ```

可以用解构语法做的： 
```
modifyVars: {
 ...getThemeVariables({
  dark: true, // 开启暗黑模式
  compact: true, // 开启紧凑模式
}), 
 'primary-color': '#1DA57A',
 'link-color': '#1DA57A',
 'border-radius-base': '2px',
 },
```

**Comment by afc163** [comment]
@AshoneA 帮忙排查一下 `colorPalette is not defined` 的问题。

**Comment by AshoneA** [comment]
> @AshoneA 帮忙排查一下 `colorPalette is not defined` 的问题。

看起来像是那条 hack 语句问题 modifyVars 中有   hack: 'true;@import "/Users/admin/project/demo/fe-template/node_modules/antd/lib/style/color/colorPalette.less";', 就会报错....

**Comment by llwslc** [comment]
> > 这个接口 `getThemeVariables(options = {})` 是不是应该扩展成 `getThemeVariables(options = {}, extra = {})` 把以下这两种情况合并?
> > ```js
> > modifyVars: getThemeVariables({
> >   dark: true, // 开启暗黑模式
> >   compact: true, // 开启紧凑模式
> > }),
> > ```
> > 
> > 
> > ```js
> > modifyVars: {
> >   'primary-color': '#1DA57A',
> >   'link-color': '#1DA57A',
> >   'border-radius-base': '2px',
> > },
> > ```
> 
> 可以用解构语法做的：
> 
> ```
> modifyVars: {
>  ...getThemeVariables({
>   dark: true, // 开启暗黑模式
>   compact: true, // 开启紧凑模式
> }), 
>  'primary-color': '#1DA57A',
>  'link-color': '#1DA57A',
>  'border-radius-base': '2px',
>  },
> ```

嗯嗯, 是可以这样用, 但我觉得扩展或者更新一下文档会更好一点

**Comment by ycjcl868** [comment]
因为要用到色板变量，得 hack 引入下

**Comment by afc163** [comment]
排查下来和下面这句话有关系，原因继续挂。

https://github.com/ant-design/ant-design/blob/875e190ac7aa41227863bf1b0d02b9c799479b50/components/tree/style/index.less#L12

https://github.com/ant-design/ant-design/blob/875e190ac7aa41227863bf1b0d02b9c799479b50/components/tree-select/style/index.less#L39

**Comment by ycjcl868** [comment]
> 因为要用到色板变量，得 hack 引入下

使用 `modifyVars

**Comment by afc163** [comment]
找到个解决方式：https://github.com/ant-design/ant-design/pull/26395

**Comment by AshoneA** [comment]
> 找到个解决方式：#26395

`hack: 'true;@import "./node_modules/antd/lib/style/color/colorPalette.less";', ` 
周末看了下可以用这种写法... 但是没找到原因

**Comment by mansion-sun** [comment]
> > 这个接口 `getThemeVariables(options = {})` 是不是应该扩展成 `getThemeVariables(options = {}, extra = {})` 把以下这两种情况合并?
> > ```js
> > modifyVars: getThemeVariables({
> >   dark: true, // 开启暗黑模式
> >   compact: true, // 开启紧凑模式
> > }),
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```js
> > modifyVars: {
> >   'primary-color': '#1DA57A',
> >   'link-color': '#1DA57A',
> >   'border-radius-base': '2px',
> > },
> > ```
> 
> 可以用解构语法做的：
> 
> ```
> modifyVars: {
>  ...getThemeVariables({
>   dark: true, // 开启暗黑模式
>   compact: true, // 开启紧凑模式
> }), 
>  'primary-color': '#1DA57A',
>  'link-color': '#1DA57A',
>  'border-radius-base': '2px',
>  },
> ```

这个在package.json中需要加什么插件解析吗，我只要用的es6语法就会报‘.’错误；感觉getThemeVariables做下兼容更合理，轮子就是为了方便使用！
```
function getThemeVariables(options = {}) {
  const {dark, compact, ...rest} = options;
    let themeVar = {
      'hack': `true;@import "${require.resolve('antd/lib/style/color/colorPalette.less')}";`,
      ...defaultTheme
    };
    if(dark) {
      themeVar = {
        ...themeVar,
        ...darkThemeSingle
      }
    }
    if(compact){
      themeVar = {
        ...themeVar,
        ...compactThemeSingle
      }
    }
  if (Object.keys(rest)?.length > 0) {
    themeVar = {
      ...themeVar,
      ...rest // 额外的自定义CSS变量对象集合
    }
  }
  return themeVar;
}
```
