### ISSUE TITLE
Not able to set initial state of radio button to checked if it is inside the form item

### ISSUE THREAD

**Issue by MukeshIn** [ant-design/ant-design#26293]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-oh4f4)

### Steps to reproduce
Put the radio button inside the form item and apply code in order to set its initial state to checked 

### What is expected?
Radio button should be selected if there is value matched in radio group

### What is actually happening?
const dayOptions = [
  { label: 'One Day', value: 1 },
  { label: 'Multiple Days', value: 2 },
];
<Form.Item name="daysValue" {...tailLayout}>
          <Radio.Group options={dayOptions} onChange={handleChange} value={1} />
 </Form.Item>

Radio button not appears as selected on page load but if I will put radio button outside the form item then it is working

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | react 16.13 |
| System | Windows 10 |
| Browser | chrome |

**Comment by MukeshIn** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-oh4f4

**Comment by MukeshIn** [comment]
Can someone help?

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-kifiv

**Comment by MukeshIn** [comment]
Thank you so much
