### ISSUE TITLE
Responsive Layout?

### ISSUE THREAD

**Issue by visvadw** [ant-design/ant-design#2629]
Hello ant-design team,

Is the responsiveness subject covered in this library? I am asking this as I could not find any documentation or example and `Layout` component does not have any prop about it.

Thank you.

**Comment by GrayChoi** [comment]
https://github.com/ant-design/ant-design/blob/master/components/layout/demo/reponsive.md

Have a look at this link？

**Comment by afc163** [comment]
`xs` `sm` `md` `lg`

http://ant.design/components/layout/#components-layout-demo-reponsive-more

**Comment by visvadw** [comment]
You're totally right, I hurried up asking. I thank you both for the feedback. 👍

**Comment by reflog** [comment]
sorry to bump this, the links are dead. is this supported?

**Comment by yesmeck** [comment]
@reflog See https://ant.design/components/grid/#components-grid-demo-reponsive

**Comment by reflog** [comment]
Yea, but how do you apply this to Layout and for example collapse Sider on
small screens?
Thanks in advance!

**Comment by yesmeck** [comment]
The Layout component not using Grid, you can use a [media query tool](https://ant.design/docs/react/recommendation) to make Sider responsive.

**Comment by afc163** [comment]
@reflog trace #4668

**Comment by loganpowell** [comment]
Might this be interesting to include in ant.d?

https://github.com/d6u/react-container-query

http://d6u.github.io/react-container-query/

**Comment by steveswork** [comment]
Layout.Sider has onBreakpoint and breakpoint that I use as a workaround to monitor break point changes. This technique is a bit unwieldy most especially when monitoring changes between two or more specific breakpoints but it is quite fast and saves me the trouble of either introducing yet another npm package into the fray or hand-rolling a bespoke solution. At this point, I simply do something along the lines: `<Layout.Sider breakpoint="xs" onBreakpoint={broken => setIsInXsWidth(broken)} />`. The `onBreakpoint` handler could also be wrapped in `useCallback` hook. If ant design has provided a more dedicated solution to this issue as of today, I am yet to become aware of it.
