### ISSUE TITLE
Form use Switch set valuePropName not working

### ISSUE THREAD

**Issue by TeedyFoold** [ant-design/ant-design#26304]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vdogp?file=/index.js:2247-2260)

### Steps to reproduce
直接使用

### What is expected?
switch 选中

### What is actually happening?
switch 未选中

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.9 |
| System | mac |
| Browser | chorme 84 |

**Comment by afc163** [comment]
https://codesandbox.io/s/wonderful-buck-oocl0?file=/index.js
