### ISSUE TITLE
select组件在多选情况下有些已存在的无法搜索到的问题，有些又可以搜索

### ISSUE THREAD

**Issue by caohuiboss** [ant-design/ant-design#26301]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/focused-moore-99vww?file=/index.js)

### Steps to reproduce
我输入1，可以出现 林超1，但是我输入汉字或者英文却无法搜索到，但实际他存在

### What is expected?
输入啥就会出现啥，建议在多选情况下，加一个属性，该属性的作用是可以控制是否可以让用户搜索，经过我的测试，将key绑定为teacherName却可以解决，但是很明显，key得保持唯一性呢，我可能名字有重复呢，虽然可以自己拼接，但无疑，太丑了不是么，并且拼接也很奇怪不是么；Vue版本antd最新版也有一样的问题

### What is actually happening?
我输入1，可以出现 林超1，但是我输入汉字比如“林”或者英文却无法搜索到，但实际他存在

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 最新 |
| System | window10 家庭版 |
| Browser | 谷歌浏览器  84.0.4147.125（正式版本） （64 位） |

**Comment by flyerH** [comment]
![image](https://user-images.githubusercontent.com/17452527/90711068-5aa51800-e2d2-11ea-9c71-06e909f46923.png)


![image](https://user-images.githubusercontent.com/17452527/90711209-b4a5dd80-e2d2-11ea-85f0-b83731309dbf.png)

**Comment by caohuiboss** [comment]
非常感谢，是我一开始没有理解这个属性的意思



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "flyerH"<notifications@github.com&gt;; 
发送时间: 2020年8月20日(星期四) 上午10:49
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "曹辉"<2550465923@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] select组件在多选情况下有些已存在的无法搜索到的问题，有些又可以搜索 (#26301)
