### ISSUE TITLE
内嵌的 Form.Item 即使 rules 包含 required 也不会显示星号

### ISSUE THREAD

**Issue by mgbaozi** [ant-design/ant-design#26305]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#components-form-demo-register](https://ant.design/components/form-cn/#components-form-demo-register)

### Steps to reproduce
官方文档表单示例中的「注册新用户」项，Captcha 字段标记了 required: true, 但没有显示星号

### What is expected?
希望可以正确显示星号

### What is actually happening?
没有显示星号

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.12.0 |
| System | macOS 10.15 |
| Browser | Chrome 84 |

---
默认的校验信息`未输入${label}` 是否可以使用外层 Form.Item 的 label, 因为按照示例，内部的 Form.Item 没有 label, 如果不写 message 会显示「未输入 undefined」

**Comment by cielblog** [comment]
Hello,
As I understood your problem is that the asterisk not showing in the captcha field,
well, that because there two <Form.Item>, the first one has the title 'captcha' but doesn't have the rules attribute, the nested <Form.Item> has the rules attribute but doesn't have the title's attribute.

And sorry for my English, I know it's trash.

![image](https://user-images.githubusercontent.com/16566503/90726709-d1d6ae00-e2ca-11ea-95e7-88beb49b8301.png)

**Comment by mgbaozi** [comment]
@cielblog 感谢回复，请问有没有什么办法 workaround 一下，我试着在外层 Form.Item 也加上了 {required: true} 也不会显示星号

**Comment by cielblog** [comment]
> @cielblog Thanks for the reply, is there any way to workaround, I tried adding {required: true} to the outer Form.Item and it won’t show asterisks

Just move the rules and name attribute to the first <Form.Item> and remove the nested <Form.ITem>.

` 
<Form.Item name="captcha" label="Captcha" extra="We must make sure that your are a human." rules={[{ required: true, message: 'Please input the captcha you got!' }]}>
              <Row gutter={8}>
                <Col span={12}>
                  <Input />
                </Col>
                <Col span={12}>
                  <Button>Get captcha</Button>
                </Col>
              </Row>
 </Form.Item>
`

![image](https://user-images.githubusercontent.com/16566503/90728754-24fe3000-e2ce-11ea-94f6-e4dfbeadb445.png)

**Comment by zombieJ** [comment]
使用 `required` 属性添加 *，Form.Item 的默认 * 来自 rules，嵌套外层只用了 Form.Item 的布局所以需要自行指定。

**Comment by mgbaozi** [comment]
@cielblog It works, 感谢！还有一个小问题， Form.Item 下的一级组件不是 Input / Select 而是 Row 的话，会影响 form.setFieldsValue 的行为，导致不会更新 Input 控件的内容，不是很完美。

@zombieJ 感谢回复，我在外层和内层 Form.Item 都加了 rules, 还是不显示 *，请问有没有其他自行指定 required 的方式
https://codesandbox.io/s/restless-butterfly-7w23b

**Comment by mgbaozi** [comment]
把外层 Form.Item 加上了 required 属性，在内层 Form.Item 设置
`{rules: {required: true, message: "Captcha is required"}}`
这样可以解决
```
<Form.Item label="Captcha" required>              
  <Form.Item
    name="schedule"
    noStyle
    rules={[{ required: true, message: 'Captcha is required' }]}
   >
      <Input />
  </Form.Item>
  <Button>Test</Button>
</Form.Item>
```

**Comment by yoyo837** [comment]
> @cielblog It works, 感谢！还有一个小问题， Form.Item 下的一级组件不是 Input / Select 而是 Row 的话，会影响 form.setFieldsValue 的行为，导致不会更新 Input 控件的内容，不是很完美。
> 
> @zombieJ 感谢回复，我在外层和内层 Form.Item 都加了 rules, 还是不显示 *，请问有没有其他自行指定 required 的方式
> https://codesandbox.io/s/restless-butterfly-7w23b

 Form.Item 下可以是任何自定义组件，前提是从props接收value和onChange到内部处理好就行

**Comment by mgbaozi** [comment]
> Form.Item 下可以是任何自定义组件，前提是从props接收value和onChange到内部处理好就行

明白了，感谢
