### ISSUE TITLE
form component with react.memo can't render as normal

### ISSUE THREAD

**Issue by tancgo** [ant-design/ant-design#26313]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/memo-5wt3q?file=/a.js:338-355)

### Steps to reproduce
component A :   click add or minus icon  , 点击子组件A的增减按钮，inputnumber值未改变

### What is expected?
like component B

### What is actually happening?
did not re-render

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | latest |
| System | windows |
| Browser | chrome 77.0.3865.90 |

**Comment by afc163** [comment]
https://codesandbox.io/s/memo-forked-x3mql?file=/a.js

**Comment by tancgo** [comment]
> https://codesandbox.io/s/memo-forked-x3mql?file=/a.js

thx
