### ISSUE TITLE
Select drop-down list is blank after scrolling （select 滚动选择后再次打开显示空白）

### ISSUE THREAD

**Issue by mjzzz1** [ant-design/ant-design#26315]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-bush-dtjeq?file=/index.js)

### Steps to reproduce
scroll and select a value， then click select again， the drop down list is blank。
下拉滚动选择一个值，然后再次点击select，下拉列表显示空白，再次滚动后才正常显示

### What is expected?
下拉列表正常显示之前选中值的位置

### What is actually happening?
下拉列表空白

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | macOS Mojave 10.14.6 |
| Browser | chrome  84.0.4147.105 |

---
审查元素发现是translateY(0px)在二次点开时被重置为0px，之前的版本第二次点开时translateY是上次滚动的位置

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26116#issuecomment-675869997
