### ISSUE TITLE
Modal.method 没有语言设置，默认的是英文，ConfigProvider设置无效

### ISSUE THREAD

**Issue by David2k13** [ant-design/ant-design#26314]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
使用支持国际化组件，默认英文

### What is expected?
希望有配置项

### What is actually happening?
使用支持国际化组件，默认英文

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome |

**Comment by David2k13** [comment]
> Hello @David2k13. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @David2k13, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/jibenshiyong-forked-db1cu

**Comment by David2k13** [comment]
> 静态方法不支持 ConfigProvider，使用 hooks：https://ant.design/components/modal-cn/#components-modal-demo-hooks

hooks 也是默认英文提示

**Comment by xrkffgg** [comment]
https://ant.design/components/config-provider-cn/#components-config-provider-demo-locale

**Comment by David2k13** [comment]
> https://ant.design/components/config-provider-cn/#components-config-provider-demo-locale

我用的是Modal.method方式不是组件形式的：https://codesandbox.io/s/jibenshiyong-forked-db1cu

**Comment by zombieJ** [comment]
你给的重现里没有用到 antd

**Comment by David2k13** [comment]
> 你给的重现里没有用到 antd

发错了https://codesandbox.io/s/withered-dust-huytf?file=/index.js:0-1810

**Comment by David2k13** [comment]
> Hello @David2k13. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @David2k13, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

https://codesandbox.io/s/withered-dust-huytf?file=/index.js:0-1810

**Comment by David2k13** [comment]
> > https://ant.design/components/config-provider-cn/#components-config-provider-demo-locale
> 
> 我用的是Modal.method方式不是组件形式的：https://codesandbox.io/s/jibenshiyong-forked-db1cu

发错了 https://codesandbox.io/s/withered-dust-huytf?file=/index.js:0-1810

**Comment by David2k13** [comment]
https://codesandbox.io/s/withered-dust-huytf?file=/index.js:0-1810

**Comment by zombieJ** [comment]
你的重现里没有用 ConfigProvider 啊，加上是好的：
https://codesandbox.io/s/jolly-frost-pkv5q

**Comment by David2k13** [comment]
> 你的重现里没有用 ConfigProvider 啊，加上是好的：
> https://codesandbox.io/s/jolly-frost-pkv5q

看你这个例子是好的，奇怪就是我放在BasicLayout上，Modal.method语言还是英文无效，其他其他组件生效，ConfigProvider套在Modal.method上是生效的

**Comment by zombieJ** [comment]
可以搞个最小重现给 Pro 提一下 issue
