### ISSUE TITLE
TabPane无法单独成组件

### ISSUE THREAD

**Issue by gitdust** [ant-design/ant-design#26320]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/stupefied-solomon-3seew?file=/index.js)

### Steps to reproduce
如Demo所示

### What is expected?
可以渲染出 TabPane

### What is actually happening?
无法渲染出 TabPane

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome  84.0.4147.135 |

---
无相关场景

**Comment by zombieJ** [comment]
TabPane 是一个语法糖，不支持 HOC。
