### ISSUE TITLE
如何在既支持依赖加载，又不用配合ant-init的情况下改变theme？

### ISSUE THREAD

**Issue by yesuanzao** [ant-design/ant-design#2632]
我想还是有很多人不用ant-init的，官方能否考虑出个方案支持一下？

antd 版本: 1.7.0
操作系统及其版本：mac
浏览器及其版本: chrome

**Comment by afc163** [comment]
https://github.com/ant-design/antd-init/tree/7d98b4cfe96fcc272a1b83aca3baf554a67fcf64/examples/customize-antd-theme#webpackconfigjs
