### ISSUE TITLE
Form如何进行组合校验，共用一个消息框

### ISSUE THREAD

**Issue by ColdXu** [ant-design/ant-design#2633]
- antd 版本: 1.7.0

<img src='http://i2.piimg.com/1949/2ffa545432bb5443.jpg' stlye="width:100%">

如何进行组合校验啊！

```js
<FormItem
    label="交易单价"
    {...formItemLayout}>
    <InputNumber
            placeholder="请填写价格"
            min={0}
            step={0.001}
            {...xPriceProps}/>元 +
            &nbsp; 
    <InputNumber
        placeholder="请填写积分"
        {...xIntegralProps}/>&nbsp;积分
</FormItem>
```

**Comment by benjycui** [comment]
http://ant.design/components/form/#components-form-demo-validate-static

![image](https://cloud.githubusercontent.com/assets/3580607/17467084/e8694afe-5d4c-11e6-8801-0b4304231565.png)


把 `Form.Item[help]` 设为空串 `''` 以覆盖默认生成的提示，自行增加一个显示提示信息的框，样式也要做不少调整。
