### ISSUE TITLE
Bad TypeScript type defs

### ISSUE THREAD

**Issue by PeterDraex** [ant-design/ant-design#26338]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://mega.nz/file/zFgHCC7L#o2n8jQ2-rUgy2Hn2w6WOF2O_nGpYuOrkaTGSo-tUSeE](https://mega.nz/file/zFgHCC7L#o2n8jQ2-rUgy2Hn2w6WOF2O_nGpYuOrkaTGSo-tUSeE)

### Steps to reproduce
1. Run the app with `npm start`
2. Open the app at `http://localhost:3000`
3. Wait for 3 seconds
4. Failed to compile error is displayed

### What is expected?
Page with single button is displayed (and stays displayed even after 3 seconds).

### What is actually happening?
TypeScript error is reported in ./node_modules/@ant-design/icons/lib/components/Icon.d.ts(19,78)

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.11.0 |
| System | N/A |
| Browser | N/A |

---
The minimal example was created like this:
1. Open Visual Studio 2019
2. Create new project for ASP.NET Core   React   Redux
3. npm install antd
4. Try to use <Button> component in App component

**Comment by afc163** [comment]
Please upgrade your typescript version to `>=3.9.0` and update @type/react to latest.
