### ISSUE TITLE
Menu component not overflowing properly starting from v4.5.0

### ISSUE THREAD

**Issue by hoshomoh** [ant-design/ant-design#26337]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8f8ij?file=/index.js)

### Steps to reproduce
1. Use the Codesanbox link provided
2. Switch between 4.4.3 and 4.5.4 and notice how the horizontal menu in the content layout no longer overflows

### What is expected?
The horizontal menu should overflow based on the parent width as shown in the image  https://monosnap.com/file/wXsCgeQ2ChUdTttVkib5pXuoLAYwNX

### What is actually happening?
The horizontal menu is not overflowing properly based on the parent width as shown in the image https://monosnap.com/file/83Uun0RhC9piEfa5eNGL4bB6WasLEK

| Environment | Info |
|---|---|
| antd | 4.5.0 |
| React | 16.13.1 |
| System | macOS Catalina v10.15.6 |
| Browser | Google Chrome 84.0.4147.125 (Official Build) (64-bit) |

**Comment by Jbmanllr** [comment]
Hi, i noticed the same problem, it looks like the margin between menu item isn't taken into account anymore and is messing up overflow calculation. You can fix the issue by setting margin inside the item menu or setting padding. I hope they fix it soon.
