### ISSUE TITLE
可以像 formik 那样加一个 isSubmitting 的状态么?

### ISSUE THREAD

**Issue by Stupidism** [ant-design/ant-design#26348]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在提交按钮直接快速点击可以按多次, onFinish 已经是一个 async 函数了, 理论上可以判断出上次提交有没有处理完

### What does the proposed API look like?
form.isSubmitting()

**Comment by afc163** [comment]
Duplicate of #27667
