### ISSUE TITLE
控制台报错-2020年8月24日08:57:37

### ISSUE THREAD

**Issue by 352328759** [ant-design/ant-design#26353]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/layout-cn/](https://ant.design/components/layout-cn/)

### Steps to reproduce
打开控制台

### What is expected?
展开代码, 复制代码等

### What is actually happening?
点击无效果

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | 16.9.0 |
| System | w7 |
| Browser | Google |

**Comment by xrkffgg** [comment]
我这里点击没问题。

**Comment by loserK7** [comment]
同出错

**Comment by 352328759** [comment]
出错界面的截图如下,不知能否作为参考


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 上午9:11
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"邓焯文"<352328759@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 控制台报错-2020年8月24日08:57:37 (#26353)





 
我这里点击没问题。

**Comment by xrkffgg** [comment]
没看到截图呀。

**Comment by 352328759** [comment]
出错界面的截图如下,不知能否作为参考


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 上午9:10
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 控制台报错-2020年8月24日08:57:37 (#26353)





 
Hello @352328759. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by Need Reproduce will be closed if no activities in 7 days.
 
你好 @352328759, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 此处 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。

**Comment by 352328759** [comment]
![1598231640(1)](https://user-images.githubusercontent.com/25167610/90994585-c4336800-e5eb-11ea-983d-876de7019835.jpg)
出错界面的截图如下,不知能否作为参考

**Comment by xrkffgg** [comment]
@352328759 点击显示代码，复制代码 都没有反应？

**Comment by 352328759** [comment]
![1598231640(1)](https://user-images.githubusercontent.com/25167610/90994645-f80e8d80-e5eb-11ea-9a79-e707be89484a.jpg)
出错界面的截图如下

**Comment by 352328759** [comment]
> @352328759 点击显示代码，复制代码 都没有反应？

都没有反应

**Comment by xrkffgg** [comment]
你用的是啥浏览器？

**Comment by 352328759** [comment]
Google, UC 都有这个问题

**Comment by loserK7** [comment]
![1598232855(1)](https://user-images.githubusercontent.com/34083776/90994979-1759ea80-e5ed-11ea-83d9-4bd7ce9411cd.jpg)

**Comment by 352328759** [comment]
@loserK7 跟你报错信息差不多

**Comment by xrkffgg** [comment]
Mac chrome firefox safari 正常

**Comment by xch1029** [comment]
> Mac chrome firefox safari 正常

我的任何浏览器都不正常，点击没有效果

**Comment by xrkffgg** [comment]
@xch1029 @352328759 @loserK7 都是 windows 环境吗？

**Comment by xch1029** [comment]
> @xch1029 @352328759 @loserK7 都是 windows 环境吗？

嗯，我是windows环境，感觉就是点击事件没了，很多可以点击的组件都没有响应，昨天我就发现了这个问题。4.5的文档是正常的

**Comment by ycjcl868** [comment]
Windows 测试确实是有问题，`?` undefined，目测和  esbuild 有关

**Comment by zombieJ** [comment]
`??` 语法看起来没有 polyfill

**Comment by weixiaoyi** [comment]
有没有4.5的文档地址，麻烦发一个，等着急用呢，无米下锅了

**Comment by zombieJ** [comment]
Chrome 什么版本的？

**Comment by 352328759** [comment]
Chrome 升级到 [版本 84.0.4147.135（正式版本） （64 位）] 能用了

**Comment by l745230** [comment]
Mac 
内核 Chromium 69.0.3497.81  控制台报错,官网控件点击无效果.

![image](https://user-images.githubusercontent.com/15940920/90997804-1a58d900-e5f5-11ea-84ee-bfab9aa280f3.png)

版本 84.0.4147.135（正式版本） （64 位）控制台报错,访问正常,
![image](https://user-images.githubusercontent.com/15940920/90998010-9d7a2f00-e5f5-11ea-8a8e-568729814a43.png)

**Comment by weixiaoyi** [comment]
chrome升级到新版就可以使用，虽然有一堆报错，不影响使用了

**Comment by zombieJ** [comment]
@l745230 升级版本，你的内核太老了。

**Comment by l745230** [comment]
能不能兼容下低一点版本的Chromium内核啊.

Mac QQ浏览器一直都是这个版本Chromium 69.0.3497.81.   他不升级我也很无奈啊,书签都在QQ账号上,多端通用.
之前AntDesign首页下拉框显示信息不全,部分信息显示... 也就算了, 4.6.0是全都用不了了

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/26357  有 patch 过会儿发，想先看到可以先用 Chrome

**Comment by ycjcl868** [comment]
https://preview-26357-ant-design.surge.sh/components/layout-cn/

大家试试这个，有没有报错

**Comment by zombieJ** [comment]
> https://preview-26357-ant-design.surge.sh/components/layout-cn/
> 
> 大家试试这个，有没有报错

@l745230

**Comment by l745230** [comment]
![image](https://user-images.githubusercontent.com/15940920/90998880-b388ef00-e5f7-11ea-842c-47f976c6ae3a.png)

**Comment by l745230** [comment]
Mac 可复现QQ浏览器...
https://browser.qq.com/mac/

**Comment by jayliang701** [comment]
同出问题。这真的是企业级框架吗？

**Comment by l745230** [comment]
> 同出问题。这真的是企业级框架吗？

AntDesign这边还算好的了.用最新版Chrome还能访问.
AntDesignPro才是真蛋疼,升级4.6.0后,布局乱套了.还回滚不到上个正常的版本.头大

**Comment by jayliang701** [comment]
> > 同出问题。这真的是企业级框架吗？
> 
> AntDesign这边还算好的了.用最新版Chrome还能访问.
> AntDesignPro才是真蛋疼,升级4.6.0后,布局乱套了.还回滚不到上个正常的版本.头大

Pro侵入性太强了，所以一直用非Pro。希望官方可以出一个离线版的文档。

**Comment by zombieJ** [comment]
@l745230 再试试

**Comment by Dgulai** [comment]
2020年8月24日 11:39:29   
同问题 文档炸了， 除了连接反馈之外的东西其他功能全无效

**Comment by zombieJ** [comment]
> https://preview-26357-ant-design.surge.sh/components/layout-cn/

@Dgulai 试试这个
