### ISSUE TITLE
Select onPopupScroll - scrollTop value is always zero

### ISSUE THREAD

**Issue by JensD98** [ant-design/ant-design#26352]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-scrolltop-is-always-zero-460-d80yc?file=/index.js:427-440)

### Steps to reproduce
Look at the `scrollTop` value in the console.

### What is expected?
`ScrollTop` value should be correct.

### What is actually happening?
`ScrollTop` value is zero.

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google Chrome 84.0.4147.135 |

---
I want to detect if the user has scrolled to the bottom, in version 4.6.0 using the `scrollTop` property that does not work anymore.

**Comment by flyerH** [comment]
`rc-select`升级依赖`rc-virtual-list`造成的，我试了下`rc-select` 11.1.4及之后这个就不好使了

**Comment by gadore** [comment]
同样的问题，关键是我也没升级node_module依赖，所有的table滚动都失效了。强制滚动到tabletop。官网的demo也是

**Comment by vVvlife** [comment]
难怪会这么卡，表示在火狐上，直接滚动就卡住了

**Comment by zombieJ** [comment]
@gadore Table 没有使用 `rc-virtual-list`，给个重现看看？

**Comment by gadore** [comment]
> @gadore Table 没有使用 `rc-virtual-list`，给个重现看看？

昂，项目赶进度，没有细排查，依赖全部删掉重下了。拉的npm官方的。暂时不用cnpm了。现在问题解决
