### ISSUE TITLE
Select组件dropdownRender中使用Input无法输入

### ISSUE THREAD

**Issue by W-ambition** [ant-design/ant-design#26359]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cyuv0?file=/index.js)

### Steps to reproduce
点击Select下拉展开，点击下拉展开项中的Input不能获取焦点，不能输入。

### What is expected?
Select组件，dropdownRender中使用Input可以正常输入

### What is actually happening?
Select组件，dropdownRender中使用Input不能输入

| Environment | Info |
|---|---|
| antd | 3.26.5 |
| React | 16.7.0 |
| System | windows10 |
| Browser | Chrome  83.0.4103.106 |

---
给Input添加了onMouseDown={e =>e.preventDefault()},但是Input不能输入，如果不加onMouseDown事件，点击Input，Select展开项会收起。

**Comment by afc163** [comment]
1. 如果你想做搜索，直接 showSearch 就可以了。
2. input 非得放在下拉菜单里的话，看看 https://github.com/ant-design/ant-design/issues/13448#issuecomment-534835105
