### ISSUE TITLE
Badge not work when props.color is incorrectly

### ISSUE THREAD

**Issue by chiaweilee** [ant-design/ant-design#26363]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/chiaweilee/pen/KKzaZWj?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fbadge-cn%2F](https://codepen.io/chiaweilee/pen/KKzaZWj?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fbadge-cn%2F)

### Steps to reproduce
set props.color to empty string('')

### What is expected?
Badge works.

### What is actually happening?
Badge not works.

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | latest |
| System | mac os 10.14.4 |
| Browser | chrome 78 |

**Comment by OmriGM** [comment]
@xrkffgg Same thing happens when the `status` prop is an empty string.
