### ISSUE TITLE
Form 文档问题

### ISSUE THREAD

**Issue by Witee** [ant-design/ant-design#2636]
#### 本地环境

- antd 版本: 1.8.0
- 操作系统及其版本： OS X 10.10.5
- 浏览器及其版本: Google Chrome 版本 52.0.2743.116 (64-bit)

#### 你做了什么？

文档：
"form	经 Form.create() 包装过的组件会自带 this.props.form 属性，直接传给 Form 即可。1.7.0 之后无需设置"

"1.7.0 之后无需设置" 是 Form.create() 不用设置？还是 “ <Form horizontal form={this.props.form}>”中不需要再设置form={this.props.form} ?

右下角的文档版本选的是1.8.0

**Comment by afc163** [comment]
`form={this.props.form}` 这句可以省略。

https://github.com/ant-design/ant-design/pull/2534

**Comment by Witee** [comment]
感谢。

还有个小问题。
CustomizedForm = Form.create(**{}**)(CustomizedForm);

中 { } 是否可以省略？因为使用方法中写的是有的，但例子中是没有的。

**Comment by afc163** [comment]
可以，不传配置就可以省略。

**Comment by Witee** [comment]
感谢。回复真快！
今天我从1.6.4升级到1.8.0，目前没发现什么错误。
