### ISSUE TITLE
Form pattern 只驗證了第一個字，後面都沒驗證

### ISSUE THREAD

**Issue by Bonnie8ni** [ant-design/ant-design#26364]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-validation-3p74n)

### Steps to reproduce
pattern 如 codesandbox 內那樣
1. 當輸入“F”時，會被判錯並顯示錯誤提示（正確的）
2. 當輸入“aF”時，不會被判錯且未顯示錯誤訊息（錯誤的）

### What is expected?
應該輸入框每個字都要驗證

### What is actually happening?
只驗證了第一個字的正確與否，所以只要第一個字符合規則，後面的字要是規則不正確也能通過

| Environment | Info |
|---|---|
| antd | 4.3.3 |
| React | 16.12.0 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
```js
/^[a-z]([-a-z0-9]*[a-z0-9])?/.test('a') // true
/^[a-z]([-a-z0-9]*[a-z0-9])?/.test('aF') // true
/^[a-z]([-a-z0-9]*[a-z0-9])?/.test('F')  // false
``

自行检查一下正则表达式吧。

**Comment by afc163** [comment]
另外，用了 Form 之后不再需要 value 和 onChange 了：https://codesandbox.io/s/ant-validation-forked-68wch

**Comment by Bonnie8ni** [comment]
我被這個混淆了 https://regexr.com/
以為沒框起來就是不符合

> 另外，用了 Form 之后不再需要 value 和 onChange 了：https://codesandbox.io/s/ant-validation-forked-68wch

我在把我錯用的地方進行修正
謝謝你 :')
