### ISSUE TITLE
Table组件 filterDropdown自定义含input下拉框时展示问题

### ISSUE THREAD

**Issue by Cedarkun** [ant-design/ant-design#26366]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sharp-nobel-tmnm8)

### Steps to reproduce
1.在表头中利用 filterDropdown自定义过滤下拉框展示
2.下拉框展示具有autoFocus属性的Input
3.点击表头的过滤Icon以展示过滤下拉框，页面会返回到页首(只有首次点击才会出现)，且autoFocus也没生效

### What is expected?
首次点击过滤图标时能页面保持在原来停留的位置，并使得Input autoFocus功能生效

### What is actually happening?
首次点击过滤图标时能页面滚轮回到页首，且autoFocus也没生效

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | windows64 |
| Browser | Google Chrome74.0.3724.8 |

---
目前已知Input 去掉autoFocus不会出现页面跳到页首的bug，想搞明白为什么会出现这个问题，是不是这个功能有什么注意点

**Comment by Cedarkun** [comment]
https://codesandbox.io/s/sharp-nobel-tmnm8 这个链接可以重现呀。滑倒页面底部就有表格，首次点击表头Name过滤按键页面就会自动返回顶部，且Input也没能自动获取焦点，为什么会这样呢？

**Comment by afc163** [comment]
刚才打开的时候还啥也没有。

**Comment by afc163** [comment]
autoFocus 非常容易破坏页面可用性，原因可见：https://medium.com/@gavyn/til-autofocus-inputs-are-an-accessibility-problem-32ced60c3109

另外第二次打开浮层的时候也无法 focus。

建议参考我们的 demo 里提供的方式来实现 focus 行为：https://ant.design/components/table-cn/#components-table-demo-custom-filter-panel
