### ISSUE TITLE
所有的滚动组件全部出问题

### ISSUE THREAD

**Issue by gadore** [ant-design/ant-design#26360]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/#components-table-demo-sticky](https://ant.design/components/table-cn/#components-table-demo-sticky)

### Steps to reproduce
任何滚动页面，都会自动滚动到头部

### What is expected?
不要自动滚动

### What is actually happening?
滚动到了头部，永远都要滚动到头部再停止

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Edge  84.0.522.63 |

**Comment by afc163** [comment]
你能录个屏么？不知道你反馈的是什么问题。

**Comment by gadore** [comment]
> 你能录个屏么？不知道你反馈的是什么问题。

好

**Comment by gadore** [comment]
> 你能录个屏么？不知道你反馈的是什么问题。

视频地址：https://cowtransfer.com/s/3985f24d2c5741

**Comment by afc163** [comment]
给个在线可重现的地址。

**Comment by gadore** [comment]
> 给个在线可重现的地址。

问题解决了，暂时不知道问题所在，就把依赖全删掉了。重新拉取后发现问题消失。抱歉刚才大惊小怪的打扰到你了T_T
