### ISSUE TITLE
tabs使用renderCustomTabBar 中二次封装头部报错（tabBarProps 中 panels为空）

### ISSUE THREAD

**Issue by hugething** [ant-design/ant-design#26365]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-11vlk?file=/index.js)

### Steps to reproduce
abs使用renderCustomTabBar 中二次封装标签头（tabBarProps 中 panels有值）

### What is expected?
能正常进行二次封装tabs使用renderCustomTabBar 中二次封装标签头（tabBarProps 中 panels有值）

### What is actually happening?
进行二次封装tabs使用renderCustomTabBar 中二次封装标签头报错（tabBarProps 中 panels为undefined, 最后发现实际变量变成了panes， 这么明显的拼写错误可以合进主分支么，。。。。。。。。。。。。，这是在版本更新后发现报错的）

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.9 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
<img width="554" alt="image" src="https://user-images.githubusercontent.com/507615/92839044-1bba3c00-f412-11ea-9734-fe2276af19dd.png">
