### ISSUE TITLE
upload没有children属性

### ISSUE THREAD

**Issue by walt-wu** [ant-design/ant-design#26361]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#components-upload-demo-basic](https://ant.design/components/upload-cn/#components-upload-demo-basic)

### Steps to reproduce
<Upload
        name="avatar"
        accept="image/jpg, image/jpeg, image/png"
        listType="picture-card"
        className="avatar-uploader"
        showUploadList={false}
        customRequest={onCustomRequest}
      >
        {props.currentWidget.coursewareThumbnail && <CloseCircleFilled className="delete-icon" onClick={deleteResource} />}
        {props.currentWidget.coursewareThumbnail ? <img src={props.currentWidget.coursewareThumbnail} alt="" /> : <div>
          <PlusOutlined />
          <div className="ant-upload-text">上传</div>
        </div>}
      </Upload>

// ts检查不通过

### What is expected?
可以给upload添加children

### What is actually happening?
不能将类型“{ children: ("" | Element)[]; name: string; accept: string; listType: "picture-card"; className: string; showUploadList: false; customRequest: (option: RcCustomRequestOptions) => void; }”分配给类型“IntrinsicAttributes & UploadProps<any> & RefAttributes<any>”。
  类型“IntrinsicAttributes & UploadProps<any> & RefAttributes<any>”上不存在属性“children”。 【ts】

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | 16.13.1 |
| System | win 10 |
| Browser | chrome 84.0.4147.135 |

**Comment by Kermit-Xuan** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/26347

**Comment by yakiang** [comment]
@Kermit-Xuan 会在 4.6.2 发布吗，大概是什么时候呢?

**Comment by Kermit-Xuan** [comment]
已经发布了，4.6.1
