### ISSUE TITLE
Table虚拟滚动,列1000，scrollLeft 0 时scroll bar迟钝 仿佛页面卡主了

### ISSUE THREAD

**Issue by ChipmunkJerry** [ant-design/ant-design#26368]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-mwyut9-myecty?file=index.js](https://stackblitz.com/edit/react-mwyut9-myecty?file=index.js)

### Steps to reproduce
列设置为1000
初屏渲染卡顿
拖动横向滚动条很艰难

### What is expected?
拖拽顺畅

### What is actually happening?
特别是拖动在最左侧，再向右拖动，鼠标需要拖拽很多下才能拖动

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16 |
| System | win10 |
| Browser | chrome49 |

---
不明白拖拽卡顿的原因，希望得到解答帮助。Thanks♪(･ω･)ﾉ

**Comment by ChipmunkJerry** [comment]
滚动条在最左边的时候，点一下向右滚动的三角，然后停顿2s左右整体才向右滚动

**Comment by oyjy2018** [comment]
你好请问chrome49不能支持Table虚拟滚动对吗？

**Comment by afc163** [comment]
Chrome 49 太老了，不再提供支持。
