### ISSUE TITLE
輸入框錯誤訊息並不會因刪除而更新

### ISSUE THREAD

**Issue by sherry-huang** [ant-design/ant-design#26370]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/epic-germain-4943p)

### Steps to reproduce
1. 點擊 Add 新增兩個輸入框，並點擊 Confirm 進行輸入框驗證
2. 再次點擊 Add 新增兩個輸入框，並點擊上方數下來第二個輸入框右方的刪除

### What is expected?
剩餘三個輸入框
第一個輸入框有 required 的提示訊息
第二、三個沒有提示訊息

### What is actually happening?
剩餘三個輸入框
第一、二個輸入框有 required 的提示訊息
第三個沒有提示訊息

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12.0 |
| System | Window10 |
| Browser | Chrome 版本 84.0.4147.135 |

**Comment by afc163** [comment]
```diff
- <div className={styles.box} key={idx}>
+ <div className={styles.box} key={item.key}>
```

**Comment by sherry-huang** [comment]
> ```diff
> item.key
> ```

 謝謝!!

**Comment by sherry-huang** [comment]
> ```diff
> - <div className={styles.box} key={idx}>
> + <div className={styles.box} key={item.key}>
> ```

已使用您的方式修正，還是有以下問題

範例網址：https://codesandbox.io/s/epic-germain-4943p

Steps to reproduce
1. 點擊 Add 新增四個輸入框，並點擊 Confirm 進行輸入框驗證
2. 並點擊上方數下來第一個輸入框右方的刪除

What is expected?
剩餘三個輸入框
且所有輸入框都要有 required 的提示訊息

What is actually happening?
剩餘三個輸入框
三個輸入框皆無提示訊息

**Comment by afc163** [comment]
@zombieJ 有空看看最后一个例子。

**Comment by zombieJ** [comment]
例子一的问题：当你删除一个字段，`key` 是 `idx`，对于 React 而言，你删除中间任意一个元素，它 diff 出来都是删除最后一个元素。它并不知道你删除了的是中间的一个 Form.Item。

例子二的问题：外层通过 `key` 做 mapping，而内部使用 `["resource", idx, "id"]` 做字段注册，每次删除都会使得内部 name 变更导致 Form.Item 以为字段不需要了而卸载又重新注册。

解决方案就是用 Form.List，这些 mapping 关系已经被封装好了。没有必要重新实现一把：https://github.com/react-component/field-form/blob/e72849a27dd24252c32cc945a0ff35765ab53f36/src/List.tsx

**Comment by afc163** [comment]
我也看漏了

```diff
                  <Form.Item
-                   name={["resource", idx, "id"]}
+                   name={["resource", item.key, "id"]}
                    rules={[{ required: true }]}
                  >
```
