### ISSUE TITLE
Table页面文字无法选择

### ISSUE THREAD

**Issue by GrayFrost** [ant-design/ant-design#26379]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
直接打开官网地址，发现table组件展示页的文字和代码均无法选择。

### What is expected?
文字内容能够被选择复制。

### What is actually happening?
无法选择复制

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | react |
| System | macos |
| Browser | chrome |

**Comment by xrkffgg** [comment]
神奇，其他组件是正常的。

**Comment by afc163** [comment]
https://github.com/react-component/table/pull/505/files#diff-e8decbd4692962416587d0dcaad17e1fR113-R121

@shaodahong

**Comment by littlepoolshark** [comment]
我....里面直接一个`event.preventDefault()`，如此简单粗暴，我服.......
