### ISSUE TITLE
TreeNode isLeaf 设置为 false 与不设置该属性时表现不一致

### ISSUE THREAD

**Issue by Enivia** [ant-design/ant-design#26373]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tree-isleaf-test-l53md?file=/index.js)

### Steps to reproduce
- 使用 Tree 组件，内有三个节点， isLeaf 属性分别为false, undefined, true
- 异步展开节点

### What is expected?
分别展开 isLeaf 设置为 false 和未设置该属性的节点时应表现一致。

### What is actually happening?
展开 isLeaf = false 的节点时，节点前三角标志仍然存在；isLeaf = undefined 时三角标志消失。

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12.0 |
| System | Windows |
| Browser | Chrome 84.0.4147.135 |

**Comment by zombieJ** [comment]
文档有误，`isLeaf` 默认是根据节点来算，设置后为强制定义。我更新一下文档。
