### ISSUE TITLE
Select组件在火狐上的滚动有明显的卡顿

### ISSUE THREAD

**Issue by vVvlife** [ant-design/ant-design#26372]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1sylm?file=/index.js)

### Steps to reproduce
点开Select，开始滚动

### What is expected?
流畅

### What is actually happening?
非常卡顿

| Environment | Info |
|---|---|
| antd | 4.6.0 |
| React | 16.13.1 |
| System | Linux Ubuntu 18.04 |
| Browser | Firfox 79.0 |

---
据说是依赖更换的原因，请看看

**Comment by afc163** [comment]
发布前我也测过很多轮，已经比当时改动的第一版性能好了很多，但是估计依然比不上改动前。

另外我本地是 Mac Firefox，Linux 下的还没测过。

**Comment by vVvlife** [comment]
> 发布前特别针对火狐也测过很多轮，已经比当时改动的第一版性能好了很多，但是估计依然比不上改动前。
> 
> 另外我本地是 Mac Firefox 80.0b8，Linux 下的还没测过。

是的，确实还是肉眼能看见的卡顿，希望后续能有更好的解决方案

**Comment by zombieJ** [comment]
能上个 gif 不？

**Comment by vVvlife** [comment]
> 能上个 gif 不？

好的，我录一下

**Comment by vVvlife** [comment]
> 能上个 gif 不？

![1598320522758mztest gif](https://user-images.githubusercontent.com/20148964/91114287-23f84480-e6ba-11ea-9c37-715536f718a5.gif)
手机录制，不知道为什么比较模糊，但是能大概看个卡顿的情况

**Comment by zombieJ** [comment]
滚动是用的滚轮还是触屏？

**Comment by vVvlife** [comment]
> 滚动是用的滚轮还是触屏？

用的是鼠标的滚轮

**Comment by zombieJ** [comment]
找了个鼠标测了一下，发现 FF 下鼠标滚轮触发的 `wheel` 和 `scroll` 事件是不同步的。我搜搜有没有相关内容：
![截屏2020-08-25 下午1 57 05](https://user-images.githubusercontent.com/5378891/91128546-fb347700-e6da-11ea-87c1-97512a661007.png)

**Comment by vVvlife** [comment]
> 找了个鼠标测了一下，发现 FF 下鼠标滚轮触发的 `wheel` 和 `scroll` 事件是不同步的。我搜搜有没有相关内容：
> ![截屏2020-08-25 下午1 57 05](https://user-images.githubusercontent.com/5378891/91128546-fb347700-e6da-11ea-87c1-97512a661007.png)

确实存在这个问题，[]( http://www.javascriptkit.com/javatutors/onmousewheel.shtml)，火狐滚动监听的事件是DOMMouseScroll  =。=

**Comment by vVvlife** [comment]
> 找了个鼠标测了一下，发现 FF 下鼠标滚轮触发的 `wheel` 和 `scroll` 事件是不同步的。我搜搜有没有相关内容：
> ![截屏2020-08-25 下午1 57 05](https://user-images.githubusercontent.com/5378891/91128546-fb347700-e6da-11ea-87c1-97512a661007.png)

确实存在这个问题，，火狐滚动监听的事件是DOMMouseScroll =。= [](http://www.javascriptkit.com/javatutors/onmousewheel.shtml)

**Comment by zombieJ** [comment]
@vVvlife 试试这个：https://virtual-list-git-ff-fix.react-component.now.sh/iframe.html?id=rc-virtual-list--basic

**Comment by vVvlife** [comment]
> @vVvlife 试试这个：https://virtual-list-git-ff-fix.react-component.now.sh/iframe.html?id=rc-virtual-list--basic

ok,这个没有问题

**Comment by zombieJ** [comment]
`+ rc-virtual-list@3.0.6`
