### ISSUE TITLE
DatePicker 如何支持半年选择器，年 季度 如何把下面的显示改变 暂时没有这样的api 啊

### ISSUE THREAD

**Issue by jeemoy0317** [ant-design/ant-design#26378]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
功能需求 看半年的报表

### What does the proposed API look like?
 出一个支持更改还有半年的api

**Comment by afc163** [comment]
半年这样的建议用 YearPicker + Select 组合实现吧。

**Comment by jeemoy0317** [comment]
> 半年这样的建议用YearPicker +选择组合实现吧。

 这个我去调研下 那如何更改季度年限免的显示呢 还有上面的年份显示
