### ISSUE TITLE
在mac上，项目正常运行，整个项目拷贝到window电脑，运行就报错：@ant-design/icons/lib/dist  找不到

### ISSUE THREAD

**Issue by z-lionel** [ant-design/ant-design#26371]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/umijs/umi/issues/5015](https://github.com/umijs/umi/issues/5015)

### Steps to reproduce
如题

### What is expected?
正常运行

### What is actually happening?
This dependency was not found:

* @ant-design/icons/lib/dist in ./node_modules/antd/es/icon/index.js

To install it, you can run: npm install --save @ant-design/icons/lib/dist

| Environment | Info |
|---|---|
| antd | undefined |
| React | "react": "^16.8.6", |
| System | window |
| Browser | chrome |

**Comment by afc163** [comment]
> 整个项目拷贝到window电脑

不要这么操作，建议 clone 并重新安装。

**Comment by z-lionel** [comment]
> > 整个项目拷贝到window电脑
> 
> 不要这么操作，建议 clone 并重新安装 node_modules。

我重新删除了node_modules了,在重新yarn了，依然报错。
版本如下：
 "@ant-design/icons": "^4.2.2",
  "antd": "^3.26.18",

在  antd/es/icon/index.js 文件里面引用的 ant-design/icons/lib/dist 没有这个文件夹，
请问这个是版本的问题吗？

**Comment by afc163** [comment]
@ant-design/icons 应该和 antd 4 一起使用，请不要混用。

**Comment by z-lionel** [comment]
> @ant-design/icons 应该和 antd 4 一起使用，请不要混用。
现在不是我想混用，而是我用的"antd": "^3.26.18"这个版本的时候，就会报这个错

**Comment by wukong615** [comment]
我也遇到了这个问题：@ant-design/icons/lib/dist 找不到。
使用的antd版本 3.20.0。出现这个问题的原因是：
在解决 3.x 版本全量引入@ant-design/icons图标文件时 resolve 路径中加入了 /dist，去掉 /dist 后可以正常启动

**Comment by yoyo837** [comment]
3.x 自带 @ant-design/icons 2.x

4.x 需要自行安装 @ant-design/icons 4.x
