### ISSUE TITLE
Mentions组件在measuring过程中应该阻止onPressEnter的调用

### ISSUE THREAD

**Issue by zhangyu1818** [ant-design/ant-design#26381]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-kepler-efj0f)

### Steps to reproduce
1. 输入@
2. 按回车

### What is expected?
不应该触发onPressEnter

### What is actually happening?
触发了onPressEnter，输出了@

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | Ubuntu 20.04LTS |
| Browser | Chrome 84 |

---
聊天功能按了@后接回车选人，触发了onPressEnter后发送了没有人的空@，我认为在measuring过程中不应该触发Textarea的onPressEnter

**Comment by zhangyu1818** [comment]
这个好像得修改rc-mentions才行

**Comment by afc163** [comment]
可以发 PR 到 rc-mentions

**Comment by afc163** [comment]
Resolved by https://github.com/react-component/mentions/pull/32
