### ISSUE TITLE
Dropdown 包裹 Tree，需要给 Tree 包裹一层 div，否则无法右键打开菜单

### ISSUE THREAD

**Issue by mianlang** [ant-design/ant-design#26380]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-c8m5i)

### Steps to reproduce
case 1: Dropdown 直接包裹 Tree，trigger 为 contextMenu，右击 tree node

case 2: Tree 外增加一层 div，右击 tree node

### What is expected?
case 1: 正常打开 Menu

case 2: 正常打开 Menu

### What is actually happening?
case 1: 无法打开 Menu

case 2: 正常打开 Menu

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.3 |
| Browser | Google Chrome 84.0.4147.125 |

**Comment by mianlang** [comment]
目前想法是 trigger 包含 contextMenu 时，给 child 赋值 ```<div>{children}</div>```

才疏学浅，还望高人指出非硬解思路

**Comment by alienzhangyw** [comment]
#31435 不只是Tree或者Table，只要是直接包裹任意react组件都不行
