### ISSUE TITLE
Image component page turning function

### ISSUE THREAD

**Issue by xiaosenzhang** [ant-design/ant-design#26385]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Like WeChat chat point open the picture, you can directly view the last picture or the next picture

### What does the proposed API look like?
Like WeChat chat point open the picture, you can directly view the last picture or the next picture

**Comment by afc163** [comment]
see https://github.com/react-component/image/pull/22

**Comment by hengkx** [comment]
https://github.com/ant-design/ant-design/blob/master/package.json#L128   4.2.0
