### ISSUE TITLE
antd 文档错误

### ISSUE THREAD

**Issue by xishanxu** [ant-design/ant-design#26388]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs-cn/#components-tabs-demo-extra](https://ant.design/components/tabs-cn/#components-tabs-demo-extra)

### Steps to reproduce
https://ant.design/components/tabs-cn/#components-tabs-demo-extra
Tabs 附加内容demo代码， position单词错误

### What is expected?
单词应该为position

### What is actually happening?
单词应该为positon

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.8 |
| System | MacOS |
| Browser | Chrome |
![image](https://user-images.githubusercontent.com/43942406/91147527-fd9ecd00-e6ea-11ea-8e17-70cd70be24d9.png)

**Comment by afc163** [comment]
来个 PR~

**Comment by xishanxu** [comment]
OK



---原始邮件---
发件人: "偏右"<notifications@github.com&gt;
发送时间: 2020年8月25日(周二) 下午3:56
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"xishanxu"<825983767@qq.com&gt;;
主题: Re: [ant-design/ant-design] antd 文档错误 (#26388)




 
来个 PR~

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/26391
