### ISSUE TITLE
Cascader input name

### ISSUE THREAD

**Issue by jzrskc** [ant-design/ant-design#26398]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We should be able to set Cascaders input name. The checkbox component is having it already.
<Checkbox
      onBlur={onBlur}
      onChange={e => onChange(e.target.checked)}
      checked={value}
      name={name} />

### What does the proposed API look like?
<Cascader
              options={options}
              name="customName"
              displayRender={(label) => label[label.length - 1]}
              onChange={() => console.log('changed!')}
            />

**Comment by afc163** [comment]
It support: https://codesandbox.io/s/xenodochial-euclid-vpq8l?file=/index.js

**Comment by jzrskc** [comment]
Thane please update documentation and interface CascaderProps. interface CascaderProps contains not fields name and id.

`
interface CascaderProps {
...
name?: string;
id?: string;
...
}
`
