### ISSUE TITLE
Upload onChange handler invoked multiple times

### ISSUE THREAD

**Issue by barisssss** [ant-design/ant-design#26396]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upload-file-handler-3blk7?file=/index.js)

### Steps to reproduce
try to upload a file and watch the console. the upload handler gets called multiple times.

### What is expected?
the handler should only be called once, when i select a file.

### What is actually happening?
the handler is called multiple times.

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | Ubuntu 19.10 |
| Browser | Chrome 84.0.4147.125 |

**Comment by afc163** [comment]
It is by designed, file upload process and status is changing during upload.
