### ISSUE TITLE
Table sticky 屬性支持設置scroll container

### ISSUE THREAD

**Issue by marklai1998** [ant-design/ant-design#26399]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
當table 在 overflow: auto 的parent 下時，sticky scrollbar不會消失即使table 已scroll 出container, 直至 width update

### What does the proposed API look like?
和getPopupContainer一樣，指定scroll的HtmlElement，或讓table自適應 overflow: auto container

**Comment by marklai1998** [comment]
reproduce
https://codesandbox.io/s/antd-reproduction-template-forked-kkfkt?file=/index.js

下面的scroll bar 不會響應overflow: auto 的 div
![image](https://user-images.githubusercontent.com/18364699/91278082-55563a80-e7b6-11ea-9fb6-f9b335d74b06.png)

即使table 已經scorll 出viewport, scrollbar 依然存在，直到table有任何更新
![image](https://user-images.githubusercontent.com/18364699/91278151-6e5eeb80-e7b6-11ea-9c7d-79102bf59135.png)

這對於flax layout不太友好，想指定scroll的HtmlElement，或讓table自適應 overflow: auto container

**Comment by hyl1374961656** [comment]
我也遇到了这种问题，为什么关闭了

**Comment by hyl1374961656** [comment]
<img width="409" alt="5578D51C-D1F6-4456-8226-F567746E51D4" src="https://user-images.githubusercontent.com/56420042/93579210-cc0ae000-f9d0-11ea-85f6-d3e9a5e5cccb.png">
吸顶好像还有几像素问题

**Comment by lich-yoo** [comment]
我这边业务上，已经改为固定高度 scroll: { y: xx } 方式了。

可以看下 element inner scroll 的前提，还有什么场景  scroll 无法解决，sticky 可以解决？

**Comment by hyl1374961656** [comment]
需要的是页面显示全部的数据，但是在小屏幕上滚动到底部需要再滚动上去对表头，其实出现两个横向滚动条这个问题通过css样式覆盖也可以解决

**Comment by shaodahong** [comment]
`inner scroll` 和 `sticky` 是两个不同的方向，`inner scroll` 页面上会出现两个滚动条，体验不是很好，如果要支持容器那么 `scroll` 需要重构，目前用的 `fixed`

**Comment by marklai1998** [comment]
所以有機會會在下個板本修正嗎？
我這邊業務上有些很長的table需要 `sticky` 去改善ux (不能用pagination
現在只能在table上面強加一個scrollbar去控制

**Comment by marklai1998** [comment]
剛試了最新的4.7.0，還是沒解決scrollbar 出現和消失的bug

圖例：table 已經scroll 到最底了，額外的scrollbar還不會消失，要用戶點一下
一但消失了scroll上去也不會變回來，需要table update
![image](https://user-images.githubusercontent.com/18364699/95735358-491b3380-0cb7-11eb-939e-8ed3d8b0897f.png)


https://codesandbox.io/s/antd-reproduction-template-forked-bvcd8?fontsize=14&hidenavigation=1&theme=dark

**Comment by marklai1998** [comment]
@shaodahong 

剛試了最新的4.7.0，還是沒解決scrollbar 出現和消失的bug

圖例：table 已經scroll 到最底了，額外的scrollbar還不會消失，要用戶點一下
一但消失了scroll上去也不會變回來，需要table update
image

codesandbox.io/s/antd-reproduction-template-forked-bvcd8?fontsize=14&hidenavigation=1&theme=dark

**Comment by shaodahong** [comment]
> @shaodahong
> 
> 剛試了最新的4.7.0，scrollber 正確的放在scroll container 裏面
> 還是沒解決scrollbar出現和消失handler的bug
> 
> 圖例：table 已經scroll 到最底了，額外的scrollbar還不會消失，要用戶點一下
> 一但消失了scroll上去也不會變回來，需要table update
> 
> ![image](https://user-images.githubusercontent.com/18364699/95735693-bcbd4080-0cb7-11eb-874d-123f905c8d65.png)
> 
> https://codesandbox.io/s/antd-reproduction-template-forked-bvcd8?fontsize=14&hidenavigation=1&theme=dark

`getContainer`

**Comment by marklai1998** [comment]
> getContainer

@shaodahong 你看reproduce，已經調用getContainer

**Comment by shaodahong** [comment]
> > getContainer
> 
> @shaodahong 你看reproduce，已經調用getContainer

https://codesandbox.io/s/antd-reproduction-template-forked-kujt6

**Comment by marklai1998** [comment]
> > > getContainer
> > 
> > 
> > @shaodahong 你看reproduce，已經調用getContainer
> 
> [codesandbox.io/s/antd-reproduction-template-forked-kujt6](https://codesandbox.io/s/antd-reproduction-template-forked-kujt6)
> 
> ![image](https://user-images.githubusercontent.com/14831261/95736170-71576200-0cb8-11eb-9c6b-e2b0e7518162.png)

哦哦哦，doc寫錯了
謝謝

**Comment by marklai1998** [comment]
> > > getContainer
> > 
> > 
> > @shaodahong 你看reproduce，已經調用getContainer
> 
> [codesandbox.io/s/antd-reproduction-template-forked-kujt6](https://codesandbox.io/s/antd-reproduction-template-forked-kujt6)
> 
> ![image](https://user-images.githubusercontent.com/14831261/95736170-71576200-0cb8-11eb-9c6b-e2b0e7518162.png)

剛才的reproduce是打錯字sorry,但我這邊業務上確實是遇到了這問題
發現是跟tab的問題

再reproduce
https://codesandbox.io/s/antd-reproduction-template-forked-bvcd8?fontsize=14&hidenavigation=1&theme=dark

**Comment by shaodahong** [comment]
tab body 有个 `overflow: hidden`

**Comment by wwwxy80s** [comment]
> @shaodahong
> 
> 剛試了最新的4.7.0，scrollber 正確的放在scroll container 裏面
> 還是沒解決scrollbar出現和消失handler的bug
> 
> 圖例：table 已經scroll 到最底了，額外的scrollbar還不會消失，要用戶點一下
> 一但消失了scroll上去也不會變回來，需要table update
> 
> ![image](https://user-images.githubusercontent.com/18364699/95735693-bcbd4080-0cb7-11eb-874d-123f905c8d65.png)
> 
> reproduce:
> https://codesandbox.io/s/antd-reproduction-template-forked-bvcd8?fontsize=14&hidenavigation=1&theme=dark

我遇到了类似的问题，情况一模一样，请问你是怎么解决的啊，还有原因是什么呢

**Comment by wozaihouma** [comment]
看起来是table的 sticky 和 tabs 里面 ant-tabs 的overflow： hidden 冲突了， 给Tab 一个style 就ok了 
![image](https://user-images.githubusercontent.com/10495680/120445533-49d61680-c3bb-11eb-8866-228839fc8f03.png)
