### ISSUE TITLE
RangePicker placeholder not correct

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#26390]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/funny-diffie-cwob1?file=/index.js)

### Steps to reproduce
选择开始时间后，弹出结束时间面板，点击月份面板选择一个更早的月份，点击外侧关闭窗口。

![Kapture 2020-08-25 at 16 50 02](https://user-images.githubusercontent.com/5378891/91153846-53777300-e6f3-11ea-9be1-fe5ea3afae83.gif)

### What is expected?
没有 placeholder

### What is actually happening?
placeholder 错误展示

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | latest |
| System | IOS |
| Browser | chrome |

**Comment by zombieJ** [comment]
@Kermit-Xuan, pls help to take a look. thx~

**Comment by Kermit-Xuan** [comment]
OK，没考虑到点击月份和年份

**Comment by Kermit-Xuan** [comment]
但是有个问题，是不是点击月份的时候，不能点击开始日期之前的月份呀？

**Comment by zombieJ** [comment]
嗯，是的。这个我看看，placeholder 清理你看看。我们分开搞~

**Comment by zombieJ** [comment]
看了一下，似乎 disabledDate 修复应该就可以了。placeholder 重置应该不需要（帮我 double confirm 一下）。

**Comment by Kermit-Xuan** [comment]
如果 disableDate 修复了，这样就不会触发 hover 事件吧？如果是的话，placeholder 就不会变。

**Comment by zombieJ** [comment]
嗯，我也觉得。那应该没其他场景了~thx
