### ISSUE TITLE
expandedRowRender and components don't work together

### ISSUE THREAD

**Issue by raualvron** [ant-design/ant-design#26394]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-dg9nyq-wuaslj](https://stackblitz.com/edit/react-dg9nyq-wuaslj)

### Steps to reproduce
- Create a Table
- Use expandedRowRender passing a component as property
- Use components passing object with body along with wrapper and row 

### What is expected?
The expanded row must render a component which is passed as prop

### What is actually happening?
The row is not expanded when components are being used.

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | Ubuntu |
| Browser | Chrome |

**Comment by zombieJ** [comment]
<img width="561" alt="截屏2020-09-23 下午10 09 32" src="https://user-images.githubusercontent.com/5378891/94024009-77f56680-fde9-11ea-99e9-d38d44843c37.png">

Seems your demo work as expect.

**Comment by raualvron** [comment]
@zombieJ What happens if you click on the plus icon twice? Is the row expanded correctly?

**Comment by zombieJ** [comment]
<img width="977" alt="截屏2020-09-23 下午10 42 55" src="https://user-images.githubusercontent.com/5378891/94028080-20a5c500-fdee-11ea-9abb-ee98e34e85c0.png">

Your customize component not correct pass props to tr.
