### ISSUE TITLE
form.Item 中设置 initialValue，Upload组件中 defaultFileList 未显示

### ISSUE THREAD

**Issue by KingThq** [ant-design/ant-design#26393]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-form-upload-00cy2?file=/index.js)

### Steps to reproduce
点击重现链接，第一个是设置了 form 的 initialValues 可以显示文件列表；第二个设置 form.Item 的 initialValue 未显示文件列表

### What is expected?
在 form.Item 中设置 initialValue 可以显示已经上传的文件列表

### What is actually happening?
在 form.Item 中设置 initialValue 组件未显示已经上传的文件列表，设置 form 的 initialValues 则可以显示

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.8.6 |
| System | macOS |
| Browser | Chrome 84.0.4147.135 |

**Comment by Kermit-Xuan** [comment]
根本原因是因为 `defaultFileList`, 这个是默认的文件列表只会在组件挂载的时候用一次，后续就不会使用了。

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#It-doesn't-work-when-I-change-defaultValue-dynamically

**Comment by KingThq** [comment]
> 根本原因是因为 `defaultFileList`, 这个是默认的文件列表只会在组件挂载的时候用一次，后续就不会使用了。

针对我这个例子，怎样写才能展示默认的文件列表和上传的文件列表呢？

**Comment by Kermit-Xuan** [comment]
直接用 `fileList` 不行么？

**Comment by KingThq** [comment]
直接用 fileList 会把默认的文件列表替换了，因为我是用在 form 下的，每次上传成功后都会调用 onChange

**Comment by Kermit-Xuan** [comment]
https://ant.design/components/upload-cn/#components-upload-demo-picture-card 这个例子就用的 `fileList`, 有初始值，上传新文件后会追加不会替换

**Comment by KingThq** [comment]
请看这个示例：https://codesandbox.io/s/antd-form-upload-00cy2?file=/UploadBtn.js
