### ISSUE TITLE
ant-select下拉列表中，已选择的值需要被删除的问题

### ISSUE THREAD

**Issue by konce** [ant-design/ant-design#264]
```` javascript
<Select combox filterOption={false}>
    // ...
</Select>
````
## 以上是基础代码

我在这个下拉列表中，选中了某个选项，然后我在别的操作中，需要清除这个下拉列表的输入框的值，请问怎么处理？`value` 和 `defaultValue`处理不了这个情况

**Comment by yiminghe** [comment]
try beta10

使用 value 属性

**Comment by yiminghe** [comment]
0.9.0 应该是 ok 的

**Comment by konce** [comment]
赞，谢谢

2015-09-14 20:51 GMT+08:00 yiminghe <notifications@github.com>:

> Closed #264 <https://github.com/ant-design/ant-design/issues/264>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/264#event-408614950>.
>



-- 

Best Regards!

Xiaojun Kang
Phone:(+86)18676653071

**Comment by konce** [comment]
[image: 内嵌图片 1]
0.9.0的点击弹层里面的时间控件，时间控件在zIndex下面

2015-09-16 14:09 GMT+08:00 康晓军 <kxj0206@gmail.com>:

> 赞，谢谢
>
> 2015-09-14 20:51 GMT+08:00 yiminghe <notifications@github.com>:
>
>> Closed #264 <https://github.com/ant-design/ant-design/issues/264>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ant-design/ant-design/issues/264#event-408614950>.
>>
>
>
>
> --
>
> Best Regards!
>
> Xiaojun Kang
> Phone:(+86)18676653071
>



-- 

Best Regards!

Xiaojun Kang
Phone:(+86)18676653071

**Comment by konce** [comment]
已使用value ，但还是不行

2015年9月12日星期六，yiminghe <notifications@github.com> 写道：

> try beta10
>
> 使用 value 属性
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/264#issuecomment-139711279>
> .
>


-- 

Best Regards!

Xiaojun Kang
Phone:(+86)18676653071

**Comment by konce** [comment]
ok 要更新版本？我发现你们beta4有问题

2015年9月12日星期六，yiminghe <notifications@github.com> 写道：

> try beta10
>
> 使用 value 属性
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/264#issuecomment-139711279>
> .
>


-- 

Best Regards!

Xiaojun Kang
Phone:(+86)18676653071

**Comment by haoxins** [comment]
> 需要清除这个下拉列表的输入框的值

@konce  解决方案是?

**Comment by konce** [comment]
try beta10

使用 value 属性

2015-10-15 20:17 GMT+08:00 haoxin <notifications@github.com>:

> 需要清除这个下拉列表的输入框的值
>
> @konce <https://github.com/konce> 解决方案是?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/264#issuecomment-148368977>
> .
>



-- 

Best Regards!

Xiaojun Kang
Phone:(+86)18676653071

**Comment by yiminghe** [comment]
怎么还是 beta，目前是 0.9.1

**Comment by konce** [comment]
那你就用最新的就好拉

2015-10-17 0:29 GMT+08:00 yiminghe <notifications@github.com>:

> 怎么还是 beta，目前是 0.9.1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/264#issuecomment-148761720>
> .
>



-- 

Best Regards!

Xiaojun Kang
Phone:(+86)18676653071
