### ISSUE TITLE
A required Input in Form, should it not be passed when user only input space?

### ISSUE THREAD

**Issue by aditya-lw** [ant-design/ant-design#26404]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#components-form-demo-validate-static](https://ant.design/components/form/#components-form-demo-validate-static)

### Steps to reproduce
Open the link and tick the required checkbox.

### What is expected?
Required Input should not accept if only blank spaces are passed

### What is actually happening?
It is accepting space.

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16 |
| System | linux 18 |
| Browser | chrome latest |

**Comment by afc163** [comment]
```diff
        rules={[
          {
            required: true,
+           whitespace: true,
            message: 'Please input your username!',
          },
        ]}
```
