### ISSUE TITLE
Alphabetical sorting of options in a Select Component

### ISSUE THREAD

**Issue by rafafernandezlopez** [ant-design/ant-design#26414]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
At selection components, the closest option should appear as a first match, not as now , that the first match is the first option element , for example, for the following input options data resource:
~~~javascript
const IncidencesStateResource = [
  {    Id: 4,    Name: "Not Identified"  },
  {    Id: 3,    Name: "Closed"  },
  {    Id: 2,    Name: "Communicated"  },
  {    Id: 6,    Name: "Identified"  },
  {    Id: 1,    Name: "Resolved"  },
  {    Id: 5,    Name: "Cancelled"  }
];
~~~
When we instantiate the component as follows:
~~~javascript
 <span>*Select without sorting</span>
    <Select
      showSearch
      style={{ width: 200, margin: "10px" }}
      placeholder="Select a Incidence State"
      optionFilterProp="children"
      filterOption={(input, option) =>
        option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0
      }
    >
      {IncidencesStateResource.map((incidences) => (
        <Option key={incidences.Id} value={incidences.Id}>
          {incidences.Name}
        </Option>
      ))}
    </Select>
~~~

And we search for "Identified, the first match exposed, would be "Not Identified", rather than "Identified", which would be the closest match.

To resolve this problem, I propose sort the data with a similar function as that, but as native mode inside the select component:

~~~javascript
/**
 * Order function by key.
 * @default "asc"
 * data => field to order (Object, List, Array).
 * key => the data to be order by this key.
 */
function orderListByKey(data, key, order) {
  const compareValues = (key, order = "asc") => (elemA, elemB) => {
    if (!elemA.hasOwnProperty(key) || !elemB.hasOwnProperty(key)) return 0;
    const comparison = elemA[key].localeCompare(elemB[key]);
    return order === "desc" ? comparison * -1 : comparison;
  };
  return data.sort(compareValues(key, order));
}
~~~

And when we use this functionality: 

~~~javascript
    <span>*Select with sorting</span>
    <Select
      showSearch
      style={{ width: 200, margin: "10px" }}
      placeholder="Select a Incidence State"
      optionFilterProp="children"
      filterOption={(input, option) =>
        option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0
      }
    >
      {orderListByKey(IncidencesStateResource, "Name").map((incidences) => (
        <Option key={incidences.Id} value={incidences.Id}>
          {incidences.Name}
        </Option>
      ))}
    </Select>

~~~

And  when we search for "Identified, the first match exposed, will be "Identified", and not "Not Identified".

### What does the proposed API look like?
To solve the problem, I propose have in the <Select> a new prop called, (order, sort, sorting, etc), to sort the Options group, by ascend or descent alphabetical sorting, with the data fields options to sort, the sorting key, and optionally the sort direction.

You can see the next codesandbox example:

https://codesandbox.io/s/sorting-options-select-antd-e2x0n?file=/index.js

**Comment by n0ruSh** [comment]
@rafafernandezlopez are you working on implementing this feature? If no, I would like to give it a go

**Comment by rafafernandezlopez** [comment]
Yes of course, feel free!

**Comment by JonhnyDev** [comment]
how do i disable this function of my select? in my case I need it to be presented exactly as it is created ?

**Comment by Nopparato** [comment]
<AnSelect
  showSearch
  // value={selectedItems}
  // defaultValue={{ key:"all", value:"all", label:"all" }}
  placeholder="aLL"
  onChange={e => handlePOStatus(e)}
  style={{ width: '100%' }}
  filterOption={(input, option) => option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0}
  // filterSort={(optionA, optionB) => optionA.children.toLowerCase().localeCompare(optionB.children.toLowerCase())}
  filterSort={(optionA, optionB) => (optionA.id > optionB.id) ? -1 : 1} 
>
  <Option key="all" value="all">all</Option>
  {options.map((option) => (
    <Option key={option.id} value={option.id}>{option.nameTh}</Option>
  ))}
</AnSelect>

[ ]
