### ISSUE TITLE
table拖动列，表现错误

### ISSUE THREAD

**Issue by T-Inphic** [ant-design/ant-design#26413]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/u65r2?file=/index.js)

### Steps to reproduce
1、拖动任一列到最右端
2、向右拖动任一列（除步骤1），出现第一个bug
3、向左拖动步骤1那一列，出现第二个bug
4、向左拖动步骤2那一列，右侧所有列都跟随（不知道是不是设计如此）

### What is expected?
解决以上bug

### What is actually happening?
不做跟随处理

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 17.0.0 |
| System | win10 |
| Browser | chrome 84.0.4147.135 |

**Comment by afc163** [comment]
不太理解具体的行为是啥，第一个 bug 和 第二个 bug 分别是什么？

**Comment by T-Inphic** [comment]
> 不太理解具体的行为是啥，第一个 bug 和 第二个 bug 分别是什么？
第一个bug不是太好描述，就是鼠标移动的距离跟操作列不同步，而且前面几列会向反方向移动
第二个bug就是步骤二那一列和鼠标移动方向相反（况且此时操作的是步骤一）

你可以点上方的codeSandBox按照步骤操作一下就很明白了

**Comment by afc163** [comment]
> 你可以点上方的codeSandBox按照步骤操作一下就很明白了

我看到的和你看到的不一定是一样的情况，看到一样的情况理解的方式也不一定一样，最好用文字描述清楚，并配上相关的 gif 或录屏。

**Comment by T-Inphic** [comment]
> > 你可以点上方的codeSandBox按照步骤操作一下就很明白了
> 
> 我看到的和你看到的不一定是一样的情况，看到一样的情况理解的方式也不一定一样，最好用文字描述清楚，并配上相关的 gif 或录屏。

![示例](https://user-images.githubusercontent.com/19276771/91625073-e9065180-e9d6-11ea-919b-5995443ac8e0.gif)
这是官网的一个可伸缩列示例，可以参考操作一下

**Comment by xiexingen** [comment]
也遇到过 就是那个拖拽的时候快一点的话 鼠标的样式没有保持同步，感觉是内部拖拽的时候实时在render导致的，这应该可以优化下

**Comment by afc163** [comment]
这个例子有很多交互问题，目前不太好修，暂时隐藏了。

https://github.com/ant-design/ant-design/commit/84c65582c71c66df9744177d337cfd3d4ce1a713
