### ISSUE TITLE
Lags when click on expand icon with many childs

### ISSUE THREAD

**Issue by EarlOld** [ant-design/ant-design#26411]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-lags-render-childs-1xnt8)

### Steps to reproduce
1. Create table
2. Add to row many children 
3. Click to expand icon 

### What is expected?
Fast expanding 

### What is actually happening?
Delay in 5s in sandbox, in my app with custom render function -  10s

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12.0 |
| System | win 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Please fix duplicated rowKey `email` in data: https://codesandbox.io/s/antd-lags-render-childs-forked-fl6kk?file=/src/index.js 

It will be much faster.
