### ISSUE TITLE
Table组件的columns[].render支持传递array，并对样式支持

### ISSUE THREAD

**Issue by 4tj** [ant-design/ant-design#26415]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前Table组件的columns配置中，render实际上是可以传递数组的。希望能够对传递数组组件时，用`<Space>`包裹一下，设置间距。这个对于最后一列是“操作”的列很实用的。另外文档里也可以写出来支持Array<Component>

### What does the proposed API look like?
```javascript
const columns = [ 
  {
    title: '操作',
    render: (_, record) => [
        <a key="opt-lock">解锁</a>,
        <a key="opt-dl-tpl">下载模板</a>,
        <a key="opt-dl-csv">下载数据</a>,
    ],
  },
]
```

**Comment by zombieJ** [comment]
ReactNode 里本身就包含了数组类型。这种 Space 包裹建议上层封装，对用户样式侵入性太大。
