### ISSUE TITLE
Space组件内部使用Fragment标签时，Fragment标签被识别为一个Space的子项

### ISSUE THREAD

**Issue by Loving-Vincent** [ant-design/ant-design#26420]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-bhabha-z8pg6?file=/index.js)

### Steps to reproduce
Antd 4.6.0 之后， Space组件内部使用的Fragment标签出现问题，导致Fragment标签内部所有元素被识别为一个space-item，不符合Fragment标签的使用逻辑。4.6.0之前的版本是OK的，可能是4.6修改Space时引发了这个问题。

![image](https://user-images.githubusercontent.com/36978364/91291892-4f695500-e7c8-11ea-9cc9-8385e49505f1.png)

![image](https://user-images.githubusercontent.com/36978364/91291989-7b84d600-e7c8-11ea-9b90-2f2a2860b47a.png)

### What is expected?
正确解析Fragment标签，并将Fragment内部所有元素解析为一个单独space的子项。

### What is actually happening?
Space组件将Fragment解析为一个子项

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | ^16.12.0 |
| System | MacOS |
| Browser | Chrome 84 |

**Comment by xrkffgg** [comment]
建议
```
<Space>
    Space
    <Space>
        <Button type="primary">Button</Button>
        <Button type="primary">Button</Button>
    </Space>
    <Button type="primary">Button</Button>
    <Upload>
        <Button>
            <UploadOutlined /> Click to Upload
        </Button>
    </Upload>
</Space>
```

**Comment by zombieJ** [comment]
蛋疼，`rc-util` 的 toArray 拓展一下好了。否则又要完成重复一遍这个代码。
