### ISSUE TITLE
Select 标签模式，剪切板的内容有前导换行，在 IE11 下无法粘贴

### ISSUE THREAD

**Issue by winguse** [ant-design/ant-design#2642]
#### 本地环境

- antd 版本: 1.8.0
- 操作系统及其版本：Windows 10
- 浏览器及其版本: IE 11

#### 你做了什么？

复制文本内容包含前导回车符，例如：`\n\naaaa`。

#### 你期待的结果是：

Ctrl + V 粘贴到Select标签模式，可以粘贴进去，并且 trim 掉回车符。这在Chrome是正常的，IE11不是。

#### 实际上的结果：

Ctrl + V 粘贴到Select标签模式，无法粘贴进去。

#### 可重现的在线演示

用 IE 11 打开 http://ant.design/components/select/ 中的标签代码演示即可测试。

**Comment by afc163** [comment]
浏览器对规范的实现问题，存在所有原生 input 上，和 Select 本身没联系。

组件层面还是不做改造了。

相关兼容方案可参考：http://brandonpugh.com/blog/2011/10/allow-pasting-multiple-lines-in-ie-textbox/
