### ISSUE TITLE
水印组件需求.

### ISSUE THREAD

**Issue by l745230** [ant-design/ant-design#26425]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
页面添加水印

### What does the proposed API look like?
<Watermark text={`currentUser?.name`}>{children}</Watermark>

看到官方对alitajs的推荐
https://github.com/ant-design/ant-design/issues/26358

然后尝试了一下.发现改变水印文字后,水印丢失的问题.
提了issue https://github.com/pansyjs/react-watermark/issues/3 ,
好像也没人跟进... start/fork也少,怎么看都像是个自娱自乐的东西....

现在涉及金融,安全方面的要求越来越高,页面水印需求也水涨船高, 
AntDesign能否出个官方的水印组件呢

毕竟蚂蚁出品,必属精品,用起来也更安心

**Comment by afc163** [comment]
暂时没精力做，欢迎你来贡献一个。

**Comment by wangxingkang** [comment]
问题修复了，公司有需求，临时写了个，还是有很多问题的，欢迎PR

**Comment by afc163** [comment]
https://antd-plus.alitajs.com/components/data-display/watermark

**Comment by wangxingkang** [comment]
https://github.com/pansyjs/watermark  提取了无任何依赖的JS库，欢迎试用
