### ISSUE TITLE
Need a new style of InputNumber

### ISSUE THREAD

**Issue by chaoers** [ant-design/ant-design#26428]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A flat input number is common to use in many scenes.
扁平化的数字输入框在很多设计中被经常使用

### What does the proposed API look like?
A new api such as "style" to control it's style.

**Comment by chaoers** [comment]
this is a example in element
https://element.eleme.cn/#/zh-CN/component/input-number

**Comment by afc163** [comment]
In Ant Design, We don't support this kind of InputNumber.
