### ISSUE TITLE
Allow customization of ant-table-cell-placeholder in <Table/>

### ISSUE THREAD

**Issue by LeeRayno** [ant-design/ant-design#26423]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Allow setting any React component as a placeholder for an empty table cell when some **cell** data is empty! 
when the some cell's data is empty not Manual set the column render function to set the empty placeholder!  
I want to set a table props `cellPlaceholder` to set the cell placeholder for all the Table that don't write render function many times!

[codepen](https://codesandbox.io/s/funny-heyrovsky-ibwdm?file=/index.js)

![placeholder](https://tva1.sinaimg.cn/large/007S8ZIlgy1gi4n3d35yzj30ua0ty765.jpg)

```js

const columns = [
  {
    title: "Name",
    dataIndex: "name",
    render: (text) => <a href="#">{text}</a>
  },
  {
    title: "Age",
    dataIndex: "age",
    render: (text) => text || "--" // again and again
  },
  {
    title: "Address",
    dataIndex: "address",
    render: (text) => text || "--" // when the address is empty I have to  write the render function to set the empty placeholder again and again
  },
  {
    title: "placeholder",
    dataIndex: "placeholder",
    render: (text) => text || "--" // again and again
  }
];

const data = [
  {
    key: "1",
    name: "John Brown",
    age: 32,
    address: "New York No. 1 Lake Park",
  },
  {
    key: "2",
    name: "Jim Green",
    age: 42
    // address: "London No. 1 Lake Park"
  },
  {
    key: "3",
    name: "Joe Black",
    age: 32,
    address: "Sidney No. 1 Lake Park",
    placeholder: "placeholder"
  },
  {
    key: "4",
    name: "Disabled User",
    age: 99,
    address: "Sidney No. 1 Lake Park"
  }
];

```

### What does the proposed API look like?
```js
<Table 
    …
    cellPlaceholder={()=><div>some component<div/>}
    …
/>
```

**Comment by afc163** [comment]
A tricky way is

```css
.ant-table-cell:empty:after {
  content: '--';
}
```

**Comment by LeeRayno** [comment]
```css
.ant-table-cell:empty:before {
  content: '--';
}
```
should use` :before`, because fixed column's shadow style use `:after`, they are conflict!

**Comment by tangmingze7280** [comment]
file

**Comment by tangmingze7280** [comment]
在哪里加啊
