### ISSUE TITLE
upload 组件在 form 下使用 customRequest 方法，onChange 只触发一次

### ISSUE THREAD

**Issue by KingThq** [ant-design/ant-design#26427]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/upload-onchange-wdspg?file=/index.js)

### Steps to reproduce
打开链接，点击上传，查看 console 打印

### What is expected?
onChange 被完整调用

### What is actually happening?
onChange 只调用一次

| Environment | Info |
|---|---|
| antd | 4.3.1 |
| React | 16.8.6 |
| System | macOS |
| Browser | Chrome 84.0.4147.135 |

**Comment by afc163** [comment]
感觉和最近 filed-form 里面的一些改动有关系。

把 Upload 拿出 Form 就正常了：https://codesandbox.io/s/upload-onchange-forked-qzu58

**Comment by KingThq** [comment]
对，Upload 不放在 Form 里面是正常的。目前有这样的需求，应该怎么实现呢？

之前也尝试过其他方法 https://codesandbox.io/s/antd-form-upload-00cy2?file=/UploadBtn.js 但是存在一些问题（默认的文件列表会被新上传的覆盖掉），请问有好的解决方法吗？

**Comment by zombieJ** [comment]
看了是 Upload 重构导致的问题。受控下同步操作会导致 fileList 先被重置到空，在通过 effect 设置列表，使得中间的 onProgress & onSuccsee 全部丢失掉。
云凤蝶最近也遇到了卡死的问题，弄不出简单重现。这个重现救火了，thx！~
