### ISSUE TITLE
<Select> can not work in shadow dom,(Select组件无法在shadow节点中使用)

### ISSUE THREAD

**Issue by demonskp** [ant-design/ant-design#26435]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/busy-buck-q5zck?file=/index.js)

### Steps to reproduce
打开链接 
点击输入框(无法正常弹出options)

### What is expected?
focus时能正常弹出options

### What is actually happening?
focus时不能正常弹出options

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | windwos |
| Browser |  Chrome 84.0.4147.135 |

---
在shadow dom中无法使用antd嘛？

**Comment by afc163** [comment]
应该是可以用的，目测问题和 antd 关系不大，你需要解决外部样式如何在 shadow dom 里生效的问题。

**Comment by demonskp** [comment]
应该并不是外部样式的问题，我已经通过to-string-loader将样式放在shadow dom内了。
同时 我观察到的情况是当focus在input内的时候，正确的类会先被加载又被取消，然后style内决定弹出options位置的top和left并不会出现。
看上去比较像计算位置时失败。

**Comment by demonskp** [comment]
更加完整的例子

https://codesandbox.io/s/busy-buck-q5zck?file=/index.js

**Comment by afc163** [comment]
目前 antd 没有针对 shadow dom 做过测试，欢迎找出问题直接给我们 PR。

**Comment by tageecc** [comment]
@demonskp 解决了吗，我也碰到类似的问题

**Comment by demonskp** [comment]
> @demonskp 解决了吗，我也碰到类似的问题

不支持就是不支持，我自己写了一个组件用。
