### ISSUE TITLE
Table 组件在设置了 scroll.y 的同时如果 columns 配置中存在空白列，表头渲染错误

### ISSUE THREAD

**Issue by debuggerccai** [ant-design/ant-design#26438]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/festive-buck-imvvz?file=/index.js)

### Steps to reproduce
1. 在 columns  中增加一条空白列配置为 { title: '', dataIndex: 'empty' } 
2. 设置 scorll.y 为任意数值
3. 表头空白，检查 dom 发现表头的计算没有完成，且 table 标签样式为 table-layout: fixed; visibility: hidden;

### What is expected?
表头正常展示

### What is actually happening?
表头空白

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.0 |
| System | macos&window |
| Browser | chrome(84.0.4147.125) |

---
实际开发中为了实现可拖动列，如果不设置空白列的话，当列宽总和不足 scroll.x 的时候列宽被拉伸了。旧版本没有遇到过这个问题，升级后调试了很久找出了原因，是不是某个计算表头的方法调整后造成的？

**Comment by debuggerccai** [comment]
我在将依赖的 rc-table 降级到 7.8.4 版本后修复了这个问题，但是不确定这样做会不会导致部分 Table 组件的新功能失效。希望官方能够关注一下这个问题

**Comment by zombieJ** [comment]
Mini reproduce: https://codesandbox.io/s/youthful-lumiere-0tkot?file=/index.js

**Comment by debuggerccai** [comment]
> Mini reproduce: https://codesandbox.io/s/youthful-lumiere-0tkot?file=/index.js

还是不行

**Comment by debuggerccai** [comment]
> Mini reproduce: https://codesandbox.io/s/youthful-lumiere-0tkot?file=/index.js
还是不行

**Comment by Mr-FSM** [comment]
> > Mini reproduce: https://codesandbox.io/s/youthful-lumiere-0tkot?file=/index.js
> > 还是不行

遇到同样的问题，发现是columns多插入了一行而导致的hidden
![image](https://user-images.githubusercontent.com/25889758/155131847-f98b8fab-84f0-4ae2-9047-2bde3ef619bb.png)
![image](https://user-images.githubusercontent.com/25889758/155131980-f38a0455-cbef-4be3-97bb-6d5532260637.png)
