### ISSUE TITLE
Upload组件在多文件上传时，onChange事件的fileList属性不正常

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#26436]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antdV4.4.2是正常的
antdV4.6.1是不正常的

### What does the proposed API look like?
Upload组件在多文件上传时，onChange事件的fileList属性能够记录所有文件列表

4.4.2版本
![image](https://user-images.githubusercontent.com/8730272/91421002-f8c35000-e887-11ea-9ea1-9bb3b3aec5a7.png)

**Comment by Kermit-Xuan** [comment]
给个复现的 codesandbox 栗子

**Comment by phoema** [comment]
抱歉，我回滚版本了，4.4.2正常。
具体表现就是我在Form里包裹了支持多文件上传的组件
                                <Upload.Dragger
                                    multiple={true}
                                    name="file"
                                    action={ossHost + "oss/material/" + OssInfo.AppCode() + "/uploadMaterial"}
                                    data={{ appid: OssInfo.AppId, appsecret: OssInfo.AppSecret }}
                                    beforeUpload={beforeUpload}
                                    onChange={onUploadChange}
                                    showUploadList={false}
                                    fileList={state.fileList}
                                >
                                    <p className="ant-upload-drag-icon">
                                        <InboxOutlined />
                                    </p>
                                    <p className="ant-upload-text">上传文件 （仅支持图片、PDF、WORD、ZIP 格式）</p>
                                    <p className="ant-upload-text"><font color="red">注：</font>文件名称如为CPC代码或标准名称可智能识别</p>
                                </Upload.Dragger>


在onChange事件中的第二个参数fileList只能拿到一个文件对象
    onUploadChange = ({ file, fileList }) => {
        //文件过大或上传失败等原因不添加此文件到this.state.fileList;
        if (file.status==undefined) {
            return;
        }
        if (file.status=='error'){
            this.state.loading=false;
            return;
        }
        if (file.status=='done'){
            this.state.loading=false;
            let fileItem= fileList.find(e=>e.uid==file.uid);
            let item= fileItem.response.data[0];

            let fileName = item.originalName.substring(0,item.originalName.length - item.objType.length -1);
            // 根据文件名称查找CPC匹配项
            let cpcInfo=cpcFileType.find(i=>i.id==fileName || i.name==fileName);
            if(cpcInfo){
                fileItem.cpcId = cpcInfo.id;
                fileItem.cpcName = cpcInfo.name;
                this.fileTypeOnChange(fileItem.cpcId,fileItem.uid);
            }
        }
        this.state.fileList = fileList;
    }

**Comment by Kermit-Xuan** [comment]
麻烦提供一个 codesandbox 的复现链接，https://codesandbox.io/s/antd-reproduction-template-6e93z

**Comment by Kermit-Xuan** [comment]
应该和这个一样的 https://github.com/ant-design/ant-design/issues/26427

**Comment by phoema** [comment]
我尝试在codesandbox复现，复现不了，看了这个#26427，很可能是外面没套form导致复现不了。。。
很抱歉啊，从系统中的代码原子化复现到codesandbox太难了

**Comment by Kermit-Xuan** [comment]
可以等 `antd@4.6.2` 发布后试试看有没有修复。

**Comment by zeya-liu** [comment]
请问fileList属会一直记录之前上传的文件信息，这个这么解决呀？例子https://codesandbox.io/s/antd-reproduction-template-forked-u4ye5?file=/index.js
