### ISSUE TITLE
form.getFieldInstance()表单获取不到动态创建字段的实例

### ISSUE THREAD

**Issue by jin-benben** [ant-design/ant-design#26434]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-wiles-yknsg?file=/index.js:382-403)

### Steps to reproduce
打开链接，添加字段，点击提交，打印控制台输出

### What is expected?
form.getFieldInstance()能获取到动态创建的字段的实例

### What is actually happening?
获取不到

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12.0 |
| System | win7 |
| Browser | chrome版本 84.0.4147.135（正式版本） （64 位） |

**Comment by zombieJ** [comment]
Form.List 不是一个 instance。Form.Item 才是：
https://codesandbox.io/s/jovial-minsky-b264e?file=/index.js
