### ISSUE TITLE
Select组件没有通过内部函数获得value显示值

### ISSUE THREAD

**Issue by rxt2012kc** [ant-design/ant-design#2643]
#### 本地环境

- antd 版本:
- 操作系统及其版本：
- 浏览器及其版本:

#### 你做了什么？

 引入 antd 了 Select，除了通过onChange等事件触发函数，无法得到select显示的值

#### 你期待的结果是：
通过类似的函数，this.refs.select.getValue()，得到select显示的值

#### 实际上的结果：
暂不支持得到select正在显示的值的函数

**Comment by benjycui** [comment]
Duplicated: https://github.com/ant-design/ant-design/issues/388

**Comment by benjycui** [comment]
Please read [documentation](http://ant.design/#/) & [FAQ](https://github.com/ant-design/ant-design/wiki/FAQ) and search [issues](https://github.com/ant-design/ant-design/issues) before open an issue, THX!

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](http://doc.zengrong.net/smart-questions/cn.html)).

**Comment by rxt2012kc** [comment]
so it doesn't have a function to get the value, only by onChange and so on to get the value ?
