### ISSUE TITLE
Select Component 's value is null, but show clear icon, is it should hide ? 

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#26432]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/dolov/pen/mdPmRWy?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fselect-cn%2F](https://codepen.io/dolov/pen/mdPmRWy?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fselect-cn%2F)

### Steps to reproduce
https://codepen.io/dolov/pen/mdPmRWy?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fselect-cn%2F

### What is expected?
not show clear icon

### What is actually happening?
show clear icon

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by afc163** [comment]
See #2367
