### ISSUE TITLE
Icon 组件 希望能够提供一个获取当前版本Icon所有名称的一个方法

### ISSUE THREAD

**Issue by shenzhenxianba** [ant-design/ant-design#26440]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在安装ant-design/icons 后 可以通过某个方法直接获取到当前库内所有的图标名称等信息

### What does the proposed API look like?
import {getIconName} from '@ant-design/icons'     调用   getIconName（）    获取一个数组列表 [name1,name2,name3,name4,.......]   当然数组内也可以是包括名字在内的一个对象

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/25559#issuecomment-656571636
