### ISSUE TITLE
Add option to show pagination when dataSource is empty

### ISSUE THREAD

**Issue by chiptoe** [ant-design/ant-design#26441]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Take an example, in url query you have page=2000, but API results with filled array only for pages 1 and 2. In case API for page=2000 does not return data for last page which is 2 but for page 2000, data will be empty array.

In result for page 2000, table displays empty state "No data", but also does not render pagination (that is current ant table behaviour), so user is unable to navigate to existing page.

Currently I can hack fix with custom row function and replacing dataSource [] to [{}], so row is rendered:
```
         const emptyRow = <tr>
		<td colSpan={props.columns?.length}>
			<Empty
				style={{ width: '100%' }}
				image={Empty.PRESENTED_IMAGE_SIMPLE}
				description={props.emptyText}
			/>
		</td>
	</tr>

	const fixPaginationComponents = isEmpty(props.dataSource) ? {
		body: {
			row() {
				return emptyRow
			}
		}
	} : undefined
	const fixPaginationDataSource = isEmpty(props.dataSource) ? [{}] as any : props.dataSource

	return <Table
		pagination={props.pagination && {
			...props.pagination,
			onChange
		}}
		dataSource={fixPaginationDataSource}
		components={fixPaginationComponents}
		locale={emptyLocale}
	/>
```

At page 2000 table pagination should look something like this:
![image](https://user-images.githubusercontent.com/13163919/91459689-3378b880-e887-11ea-82e8-a067fd1c0ed5.png)

### What does the proposed API look like?
```
<Table
      showPaginationWhenEmptyDataSource
```

**Comment by zombieJ** [comment]
When you provides pagination total count. It will not disappear. Pls follow ajax example instead: https://ant.design/components/table-cn/#components-table-demo-ajax

**Comment by chiptoe** [comment]
Actually pagination is not rendered, I tried that example with no success: https://codesandbox.io/s/inspiring-browser-lgriu?file=/index.js

**Comment by zombieJ** [comment]
ref #26143
