### ISSUE TITLE
表单相关的组件获取焦点的时候，为什么有些组件有box-shadow，有些没有

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#26448]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
比如官网的这个例子：https://codesandbox.io/s/h866z?file=/index.js

### What does the proposed API look like?
可否统一让表单相关组件focus的时候都有box-shadow呢

**Comment by Leo4815162342** [comment]
Might be related to the recent "fix": https://github.com/ant-design/ant-design/pull/26255

**Comment by xrkffgg** [comment]
@Leo4815162342 That's not the reason.
