### ISSUE TITLE
Ant design version (4.6.1) - Bugs 

### ISSUE THREAD

**Issue by illusi03** [ant-design/ant-design#26442]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/pull/26347#issuecomment-679847924](https://github.com/ant-design/ant-design/pull/26347#issuecomment-679847924)

### Steps to reproduce
When i have upgraded Ant Version in 4.6.1, 
I got error : 
@table-header-sort-active-filter-bg: lighten(@table-header-sort-active-bg, 2%);
@table-sticky-zindex: @zindex-table-fixed   1;
^
Operation on an invalid type
      Error in /home/azhari/data/laravel/bookmarker_react/node_modules/antd/es/table/style/index.less (line 12, column 0)

But, when i downgrade into < 4.6.x, its solve.

Already delete YARN.LOCK still same, thanks before

### What is expected?
Can build and normally run

### What is actually happening?
When i have upgraded Ant Version in 4.6.1, but error.
But, when i downgrade into < 4.6.x, its solve.
Already delete YARN.LOCK still same, thanks before

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | Ubuntu 20.04 |
| Browser | Chrome  |

**Comment by zchuhui** [comment]
When I upgraded to 4.6.0, I reported the same error....

**Comment by yoyo837** [comment]
Try remove `node_modules`, `package-lock.json` or `yarn.lock` and reinstall it.

**Comment by zchuhui** [comment]
> Try remove `node_modules`, `package-lock.json` or `yarn.lock` and reinstall it.

nice!

**Comment by YanYuanFE** [comment]
less降到3.x

**Comment by afc163** [comment]
升级 less 版本到 4.1.0 以上，或升级 antd 到最新。
