### ISSUE TITLE
Space内使用React.Fragment或<></>包裹的时候，size失效

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#26449]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zen-glitter-bqgbz?file=/index.js:286-300)

### Steps to reproduce
按标题描述操作

### What is expected?
size正常有效

### What is actually happening?
size失效

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | window 10 |
| Browser | chrome 83.0.4103.61 |

**Comment by afc163** [comment]
Fixed in #26444
