### ISSUE TITLE
badge 徽标数 数字错位

### ISSUE THREAD

**Issue by MinJieLiu** [ant-design/ant-design#2644]
http://ant.design/components/badge/

- antd 版本: 官网演示
- 操作系统及其版本：Window 8.1
- 浏览器及其版本: Chrome 49

#### 你做了什么？

打开页面微标错位

#### 你期待的结果是：

能正常显示

**Comment by benjycui** [comment]
或者是因为你的浏览器缩放了？

**Comment by afc163** [comment]
无法重现。

**Comment by MinJieLiu** [comment]
对，1080p 的笔记本默认是125%的缩放，公司的台式机看不出问题，只有笔记本才会出现
