### ISSUE TITLE
Table 组件使用 sticky 属性会导致整个页面无法用光标选中文字

### ISSUE THREAD

**Issue by myvipbackup2** [ant-design/ant-design#26457]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table-cn/](https://ant.design/components/table-cn/)

### Steps to reproduce
访问官方文档Table页面，无法使用光标选中任何文本，只能双击选中

### What is expected?
属性 sticky={true} 时，页面能被光标正常选中文本

### What is actually happening?
属性 sticky={true} 时，页面无法被光标选中任何文本

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | MacOS 10.15.6 |
| Browser | Chrome 85.0.4183.83 |

---
禁用 JS 后可导致问题消失，初步排查非 CSS 导致 的问题

**Comment by yoyo837** [comment]
Duplicated of #26379

**Comment by xrkffgg** [comment]
Duplicate of #26379

**Comment by littlepoolshark** [comment]
哪个版本的antd修复了这个问题呢？ 发版了吗？

**Comment by yoyo837** [comment]
删除node_modules、package-lock.json 或者 yarn.lock 重新安装即可

**Comment by littlepoolshark** [comment]
好的，谢谢。
