### ISSUE TITLE
Upload组件：onChange默认的第一个参数是一个包含file,fileList,event的对象，如果我想在原有基础上扩展参数如何做？

### ISSUE THREAD

**Issue by HomyeeKing** [ant-design/ant-design#26459]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cxvzm?file=/Upload.js)

### Steps to reproduce
`onChange` 的 参数问题，如果想添加一个回调函数，如何处理

### What is expected?
期望的是通过回掉来处理上传文件成功的结果

### What is actually happening?
实际无法添加回调

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.3.1 |
| System | mac |
| Browser | chrome newest |

**Comment by yoyo837** [comment]
没太看懂意思

**Comment by HomyeeKing** [comment]
> 没太看懂意思

onChange() 不是有回调吗，应该默认就是第一个参数，如果想扩展参数怎么在不破坏回调参数的基础上扩展，可以点sandbox看看呐

**Comment by yoyo837** [comment]
你想扩展什么参数？在onChange接口固定提供这么多数据的情况下，你拓展和onChange本身没关系吧？

**Comment by HomyeeKing** [comment]
> 你想扩展什么参数？在onChange接口固定提供这么多数据的情况下，你拓展和onChange本身没关系吧？

首先明确一个问题，上传文件之后 服务器的返回值只能通过`onChange`的回调获取吧

**Comment by yoyo837** [comment]
是

**Comment by HomyeeKing** [comment]
> 是

@yoyo837  我扩展参数就是想加个回调函数处理服务器返回来的数据啊，要不然一个上传组件写一个change多麻烦

**Comment by yoyo837** [comment]
不好意思，还是没明白啥意思。如果是嫌弃声明的onChange过多，你可以自行抽取函数或者二次封装。

**Comment by zombieJ** [comment]
自己封装一下就行了。

**Comment by HomyeeKing** [comment]
> 不好意思，还是没明白啥意思。如果是嫌弃声明的onChange过多，你可以自行抽取函数或者二次封装。

@yoyo837  就是想封装啊，通过添加回调来具体指定函数操作服务端返回值
