### ISSUE TITLE
Table join tree checkbox function  ,children can't  checked. 表格加入树状结构和checkbox之后子的是否选中值是true，却没有显示选中状态

### ISSUE THREAD

**Issue by dahaideyu** [ant-design/ant-design#26452]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[ https://github.com/NG-ZORRO/ng-zorro-antd]( https://github.com/NG-ZORRO/ng-zorro-antd)

### Steps to reproduce
no

### What is expected?
children node also show checked,希望子节点也能选中。

### What is actually happening?
no,just value is true ,只是值变了，显示没有checked的状态。

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 4.6.0 |
| System | 4.6.1 |
| Browser | 1 |

---
no

**Comment by zombieJ** [comment]
Pls fire issue to ng-zorro instead.
