### ISSUE TITLE
是否可以提供类似rangePicker的InputNumber组件.

### ISSUE THREAD

**Issue by Renderz** [ant-design/ant-design#26458]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以解决表单中有选择数值范围的场景. 

### What does the proposed API look like?
参数可以和InputNumber相同

**Comment by xrkffgg** [comment]
Try https://ant.design/components/slider-cn/
