### ISSUE TITLE
Antd table tree structure data display 

### ISSUE THREAD

**Issue by saresh-krish** [ant-design/ant-design#26456]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/hungry-williamson-uczrn?file=/index.js)

### Steps to reproduce
In this table i have added Read, Write checkbox column , Parent table checkbox selected child checkbox will enable.

### What is expected?
When i click the parent checkbox of 'Read' column , inside the child data checkbox also be enable.

### What is actually happening?
Nothing

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Version 79.0.3945.130 (Official Build) (64-bit) |

---
When i click the Parent Row Read column ,inside the Child row same Read column checkbox will enable like left side 'rowselected' option. Same function sub child also. and reverse process also when i click all child row Read columns Parent row Read checkbox will enable.

**Comment by zombieJ** [comment]
You should realize it with your logic. Table do not handle customize column render.

**Comment by saresh-krish** [comment]
Hi @zombieJ 
How to render the child row in dynamic data tree structure. like split of parentChildData in Antd table.
