### ISSUE TITLE
当给AutoComplete 动态设置options时，会导致defaultActiveFirstOption属性失效。

### ISSUE THREAD

**Issue by accwill** [ant-design/ant-design#26454]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/husvm)

### Steps to reproduce
点击文本框，第一个选项未高亮

### What is expected?
第一个选项高亮

### What is actually happening?
第一个选项未高亮

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | macOs 10.15.6  |
| Browser | chrome 84.0.4147.135（正式版本） （64 位） |

**Comment by zombieJ** [comment]
你的重现似乎没有设置 `defaultActiveFirstOption` ？
