### ISSUE TITLE
getValueFromEvent 支持Promise返回

### ISSUE THREAD

**Issue by yezongyang** [ant-design/ant-design#26451]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
切换radio的时候需要弹窗确认 是否切换导致页面隐藏或者数据清空

### What does the proposed API look like?
getValueFromEvent (args) => any | Promise

**Comment by afc163** [comment]
See #20542

**Comment by yezongyang** [comment]
@afc163 我这个场景不同， 目的是阻止Form.Item值变化。用onChange的话就没必要用Form.Item了，Form.Item收集数据肯定是更加便利~

**Comment by zombieJ** [comment]
自行封装一下 `Radio`，React 对受控状态需要保持同步，否则会遇到例如输入组件无法输入的情况。Form 侧不会支持异步。
