### ISSUE TITLE
Tabs高度变高了

### ISSUE THREAD

**Issue by aiyudeleng** [ant-design/ant-design#26463]
Tabs的高度忽然变得很高，期间没有修改过相关参数

**Comment by xrkffgg** [comment]
Tabs 4.3.0 进行了重构，你看看是不是你升级了版本。

**Comment by aiyudeleng** [comment]
我应该是早就升级到了4.3.0，之前没有碰到






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xrkffgg"<notifications@github.com&gt;; 
发送时间: 2020年8月28日(星期五) 下午5:29
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "740296066"<740296066@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] Tabs高度变高了 (#26463)





 
Tabs 4.3.0 进行了重构，你看看是不是你升级了版本。
 
&mdash;

**Comment by xrkffgg** [comment]
看看具体样式，是哪里变了
