### ISSUE TITLE
Form组件Form.Item validateStatus=error，提交表单时，表单数据校验通过，onFinish方法调用成功

### ISSUE THREAD

**Issue by TLOVET** [ant-design/ant-design#26464]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/proud-platform-wf7pv)

### Steps to reproduce
1，给Form.Item 中validateStatus设为error
```
    <Form.Item
        label="Username"
        name="username"
        validateStatus="error"
        hasFeedback
        help="Please input your username!"
      >
        <Input />
      </Form.Item>
```
2，直接点击提交按钮，数据校验通过，onFinish方法调用成功
```
    <Form
      {...layout}
      name="demo"
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
    >
```

### What is expected?
Form.Item validateStatus=error，提交表单时，表单数据校验失败，onFinish不能调用

### What is actually happening?
Form.Item validateStatus=error，提交表单时，表单数据校验通过，onFinish方法调用成功

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | macOS 10.15.6  |
| Browser | chrome 84.0.4147.135（正式版本） （64 位） |

**Comment by afc163** [comment]
手动修改 validateStatus 只会影响样式表现，不会影响校验规则和通过与否。

**Comment by TLOVET** [comment]
了解了，配合validator已实现该需求
