### ISSUE TITLE
Need a way to force render the table filter dropdown

### ISSUE THREAD

**Issue by Delwalt** [ant-design/ant-design#26472]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using ant table component.
And I am using the `filterDropdown` prop to show a custom dropdown component.
So currently once the filter dropdown is opened it stays in the DOM even after the dropdown is closed.
Which is causing unnecessary renders of hidden filter dropdowns.

Is there any way to remove the dropdown completely from the DOM after it is closed and re-render it once clicked again.
I know there is `forceRender` prop on the dropdown but is there something similar solution to the table filter dropdown?

### What does the proposed API look like?
I am not sure, I am looking more of a solution.

**Comment by namoshizun** [comment]
Hmmm I know this issue got little attention, but does anybody also feel this a pressing problem?

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/issues/45898
