### ISSUE TITLE
使用状态设置Input的value，通过Form获取不到

### ISSUE THREAD

**Issue by juneryo** [ant-design/ant-design#2647]
- antd 版本: 1.7.0

这里是Demo：
http://codepen.io/juneryo/pen/BzNjzP?editors=0011

点击确定后获取不到Input的值。。。

**Comment by ddcat1115** [comment]
value 通过 setFieldsValue 控制

http://codepen.io/ddcat1115/pen/ZOmoEv?editors=0011

**Comment by juneryo** [comment]
@ddcat1115 哦哦哦，原来如此。
不过如果想对Input进行二次封装，作为一个新组件的话，使用Form提供的方法好像就不太合适了吧。
不知道还有有没有其他的控制Input value的方式呢？

**Comment by ddcat1115** [comment]
如果单独用 Input，也可以不用 Form.create 那一套，直接 state 控制就好了，设置值用 setState，取值用 this.state.xxx 

http://ant.design/components/input/

**Comment by juneryo** [comment]
@ddcat1115 
嗯。。。。。。可能是我没描述清楚，现在的情况是这样的。
比如说我要对Input做二次封装，弄一个IconPicker。
大概就是类似这样的：
![qq 20160809110349](https://cloud.githubusercontent.com/assets/4101515/17503322/861dfe50-5e21-11e6-91fd-e3f31a58fc22.png)

那么也就是说，每次选中图标，都通过state重设了Input的value值。
但是实际上取值的时候，是想通过Form统一来取值。
```
<Form>
  <Input />
  <IconPicker />
</Form>
```

当然，在父组件上添加状态，IconPicker中添加选中后的回调也确实可以取到值就是了。
不过还是想尽量统取值下哈。=w=

**Comment by benjycui** [comment]
`IconPicker` 就是个自定义表单组件，对外提供 `onChange` 事件就可以与 `antd.Form` 一起使用了。

**Comment by juneryo** [comment]
@benjycui 
onChange 事件啊，通过状态改变 Input 的 value 属性无法触发 onChange 事件呢。。。
`<Input value={this.state.val} />`
不知道是不是刻意有这样的规范。
为了不覆盖 Input 原有的 onChange 属性，现在是对组件额外添加 onPick 属性，用于选中之后的回调。
不过这样就没法和 Input、Select 一样，统一使用 Form 的校验以及取值方式（validateFields）。

**Comment by benjycui** [comment]
`options.trigger` http://ant.design/components/form/#getFieldProps-options

另外你可以看下 antd 的 Input 组件是怎么封装的。

**Comment by afc163** [comment]
这个 IconPicker 蛮有用，感觉回头可以贡献出来。

**Comment by benjycui** [comment]
其实 IconPicker 和这个东西差不多 https://github.com/react-component/editor-plugin-emoji/blob/master/src/EmojiPicker.jsx

![image](https://cloud.githubusercontent.com/assets/3580607/18043525/069ba74c-6dfb-11e6-9b49-db70db516c00.png)
