### ISSUE TITLE
Allow forceRender feature in Dropdown component 

### ISSUE THREAD

**Issue by Delwalt** [ant-design/ant-design#26470]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
On a single page, I have more than 10 dropdowns and all of these dropdowns have options coming from API calls and the number of the options is huge. So whenever the state of the component changes those all dropdows rerenders and this is causing a performance issue.

If I can pass forceRender than the dropdown will be removed from the DOM and will only rerender when users click on a particular dropdown.

### What does the proposed API look like?
forceRender is a popular prop for this feature which is being followed on the other components.

**Comment by afc163** [comment]
Dropdown support `forceRender` which will pass to rc-trigger, you can use it.

**Comment by Delwalt** [comment]
> Dropdown support `forceRender` which will pass to rc-trigger, you can use it.

Hi I think was not able to convey the exact issue so I opened a new issue #26472.
