### ISSUE TITLE
rc-table with resize and scroll props lags

### ISSUE THREAD

**Issue by ivanmontiel-lw** [ant-design/ant-design#26475]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
  * Note: I have seen a few similar issues with many rows and performance, but none specifically for resizing.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-dirac-1p21r?file=/src/App.js)

### Steps to reproduce
1. Use Ant Table (or the rc-table directly), with code to implement the column resize behavior and scroll y.
2. Try to resize the column
3. The more rows rendered, the more the problem is noticeable.

### What is expected?
No performance issues. Header cell widths and row columns widths stay the same.

### What is actually happening?
There is noticeable lag of the header cells and desync between header widths and row widths.

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12.0 |
| System | Mac OS X |
| Browser | Chrome 84.0.4147.125 |

---
From investigating, when the scroll y prop and column widths are updated, every row in the table is re-rendered when the column is resized.

**Comment by afc163** [comment]
You better report it to rc-table.

**Comment by afc163** [comment]
Duplicate of #26413
