### ISSUE TITLE
react-addons-pure-render-mixin要求升级React，建议不要直接依赖

### ISSUE THREAD

**Issue by huangyingjie** [ant-design/ant-design#2648]
#### 本地环境

- antd 版本: 1.5.0
- 操作系统及其版本：mac osx
- 浏览器及其版本: chrome
 
#### 你做了什么？

升级 antd到1.8.0

#### 你期待的结果是：

顺利升级，不要求升级React。既然 antd没有写peerDependance，那就希望整个流程保持一致。

#### 实际上的结果：
react-addons-pure-render-mixin要求升级React到15.3

#### 可重现的在线演示

不需要

**Comment by afc163** [comment]
用 npm3 即可。

**Comment by huangyingjie** [comment]
是用npm3: 3.10.2
其实有一点没描述清楚，我的操作步骤比较特殊，多了一步删除antd，目的是下载最新的antd：
npm uninstall antd --save
npm i antd --save

**Comment by afc163** [comment]
warning 就无视吧，不影响使用的。

**Comment by huangyingjie** [comment]
````
npm WARN saveError peer invalid: react@^15.3.0, required by react-addons-pure-render-mixin@15.3.0
````
影响生成npm-shrinkwrap.json，还是有点麻烦的。

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/issues/3338#issuecomment-257077387
