### ISSUE TITLE
Select dropdown not scrollable on mobile

### ISSUE THREAD

**Issue by Addono** [ant-design/ant-design#26480]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elegant-curie-8c2k7?file=/index.js)

### Steps to reproduce
1. Open on mobile (or responsive mode on desktop)
1. Open "Select"-dropdown which overflows
1. Attempt to scroll by dragging

### What is expected?
Up to Antd 4.5.4 one could drag the dropdown to scroll through the items.

![](https://i.imgur.com/m3Ta5N3.gif)

### What is actually happening?
In Antd 4.6.0 and 4.6.1 the page will be dragged instead, hence one is unable to select issues not in view.

![](https://i.imgur.com/W1hMVp2.gif)

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.13.1 |
| System | Windows 10; Android |
| Browser | Chrome 84.0.4147.135 (64bit); Chrome |

---
Scrolling using the mouse wheel seems unaffected.

**Comment by topched** [comment]
This bug is still reproducible in version 4.6.3

**Comment by Addono** [comment]
Yeah, it's only fixed in a dependency, however the version required by Ant is not bumped, hence this dependency can still resolve to a version from before it was patched.

It landed in [`rc-virtual-list@3.0.8`](https://github.com/react-component/virtual-list/releases/tag/v3.0.8).

While Antd still requires `^3.0.3`
https://github.com/ant-design/ant-design/blob/master/package.json#L245.

I went back to using 4.5.4 for the moment, as there's nothing in 4.6 I need

**Comment by Addono** [comment]
Alternatively you could use the [`resolutions`  field ](https://github.com/Addono/Fridgetory/commit/f66635e6a090db466782779f079c8c3743a56d54#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34)in your `package.json` to bump it yourself.

E.g. on Yarn
https://classic.yarnpkg.com/en/docs/selective-version-resolutions/

**Comment by topched** [comment]
@Addono Thanks for the tip, had that before just didnt double check that they didnt push the version after they closed this issue, ill put it back for now

**Comment by zombieJ** [comment]
`^3.0.3` includes the `3.0.8`. Clean up `node_modules` & any pack lock file and reinstall instead of `resolution`.

**Comment by Addono** [comment]
> `^3.0.3` includes the `3.0.8`. Clean up `node_modules` & any pack lock file and reinstall instead of `resolution`.

Sure, probably works better for most people. However don't think it's guarranteed to be a better solution for everyone. By dropping your lockfile you could be unlucky and introduce new issues by other (transitive) dependencies breaking in newer versions.

**Comment by jagaa999** [comment]
Please update your dependency to 4.8.4 (Antd version)

**Comment by benbenbuhben** [comment]
This bug is still reproducible in version 4.8.5

**Comment by Addono** [comment]
It's not about the Antd version you're using, since the bug is present in a dependency of Antd itself, namely `rc-virtual-list`. The version you're using in your project could therefore still be one affected by the bug.

The version range of `rc-virtual-list` on which Antd depends is still the same (see current `master` [package.json](https://github.com/ant-design/ant-design/blob/5d41d29cae4bea80481199e562f24bda40cd1f7c/package.json#L246) as it was when I filed the bug report. Thus there's no reason why it would be updated to a newer version if the old version is still pinned in your lockfile.

Completely removing `node_modules` and your lockfile, if you then regenerate your lockfile you should have a newer version of `rc-virtual-list`. Although it's up to you to decide if the side-effects of getting newer versions for all your dependencies is acceptible.

Another approch is to (temporarily) add `rc-virtual-list` as a (resolutions) dependency with a version range of `^3.0.8`. Then you can remove it and the newer version will still be in your lockfile.

**Comment by IvanTsarkovV** [comment]
I'm using Ant 5.8.5, checked on 5.6.1 and 5.4.7 - this bug still there in IOS phone. I also checked https://ant.design/components/select - same bug. If I set virtual={false} - In IOS device It will scrolls, but awfully, with jerks, sometimes get stuck, please fix this bug

**Comment by adams-family** [comment]
+1 I confirm on 5.7.3, as well. Is it possible to fix it? My client literally refuses to accept the project :)

**Comment by IvanTsarkovV** [comment]
This bug is still reproducible in version 5+

**Comment by IvanTsarkovV** [comment]
@adams-family I came up with a solution to the problem, you can set 

1) virtual={false}
2) dropdownRender={(menu) => {
            return <StyledDropDown>{menu}</StyledDropDown>;
          }}
3) const StyledDropDown = styled.div(({ theme }) => ({
  maxHeight: 264,
  overflow: 'hidden',
  overflowY: 'auto',
  '.rc-virtual-list-holder': {
    maxHeight: 'none !important',
    overflow: 'visible !important',
  },
}));

looks like a hack, but it works)

**Comment by savkevip** [comment]
> none

this is breaking my UI :/ :)

![image](https://github.com/user-attachments/assets/b1e613d7-addb-4c5c-8474-d9ec30c5305f)

**Comment by kamrantg** [comment]
i also have this bug.
