### ISSUE TITLE
Pagination组件simple 分页total会四舍五入

### ISSUE THREAD

**Issue by yandianjiangfeng** [ant-design/ant-design#26491]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/spring-fast-nw0yk?file=/index.js)

### Steps to reproduce
修改total

### What is expected?
正常显示total

### What is actually happening?
total四舍五入

| Environment | Info |
|---|---|
| antd | 3.26.13 |
| React | 16.7.0 |
| System | https://codesandbox.io/s/spring-fast-nw0yk?file=/index.js |
| Browser | chrome |

**Comment by xrkffgg** [comment]
simple 有显示 total ?
