### ISSUE TITLE
Form嵌套Upload中间加div时，拖动文件到上传组件，reqiure判断不正常

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#26496]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/formupload-0qebb)

### Steps to reproduce
设置上传组件在Form中，FormItem与上传组件之间嵌套div，设置;required: true
页面打开后，直接拖动操作系统的文件进入上传框
点击提交时，必选的提示出来了。
当点开文件选择框时，无必选提示，

### What is expected?
不应该出现必选提示

### What is actually happening?
出现必选提示

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12 |
| System | Windows |
| Browser | 谷歌 |

---
4.4.2与4.6.1均有此问题
在之前某个版本是测试过的，具体哪个版本正常不记得了。

**Comment by afc163** [comment]
不要加 div，Form.Item 必须直接包裹表单控件，加任何其他元素都会导致表单出问题。

**Comment by yoyo837** [comment]
可以包自定义元素吧？但是需要自己从props拿value和onChange处理是不？

**Comment by phoema** [comment]
问题在于，拖拽和点开文件框选择文件表现不一致啊。
点开文件框能处理正确，理论上，拖拽也应该处理正确的。

> 不要加 div，**Form.Item 必须直接包裹表单控件**，加任何其他元素都会导致表单出问题。

**Comment by phoema** [comment]
之前肯定有正确的版本，这个我们项目组测试过。

**Comment by afc163** [comment]
> 问题在于，拖拽和点开文件框选择文件表现不一致啊。

Form.Item 设计上就是必须直接包裹的，其他情况我们没有测试过，也不要当 feature 使用，
