### ISSUE TITLE
table 的ant-table-header， 为什么不用"position: sticky;top:0;", 想知道会出现什么问题

### ISSUE THREAD

**Issue by johnJine** [ant-design/ant-design#26502]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不用计算滚动条宽度， ant-table-cell-scrollbar可以不要

### What does the proposed API look like?
display: contents; 和 position: sticky; 处理表格的头部

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26503#issuecomment-683752579

**Comment by zombieJ** [comment]
为了兼容 v3 的 components 自定义 header 的 API。
