### ISSUE TITLE
ref warning on `Field` component

### ISSUE THREAD

**Issue by alextrastero** [ant-design/ant-design#26500]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eloquent-sunset-nz2ou?file=/src/App.js)

### Steps to reproduce
Create a Form with custom inputs as children of `Form.Item`, a warning appears about `Field` and refs.

### What is expected?
No warning message in console

### What is actually happening?
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Field`.
    in ImageUploader (at SendFeedback.tsx:65)

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | 16.12 |
| System | MacOs |
| Browser | Chrome 83 |

---
I'm sorry but the example in codesandbox does not show this warning... 
But the issue is that if I add a custom component inside `Form.Item` I get this warning

**Comment by alextrastero** [comment]
More code:
```jsx
const SendFeedback = () => (
  <Form form={form} id={formId} onFinish={(values: any) => handleSubmit(values)}>
    <Form.Item name="media_data" valuePropName="fileList" rules={validateAtLeastOne}>
      <ImageUploader
        files={localFiles}
        onUpload={handleUpload}
        onRemove={handleRemove}
        loading={uploadLoading}
      />
    </Form.Item>
  </Form>
);

const ImageUploader = ({ files, onUpload, onRemove, loading }) => (
  <Upload
    accept="image/*,video/*"
    listType="picture"
    multiple
    showUploadList={false}
    customRequest={onUpload}>
    <Button type="dashed">
      <UploadOutlined /> Upload file
    </Button>
  </Upload>
);
```

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Field`.
    in ImageUploader (at SendFeedback.tsx:65)
```

**Comment by alextrastero** [comment]
Changing `ImageUploader` component to:

```jsx
const ImageUploader = ({ files, onUpload, onRemove, loading, innerRef }) => (
  <Upload ref={innerRef}

export default React.forwardRef((props, ref) => (
  <ImageUploader {...props} innerRef={ref} />
));
```

Solves the issue, but I don't want to change all my components to `forwardRef`

**Comment by afc163** [comment]
Please try React.ForwardRef to wrap component.
