### ISSUE TITLE
Form initialValues setting the value for Select even if the option is not valid

### ISSUE THREAD

**Issue by lucascurti** [ant-design/ant-design#26505]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sleepy-platform-6s87j?file=/index.js)

### Steps to reproduce
I'm getting the options for a `Select` from API and setting the default value in the `initialValues` for the `Form`. The problem is that the `Form` is displaying the initial value as the label in the `Select` leading to a bad UX. 

In the reproduction link you'll notice that `2` is displayed in the `Select` until the options finish loading. 

### What is expected?
Not to display a initial Value if it's not valid.

### What is actually happening?
Is displaying the initial value even if it's not a valid option for the Select.

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.12.0 |
| System | any |
| Browser | any |

---
Maybe there is a better approach to deal with this case but I checked the docs and I couldn't find an easy way to do it. I can do some logic to only set the value once the options finished loading but this means that I won't be able to use `initialValues` and it would be much more time consuming.

**Comment by afc163** [comment]
It is by designed, Select show defaultValue even not included it's options.
