### ISSUE TITLE
Set initialValues of a nested form

### ISSUE THREAD

**Issue by severi** [ant-design/ant-design#26501]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I would want to use the "initialValues" option of a form to set the initial values of nested fields.

### What does the proposed API look like?
    <Form initialValues={{
      user: {
        name: 'Hello World',
      }
    }}>
      <Form.Item name={['user', 'name']} label="Name" rules={[{ required: true }]}>
        <Input />
      </Form.Item>
    </Form>

**Comment by huseyingoztok** [comment]
It is already working for your sample.
