### ISSUE TITLE
日期选择控件“返回今天”没效果

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2650]
#### 可重现的在线演示

http://codepen.io/anon/pen/YWRLVK?editors=001

**Comment by ddcat1115** [comment]
是有点问题，@RaoHai  瞅瞅呢

**Comment by benjycui** [comment]
昨天 debug 了下，是 rc-calendar 里面的问题，Calendar 这个组件比较复杂，要多点时间才能修复。。

**Comment by afc163** [comment]
貌似演示没问题呢。

**Comment by aw6658913** [comment]
@afc163 有吧~~演示点击“返回今天”是没有反应的

**Comment by afc163** [comment]
因为面板就在『今天』的区域内。你切换月份后再点击试试。

**Comment by ddcat1115** [comment]
好吧，之前理解错了，原来『返回今天』是指可选区域的返回 😓 

@aw6658913  估计也是误解了吧？ issue先关了，有问题reopen

**Comment by aw6658913** [comment]
是的~之前误解了，现在知道它的作用了

**Comment by benjycui** [comment]
这个要不文案改下。。。这个误解我觉得很合理。

**Comment by ddcat1115** [comment]
主要『返回』+『今天』有点把时间设置为今天的感觉

改文案的同时，能不能做成 在当前范围内时就不可点，不显示或者灰掉

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2035

**Comment by afc163** [comment]
当前范围灰掉就好。

**Comment by benjycui** [comment]
trace: https://github.com/react-component/calendar/pull/137
