### ISSUE TITLE
table 有fixed={true}列的空数据， （ant-empty）为啥放在td里面, 不跟 ant-table-header是兄弟节点

### ISSUE THREAD

**Issue by johnJine** [ant-design/ant-design#26503]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
避免计算ant-empty的宽度

### What does the proposed API look like?
ant-empty不要放在表格中

**Comment by afc163** [comment]
一般都是有一些需求需要满足或者历史遗留问题，你最好直接描述遇到的具体问题，避免问 [X-Y 问题](https://coolshell.cn/articles/10804.html)。
