### ISSUE TITLE
为什么Tooltip背景色的属性为color我想设置title的颜色呢？titleColor?

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#26509]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
not

### What is expected?
not

### What is actually happening?
not

| Environment | Info |
|---|---|
| antd | undefined |
| React | latest |
| System | mac |
| Browser |  chrome latest |

**Comment by afc163** [comment]
```jsx
<Tooltip title={<div style={{ color: 'xxx' }}>tooltip title</div>} />
```

**Comment by hengkx** [comment]
@afc163  在一个项目中的话 Tooltip的背景色和字的颜色很多应该是 统一的 这样写的话是不是有点太麻烦了？或者 用theme less控制？
比如我们现在一个项目中的就是 背景色是黑色 而 字是白色的
#26511

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/blob/97f7a972bfc1c54bed8d3e7298627d5a84b6b6e3/components/style/themes/default.less#L470
