### ISSUE TITLE
RangePicker组件选中两个日期后不要关闭

### ISSUE THREAD

**Issue by xiayu1986** [ant-design/ant-design#26514]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在某些业务场景下，需要对选中的两个日期进行校验，并在RangePicker中给出校验结果提示，所以需要选中日期后不关闭日历弹层。

![图片](https://user-images.githubusercontent.com/13351108/91790946-7b5f5d00-ec44-11ea-90be-c83d4d18987c.png)

### What does the proposed API look like?
RangePicker组件选中两个日期后不要关闭

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/24083

**Comment by afc163** [comment]
https://codesandbox.io/s/practical-platform-4ksxc?file=/index.js
