### ISSUE TITLE
Checkbox属性defaultChecked不生效

### ISSUE THREAD

**Issue by zsl1549** [ant-design/ant-design#26518]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://3x.ant.design/components/checkbox-cn/#Checkbox](https://3x.ant.design/components/checkbox-cn/#Checkbox)

### Steps to reproduce
 <Checkbox defaultChecked={true}>可修改</Checkbox>  没有选中

### What is expected?
复选框是选中的

### What is actually happening?
复选框是没有选中的

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.8.6 |
| System | mac |
| Browser | google |

---
这种错误 我的天

**Comment by zsl1549** [comment]
<Checkbox defaultChecked={true}>可修改</Checkbox>

**Comment by xrkffgg** [comment]
没看到有啥问题

**Comment by yoyo837** [comment]
不好意思，描述和链接没看明白。

**Comment by zsl1549** [comment]
<Checkbox 
   defaultChecked={true}
>
可修改
</Checkbox>

**Comment by zsl1549** [comment]
设置了 defaultChecked 这个属性 复选框显示没选中 状态

**Comment by zsl1549** [comment]
@yoyo837  @xrkffgg

**Comment by yoyo837** [comment]
https://codesandbox.io/s/hopeful-hellman-44xc4

可以啊，提供你的复现看一下。

**Comment by Veynee** [comment]
我的天，是不是单次拼错了。

**Comment by zsl1549** [comment]
@yoyo837 https://codesandbox.io/s/hopeful-hellman-44xc4. 就这样写 本地不选中

**Comment by yoyo837** [comment]
没有复现不知道啥问题、从何入手。

**Comment by jayconscious** [comment]
可能是因为没有加key，导致react不会去更这个组件，defaultChecked只在第一次渲染时生效
