### ISSUE TITLE
Prop `className` did not match.

### ISSUE THREAD

**Issue by moshuchao** [ant-design/ant-design#26519]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jovial-glitter-57vt1?file=/src/App.tsx)

### Steps to reproduce
- 1.复制网址
- 2.打开控制台

### What is expected?
无错误

### What is actually happening?
Warning: Prop `className` did not match. Server: "ant-form-item-explain" Client: "ant-form-item-explain show-help-appear show-help"

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome |

---
使用ssr触发className不一致

**Comment by WeebNetsu** [comment]
Anyone know how to fix it?
