### ISSUE TITLE
Popover would not display if content use Fragment tag

### ISSUE THREAD

**Issue by Rey-Wang** [ant-design/ant-design#26517]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/falling-butterfly-kzw3p?file=/index.js)

### Steps to reproduce
1.  Use `<Fragment>` or `<>` package your popover content
2. Click or hover popover (depends on how you define trigger)

### What is expected?
expected to show popover

### What is actually happening?
nothing happen and no errer throwed

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.12 |
| System | codesandbox |
| Browser | chrome 79 |

**Comment by richard-li-next** [comment]
I and @Rey-Wang are from the same team. In the antd3.x version, Popover's children type is `children?: React.ReactNode`, but in the antd4.x version its type is changed to `children?: React.ReactElement`. So we had to wrap it with a layer of `<></>`.

**Comment by Rey-Wang** [comment]
@afc163 Even we fix the type that we can add muti-child in Popover, there still has a problem with the `<></>` or `<Fragment></Fragment`
I don't think this issue should be closed
