### ISSUE TITLE
Table 选择增加反选功能

### ISSUE THREAD

**Issue by infeng** [ant-design/ant-design#2651]
希望Table组件的选择能增加反选功能，不知道后续的更新是否有这个计划？没有的话只能自己改造一下。

**Comment by benjycui** [comment]
后续会添加，具体时间还没确定。

**Comment by benjycui** [comment]
如果你已经有改造计划，可以直接来个 PR 如何？

**Comment by infeng** [comment]
国庆之后弄一个

**Comment by infeng** [comment]
如果全选按钮加上反选的逻辑，交互上会不会有点复杂，还是另外加一个反选的按钮比较好

**Comment by yesmeck** [comment]
没看懂你说的反选的意思，是指在已勾选第一行的情况下，点反选，就取消第一行的勾选并选中其他行吗？

**Comment by infeng** [comment]
@yesmeck 对，就是你说的意思

**Comment by yesmeck** [comment]
感觉自己实现一下也不复杂 http://codepen.io/yesmeck/pen/XNmjLv?editors=001

加到 Table 里的话 UI 上确实也要有变化。

**Comment by infeng** [comment]
我在全选框旁边加一个反选框好了

**Comment by yesmeck** [comment]
@benjycui 这个要召唤下设计师？

**Comment by benjycui** [comment]
@infeng 等交互确认一下吧。。

**Comment by benjycui** [comment]
迟来的设计稿，还有时间做么？ @infeng 

![2](https://cloud.githubusercontent.com/assets/3580607/22922543/2dd132b0-f2d9-11e6-9cc9-ff0bebb1f9b9.png)

**Comment by infeng** [comment]
忙完这段时间之后做出来

**Comment by yesmeck** [comment]
@benjycui 有没有有标注的设计稿？
