### ISSUE TITLE
DatePicker 调用 ref.focus() 只有输入框聚焦，选择下拉框不出现

### ISSUE THREAD

**Issue by Sshrimp** [ant-design/ant-design#26516]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/react-component/picker](https://github.com/react-component/picker)

### Steps to reproduce
调用focus

### What is expected?
调用focus之后出现下拉框

### What is actually happening?
下拉框没有出现，只有输入框聚焦

| Environment | Info |
|---|---|
| antd | 4.4.2 |
| React | 16.11.0 |
| System | win10 |
| Browser | Chrome |

**Comment by jefferyssy** [comment]
antd@4.13.0 我也遇到同样的问题/

let pickerRef: any = useRef(null)

pickerRef.current?.focus()

<RangePicker
          ref={pickerRef}
          allowClear={false}
          value={isArray(dateFilterVal) ? dateFilterVal : []}
          onChange={onChange}
          renderExtraFooter={renderExtraFooter}
        />

**Comment by jefferyssy** [comment]
import ReactDOM from "react-dom";
import { Button, DatePicker, version } from "antd";
import "antd/dist/antd.css";
import "./index.css";

const Test = () => {
  let pickref = React.useRef();
  const todo = () => {
    pickref.current.focus();
  };

  return (
    <div className="App">
      <h1>antd version: {version}</h1>
      <DatePicker ref={pickref} />
      <Button type="primary" style={{ marginLeft: 8 }} onClick={todo}>
        Primary Button
      </Button>
    </div>
  );
};

ReactDOM.render(<Test />, document.getElementById("root"));

**Comment by jefferyssy** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-swv26

**Comment by jefferyssy** [comment]
> This issue is closed because it has been marked as `Need Reproduce`, but has not had recent activity.
> If you can provide a reproduce, feel free to ping anyone of our maintainers to reopen this issue.
> Thank you for your contributions.
