### ISSUE TITLE
less 表达式错误

### ISSUE THREAD

**Issue by GloryLin0704** [ant-design/ant-design#26512]
antd 版本 4.6.2

wepack 编译的时候会有如下错误

Module build failed (from /xxxxx/node_modules/_less-loader@5.0.0@less-loader/dist/cjs.js):

@table-header-sort-active-filter-bg: lighten(@table-header-sort-active-bg, 2%);
@table-sticky-zindex: @zindex-table-fixed + 1;
^
Operation on an invalid type

背景是引入了一个全局 less 做样式覆盖，是 less-loader 的版本过低导致？

**Comment by YanYuanFE** [comment]
less版本降到3.x，出这个问题的都是less4的break change

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/23125#issuecomment-757678485
