### ISSUE TITLE
Global set tooltip backgroup color

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#26511]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
unified

### What does the proposed API look like?
not

**Comment by afc163** [comment]
Try less variable: https://github.com/ant-design/ant-design/blob/71f726afb12a45eb14a03b41e49823c4c314dff5/components/style/themes/default.less#L472
