### ISSUE TITLE
api 适配屏幕较小的电脑

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#26510]
https://ant.design/components/config-provider-cn/
![image](https://user-images.githubusercontent.com/8358236/91785094-1f420c00-ec37-11ea-9e93-90a6e0537af4.png)

**Comment by afc163** [comment]
没懂。

**Comment by hengkx** [comment]
Windows 笔记本上 链接中的api文档 完全没办法正常浏览

**Comment by afc163** [comment]
确实需要优化一下这个表格的样式。
