### ISSUE TITLE
will all components be rewrite with hooks？

### ISSUE THREAD

**Issue by JhonXY** [ant-design/ant-design#26520]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/commit/ee50fe795298cec933d46d92f107ffb7657310bf#diff-ed7c05e544978302b73eec6e193cb92b](https://github.com/ant-design/ant-design/commit/ee50fe795298cec933d46d92f107ffb7657310bf#diff-ed7c05e544978302b73eec6e193cb92b)

### Steps to reproduce
when a default component implement with a class，i can get it prototype，then rewrite its methods.
![image](https://user-images.githubusercontent.com/21687167/91831193-58e63780-ec76-11ea-858b-6569b864edcb.png)
How can I achieve a similar effect when the default component is just a function.

### What is expected?
maybe some alternative plans?

### What is actually happening?
rewrite prototype will get a error

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | * |
| System | * |
| Browser | * |

**Comment by afc163** [comment]
We don't suggestion any prototype rewriting, all components will be refactor with hooks.
