### ISSUE TITLE
Transfer组件当作为表格穿梭框时功能 反选当页 功能异常

### ISSUE THREAD

**Issue by CalmHarbin** [ant-design/ant-design#26529]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/transfer-cn/#components-transfer-demo-table-transfer](https://ant.design/components/transfer-cn/#components-transfer-demo-table-transfer)

### Steps to reproduce
1.在分页的表格中任选一项，使用反选当页功能 

### What is expected?
1.能够正常的反选当页。

2.或者能够提供 反选所有/反选当页 这个地方的自定义配置。让用户使用自定义渲染时可自定义配置实现功能。

### What is actually happening?
反选当页 结果为 反选所有

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.8.6 |
| System | window |
| Browser | Chrome |

**Comment by Sturrbon** [comment]
I'll try this.

**Comment by afc163** [comment]
目测已经修复了。

https://ant.design/components/transfer-cn/#components-transfer-demo-table-transfer

如果还有问题，可以回复在此。
