### ISSUE TITLE
Table组件的ant-spin在可滚动区域的定位问题

### ISSUE THREAD

**Issue by cagen** [ant-design/ant-design#2652]
#### 本地环境
- antd 版本: 1.8.0
- 操作系统及其版本：OSX 10.11.5 (15F34)
- 浏览器及其版本: Chrome 51.0.2704.84 (64-bit)

#### 可重现的在线演示
http://codepen.io/anon/pen/LkXbPp?editors=0010
将Table放置于一个固定高度的可滚动区域内，在Table之前设置一个可变高度的DIV。
点击展开按钮，灰色区域会逐渐增加，当灰色区域增高到超过一定程度之后（超过窗口高度），会发现一开始不能滚动的Body区域可以滚动了，Body区域的高度增加了。Debug发现是因为` <div class="ant-spin"></div>`这个元素是绝对定位的，但没有设定具体定位的值，且外层也没有position为非static的元素让它相对其定位。它会随着灰色区域的增高和增加top值，最后就会顶出`<div class="box"></div>`的区域。

正常时候的情况：
![image](https://cloud.githubusercontent.com/assets/5174809/17506345/a9e4977c-5e3a-11e6-8940-41cb63c6beb3.png)

不正常时候的情况：
![qq20160809-0](https://cloud.githubusercontent.com/assets/5174809/17506211/9e85b13c-5e39-11e6-903c-6635e4a1b032.png)

**Comment by benjycui** [comment]
不是很能理解，能再详细描述下？

**Comment by cagen** [comment]
![2](https://cloud.githubusercontent.com/assets/5174809/17545381/4e964282-5f0f-11e6-8428-da9c46990151.gif)
说的确实有些不清楚，请看我的录屏吧
出现这个BUG是要在特定情况下的
1. 外层有个DIV是scroll的
2. Table上面有个元素的高度会变化

然后像我的操作一样，当Table上面那个元素变化后，`<div class="ant-spin" />`的top值就会随之改变，有时候自个就飞出了Table的区域（因为Table在scroll的DIV里，而spin是position: absolute的，且此时spin针对的是body做的定位），最后看到的现象就是spin飞出了好远，把body都顶高了。

**Comment by afc163** [comment]
理解起来比较难，但我觉得上面这样可以修复。

**Comment by cagen** [comment]
嗯，确实可以修复。
我本来以为需要在外层div加一个类似`.ant-spin-nested-loading`的类，去让`<div class="ant-spin" />`相对其定位。
