### ISSUE TITLE
Modal close will roll up

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#26528]
https://github.com/ant-design/ant-design/pull/26507#pullrequestreview-479537379

**Comment by afc163** [comment]
这是 #26507 的问题还是 master 的问题？

**Comment by xrkffgg** [comment]
@hengkx @jhoneybee

**Comment by jhoneybee** [comment]
> 这是 #26507 的问题还是 master 的问题？

这个是 feature 分支上 commit 的 fdc36b6的问题。

以下情况下可以复现

1. 从主仓库下载源码

```shell
#  commit hash fdc36b6
git clone https://github.com/ant-design/ant-design.git -b feature
```
2. yarn && yarn start 
3.  在屏幕 保持尺寸 580px * 547px 
4.  点击 `Open Modal with customized button props` 这个按钮

master 的我正在测试，稍等以下

**Comment by afc163** [comment]
https://ant.design 上有这个问题么？

**Comment by xrkffgg** [comment]
Mac 我没测出来。。。 Windows 他们说是有问题。

@jhoneybee 来个 gif

**Comment by hengkx** [comment]
> https://ant.design 上有这个问题么？

有，我引用的 那个gif就是

**Comment by jhoneybee** [comment]
@afc163 @xrkffgg  https://ant.design  也存在这个问题
![antd](https://user-images.githubusercontent.com/24241052/91939504-88557c80-ed28-11ea-9fb5-4c8819c02aa7.gif)

**Comment by jhoneybee** [comment]
@afc163 @xrkffgg  https://ant.design  也存在这个问题
![antd](https://user-images.githubusercontent.com/24241052/91939504-88557c80-ed28-11ea-9fb5-4c8819c02aa7.gif)

**Comment by afc163** [comment]
看上去和网站的横向滚动条有关系，本来就不应该有，我去掉好了。

**Comment by hengkx** [comment]
我没有 横向 滚动 也这样
