### ISSUE TITLE
Upload组件multiple时，onChange的info.fileList数据不正确

### ISSUE THREAD

**Issue by CaanDoll** [ant-design/ant-design#26536]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/affectionate-rain-1q38v?file=/index.js)

### Steps to reproduce
同时选择三个文件上传

### What is expected?
onChange的info.fileList为三个文件

### What is actually happening?
onChange的info.fileList为两个文件

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome84 |

---
4.4.x版本没有这个问题，4.6.2有

**Comment by afc163** [comment]
看了一下在 Firefox 下 4.4.3 和 4.6.2 的行为是一致的：

4.4.3：https://codesandbox.io/s/recursing-breeze-lvgeh?file=/index.js

在 Chrome 下 4.6.2 的行为有异常：

<img width="619" alt="image" src="https://user-images.githubusercontent.com/507615/91963513-87304980-ed40-11ea-9aa8-48a63b10cf77.png">

**Comment by afc163** [comment]
可能和 #26196 的重构有关系。@Kermit-Xuan

**Comment by Kermit-Xuan** [comment]
@zombieJ 之前你做的 patch 是不是没生效还是有问题？

**Comment by zombieJ** [comment]
多个文件的没测过，我看看

**Comment by zombieJ** [comment]
多文件的时候 onChange 先触发，之后后续文件再触发 onStart 添加列表导致中间被 effect 重置掉导致丢失。有点蛋疼。

**Comment by zombieJ** [comment]
ref https://github.com/react-component/upload/blob/7822c255d84630f45ec384a79e23e504a0f81d29/src/AjaxUploader.tsx#L103

**Comment by Kermit-Xuan** [comment]
> 多文件的时候 onChange 先触发，之后后续文件再触发 onStart 添加列表导致中间被 effect 重置掉导致丢失。有点蛋疼。

但是当 `rc` 里面触发 `onChange` 并不会 导致 `antd` 也触发 `onChange`，只有当 `rc` 中触发 `onStart` 时才会冒泡到 `antd` 中，所以有点不明白为什么会丢失呢？

**Comment by mettjus** [comment]
The bug is still present, at least on "Pictures Wall". You can reproduce it by opening the [v4.6.6 "Pictures Wall" example on CodeSandbox](https://codesandbox.io/s/lzoz8), setting `mutliple={true}` and uploading 3 or more pictures at the same time. It will sometimes lose some picture (normally the last one) from the list.

**Comment by CaanDoll** [comment]
> The bug is still present, at least on "Pictures Wall". You can reproduce it by opening the [v4.6.6 "Pictures Wall" example on CodeSandbox](https://codesandbox.io/s/lzoz8), setting `mutliple={true}` and uploading 3 or more pictures at the same time. It will sometimes lose some picture (normally the last one) from the `fileList`.

+1. I found out yesterday.Only back to 4.5.4 now

**Comment by Kermit-Xuan** [comment]
I can't reproduce it in this example with uploading 5 files.

**Comment by Kermit-Xuan** [comment]
@zombieJ 我试了几次没有复现，你试试看能不能复现

**Comment by CaanDoll** [comment]
@Kermit-Xuan 昨天在应用里发现了这个问题，不仅仅是上传丢失，而且明明接口返回成功了，但有文件的状态在uploading就不改变了。但是确实试了很久用codesandbox复现不了，退回4.5.4就好了。

**Comment by Kermit-Xuan** [comment]
应该确实有问题，但是复现不了就很尴尬，应该是文件状态同步的问题，那块儿有点复杂，得有复现才能追踪具体是什么问题。

**Comment by CaanDoll** [comment]
可能得用真实的upload url来复现，mock的url确实复现不了QAQ

**Comment by deathemperor** [comment]
I can confirm this issue on antd 4.6.4 when uploading more than 2 files.
As far as I debug, the `onChange` on `Dragger` does not trigger for those files.

**Comment by Kermit-Xuan** [comment]
> I can confirm this issue on antd 4.6.4 when uploading more than 2 files.
> 
> As far as I debug, the `onChange` on `Dragger` does not trigger for those files.

Can you provide a reproduce example?

Thanks a lot.

**Comment by Catsbe** [comment]
[我在本地模拟出来了，并且打印了每个事件触发的fileList状态，这是打印结果，希望能帮助到你们定位问题
![12](https://user-images.githubusercontent.com/25682800/95643650-13bdec80-0ae3-11eb-9e5c-eb4b758f6937.png)

**Comment by zombieJ** [comment]
@Catsbe，有代码重现吗？给个 codesandbox 哈

**Comment by Catsbe** [comment]
@zombieJ  https://codesandbox.io/s/falling-cookies-msy7n?file=/src/App.js 使用react 的hook写法useState去更新状态貌似就会出现这个问题，class写法，我在codesandbox 模拟不出来（之前也碰到过这种问题，使用把class组件setState封装成同步的就能解决）

**Comment by tanlecouheguo** [comment]
@zombieJ 我的4.8.0版本还是有这个问题现在有解决吗？

**Comment by CaanDoll** [comment]
@afc163 @zombieJ

**Comment by zombieJ** [comment]
蛋疼，得再加一个事件来处理一下

**Comment by zombieJ** [comment]
@CaanDoll , 你最新版本会有这个问题吗？我更新到 4.9.x 似乎重现不出来：https://codesandbox.io/s/tuozhuaishangchuan-antd483-forked-wvnh0

**Comment by zombieJ** [comment]
@Catsbe 最新版能重现吗？

**Comment by Catsbe** [comment]
@zombieJ  我升级到4.9.1后，正式环境和测试环境均没重现，但是现在诡异的是正式环境没问题，测试环境数量是对了，但是就是状态有问题，如图
![image](https://user-images.githubusercontent.com/25682800/102190078-7f14a800-3ef2-11eb-8865-d6432db25378.png)

**Comment by zombieJ** [comment]
Upload 的 props 列一下看看？

**Comment by Catsbe** [comment]
![image](https://user-images.githubusercontent.com/25682800/102191945-111db000-3ef5-11eb-9eff-5db3c2f00919.png)
![image](https://user-images.githubusercontent.com/25682800/102191988-209cf900-3ef5-11eb-9c99-888190ece5d9.png)
![image](https://user-images.githubusercontent.com/25682800/102192044-314d6f00-3ef5-11eb-8685-2a90e0105b9b.png)
![image](https://user-images.githubusercontent.com/25682800/102192074-3b6f6d80-3ef5-11eb-9ba4-48068382e232.png)

这是 props 的fileList
为了方便你看状态，我就只列了状态，按顺序查看就可以了

**Comment by zombieJ** [comment]
我是指 <Upload /> 组件的属性，想看看有没有异步的相关配置。

**Comment by Catsbe** [comment]
这是upload的属性
![image](https://user-images.githubusercontent.com/25682800/102196341-c010ba80-3efa-11eb-8828-cbec91905c5a.png)

这是处理onChange的事件
![image](https://user-images.githubusercontent.com/25682800/102196283-a96a6380-3efa-11eb-96fc-02018158c72f.png)
这是上传完成后更新 fileList
![image](https://user-images.githubusercontent.com/25682800/102196573-0c5bfa80-3efb-11eb-9ef3-5f98f5529ff6.png)

**Comment by zombieJ** [comment]
上传状态问题是稳定复现的吗？

**Comment by Catsbe** [comment]
现在有点搞心态，我本地突然又好了，服务器上也不是必现，不会是网络问题，或者缓存的问题吧。。

**Comment by CaanDoll** [comment]
@Catsbe @zombieJ 我也升到最新版了，发现有上面同学说的情况。上传多个文件如果多个文件都比较小，上传完成很快的情况下，会有一个（可能有两个，忘记了）文件在uploading 100% 状态不再change。现在这边解决的办法是不写action了 用customRequest方法，在成功和错误的情况时再setTimeout再触发一次就解决问题，但随即带来的是onChange file为done的情况多数会触发两次，只能判断value里是否已经有这个值了 有的话就丢掉，贴一些局部代码

![image](https://user-images.githubusercontent.com/23540471/102427242-eabe5880-404b-11eb-80c0-65639e3169be.png)
![image](https://user-images.githubusercontent.com/23540471/102427293-0295dc80-404c-11eb-86a5-d51de0b8bb7e.png)

**Comment by zombieJ** [comment]
Upload change to sync of `onChange` since `4.13.0`. Close

**Comment by pufei007** [comment]
我发现还是存在该问题，在4.20.6版本中

**Comment by zp1112** [comment]
我也有这个问题，请问最新版解决了吗？上传多个文件的时候，使用setState受控filelist会出现状态问题

**Comment by whieet** [comment]
我提供一个思路，**亲测有效**。
1. 使用fileList受控组件
2. 不去监听onChange方法
3. 监听beforeUpload
4. 在beforeUpload中写自己的上传逻辑
![image](https://user-images.githubusercontent.com/5194004/201376167-c4e7588b-0182-41ab-9257-2af1c41e7a6d.png)

5. 在onRemove中监听文件的删除
![image](https://user-images.githubusercontent.com/5194004/201373939-b89415c1-3b8a-45d7-8db1-3b44cfc454a9.png)

**Comment by kunkkaliu** [comment]
原因是在react 18里面对于所有事件的状态更新进行了批处理，使用flushSync来解决，在你的onChange事件里面。
		flushSync(() => {
			onChange(newFileList);
		});
