### ISSUE TITLE
How can I make the table header fixed on top on vertical scroll in antd with full window with in Table Area it should be like window scroll? 

### ISSUE THREAD

**Issue by yogitadheeraj** [ant-design/ant-design#26530]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-5zw87)

### Steps to reproduce
  <Table
                     tableProps={{
                        rowKey: "IndianExpImpId",
                        columns: ['IndianExpImpId'],
                        dataSource: [{IndianExpImpId: 1},{IndianExpImpId: 2}],
                        size: "small",
                        scroll: { x: 100   96, y: 700 },
                        pagination: false,
                        rowSelection: {
                            selectedRowKeys: [1, 2],
                            fixed: true
                        }
                    }} />

### What is expected?
How can I make the table header fixed on top on vertical scroll in antd with full window with in Table Area it should be like window scroll? 

### What is actually happening?
Inner Ant d table header fixed, but i Need browser scrolling

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | react |
| System | Window |
| Browser | Web Application  |

---
https://stackoverflow.com/questions/63296464/antd-table-header-fixed-on-top-when-scrolling-page

**Comment by afc163** [comment]
check https://ant.design/components/table/#components-table-demo-sticky
