### ISSUE TITLE
Table组件支持多数据源

### ISSUE THREAD

**Issue by huangyingjie** [ant-design/ant-design#2653]
希望在一个表格内上下对比两批结构相同的数据，目前没有这样的接口。
折中方案是上下并排两个表格，但问题一是逻辑重复，二是下面的表头显得多余。
第二个方案，是手动拼表格的各列数据，但table并没有暴露出像bootstrap那样公开的css样式库；（直接审查元素手动添加class是可以，但对代码稳定性构成的威胁是显而易见的）。

**Comment by huangyingjie** [comment]
个人倾向第二个方案，公开像bootstrap那样的table样式库，支持手动编写任何格式的table。

**Comment by huangyingjie** [comment]
两批数据中间还要有一行底色较深的分隔行，总体来说，就是希望支持手写table结构，而不是纯通过配置生成。

**Comment by benjycui** [comment]
不清楚你要实现的效果，麻烦提供更多的信息，效果图之类更好。

**Comment by afc163** [comment]
```
<table className="ant-table">
  <thead> ... </thead>
  <tbody> ... </tbody>
</table>
```

你可以这么写，然后自行覆盖样式，不会有什么大问题。

**Comment by huangyingjie** [comment]
@afc163 其实得在最外层包一个div，把ant-table class放在它上面
````js
<div className="ant-table ant-table-middle">
<table>
  <thead> ... </thead>
  <tbody> ... </tbody>
</table>
</div>
````
这是 1.8.0版本的实现方式，如果直接写在table上thead的样式会出问题。
大问题是没有，但依赖了table的内部细节，稳定性没有保障。

本质上，希望ant-design把css、html结构以及各种复杂组件剥离开，形成独立、对外公开的规范，用户可以用css+html自定义组件。
