### ISSUE TITLE
Pagination组件问题

### ISSUE THREAD

**Issue by liyuewen** [ant-design/ant-design#26533]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/pagination-cn/](https://ant.design/components/pagination-cn/)

### Steps to reproduce
文档上面的Pagination上下切换icon向下偏移了，不知道是刻意还是问题

### What is expected?
icon水平垂直居中

### What is actually happening?
向下偏移了一点点

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | win10 |
| Browser | 78.0.3887.7 |

**Comment by afc163** [comment]
什么浏览器？帮忙看看是不是 https://github.com/ant-design/ant-design/pull/26230 这个改动影响了。

**Comment by liyuewen** [comment]
> 什么浏览器？帮忙看看是不是[＃26230](https://github.com/ant-design/ant-design/pull/26230)这个规模影响了。

谷歌浏览器

**Comment by afc163** [comment]
帮忙看看是不是 #26230 这个改动影响了。

**Comment by liyuewen** [comment]
> 帮忙看看是不是[＃26230](https://github.com/ant-design/ant-design/pull/26230)这个介入影响了。

是的我修改过以后变得正常了，
修改前
![image](https://user-images.githubusercontent.com/34180728/91955554-f18fbc80-ed35-11ea-9ac0-0edad8e7fcb4.png)
修改后
![image](https://user-images.githubusercontent.com/34180728/91955530-e6d52780-ed35-11ea-97b4-8294a497ce51.png)

**Comment by xrkffgg** [comment]
看来是这个影响了
