### ISSUE TITLE
Modal render children is not sync which break getting `ref` in `useEffect`

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#26545]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-modal-bug-forked-mxxv7)

### Steps to reproduce
Open the codesandbox [link](https://codesandbox.io/s/antd-modal-bug-forked-mxxv7) , and then check the console output

### What is expected?
Can successfully get the `ref.current` of Modal's children

### What is actually happening?
It's `null`, so have to use a `setTimeout`

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome	84.0.4147.135  |

---
This bug is because when the `getContainer` prop to `Modal` is not `false`, the `Modal` component will call [`createContainer`](https://github.com/react-component/util/blob/69046a6bb2a111cb1909bf5b6a661b27a846e0f5/src/Portal.js#L6) in the cDM which will call [`getContainer`](https://github.com/react-component/util/blob/69046a6bb2a111cb1909bf5b6a661b27a846e0f5/src/Portal.js#L21) to create a new DOM element and append it to the `document.body`. **But**, it **will not** render the children at that time, on the contrary, it will trigger the [`forceUpdate`](https://github.com/react-component/util/blob/69046a6bb2a111cb1909bf5b6a661b27a846e0f5/src/Portal.js#L22) after that, and so, the `useEffect` in our component will be triggered **before** the children be mounted to the DOM because `forceUpdate` is not a "sync" operation(same as `setState`). So, when the `useEffect` fired, we cant get the children DOM instance

**Comment by NE-SmallTown** [comment]
friendly ping~

**Comment by zombieJ** [comment]
`+ rc-util@5.3.1`

Add `forceRender` in your code.

**Comment by NE-SmallTown** [comment]
ok，close for https://github.com/react-component/util/pull/150

**Comment by mikedeng** [comment]
How to solve this , I got the same problem in the latest antd@4.23.6, it doesn't work after `forceUpdate` added
