### ISSUE TITLE
Table表格结合Form表单会出现empty的values

### ISSUE THREAD

**Issue by chaserstrong** [ant-design/ant-design#26543]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-kck9z?file=/index.js)

### Steps to reproduce
先点击新增按钮，然后点击删除按钮，然后点击获取数据。 打开控制台，可以看到person为[empty, undefined]

### What is expected?
应该得到的person为空数组

### What is actually happening?
实际返回的是[empty, undefined]

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by chaserstrong** [comment]
@afc163

**Comment by chaserstrong** [comment]
@afc163 好像只要定义了，就会在validateFields的时候能获取到。 比如我demo里的person.fff[0]。

**Comment by chaserstrong** [comment]
@afc163  这个getFieldDecorator返回empty好像是form组件本来就是这样子的。 但是我改了下，这里返回还有addr:undefined我觉得非常不合理。 请帮忙看下
![image](https://user-images.githubusercontent.com/18061322/92101781-2ff9aa00-ee10-11ea-9816-29c565e797cf.png)
复现：
点击新增按钮，点击删除按钮，点击获取数据

**Comment by afc163** [comment]
See https://codesandbox.io/s/antd-reproduction-template-forked-0tm70?file=/index.js

你的最后一列添加按钮里不应该渲染 addr 的 form item。

**Comment by chaserstrong** [comment]
> See https://codesandbox.io/s/antd-reproduction-template-forked-0tm70?file=/index.js
> 
> 你的最后一列添加按钮里不应该渲染 addr 的 form item。

哦我理解了，感谢！
