### ISSUE TITLE
DatePicker.RangePicker选择日期的时候样式不对

### ISSUE THREAD

**Issue by 0408jiahuicao** [ant-design/ant-design#26544]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/date-picker-cn/](https://ant.design/components/date-picker-cn/)

### Steps to reproduce
在antd官网选择DatePicker中 日期格式这一栏默认选择时间是2015-05-01 - 2015-05-01 
1-点击日历选择2015-05-01 - 2015-06-08
第一个2015-05-01 颜色是灰色的

### What is expected?
颜色统一

### What is actually happening?
颜色不一样

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16 |
| System | MacOS |
| Browser | Chrome |

**Comment by Kermit-Xuan** [comment]
我这试了一下，没有复现

**Comment by 0408jiahuicao** [comment]
> 我这试了一下，没有复现，可以录个gif看看

/**
 * 1-选择一个时间段 例如 2020-09-01 - 2020-09-09  面板关闭
 * 2-重新打开面板(此时默认选择为上次选择的时间2020-09-01 - 2020-09-09)
 * 3-点击选择日期2020-09-01 2020-09-09 (注意：第一个日期和上次选择的日期相同！！) 
      不同点:第一个日期的颜色值为 #bfbfbf 实际上是用了placeholder的颜色值（.ant-picker-input-placeholder > input 的样式）
 *   正确颜色值为input的rgba(0, 0, 0, 0.85)
 *
 */
这个不能上传截图 太尴尬了

**Comment by 0408jiahuicao** [comment]
<img width="445" alt="屏幕快照 2020-09-03 上午10 05 23" src="https://user-images.githubusercontent.com/51318563/92063773-9362e800-edce-11ea-969f-f62182a91713.png">
