### ISSUE TITLE
Feature Request: Support any React element as Dropdown overlay prop

### ISSUE THREAD

**Issue by NE-SmallTown** [ant-design/ant-design#26558]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Make Dropdown more flexible

### What does the proposed API look like?
Like https://codesandbox.io/s/antd-feature-support-dropdown-overlay-more-frfbg , but now this has a bug that the `Select` Options will disappear when we click the Select placeholder and fly away

**Comment by afc163** [comment]
Dropdown is designed for popup menu, please use Popover or rc-trigger if you need custom popup node.

**Comment by NE-SmallTown** [comment]
Thanks, can we add the propTypes(I would prefer runtime check) check to Dropdown? By the way, seems still have problem when use `Popover` (https://codesandbox.io/s/antd-feature-support-popover-overlay-more-forked-i7gn1) , the position of Select is not correct

**Comment by afc163** [comment]
The position is correct: https://codesandbox.io/s/antd-feature-support-popover-overlay-more-forked-fher6?file=/index.js

**Comment by NE-SmallTown** [comment]
Ahh, my bad
