### ISSUE TITLE
The TypeScript definition for the Col element's size property, ColSize, is missing the `flex` property

### ISSUE THREAD

**Issue by blaiz** [ant-design/ant-design#26553]
- [X] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-xi587?file=/index.tsx)

### Steps to reproduce
Create a Col element like this: `<Col lg={{ flex: "1 1 auto" }}>` in a TypeScript file. Observe TypeScript error message.

### What is expected?
According to the API at https://ant.design/components/grid/#API, the `lg` property can receive "screen ≥ 992px, could be a span value or an object containing above props". Above props include `flex` but the type definition at https://github.com/ant-design/ant-design/blob/master/components/grid/col.tsx#L16 does not include `flex`.

### What is actually happening?
TypeScript complains that `flex` isn't a valid value.

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | macOS 10.15.6 |
| Browser | Chrome |

---
Underneath https://github.com/ant-design/ant-design/blob/master/components/grid/col.tsx#L16, I think we need to add this: `flex?: FlexType;`

**Comment by afc163** [comment]
fixed in https://github.com/ant-design/ant-design/pull/26578
