### ISSUE TITLE
AutoPlete'value didn't work

### ISSUE THREAD

**Issue by chinchillabreederz** [ant-design/ant-design#26566]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gracious-wiles-c973b?file=/index.js)

### Steps to reproduce
When I set the undefined of the value in AutoComplete,I can still choose it.
```
<AutoComplete
        value={undefined}
        options={options}
        style={{
          width: 200
        }}
        onSelect={onSelect}
        onSearch={onSearch}
        onChange={onChange}
        placeholder="control mode"
      />
```

### What is expected?
I set the undefined in the value and the AutoComplete will clear out.

### What is actually happening?
I set value and it doesn't change

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome 81.0 |

**Comment by afc163** [comment]
What is the steps to reproduce?

**Comment by afc163** [comment]
It is expected behavior, please check native input component: https://codesandbox.io/s/sweet-bas-h0q6m?file=/index.js
