### ISSUE TITLE
create-react-app 不 eject 下，無法訂製主題

### ISSUE THREAD

**Issue by Bonnie8ni** [ant-design/ant-design#26565]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/quirky-butterfly-5dmv0)

### Steps to reproduce
無法更改 primary-color

### What is expected?
可以更改 primary-color

### What is actually happening?
引入進 less 反而導致樣式全部失效
在 config-overrides 內設定的 primary-color 也無用
爬了很多文章但還是改不動 theme :'( 

###### 小聲說
專案目前有使用 qiankun
UI 只使用 atnd
create-react-app 不打算 eject

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.12.0 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
不 eject 的情况下确实无法定制主题。

**Comment by afc163** [comment]
Please follow https://ant.design/docs/react/use-with-create-react-app-cn

**Comment by Bonnie8ni** [comment]
文件內寫

> 同样，你可以使用 react-scripts-rewired 和 customize-cra 来自定义 create-react-app 的 webpack 配置。

可是設置了一樣沒有效果 😭

**Comment by afc163** [comment]
应该是 react-app-rewired，文档写错了：https://github.com/ant-design/ant-design/commit/25f2bd66c808480812e4934baffe155d72c6f162

**Comment by Bonnie8ni** [comment]
我自己專案內是用 react-app-rewired
我把最小實現倉庫修正了 react-app-rewired
https://codesandbox.io/s/quirky-butterfly-5dmv0?file=/package.json
一樣還是沒有效果

我在 codesandbox search 上沒有找到任何一個成功的範例 :'(
可以提供一個範例嗎 (拜託)

**Comment by afc163** [comment]
https://github.com/ant-design/create-react-app-antd

**Comment by Bonnie8ni** [comment]
拿 craco 取代 react-app-rewired 嗎？

**Comment by afc163** [comment]
如果你一定要用 react-app-rewired，可以参考 https://3x.ant.design/docs/react/use-with-create-react-app-cn

**Comment by Bonnie8ni** [comment]
https://codesandbox.io/s/quirky-butterfly-5dmv0?file=/config-overrides.js

我現在設定與官網文件一模一樣還是不行
react-app-rewired 就算退版號也不行

> module.exports = override(
>   fixBabelImports("import", {
>     libraryName: "antd",
>     libraryDirectory: "es",
>     style: true
>   }),
>   addLessLoader({
>     javascriptEnabled: true,
>     modifyVars: { "@primary-color": "#1DA57A" }
>   })
> );

**Comment by afc163** [comment]
建议在本地运行 codesandbox 不一定支持 react-app-rewired 。

**Comment by afc163** [comment]
可以的。
