### ISSUE TITLE
日期选择器 inputReadOnly 设置成 true 还是可以修改日期？

### ISSUE THREAD

**Issue by littlee** [ant-design/ant-design#26574]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-antonelli-2mbmt)

### Steps to reproduce
点击日期选择器输入框，可以修改日期

### What is expected?
设置了 inputReadOnly 不能修改日期

### What is actually happening?
设置了 inputReadOnly 可以修改日期

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | macos 10.15.6 |
| Browser | Chrome 85.0.4183.83 |

**Comment by afc163** [comment]
`inputReadOnly` means you cannot change date by typing in input.
