### ISSUE TITLE
treeselect treeDataSimpleMode 模式下setFieldsValue 类型不匹配

### ISSUE THREAD

**Issue by whx76** [ant-design/ant-design#2657]
本地环境

antd 版本: antd 1.8
操作系统及其版本：windows
浏览器及其版本: chrome 最新
你做了什么？

TreeSelelct 使用 setFieldsValue 赋值

1、定义简单数据
const treeDataSimple=[{"id":1, "pid":0, "label":"test1"},{"id":2, "pid":1, "label":"test2"}
,{"id":3, "pid":1, "label":"test3"}
,{"id":4, "pid":1, "label":"test4"}
,{"id":5, "pid":1, "label":"test5"}]

2、定义TreeSelect 

           <TreeSelect style={{ width: 300 }}
              dropdownStyle={{ maxHeight: 400, overflow: 'auto' }}
              treeData={treeDataSimple}
              placeholder="请选择"
              treeDefaultExpandAll
              treeDataSimpleMode={{ id: 'id', pId: 'pid', rootPId: 0 }}
              {...getFieldProps('TreeSelect') }
              />

3 为TreeSelect 赋值
  this.props.form.setFieldsValue({ 'TreeSelect': 5 });

期待的结果是：TreeSelect  显示test5

实际上的结果：TreeSelect  显示 5

如果用  this.props.form.setFieldsValue({ 'TreeSelect': ‘5’ }); 可得到期望结果，但是我的treeDataSimple里id定义是整形，赋值却需要字符串类型。

**Comment by warmhug** [comment]
可能文档没描述清楚。id pid 都是 key 但不是 value ，只是在没有设置 value 时会 fall back 而使用 id 当 value，因为 value 是 String 类型，所以要 String(id) 下。

请在每个数据项里加入 value 字段，类似这样子 `{"id":1, "pid":0, value:"1", "label":"test1"}`

我会把文档描述补充清楚点
