### ISSUE TITLE
Using FormInstance- isFieldsTouched in Class Component

### ISSUE THREAD

**Issue by saresh-krish** [ant-design/ant-design#26577]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/form-validation-forminstance-7fk5d?file=/index.js)

### Steps to reproduce
In this form i have tried form validation by using FormInstance elements in class component.

### What is expected?
I need form validation like this https://codesandbox.io/s/currying-butterfly-yjk66?file=/index.js:1543-1588. In this form using function component. I need same output in Class component.

### What is actually happening?
Using 'this.formRef.current.isFieldsTouched' and 'Form.Item shouldUpdate' it's not working properly in class component

| Environment | Info |
|---|---|
| antd | 4.1.2 |
| React | 16.13.1 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Version 79.0.3945.130 (Official Build) (64-bit) |

---
I need same form validation in class component. Inside of 'const [form] = Form.useForm();' i am using  'formRef = React.createRef();' but it shows 'Cannot read property 'isFieldsTouched' of null' . How to use this 'isFieldsTouched' and 'getFieldsError()' function in formRef.

**Comment by zombieJ** [comment]
https://ant.design/components/form/#Why-can-not-call-ref-of-From-at-first-time
