### ISSUE TITLE
Cascader  defaultValue not working in <Form.Item name='city'> with name property

### ISSUE THREAD

**Issue by totemtec** [ant-design/ant-design#26575]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/musing-cdn-jy72p?file=/index.js)

### Steps to reproduce
run my code

### What is expected?
show the defaultValue on page loaded.

### What is actually happening?
now working

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | react 16.12 |
| System | mac 10.14.6 |
| Browser | Chrome Version 84.0.4147.135 (Official Build) (64-bit) |

---
 <Form.Item name='city'> with name property

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24470
https://github.com/ant-design/ant-design/issues/25785#issuecomment-663350321
