### ISSUE TITLE
On clicking panel in collapse, the active panel should scroll into view

### ISSUE THREAD

**Issue by asifrahman001** [ant-design/ant-design#26576]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently when I click open a panel it and the panel content is out my view port, user is not able to see the active open panel. Ideally, it should scroll the clicked panel into the viewport if its hidden.

### What does the proposed API look like?
we can add one prop which can enable this feature for collapse, like scrollActivePanelIntoView={true}

**Comment by afc163** [comment]
You can manully execute `scrollIntoView` to active panel dom node in `onChange`.

**Comment by fredmaggiowski** [comment]
@afc163 are you sure you can do it? 

`onChange` provides a list of the active panel keys; from there I couldn't find a way to pick the one that has been clicked last and scroll into it, shouldn't `onChange` provide at least the actual latest change?

**Comment by Joshuajrodrigues** [comment]
did you find a way to do this ?

**Comment by monolithed** [comment]
https://github.com/ant-design/ant-design/issues/43664
