### ISSUE TITLE
Tabs type="editable-card" 时解析错误

### ISSUE THREAD

**Issue by yimi8126** [ant-design/ant-design#2658]
#### 本地环境

- antd 版本:最新
- 操作系统及其版本：
- 浏览器及其版本:

#### 你做了什么？

<Tabs type="editable-card">
                <TabPane tab="我的任务" key="0">
                    <Table/>
                </TabPane>
                {this.state.panes.map(pane => <TabPane tab={pane.title} key={pane.key}>{pane.content}</TabPane>)}
            </Tabs>

#### 你期待的结果是：
我的任务为固定，其他TabPane数量不定，可以为0

#### 实际上的结果：
非 type="editable-card"模型下显示正常，在 type="editable-card"时，解析Tabs下的Children为一个数组[Object, Array[0]]，非固定的TabPanes解析为一个Array，后面child.props.tab报错

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by yimi8126** [comment]
http://codepen.io/yimi8126/pen/VjqrAK?editors=0010

**Comment by afc163** [comment]
Ok, 我晚点看下。

**Comment by afc163** [comment]
这样写相当于

```
<Tabs>
  <Tab.Pane />
  {[ ... ]}
</Tabs>
```

这样是不支持的，固定的标签，直接加到 tabs 数组最前面就行。

http://codepen.io/anon/pen/qNLppg?editors=0010

**Comment by afc163** [comment]
感谢反馈。
