### ISSUE TITLE
使用Tree 时应onCheck的事件应返回当前选中的key值,现在返回的checked=true

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-design#26584]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
知道当前选中的是什么

### What does the proposed API look like?
checkedkey='1'

**Comment by afc163** [comment]
第一个参数是 checkedKeys，没有问题：https://codesandbox.io/s/clever-fire-0lcly?file=/index.js
