### ISSUE TITLE
Allow not overriding ::selection

### ISSUE THREAD

**Issue by breezewish** [ant-design/ant-design#26587]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Now there is a [global `::selection` style](https://github.com/ant-design/ant-design/blob/master/components/style/core/global.less#L493), which is not a style reset but a style pollution. For apps that do not want this kind of selection style, it is pretty hard to cancel the behaviour. 

Assign `@text-selection-bg` and `@text-color-inverse` doesn't always work, since there is [no standard color name](https://stackoverflow.com/questions/33448213/how-to-reset-background-color-of-selection) to represent a system default selection color and selection background color. Additionally, changing `@text-color-inverse` will break the rest of the apps, since the variable is not only used in `::selection`.

### What does the proposed API look like?
Provide a variable to allow not overriding the global `::selection`.

**Comment by afc163** [comment]
Is it adding a new less variable `@text-selection-color` a good solution?

**Comment by breeswish** [comment]
@afc163 Thanks for the suggestion! According to https://stackoverflow.com/questions/33448213/how-to-reset-background-color-of-selection , the color name to override back as default is deprecated, so that this solution might not be very perfect. How about additionally add a variable to optionally not to include `::selection` rulesets?

**Comment by codingcn** [comment]
This is  a style pollution.

**Comment by hueyhe** [comment]
It's definitely a style pollution. Here's a bad case. Text decorations fail to display when selected.

![image](https://user-images.githubusercontent.com/13460383/124695142-39aedb00-df15-11eb-9e42-ab0c6ac267b0.png)

![image](https://user-images.githubusercontent.com/13460383/124695175-46cbca00-df15-11eb-8b12-46773d7abe6f.png)

**Comment by martinfoakes** [comment]
I've managed to get around this issue, when I needed the text selection colours to stay the same and the background selection to be the main design colour, by adding to the top of my project's own `global.less` file:

```LESS
::-moz-selection {
  background: @primary-color !important;
  color: inherit !important;
}

::selection {
  color: inherit !important;
  background: @primary-color !important;
}
```

Do agree there should be an easier way to customise this though

**Comment by chocking** [comment]
可以本地拷一份antd的global.less, 然后配置less-loader的自定义plugin重定向文件加载
- react-app-rewired config-overrides.js
```node
const antdLessPlugin = require('./plugins/antdLessPlugin');
...
addLessLoader({
  lessOptions: function (loaderContext) {
    return {
      plugins: [antdLessPlugin]
    }
  }
}),
...
```

- antdLessPlugin.js
```node
const getFileManager = require('./getFileManager');

module.exports = {
  install: function(less, pluginManager, functions) {
    var FileManager = getFileManager(less);
    pluginManager.addFileManager(new FileManager());
  }
};
```

- getFileManager.js
```node
module.exports = function(less) {
  var LessFileManager = less.FileManager;

  function FileManager(options) {}

  FileManager.prototype = new LessFileManager();

  FileManager.prototype.loadFile = function(filename, currentDirectory, options, environment, callback) {
    if (filename === 'global') {
      return less.environment.fileManagers[0].loadFile('antd.global.less', __dirname, options, environment, callback);
    }
    return less.environment.fileManagers[0].loadFile(filename, currentDirectory, options, environment, callback);
  };

  return FileManager;
};

```

**Comment by afc163** [comment]
Global styles has been removed after antd 5.x, so does `::selection` style.
