### ISSUE TITLE
分页器当指定pageSizeOptions时，"条/页"消失

### ISSUE THREAD

**Issue by Codevers** [ant-design/ant-design#26580]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/xenodochial-pasteur-zolzq?file=/index.js)

### Steps to reproduce
1.自定义pageSizeOptions时，下拉项"条/页"消失

### What is expected?
“条/页”保留

### What is actually happening?
“条/页”未保留

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.12.0 |
| System | macOS Mojave v10.14.6 |
| Browser | Chrome  v80.0.3987.163 64bit |

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/pagination/releases/tag/v3.0.4
