### ISSUE TITLE
在tab标签中使用steps和modal后关闭modal时页面异常滚动的bug

### ISSUE THREAD

**Issue by daifuyang** [ant-design/ant-design#26582]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
https://codesandbox.io/s/strange-moore-nehpd?file=/src/App.js

### Steps to reproduce
点击tab页切换到弹窗，并点击【点我查看bug】后关闭modal框就会复现
预览：https://nehpd.csb.app/

### What is expected?
页面不进行任何滚动，保持原来的状态

### What is actually happening?
页面不异常滚动

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.8.6 |
| System | mac os |
| Browser |  Chrome x64 83.0.4103.61 |

---
代码：https://codesandbox.io/s/strange-moore-nehpd?file=/src/App.js
预览：https://nehpd.csb.app/

**Comment by afc163** [comment]
Fixed in `rc-dialog@8.1.2`.
