### ISSUE TITLE
AutoComplete的写上allowClear且children为Input.Search时，输入值，鼠标移上去会出现样式错误

### ISSUE THREAD

**Issue by XianZhengquan** [ant-design/ant-design#26589]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/runtime-brook-21q38?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
AutoComplete的写上allowClear且children为Input.Search时，输入值，鼠标移上去会出现样式错误，清除按钮与Input的search组件重叠
![image](https://user-images.githubusercontent.com/46179450/92218468-c3dc7c00-eecb-11ea-9d99-b1780f9348ce.png)

### What is expected?
Input的search变成 清除

### What is actually happening?
重叠了

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | latest |
| System | win10 |
| Browser | chrome 80 |

**Comment by afc163** [comment]
这种情况很难修复，建议用 Input.Search 上的 allowClear：https://codesandbox.io/s/musing-liskov-qsdoz
