### ISSUE TITLE
TabPanel

### ISSUE THREAD

**Issue by mirshahreza** [ant-design/ant-design#26585]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to have a tab panel with scrolling panels. I want to have full height the tabs in another container. but when the content is lorgaer than the panel entire of tab is scrolling . the tab headers scroll also.

### What does the proposed API look like?
I want to have something like golden layout or rc-dock. but importing them has problems.

**Comment by afc163** [comment]
> I want to have something like golden layout or rc-dock. but importing them has problems.

Maybe you should report this to https://github.com/ticlo/rc-dock/issues
