### ISSUE TITLE
Antd select   custom label not work with labelInValue

### ISSUE THREAD

**Issue by mattu36** [ant-design/ant-design#26591]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-river-jdrdf?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
https://codesandbox.io/s/charming-river-jdrdf?fontsize=14&hidenavigation=1&theme=dark

### What is expected?
https://codesandbox.io/s/charming-river-jdrdf?fontsize=14&hidenavigation=1&theme=dark

### What is actually happening?
Select label not work if I use labelInvalue. See example https://codesandbox.io/s/charming-river-jdrdf?fontsize=14&hidenavigation=1&theme=dark

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | - |
| Browser | Chrome |

![image](https://user-images.githubusercontent.com/57477215/92234233-53792f00-eeba-11ea-8efe-8d0a248fbfb2.png)
![image](https://user-images.githubusercontent.com/57477215/92234247-5b38d380-eeba-11ea-9681-886c7be85e1a.png)

**Comment by afc163** [comment]
https://codesandbox.io/s/musing-gagarin-wq4pl?file=/src/index.tsx

<img width="679" alt="image" src="https://user-images.githubusercontent.com/507615/92266874-7f280380-ef12-11ea-8306-9d49fd07ed12.png">

You forgot `key` in value.
