### ISSUE TITLE
Image Component Does Not Work As Expected When Used as Card Cover

### ISSUE THREAD

**Issue by Rocinante89** [ant-design/ant-design#26593]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-gin4o)

### Steps to reproduce
Create an Image component with a fixed height and use it inside the cover prop of a card. Create a normal img component using the same image and height and put it in another card. It will not respect the height setting.

https://gin4o.csb.app/

### What is expected?
Image component should respect height & width as an img tag would.

### What is actually happening?
The styles seem to be applied but the height especially is not being respected

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | latest |
| System | Win 10 |
| Browser | Chromium |

**Comment by afc163** [comment]
@shaodahong width and height should be applied to image element.
