### ISSUE TITLE
menu 组件报错 已解决

### ISSUE THREAD

**Issue by F2EVarMan** [ant-design/ant-design#266]
![image](https://cloud.githubusercontent.com/assets/10355060/9805961/c6d97728-5871-11e5-9745-7ad413175e84.png)
module.exports = React.createClass({
    getInitialState() {
        return {
            current: 'mail'
        }
    },
    handleClick(e) {
        console.log('click ', e);
        this.setState({
            current: e.key
        });
    },
    render() {
        return <Menu onClick={this.handleClick} selectedKeys={[this.state.current]} mode="horizontal">
    <Menu.Item key="mail">
      <i className="anticon anticon-mail"></i>导航一
        </Menu.Item>
    <Menu.Item key="app">
      <i className="anticon anticon-appstore"></i>导航二
        </Menu.Item>
    <SubMenu title={<span><i className="anticon anticon-setting"></i>导航 - 子菜单</span>}>
      <Menu.Item key="setting:1">选项1</Menu.Item>
      <Menu.Item key="setting:2">选项2</Menu.Item>
      <Menu.Item key="setting:3">选项3</Menu.Item>
      <Menu.Item key="setting:4">选项4</Menu.Item>
        </SubMenu>
    <Menu.Item key="alipay">
      <a href="http://www.alipay.com/" target="_blank">导航四 - 链接</a>
        </Menu.Item>
            </Menu>
    }
});

用的browserify 的方式

**Comment by F2EVarMan** [comment]
是module.exports 时候的问题 已解决

**Comment by zccst** [comment]
我如何才能使用到你最想的menu？
