### ISSUE TITLE
Menu - hover and active effect not wide enough

### ISSUE THREAD

**Issue by mjfwebb** [ant-design/ant-design#26603]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/overview/](https://ant.design/components/overview/)

### Steps to reproduce
Look at the main navigation on the Ant.design website and while on the component's overview page, hover over Resources

![image](https://user-images.githubusercontent.com/28074382/92307891-dde49000-ef99-11ea-8795-158bea99ec51.png)

### What is expected?
The hover/active effects on a menu item will reach their adjacent items.

### What is actually happening?
The hover/active effects are only taking the text width.

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | React |
| System | - |
| Browser | - |

**Comment by mjfwebb** [comment]
I believe this relates to https://github.com/ant-design/ant-design/pull/25622

**Comment by afc163** [comment]
It is by designed, the new design of Menu will not cover gap between items.

**Comment by mjfwebb** [comment]
@afc163 Could you or a designer please comment on why this design decision was made?
