### ISSUE TITLE
树形控件拖拽节点到当前父节点下后，选中状态无法取消

### ISSUE THREAD

**Issue by WendyFDU** [ant-design/ant-design#2660]
#### 本地环境

- antd 版本: 1.8
- 浏览器及其版本: safari

#### 你做了什么？

将节点拖拽到当前节点的父节点下

#### 你期待的结果是：

拖拽完成后取消选中状态（取消蓝色）

#### 实际上的结果：
比如把0-0-0-0拖动到0-0-0下，再把0-0-0-2拖动到0-0-0下
0-0-0-0和0-0-0-2都会保持被选中状态且无法取消

<img width="153" alt="2016-08-09 5 54 26" src="https://cloud.githubusercontent.com/assets/15245525/17512423/57185a86-5e5a-11e6-9a6d-efee78237f86.png">

<img width="232" alt="2016-08-09 5 53 23" src="https://cloud.githubusercontent.com/assets/15245525/17512399/31e40756-5e5a-11e6-912b-130367835fc3.png">

#### 可重现的在线演示
官网拖动实例demo

**Comment by warmhug** [comment]
升级到 rc-tree@1.3.9
