### ISSUE TITLE
Typescript react app fails to find CollapseInterface

### ISSUE THREAD

**Issue by var-ram** [ant-design/ant-design#26609]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-collapse-interface-type-issue-qtf4b?file=/src/StyledComponents.tsx)

### Steps to reproduce
Issue is visible when used with styled-components.
Hover over the identifier - StyledCollapse to view the typescript error

### What is expected?
No typescript errors

### What is actually happening?
CollapseInterface type should be exported 

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | Windows 10 2004 |
| Browser | Chrome v85 |

**Comment by afc163** [comment]
Could you turn off declaration in tsconfig.json?

```diff
- "declaration": true,
+ "declaration": false,
```

**Comment by var-ram** [comment]
> Could you turn off declaration in tsconfig.json?
> 
> ```diff
> - "declaration": true,
> + "declaration": false,
> ```

Yeaup makes sense to change that on the code sandbox project because its not a library. I am sure the `tsconfig` file could be further simplified for the sake of reproduction. Sorry didn't notice it because I forked off a project created for #24864.

**Comment by afc163** [comment]
It works after set `declaration` to `false`, https://codesandbox.io/s/antd-collapse-interface-type-issue-forked-r8v2z?file=/src/StyledComponents.tsx ,closing now.
