### ISSUE TITLE
当首次点击DropdownButton时，控制台报Cannot read property 'offsetWidth' of null的错误

### ISSUE THREAD

**Issue by weita0** [ant-design/ant-design#2661]
#### 本地环境

- antd 版本: 1.6.4
- 操作系统及其版本：OS X El Captain 10.11.6
- 浏览器及其版本: Chrome 52.0

#### 实际上的结果：
Cannot read property 'offsetWidth' of null

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by weita0** [comment]
代码是这个样子
http://codepen.io/anon/pen/RREwgY?editors=0011
把DropdownButton换成Dropdown，问题依然存在
<img width="1276" alt="2016-08-10 10 20 05" src="https://cloud.githubusercontent.com/assets/16428329/17539837/1613aca4-5ee4-11e6-859d-47b3565a57a6.png">

**Comment by benjycui** [comment]
你的提供的 demo 并没有问题。
