### ISSUE TITLE
calendar 组件,左上角 那一格点击会出现月份切换

### ISSUE THREAD

**Issue by mingdongtu** [ant-design/ant-design#26616]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-zhukovsky-teqpf)

### Steps to reproduce
1、点击日历左上角日期
2、月份递减

### What is expected?
不要有任何事件触发

### What is actually happening?
月份递减了

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | react |
| System | Macos 10.15.6 |
| Browser | chrome |

**Comment by xrkffgg** [comment]
那个显示的是上一个月的日期，你点击了，默认会将页面展示成那个月的数据。

如果某一个月的 周日 是 1 号的话，点击还是在当前月的。

**Comment by mingdongtu** [comment]
> 那个显示的是上一个月的日期，你点击了，默认会将页面展示成那个月的数据。
> 
> 如果某一个月的 周日 是 1 号的话，点击还是在当前月的。

哦哦 明白了 多谢解惑 @xrkffgg
