### ISSUE TITLE
table scroll x 当表头很长且表格内容是空的是时候，表格没有横向滚动条

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#26611]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
scroll={ x: 10000}，我设置了x轴的宽度，当有数据的时候有横向滚动条，数据是空的时候没有。

### What does the proposed API look like?
希望有横向滚动条

**Comment by bihongbin3027** [comment]
![image](https://user-images.githubusercontent.com/15045200/92345516-2fa52b80-f0fc-11ea-992a-786829553a7e.png)

**Comment by bihongbin3027** [comment]
就像上面这张图这样了，当有数据的时候，是存在横向滚动条的

**Comment by bihongbin3027** [comment]
![image](https://user-images.githubusercontent.com/15045200/92345669-d7225e00-f0fc-11ea-97ae-383e10afa262.png)
上图有数据的时候正常，有横向滚动条。
![image](https://user-images.githubusercontent.com/15045200/92345726-249ecb00-f0fd-11ea-9528-8ca9071d4bcb.png)
上图无数据的时候这样，文字挤没了，没有出现横向滚动条

**Comment by yoyo837** [comment]
提供下复现。

**Comment by bihongbin3027** [comment]
@yoyo837  抱歉，是有这个功能的，我把表格重新封装了一次，内部有些代码没处理好，所以才会导致这样。
