### ISSUE TITLE
React router link to internal route causes page reload

### ISSUE THREAD

**Issue by EugeneSnihovsky** [ant-design/ant-design#26624]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-o6kvyr?file=index.js](https://stackblitz.com/edit/react-o6kvyr?file=index.js)

### Steps to reproduce
Click on link in stackblitz example. Route will changed and whole page will reload

### What is expected?
Navigation with react-router-dom to internal route should not lead to page reload

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | MacOS 10.15.6 |
| Browser | Chrome |

**Comment by KarenEfereyan** [comment]
hello @EugeneSnihovsky how can I help with this?

**Comment by kiyutink** [comment]
Hey,
Could someone please provide some insight into why the PR has been closed? I'm considering picking this up but would need some info

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/33770#issuecomment-1017051635
