### ISSUE TITLE
antd什么时候官方支持next.js?

### ISSUE THREAD

**Issue by zhangwei900808** [ant-design/ant-design#26629]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决了next.js的支持性

### What does the proposed API look like?
官方提供解决方案

**Comment by zhangwei900808** [comment]
现在的next.js官方支持性不是太好，希望antd考虑官方支持next.js

**Comment by afc163** [comment]
See:

- https://github.com/hanpama/next-with-antd
- https://github.com/vercel/next.js/tree/canary/examples/with-ant-design
- https://github.com/vercel/next.js/tree/canary/examples/with-ant-design-less

**Comment by grubxy** [comment]
Next.js 官方样例运行存在问题。https://github.com/vercel/next.js/issues/18034

**Comment by didilinkin** [comment]
经测试，这个例子较新 并且可运行，[create-next-app-antd](https://github.com/ant-design/create-next-app-antd)

**Comment by skyblue** [comment]
> 经测试，这个例子较新 并且可运行，[create-next-app-antd](https://github.com/ant-design/create-next-app-antd)

更新到next@14.0.1 失效
