### ISSUE TITLE
'Image' is not exported from 'antd'.

### ISSUE THREAD

**Issue by pravishanth** [ant-design/ant-design#26620]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/y3oe2)

### Steps to reproduce
Just import Image component like this:
import { Image } from 'antd';

function ImageDemo() {
  return (
    <Image
      width={200}
      src="https://zos.alipayobjects.com/rmsportal/jkjgkEfvpUPVyRjUImniVslZfWPnJuuZ.png"
    />
  );
}

### What is expected?
Image component is supposed to be imported from antDesign

### What is actually happening?
Getting this Error: 'Image' is not exported from 'antd'.

| Environment | Info |
|---|---|
| antd | 4.5.3 |
| React | 16.13.1 |
| System | Mac OS Catalina 10.15.6 |
| Browser |  85.0.4183.83  |

---
The code provided by antDesign in the CodeSandBox and CodePen doesn't work either.
I tried with AntDesign 4.6.3. still same issue.

**Comment by shaodahong** [comment]
Can you try https://codesandbox.io/s/naughty-https-yp8ho?file=/index.js?

**Comment by shaodahong** [comment]
> The code provided by antDesign in the CodeSandBox and CodePen doesn't work either.

rc-image need greater or equal to `3.0.5` version

> Getting this Error: 'Image' is not exported from 'antd'.

antd need greater or equal to `4.6.0` version

**Comment by afc163** [comment]
Please remove yarn.lock and package-lock.json and reinstall `node_modules`.

**Comment by omretterry** [comment]
重新安装了之后还是有这个问题，antd@4.6.3。index.d.ts文件中也没有找到Image模块导出

**Comment by shaodahong** [comment]
> 重新安装了之后还是有这个问题，antd@4.6.3。index.d.ts文件中也没有找到Image模块导出

@omretterry 提供下复现的 demo

**Comment by omretterry** [comment]
> > 重新安装了之后还是有这个问题，antd@4.6.3。index.d.ts文件中也没有找到Image模块导出
> 
> @omretterry 提供下复现的 demo

回退到了antd@4.6.0，解决了这个问题

**Comment by abining** [comment]
我遇到了同样的 问题，是在接手一个老项目，react16，antd4.0，node14.18的环境下，尝试升级antd到最新，react升级到18；依然无法引入antd的image组件。最后把antd恢复到有antd的4.8版本，react依然是18版本，并且使用`import Image from 'antd/lib/image';`这种引入方式，成功引入。这个问题困扰我整整三个小时，太艰难了。

**Comment by abining** [comment]
通过查看node_modules目录下的antd目录，发现antd下的index文件确实引入了image组件并且导出，不清楚为什么不生效，已经重启了好几次项目，package-lock文件也删除了好几次，都是这样，好在问题现在解决了，也拓展了一些组件库使用的思路，对组件库的组织模式有了一丝了解。
By checking the antd directory in the node_modules directory, it is found that the index file of antd does introduce the image component and export it. It is not clear why it does not take effect. The project has been restarted for several times, and the package-lock file has also been deleted for several times. It also expands the idea of using some component libraries, and has a little understanding of the organization pattern of component libraries
