### ISSUE TITLE
react  ts ,antd v3升级到v4，之前在组件上扩展组件类型，升级之后没有目标属性或者interface.d.ts迁移到index.d.ts，这些都要手动重写吗

### ISSUE THREAD

**Issue by HomyeeKing** [ant-design/ant-design#26625]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
antd升级迁移

### What does the proposed API look like?
有一个相关的解决方案公告

**Comment by Kermit-Xuan** [comment]
没明白你的意思，可以给个 demo 么？

**Comment by HomyeeKing** [comment]
@Kermit-Xuan 

大概就是 ：

``` ts
//之前的代码 antd: v3.x
import { ColumnProps, TableRowSelection } from 'antd/lib/table/interface';

//升级后 antd: v4.x
'antd/lib/table/interface' 这里面已经没有ColumnProps，我看源码都迁移到了index.d.ts，

```

**Comment by Kermit-Xuan** [comment]
明白了，是这样的，虽然有些组件之前导出了像：`ColumnProps`, `TableRowSelection`这些类型声明，有些用户可能会用到这些属性，但是其实这不是官方推荐的写法，我们其实并不打算和希望让用户去使用这些类型声明。
比如我们使用 `Table` 时，我们希望用户去看文档，然后根据文档去写对应的属性：

``` jsx
<Table a="a" b={false} />
```
然而有些用户还是用到了这些声明，所以我们在每个大版本之中迭代时，会尽量使这些类型声明保持兼容，但是在大版本之间升级时，可能会由于重构等原因，导致原来的声明发生变化，甚至是破坏性更新。由于这些不是官方推荐的写法，设计初衷也是为了组件开发内部使用，所以在大版本迁移时可能不会有迁移指导。

**Comment by afc163** [comment]
推荐用 https://zhuanlan.zhihu.com/p/214280582 这个方式来引入类型。
