### ISSUE TITLE
About disable upload button Upload

### ISSUE THREAD

**Issue by hiep294** [ant-design/ant-design#26636]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mystifying-moon-m0pnn?file=/index.js:1197-1207)

### What is expected?
when set disabled upload, should only disable upload button

### What is actually happening?
when set disabled upload, also disable remove button in fileList item

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.12 |
| System | Window 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
#8677
