### ISSUE TITLE
完全自定义分页组件的快速跳转

### ISSUE THREAD

**Issue by shenchangchun-lab** [ant-design/ant-design#26635]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因目前官方的快速跳转在各国语言表达上的不同，而导致了描述及展现位置不正确

### What does the proposed API look like?
希望能够自定义分页组件的快速跳转

**Comment by afc163** [comment]
可以受控分页组件，然后在外部自行创建一个 goto 配合使用。
