### ISSUE TITLE
Allow to use different custom icons for arrow, search and loading icon in Select input

### ISSUE THREAD

**Issue by Delwalt** [ant-design/ant-design#26631]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am using Antd Select component and I want to add a custom arrow icon for select input.
To do that I use suffix icon prop, which works fine but the issue is the custom suffix icon also replaces the search icon and the loading icon.
This is the behavior I do not want. I only want to update the arrow icon and the rest icons should show default icons.

### What does the proposed API look like?
The solution that I think looks something like this.

This will allow user to update specific icons
```javascript
 <Select
arrowIcon={<SomeIcon />}
loadingIcon={<SomeIcon />}
searchIcon={<SomeIcon />}
}}
/>
```
And, this solution will work as usual
```javascript
<Select
suffixIcon={<SomeIcon />}
/>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24035#issuecomment-626587151

**Comment by zombieJ** [comment]
Use HOC to customize your icon with different status: https://codesandbox.io/s/cranky-heisenberg-hkqfy?file=/index.js
