### ISSUE TITLE
antd 4的表单初始值initialValues如果是静态数据可以实现初始化。如果是调用的后端服务返回值进行初始化就无法正常初始化。

### ISSUE THREAD

**Issue by cater111** [ant-design/ant-design#26634]

**Comment by cater111** [comment]
antd 4的表单初始值initialValues如果是静态数据可以实现初始化。如果是调用的后端服务返回值进行初始化就无法正常初始化

**Comment by yoyo837** [comment]
这是你代码执行时机的问题，要么数据从服务器拿到前 不渲染form，要么使用form.setFields

**Comment by cater111** [comment]
谢谢。我下午试一下第二种。再请教一下，第一种在服务器拿到数据前不渲染form怎么实现呀？

发自我的iPhone

**Comment by yoyo837** [comment]
服务器数据 && <Form ...

**Comment by cater111** [comment]
收到，我试下。好尴尬呀，居然忘了&&

发自我的iPhone

**Comment by s464446877** [comment]
很有用的解决了问题，但是为什么要这样只能在初始化的时候生效在更新state数据重新render的时候不就无效呢

**Comment by yoyo837** [comment]
> 很有用的解决了问题，但是为什么要这样只能在初始化的时候生效在更新state数据重新render的时候不就无效呢

如果一直有效，就和value受控一样了，用户编辑不了表单。
