### ISSUE TITLE
antd4的icon设计是我见过的最不合理的icon组织形式

### ISSUE THREAD

**Issue by MorganDream** [ant-design/ant-design#26639]
基于antd4对于ts和hooks的良好支持，我们决定升级antd。
为了符合项目兼容新旧代码的模式。我们用了antd3与antd4并存的模式。
` "antd": "3.0.0",
    "antd4": "npm:antd@4.6.2",
`
我们有个地方用到了icon，icon的type是动态获取的。这在antd4的icon设计模式下基本无解。于是采用了@ant-designs/compatible的兼容包，而兼容包的默认去引用antd也就是版本3了。

我见过一些UI库，基本icon的引入都是通过某个prop甚至class就能解决。像antd4的这种硬引入模式对动态化、可配置化开发极为不友好。
虽然你们可能不会给出解决方法，但还是要吐槽一下。

**Comment by yoyo837** [comment]
请看一下之前的解决方案，https://github.com/ant-design/ant-design/issues/12011 可以在issue里搜索一下为什么要这么改。

**Comment by MorganDream** [comment]
感谢回复。
我们改成了"antd": "4.6.2", "antd3": "npm:antd@3.0.0", 同时使用兼容包解决了问题。
