### ISSUE TITLE
Bug: Select/TreeSelect: Keyboard not showing up on iOS after a value is set

### ISSUE THREAD

**Issue by tkempken** [ant-design/ant-design#26648]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://select.react-component.now.sh/?path=/story/rc-select--multiple](https://select.react-component.now.sh/?path=/story/rc-select--multiple)

### Steps to reproduce
Open the link on your Android phone and click on the select box. The drop-down will open and the system keyboard is visible.
On Apple iOS the keyboard is missing. Based on this it's not possible to filter large lists or search for entries after an option was chosen.

### What is expected?
Keyboard is opening on iPhone like Android

### What is actually happening?
Keyboard will not open after value is chosen or prop value set

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | Apple iOS 13.6.1 |
| Browser | Safari |

---
I've identified that the issue exists in react-component/select too:

https://github.com/react-component/select/issues/541

**Comment by tkempken** [comment]
I've did a lot of testing and noticed the issue occurs since antd release 4.3.2.
4.3.1 was working without issues.
Based from the changelog I've identified the following changes as "might be related":

------------------------------------------------------------
Select
🐞 Fix Select virtual scroll display abnormally in compact mode. #24706
⚡️ Optimize Select multiple mode performance. #24785 @Kermit-Xuan

🐞 Fix Input component height issue in IE11. #24673 @xiaosongxiaosong

------------------------------------------------------------

**Comment by Kermit-Xuan** [comment]
@tkempken Try this link: https://select-git-fix-26648.react-component.vercel.app/

**Comment by tkempken** [comment]
![image](https://user-images.githubusercontent.com/6480656/93294912-2860da80-f7ec-11ea-95f1-3a679d45cf63.gif)

**Comment by tkempken** [comment]
Hi @Kermit-Xuan,
thanks for working on this topic!
The keyboard is opening but it will not close on single select mode.
On multiple it's right that it will stay open to select multiple.
In single mode the users expect that they already did a choise and the keyboard should disappear.
Maybe a simple "if not mode == multiple  then blur() after selection" is enough.

Best regards

**Comment by Kermit-Xuan** [comment]
OK.

But I found a new problem on my Android device. In the single selection mode, after opening the drop-down box and selecting it, the drop-down box cannot be closed.

There may be other issues on Android or IOS. Our current main energy is still on the PC, so there may be no time to make more compatibility for mobile devices.

**Comment by Zeeshan666** [comment]
how to fix it?
