### ISSUE TITLE
form.setFieldsValue does not work with checkboxes

### ISSUE THREAD

**Issue by divyanshmoonat** [ant-design/ant-design#26646]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
Create a form in functional component
Wrap a checkbox in Form.Item
Use form.setFieldsValue to set value of checkbox

### What is expected?
Checkbox value must be updated as provided value

### What is actually happening?
Checkbox values are not updating as per provided values in fsetFieldsValue

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by zombieJ** [comment]
valuePropName
