### ISSUE TITLE
table组件onChange事件的pagination没有记录当前页数current

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#26644]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ecstatic-haze-b3v5u)

### Steps to reproduce
1.  先切到第二页
2.  然后切换pageSize，10===》20
3. 会发现pagination的current从2 ==》1

### What is expected?
我期望记住当前current

### What is actually happening?
我期望记住当前current

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | mac |
| Browser | 谷歌 |

**Comment by zombieJ** [comment]
pageSize 变化会重置 current 以防止小的 pageSize 转大的 pageSize current 超出边界。你可以通过受控模式来自行封装相关逻辑。

**Comment by ISBN9527** [comment]
明白了
