### ISSUE TITLE
RangePicker 动态切换picker的时候 day类型的时候不能设置picker这个属性，设置了picker=day 就会出错

### ISSUE THREAD

**Issue by kevinzl** [ant-design/ant-design#26643]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http:/www.xxx.com](http:/www.xxx.com)

### Steps to reproduce
RangePicker 动态切换picker的时候 不能选择值 显示错误，直接选择选年选月的之后就会出现（切到picker=‘day’，出错，初始值month）

### What is expected?
修复

### What is actually happening?
修复

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | react |
| System | antd-pro4 |
| Browser | Chrome |

---
修复
![image](https://user-images.githubusercontent.com/6283852/92461864-52b70480-f1fc-11ea-8c7d-39811203558a.png)

**Comment by kevinzl** [comment]
要是有地方上传下录屏就好了

**Comment by kevinzl** [comment]
DEMO （ codesandbox ）补上去了，问题描述不知道有没有说清楚，如果没有表达清楚的话，我再补个视频地址

**Comment by afc163** [comment]
好像没看到 codesandbox 链接。

**Comment by kevinzl** [comment]
昨天搞的不知道为何没有了，被还原了，你上面提供的那个入口（https://u.ant.design/codesandbox-repro）

**Comment by kevinzl** [comment]
bug复现录屏：http://v.youku.com/v_show/id_XNDg2NTg1MTcyMA==.html?x&sharefrom=iphone&sharekey=9b209b35ed95fc5fbf89319e20abe2684
原因：好像day类型的时候不能设置picker这个属性，设置为空都不行

**Comment by kevinzl** [comment]
> 好像没看到 codesandbox 链接。

http://v.youku.com/v_show/id_XNDg2NTg1MTcyMA==.html?x&sharefrom=iphone&sharekey=9b209b35ed95fc5fbf89319e20abe2684

**Comment by kevinzl** [comment]
@afc163 
bug复现录屏：http://v.youku.com/v_show/id_XNDg2NTg1MTcyMA==.html?x&sharefrom=iphone&sharekey=9b209b35ed95fc5fbf89319e20abe2684
原因：好像day类型的时候不能设置picker这个属性，设置为空都不行
