### ISSUE TITLE
Style option doesn't work correctly in Textarea component with allowClear: true

### ISSUE THREAD

**Issue by U1in** [ant-design/ant-design#26642]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mo2jw?file=/index.js)

### Steps to reproduce
```javascript
<TextArea row={4} allowClear={true} style={{ resize: "none" }} />,
```
1. Import Textarea Component
2. pass props with { allowClear: true, style: { resize: "none" } }

### What is expected?
Textarea component can't be resize

### What is actually happening?
Textarea component can be resize

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google Chrome 版本 85.0.4183.83（正式版本） （64 位） |

**Comment by xrkffgg** [comment]
Try 
```tsx
<TextArea className="resize-none" />
```

Add css in your project

```css
.resize-none {
    resize: none;
}
```

**Comment by zombieJ** [comment]
antd wrapper additional dom when Input & TextArea use `allowClear` or `prefix` or `suffix` and `style` will append to parent dom. We may not adjust this since it will be a breaking change. Pls follow @xrkffgg suggestion as workaround.
