### ISSUE TITLE
Form.Item 内的自定义组件 无法通过form.getFieldsValue() 获取值 同样也无法验证

### ISSUE THREAD

**Issue by KouSum** [ant-design/ant-design#26649]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-401re)

### Steps to reproduce
参考重现链接

### What is expected?
通过form.getFieldsValue() 获取值

### What is actually happening?
Form.Item 内的自定义组件 无法通过form.getFieldsValue() 获取值 同样也无法验证

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.12.0 |
| System | win10  |
| Browser | 谷歌浏览器 |

**Comment by YH390389859** [comment]
[](https://github.com/ant-design/ant-design/issues/21214) v4 的表单修改值不会渲染整个 Component,目前我的做法是自己存一份整个form表单的数据进行取值...

**Comment by zombieJ** [comment]
你没把 `onChange` 事件还回去，Form 接收不到值变化：

```diff
   function Demo(props) {
     return (
       <Input
---      onChange={(a) => console.log(a.target.value)}
+++      {...props}
         type="password"
         placeholder="Password"
       />
     );
   }
```
