### ISSUE TITLE
关于表单默认验证校验信息

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#26654]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/](https://ant.design/components/upload-cn/)

### Steps to reproduce
选择框
![image](https://user-images.githubusercontent.com/8358236/92563417-20fc7700-f2aa-11ea-8faf-138f507c03d0.png)

### What is expected?
请选择

### What is actually happening?
请输入

| Environment | Info |
|---|---|
| antd | undefined |
| React | latest |
| System | mac |
| Browser |  chrome latest |

**Comment by afc163** [comment]
合理，改。

**Comment by zombieJ** [comment]
这种只能通过上层封装 sechema Form 才能做，用户自定义组件 or HOC 都是识别不了的。

**Comment by hengkx** [comment]
antd的组件可以识别 就可以了，用户自定义的 或者可以提供方式来配置

**Comment by afc163** [comment]
没有特别完美的方式进行识别，先这样吧，用户真实场景基本都需要自定义 message。
