### ISSUE TITLE
disableDate not working at datepicker custom for yearly

### ISSUE THREAD

**Issue by azputra** [ant-design/ant-design#26657]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nostalgic-brown-j8onw?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
when i installed disabledDate in yearly mode it didn't work

### What is expected?
for disabledDate yearly custom datepicker can work

### What is actually happening?
I'm working on a project that uses antd version 3.1.6, for the datepicker I made a custom year but when I added disabledDate it didn't work

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | react ^16.8.6 |
| System | windows |
| Browser | chrome |

---
https://codesandbox.io/s/nostalgic-brown-j8onw?fontsize=14&hidenavigation=1&theme=dark

**Comment by afc163** [comment]
https://ant.design/docs/react/faq#When-I-set-mode-to-DatePicker/RangePicker,-why-can-I-not-select-a-year-or-month-anymore
