### ISSUE TITLE
horizontal的menu，外层如果有100vh的元素，则折叠计算边界处会一直闪

### ISSUE THREAD

**Issue by CaanDoll** [ant-design/ant-design#26653]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/naughty-lake-xzpq0?file=/index.js)

### Steps to reproduce
拖动预览边框（或新窗口打开改变浏览器窗口大小）至折叠边界处

### What is expected?
显示正常

### What is actually happening?
一直在闪

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome84 |

---
是否折叠判断进入死循环

**Comment by Homingciu** [comment]
+1， 设置宽度和各种影响宽度的样式都会有这种问题

**Comment by Homingciu** [comment]
找到原因了，这里的style应该是{...propStyle, display: 'none'} 才对，不然设置的样式会被覆盖掉。导致原本设置了width，而这里把width丢掉，所以计算li的width时，li只根据了‘inline-block’来计算宽度，而没有width属性。所以会出错。

现在的兼容解决方式是，在css文件里面给.ant-menu-item设置样式（而不是写行间样式），这样就不会被覆盖掉。

![image](https://user-images.githubusercontent.com/26406656/92690603-dc3d1280-f373-11ea-9f71-b9d15720bc47.png)

**Comment by Homingciu** [comment]
再提一句，下面那个className没有继承原来的className，也是造成bug的原因

**Comment by xrkffgg** [comment]
PR welcome

**Comment by Homingciu** [comment]
> PR welcome

这是rc-menu组件的bug，我在这提有用吗

**Comment by yoyo837** [comment]
提到那边...

**Comment by afc163** [comment]
same problem: #26908

**Comment by Kermit-Xuan** [comment]
@afc163 我试了试好像没有问题了，你看看。

**Comment by afc163** [comment]
我测试 codesandbox 里也确实没问题了，@CaanDoll 可以确认一下，有问题我再 reopen。

**Comment by m-weeks** [comment]
@afc163 it is still an issue on this codesandbox from #26908

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/thirsty-mahavira-utg3n?file=/src/App.js)

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/30382
