### ISSUE TITLE
Table->Fixed Right column is shifted

### ISSUE THREAD

**Issue by EarlOld** [ant-design/ant-design#26661]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-fixed-columns](https://ant.design/components/table/#components-table-demo-fixed-columns)

### Steps to reproduce
1. Go to link
2. Zoom out to 90 - 80%

### What is expected?
Aligned column and header.

### What is actually happening?
Column is shifted.

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | latest |
| System | win 10 |
| Browser | chome |

![image](https://user-images.githubusercontent.com/24506752/92586783-67000d80-f29f-11ea-8825-dcf581644aff.png)
![image](https://user-images.githubusercontent.com/24506752/92586817-6f584880-f29f-11ea-97a6-61859633fe3b.png)
![image](https://user-images.githubusercontent.com/24506752/92586855-7c753780-f29f-11ea-974d-a2f6a0536f35.png)

**Comment by afc163** [comment]
Please refresh page after zoom, we are not able to resolve this kind of problem when zooming daynamicly.
