### ISSUE TITLE
AutoComplete组件的children允许同时添加Input和Option

### ISSUE THREAD

**Issue by guozhaolong** [ant-design/ant-design#26666]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前我需要AutoComplete组件显示一个带后缀图标的Input框，图标带点击事件，同时还需要AutoComplete弹出的下拉菜单中对Option的样式进行控制，因为我要对下拉菜单增加上下翻页选项，并且这两个翻页Option要区别与其他Option样式

### What does the proposed API look like?
AutoComplete的children中判断是否为数组，如果是数组，且第一个元素是Input，则用第一个元素作为getInputElement，其余元素如果为OptGroup或Option则用其余元素作为下拉元素

![image](https://user-images.githubusercontent.com/1046601/92672711-e9dea200-f34b-11ea-99f0-7dd733fd9fd2.png)

**Comment by guozhaolong** [comment]
我想在上一页和下一页这两个Option中分别添加上下边框线，但如果不用Option增加，则会有默认Option的padding生效，线的位置会不好看

**Comment by afc163** [comment]
see https://github.com/ant-design/ant-design/issues/23941

**Comment by zombieJ** [comment]
直接用 `options`，内部实现也是把 Option 转成 `options`：https://codesandbox.io/s/pensive-browser-yjzwc?file=/index.js

**Comment by guozhaolong** [comment]
你们能不能把别人的问题看清楚再回复再close啊？我直接传options能控制option的样式吗？只能控制option里面嵌入元素的样式，我要控制option的样式，因为你Option默认给我加了padding

**Comment by guozhaolong** [comment]
我如果在options中传入一个Option组件数组，会报错Invalid attribute name: `$$typeof`，你们试过这个功能吗就给我close了，我要控制Option样式，直接用options传入label和value对象的数组没法控制样式

**Comment by Kermit-Xuan** [comment]
不能传入组件的数组，需要传入 `ReactNode` 类型的数组，例如：
``` jsx
const options = [
 <span>aaa</span>,
 {
   label: 'option1',
   value: 'value1'
 }
 <span>bbb</span>
]
```

**Comment by zombieJ** [comment]
你看看我给的 demo ，里面有样式

**Comment by guozhaolong** [comment]
我知道可以传入类似span或div组件，但是他会嵌入到Option组件里面，而Option组件上的样式还是会生效，Option上面设置了padding，我需要在最外层组件上设置样式，而我传入的span等组件并不是最外层组件，最外层组件是Option

**Comment by guozhaolong** [comment]
感谢回复
