### ISSUE TITLE
Anchor文档中写了offsetBottom, 但实际代码没有相关props

### ISSUE THREAD

**Issue by zWingz** [ant-design/ant-design#26669]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/anchor-cn/#API](https://ant.design/components/anchor-cn/#API)

### What is expected?
props正确

### What is actually happening?
props不正确

![image](https://user-images.githubusercontent.com/13031838/92679353-c7a05080-f35a-11ea-916e-b4d11756a24f.png)

![image](https://user-images.githubusercontent.com/13031838/92679345-bf481580-f35a-11ea-964e-fd7d42790e20.png)

**Comment by yoyo837** [comment]
#17373 @muzea

**Comment by hengkx** [comment]
不对 看了下 代码里面 有用`Affix`,他里面有这个属性 但是也没有传递 ，这是算 bug 还是 文档 @afc163

**Comment by afc163** [comment]
文档问题，第一个版本就没有 `offsetBottom`.

https://github.com/ant-design/ant-design/commit/ef720db420c0b0f561f295a8ef8a2fbe4d4c82c8#diff-1f2d30d0addbfbbde130c7078d7eb3e0R21

**Comment by muzea** [comment]
需要在实现里面补充上这个属性吗？（周六团建，周末可以搞一下）

**Comment by afc163** [comment]
@muzea 欢迎啊。
