### ISSUE TITLE
When a page is opened with an iFrame, the image component in the page reports a cross-domain error

### ISSUE THREAD

**Issue by Darksnack** [ant-design/ant-design#26667]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ylq0r?file=/index.js)

### Steps to reproduce
When a page is opened with an iFrame, the image component in the page reports a cross-domain error
The above link can no longer display the picture

### What is expected?
The picture can be loaded normally in the iframe

### What is actually happening?
error message:
SecurityError
Blocked a frame with origin "https://ylq0r.csb.app" from accessing a cross-origin frame.

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.0 |
| System | win10 2004 |
| Browser | chrome 85.0.4183.102（x64） |

---
<img> Adding cross-Origin to the tag still does not take effect

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26620#issuecomment-688225500
