### ISSUE TITLE
Modal作为子组件不更新值

### ISSUE THREAD

**Issue by CrazySean007** [ant-design/ant-design#26665]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-omrf7)

### Steps to reproduce
table组件用自己的state创建一个tableDetail组件，setState之后新的值没有被传入tableDetail组件中更新数据，modal没有变化，重新打开后才能看见变化的内容，试过forceupdate也没有作用。

### What is expected?
Remove点击后modal中剩下两条记录

### What is actually happening?
Remove点击后modal中剩下还是三条记录

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | Windows 10家庭版 |
| Browser | Chrome Version 83.0.4103.106 (Official Build) (64-bit) |

---
请问有什么方法能够手动触发modal的更新么，子组件的forceupdate没有起作用

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-lui9l?file=/table-detail.js
