### ISSUE TITLE
Input autosize 类型下光标定位问题

### ISSUE THREAD

**Issue by ddcat1115** [ant-design/ant-design#2666]
无论人肉把光标定位在哪，输入一次后会自动跳到最后。

同时满足三个条件可重现：

1. autosize
2. 在Modal中
3. Input有绑定getFieldProps

http://codepen.io/ddcat1115/pen/ZOmoEv?editors=0010

**Comment by afc163** [comment]
Modal 这个条件很奇怪。

**Comment by RaoHai** [comment]
这个跟那个在modal里的input中输中文的bug是一样的触发条件。。

**Comment by afc163** [comment]
#2239 是同一个问题。

**Comment by afc163** [comment]
问题在于下面两处代码：

1. https://github.com/ant-design/ant-design/blob/f2a6b5342dee4d5f213a66ffeff6043a5430b931/components/input/Input.jsx#L87-L90
2. https://github.com/react-component/util/blob/f87ed4b06839ec84a0e4b93da27d533b26f40c46/src/getContainerRenderMixin.jsx#L25

Input 中先触发了自身的 setState 。再由于 Form 的存在由 onChange 触发了外层 Modal 的 update，进入了 `ReactDOM.unstable_renderSubtreeIntoContainer` 的逻辑。

Input 的 setState 后的 rerender 未完成时，`unstable_renderSubtreeIntoContainer` 渲染时组件对不上，直接重新生成了新组件，丢失了 focus 等状态。

---

解决方法：不要同时触发 setState 和 onChange 的逻辑。
