### ISSUE TITLE
Open Image component with Button

### ISSUE THREAD

**Issue by Keysi77** [ant-design/ant-design#26664]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It would be nice if I can open Image component with a button outside of component (like a modal with visible prop). Now It is not possible open Image component with explicit Button.  It is possible only if I click on Image.

### What does the proposed API look like?
Image should accept property visible (if preview is true visible shoud be also default true) and can be changed explicit (eg. with button)

![Screenshot 2020-09-09 at 13 50 34](https://user-images.githubusercontent.com/40443047/92594745-85680800-f2a3-11ea-8786-3e1ba3ddbe39.png)

**Comment by zombieJ** [comment]
@shaodahong Seems `visible` can be controlled.
