### ISSUE TITLE
Tag如何禁止鼠标悬念时变成的“手”的功能

### ISSUE THREAD

**Issue by Witee** [ant-design/ant-design#2667]
Tag如何禁止鼠标悬念时变成的“手”的功能

有时候 Tag 并不需要去“点击”，而鼠标放上去之后就成了“手”的形状，
如何禁止？

**Comment by ddcat1115** [comment]
可以设置 `className` 属性，再针对自己设置的 class 覆盖 .ant-tag 的 cursor 设定

**Comment by Witee** [comment]
感谢。回复很早就看过了，今天进行了修改。
增加：
.ant-tag{
  cursor : default!important;;
}
