### ISSUE TITLE
Button Style Issues. The diff type button on horizontal not alignment

### ISSUE THREAD

**Issue by k55k32** [ant-design/ant-design#26679]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/button-cn/](https://ant.design/components/button-cn/)

### Steps to reproduce
when `icon button` and `normal button` in the same parent, the button position not horizontal  alignment.
this is the official demo page
![image](https://user-images.githubusercontent.com/4620878/92724017-8892ef00-f39c-11ea-979a-ecb24cbafb2f.png)

### What is expected?
button horizontal alignment

### What is actually happening?
not horizontal alignment

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.0 |
| System | win10 |
| Browser | Chrome 81.0.4044.113 |

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/23671

**Comment by zombieJ** [comment]
Use Space component to do horizontal align

**Comment by zombieJ** [comment]
Seems it aligned in Mac:
<img width="272" alt="截屏2020-09-10 下午9 02 37" src="https://user-images.githubusercontent.com/5378891/92732384-f6ddae80-f3a8-11ea-92b9-bed921202371.png">
