### ISSUE TITLE
select选择器，当options中的value为数组时回显错误(select component,value of options is array ,display is error)

### ISSUE THREAD

**Issue by actt0422** [ant-design/ant-design#26677]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/autumn-snow-r85we?file=/index.js)

### Steps to reproduce
1:open https://codesandbox.io/s/autumn-snow-r85we?file=/index.js (打开链接)
2:select(选择一个选项)

### What is expected?
select dispaly label(选择器显示label)

### What is actually happening?
display value of array\[0\](选择器显示数组的第一项)

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.12.0 |
| System | macOS 10.15.5 |
| Browser | Chrome  85.0.4183.83 |

**Comment by afc163** [comment]
value 只支持 string or number: https://ant.design/components/select/#Option-props
