### ISSUE TITLE
How to use form.setFieldsValue to set default value for Dynamic Form nest Items Component with RangePicker 

### ISSUE THREAD

**Issue by haixin7** [ant-design/ant-design#26671]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/eager-goodall-sx72e)

### Steps to reproduce
successful to use form.setFieldsValue to set a default value for Business Name, but do not work for Dynamic Form nest Items Component with RangePicker, see commented out code with **** for (form.setFieldsValue) part 

### What is expected?
successfully to use ( form.setFieldsValue) to set a default value for Dynamic Form nest Items Component with RangePicker

### What is actually happening?
successful to use( form.setFieldsValue) to set a default value for Business Name, but do not work for Dynamic Form nest Items Component with RangePicker, see commented out code with **** for (form.setFieldsValue) part. Can not set the default value for Dynamic Form nest Items Component with RangePicker after submitting the form. 

| Environment | Info |
|---|---|
| antd | undefined |
| React |  "react": "^16.13.1" |
| System | 10.11.6 |
| Browser | chrome Version 85.0.4183.83  |

**Comment by zombieJ** [comment]
https://codesandbox.io/s/modern-forest-bpolt?file=/index.js
