### ISSUE TITLE
Table x/y scroll issue in Firefox: lagging/janky table header when x scrolling on a table with fixed header

### ISSUE THREAD

**Issue by mathieu-anderson** [ant-design/ant-design#26680]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
Example from the docs (has a minor version of the bug)
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clxck)

Repro from official repro sandbox fork
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qcvei)

Repro from other sandbox (for some reason the bug is worse than in the official repro sandbox)
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-margulis-3jhyr)

### Steps to reproduce
- Open Firefox 
- Navigate to https://codesandbox.io/s/clxck (the official example sandbox in that section of the docs: https://ant.design/components/table/#components-table-demo-fixed-columns-header )
- Scroll horizontally
- You will see the header behave in a very janky manner : https://i.imgur.com/GdP0RPj.gif

Gif of the behaviour in other repro : https://i.imgur.com/fEBokIv.gif

Gif of "stuck scrolling" from other repro sandbox https://codesandbox.io/s/gifted-margulis-3jhyr :  https://i.imgur.com/ynEotP7.gif

### What is expected?
The headers are perfectly in sync with the columns and do not get misaligned while scrolling, as it behaves on Google Chrome.

### What is actually happening?
The example sandbox from the docs linked and the gif are not a perfect reproduction of the bug I encounter in our application (much less severe), but using the example given by the official docs, it gives a glimpse into what seems to be a major compatibility problem with Firefox when using the `Table` component in conjunction with the `scroll` prop set with an object with both `x` and `y` props.

It also gives a glimpse about how *inconsistent* this bug is, as it seems to not always happen, and its severity is also very variable.

This inconsistency makes it very hard to reproduce to the full extent to which we feel it in our current app. In our app, the severity of this bug is quite high and *unpredictable*:
- consistently janky headers
- sometimes the scrolling gets stuck when scrolling all the way to the end on the horizontal axis
- sometimes no issue happens on one machine, while others suffer
- sometimes no issue is visible in local environment, but visible when deployed to staging

And it shows that it is not as simple as setting proper width value on the columns, which is the main solution offered in all the other issues that touch on this bug.

EDIT: the other repro sandbox shows the bug in a much more reliable and obvious manner.

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | Mac OS Mojave 10.14.6 |
| Browser | Firefox 80.0.1 |

---
I think some serious thoughts should be given to ensure compatibility of all `Table` features with Firefox.

**Comment by mathieu-anderson** [comment]
I see the bug (a mild version of it) in the codesandbox I linked, if you open it in Firefox 80.0.1.

This is a close reproduction of our implementation: https://codesandbox.io/s/gifted-margulis-3jhyr

The bug is exactly reproduced (if opened in Firefox 80.0.1, no issue in Chrome 85.0.4183.83). It is still inconsistent, but seems to mostly happen when:
- scrolling quickly on first render
- scrolling all the way to the right, and scrolling back to the left
- scrolling all the way to the right, changing tab in browser, then coming back to the Table : this might trigger the stuck scrolling seen here (user is trying to scroll left: https://i.imgur.com/ynEotP7.gif)

**Comment by mathieu-anderson** [comment]
Were you able to see the bug in the repro links provided ?

**Comment by zombieJ** [comment]
Table sync `scrollLeft` by `onScroll` event. Not sure why so laggy in the reproduce. Could you help to invest on this?

ref: https://github.com/react-component/table/blob/f91bcd72fb1d948f4b42ab073c0af767f4a484c3/src/Table.tsx#L448

**Comment by mathieu-anderson** [comment]
I found this bug report on Bugzilla that might be related. https://bugzilla.mozilla.org/show_bug.cgi?id=1661929

**Comment by zombieJ** [comment]
> https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects

This ref seems not resolve FF async align `scrollLeft` issue. But I guess we can wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1661929 to resolve.

**Comment by mathieu-anderson** [comment]
Another clue to add to the investigation : opening devtools seem to reliably fix the issue. Link to video (probabyl best viewed in full screen): https://imgur.com/a/ylg8266
