### ISSUE TITLE
The existing language pack does not support standard Arabic

### ISSUE THREAD

**Issue by zc3130902** [ant-design/ant-design#26687]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现有的语言包只支持 阿拉伯语（埃及）ar-EG 并不支持标准阿拉伯语ar-AR。
因为阿拉伯语世界 埃及只是类方言的一种，所以希望官方能添加 标准阿拉伯语支持

### What does the proposed API look like?
Add standard Arabic support ar-AR

**Comment by yoyo837** [comment]
这个需要操持该语言的人来贡献

**Comment by afc163** [comment]
closing for no response.
