### ISSUE TITLE
input textarea下滚动条与清空按钮过于接近

### ISSUE THREAD

**Issue by kele5240** [ant-design/ant-design#26688]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
官方例子里就有，带移除图标的input里，多次回车出现滚动条后可复现

### What is expected?
调整距离

### What is actually happening?
距离过于接近，影响视觉

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | macos |
| Browser | chrome |

**Comment by xrkffgg** [comment]
输入文字和 清除按钮 也有重叠的部分

**Comment by afc163** [comment]
不好解决：https://github.com/ant-design/ant-design/issues/25643

**Comment by afc163** [comment]
Textarea 因为可以有多行，留 padding 会导致右边一大块空间浪费，所以目前设计上是比较贴近的。
