### ISSUE TITLE
umi3 配置开启 antd compact=true 出现Failed to compile

### ISSUE THREAD

**Issue by ArronYR** [ant-design/ant-design#26698]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://umijs.org/zh-CN/plugins/plugin-antd#compact](https://umijs.org/zh-CN/plugins/plugin-antd#compact)

### Steps to reproduce
使用 https://umijs.org/ 创建项目，在`.umirc.ts`中然后开启 antd 的配置如下：
```
antd: {
  dark: false,
  compact: true,
}
```
`compact`为`false`时正常，当`compact`为`true`出现编译错误，其结果如下：
```
./node_modules/antd/es/table/style/index.less
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/less-loader/dist/cjs.js):

@table-header-sort-active-filter-bg: lighten(@table-header-sort-active-bg, 2%);
@table-sticky-zindex: @zindex-table-fixed   1;
^
Operation on an invalid type
      in /xxx/node_modules/antd/es/table/style/index.less (line 12, column 0)
    at runMicrotasks (<anonymous>)
```

### What is expected?
期望结果为正常使用`antd`的`compact`样式

### What is actually happening?
编译错误

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.12.0 |
| System | Mac 10.14.6 (18G6020) |
| Browser | Chrome 85.0.4183.83 |

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/93017449-b6835980-f57d-11ea-9974-c2d2587b5681.png)

未复现

**Comment by ArronYR** [comment]
将原先的`umi`版本`3.2.2`修改为`3.2.20`，删除了`@umijs/core: latest`（使用最新的`yarn create @umijs/umi-app`生成的项目依赖中没有`@umijs/core`），重新启动没有发送编译错误。谢谢
