### ISSUE TITLE
切换阿拉伯语言后，面包屑组件会触发RTL模式，设置ConfigProvider为ltr也无效

### ISSUE THREAD

**Issue by hello-lun** [ant-design/ant-design#26692]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://test-part-time.yy.com/](https://test-part-time.yy.com/)

### Steps to reproduce
1、点击右上角切换语言，选择“阿拉伯”语言。
2、点击"任务广场"下方的任务卡片的”进入“即可。
3、在顶部会有面包屑，此时的面包屑为RTL模式，当切换回“中文”就会变回LTR正常的模式
注意：（代码已经使用antd的ConfigProvider设置成LTR模式，但依然不管用）

### What is expected?
期望切换到阿拉伯语言后，面包屑依然为LTR模式

### What is actually happening?
实际结果是：切换到阿拉伯语言后，面包屑变成RTL模式

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | 16.13.1 |
| System | win10，版本18362 |
| Browser | 谷歌，火狐，edge |

**Comment by xrkffgg** [comment]
![image](https://user-images.githubusercontent.com/29775873/92859621-efaab500-f429-11ea-9b26-5b608c621ad7.png)

我并没有在样式中看到有关任何 rtl 的样式

**Comment by hello-lun** [comment]
> ![image](https://user-images.githubusercontent.com/29775873/92859621-efaab500-f429-11ea-9b26-5b608c621ad7.png)
> 
> 我并没有在样式中看到有关任何 rtl 的样式

可为啥会这样的呢？

**Comment by xrkffgg** [comment]
会哪样？

**Comment by xrkffgg** [comment]
应该是你项目样式的问题。
