### ISSUE TITLE
Why the data lag displayed in Modal-Form?用Madal-Form方式展示数据会有滞后的情况

### ISSUE THREAD

**Issue by weah2000** [ant-design/ant-design#26690]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/solitary-water-zvqrc?file=/src/App.js)

### Steps to reproduce
When you click the button in the table to display the data of the current row, after closing the window, and then click the other row buttons, it is always the first data. If form.resetFields() is used, the data will change. When it will lag, the display is up Data for one click.
当点击表格中按钮展示当前行的数据时,关闭窗口后,再点击其他行按钮,始终是第一次的数据,如果使用了form.resetFields(),数据会变化,当会滞后,展示的是上一次点击的数据.

### What is expected?
Display the data you want to display.
显示想要展示的数据

### What is actually happening?
When you click the button in the table to display the data of the current row, after closing the window, and then click the other row buttons, it is always the first data. If form.resetFields() is used, the data will change. When it will lag, the display is up Data for one click.
当点击表格中按钮展示当前行的数据时,关闭窗口后,再点击其他行按钮,始终是第一次的数据,如果使用了form.resetFields(),数据会变化,当会滞后,展示的是上一次点击的数据.

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | chrome 83.0.4103.116 |

---
antd 3.x is no problem.

**Comment by weah2000** [comment]
Modal.onCancel =>show data is no change, always the first data.
Modal.onOk => show data is change, but lag, the last date.

**Comment by weah2000** [comment]
Preview
https://s31.aconvert.com/convert/p3r68-cdx67/rjcyz-9d42v.gif

**Comment by mjfwebb** [comment]
You can try to add `destroyOnClose` to the Modal.

The reason the values aren't being updated is because the Modal's initial values were set to whatever the first Item was, when it was created, and then it is not being recreated, just hidden/shown.

**Comment by weah2000** [comment]
> You can try to add `destroyOnClose` to the Modal.
> 
> The reason the values aren't being updated is because the Modal's initial values were set to whatever the first Item was, when it was created, and then it is not being recreated, just hidden/shown.

i added,but it didn't work.
https://codesandbox.io/s/solitary-water-zvqrc?file=/src/App.js
line 64

**Comment by weah2000** [comment]
ok,I find a solution.
line 21. use form.setFieldsValue().
`  const onShowModal = (item) => {
    setVisible(true);
+    form.setFieldsValue({
+     ...item
+    });
  };`

Don't use initialValues to mount Form data!!!

**Comment by rammyblog** [comment]
> ok,I find a solution.
> line 21. use form.setFieldsValue().
> ` const onShowModal = (item) => { setVisible(true); form.setFieldsValue({ ...item }); };`
> 
> Don't use initialValues to mount Form data!!!

Thanks!!

**Comment by windyzoe** [comment]
> 
> 
> > ok,I find a solution.
> > line 21. use form.setFieldsValue().
> > ` const onShowModal = (item) => { setVisible(true); form.setFieldsValue({ ...item }); };`
> > Don't use initialValues to mount Form data!!!
> 
> Thanks!!

 this solution is not a right way.
leading to a difference between modal-ref-form & modal-hook-form.
initialValues should work. please reopen it.
兄弟们,这确实有问题啊,.为啥destroyonclose 加 preserve=false不能搞定modal-hook-form 的 initialValues.

**Comment by iambool** [comment]
> > > ok,I find a solution.
> > > line 21. use form.setFieldsValue().
> > > ` const onShowModal = (item) => { setVisible(true); form.setFieldsValue({ ...item }); };`
> > > Don't use initialValues to mount Form data!!!
> > 
> > 
> > Thanks!!
> 
> this solution is not a right way.
> leading to a difference between modal-ref-form & modal-hook-form.
> initialValues should work. please reopen it.
> 兄弟们,这确实有问题啊,.为啥destroyonclose 加 preserve=false不能搞定modal-hook-form 的 initialValues.

完全同意，期待官方同学能看到并解决此类问题，个人认为目前的实现方式不太合理

**Comment by TillMac** [comment]
I have the same problem in "antd" 5.0.0 version. But a little bit different is that I use the state to change the initialValue. Anyway, I use the solution found in #22372  to solve this problem:

目前使用 "antd": "5.0.0"，在 Modal 中的 form 表單值也有以上狀況，但比較不同的是，我使用 state 來設定 form 的 initialValue。總之，我參考了 #22372 的解決方法：

```
useEffect(() => form.resetFields(), [props.initialValues]);
```
