### ISSUE TITLE
allowClear and prefix/suffix options for InputNumber

### ISSUE THREAD

**Issue by TheMisir** [ant-design/ant-design#26694]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I think InputNumber also might have same features as Input component (eg: allowClear, prefix and suffix, etc.)

### What does the proposed API look like?
Like Input props. ```<InputNumber allowClear suffix="USD" />```

**Comment by xrkffgg** [comment]
Duplicate of: https://github.com/ant-design/ant-design/issues/25901

**Comment by afc163** [comment]
`suffix` prop has been added in https://github.com/ant-design/ant-design/pull/49674
