### ISSUE TITLE
Select Component Scrolling Entire Page iOS

### ISSUE THREAD

**Issue by someyoungideas** [ant-design/ant-design#26708]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select/](https://ant.design/components/select/)

### Steps to reproduce
Visit the Ant Design select component page on an iOS device using Safari. Click the "multiple selection" component to open the dropdown and attempt to scroll through the list of options.

### What is expected?
I expect the list to be the only element that scrolls, so that I can view all the options available to select.

### What is actually happening?
The entire page is scrolling so that I can not view the options from the select.

![AntDesign_bugreport](https://user-images.githubusercontent.com/1868262/92938570-502df800-f412-11ea-9437-1e85812408a5.gif)

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | ^16.9.0 |
| System | iOS 13.7 |
| Browser | Safari 13.1.2 |

**Comment by c316** [comment]
I have also noticed this happens on Firefox when using the touch pad on my MacBook to scroll, but it doesn't happen if I use my mouse with the wheel to scroll.

Also, this doesn't happen on Chrome or Safari on my MacBook at all.

Chrome
Version 85.0.4183.102 (Official Build) (64-bit)

Safari
Version 13.1.2 (15609.3.5.1.3)

Firefox
80.0.1 (64-bit)

**Comment by c316** [comment]
I was able to workaround this issue by using the `virtual` prop on the select element.

```
<Select virtual={false}>...</Select>
```

**Comment by afc163** [comment]
Seems that it had been fixed in https://github.com/ant-design/ant-design/issues/26480#issuecomment-691271831

**Comment by IvanTsarkovV** [comment]
This bug is still reproducible in version 5+
