### ISSUE TITLE
Select在搜索时，自动完成选择时触发的onChange事件会把数字转换成字符串返回

### ISSUE THREAD

**Issue by 734364420** [ant-design/ant-design#2670]
#### 本地环境

- antd 版本: 1.6.5
- 操作系统及其版本：OS X
- 浏览器及其版本: Chrome

#### 你做了什么？

输入一段文字，不点击下面搜索出来的列表项，而是点击外部，会自动选择到匹配搜索的第一项

#### 你期待的结果是：

onChange事件接收到的参数为匹配搜索的第一项的value

#### 实际上的结果：

如果value为数字，点击外部自动选择后onChange事件接收到的参数为字符串类型，点击某一项选择则为正常的数字类型

#### 可重现的在线演示

http://codepen.io/zClouds/pen/mEayjV?editors=0011

**Comment by ddcat1115** [comment]
key 和 value 都是 string 类型，不要用 number

参见api   http://ant.design/components/select/#Option-props

**Comment by benjycui** [comment]
> 如果value为数字，点击外部自动选择后onChange事件接收到的参数为字符串类型，点击某一项选择则为正常的数字类型

@yiminghe 这个需要统一一下？
