### ISSUE TITLE
modal 中设置 getPopupContainer，弹窗显示不全/覆盖输入框

### ISSUE THREAD

**Issue by lich-yoo** [ant-design/ant-design#26704]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

#### 问题场景：
https://codesandbox.io/s/nostalgic-shtern-qz7gk?file=/App.js

在 modal 中设置 getPopupContainer (为了跟随滚动)，如果 form item 数量较少，modal body 高度没有被撑起来时
下拉弹窗就会显示异常或遮挡输入框

![image](https://user-images.githubusercontent.com/18572962/92902492-e5051580-f453-11ea-940e-6171e94f1487.png)

#### 问题分析：
处理容器高度：因为 form item 数量的动态的，所以即便为 modal body 设置 min-height 也会有异常的情况（而且只有一个 form item 时，这个 min-height 可不能太大，否则会页面过多空白）

动态设置 getPopupContainer ：因为 modal body 的高度比较好的效果是设置屏幕比例 vh，因此 body 的高度是动态的，内部是否可以滚动也是动态的。而且 item 的类型较多，自身的高度与 index 也比较难协同处理。

### What does the proposed API look like?
首先，是否有现有 api 支持这种场景？

没有的话， 
element ui 的实现方式是否可以参考： 即使设置了 getPopupContainer，select 弹窗也不会在指定容器内部（通过动态设置 top 来更新位置，达到跟随滚动的效果）

**Comment by afc163** [comment]
> 通过动态设置 top 来更新位置，达到跟随滚动的效果

这种方式性能很差，多层嵌套的情况下实现复杂，我们应该不会这么做。

图中的情况建议按照滚动区域大小相应缩短 Select 弹层高度。
