### ISSUE TITLE
Message : "Warning: Form already set 'initialValues'" Break tests

### ISSUE THREAD

**Issue by exlame** [ant-design/ant-design#26707]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modest-wildflower-r2eop?file=/index.js)

### Steps to reproduce
On opening file, there is an error in console.

### What is expected?
Console should throw a **Warning**.

Based on docs, it is acceptable to use both initials values in some spicific needs.
As it is not really an error and may be a needed behavior, it should not throw a console.error because it makes the component untestable for console.error.

### What is actually happening?
Console throw a Error and break any test that spy the console.error

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.12.0 |
| System | CodeSandbox |
| Browser | Chrome |

**Comment by afc163** [comment]
It is expected, just follow instruction in warning.

**Comment by exlame** [comment]
But.. What if we need to set both initialValues? We have to live with a false error? 
This still a `Warning` message because the form is working as intended. If the developer choose this behavior, wich is actually accepted as the doc said : `Config sub default value. Form initialValues get higher priority when conflict`. It should not be an **console error** but a **console warning**.

A Console error means that we `cannot` use this, but the doc said that we **can** use this.
