### ISSUE TITLE
Anchor: showInkInFixed no working in affix={true}

### ISSUE THREAD

**Issue by zWingz** [ant-design/ant-design#26702]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/small-glitter-vozus?file=/index.js)

https://github.com/ant-design/ant-design/blob/master/components/anchor/Anchor.tsx#L298

i think it is
```js
const anchorClass = classNames(prefixCls, {
    fixed: affix && !showInkInFixed,
});
```

### Steps to reproduce

change the props `showInkInFixed` and `affix`

### What is expected?
hide the ink in Fixed mode

### What is actually happening?
ink not hide

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | * |
| System | macOS |
| Browser | Chrome |

**Comment by afc163** [comment]
It will show ink dot when click it or scroll to active content: 

<img width="992" alt="image" src="https://user-images.githubusercontent.com/507615/93077730-d1f47e80-f6bb-11ea-8f77-86ac483597df.png">

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/commit/ca18e8cd8708fa81eac0466d5006cb9208b2d1e7
