### ISSUE TITLE
Table header show anomalous when no data and set scroll x and y

### ISSUE THREAD

**Issue by hhking** [ant-design/ant-design#26701]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/youthful-elion-1qd2s?file=/index.js)

### Steps to reproduce
- set scroll x and y
- Table dataSource is empty array
- View Table header

### What is expected?
Table header show normal

### What is actually happening?
Table header style anomalous

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.12.0 |
| System | Mac OS X |
| Browser | chrome 85.0.4183.83 |

---
preview：
![image](https://user-images.githubusercontent.com/11470599/92890149-6e631a80-f449-11ea-8011-445fc6dd8a6e.png)

**Comment by hhking** [comment]
@afc163 好像并没有解决。
我在项目里 antd 升级到 4.6.4，看 rc-table 安装的也是最新的 7.8.9，但是还是有这个问题。

**Comment by afc163** [comment]
https://codesandbox.io/s/funny-mountain-3yhtv?file=/index.js

可以的。

**Comment by hhking** [comment]
有点奇怪，我项目里还是有问题，暂时没找到原因😂。

**Comment by kaioduarte** [comment]
I'm still facing this on v4.12.2, any thought on this @afc163

Repro: https://codesandbox.io/s/fixed-header-antd4122-forked-45gbn?file=/index.js
