### ISSUE TITLE
There are should be possibility to write unit tests for form validation

### ISSUE THREAD

**Issue by EugeneSnihovsky** [ant-design/ant-design#26706]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

I read all docs, issues, stackoverflow answers and still can't test form validation.
When I try to find form field error with enzyme `.find` by selector - I can't see anything.
I use `enzyme mount` and call `form.simulate('submit')` (or `submitButton().simulate('click')`) and still can't see any validation errors. But I can see console.log validation errors from `antd`
```
async-validator: [ 'is greater than 70' ]
```
And strange thing. If I pass valid form data and call `form.simulate('submit')` (or `submitButton().simulate('click')`) - form `onFinish` callback is not fired.

There are should be some docs example for unit tests ([this](https://pro.ant.design/docs/ui-test#reference-links) is not enough). You create a great library that used for big projects, but big projects can't live without tests.

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | MacOS 10.15.6 |
| Browser | Chrome |

**Comment by brucejcw** [comment]
有没有form async-validator的example, 我用react-testing-library也测不了这个行为. 来个demo, 不需要建issue了

**Comment by shannonwells** [comment]
[Reproduces here](https://codesandbox.io/s/antd-reproduction-template-forked-fx4su?file=/index.js)

With this unit test:
```
  const doSetLoginAndSaveSession = jest.fn();
      const component = mount(
        componentWithStore(Register, store, {
          walletAddress,
          doSetLoginAndSaveSession,
        })
      );
      await component.find("Input").simulate("change", "Joanne");
      await component.find("button[type='submit']").simulate("click");
      console.log(component.html());
      expect(doSetLoginAndSaveSession).toHaveBeenCalled();
```

**Comment by GitKou** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> I read all docs, issues, stackoverflow answers and still can't test form validation. When I try to find form field error with enzyme `.find` by selector - I can't see anything. I use `enzyme mount` and call `form.simulate('submit')` (or `submitButton().simulate('click')`) and still can't see any validation errors. But I can see console.log validation errors from `antd`
> 
> ```
> async-validator: [ 'is greater than 70' ]
> ```
> 
> And strange thing. If I pass valid form data and call `form.simulate('submit')` (or `submitButton().simulate('click')`) - form `onFinish` callback is not fired.
> 
> There are should be some docs example for unit tests ([this](https://pro.ant.design/docs/ui-test#reference-links) is not enough). You create a great library that used for big projects, but big projects can't live without tests.
> 
> Environment	Info
> antd	4.6.3
> React	16.13.1
> System	MacOS 10.15.6
> Browser	Chrome

I test the validation errors by using `settimeout` which is definitely not a good way, by I cant't find any better solutions.
Here is my code with `tesing-library/react`.
```
 setTimeout(() => {
        if (successed) {
          expect(screen.getByText('ErrorsXXX').not.toBeInTheDocument());
        } else {
          expect(screen.getByText('不ErrorsXXX密码规范').toBeInTheDocument());
        }
      }, 1000);
```

**Comment by linjie997** [comment]
Hello, any news or updates regarding this topic?
I'm facing the same issue, basically the validation never triggers.
On the callback `onFieldsChange`, I can correctly see the Form new values and `touched` properties, but both fields warnings and errors are always empty even if the the validation rules should fail.
