### ISSUE TITLE
Select options should have title equal to label by default

### ISSUE THREAD

**Issue by glemiron** [ant-design/ant-design#26717]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
User can't read long select options by default 

I think that title on Select options should be equal to label by default

This feature can improve end user experience and cost nothing 

### What does the proposed API look like?
No any API changes required

**Comment by afc163** [comment]
Cannot understand, please describe with more details.

**Comment by glemiron** [comment]
When you hover on selected option you are see title 
![image](https://user-images.githubusercontent.com/22412236/93015605-9b115200-f56f-11ea-8f39-feb49c7f029f.png)

But when you hover option in select there is not such title
![image](https://user-images.githubusercontent.com/22412236/93015719-82556c00-f570-11ea-8678-41de91c000fd.png)

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/releases/tag/v11.2.1

**Comment by glemiron** [comment]
Thanks a lot!
