### ISSUE TITLE
Steps component should have previous status

### ISSUE THREAD

**Issue by Gilbert1391** [ant-design/ant-design#26712]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
By having the Step component accept a "prevStatus" property, we can control how the previous step looks like after clicking next; either valid or invalid (error)

### What does the proposed API look like?
At the moment we can only control the status of the current step and nexts

**Comment by afc163** [comment]
You should use React state to control Steps current.

**Comment by Gilbert1391** [comment]
> You should use React state to control Steps current.

I can control the state of the current step, but what I am asking is to have a way to control the previous step. When you click next, the previous step is always valid, there should be a way of showing previous step as invalid.
