### ISSUE TITLE
Not able to set value manually, which is not present in options, in an ANTD Select element

### ISSUE THREAD

**Issue by pallavicusat05** [ant-design/ant-design#26710]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There are a lot options, which the developers don't know. So, we need to provide an option to allow user to manually enter the value and search.

### What does the proposed API look like?
We are able to enter values when 'mode=tags' is set, but we can select multiple options in that case. It should be possible to achieve the same, but restrict to only single option at a time rather than multiple.

**Comment by afc163** [comment]
Try `<Select showSearch />`.

Or you should https://ant.design/components/auto-complete/ instead of Select.
