### ISSUE TITLE
Tooltip alignment in form validation

### ISSUE THREAD

**Issue by jc-1234** [ant-design/ant-design#26711]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dry-violet-9q9yf)

### Steps to reproduce
Add tooltip as message for form inputs.  Trigger validation message to show.  The tooltip is not aligned and changing tooltip's placement prop does not affect alignment.  

### What is expected?
Tooltip to honor placement prop when used in form validation.  Tooltip should show outside of the input.

### What is actually happening?
Tooltip is always to the left of the input and inside the input.  

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | Latest |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
I don't think it is a right way to use Tooltip, you have to dig by youself.
