### ISSUE TITLE
Codesandbox preview failed

### ISSUE THREAD

**Issue by zombieJ** [ant-design/ant-design#26728]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/z4tp0)

### Steps to reproduce
open

### What is expected?
work

### What is actually happening?
failed

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | latest |
| System | IOS |
| Browser | chrome |

**Comment by zombieJ** [comment]
@CompuIves @siddharthkp @SaraVieira , 
Seems `react-scripts` work locally. Not know why it failed on codesandbox. Could you pls take a look?
Thanks

**Comment by SaraVieira** [comment]
Hey!

This is definitely our bug and not antd, something may have changed and we don't find babel runtime 

It works if you install babel/runtime 

https://codesandbox.io/s/currying-grass-krskt?codemirror=1

We will take a look at why you need to install that

**Comment by zombieJ** [comment]
@SaraVieira thx for your quick response~

**Comment by zombieJ** [comment]
@SaraVieira, seems we still meet the issue. Is that plan time for fixing this?

**Comment by SaraVieira** [comment]
Can you please make an issue in our repo here https://github.com/CompuIves/codesandbox-client and delete this one?

It's easier for us to keep track :/

**Comment by zombieJ** [comment]
👌
