### ISSUE TITLE
关于表单回显问题，我在当前表单的某个input框进行修改，会进行接口的请求，使用redux进行数据的接收，然后把接收到的数据，在当前表单进行回显

### ISSUE THREAD

**Issue by 1101916341** [ant-design/ant-design#26739]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在当前表单的某个input框进行修改，会进行接口的请求，使用redux进行数据的接收，然后把接收到的数据，在当前表单进行回显

### What does the proposed API look like?
可直接使用就好

**Comment by yoyo837** [comment]
你用redux和antd没有关系

**Comment by 1101916341** [comment]
> 你用redux和antd没有关系

那我该如何处理呢？数据可以打印出来，但是无法在表单中渲染

**Comment by yoyo837** [comment]
https://ant.design/components/form-cn/

**Comment by 1101916341** [comment]
> 你用redux和antd没有关系

那我该如何处理呢？数据可以打印出来，但是无法在表单中渲染

> https://ant.design/components/form-cn/

这个文档看过了，但是用过之后没效果啊，我使用的是函数式组件，监听的是鼠标移出事件，我该在什么地方使用setFieldsValue这个方法呢

**Comment by yoyo837** [comment]
可是文档上有啊，我不明白你的问题是什么

**Comment by yoyo837** [comment]
不能达到效果上复现，我给你改

**Comment by 1101916341** [comment]
> 不能达到效果上复现，我给你改

大佬，我这边校验之后，调用接口，数据是异步的数据，我该在什么地方书写setFieldsValue这个方法啊，这方面我不是特别明白，求大佬解答一下

**Comment by yoyo837** [comment]
理论上是任何有你想设置的数据的地方，得看你自己代码怎么组织的

**Comment by yoyo837** [comment]
非bug先关闭

**Comment by Tosikat** [comment]
函数组件内的任何一个地方 if(data) { form.setFieldsValue() }

**Comment by Tosikat** [comment]
![image](https://user-images.githubusercontent.com/60771556/116388653-a0958100-a84e-11eb-95f1-2568ccbddb53.png)
为防止动态渲染表单带来的影响 这样做
