### ISSUE TITLE
input标签在ie上样式不兼容

### ISSUE THREAD

**Issue by xu-Aurora** [ant-design/ant-design#26734]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://112.17.157.241:25001/#/login](http://112.17.157.241:25001/#/login)

### Steps to reproduce
http://112.17.157.241:25001/#/login

### What is expected?
在ie上input样式和在谷歌上一样

### What is actually happening?
icon和输入框文字都偏下，且input下边框缺失

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.12.0 |
| System | mac |
| Browser | ie11 |

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/24673, please upgrade to latest version of antd 4.x
