### ISSUE TITLE
1. Modal组件关闭时希望可以取消掉关闭动画直接关闭  2. Modal组件希望添加可拖拽功能

### ISSUE THREAD

**Issue by SystemLight** [ant-design/ant-design#26733]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. 当在外部改变Modal组件的transform属性实现拖拽时，关闭弹窗的动画会让modal重新归到原位置再进行关闭，效果怪异
2. 当数据填写数据时希望可以看到弹窗后面的内容，让弹窗可以拖拽令用户编辑更加自由

## onStart
拖拽开始时回调事件

## onDrag
拖拽时回调事件

## onEnd
拖拽结束时回调事件

## closeAnimation
关闭弹窗visible属性变化时，弹窗的动画效果

## drag
Modal是否可以被拖拽

```
<Modal onStart={onDrag} onDrag={onDrag} onEnd={onDrag} closeAnimation={false} drag={true} />
```

**Comment by afc163** [comment]
1. `<Modal transitionName="" />`
2. https://github.com/ant-design/ant-design/pull/26507

**Comment by forzalianjunting** [comment]
> 1. `<Modal transitionName="" />`
> 2. #26507

请问拖拽的版本什么时候发布呢？
