### ISSUE TITLE
Tooltip, Select Dropdown not showing when opening full screen mode

### ISSUE THREAD

**Issue by debotos** [ant-design/ant-design#26731]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://qy5k8.csb.app/](https://qy5k8.csb.app/)

### Steps to reproduce
https://codesandbox.io/s/antd-reproduction-template-forked-qy5k8?file=/App.js 

This is the example code.

### What is expected?
Show all the components correctly.

### What is actually happening?
Normally it's showing all absolute positioned thing/portal things but when enabling full-screen mode nothing is showing.

| Environment | Info |
|---|---|
| antd | 4.6.1 |
| React | ^16.13.1 |
| System | MacOS 10.15.6 |
| Browser | Chrome |

---
It happening inside the full screen. For full screen, I am using https://www.npmjs.com/package/react-full-screen package.

**Comment by afc163** [comment]
Try `getPopupContainer`: https://5k7wy.csb.app/

https://codesandbox.io/s/antd-reproduction-template-forked-5k7wy

**Comment by debotos** [comment]
Thanks.
