### ISSUE TITLE
DatePicker.RangePicker After wrapping with getfieldDecorator, the date cannot be entered manually。DatePicker.RangePicker 使用 getFieldDecorator 包裹后，手动输入日期故障

### ISSUE THREAD

**Issue by NorthwesternDirector** [ant-design/ant-design#26749]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-2zglp?file=/index.js)

### Steps to reproduce
在RangePicker中，最上方input内，手动输入起始日期，继续手动输入截止日期。In RangePicker, in the top input, enter the start date manually and continue to enter the end date manually

### What is expected?
手动输入起始日期后，再手动输入结束日期，数据正常显示。After manually entering the start date and then manually entering the end date, the data will be displayed normally

### What is actually happening?
在手动输入起始日期后，再手动输入结束日期时，起始日期被清空，无法保持数据。After manually entering the start date and then manually entering the end date, the start date is cleared and the data cannot be kept.

| Environment | Info |
|---|---|
| antd | 3.26.15 |
| React | 16.13.1 |
| System | win10 |
| Browser | Chrome 85.0.4183.83 |

---
DatePicker.RangePicker 使用 getFieldDecorator 包裹后。DatePicker.RangePicker After wrapping with getfieldDecorator

**Comment by NorthwesternDirector** [comment]
输入开始值，
![image](https://user-images.githubusercontent.com/32825324/93174604-d8890180-f760-11ea-8562-a9a64f7cc223.png)
然后输入结束值，开始值被清空
![image](https://user-images.githubusercontent.com/32825324/93174736-0d955400-f761-11ea-8ddd-91432740a826.png)

**Comment by afc163** [comment]
Please upgrade to antd 4.x which has fixed this problem.
