### ISSUE TITLE
Adding setCurrentPage prop to pagination 

### ISSUE THREAD

**Issue by hildakh** [ant-design/ant-design#26744]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
This will allow additional functionality to page navigation such as redirecting users to the first/last page when a new row of data is added 

### What does the proposed API look like?

![AntDesignApi](https://user-images.githubusercontent.com/30509708/93152274-22b3a980-f6b3-11ea-9d52-9dab8371b242.png)

**Comment by afc163** [comment]
You should use `current` to control pagination.
