### ISSUE TITLE
Tabs is unsupport ref 

### ISSUE THREAD

**Issue by Kdiy** [ant-design/ant-design#26748]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codesandbox.io/s/antd-reproduction-template-forked-psrrl?file=/index.js](https://codesandbox.io/s/antd-reproduction-template-forked-psrrl?file=/index.js)

### Steps to reproduce
<Tabs  ref={this.tabsRef}>

### What is expected?
add ref

### What is actually happening?
add ref

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | 16.8.6 |
| System | windows10 |
| Browser | Google Chrome	83.0.4103.97 |

**Comment by Kdiy** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-psrrl?file=/index.js

**Comment by afc163** [comment]
Why do you need ref?

**Comment by Kdiy** [comment]
> Why do you need ref? We don't provide any features from tabs instance.
![image](http://mmobbs.oss-cn-shanghai.aliyuncs.com/111.png)
