### ISSUE TITLE
Popover 设定了 getTooltipContainer 会导致 内嵌的 DatePicker 样式失效

### ISSUE THREAD

**Issue by abbish** [ant-design/ant-design#2675]
Popover 设定了 getTooltipContainer 会导致 内嵌的 DatePicker 样式失效

如图，设置了getTooltipContainer，日期表格样式错乱，ant design 版本 1.6.5

![screen shot 2016-08-10 at 5 20 44 pm](https://cloud.githubusercontent.com/assets/138192/17548589/1cbcc294-5f1f-11e6-8d85-fe9158c47fc9.png)

![screen shot 2016-08-10 at 5 20 34 pm](https://cloud.githubusercontent.com/assets/138192/17548599/2854214c-5f1f-11e6-8f94-9787d19f55ae.png)

**Comment by afc163** [comment]
可否不设？

**Comment by abbish** [comment]
不设会随页面滚动

**Comment by afc163** [comment]
那就设到 Table 的 parentNode 上，避开 table 样式。

**Comment by abbish** [comment]
不好使，跳出了 ant-table 的 div 后就开始随页面滚动了，而且代码看上去很尴尬这样

![screen shot 2016-08-10 at 6 00 00 pm](https://cloud.githubusercontent.com/assets/138192/17549741/54a584c0-5f24-11e6-9bf5-3710145958f1.png)

![screen shot 2016-08-10 at 6 00 06 pm](https://cloud.githubusercontent.com/assets/138192/17549759/6c356704-5f24-11e6-906c-e958ae7450fa.png)

**Comment by benjycui** [comment]
给 Table 加个 wrapper，container 设为该 wrapper

**Comment by afc163** [comment]
是固定表头的 Table 么？

要不搞个重现方便调试吧：http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
如果是上条说的那样，可能需要改下 date-picker 的样式了，确保不会被 Table 影响。

**Comment by abbish** [comment]
重现地址：http://codepen.io/abbish/pen/jAXxZL

**Comment by afc163** [comment]
试试 http://codepen.io/anon/pen/RREJJV

**Comment by abbish** [comment]
抱歉回复晚了，我之前在纳闷为什么你的 case 中是可以固定，而我的不可以，请看我的例子

http://codepen.io/abbish/pen/OXdwYq

**Comment by afc163** [comment]
http://codepen.io/anon/pen/KrJxPp

需要相对父容器定位。

**Comment by abbish** [comment]
多谢，成功了
