### ISSUE TITLE
table树形展示，增加像Tree那样的异步加载数据【Table Tree display, adding asynchronous load data like Tree】

### ISSUE THREAD

**Issue by 741599086** [ant-design/ant-design#26750]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
像后台需要管理省市区数据，大型商城的分类管理这些就可用table的树形展示解决了【Like the background needs to manage provincial data, the classification of large mall management these can be used to table tree display to solve】

### What does the proposed API look like?
保持跟Tree异步加载数据一致【Keep it consistent with the Tree asynchronous load data】

**Comment by afc163** [comment]
建议自行控制 dataSource 来做异步加载效果。
