### ISSUE TITLE
Collapse 组件是否能设置一个开关？缩小展开收起的点击范围，容易误点

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#26752]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Collapse 组件目前点击收起展开的范围是整个 title 所在容器的宽度，希望能够设置为实际 title 文字的宽度

### What does the proposed API look like?
tiggerContainer ?

**Comment by afc163** [comment]
你的实际需求是什么？是否是右侧额外内容点击时不希望展开。

**Comment by Dolov** [comment]
> 你的实际需求是什么？是否是右侧额外内容点击时不希望展开。

是的是的，点击文字的时候展开收起就行了

**Comment by afc163** [comment]
可以给文字右侧包裹 `<div onClick={e => e.stopPropagation()}>text</div>` 来解决。

**Comment by Dolov** [comment]
> 可以给文字右侧包裹 `<div onClick={e => e.stopPropagation()}>text</div>` 来解决。

我们一直是用的这种方案，
但是最近发现了一个问题，如果我对页面监听了 onClick 事件，这里的禁止冒泡会阻止 onClick 事件的触发的

**Comment by afc163** [comment]
页面监听 onClick 是做什么用的？

**Comment by afc163** [comment]
你可以先用样式覆盖的方式实现这个效果：https://codesandbox.io/s/magical-pond-r2zl6?file=/index.css

**Comment by Dolov** [comment]
> 页面监听 onClick 是做什么用的？

调用方总会有一些特殊的用法的

**Comment by Dolov** [comment]
> 你可以先用样式覆盖的方式实现这个效果：https://codesandbox.io/s/magical-pond-r2zl6?file=/index.css

受教了，这个方法好简单，之前的写法太**了

**Comment by Dolov** [comment]
> 你可以先用样式覆盖的方式实现这个效果：https://codesandbox.io/s/magical-pond-r2zl6?file=/index.css

额 当使用 extra 属性的时候，这个方法似乎就不太好用了

**Comment by afc163** [comment]
还是需要开一个新属性 `headerCollapsibleOnly: boolean`，可以来一个 PR。

**Comment by Dolov** [comment]
> 还是需要开一个新属性 `headerCollapsibleOnly: boolean`，可以来一个 PR。

😯 啊呀 还没提交过 PR   代码写的太烂

**Comment by Dolov** [comment]
> 还是需要开一个新属性 `headerCollapsibleOnly: boolean`，可以来一个 PR。

我想问个其他的问题，我看 antd4.0 之后的组件大部分都是基于 Hooks 的函数式组件，有一些类组件也在逐步的改为函数式组件。
我们团队的 UI 库基本上都是基于 antd3.0 二次封装的组件。最近打算升级为 4.0   面临着函数式组件和类组件的一个抉择，我想知道 antd 团队是基于怎么样的考虑决定使用函数式组件的。有没有类似于 “...一些杂事” 这样的文章介绍呢   谢谢

**Comment by afc163** [comment]
其实没什么复杂的抉择理由，hooks 是 React 团队主推的东西，优势各方面也非常明显（React 官网可见），4.0 放弃了 React 15 的支持自然可以放心的上 hooks 了。

**Comment by Dolov** [comment]
> 其实没什么复杂的抉择理由，hooks 是 React 团队主推的东西，优势各方面也非常明显（React 官网可见），4.0 放弃了 React 15 的支持自然可以放心的上 hooks 了。



> 还是需要开一个新属性 `headerCollapsibleOnly: boolean`，可以来一个 PR。

今天尝试性的提交了一个 PR，但是提交后有一项检查没有通过，不太清楚是什么原因，能不能劳烦看一下，谢谢哈
https://github.com/react-component/collapse/pull/164
