### ISSUE TITLE
Form.List的数据回填问题

### ISSUE THREAD

**Issue by gametheworld** [ant-design/ant-design#26754]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
你的文档写得烂不说，连功能不全都网上放？还非要英文版的！！！不伦不类，就这还想与国际接轨？？？

### What does the proposed API look like?
Form.List的数据回填问题

**Comment by afc163** [comment]
请描述清楚问题，发泄情绪并不能解决问题，补充完整的信息后我会 reopen。

**Comment by yoyo837** [comment]
@gametheworld 哪里不好有本事自己来贡献、补充、完善啊，东西是开源的，社区是共建的啊，谁欠你的么？

**Comment by yoyo837** [comment]
你觉得对的贡献上来，管理员反对，你再骂不迟。

**Comment by yoyo837** [comment]
什么鬼问题都说不清楚的人，收社会虐待了在这里来发泄不满，自己烂还没本事反抗只有骂街的本事。

**Comment by gametheworld** [comment]
> 鬼问题都说不清楚的人，受社会虐待了在这里来发泄不满，自己烂还没本事

劳资就要骂你怎么啦，逼逼个毛

**Comment by yoyo837** [comment]
你骂呗，我阻止不了，你能阻止我么？你一样逼逼个毛。

我看你图快堆库又解决不了业务问题快失业了干不过老板跑来网喷，线下十足的失败者。

**Comment by yoyo837** [comment]
活生生的一个loser 嘲笑你 看不起你

**Comment by gametheworld** [comment]
> 你骂呗，我阻止不了，你能阻止我么？你一样逼逼个毛。
> 
> 我看你图快堆库又解决不了业务问题快失业了干不过老板跑来网喷，线下十足的失败者。

你也不看看你的例子，没事就在那里瞎j8 评论。浪费别人时间罢了，哟，你很牛逼啊，也没见你有多高大上，你也不是垃圾一个在这里我和我这个垃圾对骂而已！！

**Comment by gametheworld** [comment]
> 活生生的一个loser 嘲笑你 看不起你

你这辈子注定也只是一个打工而已，你快去码代码吧

**Comment by yoyo837** [comment]
我TM根本就没写例子，那个问题里我给的是个codesandbox 初始化模版，我让他把他的业务写进入，我来给他改好，有什么问题？

你TM理解中文就开喷？

**Comment by afc163** [comment]
讨论偏离问题，lock。

**Comment by yoyo837** [comment]
别 我还要和他骂

**Comment by yoyo837** [comment]
@gametheworld 打工有啥不对？打工不丢脸啊，可是我TM打工比你强啊，和你一个快失业的人比，感觉你打工你自己都觉得你自己丢脸，别打工了，拿个破碗去街上吧。

**Comment by gametheworld** [comment]
> @gametheworld打工有啥不对？打工不丢脸啊，可是我TM打工比你强啊，和你一个快失业的人比，感觉你打工你自己都觉得你自己丢脸，别打工了，拿个破碗去街上吧。

别动不动就失业，别怕，你要是失业来我公司，我可以给你一口饭吃，别怕

**Comment by yoyo837** [comment]
奥哟好厉害，我失业了不会像你这样“报复社会”，好难想象你这样的人开的公司能除了维持自己的口粮对社会有什么积极贡献？

报上你的公司来我膜拜下？

**Comment by gametheworld** [comment]
> 奥哟好厉害，我失业了不会像你这样“报复社会”，好难想象你这样的人开的公司除了维持自己的口粮还能对社会有什么积极贡献？
> 
> 报上你的公司来我膜拜下？

清醒一点大哥，别见人就怼

**Comment by yoyo837** [comment]
国内国外港澳台公司都可以，报上来，我自己动手查。

**Comment by yoyo837** [comment]
我别见人就怼？是你自己起头的。

**Comment by gametheworld** [comment]
**在form标签上面 initialValues属性可以初始Form.List的回填数据** 
`<Form
            layout="vertical"
            {...formItemLayout}
            form={form}
            //初始值
            initialValues={{
              ...rd,
            }}
            name="control-hooks"
            onFinish={onFinish}
          >`

注意name=Project ,上面初始值中rd中包含了Project这个属性,且该属性是数组，当前的Form.List的length为数组的长度，并不能看到数据对象值
`
 <Form.List name="Project">
              {(fields, { add }) => {

`
那么对应Project中的属性又该如何赋值呢？
ProjectDescribe 是Project数组对象中的属性，
也可以看官方的文档
看 下面代码中name={[field.name, 'ProjectDescribe']} 
`
<Form.List name="Project">
              {(fields, { add }) => {
                return (
                  <div>
                    <Divider orientation="left" plain className="re-cn-divider">
                      项目经历
                    </Divider>
                    {fields.map((field) => (
                      <Card>
                        <Row>
                          <Col span={24}>
                            <Form.Item
                              **name={[field.name, 'ProjectDescribe']}**
                              {...{
                                wrapperCol: {
                                  offset: 0,
                                  span: 24,
                                },
                              }}
                              label="项目描述"
                            >
                              <TextArea placeholder="" rows={5} />
                            </Form.Item>
                          </Col>
                        </Row>
                      </Card>
                    ))}
                    <Form.Item
                      {...{
                        wrapperCol: {
                          offset: 0,
                          span: 24,
                        },
                      }}
                    >
                      <Button
                        type="dashed"
                        onClick={() => {
                          add();
                        }}
                        block
                      >
                        <PlusOutlined />
                        添加项目
                      </Button>
                    </Form.Item>
                  </div>
                );
              }}
            </Form.List>


`

**Comment by Kermit-Xuan** [comment]
1、按照这里的代码模版提供一个最小复现问题的示例，方便快速定位问题和后续追踪问题。

2、描述问题（期待是什么行为？实际上是什么行为）

https://codesandbox.io/s/antd-reproduction-template-6e93z

**Comment by Bigredorange** [comment]
你好，请问动态列表如何初始化值，下面是官方示例，新增users, 在页面渲染后不显示，请问如何在Form.List初始化 users 
https://codesandbox.io/s/antd-reproduction-template-forked-8je4r

**Comment by yoyo837** [comment]
> 你好，请问动态列表如何初始化值，下面是官方示例，新增users, 在页面渲染后不显示，请问如何在Form.List初始化 users
> https://codesandbox.io/s/antd-reproduction-template-forked-8je4r

https://codesandbox.io/s/antd-reproduction-template-forked-glby2?file=/index.js

这样

**Comment by gametheworld** [comment]
> 问动态列表如何初

我的 解决办法是，新增的时候向后端添加一条数据，然后新增数据后，在查询当前的User，
1、因为这样会解决后端设计中的一个外键(关联其他主表的Id)问题，你如果不先添加一条空数据进去，那么你在总保存按钮事件中必须把外键id带上，(当然这种是存在外键的时候)，这个时候后端初始两个值，一个当前空数据的id和前端传递过去的外键id(关联其他主表的Id)，再查询之后的操作保存就是修改了
2、新添加一条空数据这个时候不需要前端生成ID，因为在后端很有可能用到的id是雪花id等等其他固定的业务规则id，所以，我选择的add按钮的时候直接调用后端的添加一条数据，这个时候只需要传递一个外键id(关联其他主表的Id)

**初始化值：**
初始化值的时候在<Form> 这个标签上有个属性initialValues初始化值就好了，
那么Form.List怎么对应数据呢？对应initialValues中的属性名即可
例子 下面json赋值到initialValues
**Form.List的写法：<Form.List name="User"> 即可**
{
     Name：‘张三’，
     User:[
            {id:'abc1',first:'张'，last:'三'}
            {id:'abc2',first:'李'，last:'四'}
     ]
}
上面是数据回填Form.List对应上了数组对象，那么Form.List中的属性该怎么初始化值呢？
**对应的属性赋值如：name={[field.name, 'id']}**
<Form.Item
                              label="ID"
                              style={{display:'none'}}
                              **name={[field.name, 'id']}**
                            >
                              <Input placeholder=""/>
                            </Form.Item>


希望可以帮到你！！！！

**Comment by gametheworld** [comment]
> 1、按照这里的代码模版提供一个最小复现问题的示例，方便快速定位问题和后续追踪问题。
> 
> 2、描述问题（期待是什么行为？实际上是什么行为）
> 
> https://codesandbox.io/s/antd-reproduction-template-6e93z

Form.List在Modal中存在初始化问题，我在第一遍Modal打开时点击了add，并没有remove，然后关闭了Model，操作：修改了Fomr.List的数据源，再次打开时Modal时，发现上一次的add的同样存在，固想问一下Form.List这种情况该怎么解决，或者说Fomr.List有没有init的操作，能保证每一次的渲染都是新的

**Comment by gametheworld** [comment]
> > 1、按照这里的代码模版提供一个最小复现问题的示例，方便快速定位问题和后续追踪问题。
> > 2、描述问题（期待是什么行为？实际上是什么行为）
> > https://codesandbox.io/s/antd-reproduction-template-6e93z
> 
> Form.List在Modal中存在初始化问题，我在第一遍Modal打开时点击了add，并没有remove，然后关闭了Model，操作：修改了Fomr.List的数据源，再次打开时Modal时，发现上一次的add的同样存在，固想问一下Form.List这种情况该怎么解决，或者说Fomr.List有没有init的操作，能保证每一次的渲染都是新的

或者说Form.List可控，并不是需要非要点remove才行？

**Comment by Kermit-Xuan** [comment]
麻烦按照给的 codesandbox 模版写一个最小复现示例，这个看起来更直观。

**Comment by hengkx** [comment]
form resetFields

**Comment by gametheworld** [comment]
> form resetFields

看到了这句话：
2. 你不能用控件的 value 或 defaultValue 等属性来设置表单域的值，默认值可以用 Form 里的 initialValues 来设置。注意 initialValues 不能被 setState 动态更新，你需要用 setFieldsValue 来更新。

**Comment by yoyo837** [comment]
你这些时间都够做个在线demo了，没有什么比在线demo更清楚你的问题

**Comment by gametheworld** [comment]
> 你这些时间都够做个在线demo了，没有什么比在线demo更清楚你的问题

官方的文档写得实在让人不敢恭维，这里一段，那里一段，零零散散，所以看得头疼

**Comment by Kermit-Xuan** [comment]
大家的本质都是想解决问题，而不是单纯的抱怨。

如果使用出了问题，你就给个复现的在线 demo 说明问题，我们这边会定位和修复，光用语言描述大家都得去猜你的意思，浪费大家的时间；

如果文档哪里不清楚或者有错误，你就截个图，我们会根据情况对文档进行改进；

**Comment by gametheworld** [comment]
> 大家的本质都是想解决问题，而不是单纯的抱怨。
> 
> 如果使用出了问题，你就给个复现的在线 demo 说明问题，我们这边会定位和修复，光用语言描述大家都得去猜你的意思，浪费大家的时间；
> 
> 如果文档哪里不清楚或者有错误，你就截个图，我们会根据情况对文档进行改进；

我已经解决了问题，并不是抱怨！！
就拿Form.List
![image](https://user-images.githubusercontent.com/6021628/93585335-345dbf80-f9d9-11ea-9553-e77c9c918b4e.png)
这个表能说明什么？赋值、操作怎么处理的？就连和传统的组件处理方式一致这句话都没有说，使用组件，使用ant的最大目的是快速开发，而不是大部分时间在这里去猜怎么用！或许我用得不够熟练理解不够透彻，但是这表是确实不敢恭维

**Comment by afc163** [comment]
@gametheworld 欢迎来 PR 帮我们改进文档。

**Comment by gametheworld** [comment]
> @gametheworld 欢迎来 PR 帮我们改进文档。

好的，没问题

**Comment by ShawLyon** [comment]
我是正常一个一个写formList能回显，循环return formList无法回显。不知道是不是因为循环是异步的问题

**Comment by zxm0429** [comment]
这都2021年了，也还是没办法回显Form.List 创建的控件啊🤔

**Comment by qinghua5453** [comment]
我回显回来了，initialValue确实不行，这个变量等同于input的defaultValue 一样。需要用setFieldsValue。
我是这样做的
let groups = [{ key: '1', value: '1-1' }];
  form.setFieldsValue({ groups: groups });
这里的groups 需要跟
<Form.List name="groups"></Form.List>的name 保持一致。
另外：
form.setFieldsValue({}) 里面是对象开头的。

**Comment by qinghua5453** [comment]
<Form.Item
                        name={[field.name, 'key']}
                        rules={[
                          {
                            required: true,
                            message: '请输入配置项key',
                          },
                        ]}
                      >
                        <Input />
                      </Form.Item>
为何是key 和value 这个字段呢？
是Form.Item 里自己随意写的。

**Comment by w995928555** [comment]
您好，Form.List 通过getValueFromEvent进行组件输入值格式化，getValueFromEvent函数的返回值无法正确的显示在视图上，但是表单域的值是getValueFromEvent函数返回的值，请问这种回显问题怎么解决 谢谢！！

**Comment by yqphare** [comment]
` <Form.List
              name="trainingTime"
              initialValue={['1']}
              rules={[
                {
                  validator: async (_, trainingTime) => {
                    if (!trainingTime || trainingTime.length < 1) {
                      return Promise.reject(new Error('至少一条数据'));
                    }
                  },
                },
              ]}
            >
              {(fields, { add, remove }, { errors }) => (
                <>
                  {fields.map((field, index) => (
                    <Form.Item
                      label={index === 0 ? '*上课时间' : ''}
                      {...(index === 0 ? formItemLayout : formItemLayoutWithOutLabel)}
                      rules={[{ required: true, message: "请输入上课时间" }]}
                      key={field.key}
                    >
                      <Form.Item
                        {...field}
                        validateTrigger={['onChange', 'onBlur']}
                        rules={[
                          {
                            required: true,
                            message: "请输入上课时间",
                          },
                        ]}
                        noStyle
                      >
                        <SelectTime s={fields}></SelectTime>
                      </Form.Item>
                      <PlusCircleOutlined style={{ margin: "0 10px" }} onClick={() => add()} />
                      {fields.length > 1 ? (
                        <MinusCircleOutlined
                          className="dynamic-delete-button"
                          onClick={() => remove(field.name)}
                        />
                      ) : null}

                    </Form.Item>
                  ))}

                </>
              )}
            </Form.List>`
const SelectTime = ({ value = {}, onChange ,s}) => {
  console.log(s);
  const options = [{ value: 1, label: "每周一" }, { value: 2, label: "每周二" }, { value: 3, label: "每周三" }, { value: 4, label: "每周四" }, { value: 5, label: "每周五" }, { value: 6, label: "每周六" }, { value: 7, label: "每周日" }]
  const [week, setWeek] = useState(0);
  const [timeRange, setTimeRange] = useState([]);
  const triggerChange = (changedValue) => {
    onChange?.({
      week,
      timeRange,
      ...value,
      ...changedValue,
    });
  };
  const onNumberChange = (value) => {
    setWeek(value);
    triggerChange({
      week: value,
    });
  };
  const onCurrencyChange = (newTimeRange) => {
      setTimeRange(newTimeRange);
    triggerChange({
      timeRange: newTimeRange,
    });
  };
  return (
    <>
      <Select

        style={{
          width: 100,
          margin: '0 8px',
        }}
        options={options}
        allowClear={true}
        placeholder={"每周几"}
        onChange={onNumberChange}
      >

      </Select>
      <TimePicker.RangePicker format={"HH:mm"} onChange={onCurrencyChange} />
    </>
  )
}
对于自定义组件 ，如何实现数据回显？在控制台中可以打印出对应的form.value,但问题是数据就是没有回显出来，官方文档确实没太详细去对formlist的使用做个讲解，所以在开发过程中就会比较难受

**Comment by yqphare** [comment]
已解决 自定义组件加入value即可
