### ISSUE TITLE
<Steps.Step> cannot be used in a wrapped component.

### ISSUE THREAD

**Issue by mikhail** [ant-design/ant-design#26764]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-liqk2?file=/index.js)

### Steps to reproduce
Wrap a Steps.Step component

### What is expected?
Steps keep rendering

### What is actually happening?
Steps are not rendering / are blank / have zero size.

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | any |
| Browser | any |

---
Even with an empty wrapper the hierarchy ends up being Steps > Context.Consumer > Step and this seems to break rendering.

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-ripi0?file=/index.js
