### ISSUE TITLE
Table cannot scroll in header

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#26766]
![image](https://user-images.githubusercontent.com/507615/93290941-71c52000-f814-11ea-91ce-767c5fad1ecc.png)

红框区域无法触发横向滚动了：https://ant.design/components/table-cn/#components-table-demo-fixed-columns-header

**Comment by afc163** [comment]
3.x 是工作的：https://codesandbox.io/s/agitated-snowflake-8iy0t?file=/index.js

**Comment by zombieJ** [comment]
ref https://github.com/react-component/table/pull/410
