### ISSUE TITLE
Tabs出现滚动时，当标签不在可视区域时使用activeKey触发切换该标签，该标签仍不在可视范围

### ISSUE THREAD

**Issue by Martin0809** [ant-design/ant-design#2676]
例如，我有8个标签，1-6在可视范围，7，8不在可视范围，当前我在标签6，这时我做了一系列操作，然后修改activeKey＝7，内容变为标签7的内容，但标签7仍不在可视范围。
或者有什么方法可以触发滚动箭头的click事件么。

**Comment by ddcat1115** [comment]
问题已修复，请更新至 1.10.0

**Comment by Martin0809** [comment]
ok, 谢谢
