### ISSUE TITLE
Warning Ellipsis props in Text

### ISSUE THREAD

**Issue by JPSantistebanQ** [ant-design/ant-design#26761]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://localhost:3000/](https://localhost:3000/)

### Steps to reproduce
Warning: [antd: Typography.Text] `ellipsis` only supports boolean value. 

### What is expected?
Warning: [antd: Typography.Text] `ellipsis` only supports boolean value. 

### What is actually happening?
Warning: [antd: Typography.Text] `ellipsis` only supports boolean value. 

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Edge Chromium |

---
Warning: [antd: Typography.Text] `ellipsis` only supports boolean value.

**Comment by afc163** [comment]
Please follow warning, ellipsis only supports boolean value.

**Comment by fadeomar** [comment]
![image](https://user-images.githubusercontent.com/39485495/121889375-d53b9a00-cd21-11eb-803e-0c72b234e658.png)

**Comment by fadeomar** [comment]
using the Paragraph gives the same Error
      ```
       <Typography.Paragraph
          style={{ maxWidth: '95%' }}
          ellipsis={{ tooltip: title, rows: 2 }}
        >
        ```
