### ISSUE TITLE
是否可以用Form嵌套？

### ISSUE THREAD

**Issue by mylesshie** [ant-design/ant-design#2677]
#### 本地环境

- antd 版本: 1.6.1
- 操作系统及其版本：windows 2007
- 浏览器及其版本: chrome 52

#### 你做了什么？

父页面上一个Form表单内嵌了一个子组件，子组件也是通过Form.create()包装过的，现在父页面通过getFieldsValue 只能获取其他表单项的数据，请问如何获取子组件里面表单的数据？子组件是3个地域选择的select

#### 你期待的结果是：

能获取到子组件表单选择的数据

#### 实际上的结果：

不确定如何获取

**Comment by benjycui** [comment]
先描述需求，毕竟不一定需要通过嵌套 Form 才能实现。

**Comment by dai875939260** [comment]
把父组件的this.props.form传到子组件就可以了吧，子组件不需要Form包装

**Comment by mylesshie** [comment]
已实现，谢谢

**Comment by weijiqiang1024** [comment]
怎么实现的啊，求解决方法 现在我是获取不到子组件form的值@mylesshie

**Comment by weijiqiang1024** [comment]
已实现 把父子组件改写成兄弟组件 去除form表单嵌套

**Comment by changfu2015** [comment]
> 已实现 把父子组件改写成兄弟组件 去除form表单嵌套

这样做数据无法嵌套，

**Comment by wangzhengbo** [comment]
有一个组件，表单项比较多，完全用Form实现的。突然有一天有需求，需要把这个组件嵌入到另外一个表单组件里面去，导致Form下嵌套Form。感觉没有很好的迁移方式。
