### ISSUE TITLE
Form: How do programmatically mark a form field as touched?

### ISSUE THREAD

**Issue by mendoncanorma** [ant-design/ant-design#26772]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I want to know how to programmatically mark form field as touched.

### What does the proposed API look like?
N/A

**Comment by mendoncanorma** [comment]
@afc163 , could you please tell me how do I mark field as touched. This not an issue, but I didn't find any documentation on this.

**Comment by afc163** [comment]
You can't, `touched` state will only be affected by user interaction.

**Comment by rickvian** [comment]
@afc163 not really,

@mendoncanorma , according to this issue discussion, you can affect touched state by doing setFieldsValue
https://github.com/ant-design/ant-design/issues/33991
