### ISSUE TITLE
Antd autocomplete Backfill Issue

### ISSUE THREAD

**Issue by rsdineshbalaji** [ant-design/ant-design#26773]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/auto-complete/](https://ant.design/components/auto-complete/)

### Steps to reproduce
1. Just take any autocomplete example
2. Add backfill = true
3. Using keyboard if you scroll through suggestions, the selected value gets populated which is expected and as  per design

### What is expected?
when i mouseover the suggestion it should not get populated in textbox,  as in API it says backfill is supported for keys

### What is actually happening?
 But when i mouseover the suggestion it gets populated as well in textbox

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | MAC Book Pro |
| Browser | Chrome Version 85 |

**Comment by jaredleechn** [comment]
> as in API it says backfill is supported for keys

Do you mean that backfill should work only for keyboard events? @rsdineshbalaji

**Comment by rsdineshbalaji** [comment]
> > as in API it says backfill is supported for keys
> 
> Do you mean that backfill should work only for keyboard events? @rsdineshbalaji

Yes, it should work only on keyboard event

(API - If backfill selected item the input when using keyboard)

**Comment by rsdineshbalaji** [comment]
> > as in API it says backfill is supported for keys
> 
> Do you mean that backfill should work only for keyboard events? @rsdineshbalaji

@jaredleechn 

Yes, it should work only on keyboard event

(API - If backfill selected item the input when using keyboard)
