### ISSUE TITLE
form.getFieldsValue returns a result of type "any" instead of the generic type passed to the form

### ISSUE THREAD

**Issue by icaroponce** [ant-design/ant-design#26775]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigorous-pine-uhq9o)

### Steps to reproduce
Check the variable "values" type on line 19.

### What is expected?
the return of the function "getFieldsValue" should be typed according to the type "FormValues" passed into: Form.useForm<FormValues>()

### What is actually happening?
getFieldsValues returns a result of type "any"

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.12 |
| System | Archlinux 5.5.13-arch1-1 |
| Browser | Chromium Version 80.0.3987.149 |

---
First of all, thanks for the good job and the great TS addition here: https://github.com/ant-design/ant-design/pull/25937.
This solves a vary similar problem, typing the form values into "onFinish" but seems to not apply the same to the result of "getFieldsValue"

**Comment by devuxer** [comment]
@zombieJ , Is there a reason this fix only works for `getFieldsValue()`, and not `getFieldsValue(true)`, which still returns `any`? Can all overloads of this function return `Values`?

Can make a separate issue if you like.

**Comment by zombieJ** [comment]
@devuxer, `getFieldsValue(true)` returns all the data in store which can not same as generic type.

For example, set `initialValue: { name: 'abc', notUsed: 'cde' }` and `useForm<{ name: string }>()` with only `name` Form.Item`. `getFieldsValue()` will get `{ name: 'abc' }` but `getFieldsValue(true)` returns `{ name: 'abc', notUsed: 'cde' }`.

**Comment by devuxer** [comment]
@zombieJ , What I'm looking for is a type-safe way to access the properties on first render. If I use `getFieldsValue()` on first render, it returns an empty object. If I use `getFieldsValue(true)`, it returns the correct object but it is typed `any`. My TSConfig has strict turned on, so if I change any getFieldsValue() to `getFieldsValue(true)`, it breaks my code.

Maybe there needs to be a new overload that works like `getFieldsValue()` except that it mounts values even on first render?

At the moment, I had to write this to workaround the problem:

```ts
export type TypeSafeFormInstance<TFormModel> = Omit<FormInstance<TFormModel>, "getFieldsValue"> & {
    getFieldsValue: (() => TFormModel) &
        ((
            nameList: Array<string | number | Array<string | number>> | true,
            filterFunc?: (meta: Meta) => boolean,
        ) => TFormModel);
};
```

I then replaced all instances of `FormInstance` w/ `TypeSafeFormInstance`. Would be nice not to have to go to all this trouble.

**Comment by devuxer** [comment]
@zombieJ Do you recommend I create a separate issue for this or do you think it cannot be solved?

**Comment by zombieJ** [comment]
As described above, `getFieldsValue()` will return form generic values type but `getFieldsValue(true)` or `getFieldsValue(namePath)` will not confirm what the value type accuracy is. If you strongly confirm the values type is Form generic, it should be without `true` to force get all data in store.

**Comment by devuxer** [comment]
@zombieJ,

I understand your explanation, but as I tried to explain in https://github.com/ant-design/ant-design/issues/26775#issuecomment-1099893553, `getFieldsValue()` does not work on first render, so I have to use unsafe `getFieldsValue(true)`.

Why can't I have type-safe *and* works on first render? Why do I have to choose one or the other?
