### ISSUE TITLE
labelCol on form does not affect nested form items

### ISSUE THREAD

**Issue by steenole** [ant-design/ant-design#26770]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/steenole/pen/xxVJaZe](https://codepen.io/steenole/pen/xxVJaZe)

### Steps to reproduce
Run the codepen. Look at the rendered form.

### What is expected?
All labels should span 3 columns, since it is defined on the form (labelCol={{span: 3}})

### What is actually happening?
The first 3 fields are correct, but the next 3, which are nested, are not affected by the labelCol setting

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Edge  85.0.564.51 |

**Comment by zombieJ** [comment]
Thanks for feedback. Nest col do not accept by Form is by design. Let me update document about this.
