### ISSUE TITLE
Compile error - Can't resolve @babel/runtime/helpers/esm/createSuper

### ISSUE THREAD

**Issue by yas24** [ant-design/ant-design#26777]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/input-validator-hooks-forked-f7bly?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
Upgrading to antd version 4.6.0 or higher seems to prompt this error when using it with react. No matter what version of react I'm using, all I need to do is import any component and the project breaks.

### What is expected?
Proper import of any antd component.

### What is actually happening?
Getting a runtime error,
```
Could not find module in path: '@babel/runtime/helpers/objectSpread2' relative to '/node_modules/rc-tooltip/node_modules/rc-trigger/lib/index.js'

````

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.0 |
| System | Mac OS |
| Browser | Chrome |

**Comment by poyiding** [comment]
我在升级antd过程中也遇到这个问题，发现直到升级antd 4.5.4是正常的，到4.6.0就报这个错误，看了https://github.com/ant-design/ant-design/issues/26718这个issue推测4.6.0是否antd底层的相关依赖更新导致。现在不能升级到最新版本antd，需要等https://github.com/webpack/webpack/issues/11467 修复后才彻底解决问题，这个issue是不是不应该关闭。。

**Comment by poyiding** [comment]
是babel的bug, 如果是项目中升级遇到这个问题，可以自己项目中安装 @babel/runtime  解决
