### ISSUE TITLE
使用umi修改theme中的@font-size-base属性，form的label字体大小不受影响，别的都生效了

### ISSUE THREAD

**Issue by Monologue95** [ant-design/ant-design#26789]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://192.168.200.204:8093/user/login](http://192.168.200.204:8093/user/login)

### Steps to reproduce
http://192.168.200.204:8093/user/login

### What is expected?
能够使属性针对于form的label生效

### What is actually happening?
能够使属性针对于form的label生效

| Environment | Info |
|---|---|
| antd | 4.4.0 |
| React | 16.12.0 |
| System | window10 |
| Browser | chorme85.0.4183.102 |

**Comment by Da-Sheng** [comment]
我在将antd3升到4的情况下也碰到了同样的问题，公司业务时间原因先用样式覆盖处理了，后面看看如何更好的修复

**Comment by FateTestrossa** [comment]
> 我在将antd3升到4的情况下也碰到了同样的问题，公司业务时间原因先用样式覆盖处理了，后面看看如何更好的修复

我也是3升4遇到了这个问题，请问您现在解决了吗

**Comment by FateTestrossa** [comment]
我也是3升4遇到了这个问题，请问您现在解决了吗
