### ISSUE TITLE
button类型声明文件中buttonTypes缺失

### ISSUE THREAD

**Issue by Lighting-Jack** [ant-design/ant-design#26787]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-rcduu?file=/index.js)

### Steps to reproduce
<Button
  type="danger"
>
  删除
</Button>

### What is expected?
declare const ButtonTypes: ["default", "primary", "ghost", "dashed", "link", "text", "danger"];

### What is actually happening?
declare const ButtonTypes: ["default", "primary", "ghost", "dashed", "link", "text"];

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.8.4 |
| System | any |
| Browser | any |

**Comment by afc163** [comment]
` type="danger"` is deparecated, please use `danger` prop instead.

**Comment by Lighting-Jack** [comment]
> ` type="danger"` is deparecated, please use `danger` prop instead.

好的，文档也组件麻烦更新一下吧～文档上还是显示buttonType的tuple包含了danger

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/commit/90cfb0d25f61538d714b99c925add14358c36f2d
