### ISSUE TITLE
Tabs 使用 Affix 制作吸顶效果，TabBar 样式丢失

### ISSUE THREAD

**Issue by Michaelooo** [ant-design/ant-design#26783]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-e2o1n?file=/index.js)

### Steps to reproduce
如下代码所示，我想要实现一个 Tab 的吸顶效果，如果使用 renderTabBar 来自定义 bar ，当用 Affix  包裹住 renderTabBar  的返回子组件，那么tabBar 的样式就会丢失。

```
// 详细可参考重现链接
renderTabBar={(prop, DefaultBar, style) => (
<Affix offsetTop={50}>
    <DefaultBar {...prop} style={{ ...style, backgroundColor: '#fefefe' }} />
</Affix> )}
```

另外，我测试了过去的几个版本， antd@4.2.0 是正常的，之后的都有此异常。

### What is expected?
使用最新版本，tabBar 样式保留

### What is actually happening?
tabBar 的样式丢失

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | macos 10.15.6 |
| Browser | chrome 85.0.4183.83 |

---
尝试使用官方文档推荐的 react-sticky ，发现官方 Demo 已经跑不通。

**Comment by afc163** [comment]
> 尝试使用官方文档推荐的 react-sticky ，发现官方 Demo 已经跑不通。

可以看 https://codesandbox.io/s/romantic-sky-r4wm9

**Comment by zombieJ** [comment]
嗯，Tabs 样式对层级有依赖，`renderTabBar` 不支持嵌套 Affix。

**Comment by cuijiudai** [comment]
> > 尝试使用官方文档推荐的 react-sticky ，发现官方 Demo 已经跑不通。
> 
> 可以看 https://codesandbox.io/s/romantic-sky-r4wm9

例子也不好用了，报错了


> Could not find module in path: 'rc-util/5.2.1/lib/Dom/dynamicCSS' relative to '/node_modules/@ant-design/icons/lib/utils.js'
