### ISSUE TITLE
在 IE11 下 DatePicker 组件高度与 Select 组件高度不一致

### ISSUE THREAD

**Issue by 0xAC7** [ant-design/ant-design#26788]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/date-picker-cn/#components-date-picker-demo-switchable](https://ant-design.gitee.io/components/date-picker-cn/#components-date-picker-demo-switchable)

### Steps to reproduce
在 IE11 浏览器下，打开上面 ant-design 组件库示例 demo，该 demo 由一个 Select 组件和 DatePicker 组件组成，可以看到这两者高度不一致。

### What is expected?
在 IE11 浏览器下，所有表单类型组件的高度基本一致（除了非输入框类型的表单组件外）

### What is actually happening?
在 IE11 浏览器下，DatePicker 组件高度与 Select 组件高度不一致

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.9.21 |
| System | Windows |
| Browser | IE11 |

**Comment by 0xAC7** [comment]
该问题可能与 https://github.com/ant-design/ant-design/pull/24673  是同类型问题，这个链接是修复了 Input 组件在 IE11 下的高度问题

**Comment by zombieJ** [comment]
Close since no more feedback.
