### ISSUE TITLE
<Select combobox></Select>的内容如何实现清空？

### ISSUE THREAD

**Issue by TopviewIter** [ant-design/ant-design#2678]
`<Select combobox></Select>`的内容如何实现清空？如果通过getFieldProps的方式来进行绑定，那么就会破坏掉它原来的效果。
`<Select combobox style={{ width: 160 }} onSelect={this.handleOnSelect} onChange={this.handleSelectChange} 
                    filterOption={false} placeholder="...." optionLabelProp="children">
                    {this.state.options}
</Select>`

#### 本地环境

- antd 版本:1.8
- 操作系统及其版本：win7
- 浏览器及其版本:

#### 你期待的结果是：
可以实现内容清空

**Comment by TopviewIter** [comment]
修改显示。

**Comment by afc163** [comment]
1. 建议用 getFieldProps，具体看 Form 的例子。
2. 受控模式控制 Select 的展示。

```jsx
reset() {
  this.setState({
    value: undefined,
  });
}

onChange(value) {
  this.setState({
    value,
  });
}

...

<Select value={this.state.value} onChange={this.onChange}>
   ...
</Select>

...

<Button onClick={this.reset}>重置</Button>
```

**Comment by afc163** [comment]
https://facebook.github.io/react/docs/forms.html#controlled-components

**Comment by TopviewIter** [comment]
但上面的例子并不适用于`<Select combobox></Select>`这个组件啊，我要实现智能提示的功能。

**Comment by TopviewIter** [comment]
http://ant.design/components/select/，你上面的例子用户无法输入了。

**Comment by afc163** [comment]
http://codepen.io/anon/pen/AXYKvN?editors=001

没试过，不要信口开河啊

**Comment by TopviewIter** [comment]
这种方式 我之前试过了，但它会覆盖optionLabelProp="children"的效果。

**Comment by peakandyuri** [comment]
表示setState传undefined进去清不掉select的值

**Comment by wangcongyi** [comment]
@afc163  在 antd v3.6.2 中， Select 组件已经不能接受 value 这个 props 了？

**Comment by gentlelynn** [comment]
如果是表单的话，可尝试使用setFieldsValue
