### ISSUE TITLE
RangePicker 设置showTime  4.x的选择方式如何回到3.x的那种选择方式，选时分秒的放下面，需要再点开选时分秒呢？

### ISSUE THREAD

**Issue by kevinzl** [ant-design/ant-design#26798]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
无

### What does the proposed API look like?
有什么配置可以设置UI的显示方式

4.x 
![image](https://user-images.githubusercontent.com/6283852/93458841-702e5180-f913-11ea-95c1-0891ccf99728.png)

3.x
![image](https://user-images.githubusercontent.com/6283852/93458901-83412180-f913-11ea-91d4-4bbd34955b15.png)

**Comment by Kermit-Xuan** [comment]
目前没有方法回到之前 UI 样式，4.x 就是这样设计的。

**Comment by imakan** [comment]
遇到同样的痛点了

**Comment by LaEmma** [comment]
遇到同样的痛点 +1 
用户操作多了一步，感觉很不方便

**Comment by ginnko** [comment]
遇到同样的痛点 +2  希望能增加3.x的那种选择方式

**Comment by zhangqiongyue** [comment]
遇到同样的痛点 +3   强烈希望能增加3.x的那种选择方式
