### ISSUE TITLE
Select 通过 tab focus 后直接进行中文输入会忽略第一个字符

### ISSUE THREAD

**Issue by 0xAC7** [ant-design/ant-design#26790]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/dreamy-sinoussi-sj5yd)

### Steps to reproduce
1. 打开重现链接；
2. 先用鼠标正常点击第一个 Select，激活 Select 组件的下拉列表；
3. 通过 Tab 按键切换聚焦到第二个 Select，此时第二个 Select 显示聚焦的边框，但是下拉列表并不会出现，这种情况下可以直接进行中文输入，但是会省略掉第一个字符。

### What is expected?
能够进行正常的中文输入

### What is actually happening?
省略掉了第一个字符，导致输入中文不对，如下图
![image](https://user-images.githubusercontent.com/40794447/93439177-d1005e80-f900-11ea-97a7-f428d0954e18.png)

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.9.21 |
| System | Windows |
| Browser | Chrome |

**Comment by afc163** [comment]
原来还可以这么操作。

**Comment by 0xAC7** [comment]
> 原来还可以这么操作。

我们测试发现的，问题不大。
但我想有一批用户可能会习惯使用 tab 页快速进行输入切换，这样在填充表单时比较快捷。
所以所有的表单类型组件（带输入框的组件？）都要支持 tab 切换输入？
