### ISSUE TITLE
table组件中能否支持启用多选功能但是隐藏选择列

### ISSUE THREAD

**Issue by luzhiy123** [ant-design/ant-design#26797]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我这边封装了点击行选中，需要封装用户自定义列的顺序和是否显示，但是选择列始终在前，不能自定义移动到其他位置，也不能隐藏。
如果是官方支持，在底层就能实现不渲染dom，如果我这边封装，那么已有的丰富的选择功能就不能用，需要自己重写，希望官方支持隐藏功能

### What does the proposed API look like?
rowSelection {
     hideSelectionColumn: boolean
}

**Comment by afc163** [comment]
Duplicate of #19335

**Comment by luzhiy123** [comment]
那个回答没有有效解决，带来来列表宽度设置错位问题
https://codesandbox.io/s/polished-fast-7s6b0?file=/index.js

**Comment by afc163** [comment]
可以试试 https://codesandbox.io/s/unruffled-tharp-jfyej?file=/index.css

**Comment by afc163** [comment]
或者 https://github.com/ant-design/ant-design/issues/19335#issuecomment-547623336

**Comment by luzhiy123** [comment]
恩，可以了，非常感谢
