### ISSUE TITLE
Transfer target  TotalCount change to 0 when dataSource change

### ISSUE THREAD

**Issue by neostfox** [ant-design/ant-design#26793]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ancient-firefly-fk9p3)

### Steps to reproduce
click pagination to another page

### What is expected?
target count equal target count

### What is actually happening?
0

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.9 |
| System | window 10 |
| Browser | edge 85 |

**Comment by zombieJ** [comment]
You should keep the data with Transfer instead of dynamic update it.
