### ISSUE TITLE
for the FormItem name='RegisterPartForm[username]' doesn't seem to work as expected

### ISSUE THREAD

**Issue by ggepenyan** [ant-design/ant-design#26799]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigorous-almeida-9td5o?file=/src/App.js)

### Steps to reproduce
Just add FormItem name as name='RegisterPartForm[username]', submit the form to get the values object.

### What is expected?
In onFinish function username should appear inside RegisterPartForm object in the values object like this - {RegisterPartForm: {username: "value"}}

### What is actually happening?
In onFinish function the values object appears like this - {RegisterPartForm[username]: "value"}

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Google chrome latest version |

---
It's a strange thing and it was working as expected in the third version

**Comment by afc163** [comment]
https://codesandbox.io/s/awesome-shadow-r2b7t?file=/src/App.js

**Comment by afc163** [comment]
https://ant.design/docs/react/migration-v4#Component-refactoring

**Comment by ggepenyan** [comment]
@afc163 Thanks for the reply. Is there any way to get the same result but have the input itself appeared with name='RegisterPartForm[username]' in the form? I know it wasn't mentioned in the issue but would be nice to know is there a way for that.

**Comment by ggepenyan** [comment]
And one more thing is that this sentence - "Nest fields definition changes from 'xxx.yyy' to ['xxx', 'yyy']." I think needs to appear under [this link](https://ant.design/components/form/v3/) (form migration docs) also.

**Comment by afc163** [comment]
PR is welcome~

**Comment by ggepenyan** [comment]
@afc163 Is there any way to get the same result but have the input itself appeared with name='RegisterPartForm[username]' in the DOM?
