### ISSUE TITLE
Select组件显示问题：从props 读取Select的选项数据 循环的时候显示只显示部分，鼠标滚动一下才显示全部选择项

### ISSUE THREAD

**Issue by kevinzl** [ant-design/ant-design#26795]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http:/www.404.com](http:/www.404.com)

### Steps to reproduce
从props 读取Select的选项数据 循环的时候显示只显示部分，鼠标滚动一下才显示全部选择项

### What is expected?
修复

### What is actually happening?
修复

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | react |
| System | antd-pro4 |
| Browser | Chrome |

![image](https://user-images.githubusercontent.com/6283852/93456390-36a81700-f910-11ea-892a-a09dd3fdf9b3.png)

![image](https://user-images.githubusercontent.com/6283852/93456463-4e7f9b00-f910-11ea-9382-aad780f9807b.png)

**Comment by Kermit-Xuan** [comment]
Duplicate of #26116 

记得已经修复了，可以去这个 issue 里面讨论。

**Comment by debuggerccai** [comment]
并没有修复，还是出现了

**Comment by Kermit-Xuan** [comment]
@zombieJ 帮忙看看

**Comment by zombieJ** [comment]
@kevinzl  @debuggerccai 给个重现看看

**Comment by bihongbin3027** [comment]
@kevinzl  打开你给的Reproduction link地址，是一个色情网站。。。

**Comment by Kermit-Xuan** [comment]
> @kevinzl 打开你给的Reproduction link地址，是一个色情网站。。。

他给的不是复现链接，就是个占位用的。

**Comment by kevinzl** [comment]
我就是随便搞了个xxx地址，不是复现链接，就是个占位用的，这都能访问也是醉了

**Comment by yoyo837** [comment]
> 我就是随便搞了个xxx地址，必填项用于表单提交用的，不是复现链接，就是个占位用的，这都能访问也是醉了

还是个很牛皮的3字符域名

**Comment by zombieJ** [comment]
@kevinzl ，给个重现看看哈~
