### ISSUE TITLE
3.0的列表表头和固定列添加后thead下的粘性布局失效

### ISSUE THREAD

**Issue by hyl1374961656** [ant-design/ant-design#26794]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
希望表头跟着浏览器的窗口固定，而不是列表

### What does the proposed API look like?
111

**Comment by afc163** [comment]
3.x 不维护了，请升级到 4.x。

**Comment by hyl1374961656** [comment]
4能实现么？我查看了下3的固定列是又开了一个thead，4的好像不是这样的

**Comment by hyl1374961656** [comment]
我在3里，关闭固定列和横向滚动可以实现position:sticky ; top: 0,打开任意一个都会导致失效
