### ISSUE TITLE
Table 中的Column显示二级内容

### ISSUE THREAD

**Issue by lanstonpeng** [ant-design/ant-design#268]
var columns = [
    {
      title:'用户',
      dataIndex:'user_data.user_name'
    }];

在指定dataIndex需要显示下发数据中的二级内容
如:
[
 {
  key1:"123",
  user_data : { user_name:"123"}
 }
]

**Comment by zhujun24** [comment]
`dataIndex:'user_data.user_name'` 这样写不对吧

**Comment by lanstonpeng** [comment]
@zhujun24 ,那应该如何写呢?如果要展示二级内容的话，看了table的源码，dataIndex里面的就直接作为一个string的key了

**Comment by zhujun24** [comment]
照 Demo 里那样写不行么？二级内容的 key 和 expandedRowRender 里的 key 保持一致就可以了

**Comment by lanstonpeng** [comment]
嗯嗯，这是一种方式，刚刚想到方法了，在render里面 return data.user_name 就好了，谢谢你的回答

On 11 September 2015 at 17:57, 低位 <notifications@github.com> wrote:

> 照 Demo 里那样写不行么？二级内容的 key 和 expandedRowRender 里的 key 保持一致就可以了
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ant-design/ant-design/issues/268#issuecomment-139504354>
> .
>



-- 
*luck is where preparation meets opportunity*

**Comment by afc163** [comment]
可以用 render ~
