### ISSUE TITLE
form中 field的值残留问题求助

### ISSUE THREAD

**Issue by HengCC** [ant-design/ant-design#26801]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://404.com](http://404.com)

### Steps to reproduce
1. 维护一个数组假设为array
2. 渲染form的时候根据上面的array 动态的渲染 <form.item>, 比如渲染了3个input. 并且为第一个input输入了值. 这时候通过onvaluechange能够捕捉到这个值.
3. 在动态渲染出来的form.item中删除了第一个input(通过删除array中的第一个元素来操作的). . 这时候通过onvaluechange依然能够捕捉到这个被移除的form.item的值

### What is expected?
form.item被移除后 对应field的值也需要被清理.

### What is actually happening?
field对应的值残留...

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome |

---
一个极其复杂的动态表单维护.... 字段变化完全由外部操作来控制. 无法通过form.list来控制

**Comment by Kermit-Xuan** [comment]
你给个 [demo](https://codesandbox.io/s/antd-reproduction-template-6e93z) 我看看是什么问题？

我猜可能是动态渲染时 form.item 没有绑定key的问题，这样可能会导致 form.item 无法正常卸载。

**Comment by yoyo837** [comment]
我好像知道他说的哪件事，比如之前有俩字段注册a,b, 后来交互新增一个c，然后又交互去掉了这个c，从form取值时这个c的痕迹还在。之前豆酱好像解释过，我觉得即使要改估计也没那么快那么容易落地。@zombieJ

**Comment by Kermit-Xuan** [comment]
这个目前已经实现了，form 里面新增了个 [preserve](https://ant.design/components/form-cn/#API) 属性来控制组件销毁后是否删除字段。

**Comment by yoyo837** [comment]
@HengCC 看看这是你要的效果吗？

**Comment by HengCC** [comment]
> 这个目前已经实现了，form 里面新增了个 [preserve](https://ant.design/components/form-cn/#API) 属性来控制组件销毁后是否删除字段。

这个属性我之前试过了.  加上后 field value中 只是清空了值. 但是对应的字段还在.  就是@yoyo837 说的意思. 痕迹始终在里面. 

另外加上这个属性后.  类似下图这样的
![image](https://user-images.githubusercontent.com/6167532/93491720-9f0ced80-f93c-11ea-89b4-37ad2435fc7f.png)
当我点击移除后. 他会把我这3个动态的item都移除.  我可以肯定的是这3个 item的key是不一样的.

**Comment by HengCC** [comment]
demo
`https://codesandbox.io/s/antd-reproduction-template-forked-ucol9`

**Comment by Kermit-Xuan** [comment]
确实如此。

@zombieJ 我看之前清理的时候只是将值设为了 `undefined`，并没有删除字段: https://github.com/react-component/field-form/blob/98a1235a0764fdd7cb009bb9e4c1cdbc03b3d835/src/useForm.ts#L504

看看能不能支持下，还有个问题是当卸载清理字段后需不需要触发一下 `onValueChange`？

**Comment by yoyo837** [comment]
清理字段不需要触发onValueChange

**Comment by zombieJ** [comment]
删除不用触发，触发条件是满足字段的 `tirgger`，但是 `allValues` 直接透出 store 的值的确是个 bug。

**Comment by zombieJ** [comment]
算是个 breaking change，放到 feature branch 里了

**Comment by yuanzhian** [comment]
目前我遇到这样的问题，不知道跟你的是不是一样的。

`getFieldDecorator` 的回掉函数参数，如果`Input`组件被包裹了一层 `Fragmemt` 或其它标签，这个时候 uuid 改成2，form 仍然会捕捉到 test.1 这个field。

```js
const { uuid = 1 } = this.state; // uuid 初始值为1
getFieldDecorator(`test.${uuid}`,{})(
  <Fragment>
     <Input />
 </Fragment>
)
```
