### ISSUE TITLE
[SHOWCASE] Sticky   Filtering crashes table header

### ISSUE THREAD

**Issue by luis-carlos-campos** [ant-design/ant-design#26802]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fant.design%2Fcomponents%2Ftable%2F](https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fant.design%2Fcomponents%2Ftable%2F)

### Steps to reproduce
1-) Open Filter and sorter - Ant Design Demo
https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fant.design%2Fcomponents%2Ftable%2F

2-) Replace filter value from Joe to Joe1
Before:
      {
        text: 'Joe',
        value: 'Joe',
      }
After
      {
        text: 'Joe',
        value: 'Joe1',
      }

3-) Set Table to sticky
<Table sticky columns={columns} dataSource={data} onChange={onChange} />

4-) Try to filter by Joe

5-) Table header crashes.

### What is expected?
It should display the header for all columns

### What is actually happening?
Only Name header is displayed

| Environment | Info |
|---|---|
| antd | undefined |
| React | react 16.x |
| System | MacOS Mojave |
| Browser | Chrome Version 85.0.4183.102 |

---
If you remove sticky table works as expected

**Comment by afc163** [comment]
Reproduce: https://codesandbox.io/s/nifty-star-0xgyh?file=/index.js

- Try to filter by Joe

#### Without `sticky` prop ✅

<img width="656" alt="image" src="https://user-images.githubusercontent.com/507615/93552307-c5fe0a80-f9a2-11ea-8fb4-e143818030f3.png">

#### With `sticky` prop ❌

<img width="651" alt="image" src="https://user-images.githubusercontent.com/507615/93552294-bd0d3900-f9a2-11ea-8e44-187de7c41400.png">

@luis-carlos-campos Am I describe this bug correctly?

**Comment by shaodahong** [comment]
I'm not reproducing in my locally, and i guess cause by `rc-table` old version, you can see this demo it's be correct

https://codesandbox.io/s/wizardly-shadow-o225n?file=/index.js

so you can upgrade `antd` version and if still have, please comment
