### ISSUE TITLE
Add addonBefore and addonAfter to InputNumber

### ISSUE THREAD

**Issue by avalanche1** [ant-design/ant-design#26805]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We could have a unified formatting for Inputs and InputNumbers.
I have a form where I use Inputs with `addonBefore` prop extensively. And if InputNumber happens to be around - it looks really out of the ordinary. In such cases I have to drop usage of InputNumber and use simple Input instead - not to break uniformal style of my form.

### What does the proposed API look like?
Add `addonBefore` and `addonAfter` props.

**Comment by afc163** [comment]
Duplicate of #14284

**Comment by avalanche1** [comment]
No. That's not a duplicate. 
They ask for adding `prefix` prop. I propose adding addonBefore and addonAfter props.

**Comment by jonybekov** [comment]
Hi. I also wanted this feature as well

**Comment by mileshobby** [comment]
Please could we get this 🙏

**Comment by peraltafederico** [comment]
Why is this closed @afc163?
