### ISSUE TITLE
onClick fired twice when clicked on checkbox title

### ISSUE THREAD

**Issue by z1ne2wo** [ant-design/ant-design#26814]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/z1ne2wo/pen/bGpxPjd?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fcheckbox%2F](https://codepen.io/z1ne2wo/pen/bGpxPjd?editable=true&editors=001%3Dhttps%3A%2F%2Fant.design%2Fcomponents%2Fcheckbox%2F)

### Steps to reproduce
Click on checkbox input (view the output in the console: onClick was fired once for checkbox wrapper)
Click on checkbox title (view output in the console: onClick was fired twice for checkbox wrapper)

### What is expected?
When clicked on checkbox title, onClick is expected to be fired once, just like when click on checkbox input

### What is actually happening?
When clicked on checkbox title, onClick was fired twice for checkbox wrapper

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | Ubuntu 18.04.4 LTS |
| Browser | Google Chrome 84.0.4147.105 (Official Build) (64-bit) |

**Comment by afc163** [comment]
We use label, so it will trigger click event twice, just like native elements: https://codepen.io/afc163-1472555193/pen/KKzxOgv?editors=0011

**Comment by z1ne2wo** [comment]
Thank you for the clarification!
