### ISSUE TITLE
多选Select组件，异步获取Option时，设置defaultValue参数问题

### ISSUE THREAD

**Issue by zuiidea** [ant-design/ant-design#2681]
当Option为异步获取的变量时:

defaultValue 设置 option为key值，渲染出来显示的名称是key，而不是名称;

![image](https://cloud.githubusercontent.com/assets/16070518/17577603/48305038-5fb2-11e6-860d-2c362a7f9030.png)

defaultValue 设置 option为名称，渲染出来并未选中指定的option,且返回值为option的名称而不是key;

![image](https://cloud.githubusercontent.com/assets/16070518/17577576/056fe79a-5fb2-11e6-8ee4-46aeecead175.png)

**Comment by ddcat1115** [comment]
Option为异步获取，此时 defaultValue 已经设置过了，用 value 试试

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/1782
