### ISSUE TITLE
想了解一下 Menu 组件收起和展开时带有子菜单的菜单项和无子菜单的菜单项的动画效果为何不同？

### ISSUE THREAD

**Issue by aweiu** [ant-design/ant-design#26816]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed](https://ant.design/components/menu-cn/#components-menu-demo-inline-collapsed)

### Steps to reproduce
点击收起展开

### What is expected?
希望收起和展开时所有的菜单项走统一的动画。

### What is actually happening?
收起的时候包含子菜单的菜单项会直接消失，而无子菜单项的菜单项会有一个向左渐隐的过程。展开时候动效取反。

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.8.6 |
| System | mac os 10.14.1 |
| Browser | chrome 73.0.3683.103 |

---
如果是刻意为之，想知道这个交互动效是想要表达什么？包含子菜单项的右侧剪头已经足够表达其可以被二次折叠展开了，这里的区别动画貌似有些多余，反而造成动效不统一，也不太符合：https://ant.design/docs/spec/motion-cn#%E5%85%8B%E5%88%B6 这里的克制原则。

**Comment by afc163** [comment]
实现问题，submenu 的收起效果由于 dom 结构问题目前没找到办法和 menu item 保持一致。

**Comment by afc163** [comment]
有没有兴趣啃一下这个硬骨头？@aweiu

**Comment by aweiu** [comment]
@afc163  其实我的项目是基于 AntPro 的，那个菜单收起时候是整个直接消失，然后展开时候突然出现。所以 menu item 的动效就显得更迷了。。。
有个简单的建议是 AntPro 不如干脆直接把 menu item 的动效给取消掉。要有一起有，要无一起无！大家一起突然出现，突然消失，目前我本地的项目就决定这么搞了。
至于 Antd 的，有时间我可以来啃一下。不过得确定一下最终是希望以 submenu 还是 menu item 的动效为准，如果以 menu item 的，可能需要同时让 submenu 的箭头渐隐（或小距离左移渐隐），不然带着箭头整体左移会比较奇怪

**Comment by afc163** [comment]
最佳方案是以 Menu.Item 为准，这个动效是设计师精心设计的。

**Comment by jljsj33** [comment]
@afc163 这个已经不是我最初设计的样式了，，被你们搞坏了。。他说的是收缩时，有的没动画有的有动画，，，我当初整的时候可不是这样的，老铁。。。我也管不了了。。哈哈，，，，你有心思你调整下吧。。

**Comment by jljsj33** [comment]
https://2x.ant.design/components/menu/#components-menu-demo-inline-collapsed

2.x 还是好的，，3.x 开始就挂了，，无解，，
