### ISSUE TITLE
Collapse does not support subset of Panels to be inside of a React Fragment

### ISSUE THREAD

**Issue by severi** [ant-design/ant-design#26819]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pastebin.com/TBwqfbR8](https://pastebin.com/TBwqfbR8)

### Steps to reproduce
add subset of panels in a collapse to a react.fragment

### What is expected?
panels should be clickable / expandable

### What is actually happening?
panel cannot be expanded

| Environment | Info |
|---|---|
| antd | 4.6.3 |
| React | 16.13.1 |
| System | OSX |
| Browser | Chrome 85.0.4183.102 |

**Comment by wrongsahil** [comment]
https://stackblitz.com/edit/react-gk3ukz?file=demo.tsx

This is still not working. Any workaround for this?
