### ISSUE TITLE
Table row getting expanded on button click 

### ISSUE THREAD

**Issue by brain-eater** [ant-design/ant-design#26821]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mn8qu?file=/index.js)

### Steps to reproduce
Click on button of last row

### What is expected?
Row not getting expanded

### What is actually happening?
Row getting expanded

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | Chrome latest |

**Comment by HeitorBRaymundo** [comment]
@brain-eater you should remove the `expandRowByClick: true` property. 
It makes the whole row clickable to open the expanded row.

**Comment by brain-eater** [comment]
`onClick={(e) => e.stopPropagation()}` works. That's exactly what I needed.

@HeitorBRaymundo Thanks for the quick help.

**Comment by brain-eater** [comment]
We have multiple links and buttons in our table. and setting onClick={(e) => `e.stopPropagation()}` to each of them is kind of ugly.

Is there any way that we can say to only expand if click on a row at the table level?

I think that's possible to do this by checking the event target just before expanding. Is there any feature like this in Antd table. 
something like `shouldExpand(record, event) => boolean` will help
