### ISSUE TITLE
RangePicker组件,当picker=week，选中的开始周，点击之后没有高亮效果

### ISSUE THREAD

**Issue by wangpenghui522** [ant-design/ant-design#26823]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
目前选择了开始周之后，没有高亮效果，不知道选中周有没有生效，与picker=‘date’,picker='month'时的日期范围选择交互效果不一致

### What does the proposed API look like?
RangePicker组件,当picker=week时，期望选择了开始周，开始周高亮，然后再次打开周范围选择组件时，开始周和结束周都高亮，目前再次打开时，只有开始周高亮

**Comment by bihongbin3027** [comment]
提供一个在线的例子..

**Comment by wangpenghui522** [comment]
官方官网就可以看到我说的问题 https://ant.design/components/date-picker-cn/#header      第一个代码演示右侧的跨周选择，我选择开始周之后，开始周在日历面板上不高亮，选完结束周，第二次打开日历面板，开始周高亮，结束周不高亮

**Comment by XiaoJiuDYS** [comment]
https://codesandbox.io/s/3vk4m

![image](https://user-images.githubusercontent.com/36301924/93837014-3369ae00-fcb7-11ea-91c4-9f3744298578.png)

图上是在选结束日期，可以看到开始周未高亮

**Comment by zombieJ** [comment]
设计如此，因为日期范围拉高亮特备臃肿……
