### ISSUE TITLE
onBlur not working on Input.Password

### ISSUE THREAD

**Issue by luizlahr** [ant-design/ant-design#26829]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input/](https://ant.design/components/input/)

### Steps to reproduce
set onBlur to the Password, focus the field, remove focus and nothing happens

### What is expected?
the function to be called

### What is actually happening?
nothing

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | react.js 16.13.1 |
| System | ? |
| Browser | chrome |

**Comment by afc163** [comment]
It works: https://codesandbox.io/s/musing-ganguly-9ehj1?file=/index.js
