### ISSUE TITLE
form表单对传入的对象不能调用 二级对象

### ISSUE THREAD

**Issue by lxkun** [ant-design/ant-design#26822]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
form表单对于传入的数据应该都能拿到。

### What does the proposed API look like?
let o = {
   config: {
      username: "admin"
   }
}

       <Form.Item
          name="config.username"
          <Input />
        </Form.Item>

**Comment by zzfn** [comment]
你应该要写成
```javascript
   <Form.Item
      name={["config","username"]}
      <Input />
    </Form.Item>
```
