### ISSUE TITLE
使用Form.List报了一个关于key的警告

### ISSUE THREAD

**Issue by LiHaoGit** [ant-design/ant-design#26834]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/unruffled-kirch-9r7ne?file=/index.js)

### Steps to reproduce
点击Add field按钮

### What is expected?
不应该报错

### What is actually happening?
控制台报警告 Warning: Encountered two children with the same key, `0`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 85.0.4183.102 |

**Comment by LiHaoGit** [comment]
官方文档使用`Space`组件包裹了Form.List中的组件不会报这个问题，如果用div来包裹就会报这个警告   
官方示例：
```
....
{fields.map((field) => (
      <Space
                  key={field.key}
                  style={{ display: "flex", marginBottom: 8 }}
                  align="start"
                >
....
```
把Space组件换成div，控制台有关于key警告
```
....
{fields.map((field) => (
      <div
                  key={field.key}
                  style={{ display: "flex", marginBottom: 8 }}
                  align="start"
                >
....
```

**Comment by afc163** [comment]
You should remove duplicated key from Form.Item: https://codesandbox.io/s/boring-gareth-yc4bg?file=/index.js

**Comment by HualiangLI** [comment]
@afc163 
Have you considered remove `{...field}` from `Form.Item` in the demo codes of dynamic sections?
I reckon this will cause some misunderstandings, like rendering warnings in this issue, for some starters.

**Comment by wenlittleoil** [comment]
> You should remove duplicated key prop from Form.Item: https://codesandbox.io/s/boring-gareth-yc4bg?file=/index.js

Thanks a lot, it works for me.

**Comment by liucys** [comment]
解决方式：去除{...field}，使用fieldKey={[field.key, "first"]}的方式在Form.Item上进行声明
```tsx
<Form.List name="annual_input">
  {(fields, { add, remove }) => (
    <div>
      {fields.map((field) => (
        <div key={`annual_input${field.key}`} className="form_list_r1">
          <div className={styles.form_list_r2}>
            <Form.Item
              label=""
              name={[field.name, "year"]}
              fieldKey={[field.key, "year"]}
              rules={[{ required: false, message: "请选择年度" }]}
            >
              <DatePicker
                placeholder="请选择年度"
                picker="year"
                style={{ width: "100%" }}
              />
            </Form.Item>
            <Form.Item
              label=""
              name={[field.name, "input"]}
              fieldKey={[field.key, "input"]}
              rules={[{ required: false, message: "请填写此年度投入详情" }]}
            >
              <Input placeholder="请填写此年度投入详情" />
            </Form.Item>
          </div>
          <span className="form_list_r1remove">
            <MinusCircleOutlined
              onClick={() => remove(field.name)}
              style={{ margin: "8px" }}
            />
          </span>
        </div>
      ))}
      <Form.Item>
        <Button
          type="dashed"
          onClick={() => add()}
          block
          icon={<PlusOutlined />}
        >
          添加年度投入
        </Button>
      </Form.Item>
    </div>
  )}
</Form.List>;

````
