### ISSUE TITLE
有没有第三方API拿到Icon组件库的所有图标数据

### ISSUE THREAD

**Issue by Jidahan** [ant-design/ant-design#26837]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以和项目在线关联，用户可以自定义图标

### What does the proposed API look like?
```javascript
[
  {
     name: '<PieChartOutlined />',
    //图标的一些数据
    .....
  }
]
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/25559#issuecomment-656571636
