### ISSUE TITLE
Modal.confirm 等处理promise的方式不太符合直觉

### ISSUE THREAD

**Issue by zjuasmn** [ant-design/ant-design#2684]
#### 本地环境

- antd 版本: 1.8.0
- 操作系统及其版本：Mac OS X
- 浏览器及其版本: Chrome

#### 你做了什么？

使用Modal.confirm 的onOk处理异步操作，多次点击确定

#### 你期待的结果是：

onOk 的promise返回前， 确认按键应loading状态，避免用户多次点击确定

#### 实际上的结果：

onOk没有设置loading状态，多次点击有效，产生大量如下错误
Uncaught (in promise) TypeError: Cannot read property 'removeChild' of null(…)

#### 可重现的在线演示

http://ant.design/components/modal/#components-modal-demo-async

**Comment by benjycui** [comment]
很有道理的样子。

**Comment by zjuasmn** [comment]
还有个地方，Modal默认绑定了esc作为关闭的快捷键，但是Modal.XXX都没有绑定esc

**Comment by benjycui** [comment]
> 还有个地方，Modal默认绑定了esc作为关闭的快捷键，但是Modal.XXX都没有绑定esc

Modal 在 esc 或者点击遮罩时，会触发 `onCancel` 事件，但 Modal.xx 不一定有 `onCancel` 事件，而且 Modal.xx 的 `onCancel` 还支持异步返回，感觉不容易增加 esc 的支持。

然后 Modal.xx 应该是作为 `alert` 的替代，与 `alert` 的行为一致即可。

**Comment by djyde** [comment]
这个改变什么时候发版本呢?
