### ISSUE TITLE
Title source map styles overriding custom styles

### ISSUE THREAD

**Issue by peterwiebe** [ant-design/ant-design#26847]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-title-styles-bug-wg2le)

### Steps to reproduce
Import Typography.Title component, set a style via className prop (ie. titleStyle) and create a css class named titleStyle with the following rule: color: red;

### What is expected?
The Title to be the colour red.

### What is actually happening?
The colour is determined by the h1.typography class rule instead of the custom class rule from titleStyle. 

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | macos 10.15.2 |
| Browser | Google Chrome 85.0.4183.83  |

---
It looks like the sourcemap is taking precedence over the custom class.

**Comment by peterwiebe** [comment]
In chatting with @coreyward about this, the css specificity rules are the reason why this is happening. I guess I bring this up as a question about the implementation detail of `<Title/>`. I can change the ```color``` of a `<Button />` but not `<Title/>` as can be seen here: 

[https://codesandbox.io/s/antd-classname-implementation-comparison-0qfgz](https://codesandbox.io/s/antd-classname-implementation-comparison-0qfgz)

is there a reason for this?

[SO question](https://stackoverflow.com/questions/63974728/emotion-style-overruled-by-antd-default-style)

**Comment by zombieJ** [comment]
antd use different color with Title & Paragraph which set style by `[element].ant-typography`. You can raise priority like `h1.my-className` or `.ant-typography` to override it:
https://codesandbox.io/s/antd-title-styles-bug-forked-zqv3t?file=/src/App.js:175-177
