### ISSUE TITLE
getPopupContainer of ConfigProvider not works on Modal.confirm 

### ISSUE THREAD

**Issue by gostfather** [ant-design/ant-design#26843]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ye03x?file=/index.js)

### Steps to reproduce
使用modal.confirm(),

### What is expected?
弹窗渲染在正确的container下

### What is actually happening?
弹窗渲染在body下

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.12.0 |
| System | mac os |
| Browser | chrome 85 |

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#ConfigProvider-%E8%AE%BE%E7%BD%AE-prefixCls-%E5%90%8E%EF%BC%8Cmessage/notification/Modal.confirm-%E7%94%9F%E6%88%90%E7%9A%84%E8%8A%82%E7%82%B9%E6%A0%B7%E5%BC%8F%E4%B8%A2%E5%A4%B1%E4%BA%86%EF%BC%9F
