### ISSUE TITLE
Unable to set border color on divider component when it has text

### ISSUE THREAD

**Issue by adamistheanswer** [ant-design/ant-design#26846]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/angry-nobel-dsjs2)

### Steps to reproduce
Add text to divider component... Try and change colour of divider through style prop with border color... no color change

`<Divider style={{ borderColor: "#7cb305" }}>hello</Divider>
`
### What is expected?
color change of divider 

### What is actually happening?
Divider colour still grey when has text

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | react |
| System | mac |
| Browser | chrome |

**Comment by brzuck** [comment]
I'm having a problem with version 4.6.6.

The whole divider now (text and border) is using the color's property.
It is not respecting the color set with @divider-color
