### ISSUE TITLE
Typography.Paragraph 的 editable 可否支持取消修改，以及是否多行显示，同时和 Descriptions 一起使用会有样式抖动问题

### ISSUE THREAD

**Issue by Overcase** [ant-design/ant-design#26857]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

Can it increase customize multi-line display, Custom input can be cancelled, And can it be solved when used with the Descriptions component, The style jitter problem caused by the different heights of the display and input states, The actual effect you want to achieve is as follows

能否增加自定义多行显示，自定义输入可取消，以及能否解决与 Descriptions 组件一同使用时，因展示和输入状态的高度不同，导致的样式抖动问题，实际想达到的效果如下图

![image](https://user-images.githubusercontent.com/32009993/93863276-e822c000-fcf5-11ea-8871-97480464e0e9.png)

### What does the proposed API look like?
```javascript
{
  icon: ReactNode,
  tooltip: boolean | ReactNode,
  editing: boolean,
  // 是否多行显示
  // Whether to display in multiple lines
  textarea：booelan,
  // 是否支持取消操作
  // Whether to support cancel operation
  canCancel: boolean,
  maxLength: number,
  autoSize: boolean | { minRows: number, maxRows: number },
  onStart: function,
  onChange: function(string),
}


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by zkwolf** [comment]
取消操作大概是现在编辑状态下按ESC的效果？多行显示指的是？

**Comment by zombieJ** [comment]
Typography 的 `editable` 是轻量级编辑组件，取消通过 ESC 控制。不会拓展多行能力，因为 Paragraph 本身是一段。如果需要多行支持，请自行封装 TextArea。

**Comment by Overcase** [comment]
> 取消操作大概是现在编辑状态下按ESC的效果？多行显示指的是？

可以关注下下面的例子，与 Descriptions 一起使用会有样式问题，多行指的是输入时显示的多行文本框，而非支持多行功能！是否可以支持输入时使用一行的文档框
[CodeSandBox](https://codesandbox.io/s/interesting-rosalind-cvzxf?fontsize=14&hidenavigation=1&theme=dark)
