### ISSUE TITLE
RangerPicker provides parameters for switching the calendar panel

### ISSUE THREAD

**Issue by XiaoJiuDYS** [ant-design/ant-design#26853]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Take date as an example: Start date selection panel at the lower right corner (or end Date selection panel at the upper left corner), the calendar panel will not switch, you need to manually switch.Hopefully, the calendar panel can be switched automatically in this case.

-----------

以日期为例：
起始日期选择面板右下角（或者结束日期选择面板左上角日期），日历面板不会切换，需要手动切换。希望在这种情况下可以自动切换日历面板。

### What does the proposed API look like?
Provide a manual method to switch to the previous panel or the next panel (or it has been automatically implemented internally, only a Boolean variable needs to be configured).

---------

提供一个手动的切换到上个面板或者下个面板的方法（或者内部已自动实现，只需要配置一个布尔变量表明是否要开启此功能即可）。

**Comment by zombieJ** [comment]
没看懂，你能来个截图吗？

**Comment by XiaoJiuDYS** [comment]
https://codesandbox.io/s/6zhmi

###  The current month is September, and the start date is October 31st. I hope to switch to the October-November calendar after selecting
当前为9月，开始日期选中10月31日，希望选完可以切换到 10月-11月的日历

###  Current results:：Still stuck in the September-October calendar，Need to manually turn to November
目前的效果：仍旧停留在9月-10月的日历，需要手动翻到11月

![image](https://user-images.githubusercontent.com/36301924/94023695-192fed00-fde9-11ea-8712-a9fbf1948a9b.png)

### Expected result：Can automatically turn to November
期望的结果: 可以自动翻到11月
![image](https://user-images.githubusercontent.com/36301924/94023400-bfc7be00-fde8-11ea-81e3-610a29d81288.png)

### The current version in this example can be switched automatically if the data after October 31 is selected.
当前版本在这个例子中，可以自动切换的情况是选中10月31号之后的数据。

**Comment by zombieJ** [comment]
Make sense

**Comment by zombieJ** [comment]
![Kapture 2020-09-23 at 22 57 45](https://user-images.githubusercontent.com/5378891/94030304-403ded00-fdf0-11ea-84dc-b43c800b7ae9.gif)

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
