### ISSUE TITLE
DirectoryTree onLoad is called without loaded node's children 

### ISSUE THREAD

**Issue by ChambreNoire** [ant-design/ant-design#26855]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-jggffe?file=index.js](https://stackblitz.com/edit/react-jggffe?file=index.js)

### Steps to reproduce
When clicking on a folder node, DirectoryTree calls onSelect. The node passed to this function has no children (as they have not been loaded yet). Once the loadData function has been called, onLoad() is called. One expects the node passed to onLoad to contain the freshly loaded child nodes but it doesn't.

### What is expected?
onLoad's 'info' parameter contains {event, node}. node should include the children that have just been loaded

### What is actually happening?
node does not contain the children

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | Windows10 |
| Browser | Chrome 85.0.4183.102 |

---
(I need to be able to click a folder, thus loading it asynchronously, and once loaded and expanded, to retrieve the selected node *and it's children*)

**Comment by zombieJ** [comment]
There  are 2 concept you missed:
* `onLoad` is trigger when `loadData` resolve. It do not care what you update the tree.
* `treeData` is immutable data. So it trigger with the treeNode at `loadData` time not updated node.

**Comment by ChambreNoire** [comment]
So there's no in-build way of doing what I need to do? I have to do something messy like this :
https://stackblitz.com/edit/react-jggffe?file=index.js

**Comment by zombieJ** [comment]
Yes. You can do like this or create a tree map for cache : )
