### ISSUE TITLE
Hide/disable Tooltip of Upload component

### ISSUE THREAD

**Issue by arif25169** [ant-design/ant-design#26859]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I am not sure whether this feature is already exist or not. If there is any I would appreciate to show me the way. The problem is I don't want to show the response (regardless error or not error) as tooltip of upload component .

**Comment by zombieJ** [comment]
Maybe we can add `response={false}` to hide it.

**Comment by zombieJ** [comment]
Currently you can hide UploadList and customize one to replace.

**Comment by arif25169** [comment]
Thanks , I explicitly added `status` to `success` and it's gone

**Comment by shivaniCha** [comment]
> Thanks , I explicitly added `status` to `success` and it's gone

How did you do that? Could you please share that code snippets here?

**Comment by M-Umais-Hassan** [comment]
You can use this in the Upload as a prop, "beforeUpload={() => false}", it hides the tooltip

**Comment by kartik-raj7** [comment]
> > Thanks , I explicitly added `status` to `success` and it's gone
> 
> How did you do that? Could you please share that code snippets here?

You can simply set beforeUpload to false

  <Upload
                    onChange={uploadMultimedia}
                    disabled={loading}
                    listType="picture"
                    beforeUpload={()=>{return false}}
                  >
                    <Button icon={<UploadOutlined />}>Upload</Button>
                  </Upload>
