### ISSUE TITLE
请问下form表单中包含select组件，并且组件设置combobox属性，表单验证问题请教

### ISSUE THREAD

**Issue by qiannianv** [ant-design/ant-design#2685]
#### 本地环境

- antd 版本:1.8.0
- 操作系统及其版本：
- 浏览器及其版本:

#### 你做了什么？
一个表单中包含select组件，该组件要求既能下拉选择也能自己输入，于是设置combobox属性，在进行表单验证时，怎样能让其通过验证呢？
具体请看此链接  http://note.youdao.com/yws/public/redirect/share?id=67ee6bce0ea94171bfcbceba504aac9c&type=false

**Comment by benjycui** [comment]
公司访问不了有道，还是用 CodePen 吧。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by benjycui** [comment]
> 该组件要求既能下拉选择也能自己输入

怎么我觉得你应该用 http://ant.design/components/select/#components-select-demo-tags

**Comment by qiannianv** [comment]
前几天不是还能访问嘛~~   标签这个是多选，而我是要单选

**Comment by qiannianv** [comment]
http://codepen.io/anon/pen/EyGbqo?editors=001
那官网上的例子写的，但是却运行不起来，能先帮忙看下么？

**Comment by qiannianv** [comment]
如果有道笔记能看到就最好了

**Comment by benjycui** [comment]
我这边可以正常打开，或者你需要梯子。

> 在select中输入了下拉框中没有的值，移开后也能通过表单验证

都不知道你的校验逻辑是什么，或者你可以试下自定义校验规则。http://ant.design/components/form/#components-form-demo-validate-customized

**Comment by qiannianv** [comment]
仅仅只是验证该项必填而已，这个换了一种方法已经解决了，但下拉框有个需要优化的地方
在弹出的Modal中（Modal中包含Form表单），在select中输入了下拉框中没有的值，并且鼠标移出select组件（使其失去焦点），关闭Modal后，再次打开，这个Modal默认焦点在select上并且展示下拉框

**Comment by benjycui** [comment]
> 在弹出的Modal中（Modal中包含Form表单），在select中输入了下拉框中没有的值，并且鼠标移出select组件（使其失去焦点），关闭Modal后，再次打开，这个Modal默认焦点在select上并且展示下拉框

本地试了下，没有重现。

Please provide a re-producible demo: http://codepen.io/anon/pen/wGOWGW?editors=001
