### ISSUE TITLE
Upload>照片墙，图片上传后增加前后移位顺序功能【Upload Photo wall, image upload after adding before and after the shift sequence function】

### ISSUE THREAD

**Issue by 741599086** [ant-design/ant-design#26856]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
像商品轮播图这种情况即可解决，不然需要删除照片重新上传来定义顺序【This case can be solved like the product rotation diagram, otherwise the photo needs to be deleted and the definition order needs to be passed on】

### What does the proposed API look like?
无

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/pull/26333
