### ISSUE TITLE
Select 选择某一项Option之后，经常会再次弹出下拉菜单

### ISSUE THREAD

**Issue by aclrioe** [ant-design/ant-design#26867]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/7gxur)

### Steps to reproduce
点击Select选择Option，重复选择几次不同的Option，即可复现  
tips: 官网上Select或带Select的Form示例 均可复现  
tipssss: Safari浏览器下则无此问题

### What is expected?
选择后不会重复弹出下拉菜单

### What is actually happening?
选择后会重复弹出下拉菜单

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | macOS 10.13.6 |
| Browser | chrome 85 |

**Comment by zombieJ** [comment]
没点出来，给个 gif 看看你的操作？

**Comment by aclrioe** [comment]
> 没点出来，给个 gif 看看你的操作？

![Kapture 2020-09-24 at 10.28.18.gif](https://i.loli.net/2020/09/24/k2B1p4Seajb6c5o.gif)

**Comment by zombieJ** [comment]
神奇，我点不出来这个效果。隐身模式下呢？

**Comment by aclrioe** [comment]
> 神奇，我点不出来这个效果。隐身模式下呢？

无痕模式下也会...  刚刚顺便也试了下firefox，也能复现
就真的只有safari没这个情况

**Comment by zombieJ** [comment]
诡异了。 。 。
@ant-design/ant-design-collaborators 你们能重现出来吗？

**Comment by yoyo837** [comment]
不能，@aclrioe 是不是IE11 啊，写成Chrome了？

**Comment by Kermit-Xuan** [comment]
Edge 没有复现

**Comment by yoyo837** [comment]
会不会是因为Mac 10.13, 现在都是10.15

**Comment by aclrioe** [comment]
要是都没有复现的话就关了吧... 看起来好像是个例

**Comment by xiaohuoni** [comment]
@aclrioe 正常操作没复现，不过在选择的时候，按一下 command ｜option ｜control 这些按键，可以出现这样的效果。你要不重启一下电脑试试？？

**Comment by aclrioe** [comment]
@xiaohuoni 重启之后还是一样

**Comment by zombieJ** [comment]
> @aclrioe 正常操作没复现，不过在选择的时候，按一下 command ｜option ｜control 这些按键，可以出现这样的效果。你要不重启一下电脑试试？？

聚焦时按键触发下拉是预期行为

**Comment by xiaohuoni** [comment]
> > @aclrioe 正常操作没复现，不过在选择的时候，按一下 command ｜option ｜control 这些按键，可以出现这样的效果。你要不重启一下电脑试试？？
> 
> 聚焦时按键触发下拉是预期行为

我的意思是，是不是他某个按键坏了

**Comment by aclrioe** [comment]
> > > @aclrioe 正常操作没复现，不过在选择的时候，按一下 command ｜option ｜control 这些按键，可以出现这样的效果。你要不重启一下电脑试试？？
> > 
> > 
> > 聚焦时按键触发下拉是预期行为
> 
> 我的意思是，是不是他某个按键坏了

应该不是 如果我是某个按键坏了 那我的所有浏览器表现都应该一致吧？ Safari是正常的

**Comment by zombieJ** [comment]
未解之谜…………
