### ISSUE TITLE
Rerender issue when removing item from Form.List

### ISSUE THREAD

**Issue by SrAnthony** [ant-design/ant-design#26860]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ciy7u?file=/index.js)

### Steps to reproduce
Add some fields clicking on `add`. Check the console and only the newly created fields are updated (that's correct).
Click on `remove` on any field. The field is removed, but all fields below it will update as well, check the console.

### What is expected?
Only the field I remove should update, not the ones below it.

### What is actually happening?
All the fields below the one I am trying to remove are updated.

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 17 |
| System | Any |
| Browser | Chrome |

---
The reason they are updating is because the `field.name` props is sequential, like a index. It should not be.

**Comment by zombieJ** [comment]
Form.List is a wrapper to handle key to value index mapping. Which means Field should keep all the info when index changed. e.g:

1. When data is `[1, 3, 5]`. Field map path is `['xx.0', 'xx.1', 'xx.2']`
2. Remove `1`
3. Field path is `['xx.0', 'xx.1']`, which means all field after index 0 should switch one offset. Thus why all field after have to update

You can try only remove last one instead. Other field will not update.

PS: Your demo miss `key`. I updated: https://codesandbox.io/s/antd-reproduction-template-forked-p8137

**Comment by SrAnthony** [comment]
Ok, now I understand how it works. I created a new Form.Item with the same NamePath as the Form.List but with a fixed index value: https://codesandbox.io/s/antd-reproduction-template-forked-k4w2f

When executing form.getFieldsValue the field array has a lot of undefined indexes.

But I still cannot agree with the fields being updated when they are not being modified. If I have a big Form.List, with heavy items, this could be a problem. I am saying this because I'm rewriting an old form made with a older version of ant form, where all the fields always update. It is laggy and hard to use when have a lot of content.

For me having a lot of undefined values on the field array would not be a problem, but update all the fields below the one I remove would.

**Comment by mgupta83** [comment]
I am facing the same problem. Has anyone been able to fix this?

**Comment by awesomeWay** [comment]
I am facing the same problem. Has anyone been able to fix this?

**Comment by neginqantas** [comment]
same here, documentation should explain these cases
