### ISSUE TITLE
Button with type="link" can't have a prop ghost="true"

### ISSUE THREAD

**Issue by aslaugsollilja** [ant-design/ant-design#26861]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/AcePool/pen/BaKvwVd?editors=0010](https://codepen.io/AcePool/pen/BaKvwVd?editors=0010)

### Steps to reproduce
Set `ghost="true"` on a button with `type="link"`
like so: `<Button type="link" ghost="true">Link</Button>`

### What is expected?
That the button gets a ghost class

### What is actually happening?
no class is added when the prop `ghost="true"`

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | macOS Catalina 10.15.6 |
| Browser | chrome 85.0.4183.102 |

**Comment by afc163** [comment]
Button `type="link"` has transparent background already.

**Comment by Garrett-Smith-iq** [comment]
> Button `type="link"` has transparent background already.

We've run into a use case where our links don't have a transparent background in our custom theme. Is there any chance you could rethink this decision? Even if it doesn't have visual differences in the base theme?
