### ISSUE TITLE
AutoComplete受控模式，使用onchange onSearch value无法输入中文的问题

### ISSUE THREAD

**Issue by heytheww** [ant-design/ant-design#26869]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/auto-complete-cn/](https://ant.design/components/auto-complete-cn/)

### Steps to reproduce
1. 
 <AutoComplete
              value={inputValue}
              style={{ width: '100%' }}
              options={dataSource}
              onSearch={this.handleSearch}
              filterOption={false}
              onChange={this.handleChange}
            >
              <Input.TextArea
                ref={e => { this.editor = e }}
                onPressEnter={this.enterFunc}
                style={{ height: 100 }}
              />
            </AutoComplete>
2.
  // 话术快熟匹配
  handleSearch = value => {
    const {
      dispatch,
      im: { chatHelpSysAllList },
    } = this.props;
    // const { inputValue } = this.state

    // 计算匹配度：1前面内容的匹配度 2当前输入字的匹配度

    const list = chatHelpSysAllList && chatHelpSysAllList.length > 0 ? chatHelpSysAllList : [];

    let dataSource = [];
    for (let i = 0; i < list.length; i  ) {
      if (list[i].Details.indexOf(value) >= 0) {
        dataSource.push({ label: list[i].Details, value: list[i].Details });
      }
    }

    this.setState({
      dataSource,
    });
  };

 handleChange = value => {
    const {
      dispatch,
      im: { inputValue },
    } = this.props;

    dispatch({
      type: 'im/updateState',
      payload: {
        inputValue: `${value}`,
      },
    });
    console.log(value)
  };

3. 若inputValue存在this.state中，则render触发2次，输入中文正常，若inputValue放在dva管理的model中，输入中文闪掉，render执行3次

### What is expected?
不论组件的value传入来自哪里，均可正常输入中文

### What is actually happening?
组件的value由model  connect后传入，中文无法输入

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.8.6 |
| System | win10 |
| Browser | chrome x64 84.0.4147.125 |

---
场景要求input受控

**Comment by heytheww** [comment]
https://github.com/ant-design/ant-design/issues/18230 https://github.com/ant-design/ant-design/issues/17916 并没有解决我的问题

**Comment by zombieJ** [comment]
提供一下 codesandbox 在线重现。

**Comment by heytheww** [comment]
OK，我刚刚尝试分离代码上传到codesandbox，一分离就发现问题所在：
设我的AutoComplete所在组件为B，B的父组件为A
因为我在A和B均进行了一次connect model，所以，导致input onchange时触发多次更新，导致AutoComplete的中文输入问题
现在解决了，感谢！

**Comment by heytheww** [comment]
我的解决办法：在父组件connect model，然后给子组件通过props传它要的东西
