### ISSUE TITLE
multiple select 问题

### ISSUE THREAD

**Issue by wangwangliu** [ant-design/ant-design#2686]
let children = [];
for (let i = 10; i < 36; i++) {
  children.push( <  Option   key=  **key**  >  **value**  </   Option   >);
}

ReactDOM.render(
  <multiple
    multiple
    style={{ width: '100%' }}
    placeholder="Please select"
    defaultValue={['a10', 'c12']}
    onChange={handleChange}>
    {children}
  </Select>
, mountNode);

**defaultValue**有没有什么好的方法直接取**value**值 而不是去取**key**值然后通过**key**去编译成**value** 这样体验不好。

期待的是http://sandbox.runjs.cn/uploads/rs/439/roqnrfyi/hf5lrqut.png 这个结果
但显示的时候会先跳出http://sandbox.runjs.cn/uploads/rs/439/roqnrfyi/1.png 这个结果

**Comment by ddcat1115** [comment]
给个demo？没有重现出『先跳出XXX』的效果

 http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by afc163** [comment]
请按照 issue 模板报告问题。
