### ISSUE TITLE
能否添加一个 面板分割 组件 和Iview 一样

### ISSUE THREAD

**Issue by huoshidehua** [ant-design/ant-design#26878]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
将屏幕分割，分割线可以拖动

### What does the proposed API look like?
<Split v-model="split1"></Split>

**Comment by huoshidehua** [comment]
Split

**Comment by huntdream** [comment]
可以看看这个：https://github.com/STRML/react-grid-layout

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/12636
