### ISSUE TITLE
Down arrow on a <Select> component will open the drop-down but not select the first option

### ISSUE THREAD

**Issue by cuibonobo** [ant-design/ant-design#26877]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-mv870)

### Steps to reproduce
Once the example has completely loaded, the select element should be automatically focused. Hit the down arrow on the keyboard to open the drop-down.

### What is expected?
The first option should be selected when the drop-down opens by hitting the down arrow.

### What is actually happening?
The drop-down opens, but the first option is not selected.

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Firefox 80.0.1 |

---
The Select element requires that you press the down arrow twice in order to select the first option. This is not consistent with the default HTML `select` element. In addition, hitting the Tab key does not select the currently highlighted option, but this is a separate issue: #26876.

**Comment by afc163** [comment]
See https://codesandbox.io/s/antd-reproduction-template-forked-q8ls2

**Comment by cuibonobo** [comment]
Thanks for providing a solution, but the documentation for `defaultActiveFirstOption` says that the default value for this option is `true`. If that were the case, the desired behavior would happen by default without needing to specify the option.

It seems to me like there is still a bug: either the default behavior for `defaultActiveFirstOption` is incorrect, or the documentation should list the default value as `false`.
