### ISSUE TITLE
antd4.0 上传文件报错fileList.filter is not a function

### ISSUE THREAD

**Issue by s464446877** [ant-design/ant-design#26870]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
上传文件报错fileList.filter is not a function

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8.6 |
| System | mac |
| Browser | chrome85 |

**Comment by s464446877** [comment]
好像只有在头像上传模式下会报这个错，按钮模式的上传就没有报错

**Comment by Z-longlong** [comment]
<FormItem label="picture">
	{getFieldDecorator('logoUrl', {
		rules: [ { required: true, message: 'error' } ],
		initialValue: `${editInfo.logoUrl || ''}`,
		//  close  [antd: Upload] `value` is not validate prop, do you mean `fileList`?
		valuePropName: 'fileList'
	})(
		<Upload
                          name="imgs"
                          listType="picture-card"
                         className="avatar-uploader"
			showUploadList={false}
			action={global.uploadUri}
			beforeUpload={this.beforeUpload}
			onChange={this.handleChange}
		>
									
		</Upload>
	)}
</FormItem>
这样写就会导致 fileList.filter is not a function 这个问题
