### ISSUE TITLE
Added Button in Submenu Title cannot stop event propagation

### ISSUE THREAD

**Issue by Fangmingdu** [ant-design/ant-design#26875]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nifty-voice-moz3w?file=/index.js)

### Steps to reproduce
Just open the codesandbox link and you can see there is a button on the submenu title.

### What is expected?
When button is clicked, it should not collapse/open submenu

### What is actually happening?
When button is clicked, submenu is opened/collapsed

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | MacOS 10.15.5 |
| Browser | Chrome 85.0.4183.102 |

**Comment by afc163** [comment]
It works: https://codesandbox.io/s/adoring-liskov-4cohf
