### ISSUE TITLE
remove default scroll bar style of tree component

### ISSUE THREAD

**Issue by waveheart** [ant-design/ant-design#26871]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
the tree component has used virtualized, then it dosen't need the default scroll bar at all, 
in some cases , when user scoll the bar or expand the tree , the default scoll bar style and the virtual scroll bar style are diffrent, user experience is not good.

### What does the proposed API look like?
just remove the default style

![image](https://user-images.githubusercontent.com/25602259/94009987-e2051000-fdd7-11ea-86c6-2a3addfb9735.png)

**Comment by afc163** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/::-webkit-scrollbar
