### ISSUE TITLE
Editable tabs need close action when hiding within a dropdown

### ISSUE THREAD

**Issue by shuozhang2016** [ant-design/ant-design#26882]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tabs/](https://ant.design/components/tabs/)

### Steps to reproduce
Add as many tabs as you can

### What is expected?
Tabs in dropdown items also has capability removing itself

### What is actually happening?
Tabs not editable within dropdown

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16 |
| System | macOs |
| Browser | any |

![image](https://user-images.githubusercontent.com/17228552/94109760-0a424c80-fe74-11ea-81b2-a2645d4a8b28.png)

**Comment by n0ruSh** [comment]
@afc163 Can I take this one? I took a look at the codebase and the feature should be implemented in rc-tabs?

**Comment by afc163** [comment]
@n0ruSh sure, you could send PR to rc-tabs and then intergate it in antd.
