### ISSUE TITLE
Dynamic mention options do not always load on the first keystroke

### ISSUE THREAD

**Issue by mraiguo** [ant-design/ant-design#26881]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/mentions-cn/#components-mentions-demo-async](https://ant.design/components/mentions-cn/#components-mentions-demo-async)

### Steps to reproduce
输入数字或字母

### What is expected?
首次输入字母或数字能渲染出下拉框

### What is actually happening?
没有渲染，只有按退格后再点击才出现下拉框

| Environment | Info |
|---|---|
| antd | undefined |
| React | react16 |
| System | win10 |
| Browser | chrome |

---
https://github.com/react-component/mentions/issues/29

**Comment by afc163** [comment]
你需要先输入 @ 才行。

**Comment by mraiguo** [comment]
嗯  是我描述不全，我是说在 输入了@ 的情况下再随便输入字母或数字，不过也可以关了，我同事在 rc-mentions 提了个 pr 处理了  @afc163
