### ISSUE TITLE
Modal里面onOk事件里弹出一个Modal.confirm的问题

### ISSUE THREAD

**Issue by bihongbin3027** [ant-design/ant-design#26891]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Modal里面onOk事件里弹出一个Modal.confirm，该confirm的确定按钮没有默认获取焦点

### What does the proposed API look like?
请问这是设计如此吗？这个是复现链接：https://codesandbox.io/s/lucid-worker-btvu8?file=/index.js:411-418
还有一个问题，Modal.confirm怎么把操作按钮设置为1个，默认就是2个按钮

**Comment by fatihcandev** [comment]
I'm experiencing this problem too. The ok button becomes clickable after clicking once.
