### ISSUE TITLE
Add isInvalid prop to the input controls when error occured

### ISSUE THREAD

**Issue by kaisian97** [ant-design/ant-design#26897]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Currently, the control's valid/invalid status only apply for the Antd Form. What if I want to use other form library and want to make the control has the same error style. 

### What does the proposed API look like?
When error occured, pass the "isInvalid" to the controls
```
      <Input isInvalid ...
      <InputNumber isInvalid ...
      <Select isInvalid ...
       // other input controls
```

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/issues/33854
