### ISSUE TITLE
The Modal component's close icon did not work when missing the `onCancel` prop

### ISSUE THREAD

**Issue by Jecyu** [ant-design/ant-design#26890]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/suspicious-sara-eevst)

### Steps to reproduce
1. Provide the null value to footer props.
2. Not provide the `onCancel` callback.

### What is expected?
The Modal component's close icon can close the modal normally. 

### What is actually happening?
The Modal component's close icon can't close the modal normally. 

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | macOS Catalina 10.15.5 |
| Browser | Chrome 版本 81.0.4044.122（正式版本） （64 位） |

---
The scenario is the app not need the footer of the modal.

**Comment by huntdream** [comment]
这个不是正常行为吗，不改变`visible`的状态怎么控制Modal的打开和关闭

**Comment by Jecyu** [comment]
> 这个不是正常行为吗，不改变`visible`的状态怎么控制Modal的打开和关闭

感谢回复，因为之前习惯了 vue 的写法，所以有点疑问，是不是这是 react 和 vue 的单向数据流与双向绑定的区别写法，导致 react 中类似这样的行为都是提供回调，开发者自己在外部进行手动更新状态进行关闭的？参考的链接：https://www.zhihu.com/question/300849926

**Comment by afc163** [comment]
这是正常行为，visible 是一个受控属性。
