### ISSUE TITLE
优化 Tree 第二级节点展开动画

### ISSUE THREAD

**Issue by guoyl6** [ant-design/ant-design#26899]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/d2b0e)

### Steps to reproduce
点击树节点的第二级节点，可以看到展开结束后高度突然改变。

### What is expected?
展开动画的节点高度与结束后的节点实际高度相等。

### What is actually happening?
展开动画的节点高度大于结束后的节点实际高度。

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome |

**Comment by afc163** [comment]
@guoyl6 帮忙看看最新版本问题还在么 https://codesandbox.io/s/distracted-marco-ggsj4w?file=/index.js

如果还在能否提供一个录屏。

**Comment by guoyl6** [comment]
最新版本没有这个问题了
