### ISSUE TITLE
checkbox动态改变options里的某一项的value，checkboxGroup会错误的新增

### ISSUE THREAD

**Issue by SingleGardenDog** [ant-design/ant-design#26898]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-si15h?file=/test.js)

### Steps to reproduce
1.Checkbox.Group的options默认值是[{label:'',value:''},{lable:'',value:''}]。
2.修改options为新的数组对象(不是修改原options)为[{label:'',value:'test'},{label:'',value:''}]。这时候Checkbox.Group会错误的多渲染出几个checkbox。

### What is expected?
按照options的数组长度正常渲染

### What is actually happening?
渲染出的checkbox渲染超过options的数组长度

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16.13.1 |
| System | windows10 |
| Browser | google:85.0.4183.102 |

---
动态生成checckbox时问题必现。

**Comment by huntdream** [comment]
key的问题，初始化的时候给value带上不同的值
