### ISSUE TITLE
Anchor小圆点无法正确跟随到当前锚点

### ISSUE THREAD

**Issue by calmchang** [ant-design/ant-design#26895]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd4-anchor-issue-jyd9z)

### Steps to reproduce
1、为了方便 index.css内设置 *{position:relative}
2、在窗口滑动滚动条，可以看到小圆点没有跟随到当前焦点的锚点旁

查看了源代码发现问题出在 更新小圆点top值的计算上

```javascript
updateInk = () => {
    if (typeof document === 'undefined') {
      return;
    }
    const { prefixCls } = this.props;
    const linkNode = ReactDOM.findDOMNode(this as any).getElementsByClassName(`${prefixCls}-link-title-active`)[0];
    if (linkNode) {
      //由于relative下，offsetTop的值是相对于父节点的值，所以每个锚点<a>标签的offsetTop都一样导致计算错误
      this.inkNode.style.top = `${(linkNode as any).offsetTop   linkNode.clientHeight / 2 - 4.5}px`;
    }
  }

```
建议把relative情况下考虑进去

### What is expected?
可以跟随移动

### What is actually happening?
不能

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12.0 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
为啥要设置杀伤力这么大的全局样式？

**Comment by calmchang** [comment]
目前我的解决方法是
如果遇到了有将dom都设置成position:relative的话
可以覆盖锚点链接的样式来解决
.ant-anchor-link{
    position: static ;
  }

**Comment by afc163** [comment]
或者这样：https://codesandbox.io/s/antd4-anchor-issue-forked-847mm

```css
*:not(.ant-affix *) {
  position: relative;
}
```

**Comment by calmchang** [comment]
> 或者这样：https://codesandbox.io/s/antd4-anchor-issue-forked-847mm
> 
> ```css
> *:not(.ant-affix *) {
>   position: relative;
> }
> ```

*:not(.ant-affix *)  这个选择器并没生效
