### ISSUE TITLE
Select组件 -  mode="tags" 输入两次相同内容，onChange回调里面之前填写的tag会被清除掉

### ISSUE THREAD

**Issue by konghouyin** [ant-design/ant-design#26893]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yh7yp)

### Steps to reproduce
输入框获取焦点，输入“123”，按下enter件，tag显示符合预期。再次输入“123”，按下enter，之前显示tag“123”消失了。

### What is expected?
第二次输入“123”后，原本的tag“123”依然显示

### What is actually happening?
再次输入“123”，按下enter，之前显示tag“123”消失了。

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | react 16.12.0 |
| System | mac |
| Browser | chrome 85 |

---
onchange回调中直接消失了一项，业务方也不好找回这个丢失的一项

**Comment by zombieJ** [comment]
这就是预期行为。
