### ISSUE TITLE
Autocomplete enter key issue

### ISSUE THREAD

**Issue by rsdineshbalaji** [ant-design/ant-design#26892]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/auto-complete/](https://ant.design/components/auto-complete/)

### Steps to reproduce
Take any autocomplete example
mouser over suggestion dropdown and press enter key

### What is expected?
The mouseover suggestion should not get updated in the textbox with enter key press

### What is actually happening?
The mouseover suggestion replaces the existing  value in the textbox with enter key press

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | MAC  |
| Browser | Chrome 85 |

**Comment by zombieJ** [comment]
It's by design.
