### ISSUE TITLE
Typescript error in Icon.d.ts at node_modules/@ant-design/icons/lib/components/Icon.d.ts

### ISSUE THREAD

**Issue by ahsanzahid-se** [ant-design/ant-design#26907]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
import { layout } from 'antd'
and compilation error happens.

### What is expected?
Imports should work fine and compile

### What is actually happening?
Compilation error.

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Version 85.0.4183.121 (Official Build) (64-bit) |

---
Type '"cite" | "data" | "form" | "label" | "span" | "style" | "summary" | "title" | "pattern" | "children" | "className" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 350 more ... | "ariaLabel"' does not satisfy the constraint '"ref" | "cite" | "data" | "form" | "label" | "span" | "style" | "summary" | "title" | "pattern" | "children" | "className" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 349 more ... | "ariaLabel"'.
  Type '"translate"' is not assignable to type '"ref" | "cite" | "data" | "form" | "label" | "span" | "style" | "summary" | "title" | "pattern" | "children" | "className" | "defaultChecked" | "defaultValue" | "suppressContentEditableWarning" | ... 349 more ... | "ariaLabel"'.  TS2344

    17 |     ariaLabel?: React.AriaAttributes['aria-label'];
    18 | }
  > 19 | declare const Icon: React.ForwardRefExoticComponent<Pick<IconComponentProps, "max" | "required" | "default" | "high" | "low" | "disabled" ....................."onAnimationIteration" | "onAnimationIterationCapture" | "onTransitionEnd" | "onTransitionEndCapture"> & React.RefAttributes<HTMLSpanElement>>;
       |                                                                              ^
    20 | export default Icon;

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/23266#issuecomment-613773502
