### ISSUE TITLE
Menu: Bug with the open state of the Submenu when collapsing the sidebar

### ISSUE THREAD

**Issue by e965** [ant-design/ant-design#26905]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-submenu-bug-dyrhr)

### Steps to reproduce
0) First, open a console to see the value of the "OpenKeys" array (in MenuComponent.js)
1) Click to any meny item (Test Nav 1 or Test Nav 2)
2) Click to "Collapse trigger"

### What is expected?
Since the OpenKeys array becomes empty when the panel is collapsed, the Submenu should not be shown in the popover

### What is actually happening?
The Submenu is shown

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome 85, Firefox 81 |

**Comment by nuintun** [comment]
Same bugs

**Comment by xiaoniuge** [comment]
![A4}(5UHG@GTL Z)Z D @A21](https://user-images.githubusercontent.com/58249520/94522249-ec089200-0261-11eb-971d-fa872f73c3a5.png)

**Comment by Kermit-Xuan** [comment]
@xiaoniuge 

I can't reproduce it

![image](https://user-images.githubusercontent.com/33770367/95582967-09add680-0a6e-11eb-8d57-20fe04bcc33c.png)

**Comment by nuintun** [comment]
@Kermit-Xuan Use controlled component!

**Comment by e965** [comment]
@Kermit-Xuan any progress? 🤔

**Comment by Kermit-Xuan** [comment]
> @Kermit-Xuan any progress? 🤔

Work in progress, it's difficult to find problem 😂

**Comment by nuintun** [comment]
@Kermit-Xuan @afc163 

还是有问题：

![menu](https://user-images.githubusercontent.com/1730277/97935855-b7ce4700-1db4-11eb-811e-91ac9a22c8cf.gif)

**Comment by Kermit-Xuan** [comment]
是的，还是有问题，所以修复了后没有往 antd 里面合并，还在修闪屏的问题，这个问题已经好了，想着两个全部修好了发布个 patch 版本。

**Comment by nuintun** [comment]
@Kermit-Xuan 好的，不过 antd 中 `rc-mentions`，`rc-tabs` 已经应用了最新的，它们的依赖用的 `^`，antd 全局用的 `~`，现在 `4.8.0` 的 antd 实际引用了两个版本的 `rc-menu`：

![企业微信截图_20201103093413](https://user-images.githubusercontent.com/1730277/97936834-c1a57980-1db7-11eb-8aec-fe0ed7ac2256.png)

**Comment by Kermit-Xuan** [comment]
是的，因为上次打算升级 antd 的，发现有问题就没有升，今天我再看看，menu 的逻辑太复杂，周末找了好长时间，都没定位到问题😂。

**Comment by nuintun** [comment]
@Kermit-Xuan :smile: menu 逻辑是复杂了。

**Comment by xrkffgg** [comment]
但是 Pro 里点击收缩没问题啊 https://preview.pro.ant.design/dashboard/analysis

**Comment by Kermit-Xuan** [comment]
这个是和 slider 一起使用时出的问题，你看复现的例子。

**Comment by xrkffgg** [comment]
我看复现的例子，点击收缩的时候，ant-menu-submenu-open 还残留了一点时间
