### ISSUE TITLE
inputNumber:已设置formatter类似`$ ${value}`前缀时，在$左侧输入数字会倒序渲染（光标没有自动纠正到前缀右侧）

### ISSUE THREAD

**Issue by hellojeana** [ant-design/ant-design#26909]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number-cn/](https://ant.design/components/input-number-cn/)

### Steps to reproduce
在格式化展示案例中，在$左侧输入数字

### What is expected?
第一次在$左侧输入数字时就应该自动纠正光标至$右侧

### What is actually happening?
第二次在$左侧输入数字时才自动纠正光标至$右侧

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.0 |
| System | mac os |
| Browser | chrome |

**Comment by afc163** [comment]
Duplicate of #28366
