### ISSUE TITLE
useIntl with umi throws error of hooks 

### ISSUE THREAD

**Issue by arpanEnbake** [ant-design/ant-design#26912]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-i5azry?file=index.js](https://stackblitz.com/edit/react-i5azry?file=index.js)

### Steps to reproduce
Add a tree select 
For internationlization, add useIntl to placeholder.

import {useIntl} from 'umi'

 <TreeSelect
       placeholder={useIntl().formatMessage({id:"Please select"})}

Following error comes in console.

devScripts.js:5836 Warning: React has detected a change in the order of Hooks called by FormSearch. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useRef                     useRef
3. useState                   useState
4. useRef                     useRef
5. useMemo                    useMemo
6. useRef                     useRef
7. useContext                 useContext
8. useRef                     useRef
9. useState                   useState
10. useCallback               useCallback
11. useEffect                 useEffect
12. useRef                    useRef
13. useEffect                 useEffect
14. useContext                useContext
15. undefined                 useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    in FormSearch (created by ProTable)
    in div (created by ProTable)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (created by ProTable)
    in ProTable (created by ProviderWarp)
    in ErrorBoundary (created by ProviderWarp)
    in ConfigProviderWarp (created by ProviderWarp)
    in Provider (created by ProviderWarp)
    in ProviderWarp (at alerts/index.tsx:113)
    in div (created by PageContainer)
    in div (created by PageContainer)
    in div (created by GridContent)
    in div (created by GridContent)
    in GridContent (created by PageContainer)
    in div (created by PageContainer)
    in PageContainer (at alerts/index.tsx:112)
    in AlertList (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in Route (created by Context.Consumer)
    in Switch (created by Context.Consumer)
    in WithExceptionOpChildren (at layout/index.tsx:140)
    in ErrorBoundary (at layout/index.tsx:139)
    in main (created by Basic)
    in Basic (created by Context.Consumer)
    in Content (created by WrapContent)
    in ConfigProviderWarp (created by WrapContent)
    in WrapContent (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in section (created by Context.Consumer)
    in BasicLayout (created by Context.Consumer)
    in Layout (created by BasicLayout)
    in div (created by BasicLayout)
    in Provider (created by BasicLayout)
    in BasicLayout (at layout/index.tsx:83)
    in BasicLayout
    in Unknown (created by LoadableComponent)
    in LoadableComponent (created by Context.Consumer)
    in Route (created by RouterComponent)
    in Switch (created by RouterComponent)
    in Router (created by RouterComponent)
    in RouterComponent
    in AccessProvider
    in Provider (created by _DvaContainer)
    in _DvaContainer
    in Unknown
    in FormProvider (created by Context.Consumer)
    in LocaleProvider (created by Context.Consumer)
    in SizeContextProvider (created by Context.Consumer)
    in LocaleReceiver (created by ConfigProvider)
    in ConfigProvider (at locale.tsx:49)
    in _LocaleContainer
    in Unknown
console.<computed> @ devScripts.js:5836
overrideMethod @ react_devtools_backend.js:2273
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60

### What is expected?
No error in console

### What is actually happening?
for placeholder, react hooks cycle is broken

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16 |
| System | ubuntu 18 |
| Browser | chrome 85 |

---
This works fine if formatMessage is used instead of useIntl()

**Comment by ycjcl868** [comment]
`useIntl` should use in React Function Component, not Class Component.  https://umijs.org/plugins/plugin-locale#useintl
