### ISSUE TITLE
官方网站的网站验证码，正常情况下，几乎每次打开任何页面都会出现

### ISSUE THREAD

**Issue by 120011676** [ant-design/ant-design#26917]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/overview-cn/](https://ant.design/components/overview-cn/)

### Steps to reproduce
官方网站的网站验证码，正常情况下，几乎每次打开任何页面都会出现

### What is expected?
官方网站的网站验证码，正常情况下，几乎每次打开任何页面都会出现

### What is actually happening?
官方网站的网站验证码，正常情况下，几乎每次打开任何页面都会出现

| Environment | Info |
|---|---|
| antd | undefined |
| React | 官方网站的网站验证码，正常情况下，几乎每次打开任何页面都会出现 |
| System | 官方网站的网站验证码，正常情况下，几乎每次打开任何页面都会出现 |
| Browser | 官方网站的网站验证码，正常情况下，几乎每次打开任何页面都会出现 |

**Comment by yoyo837** [comment]
啥验证码？网站文档访问还需要验证码？

**Comment by ycjcl868** [comment]
说的是 pro？https://preview.pro.ant.design/dashboard/analysis

**Comment by 120011676** [comment]
https://ant.design/components/overview-cn/

选火车、汽车、飞机验证码

**Comment by yoyo837** [comment]
这个界面哪有什么火车飞机汽车？

**Comment by hengkx** [comment]
我也没有出现

**Comment by hengkx** [comment]
提供个gif？

**Comment by yoyo837** [comment]
他是不是被网络劫持了，加了广告？

**Comment by xrkffgg** [comment]
未出现

**Comment by 120011676** [comment]
https也能劫持，改内容什么的?
![image](https://user-images.githubusercontent.com/1992933/94503385-eb0f3a80-0238-11eb-8ee2-4358c2c26d21.png)

**Comment by yoyo837** [comment]
你的浏览器插件，VPN，你的路由防火墙设备等等。

**Comment by 120011676** [comment]
https哦？

**Comment by yoyo837** [comment]
你自己找一下原因吧，我只能猜测

**Comment by afc163** [comment]
你的代理被 cloudflare 识别成机器人了。

**Comment by 120011676** [comment]
1.没有代理
2.这是antd官网对接的cloudflare吗？
3.正常访问均出现
4.https也能劫持？

**Comment by yoyo837** [comment]
cloudflare 识别的，不算劫持

**Comment by yoyo837** [comment]
你不开这个issue我还不知道某些情况会出现人机验证呢！3年了一次也没遇到过，这是你网络环境相关的问题。

**Comment by afc163** [comment]
我个人有时候打开 v2ex.com 也会偶尔遇到。

**Comment by 120011676** [comment]
那说明是官网的了
就是想官网取消他的验证码，他个一个网站，流量多就流量多嘛

**Comment by yoyo837** [comment]
好像是内部机制，没得用户控制

**Comment by 120011676** [comment]
他用的cdn出的样
