### ISSUE TITLE
Modal组件创建的dom被异常删除

### ISSUE THREAD

**Issue by junjie-lean** [ant-design/ant-design#26920]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
Modal组件，设置属性为：
      visible={ someValue == 1 || someValue == 2  }
      onCancel={onCancel}
      title={title}
      maskClosable={false}
      width={355}
      footer={null}
      className="modal_test"

未设置   destroyOnClose、forceRender等其他属性。

### What is expected?
 在关闭组件时,将Modal实例的DOM保留在html节点中，并且能在控制someValue的情况下打开任意modal

### What is actually happening?
在通过将someValue设置为1时，可以正常打开组件，但是打开此组件后再关闭该组件，该组件实例DOM从html节点里移除。
再通过将someValue设置为2时，弹框无法正常打开。但是通过将someValue设置为1，弹框组件又能打开。

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | macOs 10.15.6   |
| Browser | Chrome 85.0.4183.121 |

**Comment by Kermit-Xuan** [comment]
给个 codesandbox 复现示例

**Comment by junjie-lean** [comment]
> 给个 codesandbox 复现示例

给不了哦，但是实际上是有这个情况的。
