### ISSUE TITLE
Windows上的火狐使用拖拽上传功能无法正确阻止浏览器在新标签页打开文件

### ISSUE THREAD

**Issue by masontin** [ant-design/ant-design#26927]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-eyl39?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
# 打开下面链接

[![Edit antd reproduction template (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-eyl39?fontsize=14&hidenavigation=1&theme=dark)

# 拖拽一张图片至控件

### What is expected?
浏览器不要打开新的标签页

### What is actually happening?
浏览器打开了新的标签页

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | lasted |
| System | Windows 10 |
| Browser | firefox 60  |

---
不要使用MacOS上的火狐测试，Mac上没问题，一定要用 Windows 10 平台   最近版本的 Firefox。从2016年至今，官方的[拖拽上传文档](https://ant.design/components/upload-cn/#components-upload-demo-drag)至今也存在这个问题。

**Comment by masontin** [comment]
![GIF 2020-9-28 20-44-09](https://user-images.githubusercontent.com/46433259/94433846-78b44100-01cb-11eb-97c1-ef487c069af2.gif)

**Comment by afc163** [comment]
Firefox 60 太老了，请升级到最新版本。

**Comment by masontin** [comment]
@afc163  我写的是60+ ， 代表60 至 最新版本都有这个问题，你可以下载最新的firefox 重现。我用了多台电脑，下了最新的 firefox 测试过的，都会弹出标签页。

**Comment by masontin** [comment]
![firefox 81](https://user-images.githubusercontent.com/46433259/94515667-a8f4f180-0256-11eb-89d8-260439095c07.gif)

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26938#issuecomment-700680974
