### ISSUE TITLE
inputNumber当formatter和rules一起用时formatter会出现异常情况

### ISSUE THREAD

**Issue by wangjinxin613** [ant-design/ant-design#26924]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/new](https://github.com/ant-design/ant-design/issues/new)

### Steps to reproduce
xx

### What is expected?
xx

### What is actually happening?
xx

| Environment | Info |
|---|---|
| antd | undefined |
| React | vue版本 |
| System | window |
| Browser | 谷歌 |

**Comment by afc163** [comment]
This is not the repository of ant design vue.
