### ISSUE TITLE
why can't i uncheck all selected rows by setState func on the Table component?

### ISSUE THREAD

**Issue by oopsRookie** [ant-design/ant-design#26928]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-liskov-legie?file=/src/index.js)

### Steps to reproduce
1、check any items
2、click button named 'UNCHCK ALL'

### What is expected?
the all of selected checkboxs UI  transform to unchecked after clicking the reset button.

### What is actually happening?
the UI of checked checkboxs didn't changed after clicking button.

| Environment | Info |
|---|---|
| antd | 4.6.2 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | firefox |

---
ps:  after you select any of them, you will find the state of selectedRowKeys in React DevTools has been reset to empty array, but the UI is not sync with the state. (still selected)
And  if i cancel the notation in line 45, i can no longer select any row

**Comment by afc163** [comment]
Your codesandbox cannot work.

**Comment by oopsRookie** [comment]
> 
> 
> Your codesandbox cannot work.

sry,i checked the orginal link, something wrong on it because of network lag. And it's ok now.
here is link
[lastest reproduction link](https://codesandbox.io/s/zealous-liskov-legie?file=/src/index.js)

**Comment by oopsRookie** [comment]
> 
> 
> Your codesandbox cannot work.

And if it's still not work. Here is source code below. thank you

```
import React from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import { Button, Table } from "antd";

const dataSource = [
  {
    id: 1,
    sortName: "a"
  },
  {
    id: 2,
    sortName: "b"
  },
  {
    id: 3,
    sortName: "c"
  },
  {
    id: 4,
    sortName: "d"
  }
];
class Example extends React.Component {
  constructor(props) {
    super(props);
    this.columns = [
      {
        title: "序号",
        render: (text, record, index) => `${index + 1}`
      },
      {
        title: "设备分类",
        dataIndex: "sortName",
        render: (text) => text,
        sorter: (a, b) => a.sortName > b.sortName
      }
    ];
  }
  state = {
    selectedRowKeys: [],
    batchRecord: [],
    page: { current: 1, pageSize: 2 }
  };
  rowSelection = {
    //selectedRowKeys: this.state.selectedRowKeys,
    preserveSelectedRowKeys: false,
    onChange: (selectedRowKeys, selectedRows) => {
      //所有选中的id,行
      //console.log("onChange()"+`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
      const batchRecord = selectedRows;
      this.setState({ selectedRowKeys, batchRecord });
    }
  };

  handlePageChange = (pagination, filters, sorter, extra) => {
    let current = pagination.current;
    let pageSize = pagination.pageSize;
    switch (extra.action) {
      case "paginate": {
        this.setState({ page: { current, pageSize } });
        break;
      }
      default:
        break;
    }
  };
  clickAll = () => {
    this.setState({ selectedRowKeys: [], batchRecord: [] });
  };
  render() {
    return (
      <div>
        <Table
          rowSelection={{ ...this.rowSelection }}
          columns={this.columns}
          dataSource={dataSource}
          rowKey="id"
          pagination={{
            defaultPageSize: 2,
            showSizeChanger: true,
            pageSizeOptions: [2, 5],
            position: ["topLeft", "bottomRight"]
          }}
          onChange={this.handlePageChange}
        />
        <Button onClick={this.clickAll}>清空所有(UNCHECK ALL)</Button>
      </div>
    );
  }
}

ReactDOM.render(<Example />, document.getElementById("root"));

```

**Comment by afc163** [comment]
https://codesandbox.io/s/broken-bash-e76lo
