### ISSUE TITLE
Upload 组件在多选模式上传图片时，onChange似乎会丢失一些图片

### ISSUE THREAD

**Issue by Catsbe** [ant-design/ant-design#26925]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/charming-wright-4v8rv?file=/src/App.js)

### Steps to reproduce
点击上传按钮，上传至少5张图片

### What is expected?
5张图片都应该显示上传成功或失败

### What is actually happening?
只显示了2张图片

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Win7 64位 |
| Browser | 版本 81.0.4044.69（正式版本）beta （64 位） |

**Comment by Catsbe** [comment]
我检查过onChange，fileList总是会丢失一些图片（通过uid辨识），导致更新时，fileList只有不到5个

**Comment by afc163** [comment]
similar with #26536

**Comment by Kermit-Xuan** [comment]
![image](https://user-images.githubusercontent.com/33770367/94416669-b4daa800-01b1-11eb-8137-a2d671914769.png)

为啥要加个 `fileList.slice(-2)` 然后重新赋值，肯定只有两个了。

**Comment by Catsbe** [comment]
不好意思，我是直接复制黏贴的官网的实例，去掉了，确实没问题，但是服务器正式环境的确有问题，我本地也试过，也没问题。。
https://github.com/ant-design/ant-design/issues/26536 跟这个BUG是一样的，期待修复ing

**Comment by afc163** [comment]
欢迎帮忙找找重现方式。
