### ISSUE TITLE
请问这段代码为何work？这么做是否有违React的基本思想？是否有潜在Crash的可能？

### ISSUE THREAD

**Issue by JonneyYan** [ant-design/ant-design#2692]
https://github.com/ant-design/ant-design/blob/2be285d2367e9dd59f225f762131b97260c0adff/components/alert/index.jsx#L24-L27

**Comment by afc163** [comment]
有时用于实现动画，不免需要一些 trick code。如果有使用问题或优化建议，欢迎提 issue 和 PR 。
