### ISSUE TITLE
Popover in data table

### ISSUE THREAD

**Issue by saresh-krish** [ant-design/ant-design#26930]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/fragrant-thunder-ckc0p?file=/index.js)

### Steps to reproduce
Popover in dynamic data table

### What is expected?
When i click the button it will show only one popover at a time.

### What is actually happening?
When i click "click me" button it will open all popover at a single time. Because popover is show/hide based on "visiable : true". 

| Environment | Info |
|---|---|
| antd | 4.1.4 |
| React | 16.13.1 |
| System | Ubuntu 18.04.3 LTS |
| Browser | Google Chrome Version 79.0.3945.130 (Official Build) (64-bit) |

---
When i click the "Click Me" button it will show only that particular Popover at a time and close also.

**Comment by xrkffgg** [comment]
You should use different `visible` in this two row. Like `visible1` and `visible2`.

**Comment by saresh-krish** [comment]
@xrkffgg i will using backend data i donot no how many rows is coming it's total dynamical data. How to control dynamical data here.

**Comment by xrkffgg** [comment]
By default, Popover support.

You can remove 

```diff
-- visible={this.state.visible}
-- onVisibleChange={this.handleVisibleChange}
```

**Comment by saresh-krish** [comment]
@xrkffgg i need to close Popover also when i click close button the popover wants to close.
If we remove the 'Visible & onVisibleChange' how to control the "{this.state.visible}" show and hide.

**Comment by xrkffgg** [comment]
You can try like 
https://stackoverflow.com/questions/63586808/react-form-single-handlechange-function-with-multiple-inputs-and-setstate-to-com

https://www.coder.work/article/5792461

**Comment by saresh-krish** [comment]
@xrkffgg i tried this above function with passing "Name" & "value" it's not working.
`this.setState({ 
        ingredient: {
            ...this.state.ingredient,
            [name]: value
        } 
    });`
Why Popover is not working like Antd Modal Popup.
