### ISSUE TITLE
Space support split

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#26939]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
不用重复写分割线

### What does the proposed API look like?

```
<Divider>
<a>aaa</a>
<a>aaa</a>
</Divider>
```

**Comment by afc163** [comment]
不太理解这样写 UI 是什么样子的。

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/94519939-02acea00-025e-11eb-9cca-b5c43b4ca04e.png)

**Comment by hengkx** [comment]
多个元素中间 用线隔开

**Comment by afc163** [comment]
垂直分割场景还比较合理，水平的分割线就会比较奇怪。

**Comment by hengkx** [comment]
我们现在的 场景就是 垂直的🤣  每个 都要写N次分割线 觉得有点麻烦

**Comment by afc163** [comment]
Divider 的 children 有作为标题的作用，这里不好改。

**Comment by hengkx** [comment]
加个Divider.Group 来实现，里面 调用Divider 怎么样？

**Comment by afc163** [comment]
可行。

**Comment by hengkx** [comment]
我加一下 4.7什么时候发 还能赶上车不

**Comment by afc163** [comment]
加的快就赶得及，这个功能比较简单。

**Comment by zombieJ** [comment]
这个不该是 Divider 的事情，应该是让 Space 支持一个插槽才对。

**Comment by afc163** [comment]
```jsx
<Space divider={<Divider type="vertical" />}>
</Space>
```

这样？

**Comment by hengkx** [comment]
Space 本身也有垂直和水平 分割线也有这样不会很奇怪吗

**Comment by zombieJ** [comment]
List 里有个 `split` 属性，这个是不是可以名字一致？

**Comment by zombieJ** [comment]
> Space 本身也有垂直和水平 分割线也有这样不会很奇怪吗

垂直的的 Space 也可以用水平的 Divider

**Comment by hengkx** [comment]
设置后space中间的间距还生效吗

**Comment by zombieJ** [comment]
生效的，不过可能要调整一下。变成每个 Item 给半个间距。
