### ISSUE TITLE
How to use font listed: http://ant.design/docs/spec/font#字体家族

### ISSUE THREAD

**Issue by oeddyo** [ant-design/ant-design#2693]
Not really an issue but more of a question:

What shall I do to use the font family listed as in: http://ant.design/docs/spec/font#字体家族

Since I saw some examples, if you do:
```xml
                                <p className="ant-upload-text">点击或将文件拖拽到此区域上传</p>
                                <p className="ant-upload-hint">请上传</p
```
Then it uses the listed fonts. But what if I need a `<p></p>` to use the fonts?

Thanks

**Comment by ddcat1115** [comment]
Not sure what's your problem... If you has imported the `antd.css` as the example does: http://ant.design/docs/react/introduce#示例 , The font-family will be adopted on `body`.

**Comment by benjycui** [comment]
You don't need to care about how to use fonts, for antd.css will set it correctly. 

And this specification is a guide for designers, not programmers.

**Comment by oeddyo** [comment]
@benjycui Got it. Thanks!

**Comment by oeddyo** [comment]
Actually I'm doing all the work so... i'm a designer too 💃
