### ISSUE TITLE
Form.Item validation message is not used when help is set

### ISSUE THREAD

**Issue by RickMeasham** [ant-design/ant-design#26931]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/validate-message-not-used-when-help-is-present-bpkuk)

### Steps to reproduce
Create a `<Form.Item>` and specify a `help` attribute and validation `rules`. Add a rule that has a `message` attribute.

### What is expected?
When the rule is broken, the message will be shown to users in the error color.

### What is actually happening?
When the rule is broken the help text remains shown to users, but is highlighted in the error color

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | react latest (16  and 17rc) |
| System | Windows 10 |
| Browser | Chrome 85.0.4183.121 |

---
I suspect there is a fairly complex workaround for this where I can set the `help` to a dynamic value that checks the validation status of the field and sets help to `undefined` when the field is invalid. But this would be a workaround to a fairly obvious expectation of how help text and validation messages should work.

**Comment by RickMeasham** [comment]
This has already been done in the ticket report

**Comment by xrkffgg** [comment]
Maybe like https://github.com/ant-design/ant-design/issues/25560

**Comment by RickMeasham** [comment]
@xrkffgg It appears your request was similar

The issue I have with the call that it's "by design" is that the specificity is backwards and unintuitive. Validation is more specific than a help message because it outlines the specific reason the user's input is incorrect versus the help message which is a generic explanation of the field's purpose. 

`help` is for help when filling out the field. `rules` are for validating the users input. The fact that you can set the help as a validation message doesn't make it validation, it means that you're (ab)using the feature.

Call it "by design" and linking to a random example in the documentation doesn't explain the design principle. And without a design principle, "by design" just means "we wrote it that way" which can be said of any bug!

**Comment by zombieJ** [comment]
Sorry. Where is the reproduce?

**Comment by RickMeasham** [comment]
@zombieJ My apologies, it looks like I forgot to hit "Save". The link in the ticket now works and shows a simple example.

**Comment by zombieJ** [comment]
It's by design. `help` is final message controlled by develop to override any thing with the rule message. You can use `extra` prop to customize some additional info.

PS: `help` maybe not a good name, it better should be `feedback`. But we may not modify this currently.
