### ISSUE TITLE
Windows上的火狐使用拖拽上传功能无法正确阻止浏览器在新标签页打开文件

### ISSUE THREAD

**Issue by masontin** [ant-design/ant-design#26938]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-eyl39?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
使用window10   Firefox 浏览器（60 - 最新版本都可以）打开 [官网示例](https://ant.design/components/upload-cn/#components-upload-demo-drag)
拖放图片，至拖拽图片至 `拖放组件`

### What is expected?
不弹出tab页

### What is actually happening?
弹出了tab页

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 最新 |
| System | Windows 10 |
| Browser | 最新 |

---
请不要，为了关闭issue关闭issue，谢谢。麻烦自己动手测试下。

**Comment by masontin** [comment]
![firefox 81](https://user-images.githubusercontent.com/46433259/94516254-ffaefb00-0257-11eb-8419-884b06298917.gif)

**Comment by masontin** [comment]
![GIF 2020-9-29 13-33-00](https://user-images.githubusercontent.com/46433259/94516464-70561780-0258-11eb-9125-b6028cf805ec.gif)

**Comment by xrkffgg** [comment]
Duplicate of https://github.com/ant-design/ant-design/issues/26927

**Comment by afc163** [comment]
https://github.com/NG-ZORRO/ng-zorro-antd/issues/5828#issuecomment-698225079

**Comment by afc163** [comment]
手头没有 windows，方便帮忙排查然后发一个 PR 么？

我找了下可能的解决方案：

1. https://github.com/SortableJS/sortablejs/issues/985#issuecomment-282646581
2. https://blog.csdn.net/qq_31635925/article/details/89477545
3. https://blog.csdn.net/cysear/article/details/73740094

**Comment by masontin** [comment]
> SortableJS/sortablejs#985 (comment)
> https://blog.csdn.net/qq_31635925/article/details/89477545
> https://blog.csdn.net/cysear/article/details/73740094

这些解决方案，我都试过了，不是无效就是影响正常的上传功能。

@afc163 今晚我看下源码，看是否可以提交PR解决这个问题。

**Comment by masontin** [comment]
@afc163 我研究明白了，这个也不是firefox 本身的问题，大家可以看下[官方示例 `HTML_Drag_and_Drop_API`](https://mdn.mozillademos.org/zh-CN/docs/Web/API/Document/dragstart_event%24samples/%E7%A4%BA%E4%BE%8B%EF%BC%9Adropzone?revision=1547170)都存在这个问题。

## 所谓的 firefox feature
在Windows上的firefox，拖放任何可以拖动的元素都会打开新标签页。
> 我感觉这个被误解了，就是个扩展引起的 effect,根本不是新特性。

## 原因
因为是firefox默认带的一个插件的问题。

## 解决方案
取消勾选: 设置/附件组件/附加组件管理器/选项/启用拖拽手势

![图片](https://user-images.githubusercontent.com/46433259/94559540-fcd1fb80-0293-11eb-83fd-2dc866bc8b6d.png)



> 参考: [How to disable Drag-and-Search feature, It open too many unwanted tabs.](https://support.mozilla.org/en-US/questions/1071203)
- - -
被坑的同学，请大家举去报此插件，**滥用拖拽**。

**Comment by afc163** [comment]
赞 @masontin 的挖掘，这个扩展我在 https://addons.mozilla.org/zh-CN/firefox/ 没找到，是谋智版本 Firefox 自带的？

**Comment by masontin** [comment]
@afc163 是的， 在 [http://www.firefox.com.cn/](http://www.firefox.com.cn) 下载安装后就存在的，自带的。

- - - 
![图片](https://user-images.githubusercontent.com/46433259/94567054-a2d63380-029d-11eb-9df0-ba5cabce7c09.png)

**Comment by afc163** [comment]
谋智真是业界毒瘤

**Comment by masontin** [comment]
迅雷也是，去年我在`chrome`上每次按`Command`键，控制台就报错，找了很久的原因，后来发现是迅雷下载扩展引起的。

前端时间我本机`create-react-app` 刚初始化的项目，每次刷新控制台都报错，几天后发现，是一个`JSONParser`扩展引起的。
