### ISSUE TITLE
翻译错误导致的血案

### ISSUE THREAD

**Issue by jsoncode** [ant-design/ant-design#26934]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/](https://ant.design/components/input-cn/)

### Steps to reproduce
对比：https://ant.design/components/input-cn/

和

https://ant.design/components/input/

中文：
onSearch	点击搜索或按下回车键时的回调
英文：
onSearch The callback function triggered when you click on the search-icon, the clear-icon or press the Enter key

the clear-icon被漏掉，导致不可预知的问题

### What is expected?
中英文统一

### What is actually happening?
中文和英文不一致

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.1 |
| System | win |
| Browser | chrome |

**Comment by afc163** [comment]
PR is welcome
