### ISSUE TITLE
想请教下 script 引入的怎么中文化

### ISSUE THREAD

**Issue by hongcheng-choi** [ant-design/ant-design#26933]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
想请教下 script 引入的怎么中文化

### What does the proposed API look like?
想请教下 script 引入的怎么中文化

**Comment by afc163** [comment]
You need https://unpkg.com/browse/antd@4.6.6/dist/antd-with-locales.min.js
