### ISSUE TITLE
Antd Table Virtual list doesn't support 'render()' function in columns

### ISSUE THREAD

**Issue by tshan007** [ant-design/ant-design#26941]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gifted-glitter-j5wwb?file=/index.js)

### Steps to reproduce
Just follow the link above to reproduce.

### What is expected?
Cells in column 'A' should render according to the customised render() function with desired styles and elements.

### What is actually happening?
Table cells are only just div components.

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.12.0 |
| System | macOS 10.15.6 |
| Browser | Google Chrome Version 85.0.4183.121  |

**Comment by afc163** [comment]
https://codesandbox.io/s/magical-mayer-xmw99

**Comment by YakimchykNadzeya** [comment]
Does Antd Table Virtual list support editable cells?

**Comment by Chasen-Zhang** [comment]
https://codesandbox.io/s/xu-ni-lie-biao-antd-4-17-1-forked-0wn04?file=/index.js
same problem

**Comment by MartemyanovAleksandr** [comment]
![image](https://github.com/ant-design/ant-design/assets/77809743/720bd3ca-d8bc-45f1-9370-94b31e9cf8a0)

you have put 3 arguments in render, not 1, like this:

` let content = (rawData[rowIndex] as any)[(mergedColumns as any)[columnIndex].dataIndex];
          if ('render' in mergedColumns[columnIndex]) {
            content = (mergedColumns as any[])[columnIndex].render(content, rawData[rowIndex], rowIndex);
          };
`
