### ISSUE TITLE
希望提供下载图片的组件

### ISSUE THREAD

**Issue by XinYueXiao** [ant-design/ant-design#26944]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
图片下载

### What does the proposed API look like?
提供下载按钮，下载组件内的所有东西

**Comment by xrkffgg** [comment]
下图片可以用 a 标签啊。
其实没太明白你的意思

**Comment by afc163** [comment]
这个和 UI 库关系不大，用 a 链接就可以了。

**Comment by XinYueXiao** [comment]
就是div的下载
感觉有很多需求是要下载(进度组件的内容,图片加文字之类)
有的下载是用canvas实现的

**Comment by XinYueXiao** [comment]
并不是.png文件的下载
类似这个
https://juejin.im/post/6858076745745039367

**Comment by xrkffgg** [comment]
链接无效，其实还是没太明白你的需求点是啥
