### ISSUE TITLE
Chrome incognito mode, ellipsis not working

### ISSUE THREAD

**Issue by WaiKoeng** [ant-design/ant-design#26946]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/q7v6s?file=/src/index.tsx)

### Steps to reproduce
ctrl-shif-N open Chrome incognito mode, check the ellipsis effect

### What is expected?
ellipsis working good in Chrome incognito mode

### What is actually happening?
ellipsis not working in Chrome incognito mode; but working good in Chrome normal mode.

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.13.1 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by huntdream** [comment]
![image](https://user-images.githubusercontent.com/7903755/94632975-92a27080-02fe-11eb-8c6a-3b0048241bbd.png)
It works well, in my device

**Comment by zombieJ** [comment]
It works will in MAC. Who can help check on windows? cc @ant-design/ant-design-collaborators

**Comment by afc163** [comment]
Cannot reproduce, will reopen when report by others.
