### ISSUE TITLE
（Chrome浏览器）Popover 组件在JS调用全屏API（requestFullscreen）全屏显示当前页后无法显示Popover的内容

### ISSUE THREAD

**Issue by miaomiaoG** [ant-design/ant-design#26942]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/miaomiaog/pen/XWdQweg?editors=0011](https://codepen.io/miaomiaog/pen/XWdQweg?editors=0011)

### Steps to reproduce
点击全屏按钮,再将鼠标悬浮到 hover me 按钮，无法出现popover

### What is expected?
鼠标悬浮到 hover me按钮的时候出现popover的内容

### What is actually happening?
鼠标悬浮到 hover me按钮的时候没有popover的内容

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.12.0 |
| System | macos |
| Browser | chrome |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/9612#issuecomment-372649389
https://github.com/ant-design/ant-design/issues/7815#issuecomment-334913924
https://github.com/ant-design/ant-design/issues/7815#issuecomment-334913924
https://github.com/ant-design/ant-design/issues/24250
