### ISSUE TITLE
Form.Item子项获取不到select的value

### ISSUE THREAD

**Issue by yuandongx** [ant-design/ant-design#26959]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://XXX.XXXX.com](http://XXX.XXXX.com)

### Steps to reproduce

const TheForm =({form})=>{
    const [platform, setPlatform] = useState();
    return (
      <Form form={form} labelCol={{ span: 5 }} wrapperCol={{ span: 12 }}>
        <Form.Item label="设备类型" name='platform' rules={[{ required: true, message: '请选择设备类型' }]}>
            <Select placeholder="选择设备类型...">
              <Option value="asa">asa</Option>
              <Option value="topsec">topsec</Option>
            </Select>,
        </Form.Item>
        <Form.Item required
            label="对象名称"
            name="name"
            rules={[{ required: true, message: '请输入对象名称!' }]}>
              <Input placeholder="请输入对象名称!"/>
        </Form.Item>
        
        <Form.Item wrapperCol={{ span: 12, offset: 5 }}>
          <Button type="primary" >
            配置预览
          </Button>
        </Form.Item>
      </Form>
    );
}
const TheModal = () => {
    const [form] = Form.useForm();
    const handleSubmit =()=>{
        console.log(form.getFieldsValue());
    }
    return(
      <Modal
        visible
        width={800}
        maskClosable={false}
        title={'编辑地址对象'}
        // confirmLoading={tloading}
        // onCancel={() => store.formFlag = null}
        onOk={handleSubmit}
        >
        <TheForm form={form}/>
      </Modal>
    );
}
export default TheModal;

### What is expected?
Form.Item 关联的select， form.geFeildsValuet可以获取对应的值

### What is actually happening?
没有值

| Environment | Info |
|---|---|
| antd | 4.0.0 |
| React | "react": "^16.11.0",     "react-ace": "^8.0.0",     "react-dom": "^16.11.0",     "react-router-dom": "^5.1.2",     "react-scripts": "3.2.0", |
| System | ubuntu20 |
| Browser | Google Chrome 版本 83.0.4103.106（正式版本） （64 位） |

---
内网服务器，不可达

![image](https://user-images.githubusercontent.com/35824522/94642892-1452c800-0318-11eb-9685-8e9a01ed521f.png)

```

const TheForm =({form})=>{
    const [platform, setPlatform] = useState();
    return (
      <Form form={form} labelCol={{ span: 5 }} wrapperCol={{ span: 12 }}>
        <Form.Item label="设备类型" name='platform' rules={[{ required: true, message: '请选择设备类型' }]}>
            <Select placeholder="选择设备类型...">
              <Option value="asa">asa</Option>
              <Option value="topsec">topsec</Option>
            </Select>,
        </Form.Item>
        <Form.Item required
            label="对象名称"
            name="name"
            rules={[{ required: true, message: '请输入对象名称!' }]}>
              <Input placeholder="请输入对象名称!"/>
        </Form.Item>
        
        <Form.Item wrapperCol={{ span: 12, offset: 5 }}>
          <Button type="primary" >
            配置预览
          </Button>
        </Form.Item>
      </Form>
    );
}
const TheModal = () => {
    const [form] = Form.useForm();
    const handleSubmit =()=>{
        console.log(form.getFieldsValue());
    }
    return(
      <Modal
        visible
        width={800}
        maskClosable={false}
        title={'编辑地址对象'}
        // confirmLoading={tloading}
        // onCancel={() => store.formFlag = null}
        onOk={handleSubmit}
        >
        <TheForm form={form}/>
      </Modal>
    );
}
export default TheModal;
```

**Comment by yoyo837** [comment]
请提供在线复现。

**Comment by xiaoguli** [comment]
父组件中：
   <Form.Item
          name="failReceivers"
          label="失败通知"
          rules={[{ required: true, message: '请选择失败信息通知人!' }]}
          style={{ height: '70px' }}
        >
          <SelectUsers
            marginTop="35px"
            placeholder="可从系统中选择已经添加邮箱的用户"
            allUsers={allUsers}
          />
   </Form.Item>

子组件中：
interface Iprops {
  marginTop: string;
  placeholder: string;
  allUsers: userInfo[];
}

const SelectUsers: React.FC<Iprops> = (props) => {
  const { Option } = Select;
  const { marginTop, placeholder, allUsers } = props;
  return (
    <>
      <Select
        placeholder={placeholder}
        style={{ marginTop: marginTop }}
        mode="multiple"
        allowClear
      >
        {allUsers.map((user, index) => {
          return (
            <Option value={user.name} key={index}>
              {user.name} ( {user.loginAccount} )
            </Option>
          );
        })}
      </Select>
    </>
  );
};
export default SelectUsers;

问题：表单提交时无法获取select选中的值，failReceivers始终是undefined

**Comment by s97712** [comment]
+1
