### ISSUE TITLE
ant design form async-validator warning

### ISSUE THREAD

**Issue by kingjam3s** [ant-design/ant-design#26953]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8gimz)

### Steps to reproduce
Submit a form with rules

### What is expected?
no warnings

### What is actually happening?
console warning like this: async-validator: ["Please enter username"].

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | Windows 10.0.18363 |
| Browser | Google Chrome 85.0.4183.121 |

**Comment by afc163** [comment]
It is intented behavior.

**Comment by biruelrick** [comment]
Put this line in App.js, after last import instruction

`global.ASYNC_VALIDATOR_NO_WARNING = 1;`
