### ISSUE TITLE
v4版本Table组件 Object.defineProperty(obj, 'scrollLeft',{...})的作用是什么

### ISSUE THREAD

**Issue by lxsunbin** [ant-design/ant-design#26957]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
	Object.defineProperty(obj, 'scrollLeft', {
			get: () => null,
			set: scrollLeft => {
				if (gridRef.current) {
					gridRef.current.scrollTo({
						scrollLeft
					});
				}
			}
		});

这段代码具体起了什么作用呢，我删除这段代码Table也能正常运行，求解

### What does the proposed API look like?
希望增加相应地说明

**Comment by zombieJ** [comment]
Table 标题滚动的时候，同步 Grid 滚动
