### ISSUE TITLE
Cascader loading icon direction in RTL

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#26958]
- Link: https://ant.design/components/cascader/#components-cascader-demo-lazy

In LTR, when you expand, the loading icon is clockwise. The panel expands from left to right.

In RTL, the panel expands from right to left. 

@israelKusayev @saeedrahimi

Hi, I want to ask for your opinion, if the loading icon is 

still 
- [ ] clockwise 

or 
- [x] counter-clockwise ?

**Comment by jueinin** [comment]
you mean if current direction is RTL, the loading icon should be counter-clockwise?

**Comment by xrkffgg** [comment]
I wonder if the rotation direction of the icon is the same as that of panel expands ?

**Comment by xrkffgg** [comment]
cc @israelKusayev @saeedrahimi

**Comment by saeedrahimi** [comment]
it could be better with counter-clockwise loading for RTL.

**Comment by saeedrahimi** [comment]
https://ant.design/components/spin/?direction=rtl#components-spin-demo-size
spin component is also counter-clockwize

**Comment by xrkffgg** [comment]
Thx
