### ISSUE TITLE
upload中是否可以调用function取代action

### ISSUE THREAD

**Issue by oeddyo** [ant-design/ant-design#2695]
I'm currently trying to use a SDK to upload files (specifically I'm using LeanCloud). However it seems in the "upload" module, I have to specify "action" string, which, if I understand correctly, is a post address. 

I'm wondering is there any way I can specify a function instead of this post address?

Thanks

**Comment by oeddyo** [comment]
求问，如果在upload中提交的时候，需要调用sdk而不是一个http post的话，应该怎么写呢？

(action是必要参数，好像没有办法不给）

**Comment by afc163** [comment]
具体的调用需求是？

**Comment by afc163** [comment]
We do not support sdk call in Upload now, you can give us reasonable PR to [rc-upload](http://github.com/react-component/upload).
