### ISSUE TITLE
Support alternative input types for AutoComplete component

### ISSUE THREAD

**Issue by rizkysyazuli** [ant-design/ant-design#26950]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
HTML has several input types like `email`, `number`, or `tel` that allows alternative keyboard inputs to be shown to the user. The AutoComplete component should be able to accommodate this feature.

### What does the proposed API look like?
The component should accept a `type=value` prop that should be passed on directly as `<input type="value" />`.

**Comment by afc163** [comment]
```jsx
<AutoComplete>
  <Input type="email" />
</AutoComplete>
```
