### ISSUE TITLE
Popover不支持style和className属性么？

### ISSUE THREAD

**Issue by liujhfly** [ant-design/ant-design#2696]
#### 本地环境

- antd 版本: 1.6.4
- 操作系统及其版本：mac
- 浏览器及其版本: chrome

#### 你做了什么？
引入气泡卡片Popover
import {Popover} from "antd";
#### 你期待的结果是：

气泡卡片内容比较多，希望能通过增加样式或类名来控制显示的宽度等内容;

#### 实际上的结果：
气泡卡片正常显示出来，但是
气泡卡片没有显示在<Popover>上增加的样式或是类名

**Comment by afc163** [comment]
`<Popover content={<div className="xxx"></div>}>`

**Comment by liujhfly** [comment]
thanks
