### ISSUE TITLE
Notification能否支持在顶部中间提示，像Message一样，还有就是能否提供不同级别如warn，info它们的背景颜色像Alert一样

### ISSUE THREAD

**Issue by Silentdoer** [ant-design/ant-design#26967]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
四个边角提示不太明显，中上即明显也不容易遮挡当前功能，不用message是因为message太小而且不支持手动关闭；然后Notification貌似目前的背景颜色都是白色的，不像alert一样error就是红色的背景，info是蓝色背景。

### What does the proposed API look like?
除了left，right，top，bottom增加top-middle，然后增加背景属性如bg-level是error则是红色背景。

**Comment by xrkffgg** [comment]
感觉可以通过 `className` `style` 自定义实现了

**Comment by afc163** [comment]
Notification 设计上就需要在边角，请使用 message。另外 message 支持手动关闭。
