### ISSUE TITLE
Add a prop to copyable to have the icon before the text

### ISSUE THREAD

**Issue by guillaumegaluz** [ant-design/ant-design#26975]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A common UX pattern when copying some text or a link is to have the copy icon before the text (because it can be of variable length). [Something like this](https://share.getcloudapp.com/mXu6oLdk).

some users want:  
`some text that you want to copy   ICON`

while some users might prefer:  
`ICON   some text that you want to copy`

If you want the second option, it's currently very hard to use the existing Ant Design's `Typography   copyable` to achieve this.

### What does the proposed API look like?
i'm suggesting that copyable could have an extra prop to swap icon and text:

```
copyable={{
  ...
  iconFirst: true,
}}
```

**Comment by afc163** [comment]
Try https://codesandbox.io/s/mystifying-frog-likny?file=/index.js
