### ISSUE TITLE
v4版本Table组件 Object.defineProperty(obj, 'scrollLeft',{...})删除也没影响？

### ISSUE THREAD

**Issue by lxsunbin** [ant-design/ant-design#26974]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Object.defineProperty(obj, 'scrollLeft', {
		get: () => null,
		set: scrollLeft => {
			if (gridRef.current) {
				gridRef.current.scrollTo({
					scrollLeft
				});
			}
		}
	});

这段代码开发者解释是“Table 标题滚动的时候，同步 Grid 滚动”，但是我删除了这段代码也可以“Table 标题滚动的时候，同步 Grid 滚动”，这是为什么啊？

### What does the proposed API look like?
为什么删除这段代码Table也能正常运行，求解

**Comment by yoyo837** [comment]
请问你要反馈什么问题，阅读代码的疑惑更多的还是需要自行消化。

**Comment by lxsunbin** [comment]
> 请问你要反馈什么问题，阅读代码的疑惑更多的还是需要自行消化。

好的，我再研究研究
