### ISSUE TITLE
Popover 和 Menu 组合使用时, SubMenu 的显示问题

### ISSUE THREAD

**Issue by xiaoYuanDun** [ant-design/ant-design#26970]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/popover-menu-zuhewentichongxian-qenvu?file=/index.js)

### Steps to reproduce
需求是要自定义下拉菜单, 最初使用的是 Dropdown, 但 Dropdown不支持自定义 content , 所以选择了 Popover
这时问题出现了,
Popover 的 content 是一个组合的多级菜单，由 Menu, ItemGroup, SubMenu, Item 组合而成
当其中一个 SubMenu 的子菜单数量较大时, 鼠标移到某个菜单项上方，其对应的子菜单不会显示在右侧，而鼠标离开此菜单项时，其右侧子菜单会一闪而过

### What is expected?
期望可以正常显示右侧子菜单

### What is actually happening?
子菜单数量较大时，显示有明显问题，Hover 时不显示，Leave 时一闪而过

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.12.0 |
| System | window 10 pro |
| Browser | chrome  85.0.4183.121 |

---
测试数据已经放在重现地址，测试后发现不全是由子菜单数量引起的

**Comment by tianwangwen** [comment]
Dropdown SubMenu也存在这个问题

**Comment by chendanping** [comment]
@xiaoYuanDun  请问这个问题解决了吗，我也遇到了同样的问题

**Comment by Kermit-Xuan** [comment]
@chendanping 试试这个是不是没有问题？

**Comment by chendanping** [comment]
> @chendanping 试试这个是不是没有问题？

哪一个。。

**Comment by Kermit-Xuan** [comment]
> > @chendanping 试试这个是不是没有问题？
> 
> 哪一个。。

https://codesandbox.io/s/popover-menu-zuhewentichongxian-forked-rwqes 这个 sorry

**Comment by Kermit-Xuan** [comment]
用的 `antd@4.4.0` 看看是不是好着

**Comment by chendanping** [comment]
> 用的 `antd@4.4.0` 看看是不是好着

你这个问题也还是在的呀，最后一个菜单项就是leave的时候闪现，你看看

**Comment by Kermit-Xuan** [comment]
![Oct-22-2020 13-16-52](https://user-images.githubusercontent.com/33770367/96827805-f553db80-1468-11eb-9a81-c48e8e7face4.gif)

并没有你说的出不来的情况😂

**Comment by xiaoYuanDun** [comment]
> @xiaoYuanDun 请问这个问题解决了吗，我也遇到了同样的问题

暂时没有解决，拉了源码再调，不过优先级不高，这几天忙完了接着调

**Comment by xiaoYuanDun** [comment]
> > > @chendanping 试试这个是不是没有问题？
> > 
> > 
> > 哪一个。。
> 
> https://codesandbox.io/s/popover-menu-zuhewentichongxian-forked-rwqes 这个， sorry 忘发了

我试了一下这个 repo，确实是正常的哈哈，是已经在新版本中解决了吗？

**Comment by Kermit-Xuan** [comment]
> > > > @chendanping 试试这个是不是没有问题？
> > > 
> > > 
> > > 哪一个。。
> > 
> > 
> > [codesandbox.io/s/popover-menu-zuhewentichongxian-forked-rwqes](https://codesandbox.io/s/popover-menu-zuhewentichongxian-forked-rwqes) 这个， sorry 忘发了
> 
> 我试了一下这个 repo，确实是正常的哈哈，是已经在新版本中解决了吗？

不是，是不确定在哪个版本开始复现的😂

**Comment by tianwangwen** [comment]
我用的@4.7.0,Dropdown也存在这个问题

**Comment by Kermit-Xuan** [comment]
因为 4.4.1 的时候对 menu 进行了重构，好多功能都移动到了 `rc-menu`，所以我才看看 4.4.0 是不是好的，所以大家谁有时间的话可以看看这个问题是从哪个版本开始复现的，方便定位问题，我现在只能一点点去定位。

**Comment by xiaoYuanDun** [comment]
> 因为 4.4.1 的时候对 menu 进行了重构，好多功能都移动到了 `rc-menu`，所以我才看看 4.4.0 是不是好的，所以大家谁有时间的话可以看看这个问题是从哪个版本开始复现的，方便定位问题，我现在只能一点点去定位。

**Comment by Kermit-Xuan** [comment]
等 https://github.com/react-component/menu/pull/346 这个发了版本后试一试有没有好使。

**Comment by hadnet** [comment]
I'm using antd 4.7.3 and SubMenu doesn't close when mouse leaves out. When using antd 4.4.0 it does works!

**Comment by xiaoYuanDun** [comment]
> 等 [react-component/menu#346](https://github.com/react-component/menu/pull/346) 这个发了版本后试一试有没有好使。

ok，今天发完版我测一下

**Comment by nuintun** [comment]
响应布局收缩有点问题，闪屏问题还是有的。 [#26905](https://github.com/ant-design/ant-design/issues/26905#issuecomment-720819405)
