### ISSUE TITLE
Typescript error for <Slider step={null} />

### ISSUE THREAD

**Issue by ranbena** [ant-design/ant-design#26976]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-slider-step-null-l1h1i?file=/src/containers/App/index.tsx)

### Steps to reproduce
Create `<Slider>` with prop `step={null}` and typescript yields an error that "null" is not an acceptable value.

### What is expected?
That "null" value IS an acceptable value.
According to the docs it has a special meaning, and there's even an example in the AntD site with it - https://codesandbox.io/s/jxny9

### What is actually happening?
In https://github.com/ant-design/ant-design/pull/26884 (v4.6.6) the ts definition was wrongly changed from `step?: number | null` to `step?: number`.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome |

---
🔔 Probably was undetected since the error appears for `--strictnullchecks`/`strict: true` in tsconfig.json.

**Comment by ranbena** [comment]
@Kermit-Xuan plz revert this line

https://github.com/ant-design/ant-design/blob/216337219654315e6868317caafe9a750ce222ad/components/slider/index.tsx#L35

**Comment by Kermit-Xuan** [comment]
you can use ‘null!’

**Comment by ranbena** [comment]
I'm afraid that's not true for typescript configured with [strict null checks](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#--strictnullchecks).

[This example](https://codesandbox.io/s/antd-slider-step-null-l1h1i?file=/src/containers/App/index.tsx) clearly demonstrates the typescript error on the Slider component.
