### ISSUE TITLE
autoFocus doesn't exists anymore in Slider? 

### ISSUE THREAD

**Issue by yeomann** [ant-design/ant-design#26982]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/slider/](https://ant.design/components/slider/)

### Steps to reproduce
see the API section of https://ant.design/components/slider/

### What is expected?
autoFocus props to work

### What is actually happening?
autoFocus doesn't exists

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Ubuntu |
| Browser | Chrome |

![image](https://user-images.githubusercontent.com/5970751/94810348-91576d80-03fc-11eb-8e84-2b4978086988.png)
![image](https://user-images.githubusercontent.com/5970751/94810492-bf3cb200-03fc-11eb-8928-e35a6be79d92.png)

**Comment by shangyilim** [comment]
indeed upon checking, the underlying `RcSlider` supports autoFocus, whats lacking here is just the type definition. I have submitted a PR to fix this
