### ISSUE TITLE
Column renders a filter button if filterDropdown is set to undefined

### ISSUE THREAD

**Issue by Jaxsun** [ant-design/ant-design#26988]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-f77ph?file=/index.js)

### Steps to reproduce
create a Table and pass in undefined as the filterDropdown on any column

### What is expected?
no filter button should appear for that column header

### What is actually happening?
a filter button appears, when clicked it shows that no filters are available

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | Ubuntu 18.04 |
| Browser | Firefox 80.0.1 |

---
This worked as expected with Ant 3

**Comment by shangyilim** [comment]
@Jaxsun Why even include `filterDropdown` if you don't want it to be visible? Would like to understand the use case here

**Comment by Jaxsun** [comment]
We had some generic code which produced Columns for us, under certain conditions we wanted to specify a filterDropdown so we had something kind of like this.

```
<Column filterDropdown={condition ? renderFilterDropdown() : undefined} />
```

We were specifying a lot of things on the column so duplicating it wasn't really an option, ie.

```
if (condition) {
 return <Column filterDropdown={renderFilterDropdown()} />
} else {
 return <Column />
}
```

We worked around the issue by using spread which is kind of janky but acceptable for now

```
val filterProps: Partial<ColumnProps<any>> = {}
if (condition) {
 filterProps.filterDropdown = renderFilterDropdown()
}
return <Column {...filterProps} />
```

**Comment by Jaxsun** [comment]
Thanks for taking this on so quickly!
