### ISSUE TITLE
一个变量可以给它赋值不同的组件吗？目前这样设置会报错

### ISSUE THREAD

**Issue by qiannianv** [ant-design/ant-design#2698]
#### 本地环境

- antd 版本:1.8.0
- 操作系统及其版本：
- 浏览器及其版本:谷歌

#### 可重现的在线演示
http://codepen.io/anon/pen/akPgZV?editors=001

**Comment by ddcat1115** [comment]
删一下无关代码再调吧，现在的demo里问题很多

参考：http://codepen.io/ddcat1115/pen/rLoXoJ?editors=001

**Comment by afc163** [comment]
不知道什么意思，你的在线演示里确实很多问题。

It will be better if you read [smart questions](http://www.catb.org/~esr/faqs/smart-questions.html)([提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way)).
