### ISSUE TITLE
Need to attribute to expand the dropdown of Select React so it spreads to the left  the Select react component 

### ISSUE THREAD

**Issue by ronenwo** [ant-design/ant-design#26981]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I have a Select on the right side of the window. 
When the dropdown opens with long lines, I need the dropdown to stretch fully according to widest line and expand to the left. 

### What does the proposed API look like?
dropdownExpandDirection : left | right

**Comment by afc163** [comment]
https://codesandbox.io/s/sad-rain-o8cl2?file=/index.js

https://codesandbox.io/s/sad-rain-o8cl2?file=/index.js
