### ISSUE TITLE
Optional number handler for `Input type="number"`

### ISSUE THREAD

**Issue by LilyMGoh** [ant-design/ant-design#26997]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
First of all, thank you for OS this project. It has been working great! I have a feature suggest/question that I need clarification:

In some contexts, it does not make a lot of sense for number input to have an up/down handler, for example, if the expected input is specific and large like monthly income or a percentage with "%" suffix. As far as I'm aware of Ant doesn't allow configuration for this to happen. When I tried removing `.rc-input-number-handler-wrap` in [Storybook](http://react-component.github.io/input-number/examples?path=/story/rc-input-number--custom) it works as expected but I couldn't find a way to config in my codebase. Is there a way? Thanks!

### What does the proposed API look like?
Allows number input with no up/down handler

**Comment by afc163** [comment]
https://stackoverflow.com/questions/3790935/can-i-hide-the-html5-number-input-s-spin-box
