### ISSUE TITLE
Image Component Style Not Applying to Underlying Image

### ISSUE THREAD

**Issue by Rocinante89** [ant-design/ant-design#26996]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jh6yf)

### Steps to reproduce
Create an Image component with a style prop containing objectFit: 'cover. The styles are being applied to the parent div instead of the image.

https://jh6yf.csb.app/

### What is expected?
Styles passed to the style prop should apply to the underlying image

### What is actually happening?
The styles are being applied to the parent div

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | latest |
| System | win 10 |
| Browser | Chrome - latest |

**Comment by jueinin** [comment]
@shaodahong how to do this? split style prop to wrapperStyle and imageStyle? I can provide a PR if you have a good solution on it.

the problem is here -> **https://github.com/react-component/image/blob/master/src/Image.tsx#L124**

**Comment by shaodahong** [comment]
> @shaodahong how to do this? split style prop to wrapperStyle and imageStyle? I can provide a PR if you have a good solution on it.
> 
> the problem is here -> **https://github.com/react-component/image/blob/master/src/Image.tsx#L124**

yep, the default `style` and `wrapperStyle`, className maybe also

**Comment by Rocinante89** [comment]
Any update on this?
