### ISSUE TITLE
collapsedWidth is broken

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#26992]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-sejf5?file=/index.js)

### Steps to reproduce
set collapsedWidth to 50

### What is expected?
collapsedWidth should change all items inside sider

### What is actually happening?
![image](https://user-images.githubusercontent.com/42112796/94909740-4d23a600-04ac-11eb-9e33-99afc05b66c3.png)

collapsedWidth isn't changing all items inside sider

I saw this issue https://github.com/ant-design/ant-design/issues/11422 and your answer @afc163 

but I think the library should do it, I don't have override less file (I'm using create react app and I don't want to add 2 npm packages just for it), or at least specify it in the docs.

thanks 🤍

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.0 |
| System | windows 10 |
| Browser | chrome 85 |

**Comment by israelKusayev** [comment]
ohh wait, I see there is `collapsedWidth` property in menu for this propose, but rc-menu doesnt do anything with it
![image](https://user-images.githubusercontent.com/42112796/95001332-915c9680-05d1-11eb-81a9-2216d28742d1.png)


![image](https://user-images.githubusercontent.com/42112796/95001347-adf8ce80-05d1-11eb-952b-0fefb6160b27.png)

**Comment by jueinin** [comment]
the `collapsedWidth` seems only work on hidden menu.

**Comment by israelKusayev** [comment]
@afc163  Please reopen bug, still not working.

**Comment by yoyo837** [comment]
Could you provide an new online reproduction demo?
