### ISSUE TITLE
antd Modal.success弹出一个使用useIntl的组件时报错了：[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry

### ISSUE THREAD

**Issue by effapp** [ant-design/ant-design#26990]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://no.test.com](https://no.test.com)

### Steps to reproduce
antd Modal.success弹出一个使用useIntl的组件时报错了：[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry

### What is expected?
不要报错

### What is actually happening?
antd Modal.success弹出一个使用useIntl的组件时报错了：[React Intl] Could not find required `intl` object. <IntlProvider> needs to exist in the component ancestry

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8.6 |
| System | win2012 |
| Browser | chrome |

**Comment by afc163** [comment]
Try https://ant.design/components/modal/#components-modal-demo-hooks

https://ant.design/components/modal/#Why-I-can-not-access-context,-redux-in-Modal.xxx
