### ISSUE TITLE
defaultExpandParent and autoExpandParent failed to work when tree has a depth greater than 2

### ISSUE THREAD

**Issue by otakustay** [ant-design/ant-design#26999]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/laughing-rhodes-efw1e?file=/src/App.js:6938-7002)

### Steps to reproduce
See sandbox

### What is expected?
Like the line commented, providing a leaf node's key to defaultExpandedKeys should expand all its parent when defaultExpandParent is enabled

### What is actually happening?
Tree is collapsed

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | macOS 10.15.6 |
| Browser | Chrome 85.0.4183.121 |

**Comment by zombieJ** [comment]
It's [by design](https://github.com/react-component/tree/blob/15bc7436282ae9808e419c08aa083e1110797d16/src/util.tsx#L166) not to conduct status to parent when `disabled`.

But you can update status as workaround: https://codesandbox.io/s/hopeful-dubinsky-uwx7r?file=/src/App.js
