### ISSUE TITLE
Popover组件在react中无法使用

### ISSUE THREAD

**Issue by yirenliancheng** [ant-design/ant-design#27007]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/yirenliancheng/Data-Visualization/tree/dev](https://github.com/yirenliancheng/Data-Visualization/tree/dev)

### Steps to reproduce
npm install; npm run start; footer中的微信Icon，无法触发hover，用了官网文档的示例也不能复现。

### What is expected?
当鼠标移动到微信icon时，可以出现一个气泡

### What is actually happening?
无法出现气泡

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.8.3 |
| System | win10 |
| Browser |  Chrome 85.0.4183.121 |

**Comment by jueinin** [comment]
确实是没效果，不知道啥原因
