### ISSUE TITLE
Error in Select when filterOptions doesn't return any matches

### ISSUE THREAD

**Issue by nrayburn-tech** [ant-design/ant-design#27006]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-uuekv?file=/index.js)

### Steps to reproduce
1. Open the sandbox link
2. Type any character into the select input
3. Error is thrown

### What is expected?
The `No Data` item should be displayed.

### What is actually happening?
If the `filterOptions` does not return true for any option, an error is thrown.
`Uncaught TypeError: Cannot read property 'removeEventListener' of null`

I wasn't really sure how to copy a well formatted stack trace from the console, but it can be seen when running the sandbox.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | React 17.0.0-rc.2 |
| System | macOS 10.15.7 |
| Browser | Brave Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit) |

---
This occurs with 17.0.0-rc.2, it does not occur with 16.13.1.
Related to https://github.com/ant-design/ant-design/issues/26136 for React 17 compatibility.

**Comment by jueinin** [comment]
I have figure out where the problem is. I will provide a PR after a while.  According to the [doc](https://reactjs.org/blog/2020/08/10/react-v17-rc.html#effect-cleanup-timing) we should use `useLayoutEffect` replace `useEffect` to make sure the cleanup function runs before unmount.
