### ISSUE TITLE
在表格组件中，【expandedRowRender，expandIcon，expandRowByClick】三个属性一起使用的问题

### ISSUE THREAD

**Issue by caohuiboss** [ant-design/ant-design#27008]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-c1e8h?file=/index.js)

### Steps to reproduce
可以观看重现链接，你会发现虽然expandIcon属性已经将左侧加号隐藏了，但是原先展开的加号所占的位置是还在的

### What is expected?
我期望的结果肯定是能点击行展开，且隐藏加号包括它所占的位置，比如姓名是第一列，并非是我已经设置成隐藏的加号为第一列

### What is actually happening?
实际结果：虽然expandIcon属性已经将左侧加号隐藏了，但是原先展开的加号所占的位置是还在的

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | react |
| System | win10/mac |
| Browser | 谷歌最新 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-z4z4o

**Comment by caohuiboss** [comment]
非常感谢，在react此方法是解决了问题的，但是在vue中我同样提了相同的issue，使用了你这边提供的并没有解决呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "偏右"<notifications@github.com&gt;; 
发送时间: 2020年10月8日(星期四) 下午4:10
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;; 
抄送: "曹辉"<2550465923@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ant-design/ant-design] 在表格组件中，【expandedRowRender，expandIcon，expandRowByClick】三个属性一起使用的问题 (#27008)





 
Try this way: https://codesandbox.io/s/antd-reproduction-template-forked-z4z4o

**Comment by afc163** [comment]
不了解 vue 的情况，建议去对应仓库反馈。
