### ISSUE TITLE
Scrolling in Select on iPhone/iPad does not work

### ISSUE THREAD

**Issue by Danielv123** [ant-design/ant-design#27011]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/strange-swanson-u7ggf)

### Steps to reproduce
Click in input element and scroll the list. 

### What is expected?
The list scrolls naturally

### What is actually happening?
The scroll will end up targeting the page as well as the list, leading to unacceptable behaviour.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.10 |
| System | iPhone/iPad |
| Browser | Latest |

---
We have only been testing on windows, android and macos devices using browser developer tools, and choosing iPad as emulated device is not enough to reproduce the issue. This issue makes our site totally unusable from iPhones. We will try to work around it using <Picker> from antd-mobile. The select component in 3.26 works fine, but downgrading is not an option at this point.

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/26480#issuecomment-691856053

**Comment by paciustanislav** [comment]
This bug is actually.
