### ISSUE TITLE
菜单展开或者收缩响应速度问题

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design#2701]
为何Menu组件的展开和收缩会那么慢，官网左侧菜单就是例子

**Comment by afc163** [comment]
官网确实有点慢。Menu 的演示我看着应该还行？

**Comment by dai875939260** [comment]
演示的还行，之前github看的一个项目的例子也是慢，响应都要4到5s的样子

**Comment by afc163** [comment]
貌似和 react-router 配合的缘故。

**Comment by dai875939260** [comment]
@afc163 额,好像的确都是用了 react-router

**Comment by jljsj33** [comment]
官网的左侧展开和收缩是事件没触发，点了之后鼠标放着不动是永。。。移出了 lits 刷新 props 了才执行动画的。。不是响应慢的问题

**Comment by benjycui** [comment]
的确是要鼠标移开才开始执行动画。

@jljsj33 无法优化？

**Comment by jljsj33** [comment]
这里的问题吧。。。shouldComponentUpdate

**Comment by wadeDra** [comment]
我也碰到了打开缓慢的问题，不过我没有使用router，但是在里面添加了配置项openKeys，在部分电脑上打开比较缓慢。对了，也出现了点击后，鼠标移开才可以展开的问题。

**Comment by benjycui** [comment]
`rc-menu` 的问题受控模式下还是会响应用户操作，而且是在 `onMouseLeave` 时响应。

**Comment by jljsj33** [comment]
不知道啥情况。。。排查了下，，看到这里是直接等于的。。。改成this.setState就没事了。。。。。https://github.com/react-component/menu/blob/master/src/Menu.jsx#L151 ，

**Comment by benjycui** [comment]
ref: https://github.com/ant-design/ant-design/issues/1600

**Comment by afc163** [comment]
https://github.com/react-component/menu/pull/48

**Comment by afc163** [comment]
主站问题还是没法修复，老的 rc-menu 发个 fix 版本？

**Comment by benjycui** [comment]
之前的版本不好修 https://github.com/react-component/menu/pull/48

**Comment by benjycui** [comment]
然后应该可以等 2.0 发布？毕竟不是功能性的  bug。。

**Comment by batouy** [comment]
收藏一下
