### ISSUE TITLE
InputNumber allows typing the letter "e" and "E" when type='number'

### ISSUE THREAD

**Issue by Gia1987** [ant-design/ant-design#27014]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/keen-sea-yd9qj?file=/src/App.js)

### Steps to reproduce
Simply type 'e' or 'E' into the input

### What is expected?
It shouldn't allow you to type letters a-z- A-Z or special characters, only numbers 0-9.

### What is actually happening?
You can type 'e' or 'E' along with the numbers

| Environment | Info |
|---|---|
| antd | 3.25.0 |
| React | 16.13.1 |
| System | Ubuntu 18.04.5 LTS |
| Browser | Brave 1.14.84, Firefox  81.0 |

---
I'm using 3.25.0, but it seems that even the last version 4.6.6 is affected.

**Comment by m-weeks** [comment]
The specification for floating point numbers allows the letter 'e' for exponents Like `1.23e4`, which would be why it's allowed.

https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#floating-point-numbers

**Comment by Gia1987** [comment]
I see now, Thanks @m-weeks for the answer. I ll close this issue.
