### ISSUE TITLE
Problem of sub menus not being stable when opening in vertical mode

### ISSUE THREAD

**Issue by huseyingoztok** [ant-design/ant-design#27016]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pdhed?file=/index.js)

### Steps to reproduce
https://www.loom.com/share/c677229bd2a84426a986400084275cf0

### What is expected?
Stability when opening sub menus.

### What is actually happening?
Sub menus not being stable when opening in vertical mode

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.12.0 |
| System | Windows 10 |
| Browser | Google Chrome |

**Comment by huseyingoztok** [comment]
In addition, it would be nice if the sub menus in vertical mode opening with the feature of hovering.

**Comment by afc163** [comment]
Should have been fixed in https://github.com/ant-design/ant-design/issues/27016
