### ISSUE TITLE
Slider tooltips not hidden on other tabs

### ISSUE THREAD

**Issue by HakimMliki-Incedo** [ant-design/ant-design#27019]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6loin?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
- create tabs with ant design
- add a slider in one fo them with `tooltipVisible ` on true
- change to an other tab by clicking on it
=> the tooltips keep showing 

### What is expected?
the tooltips of the slider to disappear on the other tabs

### What is actually happening?
the tooltips of the slider keeps showing on other tabs

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | react latest (17.0.0-rc.2) |
| System | macOs Catalina version 10.15.6 |
| Browser | Google Chrome -  Version 85.0.4183.121 (Official Build) (64-bit) / Firefox 80.0.1 (64-bit) |

### screenshots

![image](https://user-images.githubusercontent.com/60227521/95237101-103b1480-0808-11eb-9900-7f4b20624121.png)
![image](https://user-images.githubusercontent.com/60227521/95237141-1b8e4000-0808-11eb-83f7-236aac290703.png)

**Comment by afc163** [comment]
Try `getTooltipPopupContainer`.

https://codesandbox.io/s/antd-reproduction-template-forked-jbdje?file=/index.js
