### ISSUE TITLE
TreeSelect的弹出框能一直显示么

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#2702]
需求是，需要一个可通过输入的文本过滤节点的Tree控件。
普通Tree控件好像没有过滤的API，除非自己根据输入框输入项，过滤数据后重新生成TreeNode；
TreeSelect已经有了过滤的API，可是我想让TreeSelect的下拉面板一直显示，这个貌似可以通过样式控制？
还在尝试中，希望能给点指导建议。

谢谢

**Comment by wufeng87** [comment]
样式不好弄啊，还有动画效果。

**Comment by warmhug** [comment]
用`onDropdownVisibleChange`，文档里没写出来，觉得不常用。示例和代码见此：http://react-component.github.io/tree-select/examples/basic.html
![image](https://cloud.githubusercontent.com/assets/2011119/17658629/95f4ca4c-62ff-11e6-9205-6a6628bd0ad9.png)
![image](https://cloud.githubusercontent.com/assets/2011119/17658642/b9d0286c-62ff-11e6-8af2-6cc8a57d1843.png)

**Comment by wufeng87** [comment]
多谢，更新到新版本能用了

**Comment by wufeng87** [comment]
但是这个属性只在多选(multiple)模式下才能有效使用。单选模式下，选择一条下拉选项后，弹出窗口就会立即关闭。
Select.js onSelect方法：
![image](https://cloud.githubusercontent.com/assets/1686808/17659806/941566ac-6307-11e6-9568-39f8890b2941.png)

**Comment by wufeng87** [comment]
Select.js这里可否改成单选模式下props.onSelect返回false的话，就不调用setOpenState(false)？

**Comment by warmhug** [comment]
升级到 rc-tree-select@1.8.3 ，参考这里 http://react-component.github.io/tree-select/examples/basic.html  的 demo 写法
![image](https://cloud.githubusercontent.com/assets/2011119/17663877/7fe9f736-6322-11e6-82c8-b770ebf66830.png)
