### ISSUE TITLE
How to remove the seconds from the ant design datepicker?

### ISSUE THREAD

**Issue by nitingupta220** [ant-design/ant-design#27023]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3j54s)

### Steps to reproduce
Just select any date and time from the datepicker.

### What is expected?
I want to remove the seconds from the datepicker after selecting time. I don't want the seconds when in selection mode and not in the view mode after I selected date and time. I just want the seconds.

### What is actually happening?
Now when I select the time and date the seconds is also coming I want to remove the seconds.

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | React 16.8 |
| System | MacOs |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-enmfl?file=/index.js
