### ISSUE TITLE
Can't render custom element in virtual table cell

### ISSUE THREAD

**Issue by jonybekov** [ant-design/ant-design#27024]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-elgamal-qlfo9?file=/index.js)

### Steps to reproduce
Use virtual table example in antd docs. Try to add custom render method to any of column in columns array. You can see empty cells in that column.

### What is expected?
Virtual table should render custom react node when render method is defined in columns array.

### What is actually happening?
Virtual table is not running custom render function. 

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | WIndows 10 |
| Browser | Chrome 85.0.4183.121 (Official assembly), (64 bit) |

---
How can I render custom elements using virtual table example?

**Comment by jonybekov** [comment]
That was a stupid question!

**Comment by royair** [comment]
what was  so stupid about it?
column's render methods is indeed ignored. 
how'd u solved the problem? please share

**Comment by Chasen-Zhang** [comment]
how do you solve the problem? I haved met also，can you share.

**Comment by Chasen-Zhang** [comment]
https://codesandbox.io/s/xu-ni-lie-biao-antd-4-17-1-forked-0wn04?file=/index.js
same problem!  solved?

**Comment by Kn3cht** [comment]
Inside the grid rendering you can check if the column to be rendered contains the attribute render. If so, you can call that function with the corresponding row value.

Optional render function:
`mergedColumns[columnIndex].render`

Access row value:
`rawData[rowIndex] as any`

**Comment by vigneshwaran-chandrasekaran** [comment]
https://stackoverflow.com/a/71125088/3882241
