### ISSUE TITLE
Calendar moment locale problem

### ISSUE THREAD

**Issue by WhyItWorks** [ant-design/ant-design#27022]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cml73?file=/index.js)

### Steps to reproduce
```
import 'moment/locale/en-gb'
import en_GB from 'antd/lib/locale-provider/en_GB';

moment.locale('en-gb');
moment.updateLocale('en-gb', {
  week: { dow: 1 }
});
```
I try to change the start of the week, but the component does not recognize it. Any idea ? 

if I use a console.log to check the change in moment's locale, it shows everything is ok

### What is expected?
Start day change to monday

### What is actually happening?
it keep in sunday

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Mac |
| Browser | Chrome |

**Comment by zombieJ** [comment]
Use ConfigProvider to config locale: https://ant.design/components/config-provider/#components-config-provider-demo-locale
