### ISSUE TITLE
[RTL] Issue with Timeline

### ISSUE THREAD

**Issue by theunreal** [ant-design/ant-design#27026]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nz3b0?file=/index.css)

### Steps to reproduce
Use timeline in RTL app

### What is expected?
Timeline "dot" not override text

### What is actually happening?
The timeline dot image overrides the text

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.3 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-0etmj?file=/index.js

https://ant.design/components/config-provider/#components-config-provider-demo-direction
