### ISSUE TITLE
form.setFieldsValue({checkbox: true}) not work

### ISSUE THREAD

**Issue by degr** [ant-design/ant-design#27036]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-10i3t?file=/index.js)

### Steps to reproduce
open link to reproduce
check "initialValues"  - checkbox is false, text input - aaaa
check "componentDidMount" checkbox is true, text input - bbbb
check result - checkbox unchecked, input is bbbb

### What is expected?
checkbox checked

### What is actually happening?
checkbox unchecked

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | win |
| Browser | chrome |

**Comment by degr** [comment]
It is kind of urgent issue, because it is core functionality for controlled forms. I can't set checkbox value with data which from from backend. Suppose it happen because checkbox expect "checked" state, and all other fields expect "value"

**Comment by gpetrioli** [comment]
This is why the `valuePropName` is provided. To specify which prop to set the `value` to.

So adding `valuePropName="checked"` will fix your problems.

        <Form.Item name={"check"} valuePropName="checked">
          <Checkbox />
        </Form.Item>
