### ISSUE TITLE
AutoComplete自动完成组件QQ浏览器第一次点击不渲染下拉列表

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#27031]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zf0nn)

### Steps to reproduce
首次点击组件输入区域

### What is expected?
希望能够正常显示下拉列表

### What is actually happening?
不显示下拉列表

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.12 |
| System | Windows 10 |
| Browser | QQ浏览器10.4.2 |

![image](https://user-images.githubusercontent.com/8730272/95423110-21546480-0973-11eb-96ac-4fd9a8efc11e.png)

**Comment by zombieJ** [comment]
看一下你的 QQ 游览器 Chrome 内核是什么版本

**Comment by phoema** [comment]
70.0.3538.25
![image](https://user-images.githubusercontent.com/8730272/95464702-d6efd980-09ac-11eb-91ab-023a082b55aa.png)

**Comment by phoema** [comment]
QQ 浏览器显示最新版本
![image](https://user-images.githubusercontent.com/8730272/95464985-2d5d1800-09ad-11eb-973b-04614a402f23.png)

QQ浏览器官网
![image](https://user-images.githubusercontent.com/8730272/95465046-3f3ebb00-09ad-11eb-8f24-f06ebcb325d0.png)

**Comment by zombieJ** [comment]
Chrome 内核的版本，之前有收到说 Mac 的 QQ 游览器 Chrome 内核版本太低。推测 windows 上应该是一样的问题。所以想看看

**Comment by phoema** [comment]
Chrome 内核的版本:70.0.3538.25

**Comment by zombieJ** [comment]
哎，果然是一样的问题。QQ 浏览器真是新时代 IE…… 需要他们升级一下内核，antd 这边做不了什么。

**Comment by phoema** [comment]
@zombieJ 
4.6.4是正常的，升级到4.6.6就不行了
能兼容一下吗

**Comment by zombieJ** [comment]
欢迎 PR 为 QQ 浏览器做适配哈~

**Comment by phoema** [comment]
我是后端兼职前端，半路出家，只会拖拖拽拽。。
