### ISSUE TITLE
Control on Table sorter's status

### ISSUE THREAD

**Issue by hyungjunk** [ant-design/ant-design#27030]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
It helps to track table sorter status thus we could have a control on sorter's status. 

For now the sorter status is untrackable and not be changed unless sorting button is clicked.

### What does the proposed API look like?
const target = <Table {...options} />

```
/*
console.log(target.sortedColumns)
 [
    {
      column: { key: "id", title: "id", dataIndex: "id", sorter: true },
      columnKey: "id",
      field: "id",
      order: "ascend",
    },
    {
      column: { key: "name", title: "name", dataIndex: "name", sorter: true },
      columnKey: "name",
      field: "name",
      order: "descend",
    },
  ];
*/
```

**Comment by afc163** [comment]
See https://ant.design/components/table/#components-table-demo-reset-filter
