### ISSUE TITLE
onOK() in Modal.confirm is not fired

### ISSUE THREAD

**Issue by williamkhshea** [ant-design/ant-design#2703]
#### 本地环境

- antd 版本: 1.8.0
- 操作系统及其版本：OS X 10.11.6
- 浏览器及其版本: Chrome  52.0.2743.116 (64-bit)

#### 你期待的结果是：

onOK is fired

#### 实际上的结果：

onOK is not fired

#### 可重现的在线演示

http://codepen.io/williamshea/pen/GqzjQK?editors=0011

Click OK and you will see onOK is not fired.
onCancel is working.

**Comment by afc163** [comment]
`onOk`

**Comment by williamkhshea** [comment]
@afc163 Sorry, what does that mean?

**Comment by williamkhshea** [comment]
@afc163 请问这是BUG还是我写错了什么？

**Comment by afc163** [comment]
```diff
- onOK
+ onOk
```
