### ISSUE TITLE
是否可以Table某列固定宽度，不自适应

### ISSUE THREAD

**Issue by phoema** [ant-design/ant-design#27032]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我希望达到如下需求：
1、Table整体自适应，不出现横向滚动条
2、列宽都进行了设置，（此时整体宽度会根据屏幕进行百分比适应）

### What does the proposed API look like?
3、但是某一列列宽，不要参与自适应，我希望它就是这么宽，比如选择列、操作列。

**Comment by afc163** [comment]
某一列设定固定宽度就行了 `width: "300px"`

**Comment by phoema** [comment]
我希望在这种条件下某列能够宽度不变
2、列宽都进行了设置，（此时整体宽度会根据屏幕进行百分比适应）
因为如果只设置几列，不设置宽度的列显示的效果大小并不确定。

**Comment by phoema** [comment]
{
                title: '联系人',
                dataIndex: 'contact',
                width: 100,
            },{
                title: '电话',
                dataIndex: 'mobile',
                width: 120,
            }, {
                title: '邮箱',
                dataIndex: 'email',
                width: 100,
           },{
                title: '国家/地区',
                dataIndex: 'country',
                width: 150,
                sorter: true
            },{
                title: '分类',
                dataIndex: 'type',
                width: 200,
                sorter: true,
            }, {
                title: '操作',
                width: "100px",
                align:'center',

如上，在所有的列都设置了宽度的情况下，表格会进行页面自适应，但是操作列其实没有必要自适应
我想固定操作列的宽度，有解决办法吗？
所有列都设置宽度，是为了页面不管怎么自适应，每列的显示比例是一定的。

**Comment by afc163** [comment]
要自适应 + 定宽，可以用 `30%` 和 `calc(60% - 300px)` 和 `300px` 进行配合即可。

https://codesandbox.io/s/dark-thunder-1yx6i?file=/index.js

**Comment by phoema** [comment]
您这个方法可以实现定宽，但是到业务上就太复杂了
我们项目上的列表都是动态列，如下
![image](https://user-images.githubusercontent.com/8730272/95434191-8d3ec900-0983-11eb-9532-1a20e0636f0e.png)
我可以提一个需求吗？
列属性增加一个：固定宽度，不参与自适应宽度的属性。

**Comment by phoema** [comment]
https://codesandbox.io/s/dry-bush-ke1jt?file=/index.js:1072-1087
我改了改，曲线绕了一下
