### ISSUE TITLE
带搜索的树形控件展开节点时控制台报Warning:Can't perform a React state update on an unmounted component.

### ISSUE THREAD

**Issue by alienzhangyw** [ant-design/ant-design#27048]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-urlyc)

### Steps to reproduce
点击展开树的节点,查看控制台输出

### What is expected?
控制台无错误无警告

### What is actually happening?
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in CSSMotion (created by ForwardRef(MotionTreeNode))
    in ForwardRef(MotionTreeNode) (created by Item)
    in Item (created by List)
```

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Windows 10 2004 |
| Browser | Electron 10.1.12 |

**Comment by jzxznb** [comment]
大兄弟解决了吗，一样

**Comment by alienzhangyw** [comment]
> 大兄弟解决了吗，一样

看楼上，更新下rc-motion的版本就解决了
