### ISSUE TITLE
RangePicker 在 footer 添加 Select，一点击Select选择框，日期组件就会消失，选择不了

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#27040]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-frost-0h7tf?file=/index.js)

### Steps to reproduce
第一次选择下拉后，还可以，继续第二次就不行了。而且我尝试使用 open 属性控制日期组件的显示和隐藏，不行，onBlur 和 onOpenChange 在日期组件内部点击也会触发，我希望可以只在点击日期组件外面的地方才会隐藏，做不到。

### What is expected?
点击 footer 的 Select 下拉，日期组件还是显示的

### What is actually happening?
第一次点击下拉后，可以选择，日期组件隐藏。第二次再点击下拉，就选择不了了。

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | mac |
| Browser | google |

**Comment by linxianxi** [comment]
有没有办法只在点击日期弹出框外面的地方才隐藏？我试了 open onOpenChange onBlur 都不能实现，onOpenChange 和 onBlur 点击 Checkbox 的文字 和 选择 Select 的时候都会触发

**Comment by afc163** [comment]
https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E7%82%B9%E5%87%BB-Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E5%86%85%E7%9A%84%E5%8F%A6%E4%B8%80%E4%B8%AA-popup-%E7%BB%84%E4%BB%B6%E6%97%B6%E5%AE%83%E4%BC%9A%E6%B6%88%E5%A4%B1%EF%BC%8C%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F

**Comment by linxianxi** [comment]
> https://ant.design/docs/react/faq-cn#%E5%BD%93%E6%88%91%E7%82%B9%E5%87%BB-Select-Dropdown-DatePicker-TimePicker-Popover-Popconfirm-%E5%86%85%E7%9A%84%E5%8F%A6%E4%B8%80%E4%B8%AA-popup-%E7%BB%84%E4%BB%B6%E6%97%B6%E5%AE%83%E4%BC%9A%E6%B6%88%E5%A4%B1%EF%BC%8C%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3%EF%BC%9F

可以了，但是我给 Select 设置初始值后就不行了，您再看看我的复线事例

**Comment by afc163** [comment]
看到了，发现了几个问题：

1. **Select 不设初始值时**，chrome 下第一次打开 DatePicker，无法选择 Select：https://codesandbox.io/s/flamboyant-grass-grtll
2. **Select 设 defaultValue 时**，chrome 下第一次打开 DatePicker 再打开 Select 后，选择 Select 里的某个值，blur 后下拉框消失，再次 blur DatePicker 无法消失：https://codesandbox.io/s/unruffled-tereshkova-1gsz1?file=/index.js
3. Firefox 下打开 DatePicker 后，无法选择 Select：https://codesandbox.io/s/flamboyant-grass-grtll

**Comment by zombieJ** [comment]
Select 点击的时候会还原焦点到 Select 上导致 DatePicker 的 Input 失去焦点，有点蛋疼。

**Comment by linxianxi** [comment]
> Select 点击的时候会还原焦点到 Select 上导致 DatePicker 的 Input 失去焦点，有点蛋疼。

请问你们有办法解决吗，点击 select，datepicker 就会失去焦点就关闭了。解决有点困难、下个版本还没办法修复的话我就先用其它方式了

**Comment by zombieJ** [comment]
不太好搞，为了无障碍设计 Picker 的状态是严格跟随可聚焦原则。额外的 focusable 元素，对于 RangePicker 而言点出去就不能再通过 Tab 切换到另一个 input 上。看来得打个孔，遇到这种场景就不管无障碍了。

**Comment by afc163** [comment]
现在貌似好了？https://codesandbox.io/s/modest-currying-hhxtxv?file=/index.js

**Comment by linxianxi** [comment]
> 现在貌似好了？https://codesandbox.io/s/modest-currying-hhxtxv?file=/index.js

不行

**Comment by linxianxi** [comment]
这样受控加 useClickAway 倒是可以做到，但是获取不到输入框最外层 的 ref，所以只能用 uid 为每个 Picker 生成一个独一无二的了。
https://codesandbox.io/s/fan-wei-xuan-ze-qi-antd-5-6-3-forked-c2lppf?file=/demo.tsx

**Comment by happy-func** [comment]
同样的问题，不同的地方是我们把header中的年份和月份换成了Selct选择器进行选择，而你是在footer。
经过测试发现，rc-picker中的Piker.tsx和RangePicker.tsx中的这个代码
```
    isClickOutside: (target: EventTarget | null) =>
      !elementsContains(
        [
          panelDivRef.current,
          startInputDivRef.current,
          endInputDivRef.current,
          containerRef.current,
        ],
        target as HTMLElement,
      ),
```
打印的target为body。

rc-picker版本为v3.14.6
antd版本为4.24.15

**Comment by zombieJ** [comment]
Picker component has been refactor in `5.14.0`, and this issue is discussed and handled with https://github.com/react-component/picker/pull/691 which will be marked as closed.

Please feel free to create new issue if you have any further question :)

Picker 组件于 `5.14.0` 版本进行了重构，此问题已被 https://github.com/react-component/picker/pull/691 中进行讨论与处理。

如果有任何问题，欢迎随时创建新的 issue :)
