### ISSUE TITLE
Table 无数据时 hideOnSinglePage设置为false 还是隐藏分页器

### ISSUE THREAD

**Issue by Wendyxjw** [ant-design/ant-design#27057]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues](https://github.com/ant-design/ant-design/issues)

### Steps to reproduce
table的current设置为2，total设置为30，dataSource为[]，pagination的hideOnSinglePage为false，table展示无数据

### What is expected?
希望table的分页器受控于hideOnSinglePage

### What is actually happening?
table不展示分页器

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | react |
| System | 所有 |
| Browser | Chrome最新 |

**Comment by afc163** [comment]
hideOnSinglePage 是只有一页时是否展现分页，不处理空数据的情况。

空数据目前设计上是没有分页的，如果**一定需要的话**建议单独在 Table 外加一个空的 Pagination。

**Comment by Wendyxjw** [comment]
> hideOnSinglePage 是只有一页时是否展现分页，不处理空数据的情况。
> 
> 空数据目前设计上是没有分页的，如果**一定需要的话**建议单独在 Table 外加一个空的 Pagination。

如果 数据只有5页，但是他想打开第6页呢

**Comment by zhdxcz** [comment]
> hideOnSinglePage 是只有一页时是否展现分页，不处理空数据的情况。
> 
> 空数据目前设计上是没有分页的，如果**一定需要的话**建议单独在 Table 外加一个空的 Pagination。

目前数据为空是按照dataSource的数据吗？
如果total为100，但是当前页的数据返回为空数组，这种情况下是不是不应该隐藏分页器
