### ISSUE TITLE
Tree 控件属性问题

### ISSUE THREAD

**Issue by dai875939260** [ant-design/ant-design#2705]
#### 本地环境

- antd 版本: 1.8.0
- 操作系统及其版本：win10
- 浏览器及其版本: chrome

#### 你做了什么？

Tree控件属性defaultExpandedKeys实际环境中并不好用(key是变化的)，能不能提供属性自动展开全部或者展开几级菜单?

**Comment by wufeng87** [comment]
defaultExpandAll

**Comment by warmhug** [comment]
用 expandedKeys ，key 需要是稳定的，Keys should be stable, predictable  https://facebook.github.io/react/docs/reconciliation.html#trade-offs
