### ISSUE TITLE
Dropdown 关闭时的 bug

### ISSUE THREAD

**Issue by GreatAuk** [ant-design/ant-design#27058]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/b0318)

### Steps to reproduce
先右键显示 menu, 再随便找个地方点击左键，那么 menu 就会闪现一次
![](https://utopia1994.oss-cn-shanghai.aliyuncs.com/img-bed/20201009182124.gif)
### What is expected?
正常关闭

### What is actually happening?
闪现一次后才会关闭

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.12.0 |
| System | mac os |
| Browser | chrome v 86.0.4240.75 |

**Comment by afc163** [comment]
确实存在。

**Comment by zombieJ** [comment]
能来个 gif 不？

**Comment by afc163** [comment]
主楼已经有 gif 了。

**Comment by GreatAuk** [comment]
> 能来个 gif 不？
本来上传的是 gif 的，github 给转成图片了
https://utopia1994.oss-cn-shanghai.aliyuncs.com/img-bed/20201009182124.gif
