### ISSUE TITLE
修改DatePicker 的日期选择器的默认语言为 Zh-CN 不生效？

### ISSUE THREAD

**Issue by glk-hll** [ant-design/ant-design#27056]
代码如下：
 ```javascript
```

**Comment by ILuZhangKun** [comment]
> 代码如下：
> 
> ```js
>  import 'moment/locale/zh-cn';
>  import locale from 'antd/es/date-picker/locale/zh_CN';
> 
> <DatePicker locale={locale} inputReadOnly={true} onChange={onChange} />
> ```
> 
> 但是显示的还是英文？请问是怎么回事？
> ![image](https://user-images.githubusercontent.com/44257305/95564623-a746dd00-0a51-11eb-8706-3a687c06fe67.png)

我也是这个问题，你最后解决了吗？貌似是antd V3的一个bug

**Comment by tianleiyiji123** [comment]
官方没人解决么，遇到同样问题了

**Comment by yoyo837** [comment]
提供个复现

**Comment by tianleiyiji123** [comment]
new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)把这个注释掉webpack里面

**Comment by nieshiming** [comment]
> new webpack.IgnorePlugin(/^./locale$/, /moment$/)把这个注释掉webpack里面

这个注释掉webpack 打包时候不就是加载所有资源文件，会造成体积过大问题吧

**Comment by tianleiyiji123** [comment]
> > new webpack.IgnorePlugin(/^./locale$/, /moment$/)把这个注释掉webpack里面
> 
> 这个注释掉webpack 打包时候不就是加载所有资源文件，会造成体积过大问题吧

加上这个配置，就可以只打包中文的了
`new webpack.IgnorePlugin({
        checkResource(resource, context) {
          // do something with resource
          if (/moment\/locale/ig.test(context)) {
            if (!/zh-cn/ig.test(resource) && !/moment/ig.test(resource)) {
              return true
            }
          }
          return false
        }
      }),`
