### ISSUE TITLE
放置在 Layout.Sider下 的 Menu 展开子项后，改变 Layout.Sider 的 collapsed 属性会抛出异常

### ISSUE THREAD

**Issue by guoyl6** [ant-design/ant-design#27069]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/goofy-curran-d9m2n)

### Steps to reproduce
步骤一：
1. 展开 sub-menu
2. 点击 toggle collapsed 收起侧边栏
3. 会抛出异常
步骤二：
1. 去除 ConfigProvider 的 getPopupContainer 属性，重复步骤一
2. 此时不抛出异常

### What is expected?
ConfigProvider 的 getPopupContainer 配置不导致切换 Sider.collapsed 状态时抛出异常

### What is actually happening?
ConfigProvider 的 getPopupContainer 配置导致切换 Sider.collapsed 状态时抛出异常

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome |

---
1. 如果使用 rc-trigger@5.0.5 则无此问题。
2. 仅在 Menu 有子菜单展开，同时 ConfigProvider 配置了 getPopupContainer 时才会有异常抛出。

**Comment by guoyl6** [comment]
我不能确定该问题是否为 rc-trigger 所导致的。

**Comment by afc163** [comment]
Fixed in antd@4.16.1: https://codesandbox.io/s/lingering-breeze-3lm5s?file=/src/App.js
