### ISSUE TITLE
Avatar.Group - Add a maxSize prop

### ISSUE THREAD

**Issue by brandonwisnicki** [ant-design/ant-design#27068]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When creating a AvatarGroup with a max count, the avatar displaying the 'overflow number' (i.e. how many more avatar there are), there is no good way to change the size via a prop (besides directly editing the style prop). I propose a maxSize prop is added to Avatar.Group to make it easily editable. This will help the user experience as getting the exact pixel measurements from the source or element inspector can be tedious and not obvious to a new web dev. I've provided code in the codesandbox below. Thanks!

https://codesandbox.io/s/antd-reproduction-template-forked-mrfpj?file=/index.js

### What does the proposed API look like?
`
   <Avatar.Group maxCount={2} *maxSize="small"*>

      <Avatar size="small"> W </Avatar>
      <Avatar size="small"> X </Avatar>
      <Avatar size="small"> Y </Avatar>
      <Avatar size="small"> Z </Avatar>

       </Avatar.Group>
`

The API can be identical to that of the Avatar size prop. This should be a relatively simple addition because it is functionally identical to the Avatar size prop.

**Comment by afc163** [comment]
We should support `size` on Avatar.Group:

```jsx
<Avatar.Group size="small" />
  <Avatar>Z</Avatar>
  <Avatar>Z</Avatar>
  <Avatar>Z</Avatar>
</Avatar.Group>
```

**Comment by zdaizi** [comment]
i want to have a try
