### ISSUE TITLE
Modal closes when clicking popover items

### ISSUE THREAD

**Issue by PaulPCIO** [ant-design/ant-design#27080]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modal-rrs5i)

### Steps to reproduce
1. Create a modal
2. Add a component which has its own popup container, eg; [Select](https://ant.design/components/select), [Dropdown](https://ant.design/components/dropdown/), [Popover](https://ant.design/components/popover/)
3. Click an item inside the popover. 

### What is expected?
The modal should stay open.

### What is actually happening?
The modal closes when any when any items are clicked inside the popovers

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | latest |
| System | Mac |
| Browser | Chrome |

**Comment by BeInLife** [comment]
Same.
Reverting version back to 4.6.x
