### ISSUE TITLE
Collapse组件, 是否可以增加defaultExpandAll参数，默认展开所有折叠面板

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#27082]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
由于 Collapse.Panel 块是由后端接口返回的数据，如果改为受控组件则需要每个使用到的地方都需要改写

### What does the proposed API look like?
新增 `defaultExpandAll` 属性

**Comment by afc163** [comment]
不需要改受控组件，从后台返回数据之后再渲染 Collapse 并赋值 defaultActiveKey 就行了。
