### ISSUE TITLE
Table 组件设置 expandIconColumnIndex 不生效

### ISSUE THREAD

**Issue by fengyun2** [ant-design/ant-design#27083]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/elastic-ardinghelli-6gsmd?file=/index.js)

### Steps to reproduce
设置 `expandIconColumnIndex={3}` 无效

### What is expected?
展开按钮的列顺序出现在第三列

![image](https://user-images.githubusercontent.com/8147202/95671400-42ae8e00-0bc9-11eb-937e-48504b991d49.png)

### What is actually happening?
展开按钮的列顺序出现在第一列

![image](https://user-images.githubusercontent.com/8147202/95671403-55c15e00-0bc9-11eb-936e-f56c03ad021c.png)

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 17.0.0-rc.3 |
| System | win 10 |
| Browser | Chrome 83.0.4103.61 |

**Comment by Shawn-Cui** [comment]
@fengyun2 请问下，这个有解决方案吗😂
