### ISSUE TITLE
自定义菜单如何挂接相同path 或者component 的页面

### ISSUE THREAD

**Issue by unionall** [ant-design/ant-design#27091]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/tree/4.2.0](https://github.com/ant-design/ant-design/tree/4.2.0)

### Steps to reproduce
菜单从后端api获取菜单的数据，挂接相同的path 或者component  的页面的时候，出现了点击其中一个页面，左侧菜单栏的其他相同path的菜单项会出现被选中的样式。查看elements，发现相同的路径的带有 .ant-menu-submenu-selected。

### What is expected?
通过path 挂接query参数 例如 /xxx/xxx?wsa='123'，这样区分挂接相同指向路径的菜单项

### What is actually happening?
挂接相同component或者path ，点击选中后，其他非选中的菜单项也呈现被选中的样式。

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.8.6 |
| System | centos  |
| Browser | google   85.0.4183.102 |

**Comment by yoyo837** [comment]
menu的key不唯一即可吧

**Comment by unionall** [comment]
使用相同组件的时候，我需要刷新重新加载主页面，应该怎么做？ 使用的是antd pro react v4 版本，是在basiclayout.ts基础上修改的。

**Comment by yoyo837** [comment]
没太明白啥意思

**Comment by unionall** [comment]
在basiclayout.ts中构建 菜单导航的时候
`
 <PageHeaderWrapper>
      <ProTable<TableListItem>
`
对应了config.ts的路由，
那么菜单导航这里挂接了两个相同component的页面，如下：
`
 {
        path: '/only1',
        name: '测试1',
        icon: 'crown',
        children: [{
            name: '测试1子1',
            key: "code-list-777",
            icon: 'table',
            path: '/code/list/777',
            component: './code/list',
        }]
    },
        {
             path: '/only2',
        name: '测试2',
        icon: 'crown',
        children: [{
            name: '测试2子2',
            key: "code-list-888",         
            icon: 'table',
            path: '/code/list/888',
            component: './codelogic/list',
            }],            
        }
`
那么问题来了，在点击左侧边导航，切换这两个页面，明显的不会刷新内容页面。

**Comment by yoyo837** [comment]
包一层组件呗，强迫rerender，可行吧？

**Comment by yoyo837** [comment]
就是路由对应page组件，page组件始终和路由1对1，page组件再内置需要的其他业务组件
