### ISSUE TITLE
日历组件的问题

### ISSUE THREAD

**Issue by aimchina** [ant-design/ant-design#2709]
calendar的每一个格子该怎么赋值。目前我把ajax写在datecellrender方法里了，发现切换日历的时候会很卡。
有没有用过这个组件的，该怎么对每一个格子进行赋值，会感觉用起来比较流畅？

**Comment by afc163** [comment]
render 应该是纯函数，里面不应该有异步操作。

先系统学习一下 react 吧。:santa:
