### ISSUE TITLE
Typography ellipsis  typescript 定义错误

### ISSUE THREAD

**Issue by Liu-Ya** [ant-design/ant-design#27090]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nbkdd?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
不能将类型“{ rows: number; expandable: false; }”分配给类型“boolean | undefined”。

### What is expected?
ellipsis: boolean | ellipsis

### What is actually happening?
ellipsis: boolean | undefined

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 17.0.0-rc3 |
| System | Windows 10 |
| Browser | Microsoft Edge  86.0.622.38 |

**Comment by Liu-Ya** [comment]
![image](https://user-images.githubusercontent.com/23520283/95696547-2153ad80-0c6e-11eb-9504-8ea83aed258f.png)

**Comment by Liu-Ya** [comment]
```
export function warning(valid: boolean, message: string) {
  // Support uglify
  if (process.env.NODE_ENV !== 'production' && !valid && console !== undefined) {
    console.error(`Warning: ${message}`);
  }
}
```

https://github.com/ant-design/ant-design/blob/02fc6b1646386e03d7b2abf139dae8d62dd36e2d/components/typography/Text.tsx#L10-L14

这里

**Comment by Kermit-Xuan** [comment]
https://github.com/ant-design/ant-design/blob/2e284aa017e28e28e0a70e5837f7a799044729d9/components/typography/Text.tsx#L6


![image](https://user-images.githubusercontent.com/33770367/95696862-662c1400-0c6f-11eb-8005-c00f3ed91ae9.png)

只支持 `boolean`, 应该是文档没有更新，发个 PR 吧～

**Comment by Liu-Ya** [comment]
@Kermit-Xuan expandable suffix 在Text中还是会用到的,不能删掉吧😂

**Comment by Liu-Ya** [comment]
![image](https://user-images.githubusercontent.com/23520283/95697085-2f0a3280-0c70-11eb-98e2-802c88e5b31a.png)
比如这种场景

**Comment by Kermit-Xuan** [comment]
我意思是把 Typography.Text 的 `ellipsis` 属性文档需要更新。

**Comment by Kermit-Xuan** [comment]
看这里 https://github.com/ant-design/ant-design/blob/2e284aa017e28e28e0a70e5837f7a799044729d9/components/typography/Text.tsx#L15

传对象也没有用，会转成 `boolean`

@zombieJ 麻烦解释下为啥只支持 `boolean`，我不太熟。

**Comment by Liu-Ya** [comment]
明白了
