### ISSUE TITLE
css报Container#eachAtRule is deprecated. Use Container#walkAtRules instead.等警告

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#271]
我的项目从一个地方，copy到另一个地方后，就一直报这个警告。
试图把css相关的loader全部删掉重新安装，还一直警告
看着心塞，怎么借？

Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Container#eachRule is deprecated. Use Container#walkRules instead.
Container#eachDecl is deprecated. Use Container#walkDecls instead.

**Comment by afc163** [comment]
我们也遇到这个问题，感觉是某个依赖库的问题，可以一起帮忙找找。

**Comment by zccst** [comment]
@afc163 查了资料，好像是css-loader等几个模块都依赖postcss，而不同地方引用的版本不同。
我搜索了一下，把所有postcss都替换为最新版后，但启动后还是有警告。。。。

**Comment by zhujun24** [comment]
[这里有人遇到了同样的问题](https://github.com/elastic/kibana/pull/4849)，他是通过降级 `autoprefixer-loader` 解决的，也可以升级到最新的 `3.1.0` 来干掉这个警告

**Comment by zccst** [comment]
@zhujun24 版本有点问题。
我看了一下node_modules里的autoprefixer-loader，版本才3.1.0啊？
package.json中
  "name": "autoprefixer-loader",
  "version": "3.1.0",
  "description": "Autoprefixer loader for webpack",

**Comment by zhujun24** [comment]
[autoprefixer-loader 3.1.0](https://www.npmjs.com/package/autoprefixer-loader)

**Comment by zhujun24** [comment]
不行再试试 `"autoprefixer-loader": "2.0.x",`，我这 `2.0.x` 和 `^3.1.0` 都没有那个警告了

**Comment by zccst** [comment]
@zhujun24   刚试了 
cd ./node_modules/autoprefixer-loader
npm i autoprefixer@6.0.0 --save  #将autoprefixer-loader依赖的autoprefixer版本从6.0.2降到6.0.0
然后再次启动服务器，还是有警告，没有变化。

**Comment by zhujun24** [comment]
修改 package.json `"autoprefixer-loader": "^3.1.0"` ，依次 `rm -rf node_modules` `npm install` `npm start` ，还会有警告么

**Comment by zccst** [comment]
@zhujun24 我package.json的配置已经是 "autoprefixer-loader": "^3.1.0"
刚把 node_modules下的autoprefixer-loader删掉，重新安装
npm i autoprefixer-loader --save-dev
还是同样警告，算了，不打算弄了。浪费你不少时间，抱歉。

**Comment by zhujun24** [comment]
刚刚在另一个目录下跑了Antd，会出现警告，修改 package.json `"autoprefixer-loader": "^3.1.0"` 之后就没有那个警告了
