### ISSUE TITLE
请问Table如何设置text－align：center？

### ISSUE THREAD

**Issue by yuan1995913** [ant-design/ant-design#2710]
我设置了每列的宽度，我想使指定的某列居中，请问要如何设置？

**Comment by yuan1995913** [comment]
找到解决方法了 
const columns = [{
            title: '序号',
            dataIndex: 'serialNum',
            key: 'serialNum',
            width: '8%',
        }, {
            title: '名称',
            dataIndex: 'deptName',
            key: 'deptName',
            width: '12%',
        }, {
            title: '邀请人数',
            dataIndex: 'invitationNum',
            key: 'invitationNum',
            width: '25%',
            className: 'departmentTableOperation',
        }


需要加一个className，但是设置text－align：center需要加important，有什么更直接的办法吗

**Comment by afc163** [comment]
样式优先级提高。

```
th.xx,
td.xx {
  text－align: center;
}
```
