### ISSUE TITLE
antd 4.7.0版本与bizchart使用，popovertooltip会出现抖动，初始定位不准

### ISSUE THREAD

**Issue by luqio** [ant-design/ant-design#27102]
antd 4.7.0版本与bizchart一起使用，popover及tooltip会出现抖动，初始定位不准，定位两次。4.0.4版本没问题

**Comment by lxsunbin** [comment]
> antd 4.7.0版本与bizchart一起使用，popover及tooltip会出现抖动，初始定位不准，定位两次。（弹层内容为普通固定文本，非图片）4.0.4版本没问题

请问解决了吗，我也遇到了同样的问题

**Comment by WellerQu** [comment]
> > antd 4.7.0版本与bizchart一起使用，popover及tooltip会出现抖动，初始定位不准，定位两次。（弹层内容为普通固定文本，非图片）4.0.4版本没问题
> 
> 请问解决了吗，我也遇到了同样的问题

我也遇到了这个问题. 

原因是: 默认的transitionName "zoom-big-fast" 导致的. 暂时认为是样式过渡导致的视觉效果.

解决方式: 在使用Popover或者Tooltip时, 添加 transitionName= '' 覆盖默认值

```JSX
<Popover transitionName='' {...otherProps}>{ /* your other code */}</Popover>
```
Tooltip 同理.

**Comment by YYL1999** [comment]
> > > antd 4.7.0版本与bizchart一起使用，popover及tooltip会出现抖动，初始定位不准，定位两次。（弹层内容为普通固定文本，非图片）4.0.4版本没问题
> > 
> > 
> > 请问解决了吗，我也遇到了同样的问题
> 
> 我也遇到了这个问题.
> 
> 原因是: 默认的transitionName "zoom-big-fast" 导致的. 暂时认为是样式过渡导致的视觉效果.
> 
> 解决方式: 在使用Popover或者Tooltip时, 添加 transitionName= '' 覆盖默认值
> 
> ```js-jsx
> <Popover transitionName='' {...otherProps}>{ /* your other code */}</Popover>
> ```
> 
> Tooltip 同理.

必示的兄dei还是不错  成功解决

**Comment by leonsux** [comment]
> > > antd 4.7.0版本与bizchart一起使用，popover及tooltip会出现抖动，初始定位不准，定位两次。（弹层内容为普通固定文本，非图片）4.0.4版本没问题
> > 
> > 
> > 请问解决了吗，我也遇到了同样的问题
> 
> 我也遇到了这个问题.
> 
> 原因是: 默认的transitionName "zoom-big-fast" 导致的. 暂时认为是样式过渡导致的视觉效果.
> 
> 解决方式: 在使用Popover或者Tooltip时, 添加 transitionName= '' 覆盖默认值
> 
> ```js-jsx
> <Popover transitionName='' {...otherProps}>{ /* your other code */}</Popover>
> ```
> 
> Tooltip 同理.

nice! 搞了半天终于解决了，感谢大佬

**Comment by wengsj11** [comment]
> > > antd 4.7.0版本与bizchart一起使用，popover及tooltip会出现抖动，初始定位不准，定位两次。（弹层内容为普通固定文本，非图片）4.0.4版本没问题
> > 
> > 
> > 请问解决了吗，我也遇到了同样的问题
> 
> 我也遇到了这个问题.
> 
> 原因是: 默认的transitionName "zoom-big-fast" 导致的. 暂时认为是样式过渡导致的视觉效果.
> 
> 解决方式: 在使用Popover或者Tooltip时, 添加 transitionName= '' 覆盖默认值
> 
> ```js
> <Popover transitionName='' {...otherProps}>{ /* your other code */}</Popover>
> ```
> 
> Tooltip 同理.

但是这样写法会导致没有动画效果，还有其他解决方案？

**Comment by Wdam** [comment]
vue2版本也存在这个问题
