### ISSUE TITLE
[Need update documents]in antd lastest, modal destory when close, and i don't set destroyOnClose

### ISSUE THREAD

**Issue by wukong1995** [ant-design/ant-design#27108]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/](https://ant.design/components/modal-cn/)

### Steps to reproduce
please click "open modal" in first demo

### What is expected?
modal dom don't removed

### What is actually happening?
modal dom removed

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | macos |
| Browser | chrome |

---
please add `destroyOnClose: false` in defaultProps

**Comment by wukong1995** [comment]
relate: https://github.com/react-component/dialog/issues/205

**Comment by wukong1995** [comment]
i find it in changelog. but why do break change in refactoring.

**Comment by wukong1995** [comment]
please update documents.

**Comment by zombieJ** [comment]
这个重构是清理的时候全清，没有开 `destroyOnClose` 的时候不应该删。

**Comment by Kermit-Xuan** [comment]
destroyOnClose 应该给个默认值 `false`
