### ISSUE TITLE
DatePicker组件直接点击确定不会填充默认选中的日期

### ISSUE THREAD

**Issue by luckygavin** [ant-design/ant-design#2711]
#### 本地环境

- antd 版本: "1.7.0"
- 操作系统及其版本：windows 7
- 浏览器及其版本: Chrome 51.0.2704.106 m

#### 你做了什么？

![image](https://cloud.githubusercontent.com/assets/5365624/17654583/1adb308a-62d7-11e6-85fd-69ac26cc217d.png)
本地和官方实例都有这问题，直接点击那个确定高亮的日期是不会直接填到输入框里面去的，必须要手动去点击那个日期才行。

#### 你期待的结果是：

像官网一样正常显示？感觉官方都不正常-_- 
总觉的怪怪的，以我的认知应该是直接点确定就能把已经高亮的日期填进去

#### 实际上的结果：

点确定就只是把当前选择框隐藏，确定和取消的效果差不多了

#### 可重现的在线演示

http://ant.design/components/date-picker/#components-date-picker-demo-start-end
第7个例子

**Comment by afc163** [comment]
高亮是表示今天，不是表示已选。

**Comment by luckygavin** [comment]
是框住表示今天吧，你多点几下看看，当你点其他日期的时候，其他日期是高亮的，今天那个数字有一个框，那个框才是表示今天的吧

**Comment by luckygavin** [comment]
我觉得完全可以在点击确定的时候加一个判断，如果输入框中没有内容，就把当前高亮的日期填进去

**Comment by afc163** [comment]
嗯，这里不应该高亮的。

**Comment by luckygavin** [comment]
我刚刚说的那个方案是否可行呢，感觉那样更方便使用一点

**Comment by afc163** [comment]
如果没选的时候，不应该有高亮日期。
