### ISSUE TITLE
Table组件上可否设置一个全局值，供表格每行都能拿到这个值？

### ISSUE THREAD

**Issue by ISBN9527** [ant-design/ant-design#27111]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?

1. 当后台返回的一个特殊值在数据表格table:[{},{},{}]外面的时候,例如data:{allSampleTotal:xxx,table:[{},{},{}]}

2. 我需要用record里的一个值除以allSampleTotal得到一个值在UI上展现出来

### What does the proposed API look like?
自定义一个值在table上

### 后台返回数据如下
![image](https://user-images.githubusercontent.com/30942709/95730293-a364c600-0cb0-11eb-9b60-7fce371ca308.png)

**Comment by yoyo837** [comment]
转换下思维，你table的数组给到组件前map填充一下同一个值。

antd应该没办法考虑所有人不同的细节需求。

**Comment by ISBN9527** [comment]
类型有点多，不太想遍历，所以问问有没有其他办法，实在不行只有自己填充了

**Comment by yoyo837** [comment]
应该是没有了，填充吧。

**Comment by poozhu** [comment]
为什么需要填充，你处理 record 值的地方直接去取这个 allSampleTotal 不就行了么

**Comment by yoyo837** [comment]
> 为什么需要填充，你处理 record 值的地方直接去取这个 allSampleTotal 不就行了么

我猜他大概了获取数据和显示不在一个地方罢了。都行的。
