### ISSUE TITLE
Span instead of Button when Button is disabled

### ISSUE THREAD

**Issue by chris335** [ant-design/ant-design#27118]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/loving-nash-5imtj?file=/src/App.js)

### Steps to reproduce
Tooltip around a disabled Button:
`<Tooltip title={"Test"}> <Button disabled className="TestClass"></Button> </Tooltip>`

### What is expected?
A Button element without a Span around. Or at least that the ClassName stays on the Button and not on the Span

### What is actually happening?
Span is around the Button and the ClassName is on the Span

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | Windows 7 |
| Browser | Chrome v86 |

---
With the current implementation, it’s difficult to globally style a button when it’s disabled and has a tooltip.

**Comment by afc163** [comment]
It is by designed.

https://github.com/ant-design/ant-design/issues/18842#issuecomment-532036147

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21404#issuecomment-586800984

**Comment by leifdejong** [comment]
@afc163 why is this by design? Then we can't use styled components on the button without it breaking. This seems to be badly thought through. Would you be so kind to explain why this decision was made?

**Comment by JMVHill** [comment]
I agree that this is poor design. In order to apply a cosmetic change to an element you're effectively restructuring the DOM. This breaks libraries which rely on a regular DOM structure like `styled-components` for an attribute assignment which should be fairly self-contained.

I'd be keen to hear a bit more about the rationale around wrapping the button in the span also?
