### ISSUE TITLE
使用dumi二次封装antd时Button组件报错

### ISSUE THREAD

**Issue by jiachaosun** [ant-design/ant-design#27117]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://gitee.com/jiachaosun/dumi-antd](https://gitee.com/jiachaosun/dumi-antd)

### Steps to reproduce
- build出dist
- 本地建了一个cra
- yarn link dumi组件库
- cra 使用上述link过的组件库（本地调试）
- cra中App.js，import { Button } from 'my-antd'

### What is expected?
Button组件正常渲染

### What is actually happening?
定位到antd中 InternalButton

node_modules/antd/es/button/button.js:124

Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | MacOS |
| Browser | Chrome 85 |

<img width="997" alt="图片" src="https://user-images.githubusercontent.com/859382/95764297-d88a0c00-0ce2-11eb-839e-dc26bb5337b5.png">

**Comment by afc163** [comment]
建议反馈到 dumi 仓库中。
