### ISSUE TITLE
Tree 的title 内使用 Checkbox，必须先失去焦点，否则无法实现Checkbox的toggle

### ISSUE THREAD

**Issue by zhangwilling** [ant-design/ant-design#2712]
#### 本地环境

- antd 版本:1.8
- 操作系统及其版本：mac
- 浏览器及其版本:chrome最新版

#### 你做了什么？
这里没用state去控制状态变化
`<TreeNode 
       style={s.propertyName} 
       title={<Checkbox >kkkk</Checkbox>}
 />`

#### 你期待的结果是：

CheckBox支持连续点击的toggle效果

#### 实际上的结果：

需要先让Checkbox失去焦点，才能改变其状态

**Comment by warmhug** [comment]
```
<label onClick={(e) => e.stopPropagation()}><input type="checkbox" /> checked</label>
```
