### ISSUE TITLE
Divider wrong border color

### ISSUE THREAD

**Issue by afc163** [ant-design/ant-design#27132]
https://ant.design/components/divider-cn/

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/507615/95835475-d53d6180-0d70-11eb-9fb7-5e109dcc4a77.png">

**Comment by openscript** [comment]
I've also ran into this issue.

Reproduction:
https://codesandbox.io/s/antd-reproduction-template-forked-l6sto

**Comment by YassineDM** [comment]
Same behaviour when `dashed` prop is added to Divider with text (dark dashes instead of light gray ones)...
