### ISSUE TITLE
Formik Ant Design form re-renders onChange, on each key stroke, gets very slow even in production

### ISSUE THREAD

**Issue by RebecaLozreyGlobant** [ant-design/ant-design#27139]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-6e93z)

### Steps to reproduce
    "formik": "2.1.4",
    "formik-antd": "2.0.1",
    "antd": "4.4.1",
I have a form with 20 fields, with many validations, dependencies, but this is about the comments field which doesnt have dependencies or validations, is just too slow beacause the whole form re-renders on each key stroke

### What is expected?
I need the filed value to be updated in formik state just until the field loses foucus, onBlur, or else the whole form re-renders, on each key stroke

### What is actually happening?
with fast={true} the form keeps re-rendering, 

| Environment | Info |
|---|---|
| antd | 4.4.1 |
| React | 16.13.0 |
| System | Windows 10 |
| Browser | Chrome |

**Comment by afc163** [comment]
Maybe you can report this to formik issues.
