### ISSUE TITLE
Select或Tooltip首次点击不出现浮层

### ISSUE THREAD

**Issue by theDoinb** [ant-design/ant-design#27140]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
之前使用的是4.6.2，现在尝试升级到4.7.0时，发现了类似Select等浮层第一次点击不出现，焦点失去后，又出现了并收起，因为是本地有问题，
所以无法提供重现了，不过我发现官网是正确的，能大概猜到导致的原因吗？

### What is expected?
Select或Tooltip首次点击出现浮层

### What is actually happening?
Select或Tooltip首次点击不出现浮层

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.8.0 |
| System | win10 |
| Browser | chrome |

**Comment by afc163** [comment]
尝试移除 node_modules 和 package-lock.json 和 yarn.lock 后重新安装。

**Comment by theDoinb** [comment]
好像还是不行，不过我看到popover在点击展开后，有个opacity：0，不清楚其他有浮层的组件是否和这个有关系

**Comment by afc163** [comment]
给个重现吧，猜不出来问题所在。

**Comment by theDoinb** [comment]
好像是首次点击，然后组件动画的类停在了中间的状态，
现在先把版本降回去了，
后面我再看看能不给个重现吧，
先把问题关闭了

**Comment by jperelli** [comment]
I have the same problem

**Comment by yunuo-tech** [comment]
同样的问题

**Comment by phoema** [comment]
#27312 
我觉得我那个问题应该一样
因为QQ浏览器以前没事，升到最新版就不支持了
