### ISSUE TITLE
Modal的visibles属性，在hooks使用时出错

### ISSUE THREAD

**Issue by w602542704** [ant-design/ant-design#27149]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/practical-voice-8tqb9?file=/index.js:206-216)

### Steps to reproduce
1.在codesandbox里编辑modal
2.实现以下代码即可复现
import React, { useState, useEffect } from "react";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";
import { Modal } from "antd";

const App = () => {
  const [visible, setVisible] = useState(true);
  useEffect(() => {
    setVisible(false);
    console.log("123");
  }, []);
  return (
    <Modal
      title="Modal 1000px width"
      centered
      visible={visible}
      onOk={() => setVisible(false)}
      onCancel={() => setVisible(false)}
      width={1000}
    >
      <p>some contents...</p>
      <p>some contents...</p>
      <p>some contents...</p>
    </Modal>
  );
};

ReactDOM.render(<App />, document.getElementById("container"));

### What is expected?
目的：
1.让modal初始化就展示出来；
2.在useEffect中在设置隐藏；

### What is actually happening?
modal框没有了，但遮罩层还在

| Environment | Info |
|---|---|
| antd | 4.2.0 |
| React | 16.9.17 |
| System | win |
| Browser | 谷歌 |

---
我是在开发中遇到这样的问题，开发中useEffect设置了setVisible（false），更诡秘的是无论怎么刷新页面，modal始终是显示的

**Comment by afc163** [comment]
看上去和 #27136 可能底层是同一个问题。

**Comment by w602542704** [comment]
> 可能和[＃27136](https://github.com/ant-design/ant-design/issues/27136)是同一个艰苦的问题。

把项目中的useEffect替换useMemo，即可解决，但我不知道为什么这样可以解决的

**Comment by ISyangk** [comment]
你这个应用场景很奇怪啊，页面加载先弹出，随后在类似componentDidMount这个生命周期关闭，感觉没有任何意义。其次，后下说的useMemo可以实现是因为，useEffect与useMemo的区别在于，useEffect是发生在渲染之后，而useMemo是发生在渲染之前的。

**Comment by w602542704** [comment]
> 你这个应用场景很奇怪啊，页面加载先弹出，随后在类似componentDidMount这个生命周期关闭，感觉没有任何意义。其次，楼下说的useMemo可以实现是因为，useEffect与useMemo的区别在于，useEffect是发生在渲染之后，而useMemo是发生在渲染之前的。

确实这个场景可能很少，也只是为了方便开调试的时候遇到的，这个不用管的。useEffect再渲染之后执行，我设置setState为什么没有赋值上呢？是不是andt Modal的bug?

**Comment by ISyangk** [comment]
> > 你这个应用场景很奇怪啊，页面加载先弹出，随后在类似componentDidMount这个生命周期关闭，感觉没有任何意义。其次，楼下说的useMemo可以实现是因为，useEffect与useMemo的区别在于，useEffect是发生在渲染之后，而useMemo是发生在渲染之前的。
> 
> 确实这个场景可能很少，也只是为了方便开发调试的时候遇到的，这个不用管的。因为useEffect在渲染之后执行，我设置setState为什么没有渲染呢？modal始终是显示的，是不是andt Modal的bug?

那你需要去看下rc-dialog源码中对于蒙层这块依赖visible是怎么去处理了的

**Comment by w602542704** [comment]
> > > 你这个应用场景很奇怪啊，页面加载先弹出，随后在类似componentDidMount这个生命周期关闭，感觉没有任何意义。其次，楼下说的useMemo可以实现是因为，useEffect与useMemo的区别在于，useEffect是发生在渲染之后，而useMemo是发生在渲染之前的。
> > 
> > 
> > 确实这个场景可能很少，也只是为了方便开发调试的时候遇到的，这个不用管的。因为useEffect在渲染之后执行，我设置setState为什么没有渲染呢？modal始终是显示的，是不是andt Modal的bug?
> 
> 那你需要去看下rc-dialog源码中对于蒙层这块依赖visible是怎么去处理了的
算了，最近很忙，没时间看这个，不管这个了

**Comment by zombieJ** [comment]
测了一下 `4.8.0` 发现已经没了。

**Comment by EdisonVan** [comment]
4.10.0还是存在！
