### ISSUE TITLE
ConfigProvider配置getPopupContainer后，Modal.confirm、info、success、error、warning未使用ConfigProvider配置

### ISSUE THREAD

**Issue by blksky** [ant-design/ant-design#27141]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-zf18f)

### Steps to reproduce
我发现Modal.confirm、info、success、error、warning渲染的内容在body下，未使用ConfigProvider配置，modal渲染的内容在body下，使用了ConfigProvider配置，这是不统一的，在实际使用中也存在问题

### What is expected?
ConfigProvider配置getPopupContainer后，Modal.confirm、info、success、error、warning也应和Modal一样使用ConfigProvider中的配置

### What is actually happening?
ConfigProvider配置getPopupContainer后，Modal.confirm、info、success、error、warning渲染的div在body下，ConfigProvider中的配置对Modal.confirm、info、success、error、warning无效， 但是对Modal是有效的

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | Mac |
| Browser | Chrome |

---
希望能解决这个问题，而不是使用rootPrefixCls这种方式

**Comment by afc163** [comment]
https://ant.design/components/modal-cn/#%E4%B8%BA%E4%BB%80%E4%B9%88-Modal-%E6%96%B9%E6%B3%95%E4%B8%8D%E8%83%BD%E8%8E%B7%E5%8F%96-context%E3%80%81redux-%E7%9A%84%E5%86%85%E5%AE%B9%EF%BC%9F
