### ISSUE TITLE
Axure 相应资源的更新

### ISSUE THREAD

**Issue by pigletfly** [ant-design/ant-design#2714]
ant-design 更新很快，很多组件资源没有在 http://ant.design/docs/resource/download 更新

**Comment by afc163** [comment]
稍等，Axure 组件回头会有独立网站放出来。

**Comment by pigletfly** [comment]
```
The library could not be loaded.
Error message:
This file was created with Axure RP 8.0, and cannot be opened in earlier versions.

If you are using the Axure RP 8.0 Beta, please update to the latest beta version.

Please visit www.axure.com to upgrade to the latest version of Axure RP.

```
不支持Axure 7 了？1.3 的 7 可以打开

**Comment by afc163** [comment]
2.0 现在只支持 Axure 8。

重新下载，字体路径已修复。

**Comment by pigletfly** [comment]
重新从 http://ant.design/docs/resource/download  下载了，路径好像没有变化

**Comment by afc163** [comment]
路径没变化，文档更新了。

**Comment by pigletfly** [comment]
![2016-08-24 17 48 17](https://cloud.githubusercontent.com/assets/877790/17926294/fe95d648-6a22-11e6-92cc-e5dcc23b5d4b.png)
貌似这里的字体下载链接 没有变化 你说的文档更新是？

**Comment by afc163** [comment]
我试试。。我本地没有 Axure

**Comment by afc163** [comment]
我刚才传错了，现在好了。

**Comment by allorange** [comment]
现在的字体文件缺与![image](https://cloud.githubusercontent.com/assets/2107669/19805171/5c912e28-9d45-11e6-89a2-9ab9876f96a1.png)对应的删除图标字体

**Comment by xnightsky** [comment]
2.0.1 anticon 还是很少

![image](https://cloud.githubusercontent.com/assets/5158235/21480733/dc7f2508-cb9a-11e6-985e-f20329d55163.png)

**Comment by yiwuyu** [comment]
[axure组件库](http://library.ant.design)

好像挂了，控制台有报错.

**Comment by mafeifan** [comment]
链接失效了 404 not found
