### ISSUE TITLE
有些更新css的样式会和原来不一样

### ISSUE THREAD

**Issue by LightmanGong** [ant-design/ant-design#27142]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/changelog-cn](https://ant.design/changelog-cn)

### Steps to reproduce
这次更新之前表格的默认字体样式的透明度是65%，但是更新之后默认样式变成了85%，在更新日志里面也没有写
nav的li也突然多出了hover的背景样式，同样日志也没写
之前也需要过好几次类似这样默认css变化的情况，请问这个是ant的设计元素，还是我应该选定一个版本不需要更新，或者是我用法不当，谢谢

### What is expected?
希望如果修改css，会在日志里面显示

### What is actually happening?
修改样式后并不知道，或者细微的变化，比如圆角，input高度，等，不太容易被人发现

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | react |
| System | windows |
| Browser | chrom |

**Comment by afc163** [comment]
https://ant.design/changelog-cn#4.6.0

> 这次更新之前表格的默认字体样式的透明度是65%，但是更新之后默认样式变成了85%，在更新日志里面也没有写

这个写了。

<img width="580" alt="image" src="https://user-images.githubusercontent.com/507615/95946371-007e8a00-0e1f-11eb-8e95-a96e3e91aaf4.png">

> nav的li也突然多出了hover的背景样式

这个不知道是啥。

基本上有意义的样式变动都会写在 changelog 里，如果你发现漏了，可以反馈给我们，我们会及时补上。

**Comment by LightmanGong** [comment]
知道了谢谢，非常感谢。。。
