### ISSUE TITLE
增加个好看的视频，音频控件呗

### ISSUE THREAD

**Issue by 120011676** [ant-design/ant-design#27144]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
增加个好看的视频，音频控件呗

### What does the proposed API look like?
增加个好看的视频，音频控件呗

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/10977

**Comment by zombieJ** [comment]
需求简单的话建议直接使用原生 video 元素。开发视频展示控件比较重型，不是有十足的维护力度不适合轻易下手。

**Comment by yoyo837** [comment]
那体积和复杂度好像都是单独立项成独立库了
