### ISSUE TITLE
need ant search function in an custom input inside select (dropdown)

### ISSUE THREAD

**Issue by mohammadgharouni** [ant-design/ant-design#27153]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-6327k?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
I have a plusDropDown component and I want to have search functionality as described below inside it

### What is expected?
input in dropdown works same as showSearch property

### What is actually happening?
I want to have search functionality inside the dropdown instead of using showSearch property. I don't want to write the function myself and want the use ant its own search function because I need the notFound content to be displayed when there is no result

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | google chrome v86.0.4240.75  |

**Comment by afc163** [comment]
We have same searchable select design as https://semantic-ui.com/modules/dropdown.html#search-selection

If you don't like the default design, you have to resolve it by youself.

**Comment by mohammadgharouni** [comment]
I'm using ant design react component and don't want to use semantic ui
