### ISSUE TITLE
下拉菜单选项小于等于10个时，仍旧可以滚动，但滚动条样式丢失

### ISSUE THREAD

**Issue by NorthwesternDirector** [ant-design/ant-design#27151]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-water-71cew?file=/index.js:728-763)

### Steps to reproduce
手动增加一项Select.Option， 比较下拉菜单有10条数据和有11条数据时，下拉菜单的样式

### What is expected?
只要能滚动，滚动条样式应该保持一致

### What is actually happening?
小于等于10条数据时，仍旧可以滚动，但滚动条样式丢失

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | Chrome 85.0.4183.83 |

**Comment by zombieJ** [comment]
超过一定数量后会切换成虚拟滚动，这个可以同一一下按照虚拟滚动的算。
