### ISSUE TITLE
Add ability to format how Mentions options are displayed in the textarea

### ISSUE THREAD

**Issue by delyanr** [ant-design/ant-design#27157]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Provides the ability to save e.g. the UUID of a mentioned object that usually has persistence in a back-end, rather than save e.g. the name of the mentioned object that can change across time.

### What does the proposed API look like?
Add a `formatter` prop to the `Mentions` component which takes each of the `({ prefix, value })` pairs and spits out a `string` of how each pair should be displayed in the textarea (I'm not talking about the dropdown!). This allows the use of `<Mentions.Option value={obj.uuid}>{obj.name}</Mentions.Option>` passing each `obj.uuid` through the `formatter` prop to display the `obj.name` in the textarea. There are other possible API solutions, but I believe this is the cleanest. Thanks!

**Comment by afc163** [comment]
Mentions is designed for textarea input helper, you can try `<Select tags />` in your case.

**Comment by delyanr** [comment]
@afc163 What I want to do though is still be able to mix free text with the mentions/tags. I don't believe there is a way to do this using `<Select tags />`.

**Comment by FlackMonkey** [comment]
> * [x]  I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.
> 
> ### What problem does this feature solve?
> Provides the ability to save e.g. the UUID of a mentioned object that usually has persistence in a back-end, rather than save e.g. the name of the mentioned object that can change across time.
> 
> ### What does the proposed API look like?
> Add a `formatter` prop to the `Mentions` component which takes each of the `({ prefix, value })` pairs and spits out a `string` of how each pair should be displayed in the textarea (I'm not talking about the dropdown!). This allows the use of `<Mentions.Option value={obj.uuid}>{obj.name}</Mentions.Option>` passing each `obj.uuid` through the `formatter` prop to display the `obj.name` in the textarea. There are other possible API solutions, but I believe this is the cleanest. Thanks!

Would be great to have TextArea with possibility to write text and input formatted (icon, text, styling) tags from static/loadable list. So it will look not as plain text, but rich enough.

**Comment by xinghul** [comment]
please consider reopening this issue, it's a pretty common use case where we might have users with the same name.

also being able to highlight mentions would be great.

**Comment by clmz** [comment]
Too bad no one has yet added this basic feature within two and a half years, but closing an issue within one week without any solution is what they can do ...

**Comment by bruno-teruel** [comment]
Commenting to give support. This issue is crucial for Mentions, it needs to be fixed.

**Comment by RinNguyens** [comment]
Commenting to give support. This issue is crucial for Mentions, it needs to be fixed.
