### ISSUE TITLE
form.list 中的项如何排序。如： 上移下移或者拖拽

### ISSUE THREAD

**Issue by ty888** [ant-design/ant-design#27160]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
现在有个需求就是添加商品参数，有多个，而且需要排序。

### What does the proposed API look like?
看了一下form.list里面的fields似乎不可控，一时间想不到好的解决方案

**Comment by ty888** [comment]
我找到方法了

**Comment by hsyxxi** [comment]
请问你怎么解决的？

**Comment by wangwenjun12** [comment]
同问

**Comment by steadyzeus** [comment]
我也遇到这个问题。我的解决方案是用react-beautiful-dnd 拖拽库。Antd Form.List 有add,remove,move方法，move方法可以改变fileds的data顺序。
const onDragEnd = (result,move) => {
    if (!result.destination) {
      return;
    }
    move(result.source.index,result.destination.index);
  }

**Comment by glk-hll** [comment]
可以用 `Form.List` 的 `move` 方法实现上/下移：
![image](https://github.com/ant-design/ant-design/assets/44257305/6029c9b6-f925-4f2f-9784-f857214ac68a)
