### ISSUE TITLE
使用组件Tabs, type为editable-card,使用renderTabBar替换 TabBar，用于二次封装标签头,结果关闭按钮失效,不见了

### ISSUE THREAD

**Issue by 18487115313** [ant-design/ant-design#27166]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cool-water-68lnk?file=/src/App.js)

### Steps to reproduce
使用组件Tabs, type为editable-card,使用renderTabBar替换 TabBar，用于二次封装标签头

### What is expected?
二次封装后关闭标签没有失效

### What is actually happening?
结果关闭按钮失效,不见了

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.12.0 |
| System | window 10 |
| Browser | Google Chrome |

**Comment by Mongkii** [comment]
`renderTabBar` 会用 return 的元素**完全**替换 TabBar。在你的示例中，return 的元素是
```js
<div>
  {tabInfo.map((item, index) => (<div></div>)}
</div>
```
其中没有关闭按钮元素，所以不会展示

----

根据你的需求，`renderTabBar` 里可以这么写
```js
// ...
return (
  <Dropdown overlay={menuItems} trigger={["contextMenu"]}>
    <div>
      <DefaultTabBar {...props} />
    </div>
  </Dropdown>
);
```

如果需要对具体每一个 Tab 做定制，可以写成
```js
// ...
return (
  <Dropdown overlay={menuItems} trigger={["contextMenu"]}>
    <div>
      <DefaultTabBar {...props}>
        {(tabNode) => {
          // ...针对每个 tab 做一些操作
          // 比如: return <div>{tabNode}</div>
        }}
      </DefaultTabBar>
    </div>
  </Dropdown>
);
```
