### ISSUE TITLE
对话框禁用动画后无法关闭

### ISSUE THREAD

**Issue by concefly** [ant-design/ant-design#27169]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sharp-browser-kcc9y?file=/index.js)

### Steps to reproduce
1. 打开对话框
1. 点击对话框上的“关闭”按钮

### What is expected?
对话框关闭

### What is actually happening?
对话框没有消失

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.14.0 |
| System | mac |
| Browser | chrome Version 86.0.4240.75 (Official Build) (x86_64) |

---
应该和这个改动有关 https://github.com/ant-design/ant-design/pull/26940

**Comment by zombieJ** [comment]
空字符串会禁止动画：https://codesandbox.io/s/exciting-kapitsa-hmfq1

我看看怎么兼容这种写法。

**Comment by zombieJ** [comment]
讨论了一下，不用兼容。文档里写一下怎么关闭动画。
