### ISSUE TITLE
下拉选择，如果 使用搜索功能表单清除无法清除输入的搜索条件

### ISSUE THREAD

**Issue by aw6658913** [ant-design/ant-design#2716]
#### 你做了什么？
在输入框输入0，然后选择搜索出来的节点，接着点击重置按钮

#### 你期待的结果是：

选择的节点包括输入的搜索都清空

#### 实际上的结果：

选择结果清空了，但是搜索条件并为清空

#### 可重现的在线演示

http://codepen.io/anon/pen/kXVRPL?editors=001

**Comment by afc163** [comment]
应该和 Select 保持一致，选中后输入的搜索文字就应该清空。

http://ant.design/components/select/#components-select-demo-multiple

@warmhug

**Comment by warmhug** [comment]
选中后输入的搜索文字就应该清空， 感觉也不太合适

**Comment by warmhug** [comment]
@aw6658913 现在还不确定要选中清除搜索文字。快一点的解决办法：你先把 tree-select 包装一层，用于表单中，象这里 http://react-component.github.io/tree-select/examples/form.html 在里边手动清除 搜索文字。

![image](https://cloud.githubusercontent.com/assets/2011119/17658868/259d23c8-6301-11e6-91ae-d88e48035ea9.png)

**Comment by afc163** [comment]
选中后确实不应该清除搜索文字。

关闭浮层时应该清除搜索文字。

**Comment by warmhug** [comment]
关闭浮层时清除搜索文字，感觉也不好、特别是在多选框上，而且这样不是“完全受控”的。

现在能解决的办法：设置`inputValue={null}`选中后能自动清除搜索文字、和 select 组件一样；或者在表单中把 tree-select 包装一层、手动清除搜索文字，也可以配合`onDropdownVisibleChange` 做更精细控制。

另外一个可以考虑的做法：在表单中需要设置`labelInValue`，这时在 value 对象`{value:'', label:''}`再加入个`inputValue`，但还是比较麻烦、先不做。
