### ISSUE TITLE
Form.List下的Form.Item如何通过setFieldsValue设置值

### ISSUE THREAD

**Issue by qq382724935** [ant-design/ant-design#27177]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. 用例场景：在<Form.List name="list"/>下动态生成Form.Item，其中有个<Form.Item name={[filed.name,'arrayData']} ><Button>添加</Button></Form.Item>，点击按钮会出现弹出框选择一些数据保存到当前arrayData字段中。
2. 问题：在Form.List下循环的Form.Item无法通过setFieldsValue赋值
    a. setFieldsValue({['list', filed.name, 'arrayData']：['测试','测试2','测试3']})无法设置，NamePath类型参数无效
    b. setFieldsValue({[`list${filed.name}arrayData`]：['测试','测试2','测试3']}) 尝试``也无法设置
3. 对Form.list进行重新赋值，这是一种方法但list下的内容全部会重新渲染。是否有其它方法是我没想到的？

### What does the proposed API look like?
手动对Form.List下动态创建的Form.Item进行赋值，如setFieldsValue对象中的key能接收NamePath类型

**Comment by qq382724935** [comment]
https://codesandbox.io/s/charming-pond-76iud?file=/src/App.js

**Comment by qq382724935** [comment]
上面那个地址好像出问题了，备用地址：https://codesandbox.io/s/determined-black-g4tp6?file=/src/App.js

**Comment by afc163** [comment]
See https://codesandbox.io/s/vigorous-maxwell-zhxro?file=/src/App.js

**Comment by hyl1374961656** [comment]
表单提交后setFields怎么用呢

**Comment by zsz91** [comment]
使用  https://codesandbox.io/s/vigorous-maxwell-zhxro?file=/src/App.js 中的 setFieldsValue 在不改变数据length 只改变某一项的值时是有可能失败的. 
因为 react 的虚拟dom比对数据变化是浅比对.
我的解决方案是 先 设置为空数组, 再设置成更新后的新数据.
` let newData = form.getFieldsValue().areaData;
  form.setFieldsValue({areaData: [], });
  newData[field.key] = {  ...newData[field.key], someNewData: 'new',};
  form.setFieldsValue({ areaData: newData, });
`

**Comment by wj0990** [comment]
```js
const {  Form, Input, Button, Space, Select  } = antd;
const {  MinusCircleOutlined, PlusOutlined  } = icons;

const { Option } = Select;

const areas = [
  { label: 'Beijing', value: 'Beijing' },
  { label: 'Shanghai', value: 'Shanghai' },
];

const sights = {
  Beijing: ['Tiananmen', 'Great Wall'],
  Shanghai: ['Oriental Pearl', 'The Bund'],
};

const Demo = () => {
  const [form] = Form.useForm();

  const onFinish = values => {
    console.log('Received values of form:', values);
  };

  const handleChange = () => {
    form.setFieldsValue({ sights: [] });
  };
  
  const onChange = (value, key) => {
  const fields = form.getFieldsValue();
    const { sights } = fields;
    Object.assign(sights[key], { price: value })
    form.setFieldsValue({ sights })
}


  return (
    <Form form={form} name="dynamic_form_nest_item" onFinish={onFinish} autoComplete="off">
      <Form.Item name="area" label="Area" rules={[{ required: true, message: 'Missing area' }]}>
        <Select options={areas} onChange={handleChange} />
      </Form.Item>
      <Form.List name="sights">
        {(fields, { add, remove }) => (
          <>
            {fields.map(field => (
              <Space key={field.key} align="baseline">
                <Form.Item
                  noStyle
                  shouldUpdate={(prevValues, curValues) =>
                    prevValues.area !== curValues.area || prevValues.sights !== curValues.sights
                  }
                >
                  {() => (
                    <Form.Item
                      {...field}
                      label="Sight"
                      name={[field.name, 'sight']}
                      fieldKey={[field.fieldKey, 'sight']}
                      rules={[{ required: true, message: 'Missing sight' }]}
                    >
                      <Select onChange={e => onChange(e, field.key)} disabled={!form.getFieldValue('area')} style={{ width: 130 }}>
                        {(sights[form.getFieldValue('area')] || []).map(item => (
                          <Option key={item} value={item}>
                            {item}
                          </Option>
                        ))}
                      </Select>
                    </Form.Item>
                  )}
                </Form.Item>
                <Form.Item
                  {...field}
                  label="Price"
                  name={[field.name, 'price']}
                  fieldKey={[field.fieldKey, 'price']}
                  rules={[{ required: true, message: 'Missing price' }]}
                >
                  <Input onChange={onChange} />
                </Form.Item>

                <MinusCircleOutlined onClick={() => remove(field.name)} />
              </Space>
            ))}

            <Form.Item>
              <Button type="dashed" onClick={() => add()} block icon={<PlusOutlined />}>
                Add sights
              </Button>
            </Form.Item>
          </>
        )}
      </Form.List>
      <Form.Item>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
    </Form>
  );
};

ReactDOM.render(<Demo />, mountNode);
```

**Comment by asmallbottle** [comment]
> ```js
> const {  Form, Input, Button, Space, Select  } = antd;
> const {  MinusCircleOutlined, PlusOutlined  } = icons;
> 
> const { Option } = Select;
> 
> const areas = [
>   { label: 'Beijing', value: 'Beijing' },
>   { label: 'Shanghai', value: 'Shanghai' },
> ];
> 
> const sights = {
>   Beijing: ['Tiananmen', 'Great Wall'],
>   Shanghai: ['Oriental Pearl', 'The Bund'],
> };
> 
> const Demo = () => {
>   const [form] = Form.useForm();
> 
>   const onFinish = values => {
>     console.log('Received values of form:', values);
>   };
> 
>   const handleChange = () => {
>     form.setFieldsValue({ sights: [] });
>   };
>   
>   const onChange = (value, key) => {
>   const fields = form.getFieldsValue();
>     const { sights } = fields;
>     Object.assign(sights[key], { price: value })
>     form.setFieldsValue({ sights })
> }
> 
> 
>   return (
>     <Form form={form} name="dynamic_form_nest_item" onFinish={onFinish} autoComplete="off">
>       <Form.Item name="area" label="Area" rules={[{ required: true, message: 'Missing area' }]}>
>         <Select options={areas} onChange={handleChange} />
>       </Form.Item>
>       <Form.List name="sights">
>         {(fields, { add, remove }) => (
>           <>
>             {fields.map(field => (
>               <Space key={field.key} align="baseline">
>                 <Form.Item
>                   noStyle
>                   shouldUpdate={(prevValues, curValues) =>
>                     prevValues.area !== curValues.area || prevValues.sights !== curValues.sights
>                   }
>                 >
>                   {() => (
>                     <Form.Item
>                       {...field}
>                       label="Sight"
>                       name={[field.name, 'sight']}
>                       fieldKey={[field.fieldKey, 'sight']}
>                       rules={[{ required: true, message: 'Missing sight' }]}
>                     >
>                       <Select onChange={e => onChange(e, field.key)} disabled={!form.getFieldValue('area')} style={{ width: 130 }}>
>                         {(sights[form.getFieldValue('area')] || []).map(item => (
>                           <Option key={item} value={item}>
>                             {item}
>                           </Option>
>                         ))}
>                       </Select>
>                     </Form.Item>
>                   )}
>                 </Form.Item>
>                 <Form.Item
>                   {...field}
>                   label="Price"
>                   name={[field.name, 'price']}
>                   fieldKey={[field.fieldKey, 'price']}
>                   rules={[{ required: true, message: 'Missing price' }]}
>                 >
>                   <Input onChange={onChange} />
>                 </Form.Item>
> 
>                 <MinusCircleOutlined onClick={() => remove(field.name)} />
>               </Space>
>             ))}
> 
>             <Form.Item>
>               <Button type="dashed" onClick={() => add()} block icon={<PlusOutlined />}>
>                 Add sights
>               </Button>
>             </Form.Item>
>           </>
>         )}
>       </Form.List>
>       <Form.Item>
>         <Button type="primary" htmlType="submit">
>           Submit
>         </Button>
>       </Form.Item>
>     </Form>
>   );
> };
> 
> ReactDOM.render(<Demo />, mountNode);
> ```

点下删除，再操作，拿到的key会乱
