### ISSUE TITLE
Select样式优化，点击后看不出可以滚动

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#27170]
![image](https://user-images.githubusercontent.com/8358236/96101078-a5749200-0f07-11eb-8007-b9c914599751.png)

**Comment by hengkx** [comment]
上次 在群里 讨论了下 然后就没有然后了😁

**Comment by zhangchen915** [comment]
![](https://user-images.githubusercontent.com/14519018/96347654-becb3900-10d5-11eb-9a5e-0bf7004f2ba9.jpg)
需要这种滚动提示效果吧

**Comment by xrkffgg** [comment]
我感觉还好

**Comment by zombieJ** [comment]
`rc-virtual-list` 里加了初始化高亮滚动条，`rc-select` 里还没加。我加一下~
