### ISSUE TITLE
Form.Item组件的getValueProps属性结合Select组件的options属性时，value值没有正确选择

### ISSUE THREAD

**Issue by SystemLight** [ant-design/ant-design#27182]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-3mwhz)

### Steps to reproduce
```React
import React, { useEffect } from "react";
import { Select, Form } from "antd";
import ReactDOM from "react-dom";
import "antd/dist/antd.css";
import "./index.css";

function MyPage() {
  const [form] = Form.useForm();

  useEffect(() => {
    console.log("set Form");
    form.setFieldsValue({ Status: "可用" });
  }, []);

  return (
    <Form form={form}>
      <Form.Item
        name={"Status"}
        label={"Status"}
        getValueProps={(value) => {
          console.log(value); // 可用
          return {
            options: [{ label: "可用", value: "可用" }]
          };
        }}
      >
        <Select />
      </Form.Item>
    </Form>
  );
}

ReactDOM.render(<MyPage />, document.getElementById("root"));
```

### What is expected?
form.setFieldsValue时对应的options值可以显示到下拉框中

### What is actually happening?
form.setFieldsValue时对应的options值没有显示到下拉框中

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | Windows10 |
| Browser | Chrome86.0 |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-mvzu8
