### ISSUE TITLE
CheckboxGroup组件onChange事件返回的checkedList异常

### ISSUE THREAD

**Issue by chaserstrong** [ant-design/ant-design#27185]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-8wpb4)

### Steps to reproduce
搜索框输入 time 字符串，点击前两个选项，选项无法被选中。
偶发，有时候似乎又是可以的。换个浏览器或者怎么样子就会复现。

### What is expected?
点击的项应该都能被选中，checkList不应该返回[]空数组

### What is actually happening?
点击的项不能被选中，checkList返回了[]空数组

| Environment | Info |
|---|---|
| antd | 4.3.5 |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
You forgot key: https://codesandbox.io/s/antd-reproduction-template-forked-qlp25?file=/test.js

**Comment by afc163** [comment]
Also I suggest using `<Checkbox>{item}</Checkbox>`: https://codesandbox.io/s/antd-reproduction-template-forked-8wpb4?file=/test.js

**Comment by chaserstrong** [comment]
@afc163 谢谢，为啥加了key就没有这个问题了？option里的值也没有重复呀？

**Comment by afc163** [comment]
在 React 里 key 是必选的，和 antd 没关系。
