### ISSUE TITLE
feat: Affix[target]

### ISSUE THREAD

**Issue by benjycui** [ant-design/ant-design#2718]
Configurable target for `Affix`

**Comment by afc163** [comment]
http://getbootstrap.com/javascript/#affix-options

**Comment by benjycui** [comment]
`BackTop` 也需要同样的功能。

**Comment by benjycui** [comment]
等 BackTop 的也实现了，再关这个 issue

**Comment by benjycui** [comment]
BackTop 还是不支持了，不合理，由业务线的同学自行包装一层再用。
