### ISSUE TITLE
Doubts about select component in tags mode

### ISSUE THREAD

**Issue by alexchen1875** [ant-design/ant-design#27186]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/heuristic-booth-obe62?file=/index.js)

### Steps to reproduce
type some exist text  that's in options (搜索选项中已经存在的文本),
There will be two identical options in the options(选项中会存在两个一模一样的选项)

### What is expected?
only one match is show (相同的匹配项只显示一个)

### What is actually happening?
Two identical options (两个一模一样的选项)

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | windows |
| Browser | chrome  latest |

**Comment by Mongkii** [comment]
我会尝试修复

**Comment by appleshell** [comment]
这个问题跟Selec组件的搜索依据，即optionFilterProp属性有关，具体到Reproduction中的例子，设置optionFilterProp=“label"，可以解决。

**Comment by appleshell** [comment]
当option数据不是通过options属性传入，而是通过children的方式嵌套在Select中时，则需要设置optionFilterProp=“children"。

**Comment by alexchen1875** [comment]
如果本身是这样的话建议加到文档中,感谢
