### ISSUE TITLE
InputNumber控件聚焦，不能自动把全角转半角

### ISSUE THREAD

**Issue by enjoy-wind** [ant-design/ant-design#27194]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
InputNumber控件聚焦，不能自动把全角转半角

### What does the proposed API look like?
1.期望支持InputNumber，能传type属性。（“number”）,间接支持该功能。
2.或者自动支持全角转半角。

**Comment by afc163** [comment]
1. 能传：https://codesandbox.io/s/nice-leftpad-gtc6h?file=/index.js
2. 由于支持 formatter，需要能输入其他字符。
