### ISSUE TITLE
Upload组件的图片卡片样式，多次点击上传，取消后再次弹出上传窗口

### ISSUE THREAD

**Issue by WangXiZhu** [ant-design/ant-design#2719]
#### 本地环境
- antd 版本: 1.7.0

#### 你做了什么？
使用Upload组件的**图片卡片样式**，快速**多次点击**了上传按钮

#### 你期待的结果是：

像官网一样正常显示，点击取消不会弹出另外一个上传窗口

#### 实际上的结果：

点击当前窗口的‘取消’，弹出另外一个‘上传文件’窗口

#### 可重现的在线演示
[http://codepen.io/WangXiZhu/pen/YWBJqz?editors=001](http://codepen.io/WangXiZhu/pen/YWBJqz?editors=001)

**Comment by afc163** [comment]
浏览器原生 `input[type="file"]` 的行为，貌似没法修改。有好的优化建议可以直接 PR ~
