### ISSUE TITLE
upload picture-card 或者 picture 上传长图的时候会被自动截取，显示不正确

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#27190]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/upload-cn/#components-upload-demo-picture-card](https://ant.design/components/upload-cn/#components-upload-demo-picture-card)

### Steps to reproduce
上传一个长图，显示不对 https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1602838490340&di=435513885f60b599649f8bf7e09b65df&imgtype=0&src=http%3A%2F%2Fa1.att.hudong.com%2F05%2F00%2F01300000194285122188000535877.jpg 

### What is expected?
显示完全
![image](https://user-images.githubusercontent.com/47104575/96233628-e5e91400-0fca-11eb-98e7-369bdf561bad.png)

### What is actually happening?
其它部分消失了，例如脚
![image](https://user-images.githubusercontent.com/47104575/96233647-ee414f00-0fca-11eb-8543-648e4b4ef6a7.png)

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome |

**Comment by Kermit-Xuan** [comment]
这个就是这样设计的，默认是平铺，自己用样式覆盖就行了。

https://codesandbox.io/s/clever-platform-zshp6?file=/index.css

**Comment by linxianxi** [comment]
> 这个就是这样设计的，默认是平铺，自己用样式覆盖就行了。
> 
> https://codesandbox.io/s/clever-platform-zshp6?file=/index.css

我怎么不行，是先把图片保存到本地，再上传。不是一开始就写在 state 里。如果把 url 一开始定义在 fileList 里没有问题。但是重新上传就会是不对的。然后从控制台取这个 src，就是被截取的 src，不是完整的 src

**Comment by Kermit-Xuan** [comment]
demo 里面的上传 是 mock的接口，没有真正上传到服务器，所以用的默认卡片的预览图，正常情况下，可以在 onChange 里面拿到服务端链接，赋值给 `thumbUrl` 属性。

https://codesandbox.io/s/clever-platform-zshp6?file=/index.js

现在你再看看

**Comment by afc163** [comment]
我们可以把 `object-fit` 默认改成 `contain`，优先展示完整图片。

**Comment by Kermit-Xuan** [comment]
@linxianxi 欢迎PR～

**Comment by Kermit-Xuan** [comment]
> 我们可以把 `object-fit` 默认改成 `contain`，优先展示完整图片。

应该不止要改样式，我看卡片的那个预览图，应该是按照 cover 模式截取的。
