### ISSUE TITLE
希望在表格的最后一列可点击操作的a标签，点击出弹窗来查看该条记录详情

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#272]
希望在表格的最后一列可点击的操作a标签，点击通过弹窗看该条记录详情。
文档中：
{
  title: '操作',
  dataIndex: '',
  render: function(text, record) {
    return <span>
      <a href="javascript:;">操作一</a>
    </span>;
  }
}

试了直接在a上加 onClick="this.showModeal()，如下
{
  title: '操作',
  dataIndex: '',
  render: function(text, record) {
    return <span>
      <a href="javascript:;" onClick="this.showModeal()">操作一</a>
    </span>;
  }
}

但是报错
Uncaught TypeError: Cannot read property 'showModal' of undefined

我的代码如下，报错应该是因为this.showModal()不在return中：
 render: function() {
  	var columns = [{
		  title: '操作',
		  dataIndex: 'id',
		  render: function(text) {
		    return <a href="javascript:;" data-id={text} onClick={this.showModal}>查看</a>;
		  }
		}];
    return (
    	<div className="content">
    	    <Table  columns={columns} ... />
    	</div>
    );
问题是表格内容是动态生成，该怎么添加，就可以点击出现弹窗？

**Comment by zhujun24** [comment]
参考 [rc-table 里的展开实例](http://react-component.github.io/table/examples/expandedRowRender.html) 看看行不行

**Comment by zccst** [comment]
@zhujun24 谢谢你，已解决了我的问题。
但我有一个疑问，想一块探讨一下，就是把var columns = [{},{},...]; 定义放到render方法里，那么每次数据变化的时候都将调用render()，也就是执行一次columns定义，是不是效率不够高啊？

**Comment by zhujun24** [comment]
columns 不变的话，效率影响应该很小
