### ISSUE TITLE
antd tree with multi parents case

### ISSUE THREAD

**Issue by satyajitcet** [ant-design/ant-design#27205]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Multi parent scenario for a tree node will be useful to display family structure type data and to display the data where one employee reports to multiple managers.

### What does the proposed API look like?
currently i dont have this information. i am not sure also that  whether can we use current antd tree in multi parents case?

**Comment by afc163** [comment]
You can set different key for one employee but same label.
