### ISSUE TITLE
When mouse used to select value in Select, TreeSelect, Cascader or DatePicker the in Modal's Form the Modal get closed. 

### ISSUE THREAD

**Issue by yurib** [ant-design/ant-design#27208]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-steps-zi05x)

### Steps to reproduce
1 "New Collection" button 
2 observe modal form pop-up
3 use mouse to make a chose in `City`, `TreeSelect`,`Cascader` or `DatePicker`
4 observe premature form closing

### What is expected?
The form should stay until the modal window gets closed or the form canceled or submitted.

### What is actually happening?
The form gets closed preventing from filling it up completely

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | MacOS 10.14.6, Windows 2016 |
| Browser |  Chrome V:86.0.4240.80, Safary V14.0 (14610.1.28.1.10), Edge V:85.0.564.63  |

---
There was a similar issue before https://github.com/ant-design/ant-design/issues/12294, but no resolution found.
The problem looks like in the logic for `rc-dialog` package:
```
onWrapperClick = function onWrapperClick(e) {
      if (!contains(contentRef.current.getDOM(), e.target)) {
        onInternalClose(e);
      }
    };
```
Wrongly detect close event since dropdown element of the form input doesn't lay inside the DOM of the form

**Comment by afc163** [comment]
This bug is been fixed in https://github.com/react-component/dialog/pull/204: https://codesandbox.io/s/antd-reproduction-steps-forked-3m26o?file=/index.js

Please remove package-lock.json or yarn.lock and reinstall node_modules, make sure rc-dialog@8.4.2 installed.
