### ISSUE TITLE
Circular dependency when importing antd

### ISSUE THREAD

**Issue by pereiraguilherme** [ant-design/ant-design#27209]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/pereiraguilherme/olimpo/tree/integrateAntdButton](https://github.com/pereiraguilherme/olimpo/tree/integrateAntdButton)

### Steps to reproduce
 - npx create-react-library
 - import antd into ExampleComponent
 - run npm start

### What is expected?
Success build

### What is actually happening?
I'm trying to import antd to a college project and have issues when running npm start, which run `microbundle-crl watch --no-compress --format modern,cjs`. I'm getting an circular dependency message and the component does not work. I'm not sure what could be the cause, I need some help over this. Really need help on this! Thanks in advance!

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Ubuntu |
| Browser | Google Chrome |

---
I'm getting this message: 
```
Circular dependency: node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/config-provider/context.js -> node_modules/antd/es/config-provider/renderEmpty.js -> node_modules/antd/es/empty/index.js -> node_modules/antd/es/config-provider/index.js
Circular dependency: node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/config-provider/context.js -> node_modules/antd/es/config-provider/renderEmpty.js -> node_modules/antd/es/empty/index.js -> node_modules/antd/es/empty/empty.js -> node_modules/antd/es/config-provider/index.js
Circular dependency: node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/config-provider/context.js -> node_modules/antd/es/config-provider/renderEmpty.js -> node_modules/antd/es/empty/index.js -> node_modules/antd/es/empty/simple.js -> node_modules/antd/es/config-provider/index.js
Circular dependency: node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/config-provider/context.js -> node_modules/antd/es/config-provider/renderEmpty.js -> node_modules/antd/es/config-provider/index.js
Circular dependency: node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/message/index.js -> node_modules/antd/es/message/hooks/useMessage.js -> node_modules/antd/es/config-provider/index.js
Circular dependency: node_modules/antd/es/message/index.js -> node_modules/antd/es/message/hooks/useMessage.js -> node_modules/antd/es/message/index.js
Circular dependency: node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/notification/index.js -> node_modules/antd/es/notification/hooks/useNotification.js -> node_modules/antd/es/config-provider/index.js
Circular dependency: node_modules/antd/es/alert/index.js -> node_modules/antd/es/alert/ErrorBoundary.js -> node_modules/antd/es/alert/index.js
Circular dependency: node_modules/antd/es/dropdown/dropdown.js -> node_modules/antd/es/dropdown/dropdown-button.js -> node_modules/antd/es/dropdown/dropdown.js
Circular dependency: node_modules/rc-menu/es/SubPopupMenu.js -> node_modules/rc-menu/es/DOMWrap.js -> node_modules/rc-menu/es/SubMenu.js -> node_modules/rc-menu/es/SubPopupMenu.js
Circular dependency: node_modules/rc-picker/es/panels/YearPanel/index.js -> node_modules/rc-picker/es/panels/YearPanel/YearHeader.js -> node_modules/rc-picker/es/panels/YearPanel/index.js
Circular dependency: node_modules/rc-picker/es/panels/YearPanel/index.js -> node_modules/rc-picker/es/panels/YearPanel/YearBody.js -> node_modules/rc-picker/es/panels/YearPanel/index.js
Circular dependency: node_modules/rc-picker/es/panels/DecadePanel/index.js -> node_modules/rc-picker/es/panels/DecadePanel/DecadeHeader.js -> node_modules/rc-picker/es/panels/DecadePanel/index.js
Circular dependency: node_modules/rc-picker/es/panels/DecadePanel/index.js -> node_modules/rc-picker/es/panels/DecadePanel/DecadeBody.js -> node_modules/rc-picker/es/panels/DecadePanel/index.js
Circular dependency: node_modules/antd/es/input/Input.js -> node_modules/antd/es/input/ClearableLabeledInput.js -> node_modules/antd/es/input/Input.js
Circular dependency: node_modules/antd/es/checkbox/Checkbox.js -> node_modules/antd/es/checkbox/Group.js -> node_modules/antd/es/checkbox/Checkbox.js
Circular dependency: node_modules/antd/es/date-picker/generatePicker/index.js -> node_modules/antd/es/date-picker/generatePicker/generateSinglePicker.js -> node_modules/antd/es/date-picker/generatePicker/index.js
Circular dependency: node_modules/antd/es/date-picker/generatePicker/index.js -> node_modules/antd/es/date-picker/generatePicker/generateRangePicker.js -> node_modules/antd/es/date-picker/generatePicker/index.js
Circular dependency: node_modules/antd/es/list/index.js -> node_modules/antd/es/list/Item.js -> node_modules/antd/es/list/index.js
Circular dependency: node_modules/antd/es/modal/Modal.js -> node_modules/antd/es/modal/useModal/index.js -> node_modules/antd/es/modal/useModal/HookModal.js -> node_modules/antd/es/modal/ConfirmDialog.js -> node_modules/antd/es/modal/Modal.js
Circular dependency: node_modules/antd/es/modal/Modal.js -> node_modules/antd/es/modal/useModal/index.js -> node_modules/antd/es/modal/confirm.js -> node_modules/antd/es/modal/Modal.js
Circular dependency: node_modules/antd/es/space/index.js -> node_modules/antd/es/space/Item.js -> node_modules/antd/es/space/index.js
Circular dependency: node_modules/rc-tree/es/util.js -> node_modules/rc-tree/es/TreeNode.js -> node_modules/rc-tree/es/util.js
Circular dependency: node_modules/rc-tree/es/utils/treeUtil.js -> node_modules/rc-tree/es/util.js -> node_modules/rc-tree/es/TreeNode.js -> node_modules/rc-tree/es/utils/treeUtil.js
Circular dependency: node_modules/antd/es/tree/Tree.js -> node_modules/antd/es/tree/DirectoryTree.js -> node_modules/antd/es/tree/Tree.js
Circular dependency: node_modules/antd/es/upload/Upload.js -> node_modules/antd/es/upload/Dragger.js -> node_modules/antd/es/upload/Upload.js
'Fragment', 'PureComponent' and 'useReducer' are imported from external module 'react' but never used
'createPortal' is imported from external module 'react-dom' but never used

```

**Comment by afc163** [comment]
Just ignore these warnings.

**Comment by radiosilence** [comment]
@afc163 This seems to be a bad idea, parcel@2 builds are breaking due to circular dependencies.

**Comment by gcpantazis** [comment]
@afc163 I can also confirm that this breaks rollup builds. Would you be interested in a PR to fix?

**Comment by Awethentique** [comment]
Could this be due to an incorrect config?

I am getting this from rollup:
`
(!) `this` has been rewritten to `undefined`
https://rollupjs.org/guide/en/#error-this-is-undefined
node_modules/antd/es/alert/index.js
3: import _slicedToArray from "@babel/runtime/helpers/esm/slicedToArray";
4:
5: var __rest = this && this.__rest || function (s, e) {
                ^
6:   var t = {};
...and 1 other occurrence
node_modules/antd/es/affix/index.js
 7: import _typeof from "@babel/runtime/helpers/esm/typeof";
 8:
 9: var __decorate = this && this.__decorate || function (decorators, target, key, desc) {
                     ^
10:   var c = arguments.length,
11:       r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc,
...and 1 other occurrence
node_modules/antd/es/badge/index.js
3: import _extends from "@babel/runtime/helpers/esm/extends";
4:
5: var __rest = this && this.__rest || function (s, e) {
                ^
6:   var t = {};
...and 1 other occurrence

...and 72 other files

(!) Circular dependencies
node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/config-provider/context.js -> node_modules/antd/es/config-provider/renderEmpty.js -> node_modules/antd/es/empty/index.js -> node_modules/antd/es/config-provider/index.js
node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/config-provider/context.js -> node_modules/antd/es/config-provider/renderEmpty.js -> node_modules/antd/es/empty/index.js -> node_modules/antd/es/empty/empty.js -> node_modules/antd/es/config-provider/index.js
node_modules/antd/es/config-provider/index.js -> node_modules/antd/es/config-provider/context.js -> node_modules/antd/es/config-provider/renderEmpty.js -> node_modules/antd/es/empty/index.js -> node_modules/antd/es/empty/simple.js -> node_modules/antd/es/config-provider/index.js
...and 29 more`

**Comment by thyahan** [comment]
I facing similar warning, any update ?

**Comment by Zakariaels** [comment]
Is there any fix for this issue ?
I'm having the same warnings about antd circular dependencies.

**Comment by chenxiaochun** [comment]
@afc163 At least fix the easiest ones first

**Comment by chenxiaochun** [comment]
@Awethentique , about the `'this' has been rewritten to 'undefined'`, you can fix it:
```js
const config: RollupOptions = {
  ...
  onwarn: (warning) => {
    if (warning.code === 'THIS_IS_UNDEFINED') {
      return
    }
    console.error(warning.message)
  },
  ...
}
```

**Comment by georgezouq** [comment]
Any update or solution?

**Comment by IndProgo** [comment]
instead of 
```import { Button } from 'antd'```
use
```import Button from 'antd/es/button'```
