### ISSUE TITLE
Text area issues in large mode

### ISSUE THREAD

**Issue by israelKusayev** [ant-design/ant-design#27207]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-cwbkw?file=/index.js)

### Steps to reproduce
see codesandbox

### What is expected?
text area placeholder should be bigger in large mode
text area autosize should have the same height as regular input

### What is actually happening?
text area placeholder is the same size as middle
text area autosize is the same size as middle

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.14.0 |
| System | windows 10 |
| Browser | chrome 86 |

**Comment by prime417** [comment]
Can i work on the issue ?

**Comment by xrkffgg** [comment]
@prime417 PR welcome~

**Comment by afc163** [comment]
Supported in https://github.com/ant-design/ant-design/pull/27110
