### ISSUE TITLE
升级到v4，Tree组件展开节点时，出现闪动

### ISSUE THREAD

**Issue by decadef20** [ant-design/ant-design#27215]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/crazy-ride-chnrb?file=/index.js)

### Steps to reproduce
点击根节点和子节点

### What is expected?
不应该出现元素闪动

### What is actually happening?
内容过长的节点不应该闪动

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.11.0 |
| System | mac 10.13.6 |
| Browser | Chrome Version 86.0.4240.75  |

**Comment by decadef20** [comment]
请问这个不算bug吗？

**Comment by zombieJ** [comment]
是你的样式覆盖问题，不是 antd 的 bug。

**Comment by dream-unicorn** [comment]
这就是 antd 的bug
