### ISSUE TITLE
The virtual list of select component is blank accidentally 

### ISSUE THREAD

**Issue by becarchal** [ant-design/ant-design#27210]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/select-demo-virtual-blank-mvpr1?file=/src/index.js)

### Steps to reproduce
1、Enter 333 in the select component
2、Select the item333 option
3、Select the select component again
4、Virtual list renders white space occasionally, and no scroll bar

### What is expected?
The virtual list is always rendered normally, and the scroll bar position is accurately positioned.

### What is actually happening?
Virtual list occasionally white screen, and no scroll bar.

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | win10 |
| Browser | chrome  84.0.4147.105 |

---
The actual business is a virtual select of more than 500 pieces of data. When step 4 occurs, the console does not report an error. Observe the DOM render node with option in the DOM tree, and translateY is also 0. But the virtual list is rendered blank.Thx, we will communication more details as possible.

**Comment by becarchal** [comment]
step 4 screenshot 
![select-blank](https://user-images.githubusercontent.com/20692744/96366074-d5c26780-1177-11eb-9d93-4524927e9ff0.png)

**Comment by afc163** [comment]
Did antd 4.7.1 resolved this problem? https://codesandbox.io/s/select-demo-virtual-blank-forked-zesc1

**Comment by zombieJ** [comment]
Your demo do not reproduce the issue. Could you provide a gif?

**Comment by junaid7lone** [comment]
I'm facing similar issue when is open dropdown and scroll and click outside then I focus on select field the list shows up empty. It seems like the translateY style is not getting updated until I try to scroll in the dropdown then only the list shows up.
I'm currently on 4.1.4 . Here is a video i have recorded of the issue.
https://www.awesomescreenshot.com/video/1436008?key=7af1bd1421c4893c960b5406d7bbf462

**Comment by zombieJ** [comment]
@junaid7lone , there exist scroll bug on old antd version. could you upgrade antd version and try again?

**Comment by shlomi-ozon** [comment]
we have a similar issue when we check it on safari (on chrome everything looks ok),  we are using version 4.3.3 (I tried to upgrade to the newest and it didn't resolve that).
We create a Select with a search that contains 140~ options.
when the user clicks the select on the first time he sees an empty list. if he scrolls the list will show up.
part of the time he can see the list and part of the time he can't.

how it looks when he can't:
<img width="405" alt="Screen Shot 2020-10-26 at 11 58 46" src="https://user-images.githubusercontent.com/58909420/97159936-470ba700-1784-11eb-85f3-531afe01c66e.png">

how the item looks when you take a look in the dev tools:
<img width="944" alt="Screen Shot 2020-10-26 at 11 59 00" src="https://user-images.githubusercontent.com/58909420/97160030-6e627400-1784-11eb-86cc-165fb3528909.png">

you can see that the translateY is 0.

and when it is ok:
![picForApiTest](https://user-images.githubusercontent.com/58909420/97160122-905bf680-1784-11eb-982f-8fb8128adab7.jpg)

**Comment by zombieJ** [comment]
@shlomi-ozon, could you help to provider your reproduce? thx

**Comment by dospolov** [comment]
have the same issue
ant version: 4.10.2
started from version: ~4.6.2 
browser: firefox latest
react: latest
os: centos 7

**Comment by yoyo837** [comment]
Could you help to provider your reproduce to open a new issue？

**Comment by AthithyanRengaswamy** [comment]
We are running version: 4.3.1, the issue still exist

**Comment by sandeepfareye** [comment]
I am running version: 4.24.7, and still facing similar issue
