### ISSUE TITLE
点击收缩菜单（collapsed=true）时会导致应该隐藏的二级子菜单依然显示（个人觉得由于修复 #26817导致）

### ISSUE THREAD

**Issue by Gray-coder** [ant-design/ant-design#27214]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost:7790/pb/home](http://localhost:7790/pb/home)

### Steps to reproduce
https://codesandbox.io/s/4oenu
通过这个例子改写的

### What is expected?
点击收缩菜单（collapsed=true）时会应该隐藏二级子菜单

### What is actually happening?
点击收缩菜单（collapsed=true）时依旧显示二级子菜单

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | react |
| System | windows |
| Browser | chrome |

---
因为是内网系统，重现链接暂无。

**Comment by Kermit-Xuan** [comment]
应该和这个的问题一样，https://github.com/ant-design/ant-design/issues/26905

**Comment by nuintun** [comment]
@Kermit-Xuan 修复了吗，看 V4.7.1 问题还在。

**Comment by Kermit-Xuan** [comment]
还没有，我计划这周修复，下周发新版本的时候会带上。

**Comment by nuintun** [comment]
@Kermit-Xuan 👍
