### ISSUE TITLE
优化Modal的遮罩显示

### ISSUE THREAD

**Issue by peakandyuri** [ant-design/ant-design#27217]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当Modal同时显示过多，遮罩层叠加显示为深黑色，对于用户体验不够好

### What does the proposed API look like?
优化modal的dom结构渲染，从ModalA弹出ModalB，隐藏ModalA的遮罩，关闭ModalB后重新显示，如果ModalB没有显示遮罩，则ModalA不做隐藏遮罩的操作

Modal的遮罩也包括Drawer组件

**Comment by hengkx** [comment]
同时 多个 Modal 这种本来就不是很推荐吧

**Comment by afc163** [comment]
叠加显示为深黑色更容易让用户意识到打开了多个对话框，设计上不建议进行去重。

**Comment by peakandyuri** [comment]
> 叠加显示为深黑色更容易让用户意识到打开了多个对话框，设计上不建议进行去重。

企业级应用中，多层模态窗口是很正常的情况，比如弹出一个表单模态窗口，表单中又有选择的数据的模态窗口，况且为什么要让用户意识到打开几个对话框呢？感觉你们的思维还是有些狭隘。

**Comment by Kermit-Xuan** [comment]
遮罩层叠加显示为深黑色，对于用户体验不够好，具体不好在哪里呢？

你提出的这种设计具体好在哪里呢？

**Comment by peakandyuri** [comment]
> 遮罩层叠加显示为深黑色，对于用户体验不够好，具体不好在哪里呢？
> 
> 你提出的这种设计具体好在哪里呢？

遮罩的作用是提示用户不能操作模态窗口后面的东西，如果是透明的，用户感觉不到，所以会有一个半透明的层来提示到用户，但如果多个半透明的遮罩层叠加整个背景就不断加深，整个背景就接近或者就是全黑了，很难看，用户体验也不仅仅是操作上的 便捷，也包含UI的显示。
