### ISSUE TITLE
Wrong anchor jump on official website

### ISSUE THREAD

**Issue by hengkx** [ant-design/ant-design#27224]

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/97084246-5d144d00-1648-11eb-8fd3-a7e3506df69f.png)
打开任意一个组件 点击api后 滚动到顶部 然后再次打开改网址

**Comment by afc163** [comment]
>  打开任意一个组件 点击api后 滚动到顶部 然后再次打开改网址

没懂。
