### ISSUE TITLE
官网打开特别特别慢

### ISSUE THREAD

**Issue by wengcd** [ant-design/ant-design#2722]
![1 pic_hd](https://cloud.githubusercontent.com/assets/2403371/17685851/562d7210-639a-11e6-9504-3944504eb551.jpg)

就是这样... 刷新，也一样，换网络也一样，过一周也一样

**Comment by afc163** [comment]
翻墙。

**Comment by afc163** [comment]
加了一层代理优化了一下，现在应该快多了。
