### ISSUE TITLE
CheckboxGroup TS type error in v4.7.1

### ISSUE THREAD

**Issue by ArronYR** [ant-design/ant-design#27230]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/4.7.0/components/checkbox/Group.tsx](https://github.com/ant-design/ant-design/blob/4.7.0/components/checkbox/Group.tsx)

### Steps to reproduce
在`Demo.tsx`中使用`Checkbox.Group`生成对应的`Checkbox`组：
```javascript
<Checkbox.Group>
  {Object.keys(keys).map((key) => {
    return (
      <Checkbox value={key} key={key}>{formatMessage({ id: keys[key].label })}</Checkbox>
    );
  })}
</Checkbox.Group>
```
其中`keys`结构如下：
```json
const keys = {
  "a": {
     "label": "A"
  }
  "b": {
     "label": "B"
  }
}
```
项目开启了`tslint`，如上代码在`4.7.0`之前没有提示错误，升级到`4.7.1`之后在`Checkbox.Group`上出现以下提示：
```
TS2559: Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & CheckboxGroupProps'.
```

### What is expected?
无报错

### What is actually happening?
提示以下信息：
```
TS2559: Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & CheckboxGroupProps'.
```

| Environment | Info |
|---|---|
| antd | 4.7.1 |
| React | 16.12.0 |
| System | Mac 10.14.6 (18G6020) |
| Browser | Chrome 85.0.4183.83 |

**Comment by afc163** [comment]
@hengkx 看看这个。

**Comment by ArronYR** [comment]
截图如下所示：
![image](https://user-images.githubusercontent.com/7171192/96414783-27bec800-1220-11eb-88eb-a79424f48dfb.png)

**Comment by holynova** [comment]
类似错误还有<Upload>
```
Type '{ children: Element; className: string; accept: string; showUploadList: boolean; customRequest: ({ file }: { file: any; }) => Promise<void>; }' is not assignable to type 'IntrinsicAttributes & UploadProps<any> & RefAttributes<any>'.
      Property 'children' does not exist on type 'IntrinsicAttributes & UploadProps<any> & RefAttributes<any>'.
```

**Comment by hengkx** [comment]
> 类似错误还有 Upload组件, 也不支持children了
> 
> ```
> Type '{ children: Element; className: string; accept: string; showUploadList: boolean; customRequest: ({ file }: { file: any; }) => Promise<void>; }' is not assignable to type 'IntrinsicAttributes & UploadProps<any> & RefAttributes<any>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & UploadProps<any> & RefAttributes<any>'.
> ```

@holynova 这个组件的？

**Comment by hengkx** [comment]
Upload没发现问题 @holynova 

![image](https://user-images.githubusercontent.com/8358236/96417497-f21bde00-1223-11eb-98d5-2fbe5bcd0ef3.png)

**Comment by Kermit-Xuan** [comment]
> 类似错误还有 Upload组件, 也不支持children了
> 
> ```
> Type '{ children: Element; className: string; accept: string; showUploadList: boolean; customRequest: ({ file }: { file: any; }) => Promise<void>; }' is not assignable to type 'IntrinsicAttributes & UploadProps<any> & RefAttributes<any>'.
>       Property 'children' does not exist on type 'IntrinsicAttributes & UploadProps<any> & RefAttributes<any>'.
> ```

Upload 组件已经修复了。

**Comment by afc163** [comment]
https://stackoverflow.com/a/55186392/3040605
