### ISSUE TITLE
TreeSelect组件，当treeCheckStrictly为true时，能做到设置labelInValue为false。

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#27233]
- [ ∨ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
treeCheckStrictly的说明：
Whether to check nodes precisely (in the checkable mode), means parent and child nodes are not associated, and it will make labelInValue be true.

不太明白为啥treeCheckStrictly为true时，labelInValue就必须为true。

想做到treeCheckStrictly为true时，labelInValue仍保持为false。

### What does the proposed API look like?
想做到treeCheckStrictly为true时，labelInValue仍保持为false。

**Comment by zombieJ** [comment]
`treeCheckStrictly` 后，value 里会包含 `halfChecked` 的值标识选项是否是半勾选。如果不需要这个功能，建议自行封装一下 TreeSelect 组件。
