### ISSUE TITLE
Official website does not load css

### ISSUE THREAD

**Issue by sonnguyenvn32** [ant-design/ant-design#27235]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/](https://ant.design/)

### Steps to reproduce
Enter https://ant.design/

### What is expected?
The page should load with CSS.

### What is actually happening?
Enter the official site does not render properly.

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16 |
| System | macos |
| Browser | chrome Version 86.0.4240.80 |

**Comment by yoyo837** [comment]
Can not reproduce. Could you check your network environment first?

**Comment by sonnguyenvn32** [comment]
@yoyo837 , could you re-check this after clearing browser's caches ?

**Comment by yoyo837** [comment]
Yes, it works well.

**Comment by Cremz** [comment]
I'm having an issue with the JS on the official site. I get
`Uncaught SyntaxError: Invalid or unexpected token index-9f8f426a.js:356`
Tried in chrome (incognito as well) and in Firefox (never accessed the site on that one). Doesn't seem to be caused by cache. 
Most of the functionality is down. Can't see the code for a particular element, can't open the links to codesandbox.
Didn't want to open a separate issue as it's still related to the official website

**Comment by Kihoshi** [comment]
at official website , tried clear browser cache, local storage ,cookies
most of the dropdown after click, options won't appear  
couldn't expand example code  
in console, Uncaught SyntaxError: Invalid or unexpected token  /index-9f8f426a.js:356

**Comment by yoyo837** [comment]
@Cremz @Kihoshi When you got this js error, did the css load?

**Comment by DEPREZR** [comment]
I have exactly the same error: Uncaught SyntaxError: Invalid or unexpected token /index-9f8f426a.js:356
Css is loaded, but for example I can't show code in examples of documentation.

**Comment by Cremz** [comment]
all resources load fine, website looks okay, some of the js links/events don't work because of the error. you can still navigate through the site using the left menu

**Comment by Kihoshi** [comment]
now back to normal, working fine

**Comment by xrkffgg** [comment]
Clear browser cache and force refresh.
