### ISSUE TITLE
Rerender/Force Load tab pane if a tab is clicked.

### ISSUE THREAD

**Issue by arpitmalik** [ant-design/ant-design#27234]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If I have to make an API call in one tab to render contents in a table and I want - that API call should be made everytime I click on that particular tab. Basically it forceRenders the contents in that tab (and makes the API calls and all without reloading the whole page)

### What does the proposed API look like?
forceRender=true

**Comment by afc163** [comment]
You can try `destroyInactiveTabPane`.

**Comment by arpitmalik** [comment]
Please add this to the documentation as it is not visible there. Thanks.

**Comment by afc163** [comment]
@arpitmalik PR is welcome~

**Comment by arpitmalik** [comment]
Is there any functionality so that I can apply this `destroyInactiveTabPane` for a single tab pane and not for all of them? So basically if I need to destroy only single tab pane out of 10 I have^
