### ISSUE TITLE
Table不兼容

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2723]
#### 本地环境

- antd 版本: 1.9.0
- 操作系统及其版本：Ubuntu 16.04 (64-bit)
- 浏览器及其版本: 51.0.2704.79 Ubuntu 16.04 (64-bit)

#### 你做了什么？

引入 antd 的 Table, 并使用了columnsPageRange， columnsPageSize属性

#### 你期待的结果是：

能正常显示

#### 实际上的结果：

左侧箭头丢失， 1.9.0前是可以的

#### 可重现的在线演示

http://codepen.io/coderingz/pen/ZOPzmw

**Comment by afc163** [comment]
你的例子里没有 columnsPageRange、columnsPageSize

**Comment by codering** [comment]
@afc163 更新了 http://codepen.io/coderingz/pen/ZOPzmw
