### ISSUE TITLE
Input showcount not showing when Form is parent

### ISSUE THREAD

**Issue by nappalm** [ant-design/ant-design#27242]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/icy-butterfly-7c8bz?file=/src/App.js:0-328)

### Steps to reproduce
Visualize showCount input into Form

### What is expected?
https://codesandbox.io/s/jgceh

### What is actually happening?
Not show the "showCount"

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Linux |
| Browser | Chromium |

**Comment by hengkx** [comment]
showCount only support TextArea
