### ISSUE TITLE
Modal: change the route by clicking the browser back button while any modal is open will lead to disable browser scroll

### ISSUE THREAD

**Issue by HDaghash** [ant-design/ant-design#27243]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://dwo1l.csb.app/](https://dwo1l.csb.app/)

### Steps to reproduce
NOTE: This bug will not be reproducible on codesandbox since codesandbox refreshing the page on browser back & forward button click and this is not the case in noraml  react app environment.

steps to reproduce :

- Open any page in your application .
- Naviagte to another page contain modal and open it.
- Go back to the first page without closing the modal by using the browser back button.
- Observie the result: browser will disable scrolling up and down.

this hapinging for all versions after 4.7 & 4.7.1 & 4.7.2

while by downgrading to 4.6.6 will not facing this issue.

### What is expected?
Browser should not disable scrolling

### What is actually happening?
Scrolling is disable untile you refresh the page

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.13.1 |
| System | 4.x.x |
| Browser | Chrome 85 |

**Comment by afc163** [comment]
You can use a github repo to reproduce.

**Comment by colonel-badmotherfucker** [comment]
@HDaghash were you able to solve the issue ?
