### ISSUE TITLE
Tabs如何去掉快捷键的绑定

### ISSUE THREAD

**Issue by liangzhuang327** [ant-design/ant-design#27248]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://2x.ant.design/components/tabs-cn/](https://2x.ant.design/components/tabs-cn/)

### Steps to reproduce
点击一个tab，按键盘上的上下箭头，会自动触发tab的切换

### What is expected?
期望暴露参数给使用者，使使用者能干预是否开启快捷键切换的功能

### What is actually happening?
现在没有API可以干预这个功能，个人使用需求需要自定义快捷键，不需要控件的快捷键行为

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | mac |
| Browser | chrome |

**Comment by afc163** [comment]
antd 2.x 不维护了。

**Comment by liangzhuang327** [comment]
我看了遍源码，因为antd在封装rc时候没有向开发者暴露此API，本想从写这个插件，但发现rc-tabs的插件涉及的组建比较多，就放弃了，本人用以下方式屏蔽了源码中对根组建keydow的监听
`addEventListener(document.getElementsByClassName('ant-tabs')[0], 'keydown',function(e){
    e.stopImmediatePropagation();
  e.preventDefault();
})`
