### ISSUE TITLE
setting prefixCls using ConfigProvider breaks styling

### ISSUE THREAD

**Issue by jasan-s** [ant-design/ant-design#27245]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/infallible-feistel-2k930?file=/src/App.js)

### Steps to reproduce
wrap App component with ConfigProvider and pass in prefixCls. 

### What is expected?
The button should be with backgrounf blue when set to type = primary

### What is actually happening?
the button has no background. the stylesfrom import "antd/dist/antd.css"; are still referencing ant prefix

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.14.0 |
| System | MAC OSX |
| Browser | chrome |

**Comment by hengkx** [comment]
https://ant.design/components/config-provider/#API

**Comment by jasan-s** [comment]
@hengkx  docs are unclear , can you please clarify that if im using prefixCls in ConfigProvider as shown in https://ant.design/components/config-provider/#API, does that require me to build custom antd.css file with using prefixCls?

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/96528090-5e462280-12b4-11eb-8374-b9b3d309f761.png)

https://ant.design/docs/react/customize-theme    You need change `@ant-prefix`

**Comment by jasan-s** [comment]
@hengkx  liek this?
```
const CracoLessPlugin = require('craco-less');

module.exports = {
  plugins: [
    {
      plugin: CracoLessPlugin,
      options: {
        lessLoaderOptions: {
          lessOptions: {
            modifyVars: {
              '@ant-prefix': 'custom',
            },
            javascriptEnabled: true,
          },
        },
      },
    },
  ],
};
```

**Comment by zombieJ** [comment]
@jasan-s , could you help to improve doc? : )

**Comment by jasan-s** [comment]
@zombieJ yes i can. updating `index.en-US.md` for the specific component should update the docs on the site right?

**Comment by zombieJ** [comment]
Pls feel free to create PR : )
