### ISSUE TITLE
Button event targets the text/SVG icon rather than the button itself depending on where it is clicked

### ISSUE THREAD

**Issue by Shirley-Hody** [ant-design/ant-design#27241]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-z4seo?file=/index.js)

### Steps to reproduce
- Create a button with an `icon` and or some text and an `onClick` event, and add for example a `value`.
- Have an event printing the event when clicked, and try accessing the button's value
- Click on the icon in the button: target is the SVG, cannot access value
- Click on the text in the button: target is the SPAN, cannot access value
- Click on any other blank part of the button: target is the button, can access the value

### What is expected?
Before v4, it worked fine. Wherever you clicked on the button (the white part, the text, the icon), you could access the button itself in the event target

### What is actually happening?
The span or svg is returned as the target instead when clicked on those parts

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | react 16.13.1 |
| System | Windows 10 |
| Browser | Chrome 86.0.4240.75 |

**Comment by afc163** [comment]
You should use `event.currentTarget`, this is intented behavior for https://github.com/ant-design/ant-design/pull/24095
