### ISSUE TITLE
最新(1.9.0)Table组件，Warning: validateDOMNesting(...): <noscript> cannot appear as a child of 

### ISSUE THREAD

**Issue by codering** [ant-design/ant-design#2724]
#### 本地环境

- antd 版本: 1.9.0
- 操作系统及其版本：Ubuntu 16.04 (64-bit)
- 浏览器及其版本: 51.0.2704.79 Ubuntu 16.04 (64-bit)
- React 0.14.8

#### 你做了什么？

引入 antd 的 Table

#### 你期待的结果是：

像官网一样正常显示

#### 实际上的结果：
升级到1.9.0后，首次进入使用table组件的页面，有如下提示
```
Warning: validateDOMNesting(...): <noscript> cannot appear as a child of <tr>. See Root > Router > RouterContext > Test > Table > Table > TableRow > tr > noscript.
```

#### 可重现的在线演示

暂时无法重现

**Comment by codering** [comment]
刚刚用react@15.3.0试了下，没问题。。。。

**Comment by afc163** [comment]
把代码给出来。

**Comment by codering** [comment]
@afc163 问题查出来了，是由于dataSource为空时处理不当造成的。
你看下演示demo, http://codepen.io/coderingz/pen/wWOagg?editors=1111

**Comment by ddcat1115** [comment]
@codering  其实是有合并单元格情况时，会出现这个警告。被合并的单元格会return null，react@0.14 会解析为<noscript>，放在<tr>里就警告了，react@15.x 开始解析为html注释就没问题。

貌似没有太好的解决方法，只能要么升级，要么忍受warning了...

**Comment by codering** [comment]
@ddcat1115 我给的demo里并没有合并设置。

**Comment by ddcat1115** [comment]
对data为空的处理就是把所有列合并为一个单元格，render一个『暂无数据』或'nodata'的结构

**Comment by codering** [comment]
没具体看源码，1.9以前的版本是没问题的

**Comment by ddcat1115** [comment]
因为1.9以前对于空数据不是这种处理方式，为了处理定位问题才改的。单元格合并警告的问题应该是一直都在的

**Comment by codering** [comment]
关键是 首次渲染才会提示这个问题， 后面的渲染无论dataSource是否为空数组都没问题。
可否对首次渲染做下特殊处理？:confused:

**Comment by codering** [comment]
不知道  `return null`  改成 `return <td clasaName='hide'>` 是否可行？

**Comment by ddcat1115** [comment]
恩，这样可以避免警告，但感觉上是为了老版本的react把代码弄得略奇怪，毕竟原生table都不需要把已经合并的单元格再写出来 😿

**Comment by codering** [comment]
我有点奇怪啊，数据都没有，应该只需要一次tablecell渲染就ok了才对啊

**Comment by ddcat1115** [comment]
没数据时会塞入一行假数据以调用column render渲染『nodata』

**Comment by codering** [comment]
@ddcat1115  
在 https://github.com/ddcat1115/table/blob/master/src/TableRow.jsx#L89 前面加个判断可行吗？
```js
   if (record.key === 'empty' && i > 0) {
         continue
   }
```

**Comment by ddcat1115** [comment]
感觉空数据的处理只是在antd-table层面自己实现的，在rc-table中还有特殊逻辑来控制不是太好...

**Comment by ddcat1115** [comment]
先关了，有更好的解决方案欢迎pr~
