### ISSUE TITLE
Menu置于flex元素内无法根据元素宽度自动缩略

### ISSUE THREAD

**Issue by ppmmwozuiai** [ant-design/ant-design#27240]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/great-maxwell-u6etf?file=/src/App.js)

### Steps to reproduce
将Menu（mode=horizontal）置于普通容器内在容器宽度不足时，Menu会自动缩略。但如果将Menu置于flex容器的子元素内时，无法根据其父元素的宽度自动缩略。
然而，我发现antd pro实现了这点，但是从样式上并没有找出特别的地方。

### What is expected?
Menu在flex元素内自动缩略

### What is actually happening?
无法缩略

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.13.x |
| System | windows |
| Browser | chrome\edge |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/36604
