### ISSUE TITLE
Add column name to Table rowExpandable

### ISSUE THREAD

**Issue by tamaraita** [ant-design/ant-design#27244]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
I need to be able to disable the expand of a row only for a single column. Right now I can only receive the full record of the row and from there there's no way for me to be able to disable the expanding of the row.
In the column that I need to disable the expanding, I have an icon that opens a Modal. Whenever I click on the icon and the Modal opens, it also expands the row.

### What does the proposed API look like?
expandable should have the rowExpandable prop as:
```
{
....,
rowExpandable: (record, columnName or index) => boolean
}
```

**Comment by afc163** [comment]
> I need to be able to disable the expand of a row only for a single column

I don't understand this, it doesn't make sense. Could you provide a screenshot or a reproduce codesandbox? https://u.ant.design/codesandbox-repro

**Comment by afc163** [comment]
Closing for no response.
