### ISSUE TITLE
Floating Layout Sider

### ISSUE THREAD

**Issue by marian2js** [ant-design/ant-design#27249]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
A floating sider has a much better usability for mobiles in my personal opinion. And Design Pro implements this type of sider for small screens ([see here](https://preview.pro.ant.design/)). A mask is added in top of the page body and the sider can be closed by clicking outside it.

### What does the proposed API look like?
floating: boolean (default false for backward compatibility).

```
<Layout.Sider floating={true}>...</Layout.Sider>
```

**Comment by afc163** [comment]
You can use [rc-drawer](https://github.com/react-component/drawer/) with Sider for this feature, I prefer not to implement it in antd.
