### ISSUE TITLE
<Tree> Version 3 to 4 upgrade appeared 'children of Tree is deprecated. Please use treeData instead'

### ISSUE THREAD

**Issue by qianbin123** [ant-design/ant-design#27257]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/migration-v4](https://ant.design/docs/react/migration-v4)

### Steps to reproduce
```js
<Tree
       onExpand={this.onExpand}
       expandedKeys={expandedKeys}
       autoExpandParent={autoExpandParent}
       checkStrictly={true}
>
       {loop(tree_list_data_childrenList)}
</Tree>
                          
<Tree
       onExpand={this.onExpand}
       expandedKeys={expandedKeys}
       autoExpandParent={autoExpandParent}
       checkStrictly={true}
       treeData={tree_list_data_childrenList}
>
</Tree>
````

### What is expected?
Eliminate warning , and join in V3 to V4 document

### What is actually happening?
Show warning, and  V3 to V4 document no comment ! !

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16 |
| System | Mac OS |
| Browser | Chrome 85 |

---
antd官方V3升级V4文档说明中，并没有注明关于Tree组件升级时，需要把Tree的内容以treeData形式传入，导致有警告出现

**Comment by DAHU123** [comment]
这个问题解决了吗？那个treeData貌似不能放JSX，放进去的话，不能正常显示的；我现在用的antd的版本号是4.7.3。代码如下：
`
export default class LeftTree extends Component<TreeProps, TreeState> {
  constructor(props: TreeProps) {
    super(props)
    const initArr = [
      {
        title: 'parent 1',
        id: 1,
        key: '0-0',
        isEdit: false,
        children: [],
      },
    ]
    const arr = props.isInitAdd ? initArr : []
    this.state = {
      treeData: arr
    }
  }

  onSelect = (selectedKeys: any, info: any) => {
    console.log(selectedKeys)
    console.log(info)
  }

  // @ts-ignore
  genTreeNode = (treeData: Array<any>) => {
    // @ts-ignore
    return treeData.map((item: TreeNodeItem) => {
      if (item.children.length > 0) {
        return this.genTreeNode(item.children)
      }
      return (
        <TreeNode key={item.key} title={this.renderTitle(item)} />
      )
    })
  }

  renderTitle = (item: TreeNodeItem) => {
    return (
      <>
        <span>{item.title}</span>
        <Button type="link" shape="circle" icon={<PlusOutlined />} />
        <Button type="link" shape="circle" icon={<MoreOutlined />} />
        <Button type="link" shape="circle" icon={<FormOutlined />} />
      </>
    )
  }

  EmptyNode = () => (
    <TreeNode key='0-0' title='暂无数据' />
  )

  render() {
    const { treeData = [] } = this.state
    return (
      <Tree
        showLine
        switcherIcon={<DownOutlined />}
        onSelect={this.onSelect}
        treeData={treeData.length > 0 ? this.genTreeNode(treeData) : this.EmptyNode()}
       />
    )
  }
}

`
![image](https://user-images.githubusercontent.com/28329138/97399757-bf12d200-1928-11eb-846d-a348bd2c337c.png)
