### ISSUE TITLE
Tabs type="editable-card" 时，activeKey不起作用

### ISSUE THREAD

**Issue by yimi8126** [ant-design/ant-design#2725]
新增标签时设置activeKey时，tab没有切换
#### 本地环境

- antd 版本:最新版本
- 操作系统及其版本：
- 浏览器及其版本:

#### 可重现的在线演示

http://ant.design/components/tabs/
最后一个例子就可以重现

**Comment by afc163** [comment]
duplicate #2721

**Comment by yimi8126** [comment]
不是一个问题，是新增tab的时候设置当前的activeKey为新增的tab时不起作用，activeKey我看是对的

**Comment by afc163** [comment]
应该是同一个问题导致的。
