### ISSUE TITLE
Input.Search 显示不全

### ISSUE THREAD

**Issue by fwh1990** [ant-design/ant-design#27258]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://www.baidu.com](http://www.baidu.com)

### Steps to reproduce
```css
.search {
  width: 30%
}
```

```jsx
<Input.Search className="search" />
```

### What is expected?
像4.7.0一样正常渲染
![0D531333-F765-4CE6-A7D1-6DDD65322940](https://user-images.githubusercontent.com/11069720/96564696-16e08600-12f6-11eb-955f-36286c06eb81.png)

### What is actually happening?
className被复制到子标签，导致显示不全

![4B6281E2-F239-4ED0-9BCA-EC09875E1F2F](https://user-images.githubusercontent.com/11069720/96564429-bc472a00-12f5-11eb-9410-3c38148b3d08.png)

| Environment | Info |
|---|---|
| antd | 4.7.1 |
| React | 16.14.0 |
| System | Macos 10.15.6 |
| Browser | Chrome latest |

**Comment by fwh1990** [comment]
截图已经给你们了。。！还不够清楚吗？

**Comment by fwh1990** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-v2wvl

`allowClear`是关键

**Comment by fwh1990** [comment]
4.7.0没这个问题

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/27129
