### ISSUE TITLE
<Select> menu disappears after show on React 17 with Shadow Dom.

### ISSUE THREAD

**Issue by pricco** [ant-design/ant-design#27250]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-t5pxq?file=/index.js)

### Steps to reproduce
Click on the Select component, the menu appears for less than a second and then it disappears. 

### What is expected?
Show the select menu.

### What is actually happening?
The select menu disappear.

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | react@17.0.0-rc.3 |
| System | Mac OSX Catalina |
| Browser | Chrome |

**Comment by afc163** [comment]
Checking https://github.com/react-component/select/pull/575

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/select/releases/tag/v12.1.3
