### ISSUE TITLE
【style】Space组件自定义分隔符可否取消margin边距设置

### ISSUE THREAD

**Issue by hanguihe** [ant-design/ant-design#27252]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
间隔看起来舒服一点

### What does the proposed API look like?
无

### 问题说明
https://ant.design/components/space-cn/#components-space-demo-split

例如官网的例子使用Divider分隔符后仍然有4px的右边距，再加上Divider的宽度感觉有点太宽了

<img width="261" alt="截屏2020-10-20 上午11 08 16" src="https://user-images.githubusercontent.com/29910482/96535520-948b9e00-12c4-11eb-9a44-3be5e1f8c3de.png">

**Comment by hanguihe** [comment]
提了PR，老哥们看看可以接受吗🤣

**Comment by hengkx** [comment]
这个可以自定义大小吧
