### ISSUE TITLE
autocomplete component allowClear=true X component is not clickable when viewed on mobile

### ISSUE THREAD

**Issue by marioguy08** [ant-design/ant-design#27262]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/customized-ant-design-demo-forked-ucfgo?fontsize=14&hidenavigation=1&theme=dark)

### Steps to reproduce
I was able to reproduce this in the code sandbox by simply adding allowClear="true" to the autocomplete object. I Did this on my phone and I could not click the X button when something was typed so this is definitely a bug on your end.

### What is expected?
I should be able to click the X button on mobile

### What is actually happening?
I cannot click the X button when viewing on mobile. It works fine otherwise.

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | Latest version |
| System | Latest version |
| Browser | Latest version |

**Comment by afc163** [comment]
Is it still happen in antd@4.19.2 ?

**Comment by amed** [comment]
I confirm that this issue still exists on the latest version `v4.20.6`. 

The used device:
**iPhone SE (iOS 15.5 simulator)** 

reproduce link:
https://codesandbox.io/s/antd-reproduction-template-forked-0iw4eo?file=/index.js

The issue appear on real devices, integrated browser mobiles does not work.

https://user-images.githubusercontent.com/5637272/174579014-e097217c-04d0-4aa3-b055-9b4fb32062b1.mp4

**Comment by fitterfizzle** [comment]
This is still an issue with the latest version of ant v5.12.1 @afc163
