### ISSUE TITLE
需求: Image 组件增加预览 video 的功能

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#27269]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
一般图片和视频会一起上传，需要一起预览的功能

### What does the proposed API look like?
type="image"  or type="video"

**Comment by zombieJ** [comment]
Duplicate of #27144

**Comment by linxianxi** [comment]
> Duplicate of #27144

跟这个不一样，我重新弄一个详细点的需求

**Comment by qingfengmy** [comment]
或者previe里增加render函数，自己可以render图片或者视频。

**Comment by xclw2000** [comment]
我也遇到了同样的问题，有什么解决办法？
