### ISSUE TITLE
Less编译出错。版本3.24.2

### ISSUE THREAD

**Issue by zwh6611** [ant-design/ant-design#27260]
error { [LessError: error evaluating function `darken`: color.toHSL is not a function]
  message:
   'error evaluating function `darken`: color.toHSL is not a function',
  stack: undefined,
  type: 'Runtime',
  filename: 'input',
  index: 345306,
  line: 15263,
  column: 32,
  callLine: NaN,
  callExtract: undefined,
  extract:
   [ "@table-header-sort-active-bg: ~'darken(@table-header-bg, 3%)';",
     '@table-header-filter-active-bg: darken(@table-header-sort-active-bg, 5%);',
     '@table-selection-column-width: 60px;' ] }

**Comment by luocong2016** [comment]
一样
