### ISSUE TITLE
Transfer穿梭框 没有调整上下顺序的功能吗？

### ISSUE THREAD

**Issue by xiadw** [ant-design/ant-design#2726]
Transfer穿梭框 没有调整上下顺序的功能吗？
业务需求需要能调整上下顺序的功能，这点直接影响到用户体验，请问，使用目前的Transfer怎么实现调整上下顺序的功能？

**Comment by afc163** [comment]
目前未支持。

**Comment by benjycui** [comment]
https://github.com/ant-design/ant-design/issues/2538

**Comment by laonon** [comment]
请问，搜索出的数据能渲染成table格式的吗
