### ISSUE TITLE
需求：Image 可以自定义预览的内容

### ISSUE THREAD

**Issue by linxianxi** [ant-design/ant-design#27273]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当图片和视频放在一起的时候，可以预览视频或者嵌入一个 iframe

### What does the proposed API look like?
在 preview 里加一个 render， preview={{ visible, onVisibleChange, render={() => { \<video  src="" /\> } }  }}

**Comment by AttackXiaoJinJin** [comment]
我看了下，目前预览的内容仍然只能是 image：

![image](https://user-images.githubusercontent.com/26433572/197165480-e07d699b-6365-42e7-b923-c8a8ff8808da.png)

**Comment by afc163** [comment]
https://github.com/react-component/image/pull/248
https://github.com/ant-design/ant-design/pull/43075
