### ISSUE TITLE
使用Dayjs替换Moment自定义DatePicker后，组件无法国际化

### ISSUE THREAD

**Issue by shuangmianxiaoQ** [ant-design/ant-design#27276]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/wentifuxiandemo-rn4iq?file=/index.js)

### Steps to reproduce
1. 参考官方文档[替换 Moment.js](https://ant.design/docs/react/replace-moment-cn)章节的自定义组件方法，使用`Dayjs`对`DatePicker`等组件进行封装
2. 使用`ConfigProvider`组件全局国际化的过程中，自定义`DatePicker`组件无法国际化
3. 在文档的[参考实例](https://github.com/xiaohuoni/antd4-generate-picker/tree/master/antd-ts)中，`antd 4.0`版本可以正常国际化

### What is expected?
自定义`DatePicker`等组件后，可正常国际化

### What is actually happening?
自定义`DatePicker`等组件后，`antd`引入的组件可正常国际化，自定义组件国际化失效

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.14.0 |
| System | macOS 10.15.7 |
| Browser | Google Chrome 86.0.4240.80 |

---
关于替换`Moment.js`，官方文档中提到的第二种方法（使用`webpack`插件）挺实用的，但是由于 TS 类型支持问题：[antd-dayjs-webpack-plugin插件替换moment之后，TypeScript声明文件还是要求传参类型为moment.Moment](https://github.com/ant-design/antd-dayjs-webpack-plugin/issues/23)，所以采用了第一种自定义组件的方法，希望大神可以给个解决方案

**Comment by yoyo837** [comment]
> 关于替换Moment.js，官方文档中提到的第二种方法（使用webpack插件）挺实用的，但是由于 TS 类型支持问题：antd-dayjs-webpack-plugin插件替换moment之后，TypeScript声明文件还是要求传参类型为moment.Moment，所以采用了第一种自定义组件的方法，希望大神可以给个解决方案

这个好像没错的，你代码里还是用moment去写, webpack插件最终用dayjs替换实现

**Comment by shuangmianxiaoQ** [comment]
> > 关于替换Moment.js，官方文档中提到的第二种方法（使用webpack插件）挺实用的，但是由于 TS 类型支持问题：antd-dayjs-webpack-plugin插件替换moment之后，TypeScript声明文件还是要求传参类型为moment.Moment，所以采用了第一种自定义组件的方法，希望大神可以给个解决方案
> 
> 这个好像没错的，你代码里还是用moment去写, webpack插件最终用dayjs替换实现

因为moment

**Comment by shuangmianxiaoQ** [comment]
> > 关于替换Moment.js，官方文档中提到的第二种方法（使用webpack插件）挺实用的，但是由于 TS 类型支持问题：antd-dayjs-webpack-plugin插件替换moment之后，TypeScript声明文件还是要求传参类型为moment.Moment，所以采用了第一种自定义组件的方法，希望大神可以给个解决方案
> 
> 这个好像没错的，你代码里还是用moment去写, webpack插件最终用dayjs替换实现

这样子感觉还是不太优雅，本质上是想在代码中去moment，用dayjs替代的...
自定义组件方法的国际化问题，还是希望能排查一下

**Comment by yoyo837** [comment]
@iamkun

**Comment by afc163** [comment]
https://codesandbox.io/s/wentifuxiandemo-forked-l3704?file=/DatePicker.js

#24596

**Comment by glebdv** [comment]
> > Regarding the replacement of Moment.js, the second method mentioned in the official document (using the webpack plug-in) is quite practical, but due to the TS type support problem: After the antd-dayjs-webpack-plugin plug-in replaces the moment, the TypeScript declaration file is still required to be passed The parameter type is moment.Moment, so the first method of customizing the component is adopted. I hope the great god can give a solution
> 
> This seems to be correct, you still use moment to write your code, and the webpack plugin is finally implemented with dayjs.

Sorry, I think I'm a little confused over this - as I see the point is not to use momentjs in our package.json because of its maintenance mode, mutability and big size but then this plugin doesn't actually allow to use dayjs instead of moment in antd, so we have to keep moment and it just parses antd's moment bits with dayjs?

**Comment by theprimone** [comment]
> > 关于替换Moment.js，官方文档中提到的第二种方法（使用webpack插件）挺实用的，但是由于 TS 类型支持问题：antd-dayjs-webpack-plugin插件替换moment之后，TypeScript声明文件还是要求传参类型为moment.Moment，所以采用了第一种自定义组件的方法，希望大神可以给个解决方案
> 
> 这个好像没错的，你代码里还是用moment去写, webpack插件最终用dayjs替换实现

这个建议还是在官方文档说明一下，我一脸蒙蔽搜了各种文档来看应该怎么解决 😂

**Comment by Tenodec** [comment]
折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受....

**Comment by liuyib** [comment]
> 折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受....

少抱怨，多思考。下面代码即可解决你的问题：

```js
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';

dayjs.locale('zh-cn');
```

**Comment by Tenodec** [comment]
> > 折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受....
> 
> 少抱怨，多思考。下面代码即可解决你的问题：
> 
> ```js
> import dayjs from 'dayjs';
> import 'dayjs/locale/zh-cn';
> 
> dayjs.locale('zh-cn');
> ```

兄弟，你觉得这么简单配置会想不到吗。肯定是用过了还有问题啊，后面重启项目才没问题，不知道为啥umi没有动态更新

**Comment by liuyib** [comment]
照你这语气这么牛逼，咋没立马想到重启项目呢？还非得到最后才发现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 晚上9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ant-design/ant-design] 使用Dayjs替换Moment自定义DatePicker后，组件无法国际化 (#27276)





   
折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受....
  
少抱怨，多思考。下面代码即可解决你的问题：
 import dayjs from 'dayjs'; import 'dayjs/locale/zh-cn'; dayjs.locale('zh-cn');
  
兄弟，你觉得这么简单配置会想不到吗。肯定是用过了还有问题啊，后面重启项目才没问题，不知道为啥umi没有动态更新
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Tenodec** [comment]
> 

对，你是大神，你是牛逼，你是天下无敌。请大神高抬贵手，就此终结

**Comment by Tenodec** [comment]
> 照你这语气这么牛逼，咋没立马想到重启项目呢？还非得到最后才发现
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ant-design/ant-design" ***@***.***&gt;; 发送时间:&nbsp;2021年11月19日(星期五) 晚上9:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ant-design/ant-design] 使用Dayjs替换Moment自定义DatePicker后，组件无法国际化 (#27276) 折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受.... 少抱怨，多思考。下面代码即可解决你的问题： import dayjs from 'dayjs'; import 'dayjs/locale/zh-cn'; dayjs.locale('zh-cn'); 兄弟，你觉得这么简单配置会想不到吗。肯定是用过了还有问题啊，后面重启项目才没问题，不知道为啥umi没有动态更新 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

对，你是大神，你是牛逼，你是天下无敌。请大神高抬贵手，就此终结

**Comment by Tenodec** [comment]
> 照你这语气这么牛逼，咋没立马想到重启项目呢？还非得到最后才发现
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ant-design/ant-design" ***@***.***&gt;; 发送时间:&nbsp;2021年11月19日(星期五) 晚上9:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ant-design/ant-design] 使用Dayjs替换Moment自定义DatePicker后，组件无法国际化 (#27276) 折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受.... 少抱怨，多思考。下面代码即可解决你的问题： import dayjs from 'dayjs'; import 'dayjs/locale/zh-cn'; dayjs.locale('zh-cn'); 兄弟，你觉得这么简单配置会想不到吗。肯定是用过了还有问题啊，后面重启项目才没问题，不知道为啥umi没有动态更新 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

tm自己一上来就阴阳怪气

**Comment by Tenodec** [comment]
> 照你这语气这么牛逼，咋没立马想到重启项目呢？还非得到最后才发现
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ant-design/ant-design" ***@***.***&gt;; 发送时间:&nbsp;2021年11月19日(星期五) 晚上9:15 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [ant-design/ant-design] 使用Dayjs替换Moment自定义DatePicker后，组件无法国际化 (#27276) 折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受.... 少抱怨，多思考。下面代码即可解决你的问题： import dayjs from 'dayjs'; import 'dayjs/locale/zh-cn'; dayjs.locale('zh-cn'); 兄弟，你觉得这么简单配置会想不到吗。肯定是用过了还有问题啊，后面重启项目才没问题，不知道为啥umi没有动态更新 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

自己一上来就怪怪的，显得自己很那啥，所以理解别人的话都是带刺。

**Comment by liuyib** [comment]
> > 照你这语气这么牛逼，咋没立马想到重启项目呢？还非得到最后才发现
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "ant-design/ant-design" _**@**_._**>; 发送时间: 2021年11月19日(星期五) 晚上9:15 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [ant-design/ant-design] 使用Dayjs替换Moment自定义DatePicker后，组件无法国际化 (#27276) 折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受.... 少抱怨，多思考。下面代码即可解决你的问题： import dayjs from 'dayjs'; import 'dayjs/locale/zh-cn'; dayjs.locale('zh-cn'); 兄弟，你觉得这么简单配置会想不到吗。肯定是用过了还有问题啊，后面重启项目才没问题，不知道为啥umi没有动态更新 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 自己一上来就怪怪的，显得自己很那啥，所以理解别人的话都是带刺。

![image](https://user-images.githubusercontent.com/38221479/155917334-25191138-f510-423c-aaea-0a25e57f169d.png)

很多东西都不是完美的，哪有那么多开箱即用，都要喂给你饭吃吗？自己天天抱怨这抱怨那，你这种抱怨的态度没人想理你，如果你不是抱怨这抱怨那，别人会挑你刺？就挑你刺咋啦

**Comment by lizepeng** [comment]
参考 #27815, #29907 我感觉主要还是文档中的[示例代码](https://ant-design.antgroup.com/docs/react/replace-moment-cn#DatePicker.tsx)的问题：

```diff
import { Dayjs } from 'dayjs';
-import dayjsGenerateConfig from 'rc-picker/es/generate/dayjs';
+import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
import generatePicker from 'antd/es/date-picker/generatePicker';
import 'antd/es/date-picker/style/index';

const DatePicker = generatePicker<Dayjs>(dayjsGenerateConfig);

export default DatePicker;
```

**Comment by dingyanhe** [comment]
遇到了类似的问题，一行一行代码的调试替换后的DatePicker的代码。发现我引入ConfigProvider的方式如下：

```tsx
// app.tsx
import {  ConfigProvider } from "antd"; // *1
import zhCN from "antd/lib/locale/zh_CN";

...
<ConfigProvider locale={zhCN}> // **1
  <DayjsDatePicker /> // **2
</ConfigProvider>
...
```

```tsx
// 自定义DatePicker
import React from 'react';
import generatePicker from 'antd/lib/date-picker/generatePicker'; // *2
import dayjsGenerateConfig from 'rc-picker/lib/generate/dayjs';
const _DatePicker = generatePicker(dayjsGenerateConfig);

export default function DayjsDatePicker(props) {
  return <_DatePicker {...props} />
}
```

标记`*1`:  经过尝试发现，此处的ConfigProvider会被`webpack`识别成来自 `antd/es/xxxx`。

标记`*2`:  此出会被包裹LocaleReceiver，因为generatePicker来自` 'antd/lib/xxx`模块，LocaleReceiver引入也是相对目录导入的所以 context也会来自“lib”目录下。

总结：`**1` ConfigProvider来自es的context，`**2` DayjsDatePicker 绑定的上下文是 lib的context。相当于是ConfigProvider用es的ConfigContext注入，generatePicker用lib的ConfigContext读取上下文。例如：

```tsx
<EsConfigProvider locale={zhCN}>
...
   // DayjsDatePicker.js内部如下
  <LibConfigProvider locale={en_US_deafult}>
      <DatePicker /> // 引用自 lib的context，读取到的肯定是默认的 en_US_deafult 而不是 zhCN
  </LibConfigProvider>
...
</ESConfigProvider>
```

上面的描述只是大概解释，需要整个demo到generatePicker的node_modules目录下一点点调试。

解决办法：
方法1:
generatePicker保持从lib目录引入，使用[babel-plugin-import](https://www.npmjs.com/package/babel-plugin-import)，将标记`*1`默认的导入转换成 `from "antd/lib/xxxx"`

方法2：
generatePicker，改为从es目录引入即可。

**Comment by quyctd** [comment]
Thanks, @dingyanhe, for a detailed explanation. 

For some who still encounter this problem when using `Next.js`, you can try to fix it by updating the import statement like this. Hope this help

```diff
- import { ConfigProvider } from 'antd'
+ import ConfigProvider from 'antd/lib/config-provider'
```

**Comment by HUE-zec** [comment]
> > > 折腾了半天，抄官方的代码，结果日期选择只有年是中文，其他都是英文，还不知道哪里去替换时区，这官方是让我们自己去研究吗，难受....
> > 
> > 
> > 少抱怨，多思考。下面代码即可解决你的问题：
> > ```js
> > import dayjs from 'dayjs';
> > import 'dayjs/locale/zh-cn';
> > 
> > dayjs.locale('zh-cn');
> > ```
> 
> 我也试用的这种方法，还是不生效？是要重启项目吗

大佬解决了吗？我今天也遇到了，antd4使用dayjs替换后，并且使用了dayjs.locale('zh-cn')，依旧只有年是显示中文的。

**Comment by yoyo837** [comment]
`import 'dayjs/locale/zh-cn'; ` 别漏了

**Comment by HUE-zec** [comment]
> `import 'dayjs/locale/zh-cn'; ` 别漏了

pnpm install -force完美解决了

**Comment by dev-meta** [comment]
我遇到了同样的问题，而且使用上面的方法都无法解决。最后找到是版本的问题。


`
import dayjs from 'dayjs';
import 'dayjs/locale/zh-cn';

dayjs.locale('zh-cn');
`
上面的代码必不可少。
然后终端执行

`
npm ls dayjs
`
看看有几个dayjs版本，我们把本地安装的dayjs版本改成和 antd依赖的 dayjs版本一致就可以了。
