### ISSUE TITLE
TreeSelect 在宽度较小或者层级较多,并且开启虚拟滚动下 无法响应触摸板横向滚动

### ISSUE THREAD

**Issue by zhiaiing** [ant-design/ant-design#27278]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/polished-sun-cki3i?file=/index.js)

### Steps to reproduce
TreeSelect 开启虚拟滚动时 修改样式出现横向滚动条
无法响应触摸板横向滚动。

### What is expected?
可以响应触摸板横向滚动。

### What is actually happening?
无法响应触摸板横向滚动。

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.12.0 |
| System | mac |
| Browser | chrome |

**Comment by zhiaiing** [comment]
![image](https://user-images.githubusercontent.com/15857315/96687190-21605580-13b2-11eb-94b5-0e020394b101.png)
这里event.preventDefault() 阻止了默认事件 是为了防止页面的滚动， 但这是也没法响应触摸板的滑动事件了。
可不可以这里不阻止， 在dropdown根节点时再阻止。

**Comment by zhiaiing** [comment]
<img width="732" alt="WX20201021-153452@2x" src="https://user-images.githubusercontent.com/15857315/96687817-fc201700-13b2-11eb-8ad6-d222bfde3d6a.png">
这里event.preventDefault() 阻止了默认事件 是为了防止页面的滚动， 但这是也没法响应触摸板的滑动事件了。
可不可以这里不阻止， 在dropdown根节点时再阻止。

**Comment by orangelyq** [comment]
刚刚试了下，将virtual设置为false就可以出现横向滚动条了。
