### ISSUE TITLE
TreeSelect组件，若treeData传入参数value为空字符串，onChange返回的value为label值

### ISSUE THREAD

**Issue by Catlite91** [ant-design/ant-design#2727]
#### 本地环境
- antd 版本: 1.9.0
- 操作系统及其版本：osx 10.11.6 (15G31)
- 浏览器及其版本: chrome 52.0.2743.116 (64-bit)

#### 你做了什么？
TreeSelect组件，treeData中传入某项参数value为空字符串

#### 你期待的结果是：

onChange中的value为空字符串""

#### 实际上的结果：
onChange中的value为label值

传入的值：
![image](https://cloud.githubusercontent.com/assets/9129944/17687377/0c73c798-63a7-11e6-9c6f-6bc5f9a52b2e.png)

onChange返回的值：
![image](https://cloud.githubusercontent.com/assets/9129944/17687395/3378930a-63a7-11e6-9fe7-d79730270831.png)

**Comment by Catlite91** [comment]
TreeSelect的问题：
1、若treeData传入参数value为空字符串，onChange返回的value为label值
2、再次选中相同节点，返回undefined

demo：http://codepen.io/Catlite/pen/AXwwdB?editors=1111

**Comment by warmhug** [comment]
value 为什么要为空？

**Comment by Catlite91** [comment]
作为筛选条件的时候，就可能会用到空值
应该和select等组建保持一致吧

**Comment by warmhug** [comment]
key 不要设为空字符串

**Comment by Catlite91** [comment]
这里逻辑是value = value || key || label么？
是不是value永远只是value的值，不然会造成困惑

**Comment by warmhug** [comment]
fixed https://github.com/react-component/tree-select/commit/ae6552329dccd27c60924d215f019a94284c1d55

> 再次选中相同节点，返回undefined

这个是对的。再次点击就是不选，什么都没选，就是 undefined
