### ISSUE TITLE
not support internet explorer 11 ..

### ISSUE THREAD

**Issue by SeongHyuenYun** [ant-design/ant-design#27279]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
clone ant-design -> npm install -> yarn site -> serve _site 

### What is expected?
support IE

### What is actually happening?
after excuting serve _site , occurs error about polyfill in IE11

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.14.0 |
| System | mac  |
| Browser | ie 11 |

**Comment by Kermit-Xuan** [comment]
@SeongHyuenYun 

Why do you use ie11 on mac? Can you provide screenshots of error?

Why do you need site of ant-design to support IE 11? we only promise `antd` to support IE11.

**Comment by SeongHyuenYun** [comment]
sorry.. windows 10..

**Comment by Kermit-Xuan** [comment]
> sorry.. windows 10..

If you are interested in contributing to ant-design, you should use the latest Chorme/Edge browser to develop.
