### ISSUE TITLE
Missing docs for array rule

### ISSUE THREAD

**Issue by piyushk96** [ant-design/ant-design#27287]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form/#Rule](https://ant.design/components/form/#Rule)

### Steps to reproduce
- Missing docs for `defaultField` prop for array type rule as defined here https://github.com/react-component/field-form/blob/master/src/interface.ts#L78 
 

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | N/A |
| System | N/A |
| Browser | N/A |

---
It will be great if you could provide an example for using this prop

**Comment by afc163** [comment]
Fixed in https://github.com/ant-design/ant-design/pull/28437
