### ISSUE TITLE
select 虚拟滚动条报错

### ISSUE THREAD

**Issue by LeoHuiyi** [ant-design/ant-design#27282]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/daisousuokuang-ant-design-demo-forked-kcipp?file=/index.js)

### Steps to reproduce
Option为8个的时候 点击打开 
![image](https://user-images.githubusercontent.com/8001457/96693812-45279980-13ba-11eb-815a-41806b224d10.png)

### What is expected?
不报错

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.14.0 |
| System | windows |
| Browser | chrome86 |

**Comment by LeoooY** [comment]
遇到同样的问题
| Environment  |  Info  |
| -- | -- |
|  antd  |  4.7.2  |
|  react  |  16.13.1  |
|  System  |  ubuntu 20.04   |
|  Browser  |   chrome 85.0.4183.102 |

**Comment by fengsx** [comment]
+1。如果此时拖动虚拟滚动的滚动条还会报错。

![image](https://user-images.githubusercontent.com/7709602/96973088-00cb0380-154a-11eb-8a0d-a6481b0c4f10.png)

**Comment by yannliao** [comment]
我也遇到同样问题 

> +1。如果此时拖动虚拟滚动的滚动条还会报错。
> 
> ![image](https://user-images.githubusercontent.com/7709602/96973088-00cb0380-154a-11eb-8a0d-a6481b0c4f10.png)

**Comment by yoyo837** [comment]
react-component/virtual-list#72 未处理 `Maximum update depth exceeded`.

**Comment by WangJM001** [comment]
+1

**Comment by yoyo837** [comment]
Maximum update depth exceeded. 还需要改

**Comment by zombieJ** [comment]
8 条正好卡到 height == scrollHeight，fix 展示滚动条的问题就不会有 Maximum 了。
ref: https://github.com/react-component/virtual-list/commit/578c6994d5cba5173b55ee6ffe7d461946608c4f

**Comment by wenjayliu** [comment]
+1 同样问题
![image](https://user-images.githubusercontent.com/23413570/97657074-eb9f2900-1aa3-11eb-89e4-6446ae8ba94c.png)

**Comment by zombieJ** [comment]
@wenjayliu，codesandbox 会 cache。你本地安装最新的试试

**Comment by khanakia** [comment]
I am having the same issue.

**Comment by yoyo837** [comment]
Pls remove node_modules, package-lock.json or yarn.lock then reinstall.

**Comment by khanakia** [comment]
@yoyo837 Thanks 👍 It worked now :)

**Comment by florianMo** [comment]
Same happened for me with antd@4.7.2, upgrading to 4.7.3 fixed the issue. I also had to upgrade from dayjs@1.9.3 to 1.9.4 to fix typescript errors in Calendars (I use dayjs instead of moment for time related components). Be careful when removing node_modules, lock file and reinstalling (as @yoyo837 sugggests), this will upgrade all your packages.

**Comment by wencyL** [comment]
4.8.0修复了？

**Comment by yoyo837** [comment]
不用4.8.0, 之前的版本重新安装应该就好了

**Comment by wencyL** [comment]
hello，Anchor这个组件有副作用啊，URL变化的时候改变了props，导致页面重新渲染了。啥时候解决下这个副作用呀



---原始邮件---
发件人: "Amumu"<notifications@github.com&gt;
发送时间: 2020年11月3日(周二) 下午2:49
收件人: "ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"wencyL"<935446689@qq.com&gt;;
主题: Re: [ant-design/ant-design] select 虚拟滚动条报错 (#27282)




 
不用4.8.0, 之前的版本重新安装应该就好了

**Comment by crystalcatdika** [comment]
I am having the same issue when use 4.8.0 or 4.10.2

**Comment by zombieJ** [comment]
@crystalcatdika pls help to fire new issue instead.

**Comment by rahulthewall** [comment]
I have the same issue. 

On my home page, I have the following code. 

```
const SelectComponent = () => (
  <Select>
    <Option value="jack">Jack</Option>
    <Option value="jill">Jill</Option>
    <Option value="rahul">Rahul</Option>
    <Option value="dave">Dave</Option>
    <Option value="tony">Tony</Option>
    <Option value="josh">Josh</Option>
    <Option value="juan">Juan</Option>
    <Option value="nadja">Nadja</Option>
    <Option value="lisa">Lisa</Option>
    <Option value="siarhei">Siarhei</Option>
    <Option value="viktar">Viktar</Option>
    <Option value="eyal">Eyal</Option>
  </Select>
);
```

And then the route

```
<Route exact path="/select" component={SelectComponent} />
```

When I try to go the Select page, the component renders. But as soon as I scroll, I get the following error:

```
Warning: `NaN` is an invalid value for the `top` css style property.
div
div
ScrollBar@http://localhost:4006/static/js/vendors~main.chunk.js:193608:20
div
RawList@http://localhost:4006/static/js/vendors~main.chunk.js:193140:26
OptionList@http://localhost:4006/static/js/vendors~main.chunk.js:172109:19
div
div
Align@http://localhost:4006/static/js/vendors~main.chunk.js:149859:18
DomWrapper@http://localhost:4006/static/js/vendors~main.chunk.js:162171:94
genCSSMotion/CSSMotion<@http://localhost:4006/static/js/vendors~main.chunk.js:161886:26
./node_modules/rc-trigger/es/Popup/PopupInner.js/PopupInner<@http://localhost:4006/static/js/vendors~main.chunk.js:188407:17
div
./node_modules/rc-trigger/es/Popup/index.js/Popup<@http://localhost:4006/static/js/vendors~main.chunk.js:188611:17
./node_modules/rc-util/es/Portal.js/Portal<@http://localhost:4006/static/js/vendors~main.chunk.js:191748:19
Trigger@http://localhost:4006/static/js/vendors~main.chunk.js:188917:96
SelectTrigger@http://localhost:4006/static/js/vendors~main.chunk.js:172617:19
div
Select@http://localhost:4006/static/js/vendors~main.chunk.js:173472:28
Select@http://localhost:4006/static/js/vendors~main.chunk.js:172517:94
InternalSelect@http://localhost:4006/static/js/vendors~main.chunk.js:103253:28
SelectComponent
Route@http://localhost:4006/static/js/vendors~main.chunk.js:224986:29
Switch@http://localhost:4006/static/js/vendors~main.chunk.js:225188:29
div
Suspense
div
Router@http://localhost:4006/static/js/vendors~main.chunk.js:224621:30
BrowserRouter@http://localhost:4006/static/js/vendors~main.chunk.js:224241:35
SilentRefresh@http://localhost:4006/static/js/main.chunk.js:1070:23
ApolloProvider@http://localhost:4006/static/js/vendors~main.chunk.js:67032:16
ApolloConfigProvider@http://localhost:4006/static/js/main.chunk.js:2342:30
AppConfigProvider@http://localhost:4006/static/js/main.chunk.js:2498:27
App
```

Which is then followed by the following error

```
Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

I have antd-4.15.2, but I can't reproduce the error if I try the same thing in code sandbox. See: https://codesandbox.io/s/cool-fog-5qw2d

How do I debug this? Any help @afc163

**Comment by rahulthewall** [comment]
Ignore the above comment, it only happens on FF 89.0b3. Looks like an FF issue.

**Comment by zzzloving** [comment]
@yoyo837 @zombieJ  当我使用Form.Item 包裹 Select 组件时，上面的情况又复现了，antd版本已更行到最新，验证了不用Form标签包裹Select 时是好的，麻烦帮忙看一下～
```html
                 <Form.Item label="结束版本" name="endVersion">
                    <Select placeholder="请选择">
                      {columnEnums?.endVersion &&
                        columnEnums.endVersion.map(d => (
                          <Select.Option key={d} value={d}>
                            {d}
                          </Select.Option>
                        ))}
                    </Select>
                  </Form.Item>
```
[https://huslx-1300742824.cos.ap-shanghai.myqcloud.com/%E4%BC%81%E4%B8%9A%E5%BE%AE%E4%BF%A1%E6%88%AA%E5%9B%BE_9b181c71-7c83-4011-a5c9-7f9bb4a23c4f.png](url)

**Comment by zombieJ** [comment]
@zzzloving 新建一个 issue 带上重现哈~

**Comment by TaurusWood** [comment]
你好，我要怎样才能便捷的知道，你们是在哪个版本解决这个问题的呢？

**Comment by yoyo837** [comment]
查看相应的commit包含在哪个tag

**Comment by TaurusWood** [comment]
@yoyo837  这个问题解决是在rc-virtual-list的3.2.1的
但是该issues中并没有写是什么时候将rc-virtual-list更新到3.2.1的啊

**Comment by yoyo837** [comment]
> @yoyo837 这个问题解决是在rc-virtual-list的3.2.1的
> 但是该issues中并没有写是什么时候将rc-virtual-list更新到3.2.1的啊

不是很明白你是什么意思。antd依赖rc-select和rc-tree依赖rc-virtual-list，都是使用的`^`符号，如果你使用antd应该早就用的最新版本了。

**Comment by TaurusWood** [comment]
@yoyo837 我们有一个自己的组件库，目前antd的版本是4.9.3，目前还存在这个问题，yarn.lock里：
```
rc-select@^12.0.0, rc-select@~12.1.6:
  version "12.1.10"
  resolved "http://npm.xxx.com:4873/rc-select/-/rc-select-12.1.10.tgz#66ce43192751190b7c0e9a0ab1ef79606421ce30"
  integrity sha1-Zs5DGSdRGQt8DpoKse95YGQhzjA=
  dependencies:
    "@babel/runtime" "^7.10.1"
    classnames "2.x"
    rc-motion "^2.0.1"
    rc-overflow "^1.0.0"
    rc-trigger "^5.0.4"
    rc-util "^5.9.8"
    rc-virtual-list "^3.2.0"
    
rc-virtual-list@^3.2.0:
  version "3.2.0"
  resolved "http://npm.xxx.com:4873/rc-virtual-list/-/rc-virtual-list-3.2.0.tgz#21e70f42b22f510d38ceb1ba339b89b865686fcd"
  integrity sha1-IecPQrIvUQ04zrG6M5uJuGVob80=
  dependencies:
    classnames "^2.2.6"
    rc-resize-observer "^0.2.3"
    rc-util "^5.0.7"
```
就版本锁在3.2.0升不上去。

https://github.com/react-component/virtual-list/pull/72 这个issuse显示在3.2.1解决的。

因为是基础组件库，直接将antd升级到最新版本，担心影响范围太大。所以想知道antd具体哪一个版本升级到3.2.1

**Comment by yoyo837** [comment]
我看看

**Comment by yoyo837** [comment]
yarn upgrade一下应该就好了

**Comment by yoyo837** [comment]
或者删除lock文件，重新安装

**Comment by TaurusWood** [comment]
@yoyo837 
首先基础组件库的yarn.lock不能动的，可能会导致其他项目出现版本问题。

> yarn upgrade一下应该就好了，并不依赖4.9.3必须升级到后面哪个版本antd。

我不明白你这句话的意思，是指`yarn upgrade antd`么？这样会导致antd升级到最新版啊，我目前只需要尽量小的版本改动，以确定影响范围。而且我用的lerna，也不能直接支持yarn的这个命令

**Comment by yoyo837** [comment]
你的情况来说，
1. 单独升级`rc-virtual-list`到最新版本就可以了。
2. 如果不能使用yarn，你的lock文件从何而来并且对版本做锁定的呢？如果不锁定，全新安装`rc-virtual-list`是会直接到最新版本的.
3. 无法通过主动升级`antd`来达到升级`rc-virtual-list`的效果，因为在package.json一直使用的`^`依赖的它符号。

综合以上，你这就是个简单的版本锁定而已。

**Comment by TaurusWood** [comment]
@yoyo837  谢谢，忙完了回复你了
