### ISSUE TITLE
Use CSS custom variables instead of Less variables

### ISSUE THREAD

**Issue by alfredsgenkins** [ant-design/ant-design#27286]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Migration to CSS custom variables would allow to modify theme without changing the build configuration. Current approach with CRA is in my personal opinion very poor - recommendation to eject is not a good solution for a problem.

Additionally, users will get access to most new features of CSS custom variables - context awareness, default values, etc.

The migration might be very simple, one large replace over the project and default Less variables passed into it.

### What does the proposed API look like?
Instead of:

```
@primary-color: #1890ff; // primary color for all components
--antd-primary-color: #1890ff;
```

Or similar. I am not the expert in Less, rather SCSS.

**Comment by afc163** [comment]
trace #23371
