### ISSUE TITLE
Why antd Table text switch to single line from multi-line when the page width shrink to very short?

### ISSUE THREAD

**Issue by lidixiyang** [ant-design/ant-design#27284]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/lidixiyang/antd-pro-table-issue](https://github.com/lidixiyang/antd-pro-table-issue)

**Main code:**
`const columns = [
  {
    title: 'Name',
    dataIndex: 'name',
    key: 'name',
    render: text => <div>{text}</div>,
  },
];
`

`const data = [
  {
    key: '1',
    name: 'John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown John Brown ',
  },
  {
    key: '2',
    name: 'Jim Green',
  },
  {
    key: '3',
    name: 'Joe Black',
  },
];
`

`    <Table columns={columns} dataSource={data} bordered={true} showHeader={false} pagination={false} style={{ wordWrap: 'break-word', wordBreak: 'break-word' }}/>
`
### Steps to reproduce
1. Open the web page on brower with max width. 2. Shrink the brower to shortest width anyway.

### What is expected?
The multiline text remain multiline and scroll bar donot display.

### What is actually happening?
The multiline text switches to single line and a scroll bar display.

**This result does not appear with "umi" Scaffold.**

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.8.6 |
| System | Window Server 2019 |
| Browser | Firefox 81.0.2 |

**Comment by afc163** [comment]
You should use `scroll={{ x: true }}` or `scroll={{ x: 'max-content' }}` in this situation.

**Comment by lidixiyang** [comment]
> 
> 
> You should use `scroll={{ x: true }}` or `scroll={{ x: 'max-content' }}` in this situation.

Thanks but I want to close the scroll bar, not to open the scroll bar. Your method is just to open it and make the text displaying in single line. I want to display it in multi line everytime. In  fact I want it to displaly in multiline when using mobile brower which has small window width.

**Comment by afc163** [comment]
Could you provide a codesandbox?

**Comment by lidixiyang** [comment]
> Thanks. Because the issue is about brower window size, I cannot provide a codesandbox, maybe I donot know how to provide it. But I have give the Table component up, insteadly, I write a simple table myself and it works.
