### ISSUE TITLE
table的select和check的状态可以设置相对独立

### ISSUE THREAD

**Issue by goodve** [ant-design/ant-design#27280]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
日常的需求是单击选一行进行编辑，check多个进行批量删除

### What does the proposed API look like?
```javascript
{
singleSelect:bool,  //设置ture  只能单选
selectOnCheck:bool,
checkOnSelect:bool
}
```
![image](https://user-images.githubusercontent.com/17634299/96660485-4043f500-137c-11eb-877f-d883a3ac9cbb.png)

**Comment by afc163** [comment]
这是偏 data-grid 类型的表格了，暂不支持这样的交互。
