### ISSUE TITLE
Input.Search hover border right lost when allowclear

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#27296]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sousuokuang-ant-design-demo-forked-w8id2)

### Steps to reproduce
- Hover the first

### What is expected?
border normal

### What is actually happening?
border unnormal

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | The latest |
| System | mac |
| Browser | chrome |

**Comment by kanweiwei** [comment]
横向排列，本来就没有右边框，不算bug吧

**Comment by xrkffgg** [comment]
When remove `allowclear`, you will see the first item border normal. When add `allowclear`, border unnormal.

**Comment by xrkffgg** [comment]
Emm, I still want to learn how others fix it. After waiting for so long, I should do it myself.
