### ISSUE TITLE
Table组件 服务器端渲染 ReferenceError: document is not defined

### ISSUE THREAD

**Issue by daCapricorn** [ant-design/ant-design#2729]
#### 本地环境

- antd 版本: 1.9.0
- 操作系统及其版本：OS X 10.10.4
- 浏览器及其版本: Chrome 50.0.2661.102 (64-bit)

#### 你做了什么？

Table组件 服务器端渲染 若设置scroll={{ y: 500 }} 会出现ReferenceError: document is not defined

#### 你期待的结果是：

无错误

#### 实际上的结果：

出现错误

**Comment by afc163** [comment]
reinstall antd
