### ISSUE TITLE
not support IE11 ....

### ISSUE THREAD

**Issue by SeongHyuenYun** [ant-design/ant-design#27299]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design.git](https://github.com/ant-design/ant-design.git)

### Steps to reproduce
npm install -> yarn site -> serve _site -> open IE

### What is expected?
nothing

### What is actually happening?
error occurs about polyfill

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 16.14.0 |
| System | Windows10 |
| Browser | IE11 |

**Comment by afc163** [comment]
Duplicate of #27279
