### ISSUE TITLE
Table异步请求数据使用的是reqwest，而我使用jQuery的mockjax来在前端拦截请求，但拦截不到reqwest，这种情况下怎么mock数据？

### ISSUE THREAD

**Issue by zccst** [ant-design/ant-design#273]
本打算项目中异步获取数据还是基于jQuery的ajax，所以mock数据使用了mockjax，本来可以用得好好的。
但开始使用Table时，发现Table中的url使用是reqwest实现的。

var dataSource = new Table.DataSource({
  url: "/components/table/demo/data.json",
  ...
});

问题是mockjax拦截不到reqwest的ajax请求，前端没法模拟数据，影响开发进度，怎么办？

**Comment by afc163** [comment]
可以自行写 io 逻辑，使用 dataSource 来控制数据展示。

**Comment by zccst** [comment]
@afc163 你好，能具体指导一下吗？
var dataSource = new Table.DataSource({
    url: "/components/table/demo/data.json",
    ...
});
DataSource是这样的，如何下手？
