### ISSUE TITLE
虚拟列表和可嵌套子表格能否同时使用

### ISSUE THREAD

**Issue by azx1985** [ant-design/ant-design#27302]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
在table组件里虚拟列表和可嵌套子表格能一起使用

### What does the proposed API look like?
在table组件里虚拟列表和可嵌套子表格能一起使用

**Comment by afc163** [comment]
Not yet: #20339
