### ISSUE TITLE
Table `onRow` have a type-check error when use react-dnd and typescript

### ISSUE THREAD

**Issue by zD98** [ant-design/ant-design#27306]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-typescript-forked-xfjz3?file=/src/index.tsx)

### Steps to reproduce
`onRow` has a typescript check error 

### What is expected?
`onRow` has a correct type check

### What is actually happening?
Here is typescript check  error message.

Type '(record: IFruitMeta, index: number | undefined) => { index: number | undefined; moveRow: (dragIndex: number, hoverIndex: number) => void; startDragRow: (id: ReactText) => void; }' is not assignable to type 'GetComponentProps<IFruitMeta>'.
  Type '{ index: number | undefined; moveRow: (dragIndex: number, hoverIndex: number) => void; startDragRow: (id: ReactText) => void; }' has no properties in common with type 'HTMLAttributes<HTMLElement>'.

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 17.0.0 |
| System | MacOS |
| Browser | Chrome |

**Comment by zD98** [comment]
I met this issue also. 
https://github.com/ant-design/ant-design/issues/26605 was closed because have no examples.
But I provide a codesandbox link to reproduce it.

**Comment by afc163** [comment]
Try https://codesandbox.io/s/react-typescript-forked-ogj8r?file=/src/index.tsx
