### ISSUE TITLE
shouldupdate为true时，校验不会触发。

### ISSUE THREAD

**Issue by tangtangtangtangtang** [ant-design/ant-design#27308]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-nv8f0?file=/index.js)

### Steps to reproduce
如codesandbox所呈现；

### What is expected?
shouldupdate返回true在重新渲染内部组件的时候也可以重新对rules的规则进行校验

### What is actually happening?
shouldupdate返回true后，rules并没有重新执行

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | latest |
| System | macos |
| Browser | 83.0.4103.116 |

---
我记得原来文档里说shouldUpdate和dependencies不能同时使用不然会引起更新的混乱，现在是改掉了吗？
我在codesandbox加上dependencies字段是可以实现这个功能的。

**Comment by tangtangtangtangtang** [comment]
场景补充：
1. a依赖b；
2. b更新后，重新渲染a组件；
3. b更新后，重新对a进行校验（rules）； // 单独使用shouldupdate这一条无法实现，加上dependencies能实现，但我记得以前文档说这俩不能同时使用

**Comment by tangtangtangtangtang** [comment]
复现：https://codesandbox.io/s/antd-reproduction-template-forked-nv8f0?file=/index.js

**Comment by tangtangtangtangtang** [comment]
waiting...

**Comment by tangtangtangtangtang** [comment]
still wating...

**Comment by zombieJ** [comment]
`shouldUpdate` 为 renderProps 属性，普通字段绑定不需要用它。关联校验应该用 `dependencies`:
https://ant.design/components/form-cn/#dependencies

**Comment by baiziyu-fe** [comment]
@tangtangtangtangtang 
---
I think this is that you want !!!
https://codesandbox.io/s/zhucexinyonghu-antd4167-forked-pot71
