### ISSUE TITLE
希望select支持用tag展示已选项配置

### ISSUE THREAD

**Issue by maxuangithub** [ant-design/ant-design#27301]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当选择的数据过多时会把select控件的高度撑开，布局上不好看，如果支持配置显示选中个数，超过的用tag数字 1显示，可以解决这个问题

### What does the proposed API look like?
collapse-tags: number
collapse-tags: 1；表示只展示1个选中的数据，其余的用tag数字 1显示

**Comment by afc163** [comment]
Try `maxTagCount`.

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/507615/96823790-ddc42500-145f-11eb-8519-99b524373072.png">
