### ISSUE TITLE
select组件有时候点击会没有反应

### ISSUE THREAD

**Issue by xqGosky** [ant-design/ant-design#27310]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/select-cn/](https://ant.design/components/select-cn/)

### Steps to reproduce
进入页面后第一次点击select组件,选项不会展开 再点击空白处会立马出现然后又消失

### What is expected?
点击的时候可以立马出现选项

### What is actually happening?
进入页面后第一次点击select组件,选项不会展开 再点击空白处会立马出现然后又消失

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.8.6 |
| System | window |
| Browser | chrom79.XX |

**Comment by yunuo-tech** [comment]
> 官网链接是正常的，请提供下复现

这个问题我也碰到了，官网上也不正常，复现这个bug，只需要把showSearch设为未true 就能复现。

**Comment by yoyo837** [comment]
官网哪个位置的demo，明示一下

ref: #27140

**Comment by phoema** [comment]
#27031

**Comment by theDoinb** [comment]
总感觉是升级出现了什么问题....
之前为了降级，整个 nodemodules 删了重装，发现降级后还存在一些奇怪的问题，
后面把之前的 yarn.lock 沾回去重装才正常
关键不知道怎么外网重现比较头痛

**Comment by theDoinb** [comment]
发现个问题，codesandbox 上先把antd维持在4.6.2，F5刷新页面，然后升到4.7.3回报错 ，有关联吗
@afc163

**Comment by theDoinb** [comment]
官网点个 codesandbox 的Popover 应该能触发....
Could not find module in path: 'rc-motion/lib/interface' relative to '/node_modules/rc-motion/lib/CSSMotion.js'

**Comment by 0xAC7** [comment]
应该是 antd 依赖的 rc-select 导致的问题，主要原因应该是浏览器版本不兼容。
antd（4.1.3） rc-select（~10.2.0） 时，Select 无此问题；
antd（4.7.0） rc-select（~11.4.0） 时，Chrome 浏览器低于 80 版本应该会有此问题。
在 Chrome（80.0.3987.149）上偶现；
在 Chrome（83.0.4103.97）上尝试数次没有出现该问题。

**Comment by xqGosky** [comment]
> 应该是 antd 依赖的 rc-select 导致的问题，主要原因应该是浏览器版本不兼容。
> antd（4.1.3） rc-select（~10.2.0） 时，Select 无此问题；
> antd（4.7.0） rc-select（~11.4.0） 时，Chrome 浏览器低于 80 版本应该会有此问题。
> 在 Chrome（80.0.3987.149）上偶现；
> 在 Chrome（83.0.4103.97）上尝试数次没有出现该问题。

对的 可能是浏览器版本问题  帮同事浏览器升级到83就没问题了

**Comment by theDoinb** [comment]
浏览器之前是7x的，但是点官网的Selelct没问题，可能是升级过程重出现了一些不兼容的？
现在浏览器升级了，不过暂时没空去测了

**Comment by phoema** [comment]
Chrome7x有问题，复现可以使用QQ浏览器，内核为Chrome70
