### ISSUE TITLE
当 initialValue 作为 FormItem 的属性配置后，自定义表单中第一次渲染获取不到value值

### ISSUE THREAD

**Issue by NorthwesternDirector** [ant-design/ant-design#27311]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zidingyibiaodankongjian-ant-design-demo-forked-67bh3?file=/index.js:1595-1714)

### Steps to reproduce
查看 codesandbox 的 console 内容，当 initialValue 放置在 FormItem 内，第一次 console 内容为空 ，当 initialValue 放置在 Form 内，第一次 console 内容为 initialValue 值。在不同的位置设置  initialValue ，获取到 value 的时机却不同

### What is expected?
当 initialValue 作为 FormItem 的属性配置后，第一次 console 内容为 initialValue 值

### What is actually happening?
第一次 console 内容为空

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | Chrome 85.0.4183.83 |

**Comment by zombieJ** [comment]
Field 注册是 mount 后注册，时机会不太一样。我调一下看看同步会不会有问题。

**Comment by zombieJ** [comment]
时序上，Field 只有 mount 后才能算入 Form 中以防止只注册不添加节点导致的 Field 不受控问题。我看看怎么改进。
