### ISSUE TITLE
ConfigProvider支持form.requiredMark配置

### ISSUE THREAD

**Issue by xch1029** [ant-design/ant-design#27317]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
通过ConfigProvider统一设置requiredMark的样式

### What does the proposed API look like?
<ConfigProvider form={{ requiredMark: 'optional' }} >

**Comment by afc163** [comment]
你需要修改成什么呢？

**Comment by xch1029** [comment]
> 你需要修改成什么呢？
现在这么写<ConfigProvider form={{ requiredMark: 'optional' }} >，表单并没有接收到requiredMark的全局配置，我想要能够全局配置form的requiredMark属性，可以实现吗

**Comment by afc163** [comment]
你如果需要改成 `optional`，感觉是国际化的问题，是否直接使用英文语言包就行了。

**Comment by zombieJ** [comment]
看了一下，的确 ConfigProvider 里没有全局的 `requiredMark`。感觉是可以加一下

**Comment by hengkx** [comment]
![image](https://user-images.githubusercontent.com/8358236/96975291-da5a9780-154c-11eb-8a85-458c5f56306e.png)
配置这个的吧  感觉 可以来一下
