### ISSUE TITLE
Table 组件 fixed 列 v3 和 v4 宽度表现不同 (Table fixed column width effect different in v3 and v4)

### ISSUE THREAD

**Issue by nbhaohao** [ant-design/ant-design#27313]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/gudinglie-ant-design-demo-forked-3coqu?file=/index.js)

### Steps to reproduce
1. v4 demo https://codesandbox.io/s/gudinglie-ant-design-demo-forked-yhtyf
2. v3 demo https://codesandbox.io/s/gudinglie-ant-design-demo-forked-3coqu?file=/index.js

### What is expected?
希望 v4 中的 fixed 列的宽度效果和 v3 的一样，

在 v3 版本中，其他列会尽量占满表格宽度，而 fixed 的列只保留自己内容的宽度，但是在 v4 版本中，fixed 的列和其他列会平分表格的宽度。
由于我们的系统之前是用的 v3 组件库，现在想迁移到 v4。
场景是每行的固定列的宽度可能不一样，所以不方便指定 fixed 列的 width，希望 fixed 列的宽度自适应为内容的宽度

![image](https://user-images.githubusercontent.com/23535619/96883269-ce21fc00-14b2-11eb-8dad-e51ea802eacd.png)

I hope the width effect of the fixed column in v4 is the same as that of v3,

In the v3 version, other columns will try to fill the width of the table, while the fixed column only retains the width of its content, but in the v4 version, the fixed column and other columns will equally divide the width of the table.
Since our system used v3 component library before, we now want to migrate to v4.
The scenario is that the width of the fixed column of each row may be different, so it is not convenient to specify the width of the fixed column.

### What is actually happening?
v4 和 v3 版本表现不一致，v4 中的 fixed 列平分了表格的宽度。

The v4 and v3 versions behave inconsistently. The fixed column in v4 divides the width of the table equally.

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 17.0.1 |
| System | macOS10.15.6 |
| Browser | Google Chrome 86.0.4240.80 |

**Comment by afc163** [comment]
v4 是更好的方式，v3 由于实现方式所有固定列是一个新的 Table，无法参与原生 table 的布局。

v4 现在都是同一个 table 元素，不指定宽度的情况下和非固定列的布局一致。

楼主的需求在 v4 的实现下还是需要指定宽度，建议计算可能的最大操作数量来预估可能的宽度。

**Comment by nbhaohao** [comment]
了解了，谢谢回复。
