### ISSUE TITLE
antd4.5以上版本

### ISSUE THREAD

**Issue by yhjm-xixi** [ant-design/ant-design#27326]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/spec/introduce-cn#%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE](https://ant.design/docs/spec/introduce-cn#%E5%A6%82%E4%BD%95%E8%B4%A1%E7%8C%AE)

### Steps to reproduce
筛选条件是Form 包裹 ，结果是table表格 。
table设置分页，切换每页数量，比如 30条/页  切换成 10条/每页，
提示报错 Uncaught (in promise) 。

### What is expected?
4.1.3之前版本是好的。

### What is actually happening?
跟Form包裹的筛选条件，
切换分页并收集form数据提交时，提示报错Uncaught (in promise)。
备注(点击具体页码是正常的 只有切换每页数量时报错)。

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | ^16.12.0 |
| System | windows 10 |
| Browser | chrome |

**Comment by miaofei** [comment]
![image](https://user-images.githubusercontent.com/16551098/96993763-54474c80-155e-11eb-8032-af8bea28087f.png)

**Comment by yhjm-xixi** [comment]
[codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-jj2mu?file=/index.js) 
点击修改分页数量

**Comment by yhjm-xixi** [comment]
> Hello @miaofei. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @miaofei, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

**Comment by yhjm-xixi** [comment]
> Hello @miaofei. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @miaofei, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

[codesandbox](https://codesandbox.io/s/antd-reproduction-template-forked-jj2mu?file=/index.js)
