### ISSUE TITLE
右键菜单的实现

### ISSUE THREAD

**Issue by LeungManwei** [ant-design/ant-design#2732]
#### 本地环境

- antd 版本:1.9
- 操作系统及其版本：WIN10
- 浏览器及其版本: chrome 52

#### 你做了什么？
右键菜单的实现

#### 你期待的结果是：
希望加入右键菜单的实现
https://github.com/vkbansal/react-contextmenu

**Comment by GrayChoi** [comment]
你可以结合下[Menu](http://ant.design/components/menu/)和[Popover](http://ant.design/components/popover/)

**Comment by LeungManwei** [comment]
@GrayChoi 效果不一样吧。目前我是用react- contextmenu实现了，然后是希望antd加入相应的功能，使得效果开起来更加整体一点。毕竟现在公司项目也是全部上的antd

**Comment by benjycui** [comment]
把普通的 `Menu` 定位一下就可以了，`top` 和 `left` 可以从右键事件中获取。

```xml
<Menu style={{ position: 'fixed', top: x, left: y }}>
  ...
</Menu>
```

**Comment by FatFatFox** [comment]
@Manweill  你在antd中实现了react-contextmenu框架的右键菜单吗？
我在antd-admin框架里用，样式完全不起作用

**Comment by Manweill** [comment]
@FatFatFox 印象中要自己加入react-contextmenu的样式

**Comment by FatFatFox** [comment]
@Manweill 那你subMenu是怎么加的？

**Comment by Manweill** [comment]
@FatFatFox 没有用SubMenu，用的是他内置的MenuItem

**Comment by FatFatFox** [comment]
@Manweill  好，谢谢

**Comment by FatFatFox** [comment]
@benjycui 按你建议的方案实现是不是有些细节都要考虑
比如右键触发了menu显示后，还要枚举什么情况让他消失。

**Comment by aoto** [comment]
@afc163 @benjycui 请教一下，我这边通过设置Menu组件的位置来实现右键菜单，问题是显示的时候怎么探测菜单的边界，不让它超出可视区？基于antd3

![default](https://user-images.githubusercontent.com/2315342/35567768-299f1c5c-0601-11e8-83b3-bb2b581c7f0b.png)


急，谢谢

**Comment by xiongchen2012** [comment]
😄
