### ISSUE TITLE
Popconfirm 触发时会进行三次定位，导致页面效果为：触发后从一个错误位置跳动到正确位置

### ISSUE THREAD

**Issue by NorthwesternDirector** [ant-design/ant-design#27320]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
点击 Popconfirm 后，先显示在一个错误的位置之后马上移动到正确的位置

### What is expected?
点击 Popconfirm 后，就在正确的位置上显示

### What is actually happening?
在错误的位置先显示，后显示在正确的位置，给用户一种弹框位移的感觉

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.12.0 |
| System | win10 |
| Browser | Chrome 85.0.4183.83 |

---
Popconfirm 隐藏时的默认位置为C ，出现时是在一个错误的位置A，然后再次定位到正确的位置B，从 Chrome 调试工具中看到对应 element 上的 style left top 属性值 由C变到A再变到B ，问题很难排查出来，但在demo中无法复现，故想请教下可能是哪方面的问题呢

**Comment by NorthwesternDirector** [comment]
这个问题在demo中无法复现，但在开发中一直存在，不知道为什么会多定位一次，tooltip 和 popconfirm 都有这个出现后跳动一下的问题

**Comment by afc163** [comment]
没有重现我们也不知道问题出在哪了。

**Comment by NorthwesternDirector** [comment]
😣

**Comment by afc163** [comment]
可以帮忙排查一下。

**Comment by hengkx** [comment]
是不是和这个 类似 #27316 我刚在竖屏也 出现了 换横屏 好了

**Comment by NorthwesternDirector** [comment]
> 是不是和这个 类似 #27316 我刚在竖屏也 出现了 换横屏 好了

这个问题也是我之前提的，按此配置只能保证最终的位置是正常展示，但第一次跳动仍旧存在，我争取把问题在demo里复现，太感谢你们的回复啦🥰

**Comment by NorthwesternDirector** [comment]
> 可以帮忙排查一下。

复现了！可能和全局配置 <ConfigProvider> 有关，配置了之后，初次点击 Popconfirm  会跳动一次
https://codesandbox.io/s/jibenyongfa-ant-design-demo-forked-7o8jm?file=/index.js

**Comment by NorthwesternDirector** [comment]
> 是不是和这个 类似 #27316 我刚在竖屏也 出现了 换横屏 好了

复现了！可能和全局配置 ConfigProvider 有关，配置了之后，初次点击 Popconfirm 会跳动一次
https://codesandbox.io/s/jibenyongfa-ant-design-demo-forked-7o8jm?file=/index.js

**Comment by hengkx** [comment]
@NorthwesternDirector 来个gif？ 我这没办法重现

**Comment by NorthwesternDirector** [comment]
> @NorthwesternDirector 来个gif？ 我这没办法重现

试了一下刚才复现是我屏幕大小的原因，不是导致这个问题的根本😞
