### ISSUE TITLE
antd 和 moment 使用cdn资源时，日期组件不能正常国际化

### ISSUE THREAD

**Issue by KingThq** [ant-design/ant-design#27327]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
使用CDN资源，日期组件能正常国际化

### What does the proposed API look like?
我引用的cdn地址分别为：
开发环境：'https://cdn.jsdelivr.net/npm/moment@2.25.3/moment.js'，'https://cdn.jsdelivr.net/npm/antd@4.6.3/dist/antd.js'；
生产环境：'https://cdn.jsdelivr.net/npm/moment@2.25.3/moment.min.js'，'https://cdn.jsdelivr.net/npm/antd@4.6.3/dist/antd.min.js',

**Comment by KingThq** [comment]
重现仓库：https://github.com/KingThq/antd-DateComponent.git
重现步骤：安装依赖，启动看到日期选择框，语言是英文
补充说明：在 config.ts 中配置如下：

`externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
    moment: 'moment',
    lodash: '_',
    antd: 'antd',
  }`

`scripts:
    process.env.NODE_ENV === 'development'
      ? [
          'https://cdn.jsdelivr.net/npm/react@16.8.6/umd/react.development.js',
          'https://cdn.jsdelivr.net/npm/react-dom@16.8.6/umd/react-dom.development.js',
          'https://cdn.jsdelivr.net/npm/moment@2.25.3/moment.js',
          'https://cdn.jsdelivr.net/npm/lodash@4.17.11/lodash.js',
          'https://cdn.jsdelivr.net/npm/antd@4.6.3/dist/antd.js',
        ]
      : [
          'https://cdn.jsdelivr.net/npm/react@16.8.6/umd/react.production.min.js',
          'https://cdn.jsdelivr.net/npm/react-dom@16.8.6/umd/react-dom.production.min.js',
          'https://cdn.jsdelivr.net/npm/moment@2.25.3/moment.min.js',
          'https://cdn.jsdelivr.net/npm/lodash@4.17.11/lodash.min.js',
          'https://cdn.jsdelivr.net/npm/antd@4.6.3/dist/antd.min.js',
        ],`

**Comment by afc163** [comment]
https://github.com/KingThq/antd-DateComponent/pull/1
