### ISSUE TITLE
Style PointerEvents ignore Form.Item children 

### ISSUE THREAD

**Issue by joseAAlexandre** [ant-design/ant-design#27330]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-qu05k?file=/index.js)

### Steps to reproduce
Hover the label "Click Here"

### What is expected?
When hover the label with props name work same as without the name props.

### What is actually happening?
When hover the label with props name work different when without the props. 

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.1 |
| System | Windows |
| Browser | Chrome 86.0.4240.111 (Versão oficial) 64 bits |

**Comment by afc163** [comment]
Which is correct behavior in your opinion?

**Comment by joseAAlexandre** [comment]
Not allow focus on children

**Comment by afc163** [comment]
You can set another id for Input for this feature.

https://codesandbox.io/s/antd-reproduction-template-forked-uong8
