### ISSUE TITLE
Allow for different/multiple/custom filter models in Table filterDropdown

### ISSUE THREAD

**Issue by fgblomqvist** [ant-design/ant-design#27331]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
If you want to have more complex filters than "a set of strings or numbers" you need to be able to have custom filter models. For example, if I want to have a search box that allows me to specify whether the search should be case-sensitive or not. Or a number filter that allows me to specify an operator (such as greater-than, less-than, equals, etc.). The list goes on. Right now, the state functions that are provided to a filter dropdown in Table are `selectedKeys` and `setSelectedKeys`. They only store a set of numbers/strings for you.

### What does the proposed API look like?
Replace those functions with something like `currentModel` and `setModel`:
```
interface FilterModel {
  type: string;
}

setModel: (model: FilterModel) => void;
currentModel: FilterModel;
```

Models could look like this:
```ts
// The user could override the Antd FilterModel in order to gain type-safety based on which models they declared
interface FilterModel {
  type: 'number' | 'keys' | 'text';
}

// Here are some sample models
type NumberFilterModel = {
  type: 'number';
  value: number;
  operator: 'greater_than' | 'less_than' | 'equal';
};

type KeysFilterModel = {
  type: 'keys';
  values: React.Key[];
}

type TextFilterModel = {
  type: 'text';
  value: string;
  caseSensitive: boolean;
}
```

Advanced tables/apps could define many of these models to suit every need for different kinds of filters.
In e.g. the `handleTableChange` function, one could then iterate over the filters and determine the type by checking the `type` property, and then cast to that type. Finally it could do any specific processing/checking on each filter before sending it to a back-end or using it to filter the values.

Technically, you can probably use generics for this and allow the user to pass in their version of `FilterModel` (or just their type for the `FilterModel.type` property).

**Comment by afc163** [comment]
My suggestion is wrapping your filter models in upper component, antd should stick to a simple model for best.

**Comment by fgblomqvist** [comment]
> antd should stick to a simple model for best
Is the goal to make a simple framework or a good UI/UX?
