### ISSUE TITLE
antd 如何对一个或多个组件进行设置不同主题色？

### ISSUE THREAD

**Issue by w602542704** [ant-design/ant-design#27346]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当一个按钮或<Slider/>滑动组件因为全局只有一个主题色，所以组件都牵连受影响，在一个项目中想改一个或多个组件不同颜色的背景颜色和伪类颜色成本很高，如果组件有单独设置主题色的属性则降低开发成本

### What does the proposed API look like?
在一个项目中，一些的组件支持改主题色的属性功能

**Comment by afc163** [comment]
目前还不支持，可以追踪 #5656

**Comment by xrkffgg** [comment]
啊，这，那我必须要推一波了。

https://ant-design-colorful.github.io/ant-design-colorful/
