### ISSUE TITLE
When a button that has a tooltip is disabled, all of its classes and styles go to the tooltip wrapper

### ISSUE THREAD

**Issue by gslvrp** [ant-design/ant-design#27340]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-hw95z?file=/index.js)

### Steps to reproduce
Wrap a tooltip around a button with a className and disable the button.

### What is expected?
The disabled button maintain the className and all the styles it had when it was enabled.

### What is actually happening?
The className is going to the "ant-tooltip-disabled-compatible-wrapper" element, which is wrapping the button, messing up with the button style.

| Environment | Info |
|---|---|
| antd | 4.7.2 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome Version 86.0.4240.111 64 bits |

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/pull/4865/files#diff-186839a30bf8b9d67a4b10bf7c091d5fR88
https://github.com/react-component/tooltip/issues/18
https://github.com/ant-design/ant-design/issues/17449
#18534

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/21404#issuecomment-586800984
