### ISSUE TITLE
When using a collapsible sidebar with webpack 5 and react 17, it crashes

### ISSUE THREAD

**Issue by Floffah** [ant-design/ant-design#27354]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://pastebin.com/AViJLQA7](https://pastebin.com/AViJLQA7)

### Steps to reproduce
Create a component that has a layout with a collapsible sider and render it to an element with the id root

### What is expected?
it makes a layout with a collapsible sider

### What is actually happening?
this error: https://imgur.com/BWKfSay 

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Firefox |

---
hooks amiright

**Comment by afc163** [comment]
trace #26136
