### ISSUE TITLE
希望Tabs增加属性可以控制Tabs.TabPane隐藏时自动销毁(I hope that the added attributes of Tabs can control the automatic destruction of Tabs.TabPane when hidden)

### ISSUE THREAD

**Issue by SystemLight** [ant-design/ant-design#27357]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Tabs结合redux-router的Redirect组件实现多标签切换路由，现在的Tabs.TabPane当组件渲染一次后隐藏时不会销毁，导致Redirect组件没有执行，这样只能通过onChange事件主动监听调用，实现起来不是很优雅。

### What does the proposed API look like?
通过destroyOnClose属性控制TabPane 隐藏时可以销毁组件(Hope to add destroyOnClose property to control TabPane destruction)
```
<Tabs type="editable-card" hideAdd={true} size={"small"} destroyOnClose={true}>
    <TabPane key={"hello1"} tab={"容器"} forceRender={false}>
        <Redirect to={"/hello1"} />
    </TabPane>
    <TabPane key={"hello2"} tab={"跳转"} forceRender={false}>
        <Redirect to={"/hello2"} />
    </TabPane>
</Tabs>
```

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/17920#issuecomment-515868765

**Comment by ngmiduc** [comment]
Is there any progress on this feature ?

**Comment by SystemLight** [comment]
> Is there any progress on this feature ?

try to use the `destroyInactiveTabPane` propety

**Comment by ngmiduc** [comment]
Thanks it worked!
