### ISSUE TITLE
Safari 浏览器下报错 ResizeObserver loop completed with undeliverd notifications

### ISSUE THREAD

**Issue by fengsx** [ant-design/ant-design#27359]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/fengsx/antd-resize-observer-loop](https://github.com/fengsx/antd-resize-observer-loop)

### Steps to reproduce

1、使用 umi@3.2.24 新建工程
2、替换 index.tsx 的内容如下。

```
import React from 'react';
import { Table } from 'antd';

const { Column } = Table;

const showField = [
  { dataIndex: 'ID', title: 'ID', key: 'ID', width: 130 },
  { dataIndex: 'a', title: 'a', key: 'a', width: 130 },
  { dataIndex: 'b', title: 'b', key: 'b', width: 150 },
  { dataIndex: 'c', title: 'c', key: 'c', width: 120 },
  { dataIndex: 'd', title: 'd', key: 'd', width: 130 },
  { dataIndex: 'e', title: 'e', key: 'e', width: 150 },
  { dataIndex: 'f', title: 'f', key: 'f', width: 150 },
  { dataIndex: 'g', title: 'g', key: 'g', width: 150 },
  { dataIndex: 'h', title: 'h', key: 'h', width: 150 },
  { dataIndex: 'i', title: 'i', key: 'i', width: 150 },
  { dataIndex: 'j', title: 'j', key: 'j', width: 150 },
  { dataIndex: 'k', title: 'k', key: 'k', width: 100 },
  { dataIndex: 'l', title: 'l', key: 'l', width: 180 },
  { dataIndex: 'm', title: 'm', key: 'm', width: 140 },
  { dataIndex: 'n', title: 'n', key: 'n', width: 110 },
  { title: '操作', dataIndex: 'n', key: 'n', fixed: 'right', width: 220 },
];

export default () => {
  return (
    <div>
      <h1>Safari 浏览器下报错 ResizeObserver loop completed with undeliverd notifications</h1>
      <Table rowKey="ID" scroll={{ x: 'max-content', y: 500 }} dataSource={[]}>
        {showField.map((field, index) => (
          <Column {...field} key={index} />
        ))}
      </Table>
    </div>
  );
};

```

3、运行 `yarn start` 之后，用 Safari 打开

### What is expected?
不报错

### What is actually happening?
![image](https://user-images.githubusercontent.com/7709602/97103692-03b02a80-16e9-11eb-96fa-cb05f689ee34.png)

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.14.0 |
| System | Mac OS 10.15.7 (19H2) |
| Browser | Safari 14.0 (15610.1.28.1.9, 15610) |

**Comment by zombieJ** [comment]
神奇，看起来是 Safari only 的 warning。

**Comment by zombieJ** [comment]
试了一下，改成 raf 后 Table 会明显闪动，体验会变差。

**Comment by fengsx** [comment]
最小的复现代码是
```
<Table columns={[]} dataSource={[]} scroll={{  x: 500 }} />
```

在 `dataSource` 为 `[]`、`null` 或者 `undefined`，同时设置了 scroll.x 的情况下，一定会发生。

继续排查中。

**Comment by fengsx** [comment]
发现是 [rc-table](https://github.com/react-component/table) 的问题。

**Comment by hotzenklotz** [comment]
We just updated our project to the latest antd version 4.15.0 and also have this error. Works find with Chrome/Firefox but Safari has the error.

Safari 14.0.3 (6610.4.3.1.7) on MacOS 11.2.3 (20D91) (BigSur)

**Comment by Aaronius** [comment]
I'm able to reproduce this on 4.16.1

**Comment by ruizhang-chowbus** [comment]
also encounter this error, the antd version is 4.11.1

**Comment by afc163** [comment]
Trace #26621
