### ISSUE TITLE
Integrate debounce and throttle in Select & AutoComplete, with example using React function component

### ISSUE THREAD

**Issue by ceefour** [ant-design/ant-design#27351]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
In Select & AutoComplete, when fetching options remotely it will take quite some time.
When fetch is called every time onSearch (user types one character), this will slow down app and also increase burden on server.

Therefore, debounce and throttle is needed. This is a very common use case that I believe a lot of people need and should be supported natively by Ant Design.

Currently: https://ant.design/components/select/ provides a debounce example however it still uses React.Component class-based structure and uses external lodash library.

Though I mention Select & AutoComplete, when this feature is implemented, this feature can be used similarly by other components.

### What does the proposed API look like?
1. Integrate debounce and throttle functionality. You may depend on https://github.com/xnimorz/use-debounce , or fork it into Ant Design project. I think the API is good and very intuitive.
2. Update Select & AutoComplete documentation to: use React functional component, and demonstrate the debounce/throttle integration.

### Additional notes

This has been requested before: https://github.com/ant-design/ant-design/issues/12136

A lot of people are requesting this feature.

I'm worried that this feature request will be rejected again. If it gets rejected, at least please add/update documentation in Select & AutoComplete on how to implement debounce easily using React functional component (not class component).

**Comment by afc163** [comment]
See https://ant.design/components/select/#components-select-demo-select-users for a example to use debounce.

**Comment by ceefour** [comment]
@afc163 https://ant.design/components/select/#components-select-demo-select-users only provides example using class component, but not using functional component.

Should I create a new feature request for functional component example?

**Comment by afc163** [comment]
You can send a PR to migrate this demo to functional component. 🤝

**Comment by iorabiadopo** [comment]
Used the debounce and worked perfectly in the Select component, can't say the same in the AutoComplete:
the delay works just fine but if I type a word let's say, the dropdown will start flashing as many times as the letters I typed.
