### ISSUE TITLE
Logging FormInstance.getFieldValue(fieldName) causes browser to freeze/crash

### ISSUE THREAD

**Issue by nrayburn-tech** [ant-design/ant-design#27355]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-ui7rl?file=/index.js)

### Steps to reproduce
Open Sandbox
Click the Get Label button
Browser will freeze or crash

### What is expected?
Browser to remain responsive, information logged from the call

### What is actually happening?
Browser is freezing or crashing

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17.0.01 |
| System | macOS 10.15.7 |
| Browser | Brave Version 1.14.84 Chromium: 85.0.4183.121 (Official Build) (64-bit) |

**Comment by afc163** [comment]
It is a codesandbox issue to show instance in their console, won't happen in development mode.
