### ISSUE TITLE
Tree component leaf line disjoint if title is too long

### ISSUE THREAD

**Issue by gohyinhao** [ant-design/ant-design#27364]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ant-473-tree-with-line-bug-lj07z?file=/index.js)

### Steps to reproduce
1. for tree data, have a leaf node with a really long title
2. set Tree to hide leaf icon

### What is expected?
line should be connected

### What is actually happening?
line is disjoint

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.12.0 |
| System | macOS 10.15.5 |
| Browser | chrome 86.0.4240.75 |

---
more common use case for encountering this bug would be if Tree is placed inside a modal or antd drawer with a small width

**Comment by zombieJ** [comment]
发现 tree 的 intend className 似乎有 bug...
