### ISSUE TITLE
Avatar should accept image component

### ISSUE THREAD

**Issue by xinghul** [ant-design/ant-design#27360]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
right now Avatar only accepts `src` and `srcSet`, it would be great if it also takes an img component.

### What does the proposed API look like?
<Avatar image={<img src="..." />} />

**Comment by n0ruSh** [comment]
@afc163 Can i take it one?

**Comment by xinghul** [comment]
thanks for the pr @n0ruSh , looks like you forgot to update the typing?
for `AvatarProps`, `src?: string;` -> `src?: string | React.ReactNode;`?

**Comment by n0ruSh** [comment]
> thanks for the pr @n0ruSh , looks like you forgot to update the typing?
> for `AvatarProps`, `src?: string;` -> `src?: string | React.ReactNode;`?

aha.. my bad. Shall I create anther pr against feature branch to resolve this?

**Comment by yoyo837** [comment]
master is better.
