### ISSUE TITLE
upload组件，使用fileList来回显一个图片列表的时候。 其中UploadFile 类型中size字段是必传的。实际上有的时候没有加载图片链接是拿不到这个size的

### ISSUE THREAD

**Issue by SeanHit** [ant-design/ant-design#27368]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
undefined

### Steps to reproduce
·

### What is expected?
·

### What is actually happening?
· 

| Environment | Info |
|---|---|
| antd | 3.26.18 |
| React | 16.10.2 |
| System | - |
| Browser | chrome |
![image](https://user-images.githubusercontent.com/51781927/97132183-24c45a00-1781-11eb-901d-1caa3f34163d.png)

**Comment by zombieJ** [comment]
`size: null`
