### ISSUE TITLE
Popconfirm、ToolTip第一次加载时，会有跳动

### ISSUE THREAD

**Issue by xiaofengqqcom123** [ant-design/ant-design#27362]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jibenyongfa-ant-design-demo-forked-c7ceb?file=/index.js)

### Steps to reproduce
第一次加载页面，点击“Delete”，Popconfirm 弹跳出现（即：先在相对于父节点 top：0， left：0的地方出现，再在正确位置出现）

### What is expected?
点击“delete”，直接在正确位置出现

### What is actually happening?
Popconfirm 弹跳出现（即：先在相对于父节点 top：0， left：0的地方出现，再在正确位置出现）

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | react@16.13.1 |
| System | mac |
| Browser |  86.0.4240.75 |

**Comment by xrkffgg** [comment]
我这里点，没出现跳动

**Comment by xiaofengqqcom123** [comment]
> 我这里点，没出现跳动

有的，设置了getPopupContainer后，第一次点击“delete”按钮都会跳动
https://codesandbox.io/s/jibenyongfa-ant-design-demo-forked-ytt6y?file=/index.js

**Comment by yoyo837** [comment]
此复现 我这里跳动。

**Comment by afc163** [comment]
怎么和 https://github.com/ant-design/ant-design/issues/27316#issuecomment-714872269 的例子一模一样。

**Comment by hengkx** [comment]
> 怎么和 [#27316 (comment)](https://github.com/ant-design/ant-design/issues/27316#issuecomment-714872269) 的例子一模一样。

我改成了left 同样 存在

**Comment by xiaofengqqcom123** [comment]
> 怎么和 [#27316 (comment)](https://github.com/ant-design/ant-design/issues/27316#issuecomment-714872269) 的例子一模一样。
基于那个改的，现在问题是：加了getPopupContainer，一定会复现~
我们的项目中，未加getPopupContainer也会复现（我们正在排查中）

**Comment by holly-juan** [comment]
> > 怎么和 [#27316 (comment)](https://github.com/ant-design/ant-design/issues/27316#issuecomment-714872269) 的例子一模一样。
> 
> 基于那个改的，现在问题是：加了getPopupContainer，一定会复现~
> 我们的项目中，未加getPopupContainer也会复现（我们正在排查中）

hi 你的这个问题解决了吗？遇到了同样的问题

**Comment by xiaofengqqcom123** [comment]
没有解决发自我的华为手机-------- 原始邮件 --------发件人： holly-juan <notifications@github.com>日期： 2020年10月30日周五 傍晚6:51收件人： ant-design/ant-design <ant-design@noreply.github.com>抄送： xiaofeng <1944681023@qq.com>, Author <author@noreply.github.com>主    题： Re: [ant-design/ant-design] Popconfirm、ToolTip第一次加载时，会有跳动 (#27362)





怎么和 #27316 (comment) 的例子一模一样。



基于那个改的，现在问题是：加了getPopupContainer，一定会复现~

我们的项目中，未加getPopupContainer也会复现（我们正在排查中）



hi 你的这个问题解决了吗？遇到了同样的问题

**Comment by ddoonngg** [comment]
> > 怎么和 [#27316 (comment)](https://github.com/ant-design/ant-design/issues/27316#issuecomment-714872269) 的例子一模一样。
> 
> 我改成了left 同样 存在

有没有可能是因为[这里](https://github.com/react-component/align/blob/93641c5afcbb85362db9df2f32c49b56eac3f597/src/Align.tsx#L133)的useEffect里的副作用（forceAlign）是在浏览器paint之后执行的，所以会出现跳动（Align的过程）。改成[useLayoutEffect](https://reactjs.org/docs/hooks-reference.html#uselayouteffect)会有用吗？

**Comment by zhixiaoqiang** [comment]
Popover 同样会跳动，`content`内容填充时间会影响自动计算位置的结果，我这边做了内容在接口返回后再延迟300ms展示就不跳了

**Comment by Ifeinstein** [comment]
https://github.com/ant-design/ant-design/issues/27102#issuecomment-714241022  试试， 也许问题在这

**Comment by alexchen1875** [comment]
tooltip也有同样的问题,如果是通过ConfigProvider 配置的,还会导致tooltip和popconfirm的placement 失效且被遮挡的问题:
![GIF 2020-11-12 11-09-00](https://user-images.githubusercontent.com/3668637/98890715-90275f00-24d7-11eb-87f2-f0f340e424b1.gif)

**Comment by kerm1it** [comment]
@xiaofengqqcom123 现在我按照 demo 里面的步骤没有复现，你再试试呢？

**Comment by xiaofengqqcom123** [comment]
> @xiaofengqqcom123 现在我按照 demo 里面的步骤没有复现，你再试试呢？

第一次进去的时候，会有问题~

**Comment by kerm1it** [comment]
![Nov-12-2020 21-30-25](https://user-images.githubusercontent.com/33770367/98946047-546bb400-252e-11eb-9326-3ae85d324067.gif)

**Comment by kerm1it** [comment]
https://codesandbox.io/s/jibenyongfa-ant-design-demo-forked-ytt6y?file=/index.js

这个例子复现了，其实就是说，getPopupContainer 设为 不是 body 的时候会复现，默认应该是没问题的吧？

**Comment by lubyxu** [comment]
transformName = '' 会导致动画丢失。 一顿瞎操作，发现给Popover增加`overlayStyle={{transform: 'scale(1)'}}`属性，就可以解决抖动的同时，还不丢失动画。

具体什么原因，希望大佬们能帮忙说明下。。。

**Comment by FateRiddle** [comment]
默认的使用就会复现，而且不是第一次，每次都会跳。使用了@lubyxu 给的解法解决了。

**Comment by afc163** [comment]
@kerm1it 升级到 4.13.0 后貌似问题消失了：https://codesandbox.io/s/jibenyongfa-ant-design-demo-forked-3mrw5?file=/index.js

**Comment by kerm1it** [comment]
![Mar-03-2021 11-08-41](https://user-images.githubusercontent.com/33770367/109746831-011e8e00-7c11-11eb-9a40-ddb1ce47c30c.gif)

在小窗口试还是不行，但是我发现用单独窗口打开是没有问题的，很奇怪。

**Comment by cike8899** [comment]
增加`overlayStyle={{transform: 'scale(1)'}}`依然会有问题，第一次弹出没问题了，但是后面再弹出还会跳动

**Comment by wengsj11** [comment]
这个bug有找到问题吗

**Comment by aa323522** [comment]
> overlayStyle={{transform: 'scale(1)'}}

加入这个destroyTooltipOnHide 属性看看，这样每次都是第一次弹出了（目前我这边是可以这样弄）

**Comment by Akimyou** [comment]
> Popover 同样会跳动，`content`内容填充时间会影响自动计算位置的结果，我这边做了内容在接口返回后再延迟300ms展示就不跳了

我使用 antd 5 尝试给 content 加一个默认的宽高好像就可以了，参考：

```
content={
                <div style={{ width: 150, minHeight: 100 }}>
```
