### ISSUE TITLE
使用System.import的时候报错System is not defined

### ISSUE THREAD

**Issue by blackboyhc** [ant-design/ant-design#2736]
我是想实现动态加载module，所以使用System.import，但是报错System is not defined
我搜索了下说是webpack 2支持System.import了，所以antd支持吗？

**Comment by afc163** [comment]
antd 只是 UI 库，不涉及这些范畴。

**Comment by blackboyhc** [comment]
@afc163 我的意思是，我用的antd-init建的项目，所以用整套开发工具都是自带的，所以想问下这种情况下如果要实现动态加载module是应该怎么处理？

**Comment by afc163** [comment]
可以尝试 https://webpack.github.io/docs/code-splitting.html
