### ISSUE TITLE
When Input.Group wraps Select and Input, there is a problem with the width of Input

### ISSUE THREAD

**Issue by duan602728596** [ant-design/ant-design#27377]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/duan602728596/antd-inputgroup-bug-demo](https://github.com/duan602728596/antd-inputgroup-bug-demo)

### Steps to reproduce
Run the `yarn start` command, and then preview ʻindex.html`

### What is expected?
The width of `Input.Group` is equal to the width of `Select` plus the width of `Input`
![截屏2020-10-26 下午5 41 01](https://user-images.githubusercontent.com/17332657/97157071-92d54500-17b2-11eb-8ef0-f8b53655b0ff.png)

### What is actually happening?
The width of `Input` in `Input.Group` is 100%

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17.0.1 |
| System | Mac |
| Browser | Chrome 86.0.4240.111 |

**Comment by xrkffgg** [comment]
https://ant.design/components/input-cn/#components-input-demo-group

**Comment by duan602728596** [comment]
It seems unable to set the className attribute of `Input`.

**Comment by ndmnh** [comment]
Actually the className does get set to Input, just that you have to specify `!important` on the width. I tried putting a `background-color: salmon` and it does show up.

Anyway can I work on this if no one is?

**Comment by afc163** [comment]
See https://ant.design/components/input-cn/#components-input-demo-group
