### ISSUE TITLE
Modal组件设置destroyOnClose={true}，关闭modal时依然执行了被modal包裹的组件

### ISSUE THREAD

**Issue by lincolon** [ant-design/ant-design#27372]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/modal-cn/#API](https://ant.design/components/modal-cn/#API)

### Steps to reproduce
<Modal
            maskClosable={false}
            centered={true}
            title={}
            onOk={}
            visible={this.state.visible}
            onCancel={() => this.setState({visible: false, initData: null})}
            destroyOnClose={true}
            width={590}
            confirmLoading={loading}
          >
            <MyComp 
              {...restProps} 
              type={this.state.type}
              data={this.state.initData} 
              wrappedComponentRef={(formRef) => this.formRef = formRef} 
            />
          </Modal>

执行setState({visible: false, initData: null})之后，弹窗关闭，但是继续执行了MyComp组件里的逻辑， MyComp是一个函数式组件

### What is expected?
先销毁被Modal包裹的组件，再关闭Modal

### What is actually happening?
好想时同时执行的

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.1 |
| System | mac os 10.15.5 |
| Browser | chrome84 |

---
4.6.3的时候还没有这个问题，这是最近一次更新后出现的问题，我测试的时候切换了版本，证实了版本升级导致的

**Comment by lincolon** [comment]
> Hello @lincolon. Please provide a online reproduction by forking this link https://u.ant.design/codesandbox-repro or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @lincolon, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
>

https://codesandbox.io/s/antd-reproduction-template-forked-hlnn0?file=/index.js

**Comment by lincolon** [comment]
@afc163 这个问题什么时候修复呢，想升级不能升级呀，如果短时间不能修复的话，我就做兼容处理了，持续升级，跟上大部队了

**Comment by kerm1it** [comment]
这个问题我来跟进吧。

**Comment by kerm1it** [comment]
感觉正确的逻辑应该是，关闭的时候，弹窗的内容不应该重新渲染吧？而不是先销毁子元素再销毁弹窗，这样动画显示时应该会有问题的。

**Comment by lincolon** [comment]
> 感觉正确的逻辑应该是，关闭的时候，弹窗的内容不应该重新渲染吧？而不是先销毁子元素再销毁弹窗，这样动画显示时应该会有问题的。

嗯嗯，我是从4.6.3升级到4.7.3的时候发现这个问题的，是不是应该是动画执行完了之后，再去执行组件销毁呢，看一下我这里的demo
https://codesandbox.io/s/antd-reproduction-template-forked-hlnn0?file=/index.js

**Comment by kerm1it** [comment]
我复现了，大概知道怎么修改了，下午改一下试试。
