### ISSUE TITLE
Select组件选项正好为8个时，会出现滚动条，并且点击滚动条会报错

### ISSUE THREAD

**Issue by skimklin** [ant-design/ant-design#27374]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/sizes-ant-design-demo-forked-pq89s?file=/index.js)

### Steps to reproduce
点开下拉框，鼠标点击滚动条

### What is expected?
下拉框不出现滚动条

### What is actually happening?
下拉组件出现滚动条，并且点击滚动条会报错

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.12.0 |
| System | windows |
| Browser | chrome 85 |

**Comment by skimklin** [comment]
![image](https://user-images.githubusercontent.com/27659365/97154910-813e6e00-17af-11eb-8fe6-7c99d603ebb3.png)

**Comment by skimklin** [comment]
![image](https://user-images.githubusercontent.com/27659365/97154943-8e5b5d00-17af-11eb-815e-c9bdcf76d90c.png)

**Comment by BugHiding** [comment]
size | 选择框大小 | large \| middle \| small | middle
-- | -- | -- | --

**Comment by yoyo837** [comment]
ref: #27282 #27373

**Comment by xrkffgg** [comment]
后续统一在 #27282 解决。
