### ISSUE TITLE
Upload的一点问题，盼回复

### ISSUE THREAD

**Issue by chairui2001** [ant-design/ant-design#2737]
#### 本地环境

- 浏览器及其版本: Chrome 版本 45.0.2454.99 (64-bit)

#### 你做了什么？

在Form中使用Upload

#### 你期待的结果是：

1. Upload控件可以跨域上传图片
2. Form中的Upload可以正常设置onChange事件处理器

#### 实际上的结果：

1. Upload控件无法跨域
2. getFieldProps 会导致 Upload的onChange无效

**Comment by afc163** [comment]
1. https://github.com/ant-design/ant-design/search?q=upload+%E8%B7%A8%E5%9F%9F&type=Issues&utf8=%E2%9C%93
2. http://ant.design/components/form/#this.props.form.getFieldProps(id,-options) 注意特别说明

**Comment by chairui2001** [comment]
你好，1. 后台已经设置过`‘Access-Control-Allow-Origin‘:‘*‘、 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS'、'Access-Control-Allow-Headers': 'X-Requested-With, Content-Type'`这些，jquery的ajax跨域上传没有问题。根据你回复的链接，前端尝试过X-Requested-With、withCredentials等设置调整，但还是不能解决问题，附上浏览器Headers：

> General
Remote Address:192.168.0.66:80
Request URL:http://192.168.0.66/parklinks_develop/uploadfile
Request Method:OPTIONS
Status Code:200 OK

> Response Headers
Allow:GET, HEAD, POST, PUT, DELETE, TRACE, OPTIONS, PATCH
Connection:keep-alive
Content-Length:0
Date:Wed, 17 Aug 2016 02:37:10 GMT
Server:nginx/1.10.1

> Request Headers
Accept:*/*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:zh-CN,zh;q=0.8
Access-Control-Request-Headers:content-type, x-requested-with
Access-Control-Request-Method:POST
Cache-Control:no-cache
Connection:keep-alive
Host:192.168.0.66
Origin:http://localhost:8080
Pragma:no-cache
Referer:http://localhost:8080/register
User-Agent:Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.99 Safari/537.36

> Console
XMLHttpRequest cannot load http://192.168.0.66/parklinks_develop/uploadfile. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.

**Comment by chairui2001** [comment]
你好，2.你发的链接我没太明白，我这边是定义了一个PicUpload组件
```
    render() {
        const uploadProps = {
            action: API_BASE + 'uploadfile',
            listType: "picture",
            fileList: this.state.fileList,
            onChange: info => this.uploadChange(info),
        };
        return (
            <Upload {...uploadProps} {...this.props}>
                <Button type="ghost"><Icon type="upload" /> 点击上传</Button>
            </Upload>
        );
    }
```
其中uploadChange和官网的一样，只是起到限制图片数量的作用。

接下来，如果在FormItem中这样使用`<PicUpload />`，uploadChange中的逻辑会执行，但和表单脱离关系了；而`<PicUpload {...getFieldProps('operatorPicUp', {valuePropName: 'fileList', normalize: normFile})} />`会发现uploadChange中的console没有输出，逻辑也没有执行。

**Comment by chairui2001** [comment]
如果限制上传图片数量可以作为一个参数，是否会更方便些？

**Comment by chairui2001** [comment]
我也试了不另外定义PicUpload组件，像官网一样直接在FormItem中用Upload，onChange事件也没有执行

**Comment by afc163** [comment]
自行比较一下 jQuery ajax 上传方案和 antd Upload 上传的 header 吧。

**Comment by baibing** [comment]
+1,

遇到了同样的问题，Upload本身的onChange和FormItem的onChange会互相overwrite，只有后引入的才会被call

http://ant.design/components/form/#this.props.form.getFieldProps(id,-options)，这个链接里有写说getFieldProps 返回的属性包括onChange，所以不应再设置同样的属性，那还如何定义upload的onChange去获取新上传的文件信息呢？

**Comment by baibing** [comment]
测试后发现只有直接使用form item的onChange去handle file upload就可以，建议更新一下demo code

**Comment by benjycui** [comment]
@baibing http://ant.design/components/form/#getFieldProps-options

用 Form.Item 的 onChange 太诡异。

**Comment by baibing** [comment]
只有这样才可以work，只能算是一个暂时的workaround，除非antd team的人能够fix这个conflict

**Comment by benjycui** [comment]
不是发了链接你了么。。都不看的啊。。

**Comment by baibing** [comment]
可能你理解错了，其实我的做法就是你发的链接里写的，把onChange写到FormItem的getFieldProps里面去了

在demo code里仍然是写在upload上的，http://ant.design/components/form/#components-form-demo-mix

**Comment by benjycui** [comment]
`getFieldProps` 放到 `Upload` 上才是设计的行为，如果这样有问题，麻烦提供可重现 demo

Please provide a re-producible demo: http://codepen.io/benjycui/pen/KgPZrE?editors=001
