### ISSUE TITLE
Components in virtual scroll mode cannot be scrolled in Edge browser

### ISSUE THREAD

**Issue by LazyJoke** [ant-design/ant-design#27370]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant-design.gitee.io/components/tree-cn/#header](https://ant-design.gitee.io/components/tree-cn/#header)

### Steps to reproduce
It seems that none of the virtual scrolling lists can trigger scrolling

### What is expected?
Can't scroll

### What is actually happening?
Virtual scroll list cannot be scrolled

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.1 |
| System | windows 10 |
| Browser | Microsoft Edge 44.18362.449.0 |

**Comment by afc163** [comment]
Could you reproduce it in lastest Edge version?
