### ISSUE TITLE
auto-complete组件在确定类目情况下的滚动会报错

### ISSUE THREAD

**Issue by xiuse-liutao** [ant-design/ant-design#27373]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/auto-complete-cn/](https://ant.design/components/auto-complete-cn/)

### Steps to reproduce
使用auto-complete组件在确定类目情况下的滚动会报错

### What is expected?
能正常下拉滚动

### What is actually happening?
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.8 |
| System | win10 |
| Browser | 版本 87.0.4280.11（正式版本） （64 位） |

**Comment by yoyo837** [comment]
ref: #27282
