### ISSUE TITLE
Typography.Paragraph with props ellipsis an error 'Invalid regular expression...' occurs.

### ISSUE THREAD

**Issue by roman7722** [ant-design/ant-design#27382]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/ellipsis-ant-design-demo-forked-rul78?file=/index.js)

### Steps to reproduce
When adding the '(' character into a text of the component 'Typography.Paragraph' with props ellipsis an error 'Invalid regular expression...' occurs.

### What is expected?
No expected Syntax Error

### What is actually happening?
SyntaxError
Invalid regular expression: /^Ant Design, a design language (for background applications, is refined by Ant UED Team. Ant Design, a design language for background applications, is refined by Ant UED Team. Ant Design, a design language for bac/: Unterminated group

![image](https://user-images.githubusercontent.com/33327916/97167601-23eaf280-1798-11eb-9888-5b4bdbf03291.png)

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.12, 17.0.1 |
| System | Ubuntu Linux 20.04 |
| Browser | Google Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
Fixed in #27383
