### ISSUE TITLE
Use headless CMS to manage antd's official website dynamic content

### ISSUE THREAD

**Issue by hi-rustin** [ant-design/ant-design#27389]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Related comment: 

[Use headless CMS](https://github.com/ant-design/ant-design/pull/27379#issuecomment-716522408)

### What does the proposed API look like?
TBD

**Comment by xrkffgg** [comment]
Emm，感觉可以直接建个项目放这个，存一个 json 文件，然后用 axios 请求 Raw ，每次更新那个 json 就行。

就是用的 GitHub 地址，网络会限制一些。

**Comment by Rustin-Liu** [comment]
> 就是用的 GitHub 地址，网络会限制一些。

我感觉大多数网络下 这个 raw 的地址是没法访问的。

**Comment by xrkffgg** [comment]
不过本身网站就是放到 GitHub Pages  上的。

**Comment by Rustin-Liu** [comment]
> 不过本身网站就是放到 GitHub Pages 上的。

那国内的镜像会不会影响 cc: @ant-design/ant-design-collaborators

**Comment by xrkffgg** [comment]
感觉可以用 Gitee  的 raw ，国内国外访问应该都还可以。

**Comment by xrkffgg** [comment]
我看现在 Gitee 上 ant-design 的代码是一直随着 GitHub 上更新的。

仿照这个，只维护 GitHub，然后访问 Gitee 的地址应该可以。

但是不太确定国外对 Gitee  的访问到底如何，我开 US 全局，是能访问到。

**Comment by afc163** [comment]
谁来调研一下？https://jamstack.org/headless-cms/

- 价格
- 速度
- 体验

**Comment by hengkx** [comment]
> 谁来调研一下？https://jamstack.org/headless-cms/
> 
> * 价格
> * 速度
> * 体验

刚看了下 我竟然 不知道 是什么 时候 关注了 这个项目🤣

**Comment by afc163** [comment]
@ant-design/ant-design-collaborators 谁来参考这个 https://github.com/antvis/gatsby-theme-antv/pull/240 搞一下 antd 的，非常简单。

**Comment by Kermit-Xuan** [comment]
@afc163 建个仓库吧

**Comment by afc163** [comment]
https://github.com/ant-design/website-data
