### ISSUE TITLE
TreeSelect和Tree 数据中title,key,children 字段能自定义。

### ISSUE THREAD

**Issue by qflyx** [ant-design/ant-design#27385]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
从后台获取到的数据不需要重新处理，或是找后端修改返回数据的字段。

### What does the proposed API look like?
和Ant Design Vue中TreeSelect和Tree 的replaceFields一样。

**Comment by yoyo837** [comment]
title: <组件 /> 这样不可以吗？

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/24282#issuecomment-640323898
