### ISSUE TITLE
BUG：Collapse.Panel 组件 header 属性设置其他组件后，发生事件冒泡错误

### ISSUE THREAD

**Issue by leejaen** [ant-design/ant-design#2738]
在header中添加组件中添加其他组件，在点击后，panel的header仍然响应click折叠事件。
Ps. 能否在下个版本中尽快修复，项目要上线……
谢谢antd团队

codePen: http://codepen.io/leejaen/pen/RRdgJx

**Comment by benjycui** [comment]
这个不算 bug，`Collapse` 无法知道是否需要阻止冒泡。

自行处理即可 https://www.google.com.hk/?ion=1&espv=2#q=react%20stopimmediatepropagation

**Comment by leejaen** [comment]
既然让用户自定义header里面的内容，发生冒泡之后却需要手动处理，少数几个这种情况还可以，但是频繁需要这种方式的时候，是不是至少算是“不合理”的设计？ 而且用户用此功能都会出现这个问题。

但是我还是觉得直接在 header里默认加上这个功能比较好，实现方式很简单，只需要在header里的div添加 onClick={(event)=>{event.stopPropagation();}} 即可，最好添加 css 属性 display:inline-block; 。

**Comment by leejaen** [comment]
@abc163

**Comment by leejaen** [comment]
@afc163

**Comment by Wh33** [comment]
这个问题你是怎么解决的？

**Comment by leejaen** [comment]
加一个div或span 制定onClick：
<span onClick={(event)=>{event.stopPropagation();}}>
