### ISSUE TITLE
FormList 配合 namePath，getFieldsValue 内容异常。

### ISSUE THREAD

**Issue by juzhiyuan** [ant-design/ant-design#27396]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/#name-%E4%B8%BA%E6%95%B0%E7%BB%84%E6%97%B6%E7%9A%84%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99%EF%BC%9F](https://ant.design/components/form-cn/#name-%E4%B8%BA%E6%95%B0%E7%BB%84%E6%97%B6%E7%9A%84%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99%EF%BC%9F)

### Steps to reproduce
```tsx
<Form.List name="nodes">
        {(fields, { add, remove }) => (
            {fields.map((field, index) => (
              <Form.Item
                required
                key={field.key}
              >
                    <Form.Item
                      name={[field.name, 'host']}
                    >
                      <Input placeholder="域名/IP" disabled={readonly} />
                    </Form.Item>
              </Form.Item>
            ))}
        )}
      </Form.List>
```

使用  `form.getFieldsValue` 时，从第二条数据开始，内容变为：
```json
{
  "nodes": [
    {
      "host": "123"
    }, 
    {
      "host": "456",
      "altKey": null,
      "cancelable": null,
      "defaultPrevented": null,
      "dispatchConfig": null,
      "getModifierState": null,
      "等等 Event": null
    }
  ]
}
```

### What is expected?
只有 host 字段

### What is actually happening?
包含了类似 Event 的键

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.8.6 |
| System | MacOS Catalina |
| Browser | Chrome |

**Comment by juzhiyuan** [comment]
![image](https://user-images.githubusercontent.com/2106987/97270154-a4c5ef00-1869-11eb-8a87-d1e0cf6a13e4.png)

**Comment by WustLCQ** [comment]
解决了吗？同遇到这问题
