### ISSUE TITLE
table固定列后加上rowSelection错位

### ISSUE THREAD

**Issue by dyf2015** [ant-design/ant-design#2739]
列都已设置宽度，但是如果加上rowSelection，表格就会错位。

**Comment by dyf2015** [comment]
![image](https://cloud.githubusercontent.com/assets/16314313/17722055/d0379ff0-6461-11e6-8e48-77e2c061ca8f.png)
![image](https://cloud.githubusercontent.com/assets/16314313/17722066/ea969c70-6461-11e6-925f-3e06e855eae7.png)

**Comment by dyf2015** [comment]
给总宽度补60px 解决了

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by dyf2015** [comment]
const { Table } = antd;

const columns = [
  { title: '姓名', width: 100, dataIndex: 'name', key: 'name', fixed: 'left' },
  { title: '年龄', width: 100, dataIndex: 'age', key: 'age', fixed: 'left' },
  { title: '列1', dataIndex: 'address', key: '1', width: 150 },
  { title: '列2', dataIndex: 'address', key: '2', width: 150 },
  { title: '列3', dataIndex: 'address', key: '3', width: 150 },
  { title: '列4', dataIndex: 'address', key: '4', width: 150 },
  { title: '列5', dataIndex: 'address', key: '5', width: 150 },
  { title: '列6', dataIndex: 'address', key: '6', width: 150 },
  { title: '列7', dataIndex: 'address', key: '7', width: 150 },
  { title: '列8', dataIndex: 'address', key: '8', width: 150 },
  {
    title: '操作',
    key: 'operation',
    fixed: 'right',
    width: 100,
    render: () => <a href="#">操作</a>,
  },
];

const data = [];
for (let i = 0; i < 100; i++) {
  data.push({
    key: i,
    name: `李大嘴${i}`,
    age: 32,
    address: `西湖区湖底公园${i}号`,
  });
}

const rowSelection = {
  onChange:function() {
    
  }
}

function App() {
  return <Table columns={columns} dataSource={data} scroll={{ x: 1500, y: 300 }} bordered size="middle" rowSelection={rowSelection} />;
}

ReactDOM.render(<App />, document.getElementById('container'));

**Comment by dyf2015** [comment]
不好意思，不知道怎么把运行结果截过来，这里有两个问题。
1、当表格自身的长度大于滚动长度，会出现列错位重叠
2、当加上rowSelection，也会出现列重叠

以上代码都能重现，chrome下

**Comment by afc163** [comment]
学习下 markdown 吧，你在这里提问也很多次了，这代码让大家如何阅读。

https://guides.github.com/features/mastering-markdown/

**Comment by afc163** [comment]
`100 + 100 + 150*8 + 100` = `1500`

因为加上 rowSelection 了，多了一列，所以总宽度不够了，这个还是合理的。你加上宽度的解决方案也是对的。

**Comment by afc163** [comment]
一般来说，不要给每一列都定宽，留一列或几列弹性布局会比较好。

**Comment by dyf2015** [comment]
好的，我学习下MD，谢谢！

果然有一个弹性列，滚动长度超过表格长度就不出现错位了！
