### ISSUE TITLE
可以支持 react 17了吗

### ISSUE THREAD

**Issue by hihuangwei** [ant-design/ant-design#27397]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
可以支持 react 17了吗

### What does the proposed API look like?
可以支持 react 17了吗

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/issues/27339#issuecomment-716615715

**Comment by hengkx** [comment]
close #26136
