### ISSUE TITLE
鼠标在 Modal 窗口外释放导致其自动关闭

### ISSUE THREAD

**Issue by Delphier** [ant-design/ant-design#27391]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/yl46k)

### Steps to reproduce
1. 打开一个Modal窗口。
2. 在 Modal 窗口任意位置按住鼠标不要松，然后移动指针到 Modal 窗口外面。
3. 释放鼠标，此时 Modal 窗口自动被关闭。

### What is expected?
Modal 窗口不应被自动关闭。

### What is actually happening?
自动关闭。

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16 |
| System | Windows 10 |
| Browser | Chrome |

---
v4.6.6 及以前版本均正常，自 4.7.0 开始有此问题。

此问题导致的一个结果时：比如 Modal 窗口有一 Input，用户用鼠标快速拖选其中的内容，此时鼠标很容易移出 Modal 窗口外，导致窗口自动关闭。

**Comment by zengwei2** [comment]
鼠标移出弹窗外关闭弹窗影响用户体验

**Comment by afc163** [comment]
Fixed in https://github.com/react-component/dialog/pull/210
