### ISSUE TITLE
Prompt antd style

### ISSUE THREAD

**Issue by guido-visser** [ant-design/ant-design#27399]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
Sometimes you just want a quick input from a user, just a text field. Javascript provides `prompt`, but that is not conform antd. Could a `modal.prompt` be created. A modal with 1 textfield that the user can fill out?

### What does the proposed API look like?
```tsx
Modal.prompt({
    title: string,
    content: string,
    onOk: (value: string) => void
  });
```

**Comment by afc163** [comment]
It is hard to cover all situations such as there is usually a complex form in Modal.

**Comment by guido-visser** [comment]
The idea and situations are not complex at all. It's a prompt window just like `prompt`, but with antd styling... The idea is that it contains a Form with just one text field. Isn't that just a single situation? Isn't that what the Modal methods are for?

**Comment by afc163** [comment]
In most situations, we need a Form instead of a single text field. So I prefer not to provide this kind of Modal.xxx function but recommend  `<Modal></Model>`.
