### ISSUE TITLE
Table的一些建议

### ISSUE THREAD

**Issue by shenlm203** [ant-design/ant-design#274]
你好，有一些关于table的建议如下，这几天没有关注更新log，有些问题可能已经注意到了，这只是我在开发中想到的一些改进点，希望有帮助：

1. 由于各个团队的业务不尽相同，建议在做远程加载数据的时候，能够暴露出ajax的api，让开发者自己写IO异步逻辑。
2. 如果传入数据为空，建议给出一个默认的暂无数据的td或者类似节点。
3. rowselection 的一些优化

+ 可否暴露出方法，获取当前被用户选中的行的所有data数据；
+ 能够增加一个全选、反选、取消功能，比如要在table下方设置全选/反选/取消按钮，可以对当页选中进行控制；
+ 此外我们在开发业务过程中，需求方又提出可否支持翻页选取(即在翻页的时候，保留上一页的勾选数据)。

**Comment by afc163** [comment]
1. 完全可以自行写 io 逻辑，使用 dataSource 直接写数据。
2. 这个是有的。http://ant.design/components/table/#demo-local-data
3. rowselection 的相关需求比较复杂，后续可能需要重构或移出交由业务实现。https://github.com/ant-design/ant-design/issues/252

如果有相关需求，建议先自行尝试改造。

**Comment by shenlm203** [comment]
好的

**Comment by zhechang520** [comment]
通过文档没有发现如何合并列...  求问。。

**Comment by skyblue** [comment]
rowselection 目前是否是只能点击在checkbox处才生效? 能否点击行选中, 行的点击事件是否能暴露?
