### ISSUE TITLE
4.x版本中  步骤条样式不居中

### ISSUE THREAD

**Issue by king-lxt** [ant-design/ant-design#27405]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fant.design%2F](https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fant.design%2F)

### Steps to reproduce
打开链接  https://codepen.io/pen/?&editable=true&editors=001=https%3A%2F%2Fant.design%2F

### What is expected?
步骤条描述 和  步骤条居中展示

### What is actually happening?
步骤条描述 和  步骤条居中展示

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.8 |
| System | Mac OS |
| Browser | chrome  86.0.4240.111 |

**Comment by yoyo837** [comment]
https://codesandbox.io/s/zidingyidianzhuangbuzoutiao-ant-design-demo-forked-j160o

**Comment by yoyo837** [comment]
@07akioni 好像和这个有关#24907
