### ISSUE TITLE
Antd dot-state level of article not centered step

### ISSUE THREAD

**Issue by king-lxt** [ant-design/ant-design#27402]
![image](https://user-images.githubusercontent.com/23032062/97286340-5838de80-187e-11eb-9590-d4a5c6522e3b.png)

**Comment by yoyo837** [comment]
https://codesandbox.io/s/zidingyidianzhuangbuzoutiao-ant-design-demo-forked-j160o

**Comment by yoyo837** [comment]
move to #27405
