### ISSUE TITLE
Typography Paragraph Rendering issue

### ISSUE THREAD

**Issue by AramRafeq** [ant-design/ant-design#27408]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-otjj3?file=/index.js)

### Steps to reproduce
Just try to put 
``کواڵکۆم لە بۆنەیەکی ساڵانەدا بە ناوی Qualcomm) Tech Summit-لووتکەی تەکنەلۆژیای کواڵکۆم) نوێترین چیپسێتەکانی ساڵ نمایش دەکات، ئەمساڵیش کواڵکۆم وادەی بۆنەکەی دیاری کرد و لە ڕۆژی 1ـی مانگی داهاتوو بۆ کۆتایی ڕۆژی 2ـی مانگی داهاتوو بەڕێوە دەچێت پێشبینی دەکرێت چیپسێتی سناپدراگۆن 875 بە بناغەی 5 نانۆمەترییەوە ڕابگەیەنرێت لەگەڵ ڕاگەیاندی چیپسێتی سناپدراگۆن 775، کە کواڵکۆم سناپدراگۆن 875``
text inside the <Typography.Paragraph /> with ellipses prop configuration watch the sandbox demo 

### What is expected?
it is expected to display the text

### What is actually happening?
 component with ellipsis it gives new  regular expression error

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | latest |
| System | windows 10 |
| Browser | chrome |

**Comment by afc163** [comment]
Fixed in #27383
