### ISSUE TITLE
IE11 Select输入框只显示半截文字

### ISSUE THREAD

**Issue by zjuasmn** [ant-design/ant-design#2741]
#### 本地环境

- antd 版本: 1.9.0
- 操作系统及其版本：Win 8
- 浏览器及其版本: IE11

#### 你做了什么？

使用官网的Select的多选和智能提示。

#### 你期待的结果是：

正常显示输入文字

#### 实际上的结果：

文字只显示半截

#### 可重现的在线演示

http://ant.design/components/select/

![image](https://cloud.githubusercontent.com/assets/4462778/17722919/7a98c54a-6468-11e6-840e-c13f6797f3c9.png)

**Comment by afc163** [comment]
感谢反馈~
