### ISSUE TITLE
DescriptionItem not support hoc

### ISSUE THREAD

**Issue by paranoidjk** [ant-design/ant-design#27411]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/9bfc7b64](https://riddle.alibaba-inc.com/riddles/9bfc7b64)

### Steps to reproduce
- open riddle

### What is expected?
DescriptionItem with custom style and content

### What is actually happening?
not work

| Environment | Info |
|---|---|
| antd | 4.5.4 |
| React | latest |
| System | any |
| Browser | any |

---
- similar with https://github.com/ant-design/ant-design/issues/5165
- looks like part of https://github.com/ant-design/ant-design/issues/4853

**Comment by paranoidjk** [comment]
cc/ @zombieJ

**Comment by paranoidjk** [comment]
i think this bug is because of https://github.com/ant-design/ant-design/blob/master/components/descriptions/Row.tsx#L20

**Comment by zombieJ** [comment]
Since Descriptions.Item is a syntactic sugar, we may not aim to support HOC tmp.

ref #4853
