### ISSUE TITLE
antd less file causes storybook compile to fail

### ISSUE THREAD

**Issue by rkesters** [ant-design/ant-design#27414]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/rkesters/storybook-ui](https://github.com/rkesters/storybook-ui)

### Steps to reproduce
npm run storybook

### What is expected?
Successful compile

### What is actually happening?
ERROR in ./node_modules/antd/lib/tooltip/style/index.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js??ref--8-2!./node_modules/antd/lib/tooltip/style/index.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):

}
.generator-tooltip-preset-color();
^
Variable @m-6 is undefined
      in /Users/rkesters/code/node/bonfire-ui/node_modules/antd/lib/tooltip/style/index.less (line 204, column 0)

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17.0.1 |
| System | OSX |
| Browser | Chrome |

**Comment by afc163** [comment]
<img width="914" alt="image" src="https://user-images.githubusercontent.com/507615/97332981-0318bf00-18b6-11eb-9056-350c40e403c6.png">

It runs without errors in my machine by following your steps.

**Comment by rkesters** [comment]
I deleted my node_modules and `npm i` , now all is working. Closing.
