### ISSUE TITLE
switch在form中使用时，无法通过form对switch进行赋值操作

### ISSUE THREAD

**Issue by DeanPeter** [ant-design/ant-design#27415]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://riddle.alibaba-inc.com/riddles/c73bd1cd](https://riddle.alibaba-inc.com/riddles/c73bd1cd)

### Steps to reproduce
看链接的riddle，在form中使用switch，无法通过form给switch赋值

### What is expected?
点击test按钮后，switch切换为true状态

### What is actually happening?
点击test按钮后，switch状态不变

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16 |
| System | 任意 |
| Browser | 任意 |

**Comment by yoyo837** [comment]
内网看不见复现 😂

**Comment by afc163** [comment]
`valuePropName`

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/507615/97384219-3be28380-190a-11eb-93b2-f497d35865b6.png">
