### ISSUE TITLE
New "short" mode for multiple select 

### ISSUE THREAD

**Issue by pjeannet** [ant-design/ant-design#27427]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We are trying to create an inline filter form with a short length. When using select in multiple or tag modes, the display is not adapted to small length as chosen options are rendered as tags. We would like a mode where instead of displaying selected options in the input part we would have the select name and the number of selected options. This could also be done with a `inputRender` property and custom react. Such an option would be really usefull for selects with few options (like a category filter).

Sample screenshot from jira :
![image](https://user-images.githubusercontent.com/6052793/97429191-5ff89180-1917-11eb-9b77-c0cb6e0902a6.png)

### What does the proposed API look like?
Native mode :
```jsx
import { Badge, Select } from 'antd';

const { Option } = Select;

function handleChange(value) {
  console.log(`selected ${value}`);
}

ReactDOM.render(
  <Select mode="short" style={{ width: '100%' }} placeholder="Tags Mode" onChange={handleChange}>
     <Option value="jack">Jack</Option>
     <Option value="lucy">Lucy</Option>
  </Select>,
  mountNode,
);
```
Custom input render :
```jsx
import { Select } from 'antd';

const { Option } = Select;

function handleChange(value) {
  console.log(`selected ${value}`);
}

ReactDOM.render(
  <Select 
      inputRender={values => (<>Name  <Badge count={values.length} /></>) }
      mode="multiple" 
      style={{ width: '100%' }} 
      placeholder="Tags Mode" 
      onChange={handleChange}
  >
     <Option value="jack">Jack</Option>
     <Option value="lucy">Lucy</Option>
  </Select>,
  mountNode,
);
```

**Comment by afc163** [comment]
You could wrap as a upper bussiness component,

**Comment by jjalonso** [comment]
@afc163  how is possible to modify the input look from a wrapper component?
