### ISSUE TITLE
Upload的一点问题，续

### ISSUE THREAD

**Issue by chairui2001** [ant-design/ant-design#2742]
我的问题被关闭了，不知道我的回复你还看不看得到，所以又提交一个新的，请原谅。原问题回复见https://github.com/ant-design/ant-design/issues/2737

**Comment by benjycui** [comment]
* 即使 issue 被关闭，你也是可以重新打开。
* 一个问题不要分开在两个 issue 中讨论，信息不全别人也帮不了你。
