### ISSUE TITLE
FormItem与Col都存在布局属性时某个断点下出现布局错乱

### ISSUE THREAD

**Issue by travonf** [ant-design/ant-design#27437]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://stackblitz.com/edit/antd-form-layout?file=index.tsx)

### Steps to reproduce
存在设定的FormItemLayout时，将屏幕尺寸调整至992px - 768px时，布局错乱，label无法右对齐

### What is expected?
* sm：单列垂直布局
* md：单列水平布局，label可以右对齐，这个断点下不符合预期
* lg：双列垂直布局
* xl：双列水平布局

### What is actually happening?
label对齐失效

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17.0.1 |
| System | Windows 10 |
| Browser | Chrome 86 |

---
FormItem与Col结合使用时，如果只有Col存在布局属性，某些断点（比如sm、xs时）下会将Form布局从水平调整为垂直，
需要自定义，比如说以下断点时：  
* sm：单列垂直布局
* md：单列水平布局
* lg：双列垂直布局
* xl：双列水平布局

**Comment by afc163** [comment]
无法重现，你给的例子里没有设定 FormItemLayout。

**Comment by travonf** [comment]
> 无法重现，你给的例子里没有设定 FormItemLayout。

没保存成功，已重新修改，
https://stackblitz.com/edit/antd-form-layout?file=index.tsx

![image](https://user-images.githubusercontent.com/18564432/97829741-e93c0980-1d05-11eb-92cb-007a650cb17f.png)

**Comment by travonf** [comment]
没人看下吗？我想确认一下是写法错了还是存在问题？

**Comment by zombieJ** [comment]
```diff
  formItem: {
--    lg: 24,
++    lg: 4,
  },
  wrapperCol: {
--    lg: 24,
++    lg: 20,
  }
```
