### ISSUE TITLE
InputNumber组件在Form表单中设置验证规则{whitespace：true}时，输入数字后，校验不通过

### ISSUE THREAD

**Issue by xueni-liuhui** [ant-design/ant-design#27432]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-l0udm?file=/index.js)

### Steps to reproduce
输入数字即可发现下方浮动出现“字段仅包含空格”的校验信息；

### What is expected?
InputNumber组件在表单校验中能够对{whitespace：true}正确校验

### What is actually happening?
尝试用最新的4.7.3测试发现，此错误依旧存在

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | 16.13.1 |
| System | windows |
| Browser | Edge  86.0.622.56 |

**Comment by Janka55** [comment]
这个问题最新版好像还是没修4.21.3
