### ISSUE TITLE
升级后Table组件的checkbox选取失效

### ISSUE THREAD

**Issue by weiq** [ant-design/ant-design#2744]
#### 本地环境

- antd 版本: 1.8
- react  版本 15.2.1
- 操作系统及其版本：win7
- 浏览器及其版本: chrome
#### 你做了什么？

升级antd从1.7到1.8，升级到1.9也有同样的问题。在1.7中一切正常

使用Table组件，官网上的第二个例子，加载成功后点击checkbox，结果选取无效，debug发现onChange回调函数中收到的为空数组

但用codepen模拟时又正常了，怀疑是否是在1.8中对Table的一些修改导致的问题。

**Comment by NsLib** [comment]
+1 1.7 mac下正常，升级后异常

**Comment by afc163** [comment]
给重现，codepen 中是 1.9 的。

**Comment by weiq** [comment]
找到原因发现是用browser-sync导致的，打包后正常。但1.7为什么就好使呢？

**Comment by dai875939260** [comment]
我也是使用了browser-sync ，然后所有checkbox的选中都不正常。看了dom结构，span元素就是没加上选中的样式，而且IE下是正常的，chrome不正常，一直找不出原因，感觉是事件问题

**Comment by afc163** [comment]
没有使用过 browser-sync ，可以帮忙排查么？

**Comment by wmzy** [comment]
rc-checkbox 1.4.0没问题，1.4.1有这个问题，应该是因为加了onClick事件导致的。

**Comment by dai875939260** [comment]
@weiq 你现在那个是怎么解决的

**Comment by dai875939260** [comment]
的确是换成rc-checkbox 1.4.0没问题了,1.4.1增加onClick是为了解决什么问题吗？ @afc163

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/2610

**Comment by weiq** [comment]
@dai875939260 我的办法也不是太好，通过配置[Browsersync](https://www.browsersync.io/docs/options#option-snippetOptions)禁止注入脚本
snippetOptions: {
  ignorePaths: "*"
}
如果你有更好的方法，请告诉我一下

**Comment by dai875939260** [comment]
@weiq 我是直接将rc-checkbox切换到1.4.0了,禁止注入脚本Browsersync是不是有些功能 不能用了？

**Comment by weiq** [comment]
@dai875939260 我暂时只用到它的热加载功能，这个是好使的，具体其它功能你可以上它的官网上了解一下。

**Comment by zengsizhang** [comment]
@weiq 
   我按照你的方法配置了，还是不行，有DEMO吗？谢谢

**Comment by afc163** [comment]
@dai875939260 为什么增加 onClick 会导致 browser-sync 的异常？

**Comment by kossel** [comment]
I just got the same problem.
had to disable browser-sync snippet injection to temporary fix it.

**Comment by cleverjam** [comment]
I am having the same issue, but I do need the browser sync feature for cross browser testing (disabling this feature is not possible), are you guys planning on working on a fix any time soon?

**Comment by yesmeck** [comment]
Since we do not use browser-sync, if anyone can provide a repo with browser-sync setup, I'll look into this issue.

**Comment by kossel** [comment]
Hello I have created a demo project in

https://github.com/kossel/playground

step to reproduce:

`Clone the project`
`npm install`
`npm start`

It will start with browsersync in dev environment
you will notice the checkbox can not be checked

Browsersync will inject this client so everything will be sync across all the tabs
https://github.com/BrowserSync/browser-sync-client/blob/master/dist/index.js

but looks something has conflicts with the checkbox

**Comment by wmzy** [comment]
可以通过禁用browser-sync 的 ghostMode 临时解决问题：
```javascript
          bs.init({
            // disable for https://github.com/ant-design/ant-design/issues/2744
            **ghostMode**: false,

            // ......
          });
```

当然，这不是最终的解决方案......

**Comment by benjycui** [comment]
@dai875939260 @afc163 this problem is introduced by https://github.com/react-component/checkbox/commit/ecb79f8221173809ad18941e4a6c62137c9b8636 , not `onClick`.

**Comment by benjycui** [comment]
And I don't think it's a bug introduced by rc-checkbox.

Actually, it's just browser-sync cannot work well with rc-checkbox...

**Comment by benjycui** [comment]
It seems that the issue is from `browser-sync`

Before we inject `browser-sync-client`:

![image](https://cloud.githubusercontent.com/assets/3580607/23298853/231c98da-faba-11e6-9dd6-ea158d1f5a7a.png)

After:

![image](https://cloud.githubusercontent.com/assets/3580607/23298894/56f827c8-faba-11e6-9c99-f2ece4ca68d3.png)

For `browser-sync-client` will [trigger `onFocus` and `onBlur` programmatically](https://github.com/BrowserSync/browser-sync-client/blob/0b70ab9dc8484ea7eb38f26278195a211a1716fd/lib/browser.utils.js#L96-L99), and this will break `rc-checkbox`'s lifecycle. And then, [`e.target.checked`](https://github.com/react-component/checkbox/blob/a598b025b36a766fa08d38781902cc7d71640308/src/Checkbox.jsx#L72) from `onChange` of `input[type=checkbox]` will always be `false`.

This is why we cannot check an antd.Checkbox after using `browser-sync`.

**Comment by benjycui** [comment]
Of course we can refactor `rc-checkbox` to avoid `browser-sync`'s issue.

But, the best solution is fix this in `browser-sync`, for other component which is based on `onFocus` and `onBlur` will met this problem, too.

**Comment by benjycui** [comment]
I am not sure whether we need to refactor `rc-checkbox` and find a new way to save focused state @afc163 

But I think this issue can be close now. And hope someone who are familiar with `browser-sync`'s community will create an issue in repo of `browser-sync`, thanks.

**Comment by benjycui** [comment]
After discussion, we will try to refactor rc-checkbox, but you had better create issue in repo of browser-sync
