### ISSUE TITLE
Pass custom className to clearable input

### ISSUE THREAD

**Issue by Parader** [ant-design/ant-design#27444]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-issue-repro-custom-classes-clearable-input-jpubc?file=/src/App.js)

### Steps to reproduce
Inspecting the input element shows that it's missing the custom class passed to the component

### What is expected?
Input component should be able to receive custom classNames when allowClear is set to true

### What is actually happening?
Input component do not receive custom classNames when allowClear is set to true

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.1 |
| System | Window 10 |
| Browser | Chrome |

---
Changes introduced in [this](https://github.com/ant-design/ant-design/commit/27e9926438ba533143257ac19957584722c95afd) commit is what prevents custom className to be passed when allowClear is set to true

**Comment by Jarvis1010** [comment]
I found this when looking in the code
<img width="720" alt="Screen Shot 2020-10-29 at 2 19 40 PM" src="https://user-images.githubusercontent.com/5460770/97642003-cc53bd80-1a09-11eb-9ce8-79726f992b6c.png">
The className only gets applied if I pass a value into both `addonBefore` and `addonAfter` prop
