### ISSUE TITLE
document of attribute "hoverable" of Card component is incorrect

### ISSUE THREAD

**Issue by kaizvn** [ant-design/ant-design#27442]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/3.x-stable](https://github.com/ant-design/ant-design/blob/3.x-stable)

### Steps to reproduce
In changelog : https://3x.ant.design/changelog it said that "Card's **noHovering** has been renamed to **hoverable**, and its default value now is `true`."
But, in the document of Card says different : **hoverable**'s default value is `false.`

### What is expected?
Default value of attribute **hoverable** in Card document should be `true`.

### What is actually happening?
Default value of attribute **hoverable** in Card document  is `false`.

| Environment | Info |
|---|---|
| antd | 3.26.20 |
| React | react 16.x |
| System | mac os 10.14 |
| Browser | chrome 86.0.4240.111 |

**Comment by afc163** [comment]
No, default value of `hoverable` is `false`, document is correct.

**Comment by kaizvn** [comment]
> No, default value of `hoverable` is `false`, document is correct.

Oh I see. So let me updated the issue.

**Comment by afc163** [comment]
PR welcome~

**Comment by kaizvn** [comment]
> PR welcome~

@afc163 please have a look on my PR #27483, since it said that branch was off the maintenance period.
