### ISSUE TITLE
Table renders "ghost" rows that are no longer being passed into dataSource prop

### ISSUE THREAD

**Issue by kylebebak** [ant-design/ant-design#27449]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ibb.co/MS5t4tv](https://ibb.co/MS5t4tv)

### Steps to reproduce
Regarding the repro: creating a "minimal repro" of this bug could be difficult, because it's not easy to reproduce. I'm creating this issue with a screenshot that demonstrates the bug quite clearly. Here are the steps to repro:

- render a table with sticky headers
- start with a big array of objects you pass in to the table's `dataSource` prop
- change (don't mutate, replace entirely) this `dataSource` every 10s or so for a few minutes
  + change its order, length, which records you include / filter out

### What is expected?
Ant doesn't render rows in your table that aren't present in your data source.

### What is actually happening?
Ant renders rows in your table that were previously present in your data source, but are no longer present in your data source. Let's call these "ghost rows". This data source hasn't been mutated -- it has been totally replaced with a different data source which no longer contains certain rows, but these rows are still rendered.

Here is a screenshot where I'm passing an empty array into `dataSource`, but the table still includes several ghost rows from a previous `dataSource`. Ant **seems to know I'm passing an empty dataSource in, because it's rendering the empty state "No Data" message at the bottom of the table**, but it still renders the ghost rows.

>It's worth noting it takes a while to break the table. You can scroll through it, fetch additional pages, filter, sort, etc, for a while before ghost rows appear. The set of ghost rows only seems to grow over time, which means that once the table is broken it seems it's broken definitively until it's unmounted from the DOM.

-----

<img width="1241" alt="Screen Shot 2020-10-29 at 1 38 01 PM" src="https://user-images.githubusercontent.com/1524088/97626098-ffd51e80-19ee-11eb-9b1d-442e19c06335.png">

| Environment | Info |
|---|---|
| antd | 4.6.6 |
| React | 16.13.0 |
| System | macOS Mojave 10.14.6 |
| Browser | Chrome Version 86.0.4240.111 (Official Build) (x86_64) |

**Comment by zwily** [comment]
FWIW, I am having this issue too, but cannot seem to replicate it in a minimal project. Very strange!

**Comment by theGRubio** [comment]
This happens when you give height or some kind of space inside the ant-table-measure-row, it could be de tr itself or the td inside, try somthing like:
.ant-table-measure-row td {
  padding: 0 !important;
  height: 0 !important;
}
.ant-table-measure-row {
  padding: 0 !important;
  height: 0 !important;
}

**Comment by Mobasshir98** [comment]
I have two tables, A and B, and each row requires a unique rowKey for checkbox functionality to work correctly. Table A has a unique identifier called IdA, while table B uses a different key, idB, as its unique rowKey. However, table B also includes an IdA field, which is not unique. In some rows, IdA is set to 0, an empty string, or null.

The issue arises when switching from table B to table A: the rows from table B with an invalid IdA (0, "", or null) are incorrectly showing up in table A, even though table A’s data is fetched fresh from the backend.

Upon inspecting with React DevTools, I noticed that these incorrect rows from table B are still present in the Context.Provider, which might be causing the data bleed between the tables.
