### ISSUE TITLE
Table组件渲染数据时出现第一行空白行

### ISSUE THREAD

**Issue by dyh1995** [ant-design/ant-design#27441]
- [BUG ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-0q4i3?file=/index.js)

### Steps to reproduce
在表格设置了scroll之类会引起滚动的属性后，表格会在第一行之前生成一行tr，类名为ant-table-measure-row。在4.6.5版本后该tr下td元素内部会渲染空格实体符号，导致渲染出来的表格在该行有多余的高度展示出来，显示异常

### What is expected?
期望该行不占据高度，内部不渲染空格实体

### What is actually happening?
内部渲染了空格实体，该行占据16px高度

| Environment | Info |
|---|---|
| antd | 4.6.5 |
| React | 16.13.1 |
| System | mac |
| Browser | chrome 86.0.4240.111 |

**Comment by afc163** [comment]
<img width="729" alt="image" src="https://user-images.githubusercontent.com/507615/97581205-3e8ac900-1a2f-11eb-944c-d78335ec7ffe.png">

没有重现：https://codesandbox.io/s/antd-reproduction-template-forked-t34yu?file=/index.js

**Comment by appleshell** [comment]
我之前遇到过相同现象，我的问题是设置了样式：`tr: { vertical-align: baseline;}`就会出现。但在4.6.5版本之前即便设置了也不会有这个现象。

**Comment by dyh1995** [comment]
> 我之前遇到过相同现象，我的问题是设置了样式：`tr: { vertical-align: baseline;}`就会出现。但在4.6.5版本之前即便设置了也不会有这个现象。

确实是我的项目在css reset的样式里面有tr: { vertical-align: baseline;}，导致了这个问题，4.6.5版本之前设置该样式也不会出现问题是因为我在issue里面描述的那样，"在4.6.5版本后该tr下td元素内部会渲染空格实体符号",而在之前的版本里渲染出来并没有这个空格

**Comment by dyh1995** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-jevdh?file=/index.js

> <img alt="image" width="729" src="https://user-images.githubusercontent.com/507615/97581205-3e8ac900-1a2f-11eb-944c-d78335ec7ffe.png">
> 
> 没有重现：https://codesandbox.io/s/antd-reproduction-template-forked-t34yu?file=/index.js

更新了codesandbox   https://codesandbox.io/s/antd-reproduction-template-forked-jevdh?file=/index.js

**Comment by dyh1995** [comment]
> https://codesandbox.io/s/antd-reproduction-template-forked-jevdh?file=/index.js
> 
> > <img alt="image" width="729" src="https://user-images.githubusercontent.com/507615/97581205-3e8ac900-1a2f-11eb-944c-d78335ec7ffe.png">
> > 没有重现：https://codesandbox.io/s/antd-reproduction-template-forked-t34yu?file=/index.js
> 
> 更新了codesandbox https://codesandbox.io/s/antd-reproduction-template-forked-jevdh?file=/index.js
