### ISSUE TITLE
antd样式配置问题

### ISSUE THREAD

**Issue by focusdroid** [ant-design/ant-design#27445]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/docs/react/use-with-create-react-app-cn](https://ant.design/docs/react/use-with-create-react-app-cn)

### Steps to reproduce
按照文档一步步配置下来提示错误

### What is expected?
配置样式起作用

### What is actually happening?
报错

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17.0.1 |
| System | win10 |
| Browser | chrome86 |

**Comment by Kermit-Xuan** [comment]
具体什么错误呢？给个复现的例子或者仓库，光说这个不能定位问题。
