### ISSUE TITLE
Table 中Popconfirm ，出现弹跳

### ISSUE THREAD

**Issue by xiaofengqqcom123** [ant-design/ant-design#27443]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/kezhankai-ant-design-demo-forked-4wv2w?file=/index.js)

### Steps to reproduce
点击”delete“时，展现Popconfirm时，出现弹跳~
非必现问题，可以分别点击几行的”delete“按钮

### What is expected?
一次性展示Popconfirm

### What is actually happening?
出现弹跳

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16.12.0 |
| System | mac |
| Browser |  谷歌 86.0.4240.75 |

**Comment by afc163** [comment]
> 出现弹跳

不太理解出现弹跳是什么意思。

**Comment by xiaofengqqcom123** [comment]
> > 出现弹跳
> 
> 不太理解出现弹跳是什么意思。

第一次popConfirm出现位置不对，第二次出现位置正确。页面上会有弹跳的效果

**Comment by xiaofengqqcom123** [comment]
> Hello @xiaofengqqcom123. Please provide a online reproduction by forking this link [u.ant.design/codesandbox-repro](https://u.ant.design/codesandbox-repro) or a minimal GitHub repository. Issues labeled by `Need Reproduce` will be closed if no activities in 7 days.
> 
> 你好 @xiaofengqqcom123, 我们需要你提供一个在线的重现实例以便于我们帮你排查问题。你可以通过点击 [此处](https://u.ant.design/codesandbox-repro) 创建一个 codesandbox 或者提供一个最小化的 GitHub 仓库。7 天内未跟进的 issue 将会被自动关闭。
> 
> ![](https://camo.githubusercontent.com/4802e0c22ce5efbfdb0fe587511a3da956885727/68747470733a2f2f67772e616c697061796f626a656374732e636f6d2f7a6f732f616e7466696e63646e2f79396b776737445643642f726570726f647563652e676966)

第一个例子、第二个例子（https://codesandbox.io/s/antd-reproduction-template-forked-e8f16?file=/index.js ）第一次点击第一行的“delete”时，第一次popConfirm出现位置不对，第二次出现位置正确，均会出现弹跳

**Comment by afc163** [comment]
@xiaofengqqcom123 来个 gif 或者录屏吧，我这里没重现弹跳。

**Comment by xiaofengqqcom123** [comment]
[bug 复现.mov.zip](https://github.com/ant-design/ant-design/files/5463848/bug.mov.zip)
不是必现问题，多点几次

**Comment by afc163** [comment]
Duplicate of #27362

**Comment by hyl1374961656** [comment]
所以说解决了么？
