### ISSUE TITLE
Image 组件触发了 fallback 之后， alt 属性无效

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#27459]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/dolov/pen/bGevBmj?editors=0010](https://codepen.io/dolov/pen/bGevBmj?editors=0010)

### Steps to reproduce
https://codepen.io/dolov/pen/bGevBmj?editors=0010

### What is expected?
可以显示 alt 信息

### What is actually happening?
没有显示 alt 信息

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by afc163** [comment]
你给的例子里有 alt。
