### ISSUE TITLE
急需要Select,Checkbox,Radio等这些组件的options的label属性类型改为高阶组件类型

### ISSUE THREAD

**Issue by w602542704** [ant-design/ant-design#27454]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
解决如checkbox的label可以动态组合设定，内容更丰富，如options的label属性可以由文字和下拉选项框或者输入框等等组件组合，这个组合可以事先由我们截取替换好，只需要label属性类型接收改成组件类型的。

### What does the proposed API look like?
interface Option {
  label: any;
  value: string;
  disabled?: boolean;
}
```
Option｛
label:sadsfsd<inputNumber>sdfdfsdf<inputNumber>sdfdfs,
value:1
｝
```

**Comment by w602542704** [comment]
![image](https://user-images.githubusercontent.com/24689873/97655869-0328e280-1aa1-11eb-9679-347c1147e6bc.png)

**Comment by afc163** [comment]
label 现在就支持 ReactNode。

**Comment by w602542704** [comment]
> label 现在就支持 ReactNode。
太棒了
