### ISSUE TITLE
在antd的Modal组件下引入一个经过From包装的组件提交时this.props.form.validateFieldsAndScroll方法无效果

### ISSUE THREAD

**Issue by Fsenxu** [ant-design/ant-design#2745]
#### 本地环境

- antd 版本:"^1.4.1"
- 操作系统及其版本：win7
- 浏览器及其版本:"chrome 46.0.2490.80"

#### 你做了什么？

在antd的Modal组件下引入一个经过From包装的包含多个Input组件的自定义组件

#### 你期待的结果是：

提交时组件的校验正常

#### 实际上的结果：

this.props.form.validateFieldsAndScroll方法不执行

` handleSubmit(){
        this.props.form.validateFieldsAndScroll((errors, values) => {
            console.log('kkkkkk')
            if (!!errors) {
                Modal.error({
                title: '提交失败',
                content: (
                    <div>
                        <p>请填写所有必填项</p>
                        <p>Status: {errors}</p>
                    </div>  )
            });
                return;
              }
        let value = this.props.form.getFieldsValue();
        this.props.onSubmit(value);
        });
    },
render() {
    const { getFieldProps, getFieldError, isFieldValidating } = this.props.form;
const formItemLayout = {
      labelCol: { span: 7 },
      wrapperCol: { span: 12 },
    };
return (
<Form horizontal form={this.props.form}>
<FormItem
          {...formItemLayout}
          label="移动电话"
        >
          <Input {...getFieldProps('phone',{rules: [{'required': true,min: 6,}]})}  />
        </FormItem>
</Form>
    );
  },
});
searchForm = createForm()(searchForm);`

**Comment by afc163** [comment]
无法阅读。。

**Comment by afc163** [comment]
由于维护者能力所限，可能无法准确理解提问的意思，所以烦请提供一个可重现的演示，帮助我们更快的排查到问题。:smile:

http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by Fsenxu** [comment]
已解决！谢谢
