### ISSUE TITLE
React.StrictMode: Form.List's `remove` function makes all form field of the list item `undefined` instead of deleting the list item array element

### ISSUE THREAD

**Issue by arkadiyk** [ant-design/ant-design#27451]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://codepen.io/arkadiyk/pen/abZYNor?editors=0010](https://codepen.io/arkadiyk/pen/abZYNor?editors=0010)

### Steps to reproduce
- Open JS console
- delete one of the items
- press "Submit"

### What is expected?
Item is deleted and onFinish function executed

### What is actually happening?
instead of deleting the line item it assigns `undefined` to all of the fields of the deleted item. 
It triggers validation for the deleted line and proceeds to onFinishFailed function

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17 |
| System | MacOS |
| Browser | Chome latest |

---
It happens only in `React.StrictMode`.

**Comment by artespoon** [comment]
This scenario is also reproduceable on react 16.13.1.
Downgrading antd to version 4.7.2 resolves the problem.

**Comment by afc163** [comment]
Trace https://github.com/ant-design/ant-design/issues/26136 for further progress.
