### ISSUE TITLE
[Button] loading state change between nearby microtasks cause button to spin forever.

### ISSUE THREAD

**Issue by buhichan** [ant-design/ant-design#27457]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/relaxed-gauss-x7oh4?file=/src/App.js)

### Steps to reproduce
Step1: Click on the button in the left
Step2: Notice that the loading state does not change
Step3: Reload Page
Step4: Click on the button in the right
Step5: Notice that the loading state works correctly

### What is expected?
When the left button is clicked, the loading icon should correctly hide itself, since its current loading props has become "false"

### What is actually happening?
It just spins forever

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 17.0.0 |
| System | MacOS |
| Browser | Chrome |

---
This bug does not exist in 4.5.0, if it's not a bug but a feature, then it's a breaking change.

**Comment by buhichan** [comment]
是rc-motion里的useStepQueue的问题, 两个连续的startQueue会造成step永远停在prepare.

**Comment by afc163** [comment]
来个 PR ？

**Comment by buhichan** [comment]
pr: https://github.com/react-component/motion/pull/11
