### ISSUE TITLE
3x 与 4x 部分组件的样式有冲突如何处理

### ISSUE THREAD

**Issue by Dolov** [ant-design/ant-design#27450]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design](https://github.com/ant-design)

### Steps to reproduce
项目中同时引用了 3x 和 4x 的版本，会存在样式的冲突，比如 button 组件在 内容为空的情况下，:empty 伪类的样式就是不一样的，请问这种情况改怎么规避？谢谢

### What is expected?
项目中同时引用了 3x 和 4x 的版本，会存在样式的冲突，比如 button 组件在 内容为空的情况下，:empty 伪类的样式就是不一样的，请问这种情况改怎么规避？谢谢

### What is actually happening?
项目中同时引用了 3x 和 4x 的版本，会存在样式的冲突，比如 button 组件在 内容为空的情况下，:empty 伪类的样式就是不一样的，请问这种情况改怎么规避？谢谢

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | react |
| System | MAC |
| Browser | CHROME |

**Comment by yoyo837** [comment]
不支持同时引用多个版本的antd.

**Comment by gauseen** [comment]
> 不支持同时引用多个版本的antd.

@yoyo837 如果基于 antd4.x 封装了业务组件库并声明依赖，想在H5里使用业务组件库（H5项目里依赖antd3.x 版本），这样可行吗？
