### ISSUE TITLE
Can the default value of optionFilterProp in Select be set to 'children' ?

### ISSUE THREAD

**Issue by appleshell** [ant-design/ant-design#27456]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1. 通常情况用户可能习惯根据下拉框中的显示的内容进行搜索，并不知道其背后的value是什么
2. 在设置options来渲染时，optionFilterProp设置为children无效([demo](https://codesandbox.io/s/antd-select-optionlabelprop-opfkq))，需要设置为label。[#27186](https://github.com/ant-design/ant-design/issues/27186)

### What does the proposed API look like?
1. optionFilterProp默认值是children
2. 设置options时，optionFilterProp值为label。

**Comment by afc163** [comment]
It would be a breaking change, we won't change it.

**Comment by appleshell** [comment]
can i make a pr to update doc that user should set optionFilterProp to `label` when set options?

**Comment by afc163** [comment]
Sure. ❤️
