### ISSUE TITLE
各位大牛，请教下Input控件的搜索框的firefox的兼容性问题

### ISSUE THREAD

**Issue by yuan1995913** [ant-design/ant-design#2746]
使用antd的搜索框，代码是完全复制demo的 
在firefox下只有一个放大镜的icon，然后设置margin－left吧搜索框顶出来，
在chrome下输入框会超出放大镜的icon

antd为1.8
firefox和chrome均为官方最新的稳定版

**Comment by afc163** [comment]
给重现。。。

**Comment by yuan1995913** [comment]
@afc163 您好

这是在firefox下  只有放大镜的icon
![2](https://cloud.githubusercontent.com/assets/16458252/17726551/5fa382ac-6486-11e6-970c-46ef1f999f6a.png)

chrome下 是正常的  
这个是没有加任何样式的。。

**Comment by afc163** [comment]
为何这里看着是好的呢？http://ant.design/components/input/#components-input-demo-search-input

尽量给重现吧，不然难以解决 http://codepen.io/anon/pen/wGOWGW?editors=001

**Comment by yuan1995913** [comment]
@afc163 
请问一下，我的代码中并没有引用这个less文件 是不是这个原因呢？ https://github.com/ant-design/ant-design/blob/master/components/input/style/search-input.less

**Comment by afc163** [comment]
我觉得是。

**Comment by yuan1995913** [comment]
@afc163 好的 谢谢您 我在试试
