### ISSUE TITLE
Tree树形控件展开折叠时，会导致节点内文字变为选中状态

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27471]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/tree-cn/#components-tree-demo-line](https://ant.design/components/tree-cn/#components-tree-demo-line)

### Steps to reproduce
点击展开折叠按钮进行切换

### What is expected?
切换时节点文字不被选中
[![BtxMUf.gif](https://s1.ax1x.com/2020/10/30/BtxMUf.gif)](https://imgchr.com/i/BtxMUf)

### What is actually happening?
切换时节点文字被选中了
[![BtxSD1.gif](https://s1.ax1x.com/2020/10/30/BtxSD1.gif)](https://imgchr.com/i/BtxSD1)

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | react@16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

---
拖动示例是符合期望的

**Comment by yoyo837** [comment]
单击不会，双击会

**Comment by afc163** [comment]
要加一个 `use-select: none`。
