### ISSUE TITLE
Expanded Table doesnt have props for thead title and its empty , Or I want Make a Custom button and use a function to expand table without use default expand table props

### ISSUE THREAD

**Issue by pooooriya** [ant-design/ant-design#27475]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/issues/11246](https://github.com/ant-design/ant-design/issues/11246)

### Steps to reproduce
I want to add a column that has rendered a button that when i want click this button its render a box as a expandedrowrender functions or add a thead title for expand icons to explain what this icon do for example i want a show my music lyrics when this icon clicked but I have to  set thead body to "lyrics" but antd thead title for expanded icons is empty and cant set anything to it so you can add props to for example 'setExpand()" to set it true or false any where by any buttons or add a thead title for epanded icon to help others know what tish buttons do !!

### What is expected?
t so you can add props to for example 'setExpand()" to set it true or false any where by any buttons or add a thead title for epanded icon to help others know what tish buttons do !!

### What is actually happening?
thead title in expanded icon is empty and cant set it by a props or we dont have any function to set it true and hide default expanded icon

| Environment | Info |
|---|---|
| antd | 4.6.4 |
| React | 16.13.1 |
| System | ubonto 20.04 |
| Browser | Version 86.0.4240.111 (Official Build) (64-bit) |

**Comment by afc163** [comment]
You should use `expandKeys` to control expand state and `expandIconColumnIndex={-1}` to hide default expand icon column.

**Comment by pooooriya** [comment]
i don know how can i use expandKeys  and its isnt in documantion is it new?

**Comment by pooooriya** [comment]
can you tell me a sample of use expandKeys  ?

**Comment by pooooriya** [comment]
do you mean expandedRowKeys?

**Comment by afc163** [comment]
Yeah, `expandedRowKeys`.

https://stackoverflow.com/questions/47977632/how-to-expand-antd-table-row-by-click-a-button/48081222#48081222

**Comment by pooooriya** [comment]
`   <Col lg={20} xs={24}>
        <Table
          dataSource={dataSource}
          columns={columns}
          pagination={false}
          expandedRowKeys={[1, 2]}
          expandIconColumnIndex={1}
          expandable={{
            expandedRowRender: (record) => (
              <p style={{ margin: 0 }}>{record.lyrics}</p>
            ),
            rowExpandable: (record) => record.name !== 'Not Expandable',
          }}
        />
      </Col>`

I used this for my code but it doesnt work and when i remove expandedRowKeys it works !!
