### ISSUE TITLE
How to type SelectRef after upgrading to 4.7

### ISSUE THREAD

**Issue by icaroponce** [ant-design/ant-design#27474]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/determined-heisenberg-gfr3x?file=/src/App.tsx)

### Steps to reproduce
Running the code (as in the sandbox) with version 4.6.6 worked just fine. After upgrading to v4.7.3 I can't properly type a ref for the Select component.
TS complains: `2749: 'Select' refers to a value, but is being used as a type here. Did you mean 'typeof Select'? `

### What is expected?
A way to type a ref to Select

### What is actually happening?
With the actual exported interfaces couldn't properly type a ref to a Select component. The way used in the sandbox code example worked just fine in versions 4.6*

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13 |
| System | Archlinux 5.5.13-arch1-1 |
| Browser | Chromium Version 80.0.3987.149 |

**Comment by hengkx** [comment]
https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L54

Please use RCSelect<Value>

**Comment by afc163** [comment]
用户不应该再去引用 rc-select 的。

**Comment by hengkx** [comment]
@zombieJ 我看 RCSelect那边的 ref 最终 是指向了 input ，我准备 吧这边的 改成 input  ，RCSelect导出的 ref 类型要改吗？

**Comment by icaroponce** [comment]
> https://github.com/ant-design/ant-design/blob/master/components/select/index.tsx#L54
> 
> Please use RCSelect

@hengkx Thanks for the reply, but I'd prefer not have to install `rc-select` as a direct dependency to my project only for this reason when it's already a dependency for antd.
