### ISSUE TITLE
Antd Select icon is unclickable if 'suffixIcon' prop is passed

### ISSUE THREAD

**Issue by siwalikm** [ant-design/ant-design#27479]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-select-suffixicon-bug-zum3c?file=/index.js)

### Steps to reproduce
Try clicking on the custom icon in the Select element. Notice dropdown doesn't open.

### What is expected?
Expected the dropdown to react (open/close) when custom icon is clicked

### What is actually happening?
Select dropdown doesn't open when icon is clicked

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.1 |
| System | macos v10.15.7 |
| Browser | Chrome |

**Comment by siwalikm** [comment]
Quick workaround is adding some custom css like
```css
.ant-select-arrow .anticon:not(.ant-select-suffix) {
    pointer-events: none;
}
```
But ideally this should be the out-of-the-box behaviour.

I can raise a PR for this if any mods can confirm the bug needs fixing.

**Comment by afc163** [comment]
See https://github.com/ant-design/ant-design/issues/23263
