### ISSUE TITLE
tree组件节点的disabled属性会影响到节点的展开状态

### ISSUE THREAD

**Issue by luanki** [ant-design/ant-design#27478]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/shoukongcaozuoshili-ant-design-demo-forked-cj0kh?file=/index.js)

### Steps to reproduce
见链接

### What is expected?
treeNode节点的展开状态与disabled有关系（是一种什么样的关系？）或者没有关系（disabled不影响该节点的展开收起）

### What is actually happening?
treeNode节点在disabled状态下，但是会由于expandedKeys的不同，该节点的展开状态不同（有时是展开的，有时是收起的）

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.12.0 |
| System | win10 |
| Browser | chrome 86.0.4240.111（正式版本） （64 位） |

**Comment by afc163** [comment]
> disabled不影响该节点的展开收起

应该没关系，来个 PR 吧。

**Comment by luanki** [comment]
> > disabled不影响该节点的展开收起
> 
> 应该没关系，来个 PR 吧。

@afc163 确实没有关系（不会影响该节点）,但有另外一个问题，不知道当初设计是否是这样子的：
>子节点的disabled属性会影响父级（祖先，递归的一整条线）节点的展开收起状态，在树的一条分支下仅有一个展开的节点且该节点是disabled的条件下，现象更明显

示例：<https://codesandbox.io/s/shoukongcaozuoshili-ant-design-demo-forked-24oiw?file=/index.js>

**Comment by appleshell** [comment]
disabled是有影响的[#L308](https://github.com/react-component/tree/blob/master/src/util.tsx#L308)，影响递归对当前节点的父节点的展开处理。

**Comment by appleshell** [comment]
[#L159](https://github.com/react-component/tree/blob/master/tests/Tree.spec.js#L159)说明是不展开disabled节点的父节点，感觉有点矛盾了，应该遵循哪种设计？@afc163

**Comment by zombieJ** [comment]
不是 bug，规则其实就是 `disabled` 节点不参与传导。你直接把 `expandedKeys` 改成一个 `disabled` 的和一个同级但是不 `disabled` 就明白了：

https://codesandbox.io/s/shoukongcaozuoshili-ant-design-demo-forked-gig6n?file=/index.js

**Comment by zombieJ** [comment]
> > disabled不影响该节点的展开收起
> 
> 应该没关系，来个 PR 吧。

它影响传导计算，但是 `disabled` 节点本身的 `expanded` 是按照给予的 key 来的。

**Comment by zombieJ** [comment]
文档里需要写一下，这也算是年经贴了。
