### ISSUE TITLE
setting expandedKeys in Tree component does not work

### ISSUE THREAD

**Issue by farshad-abb** [ant-design/ant-design#27486]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-7uhk5)

### Steps to reproduce
click the expand button

### What is expected?
we expect that parent 1-0 get expanded

### What is actually happening?
it is not expanded and after clicking "click to expand" button when you click to expand another treeNode, the "parent 1-0" gets expanded!!!

| Environment | Info |
|---|---|
| antd | 4.7.0 |
| React | React |
| System | windows |
| Browser | Chrome |

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-igjjj?file=/index.js:1471-1518

```diff
        onClick={() => {
-         let newExpanded = expandedKeys;
+         let newExpanded = [...expandedKeys];
          if (expandedKeys.indexOf("0-0-0") === -1) newExpanded.push("0-0-0");
          setExpandedKeys(newExpanded);
          console.log(expandedKeys);
        }}
```
