### ISSUE TITLE
...getColumnSearchProps is not taking nested objects

### ISSUE THREAD

**Issue by codenamics** [ant-design/ant-design#27481]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/table/#components-table-demo-head](https://ant.design/components/table/#components-table-demo-head)

### Steps to reproduce
 {
        title: 'Name',
        dataIndex: ["data", "name"],
        key: ["data", "name"]',
        ...this.getColumnSearchProps(["data", "name"]), // error when searching
      },

### What is expected?
Able to pass nested objects to getColumnSearchProps()

### What is actually happening?
cannot search using getColumnSearchProps() with nested object passed

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | latest |
| System | Windows |
| Browser | Chrome |

**Comment by codenamics** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-koztw?file=/index.js

**Comment by afc163** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-xgvhp?file=/index.js
