### ISSUE TITLE
formItem的label为ReactNode时，umi构建后校验不通过控制台async-validator输出Please enter undefined

### ISSUE THREAD

**Issue by RealWseven** [ant-design/ant-design#27494]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/RealWseven/formItemIssue/blob/main/src/pages/FormItem/index.tsx](https://github.com/RealWseven/formItemIssue/blob/main/src/pages/FormItem/index.tsx)

### Steps to reproduce
代码如下：
<Form.Item
        label={<span>22333</span>}
        name="username"
        rules={[
          {
            required: true,
            message: 'Please input your username!',
          },
        ]}
      >
        <Input />
</Form.Item>，
umi构建项目之后运行，不输入值，直接点击提交

### What is expected?
控制台async-validato输出please enter 22333

### What is actually happening?
控制台async-validato输出please enter undefine

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.1 |
| System | windows10 |
| Browser | chrome86.0.4240.111 |

**Comment by zombieJ** [comment]
`async-validate` 错误信息指的是你没有满足 `required` 规则，当前值是 `undefined`。和 `label` 没有关系。

**Comment by haishancheng** [comment]
messageVariables
