### ISSUE TITLE
Select多选情况下，能否删除已选的但已disabled 的option

### ISSUE THREAD

**Issue by asevenm** [ant-design/ant-design#27495]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
业务场景：在有自增列表的form表单中，列表中，不同的项要限制用户选取相同的select option，所以会记录已选择的所有option，并使其disabled，但是这个时候，已选择的项又不能进行删除操作了

### What does the proposed API look like?
select 添加相应属性支持

**Comment by yoyo837** [comment]
受控模式就好了吧？

**Comment by afc163** [comment]
> 所以会记录已选择的所有option，并使其disabled

建议已选择的 option 不要用 disabled 的方式标记，而是用 `selected ✅` 或者`直接隐藏`的方式标记使其不可再次选择。

**Comment by asevenm** [comment]
> > 所以会记录已选择的所有option，并使其disabled
> 
> 建议已选择的 option 不要用 disabled 的方式标记，而是用 `selected ✅` 或者`直接隐藏`的方式标记使其不可再次选择。

好的，谢谢
