### ISSUE TITLE
<Steps /> small size breaks on mobile 

### ISSUE THREAD

**Issue by amed** [ant-design/ant-design#27498]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lnu4w?file=/index.js)

### Steps to reproduce
Reduce window size until the mobile version is being shown.

### What is expected?
The step should be visible vertically in one line

### What is actually happening?
Selected item is shifted out of the vertical line

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.13.1 |
| System |  macOS |
| Browser | Chrome |

![Screenshot 2020-11-02 at 08 54 54](https://user-images.githubusercontent.com/5637272/97845994-a40bdd80-1ced-11eb-9458-546f8442d85b.png)

**Comment by yoyo837** [comment]
@07akioni Broken by #25839 after v4.5.0.
