### ISSUE TITLE
希望table组件的onRow-onClick与列的Action点击事件不会同时触发

### ISSUE THREAD

**Issue by XiaoColl** [ant-design/ant-design#27492]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
即想有操作区的Action，同时也能有OnRow的点击行功能，很多场景是操作区与点击行事件并存的需求。目前会触发多次。

### What does the proposed API look like?
提供一个API，可以拦截事件的传递，列的action优先。

**Comment by afc163** [comment]
阻止冒泡 `onClick={e => e.stropPropagation()}`

**Comment by XiaoColl** [comment]
> 阻止冒泡 `onClick={e => e.stropPropagation()}`

并不能阻止

**Comment by yoyo837** [comment]
请查看一下是否React 合成事件有关导致不能阻止。

**Comment by afc163** [comment]
实测可以：https://codesandbox.io/s/kezhankai-ant-design-demo-forked-6sx4e?file=/index.js

**Comment by a798032825** [comment]
> 实测可以：https://codesandbox.io/s/kezhankai-ant-design-demo-forked-6sx4e?file=/index.js

你好，想请教下，你这样确实可以对遇到的单个按钮事件做冒泡处理，我这边想封装处理组件，避开在引用组件时每次按钮都要去加冒泡，应该如何去改会可行？
