### ISSUE TITLE
希望transfer的render可以支持渲染整行, 包括checkbox

### ISSUE THREAD

**Issue by 4-1-1** [ant-design/ant-design#27506]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
因为我想做拖拽排序, 或者内置一个拖拽排序也可以

### What does the proposed API look like?
```js 
render = (node, includeCheckBox=false)=>{}
```

**Comment by afc163** [comment]
看看这个例子：https://ant.design/components/transfer-cn/#components-transfer-demo-table-transfer 里面完全换掉了。
