### ISSUE TITLE
Form.Item, normalize, replace whitespace with empty string, the cursor will jump to the end of the input

### ISSUE THREAD

**Issue by acfasj** [ant-design/ant-design#27504]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/clever-glitter-wngg2?file=/src/App.tsx)

### Steps to reproduce
Enter whitespace in the middle of string, the cursor will jump to the end of the input

### What is expected?
keep the cursor position as it is

### What is actually happening?
the cursor jump to the end of the input

| Environment | Info |
|---|---|
| antd | 4.7.3 |
| React | 16.8/17 |
| System | macOS 10.14.6 |
| Browser | chrome  86.0.4240.111 |

---
It may related to https://github.com/facebook/react/issues/955 ,  since this issue is old, it may be antd's bug

**Comment by afc163** [comment]
It is not antd bug, check this controlled input: https://codesandbox.io/s/strange-tree-exkly?file=/src/App.tsx

**Comment by acfasj** [comment]
> It is not antd bug, check this controlled input: https://codesandbox.io/s/strange-tree-exkly?file=/src/App.tsx

thx, I should try native react controlled input before submit the issue
