### ISSUE TITLE
insert-css violates the Content Security Policy (CSP) Directives.

### ISSUE THREAD

**Issue by ifen** [ant-design/ant-design#27508]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://www.npmjs.com/package/inline-css](https://www.npmjs.com/package/inline-css)

### Steps to reproduce
This library is causing my CSP to fail. Is there anything that can be done?

### What is expected?
CSP to not fail.

### What is actually happening?
This library is causing my CSP to fail with the error "Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash...."

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.14.0 |
| System | All |
| Browser | Chrome |

**Comment by afc163** [comment]
https://ant.design/components/config-provider/#Content-Security-Policy

**Comment by IgorSelin** [comment]
I still have issues when I use Table from antd? any ideas?
