### ISSUE TITLE
表单里input的内容长度校验是否没考虑到首尾包含空格的情况？

### ISSUE THREAD

**Issue by mervynchung** [ant-design/ant-design#2750]
#### 本地环境

- antd 版本:
1.4.5

#### 你做了什么？
例如表单里的input使用如下规则，
```
const usernameProps = getFieldProps('username', {
            rules: [
                {required: true, min: 5, whitespace: true, message: '用户名至少5个字符'}
            ]
        });
```

#### 你期待的结果是：

输入 '&nbsp;&nbsp;&nbsp;ab'，字符实际只有两个，理应校验失败

#### 实际上的结果：

实际上把空格也算作字符，长度校验通过了

目前还是停留在antd 1.4.x版本，希望后续版本的长度校验能先为输入值做个trim()吧。谢谢

**Comment by benjycui** [comment]
HTML 的 `maxLength` 也不会忽略空格 http://www.w3school.com.cn/tiy/t.asp?f=html_input_maxlength

空格的语义由业务决定，所以这里你还是用自定义规则吧。
