### ISSUE TITLE
PageHeader footer 当页面过长导航需要在滚动范围内始终展现

### ISSUE THREAD

**Issue by Lcj-space** [ant-design/ant-design#27518]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
页面过长时，减少不必要的操作

### What does the proposed API look like?
可以传入一个 isAffix 为true 即可

**Comment by afc163** [comment]
Try wrap PageHeader with https://ant.design/components/affix-cn

**Comment by Lcj-space** [comment]
> Try wrap PageHeader with https://ant.design/components/affix-cn
有问题的，用完后下面部分出现滚动问题

**Comment by afc163** [comment]
来个重现：https://u.ant.design/codesandbox-repro

**Comment by effapp** [comment]
“Try wrap PageHeader with https://ant.design/components/affix-cn”这个办法确实不行，它把PageHeader包裹的内容也固定住了。
