### ISSUE TITLE
AntD表单校验时，中文输入法，如果校验规则规定了只能输入中文/英文/数字时，实时输入容易触发报错

### ISSUE THREAD

**Issue by wljray** [ant-design/ant-design#27516]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://blog.csdn.net/handsomexiaominge/article/details/80977402](https://blog.csdn.net/handsomexiaominge/article/details/80977402)

### Steps to reproduce
中文输入法时，假设期望输入 「中文输入问题」，因为中文非直接输入法，会有pinyin（字母）「zhong'wen'shu'ru'wen'ti」过渡到汉字的过程。

部分输入法用'断字，部分用空格，但这些中间过程的输入结果，会导致输入框的实时输入校验规则运行错误，需要增加修正逻辑。
![image](https://user-images.githubusercontent.com/1441944/97954706-3c35bf80-1ddf-11eb-9f9d-d890182d932e.png)

修正逻辑参考：
https://blog.csdn.net/handsomexiaominge/article/details/80977402

### What is expected?
https://blog.csdn.net/handsomexiaominge/article/details/80977402

中文输入法输入过程，未打出汉字时，不触发校验

### What is actually happening?
https://blog.csdn.net/handsomexiaominge/article/details/80977402

| Environment | Info |
|---|---|
| antd | undefined |
| React | 所有版本 |
| System | 所有版本 |
| Browser | 所有版本 |

**Comment by steveleeh** [comment]
虽然严格意义上这不属于antd的问题，但是如果能加个字段决定是否用来处理（中文、韩文）这种语言的场景就好了，现在解决方案也是中间写一层来做，但是涉及到的组件挺多的，如果能统一处理就好了。

**Comment by zombieJ** [comment]
Form.Item 是不管子组件是什么类型的，如果需要最后输入完毕再触发校验可以将 `validateTrigger` 设置成 `onBlur` 和 `onCompositionEnd`
