### ISSUE TITLE
Upload Component: disable upload and disable remove should be configured separately

### ISSUE THREAD

**Issue by shenyinabcd** [ant-design/ant-design#27519]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
There isn't a way to make the Upload Component that remove is enabled while upload is disabled.

Currently when Upload component is disabled, both upload and remove are disabled.

A requirement for example: one entity can hold only 5 files . If exceeds 5 files, no more files can be uploaded, but the previous files could be removed. Current situation is, in order to disable upload function, Upload should be set disabled. But when Upload is set to disabled, both upload and remove are disabled.

Why current Upload act like this. See another opposite requirement from issue history: want upload and remove are both disabled, when Upload Component is disabled. See https://github.com/ant-design/ant-design/issues/8677

Upload and remove should be controlled separately.

### What does the proposed API look like?
idea 1:
When disabled is set, should **able** to remove file. The usages are:
disable upload and enable remove, use `<Upload disabled>`
disable both upload and remove, use `<Upload disabled showUploadList={{ showRemoveIcon: false }} />`

or idea 2:
`<Upload disableUpload={true} disableRemove={false}>`

**Comment by shenyinabcd** [comment]
If change as idea 1, this is a bug fix.
If change as idea 2, this is a new feature.

**Comment by akochemasov** [comment]
How to solved this problem?
