### ISSUE TITLE
如何通过原生JS修改Form值

### ISSUE THREAD

**Issue by FourLeafClover** [ant-design/ant-design#27522]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们希望浏览器注入原生JS脚本去实现Form自动填写数据。主要用于开发测试的时候大量的form数据，不需要每次手动输入。

### What does the proposed API look like?
对于Antd Form, 我通过document.querySelector找到form-item下的原生input后。设置了value值。并通过element.dispatchEvent(new Event('change'))去触发input的onchange事件。UI上Form数据已经变化。但是当点击Form提交按钮的时候。发现input的值实际上没有赋值上去。请问可以通过什么方式实现。【PS: antd design vue就可以寻找dom在dispatchEvent(new event('input'))实现】

**Comment by afc163** [comment]
不要用原生 dom 操作，在 React 应用尽量用 React 的思路解决问题。

**Comment by zhoukai12** [comment]
请问这个有解决方案么 我也是和楼主同样的问题

**Comment by Gan-Xing** [comment]
function setReactInputValue(element, value) {
  const nativeInputValueSetter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
  nativeInputValueSetter.call(element, value);

  element.dispatchEvent(new Event('input', { bubbles: true }));
}

// 获取输入元素
const inputEmail = document.getElementById("email");
const inputPassword = document.getElementById("password");

// 设置输入元素的值
setReactInputValue(inputEmail, '输入的邮箱');
setReactInputValue(inputPassword, '输入的密码');

// 使用 XPath 获取提交按钮
const buttonXPath = '/html/body/div/div/div[2]/div/div[2]/form/button';
const submitButton = document.evaluate(buttonXPath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;

// 提交表单
submitButton.click();

这种方法可以处理。
