### ISSUE TITLE
统一修改Select suffixIcon属性？

### ISSUE THREAD

**Issue by wufeng87** [ant-design/ant-design#27520]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
我们现在没在antd Select基础上封装一层，现在有200个文件调用了Select，想统一修改suffixIcon ，有啥简便的方法可以做到吗？谢谢。

`<Select suffixIcon={do`wnIcon}`

### What does the proposed API look like?
全局配置接口？

版本信息：   "antd": "3.26.14",

**Comment by yoyo837** [comment]
包一层，修改import  , 代码不变

**Comment by wufeng87** [comment]
很的 谢谢

**Comment by sjkmuninj** [comment]
我这样解决了,不知道你那边适合不适合
在mian入口文件里面
```
import {Select} from "ant-design-vue";
Select.props.suffixIcon={
	default(){
		return this.$createElement(
			"div",
			{attrs: {class: "anticon"}},
			[this.$createElement("i", {
				attrs: {class: "iconfont icon-arrowDown"}}
			)]
		);
	}
};
```

**Comment by dongcer** [comment]
> 包一层Select默认一个suffixIcon，支持覆盖，修改使用Select的地方的import，改为这个组件，import后也叫Select , 其他代码不变

但是像分页那个select就没办法了
