### ISSUE TITLE
antd tree组件展开和折叠时的图标自定义

### ISSUE THREAD

**Issue by xiaohui-gsv** [ant-design/ant-design#27528]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
树的展开和折叠图标，目前只有一个switcherIcon api来设置，只能设置一个，这样我想实现折叠时显示加号，展开时显示减号就实现不了

### What does the proposed API look like?
提供两个api，一个设置展开时的图标，一个设置折叠时的图标，类似meterial的tree组件有defaultCollapseIcon和defaultExpandIcon

**Comment by afc163** [comment]
Duplicate of #25632

**Comment by pxim** [comment]
现在 switcherIcon  有bug，和 链接的这个 25632没啥关系

**Comment by SuperEffort** [comment]
请问有解决方案了吗？
