### ISSUE TITLE
Search组件中input和button在某些缩放比例下高度不一致

### ISSUE THREAD

**Issue by AlanCutFlim** [ant-design/ant-design#27539]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-cn/#components-input-demo-search-input](https://ant.design/components/input-cn/#components-input-demo-search-input)

### Steps to reproduce
对游览器进行缩放（图中是125%缩放），使用devtool查看两个元素的高度

### What is expected?
input和button高度一致

### What is actually happening?
input和button高度不一致
[![BceC5j.png](https://s1.ax1x.com/2020/11/04/BceC5j.png)](https://imgchr.com/i/BceC5j)

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.14.0 |
| System | macOS Catalina 10.15.4 |
| Browser | Chrome 86.0.4240.111 |

**Comment by afc163** [comment]
抱歉，目前没有好办法去完美匹配每一个放大缩小百分比的高度问题。
