### ISSUE TITLE
Avatar group size

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#27530]
### Reproduction link
[https://ant.design/components/avatar-cn/#components-avatar-demo-group](https://ant.design/components/avatar-cn/#components-avatar-demo-group)

| Environment | Info |
|---|---|
| antd | 4.8.0 |

- https://github.com/ant-design/ant-design/pull/27348

嵌套 Tooltip 的 Avatar size 没有生效，观察第三个。

**Comment by hengkx** [comment]
奇怪 怎么 会有 一个 size没生效

**Comment by hengkx** [comment]
。。。。。。。。。。。。。 为什么 多了个 tooltip

**Comment by hengkx** [comment]
要支持这种吗

**Comment by xrkffgg** [comment]
例子都给出来了，起码要支持啊 😂

**Comment by zombieJ** [comment]
https://github.com/ant-design/ant-design/blob/73c4566c616ec67f2466002108f3422d3e571e13/components/avatar/group.tsx#L39

这个应该用 Context，不应该直接改 Props

**Comment by hengkx** [comment]
ok 我改一下
