### ISSUE TITLE
Modal.prompt required

### ISSUE THREAD

**Issue by bowencool** [ant-design/ant-design#27537]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
代替window.prompt

### What does the proposed API look like?
const text = await Modal.prompt({
  ...
});

**Comment by afc163** [comment]
see https://github.com/ant-design/ant-design/issues/27399#issuecomment-717144167

**Comment by webLiang** [comment]
看来还是没有啊 哈哈
