### ISSUE TITLE
form表单eslint报错

### ISSUE THREAD

**Issue by zzfn** [ant-design/ant-design#27534]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/form-cn/](https://ant.design/components/form-cn/)

### Steps to reproduce
官网demo直接粘贴，eslint提示 Element Form.Item doesn't have required attribute fieldContex

### What is expected?
fieldContext: InternalFormInstance 类型定义是不是忘记加？

### What is actually happening?
eslint 报错

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.14.0 |
| System | macos10.15.6 |
| Browser |  chrome86.0.4240.111 |

**Comment by yoyo837** [comment]
哪一个demo？

**Comment by zzfn** [comment]
> 哪一个demo？
第一个
```
 <Form
      {...layout}
      name="basic"
      initialValues={{ remember: true }}
      onFinish={onFinish}
      onFinishFailed={onFinishFailed}
    >
      <Form.Item
        label="Username"
        name="username"
        rules={[{ required: true, message: 'Please input your username!' }]}
      >
        <Input />
      </Form.Item>

      <Form.Item
        label="Password"
        name="password"
        rules={[{ required: true, message: 'Please input your password!' }]}
      >
        <Input.Password />
      </Form.Item>

      <Form.Item {...tailLayout} name="remember" valuePropName="checked">
        <Checkbox>Remember me</Checkbox>
      </Form.Item>

      <Form.Item {...tailLayout}>
        <Button type="primary" htmlType="submit">
          Submit
        </Button>
      </Form.Item>
    </Form>
```
![1604459999675qcTJ2C](https://cdn.zzfzzf.com//1604459999675qcTJ2C.png)

**Comment by yoyo837** [comment]
来个ts复现？

**Comment by zzfn** [comment]
> 来个ts复现？

https://github.com/zzfn/antd-demo-ts.git
cra创建，引入ant
用webstorm打开 index.tsx 会发现标黄色warning

**Comment by yoyo837** [comment]
vscode无法重现，虽然我没有用webstorm来看，但个人觉得，代码里并没有给`Form.Item`赋予`required`属性，理论上不应该报这个错误。

**Comment by zzfn** [comment]
是不是`    fieldContext: InternalFormInstance;`没加问号`    fieldContext?: InternalFormInstance;`就是必填呀

> vscode无法重现，虽然我没有用webstorm来看，但个人觉得，代码里并没有给`Form.Item`赋予`required`属性，理论上不应该报这个错误。

**Comment by afc163** [comment]
看上去更像是 webstorm 配置的问题。

**Comment by Clago** [comment]
我webstorm更新后也这样，很神奇，但是代码里明明已经omit忽略了。应该是ide问题
export interface FieldProps<Values = any> extends Omit<InternalFieldProps<Values>, 'name' | 'fieldContext'> {
    name?: NamePath;
}

**Comment by rxliuli** [comment]
这应该是一个类型定义错误，具体来源于
https://github.com/react-component/field-form/blob/12e8f5b6a57d3fbc522af803b04ac41165522d15/src/Field.tsx#L85
可能需要在 antd 层面进行屏蔽

**Comment by MarcusHong** [comment]
it fixed on rc-field-form@1.14.0

**Comment by mqliutie** [comment]
所以现在最新版的antd可以了嘛, 还是要自己单独升rc-field-form包?

**Comment by mqliutie** [comment]
> 这应该是一个类型定义错误，具体来源于
> https://github.com/react-component/field-form/blob/12e8f5b6a57d3fbc522af803b04ac41165522d15/src/Field.tsx#L85
> 可能需要在 antd 层面进行屏蔽

可是看类型中已经Omit了, 这个属于编辑器自己识别问题么?  升级到4.8.6确实没有warning了

**Comment by rxliuli** [comment]
> > 这应该是一个类型定义错误，具体来源于
> > https://github.com/react-component/field-form/blob/12e8f5b6a57d3fbc522af803b04ac41165522d15/src/Field.tsx#L85
> > 可能需要在 antd 层面进行屏蔽
> 
> 可是看类型中已经 Omit 了，这个属于编辑器自己识别问题么？升级到 4.8.6 确实没有 warning 了

并不是，可能 v4.8.6 引用了新版本的 rc-field-form，而新版的 rc-field-form 将这个类型定义错误修复了（其实就是 antd 的开发成员修复的）
