### ISSUE TITLE
remove .reset-component

### ISSUE THREAD

**Issue by xrkffgg** [ant-design/ant-design#27542]
### Background

目前多个组件样式引入 .reset-component，造成样式重写了多份。

- https://github.com/ant-design/ant-design/issues/9363#issuecomment-708375579

### Ref

- https://github.com/ant-design/ant-design/issues/9363#issuecomment-444905848
- https://github.com/ant-design/ant-design/issues/4331#issuecomment-423691027

**Comment by xrkffgg** [comment]
https://github.com/ant-design/ant-design/pull/27527#issuecomment-721534335

**Comment by zombieJ** [comment]
是不是应该用 webpack 插件来处理？把和默认相同的样式直接移除掉。`.reset-component` 就是为了拉齐样式，基本都是遇到漏的就会加进去。移除了反而会变成每个组件都需要独自配置。

**Comment by zombieJ** [comment]
暂时先关了，以后找到对应插件再搞一下。
