### ISSUE TITLE
modal宽度问题

### ISSUE THREAD

**Issue by sunzd116** [ant-design/ant-design#2754]
#### 本地环境

- antd 版本:1.7.0
- 操作系统及其版本：ubuntu16.04
- 浏览器及其版本:chrome 52.0.2743.116 (64-bit)

#### 你做了什么？

引入antd 的modal，在Modal中设置```style={{ width: 800px ]}```但是实际显示的宽度为520px

打开控制台选中该元素其样式为
```
element.style {
    width: 520px;
    transform-origin: 486.5px 53px 0px;
    top: 100px;
}
```
可以看出在modal中定义的width无效，但是在modal中设置style的其他属性比如```top:{300px}```，却有效

**Comment by sunzd116** [comment]
我找到解决办法了 要在```ant-modal-content```中设置```width```，并且设置```margin-left```使它居中。但要是在modal中设置```style```的```width```属性就更方便了

**Comment by afc163** [comment]
有 width 属性。。。

**Comment by sunzd116** [comment]
我的意思是```<Modal style={{ width:800 }} />``` 无效，要去css中写啊 @afc163

**Comment by afc163** [comment]
`<Modal width={800} />`

...

**Comment by zlh314159** [comment]
弹框怎么去设置最大width和最小width，而不是设置width为一个固定值。我的场景是弹框里面的图片如果是小图就小屏显示，大图就大屏显示，谢谢
