### ISSUE TITLE
远程加载options的Cascader默认值及与FormItem协同关系

### ISSUE THREAD

**Issue by Augustzyh** [ant-design/ant-design#27541]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
1、Cascader 通过每一步的点击（loadData）来实时获取下一个目录的选项，但设置默认值的时候并不能回显；
2、使用FormItem包裹的上述Cascader组件，设置initialVal的时候同样不能完全回显；
3、FormItem包裹的上述Cascader组件，Cascader组件onChange事件失效，拿不到返回值，只能通过form整体的Change监听到改变
4、前三者存在的情况下通过直接在被FormItem包裹的Cascader中使用defautValue，报警告Warning: [antd: Form.Item] `defaultValue` will not work on controlled Field. You should use `initialValues` of Form instead.但是设置initialVal也不起作用，设置intialVal解析到子组件内只能取到一个状态value，并不利于回显和再次选择的管控

### What does the proposed API look like?
1、远程通过loadData加载options的Cascader组件设置默认值时希望自动执行loadData来达到回显目的；
2、修复被FormItem包裹的Cascader组件onChange函数失效问题；
3、FormItem包裹的上述Cascader组件，设置initialVal时可以达到和1、一样的目的

**Comment by afc163** [comment]
> 1、远程通过loadData加载options的Cascader组件设置默认值时希望自动执行loadData来达到回显目的；
> 3、FormItem包裹的上述Cascader组件，设置initialVal时可以达到和1、一样的目的

应该使用 setFieldValue 来设置异步加载的数据。

>  2、修复被FormItem包裹的Cascader组件onChange函数失效问题；

bug report 请提供重现：https://u.ant.design/codesandbox-repro

**Comment by Augustzyh** [comment]
https://codesandbox.io/s/antd-reproduction-template-forked-4fm40 
没有open的级联api，请求需要修改一下，只写了个demo，加了注释，个人本地能够运行

**Comment by afc163** [comment]
你给的例子右侧是空白的。

**Comment by Augustzyh** [comment]
这个盒子在哪改配置能支持tsx。。。不支持tsx空白了

**Comment by yoyo837** [comment]
如果不是类型问题，可以直接写js

**Comment by Augustzyh** [comment]
那就不好改了，其实这个问题看代码想一下应该也能给出解释吧，
简化远程load的Data，设置默认值的时候，会自动去按顺序获取远程数据吗，可以直接拿文档里的案例试试：
https://codesandbox.io/s/dongtaijiazaixuanxiang-ant-design-demo-forked-i1tjv?file=/index.js
很显然，只会加载出option的第一层，同理，formItem的intialVal设置这个值也不会去请求

然后那个onChange失效的问题这里我放弃提问，我在Form+Form.Item没有复现，在Pro组件里的ProFrom + Form.Item会出现，但是现在在CasCader下面再加一个任意隐藏元素，onChange又有效了

**Comment by afc163** [comment]
loadData 是交互触发的，不会自动运行。

**Comment by Augustzyh** [comment]
所以这种远程数据的情况该如何更方便的回显呢，不知道现在有没有，是都需要开发人员自行封装获取option的函数吗，是不是可以考虑吧这个回显逻辑封装在内部，只让开发人员获取第一层的option，随后组件内部用loadData的值结合defalutValue和initialValue去获取当前的option树，不知道是不是我没有找到文档对应的解决方案，使用的时候都会进行二次封装

**Comment by afc163** [comment]
https://github.com/ant-design/ant-design/issues/6761#issuecomment-489890685

可能是个解决方式。

**Comment by afc163** [comment]
看了下不是非常不好解决，相关 issue：#16968

一个不完美的解决方法是：https://codesandbox.io/s/dongtaijiazaixuanxiang-ant-design-demo-forked-j680l?file=/index.js

**Comment by Grafaceio** [comment]
应该要支持像select组件的labelInValue

**Comment by dasoncheng** [comment]
这个issues没有后续了吗？

**Comment by Augustzyh** [comment]
自己递归封装了一个后台加载的先用着，但因为各接口逻辑可能有很多差别，props还不是很友好还没有提，自己二次封装也是能解决的，等官网团队的迭代吧

**Comment by kyrie1103** [comment]
Is there a better solution for this issues?

**Comment by YqxLzx** [comment]
这么棘手和频繁的问题,居然没后续了

**Comment by YqxLzx** [comment]
> setFieldValue

setFieldValue怎么能够解决异步数据的问题，异步是丢失了label，而不是值。

**Comment by YqxLzx** [comment]
我利用displayRender这个属性算是解决了，还得是一一去匹配，然后通过displayRender来渲染

**Comment by coderzhizi** [comment]
2024年了
