### ISSUE TITLE
Dropdown cannot use

### ISSUE THREAD

**Issue by cc616** [ant-design/ant-design#27544]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/jiben-ant-design-demo-forked-hnn7r?file=/package.json)

### Steps to reproduce
直接预览

### What is expected?
能够正常渲染页面

### What is actually happening?
页面报错，提示React.Children.only expected to receive a single React element child.

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 16.12.0 |
| System | macOS |
| Browser | Google Chrome 80.0.3987.87 |

**Comment by afc163** [comment]
包一个 span：`<Dropdown overlay={menu}><span>测试测试</span></Dropdown>`。

https://codesandbox.io/s/jiben-ant-design-demo-forked-x2ixh
