### ISSUE TITLE
InputNumber 格式化金额时 只输入4位 会自动补充为5位

### ISSUE THREAD

**Issue by dengshijian** [ant-design/ant-design#27554]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://ant.design/components/input-number/#components-input-number-demo-formatter](https://ant.design/components/input-number/#components-input-number-demo-formatter)

### Steps to reproduce
InputNumber 的格式化金额示例输入4位数字

### What is expected?
正常显示

### What is actually happening?
显示5位数字

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | react |
| System | win 10 |
| Browser | google 86.0.4240.111 |

**Comment by WangJM001** [comment]
什么问题后来查了么？出现同样问题了

**Comment by WangJM001** [comment]
不是我本地出现的，不好重现

**Comment by dengshijian** [comment]
问题出现时间很短暂,过了一会自动就好了,暂时不知道问题出现得原因




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ant-design/ant-design"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月9日(星期一) 中午12:00
收件人:&nbsp;"ant-design/ant-design"<ant-design@noreply.github.com&gt;;
抄送:&nbsp;"邓铈舰"<384122988@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ant-design/ant-design] InputNumber 格式化金额时 只输入4位 会自动补充为5位 (#27554)





 
不是我本地出现的，不好重现

**Comment by 445339805** [comment]
@dengshijian    微软中文输入法下必现，chrome版本 86.0.4240.193，输入第四位会变5位，再输入下一位会增加3位。

**Comment by WangJM001** [comment]
> @dengshijian 微软中文输入法下必现，chrome版本 86.0.4240.193，输入第四位会变5位，再输入下一位会增加3位。

确实 谷歌中文输入法下也可重现

**Comment by 445339805** [comment]
>@dengshijian 问题很大，能不能协助解决下，formttter加载两次，第二次拿到的是错误的值

**Comment by liyang0612** [comment]
都这么久了竟然一点反馈和解决方案都没有

**Comment by Dolov** [comment]
> 都这么久了竟然一点反馈和解决方案都没有

这个问题今天捯饬了半天，倒也不是 antd 的问题，原生 js 实现千分位分割也会有这样的问题。

windows 下中文状态会触发两次 onChange ，两次的回调值是相同的。（猜测会做一个合并）
但是由于千分位分割时插入了 ” ，“ 号，导致第二次回调的合并结果出现了异常。（瞎猜的）
想了两个临时的解决方案。
1. 对比两次 onChange 的时间差，windows 下中文状态的自动触发的时间差大概在 10 ms 内，如果小于这个时间则 return  
    但是集成在实际的应用中时间差应该会被放大。不推荐
2. 延时执行 formatter 操作，需要更改源码
```js
onChange = e => {
    const { onChange } = this.props;

    if (this.state.focused) {
      this.inputting = true;
    }
    this.rawInput = this.props.parser(this.getValueFromEvent(e));
    // this.setState({ inputValue: this.rawInput });
    setTimeout(() => {
      this.setState({ inputValue: this.rawInput });
    }, 0)
    onChange(this.toNumber(this.rawInput)); // valid number or invalid string
  };
```

**Comment by yoyo837** [comment]
防抖节流？

**Comment by Dolov** [comment]
> 防抖节流？

差不多吧，就是先让两次 onChange 执行完毕之后再进行 formatter 千分位分割的操作

**Comment by yoyo837** [comment]
有兴趣来个PR吗？给它节流一下试试看...
