### ISSUE TITLE
Antd components freezing in concurrent mode

### ISSUE THREAD

**Issue by Daidalos117** [ant-design/ant-design#27552]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/agitated-feather-bu40g)

### Steps to reproduce
1) Install experimental React and use concurrent mode
2) Import some Antd component (select)
3) Try to use component
4) Browser get freezed

### What is expected?
To work normally.

### What is actually happening?
Tab is freezed, needs to be killed.

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 0.0.0-experimental-7f28234f8 |
| System | Doesnt matter/MacOS 10.15 |
| Browser | Doesnt matter/Chrome |

---
This is real pain for me now, cause I bought Dashboard template based on Antd and wanted to use it in Blitz.js (which is based on experimental React). Is this worked on? Or should I give up using antd in this case?

**Comment by afc163** [comment]
Trace #13308 and #26136

**Comment by Daidalos117** [comment]
Hm, not solved for 2 years. I suppose I can't use antd then.

**Comment by afc163** [comment]
@Daidalos117 Could you help us for concurrent mode?

**Comment by RichardSPrins** [comment]
Was there any solution to this issue yet? I am using BlitzJS as well, and my app freezes when using the select in the Calendar Component.

**Comment by Lucheti** [comment]
Reading this issue a few months ago would have saved me a few facepalms.... Any news in here?
for those using blitz setting
`module.exports = { experimental: { reactRoot: false, }, }
`

in the blitz config file does the job

**Comment by xtealer** [comment]
Same issue with React 18

**Comment by NotCJSBirdie** [comment]
same issue here, antd table header don't work fine with React 18

**Comment by ofelia-bb** [comment]
Had an issue with Antd datepickers and select , fixed by adding this:

```
"resolutions": {
  "rc-tooltip": "5.3.1",
  "rc-picker": "2.6.9",
  "rc-trigger": "5.3.4"
}
```

"react": "^18.3.1",
"antd": "4.24.12",
