### ISSUE TITLE
one way transfer list

### ISSUE THREAD

**Issue by pran2871** [ant-design/ant-design#27556]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/transfer/demo/oneWay.md](https://github.com/ant-design/ant-design/blob/master/components/transfer/demo/oneWay.md)

### Steps to reproduce
just execute in normal way

### What is expected?
one way transfer list

### What is actually happening?
normal transfer list

| Environment | Info |
|---|---|
| antd | undefined |
| React | v17 |
| System | Mac |
| Browser | Any |

---
The code mentioned there  is not associated to one way transfer list

**Comment by afc163** [comment]
See https://ant.design/components/transfer/#components-transfer-demo-oneWay

**Comment by pran2871** [comment]
<img width="576" alt="Screen Shot 2020-11-04 at 11 57 15 PM" src="https://user-images.githubusercontent.com/72671337/98199666-b5c1d080-1ef9-11eb-995b-6bfa9cf68188.png">
when I tried to run code for one way transfer I am getting this output that's the reason I raised issue

**Comment by pran2871** [comment]
Can you please correct the code for oneway transfer list

**Comment by afc163** [comment]
@pran2871 If you are using antd 3, pleae refer to https://3x.ant.design/components/transfer/
