### ISSUE TITLE
能否提供一个与表格关联的高级搜索的模板，支持字段搜索（字符串和日期）

### ISSUE THREAD

**Issue by zhanglianghui** [ant-design/ant-design#2755]
请问各位大牛有没有现成的模板啊，在http://ant.design/docs/pattern/advanced-search里面没有示例代码

**Comment by afc163** [comment]
You can find some demos [here](https://github.com/ant-design/ant-design/tree/design-pattern/docs/pattern/table/demo) for now

**Comment by yh201407** [comment]
同上, 网站模式里的案例能不能提供一下源代码? 只凭组件里的demo, 和简短的API, 实际用起来真的很费劲
