### ISSUE TITLE
we have only color for tooltip why not add background color property ?

### ISSUE THREAD

**Issue by zeden** [ant-design/ant-design#27553]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
We can customize tooltip as we want, thank's a lot

### What does the proposed API look like?
the api propose  color but not background property ?

**Comment by afc163** [comment]
It is background color but named as `color`.

https://ant.design/components/tooltip/#components-tooltip-demo-colorful

**Comment by zeden** [comment]
yes , I know but how can i make a tooltip with backgroud white and font black for example.
Thank's
