### ISSUE TITLE
Upload组件事件参数fileList不正确

### ISSUE THREAD

**Issue by necessityOVO** [ant-design/ant-design#27558]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://stackblitz.com/edit/react-d5m7eb?devtoolsheight=33&file=index.js](https://stackblitz.com/edit/react-d5m7eb?devtoolsheight=33&file=index.js)

### Steps to reproduce
首先上传非image类型文件`console.log`为`false`，表示上传中断，再次上传image类型文件打印了`true`和`fileList`

### What is expected?
打印的fileList应该只有第二次上传成功的image类型的文件

### What is actually happening?
再次上传image类型文件时onChange事件的fileList仍然有第一次上传失败的文件，

| Environment | Info |
|---|---|
| antd | 4.8.0 |
| React | 17.0.0 |
| System | win10 |
| Browser | Google Chrome 86.0 |

---
我认为上传失败fileList里就不应该再有失败的文件了，不然每次都得在失败时执行`fileList.pop()`手动执行清除失败文件，不然下一次的`setState`会导致失败的文件显示在照片墙上，如是我用法不对，麻烦指出

**Comment by LiteSun** [comment]
或许你应该限制上传文件的类型以限制用户上传错误格式的文件？

![image](https://user-images.githubusercontent.com/31329157/98202937-0c68f200-1f6e-11eb-9671-338e0da84f97.png)

**Comment by afc163** [comment]
Duplicate of #15561
