### ISSUE TITLE
cant show local files in assets folder

### ISSUE THREAD

**Issue by barron9** [ant-design/ant-design#27555]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://yok](http://yok)

### Steps to reproduce
./assets/logo.png 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

### What is expected?
show local image

### What is actually happening?
      <img src={require('./../../assets/logo.png')} /> returns error 

| Environment | Info |
|---|---|
| antd | undefined |
| React | 16 |
| System | ant design |
| Browser | opera |

**Comment by afc163** [comment]
It is not antd components issue.
