### ISSUE TITLE
Steps步骤条当Step过多时，能否在中间加上一个省略标志，点击标志后展开

### ISSUE THREAD

**Issue by togetherEnjoy** [ant-design/ant-design#27562]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
当步骤条过多时，排布过于拥挤，收集一部分Step，点击时可以展开折叠

### What does the proposed API look like?
无

**Comment by afc163** [comment]
步骤条过多是不是应该用垂直的更好？
